### ISSUE TITLE
odd menu look

### ISSUE THREAD

**Issue by sigod** [telegramdesktop/tdesktop#100]
Sometimes menu looks like this:
![screenshot 2014-08-06 15 10 05](https://cloud.githubusercontent.com/assets/1175750/3826512/deb6d2c8-1d62-11e4-9bb1-fe55794597c3.png)

I'm not sure why that happens and how to reproduce this behavior. I've seen this bug periodically for a long time.

Windows 7, x64
v0.5.13

**Comment by telegramdesktop** [comment]
Hope it won't be in Win7 anymore.
