### ISSUE TITLE
[Feature Request] Disable Cloud Draft sync

### ISSUE THREAD

**Issue by AhyaH-YHWH** [telegramdesktop/tdesktop#10001]
many of TDesktop Bugs are related to cloud draft constantly being synced 

like overwriting typing message, and heavier ram usage and crash at start

I suggest adding an option for each chat to disable cloud draft sync there, or disabling it totally in app

**Comment by ilya-fedin** [comment]
>  and heavier ram usage and crash at start

RAM usage has nothing to do with drafts. And what crash at start are you talking about?

**Comment by AhyaH-YHWH** [comment]
It happens to me many times, I open TDesktop, and I should leave it in first minute or 2 Minutes, when it is reading message

If I start typing in a chat right after TDesktop loads chats, it will freeze the app for more time, and has happened some times app crashed because I was in hurry. 4GB of ram, Windows 10 x64, 20H2

**Comment by ilya-fedin** [comment]
It is unlikely that it is due to drafts. You should post crash report tag here if you want to report the crash.

**Comment by Younes-L** [comment]
@AhyaH-YHWH try using this fork [TDesktop-x64](https://t.me/tg_x64) to see if disabling cloud sync for drafts makes a difference for you (latest release on [GitHub ](https://github.com/TDesktop-x64/tdesktop) might have bugs, see their telegram channel for newer builds)

I doubt the two are linked but it's interesting to  note that the timing of this issue coincides with the addition of [Disable Cloud Draft Sync To Local](https://github.com/TDesktop-x64/tdesktop/commit/89daa53ced22f0f88bdfc4838389e13d3bdfb7ff)
