### ISSUE TITLE
[Question] Why is date format on TDesktop hardcoded?

### ISSUE THREAD

**Issue by Akyh** [telegramdesktop/tdesktop#10006]
Why is date format on TDesktop hardcoded and cant be customized for other standards?

I thinh the best way for use date format is string as is done on Android. That alows translators to put right date format in translation .

On TDesdktop there is no string for that, and app also dont use date format from system. That is not good.
<img width="713" alt="Izrezak" src="https://user-images.githubusercontent.com/76448476/103134489-bed94d80-46b1-11eb-8f5e-459c7fa615e3.PNG">

**Comment by ilya-fedin** [comment]
#618

**Comment by Akyh** [comment]
> #618

Oh, that is not good. The same is also on iOS. I dont know why. Its so annoying.
