### ISSUE TITLE
[Question]  Where does Tdesktop store the voice message record before it get uploaded!?

### ISSUE THREAD

**Issue by MohamedLamineAllal** [telegramdesktop/tdesktop#10009]
It happened a lot for me! Telegram crash while i'm  voice recording! Sometimes i would have recorded for minutes! And because of a crash! All is lost!
Does telegram save all in memory! Or to disk! And is there a way to recover it in case of a crash (directly after the crash) ?

Another question! Can any one help me find the line of code or section that is responsible for recording voice messages! So that i make my own version where i can save the voices to disk! if it's not! And have them easily recorded!

Such a feature can be too nice! Write to disk! And recover automatically in case of a crash! And that at the start of the app!
If i'll get some orientation i'll implement such a feature !

**Comment by john-preston** [comment]
Yes, they're stored in memory before being sent, so sorry, they're lost.

What OS do you use? Version of tdesktop?

**Comment by MohamedLamineAllal** [comment]
I'm on Linux Debian ! And i was on version 1.8.15! I just updated! It may be an unhandled exception!

If you can orient me to the relevant files and directories (directories) i would appreciate it!

Otherwise what about adding the feature of making it persist to disk ! Or just in case of crash! Save it do disk!
Well for the later i'm not sure about it! I don't know how it's crashing! Telegram become irresponsive! I use gnome as desktop environment ! I get promoted to Wait or kill it! Waiting do nothing! Does is it always come from within Telegram app ! Can every exception be catched or There is some things that can happen at os level! And i don't know what are the possibilities in such case! Self healing may be!

But the persisting  to disk is always possible! I'm curious about how writing to disk and in memory compare! Clearly it will be faster! But it's something that pause problem to disk! And not loosing the recording is something too important and interesting! For instance if you kill telegram ! connection interruption then computer shutdown! ...etc! It gonna give more flexibility and a better experience (offline experience too)! And telegram is already doing highly at all kind of levels!

Thank you a lot! Would the team consider such a feature!
Also I'm willing to work on it (At least for myself)!
Thank's again!
