### ISSUE TITLE
Inconsistency in the Number of Participants

### ISSUE THREAD

**Issue by i4081i** [telegramdesktop/tdesktop#10008]
The same issue is mentioned in #9992 .

### Steps to reproduce
Join a group voice chat.

### Expected behaviour
The list and number of participants should be consistent.

### Actual behaviour
More people appear in the list than the number indicated at the top. The list is shown correctly in the mobile version.

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 2.5.1

[log.txt](https://github.com/telegramdesktop/tdesktop/files/5742145/log.txt)
![SCREENSHOT_ANDROID](https://user-images.githubusercontent.com/74790565/103138021-3d001900-46df-11eb-8fe4-42615db93f7c.jpg)
![SCREENSHOT_WINDOWS](https://user-images.githubusercontent.com/74790565/103138022-3d98af80-46df-11eb-9b3a-e2b7da36f247.jpg)

**Comment by ilya-fedin** [comment]
> The same issue is mentioned in #9992 .

What is the point of having two issues for one problem?

**Comment by i4081i** [comment]
Just re-started Telegram Desktop and now the problem is solved.

**Comment by i4081i** [comment]
The issue appears to be solved after you re-start the client, but it becomes available again. Therefore, you have to constantly re-start Telegram.

**Comment by ilya-fedin** [comment]
It is still a duplicate
