### ISSUE TITLE
[Feature Request] Integrate with the System Media Transport Controls on Windows

### ISSUE THREAD

**Issue by yunfandev** [telegramdesktop/tdesktop#10004]
### Is your feature request related to a problem?
When playing music or video, integrate with the System Media Transport Controls on Windows

like this:

![image](https://user-images.githubusercontent.com/8027453/103131913-b991f800-46dd-11eb-866e-9dab76b73aaa.png)

### Describe the solution you'd like

[Integrate with the System Media Transport Controls](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/integrate-with-systemmediatransportcontrols)

**Comment by ilya-fedin** [comment]
> Integrate with the System Media Transport Controls

This is UWP API, while tdesktop is a Win32 app

**Comment by yunfandev** [comment]
@ilya-fedin Hi, Chrome also was a Win32 app, but chrome seems support System Media Transport Controls. For example, you can try open [this link](https://www.youtube.com/watch?v=Au-rrY0afe4) in chrome on Windows 10.

![image](https://user-images.githubusercontent.com/8027453/103139003-a8171300-4712-11eb-859d-9ed2d76f01e6.png)

There is a way to [Call Windows Runtime APIs in desktop C++ apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance#modify-a-c-win32-project-to-use-windows-runtime-apis). 😁😁😁

**Comment by phanirithvij** [comment]
I think this can be closed as it was implemented.
