### ISSUE TITLE
Computer stucks while using Telegram Desktop

### ISSUE THREAD

**Issue by brookite** [telegramdesktop/tdesktop#10003]
### Steps to reproduce
I did not understand how to reproduce the problem, this happens under incomprehensible circumstances (possibly related to video or photo content)

### Actual behaviour
Under certain actions, the application, and with it the entire operating system, freezes. At the same time, a HDD light on the system unit is actively lit. The solution to the problem is to restart the device. I think it has something to do with excessive use of RAM and hard disk

### Configuration
**Operating system:** Windows 10 32bit
**RAM**: 2 GB

**Version of Telegram Desktop:** 2.5.1

**Comment by Mehrshad3** [comment]
I guess these 2 issues are related.

**Comment by brookite** [comment]
Actually on 2.5.8. It seems to be related to video avatars in channels
