### ISSUE TITLE
[Question] How to disable GPU rendering, and just use CPU? 

### ISSUE THREAD

**Issue by umbertov** [telegramdesktop/tdesktop#10019]
Hi, lately i have been using my GPU for intensive computations (maximizing both VRAM and usage), and using telegram desktop is often a problematic task, because it seems to make heavy use of the GPU for rendering... well, everything. When the GPU is heavily used, loading a single chat takes some seconds, and i can see the screen being loaded progressively, row by row, left to right.

I looked up on the internet and there seem to be some Electron command line arguments like `--disable-gpu` and `--force-cpu-draw`, but they seem to be happily ignored by telegram. I've been trying to see if there is an help section with `telegram-desktop --help`, but i found that whatever argument i pass to `telegram-desktop` is always ignored, and Telegram desktop just starts unconditionally.

Using other desktop applications works fine, including web browsing (chromium/firefox, including using web.telegram.org interface, which has bad UX tbh) and pdf viewing.
I'd just like to find a way for Telegram desktop to be rendered using the CPU, whose usage isn't maxed out, but I can't seem to find a way.

Thanks in advance for any answer.

I doubt it is relevant, but for the sake of completeness, my setup is:
Arch Linux, linux-lts 5.4.85-1
Telegram Desktop 2.5.1-1 from official arch repos
RTX 2080 ti
i5-6400

**Comment by ilya-fedin** [comment]
No, tdesktop performs all computations on CPU. Rendering of UI, color space conversion, video frames scaling, video decoding - all is done on CPU, there's no usage of OpenGL, VA-API, VDPAU and etc.
