### ISSUE TITLE
[Feature Request] Keybind for toggling microphone

### ISSUE THREAD

**Issue by t3ddyss** [telegramdesktop/tdesktop#10013]
Would be cool to have an option to toggle microphone's transmission on and off like in Discord using keybind

**Comment by john-preston** [comment]
@t3ddyss You can enable system wide push to talk shortcut in Settings or use Space inside the call window.

**Comment by DarkArc** [comment]
@john-preston that's great. However this is a bit different, it's nice to be able to have your mic in a "voice activation" type recording mode, and be able to quickly stop recording. An example use case is going AFK, while in a full screen game.

With this proposed feature:
1. In a full screen game, the pizza guy rings the doorbell
2. Pause the game
3. Press your chosen shortcut (e.g. `meta + M`)
4. Get your pizza

Without this feature:
1. In a full screen game, the pizza guy rings the doorbell 
2. Pause the game
3. Tab out (or close the game if not possible)
4. Select the telegram voice chat window via window cycling or via the mouse
5. Click the mute mic button
6. Get your pizza

This can also be useful in more professional environments (e.g. you're in another window, a child starts screaming the background and you want to mute this (obviously) as fast as possible)
