### ISSUE TITLE
[bug] Chat list limit

### ISSUE THREAD

**Issue by tguser13** [telegramdesktop/tdesktop#1001]
Old chats seem to just disappear at the bottom of the chat list.
If someone write in the chat they appear again so they are not removed just not visible.
Probably another useless hard-coded limit around 500.
Older chats are not loaded if I scroll down.

**Comment by auchri** [comment]
I can't find such a limit in the source code, but you can find old conversations using the search function :)

**Comment by telegramdesktop** [comment]
Soon it will be 1000 after launch and then other 1000 each 30 seconds, not faster. It is a server-side flood-control, so I can't do anything with that (except saving everything on hdd between launches, but this won't be done soon + it does not fix that issue when you just logged in to your account).
