### ISSUE TITLE
[Bug] Too high memory usage in linux when starting group call

### ISSUE THREAD

**Issue by smaznet** [telegramdesktop/tdesktop#10018]
Hello i tried call on windows and linux 
in windows i got this usage

![image](https://user-images.githubusercontent.com/10239885/103172199-005f2980-4867-11eb-98bc-84b6fedec1fe.png)

in linux i got this

![image](https://user-images.githubusercontent.com/10239885/103172211-24bb0600-4867-11eb-8cec-d2b4bb3ae974.png)

Both using one account on same group

**Comment by alefvanoon** [comment]
![image_2020-12-29_19-21-00](https://user-images.githubusercontent.com/53198048/103304120-072f9d00-4a1d-11eb-8d5d-af32bf00e1e3.png)
also CPU usage
