### ISSUE TITLE
Is block not supposed to block messages in groups?

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#10012]
Hi there,

I just blocked someone & when I wrote something in a group that he was also a member of, he saw what I wrote.

This caused him to threaten me.

I'm not happy he was able to see what I wrote.

**Comment by ilya-fedin** [comment]
No, it's not

**Comment by ILoveSkilledCoders** [comment]
Well, can you make that a feature request?

When I block someone on other SM sites, they can't see anything I type.

Thanks

**Comment by RememberTheAir** [comment]
You can upvote this suggestion: https://bugs.telegram.org/c/37

This feature is something that needs to be supported platform-wise, so it's out of the scope of this repository

**Comment by ILoveSkilledCoders** [comment]
I can't upvote or comment. It keeps asking me to log in & I enter in my number & I get no text. :(

So is this a bug or a feature request?

**Comment by ILoveSkilledCoders** [comment]
Ok, done, but why does it say my account isn't allowed to report a bug or offer a feature request?

Thanks
