### ISSUE TITLE
Telegram crashes in Gentoo Linux after clicking on any conversation

### ISSUE THREAD

**Issue by domaingood** [telegramdesktop/tdesktop#10016]
teps to reproduce
Download the official Linux binary (on amd64)
In a conversation, send an image
Hover the mouse over the filepicker to focus it.
Expected behaviour
The window should gain focus.

Actual behaviour
Telegram crashes.

Configuration
Operating system: Gentoo 5.4.81

Version of Telegram Desktop: 2.4.11

**Comment by ilya-fedin** [comment]
Current latest version is 2.5.1
