### ISSUE TITLE
Chats appear on the same side unless the window's width is lowered. 

### ISSUE THREAD

**Issue by MidhunrajXYZ** [telegramdesktop/tdesktop#10024]
### Steps to reproduce
1. Maximize or increase the width of the chat window (to about > 1000 pixels)

### Expected behaviour
Chats of my friend should be aligned to the left side and that of mine should be aligned to the right side. 

### Actual behaviour
All the previous chats are aligned to the left side only.

### Configuration
**Operating system: Arch Linux** (My friend is using Windows 10, having the same issue as well)

**Version of Telegram Desktop:**
2.5.1

**Installation source (Linux Only)** -  AUR repository

**Used theme**: Night mode

When the width is higher:
![20201229_083547](https://user-images.githubusercontent.com/50173278/103256239-77ed9f80-49b2-11eb-8798-cc2214f8dc40.png)

When width is less: (works normally)
![20201229_084143](https://user-images.githubusercontent.com/50173278/103256252-863bbb80-49b2-11eb-851e-bc590d8645ca.png)

**Comment by ilya-fedin** [comment]
not a bug

**Comment by MidhunrajXYZ** [comment]
wait, it is intentional? But then wouldn't this make confusion? Especially when going through a group chat.

What is the usage of moving the user chat to the left side upon increasing the width of the window?

**Comment by ilya-fedin** [comment]
this is called "adaptive layout", it is implemented to avoid moving eyes on big screens AFAIK

**Comment by Aokromes** [comment]
> wait, it is intentional? But then wouldn't this make confusion? Especially when going through a group chat.
> 
> What is the usage of moving the user chat to the left side upon increasing the width of the window?

you can disable the setting when having telegram maximized.

**Comment by MidhunrajXYZ** [comment]
If that is a concern, instead of snapping the user's chat to the left after a threshold width, perhaps make it stay at that place would be less confusing I guess. 

I meant something like the following:
![20201229_084143_mod](https://user-images.githubusercontent.com/50173278/103267620-e55ff700-49d7-11eb-9ebf-590978c6d1fa.png)

**Comment by MidhunrajXYZ** [comment]
> you can disable the setting when having telegram maximized.

There is a setting for that? I cannot find it.

**Comment by Aokromes** [comment]
on chat settings, adaptative layout.

**Comment by MidhunrajXYZ** [comment]
oh ok. I was being ignorant and didn't see the "...when having telegram maximized" part of your message.
