### ISSUE TITLE
Caption is sent as a separate message when sending webp image

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#10029]
### Steps to reproduce
1. Go to a webpage with webp images, e.g. https://developers.google.com/speed/webp/gallery1
2. Right-click any webp image -> Copy image
3. Paste image to Telegram, write some comment (caption) and send it.

### Expected behaviour
Webp image should be sent as image with caption

### Actual behaviour
Caption text is sent as a separate message right before the image itself

### Configuration
**Operating system:** Windows 10, Firefox 84.0.1
**Version of Telegram Desktop:** 2.5.2 beta

**Comment by Xeddius** [comment]
Webp images aren't sent as "images" they're sent as Stickers, much to our dismay, the developers seem incapable or unwilling of fixing this issue. There should be an option to select if you want to send webp as image or as a sticker, but instead we are told over and over again to nerf our browser settings and block webp or to convert the files before sending them along with other unreasonable and unfavorable ideas. webp sends as a regular image on other platforms like telegram-web. I've been discussing with a few people the idea of forking telegram desktop and migrating away from the webp-to-sticker stupidity and improving quality-of-life for other desktop users.

**Comment by jonata** [comment]
Maybe related: #16312

**Comment by soredake** [comment]
Not stale.

**Comment by john-preston** [comment]
@soredake webp images are displayed as stickers in all Telegram apps, they can't have captions :(

**Comment by john-preston** [comment]
Maybe there should be a "Compress image" checkbox and if it's checked then the image is sent as a jpg photo and has a caption inside 🤔

**Comment by soredake** [comment]
> @soredake webp images are displayed as stickers in all Telegram apps, they can't have captions :(

I know, that's unfortunate.

**Comment by RememberTheAir** [comment]
> Maybe there should be a "Compress image" checkbox and if it's checked then the image is sent as a jpg photo and has a caption inside 🤔

That would be great! Such an option has been suggested in #6276 too (which is the oldest/most popular discussion about webps being sent as stickers), but personally I've always assumed tdesktop wasn't offering it because the mobile apps behave in a different way

**Comment by soredake** [comment]
> Maybe there should be a "Compress image" checkbox and if it's checked then the image is sent as a jpg photo and has a caption inside 🤔

This would be nice!

**Comment by Neurotoxin001** [comment]
Fixed https://github.com/telegramdesktop/tdesktop/commit/3467fe226ff0e640d4ed68d642a7e710c352562c
