### ISSUE TITLE
Microphone not working, but works on voice messages

### ISSUE THREAD

**Issue by Akyh** [telegramdesktop/tdesktop#10028]
Microphone doesnt work in voice chat but when I record one voice message then it work for only one session

2.5.2 beta

Here is video.
https://t.me/TelegramDesktopTalk/54530

**Comment by Akyh** [comment]
LOGS:

https://t.me/TelegramDesktopTalk/54605

**Comment by iman-sedgh** [comment]
same Here

**Comment by sirfz** [comment]
Even setting the microphone in the advanced call settings doesn't make a difference

**Comment by Akyh** [comment]
> Even setting the microphone in the advanced call settings doesn't make a difference

Did you try newest beta 2.5.6. Works there

**Comment by sirfz** [comment]
> 
> 
> > Even setting the microphone in the advanced call settings doesn't make a difference
> 
> Did you try newest beta 2.5.6. Works there

Same problem, other party doesn't hear me at all

**Comment by john-preston** [comment]
@sirfz 🤔 2.5.6 uses the same code for voice messages recording and calls and voice chats, so that's strange. Are you sure you've tested that version/

**Comment by sirfz** [comment]
@john-preston yes, using 2.5.6. I had the input/output devices set in Windows advanced sound options. I changed them back to default and test voice call, it's working now.

**Comment by ilya-fedin** [comment]
Is this still valid?

**Comment by Akyh** [comment]
> Is this still valid?

I think it is
