### ISSUE TITLE
[Feature Request] random music

### ISSUE THREAD

**Issue by MEGASUPERSPY** [telegramdesktop/tdesktop#10023]
Hello, can I please add **random music** playback to the PC version, Telegram has been playing for many years (_we all love it very much_), but on the PC version ... there are still no functions. For example, channel statistics. Thank you very much for all your efforts and work! Sincerely, Alexander.

--------------------------------

Здравствуйте, можно пожалуйста на ПК версию, добавить **случайное воспроизведение музыки**, Телеграму уже очень много лет (_мы все его очень любим_), но на ПК версии... все так нету каких-то функций. Например статистика канала. Спасибо большое Вам, за все Ваши старания и работу! С уважением, Александр.

**Comment by ilya-fedin** [comment]
#4640
