### ISSUE TITLE
Use standard icon locations in linux

### ISSUE THREAD

**Issue by bil-elmoussaoui** [telegramdesktop/tdesktop#1002]
Well, 
i think that icons should not be placed in the same folder as the desktop file, there's a standard location for applications/indicator icons in linux; which make it possible for designers to create icons themes for each application

the icons can be placed in `usr/share/icons/` or in `.local/share/icons`, you can have more informations here 
[freedesktop standards](http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html)
[Icon naming in Gnome](https://developer.gnome.org/icon-naming-spec/)

**Comment by lucaciavatta** [comment]
I hope too because, every time Telegram has an update, I must rewrite the telegram.desktop file to put the correct path of the theme icon. I think it's a good idea to follow the standard guidelines. Thanks.

**Comment by MichaelTiebesl** [comment]
@lucaciavatta I don't have that with Arch Gnome 3.18. Every update from Telegram i remove in home in /home/nameuser/.local/share/applications the telegram desktop to get the original Icon again.

**Comment by auchri** [comment]
I think that's fixed by #1431, thx @L0L022 !!
