### ISSUE TITLE
uploading compressed file is freezed at the end of uploading 

### ISSUE THREAD

**Issue by amindadgar** [telegramdesktop/tdesktop#10022]
### Steps to reproduce
1. Open telegram desktop (windows)
2. compress a video file with winrar ( configs= Dictionary Size is 256mb, best compression method and create solid archive )<br>
 _Info: the video file size is about 85 mb and compressed size is 80 mb_
3. send the compressed file into a group ( 49 members not a super group ).

### Expected behaviour
the file start uploading and after some time it would be uploaded in some time.

### Actual behaviour
the file started uploading normally, But at the end of the uploading ( when there are some bytes till the end of upload ) uploading freezes. 
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.4.2

**Used theme**:
day

**Comment by navidmafi** [comment]
i have some kind of this problem with sending photos or files with Proxy
i think it's because of some reason it make a verification process to ensure the file uploads correctly ( maybe not )
but with proxies something goes wrong and it takes longer
so I can confirm this issue
