### ISSUE TITLE
[Question] Why there is no "Linux 32 bit: Binary" release in new releases?

### ISSUE THREAD

**Issue by alihardan** [telegramdesktop/tdesktop#10037]
Is releasing 32 bit binary for Linux stopped forever?

**Comment by ilya-fedin** [comment]
32-bit is deprecated since 2020 December 01

**Comment by alihardan** [comment]
@ilya-fedin, Can we still compile the newest version of it on 32 Bit Linux?

**Comment by ilya-fedin** [comment]
I don't know, no one checks if the app compiles on anything than x86_64 on Linux
