### ISSUE TITLE
Потеря текста после воссоединения интернета

### ISSUE THREAD

**Issue by keworr** [telegramdesktop/tdesktop#10032]
Если ты набираешь какой-то текст в диалоге и телега переподключается/пропадает интернет, то после переподключения произойдёт потеря текста, который ты успел набрать в момент этой загрузки/пока не было интернета. 

Трабла на ubuntu, но думаю актуально везде

**Comment by ilya-fedin** [comment]
#4922

**Comment by ilya-fedin** [comment]
please note that this bugtracker is english only

**Comment by keworr** [comment]
If you type some text in the dialogue and Telegram reconnects/the Internet disappears, then after reconnection, the text you typed at the time of this download/while there was no Internet will be lost.

Trouble on ubuntu, but I think it's relevant everywhere
