### ISSUE TITLE
High CPU on update (GNU/Linux)

### ISSUE THREAD

**Issue by vitaminace33** [telegramdesktop/tdesktop#1003]
Hi there!

I've noticed (already 6 months ago, at least) that tdesktop goes from idle to "high" CPU consumption when and update is available. Clicking on the update button makes tdesktop going back to idle.

Note: when I say "high", it is not an absolute "high", but a relative one. In this case, tdesktop consumes 5% of one of my cores, which is undoubtedly high for doing nothing.

Telegram Desktop v8.43 on Arch Linux x86_64

**Comment by telegramdesktop** [comment]
I am afraid it is the Update button animation %)

**Comment by vitaminace33** [comment]
¿"animation" you say? the update button image is still. ¿running internally as an animation? it is obviously a quite uncritical bug, but should be corrected I believe.

cheers!

**Comment by telegramdesktop** [comment]
No, it is in window header (when the update is ready) and it highlights from blue to white and back all the time.

**Comment by telegramdesktop** [comment]
To get your attention :)

**Comment by vitaminace33** [comment]
on my system, besides the update button, telegram has no other animation (no flickering, no nothing). using gnome 3.

**Comment by telegramdesktop** [comment]
What do you mean "besides the update button"? I'm talking exactly about animation of the update button.

**Comment by auchri** [comment]
@vitaminace33 This one: ![update](https://cloud.githubusercontent.com/assets/5092164/9325539/52223c1c-4593-11e5-8eb7-163be2514719.gif)

**Comment by vitaminace33** [comment]
@telegramdesktop, soz. When you said "window header", I thought you meant "window title bar" and got confused. Yes, I meant the "Update ↑" button, which I did not realize had a glowing animation. Still, I think the "high" cpu consumption for such animation is a strange behavior. But whatever, I hope you all had a nice summer. Cheerios!!! :D
