### ISSUE TITLE
Change Login Code Message format [Feature Request] 

### ISSUE THREAD

**Issue by navidmafi** [telegramdesktop/tdesktop#10039]
Hi , i want to suggest an idea for login codes messages
when somebody request a code to login to telegram, a message contains login code sends to another clients, right?
and the message formatting is like this:

> Login code: XXXXX. Do not give this code to anyone, even if they say they are from Telegram! .... 

 now my question is ,  if telegram message notification on the phone (for example) is on , even if i have lock screen , 
can another people see this in my lock screen?
![image](https://user-images.githubusercontent.com/46371349/103399506-a86e3e80-4b56-11eb-9800-6b23ba0a9b84.png)
(not real notification , just for explaining)
if they can see this in real , I think it's a bit risky
it could be better if Login Code Message format looks something like this :

> Dear USER-NAME here is your login code , Do not give this code to anyone, even if they say they are from Telegram!
Your code is XXXXX

**Comment by john-preston** [comment]
@navidmafi It was specifically made that way, so you could enter the code just from looking on the notification.
