### ISSUE TITLE
Pin message visual bug

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#10036]
When any channel **that you not admin** pins message it's displays like it's you pin that message (with 2 check marks), for example:
https://t.me/agit_ru/8237
![image](https://user-images.githubusercontent.com/39812401/103366296-491b1a80-4ad3-11eb-8c4e-d73f3a8cb780.png)

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.5.3 beta

**Used theme**: dark default

**Comment by 23rd** [comment]
Is it still occurring?

**Comment by Neurotoxin001** [comment]
2.5.8 seems like fixed it
