### ISSUE TITLE
Profile view showed after click on "Scheduled Messages" label

### ISSUE THREAD

**Issue by slothdeboss** [telegramdesktop/tdesktop#10044]
### Steps to reproduce
1. Schedule message or navigate to already scheduled messages
2. After navigating to scheduled messages screen click on "Scheduled Messages" label
3. User profile view is displayed

### Expected behaviour
I guess it's a bit confusing that click on that label opens user profile view

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.5.3 beta

**Comment by sionghwa** [comment]
我不知道我发生了什么问题
