### ISSUE TITLE
All message align to left instead of seperate by message sent/received

### ISSUE THREAD

**Issue by edmond1992** [telegramdesktop/tdesktop#10049]
### Steps to reproduce
1. Open a chat with message sent/received
2. Pull the chat window wider or make it full screen

### Expected behaviour
Message align separately to left/right by message sent/received
![image](https://user-images.githubusercontent.com/47852799/103438534-c75ff400-4c6e-11eb-990c-2a683a64ba44.png)

### Actual behaviour
Tell us what happens instead
All message aligned to left
![image](https://user-images.githubusercontent.com/47852799/103438550-f24a4800-4c6e-11eb-9936-49c33c569d66.png)

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
V2.5.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
N/A
**Used theme**:
N/A
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
disable adaptative layout on settings chat.
