### ISSUE TITLE
greek characters sent through ifttt bot aren't displayed properly

### ISSUE THREAD

**Issue by patrickdrd** [telegramdesktop/tdesktop#10047]
### Steps to reproduce
1.  create an applet in ifttt to monitor a rss feed or a twitter account containing greek characters
2.  send the results to telegram (action)
3. open any telegram app (android/desktop/web), the result is the greek characters are displayed as following

![image](https://user-images.githubusercontent.com/24896778/103436687-51846a00-4c27-11eb-936b-7b5c4782760b.png)

(the bottom part is the preview)

### Expected behaviour
greek characters should display properly and not with `&alpha;` and `&beta;` etc

### Actual behaviour
greek characters display with `&alpha;` and `&beta;` except the accented characters such as ά, έ, ή etc, these are displayed perfectly fine!
I contacted ifttt as well for the issue and they replied: 

> That's also really useful information regarding the characters with tonos. Just from doing a quick check, I can see that these don't appear to have HTML entities and use decimal and hex codes instead. This may still end up being reliant on how Twitter/Telegram displays these characters

and birdie who helps with ifttt on discord replied:

> the issue what i thought before, telegram decoding symbols on their side, converting them to entitles
> that was seen in test with &alpha;

**Version of Telegram Desktop:**
this happens for a long while, because I had reported it a year and a half back when I had the same problem sending google calendar to telegram with the exactly same results and I think it's time it gets fixed :) 

happy new year!

**Comment by Aokromes** [comment]
not telegram desktop issue.

**Comment by patrickdrd** [comment]
really?
I think it's all telegram issue: Android, desktop and web!!!

**Comment by Aokromes** [comment]
it looks more server side to me.

**Comment by patrickdrd** [comment]
ah.ok not l now I agree

**Comment by ilya-fedin** [comment]
> it looks more server side to me.

This is a IFTTT's bot issue
