### ISSUE TITLE
"Retract vote" button not available in discussion views

### ISSUE THREAD

**Issue by emanuele6** [telegramdesktop/tdesktop#10055]
### Steps to reproduce I
1. Create a poll in a group 
2. Reply to the poll with a message
3. Vote in the poll
4. Right-click on the poll
5. Click "View 1 reply" (or "View \<n\> replies")
6. Now right-click on the poll from this view.   
### Steps to reproduce II
1. Create a poll in a channel with comments enabled
2. Vote in the poll
3. Click on the "Leave a comment" (or "\<n\> comments") button under the poll
4. Right-click on the poll from this view.

### Expected behaviour
I should have the option to retract my vote ("Retract vote") in the context menus of the poll messages when I am in one of these "Discussion" views like in normal channel or chat views.
![image](https://user-images.githubusercontent.com/20175435/103455310-48a99c00-4cec-11eb-96c3-c47df0d4aaae.png)

### Actual behaviour
I don't have that option in the context menu
![image](https://user-images.githubusercontent.com/20175435/103455341-7989d100-4cec-11eb-81c9-4d88b7b95f16.png)

### Configuration
**Operating system:** ArchLinux distribution of GNU/Linux; Linux Kernel version `5.4.85-1-lts`

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: `pacman`

**Used theme**:

**Comment by 23rd** [comment]
Thank you for your report.

**Comment by Mehrshad3** [comment]
I tested it and I had this issue too.
