### ISSUE TITLE
Downloads saved to nonascii dirs can't be opened

### ISSUE THREAD

**Issue by Yanpas** [telegramdesktop/tdesktop#1005]
See also #557 #567 
Downloads saved to nonascii dirs can't be opened (linux). Convert paths to utf-8. Mine destination was ~/Загрузки
![_2015-08-16_19-11-49](https://cloud.githubusercontent.com/assets/7345761/9294082/d4d448fc-444a-11e5-890b-62ce7c0d2960.png)

**Comment by Yanpas** [comment]
I suggest devs to inspect all code for "toLocal8Bit()" and replace it with "toUTF8()" where it is needed.

**Comment by telegramdesktop** [comment]
It has no more toLocal8Bit() for many versions already. Does work fine for me in Ubuntu 12.04, so I'm not sure I can help you with that.

**Comment by Yanpas** [comment]
U say that opening downloaded file located in /home/user/Загрузки/TelegramDesktop doesn't output any error? I'm using XFCE, so my FM is thunar. I'm not sure it's important. Xdg-open are the same for Mint 17.2 and ubuntu 12.04

**Comment by Yanpas** [comment]
Seems like exo-open problem, it doesn't support parsing URIs with %xx

**Comment by Yanpas** [comment]
Problem was in exo-open

**Comment by telegramdesktop** [comment]
@Yanpas Great to hear that it was solved.
