### ISSUE TITLE
Bug of displaying a link in the chat description

### ISSUE THREAD

**Issue by peach-lasagna** [telegramdesktop/tdesktop#10056]
### Steps to reproduce
Chat description screen:
![изображение](https://user-images.githubusercontent.com/59787538/103456858-b37ac780-4d2c-11eb-975a-50be4f4c0a4e.png)
Links to a third-party resource are displayed incorrectly (you cannot click on them and follow it).
But the link with the t.me domain is displayed correctly and you can click on it.

### Actual behaviour
i can click on blue link, which lead to third-party resource.

### Configuration
**Operating system:**
Windows 10
Android 10

**Version of Telegram Desktop:**
2.5.1

**Comment by Aokromes** [comment]
bugged link, not telegram bug.

**Comment by peach-lasagna** [comment]
No! We try to replace link, but it don't work

**Comment by baskiton** [comment]
Confirm. Windows 10, Ubuntu 20.04 third-party links are not displayed correctly.
According to information from other community members, links are displayed correctly on Mac OS X BS.
![image](https://user-images.githubusercontent.com/40061352/103474009-d317fb80-4dd1-11eb-9fbb-bd88c6082fe2.png)
