### ISSUE TITLE
UI bug after "view reply" 

### ISSUE THREAD

**Issue by xaoirse** [telegramdesktop/tdesktop#10051]
### Steps to reproduce
1. Right click on a message that contains two or more line (persian or rtl lang)
2. Select "View 1 Reply"
3. And then press back

### Expected behaviour
Tell us what should happen
![image](https://user-images.githubusercontent.com/32076703/103447088-e628af80-4c9b-11eb-9891-46b9fa3e66ae.png)
Chars go on arrow icon after abow steps

### Actual behaviour
Chars should be next to arrow icon
### Configuration
**Operating system:**
Ubuntu 20.04.1 LTS

**Version of Telegram Desktop:**
2.5.1
**Installation source (Linux Only)**
the official website
**Used theme**:
Tinted
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#9039
