### ISSUE TITLE
Playing a video does not prevent screen from turning off

### ISSUE THREAD

**Issue by hertz98** [telegramdesktop/tdesktop#10057]
### Steps to reproduce
1. Ensure that screen is set to turn off after some time with no acrivity in Power & Sleep
2. Play any video in any chat

### Expected behaviour
Without mouse activity, screen should stay on until the end of video

### Actual behaviour
The video continues to play with the screen off (audio on), preventing the pc from sleep.

![Telegram powercfg](https://user-images.githubusercontent.com/76890016/103470084-c9f54300-4d6d-11eb-8a66-52cc963c434f.png)

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.5.1

**Comment by ilya-fedin** [comment]
#7790
