### ISSUE TITLE
2.5.1 win7 x64

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#10064]
i was typing a long message, someone joined the group and right at that moment i lost half the text of my message in the input field. now i only write long messages in a text editor and then paste to telegram.

fix it already, the issue is from 2.4.3 https://github.com/telegramdesktop/tdesktop/issues/8796

**Comment by imashxtyz** [comment]
damn it, what if i lost something important and not just shitposting?

**Comment by Aokromes** [comment]
duplicate.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4922
