### ISSUE TITLE
[Feature Request] Include active chat name in a Window title

### ISSUE THREAD

**Issue by SilverFire** [telegramdesktop/tdesktop#10067]
For those, who track personal productivity and uses Telegram for both Work & Private communications, it's **impossible to distinguish time spent in different chats**.

### Describe the solution you'd like

It would be really helpful to **include the active chat name in the window title**. Probably, with a switch in the settings for privacy reasons.

Activity tracking programs usually capture window titles to distinguish the activity inside the application.

### Describe alternatives you've considered

Tracking software also relies on File Descriptions opened by a process, but Telegram does not open any special FD, that can identify an open chat.

### Additional context

I use TimingApp for activity tracking. Its developers say that they did not find any possible way to detect active chat inside a Telegram Desktop. However, in Slack, WhatsApp, Skype, iMessage, and probably many others, it works well

**Comment by modestfalcon** [comment]
I wanted to add an identical issue, it's very important to be able to track the window title.

**Comment by Yurapoltora** [comment]
One more here.
Cant track correctly via timingapp the chat activity.

**Comment by JustACatRu** [comment]
Plus one, indeed!

PS: Searched but did not found this issue/request and opened up new one: https://github.com/telegramdesktop/tdesktop/issues/16057 - hope bots and moders will solve this. Sorry.

**Comment by ankostis** [comment]
+1 also, tracking with `arbtt` 9actualy `arbt-capture` gnome-extension, since i'm on `wayland`.

**Comment by PepRoll** [comment]
+1

**Comment by appscaptain** [comment]
Same here. Also need to track. With timingapp.com. Really missing this. And the same goes for call windows for call tracking.

**Comment by pavlozt** [comment]
+many. 
Many people who are fond of self-measurement will want this simple feature.

**Comment by testomaan** [comment]
We need this to track projects with ManicTime etc.

**Comment by appscaptain** [comment]
Still as relevant as ever.

**Comment by PetbkA** [comment]
Just saw this and was very surprised - can't believe that adding contact name in caption is so hard to implement that this issue exists for almost two years and with no changes :(

**Comment by ilya-fedin** [comment]
@PetbkA it's not hard to implement, I think there's no permission for such a visible change. And I'm not sure developers want to provide that information to other software at all. And I don't think this feature request will ever be a priority as it's a request supplied by community.

**Comment by PetbkA** [comment]
Just tried Telegram Web - caption of browser windows isn't changing depending on chat too, BUT chat ID is changind in URL:
> https://web.telegram.org/z/#NNNNNNN

So you can workaround this lack of functionality by using Web version watcher (for example, [ActivityWatch](https://activitywatch.net/) has [aw-web-watcher](https://github.com/ActivityWatch/aw-watcher-web)).

Once again I'm surprised why developers still don't fix this in desktop version :(

**Comment by ilya-fedin** [comment]
Because this is not a bug to fix and feature requests are just requests, no one accepted this one.

**Comment by pongo** [comment]
In forums, the title of the window contains only the name of the topic. It looks like it should also include the name of the forum.

`<Topic> - <Forum> - Telegram`

**Comment by PetbkA** [comment]
@Aokromes 
> now it's implemented on task bar title, idk if it's what opener wanted.

The issue was about _window_ title, although you could mean it.

**4.5.3** - window title is still _Telegram_ everywhere: In Alt + Tab list, in window title and _Telegram Desktop_ in task bar. May be you meant some alpha version? AFAIK 4.5.3 is the latest release version release 3 weeks ago

**Comment by ilya-fedin** [comment]
@PetbkA it's only in beta versions yes.

@Aokromes meant exactly what he said. The window still has no title at all on Windows and Linux. On Mac the window title is now changed, although the title in the dock is still the same (so on Mac it's the other way around).

**Comment by Aokromes** [comment]
> @Aokromes
> 
> > now it's implemented on task bar title, idk if it's what opener wanted.
> 
> The issue was about _window_ title, although you could mean it.
> 
> **4.5.3** - window title is still _Telegram_ in Alt + Tab list and window title and _Telegram Desktop_ in task bar. May be you meant some alpha version? AFAIK 4.5.3 is the latest release version release 3 weeks ago

get beta 4.5.8 the taskbar title is used on alt+tab too.

**Comment by ilya-fedin** [comment]
> The window has it, but it's not shown in UI.

Well, that's what @Aokromes called "taskbar title", it's displayed only on taskbar button.
