### ISSUE TITLE
Ctrl+C Ctrl+V not working on Ubuntu 

### ISSUE THREAD

**Issue by Hisfantor** [telegramdesktop/tdesktop#10060]
### Steps to reproduce
1. Ubuntu 20.4 i3wm
2. I tested snap, apt and the download from https://desktop.telegram.org/
3. Ctrl+C and Ctrl+V in chat

### Expected behaviour
copy paste via shortcuts in input field
### Actual behaviour
nothing at all
### Configuration
now on tsetup.2.5.1.tar.xz

**Comment by ilya-fedin** [comment]
Can't reproduce, copies and pastes just fine.

**Comment by ilya-fedin** [comment]
@Hisfantor

**Comment by Hisfantor** [comment]
> Can't reproduce, copies and pastes just fine.

seems to be a problem with my windowmanager i3

**Comment by ilya-fedin** [comment]
If this is an i3's issue, you can close the issue
