### ISSUE TITLE
Telegram Beta 2.5.3 in Windows 10 multiple display problem

### ISSUE THREAD

**Issue by GreenYun** [telegramdesktop/tdesktop#10065]
### Steps to reproduce
1. Open Telegram and login
2. Mouse right click the message list

### Expected behaviour
Popup menu shown next to the mouse

### Actual behaviour
Popup menu shown in main display despite Telegram window was placed in

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.5.3 Beta

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7099
