### ISSUE TITLE
[Feature Request] Let users choose their audio devices during an audio call

### ISSUE THREAD

**Issue by Davester47** [telegramdesktop/tdesktop#10078]
### Is your feature request related to a problem?
On my desktop, I have a hard time making audio calls on telegram because I am unable to choose which microphone or speakers for Telegram to use. Sometimes the audio doesn't go through at all, because I think Telegram is using a dummy input or output.

### Describe the solution you'd like
I think it would help greatly if there was an options menu during a Telegram call that would let users choose which microphone and which speakers to use for the call.

### Describe alternatives you've considered
I thought that putting the audio options into the Telegram settings might also work, but then if it's not working during a call you have to go get the settings back out again. Putting it on the call screen would be much more convenient.

**Comment by ilya-fedin** [comment]
Settings -> Advanced -> Call Settings
