### ISSUE TITLE
[Feature Request] Image Viewer Full Screen Disable

### ISSUE THREAD

**Issue by ronaldux** [telegramdesktop/tdesktop#10075]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.

-I'm multitasking and is annoying when I open a image and all my screen get occupied by the image  

### Describe the solution you'd like
I'd like a option on settings for a smaller previewer of the size of the window of telegram

### Describe alternatives you've considered

a option on settings to disable the fullscreen viewers and a smaller viewer, or open images in default app of the system

### Additional context

I have a wide 32" display and I recieve a image and stop watching all my work by the popup image viewer of telegram

**Comment by ilya-fedin** [comment]
#1710

**Comment by ronaldux** [comment]
The solution is for videos not images.
