### ISSUE TITLE
[Question] Question for downloading Visual Studio 2019

### ISSUE THREAD

**Issue by Mehrshad3** [telegramdesktop/tdesktop#10074]
I want to download Visual Studio 2019 to compile Telegram.
Can the plan *Community* compile it?
![image](https://user-images.githubusercontent.com/75848143/103686954-cac3ea00-4fa4-11eb-9b76-62e83035acc3.png)

**Comment by jimdi** [comment]
yes, it's work fine

**Comment by Mehrshad3** [comment]
thanks for answering
