### ISSUE TITLE
error to run command：configure.bat -D TDESKTOP_API_ID = YOUR_API_ID -D TDESKTOP_API_HASH = YOUR_API_HASH -D DESKTOP_APP_USE_PACKAGED = OFF

### ISSUE THREAD

**Issue by MarkLi2011** [telegramdesktop/tdesktop#10072]
configure.bat  force  -D TDESKTOP_API_ID=API_ID -D TDESKTOP_API_HASH=API_HASH -D DESKTOP_APP_USE_PACKAGED=OFF

![image](https://user-images.githubusercontent.com/4051126/103680594-723a2000-4f97-11eb-9cf1-9c993918b161.png)

Edited by @23rd: removed author's credentials.

**Comment by ilya-fedin** [comment]
it's Qt 5.15.2 now

**Comment by 23rd** [comment]
I would suggest you to clean your build environment and rebuild an every dependence.

**Comment by MarkLi2011** [comment]
Thank you for your reply! Besides choosing to rebuild with Qt 5.15.2, is there any other solution to the problem itself?
