### ISSUE TITLE
QR code in dark theme does not recognize

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [telegramdesktop/tdesktop#10077]
### Steps to reproduce
1. Add new account by QR code
2. QR code does not recognize by phone

### Expected behaviour
Looks like in dark theme QR code image was shown in reverse color, which does not recognize by Android client.

### Actual behaviour
QR code does not recognize

### Configuration
**Operating system:** Ubuntu 20.04.1 LTS

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: By `apt` which I think it use **snap** in Ubuntu

**Used theme**: Tinted

**Comment by Aokromes** [comment]
fixed by https://github.com/telegramdesktop/tdesktop/commit/627426f60421fcb5a422d22da55a0a1dd9aa743a ?
