### ISSUE TITLE
Telegram Desktop jumps up some message while trying to scroll up just a little

### ISSUE THREAD

**Issue by asbestomolesto** [telegramdesktop/tdesktop#10081]
### Steps to reproduce
1. Choose a telegram channel
2. Scroll down to look at new messages, or up to check 2 or 3 old messages 
3. The chat JUMPS UP 10 or 20 messages and you are lost into very old messages. 

### Expected behaviour
It must just scroll smoothly where I want it to go. 

### Actual behaviour
It jumps erratically UP to my old messages or to some random messages. 

NOTE: It does the same thing into the Settings scroll menu. 

### Configuration
DEVUAN Gnu/Linux Beowulf

**Version of Telegram Desktop:**
The latest 2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Main Website

**Used theme**:
Default

**Comment by ilya-fedin** [comment]
#6746

**Comment by asbestomolesto** [comment]
> #6746

Ehm - can you explain to me? I can't understand where the problem is and how to solve :)  Thank you :)

**Comment by ilya-fedin** [comment]
You can't solve, it's a bug in Qt, read the original issue.
