### ISSUE TITLE
Videos and images display problem

### ISSUE THREAD

**Issue by MortezaTaghaddomi99** [telegramdesktop/tdesktop#10085]
### Steps to reproduce
1. play a video or open an image. if the size of the image is small, nothing shows on the screen and it blurs. 
otherwise it shows at the button of the page with inappropriate size. 

### Actual behaviour
image and video size are too large. they're not showing at the center of the page. 

### Configuration
**Operating system:**
windows 10, both 1080 and 4k display

**Version of Telegram Desktop:**
2.5.4 beta

**Used theme**:
dark 

![image](https://user-images.githubusercontent.com/43267281/103953085-ba537100-5156-11eb-81fa-b86428333129.png)

**Comment by MortezaHajiabadi8** [comment]
I have same problem on 1080 screen windows10.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/10084
