### ISSUE TITLE
[Feature Request] Add filtering for notifications by text

### ISSUE THREAD

**Issue by LeeSwagger** [telegramdesktop/tdesktop#10087]
### Is your feature request related to a problem?
I receive too much notifications from channels, but I wouldn't like to disable all of them.

### Describe the solution you'd like
I would like to filter notifications by certain text. For example, I receive notification only if message contains word or phrase "home".

### Describe alternatives you've considered
I know several bots for this task, but i can't use it in private channels.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
