### ISSUE TITLE
Referencing Issue #1511, Telegram Xorg client doesn't allow key-chords (ie. cut copy paste Cx Cc Cv or close window, Cw)

### ISSUE THREAD

**Issue by thor314** [telegramdesktop/tdesktop#10080]
Referencing the closed issue #1511, an issue that was opened in 2016 and closed prior to a fix: 

Telegram allows right-click clipboard related commands, but doesn't capture basic Control-whatever input. 

Ie. Right-click copy/paste/whatever works, but not Control-whatever.

**Operating system:**
Xorg on Arch Linux

**Version of Telegram Desktop:**
2.5.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
`yay Telegram`

**Comment by ilya-fedin** [comment]
Clipboard works just fine for me, make sure that you don't have some clipboard manager that interferes with Qt applications

**Comment by ilya-fedin** [comment]
@thor314

**Comment by thor314** [comment]
@ilya-fedin I am not running a clipboard manager. I can't reproduce this behavior on other Qt applications.

**Comment by ilya-fedin** [comment]
I can't reproduce your issue. Something is wrong with your system or steps to reproduce are wrong. I also recommend to test binary from https://desktop.telegram.org to exclude packaging issues.
