### ISSUE TITLE
v0.8.51, Linux: Desktop notifications no longer appearing

### ISSUE THREAD

**Issue by jflory7** [telegramdesktop/tdesktop#1008]
I updated my Telegram Desktop client this morning, and I noticed that I am no longer getting desktop notifications overlaying on my screen like I used to. I only hear the sound, but I no longer see a visual notification on my desktop. I am running Fedora 22, using GNOME 3.16.3 as my desktop environment. More information available on request, not sure what else is needed!

**Comment by jtojnar** [comment]
I believe this started in 0.8.48, #984 might be relevant.

**Comment by auchri** [comment]
@jtojnar No, that's something different

**Comment by jflory7** [comment]
I think it may have been going for the past two updates. I only just noticed it explicitly after a heavy day of using the desktop client.

**Comment by jtojnar** [comment]
I first noticed the problem in either 0.8.48 or 0.8.49. #984 states that tdesktop started using libappindicator in 0.8.48 so I thought libappindicator might be the problem. I use Arch Linux with Openbox.

**Comment by gururuby** [comment]
The same problem after installing version 0.8.51
OS Ubuntu 14.04

**Comment by telegramdesktop** [comment]
Should be fixed in 0.8.52 stable version.

**Comment by Brawl345** [comment]
It was also defect on Windows 7. Now it's working again! Thank you!

**Comment by jflory7** [comment]
Yay, awesome! What a fast turnaround. I will test this as soon as I get back to my desktop! 

Cheers,
————————————

Justin W. Flory
jflory7@gmail.com
Sent via Android

----- Reply message -----
