### ISSUE TITLE
Version 2.5.4 breaks in various ways when playing a video or opening an image

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#10084]
### Steps to reproduce
1. open any video (or open a photo after playing a video)
2. watch Telegram collapse on itself in various different ways

### Expected behaviour
Videos play correctly as they used to do on pre-2.5.3

### Actual behaviour
The video player performs a number of glitches, for example:
- videos are opened extremely zoomed, in a way they take the whole screen ([this](https://files.catbox.moe/0m5z8s.png) is how [this](https://t.me/mafkamote/10974) video appears - also [this](https://files.catbox.moe/ern4b3.mp4) is how the picture I've just linked is opened)
- videos are opened but you don't actually see the video, just the black/grey semi-trasparent background ([video](https://files.catbox.moe/uohauv.mp4))
- telegram desktop crashes ([video](https://files.catbox.moe/uohauv.mp4)), I've sent the crash report

I currently have two monitors plugged in: my standard 1920*1080 PC monitor, and a 4K TV ([screen from windows display settings](https://files.catbox.moe/h68uyi.png)) which is **turned off**. Windows knows it is plugged in, but it isn't detected by display management applications such as DMT and Display Fusion. If more details are required, I will gladly provide them

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.5.4

**Used theme**: default dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Mepth** [comment]
++ fix pls

**Comment by ArtemMoshkovich** [comment]
Had to downgrade to 2.5.3 in light of this issue. Both video and image previews are completely broken in 2.5.4.

**Comment by RememberTheAir** [comment]
@ArtemMoshkovich you can download older versions from this GitHub repository's releases

**Comment by ArtemMoshkovich** [comment]
Absolutely. That's what I was referring to in the opening line "Had to downgrade to 2.5.3 in light of this issue."

Any sense of what might fix this problem for 2.5.4?

**Comment by ImoutoChan** [comment]
Restart somehow fixed zoomed in images for me, but now telegram opens previewer on wrong display (second in my setup) and ignores completely current location of tg window.

**Comment by rafitamolin** [comment]
Same issue here, can reproduce

**Comment by cca310** [comment]
> 
> 
> Same issue here, can reproduce.
> 
> This should be treated as an urgent issue to be fixed. I use Telegram for work and being unable to properly see images & videos is terrible.

maybe don't rely on a beta/prerelease software for work use...?

**Comment by lifegpc** [comment]
Me too. Have same bug.

**Comment by jhhd88** [comment]
Me too. Have same bug

**Comment by necros2k7** [comment]
ApiId: 2040
Assertion: Unexpected: Qt FATAL message was generated! crash_reports.cpp:129
Binary: Telegram.exe
Launched: 08.01.2021 13:28:54
Platform: Windows
QtFatal: createDIB: CreateDIBSection failed (1919x130717, format: 6)
UserTag: 86468c188a6255a4
Version: 2005004 beta
Memory-usage: 656 MB (peak), 386 MB (current)
Pagefile-usage: 957 MB (peak), 728 MB (current)

Caught signal 11 (SIGSEGV) in thread 12504

Backtrace omitted.

Google Breakpad caught a crash, minidump written in thread 13052
Minidump: eab38eaa-25b6-45b6-a96d-3de0091fed6a

Backtrace omitted.

**Comment by 7yang7** [comment]
Me too. Have same bug.

**Comment by RememberTheAir** [comment]
Please people stop posting "me too" comments, either use github's reactions which are meant to avoid notifications spam, or post additional details

**Comment by john-preston** [comment]
@7yang7 I've removed that version from autoupdate, you can downgrade manually (relogin will be required).

**Comment by maxoku** [comment]
Yeah, it opens zoomed and when I unzoom it's always cut from bottom, positioned too low. Later it stops even opening it.
Couldn't you just add a new beta version, the older one but with higher number? Relogging and resetting everything is annoying.

**Comment by jimdi** [comment]
I have this issue too, but telegram assembled from dev branch source worked like a charm

**Comment by simonhollingshead** [comment]
I just want to point out that the name of this bug is possibly overly-specific.  I have the same issue, but I'm using a laptop with only the built-in laptop screen, no external display.

As such, the whole 'weirdly zoomed in, off centre and can't close' can be reproduced without owning a second monitor, let alone connecting or disconnecting it while Telegram is open.

**Comment by d-Rickyy-b** [comment]
Always have had issues with the second display. Videos and images are opening on the wrong (second) display instead of the one where Telegram is opened already. Now after the latest update (2.5.4), images and videos are offset towards the bottom of the screen and zoomed in. Not sure if this is only related to "turned off display" being connected. But I think it has to do something about monitor resolution & waking up from standby mode.

![grafik](https://user-images.githubusercontent.com/5798157/104077486-36fb5380-521a-11eb-88a4-ec6c60c04462.png)

Zooming now will lead to the image being resized and cut off.

![grafik](https://user-images.githubusercontent.com/5798157/104077580-9f4a3500-521a-11eb-9930-5f5d6d6adb41.png)

**Comment by BpArCuCTeMbI** [comment]
same problem. Win7 x64. tg 2.5.4 Beta

**Comment by AkramiPro** [comment]
same problem. Win10 x64. tg 2.5.4 Beta
pls fix

**Comment by VadVergasov** [comment]
Looks the same on 2.5.1 stable, Windows 10 x64 Home. But without zoom problems, only crashes.

**Comment by aminya** [comment]
I think this was fixed by
https://github.com/telegramdesktop/tdesktop/commit/8ae1b10b91267935419e57468e76004296f7201b

Probably we should await a new release.

**Comment by d-Rickyy-b** [comment]
Seems to have been fixed in 2.5.5 beta. At least I have not encountered any issues so far.
