### ISSUE TITLE
Disable notification for specific user

### ISSUE THREAD

**Issue by Upd4ting** [telegramdesktop/tdesktop#10083]
### Steps to reproduce
1.  Go to an user profile and disable his notifications
2.  Ask him to chat in a group
3.  A notification for his message will prompt

### Expected behaviour
No notification

### Actual behaviour
A notification has been prompted

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official website

**Used theme**:
Dark

**Comment by RememberTheAir** [comment]
That's a group notification, so you would have to mute the group chat too. This is how it is supposed to work, and the expected behavior for most people

**Comment by Upd4ting** [comment]
And is there any way we could remove notification from only one person of the group?

We got a gitlab bot and we don't want to be notified each time he post in the group.

**Comment by RememberTheAir** [comment]
> And is there any way we could remove notification from only one person of the group?

Not that I know of. You could try to configure the bot to post in a channel instead of a group, so each subscriber can decide how to configure the channel notifications

**Comment by Upd4ting** [comment]
But it will need to have one group to talk with others and one channel for the bot. As we use that for our customers flow, having one channel and one group per project is a little heavy. 

It seems logic for us that if we disable notification of an user, we don't want his notification either in the common group we got with him. 

It would be amazing if you could add a new feature to handle notification per user in groups.

**Comment by Aokromes** [comment]
it must be done server side.

**Comment by mwesto** [comment]
As we had control over the code of our bot, we added this parameter which stops the sound notifications.

```
bot.telegramBot
  .sendMessage(chan_id, message, {
    parse_mode: 'HTML',
    disable_web_page_preview: true,
    disable_notification: true, // <-------------
  })
```
