### ISSUE TITLE
Schedule message option disappears after scheduling a message

### ISSUE THREAD

**Issue by arni1981** [telegramdesktop/tdesktop#10082]
### Steps to reproduce
1. Open any contact
2. Right-click on a sticker and schedule a message
3. Open another contact and right-click on a sticker and schedule a message

### Expected behaviour
Well, that you should be able to schedule another message

### Actual behaviour
The "Schedule message" option has disappeared, along with the "Send without sound" option.

### Configuration
**Operating system:**
Ubuntu 20.04

**Version of Telegram Desktop:**
2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Downloaded the Linux desktop version from official website,

**Comment by 23rd** [comment]
Yeah, the "Schedule message" option has disappeared, because you are in the section of scheduled messages already, and any message from there can be sent only as scheduled.

**Comment by saturn99** [comment]
yes version 2.5.1 have a problem

![Screenshot_2021-01-07_15-22-47](https://user-images.githubusercontent.com/5188799/103890075-b2ff7980-50fc-11eb-9b90-e2f6563f36ba.png)

**Comment by arni1981** [comment]
> Yeah, the "Schedule message" option has disappeared, because you are in the section of scheduled messages already, and any message from there can be sent only as scheduled.

That's nonsense, why do you dismiss bug reports without even looking at them?

**Comment by arni1981** [comment]
> yes version 2.5.1 have a problem
> 
> ![Screenshot_2021-01-07_15-22-47](https://user-images.githubusercontent.com/5188799/103890075-b2ff7980-50fc-11eb-9b90-e2f6563f36ba.png)

Exactly what happens for me too

**Comment by 23rd** [comment]
Sorry, I misunderstood you.
As you wrote in the original version of your post:

> 1. Open any contact
> 2. Right-click on a sticker and schedule a message
> 3. Right-click on another sticker and schedule a message

After the action in the second point, you jump to a separate section of scheduled messages. So the action in the third point will proceed in this section, where the context menu is shown correctly.

Now, after your upd of the first post, I have got the problem and can confirm it.

Thanks for your report, it will be fixed in the next version.

**Comment by arni1981** [comment]
> Now, after your upd of the first post, I have got the problem and can confirm it.
> 
> Thanks for your report, it will be fixed in the next version.
Yeah, I'm sorry too, I missed a step or wasn't precise enough in my original post.
Happy coding! :+1:
