### ISSUE TITLE
Media Viewer on the wrong screen with two screens

### ISSUE THREAD

**Issue by Kyruf** [telegramdesktop/tdesktop#10092]
### Steps to reproduce
1. Open a media on two screen with Telegram on the secondary monitor
2. The media viewer will be on the other screen, sometimes de-centered
![Screenshot_1](https://user-images.githubusercontent.com/13384536/104079440-5fd41680-5223-11eb-8f24-19af1c186933.png)

### Expected behaviour
Open on the screen telegram is onto, in the middle

### Actual behaviour
Media Viewer does not open on the correct screen

### Configuration
**Operating system: Windows 10 64bit 20H2

**Version of Telegram Desktop: 2.5.4 beta

**Used theme**: stock dark theme

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/10084
