### ISSUE TITLE
[Feature Request] Support nested message entities in editor

### ISSUE THREAD

**Issue by gleb-chipiga** [telegramdesktop/tdesktop#10090]
### Is your feature request related to a problem?
In the message editor, there is no way to combine different formatting features, that is, to use nested entities. For example, there is no way to use bold italic type. The Android application has the ability to use nested entities.

### Describe the solution you'd like
Add support for nested message entities in editor.

### Describe alternatives you've considered
There are no alternatives to this feature.

**Comment by ilya-fedin** [comment]
#7805
