### ISSUE TITLE
v0.8.51, Windows 10: Toast notifications disappear from Action Center even though I haven't interacted to it yet

### ISSUE THREAD

**Issue by resir014** [telegramdesktop/tdesktop#1009]
Hi, I might have found a potential bug with the Windows 10 toast notifications.

If a notification comes into the device, and I looked on the Action Center to preview it, normally it should stay in the Action Center until I interacted with it. But in Telegram Desktop's case, the notifications will disappear from the Action Center when I close it, even though I haven't interacted to them yet.

Here's a quick screencast demonstrating the bug:
https://dl.dropboxusercontent.com/u/76173191/ShareX/2015/08/2015-08-18_14-50-31.mp4

The notifications will also disappear as soon as the notification bubble retracts from the screen, if I haven't interacted with it:
https://dl.dropboxusercontent.com/u/76173191/ShareX/2015/08/2015-08-18_14-58-38.mp4

Was this intended behaviour or a bug?

**Comment by telegramdesktop** [comment]
I'm not sure that I'm in charge of that behaviour, didn't see anything about that in Win10 notifications API.

**Comment by telegramdesktop** [comment]
Looks like this is a Windows bug and I have nothing to do with it:

http://stackoverflow.com/questions/31962216/unexpected-behaviours-in-toast-notification-from-desktop-app-in-windows-10

and 

http://blogs.msdn.com/b/tiles_and_toasts/archive/2015/07/02/adaptive-and-interactive-toast-notifications-for-windows-10.aspx#10634761

I'm afraid right now you can only switch back to my own notifications in Settings, removing the checkbox Use Windows notifications :(

**Comment by resir014** [comment]
@telegramdesktop Ah, I see now. It was still a nice first step on integrating the notifications with Windows nevertheless. :P 

Thanks for clearing it up! You can close this issue for now.
