### ISSUE TITLE
image preview modal problem - next/prev and download button are removed in new version

### ISSUE THREAD

**Issue by AkramiPro** [telegramdesktop/tdesktop#10093]
**notice:**  I'm using Second display and my laptop screen is off. Actually I think this is reason of this bug.

### Steps to reproduce
1. click on image or video

### Expected behaviour
open image in modal view with download button and next/prev button

### Actual behaviour
modal open but with too many offset from top and download button and next/prev button are gone ! 

![Screenshot_1](https://user-images.githubusercontent.com/54323929/104086904-f11daa00-5270-11eb-8ce8-3f031b478827.png)

### Configuration
**Operating system:** windows 10

**Version of Telegram Desktop:** 2.5.4 beta

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/10084
