### ISSUE TITLE
Crash while trying to install to Windows 10 VM

### ISSUE THREAD

**Issue by vindard** [telegramdesktop/tdesktop#10096]
### Steps to reproduce
1. Run `tsetup.2.5.1.exe` to install

### Expected behaviour
The program should install.

### Actual behaviour
The program immediately crashes with a `External exception 8000002.` error

![issue](https://user-images.githubusercontent.com/17693119/104119977-4c3eb380-52e8-11eb-8327-07d295b29166.png)

### Configuration
**Operating system:**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎1/‎2/‎2021
OS build	19042.631
Experience	Windows Feature Experience Pack 120.2212.31.0

**_Running in a VirtualBox VM with 4 cores and 6GB of RAM assigned to it. Base system: 64-bit System76 Lemur Pro system with Pop! OS 2010_**

![image](https://user-images.githubusercontent.com/17693119/104120020-88721400-52e8-11eb-8be3-a5402f216822.png)

**Version of Telegram Desktop:**
2.5.1

**Comment by ilya-fedin** [comment]
Looks like something is wrong with your Windows

**Comment by vindard** [comment]
> Looks like something is wrong with your Windows

Thanks yes it does look that way. I did some more digging on that error code and [found this](https://support.tabs3.com/main/r10309.htm)

![Screenshot_20210110-174138__01](https://user-images.githubusercontent.com/17693119/104136273-79807580-536b-11eb-8a80-2104bf4f5cf5.jpg)

Closing this issue here for now as it seems I'll need to troubleshoot my Windows setup.
