### ISSUE TITLE
"Up" key to edit your last message doesn't work in comments screen

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#10106]
### Steps to reproduce
1. leave a comment in a channel
2. try to edit the message using the "up" key

### Expected behaviour
The app lets you edit the message

### Actual behaviour
Nothing happens

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.5.5

**Comment by ilya-fedin** [comment]
#8692
