### ISSUE TITLE
[Feature Request] 64-bit version of Telegram Desktop for Windows.

### ISSUE THREAD

**Issue by Lemax1995** [telegramdesktop/tdesktop#10109]
### Is your feature request related to a problem?
When I try to upload a big number of videos or try to play videos of large size (~1.4-1.9 GB) in the built-in videoplayer, Telegram Desktop often crashes. I need to reopen the application, and, for example, in the former case I need to select videos again and start uploading again.
I suppose that the reason may be the fact that official Telegram Desktop is a 32-bit application, which limits the number of memory available for the application.

### Describe the solution you'd like
I suggest to release two versions of Telegram: 32-bit and 64-bit. I am sure that 64-bit version of Telegram Desktop would solve this problem.

### Describe alternatives you've considered
I tried a fork of Telegram Desktop which is recompiled for 64-bit: https://github.com/TDesktop-x64/tdesktop
This fork solved my problems: now I can play any video without crashes and I can upload any number of files without crashes.

### Additional context
I have nothing else to say except to ask for 64-bit version of Telegram Desktop for Windows.

**Comment by john-preston** [comment]
@Lemax1995 Yes, this is required indeed. I hope to release it one day.

**Comment by Lemax1995** [comment]
> @Lemax1995 Yes, this is required indeed. I hope to release it one day.

Thank you for all your work! I am looking forward for your release.
