### ISSUE TITLE
[Feature Request] Before sending photos and videos, the window can be moved

### ISSUE THREAD

**Issue by Mehrshad3** [telegramdesktop/tdesktop#10108]
### Is your feature request related to a problem?
A little. I wanted to copy a message from my friend and a photo and send the photo whose caption was my friend's message. when I pasted the photo I couldn't read my friend's message.

### Describe the solution you'd like
As the screenshot in *Additional context*, a window opens. I can't move it. It would be cool if I could move it. or maybe minimize it.

### Describe alternatives you've considered
I could read the message from my phone or write it on paper but I think these alternatives aren't exciting because they are a bit slow. But I think I have 2 better alternatives:
1. It was good if Telegram had an extended clipboard that could store multiple messages, pictures, videos,…
2.  It was good if:
<t>1. When we uploaded a file, we could see its link in Telegram's server if it has a link.
<t>2. In Telegram desktop there was a gallery of photos and videos we uploaded and when we want to send a photo, choose it from gallery and paste the text from clipboard.

### Additional context
![window](https://user-images.githubusercontent.com/75848143/104177094-7e056680-541d-11eb-85ee-6f451ab3d8b9.png)

**Comment by ilya-fedin** [comment]
Just change the sequence of actions: copy-paste the message first and copy-paste the image after that

**Comment by Test047494303730** [comment]
> Just change the sequence of actions: copy-paste the message first and copy-paste the image after that

thanks

**Comment by Mehrshad3** [comment]
> Just change the sequence of actions: copy-paste the message first and copy-paste the image after that

thanks
