### ISSUE TITLE
[Feature Request] Custom chat background for each chat

### ISSUE THREAD

**Issue by Tkkg1994** [telegramdesktop/tdesktop#10116]
### What's the problem?
Users have different choices when it comes to chat backgrounds. Currently you can only set one for all chat. Should it be synced or not?

### Describe the solution you'd like
What I'd like to see would be: in each chat setting or group setting you're able to chose a custom background. Of course the default wallpaper is still there but you could replace it individually in each and every chat/group.
The other question would be if the chat background is synced to the other users as well. Means admins can set a custom background which applies to all users in his group. Or two people who chat with each other in a private chat, they can chose to share the same background or have seperate ones.

It would also be nice if the chat bubbles then change the color to adjust to the chat background colors like it's already done with darkmode.
In my opinion this would make the experience for the users so much better because it's more individual.

### Describe alternatives you've considered
Nothing comes in my mind for here. The first step could be to allow custom chat backgrounds for each and every user befor going public and sync it with all group members or privat chats.

**Comment by ilya-fedin** [comment]
#2642
