### ISSUE TITLE
IsWayland

### ISSUE THREAD

**Issue by perestoronin** [telegramdesktop/tdesktop#10114]
### Steps to reproduce
1.  make from sources

### Expected behaviour
succesful compilation

### Actual behaviour
failed compilation

### Configuration
**Operating system: Gentoo Linux**

**Version of Telegram Desktop: 2.5.5**

<details><summary><b>Logs</b>:</summary>
/var/tmp/portage/net-im/telegram-desktop-2.5.5/work/tdesktop-2.5.5-full/Telegram/SourceFiles/platform/linux/notifications_manager_linux_dummy.cpp: В функции «std::unique_ptr<Window::Notifications::Manager> Platform::Notifications::Create(Window::Notifications::System*)»:
/var/tmp/portage/net-im/telegram-desktop-2.5.5/work/tdesktop-2.5.5-full/Telegram/SourceFiles/platform/linux/notifications_manager_linux_dummy.cpp:32:6: ошибка: нет декларации «IsWayland» в этой области видимости
   32 |  if (IsWayland()) {
      |      ^~~~~~~~~
</details>

**Comment by ilya-fedin** [comment]
Yes, build without dbus is broken, you should build with dbus for now

**Comment by Mehrshad3** [comment]
What is *dbus*?

**Comment by ilya-fedin** [comment]
wikipedia://d-bus

**Comment by Mehrshad3** [comment]
thanks

**Comment by ilya-fedin** [comment]
Fixed by https://github.com/telegramdesktop/tdesktop/commit/5cb081ca9a07d5d2664a2997f1cb1683ec3ffe60
