### ISSUE TITLE
[Feature Request] Kid mode / Limit client functionality on certain device

### ISSUE THREAD

**Issue by offstate** [telegramdesktop/tdesktop#10115]
### Is your feature request related to a problem?
I created an account for my little daughter and I wish she could not add chats, groups and read channels that I did not allow

### Describe the solution you'd like
The first solution is to mark some device as child and block some features on it. (New devices treat as parent)
Another way is to select one device as parent/main and allow to manage ability of other users of the same account from it. (New devices treat as child) In this case you will have a problem if you loose main device.
The second solution is to block features on certain device and set some parent password to unlock

**Comment by Llewellynvdm** [comment]
Oops I just [opened a issue](https://github.com/telegramdesktop/tdesktop/issues/10209) with the same kind of feature request. This is a very needed feature indeed!
