### ISSUE TITLE
Double titlebar and no shadows on Ubuntu 20.10 + Wayland

### ISSUE THREAD

**Issue by the-Mitu** [telegramdesktop/tdesktop#10119]
### Steps to reproduce
1. Open Telegram (I use the one installed from Snap package)
2. Close window with an X
3. open it again from the tray

### Expected behaviour
Window should restore with a single titlebar. It also should have the shadow.

### Actual behaviour
It looks like this (shadows are absent at all even right after launching the app):

![double-titlebar](https://user-images.githubusercontent.com/3919854/104328270-f3d80380-54eb-11eb-9635-e63113b1a819.png)

### Configuration
**Operating system:** Ubuntu 20.10, Wayland session

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: snap

**Used theme**: On Ubuntu I use the default theme.

<details><summary><b>Logs</b>:</summary>

Logs from terminal:

```
(process:110506): Telegram-WARNING **: 15:42:17.717: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 15:42:17.717: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 15:42:17.717: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Using Wayland-EGL
error: : cannot open
error: : cannot open
error: : cannot open
Using the 'xdg-shell' shell integration
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```
</details>

**Comment by ilya-fedin** [comment]
You removed the template -> issue is invalid

**Comment by the-Mitu** [comment]
Oops, sorry. Fixed.

**Comment by ilya-fedin** [comment]
Ok, I started Telegram on Wayland, it has only the bottom titlebar, closed the window, clicked on the tray and the window appeared with the same titlebar. Maybe there's some missing steps to reproduce?

**Comment by the-Mitu** [comment]
Not for me, it happens consistently every time on wayland session with just these steps. Do you try on Ubuntu and GNOME as well?

This line:

```
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

appears at the moment of restoring the window, if that's any help.

I tried setting `TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY`, `TDESKTOP_DISABLE_GTK_INTEGRATION` and `QT_QPA_PLATFORM=wayland`, but this does not seem to change anything. What's weird, this line:

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

appears even if I **do** set `QT_QPA_PLATFORM=wayland`.

**Comment by ilya-fedin** [comment]
> Do you try on Ubuntu and GNOME as well?

No way that I install GNOME, sorry...

> appears at the moment of restoring the window, if that's any help.

It just warns you that Wayland doesn't have any API to focus windows

> appears even if I **do** set `QT_QPA_PLATFORM=wayland`.

Yeah, Qt doesn't check if you set it or not when showing this warning

**Comment by ilya-fedin** [comment]
I tested with official binary, looks like this is reproducible only with snap version... Probably due to the Qt version Canonical provides. Sadly, but they won't update Qt until next LTS version (22.04).

**Comment by ilya-fedin** [comment]
Fortunately, looks like a little workaround helps with that
