### ISSUE TITLE
[Feature Request] Post stories and status updates

### ISSUE THREAD

**Issue by Tkkg1994** [telegramdesktop/tdesktop#10117]
### Is your feature request related to a problem?
No, it's not a problem but simply a missing feature.

### Describe the solution you'd like
It can be implemented similar to Snapchat, WhatsApp or Instagram. For people which got Telegram as main messenger, they would probably love to post their daily picture they've took in a story. This could last for 24h or a specific time the user can set himself. Of course the user has to chose if only contacts, allowed members or all people can watch their story. Further additions would be to: watch only once, set a timer for the picture to appear.

### Describe alternatives you've considered
For a first implementation a basic story tool would be enough to keep your contacts updated about your activities.

**Comment by 23rd** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8458

**Comment by 23rd** [comment]
https://bugs.telegram.org/c/83

**Comment by RememberTheAir** [comment]
Telegram recently launched a "bugs & suggestions" platform. If you want stories to be added to Telegram, please login and upvote [this card](https://bugs.telegram.org/c/83), as this issue is off-topic in this issue tracker

**Comment by Tkkg1994** [comment]
@RememberTheAir Thanks for the suggestion platform, I was searching for that and couldn't find it anywhere
