### ISSUE TITLE
[Feature Request] More Administration Options

### ISSUE THREAD

**Issue by archslayer** [telegramdesktop/tdesktop#10110]
Hi;
Telegram is perfect to P2P talk but group chats has very very limited options to manage and it is impossible to control. Even i'm paying money to combot to manage groups it is still not enough.
1- About admin rights, there is only ban users section for control. But it is too much for for a moderator because in bad situation he can ban everyone.  So first we need only  "silence" authorization asadmin rights. A moderator can silence people for limited time or unlimited from group but wont have to permanent ban permit.
2- Maybe its time to consider sub-group option for big groups, like discord chat channels under the main channel.
3-  Maybe maybe maybe, most of the stuff in combot, from bad word filter to anti-spam tools should be already default tools for Telegram... When i was younger like 15-20 year ago maybe more, we were talking in IRC channels and mIRC scripts had more tools for group moderation than Telegram.  
We reallylike telegram but it started to imposible to control groups and consider redirecting groups to discord because of administration issues. I hope we will have more improvements about this soon.  Thank you for read.

**Comment by ilya-fedin** [comment]
This is a bugtracker of tdesktop, not of the Telegram platform
