### ISSUE TITLE
[Feature Request] GIF Folders

### ISSUE THREAD

**Issue by wjwalcher** [telegramdesktop/tdesktop#10121]
### Is your feature request related to a problem?
Currently, Telegram keeps all your GIFs in one large page sorted by most recently used GIF. It would be nice if there was also an option to use folders to organize your GIFs (so you could organize them by mood/reaction, for example). This would make it much easier to find GIFs when you have a lot of them saved. 

### Describe the solution you'd like
Add an option to create folders to sort your GIFs. Then, the GIFs tab would show you these folders instead of showing you all your GIFs at once, making them more searchable.

**Comment by MasterGroosha** [comment]
I'm afraid this is an API issue. Please consider looking for similar suggestions at https://bugs.telegram.org and post your own one if possible
