### ISSUE TITLE
Persian translation issuses

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#10128]
Hello.

Although all desktop Telegram strings have been translated into Persian (Farsi), But when I hover the mouse over the time of sending / receiving a message, it displays the name of the month and day in English!

**Comment by ilya-fedin** [comment]
QLocale is used to determine date+time format string, so it should get translation from your system.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4182
