### ISSUE TITLE
Add support for searching Giphy from inside tdesktop

### ISSUE THREAD

**Issue by Sushubh** [telegramdesktop/tdesktop#1012]
The mobile app already has this feature. It would be great to have it inside the desktop app as well. I could not find an existing request for this. I assume this is because users are comfortable searching through Giphy manually and downloading GIF and then uploading it on tdesktop?

**Comment by auchri** [comment]
Yes, I think this works well without the integration in tdesktop

**Comment by auchri** [comment]
https://api.giphy.com/

**Comment by auchri** [comment]
#565

**Comment by Geobert** [comment]
we have inline bots now :D

**Comment by auchri** [comment]
true :D
