### ISSUE TITLE
[libtgvoip]: Request for new release

### ISSUE THREAD

**Issue by raghavgururajan** [telegramdesktop/tdesktop#10125]
Hello Folks!
The libtgvoip repository doesn't have 'Issue Tracker', so I am posting here.
There has been many commits (fork) since the release of 5.4.4.
Can you please make a new release with a tag?
Thank you!
Regards,
RG.

**Comment by RememberTheAir** [comment]
libtgvoip is deprecated, [tgcalls](https://github.com/TelegramMessenger/tgcalls) is the new voip library

**Comment by ilya-fedin** [comment]
There's no point in a release since out-of-Telegram-tree build support is community maintained and currently is totally broken
