### ISSUE TITLE
[BUG] macOS notifications play sound when not wanted/authorised

### ISSUE THREAD

**Issue by iamGavinJ** [telegramdesktop/tdesktop#10126]
### Steps to reproduce
1. Open System Preferences -> Notifications -> Select Telegram from the lookup list -> Deselect "Play sound for notification"
![image](https://user-images.githubusercontent.com/15910740/104400612-981b7380-5507-11eb-9416-939b0e7ea3fa.png)
2. Send a message to the logged in.

### Expected behaviour
Notification banners should display, but not with an accompanying audio alert.

This may provide a clue:
https://developer.apple.com/documentation/usernotifications/unnotificationsettings/1648402-soundsetting

### Actual behaviour
Banner is displayed accompanied with the usual audio alert.

### Configuration
**Operating system:**
macOS (Big Sur) 11.1

**Version of Telegram Desktop:**
2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
macOS App Store

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by iamGavinJ** [comment]
There is also a related case when "do not disturb" is enabled.  In this scenario, when DND is enabled, the banner notification *does not* display, yet the audio alert still does.

**Comment by ilya-fedin** [comment]
#9857
