### ISSUE TITLE
reminders added on telegram desktop don't sync with android device

### ISSUE THREAD

**Issue by patrickdrd** [telegramdesktop/tdesktop#10129]
### Steps to reproduce
1. open saved messages on telegram desktop
2. add a reminder
3. open telegram on android device

### Expected behaviour
reminders should sync in all devices

### Actual behaviour
reminder isn't there if telegram on android isn't open at the time of creating it

### Configuration
windows 8.1

**Version of Telegram Desktop:**
2.51 (portable)

**Comment by patrickdrd** [comment]
issue opened 19 days ago,
so I think it needs a kind reminder

**Comment by patrickdrd** [comment]
kind reminder, come on guys..

**Comment by Aokromes** [comment]
bumping won't help to get it fixed.

**Comment by patrickdrd** [comment]
what will? who should I talk to?
I even send them an email, still nothing :(
