### ISSUE TITLE
[Feature Request] "up" key to edit the media with the caption when the last sent message is an album

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#10134]
### Is your feature request related to a problem?
Right now, when we send an album with a caption, the caption is added to the first message of the album. Using the "up" key, however, will make you edit the caption of the _last_ image/document belonging to the album. In my experience it is likely that, as an user, I want to edit the album's caption (which is not the caption of the last message sent, but the first one of the album)

### Describe the solution you'd like
Make the "up" key edit the first album media caption when the last message sent is a media group, if technically possible

### Describe alternatives you've considered
None

**Comment by 23rd** [comment]
I believe there was another issue with the same request, but I can't find it.
This will be fixed in the next release.
