### ISSUE TITLE
crash while whatching channel with videos

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#10136]
all in video
tested on 2.5.1 and 2.5.5 beta
win 10 20H2 x64
mediainfo also attached

https://user-images.githubusercontent.com/10371194/104589741-60cdd380-567b-11eb-9fa8-bd34f54c3d3c.mp4

[mediainfo.txt](https://github.com/telegramdesktop/tdesktop/files/5814340/mediainfo.txt)

**Comment by ilya-fedin** [comment]
crash report tag?

**Comment by f242** [comment]
@ilya-fedin 47553fe3-de76-46cf-bef7-e5fce405a3b3
