### ISSUE TITLE
Sending messages without joining a chat

### ISSUE THREAD

**Issue by lejabque** [telegramdesktop/tdesktop#10133]
### Steps to reproduce
1. Open a chat attached to a channel (discussion) or a public chat using a link (No need to join the chat!)
2. Type a message and press "Enter"

### Expected behaviour
Nothing 

### Actual behaviour
Message is sent to the chat without joining

### Configuration
**Operating system:** Ubuntu 20.04.1, Plasma

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)**: snap

![image](https://user-images.githubusercontent.com/30625073/104534595-9ea00d00-5625-11eb-94e5-d7412cd94ad6.png)

**Comment by lejabque** [comment]
Also works with sending messages to the channel

**Comment by ilya-fedin** [comment]
#8906

**Comment by ilya-fedin** [comment]
@Aokromes maybe it is better to close question instead? It's poorly described (the bug is reproducible only in snap version what is not mentioned in #8906).

**Comment by Mehrshad3** [comment]
I thought it's not a bug. Was I wrong?

**Comment by lejabque** [comment]
> @Aokromes maybe it is better to close the question instead? It's poorly described (the bug is reproducible only in snap version what is not mentioned in #8906).

I checked it on the Linux static build now, the same bug, so it's not only snap version problem
