### ISSUE TITLE
[Feature Request]  Add temporary group chats

### ISSUE THREAD

**Issue by sina-rostami** [telegramdesktop/tdesktop#10132]
temporary group with specified expiration time feature would be a nice choice.
for who want to chat and make conversation together just for several minutes or hours.
+ after expiration time  all history would be clear.
+ expiration time can be changed (extension availability for the expiration time).

**Comment by MasterGroosha** [comment]
I think this is an API Issue and more relevant to bugs.telegram.org

**Comment by sina-rostami** [comment]
thanks. I'll share this feature request in the website you mentioned too.
