### ISSUE TITLE
[Feature Request] improve proxy settings

### ISSUE THREAD

**Issue by OmidRafiee** [telegramdesktop/tdesktop#10130]
It seems to add a button to clear all the proxy or add a button to clear all proxy inactive can help the user better comfort.

![image](https://user-images.githubusercontent.com/25098596/104452073-b9d43380-55b7-11eb-9fd9-5934e2da18db.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5028
