### ISSUE TITLE
Doesn't select the system default speaker and microphone

### ISSUE THREAD

**Issue by sarptekbas** [telegramdesktop/tdesktop#10135]
### Steps to reproduce
1. Someone calls
2. Answer
3. The caller speaks

### Expected behaviour
Tell us what should happen
When talking to someone or calling it should automatically change to the system default mic and speaker.

### Actual behaviour
It just uses what is default when it is installed or last opened.

### Configuration
**Operating system: Windows 10 Pro 2004**

**Version of Telegram Desktop: 2.5.1**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Dark Theme / Night Mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#9814
