### ISSUE TITLE
[Feature Request] Don't show my avatar in conversations where I choose to hide my avatar.

### ISSUE THREAD

**Issue by alandria** [telegramdesktop/tdesktop#10138]
### Is your feature request related to a problem?

There is a feature to show/hide my profile photo for certain contacts and groups. I can hide my avatar, but I can't really check the current state of avatar visibility since I always see my messages with my avatar shown. 
This issue is concerning my privacy since I'm using this to limit the scope of people who are able to see my profile photo.

### Describe the solution you'd like
Don't show my avatar to me in conversations when it is forbidden to see my avatar to another chat members.

### Describe alternatives you've considered
I can check if someone can see my profile photo using Privacy settings menu, but sometimes it is getting difficult to check exact person who should be member of some chat where I choose to hide my profile photo.

### Additional context
Additional feature that might be added - disabling/enabling visibility of my profile photo from the respondent user info window.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
