### ISSUE TITLE
Stickers posted to group chat from Android and iOS clients show "The message is not supported in your version of Telegram Web." on desktop client.

### ISSUE THREAD

**Issue by vicbreen** [telegramdesktop/tdesktop#10139]
I am moving my group of friend off of WhatsApp to Telegram, and this bug is drawing a lot of hate.

### Steps to reproduce
1. Post a sticker to our shared chat (not a secret chat). Either from Android or iOS clients, doesn't matter.
2. View the chat on Telegram Web.
3. Messages that should show stickers are showing "The message is not supported in your version of Telegram Web. Update the app to view: web.telegram.org." on stand-alone web client.

### Expected behaviour
Stickers posted to the chat should show up for all users regardless of which client views the chat.

### Actual behaviour
Stickers are being replaced with error message "The message is not supported in your version of Telegram Web. Update the app to view: web.telegram.org."

### Configuration
**Operating system:**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎9/‎3/‎2020
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0

**Version of Telegram Desktop:**
0.5.7.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
n/a

**Used theme**:
default

Example screen capture attached (redacted, of course):

![Telegram-web-fail](https://user-images.githubusercontent.com/5504858/104662201-1fd7be00-567f-11eb-9661-c09be20d9701.png)

**Comment by ilya-fedin** [comment]
this is the repo of Telegram Desktop, not Telegram Web...

**Comment by Ondra1230** [comment]
Repo?what is it?Sent using the mobile mail appOn 15/01/2021 at 01:28, ilya-fedin wrote:
                
            
            
                
                    From: "ilya-fedin" <notifications@github.com>Date: 15 January 2021To: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Subject: Re: [telegramdesktop/tdesktop] Stickers posted to group chat from Android and iOS clients show "The message is not supported in your version of Telegram Web." on web client. (#10139)
                
                
this is the repo of Telegram Desktop, not Telegram Web...

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/10139#issuecomment-760562941",
"url": "https://github.com/telegramdesktop/tdesktop/issues/10139#issuecomment-760562941",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ilya-fedin** [comment]
> Repo?what is it?

GitHub repository, the place you're currently in

**Comment by vicbreen** [comment]
> this is the repo of Telegram Desktop, not Telegram Web...

I made a mistake in the subject. The problem is seen in Telegram Desktop, but the error message provided says "Telegram Web" in it which I think is why I got confused and wrote the subject wrong.

**Comment by ilya-fedin** [comment]
Screenshot and version you provided points to the fact that you're not using Telegram Desktop, since the current version is 2.5.1

**Comment by ilya-fedin** [comment]
I see that Telegram Web has version 0.5.7, so you're using Telegram Web. not Telegram Desktop

**Comment by vicbreen** [comment]
...and you're absolutely right. I don't know why I thought I was running the desktop app and not a pop out piece of chrome. My bad :(
