### ISSUE TITLE
Align my messages on the right, and other people's msgs on the left.

### ISSUE THREAD

**Issue by fausgaitan** [telegramdesktop/tdesktop#10144]
### Is your feature request related to a problem?
the problem is that from a UX perspective I'm so confused when I scan the messages, they are all aligned to the left... mine should be on the right, and the other person's messages should be on the left.

### Describe the solution you'd like
my messages should be on the right, and the other person's messages should be on the left.

### Describe alternatives you've considered
You could make my messages stand out more with better contrast.

### Additional context
I know you would be copying WhatsApp, but honestly, it's the best solution. There's a mental effort when you scan the messages to figure out which ones I sent and which ones I received... it's a bad experience.

![image](https://user-images.githubusercontent.com/53086200/104731680-d3da5700-571a-11eb-879b-c5fb6cf0dcbe.png)

**Comment by ilya-fedin** [comment]
Settings -> Chat settings -> Adaptive layout for wide screens
