### ISSUE TITLE
Drop of a photo - must be "media"! Not "file" (document)

### ISSUE THREAD

**Issue by waspar** [telegramdesktop/tdesktop#10143]
### Steps to reproduce
1. Drop photo (500px x 700px or any other big)
2. Option - without compress

### Expected behaviour
I expected behavior like on mobile app - photo displayed as a media resource
![photo_2021-01-15_14-33-31 jpg - Windows Photo Viewer](https://user-images.githubusercontent.com/1203589/104723212-f92d8c00-573f-11eb-9286-db6146c8444b.jpg)

### Actual behaviour
Photo displayed as a file (document)

### Configuration
**Operating system:**
Windows 10 Pro 19042.685

**Version of Telegram Desktop:**
2.5.1

**Used theme**:
Light

**Comment by john-preston** [comment]
@waspar This is what "compressed" is for. If you want to send original uncompressed file, it is sent as a file. If you want to send a photo, like mobile apps, then it is sent compressed (like mobile apps send it).

**Comment by waspar** [comment]
"Tabs"
![1](https://user-images.githubusercontent.com/1203589/104723977-19aa1600-5741-11eb-82c4-40b8608e5820.jpg)
![2](https://user-images.githubusercontent.com/1203589/104723979-1a42ac80-5741-11eb-9255-156919fcfeb5.jpg)

**Comment by waspar** [comment]
@john-preston "compressed" or "uncompressed" option doesn't change anything

**Comment by waspar** [comment]
Drop areas don't change anything either

**Comment by waspar** [comment]
I did not find an option in the settings to change this behavior

**Comment by waspar** [comment]
@john-preston Ok! Thanks! After restart app "compressed" option works fine.
