### ISSUE TITLE
[Feature Request] Not count unread messages from Archived Chat

### ISSUE THREAD

**Issue by gbschenkel** [telegramdesktop/tdesktop#10145]
### Is your feature request related to a problem?
The amount of unread messages showed on Telegram System Notification are the sum of all Chat/Group/Channel in Telegram. Is a bit annoying when you see the notification and say, 150 or 999+ unread messages, I need to go, enter in all archived Channels/Groups and just read them all.
For me is a problem to keep it up-to-date since I use it for work, I am can't miss a important message.

### Describe the solution you'd like
I like to System Notification only show the amount of unread messages from not archived chat/groups/channel.

### Describe alternatives you've considered
A option to enable this kind of configuration in Settings will be best, because some people maybe don't like or want this.
Other thing could you implement Filter from Folders for notification, like the Folders, then the People can put in Notification just what they want.
Or maybe just sync the Notification with some of the Folders, since the filter option is already in there.

### Additional context
![image](https://user-images.githubusercontent.com/1715069/104734693-6aa91280-571f-11eb-8b4b-9ba2202e5a9e.png)

**Comment by ilya-fedin** [comment]
Settings -> Notification -> Include muted chats in unread count

**Comment by gbschenkel** [comment]
> Settings -> Notification -> Include muted chats in unread count

That is for muted not Archived, I have plenty of muted chats, I like to count on telegram icon, but I don't want they pop up, that is why is muted, which is the same as on my cellphone. The not muted I want to pop up, because can be a private conversation or from my work group.

**Comment by gbschenkel** [comment]
Please reopen this issue.

**Comment by ilya-fedin** [comment]
Looking by #7170, this is tracked by #6195

**Comment by gbschenkel** [comment]
Ok, I will follow the #3916
