### ISSUE TITLE
[Feature Request] Create Telegram peer-to-peer technology

### ISSUE THREAD

**Issue by AsUn-bxxO** [telegramdesktop/tdesktop#10147]
### Is your feature request related to a problem?
I am using Telegram for the first time as a new user.

But unfortunately there is no general peer-to-peer network for nice messenger app, like Telegram.

Unfortunately, there is also no extra feature in Telegram Desktop to use microblogging.

It also generally lacks a true microblogging web version, similar to Twitter.

### Describe the solution you'd like
I know peer-to-peer concepts mostly from the BitTorrent area. There is also the BTFS (BitTorrent Filesystem) from BitTorrent.
https://www.bittorrent.com/token/bittorrent-file-system/

With WebTorrent: https://github.com/webtorrent/webtorrent

Telegram could become an integrated video platform where users can share their video much like Youtube. If there is still a new currency, all YouTubers can also switch to Telegram video platform and for every click of their video they also get paid, but independently so remunerated by cryptocurrencies.

It is also possible copyright music or videos are uploaded and are also not deleted no matter whether uploaded by official authors or any users. For each click there is a compensation directly to the artists, so similar to Spotify but independent.

It can really build a new ecosystem.

I think it is already possible to implement something like this in practice.

### Describe alternatives you've considered
There is no alternative. Telegram is becoming more popular and more real features should be added.

A peer-to-peer solution has other advantages, for example, with blockchain technology or without, it is possible to create an account in less than 10 seconds and without providing a mobile number.
It is also possible to create an offline/local account and connect to local networks, an example is a Wi-Fi 6E personal hotspot from smartphone (currently only Android high-end smartphones support creating personal hotspot without SIM card, just like a Wi-Fi router).

With a mobile number, the user is completely dependent on his provider. This is harmful for privacy.

### Additional context
Telegram needs a web version for browser and a microblogging function. In addition, an alpha or beta version should be launched for new Telegram peer-to-peer network.

**Comment by Aokromes** [comment]
https://bugs.telegram.org/

**Comment by AsUn-bxxO** [comment]
> https://bugs.telegram.org/

@Aokromes 
Can you transfer my report to this page? I can't login to this site because I am forced to enter a mobile number.

**Comment by Aokromes** [comment]
no
