### ISSUE TITLE
Chat frame must get certain width in order to get chat messages positionated properly.

### ISSUE THREAD

**Issue by maher1719** [telegramdesktop/tdesktop#10149]
### Steps to reproduce
1. open any chat
2. My chat messages got inclined to the left 
3. If I open the stickers bar the chat messages get inclined correctly
4. Chat frame must get certain width to work propeerly

My chat messages got inclined to the left.

![screen one](https://user-images.githubusercontent.com/25207866/104770413-d2d41480-5770-11eb-93d8-32de97590855.PNG)

Chat frame must get certain width.

![min width](https://user-images.githubusercontent.com/25207866/104770406-cf408d80-5770-11eb-82d6-96b5efcdf432.PNG)

### Expected behaviour
Tell us what should happen
My chat messages get inclined in the right.

### Actual behaviour
My chat messages get inclined to the left if stickers bar is closed.
I noticed the chat frame must get a specific width to work correctly.
### Configuration
**Operating system:**
Windows 10 64bit v20H2 build 19042.685 screen resolution 1366x768

**Version of Telegram Desktop:**
2.5.1

**Used theme**:
Dark theme but also happen in the bright theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/10144#issuecomment-760953849
