### ISSUE TITLE
[Question] Why global search results are limited and will this be fixed?

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#10158]
When searching for something, global search results are limited (only 3 shown), if I am subscribed to similarly named channels/groups, or I have messages that contain that search query. Why is this? This really spoils my experience with the app, and complicates discovery. Will this be fixed, global search results expanded? I don't even mean more than usually shown, although that would be incredibly nice, as also would be nice to discover channels/groups from within Telegram itself and not jut come there from external sources, but that 3-result limitation.

**Comment by ilya-fedin** [comment]
#8857
