### ISSUE TITLE
No "Invite to Group via Link" button in the desktop version.

### ISSUE THREAD

**Issue by vi** [telegramdesktop/tdesktop#10154]
### Steps to reproduce
1. Start `telegram-desktop` version `2.2.0+ds-5` from Debian Bullseye  
2. Log in to the same account as in Telegram version 7.3.1 on Android.
3. Try to obtain an invitation link to a group using "Add member" function.

### Expected behaviour

There is "Invite to Group via Link" button at the top of member candidate list, which allows to copy the link. 

### Actual behaviour

Only existing members are displayed in the list, without the button at the top, unlike in Android version of that window.

### Configuration

**Operating system:** Linux Debian Bullseye

**Version of Telegram Desktop:** `2.2.0+ds-5`

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Debian's repositories.

**Used theme**: light, the default one.

**Comment by RememberTheAir** [comment]
You have to go to options -> manage group -> group type, there you'll find the option to copy the invite link. But yes it would be nice to have it in the "add members" widget

**Comment by vi** [comment]
Yes, now I see the link in "group type" window.

I though I explored the entire "Manage group" window, but missed it.

**Comment by vi** [comment]
As of version `2.6.1+ds-1` there is still no link in "Add members" window.

**Comment by Aokromes** [comment]
telegram is 2.8.x already, download it from desktop.telegram.org

**Comment by vi** [comment]
There is "Invite via Link" option in "Add members" dialogue in 3.1.1.
