### ISSUE TITLE
[Feature Request]  Moderation tools , channel in moderation

### ISSUE THREAD

**Issue by ringo32** [telegramdesktop/tdesktop#10159]
### Is your feature request related to a problem?
if a channel go overboard how to manage the channel in general in a instance.

### Describe the solution you'd like
would like on irc , put the group in moderation.

just quiet the group for normal users for a moment and let moderators talk to it.

### Describe alternatives you've considered
idk

### Additional context
just place where moderators place a option, moderation button..; only moderators can talk through the channel; and moderators of the group can switch back to orginal. sometimes not need to bann people or remove. just keep the calm back.

**Comment by Aokromes** [comment]
enable slow mode.
