### ISSUE TITLE
Telegram Desktop for Windows 10 crashes with start the video call 

### ISSUE THREAD

**Issue by vogiadni** [telegramdesktop/tdesktop#10150]
hello everyone;
it's more than a few months that telegram desktop (V. 2.5.1) in my device crashes when i start the video call, then will appears blue page and system shutting down. 
so anybody has imagine of that issue to fix please?

thanks in advanced

**Comment by ilya-fedin** [comment]
Crash report tag?

**Comment by vogiadni** [comment]
how do i can send you the log?

**Comment by vogiadni** [comment]
please find it in attached.
[log.txt](https://github.com/telegramdesktop/tdesktop/files/5823554/log.txt)

**Comment by vogiadni** [comment]
let me know where i can find that report or in which directory?

**Comment by ilya-fedin** [comment]
On the next launch after crash tdesktop shows you crash reporter and it gives you a crash report tag when you've sent the report

**Comment by vogiadni** [comment]
I got newly crashed a few min ago but it directly shown the blue page not error.

**Comment by vogiadni** [comment]
![image](https://user-images.githubusercontent.com/77511224/104793162-bc52ab00-57ba-11eb-9a74-ab0848b444be.jpeg)

**Comment by ilya-fedin** [comment]
There seems to be a problem with your OS

**Comment by vogiadni** [comment]
What kind of problem do you mean?! In different os i used of TD but just in win10 i hv this

**Comment by ilya-fedin** [comment]
> What kind of problem do you mean?!

Your OS is damaged most likely if you're seeing the blue screen

**Comment by vogiadni** [comment]
I don't think so my friend because this problem happened just in telegram

**Comment by ilya-fedin** [comment]
This means that you're just using too little software most likely. Only drivers can cause this error since common software (including Telegram) is not running in kernel mode and therefore unable to call a kernel trap.

**Comment by john-preston** [comment]
@vogiadni Also please try the beta version 2.5.5 (update from settings), only beta version asks you to share the crash report after a crash. But only after an app crash, not the whole system crash (which no regular app should be able to cause anyway).

**Comment by vogiadni** [comment]
john thank you for your comment; but the system Immediately after crashing the app, the system shows the blue screen and I have no way except restart the sys. anyway I'll check it with V. 2.5.5 and share the result. 
thanks again

**Comment by vogiadni** [comment]
hi again @john-preston i updated to beta and check it again but unfortunately the result is same...!!!

**Comment by Aokromes** [comment]
try https://www.nirsoft.net/utils/blue_screen_view.html

**Comment by vogiadni** [comment]
thanks a lot @Aokromes , i checked it and depends the programs report; problems happened by;

1. NT Kernel & system, Microsoft antimalware file system filter driver. (in one date)
2. No;1 content plus Nvidia windows kernel mode driver. (another time)

if needs any extra info let me know please.

**Comment by Aokromes** [comment]
try updating gfx drivers.

**Comment by ilya-fedin** [comment]
> thanks a lot @Aokromes , i checked it and depends the programs report; problems happened by;
> 
>     1. NT Kernel & system, Microsoft antimalware file system filter driver. (in one date)
> 
>     2. No;1 content plus Nvidia windows kernel mode driver. (another time)
> 
> 
> if needs any extra info let me know please.

So the problem is in your Nvidia drivers or in your Windows either

**Comment by vogiadni** [comment]
do you have any idea to how to fix that? i reinstalled the Nvidia's driver but again happened. whats the reaction of Microsoft antimalware file system filter driver or kernel in this point?

**Comment by ilya-fedin** [comment]
> do you have any idea to how to fix that?

report that to NVidia/Microsoft

**Comment by ilya-fedin** [comment]
> whats the reaction of Microsoft antimalware file system filter driver or kernel in this point?

No one could know that except of microsoft developers

**Comment by Aokromes** [comment]
> do you have any idea to how to fix that? i reinstalled the Nvidia's driver but again happened. whats the reaction of Microsoft antimalware file system filter driver or kernel in this point?

what version of drivers you installed? try downloading latest ones from www.guru3d.com you may want to try older versions too.

**Comment by vogiadni** [comment]
@ilya-fedin thanks for your mention. 
@Aokromes i installed the latest official version 342.01 from Nvidia website.

**Comment by Aokromes** [comment]
latest is https://www.guru3d.com/files-details/geforce-461-09-whql-driver-download.html

**Comment by vogiadni** [comment]
i tried to download and install new version of Nvidia driver but depends on device model as Geforce 8400, it's impossible to update except 342.01. this problem just happened in win10, because i never had same issue in another OS. anyway thank you all.

**Comment by Aokromes** [comment]
this issue is still valid with 2.8.4 / 2.8.6 beta?
