### ISSUE TITLE
All messages become replies to previous comments

### ISSUE THREAD

**Issue by Section25** [telegramdesktop/tdesktop#10155]
I'm using Telegram on my Mac and I have been trying to figure this out for days before I realised that the app was on here so hopefully somebody can tell me if I have some kind of unreasonable expectation.

Whenever I try to add a comment in a channel thread, instead of appearing as a comment in the thread, it appears indented as a reply to somebody else's comment, usually (but not always) the lowest visible comment. This obviously obliterates context and can give the impression that I am responding to a particular comment when I am trying to make a general comment about the topic. Everybody else seems to have the ability to make comments on the original post - just not me.

Maybe related - but probably not - I have been trying to figure out what the [ / ] button is for - as far as I can tell, it just inserts a / and then it disappears.

I can't find any kind of user guide, there is no Help menu in the app and the app doesn't show tool tips so being a bit of a novice with Telegram, I'm in the dark.

**Comment by RememberTheAir** [comment]
> henever I try to add a comment in a channel thread, instead of appearing as a comment in the thread, it appears indented as a reply to somebody else's comment, usually (but not always) the lowest visible comment.

Can you share a screen recording of the issue?

> Maybe related - but probably not - I have been trying to figure out what the [ / ] button is for - as far as I can tell, it just inserts a / and then it disappears.

Probably not related. Comments in channels are just a "window" to the replies sent in the discussion group of a channel. When you comment in a channel, you're actually sending a message in the channel's discussion group. The "/" icon is displayed when the channel's discussion group has a bot among its members, but if the bot has no configured /command, when you click on the "/" nothing will happen.

What Telegram Desktop are you using anyway?

**Comment by Section25** [comment]
As I mentioned, I am using the Mac version.

But I think I have figured it out. I thought that the app displayed posts something like Twitter, i.e. all posts are aligned the same but they seem to be displayed more like Mac/iOS messages in that my posts are aligned on the right and everybody else's are aligned left - so a short reply appears the same as a comment reply until one notices the speech bubble arrows and indent bars.

**Comment by Aokromes** [comment]
if you use a version 7.x of telegram not lite you are on the incorrect bugtracker.

**Comment by Section25** [comment]
The about window says 2.5.1 - I just clicked on the GitHub link on the Telegram website that I downloaded it from.
