### ISSUE TITLE
File handles not being freed

### ISSUE THREAD

**Issue by uhthomas** [telegramdesktop/tdesktop#10156]
### Steps to reproduce
1.  Drag and drop a video into Telegram
2. Send the video
3. Wait for the send to finish
4. Try to delete the video

### Expected behaviour
The video should be able to be deleted.

### Actual behaviour
The video cannot be deleted, as the file is in use. Restarting Telegram Desktop frees the handles.

![image](https://user-images.githubusercontent.com/9749173/104823576-1434f480-5843-11eb-809b-b001f21f83c2.png)

![image](https://user-images.githubusercontent.com/9749173/104823607-4e9e9180-5843-11eb-8149-1b3fc5097f83.png)

### Configuration
**Operating system:** Windows 10 Pro

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: None

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#7818
