### ISSUE TITLE
[Feature Request] Stick Window to Desktop Edges

### ISSUE THREAD

**Issue by reyaz006** [telegramdesktop/tdesktop#10151]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Stick Telegram window edges to desktop edges automatically when near then at 10 pixels or less.

### Describe alternatives you've considered
Windows 7/8/10 have "snap" feature that allows to position several windows close to each other and to desktop edges. But it doesn't help when only one window is needed to be positioned perfectly at the edge. Also it tends to be activated unintentionally by the user (with a double-click at the window edge for example) and thus some prefer to have this feature disabled.
Sticking might be more useful since when a user moves a window around screen it's never unintentional.

### Additional context
Demonstration (here it sticks to other windows, but my feature suggestion is about desktop edges): https://www.nurgo-software.com/images/AquaSnap/Snapping.gif

**Comment by ilya-fedin** [comment]
Weird feature request, there's no sense to implement a feature that copies a system's feature for a such specific use case...
