### ISSUE TITLE
Secret chat

### ISSUE THREAD

**Issue by laloshifrin** [telegramdesktop/tdesktop#10162]
Please add secret chat.
Thanks

**Comment by Ondra1230** [comment]
WHY? NO

 
 

Sent: Monday, January 18, 2021 at 1:06 AM

**Comment by ilya-fedin** [comment]
#871

**Comment by dm17** [comment]
Not really useful to reference a locked thread... This is a key feature not available on Linux.

**Comment by RememberTheAir** [comment]
@dm17 locked thread for a feature request -> no plan to add that in the short term.

Anyway, there's a "secret chats on desktop" issue which is still active and with some comments from the dev: #8071

**Comment by ilya-fedin** [comment]
> locked thread for a feature request -> no plan to add that in the short term.

most likely it's closed because became too hot
