### ISSUE TITLE
Links open new instance of Browser but not the Site.

### ISSUE THREAD

**Issue by JPRuehmann** [telegramdesktop/tdesktop#10164]
### Steps to reproduce
1. Click on a Link in Telegram
2. 
3. 

### Expected behaviour
Open the Site in the Browser.

### Actual behaviour
Open a  new Instance of the Browser and the Start Page.
But not the selected Site.

### Configuration
Kubuntu 18.04 LTE (32Bit)

2.4.4

Download Site from Telegramm.

Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Telegram uses system APIs to open links & files. Whatever other programs doing is not in Telegram responsibility.

**Comment by JPRuehmann** [comment]
Then it uses them in the Wrong way!
Because all other Apps such as Twitter or Adobe Reader aso. Not having this Problem!

**Comment by JPRuehmann** [comment]
This is Support!
Thanks.

**Comment by ilya-fedin** [comment]
I don't recommend you to say 'all other programs" because whenever people saying that they're wrong. The fact that you have problems means that your system is misconfigured.

**Comment by ilya-fedin** [comment]
> 2.4.4

the latest version is 2.5.1...

**Comment by JPRuehmann** [comment]
32Bit Linux?

**Comment by JPRuehmann** [comment]
Than let us say all Apps I know off on my System.

**Comment by ilya-fedin** [comment]
> 32Bit Linux?

linux 32-bit is not supported anymore. You can't report a bug from an outdated version.

**Comment by JPRuehmann** [comment]
Thanks, there is no word outdated.
