### ISSUE TITLE
Interface scaling increases minimum window height when it shouldn't

### ISSUE THREAD

**Issue by notNSANE** [telegramdesktop/tdesktop#10169]
### Steps to reproduce
1. Increase UI scaling to 200%
2. Try to keep the app height the same size as 100% scaling

### Expected behaviour
App height should be the same as 100% scaling in any other scaling mode.

### Actual behaviour
App height minimum increases with each higher scaling.

### Configuration
**Operating system:** Windows 10.

**Version of Telegram Desktop:** 2.5.5

**Used theme**: Default

**Comment by john-preston** [comment]
@notNSANE This is intended. There are minimum width and height of the window relative to its contents, so when the scaling increases, they're increased as well.

**Comment by notNSANE** [comment]
> @notNSANE This is intended. There are minimum width and height of the window relative to its contents, so when the scaling increases, they're increased as well.

OK, but I can't select text size at 100% scaling, so I can't read. If I scale the app at 150% then the app doesn't fit in the screen space I have asigned it. You closed all my isses.

What do I do? @john-preston

**Comment by john-preston** [comment]
@notNSANE I'm afraid the only thing you can do is to assign more screen space for the app.
