### ISSUE TITLE
Telegram is craching when accepting a call

### ISSUE THREAD

**Issue by rednaks** [telegramdesktop/tdesktop#10160]
### Steps to reproduce
1. Call or receive a call
2.  Accept or when the other hangs up
3. Telegram Crashes

### Expected behaviour
not to crash

### Actual behaviour
crashed

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)** -  flatpak 

**Used theme**: dark mode

<details><summary><b>Logs</b>:</summary>
D/tgvoip: Received init ack
D/tgvoip: Received init
I/tgvoip: Peer version is 9
I/tgvoip: Sending init ack
W/tgvoip: Received duplicated packet for seq 13
W/tgvoip: Received duplicated packet for seq 13
W/tgvoip: Received duplicated packet for seq 13
W/tgvoip: Received duplicated packet for seq 13
V/tgvoip: Call state changed to 3
E/tgvoip: Capture buffer is too big (18048)
Segmentation fault (core dumped)

</details>

**Comment by ilya-fedin** [comment]
Install debug packages (org.kde.Sdk, org.kde.Platform.Debug, org.telegram.desktop.Debug), [run gdb](https://docs.flatpak.org/en/latest/debugging.html#running-debugging-tools), get a backtrace with `run` and `bt full` gdb commands and send it here.

**Comment by rednaks** [comment]
Hi, we managed to solve the issue, the other contact had an outdated version of telegram.

**Comment by ilya-fedin** [comment]
It should work even when other contact has an outdated version..

**Comment by rednaks** [comment]
I'm unable to reproduce right now but, it was on android, version of telegram: 5.15.0
