### ISSUE TITLE
☺ is displayed as an emoji

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#10161]
### Steps to reproduce
1. Disable "Replace emoji automatically".
2a. Send ``a☺``.
2b. Or ``a`☺` ``.
2c. Or ``a☺<S-←><C-S-m>``.

### Expected behaviour
The `☺` symbol remains untouched.

### Actual behaviour
`☺` is displayed as an emoji, rather than a plain ol' CP866 0x01 smile.

### Configuration
**Operating system:** Debian GNU/Linux 11

**Version of Telegram Desktop:** 2.5.5 beta

**Installation source (Linux Only)**: the official website

**Used theme**: Classic

**Comment by ilya-fedin** [comment]
"Replace emoji automatically" option is for replacing text smiles ("xD", ":shrug:", etc). What you see is tdesktop's emoji support and how it renders symbols.

**Comment by bodqhrohro** [comment]
>and how it renders symbols.

For a while, it displays the symbol properly:
![2021-01-18-231625_1366x768_scrot](https://user-images.githubusercontent.com/2134486/104963507-5e54dc00-59e3-11eb-934e-ab027eda9d8a.png)
The smile turns into an emoji after a message is sent, or sometimes even during editing (for example, if I apply some formatting to it).

**Comment by ilya-fedin** [comment]
If this happens after sending, it's a server-side replace most likely

**Comment by ilya-fedin** [comment]
I checked and it becomes emoji as soon as I paste it. Probably you have some rendering lag if you able to see it monochrome.

**Comment by bodqhrohro** [comment]
>it's a server-side replace most likely

The symbol code remains intact. It's just about how TelegramDesktop displays it.

>it's a server-side replace most likely

I type it with Composé.

**Comment by ilya-fedin** [comment]
> The symbol code remains intact. It's just about how TelegramDesktop displays it.

It is clear that disabling this option shouldn't change the behavior then, since this is not a replace.

> I type it with Composé.

You may want to create a bug report about this with details, since you shouldn't see monochrome smile at all.
