### ISSUE TITLE
No audio from calls or voice chats when audio device is not set to 16bit 48kHz

### ISSUE THREAD

**Issue by EdoaLive** [telegramdesktop/tdesktop#10172]
### Steps to reproduce
1. Set Windows audio device "Default Format" to 24bit 192kHz
2. Start a voice/video call or join a voice chat
3. People can hear you, but you can't hear anything
(other sounds like voice messages seems to work)

### Expected behaviour
I should hear audio from calls and  voice chats

### Actual behaviour
I don't hear audio from calls or voice chats
I have to re-configure my sound device to 16bit 48kHz in order to work-around this (took me some time to figure out this...)

### Configuration
**Operating system:**
Windows 10 pro 20H2

**Version of Telegram Desktop:**
2.5.1 windows

**Comment by john-preston** [comment]
@EdoaLive Please try the latest beta version, does it work there?

**Comment by EdoaLive** [comment]
It seems to work on the beta (2.5.5), thank you!
