### ISSUE TITLE
[Feature Request] Consider enabling LZO compression for Snap

### ISSUE THREAD

**Issue by om26er** [telegramdesktop/tdesktop#10176]
The snap package of Telegram Desktop works quite good on my Linux based system. However the startup time of Telegram is quite substantial when using the snap package. In recent months, the snapcraft upstream made some improvements to the packaging format and now they support LZO compression for snaps. I tried to build telegram-desktop snap by enabling LZO compression and did see substantial performance improvements in startup time.

I think this app should enable that by default.

Note that changing the compression format will also increase the install footprint of the snap package. More reading here https://snapcraft.io/blog/why-lzo-was-chosen-as-the-new-compression-method

Fortunately the change is a one liner
```
om26er@HomePC:~/scm/ubuntu/tdesktop$ git diff
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index 94343903e..17497632e 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -5,6 +5,7 @@ icon: Telegram/Resources/art/icon512@2x.png
 base: core20
 grade: stable
 confinement: strict
+compression: lzo
 
 architectures:
   - build-on: amd64
```

**Comment by ilya-fedin** [comment]
I've seen some incompatibility notes about older systems on snapcraft forums... IMHO, it is better to leave it default and wait until snapcraft team decides LZO to be default, so that it will be used without any changes to snapcraft.yaml

**Comment by om26er** [comment]
I believe LZO was chosen by upstream specifically because it's compatible to *all* targets that snapd currently supports including much older kernels. I am curious to know, do you have any specific case in mind ?

**Comment by ilya-fedin** [comment]
> do you have any specific case in mind ?

No, it's just what I've read on the snapcraft forum.

> I believe LZO was chosen by upstream specifically because it's compatible to _all_ targets that snapd currently supports including much older kernels.

I believe if LSO has no problems, it should been used automatically, without any changes from package maintainers.

**Comment by om26er** [comment]
@ilya-fedin So I queries the Snapcraft team about the reason for LZO not being default. It seems it's mostly due to the fact that snapcraft (Ubuntu Core, really) targets the embedded space as well, where storage is still not redundant enough.

Since Telegram is a (great) Desktop app, I think we should consider making the move to LZO compression.

https://forum.snapcraft.io/t/lzo-compression-by-default/22256

**Comment by ilya-fedin** [comment]
What's the minimum snapd version with LZO support? For instance, debian stable has 2.37 and it's not autoupdatable: https://packages.debian.org/buster/snapd. Will these users lose capability of installing tdesktop?

**Comment by om26er** [comment]
LZO compression doesn't require any specific version of snapd, it has a minimal Linux kernel version requirement, which to my knowledge all distros that support snapd already have.

**Comment by om26er** [comment]
> LZO compression doesn't require any specific version of snapd, it has a minimal Linux kernel version requirement, which to my knowledge all distros that support snapd already have.

Related talk here https://forum.snapcraft.io/t/when-to-contact-upstreams-to-use-lzo-compression/20858

**Comment by ilya-fedin** [comment]
Are there any list of already switched publishers?

**Comment by om26er** [comment]
> Are there any list of already switched publishers?

I am not sure about a bigger list, however Chromium started using LZO compression since a few months https://snapcraft.io/chromium

Maybe @popey know of a few other upstreams who made the move.

**Comment by ilya-fedin** [comment]
> I am not sure about a bigger list, however Chromium started using LZO compression since a few months https://snapcraft.io/chromium

AFAIK, chromium is published by Canonical itself and they testing their new features before others. It's worth to see how much third-party publishers already switched.

**Comment by ilya-fedin** [comment]
I tried to build snap with LZO compression and it tells me that it's still experimental: `EXPERIMENTAL: Setting the squash FS compression to 'lzo'.`
It works on debian though.

**Comment by om26er** [comment]
Quick update: We have now updated several snaps to start using LZO compression by default. That includes:

* https://github.com/snapcrafters/android-studio
* https://github.com/snapcrafters/signal-desktop

Will share more if we face **any** issues.
