### ISSUE TITLE
Changing workspace will always show a window on top even if it wasn't

### ISSUE THREAD

**Issue by lucaszanella** [telegramdesktop/tdesktop#10177]
I initially thought it was a bug in Gnome so I opened an issue there (https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3569) but then I discovered it is telegram specific

I have telegram as "always on visible workspace". Bringing it to the front of the screen and then to the back on Workspace 2, will always make it visible on Workspace 1, even it was in the back.
I wanted it to only be on the front in workspace 1 if I made it on the front on workspace 1.
Ubuntu 20.04
Video: https://imgur.com/a/PlSBfbN
You can see that when I put telegram on front in workspace 2 and then bring it back, then I switch to workspace 1 and it's on the front. This is very annoying

### Steps to reproduce
1. open telegram 
2. mark as always on visible workspace
3. make it visible on one workspace and then make it invisible by bringing another window (firefox for example) on top
4. switch to other workspace, it appears on top

### Expected behaviour
it shouldn't appear on top on the new workspace

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

Ubuntu 20.04

**Version of Telegram Desktop:**

2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

snap

**Used theme**:

default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
> but then I discovered it is telegram specific

Check other Qt applications, it might be Qt specific
