### ISSUE TITLE
[Feature Request] Reaction emojis

### ISSUE THREAD

**Issue by Aethalides** [telegramdesktop/tdesktop#10175]
### Is your feature request related to a problem?
Allow the use of emjoi as in-line reaction

### Describe the solution you'd like
On the right hand side of a message display an emjoi button selector. Clicking on it allows the selection of an emoji. The chosen emoji is displayed underneath the message along with a count of how many users have chosen this reply emoji

### Describe alternatives you've considered
n/a

### Additional context

![image](https://user-images.githubusercontent.com/5896279/105057641-55105180-5a6d-11eb-8066-e899cff97f39.png)

**Comment by RememberTheAir** [comment]
This is offtopic on tdesktop's github, refer to Telegram's official suggestions platform: https://bugs.telegram.org/c/23
