### ISSUE TITLE
Search Language Issue.

### ISSUE THREAD

**Issue by opqriu** [telegramdesktop/tdesktop#10179]
No problem even searching in English. English search works fine and good.
But, However, there is a problem with Korean search. (Fatal search bug)
When searching Korean, if I do not enter all the letters of the word, the search results will not appear.
To search 텔레그램(Telegram), I need to enter 텔레그램(Telegᅟram).
But Typing 텔레그(Teleg) or 텔레(Tele) will show no results (zero results).
I use Linux, but  other OS Telegram Desktop are the same.

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/724
