### ISSUE TITLE
Fail colors in message actions

### ISSUE THREAD

**Issue by AboShanab** [telegramdesktop/tdesktop#1017]
Hello telegram team, i show problem in my message actions colors show this photo : http://i.imgur.com/96zfjjQ.png
Why that's black color ? i think it's a bug, i got that's problem in Debian Jeesie KDE4 and Xfce
Thanks.

**Comment by auchri** [comment]
Which black color do you mean?
the color of the text or the background?

Please describe your issue better.

**Comment by AboShanab** [comment]
the color of the background
I got that's problem in 0.80.50+

**Comment by auchri** [comment]
Plesse make a screenshot of the whole window

**Comment by lunix4** [comment]
Please use a compositor manager like compton or compositing window manager like xfwm4, compiz. Problem solved

**Comment by skwerlman** [comment]
@lunix4 their using XFCE4, which uses XFWM4 by default

**Comment by AboShanab** [comment]
@auchri when i try to make a screenshot for telegram window, the window of options is hidden

**Comment by auchri** [comment]
make a screenshot of the whole screen and crop the image?

**Comment by lunix4** [comment]
so, you have to enable composite manager in xfwm4

**Comment by AboShanab** [comment]
@lunix4 : Thanks, it's solved my problem.
