### ISSUE TITLE
[Feature Request] Add emoji reactions for messages

### ISSUE THREAD

**Issue by ruslansin** [telegramdesktop/tdesktop#10173]
### Is your feature request related to a problem?
Sometimes it would be great to be able to react to a message using emoji. 

### Describe the solution you'd like
For each message, you can add emoji reactions.
Bonus: telegram bots can process reactions for messages

### Additional context
Similar functionality can be found on social networks and messengers such as Skype and Discord

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/23
