### ISSUE TITLE
[Question] Where is the .desktop file for Linux?

### ISSUE THREAD

**Issue by pvonmoradi** [telegramdesktop/tdesktop#10188]
I have used the "install Telegram binary directly" method and I'm using Xubuntu 18.04. I have not set any desktop file but my app launcher can find it!
My question is, does the binary generate the `.desktop` file somewhere automatically?

**Comment by ilya-fedin** [comment]
yeah, in ~/.local/share/applications

**Comment by pvonmoradi** [comment]
@ilya-fedin Ah! thanks. Problem is, the file has a cryptic name : `appimagekit_685b850ffb3350caa7131a0a2fb1f8bf-Telegram_Desktop.desktop`. Is this file re-created/deleted on each update?

**Comment by ilya-fedin** [comment]
> Is this file re-created/deleted on each update?

yeah, it is
