### ISSUE TITLE
Knowledge Base

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#10189]
Hi there,

Do you guys not have a knowledge base with a search feature?

We are having a huge issue trying to find the answers to our questions & everything is outdated from back in 2015/2017.

We are having a huge problem finding pre-made bots to do a welcome message, they have to agree to rules, etc.

Thanks

**Comment by ilya-fedin** [comment]
https://telegram.org/faq?

**Comment by Aokromes** [comment]
this doesn't belongs to here anyway.

**Comment by ILoveSkilledCoders** [comment]
You closed my question without even answering or addressing it???

**Comment by Aokromes** [comment]
this repository is for telegram desktop client, not for webpage issues.

**Comment by ILoveSkilledCoders** [comment]
I am using the desktop client & we need to find answers to our questions on how to use the bots.

If you can't help, then where do I go?

Also, where do I submit feature requests?

Thanks
