### ISSUE TITLE
[high dpi] Provide .svg or hi-res icon in taskbar for Linux

### ISSUE THREAD

**Issue by yhsb2k** [telegramdesktop/tdesktop#10180]
### Steps to reproduce
1. Use ubuntu (18.04 or newer) and connect 4k monitor.
2. Set original resolution (3840 x 2160) in the system and enable high dpi support. In MATE environment: Control Center -> MATE Tweak -> Windows -> HiDPI.
2. Launch Telegram and see the low resolution (blurred compared, for example, with nvidia) icon in taskbar:
![Screenshot at 2021-01-20 10-22-50](https://user-images.githubusercontent.com/13915612/105151821-16cb6e80-5b0f-11eb-856b-ab406cc1b9b7.png)

### Expected behaviour
Telegram icon in taskbar should be in .svg format or in high resolution.

### Actual behaviour
Low resolution (blurred) icon in taskbar.

### Configuration
**Operating system:** Ubuntu 18.04 with MATE

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: official website.

**Used theme**: Dark

**Comment by ilya-fedin** [comment]
X protocol doesn't support setting svg icons as window icons, this suggestion doesn't have any sense

**Comment by Mehrshad3** [comment]
> X protocol doesn't support setting SVG icons as window icons, this suggestion doesn't have any sense

and what about high-resolution icons?

**Comment by ilya-fedin** [comment]
> and what about high-resolution icons?

tdesktop sets a 256px icon as window icon
