### ISSUE TITLE
Chat text align issue.

### ISSUE THREAD

**Issue by Albatroon** [telegramdesktop/tdesktop#10181]
![image](https://user-images.githubusercontent.com/12618175/105167837-e8a35a00-5b21-11eb-9872-aa7d6660c897.png)

Chat text should be on right for me (sender) & left for the other side. But when Maximizing the window all goes left. 

### Configuration
Operating system: Windows 10
Screen Resolution 1920 x 1080

Version of Telegram Desktop: 2.5.1 & 2.5.5 Beta

**Comment by Aokromes** [comment]
not a bug, disable adaptative layout.
