### ISSUE TITLE
Google Play Store link preview in cyrillic, regardless of source language on page

### ISSUE THREAD

**Issue by shayaknyc** [telegramdesktop/tdesktop#1018]
This is true regardless of desktop or android client. If I copy/paste or share directly from the google play store to telegram, the preview information in the sent chat box is all in Cyrillic characters (presumably Russian), even though the page is in English. Any ideas?
![1](https://cloud.githubusercontent.com/assets/13590551/9369021/adf94f88-4694-11e5-8aed-7c8654407157.png)
![2](https://cloud.githubusercontent.com/assets/13590551/9369020/adf5041e-4694-11e5-83ce-1f1cef379ebd.png)

**Comment by auchri** [comment]
Maybe the language of the server is Russian.

But that's not a issue of telegram desktop.

Contact the telegram team on twitter: https://twitter.com/telegram or use the build in support feature

**Comment by shayaknyc** [comment]
I can definitely say with complete certainty that this is not the case. For example, if you send a google play link on Facebook, the preview text is in English, not Russian. This experience only occurs using telegram.

**Comment by auchri** [comment]
Yes, I meant the language of the telegram servers.

**Comment by shayaknyc** [comment]
Gotcha. Thanks for the clarification!
