### ISSUE TITLE
Written messages not updated properly, when switch the window most part is gone. Have to rewrite again.

### ISSUE THREAD

**Issue by Cyborg002** [telegramdesktop/tdesktop#10183]
I'm using windows 7 Operating System. As I type a long messages (Because I also used Telegram as a note making) and forgot to send(or hit the enter key), and switch to another application. And again when I switch back to telegram, what I see that most of the lines are gone, only initial 3 to 4 lines remains. They completely disappear. I've to rewrite the whole message again.

**Comment by ilya-fedin** [comment]
#4922
