### ISSUE TITLE
Forwarding albums

### ISSUE THREAD

**Issue by hooddy** [telegramdesktop/tdesktop#10195]
### Steps to reproduce
I am trying to forward albums of photos (btw this issue is on any Telegram versions - desktop, mobile, unigram)

### Expected behaviour
i am awaiting to forward full photo album

### Actual behaviour
it is forward only first album shot

### Configuration
win10x64

**Version of Telegram Desktop:**
2.5.5b

**Used theme**:
default

**Comment by RememberTheAir** [comment]
Try to click on the caption and then "forward message". If the album doesn't have a caption, right-click on the empty space next to the message, then "select message" -> forward message
