### ISSUE TITLE
App crashes when loading private chat with several GIFs

### ISSUE THREAD

**Issue by MiguelFerPi** [telegramdesktop/tdesktop#10194]
### Steps to reproduce
1. Send and/or many GIFs to/from someone.
2. Close telegram.
3. Go back later to that same chat

### Expected behaviour
It should load the chat and GIFs without any problems.

### Actual behaviour
The app briefly shows the chat, it might load 1 or 2 GIFs but stopped, and then crashes.

### Configuration
**Operating system:** w10-x64

**Version of Telegram Desktop:** 2.2.5-beta

**Used theme**: Tinted, Dark mode

<details><summary><b>Logs</b>:</summary>
Crash report tag: `55f5da24-6dc9-44ab-a3da-d2df0b49ed4a`
</details>

This has been happening for like almost a year, I just haven't got the time and mood to write a report.
Also, it temporarily fixes if I go into Storage management and clear the cache.

**Comment by c0re100** [comment]
#7287
