### ISSUE TITLE
Wayland mode misplaces window positioning upon opening application.

### ISSUE THREAD

**Issue by SaucySauce** [telegramdesktop/tdesktop#10199]
Steps:

Enable Wayland mode for Qt5 apps on GNOME Shell Wayland session with parameter export QT_QPA_PLATFORM=wayland;

Reboot/Log back in;

Open Telegram;

Behavior:

Window opens with top left corner centered in the middle of the screen whilst clearly in maximized mode, moving the window and maximizing it again will fix the bug for the most part until app process is terminated, same bug will occur when initiating it again.

![Screenshot from 2021-01-22 14-45-36](https://user-images.githubusercontent.com/38703177/105512388-92205200-5cc0-11eb-9c18-13676210de31.png)

What should happen:

App window opens maximized fully shown throughout the screen.

OS: Arch Linux
Session: GNOME Shell 3.38.3
App version: 2.5.1 as found on official repos

**Comment by Aokromes** [comment]
update to 2.5.5 (2.5.6) beta from desktop.telegram.org.

**Comment by ilya-fedin** [comment]
Applications can't control their position on Wayland, there's just no API for positioning. It is entirely in compositor responsibility (in other words, it is a GNOME bug).

**Comment by SaucySauce** [comment]
Thanks.

**Comment by SaucySauce** [comment]
Is the lack of a titlebar also an issue with GNOME Shell on Wayland mode?

**Comment by ilya-fedin** [comment]
> Is the lack of a titlebar also an issue with GNOME Shell on Wayland mode?

I see titlebar on your screen shot

**Comment by SaucySauce** [comment]
Server side Decoration I mean.

**Comment by ilya-fedin** [comment]
Yeah, they don't want to support server-side decorations on Wayland
https://gitlab.gnome.org/GNOME/mutter/-/issues/217

**Comment by SaucySauce** [comment]
Damn.

**Comment by SaucySauce** [comment]
Any way of making the CSD on telegram slightly bigger? The buttons are too small.

**Comment by ilya-fedin** [comment]
no way, sorry

**Comment by SaucySauce** [comment]
Ok, no problem.
