### ISSUE TITLE
Telegram reduces tone pitch of other playing music sources upon start

### ISSUE THREAD

**Issue by OlliC** [telegramdesktop/tdesktop#10196]
### Steps to reproduce
1. Have a sound source playing. For Example a Youtube video in Firefox.
2. Start Telegram-Desktop.
3. Listen to the audio of the Youtube video.

### Expected behaviour
Starting Telegram-Desktop should have no effect on other playing sound sources.

### Actual behaviour
Playing sound sources suddenly become reduced in their tone pitch by alot. It sounds like it is played at half the speed.

### Configuration
**Operating system:** Fedora 33

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)**: Distribution Package
**Used theme**: None. but using Dark Mode.

**Comment by ilya-fedin** [comment]
#1548
