### ISSUE TITLE
Telegram on GNOME Shell Wayland fullscreen image view bug

### ISSUE THREAD

**Issue by SaucySauce** [telegramdesktop/tdesktop#10198]
Steps:

Be on GNOME Shell 3.38 Wayland session.

Enable Qt Applications to run on Wayland mode with environment parameter: export QT_QPA_PLATFORM=wayland

Upon rebooting/logging back in, open Telegram.

View image on a chat.

What happens:

When using extensions that send fullscreen windows to new workspaces, the image viewer is recognized as an independent window and is sent to another workspace.

What should happen:

The image viewer remains in the same space/workspace used by the main telegram window, this is the behaviour on Xwayland windowed Telegram desktop app and on the Xorg session.

No other bugs present and app is perfectly stable.

OS: Arch Linux
App version: 2.5.1 as found on the official repos.

**Comment by Aokromes** [comment]
update to 2.5.5 (2.5.6) beta from desktop.telegram.org .

**Comment by SaucySauce** [comment]
Thanks.

**Comment by ilya-fedin** [comment]
Like already been mentioned in #10199, there's no API for positioning and we can't do anything about that.
