### ISSUE TITLE
[Feature Request] Allow scaling below 100%

### ISSUE THREAD

**Issue by LyrixCaz** [telegramdesktop/tdesktop#10193]
### Is your feature request related to a problem?
Yes, in devices like the PinePhone for example which uses the telegram desktop app, the scaling seems alright until you have folders setup. Then the folder taskbar will take a lot of the screen real estate and you wont be able to see the entirety your messages.
### Describe the solution you'd like
A possible workaround for this would be to allow for the scaling % to be inputted on the options..
A fix for this would probably involve hiding the folder bar or rearranging the location of it.
A possible fix would also be to allow some sort of 'text wrap' in the chats so they wont leave the screen. 
### Describe alternatives you've considered
Personally I haven't considered any alternatives, as there isn't at the moment as far as i know..
![IMG_20210121_094936](https://user-images.githubusercontent.com/45947682/105367314-39858200-5bf8-11eb-8636-765d2dc12ac6.jpg)

**Comment by Aokromes** [comment]
also, scaling bellow 100% is already implemented with command line.
