### ISSUE TITLE
[Feature Request]   Options to highlight or silence in a group.

### ISSUE THREAD

**Issue by onolox** [telegramdesktop/tdesktop#10200]
### Is your feature request related to a problem?
Management of too many people in a group.

### Describe the solution you'd like
In a large group, we need 2 options for managing messages:
- An option to "silence" someone, only the thumbnail will appear, but the message will only appear if we click on the thumbnail.
- An option to “enhance” the people we like, to make their messages highlighted. A special gold halo around the messages of them, or something like that.

### Additional context
To make the hundreds of messages more bearable to deal with.

**Comment by Demetri0** [comment]
1. Hmm... making "silence" mode sounds strange... ban could be a better solution that makes less spam.
2. Oh crap, please... no need highlights, or at least provide as an option that disabled by default.

// Just user point of view

**Comment by RememberTheAir** [comment]
Both the things you asked for are out of the scope of this project since Telegram Desktop can't just decide to implement them without the other official apps doing it too. You should open a suggestion at https://bugs.telegram.org (there's already an entry for your first suggestion: https://bugs.telegram.org/c/1787 and slightly related https://bugs.telegram.org/c/37)

**Comment by onolox** [comment]
Ok, I've posted the second suggestion in the link you posted, you can close this issue. 
Thanks!

**Comment by onolox** [comment]
> 1. Hmm... making "silence" mode sounds strange... ban could be a better solution that makes less spam.
> 2. Oh crap, please... no need highlights, or at least provide as an option that disabled by default.
> 
> _// Just user point of view_

Sure it will be disabled by default, because you have to select the person to have a highlight. One by one.
And I think you don't participate in big groups... hundreds os posts everyday...
