### ISSUE TITLE
Some copy/pasted images get faded

### ISSUE THREAD

**Issue by novel** [telegramdesktop/tdesktop#10207]
For several months I've been been told by other people that screenshots I paste are faded. I didn't notice it myself until I've checked from the other client. I'm using `import` (a part of ImageMagick) to make screenshots.

### Steps to reproduce
1. Take screenshots using two different tools. I've used `scrot` and `import`: `scrot -c -d 5 scrot_faded_img_test.png`, and `sleep 5 && import -window root import_faded_img_test.png`,
2. Open a desktop client, in some chat click 'Attach' button and attach those two png files from step 1,
3. Open this chat from a different client (e.g. Mobile).

### Expected behaviour
Screenshots should be same.

### Actual behaviour
Screenshots generated using `import` are faded, the other one is fine.

Here are the original files produced by `import` and `scrot`:

https://people.freebsd.org/~novel/misc/import_faded_img_test.png
https://people.freebsd.org/~novel/misc/scrot_faded_img_test.png

And here's a recoded version which I've saved from Telegram using a mobile client:

https://people.freebsd.org/~novel/misc/import_faded_img_test_recoded.jpg

### Configuration
**Operating system:**
FreeBSD 13.0-CURRENT amd64

**Version of Telegram Desktop:**
2.4.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
FreeBSD packages

**Used theme**:
Tinted

Mobile client I used for testing: Telegram iOS 7.3.1 (doesn't seem it matters though as I get reports about my faded screenshots from varioius people using various clients).

One more note: jpg to jpg conversion seem to be working fine for `import`. I.e., if I do `import foobar.jpg` and paste that, it won't get faded.

**Comment by ilya-fedin** [comment]
this is fixed in latest versions
