### ISSUE TITLE
[Feature Request] don't replace links with emoji

### ISSUE THREAD

**Issue by RiedleroD** [telegramdesktop/tdesktop#10203]
### Is your feature request related to a problem?
This is the third time I replied "idk" with a link to someone, pressed enter, and then found that the word got replaced by the shrug emoji and removed the link entirely.

### Describe the solution you'd like
Please either keep formatting when replacing a word or just don't replace words with links with an emoji.

### Describe alternatives you've considered
Maybe adding a setting to toggle that behaviour on/off would be considerable, but imo, there are already enough settings in telegram desktop.

**Comment by Mehrshad3** [comment]
> Please keep formatting when replacing a word.

I think it's the best solution that is possible.

**Comment by RiedleroD** [comment]
seems to be fixed…? I mean, emojis just don't get inserted by pressing enter anymore, so the problem is gone.
