### ISSUE TITLE
Tray icon is no longer displayed

### ISSUE THREAD

**Issue by schinfo** [telegramdesktop/tdesktop#10210]
### Steps to reproduce
1. install Telegram-Desktop 2.5.6 beta
2. start Telegram-Desktop

### Expected behaviour
Tray Icon should be displayed + number of unread messages

### Actual behaviour
Instead of the Telegram icon, the following is displayed:

![Bildschirmfoto vom 2021-01-24 15-30-29](https://user-images.githubusercontent.com/26834276/105633656-21ad3880-5e5a-11eb-80dc-010d846d2190.png)

downgrading to 2.5.5.r1 solved the problem.

### Configuration
**Operating system:**
Manajaro Linux + Kernel 5.11-rc4 + Cinnamon DE

**Version of Telegram Desktop:**
2.5.6 beta - with latest commit 9b9531d2798eb0c4624c65ddeee8c87eda23a820

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
https://gitlab.manjaro.org/security-overlay/telegram-desktop/-/blob/master/PKGBUILD

**Used theme**:
Mint-Y-Dark-Teal (Mint Cinnamon)

Night (for Telegram)

**Comment by ilya-fedin** [comment]
You removed some important parts of the template, please restore them.

**Comment by ilya-fedin** [comment]
> **Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
> https://gitlab.manjaro.org/security-overlay/telegram-desktop/-/blob/master/PKGBUILD

Thank you for restoring the template, but there are no notifications on post edits...

Can you show `echo $QT_QPA_PLATFORMTHEME`?

**Comment by schinfo** [comment]
It's **qt5ct**

**Comment by ilya-fedin** [comment]
Check that you have the same icon theme set in qt5ct as in cinnamon settings

**Comment by schinfo** [comment]
Thanks for the hint - that's the reason - is fixed ;-)
