### ISSUE TITLE
Telegram crashes on Windows after receiving some links.

### ISSUE THREAD

**Issue by k41n** [telegramdesktop/tdesktop#1021]
such a conversation forces telegram for windows to crash and user on that side is unable to open that conversation again because telegram crashes again on opening it.

![1440052930238](https://cloud.githubusercontent.com/assets/5092164/9377567/919fd7ae-471a-11e5-9f1f-cdf80f9eb5d0.png)

![img_20082015_094307](https://cloud.githubusercontent.com/assets/895649/9377448/d9c8df38-4721-11e5-84df-14bf34ed6d9c.png)

Windows 7, Telegram 0.8.52

**Comment by telegramdesktop** [comment]
Does not happen for me. Could you please contact me at https://telegram.me/preston so I ask you for crashdumps from "tdumps" folder? Or I'll ask you to forward these messages to me, so it could crash at my pc as well. You can do it through https://web.telegram.org

**Comment by telegramdesktop** [comment]
Found and will be fixed in next version, I hope.
