### ISSUE TITLE
picture preview with different screen resolution

### ISSUE THREAD

**Issue by mergandevinsander** [telegramdesktop/tdesktop#10228]
![image](https://user-images.githubusercontent.com/4045972/105859302-67eecd00-5ffd-11eb-8d7f-74bced6fddd6.png)
with my current dispalys layout and app at third screen picture preview opens as if my displays aligned by top border.

**Comment by ilya-fedin** [comment]
Looks like you're using an outdated version, you can't report bugs of oudated versions

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/10084
