### ISSUE TITLE
[Feature Request] Improve Thread View

### ISSUE THREAD

**Issue by iwan-c-sugeng** [telegramdesktop/tdesktop#10224]
### Is your feature request related to a problem?
Currently Thread View is already available in desktop and apps, but still need more improvement, like we can't view thread from latest reply within main thread, we need to click the reply message until the source message, this is less intuitive and not comfortable enough. This is in a super group chat. 

### Describe the solution you'd like
I've seen slack view thread method, i think we can add something like reply text as a shortcut to view the thread, and also we can always see view thread in all messages that is in a thread, we don't have to get to thread starter to view a thread

### Describe alternatives you've considered
In Official desktop telegram, we can add a dedicated window for thread view if the desktop is wide enough to put a dedicated windows

**Comment by RememberTheAir** [comment]
> like we can't view thread from latest reply within main thread, we need to click the reply message until the source message, this is less intuitive and not comfortable enough

I'm afraid this is intended. It used to work like that in early betas, but now you can access the thread view from any message only if the supergroup is linked to a channel

Anyway, this suggestion belongs to https://bugs.telegram.org as it shouldn't be tdesktop-specific
