### ISSUE TITLE
[Feature Request] Want All Mathematical Symbols in Emoji Store.

### ISSUE THREAD

**Issue by Cyborg002** [telegramdesktop/tdesktop#10220]
As I used telegram as a Note Making, There'd be a difficulty when you want to enter **Mathematical symbol**. So I request you to add that feature too. 
It'll also be helpful, if someone want to discuss mathematics over chatting.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6056 ?

**Comment by ilya-fedin** [comment]
> #6056 ?

Maybe he wants something like LaTeX? The issue is too unclear.

**Comment by Mehrshad3** [comment]
Would it be nice that there be a place in a setting to set emoji types (People, Nature, Flags, Mathematics, Blocks,…) you want to use?
Like stickers that we can set what sticker packs we like and want to use

**Comment by Mehrshad3** [comment]
> > #‌6056 ?
> 
> Maybe he wants something like LaTeX? The issue is too unclear.

I think both issues are clear. (#‌10220,#‌6056)

**Comment by ilya-fedin** [comment]
> I think both issues are clear. (#‌10220,#‌6056)

This one is poorly described and unclear.

**Comment by Mehrshad3** [comment]
I think he wants a new emoji type <i>mathematics</i> in this bar:
![image](https://user-images.githubusercontent.com/75848143/105867928-dbe3a200-600a-11eb-8510-bb0d0a99e717.png)

**Comment by ilya-fedin** [comment]
What should this emoji type contain?

**Comment by Mehrshad3** [comment]
I think the block <i>Mathematical Operators</i> is neseccary.
![Mathematical Operators](https://user-images.githubusercontent.com/75848143/105870727-ccb22380-600d-11eb-84d6-e3de07d5e9b3.jpg)
And some characters outside this block like:
`ℂℍℕℚℝℤ←→↔️⇍⇎⇏⇐⇒⇔`
I think it's better to discuss what exciting characters it should contain.

**Comment by ilya-fedin** [comment]
But they aren't emojis...

**Comment by Mehrshad3** [comment]
> But they aren't emojis...

@Cyborg002

**Comment by Cyborg002** [comment]
Isn't there any way to add this Functionality ?

**Comment by ilya-fedin** [comment]
> Isn't there any way to add this Functionality ?

You can install some program into your system that will show mathematical symbols popup by some hotkey. It's a more generic and universal solution.

**Comment by Mehrshad3** [comment]
> You can install some program into your system that will show mathematical symbols popup by some hotkey.

I use [Character Pad](https://play.google.com/store/apps/details?id=com.husseinelfeky.characterpad) for android. but I don't know any software for windows.

**Comment by Cyborg002** [comment]
Okay, Thanks for suggestions.
I'll look for another tool for this.
