### ISSUE TITLE
Noises are heard when answering an audio call.

### ISSUE THREAD

**Issue by noname-3** [telegramdesktop/tdesktop#10227]
### Steps to reproduce
1. Launch telegram desktop.
2. Call a person by audio call.
3. The person is almost inaudible, because the sound makes a noise.

### Expected behaviour
I must clearly hear what the person is saying

### Actual behaviour
The person is almost inaudible, because the sound makes a noise.

### Configuration
Arch linux kde

**Version of Telegram Desktop:**
2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Arch linux official packages ( pacman -S ).

**Comment by ilya-fedin** [comment]
#9980
