### ISSUE TITLE
VS2019 Build: This perl implementation doesn't produce Windows like paths

### ISSUE THREAD

**Issue by pedy** [telegramdesktop/tdesktop#10225]
Following [Build instructions for Visual Studio 2019](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md), after entering the following command:
`perl Configure no-shared no-tests debug-VC-WIN64A`
I face this output:
```
Configuring OpenSSL version 1.1.1j-dev (0x101010a0L) for debug-VC-WIN32
Using os-specific seed configuration

******************************************************************************
This perl implementation doesn't produce Windows like paths (with backward
slash directory separators).  Please use an implementation that matches your
building platform.

This Perl version: 5.26.2 for x86_64-msys-thread-multi
******************************************************************************
```
The instructions mentions _Strawberry Perl_ and I've installed _strawberry-perl-5.32.0.1-64bit.msi_. What should change?

**Comment by john-preston** [comment]
@pedy I think your perl is from msys, I guess you need to check that strawberry perl is the first perl in your PATH.
