### ISSUE TITLE
All chats are now showing up on the left instead of left and right

### ISSUE THREAD

**Issue by RedditReeker** [telegramdesktop/tdesktop#10221]
### Steps to reproduce
1. Go on telegram
2. check a chat
3. everything is showing up as on the left

### Expected behaviour
Tell us what should happen
it should be on the left and right
### Actual behaviour
Tell us what happens instead
just on the left
### Configuration
windows 10 pc
**Operating system:**
windows
**Version of Telegram Desktop:**
most recent
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
disable adaptative layout on settings.
