### ISSUE TITLE
Notification Tone not selectable on Mac OS 10.13.6

### ISSUE THREAD

**Issue by OrganicChem** [telegramdesktop/tdesktop#10236]
Mac OS: 10.13.6 (High Sierra)
Mac Model: 27" Imac Desktop
Telegram version: 7.3 (211334) Stable

In Preferences>Notifications and Sounds> Notification is set to default and other options are not available.

**Comment by ilya-fedin** [comment]
You confused with https://github.com/overtake/TelegramSwift
