### ISSUE TITLE
Export function stuck on some medias

### ISSUE THREAD

**Issue by stranck** [telegramdesktop/tdesktop#10232]
While using the export function with the following settings, it remains consistently stuck while downloading some medias.
![image](https://user-images.githubusercontent.com/16164827/105896631-587c7d80-6017-11eb-8c02-a239241595fc.png)

It happened with stickers:
![image](https://user-images.githubusercontent.com/16164827/105896598-4ef31580-6017-11eb-8019-b427a94c9a87.png)

and with voice messages:
![image](https://user-images.githubusercontent.com/16164827/105896733-78ac3c80-6017-11eb-9ebd-cec3b979eb7c.png)

I don't know which is the sticker that casues this, but I was able to find the problematic voice message. Comes out that you *can't* download it in any platform (Tested plus messanger, Telegram, Telegram X on android; Telegram X on iOs; Telegram desktop on various PCs) and if you try to call the `getFile` function via the bots api, it just waits for 10 secs and then returns `{"ok":false,"error_code":400,"description":"Bad Request: wrong file_id or the file is temporarily unavailable"}`.

I can understand that this is a problem with telegram itself, so **I'm here to simply ask if the export function could just skip these problematic files**. I checked a backup I did back in 2018 (Precisely, 2018-06-30), when the export function was still in BETA, and I found out that since that time that voice message has been problematic. However, as shown in the following screenshot, the export function that was still in BETA managed to recognize the problem, skip it, and continue the backup. Is it possible to do the same also today?
![image](https://user-images.githubusercontent.com/16164827/105897473-7dbdbb80-6018-11eb-81ea-1ed654cc30a8.png)

I've forwarded the voice message to a telegram channel, so you can **reproduce the bug** https://t.me/joinchat/QvpntQX0k4gMSYEQ

### Expected behaviour
The export function should mark the "bad" media files as "undownloadable" media and continue in the export function

### Actual behaviour
The export got stuck in exporting "bad" media files that couldn't be downloaded in any way from Telegram itself

### Configuration
**Operating system:** Windows 10 Pro 18363 

**Version of Telegram Desktop:** 2.5.1

**Used theme**: Tinted with night mode

**Comment by lucariokun** [comment]
I've been able to reproduce th error.

**Comment by ilya-fedin** [comment]
#8890
