### ISSUE TITLE
Indicator ubuntu unity 14.04

### ISSUE THREAD

**Issue by dimuravyev** [telegramdesktop/tdesktop#1023]
Telegram 0.8.52
https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/89

But if i downgrade to 0.8.38 no telegram indicator in tray.

**Comment by auchri** [comment]
Please describe your issue and don't just link to another one

**Comment by bil-elmoussaoui** [comment]
Well, the issue is that Telegram is not detecting correctly the libappindicator even if it's installed in Ubuntu Unity 14.04. Telegram in that case uses Qt indicator, but it's not the ideal for Ubuntu system ;)

**Comment by dimuravyev** [comment]
In Telegram 0.8.38 i used custom tray icon by change icons in 
`~/.TelegramDesktop/tdata/ticons`
After update to latest version, telegram stopped using icons in   
`~/.TelegramDesktop/tdata/ticons`.
I tried downgrade to 0.8.38, but telegram indicator missing.
 
```
$ ./Telegram
libs init..
loading gtk-3 with version 0..
could not load gtk-3 without version.
loading gtk-x11-2.0 with version 0..
could not load gtk-x11-2.0 without version.
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
```

**Comment by bil-elmoussaoui** [comment]
Opening telegram in my case shows this 
```bash
$ ./Telegram
libs init..
loading appindicator3 with version 1..
loaded appindicator3 with version 1!
loading gtk-3 with version 0..
loaded gtk-3 with version 0!
loaded gtk funcs!
loaded appindicator funcs!
status icon api loaded
```

**Comment by auchri** [comment]
I think because the newer versions use a newer version of qt

**Comment by bil-elmoussaoui** [comment]
@auchri i'm using the latest version of telegram too and it works in my case ;)

**Comment by auchri** [comment]
tdesktop uses the qt methods to detect libraries, so I think it's a issue of qt :)

**Comment by telegramdesktop** [comment]
@dimuravyev I've used libappindicator directly only while Qt tray icons were not working in Ubuntu Unity. I'm afraid my own implementation won't be better, so I'll stay with the Qt implementation where I can.

**Comment by bil-elmoussaoui** [comment]
@telegramdesktop if you can just change the folders in tmp like the ones used by Sni-Qt to make it possible to change the icons.
