### ISSUE TITLE
Client won't preview uncompressed image from clipboard when enabled 'Ask download path for each file'

### ISSUE THREAD

**Issue by mooons** [telegramdesktop/tdesktop#10237]
### Steps to reproduce
1. Settings - Advanced - **Check** 'Ask download path for each file' (By default this is unchecked, files will be auto downloaded to user's `Downloads\Telegram Desktop` directory)
2. Restart Telegram Desktop
3. Copy an image to the clipboard (for repro, simply Win+Shift+S take a random area screenshot), then paste the image to a chat, say, "Saved Messages".
4. Uncheck 'Compress images', send.
5. Click on the upload file, it won't show the in-app preview.

### Expected behaviour
In Step 4 it should show an in-app preview of the image.

In fact, if you go back to Settings - Advanced and **uncheck** 'Ask download path for each file' back. Then click that same image file in the chat, it will show the image. I suspect this has something to do with the desktop client having to download the file first before showing preview, but when 'Ask download path for each file' is checked, it won't download the file (should expect a dialogue box to save the file, or just save it to %temp% and preview it IMO).

~~This bug may apply to videos as well.~~

### Actual behaviour
As described in Step 5.

### Configuration
**Operating system:** Windows 10 20H2 19042.746

**Version of Telegram Desktop:** ~~2.5.1~~ 2.5.8

**Used theme**: Night mode

**Comment by mooons** [comment]
The issue is likely caused by the failure of `data->saveFromDataSilent()` in `data_document.cpp`:

https://github.com/telegramdesktop/tdesktop/blob/3251b8bf6e740e55777e85d63065a61e43df54fe/Telegram/SourceFiles/data/data_document.cpp#L355

This bug can be triggered with these condition combined:
1. 'Ask download path for each file' is checked
2. and the file is an image
3. and the original file on the disk does not exist at its location any more

**Comment by john-preston** [comment]
@mooons I can't reproduce that.

1. I've changed the settings.
2. I've taken an image 123.jpg and sent it to a chat.
3. I've removed the file from disk.
4. I've clicked on the sent file.

At click the downloaded file turned to a non-downloaded (with an arrow down on the thumbnail) and a "Save file" dialog box appeared. When I chose a filename it saved the file there. When I clicked on the file once again, it opened the file in the in-app viewer.

**Comment by mooons** [comment]
@john-preston

Try taking a random screenshot with Win+R (so the image is saved to the clipboard), and paste it in a chat, uncheck compress images, Send. Then attempt to open the image.

**Comment by mooons** [comment]
So it looks like the problem can actually be in the filename generation? when the source image file isn't coming from the disk.

**Comment by john-preston** [comment]
No, there is a special case for the images sent from clipboard. They're allowed to be saved to the encrypted cache (so that you don't need to create such file on disk after sending), but this case is not checked when trying to view such image.

**Comment by john-preston** [comment]
@mooons Please try the latest commit from the `dev` branch.

**Comment by mooons** [comment]
> @mooons Please try the latest commit from the `dev` branch.

@john-preston Can confirm https://github.com/telegramdesktop/tdesktop/commit/5feb381cb26fe4dda0e3438f4635e70ccf05fafe fixed the issue. Thanks! Will close my PR.
