### ISSUE TITLE
[Feature Request] Option. Hide previews of next photos while single image is open

### ISSUE THREAD

**Issue by iGrog** [telegramdesktop/tdesktop#10238]
### Is your feature request related to a problem?
Problem is, that if single image is open to full screen for viewing, the small preview images of next photos or description text appears on the bottom of the screen. And they hide usually a signifint part of image that is currently open.

### Describe the solution you'd like
Add an option in settings to show of hide these previews/descriptions in full screen mode.

### Describe alternatives you've considered
Yes, I know that I can move mouse away from the picture (for example to second monitor) then small previews dissapear. But it is not a good option, as hiding is happening by timer and small previews appear again if mouse is entered back to image.

### Additional context
See pictures below to better understand my problem.

![Image 1](https://snipboard.io/ivAmE7.jpg)
![Image 2](https://snipboard.io/HrhyDI.jpg)

**Comment by ilya-fedin** [comment]
#7931?
