### ISSUE TITLE
ux error at handling autocompletion of mention/username

### ISSUE THREAD

**Issue by kuesji** [telegramdesktop/tdesktop#10233]
broken autocomplete for mention

### Steps to reproduce
1. make sure about your name and username doesn't starts with `mes`  
2. join a group where at least one or two user with name or username starting with `mes`
3. typing `@mes` and pressing tab key autocompletes to your username 

### Expected behaviour
autocompletes to other user with name or username starts with `mes`

### Actual behaviour
autocompletes to my username

### Configuration
**Operating system:** `arch linux`

**Version of Telegram Desktop:** `2.5.1`

**Installation source (Linux Only)** - `distribution package`

**Used theme**: `tinted`

**Comment by john-preston** [comment]
"Saved messages" is indexed in the current user-s name for all autocompletes, that way you find your Saved Messages chat in the chats list on the left. Right now the index is application-wide, so in all places that allow you to filter users by a string the same index is used (which includes users first name, last name, username, phone number, some other things, like "Saved Messages" for the current user).

**Comment by kuesji** [comment]
maybe we should remove this "feature" because android or ios client doesn't do this and changing behaviour on desktop brokes user experience. typing some characters and pressing tab should work on name/username starts with `me` too.

**Comment by john-preston** [comment]
@kuesji This is not a feature on it's own, it is a side effect of the feature "Type 'mes' in filter of your chats to find 'Saved Messages' chat". If we just remove this feature, then it won't work.
