### ISSUE TITLE
Empty call window title. Difficult to find/select the window on linux desktop.

### ISSUE THREAD

**Issue by zen2** [telegramdesktop/tdesktop#10243]
### Steps to reproduce
1.     Initiate a voice call

### Expected behaviour
The voice call window have a tittle with contact name.

### Actual behaviour
Voice call window appear with an empty title.
The voice call window appear with no title in tasks bar or windows list.

### Configuration
**Operating system:**
Gentoo Linux

**Version of Telegram Desktop:**
Telegram Desktop 2.5.7, PC 64bit, Linux X11 glibc 2.32

**Installation source (Linux Only)**
binary release 2.5.7 from Github

**Used theme**:
Dark

**Comment by eworm-de** [comment]
Ah, just wanted to open an issue for this myself... 😜
So yes, please add a title - and an icon, that's missing as well.

**Comment by Mehrshad3** [comment]
> ### Expected behaviour
> The voice call window have a title with contact name.

Why this is the excepted behavior?

**Comment by eworm-de** [comment]
I would be happy to have a title at all. Adding a contract name would be nice but is not a must.

**Comment by eworm-de** [comment]
Just had another call. This is what the window looks like in task bar (marked with a red ellipse).

![Screenshot_2021-02-01_10-38-35](https://user-images.githubusercontent.com/970853/106441756-bb886d00-647a-11eb-943d-c4307c51e248.png)

Really annoying if you do not find the window to answer the call...

**Comment by zen2** [comment]
> > ### Expected behaviour
> > The voice call window have a title with contact name.
> 
> Why this is the excepted behavior?

Because users need to identify differents windows from different applciations on a multi-tasking desktop.
On linux, we got workspaces and so we can move windows between workspaces.
The main telegram window have a title 'telegram' so it's easy to identify it and select it in a window list.
When you make a call, you can change current workspace and window focus on another application.
Later when you want to terminate your call, you need to find the call window and actually you have to know that is the one without title that is hard to find depending on your desktop windows selector.

More about this: https://ux.stackexchange.com/questions/35782/is-desktop-window-title-necessary

Finally to have the contact name as title seems logical since you got the main window labelled as telegram (that permit to read/send message to others users while you're in a call) and call window need to have a different name to be identified.
Since the purpose of this window is a voice call with someone, it seems logical to get the contact name in this title like "Username voice call".

**Comment by eworm-de** [comment]
I think you have just one voice call at a time, no? So IMHO something like "_Telegram - Voice Call_" or "_Telegram - Video Call_" would be fine. But I would still prefer the contact name to be included.

BTW, for group voice chat we see the group name in title, an icon is still missing, though.

**Comment by zen2** [comment]
> I think you have just one voice call at a time, no? So IMHO something like "_Telegram - Voice Call_" or "_Telegram - Video Call_" would be fine. But I would still prefer the contact name to be included.
> 
> BTW, for group voice chat we see the group name in title, an icon is still missing, though.

That's a good point. So group voice chat window got the group name as title.
It seems really coherent that voice/video call window get the contact name as title.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by eworm-de** [comment]
Sadly it is.

**Comment by ilya-fedin** [comment]
> this bug is still valid?

It's enhancement rather than a bug

**Comment by eworm-de** [comment]
> It's enhancement rather than a bug

I disagree here. Changing an existing title to something better is an enhancement.
The actual situation with no title at all is a bug.

**Comment by zen2** [comment]
> > It's enhancement rather than a bug
> 
> I disagree here. Changing an existing title to something better is an enhancement.
> The actual situation with no title at all is a bug.

That's why it's called an issue on github ^^
Anyway it should be a simple thing to fix and this issue is really a problem for real usage.
It make appear desktop window selection completelly broken:
- on window task bar if it exist
- on window select popup
- on alt-tab window selector

In addition it's not possible to select properly the window property to manage it for auto-tiling window manger or to force position/size using classical X window management because you got only an ID and no pattern to match the name.

**Comment by ilya-fedin** [comment]
> I disagree here.

Looking at how long this issue open, this looks like the current state is intended and is not going to be changed

**Comment by eworm-de** [comment]
But it does not make any sense for such a state to be intended, no?
Let's see it the other way round: The issue has not yet been closed, so it is not intended.

**Comment by ilya-fedin** [comment]
Enhancement issues are not being closed here usually, they can stay open for years without decision to implement or not
