### ISSUE TITLE
[Feature Request] Create a poll/feedback when someone joins the channel

### ISSUE THREAD

**Issue by AngryPhantom** [telegramdesktop/tdesktop#10245]
### Is your feature request related to a problem?
I need to have some kind of a feedback to know how & where people found my channel.

### Describe the solution you'd like
It would be really great to have an option to create a poll (or any other type of feedback) which will be triggered when someone **joins the channel**.

### Describe alternatives you've considered
Pin a poll and then make updates reminding the subscribers to vote from the pinned message, which is a bit uncomfortable.

Thank you very much in advance.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
