### ISSUE TITLE
prefix file in tdata

### ISSUE THREAD

**Issue by peach-lasagna** [telegramdesktop/tdesktop#10248]
### Steps to reproduce
1. open \Roaming\Telegram Desktop\tdata\prefix
2. Content:
![изображение](https://user-images.githubusercontent.com/59787538/106235983-7ff96300-622e-11eb-8791-1b9709d281fd.png)
3. open link in browser(i tried Firefox and chrome)
![изображение](https://user-images.githubusercontent.com/59787538/106236060-a5866c80-622e-11eb-86c4-732cec31003a.png)
![изображение](https://user-images.githubusercontent.com/59787538/106236124-c3ec6800-622e-11eb-842c-0aac6a2f9175.png)
![изображение](https://user-images.githubusercontent.com/59787538/106236212-ed0cf880-622e-11eb-8f82-1170e284d368.png)

4. WTF ? Why it is in blocklist ? i'm from Russia, telegram was in the blocklist, but was removed from it.
### Expected behaviour
i can go on link

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.5.7

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this doesn't looks something related to this tracker.

**Comment by peach-lasagna** [comment]
i remember you =_=

**Comment by ilya-fedin** [comment]
Why do you report error of your ISP to tdesktop?
