### ISSUE TITLE
A separate bookmark button

### ISSUE THREAD

**Issue by jayantapandit** [telegramdesktop/tdesktop#10258]
### Is your feature request related to a problem?
It takes quite a few number of taps to bookmark a selected message object by forwarding it to Saved Messages chat box. 

### Describe the solution you'd like
A bookmark button that appears upon selecting a message, a click on which will transfer the item to Saved Messages directly effectively bookmarking it quickly for the user.

### Describe alternatives you've considered
No alternatives considered.

### Additional context
No additional context.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6505
