### ISSUE TITLE
Build Error tg_owt webrtc:DEPRECATED

### ISSUE THREAD

**Issue by Tuxino88** [telegramdesktop/tdesktop#10257]
i compiled from source tg_owt and than telegram but the latter fail with this output below : 

![Schermata da 2021-01-28 22-50-20](https://user-images.githubusercontent.com/75674245/106258168-c98d8200-621d-11eb-8556-d0946afb26d9.png)

**Comment by ilya-fedin** [comment]
Shared build of tg_owt is community maintained. No one interested contributed a fix yet.

**Comment by Tuxino88** [comment]
ok so if i disable webrtc i lose call support? (at the moment)
I just disable it like this?
`-DDESKTOP_APP_DISABLE_WEBRTC_INTEGRATION:BOOL=ON`

**Comment by ilya-fedin** [comment]
Build without WebRTC is not supported for a long time

**Comment by Tuxino88** [comment]
Ok so version 2.5.7 is currently not buildable? having problems with GTK I wanted to switch to the Dev version

**Comment by john-preston** [comment]
Why not build tg_owt statically, like in tdesktop official builds?

**Comment by Tuxino88** [comment]
ah I didn't know, I don't know how, can you help me?

**Comment by ilya-fedin** [comment]
> ah I didn't know, I don't know how, can you help me?

You can use official building instructions

**Comment by Tuxino88** [comment]
Ok thanks for all :)

**Comment by Tuxino88** [comment]
**sorry if I reopen but does not find the dependency which is still installed**

CMake Error at cmake/target_link_static_libraries.cmake:41 (message):
  Could not find static library libxkbcommon.a
