### ISSUE TITLE
Closing parenthesis wrongfully being placed on new line 

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#10255]
### Steps to reproduce
1. send a text with a line that ends with a closing parenthesis "`)`"

### Expected behaviour
The app doesn't put the closing parenthesis on a newline - it should put in the new line also the ending word if there is no space between the word and the parenthesis, or size the bubble differently

### Actual behaviour
The app pus on the new line the parenthesis alone

![image](https://user-images.githubusercontent.com/16143208/106249731-06a04700-6213-11eb-8c21-34153f7fafe3.png)

### Configuration
**Operating system:** Windows 10/linux mint

**Version of Telegram Desktop:** 2.5.7

**Used theme**: stock dark

**Comment by RememberTheAir** [comment]
Yes, still an issue

**Comment by RememberTheAir** [comment]
unstale

**Comment by RememberTheAir** [comment]
unstale

**Comment by RememberTheAir** [comment]
unstale

**Comment by ilya-fedin** [comment]
seem to be a dup of #7615
