### ISSUE TITLE
Telegram can't building FATAL

### ISSUE THREAD

**Issue by Sarptra** [telegramdesktop/tdesktop#10259]
CMake Error at cmake/external/qt/package.cmake:23 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:37 (include)

-- Configuring incomplete, errors occurred!

working with macOS big sur latest with Xcode latest

**Comment by john-preston** [comment]
@Sarptra Looks like Qt was not built or installed the way it is stated in the instructions.

**Comment by Sarptra** [comment]
How can I install?
