### ISSUE TITLE
Scheduling a message when user goes online option disappears after scheduling a message for another contact

### ISSUE THREAD

**Issue by arni1981** [telegramdesktop/tdesktop#10250]
This is a follow-up report to this #10082, which was fixed (partially as it now appears) in 2.5.7

### Steps to reproduce
1. Open any contact
2. Right-click on a sticker and schedule a message
3. Open another contact and right-click on a sticker and schedule a message

### Actual behaviour
The option to send when user is online is gone.
There is also an extra cancel button appearing from somewhere.

![image](https://user-images.githubusercontent.com/706797/106239897-40fdea00-61fb-11eb-82e9-9941e133856c.png)

### Configuration
**Operating system:**
Ubuntu 20.04

**Version of Telegram Desktop:**
2.5.7

**Installation source (Linux Only)** 
Downloaded the Linux desktop version from official website,

**Comment by 23rd** [comment]
> The option to send when user is online is gone.

Unfortunately, I can't reproduce this.

**Comment by arni1981** [comment]
I've tried and confirmed this behavior multiple times, it happens both with the downloaded version and a freshly installed Snap package, versions 2.5.7.

**Comment by arni1981** [comment]
Hmm, with 2.5.8 this has changed slightly.
The extra cancel is gone.

The send as online option now disappears when I try to send a schedules message to a third contact.
To be precise:

1. Open any contact
2. Right-click on a sticker and schedule a message
3. Open another contact and right-click on a sticker and schedule a message
4. Open yet another contact and right-click on a sticker and schedule a message.

-> Now the option to send when online has disappeared again.

**Comment by 23rd** [comment]
Are you sure these contacts are sharing their Online status with you?

**Comment by arni1981** [comment]
That's a very good catch, I don't share my online status with most contacts so that is the reason in all likelihood.
I consider this fixed for me then at least.
