### ISSUE TITLE
Missing `Socks/MTproto` proxy after crash.

### ISSUE THREAD

**Issue by 2i3r** [telegramdesktop/tdesktop#10252]
When the app opens after a crash and tries to check for update, only `HTTP` proxy can be configured.  no `Socks/MTProto`  option are available, which are in normal application modes.

### Steps to reproduce
1.  crash telegram client. (type `crashplease` in settings.)
2.  in proxied network where direct connection to `telegram server` cannot be made (or simply go offline), open telegram client again. 
3.  a window should be opened, with title  `Telegram`, and a line which tells it crashed before.  next to `Checking for updates ...`/`Update Check failed :(`, there is a clickable `NETWORK SETTINGS` label, click on it. `HTTP Proxy Settings` opens.

### Expected behaviour
in `Network Settings` the `Socks/MTproto` protocols should be selectable. or even better the list of configured proxies should be loaded to choose from.
I assume it could try to use previously set proxy.

### Actual behaviour
in `Network Settings` only `HTTP` proxy could be configured.

### Configuration
**Operating system: Windows 10**

**Version of Telegram Desktop:**2.5.7

**Used theme**: 

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@2i3r This window is outside of the app main code as much as possible. It doesn't have access to mtproto protocol or to settings of the app, which hold the proxies as well.

**Comment by 2i3r** [comment]
@john-preston I understand that it need to work independently and works even app keep crashes or settings are broken, though it could **try** to read setting files and use a separate old and very stable version of `MTproto` to start a minimal proxied connection. 

Note that in lots of restricted network situations, `HTTP` proxy is not always available.

**Comment by john-preston** [comment]
@2i3r Well, in those cases I'll ignore the crash reports and you'll have to skip reporting and try to autoupdate from the app. If it crashes on start you'll have to download a new version manually.

A separate mtproto implementation only for autoupdating in cases when the app crashes on start and there is no way to autoupdate by https — too much work for too rare cases, sorry.

**Comment by ilya-fedin** [comment]
#4867
