### ISSUE TITLE
Amount of unread messaged disappeared in desktop version 2.5.7

### ISSUE THREAD

**Issue by alxdjz** [telegramdesktop/tdesktop#10251]
Notification setting are set to show amount of unread messages both in muted and unmuted chats. However amount of unread messaged is not displayed on tray icon. 

Please find out snapshot of settings and tray icon below
![image](https://user-images.githubusercontent.com/37000960/106243338-474f8e80-621a-11eb-8be6-5ba4e5248ce9.png)

![image](https://user-images.githubusercontent.com/37000960/106243824-0ad06280-621b-11eb-8141-b861d5e78674.png)

Expected behavior: amount of unread messages is displayed on tray icon like it was in previous version.

**Comment by ilya-fedin** [comment]
Yeah, counter won't be displayed if your icon theme has icon with a dot-styled indicator. If you want the counter, change your icon theme.

**Comment by alxdjz** [comment]
Could you please briefly describe the way to change icon theme? Can't find such option in settings. Sorry if this question is already answered. Quick search did not help me to find the answer.

**Comment by ilya-fedin** [comment]
It should be somewhere in your system settings

**Comment by alxdjz** [comment]
I've found it in qt5ct application. This application allows to change various settings for qt5 applications including icons style. My issue was that for some reason used icon style does not contain telegram icons. I suppose that default icon is used in this case. 

I use Linux Mint 19 with cinnamon DE. 

Thanks for advice and sorry to bother you.
