### ISSUE TITLE
[Feature Request] Add TOTP as alternative way to login

### ISSUE THREAD

**Issue by NotStatilko** [telegramdesktop/tdesktop#10253]
### Is your feature request related to a problem?
If users lose access to the SIM card, they lose access to their accounts. An alternative method of getting the code is needed. [**TOTP**](https://en.wikipedia.org/wiki/Time-based_One-Time_Password) can also be used to change password in case user forgot it and haven't access to the email.

### Describe the solution you'd like
"Use one-time code" on login screen as alternative to receiving code to phone number.

**Comment by RafaelLinux** [comment]
It seems a good way to solve a possible problem with SIM card.
