### ISSUE TITLE
latest beta version bug - schedule message dialog has two cancel button

### ISSUE THREAD

**Issue by amirmahdi-nsh** [telegramdesktop/tdesktop#10261]
### Steps to reproduce
1. Open telegram desktop
2. Select a chat(there is no different which kind of)
3. Try to send a schedule message by right clicking on the send button and selecting `Schedule message`

### Expected behaviour
There should be one cancel button :))

### Actual behaviour
There is two Cancel button

### Configuration
**Operating system:**
Arch Linux
**Version of Telegram Desktop:**
2.5.7
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
offical website

**Used theme**:
default

**Comment by amirmahdi-nsh** [comment]
Seems [this commit](https://github.com/telegramdesktop/tdesktop/commit/1ec6b4313d1822c55e8e926379c56838dea5d1ff) solved this bug.
I will wail until the release and if it is really fixed I'll close this issue.

**Comment by ilya-fedin** [comment]
#10249
