### ISSUE TITLE
Recent update broke unread message badge counter

### ISSUE THREAD

**Issue by Entropy0** [telegramdesktop/tdesktop#10263]
### Steps to reproduce
1. Install most recent version
2. Set "Count unread messages" to true
2.a. Set  "Include muted chats in unread count" to true
3. Wait until you get a message

### Expected behaviour
A badge with the number of unread messages appears on the tray icon.
The badge will be grey if you selected to include muted chats and the message is in a muted chat.

### Actual behaviour
Only a tiny, barely discernible blue dot appears, but no number.
No dot appears whatsoever for messages in muted chats.

### Configuration
**Operating system:**
Linux
**Version of Telegram Desktop:**
2.5.7
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
official website
**Used theme**:
default

**Comment by ilya-fedin** [comment]
It depends on icon theme you chosen. If you have an icon theme with a dot indicator, counter overlay won't be added.

**Comment by Entropy0** [comment]
It used to work just fine up until the most recent update.

But I cycled through all the available themes nevertheless and found that the telegram icon stays the same no matter which theme I select while the rest of the icons in the tray vary wildly.

**Comment by ilya-fedin** [comment]
> It used to work just fine up until the most recent update.

Yeah, the behavior was changed since most users except monochrome icon to not to be overlapped by the counter.

> But I cycled through all the available themes nevertheless and found that the telegram icon stays the same no matter which theme I select while the rest of the icons in the tray vary wildly.

Have you restarted tdesktop after each icon theme change?

**Comment by Entropy0** [comment]
> > It used to work just fine up until the most recent update.
> 
> Yeah, the behavior was changed since most users except monochrome icon to not to be overlapped by the counter.

Honestly, I don't want a monochrome icon at all - I was far more happy with the old blue-and-white one. But sadly Telegram seems to be ignoring the ones I put into ~/.local/share/TelegramDesktop/tdata/ticons so I was fine with the monochrome version - as long as there was a counter :-/
> 
> > But I cycled through all the available themes nevertheless and found that the telegram icon stays the same no matter which theme I select while the rest of the icons in the tray vary wildly.
> 
> Have you restarted tdesktop after each icon theme change?

I have now: Still no change to the icon at all.

Do you know of a mate-theme that should have the badge counter visible so that I can confirm whether this works as intended?

**Comment by ilya-fedin** [comment]
> Do you know of a mate-theme that should have the badge counter visible so that I can confirm whether this works as intended?

Badge counter will be visible as long as your icon theme doesn't have `telegram{,-mute,-attention}-panel` icons.
If you use MATE, please note that your distro maintainer disabled GTK integration and there are no guarantee that tdesktop will behave correctly due to this.

**Comment by Entropy0** [comment]
I double-checked now by manually installing a theme and checking for the files you mentioned and it appears that Telegram simply _ignores_ whatever icon the theme provides - it is always the same default white one, regardless of whether the theme contains any of `panel/*/telegram{,-mute,-attention}-panel.svg` or not.

And mate does support gtk just fine otherwise…

If you tell me what logs you need I would be happy to provide them.

**Comment by grayich** [comment]
same
the topic has not changed, the counter has disappeared 

make the counter be independent of the theme 
there is no life without a counter

**Comment by ilya-fedin** [comment]
> And mate does support gtk just fine otherwise…

I mean tdesktop gtk integration. Some distro maintainers disable it. tdesktop will write to terminal if that's the case.

>  it is always the same default white one, regardless of whether the theme contains any of `panel/*/telegram{,-mute,-attention}-panel.svg` or not.

Can you show how it looks like? It's also worth to check the value of `echo $QT_QPA_PLATFORMTHEME`, maybe you're using something like qt5ct and you should change qt5ct settings then.

**Comment by ilya-fedin** [comment]
> make the counter be independent of the theme

Currently no way. See #6721. Adding options requires permission from @john-preston and he doesn't give one.

**Comment by Entropy0** [comment]
> > And mate does support gtk just fine otherwise…
> 
> I mean tdesktop gtk integration. Some distro maintainers disable it. tdesktop will write to terminal if that's the case.

The only output Telegram gives when starting is
```
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
```

> > it is always the same default white one, regardless of whether the theme contains any of `panel/*/telegram{,-mute,-attention}-panel.svg` or not.
> 
> Can you show how it looks like? It's also worth to check the value of `echo $QT_QPA_PLATFORMTHEME`, maybe you're using something like qt5ct, you should change qt5ct settings then.

Interesting, I had never heard of qt5ct. For some reason every try icon _other than_ that of Telegram is controlled by setting the theme via `mate-appearance-properties` but Telegram (and only Telegram) adheres to the changes set by `qt5ct`. Weird.

For anyone who stumbles upon this thread via google:
If a theme doesn't have any `panel/*/telegram{,-mute,-attention}-panel.svg`, the icon that gets displayed is chosen from `apps/*/` instead of `panel/*/` (`org.telegram.desktop.svg`, `telegram-desktop.svg` and `telegram.svg` all seem to be found) and doesn't have any indicator at all (neither little dot not counter).  
And if a theme doesn't have an icon _there_ the tray icon simply disappears when activating it via `qt5ct` but if you then click the spot where it should be it reappears as the default icon and has a badge counter!

Thank you for the help @ilya-fedin !

**Comment by ilya-fedin** [comment]
> For some reason every try icon _other than_ that of Telegram is controlled by setting the theme via `mate-appearance-properties` but Telegram (and only Telegram) adheres to the changes set by `qt5ct`. Weird.

Because Telegram is a qt application. If you will install something like VLC or qBittorrent, they will also be controlled by qt5ct...

**Comment by ilya-fedin** [comment]
> If a theme doesn't have any `panel/*/telegram{,-mute,-attention}-panel.svg`, the icon that gets displayed is chosen from `apps/*/` instead of `panel/*/` (`org.telegram.desktop.svg`, `telegram-desktop.svg` and `telegram.svg` all seem to be found) and doesn't have any indicator at all (neither little dot not counter).

I checked and I see that the counter is present in that case, as it supposed to:
![image](https://user-images.githubusercontent.com/17829319/106317039-98d13b00-6265-11eb-9ccc-95d70ae32099.png)
