### ISSUE TITLE
Notification counter in system tray not working

### ISSUE THREAD

**Issue by beglort** [telegramdesktop/tdesktop#10264]
### Steps to reproduce
1. Install telegram-desktop 2.5.7.r4
2. open telegram desktop and be sure notifications are enabled
3. receive some messages

### Expected behaviour
The notification counter in system-tray should become red and show a number of received messages

### Actual behaviour
The icon tray doesn't show any red dot or any number of received messages 

### Configuration
**Operating system:** 
Manjaro 20.2.1 + kernel 5.10.11 + DE: KDE 5.78.0 / Plasma 5.20.5

**Version of Telegram Desktop:**
 2.5.7.r4 
** Latest working version of Telegram Desktop:** 
2.5.5.r1 

**Installation source (Linux Only)** - package from distribution, repository: community 

**Used theme**: 
GTK Theme: Breeze [GTK2/3] 
Breeze Icon theme 
Plasma theme: Breeze

** Output if launched from terminal** 

![Screenshot_20210129_181935](https://user-images.githubusercontent.com/47941965/106306629-3e7cae00-6256-11eb-9fcf-ea1da160fd88.png)

**Comment by ilya-fedin** [comment]
#10263 #10251

**Comment by beglort** [comment]
> #10263 #10251

None of the above seems to apply with kde plasma, one is about mate desktop and another about cinnamon. 
I tried all the defaults theme and downloaded many others.
The new tray icon works only when I use a monochrome icon theme: it appears just as a simple dot (expected behaviour)

**expected**
![Screenshot_20210130_003326](https://user-images.githubusercontent.com/47941965/106338393-9d104f00-628b-11eb-8162-27a05f326600.png)

Breeze theme doesn't use a monochrome icon, nor monochrome was used by any other theme I tried, still the counter badge is not present.

**not working**
![Screenshot_20210130_003356](https://user-images.githubusercontent.com/47941965/106338489-d8ab1900-628b-11eb-9bd9-0d69163ff399.png)

**Comment by ilya-fedin** [comment]
@beglort looks like it is a bug in KDE's kiconthemes framework. Unfortunately, we can't fix third-party libraries, I recommend to install the binary from https://desktop.telegram.org where we can control used libraries.

**Comment by beglort** [comment]
@ilya-fedin thank you, I will report the issue to KDE then, I'm in the unstable branch so I guess as soon as the other users will upgrade plasma the problem will be noticed. For now I use a theme with monochrome since is the only one working

**Comment by ilya-fedin** [comment]
@beglort it's worth to mention in the report that the bug is that `QIcon::hasThemeIcon("telegram-attention-panel")` returns true even when only `telegram` icon is present in the icon theme.

**Comment by ilya-fedin** [comment]
> I'm in the unstable branch so I guess as soon as the other users will upgrade plasma the problem will be noticed.

This bug is not only in unstable branch of Plasma, it is reproducible in stable versions as well.

**Comment by beglort** [comment]
> @beglort it's worth to mention in the report that the bug is that `QIcon::hasThemeIcon("telegram-attention-panel")` returns true even when only `telegram` icon is present in the icon theme.

I will do, thank you for all the info

**Comment by soredake** [comment]
@ilya-fedin same bug with flatpak version, icon worked in previous versions of telegram flatpak, IIRC

**Comment by ilya-fedin** [comment]
We can't do anything except of waiting a fix from KDE side

**Comment by soredake** [comment]
@beglort do you filled bugreport to kde?

**Comment by ilya-fedin** [comment]
> https://bugs.kde.org/show_bug.cgi?id=432293

So, they decided to "fix" it by providing monochrome icons instead of fixing actual bug in kiconthemes? :see_no_evil: 
Maybe we should do `QApplication::setDesktopSettingsAware(false)` on KDE in order to avoid injecting their libraries...

**Comment by soredake** [comment]
They fixed it, not ideal, but something.
![изображение](https://user-images.githubusercontent.com/5204968/107516856-ab2c6c80-6bb5-11eb-97c5-795b9470499b.png)

**Comment by beglort** [comment]
> > https://bugs.kde.org/show_bug.cgi?id=432293
> 
> So, they decided to "fix" this by providing monochrome icons instead of fixing actual bug in kiconthemes? see_no_evil
> Maybe we should do `QApplication::setDesktopSettingsAware(false)` on KDE in order to avoid injecting of their libraries...

I thought that with frameworks 5.79 we could choose between the monochrome and the original status icon since an user asked it [https://invent.kde.org/frameworks/breeze-icons/-/merge_requests/81](here) and received a positive reply.  
Then if is not the bug shouldn't be closed, a message counter is important

**Comment by beglort** [comment]
> They fixed it, not ideal, but something.
> ![изображение](https://user-images.githubusercontent.com/5204968/107516856-ab2c6c80-6bb5-11eb-97c5-795b9470499b.png)

this is the new plasma "fix" isn't there an option to have a real counter? 
Not really what I was asking when I filed the bug there 🙄

**Comment by ilya-fedin** [comment]
> and received a positive reply

I don't see one on the link. I see only suppositions.

**Comment by beglort** [comment]
> I see only suppositions.

I thought it was this:
"There is, you can specify an Icon by name and an OverlayIcon by pixmap. This was actually broken on plasma side but seems to be fixed now."
But it seems I just misunderstood it.

**Comment by ilya-fedin** [comment]
They meant applications developers by "you". And no, tdesktop doesn't support OverlayIcon by three reasons:
1. It brokes color scheme support anyway
2. The counter is unreadable with it
3. It's supported only Plasma, while tdesktop aims to be DE-neutral.

**Comment by beglort** [comment]
> They meant applications developers by "you". And no, tdesktop doesn't support OverlayIcon by three reasons:
> 
>     1. It breaks color scheme support anyway
> 
>     2. The counter is unreadable with it
> 
>     3. It's supported only by Plasma, while tdesktop aims to be DE-neutral.

OK, I got it. You've been very clear thank you.
So my best chance now is to use the version from the official telegram site (what I'm doing) or just accept the new plasma "improvement"

**Comment by ilya-fedin** [comment]
> So my best chance now is to use the version from the official telegram site (what I'm doing) or just accept the new plasma "improvement"

Yeah. And you will should remove these new icons as soon as they land you in order to have the counter even on official binary.

**Comment by beglort** [comment]
> > So my best chance now is to use the version from the official telegram site (what I'm doing) or just accept the new plasma "improvement"
> 
> Yeah. And you will should remove these new icons as soon as they land you in order to have the counter even on official binary.

Thank you for the tips.
I guess once these changes reach more kde users there will be many help requests on the various forum. I understand that monochrome is nicer, but the counter is a big help indeed

**Comment by ilya-fedin** [comment]
> but the counter is a big help indeed

Isn't counter on the taskbar icon enough?

**Comment by beglort** [comment]
> > but the counter is a big help indeed
> 
> Isn't counter on the taskbar icon enough?

Not really, because when I use a auto hiding dock it won't be shown. 
Some might just set telegram to start when system start and don't have the icon on the taskbar, but only in tray. 
Still the system tray is the place where users look for notifications, and the red dot is also easier to check than the blue dot in the blue taskbar icon.
These are just my opinions but I imagine other can have similar reasons

**Comment by Shatur95** [comment]
@ilya-fedin, why the issue was closed? It worked perfectly before 2.5.5:

![изображение](https://user-images.githubusercontent.com/22453358/108477689-384d8080-729c-11eb-9a90-80cc54fd6a0e.png)

But currently it displays only a single dot. If I change theme, them I will have a default Telegram icon instead of themed (as it 2.5.5).

**Comment by ilya-fedin** [comment]
Sorry, but you can't have counter on monochrome icon anymore. Since @john-preston doesn't allow to add an option for this, there's no other way except of don't add counter for all users of monochrome icons.

**Comment by Shatur95** [comment]
Thanks for the fast answer!

> Since @john-preston doesn't allow to add an option for this

@ilya-fedin , what's the problem with displaying an icon on a monochrome icon?

**Comment by ilya-fedin** [comment]
> what's the problem with displaying an icon on a monochrome icon?

what icon on a monochrome icon?

**Comment by Shatur95** [comment]
@ilya-fedin, sorry, I meant counter :)

**Comment by ilya-fedin** [comment]
> sorry, I meant counter :)

https://github.com/telegramdesktop/tdesktop/issues/10239

**Comment by Shatur95** [comment]
> #10239

@ilya-fedin, thanks for the info. I don't know why it was broken for @AndydeCleyre, but I also use Arch with KDE and had a nice-looking system tray:
![изображение](https://user-images.githubusercontent.com/22453358/108479492-79469480-729e-11eb-806b-f7f5708481f2.png)
Can can we have an option that allows to display a counter on monochrome icons?

**Comment by ilya-fedin** [comment]
> Can can we have an option that allows to display a counter on monochrome icons (e.g. returns behavior from 2.5.5)?



> Since @john-preston doesn't allow to add an option for this

**Comment by Shatur95** [comment]
> Since @john-preston doesn't allow to add an option for this

@ilya-fedin, I understand, I meant is there just a chance to reconsider this decision? Apparently, I'm not the only one complaining about the new change.

**Comment by ilya-fedin** [comment]
> I understand, I meant is there just a chance to reconsider this decision?

i don't know... ask @john-preston

**Comment by Shatur95** [comment]
> i don't know... ask @john-preston

Opened a proposal for it in #10407.

**Comment by orivej** [comment]
For the reference Telegram has stopped showing the counter in the tray since #10142.
