### ISSUE TITLE
[Feature Request] Allow downloading an entire album

### ISSUE THREAD

**Issue by FraMecca** [telegramdesktop/tdesktop#10275]
### Is your feature request related to a problem?
On the mobile client it is possible to download an entire album in a tap when the sender shares the album correctly. On the desktop client this is not possible as of 2.5.8

### Describe the solution you'd like
right click -> download album -> choose path

### Describe alternatives you've considered
Writing a python script but I don't want to deal with api keys. Or exporting a json and parsing it but that requires generating the json every time and duplicating the content

**Comment by Sonico98** [comment]
There's a discussion about this on #1382
