### ISSUE TITLE
Automatic media download option settings not saved or at least not shown that saved

### ISSUE THREAD

**Issue by necros2k7** [telegramdesktop/tdesktop#10278]
### Steps to reproduce
1. Go to Settings - Automatic media download (in priv. chats, in grps...)- set media limit to say 1mb 
2.  Close window
3.  Re-enter to Automatic media download (in priv chats, in grps..) 

### Expected behaviour
Entered value should be seen

### Actual behaviour
Default value shown

### Configuration
**Operating system:**
win10x64
**Version of Telegram Desktop:**
2.5.8x64
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#7190?
