### ISSUE TITLE
[Feature Request] Option to disable read receipt double check after reading messages

### ISSUE THREAD

**Issue by jayantapandit** [telegramdesktop/tdesktop#10279]
### Is your feature request related to a problem?
An option for the user to not let the other person know if one is viewing the others' messages would allow for more control over one's privacy, while still being able to read through the received messages after opening the chat.

### Describe the solution you'd like
A quick toggle to enable/disable read receipt

### Describe alternative solutions you have considered
This should be something enabled by default when a message from an unknown person is received, pretty much like the privacy feature for DMs in Instagram.

### Additional context
Telegram for Android has a similar feature which can be used to view a little non-scrollable window of the top of the recently received messsage thread like so:![Screenshot_20210131-194508.png](https://user-images.githubusercontent.com/55305804/106386845-f5b32980-63fc-11eb-824e-00f61623f86a.png)

The window appears on long press on display picture of the chat. The messages read this way are not 'marked as read' by the client until the user lifts up the window to open the maximized chat.

**Comment by RememberTheAir** [comment]
It would be against the API terms of service: https://core.telegram.org/api/terms (point 1.4). I think such suggestions belongs to https://bugs.telegram.org, Telegram's platform for platform-wise suggestions such as this one

**Comment by jayantapandit** [comment]
> It would be against the API terms of service: https://core.telegram.org/api/terms (point 1.4). I think such suggestions belongs to https://bugs.telegram.org, Telegram's platform for platform-wise suggestions such as this one 

I shared a little context. It feels like a mini ghost mode to me.

**Comment by jayantapandit** [comment]
> It would be against the API terms of service: https://core.telegram.org/api/terms (point 1.4). I think such suggestions belongs to https://bugs.telegram.org, Telegram's platform for platform-wise suggestions such as this one 

@RememberTheAir I shared a little context from the Android version. It feels like a mini ghost mode to me. What do you think?

**Comment by RememberTheAir** [comment]
@jayantapandit I wouldn't mind something similar to what the android app lets you do, yes. I don't know how would it look like on desktop though - I mean, I don't know how easy it would be to add such a function in the current codebase and how it would properly fit in a desktop interface. Maybe it's better to open a new issue asking for android/ios-like chat preview (if there isn't already, haven't searched)
