### ISSUE TITLE
[Feature Request] Disable editing last message in groups/channels with UP arrow

### ISSUE THREAD

**Issue by Anton-V-K** [telegramdesktop/tdesktop#10273]
### Is your feature request related to a problem?
The feature to edit own last message in ~~chats~~ groups was implemented with #1779. I've discovered it just recently (on an old PC without mouse), and it was a pain in the neck to scroll the history with touchpad (it had no mouse wheel), since I couldn't do it with UP arrow.

### Describe the solution you'd like
Add an option/setting to disable this behavior, or fix to another shortcut (like Ctrl+UP, which also does the same in 2.5.7 - two shortcuts for the same feature?).
Only one shortcut should be used to edit own last message - let it be Ctrl+UP, which now works for private chats, groups and channels.

**Comment by ilya-fedin** [comment]
> since I couldn't do it with UP arrow.

It scrolls when it goes into edit mode. You can reset it with ESC when you finished scrolling. If you have some text entered, it won't go into edit mode.

**Comment by Anton-V-K** [comment]
@ilya-fedin , thanks for the hint. Such behavior wasn't obvious for me.

Anyway it looks like a workaround, since it requires extra key strokes just to scroll the history.
And if your last message is large, it will occupy quite a lot of screen - you can't hide it.

**Comment by Anton-V-K** [comment]
Instead of closing this request without any changes, I'd prefer to have a kind of solution to make the reaction for UP key consistent in all conversations (private chats, channels, groups, etc.)
Similar issues: #4480, #6292

**Comment by ilya-fedin** [comment]
It's consistent in all conversations (private chats, channels, groups, etc.)

**Comment by Anton-V-K** [comment]
Well, I'd prefer to have more consistency :)
Hitting UP key in ...
1) ... a private group/chat - edits my last message and scrolls up
2) ... a private channel (with read-write access) - edits my last message and scrolls up
3) ... a private channel (where I can't post anything) - just scrolls up

And there are few exceptions:
a) if my message in a private chat is old (posted more than 2 days ago?) - UP key just scrolls up (well, you can't edit old messages)
b) if you've already typed a new message - UP key just scrolls up

Anyway if I wan't to scroll the history, I don't wan't the app to bring my last message for editing, but in many cases I can't avoid this behavior.
And here is how an attempt to scroll the history looks after long message in a small window:
![Telegram-edit-last-message](https://user-images.githubusercontent.com/20116984/127741192-87c037ea-aae9-4f73-9fc3-c3e57b63d1d8.png)
Is it really OK? I don't think so :)

BTW Ctrl+UP now replies to the last message. I wonder why this behavior had been changed, since it was initially planned to edit last message in #1060.

Generally I'd be fine with another shortcut to scroll the history with keyboard - Alt+UP or something like this.

**Comment by ivandeex** [comment]
Please add an advanced setting to disable the "Edit last message with UP" in all contexts.

**Comment by Anton-V-K** [comment]
Alt+UP (Linux/Windows) / Option+UP (Mac) shortcut may be utilized for line-by-line history scrolling, so it may be developed as a new feature.
Re-using UP key for that would be harder in implementation, since a bunch of functionality is already bound to this key.
