### ISSUE TITLE
While typing TG moves my cursor and deletes my text

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#10270]
### Steps to reproduce
1. While writing a comment in a group, this has happened to me at least 4 times in various different groups. I start typing & I type a lot, & the next thing I know, the last sentence or paragraph is gone & my cursor either jumps to the top of the text field or some place above where my last sentence/parag. was.
2. When I go back to retype what I was saying, all is fine.
3. 

### Expected behaviour
I should be able to type.

### Actual behaviour
See above.

### Configuration
Win 7

**Version of Telegram Desktop:**
Latest version

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#4922
