### ISSUE TITLE
[Feature Request] Remove the limit of accounts

### ISSUE THREAD

**Issue by pasvistelik** [telegramdesktop/tdesktop#10272]
### Is your feature request related to a problem?
I see that there is sort of a crutch with `kMaxAccounts = 3` which is made to avoid some RAM usage issues on 32-bit platforms (according to the explanation I found at #9038)
https://github.com/telegramdesktop/tdesktop/blob/b6483cb65cceca59e3230b787e7bfc744532b8a9/Telegram/SourceFiles/main/main_domain.h#L33
As a ubuntu 64-bit user, now I have to compile my own Telegram Desktop version without that limit.

### Describe the solution you'd like
I would like to have no limit of max accounts, at least for 64-bit platforms.

### Describe alternatives you've considered
As an alternative, I would like the Telegram Desktop app to have a customizable limit of accounts amount that could be added (somewhere at the settings, with a caveat), so it would be the responsibility of the app user.

### Additional context
I find it inappropriate that Telegram Desktop limits all the desktop platforms due to a problem with 32-bit platforms. I hope this limitation will be removed in upcoming releases.

**Comment by NotNotMarshall** [comment]
> ### Is your feature request related to a problem?
> I see that there is sort of a crutch with `kMaxAccounts = 3` which is made to avoid some RAM usage issues on 32-bit platforms (according to the explanation I found at #9038)
> https://github.com/telegramdesktop/tdesktop/blob/b6483cb65cceca59e3230b787e7bfc744532b8a9/Telegram/SourceFiles/main/main_domain.h#L33
> 
> 
> As a ubuntu 64-bit user, now I have to compile my own Telegram Desktop version without that limit.
> ### Describe the solution you'd like
> I would like to have no limit of max accounts, at least for 64-bit platforms.
> 
> ### Describe alternatives you've considered
> As an alternative, I would like the Telegram Desktop app to have a customizable limit of accounts amount that could be added (somewhere at the settings, with a caveat), so it would be the responsibility of the app user.
> 
> ### Additional context
> I find it inappropriate that Telegram Desktop limits all the desktop platforms due to a problem with 32-bit platforms. I hope this limitation will be removed in upcoming releases.

As a leader of the world's most notorious tech company which is of course Google, I support this idea too. +1

**Comment by Cyber-Criminal** [comment]
this limits make users to use untrusted mods...

**Comment by ben221199** [comment]
I agree.

**Comment by alirayaneh** [comment]
good Idea .
