### ISSUE TITLE
the Vazir font (License) link not working.

### ISSUE THREAD

**Issue by noahabe** [telegramdesktop/tdesktop#10274]
### Steps to reproduce
1. Click on the License link on the README.md file
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead
It readirects to a page not found

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
new license file.
https://github.com/rastikerdar/vazir-font/blob/master/OFL.txt

**Comment by noahabe** [comment]
but still the link on the README.md file is not working.

**Comment by ilya-fedin** [comment]
> new license file.

This link would be incorrect since tdesktop has old version of Vazir bundled licensed by Apache license.
The correct link would be: https://github.com/rastikerdar/vazir-font/blob/v26.0.2/LICENSE
