### ISSUE TITLE
Does not display the icon to send a voice message if there is no microphone

### ISSUE THREAD

**Issue by Lazek** [telegramdesktop/tdesktop#1027]
![voice_message](https://cloud.githubusercontent.com/assets/10336636/9423444/67c20fac-48cc-11e5-9e09-e5fe7e3ba04f.PNG)

If  operating system does not have a single microphone to record voice messages, then perhaps should not display an icon to send a voice message.

To prevent sending empty messages.

It is necessary to immediately display the - Send - as it was in previous versions.

**Comment by auchri** [comment]
Related to #784
