### ISSUE TITLE
Voice group calls 

### ISSUE THREAD

**Issue by Draghy** [telegramdesktop/tdesktop#10276]
With the new update 2.5.8 I'm having problems with my microphone in the group voice calls, instead with 2.5.1 there weren't problems with my microphone. How can I solve this? 
Is there anyone else experiencing this problem?

Windows 7

**Comment by ilya-fedin** [comment]
Please re-report this properly, without removing the template and with details.

**Comment by insign** [comment]
There are about 800 issues open. Have you ever asked yourself about wasting the time of others by not following guidelines and asking for personal problems with your OS?
