### ISSUE TITLE
Unable to Delete Message for both sides on TDesktop

### ISSUE THREAD

**Issue by SpEcHiDe** [telegramdesktop/tdesktop#10271]
### Steps to reproduce
1.  send a message to a Telegram Bot
2.  try to delete a message

### Expected behaviour
In Telegram X, we are able to delete message for both sides.
![image](https://user-images.githubusercontent.com/6317196/106349929-09289c80-62f8-11eb-814c-3b604ebaf091.png)

ScreenShot from web.telegram.org

![20210212_113946](https://user-images.githubusercontent.com/6317196/107736064-25303300-6d27-11eb-81c6-6c00e991e566.jpg)

also, The Telegram Server sends a deleted_message update to Bots.
![image](https://user-images.githubusercontent.com/6317196/106349991-89e79880-62f8-11eb-9e56-b3b00869bad1.png)

### Actual behaviour
In TDesktop, there is no similar checkbox, and we are not able to delete message for both sides.
![image](https://user-images.githubusercontent.com/6317196/106349942-278e9800-62f8-11eb-9956-4a332bfc9bed.png)

**Comment by SpEcHiDe** [comment]
Not Stale ,😐

**Comment by 23rd** [comment]
#3818.

**Comment by RememberTheAir** [comment]
I believe this is the intended and correct behavior, since the Android app doesn't offer that checkbox either and I guess the iOS app doesn't too

**Comment by john-preston** [comment]
Yes, this is consistent with both official iOS mobile app and official Android mobile app.

**Comment by SpEcHiDe** [comment]
but, it still works if I use any of web.telegram.org/?legacy=1 or t.me/tgx_android 🥺😭

https://github.com/SpEcHiDe/NoPMsBot/commit/c6bf6dfbfa7612d7b130b1eceb38cf5b850b887b#diff-7a3cbf0ad98e9dde6546f88abf48b52102778619093e10ef077ffa81f41b7c81R35


it only does not work on the "official" desktop and android applications.

**Comment by RememberTheAir** [comment]
The web client is deprecated and TGX is an experimental app. The main/leading apps behave like that so that's the intended behavior

**Comment by john-preston** [comment]
@SpEcHiDe And iOS. So, all of the official native applications.
