### ISSUE TITLE
[Discussion] Possibility of changing the interface scale WITHOUT restarting the client

### ISSUE THREAD

**Issue by mooons** [telegramdesktop/tdesktop#10282]
Hi there,

I acknowledge this might be a niche use case, and possibly a limitation of Qt. But I want to ask if it is possible, at all, to dynamically change the interface scale without restarting the desktop client?

Right now when the "Default interface scale" is selected, it seems to follow **main display**'s DPI:

![image](https://user-images.githubusercontent.com/10822203/106397183-e6ae8600-63c0-11eb-99b1-cd8e99b558ae.png)

![image](https://user-images.githubusercontent.com/10822203/106397187-eadaa380-63c0-11eb-9f19-7cfaad283f7c.png)

My use case is, when I have a mix of monitor with different DPIs set, the font size is kept the same when dragged from say, a 150% DPI display to a 100% DPI display. The result of that is a (much) bigger interface than I expected on a 100% DPI display. And right now if I need to switch DPI, I would have to restart the client:

![image](https://user-images.githubusercontent.com/10822203/106397096-9505fb80-63c0-11eb-96ff-9555bc70093a.png)

It would be lovely if Qt Telegram Desktop can behave like Chrome / Sublime Text when dragged across displays with different DPIs.

Cheers.

Ref:
- https://doc.qt.io/qt-5/highdpi.html

**Comment by ilya-fedin** [comment]
It is possible, but requires rewriting of a lot of code
#1121

**Comment by mooons** [comment]
> It is possible, but requires rewriting a lot of code
> #1121

Thanks @ilya-fedin .
