### ISSUE TITLE
After 2.5.8 update image view appears on incorrect display

### ISSUE THREAD

**Issue by Demetri0** [telegramdesktop/tdesktop#10281]
### Steps to reproduce
1. Use at least two monitors
2. Open any chat that have a message with an image 
3. Click by image for view it in a full size

### Expected behaviour
Image full view should appear on the same display with the main telegram window located.

### Actual behaviour
Image full view appears on another display.

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** 2.5.8

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: `ppa:atareao/telegram`

**Used theme**: Night

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5126
