### ISSUE TITLE
Profile Videos not play

### ISSUE THREAD

**Issue by saturn99** [telegramdesktop/tdesktop#10288]
in version 2.5.8 on Linux videos on profile not play and it show only image

```
OS: Linux
Version: 2.5.8
```

**Comment by shubarov** [comment]
`Telegram Desktop, version 2.5.8.`
`OS: Windows 10 Pro (2004)`
there is no sound when watching a video (also audio messages). if the files are downloaded, then everything is fine in the vdieo player. there is also sound in all other applications, only there is no sound in telegram-desktop.

**Comment by saturn99** [comment]
UP

**Comment by Muhammadyusuf96** [comment]
> in version 2.5.8 on Linux videos on profile not play and it show only image
> 
> ```
> OS: Linux
> Version: 2.5.8
> ```

In Windows 8.1 also. 
Telegram ver:2.5.8

**Comment by CaseyK9** [comment]
This issue exists on Windows 10 Pro (20H2) and Ubuntu 20.04.2 (Kubuntu 20.04).
Telegram versions: 2.5.4 through 2.5.8

To reproduce, open Telegram desktop, navigate to a user with a profile video, attempt to play it, and it will only be a static image.

**Comment by saturn99** [comment]
@john-preston

**Comment by john-preston** [comment]
@saturn99 Thanks. I hope it will be fixed in the next version.
