### ISSUE TITLE
[Feature Request] Some new emojis are missing

### ISSUE THREAD

**Issue by matheusfillipe** [telegramdesktop/tdesktop#10285]
This is a serious and Urgent problem! ;)
The polar bear and a few other emojis that came for the mobile version like in the last 2 months 
I mean this emoji:
<img src="https://user-images.githubusercontent.com/24435787/106405680-d7a5f300-6415-11eb-8652-45e306cbb307.png" width="100" height="120"/>

Currently it is displayed as:
![image](https://user-images.githubusercontent.com/24435787/106405942-877b6080-6416-11eb-87b5-2bfe015ba969.png)

I didn't find any PR regarding this so far so I decided to open this issue.

Telegram-desktop: 2.5.8
OS: Arch Linux x86_64, DE: KDE Plasma 5.20.2, CPU: Intel i7-7700HQ (8) @ 3.800GHz, GPU: NVIDIA GeForce GTX 1050 Ti Mobile, GPU: Intel HD Graphics 630, Memory: 15.5 GiB

**Comment by 23rd** [comment]
Looks like a duplicate of #9775.

**Comment by matheusfillipe** [comment]
Oh yes that might be true.
