### ISSUE TITLE
linux playback speed change for video not work (1.5x, 0.5x, 2x)

### ISSUE THREAD

**Issue by bezdna** [telegramdesktop/tdesktop#10289]
### Steps to reproduce
1. open video
2. playback speed change

### Expected behaviour
video playback speed changed

### Actual behaviour
nothing changes

### Configuration
**Operating system:**
ubuntu 18.04.5 LTS
KDE 

**Version of Telegram Desktop:**
2.5.8
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>

Private

431352 KB | [heap]
40096 KB | /home/anton/Загрузки/Telegram/Telegram
788 KB | /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
540 KB | /usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc
440 KB | /usr/share/fonts/truetype/tibetan-machine/TibetanMachineUni.ttf
300 KB | /usr/share/fonts/truetype/dejavu/DejaVuMathTeXGyre.ttf
236 KB | /usr/share/fonts/truetype/freefont/FreeSansBold.ttf
236 KB | /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
164 KB | /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0
160 KB | /usr/share/fonts/truetype/noto/NotoSansEgyptianHieroglyphs-Regular.ttf
148 KB | /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.4000.14
136 KB | /usr/share/fonts/truetype/noto/NotoSansMongolian-Regular.ttf
116 KB | /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
116 KB | /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
108 KB | /usr/lib/x86_64-linux-gnu/libGL.so.1.0.0
96 KB | [stack]
80 KB | /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
72 KB | /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2200.30
64 KB | /usr/share/fonts/truetype/freefont/FreeSerifBold.ttf
56 KB | /usr/lib/x86_64-linux-gnu/libepoxy.so.0.0.0
48 KB | /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
48 KB | /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so
44 KB | /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so
40 KB | /usr/share/fonts/truetype/noto/NotoSansJavanese-Regular.ttf
40 KB | /usr/lib/x86_64-linux-gnu/libgdk-3.so.0.2200.30
36 KB | /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0
32 KB | /usr/lib/x86_64-linux-gnu/libfreetype.so.6.15.0
32 KB | /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.5600.4
28 KB | /lib/x86_64-linux-gnu/libgcrypt.so.20.2.1
28 KB | /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
24 KB | /lib/x86_64-linux-gnu/libc-2.27.so
20 KB | /usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
20 KB | /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0
20 KB | /lib/x86_64-linux-gnu/libblkid.so.1.1.0
16 KB | /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.28
16 KB | /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0
16 KB | /usr/lib/x86_64-linux-gnu/libatspi.so.0.0.1
16 KB | /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.22810.1
16 KB | /lib/x86_64-linux-gnu/libsystemd.so.0.21.0
16 KB | /usr/lib/x86_64-linux-gnu/libEGL.so.1.0.0
16 KB | /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.10.1
12 KB | /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
12 KB | /usr/lib/x86_64-linux-gnu/libpulse.so.0.20.2
12 KB | /usr/lib/x86_64-linux-gnu/libgraphite2.so.3.0.1
12 KB | /usr/lib/x86_64-linux-gnu/libwayland-client.so.0.3.0
12 KB | /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0.0.0
12 KB | /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
12 KB | /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0.0.0
12 KB | /usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2.11510.0
12 KB | /lib/x86_64-linux-gnu/libexpat.so.1.6.7
12 KB | /lib/x86_64-linux-gnu/libmount.so.1.1.0
12 KB | /lib/x86_64-linux-gnu/libm-2.27.so
8 KB | /lib/x86_64-linux-gnu/libnss_files-2.27.so
8 KB | /lib/x86_64-linux-gnu/libnss_nis-2.27.so
8 KB | /lib/x86_64-linux-gnu/libnss_compat-2.27.so
8 KB | /usr/lib/x86_64-linux-gnu/libpciaccess.so.0.11.1
8 KB | /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
8 KB | /usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libzstd.so.1.3.3
8 KB | /usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
8 KB | /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
8 KB | /usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
8 KB | /lib/x86_64-linux-gnu/libnsl-2.27.so
8 KB | /lib/x86_64-linux-gnu/libapparmor.so.1.4.2
8 KB | /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
8 KB | /lib/x86_64-linux-gnu/libwrap.so.0.7.6
8 KB | /usr/lib/x86_64-linux-gnu/libdatrie.so.1.3.3
8 KB | /usr/lib/x86_64-linux-gnu/libthai.so.0.3.0
8 KB | /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0.10702.0
8 KB | /usr/lib/x86_64-linux-gnu/libxcb-render.so.0.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
8 KB | /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
8 KB | /usr/lib/x86_64-linux-gnu/libXcomposite.so.1.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
8 KB | /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0.4000.14
8 KB | /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3611.0
8 KB | /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
8 KB | /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.4000.14
8 KB | /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
8 KB | /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
8 KB | /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
8 KB | /lib/x86_64-linux-gnu/libgpg-error.so.0.22.0
8 KB | /usr/lib/x86_64-linux-gnu/liblz4.so.1.7.1
8 KB | /lib/x86_64-linux-gnu/liblzma.so.5.2.2
8 KB | /lib/x86_64-linux-gnu/libdbus-1.so.3.19.4
8 KB | /lib/x86_64-linux-gnu/libuuid.so.1.3.0
8 KB | /lib/x86_64-linux-gnu/libbsd.so.0.8.7
8 KB | /lib/x86_64-linux-gnu/librt-2.27.so
8 KB | /lib/x86_64-linux-gnu/libpcre.so.3.13.3
8 KB | /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libGLX.so.0.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libpng16.so.16.34.0
8 KB | /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
8 KB | /lib/x86_64-linux-gnu/libresolv-2.27.so
8 KB | /lib/x86_64-linux-gnu/libselinux.so.1
8 KB | /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.5600.4
8 KB | /lib/x86_64-linux-gnu/libgcc_s.so.1
8 KB | /lib/x86_64-linux-gnu/libdl-2.27.so
8 KB | /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4
8 KB | /lib/x86_64-linux-gnu/libpthread-2.27.so
8 KB | /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
8 KB | /lib/x86_64-linux-gnu/libz.so.1.2.11
8 KB | /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4
8 KB | /usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
8 KB | /lib/x86_64-linux-gnu/ld-2.27.so

Shared

11148 KB | /memfd:xorg (deleted)
1548 KB | /lib/x86_64-linux-gnu/libc-2.27.so
1168 KB | /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.5600.4
1052 KB | /lib/x86_64-linux-gnu/libm-2.27.so
720 KB | /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4
664 KB | /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
568 KB | /usr/lib/x86_64-linux-gnu/libfreetype.so.6.15.0
556 KB | /usr/lib/x86_64-linux-gnu/libgdk-3.so.0.2200.30
404 KB | /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so
304 KB | /var/cache/fontconfig/0bd3dc0958fa2205aaaa8ebb13e2872b-le64.cache-7
272 KB | /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4
252 KB | /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
236 KB | /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
236 KB | /lib/x86_64-linux-gnu/libdbus-1.so.3.19.4
232 KB | /usr/lib/x86_64-linux-gnu/libpulse.so.0.20.2
228 KB | /usr/share/fonts/truetype/lato/Lato-Bold.ttf
212 KB | /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.10.1
184 KB | /usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc
172 KB | /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so
160 KB | /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
160 KB | /lib/x86_64-linux-gnu/ld-2.27.so
136 KB | /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
132 KB | /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0
132 KB | /var/cache/fontconfig/467c019e582ee353435ea5c21d137ef6-le64.cache-7
128 KB | /usr/lib/x86_64-linux-gnu/libGL.so.1.0.0
128 KB | /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2200.30
124 KB | /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0
124 KB | /usr/lib/locale/locale-archive
112 KB | /lib/x86_64-linux-gnu/libz.so.1.2.11
108 KB | /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0.0.0
104 KB | /lib/x86_64-linux-gnu/libpthread-2.27.so
88 KB | /var/cache/fontconfig/cabbd14511b9e8a55e92af97fb3a0461-le64.cache-7
84 KB | /var/cache/fontconfig/04aabc0a78ac019cf9454389977116d2-le64.cache-7
76 KB | /var/cache/fontconfig/d52a8644073d54c13679302ca1180695-le64.cache-7
64 KB | /usr/lib/x86_64-linux-gnu/libatspi.so.0.0.1
64 KB | /lib/x86_64-linux-gnu/libgcc_s.so.1
64 KB | /usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
60 KB | /usr/share/mime/mime.cache
60 KB | /var/cache/fontconfig/9b89f8e3dae116d678bbf48e5f21f69b-le64.cache-7
56 KB | /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
56 KB | /usr/lib/x86_64-linux-gnu/libEGL.so.1.0.0
56 KB | /usr/lib/x86_64-linux-gnu/libGLX.so.0.0.0
52 KB | /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.4000.14
48 KB | /var/cache/fontconfig/d589a48862398ed80a3d6066f4f56f4c-le64.cache-7
44 KB | /var/cache/fontconfig/945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-7
36 KB | /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
32 KB | /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
32 KB | /var/cache/fontconfig/bf3b770c553c462765856025a94f1ce6-le64.cache-7
28 KB | /var/cache/fontconfig/e13b20fdb08344e0e664864cc2ede53d-le64.cache-7
24 KB | /var/cache/fontconfig/3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-7
24 KB | /var/cache/fontconfig/b47c4e1ecd0709278f4910c18777a504-le64.cache-7
20 KB | /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
20 KB | /var/cache/fontconfig/2300eef321c393bfd76478a5c0e95b23-le64.cache-7
20 KB | /var/cache/fontconfig/bbd3eebb6912613e2596f2fd46535a95-le64.cache-7
20 KB | /var/cache/fontconfig/def309198bfa603429122923fa2bb2d4-le64.cache-7
20 KB | /var/cache/fontconfig/9d2451b1fd30e5bffe8383fd27c35478-le64.cache-7
16 KB | /var/cache/fontconfig/de156ccd2eddbdc19d37a45b8b2aac9c-le64.cache-7
16 KB | /var/cache/fontconfig/c57959a16110560c8d0fcea73374aeeb-le64.cache-7
12 KB | /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
12 KB | /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
12 KB | /lib/x86_64-linux-gnu/libdl-2.27.so
12 KB | /var/cache/fontconfig/f259c2cffa685e28062317905db73c4a-le64.cache-7
12 KB | /var/cache/fontconfig/674d1711f2d1d2a09646eb0bdcadee49-le64.cache-7
8 KB | /usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
8 KB | /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
8 KB | /var/cache/fontconfig/14a5e22175779b556eaa434240950366-le64.cache-7
8 KB | /var/cache/fontconfig/4f3e3037c9980c83b53a9351efadef62-le64.cache-7
8 KB | /var/cache/fontconfig/767a8244fc0220cfb567a839d0392e0b-le64.cache-7
8 KB | /var/cache/fontconfig/69fb4bbe1b2fa860e172a32ebf28505c-le64.cache-7
8 KB | /var/cache/fontconfig/a0107c79d978dfcc5e42cb1335b71036-le64.cache-7
8 KB | /var/cache/fontconfig/550f3886151c940c12a5ed35f6a00586-le64.cache-7
8 KB | /var/cache/fontconfig/6afa1bb216ce958c1589e297e8008489-le64.cache-7
4 KB | /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0
4 KB | /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
4 KB | /home/anton/.local/share/mime/mime.cache
4 KB | /usr/share/locale-langpack/en_GB/LC_MESSAGES/pulseaudio.mo
4 KB | /var/cache/fontconfig/087e1975ba9a574b140bb1df193bf770-le64.cache-7
4 KB | /var/cache/fontconfig/0d8c3b2ac0904cb8a57a757ad11a4a08-le64.cache-7
4 KB | /var/cache/fontconfig/1ac9eb803944fde146138c791f5cc56a-le64.cache-7
4 KB | /var/cache/fontconfig/dc05db6664285cc2f12bf69c139ae4c3-le64.cache-7
4 KB | /var/cache/fontconfig/660208299946a285a940457d1287da33-le64.cache-7
4 KB | /var/cache/fontconfig/4794a0821666d79190d59a36cb4f44b5-le64.cache-7
4 KB | /var/cache/fontconfig/b872e6e592da6075ffa4ab0a1fcc0c75-le64.cache-7
4 KB | /var/cache/fontconfig/f6d4eedfaab2589bde49f7a3ff831d22-le64.cache-7
4 KB | /var/cache/fontconfig/589f83ef4c36d296ce6e1c846f468f08-le64.cache-7
4 KB | /var/cache/fontconfig/bab58bb527bb656aaa9f116d68a48d89-le64.cache-7
4 KB | /var/cache/fontconfig/2171a34dccabdb6bcbbc728186263178-le64.cache-7
4 KB | /var/cache/fontconfig/c5c45a61289222e0d30b1a26ef4effbe-le64.cache-7
4 KB | /var/cache/fontconfig/aec30016f93e1b46d1a973dce0d74068-le64.cache-7
4 KB | /var/cache/fontconfig/3f589640d34b7dc9042c8d453f7c8b9c-le64.cache-7
4 KB | /var/cache/fontconfig/16c2fda60d1b4b719f4b3d06fd951d25-le64.cache-7
4 KB | /var/cache/fontconfig/a48eab177a16e4f3713381162db2f3e9-le64.cache-7
4 KB | /var/cache/fontconfig/564b2e68ac9bc4e36a6f7f6d6125ec1c-le64.cache-7
4 KB | /var/cache/fontconfig/56cf4f4769d0f4abc89a4895d7bd3ae1-le64.cache-7
4 KB | /var/cache/fontconfig/b9d506c9ac06c20b433354fa67a72993-le64.cache-7
4 KB | /var/cache/fontconfig/370e5b74bf5dafc30834de68e24a87a4-le64.cache-7
4 KB | /var/cache/fontconfig/6b2c5944714ca7831b25bed9e85cb5c8-le64.cache-7
4 KB | /var/cache/fontconfig/d5178ab6d91b49bf20a416737dcea9e8-le64.cache-7
4 KB | /var/cache/fontconfig/551ecf3b0e8b0bca0f25c0944f561853-le64.cache-7
4 KB | /var/cache/fontconfig/8a687c406b77f27d99abfeeba937fcce-le64.cache-7
4 KB | /var/cache/fontconfig/3f7329c5293ffd510edef78f73874cfd-le64.cache-7
4 KB | /var/cache/fontconfig/0c9eb80ebd1c36541ebe2852d3bb0c49-le64.cache-7
4 KB | /var/cache/fontconfig/22368d551a680bfe5a62c02760edf4ea-le64.cache-7
4 KB | /var/cache/fontconfig/4d9c95eba1cb85bbcf2878543262124a-le64.cache-7
4 KB | /var/cache/fontconfig/85e0a52ce643a7ba2ae53e5d6949cead-le64.cache-7
4 KB | /var/cache/fontconfig/49f0de54bdd920fe4f0dfd4cbac43e6b-le64.cache-7
4 KB | /var/cache/fontconfig/f6e6e0a5c3d2f6ae0c0c2e0ecd42a997-le64.cache-7
4 KB | /var/cache/fontconfig/4b2eda6bb976bda485cb2176619421d5-le64.cache-7
4 KB | /var/cache/fontconfig/c277e94e32b20404286a1ddafa5a80f0-le64.cache-7
4 KB | /var/cache/fontconfig/a6912409548b9a06a240b05cb2414bc9-le64.cache-7
4 KB | /var/cache/fontconfig/e0aa53bcfa504e64f87823c16bc01eb6-le64.cache-7
4 KB | /usr/share/locale-langpack/en_GB/LC_MESSAGES/libc.mo
4 KB | [vdso]

</details>

**Comment by ilya-fedin** [comment]
I checked and it works. Probably steps to reproduce are wrong/

**Comment by Tuxino88** [comment]
> I checked and it works. Probably steps to reproduce are wrong.

question: are VAAPIs supported?

**Comment by ilya-fedin** [comment]
> question: are VAAPIs supported?

No

**Comment by Tuxino88** [comment]
> No

are they planned in the future?

**Comment by ilya-fedin** [comment]
> are they planned in the future?

AFAIK, no. Too much work that requires knowledge how to work with GPU memory.

**Comment by bezdna** [comment]
file:///home/anton/Ð’Ð¸Ð´ÐµÐ¾/Peek 2021-02-01 16-32.gif

**Comment by bezdna** [comment]
![2](https://user-images.githubusercontent.com/518939/106473026-f787f600-64ab-11eb-9aea-1aa58e73b1f9.gif)

**Comment by ilya-fedin** [comment]
The missing step to reproduce is "compositing must be disabled". You forgot to specify it.

**Comment by bezdna** [comment]
Works now, thanks

**Comment by Aokromes** [comment]
so, i can close this?
