### ISSUE TITLE
How to create a issue ?[Question] 

### ISSUE THREAD

**Issue by Aadityapburujwale** [telegramdesktop/tdesktop#10286]
I want to create a issue for android version, but there is no option to create a new issue. there is only pull request option.

**Comment by Aokromes** [comment]
you cannot, android have disabled it, you need to use in app, ask a question or if you can use bugs.telegram.org

**Comment by Aadityapburujwale** [comment]
@Aokromes I want to request a feature.

**Comment by Aokromes** [comment]
those 2 are the only places you can use.
