### ISSUE TITLE
Telegram is unresponsive after upgrade to Mac OS X Big Sur + DisplayLink External Monitor

### ISSUE THREAD

**Issue by benjaminprojas** [telegramdesktop/tdesktop#10298]
### Steps to reproduce
1. After the upgrade to Mac OS X Big Sur and using an external Monitor powered by DisplayLink, the Telegram application does not work. https://www.displaylink.com/downloads/macos 
2. It does however work on the native monitors that are not extended via DisplayLink.
3. No other application breaks in this way, only Telegram.

![image](https://user-images.githubusercontent.com/962530/106604048-18446000-652d-11eb-9780-086fa5cae89e.png)

### Expected behaviour
The application should work exactly the same on all monitors.

### Actual behaviour
The telegram application is distorted and unresponsive. It's basically like dragging a screenshot around, but only on this external display.

### Configuration
**Operating system:**
Mac OS X Big Sur

**Version of Telegram Desktop:**
2.5.8

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
> 3. No other application breaks in this way, only Telegram.

Have you checked other Qt applications, like qBittorrent?

**Comment by benjaminprojas** [comment]
> Have you checked other Qt applications, like qBittorrent?

I just tested qBittorrent and it works just fine, no issues.

**Comment by benjaminprojas** [comment]
Any additional thoughts here? This is still happening 4 months later.

**Comment by benjaminprojas** [comment]
Still an issue I deal with daily.
