### ISSUE TITLE
overflow problem in telegram desktop and mobile

### ISSUE THREAD

**Issue by ehsan2003** [telegramdesktop/tdesktop#10295]
### Steps to reproduce
1.  small changes for chat messages view

### Expected behaviour
Tell us what should happen
telegram should wrap words or at least prevent overflowing from the message box
### Actual behaviour
Tell us what happens instead
the text overflows out of the message box for this content : 
```
݆݅           
























۶هه۷۵۵۷۸۸۶۵هه











هههههههههههه







۶ههههههه
هههههههههه
           * ҈҈҈҉҉҉҉҈҈҈҈҈҉҉҉҉҈҈҈҉҉҉҈҈҈҉҉҉҈҈҈҈҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҈҈҈҈҈҈҈̫̫҉҉҉҉҈҈֟֟*
݆݅* ҈҈҈҉҉҉҉҈҈҈҈҈҉҉҉҉҈҈҈҉҉҉҈҈҈҉҉҉҈҈҈҈҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҈҈҈҈҈҈
݆݅* ҈҈҈҉҉҉҉҈҈҈҈҈҉҉҉҉҈҈҈҉҉҉҈҈҈҉҉҉҈҈҈҈҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҉҈҈҈҈҈҈ههههههه
݆݅
```
![image](https://user-images.githubusercontent.com/51885828/106513308-0d1b1100-64e8-11eb-9fcb-95f1e1c15304.png)

### Configuration
**Operating system:**
this problem appears for both telegram desktop and mobile

**Comment by RememberTheAir** [comment]
> ### Configuration
> 
> Operating system:
> this problem appears for both telegram desktop and mobile

You're reporting an issue on Telegram Desktop's issues tracker, so you should provide the details of your installation. Ideally you should provide both, instead of not providing any

**Comment by ilya-fedin** [comment]
> You're reporting an issue on Telegram Desktop's issues tracker, so you should provide the details of your installation.

I'm 100% sure there are multiple duplicates of this issue, but I can't find them

**Comment by ilya-fedin** [comment]
#8488 #8229 #6416
