### ISSUE TITLE
Can't send PDFs with multiple pages without compression via Telegram Desktop

### ISSUE THREAD

**Issue by fjorgemota** [telegramdesktop/tdesktop#10294]
### Steps to reproduce
1. Click on the upload button on a chat;
2. Select a PDF file with multiples pages (here's a [PDF file with two pages](https://github.com/telegramdesktop/tdesktop/files/5906058/sample.pdf), as an example);
3. Observe that there's no way to send it without compression (as a file), so it's sent as a image of the first page instead, like in the screenshot below:

![screenshot of the error](https://user-images.githubusercontent.com/529864/106505416-0c15bf80-64a7-11eb-81d2-58f6f8d707a3.png)

### Expected behaviour
The option to NOT compress (and therefore convert to a image of the first page) should exists, and with that option disabled the PDF should be managed as a file instead of a image.

### Actual behaviour
Only a image of the first page of the PDF is rendered and uploaded.

### Configuration
**Operating system:** Antergos Linux (a distro based on Arch Linux)

**Version of Telegram Desktop:** 2.5.8

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: [`telegram-desktop` package on the community repository of the Arch Linux distro](https://archlinux.org/packages/community/x86_64/telegram-desktop/)

**Used theme**: Default Tinted theme, with "Adaptive layout for wide screens" disabled and "Night mode" enabled.

<details><summary><b>Output of the program/Logs</b>:</summary>
(process:105308): Telegram-WARNING **: 16:02:44.002: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 16:02:44.004: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 16:02:44.004: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).

(process:105308): Telegram-WARNING **: 16:02:44.004: Application was built without embedded fonts, this may lead to font issues.
[ALSOFT] (EE) Failed to set real-time priority for thread: Operação não permitida (1)
error: : cannot open
error: : cannot open
error: : cannot open
</details>

**Additional details**: When downloading the static build available on the README, the error doesn't seem to happen, as the PDF is recognized as a file instead of a image:

![image](https://user-images.githubusercontent.com/529864/106505688-67e04880-64a7-11eb-96e1-683d95d19929.png)

Now I'm not really sure if it's an issue on the building process of the package for Arch Linux....

**Comment by ilya-fedin** [comment]
This is influence of qt5-webengine

**Comment by fjorgemota** [comment]
So...basically the solution is to use the static build, right?

**Comment by ilya-fedin** [comment]
Yeah

**Comment by john-preston** [comment]
@ilya-fedin Actually, PDFs should always be sent as files, not as photos, even if they can be read. I’ll look if something broke that.
