### ISSUE TITLE
Tray icon is tiny again on ubuntu

### ISSUE THREAD

**Issue by trevarj** [telegramdesktop/tdesktop#10293]
### Steps to reproduce
1. Open TG desktop with app icons enabled 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Ubuntu 20.10 / Gnome 
**Version of Telegram Desktop:**
2.5.8
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Github
**Used theme**:

![image](https://user-images.githubusercontent.com/5448324/106495144-5b221b80-64cc-11eb-9677-afbfebc6e6bb.png)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Looks like a bug in your tray applet

**Comment by trevarj** [comment]
> Looks like a bug in your tray applet

Yep! Sorry
