### ISSUE TITLE
wrong window for media view

### ISSUE THREAD

**Issue by MrBam** [telegramdesktop/tdesktop#10296]
with 2 monitor setup, view screen open on last left monitor.
### Steps to reproduce
1. open app
2. open chat
3. open media (gif/photo/video)

### Expected behaviour
view screen opens on desktop with app on it  

### Actual behaviour
view screen opens on last left desktop

### Configuration
**Operating system:**
Linux  5.4.0-62-generic #70~18.04.1-Ubuntu SMP Tue Jan 12 17:18:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
**Version of Telegram Desktop:**
2.5.8
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
the official website, than apps updates
**Used theme**:
nigth mode, but no differences 
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5126
