### ISSUE TITLE
[Feature Request] Secure storage of media files.

### ISSUE THREAD

**Issue by koval01** [telegramdesktop/tdesktop#10291]
### Is your feature request related to a problem?
File system privacy issue.

### Describe the solution you'd like
I want you to add a cache mode to Telegram for PC. That is, if I received a photo or video as a file (not compressed), it will be saved on my PC in encrypted form. So that it can be viewed only through the Telegram client itself.

### Describe alternatives you've considered
After each session, delete the Telegram Desktop folder from the Downloads directory (Windows)

### Additional context
This feature should be optional, ie leave the normal mode of saving media files as desired.

**Comment by ilya-fedin** [comment]
#6806
