### ISSUE TITLE
Deleted messages are not shown like on other platforms

### ISSUE THREAD

**Issue by jlubeck** [telegramdesktop/tdesktop#10292]
On mobile you can see someone replied to a deleted message.

![photo_2021-01-25_mobile](https://user-images.githubusercontent.com/3067603/105733126-2d9f0600-5eff-11eb-8fbc-41f758ab8b33.jpeg)

On desktop you can't, which takes conversations completely out of context. 
![photo_2021-01-25_desktop](https://user-images.githubusercontent.com/3067603/105733136-2f68c980-5eff-11eb-9220-2a5f36fbae13.jpg)

On desktop it looks like the person is saying the blog post looks like a scam website, when he was actually replying to another message which got deleted.

**Comment by ilya-fedin** [comment]
But both screenshots are from desktop

**Comment by Mehrshad3** [comment]
> On desktop you can't

I can; I don't know why you can't.

**Comment by Mehrshad3** [comment]
Also, this issue doesn't have the template.
