### ISSUE TITLE
Add emoji scaling option

### ISSUE THREAD

**Issue by disharmonized** [telegramdesktop/tdesktop#1030]
Please, add support for scaling emoji smiles in messages. I am using telegram desktop on Windows and obvious size difference of stickers and smiles are make me sad =(. Smiles are too small.

**Comment by auchri** [comment]
Emojis are as big as the text, this is also the case in the android app and that's not an issue

**Comment by auchri** [comment]
Here is a sticker pack with emojis: https://telegram.me/addstickers/sticker_emoji_by_naeim
