### ISSUE TITLE
Sending emoji or sticker will not showing read color(blue) instead it shows (white) after the messages read by recipient

### ISSUE THREAD

**Issue by nandakumardtc** [telegramdesktop/tdesktop#10307]
### Steps to reproduce
1. Send any emoji or sticker

### Expected behaviour
It  should show check mark with blue color after the messages was read by recipient

### Actual behaviour
It shows white colored check mark instead of blue color after the messages was read by recipient

### Configuration
**Operating system:**
windows 10 pro build 20H2

**Version of Telegram Desktop:**
Version 2.5.8

**Used theme**:
Tinted
![image](https://user-images.githubusercontent.com/40513758/106847792-a6f3e100-66d5-11eb-8aa6-2a00c0f9bd53.png)

screen shot is taken after the message was read by recipitent

**Comment by john-preston** [comment]
@nandakumardtc There is now color indication of read status in Telegram. One check mark means the message is sent, two check marks mean it was read.

**Comment by nandakumardtc** [comment]
but for text messages it shows one check is for sent after delivered same to recipient it shows double check with white color. when the recipient reads will change to double check with blue color

**Comment by RememberTheAir** [comment]
> After message delivered the same changed to double check with white color. when the recipient reads will change to double check with blue color

Nope, it doesn't work like that. Color is _not_ relevant and doesn't give any information about the message delivery status. On Telegram there are only two possible states:

- one checkmark: delivered to the server (your phone/PC -> Telegram server. The server will deliver the message to every Telegram app the recipient is using)
- two checkmarks: read by the recipient

On Telegram, there is no "delivered to recipient phone" status (which is WhatsApp's grey double checkmark). You can read more about it in the FAQ: https://telegram.org/faq#q-what-do-the-check-marks-mean

**Comment by nandakumardtc** [comment]
@RememberTheAir Thanking for you clarification and sorry for the misunderstanding
