### ISSUE TITLE
Hide the messages of certain users in a group chat

### ISSUE THREAD

**Issue by aminya** [telegramdesktop/tdesktop#10316]
### Is your feature request related to a problem?

Is it possible to add a feature to hide the messages from certain users in a group chat? 

Some users might prefer to hide the messages of certain users, so they can have a cleaner conversation.

### Describe the solution you'd like
Adding an option in the groups, which allows hiding the messages of certain users. 

The option should be personal and independent of the admin settings for that group. It should be a filter that is applied only by that person and other members should not notice this.

### Describe alternatives you've considered
N/A

**Comment by Aokromes** [comment]
this belongs to https://bugs.telegram.org

**Comment by aminya** [comment]
Created here: https://bugs.telegram.org/c/1787
