### ISSUE TITLE
Share text via link

### ISSUE THREAD

**Issue by auchri** [telegramdesktop/tdesktop#1031]
It would be great if Telegram Desktop also supports the scheme to share text:

tg://msg?text=...&url=...

It's already implemented in the android app: https://github.com/DrKLO/Telegram/issues/1215#issuecomment-130844379

**Comment by Clevero** [comment]
+1

Can please someone implement this feature? It would help me for a chrome extension for my bot :/

**Comment by amastaneh** [comment]
+1

**Comment by stek29** [comment]
Could you please explain it?)
Link to android issue is broken...

**Comment by auchri** [comment]
See http://telegram.wiki/tips:urischeme :)

**Comment by stek29** [comment]
@auchri btw, the link is broken. It's on http://telegram.wiki/tips:urischeme or on [wayback machine](http://web.archive.org/web/20151207114641/http://telegram.wiki/tips:urischeme)

**Comment by auchri** [comment]
@stek29 Thanks, I've updated the link.

**Comment by stek29** [comment]
And the page on wiki itself is outdated -- `share` isn't there while it is actively used, and `msg`/`resolve` are, while they're not used anymore afaik.

**Comment by Aokromes** [comment]
this is implemented already no?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
