### ISSUE TITLE
"Deleted message" in reply is not disappearing

### ISSUE THREAD

**Issue by makisukurisu** [telegramdesktop/tdesktop#10315]
### Steps to reproduce
1. Send message to any chat
2. Reply to it
3. Delete message sent on step 1

### Expected behavior
"Deleted message" in reply will disappear as it does on Mobile and Web (+ bunch of other clients) 
![image](https://user-images.githubusercontent.com/49622129/107074945-1eb72e00-67f2-11eb-84c3-36fe1c5f5e5b.png)
![image](https://user-images.githubusercontent.com/49622129/107074954-224ab500-67f2-11eb-9ed0-7dd29887c42a.png)

Screenshots from Telegram Mobile on Android.

### Actual behavior
"Deleted message" stays there for ever (or at least 9 days+)

![image](https://user-images.githubusercontent.com/49622129/107075005-32fb2b00-67f2-11eb-9141-7085b5c38430.png)
![image](https://user-images.githubusercontent.com/49622129/107075015-368eb200-67f2-11eb-8250-e20c9a96d0f0.png)

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 2.5.8 (install beta checked, no updates available)

**Used theme**: Does not affect the issue

P.S. Reentering chat, clicking on reply, reopening the app won't help. Same thing happens in both - group chats and personal chats (including saved messages) 
P.P.S. I don't think it's other platforms problem since Telegram regularly says on "deleting messages with no trace", and reply mark is clearly a trace of deleting messages.

**Comment by makisukurisu** [comment]
Just to make it clear. Although #10292 may look similar by name - it isn't by content of issue.

**Comment by Mehrshad3** [comment]
In my opinion, excepted behavior is that "Deleted message" stays there forever. because it's good that the user can see the message is replied to a deleted message and not be confused.

**Comment by makisukurisu** [comment]
Sorry for not closing this issue. Guess that's something to do for mobile devs.

I'm satisfied with reply from Mehrshad3.
