### ISSUE TITLE
JSON export missing fields

### ISSUE THREAD

**Issue by arladmin** [telegramdesktop/tdesktop#10312]
### Steps to reproduce
1. Import a chat from another platform, like Whatsapp, into a Telegram Chat.
2. In Telegram, export the new Chat's chat history, in JSON format.

### Expected behaviour
1. The JSON format should contain all the relevant fields for each message, including the Original Timestamp (which can already be seen in the Telegram chat app).

### Actual behaviour
1. The objects in the JSON file do not contain any field for Original Timestamp.
2. Only 'date' field is included, which just contains the timestamp from the time of import.

### Configuration
**Operating system:** Win 10

**Version of Telegram Desktop:** 2.5.8

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@arladmin Yeah, they should be added.

**Comment by arladmin** [comment]
> @arladmin Yeah, they should be added.

Hi @john-preston , is there an ETA you could share with me, for this fix to get implemented?

Thanks.

**Comment by arladmin** [comment]
Hi @john-preston, any update on this?

Thanks
