### ISSUE TITLE
Telegram Desktop has no sound on a Raspberry Pi 4 with kernel 5.10.13

### ISSUE THREAD

**Issue by the-real-cyberpatrol** [telegramdesktop/tdesktop#10319]
### Steps to reproduce
1. Start Telegram Desktop on a Raspberry Pi 4 with Arch Linux ARM with kernel 5.10.13 (package core/linux-raspberrypi4)
2. Open a group or channel with a video, a video message or a voice message
3. Play the message

### Expected behaviour
The message should be played with sound.

### Actual behaviour
The message is played without sound.

### Configuration
**Operating system:**
Arch Linux ARM (armv7h) with Xfce on a Raspberry Pi 4.

**Version of Telegram Desktop:**
2.5.1 and 2.5.8

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Distribution package: community/telegram-desktop 2.5.8-1

**Used theme**:
Classic

<details>
With kernel 5.10.13 Telegram Desktop plays any videos, video messages and voice messages without sound.
With kernel 5.4.83 everything is played correctly with sound.
So downgrading the kernel is a workaround.

I don't know if it's a bug in the kernel or if something in the kernel has changed so that Telegram Desktop needs to be adapted to the new kernel.

Doesn't happen on a x64 system with Artix Linux.
Any other sound related software like media players is not affected.
</details>

**Comment by Aokromes** [comment]
3rd party bug.
