### ISSUE TITLE
The GIF don't play while opening

### ISSUE THREAD

**Issue by sepehr-brj** [telegramdesktop/tdesktop#10317]
### Steps to reproduce
1. Right click on a GIF (Don't play the GIF)
2. Open GIF
3. 

### Expected behaviour
Playing GIF

### Actual behaviour
The GIF is not playing

### Configuration
**Operating system:** Windows 7 x86

**Version of Telegram Desktop:** 2.5.8

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Tined

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Mehrshad3** [comment]
> 2\. Open GIF

How can I do this? where is the button?

**Comment by sepehr-brj** [comment]
> How can I do this? where is the button?

![image](https://user-images.githubusercontent.com/55192376/107115121-a1d29580-687f-11eb-881a-f09dcd4921ce.png)

**Comment by Mehrshad3** [comment]
I don't have this option.

**Comment by sepehr-brj** [comment]
If GIFs autoplay is on, just click on GIF to open it.
This bug doesn't exist when GIFs autoplay is on.
