### ISSUE TITLE
Telegram and its hunger for attention

### ISSUE THREAD

**Issue by renatofrota** [telegramdesktop/tdesktop#10310]
### Steps to reproduce
1. Install Telegram and start a chat with a friend
2. Go do something else while waits for an answer like any not obsessed person
3. Receive a message and get extremely annoyed by Telegram stealing window focus

### Expected behavior
Telegram should NOTIFY ME there's a new message - that's what the **notifications** are supposed to do.

### Actual behavior
Telegram steal focus although I've never asked him to do so.

### Configuration
**Operating system:**
Linux Mint Cinnamon

**Version of Telegram Desktop:**
2.5.8

**Installation source:**
Official website

**Used theme:**
Not relevant

Yeah, that option "at notification settings iirc" actually exists, I know. However, a lot of people agree with me it makes absolutely no sense this option is **enabled by default**. No application should STEAL FOCUS (omg!) unless I have explicitly **ASKED** IT TO DO SO.

#7885
#7887
#7900
#7922
#7964
#8006
#8268
#8346
#8372
#enough?

This feature is not even adequate to be placed within **notifications** settings. It should be a configurable option at settings > advanced > **system integrations**, which I could turn on manually, in case I am 101% sure (a.k.a. masoquist).

Please, you, who closed all the related issues above, let me know:

- do you have this awesome feature turned on?
- if so, would it hurt you if the option come disabled by default and you have to turn it on instead all of us having to disable this shit?

Thanks for the awesome product and service. Sorry if it seems rude but I am really pissed off I have to disable this thing everytime I install Telegram. Also, a lot of people I recommend Telegram tell me they hate it because the app "monopolize the computer like I had nothing else to do in my life but to read the incoming messages as if they were all nuclear bomb alerts". So, this is HORRIBLE MARKETING.

**Comment by ilya-fedin** [comment]
This option should flash taskbar item. If its steals focus it is a bug in your DE.
