### ISSUE TITLE
[Question] Emacs key bindings.

### ISSUE THREAD

**Issue by badianeka** [telegramdesktop/tdesktop#10318]
I would like to be able to use my Emacs key binding in order to more efficiently type messages.  Everything else on my desktop where they are available honors them and I would like that to also be available in Telegram.  It's really tedious to have to use my left and right arrow and use some time consuming manual steps in order to accomplish certain things.  Ctrl-e works and so does ctrl-d but not alt-b, alt-f, alt-d, ctrl-a.  

Is it something I have to configure? 

I would appreciate some help in this matter if possible.

**Comment by Aokromes** [comment]
you will need to use some 3rd party app to customize key bindings, you don't state what os you use, but if you use windows 10 you can download power toys for that.

anyway, if macos:
https://github.com/telegramdesktop/tdesktop/issues/8587

**Comment by badianeka** [comment]
I use Linux.  As I pointed out, other applications respond to the already configured key bindings so the implication is that they are configured.  The issue as indicated is why telegram desktop does honor them?

The desktop environment is XFCE 4.12.3.  and my KeyThemeName under xsettings are set to Emacs.  As I'm typing this reply in Firefox and barring the use of Ctrl-w, I can use all of the keybinds to move through text.

**Comment by ilya-fedin** [comment]
> So what I would like to know is how doesn't Telegram desktop honor them?

Because this is a gtk setting, while tdesktop is qt based

**Comment by badianeka** [comment]
Is there a dot rc file that qt applications might look for where I can insert the keybiding directives? 


   On Saturday, February 6, 2021, 2:42:59 PM EST, ilya-fedin <notifications@github.com> wrote:  
 
 



So what I would like to know is how doesn't Telegram desktop honor them?


Because this is a gtk setting, while tdesktop is qt based

**Comment by badianeka** [comment]
Is there a dot rc file that qt applications might look for where I can insert the keybiding directives?
   On Saturday, February 6, 2021, 2:42:59 PM EST, ilya-fedin <notifications@github.com> wrote:  
 
 



So what I would like to know is how doesn't Telegram desktop honor them?


Because this is a gtk setting, while tdesktop is qt based

**Comment by ilya-fedin** [comment]
Qt provides no way to change default keybindings AFAIK. They're hardcoded in QPA.

**Comment by badianeka** [comment]
QT is, for generality's sake, a programming library and it's use in other environments besides KDE; the latter makes use of QT.  In UNIX/Linux many applications gather configurable parameters from RC dot files, so it's the application developer who has ensure this. QT and GTK are libraries.  GTK as a library can be used to write an application which can run in a desktop environment or with a window manager and it will make use of a dot file where many aspects of its configuration are available. 



   On Sunday, February 7, 2021, 4:22:29 AM EST, ilya-fedin <notifications@github.com> wrote:  
 
 


Qt provides no way to change default keybindings AFAIK. They're hardcoded in QPA.
