### ISSUE TITLE
[Feature Request] PLEASE remove the need for a cellphone number to use telegram, alot of people use services like this BECAUSE they DONT have a cellphone plan. 

### ISSUE THREAD

**Issue by linusrg1** [telegramdesktop/tdesktop#10314]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.
When you sign up for telegram you NEED a cellphone number, which means anyone including myself who doesnt have one cant use telegram, which just seems dumb. 
### Describe the solution you'd like
The ability to choose between a cellphone number AND email when signing up. 
### Describe alternatives you've considered
whatsapp but I do not trust it rn. They have the same issue but at least they had a way around it

**Comment by ilya-fedin** [comment]
This is an issue tracker for desktop client, your issue is server side

**Comment by Aokromes** [comment]
i really doub such feature will be ever implemented.

**Comment by RememberTheAir** [comment]
Related discussion on Telegram's "bugs & suggestions" platform: https://bugs.telegram.org/c/858
