### ISSUE TITLE
Enormous amount of memory used

### ISSUE THREAD

**Issue by vbakc** [telegramdesktop/tdesktop#10327]
![screen](https://user-images.githubusercontent.com/30199803/107160604-44187900-6965-11eb-8eb4-a01f8fcec5d1.png)

App uses more than 2 Gb of memory. Even when closed

### Steps to reproduce
1. Use the app
2. Open system monitor

### Expected behaviour
App uses less than 100mbs of RAM

### Actual behaviour
App uses 2gbs of RAM and it is not the limit

### Configuration
**Operating system:** Debian 10

**Version of Telegram Desktop:**
2.5.8

**Installation source (Linux Only)** - the official website

**Used theme**:
Standard

**Comment by ilya-fedin** [comment]
#7361
