### ISSUE TITLE
Emoji Text Search Field

### ISSUE THREAD

**Issue by BTCAlchemist** [telegramdesktop/tdesktop#10325]
Sometimes people want to search for an emoji using a text search field. This feature can save the user time and can be found on Slack, Discord, and iOS. Would it be possible to add an emoji text search field to the Telegram app?

Emoji text search field in Slack:
![image](https://user-images.githubusercontent.com/56145569/107158639-63e97600-6940-11eb-923e-5e0f641188dd.png)

Telegram emoji without text search field:
![image](https://user-images.githubusercontent.com/56145569/107158614-37355e80-6940-11eb-915a-415a24f3cda3.png)

**Comment by Aokromes** [comment]
you use textbox for that
https://i.imgur.com/Ej5yzNh.png

**Comment by BTCAlchemist** [comment]
@Aokromes Good to know this is an option. However, it doesn't give the full list of emoji search results. It's also less intuitive for users who don't already know they can use a colon ':' to search.

**Comment by ilya-fedin** [comment]
#7772
