### ISSUE TITLE
[Linux] Inconsistent Mouse Pointer in Telegram

### ISSUE THREAD

**Issue by erebus-oneiros** [telegramdesktop/tdesktop#10321]
### Steps to reproduce
1. Install flatpack version of Telegram in Linux Mint.
2. Launch Telegram-Desktop 

### Expected behaviour
The system's default pointer style should show up in telegram.
![photo_2021-02-07_13-07-21](https://user-images.githubusercontent.com/78677882/107140036-7e721e00-6945-11eb-8e3a-d1443febca40.jpg)
![photo_2021-02-07_13-07-25](https://user-images.githubusercontent.com/78677882/107140037-7fa34b00-6945-11eb-876a-9801711813cc.jpg)

### Actual behaviour
Telegram has weird black pointer with weirder "hand selection" tool. 

### Configuration
**Operating system:**
Linux Mint 19.3
**Version of Telegram Desktop:**
Flathub 2.5.8
**Installation source (Linux Only)** - 
flatpak

**Used theme**:
Desktop: Cinnamon Default. 

More info:
This issue is still present. Looking online on different linux forums confirms this. The Snap and Flatpack versions have this weird cursor styles but the .deb or the repository version doesn't.

Another weird behavior: the pointer shows up as the system's default version in screenshots.

**Comment by ilya-fedin** [comment]
But flatpak is a confined environment, tdesktop can't access your system themes

**Comment by ilya-fedin** [comment]
> but the .deb

tdesktop doesn't provide any .debs, so I don't understand what are you talking about...

**Comment by erebus-oneiros** [comment]
I appreciate your quick response.
> tdesktop doesn't provide any .debs, so I don't understand what are you talking about...
Sorry, I thought it would be available as .deb as it had a direct download link from the website. Checked again that's a .tar. 

> But flatpak is a confined environment, tdesktop can't access your system themes
Now this issue makes sense. In that case, wouldn't it make more sense to use the default pointer theme with the "simple" white pointer and white hand selection tool. This theme is by far the most common one in most linux distros so it would make more sense to use this. Another option could be to put pointer selection option in the "Advanced Settings". Like the "Use system Window Frame" there could be a "Use system pointer option".

**Comment by ilya-fedin** [comment]
> In that case, wouldn't it make more sense to use the default pointer theme with the "simple" white pointer and white hand selection tool

Cursor theme support is completely on Qt level, we can't tell Qt which cursor theme we want to use, it is regulated by QPA without any public API for application developers.

**Comment by erebus-oneiros** [comment]
>Cursor theme support is completely on Qt level, we can't tell Qt which cursor theme we want to use

But there should be something different that Telegram is doing with its Flatpack version that is non-standard. You say that the flatpack version can't access the system theme, but then I have flatpack versions of many other software (specific example LibreOffice, Skype) and they all have consistent pointer themes.

**Comment by ilya-fedin** [comment]
> but then I have flatpack versions of many other software (specific example LibreOffice, Skype) and they all have consistent pointer themes.

LibreOffice uses its own toolkit that uses gtk (by default), skype uses electron that is based on chromium that uses its own toolkit that uses gtk as well, while tdesktop uses Qt. If you want to compare tdesktop with other application, you should compare it with VLC or qBittorrent.

**Comment by erebus-oneiros** [comment]
So, I Installed VLC flactpack version and compared. It indeed has the same set of mouse pointers as Telegram's Flatpack.

Looked online for the solution with flatpack. This is a known issue with flatpack but finally found a solution:
https://github.com/flatpak/flatpak/issues/709#issuecomment-741883444
`flatpak --user override --filesystem=/home/$USER/.icons/:ro
flatpak --user override --filesystem=/usr/share/icons/:ro`
This makes flatpack access the same cursor style as the systems. Leaving the solution here in case anyone comes from a web-search. As this has been pointed out many times in the past here on the "Tdesktop issue", this would save time both for you and the users.

Thanks for narrowing down the problem. Appreciate all your time and effort for FOSS!
