### ISSUE TITLE
can no longer drag folders into github desktop (windows 7)

### ISSUE THREAD

**Issue by christopherskyi** [telegramdesktop/tdesktop#1032]
I create a local folder that holds my files. When I drag this folder into github, the name of the folder becomes the name of the repo, the folder name in the local path is grayed out -- see below:

![issue](https://cloud.githubusercontent.com/assets/7048732/9475025/170387d6-4b32-11e5-8002-06df21783f30.gif)

But when I click on create repository, I get a weird error:

![issue2](https://cloud.githubusercontent.com/assets/7048732/9475087/732dd804-4b32-11e5-8c11-9e1a9cf8296e.gif)

Despite getting this error, however, github.com does manage to create a .git folder in my local folder. Anyway, broken behavior on github.com's part, as far as I can tell

**Comment by auchri** [comment]
What has that got to do with telegram desktop?
