### ISSUE TITLE
Flatpak version fails to send any file. "File is empty and can't be sen't"

### ISSUE THREAD

**Issue by igorcmelo** [telegramdesktop/tdesktop#10326]
### Steps to reproduce
1. Click and drag a file to a chat
2. Release it 

### Expected behaviour
File should be selected to be sent

### Actual behaviour
Shows message: "File <filepath> is empty and can't be sen't". <br>

Video showing the issue:
https://user-images.githubusercontent.com/59902451/107159566-b2623900-696f-11eb-90cb-bc838e81275c.mp4

### Configuration
**Operating system:**
OS: ubuntu 20.04

**Version of Telegram Desktop:**
telegram version (flatpak): 2.5.8
telegram version (snap): 2.5.8

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
flatpak version: 1.6.5
snap version: 2.48.2

**Used theme**:
Dark (default).

**More info**:
I also removed flatpak version, deleted all files and installed it again, but problem persists.

**Comment by Aokromes** [comment]
iirc it's flakpak limitation.

**Comment by ilya-fedin** [comment]
https://github.com/flathub/org.telegram.desktop/issues/23
