### ISSUE TITLE
Sending a lot of compressed photos

### ISSUE THREAD

**Issue by VadVergasov** [telegramdesktop/tdesktop#10324]
### Steps to reproduce
1. Select a lot of photos to send and drag and drop then or load with an attach button
2. Select compress
3. Send

### Expected behaviour
All photos should be compressed and sent as photos

### Actual behaviour
Few (about 10) will be sent as photos, other as files.

### Configuration
**Operating system:**
Windows 10 x64 Home, 20H2

**Version of Telegram Desktop:**
2.5.8 stable

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official web-site, then updated

**Used theme**:
Black

<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/5939765/log.txt)
</details>

**Comment by john-preston** [comment]
@VadVergasov Does this happen with 64-bit version of tdesktop? You can find installer and portable archive at https://github.com/telegramdesktop/tdesktop/releases

**Comment by VadVergasov** [comment]
In 64bit portable all is OK.
