### ISSUE TITLE
Doesn't work correctly with windows keyboard in tablet mode

### ISSUE THREAD

**Issue by OlyaZasimovich** [telegramdesktop/tdesktop#10322]
I use telegram on Lenovo yoga x1 gen 5 with windows10 pro 
and when the telegram and the keyboard work simultaneously the keyboard has cut part of the app and the app isn't transform back when the keyboard is disappeared. Could you please fix it?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/218

**Comment by OlyaZasimovich** [comment]
@Aokromes I think it's another issue, cause the keybord is automatically opens in my case, but ruined the app.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8540
https://github.com/telegramdesktop/tdesktop/issues/3274 ?
