### ISSUE TITLE
[Question] shortcuts-custom.json Mac OS

### ISSUE THREAD

**Issue by yevhenshymotiuk** [telegramdesktop/tdesktop#10331]
Where can I find `shortcuts-custom.json` in Mac OS (`~/.local/share/TelegramDesktop/tdata/shortcuts-custom.json` in Linux)? Is this even possible with this or [native app](https://github.com/overtake/TelegramSwift) in Mac OS?

**Comment by john-preston** [comment]
@yevhenshymotiuk ~/Library/Application Support/Telegram Desktop/tdata/

**Comment by yevhenshymotiuk** [comment]
~/Library/Application Support/Telegram Desktop/tdata
❯ pwd
/Users/yevhenshymotiuk/Library/Application Support/Telegram Desktop/tdata

~/Library/Application Support/Telegram Desktop/tdata
❯ ls -al
.rw-r--r-- 145 yevhenshymotiuk  8 Feb 16:55 shortcuts-custom.json

~/Library/Application Support/Telegram Desktop/tdata
❯ cat shortcuts-custom.json
```
[
    {
        "command": "previous_chat",
        "keys": "alt+k"
    },
    {
        "command": "next_chat",
        "keys": "alt+j"
    }
]
```
Doesn't work in either apps. Telegram apps (Telegram Desktop and Telegram Lite are installed from App Store). Not sure if swift app has this functionality but have checked to make sure

**Comment by john-preston** [comment]
@yevhenshymotiuk This path is for Telegram Desktop from website (https://desktop.telegram.org)

Telegram Lite has a more complex path inside some containers. Swift native app is a completely separate thing and it doesn't have this file, it has some in-app settings for shortcuts, if I recall correctly.

**Comment by yevhenshymotiuk** [comment]
Ok, now everything seems fine, thank you. But there is an issue - with the following `shortcuts-custom.json` i am able to use not `ctrl` but `command` + k/j shortcuts. And also if i start my shortcut with alt (f.e. `alt+k`) it doesn't work for `option` at all 
```
[
    {
        "command": "previous_chat",
        "keys": "ctrl+k"
    },
    {
        "command": "next_chat",
        "keys": "ctrl+j"
    }
]
```

**Comment by yevhenshymotiuk** [comment]
I close this because key issues are not related to this question

**Comment by yevhenshymotiuk** [comment]
I can open another issue for this if it is really a bug
