### ISSUE TITLE
[Feature Request] Ability to not receive incoming calls

### ISSUE THREAD

**Issue by pauser0000001** [telegramdesktop/tdesktop#10330]
### Is your feature request related to a problem?
If you have several devices associated with the same account, apparently only one of them receives the call. In my case, the Desktop Application in a system without microphone nor camera, when it is useless to answer an incoming call.

### Describe the solution you'd like
The ability to not receive incoming calls in one device so others with microphone and camera can answer the call.

**Comment by ilya-fedin** [comment]
![image](https://user-images.githubusercontent.com/17829319/107208503-9905cf00-69f9-11eb-96be-6a26f1a5ef3b.png)
