### ISSUE TITLE
QR code log in problem in dark mode

### ISSUE THREAD

**Issue by arbabseyfola** [telegramdesktop/tdesktop#10335]
### Steps to reproduce
1. Add account
2. Quick log in with QR code
3. QR code not detected.

### Expected behaviour
Log in with QR code scanning 

### Actual behaviour
QR code not detected by Android application in dark mode.

### Configuration
**Operating system:** windows 10 64bit

**Version of Telegram Desktop:** 2.5.8 x64

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/10077
