### ISSUE TITLE
Message field highlight all text when chat updates

### ISSUE THREAD

**Issue by SampaioLeal** [telegramdesktop/tdesktop#10339]
### Steps to reproduce
1. Open the client
2. Enter some text
3. Tell your contact to send some text

### Expected behaviour
The message field should not update or change the cursor position

### Actual behaviour
When a message comes, the message field selects all the text you're currently typing.
When the text you're typing is being bigger and the message field breaks a line it selects all the text.

### Configuration
**Operating system:** KDE Neon User Edition - 5.20

**Version of Telegram Desktop:** 2.5.8

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: the official website

**Used theme**: Night Mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Can't reproduce. Some steps to reproduce probably missing (like some custom KDE settings).

**Comment by SampaioLeal** [comment]
Well, for now the problem is gone..... it appeared some times since i installed KDE Neon

**Comment by ilya-fedin** [comment]
Maybe you have a broken mouse/keyboard?
