### ISSUE TITLE
Telegram appears don't support Linux unicode input (ctrl + shift + u)

### ISSUE THREAD

**Issue by ryukinix** [telegramdesktop/tdesktop#1033]
On linux I can't entry a unicode character by ctrl + shitf  + u, like /u221e.
The unicode mode entry just don't show for me.

It's possibile to fix that? I see that problem (or don't implemented feature) a long time...

**Comment by giordano** [comment]
This should be a feature provided by GTK+ library, Telegram Desktop is written with Qt library.

**Comment by ryukinix** [comment]
I didn't know this was a exclusive feature for GTK+. Exists any alternative for write unicode characters at apps made with Qt ?

**Comment by giordano** [comment]
Not that I'm aware of and according to [this answer on superuser.com](http://superuser.com/a/493243/228239), and bug report therein, this isn't going to be fixed in the near future

**Comment by auchri** [comment]
So it's not a issue of telegram?

**Comment by giordano** [comment]
I don't think so.

**Comment by ryukinix** [comment]
Interesting.

**Comment by auchri** [comment]
@giordano Thanks for clarifying!
Closing this because issue of Xorg/Qt
