### ISSUE TITLE
Windows notifications on new joined contacts with option disabled

### ISSUE THREAD

**Issue by superbonaci** [telegramdesktop/tdesktop#10333]
1. Create a new Telegram account on your android phone
2. Install Telegram Desktop and login to your account
3. Disable, on Telegram for android, notifications when contacts join Telegram
4. When you run Telegram desktop again, the option will be disabled on it as well, however I still get toast notifications on Windows 10 when new contacts join Telegram.

Option is disabled automatically on Telegram Desktop:
![](https://i.imgur.com/BewjwlD.png)

Toast notification on new joins still appear (sample image not related):
![](https://news-cdn.softpedia.com/images/news2/Telegram-Desktop-Review-467843-12.jpg)

**Comment by john-preston** [comment]
The toasts should not appear starting with the next version.
