### ISSUE TITLE
If system have 2 display with different scale, Telegram always use scaling from main display

### ISSUE THREAD

**Issue by evemilano** [telegramdesktop/tdesktop#10344]
Steps to reproduce
Connect 2 display and set different scale
Run Telegram
Move telegram window to other display
Expected behaviour
It should re-scale ui and fonts according to diplay settings there it's window located

Actual behaviour
It still have UI/font scaling from main display

Configuration
Operating system:
Windows 10 x64
Version of Telegram Desktop:
2.5.8
Used theme:
Dark

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1121
