### ISSUE TITLE
[Question] How can I disable Ctrl+w?

### ISSUE THREAD

**Issue by emanuele6** [telegramdesktop/tdesktop#10349]
Is there a way to not make `ctrl+w` close telegram?
I am used to using `ctrl+w` to delete the previous word so I keep closing telegram by mistake...

------------------
EDIT: I'm using Telegram Desktop version 2.5.8 on a GNU/Linux system.

**Comment by ilya-fedin** [comment]
No way, this shortcut is hardcoded at Qt level
https://github.com/qt/qtbase/blob/5.15/src/gui/kernel/qplatformtheme.cpp#L194

**Comment by AhyaH-YHWH** [comment]
https://github.com/telegramdesktop/tdesktop/wiki/Keyboard-Shortcuts
https://t.me/TelegramDesktopTalk/48951

Change Keyboard Shortcut, with editing text file "shortcuts-custom.json", on Telegram Installation path

for example on Windows, it can be find in tdata folder
![image](https://user-images.githubusercontent.com/73444508/107618721-47627c00-6c67-11eb-9f18-f79d0d14aa74.png)

**Comment by emanuele6** [comment]
@AhyaH-YHWH It's `~/.local/share/TelegramDesktop/tdata/shortcuts-custom.json` on GNU/Linux.

I just had to write this in that file:
```json
[
    {
        "command": null,
        "keys": "ctrl+w"
    }
]
```

Thanks a lot!
