### ISSUE TITLE
[Feature Request] When people leave a channel/group, make it impossible to add them again for the admin

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#10346]
### Is your feature request related to a problem?
I don't know who from my contact list has left my channel and whom I shouldn't add again. I would consider adding those who left spamming, and I don't want to do that.

### Describe the solution you'd like
As is the case with "Removed users", that can not again join the channel/group, make it impossible for the admin to add again those contacts that left the channel/group.

### Describe alternatives you've considered
There is no better alternative I can think of.

**Comment by RememberTheAir** [comment]
Telegram functions in a way that only your contacts can add you to a group you willingly left. This is how it is intended to work and it's an anti-spam measure, so it's not a feature request to change how it works. In a scenario where someone willingly left a group and an admin want them back, the admin should PM this user and provide him an invite link - and let the user who left decide by theirself whether to join back or not
