### ISSUE TITLE
[Feature Request] Icelandic spell check

### ISSUE THREAD

**Issue by Trendyne** [telegramdesktop/tdesktop#10347]
The hunspell dictionary exists as FOSS. It's used by [libreoffice](https://extensions.libreoffice.org/en/extensions/show/hunspell-is-the-icelandic-spelling-dictionary-project). 
https://github.com/nifgraup/hunspell-is
It's mostly in Icelandic, but build instructions are in English, and pretty straightforward anyway.
Thank you.

**Comment by pYFZOS5** [comment]
https://github.com/telegramdesktop/tdesktop/issues/10356
