### ISSUE TITLE
Can't hear last people entering voice chat if voice chat has more than 5 people.

### ISSUE THREAD

**Issue by veryprofessionaldodo** [telegramdesktop/tdesktop#10357]
### Steps to reproduce
1. Have 5 people in the same voice chat.
2. Have another person join in.
3. The new person can speak, but not be heard.

### Expected behaviour
We should hear every person on the voice chat.

### Actual behaviour
Can only hear first 5 people to join the voice chat in any given time. 

### Configuration
**Operating system:**
Android, Linux, Windows

**Version of Telegram Desktop:**
2.5.8-1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
For Linux I used the AUR version.

**Comment by julietafrade97** [comment]
Same here

**Comment by joao-conde** [comment]
Same for me.

**Comment by zepedrob16** [comment]
Can confirm that this has been happening to me as well on the Desktop App in Windows 10. The voice chat has been restarted several times in the group chat and the problem persists in every attempt.
