### ISSUE TITLE
On multiple monitor setup - Telegram reverts to the main laptop screen out of the blue

### ISSUE THREAD

**Issue by wowfree** [telegramdesktop/tdesktop#10358]
### Steps to reproduce
1.  There are no steps.  
2.   However, I have Telegram open and in 1 of my 2 external monitors 
3.   Then all of a sudden it reverts back into the main monitor of my laptop.  
4.   there's no reason why it happens, it just happens

### Expected behaviour
Tell us what should happen --- it should stay in the monitor screen that I have it in. 

### Actual behaviour
Tell us what happens instead  -- I shard the problem above

### Configuration
**Operating system:**
Window 10
**Version of Telegram Desktop:**
2.5.8
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2840
