### ISSUE TITLE
Could not input Chinese characters with fcitx in Arch Linux 64-bit

### ISSUE THREAD

**Issue by hot123tea123** [telegramdesktop/tdesktop#1035]
https://desktop.telegram.org/#v-0-8-52-stable-19-08-15, this bug is fixed in 0.8.52.
and yes, I installed 0.8.52 version in LinuxMint 17 32-bit, and it works perfect!
however, I still could not input Chinese characters with fcitx in Arch Linux 64-bit.
qt4 4.8.7, qt5 5.5.0, fcitx-qt4 4.2.9, fcitx-qt5 1.0.4

**Comment by hot123tea123** [comment]
fix, my mistake.
I need to setup QT_IM_MODULE.
* Use .xprofile if you are using KDM, GDM, LightDM or SDDM
* Use .xinitrc if you are using startx or Slim.

   export GTK_IM_MODULE=fcitx
   export QT_IM_MODULE=fcitx
   export XMODIFIERS=@im=fcitx

see also: https://wiki.archlinux.org/index.php/Fcitx#GTK.2B_and_Qt_modules

**Comment by adolphlwq** [comment]
@hot123tea123 thx!
