### ISSUE TITLE
[Question] How can I have multiple views of posts in my private channel, if I am the only subscriber?

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#10350]
Basically I created a private channel for drafts, and started seeing strange thing – even though I was the only one who could view them, they had few more views than was possible. My question is simple – HOW?

I hope maybe someone familiar with the development can answer this. What I mean is I am interested in facts, not speculations.

**Comment by RememberTheAir** [comment]
A single users can generate multiple views - there is a cool down to avoid to count multiple views from the same user in a short time, but after some time they're counted again.

Also:
- forwarding a message contributes in increasing its views counter
- views are session-based so views from other devices are counted again

https://twitter.com/telegram/status/1284146769769701377

**Comment by azat11** [comment]
This sucks. This way it's impossible to tell how many unique views posts really have.
