### ISSUE TITLE
Telegram not Starting on Win 10

### ISSUE THREAD

**Issue by Air-Sidney** [telegramdesktop/tdesktop#10353]
### Steps to reproduce
1.  Setup telegram to autostart minimized
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
Windows 10, 20H2, build 19042.746

**Version of Telegram Desktop:**
Latest 2.5.8

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
GitHub releases

**Used theme**:

<details><summary><b>Logs</b>:</summary>
[2021.02.11 12:54:56] Launched version: 2005008, install beta: [FALSE], alpha: 0, debug mode: [FALSE]
[2021.02.11 12:54:56] Executable dir: C:/Users/User/AppData/Roaming/Telegram Desktop/, name: Telegram.exe
[2021.02.11 12:54:56] Initial working dir: C:/Users/User/AppData/Roaming/Telegram Desktop/
[2021.02.11 12:54:56] Working dir: C:/Users/User/AppData/Roaming/Telegram Desktop/
[2021.02.11 12:54:56] Command line: C:\Users\User\AppData\Roaming\Telegram Desktop\Telegram.exe
[2021.02.11 12:54:56] Executable path before check: C:/Users/User
/AppData/Roaming/Telegram Desktop/Telegram.exe
[2021.02.11 12:54:56] Logs started
[2021.02.11 12:54:56] Connecting local socket to Global\2c9ba20c3c337220051b997dad171e4c-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2021.02.11 12:54:56] This is the only instance of Telegram, starting server and app...
[2021.02.11 12:54:56] Could not delete 'C:/Users/User/AppData/Roaming/Telegram Desktop/log.txt' file to start new logging!

[log.txt](https://github.com/telegramdesktop/tdesktop/files/5964385/log.txt)
</details>

**Comment by Aokromes** [comment]
it looks bad permisions, try moving telegram desktop directory to c:\ and test again.

**Comment by Air-Sidney** [comment]
I'm checked filesystem, filesystem is file. 
Permission all granted by Default system. 
After windows restart, telegram run without errors. But if windows is shut dows and start, i see error again. 
Troubles only with Telegram, all other soft working fine

**Comment by ilya-fedin** [comment]
Probably some antivirus software prevents Telegram from removing its log

**Comment by Aokromes** [comment]
maybe anti-rootkit tool from windows 10. that's why i told him to move telegram outside users.

**Comment by ilya-fedin** [comment]
but his user won't have rights in C:\

**Comment by Aokromes** [comment]
> but his user won't have rights in C:\

if he creates fresh directory yes

**Comment by Air-Sidney** [comment]
When windows is shutdown some info saving in cache, when windows restart and loading this cache is clean up.
After restarting windows Telegram run and working fine.

**Comment by Air-Sidney** [comment]
This steps is working. Every times and every days for me on two devices. At home PC and Work PC. All Devices on window 10. Maybe it's happened after some windows update ?

**Comment by ilya-fedin** [comment]
@john-preston you can get file errors via QIODevice::errorString() (that is inherited by QFile) and log them when something weird is happening on file operations that block application launch like this

**Comment by dimonDDL** [comment]
I am experiencing the same issue on a different win10 machine, while the other 3 win10 computers in the house don't experience this issue. 
Version: 2.7.1 from official website.
I have tried looking for what is locking the log.txt file in Process Explorer but it didn't return any results. Also it is impossible to delete the log.txt and if you use a tool like Unlocker to delete it at next startup it will work for that time, but after next reboot it's broken again.
I have tried giving the telegram.exe admin permissions, installing on a different drive, setting the folders as writable but nothing seems to help.

**Comment by ilya-fedin** [comment]
sounds like a virus

**Comment by dimonDDL** [comment]
Wouldn't the process still show up in Process Explorer?

**Comment by ilya-fedin** [comment]
no if the virus hides itself

**Comment by Air-Sidney** [comment]
> sounds like a virus

No viruses. Just one reboot. I told Win 10 made safe last state for boost new loading. But if you reboot saves is cleaning. You can check measure start time when you "Shut down" and power on again your PC and "Reboot".

**Comment by ilya-fedin** [comment]
> No viruses.

How can you describe such behavior then?

**Comment by Air-Sidney** [comment]
> > No viruses.
> 
> How can you describe such behavior then?

Илья, я описал все как есть. Ни одни антивирус никаких вирусов не нашел. Если это бага только у меня ну ок, буду с ней дальше жить ) но на разных компах одно и тоже и только с телегой, странно этот как-то

**Comment by ilya-fedin** [comment]
Ну значит на разных компах что-то есть, потому что что-то не дает тдесктопу удалить лог-файл. Если нет другого экземпляра процесса телеги в фоне, то с системой явно какая-то беда.

**Comment by Air-Sidney** [comment]
> Ну значит на разных компах что-то есть, потому что что-то не дает тдесктопу удалить лог-файл. Если нет другого экземпляра процесса телеги в фоне, то с системой явно какая-то беда.

ни один анализатор не нашел ни одного процесса который бы работал с файлов лога. Телегу понятное дело я выгружаю перед этим.

**Comment by ilya-fedin** [comment]
> ни один анализатор не нашел ни одного процесса который бы работал с файлов лога.

Но ведь что-то все-таки не дает телеге его удалить

**Comment by GermannPerutskij** [comment]
@Air-Sidney как ты решил эту проблему? У меня всё абсолютно аналогично, помогает только снос телеги и чистая установка, после перезапуска проблема повторяется.

**Comment by ilya-fedin** [comment]
вы 100% уверены, что нет повисшего процесса Telegram.exe в диспетчере задач? может он где-то в глубине списка.

**Comment by GermannPerutskij** [comment]
@ilya-fedin Процесс есть, он и не дает запустить повторно Телеграм, пока его не закроешь - заново запустить Телеграм не получится. Но даже если его закрыть и запустить заново - выдают ту же ошибку.

**Comment by ilya-fedin** [comment]
сделай дамп с этого зависшего процесса и отправь его @john-preston (`@preston` в телеге)

**Comment by GermannPerutskij** [comment]
> сделай дамп с этого зависшего процесса и отправь его @john-preston (`@preston` в телеге)

Отправлять кому-то свой дамп файл безопасно? Я не знаю, что в нём содержится.

**Comment by ilya-fedin** [comment]
> Отправлять кому-то свой дамп файл безопасно?

Это полный дамп памяти процесса, включая ключи сессии. Но по-другому не выяснить, в чем проблема.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Air-Sidney** [comment]
Not

**Comment by Air-Sidney** [comment]
Not reproduced on latest versions. I think fixed. Maybe win 10 updates fixed that
