### ISSUE TITLE
video played full screen in wrong screen and app stops working in second screen

### ISSUE THREAD

**Issue by TohidHeshmati** [telegramdesktop/tdesktop#10354]
### Steps to reproduce
1. in a laptop connected to external monitor play a video
2. make the video full screen 
3. problem-1: the app does not react to clicks anymore.
4. problem-2: the full screen option previously was applied to the screen that the app was in and now it gets full screen only on laptop. it would be nice to choose between screens or at least as it was in previous versions be possible to make full screen in the window that the app is present.

### Expected behavior (the word behavior has a typo in issue template;))) )
It was  correct in previous versions and got full screen in the monitor that app was present and the app itself was functional.

### Actual behavior
The app is not functioning while a video is playing in full screen. (it had in older versions)

### Configuration
**Operating system:**
Ubuntu 20
**Version of Telegram Desktop:**
2.5.8
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
(maybe snap)
**Used theme**:
dark
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5126
