### ISSUE TITLE
[Suggestion] Add support for screen magnifying for windows

### ISSUE THREAD

**Issue by rosolko** [telegramdesktop/tdesktop#1036]
For now can't place (magnify) application in some corner or border.

**Comment by auchri** [comment]
It works for me, Win 7, 8 and 10

**Comment by rosolko** [comment]
But, for me doesn't work :(

3 systems:
Windows 10 Home,
Windows 10 Pro,
Windows 8.1 Enterprise

I haven't found any application setting related to this issue.

**Comment by auchri** [comment]
Do you mean the Aero Snap feature of Windows?

**Comment by rosolko** [comment]
No.
Oh, i don't know, how it's exactly names. 
I mean - magnet window to the boundaries of the work area.
And behavior is - you are move application windows to screen corner and application  windows in stick to corner, and don't easy move to off-screen.

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by rosolko** [comment]
Re-check - issue isn't re-producable. Let's close it!
