### ISSUE TITLE
Telegram is not saving changes in a group, when I am trying to change it from private to public

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#10362]
### Steps to reproduce
1. Create a private group
2. Chage the type to public and assign a link (an available link)
3. Click "Save" to close type changing screen, and it closes, and the group type shows as public.
4. Click "Save" to save the changes to the group – and it does nothing; the group management screen does not close, and I can not change the type of the group.

### Expected behaviour
Well, the changes should be saved. As always.

### Actual behaviour
Changes are not saved.

### Configuration
**Operating system:** Win 7

**Version of Telegram Desktop:** 2.5.8

**Used theme**: Tinted

### Additional context
I tried this on Android too – pressing "Save" closes the group management screen, but the changes are not saved.

**Comment by john-preston** [comment]
@azat11 You can look at 'log.txt', there should be an error about that.

**Comment by azat11** [comment]
> @azat11 You can look at 'log.txt', there should be an error about that.

RPC Error: request 532 got fail with code 400, error USERNAME_INVALID

I tried to change another group from public to private and back to public again – and now it too does not return to public with the same error.

**Comment by john-preston** [comment]
@azat11 🤔 I wonder if it is server side issue or if I send something wrongly.. Can you contact me at t.me/preston and share the username you've lost for your public group that you tested the second time (there, in private)?

**Comment by azat11** [comment]
> 
> 
> @azat11 thinking I wonder if it is server side issue or if I send something wrongly.. Can you contact me at t.me/preston and share the username you've lost for your public group that you tested the second time (there, in private)?

DM'd you there.
