### ISSUE TITLE
Incorrect menu behavior in X11

### ISSUE THREAD

**Issue by mikhirev** [telegramdesktop/tdesktop#10366]
Hello!

In all Qt (an not only Qt, also GTK etc.) apps it is possible to activate a menu item without extra click: 

1. Press a mouse button to open menu (either left button on menu bar or right button for context menu).
2. Move the pointer to menu item.
3. Release the button to activate the item.

This is very convenient and ergonomic. But this does not work in Telegram Desktop. You have to release the button and make one additional click on the menu item. Such behavior breaks a habitual procedure. Please fix menus to behave as all standard applications.

### Steps to reproduce
1. Press a mouse button to open menu (either left button on menu bar or right button for context menu).
2. Move the pointer to menu item.
3. Release the button.

### Expected behaviour
The menu item is activated.

### Actual behaviour
Nothing happens until you click the left mouse button one more time.

### Configuration
**Operating system:** Debian GNU/Linux 10

**Version of Telegram Desktop:** 2.2.0+ds-2~bpo10+1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: distribution package

**Used theme**: classic

**Comment by ilya-fedin** [comment]
> 2.2.0+ds-2~bpo10+1

Latest version is 2.5.8, you can't report for outdated version here

**Comment by mikhirev** [comment]
It is a longstanding bug and I don't think it was fixed since 2.2.0 release. Anyway it is very easy to reproduce. A developer should have a fresh version built, and can make couple of clicks to see what I described.

The version I use is the latest one in Debian 10 official repos.

**Comment by ilya-fedin** [comment]
Please test on the latest version from https://desktop.telegram.org if you want to report here.

**Comment by mikhirev** [comment]
I wont install software from untrusted sources. Reproducing the issue would take much less of your time than typing replies here.

**Comment by ilya-fedin** [comment]
¯\_(ツ)_/¯ you can't report here without testing on official builds, sorry

**Comment by Aokromes** [comment]
> I wont install software from untrusted sources. Reproducing the issue would take much less of your time than typing replies here.

desktop.telegram.org is official source.

**Comment by bagasik** [comment]
First the right button, then the left one, in this sequence the menu is used.
