### ISSUE TITLE
Incorrect participants counter on voice chat

### ISSUE THREAD

**Issue by ErfanPY** [telegramdesktop/tdesktop#10363]
### Steps to reproduce
1. Make a voice chat in a group.
2. Add some people to the voice chat.
3. Ask some ones to leave the voice chat.

### Expected behaviour
The participants counter should decrease when some one left.

### Actual behaviour
The participants counter remains at highest value like no one left the voice chat.

### Configuration
Windows 10

Version 2.5.8 telegram desktop

**Comment by VadVergasov** [comment]
Can't reproduce this issue... Tried with two accounts.

**Comment by ErfanPY** [comment]
All of my friends on telegram desktop had same issue .
how can I represent this issue here ? Should I screen record it when it happens ?

By the way we all use proxy or VPN for connection. Can be related ?
