### ISSUE TITLE
Use a symbolic/monochrome tray icon on linux?

### ISSUE THREAD

**Issue by JoeJoeTV** [telegramdesktop/tdesktop#10378]
I installed telegram using a community ppa(but this applies to the tar.gz download as well) and I noticed that it doesn't use a symbolic tray icon like most other programs.
I tried using hardcode-tray, but that didn't even detect telegram.
I have seen this working before, on an old installation of Linux Mint 19.3, but I don't know the steps it required to get working.
I am using the Papirus Icon pack which I was also using back then and it has icons for telegram.

Is it possible to get a symbolic tray Icon for Telegram on Linux?

Specs:
- OS: Linux Mint Cinnamon 20.1 64 bit
- TG Install: tar.gz download or community PPA

**Comment by ilya-fedin** [comment]
Check that you have the right icon theme set in qt5ct

**Comment by JoeJoeTV** [comment]
> Check that you have the right icon theme set in qt5ct

Thank You! That was what I was searching for. Ok this issue is solved.
