### ISSUE TITLE
No way of telling who wrote what in channel conversations

### ISSUE THREAD

**Issue by jaromor** [telegramdesktop/tdesktop#10373]
### Steps to reproduce
1. create a New Channel
2. invite people
3. start the conversaion

### Expected behaviour
I should be able to tell which message was written by whom

### Actual behaviour
All messages are in the same color, all aligned to the left (regardless of "Adaptive layout for wide screens")

### Configuration
Windows 10
1920x1200

**Version of Telegram Desktop:**

2.5.8

**Used theme**:

Default, also tried Dracula

![image](https://user-images.githubusercontent.com/40000923/107878734-e049ff00-6ed4-11eb-80a5-5a261f123712.png)

**Comment by Aokromes** [comment]
it's how channels works.
