### ISSUE TITLE
Windows build issue. "module machine type 'x86' conflicts with target machine type 'x64'"

### ISSUE THREAD

**Issue by Thoufak** [telegramdesktop/tdesktop#10375]
Hello. I'm trying to build the tdesktop with VS. I'm using [this guide](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md) and there seems to be an issue with the step "Clone source code and prepare libraries". I'm inputting the commands one by one, so that I can study the output carefully. The command **nmake** (right after **perl Configure no-shared no-tests VC-WIN32**) fails with the description **fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'**. Please see the console logs attached.

[tdesktop_build_nmake_failure.txt](https://github.com/telegramdesktop/tdesktop/files/5978003/tdesktop_build_nmake_failure.txt)

**Comment by ilya-fedin** [comment]
Looks like you've violated this step
![изображение](https://user-images.githubusercontent.com/17829319/107883024-31152400-6ee4-11eb-8403-0c7bb5745160.png)

**Comment by Thoufak** [comment]
Yes, indeed. Thank you.
