### ISSUE TITLE
[Bug] Font is distorted on some devices.

### ISSUE THREAD

**Issue by sunstream** [telegramdesktop/tdesktop#1037]
Summary: on a workstation running Windows Server 2012 the font in Telegram gets distorted: some (or all of) vertical lines in the letters have double width.

Issue history:
1. My friend installed Telegram on his workstation, complained about font issue and sent me a screenshot (see screenshot 1).
![fonts_screenshot_1](https://cloud.githubusercontent.com/assets/3416701/9487600/befa556a-4bdb-11e5-90db-751a6aba7664.jpg)
2. I advised him to change Telegram UI scale to 125%. The issue was gone.
3. Next day, when he launched Telegram, the issue re-appeared on 125%. He tried to switch to 100% scale, but the distortion grew worse (see screenshot 2).
![font_screenshot_2](https://cloud.githubusercontent.com/assets/3416701/9487599/bef4efee-4bdb-11e5-81de-578344b38dbc.jpg)

We are both using Russian language (Cyrillic alphabet), but I observe no issues with fonts on my workstation.

Workstation comparison:

Problematic one:
OS: Windows Server 2012
Screen resolution: 1920х1080
Telegram version: portable

"Good" one:
OS: Windows 7 SP 2
Screen resolution: 1366x768 and 1920x1080
Telegram version: installed

**Comment by auchri** [comment]
Is font smoothing enabled on the windows server?

**Comment by sunstream** [comment]
> Is font smoothing enabled on the windows server?
Yes, it is.

**Comment by auchri** [comment]
Windows Server is not official supported, so I'm not sure if I should close this or not.
@telegramdesktop

**Comment by sunstream** [comment]
> Windows Server is not official supported, so I'm not sure if I should close this or not.

Is changing the default font feature planned for Telegram Desktop? If yes, then changing the font might solve this problem. Could WS 2012 have font smoothing problems with this particular font?

**Comment by auchri** [comment]
I don't think that the default font will be changed

**Comment by sunstream** [comment]
> I don't think that the default font will be changed

I mean a possibility for the user to pick custom font, as in the other messengers (like Miranda or Pidgin).

**Comment by auchri** [comment]
Maybe sometimes, see #90

**Comment by sunstream** [comment]
> Maybe sometimes, see #90

Can we link these issues to check if this feature fixes the problem?

**Comment by auchri** [comment]
Yep
