### ISSUE TITLE
Download "Failed" in the Linux installer version

### ISSUE THREAD

**Issue by prasannarajaram** [telegramdesktop/tdesktop#10370]
### Steps to reproduce
1. Start Telegram desktop 
2. Navigate to any channel with media (vidoes)
3. Click on the Download icon

### Expected behaviour
It should download the media to the preferred download folder

### Actual behaviour
On the same media (video in my case), the download icon gets replaced with "Failed"

### Configuration
**Operating system:**
Arch Linux
**Version of Telegram Desktop:**
2.5.8
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
 - https://desktop.telegram.org/
 - Arch repo
 For both the installation sources, I face the same issue
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
> Insert log.txt here (if necessary)

It's necessary
