### ISSUE TITLE
[Question] msbuild openAL fails

### ISSUE THREAD

**Issue by Thoufak** [telegramdesktop/tdesktop#10379]
Hi. I'm using [this guide](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md) to build the app. The command **msbuild OpenAL.vcxproj /property:Configuration=Debug** fails with a lot of errors (see logs attached). There also might be some problems with the preceding **cmake** command as it says "Could NOT find" multiple times (see the logs of this command attached too). 

[msbuild OpenA.txt](https://github.com/telegramdesktop/tdesktop/files/5979935/msbuild.OpenA.txt)
[cmake.txt](https://github.com/telegramdesktop/tdesktop/files/5979936/cmake.txt)

**Comment by ilya-fedin** [comment]
This looks like openal bug https://github.com/kcat/openal-soft/issues/498
