### ISSUE TITLE
Please add folders and subfolders in channel/user list

### ISSUE THREAD

**Issue by borisgappov** [telegramdesktop/tdesktop#10387]
I use telegram not only as a means of communication but also as a means of receiving the news. 
Due to the fact that there are too many channels and people, it becomes difficult and inconvenient to find the desired channel or chat. 
I would like to group channels like Friends, Work Chats, News, etc. 
Moreover, folders should allow creating a nested structure (subdirectories)

**Comment by RememberTheAir** [comment]
> I would like to group channels like Friends, Work Chats, News, etc.

You can do that: settings -> folders

**Comment by Aokromes** [comment]
subfolders must be added aplications wide, not only desktop.

https://bugs.telegram.org
