### ISSUE TITLE
Cursor hovering stops working

### ISSUE THREAD

**Issue by gorghino** [telegramdesktop/tdesktop#10384]
### Steps to reproduce
1. Something I haven't figured out yet. 
2. Cursor stuck to to "Finger pointing" and hovering effects stop working
3. Click GUI elements doesn't follow the correct behavior in general

### Expected behaviour
I expect the arrow cursor on the chat when I'm not selecting anything in particular.
I expect hand cursor when I'm hovering pictures, links, gif.
I expect to see the emoji list If I hover the emoji button.
I expect to see the "Writing cursor" hovering the search bar.
I expect to see gray background when hovering my chat entries etc.

### Actual behaviour
The cursor stay "stuck" to the latest used and hovering effect are not working.
I can click on the emoji button; this triggers the hand cursor that continues over all the elements in the window.
If I open the chat setting (top right menu), hovering out doesn't close the menu. I can actually close the right bar and the menu remain open in the center of the window with the menu button 'selected'.

![image](https://user-images.githubusercontent.com/1898283/107963003-e8bf3a00-6fa7-11eb-9727-5b7b4decd003.png)

Restarting the app doesn't solve the issues.
Logging off/on again in the session **solves** the issues. 

Video example: https://drive.google.com/file/d/15WDwdX_TJ6ok48RkM1jvKsHM0m6-Grvn/view?usp=sharing
(Don't mind the black screen at the beginning, that's an error from video exporting. Note the emoji remains selected once clicked. Resizing the window doesn't solve)

### Configuration
![image](https://user-images.githubusercontent.com/1898283/107965017-48b6e000-6faa-11eb-90b2-7122b42a4027.png)

**Version of Telegram Desktop:** 2.5.8 

**Installation source (Linux Only)** : flatpak

Starting telegram with the terminal gives me this warning (related?):

> gorgo@pop-os:~/Downloads/Telegram Desktop$ flatpak run org.telegram.desktop --help
(process:2): Telegram-WARNING **: 15:55:27.901: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 15:55:27.902: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 15:55:27.902: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).

**Comment by ilya-fedin** [comment]
Can you reproduce with the official version from https://desktop.telegram.org?

**Comment by gorghino** [comment]
I've used the official version in the last few days and I'm not facing the bug I described.
Probably only flatpak's version is affected? Shall I address the problem to someone else?

**Comment by ilya-fedin** [comment]
Is this Xorg or Wayland?

**Comment by gorghino** [comment]
Xorg

**Comment by ilya-fedin** [comment]
I can't reproduce with flatpak as well...

**Comment by gorghino** [comment]
It's hard saying what is causing this bug...
I'm using "Hybrid graphic" mode with Pop!_Os to use PRIME support from NVIDIA.
Could I run flatpak Telegram with debug log? May be useful to you?

**Comment by ilya-fedin** [comment]
Application debug log will be useless, such low-level things are handled at Qt level :(

**Comment by ilya-fedin** [comment]
You may want to check other Qt applications from flatpak, like VLC or qBittorrent

**Comment by gorghino** [comment]
I confirm this happens with the official version too (2.6.1 running atm).
```

gorgo@pop-os:~$ ps aux | grep Telegram
gorgo       7992  3.1  6.2 7477704 1010092 ?     Sl   mar03  38:05 /home/gorgo/Telegram/Telegram -workdir /home/gorgo/.local/share/TelegramDesktop/ --
```

I don't use VLC or other QT apps so often to report similarities :( If it happens, I'll report it.

**Comment by ilya-fedin** [comment]
I still can't reproduce this. Maybe something is wrong with your system configuration? You seem to be the only who affected by this problem.

**Comment by Demetri0** [comment]
I meet this bug couple of times but restart the telegram-desktop solves the problem for me.
Ubuntu 20.04 / GNOME 3.36.5

**Comment by ilya-fedin** [comment]
Probably steps to reproduce lack something then? Because I can't reproduce and never seen such a bug.

**Comment by ilya-fedin** [comment]
Maybe some GNOME extension interferes with tdesktop?

**Comment by Demetri0** [comment]
No, sorry, as I mentioned before that was a couple of times with a long time window, so I didn't attach any importance to it.

My Extensions list:
- Caffeine by eon
- Desktop Icons by rastersoft
- EasyScreenCast by tobias47n9e
- Remove Dropdown Arrows by mpdeimos
- TeaTime by oleid
- Top Panel Workspace Scroll by gfxmonk

**Comment by ilya-fedin** [comment]
Can you disable all of them and check if the issue will disappear?

**Comment by ilya-fedin** [comment]
> Ok, next time I meet that, I will try to disable extensions firstly :)

Well, if you meet that, this probably would mean that extensions are already did something that turned tdesktop into that state (and given that @gorghino says that only logout helps, these extensions may break some insternal GNOME state until GNOME restart).

The thing is that you should disable all the extensions, relogin and live some timee without them and see if the issue will appear or not.

Given that tdesktop restart helps for you, but not for @gorghino, you both should do this since you may have two different issues and for one of you this may help, while for other is not.

**Comment by gorghino** [comment]
Ok, actually last time I faced the bug, closing and reopening it solved the problem. 
Maybe flatpak's version require a logout?

My extensions are:
```
gorgo@pop-os:~$ gnome-extensions list
extensions@abteil.org
ESC_to_close_overview@paperthin.gmail.com
alt-tab-raise-first-window@system76.com
always-show-workspaces@system76.com
ding@rastersoft.com
pop-shell@system76.com
pop-shop-details@system76.com
system76-power@system76.com
ubuntu-appindicators@ubuntu.com

```

**Comment by ilya-fedin** [comment]
@gorghino please

> disable all the extensions, relogin and live some time without them and see if the issue will appear or not

**Comment by gorghino** [comment]
The issue just appreared with ALL extensions disabled. 

I closed and reopen Telegram. (I checked, no active Telegram process was on ps -aux).
The cursor is the default arrow at the beginning. If I click on a contact chat, the cursor changes to the hand cursor and it doesn't hover on anything as described in the first thread.
Right click change the cursor to the arrow until I click on emoji icon; then it becomes hand cursor and it doesn't change.

I tried to xkill Telegram and reopen it but the behaviour persists.
I guess at the moment I can restore the correct behavior with logout/login.

Please let me know if I can check something (env variables?) at the moment when I'm facing the issue.

**Comment by ilya-fedin** [comment]
That's bad. I still can't reproduce this, have no idea what this could be and how to fix this, sorry :(

**Comment by gorghino** [comment]
Update: apparently when Telegram is 'unresponsive' , If I open ArduinoIDE, that's unresponsive as well. On ArduinoIDE I cannot click on anything; the cursor stay on "Select Text cursor"; some buttons changes on hover but I cannot click on them...
I knew ArduinoIDE is java-based but no idea about graphics-libs  hmm
I'm trying VLC and qBittorrent but they seems ok

**Comment by gorghino** [comment]
Can't tell if it's related, but touching the touchscreen restores Telegram to the normal cursor behavior. Investigating..

**Comment by ilya-fedin** [comment]
> Investigating..

Have you investigated?

**Comment by gorghino** [comment]
I'm still looking for which steps lead to the problem. At least I know that touching the touchscreen is a workaround to avoid rebooting.

**Comment by ilya-fedin** [comment]
Oh, ok :(

**Comment by ilya-fedin** [comment]
A month has passed, have you investigated?

**Comment by gorghino** [comment]
Unfortunately not. I usually look at the syslog to catch some video errors that may break tg but I haven't found a constant so far.
