### ISSUE TITLE
Crash when trying to send very high resolution pictures to chat

### ISSUE THREAD

**Issue by VictorienXP** [telegramdesktop/tdesktop#10386]
### Steps to reproduce
1. Going in any chat or any other places where you can send pictures
2. Selecting/drag&drop very high resolution png file(s) to upload (10000x10000 for example)
3. Repeat step 2 if you get the expected behavior (add more at once).

### Expected behaviour
Having the picture(s) showing up and ready to send

### Actual behaviour
Crash

### Configuration
**Operating system:** Windows 10 Pro "20H2" 19042.804

**Version of Telegram Desktop:** 2.5.8

**Used theme**: custom

### Details
I've made a test png file with GIMP which is around ~2 MB and 10000x10000 in resolution.
My test png opened in GIMP takes around ~800 MB of RAM.
My Telegram in idle (just after startup) was at ~121 MB of RAM.
Telegram might not expect such big compressed png files.
Related issue: #6187

### Crash report
```
ApiId: 2040
Assertion: "!file.preview.isNull()" storage_media_prepare.cpp:276
Binary: Telegram.exe
Launched: 17.02.2021 00:17:06
Platform: Windows32Bit
Version: 2005008
Memory-usage: 921 MB (peak), 551 MB (current)
Pagefile-usage: 908 MB (peak), 537 MB (current)

Google Breakpad caught a crash, minidump written in thread 20712
Minidump: db98fa61-0564-4f2f-baeb-6e1585431b0b

Backtrace omitted.
```

**Comment by ilya-fedin** [comment]
This is 32-bit RAM limit, if you want to past so big images, download a 64-bit version from https://github.com/telegramdesktop/tdesktop/releases/tag/v2.5.8

**Comment by VictorienXP** [comment]
I wasn't aware there is a 64-bit build available for Windows, is it new?
Thank you for mentioning it!
64-bit should definitely fix the issues I have with big files!

**Comment by john-preston** [comment]
@VictorienXP Yes, it is still being tested.
