### ISSUE TITLE
Changes in settings are not applied

### ISSUE THREAD

**Issue by Sounderro** [telegramdesktop/tdesktop#10388]
### Steps to reproduce
1. Settings - Advanced- Automatic media download - Any of choice (private chats, groups, channels) 
2. In any sections (Automatically download and Autoplay)  select Limit by size to "up to 1 MB", other switchs set to No.
3. 

### Expected behaviour
After click Save changes applies.

### Actual behaviour
After click Save "Limit by size" returns to default values.

### Configuration
**Operating system:** Windows 7 SP1

**Version of Telegram Desktop:** 2.5.8 Portable

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@Sounderro If you choose everywhere No, then the limit is not saved, because in code there is just a limit for every type and zero, if you choose No. So it really saves zeros for all types.

I should hide the limit slider if you uncheck all media types.

**Comment by Sounderro** [comment]
Thank you for explanation.

**Comment by ilya-fedin** [comment]
#7190
