### ISSUE TITLE
Hide silent notifications in tray icon counter

### ISSUE THREAD

**Issue by marcocastignoli** [telegramdesktop/tdesktop#10385]
### Is your feature request related to a problem?
From my point of view, it is a problem. The main reason why I want to mute a group is because I don't want to lose my attention into it. Having the notification counter always on is disturbing me

### Describe the solution you'd like
Simply remove the counter for silent notifications

**Comment by ilya-fedin** [comment]
look into notification settings in the app

**Comment by marcocastignoli** [comment]
I'm both sorry and happy to know that this exists. Sorry ofc to have bothered you.
