### ISSUE TITLE
Popup window of incoming call is really glitchy in tablet mode on windows

### ISSUE THREAD

**Issue by l0drex** [telegramdesktop/tdesktop#10391]
### Steps to reproduce
1. Enter tablet mode
2. Get called

### Expected behaviour
A popup window should appear to accept the call

### Actual behaviour
The popup window appears, but is really glitchy. When pressing the accept button, a short delay of maybe two seconds passes until the call is accepted. Sometimes I can't even press any buttons.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.5.1

**Used theme**: Default

**Comment by Aokromes** [comment]
try on 2.5.9

**Comment by l0drex** [comment]
Just updated to 2.5.9.0, the issue is still there. Window for incoming all is lagging around so that I can't press any buttons

**Comment by l0drex** [comment]
Any updates?

**Comment by l0drex** [comment]
I have experienced some issues in tablet Mode with Firefox, too. I 'fixed' them by using the native title bar. 

Since this popup seems to use a custom title bar, too, it might help to use the native one.
