### ISSUE TITLE
incorrect search 

### ISSUE THREAD

**Issue by spartaque** [telegramdesktop/tdesktop#1039]
Hi!
In recent time i found some bug
![4519afc53f](https://cloud.githubusercontent.com/assets/5092164/9499046/383dce8e-4c1d-11e5-9d73-e9e2f0d71092.jpg)

**Comment by auchri** [comment]
You have to write full words
![image](https://cloud.githubusercontent.com/assets/5092164/9499123/c050ee00-4c1d-11e5-97cb-c945e534b87b.png)
