### ISSUE TITLE
Cannot determine which image has been replied to on Linux

### ISSUE THREAD

**Issue by MaxMatti** [telegramdesktop/tdesktop#10390]
### Steps to reproduce
1. Send multiple images in one gallery
2. Reply to one of the images
3. Click on the "reply to" part of the reply which links to the original image

### Expected behaviour
the original image should be highlighted in the gallery

### Actual behaviour
on linux: the whole gallery is being highlighted
on windows: expected behaviour

### Configuration
**Operating system:** Archlinux

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)** - distribution package: AUR 2.5.1-1

**Used theme**: https://t.me/addtheme/abtheme as well as the default theme

<details><summary><b>Screenshots</b>:</summary>
Windows: <img width="509" alt="image" src="https://user-images.githubusercontent.com/1584478/108197240-65722580-711a-11eb-8c52-26680ae086aa.png">

Linux: <img width="509" alt="image" src="https://user-images.githubusercontent.com/1584478/108197278-728f1480-711a-11eb-9aa0-fe61b2ada020.png">
</details>

**Comment by ilya-fedin** [comment]
> **Version of Telegram Desktop:** 2.5.1

Current latest version is 2.5.8, old versions aren't supported

**Comment by MaxMatti** [comment]
Seems like I had trouble updating Telegram which is why I thought 2.5.1 is the current version. Issue is fixed in 2.5.8,
