### ISSUE TITLE
[Feature Request] Timed message independent console and timed message automatically define the sending time

### ISSUE THREAD

**Issue by cxplay** [telegramdesktop/tdesktop#10397]
Add an independent console to timing messages; *every next message can be sent at this time.*
The function of timing messages is great, but often because each timing message needs to manually set the sending time, the efficiency is reduced.

**Comment by RememberTheAir** [comment]
This cannot be done by this app because the API doesn't offer any method for recurring schedules or scheduling intervals - and it's not a standard feature on any of the official clients. You should bring this to https://bugs.telegram.org/
