### ISSUE TITLE
> Because it's not an issue for some people

### ISSUE THREAD

**Issue by blacklat** [telegramdesktop/tdesktop#10393]
> Because it's not an issue for some people
> 
> It's a feature, not a bug

you're wrong, if the character shown is different from the one provided it is an error

_Originally posted by @blacklat in https://github.com/telegramdesktop/tdesktop/issues/522#issuecomment-718756122_

so, will you guys solve this ridiculous bug that extends for years or not?

**Comment by Aokromes** [comment]
when it's intended it's not a bug.

**Comment by blacklat** [comment]
> when it's intended it's not a bug.

Obviously it is, you don't have to be very smart to reach that conclusion. If I type a character and another one appears, it is OBVIOUS that it is wrong. I wanted to know whose mental retard was responsible for this ridiculous idea of changing characters.

**Comment by ilya-fedin** [comment]
What's the problem to disable the feature if you don't need it? 🙄

**Comment by john-preston** [comment]
@blacklat It was mine 😔

**Comment by ShrirajHegde** [comment]
> @blacklat It was mine

#16221 end this nonsense please, better late than never

**Comment by ShrirajHegde** [comment]
>when it's intended it's not a bug.

Wikipedia:

>A software bug is an error, flaw or fault in a computer program or system that causes it to produce an <ins>**incorrect**</ins> or <ins>**unexpected result**</ins> , or to behave in unintended ways.

this is both incorrect and unexpected

**Comment by blacklat** [comment]
@ShrirajHegde 

so is your knowledge based on wikipedia? you must be a guy with a lot of knowledge, congratulations

**Comment by ShrirajHegde** [comment]
Is this another desperate attempt to feel superior by calling Wikipedia unreliable?

Definitions are reliable on Wikipedia

**Comment by blacklat** [comment]
@ShrirajHegde fuck you lamer

**Comment by ShrirajHegde** [comment]
> @ShrirajHegde fuck you lamer

@blacklat 

"wIkIpeDia bAaAaD, mE gOoD,I nO tRuSt wIkIpeDiA, giB mE nObEl"

Imagine having to act like definitions on Wikipedia inorder to feel superior, LOL. And then calling others lame.

**Comment by ShrirajHegde** [comment]
> @ShrirajHegde fuck you lamer


@blacklat 

"wIkIpeDia bAaAaD, mE gOoD,I nO tRuSt wIkIpeDiA, giB mE nObEl"

Imagine having to act like definitions on Wikipedia are unreliable inorder to feel superior, LOL. And then calling others lame.
