### ISSUE TITLE
[Bug] Use system window frame is not working for voice chat dialog

### ISSUE THREAD

**Issue by Demetri0** [telegramdesktop/tdesktop#10409]
### Steps to reproduce
1. Go to settings -> Advanced. And set option Use system window frame
2. Open any group voice chat (or 1-1 voice window)

### Expected behaviour
System window frame should be applied both to the main window and voice chat window

### Actual behaviour
System window frame applied only to the main window, but not for voice chat window

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** 2.5.9

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Dark

**Comment by Aokromes** [comment]
afaik not a bug, instead intended.

**Comment by Demetri0** [comment]
@Aokromes I believe it looks very nice for windows users, but for me, it looks foreign. I could not say that it looks pretty on my system, and I expect the option that says "Use system window frame" would be applied for each window, not for main only.

**Comment by ilya-fedin** [comment]
#10002

**Comment by Demetri0** [comment]
Well if there is already the feature request, I think this issue could be closed
