### ISSUE TITLE
How to report bug to android telegram team?

### ISSUE THREAD

**Issue by artiblaster** [telegramdesktop/tdesktop#10401]
Hello,

sorry that I bring it here,

I want to report a bug on Android version, but I have no idea where to do that!

Sorry that it's here, but I just want to report a bug

**Comment by MasterGroosha** [comment]
Please, don't spam TDesktop repo with irrelevant issues. If you have any troubles with other Telegram apps, you have many options, e.g.:
1) Ask in-app support (Settings -> Ask a question)
2) Report your issue at https://bugs.telegram.org
3) Ping `@Telegram` in Twitter
