### ISSUE TITLE
[Feature Request] Notification counter for themed icons on Linux

### ISSUE THREAD

**Issue by Shatur** [telegramdesktop/tdesktop#10407]
### Is your feature request related to a problem?
After version 2.5.5, if the system theme contains a monochrome icon, then the notification counter is not displayed on it.

**Before:**

![изображение](https://user-images.githubusercontent.com/22453358/108477689-384d8080-729c-11eb-9a90-80cc54fd6a0e.png)

**After:**

![img](https://user-images.githubusercontent.com/37000960/106243824-0ad06280-621b-11eb-8141-b861d5e78674.png)

This approach may be look nice in some situations, but it is much less practical.

### Describe the solution you'd like

It would be nice to add an option that would return the old behavior (displaying notification counter). It would make everyone happy.

As a workaround, users can change the icon theme for Telegram, which does not contain the icon for the system tray. But then the Telegram icon will look different from the rest of the monochrome icons (see how it worked before in the screenshots above).

### Additional context

I talked with @ilya-fedin and he said that I should ask @john-preston.

Related issues reported by confused users: #10264, #10251, #10263.

**Comment by john-preston** [comment]
@Shatur95 It's OK with me if the option is displayed only in that case (it actually changes something).

**Comment by Shatur95** [comment]
> @Shatur95 It's OK with me if the option is displayed only in that case (it actually changes something).

Can be checked using [QIcon::hasThemeIcon()](https://doc.qt.io/qt-5/qicon.html#hasThemeIcon).

**Comment by ilya-fedin** [comment]
> Can be checked using [QIcon::hasThemeIcon()](https://doc.qt.io/qt-5/qicon.html#hasThemeIcon).

hasThemeIcon is already used
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/linux/main_window_linux.cpp#L155-L159
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/linux/main_window_linux.cpp#L633-L636

> No, will always return true because the installed app will have an icon in the hicolor folder.

It works as supposed until you're using distribution package with KDE. KDE injects their bugged libraries and it works wrong. Not a blocker since installation via distribution packages is not recommended anyway.

**Comment by Shatur95** [comment]
> hasThemeIcon is already used

I meant that the suggested option might appear when an icon from the theme is used by checking (as was suggested by @john-preston).
But maybe this option can only exist on Linux without any checks, since the user can change the icons theme at any time?

**Comment by ilya-fedin** [comment]
> I meant that the suggested option might appear when an icon from the theme is used for Telegram

Yeah, I understood. I just mentioned that hasThemeIcon is broken only when KDE injects their bugged libraries. It will work just fine for users of official binary.

**Comment by ilya-fedin** [comment]
> I meant that the suggested option might appear when an icon from the theme is used for Telegram

Yeah, I understood. I just mentioned that hasThemeIcon is broken only when KDE injects their bugged libraries. It will work just fine for users of official binary.

**Comment by Phi-Li** [comment]
> > I meant that the suggested option might appear when an icon from the theme is used for Telegram
> 
> Yeah, I understood. I just mentioned that hasThemeIcon is broken only when KDE injects their bugged libraries. It will work just fine for users of official binary.

Not at all. Just downloaded `tsetup.2.8.1.tar.xz` from desktop.telegram.org and icon was still the KDE blue dot version.
I'm using:
- Archlinux 5.12.14
- Plasma 5.22.3
- Plasma framework 5.83.0

**Comment by ilya-fedin** [comment]
They added a monochrome icon. Lack of counter on monochrome is expected and exactly the reason this check was added. If you want counter, you should use icon pack without monochrome icon.

**Comment by Shatur** [comment]
> If you want the counter, you should use icon pack without monochrome icon.

Yes, and this proposal suggests to apply the counter even on monochrome icons, as it was before. Because at the moment the user can have either a monochrome icon that matches his theme, but without a counter, or a counter, but with an icon that stands out in the system tray.
The developers seems to agree, but I need to find time to send a PR :)

**Comment by ilya-fedin** [comment]
> Yes, and this proposal suggests to apply the counter even on monochrome icons, as it was before.

No, thanks, this will break color schemes again :)

**Comment by Shatur** [comment]
> No, thanks, this will break color schemes again :)

This should be a colorscheme issue if it defines a wrong icon. Also the user can even fix it yourself by simply replacing the icon.
And @john-preston  agreed with my proposal as far as I understood.

**Comment by ilya-fedin** [comment]
> This should be a colorscheme issue if it defines a wrong icon.

The thing is, color-scheme is applied on panel side. When the counter is being added, the icon is rasterized and sent as a bitmap, so applying color scheme is no longer possible.

> Also the user can even fix it yourself by simply replacing the icon

You can do the same to get counter

**Comment by ilya-fedin** [comment]
> And @john-preston agreed with my proposal as far as I understood.

He agreed that there could be an option, not a revert (you said "as it was before", so I assume you meant revert)

**Comment by Shatur** [comment]
> The thing is, color scheme is applied on panel side. When the counter is being added, the icon is rasterized and sent as a bitmap, so applying color scheme is no longer possible.

Sorry, I didn't get it. What's the problem with applying a color scheme?

> You can do the same to get counter

Yes, I technically can replace cached icons with monochrome by modifying **every** cached icon with counter, but let's be realistic :)

> He agreed that there could be an option, not a revert (you said "as it was before", so I assume you meant revert)

No, sorry, I meant to add a parameter that restores the previous behavior.

**Comment by ilya-fedin** [comment]
> How color schemes can be broken by the old behavior?

KDE applies color scheme to svg icons. You can change the color of monochrome icons by chaning color scheme in KDE settings. When icons are rasterized, this is no longer possible and here angry users come to issues (#10239).

> Yes, technically I can replace cached icons with monochrome by modifying **every** cached icon with counter, but let's be realistic :)

WTF, what cache you referring to? tdesktop doesn't cache tray icon starting from 1.9.x. If you want to get the counter, all you need is to remove `telegram-{,attention,mute}-panel.png` from your icon theme.

**Comment by Shatur** [comment]
> KDE applies color scheme to svg icons. You can change the color of monochrome icons by chaning color scheme in KDE settings. 

Oh, got it. Never used this feature before. Thanks for the explanation. Yes, this is definitely should be an option.

> WTF, what cache are you referring to? tdesktop doesn't cache tray icon starting from 1.9.x.

Then it was like this before. In this case, it is impossible to get a monochrome icon with an indicator counter at all.

> If you want to get the counter, all you need is to remove telegram-{,attention-,mute-}panel.png from your icon theme.

Yes, I know, and I will have the default icon instead of ![изображение](https://user-images.githubusercontent.com/22453358/108477689-384d8080-729c-11eb-9a90-80cc54fd6a0e.png).
Maybe I will try to reintroduce this feature as an option and send a PR.

**Comment by ilya-fedin** [comment]
> Yes, I know, and I will have the default icon instead of ![изображение](https://user-images.githubusercontent.com/22453358/108477689-384d8080-729c-11eb-9a90-80cc54fd6a0e.png).

You can rename telegram-panel.png to telegram.png and remove the two others (`telegram-{attention,mute}-panel.png`)

**Comment by ilya-fedin** [comment]
> Maybe I will try to reintroduce this feature as an option and send a PR.

It's something weird to add the counter when icon already has a dot indicator, btw.

**Comment by ilya-fedin** [comment]
I would say it's more correct to make icons with counter from icon theme creators rather than creating an option that would restore this weird behavior.

**Comment by Shatur** [comment]
> You can rename telegram-panel.png to telegram.png and remove the two others (telegram-{attention,mute}-panel.png)

This is how it looks after the suggested changes:

![изображение](https://user-images.githubusercontent.com/22453358/124903705-e5772a00-dfec-11eb-9703-c3c1003b7341.png)

> It's something weird to add the counter when icon already has a dot indicator, btw.

But dot indicator is useless :) The notification counter was much better. And I'm not the only one, judging by the issues. Probably #10239 is the only issue, while we have many other issues about the current behavior.

> I would say it's more correct to make icons with counter for icon theme creators rather than creating an option that would restore this weird behavior.

I fully understand your position on adding this option. But how that can be achieved on the icon themes side?

**Comment by ilya-fedin** [comment]
> This is how it looks after the suggested changes:

are you sure you did it right, so that telegram.png contains the monochrome icon and none of `telegram-{,attention-,mute-}panel.png` exist?

> But dot indicator is useless :) The notification counter was much better.

None of icon theme creators had counter support on the time of adding icon theme support AFAIK.

> I fully understand your position on adding this option. But how that can be achieved on the icon themes side?

tdesktop can ask icons with count value in its name, e.g. `telegram-{attention,mute}-panel-{1-999}.png` and `telegram-{attention,mute}-panel-dotdot{1-99}.png`

**Comment by Shatur** [comment]
> Are you sure you did it right, so that telegram.png contains the monochrome icon and none of telegram-{,attention-,mute-}panel.png exist?

Yes. I use [papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icon theme. But the icons are in `.svg` format, is this important?

```
find . -name 'telegram.*'
./24x24/apps/telegram.svg
./24x24/panel/telegram.svg # <- Monochrome, was renamed from `telegram-panel`
./22x22/apps/telegram.svg
./22x22/panel/telegram.svg # <- Monochrome, was renamed from `telegram-panel`
./32x32/apps/telegram.svg
./64x64/apps/telegram.svg
./16x16/apps/telegram.svg
./16x16/panel/telegram.svg # <- Monochrome, was renamed from `telegram-panel`
```

> None of icon theme creators had counter support on the time of adding icon theme support AFAIK.
> tdesktop can ask icons with count value in its name, e.g. telegram-{attention,mute}-panel-{1-999}.png and telegram-{attention,mute}-panel-dotdot{1-99}.png

But would that require adding 999 new icons to the theme?

**Comment by Phi-Li** [comment]
OK, time to bring some temporary workaround for this issue.
For Archlinux users you need to rename/remove all Telegram icon files from package `breeze-icons`:
```
/usr/share/icons/breeze/apps/48/telegram.svg
/usr/share/icons/breeze/status/22/telegram-panel.svg
/usr/share/icons/breeze/status/22/telegram-attention-panel.svg
/usr/share/icons/breeze/status/22/telegram-mute-panel.svg
/usr/share/icons/breeze/status/24/telegram-panel.svg
/usr/share/icons/breeze/status/24/telegram-attention-panel.svg
/usr/share/icons/breeze/status/24/telegram-mute-panel.svg
/usr/share/icons/breeze-dark/apps/48/telegram.svg
/usr/share/icons/breeze-dark/status/22/telegram-panel.svg
/usr/share/icons/breeze-dark/status/22/telegram-attention-panel.svg
/usr/share/icons/breeze-dark/status/22/telegram-mute-panel.svg
/usr/share/icons/breeze-dark/status/24/telegram-panel.svg
/usr/share/icons/breeze-dark/status/24/telegram-attention-panel.svg
/usr/share/icons/breeze-dark/status/24/telegram-attention-panel.svg
```
Now I have the original tray icon for Archlinux-packed Telegram.
As a long-term user since early versions of Plasma, I'm used to modify theme files to revert their exciting changes in a new version.

**Comment by ilya-fedin** [comment]
> Yes. I use [papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icon theme. But the icons are in `.svg` format, is this important?

I guess KDE doesn't prefer `panel` over `apps ones, lol. I think you need to move them to `apps` folder and remove original ones in other sizes. But that will lead to app icon being monochrome...

> But would that require adding 999 new icons to the theme?

Yeah, unfortunately. Another solution would be to add tray protocol extension to set the count, so that the counter is drawn by panel. But I don't know who I need to talk to submit one.

**Comment by Shatur** [comment]
> I guess KDE doesn't prefer panel over apps ones, lol. I think you need to move them to apps folder and remove original ones in other sizes. But that will lead to app icon being monochrome...

Wow, this is weird :) But can be a temporary solution, thanks!

> Yeah, unfortunately.

Hm... The issue in rasterization, right?
What if we check the format of the icon and if it's SVG then modify it in place without a rasterization (just by adding text) to add an indicator counter?

**Comment by ilya-fedin** [comment]
It's a question though, how panel implementations will react to this. The API allows to pass raster bitmaps or icon name in icon theme, it doesn't allow to pass svg content. You can try to pass the path to svg icon in IconName field (that 100% works for png), but I'm not sure will this work or not. If not, this would reuqire creating an icon theme on runtime (e.g. creating a folder in ~/.local/share/icons, creating a index.theme file, creating subfolders, icon files, etc.)

**Comment by ilya-fedin** [comment]
> Now I have the original tray icon for Archlinux-packed Telegram.

tdesktop sets `setDesktopSettingsAware(false)` currently (for multiple last versions) as a workaround for qt plugin system/webkit2gtk conflict, but once gtk remoting will arrive at stable version, this workaround will be removed and tdesktop from distro builds will use KDE's platformtheme again and you will be affected to the KDE bug mentioned in the thread, so you will lose the counter.

**Comment by Phi-Li** [comment]
Not an expert in GUI dev. So in future KDE won't fallback to icon files Telegram provides even if themed icon files are removed? Or current implementation of counter on the tray icon won't work in future?

**Comment by ilya-fedin** [comment]
> Not an expert in GUI dev. So in future KDE won't fallback to icon files Telegram provides even if themed icon files are removed? Or current implementation of counter on the tray icon won't work in future?

Qt has a plugin system that allows DEs to inject their libraries to integrate applications. As was mentioned [here](https://github.com/telegramdesktop/tdesktop/issues/10407#issuecomment-782701915), KDE libraries have a bug that leads the check to always return true, so that the counter will be never added to the icon. Multiple latest versions have a workaround to avoid gtk have different backend (wayland/x11) and make window embedding work (for the bot payment feature). Once the workaround won't be needed, KDE will be able to inject libraries again and the KDE bug will affect tdesktop again when running on KDE.

**Comment by Shatur** [comment]
@ilya-fedin Yes, I would try ti implement, but probably it's a hacky solution... I think that the our first suggestion to add an option "Draw counter on themed icon" will be a better solution. Will you accept my PR if I implement it?

> Once the workaround won't be needed, KDE will be able to inject libraries again and the KDE bug will affect tdesktop again when running on KDE.

I do not know how it was before, but `QIcon::hasThemeIcon` works 100% correctly in my KDE environment. Maybe the issue was specific to KDE Neon or just was fixed by developers. So, there is nothing to worry about, @Phi-Li :)
In my message https://github.com/telegramdesktop/tdesktop/issues/10407#issuecomment-782694342 I meant that `QIcon::hasThemeIcon("telegram")` will always return true for my case because this icon is installed by the package. Sorry If I confuse you.

**Comment by ilya-fedin** [comment]
> Will you accept my PR if I implement it?

It's a question for @john-preston, I have no push access.

> I do not know how it was before, but `QIcon::hasThemeIcon` works 100% correctly in my KDE environment.

Try to invoke `QIcon::hasThemeIcon("telegram-panel")` when telegram.svg is present, but telegram-panel.svg is not.

**Comment by Shatur** [comment]
> Try to invoke QIcon::hasThemeIcon("telegram-panel") when telegram.svg is present, but telegram-panel.svg is not.

Returns `false` for me. Is this expected?

**Comment by ilya-fedin** [comment]
> Returns `false` for me. Is this expected?

Are you sure KDE injects its libraries? It returns true for me on KDE in that case and false on all other DEs.

**Comment by Shatur** [comment]
> Are you sure KDE injects its libraries? It returns true for me on KDE in that case and false on all other DEs.

How can I check this?
Do you have an older version of Qt / KDE? If you are using KDE Neon, this may be a distro issue. I use Qt5 5.15.2 and Plasma 5.22.3.

**Comment by ilya-fedin** [comment]
> How can I check this?

:thinking: with `QT_DEBUG_PLUGINS=1`

> Do you have an older version of Qt / KDE? If you are using KDE Neon, this may be a distro issue. I use Qt5 5.15.2 and Plasma 5.22.3.

I see the bugged place is still here:
https://github.com/KDE/kiconthemes/blob/783296891ba07bc5a78a498b9425571b391d21be/src/kiconengine.cpp#L110-L116

hasIconTheme constructs a QIcon and checks that its name is equal to what you requested, KIconEngine always returns the name that was requested instead of actual name (like Qt's built-in icon engine does).

**Comment by Shatur** [comment]
> thinking with QT_DEBUG_PLUGINS=1

Here is my log: [log.txt](https://github.com/telegramdesktop/tdesktop/files/6785397/log.txt)

> I see the bugged place is still here:

So `mIconLoader->hasIcon(mIconName)` is always returns `true` for you?

**Comment by ilya-fedin** [comment]
> So `mIconLoader->hasIcon(mIconName)` always returns `true` for you?

This has nothing to do with `mIconLoader->hasIcon(mIconName)`, it's `return mIconName`;

**Comment by ilya-fedin** [comment]
> Here is my log: [log.txt](https://github.com/telegramdesktop/tdesktop/files/6785397/log.txt)

either your distro patches the library or you don't have telegram.svg

**Comment by Shatur** [comment]
> either your distro patches the library or you don't have telegram.svg

Oh, sorry, I just called it **before** `QApplication`. Yes, `QIcon::hasThemeIcon("telegram-panel")` returns `true` because it fallbacks to `telegram`. And when I construct the icon it uses `telegram` icon but says that the name is `telegram-panel`.
How you expect it to work?

**Comment by ilya-fedin** [comment]
> How you expect it to work?

It should return false in that case, just like pure Qt does

**Comment by Shatur** [comment]
> QIcon::hasThemeIcon should return false in that case and QIcon::name should return actual name, just like pure Qt does

Got it, thanks. Even found a related [bug report](https://bugs.kde.org/show_bug.cgi?id=432293).

**Comment by Shelvak** [comment]
That's happening with a new gnome install with manjaro/arch.

telegram-desktop-3.1.0-1 (manjaro)
telegram-desktop-3.1.1-1 (Arch)
Gnome 40.4.0

Any workaround? :pray:

**Comment by soredake** [comment]
https://bugs.kde.org/show_bug.cgi?id=432293

**Comment by ilya-fedin** [comment]
I don't know why @Aokromes closed the issue, but there's no plan to implement this feature, sorry. We consider the current UX where the counter is displayed only in the taskbar icon good enough.

**Comment by soredake** [comment]
I'm *kinda* fine with notification counter in taskbar icon, but in kde, unlike in windows, counter does not have red background, will need to report this to kde, not sure which component is responsible for counter background color.

**Comment by ilya-fedin** [comment]
On Windows it's painted by tdesktop itself and is set with WinAPI as icon overlay, on Linux there's no such API, but there's API to send the counter and then the panel draws it. I guess it should follow your color-scheme in KDE.

**Comment by Shatur** [comment]
> but there's no plan to implement this feature, sorry. 

That's bad. It was much better before when we had a counter on icon.

**Comment by ilya-fedin** [comment]
Point raised by @john-preston in https://github.com/telegramdesktop/tdesktop/issues/10407#issuecomment-782693898 should still be valid, so it just needs someone interested to implement that (definitely not me as I like the current behavior and apparently not @john-preston).

**Comment by soredake** [comment]
Not stale.

**Comment by ilya-fedin** [comment]
I believe this should be closed as:
1. 1.5 years hapenned and no one contributed this, as not I nor @john-preston have plans to implement this, it seems this issue will just remain open forever like planned while it's not true. Anyone can contribute this even after the issue will be closed, though (I still can't guarantee the contirbution will be accepted, it's up to @john-preston, so the one who wants this would have to try and see what will happen).
2. It seems I misunderstood the request. I thought it's a request to disable the monochrome icon and use a colored icon with a counter. Re-reading the report, I see that it's a request to have the counter with a monochrome icon. Such options shouldn't exist in my opinion as it would provide bad UX, the option will bug as soon as the user will try to activate it while using Breeze Twilight theme, so we will get bug reports about this. To make this bug-less, one would have to integrate tdesktop with KDE frameworks providing color scheme integration and I don't believe anyone would spend effort on this. Another way for anyone interested is to contribute to Qt to either add KDE color scheme support (and tdesktop would have it automatically) or add abstraction for the OverlayIconPixmap API of the StatusNotifierItem specifications. The latter is way easier, Qt should have everything implemented, just lacks an API for tdesktop to use this. But the person who would like to implement this will have to convince Qt developers to add this new public API.

So I believe we should close this as a platform restriction. The [new tray icon spec](https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/84) that is in works doesn't have the possibility to set pixmaps, at all, so it's likely that in future we won't have the tray counter at all on Linux, only those monochrome icons with dots in vector format (it's unrealistic to have counter with the XDG icon theme spec as there would have to be thousands of icon files, for each count). Unfortunately, that's where the Linux stack goes, with the leadership of GNOME and its HIG.

Anyone can contribute an option to disable monochrome icon still, though, if that's something acceptable to anyone.
