### ISSUE TITLE
[Feature Request] Add to polls optional possibility to see the results without voting

### ISSUE THREAD

**Issue by MrHakimov** [telegramdesktop/tdesktop#10400]
## English 🇺🇸

Now it is possible to see the poll results only if user already voted, which isn't that good in cases where none of the poll's options are suitable to user, but he/she really wants to look at the results. This can of course be done by clicking on any option and then retracting the vote, but first, the percentages (albeit a little) will take into account the vote of the user who does not want it, and secondly, the results change from time to time and it is not very convenient for a very curious user to vote every time and then retract their vote.

One possible solution is to add an optional switch-button here along with `Anonymous voting`, `Multiple answers` and `Quiz mode` which if checked turns on the ability to see the results without voting if the poll is not in `Quiz mode`, for example.

![image](https://user-images.githubusercontent.com/29480849/108413441-16bcac80-723c-11eb-9e10-e354f3900405.png)

Another possible way to do that is adding "dummy" options to the poll such that it does not affect the percentages of other options. It can be option before `Add an option` button disabled by default, for example.

## Russian 🇷🇺

На данный момент результаты опросов в Telegram можно увидеть только в том случае, если пользователь уже проголосовал, что не очень хорошо в тех случаях, когда ни один из вариантов опроса не подходит пользователю, но он действительно хочет посмотреть на результаты. Это, конечно, можно сделать, нажав на любой вариант, а затем отозвав голос, но, во-первых, проценты (пусть и немного) будут учитывать голос пользователя, который этого не хочет, а во-вторых, результаты время от времени меняются, и очень любопытному пользователю не очень удобно каждый раз голосовать, а затем отзывать свой голос.

Одним из возможных решений является добавление дополнительной кнопки переключения (switch-button) здесь (см. картинку выше) вместе с `Anonymous voting`, `Multiple answers` и `Quiz mode`, который, если включен, добавляет возможность видеть результаты опроса без голосования, если опрос не находится в "режиме викторины", например.

Другой возможный способ сделать это-добавить "фиктивный" вариант в опрос таким образом, чтобы он не влиял на проценты других вариантов (классическая кнопка "тык", но умная, так как процентов за нее не начисляется). Например, это может быть опция перед кнопкой `Add an option`, отключенная по умолчанию.

**Comment by MasterGroosha** [comment]
This would completely destroy the purpose of voting, IMO. Anyway, that's API Issue, not TDesktop-related

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
