### ISSUE TITLE
Account migration [Feature Request] 

### ISSUE THREAD

**Issue by osysltd** [telegramdesktop/tdesktop#10410]
### Account migration
Account migration tool \process is required when changing accounts, avatar re-upload, First Name, Last Name, subscription migration, post-migration de-activation confirmation.

## Solution
Identity phone number migration tool to change the phone number but keep subscriptions and chats. Profile settings must be copied as well.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
