### ISSUE TITLE
[Feature Request] Rewind video by left/right arrow hotkeys 

### ISSUE THREAD

**Issue by AlexMercier** [telegramdesktop/tdesktop#10412]
### Is your feature request related to a problem?
Hello. I want to suggest improvements with video navigation.  
For now when I wath video  and when I press left/right arrow buttons on the keyboard ←, → then Telegram just switches between media attachments.  

### Describe the solution you'd like
I think that it will be more user friendly if you make the arrow buttons to fast forward and rewind the video.

### Additional context
Windows 10, Telegram Desktop version 2.5.9

**Comment by Aokromes** [comment]
those keys are already used.

**Comment by AlexMercier** [comment]
> those keys are already used.

Used for what? When I press this buttons on video, then it just switches to previous/next media in chat.

**Comment by john-preston** [comment]
@AlexMercier Exactly for that.

**Comment by AlexMercier** [comment]
Ok. so, it means that my suggestion to make this keys for rewind video was declined?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6606
