### ISSUE TITLE
desktop clinet version 2.5.8 routes output sound to wrong device

### ISSUE THREAD

**Issue by sergstesh** [telegramdesktop/tdesktop#10411]
First of all, I also have Skype installed, and I don't have this problem with Skype, so most likely it's not a pulseaudio problem.

My system:
```
uname -a
Linux sergei-dt 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
.
I have two audio devices - the built-in sound card and a USB headset with microphone. 

In Telegram desktop client in menu (Settings -> Advanced -> Call Settings)  I choose output device to be "USB PnP Sound Device Analog Stereo" and I choose microphone to be "USB Sound Device Analog Mono".

When I talk using the client, microphone works as expected, but output sound goes to built-in soundcard - not to "USB PnP Sound Device Analog Stereo". I know this because I have speakers connected to the built-in soundcard output, i.e. I hear sound from the speakers - not from the headphones of "USB PnP Sound Device Analog Stereo".

Since it's a Kubuntu system, I have 'pavucontrol-qt' application installed. If in the application I disable built-in soundcard - even on the fly, while talking, output sound goes to "USB PnP Sound Device Analog Stereo" as expected/desired. If I re-enable built-in soundcard, output sound again goes to built-in soundcard.

The desktop client was installed via 'flatpak' (if it makes any difference).

I do not have simultaneous audio output to several devices enabled at all. And, again, with Skype it works as expected.

**Comment by ilya-fedin** [comment]
#8435
