### ISSUE TITLE
[Question] How to increase VoiceChat quality on client side (desktop)?

### ISSUE THREAD

**Issue by johnybaker** [telegramdesktop/tdesktop#10414]
Hi, can you suggest where voice chat bitrate settings located please? I'm kinda tired of searching for it all over the repo. VoiceChat is an awesome feature and it works good with voice , but we really like to play music and use it as a little "radio" station in our group but as soon as music hits, sound quality drops to unpleasant levels. Thanks.

**Comment by johnybaker** [comment]
@john-preston pleaaaaase

**Comment by john-preston** [comment]
![image](https://user-images.githubusercontent.com/17900494/108705706-1ae01700-7527-11eb-8866-fbcd815ab45b.png)

**Comment by johnybaker** [comment]
@john-preston I already changed 32 to 96 in all that files (last one is commented tho) didn't helped me.

**Comment by Aokromes** [comment]
imho you must raise the 6

**Comment by johnybaker** [comment]
> imho you must raise the 6

That part is already commented in InstanceImplReference.cpp file

**Comment by john-preston** [comment]
I guess all the participants should have those new settings.

**Comment by johnybaker** [comment]
Tried that. Did not worked. Maybe something in libtgvoip needs to be twisted instead of tgcalls?

**Comment by c0re100** [comment]
As @john-preston said, if you're changing to higher bitrate, client should have those new setting, but official tdesktop min/max bitrate is 32kbps.
So another user can't hear the difference :)

**Comment by johnybaker** [comment]
@c0re100 I tried that, changed all 32kbps to 256kbps, and launched same recompiled client on both sides. Same thing :/, plus some echo/noise cancelation and volume control thingie kicks in while music starts playing and distorts sound.

**Comment by c0re100** [comment]
> @c0re100 I tried that, changed all 32kbps to 256kbps, and launched same recompiled client on both sides. Same thing :/, plus some echo/noise cancelation and volume control thingie kicks in while music starts playing and distorts sound.

You need to disable audio processing :)
https://github.com/TDesktop-x64/tgcalls/commit/ada549fe15bc3508e844a2683e79b5199777f49f#diff-81a7e0e8ef3ddad1470a08d41c2189240694ed40208455f624b80c989ca1bb72R1233

**Comment by johnybaker** [comment]
@c0re100 yeah that fixed it lol, thank you very much for helping me :) hope in future official TG client will have some sort of HQ switch for this

**Comment by johnybaker** [comment]
@c0re100 I will try to bother you for the last time... Is it possible to make it stereo instead of default mono?

**Comment by c0re100** [comment]
You need to change the SDP.
