### ISSUE TITLE
Cannot send PDF documents without compression

### ISSUE THREAD

**Issue by Ternvein** [telegramdesktop/tdesktop#10413]
### Steps to reproduce
1. Attach PDF document
2. Click Send
3. Make sure that PDF document was sent as picture with compression

### Expected behaviour
Either send PDF document as document, not as picture, or there should be a checkbox to send it without compression.

### Actual behaviour
PDF document always sent as picture with compression, no settings for this were found.

### Configuration
**Operating system:** ArchLinux

**Version of Telegram Desktop:** 2.5.9

**Installation source (Linux Only):** distribution package

**Used theme**: Night

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

Now PDF documents in Telegram are sent as pictures, not as documents. And even so, there is no opportunity to send it without compression, which renders these documents practically unreadable.

**Comment by ilya-fedin** [comment]
Is this still valid?
