### ISSUE TITLE
2.5.9 (win) lowers the sounds for all apps even with "Do nothing"

### ISSUE THREAD

**Issue by Zarezy** [telegramdesktop/tdesktop#10417]
Version 2.5.9 (win) lowers the sounds for all apps even with Sound/Communications "Do nothing" and for me it's not restoring the volume back after the call ends. I need to restart apps for them to get their volume back. It happens every time.

### Steps to reproduce
1. Receive or make a call using telegram.

### Expected behaviour
Volume of other apps should remain.

### Actual behaviour
Volume of other apps gets lowered significantly and not getting restored after call ends.

### Configuration
Windows 10 Pro 19042.746

**Version of Telegram Desktop:**
2.5.9

**Comment by john-preston** [comment]
@Zarezy I can't reproduce that :( Does it happen in group voice chats? Or only in one-on-one calls? Is the call made between tdesktop 2.5.9 and some old version of a Telegram app? Does it happen the same way in one-on-one video call?

**Comment by Zarezy** [comment]
>Does it happen in group voice chats? Or only in one-on-one calls
Never tried group voice chats.

>Is the call made between tdesktop 2.5.9 and some old version of a Telegram app?
Well it looks like it can be the issue. Just tried with updated version and it works correctly. But still I can't force other people to update their version.

Maybe this is why I have this weird issue with android version of telegram. After some time when I pick up the call it always in speaker mode,

**Comment by john-preston** [comment]
@Zarezy Sorry, old calls library is not maintained any more. I hope the apps will be updated sooner or later.

**Comment by ilya-fedin** [comment]
#8192
