### ISSUE TITLE
Telegram installed from flatpak quits after several seconds of idle

### ISSUE THREAD

**Issue by Aceler** [telegramdesktop/tdesktop#10418]
### Steps to reproduce
Install a flatpak version of Telegram (static binary works fine).
Launch it.
Close the window (keep running in the tray).

### Expected behaviour
Telegram should keep running in the tray, allowing to open it up, send notifications etc.

### Actual behaviour
Telegram silently quit after 30-40 seconds.

### Configuration
**Operating system:**
Ubuntu 20.04
**Version of Telegram Desktop:**
2.5.9
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Flatpak
**Used theme**:
Ubuntu default
<details><summary><b>Logs</b>:</summary>
I only got this in journalctl:
telegram-deskto[73730]: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATF>
telegram-deskto[73730]: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any>
telegram-deskto[73730]: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mi>
org.telegram.desktop.desktop[73730]: QSocketNotifier: Can only be used with threads started with QThread
org.telegram.desktop.desktop[73730]: error: : cannot open
org.telegram.desktop.desktop[73730]: error: : cannot open
org.telegram.desktop.desktop[73730]: error: : cannot open
systemd[2235]: flatpak-org.telegram.desktop-72549.scope: Succeeded.
</details>

**Comment by Aokromes** [comment]
you even have a tray installed?

**Comment by Aceler** [comment]
Yes, of course. I can see the tray icon and interact with it.

**Comment by ilya-fedin** [comment]
> Telegram silently quit after 30-40 seconds.

maybe it's a crash?

**Comment by Aceler** [comment]
Maybe. But I don't see anything in the logs. If you tell me, where can I find more logs, I can post them.

**Comment by Aokromes** [comment]
> Maybe. But I don't see anything in the logs. If you tell me, where can I find more logs, I can post them.

try to run telegram under gdb with gdb ./Telegram

**Comment by ilya-fedin** [comment]
> If you tell me, where can I find more logs, I can post them.

telegram log is at ~/.var/app/org.telegram.desktop/data/TelegramDesktop
You can get crash trace like described here: https://docs.flatpak.org/en/latest/debugging.html

**Comment by Wasiliy76** [comment]
Вт, 23 февр. 2021 г. в 04:09, ilya-fedin <notifications@github.com>:

**Comment by Aceler** [comment]
[log.txt](https://github.com/telegramdesktop/tdesktop/files/6028428/log.txt)

There was no crash, telegram-desktop just quit.

**Comment by Aceler** [comment]
[tg-gdb.log](https://github.com/telegramdesktop/tdesktop/files/6028498/tg-gdb.log)

**Comment by ilya-fedin** [comment]
> There was no crash, telegram-desktop just quit.

Maybe something from your system sends SIGTERM to tdesktop when it detects that it's running from flatpak?

**Comment by Aceler** [comment]
Wow, I don't think I got virus for Ubuntu that detects and stops Telegram :-)

Still, how can I trace that?

Maybe flatpak itself does not allow an app to run in the background?

**Comment by Aceler** [comment]
Seems like I've got this:

```
$ flatpak permissions
Table             Object              App                             Permissions           Data
gnome             shortcuts-inhibitor org.gnome.Boxes.desktop         GRANTED               []
background        background          com.skype.Client                yes                   0x00
background        background          eu.tiliado.Nuvola               yes                   0x00
background        background          eu.tiliado.NuvolaAppYandexMusic yes                   0x00
background        background          org.olivevideoeditor.Olive      yes                   0x00
background        background          org.telegram.desktop            no                    0x00

```

I said
```
flatpak permission-remove background background org.telegram.desktop
flatpak permission-set backgorund background org.telegram.desktop yes
```
…and now it is working fine. 

So, the problem was with flatpak manifest, please check if background compatibility is set.

**Comment by ilya-fedin** [comment]
> So, the problem was with flatpak manifest, please check if background compatibility is set.

What is background compatibility and how to set it?

**Comment by Aceler** [comment]
I suppose, flatpak package should ask flatpak package manager for permission to run in a background using some kind of manifest. There is a doc file about it: https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.portal.Background.xml#L34

I never meddled with permissions before, so it definitely wasn't me who restrict telegram from run in background. Or I did that by accident :-)

**Comment by ilya-fedin** [comment]
It's not related to manifest, you provided documentation for a dbus call that should be programmatically done by an application. IIRC tdesktop does it when you changing autostart settings inside tdesktop

**Comment by Aceler** [comment]
OK. The only question is, is it broken in the flatpak package or is that I accidentally broke it in my installation.

**Comment by ilya-fedin** [comment]
Probably it's you denied autostart once and flatpak saved that
