### ISSUE TITLE
Duplicate native notifications in Gnome

### ISSUE THREAD

**Issue by ilyachch** [telegramdesktop/tdesktop#10420]
### Steps to reproduce
1.Turn on Native notifications
2. Telegram app should not be in focus
2. Get notificaion

### Expected behaviour
Should be single notification according to notifications settins

### Actual behaviour
There are 2 notifications. One - as expected. The second - "Window "Telegram" is waiting"
![Снимок экрана от 2021-02-22 16-20-49](https://user-images.githubusercontent.com/1570221/108721102-487a8f80-752a-11eb-8c66-50eb23f1a45e.png)

### Configuration
**System Configuration:** Ubuntu 20.04.2 - Xorg

**Version of Telegram Desktop:** 2.5.9

**Installation source (Linux Only)** - snap

**Comment by ilya-fedin** [comment]
#8924
