### ISSUE TITLE
snap version does not use my subpixel rendering settings

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#10429]
Originally reported here https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1916342

### Steps to reproduce
1. Start telegram from snap
2. Fonts using grayscale rendering instead of my settings (rgb)
3. 
### Expected behaviour
Snap should import my font settings from ~/.config/fontconfig/fonts.conf and use rgb subpixel rendering
![rgb](https://user-images.githubusercontent.com/5204968/108842864-94890b00-75e2-11eb-8d0f-d3f61097a3aa.png)

### Actual behaviour
Telegram from snap uses default grayscale rendering, due to not importing user font settings.
![non-rgb](https://user-images.githubusercontent.com/5204968/108842879-9b178280-75e2-11eb-8f63-9f3d768c7bef.png)

### Configuration
**Operating system:** Kubuntu 20.10

**Version of Telegram Desktop:** 2.5.9

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Snap

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
> Snap should import my font settings from ~/.config/fontconfig/fonts.conf and use rgb subpixel rendering

tdesktop doesn't have anything special about font settings...

**Comment by ilya-fedin** [comment]
btw, I checked and found that snaps even can't read ~/.config/fontconfig/fonts.conf, snapd denies access to it (you can check it by accessing it with cat in `snap run --shell telegram-desktop`, specifying absolute path (not $HOME or ~, snapd overwrites it)). Looks like they misled you.

**Comment by soredake** [comment]
> 
> 
> > Snap should import my font settings from ~/.config/fontconfig/fonts.conf and use rgb subpixel rendering
> 
> tdesktop snap doesn't have anything special about font settings... Only standard snap scripts.

https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1916342/comments/3 https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1916342/comments/5

**Comment by ilya-fedin** [comment]
I don't want to implement font settings reading manually...

**Comment by soredake** [comment]
@john-preston

**Comment by ilya-fedin** [comment]
I would say this is ridiculous, making font settings reading to be manually implemented by snap developers. I don't imagine how each app will parse fontconfig files manually...

**Comment by soredake** [comment]
> 
> 
> I would say this is ridiculous, making font settings reading to be manually implemented by snap developers. I don't imagine how each app will parse fontconfig files manually...

Chromium in snap does this automatically, and i don't see any manual font settings loading in snapcraft file.

**Comment by ilya-fedin** [comment]
> Chromium in snap does this automatically

How does it do?

**Comment by ilya-fedin** [comment]
I'm afraid it is not related to fontconfig... gtk reads font settings from xsettings/gsettings rather than from fontconfig files, so chromium and other gtk applications will just work once you set font rendering settings in your DE (if it sets the settings for gtk).

**Comment by anonymouse64** [comment]
Can the telegram desktop be adapted to use one of the snapcraft extensions which provide this functionality automatically? see https://snapcraft.io/docs/snapcraft-extensions

**Comment by ilya-fedin** [comment]
> Can the telegram desktop be adapted to use one of the snapcraft extensions which provide this functionality automatically?

No, kde-neon extension is garbage. [Here](https://forum.snapcraft.io/t/qt-5-12-on-ubuntu-20-04-has-bugs-what-are-my-options/22260/8?u=ilya-fedin) I stated why.

**Comment by ilya-fedin** [comment]
@soredake will font style be right if you run Telegram with XDG_CURRENT_DESKTOP=GNOME?

**Comment by soredake** [comment]
> @soredake will font style be right if you run Telegram with XDG_CURRENT_DESKTOP=GNOME?

Yes, with "GNOME" rgb is applied to telegram fonts, but hinting is not.

snap with `XDG_CURRENT_DESKTOP=GNOME`
![snap](https://user-images.githubusercontent.com/5204968/109129382-434f5780-7759-11eb-87cb-c606c73fe87b.png)

flatpak with `--filesystem=xdg-config/fontconfig:ro`
![flatpak](https://user-images.githubusercontent.com/5204968/109129422-4f3b1980-7759-11eb-9285-708d5313d551.png)

**Comment by ilya-fedin** [comment]
> but hinting (i set it to medium, default is slight) is not.

`xrdb -query | grep Xft.hintstyle`

**Comment by ilya-fedin** [comment]
> Yes, with "GNOME" rgb is applied to telegram fonts, but hinting (i set it to medium, default is slight) is not.

btw, does chromium has the same problem?

**Comment by soredake** [comment]
> > but hinting (i set it to medium, default is slight) is not.
> 
> `xrdb -query | grep Xft.hintstyle`

Do i need to run it in snap or host system?

**Comment by ilya-fedin** [comment]
> Do i need to run it in snap or host system?

on host

**Comment by soredake** [comment]
> > Yes, with "GNOME" rgb is applied to telegram fonts, but hinting (i set it to medium, default is slight) is not.
> 
> btw, does chromium have the same problem?

Yes, same problem with snap version.

snap:
![snap_chromium](https://user-images.githubusercontent.com/5204968/109131715-b8bc2780-775b-11eb-8a78-5e6a4427bdea.png)

ppa:
![ppa_chromium](https://user-images.githubusercontent.com/5204968/109131779-c671ad00-775b-11eb-9004-089e41f78313.png)

**Comment by soredake** [comment]
> > Do i need to run it in snap or host system?
> 
> on host

![изображение](https://user-images.githubusercontent.com/5204968/109131840-d7222300-775b-11eb-92bb-f9bc7b6b1bf7.png)

**Comment by ilya-fedin** [comment]
> Yes, same problem with snap version.

So snap doesn't really supports fontconfig even with extension. Chromium works with rgba just because gtk reads settings from Xft (Qt does the same if `XDG_CURRENT_DESKTOP` is set to one of `GNOME`, `UNITY`, `XFCE`)

**Comment by ilya-fedin** [comment]
@Aokromes looks like you can close the issue, it's an issue with snap

**Comment by soredake** [comment]
@anonymouse64 can you reopen my launchpad issue? Because using extensions is clearly not an option.

**Comment by soredake** [comment]
> > Yes, same problem with snap version.
> 
> So snap doesn't really support fontconfig even with extensions. Chromium works with rgba just because gtk reads settings from Xft (Qt does the same if `XDG_CURRENT_DESKTOP` is set to one of `GNOME`, `UNITY`, `XFCE`) rather than from fontconfig.

Sad that it does not read `Xft.hintstyle`.

**Comment by ilya-fedin** [comment]
> Sad that it does not read `Xft.hintstyle`.

It reads, as I can see in Qt code. The difference might be due to another reason (e.g. the difference in freetype versions).

**Comment by ilya-fedin** [comment]
Or it could be due to some more fontconfig-specific settings like lcd filter

**Comment by soredake** [comment]
> > Yes, same problem with snap version.
> 
> So snap doesn't really support fontconfig even with extensions. Chromium works with rgba just because gtk reads settings from Xft (Qt does the same if `XDG_CURRENT_DESKTOP` is set to one of `GNOME`, `UNITY`, `XFCE`) rather than from fontconfig.

So, i've done `sudo cp ~/.config/fontconfig/fonts.conf /etc/fonts/local.conf`, reinstalled chromium in snap, and now font rendering is same, fonts hook is indeed working, it just does not read ~/.config/fontconfig/fonts.conf
