### ISSUE TITLE
Video avatars make my computer freeze

### ISSUE THREAD

**Issue by brookite** [telegramdesktop/tdesktop#10427]
Several versions of Telegram Desktop I am seeing the problem on my computer. When opening some channels, my computer completely freezes, it is impossible to move the cursor, the HDD lamp starts blinking on the system unit very often, I only had to abnormally power off the computer. Initially, I didn't understand why this was happening. But now I realized that this happens only with those channels that have a dynamic video avatar (profile video). 

My hardware is already considered obsolete, but I need Telegram Desktop
Windows 10 32 bit (exe installer)
2 GB RAM
It's problem actually on Telegram Desktop 2.5.9
Maybe, if the problem cannot be solved, add the ability to turn off the animation of avatars in Telegram Desktop?

**Comment by KittiKatty** [comment]
> Several versions of Telegram Desktop I am seeing the problem on my computer. When opening some channels, my computer completely freezes, it is impossible to move the cursor, the HDD lamp starts blinking on the system unit very often, I only had to abnormally power off the computer. Initially, I didn't understand why this was happening. But now I realized that this happens only with those channels that have a dynamic video avatar (profile video). 
> 
> My hardware is already considered obsolete, but I need Telegram Desktop
> Windows 10 32 bit (exe installer)
> 2 GB RAM
> It's problem actually on Telegram Desktop 2.5.9
> Maybe, if the problem cannot be solved, add the ability to turn off the animation of avatars in Telegram Desktop?

**Comment by brookite** [comment]
I have observed that the problem sometimes does not show up. Perhaps this happens on the channels of the video avatar, when there are more than 1 unread messages there

**Comment by Aokromes** [comment]
try downloading 2.8.6 beta to see if it works better, if no you can try disable hardware acceleration.

**Comment by brookite** [comment]
After a series of updates, I have not seen this problem again. I think this issue can be closed
