### ISSUE TITLE
Add Minimize To Tray button [Feature Request] 

### ISSUE THREAD

**Issue by r0ei** [telegramdesktop/tdesktop#10422]
### Is your feature request related to a problem?
Let's say I want to fully close telegram desktop. Right now I have to right click on the icon on my task bar and choose **Quit Telegram**. I don't want to do that everytime and I don't always want to do that, sometimes the icon doesn't even appear because I'm in fullscreen with an application.

### Describe the solution you'd like
One solution will be adding **Minimize to Tray** button which will be placed in the settings. When you set it to off, hitting X will make Telegram quit, and not make it just stay in the background. Just for example, Discard has that option, as you can see in the image below:

![Screenshot from 2021-02-22 17-34-16](https://user-images.githubusercontent.com/51533978/108730442-343b9000-7534-11eb-9461-a5d56c61f993.png)

**Comment by Aokromes** [comment]
you already can enable "show tray icon" (on some linuxes needs aditional software installed because no tray on them)

**Comment by r0ei** [comment]
> you already can enable "show tray icon" and it does what you want (on some linuxes needs aditional software installed because no tray on them)

I don't think it does what I want. **show tray icon** does not mean **close the application on X**. It is not closing telegram, afaik it is still running in the background but the icon doesn't shown. FYI: I use Ubuntu Gnome

**Comment by john-preston** [comment]
@r0ei You can press Ctrl+Q.

**Comment by ilya-fedin** [comment]
> It is not closing telegram, afaik it is still running in the background but the icon doesn't shown.

Well, it should close: https://github.com/telegramdesktop/tdesktop/blob/ca0be2c3ffae64f7b6426e93f70cfcab75bba4d4/Telegram/SourceFiles/window/main_window.cpp#L693

(git says this logic is there from the first commit)

**Comment by r0ei** [comment]
> > It is not closing telegram, afaik it is still running in the background but the icon doesn't shown.
> 
> Well, it should close:
> 
> https://github.com/telegramdesktop/tdesktop/blob/ca0be2c3ffae64f7b6426e93f70cfcab75bba4d4/Telegram/SourceFiles/window/main_window.cpp#L692-L693
> 
> (git says this logic is there from the first commit)

Oh, my bad. Yeah you have to disable the tray icon and leave the task bar icon. Thanks!
