### ISSUE TITLE
Fix - manual Download path

### ISSUE THREAD

**Issue by Redee** [telegramdesktop/tdesktop#1042]
No approve different folder to Downloads.
Telegram Desktop, last version, Windows XP sp3.

**Comment by auchri** [comment]
Works for me

**Comment by ppparadox** [comment]
False

**Comment by auchri** [comment]
Anyone can confirm this?

**Comment by Redee** [comment]
For understanding - I choose path but its only open - not approve.

**Comment by telegramdesktop** [comment]
@Redee I don't understand you. What does it mean "only open - not approve"?

**Comment by saeedhn** [comment]
Same problem with custom download path in Windows XP SP3....
When I choose custom download path to change it opens a window which should have "Select Folder" key and actually have it in other Windows Versions (such as Windows 8 on my laptop) but on my PC with XP SP3 it's "Open File"!!!

**Comment by Aokromes** [comment]
Confirmed, if i select a folder for download target it is open, i cannot assign the folder.

**Comment by auchri** [comment]
Still unable to reproduce:

![dasd](https://cloud.githubusercontent.com/assets/5092164/20099612/ad5bc7f6-a5b9-11e6-84d0-0f72bfba93d4.gif)

**Comment by john-preston** [comment]
@auchri Looks like it is WinXP only. Do you try WinXP?

**Comment by auchri** [comment]
@john-preston No, I tried it on Windows 10.

Since WIndows XP is really outdated, we should maybe drop official support for it.

**Comment by Aokromes** [comment]
Yes, window xp only :)

**Comment by mvilkin** [comment]
@john-preston Checked on Windows XP. It uses a dialog with "Open" button, but the path changes and all works fine.

**Comment by john-preston** [comment]
@mvilkin It was fixed in cce99a96ac09dd4df0b38149ad624ffdaf9f4090 indeed.
