### ISSUE TITLE
Add support named pipe

### ISSUE THREAD

**Issue by SGmuwa** [telegramdesktop/tdesktop#10423]
### Is your feature request related to a problem?

I can't upload files via a named pipe. For reproducing in Ubuntu:

```bash
mkfifo example.txt # Create named pipe
while true; do # Use while true because my file manager read this file before telegram.
    echo 123 > example.txt # Send data to pipe
done
```

When I try put the file in Telegram Desktop, it shows error about zero length of `example.txt`. Also, when I create a pipe in advance and try to download a file, Telegram Desktop saves the file in a scattered order.

### Describe the solution you'd like
I would like Telegram Desktop to be able to work with named pipes.

I expect Telegram Desktop to send file `example.txt` with content `123\n`

### Describe alternatives you've considered
Nothing prevents me from using physical media, I have enough storage space. I generated a file in advance, saved it to disk, and sent it to Telegram.

### Additional context
I don't think it really makes sense to implement this. I have not tested it, but probably there are, for example, **telethon** or **telegram-cli** as alternative solutions

**Comment by ilya-fedin** [comment]
I don't think anyone will implement this... You should contribute this by your own if you really need this most likely.

**Comment by mymedia2** [comment]
@ilya-fedin your remark is pretty rough. Do not tell others what they should do. If you have nothing to say, it is better to keep silent and go past.

**Comment by nuclight** [comment]
This is not possible due to protocol limitation. The [documentation](https://core.telegram.org/api/files) says:

> `upload.saveBigFilePart#de7b673d file_id:long file_part:int `**file_total_parts**`:int bytes:bytes = Bool;`
>
> Use upload.saveBigFilePart in case the full size of the file is more than 10 MB and upload.saveFilePart for smaller files.

Thus you need to know file size in advance to use proper method and tell server it's size.

**Comment by SGmuwa** [comment]
> I don't think anyone will implement this... You should contribute this by your own if you really need this most likely.

Yes, I think so too.  I do not promise that I will implement it, but maybe I will do it for fun.

> Thus you need to know file size in advance to use proper method and tell server it's size.

Thank you, it probably really can't be done for reading in one pass.  It is then worth notifying the user that the named pipe will be opened twice due to the peculiarities of the Telegram API.

**Comment by nuclight** [comment]
What? Twice - for _pipe_? This is either a trolling or wild incompetence.

**Comment by SGmuwa** [comment]
> What? Twice - for _pipe_? This is either a trolling or wild incompetence.

I agree with you, asking the user to send information to the pipe twice is a crutch.  However, I have no normal ideas. Here are the ways to solve the problem:

* Ask user send information twice. (Bad because user must generate a equal information twice)
* Create file-buffer in RAM or in a disk. (Bad, as memory may not be enough)
* Create a secret channel and send information in chunks. (Bad because other devices will see this channel, Internet traffic usage is three time more, too complex logic and something may break)
* Ask user for size (and hash?) before uploading. (Bad because it is not comfortable)

Perhaps if I sit down to implement this, I can implement all 4 methods and I can add a switch to the settings.

**Comment by ilya-fedin** [comment]
> and I can add a switch to the settings

https://github.com/telegramdesktop/tdesktop/blob/dev/.github/CONTRIBUTING.md#what-contributions-are-accepted

**Comment by SGmuwa** [comment]
> https://github.com/telegramdesktop/tdesktop/blob/dev/.github/CONTRIBUTING.md#what-contributions-are-accepted

Thank you, really, this setting is too specialized. I do not know if Telegram Desktop currently has a storage with hidden parameters, for example, in the file system, but if so, then it would be possible to hide this setting there.

**Comment by SGmuwa** [comment]
> https://github.com/telegramdesktop/tdesktop/blob/dev/.github/CONTRIBUTING.md#what-contributions-are-accepted

I'm not sure if I create a pull request it will be a bug fix or feature creation.  If the first, then everything is ok, if the second, then the pull request will be rejected

**Comment by SGmuwa** [comment]
> > https://github.com/telegramdesktop/tdesktop/blob/dev/.github/CONTRIBUTING.md#what-contributions-are-accepted
> 
> I'm not sure if I create a pull request it will be a bug fix or feature creation. If the first, then everything is ok, if the second, then the pull request will be rejected

Извините за мой плохой английский, но тут сказано, что нельзя вводить новые фичи или нельзя вводить новые фичи в пользовательский интерфейс?

Sorry for my bad English, but does it say that I am not allowed to add new features or I am not allowed to add new features to the user interface?

**Comment by ilya-fedin** [comment]
Обычно престон принимает PR'ы, если это какая-нибудь платформоспецифичная фича, которая не требует ничего в UI. А если это какая-нибудь видимая фича, которая добавляет что-то, чего нет в остальных клиентах, то нет.07.03.2021, 08:17, "SGmuwa" <notifications@github.com>:


https://github.com/telegramdesktop/tdesktop/blob/dev/.github/CONTRIBUTING.md#what-contributions-are-accepted

I'm not sure if I create a pull request it will be a bug fix or feature creation. If the first, then everything is ok, if the second, then the pull request will be rejected

Извините за мой плохой английский, но тут сказано, что нельзя вводить новые фичи или нельзя вводить новые фичи в пользовательский интерфейс?
Sorry for my bad English, but does it say that I am not allowed to add new features or I am not allowed to add new features to the user interface?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- С уважением,Илья Федин
