### ISSUE TITLE
self-closing app on windows

### ISSUE THREAD

**Issue by pironmind** [telegramdesktop/tdesktop#10438]
### Steps to reproduce
1. Open telegram
2. Try to resend message or just typing
3. App closing 

### Expected behaviour
Tell us what should happen

it should work...

### Actual behaviour
Tell us what happens instead

it closing

### Configuration
**Operating system:**

W10, v 20H2

**Version of Telegram Desktop:**

2.6.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

-

**Used theme**:

black

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

-

**Comment by Aokromes** [comment]
plz post crash id here on next restart.

**Comment by pironmind** [comment]
> plz post crash id here on next restart.

No logs, closing without crash popup

**Comment by Ryder17z** [comment]
Probably a due to an issue with the cache.
