### ISSUE TITLE
Can not close Telegram if it opened on another workspace

### ISSUE THREAD

**Issue by GDGooD** [telegramdesktop/tdesktop#10431]
1. Open Telegram Desktop
2. Switch to another workspace
3. Can not close and open window from tray

### Expected behaviour
Tray shows option for closing a window, so it is possible to reopen a window on active workspace 

### Actual behaviour
"Close Telegram" button is missed after a new update, it is need to find a window between workspaces.

### Configuration
Ubuntu MATE 18.04

https://ubuntu-mate.org/ - the official website / GitHub releases / flatpak / snap / distribution package.

Telegram Desktop 2.6

**Comment by ilya-fedin** [comment]
If Telegram is focused, it shows "Minimize to Tray", "Open Telegram" otherwise.
