### ISSUE TITLE
[Feature Request]  Select webcam in video-call

### ISSUE THREAD

**Issue by AiratHalitov** [telegramdesktop/tdesktop#10434]
### Is your feature request related to a problem?
I can't select webcam on my laptop. I have two webcams (integrated and USB). 

### Describe the solution you'd like
It should be possible to select a webcam in the application settings.
The same issue with mic selecting.

### Describe alternatives you've considered
You can see how it is working in skype settings. 

v2.6

**Comment by Aokromes** [comment]
it's under calls -> 3 dots -> calls settings.

**Comment by AiratHalitov** [comment]
@Aokromes 
Could you show me a screenshot?

**Comment by Aokromes** [comment]
i don't have webcam.

**Comment by AiratHalitov** [comment]
>  it's under calls -> 3 dots -> calls settings.

There is no 3 dots anywhere

**Comment by Aokromes** [comment]
https://i.imgur.com/l1tzdYX.png

**Comment by AiratHalitov** [comment]
> https://i.imgur.com/l1tzdYX.png
where is it? 
Could you give some more information?

**Comment by AiratHalitov** [comment]
> https://i.imgur.com/l1tzdYX.png

I found it. Thanks!
