### ISSUE TITLE
Segmentation Fault on canceling "Create a new link"

### ISSUE THREAD

**Issue by jkmpariab** [telegramdesktop/tdesktop#10432]
### Steps to reproduce
1.  click ... > Manage Group/Channel > Invite Links
2. click CANCEL button

### Expected behaviour
Cancel add a new link without carashing (segfault)

### Actual behaviour
Seg Fault

### Configuration
**Operating system:**
Ubuntu 20.04 amd64

**Version of Telegram Desktop:**
v 2.6.0

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Offical website and auto updated  deb version

**Used theme**:
Tinted

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by gleb-chipiga** [comment]
Same error on  Ubuntu 18.04 amd64.

**Comment by Aokromes** [comment]
plz post crash id or gdb crashlog.
