### ISSUE TITLE
Voice recording button disappears.

### ISSUE THREAD

**Issue by Chishala-Mukuka** [telegramdesktop/tdesktop#10436]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen
After opening a telegram instance on pc,  a voice recording button is default,  the send button is only active if there is user input in the textbox and returns to default voice recording if input is deleted.
### Actual behaviour
Tell us what happens instead
A default voice recording button is been replaced with a send button without having written any text or clicked in the textbox. 
### Configuration
**Operating system:**
Windows 10 20H
**Version of Telegram Desktop:**
v2.5.7 ,v2.5.9, v2.6.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Dark
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
It's disappears when the client can't find microphone on start. Ensure you have connected the mircophone and restart the application.
