### ISSUE TITLE
Telegram for use in Broadcasting

### ISSUE THREAD

**Issue by SistemasRTRM** [telegramdesktop/tdesktop#10442]
Hi there! 

**Introduction:**
We're a radio station. Since the pandemic increasingly we have to put on air more and more phone call contributions since people are not allowed to come in person to our venues. Traditionally this calls we're GSM but now everybody is demanding Telegram voice calls. We're trying to setup a stable system to do this because is easy for people to use this kind of apps (and gaining sound quality obviously).

**The setup:**
To do this we use Telegram Desktop (Windows 10) and the computer input sound (wich would be the microphone) comes from a sound mixer and the sound that goes to the mixer comes from Windows default sound card (the speakers).

**The problem:**
If the "microphone" part is quiet (the mixer isn't sending sound to the computer) everything goes fine. But if one end tries to speak while the other end is producing sound (i.e background music, another person speaking at the same time) the sound drops.

Put in another way, let's call studio presenter A and the interviewed person B. If B is speaking and A isn't producing any sound everything is fine. In the moment A starts to speak (this could be a background music, or other person in the studio speaking at the same time) B sound starts to drop. We've observed that if we lower A's sound to a minumum B sound doesn't drop, but it's too quiet for B to listen anything at the studio. 

It's like something is kicking in in the moment A starts to speak at the same time that B does. Just to clarify, the signal the sound mixer sends to the computer with Telegram Desktop is a cleanfeed, this means it is not sending B's signal back to B so it doesn't feedbak o have a delayed self-reception.

Any clue? Thanks!

**Comment by Trainax** [comment]
**Mine is just a supposition** (so I could be wrong, do this under your own resposability).

I would suggest you to go into Windows control panel, then click on the Audio option. On the window which opens select the "Communications" tab and set the radio button to "Don't intervene", then click "Apply" and "Ok". Try if this solves the issue
