### ISSUE TITLE
[Question] Restore cleared chats from cache?

### ISSUE THREAD

**Issue by jeffythedragonslayer** [telegramdesktop/tdesktop#10445]
Once in a blue moon, I notice that my chat history from certain individuals will be inexplicably cleared.  Can I still find these chats in the cache on desktop somewhere?  Ideally lookup by telegram id or name.

**Comment by john-preston** [comment]
@jeffythedragonslayer No, tdesktop doesn't store chats / messages in cache.

**Comment by KittiKatty** [comment]
> Once in a blue moon, I notice that my chat history from certain individuals will be inexplicably cleared.  Can I still find these chats in the cache on desktop somewhere?  Ideally lookup by telegram id or name.
