### ISSUE TITLE
Some problem with UI

### ISSUE THREAD

**Issue by lawbr3aker** [telegramdesktop/tdesktop#10449]
### Problems:
+ Can't scroll chats
      Instead window resizing horizontally!
+ Automatic focus,
      When I'm on another windows, the telegram itself popup!
#### Note:
Sometimes it works properly!

**Comment by mcchan1** [comment]
Same. Please add a vertical scroll bar for desktop - MacOS. I can use the arrow keys, but it is not the same.

**Comment by fidojones** [comment]
Same problem here, telegram desktop 2.6.1 and manjaro, the window take the focus itself, it's anoying

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7885#issuecomment-628268069
