### ISSUE TITLE
Does not display fonts correctly

### ISSUE THREAD

**Issue by 4AmiR4** [telegramdesktop/tdesktop#10444]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Does not display the fonts used for the text correctly
Shows only a few rectangles
please help
I really need
Please tell me how to solve this problem**
### Configuration
**Operating system:**

**Windows 8.1 Pro**

**Version of Telegram Desktop:**

**Version 2.6.1
![warning](https://user-images.githubusercontent.com/79722008/109356054-6d0d9900-7895-11eb-8a70-e50e69386032.png)
![warning](https://user-images.githubusercontent.com/79722008/109356104-7dbe0f00-7895-11eb-8fd4-580b0f228e3b.png)
![warning](https://user-images.githubusercontent.com/79722008/109356122-86164a00-7895-11eb-980f-2cfd96df94c8.png)

**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#6056

**Comment by 4AmiR4** [comment]
> [# 6056](https://github.com/telegramdesktop/tdesktop/issues/6056)

**What?????!**

**Comment by ilya-fedin** [comment]
@4AmiR4 your issue is a duplicate
