### ISSUE TITLE
Window Manager focus settings are not respected after 2.6.1

### ISSUE THREAD

**Issue by Edu4rdSHL** [telegramdesktop/tdesktop#10441]
### Steps to reproduce
1. Configure your window manager to switch to window's workspace when a window raises itself.
2. Open Telegram
3. Switch to another workspace
4. Click the tray icon or app icon

### Expected behaviour
The focus is switched to the window's workspace.

### Actual behaviour
The window is bring to the current workspace

### Configuration
**Operating system:** ArchLinux

**Version of Telegram Desktop:** 2.6.1

**Installation source (Linux Only)** - ArchLinux package but happens with the official version too.

**Used theme**: night

### Additional info

**Window manager settings**

![image](https://user-images.githubusercontent.com/32582878/109331143-7b729b00-782a-11eb-8c12-64524c101443.png)

The bug was introduced in https://github.com/telegramdesktop/tdesktop/commit/f9bba753952e110ae388126704b7f664be2ce1ad

**Comment by Edu4rdSHL** [comment]
The problematic code is
```c
if (Platform::IsX11()) {
		base::Platform::ActivateThisProcessWindow(winId());
	}
``` 
also the "issue" that tried to fix doesn't exists, when you are in another workspace it shows the "Open Telegram", "Disable notifications" and **"Quit Telegram"** options in the tray icon (tested in 2.6.0).

**Comment by ilya-fedin** [comment]
> also the "issue" that tried to fix doesn't exists, when you are in another workspace it shows the "Open Telegram", "Disable notifications" and **"Quit Telegram"** options in the tray icon (tested in 2.6.0).

I personally checked on MATE and confirmed that "Open Telegram" did nothing previously if the window is on another workspace.

**Comment by Edu4rdSHL** [comment]
Then it's a problem with MATE managing the focus incorrectly. Works fine in XFCE, Gnome and KDE.

**Comment by ilya-fedin** [comment]
> Works fine in XFCE, Gnome and KDE.

I see someone also reported this on XFCE in the past
https://github.com/telegramdesktop/tdesktop/issues/7402

**Comment by Edu4rdSHL** [comment]
I would love if you can test yourself the issue, it's a problem with the recent change, all other apps are respecting the window manager focus setting and also the issue you mention is caused by a wrong configuration of the window manager in XFCE. By default, windows are bring to current workspace when they raises itself but you can change it to "Switch to windows workspace" and that's managed by the window manager itself. Actually the window isn't raised but forced to open in the current workspace, causing the problem.

**Comment by ilya-fedin** [comment]
> all other apps are respecting the window manager focus setting and also the issue you mention is caused by a wrong configuration of the window manager in XFCE

This won't help users on MATE/XFCE even if this issue is really on their side. IMHO breaking user settings of some WMs is better than have a broken core feature on another WMs.

**Comment by Edu4rdSHL** [comment]
> > all other apps are respecting the window manager focus setting and also the issue you mention is caused by a wrong configuration of the window manager in XFCE
> 
> This won't help users on MATE/XFCE even if this issue is really on their side. IMHO breaking user settings of some WMs is better than having a broken core feature on another WMs.

It's not about user settings, it's about the focus standard that was broken in that commit and make impossible to use the desktop app as it keeps interfering with your workflow but if you think that this behavior (forcing the window to bring to the current workspace and steal the focus) is correct then feel free to close the issue.

**Comment by ilya-fedin** [comment]
Yeah, i think it's correct, but I don't have right to close issues, maybe @Aokromes can

**Comment by Edu4rdSHL** [comment]
Ok, thank you for broken the beahvior in all DEs for fixing a broken one.

**Comment by AlynxZhou** [comment]
Thanks every one for your reverting this commit, today my workflow was totally destroyed because telegram jumps to my every workspaces instead of the one I choose.

**Comment by AdamantGarth** [comment]
> > Works fine in XFCE, Gnome and KDE.
> 
> I see someone also reported this on XFCE in the past
> #7402

Yeah, Xfce has had this setting for a long time but it didn't work for me until latest Xfce major release. Now it finally works like in GNOME and Plasma. And maybe Cinnamon too, don't quite remember. From what I know, no other DE or window manager focuses windows that request activation from another workspace. Although i3 and awesome window managers can be configured to behave correctly.

So yeah, I'm also glad the commit was reverted - this is window manager's task, applications shouldn't try to handle it. I'd recommend the author of #10431, @GDGooD, to report that issue [upstream](https://github.com/mate-desktop/marco/issues).

**Comment by ilya-fedin** [comment]
Fair enough

**Comment by ilyachch** [comment]
Same problem for gnome 3.38.4 - telegram windows switches its own workspace to current
All other notifications are working as expected.

**Comment by atahabaki** [comment]
I've similar problem. I configured i3wm to move the Telegram Workspace, howsoever when I click the notification, Telegram Desktop appears at the top, it's a bit annoying.
