### ISSUE TITLE
Application crashes when opening context menu in textbox

### ISSUE THREAD

**Issue by asorel1942** [telegramdesktop/tdesktop#10454]
### Steps to reproduce
1. Type text into textbox
2. (optional) Highlight word in textbox
3. Right click on word in textbox

### Expected behaviour
Select items on context menu to apply to text, e.g. formatting, spellcheck

### Actual behaviour
Application briefly freezes, then crashes

### Configuration
**Operating system:**
Manjaro Linux KDE 64-bit
**Version of Telegram Desktop:**
2.6
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official Repositories (community)
**Used theme**:
Tinted
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
X or Wayland? Can you check if the issue is present on official binary?

**Comment by asorel1942** [comment]
My system is using X11. However, I'm fairly certain I have the official repository installed; is this not the official package?

![image](https://user-images.githubusercontent.com/33983895/109699781-fd323380-7b5e-11eb-9f81-c65221dfd709.png)

**Comment by ilya-fedin** [comment]
Probably it's an issue with Qt manjaro maintainers built tdesktop with, we can't fix third-party packaged

**Comment by asorel1942** [comment]
If I had to guess, it would seem that the reason for the change is the official executable being 2.6.1, and the version found in the Manjaro Official Repositories being 2.6.0-1.

**Comment by ilya-fedin** [comment]
And... what? :thinking: Could the issue be closed?
