### ISSUE TITLE
Add support for "Shuffle All" and "Repeat All" in playlist

### ISSUE THREAD

**Issue by unintended** [telegramdesktop/tdesktop#1045]
![image](https://cloud.githubusercontent.com/assets/641973/9606324/68095ee6-50cb-11e5-9880-afc4a2c5048a.png)

**Comment by 1997alireza** [comment]
there isn't this item in my telegram
![screenshot from 2017-06-02 01-40-38](https://cloud.githubusercontent.com/assets/16881497/26701089/0b61ec8c-4735-11e7-975d-9dfa1aee5945.png)

**Comment by ctliang** [comment]
Hi there,

I'd also would like to vote for this enhancement. 👍 

Hope we can get more people backing this, so it will get implemented soon!

Cheers,

**Comment by rdlmda** [comment]
#4561 was closed because it was linked here, but there's no mention to it here and... I'd *really* love the reverse ability, I don't care much about the rest. Telegram for Android has reverse playlist and I'd really like it on the desktop.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4640

**Comment by IlyaMrz** [comment]
year 2020 no shuffle play in desktop.... great

**Comment by RememberTheAir** [comment]
@IlyaMrz you say this like tdesktop was a music player app. It's not, it's a messaging app which happens to offer a built-in music player. Probably these stuff is a bit more complex to implement in a cloud-based app which playing queue is based on chunks of chat history pulled from the server - so they probably decided it's a low priority task

**Comment by y9san9** [comment]
@RememberTheAir by the way android app is not music app too.

**Comment by y9san9** [comment]
for it's very important feature and is not too hard to implement. I have to turn on music from phone, but I'm using phone rarely and it's not convenient for me

**Comment by aminjoharinia** [comment]
please add this option
