### ISSUE TITLE
Empty field with the name and filename extension

### ISSUE THREAD

**Issue by ivanmood0** [telegramdesktop/tdesktop#10453]
When saving a file (image, audio, document, etc.) an empty field with the name and filename extension.

Installation source: Snapcraft (snap package)
Version: 2.6.1
Distro: Ubuntu 20.04
![teleg_bug](https://user-images.githubusercontent.com/79835684/109539754-5a2fda00-7aca-11eb-8fde-c98be9446fd0.png)

**Comment by ilya-fedin** [comment]
Probably some incompatibility between qt and gtk and couldn't be solved at tdesktop level?

**Comment by ivanmood0** [comment]
> Probably some incompatibility between qt and gtk and couldn't be solved at tdesktop level?

The deb version of the package works ok (collected from the official website). I read about a similar problem with the flatpak version on Linux Mint. The problem arose about a month ago (I can't say the exact version on which this problem appeared), before that the snap version worked without any complaints.

**Comment by ilya-fedin** [comment]
> The deb version of the package works ok (collected from the official website).

But there's no deb on official website...

> I read about a similar problem with the flatpak version on Linux Mint.

Yeah, Qt uses xdg-desktop-portal to open file dialogs in confined environments since it's the only right way to do this in confined environments. I checked the snap on KDE Neon and found that this bug doesn't happen for me, that's why I assume that Qt doesn't know how to set this hint for xdg-desktop-portal-gtk (since it works with xdg-desktop-portal-kde). I don't think we really can something about that.

> The problem arose about a month ago (I can't say the exact version on which this problem appeared), before that the snap version worked without any complaints.

Well, snapd switched to portals not so long ago, but there's nothing we can do about that, again.

**Comment by ivanmood0** [comment]
> > The deb version of the package works ok (collected from the official website).
> 
> But there's no deb on official website...
> 
> > I read about a similar problem with the flatpak version on Linux Mint.
> 
> Yeah, Qt uses xdg-desktop-portal to open file dialogs in confined environments since it's the only right way to do this in confined environments. I checked the snap on KDE Neon and found that this bug doesn't happen for me, that's why I assume that Qt doesn't know how to set this hint for xdg-desktop-portal-gtk (since it works with xdg-desktop-portal-kde). I don't think we really can do something about that.
> 
> > The problem arose about a month ago (I can't say the exact version on which this problem appeared), before that the snap version worked without any complaints.
> 
> Well, snapd switched to portals not so long ago, but there's nothing we can do about that, again.

On the official website in general there is none installation package (be it snap, flat, deb or rpm) only compressed .tar archive. It was meant that when unpacking a .tar archive, as well as when installing a deb package (created on the basis of a .tar archive), such a problem does not arise. The problem arose in the snap version, which previously worked without any complaints, that is, initially the snap version worked correctly, something broke in the latest updates.

**Comment by ilya-fedin** [comment]
Have you read my explanation about the portals? I already answered you why it behaves differently.

**Comment by ivanmood0** [comment]
> Have you read my explanation about the portals? I already answered you why it behaves differently. And we can't do nothing about that, the bug is in Qt or in xdg-desktpo-portal-gtk.

In your opinion, the official version does not use xdg-desktop-portal-gtk? Or Qt she does not use? Your explanation is absurd. If the unpacked and installed version of .tar or the compiled version of .deb had this problem, it could be assumed that the problem is common to GTK environments. And yes, this is some kind of bullshit, not an explanation.

**Comment by ilya-fedin** [comment]
> In your opinion, the official version does not use xdg-desktop-portal-gtk? Or Qt she does not use?

Yeah, Qt uses portals only in confined environments: https://github.com/qt/qtbase/blob/5.15/src/gui/kernel/qguiapplication.cpp#L264

> Your explanation is absurd.

You just don't understand that when applications are confined, they reach different code paths...

> And yes, this is some kind of bullshit, not an explanation.

You may not believe it, but it works this way. When Qt apps are not confined, they are using gtk directly. When they are, they using xdg-desktop-portal and portal dialog implementation can have its own bugs, there a plenty of incompatibility between the KDE and the GTK portal backends and looks like Qt implements only KDE backend compatible hints.

If you still don't believe, you can install Kubuntu/KDE Neon in virtual environment, install tdesktop from snap and see that file name fills as it should (that's what I see).

**Comment by ilya-fedin** [comment]
https://github.com/flatpak/xdg-desktop-portal-gtk/issues/191
