### ISSUE TITLE
Window freezes when scrolling and moving actively (KDE)

### ISSUE THREAD

**Issue by NiroxSDV** [telegramdesktop/tdesktop#10466]
### Steps to reproduce
1. Check on Kubuntu 20.04, KDE Neon 5.21.0-5.21.2
2. Make NOT full screen for app 
3. Grab the window and move it around the screen.
4. Release the window and scroll through the history in the chat or group, where there are many messages.
5. One more time grab the window and move it around the screen.
6. repeat 4 and 5
7. 100% you get a hung window. But! The system is not frozen, but does not respond to mouse clicks.
8. Press Alt and all start working again. 

### Configuration
**Operating system:**
Operating System: KDE neon 5.21
KDE Plasma Version: 5.21.2
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.4.0-66-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-6600U CPU @ 2.60GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 520

**Version of Telegram Desktop:**
2.6.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
1. KDE Discover - Telegram (Flatpak)
2. Telegram from https://telegram.org/dl/desktop/linux/tsetup.2.6.1.tar.xz
_The result is the same. It is repeated in 100% of cases, on different versions of KDE and systems._ 

**Used theme**:
KDE Breeze Dark, in Telegram Night Mode

**Comment by ilya-fedin** [comment]
> 7. The system is not frozen, but does not respond to mouse clicks.

Sounds like a KDE bug. I don't imagine how tdesktop can do this.

**Comment by NiroxSDV** [comment]
Maybe you are right. In linux MINT all working fine. But I’m and my friend see this only with Telegram :(

**Comment by ilya-fedin** [comment]
Probably it's worth to report to KDE folks, they should know better why this is hapenning, I have no idea...

**Comment by NiroxSDV** [comment]
Sure, thanks. I will do this.
