### ISSUE TITLE
[BUG] Window loses state 'pin to all workspaces' in Plasma 5

### ISSUE THREAD

**Issue by qmmp123** [telegramdesktop/tdesktop#10461]
### Steps to reproduce
1. Open Telegram (with local passcode)
2. Enter passcode
3. Pin window to all workspaces
4. Wait new notification
5. Click notification to show telegram

### Expected behaviour
I think window should be pinned until user unpin it by himself

### Actual behaviour
Window loses pinstate

### Configuration
**Operating system:** Arch Linux 5.10.16

**Desktop Environment:** KDE Plasma 5.21.0

**Graphics Platform:** X11

**Version of Telegram Desktop:** 2.6.1

**Installation source (Linux Only)** - the official website

**Used theme**: Night

**Comment by ilya-fedin** [comment]
Already fixed on dev branch
