### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by KES777** [telegramdesktop/tdesktop#10462]
### Is your feature request related to a problem?
Sometimes I want to highlight code
```markdown
code **highlighted**
```
NOTICE: github highlighted word but asterisks still displayed

### Describe the solution you'd like
I'd like when asterisks are not shown

I'd like to use **```markdown** as language for codeblock

### Additional context
Here is code

![_4](https://user-images.githubusercontent.com/799021/109983123-34ddde80-7d0b-11eb-9593-85a6acc4e881.jpg)

Here is how it is displayed at telegram:

![_5](https://user-images.githubusercontent.com/799021/109983164-40310a00-7d0b-11eb-8186-3685d88fc2d9.png)

expected result:
`markdown` word should not displayed
`highlighted` word should be bold

**Comment by ilya-fedin** [comment]
#250
