### ISSUE TITLE
[Feature Request] Clickable timecodes improvements

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#10460]
### Is your feature request related to a problem?
Since your bot locked #5473, let me open another issue with some additions.

First, timecodes are not clickable for YouTube video, though they work for audio files
![изображение](https://user-images.githubusercontent.com/2780044/109927519-68057b00-7cd5-11eb-9c4c-4172fec48c97.png)

~~For regular video, only first timecode is clickable, making such feature useless~~ (edit: irrelevant, see comment below)
![изображение](https://user-images.githubusercontent.com/2780044/109927605-87040d00-7cd5-11eb-8539-ad5a28b9f99f.png)

### Describe the solution you'd like
Telegram introduced clickable timecodes back in August'19, though official apps still don't support this feature properly (not only TDesktop). I'd like Desktop app to support such clickable links (or - \*makes a deep breath\* - introduce timecode as a separate entity with Bot API support)

### Describe alternatives you've considered
Like in 90's: click the link and/or use timeline to find the precise moment.

**Comment by john-preston** [comment]
In your example of video file it looks like the file is 44 seconds while the timecodes are larger (except the first)?

**Comment by john-preston** [comment]
Time codes for videos work fine for me:

![image](https://user-images.githubusercontent.com/17900494/109931889-e3b9f480-7ce2-11eb-916e-de7e94f2cfb2.png)

**Comment by MasterGroosha** [comment]
@john-preston oh, my bad! You're right. So only YouTube links issues are left AFAIK

**Comment by MasterGroosha** [comment]
Nope, still relevant
