### ISSUE TITLE
Send .mp4 files as files.

### ISSUE THREAD

**Issue by Ryder17z** [telegramdesktop/tdesktop#10468]
`I just found a way. Use the [Telegram Web](https://web.telegram.org/) instead. You can upload .mp4 files as files.`

`_Originally posted by @TheOldGoldenFish in `
https://github.com/telegramdesktop/tdesktop/issues/3217#issuecomment-687842818_

Not a solution.

**Comment by TheOldGoldenFish** [comment]
I did and it worked well.

**Comment by Ryder17z** [comment]
doesn't help if they patch the webclient

**Comment by catSIXe** [comment]
> doesn't help if they patch the webclient

You already sending them as files... No Re-Compression is happening, its just that there is an embedded player. Telegram does 0-processing to any mp4 files. youre sending...

**Comment by Ryder17z** [comment]
I thought they re-encoded them as that's what usually happens in IM clients
from my experience.

**Comment by catSIXe** [comment]
only on mobilephone clients this is common, but you can also send them 
uncompressed there

------ Origineel bericht ------
Van: "TheExileFox" <notifications@github.com>
Aan: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>
CC: "cat6e" <github2.konrad@sch.umann.it>; "Comment" 
<comment@noreply.github.com>
Verzonden: 6-3-2021 15:08:32
Onderwerp: Re: [telegramdesktop/tdesktop] Send .mp4 files as files. 
(#10468)

>
>I thought they re-encoded them as that's what usually happens in IM 
>clients
>from my experience.
>

**Comment by catSIXe** [comment]
only on mobilephone clients this is common, but you can also send them
uncompressed there

**Comment by catSIXe** [comment]
and also

> If the MP4 is sent as video it will get the preview, but not the original filename. It won't be searchable, and will appear as media, not as file.
fromt he other issue report

the filename is untouched too
![image](https://user-images.githubusercontent.com/63829136/110212001-92a03100-7e99-11eb-9514-4aa34555f99e.png)
if you click on the preview to enter fullscreen mode, you can read it in the bottom left corner

![image](https://user-images.githubusercontent.com/63829136/110212017-a6e42e00-7e99-11eb-8623-e67f07dc1b3b.png)
or when you save it to a file.

**Comment by TheOldGoldenFish** [comment]
> > doesn't help if they patch the webclient
> 
> You already sending them as files... No Re-Compression is happening, its just that there is an embedded player. Telegram does 0-processing to any mp4 files. youre sending... 

TG Desktop won't compress anything but when you send it, it won't be uploaded as a FILE. It will be sent as a Video which you can what live. That was the case.

**Comment by AmadeusK525** [comment]
I actually agree with this Issue. This is the official GitHub for the Telegram Desktop App, not the Web ver (which is subpar). Fixing this shouldn't be difficult at all (and apparently it was already done in previous versions, from what I can tell. A lot of people state that the default behavior used to be to ask the user whether they wanted to send it as a file). The option to do this is already present when uploading photos and it should be present when uploading videos as well.

**Comment by john-preston** [comment]
@AmadeusK525 No, videos always were and are now uploaded as files. Those files are displayed as videos, with a play button and thumbnail, if they can be played inapp, but it is the same file that was sent and you can download it and get the same bytes that were sent
