### ISSUE TITLE
Fact-check for shared links

### ISSUE THREAD

**Issue by davimh** [telegramdesktop/tdesktop#10469]
Hello everyone!
Lately been wondering why instant message apps aren't integrated with fact-checking services. Think it should be nice for users to see if the content their sharing with their relatives have been considered true, false, partially true or what other category it could have.
Are there any plans related to that?

**Comment by Ryder17z** [comment]
this is quite difficult to do though. Where do you draw the line for partially true?

**Comment by davimh** [comment]
Yes, sure it is. But in the last couple of years, the number of fact checking services have increased a lot, and they have their own methods to define the truthness of an affirmation. And more recently, Google made an API for that purpose avaliable (https://toolbox.google.com/factcheck/apis).
Search result for a claim contained in a link looks like this:
![Screenshot_2021-03-05-07-01-56-360_com android chrome](https://user-images.githubusercontent.com/32531840/110100350-10244e00-7d81-11eb-95fc-da4a4db17e15.jpg)

**Comment by catSIXe** [comment]
just use your brain, if you have one...

**Comment by Xeddius** [comment]
Snopes is your friend. Fact-checking all links from within telegram itself isn't sensible, it would not only violate privacy but also cause issues for the majority of users who don't even use links to "News" sites. What would be the point in sending every url, even unrelated ones, to a fact-checking service? It's also a waste of data.

Something that is much more realistic would be a fact checking telegram bot that you could forward a link/url to. It would fact-check it for you using an api of your choice. I'm sure you can commission someone to write a bot for you or assist you if you put out a code bounty. This is something less for telegram devs and more for telegram bot creators.

**Comment by Ryder17z** [comment]
`<Mod> has removed `@catSIXe` from the chat.`

@Xeddius a handful of bots come up if you search "fact check bot" - sadly none of them work at the moment.

**Comment by catSIXe** [comment]
> `<Mod> has removed `@catSIXe` from the chat.`
nice try ;-)

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
