### ISSUE TITLE
[Feature Request] In groups chats give ability to hide messages from some users

### ISSUE THREAD

**Issue by WrongBit** [telegramdesktop/tdesktop#10471]
This feature was requested **FIVE TIMES**, but Telegram team ignores it. WHY?

We need ability to hide messages from some users in group chats. Admin of channel can kick "bad user", but casual group member cannot - that's why we need this feature.
I'm not sure we need to BLOCK user globally from contacting us, maybe only "block in this channel". In any case WE DO NOT WANT to see messages of some offensive persons - HIDE THEIR MESSAGES. Meaning not hide completely, but "collapse", so we don't see their rubbish.

I request DEFINITIVE ANSWER, will Telegram team implement it or not?? FIVE TIMES you were requested for the same feature and five times feature was autoclosed, because you even didn't assign anybody! Is it so hard to implement??? Not a bit harder than filtering row of records.
Please stop ignoring this feature, it's extremely needed! Too much clowns per group, you know that.

**Comment by john-preston** [comment]
@WrongBit This just doesn't belong here. Telegram Desktop being the official desktop app should have the same basic features all other Telegram apps (on other platforms, mobile) have.

For platform-wide (for all apps) feature requests and suggestions now there is public tracker. Your feature request is there already:

https://bugs.telegram.org/c/37

**Comment by WrongBit** [comment]
@john-preston : 

> should have the same basic features all other Telegram apps

Serious? How you decide that? Didn't you mention (eventually) that desktop has 24" screen, while mobile barely reach 6"? Desktop & mobile are **two different worlds** and barely you're smart enough to make 'em equal. That's why features CAN and MUST be different.
Funny, but even you know that desktop client has NO feature to send picture from attached camera. While mobile client has this ability. So... what will be your excuse that functionality is different?
