### ISSUE TITLE
Unicode 13 emoji modifiers show as their individual parts instead of a single glyph.

### ISSUE THREAD

**Issue by TheReverend403** [telegramdesktop/tdesktop#10478]
### Steps to reproduce

Paste the following (or any other emoji with modifiers) into any text input.

🏳️‍🌈
🏳️‍⚧️
👩‍❤️‍👨
🧑‍🤝‍🧑

### Expected behaviour

![expected](https://dev.pste.pw/f/FfQ.png)

### Actual behaviour

![result](https://dev.pste.pw/f/ghD.png)

These same emoji work perfectly fine everywhere else on my system.

### Configuration
**Operating system:**

Gentoo Linux

**Version of Telegram Desktop:**

2.6.1

**Installation source (Linux Only)**

Distro binary package.

**Comment by ilya-fedin** [comment]
#9775
