### ISSUE TITLE
Telegram for Windows: Doesn't resize properly when I move the window to another screen

### ISSUE THREAD

**Issue by nZeus** [telegramdesktop/tdesktop#10473]
### Steps to reproduce
1. You need 2 screens with different resolution
2. Open telegram on 1 screen
3. Move it to another

### Expected behaviour
* The app should resize accordingly (like all the other apps do)

### Actual behaviour
* The app is resized incorrectly, and scaling is terrible (fonts are huge), not possible to use the app.

### Configuration
Win 10

**Version of Telegram Desktop:**
2.6.1

**Used theme**:
N/A

Setup:
2xFullHD screens on top;
4k screen ate the bottom

![image](https://user-images.githubusercontent.com/2727326/110093532-1cb5a000-7d9b-11eb-9bff-0cdb08ce579d.png)

![image](https://user-images.githubusercontent.com/2727326/110093577-29d28f00-7d9b-11eb-8e3f-e04fd903b916.png)

**Comment by ilya-fedin** [comment]
#1121
