### ISSUE TITLE
[Bug] Cannot see name changes of people in contact list

### ISSUE THREAD

**Issue by timea-techgirl** [telegramdesktop/tdesktop#10479]
### Steps to reproduce
1. Add someone to contacts and save it as it is. If they change their name, I can't see the change

### Expected behaviour
I should be able to see a contact's name changes even if they are in my contact list

### Actual behaviour
If they change their name, I cannot see the changed name. In other words, I can't track name changes of people in my contact list. I can only see the change if I delete them from my list. I hope this behaviour can be fixed.

At the moment, I have deleted contacts and added them all in exceptions list so that they can see my profile picture (it's only visible to contacts) and now I can see whenever they change their name

### Configuration
**Operating system:**
Windows 10 x64

**Version of Telegram Desktop:**
2.6.1

**Used theme**:
Night

**Comment by RememberTheAir** [comment]
That's the intended behavior, please refer to the explanations given in this Reddit thread: https://redd.it/lvlznh

**Comment by timea-techgirl** [comment]
I think if the name is separated from contact name, people can see both. Right now, there is no right solution for this.
