### ISSUE TITLE
[Suggestion] Optional URL preview

### ISSUE THREAD

**Issue by Tigerken** [telegramdesktop/tdesktop#1048]
Hi,

I don't know if many other users of the app will agree with me, but I'd like to have 'URL preview' as an optional feature (which you can turn on/off in settings). Previewing urls that lead to images makes a lot of sense, but I think that a preview for http://google.com or any other non-media link is just cluttering the screen. And I know that you can click away the suggestion before you send the message containing an URL, but I'd prefer not having to do that every time. I am however very impressed with the speed and responsiveness of the implementation of URL preview :+1: 

So my suggestion is either to
- Make URL preview an optional setting
- Create an setting to only preview media pages (image extensions, youtube pages, ..)

Thank you for your consideration,
Thomas

**Comment by auchri** [comment]
Duplicate #687
