### ISSUE TITLE
No close button in theme preview

### ISSUE THREAD

**Issue by mymedia2** [telegramdesktop/tdesktop#10483]
### Steps to reproduce
1. Click to a downloaded .tdesktop-theme to open a preview window.
2. You can find a lot of themes in related channels, for example https://t.me/themes/105

### Expected behaviour
You will see a close button.

### Actual behaviour
Empty space. That's not theme bug, if you apply the theme, the close button will appear.

![изображение](https://user-images.githubusercontent.com/9163157/110171468-d00aad00-7e0c-11eb-8115-7f2dd60957ff.png)

### Configuration
**Operating system:** GNU/Linux Debian 11 bullseye

**Version of Telegram Desktop:** 2.6.1+ds-1

**Installation source (Linux Only)** - ~the official website / GitHub releases / flatpak / snap~ / distribution package: APT

**Used theme**: Default / Summer Evening

<details><summary><b>System Information</b>:</summary><pre><code>
Debian Release: bullseye/sid
  APT prefers testing
  APT policy: (500, 'testing'), (1, 'unstable')
Architecture: amd64 (x86_64)

Kernel: Linux 5.10.0-3-amd64 (SMP w/2 CPU threads)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8), LANGUAGE not set
Shell: /bin/sh linked to /usr/bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages telegram-desktop depends on:
ii  libavcodec58                                      7:4.3.1-8
ii  libavformat58                                     7:4.3.1-8
ii  libavutil56                                       7:4.3.1-8
ii  libc6                                             2.31-9
ii  libdbusmenu-qt5-2                                 0.9.3+16.04.20160218-2+b1
ii  libgcc-s1                                         10.2.1-6
ii  libgdk-pixbuf-2.0-0                               2.42.2+dfsg-1
ii  libglib2.0-0                                      2.66.7-1
ii  libgtk-3-0                                        3.24.24-1
ii  libhunspell-1.7-0                                 1.7.0-3
ii  libjpeg62-turbo                                   1:2.0.5-2
ii  libkf5waylandclient5                              4:5.78.0-2
ii  liblz4-1                                          1.9.3-1
ii  liblzma5                                          5.2.5-1.0
ii  libminizip1                                       1.1-8+b1
ii  libopenal1                                        1:1.19.1-2
ii  libopus0                                          1.3.1-0.1
ii  libqrcodegencpp1                                  1.5.0-2
ii  libqt5core5a [qtbase-abi-5-15-2]                  5.15.2+dfsg-4
ii  libqt5dbus5                                       5.15.2+dfsg-4
ii  libqt5gui5                                        5.15.2+dfsg-4
ii  libqt5network5                                    5.15.2+dfsg-4
ii  libqt5waylandclient5 [qtwayland-client-abi-5-15-  5.15.2-2
ii  libqt5widgets5                                    5.15.2+dfsg-4
ii  librlottie0-1                                     0.1+dfsg-1
ii  libssl1.1                                         1.1.1j-1
ii  libstdc++6                                        10.2.1-6
ii  libswresample3                                    7:4.3.1-8
ii  libswscale5                                       7:4.3.1-8
ii  libx11-6                                          2:1.7.0-2
ii  libxcb-keysyms1                                   0.4.0-1+b2
ii  libxcb-record0                                    1.14-3
ii  libxcb-screensaver0                               1.14-3
ii  libxcb1                                           1.14-3
ii  libxxhash0                                        0.8.0-2
ii  qt5-image-formats-plugins                         5.15.2-2
ii  zlib1g                                            1:1.2.11.dfsg-2

Versions of packages telegram-desktop recommends:
ii  fonts-open-sans  1.11-1.1

telegram-desktop suggests no packages.

</code></pre></details>

**Comment by mymedia2** [comment]
Was it fixed?

**Comment by Aokromes** [comment]
dunno, it was on official package?
