### ISSUE TITLE
Upload file from web

### ISSUE THREAD

**Issue by chalist** [telegramdesktop/tdesktop#10484]
It will be very good if you can upload files from across the web.

When the URL of a file has been pasted, it's possible to open a dialog box and ask for sending URL or uploaded file with pasted URL.

On the other hand, Telegram has been censored in some countries, and this can help send large files.
We can't Not just for movies, sending a 2GB file in poor Internet countries sometimes takes a day.

This is very practical.

Thanks.

**Comment by john-preston** [comment]
@chalist On Windows you can paste url to the choose file dialog input field and it will be downloaded for sending.

**Comment by catSIXe** [comment]
Why "upload from web"... do you see whats wrong with this?
You're re-uploading something AGAIN... this is such a wasteful waste of ressources, you should just copy the URL, the Preview is in most cases enough.. There is no need to reupload something that is already saved somewhere. (The Previerw does their Job).

**Comment by chalist** [comment]
@john-preston 
I use linux.

@catSIXe  Maybe you are right, but for channels that send movies and videos, this is very practical.
It's very hard to download and upload a 2GB file. It can be very useful for countries where the Internet is not high.

**Comment by catSIXe** [comment]
Telegram is not a Movie-Platform lol?

**Comment by chalist** [comment]
We can not force people to use tools based on our taste.
On the other hand, Telegram has been censored in some countries, and this can help send large files.
We can't Not just for movies, sending a 2GB file in poor Internet countries sometimes takes a day.

**Comment by Xeddius** [comment]
@chalist
> I use linux.

`split -b2000M bigfile`
Just split the file into 2gb pieces and send. Problem solved.

**Comment by chalist** [comment]
> @chalist
> 
> > I use linux.
> 
> `split -b2000M bigfile`
> Just split the file into 2gb pieces and send. Problem solved.

This is sweeping issue under the carpet :D

**Comment by Xeddius** [comment]
@chalist 
> This is sweeping issue under the carpet :D

Not at all, Telegram has a 2gb file size limit, splitting the files allows large files to be sent.
If you need to upload even larger files (up to 10gb), then you should use a sharing service like [tmp.ninja](https://tmp.ninja/)
the files are valid for 48h and you can upload directly from any device with curl!
`curl -i -F file=@localfile.rar https://tmp.ninja/api.php?d=upload-tool`

It's unlikely the Telegram filesize limit will increase.
If you're referring to the web interface for telegram then you are posting in the wrong github repo and I recommend posting your suggestion in the appropriate location. [Telegram Suggestions and Bugs](https://bugs.telegram.org/)

**Comment by chalist** [comment]
@Xeddius Thanks. I diden't know suggestions page.

**Comment by ilya-fedin** [comment]
> I use linux.

Probably you should ask your DE to support URLs in file chooser like on Windows?

**Comment by chalist** [comment]
@ilya-fedin Maybe that works on Windows. But I didn't see that feature, so Idk.
