### ISSUE TITLE
GTK file dialog override broken since 2.6.1

### ISSUE THREAD

**Issue by ingvar-lynn** [telegramdesktop/tdesktop#10482]
### Steps to reproduce
run `env QT_QPA_PLATFORMTHEME=gtk3 TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1 $(which Telegram)`

### Expected behaviour
GTK file dialog on file send/save

### Actual behaviour
baked-in qt file dialog

### Configuration
Ubuntu 20.04

telegram 2.6.1

**Installation source** - the official website -> autoupdater

**Used theme**: gtk3

no hints of the problem in log whatsoever (`-debug` flag used)

pretty sure 2.6.0 worked fine

tried replacing `gtk3` with `gtk2` - no effect

**Comment by ilya-fedin** [comment]
Please look into wiki for actual environment variables
https://github.com/telegramdesktop/tdesktop/wiki/Environment-variables

**Comment by ingvar-lynn** [comment]
thanks, `TDESKTOP_USE_GTK_FILE_DIALOG=1` fixed the problem.
