### ISSUE TITLE
It looks like telegram overrides XDG_CURRENT_DESKTOP to gnome

### ISSUE THREAD

**Issue by DenisKuplyakov** [telegramdesktop/tdesktop#10488]
### Steps to reproduce
1. Open some pdf file from telegram
2. File opened with LibreOffice Draw
3. Open the same pdf from dolphin
4. File opened with Okular

### Expected behaviour
File should be opened with Okular from telegram

### Actual behaviour
File opened with LibreOffice Draw

### Configuration
**Operating system:** OpenSUSE Tumbleweed

**Version of Telegram Desktop:** 2.6.1

**Installation source (Linux Only)** - the official website 

**Used theme**: Classic

### Additional info
I have read https://github.com/telegramdesktop/tdesktop/issues/9825 for details on how file opening is implemented. And it looks like that in my case telegram overrides XDG_CURRENT_DESKTOP from KDE to gnome, as xdg-mime reports following:

```
$ xdg-mime query default application/pdf      
okularApplication_pdf.desktop
$ XDG_CURRENT_DESKTOP=gnome xdg-mime query default application/pdf
draw.desktop
```

**Comment by ilya-fedin** [comment]
> I have read #9825 for details on how file opening is implemented.

But if you really read it, you should understand, that tdesktop doesn't use shell scripts like xdg-mime...

**Comment by DenisKuplyakov** [comment]
I have read it, understood that tdesktop uses `g_app_info_launch_default_for_uri`, but though that it also relies on xdg facilities to resolve mimetype. Ok, my mistake.

It looks like it rely on `gio mime` stuff to resolve mimetypes to applications. But I still don't understand what makes gio's and kde's file associations out of sync.

GIO is gnome stuff, is there any way to use some KDE specific methods in KDE?

**Comment by ilya-fedin** [comment]
> But I still don't understand what makes gio's and kde's file associations out of sync.

AFAIK KDE is non-XDG-compilant and uses custom way to determine default applications. It has some key in .desktop files of KDE applications that KDE libraries (KService/KIO) read and put them higher in priority. Any other XDG implementations don't know about that, of course.

> GIO is gnome stuff, is there any way to use some KDE specific methods in KDE?

Not really. glib is a small C library that is present on every desktop and could be even loaded with dlopen if this wasn't so. While KDE libraries are C++ libraries (they couldn't be used with dopen) with a lot of dependencies on other KDE libraries.

**Comment by DenisKuplyakov** [comment]
As I seen somewhere (maybe I'am wrong) tdesktop already uses xdg-desktop-portal.

It has an appropriate method to open files:

https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-method-org-freedesktop-portal-OpenURI.OpenFile

**Comment by ilya-fedin** [comment]
You can say glib to use it with `GTK_USE_PORTAL=1`

**Comment by ilya-fedin** [comment]
Take in mind that XDP uses glib as well and won't use KDE's custom additions to XDG as well
https://github.com/flatpak/xdg-desktop-portal/blob/master/src/open-uri.c
