### ISSUE TITLE
telegram for mac has two version . the 2.6.1 and the 7.5.x

### ISSUE THREAD

**Issue by netroby** [telegramdesktop/tdesktop#10485]
I found the latest version 7.5.x was not working with proxy.

But the 2.6.1 version can working well.

The 2.6.1 for mac can be download via: https://desktop.telegram.org/

The 7.5.x version can not using proxy.

**Comment by netroby** [comment]
The 7.5.x version not working at all.

https://github.com/overtake/TelegramSwift

https://macos.telegram.org/

I am not sure is it an official project.

Why there be two project?

**Comment by iMonZ** [comment]
> The 7.5.x version not working at all.
> 
> https://github.com/overtake/TelegramSwift
> 
> https://macos.telegram.org/
> 
> I am not sure is it an official project.
> 
> Why there be two project?

It is an official project.

Telegram Desktop is written for QT which is a Multiplatform Desktop library
while Telegram Swift is natively written for macOS and has every feature that the IOS app has!
Telegram Desktop is a mess it lacks so much features and is buggy as hell while Telegram Swift works perfectly fine and has all features!

**Comment by Aokromes** [comment]
they are different products with similar names
