### ISSUE TITLE
Wrong UI scalling applied for external applications opened from telegram

### ISSUE THREAD

**Issue by DenisKuplyakov** [telegramdesktop/tdesktop#10487]
### Steps to reproduce
1. open some PDF, text file or archive from telegram
2. okular, kwrite or ark is shown with excessive scaling applied for UI (see screenshots)
3. open the same file from telegram download dir with dolphin
4. okular, kwrite or ark is shown with correct scalling applied for UI (see screenshots)

Scale factor in telegram is set to 150%. I've tried to set it to 100%, but the issue remains

### Expected behaviour
External programs should be opened with the correct scaling

### Actual behaviour
External programs opened with wrong scaling

### Configuration
**Operating system:** OpenSUSE Tumbleweed

**Version of Telegram Desktop:** 2.5.8

**Installation source (Linux Only)** - distribution package (telegram-desktop)

**Used theme**: Classic

![from_dolphin](https://user-images.githubusercontent.com/3333218/110207716-6a630300-7e96-11eb-8a0a-a32f12744911.png)
![from_telegram](https://user-images.githubusercontent.com/3333218/110207718-6b943000-7e96-11eb-9e4b-def0643df115.png)

**Comment by Aokromes** [comment]
> ### Steps to reproduce
> 1. open some PDF, text file or archive from telegram
> 2. okular, kwrite or ark is shown with excessive scaling applied for UI (see screenshots)
> 3. open the same file from telegram download dir with dolphin
> 4. okular, kwrite or ark is shown with correct scalling applied for UI (see screenshots)
> 
> Scale factor in telegram is set to 150%. I've tried to set it to 100%, but the issue remains
> 
> ### Expected behaviour
> External programs should be opened with the correct scaling
> 
> ### Actual behaviour
> External programs opened with wrong scaling
> 
> ### Configuration
> **Operating system:** OpenSUSE Tumbleweed
> 
> **Version of Telegram Desktop:** 2.5.8
> 
> **Installation source (Linux Only)** - distribution package (telegram-desktop)
> 
> **Used theme**: Classic
> 
> ![from_dolphin](https://user-images.githubusercontent.com/3333218/110207716-6a630300-7e96-11eb-8a0a-a32f12744911.png)
> ![from_telegram](https://user-images.githubusercontent.com/3333218/110207718-6b943000-7e96-11eb-9e4b-def0643df115.png)

try downloading official package from desktop.telegram.org

**Comment by DenisKuplyakov** [comment]
> try downloading official package from desktop.telegram.org

I have downloaded 2.6.1 from desktop.telegram.org. The issue still presist

**Comment by ilya-fedin** [comment]
Yeah, tdesktop is forced to unset scale variables since they're incompatible with tdesktop: https://github.com/desktop-app/lib_ui/blob/fe09c42f0cd105ce7c48cdf1c5ae5043cc90e869/ui/ui_utility.cpp#L182-L187

**Comment by DenisKuplyakov** [comment]
I have such env vars that can be affected by this
```
$ env | grep QT_
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_IM_MODULE=xim
QT_IM_SWITCHER=imsw-multi
QT_SCREEN_SCALE_FACTORS=eDP-1=1;DP-1=1;HDMI-1=1;DP-2=1;HDMI-2=1;DP-3=1;HDMI-3=1;
```

I associated application/pdf via `gio mime` with konsole and tested env in opened (wrong scaled) konsole window:
```
$ env | grep QT_
QT_IM_MODULE=xim
QT_IM_SWITCHER=imsw-multi
```

I think if tdesktop requires such environment change it shouldn't affect applications launched

**Comment by ilya-fedin** [comment]
> I think if tdesktop requires such environment change it shouldn't affect applications launched

:man_shrugging: child processes inherit tdesktop environement, I guess this couldn't be really changed (at least in a non-hacky way)

**Comment by DenisKuplyakov** [comment]
By the way "Save file as" dialog shows correctly. And "Open folder with the file" opens Dolphin with correct scaling

**Comment by ilya-fedin** [comment]
file dialog on KDE/open folder are using D-Bus APIs and some service on the system launches these processes...
