### ISSUE TITLE
Window draws attention WHEN OPTION DISABLED

### ISSUE THREAD

**Issue by CodeMouse92** [telegramdesktop/tdesktop#10495]
I have the "Draw attention to the window" option ***DISABLED*** on Telegram 2.6.1, and yet it continues to grab focus on a new message *most* of the time (but weirdly, not always). This is fairly annoying at times, especially when I'm typing.

### Steps to reproduce
1. Ensure "Draw attention to the window." is ***unchecked.***
2. Leave the window open (not minimized), but hide it behind another another. Start clicking/typing in a different window.
3. Receive a message.
4. Notice that Telegram was brought to front, and keyboard focus immediately grabbed.

### Expected behaviour
Telegram should not grab focus or move to front, since "Draw attention to the window" was not checked.

### Actual behaviour
Telegram grabs focus.

### Configuration
**Operating system:** Pop_OS! (Ubuntu) 20.04

**Version of Telegram Desktop:** 2.6.1; I seem to recall the problem starting for me with 2.6.0.

**Installation source (Linux Only)** Official website.

**Used theme**: Day, Night

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

## Additional Note

Speaking as a software developer and community manager who spends a *lot* of time triaging bugs — so I totally understand the "fix it now!!1!" fatigue — you really should NOT be blaming the DE for this, as occurred with #10310. Telegram is *quite literally the only program that does this*, and I have more chat clients and notification-generating apps installed than is probably healthy for a person. It may be a bug specific to Telegram running on GNOME, but it still falls to Telegram to diagnose this.

## Additional Note 2
Reposting since Aokromes doesn't believe in reading.

**Comment by ilya-fedin** [comment]
Can't reproduce, doesn't focuses for me

**Comment by CodeMouse92** [comment]
Like I said, this is a rather unpredictable bug. Just when I think it's fixed...

Yay for nondeterministic bugs. Spend your career hunting them, and they start coming for *you*, haha.

**Comment by ilya-fedin** [comment]
> Like I said, this is a rather unpredictable bug.

Maybe some GNOME extension is interfering with tdesktop? Never seen anything like that.

**Comment by ilya-fedin** [comment]
I don't see how it can call QWindow::alert when the setting is disabled: https://github.com/telegramdesktop/tdesktop/blob/1fc24398a03818a8fa228e9c4dba0966b30055bd/Telegram/SourceFiles/window/notifications_manager.cpp#L394-L401

**Comment by CodeMouse92** [comment]
@ilya-fedin It might be deeper. On another project I was working on, the UI's checkbox was not properly affecting/reflecting the state of a setting.

**Comment by ilya-fedin** [comment]
If this is the case, it should reset on each reopen of settings since the same method is used to retrieve the state in the settings dialog:
https://github.com/telegramdesktop/tdesktop/blob/1fc24398a03818a8fa228e9c4dba0966b30055bd/Telegram/SourceFiles/settings/settings_notifications.cpp#L624-L630

**Comment by CodeMouse92** [comment]
Just trying to diagnose this a bit myself. I see one place where the setting is being directly mutated, although it's not clear what from. (Also, why wouldn't it toggle the box, then?)

https://github.com/telegramdesktop/tdesktop/blob/1a3253ae8b537a756c3bd06a5f5ceef471548d52/Telegram/SourceFiles/mainwindow.cpp#L730

Incidentally, I seem to remember this occurring on the XFCE DE as well (same computer). If I can get definite confirmation on that, it'll help narrow down what's causing this. It is weird that *only* Telegram, and literally nothing else...including several other chat clients...does this.

**Comment by ilya-fedin** [comment]
> I see one place where the setting is being directly mutated, although it's not clear what from.

When you disable notifications via tray option, it's expected that it will be restored to previous on next launch. This code handles this.

> Also, why wouldn't it toggle the box, then?

It will.

**Comment by CodeMouse92** [comment]
> It will.

I mean, if that was the source of the bug, it should logically change the checkbox on restart in my case, which it isn't.

**Comment by ilya-fedin** [comment]
> I mean, if that was the source of the bug, it should logically be triggering a change of the checkbox on restart in my case

yeah, exactly

**Comment by ilya-fedin** [comment]
> Incidentally, I seem to remember this occurring on the XFCE DE as well (same computer).

But XFCE doesn't focus the window even when the setting is active, it propery flashes the item in taskbar instead. Only GNOME and GNOME-based DEs are doing this weird thing.

**Comment by CodeMouse92** [comment]
I'll let you know when I can narrow down the reproduction of the setting not taking. Like I said, this is inconsistent.

> But XFCE doesn't focus the window even when the setting is active, it propery flashes the taskbar item instead. 

I could be remembering wrong. Like I said, I'll let you know if I can confirm.

By the way, here's the bug for the focus-grabbing: https://bugreports.qt.io/browse/QTBUG-48486

**Comment by ilya-fedin** [comment]
> Even so, this bug is more about that setting not "taking" somehow.

But if you say that you see this even on XFCE, this means that your problem is not related to this setting at all since XFCE doesn't focus the window on QWindow::alert

**Comment by CodeMouse92** [comment]
Your last comment:

> But if you say that you see this even on XFCE, this means that your problem is not related to this setting at all since XFCE doesn't focus the window on QWindow::alert

My last comment:

>> But XFCE doesn't focus the window even when the setting is active, it propery flashes the taskbar item instead.
> 
> I could be remembering wrong. Like I said, I'll let you know if I can confirm.

**Comment by ilya-fedin** [comment]
> The problem is Qt, not "the DE"

Qt just sets `demands-attention` hint, as documented. DEs (as usual) don't behavior in a standardized way and doing any weird thing they can imagine.

**Comment by ilya-fedin** [comment]
@andreyorst yeah, the window is manually moved to the active workspace now since not all window managers switch workspaces on focus request and people think that focus just doesn't work.

**Comment by ilya-fedin** [comment]
> Like I said, I'll let you know if I can confirm.

So...?

**Comment by CodeMouse92** [comment]
Not so far. I actually had to reinstall everything on this machine. Haven't had this repeat yet. Give it time. (Don't just close, though, @silasfrigo already confirmed.)

**Comment by ilya-fedin** [comment]
> Haven't had this repeat yet.

But you promised you will check how XFCE behaves with the option enabled:

> > But XFCE doesn't focus the window even when the setting is active, it propery flashes the taskbar item instead.
> 
> I could be remembering wrong. Like I said, I'll let you know if I can confirm.

**Comment by CodeMouse92** [comment]
I haven't had it happen again there, and I'm not using XFCE right now. If I have it repeat, I'll report, but for now, I think it's likely I was mistaken about that part.

**Comment by ilya-fedin** [comment]
@silasfrigo can you describe your case in details?

**Comment by silasfrigo** [comment]
@ilya-fedin Since i updated my Ubuntu to 20.04, it no longer happened.

**Comment by CodeMouse92** [comment]
Actually, I haven't had it happen again since the complete OS reinstall (I was on 20.04 before, and still am). Something weirdly transient about this one, but hopefully it's resolved.

**Comment by ilya-fedin** [comment]
So the issue could be closed?

**Comment by CodeMouse92** [comment]
Yeah, probably. I don't know if you have a "spooky" tag you could add to it; I highly recommend those on issues which aren't well understood or formally resolved, so you can close it while marking potentially nondeterministic behavior. (I'm also a project manager.)
