### ISSUE TITLE
[Feature Request] - Toggle Telegram window from the notification icon

### ISSUE THREAD

**Issue by Sopor** [telegramdesktop/tdesktop#10490]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.
As it is now it is only possible to open Telegram from the notification icon (systray), not minimize it.

### Describe the solution you'd like

I would like it to be possible to minimize Telegram by a single press on the notification icon.

This will make it easy to open Telegram and close it without even moving the mouse pointer. As it is now i have to move it to the X in the Telegram window.

**Comment by Sopor** [comment]
Btw, why are the bot closing `Feature Request` when it is the Telegram developer team we are waiting for and not the user?

`Feature Request` should be closed by a human and not a bot.

**Comment by ilya-fedin** [comment]
If the window is active, it will be hidden. Otherwise, it will be focused.

> Btw, why are the bot closing `Feature Request` when it is the Telegram developer team we are waiting for and not the user?

To close feature requests no one really interested in.

**Comment by mymedia2** [comment]
Which operating system and desktop environment do you bear in mind? Telegram Desktop already has the feature, though it may be unsupported by some OS or DE. I know that if in KDE on Linux you click Telegram icon in system tray while Telegram window is focused, it will became hidden.

**Comment by Sopor** [comment]
Strange that those other feature requests about this was telling us that it was added already instead of only closing them #8053 #5600

And yes, you are right. It seems that this is added now so i will close this...

**Comment by ilya-fedin** [comment]
> Strange that those other feature requests about this was telling us that it was added already instead of only closing them

This feature is here from the first commit: https://github.com/telegramdesktop/tdesktop/blob/4221fe666f13f1d83c27c5f64e83d9bc8b3cfb51/Telegram/SourceFiles/window.cpp#L582-L590

That's probably why these feature requests are ignored.
