### ISSUE TITLE
Window draws attention when it shouldn't

### ISSUE THREAD

**Issue by CodeMouse92** [telegramdesktop/tdesktop#10494]
I have the "Draw attention to the window" option unchecked on Telegram 2.6.1, and yet it continues to grab focus on a new message *most* of the time (but weirdly, not always). This is fairly annoying at times, especially when I'm typing.

### Steps to reproduce
1. Ensure "Draw attention to the window." is unchecked.
2. Leave the window open (not minimized), but hide it behind another another. Start clicking/typing in a different window.
3. Receive a message.
4. Notice that Telegram was brought to front, and keyboard focus immediately grabbed.

### Expected behaviour
Telegram should not grab focus or move to front, since "Draw attention to the window" was not checked.

### Actual behaviour
Telegram grabs focus.

### Configuration
**Operating system:** Pop_OS! (Ubuntu) 20.04

**Version of Telegram Desktop:** 2.6.1; I seem to recall the problem starting for me with 2.6.0.

**Installation source (Linux Only)** Official website.

**Used theme**: Day, Night

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

## Additional Note

Speaking as a software developer and community manager who spends a *lot* of time triaging bugs, don't blame the DE. Telegram is *quite literally the only program that does this*, and I have more chat clients and notification-generating apps installed than is probably healthy for a person. It may be a bug specific to Telegram running on GNOME, but it still falls to Telegram to diagnose this.

**Comment by Aokromes** [comment]
disable setting, not a bug, working as intended. blame who asked to implement this.

**Comment by CodeMouse92** [comment]
**I did disable the damned setting.**
