### ISSUE TITLE
Sending MP4 as GIF causes MP4 file to be locked

### ISSUE THREAD

**Issue by ssg** [telegramdesktop/tdesktop#10496]
### Steps to reproduce
1. Drag'n'drop an MP4 file to a chat
2. MP4 gets converted to GIF and sent
3. After transfer is complete, try to delete MP4 file

### Expected behaviour
File should be deleted

### Actual behaviour
Windows displays error as file is kept open.
Closing Telegram fixes this issue.

### Configuration
**Operating system:**
Windows 10 20H2
**Version of Telegram Desktop:**
2.5.9 x64
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Windows Store

**Comment by ilya-fedin** [comment]
#7818
