### ISSUE TITLE
Crash when cancelling adding an account

### ISSUE THREAD

**Issue by andev0** [telegramdesktop/tdesktop#10500]
### Steps to reproduce
1. Call someone.
2. Click "Add Account" in the side menu.
3. Click the "Cancel" button on the top left.

### Expected behaviour
Adding an account should be cancelled.

### Actual behaviour
Telegram crashes.

### Configuration
Windows 10 Pro 1909
Windows 10 LTSC 1809

**Version of Telegram Desktop**: 2.6.1

**Used theme**: night+green

<details><summary><b>Logs</b>:</summary>
[Time] Audio Info: recreating audio device and reattaching the tracks
[Time] Call Info: Creating instance with version '3.0.0', allowP2P: [TRUE]
[Time] Call Error: Unexpected state in handleStateChange: 4
[Time] Audio Info: Closing audio playback device.
[Time] Assertion Failed! "ptr_ != nullptr" pointers:83
</details>

**Comment by Aokromes** [comment]
plz post crash id on next restart.

**Comment by fejalex** [comment]
@Aokromes 
Your Report Tag: 092dc595-3394-4d56-a6a8-bc1c21810c83
Is it what you want?
