### ISSUE TITLE
message notifications adds window to task switcher, but not workspace

### ISSUE THREAD

**Issue by shinenelson** [telegramdesktop/tdesktop#10507]
### Steps to reproduce
1. Have Telegram Desktop running in different workspace
2. Receive notifications

### Expected behaviour

The message notification respecting the preference in the settings.
The application window is not added to the task switcher without it being in the workspace.

### Actual behaviour

Double notification
1. The actual message notification ( respecting the preference in the settings )
2. System notification saying the application "is ready"

![Screenshot from 2021-03-09 23-17-07](https://user-images.githubusercontent.com/4771718/110517249-a0231880-8130-11eb-9aca-f575de9ae590.png)

I think the second notification is triggered because the application is being added to the window list. It shows up in the task switcher ( Alt-Tab ), and annoyingly inhibits Alt-Tab switching because the window is not actually there. Upon selecting the window from the task switcher, it navigates to the workspace where the application actually was in.

I am not sure whether this is a bug or a feature gone wrong. If it was a feature of the window popping up in the current workspace, it did not work for me at least.
Or maybe working with multiple work-spaces was not considered when the feature was developed.
Or it could possibly be a Qt bug on GNU/Linux too, I am not sure.

I also tried switching to using native notifications, the "Telegram Desktop is ready" notification still appears along with the other message notifications in the message tray.

---
### Configuration
**Operating system:** Ubuntu 21.04

**Version of Telegram Desktop:** 2.6.1

**Installation source (Linux Only)** : official website, binary run directly from extracted folder

**Used theme**: default with night mode enabled ( though I do not think the theme has anything to do with this issue )

**Comment by ilya-fedin** [comment]
#8853
