### ISSUE TITLE
[Feature Request] Overfeature: fetching link content - make it an option! Reopen #10472

### ISSUE THREAD

**Issue by WrongBit** [telegramdesktop/tdesktop#10504]
I got no any reasonable answer on my request and it was... closed! Why? I request more respect to user's feedback! Even if you (Aokromes) is collaborator, it doesn't give you right of "god" in a project. And I won't shy to escalate my request to higher level.
I still request feature in #10472 and this request MUST BE OPEN, until free resources appears.

**Comment by Aokromes** [comment]
also you look to report for telegram android not telegram desktop.

**Comment by WrongBit** [comment]
@Aokromes : you're talking nonsense. I'm not reporting about bug, open eyes and read: **[Feature Request]**
