### ISSUE TITLE
No visual indicator when window has focus or is active

### ISSUE THREAD

**Issue by BoffinBrain** [telegramdesktop/tdesktop#10501]
_(This issue is an updated copy of [#3682](https://github.com/telegramdesktop/tdesktop/issues/3682#issue-244186311) which was auto-closed by one bot because no developers replied to it, and then auto-locked by another bot.)_

Whether tdesktop has focus or is inactive, the window border and title bar always look the same. The only subtle hint might be the presence or absence of a blinking text cursor.

On Windows, I would suggest going with a red close button, since this is one of the ways Windows indicates a focused window on Windows Vista, 7, 8 and 10. You could also change the color of the whole title bar like on classic Windows. Another possible addition could be having the application's name in the top left of the title bar (you know, like every other application does?) which can toggle between a muted color and a more vivid one.

### Configuration

**Operating system:** Windows 7 or 10

**Version of Telegram Desktop:** 2.6.1

**Used theme:** Default or Night Mode

Here's a screenshot of the night mode title bar when it's not in focus, and when it is in focus. The only difference is a slight change in the shade of grey. In light mode, there is no difference at all.

![image](https://user-images.githubusercontent.com/13255058/110258645-94521d80-7f9b-11eb-8829-9bb681908578.png)

@scvairy and @stek29 because they 👍 the previous ticket.

**Comment by ilya-fedin** [comment]
> because no developers replied to it

bots waiting for reply from the reporter...

**Comment by BoffinBrain** [comment]
> bots waiting for reply from the reporter...

I don't understand. Where in the original ticket did the bot ask me for a reply?

**Comment by ilya-fedin** [comment]
![image](https://user-images.githubusercontent.com/17829319/110259544-1a706300-7fa0-11eb-8645-7f28d789da9c.png)

**Comment by BoffinBrain** [comment]
Okay, so 'let us know with a comment' actually meant 'reply to this issue'. I think Stale-bot's messaging was clearer. I was probably too busy with life things to chase this at the time, but anyway, here it is again.

**Comment by ilya-fedin** [comment]
> Okay, so 'let us know with a comment' actually meant 'reply to this issue'.

What else could this mean? :confused:

**Comment by BoffinBrain** [comment]
So, back on topic! I've made these mock-ups for the dark and light theme for critique. The changes are as follows:

1. Added "Telegram" to the title bar (just an idea - this is purely optional)
2. Window controls have less contrast than before when not in focus, and have more contrast than before when in focus.
3. Added a highlight border around the search box in dark mode because it doesn't currently have one (should this be reported as a separate issue?)

![Telegram Title Bars](https://user-images.githubusercontent.com/13255058/113434485-f6564500-93d8-11eb-8798-d25dcfac036f.png)

I was considering making the close button red when in focus, but it looks like other apps, including Windows itself, don't do this any more. More minimalism, I guess.

**Comment by ilya-fedin** [comment]
> I offer the following suggestion for a more concise message

Actual message is here
https://github.com/telegramdesktop/tdesktop/blob/dev/.github/stale.yml#L10-L17

**Comment by BoffinBrain** [comment]
Ah, so it now gives 30 days notice before closing? If so, the second paragraph needs a correction, or an addition.

**Comment by BoffinBrain** [comment]
Yes, Stale-Bot. I'm still alive. 180 days really flies by, doesn't it?

**Comment by ilya-fedin** [comment]
Apparently, someone should finally tell this to you: the design is proposed by Telegram Designers. Developers don't have right to implement any third-party propositions AFAIU. Telegram Designers don't read GitHub Issues, this is not a relly official bugtracker, it's read only by developers from Telegram Team (like @john-preston) and by third-party contributors (like me). No one relay these issues to other parts of their team usually (sometimes some bugs are relayed to server-side developers, but usually such issues are ignored). The only way to propose such a change is https://t.me/designers. Still, they have full right to not to agree with your propose and your post will be just ignored. For the best results I recommend to create a video mockup. As far as I heard, they react better to videos.

**Comment by RememberTheAir** [comment]
Maybe also opening a ticket on https://suggestions.telegram.org or bugging them on Twitter could help. On Linux I'm using the native window frames option so that helps with figuring out whether Telegram is focused or not, but on windows native frames suck so I would love to have other visual indications about the focus status

**Comment by RememberTheAir** [comment]
unstale
