### ISSUE TITLE
[Feature Request]  Option to Prevent Other Party From Deleting Messages

### ISSUE THREAD

**Issue by madranet** [telegramdesktop/tdesktop#10505]
One of the 'features' that Telegram has is that it allows the other party in a conversation to unilaterally delete messages from the conversation. 

Much though I love Telegram, this [for me] is the absolute worst feature imaginable. What this remote delete facility actually does is it gives someone else the ability to delete data stored on my devices, without my permission. I know some people think this is a great idea. But I find it abhorrent  --all the more so given that it's a 'feature' of an app which is supposed to be built around privacy and security. The only person who should have the ability to delete [or authorise deletion] of data from my devices is me. Full stop.

I'm sure many people will remember the furore a couple of years back when Amazon was found to have been remotely deleting books from people's Kindles.  People were rightly outraged at this invasion of their privacy and, in my eyes, Telegram allowing the other party in a conversation to unilaterally delete messages from my devices is no different from Amazon's behaviour.

The situation is made worse by the fact that the dialogue for deleting a message defaults to  _"Delete for me and &lt;other party&gt;"_. So even if the other person in the conversation is considerate enough to only want to delete messages from their own devices, they need to remember to untick this option each time, so they don't accidentally delete from mine too.

In addition, Telegram doesn't offer an auto-backup feature. So, if I want to keep a permanent record of my conversations, in case of accidental or deliberate deletion by someone else, I have to remember to manually trigger a backup every few days. And the backup feature is extremely 'dumb'. It never remembers were the previous backup was saved and it doesn't incrementally backup, but downloads everything, every time.

I know that Telegram won't remove this 'remote delete' ability completely. But I would like to request the ability for either party in a conversation to choose to not allow remote deletion from their own devices.  If there are any security concerns about this [and I don't really see any valid ones], then Telegram could present a warning to the other party when they first enter into conversation saying something like _"Any messages you delete from this conversation will remain on the other party's devices"_. 

Either way, please allow us the right to protect the data on our own devices from remote deletion.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by madranet** [comment]
Thanks for moving it for me.

Oh wait. you didn't.
