### ISSUE TITLE
telegam dpi not amooth using hidpi with multi monitor in windows 10.

### ISSUE THREAD

**Issue by onionmixer** [telegramdesktop/tdesktop#10514]
hi. dear telegram developers.

my env is...

1. windows 10 64bit - laptop
2. multi monitor - 1080p, 1080p, 4k(2160p). > yes. 3 monotor.
3. 4k monitor using hidpi. another monotor using normal dpi.

of course.. i know alreay hidpi option in telegram. but use hidpi option in tellgram then.... really big display in normal dpi.

another application using smooth.(ex : notepad++)

can fix this issue please?. thanks.

**Comment by ilya-fedin** [comment]
#1121
