### ISSUE TITLE
Memory leak after playing media files

### ISSUE THREAD

**Issue by NotStatilko** [telegramdesktop/tdesktop#10516]
### Steps to reproduce

Play large video or audio multiple times.

### Expected behaviour

Telegram should flush media files from memory.

### Actual behaviour

Media just stacks up in memory so Telegram (and system) becomes unusable on old machines until we restart it.

### Configuration
**Operating system:**
Debian GNU/Linux 10 (buster) &
Ubuntu 20.04 Focal Fossa

**Version of Telegram Desktop:**
`2.6.1`

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

Official website. 

![Screenshot_2021-03-11_10-54-10](https://user-images.githubusercontent.com/43419673/110764169-67cc2900-825b-11eb-8738-367531bccc3e.png)

__(Telegram would continue to fill the memory further, the screenshot is not the limit.)__

**Comment by ilya-fedin** [comment]
#7361?

**Comment by NotStatilko** [comment]
> #7361?

Telegram doesn't remove video from memory after watching it? Looks crazy, this is just 2 big videos for my machine. 
The #7361 was about cached images and normal messages, so I decided to open a new one. 

Close this issue if it's a duplicate, but make fix please :')

**Comment by ilya-fedin** [comment]
> Close this issue if it's a duplicate, but make fix please

There are no fix for leaks because @john-preston can't reproduce them. So most likely there won't be a fix.

**Comment by NotStatilko** [comment]
> > Close this issue if it's a duplicate, but make fix please
> 
> There are no fix for leaks because @john-preston can't reproduce them. So most likely there won't be a fix.

Maybe because that's only on Debian? I don't know but in #7361 John Preston tested only on Windows.

**Comment by ilya-fedin** [comment]
> Maybe because that's only on Debian? I don't know but in #7361 John Preston tested only on Windows.

Maybe. @john-preston is not really familiar with programming for Linux, so probably it's worth to find the leak and fix on your own.

**Comment by ilya-fedin** [comment]
tools like valgrind are useless here since tdesktop uses smart pointers and the only way you can find the leak is memory profiler

**Comment by NotStatilko** [comment]
> > > Close this issue if it's a duplicate, but make fix please
> > 
> > 
> > There are no fix for leaks because @john-preston can't reproduce them. So most likely there won't be a fix.
> 
> Maybe because that's only on Debian? I don't know but in #7361 John Preston tested only on Windows.

When i used Windows (~1 year ago) there **seemed** to be no such problem.

> > Maybe because that's only on Debian? I don't know but in #7361 John Preston tested only on Windows.
> 
> Maybe. @john-preston is not really familiar with programming for Linux, so probably it's worth to find the leak and fix it on your own.

I'm like John, but not familiar with C++ at all. So if anyone can help that's will be very good.

This problem can be related to #7280, #10327 & other issues which based on Linux systems. 

It seems that it's not #7361 because we are not talking about "weeks of continuous work of Telegram" (which can be explained by the fact that Telegram caches text messages in memory), but about the fact that Telegram does not clean media files from memory at all. 

If any of devs have Linux please try to open & close some big video files and check memory, because if it's not only my problem that's definitely looks like a serious bug.

Btw when i used Windows (~1 year ago) there seemed to be no such problem.

**Comment by ilya-fedin** [comment]
> If any of devs have Linux please try to open & close some big video files and check memory, because if it's not only my problem that's definitely looks like a serious bug.

I checked and RAM consumption stops increasing somewhere at 900M. Probably it's the in-RAM cache limit.

**Comment by ilya-fedin** [comment]
I tried to look channels with a lot of media after this, it's increased to 1030MB and stopped.

**Comment by NotStatilko** [comment]
> I tried to look channels with a lot of media after this, it's increased to 1030MB and stopped.

So it's on Telegram or Linux side? Any way to fix this?

**Comment by ilya-fedin** [comment]
> So it's on Telegram or Linux side?

I tested on Linux

**Comment by NotStatilko** [comment]
> > So it's on Telegram or Linux side?
> 
> I tested on Linux

The same on Windows? Any workaround of this RAM cache? May be additional option in Settings -> Advanced in Telegram? Or it's only on Linux and i can fix it by myself with some pretty commands? :)

**Comment by ilya-fedin** [comment]
I don't use Windows, but it should be the same. AFAIK the size of RAM cache is hardcoded and the only who can add new settings is @john-preston

**Comment by NotStatilko** [comment]
@john-preston, i need your help :)

How about adding this to settings? If it's really so necessary users with big amount of RAM can increase it to speed-up Telegram and vice versa. Or we can make this as variable and use 25% of RAM. Or just make a key for executable, such as `--ram-cache=p (percent)`.

This constant can be real problem in machines with low amount of RAM. 2 videos and i should restart Telegram, not so usable.

**Comment by NotStatilko** [comment]
> I don't use Windows, but it should be the same. AFAIK the size of RAM cache is hardcoded and the only who can add new settings is @john-preston

Thanks for help and testing.

**Comment by john-preston** [comment]
@NotStatilko Hi. There is no such thing as ram cache limit right now :(

All memory used to play video files should be freed once you close media viewer. All memory used to autoplay video files inside chat should be freed once you close the chat.

**Comment by NotStatilko** [comment]
> @NotStatilko Hi. There is no such thing as ram cache limit right now :(
> 
> All memory used to play video files should be freed once you close media viewer. All memory used to autoplay video files inside chat should be freed once you close the chat.

But this doesn't happen on Linux, which is confirmed by Ilya Fedin. Memory rises up to ~1100MB and never freed.

**Comment by ilya-fedin** [comment]
@NotStatilko can you provide exact steps to reproduce? I checked the leak I observed with heaptrack and looks like it caused by video preview in the video list in channel/group profile rather than by videos themselves

**Comment by NotStatilko** [comment]
> @NotStatilko can you provide exact steps to reproduce? I checked the leak I observed with heaptrack and looks like it caused by video preview in the video list in channel/group profile rather than by videos themselves

Just find 2 videos with ~800MB size and play it for 10 (or longer) minutes. Close the video and check memory, it shouldn't be freed. You can also play some music and check RAM. On my machine it doesn't freed at all. 

Not scroll previews, just watch large video.

**Comment by ilya-fedin** [comment]
> Just find 2 videos with ~800MB size and play it for 10 (or longer) minutes.

"just find"
You're talking like it's easy to find one for everyone. Can you provide link to these videos?

**Comment by NotStatilko** [comment]
> > Just find 2 videos with ~800MB size and play it for 10 (or longer) minutes.
> 
> "just find"
> You're talking like it's easy to find one for everyone. Can you provide link to these videos?

https://t.me/dvachannel/65932

**Comment by NotStatilko** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16084#issuecomment-841189351
