### ISSUE TITLE
Unexpected window drag while typing and by the mouse move on Linux Mint 20.1, Cinnamon

### ISSUE THREAD

**Issue by Wohlstand** [telegramdesktop/tdesktop#10512]
### Steps to reproduce
1. Keep Telegram window open
2. Type anything in any application, type messages in Telegram itself
3. Move the mouse around and type anything, move the mouse over Telegram window keeping held no buttons

### Expected behaviour
Telegram stay not touched. The only way to drag and move the Telegram window is to drag the title bar or hold the ALT key together with a mouse button to drag the window at any of its positions.

### Actual behaviour
In a random and sudden moment, the Telegram window gets to be dragged with no keyboard keys held, and no mouse buttons pressed or held. That happens randomly and it's hard to catch. But, happens often and annoying. While typing the message in the Telegram itself, the cursor gets suddenly turned into the "dragging in process" that prevents me to type the message. Then, the mouse move does move the window itself.

This mess got introduced after 2.6.0 or 2.6.1 (don't remind).

The keyboard and mouse replacement didn't help.

### Configuration
**Operating system:**
Linux Mint 20.1, Cinnamon

**Version of Telegram Desktop:**
2.6.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
The ISO image downloaded from the official site https://www.linuxmint.com/edition.php?id=284
All mainstream updates were installed by `apt update / apt upgrade`.
Using Russian locale, having to set up Russian and Polish layouts (the Polish layout is used instead of well-known English as I do learn and type Polish, and as my Polish friend tells, the Polish layout is used for both English and Polish, the ALT key is used to get access to Polish-specific characters such as "łćóśęą").

EDIT: The installation of Telegram itself, the first time I downloaded it by the Github Releases (Linux 64 binary tar.gz archive), then, the update gets came by the Telegram itself, I just hit the "Обновить Telegram" to cause it to restart and run the updated version.

**Comment by ilya-fedin** [comment]
already fixed on dev branch

**Comment by Wohlstand** [comment]
@ilya-fedin , Отлично :fox_face: 
Когда запланировано ближайшее обновление, хотя бы Беты? Иначе тогда попробую собрать из исходников временную копию...

**Comment by ilya-fedin** [comment]
> Когда запланировано ближайшее обновление, хотя бы Беты?

хз, только престон знает, я просто контрибучу

> Хотя вижу GitHub Actions, и там сборка битая пока временно, буду ждать тогда.

Она всегда битая...

**Comment by Wohlstand** [comment]
> хз, только престон знает, я просто контрибучу

Ну ладно, но всё равно спасибо за новость о том, что багу уже починили :fox_face: 

> Она всегда битая...

В одной из них вижу, что не хватает одного пакета в седьмой Центоси... У меня кстати на домашнем сервере она до сих пор пашет.

**Comment by ilya-fedin** [comment]
> В одной из них вижу, что не хватает одного пакета в седьмой Центоси...

а, линуксовый экшен просто работает от докер-образа и престон не залил образ на актуальном докерфайле с новыми зависимостями еще
