### ISSUE TITLE
Upon opening, a white screen is briefly visible before content loads

### ISSUE THREAD

**Issue by Xalaxis** [telegramdesktop/tdesktop#10518]
### Steps to reproduce
1. Have Telegram minimized to system tray
2. Click icon
3. Room and eyes are briefly blasted with white light before theme kicks in :)

### Expected behaviour
Theme should either appear instantly, or a black placeholder loading screen should be used for darker themes.

### Actual behaviour
A solid white screen is briefly displayed, which can be blinding in a dark room.

### Configuration
**Operating system:**

Windows 10

**Version of Telegram Desktop:**

2.6.1

**Used theme**: https://t.me/ABTheme/105

**Comment by ilya-fedin** [comment]
it's probably a bug in your gfx driver, see #8451. I can't reproduce.

**Comment by Xalaxis** [comment]
> it's probably a bug in your gfx driver, see #8451. I can't reproduce.

Can you confirm you are running with a black theme and "Use system window frame" disabled?

**Comment by ilya-fedin** [comment]
> Can you confirm you are running with a black theme and "Use system window frame" disabled?

No, but I tried to switch to black theme especially for you.

**Comment by Xalaxis** [comment]
I am not experiencing this issue at present on the current version.
