### ISSUE TITLE
[Feature request] Add an option to put channels and groups into categories 

### ISSUE THREAD

**Issue by Machielovic** [telegramdesktop/tdesktop#10523]
I miss the option to put the channels and groups into categories or to be able to put them into folders or something like that. Like you can now archive a chat if the group or channel is dead.

**Comment by Younes-L** [comment]
This feature has been added in [v 2.0.0](https://github.com/telegramdesktop/tdesktop/releases/tag/v2.0.0)
Go to **tdesktop settings > folders** to create folders
https://telegram.org/blog/folders#desktop-sync
