### ISSUE TITLE
[Feature Request] Hiding channel messages 

### ISSUE THREAD

**Issue by koutsenko** [telegramdesktop/tdesktop#10524]
### Is your feature request related to a problem?
The main problem is information overload and the inability to "throw away" unnecessary information as you read it. Many of us are subscribed to channels with useful content, and would like to save messages that are personally useful to ourselves. We can copy useful posts to Favorites, into one feed. It is not very convenient if the content is on different topics.

### Describe the solution you'd like
Add the ability to hide selected messages in the channel and chat, only for yourself. It is proposed to store metadata on the server - chat or channel id and an array of hidden messages id. On the client, add the "Hide" item and the "Show hidden" option to the context menu, if, for example, you have hidden something by mistake. Something like filtering chats and channels by message id. Of cource if you're selected many items, you can hide them all.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by koutsenko** [comment]
Ok, thanks, I created an issue here https://bugs.telegram.org/c/3201
