### ISSUE TITLE
[Question] OSX Big Sur 11.2.2 app constantly crashing with default LibreSSL and no crashes with latest libressl 3.2.4

### ISSUE THREAD

**Issue by krutoivoker** [telegramdesktop/tdesktop#10529]
Hello,
**Problem:**
I've recently compiled tdesktop, master branch, ~1 week old, for OSX using the official guide. I've observed that the app constantly crashing. Xcode showed the place in code: it was openssl_help.h, line 558 	if (!RAND_bytes(buffer, sizeof(T))) {
The probability of a crash depends on how often the app trying to download something. It was something about MTProto threads, Downloads, and EXC_BAD_ACCESS. (Xcode showed that). Tried with own MTProto proxy and without.
After several days of WTF-thinking I've decided to replace LibreSSL with the latest 3.2.4 from an official site. And after that app stopped crashing.
**Question:**
 Why did it happen? Something buffer-related occurred as I understand that. Why no such crashes in an official Telegram Desktop for Mac?

**Comment by ilya-fedin** [comment]
tdesktop uses openssl, not libressl...

**Comment by krutoivoker** [comment]
Strange, app stopped crashing right after updating system's libressl.

**Comment by john-preston** [comment]
I don't know. If you really used that library, it could've required multi-threading initialization, the newer versions of openssl don't required it. But if you built it yourself you should've used self-compiled openssl.

**Comment by krutoivoker** [comment]
Thank you. I'll try to investigate it deeper.
