### ISSUE TITLE
Arabic latter Yaa (ي) appears as Alif (ى) without dots

### ISSUE THREAD

**Issue by osamz** [telegramdesktop/tdesktop#10536]
### Steps to reproduce
1. Open app
2. Write any Arabic word that ends by latter  **ي** anywhere (search bar, message) or open any message contains Arabic word ends by same latter.

### Expected behaviour
Any word ends with latter **ي** appears as **ي** as it is, for example: **في** .
![image](https://user-images.githubusercontent.com/13044444/111073604-6c5d3f80-84f0-11eb-83d8-8772acc5497e.png)

### Actual behaviour
the ي latter appears as ى (which totally different latter, and changes meaning)
![image](https://user-images.githubusercontent.com/13044444/111073674-a2022880-84f0-11eb-8bd9-446a9cc70ee5.png)

### Configuration
**Operating system: Windows 10 home 20H2**

**Version of Telegram Desktop: 2.6.2 beta, language is English .**

**Used theme**: default dark

### Notes:
1. Problem appears only if word ends by latter **ي**
2. Problem maybe in other languages as Persian, Urdu.
3. The latter is **ي** actually, only appears as **ى** (same shape, without dots)
4. Problem appears only after update to 2.6.2 beta

**Comment by AssemKhidhr** [comment]
Same issue here with the classic theme. Tried the following fix and failed:

1. Run
2. Regedit
3. `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes`
4. modify MS Shell Dlg 2

**Comment by ilya-fedin** [comment]
2.6.2 has updated Vazir, maybe a Vazir bug?

**Comment by Muaath5** [comment]
I also had this problem :(
I have version 2.6.2

**Comment by Aokromes** [comment]
https://github.com/rastikerdar/vazir-font/issues/194 ?

**Comment by osamz** [comment]
> 
> 
> [rastikerdar/vazir-font#194](https://github.com/rastikerdar/vazir-font/issues/194) ?

Yes, same problem.

**Comment by osamz** [comment]
> 
> 
> 2.6.2 has updated Vazir, maybe a Vazir bug?

Yes, I think

**Comment by osamz** [comment]
This issue is not (only) on 3rd party. I use the original version.
