### ISSUE TITLE
Notifications show in-game and cause 90% FPS drop

### ISSUE THREAD

**Issue by TheGP** [telegramdesktop/tdesktop#10539]
### Steps to reproduce
1. Play Dota2
2. Get some standart notifications (no gnome native, telegram native didn't test it)
3. Get 90% FPS drop

### Expected behaviour
Notifications should not show at all when a game is full screen 

### Actual behaviour
Notifications show on top of the game and cause huge FPS drop

### Configuration
**Operating system:** Ubuntu 20.10

**Version of Telegram Desktop:** 2.6.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: From Ubuntu software store

**Used theme**: Standart

**Comment by ilya-fedin** [comment]
Can you provide any API to detect a running full-screen game on Linux? I don't know ones.

**Comment by taha-ghadirian** [comment]
> Can you provide any API to detect a running full-screen game on Linux? I don't know ones.

Hello, Its better to detect notification sending settings using Focus assistant (in windows) Or Notification settings In Linux.

**Comment by ilya-fedin** [comment]
> Hello, Its better to detect notification sending settings using Focus assistant (in windows) Or Notification settings In Linux.

AFAIK there's no known API to do that. tdesktop already uses some Windows API to check DirectX games, but this doesn't work for all the games for some reason (#2290). There's no such API on Linux at all AFAIK.

**Comment by Jalkhov** [comment]
I just want to point out that in [Osu!](https://osu.ppy.sh/home/) this problem also occurs, and boy, it's a game that doesn't require too many resources.

**Comment by ilya-fedin** [comment]
I don't understand what do you want after these words... This can be solved if someone provide a way to solve this, but no one provided so far.

**Comment by CyanRyan** [comment]
I had this issue for months. Disabling animations in performance settings fixed it. It's not the notification itself that causes the problem, just the fade-out effect of the notification. This still needs to be fixed, but this is a great band-aid solution in the meantime.

**Comment by ilya-fedin** [comment]
Well, there seem to be no way to fix this. X11 doesn't seem to provide any API to know where's a game is running.

**Comment by ilya-fedin** [comment]
@Aokromes i think the issue should be closed since the platform doesn't provide APIs to implement this.
