### ISSUE TITLE
In Gnome after clicking notification, window appears on current workspace instead of moving to workspace with telegram window

### ISSUE THREAD

**Issue by ilyachch** [telegramdesktop/tdesktop#10543]
### Steps to reproduce
1. Open Telegram
2. Move it to another workspace
3. Get notification and click it

### Expected behaviour
If the telegram application is open, the current workspace should be switched to where the telegram window is currently on

### Actual behaviour
Telegram window moves from workspace it was open on to current workspace

### Configuration
**Operating system:** Fedora 33, Gnome 3.38.4, X11 session

**Version of Telegram Desktop:** 2.6.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: flatpak

**Comment by ilya-fedin** [comment]
#10441

**Comment by ilyachch** [comment]
I also want to add:
If I turn on "Notifications -> Draw attention to the window", there are 2 notifications (Notification with sender, message etc, and notification "Window is ready")

After clicking the second notification, everything works as expected (I think it cause native gnome behavior).
So affected only app notification.

**Comment by aspieln3r** [comment]
I was searching a solution to this for somedays thinking its a gnome issue but when I click on notifications send by my browser, workspace is swtiched and browser opens in its assigned window as expected. This is a telegram issue. I can confirm behaviour is same when using native notifications and the telegram built in notificaiton

**Comment by ilyachch** [comment]
So, what is the decision? Related issue is also closed without PR or anything else
