### ISSUE TITLE
[Feature Request] Dont close image popup when using multiple monitors

### ISSUE THREAD

**Issue by alejandroPardo** [telegramdesktop/tdesktop#10541]
### Is your feature request related to a problem?
When working in multiple monitors, opening an image opens a popup with the image on one monitor, the other one continues to have previous content. 

### Describe the solution you'd like
It would be very useful to have the image opened in the popup in one monitor while you use the other one without it closing automatically on outside click. Sometimes I have to use an image information and when I click outside it closes.

### Describe alternatives you've considered
The solution (if possible) is to allow the image popup to remain open when clicking on another app in another screen.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1710
