### ISSUE TITLE
Telegram window sticked to mouse pointer

### ISSUE THREAD

**Issue by Germano0** [telegramdesktop/tdesktop#10542]
Sometimes when you use Telegram Desktop, it will be sticked to the mouse pointer as if you are moving the window around the screen. Sometimes the trigger is the receive of a new message or sometimes it happens when you use mouse scrollbar to scroll messages

### Configuration
**Operating system:**
Fedora

**Version of Telegram Desktop:**
2.6.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official website

**Used theme**:
Classic

**Comment by ilya-fedin** [comment]
Already fixed in 2.6.2

**Comment by Germano0** [comment]
I confirm the bug on 2.7

**Comment by ilya-fedin** [comment]
@Germano0 can't confirm
