### ISSUE TITLE
[Bug Report] Telegram Desktop on Ubuntu does not get the original filename when the "Save File As..." button is clicked

### ISSUE THREAD

**Issue by awesomelike** [telegramdesktop/tdesktop#10554]
### Steps to reproduce
1. For any file in the chat, click "Save File As..."
2. See the name of a file it is going to save

### Expected behaviour
It should automatically get the filename and file extension from the original file as it is sent in the chat. 

### Actual behaviour
It does not get the filename and file extension and makes it empty. It is annoying to write it manually.

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** 2.6.1

**Installation source (Linux Only)** - snap

**Used theme**: Tinted

<details><summary><b>Logs</b>:</summary>
Screenshots:

How the file looks like in the chat:
![image](https://user-images.githubusercontent.com/33417732/111467621-74162180-8746-11eb-9319-9bddd6aba0ab.png)

How it looks like on the save dialog:
![image](https://user-images.githubusercontent.com/33417732/111467749-a0ca3900-8746-11eb-9b6e-e34198b61535.png)

</details>

**Comment by ilya-fedin** [comment]
https://github.com/flatpak/xdg-desktop-portal-gtk/issues/191
