### ISSUE TITLE
[Feature Request] Toggle menu mouse-over hover behaviour in settings

### ISSUE THREAD

**Issue by rwilhelm** [telegramdesktop/tdesktop#10552]
### Is your feature request related to a problem?

Some menus open on mouse hover. This is very intrusive behavior for users who are used to different menu behaviour or have a different workflow. It is very distracting if you move your mouse and suddenly you get the list of emoticons or the other hamburger menu in the lower right corner. 

### Describe the solution you'd like

* Mouse-hover should optional/configurable (toggle on/off).

### Describe alternatives you've considered
* All (important) menus should have (configurable) keyboard shortcuts to reach them.

### Additional context
UIs should not behave intrusive. It is very similar to windows stealing current focus.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1333
