### ISSUE TITLE
Tray icon is dark instead of white

### ISSUE THREAD

**Issue by lyonelz96** [telegramdesktop/tdesktop#10556]
### Steps to reproduce
1. Launch telegram

### Expected behaviour
Telegram tray icon should be white

### Actual behaviour
Telegram tray icon is dark

### Configuration
**Operating system:**
Arch Linux x86_64
Window Manager: bspwm with polybar

**Version of Telegram Desktop:**
2.6.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Arch community package
https://archlinux.org/packages/community/x86_64/telegram-desktop/

**Used theme**:
According to neofetch:
Theme: Orchis-dark [GTK2/3]
Icons: Qogir-dark [GTK2/3]

### Screenshot
![image](https://user-images.githubusercontent.com/43832900/111526597-52606e80-8735-11eb-8e90-f588860d62bf.png)

I tried changing the icon theme and it's still dark. I haven't really changed anything significant from what I remember.

**Comment by ilya-fedin** [comment]
> Theme: Orchis-dark [GTK2/3]

This icon theme contains dark icon. This is a bug in your icon theme.

**Comment by ilya-fedin** [comment]
Probably you have set another icon theme for Qt applications? Check `QT_QPA_PLATFORMTHEME` variable?

**Comment by lyonelz96** [comment]
Mine is set to 'gnome'. What I don't understand is why this would be causing an issue now. I haven't really changed anything regarding the theme in a while and it was fine before. Just kinda happened randomly.  I'll experiment with the theme stuff later and report back.

**Comment by Aokromes** [comment]
i suggest you to download official package from desktop.telegram.org or from releases, from what i was told archlinux stoped to maintain distribution package.

**Comment by ilya-fedin** [comment]
> i suggest you to download official package from desktop.telegram.org or from releases, from what i was told archlinux stoped to maintain distribution package.

No, it's fedora&gentoo.

**Comment by ilya-fedin** [comment]
> Mine is set to 'gnome'.

Do you have QGnomePlatform installed? Do you have any tdesktop-related environments variables (`env | grep -e TDESKTOP -e DESKTOP_APP`) set?

**Comment by lyonelz96** [comment]
I have QGnomePlatform installed and no outputs on my console for `env | grep -e TDESKTOP -e DESKTOP_APP`

**Comment by ilya-fedin** [comment]
I can't reproduce even with your icon theme, sorry. Icon appears white.

**Comment by ilya-fedin** [comment]
>  I'll experiment with the theme stuff later and report back.

Have you done your experiments?

**Comment by lyonelz96** [comment]
> >  I'll experiment with the theme stuff later and report back.
> 
> Have you done your experiments?

Yeah!, so I tried messing around with themes and the icon changes but the color still stays dark unfortunately :(. Something might've broke it during an update. 

Seems to be my issue tho not telegrams.

**Comment by ilya-fedin** [comment]
You can try tdesktop from official website to exclude broken settings of system Qt

**Comment by lyonelz96** [comment]
> You can try tdesktop from official website to exclude broken settings of system Qt

Boom. I installed the `telegram-desktop-bin` package from the AUR instead, icon is white now!

**Comment by ilya-fedin** [comment]
Yeah, it contains the official binary from official website. So something is wrong with Qt settings, probably QT_QPA_PLATFORMTHEME/QT_STYLE_OVERRIDE plugins :thinking:

**Comment by Aokromes** [comment]
so, close?

**Comment by ilya-fedin** [comment]
> so, close?

yeah, it is an issue with system configuration

**Comment by Skaalgard** [comment]
I'm having the exact same issue in Linux Mint 20 Xfce, just since the last update. Tray icon is black (when it was previously the correct color) despite system icon settings. Using 2.7.1

**Comment by ilya-fedin** [comment]
@Skaalgard can't confirm
![изображение](https://user-images.githubusercontent.com/17829319/114337817-58354e00-9b41-11eb-8bd5-2bfbaec38ea8.png)

**Comment by Skaalgard** [comment]
I'm not sure why I'd go through the trouble of lying about this, but alright. This seems to be an area of contention whenever this issue is brought up.

![Screenshot_2021-04-11_22-52-48](https://user-images.githubusercontent.com/31973127/114338419-a7b35400-9b18-11eb-98b2-84e4666d6aa0.png)

![Screenshot_2021-04-11_22-53-08](https://user-images.githubusercontent.com/31973127/114338447-b26de900-9b18-11eb-9e4c-b640dfb54988.png)

![Screenshot_2021-04-11_22-52-48](https://user-images.githubusercontent.com/31973127/114338496-cb769a00-9b18-11eb-9917-af9c0685584e.png)

**Comment by Skaalgard** [comment]
Obviously, however, every DE is broken, apparently.

**Comment by ilya-fedin** [comment]
QT_QPA_PLATFORMTHEME value and installation source would be more valuable then neofetch

**Comment by ilya-fedin** [comment]
Ah, no, it's valuable, `Icons: ePapirus [GTK2], Mint-Y [GTK3]` shows the culprit

**Comment by Skaalgard** [comment]
Alright, so how does one fix this?

**Comment by Skaalgard** [comment]
And why did it work until last update?

**Comment by ilya-fedin** [comment]
I don't know why it did work, you haven't provide information I requested yet so I have no idea and this was just a luck since you system is definitely misconfigured.

**Comment by ilya-fedin** [comment]
> Alright, so how does one fix this?

Synchronize your toolkit settings (GTK2, GTK3, Qt).

**Comment by Skaalgard** [comment]
Can you point me in the right direction on how to do that? Searching around for "synchronize toolkit settings xfce" doesn't yield much.

**Comment by ilya-fedin** [comment]
> Can you point me in the right direction on how to do that?

I guess Xfce sets the settings only for gtk2. So you need manually change gtk3's settings.ini. For Qt you should check `QT_QPA_PLATFORMTHEME` value, it should point which tool you should use to configure Qt.

**Comment by Skaalgard** [comment]
In /etc/gtk-3.0?

**Comment by ilya-fedin** [comment]
~/.config/gtk-3.0

**Comment by Skaalgard** [comment]
There is no settings.ini file in this directory. Should I create one?

**Comment by ilya-fedin** [comment]
https://wiki.archlinux.org/index.php/GTK#Configuration

**Comment by etircopyh** [comment]
> There is no settings.ini file in this directory. Should I create one?

You should be more aware of the system you're using.

**Comment by Skaalgard** [comment]
> > There is no settings.ini file in this directory. Should I create one?
> 
> You should be more aware of the system you're using.

Thank you for this novel, productive, and helpful reply. Time well spent.

**Comment by Skaalgard** [comment]
> https://wiki.archlinux.org/index.php/GTK#Configuration

Thank you, this was very helpful. I was able to synchronize gtk2/3 with this. Tray icon is still dark, but we'll see if this persists after a reboot.

**Comment by ilya-fedin** [comment]
It can't read the changes on the fly, but should read the new configuration if restart the application.

**Comment by Skaalgard** [comment]
I restarted and tray icon is still dark. I'm still poking around to see what else I can do.

**Comment by ilya-fedin** [comment]
It would be a way easier to find the cause if you show QT_QPA_PLATFORMTHEME value and say where you installed tdesktop from

**Comment by Skaalgard** [comment]
I installed it from my distro repository. Installing the official binary from the website caused other display issues.

I'm looking around to find out how to get the value of this to you.

**Comment by ilya-fedin** [comment]
> I installed it from my distro repository.

It couldn't be the true since Mint 20 is based on Ubuntu 20.04 (Focal) and it has only 2.0.1 and 2.1.7: https://packages.ubuntu.com/focal/telegram-desktop https://packages.ubuntu.com/focal-updates/telegram-desktop

> Installing the official binary from the website caused other display issues.

Which display issues?

**Comment by Skaalgard** [comment]
It's a flatpak, which is included in my distro software repository.

The official binary had issues with icons not following system theme at all, cursors changing to not follow theme when over Telegram window, etc. The tray icon issue is the only problem i've had with the flatpak and even then only after the latest update.

**Comment by ilya-fedin** [comment]
I think it's worth to try now, when you fixed gtk3 settings. And you still haven't shown `QT_QPA_PLATFORMTHEME` value. :confused:

**Comment by Skaalgard** [comment]
I am unsure how to find this for you. I've been looking it up. I didn't want to ask yet another stupid question.

**Comment by ilya-fedin** [comment]
>  am unsure how to find this for you.

`echo $QT_QPA_PLATFORMTHEME`

**Comment by ilya-fedin** [comment]
>  I didn't want to ask yet another stupid question.

it's better than ignoring questions...

**Comment by Skaalgard** [comment]
The value is qt5ct

**Comment by Skaalgard** [comment]
> I installed it from my distro repository. Installing the official binary from the website caused other display issues.
> 
> I'm looking around to find out how to get the value of this to you.

**Comment by ilya-fedin** [comment]
> The value is qt5ct

So run qt5ct from application menu (or from terminal) and configure it

**Comment by ilya-fedin** [comment]
Official binary can read qt5ct settings, but flatpak doesn't, so it reads settings from gtk3 most liekly

**Comment by Skaalgard** [comment]
In qt5ct, it's set to "gtk2," so I don't know what the issue is there.

**Comment by ilya-fedin** [comment]
But flatpak packages can't read gtk settings from configs due to sandbox, gtk stylizing in flatpak works only when any X Settings daemon is running (like gnome-settings-daemon, mate-settings-daemon, [xsettingsd](https://github.com/derat/xsettingsd/wiki))

**Comment by ilya-fedin** [comment]
> In qt5ct, it's set to "gtk2," so I don't know what the issue is there.

gtk2 is a widget theme, while you need to check whether icon theme is chosen right (it's in a separate tab in the configurator)

**Comment by Skaalgard** [comment]
With the official binary, the icon is a blue Telegram logo and it doesn't follow the icon theme at all. I'd frankly rather deal with the dark icon. I'll let you know if the problem is corrected after a reboot.

**Comment by ilya-fedin** [comment]
> With the official binary, the icon is a blue Telegram logo and it doesn't follow the icon theme at all.

It should be the right one when you choose the right icon theme in qt5ct

**Comment by Skaalgard** [comment]
The correct icon theme had been selected in qt5ct, even before I checked just now. I don't know what broke this in the last update but that is the _only_ variable here that has changed.

**Comment by ilya-fedin** [comment]
> The correct icon theme had been selected in qt5ct

Are you sure? :thinking: tdesktop writes to debug log which icon theme settings it gets from Qt to debug logs (they could be activated with `debugmode` cheat code that you should enter in tdesktop settings blindly, without any input field), they're placed in `~/.local/share/TelegramDesktop/DebugLogs` in the case of official binary.

**Comment by Skaalgard** [comment]
When I opened the settings, it was already selected.

**Comment by ilya-fedin** [comment]
> When I opened the settings, it was already selected.

I hope you checked the separate tab with the list of icon themes and don't talk about the `gtk2` value?

**Comment by Skaalgard** [comment]
Yes, I checked the icon tab.

**Comment by ilya-fedin** [comment]
What if you icon theme doesn't have icons for tdesktop and flatpak just gets from random one?

**Comment by ilya-fedin** [comment]
But if it's ePapirus then it should... IMHO it's worth to check debug logs

**Comment by ilya-fedin** [comment]
Also it's worth to check wheter you have `QGnomePlatform` installed with `flatpak list`. It probably does some palette tricks since the original reporter also had problems with it (official binary doesn't support QGnomePlatform, so it's stopped when he switched to official binary).

**Comment by ilya-fedin** [comment]
If `QGnomePlatform` is the culprit, this can explain why it wasn't happen previously: there was a call to `QApplication::setDesktopSettingsAware(false);` for gtk-based environments. This was an outdated workaround to prevent crashes that don't happen anymore. So I removed it and tdesktop started to use QGnomePlatform like other Qt applications while previous it didn't (and so wasn't affected by its bugs). So this seem to be a bug in QGnomePlatform, it recolors the icon for some reason.
