### ISSUE TITLE
Diferent files with same names

### ISSUE THREAD

**Issue by adrian13579** [telegramdesktop/tdesktop#10567]
### Steps to reproduce
1.  Upload a file ( example: `a.txt` )
2.  Upload a second file with the same name but different content

### Expected behavior
Different files with same name

### Actual behavior
When the last file is downloaded, it is actually the old one.

### Configuration
**Operating system:**
Ubuntu 20.04
**Version of Telegram Desktop:**
2.6.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
snap on Ubuntu 20.04
**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
1. Created two test.txt files. The first in home folder, the second in Documents folder.
2. Drag'n'Dropped the first file to Saved messages
3. Drag'n'Dropped the second file to Saved messages
4. Opened both files
Result: they are different
