### ISSUE TITLE
Telegram does not respect Always on Visible Workspace anymore

### ISSUE THREAD

**Issue by lucaszanella** [telegramdesktop/tdesktop#10560]
It always worked, but now even if I mark it "Alwyas on visible workspace", it simply won't work after some minutes. I click on the notification and it goes to the other workspace. Just works rigth after I mark it. But then after minutes of usage it simply unmarks itself. Maybe the window regenerates somehow, I don't know

Ubuntu 20.04 

telegram 2.6.1, installed via snap

**Comment by ilya-fedin** [comment]
#10461
