### ISSUE TITLE
[Feature Request] Add chats to folder using Drag&Drop

### ISSUE THREAD

**Issue by taha-ghadirian** [telegramdesktop/tdesktop#10561]
### Is your feature request related to a problem?
When I want to add a chat to a folder, I should go to "edit folder setting" then select folder and search chat name then add it. 
But what if I cant search group name? For example because of the un regular font in Chat name.
The best solution is using drag&drop.

### Describe the solution you'd like
Add chats to folder by drag&drop chat.

**Comment by ilya-fedin** [comment]
#7463
