### ISSUE TITLE
No inline bots suggestions

### ISSUE THREAD

**Issue by AlexWayfer** [telegramdesktop/tdesktop#10576]
Hello.

#6270 is still an issue for clean installation, version 2.6.1 (I'm sure 2.7 has nothing dealing with it), Windows 10 x64.

**Comment by AlexWayfer** [comment]
It still an issue on Linux after update to version 3.1. No suggestion until I enter a complete correct bot nickname.

**Comment by AlexWayfer** [comment]
I believe it's still an issue of a local cache, I've seen no changes about it.

**Comment by BloodShadow174** [comment]
The problem is relevant, but the reason why the recommendations disappear is unknown. This started around the end of 2020 and since then the recommendations have disappeared from time to time.
