### ISSUE TITLE
[Question] Linux - Telegram Desktop - Dual Instance ( 2 Numbers )

### ISSUE THREAD

**Issue by marcoczen** [telegramdesktop/tdesktop#10571]
Guys,

Telegram Desktop is running fine on a Linux box. Just need it for another number.
Is there a way to get 2 separate instances ( 2 separate  windows ) running and keep each independent of the other ?

Thanks.

**Comment by RememberTheAir** [comment]
You can use the same binary and start a new instance by using the `-workdir` command:

```bash
Telegram -workdir /path/to/some/directory/where/to/store/session/data
```

This way you can run more than one parallel instance of Telegram Desktop

**Comment by ilya-fedin** [comment]
> You can use the same binary and start a new instance by using the `-workdir` command:

This is not a good way, this will mess desktop shortcuts and etc. Appropriate way to that is to copy the binary and create `TelegramForcePortable` folder along the binary.

**Comment by marcoczen** [comment]
> You can use the same binary and start a new instance by using the `-workdir` command:
> 
> ```shell
> Telegram -workdir /path/to/some/directory/where/to/store/session/data
> ```
> 
> This way you can run more than one parallel instance of Telegram Desktop


Noted .. when i tried this , it just brought up the first instance ...

**Comment by marcoczen** [comment]
> > You can use the same binary and start a new instance by using the `-workdir` command:
> 
> This is not a good way, this will mess desktop shortcuts and etc. The appropriate way to that is to copy the binary and create `TelegramForcePortable` folder along the binary.

Is there a documentation link or wiki link where i can find out how to do the above ?

**Comment by marcoczen** [comment]
Hi @Aokromes  - since you closed this issue, then you must know where i can get information on how to get dual instances of Telegram Desktop. Some light would be appreciated.

**Comment by ilya-fedin** [comment]
> Noted .. when i tried this , it just brought up the first instance ...

the directory you specifying should exist, or it will silently fallback to the default one

> Is there a documentation link or wiki link where i can find out how to do the above ?

this is undocumented. But I don't understand what do you mean by "how", you don't know how to copy a file or how to create a directory?

**Comment by marcoczen** [comment]
> > Noted .. when i tried this , it just brought up the first instance ...
> 
> the directory you specifying should exist, or it will silently fallback to the default one

Ok. Understood. 

> 
> > Is there a documentation link or wiki link where i can find out how to do the above ?
> 
> this is undocumented. But I don't understand what do you mean by "how", you don't know how to copy a file or how to create a directory?

How -> How to properly run 2 instances ( 2 numbers )  of Telegram Desktop ( as per title ) and also the method you mentioned of copying the binary and  creating TelegramForcePortable.

**Comment by ilya-fedin** [comment]
> How to properly run 2 instances ( 2 numbers ) of Telegram Desktop ( as per title )



> copy the binary and create `TelegramForcePortable` folder along the binary.

it the proper way

**Comment by marcoczen** [comment]
> > How to properly run 2 instances ( 2 numbers ) of Telegram Desktop ( as per title )
> 
> > copy the binary and create `TelegramForcePortable` folder along the binary.
> 
> it the proper way

Ok. I get that it is the proper way. Thank you.
Could u point me to a link that talks about how to create TelegramForcePortable ?
Is it just a directory ? 

So...
mkdir TelegramForcePortable ?

**Comment by RememberTheAir** [comment]
> mkdir TelegramForcePortable

Yes, in the same directory of the app binary

**Comment by ilya-fedin** [comment]
> Could u point me to a link that talks about how to create TelegramForcePortable ?

No link, sorry. Just create the directory in the same directory the binary is placed.

**Comment by marcoczen** [comment]
> > Could u point me to a link that talks about how to create TelegramForcePortable ?
> 
> No link, sorry. Just create the directory in the same directory the binary is placed.

So .. there will be 2 folders ( one for each number ) and in the second folder  ( which also  contains the Telegram / Update binaries, i have to create a folder called Telegram Force Portable ?

And i just launch both binaries by clicking on them ? Not necessary to pass them any options etc ?

**Comment by ilya-fedin** [comment]
yeah

**Comment by marcoczen** [comment]
> yeah, everything is right

Thanks... Are you one of the Telegram Desktop Devs ? 
How do you know so much info ? Thanks once again ..

**Comment by ilya-fedin** [comment]
>  Are you one of the Telegram Desktop Devs ?

No, i'm just a contributor

> How do you know so much info ?

by looking the code and asking preston...

**Comment by marcoczen** [comment]
> > How do you know so much info ?
> 
> by looking the code and asking preston...

Very impressive... THANKS !
Closed.
