### ISSUE TITLE
Update error!

### ISSUE THREAD

**Issue by warburtonn** [telegramdesktop/tdesktop#10575]
### Steps to reproduce
1. Click Update Button In DesktopTelegram Client
2. Wait restart DesktopTelegram
3. Get Update error!
![изображение](https://user-images.githubusercontent.com/23268708/111851417-be043080-891b-11eb-80ce-c81195893d08.png)

### Expected behaviour
After clicking on the Update button in Desktop Telegram I expected restart client in latest updated version
### Actual behaviour
After clicking on the Update button, I got an error
**Update error!
Failed to update Telegram :(
\path_to_desctop_telegram_exe is not accessible.**

### Configuration
**Operating system:**
Windows 10 Pro x64
**Version of Telegram Desktop:**
Telegram Desktop version 2.6.1

**Used theme**:
Default theme
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)

</details>

**Comment by Aokromes** [comment]
not telegram bug instead windows bug, restart windows and start telegram.
