### ISSUE TITLE
Wrong message direction as a sender

### ISSUE THREAD

**Issue by rafoolin** [telegramdesktop/tdesktop#10579]
### Expected behaviour
In the past, as a sender of messages, my own messages used to align on the right and others on the left.

### Actual behaviour
Any message that I send in any chat or group, it aligns `left`, used to align `right`, but when I pin the `emoji sidebar`, it aligns correctly.

### Configuration
**Operating system:** Manjaro Linux 
- KDE Plasma Version: 5.21.2 
- KDE Frameworks Version: 5.79.0 
- Qt Version: 5.15.2
- Kernel Version: 5.9.16-1-MANJARO
- OS Type: 64-bit
- Graphics Platform: X11

**Version of Telegram Desktop:** v2.7 19.03.21

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
snap
**Used theme**:  Night Mode - Tinted
### Screenshots

With Emoji sidebar:
![side_bar](https://user-images.githubusercontent.com/54066251/111870282-09522980-8984-11eb-99e8-6d5deeb49e98.png)

Without Emoji sidebar:
![no_sidebar](https://user-images.githubusercontent.com/54066251/111870277-022b1b80-8984-11eb-93b7-e1e69fee9485.png)

**Comment by Aokromes** [comment]
disable adaptative layout.
