### ISSUE TITLE
context menu en worng screen

### ISSUE THREAD

**Issue by rsanjuan87** [telegramdesktop/tdesktop#10573]
I use 2 screen, when I do a rigth click on a message, the context menu shows in first screen. even if I have setted the second as my main screen, and telegram app is on second screen
MacOS Catalina 10.15.7

**Comment by 23rd** [comment]
Please provide a current client version of Telegram you have.

**Comment by rsanjuan87** [comment]
2.6.1

**Comment by rsanjuan87** [comment]
![imagen](https://user-images.githubusercontent.com/25087943/111799823-c029a900-88a1-11eb-8ff0-85209321d57a.png)

**Comment by ilya-fedin** [comment]
#7099

**Comment by rsanjuan87** [comment]
> #7099

oh! so no solution?

**Comment by rsanjuan87** [comment]
solved on 2.7
thanks !!! A LOT!!

**Comment by ilya-fedin** [comment]
Appeared on its own and solved on its own? :thinking:

**Comment by rsanjuan87** [comment]
> Appeared on its own and solved on its own? 🤔

update and it´s solved
