### ISSUE TITLE
[Feature Request] 175% interface scale

### ISSUE THREAD

**Issue by tykazzz** [telegramdesktop/tdesktop#10588]
I just really need it
![screenshot](https://user-images.githubusercontent.com/37346583/111908454-9fa44f00-8a59-11eb-8062-611ea902e0a7.png)
200% is too much and 150% is not enough

**Comment by NotStatilko** [comment]
You can set custom scale with keyword argument.

For example on Linux: `Telegram/Telegram -scale 175`

**Comment by tykazzz** [comment]
Thank!
