### ISSUE TITLE
Telegram restarted at wrong window position

### ISSUE THREAD

**Issue by arisudesu** [telegramdesktop/tdesktop#10587]
I am using Telegram on Windows with taskbar pinned to top, and everytime I restart Telegram, it's window is offset to the top. This is very much annoying because I can't access window controls to move it down.

P.S. Please. Just fix it. I constantly see apps mishandling top taskbar when considering window position, This is really annoying behavior. Don't just assume everyone uses default taskbar placement.

Before restart:
![изображение](https://user-images.githubusercontent.com/6342849/111902280-cceb0000-8a4d-11eb-9368-969f8bbb6ac5.png)

After restart window is placed here - can't access titlebar and search:
![изображение](https://user-images.githubusercontent.com/6342849/111902296-eab86500-8a4d-11eb-8ba0-ddb3c54f66bf.png)

### Steps to reproduce
1. Pin Windows taskbar to top
2. Move telegram close to taskbar
3. Restart it

### Expected behaviour
Telegram window is in the same position after restart

### Actual behaviour
Telegram window position is above previous

### Configuration
**Operating system:** Windows 10 20H2

**Version of Telegram Desktop:** 2.7.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: -

**Used theme**: -

**Comment by ilya-fedin** [comment]
#1189
