### ISSUE TITLE
Cant't create group from

### ISSUE THREAD

**Issue by Redee** [telegramdesktop/tdesktop#1058]
Can't create group at WinXP sp3 - from me and one man.
But from me and two men its ok.

At win7 its ok - from me and one man.

Need else provide standalone group from only group creator.

**Comment by auchri** [comment]
A group with 2 people makes no sense.
But you can create a group with 3 people and remove one.

**Comment by telegramdesktop** [comment]
They work the same in WinXP and Win7, if you choose only one person in the group create box, you just open conversation with him, if you choose two users (one of them can be yourself, if you have yourself in your contacts list), then it will create the group.
