### ISSUE TITLE
Night mode doesn't sync with linux

### ISSUE THREAD

**Issue by l0drex** [telegramdesktop/tdesktop#10595]
### Steps to reproduce
1. Select a light color scheme.
2. Start telegram.
3. Activate the option to sync night mode with system colors.
4. Change the system colors to a dark color scheme.

### Expected behaviour
The theme in telegram should now use dark colors.

### Actual behaviour
Nothing happens. This also happens the other way around (starting with dark color scheme, then changing to a light scheme). The theme only changes when telegram is restarted.

### Configuration
**Operating system:** Linux (Manjaro with KDE Plasma)

**Version of Telegram Desktop:** 2.6.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Pacman

**Used theme**: Default with custom colors

**Comment by ilya-fedin** [comment]
You probably should install xsettingsd

**Comment by l0drex** [comment]
> You probably should install xsettingsd

I installed it but dark mode still doesn't change when system theme changes.

**Comment by Aokromes** [comment]
try downloading 2.7.1 from releases tab or desktop.telegram.org

**Comment by l0drex** [comment]
Output when running from command line is:

```
** (process:23994): WARNING **: 15:42:30.844: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
** Message: 15:42:30.845: This can be ignored by setting DESKTOP_APP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
** Message: 15:42:30.845: GTK integration can be disabled by setting DESKTOP_APP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to some features being unavailable.

(process:23994): Telegram-WARNING **: 15:42:30.846: Application was built without embedded fonts, this may lead to font issues.
Gtk-Message: 15:42:31.181: Failed to load module "appmenu-gtk-module"
[ALSOFT] (EE) Failed to set real-time priority for thread: Die Operation ist nicht erlaubt (1)
error: : cannot open
error: : cannot open
error: : cannot open
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
```


There is also currently a problem with KDE Plasma when changing the theme:

```
QDBusConnection: error: could not send signal to service "" path "//home/l0drex/.kde4/share/config/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/l0drex/.kde4/share/config/kdeglobals
```
Could that be the problem?

**Comment by ilya-fedin** [comment]
> I installed it but dark mode still doesn't change when system theme changes.

Have you relogined after installing?

**Comment by ilya-fedin** [comment]
> Could that be the problem?

no, tdesktop checks gtk theme name and enables dark mode when it contains `-dark`.

**Comment by ilya-fedin** [comment]
check if the settings actually exposed via XSettings protocol by `dump_xsettings`

**Comment by ilya-fedin** [comment]
so Telegram can't see whether you activated dark mode system-wide. You should change the theme in order to activate night mode in telegram.

**Comment by l0drex** [comment]
The thing is that the theme changes correctly when I restart telegram completely :thinking:

**Comment by l0drex** [comment]
Light mode:
```
Gtk/ButtonImages 1
Gtk/CursorThemeName "breeze_cursors"
Gtk/CursorThemeSize 24
Gtk/DecorationLayout "icon:minimize,maximize,close"
Gtk/EnableAnimations 1
Gtk/FontName "Noto Sans,  10"
Gtk/MenuImages 1
Gtk/PrimaryButtonWarpsSlider 0
Gtk/ToolbarStyle 3
Net/IconThemeName "breeze"
Net/ThemeName "Breeze"
```

Dark mode:
```
Gtk/ButtonImages 1
Gtk/CursorThemeName "breeze_cursors"
Gtk/CursorThemeSize 24
Gtk/DecorationLayout "icon:minimize,maximize,close"
Gtk/EnableAnimations 1
Gtk/FontName "Noto Sans,  10"
Gtk/MenuImages 1
Gtk/PrimaryButtonWarpsSlider 0
Gtk/ToolbarStyle 3
Net/IconThemeName "breeze-dark"
Net/ThemeName "Breeze"
```

So the icon theme name actually changes, but not the color theme.

**Comment by ilya-fedin** [comment]
Maybe plasma changes gtk-application-prefer-dark-theme, but it is not possible to watch for it changes in runtime since it isn't exposed via xsettings. I'm afraid we can do nothing without improvements from Plasma side, so that they will change theme name.

**Comment by l0drex** [comment]
As I'm switching themes right now I realized a few things:
- After installing `xsettingsd`, GitHub in Firefox sometimes switches to a dark mode when I switch to a dark theme. So the `browser-prefers-dark-theme` value must have changed. However, that doesn't happen every time.
- On one occasion, `dump_xsettings` did not output anything. However, I can't replicate that.

**Comment by l0drex** [comment]
> Maybe plasma changes gtk-application-prefer-dark-theme, but it is not possible to watch for it changes in runtime since it isn't exposed via xsettings. I'm afraid we can do nothing without improvements from Plasma side, so that they will change theme name.

Could you maybe include a check for the icon theme name?

**Comment by ilya-fedin** [comment]
> Could you maybe include a check for the icon theme name?

No, there are a high chance this will lead to misbehavior for some users. I can imagine someusers using dark icons with light theme.

**Comment by ilya-fedin** [comment]
>     * So the `browser-prefers-dark-theme` value must have changed.

I have no idea how they getting the change. If you will find how, we can adapt that to tdesktop.

**Comment by l0drex** [comment]
> No, there are a high chance this will lead to misbehavior for some users. I can imagine some users using dark icons with light theme.

Good point. I opened a bug report over at [bugs.kde.org](https://bugs.kde.org/show_bug.cgi?id=434838).

**Comment by Aokromes** [comment]
so, 3rd party bug?

**Comment by Pointedstick** [comment]
And I closed as a downstream bug. :)

In KDE, we have a GTK theme that named "Breeze" that is color-scheme aware: if you set a dark KDE color scheme, it becomes dark automatically. If you set a zany custom purple color scheme or whatever, it uses that too. So I'm afraid there is no separate "dark" GTK theme whose name you can key off of. What you can do instead is also look for the KDE color scheme name in the user's `.kdeglobals` file:

```
grep ColorScheme ~/.config/kdeglobals 
151:ColorScheme=BreezeDark
```

And you can look for the word "Dark" in there if you really need to.

Please use the API instead of a `grep` of course, because there can be multiple entries there, and you want the one in the `[General]` group

And of course simply using the colors from the QPalette directly would be the preferred solution given that Telegram is a Qt app, but I understand that we can't always have nice things. :)

**Comment by ilya-fedin** [comment]
> Please use the API instead of a `grep` of course

Where's that API is documented? :thinking: 

> And of course simply using the colors from the QPalette directly would be the preferred solution given that Telegram is a Qt app

I guess tdesktop doesn't have KDE colors in QPalette since it requires KDE's platformtheme plugin that is impossible to distribute with tdesktop due to a lot of dependencies it has.

**Comment by gikari** [comment]
> And of course simply using the colors from the QPalette directly would be the preferred solution given that Telegram is a Qt app, but I understand that we can't always have nice things. :)

Alternatively the heuristic can be used to determine KDE color scheme's darkness (this is how we set `gtk-application-prefer-dark-theme`):
```
bool ConfigValueProvider::preferDarkTheme() const
{
    KConfigGroup colorsConfigGroup = kdeglobalsConfig->group(QStringLiteral("Colors:Window"));
    QColor windowBackgroundColor = colorsConfigGroup.readEntry(QStringLiteral("BackgroundNormal"), QColor(239, 240, 241));
    const int windowBackgroundGray = qGray(windowBackgroundColor.rgb());

    return windowBackgroundGray < 192;
}
```

**Comment by ilya-fedin** [comment]
Just tried to add such a code
```
	if (DesktopEnvironment::IsKDE()) {
		return qGray(QPalette().color(QPalette::Window).rgb()) < 192;
	}
```
And it seem to work thank to QKdeTheme from Qt's genericunixthemes. But it still applies only after restart, how to subscribe to palette change? :thinking:

**Comment by ilya-fedin** [comment]
So paletteChanged is at QGuiApplication while I looked at QApplication. Looks like Qt's QKdeTheme doesn't support looking for theme changes on the fly since connecting to paletteChanged doesn't help sadly.

**Comment by ilya-fedin** [comment]
Looks like I got something with portals (god, save portals!)...
