### ISSUE TITLE
Telegram moves from workspaces when clicking notifications in GNOME

### ISSUE THREAD

**Issue by 1eldiego** [telegramdesktop/tdesktop#10594]
Whatever workspace you are, Telegram just moves there and get focused when you click a notification. I have to move it back everytime with shift+ctrl+alt+arrow. Or dont click the notification at all and change workspace and focus Telegram manually. I tried enabling/disabling the "Use native notifications" and "Draw attention to the window" options.

Other apps' notifications works just right (such as MS Teams).

### Steps to reproduce
1. Open Telegram in workspace 1 (among some other apps, so the workspace stays)
2. Go to workspace 2
3. Receive a Telegram notification
4. Click the notification

### Expected behaviour
You should be moved to workspace 1 and focus Telegram

### Actual behaviour
Telegram changes to workspace 2 and get focused there

### Configuration
**Operating system:** Arch Linux (GNOME 3.38.4)

**Version of Telegram Desktop:** 2.6.1

**Installation source (Linux Only):**
pacman -S telegram-desktop

**Used theme**: default (Adwaita I think)

**Comment by Aokromes** [comment]
update to 2.7.1
