### ISSUE TITLE
[Feature Request] Set the default theme to match the system theme

### ISSUE THREAD

**Issue by rakleed** [telegramdesktop/tdesktop#10596]
### Is your feature request related to a problem?
If a dark theme is used in my system and in all applications, then when I start Telegram for the first time, a light theme appears, which is very unpleasant for the eyes (especially at night and in dark rooms).

### Describe the solution you'd like
Set the default application theme to match the system theme.

### Describe alternatives you've considered
Prompt when you first start the application to select the desired theme.

### Additional context
In the vast majority of applications, the default setting is to match the application theme to the system theme.

**Comment by l0drex** [comment]
There is already a settings for that:
- Settings
- Chat Settings
- Automatic night mode
- Sync with system colors

(Actual names of these settings might be a little different)

**Comment by rakleed** [comment]
@Aokromes why did you close the issue? I ask you to make the default match of the application theme to the system theme. And now the default theme is light.
