### ISSUE TITLE
[Feature Request] Ability to disable account self-destruction

### ISSUE THREAD

**Issue by Tegnio** [telegramdesktop/tdesktop#10590]
It would be nice if I could disable account self-destruction feature in Telegram settings by clicking on "Turn Off" button, which would appear below all the buttons shown on a screenshot.
![Screenshot from 2021-03-21 19-18-29](https://user-images.githubusercontent.com/73775612/111912511-02f2a900-8a7b-11eb-91b1-bd94e138cf90.png)

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
