### ISSUE TITLE
[Feature Request] Search in comments view

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#10598]
### Is your feature request related to a problem?
No, this is rather a missing feature: the mobile apps offer an option to search for messages in the comments view

### Describe the solution you'd like
A search icon plus the CTRL+F keyboard shortcut

### Describe alternatives you've considered
None

***

I tried to look for similar issues because I'm quite surprised nobody asked for this yet, but I couldn't find any

**Comment by ilya-fedin** [comment]
#8716

**Comment by ilya-fedin** [comment]
Just remember that comments also called discussion ^_^

**Comment by RememberTheAir** [comment]
@ilya-fedin right, didn't search for "discussion". Thanks
