### ISSUE TITLE
[Feature Request] Align Telegram Desktop icon with new Telegram icon on macos

### ISSUE THREAD

**Issue by Marc66** [telegramdesktop/tdesktop#10602]
Recently, a new Big Sur compatible icon (square with rounded corners) was introduced in the Mac App Store Telegram app but the Telegram Desktop icon is still the round one.

This request is to use the same icon in both apps on macos

I tried changing the icon of my Telegram Desktop app with the "new" one and it works fine except when the app is open; it reverts to the round icon

**Comment by Aokromes** [comment]
icon was updated to what marketing team wanted.
