### ISSUE TITLE
tdesktop badly validates some URL's

### ISSUE THREAD

**Issue by evgenymarkov** [telegramdesktop/tdesktop#1061]
For example: https://play.rust-lang.org/?code=fn%20main%28%29%20{%0A%20%20%20%20%2F%2F!%20The%20%60adder%60%20crate%20provides%20functions%20that%20add%20numbers%20to%20other%20numbers.%0A%20%20%20%20%2F%2F!%0A%20%20%20%20%2F%2F!%20%23%20Examples%0A%20%20%20%20%2F%2F!%0A%20%20%20%20%2F%2F!%20%60%60%60%0A%20%20%20%20%2F%2F!%20assert_eq!%284%2C%20adder%3A%3Aadd_two%282%29%29%3B%0A%20%20%20%20%2F%2F!%20%60%60%60%0A%20%20%20%20%0A%20%20%20%20%2F%2F%2F%20This%20function%20adds%20two%20to%20its%20argument.%0A%20%20%20%20%2F%2F%2F%0A%20%20%20%20%2F%2F%2F%20%23%20Examples%0A%20%20%20%20%2F%2F%2F%0A%20%20%20%20%2F%2F%2F%20%60%60%60%0A%20%20%20%20%2F%2F%2F%20use%20adder%3A%3Aadd_two%3B%0A%20%20%20%20%2F%2F%2F%0A%20%20%20%20%2F%2F%2F%20assert_eq!%284%2C%20add_two%282%29%29%3B%0A%20%20%20%20%2F%2F%2F%20%60%60%60%0A%20%20%20%20pub%20fn%20add_two%28a%3A%20i32%29%20-%3E%20i32%20{%0A%20%20%20%20%20%20%20%20a%20%2B%202%0A%20%20%20%20}%0A%20%20%20%20%0A%20%20%20%20%23[cfg%28test%29]%0A%20%20%20%20mod%20tests%20{%0A%20%20%20%20%20%20%20%20use%20super%3A%3A*%3B%0A%20%20%20%20%0A%20%20%20%20%20%20%20%20%23[test]%0A%20%20%20%20%20%20%20%20fn%20it_works%28%29%20{%0A%20%20%20%20%20%20%20%20%20%20%20%20assert_eq!%284%2C%20add_two%282%29%29%3B%0A%20%20%20%20%20%20%20%20}%0A%20%20%20%20}%0A%20%20%20%20%0A}
Yes, it is valid link. When i sent to my friend this link, i saw follows:
![screenshot_2015-09-04_18-33-25](https://cloud.githubusercontent.com/assets/6116627/9685022/ec1500d0-5334-11e5-966c-7ebf0b1ca0d5.png)
But my friend saw:
![photo_2015-09-04_18-44-53](https://cloud.githubusercontent.com/assets/6116627/9685048/10deb8ca-5335-11e5-8bf7-dd9157353b77.jpg)

**Comment by telegramdesktop** [comment]
Links are parsed on server now, so it is a server-side issue (that full link is not clickable). But the display bug in the first screenshot (on outgoing message) is mine and I hope I will fix that in the next release.

**Comment by auchri** [comment]
@evgenymarkov The link you posted works fine for me
![image](https://cloud.githubusercontent.com/assets/5092164/9686328/c1d478ca-5323-11e5-94bb-cf662a548a46.png)

**Comment by evgenymarkov** [comment]
I send this message from two computers with different OS(linux, win) now and I see the same thing. 
![screenshot_2015-09-04_20-31-24](https://cloud.githubusercontent.com/assets/6116627/9687666/048af03e-5344-11e5-9e76-2e37e96a0f38.png)
I've seen issues with parsing links earlier and I might be able to find them if it needed.

**Comment by auchri** [comment]
Please send me the link: https://telegram.me/Auroratic

**Comment by auchri** [comment]
@telegramdesktop This happens only with linux, with windows it works

**Windows:**
![image](https://cloud.githubusercontent.com/assets/5092164/9688177/dfd44b8e-532d-11e5-87d2-326a1c113e68.png)

**Linux (Ubuntu):**
![image](https://cloud.githubusercontent.com/assets/5092164/9688194/f40a3dca-532d-11e5-8470-c53c601a6fbe.png)

So it seems there is an encoding problem with linux

**Comment by telegramdesktop** [comment]
Could it be that you tried different app versions from Windows and from Linux?

**Comment by auchri** [comment]
@telegramdesktop Nop. But what I said is false.

It works fine when copying from Google Chrome and it fails with firefox

**Comment by telegramdesktop** [comment]
Should be fixed in 0.8.56 (display, not link parse, links are parsed on server, but I've reported that case to server-side developer).
