### ISSUE TITLE
URL with IP adress

### ISSUE THREAD

**Issue by hrach** [telegramdesktop/tdesktop#1064]
If I send this url `http://89.185.254.8/nextras/orm/master/index.html`, the preview? functionality transforms url to `http://89.185.0.254.8/nextras/orm/master/index.html` and make only a part clickable. The clickable part directs to wrong IP. However, copying such bad modified url copies the correct one. See attached screenshot.
![screen_telegram](https://cloud.githubusercontent.com/assets/284263/9690167/fb704908-533a-11e5-8e39-87fbdf189092.JPG)

**Comment by auchri** [comment]
Note: It's only displayed false, but send correctly (appears right in the android app)

**Comment by telegramdesktop** [comment]
Should be fixed.
