### ISSUE TITLE
Is there a way to display unread message only?

### ISSUE THREAD

**Issue by camagenta** [telegramdesktop/tdesktop#1067]
when some one using telegram with many-many group, sometimes the unread message gradually increased when he can't read all the message. for some people like me, the unread counter a bit annoying :)

So, I'm asking is there a way to short unread message only?

I think this feature is available in gmail using label **unread**

**Comment by auchri** [comment]
Your description is very hard to read. You you want to display only unread messages?

**Comment by camagenta** [comment]
Sorry @auchri for my bad english.

Yes. I just want to display only unread message.

Can we do it in telegram?

**Comment by auchri** [comment]
Yes, but if you get new messages, the chat stays at the first unread message.

Whats the use case for this feature?

**Comment by camagenta** [comment]
just like an email @auchri. sometimes we skip a message and it still counted as unread message.

that's a bit annoying to see an unread counted message. 
so for quickest way, i think we sort unread massage. and open it one by one.

maybe. marked all as read is needed.

**Comment by Aokromes** [comment]
I think this is suplicate of this https://github.com/telegramdesktop/tdesktop/issues/775 :)

**Comment by auchri** [comment]
Yes maybe, I'm not sure..

**Comment by camagenta** [comment]
Hmm, #775 is different with what I mean. But that issue is alot better I think hehe.

Maybe I should give this idea an ilustration.

Too bad, I can't attach a picture using mobile. Insya Allah on Monday I'll upload the screen shoot.

Example case
I subs on 5 telegram bots, more than 10 groups, and lots personal chat. When I'm at work, I can't read all unread message at that time. I must prioritize what I've to read. So the effect is some unread message is still unread and going down with  more active conversation

When I going home, I ussually read the rest of unread message. But the problem is some unread message is not at the top of telegram conversation list. So I say about this unread sorting ideas.

Hehe.. Sorry for my bad english :)

**Comment by auchri** [comment]
Ah I see...so you wanna only display conversations, which have unread messages, in the left column.
All other conversations should be hidden from the left column.

Is that what you trying to say? :)

**Comment by camagenta** [comment]
nah, Alhamdulillah..
you got my point.
what I really want to do is
type label:unread (or some other command)
the left column is just display the conversation with the unread message


can we do that?

**Comment by poooch** [comment]
auchri, so what's the news about it?

**Comment by capiscuas** [comment]
I also would like this feature, maybe related to #3957 . a way to sort the chats by those that still have pending messages to see.

**Comment by AlexanderKochetkov** [comment]
Maybe add an option to "Show unread first" in contact list.

**Comment by capiscuas** [comment]
It could have some time delay, for example, for conversations read after 30min i think the conversation is cold so it can go down the list... if last read msg was less 30min ago(this time could go in preferences), it means that conversation could still be going on.

**Comment by skywinder** [comment]
Please add an option to show only Unread messages 🔥🔥🔥

**Comment by rzahrai** [comment]
+1. Add code permitting search similar to Gmails', "is:unread" to show only chats with unread content.

**Comment by gernotpokorny** [comment]
"+1. Add code permitting search similar to Gmails', "is:unread" to show only chats with unread content."

yep would be defenitely useful

**Comment by terrycloth** [comment]
I would prefer to simply sort unread messages at the top of the chat list, under pinned chats.

I also think it would be useful if any chats with *saved drafts* were also sorted to the top of the chat list, but since since requests to sort unread first have all been marked as duplicates of this issue, I wasn't sure if you'd want a whole separate feature request for this.

**Comment by Iamdeadlyz** [comment]
Any updates for this one? This would be pretty useful since I also miss some unread messages 👍

**Comment by capiscuas** [comment]
I still think it would be a great feature. I am always thinking to find another telegram client that may have the option but nothing yet.

**Comment by KelvinPac** [comment]
2019 and Telegram has no such simple feature. Am finding personal messages buried in a heap of messages a month later. Bring this feature to telegram ASAP

**Comment by stek29** [comment]
@kelvinpac use workmode

**Comment by KelvinPac** [comment]
How do I access work mode?

**Comment by stek29** [comment]
open settings and type workmode

**Comment by buylife** [comment]
Please explain in details about getting workmode you mentioned

**Comment by KelvinPac** [comment]
Yeah please.. Is it available in the android telegram application?

**Comment by RememberTheAir** [comment]
@buylife 

1. open settings
2. type "workmode". You just have to type it an tdesktop will ask you to enable it. It's an hidden feature

@KelvinPac it is not available on android

**Comment by buylife** [comment]
@RememberTheAir is it only available for tdesktop? how about telegram ios?

**Comment by RememberTheAir** [comment]
@buylife tdesktop only

**Comment by oshliaer** [comment]
So what is next after `workmode`? Nothing changes.

**Comment by elessarperm** [comment]
I would appreciate a gmail inbox-like approach: just optionally show all the unread in a separated block.

**Comment by Soleone** [comment]
I have hundreds of conversations. I have 4 unread messages somewhere. I have no idea in which conversation the messages are in. I have to carefully scroll through hundreds of contacts and channels to find them.

Why can I not see unread messages at the top or easily via some other filter? Or am i missing something and this is available? Seems like such a basic feature.

**Comment by RememberTheAir** [comment]
@Soleone the app in your screenshot is the iOS app or the native MacOS app, either way not tdesktop

**Comment by kiemrong08** [comment]
Nicegram IOS App have this feature but telegram desktop doen't. Please add this feature to tdesktop, it very useful.

**Comment by ngankt2** [comment]
I always see an unread message, but I can't find it

**Comment by ginto-sakata** [comment]
So can we add this?

**Comment by jt3k** [comment]
I want the same as others want

**Comment by Aokromes** [comment]
very likely it will come with folders.

**Comment by Aokromes** [comment]
implemented on 1.9.22 beta.
