### ISSUE TITLE
[Idea] Stickers pack or one sticker Remove

### ISSUE THREAD

**Issue by Jav4dR** [telegramdesktop/tdesktop#1068]
Please add Sticker pack Remove or one sticker in List Stickers.

**Comment by auchri** [comment]
You can remove sticker packs by hover the name of the sticker pack

**Comment by Jav4dR** [comment]
how to remove?

**Comment by auchri** [comment]
![image](https://cloud.githubusercontent.com/assets/5092164/9700156/9dc23946-53f9-11e5-95c7-2d177d82918e.png)

**Comment by Jav4dR** [comment]
thanks
