### ISSUE TITLE
Link address unexpectedly truncated

### ISSUE THREAD

**Issue by JokerQyou** [telegramdesktop/tdesktop#1072]
Some website, like the [Netease Music][1], is more like a webapp than a ordinary website. These website use hash to locate resources, e.g., NetEase Music uses link like `http://music.163.com/#/m/song?id=22746144` to specify a song, by viewing that webpage you can directly see the details of that song and listen to it. 

But I just found that tdesktop seems to truncate the hash part of these links. If I send that link to someone, the text is okay, but the link address is parsed as `http://music.163.com/`, anything after the hash (and the hash itself) are gone. Thus the people who received my message will only be able to see the home page if they click it. 

[1]: http://music.163.com/

**Comment by JokerQyou** [comment]
As seen in #1061 , links seem to be parsed on Telegram server now?

**Comment by auchri** [comment]
Yes, the are parsed on the server

**Comment by JokerQyou** [comment]
Hmm, and how can I send a feedback about this to Telegram? I found neither feedback links on their website, nor feedback repo on GitHub.

**Comment by telegramdesktop** [comment]
I can't get it work the way you describe:
![image](https://cloud.githubusercontent.com/assets/6113871/9703751/bf2554d2-5495-11e5-9d03-d23cbcf7d236.png)

Click leads me to that address, which then turns to that one:
![image](https://cloud.githubusercontent.com/assets/6113871/9703753/d689d65c-5495-11e5-899a-19c43a3ffba4.png)

**Comment by JokerQyou** [comment]
@telegramdesktop Well I and one of my friends both have this problem, and we're both using tdesktop 0.8.52 on Windows 10 professional 64bit. Once I sent that link to my friend, I cannot open that page by clicking the link; 'Copy link' results in the correct address, but 'Open link' does not. 

I've not tested it on my Mac. I'll do it once I get home (in 2 hours), and let you know the result.

BTW, that makes me think it's a client-side issue.

**Comment by JokerQyou** [comment]
Ok. Confirmed: this issue only occurs on Windows.

**Comment by telegramdesktop** [comment]
@JokerQyou what browser do you use? Microsoft Edge on Windows 10 opens url correctly, but Google Chrome does not, I'm afraid it is Chrome issue: if you press Win+R (Run command dialog), paste your url:

http://music.163.com/#/m/song?id=22746144

in that dialog and hit OK:

![image](https://cloud.githubusercontent.com/assets/6113871/9784731/c9affaec-57b5-11e5-8af5-f62b78b069e7.png)

Google Chrome will still open just "http://music.163.com/" :(

**Comment by auchri** [comment]
Chromium bug: https://code.google.com/p/chromium/issues/detail?id=157184

**Comment by JokerQyou** [comment]
Thanks for your help. :)
