### ISSUE TITLE
preview of image from url sometimes not work

### ISSUE THREAD

**Issue by parsibox** [telegramdesktop/tdesktop#1073]
![capture1 00000003](https://cloud.githubusercontent.com/assets/12513476/9703241/63656982-5492-11e5-9799-47fdb5c35c23.PNG)
hi
sometimes my image from url not show in telegram desktop windows 7 (please  see attach )
and some url not show any note

**Comment by auchri** [comment]
Does it only happen on Telegram Desktop or does it happen in the android client too?

**Comment by telegramdesktop** [comment]
@auchri Preview gen is done by server as well. If server can't reach the image by your url (because it depends on your IP address or somehow else is not available from server) then there will be no image preview.

**Comment by parsibox** [comment]
my server is up and i can see image in firefox

**Comment by parsibox** [comment]
it is also wrong in android

**Comment by auchri** [comment]
@parsibox Please send me the link to https://telegram.me/Auroratic

**Comment by parsibox** [comment]
sent
it work now but in mornin it work

**Comment by auchri** [comment]
It works now ¯\_(ツ)_/¯

**Comment by kian1397** [comment]
too this lnk
http://www.jahanemadan.com/2017-12-25-07-37-41/vije/item/929-2019-02-12-11-38-29

**Comment by Laiteux** [comment]
2.0.1 same, please fix :(
