### ISSUE TITLE
Default to last used emoji/stickers

### ISSUE THREAD

**Issue by Nidonocu** [telegramdesktop/tdesktop#1076]
For those that don't use emoji but do enjoy using stickers, its annoying to have to click-through the emoji menu every time to access stickers.

Could the smiley-face button either remember the last used pane (so if the user last used a sticker, show the stickers screen when its clicked) or could there be separate emoji and sticker buttons.

**Comment by mushopea** [comment]
+1 yes, please!!

**Comment by Akita91** [comment]
some one please make this happen 😢
