### ISSUE TITLE
Reorder sticker packs

### ISSUE THREAD

**Issue by Nidonocu** [telegramdesktop/tdesktop#1077]
Sticker packs are currently ordered: Frequently used > Pre-installed > Custom installed, sorted by reverse install date.

It would be nice to re-order this list to a custom order by dragging the pack icons back and forth along the bar to the user's preference, and offering a 'Sort by Name/Install Date/Size/Last Used' option on a right-click menu for quick re-sorting.

**Comment by auchri** [comment]
There is no api to sync the order of the packs to the other clients
