### ISSUE TITLE
Security - iOS Client Displays PIN Dialog After App UI

### ISSUE THREAD

**Issue by foxmajik** [telegramdesktop/tdesktop#1078]
This is a security issue.

I'm posting it here because I spent a good half an hour searching for the bug tracker for the iOS client and wasn't able to find it.

Please help me by moving this bug to the correct project or providing a link to it so I can post it in the right place.

When switching to the Telegram app on iOS, the Telegram interface is displayed briefly before the PIN dialog displays, exposing all user data one would want to protect with a PIN.

One could easily trigger a screen shot before the PIN dialog and then  read the messages, thus defeating the purpose of the PIN.

**Comment by auchri** [comment]
Are you talking about this client: https://itunes.apple.com/us/app/messenger-for-telegram/id747648890 ?

**Comment by foxmajik** [comment]
Obviously I'm talking about the one linked to from the main Telegram website.

This one:

https://itunes.apple.com/app/telegram-messenger/id686449807

**Comment by auchri** [comment]
Hm, you can write to the telegram team on twitter: https://twitter.com/telegram

Or go to settings -> Ask a question :)

**Comment by foxmajik** [comment]
Oh that's already been done some time ago.

They're unresponsive.

See here: https://twitter.com/zettlerm/status/439393971719385088

**Comment by t9nf** [comment]
Dengue 👹

**Comment by auchri** [comment]
@foxmajik 
![image](https://cloud.githubusercontent.com/assets/5092164/9748277/fdee9f26-5683-11e5-85a7-ae357dbcb097.png)

**Comment by foxmajik** [comment]
Thank you @auchri .

![translate-telegram-bug-response](https://cloud.githubusercontent.com/assets/300165/9748419/69158224-5639-11e5-9bbe-21319cf72c3c.JPG)

It looks like he's saying that he's aware of the issue and a fix has been proposed, but it has not yet been released.

Could you possibly ask him where his bug tracker is hosted?

**Comment by auchri** [comment]
They don't have a public bug tracker for the iOS app.

**Comment by foxmajik** [comment]
That's... odd.

How are they supposed to receive input from users who discover bugs?

**Comment by auchri** [comment]
Via twitter or the "Ask a question" feature
