### ISSUE TITLE
No incoming messages are synchronized between the application on iphone and windows 10 desktop

### ISSUE THREAD

**Issue by croupier** [telegramdesktop/tdesktop#1080]
telegram last vertions
iphone 4s iOS 8.4.1
windows 10 pro en 64x with all updates, telegram portable

If I get a message on my phone, it is not displayed on the computer until restart the application.
Both applications are running in the background.
In previous versions it was ok.

**Comment by auchri** [comment]
Does it work today?

**Comment by croupier** [comment]
Today everything is working properly.
version 0.8.57
Thank you.
