### ISSUE TITLE
Set to show unread count per group

### ISSUE THREAD

**Issue by Rym-** [telegramdesktop/tdesktop#1081]
I would like to be able to turn off unread counts for specific chat groups. For example any group with my friend I'd like to see the number of unread messages. I'm also in a public group and I don't need to see the number of unread messages (or any type of sign that there are unread messages at all).

**Comment by auchri** [comment]
You can mute these groups und uncheck "Include muted chats in unread count" in the settings

**Comment by Rym-** [comment]
Haha wow apparently I was exactly 1 version behind. Updated and see it now, thanks!

**Comment by Rym-** [comment]
Though, thinking about it, would it still not be possible to set this per group? I have all my group chats muted due to the volume of messages. But for my friend I would like to see the unread count, public group not?

**Comment by auchri** [comment]
You can mute the group and don't mute your friend?

**Comment by Rym-** [comment]
It's not so much my friend, the difference is between a group chat with friends (8) and a public group chat (python telegram bot API, 65 users)

**Comment by auchri** [comment]
Then mute the large grouo and don't mute the group with your friends?

**Comment by Rym-** [comment]
Auchri, I agree that this is possible, but my use case is the following: When I am at the office i cannot have my phone constantly going off, so I have all groups set to mute (a single user will most likely not spam me with messages during the day.) I do however like to see if I am missing messages from my group of friends. On the other hand i am not interested in seeing if i have missed messages from a public chat group with many users.

The question is basically if you guys think it is worth it to create an option to see unread count PER GROUP or not :) If not, no worries, I was just interested in the feature!

**Comment by UnAfraid** [comment]
I really need this option too.
I am using telegram for primary messenger now, and i am part of multiple discussions, and some of them are kinda spammy and i cant know if i have something important to read.

**Comment by Rym-** [comment]
In the end I left a couple of groups because it was too annoying to constantly have unread messages, only finding that they are of these not-so-important chat groups instead of my family & friends. I still would really like this option as well.

**Comment by telegramdesktop** [comment]
@UnAfraid When the group is muted you see only gray count in the conversations list, you even can exclude them from "all unread messages" count, which is displayed upon the icon. I don't see the problem.

**Comment by UnAfraid** [comment]
I have important conversations and non important ones.
All of them are without notifications i am counting on the gray numbers if there is something on the important conversations but most of the times non important ones are making me open the messenger every minute for nothing..
If i mute all i won't see if something was said on the important groups unless someone mention me.

**Comment by auchri** [comment]
@UnAfraid The option you requested exists already

![image](https://cloud.githubusercontent.com/assets/5092164/10675692/f1516b72-7901-11e5-872d-11ad28b9015c.png)

**Comment by UnAfraid** [comment]
@auchri not this one..
I am requesting for 

![](http://i.imgur.com/DqWxK6K.png)
per group chat

**Comment by DaFri-Nochiterov** [comment]
:+1: +1

![image](https://cloud.githubusercontent.com/assets/10401817/10692639/2c4bffc4-79bd-11e5-9e31-17acec22b54e.png)

**Comment by UnAfraid** [comment]
@DaFri-Nochiterov exactly! :+1:

**Comment by Rym-** [comment]
Yup, this is also what I originally had in mind :+1:

**Comment by UnAfraid** [comment]
Is there any chance to get this request fulfilled?

**Comment by Gladicek** [comment]
:+1:

**Comment by Sdw-** [comment]
:+1:

**Comment by Painkiller359** [comment]
It will be great if we see this feature included in the messenger.

**Comment by Sdwz** [comment]
+1

**Comment by kirtom** [comment]
+1

**Comment by alekseyl1992** [comment]
+1 on this
I have all my chats muted
but I would like to exclude public chats from unread count as well

so that if I see grayed unread counter on tray icon - I know, that I've missed something from importnant (private) chats, not from public ones

private chats - those with my friends and colleagues
public chats - technology related public chats with 100+ peapoles in each

generally speaking, it would be convinient to move public chat to a separate group in the list
but setting "Include in unread count" per chat would solve the problem as well

**Comment by Aokromes** [comment]
Even this is older, #3916 is wider request.
