### ISSUE TITLE
Can't send command to bot

### ISSUE THREAD

**Issue by AboShanab** [telegramdesktop/tdesktop#1082]
Hi there 

I have a problem with telegram,if i send command to bot the command isn't delivered and this problem also in the IOS my mobile

SCREENSHOT:
http://prntscr.com/8efb1m

Pc information : 
Windows 10 64 bit
Telegram Desktop 0.8.55

**Comment by auchri** [comment]
If it also not works with the iOS app, write to the telegram team on twitter (https://twitter.com/telegram) or with the "Ask a question" feature in the settings
