### ISSUE TITLE
Undoing pasted emoji results in incorrect font display

### ISSUE THREAD

**Issue by nivomi** [telegramdesktop/tdesktop#1083]
After pasting multiple emoji into the message entry textbox, hitting ctrl+z will cause certain emoji characters to display using the Windows emoji palette instead of Telegram's inbuilt set.

![image](https://cloud.githubusercontent.com/assets/5092164/9771341/b2d7ad54-5735-11e5-9d80-546021e67710.gif)

Steps to reproduce:

1. Copy these octopi into your clipboard: 🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙
2. Paste them into a Telegram chatbox using ctrl+v
3. Press ctrl+z one or more times
4. Observe that the squids revert from Apple-style Emoji to the Windows character set

Running Windows 10 with Telegram version v 0.8.55 stable

**Comment by telegramdesktop** [comment]
@nivomi Yes, replacing emoji characters with pics is done after pasting, so undo firstly convert pics back to characters and only after that undoes the paste. I'll try to unite edit+emoji_replace into one undo step, but I'm not sure I will succeed — I use Qt text fields with undo stack for that, not my own.

**Comment by auchri** [comment]
fixed
