### ISSUE TITLE
glitch on button input with spaces in

### ISSUE THREAD

**Issue by dcsan** [telegramdesktop/tdesktop#1084]
when sending json with an extra space in for a menu

```
 reply_markup: '{"keyboard":[["sticker "],[" menu"]], ... }'
```

(note the space after "sticker_")

it will render fine as a button:
![image](https://cloud.githubusercontent.com/assets/514002/9782396/8fd14920-5751-11e5-8ff8-5b305b4cd5e6.png)

but clicking that button will send a wrongly trimmed result to the client - two characters are trimmed from the end.

![image](https://cloud.githubusercontent.com/assets/514002/9782337/3e6098ac-5751-11e5-8ca4-517653705e42.png)

**Comment by auchri** [comment]
Just a question: Why do you create buttons with a space at the beginning or at the end? oÔ

**Comment by dcsan** [comment]
this was a bug of mine (I forgot to trim() the input) but it did let me find this bug in TG. probably low priority as there's an easy workaround but thot I'd log it anyway.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
