### ISSUE TITLE
Low contrast when selecting a user from the auto-complete suggestions

### ISSUE THREAD

**Issue by Vashiru** [telegramdesktop/tdesktop#1086]
When typing in the name to mention somebody in a group chat a couple of options will appear for auto completion. However the contrast of the color of the selected user for autocomplete vs the background on the non-selected users is very low. On most screens I can barely make out the difference, which have caused me to mention the wrong person a couple of times. Could the contrast be increased?

**Comment by auchri** [comment]
When you hover  contact, the contact background get's the same color as the selected user in the autocomplete list. That's the same color.
For me the contrast is high enough, I see clearly which user is selected. Maybe you have false monitor settings or just bad monitors.

**Comment by Vashiru** [comment]
![screenshot 2015-09-12 12 32 08](https://cloud.githubusercontent.com/assets/11370057/9833187/a9650234-598e-11e5-9f14-39762f40ccb6.png)

I've loaded this image up in Photoshop, checked the colors on it. On a HSB scale the difference is a mere 4% in brightness; #FFFFFF vs #FEFEFE. Though you're right that it's the same color for the keyboard as when you hover it with your mouse, with your mouse you still have the visual guidance of the pointer as to which one is selected. When you using your arrow keys instead it gets a lot harder tell as you lose the guidance. Especially when monitoring multiple things at once and being distracted for a second I find it hard to tell which one is actually selected at that moment.

Perhaps it would be better to use the same (blue) color as with the currently active chat. When you navigate through those by keyboard you'll notice it uses the blue background as well, but when using the mouse it will actually use the gray one for the hover.

**Comment by Aokromes** [comment]
maybe a bit darker or even total different color can do the job.
