### ISSUE TITLE
Right-click on input fields display an aged style menu

### ISSUE THREAD

**Issue by NonnEmilia** [telegramdesktop/tdesktop#1090]
I'm on Windows 7 and when I right click on input fields appear to me an "aged style" (Windows 98 like) menu.

It is easier looked than explained:
![tdesktop-right-click-menu](https://cloud.githubusercontent.com/assets/2818194/9843601/38ad5602-5abc-11e5-9a55-45f06af69d34.png)

The same happen on the search input field.

A right click elsewhere displays correctly a Telgram-Desktop-like menu.

**Comment by ralesk** [comment]
That's a Qt thing I guess, not really depending on Telegram as such.

**Comment by z3ntu** [comment]
It is still very ugly and not fitting to the Telegram style.

**Comment by z3ntu** [comment]
Also probably a duplicate of #987

**Comment by telegramdesktop** [comment]
@z3ntu That will be replaced with custom one in future versions.

**Comment by z3ntu** [comment]
Any ETA?

**Comment by z3ntu** [comment]
Fixed in 0.9.9 dev
