### ISSUE TITLE
Commandline Send image Windows

### ISSUE THREAD

**Issue by joshkreud** [telegramdesktop/tdesktop#1091]
There is the "-sendpath" commandline switch in telegram. 
I use it to send a screenshot directly to telegram using greenshot. With "-sendpath" the image gets sent as a file. Meaning in full size. 
How about an "-sendimage" switch. which sends the image as an actual image?

**Comment by Tschlienger** [comment]
I was just trying the same thing with Greenshot and got stuck with the -sendpath Option. Would be very nice if sending an Image would be possible! 👍

**Comment by stek29** [comment]
@joshuader6 Adding a switch to change type of attachment is more elegant solution imo
