### ISSUE TITLE
Setting QT_DEVICE_PIXEL_RATIO messes up the interface

### ISSUE THREAD

**Issue by athanasio** [telegramdesktop/tdesktop#1092]
Hello,
I'm using a windows laptop with a HiDPI display and for some older apps to work properly, I need to set QT_DEVICE_PIXEL_RATIO to auto as a user variable. However, this messes up with Telegram desktop app on Windows. 
Since Telegram already supports proper scaling options, could you make the app to ignore the value set on this variable?

Regards,
Th.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
