### ISSUE TITLE
Audios recorded with Telegram Android can not be loaded in Windows Desktop client

### ISSUE THREAD

**Issue by coder66** [telegramdesktop/tdesktop#1093]
When someone sends a recorded audio, I get the notification in the chat window on the desktop client.

However, there is always an "upload error". Clicking "Download" shows an error that the file can not be downloaded. Works fine on the Telegram for Windows Phone.

Using latest DEV Windows client on Windows 10 - but this has been around ever since I have been using Telegram for Windows.

![snap 1](https://cloud.githubusercontent.com/assets/14278231/9854515/7003f23a-5b09-11e5-8f68-ade62cf9c131.png)

**Comment by auchri** [comment]
Works for me
![image](https://cloud.githubusercontent.com/assets/5092164/9855100/9e7ea4f4-5b0c-11e5-8a83-5e3450f82914.png)

**Comment by Aokromes** [comment]
Same here.

**Comment by coder66** [comment]
Note: I am using the portable version of Telegram. Perhaps that causes this behaviour?

**Comment by auchri** [comment]
It works for me in the portable version too

**Comment by coder66** [comment]
Still not working on my Win10 Insider Preview as portable version. Does Telegram.exe need to run with admin rights?

**Comment by auchri** [comment]
No, no admin rights needed

**Comment by coder66** [comment]
I reset the path where the files should be saved and now I can download them. Seems there was something wrong in the path setting in options. Closing for now.
