### ISSUE TITLE
Delete and exit in a group settings does nothing

### ISSUE THREAD

**Issue by susloparovdenis** [telegramdesktop/tdesktop#1094]
I was kicked from a group. After "Delete and exit" or "leave", the group still remain on the left panel. Windows. telegram version is 0.8.57

**Comment by shahriar-gholami** [comment]
I still have this issue on 0.9.10
Spammers are using this, they invite to a group then kick you, so you cant report as spam and delete the conversation
windows 7

**Comment by sabereen** [comment]
I have this problem too.
I leaved a group but every time I back to telegram, the group comes back;

**Comment by Aokromes** [comment]
Works for me on 1.2
