### ISSUE TITLE
[Privacy] Phone number gets shared

### ISSUE THREAD

**Issue by ralesk** [telegramdesktop/tdesktop#1096]
I've seen this happen a few times already and I suspect a bug somewhere in the protocol.

I had three contacts I added with their @-names, and we do not know each other's phone numbers.  At least I don't know theirs for sure.  For two of them, their phone number appeared later to me, for one of them my phone number appeared to them.  Which I don't mind personally, but other people might not like their phone number getting shared — that's why we use the usernames afterall.

**Comment by ppparadox** [comment]
+1

**Comment by Aokromes** [comment]
I confirm this bug.

**Comment by ineedblood** [comment]
Seen this more often. 

Anyway to reproduce it?

**Comment by ineedblood** [comment]
Al-right, just to point out once this bug triggers both contacts see their phones

**Comment by SmartManoj** [comment]
Still

**Comment by SmartManoj** [comment]
> Still ?

@Aokromes

**Comment by ralesk** [comment]
Currently, the Privacy & Security settings has a Phone Number part where you can select that it be shared with Nobody.

Whether this works, is enough, and satisfies the original report or the concerns of the other commenters, I don't know.

It is certainly not the default setting, so that's a bit of an issue.

**Comment by ralesk** [comment]
Still an issue.

**Comment by ralesk** [comment]
I still see people's phone numbers when I think I shouldn't be — so probably this issue is still a thing.
