### ISSUE TITLE
[Privacy] Multiple users per phone number

### ISSUE THREAD

**Issue by ralesk** [telegramdesktop/tdesktop#1097]
I know of plenty people who use different names (nicknames, handles, whatever) in different circles — real name for classmates and family and work; nicknames among other kind of friends or maybe in a development circle; the list goes on.

It would be nice to have separate profiles per phone number — but this would require phone number not to be the primary identification thing in MTProto I guess.  So we could continue to separate things.

**Comment by ralesk** [comment]
Should I report it somewhere closer to the API or the proto, or is that being developed in the dark?  I'd think just closing the issue will result in this being forgotten entirely.

**Comment by telegramdesktop** [comment]
@ralesk I'm almost sure multiple users per phone number won't ever be done, but you can suggest it on official @telegram Twitter.
