### ISSUE TITLE
The link in the README under Build instructions → "Qt Creator 3.2.0 Ubuntu" is broken.

### ISSUE THREAD

**Issue by shlomif** [telegramdesktop/tdesktop#1098]
The link in the README under Build instructions → "Qt Creator 3.2.0 Ubuntu" is broken. It leads to https://github.com/telegramdesktop/tdesktop/blob/master/qtcreator.md and it does not exist. In the repo, the filename is given in "ALL CAPS" but it's not clear to me which one is the intentional one.

**Comment by auchri** [comment]
Thank you :)

**Comment by shlomif** [comment]
You're welcome.
