### ISSUE TITLE
"Last seen recently" isn't working in groups

### ISSUE THREAD

**Issue by mrkeyboard** [telegramdesktop/tdesktop#1099]
Despite disabling "last seen" in settings, it's possible to assume when I was online in a group. In the following picture I'm the person in the middle, between a person currently online and another person who was online 5 minutes ago. Screenshot taken by another user in the group to let me know. 

![image](https://cloud.githubusercontent.com/assets/936268/9907026/e01dd634-5c95-11e5-879b-8bb60156baa3.png)

**Comment by snird** [comment]
+1

**Comment by orenyomtov** [comment]
+2

**Comment by DaFri-Nochiterov** [comment]
+3

**Comment by RememberTheAir** [comment]
On tdesktop 1.7.3 it still works like that. On Telegram for Android, people which have their last seen hidden always appear _after_ those who keep it public, probably to avoid to unintentionally share the approximate last seen time of the chat members.

This is something I noticed today in a chat with people who are whitelisted to see my last seen time:
![image](https://user-images.githubusercontent.com/16143208/58883785-69a8a600-86df-11e9-981f-dc76d609a68d.png)

From the screenshot above, I can guess the highlighted guy's last seen was between 18 and 22 minutes ago

Side note: Telegram X for Android shows them at the top of the list

**Comment by john-preston** [comment]
@RememberTheAir This doesn't reveal anything not known to the app already. It just means that there was some activity in the app from that user between 18 and 22 minutes ago.

**Comment by RememberTheAir** [comment]
@john-preston Yes exactly, thus revealing the approximate last access time of that user - who decided to hide it. I'm aware that's how the API orders the members, but the Android apps (I suppose) try to hide that info by placing users which have their last seen hidden at the top/bottom of the list. If you ask me, I don't see why the API doesn't directly give the members ordered in a way the approximate last acces time cannot be guessed by the user position in a group's members list.

I don't know how the iOS/Mac apps behave btw

**Comment by john-preston** [comment]
@RememberTheAir No, this is client that is reordering them. Why not, user revealed himself by posting in a group, I don't think he expects that no one noticed his message or smth.

**Comment by RememberTheAir** [comment]
@john-preston oh wait, so the order is not based on the actual last seen but also on the last activity in the chat. Yeah makes sense, thanks for explaining it. Didn't think about that. I guess this issue can be closed then

**Comment by john-preston** [comment]
@RememberTheAir The activity time is one for a user, in all chats we're both in, but I don't hink this is a problem. It is by last seen, but local last seen is updated when we see a message from a user,.
