### ISSUE TITLE
GUI window 

### ISSUE THREAD

**Issue by bugmancx** [telegramdesktop/tdesktop#1100]
After encountering a situation where the entire telegram window displayed only as a title bar, I deleted the application's Container under  ~/Library/Containers/ru.keepcoder.Telegram and reconfigured Telegram to my account.

Since then it randomly crashes and I have repeated these steps. What better information can I provide to report a proper bug?

![screen shot 2015-09-16 at 16 53 10](https://cloud.githubusercontent.com/assets/130010/9913266/e3943818-5ca3-11e5-8ec5-c6e358e3edda.png)

**Comment by telegramdesktop** [comment]
@bugmancx ru.keepcoder.Telegram is another OS X app, not Telegram Desktop. Are you sure you use Telegram Desktop? Try version from https://desktop.telegram.org please

**Comment by bugmancx** [comment]
You're right. I was confused! Apologies. I'll close this bug.
