### ISSUE TITLE
Last Seen not working correctly if one also uses the iOS-app.

### ISSUE THREAD

**Issue by ErikThorsell** [telegramdesktop/tdesktop#1102]
Over the last weeks I've experienced the issue where I check a conversation on my phone and then turn on my computer and check the same conversation there. The "Last seen-message" on the phone will still be correct but on the computer the "Last seen-message" will have changed to what ever time I checked the message on the phone.

E.g.
Message received at 13:00, checked on phone 17:00. The phone app will say "last seen 4 hours ago".
Now goes to my computer (running the app under Arch Linux) and the app will declare "last seen just now" (or however many minutes it has been since I checked my phone).

**Comment by auchri** [comment]
Do you use an different account on the computer than on the iPhone?

**Comment by ErikThorsell** [comment]
I do use the same phone number on both devices.

// Erik

On 17 sep. 2015, at 10:20, auchri <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you use an different account on the computer than on the iPhone?

-
