### ISSUE TITLE
Send message on pressing <Enter> twice

### ISSUE THREAD

**Issue by timic** [telegramdesktop/tdesktop#1103]
Handy feature that saves your fingers

**Comment by auchri** [comment]
oO
Messages are sent when you press enter.

**Comment by timic** [comment]
Oh. It's not a bug report. It's feature request.

**Comment by auchri** [comment]
Messages are already sent when you press enter once, how should they be sent when you press enter twice?

**Comment by timic** [comment]
When I press `enter` once it should create new line. This behaviour is the same as in case when `Send by Ctrl+Enter` option is selected.

![image](https://cloud.githubusercontent.com/assets/1687875/9954572/df9369fa-5df2-11e5-8fbc-fc9f177beb2b.png)

If I press `enter` again then it should send message and created line should disappear.

**Comment by auchri** [comment]
ctrl is just two keys below enter, so it makes not really much sense for me

but I will mark it as enhancement

**Comment by c0der404** [comment]
@timic and if you want to make **two** new lines? :smiley:

**Comment by Aokromes** [comment]
better ticket:
https://github.com/telegramdesktop/tdesktop/issues/3366#issuecomment-299989401
