### ISSUE TITLE
No tray icon - Debian 8.2 and Gnome 3.14.1

### ISSUE THREAD

**Issue by MarioVillani** [telegramdesktop/tdesktop#1105]
Tray icon does not show anymore. 
Is there a way to enable it again?I checked in Telegram settings and i also installed "Topicons" gnome extension to show legacy icons, but it does not show at all.

**Comment by auchri** [comment]
install the libappindicator library

**Comment by MarioVillani** [comment]
It worked. Thank you.

**Comment by frictionlessmeme** [comment]
Not working for me.  Is there a specific libappindicator package that should be used?

FWIW, originally this didn't work, and then it was fixed for several months, but an update a few months back broke it again.
