### ISSUE TITLE
Sending file as video

### ISSUE THREAD

**Issue by shibme** [telegramdesktop/tdesktop#1106]
Telegram desktop doesn't have the feature of sending video. Rather only sends it as a document. Please add support for sendVideo API.

**Comment by LibertyPaul** [comment]
+1

**Comment by fabiothz** [comment]
I like have this feature

**Comment by SPAHI4** [comment]
+1
live viewing of files such as `webm` would be perfect

**Comment by auchri** [comment]
mp4 files are sent as video now.

**Comment by rafalbednarczuk** [comment]
@auchri 
There are other video formats other than mp4. Webm files aren't "send as video". Telegram X client for Android supports sending webm as video.
