### ISSUE TITLE
Categories in list of chats

### ISSUE THREAD

**Issue by Brawaru** [telegramdesktop/tdesktop#1107]
When user have a large number of chats, the list looks dirty, it is inconvenient to navigate. 
I suggest making the possibility to sort chats in categories, as well as the ability to disable notifications for the entire category.

For example, I made a 'concept' new kind of list:
![image](https://cloud.githubusercontent.com/assets/10401817/9975772/b965222c-5ef2-11e5-8582-592311e20821.png)

When the user receive the messages:
![image](https://cloud.githubusercontent.com/assets/10401817/9975766/a050b184-5ef2-11e5-9206-37a501ed476c.png)

**UPD** from 20 Apr 2016:

There, on concept's images, you can see custom categories.

Default set of categories is:
- Chats
- Groups
- Bots
- Channels
- Favorites

Any of this categories can be changed. Also, you can create your own categories, like "School friends" or "My bots". In names of categories supported Emoji.

Settings for categories:

```
Categories
[■] Enable categories

Default category for..
 Users:           [ Users       🔽 ]
 Bots:            [ Bots        🔽 ]
 Groups:          [ Groups      🔽 ]
 Supergroups:     [ Groups      🔽 ]
 Сhannels:        [ Channels    🔽 ]

Categories:

Users ✏️
  [■] Don't delete row on deleting chat
  [Members] [Remove]

Bots ✏️
  [■] Don't delete row on deleting chat
  [Members] [Remove]

Groups ✏️
  [ ] Don't delete row on deleting chat
  [Members] [Remove]

[ Channels| ] ✅
  [ ] Don't delete row on deleting chat
  [Members] [Remove]

[ + Add ]

```

And.. As you can see row of "Botfather" doesn't contain message, it's because chat is empty.
You can enable it in settings of categories to keep row even on deleting chat (or unsubscribe from channel).

You can add users to categories in user's profile.
## 

_Sorry for my bad English_

**Comment by auchri** [comment]
that looks nice :+1:

**Comment by sergioad** [comment]
I really do not know if could be good include a bots  category but I agree with the favorites  category, I also suggest a low priority category, a category of chats wich does not counts how many new messages you have, it only shows a red badge with an exclamation sign,  it stills  giving you desktop notiffications but with not counting the number of new messages

**Comment by Aokromes** [comment]
As long the categories is customizable it have my vote :)

**Comment by kanishkablack** [comment]
Yep agreed, Bots are invading the list, searching though contacts is becoming harder and harder

**Comment by nicolasdejong** [comment]
Telegram is more and more used in a professional environment e.g. by sending files, images, links or questions to colleagues. Contact categories would fit in perfectly there as well so that one can have e.g. 'private' and 'work' categories (and various 'channels' categories like twitter groups).

**Comment by caiodias** [comment]
Categories with the possibility of rename each one could be nice.

**Comment by auchri** [comment]
Categories with user defined names would need a new api

**Comment by s4m4n** [comment]
+1

**Comment by komsboymore** [comment]
+1

**Comment by aaomidi** [comment]
+1

**Comment by zackpollard** [comment]
+1

**Comment by pmarrapese** [comment]
+1

**Comment by stuntguy3000** [comment]
+1 Support, must have feature.

**Comment by SkepticalsArctic** [comment]
+1

**Comment by Sponges** [comment]
:+1:

**Comment by faridcboy** [comment]
+1

**Comment by bo0tzz** [comment]
+1

**Comment by bomberstudios** [comment]
👍🎉❤️

**Comment by Atxa** [comment]
+1

**Comment by mattmezza** [comment]
:+1: 
I'm using group chats as thread based chats and for this reason I have got a very huge number of open chats... It would be very good to have the possibility to categorize (either automatically or manually) my chats in order to be able to create different workspaces (per job, per client, work/family, per exam, per activity).

**Comment by vozzurg** [comment]
+1

**Comment by Perkovec** [comment]
+1

**Comment by aaomidi** [comment]
Is there any actual information that this is in the works?

**Comment by telegramdesktop** [comment]
@aaomidi This is not in the work, sorry.

**Comment by urbansheep** [comment]
With wider spread of channels and with Telegram becoming a news source (many muted channels available to be read on demand), this filter is even more important — personal chats get drowned in the bots/channels/groups.

Some kind of filtering/grouping for different chat types would help a lot.

**Comment by kanishkablack** [comment]
@telegramdesktop sync categorises can't be synced across the devices, is the reason, why its been dropped or any other peculiar reason ?
I am suspecting that's the same reason why the secret chat is dropped in desktop..

If thats the main reason, there can be a work around the issue

**Comment by aaomidi** [comment]
I would just like to say that adding this would be a tremendous feature and would help organization. Please reconsider your decision :)

**Comment by amiremami** [comment]
Guyz maybe something like this: 

![asdasdsa](https://cloud.githubusercontent.com/assets/15929497/13160213/5efe71aa-d696-11e5-871b-bb9146ea0afe.png)

I have to say the more features telegram add the more harder is working with it. It's becoming impossible to follow more channels and groups because this section is not organised at all.

Thanks

**Comment by haevalencia** [comment]
+1 tabs to separate contacts, chats, groups and channels.

**Comment by code88899091** [comment]
+1 to allow catergorizing by any way. Let's consider some media project that has several channels, some live chats and bots. I would like to make a single category for them. Artifical division of them by bots/channels/chats will have much less sense.

**Comment by auchri** [comment]
@code88899091 no api for that

**Comment by diazbastian** [comment]
:+1:

**Comment by aaomidi** [comment]
@auchri Even though there is no API for that, it could still be implemented on the local level and hopefully official telegram provides an API to take it to the cloud level.

**Comment by auchri** [comment]
yes, it *could* be. But I'm sure nobody of the Telegram team wants this.

**Comment by zackpollard** [comment]
@auchri Right, but they could also add this functionality into MTProto as it is a highly requested feature that people have now made a campaign about in numerous channels http://www.zackpollard.pro/at-screenshots/qJavbFFd.png . It should be considered to be added, it would be very helpful as right now navigating through the numerous chats, channels, bots and groups that you are in is a very tedious task and is becoming very annoying to do.

**Comment by amiremami** [comment]
Unfortunately it's not so easy following more than 10 channels with a lot of contacts and groups. It's becoming so messy! :(

**Comment by aaomidi** [comment]
Honestly makes no sense that Telegram doesn't want this. I really wish someone explained the downside of this feature.

**Comment by zaz600** [comment]
+1

**Comment by luc1ph3r** [comment]
+1

**Comment by nexfwall** [comment]
Just +1. We need this categorization.

**Comment by code88899091** [comment]
@auchri seems members of the telegram team has only a few of groups.

**Comment by kanishkablack** [comment]
@code88899091 lol

**Comment by GanGMaN** [comment]
+1

**Comment by DaFri-Nochiterov** [comment]
@GanGMaN, please use new Github [Reactions feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)

**Comment by SniperRus** [comment]
very usefull tab realisation in android Plus Messenger (clone Telegram)
there are several tabs there - all, users, groups,supergroups,bot,favs 
and you could setting up additionally group unreaded chats in desc order
![photo_2016-04-13_02-33-57](https://cloud.githubusercontent.com/assets/8127444/14478646/39593426-0120-11e6-9e9f-6c88d5201e6b.jpg)

**Comment by aaomidi** [comment]
I would rather have it so I can make my own categories.

**Comment by dandaka** [comment]
A must have feature for Telegram. Right now I'm not subscribing to Bots/Blogs channels to not mess with messages.

**Comment by amiremami** [comment]
It seems this we won't see this feature in near future. But is it possible to add "pinning chats" feature at least? #821 and #601 . 


>  Right now I'm not subscribing to Bots/Blogs channels to not mess with messages.

This is the biggest problem of webmasters, because hundreds of users leave the channel daily because of this reason.

**Comment by phraymond** [comment]
Please reconsider this in terms of prioritization. Now that TG use has exploded, it's become as painful as Hangouts! More so, actually, since at least Hangouts mobile app has the concept of Favorites.

![2016-07-18 10_35_56-](https://cloud.githubusercontent.com/assets/1957542/16924752/acedd814-4cd5-11e6-9359-b28ea89745f0.png)

**Comment by whyfuture** [comment]
How come this is not in top-prio? After subscribing to bots and channels — list is a mess and I tend to miss out important messages.

**Comment by tomcpc** [comment]
This is becoming more and more of a pain to me. It came to the point where I left many of my groups and stored the invitation links to them in a channel only to myself. Now I only enter the groups when I need and I leave them as soon as possible.

And looks like people are desperate for this feature, there is $150 bounty for it at Bountysource: https://www.bountysource.com/issues/26799986-categories-in-list-of-chats

**Comment by Salkin2** [comment]
@telegramdesktop 

Is there any reason for that? I mean this idea is a great usability improvement. Telegram is becoming much more than a messenger, it's becoming a sort of "microinternet", with lots of channels, groups and bots that often have links to each others. In reality I think that many people have more groups and channels than conversations with friends and family, that usually are on Whatsapp.
Well, this is great and makes Telegram the messenger app with a most promising and interesting future, but it needs a way to order all those cool things. It's a complete mess to have 2 or 3 hundreds of conversations all mixed up. TG really need to use tabs to order then accordint to categories like "Bots", "Channels", etc. Please reconsider your decision and try to make this a priority; I don't want to deprecate things, but I think we need tabs much more than we need photo filters, for example. And if you can implement this function soon, please tell us something like "There are technical diffculties like this and that and those", at least we shall know that you have taken this idea seriously into account" and other developers perhaps could contribute with code. That's the greatness of open source, no?

Best regards.

**Comment by stek29** [comment]
@Salkin2 There are really some technical difficulties.
Current implementation of chat list won't fit with categories.
When "Work mode" was implemented Dev just added second List with important chats only in it.
Now Imagine there are 5 categories. 5 Lists, and each one should be reordered each time a new message arrives.

Also, other official apps don't have tabs but do have features like "decorative photo filters" and games, and TDesktop Developer has to implement those first.

**Comment by Salkin2** [comment]
@stek29 Thanks for your clarifying answer. So, maybe the current implementation would need an important redesign. The current one leaves its unique list a complete mess when you start to have a few dozens of conversations, channels, groups, etc.
BTW, I didn't know there was only one developer working on the official clients. I thought there was a more or less numerous team of developers. I understand then that it must be a lot of work for just one person, but anyway I hope he/she takes this popular request into account for the not too far future.

**Comment by stek29** [comment]
@Salkin2 one app -- one developer. That's the idea.

**Comment by alnour-altegani** [comment]
any good news about this feature ? I really want this categorization thing

**Comment by whyfuture** [comment]
Indeed, uncontrolled flow of threads is a massacre;(

On Fri, Nov 4, 2016 at 09:26, alnour altegani <notifications@github.com> wrote:
any good news about this feature ? I really want this categorization thing

**Comment by raonyguimaraes** [comment]
Everyone is waiting for this feature, I don't think would be that hard implement... Please :)

**Comment by anmiles** [comment]
There are so many groups last time (channels, bots etc. appeared). It's so hard to understand them. Please, simplify our lives, please, please! :)

**Comment by amiremami** [comment]
If it helps, I also insist again on adding this feature!

**Comment by rufusht** [comment]
Please give us any feature that can organize "chat hell"! 
Peoples want it for all telegram apps, not only for "tdesktop". It is obvious. :/
Where is the place where we can request vital features for all telegram apps?
Thanks

**Comment by tomcpc** [comment]
@stek29 I understand that TDesktop can't add features on its own and that there are features present at other official apps that it is missing. Also, I'm sure you understand that even though the request is in this repository, in fact people want it for all Telegram apps.

There is a chance that I'm overestimating the importance of this feature since it's so important to me, but I have the impression that the community would be much happier with this than with many of other features implemented recently - don't get me wrong, I like every feature, it's just a matter of priorities.

That being said, is there a place to suggest **and** discuss feature requests for Telegram as a whole? Discussing the feature requests with other users and being able to see how popular each of them are is much better than sending an e-mail to the support and getting a vague "thank you" answer days later.

People come to GitHub and make such general requests as this one in the repositories either because there isn't a place to make and discuss features for Telegram as whole, or either because they can't find such place.

**Comment by FiretronP75** [comment]
If Telegram didn't want this, it would be closed. The fact that it is open means they are considering it. Telegram simply left a comment that "it is not in the works" yet, not that it never will be. They did not start working on it, but, they didn't throw the idea out. Other things are just higher priority to get done first.

**Comment by stek29** [comment]
@FiretronP75 Telegram almost never says never, and even if it does it still may happen.
But the fact they didn't close this doesn't mean it would be implemented.

**Comment by bardiarastin** [comment]
+1 tabs to separate contacts, chats, groups and channels.

**Comment by Twilightssuperb** [comment]
Telegram dev team should look at [iGram](https://i-gram.ir/downloads/)—tiny desktop Telegram fork with not almost tabs, but sidebar:
![igram sidebar](https://cloud.githubusercontent.com/assets/7080928/25006191/9d5bf4f4-2064-11e7-940d-12f45ae764f8.png)
Also it shows the whole notifications counter. iGram came from Iran, but supports English language. Warning: after launch iGram can subscribe you to some arabic channels.

**Comment by stek29** [comment]
@Twilightssuperb yay, another GPL Violation :D

**Comment by ThiPv** [comment]
2 important points:

- Categories shouldn't be limited like 1 for private chats, 1 for groups, 1 for bots... Please don't. Let the user create and order the categories as users personal needs. It's usual to have private chat, groups, bots, channels with a common subject that would be interesting to group together.

- Don't forget to let the option to hide categories (or even private chats, groups, bots, channels). It may be a little (or much) embarrassing, for instance, if we have a group that​ eventually (or always) post some porn content so this group goes to the top of the list exactly when we are showing something in the app to other person (like a family member), it's very undesirable.

This will be a very good improvement to the app in terms of usability and privacy.

**Comment by NabiKAZ** [comment]
This have benefits.  
At least User's Chats, Channels, Groups, Bots are needed in separate categories.  
Sample GUI of mobogram:  
![image](https://cloud.githubusercontent.com/assets/246721/26507737/f0f7a4f4-4266-11e7-9028-d3cd8fbce440.png)

**Comment by arny91** [comment]
I think that everybody here would benefit from using a piece of mechanism to sort the chats, for both the mobile and the desktop version. I'm using plus messenger on android and i have tabs, but i'm keeping the mess on the desktop version. Moreover, i'm using Linux, so i don't have many chances.

**Comment by dentra** [comment]
If the tabs do not fit into the ideology of the telegram interface, it is possible that category will represented as a normal contact or chat (with its message counter and settings for notifications) by clicking on which we will see a list of contacts, chats and channels from the selected category. 

If we draw an analogy, then contacts, chats and channels are files, and categories are folders.

**Comment by GreenRobot777** [comment]
Hi there! Anybody have a link to pull-request of something like this feature or fork repository which the realised that functional? I want to realize this by myself, but i have no idea how to start... Thanks! ☮️

**Comment by stek29** [comment]
@GreenRobot777 if you really want I can try to find my old code, but it won't apply and had worst implementation I can think of.

And afaik there is no public fork with this feature implementated. There is however some Iranian fork which violates GPL and OpenSSL's licenses and doesn't provide it's source code.

**Comment by nexfwall** [comment]
@tomcpc
>That being said, is there a place to suggest and discuss feature requests
for Telegram as a whole?


Twitter, maybe? 🙃

**Comment by Line117** [comment]
The end of 2017. Chat-list is a dump. People, bots, channels, work, friends, ...
Everything jumps, nothing to find.

**Comment by stek29** [comment]
The end of 2017. People keep sending comments with same meaning, which can only annoy. 
Please, use reactions and don't comment if your comment doesn't bring anything new.
_Opinion is my own, not @telegramdesktop's or Telegram's_

**Comment by dmitriy-dokshin** [comment]
It's a "must have" feature! It's absolutely impossible to understand what's going on in multiple group chats, bots and so on after some time of usage. It's another problem when Telegram is used for work.

**Comment by klimrmad** [comment]
Definitely required!

**Comment by dmitriy-dokshin** [comment]
And it's worth noting that these categories should be customizable and hierarchical, not only favorites, groups, bots, friends, as suggested at the beginning.

**Comment by AlexanderKochetkov** [comment]
No changes since 2015. New channels every day, contacts list are getting messed up completely.

**Comment by antonavy** [comment]
This can be implemented with tags, for example. Different chats and channels, bots and groups can have tags attached to them.  
You can have the default list as it is now, with tons of everything and impossible to find anything by hand, people getting buried under channels in a sec, even if you'd written a message 10 sec ago.
Then you can have a list with optional tags, that get's filtered by them.

**Comment by HamedBegloo** [comment]
OK it seems it's nearly impossible for Devs to add it to the official apps. While we see many unofficial clients for both Desktop and Mobile devices which feature pre-defined tabs for general categories, I may want to know am I allowed to request from other people to introduce us any new unofficial Telegram client which supports "User-defined"/"User-created" tabs in this thread as soon as they get the information?

Keep in mind there is one Iranian unofficial client for Mobile devices named [Mobogram](https://mobogram.en.aptoide.com/) which can do this( not by tabs however and rather with some sort of drop-down list) but the thing is, there is a strong rumor that this app has an unsafe client-side encryption or maybe even actively violating people's privacy for espionage purposes and being closed-source makes it more probable. **Even [Pavel Durov himself said](https://twitter.com/durov/status/891213634248085505?lang=en) it's a "potentially insecure" app.**

**Comment by AndreyAzimov** [comment]
Please add folders

**Comment by kt3** [comment]
Looking forward for such groups/folder feature.  It would be a point for us to completely migrate all the chats from Slack, which out of the box supports spaces for teams (but IMHO it is the only reason we are using it - it is slow and buggy compared to Telegram).

**Comment by ross999** [comment]
Who pays these developers? Twitter? This is a MUCH needed feature. If you guys can't get it done my developers in NYC can do it.

**Comment by stek29** [comment]
@ross999 Do your cool developers in NYC know how to use Git and how to make a Pull Request on GitHub?

**Comment by ross999** [comment]
They sure do. Why don't you lazy guys do this? People have been asking for 2 years now. What's the problem?

**Comment by stek29** [comment]
This can't be done just on one platform, TDesktop isn't a standalone project, it's part of Telegram.

Speaking of "who pays these developer": nobody pays to me (and @auchri afaik).
Not sure about @john-preston, but likely Telegram pays him. That's another reason why it can't be done separately from other Telegram apps.

**Comment by ross999** [comment]
So it's impossible? 

Appreciate that you guys are working hard for little to no money but Telegram is almost unusable in this form. And this is something that been requested many times or a couple of years. That's why I and others are frustrated that nothing has been done or looks like even attempted.

**Comment by ross999** [comment]
I just realize this is not official Telegram support but the github for a Telegram app? How do I report this to the official Telegram people?

**Comment by anfimovir** [comment]
@ross999 Via Telegram Support (https://telegram.org/support) or Twitter.

**Comment by Banane9** [comment]
I think one possible "bandaid" fix to the whole messy thing would be to assign a higher priority to non-muted chats that have unread messages. So they'd always appear at the top of the list, under the pinned chats.

At least theoretically that should work by just adding a line of

`if (chatLeft.isMuted xor chatRight.isMuted) return chatLeft.isMuted ? chatRight : chatLeft`  
(replace `chatRight` / `chatLeft`) with `-1` / `1` for a compare method)

after the pinned and before the date comparison in a Method that would return the most "important" chat (that should be at the top of the list).

**Comment by PvUtrix** [comment]
We need tabs in the list of channels, it's becoming a horrible mess.
I suggest Contacts / Chats / Custom 1 / Custom 2

**Comment by auchri** [comment]
You can vote here: https://t.me/tgbeta/3500
