### ISSUE TITLE
Group Chat Announce

### ISSUE THREAD

**Issue by itstake** [telegramdesktop/tdesktop#1109]
Please make group chat announce.

how it works:

1.group moderator set message in group setting panel
2.message is pinned bottom of group title

Example:
![cap 2015-09-19 21-58-12-440](https://cloud.githubusercontent.com/assets/5001353/9976282/03df542c-5f1a-11e5-91d6-9f9db405812e.jpg)

**Comment by auchri** [comment]
No API for that
