### ISSUE TITLE
Unsupported characters as link

### ISSUE THREAD

**Issue by gromoleg** [telegramdesktop/tdesktop#1110]
Hello! I send /get effective. 
Power
لُلُصّبُلُلصّبُررً ॣ ॣh ॣ ॣ
冗
to ImageBot and it worked.
After that i tried to forward my message, but got
![q](https://cloud.githubusercontent.com/assets/9316141/9982258/41f3ae9c-5fde-11e5-8613-5075d5775911.jpg)
I think "Unsu" should not be as link.
When I press this link my browser tries to open http://unsu/

**Comment by gromoleg** [comment]
using ubuntu 14.04

**Comment by auchri** [comment]
Is this supposed to look like this?

![unbenannt](https://cloud.githubusercontent.com/assets/5092164/9982276/93d60ce4-5fd6-11e5-9603-ba27d8da4ef1.JPG)
