### ISSUE TITLE
v0.8.57, Linux: Desktop notifications appearing some of the time

### ISSUE THREAD

**Issue by jwflory** [telegramdesktop/tdesktop#1113]
Similar to #1008, but notably different.

I am only subjectively receiving desktop notifications in my Telegram Desktop client. If I am in a different window, I usually will not receive notifications for a new message from a contact. However, it seems if the user sends more messages after the initial message (assuming it's still unread), I sometimes get notifications. Additionally, if I am in a different window in Telegram (e.g. checking the version on the About menu), I will get notifications normally.

Restarting the client fixes the issue some of the time, but either the issue will repeat after a whole or sometimes restarting does not fix it.

I am running Fedora 22, GNOME 3.16.3, Linux 4.1.6-201.fc22.x86_64.

**Comment by stubbs28** [comment]
I am having the same issue, and so are many of the users in my supergroup.

**Comment by jflory7** [comment]
I would like to update this and say I am no longer having this issue on my system. I am now using Fedora 23, GNOME 3.18.3, Linux 4.3.3-303.fc23.x86_64.

**Comment by stubbs28** [comment]
I am using Arch and Telegram Desktop version 0.9.18
Other users in the supergroup are on windows. I don't know if any of them use mac.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after months, closing.
