### ISSUE TITLE
Adding contact to group chat

### ISSUE THREAD

**Issue by crealist** [telegramdesktop/tdesktop#1116]
When creating new group at contact list i see only contacts created automatically by phone or manually by phone. There is no contacts who found me by username, so i can't add them.

**Comment by telegramdesktop** [comment]
@crealist Sorry, no way to add a user to contacts by username, only by phone number. But you can still search by username and add from search.

**Comment by crealist** [comment]
Hm... It's meat that i can add user to group chat only if i know his phone?

**Comment by telegramdesktop** [comment]
@crealist No, you also can write his username and he will be shown in Add Members dialog box.

**Comment by crealist** [comment]
But no! User found me by username. I see him in conversation list.
But in "new group dialog" and in "add member dialog" (to existing) - in both he is absent.

**Comment by telegramdesktop** [comment]
@crealist He is not in the list, but if you type his username (exactly) in the search field, he will appear in search results.

**Comment by crealist** [comment]
But no again. (  "No contacts found".

**Comment by telegramdesktop** [comment]
@crealist Perhaps you type wrong username. Not his name, first name or last name, but username, which is displayed in his profile after @ character.

**Comment by crealist** [comment]
Screenshot 1 https://yadi.sk/i/bwP_wWKljExWp
Screenshot 2 https://yadi.sk/i/idizrbfqjExks

**Comment by telegramdesktop** [comment]
@crealist But this is the name of that user, not username. Can you show me profile of that user? When you open conversation with this user and click on the top bar.

As I can see in global search, there is no user with username "komirina" in Telegram, so komirina does not have that username.

**Comment by crealist** [comment]
You're right! He hasn't @username at profile. )  One way - ask him (her) to write it in settings?
