### ISSUE TITLE
Clicking on element in list of commands leads to crash

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1118]
![image](https://cloud.githubusercontent.com/assets/10401817/10046037/1b29b740-6239-11e5-97df-894f0db83076.png)

When i click on any element in list of command (by typing /) it leads to crash of Telegram.

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov Thanks for your report, this will be fixed soon.

**Comment by telegramdesktop** [comment]
Should be fixed in the last dev version (0.8.59).
