### ISSUE TITLE
Analysis of Telegram source code by PVS-Studio static code analyzer

### ISSUE THREAD

**Issue by InkViziT0r** [telegramdesktop/tdesktop#1119]
Development team of proprietary PVS-Studio C/C++ static analyzer presents their report on the source code of Telegram in the article, which contains the review of the most suspicious code fragments they discovered.

You can read article on the official site:
http://www.viva64.com/en/b/0346/

**Comment by telegramdesktop** [comment]
@InkViziT0r That's interesting, thank you. Some of the highlighted places really are mistakes.
