### ISSUE TITLE
Windows 10 Tablet mode snapping

### ISSUE THREAD

**Issue by Snnlk** [telegramdesktop/tdesktop#1120]
The app doesn't snap to the side when in Windows 10 Tablet mode.
For FYI, I am in the main release (NOT an insider). Testing on a Surface Pro 3.

Can someone confirm (or disprove) that this is happening as well?

**Comment by auchri** [comment]
Works for me
![unbenannt](https://cloud.githubusercontent.com/assets/5092164/10048931/90145e80-6215-11e5-8457-3c099af532ff.png)

**Comment by Snnlk** [comment]
@auchri I meant snapping to the side when using multiple windows. Something like this:
![screenshot 5](https://cloud.githubusercontent.com/assets/4171276/10049080/f6590dee-61e3-11e5-860d-caef2175a3d7.png)
For some reason desktop Telegram (with me) cannot be snapped to the side in Tablet mode, unlike the apps I displayed in the example above.

**Comment by auchri** [comment]
Works for me :)
![unbenannt](https://cloud.githubusercontent.com/assets/5092164/10049359/6a6c2954-6217-11e5-9941-1123ea5c2501.png)

**Comment by Snnlk** [comment]
@auchri It is working for with me now for some reason! I could swear I had this issue recurring for a really long time (including up to yesterday).

Anyways, guess you can label this as closed?

**Comment by auchri** [comment]
Thats strange :D
