### ISSUE TITLE
Opening/hiding main window through tray icon on Windows seems non-intuitive

### ISSUE THREAD

**Issue by GMMan** [telegramdesktop/tdesktop#1122]
Version: Telegram Desktop for Windows 0.8.57

It took me a while to figure out that clicking on the tray icon once opens the main window and double clicking on it hides the window. Most messenger type programs use double clicking to both open and hide their main windows. It would be less confusing to users who start using Telegram after they've used other messenger programs if showing/hiding main window from tray would follow conventions.

**Comment by auchri** [comment]
I don't think this is necessary, because most people will close the window with the close button in the title bar or with alt+F4. In addition, once you know that you can close the window with double click, you know it next time and it's not really confusing.

**Comment by GMMan** [comment]
It's not really the closing part I'm concerned about, but the opening part.
It took me a while to figure out why when I double click on the icon the
window opens then immediately closes (initially I was going to file a bug
that the icon was just plain broken, before I experimented with different
timing in clicks). Most other software opens with double clicking, whereas
this doesn't. That's where the confusion lies.
