### ISSUE TITLE
Document Drag Error when drag the icon on Mac

### ISSUE THREAD

**Issue by ryush00** [telegramdesktop/tdesktop#1123]
<img width="532" alt="2015-09-24 7 23 56" src="https://cloud.githubusercontent.com/assets/4997174/10071078/dbd81e92-62f1-11e5-8709-0d8d6bf0bb21.png">

`This document could not be found in the file system. Try saving the document ‘/Users/ryush00/Library/Containers/org.telegram.desktop/Data/Library/Application Support/Telegram Desktop/Telegram’.`

When I drag the app's icon, the error showed up.

<img width="557" alt="default" src="https://cloud.githubusercontent.com/assets/4997174/10071137/4df005d0-62f2-11e5-8193-2f1f96341424.png">
**this**

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
