### ISSUE TITLE
Two application icons in Ubuntu

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#1127]
Dear all, 

I am shown with two Telegram icons in the launcher of Ubuntu 15.04. Can someone reproduce the problem?

```
ii  telegram                                             0.8.52-0ubuntu0                            amd64        Telegram Desktop
```

![image](https://cloud.githubusercontent.com/assets/170947/10084666/f82a56ec-6304-11e5-9452-296ac858f633.png)

Thankfully,

Robert

**Comment by auchri** [comment]
No, I can not reproduce that

Maybe you installed another application or package

**Comment by orschiro** [comment]
Dear @auchri,

Thanks for your response!

I found that there was an extra `telegram.desktop` placed in `~/.local/share/applications`. I removed the file and the duplicate icon is gone.
