### ISSUE TITLE
Question: how secure is the auto update process?

### ISSUE THREAD

**Issue by ppparadox** [telegramdesktop/tdesktop#1128]
As per title.

**Comment by auchri** [comment]
The issues section on GitHub is for issues and not for questions. I close this now, maybe **telegramdesktop** will answer you.

**Comment by ppparadox** [comment]
You know there's a 'question' label too, do you?

**Comment by telegramdesktop** [comment]
@ppparadox Well, the update is signed with a private key, that is checked before applying the update. So if you have valid TelegramDesktop build on your system (for example, you downloaded it from https://desktop.telegram.org and you assume that it was not changed for the wrong one by man in the middle, who can substitute https requests), then you'll have valid updated TelegramDesktop.

**Comment by ppparadox** [comment]
Great!
