### ISSUE TITLE
Reply to bot message in group doesn't work

### ISSUE THREAD

**Issue by ahmadalli** [telegramdesktop/tdesktop#1129]
When PollBot asks me to answer a poll like here:
![image](https://cloud.githubusercontent.com/assets/2167301/10097008/c642b4fc-6382-11e5-89ea-4cb024a3b8ad.png)
after I click on one of the choices, it doesn't reply the original message:
![image](https://cloud.githubusercontent.com/assets/2167301/10097039/0a13ff06-6383-11e5-952f-7b2a7c62ff9e.png)

**Comment by telegramdesktop** [comment]
@ahmadalli Yes, this bug was introduced in 0.9 and not fixed in 0.9.1. It will be fixed in 0.9.2 version today. Thank you for your report!
