### ISSUE TITLE
Remove history from groupchat

### ISSUE THREAD

**Issue by boodoolak** [telegramdesktop/tdesktop#113]
Не умею по-английски, простите.
Необходима опция очистки истории групчата. 
И категорически необходима опция не хранить историю групчата.
Как пример - джаббер. Хранить последние 10 сообщений, которые подгружать при холодном старте. Либо дать настройку с возможностью указать периодичность очистки. 
Причем привязывать очистку к аккаунту. К примеру очистил я ее на телефоне, и автоматически очистилась на десктопном клиенте. Это очень важно и нужно.

**Comment by auchri** [comment]
It's possible to delete the history of a group

**Comment by realas-data** [comment]
@auchri how? I've tried and it's not letting me. Using the Mac client or the iOS one. It only allows to delete it from my local client, not for everyone (or for the kicked person, for example)

**Comment by telegramdesktop** [comment]
@realas-data There is no way to delete chat messages in someone others inbox. The channels share the history, so it could be done, but groups and private messages have their own copy for each participant and they are "theirs" messages already, they can't be deleted by you.

**Comment by realas-data** [comment]
@telegramdesktop thanks for clarifying, that's what I thought.

**Comment by mautematico** [comment]
Supergroups share messages, just like channels.

I think the thing is there are not any option to 'clear history' for supergroups (as a supergroup admin), while it is for regular groups (as regular member).
