### ISSUE TITLE
ability to copy mobile nummer to clipboard

### ISSUE THREAD

**Issue by Skaronator** [telegramdesktop/tdesktop#1131]

**Comment by telegramdesktop** [comment]
You can right-click in user profile and copy mobile number from there:
![image](https://cloud.githubusercontent.com/assets/6113871/10104348/f5b5dc08-63b1-11e5-8c59-dc6c66d1578e.png)

**Comment by Skaronator** [comment]
Oh didn't know that but it doesn't work on the own profile.

**Comment by telegramdesktop** [comment]
@Skaronator It does work in own profile, it does not work in Settings, but no one thought you'll need to copy your own phone number.

**Comment by Skaronator** [comment]
It does now work in settings, ty for that even if it wasn't because of this issue.
