### ISSUE TITLE
Telegram shows empty language checkbox in profile settings

### ISSUE THREAD

**Issue by tropicoo** [telegramdesktop/tdesktop#1135]
On Windows XP x32 En could be selected language with empty name. After selecting it dialog window appears with empty label and buttons. Screenshots attached.
// Telegram 0.9.2 Portable.

![screenshot 2015-09-26 001](https://cloud.githubusercontent.com/assets/888784/10118198/a5d7a44e-647b-11e5-97e7-7e20e969f266.png)
![screenshot 2015-09-26 002](https://cloud.githubusercontent.com/assets/888784/10118199/a5d7d3f6-647b-11e5-9018-7ed3068b927b.png)

**Comment by auchri** [comment]
Can You See These Chinese Characters?
祝你能夠很愉快的學習中文

**Comment by tropicoo** [comment]
Yes, I see all characters except 4th in my browser.

**Comment by tropicoo** [comment]
I pasted them into Telegram, but they look like empty boxes.

**Comment by auchri** [comment]
Do you have "East Asian Languages" enabled?
![image](https://cloud.githubusercontent.com/assets/5092164/10118315/3c599ab4-6475-11e5-85d4-791f0a10e3e5.png)

**Comment by tropicoo** [comment]
Nope, I've just installed and now it shows characters.

![screenshot 2015-09-26 003](https://cloud.githubusercontent.com/assets/888784/10118404/99b55798-647f-11e5-865d-d7c76bcc3673.png)
![screenshot 2015-09-26 004](https://cloud.githubusercontent.com/assets/888784/10118405/99ba66a2-647f-11e5-8a28-e6bdc9e708cc.png)
