### ISSUE TITLE
Issue tracker for Android?

### ISSUE THREAD

**Issue by mxa** [telegramdesktop/tdesktop#1137]
Where is the issue tracker for the Android app? https://github.com/DrKLO/Telegram I can't submit issues there. Also: on this page https://core.telegram.org/tsi/bugs#messages-not-getting-delivered the link to Trello is dead.

**Comment by auchri** [comment]
@DrKlo has closed the issue tracker. Don't ask me why

**Comment by mxa** [comment]
Let me quote from the document i linked to above:

A note on users

One may think that users are people with problems. Wrong. It is us, who have problems — the user is just a convenient medium for studying them. Our problem is either that something is wrong in our system. Or that we can't understand what the user is doing wrong. When you look at it this way, you quickly realize that the user is our most important asset when it comes to bugs. He can help us identify bugs and improve usability.

So when somebody comes with a problem, we are not looking for a way to make him go away. Instead we must do all we can to not let the user leave before we find the problem. This means that everything you ask him to do must tell you something important. Nobody enjoys rebooting their phone or logging out and in. The general rule is minimum actions — maximum effect.

If you do ask something that requires at least some effort, please be nice about it! People don‘t have any obligations to Telegram — we need to convince them to help us and to thank them when they do. It’s the least we can do.
