### ISSUE TITLE
The native file browser is not used for sending images etc.

### ISSUE THREAD

**Issue by adiultra** [telegramdesktop/tdesktop#1140]
I have installed telegram on elementary OS Freya.
Everything is working fine except that telegram uses an awkward prompt for selecting files or images to send. 

![choose images_085](https://cloud.githubusercontent.com/assets/12121575/10162805/7ea8849a-66cb-11e5-8c4f-21071a61017c.png)

whereas the background choosing dialogue is quite nice

![telegram_084](https://cloud.githubusercontent.com/assets/12121575/10162818/967e2a7a-66cb-11e5-8741-5319c4545d83.png)

Can you please change the default file chooser or use the one of the native OS.

**Comment by auchri** [comment]
Duplicate #438
