### ISSUE TITLE
Blocked user list magically disappears (server side?)

### ISSUE THREAD

**Issue by cabezadepato** [telegramdesktop/tdesktop#1143]
Running OS: iOS 8.4.1 & OSX 10.9.5
My blocked users' list disappeared overnight. No action taken on my behalf, no update. No logs provided as this is no crash and looks like a server side issue. Please solve this asap, it is a privacy violation of the serious kind.

**Comment by telegramdesktop** [comment]
@cabezadepato If it is server-side issue you can write to support about it («Ask a question» menu in Settings), I can't help you with that.

**Comment by cabezadepato** [comment]
I don't know for sure, I haven't debugged the network comms to assert that. I mainly use the desktop client, and it was the first thing I launched this morning. Looks like a server issue, though. Close this one if you feel is unrelated to the client.

**Comment by telegramdesktop** [comment]
@cabezadepato Well, Telegram Desktop app does not have block list display at all, it can unblock a single user only if you click on Unblock button in conversation with him or in his profile. Another OS X application (named just Telegram in App Store), the native one, has blacklist and I'm not sure about it.

**Comment by cabezadepato** [comment]
My bad then. I'm closing this one.
