### ISSUE TITLE
RateStickerBot crashes the desktop app

### ISSUE THREAD

**Issue by jipipayo** [telegramdesktop/tdesktop#1144]
steps to reproduce:

1) start to rate some stickers.
2) delete the last one.
3) click on some stars to rate the deleted sticker.

the full app closes

version 0.9.2 Linux

some trace from dmesg:
[24929.871565] Telegram[6254]: segfault at 18 ip 00000000007ff741 sp 00007ffc09514870 error 4 in Telegram[400000+2315000]

uname -a
Linux  4.1.0-2-amd64 #1 SMP Debian 4.1.6-1  x86_64 GNU/Linux

**Comment by DaFri-Nochiterov** [comment]
:+1: other bot, but same situation
Windows
 TDesktop 0.9.3 dev

**Comment by telegramdesktop** [comment]
@jipipayo Thank you for your report! I will fix that in the next version (keyboard will disappear if the message, that caused it, was deleted).

**Comment by stek29** [comment]
So is it fixed?
