### ISSUE TITLE
Keyboard keeps popping back up on windows 10 if manually closed.

### ISSUE THREAD

**Issue by RusinaRange** [telegramdesktop/tdesktop#1146]
If you close a bot created keyboard from clicking the down arrow or the X on the message it's replying to, select a different chat and come back the keyboard also pops back up.

edit: It would be better to say the keyboard pops up inconsistently.
1) If you go from normal chat to group chat it always pops up
2) if you go from a chat with the keyboard open into another conversation with the bot the keyboard will be open
3) if you go from a chat with no chat open into a 1 on 1 conversation with the bot it does not open the keyboard

**Comment by telegramdesktop** [comment]
@RusinaRange Well, that is the desired behaviour of the custom bot keyboard, you can compare it to other applications behaviour, like iOS app. Perhaps it will be changed in the future, but currently it is intended to work that way.

**Comment by RusinaRange** [comment]
It's intended that it opens up the bot keyboard EVERY time you open a group chat with the bot in it?

Also it doesn't work that way on the android version of the app.

**Comment by telegramdesktop** [comment]
@RusinaRange It should open it until you send a reply to that bot and he hides it after that.

**Comment by RusinaRange** [comment]
Alright, kinda weird that closing the keyboard manually doesn't close it all together.
