### ISSUE TITLE
Ctrl+W Closes Window on OS X, Causes Problems with Delete World Keybinds

### ISSUE THREAD

**Issue by mitsuhiko** [telegramdesktop/tdesktop#1147]
I use Ctrl+W for deleting the last word, but unfortunately on telegram this binds to closing the window.  This has never been a shortcut that does window closing on OS-X.  Instead Cmd+W should close the window.

**Comment by telegramdesktop** [comment]
@mitsuhiko Thanks for your report, I will fix that in the next version.

**Comment by luckydonald** [comment]
Would be perfect with<kbd>cmd</kbd>+<kbd>0</kbd>, which is the typical Mac OS shortcut to bring back the main window. (see e.g. Mail.app)

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by mitsuhiko** [comment]
Seems to work on the current version.
