### ISSUE TITLE
[Feature Request] Custom Colors/ xaml/ skins

### ISSUE THREAD

**Issue by thexbasic** [telegramdesktop/tdesktop#1149]
Hi, my request is the possibility to customize e.g. Colors / use a custom (dark) skin. Because I'm working with a pretty bright screen, sometimes in a darker room and its pretty tiring having the bright Telegram Desktop window there ^^ The feature would be handy for mobile phones too... Skype has the same problem, but I think Telegram has the possibility to make things better, because even compiling the Telegram source (getting the lib's etc) is not that easy...

**Comment by auchri** [comment]
#185
