### ISSUE TITLE
[Bug]can't edit people's names or contact details.

### ISSUE THREAD

**Issue by shirishag75** [telegramdesktop/tdesktop#115]
Hi all, 
There doesn't seem to be way to edit people's names, contact details etc. Could you fix it ? This is on gnu/linux debian 64-bit and tdesktop is at 0.5.16 so it's the latest binary release you released yesterday.

**Comment by gmolledaj** [comment]
Malfermu la konversacion, premi supre dekstre de la nomo en la butono ">".
Se vi ne forlasu redakti klaku aldoni kontakton kaj tiam aktualigi ĝin.

Abre la conversación, pulsa arriba a la derecha del nombre en el botón ">".
Si no sale editar, pulsa en añadir contacto y ahí lo actualizas.

Open the conversation, press top right of the name in the button ">".
If you not view a edit button then click on add contact and to add it.

**Comment by telegramdesktop** [comment]
And what is the problem? You open your contact's profile and click "Edit" on the upper-right corner of the window.
