### ISSUE TITLE
Gnome 3 duplicated icons in favorite list

### ISSUE THREAD

**Issue by WyRe** [telegramdesktop/tdesktop#1150]
When you have got anchored Telegram-desktop icon to favorite list it will appear twice if you have opened Tdesktop.

http://i.imgur.com/2j7bUu1.jpg

**Comment by MichaelTiebesl** [comment]
I use Gnome in Arch and fixed this with a desktop file in /usr/local/bin

**Comment by kanishkablack** [comment]
open up ~/.local/share/applications/Telegram.desktop

Add the following line
StartupWMClass=Telegram

That should solve the issue

**Comment by kanishkablack** [comment]
open up ~/.local/share/applications/Telegram.desktop

Add the following line
StartupWMClass=Telegram

That should solve the issue

**Comment by WyRe** [comment]
@kanishkablack doesn't it ... xD but thank so much for the ideas! :D

**Comment by MichaelTiebesl** [comment]
@WyRe I made a copy from Telegram Desktop in /usr/share/application/ and put that in /usr/local/bin.
I named the copy telegramdesktop.desktop. You have to open the Telegram Desktop in Gedit from /usr/share/application and root and copy as root it into usr/local/bin. That's it.

Every update from Telegram i remove in home in /home/nameuser/.local/share/applications the telegram desktop to get the original Icon again.

**Comment by WyRe** [comment]
Apparently I think that I've solved the issue by substitution of https://aur.archlinux.org/packages/telegram-desktop/ for https://aur.archlinux.org/packages/telegram-desktop-bin-dev/ which is precompiled, so... I guess the problem was in telegram-desktop packaging, maybe I should post this topic in the comments of this AUR package. I'll close that issue because doesn't seem be thing of telegram devs :D

http://i.imgur.com/YV8gdnN.jpg

Sorry for the inconveniences and thank you so much for your time.
