### ISSUE TITLE
[Windows 10] Right click on message leads to window loses focus

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1151]

**Comment by telegramdesktop** [comment]
Right click on message should show you context menu with actions, which of course takes focus from the input field. Or did I misunderstand you?

**Comment by DaFri-Nochiterov** [comment]
Yes, I see context menu and when I click "reply" window lost focus

**Comment by telegramdesktop** [comment]
I can't confirm this, when I right click window looses focus, when I click Reply, window regains focus and focuses input field, Windows 10, Telegram Desktop 0.9.3.dev

**Comment by DaFri-Nochiterov** [comment]
![bandicam_2015-10-03_19-14-42-660](https://cloud.githubusercontent.com/assets/10401817/10262870/f17a2fe2-6a03-11e5-8404-0a198dc6c3b4.gif)

Windows 10, TDesktop 0.9.3 dev

**Comment by telegramdesktop** [comment]
I didn't understand, was the window focused before the right click? Do you use tablet mode or regular mode on regular pc?

**Comment by DaFri-Nochiterov** [comment]
The window had focus.
After clicking the right mouse button the focus is lost (this is normal). 
But after closing context menu it does not return.
-- 
Tablet mode disabled (I don't use it)

**Comment by DaFri-Nochiterov** [comment]
It bug of Windows 10, after switching workspace.
Log off and log in helped me.

**Comment by vozzurg** [comment]
I have only 1 workspace. I logout and login - but its not helped. 
![ec4e2bd4b919c903cdf3b915baef87ca](https://cloud.githubusercontent.com/assets/14953243/10262998/d6970404-69f7-11e5-8167-42f61fc228a9.gif)

**Comment by telegramdesktop** [comment]
@vozzurg I don't see you pressing Reply, seems like you open context menu and then close it by clicking somewhere outside the chat window or what?

**Comment by vozzurg** [comment]
@telegramdesktop I'm sorry, I did not understand the situation in the topic, I thought that a bug - it's when the focus is lost when i open the menu.
when i clicked reply - the focus returns.
