### ISSUE TITLE
[Feature Request] Still getting added to groups from blocked ppl

### ISSUE THREAD

**Issue by thexbasic** [telegramdesktop/tdesktop#1153]
Hi there,
telegram is a great app, but even there are some guys trolling around... sure you can block them, but that doesnt help if youre getting added back to groups and get spammed. Reporting these ppl would be one way, but in my opinion its way to much effort. Also the possibility exists that given ppl have friends or come with other accounts, therefore my desired, "future proof" request is that blocked people can't add you to groups. I guess the problem is not Telegram Desktop related only, so feel free to tell me  whom I may contact regarding this matter.

**Comment by auchri** [comment]
:disappointed: 
Please write the telegram team on [twitter](https://twitter.com/telegram) or with the "Ask a question" feature in one of the apps.

**Comment by telegramdesktop** [comment]
@thexbasic If you blocked someone (added to blacklist), he should not be able to add you to groups. Are you sure it is the same guy — who adds you and who is in your blacklist?

**Comment by thexbasic** [comment]
Yes. I've even tried that with a friend since I thought it shouldnt be possible \: but it was.
I already reinstalled Telegram, but nothing changed.. Gonna contact @Telegram then,
thanks
