### ISSUE TITLE
Add Jabber client functionality

### ISSUE THREAD

**Issue by jeyemwey** [telegramdesktop/tdesktop#1156]
I just realized that Telegram is the only real *chat software* I got installed on my system.

Wouldn't it be nice, if you could also add other chat systems that work on __Jabber/XMPP__ to TDesktop?

I would love to see any feedback to that question!

**Comment by auchri** [comment]
I don't think that will be implemented, because this is a client for the Telegram API only.

**Comment by telegramdesktop** [comment]
@jeyemwey I'm sorry, but that is not planned. Perhaps maybe some fork will do that. Current software is made specifically for MTProto and Telegram API and will stay that way.
