### ISSUE TITLE
Stickers in channels

### ISSUE THREAD

**Issue by hebrew878** [telegramdesktop/tdesktop#1158]
whenever we add a sticker set that was sent by channel admin, telegram desktop lets us send sticker to channel ?

see pictures
![td1](https://cloud.githubusercontent.com/assets/2658040/10303673/fbf19a6a-6c32-11e5-836a-617f14f7e9d4.png)
![td2](https://cloud.githubusercontent.com/assets/2658040/10303676/fddcf914-6c32-11e5-894d-1ccc7d9333b8.png)
![td3](https://cloud.githubusercontent.com/assets/2658040/10303680/04a180c6-6c33-11e5-8410-38996d222994.png)

**Comment by stek29** [comment]
It's fixed for me, pressing on stickers doesn't send anything

**Comment by hebrew878** [comment]
thanks
