### ISSUE TITLE
Show wrong image when click to image preview

### ISSUE THREAD

**Issue by AleshchenkoMaksim** [telegramdesktop/tdesktop#1160]
Program show wrong image in popup window when click on image preview.
I receive message with this image:
![ef7875be4f](https://cloud.githubusercontent.com/assets/1853422/10321517/d825f5d2-6c81-11e5-8e5a-d6f53feb0dc1.png)

but when i click, i see another image from another message:
![82q45e5c4ljgmd](https://cloud.githubusercontent.com/assets/1853422/10321691/b49d7e04-6c82-11e5-99a9-965cb666c1fd.png)

**Comment by Tozzje** [comment]
I have very little to add, except "Me too!".  One thing to add is that the full screen image is displayed with a "Go left"  arrow, but it does nothing when I click on it.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by AleshchenkoMaksim** [comment]
> this bug is still valid on 1.9.8? i remember to see this long time ago, but no anymore.

I have not seen this bug for a long time. It seems it has already been fixed. I think you can close the ticket.
