### ISSUE TITLE
Multiprotocol feature

### ISSUE THREAD

**Issue by sundagy** [telegramdesktop/tdesktop#1162]
Hello!

Part of my friends do not want to install Telegram, and use good old ICQ. Although I like Telegram, and I had to use several apps to communicate with each other. It would be cool to unite in one telegram-shell a several instant messaging protocols. Huh?

**Comment by telegramdesktop** [comment]
@sundagy I'm sorry, but that is not planned. Perhaps maybe some fork will do that. Current software is made specifically for MTProto and Telegram API and will stay that way.
