### ISSUE TITLE
Infinite update

### ISSUE THREAD

**Issue by amoncusir** [telegramdesktop/tdesktop#1164]
# About version
* Version: 0.8.24
* OS: Ubuntu 14.4 LTS

# Issue
Every time, Telegram download and install this version (0.8.24) if checkbox "Update automatically" is checked.

**Comment by telegramdesktop** [comment]
@amoncusir Are you using the version from https://desktop.telegram.org? Is location of Telegram binary (and itself) accessible for writing for the app?

**Comment by amoncusir** [comment]
@telegramdesktop True, it had denied access... Sorry for this, and thanks!
