### ISSUE TITLE
can't input Chinese characters under Linux 64 version

### ISSUE THREAD

**Issue by 4disland** [telegramdesktop/tdesktop#1166]
I'm using fcitx framework(Sougou input method), but I can't input Chinese Characters under linux 64 desktop client.
Hopping to solve this problem asap.:)

**Comment by auchri** [comment]
Maybe #1035 helps

**Comment by 4disland** [comment]
After reviewing [#1035](https://github.com/telegramdesktop/tdesktop/issues/1035), I solved it by exec `QT_IM_MODULE=fcitx /path/to/Telegram`
thanks a lot :smile:
