### ISSUE TITLE
Direct Capture of selectable screen area to send to contact

### ISSUE THREAD

**Issue by corb06** [telegramdesktop/tdesktop#1168]
Previous issues regarding this feature have been closed. 
Trillian instant messenger has this feature built in, it works really good. Telegram should also have this.

Closed: Copy screen to share in conversations #1069
Closed: FEATURE: Webcamera and screenshot support #838

**Comment by corb06** [comment]
Previous issues regarding this feature have been closed. 
Trillian instant messenger has this feature built in, it works really good. Telegram should also have this.

**Comment by auchri** [comment]
Did you read #838?
> For selected area, use your OS's screen capture tool (Snipping Tool on Windows) and just copy the image, then paste it into Telegram's chat box. no need to save file.

> I do agree that integrated screenshots would be even cooler, but probably not worth the work to get it working across all platforms that TDesktop supports.

**Comment by corb06** [comment]
Too bad, would really been great too have a more built in function instead of dealing with copy and pasting and all that. 
Take a look at Trillian messenger for Windows, and youll see what I mean.
https://www.trillian.im/

**Comment by trollcop** [comment]
This guy in 2015 knows what he's talking about. I really don't understand why the developers insist on marking these feature requests wontfix. It would make the client absolutely perfect for work use.
