### ISSUE TITLE
Show better error message when adding too much sticker packs

### ISSUE THREAD

**Issue by AlexMercier** [telegramdesktop/tdesktop#1170]
when added sticker sets over than 200 then when  I try to add more, this App say STICKER PACK NOT FOUND after clicking Add. 
Make it error more clear please. Thanks.

Also web version of telegram show error with description:

```
Method: messages.installStickerSet
Result: {"_":"rpc_error","error_code":400,"error_message":"STICKERSETS_TOO_MUCH"}
Stack: Error
 at h (https://web.telegram.org/js/app.js:18:3312)
 at https://web.telegram.org/js/app.js:18:4530
 at l (https://web.telegram.org/js/app.js:8:11738)
 at https://web.telegram.org/js/app.js:8:11910
 at m.$eval (https://web.telegram.org/js/app.js:8:19316)
 at m.$digest (https://web.telegram.org/js/app.js:8:17747)
 at https://web.telegram.org/js/app.js:8:19403
 at a (https://web.telegram.org/js/app.js:7:2845)
 at https://web.telegram.org/js/app.js:7:4299
 at n (https://web.telegram.org/js/app.js:2:16667)
```

**Comment by auchri** [comment]
It's a server limit, so you have to contact the Telegram support to increase this limit.

**Comment by AlexMercier** [comment]
Please fix this issue. it's not that difficult. Just add one notification...
because "Sticker pack not found" and "Sticker packs is full" it's a two different errors

**Comment by auchri** [comment]
Pull requests are welcome :)

**Comment by AlexMercier** [comment]
@auchri sorry but I'm not windows developer(

**Comment by TechnoAyan** [comment]
The same issue I am facing nowadays? :(

**Comment by AlexMercier** [comment]
not fixed yet :-1:

**Comment by auchri** [comment]
Sticker sets are now archived if you add too much, so this issue is no longer relevant.
