### ISSUE TITLE
Feature : Tray icon Click to Open [request]

### ISSUE THREAD

**Issue by kanishkablack** [telegramdesktop/tdesktop#1171]
Tray icon Click to Open in Linux

**Comment by auchri** [comment]
#992

**Comment by atenrok** [comment]
just upgraded to 0.9.6 stable on FC21 XFCE. Both LMB and RMB click produce a menu instead of bringing the main window to foreground. Regression  or am I doing something wrong?

**Comment by telegramdesktop** [comment]
@atenrok Was it not like that before? I use libappindicator or Qt tray icon if the first is not available.

**Comment by atenrok** [comment]
not since the time #458 has been closed (https://github.com/telegramdesktop/tdesktop/issues/452). Now it is back to weird behaviour.

**Comment by kanishkablack** [comment]
@telegramdesktop in linux on cllick of LMB, should toggle the telegram app like in windows, unlike that both LMB and RMB shows the menu.

**Comment by atenrok** [comment]
v 0.9.10 stable 04.11.15

still brocken. LMB opens a menu instead toggling the main window visibility
