### ISSUE TITLE
[bug?]Can not sent this image by draging it in "Drop photos here" way.

### ISSUE THREAD

**Issue by ruleroller** [telegramdesktop/tdesktop#1172]
Neither 0.8.57 nor 0.9.2 stable can do this.
And 0.9.3 dev still can not do this.

The image only can be sent as a **file**.

You can download this image and give a try.

Photo:

![can_not_sent](https://cloud.githubusercontent.com/assets/3047708/10421830/bd8e69b0-70e2-11e5-8ad1-d48ee9274acb.jpg)

OS: Mac OS X 10.11

**Comment by auchri** [comment]
I can confirm it doesn't work with windows too

**Comment by telegramdesktop** [comment]
Qt 5.5.0 could not read that image, the next version will be based on Qt 5.5.1, which does read and send that image in compressed way (as a photo, not a file).

**Comment by Aokromes** [comment]
this bug was fixed already no @john-preston ?
