### ISSUE TITLE
App takes a while to open (first-launch only)

### ISSUE THREAD

**Issue by mikerockett** [telegramdesktop/tdesktop#1173]
The first time Telegram is launched, it seems to be taking a while - approx. 10-15 seconds. Not sure when this started, but it wasn't like this earlier in the year.

PC-speed is not an issue here, so something is bogging down the app on first-run. If I close and re-open, it only takes about a second, which is fine.

**Comment by telegramdesktop** [comment]
@mikerockett That definitely should not be so. Can you provide some additional details? OS, version, OS version? First time between reinstalls or between log ins or how often? Only when not logged in or sometimes after log in?

**Comment by mikerockett** [comment]
@telegramdesktop I'm running Windows 8 (Build 9200, unfortunately) with TD 0.9.2. This only occurs the first time it is launched after Windows login. If I close it and then re-open, speed is as expected. This has been persistent for over two months now - maybe even longer (can't really remember). For reference, I'm running an i7-4500U with 6GB RAM.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by mikerockett** [comment]
Highly doubt it, but can't confirm because I've moved over to MacOS. Quite sure that, given the technical scope of this issue, it can be closed.
