### ISSUE TITLE
Ctrl+Shift+1 and Ctrl+Shift+2 not working

### ISSUE THREAD

**Issue by Alireza-Mim** [telegramdesktop/tdesktop#1176]
Using the default Persian keyboard on Windows, Ctrl+Shift+1 and Ctrl+Shift+2 should type Zwj and Zwnj characters respectively

On Telegram Windows message box these key combinations are totally stripped and type nothing.

**Comment by Alireza-Mim** [comment]
@telegramdesktop  Can you please assign this to me? Seems like I can't assign

**Comment by auchri** [comment]
We can't assign you, because you are no member of this repo :)
but it would be great if you would work on this :+1:

**Comment by Alireza-Mim** [comment]
1- I will work on this starting tonight or tomorrow night, but I want to make sure that nobody starts doing the same ;)

2- How can I become a member of this repo?

**Comment by auchri** [comment]
> How can I become a member of this repo?
You can't get a member, because then you would have all rights (closing/opening issues/pull requests)

**Comment by Alireza-Mim** [comment]
Oh! I even don't want that :))

**Comment by Alireza-Mim** [comment]
Turns out that it is a bug in Qt. I found the bug, which is caused when they were trying to fix another bug and it is poorly coded. 

Should I change it in our Qt patch and commit?

**Comment by Alireza-Mim** [comment]
@auchri  we can now close this issue

**Comment by auchri** [comment]
@Alireza-Mim thanks for the patch :+1: :)
