### ISSUE TITLE
Create Groups From Desktop Client

### ISSUE THREAD

**Issue by rumdood** [telegramdesktop/tdesktop#1177]
Right now it appears that groups can only be created via the mobile apps. This is a rather annoying oversight for anyone who moves between both mobile and desktop throughout the day.

**Comment by telegramdesktop** [comment]
@rumdood They can be created by the same button to the right of the search field.

**Comment by rumdood** [comment]
Ah, OK. Didn't find that and the FAQ only gives instructions for the mobile clients. Guess this is an issue for the FAQ on the site then. Apologies.

**Comment by knezi** [comment]
Can't you make the button little more intuitive? It does not look like a button for creating a group and I've just spent over a half an hour searching for it, because I did not suspect this button of being it :).

**Comment by stek29** [comment]
@knezi one day...
