### ISSUE TITLE
[Bug] Username dialog is bugged in 0.9.5

### ISSUE THREAD

**Issue by joshery420** [telegramdesktop/tdesktop#1182]
Just some text overlap in the dialog, nothing huge.

![image](https://cloud.githubusercontent.com/assets/849941/10498681/c580998c-7280-11e5-86d3-36587964c939.png)

**Comment by tencrocs** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/9224421/10502402/5c08d796-731e-11e5-8cfb-ea7ac225b42d.png)
I can confirm this as well.

**Comment by telegramdesktop** [comment]
@tencrocs Should be fixed in 0.9.6, please check.

**Comment by DaFri-Nochiterov** [comment]
![image](https://cloud.githubusercontent.com/assets/10401817/10503168/a58a3230-731d-11e5-80e0-299d62fc42dd.png)

@telegramdesktop, fixed

**Comment by joshery420** [comment]
Yep, definitely fixed. Thanks for the quick response @telegramdesktop
