### ISSUE TITLE
[Feature] Make UI animations optional

### ISSUE THREAD

**Issue by fuwaneko** [telegramdesktop/tdesktop#1184]
After updating to 0.9.6 I see a lot of horrible motion blur animations. Please, make them optional (and/or configurable) in settings.

**Comment by telegramdesktop** [comment]
@fuwaneko They are just old animations, but done a little bit faster — with no background redrawal 😆 motion blur is just a side effect ¯\_(ツ)_/¯

**Comment by fuwaneko** [comment]
@telegramdesktop yes, but it's horrible. I'm visually impaired and it literally hurts my eyes. All I ask is a checkbox to disable them completely and/or checkbox to return them back to what it was before.

**Comment by aratno** [comment]
Agree with @fuwaneko. The same animation can be sickening when sped up.

**Comment by f242** [comment]
this animations very slow when i connect to my PC through RDP

**Comment by GuilhermeBCM** [comment]
I use a remote Linux desktop a lot, and animations slows down a lot of things, specially switching chats.
A checkbox to "disable animations/effects" would speed up the application in this scenario.

**Comment by Aokromes** [comment]
aren't animations handled by windows?

**Comment by Aokromes** [comment]
#897 ?

**Comment by S-U-M-1** [comment]
Why has nothing been done about this? All it takes is to add an option to turn off animations (as it was pre-1.0).

**Comment by Remu-rin** [comment]
Fixed in 1.4.0.
