### ISSUE TITLE
About - incorrect url to changelog

### ISSUE THREAD

**Issue by Lazek** [telegramdesktop/tdesktop#1186]
Telegram Desktop 0.9.6

After click to: version 0.9.6

Open next url:
https://desktop.telegram.org/?_hash=changelog

Please update it to:
https://desktop.telegram.org/#changelog

For show changelog after open page.

**Comment by telegramdesktop** [comment]
@Lazek This will be done by server redirect, because Google Chrome on Windows omits hash part of the url when it opens urls from other apps :(

**Comment by Lazek** [comment]
Ohh, I'm test it in Firefox..

**Comment by Lazek** [comment]
Solved :)
