### ISSUE TITLE
Tray icon does not work in the legacy system tray on gnome 3.18

### ISSUE THREAD

**Issue by bedf** [telegramdesktop/tdesktop#1187]
tested on:
Fedora 23 beta 64 bit
Gnome 3.18.0
Telegram Desktop 0.9.6

I have a GNU/Linux computer on which you use the desktop environments Gnome and XFCE. Using Telegram in XFCE icon in system tray works perfectly, closing the Telegram window automatically minimizes to the system tray, however, using telegram in Gnome, no icon appears and when you close the Telegram window the program closes completely (reviewed in system monitor).

Cheers

**Comment by auchri** [comment]
See #1105
