### ISSUE TITLE
cannot create group with one contact

### ISSUE THREAD

**Issue by sigod** [telegramdesktop/tdesktop#119]
I need to select myself in _New Group_ dialog along with another contact. Otherwise it just opens history with that contact.

Also, it would be very useful if one would be able to create a group only with himself (if MTProto allows that).

**Comment by telegramdesktop** [comment]
Well, it is a feature, so you could use New Group box like Contacts box and just open history with him, it is a very rare case you need a group with only one user. You can have conversation with yourself, I'm not sure about a group with only one participant.
