### ISSUE TITLE
How to report bug to telegram team?

### ISSUE THREAD

**Issue by runn1ng** [telegramdesktop/tdesktop#1190]
Hello,

sorry that I bring it here,

I want to report a bug on Android version, but I have no idea where to do that!

Here
https://core.telegram.org/tsi/bugs

I found some information about trello, but there is no link to that mythical trello! Where is it? Or is this manual not for me and only for internal team?

Sorry that it's here, but I just want to report a bug

**Comment by runn1ng** [comment]
This is frustrating. Why don't you have "report bug" anywhere on either website or app itself?

**Comment by auchri** [comment]
Report a bug with the "Ask a question" feature in one of the official apps.

**Comment by runn1ng** [comment]
Oh, I see it now. Sorry for bothering you here. It's very hidden and almost invisible.

**Comment by thebigsmileXD** [comment]
It should really be moved to a more visible place

**Comment by robske110** [comment]
You're here?

**Comment by giocomai** [comment]
For the records, here are the links to relevant Trello boards:
http://help.trello.com/article/709-reporting-trello-bugs

**Comment by danielgomezrico** [comment]
Will be great an issues tab in github since the code is here... then how to track/add issues by developers itself?

**Comment by landry314** [comment]
they dont answer that. also, they have had a dead link to their trello page forever, it is like they dont want the help of users to improve their app, it is disturbing and makes me wonder.

**Comment by giocomai** [comment]
Indeed, they never reply or seem to acknowledge "bug reports" provided via the "ask a question" feature. Also, their bug page is totally misleading, which is a huge waste of time for any well-intentioned person wishing to help them develop better software. It does not even make sense.

**Comment by Blender3D** [comment]
I tried to use "Ask a question" feature, but even after explicitly asking *how* to report a bug, nobody answered. C'mon guys, at least make an issue-only GitHub repository. Anything.

**Comment by stek29** [comment]
@landry314 Trello board is private, not dead.
@giocomai "Their bug page" is for TSI volunteers, not for users.

**Comment by ssd352** [comment]
@stek29 
@TelegramAuditions never answers either.

**Comment by stek29** [comment]
@ssd352 It answers only to questions related to joining TSF, and answers everyone once in a while.

**Comment by slavafomin** [comment]
So, the Telegram team doesn't accept public opinion or feature/bug requests? That's a shame for so openly designed technology.

**Comment by landry314** [comment]
They do, through the filter of a volunteer. Users can not post directly to their board. Try "Ask a Question" in Settings.

**Comment by slavafomin** [comment]
I've tried to write to a support chat couple of times, but there were no responses at all.

**Comment by landry314** [comment]
the volunteer who is named "+42410" on telegram is great. i dont know how you would directly reach him. i have tried to do this in a new chat but cant seem to. luckily i keep that chat open for my needs.

**Comment by stek29** [comment]
@landry314 that number is for lots of volunteers.
Actually you can even chat with multiple volunteers at the same time.

**Comment by Namzhil** [comment]
Hi, always have a problem on Windows 7, x64 - http://joxi.ru/YmEyvvjhE8dEm6

Top border of window creeping me out.

**Comment by jtimon** [comment]
What's the right place to create issues/tickets?
They're not always bugs but wanted features or modifications: for example: use private chat by default in all 1 to 1 conversations, private groups that telegram doesn't have access to (well, has access to the conversations encrypted with keys they don't hold), share files in private groups encrypted so that every person in the group can decrypt the file, but telegram cannot decrypt the file (even if it stores it in its cloud), etc.

**Comment by landry314** [comment]
telegram is hit or miss with their volunteer help. if you are lucky, you will get a volunteer and he was forward your suggestions to their private development board. the closed way they develop their app is disturbing.
