### ISSUE TITLE
problem with opus.sln

### ISSUE THREAD

**Issue by eslamih10** [telegramdesktop/tdesktop#1198]
Hi
When opus.sln to build,I get the   'a' : must return a value d:\tbuild\libraries\opus\win32\vs2010\m.cpp
error,please help me.thanks

**Comment by telegramdesktop** [comment]
need to add something like "return 0;" in this int a() { }, I'll add it soon. Strange that it did compile for me.

**Comment by eslamih10** [comment]
I get the
"entry point must be defined" error

**Comment by telegramdesktop** [comment]
Which Visual Studio version do you use?

**Comment by eslamih10** [comment]
2013

**Comment by telegramdesktop** [comment]
I've tried now and I see, that Debug configuration is not built with that error, but the Release is built successfully, and you only need the Release one. I'll adjust build instructions.

**Comment by telegramdesktop** [comment]
And I see, why it can't be built in Debug, it has wrong Configuration Type. I've updated the "opus" repository, you can check out master branch.

**Comment by eslamih10** [comment]
i get the error in debug mode,i have not problem with release mode!

**Comment by telegramdesktop** [comment]
@eslamih10 Should be fixed already, check out new version from the repository.

**Comment by eslamih10** [comment]
thank you very much
