### ISSUE TITLE
[UI Enhencement] Indicator doesn't respect monochrome style (Ubuntu)

### ISSUE THREAD

**Issue by keunes** [telegramdesktop/tdesktop#1199]
Standard, all indicators in Ubuntu are monochrome. Telegram is an odd one in that area with its coloured background. Though I like the icon as such, I don't like that it's at odds with the rest. But more importantly this renders a problem when the Dash is pulled forward, as the icon becomes a plain circle:
![screenshot from 2015-10-18 14 35 24](https://cloud.githubusercontent.com/assets/11229646/10564460/709a1a00-75b5-11e5-9b09-606c58dc8ced.png) [normal]
![screenshot from 2015-10-18 14 35 13](https://cloud.githubusercontent.com/assets/11229646/10564459/7095886e-75b5-11e5-8553-31a456c7faa3.png) [with dash open]

It would be nice if the icon could be the paper aeroplane with transparent background.

**Comment by telegramdesktop** [comment]
What is "Dash"?

**Comment by keunes** [comment]
The Dash is a part of the Unity interface of Ubuntu. When pressing the super-key (aka Windows key), you get a window in which you can search all installed programmes, content from the web and local files. More: [official info](https://help.ubuntu.com/stable/ubuntu-help/unity-dash-intro.html) and images of the dash](https://www.google.be/search?q=ubuntu+dash&tbm=isch#imgrc=YKsGlYIgUXK0bM%3A)

**Comment by telegramdesktop** [comment]
@keunes Didn't see that problem with the icon there.. Color currently is used for red / gray counter, but perhaps it could be done better.

**Comment by keunes** [comment]
Which problem don't you see? I indicated two problems:
- inconsistency with the indicator area (all icons are monochrome except Telegram)
- icon is indistinguishable when Dash is open (it's a plain circle, you can't see it's Telegram)

Do I understand it correctly that the background colour indicates a status? What do red and grey indicate?

An option for Telegram to indicate statuses would be to have a light-grey (like the other icons) aeroplane for regular status and to A) make the aeroplane blue or B) put a circle around the aeroplane, in case there's a new message. Then the icon could be dark grey if you're not logged-in (or if there's something else wrong such as not being connected to the internet).

*Other examples:*
The bluetooth icon indicates that it's on by being light grey (as is the case above), and when it's off the icon is dark grey. The coffeecup icon (of a program that protects against screensaver) has coffee damp above the cup when it's turned on. The battery icon is filled depending on the battery percentage and turns red when battery status is critical. Dropbox is dark-grey when syncing is paused, and has an exclamation mark in the middle when there's an error.

**Comment by auchri** [comment]
Is it because of #1002?

**Comment by telegramdesktop** [comment]
@keunes I didn't see the blank circle instead of blue icon before in Ubuntu, didn't pay attention to it, only saw it when you described the issue.

Red background of the unread messages counter icon indicates that there are unread messages in not muted conversations, gray unread messages counter icon indicates that all the unread messages are in conversations with muted notifications.

**Comment by keunes** [comment]
@auchri: nope, that has to do with the location of the icon within the Ubuntu filesystem, this is about the actual design of the icon.

**Comment by DeadMetaler** [comment]
White circle it's normal. If you want to change this, icon must be repaint with transparent Airplane logo inside circle, but it can't be white.

**Comment by keunes** [comment]
@DeadMetaler I would argue the white circle is *not* normal; indeed it works as expected from the Ubuntu side, but it is not normal in the sense that these icons are supposed to still be recognisable with the Dash open.

Indeed it is possible to make the Airplane logo transparent, but I prefer my previous proposal (to get rid of the circle and just have the aeroplane as icon). Your proposal would lead to an airplane in any colour (depending on the user's theme settings), something which you want to avoid.
> An option for Telegram to indicate statuses would be to have a light-grey (like the other icons) aeroplane for regular status and to A) make the aeroplane blue or B) put a circle around the aeroplane, in case there's a new message. Then the icon could be dark grey if you're not logged-in (or if there's something else wrong such as not being connected to the internet).

Here's how I imagined it would look like (ltr: new unmuted message, active, not active):
![t_icon_inbar](https://cloud.githubusercontent.com/assets/11229646/10787320/4dcad470-7d70-11e5-9c89-1de44f0a3fc5.png)
![t_icon_indash](https://cloud.githubusercontent.com/assets/11229646/10787659/cc229fd6-7d72-11e5-9029-2b44042bc931.png)
Note that it doesn't look as neat as it's just a mock-up and image boundaries are a bit blurry.

I must admit that I didn't account for a counter in my proposal, but actually I wouldn't miss it. If needed, it could be added similar to current practice.

**Comment by cpriego** [comment]
Yes please!, I've been struggling with this for a long time. There was a temporary solution with the help of https://github.com/bil-elmoussaoui/Hardcode-Tray script but the indicator code changed and it no longer works.

**Comment by bil-elmoussaoui** [comment]
@cpriego i'm the dev of Hardcode-Tray, can you report that there so i can see if can fix it ?Thanks :+1:

**Comment by alexeydemin** [comment]
5 months gone since issue report, every week I get new desktop version but the problem still exists...

**Comment by bicodegas** [comment]
Don't know if this helps or if it is a workaround, but it's working for now.
I installed Telegram from the atareo-team ppa (I'm using Xubuntu Trusty). I changed the icons on ~/.TelegramDesktop/tdata/ticons/ like this:
![captura de ecra_2016-07-02_02-07-14](https://cloud.githubusercontent.com/assets/14196331/16537468/eb9fef3a-3ffa-11e6-866a-c846c1d6e9b8.png)

And now Telegram is using them:
![captura de ecra_2016-07-02_02-11-58](https://cloud.githubusercontent.com/assets/14196331/16537470/eba3c8da-3ffa-11e6-9583-932643908617.png)

![captura de ecra_2016-07-02_02-15-43](https://cloud.githubusercontent.com/assets/14196331/16537517/1e0f39d4-3ffc-11e6-8473-d53869f1b373.png)

(now if I only had a Faenza-Dark type Telegram indicator icon, I would be happy)

**Comment by rival82** [comment]
heres some custom tray icons i made to address this annoyance.

https://github.com/rival82/mono_dark_tray-icons

**Comment by AndydeCleyre** [comment]
Right now I'm using this to get a grey tray icon until there's a new message. You may need a different source image.

```bash
#!/bin/bash
cd ~/.TelegramDesktop/tdata/ticons
rm -r *

# blue -> grey (no messages)
convert /usr/share/pixmaps/telegram.png -modulate 51,0,100 ./ico_22.png

# grey (muted, no messages):
cp ico_22.png icomute_22_0.png

# blue (one message)
cp /usr/share/pixmaps/telegram.png ico_22_1.png

# blue (muted, one message):
cp /usr/share/pixmaps/telegram.png icomute_22_1.png

# blue (more messages)
for f in {2..2000}; do ln -s ico_22_1.png ico_22_$f.png; done
for f in {2..2000}; do ln -s icomute_22_1.png icomute_22_$f.png; done
```

**Comment by cibersheep** [comment]
This is really cool.
It seems that the ico_22_X.png is ¿created on the fly? It would be nice to just modify the original though.
Does someone know if I'm right,  where is it?

**Comment by timorei** [comment]
The one thing I am wondering about: Is there any current desktop environment that's not defaulting to monochrome systray icons? Windows 10 has monochrome icons, plasma, unity, gnome-shell, macos,... They all seem to actually prefer monochrome icons. 

It might be worth considering switching to monochrome tray icons as default.

**Comment by Feichtmeier** [comment]
I used the icons from https://github.com/bil-elmoussaoui/Hardcode-Tray and exported them as png to 
~/.TelegramDesktop/tdata/ticons/
[ticons.tar.gz](https://github.com/telegramdesktop/tdesktop/files/799871/ticons.tar.gz)

**Comment by bil-elmoussaoui** [comment]
@Feichtmeier You don't really need to copy anything by yourself, it's done automatically :) (if  you're using a theme that does include icons for telegram)

**Comment by Feichtmeier** [comment]
I sadly have too because your (really awesome) script sadly doesn't replace the telegram tray icons (we talked about it on your github page). :)
So I converted some of your icons to png and scaled them to 512x512 and renamed them to the same name telegram gave to their icons in that folder and tadaaah

![image](https://cloud.githubusercontent.com/assets/15329494/23321262/fa45ce3e-fade-11e6-93f7-48caed69d652.png)

**Comment by bil-elmoussaoui** [comment]
Can you reopen that issue so I can fix it ?

**Comment by Feichtmeier** [comment]
We talked about it in this issue https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/271
I can't reopen https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/310 because it is not my issue (I believe... total github noob here)

**Comment by Aokromes** [comment]
Maybe better #1908 ?
