### ISSUE TITLE
Url parsing fails on sftp:// protocol

### ISSUE THREAD

**Issue by Robadob** [telegramdesktop/tdesktop#1201]
If you send a url such as sftp://example.com it only parses/highlights ftp://example.com as the url, but sftp is a completely valid protocol (ftp over ssh).

I don't have windows setup to actually do anything with sftp:// addresses though, incase that's relevant.

Running version 0.9.6, Windows 8.1 x64

**Comment by Robadob** [comment]
Just realised the mobile app also makes this mistake, so not sure if it's an intentional bug.

**Comment by telegramdesktop** [comment]
@Robadob Url highlighting is done on server, so it is a server-side issue. I will inform server-side team about the sftp protocol, perhaps they will add it support some day.

**Comment by Robadob** [comment]
This has now been fixed by the server team fyi.
