### ISSUE TITLE
Windows 10 - Touch keyboard doesn't show up

### ISSUE THREAD

**Issue by Tiacs** [telegramdesktop/tdesktop#1202]
When clicking into the chat textfield, the touch keyboard of Windows 10 doesn't show up in Tablet Mode!

Also when opening the touch keyboard manually, the keyboard overlaps the textfield and so you can't see what you are typing.

**Comment by auchri** [comment]
Duplicate #218

**Comment by telegramdesktop** [comment]
@Tiacs Next dev version will be built upon Qt 5.5.1, I hope there this issue will be fixed, but I'm not sure yet.
