### ISSUE TITLE
[Feature request] Option to disable stickers.

### ISSUE THREAD

**Issue by Fruchle** [telegramdesktop/tdesktop#1203]
On data-light connections, and/or a busy channel, stickers can be overly intrusive.

A client-side option to disable their loading and display would be much loved.

I would recommend as separate options: disable all stickers / disable new stickers, so if you already have them it will display. When disabled, to show the original emoji instead.

**Comment by LipkeGu** [comment]
:+1:

**Comment by VitRom** [comment]
Enable / Disable / Load-on-Click ?

**Comment by theus** [comment]
Or block specific pack and able to load on click.

> --

Theus Falcão
Sent by Gmail Mobile

**Comment by auchri** [comment]
#763
