### ISSUE TITLE
Chat list items got duplicated

### ISSUE THREAD

**Issue by emadgh** [telegramdesktop/tdesktop#1205]
Hi, chats got duplicated, seems to be a graphical problem, i know you know why :-D

I just move my mouse on it and it will be gone,

![clip2net_151019234942](https://cloud.githubusercontent.com/assets/411159/10590186/40a2295c-76bc-11e5-902b-7c89feb1f1f2.png)

**Comment by telegramdesktop** [comment]
I've found the bug, it should be fixed in the next (0.9.7.dev) version.
