### ISSUE TITLE
error on telegram.sln

### ISSUE THREAD

**Issue by eslamih10** [telegramdesktop/tdesktop#1206]
when build the telegram.sln i get the "GeneratedFiles\qrc_telegram_emojis.cpp(344770): fatal error C1001: An internal error has occurred in the compiler." error,please help me

**Comment by auchri** [comment]
Which version of visual studio do you use?

**Comment by eslamih10** [comment]
2013

**Comment by auchri** [comment]
Try upgrading to Visual Studio 2015 :)
The new version is required to build the next version of tdesktop.

**Comment by telegramdesktop** [comment]
@auchri "will be required", a lot is changed there and will require to rebuild almost all third party libraries + Qt 5.5.1, so it needs to wait a little.

**Comment by telegramdesktop** [comment]
@eslamih10 Even Debug configuration?

**Comment by eslamih10** [comment]
@auchri "visual studio 2015" is supported in windows 7-32 bit?

**Comment by DaFri-Nochiterov** [comment]
@eslamih10, yes, see here: 
https://www.visualstudio.com/en-us/products/visual-studio-2015-compatibility-vs.aspx

**Comment by DaFri-Nochiterov** [comment]
@eslamih10, yes, see here:
https://www.visualstudio.com/visual-studio-2015-system-requirements-vs#3

**Comment by eslamih10** [comment]
DaFri-Nochiterov,thanks

**Comment by z3ntu** [comment]
@eslamih10 Closed?
