### ISSUE TITLE
TDesktop eats a lot of RAM

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1207]
My friend said that TDesktop eats a lot of RAM. 
I decided to check, and I can confirm it on my PC:
![image](https://cloud.githubusercontent.com/assets/10401817/10602983/e9d685e8-7745-11e5-9f54-ceea0c13968b.png)

**Comment by telegramdesktop** [comment]
Well, sorry, but it does ¯\_(ツ)_/¯

But I'd say, that's a lot:
![image](https://cloud.githubusercontent.com/assets/6113871/10603049/4ba98448-771c-11e5-8cc0-25461979a4ec.png)

:)
