### ISSUE TITLE
Music wont show in Files Section of Shared Media

### ISSUE THREAD

**Issue by ahmadalli** [telegramdesktop/tdesktop#1208]
![image](https://cloud.githubusercontent.com/assets/2167301/10606082/252df454-773d-11e5-9a53-bd86f428ee3c.png)
but I found it via search
![image](https://cloud.githubusercontent.com/assets/2167301/10606094/349cea62-773d-11e5-8630-3987ef732014.png)

**Comment by telegramdesktop** [comment]
@ahmadalli Yes, server does not index audio files in files section. A separate section "N audio files »" will be added in one of the future versions.
