### ISSUE TITLE
Saving images is not possible on OS X

### ISSUE THREAD

**Issue by magicgoose** [telegramdesktop/tdesktop#1209]
there's "save as" dialog, but after "saving" a picture this way, it's not there. Also the setting about download location (on screenshot) does not have any effect.
![screen shot 2015-10-20 at 3 15 10 pm](https://cloud.githubusercontent.com/assets/1442206/10606729/85167422-773d-11e5-9a5e-71380183cea0.png)

**Comment by telegramdesktop** [comment]
@magicgoose Does work for me. What folder do you choose in "save as" dialog that you see? Are you sure it is not write protected?

**Comment by magicgoose** [comment]
I tried with the default one, and after it failed, I manually created `telegram` folder in `~/Downloads`, in both cases my user had full access to them.

**Comment by magicgoose** [comment]
BTW, I use OS X 10.11 (15A284)

**Comment by telegramdesktop** [comment]
@magicgoose well, you right-click on the photo:

![image](https://cloud.githubusercontent.com/assets/6113871/10607759/00fa6398-773c-11e5-9386-f835780fd13c.png)

You choose "Save Image As..":

![image](https://cloud.githubusercontent.com/assets/6113871/10607793/3aa10d72-773c-11e5-9816-38bd3d99213b.png)

You see, which folder is selected there ("Downloads" in my case) and you Save it - and it's there.

**Comment by telegramdesktop** [comment]
The same goes if you right click the photo while viewing it, choose "Save As.." or just choose "Save As.." in the bottom-right corner of the photo viewer. If you click an arrow in the right bottom corner of the photo viewer, you'll get that message:

![image](https://cloud.githubusercontent.com/assets/6113871/10607840/88e6ced6-773c-11e5-94c9-20e8673cfe5f.png)

where "Downloads" link leads you exactly to that new file in Finder.

**Comment by magicgoose** [comment]
In my case, I do exactly this and there's no saved file after that.

**Comment by telegramdesktop** [comment]
@magicgoose and you have the right selected folder in that save dialog? Because sometimes the dialog looks that way:

![image](https://cloud.githubusercontent.com/assets/6113871/10608049/94709d4e-773d-11e5-9f1f-c0da66b817f4.png)

And a location like in that screenshot is selected (the hard drive), there is no way to write a file there.

**Comment by magicgoose** [comment]
Yes I did that right

**Comment by telegramdesktop** [comment]
@magicgoose Do you use the AppStore version? Perhaps you should try the one from https://desktop.telegram.org (or update it, if you already use the one from site).

**Comment by magicgoose** [comment]
![screen shot 2015-10-20 at 4 26 39 pm](https://cloud.githubusercontent.com/assets/1442206/10608376/6bf24ebc-7747-11e5-8b37-86b1f3a33cf5.png)
this is what's in About dialog

**Comment by magicgoose** [comment]
…and I'd rather keep using AppStore version since it's sandboxed

**Comment by telegramdesktop** [comment]
Well, I should check the app store version explicitly, perhaps it is not saving them exactly because of the sandbox.
