### ISSUE TITLE
Typing `>>` gives `»`

### ISSUE THREAD

**Issue by LiaungYip** [telegramdesktop/tdesktop#1210]
Telegram Desktop 0.9.6 on Windows.

When trying to type double angle brackets, i.e. `>>`, the message is instead sent with Unicode `»`.

This makes it confusing to talk about things like shell commands, e.g. `some_command >> appended_output.txt`.

![](http://i.imgur.com/MrTYPcG.png)

![image](https://cloud.githubusercontent.com/assets/2173684/10609617/1b48a166-7777-11e5-8d58-dce2769e6ea4.png)

**Comment by telegramdesktop** [comment]
@LiaungYip Currently it is a feature :(

**Comment by nvx** [comment]
Where is this feature implemented? Is it translating messages before sending to the Telegram servers? Is translation happening in the Telegram servers? Or is it a formatting option when displaying messages?

Perhaps the best way to address this would be to implement a way to send messages with an identifier to say to not apply any formatting.

HipChat for example achieves this by prefixing messages with the literal "/code", the message that follows is then presented in a monospace font as-is without any further processing applied.

**Comment by telegramdesktop** [comment]
@nvx Right now it replaces them before sending to server. Perhaps it will be optional starting with some version.

**Comment by LiaungYip** [comment]
Implementing the backtick syntax for code formatting (as the web client already does?) would also address the issue.

**Comment by auchri** [comment]
fyi duplicate of #522

**Comment by LiaungYip** [comment]
Thanks @auchri .

**Comment by deconstruction** [comment]
I see that the latest tdesktop version implements backtick syntax, which is still not a good solution, since it requires additional manual editing of messages, which is a PITA, especially in case of copy-pasting code. 

What exactly preventing from completely disabling the formatting of messages (by default/by option/by command line switch)? Neither android nor web telegram clients do not cripple messages, why tdesktop do this is beyond me.

**Comment by telegramdesktop** [comment]
@deconstruction When you copy code it is better to wrap it in ticks anyway, code is displayed much better with it.

Option to disable formatting will be added as well.

**Comment by deconstruction** [comment]
@telegramdesktop Such an option would be extremely useful. Thank you for your work, tdesktop is great.
