### ISSUE TITLE
Last seen time not always correctly updated when reconnecting

### ISSUE THREAD

**Issue by matteocontrini** [telegramdesktop/tdesktop#1211]
Hello,
sometimes it happens that when I connect to Wi-Fi after a period of time I was offline, Telegram on Windows takes some time to understand that the connection is available again.
And when it does, I often see that the selected contact is shown as "online" even if it's not. After a minute or so, the contact would go offline and the last seen time would appear as "less than a minute ago". Only exiting the app from the system tray and launching it again appears to correct the issue and to show the right last seen "ago" time.
I compared the online status with other devices and at the moment of the issue to verify that the shown last seen time on desktop was wrong.

I'm using the latest stable release on Windows 10, on a Surface Pro 3.

**Comment by telegramdesktop** [comment]
@matteocontrini We additionaly mark user as "online" when he does some action, like sends you a message, reads your message or sends "typing" status. Perhaps in that case we receive some event, like "message was read by this user" and mark him as online even if the action itself happened already some time ago.

We can check the new message date/time and decide, do we want to mark user as online, but no such timestamp for "typing" status or message read event. I'll think about how it can be fixed.

**Comment by matteocontrini** [comment]
Ah I see now. Thanks for the fast feedback.

I also reported the issue to the official Telegram support but they told me that it was a problem of the speed of my Internet connection (lol).

**Comment by yukuku** [comment]
This issue needs to be fixed quickly, because this is misleading and can cause some quarrel among emotional participants.

**Comment by matteocontrini** [comment]
Up

**Comment by aix27249** [comment]
I have this bug for a long time both on Mac (regardless of OSX version - used a lot on 10.6, 10.7, 10.10 and 10.11) and Linux. After resuming computer from sleep, some (but, not all) contacts last seen date is displayed by the time of reconnection.

Sometimes this is very confusing.

**Comment by 3v1n0** [comment]
Same here on Linux... When suspending my laptop and then back some contacts are showing the last seen as "now", and it keeps showing the wrong timestamp, until I don't restart the app.

**Comment by Danarman** [comment]
I have version 0.9.49 on Windows 10 Pro and same behavior... this should be fixed by now or at least offer a manually refresh option.

**Comment by matteocontrini** [comment]
Does anyone else have the "feeling" that this is now fixed?

**Comment by john-preston** [comment]
@matteocontrini Indeed, this should be fixed in the latest version.

**Comment by rimmi21** [comment]
My husband finds that my last seen shows him online even when i quit telegram .. and this is happening repeatedly .. it's creating issues between us and he thinks am into something else. Would you kindly clarify this issue? I use IOS. And most of the time my last seen shows like "online" even when am offline for about 20-30 minutes. Please solve this issue. Please provide me with a clear cut clarification regarding this issue, as it's serious enough for me as well as my relationship now. Please help ! :-(

**Comment by matteocontrini** [comment]
On iOS, you're automatically put offline when you close the app. If something goes wrong and the app can't do that, the "online" status will expire after 5 minutes.
Just make sure you are not killing Telegram from the "apps switcher" (swiping up), because in that way most of the times you'll have the result of being marked as "online" for another 5 minutes.

**Comment by rimmi21** [comment]
yes i do that Often to save the battery power and run less apps in the background .. but if this is the case then i won't do it anymore. And whenever i am shown online it is not just for 5 mins, rather 10-20 mins sometimes .. still .. Thanks Matteo.
