### ISSUE TITLE
strange bug with ui / telegram closes

### ISSUE THREAD

**Issue by xxxwww** [telegramdesktop/tdesktop#1213]
1 Click on "Settings"
2 Click on avatar
3 Click on uploader nickname
4 Click on "Contact info" in topbar
5 Oh yeah, telegram closes

Telegrams closes with "Error segmentation" message in console
<a href="http://webm.host/f3826/vid.webm" target="_blank">WebmDemo</a>

**Comment by auchri** [comment]
Thanks for reporting! The bug also happens with windows.

**Comment by heejune** [comment]
Tried to repro, but seems it already resolved (0.9.15)
