### ISSUE TITLE
Perhaps I missed something, but...

### ISSUE THREAD

**Issue by TheRubberWolf** [telegramdesktop/tdesktop#1214]
Where was the part where telegram asked permission to notify everyone (including Skype contacts) who had my phone number that I was using the program?

I was shocked that skype contacts started messaging me on telegram the instant I'd joined, more that I hadn't been directly asked if that's what I wanted (It really, really wasn't what I'd wanted.)

If there isn't a mechanism for asking permission or simply informing of this feature, I request that one be added. I personally consider this a rather glaring privacy issue, as the UK Data Protection Act regulates use/misuse of personal data, data like... for example, my mobile phone number.

**Comment by auchri** [comment]
Telegram doesn't inform your Skype contacts, it just send a notification to your contacts that you are using telegram now.

**Comment by KanThorne** [comment]
I think I missed this part too but it broadcast my joining to all of my phone contacts who also used the service which almost immediately negated my use of the service and it did not ask me either.

**Comment by auchri** [comment]
The notification is send by the server so it can't be disabled atm. 
Anyway, that's not an issue of Telegram Desktop.

**Comment by TheRubberWolf** [comment]
So where should I post this issue so it can be resolved? There needs to be a mechanism that asks permission to share my data (the programs I use) over the internet. I did not give my permission, so it shouldn't have happened.

Where can I post this so it may be resolved?

**Comment by telegramdesktop** [comment]
@TheRubberWolf You can contact the support in Settings, this has nothing to do with Skype or Telegram Desktop.
