### ISSUE TITLE
Save space by haing name and time in one line

### ISSUE THREAD

**Issue by lightonflux** [telegramdesktop/tdesktop#1215]
At the moment telegram waste much space with the message bubbles. In a channel with several hundreds messages this can make quite some scrolling distance.

At the moment the messages bubbles have three lines or elements: 

```
 Name 
 Message dsfjkgsd fkdsghjdksfg sjkfgh skfjg ksjfgh ksjfg ks
                                                      23:34
```

I suggest to use the following formatting instead. It would save quite some space: 

```
 Name                                                 23:23
 Message dsfjkgsd fkdsghjdksfg sjkfgh skfjg ksjfgh ksjfg ks
```

**Comment by NXij** [comment]
The time does not increase the size of the paddings anyways, it would not save any space unless the dev decided to decrease the size of the paddings, which could maybe go against the design principles.

**Comment by lightonflux** [comment]
Oh is see. It appears that many people in a channel leave a trailing \n which is why it appears like time has a new line. Does telegram remove trailing spaces or line breaks?

**Comment by NXij** [comment]
mmm... havent noticed people having a empty new line in their messages. The time is just placed in the edge of the textbox, misaligned from the message itself. This is not a \n thing, its just the big padding.
