### ISSUE TITLE
[Feature Request] Separates types of conversations

### ISSUE THREAD

**Issue by TiagoDanin** [telegramdesktop/tdesktop#1219]
Implements an option that can provide a better organization of conversations, Separating Chat | Groups | Channels.
Example of desgin:
![capture](https://cloud.githubusercontent.com/assets/5731176/10650932/26185e4c-782b-11e5-88d8-0d689b612b0e.JPG)
This ugly ... XD of course it won't be like that at the end.

**Comment by auchri** [comment]
See #1107 :)
