### ISSUE TITLE
Change the order of items in tray menu.

### ISSUE THREAD

**Issue by cawa-93** [telegramdesktop/tdesktop#1220]
Please omit the item "Disable notification" down to the item "Exit Telegram".
Because of the open window used to press the first element in the list. And constantly in error disable notifications.

**Comment by z3ntu** [comment]
+1

**Comment by telegramdesktop** [comment]
@z3ntu Should be done already in 0.9.7 dev version.

**Comment by z3ntu** [comment]
In 0.9.7 Dev it is 
"Open Telegram"
"Minimize to tray"
"Disable notifications"
"Quit Telegram"
goddamnit I was a minute too late :/
