### ISSUE TITLE
[Linux] Can't type emojis

### ISSUE THREAD

**Issue by Nixola** [telegramdesktop/tdesktop#1222]
I modified my keyboard layout to include some emoji in empty key combinations, but they just don't work in Telegram (if I try to "type" them, nothing happens). That, coupled with an apparent lack of typing them in other ways, such as using (colon)kissing_heart(colon) or such, can make using emoji really inconvenient. Is it a fixable issue or does it depend on QT? I noticed that another Telegram client that uses QT as well has the same issue

**Comment by telegramdesktop** [comment]
@Nixola I think the symbols just don't get into the input field from Qt at all, because if you copy them from somewhere and paste to the field they work as they should.

**Comment by Nixola** [comment]
Should I create an issue in QT5's repo (and of course close this one) then?

**Comment by auchri** [comment]
@Nixola Does they work in another application?

**Comment by telegramdesktop** [comment]
@Nixola I didn't really check, that it is indeed Qt issue. Should be reproducable somehow in other Qt applications.

**Comment by Nixola** [comment]
It doesn't work in qarma (the only other Qt app I could think of, and I had to be told about it anyway, I think I should open an issue there. Thanks for the help!

**Comment by auchri** [comment]
See http://wiki.qt.io/ReportingBugsInQt

**Comment by Supuhstar** [comment]
This also exists in Windows.
