### ISSUE TITLE
Telegram Icon low resolution

### ISSUE THREAD

**Issue by mxa** [telegramdesktop/tdesktop#1223]
On Alt-tab the telegram Icon is shown uglier then others. Linux Cinnamon ![telegram_icon](https://cloud.githubusercontent.com/assets/1220707/10709250/9d2896d2-7a60-11e5-920d-def4760d634e.png)

**Comment by telegramdesktop** [comment]
I don't know where this one is specified in Qt app :(

**Comment by auchri** [comment]
@telegramdesktop http://www.qtforum.org/article/11098/alt-tab-image.html :)

**Comment by telegramdesktop** [comment]
They are talking about Windows, there I specify icons up to 256x256 in an .rc file :) But I'll try setting something other to application and window as well.

**Comment by mxa** [comment]
Whatever you did it is fixed in the current version! Thanks :+1:

**Comment by telegramdesktop** [comment]
@mxa Wow! Perhaps Qt 5.5.1 got it fixed..
