### ISSUE TITLE
Please consider adding an option

### ISSUE THREAD

**Issue by amiripars** [telegramdesktop/tdesktop#1226]
Hello
Please consider adding an option to Telegram Desktop in order to make it possible to prevent pictures from being loaded automatically. Though this feature is available on mobile, lack of it can be felt on Desktop version and we'd really appreciate it if you could add this option to Desktop version as well. Thank

**Comment by auchri** [comment]
Duplicate #835

**Comment by amiripars** [comment]
???????!!!!!!
Please consider adding an option to Telegram Desktop in order to make it possible to prevent pictures from being loaded automatically. Though this feature is available on mobile, lack of it can be felt on Desktop version and we'd really appreciate it if you could add this option to Desktop version as well.
