### ISSUE TITLE
Markdown in channels

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1227]
Message text:
```
### Hello!
This is my **super-super** channel!
*Welcome!!!* 
```
How it looks:

![image](https://cloud.githubusercontent.com/assets/10401817/10710969/3e8c25ee-7a97-11e5-86ea-60307f896220.png)

**Comment by Nesffer** [comment]
+1

**Comment by auchri** [comment]
Thats not supported by the other clients
