### ISSUE TITLE
"Feature Request": Seperate Chats, Groups and Channels

### ISSUE THREAD

**Issue by komsboymore** [telegramdesktop/tdesktop#1229]
Hello,
I want to send a "Feature Request"
Please separate individual chat with groups and channels. 3 section:

- Individual chat
- Groups
- Channels

With this structure users can check the groups and channels when they want. It should be very useful in all platforms like Android and Windows.

Regards.

**Comment by s4m4n** [comment]
Do you mean having an option to separate view of "Individual Chat" "Group" and "Channel" ? 

I'm sure that it would be useful for many users on different platforms.

+1

**Comment by komsboymore** [comment]
Yep "s4m4n" ...

**Comment by kanishkablack** [comment]
+1

**Comment by auchri** [comment]
Duplicate #1107
