### ISSUE TITLE
hebrew for Telegram Desktop

### ISSUE THREAD

**Issue by shaiho** [telegramdesktop/tdesktop#123]
/*
This file is part of Telegram Desktop,
the official desktop version of Telegram messaging app, see https://telegram.org

Telegram Desktop is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

It is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

Full license: https://github.com/telegramdesktop/tdesktop/blob/master/LICENSE
Copyright (c) 2014 John Preston, https://desktop.telegram.org
*/
direction: "RTL";

lng_maintitle: "Telegram Desktop";

lng_menu_contacts: "אנשי קשר";
lng_menu_settings: "הגדרות";
lng_menu_about: "אודות";
lng_menu_update: "עדכן";
lng_menu_restart: "הפעל מחדש";
lng_menu_start_messaging: "התחל להתכתב";
lng_menu_conversations: "רשימת שיחות";
lng_menu_back: "חזור";

lng_open_from_tray: "פתח את טלגרם";
lng_minimize_to_tray: "מזער למגש המערכת";
lng_quit_from_tray: "יציאה";
lng_tray_icon_text: "טלגרם עדיין פועל ברקע,
אתה יכול לשנות זאת בדף ההגדרות.

אם הסמל נעלם משורת המשימות,
אתה יכול לגרור אותו לכאן חזרה מהסמלים המוסתרים.";

lng_month1: "ינואר";
lng_month2: "פברואר";
lng_month3: "מרץ";
lng_month4: "אפריל";
lng_month5: "מאי";
lng_month6: "יוני";
lng_month7: "יולי";
lng_month8: "אוגוסט";
lng_month9: "ספטמבר";
lng_month10: "אוקטובר";
lng_month11: "נובמבר";
lng_month12: "דצמבר";

lng_weekday1: "שני";
lng_weekday2: "שלישי";
lng_weekday3: "רביעי";
lng_weekday4: "חמישי";
lng_weekday5: "שישי";
lng_weekday6: "שבת";
lng_weekday7: "ראשון";

lng_weekday1_full: "שני";
lng_weekday2_full: "שלישי";
lng_weekday3_full: "רביעי";
lng_weekday4_full: "חמישי";
lng_weekday5_full: "שישי";
lng_weekday6_full: "שבת";
lng_weekday7_full: "ראשון";

lng_month_day: "{month} {day}";

lng_cancel: "ביטול";
lng_continue: "המשך";
lng_close: "סגור";
lng_connecting: "מתחבר..";
lng_reconnecting: "מתחבר שוב בתוך %1 ש..";

lng_reconnecting_try_now: "נסה כעת";

lng_status_service_notifications: "שירות התראות";
lng_status_offline: "נראה לאחרונה לפני זמן רב";
lng_status_recently: "נראה לאחרונה לא מזמן";
lng_status_last_week: "נראה לאחרונה השבוע";
lng_status_last_month: "נראה לאחרונה החודש";
lng_status_invisible: "מוסתר";
lng_status_lastseen: "נראה לאחרונה {when}";
lng_status_lastseen_now: "ממש עכשיו";
lng_status_lastseen_minute: "לפני דקה %1";
lng_status_lastseen_minutes: "לפני %1 דקות";
lng_status_lastseen_hour: "לפני שעה %1";
lng_status_lastseen_hours: "לפני %1 שעות";
lng_status_lastseen_today: "היום ב {time}";
lng_status_lastseen_yesterday: "אתמול ב {time}";
lng_status_lastseen_date: "{date}";
lng_status_lastseen_date_time: "{date} ב {time}";
lng_status_online: "מחובר";
lng_status_connecting: "מתחבר..";

lng_chat_no_members: "הקבוצה לא נגישה";
lng_chat_members: "%1 משתמשים";
lng_chat_members_online: "%1 משתמשים, %2 מחוברים";

lng_server_error: "שגיאת שרת פנימית.";
lng_flood_error: "יותר מידי נסיונות. נסה שוב מאוחר יותר.";
lng_deleted: "לא מוכר";

lng_intro: "ברוך בואך לגירסה הרשמית של [a href=\"https://telegram.org/\"]טלגרם[/a] עבור מחשבים.
זה [b]מהר[/b] ו[b]בטוח[/b].";
lng_start_msgs: "התחל לדבר";

lng_intro_next: "הבא";
lng_intro_finish: "הרשם";

lng_phone_ph: "מספר הטלפון שלך";
lng_phone_title: "הטלפון שלך";
lng_phone_desc: "אנא וודא את קוד קידומת המדינה שלך
והזן את מספר הטלפון שלך.";
lng_phone_notreg: "שים לב: אם עדיין אין לך חשבון בטלגרם,
בבקשה [b]הרשם[/b] עם מכשיר [a href=\"https://telegram.org/\"]iOS / אנדרואיד[/a] או {signup}כאן »{/signup}";
lng_country_code: "קוד מדינה";
lng_bad_country_code: "קוד מדינה לא חוקי";
lng_country_ph: "חיפוש";
lng_country_done: "סיום";
lng_country_none: "מדינה לא נמצאה";
lng_country_select: "בחר מדינה";

lng_code_ph: "הקוד שלך";
lng_code_desc: "שלחנו הודעה עם קוד הפעלה
לטלפון שלך. הזן את הקוד מתחת.";
lng_code_call: "טלגרם יתקשר אליך בתוך %1:%2";
lng_code_calling: "מבקש שיחה משרת טלגרם..";
lng_code_called: "טלגרם חייג למספר שלך";

lng_bad_phone: "מספר טלפון לא חוקי. נסה שוב בבקשה.";
lng_bad_phone_noreg: "מספר הטלפון שלך אינו רשום עדיין.";
lng_bad_code: "הזנת קוד שגוי. נסה שוב בבקשה.";
lng_bad_name: "הזן בבקשה שם פרטי ומשפחה שלך.";
lng_bad_chat_title: "הזן בבקשה שם צ\'ט חדש.";
lng_bad_photo: "נבחרה תמונה לא טובה.";

lng_signup_title: "מידע ותמונה";
lng_signup_desc: "הזן בבקשה אצ שמך
והעלה תמונה.";
lng_signup_firstname: "שם פרטי";
lng_signup_lastname: "שם משפחה";

lng_dlg_filter: "חיפוש";
lng_dlg_conversations: "שיחות";
lng_dlg_messages: "הודעות";
lng_dlg_new_group_name: "שם קבוצה";
lng_dlg_create_group: "צור";
lng_no_contacts: "אין לך אנשי קשר";
lng_contacts_loading: "טוען..";
lng_contacts_not_found: "לא נמצאו אנשי קשר";

lng_settings_profile: "פרופיל";
lng_settings_edit: "ערוך";
lng_settings_save: "שמור";
lng_settings_cancel: "ביטול";
lng_settings_upload: "הגדר תמונת פרופיל";
lng_settings_badsize: "התמונה בגודל לא טוב, נסה בבקשה תמונה אחרת.";
lng_settings_crop_profile: "בחר אזור מרובע מתוך התמונה עבור הפרופיל";
lng_settings_uploading_photo: "מעדכן תמונה..";

lng_username_title: "שנה שם משתמש";
lng_username_about: "אתה יכול לבחור שם משתמש בטלגרם.
אם תעשה זאת, משתמשים אחרים יכולו לחפש אותך
על ידי שם המשתמש וליצור איתך קשר
מבלי לדעת את מספר הטלפון שלך.

אתה יכול להשתמש בתווים a-z, 0-9 וקו תחתון.
אורך מינימלי של 5 תווים.";
lng_username_invalid: "שם המשתמש לא חוקי.";
lng_username_occupied: "שם משתמש זה כבר נמצא בשימוש.";
lng_username_too_short: "שם המשתמש קצר מידי.";
lng_username_bad_symbols: "שם זה מכיל תווים לא חוקיים.";
lng_username_available: "השם זמין.";
lng_username_not_found: "משתמש @{user} לא נמצא.";

lng_settings_section_contact_info: "מידע איש קשר";
lng_settings_phone_number: "מספר טלפון:";
lng_settings_username: "שם משתמש:";
lng_settings_choose_username: "בחר שם משתמש";
lng_settings_change_username: "שנה";

lng_settings_section_notify: "התראות";
lng_settings_desktop_notify: "התראות שולחן עבודה";
lng_settings_show_name: "הצג שמות שולחים";
lng_settings_show_preview: "הצג תצוגה מקדימה של הודעה";
lng_settings_sound_notify: "הפעל צליל";

lng_notification_title: "טלגרם למחשב";
lng_notification_preview: "יש לך הודעה חדשה";

lng_settings_section_general: "כללי";
lng_settings_auto_update: "עדכן אוטומטית";
lng_settings_current_version: "גירסה {version}";
lng_settings_check_now: "בדוק גירסה כעת";
lng_settings_update_checking: "בודק עדכונים..";
lng_settings_latest_installed: "הגירסה האחרונה מותקנת";
lng_settings_downloading: "מוריד עדכון {ready} / {total} Mb..";
lng_settings_update_ready: "גירסה חדשה מוכנה להתקנה";
lng_settings_update_now: "אתחל כעת";
lng_settings_update_fail: "בדיקת עדכון נכשלה עם השגיאה :(";
lng_settings_workmode_tray: "הצג סמל במגש המערכת";
lng_settings_workmode_window: "הצג סמל בשורת המשימות";
lng_settings_auto_start: "הפעל את התוכנה בעת הפעלת המחשב";
lng_settings_start_min: "הפעל ממוזער";
lng_settings_add_sendto: "הוסף את טלגרם לתפריט שלח אל»";
lng_settings_scale_label: "גודל ממשק";
lng_settings_scale_auto: "אוטומטי ({cur})";

lng_settings_section_chat: "אפשרויות שיחה";
lng_settings_replace_emojis: "החלף סמיילים";
lng_settings_view_emojis: "הצג רשימה";
lng_settings_emoji_list: "רשימת סמיילים נתמכים";
lng_settings_send_enter: "שלח הודעה בלחיצת אנטר";
lng_settings_send_ctrlenter: "שלח הודעה בלחיצת Ctrl+Enter";
lng_settings_send_cmdenter: "שלח הודעה בלחיצת Cmd+Enter";
lng_settings_cats_and_dogs: "הצג ברקע כלבים וחתולים";

lng_download_path_dont_ask: "אל תשאל מיקום הורדה עבור קבצים";
lng_download_path_label: "תיקיית הורדה: ";
lng_download_path_temp: "תיקייה זמנית";
lng_download_path_default: "תיקיית ברירת מחדל";
lng_download_path_clear: "מחק הכל";
lng_download_path_header: "בחר תיקיית הורדה";
lng_download_path_default_radio: "תיקיית טלגרם במערכת «הורדות»";
lng_download_path_temp_radio: "תיקיה זמנית, נמחק בעת התנתקות או הסרה";
lng_download_path_dir_radio: "תיקיה אישית, נמחק רק ידנית";
lng_download_path_choose: "בחר תיקיית הורדה";
lng_sure_clear_downloads: "אתה רוצה למחוק את כל הקבצים שירדו מהתיקיה הזמנית? זה נעשה אוטומטית בעת התנתקות או הסרה.";
lng_download_path_failed: "הורדת קבצים לא תצליח. וזאת כיון שמיקום התיקיה שגוי.

אתה יכול לשנות את מיקום ההורדה מההגדרות.";
lng_download_path_settings: "עבור להגדרות";
lng_download_finish_failed: "הורדת קבצים לא הסתיימה.

אתה רוצה לנסות שוב?";
lng_download_path_clearing: "מוחק..";
lng_download_path_cleared: "נמחק בהצלחה!";
lng_download_path_clear_failed: "מחיקה נכשלה :(";

lng_settings_section_cache: "אחסון מקומי";
lng_settings_no_images_cached: "לא נמצאו תמונות במטמון!";
lng_settings_image_cached: "מטמון: {count} תמונה, {size}";
lng_settings_images_cached: "מטמון: {count} תמונות, {size}";
lng_local_images_clear: "מחק הכל";
lng_local_images_clearing: "מוחק..";
lng_local_images_cleared: "נמחק!";
lng_local_images_clear_failed: "מחיקה נכשלה :(";

lng_settings_section_advanced: "מתקדם";
lng_connection_type: "סוג חיבור:";
lng_connection_auto_connecting: "ברירת מחדל (connecting..)";
lng_connection_auto: "ברירת מחדל ({type} בשימוש)";
lng_connection_http_proxy: "HTTP עם שרת מתווך";
lng_connection_tcp_proxy: "TCP עם שרת מתווך";
lng_connection_header: "סוג חיבור";
lng_connection_auto_rb: "אוטומטי (TCP אם זמין או HTTP)";
lng_connection_http_proxy_rb: "HTTP עם http-proxy מותאם אישי";
lng_connection_tcp_proxy_rb: "TCP עם socks5-proxy מותאם אישי";
lng_connection_host_ph: "שם שרת";
lng_connection_port_ph: "יציאה";
lng_connection_user_ph: "שם משתמש";
lng_connection_password_ph: "סיסמה";
lng_connection_save: "שמור";
lng_settings_reset: "סגור חיבורים אחרים";
lng_settings_reset_done: "חיבורים אחרים נסגרו";
lng_settings_logout: "התנתק";
lng_sure_logout: "אתה בטוח שאתה רוצה להתנתק?";

lng_settings_need_restart: "עליך לאתחל על מנת להחיל
חלק מההגדרות החדשות. לאתחל כעת?";
lng_settings_restart_now: "כן, עכשיו";
lng_settings_restart_later: "מאוחר יותר";

lng_topbar_info: "מידע";
lng_profile_settings_section: "הגדרות";
lng_profile_participants_section: "משתתפים";
lng_profile_info: "מידע איש קשר";
lng_profile_group_info: "מידע קבוצה";
lng_profile_add_contact: "הוסף איש קשר";
lng_profile_edit_contact: "ערוך";
lng_profile_edit_group: "ערוך";
lng_profile_phone: "מספר טלפון: {phone}";
lng_profile_enable_notifications: "התראות";
lng_profile_clear_history: "מחק היסטוריה";
lng_profile_send_message: "שלח הודעה";
lng_profile_share_contact: "שתף איש קשר";
lng_profile_delete_contact: "מחק";
lng_profile_set_group_photo: "הגדר תמונה";
lng_profile_add_participant: "הוסף משתמש";
lng_profile_delete_and_exit: "עזוב";
lng_profile_kick: "הוצא החוצה";
lng_profile_sure_kick: "להוציא את {user} מהקבוצה?";
lng_profile_loading: "טוען..";
lng_profile_shared_media: "מדיה משותפת";
lng_profile_no_media: "אין מדיה בשיחה זו.";
lng_profile_photo: "תמונה {count} »";
lng_profile_photos: "{count} תמונות »";
lng_profile_photos_header: "סקירת תמונות";
lng_profile_video: "קובץ וידאו {count} »";
lng_profile_videos: "{count} קבצי וידאו »";
lng_profile_videos_header: "סקירת קבצי וידאו";
lng_profile_document: "מסמך {count} »";
lng_profile_documents: "{count} מסמכים »";
lng_profile_documents_header: "סקירת מסמכים";
lng_profile_audio: "הודעה קולית {count} »";
lng_profile_audios: "{count} הודעות קוליות »";
lng_profile_audios_header: "סקירת הודעות קוליות";
lng_profile_show_all_types: "הצג את כל הסוגים";
lng_profile_copy_phone: "העתק מספר טלפון";

lng_participant_filter: "חיפוש";
lng_participant_invite: "הזמן";
lng_create_new_group: "קבוצה חדשה";
lng_create_group_next: "הבא";
lng_create_group_title: "קבוצה חדשה";

lng_sure_delete_contact: "אתה בטוח, אתה רוצה למחוק את {contact} מרשימת אנשי הקשר שלך?";
lng_sure_delete_history: "אתה בטוח, אתה רוצה למחוק את כל היסטוריית ההודעות שלך עם {contact}?

פעולה זו לא ניתנת לביטול.";

lng_sure_delete_and_exit: "אתה בטוח, אתה רוצה למחוק את כל ההודעות ולצאת מהקבוצה «{group}»?

פעולה זו לא ניתנת לביטול.";

lng_sure_enable_debug: "אתה רוצה להפעיל מצב ניפוי שגיאות?

כל אירועי הרשת שלך יתועדו.";

lng_message_empty: "(empty)";

lng_action_add_user: "{from} הוסיף את {user}";
lng_action_kick_user: "{from} הוציא את {user}";
lng_action_user_left: "{from} עזב את הקבוצה";
lng_action_user_joined: "{from} התחבר לקבוצה";
lng_action_user_photo: "{from} הוסיף תמונת פרופיל חדשה";
lng_action_user_registered: "{from} הצטרף כעת לטלגרם";
lng_action_removed_photo: "{from} הסיר את תמונת הקבוצה";
lng_action_changed_photo: "{from} שינה את תמונת הקבוצה";
lng_action_changed_title: "{from} שינה את שם הקבוצה ל«{title}»";
lng_action_created_chat: "{from} יצר קבוצה בשם «{title}»";
lng_action_checked_in: "{from} התחבר";

lng_forwarded_from: "הועבר מ ";

lng_attach_failed: "נכשל";
lng_attach_file: "מסמך";
lng_attach_photo: "תמונה";

lng_media_type: "סוג מדיה";
lng_media_type_photos: "תמונות";
lng_media_type_videos: "קבצי וידאו";
lng_media_type_documents: "מסמכים";
lng_media_type_audios: "הודעות קוליות";

lng_media_open_with: "פתח באמצעות";
lng_media_download: "הורד";
lng_media_cancel: "ביטול";
lng_media_video: "קובץ וידאו";
lng_media_audio: "הודעה קולית";

lng_in_dlg_photo: "תמונה";
lng_in_dlg_video: "וידאו";
lng_in_dlg_geo: "מיקום";
lng_in_dlg_contact: "איש קשר";
lng_in_dlg_audio: "אודיו";
lng_in_dlg_document: "מסמך";

lng_send_button: "שלח";
lng_message_ph: "כתוב משהו..";
lng_empty_history: "";
lng_willbe_history: "בחר שיחה בבקשה כד להתחיל לשוחח";
lng_message_with_from: "[c]{from}:[/c] {message}";
lng_from_you: "אתה";

lng_typing: "כותב";
lng_user_typing: "{user} כותב";
lng_users_typing: "{user1} ו {user2} כותבים";
lng_many_typing: "{n} כותבים";
lng_unread_bar: "%1 הודעות שלא קראת";

lng_maps_point: "מיקום";
lng_save_photo: "שמור תמונה";
lng_save_video: "שמור וידאו";
lng_save_audio: "שמור אודיו";
lng_save_document: "שמור מסמך";
lng_save_downloaded: "{ready} / {total} {mb}";
lng_duration_and_size: "{duration}, {size}";
lng_choose_images: "בחר תמונות";

lng_context_open_link: "פתח קישור";
lng_context_copy_link: "העתק קישור";
lng_context_open_email: "כתוב לכתובת זו";
lng_context_copy_email: "העתק כתובת מייל";
lng_context_open_hashtag: "חפש על ידי ביטוי";
lng_context_copy_hashtag: "העתק ביטוי";
lng_context_open_image: "פתח תמונה";
lng_context_save_image: "שמור תמונה בשם..";
lng_context_forward_image: "העבר תמונה";
lng_context_delete_image: "מחק תמונה";
lng_context_copy_image: "העתק תמונה";
lng_context_close_image: "סגור תמונה";
lng_context_cancel_download: "בטל הורדה";
lng_context_show_in_folder: "הצג בתיקיה";
lng_context_show_in_finder: "הצג בחיפוש";
lng_context_open_video: "פתח וידאו";
lng_context_save_video: "שמור וידאו בשם..";
lng_context_open_audio: "פתח אודיו";
lng_context_save_audio: "שמור אודיו בשם..";
lng_context_open_document: "פתח קובץ";
lng_context_save_document: "שמור קובץ בשם..";
lng_context_forward_file: "העבר קובץ";
lng_context_delete_file: "מחק קובץ";
lng_context_close_file: "סגור קובץ";
lng_context_copy_text: "העתק תוכן הודעה";
lng_context_to_msg: "עבור להודעה";
lng_context_forward_msg: "העבר הודעה";
lng_context_delete_msg: "מחק הודעה";
lng_context_select_msg: "בחר הודעה";
lng_context_cancel_upload: "בטל העלאה";
lng_context_copy_selected: "העתק טקסט שנבחר";
lng_context_forward_selected: "העבר נבחר";
lng_context_delete_selected: "מחק נבחר";
lng_context_clear_selection: "מחק בחירה";
lng_really_send_image: "אתה רוצה לשלוח תמונה זו?";
lng_really_send_file: "אתה רוצה לשלוח קובץ זה?";
lng_really_share_contact: "אתה רוצה לשתף איש קשר זה?";
lng_send_image_compressed: "שלח תמונה דחוסה";

lng_forward_choose: "בחר נמען..";
lng_forward_confirm: "העבר אל {recipient}?";
lng_forward_share_contact: "שתף איש קשר עם {recipient}?";
lng_forward_send_file_confirm: "שלח את «{name}» אל {recipient}?";
lng_forward_send_files_confirm: "שלח קבצים שנבחרו אל {recipient}?";
lng_forward: "העבר";
lng_forward_send: "שלח";

lng_contact_phone: "מספר טלפון";
lng_enter_contact_data: "איש קשר חדש";
lng_edit_group_title: "ערוך שם קבוצה";
lng_edit_contact_title: "ערוך שם איש קשר";
lng_edit_self_title: "ערוך את השם שלך";
lng_confirm_contact_data: "איש קשר חדש";
lng_add_contact: "צור";
lng_add_contact_button: "הוסף איש קשר";
lng_contacts_header: "אנשי קשר";
lng_contact_not_joined: "למרבה הצער {name} עדיין לא הצטרף לטלגרם, אבל אף פעם לא מאוחר. שלח לו הזמנה.

אנחנו נספר לך על כל איש קשר שהצטרף לטלגרם.";
lng_try_other_contact: "נסה אחר";
lng_contacts_done: "ביטול";

lng_drag_images_here: "גרור תמונה לכאן";
lng_drag_photos_here: "גרור תמונות לכאן";
lng_drag_files_here: "גרור קבצים לכאן";

lng_drag_to_send_quick: "כדי לשלוח אותם במהירות";
lng_drag_to_send_no_compression: "כדי לשלוח אותם ללא דחיסה";
lng_drag_to_send_documents: "כדי לשלוח אותם כמסמך";

lng_selected_clear: "ביטול";
lng_selected_delete: "מחק";
lng_selected_forward: "העבר";
lng_selected_count_1: "הודעה %1";
lng_selected_count_5: "%1 הודעות";
lng_selected_cancel_sure_this: "אתה רוצה לבטל העלאה זו?";
lng_selected_delete_sure_this: "אתה רוצה למחוק הודעה זו?";
lng_selected_delete_sure_1: "אתה רוצה למחוק הודעה %1?";
lng_selected_delete_sure_5: "אתה רוצה למחוק %1 הודעות?";
lng_selected_delete_confirm: "מחק";

lng_emoji_no_recent: "סמיילים אחרונים יהיו כאן";

lng_about_version: "גירסה {version}";
lng_about_text: "תוכנת מסרים מידיים רשמית חינמית מבוססת על [a href=\"https://core.telegram.org/mtproto\"]MTProto[/a] ו
[a href=\"https://core.telegram.org/api\"]Telegram API[/a] מהירה ומאובטחת

תוכנה זו היא ברשיון תחת [a href=\"https://github.com/telegramdesktop/tdesktop/blob/master/LICENSE\"]GNU GPL[/a] גירסה 3,
קוד המקור לתוכנה נמצא באתר [a href=\"https://github.com/telegramdesktop/tdesktop\"]GitHub[/a].

תורגם לעברית על ידי שי הורן";
lng_about_done: "סיום";

lng_search_no_results: "לא נמצאו הודעות";
lng_search_one_result: "נמצאה הודעה {count}";
lng_search_n_results: "נמצאו {count} הודעות";
lng_search_global_results: "תוצאות חיפוש";

lng_mediaview_save: "הורד";
lng_mediaview_forward: "העבר";
lng_mediaview_delete: "מחק";
lng_mediaview_single_photo: "תמונה בודדת";
lng_mediaview_group_photo: "תמונת קבוצה";
lng_mediaview_profile_photo: "תמונת פרופיל";
lng_mediaview_n_of_count: "תמונה {n} מתוך {count}";
lng_mediaview_doc_image: "מסמך";

lng_mediaview_saved: "התמונה נשמרה לתיקיית [c]ההורדות[/c] שלך";

lng_new_authorization: "{name},
זיהינו התחברות לחשבון שלך מהתקן חדש ביום {day}, {date} בשעה {time}

התקן: {device}
מיקום: {location}

אם זה לא נעשה על דעתך, באפשרותך לעבור לתפריט וללחוץ על — סגור חיבורים אחרים.

תודה,
צוות טלגרם";

// Mac specific

lng_mac_choose_app: "בחר תוכנה";
lng_mac_choose_text: "בחר תוכנה לפתיחת המסמך \"{file}\".";
lng_mac_enable_filter: "הפעל:";
lng_mac_recommended_apps: "תוכניות מומלצות";
lng_mac_all_apps: "כל התוכניות";
lng_mac_always_open_with: "פתח תמיד באמצעות";
lng_mac_this_app_can_open: "תוכנה זו יכולה לפתוח את \"{file}\".";
lng_mac_not_known_app: "אנחנו לא יודעים אם תוכנה זו יכולה לפתוח את \"{file}\".";

lng_mac_menu_about: "אודות טלגרם";
lng_mac_menu_preferences: "העדפות...";
lng_mac_menu_file: "קובץ";
lng_mac_menu_logout: "התנתק";
lng_mac_menu_edit: "ערוך";
lng_mac_menu_undo: "בטל";
lng_mac_menu_redo: "בצע שוב";
lng_mac_menu_cut: "גזור";
lng_mac_menu_copy: "העתק";
lng_mac_menu_paste: "הדבק";
lng_mac_menu_delete: "מחק";
lng_mac_menu_select_all: "בחר הכל";
lng_mac_menu_window: "חלון";
lng_mac_menu_contacts: "אנשי קשר";
lng_mac_menu_add_contact: "הוסף איש קשר";
lng_mac_menu_new_group: "קבוצה חדשה";
lng_mac_menu_show: "הצג את טלגרם";
// Keys finished

**Comment by telegramdesktop** [comment]
When language is approved as an official one it would be done through Transifex:
https://www.transifex.com/projects/p/telegram-desktop

Before that you can only use your own translation files through Alt+Shift+Click on Change Language and selecting your own .strings file.

**Comment by DovyLive** [comment]
I have new hebrew..
