### ISSUE TITLE
Telegram tray icon can not be interacted with in gnome

### ISSUE THREAD

**Issue by rbieb** [telegramdesktop/tdesktop#1230]
This is the output of "telegram -startintray"

```
libs init..
loading appindicator3 with version 1..
could not load appindicator3 without version.
loading appindicator with version 1..
loaded appindicator with version 1!
loading gtk-x11-2.0 with version 0..
loaded gtk-x11-2.0 with version 0!
loaded gtk funcs!
loaded appindicator funcs!
status icon api loaded
(Telegram:5765): GLib-GObject-WARNING **: gsignal.c:2451: signal 'child-added' is invalid for instance '0x3caa7c0' of type 'GtkMenu'
```

The icon itself does show up, but it can not be clicked.

**Comment by DeadMetaler** [comment]
Have same problem. No tray icon If i launching Telegram from Dash menu, but if i launch Telegram from double clicking on .desktop or binary file, it's present. Gnome Shell 3.18.

**Comment by ThiagoLopes** [comment]
@rbieb @DeadMetaler 
Telegram need "libappindicator-gtk3" for tray icon.

**Comment by DeadMetaler** [comment]
@ThiagoLopes 
In my system no any libappindicator, but Telegram has tray icon with lauchin from ~/.local/share/Telegram.desktop
https://youtu.be/m7kryAZGT58

**Comment by ThiagoLopes** [comment]
You can see here: https://aur.archlinux.org/packages/telegram-desktop-bin/

> libappindicator-gtk2 (libappindicator-activate-gtk2) (optional) – to hide Telegram in the tray bar (GTK2-based desktop environment)
libappindicator-gtk3 (libappindicator-activate-gtk3) (optional) – to hide Telegram in the tray bar (GTK3-based desktop environment)
libappindicator-sharp (libappindicator-activate-sharp) (optional) – to hide Telegram in the tray bar (Unity-based desktop environment) 

It depends on the system you are using, try searching for something in the repository of your system.

**Comment by Aokromes** [comment]
#1217 ?

**Comment by DeadMetaler** [comment]
Now Telegram working with Gnome and tray perfectly and without  non-Gnome package like libappindicator-gtk3.

**Comment by DecimusXIV** [comment]
Installed libappindicator and libappindicator-gtk3, but icon does not show up (though clickable) on Fedora 25 with Cinnamon 3.2.1
