### ISSUE TITLE
Only Music Mode for the Telegram Player

### ISSUE THREAD

**Issue by BluscreamFanBoy** [telegramdesktop/tdesktop#1232]
A Filter for the Music Player that detects if the file is a song or a sound or something other so that I can choose to play only music

**Comment by telegramdesktop** [comment]
@BluscreamFanBoy I don't clearly undestand what do you want but I'm almost sure it won't be implemented.

**Comment by BluscreamFanBoy** [comment]
I use telegram for sharing free mixtapes with other and also I use telegram to send sound memes. In my workflow of hearing music I just want to use the telegram player like every other music player only for music. So can integrate a only music mode for the current telegram player.

**Comment by telegramdesktop** [comment]
@BluscreamFanBoy It plays all audio files that are in the current conversation. Perhaps such files should not be marked as audio files at all, go to "files" shared media section (instead of "audio files"), and not be played by in-app media player at all. But then there needs to be a way to understand, that it is such a "not-really-audio" file.

**Comment by BluscreamFanBoy** [comment]
There are different ways to solve the problem.
1. Deleted Option for a Entry of the current Playlist (my recommendation: without deleting the file from the conversion)
2. Detect the File or Name as Music
2.1 Try to get around with detecting this things as music with the metadata
2.2 Try to use regex Pattern for detecting normal songs some of them looks [tracknumber]. [title].[format] or some looks like this [tracknumber]. [title] [prod|feature|feat|...] [[Audio|Video] by] [Artists].[format] or some integrate the normal Music Directory stuff in their title [artist] - [album] - [title].[format]
2.3 Try to solve the thing with a song recognizer
3. Tag Audio Files

**Comment by telegramdesktop** [comment]
@BluscreamFanBoy Such things are not planned currently, sorry. Except maybe for the first (somehow manage playlist), but currently playlist _is_ the "shared audio files", which are determined by server, not by the app. All removings from this list will be saved only locally, not in cloud and only till relogin, so currently it won't be implemented.
