### ISSUE TITLE
Telegram crash when trying to disable notifications

### ISSUE THREAD

**Issue by frunc** [telegramdesktop/tdesktop#1234]
I'm using win7 with telegram v0.9.6

When is Telegram closed and you start it first time. Before you write passcode press right click on telegram in tray and try to disable notifications.

It crushs every time

**Comment by telegramdesktop** [comment]
@frunc That should be fixed in the last dev versions, please check: https://desktop.telegram.org/#dev-version

**Comment by frunc** [comment]
Yes. It's fixed in dev version
