### ISSUE TITLE
Curly braces in url issue

### ISSUE THREAD

**Issue by Kaos1337** [telegramdesktop/tdesktop#1235]
Hello,
I would report an url parsing issue, look this url https://betacenter.avira.com/project/forum/topic.html?cap=A788D05206E74FEC88A6C705F84F23E7&forid={FA14F5D1-44B8-442D-8B52-5A6F3708DE8D}
It's from a betacenter provided by Centercode software. It contains curly braces that break the link.
Can you parse an url with that type of braces too?
Thank you.

**Comment by auchri** [comment]
Works now :)
![image](https://cloud.githubusercontent.com/assets/5092164/10831715/7b70fe00-7e87-11e5-8f24-b4bcabe784a0.png)
