### ISSUE TITLE
[Feature Request] Hide contact list

### ISSUE THREAD

**Issue by robertgc** [telegramdesktop/tdesktop#124]
Personally, I don't need the contact list open all the time.

**Comment by jgiak92** [comment]
I prefer a list of existing conversation, like on telegram web or the android application

**Comment by ezdev128** [comment]
I'm agree with this opinion. I like to have some button to hide contact list.

**Comment by Arttse** [comment]
And where is the privacy? I would like to hide my phone number from contacts. One of the reasons i don't want my phone number was collected in a database.

**Comment by auchri** [comment]
Only conversations are now shown
