### ISSUE TITLE
Sometimes passcode input doesn't work

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#1243]
Sometimes, when I launch Telegram on Windows 10 it focus on passcode line (as usual) but I can't input nothing.
Then I click on passcode line once more and input starts working.

**Comment by c0der404** [comment]
And sometimes it **doesn't** focus on passcode line when I launch it.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
