### ISSUE TITLE
Usage of diversity popup panel for body part emojis is not clear, unlike Android version

### ISSUE THREAD

**Issue by ali-shamakhi** [telegramdesktop/tdesktop#1245]
the scenario:
If you select [one of these emojis](http://www.unicode.org/reports/tr51/#Subject_Emoji_Modifiers) for the first time, a popup panel appears for selecting the skin color. From now on, this selection is set for that emoji to be its default option, so on further clicks on that emoji brings up the popup panel. (this goes for each one of them)

I think people usually want to use the default standard [non-realistic yellow color](http://www.unicode.org/reports/tr51/#non-realistic), not to mess with the popup panel (specially fast-typers by keyboard and mouse that use a variety of these emojis).
By the way, those who really want to use a different skin color, probably are aware of how to bring up the panel by click-n-holding on it (also, a right click even would be great).

I've seen people saying "Why does'nt color options appear anymore?", because they've seen it appear the first time but didn't bother to use, now they have no idea how to bring it back.

It should always popup by a simple click on emoji, or not showing up at all (show when holding or right-clicking). The second is better and faster, since the Android version implemented this way too.

**Comment by telegramdesktop** [comment]
@ali-shamakhi Current behaviour was taken from iOS, where it goes like that: first time you choose the color, then you choose by long tap. But the right click could be added as well, I suppose.

**Comment by ali-shamakhi** [comment]
I didn't know about iOS, but I think this issue is different from smartphones since you are using real keyboard for typing. This may sound like a personal subject, but may improve usage experience on desktop, worth studying ;)

At least, the right click support could be handy.

**Comment by telegramdesktop** [comment]
@ali-shamakhi Typing from keyboard has almost nothing to do with skin color. The only thing is that emoji substituted by text replacement use the same color that you have chosen the last time in the picker.

**Comment by ali-shamakhi** [comment]
@telegramdesktop Yes, typing from keyboard has nothing to do with emojis at all (if you do not use keyword shortcuts), but the color panel may become annoying. consider this:

- John usually doesn't use emojis, maybe just using 👍 and 👎 . Now he is typing a long text and somewhere in the text he uses 👌 by clicking in emoji panel. After hitting the send button, he finds out there is no 👌 in the text, because he didn't wait to choose its color (he didn't need to wait for 👍 or 👎, he had chosen the color before).

I believe this is a common issue for heavy keyboard users, specially those who are new to Telegram Desktop.

**Comment by telegramdesktop** [comment]
@ali-shamakhi I don't think that is an issue. If you choose an emoji from panel, you definitely see if it appeared in the field or not. Didn't hear any complaints about that either.

**Comment by maryht** [comment]
I do agree with MR Shamakhi. Some times we need to install telegram on new devices or in the same device for times for several reasons . It's not efficient to choose the emojies' colors for first time by force. It is really on my nerve! =))
Because I don't see any need to choose the colors except I want to!  So choosing colors for the first time is not a good point and choosing by right click is so nice for me. It would be enjoyable! !

**Comment by telegramdesktop** [comment]
@maryht If we leave only right click almost everyone will never know that there is not yellow color at all :)

**Comment by auchri** [comment]
It would be great if I choose the color for the first time, the color of *all* emojis gets changed (so I don't have to change for each emoji) (#756 btw)

**Comment by ali-shamakhi** [comment]
@telegramdesktop yeah, better speak for myself about typing experiences!

@auchri I believe the first popup is for showing the ability of changing colors to new users. If so, there us no reason to show this first-time-experience for other emojis. I think it has more meaning if all emojis change color when you select for one, like you say. But this will limit user's freedom in his/her own way of usage. maybe an option in setting would be useful in this case.

**Comment by maryht** [comment]
@telegramdesktop 
But I also think that for the next times almost every one will never know that the color can be changed! 
thanks for your answers:)

**Comment by megan657** [comment]
I think having Right Click would be great. When you're just leisurely chatting the current state is fine. But when you're in a hurry or you're just a fast typer it becomes a problem. You said people wouldnt know the yellow color exists if you just have right click,well I didnt know there were any other colors left other than yellow for a few days(android ver)because they all just turned yellow one day but I figured it out eventually.people will get it after a while I don't think thats an issue.

**Comment by telegramdesktop** [comment]
@megan657 I said if there is only one way to change the color — by right click, they won't ever see colors other then yellow :) but perhaps change all of them to the first chosen color and show a tooltip about changing it further by right click (for each emoji separately) will be the right behavior.

**Comment by ali-shamakhi** [comment]
@telegramdesktop agreed :+1:

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Comment by MrEduar** [comment]
Any updates on this?
