### ISSUE TITLE
Wrong Shared Media display after clearing chat history

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#1246]
After I cleared chat history, there are still some links that display in Shared Media section.
When I click any of them it forwards me to appropriate menu that is already empty.
Then after returning to chat menu all these links disappear from Shared Media section as it should be once after clearing history.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
