### ISSUE TITLE
[Bug] Sending files to channels

### ISSUE THREAD

**Issue by ali-shamakhi** [telegramdesktop/tdesktop#1247]
I believe this is a client bug. Telegram Desktop uses internet traffic to upload the file, but the file will not be delivered to the channel.
![capture](https://cloud.githubusercontent.com/assets/10486368/10870920/2eb59d56-80ed-11e5-8b8a-b76125e45e4e.PNG)

**Comment by auchri** [comment]
In addition, I can drag and drop a file to a channel, and it's "sent", even if I'm not an admin of the channel.

![image](https://cloud.githubusercontent.com/assets/5092164/10870932/d9d298f2-80d8-11e5-907e-3d1b1519642d.png)
(Official telegram channel)

**Comment by ali-shamakhi** [comment]
@auchri but no delivered "tick" at all. I think the server doesn't allow this.

**Comment by auchri** [comment]
@ali-shamakhi Yes, that would not make much sense :smile:

**Comment by auchri** [comment]
Will be fixed in next version
