### ISSUE TITLE
Support multiple file copy/paste to send files

### ISSUE THREAD

**Issue by ali-shamakhi** [telegramdesktop/tdesktop#1248]
Copy/Paste one file inside a conversation pane will bring a sending prompt.
![capture](https://cloud.githubusercontent.com/assets/10486368/10871012/93ed949c-80ef-11e5-85c8-868753d2dfcb.PNG)
Being able to copy/paste multiple files at once will be a useful feature. By the way a maximum number of allowed files (5 for example) should be set to prevent messy prompts.

**Comment by telegramdesktop** [comment]
@ali-shamakhi I think it should be one prompt, like "do you want to send 100 files?" :)

**Comment by auchri** [comment]
+ list of the file names? :)

**Comment by telegramdesktop** [comment]
@auchri I don't think you need the names, if you don't remember, what you've selected, you won't send them :)

**Comment by ali-shamakhi** [comment]
@telegramdesktop then you have 100 file-uploading tiles between you and the last message :)

**Comment by auchri** [comment]
@telegramdesktop But if I select one file by mistake? :stuck_out_tongue_winking_eye:

**Comment by DaFri-Nochiterov** [comment]
+1 :octocat:
