### ISSUE TITLE
Disable auto downloading musics after playing

### ISSUE THREAD

**Issue by Noise47** [telegramdesktop/tdesktop#1249]
I have a problem, when I download and listen to a music, if there are other musics posted after it, telegram will begin to download automatically and it's so irritating.
I have this problem in Windows and don't know if other versions are like this.

**Comment by telegramdesktop** [comment]
@Noise47 After music is played the player moves to the next song, so it is getting downloaded to start playing instantly. All other Telegram apps behave the same.

**Comment by ali-shamakhi** [comment]
The player has a shuffle option and a playlist menu, what is the purpose of playlist if you can't add or remove tracks from it ?

**Comment by auchri** [comment]
@ali-shamakhi 
See #1232 
> Such things are not planned currently, sorry. **Except maybe for the first (somehow manage playlist)**

**Comment by telegramdesktop** [comment]
@ali-shamakhi The player has not :) I'm speaking not about some player app, but about the player in telegram desktop. No way to make a cloud-synced shuffle right now, the playlist is just the shared audio files section.

**Comment by ali-shamakhi** [comment]
@telegramdesktop I know the limits :)  . At least you could remove some tracks from that playlist, couldn't you?

**Comment by telegramdesktop** [comment]
@ali-shamakhi By deleting the messages :)

**Comment by ali-shamakhi** [comment]
@telegramdesktop OK . but that's not fair!

**Comment by Noise47** [comment]
you can add an option for this. I don't want to download all the other songs. I just want to listen to one song I have downloaded and it's really bothering me.

**Comment by telegramdesktop** [comment]
@Noise47 Well, if you stop the player after the one, it will download not all the other songs, but just only one next.

**Comment by Noise47** [comment]
the problem is i do not listen to one song in my whole life! I download one song and listen to it and telegram downloads the next one that I clearly don't want to download. then I download another song and it tries to download the next one. by the end of the month I wanted to listen to 200MB of songs but i have downloaded over 400MB of songs.
and your answer is not helping this problem :)
