### ISSUE TITLE
Inline videos and gif files

### ISSUE THREAD

**Issue by mattrick16** [telegramdesktop/tdesktop#1251]
I think it would be great have have inline gif files and video files. This would have the normal "play" button overlay on them before playing, but instead of opening in the external service, it would be inlined into the chat.

I'd love to see this feature and hope to see it implemented :)

Thanks!

**Comment by telegramdesktop** [comment]
@mattrick16 Gifs are played inline for a long time already.

**Comment by mattrick16** [comment]
@telegramdesktop 

Gifs that are linked externally do not though.

**Comment by auchri** [comment]
For inline videos see #29

**Comment by auchri** [comment]
@mattrick16 Yes, and as long as the server does not fetch the images, this should not be implemented
