### ISSUE TITLE
Feature request: search by username

### ISSUE THREAD

**Issue by thiagopnts** [telegramdesktop/tdesktop#1252]
I'm not sure if its possible, but it would be nice to support a twitter-like search by username, e.g:

`from:username whatever msg`

**Comment by auchri** [comment]
I'm not sure atm but you can search for usernames with `@username`

**Comment by thiagopnts** [comment]
Yes, what I'm proposing is more related to searches inside a group. Right now we can search a group's messages by typing whatever we want to find. I'm proposing a filter by username to this search

**Comment by telegramdesktop** [comment]
@thiagopnts Search is done on server and there is no way to search for messages from a specific user in a group in API, so I can't add it :(
