### ISSUE TITLE
Client doesn't switch output devices

### ISSUE THREAD

**Issue by zackpollard** [telegramdesktop/tdesktop#1253]
When changing default output device on windows 10 (unsure if other operating systems are affected) the client will not also change output device. This means that if I switch to my headset, any audio from telegram will continue to come out of the speakers and will only switch device if I exit telegram entirely and reboot it after making the switch.

This is confirmed to still be the case in the latest release and dev versions of the client, version 0.9.6 and 0.9.8 respectively at the time of writing.

**Comment by auchri** [comment]
Duplicate #776
