### ISSUE TITLE
Telegram for windows not working

### ISSUE THREAD

**Issue by jordillonchesteve** [telegramdesktop/tdesktop#1258]
Hi, since last week, Telegram for Windows 0.9.6 stoped working partially. The minimize, maximize and close buttons don't work, as well as the majority of buttons inside the program. Is there anyone else experiencing the same problems?? I installed several versions and the dev ones as well, but still doesn't work.
- Here you can see a screen capture with the buttons not working circled: http://screenshot.net/xyel3c5.jpg
- After uninstalling I am stuck on the first page :'( http://screenshot.net/el4nnhw.jpg

I have a Windows 10 version and haven't done any changes on the system before that happened.

Thanks a lot.

**Comment by telegramdesktop** [comment]
@jordillonchesteve No idea, I develop and use it in Win10 and everything works fine :( portable version?

**Comment by jordillonchesteve** [comment]
@telegramdesktop same problem here. I believe it's a missunderstanding between Telegram and Windows. I deleted all the logs of the registry editor after uninstalling, but nothing.
Is there a way I can send you some logs of what's going on?

**Comment by telegramdesktop** [comment]
@jordillonchesteve Need to check all versions (portable), one by one :) I'll give you an url list, what was the last working version?

**Comment by telegramdesktop** [comment]
Try from the first one (0.9.2 stable version), will it work? After launch disable autoupdate in Settings and then check the buttons and stuff in one after the other:

https://updates.tdesktop.com/tsetup/tportable.0.9.2.zip
https://updates.tdesktop.com/tsetup/tportable.0.9.3.dev.zip
https://updates.tdesktop.com/tsetup/tportable.0.9.4.dev.zip
https://updates.tdesktop.com/tsetup/tportable.0.9.5.zip
https://updates.tdesktop.com/tsetup/tportable.0.9.6.zip

**Comment by jordillonchesteve** [comment]
Nothing works. I get stuck on the initial page of the app: 
![image](https://cloud.githubusercontent.com/assets/7152949/10923834/6a965152-8283-11e5-86fa-e3de6a7e6a6d.png)

**Comment by telegramdesktop** [comment]
Something went wrong with the shadows as well %)

I have no idea what is wrong with your particular case :( Did it work ever?

**Comment by jordillonchesteve** [comment]
Yes! That's why I uploaded the picture. It's the first time it ever happens. I was a heavy happy user of the app and now I am struggling to survive with my phone app... I feel so frustrated. I don't know what can I do...

**Comment by telegramdesktop** [comment]
@jordillonchesteve Did you try system restart? :)

**Comment by jordillonchesteve** [comment]
yes, several times and also between installations.

**Comment by auchri** [comment]
maybe your graphic card is dying?

**Comment by jordillonchesteve** [comment]
Thanks @auchri. That might be a thing. I recently started using my nvidia to speed up the app. Maybe I broke something. I am gonna update the firmware and see if that helps.

**Comment by auchri** [comment]
Did you changed something in the NVIDIA Control Panel? That might be the cause of this problem.

**Comment by jordillonchesteve** [comment]
Nothing. I tried all configurations on the NVIDIA Control Panel, but still not working.

**Comment by Aokromes** [comment]
@jordillonchesteve if you still have problems with this, can you try underclocking your gfx?

**Comment by jordillonchesteve** [comment]
@Aokromes thanks, but nothing... I might be the only one with this problem...

**Comment by guru245** [comment]
I have the same problem. I am using Surface pro4 in Windows 10.
