### ISSUE TITLE
Right mouse click option: marks as unread

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#1259]
Dear all, 

Would it be possible to add a feature by which the user can use the right mouse click option on a conversation to mark a conversation as unread again?

This is useful once you've read a conversation but want to mark is so you won't forget to check it again. 

Thanks for your opinion!

~ Robert

**Comment by auchri** [comment]
Mark messages as unread is not supported by the api

**Comment by orschiro** [comment]
That's a pity to hear. 

Thanks for the feedback!

~ Robert

**Comment by p91paul** [comment]
Is there any way to move this issue upstream so that the feature is added to the api?

**Comment by stek29** [comment]
@p91paul Twitter or In-App support
