### ISSUE TITLE
Crash when saving .rar attachment

### ISSUE THREAD

**Issue by retifrav** [telegramdesktop/tdesktop#1260]
The application craches when I try to **Save File As...** on `.rar` attachment.

How to reproduce: send a `.rar` file to yourself, then click on it with right button, choose **Save File As...** and either save it or click Cancel - the application will crash.

I have *v0.9.9 dev* and *Windows 8.1 x64*.

**Comment by JIghtuse** [comment]
Not reproducible on Fedora 23.

**Comment by telegramdesktop** [comment]
@retifrav Thank you for your report, that will be fixed in the upcoming stable version.

**Comment by LipkeGu** [comment]
:+1: can reproduce it on Windows 10 Pro x64 - it crashes right after the cancel action...

**Comment by telegramdesktop** [comment]
@LipkeGu it should not crash in 0.9.10 stable version. Are you sure you try that one?
