### ISSUE TITLE
Voice messages wont play if 2 or more sound output devices active Telegram0.9.6 (Windows 7)

### ISSUE THREAD

**Issue by Hanzie82** [telegramdesktop/tdesktop#1262]
Hello,

First of let me tell you i like Telegram very much.
Been avid user for a long time now on Android and (bit later) on Windows too

But i've come across what i think is a bug.
Backstory: For normal use i use the analog speaker (5.1) output of my soundcard. And have the other devices disabled. But for some movies i do like to use optical out. And for normal working i dont really have to disable the optical as my media software switches automagicly.

Problem with Telegram is when i don't disable the optical the voice messages wont play. The time doesnt even change as if it stops imideatly.
But if i disable the optical output in Windows's sound panel it all works like it should.

Using up to date Windows and drivers. (I checked).

Sysinfo: 
Operating System
	Windows 7 Ultimate 64-bit SP1
CPU
	AMD Phenom II X4 980
RAM
	16,0GB Dual-Channel DDR3 @ 668MHz (9-9-9-24)
Motherboard
	ASUSTeK COMPUTER INC. Crosshair V Formula (Socket 942)
Graphics
	PLX2483H (1920x1080@60Hz)
	PLE2200 (1680x1050@60Hz)
	PLE1900 (1280x1024@75Hz)
	2048MB ATI AMD Radeon HD 6900 Series (ASUStek Computer Inc)
	1024MB ATI AMD Radeon HD 5700 Series (XFX Pine Group)
	CrossFire Disabled
Audio
	Realtek High Definition Audio (onboard)
Sysinfo by speccy.

**Comment by auchri** [comment]
I think that's because of https://github.com/telegramdesktop/tdesktop/issues/418
