### ISSUE TITLE
Text in message input remains semibold if last message ends with ~

### ISSUE THREAD

**Issue by Bullsquid** [telegramdesktop/tdesktop#1263]
This one started in version 0.9.10 after #27 fix.
STR:
1) Write a message ending with ~ (tilde) symbol
2) Send it
3) Write something else in message input
4) Text you input is now semibold unless you send it / delete it.
![2015-11-05 00-10-37 screenshot](https://cloud.githubusercontent.com/assets/8293030/10953737/5916afd8-8352-11e5-8c3d-d1258d825edc.png)

**Comment by telegramdesktop** [comment]
@Bullsquid Didn't test that thing enough :( Thanks for the report, I'll fix that in the next versions.
