### ISSUE TITLE
Tilde ~ still is dash in search bar

### ISSUE THREAD

**Issue by JuanPotato** [telegramdesktop/tdesktop#1264]
![image](https://cloud.githubusercontent.com/assets/9531780/10954586/65d0058e-831c-11e5-8db5-2092d8557490.png)

**Comment by telegramdesktop** [comment]
@JuanPotato Yes, that would be as long as the QLineEdit control is used there. Some day it will get replaced with a new one, like in Edit group box, and then it will be fixed there as well.

**Comment by JuanPotato** [comment]
@telegramdesktop Wow you reply fast, thanks for the info.

**Comment by telegramdesktop** [comment]
@JuanPotato I use https://telegram.me/GitHubBot for that :)

**Comment by JuanPotato** [comment]
@telegramdesktop Thank you for showing me this. :D Using it to get notified my [Legofy](https://github.com/JuanPotato/Legofy/) program.

**Comment by giordano** [comment]
Well, I'm still seeing the tilde as a dash also in messages and message input.  Should I open another report?

**Comment by telegramdesktop** [comment]
@giordano What TDesktop version do you try? OS version?

**Comment by giordano** [comment]
TDesktop 0.9.10, I updated my comment, OS is an up-to-date Debian testing.

**Comment by telegramdesktop** [comment]
@giordano And how is the conversations list displayed in your case? Are the names of the users / groups displayed semibold font or regular? Should be something like that:
![image](https://cloud.githubusercontent.com/assets/6113871/10955868/043bf0fe-8325-11e5-97c8-dee8f0833e6f.png)

Thats how it looks in Debian for me:
![image](https://cloud.githubusercontent.com/assets/6113871/10956054/4638bea0-8326-11e5-87e9-5624bb2d09e2.png)

**Comment by giordano** [comment]
> @giordano And how is the conversations list displayed in your case? Are the names of the users / groups displayed semibold font or regular? Should be something like that:

No, I see everywhere `-` in place of `~` and the user/groups/channels are displayed as regular.  I'm sure I'm using 0.9.10 because TDesktop tells me so and now pop menu look better than the GTKish there were before.

**Comment by telegramdesktop** [comment]
Looks like it fails to read the semibold font, so the names are displayed incorrectly (regular instead of semibold) and tildes as well (regular instead of semibold), so fix is not actually working :(

**Comment by DeadMetaler** [comment]
Arch Linux ~ Gnome Shell 3.18
![2015-11-05 16-10-59](https://cloud.githubusercontent.com/assets/10463702/10969320/9ce7eda4-83d8-11e5-910f-2581d288cb3b.png)

**Comment by stek29** [comment]
Isn't this fixed?

**Comment by DeadMetaler** [comment]
Fixed long time ago for me.

**Comment by giordano** [comment]
Not for me (Telegram Desktop 1.1.7 on Debian Testing)

**Comment by john-preston** [comment]
@giordano Not fixed in the search bar yet :( it uses an old input field.

**Comment by DeadMetaler** [comment]
@john-preston 
Arch Linux
Stock freetype
Telegram 1.1.2

![2017-05-31 12-23-41](https://cloud.githubusercontent.com/assets/10463702/26625247/35331be2-45fc-11e7-8a26-7f3f6b41bffd.png)

**Comment by john-preston** [comment]
@DeadMetaler Maybe you use not 100% interface scale in Settings?

**Comment by giordano** [comment]
Indeed setting scaling at 125% solves the issue (I can see the tilde in both search box and input field), but I'd prefer keeping scaling at 100%.

**Comment by DeadMetaler** [comment]
@john-preston I'm using 100% interface scale.
Tested with downloaded binary and compiled with system Qt.

**Comment by Aokromes** [comment]
it's fixed, but you may need to zoom to see it's tilde and not dash.
