### ISSUE TITLE
X11 selection stopped working in 0.9.10

### ISSUE THREAD

**Issue by ralesk** [telegramdesktop/tdesktop#1266]
On X11 (Linux, BSD, etc.) there are typically two copy buffers: the classic X11 one where things go when you select an area and you paste with the middle click, and the clipboard provided by your desktop environment.

When I selected the update message and tried to paste with middle click in another window, I got an old selection pasted so something might be obscuring the selection copy event.

**Comment by telegramdesktop** [comment]
@ralesk Are you sure it worked before 0.9.10? It is a custom-written selection, I'm not sure it ever worked that way.

**Comment by ralesk** [comment]
I fairly often paste with middle click, I guess I would have noticed it long ago.  But I'm not 100% sure.

**Comment by giordano** [comment]
It never worked with text of sent messages, it always worked (and still works) with text in message input field.  See bugs #530 and #961.

**Comment by ralesk** [comment]
Thanks, strange I never noticed so far. Closing this, further conversation in #530.
