### ISSUE TITLE
Channel administrators can not add members to their channel

### ISSUE THREAD

**Issue by java-boy** [telegramdesktop/tdesktop#1268]
I have created a Channel and added some administrators to it.
They can send messages to the channel but can not add members, I need them to be able to add members but not add admins.
Or you can add a check box to channel settings to check it by channel creator and let other admins to add members too.
Best wishes.

**Comment by telegramdesktop** [comment]
@java-boy As I know they can't do that in any Telegram client, not only TDesktop. This is a server-side restriction, API allows only channel creator to invite members. He can give the invitation link to other admins, and they can share that link with the people they are inviting.

**Comment by java-boy** [comment]
@telegramdesktop thanks for your response.
Where is the server side code in github?
How can I ask server side developers to add this feature to server API?
I think that will be a good feature to let administrators to add members too.

**Comment by AhrimanSefid** [comment]
yes.
plz add item for add other admin add members.

**Comment by yottanami** [comment]
+1

**Comment by behnamsobhkhiz** [comment]
+1

**Comment by Hamidnwo** [comment]
+1

**Comment by AhrimanSefid** [comment]
+1
