### ISSUE TITLE
Tabs are trimmed in code blocks if it's the first line

### ISSUE THREAD

**Issue by AngeloG** [telegramdesktop/tdesktop#1269]
Pasting the following code inside of a code block: (including the tabs)

		print("Hello, ");
		print("world!\n");

Will result in the first tabs being trimmed (due to it being the first part of the message, if you type some text before the code block, it's fine):

![](https://4o4.nl/20151105oTbVj.png)

**Comment by telegramdesktop** [comment]
@AngeloG The message is always trim-ed on server, so I'm afraid I can't fix that.

**Comment by AngeloG** [comment]
Hm, wouldn't the ``` count as a starting character?

**Comment by telegramdesktop** [comment]
@AngeloG It is not handled on server, you're sending just text and the intervals, where you apply the formatting. So that it is up to client app to decide, how it allows the input.

**Comment by AngeloG** [comment]
How is this transferred to the server then? On the mobile app I just see the text, so how does the formatting get applied for other tdesktop users?

**Comment by telegramdesktop** [comment]
@AngeloG The app gets plain text + intervals (where and what formatting starts and stops), so it is sent to the server as well. So trim does bad work here, because trim-ed get the plaintext.

**Comment by AngeloG** [comment]
Ah, understood. That's a shame.
