### ISSUE TITLE
Notification minimizes full screen applications

### ISSUE THREAD

**Issue by Christilut** [telegramdesktop/tdesktop#127]
Some full screen applications lose their full screen state when a notification occurs. Notably this happens in Battlefield 3 for me, but there may be other applications that have this issue. 

Maybe suppress notifications when something is fullscreen or make sure they pop up below the full screen application.

**Comment by telegramdesktop** [comment]
Notifications should not be shown now while fullscreen app is shown (from 0.7.10 version).

**Comment by programcoder** [comment]
please make it a setting or something, because It's really important for me to see notifications on a video playblack, which didn't annoy me neither did it minimized my video.
