### ISSUE TITLE
Text formatting as bold, italic/emphasized, underlined and strikethrough

### ISSUE THREAD

**Issue by genosonic** [telegramdesktop/tdesktop#1271]
The idea is to support the formatting of text like on Google+ (or like Markdown, but this one only has bold and italics) by wrapping text between certain characters. For example, writing `*bold text*` would produce **bold text**.

Example possibilities:

* Underscore signs ( _ ) for _emphasized/italic text_.
* Asterisks ( * ) for **bold text**.
* Minus signs ( - ) for strikethrough text.
* Double underscore signs ( __ ) for underlined text.

This feature could allow a mix of these formattings, for example:  `*_bold and italic_*` would publish as **_bold and italic_** text.

This builds on the recently implemented idea of monowidth code, wrapped in backticks ( ` ), which works very similar to this.

**Comment by Cameri** [comment]
+1 for support, shouldn't be hard to implement given that we now have backticks for blocks of code.

**Comment by JuanPotato** [comment]
+1, but iirc only bots are able to send those, they are supported. Just not for users.

**Comment by genosonic** [comment]
Comment along with closing maybe?

**Comment by auchri** [comment]
> +1, but iirc only bots are able to send those, they are supported. Just not for users.

**Comment by okutane** [comment]
Can one become a bot?

**Comment by stek29** [comment]
@okutane there's no need to -- it's not an api issue anymore

**Comment by BlkPingu** [comment]
> > +1, but iirc only bots are able to send those, they are supported. Just not for users.

What was the idea behind this @auchri ? Telegram users need this, along with better markdown support like code highlighting

**Comment by stek29** [comment]
@BlkPingu there are already options for everything api supports.

> better markdown support

that's an api issue

> code highlighting

#250
