### ISSUE TITLE
Some emoji's seem to be broken on desktop version

### ISSUE THREAD

**Issue by chaosdrop** [telegramdesktop/tdesktop#1273]
Since the second to last mobile update I think it was the one that introduced "New/enhanced emoji's" I've been getting a lot of little white boxes [] on my desktop version.

**Comment by telegramdesktop** [comment]
@chaosdrop New emoji from OS X 10.11.1 / iOS 9.1 are not supported yet.

**Comment by auchri** [comment]
@chaosdrop See #1196
