### ISSUE TITLE
In monospace code blocks the leading space on the first line is trimmed

### ISSUE THREAD

**Issue by Fsmv** [telegramdesktop/tdesktop#1275]
To reproduce send:

<pre lang="no-highlight"><code>```
          this line has leading spaces
      so does this one
```
</code></pre>

It will appear as:
![](http://i.imgur.com/BaBhh2S.png)

It should preserve the leading spaces on the `this line has leading spaces` line

**Comment by auchri** [comment]
Duplicate #1269 
Please search for existing issues before crearing new ones
