### ISSUE TITLE
Tdesktop not synchronized channels with applications from other platforms.

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1276]
Tested on:
Fedora 23 (gnome).
Telegram desktop 0.9.10

Common cases:
- If you add a channel from Tdesktop, is not synchronized in "Telegram web" or "Telegram for Android".
-  If you delete a channel from Tdesktop, is not synchronized in "Telegram web" or "Telegram for Android".

Note: In some cases Telegram web synchronizes the channels (random behavior).It could be an error Telegram for Android?

**Comment by ali-shamakhi** [comment]
This includes unread badge count for new posts on channels. If you check new posts from TDesktop, they will not be marked as read on other platforms.

**Comment by kanishkablack** [comment]
there seems to be bug, just faced it

**Comment by Aokromes** [comment]
i have seen this sometimes.
