### ISSUE TITLE
[Feature Request] Open the app window when switching to telegram using keyboard

### ISSUE THREAD

**Issue by zhongwei-z** [telegramdesktop/tdesktop#1278]
When using `CMD + Tab` on OS X to use the app switcher to switch to Telegram, it would be nice if the window can be opened if it has been closed previously. In this way the user would not have to click on the icon (or using other ways) to open up Telegram. This can be done in the native Telegram for OS X.

**Comment by toioski** [comment]
@zhongwei-z this is a killer feature, I switch back to macOS Telegram only to have this feature!

**Comment by john-preston** [comment]
Should be fixed in the 1.0.12 release.

**Comment by fiedl** [comment]
Could you make this configurable? I've noticed the changed behaviour immediately as it significantly differs from the behaviour of standard apps like [Apple's Messages app](https://support.apple.com/en-us/HT202549).

### Desired behaviour

This is how Apple's Messages app behaves.

**Closing the tdesktop window with `Cmd+W` or clicking the window "x"**
- the window disappears
- the dock icon stays opaque
- the window is really closed, not just hidden, and cannot be seen anymore with window preview tools like [hyperdock](http://hyperdock.bahoom.com)
- the application stays active, i.e. the menu bar still shows "Telegram" and does not switch to another application
- when switching to tdesktop using `Cmd+Tab` from another application, the application is activated, i.e. the tdesktop menu top bar is visible, but the window won't open

**Hiding the tdesktop window with `Cmd+H`**
- the window disappears
- the dock icon becomes transparent
- the window isn't closed but only hidden. It does have a preview image with hyperdock
- another application becomes active, i.e. the menu bar does not show "Telegram" anymore
- when switching to tdesktop using `Cmd+Tab` from another application, the application is activated and the window is opened

### Observed behaviour

This is how tdesktop behaves after 1.0.12.

**Closing the tdesktop window with `Cmd+W` or clicking the window "x"**
- the window disappears
- the dock icon becomes transparent
- the window isn't closed but only hidden. It does have a preview image with hyperdock
- another application becomes active, i.e. the menu bar does not show "Telegram" anymore
- when switching to tdesktop using `Cmd+Tab` from another application, the application is activated and the window is opened

**Hiding the tdesktop window with `Cmd+H`**
- the window disappears
- the dock icon becomes transparent
- the window isn't closed but only hidden. It does have a preview image with hyperdock
- another application becomes active, i.e. the menu bar does not show "Telegram" anymore
- when switching to tdesktop using `Cmd+Tab` from another application, the application is activated and the window is opened

As you can see from this comparison, the correct "close-window" behaviour has disappeared. Now, "close window" behaves like "hide window".

**Comment by john-preston** [comment]
@fiedl Why do you want to leave Telegram application active while the window is closed?

**Comment by fiedl** [comment]
@john-preston Thanks for your quick reply! I guess this is just a side effect of the "close-window" behaviour. It's most useful in other applications where you can do something using a keyboard shortcut without going through the main window.

I would like to have the default "close-window" behaviour back for two reasons:

1. I don't want the dock icon to become transparent. It draws attention to the icon in my workflow, since I only hide (`Cmd+H`) windows if I intend to come back to them in a couple of seconds. Thus, a transparent dock icon means, I've forgotten something :) 
2. I don't want the telegram window to open if I accidentally switch to the telegram app using `Cmd+Tab`. People who want it to open, could just hide the window (`Cmd+H`) rather than closing it.

**Comment by john-preston** [comment]
@fiedl The last one is this issue main thing as I understand. I prefer to show the window when you cmd tab to the application, it feels like a bug when you cmd tab to the single-window app like Telegram and don't see anything.

**Comment by fiedl** [comment]
@john-preston Well, it's the usual app behaviour of other apple apps like "Messages". Have a look at this proof:

![messages window close](https://cloud.githubusercontent.com/assets/1679688/23237407/8fb087a8-f95d-11e6-9973-2e1344cd2ea5.gif)

But I understand that this is not everyone's favoured behaviour and that the whole point of this issue has been to suggest the opposite behaviour.

This is why [I've suggested to make it configurable](https://github.com/telegramdesktop/tdesktop/issues/1278#issuecomment-281725766) — please! :)
