### ISSUE TITLE
Image caption as the 3rd option on dragging file

### ISSUE THREAD

**Issue by kolyasya** [telegramdesktop/tdesktop#1279]
After the last updates, we have caption window for every image, which we try to send.
I think it's not the best option, because for the most part we need just to send image.
So, idea is to change dragging dialog for this one:
![telegram-sending-types](https://cloud.githubusercontent.com/assets/3371143/11021481/48eea8e6-8653-11e5-8097-a193b5d53c8e.jpg)

So, if we want to send image with caption, we'll have 3d option. But for the regular use we can drag images on the big area and send them just as usual, without caption.

**Comment by Excelion** [comment]
That is also strange for me. The quick way, for me, means  - instantaneous sending of image\screenshot\picture\photo.

In practice, now, dropping images without compression is not labeled as 'quick', but allows you to immediately send the poorly-looking message, with big original size.
