### ISSUE TITLE
unable to remove conversations and contacts.

### ISSUE THREAD

**Issue by shirishag75** [telegramdesktop/tdesktop#128]
hi all, 
I am unable to remove conversations and contacts from telegram. Please fix this. This is on Debian jessie and running latest telegram 0.5.17

**Comment by telegramdesktop** [comment]
Why can't you? For groups there is a Leave button in group profile:
![image](https://cloud.githubusercontent.com/assets/6113871/5957265/0c25a334-a7c8-11e4-8df1-a47c2a5689d4.png)
For users there is a Clear History and Delete (last one only for your contacts):
![image](https://cloud.githubusercontent.com/assets/6113871/5957271/2c12d7fc-a7c8-11e4-9421-fa7f52d1815d.png)
