### ISSUE TITLE
Add emojis to captions

### ISSUE THREAD

**Issue by auchri** [telegramdesktop/tdesktop#1280]
It would be great if emojis could be also added to captions of images.

Maybe something like:
![image](https://cloud.githubusercontent.com/assets/5092164/11022055/6a14613a-8655-11e5-9a76-6102d803e0c9.png)

A click on the face opens the standard emoji panel

**Comment by DaFri-Nochiterov** [comment]
+1

**Comment by formatq** [comment]
We want this!

**Comment by 23rd** [comment]
Looks like it was done a long time ago.

**Comment by auchri** [comment]
finally 😁
