### ISSUE TITLE
Feature request: Ban user from chat

### ISSUE THREAD

**Issue by foxmajik** [telegramdesktop/tdesktop#1282]
As an admin, one can kick users from the chat, but if there's a chat link that person can invite themselves right back to the chat.

Then you have the person you just kicked back in your chat, and now they are angry.

Although one can invalidate the invite link, this prevents the link to the chat from being used by other potential chat participants.

Whereas the link may be posted to lots of different places to draw interest to the chat, it is essential to be able to ban a specific user without invalidating the chat link.

Without the ability to ban users there are massive social implications:

* There's no way to ban text flooding bots.
* One cannot remove a person who is detrimental to the chat permanently.
* Spammers cannot be prevented from entering the chat.
* Providing a kick function but no ban function causes an angry person to return to the chat and begin hazing.

**Comment by f242** [comment]
+1

**Comment by JuanPotato** [comment]
+1
