### ISSUE TITLE
Feature request: Selective text gagging

### ISSUE THREAD

**Issue by foxmajik** [telegramdesktop/tdesktop#1283]
Selective text gagging would allow a user to select a bit of text and choose to reject any message that contains that text in the future by having the client drop that text from the update loop rather than displaying it.

This feature could fix issue #1282 and issue #1281 and issue #1025 and issue #488 (which is quite old and still valid).

Using a partial match or regex one could drop any text incoming that contains a user's username or display name, or any message that contains an offending word or URL such as "freesexnearyou.com" etc.

**Comment by auchri** [comment]
No api for that
