### ISSUE TITLE
Functionality of "delete" feature is ambiguous

### ISSUE THREAD

**Issue by foxmajik** [telegramdesktop/tdesktop#1284]
What exactly happens when one selects a message and "deletes" it is ambiguous in the UI.

Most people I have encountered have assumed that using the UI item "delete" removes the message from the chat history for everyone in the chat.

However, what it actually does is remove the message subjectively from the user's screen.

Other users still see the message.

The "delete" feature sets an expectation it doesn't fulfill.

The UI could be changed to more clearly indicate what the feature does.

Here are a couple of suggested ways of doing that:

1. You could change the context menu item to be more descriptive by changing it from "delete" to "don't show me this message" or "delete message (others will still see the message)" without adding significantly to the amount of UI space required.

2. A mouse-over tip could say something like "only removes the message from your chat history -- others will still see the message" could be added.

3. When a user "deletes" a message, the message could be briefly replaced with an explanation of what just happened, ie "message deleted from your chat history -- other users still see the message" then the deleted message could fade out or roll up.

**Comment by auchri** [comment]
See #499

**Comment by telegramdesktop** [comment]
If you delete a message in a private conversation you do not think it is deleted on the other side, you delete only your copy, that is the way e-mail works, sms works, it is perfectly clear to all users. The group chats are absolutely the same, except that there are not two, but three and more participants. So I don't see any problem with that and I don't think it is a frequently confusing place.

**Comment by mohammad1354** [comment]
Rastak group in Esfahan,Iran 
           Real state agency

**Comment by Gruenbaer** [comment]
Again...why name it DELETE if it doesn't do what it says...
"it is perfectly clear to all users". Well, let me tell you, it is not. I was just asked for the n-th time whether I still see the message which my counterpart just DELETED. The wording is misleading. 
foxmajik even posted a simple solution - and you still don't want to change it. 
I just don't get it. 
Besides of that, great messenger!

**Comment by FeanorsCurse** [comment]
I agree that it's really unclear, I was also expecting it to be deleted everywhere, as was my whole family. We switched from skype, where "delete" actually means "delete everywhere", so I completely agree that it should be either renamed, or preferably have the option to be properly deleted.

**Comment by foxmajik** [comment]
> If you delete a message in a private conversation you do not think it is deleted on the other side, you delete only your copy, that is the way e-mail works, sms works, it is perfectly clear to all users. 

Your assessment is a type of fallacy known as cherry picking -- the act of pointing at individual cases or data that seem to confirm a particular position, while ignoring a significant portion of related cases or data that may contradict that position.

Cherry picking is frequently used by coders to attempt to avoid work that is readily justifiable just long enough for a new release cycle to begin, thus steamrolling the request for change.

Please don't do that.

**Comment by stek29** [comment]
That's an issue caused by telegram architecture: there are message histories for each user and for channels/supergroups. 

When you delete a message, it is deleted in one history.
That's why it's deleted only for you in private chat and normal groups, and for everyone in channels/supergroups.

**Comment by FeanorsCurse** [comment]
Ok, but still, why not delete it in each history, like skype does? If it's possible to send message to each channel/user, why is it then not possible to send a delete command to each channel/user?

**Comment by foxmajik** [comment]
^

**Comment by stek29** [comment]
@FeanorsCurse Ask Telegram -- on Twitter or using Ask a question button.
@foxmajik Please use Reactions :)
