### ISSUE TITLE
Messages should use 100% of chat window width

### ISSUE THREAD

**Issue by Lesik** [telegramdesktop/tdesktop#1287]
On large screens there is a lot of wasted space because messages don't extend to 100% screen width. Since messages can't overlap anyways (because they're always below each other, never on the same height) I don't see much sense in this behaviour.

Besides, with the new `code` feature (which is really nice by the way) the code is uglily linebroken instead of maintaining the 79/80 character code width, which is pretty much standard.

![127598126312](https://cloud.githubusercontent.com/assets/2021487/11047874/f64cb938-8734-11e5-8ea7-08107e5a159d.png)

**Comment by auchri** [comment]
See #321 :)
