### ISSUE TITLE
"Open Telegram" sometimes need two clicks

### ISSUE THREAD

**Issue by z3ntu** [telegramdesktop/tdesktop#1292]
When Telegram is minimized AND another window is focused, the action needs two clicks to reveal Telegram Desktop.
Using Ubuntu 15.10 (with Unity) & 0.9.10 Dev version of Telegram Desktop

Not reproducible every time but happens very often.

**Comment by kanishkablack** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1171

**Comment by z3ntu** [comment]
I don't think this happens anymore. Can't reproduce it right now with KDE and I don't have a machine with Unity anymore.
