### ISSUE TITLE
Message counter

### ISSUE THREAD

**Issue by c143** [telegramdesktop/tdesktop#1296]
Hello
There is a counter for sent media in telegram but not for messages. It would be cool to have kind of a statistic how many messages you sent to a specific user.

Greetings

**Comment by telegramdesktop** [comment]
There is no API for sent and received messages count separately, but the information about messages count in the specific conversation is available. However, currently it does not fit anywhere in design, so only the interested guys can look it up in debug logs :) If you are interested in a specific conversation, I can give instructions, how you can find it, but it is not going to the interface right now.

**Comment by c143** [comment]
Yeah, it would be awesome, if you could tell me how to look up sent messages for a specific conversation. Thanks!

**Comment by drs-m** [comment]
I would like to get some advice too.

**Comment by Isakamays** [comment]
Hi telegramdesktop,

I am also interested in getting some advice for it.

Cheers,

**Comment by ubunterro** [comment]
And for me too, if posible.

**Comment by Juansero29** [comment]
I'd also love to know how many messages have been sent between two people in Telegram. This could be added (I think) to the interface, when you're going up in the chat, or just as a statistic in the same place than videos, audios, files, etc...

**Comment by hojjatgh2376** [comment]
Hi
I'd also love to know how many messages have been sent in a group of telegram.

**Comment by iamakulov** [comment]
For everyone else looking for the instructions: http://telegram.wiki/tips:tdesktopcountingmessages

**Comment by A1rPun** [comment]
Updated link: http://telegram.wiki/desktop/tdesktopcountingmessages

**Comment by sonic2kk** [comment]
I've found these files but how exactly do I see a count of messages? From looking at the file I get the impression the count is broken up into number sent and number received. Thanks!

**Comment by KoalaBear84** [comment]
I also could find any details in the mtp logs.
