### ISSUE TITLE
[Request] In-App Media Playback

### ISSUE THREAD

**Issue by Royal2000H** [telegramdesktop/tdesktop#1298]
I've seen similar requests in closed issues on this GitHub, however, those were made before other official apps had this feature. It only makes sense to bring Telegram Desktop up to speed with the other clients. From the Telegram blog, they say:

["Telegram allows you to play media from services like YouTube, Vimeo or SoundCloud directly from Telegram – without having to leave the app."](https://telegram.org/blog/search-and-media)

Personally I know that this works in the Android and Telegram Web (and Chrome) apps, I'm told it works in iOS as well. It works not just for Youtube, etc but also I think for WebM's. Tested with imgur gifv links.

**Comment by angusprune** [comment]
I would like imgur gifv (webm) to work natively too. Having to download them as massive gifs just to share them is annoying.

**Comment by Niklan** [comment]
+1 for webm support, definitely need it.

**Comment by fut33v** [comment]
++ for webm support
do you have any plans on implementing webm playback?

**Comment by tropicoo** [comment]
I'm struggling because 90% of modern gifs are being hosted on imgur as .gifv html containers (.gif, .webm, .mp4 for different devices) or at gfycat.com
Are there any estimates about autoplay of webm/mp4 from Imgur's .gifv containers and from gfycat

![screenshot 2016-02-17 001](https://cloud.githubusercontent.com/assets/888784/13122366/3e4f5672-d5bf-11e5-881e-9052800cdc8f.png)

**Comment by doublejumper** [comment]
+1 for webm support

**Comment by ttsda** [comment]
+1 for webm

**Comment by schuwima** [comment]
+1 webm

**Comment by mirh** [comment]
It at least works if you manually send the mp4 file you can find in the og:video header property in gifv [links](https://i.imgur.com/VNPcuYP.gifv). 
I guess it shouldn't be all that hard to hook on the server when thumbnail preview is generated?

**Comment by stek29** [comment]
So, can the new player be used for this?

**Comment by rshadow** [comment]
+Vote

**Comment by grravity** [comment]
What the hell is the deal with webm? This is the most annoying thing, people have been waiting years now for webm playback support.
It's super frustrating needing to convert all videos from webm..
