### ISSUE TITLE
security problem

### ISSUE THREAD

**Issue by libora** [telegramdesktop/tdesktop#13]
Hi, file "config" in folder "tdata" contains the login information and password for proxy in an unencrypted form. It can be very big safety problem especialy for portable version!

**Comment by ppparadox** [comment]
+1

**Comment by edmundlaugasson** [comment]
There is [some discussion about Telegram security issues](https://www.reddit.com/r/netsec/comments/3wd29m/analysis_of_telegram_crypto/) and also one[ master thesis available talking about Telegram protocol security issues](http://cs.au.dk/~jakjak/master-thesis.pdf). It would be good if Telegram would rely on proven free and open-source encryption protocol(s) and not reinvent the wheel.

**Comment by edmundlaugasson** [comment]
One more idea regarding secret chat - using telegram.me mechanism I would propose to make possible to create link which will directly start secret chat. E.g. https://telegram.me/secret/YourUsernameHere

**Comment by john-preston** [comment]
Proxy settings are encrypted for a long time now.
