### ISSUE TITLE
[win10] Telegram does not start when it is already running on different user account

### ISSUE THREAD

**Issue by bkalinow** [telegramdesktop/tdesktop#1300]
I have just discovered that Telegram Desktop for Windows does not start when it is already running on **different user account**. My wild guess is it tries to detect already running instance (and possibly bring it to front), but ignores the fact that only current user instances should be subjects for this check. 

Tested on Windows 10 and non-portable (tsetup) Telegram version 0.9.10.

**Comment by Aokromes** [comment]
strange thing, macos looks to work but makes 100% cpu use.

**Comment by jeffythedragonslayer** [comment]
I was able to get two instances of Telegram running on Windows 10 if I launch one that was installed from the Microsoft Store and one that was downloaded from https://telegram.org/

In Task Manager->Details they are both listed as "Telegram.exe" though so it must detect duplicate instance through some other mechanism than the filename...

**Comment by bkalinow** [comment]
> I was able to get two instances of Telegram running on Windows 10 if I launch one that was installed from the Microsoft Store and one that was downloaded from https://telegram.org/

I do not know if MS Store version (which might be entirely different app) exhibits the same problem - now, 4y+ later, I am the only Telegram user on my machine :)
