### ISSUE TITLE
Hotkey support

### ISSUE THREAD

**Issue by tostiheld** [telegramdesktop/tdesktop#1305]
It could be that i'm not looking hard enough, but i can't spot any hotkey support. My workflow depends greatly on hotkeys so it'd be great if hotkey support was added. For example: in linux it's pretty common to have control-q/w to close a window/document. Sadly it doesnt work in the telegram desktop client.

I wanted to submit a pull request but then i read in the contributing.md file that you won't accept new features. Let me know if i can submit a pull request anyways.

**Comment by tostiheld** [comment]
oops, i just found an issue where hotkeys are already mentioned. never mind.

**Comment by auchri** [comment]
@telegramdesktop 
> I wanted to submit a pull request but then i read in the contributing.md file that you won't accept new features. Let me know if i can submit a pull request anyways.
