### ISSUE TITLE
Cannot remove a deleted group

### ISSUE THREAD

**Issue by rowhani** [telegramdesktop/tdesktop#1308]
I have been added to an Ads group (without permission) and then the group has been deleted by the owner. Now I cannot delete the group and although I press "Leave" or "Delete and Exit", its name is still shown on my chat history. It says the "group is unaccessible". How can I remove it?

**Comment by Sh4hr14r** [comment]
This also happens when you are added to a group and then kicked from it. It is used as an advertising method since you can view some of the messages before you were kicked. It is so annoying please fix this.

**Comment by telegramdesktop** [comment]
Should be fixed in 0.9.12 dev version.
