### ISSUE TITLE
Can not send messages to strangers.

### ISSUE THREAD

**Issue by ruleroller** [telegramdesktop/tdesktop#1309]
I am not SPAM, and tried sending mail to spam@telegram.org to report this several days ago, until now still no response.

Github here may not the right place to talk about this, but I have to get some real person to help me out of this situation.

Is there any offical Telegram staff can help me?

![screenshot 2015-11-17 22 07 26](https://cloud.githubusercontent.com/assets/3047708/11234450/ecdba7e0-8e02-11e5-8828-1059e77995eb.png)

**Comment by auchri** [comment]
Someone reported you.
You can get help with the "Ask a question" feature in one of the official apps.
