### ISSUE TITLE
Need bookmarks for messages

### ISSUE THREAD

**Issue by mrpuzzler** [telegramdesktop/tdesktop#1312]
It's very important to have some bookmarks for messages. It's cool to mark some messages with "star" and open them in separate window. So I can keep history for all important messages, and can find them in 2 clicks.

**Comment by auchri** [comment]
no api for that :/

**Comment by mrpuzzler** [comment]
Yeah, but this is must-have feature. It's impossible to manage messages now.

**Comment by auchri** [comment]
I forward important messages to myself, so I can find them a lot easier :)

**Comment by mrpuzzler** [comment]
Yeah, I can write it down on paper ...

**Comment by auchri** [comment]
That's possible too :yum:

**Comment by mrpuzzler** [comment]
Any change this feature can be implemented?

**Comment by auchri** [comment]
At first, there have to be a api for that.

You can suggest a new api with the "Ask a question" feature in one of the official apps.

**Comment by mrpuzzler** [comment]
But this is official app, I suggest feature ... don't you accept it here? Can you share any other link to post this proposal?

**Comment by auchri** [comment]
This client just uses the [open Telegram API](https://core.telegram.org). If something does not exist in the api, we can't implement it in the client.
You can suggest a new feature on twitter too: https://twitter.com/telegram

**Comment by 0x49D1** [comment]
Seems like a nice feature to have.. I know that i can forward messages and files to myself, but it'be better to have some "wrapper" interface for such functionality to be closer to masses.

**Comment by stek29** [comment]
Even support would recommend you to make a private channel for that.
Channels are more flexible and suitable for saving something, because you can create different channels for different things to save
But Forwarding has an issue -- it's not easy to find original message. That's why bookmarks are needed IMO.

**Comment by cala2ar** [comment]
you can put a hashtag on the message you want to follow , so you can find it easier . you can also delete it like a task ...

**Comment by lapisdecor** [comment]
This feature could be implemented with something similar to what is done in archive, with the difference you 'archive' (bookmark) a message instead of a chat.
