### ISSUE TITLE
anonymous photos and stickers in chat

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#1315]
photos and pictures are shown without username
![screen](http://img-fotki.yandex.ru/get/16189/78276594.c/0_eef02_78384964_orig.png)

**Comment by telegramdesktop** [comment]
@f242 This is so "by design", you can click on the photo of the sender to the left of the image if you're not sure who've sent it.

**Comment by f242** [comment]
>you can click on the photo of the sender
but is not user-friendly, clicks on each
imagine this in chat with a lot of users

**Comment by telegramdesktop** [comment]
@f242 Well, in 98% of cases you know the profile photo already or this user is sending some text except images and you saw his name already.
