### ISSUE TITLE
Show long file names

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#1319]
![screen](http://img-fotki.yandex.ru/get/15513/78276594.c/0_eef0b_3fc2d6dd_orig.png)

> If someone sends a file with a long filename, a mouseover with the full filename should appear .

**Comment by auchri** [comment]
Amazing description :+1:

**Comment by cristian64** [comment]
I'm currently being annoyed by this issue. No way you can read the full name unless the file is downloaded first.

**Comment by f242** [comment]
@cristian64 you can go to profile -> shared media -> files
but i think tooltip will be more useful

**Comment by cristian64** [comment]
Actually, I hadn't thought of that list of files, thank you. However, the list you see there doesn't even have the original file names, but some kind of cooked name, to remove special characters apparently.

**Comment by john-preston** [comment]
@cristian64 I'm afraid they're removed on the server-side.

**Comment by cristian64** [comment]
I think you're right. Only the client that sent the files have some trace of the original name.

**Comment by Aokromes** [comment]
Interesting point on this, on chat side the filename is cut, but on contacts part the full name is show.
https://i.imgur.com/stLButz.png

**Comment by SmartManoj** [comment]
@f242 even on  profile -> shared media -> files , it truncated with ...

**Comment by ido1990** [comment]
5 yrs and still the same?

**Comment by Aokromes** [comment]
> 5 yrs and still the same?

pull requests are welcomed, also. like i pointed, on contacts part the full name is show, so if we take that we can use it for tooltip.

**Comment by ido1990** [comment]
> 
> 
> > 5 yrs and still the same?
> 
> pull requests are welcomed, also. like i pointed, on contacts part the full name is show, so if we take that we can use it for tooltip.

I wish I could contribute to Telegram Desktop.
Don't know C++ :(

**Comment by SmartManoj** [comment]
@ilya-fedin, stale bot can know the No. of reactions on an issue?

**Comment by SmartManoj** [comment]
@Aokromes image
![](https://i.imgur.com/stLButz.png)

**Comment by SmartManoj** [comment]
@Aokromes could you send the file to a test channel?

**Comment by ilya-fedin** [comment]
> stale bot can know the No. of reactions on an issue?

it doesn't look at reactions AFAIK

Don't know if authors of the bot can add such a feature, though

**Comment by Aokromes** [comment]
https://t.me/TelegramDesktopTalk/49074

**Comment by Remu-rin** [comment]
Still relevant.

**Comment by AndydeCleyre** [comment]
Relevant: #5231

**Comment by AxE47** [comment]
Still Not Solved !!!!!

**Comment by voltrare** [comment]
true

**Comment by pablogzlezmora** [comment]
Relevant.

**Comment by ShreyMarwaha** [comment]
Still relevant.

**Comment by MinusAlternative** [comment]
Please fix this. I find it insane that an app with 500M+ downloads misses such a basic feature.

**Comment by MinusAlternative** [comment]
Please fix this. I find it insane that an app with 1B+ downloads misses such a basic feature.

**Comment by Aokromes** [comment]
try on 4.2.0

**Comment by 23rd** [comment]
Tooltips for long filenames should be added to the 4.3.0 version.

**Comment by Aokromes** [comment]
yes, tooltip is there, but if 2 files contains 99% of the start of file with same name the 2nd and following will have the end of filename (without extension) cut, but acording preston this is server side issue.
