### ISSUE TITLE
Larger emoji size in preview

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1321]
Hello, I think the desktop would be nice to have a preview of the emoji in a slightly larger size/resolution.
There are other applications that show the apple emoji with higher resolution and increase in size, increasing the size of the font. Is it now possible in TDesktop?
http://emojipedia.org/apple/

On the other hand, the possibility of changing emoji pack is highly desirable. My favorites are used by Twitter ... maybe others like it used in Google, etc.
Cutegram possible change emoji pack, but is far behind Tdesktop.

http://emojipedia.org/twitter/
http://emojipedia.org/google/

Thanks

**Comment by auchri** [comment]
> On the other hand, the possibility of changing emoji pack is highly desirable

No, we want the same emojis at all official clients.

**Comment by phraymond** [comment]
I came here to make this feature request as well. I'd like to be able to hover over a sticker and have a preview image pop up that's much larger. These eyes are getting old, I'm afraid....

**Comment by diazbastian** [comment]
@auchri I realized that since the last update Telegram for Android and iOS, there are new emojis that are not supported by TDesktop. I need not create a new report to be closely related.

Thanks

**Comment by telegramdesktop** [comment]
@diazbastian Those new emoji will be supported in the next version.

**Comment by auchri** [comment]
@diazbastian #1196

**Comment by auchri** [comment]
See #2804
