### ISSUE TITLE
Confirmation to send stickers

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1322]
Send wrong stickers is something that happens to me often. With the system of scroll with two fingers it is very easy to make mistakes.

In android, there is a way to see the sticker before sending it (holding down the sticker). In Tdesktop could add a confirmation button on the talk bubble (delete/send) to avoid making mistakes.

**Comment by Alirezanet** [comment]
bump . i have same problem... :+1:

**Comment by diazbastian** [comment]
I think this issue is solved several versions behind. If you would like to close this report. Thank you.
