### ISSUE TITLE
Mobile number appears instead of person's name

### ISSUE THREAD

**Issue by goncalor** [telegramdesktop/tdesktop#1324]
I downloaded the desktop app yesterday. The names of the conversations are the mobile numbers, and not the person's name or username.

I am running Debian + Cinnamon; and Telegram's version 0.9.10.

![screenshot from 2015-11-24 11 18 09](https://cloud.githubusercontent.com/assets/7317678/11365485/d3a6b9b8-929e-11e5-8a7e-65b7b7e6d9b0.png)

**Comment by DaFri-Nochiterov** [comment]
:+1: Can confirm this on 0.9.12 dev version.  

![image](https://cloud.githubusercontent.com/assets/10401817/11365727/f184a670-92da-11e5-9338-c7351138b153.png)

**Comment by goncalor** [comment]
It seems this happens only when someone else adds me to their contacts. If it's me adding them the name I input when adding them appears instead of the mobile number.

**Comment by telegramdesktop** [comment]
@goncalor All the users that whose phone number you have access to, but whom you don't have in your contact list, are displayed as those numbers in the conversations list. It is done like it works in iOS app.

**Comment by DaFri-Nochiterov** [comment]
But if I don't want to see phone number instead of name?

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov Currently I can offer to add him to contacts list. Perhaps there will be a different approach to this issue, but current behavior strictly follows iPhone app, which was an example for tdesktop from the start.

**Comment by DaFri-Nochiterov** [comment]
@telegramdesktop If I add this user to my contacts list, he will begin to add me in conversations, where I don't want to be. :) 
OK, I got it. 
Thanks for reply.
