### ISSUE TITLE
Telegram does not opens from tray at first attempt when being run from autostart on Linux

### ISSUE THREAD

**Issue by LDVSOFT** [telegramdesktop/tdesktop#1326]
I have a strange minor issue with Telegram on Ubuntu 14.04, when it's being run via autostart.

1. Add Telegram to autostart with desktop file.
I created this one via `gnome-session-properties` dialog.
```
[Desktop Entry]
Type=Application
Exec=/opt/telegram/Telegram -startintray
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[ru]=Telegram
Name=Telegram
Comment[ru]=Мессенджер Telegram
Comment=Telegram messenger
```
2. Reboot / Leave session and login back. Telegram icon will appear, not the app, as intended.
3. Click on tray menu. Option `Minimise to tray` will be disabled.
Click on `Open Telegram`: **app does not open**, but `Minimise to tray` becomes active. Clicking again does not help.
4. Click `Minimise to tray`, again nothing happens, but the option becomes disabled again.
5. Click again `Open Telegram` and app shows up normally.

When Telegram is closed completely and started with `-startintay` option from terminal manually, I got this issue not every time, sometimes it just works fine.

**Comment by auchri** [comment]
Duplicate #768
