### ISSUE TITLE
Use Nautilus 

### ISSUE THREAD

**Issue by ALCC01** [telegramdesktop/tdesktop#1328]
On Ubuntu 14.04 LTS, the app uses a weird Windows XP-style file browser for uploading files and photos, that makes really difficult to accomplishing even the most simple tasks as it does not fit the directory structure (most of the times you are forced to start from the / directory).

It would be really helpful to replace it with Ubuntu's standard file manager, Nautilus.

**Comment by DaFri-Nochiterov** [comment]
Similar issue #972 was closed and referenced to issue #987

**Comment by ManuelSchneid3r** [comment]
I am the author of #987. Note that #987 is *not* about the filechooser. #987 is about the *application style* in general. Check #982 for native filechooser.

**Comment by john-preston** [comment]
In the latest 0.9.57 version gtk file chooser should be used if it is available. Please check.

**Comment by ALCC01** [comment]
The appropriate file chooser appears to be used in the 0.9.57 release.
