### ISSUE TITLE
[Request] Shortcut to delete selected conversation in conversation list

### ISSUE THREAD

**Issue by myurtsev** [telegramdesktop/tdesktop#1330]
Hi!

I don't know if I'm the only one but it's a little frustrating to delete a conversation. In the current version we  have to navigatie into 'contact information' and select 'delete conversation' to delete it. I would like to have a option in the form of a keyboard shortcut like backspace or command backspace to delete the selected conversation in the conversation list left of the user interface. I think this would be better in stead  leaving the chat area to just delete a conversation. It's to many effort to achieve something simple; deleting. It should be simpler for the user experience.

This also creates the possibility to delete multiple conversations by selecting them with command/ctrl click just like in Finder or Explorer (depending on which OS you currently are).

**Comment by auchri** [comment]
Added to #1060
