### ISSUE TITLE
Can't remove added sticker pack?

### ISSUE THREAD

**Issue by joshery420** [telegramdesktop/tdesktop#1331]
Maybe I just can't find it, but I can't figure out how to remove a third-party sticker pack I added without opening up the Android app and handling it through there.

**Comment by auchri** [comment]
#1068

**Comment by joshery420** [comment]
Ahhhhhh, I see now.
Thanks for the quick reply!
I did actually see that post @auchri, but I thought that was supposed to be in the "Pack Info" dialog.

Might be good to let people remove it that way too, or by right clicking on a sticker from a pack they have installed and under "Pack Info" is something like "Remove Pack" in the context menu.
Honestly, I've scrolled through that list so damn much and I've never noticed the little X for each sticker pack haha.
