### ISSUE TITLE
Hover-activated buttons yes/no?

### ISSUE THREAD

**Issue by ralesk** [telegramdesktop/tdesktop#1333]
There's this thing with the attachment and emoticon buttons that they activate on hover (bringing up the little windows)... and to be quite honest I find that a really weird behaviour.

So I'd just like to ask the others here in the issue-land whether it's just me or they too are bothered by it.

It doesn't seem like a hard thing to change either way (I mean, to activate them on click like every other button/menuitem/whatever).

**Comment by VitRom** [comment]
+1, it's VERY annoying.
Especially taking in account a wide-spread reading habit to point with a mouse onto a key areas. One tiny move over the last message timestamp and a huge popup blows in eyes.

**Comment by amiremami** [comment]
I agree with @ralesk and @VitRom . We worked for years with the point and click system, it's really annoying that hovers make the tooltip appears accidently. I was thinking maybe it's better to show the emoticons tooltip as a fixed sidebar, same as this:

![dfgfdg](https://cloud.githubusercontent.com/assets/15929497/11879979/cc1ff232-a4fe-11e5-965e-056c15f4dd5e.png)

This will prevent accident hover thing, and also increases speed in searching and choosing the sticker we want to send.

**Comment by ralesk** [comment]
Still wishing for the hover popups to be turned into click-activated ones.  Any feedback from developers on this, and other users?

**Comment by ralesk** [comment]
I still regularly bump into not wanting to open the emoji popup but managing to and ending up almost clicking an emoji.

**Comment by amiremami** [comment]
After working a lot with Telegram, I get used to it and now I'm too lazy for clicking on emoji button for opening it! 😄

**Comment by VitRom** [comment]
A two kind of jokes are, one with a smile(s), and another one for those who understands that a joke's salt not in the smile(s).
Hover-activation is for the first only.
Er... :-)

**Comment by ralesk** [comment]
My biggest problem with all the UI bugs I reported is that nobody from Telegram bothers to respond to it.

**Comment by stek29** [comment]
#1751 btw

**Comment by ralesk** [comment]
Thanks @stek29. Amazing response time there too.

**Comment by gottesman** [comment]
The user's list from a group, with less than 100 members, just pops up when I move the mouse to the Back Button when I want to go back to main screen. That's pretty annoying, because I end up viewing a user's profile if I just insta-click.

![image](https://cloud.githubusercontent.com/assets/8980291/24885070/c1ce0fa8-1e4c-11e7-9489-1388c6fec3c2.png)

**Comment by john-preston** [comment]
@gottesman That's a regression, this dropdown should appear below the top bar (which leads to group profile or back), I'll fix that in the next version, thanks.

**Comment by ralesk** [comment]
I wonder if there's even a point of that popup.  I mean going to the group profile gives you a much more convenient user list anyway.

**Comment by gottesman** [comment]
@john-preston It's way better now in the new Alpha :thumbsup:

![image](https://cloud.githubusercontent.com/assets/8980291/24935824/b2229352-1f24-11e7-9eee-a8f99a557632.png)

**Comment by VBelozyorov** [comment]
@john-preston but what about this original issue with emoji toolbar? If you afraid to change UX, simply add option to switch between mouse move and click on emoji button.

**Comment by john-preston** [comment]
@VBelozyorov Now you can just use three column mode and not have emoji pan appear on hover event.

**Comment by VBelozyorov** [comment]
Excuse me, what is  
> three column mode
I've tried to search, but no success.

**Comment by john-preston** [comment]
@VBelozyorov You can click on the emoji icon near the send button and switch to a three column mode.

**Comment by VBelozyorov** [comment]
Hmm…
I have v1.0.29 on Linux (openSUSE Leap 42.2)
But I have no send button:

![Version and input field](https://cloud.githubusercontent.com/assets/860208/25097142/ed017dae-23ab-11e7-8d9f-3a5dcf55c85e.png)

Meanwhile emoji toolbar looks like this:
![Emoji toolbar](https://cloud.githubusercontent.com/assets/860208/25097238/62c0876a-23ac-11e7-8dd6-31b48c8ba994.png)

It's quite three-columned for me, but it's still appears on mouse hover on emoji button

**Comment by john-preston** [comment]
@VBelozyorov I mean click on the emoji icon (near to send button when send button is displayed, when it is not — near to the record audio message button, in the bottom right corner of the screen).

**Comment by VBelozyorov** [comment]
Sorry, I do not understand - what should happen when I click on it?
What happens now: _hover_ - _toolbar appear_ - _click_ - _toolbar disappear_
And all goes the same way on next _hover_, behavior is not changes.
![vokoscreen-2017-04-17_21-10-37](https://cloud.githubusercontent.com/assets/860208/25098745/6c930ffa-23b2-11e7-8ae7-f5fc5d4ba8c7.gif)

**Comment by john-preston** [comment]
@VBelozyorov Looks like your screen is too small for the third column then :( Sorry. It was supposed to become like this:

**Comment by john-preston** [comment]
![image](https://cloud.githubusercontent.com/assets/17900494/25098912/f3e46472-23b2-11e7-83a2-8f1fc09f65ac.png)

**Comment by VBelozyorov** [comment]
1920×1080 isn't big enough?

**Comment by john-preston** [comment]
@VBelozyorov Ah, I forgot! It is available only in the alpha version right now, you can try it from https://desktop.telegram.org/changelog#alpha-version or wait for the next stable version update.

**Comment by VBelozyorov** [comment]
It's interesting, but not solution (for me). All those emoji overload window and make message perception more difficult.
Thanks for make this panel optional.

**Comment by ralesk** [comment]
I stand with @VBelozyorov :)  Glad that the emoji toolbar three panel mode is (will be) optional; it certainly doesn't solve the issue for those who use the collapsed (narrow window, single panel) mode.  The hover on the bottom icons (or really, everywhere) gets in the way too much.

**Comment by ralesk** [comment]
P.S. Thanks for finally responding to this issue.

**Comment by knickers** [comment]
Just wanted to chime in to keep this thread active because this is actually pretty important. A setting to turn off emoji panel open-on-hover is the proper solution in my opinion. I love telegram and will continue to use it, but this happens to me dozens of times per day and gets really frustrating.

**Comment by kke** [comment]
The smileyface is too close to the "scroll to bottom" thing and the hover thing always opens and instead of scroll to bottom, your cursor now points to a heart icon which is where the scroll to bottom buttom was before the hover thing appeared over it. Annoying.

**Comment by ralesk** [comment]
I can't count the amount of times I have to try and retry and retry clicking something because the god damned hover smileys popped up.

**Comment by Kirrrr** [comment]
It is just unbelievable...
The only thing many people here need is a configurable hover timeout for damned emoji button. No bloody UI filosophy or UX ideology. Just one configurable timeout value. What the heck?

**Comment by S-U-M-1** [comment]
How has it taken nearly 3 years to just add a simple 250ms delay on that damn emoji button?

**Comment by YanDoroshenko** [comment]
@S-U-M-1 You're saying "has taken" as if it was done.

**Comment by S-U-M-1** [comment]
@YanDoroshenko Exactly.

**Comment by Kirrrr** [comment]
@S-U-M-1 
Erm... So... It's done???

**Comment by ralesk** [comment]
Not that I can see...

**Comment by S-U-M-1** [comment]
@Kirrrr No, I'm saying "exactly" as in it wasn't even done, let alone "has taken" time to do.

**Comment by john-preston** [comment]
Showing on click was added to Settings > Advanced > Experimental.
