### ISSUE TITLE
Interface Scale - <100

### ISSUE THREAD

**Issue by jawsome** [telegramdesktop/tdesktop#1334]
Hello,

On smaller resolution screens, the Desktop interface is quite bit and the text is quite big.  The option to make the interface scaled greater than 100% already exists. It would be awesome if it could also be scaled down lower than 100% such as 90%/80%/70%/50% similar to how Ctrl+- works in standard web browsers.

I'm happy to attempt to write a PR with a little direction on the functions and areas of the code that would be changed.

<3

**Comment by NXij** [comment]
I'd love this too, though unlikely it will be implemented

**Comment by januszeal** [comment]
This would be a pretty nice enhancement to have. No wasted screen real estate please!

**Comment by SkepticalsArctic** [comment]
I agree, it can be really bothersome to use telegram on a small screen

**Comment by Aokromes** [comment]
#1121

**Comment by Twilightssuperb** [comment]
Any news?

**Comment by zigarrre** [comment]
This has nothing to do with #1121! #1121 is only about automatic scaling, this is about scaling factors <1 (<100%).

So please remove duplicate tag and reopen.

**Comment by stek29** [comment]
@zigarrre #1121 is a meta issue for non-standard scales and automatic scale/scaling without restart.

**Comment by himanshuxd** [comment]
In [#2628](https://github.com/telegramdesktop/tdesktop/issues/2628) this issue has been cited and referenced as duplicate and closed and the same has done here by citing that issue. This is a bad way to kill of two issues that want people to scale their desktop client <100% and had nothing to do with automatic scaling.
