### ISSUE TITLE
Enable search for groups and waiting list

### ISSUE THREAD

**Issue by HostFat** [telegramdesktop/tdesktop#1336]
I didn't find where it is possible to make suggestion / feature requests, so I'll put it here, in the hopping that some core dev will read it :)

It will be great if it was possible to enable groups (so, disabled by default. ON/OFF) to be find through the search.

This should be obviously possible only from the admin of the group.

The other thing is the possibility to disable the free access to the group (always, an ON/OFF feature, disabled by default), but adding a "waiting list".
So if the admin of the group enable it (the waiting list), then he can freely even put the invitation link "everywhere", and all the arriving users will need to be enabled one by one from the admin/s.

**Comment by auchri** [comment]
no api for that :/
