### ISSUE TITLE
Respect shortcuts from DefaultKeyBinding.dict

### ISSUE THREAD

**Issue by mitsuhiko** [telegramdesktop/tdesktop#1338]
Not sure how you feel about fixing this, but I suppose Chrome or whatever you use might already have support for that.  Basically that file (DefaultKeyBinding.dict) is used to define additional keyboard shortcuts for input fields.  Would be cool if that was supported.

**Comment by Aokromes** [comment]
you can use tdata/shortcuts-custom.json now.
