### ISSUE TITLE
[Bug] Save dialog is behind the photo

### ISSUE THREAD

**Issue by SafaAlfulaij** [telegramdesktop/tdesktop#134]
The Save As dialog is behind the photo.
OS: ArchLinux
![telegramproblem](https://cloud.githubusercontent.com/assets/3509617/4048030/9e0dfdae-2d3f-11e4-99a0-f7339be40e10.png)

**Comment by telegramdesktop** [comment]
Is it still like that in new versions? Check 0.7.10.

**Comment by SafaAlfulaij** [comment]
Great! The photo mode disappears when trying to save. Thanks a lot! :-)
