### ISSUE TITLE
Add french translation on Transifex

### ISSUE THREAD

**Issue by boopr** [telegramdesktop/tdesktop#1343]
Hello,

I really want to help to translate Telegram in French. Is it possible to add a new group in Transifex ? 

Thanks!

**Comment by auchri** [comment]
See https://github.com/telegramdesktop/tdesktop/pull/1409#issuecomment-165588781

**Comment by peyremorgan** [comment]
Hi,

is the languages list still frozen ? Do you have an estimated timeframe on when new languages will be considered ?

Thanks,
