### ISSUE TITLE
Disable clickable bot actions when command is not implemented in bot

### ISSUE THREAD

**Issue by BramBoos** [telegramdesktop/tdesktop#1344]
As the title already says. When you have a bot with only 1 command (e.g. /start) then only make a link of the /start word. When you say something like: "My temp dir is /tmp", then /tmp is not clickable because the bot(s) in a group has not implemented the /tmp command.

Sorry for my bad explanation. In short words: stop spam in groups because /[text] is clickable.

**Comment by DaFri-Nochiterov** [comment]
No.
Bots can use any commands in some situations.
For example:
[Sasha]
/posts

[Bot]
/list_1 - lorem ipsum
/list_2 - lorem ipsum 

[Sasha]
/photos

[Bot]
/photo_1 - ...
...
