### ISSUE TITLE
WinXP 32bit: Tdesktop BSoD adding Stickers

### ISSUE THREAD

**Issue by PUOjACKz** [telegramdesktop/tdesktop#1347]
I have added 5 more sticker set, installing them through the browser setup sequence (so going on a telegram sticker website and clicking on the url https://telegram.me/addstickers/)

Doing so caused a fatal BSoD on the Win32 module.

**Comment by auchri** [comment]
First of all: [Windows XP should not be used anymore](http://windows.microsoft.com/en-us/windows/end-support-help). Consider updating your OS.

Second, post the [stop error message](http://www.bleepingcomputer.com/forums/t/74712/how-to-find-bsod-error-messages/).

**Comment by telegramdesktop** [comment]
@PUOjACKz I'm afraid there even is not crashdump about that %) So I'm not sure I can do anything about that. Does it happen all the time you try to do so?

**Comment by PUOjACKz** [comment]
Two times I have tried, and two times it happened.

@auchri Unfortunatelly this terminal cannot be upgraded for various reasons.

**Comment by auchri** [comment]
You can use [Telegram Web](https://web.telegram.org) instead :)

**Comment by theus** [comment]
@auchri +1
