### ISSUE TITLE
I can not input Korean in Telegram desktop chat windows on Ubuntu 15.10

### ISSUE THREAD

**Issue by namwonkeun** [telegramdesktop/tdesktop#1348]
I can input Korean in Telegram web or chrome app extensions chat window on Ubuntu 15.10.
But I can not input Korean in Telegram desktop chat window on Ubuntu 15.10.
It's not Korean IM errors.
Please patch it.

**Comment by conr2d** [comment]
I heard that this is not an issue about telegram, but QT5 Korean input problem. Using dasom IM might be an available solution currently.

**Comment by namwonkeun** [comment]
Although I'm using Dasom-im, But it's impossible to input Korean.

**Comment by conr2d** [comment]
I experienced similar issue in Ubuntu 14.04, but I solved Korean input problem with fcitx (another IM like dasom) by installing fcitx-hangul and fcitx-frontend-qt5 packages. If it cannot solve your problem, then update Qt5 to the latest code via PPA. I hope it gets resolved well.

**Comment by telegramdesktop** [comment]
@namwonkeun Currently fcitx and ibus qt plugins are used, so those input methods should work.

**Comment by namwonkeun** [comment]
Thank you.

**Comment by bit-pirate** [comment]
FYI, on Kubuntu 14.04 I got it working by starting the app like this:

```
QT_IM_MODULE=ibus /<path_to_executable>/Telegram/Telegram
```

Got the hint from here issue #1900 and #1041 .

**Comment by bakyeono** [comment]
QT_IM_MODULE=<your-input-method> envvar works beautifully.
