### ISSUE TITLE
Read count in a private channel exceeds the number of members

### ISSUE THREAD

**Issue by les-sosna** [telegramdesktop/tdesktop#1355]
In my private channel of only two members including myself I've got a message with the read count of 4.
![image](https://cloud.githubusercontent.com/assets/7249891/11540517/07992e92-98e2-11e5-87f2-74e4887beadf.png)
![image](https://cloud.githubusercontent.com/assets/7249891/11540553/37b94878-98e2-11e5-8190-0e8b31322aa3.png)

**Comment by telegramdesktop** [comment]
@les-sosna View count is incremented not only once for one viewer, when some time have passed it counts your view once again, if you really view it.
