### ISSUE TITLE
Sticker Packs Don't update until restarted

### ISSUE THREAD

**Issue by chaosdrop** [telegramdesktop/tdesktop#1356]
Seems that sticker packs our not being updated until telegram is completely closed out and restarted.

**Comment by JuanPotato** [comment]
Can confirm, my sticker packs don't get updated until I find a sticker in the updated version of the pack and right click -> share, then it loads in mine

**Comment by telegramdesktop** [comment]
@JuanPotato They should update automatically when you show up the stickers panel, but not more then once in an hour.

**Comment by JuanPotato** [comment]
@telegramdesktop I'll keep watching it, thanks for the info

**Comment by i-cant-git** [comment]
I wish there was a way to force update sticker pack because you need to see results right away when making sticker packs.
