### ISSUE TITLE
Caption for other media files

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1357]
This is a feature to discuss, but that greatly benefits all official applications.
Telegram is widely used to share files of all types and in some companies use it as a replacement for email. I think it would be helpful to add a caption to audio files, voice messages, video and documents, enabling better organize conversations by giving them a context to be able to add hashtags and mentions (especially in supergroups talks or forwarding messages).

Cheers

**Comment by theus** [comment]
+1

**Comment by DaFri-Nochiterov** [comment]
It's not implemented by API.

**Comment by diazbastian** [comment]
>It's not implemented by API.
>
>Caption can be added only to videos and photos, as I know.

@DaFri-Nochiterov for that reason it is a feature to discuss, because it requires more profound changes. But I have no doubt it would be something that greatly benefits today's file sharing in the way we communicate with Telegram.

Cheers

**Comment by auchri** [comment]
> for that reason it is a feature to discuss, because it requires more profound changes.

Please discuss somewhere else, this repository is for Telegram Desktop only.
