### ISSUE TITLE
mention followed by link goes out the message box

### ISSUE THREAD

**Issue by sijad** [telegramdesktop/tdesktop#1358]
if someone send you a message with a link + lot of spaces + username mention, the mention will goes out the message box
this:
```
http://google.com                                                                                                            @sijad
```
produce this:
![screen shot 1394-09-12 at 12 26 51 pm](https://cloud.githubusercontent.com/assets/7693001/11555983/37ed713e-99b9-11e5-83b3-76b94c672b7f.png)

**Comment by telegramdesktop** [comment]
@sijad Thank you for your report! This will be fixed in the upcoming release.

**Comment by TiagoDanin** [comment]
Bug not only occurs with username mention.
![gif](https://cloud.githubusercontent.com/assets/5731176/11568999/15fa68b0-99ce-11e5-9697-3b6aa20e637e.gif)
Special character and Emoji

**Comment by sijad** [comment]
@telegramdesktop I think it's fixed, can you confirm that?

**Comment by auchri** [comment]
Yes, with https://github.com/telegramdesktop/tdesktop/commit/2d53ab88a08682e0be33cbde76a4fb0e8c5c689a :)
