### ISSUE TITLE
Touch doesn't work

### ISSUE THREAD

**Issue by KarlTheBee** [telegramdesktop/tdesktop#1366]
I've got an Laptop with touchscreen and Windows 8.1.
But telegram doesn't react at all to touch-gestures since the end of november.
Before november I was able to select chats, choose icons and do basically everything via touchscreen.
Now telegram ignores the inputs via touch, it does nothing (no freezing, no error message, no weired stuff) - just no reaction.

**Comment by RPDeshaies** [comment]
:+1: I have the same issue here with Telegram Desktop on my Asus transformer Tablet using Windows 10

**Comment by mirhl** [comment]
Indeed, I have this problem even with my graphic tablet. 
Or better its driver still moves the cursor and all, and pressure sensitivity still works in program using directly wintab API. 

Everything that relies on Windows Ink Services API is screwed though. Gestures stop working and so Journal dedicated features.

**Comment by telegramdesktop** [comment]
@mirhl I test on Surface Pro 2 on Win10 and it does work (I test scrolling of chat list, scrolling of history, long touch for context menu of message etc).

**Comment by mirhl** [comment]
Sorry, I should have mentioned I'm using Windows 7. 
10 is probably using [one](https://msdn.microsoft.com/en-us/library/windows/desktop/ff657750.aspx) of the [newer](https://msdn.microsoft.com/en-us/library/windows/apps/xaml/windows.ui.input.aspx) input [APIs](https://software.intel.com/en-us/articles/comparing-touch-coding-techniques-windows-8-desktop-touch-sample) to handle that, but I guess those ain't the problem.

**Comment by telegramdesktop** [comment]
@mirhl I just try to handle touch events in Qt that I receive, perhaps they didn't handle them for Windows 7 or did it differently, I'm not sure :(

**Comment by RPDeshaies** [comment]
I'm on Windows 10 with an ASUS Transformer Book T100TA and I have this problem

**Comment by mirhl** [comment]
@telegramdesktop The crazy thing I noticed is that qt itself seems to hook (and screw) something in the OS.

**Comment by mirhl** [comment]
For unknown reasons, I tried another driver version and now, no matter what the tablet interface always stick. 
I wonder if it couldn't have something to do with the input device you use when Telegram opens. 

Perhaps that's why on your Surface (where I guess there's *just* the touchscreen) you hadn't problems.

**Comment by Aokromes** [comment]
Works for me on windows 10 and 0.9.48.

**Comment by deonel** [comment]
I also had the same issue on windows 10 but i tried rebooting my machine and telegram responded to touch.
