### ISSUE TITLE
Pressing ESC on any window should close it

### ISSUE THREAD

**Issue by marcopaganini** [telegramdesktop/tdesktop#1367]
Pressing ESC on the conversation window brings back the main window with the contacts. Pressing ESC on the main window does nothing. It should ESCape from this window (i.e, close it). Not having a way to close the window quickly could represent a privacy problem for those using telegram in a low privacy environment.

**Comment by auchri** [comment]
No, just closing the current conversation is the right behavior. There will be a shortcut to close the window, but for that see #1060 

fyi alt + F4 is also fast

**Comment by marcopaganini** [comment]
Hmm, any reason why not close the window with ESC? ESC is somewhat
"universal" for "get me out of here" and it would make sense to close all
windows with it. Of course, I'm not talking about exiting telegram, just
closing all the windows.

**Comment by splintor** [comment]
I agree. Would also like Esc to close the window when no chat is open. Alt+F4 is less convenient.

**Comment by ralesk** [comment]
I'm very much "No" on this one.

It's popup dialogs and other modal things that can be dismissed with Esc.  Every main window you encounter is not closeable with Esc (look at pretty much any other chat application, browsers, etc.)

On the other hand, Esc should only ever close one level of modal stuff — i.e. if I have an image open, pressing Esc should only close the lightbox and not the chat it was opened from.  But that's a different bug really.

**Comment by marcopaganini** [comment]
What about Ctrl-W? Seems to be the gnome recommended way (but I could be
wrong.)

**Comment by ralesk** [comment]
That one seems to be fairly common for "Close Window" (also known as, nowadays I think less often, Ctrl+F4 in the Windows world).

**Comment by splintor** [comment]
@ralesk OK, so why not make it optional? For me, it is very convenient to use Esc to close the current conversation, and then another Esc to close the Telegram window and go back to my work (note that I use Telegram as a "pop-up" to do some chat, and not as a main working tool like a browser or a text editor).
However, I really don't mind having it optional, and even have it disabled by default, as long as I have the easy option to enable it, so I can easily press Esc to dismiss the entire Telegram window. Currently, I have to use Alt+F4 to close it, which is less convenient.

**Comment by marcopaganini** [comment]
+1 on making ESC an option.

**Comment by ANSI-C** [comment]
Any news on this? Are they willing to make it optional? The desktop version is useless for me without this basic behaviour that dates back to nineties.

**Comment by john-preston** [comment]
@ANSI-C You can use Ctrl+W to close the tdesktop window. Closing a window by Escape is not default in any way, there is no such Windows or OS X default app or a web browser app that closes the window that way.

**Comment by ralesk** [comment]
Generally, dialogs close on Esc, and they do so in Telegram as well (including panes that kinda act like dialogs would in a classic application).  Main windows don't and shouldn't close on Esc.

**Comment by ANSI-C** [comment]
@john-preston Skype and countless other IM applications do, they get rid of the UI by pressing ESC.
@ralesk I don't care about the academic talks on the semantics of _application window vs dialog_, I just wish the option to get rid of the window with a swift hotkey that has been used for decades for switching _contexts_.

**Comment by auchri** [comment]
> @john-preston Skype and countless other IM applications do, they get rid of the UI by pressing ESC.

Sykpe does not close it's window by pressing ESC.

I agree with @john-preston and @ralesk, the main windows shouldn't close on ESC.

**Comment by ANSI-C** [comment]
Me and countless other users don't want to change the application default behaviour, we just wish to have the _option_ to enable an alternate one. _Option_ and _choice_ are the magic words.

**Comment by auchri** [comment]
@ANSI-C Make a PR? :wink:

**Comment by ANSI-C** [comment]
@auchri when a contact sends me a message via Skype I can answer, get rid of the window by pressing ESC, and get back to what I was doing, with Telegram I just can't.

**Comment by ralesk** [comment]
Notice that in Telegram, chats are not separate windows¹, like they are (were) in Skype and numerous other clients.  Notice that in single window mode (at least the linux client) Esc does not close the chat window in Skype, or, AFAIR, in Pidgin.

And "Countless other users"?

¹: which is a different problem entirely, and though I'm now used to the single window behaviour, I wouldn't mind separate windows either, and then, yes, I'd like them to close on Esc.
