### ISSUE TITLE
Error in transition in the new context menu (search messages)

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1368]
Hello, thank you very much for the fast development of TDesktop.

I think there is a small error in the transition to search messages from a contact from the new context menu. I think that closing the search box, you have to return to the contact list directly, not the messages from the contact.

Thanks

**Comment by auchri** [comment]
Steps to reproduce:

* Resize telegram to enable compact mode
* Right click on a conversation and select "Search in chat"
* Close the search field

Expected: I should be at the contact list again
Current: I'm at the messages from the conversation
