### ISSUE TITLE
Emoticons in urls

### ISSUE THREAD

**Issue by shinax** [telegramdesktop/tdesktop#137]
I'm getting emoticons inside urls which I paste in the application. This cuts the urls and breaks them.
For example this url https://www.youtube.com/watch?v=jnlFa-188oQ
the 8o gets converted to the emoticon.
![image](https://cloud.githubusercontent.com/assets/1668702/4082748/973e2bbe-2ef4-11e4-83ac-7c3c290253b0.png)
I'm using 0.5.17 in 64bit Windows 7.

**Comment by telegramdesktop** [comment]
No replaces are applied inside words (like xD in abcxDef) and inside links from some version. Please check the latest, 0.7.10.
