### ISSUE TITLE
When resizing the TDesktop window, the notification indicator is lost

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1370]
TDesktop 0.9.15 64 bit
fedora 23 64 bit gnome

I mean the indicator on the top left of TDesktop.
When used the Compact Mode and receive messages, an indicator appears with the number of recent notifications. When you resize the window, this indicator disappears. The same is true in reverse. (Normal Window - Compact Mode).

Cheers

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
