### ISSUE TITLE
Lock in system tray

### ISSUE THREAD

**Issue by jhalt** [telegramdesktop/tdesktop#1371]
Simple feature: Right click telegram icon in system tray to "Lock Telegram" if a local password is set.

**Comment by DaFri-Nochiterov** [comment]
+1

**Comment by amiremami** [comment]
This is exactly what I was thinking.  Provide a feature to let us open telegram with password.

**Comment by auchri** [comment]
@amiremami Feel free to send us a Pull Request ;)

**Comment by amiremami** [comment]
@auchri Sorry, I'm not a coding guy unfortunately :(

**Comment by telegramdesktop** [comment]
@jhalt A context menu item can be added for locking, not just locking by the click itself.
