### ISSUE TITLE
Windows SDK configure issue

### ISSUE THREAD

**Issue by alejodosr** [telegramdesktop/tdesktop#1377]
Hi,

when correcting the Windows SDK Lib, where does this command have to be launched?

configure -debug-and-release -opensource -confirm-license -static -I "D:\TBuild\Libraries\openssl\Release\include" -L "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Lib" -l Gdi32 -no-opengl -openssl-linked OPENSSL_LIBS_DEBUG="D:\TBuild\Libraries\openssl_debug\Debug\lib\ssleay32.lib D:\TBuild\Libraries\openssl_debug\Debug\lib\libeay32.lib" OPENSSL_LIBS_RELEASE="D:\TBuild\Libraries\openssl\Release\lib\ssleay32.lib D:\TBuild\Libraries\openssl\Release\lib\libeay32.lib" -mp -nomake examples -nomake tests -platform win32-msvc2015

(command not found, every time I launch it)

Thanks

**Comment by telegramdesktop** [comment]
@alejodosr This has nothing to do with correcting the Windows SDK, this is configuration command for build Qt library.

**Comment by alejodosr** [comment]
Thanks, solved!
