### ISSUE TITLE
Main differences in the whole process (x64 build)

### ISSUE THREAD

**Issue by alejodosr** [telegramdesktop/tdesktop#1378]
Hi,

my machines is Windows 7 x64, What are the main differences in the whole process when building for this x64 target?

Thanks

**Comment by telegramdesktop** [comment]
@alejodosr Honestly, I don't know. I didn't build it for x64 target on Windows, I always build a x86 target even using the 64bit Windows for compatibility.

**Comment by alejodosr** [comment]
So, the whole process can be followed as it is, even if you're running a Windows 7 64 bits?

**Comment by alejodosr** [comment]
Only FYI, if you are using a Windows 7 64 bits on a x64 architecture, use "VS2015 x64 x86 Cross Tools Command Prompt" instead of the one stated in the Build Instructions for Visual Studio 2015, for building an x86 version of Telegram
