### ISSUE TITLE
A bug with back quotes

### ISSUE THREAD

**Issue by zsavely** [telegramdesktop/tdesktop#1379]
This bug appears when I send a message like:
```
Is it a `bug`?
```
And the thing is that `bug` should change the text style but it doesn't. I think there is some problem with the question mark at the end because
```
Is it a `bug` ?
```
works perfectly.

![image](https://cloud.githubusercontent.com/assets/5822417/11744108/8a7e9ab6-a01e-11e5-9ca6-03c3e3b03004.png)

**Comment by telegramdesktop** [comment]
@zsavely Yes, I'll add the question mark to the allowed symbols in such case. Thanks for your report.

**Comment by nop144d** [comment]
Cannot reproduce this, is it already fixed?
![image](https://cloud.githubusercontent.com/assets/11941221/18842341/bfa17858-8425-11e6-80ef-482c25cdf211.png)
Telegram version: 0.10.8

**Comment by stek29** [comment]
Offtopic: @nop144d what's wrong with your font rendering?_?

**Comment by nop144d** [comment]
@stek29 I don't feel anything wrong, so have no clue.
