### ISSUE TITLE
Add option to start telegram minimized at startup

### ISSUE THREAD

**Issue by prab4th** [telegramdesktop/tdesktop#1380]
Telegram windows has an option to start telegram _minimized_ at startup. Telegram for linux and macos does not have that. It does not have at least an option to make it start at startup.

**Comment by lopezbj** [comment]
In Fedora 27 with Telegram 1.2.6 , to start Telegram minimized, I just copied the `~/.local/share/applications/telegramdesktop.desktop` file to `~/.config/autostart/`
and added `-startintray` to the Exec path:

```
[Desktop Entry]
.
.
.
TryExec=/home/USER/PATH/TO/APP/Telegram/Telegram
Exec=/home/USER/PATH/TO/APP/Telegram/Telegram -startintray -- %u
.
.
.
```
Maybe a checkbox option could be give to the user which adds, removes (or modifies) this file, depending on whether the user selects _start automatically_, _don't start automatically_ or _start minimized_?

**Comment by ilya-fedin** [comment]
> Telegram for linux and macos does not have that.

Linux have now, so `linux` label can be removed, I guess :thinking:

**Comment by Aokromes** [comment]
maybe i need to dig enhancement labeled issues to see if some can be closed xd

**Comment by AleksandrL** [comment]
Fedora 27 (Workstation Edition), 4.13.9-300.fc27.x86_64
Telegram Desktop 1.9.14
================================================================
Thanx lopezbj, [this](https://github.com/telegramdesktop/tdesktop/issues/1380#issuecomment-362584874) helped me for a few months but Telegram stopped loading after installing "Dash to panel" GNOME extension and some other stuff.
My tested solution (lopezbj's solution update)
================================================================
[File ~/.config/autostart/telegramdesktop.desktop]
[Desktop Entry]
...
TryExec=/home/[My_login]/telegram.org/tsetup.1.9.9/Telegram/start.sh
Exec=/home/[My_login]/telegram.org/tsetup.1.9.9/Telegram/start.sh
...
================================================================
[File /home/[My_login]/telegram.org/tsetup.1.9.9/Telegram/start.sh]
sleep 10
cd /home/[My_login]/telegram.org/tsetup.1.9.9/Telegram
./Telegram -autostart -startintray -- %u
================================================================
Of course the execution privilege is needed, just do
chmod +x /home/[My_login]/telegram.org/tsetup.1.9.9/Telegram/start.sh
================================================================

**Comment by ilya-fedin** [comment]
OMG

**Comment by ilya-fedin** [comment]
![image](https://user-images.githubusercontent.com/17829319/76710985-c079ec00-6703-11ea-85fc-58977b97a414.png)

**Comment by AleksandrL** [comment]
> ![image](https://user-images.githubusercontent.com/17829319/76710985-c079ec00-6703-11ea-85fc-58977b97a414.png)

I found these three checkboxes at least a year ago.
In my case Telegram not loads without my solution (see above) and with all (or almost all) _combinations_ of these checkboxes. No icon, no messages received, etc.
In some cases (with some _combinations_) `ps -ax|grep telegram` showed me the process.
Please believe me, I've experimented 5+ hours before posting.
I can send configuration files and|or any other system information; ask me please, if you are interested.

**Comment by ilya-fedin** [comment]
> I found these three checkboxes at least a year ago.

There was no of these checkboxes a year ago, I added them a ~month ago.

> In my case Telegram not loads without my solution (see above) and with all (or almost all) _combinations_ of these checkboxes.

"Launch Telegram when system starts" creates .desktop and allows -auotstart
"Launch minimized" implies -startintray to -autostart

> No icon, no messages received, etc.

Maybe there are a race condition with tray, it should autostart, but maybe without icon. On 1.9.20 there are fixes for that.
