### ISSUE TITLE
Add hash tags

### ISSUE THREAD

**Issue by chaosdrop** [telegramdesktop/tdesktop#1381]
The hash tags in Telegram are a really great system... but 90+% of the time I can only thing about adding them after I have already sent a message or realize I need one on a messages from hours or even days ago... So it would be really cool to be able to add hash tags to old messages and even better would be to add private hash tags to other peoples messages. I keep trying to get my sister to #GroceryList but I don't think she'll ever remember.

**Comment by theus** [comment]
I usually use the trick of reply the old message with the hashtag for
future searches. But a native option will be great.

On Sat, Dec 12, 2015, 02:48 chaosdrop <notifications@github.com> wrote:

> The hash tags in Telegram are a really great system but 90+% of the time I
> can only thing about adding them after I have already sent a message or
> realize I need one on a messages from hours or even days ago So it would be
> really cool to be able to add hash tags to old messages and even better
> would be to add private hash tags to other peoples messages I keep trying
> to get my sister to #GroceryList but I don't think she'll ever remember
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/1381>.
>
-- 

Theus Falcão
Sent by Gmail Mobile

**Comment by auchri** [comment]
no api for that

**Comment by chaosdrop** [comment]
where would we go to request api features?

**Comment by auchri** [comment]
https://twitter.com/telegram
