### ISSUE TITLE
Close the fuck issues

### ISSUE THREAD

**Issue by ygcaicn** [telegramdesktop/tdesktop#13828]
I am thinking about how to close a large number of useless issues. Refer to this document, I think maybe you can try it through commit.

https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#closing-multiple-issues

```
git commit -m "\"$(for i in {10603..13174};do echo -n "closes #$i, ";done) message\""
```

**Comment by Aokromes** [comment]
thx! we reported to github yesterday but no luck deleting them, not only closing.

**Comment by john-preston** [comment]
![image](https://user-images.githubusercontent.com/17900494/112293248-6105d300-8cab-11eb-98c9-e0f55c425b50.png)
