### ISSUE TITLE
[Feature Request][Desktop] Invite friend to another friend's chat

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1384]
Provide an option to simply invite another friend to another friend's chat, something like conference.
For example I am chatting with A . and I want B join us to chat together, just for a short time.
This does not need to make a group and its for temporary chats, and for example up to 5 person only.

**Comment by theus** [comment]
I like it!

-- 

Theus Falcão
Sent by Gmail Mobile

**Comment by auchri** [comment]
No api for that -> create a group
