### ISSUE TITLE
qwebp.lib not found

### ISSUE THREAD

**Issue by alejodosr** [telegramdesktop/tdesktop#1385]
Following the building instructions a without any error, I have built Qtstatic libraries. However, in qtbase/plugins/imageformats there is not "qwebp.lib" file, required in the whole Telegram building. Any advice?

**Comment by ali-shamakhi** [comment]
I had this problem in VS2015
```
1>------ Skipped Build: Project: MetaEmoji, Configuration: Release Win32 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: codegen_style, Configuration: Release Win32 ------
3>------ Skipped Build: Project: Packer, Configuration: Release Win32 ------
3>Project not selected to build for this solution configuration 
2>LINK : fatal error LNK1181: cannot open input file 'imageformats\qwebp.lib'
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 2 skipped ==========

```
Fixed by adding `PathToProjectRoot\Libraries\QtStatic\qtbase\plugins` to codegen_style project properties > VC++ Directories > Library Directories
Any clues on why this behaviour ?

**Comment by john-preston** [comment]
@ali-shamakhi Release build was not tested, it should be fixed in the current dev branch already.

**Comment by ali-shamakhi** [comment]
@john-preston thanks for reply!
