### ISSUE TITLE
Implement RTL layout

### ISSUE THREAD

**Issue by SafaAlfulaij** [telegramdesktop/tdesktop#1387]
> -- translations to languages with rtl writing are not accepted right now, because the program interface does not support rtl layout, and it is a bad translation without it (arabic, hebrew).

Just an issue to keep us updated and to know if implementing the RTL layout will be in near future or not :)

**Comment by telegramdesktop** [comment]
@SafaAlfulaij I'm not sure about the near future, but all new UI I implement I try to do with RTL support from the beginning.. Together with redesign which is currently in progress this can really be finished some day.

**Comment by SafaAlfulaij** [comment]
@telegramdesktop One more thing, what about supporting all plural forms so adding a language won't lead to grammatical errors? I really tried to understand how the plural tags work but it looks too complex for a C++ learner.

**Comment by SafaAlfulaij** [comment]
I wonder if you could at least tell us what is your todo list somewhere publicly. I mean for the application itself not the protocol updates...
People are still asking to be able to change the font :D
