### ISSUE TITLE
Touch issue on Linux

### ISSUE THREAD

**Issue by f3flight** [telegramdesktop/tdesktop#1389]
Using Arch Linux on a tablet (Dell Venue 11 Pro 7140), running the latest version of Telegram (0.9.15).

Touch works for everything EXCEPT chat selection. So I cannot select a contact with my finger. Mouse click works, but touching contacts does nothing. Every other possible action works with touch - menus, attachments, emoji, voice message.

Let me know if I can help by providing any extra info.

**Comment by RussianNeuroMancer** [comment]
I have same issue with Gnome Shell 3.18 on Ubuntu Gnome 16.04.

**Comment by dmig** [comment]
Same issue for Telegram 0.9.49, Xubuntu 15.10, 16.04

**Comment by RussianNeuroMancer** [comment]
Not reproducible anymore with latest build.

**Comment by RussianNeuroMancer** [comment]
Not reproducible anymore with latest build.

**Comment by dmig** [comment]
Right. It was fixed in 0.9.4x. Can be closed now
