### ISSUE TITLE
[Feature Request] Minimize to tray

### ISSUE THREAD

**Issue by haimat** [telegramdesktop/tdesktop#139]
Would it be possible to add an option so that tdesktop shows an icon in the system tray (task bar) and minimizes to it?

**Comment by heihachi** [comment]
+1 for all the features

**Comment by rumatoest** [comment]
+1

**Comment by edubxb** [comment]
+1

I use GNOME 3

**Comment by atoj** [comment]
+1 for the cinnamon-minimize-to-tray thing =D

**Comment by telegramdesktop** [comment]
Tray icon using libappindicator with fallback to gtk_status_icon, if libappindicator is not installed, will be added in 0.7.7. I don't know actually, will it work on your system.

**Comment by RyuzakiKK** [comment]
I Installed the version 0.7.7 with Cinnamon.
When I open telegram I see a blank spot in the tray but the icon is not loaded. Also if I press the close button on telegram it doesn't minimize to tray and I can't find a way to minimize.
I don't know if this happen because the tray is not loaded correctly or because this feature is missing.

**Comment by telegramdesktop** [comment]
Did you build it from source? It is not released yet.

**Comment by RyuzakiKK** [comment]
I simply wrote 0.7.7 at it downloaded the lastest version. Maybe is available in telegram server?
https://updates.tdesktop.com/tlinux/tsetup.0.7.7.tar.xz

**Comment by telegramdesktop** [comment]
I've updated that archive, now it works in Ubuntu, you can try it once more.
I'm not sure about Cinnamon, but when you close the window by "X" they tray icon should stay where it was, allowing to show the window back from the menu.

![image](https://cloud.githubusercontent.com/assets/6113871/5774514/c81b59d8-9d7f-11e4-87c1-70da4ef48bf2.png)

**Comment by RyuzakiKK** [comment]
Ok now I see the tray icon and when I press the 'x' it minimize itself.
The only problem now is that the icon do a strange thing never seen before.
https://www.youtube.com/watch?v=YrwStDapUU0

**Comment by m00nk** [comment]
there is no tray icon on linux Mint 17 XFCE (telegram version 0.7.6). 

+1 For minimize on linux XFCE

**Comment by telegramdesktop** [comment]
0.7.6 does not support it, yes.

Looks like cyclic resizing, tested that on Ubuntu it worked fine, without cycling. Trying to fix that..

**Comment by telegramdesktop** [comment]
RyuzakiKK try once more please, it should stop resizing in cycle.

**Comment by RyuzakiKK** [comment]
Ok now it doesn't cycle anymore.
But I think there are 2 things to fix.
The first is the counter of the unread messages too big that hide the telegram icon completely (not high priority).
The second is that after I read the message the counter on the tray doesn't disappear and continue to display 1 unread.
![screenshot from 2015-01-16 12 09 01](https://cloud.githubusercontent.com/assets/3227973/5775354/3b61eb52-9d79-11e4-88ca-f7b1ee1cb01d.png)

**Comment by telegramdesktop** [comment]
That's weird, in ubuntu it changes after the unread count.

**Comment by RyuzakiKK** [comment]
Here it changes only with new unread messages, so it always say 1 or more but never disappear.

**Comment by nplezka** [comment]
Version 0.7.7: Good work, really fast! For now the only bug I see is no icon in Gnome Shell system tray.

**Comment by boris-il-forte** [comment]
Tested in debian with KDE. Finally!
works well except for the two isseues highlighted by @RyuzakiKK

**Comment by rumatoest** [comment]
Tested on Kubuntu 14.10
Confirming issues from @RyuzakiKK

**Comment by sander85** [comment]
I agree with @RyuzakiKK and also add that usually linux tray icons work a bit differently than the current tdesktop client. One click brings the window on top but another click on the icon should minimize it into tray not open context menu (we have right click for that!). So make it possible to hide the window with one click like other such apps do under linux :)

**Comment by susnux** [comment]
Thank you that is quite nice! Much better then my modded version.
But there are to point which are mentioned before:
1. (more important) it always shows 1-unread
2. left click should minimize it and then raise it again, context menu is right click.

But better then nothing ;-)
Tested on openSUSE 13.2 with KDE.

**Comment by mbnoimi** [comment]
Well done... Thanks a lot

**Comment by haimat** [comment]
The new tray icon is great, thank you very much. (Under XFCE) there is one issue though: The red icon that shows the number of unread messages stays forever, even after I have seen the new message. Is that a bug or a feature?

**Comment by SafaAlfulaij** [comment]
#403 @haimat

**Comment by rumatoest** [comment]
Kubuntu linux 14.10
Now I can not open minimized to tray application by clicking on icon. 
Why I must open tray menu to open messages window?

**Comment by focuz** [comment]
The current implementation is quite unusable - at least in KDE. One now has to right click on the Telegram icon in the system tray, to open a menu, then select 'Open Telegram'. Left-click does nothing whatsoever.

Normal behaviour would be: left-click on the icon to toggle between show window and hide window.

**Comment by SafaAlfulaij** [comment]
The developer should use the system icon Qt provides. That is the standard way.

**Comment by boris-il-forte** [comment]
Qt5 implementation is broken on linux.  
Please read the previous issues!

Now the system tray is perfectly usable in kde.

I suggest you to open a feature request instead of posting in this topic that should be closed...

**Comment by focuz** [comment]
With all respect, boris-il-forte, the system tray issue has not been resolved sufficiently and is certainly not 'perfectly usable'. A recent update of libappindicator1 seems to have worsened things.

**Comment by boris-il-forte** [comment]
I'm using libappindicator1 (0.4.92-3.1) and libappindicator3-1 (0.4.92-3.1) on debian testing.
Works perfectly, the only missing feature is the left-click feature you are suggesting. I agree that is a good feature to have, however it doesn't make unusable the tray icon, and you can overcome (partially this issue adding a desktop launcher, and you will get almost the same behaviour...

I think that if someone says that the tray icon is unusable on kde, then the developer could think to disable that feature because is broken. And it's not broken at all! There is only a missing feature (that saves you 1 click)

**Comment by telegramdesktop** [comment]
Maybe tray icon will be supported better when moved to Qt 5.4, but while Qt 5.3.1 with broken Linux tray icon is used, I use only libappindicator implementation.
