### ISSUE TITLE
[Bug] Multi inputs that doesn't respect Bidirectional text (Arabic text not aligned to right)

### ISSUE THREAD

**Issue by SafaAlfulaij** [telegramdesktop/tdesktop#1390]
"Add group/channel dialog": the name inputs doesn't align Arabic text to right (While the text direction is right).
"Add contact dialog": first and last name and search input (same as above) ((Same with adding members/admins to channels))

**Comment by SafaAlfulaij** [comment]
@telegramdesktop I hope you fix them in the coming release:smile:

**Comment by telegramdesktop** [comment]
This is strange, because all input fields (add group / channel / contact) are done in the same way as message input field is done. Do they work differently in terms of handling bidi text? Can you provide an example -- for example, what text should I paste from clipboard in message input field and in the add contact dialog box so that they will be differently shown?

**Comment by SafaAlfulaij** [comment]
@telegramdesktop: You can use "تجربة" for example.
Here are some screenshots:
![Align problem 1](https://cloud.githubusercontent.com/assets/3509617/11813421/7ab6b906-a352-11e5-9ac6-7d6e62195d00.png)
![Align problem 2](https://cloud.githubusercontent.com/assets/3509617/11813420/7ab62fea-a352-11e5-9c14-f0bea18f86c5.png)
![Align problem 3](https://cloud.githubusercontent.com/assets/3509617/11813477/bf403b38-a352-11e5-8e9f-62e6b6772c47.png)
![Align problem 4](https://cloud.githubusercontent.com/assets/3509617/11813476/bf3ebcae-a352-11e5-93c8-2d2107744759.png)

**Comment by telegramdesktop** [comment]
Yeah, I see that one. I think I will be able to fix that for the next version, thanks for your report.

**Comment by SafaAlfulaij** [comment]
Your most welcome!
Thank you.

**Comment by telegramdesktop** [comment]
Please try this out in the 0.9.17 version.

**Comment by SafaAlfulaij** [comment]
Thanks! It's correct aligned now :smile:
