### ISSUE TITLE
Too big window width on the windowsdesktop app with dual monitors

### ISSUE THREAD

**Issue by Hast** [telegramdesktop/tdesktop#1391]
Windows 7, 2 monitors, 1920x1080 each.
When I click on the full screen button while telegram app is on the left monitor, small vertical strip appears on the right one.

![Screenshot](http://dl3.joxi.net/drive/0000/1843/1843/151213/aeb58326aa.jpg)

**Comment by auchri** [comment]
Duplicate #373

**Comment by telegramdesktop** [comment]
@Hast I don't know how to fix that in Win7, it is fixed in the system in 8/8.1/10.

**Comment by wwevo** [comment]
It is not fixed in windows 10 ^^

Current version, all updates installed both windows and gpu (gtx1060)

https://user-images.githubusercontent.com/18307732/40496271-9ff87eb2-5f79-11e8-91ff-7b11e4bff974.png
