### ISSUE TITLE
@Number link causes log out and very hard to log in

### ISSUE THREAD

**Issue by egorpugin** [telegramdesktop/tdesktop#1392]
Repro steps on the latest stable client (on windows).
1. Write 1st msg: 'something @Number'.
2. Write 2nd msg: 'something else @Number'.
3. Click on the first message link (@Number).
4. Click back at the top of the contact info.
5. Click on the second link (@Number).
Now you're logged out and after log in you can instantly being logged out again.

**Comment by stek29** [comment]
@egorpugin I can't reproduce this, do you still have this problem?

**Comment by egorpugin** [comment]
No. I can't repro this anymore. Closing.
