### ISSUE TITLE
[Feature Request] Let members message to telegram channels

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1397]
Provide an option for channel owners to receive messages by members. For now, the contact is really one way.
Thanks

**Comment by auchri** [comment]
No api for that.
fyi that's what channels are created for. If you want talk with the members, create a group instead.

**Comment by amiremami** [comment]
@auchri Yes you are right, but unfortunately group has it's own limitations. number of members limitation and also there is no view counter. Everyone is looking for merging group and channel features :( Thanks anyway.
