### ISSUE TITLE
[Feature Request][Desktop] Press up arrow key, repeat the last sent message

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1398]
This is really useful feature for time you want to repeat the same thing last time you sent. So in the message box, press arrow up, and last sent message (or even more) will appear.

**Comment by telegramdesktop** [comment]
@amiremami This is very geeky, most of the users are used to scrolling by arrows, not console-like behavior.

**Comment by auchri** [comment]
Duplicate #873

**Comment by amiremami** [comment]
@telegramdesktop Yes, when focus is in the window, it should scroll, but when focus is in the "write a message box" it can shows last message. This feature was in yahoo messenger and it was really helpful for repeating the previous sent messages. Thanks anyway :)
