### ISSUE TITLE
Schedule send post

### ISSUE THREAD

**Issue by mamadoo** [telegramdesktop/tdesktop#1399]
Please add support schedule send post in channel telegram.
This feature very helpful for channel manager. Because with this property their channel always updated.

Thanks.

**Comment by DaFri-Nochiterov** [comment]
API doesn't supporting this.
+1 for this feature.

**Comment by mamadoo** [comment]
@DaFri-Nochiterov it means not possible to do that?

**Comment by DaFri-Nochiterov** [comment]
@mamadoo, yes, impossible.
