### ISSUE TITLE
Image viewer breaks after resolution change

### ISSUE THREAD

**Issue by mirh** [telegramdesktop/tdesktop#1400]
As title. 
Launch Telegram. 
Change resolution (in my case: 1920x1080 --> 1440x1080)
Open some photo. 

*Possibly* something to do with #373

**Comment by ofalvai** [comment]
I think this is a duplicate of #1542

**Comment by mirh** [comment]
If any, I see #1604 duplicate of this. 
But it has nothing to do with *higher* resolution. 

And I just now notice the cant reproduce tag @auchri (which seems silly tbh)
I'm on windows 7 if it can help. 
Perhaps it's something with changing resolutions with **different** aspect ratios?

**Comment by Aokromes** [comment]
I have a similar/related issue, if i open one image on portrait mode and close it, i rotate tablet and open the same image it will have problems to show properly and won't fit the screen.
