### ISSUE TITLE
Telegram tray icon didn't shown after window closing 

### ISSUE THREAD

**Issue by dmpanch** [telegramdesktop/tdesktop#1401]
When I close telegram window -  it stop showing icon in tray. I hear when get new messages but nothing to see here. I should open .exe again to fix it.
![default](https://cloud.githubusercontent.com/assets/4539449/11822414/1bda9d74-a377-11e5-9bc2-d276faed8152.png)

**Comment by rredesigns** [comment]
Seems a very common bug. Happens under Linux too (KDE, Cinnamon and Mate tested). Only solution is to kill the process and open it again, the second start keeps the system tray icon successfully.

**Comment by camypaj** [comment]
I also experience this, and while what @rredesigns suggested works, it isn't exactly a solution, rather a workaround.. I wonder what is causing it.

**Comment by rredesigns** [comment]
I think it has to do with the system tray itself. I always make Telegram run at startup, but it bugs, so I set a 60 seconds delay to it, so Pidgin starts before and uses the tray, once Telegram starts, 90% of the time it stays there. I think that it has to do with Telegram Desktop scope. Linux fs is quite complex, and all apps run from /bin dir, while Telegram runs from the home folder, so probably the OS is not giving enough importance to it.

**Comment by jorgicio** [comment]
Same happens to me, but the tray icon never appears D:

**Comment by rredesigns** [comment]
@jorgicio really? It's been more than a year since this issue. It works perfect for me with Manjaro XFCE, and I didn't hear of problems withe the MATE edition and the system tray. Maybe your OS is missing something. Also, try with a different tray, install tint2 panel for instance and see if that works.

**Comment by jorgicio** [comment]
@rredesigns Well, it's not because before 1.0.26 it worked flawlessly and not now. And using the same MATE version in both cases. So the culprit may be in some Telegram Desktop code.

**Comment by rredesigns** [comment]
Check the system monitor and see if Telegram keeps running in the background and if it has significant activities. Telegram does change all the time, but there are some areas that remain the same. I will check into this a bit more.

**Comment by jorgicio** [comment]
Checked and it does, it's still running in background, I had to open Telegram with the launcher when I want to watch it. Also receives notifications and can open the app from therem

**Comment by rredesigns** [comment]
How did you install it?

**Comment by jorgicio** [comment]
From the package manager (Portage in my case), as usual.

**Comment by rredesigns** [comment]
Also, can you see if what I suggested does something? (killing it, then restart the app). Also, can you check the official build from telegram.org?

**Comment by jorgicio** [comment]
Killing and restarting the app does not work, the behaviour is the same.

And I just run a clean Telegram installation but this time as root, and the tray icon opened. I'll try cleaning my installation but this time as a regular user.

**Comment by rredesigns** [comment]
Just dowload the client from the web and run the binary in it. Then tell me what happens. Some people have problems with the repo install, but the official client works just fine.

**Comment by jorgicio** [comment]
Done, and happens the same. However, as root it works fine.

**Comment by rredesigns** [comment]
I hope you are using gksudo or the root sesion for that. 

I don't know how the system tray actually works. I will find some info about it and be back if I have another idea.

**Comment by jorgicio** [comment]
In fact, I was launching the telegram desktop from the command line. And it also launches and it always run with the tray icon there.

**Comment by jorgicio** [comment]
Tried with a previous Telegram version, and tray icon appears and all working fine.

**Comment by rredesigns** [comment]
Then I guess for now you can create a shell script that runs Telegram. Then add that to the menu, or modify the telegram .desktop file so it uses the script.

**Comment by rredesigns** [comment]
Oh, god. Apparently every window manager has it's own tray, though Qt should be able to handle them. Did you try Tint2? It is important to see wheter this issue is Qt or MATE.

**Comment by jorgicio** [comment]
Ok, just tried with tint2, and it didn't work. Also killed and restarting telegram-desktop and nothing. Tray icon still doesn't come out.

**Comment by rredesigns** [comment]
This is kind of tricky because Telegram uses Qt and MATE is all Gtk. I assume also that you have Qt4 installed. It looks like Telegram uses an older version.

**Comment by jorgicio** [comment]
Well... It's true but I have to because of Clementine.

**Comment by rredesigns** [comment]
Well, I see Telegram is using Qt5 now. So make sure you have the latest version.

**Comment by jorgicio** [comment]
I have both versions installed, and the fact that a previous version of Telegram worked fine but not the most recent, it says that the problem may be in Telegram itself.

**Comment by rredesigns** [comment]
Yeah, that would be the first thought, but just consider how probable it is they would modify that part of the app. I just don't see that happening. Also, I'm using XFCE which is Gtk too. If it had to do with toolkits or it's implementations, I should be having the same issue. 

When you said that launching from CLI it worked, you meant as root or regular user?

**Comment by jorgicio** [comment]
I meant as root, and there the icon appears. And remember that MATE migrated all its code to GTK+3 while XFCE still uses GTK+2.

**Comment by rredesigns** [comment]
Then maybe the problem is with dbus or polkit perhaps. If it works with root, then Telegram itself works. I have no idea though how MATE's window manager launches the apps, or what orders it uses to do so, but that would be a good place to start looking.

**Comment by jorgicio** [comment]
Well... I rebuilt mate-polkit with appindicator support, and it didn't work either. Yes, I had to inspect how MATE launch its apps, but I noticed that are more people with the same problem as me.

**Comment by rredesigns** [comment]
Yeah. I had that problem myself, but a year ago I was a complete noob to Linux. xD

I learned a bunch of stuff along the road, and one of them is that a bug could be pretty much anywhere. In this case, since Telegram works fine as root, then I think it is permission related and how the app is being called up, but I don't know much about MATE or Gnome to say a word about that. What I do know though, is that each system tray belongs to every DE, and that makes it a lot harder, since you have to know very well your window manager to debug this stuff. Luckily, since they are both open source a solution will arrive sooner or later. 

I will keep checking into it. There are a bunch of issues like this one with many answers. Perhaps you can find something useful in other open issues, or closed ones that's been solved already.

**Comment by jorgicio** [comment]
I don't know what made came out that story, I just want to make know that it's an issue that happens to most of people and did not happen before. I know every DE works in some different way, and also I'm not going to install all of them to test.

**Comment by rredesigns** [comment]
What's story? I was talking about the time I had the same issue you do. And to be honest, only in MATE I had it, so I'm pretty sure it has nothing to do with Telegram.

**Comment by jorgicio** [comment]
If it was MATE only, most of the people would have not this issue in some other DE, also, explain why just now came out this issue and not with previous versions. It shows clearly the problem may be in Telegram itself.

**Comment by rredesigns** [comment]
Well, I could ask something similar. How come I never, ever, experienced this issue neither with xfce, nor openbox, i3 or even jwm? No matter what version of Telegram I was using, never happened not even once? How could it be a Telegram problem when it never failed me once with other DE/WM than MATE?

**Comment by jorgicio** [comment]
Because previous versions did the work better ;) When it fails with the same configuration of the DE as before, the problem is the software itself (in this case, Telegram). It may not fail in some other DEs, but since the time it fails in some desktop, without modifying some other setting and making previous versions worked better, we can conclude the problem is also in Telegram. Being that case, it may take some time to fix it and there's no some reason to make it hurry up ;)

**Comment by rredesigns** [comment]
"...It may not fail in some other DEs..." That's my point. It should affect all Gtk-based DE's in the exact same way. Well, maybe porting to Gtk3 was not a good idea. xD

BTW, did you try other clients, like Cutegram?

**Comment by jorgicio** [comment]
Not necessarily to affect all gtk-based all GTK-based DE's as a rule, and not necessarily in the same way. I'm using MATE 1.18, and before 1.0.26, Telegram Desktop worked flawlessly until that version since. It shows that the culprit is Telegram because it didn't not know how get rid with the DE settings. So explain why it worked before and not now. And it's not necessarily the DE the culprit.
And Cutegram is somewhat outdated. No plan of changing the client because of a devel-level failure in the app ;)

**Comment by Translator5** [comment]
In linux mint it worked for around a week. but for days now again broken tray icon :confused:!

**Comment by JuPlutonic** [comment]
Close button hide main window, Telegram disappears from bar and it isn't showing tray icon. 
Tint2 panel (Ubuntu 16.04.2 x64) Telegram 1.1.19.

Maybe on beta, on Telegram compiled from sources you guys haven't seen such behavior?
PS:
Notifications working (native and generic). If I quickly click on notification's reply button it is open main window. And now I trying not to use close button on Telegram main window.

**Comment by jeroenst** [comment]
I also experience this bug on Linux Mint 19.1 Tessa x86_64

**Comment by dima1206** [comment]
Windows 7, Telegram 1.8.13, enabled start at boot. Sometimes it opens only on the background and not in the system tray. Killing the process and reopening telegram help solve the problem until one of the next restarts of the windows.

**Comment by vonzepp** [comment]
Very annoying bug :( Constantly repeats on Windows 10 1909 Build 18363.778.
It is present on several versions of telegram desktop including latest 2.1.6
Workarounds:
1) Turn On/Off "Show taskbar icon" in Settings
2) kill Telegram from task manager and restart it
