### ISSUE TITLE
Note for Build Instructions in Visual Studio (Qt 5.5.1)

### ISSUE THREAD

**Issue by alejodosr** [telegramdesktop/tdesktop#1402]
When building Qt5.5.1 ,be sure that this command is properly executed:

perl init-repository --module-subset=qtbase,qtimageformats

In my case, just only one of those modules was taken into account, so that a had to execute it separately with every module.

**Comment by auchri** [comment]
Would be great if you would open a pull request to fix this issue :)

**Comment by 3ngineer** [comment]
This command "perl init-repository --module-subset=qtbase,qtimageformats" doesnt execute properly for me, I dont know what to do! 
here's the code :::

 MINGW32 /d/TBuild/Libraries/QtStatic (5.5)
$ perl init-repository --module-subset=qtbase,qtimageformats
      3 [main] perl 6464 child_info_fork::abort: address space needed by 'NamedCapture.dll' (0x2B0000) is already occupied
Can't fork, trying again in 5 seconds at init-repository line 286.

**Comment by stek29** [comment]
Try to run it in git shell.

**Comment by 3ngineer** [comment]
I used git for all of the steps!
