### ISSUE TITLE
[feature request] Display who in group has read up to where

### ISSUE THREAD

**Issue by jaywick** [telegramdesktop/tdesktop#1403]
I'm not sure if this has been brought up before (please close if it has).

Hangouts and WhatsApp show who has read up to which point in the thread. Is this possible to implement in Telegram?

**Comment by DaFri-Nochiterov** [comment]
No API for that.
I too want same feature :c

**Comment by jaywick** [comment]
Where can I suggest this feature for API? Is there like a UserVoice style website?

**Comment by DaFri-Nochiterov** [comment]
@jaywick, on Twitter: https://twitter.com/telegram.
