### ISSUE TITLE
File Chooser on Linux is Butt Ugly

### ISSUE THREAD

**Issue by mypetbirdrules** [telegramdesktop/tdesktop#1404]
The file chooser in telegram desktop doesn't respect system-wide themes from gtk.

**Comment by DaFri-Nochiterov** [comment]
Duplicate #987

**Comment by ManuelSchneid3r** [comment]
I am the author of #987. #987 is not about the filechooser. #987 is about the application style in general. Check #982 for native filechooser.

**Comment by john-preston** [comment]
In the latest 0.9.57 version gtk file chooser should be used if it is available. Please check.
