### ISSUE TITLE
Telegram monopolizing sound device  [Arch Linux]

### ISSUE THREAD

**Issue by graydonhall** [telegramdesktop/tdesktop#1405]
when running 'fuser -v /dev/snd/*' before starting telegram, pulseaudio is in control of my sound device and everything is running as expected.

```
                    USER        PID ACCESS COMMAND
/dev/snd/controlC0:  (myuser)   3102 F.... pulseaudio
```
Then after running telegram, the sound device is taken over by telegram, completely barring access to pulseaudio and screwing up sound on my computer system-wide until I close it.

```
fuser -v /dev/snd/*
                     USER        PID ACCESS COMMAND
/dev/snd/controlC0:  (myuser)   3102 F.... pulseaudio
                     (myuser)   3299 F.... Telegram
/dev/snd/pcmC0D0p:   (myuser)   3299 F...m Telegram
```
Why isn't telegram using pulseaudio like every other application? I cannot use sound on my computer and telegram at the same time because of this. A temporary workaround is running telegram in firejail which prevents it from taking over the /dev/snd/* and allows me to use sound, but this must be a problem for others even if they don't realize it (took me a few hours to find the problem).

**Comment by adavis98** [comment]
Did you try turning it off then back on?

**Comment by jarnold120** [comment]
What about unplugging it and then plugging it back in?

**Comment by adavis98** [comment]
Did you make sure your headphones were plugged into the headphone jack and not the microphone one?

**Comment by adavis98** [comment]
I did a little  searching around. Turns out that you need to make sure that neither the system volume nor the windows media player are muted.

**Comment by jarnold120** [comment]
Have you tried shaking your laptop a bit or blowing into the fan grill. I find that usually works for me.

**Comment by ralesk** [comment]
Hmm, I wonder if it's distro related, as I've never seen this happen (I listen to music on my computer while also having Telegram running almost all the time) on my Fedora at least.

**Comment by graydonhall** [comment]
This was a distro related issue, I identified the problem with other applications as well. Not a telegram bug. I got a new laptop and reinstalled and everything works fine, so I will likely never know what caused it.

**Comment by xuzhao9** [comment]
I actually meet the same problem under openSUSE Tumbleweed with Plasma 5. Telegram version 0.9.48-19.6.
Any hints for solution?
