### ISSUE TITLE
OS X emojis not working

### ISSUE THREAD

**Issue by Nuruddinjr** [telegramdesktop/tdesktop#1408]
OS X TDesktop from AppStore latest versions are not converting to emojis except :-) ,

**Comment by telegramdesktop** [comment]
@Nuruddinjr Can you provide an example? What does not work there?

**Comment by Nuruddinjr** [comment]
<img width="237" alt="screen shot 2015-12-16 at 11 21 25 pm" src="https://cloud.githubusercontent.com/assets/9083431/11849847/c8ad8a3c-a44b-11e5-908a-02a75a3e58c4.png">
here

**Comment by Nuruddinjr** [comment]
<img width="422" alt="screen shot 2015-12-16 at 11 22 41 pm" src="https://cloud.githubusercontent.com/assets/9083431/11849896/0948527a-a44c-11e5-8941-9d9647706019.png">
here as well, as we can see when emoji goes alone it works but with words it doesnt work

**Comment by telegramdesktop** [comment]
This screenshot is not from Telegram Desktop, but from another OS X app.

**Comment by Nuruddinjr** [comment]
<img width="424" alt="screen shot 2015-12-16 at 11 26 17 pm" src="https://cloud.githubusercontent.com/assets/9083431/11849958/735017fc-a44c-11e5-97b6-6eeec0186d3b.png">
Isn't it a Telegram Desktop App?

**Comment by auchri** [comment]
No, that's not Telegram Desktop.
See https://github.com/overtake/telegram
