### ISSUE TITLE
Yellow icon in tray

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1411]
![image](https://cloud.githubusercontent.com/assets/10401817/11866156/56faed16-a4d3-11e5-888c-b7b9e2ac6fd7.png)

I install new Linux Mint 5 days ago, and immediately download TDesktop, Chrome.
And when I looked in tray I saw yellow icon of TDesktop. 
What? Why icon is yellow? It's Telegram Emoji?

OS: Linux Mint 17.3 (Cinnamon, 64bit)
TDesktop: 0.9.15 dev

**Comment by ftdebugger** [comment]
I have same issue after update from 17.2 to 17.3. 

Also change behavior on click: now it show menu instead of telegram window

![telegram](https://cloud.githubusercontent.com/assets/170282/11913455/83a9396e-a675-11e5-9dc3-b50bc28459d8.png)

**Comment by arseniypetrikor** [comment]
I have same issue after update to 17.3
![2015-12-21 10 36 03](https://cloud.githubusercontent.com/assets/14013687/11924151/a6a590e8-a7ce-11e5-8e8d-caf8b32447ee.png)

**Comment by auchri** [comment]
version 17.3 does not exist....

**Comment by DaFri-Nochiterov** [comment]
Now I changed my desktop environment to 'MATE' and no longer getting this problem.
It's only on Cinnamon.

**Comment by xit0c** [comment]
Same issue.
OS: Linux Mint 17.3 (Cinnamon) 64bit
Telegram Version: 0.9.15
![screen](https://cloud.githubusercontent.com/assets/15820253/12059934/801023fa-af65-11e5-8e92-4088b9cedd5a.png)

**Comment by xit0c** [comment]
I've also noticed that the menu item is missing, even if it appears in the settings of the menu applet... should I open another issue for this? I think they're related somehow but I'm not sure.
![screen2](https://cloud.githubusercontent.com/assets/15820253/12060114/ad9f807e-af68-11e5-83ec-797db5291647.png)

**Comment by auchri** [comment]
better open a pull request to fix the issue :)

**Comment by DaFri-Nochiterov** [comment]
This problem only in Cinnamon desktop environment as I understand.

I'm using MATE (on Ubuntu 15.10) and don't get this:
![image](https://cloud.githubusercontent.com/assets/10401817/12084766/2a002cb4-b2e2-11e5-9930-c69d6fa961cd.png)

**Comment by dhomo** [comment]
Same issue
Cinnamon 2.8.6

**Comment by camypaj** [comment]
Hi all,

interestingly enough, it seemed a bit more stable with up-to-date cinnamon
(2.8.6) on Linux Mint 17.3 and Telegram Desktop (0.9.18).
Unfortunately, I can still reproduce the problem by:
1. Starting Telegram (app icon is there in system tray)
2. restarting Cinnamon (alt+F2, r)
3. icon disappears, and telegram, if you close it, still runs in
background, notifies and all, but the icon in tray is gone, and I cannot
get it back (or close Telegram, without killing it).

Regards

On 15 January 2016 at 17:08, dhomo <notifications@github.com> wrote:

> Same issue
> Cinnamon 2.8.6
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/1411#issuecomment-172002195>
> .
>



-- 
Milan Antonijević

**Comment by infraredbg** [comment]
Same for me after updating from 17.2 to 17.3.
Also on Cinnamon.

**Comment by DaFri-Nochiterov** [comment]
After updating from Ubuntu 15.10 to Ubuntu 16.04 this happened again =(

**Comment by xdirex** [comment]
Same issue
Mate, Debian
![traytelegram](https://cloud.githubusercontent.com/assets/3026628/15095080/614763c8-14c0-11e6-8908-4731c89b0ee9.png)

**Comment by Translator5** [comment]
ref. #2638  but ffor me it's fixed
