### ISSUE TITLE
Make image caption optional

### ISSUE THREAD

**Issue by iklimchuk** [telegramdesktop/tdesktop#1412]
Please make image caption (desktop client) optional. Currently there is no way to disable it.
Telegram was perfect instant messenger before this feature introduction but now every time I share an image I have to additionally submit it.
Not all users need captions so it will be great if we have a way to disable this feature.

![photo_2015-12-17_15-37-35](https://cloud.githubusercontent.com/assets/10230808/11872225/71fc84e8-a4d4-11e5-8fed-af337d30348a.jpg)

Thank you.

**Comment by auchri** [comment]
Just press enter or "Send" to send the image without a caption.

**Comment by iklimchuk** [comment]
i know that, but it requires additional, not needed action every time i send an image
