### ISSUE TITLE
Provide rotate in the photo viewer

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1413]
Provide Rotate Feature in Right Click

![asd](https://cloud.githubusercontent.com/assets/15929497/11872979/90caa248-a4d8-11e5-9aff-ec0cc9fe316a.png)

**Comment by auchri** [comment]
Not there, but it could be implemented in the photo viewer

**Comment by amiremami** [comment]
Thanks auchri, is it also possible to add zoom feature by pressing + in photo viewer?

**Comment by auchri** [comment]
try <kbd>ctrl</kbd> + <kbd>+</kbd> ;)

**Comment by amiremami** [comment]
oh right, thanks a lot ;)

**Comment by zaz600** [comment]
+1 up

**Comment by amiremami** [comment]
No update on this? :(

**Comment by amiremami** [comment]
Please add this if it's possible, My friends sent me a lot of images of book and many of them needed rotation.

**Comment by amiremami** [comment]
Please provide this feature, this is really practical. Thanks.

**Comment by stek29** [comment]
@amiremami I doubt that "Please provide it" comments would speed up development.

**Comment by frops** [comment]
Hello, guys! When will it be implemented?

**Comment by Aokromes** [comment]
Maybe a good idea it can be to add buttons for zoom in, zoom out, rotate right, rotate left, exit full screen on the viewer.

**Comment by danbruegge** [comment]
Maybe the simplest solution or workaournd will be to add an option and let the user choose an external/OS default imageviewer?

**Comment by curtusoft** [comment]
i have friends for wich the concept of landscape image and portrait mode is abstract. so they make a photo with the rotation sensor disabled on their phones.

All the basic photo viewers, as how bullshit they can be should provide a option to rotate a photo. it's not optional it should be there, WTF.

we cannot rotate the monitor or i have learn stupid arguments like ask people to rotate the photos before send, maybe i can read the message 4h after the photo was send, and the user is not online.

this is a **required feature** the other option are not a viable solution.
it's very dissapointing that there is not a rotation button/option or whatever.

**Comment by kasumiru** [comment]
up

**Comment by andrhua** [comment]
tfw (it seems that) majority of tg devs use macs and rotate/zoom buttons are present in mac client

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/4544b091a0722190f5aa21a1e01ff5df5b435bcf coming on 1.9.10

**Comment by amiremami** [comment]
Perfect news and really appreciate your effort :)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v1.9.10
