### ISSUE TITLE
[Feature Request] Show bigger Emojis

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1414]
Show bigger emojis if we send them without any text, same as skype.

![fgh](https://cloud.githubusercontent.com/assets/15929497/11879594/9dd17664-a4fc-11e5-9e72-b2c67c011422.png)

**Comment by iklimchuk** [comment]
you always can use stickers if you want something "big".
imho, chat area should stay as compact as possible.

**Comment by amiremami** [comment]
You are right, but when we send emojis without any text, it is exactly same as the time we are sending sticker. And I didn't mean show it as big as stickers, just a bit more bigger same as skype.

**Comment by telegramdesktop** [comment]
@amiremami Including large versions of more than 1600 emoji that are currently supported will increase the installer too much in my opinion.

**Comment by amiremami** [comment]
That's also true, @telegramdesktop you are the boss :yum:  I'm just telling my opinions maybe they would be useful :)

**Comment by amiremami** [comment]
Finally this happened in mobile version, any chance for desktop?

**Comment by stek29** [comment]
youtu.be/umDr0mPuyQc
@amiremami they were removed in mobile version too ;)

**Comment by RememberTheAir** [comment]
They brought them back in Telegram 5.5

**Comment by alivekenny** [comment]
I'm also would like to see large emoji in TD. Especially since we have it on iOS and Android :-)

<img src="https://user-images.githubusercontent.com/21039303/55225278-1bd17680-5234-11e9-8826-3c960d56cceb.PNG" width="350">

**Comment by 23rd** [comment]
This is awful. =(

**Comment by alivekenny** [comment]
@23rd Well, it is personal opinion. Some hate stickers, some hate emojis or gifs. I don't really like chat wallpapers myself (default wallpaper in TD makes me puke). And it's okay to have this opinion, you don't have to use it afterall, right? But for people who do like it, why not make their experience richer? :-)
