### ISSUE TITLE
[Suggestion] Show images on contact list when in small screen

### ISSUE THREAD

**Issue by igorsantos07** [telegramdesktop/tdesktop#1415]
Would be easier to use the application if the small-screen layout was similar to messenger.com, where instead of displaying a complete list of chats, including user name, picture and last message, only the 
picture would appear.
This enables the user to switch quickly between chats without taking much real state and requiring additional actions.

Mock:
![mock](https://cloud.githubusercontent.com/assets/532299/11880308/21ab7446-a4e7-11e5-8b33-1d1767414193.jpg)

**Comment by iklimchuk** [comment]
if you decide to do this please make it optional.

**Comment by theus** [comment]
The avatars could be rounded. =)

**Comment by haevalencia** [comment]
Great! +1

**Comment by green-ex** [comment]
I'm upvoting this too! Currently, the Contact List disappears entirely, but just a small list with the icons would be a tremendous help in switching chats.
Otherwise, maybe provide an option to resize the width of the Contact List?

**Comment by stek29** [comment]
Btw OS X native app already has this feature.

![image](https://cloud.githubusercontent.com/assets/11808223/19166955/649aa480-8c12-11e6-8ff3-53200ba81a06.png)

**Comment by igorsantos07** [comment]
I wouldn't say this is closed.
I've seen the new feature but it still hides the contact pictures sidebar
when the window gets smaller, just like it happens when the contact list is
full-sized.

The contact pictures should be kept there even on the smaller window.

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]
