### ISSUE TITLE
[Feature Request] Provide Simple Editing Feature for Pictures

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1417]
It would be great if you add a feature for simple editing images and let us add for example some basic shapes such as circle, cross, checkmark and arrow to images.

![rtytry](https://cloud.githubusercontent.com/assets/15929497/11881023/89ddd104-a504-11e5-894e-2ab072fd9648.png)

**Comment by auchri** [comment]
I think it would not be worth the amount of work.

Use your system image editor or gimp or something like that.

**Comment by amiremami** [comment]
Okay thanks anyway auchri :)
