### ISSUE TITLE
Can't type accents in image caption on GNU/Linux

### ISSUE THREAD

**Issue by hk0O7** [telegramdesktop/tdesktop#1418]
Since the caption feature was introduced, I haven't been able to type accents (diacritics) in the caption text box, although I can paste text with accents. I am using Linux Mint 17 MATE Edition (x86_64).

**Comment by damaru2** [comment]
Same here. Linux Xubuntu 14.04

**Comment by JPTIZ** [comment]
Same here. Arch Linux. Telegram version 0.9.28.

**Comment by marialejandra** [comment]
Issue #1739 here. I don't have problems with accents (using an AZERTY keyboard) but just with the circumflex accent (â, ê, etc.) and the diaeresis (ä, ë, etc.). I'm using (X)ubuntu 15.10.

**Comment by john-preston** [comment]
This should be fixed in 0.9.55 alpha version, please check.

**Comment by hk0O7** [comment]
I can confirm they're working correctly in version 0.9.55a. Thank you!

**Comment by damaru2** [comment]
Works in Xubuntu 14.04
