### ISSUE TITLE
Delete key on chat list should trigger "delete chat" action

### ISSUE THREAD

**Issue by igorsantos07** [telegramdesktop/tdesktop#1419]
I found it simply **AMAZING** how controllable Telegram is through the keyboard <3

But when goofing around I tried to delete a chat using <kbd>Del</kbd>, but it does not respond. I guess it makes sense to see the "Delete chat" confirmation screen on <kbd>Del</kbd>?

**Comment by Aokromes** [comment]
fixed on 1.9.8.

**Comment by igorsantos07** [comment]
unstale this, please
