### ISSUE TITLE
During kbd navigation, focus on chat list should move to list item

### ISSUE THREAD

**Issue by igorsantos07** [telegramdesktop/tdesktop#1420]
Inside the chat list, the search box is always on focus. Even if you press <kbd>down</kbd> to navigate the list.

This is not an issue if you're just going to open one of the chats, but this makes the user unable to use <kbd>Menu</kbd> to simulate a right click - so he can delete the chat, see the contact profile, etc.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Comment by igorsantos07** [comment]
Whoops. Yeah, it's still valid at 1.9.19 beta.

![image](https://user-images.githubusercontent.com/532299/75459234-d5adf700-595d-11ea-9733-d405799414a2.png)
