### ISSUE TITLE
Option to select font (windows)

### ISSUE THREAD

**Issue by woj-tek** [telegramdesktop/tdesktop#1421]
Under windows (at least 10, but I guess 8 is the same) MS is trying to force it's stupid 'cleartype' or somesuch, which may work for some, but on 24" 1920x1200 it simply looks terrible (yes, I've tried to tune it without success). So in the end I've disable smoothing everywhere, use Tahoma/Verdana almost elusively and it works perfect. However, since some time (dunno, a couple of months) Telegram started to manifest same blurriness. And it's quite annoying (especially on narrow letters) because readability was greatly decrease.
Is it possible to either change the font somehow? (selecting type, increasing it, etc)?

**Comment by auchri** [comment]
Duplicate #90
