### ISSUE TITLE
The time is incorrectly compared on multiple new messages

### ISSUE THREAD

**Issue by DuckThom** [telegramdesktop/tdesktop#1422]
![bug](http://puu.sh/m1zBH/3ca59ef847.jpg)

The order of the messages in the image above should be:
- 8:12 AM
- 8:20 AM
- 8:18 PM

But instead, the AM/PM part is ignored

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by DuckThom** [comment]
I haven't noticed it in the past couple of months. Although, I also don't think it has occurred again that I had unread messages in such a timespan.
