### ISSUE TITLE
Telegram Desktop Portable IS NOT portable

### ISSUE THREAD

**Issue by VitRom** [telegramdesktop/tdesktop#1423]
**BUG** with _portability_. WinXP-SP3-Ru, TD "portable" v0.9.15-stable.
1. extract and run TD claimed "portable", login etc.
2. localize it as by online guide (download .strings, Options, "loadlang" etc.)

_Expected_:
Some way to point to a file right in the program directory or by relative path.
Like textbox to input "locale.strings" or ".\locale.strings" or "data\locale.strings"
_Got_:
Nothing similar
1. restart and make sure new locale works, then logout and close
2. delete or move .strings from step 2, if it's inside the program dir move this dir somewhere
3. run program

_Expected_:
Localized UI
_Got_:
Non-localized, "Custom language" binding lost (because of absolute path)

**Comment by VitRom** [comment]
The same fake portability applies to the Download Dir option.
There is no any way to store downloaded files nearby to app in the same or nested dir.
I.e.to have them always accessible when using TD-portable from a removable storage on a different PCs.

**Comment by telegramdesktop** [comment]
@VitRom You can choose the second option, it is right what you need — temp dir in app folder.

**Comment by VitRom** [comment]
@telegramdesktop thanx, I'll try. While the first part still actual.

But I'm in doubt, what string of these next three (from the "Choose download path" popup dialog)
* Telegram folder in system "Downloads"
* Temp folder, cleared on logout or uninstall
* Custom folder, cleared only manually

I shall read as *temp dir in __app__ folder*?

**Comment by telegramdesktop** [comment]
@VitRom The second. About the language — this feature was introduced for translators testing their phrases before release and only after it started to be used for custom pang packs by users, this was not the case when this feature was implemented.

**Comment by VitRom** [comment]
Well, this way a downloads are in the _**.\tdata\tdld**_ so the 2nd option works. Except that in the rest of desktop world the words "temp folder" means a bit different thing.
Still bad that it will be "cleared on logout" and that a some kind of files, i.e. localization, aren't ordinary "downloads" but are forcibly mixed with them.
Still unclear what will happen after this session closed from another device.

About localization, this .strings file binding, regardless of it's initial meaning, still the one only way to localize TD to an uncompiled language. Unfortunately these .strings files are linked by absolute path.

But why invent bicycle at all?! Why not simply place any *.strings* aside to the app *.exe*?

**Comment by telegramdesktop** [comment]
@VitRom Yes, perhaps it could copy the file to the data folder (which is portable) + remember the absolute path and after each launch try to copy the new version of file from this path to the data folder (if the version by the absolute path exists) and just use the old one, if it does not.

**Comment by VitRom** [comment]
@telegramdesktop Why to copy anything? A kindergarten level of *usability* design will still.
Just replace a fixed hardcoded language list with a dynamic, filled on start:
* hardcoded lang 1
* hardcoded lang 2
* etc.
* lang of in-app-dir .strings 1
* lang of in-app-dir .strings 2
* etc.
* lang of user chosen file located by abs. path
* choose file (to browse FS for another absolute path)
