### ISSUE TITLE
Support for FreeBSD or *BSDs ?

### ISSUE THREAD

**Issue by mzs114** [telegramdesktop/tdesktop#1424]
Will Telegram work on any of the BSDs natively?
If not, any plans to support them?

**Comment by Peter2121** [comment]
+1 for *BSD support

**Comment by agilob** [comment]
bump

**Comment by arclabch** [comment]
+1

**Comment by cosmoduff** [comment]
+1 for BSD

**Comment by brahmann** [comment]
+1 for BSD too, really need it.

**Comment by stek29** [comment]
Please, use github reactions, stop sending '+1' and 'yes please' comments.

**Comment by stek29** [comment]
#136 Duplicate?

**Comment by agilob** [comment]
Why closing issue that has more votes?

**Comment by auchri** [comment]
#136 was created first.

**Comment by agilob** [comment]
This one is more active, has more votes and is upper in google search under telegram freebsd.
