### ISSUE TITLE
Can not revoke Group Invite link completely

### ISSUE THREAD

**Issue by VitRom** [telegramdesktop/tdesktop#1425]
TD-port v0.9.15
1. Create a new Group
2. Open this Group Info and create a new Invite link in the Settings area
3. Click on Revoke invite link, a confirmation pops up saying "Your prev. link will be deact and **we'll generate new**"
4. (A) press OK, the old link cleared and the new link generated (B) press Cancel, the old link still.
Such a behavior named "regenerate", not "revoke".

_Expected_:
No "bonus service". I.e. the old link cleared but new **does not** created and "create invite" returns back.

**Comment by telegramdesktop** [comment]
@VitRom This is a lang-pack issue :( Perhaps it could be renamed, but it could not be fixed as expected — no server-side API for completely dropping the link.

**Comment by VitRom** [comment]
This is a developers staff-pack issue :)
German translation says "widerruffen" that means "withdraw, revoke" too.
So it must be renamed.
@telegramdesktop shall i close this by self or wait for any assignments?

**Comment by matteocontrini** [comment]
Who is responsible for translations? How can we contribute?

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by RememberTheAir** [comment]
@matteocontrini you can contribute on https://translations.telegram.org/

**Comment by sinwe** [comment]
The latest version (5.9.1 (189475) AppStore) is unable to revoke group invite link at all. Whenever old group link is revoked, new link is created but the old one is still active

**Comment by Aokromes** [comment]
this is for telegram desktop (lite on macos) not Telegram macos.

**Comment by sinwe** [comment]
This issue is for all telegram app (ios, iPad OS, MacOS),  I'm not sure if it is problem on server side.

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
