### ISSUE TITLE
Every time I open telegram an sms auth is required

### ISSUE THREAD

**Issue by jordifreek** [telegramdesktop/tdesktop#1426]
Using ubuntu 14.04. The sms auth process is not working well for me and i don't know why. With every program update or pc restart the telegram app ask me for my telephone number in order to get the sign in code. Do this every day is annoying and i don't now if is my problem or a bug.

**Comment by DaFri-Nochiterov** [comment]
Try to re-install TDesktop from [site](https://desktop.telegram.org/). 

Download archive, drop files `Telegram` and `Updater` to any folder, like `~/Stuff/TDesktop/`.
After this open file `Telegram` (type in bash `./Telegram`), log in. You will get shortcut in Unity (if tdesktop version isn't portable).
Now everything should work fine.

**Comment by jordifreek** [comment]
Ok, done. I use the `/opt` directory for this kind of programs, then `/opt/Telegram/Telegram`. You know this directory has root permissions, is this a problem?
