### ISSUE TITLE
Add Download to WebP files

### ISSUE THREAD

**Issue by Sushubh** [telegramdesktop/tdesktop#1427]
Telegram use WebP so I assumed that it should support them for sharing as images. But the image sharing popup does not include WebP in supported image types. I switched to all images while sharing and was able to select WebP. It sends it fine as original but not when compressed option is picked. Compressed version does not go at all and the timer stays on the image. Preview of the original is visible in the window but it is shared as a text message and no file operation is possible. 

If I send WebP as a file... It sends it fine. It appears as image in the chat box and not like files. But user actions are not available on it. It does not open in lightbox. There is no option to download. It appears as a text message which you can forward/delete/reply/etc. 

The attached image show the menu that comes on webp shares. And the unsent webp image when sent with compressed option. 

![telegram](https://cloud.githubusercontent.com/assets/310098/11946096/0a7e8832-a87d-11e5-99f2-20f27081feca.png)

**Comment by DaFri-Nochiterov** [comment]
WebP is used as stickers, which can't be downloaded.

**Comment by Sushubh** [comment]
That's ok. But at least allow the user to send WebP images as files?

**Comment by telegramdesktop** [comment]
@Sushubh Telegram uses .webp files for stickers, so a sent .webp file is displayed and acts like a sticker. I can add a "Save As" button in the context menu or you can send them in .zip

**Comment by Sushubh** [comment]
A save as option would be nice if there are no issues providing such an option. Thanks!

**Comment by diazbastian** [comment]
In version 0.9.18 You can download all webp image on TDesktop (whether or not a sticker).
Is it possible to separate the webp images sent by a user of the packs of stickers?

Cheers

**Comment by telegramdesktop** [comment]
@diazbastian Currently all the .webp images are sent and displayed as stickers, this is the way across all Telegram applications, sorry. The same with .gif animations.

**Comment by diazbastian** [comment]
@telegramdesktop I understand, that's the way to go, however, TDesktop is the only client that allows downloading stickers. From another point of view, this causes some problems with the artists who create packs of stickers and are now easily downloadable and likely to create other (despite being public).
Cheers
![stickers-saveas](https://cloud.githubusercontent.com/assets/5126124/12214782/c83c3aac-b680-11e5-9870-d74ca15c721e.png)

**Comment by Zenexer** [comment]
What if I have a WebP file that I want to send the same way I send PNG file?  Are you saying I have to convert to an inferior format? ;)

**Comment by diazbastian** [comment]
@Zenexer The webp format is not used massively or supported by most existing software. It is also used in specially Telegram (stickers).
I do not see the downside of using another format or send a webp image in compressed file (zip, tar.xz, 7zip, etc)..

**Comment by telegramdesktop** [comment]
@Zenexer and what is the problem with sending it right now? Yes, it displays a bit differently in UI (like sticker), but you still can save the .webp to the file from context menu, I don't see the problem.

**Comment by telegramdesktop** [comment]
I've added the Save button btw.
