### ISSUE TITLE
Message attached with image doesn't let to write several characters like á, é, í, ó, ú

### ISSUE THREAD

**Issue by damaru2** [telegramdesktop/tdesktop#1428]
I don't know what codification is being used but when one type those characters (typical in Spanish) they are not written down. It just happen when one attaches a message with and image.

I am using the last version ( 0.9.15 ) on a Xubuntu 14.04

Moreover there is a very small limit on the size of that message , 100 characters or so. One cannot write a couple of sentences. I think that limit should be increased.

**Comment by Aokromes** [comment]
#1360

**Comment by damaru2** [comment]
It's something like 1360, yes. But in my case those characters work perfectly everywhere but when you attach a message with an image.

**Comment by Aokromes** [comment]
maybe #1418 then?

**Comment by damaru2** [comment]
Exactly. I hadn't realised that with copy/paste the accents were written but they are. It is #1418
