### ISSUE TITLE
Забавный глюк с отображением статуса "онлайн"

### ISSUE THREAD

**Issue by anya-gordeychuk** [telegramdesktop/tdesktop#1429]
У одного друга обычно скрыто отображение онлайна, но почему-то когда он пишет в одной группе (супергруппа, если что), в диалоге вижу, что он онлайн, даже если мы с ним лично не переписываемся. Через несколько секунд "online" пропадает и появляется "last seen recently".
![666](https://cloud.githubusercontent.com/assets/16072445/11965006/4bfe8fb4-a8fa-11e5-982e-40e12e1db3d1.png)

**Comment by auchri** [comment]
Write english please....

**Comment by telegramdesktop** [comment]
@anya-gordeychuk This is intended behavior, when user writes anything in any group we mark him online for a half a minute locally.

**Comment by anya-gordeychuk** [comment]
Thanks!
