### ISSUE TITLE
[Bug] Sending image from menu actually sends it as file, dragging works fine

### ISSUE THREAD

**Issue by netsurfer912** [telegramdesktop/tdesktop#143]
![menu](https://cloud.githubusercontent.com/assets/1337470/4099889/9f77cd8a-3075-11e4-9ad3-9ed9a44d993e.png)
When sending an image from the provided menu, it is not sent like a typical image, but like a file. 
![file](https://cloud.githubusercontent.com/assets/1337470/4099913/b1eb8294-3076-11e4-965c-bcc544336225.png)
My partner has to download the file before being able to view it. 

When the image file is dragged onto the telegram-window however, it is displayed just like a regular image sent from any of the other apps. 
![image](https://cloud.githubusercontent.com/assets/1337470/4099941/87d65bfe-3077-11e4-9441-1cefc63bd292.png)

//yes, I am indeed proud of my cursor.

**Comment by telegramdesktop** [comment]
Use Copy Image in browser in order to send it as a photo (compressed), or uncompressed .png from clipboard.
