### ISSUE TITLE
Landline Number for Desktop app

### ISSUE THREAD

**Issue by RyanCarlisle** [telegramdesktop/tdesktop#1430]
I've been trying to use my landline number for the desktop app for Telegram but every time time it reads incorrect phone number....Kindly direct me on what I should do...

**Comment by telegramdesktop** [comment]
@RyanCarlisle Currently Telegram supports only mobile numbers, as I know, so there is nothing I can do to help you. Anyway, this issue has nothing to do with Telegram Desktop app.

**Comment by RyanCarlisle** [comment]
by the way would I receive notifications on my mobile for the messages that I sent if I use the desktop app with my mobile number....

**Comment by alenguav** [comment]
I was thinking of that you could send voice notifications to fixed telephone numbers for validation in this case.

**Comment by stek29** [comment]
Ask tg on Twitter or via in app support, TDesktop has nothing to do with server side limitations.
