### ISSUE TITLE
Option to check every X hours?

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#1434]
Dear all, 

What do you think of an optional feature for Telegram Desktop to check for new messages every X hours? 

This would give the user the convenience to keep Telegram Desktop running in the background without the constant (potential) distraction of newly incoming messages. 

Merry Christmas,

~ Robert

**Comment by auchri** [comment]
Sorry, but that's not the goal of an *instant* messenger :)

**Comment by orschiro** [comment]
Dear @auchri,

Thanks for your response! What you're saying makes indeed sense. 

For all others who seek for a solution, it's outlined here:

http://askubuntu.com/questions/713156/is-there-software-to-periodically-start-and-close-an-application
