### ISSUE TITLE
Shortcuts: next/prev chat

### ISSUE THREAD

**Issue by vladimir-sol** [telegramdesktop/tdesktop#1435]
Would be nice to be able to switch chats with `CMD+SHIFT+]` or `CMD+SHIFT+[` (standard Mac shortcuts for switching tabs), because I keep trying to do that anyway :)

**Comment by auchri** [comment]
works with <kbd>cmd</kbd> + <kbd>tab</kbd>

**Comment by vladimir-sol** [comment]
Please reopen. It doesn't. Anyways, cmd+tab is reserved for switching **windows**, chats are closer to **tabs** within telegram desktop window. And I've named the standard shortcuts for that above.

**Comment by seadog007** [comment]
I think standard Mac shortcuts for switching tabs is `Ctrl + Tab` and `Ctrl + Shift + Tab`

**Comment by vladimir-sol** [comment]
@auchri if you're closing it because of seadog007 reply, then - he's no idea what he's talking about. Please reopen.
