### ISSUE TITLE
Placeholder of message input box does not disappear when IME starting to compose (OS X)

### ISSUE THREAD

**Issue by dannvix** [telegramdesktop/tdesktop#144]
Environment:
- Telegram v0.5.17
- Mac OS X 10.9.4 English
- IME: [Yahoo! Keykey](https://github.com/yahoo/KeyKey)
- Input language: Traditional Chinese (with _Smart Phonetic_)

The placeholder text of the message input box does not disappear when the IME starting to compose Chinese characters. After the first CJK character composed, the placeholder disappears as expected.

By the way, I found the _build-in Japanese IME of OS X_ also encounters the same issue when composing in Telegram.

![telegram-placeholder](https://cloud.githubusercontent.com/assets/80781/4101841/dbc386fc-3107-11e4-8ed5-3b85dc615351.png)

**Comment by tangyi** [comment]
same here. 

version 0.9.43

**Comment by jt-wang** [comment]
Same here.

**Comment by stek29** [comment]
Why is it closed?

**Comment by jt-wang** [comment]
@auchri We wonder why it is closed without any explanation...?

**Comment by auchri** [comment]
@jt-wang because.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by lixorte** [comment]
> this bug is still valid on 1.9.8?

Telegram 1.9.10 beta on macOS 10.15.1 is fine when using build-in Japanese.
