### ISSUE TITLE
Empty message in reply with sticker

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1440]
![image](https://cloud.githubusercontent.com/assets/10401817/12011475/f769404a-acf8-11e5-9d51-12103157e88c.png)

If user doesn't have name (just space), after reply to his message with sticker - message in reply are empty.

**Comment by stek29** [comment]
More screenshots:
![2015-12-27 21 19 19](https://cloud.githubusercontent.com/assets/11808223/12011493/7242322c-ace0-11e5-8be6-91536019c5d3.png)
But should be:
![photo_2015-12-27_21-24-14](https://cloud.githubusercontent.com/assets/11808223/12011486/38bd52ac-ace0-11e5-9d1f-f7e0a8f171da.jpg)

**Comment by telegramdesktop** [comment]
"If user doesn't have name (just space), ... " his death should be slow and painfull!

**Comment by vozzurg** [comment]
+1
![screenshot_765](https://cloud.githubusercontent.com/assets/14953243/12011530/f09792ae-acf2-11e5-84d6-77868d97a902.png)

**Comment by stek29** [comment]
IDK when it was fixed, But I can't reproduce it now.
@auchri maybe it should be closed?
![screen shot 2016-03-27 at 01 48 14](https://cloud.githubusercontent.com/assets/11808223/14062813/6e0cfe30-f3c6-11e5-8eb3-1a1ba409e40c.png)

**Comment by luckydonald** [comment]
@auchri It is introduced again it seems:
![image](https://cloud.githubusercontent.com/assets/2737108/21956517/21ba3ee0-da83-11e6-96fa-3f9c47b9dd21.png)
![image](https://cloud.githubusercontent.com/assets/2737108/21956519/2df700bc-da83-11e6-97c4-4e61bbd004b8.png)
(Tested OS X, V1.0)

**Comment by john-preston** [comment]
@luckydonald This is intended. If the window is so small there is no place for the reply information it is displayed that way.

**Comment by luckydonald** [comment]
But `...` isn't really helpful.
