### ISSUE TITLE
No message notification sound in Telegram Desktop App on OSX

### ISSUE THREAD

**Issue by stoptherock1** [telegramdesktop/tdesktop#1441]
When a message arrives and the app is working in the background (app's window is not active, there is no sound notification happens, despite the fact, that notifications are enabled.
![screen shot 2015-12-28 at 00 19 48](https://cloud.githubusercontent.com/assets/6492429/12012527/85b069a0-acf9-11e5-8afd-a2a46c931bd8.png)
![screen shot 2015-12-28 at 00 19 45](https://cloud.githubusercontent.com/assets/6492429/12012528/85b3d81a-acf9-11e5-8c28-b9fa11d9f684.png)

**Comment by auchri** [comment]
That's not Telegram Desktop.

**Comment by stoptherock1** [comment]
Well, I have got this app from the App Store: 
https://itunes.apple.com/us/app/telegram/id747648890?mt=12

What is the difference between my version and the one from this page: https://desktop.telegram.org/   ?

**Comment by telegramdesktop** [comment]
@stoptherock1 There are two apps in the App Store: https://telegram.org/faq#q-why-do-you-have-two-apps-in-the-mac-app-store

**Comment by stoptherock1** [comment]
If there are 2 official clients, which is quite misleading, why have you closed the thread?

**Comment by telegramdesktop** [comment]
@stoptherock1 Because this repository, code and issues are only about one of them, named «Telegram Desktop».

**Comment by stoptherock1** [comment]
Oh, ok. Thank you!
