### ISSUE TITLE
Add in the context menu the entry Download/ Stop Download

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1442]
This is very useful in the following cases:
- For our own files (chat view - shared media)
- For audio files (shared media)

It can also be very useful to add all types of files in compact mode (more space for file name and number of views).
![telegram](https://cloud.githubusercontent.com/assets/5126124/12029531/fbcac55e-adcb-11e5-9114-51ed2781c8d9.png)

**Comment by Aokromes** [comment]
this is implemented 1.9.8 no?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
