### ISSUE TITLE
Add search box to other sections of shared media

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1443]
In the latest update for Android and iOS client, search boxes for all sections in shared media were added. To TDesktop it would also be convenient to add a search box to files, videos, music, etc.

Thank you

**Comment by Aokromes** [comment]
+1

**Comment by telegramdesktop** [comment]
@Aokromes It will be added to the files section in the next release, but not to the others. I'm not sure I understand what will you search for in photos / videos. It could be added to audio files, but some day further.

**Comment by Aokromes** [comment]
Imho it can be added to photos or videos searching for file names  or even exif data.

**Comment by telegramdesktop** [comment]
@Aokromes This is a server-side search, and currently server does not index exif data for photos and does not even save filenames of the photos and videos that are sent. So there is no sense in adding this search field to Telegram Desktop — nothing will be found. Only one thing is indexed for photos and videos on server — captions, but they appear so rarely that this search field will more confuse users than help them.

**Comment by diazbastian** [comment]
@telegramdesktop Hello, what you mentioned is that TDesktop only recognized as *.mov video files? I mean they are the only ones to appear in the video section on shared media. Something similar happens with the image sent as files. Not appear in the images section.
For me it is confusing to happen this.

Cheers

**Comment by telegramdesktop** [comment]
@diazbastian There is a "files" section, where all the files go — uncompressed images (which is equal to images sent as files), video files sent from TDesktop, and all other files. + there is a media type "photo" which has all compressed sent images and do not have filenames etc + there is a media type "video" which has all videos sent from mobile apps (TDesktop currently does not send media type "video" at all — you can send video files, but they will go to "files" section).

There will be search in "files" shared media section and there is almost no sense in search for "photo" and "video" media types.

**Comment by diazbastian** [comment]
>There will be search in "files" shared media section and there is almost no sense in search for "photo" and "video" media types.

@telegramdesktop Now I understand a little more the logic of file categorization in Tdesktop (thanks!).

Yes, it makes no sense that there is a search box in the photos and videos section. So why not treat them in a single section, like mobile devices (Multimedia)?.
This would be more familiar to users.

Cheers

**Comment by diazbastian** [comment]
@auchri 
Hi. Thank you very much for the great last update.
I do not understand much labeling. Are you totally closed the report or consider adding a search box for music files?

The same goes for #1449 and sort of the multimedia list.

Cheers

**Comment by auchri** [comment]
> adding a search box for music files?

not supported by the api

> This is a server-side search, and currently server does not index exif data for photos and does not even save filenames of the photos and videos that are sent.

**Comment by telegramdesktop** [comment]
@diazbastian well, search in the audio files is supported (by the filename, performer and song title in ID3 tags), so perhaps it will be added in the future.

**Comment by haevalencia** [comment]
Cool, it is also true that the order of audios and voice messages is strange and inverse to what you see in other types of content. It would be nice to be able to unify all with a similar view.

**Comment by haevalencia** [comment]
Ping!... auto-closer is bad xD

**Comment by john-preston** [comment]
It was added for the audio files in the latest alpha versions.

**Comment by haevalencia** [comment]
Why does the search work differently from mobile versions?

In Telegram Desktop I must write a complete word for search results to appear, but in Android, results start to appear with a few letters. On the other hand, now that the API allows it, it would be cool that in the sections of "photos", "videos" and "voice messages" you could search by date directly, since they do not allow searches by terms.
