### ISSUE TITLE
[Feature Request] Storing Hostname and Port of Proxy server (Socks/HTTP)

### ISSUE THREAD

**Issue by themegabyte** [telegramdesktop/tdesktop#1444]
I switch all the time (between proxy and direct), and this is a must have feature.
I know Telegram Desktop has an automatic system that detects direct or HTTP (routed through system proxy) mode but my proxy drops connection too often,and breaks the conversation....

The feature isn't THAT conversation breaking but it is a must have since re-entering the proxy every time we switch is time consuming.

**Comment by auchri** [comment]
Duplicate #955
