### ISSUE TITLE
Repeating Emoji replace by

### ISSUE THREAD

**Issue by andersonluciano** [telegramdesktop/tdesktop#1446]
Repeating several times one Emoji, it replaced by Android Emoji
Follows a print bug:

![photo_2015-12-30_14-49-00](https://cloud.githubusercontent.com/assets/3874219/12053878/6ea78e34-af04-11e5-84af-dc3adce612f1.jpg)

**Comment by telegramdesktop** [comment]
This repository is about Telegram Desktop app, not Telegram for Android.

**Comment by andersonluciano** [comment]
Sorry @telegramdesktop you know where I inform this bug? I didn't found..

**Comment by auchri** [comment]
@andersonluciano That's not a bug. If more emojis would be replaced with the ones from apple, the app would crash.

**Comment by andersonluciano** [comment]
I understand @auchri 

Thanks
