### ISSUE TITLE
Make Telegram follow native windowing theme

### ISSUE THREAD

**Issue by Alkaris** [telegramdesktop/tdesktop#1452]
This is probably something for enhancement than an issue.

I would like to see Telegram particularly on Linux to follow and use the native windowing theme when you want to share images or files with someone, it's really ugly seeing it not following the native windowing theme on Linux when opening the window for choosing what to send.

![shutter_2016-01-01-02-16__18_46_10_pm](https://cloud.githubusercontent.com/assets/6682988/12073716/737f9d50-b181-11e5-9c2a-92378800f186.png)

![shutter_2016-01-01-02-16__18_47_11_pm](https://cloud.githubusercontent.com/assets/6682988/12073726/e5ac6110-b181-11e5-912f-654df0e2f763.png)

It should respect and use the current windowing theme by the system instead of selecting its own which isn't included in the system or enabled by default.

**Comment by DaFri-Nochiterov** [comment]
Duplicate #987

**Comment by ManuelSchneid3r** [comment]
I am the author of #987. Note that #987 is *not* about the filechooser. #987 is about the *application style* in general. Check #982 for native filechooser.

**Comment by john-preston** [comment]
In the latest 0.9.57 version gtk file chooser should be used if it is available. Please check.
