### ISSUE TITLE
Continous crashing after update a hour ago (inline gifs?)

### ISSUE THREAD

**Issue by mirhl** [telegramdesktop/tdesktop#1455]
[Dumps](https://drive.google.com/file/d/0B5Fd8kTRtzaBVDVPMlR3RmdseW8/view)

**Comment by telegramdesktop** [comment]
@mirhl Yes, fixing currently, sorry.

**Comment by telegramdesktop** [comment]
@mirhl Please try out the fixed 0.9.17 version.

**Comment by mirhl** [comment]
Fixed. Thank you.
