### ISSUE TITLE
New release crashes after receiving a reply to an inline bot message

### ISSUE THREAD

**Issue by pietroalbini** [telegramdesktop/tdesktop#1456]
If someone has sent to you (either in a private chat or a group) a reply to an inline bot message, Telegram Desktop crashes over and over, either when you open it or when you open that specific chat. If then you want to use the client, you need to delete that message from another client. It also crashes when trying to send a reply to an inline bot message.

Steps to reproduce:

* Send an inline bot message to someone, or to a group (for example `@bold test`)
* From another client, reply to that message
* Open Telegram Desktop and it will crash
* Remove the message from another client to "fix" the issue

**Comment by telegramdesktop** [comment]
@pietroalbini Yes, fixing currently, sorry.

**Comment by telegramdesktop** [comment]
@pietroalbini Please try out the fixed 0.9.17 version.

**Comment by pietroalbini** [comment]
Ok, that's fixed! Thanks :-)
