### ISSUE TITLE
Group messages from the same sender 

### ISSUE THREAD

**Issue by anpep** [telegramdesktop/tdesktop#1457]
In Webogram, messages from the same sender get grouped. It would be nice if in Telegram Desktop they got grouped too, as it would make "flooding" less noticeable.

![2016-01-04_15-30-08](https://cloud.githubusercontent.com/assets/4117838/12091555/18b78dce-b2f8-11e5-93dc-f83ed85b91c7.png)

**Comment by auchri** [comment]
Duplicate  #429 , thx
