### ISSUE TITLE
0.9.16 crashes when trying to view a full-size picture inside a reply

### ISSUE THREAD

**Issue by anpep** [telegramdesktop/tdesktop#1458]
![image](https://cloud.githubusercontent.com/assets/4117838/12092921/58fb3a5e-b300-11e5-8fdd-9fa2428dc3dd.png)

When clicking the attachment of a replied message, the new release crashes immediately.

**Comment by telegramdesktop** [comment]
@anpep Please try out the fixed 0.9.17 version.

**Comment by anpep** [comment]
It's fine now, thanks!

**Comment by anpep** [comment]
It's fine now, thanks!
