### ISSUE TITLE
Inline bot text shows encoded HTML entities

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#1459]
![image](https://cloud.githubusercontent.com/assets/4117838/12094812/1a4cb64c-b30b-11e5-8991-cb1935fff91d.png)

Instead of `!`, the inline bot text placeholder shows HTML entities for special characters.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
