### ISSUE TITLE
[Question] Is it possible to extract numbers of "seen"

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1461]
I have two questions. I want to know is it possible to:

1- Extract the numbers of members in a channel

2- Extract the numbers of "seen" of a link shared in telegram

I want to show the number of members in my sidebar and show the numbers of seen in sharing buttons below an article. Same as this image:

![untitled](https://cloud.githubusercontent.com/assets/15929497/12096866/af5484d8-b318-11e5-8734-bc299117bb9e.png)

If there is not API for these, can telegram adds them? or is there any other section that I can ask about API stuff?

Thanks a lot

**Comment by auchri** [comment]
I think it's currently not possible to do that. You can ask at https://twitter.com/telegram or with the "Ask a question" - feature in one of the official clients for such an api.

**Comment by amiremami** [comment]
I really appreciate your help auchri, thanks man :)
