### ISSUE TITLE
Frames of Transparent Gif overlayed on eachother

### ISSUE THREAD

**Issue by emadgh** [telegramdesktop/tdesktop#1462]
Transparent gifs go's wrong...
![image](https://cloud.githubusercontent.com/assets/411159/12099162/f35bd2ee-b33b-11e5-94b9-00aa392e4b0d.png)

original gif
![bla-bla-emoticon](https://cloud.githubusercontent.com/assets/411159/12099173/fb51e98e-b33b-11e5-97c4-922bd91d0d94.gif)

**Comment by telegramdesktop** [comment]
This one will be fixed in the next version, thanks.

**Comment by telegramdesktop** [comment]
Please check, it should be fixed in the last 0.9.18 stable version.
