### ISSUE TITLE
OSX replace function not working

### ISSUE THREAD

**Issue by c143** [telegramdesktop/tdesktop#1463]
Hey
In OSX there is an option to replace specific words with others. Works in other text apps, like TextEdit, but not in Telegram. Especially for a Chat-App thats really important.

Example: http://osxdaily.com/2012/03/12/convert-text-to-emoji-mac/

**Comment by telegramdesktop** [comment]
I'm sorry, but this can't be done in Telegram Desktop right now. TDesktop is based on Qt library and uses Qt input fields, which are custom controls, not provided by the OS, so this native input-field features do not work there :(
