### ISSUE TITLE
Show results of inline bots on top of message box

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1465]
![image](https://cloud.githubusercontent.com/assets/10401817/12101334/46e8ca1c-b35e-11e5-8c74-3bcc83459ec0.png)
This is very uncomfortable, when 'Results' window hide text.

And another  problem:
Long texts with @bold are cuted.

```
**Text:**
1. Text
2 - 7.[here the end] Text
8. Text [it will be removed]
9. Text
```

**Comment by vdrhtc** [comment]
Yes, it would be really nice if this issue gets fixed, more-than-single-line texts are useful

![2017-01-09 18-59-44](https://cloud.githubusercontent.com/assets/3819012/21772817/33a2545c-d6a6-11e6-9728-6c68a17efa84.png)

**Comment by auchri** [comment]
Should be fixed by 143181095f4d8a7b4c55e3e7f341abde850132ab

**Comment by john-preston** [comment]
@vdrhtc Please check out the latest alpha 0.10.26

**Comment by vdrhtc** [comment]
@john-preston Oh, thanks! Should I build it myself?

**Comment by john-preston** [comment]
@vdrhtc You can download it from the bottom of https://desktop.telegram.org/#alpha-version page.

**Comment by vdrhtc** [comment]
@john-preston Great, now it works, thanks!

![2017-01-10 09-56-55](https://cloud.githubusercontent.com/assets/3819012/21796684/c199bcf0-d723-11e6-97e5-828ab35f9fc8.png)

However, the inline results window size seems to be too large, but I believe there's already an issue #2793 for that
