### ISSUE TITLE
Upload very slow / not uploading

### ISSUE THREAD

**Issue by jmigual** [telegramdesktop/tdesktop#1469]
Hi when I'm uploading a file or an image the upload is very slow and sometimes it never ends. When I use the web version it uploads very fast so it's not a connection problem. Also if I run telegram as Administrator this problem solves.
My specs are these:
OS: Windows 10 x64
CPU: Intel(R) Xeon(R) X5650 @ 2.67GHz
RAM: 12GB
Telegram version: 0.9.18

**Comment by swito74** [comment]
I'm having the same problem. Web telegram is ok, but sending a picture compressed or uncompressed is too slow.

OS: Windows 10 x64
CPU: AMD Phenom II X4 965 @ 3.4 GHz
RAM: 8GB
Telegram version: 0.9.18

**Comment by namikiri** [comment]
I have the same issue. Running as Administrator **does not solve** the problem. 
Files, images and voice notes don't upload at all. Sometimes I have just a small rotating dot, sometimes I have a donut with an X in center of it, but files don't send.
After three or more restarts it is possible to make Telegram send images temporarily, but it lasts for unknown time. 
Web version is also affected: when I try to send an image, it begins to reconnect several times.

OS: Windows 10 x64
CPU: Intel Core i3-2310M
RAM: 4GB
Network Adapter: Qualcomm Atheros AR8152 (I have tried to remove W10 drivers and install Atheros's ones, no effect)
Telegram version: 0.9.18

**Comment by namikiri** [comment]
If you're using Atheros AR8152 NIC as It may be a NIC driver fault: http://superuser.com/questions/1035355/upload-hangs-on-windows-10-and-atheros-ar8152-nic

**Comment by Fell** [comment]
Same Issue here.

OS: Windows 10 x64
CPU: Intel Core i5-4690K
RAM: 8GB
Network Adapter: Intel I218-V Gigabit LAN controller 
Telegram version: 0.9.28

**Comment by mbnoimi** [comment]
Most of time Uploading/Downloading for large files through Telegram desktop sucks while Android version works fine

- Linux Mint x64 xfce
- Telegram 0.9.42

**Comment by AxissXs** [comment]
same issue here with Telegram v 0.9.49 on win8 x64 :disappointed:

**Comment by Aokromes** [comment]
guys, try updating your network drivers, like namikiri pointed there are some network cards with bugged drivers.

**Comment by fardad1** [comment]
I have same issue by mbp. all my drivers are updated.

**Comment by namikiri** [comment]
@fardad1 did you try to _roll back_ the drivers?

**Comment by Aokromes** [comment]
@fardad1 what's your network interface? if it's killer network you may need to find real drivers instead killer's ones.
