### ISSUE TITLE
Can't drag Gif files like photos and ...

### ISSUE THREAD

**Issue by emadgh** [telegramdesktop/tdesktop#1471]
We could drag GIF files like other files directly without selecting them like photos,files and stickers. 
It start selecting messages.

**Comment by auchri** [comment]
works for me

**Comment by DaFri-Nochiterov** [comment]
+1

![ezgif-4161188374](https://cloud.githubusercontent.com/assets/10401817/12187629/a7ebab92-b5d7-11e5-9619-6ff40f094183.gif)

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
