### ISSUE TITLE
Return to list on dragging messages when tg is small

### ISSUE THREAD

**Issue by emadgh** [telegramdesktop/tdesktop#1472]
When we're using telegram in small width, it would be good to return to _chat list_ on dragging messages...

Thanks in advanced.

![image](https://cloud.githubusercontent.com/assets/411159/12118386/6190f4c0-b3db-11e5-8907-56fd9198e3cb.png)

**Comment by Aokromes** [comment]
why no simply click on fw button?

**Comment by Aokromes** [comment]
poke.
