### ISSUE TITLE
URI ignoring in markdown

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1474]
Example: `"[▶️ Open in App](" + obj.uri + ")"`
URI same as in Spotify: `spotify:track:2GTFUrIDg5Xq17sU9dtPcx`
Why this is ignored? It's very bad for my bot (may be and not for my).
May be ask user "Did you want to open app Spotify?"?

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov This has nothing to do with Telegram Desktop, it is a server side issue, sorry.

**Comment by DaFri-Nochiterov** [comment]
Oh, Okay :C
