### ISSUE TITLE
Bot API: list chat rooms

### ISSUE THREAD

**Issue by aurium** [telegramdesktop/tdesktop#1475]
Is there a way to know where my bot is, with the current bot API?

I Believe `getMe` should return a list of chats where the bot is listening https://core.telegram.org/bots/api#getme

**Comment by auchri** [comment]
I don't know, sorry. But this repo is only about Telegram Desktop.

**Comment by aurium** [comment]
While there is no official and pubic channel to talk about the Bot API, i believe we could do it at telegramdesktop, as it looks more a telegram.org project than a personal space. :-)

Well, can you point a reliable place to do this question, where the Telegram's devs will read and answer?

**Comment by auchri** [comment]
https://twitter.com/telegram or the "Ask a question" feature in one of the official apps.

**Comment by DaFri-Nochiterov** [comment]
@auchri ..or [`@BotSupport`](http://telegram.me/botsupport)?
No matter how much I did not ask in Twitter or Support - I've not got answers.
Only Bot Support answer me fast..
     ... in a typical pattern "maybe it will be" (I asked about new features for bot api)

**Comment by dariuosh56** [comment]
salam

**Comment by aurium** [comment]
Thanks @DaFri-Nochiterov! :thumbsup:
