### ISSUE TITLE
Change default sound output device automatically

### ISSUE THREAD

**Issue by carp3** [telegramdesktop/tdesktop#1477]
Hi, I have a Bluetooth headphone. When I turn it on, windows recognize it as a new sound output device and automatically make it default. Most programs switch to new output device instantly (like Winamp, VLC, etc...) but telegram don't. I have to restart telegram manually.

 Here is a picture of the situation:

![image](https://cloud.githubusercontent.com/assets/1427433/12142790/255ed91c-b490-11e5-846f-9c96e6a1d449.png)

I think telegram should switch to the new default output device automatically. 

Telegram 0.9.17/Windows 8.1

Thank you.

**Comment by auchri** [comment]
duplicate #776
