### ISSUE TITLE
disable Gif autoplay 

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#1478]
Kinda anoying to not be able to pause them

(not like #687, I like the preview, just want to stop the animation)

**Comment by AndydeCleyre** [comment]
So two separate issues are in here, disabling gif autoplay and gif pausing (regression). The latter is most important to me.

**Comment by telegramdesktop** [comment]
@Geobert You can disable gif auto play in automatic media download settings box in Settings>Chat options

**Comment by AndydeCleyre** [comment]
@telegramdesktop Thank you! 

Turning off autoplay for gifs also enables pausing gifs. It's still a bug/regression that autoplayed gifs can't be paused, but this is good enough for my personal use.

**Comment by lindhe** [comment]
Clarifications for others that couldn't find the option: click **Automatic media download settings** under Settings > Chat options.

**Comment by u007** [comment]
no longer there
