### ISSUE TITLE
Go back and forward voice message

### ISSUE THREAD

**Issue by CristianOspina** [telegramdesktop/tdesktop#1480]
In other clients I can go to any position of the voice message. On the client desktop (at least for Windows), you can only stop or play it. If I want to hear a specific part, I have to wait for the whole message is played, so to start it again.

It would be nice to have that feature in this client.

**Comment by telegramdesktop** [comment]
@CristianOspina Yes, this should be added in some version, but I'm not sure how soon..

**Comment by CarlosLopezES** [comment]
I agree, would be really useful on long voice messages
