### ISSUE TITLE
No combined inline results from bot

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1481]
If bot return combined inline results (is - photos, gifs, video) you saw nothing and when you click "< Emoji", you get this amazing panel with icons: 
![image](https://cloud.githubusercontent.com/assets/10401817/12181147/ba293d56-b5aa-11e5-87bc-89d256f68770.png)
... and no chance to come back :smiling_imp:

**Comment by DaFri-Nochiterov** [comment]
On Android you get some results, but after this results you can only get 'indicator of download bug'

**Comment by auchri** [comment]
do you have a example bot to reproduce this issue?

**Comment by DaFri-Nochiterov** [comment]
Yes, it's my bot: `@tumblrtagbot`

**Comment by DaFri-Nochiterov** [comment]
I got some details: this happens when bot doesn't return size of photo/gif
(I not sure, but when my bot started to send `gif_width` and `gif_height` - I got results)

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov It _should_ return dimensions for GIFs and photos. Needs to be enforced on the server side I guess..

**Comment by DaFri-Nochiterov** [comment]
@telegramdesktop in documentation written, that's are optional
```
|   param    |   type  |       description           |
|:----------:|:-------:|:---------------------------:|
| gif_width  | Integer | Optional. Width of the GIF  |
| gif_height | Integer | Optional. Height of the GIF |
```

Or you not about this?

**Comment by auchri** [comment]
@DaFri-Nochiterov does it still hapen?

**Comment by DaFri-Nochiterov** [comment]
I can't check now, sorry. You can close issue for now. If someday I get my PC working, I'll test and say you results :)
