### ISSUE TITLE
If picture or gif is so small, inline-bot username goes beyond messages border

### ISSUE THREAD

**Issue by vozzurg** [telegramdesktop/tdesktop#1482]
bug on the picture
![screenshot_779](https://cloud.githubusercontent.com/assets/14953243/12196500/cc132aba-b620-11e5-8817-d6c83869644c.png)

sorry for my bad english ¯\_(ツ)_/¯

**Comment by telegramdesktop** [comment]
Should be fixed in latest dev version.
