### ISSUE TITLE
Add support to stop and resume GIF animations

### ISSUE THREAD

**Issue by LDVSOFT** [telegramdesktop/tdesktop#1485]
It would be great to add way to start and stop gifs animations. Right now, playing all gifs that are visible takes too much CPU and user cannot stop them from being played rather than close chat window.

For example, it can be done like this: the whole GIF is clickable; when gif is not playing, display first frame with transparent "play" sign.

**Comment by telegramdesktop** [comment]
@LDVSOFT You can turn off auto play in settings in automatic media download box, then they'll behave the way you described.

**Comment by LDVSOFT** [comment]
@telegramdesktop oh wow! That was very well hidden) Maybe this option should be moved out of automatic download?

**Comment by Aokromes** [comment]
@telegramdesktop thx! just found i can disable images previews now :)
