### ISSUE TITLE
Ability to create multiple chat-rooms in a group

### ISSUE THREAD

**Issue by Kolahzary** [telegramdesktop/tdesktop#1488]
Hello everyone,
I feel I'm not in correct place to send my suggestion about new features of telegram, sorry about that ( I found nowhere else to send this suggestion ).
Anyway, we have a group of classmates in telegram( at least 100 members! ), but not all of members want to see every message sent in group.
for example ==>
* we speak about *Discrete mathematics course* 
    * there are some members that doesn't have this course. 
* then someone speaks about *Holidays*( e.g. who wants to come with me to Abidar mountain? ) 
    * not all of members are interested in this kind of messages...
* and also when someone wants to speak about something else
    * he must wait until others end their irrelevant conversation then starts his topic.

So, we can create multiple groups to solve this problem, but I think **it's better if administrator would be able to create multiple rooms in a group**, e.g. in our scenario we have a room about *Holidays* and another room about *Discrete mathematics course* and then no one bothers other one...
Sorry for my weak English :eyes:

**Comment by auchri** [comment]
Sorry, but that's not supported by the api.

**Comment by punkrock** [comment]
Does that mean, it will never be possible to have a public chat with different rooms? I really miss this.

**Comment by Kolahzary** [comment]
@punkrock 
No, public room is necessary, but a user sends his message to public room if he/she wants everyone to know about his/her message.
Administrator of group will warn the user if message is not relative to current room.

**Comment by DaFri-Nochiterov** [comment]
Just look at [![image](https://cloud.githubusercontent.com/assets/10401817/13808044/65cef6dc-eb8e-11e5-9595-1c958b49e6d9.png) @PublicTestGroup](https://telegram.me/publictestgroup). All users chat with different themes, in different languages. If themes can be separated as rooms, it'll be cool
