### ISSUE TITLE
Can't select the compiled Qt-5.5.1 on QT creator

### ISSUE THREAD

**Issue by fotanus** [telegramdesktop/tdesktop#1489]
Hi, 

First of all, thanks for the wonderful software you guys developed. I have been actively using and migrating everything I can to it. It is beautiful, fast and works quite well.

That said, I'm having problems compiling the code on Ubuntu with [the instructions provided](https://github.com/fotanus/tdesktop/blob/master/QTCREATOR.md). There is a yellow icon next to my compiled version and you can read "No qmlscene installed". What am I missing? I can't select this version on the Kits tab. Following is a screenshot from the dialog:

![image](http://i.imgur.com/gFZh1MV.png)

I understand that right now improving the build process is not the priority of the project. However, having a simplified building process will increase the number of contributors, so it might actually be a good idea. My suggestion is trying adding a vagrant or docker virtual machine. The only drawback I can think of is that I don't know how well it works with graphical applications.

**Comment by araishikeiwai** [comment]
I too tried to build it myself to try to implement the emoji shortcut (using :[emojiname]: just like web telegram) but I had problem when buliding the `Telegram.pro`

i followed the instructions carefully and found a problem when 'patching' Qt5.5.1 (I forgot what the problem was because I deleted my `tdesktop` folder already :sweat_smile:

**Comment by fotanus** [comment]
@araishikeiwai have you implemented it?

**Comment by araishikeiwai** [comment]
no since i couldn't build it in the first place. but i was planning to do a similar approach to #454
