### ISSUE TITLE
Forwarded messages displayed strange

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1498]
![image](https://cloud.githubusercontent.com/assets/10401817/12223610/7023d8e8-b806-11e5-82ad-3151650ed813.png)

I forward message, but It displayed like message from other people (without profile picture)

It's new feature?

TDesktop version: 0.9.19

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov Perhaps you forwarded it to yourself? All messages to yourself are displayed as incoming, not outgoing.

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov I see now, a 0.9.19 bug. Thanks for your report.
