### ISSUE TITLE
Telegram forgets all setting every few restarts

### ISSUE THREAD

**Issue by lzap** [telegramdesktop/tdesktop#1499]
Using X with i3 on Fedora 64bits.

Every second or third restart, Telegram starts over asking me for PIN via SMS.

I am ready to help with debugging, just tell me where to look for. Thanks.

**Comment by telegramdesktop** [comment]
@lzap Enable debuglogs in settings by typing "debugmode" and agreeing in the confirmation box, then restart your app until it loggs you out and look at the logs. BTW are you using the version from https://desktop.telegram.org?

**Comment by lzap** [comment]
Enabled debugs, re-registered. I noticed that I created symlink in `~/bin/` pointing to `/opt/telegram/Telegram`, but apparently there was another binary installed in `~/TelegramDesktop`. I was launching via the symlink all the time. Let's see if it forgets settings once again.

**Comment by lzap** [comment]
And yes, was using that version. Currently 0.9.18 but apparently there is a new one on the site, it still shows me .18 as the latest.

**Comment by lzap** [comment]
After some testing, I confirm. It was the symlink perhaps.
