### ISSUE TITLE
[Request] Support for Icon Tray on Linux

### ISSUE THREAD

**Issue by ItachiSan** [telegramdesktop/tdesktop#150]
As in title.
Actually, I'm on GNOME 3 (ArchLinux) with the app but I can also test on Ubuntu 12.04, if necessary.
I think it's still missing as I saw no setting for tray icon in the app.

**Comment by edubxb** [comment]
+1

I use GNOME 3

**Comment by telegramdesktop** [comment]
Tray icon using libappindicator with fallback to gtk_status_icon, if libappindicator is not installed, will be added in 0.7.7. I don't know actually, will it work on your system.

**Comment by kvaster** [comment]
Indicator does not work on kde (gentoo system). It was working on 0.7.7, but it stopped working on 0.7.8.

**Comment by rafaelmr2** [comment]
@telegramdesktop, it works in my Fedora 21 installing libappindicator, thanks.

**Comment by rafaelmr2** [comment]
With Gnome Shell.

**Comment by uvatbc** [comment]
Works well in Ubuntu 14.04, 14.10.
With the new Plasma 5 shell in 15.04, tray icon is gone.
I think its some new standard or library required by Plasma 5 :(

**Comment by roberth1990** [comment]
http://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/

**Comment by msevilla00** [comment]
Icon tray disappeared in the last update (0.8.13 stable) in Linux Mint 17 (based on trusty) with Cinnamon desktop environment   :-/

**Comment by pdf** [comment]
Related issues: #702 #492 #679 #516

**Comment by msevilla00** [comment]
Icon tray appeared again after restarted program following these commands:
```
$ killall Telegram
$ ./Telegram --%u
```
I do not know the reason but it worked. :-)

**Comment by sl1pkn07** [comment]
@msevilla00 not in KF5/plasma-next

**Comment by msevilla00** [comment]
@sl1pkn07 sounds like you have have unresolved dependencies in Plasma 5 ¿?
It reminds me the problem Telegram Desktop has in Ubuntu Mate. Have a look to this issue: #638

**Comment by sl1pkn07** [comment]
Nope. Telegrama works. But not show the systray icon un the panel

**Comment by pdf** [comment]
@msevilla00 the main related issue for KF5 is #702

**Comment by auchri** [comment]
The referenced issue was fixed, so I close this one too

**Comment by ComBin** [comment]
No tray icon on "Mint 18.1".
