### ISSUE TITLE
Pressing Esc on image lightbox shouldn't close chat

### ISSUE THREAD

**Issue by ralesk** [telegramdesktop/tdesktop#1500]
As a regression of #54, I noticed recently that pressing Esc on the lightbox will also cascade the Esc-press to the chat and I will be returned to the chat list.

At least this seems to be true on Windows.
On Linux (XFCE at the moment), it seems that the main window loses focus after I close the lightbox (which is probably why the chat doesn't close there)

**Comment by ralesk** [comment]
I feel this might be related to #1439, or at least probably solvable together with that one

**Comment by telegramdesktop** [comment]
This happens to me only if you long-hold Esc key (like when multiple letters are written in an input field when you hold the key), when you just press Esc key it only closes the photo viewer, not the chat (in Windows and OS X). Perhaps you have very small interval between keypress-es are fired?

**Comment by ralesk** [comment]
I pretty much never get double keypresses otherwise, so I don't think it's that.  It doesn't come up always, but I did notice it a couple times recently and it felt very strange — I'll try to see if (and when) it comes up again.

**Comment by ralesk** [comment]
Apparently xfwm4 is being dumb about something.  Depending on its mood, it either loses focus from the main window after lightbox, or pressing Esc in it also escapes the chat.  Kwin doesn't seem to suffer from this.

I guess out of all this, the double esc is the only one that can be theoretically protected against, but not sure...
