### ISSUE TITLE
[Bug Report] Markdown: Bold text in Persian

### ISSUE THREAD

**Issue by fadavi** [telegramdesktop/tdesktop#1506]
Hello.
It seem's Telegram Desktop (Linux) has a bug in markdown support.
So I tried this markdown via [@bold](https://telegram.me/bold):
```
@bold
Normal Text
متن عادی

*Bold*
*ضخیم*

_Italic_
_ضخیم_

`Monospace`
`گام ثابت`

[Link](example.com)
[پیوند](example.com)
```

Result:
![Result](http://i.imgur.com/CGR41yw.png)

As you can see, **bold text** for Persian characters does not work. Thanks.

**Comment by telegramdesktop** [comment]
@fadavi Seems that the font (Open Sans Semibold) does not have them :(

**Comment by auchri** [comment]
-> #90
