### ISSUE TITLE
Annoying ads

### ISSUE THREAD

**Issue by mehdipourfar** [telegramdesktop/tdesktop#1507]
Everyday, I'm receiving tons of advertisements. Some add me to a group. Some add me to a channel. Some send text message. It's very annoying. The first five minutes that I open Telegram, will be wasted in deleting spams like this:
for spam in messages:
    print "f**\* you " + spam.sender
    spam.delete()
And your Report as spam or Block feature doesn't help since the advertisers change their numbers everyday.
I'm not the only one who is experiencing this problem. In Iran, I know, there are millions of users with the same situation. It will be great if you think about a way to solve this. For example, by giving us a choice to prevent unknown numbers (the numbers which are not in our contact) from adding us to groups or channels and so on. These days, Telegram is going to become more annoying than useful for me.

**Comment by bliz937** [comment]
I believe the windows phone client used to have a white list option, can't seem to find it.

I think an idea would be to have options similar to that of the last seen privacy setting.
Have the ability to specify who can add you to a group or channel, contacts, contacts of contacts - with overriding rules.

**Comment by roloreaper** [comment]
Not sure this is the right place to log the bug.
This is just the Client to the Telegram System. Please try finding the bug tracker for that application http://core.Telegram.org would probably be my suggestion
