### ISSUE TITLE
[usability] No automatic selection of sticker when you insert a emoji

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1508]
version 0.9.19

Using the new feature, automatically selecting the suggested sticker is very annoying when wanting to insert a emoji in a conversation. It is common in mobile devices manually select the suggested sticker when you insert a emoji and the same should happen in TDesktop.

For example in a conversation, an unsuspecting user may want to insert a emoji (emoji + enter), instead, the first suggested sticker is inserted.

In case, the user must manually choose the suggested sticker.

Cheers

**Comment by telegramdesktop** [comment]
@diazbastian Yes, it won't be selected by default in the future.

**Comment by amiremami** [comment]
@telegramdesktop Is it possible to suggest stickers but disable the focus from them? So if we press enter, we can send emjoji.

![asd](https://cloud.githubusercontent.com/assets/15929497/12263405/118f7ab0-b92f-11e5-8efa-e4bbc8ce850c.png)

**Comment by theus** [comment]
I send a sticker by mistake all the time instead of send a emoji with enter :/

**Comment by diazbastian** [comment]
This problem is solved long ago...
