### ISSUE TITLE
[Feature request] Being able to lock Telegram in the "notification bar" (don't know how it's called)

### ISSUE THREAD

**Issue by larfadin** [telegramdesktop/tdesktop#1509]
When we have set a password on telegram desktop for security reason, it would be great if when we click on telegram (where it show: `Open telegram`, `minimize to tray`, `Disable notification`, `Quit telegram`).
It would be great to have one more choice: `lock telegram`. Like when we lock our session on our computer

**Comment by auchri** [comment]
Duplicate #1371
