### ISSUE TITLE
Title glitches on Windows7 Classic Theme

### ISSUE THREAD

**Issue by Revertron** [telegramdesktop/tdesktop#1510]
In the version 0.9.18 I have a new bug. You can see it on this picture:
![telegramtitlebug](https://cloud.githubusercontent.com/assets/105154/12256828/e7da9ab4-b911-11e5-807c-218edaeda598.png)
To reproduce this bug you need to have Windows 7 (x64) with Classic theme. Just minimize Telegram with button on title and restore by clicking on it in Windows' application bar.

**Comment by telegramdesktop** [comment]
I think this should've been in all version from the very start. I don't know how this comes out :(

**Comment by Revertron** [comment]
I did see this bug before, but it was rare, now, with latest stable release it is just like always If you do it like I wrote before.

**Comment by Revertron** [comment]
UDP: Restarted Telegram and can't reproduce it. But before restart it was 100% reproducible.
Do you make this window borderless from the start, or you just paint over client and non-client area?

**Comment by telegramdesktop** [comment]
@Revertron I paint over non client area, because I need title to work as a title (snap to border for example).

**Comment by auchri** [comment]
Duplicate #1216
