### ISSUE TITLE
Telegram blocks copy text to linux Xorg clipboard

### ISSUE THREAD

**Issue by unera** [telegramdesktop/tdesktop#1511]
selects and use mouse3 button don't work
selects and menu/copy copies into telegrams INTERNAL clipboard, xorg knows nothing about copied text.

So it is impossible to copy text from chat to terminal.

I don't know, may be in KDE/Gnome the problem is unreproducible, but I don't want to install them to check the bug.

**Comment by michirod** [comment]
on Gnome 3:
mouse3 button doesn't work.
^C + ^V does work.
right click and copy does work

**Comment by Zenexer** [comment]
Not able to reproduce on GNOME 3.  Mouse 3 doesn't work, but that's true for many applications; it's a dying standard.  Clipboard works fine, though.  I wrote this in in Telegram and copied it to GitHub.

**Comment by unera** [comment]
> on Gnome 3: ... does work

I don't use Gnome3/KDE.
So I use Xorg clipboard - without Gnome/KDE replaces.

locale - ru_RU.UTF-8

**Comment by unera** [comment]
> mouse3 button doesn't work.

Almost always I use mouse3 to copy text.

**Comment by unera** [comment]
> mouse3 doesn't work ... it's a dying standard. 

Telegram is the first my application that can't copy text to clipboard.

**Comment by The-Compiler** [comment]
From the [XDG clipboard spec](http://standards.freedesktop.org/clipboards-spec/clipboards-0.1.txt):

> - selecting but with no explicit copy should only set PRIMARY,
>   never CLIPBOARD
>
> - middle mouse button should paste PRIMARY, never CLIPBOARD

IMHO, this doesn't only say "never CLIPBOARD", it also says you *should* set PRIMARY.

And honestly, I've not seen a single application except Wine-applications where this doesn't work.

**Comment by binrush** [comment]
Same problem on Debian with dwm as windows manager.

**Comment by ddomgn** [comment]
Debian Stretch/Sid, Xfce4, copy-paste works perfectly.

**Comment by misty-fungus** [comment]
Same problem on Debian/Sid. Neither of MMB, ctl+c or internal telegram RMB + Copy worked.
Experienced this problem for a month, then after system upgrade & telegram restart it has gone away.

**Comment by unera** [comment]
> Debian Stretch/Sid, Xfce4, copy-paste works perfectly.

copy/paste latin-1 symbols works fine.
copy/paste non-latin symbols (my locale is ru_RU.UTF-8) doesn't work.
So I think that Telegram does something wrong while copy text to clipboard.

**Comment by 0xBF** [comment]
Debian Jessie, Gnome 3, ru_RU.UTF-8 locale

copy/paste by ctrl-c + ctrl-v work ok
copy/paste by mouse selection + middle button doesn't work

Telegram is the only app with such problem, and this is really very annoying

**Comment by john-preston** [comment]
@0xBF Does it work in Telegram message input field and does not work only for messages? Or it does not work anywhere in Telegram?

**Comment by 0xBF** [comment]
@john-preston yes, it work in input field, but doesn't work for messages.

**Comment by Bo0oM** [comment]
I confirm the problem
Gnome 3, ru_RU.UTF-8

**Comment by alxrem** [comment]
OpenSuse Tumbleweed, Gnome 3.20, Telegram 0.9.40. Selected text of message don't appear in the primary clipboard, so the middle mouse button doesn't work as expected.

**Comment by sakal** [comment]
> Mouse 3 doesn't work, but that's true for many applications; it's a dying standard

who's told that is dying standard? It's a normal and expected if you using Linux not for the first time.

**Comment by dedok** [comment]
+1 for this feature

**Comment by 0xBF** [comment]
0.9.51 is now ok for me

**Comment by fzg** [comment]
Copy-paste is broken **again** on Telegram Desktop 1.1.23 / Debian GNU/Linux sid amd64 (xserver-xorg-core 2:1.18.4-2, icewm 1.3.8+mod+20161220-1, XTERM_LOCALE=en_US.UTF-8)

I'd say it was working til a couple months ago.

Be it with mouse clicks or ^C ^V,
be it from msg input box or chat content.

Only app that is broken like this (not counting wine). Comes without saying that it's a major annoyance.

**Comment by dschwoerer** [comment]
It worked for me in the past, but wasn't working just now.
After restarting telegram-desktop it showed a notice that it was updated and now it works again.
`Telegram Desktop was updated to version 1.2.6` - before it was version `1.2.1-1.fc26`
This is on fedora 26, using awesome WM

**Comment by stek29** [comment]
Lmao nice, package installed from official fedora distribution doesn't have autoupdate disabled? Sounds like an issue in fedora pkg for me: app shouldn't update to official build from fedora's, and should be managed only by package manager.

**Comment by dschwoerer** [comment]
There is not official fedora telegram-desktop package - due to the unfree nature of telegram.
It was updated by dnf - I doubt that telegram-desktop would have sufficient permission to update itself, but I didn't review the package in detail.

**Comment by AlexanderAmelkin** [comment]
@dschwoerer, what? Unfree nature of Telegram? It's open source and GPL! Look here:
https://github.com/telegramdesktop/tdesktop/blob/dev/LICENSE

**Comment by AstraSerg** [comment]
It stops working again after update to 1.5.1

**Comment by laviua** [comment]
1.5.4 still not working

**Comment by AlexanderAmelkin** [comment]
For anyone experiencing this problem, please check that you aren't running Telegram Desktop in a container. Many distributions (e.g. Linux Mint) offer some 'Application manager', 'Snap' or similar solutions to bring in applications as containers. In such cases copy-paste between the container and the host OS may be blocked as well as saved files will not be found where expected.

**Comment by dyonis** [comment]
I noticed that restarting the telegram helps for a while.
But after some event the clipboard stops working again.
Tg version 1.5.7 Beta
Xubuntu Ubuntu 16.04.5

**Comment by TarisMarh** [comment]
The problem appeared again.

Fedora 31
XFCE 4.14
Telegram-desktop 1.9.3

**Comment by fractalvision** [comment]
I solved it by turning on the 'Read/Write files on removable storage devices' switch in permissions section of the installed app.

**Comment by fractalvision** [comment]
Well, seems that the problem still persists, even with non-flatpak version. Right now, I'm using the dev version of the original client, but copy/paste keeps getting disabled randomly. It definitely works after start/restart the app, but then, in some moment, you notice that it doesn't and needs a restart again.

**Comment by sergeyklay** [comment]
The problem is not solved. 
```
$ dnf info telegram-desktop
Last metadata expiration check: 0:00:16 ago on Tue 28 Apr 2020 08:52:55 AM EEST.
Installed Packages
Name         : telegram-desktop
Version      : 2.0.1
Release      : 1.fc31
Architecture : x86_64
Size         : 38 M
Source       : telegram-desktop-2.0.1-1.fc31.src.rpm
Repository   : @System
From repo    : rpmfusion-free-updates
Summary      : Telegram Desktop official messaging app
URL          : https://github.com/telegramdesktop/tdesktop
License      : GPLv3+ and LGPLv2+ and LGPLv3
Description  : Telegram is a messaging app with a focus on speed and security, it’s super
             : fast, simple and free. You can use Telegram on all your devices at the same
             : time — your messages sync seamlessly across any number of your phones,
             : tablets or computers.
             : 
             : With Telegram, you can send messages, photos, videos and files of any type
             : (doc, zip, mp3, etc), as well as create groups for up to 50,000 people or
             : channels for broadcasting to unlimited audiences. You can write to your
             : phone contacts and find people by their usernames. As a result, Telegram is
             : like SMS and email combined — and can take care of all your personal or
             : business messaging needs.
```

Can paste from the clipboard. There are no problems with any other app, only with telegram.
