### ISSUE TITLE
How you implement the 'chat box'?

### ISSUE THREAD

**Issue by tlexy** [telegramdesktop/tdesktop#1512]
I try to read the code, but i failed to build the project both in linux and windows platform. i just wonder how you implement the chat box with the function that customer can select the and copy the text messages and emoji......if you could told me about it or give me some material, i'll very appreciate it.

**Comment by tlexy** [comment]
![20160112174235](https://cloud.githubusercontent.com/assets/7891191/12259941/eadde24c-b953-11e5-8ff0-9f5c022485d8.png)

**Comment by telegramdesktop** [comment]
Well, this all are custom ui controls, see [history.cpp](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/history.cpp) and [text.cpp](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/gui/text.cpp)
