### ISSUE TITLE
Can't create group with signle meber (self).

### ISSUE THREAD

**Issue by tbdbj** [telegramdesktop/tdesktop#1517]
New group -> Next->"abcd"->select self-> create button not works

**Comment by telegramdesktop** [comment]
@tbdbj Yes, server will respond with "too few members" error.

**Comment by tbdbj** [comment]
Зато можно создать группу на два человека, а потом его удалить. Останется один. Почему ч просто не могу создать группу, а потом её наполнить ботами и пр. При этом группа из самого себя ничему не противоречит и делается она просто. Значит баг.

**Comment by telegramdesktop** [comment]
@tbdbj 1. Please write in English, this is an international telegram desktop issue tracker.

2. This issue has nothing to do with telegram desktop, so there is no sense in placing it here. You can contact Telegram team in Twitter on @telegram or in Settings of any Telegram app, using the «Ask a question» button. Only issues that are specific for telegram desktop get any attention here.
