### ISSUE TITLE
the need of more "online" time

### ISSUE THREAD

**Issue by pyed** [telegramdesktop/tdesktop#1518]
As soon as you put `tdesktop` in focus you will be shown `online`, but when you get out of focus `tdesktop` will wait exactly `5 seconds` to set your status to offline.

What I wish to do is to bumping this number to something like `30-60 seconds` so I can do some work on my computer while chatting with "someone" and not having this "someone" shouting on me for not paying enough attention.

so what I'm asking for is which `variable` or `function` is responsible for this behavior, so I can alter it and compile my own version

**Comment by stek29** [comment]
Change `OfflineIdleTimeout`. 
It's set in `facades.cpp` somewhere near line 513

**Comment by auchri** [comment]
@stek29 thank you!
