### ISSUE TITLE
Запрос на добавление а группу/ кривая система бана

### ISSUE THREAD

**Issue by tbdbj** [telegramdesktop/tdesktop#1519]
У вас заложен кривой сценарий на добавления в группу.
Я создаю группу. У меня есть контакт человека. Я его указываю (случайно или специально), у человека мой телефон не в книге адресной потому что общаемся редко по мобиле и он звонит напрямую. Он не разобравшись что за группа жалуется на меня и я а бане. Это весьма кривая логика. Если мне названивает человек, я его вношу в Боже лист и все, его названиваете не приводят к отказу связи у него.
В добавок, ваш баг сам по себе корявый. Вы блочите доступ по нахождению в адресной книге. Супер умное решение, которое тупо отрезает всех ботов. Одна такая случайность и я перевожу все свои контакте из раздела b2b на slack и им подобные, потому как сделали вы криво, а из за любой ошибки потом с кем то связываться мне совершенно не хочется и позволить встать процессу я не могу. Выпрямляйте иначе от вас уйдёт бизнес клиенты. По хорошему я вообще не должен вам писать, в том числе и сюда.

**Comment by tbdbj** [comment]
А да. Предлагаю ввести Блэклист. Ввести запрос на присоединение к группе. Убрать баг как параною или оставить его если вы считаете что делаете не платформу а долбанную чатрум хреновину

**Comment by tbdbj** [comment]
Убрать бан как таковой, или нынче винты это проблема?

**Comment by telegramdesktop** [comment]
@tbdbj 1. Please write in English, this is an international telegram desktop issue tracker.

2. This issue has nothing to do with telegram desktop, so there is no sense in placing it here. You can contact Telegram team in Twitter on @telegram or in Settings of any Telegram app, using the «Ask a question» button. Only issues that are specific for telegram desktop get any attention here.

**Comment by tbdbj** [comment]
Well bratello
