### ISSUE TITLE
The stickers from some packs are displayed as images sent as files (Android to TDesktop)

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1522]
It is a strange behavior does not occur with all packs of stickers.
I've noticed that two different things happen:

1-The stickers sent from Android are displayed as images sent as files on TDesktop
2-Not always the sticker sent from TDesktop is displayed in Android.

Telegram for Android 3.4.2
TDesktop on Linux (fedora 23) version 0.9.19

Sticker pack: https://telegram.me/addstickers/SASSAS

Cheers
![1](https://cloud.githubusercontent.com/assets/5126124/12344713/3a1c0d4e-bb1f-11e5-897f-29b86f2fc7c4.png)
![2](https://cloud.githubusercontent.com/assets/5126124/12344714/3a20693e-bb1f-11e5-8935-c6cf9e48d606.jpg)
![3](https://cloud.githubusercontent.com/assets/5126124/12344715/3aa3911a-bb1f-11e5-9d1d-8c119302a4cb.png)

**Comment by auchri** [comment]
Duplicate #826 
(Same sticker pack, lol)
