### ISSUE TITLE
Wrong window title

### ISSUE THREAD

**Issue by xakkep9000** [telegramdesktop/tdesktop#1526]
![image](https://cloud.githubusercontent.com/assets/5684489/12373547/07723b48-bc96-11e5-9852-32b48900c9c6.png)

Windows 7, Desktop telegram, use old theme (like win95, that named in Win7 like 'High contrast')

When I open telegram from pop messages, title of telegram windows displayed simultaneously with standart windows title.

**Comment by auchri** [comment]
Duplicate #1216
