### ISSUE TITLE
Lenny face problem at OS X

### ISSUE THREAD

**Issue by stek29** [telegramdesktop/tdesktop#1527]
Lenny face (`( ͡° ͜ʖ ͡° )`) has no mouth   
But when I send it as code (backticked) it's ok  
Some screenshots:
On Windows: ![Win](https://cloud.githubusercontent.com/assets/11808223/12375003/8c63f336-bcbf-11e5-8477-8e0d02011589.jpg)

On OS X: ![OS X](https://cloud.githubusercontent.com/assets/11808223/12374996/5d3bedde-bcbf-11e5-9a28-e3c20784beff.png)

I use 0.9.18 AppStore version on OSX 10.11.2

**Comment by stek29** [comment]
Also it shows wrong everywhere (messages, text fields, labels, site previews)

**Comment by Zenexer** [comment]
Looks like the font doesn't support that character; it's showing up as a box.

**Comment by stek29** [comment]
Yes, but it works on windows, and works in code mode

**Comment by stek29** [comment]
It adds fonts in application.cpp:

    QFontDatabase::addApplicationFont(qsl(":/gui/art/fonts/OpenSans-Regular.ttf"));
    QFontDatabase::addApplicationFont(qsl(":/gui/art/fonts/OpenSans-Bold.ttf"));
    QFontDatabase::addApplicationFont(qsl(":/gui/art/fonts/OpenSans-Semibold.ttf"));

And that fonts *don't* have glyph for `U+035C` symbol!

Also, if I comment out that lines, it builds with other font (standard Qt font maybe?), but in code mode fonts are same. 
And I can't find any other place where fonts are added, so it should be standard Qt font (which may be system font)

**Comment by Zenexer** [comment]
But I love Open Sans :(

**Comment by stek29** [comment]
Where could I get Open Sans font? Some repo? Maybe I can report this problem?

**Comment by Zenexer** [comment]
It should be on Google Fonts.

**Comment by stek29** [comment]
I still can't understand this: why it doesn't use some system font if default doesn't have it?

**Comment by noquierouser** [comment]
I remember some time ago to have recommended [Noto Sans](https://www.google.com/get/noto/) as a font for the app, because of its support for many languages.

Has anyone tested Lenny face with Noto Sans?

**Comment by stek29** [comment]
I think it all should be part of big update with themes support: dynamic style.txt, emojis, icons, fonts, etc...

**Comment by DaFri-Nochiterov** [comment]
@stek29 And theme manager to change queue of loading (like in Minecraft, good example? :smiley:)

For example:
1. Dark theme (overrides TDesktop default set)
2. EmojiOne theme (overrides emoji from dark theme if it contains emoji)
3. Roboto font theme (overrides font from dark theme if it contains fonts)

This may take more time to load TDesktop, but it's chosen by user: themes or fast load.

**Comment by stek29** [comment]
@DaFri-Nochiterov Just make one dark roboto emojione theme...

**Comment by stek29** [comment]
Btw I just understood it was a duplicate of #585 and others. :confused:
