### ISSUE TITLE
File picker on linux not showing extensionless files

### ISSUE THREAD

**Issue by Arcaena** [telegramdesktop/tdesktop#1528]
I'm not sure if the file picker on Linux is part of the qt framework (and thus upstream) or if it's a problem.

Here's a visual example:

![2016-01-16_20 34 13_scrot](https://cloud.githubusercontent.com/assets/3235827/12375623/86d0e1ba-bc90-11e5-8f24-99c4a0dbe99b.png)

Basically, any file that doesn't have a period in the filename doesn't show up in the file picker. While dragging and dropping the files still works, it's a bit cumbersome.

When I tick "show hidden files", then files and folders that begin with a period show up; however, files without a period still don't show up.

A framework such as [this](https://github.com/mlabbe/nativefiledialog) could be used instead, or something like [xdg-open](https://wiki.archlinux.org/index.php/xdg-open) could be checked against to call the native file manager. (Currently I use thunar, so it might just be that qt doesn't check for that and falls back to their own dialogue, I think)

**Comment by auchri** [comment]
See #987

**Comment by ManuelSchneid3r** [comment]
I am the author of #987. Note that #987 is *not* about the filechooser. #987 is about the *application style* in general. Check #982 for native filechooser.

**Comment by john-preston** [comment]
In the latest 0.9.57 version gtk file chooser should be used if it is available. Please check.

**Comment by john-preston** [comment]
https://github.com/mlabbe/nativefiledialog lists "GTK+3 dialog on Linux", so I guess no advantage in using it now.
