### ISSUE TITLE
Making hashtags with only numbers

### ISSUE THREAD

**Issue by meness** [telegramdesktop/tdesktop#1529]
Hi,

I found when I send a picture as compressed and prepare a hashtag with only numbers (i.e. `#1992`) everything is fine but when I send the prepared text without a picture, the hashtag is not linked.

**Note:** I'm using the latest version of Telegram for Windows.
**Note:** This problem also exists in the latest version of Telegram for Android

![screenshot 34](https://cloud.githubusercontent.com/assets/7955356/12376802/654226a4-bd1b-11e5-8de6-d99fd8acae2f.png)

**Comment by stek29** [comment]
But it suggests you previous number hashtag while typing (even if they're not highlighted):
![2016-01-23 3 59 01](https://cloud.githubusercontent.com/assets/11808223/12527050/1846d9b6-c186-11e5-9a62-95256ab01a84.png)

And it's highlighting it while sending message, but when it sent, it becomes simple text:
![2016-01-23 3 59 27 1](https://cloud.githubusercontent.com/assets/11808223/12527060/3c89d120-c186-11e5-8c91-d599ac6f1cd8.png)
![2016-01-23 4 03 17](https://cloud.githubusercontent.com/assets/11808223/12527065/47d7f430-c186-11e5-8940-1b09a994fb38.png)

**Comment by stek29** [comment]
I'm not sure if this is an actual bug tbh.
The problem is server doesn't allow hashtags starting with number, but TDestkop allows them.
But text in captions is parsed on client side only. That's why this happens. 
Just tweaking a regexp should be enough to fix it, but is it needed?

**Comment by Aokromes** [comment]
before this was possible, on android you cannot, now you cannot on desktop too. not a bug.
