### ISSUE TITLE
Tray icon drawn on another one (XFCE)

### ISSUE THREAD

**Issue by jmayday** [telegramdesktop/tdesktop#1530]
Hi, 

I've updated Telegram already a few times but some issue is still present - tray icon is drawn on another one - please see attached png file. 
I'm using Archlinux and XFCE 4.12

Name          : xfce4-panel
Version        : 4.12.0-1

Name          : telegram-desktop-bin
Version        : 0.9.18-1

![telegram](https://cloud.githubusercontent.com/assets/10167533/12377234/a05d3fbc-bd16-11e5-81b1-693b89209efe.png)

**Comment by Aokromes** [comment]
#1071 Maybe it's generic bug?

**Comment by jmayday** [comment]
@Aokromes I'll pay attention if this occurs for other applications and get you informed.

**Comment by jmayday** [comment]
@Aokromes seems like it's rather a generic bug of XFCE. Closing.
