### ISSUE TITLE
Layer level

### ISSUE THREAD

**Issue by badoualy** [telegramdesktop/tdesktop#1538]
Hi,

where did you get the tl-schema you're currently using? It's not documented on the telegram website, do you have the json version?

**Comment by CharlesOkwuagwu** [comment]
Same is in Webogram

**Comment by badoualy** [comment]
Lol, you found the solution, the json is included here:
https://github.com/zhukov/webogram/blob/master/app/js/lib/config.js#L101

**Comment by auchri** [comment]
Or here: https://github.com/zhukov/webogram/blob/master/app/js/lib/schema.tl.txt :)

**Comment by mbande** [comment]
as the most recent version [documented](https://core.telegram.org/api/layers#layer-18) in telegram website is layer 18, how one can find out what new features is included in new layers?

**Comment by stek29** [comment]
@mbande By digging through the source code, testing and guessing.
