### ISSUE TITLE
Thumbnails of sticker packs are too few and too small / window too small.

### ISSUE THREAD

**Issue by DiThi** [telegramdesktop/tdesktop#1539]
Being a frequent user of Tdesktop, I put up with the UI awkwardness because I thought the phone version was equally bad.

Nope.

I bought a new phone and started using Telegram on it a lot, and surprise! I can see SEVEN thumbnails, with a sharp HiDPI screen, very clear despite their small size.

In Tdesktop I can only see FOUR at a time (and a faded half), in a big screen that I can't put closer to my face (but instead things should be bigger). The stickers window occupy a very tiny bit of my PC screen, no matter how big the main window is. Additionally scrolling a tiny space with a mouse wheel is not a very good experience, and scrolling with a touch pad is too awkward.

It is OK if you have less than 7, but I have 20 even after removing the packs I don't use, and it takes me too long to find the one I want to use, it's frustrating.

Suggested solution: make sticker window detachable and resizable.

Related issues: #975 #890 (also I thought there was an issue suggesting a resizable sticker window, but I can't find it)

**Comment by auchri** [comment]
#713 :)
