### ISSUE TITLE
Build Error for Telegram.pro QTLauncher Linux

### ISSUE THREAD

**Issue by keyvanarasteh** [telegramdesktop/tdesktop#1541]
When i try to compile Telegram.pro i'm getting error : 

/home/keyvan/TBuild/Libraries/QtStatic/qtbase/lib/libQt5Widgets.a(qgtkstyle_p.o): In function `QGtkStylePrivate::getGConfString(QString const&, QString const&)':
qgtkstyle_p.cpp:(.text+0x5e2): undefined reference to `g_object_unref'
qgtkstyle_p.cpp:(.text+0x5f5): undefined reference to `g_error_free'
qgtkstyle_p.cpp:(.text+0x686): undefined reference to `g_free'
/home/keyvan/TBuild/Libraries/QtStatic/qtbase/lib/libQt5Widgets.a(qgtkstyle_p.o): In function `QGtkStylePrivate::getGConfBool(QString const&, bool)':
qgtkstyle_p.cpp:(.text+0x763): undefined reference to `g_object_unref'
qgtkstyle_p.cpp:(.text+0x772): undefined reference to `g_error_free'
/home/keyvan/TBuild/Libraries/QtStatic/qtbase/lib/libQt5Widgets.a(qgtkstyle_p.o): In function `QGtkStylePrivate::getThemeName()':
qgtkstyle_p.cpp:(.text+0x7fd): undefined reference to `g_object_get'
qgtkstyle_p.cpp:(.text+0x84e): undefined reference to `g_free'
/home/keyvan/TBuild/Libraries/QtStatic/qtbase/lib/libQt5Widgets.a(qgtkstyle_p.o): In function `QGtkStylePrivate::getFilesystemIcon(QFileInfo const&)':
qgtkstyle_p.cpp:(.text+0x1025): undefined reference to `g_free'

i runned qmake & MetaStyle & MetaLang Before. :-1: 

help plzzzz

**Comment by keyvanarasteh** [comment]
it's because of this : 
![issue1](https://cloud.githubusercontent.com/assets/16303698/12473784/3fdfb14a-bfca-11e5-8127-c2dc5685f47c.jpg)

help to solve this problem :-( i cant select staticqt for kits : 

![issue2](https://cloud.githubusercontent.com/assets/16303698/12473813/75b8e2e6-bfca-11e5-8a62-0c9abb5e1523.jpg)

help plzzz :1234:

**Comment by keyvanarasteh** [comment]
Errors Screenshot :

![errors](https://cloud.githubusercontent.com/assets/16303698/12475687/7eaf1488-bfd9-11e5-8bb3-231b711946bc.jpg)

**Comment by DaFri-Nochiterov** [comment]
@keyvanarasteh, in Kits tab press "Clone", now select new kit in 'Manual', change name, change Qt Version and press Apply.
