### ISSUE TITLE
Secret chat on Windows?

### ISSUE THREAD

**Issue by ivankoma** [telegramdesktop/tdesktop#1545]
How do I create secret chat on Windows client?

I have both Android and Windows client, my friend has only Windows client. If I create secret chat on phone and I invite him app only says "Waiting for X to get online...", but he is online.

**Comment by auchri** [comment]
Secret chat is not yet implemented in telegram desktop. See #871

**Comment by euglv** [comment]
When you are going to implement secret chats on Windows desktop client?
This is the most useful feature that telegram has.

**Comment by Milamesher** [comment]
Hello! I still don't see any opportunity to create a secret chat on windows desktop. Could you tell me please, are you going to implement it? It woild be a really great feature and very useful thing for me

**Comment by Milamesher** [comment]
Hello! I still don't see any opportunity to create a secret chat on windows desktop. Could you tell me please, are you going to implement it? It woild be a really great feature and very useful thing for me.
I wanted to ask this question at #871, but it's locked.

**Comment by stek29** [comment]
@Milamesher As far as I know nothing changed, and your comment provides 0 useful information. That's why the issue is looked.

**Comment by Milamesher** [comment]
@stek29 Thanks for your answer! I still hope it will be implemented.

**Comment by auchri** [comment]
@Milamesher The hope dies last 😉

**Comment by euglv** [comment]
I am not using telegram because of no secret chats

**Comment by auchri** [comment]
@euglv Unigram X supports secret chats.

**Comment by faustdotmef** [comment]
it's not serious for f*ng sake.
