### ISSUE TITLE
Telegram hijacks network

### ISSUE THREAD

**Issue by kgizdov** [telegramdesktop/tdesktop#1546]
Hi,

I am only able to test on one desktop (laptop actually) machine, but the issue is absolutely consistent.

On **Linux** and **Telegram 0.9.18** the desktop app gradually **floods the network** until it is solely connected to the Internet. After an hour or so, no other program can connect even to local IP (such as router at 192.168.1.x), but **Telegram's connection is undisturbed**. This happens on any network I have connected to - **Wifi, ethernet, home, office, even airport**. After some time this results in **high CPU usage** due to constant reconnect attempts from other processes. **If Telegram is not running the system behaves normally.**

I am however unable to identify a reason and exact mechanism for this. **Please advise on a way to troubleshoot.**

Thanks.

**Comment by stek29** [comment]
Have you tested older/newer versions?

**Comment by Zenexer** [comment]
This sounds like you're in groups with a lot of backlogged images.  Disable image/video/voice previews.

**Comment by kgizdov** [comment]
0.9.18 is the latest version that would auto update for me and I did not have this problem previously. This is a recent issue and does not happen on my Android.

Also, I am not part of any groups at all. Personal chats have almost no images and certainly no videos. So I don't think this applies.

It's interesting that you bring up that point, @Zenexer . If backlogs crumble the network, wouldn't it be a priority to limit backlog downloads and trigger them only on scrolling up towards the history of the current conversation.

**Comment by Zenexer** [comment]
Skype has always had issues loading backlogs; I thing they're trying to
avoid that sort of delay.  I believe it does wait until you scroll up
before downloading everything.  I've never seen it overwhelm a connection,
but I suppose it's possible, maybe if you're scrolled up somehow.  I'm not
sure what else would be using a lot of bandwidth.  How are you identifying
it as Telegram's traffic? Maybe that will hold some clues.

**Comment by stek29** [comment]
Can you please run something like `iftop` and check that it's Telegram really?

**Comment by kgizdov** [comment]
Hi,

@Zenexer I have no idea how this conversation went to Skype and backlogs. I already explained that this is highly unlikely in my case. Please read further down for further clarification.

@stek29 Just finished testing with `htop`, `lstop` and `nethogs` and I am more worried. It seems Telegram spawns more and more processes as it sits in the background. When I start Telegram, it starts some low number of processes (3-4), but after about an hour `htop` shows that number has jumped to 22 - varying in PID and active time, thus do not seem like threads to me. In the mean time, Telegram has been completely silent, no notifications or anything and has been sitting in the notification tray the whole time. The network usage from `lstop` shows frequent bursts of low bandwidth and `nethogs` shows Telegram just below Chrome - on which btw, I was watching 1080p videos the whole time.

I am obviously not an expert, but I think this would explain my issue. If Telegram spawns more and more processes with time, it would seem that each of them trying to reach the server will eventually overwhelm the network as the queue will be completely full of individual requests. Since all the connections are very brief and of low bandwidth, I believe it is highly unlikely the issue is due to backlog downloads. Any further suggestions on how to limit/prevent this behaviour are much appreciated.

**Comment by stek29** [comment]
I'm sure they'll need logs, so maybe you could create gist with them and leave link here?

**Comment by kgizdov** [comment]
Hi,

Sorry for the delay. I'm not sure how to produce proper logs, but I took some screenshots of `htop` and `nethogs`. Let me know if any other info is needed.

![htop](http://imgur.com/RI831t8.png)

There's lots to scroll down on `htop`. And here's `nethogs`

![nethogs](http://imgur.com/2qmKVjA.png)

It's weird how the actual per process bandwidth is pretty low, but there are lots of processes and high CPU usage. I don't have the actual know-how to diagnose exactly how and when it happens. I have discovered however, that Telegram needs to be idle for a long period of time (30+ minutes) for the problem to occur, otherwise it's all good. And it happens more often than not on managed networks with low bandwidth. Rarely happens at home.

For now, I'm closing and opening it every once in a while to get around the issue.

**Comment by Aokromes** [comment]
IDK if valgrind/helgrind can help you to find issues on linux code.

**Comment by kgizdov** [comment]
I am no longer experiencing this issue. `valgrind telegram` is clean and process count seems to be consistent with usage. Things that have changed from before include a version update, xorg & Qt updates and I set the scaling to x2 inside Telegram itself rather than with `export QT_DEVICE_PIXEL_RATIO=2`. I'm glad it all works fine, but it's a shame I could not identify the issue previously.
