### ISSUE TITLE
[REQUEST] Are there any vector files for the image assets?

### ISSUE THREAD

**Issue by JuanPotato** [telegramdesktop/tdesktop#1547]
I am trying to make a dark theme for telegram desktop and it would be very helpful if I could have vector files as they are easier to change colors in.

**Comment by telegramdesktop** [comment]
@JuanPotato Sorry, sprites are done that way, no vector images as a source :(

**Comment by JuanPotato** [comment]
Ok, thanks for the info. Guess I'll just photoshop intensly
