### ISSUE TITLE
Can't type emoji

### ISSUE THREAD

**Issue by Supuhstar** [telegramdesktop/tdesktop#1549]
Simply focus on a text field, open Windows' touch keyboard, open the Emoji section, and attempt to type them. Notice nothing is typed.

**Comment by Supuhstar** [comment]
Created sister bug in QT: https://bugreports.qt.io/browse/QTBUG-50617

**Comment by Supuhstar** [comment]
Related: [QT bug on Android with similar symptoms](https://bugreports.qt.io/browse/QTBUG-35156) has been fixed.

**Comment by john-preston** [comment]
@Supuhstar I won't be able to move to Qt 5.7 anytime soon, they drop too much of the OSs.

**Comment by Supuhstar** [comment]
@john-preston that's fine; as long as this is on your radar :smile_cat: 
Maybe also think of alternatives, like using a non-QT input field, or intercepting the emoji keystrokes and inserting them at the carat.

**Comment by Supuhstar** [comment]
Hey this seems to be resolved in 0.10.19!I'll test on my other computer later to verify
