### ISSUE TITLE
Set custom background

### ISSUE THREAD

**Issue by Brawl345** [telegramdesktop/tdesktop#155]
It would be great if we can set our own background for chats, like the mobile app!

**Comment by Streppel** [comment]
:+1:  I'd love this feature as well

**Comment by Wick** [comment]
This, or at least a darker theme please! I'm getting blinded as it is now :P

**Comment by narunetto** [comment]
i agree with a dark theme or a background changer, this would be incredibly useful

**Comment by Katzen-Gott** [comment]
Looks like it's fixed since v0.7.13 stable (10.02.15). @Brawl345 could you please check and close if it's OK now?

**Comment by Brawl345** [comment]
Yep it's great! I'll close this issue now :)
