### ISSUE TITLE
Delete old avatars (not the current one)

### ISSUE THREAD

**Issue by Leammas** [telegramdesktop/tdesktop#1551]
In desktop app it's impossible to remove one of the old avatars. You can do it only deleting all one by one starting with the current (like stack.pop()). It works in mobile app though. Corresponding screenshots attached.
![shot](https://cloud.githubusercontent.com/assets/9443290/12535701/f1ef439e-c29c-11e5-82d1-9fa3888aca76.png)
![shot2](https://cloud.githubusercontent.com/assets/9443290/12535702/f1efd430-c29c-11e5-9e1e-0aad294a368c.png)

**Comment by Aokromes** [comment]
#204
