### ISSUE TITLE
License of the default "great mind" stickers (and where to get them)

### ISSUE THREAD

**Issue by runn1ng** [telegramdesktop/tdesktop#1552]
Hello,

I am not sure if this is the good place to ask, but I can think of no better, since there is no official Telegram contact.

I want to use Telegram stickers in my unrelated project. What licence are the default "great minds" stickers under, and where to download them, if they are under some free/creative commons license?

Thanks

**Comment by stek29** [comment]
There is official contact, on [Contest page](https://core.telegram.org/contest300K#bonus-objective)
I've even wrote there about problem in API Documentation, and they answered 
But I'm not sure that you should write there

**Comment by auchri** [comment]
Ask at twitter https://twitter.com/telegram or use the "Ask a question" feature in one of the official apps.

**Comment by runn1ng** [comment]
thanks!
