### ISSUE TITLE
Add feature to Autoscroll to the newest message.

### ISSUE THREAD

**Issue by mikh86** [telegramdesktop/tdesktop#1553]
It would be really useful if you can add an option that would automatically scroll down to the last message sent, so its easier to stay with the conversation.

**Comment by ProfessorGary** [comment]
yes if you guys add this you all would automatically become the kings of the universe

**Comment by telegramdesktop** [comment]
@ProfessorGary I didn't understand the request.

**Comment by ralesk** [comment]
When you're on the bottom of the chat, the chat already keeps up with the conversation.  Except if the window is unfocused, because then it waits until the screen is full and then instead of making you lose track, it stays at the first unread message with the message at the top of the screen.

If you aren't scrolled to the bottom of the chat view, it will stay where it is.

So I don't understand the issue either.

**Comment by MeDeVILe** [comment]
@LiquidProcessor just press End button on your keyboard.

**Comment by DaFri-Nochiterov** [comment]
+1 for option to auto-scroll chat instead display '{count} unread messages'.
Always scroll chat to newest message, also when window aren't focused. (but on screen now)

**Comment by ralesk** [comment]
Why would you want to miss messages automatically? This way there's an option to read if you want, or press one button and skip all of them.

**Comment by DaFri-Nochiterov** [comment]
I'am reading chat, but when window unfocused, after 10 seconds new messages will be not shown, just '123 unread messages' on top. I want to scroll it automatically without need click on the button each 15 seconds.

Example, where it's needed, when I doing 'work':
![image](https://cloud.githubusercontent.com/assets/10401817/13037101/3c379ebc-d3a3-11e5-80fa-4bcf4b1aaad4.png)

**Comment by MeDeVILe** [comment]
So if in try show unread when on panel keep rolling

**Comment by jeyemwey** [comment]
:+1: for this one! Might be interesting if you just want to follow a channel without being active.

**Comment by formatq** [comment]
I think it already implemented in last release

**Comment by stek29** [comment]
@formatq try to unfocus app (switch to other app while tdesktop is still visible)
Does it scroll?

**Comment by kehindelawal** [comment]
hi. Is it possible to be able to scroll to the TOP or implement it. One of the differentiating point from whatsapp is that joining a group makes all the group's past chat available to you. This is very good for student using a group for study purposes. However, you might have to scroll thru days/months of post to be able to catch the groups oldest discussion. 
hope this request is clear.
Thank you

**Comment by jcadduono** [comment]
yup I'm in large groups and it's really annoying to have to hit the arrow button every time I want to go back to reading the conversation. You should consider adding an "Enable scrolling in background" option to each window the same way "Disable notifications" works from the 3 dot menu. (per group setting)

Another feature I would really like that is somewhat related is middle mouse button click hold scrolling, the same way it works in a web browser window.

@telegramdesktop

**Comment by casper** [comment]
This problem seems to have been reported previously here too:    
https://github.com/telegramdesktop/tdesktop/issues/753

..and here:    
https://www.reddit.com/r/Telegram/comments/5dzhzr/qa_telegram_wont_autoscroll_the_chat/

The issue is that when you leave the window unfocused, after about 10-15 seconds it stops scrolling.
It makes it impossible to keep up with live conversations. How is this not fixed yet?

**Comment by auchri** [comment]
@casper It's not a bug. If I leave the Window open and go away from the computer, new messages should _not_ be marked aa read.

**Comment by casper** [comment]
Here is a simple AutoHotkey script to fix this issue:
```ahk
#NoEnv 
SendMode Input
SetWorkingDir %A_ScriptDir%

Loop {
  If Not WinActive("Telegram") {
    ; Send WM_ACTIVATE to fool Telegram into thinking the window has been activated.
    ; This seems to prevent the balloon notification of missed messages.
    PostMessage, 0x0006,2,,,Telegram
    
    ; Send WM_KEYDOWN + KEYUP for VK_NEXT (0x22 PgDown) to scroll to bottom.
    ; This ensures we're seeing the latest output.
    PostMessage, 0x100, 0x22,,,Telegram
    PostMessage, 0x101, 0x22,,,Telegram 
  }

  Sleep 1000
}
```

**Comment by casper** [comment]
@auchri If I put the window in the corner of the screen to be able to follow a conversation while I do something else, the scrolling will stop after a while. 

That's a bug as far as I'm concerned. I want the window to keep scrolling regardless of if it's active or not. That's how IRC or Slack or any other chat application works. 

Now Telegram demands that the window is kept active at all times. It prevents me from doing other work while keeping an eye on the discussion.

**Comment by ralesk** [comment]
And a lot of other people would want to read up on the messages and not miss them.  To them this is a feature.

**Comment by ElectricMan** [comment]
I have to agree with @casper. I want Telegram to work as IRC does. I often have group chats open in telegram on my second monitor, and being forced to scroll down everytime is crap.

If this is a feature, please ad an option/setting to activate auto scroll.

**Comment by ralesk** [comment]
Maybe autoscroll the active chat view only if you're already on the bottom of the viewport? If you scroll a bit up, don't autoscroll any further.

**Comment by nwhitmont** [comment]
open for 2 years now -- anyone going to work on this?

**Comment by klaus7** [comment]
I'm also the sort of guy who has the chat window not active most of the time and I hate it that I always have to scroll down to read the new messages. Wouldn't it be possible to just have a setting "Always scroll to new message?" that is disabled by default? Then everybody would be happy.

**Comment by DmitryGG** [comment]
Status?

**Comment by michaelmagistro** [comment]
+1
First of all, I have several monitors and telegram is always open, but not focused, so I can always see it.
Second of all, not every chat is the same. Some chats might have bots or are of a nature that only the most recent messages matter. So, having the option for autoscroll would be great.

I understand some chats require every message be seen and read, or are more slow-moving. But some chats are more lively and having to scroll is a pain.

**Comment by michaelmagistro** [comment]
> Here is a simple AutoHotkey script to fix this issue:
> 
> ```ahk
> #NoEnv 
> SendMode Input
> SetWorkingDir %A_ScriptDir%
> 
> Loop {
>   If Not WinActive("Telegram") {
>     ; Send WM_ACTIVATE to fool Telegram into thinking the window has been activated.
>     ; This seems to prevent the balloon notification of missed messages.
>     PostMessage, 0x0006,2,,,Telegram
>   }
> 
>   Sleep 1000
> }
> ```

Thanks, this works

**Comment by nikowonde** [comment]
> I'm also the sort of guy who has the chat window not active most of the time and I hate it that I always have to scroll down to read the new messages. Wouldn't it be possible to just have a setting "Always scroll to new message?" that is disabled by default? Then everybody would be happy.

This is something I would want to see being included into Telegram, having it open on once screen and doing other tasks while looking chat now and then it would be great to keep up with the newest convos...

**Comment by Tester-helper** [comment]
We have 9/2019 and still not fixed? Terrible...

**Comment by saisaijo** [comment]
I'm flabbergasted that almost 4 years later this is still an issue with the web app..
In a world where people try to do more things at the same time, requiring you to keep focus on a window is just bad design and low adaptability to the market.

**Comment by setevoy2** [comment]
Indeed - "_opened this issue on Jan 25, 2016_" and now is 2019...
This would be really great to have the ability to enable auto-scroll down when TG out of focus.

**Comment by Alexisgarci** [comment]
why isnt this done already? just do it already!!!!!

**Comment by Mte90** [comment]
Slack has a feature like that enabled to set the workspace that you want to autoscroll to bottom and mark as read.
Maybe an option for channels can save a lot of time.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/753

**Comment by andychups** [comment]
Use folder "Unread" like workaround. Don't thank me.
