### ISSUE TITLE
Pause already downloaded and playing gif

### ISSUE THREAD

**Issue by MyCloud012** [telegramdesktop/tdesktop#1554]
Hello,

I wanted to give feedback about the newly added inline bots, specifically, the @gif one. Throughout a UI wise, I believe you should add the option to "pause" the looping of the gif. In a typical use case where a conversation has ended with @gif something, it lasts for hours until a sufficient number of messages have occurred to slide it up. This gif looping behavior is kinda UI abusing , as a user, I started to feel that I carved a short-long term gif  in the chat to express a very moment dependent thing.

**Comment by telegramdesktop** [comment]
@MyCloud012 You can disable gif auto play in settings > automatic media download

**Comment by stek29** [comment]
@telegramdesktop I think he wants to pause already downloaded and playing gif

**Comment by MyCloud012** [comment]
@stek29 Your thought is correct.

**Comment by stek29** [comment]
@MyCloud012 Maybe you'll change issue title then? It's a bit confusing.

**Comment by doublejumper** [comment]
+1

**Comment by Aokromes** [comment]
This is already working on 0.9.49

**Comment by doublejumper** [comment]
@Aokromes Is it? I see no sign of it here, neither with @gif or uploaded gifs.

**Comment by palenshus** [comment]
Verified this works, if you uncheck Autoplay in settings > automatic media download, you can click the GIF to pause it

**Comment by oriadam** [comment]
Hey, 
Sorry for bumping this after so long, I just have one obvious question -
Why "pause-gif" is kept only for those who disabled Autoplay/Auto download?
