### ISSUE TITLE
your app is scam

### ISSUE THREAD

**Issue by s777s** [telegramdesktop/tdesktop#1555]
Hate you, guys. Really hate you.
You app - is real scam.
I needed Telegram ONLY because of its _secretchat_ function!
And nothing else, it is well documented on official site, it is MAIN function.
Moreover, it is positioned as main function (with end-to-end client-to-client encryption) in all information sources!
There is ready app in official Arch repos - Cutegram! And it works excelent with end-to-end encryption!
But I've downloaded your GARBAGE from Aur  firstly (with a lot of another garbage in dependencies) and it was compiling for ages!
Why? Because  you are scammers and named your project "Telegram-desktop" as if it was official client (like on android or iphone) instead of smthg like Hrenogram-desktop and haven't inclded basic functionality!
I don't need all that smiles etc, only BASIC official functionality!
I'm SO angry!(((

**Comment by ralesk** [comment]
This is the official client though. Sorry that you don't like it, but this is the real thing.  Cutegram is a fairly decent clone.

**Comment by PerryVerheij** [comment]
Sorry @s777s, but there are lots of users out in this world who **do** want those features you just mentioned. If you really dislike them, you should probably search for a different chat service.

I'd mark this issue closed, @telegramdesktop.
