### ISSUE TITLE
Feature request: Edit message

### ISSUE THREAD

**Issue by armedjack** [telegramdesktop/tdesktop#1556]
Guys are you srlsly? Skype, Slack etc has this option. Telegramm still does'not.

1) Right click on own msg => "Edit" option in pop-up menu => Msg in text field => Original text changing on a new one after submiting with adding "Eddited hh:mm"

2) Press Up Arrow Buttun => Last own msg in text field => Original text changing on a new one after submiting with adding "Eddited hh:mm"

**Comment by DaFri-Nochiterov** [comment]
Doesn't supported by API

**Comment by auchri** [comment]
yep
