### ISSUE TITLE
Share faster with local peers

### ISSUE THREAD

**Issue by christianromeni** [telegramdesktop/tdesktop#1557]
We are using telegram in our company to send us small files from one to another. And I was currently waiting for a file to be transferred when I had an Idea. I'm not sure if it makes sense here, but what about finding other people using telegram desktop in the same network and establishing local connections to make transferring files faster on local. At the same time it should still be uploaded to the telegram servers in the background.
I'm not sure if this is the right place for it, but maybe I'm not the only one using it that way ;)

**Comment by jeffythedragonslayer** [comment]
Perhaps we add an opt-in option to support BitTorrent protocol to do this.

**Comment by RememberTheAir** [comment]
Telegram is a closed environment and this is probably way out of the scope of an official MTProto client
