### ISSUE TITLE
Toggle hide of contacts bar

### ISSUE THREAD

**Issue by mysp00n** [telegramdesktop/tdesktop#1560]
As title really, ability to toggle hide/show the contacts bar on the left - such as what happens when you shrink the window size but the above option would allow this functionality regardless of size.

**Comment by demidovakatya** [comment]
:+1: 

> such as what happens when you shrink the window size
Thank you so much for mentioning this! I would never guess about it

**Comment by auchri** [comment]
Duplicate #314
