### ISSUE TITLE
Android client development

### ISSUE THREAD

**Issue by woj-tek** [telegramdesktop/tdesktop#1561]
Hi!
I know that this is for telegram desktop but I'm curious about the status of development of Android app. Issues section was removed (so it's not possible to submit suggestions), pull requests are rarely integrated.

I've tried asking at twitter https://twitter.com/telegram or using "Ask a question" in the client but neither resulted in any response.
This doesn't send a positive vibe and diminishes the will to contribute/help.

**Comment by telegramdesktop** [comment]
@woj-tek I'm not sure, but I'm afraid the Android app developer was receiving too much attention and couldn't handle all the feedback — even for a lot smaller (desktop) app it is near to impossible to pay attention to everything what is suggested / wanted / discussed here, I barely look through all the stuff using Telegram @GitHubBot. So the status of Android app is «in development», like before.

There should be no misunderstanding, Telegram has open-source client apps, but they are not community developed, they do not follow the open-source software development process. They just have public source code and that's it.

Speaking of Telegram Desktop, I highly appreciate community contributions in improving the stability of the app and bug fixing pull requests (or at least information about how to fix them) are always welcome, but not the feature selection and/or their priority.

**Comment by woj-tek** [comment]
Thanks for the clarification. A bit of pity, but I understand :-)
