### ISSUE TITLE
cannot search Chinese message

### ISSUE THREAD

**Issue by sunt05** [telegramdesktop/tdesktop#1562]
Search for Chinese messages basically get noting correct.

**Comment by auchri** [comment]
any examples?

**Comment by sunt05** [comment]
![screen shot 2016-01-27 at 6 08 28 pm](https://cloud.githubusercontent.com/assets/1802656/12623213/04611896-c521-11e5-98a9-2af8e4362e1a.png)
This is a screenshot for a message window showing some Chinese messages.
Obviously, "中文" appears in the messages.
However, searching for it returns nothing.
![screen shot 2016-01-27 at 6 10 46 pm](https://cloud.githubusercontent.com/assets/1802656/12623295/52d57742-c521-11e5-9b24-613f550b127b.png)

**Comment by telegramdesktop** [comment]
@sunt05 Telegram Desktop uses server-side search, so it is not a tdesktop issue :( thanks for your report anyway.

**Comment by taijuin** [comment]
You can find the "中文", unless you search "这是一句中文", but not "句中文", "一句中文", "是一句中文"。😞

**Comment by taijuin** [comment]
you can find the "中文", if the message is "測試 中文 搜尋"，but not "測試中文搜尋".

**Comment by fengkx** [comment]
two years...

**Comment by ssmlee** [comment]
ya any progress on this feature?

**Comment by ssmlee04** [comment]
any progress on this feature? It would be an extremely useful feature for non English speaking users. thanks!

**Comment by wangqr** [comment]
It has been 4 years and we still don't have this function implemented on telegram server side. Can we add a function to search locally? Even if it only returns recent results, it is still quite useful

**Comment by Aokromes** [comment]
it looks it's not only chinese, instead no partial searchs.
https://github.com/telegramdesktop/tdesktop/issues/7096

**Comment by themikesam** [comment]
they always close this kind of issues...

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/724
