### ISSUE TITLE
Option to not automatically show images, links previews and stickers

### ISSUE THREAD

**Issue by kmaid** [telegramdesktop/tdesktop#1567]
I would like an option to disable automatically showing images, links previews and stickers or some way of filtering content not suitable for work.

**Comment by stek29** [comment]
You can disable images preload in settings
Stickers already requested here
But disabling link preview... That's interesting feature

**Comment by kmaid** [comment]
The developer didn't see why it was important though. I was hoping this might give it a better use case

**Comment by auchri** [comment]
Link preview: #687
