### ISSUE TITLE
QtStatic Patch Not working !!!!

### ISSUE THREAD

**Issue by keyvanarasteh** [telegramdesktop/tdesktop#1572]
`cd qtbase && git apply ../../../tdesktop/Telegram/_qtbase_5_5_1_patch.diff && cd ..
`

not working it fails with error :-1: 

help please

`error: patch failed: mkspecs/common/msvc-desktop.conf:28
error: mkspecs/common/msvc-desktop.conf: patch does not apply
error: patch failed: src/corelib/tools/qunicodetables.cpp:5839
error: src/corelib/tools/qunicodetables.cpp: patch does not apply
error: patch failed: src/gui/kernel/qplatformdialoghelper.h:363
error: src/gui/kernel/qplatformdialoghelper.h: patch does not apply
error: patch failed: src/gui/painting/qpaintengine_p.h:79
error: src/gui/painting/qpaintengine_p.h: patch does not apply
error: patch failed: src/gui/text/qtextlayout.cpp:643
error: src/gui/text/qtextlayout.cpp: patch does not apply
error: patch failed: src/gui/text/qtextlayout.h:186
error: src/gui/text/qtextlayout.h: patch does not apply
error: patch failed: src/network/socket/qnativesocketengine_win.cpp:685
error: src/network/socket/qnativesocketengine_win.cpp: patch does not appl
error: patch failed: src/platformsupport/fontdatabases/basic/qbasicfontdat`

**Comment by keyvanarasteh** [comment]
@telegramdesktop can you upload or send me patched version of qtbase ??

i need that very emergency and it's not working on my system. 

thanks.

**Comment by Aokromes** [comment]
This issue is still valid? @auchri
