### ISSUE TITLE
Always keep the  emoji dialogue over the write a message box in long texts

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1575]
The problem occurs when you enter long text, especially using TDesktop in compact mode.
When you enter long text and want to make an edit with emoji, etc. the dialogue overlaps the text and impedes proper reading/editing before being sent message by the user.

*Example:*
Edit text with custom markdown with @ bold or @ formattingbot bot It becomes a complex task.

Cheers

**Long text**
![bold_results1](https://cloud.githubusercontent.com/assets/5126124/12773160/837ac3ca-ca17-11e5-8018-6c0097cd64f3.png)

**Result dialogue**
![bold_results2](https://cloud.githubusercontent.com/assets/5126124/12773171/9e83263a-ca17-11e5-9800-d55a99e566cb.png)

**Mockup**
![bold_results3](https://cloud.githubusercontent.com/assets/5126124/12773177/ac87b2c8-ca17-11e5-8fa5-5b0cf78588b3.png)

**Comment by DaFri-Nochiterov** [comment]
#1465 - I have already written about this and another issue with inline bots.

**Comment by diazbastian** [comment]
@DaFri-Nochiterov hat good news . Hopefully that is marked as a duplicate.

Note: I hope that the change is general. You also need to use emoji in long texts, etc.

Cheers
