### ISSUE TITLE
Sysetm time zone change does not change timezone within Telegram

### ISSUE THREAD

**Issue by 8191** [telegramdesktop/tdesktop#1576]
OS: Windows 7
Telegram: 0.9.18

After changing the system's timezone, Telegram keeps using the old timezone.

**Comment by rutja76** [comment]
I noticed the same. After changing the timezone, Telegram updates the time only if closed and reopened.

**Comment by erikvb** [comment]
same on windows 10

**Comment by lkaratun** [comment]
same on win8.1

**Comment by pcherednichenko** [comment]
same on LG Nexus 5X
![screen](https://cloud.githubusercontent.com/assets/19668889/22863000/0688037c-f14a-11e6-802e-575cb1dd1d81.jpg)
Try to fix by clear app data- still wrong time
And delete and reinstall app from Google Play- still wrong time
Also reboot phone

**Comment by auchri** [comment]
@pcherednichenko This repo is for telegram desktop only 😉

**Comment by pcherednichenko** [comment]
@auchri okay, I remove my comment :) sorry for mistake

**Comment by luqmanarifin** [comment]
Same on win 7 SP 1. But after changing the timezone, Telegram updates the time only if closed and reopened.

**Comment by Aokromes** [comment]
Maybe #618 ?

**Comment by jeyemwey** [comment]
> I noticed the same. After changing the timezone, Telegram updates the time only if closed and reopened.
> - @rutja76 

I had to restart my Windows until Telegram noticed the change.

**Comment by jimkohli** [comment]
You may have to mouse-right and select "Quit Telegram" (rather than just close the app) to get Telegram to pick up the timezone change.

**Comment by idevin** [comment]
Same bug on Xubutu 19.10

**Comment by lkaratun** [comment]
I think this is still not resolved

**Comment by caffeine74** [comment]
I think this is still not resolved. I am on Win 10 and my TZ is EST5EDT but timestamps in TG are UTC.

**Comment by loganrosen** [comment]
I'm still able to reproduce this issue. The timestamp in the left rail updates automatically, but not the timestamps of individual messages.

**Comment by adamel** [comment]
.

**Comment by ilya-fedin** [comment]
Why are you keeping this open? Timezone is not changed so frequently to watch for it change, I believe it's ok to restart application when timezone is changed.

**Comment by john-preston** [comment]
Well, it can be a feature request then. At least if other similar apps (Discord? Slack? Teams? Idk) work better.

**Comment by 7krasov** [comment]
Ubuntu 22.04.1 LTS
Snap package:
telegram-desktop                      4.1.1                       4116   latest/stable  telegram.desktop  -

None of
snap remove --purge telegram-desktop
or manual removal of snap package folder in user directory doesn't help

I see UTC time although mine is +0300.

As described here, the timezone was changed before
I had no such issues earlier (I suppose because the tz was correct all the time)

**Comment by ilya-fedin** [comment]
Switch from snap to the binary from https://desktop.telegram.org

**Comment by 7krasov** [comment]
@ilya-fedin thanks for your support!
I tried to use the binary app, and the timezone is correct here :+1: 

When I'm turning back to the snap (run it) I'm still having the wrong tz. Are you planning to fix it within the snap?

Thank you!

**Comment by 7krasov** [comment]
@ilya-fedin or, maybe, you can tell me where this setting is being stored for ubuntu/snap system so I could clean it and reinstall the snap again? :smile:

**Comment by ilya-fedin** [comment]
I'm afraid it's not possible, it sounds like snap runtime provided by Canonical doesn't have timezone database for timezone you've chosen on your host system

**Comment by 7krasov** [comment]
Thanks a lot, Ilya! :rocket: :muscle: 
Really, switched to another TZ in ubuntu settings and the app got this timezone well!
