### ISSUE TITLE
Cannal view Counts not update

### ISSUE THREAD

**Issue by soroushsarabi** [telegramdesktop/tdesktop#1577]
hi, 
i have problem with update channel messages view counter.after i get message with proto.getChannelDialogs i use proto.ReadHistory for mark them read.

after i check unread message with getChannelDialogs, i see 0 but nobody seen added view counter of channel messages added any more.

why not counter added my views?

**Comment by telegramdesktop** [comment]
@soroushsarabi Views are incremented by «messages.getMessagesViews» method, which is called only for messages that actually appeared on the screen.
