### ISSUE TITLE
Sent and received messages falling too far apart in maximized window

### ISSUE THREAD

**Issue by dlussky** [telegramdesktop/tdesktop#1578]
It's really hard to read history in maximized window, because messages is aligned to the sides. I suggest adding some kind of max-width to messages container, so they would stick together in the middle. The good example of what I mean is Viber desktop client ([screenshot](http://cdn.dlussky.ru/screenshots/viber_fullscreen.png))

**Comment by telegramdesktop** [comment]
@dlussky Perhaps this is better, yes. But in my opinion it is not a good layout anyway, it just is not done for the full screen / maximized window, I see no reason to use such window size at all.

**Comment by dlussky** [comment]
I have a tiling window manager and when you open a window on an empty screen - it's always maximized, and I really like that behavior. Most of the times i have multiple messengers stacked side-by-side, but it's really annoying to open another window just so Telegram would not be unreadable.
