### ISSUE TITLE
[LINUX] Installation script

### ISSUE THREAD

**Issue by jalcaldea** [telegramdesktop/tdesktop#158]
Hi!

This morning I've made an installation script for Linux version of Telegram.
I hope it will be useful to someone and tell me if you find a bug or enhancement.

You can found the script here -> [installation-script.sh](https://gist.github.com/jalcaldea/acb22b21a8c9f0728198)

**Comment by bil-elmoussaoui** [comment]
@auchri you can close this ;) as if @telegramdesktop wanted to support linux installation, they will release a deb package for distros based on debian and rpm for the ones based on fedora ;)

**Comment by auchri** [comment]
@bil-elmoussaoui thx for your help!
