### ISSUE TITLE
Could not open style classes input file 'style_classes.txt'!

### ISSUE THREAD

**Issue by shotgunner** [telegramdesktop/tdesktop#1580]
I currently follow the build instruction in the repo but when I want to run metaStyle project I got the following error:  
```sh
Could not open style classes input file 'style_classes.txt'!
```

after that when I want to build and run main Telegram project I get the following error in the QtCreator:  
```sh
 [GeneratedFiles/style_auto.cpp] Error 127
```
what is wrong ?

**Comment by telegramdesktop** [comment]
@shotgunner You don't need to run MetaStyle by your own. You need to configure and build all projects like it is told in the instructions and then build Telegram. Try to press Build -> Run qmake in Telegram project after it failed to build and then build it again (Debug configuration).

**Comment by shotgunner** [comment]
@telegramdesktop thank you  the error changed:    
```sh
/home/doomie/Documents/test/telegram-source-codes/Qt-desktop-version/tdesktop/Telegram/SourceFiles/gui/text.h:118: error: ../../../QtStatic/qtbase/src/gui/text/qfontengine_p.h: No such file or directory
 #include "../../../QtStatic/qtbase/src/gui/text/qfontengine_p.h"
                                                                 ^
```
it can't find the `qfontengine_p.h` but it already existed in my `QtBase` directory
I must change the address ??

**Comment by telegramdesktop** [comment]
@shotgunner No, you should build Qt in that path: git clone it in Libraries/QtStatic, so you have Librarise/QtStatic/qtbase/src, then apply the patch and then configure, make and sudo make install — then this file will be in that location.

**Comment by shotgunner** [comment]
@telegramdesktop I already clone QtStatic in `Libraries`  and apply patch and then I configure it. and finally make and make install it. but same error raised :disappointed:   
```sh
/home/mojtaba/Documents/test/telegram-source-codes/Qt-desktop-version/tdesktop/Telegram/SourceFiles/gui/text.h:118: error: ../../../QtStatic/qtbase/src/gui/text/qfontengine_p.h: No such file or directory
 #include "../../../QtStatic/qtbase/src/gui/text/qfontengine_p.h"
                                                                 ^
```

**Comment by telegramdesktop** [comment]
@shotgunner Do you have /home/mojtaba/Documents/test/telegram-source-codes/Qt-desktop-version/Libraries/QtStatic/qtbase/src/gui/text/ folder?

**Comment by shotgunner** [comment]
@telegramdesktop yes

**Comment by telegramdesktop** [comment]
@shotgunner Do you have /home/mojtaba/Documents/test/telegram-source-codes/Qt-desktop-version/Libraries/QtStatic/qtbase/src/gui/text/qfontengine_p.h file? I'm not sure why it does not work, because project does have ./../../Libraries/QtStatic/qtbase/include include path in Telegram.pro, so it should find this file there starting from this path.

**Comment by shotgunner** [comment]
@telegramdesktop yes I have this file `qfontengine_p.h` in this location `/home/mojtaba/Documents/test/telegram-source-codes/Qt-desktop-version/Libraries/QtStatic/qtbase/src/gui/text/`
here is section of my `telegram.pro` file:  
```sh
INCLUDEPATH += ./../../Libraries/QtStatic/qtbase/include/QtGui/5.5.1/QtGui\
               ./../../Libraries/QtStatic/qtbase/include/QtCore/5.5.1/QtCore\
               ./../../Libraries/QtStatic/qtbase/include\
               /usr/local/include/opus\
               ./SourceFiles\
               ./GeneratedFiles
```

**Comment by telegramdesktop** [comment]
@shotgunner Well, then I don't understand, why the compiler does not see this file. You can change the path so that it will find it, like absolute or something, I don't know, why it happens that way :(

**Comment by shotgunner** [comment]
@telegramdesktop after changing it to absolute address I got new error :|  
```sh
/home/mojtaba/Documents/test/telegram-source-codes/Qt-desktop-version/Libraries/QtStatic/qtbase/src/gui/text/qfontengine_p.h:52: error: private/qtextengine_p.h: No such file or directory
 #include "private/qtextengine_p.h"
                                   ^
```

**Comment by shotgunner** [comment]
@telegramdesktop I sorry to wasting your time :(

**Comment by telegramdesktop** [comment]
@shotgunner Well, then the only way is to make him see the original include path :) I don't know, re-running qmake from Qt Creator does some strange magic with relative paths from time to time there.

**Comment by shotgunner** [comment]
@telegramdesktop thank you the magic happened :open_mouth: :open_mouth: I rerunning qmake and clean all project and then rebuild after 10 mins it successfully build.
