### ISSUE TITLE
File name as time sent not downloaded

### ISSUE THREAD

**Issue by PaulNerd** [telegramdesktop/tdesktop#1586]
Hi,
this is very inconvenient to me when I'm trying to back everything up and sort it.
The file name of files sent with Telegram (except uncompressed ones), like images and audio, is the timestamp of when it was downloaded (e.g. photo_2016-02-09_12-16-46 now), even if it happened months after it was originally included in the conversation.
This can lead to huge mixups and it's time-consuming for me to rename every single file.

I'd ask to change that so that the file name reflects the original place in the conversation.
Thanks.

**Comment by telegramdesktop** [comment]
@PaulNerd This seems right, I'm not sure when this will be changed, but the sent time is definitely a better name.

**Comment by PaulNerd** [comment]
Thanks
it should be a pretty straightforward and fast change to make, I believe :-)

**Comment by PaulNerd** [comment]
Sorry to bother you... any news on this one?
I'm not familiar with Github nor Telegram code, and I don't have the time to try and find the place where the filename string is formed, otherwise I could have given it a shot.
