### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by frunc** [telegramdesktop/tdesktop#1590]
Hi. I'm using 0.9.21 dev version on windows 7. Few version before everything was fine but now I have problems. I'm not sure from what version problem started.

Telegram is installed on SDD on C drive, and I have HDD on drive D. Telegram download folder is on C drive. Startup is quick but when it starts to load conversation my HDD start spinning, and telegram is waiting for him to respond. As soon HDD start spinning everything is working fine.

**Comment by telegramdesktop** [comment]
@frunc So, how is HDD drive involved in Telegram activity? Working folder there? Appdata folder? Anything?

**Comment by frunc** [comment]
Don't know how and why did this started to happening. I reinstalled telegram and now is all back to normal. I will close this issue. If it starts to happening again I will try to check more detail and report.
