### ISSUE TITLE
All messages on one side in fullscreen

### ISSUE THREAD

**Issue by mahdiG** [telegramdesktop/tdesktop#1591]
Hi. I'm using 0.9.21 dev on Linux. All messages including mine are displayed on left side of the chat when the window is fullscreen.
![telebug](https://cloud.githubusercontent.com/assets/4989445/12953850/6b00818e-d031-11e5-8e95-046697610be3.jpg)

**Comment by telegramdesktop** [comment]
This is a feature. When the window gets wider than a specific limit it is considered that this way the messages history could be read easier than in the old layout, when your messages go to the right side. A little bit of a discussion here #1587

**Comment by CREEATION** [comment]
Hello @telegramdesktop!

I'd like to open this issue again.
Could you please make an option for this feature? :)
Some people like it on the right side of the chat window.

**Comment by peteski22** [comment]
It's not a great feature! 

I use Telegram desktop in full screen (maximized window) mode, I like having easy access to the conversations for one.

"I still can't understand why anyone on earth uses large (or even fullscreen) window for Telegram Desktop, it will be not good anyway"
https://github.com/telegramdesktop/tdesktop/issues/1587

My laptop screen is 1600x900. Full screen looked absolutely fine. Now I'm forced to manually size the window such that conversations flow left/right or just not use Telegram Desktop. :(

Regardless of the opinions about whether it's better left/right/centered etc. why not just make it configurable and leave the current behaviour as-is?

This is regarding version 0.9.24.

**Comment by CREEATION** [comment]
:+1:

**Comment by AndKan** [comment]
So, just updated to 0.9.24 and it really bothered me and all my friends. I mean, it's not like it's the worst thing in the world(it actually looks alright by all means), but I really like the old way better, with my sent messages on the other side. 

Really think there should be a configuration option to disable this feature.

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.
