### ISSUE TITLE
[Feature Request] Show avatar next to contact name in small window chat

### ISSUE THREAD

**Issue by danarrib** [telegramdesktop/tdesktop#1592]
Hello, I would contribute by adding this feature by myself, but i'm having hard time to make the solution run with the instructions provided... So I'll ask for someone to do it.

Using the small chat window while talking to multiple contacts at same time is a bit difficult because I can't distinguish between them just by the name... So it'll be great if someone can just put the contact's avatar near the contact name on the top of the Window. Just like this example:
![image](https://cloud.githubusercontent.com/assets/17026744/12960035/390f8e7e-d020-11e5-8ef4-e2c30f0e6c5f.png)

That's it. Thanks a lot.

**Comment by auchri** [comment]
Better #1415

**Comment by danarrib** [comment]
I think that's not "better". Just different. The window width is larger in this #1415 suggestion. The purpose of having a compact window is to be usable in lower resolution screens (mine is 1366x768)

I like the #1415 suggestion, but I think this behavior must be optional (by a flag in the settings section), and i think that my suggestion of avatar on top of the window must be present anyway (can also be an optional feature too).

**Comment by danarrib** [comment]
Wow guys! You did it! Thank you so much!
![image](https://cloud.githubusercontent.com/assets/17026744/14471383/b3aaf644-00c4-11e6-8d4f-3a9f31ca7046.png)
