### ISSUE TITLE
Markdown on Desktop

### ISSUE THREAD

**Issue by Derpford** [telegramdesktop/tdesktop#1593]
Odd behavior with Markdown on the Linux desktop client:
When using the @bold bot, formatting works fine. The backtick formatting works perfectly, as well.

However, using asterisks and underscores (as shown in the @bold bot's suggestions window) does not seem to work on the desktop client.

**Comment by telegramdesktop** [comment]
@Derpford Bold and italic can be done only through bot, no way to send them from user (you can check other Telegram apps), it is serverside.

**Comment by Derpford** [comment]
Is there any reason we can't have it inline?

**Comment by Derpford** [comment]
To be fair, replacing certain symbols with formatted text is kind of
advanced. But the Telegram team seems to be good at this whole coding thing.

**Comment by mg-13** [comment]
There already is partial markdown support like inline code with backticks and code blocks. I don't understand how bots are allowed to send markdown (bold, italic) and humans are not.

**Comment by nshtg** [comment]
Recently whatsapp added inline markdown support. It's feeling really odd that whatsapp is ahead on something this comfortable...

**Comment by stek29** [comment]
Anyway, even if client tries to send markdown encoded properly it will be removed by server.
So it's <kbd>api issue</kbd>.

**Comment by akaWolf** [comment]
Sounds strange.. Why not just to send a raw text through server and after at the client side do the remaining graphical work?

**Comment by sae13** [comment]
this app convert markdowns automatically 
https://github.com/UnigramDev/Unigram
