### ISSUE TITLE
[Bug] Add member item at top of channel members disappeared

### ISSUE THREAD

**Issue by alirezaaa** [telegramdesktop/tdesktop#1597]
Hi,

I have a channel which has more than 200 members. After reaching 200 members milestone, the add member item at top of channel members not showing.

**Note:** I'm using the latest version of Telegram desktop.

![screenshot 45](https://cloud.githubusercontent.com/assets/7955356/12982282/5f71b770-d0f9-11e5-9cfc-b3c26c665a1e.png)

**Comment by telegramdesktop** [comment]
@alirezaaa After 200 members you can't add any more readers by yourself, you can only share an invitation link where you like, they should join themself.

**Comment by alirezaaa** [comment]
@telegramdesktop Why did you decide to make this limitation to administrators of channels?
@auchri Please don't close issues very quickly!

**Comment by telegramdesktop** [comment]
@alirezaaa Well, this is a decision made on the server side, not a client side. The main idea is that large channels should grow by themselves, not by invitations, as I understand. Anyway, I can do nothing about that.
