### ISSUE TITLE
Crashes while opening a chat (OS X).

### ISSUE THREAD

**Issue by HashCode55** [telegramdesktop/tdesktop#1599]
Gets crashed while opening the chat with a person, not like crashes while opening every chat, only while opening chat with a specific person. 
To get it working I have to delete the conversation with that person and restart the chat.

**Comment by telegramdesktop** [comment]
Crash report (full text) will be much appreciated. Also, do you use Telegram Desktop (from https://desktop.telegram.org) or native OS X app, which is called "Telegram" in Mac App Store?

**Comment by HashCode55** [comment]
Heres the crash report - 
[CrashReport.txt](https://github.com/telegramdesktop/tdesktop/files/128763/CrashReport.txt)

And I'm using Telegram Desktop.

**Comment by telegramdesktop** [comment]
@HashCode55 This is a bug in previous version of Telegram Desktop from Mac App Store. It is fixed already in the last Mac App Store version 0.9.21 or you can download the last stable version from https://desktop.telegram.org -- usually it is more stable and works better, than the appstore version.
