### ISSUE TITLE
Invalid icon in notifications

### ISSUE THREAD

**Issue by CatWhoCode** [telegramdesktop/tdesktop#1600]
Notification box contains the incorrect icon when you receive a message from the group.
Attached screenshot shows the notification from the supergroup, but with the channel icon.
![tg_bugreport](https://cloud.githubusercontent.com/assets/1366386/13014055/cd185f24-d1d3-11e5-8ae3-453877cc22de.png)
```
Telegram 0.9.21 dev
Ubuntu 15.10 amd64 (Linux 4.2.0-28)
```

**Comment by telegramdesktop** [comment]
Thanks for your report! This will be fixed in the next version.
