### ISSUE TITLE
"Always on Visible Workspace" setting gets lost

### ISSUE THREAD

**Issue by igormp** [telegramdesktop/tdesktop#16042]
### Steps to reproduce
1. Mark the "Always on Visible Workspace" option on the pop up menu
2. Change workspace a couple times
3. Suddenly telegram won't go along with the switch

This seems to be an issue both in Gnome and Cinnamon. I haven't pinpointed an exact way to reproduce, nor have any idea where something like that would be logged. Apparently it's the same issue as #2676

### Expected behaviour
The option should be kept checked, and Telegram should follow the workspace change.

### Actual behaviour
The option seems to get lost at some time, requiring me to check it again.

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 2.6.1

**Installation source (Linux Only):** Arch's official repo

**Used theme**: Dark mode only

**Comment by ilya-fedin** [comment]
Latest version is 2.7.1, you can't report for old versions

**Comment by Aokromes** [comment]
also, try downloading the version from desktop.telegram.org or releases tab.

**Comment by igormp** [comment]
Just a follow up that I've updated to 2.7.1 (along with the latest gnome version), and the issue seems to be gone. Not sure what actually solved it, but I'm happy nonetheless :)

**Comment by igormp** [comment]
After some days, the problem has reappeared :disappointed: 

I can't find a way to properly reproduce this issue, nor can other friends that happened to suffer from the same bug.

**Comment by ilya-fedin** [comment]
probably you downgraded back to 2.6.1

**Comment by igormp** [comment]
> probably you downgraded back to 2.6.1

I wish
![image](https://user-images.githubusercontent.com/5247904/113778125-67ac3580-9702-11eb-805c-0c9951e3b5b1.png)

**Comment by ilya-fedin** [comment]
The change was reverted in 2.7.1, so this is something other
