### ISSUE TITLE
Telegram crash when trying send a lot of images

### ISSUE THREAD

**Issue by Flowelcat** [telegramdesktop/tdesktop#16044]
### Steps to reproduce
1. Open attach menu
2. Attach more than ~400 images (in my case 493), It crashed on 470 too. Sometimes more sometimes less needed to crash.
3. Wait till telegram read information about all photos

### Expected behaviour
Telegram must load images and send them. Or if needed must give me warning that i can't load more than n images

### Actual behaviour
Telegram closes completly without an error

### Configuration
**Operating system:**
Windows 10 
Version 10.0.18363 Build 18363

**Version of Telegram Desktop:**
2.7.1

**Used theme**:
Custom amoled black theme
Dark mode is on

<details><summary><b>Logs</b>:</summary>
No log, please give me advice how get to get logs on windows.
</details>

**Comment by ilya-fedin** [comment]
Probably you're hitting 32-bit RAM address limit of your OS

**Comment by john-preston** [comment]
@Flowelcat Can you please see if it is 64 bit version or not? You can open Main Menu and see on the bottom (it should say "Version 2.7.1" or "Version 2.7.1 x64").

If it is not "x64", please download x64 version from https://desktop.telegram.org or from https://github.com/telegramdesktop/tdesktop/releases and install (just over yours, no need to uninstall old one). And try again.

**Comment by Flowelcat** [comment]
@john-preston Installed x64 version. With x64 version can't reproduce this bug. Tried to send up to 844 images at once, all loading with no problems. So bug only occurs on x32 version of telegram desktop.

**Comment by ilya-fedin** [comment]
> So bug only occurs on x32 version of telegram desktop.

This is not a bug, this is the 32-bit RAM adressing limit

**Comment by john-preston** [comment]
@ilya-fedin Well, it is a bug, but unfortunately it is low priority at that point. It could be done without a crash even on 32 bit version, just no time for that, even more now, when there is an x64 version that is becoming the default on Windows.

**Comment by arisudesu** [comment]
Happened to me too. Didn't know x64 version exist. Thanks.
