### ISSUE TITLE
[Question] Login from "Lithuania" detected, even though I am in a different country

### ISSUE THREAD

**Issue by psyonara** [telegramdesktop/tdesktop#16043]
Hi, I installed the desktop app from Flathub, and once I logged in, I got a message in Telegram saying it detected a new login from Lithuania, even though I'm in South Africa.

I friend on mine has seen the same behaviour.

Is this anything I need to be concerned about, or is that expected?

Thank you.

**Comment by mydoghasworms** [comment]
I had the same experience, but with the Windows app from https://desktop.telegram.org/

I am also based in South Africa, so I expected to see the login coming from here, not from Lithuania.

![image](https://user-images.githubusercontent.com/514461/112444145-69671800-8d56-11eb-9d6e-c0041943259c.png)

For now I have disabled access from the desktop app until this can be clarified.

**Comment by Aokromes** [comment]
such issue belongs to https://bugs.telegram.org/
very likely your isp got ips from lithuania and db needs to be updated.

**Comment by mydoghasworms** [comment]
@Aokromes Thanks, I reported it as a bug.

**Comment by john-preston** [comment]
@mydoghasworms It was an address of a proxy server, but it should be better now. Please check.

**Comment by mydoghasworms** [comment]
@john-preston Thanks, I can confirm that the message now correctly identifies my location. Can you provide any more detail on the issue? Is the code in question that was changed for this fix also publicly verifiable? Regards.

**Comment by john-preston** [comment]
@mydoghasworms I don't know the details, sorry, this was a change from the server side. As I understand the proxies are used to circumvent bad connectivity or local censorship of access to Telegram servers. And it appears that at some point a proxy address was used in the notification about a new login instead of the initial user address.
