### ISSUE TITLE
Telegram homepage

### ISSUE THREAD

**Issue by freemangilgamesh** [telegramdesktop/tdesktop#16047]
How about making telegram messenger an all-in-one app?!!! I suggest you add a telegram homepage where all the news and friends' posts are. It could be the first thing you see when you launch the app.

**Comment by Aokromes** [comment]
such request belongs to https://bugs.telegram.org/

**Comment by freemangilgamesh** [comment]
no I mean a timeline-like homepage (like on fb)

**Comment by Aokromes** [comment]
platform wide feature requests belongs to that bug tracker.
