### ISSUE TITLE
context menu on wrong screen

### ISSUE THREAD

**Issue by a7lan** [telegramdesktop/tdesktop#16050]
### Steps to reproduce
1. PC with 2 monitor. 1 monitor connect to discrete GPU. 2 monitor connect integrated video card 
2. Open context menu
3. Context menu on wrong monitor

### Expected behaviour
context menu on the right screen 

### Actual behaviour
context menu on wrong screen

### Configuration
Operating system: windows 10 1809. Discrete GPU Radeon RX480. 

Version of Telegram Desktop: 2.7.1

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7099
