### ISSUE TITLE
[Feature Request] About shortcut keys to wake up and hide telegram window on Windows.

### ISSUE THREAD

**Issue by jyxjjj** [telegramdesktop/tdesktop#16058]
### Is your feature request related to a problem?
1.I want to wake up the window of telegram from taskbar and tray without mouse.
2. Shortcut keys cannot be edited if conflicted with other programs.

### Describe the solution you'd like
For 1. Use some shortcut key like Ctrl+Alt+X and so on.
For 2. Add settings on setting options. I mean all, like create links when edit.

### Describe alternatives you've considered
For 1. I tried to get the window HWND of telegram, And wake it up. I succeeded when the telegram is on taskbar, but failed on tray.
When it was on tray, i will wake a transparement window and cannot close it.
For 2. I can only edit other programs' shortcut key.

### Additional context
None.

**Comment by ilya-fedin** [comment]
There are standard Windows feature, you can set a key shortcut in start menu/desktop shortcut properties.
