### ISSUE TITLE
[Feature Request] Change application title (window title) according to active chat name (or person name)

### ISSUE THREAD

**Issue by JustACatRu** [telegramdesktop/tdesktop#16057]
### Is your feature request related to a problem?
The problem is: there is no way to distinguish by window title what chat is now active.

The purpose of this is mainly for time management software - it should be able to distinguish somehow what chat you are using now: is it some work related discussion or just a private chatting with a friend.

### Describe the solution you'd like
It would be great to have an option to set application (window) title to active chat/group name or person name.
Now app title is:
"Telegram[ (unread_count)]"
But I want to see something like this:
"[person/group/chat_title - ]Telegram[ (unread_count)]"
For example, when chat with BotFather is active:
"BotFather - Telegram (1234)"

**Comment by ilya-fedin** [comment]
#10067
