### ISSUE TITLE
Telegram Desktop Segementation Fault when using the Voice Message Feature on Arch Linux

### ISSUE THREAD

**Issue by ottersarecool** [telegramdesktop/tdesktop#16069]
### Steps to reproduce
1. Have Arch Linux installed
2. Start Telegram Desktop
3. Try to send a voice message

### Expected behaviour
It should record and send a voice message

### Actual behaviour
It crashes silently

### Configuration
**Operating system:**
Arch Linux 64bit

**Version of Telegram Desktop:**
2.7.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Arch Linux community repo

**Used theme**:
Default night mode

<details><summary><b>Logs</b>:</summary>
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
Segmentation fault (core dumped)

</details>

**Comment by ilya-fedin** [comment]
please test on the official binary from https://desktop.telegram.org

**Comment by ottersarecool** [comment]
> please test on the official binary from https://desktop.telegram.org

This worked!
