### ISSUE TITLE
Window size

### ISSUE THREAD

**Issue by SaeidNH** [telegramdesktop/tdesktop#16064]
### Steps to reproduce
1. Change Telegram window size (mostly make it bigger - bring the bottom close to taskbar and top to 1 or half inch from top)
2. Close Telegram from tray icon
3. Open Telegram desktop and you'll see the windows size is changed

### Expected behaviour
Tell us what should happen
Save window size
### Actual behaviour
Tell us what happens instead
Usually the window becomes smaller
### Configuration
**Operating system:**
Windows 10 Pro
**Version of Telegram Desktop:**
2.7.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Dark
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#1189
