### ISSUE TITLE
Will tdesktop Ever Allow Federation in Feature Requests?

### ISSUE THREAD

**Issue by dm17** [telegramdesktop/tdesktop#16068]
In the case that a (self-hosted) telegram-server comes about via community contribution: will telegram-desktop allow the contribution of feature where you can choose alternative servers to connect to? This would make it easy to switch between official telegram server and our own (or connect to both simultaneously).

Wire has wire-server including documentation & scaffolding to self host with k8s, but I realize Durov expressed disinterest in releasing telegram-server... But that was only because releasing it would not constitute proof for how the official telegram-server is working. That is true, but many people want telegram-server for other reasons - for example just being self-hosting enthusiasts.

So, for those interested in developing a telegram-server, it would be a lot more work if we learn that the official client would not allow a "server chooser feature" (and would therefore have to be forked by anyone who wanted to use their own telegram-server). Thoughts?

Thanks & much appreciated!

**Comment by Aokromes** [comment]
such request belongs to https://bugs.telegram.org/

**Comment by dm17** [comment]
> such request belongs to https://bugs.telegram.org/

Can we keep this issue unlocked for the sake of discussion, though? :)

**Comment by john-preston** [comment]
@dm17 I think that it won't be added to the UI settings because of the highly advanced nature of the feature and the percentage of users that need it. But I think it could be added in some way (as a secret code in Settings, like there are some now, or as some command line arguments or something else).

Although I don't think it should be added before some real self hosted alternatives are already working. Because while they are developed it won't be a problem for the developers to build their forks of tdesktop with replaced IPs / RSA public keys. And I'm not sure if it will go any further 🙈  Just because the task is huge.

**Comment by john-preston** [comment]
There is a per-account difference in backends right now, you can have one account logged into the main Telegram cloud and the second one to the test Telegram cloud (different IPs). There could be some secret way to add an account with a completely unrelated IPs / public keys that will work independently of other accounts.

**Comment by dm17** [comment]
@john-preston That makes sense. What do you think would be the best way to present alternative reasons to release telegram-server to Telegram? So far Durov only said it doesn't make sense to release as a proof of what their servers are running, which is true... But It could save independent devs a lot of time remaking it - and be useful in the self hosting community. I'm sure there are many reasons they could consider at least a partial release of telegram-server...

**Comment by john-preston** [comment]
@dm17 (personal opinion) I don't think that alternative clouds are a feature that would benefit Telegram itself, because it will fragment the userbase.

There is no interaction between clouds (so users of one, like the test cloud on Telegram, can't send messages to users of another, like the main cloud on Telegram), so there is no federation in that sense.

Those additional accounts, that would be located in alternative clouds, would be completely isolated in their small userbases. And the mass-market messaging app popularity and usefullness grows proportionally with its userbase and connectivity growth.

**Comment by dm17** [comment]
@john-preston I didn't realize that Telegram was only about increasing mass-market adoption... To be fair, this would be for technical users - not about launching alternative clouds to detract from the official one. Here are some reasons I think should enter into consideration:

1) Debugging for developers can be aided by the ability to (even locally) host their own telegram-server.
2) Confidence in Telegram can be increased when you have a backup server that you can use in a pinch.
3) This does & will not require a need for federation - just like Wire's wire-server & wire-client are not federated.
4) There is still no secret chat for Linux users (I suppose one could again argue that Linux doesn't matter for mass adoption, though).
5) Wire (a competitor) has released their wire-server with instructions on how to use it.
6) Telegram could increase their telegram-server code quality by releasing it (or part of it).
7) Pavel joined the World Economic Forum, which is currently publicizing a global "Great Reset" across all of their channels publicly (and specifically cite global telecommunications changes that need to be made). 
Couple this with the fact that Telegram is now HQ'd in Abu Dhabi, which gives UAE massive leverage - and this round's (150M) investor is Abu Dhabi Catalyst Partners (which is co-owned by Rick Gerson, advisor to the ruler of UAE &  Jared Kushner's friend)...

If we want to keep Telegram nice unlike Facebook, WhatsApp, and the like - then having a bit more control at least gives peace-of-mind, right? It can't always be driven amorally by increasing adoption & market capitalization.

**Comment by john-preston** [comment]
4. How is this connected to the discussion? 🤔  Open server side code is not needed for secret chats on Linux, just a lot of work.

Well, those are just my thoughts. Your points may be valid as well..

**Comment by dm17** [comment]
> 1. How is this connected to the discussion? thinking  Open server side code is not needed for secret chats on Linux, just a lot of work.
> 
> Well, those are just my thoughts. Your points may be valid as well..

Connected via the utility of a secret chat feature: to keep your clear-text messages off of a server somewhere. An alternative to keeping your messages off of someone else's server is to run your own, for example.

**Comment by wubenqi** [comment]
@dm17 

I am a developer of a third-party server (chatengine and telegramd). There is a technical problem with your idea. The newly released tdesktop app uses the latest mtproto, but the third-party server cannot support the latest mtproto in time, which will cause many problems, unless tdesktop can be compatible with the old mtproto.

**Comment by dm17** [comment]
> @dm17
> 
> I am a developer of a third-party server (chatengine and telegramd). There is a technical problem with your idea. The newly released tdesktop app uses the latest mtproto, but the third-party server cannot support the latest mtproto in time, which will cause many problems, unless tdesktop can be compatible with the old mtproto.

I think you've misunderstood the idea. The idea is for Telegram to release telegram-server; this idea is totally unrelated to your third-party server currently - but I'm happy to hear suggestions.
