### ISSUE TITLE
Mac App Store URL is broken

### ISSUE THREAD

**Issue by sgon00** [telegramdesktop/tdesktop#16066]
Hi, I am trying to download the app. But when I visit the official website https://desktop.telegram.org/ and then click the URL https://telegram.org/dl/desktop/mac_store. It will redirect to the link https://apps.apple.com/us/app/telegram-desktop/id946399090 which is 404 error. Thanks a lot.

Btw, which one in the App Store is this app? The one which has Provider `Telegram FZ-LLC` and name `Telegram Lite`?

**Comment by RememberTheAir** [comment]
> The one which has Provider Telegram FZ-LLC and name Telegram Lite?

Yes, Telegram Desktop on the AppStore is called Telegram Lite

**Comment by john-preston** [comment]
@sgon00 🤔 for me https://apps.apple.com/us/app/telegram-desktop/id946399090 is not 404, it looks like this:

![image](https://user-images.githubusercontent.com/17900494/112947992-8893ea00-9148-11eb-83bc-4aca6f3fcce9.png)

**Comment by sgon00** [comment]
@john-preston Thanks a lot for the reply. It's not 404 today. I don't know what happened yesterday and it did show 404 yesterday. I will close this issue now.
