### ISSUE TITLE
I can't log-in with my absolutely correct passcode

### ISSUE THREAD

**Issue by mevsme** [telegramdesktop/tdesktop#16061]
### Steps to reproduce
1. set passcode (in my case it's 4 latin letters)
2. logout (wait 1 hour)
3. enter passcode
4. Telegram says it's wrong

### Expected behaviour
Log in into Desktop App

### Actual behaviour
Screen that says the passcode is wrong

### Configuration
Windows 10 x64 

**Version of Telegram Desktop:**
2.71

I am 100 sure that the passcode is correct and I reseted it just today cuz I was not able to log in in the morning too.

**Used theme**:
default

<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/6217923/log.txt)
</details>

**Comment by john-preston** [comment]
By "logout" you mean Quit Telegram?

Does this happen with some other 4 latin letters, that you can share here, so I could reproduce the bug? I don't know how this can happen.

**Comment by mevsme** [comment]
I used QWES. Now I don't use lock screen and I reinstalled Telegram. This happend twice during a day and I turned passcode off. Also it was ok for pretty long time. But once I left my computer for few days and also time (winter > summer) had changed I was not able to log-in into Telegram Desktop. I will activate passcode again and check.
@john-preston

**Comment by mevsme** [comment]
I forgot about CAPS
