### ISSUE TITLE
Tray icon doesn't show telegram logo 

### ISSUE THREAD

**Issue by jawadalkassim** [telegramdesktop/tdesktop#16067]
### Steps to reproduce
1. Updated to version 2.7.1
2. launch telegram

### Expected behaviour
telegram tray icon shows telegram logo

### Actual behaviour
it's showing three dots

### Configuration
**Operating system:**
Pop OS Linux 20.10 
Gnome 3.38
Kernel 5.8

**Version of Telegram Desktop:**
2.7.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Flatpak

**Used theme**:
Tinted

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

![image](https://user-images.githubusercontent.com/48631694/112877581-9d806700-90cf-11eb-9a95-6f6aeb4fd3ac.png)

**Comment by ilya-fedin** [comment]
This looks like desynchronization between icon theme inside flatpak and on the host, so that tdesktop sees the icon and sets it, by your panel doesn't

**Comment by ilya-fedin** [comment]
> it's not related to third party extensions only, also system panel with the same issue

I don't know what do you except to hear: your panel still doesn't see the icon

**Comment by ilya-fedin** [comment]
This is a problem with you system configuration, applications and the panel are using different icon themes.

**Comment by jawadalkassim** [comment]
when changing icon theme the logo appears again, it's an issue with pop_OS icon package

**Comment by ilya-fedin** [comment]
>  it's an issue with pop_OS icon package

I guess pop_OS icon theme doesn't have icon for telegram while you (or not you, on its own) have set some different icon theme for Qt applications. You should check QT_QPA_PLATFORMTHEME value.
