### ISSUE TITLE
Opentype support missing for OpenSans

### ISSUE THREAD

**Issue by chromer030** [telegramdesktop/tdesktop#16065]
### Steps to reproduce
1. Just run telegram and watch the log in console

### Expected behaviour
Should be no such error, Google has not released any OTF for opensans.
This issue reported once here https://github.com/telegramdesktop/tdesktop/issues/5652 but not resolved yet after 3 years !
### Actual behaviour
lots of error about missing Opentype font.

### Configuration
**Operating system:**

Linux 5.11.10 Arch , KDE

**Version of Telegram Desktop:**
Latest version from this repository (I'm not using distros packages for Telegram.)

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
https://github.com/telegramdesktop/tdesktop/releases

**Used theme**:
Original Telegram

**Logs**:

````
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
QTextCursor::setPosition: Position '-1' out of range
  OpenType support missing for "DAOpenSansSemibold", script 18
  OpenType support missing for "DAOpenSansSemibold", script 14
  OpenType support missing for "DAOpenSansSemibold", script 11
  OpenType support missing for "DAOpenSansSemibold", script 16
  OpenType support missing for "DAOpenSansSemibold", script 66
  OpenType support missing for "DAOpenSansSemibold", script 12
QTextCursor::setPosition: Position '-1' out of range
QCoreApplication::postEvent: Unexpected null receiver
````

**Comment by ilya-fedin** [comment]
> This issue reported once here #5652 but not resolved yet after 3 years !

Because this warning is thrown by internal Qt code and there's nothing to fix on tdesktop side

**Comment by chromer030** [comment]
So if culprit is QT, Telegram Desktop has noting to do about it. Closing issue.
Thank you for informing.
