### ISSUE TITLE
Can't attach caption to file album, caption is sent as separate message instead

### ISSUE THREAD

**Issue by Younes-L** [telegramdesktop/tdesktop#16063]
Sending grouped photo files (file album) with caption - Causes one text-only message to be sent first.
related issue (closed) : #10192
related commit : 5277080
### Steps to reproduce
1. open any chat where you can send messages
2. attach 2 or more files including pictures
3. add caption to the message before sending it
4. check [ x ] group items

### Expected behaviour
first file should include the caption (same as tgandroid)

### Actual behaviour
caption is sent as a separate text message, and none of the files are sent with caption

### Configuration
**Operating system:** Linux Mint

**Version of Telegram Desktop:** 2.7.1 (also 2.7, 2.6.8, 2.6.3, 2.6.1)

**Installation source (Linux Only)** : GitHub releases

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

### Note
the same problem happens when sending files **without grouping** . I suppose fixing this issue would fix both problem, but let me know if i should open a second issue for sending ungrouped files.

**Comment by john-preston** [comment]
Well, if you send several files (with or without grouping) there is no way to add a single caption that will not surprise some users, so in that case it is named "Comment" and sent separately. Because adding the comment to the first file (like it is done for media albums, like albums with many photos) will be displayed under the first file, above the second -- in the middle of the album. But you've added it at the bottom of the list. Adding it to the last file will be inconsistent with the captions added to media albums.

Possible solution would be to allow to add a caption to every file separately, but right now there is no such way and I'm not sure how to do that without cluttering the send box UI.

**Comment by john-preston** [comment]
I acknowledge that there is a problem, right now it is a compromise. Perhaps it could be done better.

**Comment by Younes-L** [comment]
@john-preston i appreciate your detailed reply, here's my suggestion for how it could be done,  
![image](https://user-images.githubusercontent.com/23421600/113570507-030ab100-9604-11eb-912b-d7d3b393b5a8.png)

and i also question some of the reasons listed in your reply :
> Because adding the comment to the first file will be displayed under the first file, above the second -- in the middle of the album.

is this a problem ? it makes sense, both tgandroid and tgios do exactly this.  
Albums in telegram are just a bunch of separate messages, and because the [caption + first file] are parts of the same message, they should be displayed alongside each other. If telegram wanted the caption to be displayed at the bottom, then they would attach it to the last file instead of the first file.

> But you've added it at the bottom of the list.

this IMO is subjective. The file sending dialog could be rearranged if you think it implies last file will be captioned. From what i see, the UI doesn't explicitly specify which file will be captioned, so first file is just as valid of a guess as last file.

> Adding it to the last file will be inconsistent with the captions added to media albums.

yes, and this is why the caption should be added to the first file.

**Comment by john-preston** [comment]
@Younes-L Yes, if it is arranged like in your screenshot - then you really understand what you'll see when you send the album.

But in case it is arranged like it is right now and you see three files, then below them the input field, you write the text there, send the album and see your text jump up, right below the first of three files - this will surprise users a lot (in a bad way).
