### ISSUE TITLE
Wonky mouse behavior when inside suckless tabbed (xembed)

### ISSUE THREAD

**Issue by endigma** [telegramdesktop/tdesktop#16077]
### Steps to reproduce
1. Re parent a telegram window inside tabbed.
2. Open an image, or otherwise remove focus from the application

### Expected behaviour
Telegram client should remain functional as expected.

### Actual behaviour
Mouse alignment issues, selection doesn't work as expected, context menus for messages and files are messed up, some buttons don't do anything. This can be fixed by switching tabs within the tabbed window (go to another child window, then back to telegram), but this fix only persists until telegram loses focus again

### Configuration
**Operating system:** Linux 5.11.11_1 #1 SMP 1617136041 x86_64 GNU/Linux

**Version of Telegram Desktop:** 2.7.1

**Installation source (Linux Only)**: [void-linux package](https://github.com/void-linux/void-packages/tree/master/srcpkgs/telegram-desktop)

**Used theme**: My own

There's nothing topical whatsoever in logs.

**Comment by ilya-fedin** [comment]
> 1. Re parent a telegram window inside tabbed.

What do you mean?

**Comment by endigma** [comment]
> > 1. Re parent a telegram window inside tabbed.
> 
> What do you mean?

Make telegram-desktop a tab inside tabbed, this involves re-parenting the window. You can put telegram inside tabbed in other ways but this is how I do it so that's "how to reproduce". I re-parent using xdotool. I reckon this would also have an issue if made in other ways, so any tutorial showing how to make a tabbed setup should do.

**Comment by ilya-fedin** [comment]
> Make telegram-desktop a tab inside tabbed

tabbed what?

**Comment by endigma** [comment]
> > Make telegram-desktop a tab inside tabbed
> 
> tabbed what?

[suckless tabbed](https://tools.suckless.org/tabbed/)

here is the script I use

[hastebin](https://haste.cya.cx/ixehetinef.bash
)

**Comment by ilya-fedin** [comment]
> this involves re-parenting the window

If you're doing such low-level things, you should report to Qt instead, tdesktop uses high-level Qt APIs

**Comment by endigma** [comment]
> > this involves re-parenting the window
> 
> If you're doing such low-level things, you should report to Qt instead, tdesktop uses high-level Qt APIs

It doesn't occur with other Qt apps, only telegram.

**Comment by ilya-fedin** [comment]
> It doesn't occur with other Qt apps, only telegram.

I'm asking you to list Qt apps you've tried since people frequently can't differ Qt apps

**Comment by endigma** [comment]
> > It doesn't occur with other Qt apps, only telegram.
> 
> I'm asking you to list Qt apps you've tried since people frequently can't differ Qt apps

Teamspeak 3, QtPass, MultiMC, OBS Studio, and the Qt5Ct app to be sure.

**Comment by ilya-fedin** [comment]
> * Re parent a telegram window inside tabbed.
> 
> * Open an image, or otherwise remove focus from the application

Can't reproduce with these steps, official binary and MATE on NixOS, tdesktop appears inside tabbed and works just fine when I focus some other window and return to tdesktop

**Comment by endigma** [comment]
Is tdesktop the only window in the tabbed instance?

**Comment by ilya-fedin** [comment]
> Is tdesktop the only window in the tabbed instance?

yeah, I did only what you described.

**Comment by endigma** [comment]
Can you try putting any other window in there with it? I didn't check if another window is a necessity to reproduce.

**Comment by ilya-fedin** [comment]
I can reproduce now, but I have bad news: I have no idea what could cause this, it looks like tabbed produces incorrect events or something like that...

**Comment by endigma** [comment]
Some useful information is that there appears to be some sort of mouse offset, which may be a hint to what's causing it.

**Comment by ilya-fedin** [comment]
yeah, I see. But widgets are working with values Qt gives to them.

**Comment by endigma** [comment]
Do you reckon cross posting as a Qt5 issue is in order?

**Comment by ilya-fedin** [comment]
> Do you reckon cross posting as a Qt5 issue is in order?

i think you should involve both tabbed developers and Qt developers. There are a high chance that Qt developers will close your issue since you won't be able to provide a minimal reproducer most likely.

**Comment by endigma** [comment]
> > Do you reckon cross posting as a Qt5 issue is in order?
> 
> I think you should involve both tabbed developers and Qt developers. There are high chance that Qt developers will close your issue since you won't be able to provide a minimal reproducer most likely.

Yeah the part where something is arbitrarily wrong with tdesktop that I can't find in other apps makes it difficult to locate.

**Comment by ilya-fedin** [comment]
:man_shrugging: like I said, I have no idea

**Comment by ilya-fedin** [comment]
Something weird definitely happens not only to tdesktop. If I embed the VLC's preferences window in to tabbed, the settings tabs on top of the window lose the hover effect. tdesktop takes expensive use of Qt's positioning APIs for its rich custom widgets, so it's clear tdesktop is more affected than standard widgets users.

**Comment by endigma** [comment]
So the best idea of what's causing it right now is apps that directly use mouse position?

**Comment by ilya-fedin** [comment]
> So the best idea of what's causing it right now is apps that directly use mouse position?

Qt's widgets are using these APIs internally, but there are a lot of ways to the same thing, for instance there are multiple position APIs with relation to different anchors (e.g. global position, position relative to the window, position relative to the widget and so on). So it might be that some of these APIs working incorrectly when the window is embedded and that Qt's standard widgets are using APIs that aren't affected.

**Comment by endigma** [comment]
> Qt's widgets are using these APIs internally, ...

So how does this affect where a fix might be implemented? I assume it should be taken to Qt5? I don't think the tabbed developers can do a whole lot here given it just uses Xembed.

**Comment by ilya-fedin** [comment]
> I assume it should be taken to Qt5?

Yeah, probably

**Comment by endigma** [comment]
What version of Qt does tdesktop use internally?

**Comment by endigma** [comment]
Posted](https://bugreports.qt.io/browse/QTBUG-92364) to Qt5 Jira

**Comment by ilya-fedin** [comment]
You deleted the message, but you're not using tdesktop's Qt since you're using tdesktop from your repository. Your tdesktop uses whatever Qt version is in your distro repo.

**Comment by Aokromes** [comment]
so. close this?

**Comment by endigma** [comment]
Escalated to Qt developers
