### ISSUE TITLE
Problem with photos captions Linux

### ISSUE THREAD

**Issue by MeDeVILe** [telegramdesktop/tdesktop#1607]
When I send photo with caption, caption only appear on desktop version. The same message on mobile doesn't have caption and is send as a file.

This how it looks on desktop
![zrzut ekranu z 2016-02-14 09 50 46](https://cloud.githubusercontent.com/assets/6697190/13032801/718f1560-d301-11e5-986d-87897af38243.png)

And the same photo on mobile
![photo_2016-02-14_09-59-37](https://cloud.githubusercontent.com/assets/6697190/13032804/b1597a46-d301-11e5-9573-ba1a13c7c7d2.jpg)

Sending the other way is working
![zrzut ekranu z 2016-02-14 09 57 05](https://cloud.githubusercontent.com/assets/6697190/13032812/dade1f48-d301-11e5-945e-37922e9bc901.png)

**Comment by telegramdesktop** [comment]
@MeDeVILe And which exactly mobile app and version are you talking about?

**Comment by MeDeVILe** [comment]
Now when you said I compared Plus messenger doesn't see captions but i checked web-version and there is captions  but sending photo without compression send it as a file with captions is it normal?

Web-version same photo first compressed second send without compression
![zrzut ekranu z 2016-02-14 11 35 53](https://cloud.githubusercontent.com/assets/6697190/13033232/4e5c8b6e-d30f-11e5-9828-d7b843a4cc0c.png)

**Comment by telegramdesktop** [comment]
@MeDeVILe Well, some apps do not yet display file captions (they display only photo captions which were introduced much earlier), but all official apps should show them already or should start showing them in the near releases. So which official app do you try and don't see the caption?

**Comment by MeDeVILe** [comment]
@telegramdesktop They don't show on official android app

**Comment by MeDeVILe** [comment]
So if telegram desktop can add captions to file (unfortunately only by uploading photo) it shouldn't be hard to add possibility to send video with captions #1606 as it is in official iOS version.

**Comment by telegramdesktop** [comment]
@MeDeVILe You can add caption to any file when you copy that file in your file explorer and paste it in the message field.

Sending videos is a bit more complicated task, because you need to learn how to get video thumbnail and duration from the file and perhaps even re-encode and compress it, like iOS app does.

**Comment by MeDeVILe** [comment]
@telegramdesktop thank you very much. Everything is working and even by copy/paste I'm able to add captions to videos.

**Comment by telegramdesktop** [comment]
@MeDeVILe Well, they are not sent as videos, but welcome anyway.

**Comment by MeDeVILe** [comment]
@telegramdesktop mp4 up to 2MB are sent as videos with thumbnails and everything. Bigger are treat as files.
