### ISSUE TITLE
Group replies and @mentions use wrong notification icon

### ISSUE THREAD

**Issue by tari01** [telegramdesktop/tdesktop#16082]
### Steps to reproduce
1. Join a group
2. Post something
3. Have someone else post something
4. Have someone else post something, mentioning you (@)
5. Have someone else reply to your post

### Expected behaviour
Step 3 should use **telegram-mute-panel.svg** and not notify you
Step 4 should use **telegram-attention-panel.svg** and notify you
Step 5 should use **telegram-attention-panel.svg** and notify you

### Actual behaviour
Step 3 works as expected
Step 4 uses **telegram-mute-panel.svg** and notifies you
Step 5 uses **telegram-mute-panel.svg** and notifies you

### Configuration
Manjaro MATE
Telegram Desktop 2.7.1 (GitHub Linux 64 bit binary)

**Comment by Aokromes** [comment]
download the official version from desktop.telegram.org or releases tab.

**Comment by ilya-fedin** [comment]
I'm not sure it's a bug. This seem to be cross-platform behavior.

**Comment by tari01** [comment]
> download the official version from desktop.telegram.org or releases tab.

Updated my Telegram source, but the behaviour is the same.

**Comment by tari01** [comment]
> I'm not sure it's a bug. This seem to be cross-platform behavior.

When the group itself is muted, the notifications follow the exceptions (mentions, replies), so you get notified, as it should be. The problem is that the icon behaviour is not consistent with the notifications...

It appears the icon follows a different logic from the notification.

**Comment by ilya-fedin** [comment]
> When the group itself is muted, the notifications follow the exceptions (mentions, replies), so you get notified, as it should be. The problem is that the icon behaviour is not consistent with the notifications...

Yeah, I understood. I'm not sure this is a bug.

**Comment by ilya-fedin** [comment]
preston confirmed that the current behavior is intended
