### ISSUE TITLE
[Feature Request] Remember last opened chat

### ISSUE THREAD

**Issue by AndRo-Marian** [telegramdesktop/tdesktop#16081]
### Is your feature request related to a problem?
When I minimize the software to System Tray and after I open it again it's not remember the last selected chat.

### Describe the solution you'd like
I would like and option on settings to 'Remember chat after system tray' or by default

Windows 10

**Comment by RememberTheAir** [comment]
If you minimize telegram using the minimize icon (or CTRL+M), the next time you open it from the tray it will show exactly the same thing it was showing when you minimized the app

**Comment by AndRo-Marian** [comment]
> If you minimize telegram using the minimize icon (or CTRL+M), the next time you open it from the tray it will show exactly the same thing it was showing when you minimized the app

But I want for X or CTRL+W for System Tray icons.
