### ISSUE TITLE
Telegram-desktop does not update new messages on Linux Mint

### ISSUE THREAD

**Issue by pindos74** [telegramdesktop/tdesktop#16080]
Hello. I use Telegram-desktop 2.7.1 installed from official repository on Linux-Mint 20.1 Cinnamon. The same behavior was on previous installation from deb-package downloaded from official Telegram site. The problem is that there is no updates for my subscribed channels. I can't see new messages until I click on target channel. Also there are no notifications in the corner of the screen and no numbers of new unread messages in grey circle on the tray icon. 
I use tdesktop also on my Windows 10 PC. It work fine there. For example, I see new notification in Windows from some channel. I look at my Linux-laptop and it is quite silent. No notifications, no numbers of unread messages. And only when I click on that channel, I receive the updated information. But only for that one channel. I that way I can see, for example, 10 unread messages in Windows tray-icon, and nothing in Linux Mint. If I quit and restart Telegram on Linux the tray and chat list show the same number of messages as in Windows.
I noticed that this happened after some update. May be it was Telegram update, or may be Linux Mint. As far as I remember a month ago or something like that, everything worked fine on Linux Mint. I saw all notifications and number of unread messages.
Now I start Telegram from terminal. After some time I see these lines:

[8881:8881:0402/162020.661162:ERROR:CONSOLE(19)] "Uncaught (in promise) [object Object]", source: chrome://op-resources/modules/services/history.js (19)
[8881:8881:0402/162030.044142:ERROR:flow_session.cc(514)] Flow client is Unauthorized. Reset.
  OpenType support missing for "Open Sans", script 11

They appeared to my mind when new notifications appeared in Windows. But may be I'm mistaken.

**Comment by ilya-fedin** [comment]
> The same behavior was on previous installation from deb-package downloaded from official Telegram site.

Official Telegram site doesn't distribute deb packages. You messed something up or are a victim of phishing.

**Comment by pindos74** [comment]
> Official Telegram site doesn't distribute deb packages.

Sorry, it was long time ago. I have forgotten. I installed not a deb. I used portable version. But now I use distro-version on my laptop and on VM. The problem is still exist.

**Comment by ilya-fedin** [comment]
> But now I use distro-version

mint 20 is based on ubuntu focal that has tdesktop of version 2.0.1
https://packages.ubuntu.com/focal/telegram-desktop

But you're saying you're using 2.7.1. Something is wrong here.

**Comment by pindos74** [comment]
> But you're saying you're using 2.7.1. Something is wrong here.

yuriy@LinuxMint-cin ~ $ apt show telegram-desktop
Package: telegram-desktop
Version: 2.1.7+ds-2~ubuntu20.04.1
Built-Using: libtgvoip (= 2.4.4-2), mapbox-variant (= 1.1.6-1), ms-gsl (= 2.1.0-1), range-v3 (= 0.10.0-1), tl-expected (= 1.0.0~dfsg-2)
Priority: optional
Section: universe/net
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Nicholas Guriev <guriev-ns@ya.ru>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 45,5 MB
Depends: qt5-image-formats-plugins (>= 5.9.0), libavcodec58 (>= 7:4.2), libavformat58 (>= 7:4.2), libavutil56 (>= 7:4.0), libc6 (>= 2.29), libdbusmenu-qt5-2 (>= 0.3.2), libgcc-s1 (>= 4.0), liblz4-1 (>= 0.0~r130), liblzma5 (>= 5.1.1alpha+20120614), libminizip1 (>= 1.1), libopenal1 (>= 1.14), libopus0 (>= 1.1), libqrcodegencpp1 (>= 1.2.1), libqt5core5a (>= 5.12.2), libqt5dbus5 (>= 5.9.0), libqt5gui5 (>= 5.10.0) | libqt5gui5-gles (>= 5.10.0), libqt5network5 (>= 5.9.0), libqt5widgets5 (>= 5.9.0), librlottie0-1 (>= 0~git20200305.a717479+dfsg), libssl1.1 (>= 1.1.0), libstdc++6 (>= 6), libswresample3 (>= 7:4.0), libswscale5 (>= 7:4.0), libx11-6, libxxhash0 (>= 0.6.5), qtbase-abi-5-12-8, zlib1g (>= 1:1.1.4)
Recommends: fonts-open-sans
Homepage: https://desktop.telegram.org
Download-Size: 17,8 MB
APT-Manual-Installed: yes
APT-Sources: http://mirror.timeweb.ru/ubuntu focal-updates/universe amd64 Packages
Description: fast and secure messaging application
 Telegram is a messaging app with a focus on speed and security, it is
 super-fast, simple and free. You can use Telegram on all your devices at the
 same time — your messages sync seamlessly across any number of your phones,
 tablets or computers.

**Comment by ilya-fedin** [comment]
So it's 2.1.7, not 2.7.1. Sorry, but you can't report for old versions, please install the latest version or the issue will be closed most likely.

**Comment by pindos74** [comment]
Sorry, again. It was a mistake.

**Comment by pindos74** [comment]
But I have the problem.

**Comment by ilya-fedin** [comment]
So install the latest version

**Comment by pindos74** [comment]
I used the latest version! As I have said already. I installed distro-version today. The behavior is the same. No notifications from channels!

**Comment by ilya-fedin** [comment]
You said you're used latest version long time ago. You can't report until you install the latest version right now and check on it.

**Comment by pindos74** [comment]
I have installed it long time ago. But used it until today. There were problems even with notifications from my contacts. Now with distro-version I can see notifications from contacts, but no notifications from groups.

**Comment by Aokromes** [comment]
download the official version from desktop.telegram.org or releases tab.

**Comment by ilya-fedin** [comment]
> But used it until today.

So use it again if you want to report

**Comment by john-preston** [comment]
@pindos74 Version 2.1.7 is not working good due to server changes, so you'll need to use a later version (better the latest one, of course) to get a fix for that problem. Sorry.

**Comment by pindos74** [comment]
> so you'll need to use a later version (better the latest one, of course) to get a fix for that problem. Sorry.

I used the latest 2.7.1 until today.  I had the problems. I removed distro-version 2.1.7 now on my VM and installed the latest 2.7.1.  Now I'm waiting for the new messages on subscribed channels to see what will happen.

**Comment by pindos74** [comment]
I removed ~/.local/share/TelegramDesktop on my laptop, installed the latest version. Now all notifications in tray icon are working properly. May be the problem was in local cache. Thanks to everyone for help!
