### ISSUE TITLE
[Feature Request] [Linux] missing emoji suggestion for russian keyboard like in Windows

### ISSUE THREAD

**Issue by doctorx32** [telegramdesktop/tdesktop#16085]
### Is your feature request related to a problem?
This feature does not implemented for Linux

### Describe the solution you'd like
when typing `:`, and some cyrillic letters, suggest a related emoji. 

### Describe alternatives you've considered
switching to Latin keyboard

### Additional context
Tdesktop for Windows has this feature, it suggests related emoji for example `:лол`, `:о`, `:хд` etc

**Comment by ilya-fedin** [comment]
Can't confirm, works just fine
