### ISSUE TITLE
[Feature Request] Option to choose notification banner theme

### ISSUE THREAD

**Issue by limepixl** [telegramdesktop/tdesktop#16090]
### Is your feature request related to a problem?
Not a problem but, it would be nice to have a light theme selected while also having dark themed notification banners.

### Describe the solution you'd like
An option in the notification settings or the chat settings that enables dark notifications banners.

### Describe alternatives you've considered
A toggle "Apply theme to notifications" that is enabled by default, and when disabled, brings up the same theme customization options for banner notifications.

**Comment by Aokromes** [comment]
i doub such thing is possible.
