### ISSUE TITLE
[Feature Request] Replace icons of folders with emoji-only names with emojis themselves

### ISSUE THREAD

**Issue by Brawaru** [telegramdesktop/tdesktop#16097]
### Is your feature request related to a problem?

There's the following feature request on the Telegram feedback site: https://bugs.telegram.org/c/407.

Currently, Telegram has only a limited set of icons for folders, which is a real bummer. Not only it limits creativity, but the icons are also monochromatic and might be difficult to differentiate. 

### Describe the solution you'd like

A safe API-independent solution: if a folder has only a single emoji in its name, remove the name and replace the folder icon with this emoji.

### Describe alternatives you've considered

An alternative solution would be allowing users to set emoji as icons manually.

### Additional context

×

**Comment by ilya-fedin** [comment]
> A safe API-independent solution

Official clients can't behave differently, so such workaround solutions are usually no-go
