### ISSUE TITLE
[Feature Request] Please let me "Pin to top" as many chats as I need

### ISSUE THREAD

**Issue by ILyaCyclone** [telegramdesktop/tdesktop#16099]
"Pin to top" is a nice feature but why only 5?
Let me "Pin to top" as many chats as I need.

Currently when trying to pin 6th chat, there is an error popup, saying that maximum pinned chat number is 5.

Windows 10
Telegram Desktop 2.7.1

**Comment by RememberTheAir** [comment]
Please upvote this suggestion on the official suggestions platform: https://bugs.telegram.org/c/64

Requests that should be implemented on all clients are offtopic in this issues tracker

**Comment by ILyaCyclone** [comment]
> Please upvote this suggestion on the official suggestions platform: https://bugs.telegram.org/c/64
> 
> Requests that should be implemented on all clients are offtopic in this issues tracker

Thank you.

**Comment by Aokromes** [comment]
> "Pin to top" is a nice feature but why only 5?
> Let me "Pin to top" as many chats as I need.
> 
> Currently when trying to pin 6th chat, there is an error popup, saying that maximum pinned chat number is 5.
> 
> Windows 10
> Telegram Desktop 2.7.1

because mobile phones screen size.
