### ISSUE TITLE
Telegram desktop (Linux) randomly doesn't display subscribed channels

### ISSUE THREAD

**Issue by paul1149** [telegramdesktop/tdesktop#16107]
### Steps to reproduce
1. open Telegram desktop 2.2 on linux
2. subscribe to channels
3. close T. reopen the next day

### Expected behaviour
Tell us what should happen
should see subscribed channels

### Actual behaviour
Tell us what happens instead
randomly channels will not appear. then they will reappear days later.
a search for a subscribed channel will show it is still subscribed.

### Configuration
**Operating system:**
mx linux 19 (debian) x64

**Version of Telegram Desktop:**
2.2.0

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
official
Note: official 2.7 and 2.6 beta versions are mislabeled 2.2.0.

**Used theme**:
dark

**Comment by Aokromes** [comment]
Version of Telegram Desktop:
2.2.0

download 2.7.0 from https://github.com/telegramdesktop/tdesktop/releases they aren't misslabeled.

**Comment by C4H7Cl2O4P** [comment]
Version 2.1 for Linux has the same issue. I can see messages in my mobile Telegram which I can't see in Linux Desktop Telegram 2.1  Not all but some of them.

**Comment by Aokromes** [comment]
download 2.7.1 from releases.

**Comment by paul1149** [comment]
I see my reply by email didn't show up here. 
Thanks for the input. The Releases are labeled correctly. Even the official releases page was correct yesterday, whereas it wasn't before.
2.7.1 has been showing everything correctly for two days running now. Still need to give it more time due to the randomness of the problem, but things are looking good.
Thanks again.

**Comment by C4H7Cl2O4P** [comment]
> download 2.7.1 from releases.
Unfortunatelly I have another issue with it. https://github.com/telegramdesktop/tdesktop/issues/16111

**Comment by ilya-fedin** [comment]
> 2.7.1 has been showing everything correctly for two days running now. Still need to give it more time due to the randomness of the problem, but things are looking good.

Could the issue be closed?

**Comment by paul1149** [comment]
It's still behaving. Thanks for your help.

**Comment by paul1149** [comment]
2 weeks later, no problem. Solved.
