### ISSUE TITLE
the app only shows the private chats and are new messages on the groups.

### ISSUE THREAD

**Issue by PureNetProyect** [telegramdesktop/tdesktop#16101]
i only can see my private and bot chats, but in my other account i can see that in the groups that i have the two accounts on them are new messages

**Comment by Aokromes** [comment]
fill the template you deleted.

**Comment by PureNetProyect** [comment]
i didnt deleted anything it came in blank

**Comment by ilya-fedin** [comment]
Make sure you're running the latest version, old versions won't work correctly anymore due to server-side changes
