### ISSUE TITLE
Option to use notify-send on Linux

### ISSUE THREAD

**Issue by Arcaena** [telegramdesktop/tdesktop#1610]
On windows there's a choice to use Windows notifications in favor of Telegram's notifications style. On Linux there's no such option; it'd be great if we could have an option to use notify-send to send notifications to the user's notification server instead of Telegram's notifications.

I know that Qt supports sending notifications through libnotify on linux; it shouldn't add any dependencies for building.

**Comment by DaFri-Nochiterov** [comment]
Discussion about native linux notifications here: #91.

**Comment by telegramdesktop** [comment]
@Arcaena I'll try to use this thing some day:

https://developer.gnome.org/libnotify/0.7/NotifyNotification.html

if it uses what you want, then this will be done. If not — I'm not sure.

**Comment by auchri** [comment]
@telegramdesktop Why don't use something like https://github.com/KDE/snorenotify ? The licence of Snorenotify is also compatible with the licence of tdesktop.
