### ISSUE TITLE
[Feature Request] Telegram Reminders for scheduled calls/conversations/etc.

### ISSUE THREAD

**Issue by LyceumCorp** [telegramdesktop/tdesktop#16108]
### Is your feature request related to a problem?
Telegram is a messaging app that is widely used for personal and business conversations. (wow!)
It often happens that your interlocutor asks to call back later or write to him/her another day.
If you have a lot of personal/business contacts you can be overwhelmed by amount of **promised future calls, texts**, etc.
Of course you can just keep all this in mind or create notifications using third-party app/service. But...

### Describe the solution you'd like
If all these promises imply using of Telegram then why Telegram can't help me with that?
It will be very useful if I can just click on a chat/contact and **create a notification about a future call or event** that will pop up when the time comes. 

### Describe alternatives you've considered
Telegram reminders can help you to remember about important future conversations, calls, and keep your promises on time.

### Additional context
Let me show you an example:
- One of your business customers (imagine you have a huge amount of them) during a conversation asks to call him back in Telegram next Monday and he will be ready to discuss a deal. Second one asks to text him next Tuesday evening. Third one asks to send him actual prices next Wednesday. Plus, mother asks you to call uncle John Doe next Thursday. Etc.
- You click RMB on their contacts one by one and select from a drop down menu an option "Create a reminder".
- There you select date/time and customize a notification text for it.
- On Monday you'll receive a reminder notification about promised call to Customer 1. Notification text, for example, could be seen only by you in a chat window. For example "Call him at 9:00 AM and ask about the deal". On Tuesday, Wednesday, Thursday it all goes the same way.

**Comment by ilya-fedin** [comment]
Platform-wide feature requests belong to https://bugs.telegram.org/

**Comment by LyceumCorp** [comment]
> 
> 
> Platform-wide feature requests belong to https://bugs.telegram.org/

Thanks. Should I post it there and close here?
