### ISSUE TITLE
Impossible to remove blocked / deleted contacts from groups

### ISSUE THREAD

**Issue by NeriusTheDragon** [telegramdesktop/tdesktop#1611]
When a user blocks the group owner of a group they are both in, that group owner is thereafter unable to remove said contact from the said group.

![image](https://cloud.githubusercontent.com/assets/733248/13035478/ac327f72-d351-11e5-932f-0fcdcf240595.png)
![image](https://cloud.githubusercontent.com/assets/733248/13035480/b4ac7b30-d351-11e5-844b-be29278ea7d0.png)

The remove link is there and triggers a popup, which does nothing.

The web version throws an error about a missing parametrer:

![image](https://cloud.githubusercontent.com/assets/733248/13035473/981c8424-d351-11e5-81a7-13a231f967f0.png)

**Comment by GayDragon** [comment]
Relevant Webogram technical info:
```
Method: channels.kickFromChannel
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"USER_ID_INVALID"}
Stack: u@https://web.telegram.org/js/app.js:18:4455
https://web.telegram.org/js/app.js:18:5748
l@https://web.telegram.org/js/app.js:8:11739
https://web.telegram.org/js/app.js:8:11911
$eval@https://web.telegram.org/js/app.js:8:19316
$digest@https://web.telegram.org/js/app.js:8:17752
https://web.telegram.org/js/app.js:8:19410
a@https://web.telegram.org/js/app.js:7:2906
https://web.telegram.org/js/app.js:7:4356
n@https://web.telegram.org/js/app.js:2:16922
```

**Comment by Thanix** [comment]
The issue might have been caused by the user having removed their account.

**Comment by Aokromes** [comment]
I think this is fixed.
