### ISSUE TITLE
telegram-desktop crashes when using hardened_malloc instead of glibc-malloc

### ISSUE THREAD

**Issue by IshoAntar** [telegramdesktop/tdesktop#16112]
### Steps to reproduce
1. Install [hardened_malloc](https://github.com/GrapheneOS/hardened_malloc).
2. Add the library (`libhardened_malloc.so`) path to `/etc/ld.so.preload`.
3. Launch the app.

### Expected behaviour
The application should start normally.

### Actual behaviour
The application crashes with the message:
```
fatal allocator error: sized deallocation mismatch (small)
[1]    18162 abort (core dumped)  telegram-desktop
```

### Configuration
**Operating system:** Arch Linux, kernel `5.11.11-hardened1-1-hardened`.

**Version of Telegram Desktop:** 2.7.1

**Installation source (Linux Only)**: Distribution package.

**Used theme**: The default, i guess. i didn't modify it, yet!

**Comment by Aokromes** [comment]
i suggest you to try official package instead.

**Comment by ilya-fedin** [comment]
I don't think environments with hijacked mallocs are claimed as supported...

**Comment by IshoAntar** [comment]
@ilya-fedin Yeah, it did cause problems with other applications too (Dolphin), so I'll just use it on a case-by-case basis instead of a system-wide preloaded library.
