### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by cagv1507** [telegramdesktop/tdesktop#16113]
So-Pop--------Falha ao instalar "Telegram Desktop"

Aparece esse aviso>>>>>Esse pode ser um problema temporário ou pode ter sido causado por software externo ou compilado manualmente.

Eu tenho o so Mint/Ubuntu e não teve problema na instalação.

**Comment by Aokromes** [comment]
english plz.

**Comment by ilya-fedin** [comment]
> english plz. and restore deleted template.

These people don't answer usually... IMHO just close the issue and let him to create another one right written if he is interested in reporting/feature requesting/whatever he did.
