### ISSUE TITLE
Command line switches exist but there is no --help to learn about them

### ISSUE THREAD

**Issue by tremby** [telegramdesktop/tdesktop#16110]
I learned today from [the wiki](https://github.com/telegramdesktop/tdesktop/wiki/Command-Line-Switches) that Telegram-desktop has some command line switches. But there's no `--help`, so I long assumed there were none.

### Steps to reproduce
1. Run `telegram --help`

### Expected behaviour
Some help text is displayed, and the available options are listed. Telegram takes no other action.

### Actual behaviour
The `--help` switch is ignored and Telegram starts.

### Configuration
**Operating system:** Ubuntu

**Version of Telegram Desktop:** Don't know because there's no `--version` either. JK; 2.3.2. But seriously, add `--version` too.

**Installation source (Linux Only)** - GitHub releases

**Used theme**: n/a

**Comment by ilya-fedin** [comment]
#901
