### ISSUE TITLE
Bug: Dash/line in file names (if long enough) changes into underscore after sending to Telegram

### ISSUE THREAD

**Issue by mikkovedru** [telegramdesktop/tdesktop#16114]
### Steps to reproduce
1. Save this file on your computer:
[2021-04-10_text_file_test_file_test_file_test_file_test_buggy.txt](https://github.com/telegramdesktop/tdesktop/files/6290000/2021-04-10_text_file_test_file_test_file_test_file_test_buggy.txt)

2. Send the file to your Telegram's Saved Messages.
3. See a bug already:
3a) The file-sending window is fine. 
![image](https://user-images.githubusercontent.com/2521942/114273062-54120f00-9a21-11eb-87af-4d1d70688cd1.png)
3b) The name also shows properly in the chat
![image](https://user-images.githubusercontent.com/2521942/114273097-80c62680-9a21-11eb-9545-1beebf88d407.png)
3c) But the bug can already be seen from the preview of the last message:
![image](https://user-images.githubusercontent.com/2521942/114273111-920f3300-9a21-11eb-8774-03077036c6c4.png)
3d) And when trying to save the file, the file name suggestion is also wrong:
![image](https://user-images.githubusercontent.com/2521942/114273165-c71b8580-9a21-11eb-9406-a27a519bf405.png)

The length of the file's name influences the bug. The file above is the shortest one (65 chars) with which the bug is present. If only one character is removed (65 chars -> 64 chars), the bug disappears. Example: 
[2021-04-10_text_file_test_file_test_file_test_file_test_work.txt](https://github.com/telegramdesktop/tdesktop/files/6290008/2021-04-10_text_file_test_file_test_file_test_file_test_work.txt)

### Expected behavior
The file name stays consistent always:
1. the original file
2. inside the Telegram 
3. when saved from Telegram

### Actual behavior
Dash/line changes into an underscore if the file name is long enough.

### Configuration
**Operating system:**
Linux Mint Cinnamon 20.1

**Version of Telegram Desktop:**
2.7.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
apt

**Comment by ilya-fedin** [comment]
It changes in the message after application restart as well. Probably a server-side replace?

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
