### ISSUE TITLE
When you export chats with RTL messages containing LTR words, the words will have bad order. 

### ISSUE THREAD

**Issue by Mehrshad3** [telegramdesktop/tdesktop#16120]
### Steps to reproduce

1. In a group type messages in RTL direction like
    1. <code><span dir="rtl">سلام hello درود</span></code>
    2. <code><span dir="rtl">سلام👋</span></code>
    3. <code><span dir="rtl">با پاپیتا میتوانی به جمله <span dir="ltr">What is خرمالو in English?</span> جواب بدهی.</span></code> that contains:
        1. <code>با پاپیتا میتوانی به جمله</code>
        2. Start of left-to-right embedding
        3. <code>What is خرمالو in English?</code>
        4. Pop directional formatting
        5. <code dir="rtl">جواب بدهی.</code>
2. Export the chat history in HTML.

### Actual/Unexpected behavior

It shows the messages incorrectly as shown in the photo:
![current order of the words](https://user-images.githubusercontent.com/75848143/114344393-fdb5e500-9b74-11eb-968c-92a8b609763a.png)
HTML texts are:

<pre><code>       &ltdiv class="text"&gt
سلام hello درود
       &lt/div&gt</pre></code>

<pre><code>       &ltdiv class="text"&gt
سلام👋
       &lt/div&gt</pre></code>

<pre><code>       &ltdiv class="text"&gt
با پاپیتا میتوانی به جمله  What is خرمالو in English?  جواب بدهی.
       &lt/div&gt</pre></code>

### Describe the solution you'd like

I don't know HTML too much but 1 solution that I know is using span.

<pre><code>       &ltdiv class="text"&gt
&ltspan dir="rtl"&gtسلام hello درود&lt/span&gt
       &lt/div&gt</code></pre>

<pre><code>       &ltdiv class="text"&gt
&ltspan dir="rtl"&gtسلام👋&lt/span&gt
       &lt/div&gt</code></pre>

<pre><code>       &ltdiv class="text"&gt
&ltspan dir="rtl"&gtبا پاپیتا میتوانی به جمله &ltspan dir="ltr"&gtWhat is خرمالو in English?&lt/span&gt جواب بدهی.&lt/span&gt
       &lt/div&gt</code></pre>
and also I think solving this issue is related to the [bidi algorythm](https://www.unicode.org/reports/tr9/).

### Configuration

**Operating system:** PC 32bit, Windows 7

**The version of Telegram Desktop:** 2.7.1

**Used theme:** Classic

**Comment by saman1337** [comment]
hello
you can use my edited css file
just copy/paste css and the font inside css folder in the exported chat files
[custom css.zip](https://github.com/telegramdesktop/tdesktop/files/6750537/custom.css.zip)

**Comment by cben** [comment]
Saman's CSS uses `direction: rtl;` and `	text-align: right;` which may only be OK if you communicate _purely_ in Arabic.

It's better to drop those lines and instead add `unicode-bidi: plaintext;`.  [Spec](https://drafts.csswg.org/css-writing-modes/#bidi-algo)
* This makes browser autodetect base direction by first strong char.
* Better yet, it does that line-by-line, similar to Telegram (at least on Android and Desktop), which is best weapon we users have to make mixed texts legible...

Here is screenshot of some mixed text from export with default (LTR) style:
(I'm on Telegram 2.7.1 on Linux, viewed with Chrome 92)
![Ekrankopio de 2021-09-03 13-25-15](https://user-images.githubusercontent.com/273688/131990974-5321cc3a-c5bd-4ccc-adef-ed03f7629368.png)

Same with `unicode-bidi: plaintext;`:
![Ekrankopio de 2021-09-03 13-34-18](https://user-images.githubusercontent.com/273688/131992500-3c06496d-e83e-4bc2-8519-c054f855c29f.png)
Note how the equation on its own line had inferred LTR direction!
In exported HTML, I see Telegram used `<br>` tags, which according to the spec are "forced paragraph break"s making the lines separate "bidi paragraph"s, with direction heuristics applied to each one:
```
... אתה כבר מכיר את ההגדרה<br>e^{ix} = cos(x) + i*sin(x)<br>נכון? ...
```

- BTW, if you add `text-align: right;` that would force the equation to still be right-aligned.  It'd still be correctly ordered as LTR line — that's _separate question_ from alignment — but less convenient to reader.  Anyway Telegram itself does align lines separately according to detected direction, so exported HTML should do the same — omit `text-align`, or explicitly set `text-align: start`.  (start/end in CSS mean left or right according to direction)

**Comment by cben** [comment]
Opened PR #16893 :pray:
