### ISSUE TITLE
Search and Shared Content do not show messages before the 1 million cutoff (messages before can only be seen using the calendar)

### ISSUE THREAD

**Issue by Terrydaktal** [telegramdesktop/tdesktop#16128]
When I hit the 1m limit in 2019, every few months the count of media sent in each chat would drastically drop a few thousand, and the messages would not longer be searchable in the search history or accessible via the calendar.

Since this has been fixed, I have been able to access everything via the calendar, and only the number of audio files sent is accurate and goes back to the earliest date. The number of photos and voice messages in chats however keeps decreasing sharply every few months still and these are no longer viewable in the media page and the messages are no longer searchable in the search. They can only be accessed by going to a specific date on the calendar. I'd say it happens every 10 months or so, and my searchable history snaps from about 4 years to 3 years from the current date.

It is possible that this is only happening to people who triggered the 1m cutoff in the first place, and people who never reached it before the cutoff was removed are not experiencing this continual decrease, but I might be wrong.

Don't close this issue until you've got it through to Telegram's god awful support service (for anything other than the telegram desktop client because there's a github), because this is a server and client-wide issue.

This is a major issue and major functionality loss and all current updates are addressing pointless matters.

**Comment by GST998** [comment]
1
