### ISSUE TITLE
[Question] How can I find administrators and creators on the telegram groups?

### ISSUE THREAD

**Issue by wajika** [telegramdesktop/tdesktop#16139]
I don't find any obvious mark to distinguish administrator from user. Is there such a design in telegram?

**Comment by RememberTheAir** [comment]
In the members list, administrators will have a star next to their name

**Comment by wajika** [comment]
@RememberTheAir Hello , I am glad you can reply to me.

If there are a lot of people in the group, how can I find the administrator quickly? If the administrator account is deleted, will the rights be automatically transferred to another account?
I want to make a suggestion, can I automatically put the administrator account on top?

**Comment by RememberTheAir** [comment]
> If there are a lot of people in the group, how can I find the administrator quickly?

There is no other quick way of doing it from telegram desktop

> If the administrator account is deleted, will the rights be automatically transferred to another account?

There is no automatic inheritance of admin/creator privileges in place as of now. If the only administrator deleted their account, then there's no way to promote another admin

**Comment by wajika** [comment]
@RememberTheAir 

I have a lot of groups with nearly 1000 + people. It takes a lot of time to find them one by one

**Comment by RememberTheAir** [comment]
Yeah I know, but there's no way to do it, I don't know what to tell you. Maybe use [Kotatogram](https://t.me/kotatogram), it allows to see the administrators list right away without having to scroll the members list

**Comment by wajika** [comment]
> Yeah I know, but there's no way to do it, I don't know what to tell you. Maybe use [Kotatogram](https://t.me/kotatogram), it allows to see the administrators list right away without having to scroll the members list

I installed kotatogram. It's really easy to use. 
Thank you.

**Comment by wajika** [comment]
![image](https://user-images.githubusercontent.com/17058349/115007980-2c1d2280-9edd-11eb-916e-d353e1e7205d.png)
I encountered the problem mentioned above, the administrator account has been deleted, no one can manage the group?

**Comment by RememberTheAir** [comment]
Yes, you should create a new one

**Comment by wajika** [comment]
> Yes, you should create a new one

Is there any way to get control of this group?

**Comment by Aokromes** [comment]
> > Yes, you should create a new one
> 
> Is there any way to get control of this group?

no, he must transfer group before delete account.

**Comment by wajika** [comment]
> > > Yes, you should create a new one
> > 
> > 
> > Is there any way to get control of this group?
> 
> no, he must transfer group before delete account.

ok

**Comment by RememberTheAir** [comment]
> Is there a way to add a bot to this group?

If the permission to add new members is enabled for everyone, yes. But it cannot be promoted to administrator. You cannot have someone to administrate the chat if the only account with the ability to promote new administrators has been deleted. Your only solution is to create a new group

**Comment by wajika** [comment]
> > Is there a way to add a bot to this group?
> 
> If the permission to add new members is enabled for everyone, yes. But it cannot be promoted to administrator. You cannot have someone to administrate the chat if the only account with the ability to promote new administrators has been deleted. Your only solution is to create a new group

OK, thank you for your reply.
