### ISSUE TITLE
screen flickering when opening media window

### ISSUE THREAD

**Issue by ixzh** [telegramdesktop/tdesktop#16134]
### Steps to reproduce
1. launch telegram desktop 2.7.1
2. open any image, which works as expected;
3. `Esc` to close the media, and reopen it or any other media

### Expected behaviour
The same full screen window shall appear, with no flickering

### Actual behaviour
a separate rendering window opens, which flicks.

### Configuration
**Operating system:**
Arcolinux with xmonad window manager
**Version of Telegram Desktop:**
2.7.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
AUR
**Used theme**:
gtk?
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

https://user-images.githubusercontent.com/14981695/114613961-87c98f00-9cd6-11eb-9f60-e19e3e9df8cb.mp4

**Comment by ixzh** [comment]
It seems like the first opening of any media, telegram is calling external programme to render the full frame media windows, as I notice the cpu usage by telegram doesn't spike.

whereas any subsequent opening, telegram itself is rendering the image/video, causing telegram cpu usage to spike. (from like 1% to 20%).

that's my observation from CPU usage by telegram alone.

**Comment by ilya-fedin** [comment]
#10599

**Comment by ixzh** [comment]
> #10599

Many thanks! doFloat works
