### ISSUE TITLE
[Feature Request] Different speed of playing audio messages

### ISSUE THREAD

**Issue by maxiv** [telegramdesktop/tdesktop#16138]
### Is your feature request related to a problem?
Very often needed increase speed of playing audio messages, but x2 is too much for it and hard to understand.

### Describe the solution you'd like
Add buttons x1.25, x1.5 to audio bar.

### Describe alternatives you've considered
Add element with slider for set speed from x1 to x2.

**Comment by Nirzak** [comment]
Nice Idea. Moreover, this idea can be implemented on telegram audio and video players also. Especially on video players.

**Comment by 23rd** [comment]
> Especially on video players.

But it is already implemented.

**Comment by Nirzak** [comment]
> > Especially on video players.
> 
> But it is already implemented.

But I have checked. There's no such option to speed up the playback!

**Comment by 23rd** [comment]
<details>

![image](https://user-images.githubusercontent.com/4051126/115928954-a0ccff80-a48f-11eb-857f-72c5b14c291c.png)
</details>

**Comment by Nirzak** [comment]
Oh yeah! My bad. So it's only audio streaming where playback speed is not available. But on android telegram, playback speed for video is not available
