### ISSUE TITLE
ERROR: opus not found using pkg-config

### ISSUE THREAD

**Issue by cyberfriend-d** [telegramdesktop/tdesktop#16130]
### Steps to reproduce
cd C:\TDBUILD\
SET PATH=%cd%\ThirdParty\Strawberry\perl\bin;%cd%\ThirdParty\Python27;%cd%\ThirdParty\NASM;%cd%\ThirdParty\jom;%cd%\ThirdParty\cmake\bin;%cd%\ThirdParty\yasm;%PATH%
cd C:\TDBUILD\Libraries\win64
git clone https://github.com/telegramdesktop/opus.git
cd opus
git checkout tdesktop
cd win32\VS2015
msbuild opus.sln /property:Configuration=Debug /property:Platform="x64"
msbuild opus.sln /property:Configuration=Release /property:Platform="x64"

cd ..\..\..\..\..
SET PATH_BACKUP_=%PATH%
SET PATH=%cd%\ThirdParty\msys64\usr\bin;%PATH%
cd Libraries\win64

git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg
cd ffmpeg
git checkout release/4.2

set CHERE_INVOKING=enabled_from_arguments
set MSYS2_PATH_TYPE=inherit
bash --login ../patches/build_ffmpeg_win.sh

### Expected behaviour
Compiled ffmpeg

### Actual behaviour
ERROR: opus not found using pkg-config

### Configuration
**Operating system:**
Windows 10 Pro 20H2 19042.746

**Version of Telegram Desktop:**
actual x64

<details><summary><b>Logs</b>:</summary>
[config.log](https://github.com/telegramdesktop/tdesktop/files/6302118/config.log)
</details>

**Comment by tedmosbious** [comment]
@cyberfriend-d Did you solve this issue?
I have a same problem too?

**Comment by cyberfriend-d** [comment]
> 
> 
> @cyberfriend-d Did you solve this issue?
> I have a same problem too?

No, but I have walkaround solution:
**1.** Go to **_BuildPath_\Libraries\patches**
**2.** Open **build_ffmpeg_win.sh**
**3.** Delete **--enable-libopus** option.

Already logged in from a compiled client, everything works well.

**Comment by john-preston** [comment]
@cyberfriend-d 🤔 libopus was required to add opus encoder that is used when you send voice messages. Are they working?

**Comment by cyberfriend-d** [comment]
> 
> 
> @cyberfriend-d 🤔 libopus was required to add opus encoder that is used when you send voice messages. Are they working?

There was no sound card in my VM, but I have tested now:
[2021.04.16 13:14:53] Audio Error: Unable to avcodec_find_encoder for capture

I can listen, but can't record voice messages...

**Comment by imbushuo** [comment]
It's a bug in upstream dependency declaration. Currently a usable workaround is:
1. Go to your libopus build artifact directory
2. Copy any library, for instance `opus.lib`, paste and rename it to `ssp.lib`.

**Comment by john-preston** [comment]
@imbushuo I had to make a workaround for 'm' library in Windows build, because ffmpeg in msys wanted 'libm', although it is not needed on Windows. I've added an empty static library 'm'. Does it mean I need to add an empty static library 'ssp' as well?

**Comment by john-preston** [comment]
I've added 'ssp' library to telegramdesktop/opus repository. Can you please try once again (starting with building opus) the ffmpeg build from instructions?

**Comment by john-preston** [comment]
@cyberfriend-d

**Comment by cyberfriend-d** [comment]
> 
> 
> I've added 'ssp' library to telegramdesktop/opus repository. Can you please try once again (starting with building opus) the ffmpeg build from instructions?

Just tried it on x86, compiled successfully, thanks!

**Comment by soliloqueen** [comment]
On x86_64, build will still fail this way unless
`--extra-ldflags="-libpath:$FullExecPath/../opus/win32/VS2015/Win32/Release"`
in build_ffmpeg_win.sh
is changed to
`--extra-ldflags="-libpath:$FullExecPath/../opus/win32/VS2015/x64/Release"`
