### ISSUE TITLE
[Feature Request] Add a privacy setting to hide our profile from global search

### ISSUE THREAD

**Issue by Nirzak** [telegramdesktop/tdesktop#16131]
### Is your feature request related to a problem?
When we use a specific username, anyone can find us through the telegram global search. It can be a severe privacy risk, especially for female users. People can search and send them spam messages.

### Describe the solution you'd like
An option on the privacy setting to set our profile private from global search so that we can decide who can find us by our username.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by Nirzak** [comment]
Ok sir!

**Comment by Muaath5** [comment]
Simply: Don't add a username to youself, Or remove it.

You can see [Who can message me?](https://telegram.org/faq?setln=en#q-who-can-contact-me) in [Telegram FAQ](https://telegram.org/faq).
> If you set a **[public username](https://telegram.org/faq?setln=en#usernames-and-t-me)**. Others can use **Global Search** and find you by your username.
