### ISSUE TITLE
Double click to select a word doesn't work

### ISSUE THREAD

**Issue by mahdiG** [telegramdesktop/tdesktop#1613]
Hi. I'm using 0.9.22 dev on Linux. Double clicking on a word to select(highlight) doesn't work. But clicking and hovering on a word works fine and highlights the word.

**Comment by DaFri-Nochiterov** [comment]
Can't confirm it.

**OS**: Linux Ubuntu 15.10
**DE**: Cinnamon 2.6.13

**Comment by mahdiG** [comment]
I don't have the issue in 0.9.23 anymore

**Comment by telegramdesktop** [comment]
Yes, should be fixed in 0.9.23
