### ISSUE TITLE
Avoid to open sticker panel on mouse hover

### ISSUE THREAD

**Issue by ivmazurenko** [telegramdesktop/tdesktop#16142]
**Steps to reproduce**

Try to click on your message in a desktop application
Accidentally hover a mouse over sticker panel

**Expected behaviour**

The sticker has not been sent.

**Actual behaviour**

The sticker was sent.

**Configuration**

Operating system:
any
Version of Telegram Desktop:
any
Used theme:
any

**Comment by ivmazurenko** [comment]
This is how it looks like

![72677681-a62ae580-3aa7-11ea-8f29-2cf32422a31d](https://user-images.githubusercontent.com/34516127/114711998-e40ccd00-9d2f-11eb-9c8e-1b7c7400cca0.gif)

**Comment by ilya-fedin** [comment]
#1333 #7808

**Comment by ivmazurenko** [comment]
Why do you closed this bug? 

Several times i have send stickers and emojies  accidentally to my teammates. This hovering panel should be at least configurable???

**Comment by ilya-fedin** [comment]
> Why do you closed this bug?

![изображение](https://user-images.githubusercontent.com/17829319/116778545-0a39a900-aa62-11eb-950a-d7a100da1ae4.png)
