### ISSUE TITLE
how to create setup file[Question] 

### ISSUE THREAD

**Issue by 0xNima** [telegramdesktop/tdesktop#16143]
Hi
How can I create setup file from existing solution?

**Comment by Aokromes** [comment]
you must compile, then you need to use some installer creator for example NSIS.

**Comment by 0xNima** [comment]
> you must compile, then you need to use some installer creator for example NSIS.

I installed NSIS extension. should I create a new NSIS project under Telegram solution? or just create Script.nsi under Telegram project and rebuild?
