### ISSUE TITLE
Right side of screen cut off (Librem 5 Evergreen + PureOS Byzantium)

### ISSUE THREAD

**Issue by stephen304** [telegramdesktop/tdesktop#16149]
### Steps to reproduce
1. Install telegram-desktop on the Purism Librem 5 Byzantium repo
2. Open app

### Expected behaviour
App should fit on the screen

### Actual behaviour
App is cut off on the right side
![image](https://user-images.githubusercontent.com/981915/115034796-e3904580-9e99-11eb-8e52-604db0e975b5.png)
![image](https://user-images.githubusercontent.com/981915/115034986-15a1a780-9e9a-11eb-9490-066de3e86532.png)
![image](https://user-images.githubusercontent.com/981915/115035537-ab3d3700-9e9a-11eb-9476-14853e985c6a.png)

### Configuration
Librem 5 Evergreen, running Byzantium

**Version of Telegram Desktop:**
2.6.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
http://repo.pureos.net/pureos
```
Package: telegram-desktop
Version: 2.6.1+ds-1
Built-Using: libtgowt (= 0~git20210124.be23804+ds-3), libtgvoip (= 2.4.4+git20210101.13a5fcb+ds-2), ms-gsl (= 3.1.0-4), range-v3 (= 0.11.0-1), tl-expected (= 1.0.0~dfsg-2)
Priority: optional
Section: net
Maintainer: Nicholas Guriev <guriev-ns@ya.ru>
Installed-Size: 60.4 MB
Depends: qt5-image-formats-plugins (>= 5.9.0), libavcodec58 (>= 7:4.2), libavformat58 (>= 7:4.2), libavutil56 (>= 7:4.0), libc6 (>= 2.29), libdbusmenu-qt5-2 (>= 0.3.2), libgcc-s1 (>= 4.2), libgdk-pixbuf-2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.35.9), libgtk-3-0 (>= 3.21.4), libhunspell-1.7-0, libjpeg62-turbo (>= 1.3.1), libkf5waylandclient5 (>= 4:5.1.1+git20141128.0009), liblz4-1 (>= 0.0~r130), liblzma5 (>= 5.1.1alpha+20120614), libminizip1 (>= 1.1), libopenal1 (>= 1.14), libopus0 (>= 1.1), libqrcodegencpp1 (>= 1.2.1), libqt5core5a (>= 5.15.1), libqt5dbus5 (>= 5.14.1), libqt5gui5 (>= 5.15.1) | libqt5gui5-gles (>= 5.15.1), libqt5network5 (>= 5.15.1), libqt5waylandclient5 (>= 5.10.1), libqt5widgets5 (>= 5.15.1), librlottie0-1 (>= 0~git20200305.a717479+dfsg), libssl1.1 (>= 1.1.0), libstdc++6 (>= 9), libswresample3 (>= 7:4.0), libswscale5 (>= 7:4.0), libx11-6, libxcb-keysyms1 (>= 0.4.0), libxcb-record0, libxcb-screensaver0, libxcb1, libxxhash0 (>= 0.6.5), qtbase-abi-5-15-2, qtwayland-client-abi-5-15-2, zlib1g (>= 1:1.1.4)
Recommends: fonts-open-sans
Homepage: https://desktop.telegram.org
Download-Size: 21.5 MB
APT-Manual-Installed: yes
APT-Sources: http://repo.pureos.net/pureos byzantium/main arm64 Packages
Description: fast and secure messaging application
 Telegram is a messaging app with a focus on speed and security, it is
 super-fast, simple and free. You can use Telegram on all your devices at the
 same time ?? your messages sync seamlessly across any number of your phones,
 tablets or computers.

```

**Used theme**:
Default theme

Maybe it just needs the minimum width to be decreased a bit, because it almost works perfectly out of the box.

**Comment by Aokromes** [comment]
duplicate, and unsupoorted device.

**Comment by stephen304** [comment]
Ouch. I guess the solution is a small patch downstream then. Seems like such a minor thing to tweak.

**Comment by Aokromes** [comment]
a workaround can be run telegram on sub 100% scale.

**Comment by stephen304** [comment]
> a workaround can be run telegram on sub 100% scale.

Are there supposed to be options below 100%? Maybe 2.6.1 doesn't have that option yet? 

![image](https://user-images.githubusercontent.com/981915/115039914-e3df0f80-9e9e-11eb-917a-5bd60a0ceb52.png)

**Comment by Aokromes** [comment]
> > a workaround can be run telegram on sub 100% scale.
> 
> Are there supposed to be options below 100%? Maybe 2.6.1 doesn't have that option yet?
> 
> ![image](https://user-images.githubusercontent.com/981915/115039914-e3df0f80-9e9e-11eb-917a-5bd60a0ceb52.png)

it's command line option, maybe you can send a patch to the maintainer to allow 90% scale without have to run telegram on command line.

**Comment by stephen304** [comment]
> it's command line option, maybe you can send a patch to the maintainer to allow 90% scale without have to run telegram on command line.

Is there any documentation for the CLI options? Running telegram-desktop -h / --help doesn't seem to show any info, and the docs folder in this repo doesn't seem to include any CLI flags info either.

**Comment by Aokromes** [comment]
> > it's command line option, maybe you can send a patch to the maintainer to allow 90% scale without have to run telegram on command line.
> 
> Is there any documentation for the CLI options? Running telegram-desktop -h / --help doesn't seem to show any info, and the docs folder in this repo doesn't seem to include any CLI flags info either.

https://github.com/telegramdesktop/tdesktop/wiki/Command-Line-Switches

**Comment by ilya-fedin** [comment]
> Seems like such a minor thing to tweak.

It's not, actually. Minimum size hints are for a reason here, the design is not so adaptive. tdesktop needs a redesign to work on such small screens and just changing the hints will lead to artifacts (it's 100% known, someone did such a PR in the past). There's no intent to support mobile screens in tdesktop AFAIK, so it's unlikely someone redesign tdesktop for such a niche use.

**Comment by stephen304** [comment]
> It's not, actually. Minimum size hints are for a reason here, the design is not so adaptive. tdesktop needs a redesign to work on such small screens and just changing the hints will lead to artifacts (it's 100% known, someone did such a PR in the past). There's no intent to support mobile screens in tdesktop AFAIK, so it's unlikely someone redesign tdesktop for such a niche use.

My mistake, the desktop app looks identical to the android app, so you can understand why people might think it's also supposed to work when resized narrow. If the android app already works on an identical screen size, maybe some hints could be taken from there. It seems like you could just adjust the design the same way android does for a 5 inch screen.

**Comment by ilya-fedin** [comment]
> maybe some hints could be taken from there

android app is a completely separate app written in java

**Comment by stephen304** [comment]
> android app is a completely separate app written in java

I mean design-wise, not code-wise. I don't think it would necessarily require a redesign since this app already shares the same design as the android app. So there should be enough space to fit it on the same screen as the android app without reworking the design, but instead by finding discrepancies and bringing the apps closer to parity. Maybe it's just a matter of a few components on the desktop app being given too much space compared to the android app.

**Comment by ilya-fedin** [comment]
> I mean design-wise, not code-wise.

This doesn't change the fact that there's no intent to work on it

**Comment by stephen304** [comment]
> This doesn't change the fact that there's no intent to work on it

Sorry if I'm not fully understanding, but it seemed like the blocker was an uncertainty about whether it's possible to fix the issue without a major redesign. If that's why there's no intent to work on it, then perhaps if an easier solution by tweaking the existing design is possible, then maybe it won't be too much work to make a fix. It would really make the app seem more polished instead of having things slightly cut off on every screen.

**Comment by ilya-fedin** [comment]
tdesktop being an official app is developed in a proprietary-like process. AFAIK the designer team gives @john-preston a ready mockup and he can't change anything in it. The community can't contact the designer team and propose changes to the design. It seems to me the only way to port tdesktop to mobile Linux world is to fork it.

**Comment by stephen304** [comment]
I see, I wasn't aware of that process limitation. In that case it's probably easier to just use a different client. Thanks for the pointers :+1:
