### ISSUE TITLE
Trick used to make users unable to leave channel

### ISSUE THREAD

**Issue by ebraminio** [telegramdesktop/tdesktop#1614]
It seems some channels are incorporating some tricks to make users unable to leave a channel by filling description of a channel by blank lines. The attached screenshot shows fake leave channel text which tries to mimic telegram desktop UI but with unclickable links to make users think the channel is not leave-able at all (you can guess the join to these channels also were without user consent at the first hand...). Also some other channels just have blank lines without unclickable mock UI just to put actual leave channel buttons out of user sight. I guess you should eventually use some height limitation for description other than better space trimming strategy which Telegram Desktop doesn't seem to have neither of them.
![a](https://cloud.githubusercontent.com/assets/833473/13060174/dd5bcd08-d444-11e5-9b39-fd7e0050c138.png)

**Comment by DaFri-Nochiterov** [comment]
Leave by click button in the context menu?
![image](https://cloud.githubusercontent.com/assets/10401817/13072177/f13cb490-d4c1-11e5-805d-6a0667c0effe.png)

**Comment by ebraminio** [comment]
That is a way of course but I was just reporting a thing a confused user was describing to me that he is unable to leave some channels and then I found the trick being used by those channels.

**Comment by emadgh** [comment]
Just scroll down :palm_tree: :disappointed:

**Comment by stek29** [comment]
Why is it bug?

**Comment by ebraminio** [comment]
Well, because it is doing its job on confusing the user I met well, also it is an effective trick, that's why it is still in use.

**Comment by auchri** [comment]
imho that's an api issue, because the blank lines should be already filtered by the servers.

**Comment by ebraminio** [comment]
I don't know if that is done already or not but that seems also easy to be tricked by putting invisible characters on each line.

**Comment by stek29** [comment]
@auchri Same as empty names and RTL magic -- "Kids are playing with Unicode"

**Comment by stek29** [comment]
@ebraminio Any channels that use it?

**Comment by ebraminio** [comment]
Not now perhaps but also not hard to imagine to see when you block the simplest trick.

**Comment by stek29** [comment]
Ok I'll made one then)

**Comment by ebraminio** [comment]
^ Nice, quite effective for Android client also :)

**Comment by ebraminio** [comment]
Also worth to be noted I saw another channel that was using dots so filtering unicodes wouldn't be the fight you gonna win eventually, but maybe limiting total new lines to a number, maybe 5, and converting the rest to space, would be a thing that could be done serverside also I'd guess.

**Comment by stek29** [comment]
I think if you see dots under buttons you should understand that something is wrong)

**Comment by ebraminio** [comment]
That could be a good assumption but seems not what non tech-savvy people, not neseccarly elderies even, can understand and as far as scroll bar has not a fixed place and is hidden at the first place, this technique is used on wild (I don't have example of this one now) and from number of stocked users on such channels (say ~1000, as said previously, not added at with their consent at first place), it seems to be effective.

**Comment by stek29** [comment]
And now imagine User's `About`s (`Bio`s) like these.

**Comment by stek29** [comment]
Not valid since 1.0 I guess

**Comment by Topsliked** [comment]
Today telegram’s channels are increasing and everyone want to increase members of these channels. Do you like increase your members without no cost and ad? Do you like add real members to your channels? Telemember App can do this. This is very simple just you must log in to your account and be join to some channels and gaining coins. Reach members by spending coins.
Here is the related links.

Google play: https://goo.gl/txooZK
Company Page: http://topsliked.com/
