### ISSUE TITLE
Proper font setting options on Windows Telegram [Feature Request] 

### ISSUE THREAD

**Issue by Sa-Ja-Di** [telegramdesktop/tdesktop#16154]
### Is your feature request related to a problem?
Windows Telegram lacks proper font setting options

### Describe the solution you'd like
I want to change in Windows Telegram font size and type, bc the standard font size is way too small and scaling is not working in a  good way.

**Comment by ilya-fedin** [comment]
#90

**Comment by paul1149** [comment]
I'm on Linux, using English, and I find the font hard to read. It does seem to be a sans, which is good, but still it's problematic. I'm in Night Mode, which seems to accentuate the problem.

The original #90, 5 years old, is now closed for comment.

**Comment by ilya-fedin** [comment]
it is locked, but it is still open

**Comment by paul1149** [comment]
Yes, I mentioned that thread to cite its age, and to provide the reason I was responding here.

**Comment by ilya-fedin** [comment]
Sorry, AFAIK there's no plan to allow to change font

**Comment by paul1149** [comment]
Thank you. Sorry to hear that.
