### ISSUE TITLE
no login by sms code in desktop version

### ISSUE THREAD

**Issue by ilyapashuk** [telegramdesktop/tdesktop#16153]
hello.

I downloaded tg desktop and tried to login

but I'm able to login only with code from app on an other device, but not with sms code.
I simply don't see this option in the tg desktop ui

latest version

**Comment by john-preston** [comment]
@ilyapashuk Yeah, they've disabled it from the server side :( Only login with another Telegram app (already logged) is supported now.

**Comment by Aokromes** [comment]
then this issue belongs to https://bugs.telegram.org

**Comment by HenkKalkwater** [comment]
An issue for this has been created over there: https://bugs.telegram.org/c/4239

**Comment by X547** [comment]
So it is not possible to use Telegram without smartphone anymore?

**Comment by Aokromes** [comment]
> So it is not possible to use Telegram without smartphone anymore?

some 3rd party clients looks to allow it. kotatogram for example.

**Comment by kbeals305** [comment]
Thanks @Aokromes   I was able to login with Kotatogram
