### ISSUE TITLE
Proxy settings no work properly while using SOCKS5 set by system PAC 

### ISSUE THREAD

**Issue by AkariiinMKII** [telegramdesktop/tdesktop#16150]
### Steps to reproduce
1. Set proxy settings to `use system proxy settings`
2. Set system proxy settings to custom PAC content (I'm using [Clash for Windows](https://github.com/Fndroid/clash_for_windows_pkg) to serve PAC file, 7999 is my local proxy server port for HTTP and SOCKS5 connections)
```
function FindProxyForURL(url, host) {
  if (
    isPlainHostName(host) ||
    shExpMatch(host, "*.local") ||
    isInNet(host, "10.0.0.0", "255.0.0.0") ||
    isInNet(host, "127.0.0.0", "255.0.0.0") ||
    isInNet(host, "172.16.0.0", "255.240.0.0") ||
    isInNet(host, "192.168.0.0", "255.255.0.0") ||
    isInNet(dnsResolve(host), "10.0.0.0", "255.0.0.0") ||
    isInNet(dnsResolve(host), "127.0.0.0", "255.0.0.0") ||
    isInNet(dnsResolve(host), "172.16.0.0", "255.240.0.0") ||
    isInNet(dnsResolve(host), "192.168.0.0", "255.255.0.0")
  ) {
    return "DIRECT";
  } else {
    return "SOCKS5 127.0.0.1:7999; PROXY 127.0.0.1:7999; DIRECT";
  }
}
```

### Expected behaviour
Connect to local proxy server `127.0.0.1:7999` with SOCKS5 connections.

### Actual behaviour
Connections from Telegram Desktop bypassed the proxy and directly went outbound.

Meanwhile, other programs like Chrome and Steam connected to proxy properly, prove that the PAC script does work in this situation.

And I've test some other situations for reference:
1. When changing content from `return "SOCKS5 127.0.0.1:7999; PROXY 127.0.0.1:7999; DIRECT";` to `return "PROXY 127.0.0.1:7999; SOCKS5 127.0.0.1:7999; DIRECT";` in PAC file, it works well with HTTP connections.
2. When changing proxy settings to `use custom proxy`, and manually select SOCKS5 proxy `127.0.0.1:7999`
, it works well with SOCKS5 connections.
### Configuration
**Operating system:** Win 10 Pro x64 ver2004 (19041.685)

**Version of Telegram Desktop:** 2.7.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: default theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Looking at Qt code, Windows support only HTTP proxy via PAC
https://github.com/qt/qtbase/blob/5.15/src/network/kernel/qnetworkproxy_win.cpp#L614-L617

**Comment by AkariiinMKII** [comment]
> Looking at Qt code, Windows supports only HTTP proxy via PAC
> https://github.com/qt/qtbase/blob/5.15/src/network/kernel/qnetworkproxy_win.cpp#L614-L617

Thank you for response, I'll take that
