### ISSUE TITLE
[Feature Request] Show common groups with other users / spammers

### ISSUE THREAD

**Issue by suntong** [telegramdesktop/tdesktop#16157]
### Is your feature request related to a problem?

Yes, there has been too many people contacting me in private that I'd deem spam / harassments, and I have no idea how they were able to reach me, as I'm on lots of groups.

### Describe the solution you'd like

- Most of the groups that I'm in have the policy of cannot spam on other people in the group, yet
- I have no idea which groups the spammer came from
- thus, showing the common groups I have with the new person / spammer would be a great tool for me to know where the spammer are coming from, thus
- report to the group admin so that the spammers  can be kicked from the group

### Describe alternatives you've considered

Knowing from which group they reached me would be a plus, for e.g., in the case when there are several common groups that I and the spammer have in common.

### Additional context

N.A.

**Comment by RememberTheAir** [comment]
It's already possible to see the groups you have in common with someone by opening that user's profile: under the list of shared medias categories, there's a "groups in common" item.

I don't think telegram tracks from where an user opened another user's profile to initiate a conversation, so it's impossible for an app to display this kind of information

**Comment by suntong** [comment]
Which version has that feature? 

Where can I find it?

![image](https://user-images.githubusercontent.com/422244/115247237-9eb41b00-a0f4-11eb-9af5-99d51dfeb885.png)

![image](https://user-images.githubusercontent.com/422244/115247262-a4116580-a0f4-11eb-85d2-b616e54adc78.png)

My version is v7.6.0 Android.

**Comment by suntong** [comment]
Do I have to "Add to Contact" in order to see that? (that defeats the purpose of blocking out spammers)

**Comment by RememberTheAir** [comment]
You're using the android app, not Telegram Desktop. This issue tracker is about Telegram Desktop.

From the android app you can see the list of common group from an user's profile (you don't need to add the  to your contacts):
![Kotatogram_2021-04-19_15-55-59](https://user-images.githubusercontent.com/16143208/115248317-dee0c100-a127-11eb-9b03-cf2fa8013f8a.png)

**Comment by suntong** [comment]
Oh, sorry, this is what I get from Telegram Desktop V7.1

![image](https://user-images.githubusercontent.com/422244/115250721-d8d2ec00-a0f7-11eb-8996-49274a5e7d7b.png)

no list of common group either.

**Comment by RememberTheAir** [comment]
That's because you don't have common groups with this account. Many spam account simply join public groups, scrap the members list, leave, and message the list of people they've been able to gather

**Comment by suntong** [comment]
Oh, Gotya. thx!

Closing it (until new info discovered).

**Comment by suntong** [comment]
Just wish a line of "no common group" can be shown in the profile if it is the case. 

Make it easier for newbie like me.

**Comment by Aokromes** [comment]
such request belongs to https://bugs.telegram.org
