### ISSUE TITLE
Scanning QR code From mobile Telegram is not work in Telegram Desktop night mode

### ISSUE THREAD

**Issue by mahdimRa** [telegramdesktop/tdesktop#16152]
### Steps to reproduce
1. Open Telegram Desktop ( In the night mode )
2. Go to the sidebar
3. Click on Add Account 
4. Using QR code to log in to Telegram Desktop
5.  Scanning QR code by Telegram Android

### Expected behaviour
When QR code is scanned by Telegram android to log in to Telegram Desktop, we Expected to log in to Telegram Desktop

### Actual behaviour
But unfortunately, if you use Telegram Desktop in dark mode, you will not log in to your account in this way ( QR code scanning) because the QR code scanner in mobile telegram can not recognize QR code in night mode.

### Configuration
**Operating system:*Ubuntu 20.04.2 LTS  -  windows10*

**Version of Telegram Desktop:2.7.1**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: the official website

**Used theme**: night mode

<details><summary><b>But unfortunately, if you use Telegram Desktop in dark mode, you will not log in to your account in this way ( QR code scanning) because the QR code scanner in mobile telegram can not recognize QR code in night mode.

<H1> How to solve this problem? (temporary) </H1>
If you still want to use a QR code scanner to log in to Telegram Desktop, you must change night mode to day mode.</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/10077

**Comment by john-preston** [comment]
@mahdimRa What is the Android device? My reads it, on Samsung Galaxy S20.
