### ISSUE TITLE
[Feature Request] Multiselect chats

### ISSUE THREAD

**Issue by MohammadMD1383** [telegramdesktop/tdesktop#16151]
I wonder if it was possible to multiselect chats (e.g. by holding <kbd>ctrl</kbd> and clicking on chats) and then do something with them. (e.g. read or mute etc)

e.g. situation: marking 10 chats as read is difficult and annoying when doing one by one …

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1841

**Comment by ilya-fedin** [comment]
#4079
