### ISSUE TITLE
[Feature Request] Emergency PIN-code

### ISSUE THREAD

**Issue by ngadiyak** [telegramdesktop/tdesktop#16169]
Telegram application has the security PIN-code, but it is not very safety for an user, e.g. someone took control of my phone/laptop and he have a possibility to make me saying the PIN-code.

**How to resolve?**

Two different pin-codes: 
1. gives access to all messages
2. removes marked channels first and then shows unmarked

If user enters 1st PIN-code, Telegram should show checkbox remove/not remove in the settings on any channel and give to user the possibility of changes that, in other words it works as usual for user.

If user enters 2nd PIN-code, Telegram removes marked channels (and all media posted in them) first, clears search history, set up settings (vpn/proxy and other sensitive sections) to default.

**Settings.**

User can be able to set up two pin-codes.
User becomes able to setup 2nd PIN-code only after 1st.
To setup 2nd, he must enter 1st PIN-code.
When he have set up 2nd, that section should not be changed.

`<button_set_emergency_code>` --> `<click>` --> `<enter_your_pin>` --> `<ok>  `

If an user setup 2nd PIN-code twice, Telegram should replace old value with the new one.

**Comment by mymedia2** [comment]
Hi! Thank you for the feature request. Since this is general one and does not solely related to Telegram Desktop it should be reported to bugs.telegram.org. For better protection you can setup cloud password, go to Settings > Privacy and Security > Two-step verification.
