### ISSUE TITLE
Program doesn't properly get closed

### ISSUE THREAD

**Issue by iArmann** [telegramdesktop/tdesktop#16163]
## When exiting the program, it doesn't get closed properly. 
This behaviour usually happens because the program is running on the background after closing it. Therefore, it's not properly exited so if next time a user tries to run the program it throws an error, because it's already running _on the background_. This happens specially when the program is **quickly** executed after being closed.
Whenever I encounter this issue, I kill the application running on background and execute it again.

### Expected behaviour
App must get closed properly, so it could run after it's closed.

### Actual behaviour
Running on background unmanageably.
### Configuration
**Operating system:** windows 10 x86_64

**Version of Telegram Desktop:** latest update via automatic updater - 2.7.1

**Used theme**: dark

<details><summary><b>Logs</b>:</summary>
<img alt="telegram-bug" src="https://user-images.githubusercontent.com/67087266/115477342-f075b600-a258-11eb-940b-ab94e4e81215.jpg" />
</details>

**Comment by ilya-fedin** [comment]
#10353
