### ISSUE TITLE
tdesktop: не работает вкладка в эмодзи "недавно использованные".

### ISSUE THREAD

**Issue by kitokedoki** [telegramdesktop/tdesktop#16164]
1. При открытии панели с эмодзи, первой по умолчанию открывается вкладка с недавно использованными эмодзи. Я каждый день, почти год, использую эмодзи с луной с глазами и солнцем с глазами, но они туда никак не встают. Зато там есть эмодзи с обезьянкой, которую я вообще не использую. Таким образом, во вкладку с часто используемыми эмодзи не подтягиваются часто используемые мной эмодзи.

### Expected behaviour
Панель с часто используемыми эмодзи должна обновляться

### Actual behaviour
Панель с часто используемыми эмодзи сейчас не обновляется, она не меняется совсем.
### Configuration
**Operating system:**
Windows 10 home

**Version of Telegram Desktop:**
2.7.1

**Used theme**:
Темная

**Comment by Aokromes** [comment]
english plz.

**Comment by kitokedoki** [comment]
1. When you open the emoji panel, the most recently used emoji tab is opened first by default. Every day  I use emoji  "moon with eyes" and the "sun with eyes", but they don't fit in there. But there is a monkey emoji that I don't use at all. Thus, my frequently used emojis are not pulled into the tab with frequently used emojis. 

### Expected behaviour
The frequently used emoji panel should be updated

### Actual behaviour
The panel with frequently used emojis is not updated now, it does not change at all. 

### Configuration
**Operating system:**
Windows 10 home

**Version of Telegram Desktop:**
2.7.1

**Used theme**:
Dark

**Comment by MasterGroosha** [comment]
I might be wrong, but emoji you type manually (by copy-paste or `:colon-search:`) don't get counted into most frequently used. At least this is how I observe it

**Comment by john-preston** [comment]
@kitokedoki
> Every day I use emoji ...

How exactly do you use it? You click on it in the panel? Because only those chosen from the panel jump up in the recents right now. I guess it should be improved.

**Comment by kitokedoki** [comment]
Yes, I click on it in the panel. Not type manually or copy-paste
![Безымянный - Paint 2021-04-22 14 25 02](https://user-images.githubusercontent.com/82925079/115690577-9c60f380-a376-11eb-9813-1354ab1383b3.png)

**Comment by aleksusklim** [comment]
Same issue here. The recent panel is full of other emojis that I don't use, but clearly lack ones that I choose frequently.

Any emoji auto-replace or suggesting is disabled in settings, I use only mouse when picking icons from the panel.
Also, when I pick an emoji – it might be added to the recent list, but somewhere in the middle of it, not at the first position.
After restarting TDesktop, those new emoji often disappear again.

**Comment by john-preston** [comment]
@aleksusklim Indeed, looks like they're reset on relaunch 😰

**Comment by ilya-fedin** [comment]
#4018
