### ISSUE TITLE
Error: "Could not start Telegram Desktop!" 

### ISSUE THREAD

**Issue by GermannPerutskij** [telegramdesktop/tdesktop#16160]
Has the same problem as in [this](https://github.com/telegramdesktop/tdesktop/issues/4929) post. Nothing helped, neither changing log file or clean reinstall
![1](https://user-images.githubusercontent.com/77357171/115420629-f7260e00-a203-11eb-9a47-3317e5d00555.png)
Error remains on different kinds of versions(v1.9.9-v2.7.1)

**Comment by ilya-fedin** [comment]
#10353

**Comment by GermannPerutskij** [comment]
@Aokromes Why you're closing this topic? There no answer in first replay

**Comment by ilya-fedin** [comment]
because it's a duplicate

**Comment by GermannPerutskij** [comment]
@ilya-fedin Как ты решил эту проблему?

**Comment by ilya-fedin** [comment]
нет у меня такой проблемы
