### ISSUE TITLE
High CPU load when playing a video

### ISSUE THREAD

**Issue by sgon00** [telegramdesktop/tdesktop#16168]
When playing **any** video (small resolution), the CPU load will take ~~70%~~ 80% of one CPU core.

This is really unexpected. It won't exceed 8% of one core when I play a 4K video by VLC.

### Configuration
**Operating system:** MacOS Big Sur 11.2.3 (20D91)

**Version of Telegram Desktop:** 2.7.1

**Installation source** - the official website (dmg)

**Used theme**: Tinted

**Comment by ilya-fedin** [comment]
#6312

**Comment by sgon00** [comment]
@ilya-fedin sorry that I didn't express clearly. I mean when playing any videos, the cpu will be 80%. Not 4k. I never play 4K in telegram. I just checked one video resolution, which is 480x848.

**Comment by ilya-fedin** [comment]
Don't matter, your issue is about hardwaare acceleration and that issue is about hardware acceleration

**Comment by sgon00** [comment]
@ilya-fedin very sorry again. I just read the issue title before. I even didn't read the second post. The second post mentioned it happend in smaller resolution too. Sorry about that.  :)

**Comment by sgon00** [comment]
I have changed the title to include `MacOS` keyword.
I am not sure if it's proper to say the following words here. So I am not putting this in that big thread.
So far, as a workaround, I am using `TelegramSwift`, the native MacOS client. It has much less CPU load than telegram desktop.
I think that might support hardware acceleration.
I really want to use telegram desktop and use it on my Linux. But due to the high cpu load issue, I have to leave it on my MacOS for now.
Hopefully, the issue can be fixed soon.
Sorry for saying the above words. Just trying to help other people who have the same problem on MacOS.
