### ISSUE TITLE
Telegram automatically puts underscores if uploaded file name is more than 60 characters

### ISSUE THREAD

**Issue by Nirzak** [telegramdesktop/tdesktop#16161]
### Steps to reproduce
1. The name of this file is exactly 61 characters long. Just download it and upload it to telegram. file: 
[This is for test-This file is created to test underscore bugs.txt](https://github.com/telegramdesktop/tdesktop/files/6346203/This.is.for.test-This.file.is.created.to.test.underscore.bugs.txt)
You'll get the following result:
<img height="60%" width="60%" src="https://user-images.githubusercontent.com/11460645/115453413-6cfc9a80-a241-11eb-96f6-5c07cde5eb79.PNG" />
So, what it does. It is replacing the dash and space characters as underscores for any filename that is greater than
60 characters.
The filename has now become like this : This_is_for_test_This_file_is_created_to_test_underscore_bugs

### Expected behavior
It should remain the filename untouched just like this `This is for test-This file is created to test underscore bugs`

### To get normal output
Remove a character from the above-given file name and make it 60 characters long and you'll get
the following normal output.
<img height="60%" width="60%" src="https://user-images.githubusercontent.com/11460645/115453863-ea280f80-a241-11eb-9127-1c8767635f67.PNG" />

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.7.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Comment by ilya-fedin** [comment]
#16114

**Comment by Nirzak** [comment]
> #16114

Oh! thanks for mentioning that one. Read that one also. It's the same issue. But the minimum number of characters is 60, not 64.

**Comment by ilya-fedin** [comment]
I guess it is intentional change on server side
@Aokromes probably it's worth to close both issues
