### ISSUE TITLE
[Feature Request] Desktop differentiation

### ISSUE THREAD

**Issue by doev03** [telegramdesktop/tdesktop#16162]
### Is your feature request related to a problem?
Yes. Too many chats on one window.

### Describe the solution you'd like
I suggest adding the ability to switch tabs, each of which will have chats on different topics. We can, for example, have a tab with chats for work and chats for education.

Please respond if you are going to implement this. If not, I'll have to do it myself...

P.S.
Sorry for my bad English :)

**Comment by ilya-fedin** [comment]
Settings -> Folders
