### ISSUE TITLE
"Save file as" does nothing - ubuntu

### ISSUE THREAD

**Issue by francesco-taioli** [telegramdesktop/tdesktop#16178]
### Steps to reproduce
1.  send file on telegram
2.  right click -> Save file as
3. dialog box for select the name and the location

### Expected behaviour
The file is saved under the  selected directory with the name specified before

### Actual behaviour
Dialog box closed, but the file is not present in that directory

### Configuration
**Operating system:** Ubuntu 20.04.2 LTS 64-bit - gnome 3.36.8

**Version of Telegram Desktop:** 2.7.1

**Installation source (Linux Only)** - snap

**Used theme**: dark

**Comment by ilya-fedin** [comment]
I did:
1. Created a file named `test.txt` in home directory
2. Sent it to Saved messages
3. right click -> Save file as
4. Chosen home directory
5. Saved file as test2.txt

Result: file successfully saved, can't reproduce

**Comment by ilya-fedin** [comment]
@Aokromes looks like author is not going to answer, probably it's worth to close the issue

**Comment by francesco-taioli** [comment]
@ilya-fedin  sorry for being late. Did exactly your list of operations but i can't save the file though

**Comment by ilya-fedin** [comment]
@francesco-taioli can you provide a record of the issue?

**Comment by francesco-taioli** [comment]
@ilya-fedin i don't think so, there is personal chat. I will try to re-install telegram and see if it persist

**Comment by francesco-taioli** [comment]
@ilya-fedin  found the issue.
I installed the app via snap. In the permission tab telegram doesn't has the permission to read/write files on removable device. If I turn on this option, I can save the file via the right click.
If this option is turned off, it doesn't work. Telegram doesn't report any error though  
![telegram](https://user-images.githubusercontent.com/17709353/117531841-e25bbf80-afe4-11eb-8eb7-125616b5dba5.png)

**Comment by ilya-fedin** [comment]
But you said you can't save files to home directory :thinking:

> Did exactly your list of operations but i can't save the file though

Or this wasn't 'exactly' actually?

**Comment by francesco-taioli** [comment]
Ok, so I found that if that option is **turned off you can't save file with 'save file as'** (i.e your list of operations). Moreover, Telegram doesn't report any error. This option I think is the default when downloading with snap.

If that option is **turned on there is no problem when saving**

**Comment by ilya-fedin** [comment]
That option shouldn't influence when you saving not to removable media, e.g. to home directory.

**Comment by francesco-taioli** [comment]
no, i choose /home/$USER. Nevertheless, it doesn't save the file in any folder, not only /home

**Comment by ilya-fedin** [comment]
That's weird, but I guess that's impossible to fix on tdesktop side since it can't control sandbox

**Comment by magickreeator** [comment]
I have a similar issue. Telegram freezes, when I save photos from chats on Ubuntu 20.04.
Steps to reproduce:
1. open an picture in chat
2. right click on the picture
3. press Save as...
4. choose the file location (/home/$USER/Загрузки/Telegram Desktop)
5. press Save
Actual result: Telegram freezes (a system message is shown on click)
journalctl -xe:
![image](https://user-images.githubusercontent.com/10911885/124288601-0a395080-db5a-11eb-9e10-4feaa3dac349.png)
Expected result: Telegram saves the picture and continue working
I checked on two PCs

**Comment by ilya-fedin** [comment]
@magickreeator your issue is not similar, this issue is about situation when you're choosing a file that application has no access to and application doesn't give any dialog box, just ignores the fact file was chosen

**Comment by thesmallcreeper** [comment]
@magickreeator Btw I am not up to speed with the repo. Today I also had this problem (during e-exam :/ :/ ) with the release of latest 2.8.4 update via snap. Yesterday (before update) everything was fine. I do believe that we should make a new issue. Let me know if you do :)
