### ISSUE TITLE
Sound in videos not works, Telegram 2.7.1 Desktop, Linux Ubuntu

### ISSUE THREAD

**Issue by scorobo** [telegramdesktop/tdesktop#16170]
### Steps to reproduce
1.  Run Telegram
2. Play any video with sound in any channel
3. Sound no works

### Expected behaviour
I can't play sound in videos. 

### Configuration
**Operating system:**
Ubuntu 20.04.2 LTS

**Version of Telegram Desktop:**
2.7.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
the official website tag.gz 

<details><summary><b>Logs</b>:</summary>

(Telegram:112109): dbind-WARNING **: 19:46:02.048: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[ALSOFT] (EE) Failed to set real-time priority for thread: Операция не позволена (1)

ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: Нет такого файла или каталога
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: Нет такого файла или каталога
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: Нет такого файла или каталога
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: Нет такого файла или каталога
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
</details>

**Comment by ilya-fedin** [comment]
The log looks like you started Telegram with sudo

**Comment by user23108947023948** [comment]
I am having the same issue on Linux Mint 20.1 Cinnamon edition using Telegram 2.7.1.  I recall it working a few weeks ago and off the top of my head, can't think of anything that might have changed.

**Comment by ilya-fedin** [comment]
> I am having the same issue on Linux Mint 20.1 Cinnamon edition using Telegram 2.7.1. I recall it working a few weeks ago and off the top of my head, can't think of anything that might have changed.

We need logs.

**Comment by user23108947023948** [comment]
Sorry if I'm missing something obvious (I'm a non-technical end user), but which specific log(s) should I post?

**Comment by ilya-fedin** [comment]
terminal output and `~/.local/share/TelegramDesktop/log.txt`

**Comment by ilya-fedin** [comment]
@scorobo @user23108947023948 please provide needed info or the issue will be closed
