### ISSUE TITLE
[Feature Request] Tabs in a stock file-chooser

### ISSUE THREAD

**Issue by meklonets** [telegramdesktop/tdesktop#16177]
Archlinux.
SwayWM
Official telegram binary.
.bashrc has:
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORM=wayland
pcmanfm-qt as file manager app.
Tdesktop uses his own qt file-chosser and this is ok but is there any way to add Tabs to the right field as on my screenshot.
![16h_05m_40s_23_Apr_21](https://user-images.githubusercontent.com/13570880/115876160-a5bd8f00-a44e-11eb-986d-37ec205e2126.png)

**Comment by ilya-fedin** [comment]
This chooser is not a part of Telegram code, it is a part of Qt code and Telegram can't change it
