### ISSUE TITLE
Multi-accounts: Posts on groups always display first account name

### ISSUE THREAD

**Issue by lifeboy** [telegramdesktop/tdesktop#16176]
### Steps to reproduce
1. Add a second account to Telegram Desktop, using a different phone number
2. Join a group (public or private) as the second account
3. Post a message.
4. Switch to the first account and view the message:  The message comes from the second account, but the name of the first account is displayed as the sender, which is of course a bug.

### Expected behaviour
The name of the second account must be displayed and no part of the first account must be shown or used

### Actual behaviour
The name of the first account is used

### Configuration
**Operating system:**
Ubuntu 18.04
Android 9

**Version of Telegram Desktop:**
Desktop 2.7.1
Telegram for Android v7.6.0 (2264) arm64-v8a

**Comment by john-preston** [comment]
@lifeboy I can't reproduce that on desktop. I don't know how you tested it and why you mention Android version.

This doesn't sound possible at all. All data and messages are completely separate in two accounts, they can even not have access to different groups and even be in different clusters (real net and test net). I think you've mistaken something.

**Comment by lifeboy** [comment]
I'm not mistaken.  Why would I open a ticket and go to all the trouble if
it wasn't as I described?

Here's a message I posted as the account "Friedrich" (activation message
can be seen in the Telegram message group on the right)

[image: image.png]

Switching to the first account, here what I see in that same group.

[image: image.png]

Friedrich profile pic is shown, but the name is Roland, not Friedrich,
which is wrong.

I added Android, because the behaviour on it is identical.  It's not a
version issue it seems.

**Comment by lifeboy** [comment]
Aa a matter of fact, here are two more screen shots.

When I view the message posted by Friedrich as "Roland Giesler", this is what I see.

![image](https://user-images.githubusercontent.com/4822951/115971053-a20d3380-a546-11eb-8f7e-0fe08c8d5504.png)

However, this is what the user's actual profile looks like.

![image](https://user-images.githubusercontent.com/4822951/115971076-c537e300-a546-11eb-94c7-36af6bde95db.png)

So, for some stranger reason I see the wrong name.  

If I post something from Android, the behaviour is identical, so I'm not going to post more screenshots from that as well.

**Comment by john-preston** [comment]
@lifeboy This means one of your account has the second account in its contacts list with the wrong name.

So your first account has the phone number of "Friedrich der Grosse" in his contacts list with the name "Roland Giesler". You don't need to post a message, you can just open the account profile and see the name.

**Comment by lifeboy** [comment]
My goodness!  This must have been automatically (is that possible?)
created, as I definitely did not save it like that...   at least the
mystery "bug" has been solved.
