### ISSUE TITLE
Pinned chat in Unread folder never clears

### ISSUE THREAD

**Issue by rioda-org** [telegramdesktop/tdesktop#16173]
### Steps to reproduce
1. Pin some chat while you are in Unread folder
2. Unpin it

### Expected behaviour
It should not appear in Unread folder forever after unpining it

### Actual behaviour
Previously pinned chat never clears from Unread folder

### Configuration
Operating System: Win10 Ver 20H2 (OS Build 19042.928)

Version of Telegram Desktop: 2.7.1 x64

Used theme**: Default theme, night mode

**Comment by RememberTheAir** [comment]
Yes, pinning a chat inside a folder will automatically add it to the folders as a "manually included" chat. I believe this is the intended behavior, which is a bit weird, but it works like that on all apps. I think this issue should be brought to https://bugs.telegram.org

**Comment by rioda-org** [comment]
Ah, didn't cross my mind that chats can be removed like from other folders. Thanks. Now that I know this, it's usefull as an option to pin in unread folder.
