### ISSUE TITLE
[Feature Request] Filename when saving file should be created date instead download date

### ISSUE THREAD

**Issue by wankio** [telegramdesktop/tdesktop#16180]
### Is your feature request related to a problem?
Telegram desktop dont have Downloads tab so you dont know which videos in queue is failed or not, only thing you can do is looking into downloaded folder and search any video don't have thumbnail (broken/unfinished download)

### Describe the solution you'd like
Everytime when you save something, it will named file as the time when you click save. So instead named file as download date, it will named file as Created date or edited date. you can easily re-download unfinished/broken videos/gif or pictures with those created date information

**Comment by ilya-fedin** [comment]
That's impossible, server doesn't preserve such info, see #4951
