### ISSUE TITLE
photo on invoice not shown as well

### ISSUE THREAD

**Issue by mugavri** [telegramdesktop/tdesktop#16187]
photo on invoice not shown as well,

![image](https://user-images.githubusercontent.com/12531879/116101655-ad7f6c80-a6b6-11eb-9b4c-b8d870335454.png)

if you click on the black space then the photo opening on media viewer

![image](https://user-images.githubusercontent.com/12531879/116101915-eb7c9080-a6b6-11eb-9b93-aa13e8da4884.png)

(BTW, link to photo is : [https://img.mako.co.il/2010/11/06/master_chef_8_10musa_c.jpg](url))

**Comment by Aokromes** [comment]
works for me (TM)
https://i.imgur.com/kvU9f6x.png
