### ISSUE TITLE
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)

### ISSUE THREAD

**Issue by andrew-ld** [telegramdesktop/tdesktop#16182]
### Steps to reproduce
1. start recording a voice message
2. (now the recording time remains 00.01)
3. I no longer hold down the record button

the application after releasing the voice recording button freezes for about 1 second and then crashes

### Expected behaviour
it should say that it failed to record the voice message or it should send the voice message if there was no error

### Actual behaviour
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
fish: Job 1, 'telegram-desktop' terminated by signal SIGSEGV (Address boundary error)

## Note
the microphone works in voice chats, it seems not to go only when I record a voice message

### Configuration
**Operating system:** archlinux

**Version of Telegram Desktop:** 2.7.1

**Installation source (Linux Only)** archlinux official repo

**Used theme**: default / white

**Comment by Limgmk** [comment]
Hello, I have the same problem on archlinux now. Did you solve this problem?
