### ISSUE TITLE
An open chat is marked as read, even when the window is out of focus

### ISSUE THREAD

**Issue by SKProCH** [telegramdesktop/tdesktop#16188]
### Steps to reproduce
1. Open chat
2. Switch to another window
3. Wait for message
4. It is now automatically read, and there is no notification of the arrival of the message

### Expected behaviour
While the window is out of focus, the chat should not be read

### Actual behaviour
An open chat is marked as read, even when the window is out of focus

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.7.2
**Used theme**:
Night

**Comment by john-preston** [comment]
@SKProCH It is marked if it is visible and not overlapped (seen) and the computer is used.

**Comment by SKProCH** [comment]
Can you make it a switchable function? I have 3 monitors, on one of them telegrams are constantly open and I often simply do not see (and do not hear, there is no notification) that I have received a new message. And all the time after having answered the person to close the dialogue window is inconvenient and not practical, I think. It also gets in the way when you work with the data that was sent to you and you cannot close the dialog.

**Comment by tetra-fox** [comment]
Additionally, this change causes messages to be marked as read while Windows is locked with the <kbd>WIN</kbd>+<kbd>L</kbd> shortcut if the window is "visible" when really it's impossible to be, given that the workstation is locked.

**Comment by john-preston** [comment]
@tetra-fox Thanks, that's important.

**Comment by john-preston** [comment]
The locked screen issue should be fixed in the next update.

**Comment by acidnik** [comment]
> @SKProCH It is marked if it is visible and not overlapped (seen) and the computer is used.

In my case (Linux, xfce) this happens even if telegram is overlapped by other window (the other window begin maximized)

**Comment by ilya-fedin** [comment]
@acidnik please give `xprop` and `xwininfo` of that window

**Comment by acidnik** [comment]
xpop:
```
_NET_WM_ICON_GEOMETRY(CARDINAL) = 808, 1170, 200, 30
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_STICK
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x73aca900
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED
_NET_WM_USER_TIME(CARDINAL) = 249568117
WM_NAME(UTF8_STRING) = "YouTube — Yandex Browser"
_NET_WM_NAME(UTF8_STRING) = "YouTube — Yandex Browser"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 35
		program specified minimum size: 672 by 328
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) = 	Icon (128 x 128):
	(not shown)

_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED(CARDINAL) = 1
WM_WINDOW_ROLE(STRING) = "browser"
WM_CLASS(STRING) = "yandex-browser-beta", "Yandex-browser-beta"
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 1046
WM_CLIENT_MACHINE(STRING) = "metal"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```

xwininfo:
```

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x380009e "YouTube — Yandex Browser"

  Absolute upper-left X:  0
  Absolute upper-left Y:  36
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1601
  Height: 1135
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +0+36  --1+36  --1-29  +0-29
  -geometry 1601x1135+0-29
```

**Comment by nuclight** [comment]
Haha, they broke this feature in #753 by request of some marginals who always have inactive window at their eye. The previous behaviour must be restored as default and option added for those who want auto-scrolling/marking.
