### ISSUE TITLE
v2.7.2 is not open on debian (last time telegram desktop was not closed properly debian)

### ISSUE THREAD

**Issue by nightbuster** [telegramdesktop/tdesktop#16198]
### Steps to reproduce
1. update to v2.7.2
2. launch
3. watching the window with the phrase (or nothing)

### Expected behaviour
opened a window with Telegram Desktop

### Actual behaviour
Update fails or upgrades to 2.7.2 and won't open

### Configuration
**Operating system:**
Linux Debian 9 (stretch)

**Version of Telegram Desktop:**
2.7.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
https://desktop.telegram.org/ - Telegram for Linux x64

**Used theme**:
default theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by nightbuster** [comment]
it is working for me after downgrade to 2.7.0 version (update disabled)

**Comment by mrLSD** [comment]
#16189

**Comment by carnendil** [comment]
I can confirm the same error on Ubuntu 16.04.

When running `./Telegram`, from the `tsetup.2.7.2.tar.xz`, the following message appears:

`[ALSOFT] (EE) Failed to set real-time priority for thread: Operación no permitida (1)`

The last bit is Spanish for "Operation not allowed".

**Comment by MihanEntalpo** [comment]
Has the same problem. The Telegram executable failed to start bacause of Segmetanion Fault.
Attaching result of `strace ./Telegram > /tmp/telegram.log 2>&1`
[telegram.log](https://github.com/telegramdesktop/tdesktop/files/6381941/telegram.log)

**Comment by MihanEntalpo** [comment]
> #16189

Working version (2.7.1) shows the same message, but doesnt die with segmentation fault, so this is not the source of the problem

**Comment by PashaTurok** [comment]
The same problem. Good morning from telegram!

**Comment by mrLSD** [comment]
> > #16189
> 
> Working version (2.7.1) shows the same message, but doesnt die with segmentation fault, so this is not the source of the problem

The discussion about v2.7.2, not about v2.7.1

**Comment by MihanEntalpo** [comment]
> > > #16189
> > 
> > 
> > Working version (2.7.1) shows the same message, but doesnt die with segmentation fault, so this is not the source of the problem
> 
> The discussion about v2.7.2, not about v2.7.1

If you look closely you'll see, that I've answered to a message that make a suggestion on "this is an old issue 16189", and add information that old version also outputs this message, but working fine.

Does the fact that this discussion is about v2.7.2 means that no one should mention other versions even in comparison purpose :) ?

**Comment by roccopietrini** [comment]
Same here with Ubuntu 16.04.7

**Comment by cubotto** [comment]
> s working for me after downgrade to 2.7.0 version (update disabled

where you donwloaded?

**Comment by qb60** [comment]
> > s working for me after downgrade to 2.7.0 version (update disabled
> 
> where you donwloaded?

https://github.com/telegramdesktop/tdesktop/tags

**Comment by roccopietrini** [comment]
I also had to downgrade to 2.7.1 to make it work again.

**Comment by MissingUser** [comment]
Same problem with Ubuntu 16.04.7 LTS x86_64 (Spanish configuration) after allowing the update

**
[ALSOFT] (EE) Failed to set real-time priority for thread: Operación no permitida (1)
Violación de segmento
**

Operación no permitida = Operation not allowed
Violación de segmento = Segment violation

**Comment by cdarken** [comment]
> it is working for me after downgrade to 2.7.0 version (update disabled)

How do I disable the update? It starts updating itself right away when I run it.

**Comment by PoliakovMaksym** [comment]
> > it is working for me after downgrade to 2.7.0 version (update disabled)
> 
> How do I disable the update? It starts updating itself right away when I run it.

I downloaded the v2.7.1 from the repo. When you run the "Telegram" file you will have time to press the "Skip" button which will launch it without updating to the latest version

**Comment by Arinelle** [comment]
I also get the segmentation fault since the update this morning on Linux Mint 18.3.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16189

**Comment by nightbuster** [comment]
> Download the v2.7.1 from the repo and when you run the "Telegram" file you will have time to press the "Skip" button which will launch it without updating to the latest version

Yes! It worked for me and for any version less than 2.7.2

**Comment by nightbuster** [comment]
Waiting for release

**Comment by cdarken** [comment]
> > > it is working for me after downgrade to 2.7.0 version (update disabled)
> > 
> > 
> > How do I disable the update? It starts updating itself right away when I run it.
> 
> Download the v2.7.1 from the repo and when you run the "Telegram" file you will have time to press the "Skip" button which will launch it without updating to the latest version

Thank you! The text was so washed out I barely could see it and even when I saw it I thought it was disabled.

**Comment by nightbuster** [comment]
Updated to 2.7.3. It's working
