### ISSUE TITLE
Most recent release (2.7.2) Segfaults on Linux

### ISSUE THREAD

**Issue by ikmckenz** [telegramdesktop/tdesktop#16191]
### Steps to reproduce
1. On Ubuntu 16.04, try to run the newly released binary
2. It segfaults.
3. Also, this happens to system installation when updating. 

### Configuration
**Operating system: Ubuntu 16.04**

**Version of Telegram Desktop: 2.7.2**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: The website and GitHub release, as well as updating from the old website version.

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16189
