### ISSUE TITLE
Messages not appearing in 2.7.2 (Linux snap install)

### ISSUE THREAD

**Issue by maksloboda** [telegramdesktop/tdesktop#16194]
### Steps to reproduce
1. Open a chat with someone
2. Focus a different window
3. Make the other person send you a message

### Expected behaviour
Message appears

### Actual behaviour
Message wont appear even after selecting TG window again.
Messages reappear after sending a message though.

### Configuration
**Operating system:** Ubuntu 20.04.2 LTS 64-bit

**Version of Telegram Desktop:** 2.7.2

**Installation source (Linux Only)** - snap

**Used theme**: Tinted (not sure if this is what is needed)

<details><summary><b>Logs</b>:</summary>
</details>

Edit:
It manifests even in "Saved messages" when using a second device to send.
It appears that 2-5 minutes must pass after selecting another window before sending a message

**Comment by ilya-fedin** [comment]
I can't get what are you talking about. Can you make a record with the issue?

**Comment by maksloboda** [comment]
Cant replicate after restarting the computer.
