### ISSUE TITLE
[Feature Request] Username suggestion/autofill when composing image/video captions

### ISSUE THREAD

**Issue by MaxwellCody** [telegramdesktop/tdesktop#16197]
### Is your feature request related to a problem?
For those of us who don't memorize the usernames for every single user in a chat, it's very inconvenient to tag a user on an image or video message. The compose media message dialog is modal so you must close it in order to lookup someone's username, which will discard your drafted message. It's also not very convenient to use the system clipboard to save the drafted message since, in most cases, you'll be needing that for the username.

### Describe the solution you'd like
Provide suggestions and autofill for usernames when the user starts typing a word beginning with `@`, just like how the primary message compose box behaves.

### Describe alternatives you've considered
Saving the drafted message to the clipboard, closing the compose media message dialog, looking up the username, memorizing it, and then reopening the dialog and adding the username.

#### The primary message compose box provides an easy way to lookup usernames.
![composing a text message on telegram desktop](https://user-images.githubusercontent.com/30818918/116167408-c04d6d80-a6c5-11eb-83ef-41669b76f9bf.png)
#### The media message compose box does not provide a way to lookup usernames.
![composing a media message on telegram desktop](https://user-images.githubusercontent.com/30818918/116167539-03a7dc00-a6c6-11eb-8588-f8d3cff38a56.png)

**Comment by ilya-fedin** [comment]
#9020
