### ISSUE TITLE
Some emoji (flags) are not displayed correctly on Linux

### ISSUE THREAD

**Issue by nbz6** [telegramdesktop/tdesktop#16190]
Some emoji are not displayed correctly in the Telegram Desktop on Linux.
I regularly see people that sometimes don't choose the right flag for France in there emoji list, and then choose Clipperton Island's or St. Martin's.

I've tested all others emoji 1.0, the issue is **only** on these 10 emoji and in particular in the flag category.
These emoji doesn't seems to look recent, they were introduced with Emoji 1.0 in 2015.
They seems to exist in the 4 emojis packs in Telegram Desktop and display well in the Windows version of Telegram Desktop.
Finally there are displayed well in all my others Linux applications, but not in Telegram Desktop.

### Steps to reproduce
1. Copy paste one or all these 10 flags in your Telegram Desktop on Linux : 
```
🇦🇨 Flag: Ascension Island
🇧🇻 Flag: Bouvet Island
🇨🇵 Flag: Clipperton Island
🇩🇬 Flag: Diego Garcia
🇪🇦 Flag: Ceuta & Melilla
🇭🇲 Flag: Heard & McDonald Islands
🇲🇫 Flag: St. Martin
🇸🇯 Flag: Svalbard & Jan Mayen
🇹🇦 Flag: Tristan Da Cunha
🇺🇲 Flag: U.S. Outlying Islands
```

2. See the result in your input field or in your message

### Expected behaviour
You should see the emoji flag like displayed above.

### Actual behaviour
This is what I see for these emoji :
![image](https://user-images.githubusercontent.com/4399512/116138160-bed77180-a6d4-11eb-826b-9ea220744220.png)

### Configuration
**Operating system: Arch Linux**

**Version of Telegram Desktop: 2.7.2**

**Installation source (Linux Only)** - distribution package: community/telegram-desktop 2.7.2-1

**Used theme**: Tinted Dark

**Comment by ilya-fedin** [comment]
#9775

**Comment by nbz6** [comment]
> #9775
It doesn't seem to be related to Emoji 13.0 but I could be wrong.
From what I read these flags are present since Emoji 1.0 in 2015

**Comment by nbz6** [comment]
I've installed an Ubuntu 21.04 VM and tested the snap 2.7.2 version and the ubuntu package 2.6.1 version.
Both doesn't have the issue.

Could be specific to Arch Linux package or dependency.

**Comment by ilya-fedin** [comment]
I see these emojis aren't converted to images like others, so this means they aren't supported yet, so -> #9775

**Comment by nbz6** [comment]
> I see these emojis aren't converted to images like others, so this means they aren't supported yet, so -> #9775

Thanks for the explanation. I see now.
On Ubuntu I've set the "JoyPixels" pack which has circular form, and we can see the diff with these 10 flags.
![image](https://user-images.githubusercontent.com/4399512/116163793-b85af100-a6f8-11eb-9c3d-d496eb9764fd.png)
