### ISSUE TITLE
Enable Secure Chat

### ISSUE THREAD

**Issue by rezapc** [telegramdesktop/tdesktop#162]
it would be nice if we have a Secure chat on client in Windows(or other OS's also)

**Comment by hawken93** [comment]
+1

**Comment by intrd** [comment]
+1

**Comment by ingvarch** [comment]
+1

**Comment by onrik** [comment]
+1

**Comment by mikeadamz** [comment]
+1

**Comment by Altair2015** [comment]
+1

**Comment by nmat** [comment]
+1

**Comment by asd-and-Rizzo** [comment]
+1

I did installed Android x86 into VirtualBox. Weird but works.

Please add feature and Donate button.

**Comment by russlevy** [comment]
+1

**Comment by asyassa** [comment]
+1

**Comment by Altair2015** [comment]
Пиривет. А теперь еще раз

С уважением Максим Русланович Пхалагов
24 марта 2015 г. 6:02 пользователь "asyassa" <notifications@github.com>
написал:

**Comment by Altair2015** [comment]
+1

**Comment by najela** [comment]
+1

**Comment by wp9015362** [comment]
+1

**Comment by deemz** [comment]
+1

**Comment by iliketurtlesbro** [comment]
+1

**Comment by asd-and-Rizzo** [comment]
have anybody  tried https://archon-runtime.github.io and may share experience and converted apk? So it may appear android version is good enough to run on chrome on wkndows

**Comment by btcid** [comment]
+1

**Comment by auchri** [comment]
Duplicate #871
