### ISSUE TITLE
Telegram 2.7.2 Linux x64 segfault

### ISSUE THREAD

**Issue by kazm-dd** [telegramdesktop/tdesktop#16203]
### Steps to reproduce
1. Unpack tsetup.2.7.2.tar.xz over previous version or by using Updater
2. Execute ./Telegram
3. Local passcode is requested. Enter the correct code

### Expected behaviour
Normal startup

### Actual behaviour
Program crashes with segfault

### Configuration
**Operating system:**
Ubuntu 16.04 LTS 64 bit
Linux dd-ws 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Version of Telegram Desktop:**
2.7.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
https://telegram.org/dl/desktop/linux

<details><summary><b>Logs</b>:</summary>
(gdb) run
Starting program: /opt/Telegram/Telegram 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe9afc700 (LWP 14404)]
[New Thread 0x7fffe92fb700 (LWP 14405)]
[New Thread 0x7fffe3fff700 (LWP 14406)]
[New Thread 0x7fffe2da2700 (LWP 14407)]
[New Thread 0x7fffe25a1700 (LWP 14408)]
[New Thread 0x7fffe1da0700 (LWP 14410)]
[New Thread 0x7fffe159f700 (LWP 14411)]
[New Thread 0x7fffe0d9e700 (LWP 14412)]
[New Thread 0x7fffc7fff700 (LWP 14413)]
[New Thread 0x7fffc77fe700 (LWP 14414)]
[New Thread 0x7fffc6ffd700 (LWP 14415)]
[New Thread 0x7fffc67fc700 (LWP 14416)]
[New Thread 0x7fffc5ffb700 (LWP 14417)]
[Thread 0x7fffc67fc700 (LWP 14416) exited]
[New Thread 0x7fffc67fc700 (LWP 14419)]
[New Thread 0x7fffc55f3700 (LWP 14420)]
[New Thread 0x7fffc4df2700 (LWP 14421)]
[New Thread 0x7fffabfff700 (LWP 14422)]
[New Thread 0x7fffa98d2700 (LWP 14423)]
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[New Thread 0x7fffa90d1700 (LWP 14424)]
[New Thread 0x7fffa88d0700 (LWP 14425)]
[New Thread 0x7fff97fff700 (LWP 14426)]

Thread 1 "Telegram" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7583ede in g_socket_control_message_deserialize () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#2  0x00007ffff757a300 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#3  0x00007ffff757dcb1 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff757e246 in g_socket_receive_message () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x00007ffff75acfb1 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007ffff75ad93f in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007ffff75adfc6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007ffff7561a6f in g_initable_new_valist () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x00007ffff7561b26 in g_initable_new () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007ffff7565230 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x00000000012ce365 in base::Platform::NetworkAvailable() ()
#12 0x00000000012d80f5 in base::NetworkReachability::NetworkReachability() ()
#13 0x00000000012d837e in base::NetworkReachability::Instance() ()
#14 0x0000000001b7c006 in MTP::Instance::Private::Private(gsl::not_null<MTP::Instance*>, MTP::Instance::Mode, MTP::Instance::Fields&&) ()
#15 0x0000000001b5c2db in MTP::Instance::Instance(MTP::Instance::Mode, MTP::Instance::Fields&&) ()
#16 0x0000000001c5243e in Main::Account::startMtp(std::unique_ptr<MTP::Config, std::default_delete<MTP::Config> >) ()
#17 0x0000000001c53cd2 in Main::Account::start(std::unique_ptr<MTP::Config, std::default_delete<MTP::Config> >) ()
#18 0x000000000195c8bc in Storage::Domain::startModern(QByteArray const&) ()
#19 0x000000000195cb09 in Storage::Domain::start(QByteArray const&) ()
#20 0x0000000001c2b8a4 in Main::Domain::start(QByteArray const&) ()
#21 0x00000000018bbb88 in Window::PasscodeLockWidget::submit() ()
#22 0x0000000003f8f373 in ?? ()
#23 0x000000000121bee8 in Ui::MaskedInputField::keyPressEvent(QKeyEvent*) ()
#24 0x0000000003636d47 in ?? ()
#25 0x000000000370c74a in ?? ()
#26 0x00000000011cb586 in Ui::RpWidgetMethods::handleEvent(QEvent*) ()
#27 0x0000000003607e7f in ?? ()
#28 0x0000000003611db4 in ?? ()
#29 0x000000000218090e in Core::Sandbox::notify(QObject*, QEvent*) ()
#30 0x0000000003f5c328 in ?? ()
#31 0x0000000003651eb6 in ?? ()
#32 0x0000000003607e7f in ?? ()
#33 0x0000000003611598 in ?? ()
#34 0x000000000218090e in Core::Sandbox::notify(QObject*, QEvent*) ()
#35 0x0000000003f5c820 in ?? ()
#36 0x00000000039613a3 in ?? ()
#37 0x0000000003966555 in ?? ()
#38 0x000000000393c2c4 in ?? ()
#39 0x00000000033a294a in ?? ()
#40 0x00007ffff5d5a267 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007ffff5d5a4c0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#42 0x00007ffff5d5a56c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x0000000003fb547e in ?? ()
#44 0x0000000003f5ae9e in ?? ()
#45 0x0000000003f63f66 in ?? ()
#46 0x000000000218686b in Core::Sandbox::start() ()
#47 0x000000000218a478 in Core::Launcher::executeApplication() ()
#48 0x000000000218a615 in Core::Launcher::exec() ()
#49 0x0000000001040538 in main ()
(gdb) 

</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16189
