### ISSUE TITLE
2.7.2 crashes after update from 2.7.1 on linux mint 18.2 (64bit)

### ISSUE THREAD

**Issue by admzzz** [telegramdesktop/tdesktop#16205]
### Steps to reproduce
1.  confirm update in gui or manually extract 2 binaries from tsetup.2.7.2.tar.xz
2.  start telegram from desktop file or commandline `/opt/Telegram/Telegram -- %u`

### Expected behaviour
telegram should start

### Actual behaviour
window opens and dissapears.
if starting from terminal,
```
$ /opt/Telegram/Telegram -- %u
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
Segmentation fault
```
extracted back v 2.7.1 works fine.

```
$ uname -a
Linux wwwadm 5.2.14-ext73-72.14-haswell #9 SMP Mon Sep 9 20:44:52 CEST 2019 x86_64 GNU/Linux
$ cat /etc/lsb*
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.2
DISTRIB_CODENAME=sonya
DISTRIB_DESCRIPTION="Linux Mint 18.2 Sonya"
```

**Comment by Guzya** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16204

**Comment by admzzz** [comment]
@Guzya ,
не думал, что тут и по-русски можно ;-)

**Comment by Guzya** [comment]
Ну так владелец-то русскоговорящий )))
