### ISSUE TITLE
Не обновился и не запускается Telegram Desktop

### ISSUE THREAD

**Issue by Guzya** [telegramdesktop/tdesktop#16204]
Нажал обновить в приложении, после этого приложение закрылось и все.
При ручном запуске, мелькает окошко и все.
Скрин мелькающего окошка приложил.
Так же попробовал скачать архив отсюда tsetup.2.7.2.tar.xz, ситуация не поменялась.

### Steps to reproduce
1. Нажал обновить в приложении
2. Попробовал tsetup.2.7.2.tar.xz 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Linux mint 19
**Version of Telegram Desktop:**
tsetup.2.7.2.tar.xz
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Нажал кнопку обновить в самом приложении
![Снимок экрана от 2021-04-27 13-54-51](https://user-images.githubusercontent.com/22929301/116230536-6f3e8780-a760-11eb-88f4-2022dff9b907.png)

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@Guzya This will be fixed in 2.7.3 within an hour. It should be able to autoupdate from the non-working version.

**Comment by Guzya** [comment]
Ок!
