### ISSUE TITLE
2.7.2 ignores my fonts.conf and the fonts are aweful

### ISSUE THREAD

**Issue by AngryPhantom** [telegramdesktop/tdesktop#16201]
### Configuration
Debian 10, Void Linux etc.
Telegram 2.7.2 (your 64bit binary)

After autoupdate Telegram fonts became aweful. There is no antialiasing at all. It now even ignores my fonts.conf.
Everything was fine up until now. The last OK version is 2.7.1.
Is it possible to fix somehow?

Thank you.

**Comment by ilya-fedin** [comment]
`xrdb -query`

**Comment by AngryPhantom** [comment]
@ilya-fedin

[xrdb -query](https://pastebin.com/raw/s4J7Hsdy)

**Comment by ilya-fedin** [comment]
I see this:
```
Xft.antialias:	0
Xft.dpi:	96.1259765625
Xft.hinting:	1
Xft.hintstyle:	hintfull
Xft.lcdfilter:	none
Xft.rgba:	none
```
Of course the font will look awful.

**Comment by AngryPhantom** [comment]
@ilya-fedin

Ah, sorry. That's my global settings probably.

Since I don't like antialiasing myself, it's disabled in MATE and XFCE. I only use it for Chromium and Telegram because they have garbled fonts (without antialiasing).

So I created a _.config.telegram_ directory with a _/fontconfig/fonts.conf_ inside. The contents of [fonts.conf](https://pastebin.com/raw/TJsMkQNy).

Then I start Telegram with this:

`sh -c "XDG_CONFIG_HOME="/home/username/.config.telegram" Telegram %U"`

Is there anything I can do with this? Again, everything was fine up until version 2.7.2.

**Comment by ilya-fedin** [comment]
You can't do anything except of removing or changing these settings, they have higher priority now.

**Comment by AngryPhantom** [comment]
@ilya-fedin

>higher priority

Still strange to me why it ignores the above command. So I guess it just got broken in version 2.7.2. Staying with 2.7.1 then. Still an issue/bug since it **should work** as before.

Thanks.

**Comment by ilya-fedin** [comment]
It shouldn't and it won't. X applications should read Xrm settings first, then fallback to fontconfig.

**Comment by ilya-fedin** [comment]
@Aokromes can you close the issue as wontfix?
