### ISSUE TITLE
Crash application after click on incoming message from ShopBot

### ISSUE THREAD

**Issue by judemvm** [telegramdesktop/tdesktop#16202]
### Steps to reproduce
1. buy test product in @TestStore
2. open dialogue with @ShopBot
3. click on incoming message from bot like `You successfully transferred 99,99 € to Shop Bot for “Genuine” Dragon`
4. crash application

### Expected behaviour
open the receipt dialog

### Actual behaviour
crash application

### Configuration
**Operating system:**
Ubuntu 20.04 - (Linux 5.11.15-051115-generic #202104161034 SMP Fri Apr 16 10:40:30 UTC 2021 x86_64 x86_64 x86_64)

**Version of Telegram Desktop:**
2.7.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
snap

**Used theme**:
default
<details><summary><b>Logs</b>:</summary>

- [2021.04.27 14:36:15] Launched version: 2007002, install beta: [FALSE], alpha: 0, debug mode: [TRUE]
- [2021.04.27 14:36:15] Executable dir: /snap/telegram-desktop/2610/usr/bin/, name: telegram-desktop
- [2021.04.27 14:36:15] Initial working dir: /home/user/snap/telegram-desktop/common/
- [2021.04.27 14:36:15] Working dir: /home/user/snap/telegram-desktop/2610/.local/share/TelegramDesktop/
- [2021.04.27 14:36:15] Command line: telegram-desktop -debug
- [2021.04.27 14:36:15] Executable path before check: /snap/telegram-desktop/2610/usr/bin/telegram-desktop
- [2021.04.27 14:36:15] Logs started
- [2021.04.27 14:36:15] Launcher filename: telegram-desktop_telegram-desktop.desktop
- [2021.04.27 14:36:15] IBus portal is present! Using it.
- [2021.04.27 14:36:15] Connecting local socket to /run/user/1000/snap.telegram-desktop/6641694cc3544c28555618437ad5a3f8...
- [2021.04.27 14:36:15] This is the only instance of Telegram, starting server and app...
- [2021.04.27 14:36:15] Moved logging from '/home/user/snap/telegram-desktop/2610/.local/share/TelegramDesktop/log_start0.txt' to '/home/user/snap/telegram-desktop/2610/.local/share/TelegramDesktop/log.txt'!
- [2021.04.27 14:36:15] Primary screen DPI: 96
- [2021.04.27 14:36:15] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
- [2021.04.27 14:36:15] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
- [2021.04.27 14:36:15] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
- [2021.04.27 14:36:15] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
- [2021.04.27 14:36:15] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
- [2021.04.27 14:36:15] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
- [2021.04.27 14:36:15] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
- [2021.04.27 14:36:15] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
- [2021.04.27 14:36:15] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
- [2021.04.27 14:36:15] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
- [2021.04.27 14:36:15] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
- [2021.04.27 14:36:15] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
- [2021.04.27 14:36:15] App Info: reading settings...
- [2021.04.27 14:36:15] App Info: reading encrypted settings...
- [2021.04.27 14:36:15] Lang Info: Loaded cached, keys: 3112
- [2021.04.27 14:36:15] OpenAL Logging Level: 3
- [2021.04.27 14:36:15] Audio Playback Devices: Built-in Audio Analog Stereo;GP107GL High Definition Audio Controller Digital Stereo (HDMI 2)
- [2021.04.27 14:36:15] Audio Playback Default Device: Built-in Audio Analog Stereo
- [2021.04.27 14:36:15] Audio Capture Devices: Built-in Audio Analog Stereo;Monitor of Built-in Audio Analog Stereo;Monitor of GP107GL High Definition Audio Controller Digital Stereo (HDMI 2)
- [2021.04.27 14:36:15] Audio Capture Default Device: Built-in Audio Analog Stereo
- [2021.04.27 14:36:15] Not using D-Bus global menu.
- [2021.04.27 14:36:15] Using Unity launcher counter.
- [2021.04.27 14:36:15] System tray available: [TRUE]
- [2021.04.27 14:36:15] App Info: reading accounts info...
- [2021.04.27 14:36:15] App Info: bad decrypt key, data not decrypted - incorrect password?
- [2021.04.27 14:36:15] App Info: could not decrypt pass-protected key from info file, maybe bad password...
- [2021.04.27 14:36:15] Using SNI tray icon.
- [2021.04.27 14:36:17] App Info: reading accounts info...
- [2021.04.27 14:36:18] App Info: reading encrypted info...
- [2021.04.27 14:36:18] App Info: reading map...
- [2021.04.27 14:36:18] App Info: reading encrypted map...
- [2021.04.27 14:36:18] App Info: reading encrypted user settings...
- [2021.04.27 14:36:18] App Info: encrypted user settings read.
- [2021.04.27 14:36:18] App Info: reading encrypted mtp data...
- [2021.04.27 14:36:18] MTP Info: read keys, current: 5, to destroy: 0
- [2021.04.27 14:36:18] Map read time: 7
- [2021.04.27 14:36:18] App Info: reading encrypted mtp config...
- [2021.04.27 14:36:18] TCP Error: network - Network unreachable
- [2021.04.27 14:36:18] App Info: reading map...
- [2021.04.27 14:36:18] App Info: reading encrypted map...
- [2021.04.27 14:36:18] HTTP Error: network error 99 - Network unreachable
- [2021.04.27 14:36:18] App Info: reading encrypted user settings...
- [2021.04.27 14:36:18] App Info: encrypted user settings read.
- [2021.04.27 14:36:18] App Info: reading encrypted mtp data...
- [2021.04.27 14:36:18] MTP Info: read keys, current: 5, to destroy: 0
- [2021.04.27 14:36:18] Map read time: 1
- [2021.04.27 14:36:18] App Info: reading encrypted mtp config...
- [2021.04.27 14:36:18] TCP Error: network - Network unreachable
- [2021.04.27 14:36:18] HTTP Error: network error 99 - Network unreachable
- [2021.04.27 14:36:18] Export Info: Destroy top bar by controller removal.
- [2021.04.27 14:36:18] Error while inflating gzip file: SVG format check failed
- [2021.04.27 14:36:18] Error while inflating gzip file: SVG format check failed
- [2021.04.27 14:36:18] Native Notification Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
- [2021.04.27 14:36:18] TCP Error: network - Network unreachable
- [2021.04.27 14:36:18] HTTP Error: network error 99 - Network unreachable
- [2021.04.27 14:36:18] TCP Error: network - Network unreachable
- [2021.04.27 14:36:18] HTTP Error: network error 99 - Network unreachable

</details>

**Comment by ntfshard** [comment]
Same on Windows official 2.7.3 build

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/d984c5924d92b2476de333b164bf5cc43e93e53b
