### ISSUE TITLE
All messages showing on the left side

### ISSUE THREAD

**Issue by Jawler** [telegramdesktop/tdesktop#1620]
Since the update to 0.9.24 the client shows all messages on the left side of the window. Since it shows only the pictures and not the names it becomes hard to tell who wrote which message.

**Comment by auchri** [comment]
> This is a feature. When the window gets wider than a specific limit it is considered that this way the messages history could be read easier than in the old layout, when your messages go to the right side. A little bit of a discussion here #1587

**Comment by Jawler** [comment]
Okay, but if i have the same profile picture as someone else it is nearly impossible to have an overview of who wrote which message. Now i can not maximize my window any more. I think a tickbox in options menu should let me decide.

**Comment by Pablohn26** [comment]
@Jawler +1 , please add an option to switch to old style since it is difficult to follow the conversation. I commented that here https://github.com/telegramdesktop/tdesktop/commit/19d395a9466afe866bfa11f42c1c697445d5f1c4#commitcomment-16131703

**Comment by telegramdesktop** [comment]
@Jawler This is a feature, starting from version 0.9.24 in the wide window sizes (like most fullscreen sizes) the messages have one side layout.

We thought through and tested that change and we are sure that this way is better than it was before, although everyone is used to the old way and the new layout seems strange and unfamiliar at first. It is easier to read the conversation when the messages go one after another and not at the different sides of a large window (which is twice as wide as the widest message), the incoming and outgoing can be easily differentiated by user photo _and_ by bubble background color (white vs green). In the wide windows the conversation area always looked ridiculous and there is no way to fill it with content in a reasonable and usable way, but at least now messages are not thrown to the different parts of the screen at random.

So it will be left that way at least for now, with no additional settings for returning to the old layout or smth like that. Sorry if someone strongly dislikes it :(

**Comment by richraid21** [comment]
"We are sure that this way is better" , "It is easier to read" 

Thanks for making up my mind for me /s

**Comment by andenq** [comment]
Maybe someone with experience in working with QT can fix this in a branch?

**Comment by vernazza** [comment]
Then, please, insert a bug to avoid this feature

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.

**Comment by richraid21** [comment]
Thank you very much @telegramdesktop

**Comment by Jawler** [comment]
This is awesome. Thanks for listening to the useres.
