### ISSUE TITLE
Similar to #16163

### ISSUE THREAD

**Issue by iArmann** [telegramdesktop/tdesktop#16219]
Furthermore, I have noticed that this behaviour happens specifically when I start the app without **network connection**.

<details><summary><b>Logs</b>:</summary>
<img src='https://user-images.githubusercontent.com/67087266/116309825-7bf1c880-a7be-11eb-89bc-dde174d85e1b.jpg' />
</details>

**Comment by ilya-fedin** [comment]
#10353
