### ISSUE TITLE
Immediate crash when recording

### ISSUE THREAD

**Issue by hikagura99** [telegramdesktop/tdesktop#16217]
### Steps to reproduce
1. Record an audio

### Expected behaviour
Record an audio

### Actual behaviour
Immediate crash (console says there's a segmentation error)

### Configuration
**Operating system:**
Artix Linux

**Version of Telegram Desktop:**
2.7.3-1

**Installation source (Linux Only)** 
pacman

**Used theme**:
Night mode default

**Comment by ilya-fedin** [comment]
Please check the official binary from desktop.telegram.org

**Comment by mcilloni** [comment]
I can confirm there is an issue with the Arch Linux provided build - I replaced the `telegram-desktop` package with the official build and microphone works fine now.

**Comment by Thaodan** [comment]
I could be still related to newer ffmpeg and so not only a third party issue.

**Comment by ilya-fedin** [comment]
> I could be still related to newer ffmpeg and so not only a third party issue.

If ffmpeg broke backward compatibility in a minor release then I imagine it's a ffmpeg bug

**Comment by shibotto** [comment]
> If ffmpeg broke backward compatibility in a minor release then I imagine it's a ffmpeg bug

FFmpeg 4.4 is a major release.

**Comment by ilya-fedin** [comment]
> FFmpeg 4.4 is a major release.

Well, tdesktop never claimed it's ported to a new major release, so it's a packaging error to build with another major release.

**Comment by Thaodan** [comment]
It doesn't need to since it is not a new major release but a minor release. 
Unless tdesktop uses some private functions it should be fine.

**Comment by ilya-fedin** [comment]
> FFmpeg 4.4 is a major release.



>  it is not a new major release but a minor release

![изображение](https://user-images.githubusercontent.com/17829319/118105249-adc47b00-b3cb-11eb-959a-dbd5abbb5571.png)

**Comment by Thaodan** [comment]
> > FFmpeg 4.4 is a major release.
> 
> > it is not a new major release but a minor release
> 
> ![изображение](https://user-images.githubusercontent.com/17829319/118105249-adc47b00-b3cb-11eb-959a-dbd5abbb5571.png)

Nice bullshit?

**Comment by shibotto** [comment]
> > FFmpeg 4.4 is a major release.
> 
> > it is not a new major release but a minor release

It *is* a new major release:
![news](https://user-images.githubusercontent.com/3816409/118113196-4536c780-b3e6-11eb-85b3-047a27d3946e.png)

If anyone is interested in solving the problem, this is the FFmpeg commit that introduced the breakage: https://github.com/FFmpeg/FFmpeg/commit/827d6fe73d2f5472c1c2128eb14fab6a4db29032

> Nice bullshit?

Please keep the discussion civil. Getting the issue restricted does not help anybody.

**Comment by ilya-fedin** [comment]
> If anyone is interested in solving the problem, this is the FFmpeg commit that introduced the breakage: [FFmpeg/FFmpeg@827d6fe](https://github.com/FFmpeg/FFmpeg/commit/827d6fe73d2f5472c1c2128eb14fab6a4db29032)

I had a talk with @john-preston, he says he doesn't have time to look into it now, so distros need to build tdesktop with ffmpeg 4.3 if they don't want to have non-working tdesktop for a month or something

**Comment by Thaodan** [comment]
Am Donnerstag, 13. Mai 2021, 13:32:26 EEST schrieb Shiba:
> > > FFmpeg 4.4 is a major release.
> > > 
> > > it is not a new major release but a minor release
> 
> It *is* a new major release:
> ![news](https://user-images.githubusercontent.com/3816409/118113196-4536c780
> -b3e6-11eb-85b3-047a27d3946e.png)
> If anyone is interested in solving the problem, this is the FFmpeg commit
> that introduced the breakage:
> https://github.com/FFmpeg/FFmpeg/commit/827d6fe73d2f5472c1c2128eb14fab6a4db
> 29032
Changing the second number in a version makes it a minor release. In any case we are 
fighting about semantics and not about fixing the issue. Thanks for bisecting the issue.

> > Nice bullshit?
> 
> Please keep the discussion civil. Getting the issue restricted does not help
> anybody.
Well he was replying with a trump picture to my reply that doesn't make the issue that 
civil.

**Comment by mcilloni** [comment]
> Changing the second number in a version makes it a minor release.

This is only true if a project follows [semver](https://semver.org). Otherwise, version numbers don't mean a thing except what the authors decide they mean. The first digit in Linux kernel versions, for instance, has had like zero semantic meaning since Linux 2.0 (i.e. linux 3.19->4.0, but it could have been 3.20 as well), and we may argue the dot is only there for stylistic reasons. 
Windows version numbers have also no meaningful value whatsoever (Windows XP was 5.2, Vista was 6.0, 8 was 6.2 and Windows 10 is 10.0), and Systemd uses only a single digit to indicate its release number (plus optionally a dot for bugfixes).
