### ISSUE TITLE
Desktop Notifications stopped working since 2.7.2 if focus assist is turned on and set to priority only

### ISSUE THREAD

**Issue by RidenShark** [telegramdesktop/tdesktop#16215]
Initially, when focus assist was turned on, Telegram used to notify. It no longer notifies. Please put it in the update log if you make drastic changes like this. Due to this, I missed a very important message that required my assistance for an emergency. I am glad someone was able to be there instead of me.

Please provide an option to break through the focus assist. Telegram is always a priority for me. My whole family is on it. Please be responsible when you change things like this without announcing. Thanks.

**Comment by john-preston** [comment]
@RidenShark You can enable native notifications in settings (Settings > Notifications > Use Windows notifications) and then add Telegram to priority apps list in Settings.

**Comment by RidenShark** [comment]
Telegram's notifications are easy to reply right from the notification pop-up though. I feel windows notification is inferior this way. Please restore the previous behaviour or add an option to something like 'notify as priority'.

**Comment by john-preston** [comment]
@RidenShark After adding the app to the list you can enable custom notifications again.

**Comment by RidenShark** [comment]
I checked the list. Telegram doesn't appear there. :(

**Comment by john-preston** [comment]
@RidenShark Even after receiving a native notification? 😰

**Comment by RidenShark** [comment]
![image](https://user-images.githubusercontent.com/66911854/116273843-bbf58300-a79f-11eb-810e-b09f207e9a9f.png)

This is all I have there. 😅 I think this is a very bad UX and a decision in the first place. I see two ways to solve this.

1. Revert to the previous behaviour.
2. Add an option like 'Ignore windows priority' or 'Notify indifferent to priority'. (Sorry, my English is bad.).

**Comment by RidenShark** [comment]
> 
> 
> @RidenShark Even after receiving a native notification? 😰

Yes. I did enable native notification before checking the priority list.

**Comment by RidenShark** [comment]
@john-preston, also I believe it makes sense for Telegram to ignore any focus assist rules because it is Telegram's own notification system. It should only follow Focus Assist rules only when it is selected to the native one. Please consider this too.

**Comment by AkramiPro** [comment]
please make changes back to normal ! its socks that i cant receive any nitice !!!
