### ISSUE TITLE
Client crash when clicking on an invoice link

### ISSUE THREAD

**Issue by rogerfar** [telegramdesktop/tdesktop#16210]
Using latest version of Telegram Windows Desktop (2.7.3) I made a test purchase in the test shop.

Then it shows something that looks like a link to an invoice:

![image](https://user-images.githubusercontent.com/1142915/116248400-14d60480-a729-11eb-9cef-0c0df25f7ccd.png)

It has a hand icon when hovering over, but when clicking it, it will crash the client completely without any errors showing on screen.

**Comment by john-preston** [comment]
@rogerfar Thanks for your report!
