### ISSUE TITLE
Warning "This proxy is not supported by this version"

### ISSUE THREAD

**Issue by mjavadddd** [telegramdesktop/tdesktop#16218]
Telegram Desktop does not support some proxies and writes "This version does not support this proxy, update the program"
### Steps to reproduce
1. Click on this link ( https://t.me/mtproto_ir/17225)
2. Click on "Connect"

### Expected behaviour
Must be connected to a proxy

### Actual behaviour
A warning is displayed that this version does not connect to this proxy

### Configuration
** windows 10 20H2 :**

** 2.7.3 :**

![20210427_225606](https://user-images.githubusercontent.com/83297910/116293128-c453bb00-a7ab-11eb-8772-c04626a39ecb.jpg)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by amirrh6** [comment]
@john-preston I also have faced such issue with some proxies. Please give it a check. Thanks ❤️
