### ISSUE TITLE
After v0.9.24 all my messages go on the left like the person I'm talking with

### ISSUE THREAD

**Issue by optiroot** [telegramdesktop/tdesktop#1621]
Hello. Great job with Telegram. I use it by years but never had to write in the Issues section - good thing!

Now the problem is that after that I upgraded to 0.9.24 all my messages go on the left of the conversation and the problem is present in groups too.
My aspect ratio is 16:9 and I have a 1920x1080 screen. If I reduce the size of the window, messages go back in the same position as they were before upgrading to 0.9.24.
I have Windows 10.
I don't know if the problem is present in other OS too.

There are screenshots for reference:
![t1](https://cloud.githubusercontent.com/assets/12573563/13091123/f0d57d7e-d4f9-11e5-9bc2-b17a4fce9772.PNG)
![t2](https://cloud.githubusercontent.com/assets/12573563/13091130/f47e24bc-d4f9-11e5-8e14-3e125c6dabf9.PNG)

As I said I don't know if this is a bug, but if it is wanted - could we create a poll and see who wants this? I think it was better before.

Thank you for your time and for all your efforts.

**Comment by auchri** [comment]
See #1620

**Comment by telegramdesktop** [comment]
@optiroot This is a feature, starting from version 0.9.24 in the wide window sizes (like most fullscreen sizes) the messages have one side layout.

We thought through and tested that change and we are sure that this way is better than it was before, although everyone is used to the old way and the new layout seems strange and unfamiliar at first. It is easier to read the conversation when the messages go one after another and not at the different sides of a large window (which is twice as wide as the widest message), the incoming and outgoing can be easily differentiated by user photo _and_ by bubble background color (white vs green). In the wide windows the conversation area always looked ridiculous and there is no way to fill it with content in a reasonable and usable way, but at least now messages are not thrown to the different parts of the screen at random.

So it will be left that way at least for now, with no additional settings for returning to the old layout or smth like that. Sorry if someone strongly dislikes it :(

**Comment by vhexs** [comment]
It's a waste of screen space and it looks ugly & confusing. Everyone is used to the way it was already set out, and it's like that on every other messaging app, so why change the standard?

**Comment by optiroot** [comment]
Thank you for the esplicative answer, but as @vhexs said, it's ugly as solution.
I used to type in Telegram in fullscreen, and now if I'm in fullscreen I see all my messages pushed to the left. There is so much space on the right that could be useful for something other. It's wasted in this way.

If really you don't want to bring back the old-messages style, at least add some features - like... another chat? - that on wide screens can use that space.
Considering the thing, precisely just the half of the space is being used.

I know that you want to do improvements, but think at what community (we) say too! So much people use Telegram everyday and I don't think they **really** like messages shown in this way.
Anyway, I wanted to say that I never had any problems in the reading in the old way, because it is adapted to my screen.

I noticed that on Linux text, in 1920x1080 is usually smaller compared to Windows, but you can ever adjust via settings the font size. So I don't really understand which was the problem...

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.

**Comment by vhexs** [comment]
@telegramdesktop that's great, thank you!

**Comment by optiroot** [comment]
Perfect. Than you. Now it's better.
