### ISSUE TITLE
Crash when attaching a file to chat 

### ISSUE THREAD

**Issue by b0xmaks** [telegramdesktop/tdesktop#16224]
### Steps to reproduce
1. Open chat
2. Click on "clip" to attach a file
3. Profit...

### Expected behaviour
A file manager window must open to select and add a file. 

### Actual behaviour
The application simply closes. After starting, it gives the window that it was not correctly closed. 

### Configuration
**Operating system: Debian 10 Buster**

**Version of Telegram Desktop: 2.7.2, 2.7.3**

**Installation source (Linux Only)** - the official website

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Provide a crash report tag that crash report window gives you

**Comment by LaraChicharo** [comment]
Same here, except that my window just freezes after I select an file to send.
Debian 9.
Version of Telegram Desktop: 2.7.4

**Comment by Aokromes** [comment]
try 2.7.5 beta from desktop.telegram.org

**Comment by ilya-fedin** [comment]
@Aokromes looks like reporter is not going to answer, probably it's worth to close the issue...

**Comment by Aokromes** [comment]
@b0xmaks @LaraChicharo
