### ISSUE TITLE
[Feature Request] Search Tool (magnifier tool) for emoji like Android phone

### ISSUE THREAD

**Issue by Almaric78** [telegramdesktop/tdesktop#16228]
Hello, is it possible to have a search tool (magnifier tool) for searching emojis on Desktop App like there is already on Android smartphone ? Thanks a lot 

![image](https://user-images.githubusercontent.com/36954964/116423571-17c41880-a841-11eb-8e62-ce8b43c28071.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2804
