### ISSUE TITLE
No desktop notifications after updating to the latest version on Windows 10

### ISSUE THREAD

**Issue by DemonicArthas** [telegramdesktop/tdesktop#16227]
### Steps to reproduce
1. Launch Telegram
2. Wait for someone with enabled notification to write to you

### Expected behaviour
There should be a popup preview/notification with sound

### Actual behaviour
There's no notification preview nor sound

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.7.0 onwards

**Used theme**: doesn't matter

### Workaround
I've tried disabling/enabling notifications, reinstalling Telegram, restarting my PC - nothing helps. Obviously, the only workaround is to roll back to previous version, then the notifications start working normally, so it's definitely something to do with update.

**Comment by ilya-fedin** [comment]
#16215

**Comment by DemonicArthas** [comment]
> 
> 
> #16215

Got it, thanks.
