### ISSUE TITLE
Crash when switching an account when listening to music through a bot | `NOT an important error `

### ISSUE THREAD

**Issue by TwizCOM** [telegramdesktop/tdesktop#16220]
### Steps to reproduce
1. type in message text field any music bot, for example (not advertising ) , @nowplaybot
2. select a track and press on play button
3. select another account
![image](https://user-images.githubusercontent.com/36485063/116310352-8c03ab00-a7b2-11eb-95c4-8ebc608f1d5f.png)
![image](https://user-images.githubusercontent.com/36485063/116310439-b05f8780-a7b2-11eb-9e6f-618bf399dc66.png)

### Actual behaviour
The app crashed

### Configuration
**Operating system:**
_Windows 7 x64
Windows 10 x64_

**Version of Telegram Desktop:**
_2.7.3 x64_
**Used theme**:
_**Dark**_
<details><summary><b>Logs</b>:</summary>
[2021.04.27 23:39:52] Export Info: Destroy top bar by controller removal.
[2021.04.27 23:39:52] Assertion Failed! "ptr_ != nullptr" pointers:77
</details>

**Comment by ilya-fedin** [comment]
provide a crash report tag, please
