### ISSUE TITLE
ubuntu doesnt have native "browse files", "choose images"

### ISSUE THREAD

**Issue by iamserjo** [telegramdesktop/tdesktop#1622]
Looks ugly what is now. Cant use my recent files ive just created

**Comment by auchri** [comment]
Please search for existing issues before creating new ones.
#987

**Comment by ManuelSchneid3r** [comment]
I am the author of #987. Note that #987 is *not* about the filechooser. #987 is about the *application style* in general. Check #982 for native filechooser.

**Comment by john-preston** [comment]
In the latest 0.9.57 version gtk file chooser should be used if it is available. Please check.
