### ISSUE TITLE
[Feature Request] Blur images

### ISSUE THREAD

**Issue by RustemB** [telegramdesktop/tdesktop#16222]
There are times when you flip through a chat room in front of people, and there's content that you wouldn't want others to see. Like images with secret information

**Comment by etircopyh** [comment]
You could tell "people" to turn round.

**Comment by NotStatilko** [comment]
Tbh blurring an image from peoples that you don't messaged can be a good feature. I.e images and videos will be only show on tap or after you answer. The "readed" badge too.

> There are times when you flip through a chat room in front of people, and there's content that you wouldn't want others to see. Like images with secret information

Just use private chats for this.

**Comment by RustemB** [comment]
> Just use private chats for this.
I mean in group chats. When someone sends "bad" photos but there is your mum in front of you :D

**Comment by NotStatilko** [comment]
> > Just use private chats for this.
> > I mean in group chats. When someone sends "bad" photos but there is your mum in front of you :D

You can disable auto loading images in Settings

**Comment by etircopyh** [comment]
Yeah, actually this "feature" is already there. Also there is some "sensitive content filtering" but I'm not sure what it does.
