### ISSUE TITLE
Telegram desktop 2.7.4 crashes when recording a voice message 

### ISSUE THREAD

**Issue by barfin** [telegramdesktop/tdesktop#16234]
### Steps to reproduce
1. record a voice
2. crash

### Expected behaviour
it should record voice normally

### Actual behaviour
telegram crashes

### Configuration
**Operating system:** Arch Linux (Kernel 5.11.16-zen)

**Version of Telegram Desktop:** 2.7.4

**Installation source (Linux Only)**: official arch linux repos

**audio server**: Pulseaudio 14.2

**Audio card**: realtek alc1150

**Used theme**: default

<details><summary><b>Logs</b>:</summary>

╰─ telegram-desktop 

(telegram-desktop:41859): lib_base-WARNING **: 14:07:06.203: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
lib_base-Message: 14:07:06.205: This can be ignored by setting DESKTOP_APP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
lib_base-Message: 14:07:06.205: GTK integration can be disabled by setting DESKTOP_APP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to some features being unavailable.

(telegram-desktop:41859): Telegram-WARNING **: 14:07:06.445: Application was built without embedded fonts, this may lead to font issues.
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
qt.svg: Error while inflating gzip file: SVG format check failed
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[1]    41859 segmentation fault (core dumped)  telegram-desktop

</details>

**Comment by Aokromes** [comment]
arch package bug.

**Comment by IlyaIndigo** [comment]
Is it the same on openSUSE?
Is this also an openSUSE problem?
At least give me the details.

**Comment by Aokromes** [comment]
> Is it the same on openSUSE?
> Is this also an openSUSE problem?
> At least give me the details.

if they linked with ffmpeg 4.4 yes, the bug is the same, you need to wait to them to update to latest telegram desktop source or use official packages.

**Comment by IlyaIndigo** [comment]
> > Is it the same on openSUSE?
> > Is this also an openSUSE problem?
> > At least give me the details.
> 
> if they linked with ffmpeg 4.4 yes, the bug is the same, you need to wait to them to update to latest telegram desktop source or use official packages. (desktop.telegram.org packages)

Is the problem fixed in telegram-desktop or in ffmpeg?

**Comment by Aokromes** [comment]
> > > Is it the same on openSUSE?
> > > Is this also an openSUSE problem?
> > > At least give me the details.
> > 
> > 
> > if they linked with ffmpeg 4.4 yes, the bug is the same, you need to wait to them to update to latest telegram desktop source or use official packages. (desktop.telegram.org packages)
> 
> Is the problem fixed in telegram-desktop or in ffmpeg?

it's fixed on telegram sources and on official desktop.telegram.org binaries. i don't know on distribution telegram-desktop binaries.

**Comment by IlyaIndigo** [comment]
@Aokromes Thank you!
