### ISSUE TITLE
[QUESTION]: tdesktop and tgowt

### ISSUE THREAD

**Issue by raghavgururajan** [telegramdesktop/tdesktop#16230]
Hi Team,

Is there a way to know which commit of tgowt to use for a particular version of tdesktop?

Regards,
RG.

**Comment by Aokromes** [comment]
you may use history of github over the build file of your platform.

**Comment by raghavgururajan** [comment]
@Aokromes 
Could you explain in other words please?

**Comment by Aokromes** [comment]
on what plataform (macos, linux or windows) are you trying to compile telegram?

**Comment by raghavgururajan** [comment]
@Aokromes
Platform: GNU/Linux
OS: Guix System

I have already packaged tdesktop for Guix (https://guix.gnu.org/en/packages/telegram-desktop-2.5.9/).

I am trying to update to 2.7.3. But not sure which commit of tgowt to use.

It'd be great if README of tdesktop mentions which commit of tgowt to use, whenever new release for tdesktop is made.

**Comment by Aokromes** [comment]
> tgowt

looking at windows build changelog it doesn't looks they are tied to versions.

**Comment by raghavgururajan** [comment]
@Aokromes 
When I was doing the initial packaging, @ilya-fedin told me to use a specific tgowt commit instead or current master.
I wonder what it is now.

**Comment by ilya-fedin** [comment]
Well, master is broken from time to time. Unfortunately, there's no good answer to this question, you can't know which commit should be used if you're not involved in development.

**Comment by noiseless** [comment]
From my point of view, it makes sense to use the version used to build the snap package. Isn't it?

https://github.com/telegramdesktop/tdesktop/blob/dev/snap/snapcraft.yaml#L427

**Comment by mikhailnov** [comment]
+1, I think the easiest sulution would be git tag in tg_owt of the same version as tdesktop
