### ISSUE TITLE
Text you sent is on the left when in fullscreen mode

### ISSUE THREAD

**Issue by Aedirn** [telegramdesktop/tdesktop#1623]
With the last update if your client is in fullscreen, the messages you send are shown on the left with the messages you received.

![image](https://cloud.githubusercontent.com/assets/1337268/13092422/234620c8-d500-11e5-87cf-181314776f9e.png)

**Comment by auchri** [comment]
Please search for existing issues before creating new ones.
#1620

**Comment by telegramdesktop** [comment]
@Aedirn This is a feature, starting from version 0.9.24 in the wide window sizes (like most fullscreen sizes) the messages have one side layout.

We thought through and tested that change and we are sure that this way is better than it was before, although everyone is used to the old way and the new layout seems strange and unfamiliar at first. It is easier to read the conversation when the messages go one after another and not at the different sides of a large window (which is twice as wide as the widest message), the incoming and outgoing can be easily differentiated by user photo _and_ by bubble background color (white vs green). In the wide windows the conversation area always looked ridiculous and there is no way to fill it with content in a reasonable and usable way, but at least now messages are not thrown to the different parts of the screen at random.

So it will be left that way at least for now, with no additional settings for returning to the old layout or smth like that. Sorry if someone strongly dislikes it :(

**Comment by Pablohn26** [comment]
As I commented here https://github.com/telegramdesktop/tdesktop/commit/19d395a9466afe866bfa11f42c1c697445d5f1c4#commitcomment-16131703  could be possible to add an option to switch to old style? If a conversation is between people with no picture or almost the same picture it is difficult to follow it.

**Comment by Pablohn26** [comment]
In addition, when you select text the colour is close to be the same than the other person. 
Could you, at least, open this issue to skip duplicates and talk about that?

**Comment by vhexs** [comment]
I agree, it's confusing and annoying with it all on the left. Not a good UX.

**Comment by eckcon** [comment]
I have to disagree with @telegramdesktop, because usually you do NOT read your own messages while writing with somebody, you just look on the left side of the chat area (where your chatpartners messages are)... Now with all messages on the left it's far less easy to see in milliseconds (and without thinking about it) if your chat partner wrote you.
If you scroll up the history, @telegramdesktop might be right and it could be better to see everything on the left, but at the moment you are writing, the old layout is way better in my opinion.

**Comment by eckcon** [comment]
I might be the only one, but I would even say: The more far away and less distracting your own messages are in a conversation, the better ;-)

**Comment by vhexs** [comment]
What if, as you scrolled up, your messages seamlessly moved to the left? Hmmmmmmmm...

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.
