### ISSUE TITLE
Linux: Call Window has no Title

### ISSUE THREAD

**Issue by miili** [telegramdesktop/tdesktop#16232]
Window of the call has no title

![image](https://user-images.githubusercontent.com/4992805/116467120-9e8fea00-a86f-11eb-8c8d-401e857dad1b.png)

### Steps to reproduce
1. Install Linux Client
2. Start a call

### Expected behaviour
Window title for call window.

### Actual behaviour
Call window has no title.

### Configuration
Debian 10

2.7.4

Installed from Telegram.org website.

**Used theme**:
Dark

**Comment by ilya-fedin** [comment]
#10243
