### ISSUE TITLE
Crash when attaching a file to chat on Fedora

### ISSUE THREAD

**Issue by wedersonals** [telegramdesktop/tdesktop#16239]
### Steps to reproduce
1. Open chat
2. Click on "clip" to attach a file
3. Open or Cancel 

### Expected behaviour
If any files are opened, send them. If the file selection screen is canceled, the system will return to normal.

### Actual behaviour
The application is stuck and does not respond to any type of event (keyboard or mouse)

### Configuration
**Operating system:*Fedora 25*

**Version of Telegram Desktop:*2.7.4*

**Installation source (Linux Only)** - the official website

**Used theme**: Gnome

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by wedersonals** [comment]
Until this morning while using version 2.7.3 everything was normal. There were no updates to the operating system. The only change was the version of Telegram automatically to 2.7.4.

The only way to close the application is through the kill PID .

[log.txt](https://github.com/telegramdesktop/tdesktop/files/6401551/log.txt)

**Comment by wedersonals** [comment]
> plz post the crash id you get on next startup.

This does not happen. When the application crashes, I kill the process and start again. And the application opens normally without presenting the crash id.

**Comment by Aokromes** [comment]
try to run it under gdb.

**Comment by Aokromes** [comment]
ps. fedora 25??? that's EOL near 4 years ago.

**Comment by wedersonals** [comment]
I researched how to run in debug mode and found
Telegram -debug
I compressed all the logs generated in the folder. Both log.txt and those in the DebugLogs folder.

[telegram_logs.zip](https://github.com/telegramdesktop/tdesktop/files/6402031/telegram_logs.zip)

**Comment by ilya-fedin** [comment]
> When the application crashes, I kill the process and start again.

If you have to kill the process, that mean it doesn't crash, but deadlocks instead. You should run Telegram via gdb, do actions to make it freeze, trap it and get a backtrace.

**Comment by ilya-fedin** [comment]
Actually, a record of dbus messaging via bustle and xdg-desktop-portal version would be more valuable, I think

**Comment by ilya-fedin** [comment]
Looks like author went MIA, probably it's worth to merge the issue with #16224
