### ISSUE TITLE
Telegram Crash when trying to record an audio message on Arch Linux

### ISSUE THREAD

**Issue by Myphz** [telegramdesktop/tdesktop#16249]
### Steps to reproduce
1.  Open Telegram
2.  Try to record an audio message to someone
3.  Telegram crashes with segmentation fault

### Configuration
**Operating system: Arch Linux with 5.11.16-arch1-1 linux kernel**

**Version of Telegram Desktop: 2.7.4**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
pacman -S telegram-desktop

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
[daniel@archlinux ~]$ telegram-desktop
(telegram-desktop:6815): lib_base-WARNING **: 17:43:51.131: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
lib_base-Message: 17:43:51.132: This can be ignored by setting DESKTOP_APP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
lib_base-Message: 17:43:51.132: GTK integration can be disabled by setting DESKTOP_APP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to some features being unavailable.

(telegram-desktop:6815): Telegram-WARNING **: 17:43:51.138: Application was built without embedded fonts, this may lead to font issues.

(telegram-desktop:6815): Gtk-WARNING **: 17:43:51.244: Failed to parse /home/daniel/.config/gtk-3.0/settings.ini: Key file does not have group “Settings”
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
Segmentation fault (core dumped)
</details>

**Comment by ilya-fedin** [comment]
It's a problem of arch linux package. Please switch to official binary, snap or flatpak package.
