### ISSUE TITLE
I installed the latest version from flatpak in my linux machine but I am not able to see or create quizzes

### ISSUE THREAD

**Issue by harshverma27** [telegramdesktop/tdesktop#16243]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Please fill the template

**Comment by ilya-fedin** [comment]
@Aokromes can you close this invalid issue?
