### ISSUE TITLE
[Feature Request] Allow users to disable noise reduction in group voice calls

### ISSUE THREAD

**Issue by SCLeoX** [telegramdesktop/tdesktop#16248]
### Is your feature request related to a problem?
I was trying to stream some music from my computer to a group voice call (using some audio router that allows me to redirect speaker output to a virtual microphone). However, the indicator keeps flickering back and forth between "listening" and "speaking". People also reported the audio gets cut off from time to time. It seems that Telegram is trying to do background noise reduction, and accidentally cut off some music.

### Describe the solution you'd like
An option to disable noise reduction

### Describe alternatives you've considered
A slider that allows you to adjust noise reduction level.

### Additional context
^

**Comment by Aokromes** [comment]
such request must be platform wide, https://bugs.telegram.org

**Comment by SCLeoX** [comment]
@Aokromes Why must this be platform wide? Is this done on the server? Pardon my ignorance but doesn't a majority of other voice chat applications do noise reduction on the client? (For example, as far as I know, Skype, discord, TeamSpeak, and steam voice chat all do this on the client.)
