### ISSUE TITLE
App takes a lot of time to open

### ISSUE THREAD

**Issue by rtomasa** [telegramdesktop/tdesktop#16240]
### Steps to reproduce
1. Update to Fedora 34
2. Install Telegram from Software via Flathub
3. Open the application

### Expected behaviour
Application should start immediately

### Actual behaviour
App takes almost 30 secs to open

### Configuration
**Operating system:** Fedora 34

**Version of Telegram Desktop:** 2.7.4

**Installation source (Linux Only)** - flatpak via Gnome Software

**Used theme**: default vanilla Gnome 40 theme

<details><summary><b>Logs</b>:</summary>
$ flatpak run  org.telegram.desktop

(telegram-desktop:2): lib_base-WARNING **: 23:52:13.070: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
lib_base-Message: 23:52:13.071: This can be ignored by setting DESKTOP_APP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
lib_base-Message: 23:52:13.071: GTK integration can be disabled by setting DESKTOP_APP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to some features being unavailable.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
AL lib: (EE) Error enumerating devices: Capture Stream did not get ready (Timeout)
AL lib: (EE) Error enumerating devices: Capture Stream did not get ready (Timeout)
AL lib: (EE) Error enumerating devices: Capture Stream did not get ready (Timeout)
error: : cannot open
error: : cannot open
error: : cannot open
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
QCoreApplication::postEvent: Unexpected null receiver
QObject::~QObject: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
</details>

### Workaround

I found out that connecting a webcam or microphone, the app starts immediately as expected and the following lines do not appears in the log: `AL lib: (EE) Error enumerating devices: Capture Stream did not get ready (Timeout)`

**Comment by ilya-fedin** [comment]
It is a pipewire bug, not a tdesktop bug
