### ISSUE TITLE
Linux: Crash when downloading files

### ISSUE THREAD

**Issue by rubyco-me** [telegramdesktop/tdesktop#16245]
I experience the issue since the last update to 2.7.4. 
Every time I try to download a file send to me in groups or single chats, the app crashes. I haven't tried it with files other than PDFs.

# Steps to reproduce
1. Receive a (pdf) file, send to you
2. Click to download it
3. The app crashes

# Details
Linux (Debian 10 Buster)
Telegram desktop 2.7.4
Installed from TAR archive from official website (telegram.org)

**Comment by Aokromes** [comment]
plz, post crash id on next restart, or if you don't get crash id, run telegram under gdb

**Comment by ilya-fedin** [comment]
> * Receive a (pdf) file, send to you
> 
> * Click to download it
> 
> * The app crashes

Just received a pdf, no crash

**Comment by rubyco-me** [comment]
> plz, post crash id on next restart, or if you don't get crash id, run telegram under gdb

Haven't gotten any crash id. Gotta try to reproduce while running under gbd.

**Comment by ilya-fedin** [comment]
doesn't coredumpctl have a dump of that crash?

**Comment by rubyco-me** [comment]
Hey, 
Haven't gotten around to checking with gdb until this moment. When running the executable under gdb and trying to reproduce the error, it says SIGSEGV, so it seems to be a segmentation fault. 
Maybe interesting, that Ifound a workaround, too: When the option "Ask download path for each file" is deactivated, the error does not occur. In this case, the files are just downloaded into the download folder.

Maybe this helps resolving the issue. thx for maintaining Telegram!

**Comment by ilya-fedin** [comment]
>  When running the executable under gdb and trying to reproduce the error, it says SIGSEGV, so it seems to be a segmentation fault.

yeah, you should get a backtrace with `bt full`

> When the option "Ask download path for each file" is deactivated, the error does not occur. In this case, the files are just downloaded into the download folder.

Can't reproduce with enabled option either

> Maybe this helps resolving the issue. thx for maintaining Telegram!

Does this mean you won't provide backtrace and the issue can be closed?

**Comment by rubyco-me** [comment]
bt full says:
Thread 1 "Telegram" received signal SIGSEGV
0x0000000004179b9a in ?? ()
(gdb) bt full
#0  0x0000000004179b9a in ?? ()
No symbol table info available.
#1  0x000000000417aecf in ?? ()
No symbol table info available.
#2  0x0000000004177fef in wl_proxy_marshal_array_constructor_versioned ()
No symbol table info available.
#3  0x00000000041782ad in wl_proxy_marshal_constructor ()
No symbol table info available.
#4  0x00007fffba5c5389 in im_module_init ()
   from /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so
No symbol table info available.
#5  0x00007ffff604bdeb in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#6  0x00007ffff7c83351 in g_type_module_use ()
   from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#7  0x00007ffff604c62c in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#8  0x00007ffff604d27b in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#9  0x00007ffff604d382 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#10 0x00007ffff5fe028c in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#11 0x00007ffff5fe6e45 in gtk_entry_set_placeholder_text ()
   from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#12 0x00007ffff7c64980 in g_object_setv ()
   from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#13 0x00007ffff7c658ce in g_object_set_property ()
   from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#14 0x00007ffff5f5afed in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#15 0x00007ffff5f5c6b5 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging-- <RET>
No symbol table info available.
#16 0x00007ffff5f5e15d in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#17 0x00007ffff77616b2 in ?? ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#18 0x00007ffff77627f6 in g_markup_parse_context_parse ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#19 0x00007ffff5f5e576 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#20 0x00007ffff5f593e4 in gtk_builder_extend_with_template ()
   from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#21 0x00007ffff61bad07 in gtk_widget_init_template ()
   from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#22 0x00007ffff60af58a in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#23 0x00007ffff7c80107 in g_type_create_instance ()
   from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#24 0x00007ffff7c62548 in ?? ()
   from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#25 0x00007ffff7c63fad in g_object_newv ()
   from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#26 0x00007ffff5f5b0c2 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#27 0x00007ffff5f5c6b5 in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#28 0x00007ffff5f5e15d in ?? () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#29 0x00007ffff77616b2 in ?? ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0

Sorry if you need to instruct me a little on how to extract the needed information, I'm not that familiar with gdb.

**Comment by ilya-fedin** [comment]
Already fixed on dev branch

**Comment by rubyco-me** [comment]
alright looking forward to it, thx.

**Comment by rubyco-me** [comment]
alright looking forward to it, thx
