### ISSUE TITLE
Escape should minimize window

### ISSUE THREAD

**Issue by Dabuka** [telegramdesktop/tdesktop#1624]
Escape should minimize window, it'll greatly improve usability. Minimizing with ctrl + F4 or alt + F4 is too difficult.

Common use-case:
1. Open with incoming notification
2. Send answer
3. Hit escape and continue work.

**Comment by auchri** [comment]
and what's about <kbd>ctrl</kbd> + <kbd>w</kbd>?

**Comment by Dabuka** [comment]
That's better, thanks. But still ctrl in use. Now Escape is meaningless - closing current chat.

**Comment by auchri** [comment]
Duplicate #1367

**Comment by telegramdesktop** [comment]
@Dabuka This should be done by a reply-from-notification feature.
