### ISSUE TITLE
Linux: Very high RAM usage

### ISSUE THREAD

**Issue by phoe** [telegramdesktop/tdesktop#16254]
### Steps to reproduce
1. Keep Telegram running for several days.
2. Observe it taking almost 1.9 GB of RAM.

![Zrzut ekranu z 2021-05-01 14-11-46](https://user-images.githubusercontent.com/15045546/116782040-2d2a8400-aa87-11eb-8349-e7adc9cccec9.png)

### Configuration
Debian sid, Telegram 2.7.4, installed from the official website, dark theme.

**Comment by ilya-fedin** [comment]
#16084

**Comment by phoe** [comment]
Thanks - moving the discussion there.
