### ISSUE TITLE
 crashing constantly

### ISSUE THREAD

**Issue by AmidoNewsInside** [telegramdesktop/tdesktop#16251]
### Steps to reproduce
1. Download audio, receive message, it's random and constantly
2. 
3. 

### Expected behaviour
that this random and constantly crashes stop

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system: windows 10 20h2 build 19042.928**

**Version of Telegram Desktop:**
2.7.4

**Used theme**:
Dark/Night
<details><summary><b>Logs</b>:4.30 20:04:51]
[log.txt](https://github.com/telegramdesktop/tdesktop/files/6408459/log.txt)

Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
provide a crash report tag
