### ISSUE TITLE
Spellcheck crashes the app

### ISSUE THREAD

**Issue by serveral1** [telegramdesktop/tdesktop#16258]
### Steps to reproduce
1. Open telegram
2. Type anything that triggers the spellchecker
3. Crash

### Expected behaviour
Spellchecker should work as intended without crashing the app

### Actual behaviour
Spellchecker is currently crashing the app, turning it off seems to get rid of the crashes.

### Configuration
**Operating system:**
Windows 10 Enterprise LTSC. Ver: 1809. OS Build: 17763.1879
**Version of Telegram Desktop:**
2.7.4
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Dark
<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/6410753/log.txt)
</details>

**Comment by john-preston** [comment]
Can you see if there are any .dmp files after such crashes in "tdata/dumps" folder near the Telegram.exe?

**Comment by serveral1** [comment]
> 
> 
> Can you see if there are any .dmp files after such crashes in "tdata/dumps" folder near the Telegram.exe?

[dump.zip](https://github.com/telegramdesktop/tdesktop/files/6423089/dump.zip)
here's the dump file belonging to that specific log

**Comment by serveral1** [comment]
turns out my system's spellchecker files were corrupted (along with a bunch of other ones due to hdd failures. i'm now on a fresh new install) and that seems to have been the reason behind the crashes. sorry for the inconvenience.
