### ISSUE TITLE
Mark read on notification right mouse click.

### ISSUE THREAD

**Issue by Dabuka** [telegramdesktop/tdesktop#1625]
Currently there is no way to mark chat read without opening main window.

And it's annoying to open (then close) main window just to mark "ok" message read.

It'll be great to mark chat read with right mouse click on notification box.

**Comment by shark0der** [comment]
Right know I'm using the right click to close the notification. Perhaps there should be ways to perform both actions, one for closing and another for marking the conversations as read. My suggestion would be to either leave the current feature as it is (closing the notification) and mark messages as read with ctrl/cmd+click or add a button to the notification for marking the messages as read.

**Comment by jhalt** [comment]
:-1: I use this to dismiss notifications on my desktop before I have the chance to actually read the contents of the message.

**Comment by jhalt** [comment]
@Dabuka: Can you clarify whether you mean the pop-up notification or the in the app?

**Comment by Dabuka** [comment]
@jhalt pop-up. The main idea is not to open main window (and not close it after).

**Comment by shark0der** [comment]
This probably can be added in the application's tray menu.

**Comment by jhalt** [comment]
@Dabuka: Ah, I understand. I respect your idea, but in my use-case, I right-click to dismiss notifications when I don't have the time to actually read the contents of the message. In my case, people may get the wrong impression that I read their message when I really didn't.

Completely respect the idea, just wanted to share another perspective

**Comment by haevalencia** [comment]
yes please

**Comment by auchri** [comment]
Use the new [reactions of GitHub](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) on **the first entry of this issue** instead of creating unnecessary `yes please` comments.

**Comment by Akronix** [comment]
I see more #1625 more than this one, since the mouse actions are already taken and can be much less intuitive.

**Comment by stek29** [comment]
You can just reply with empty message

**Comment by Dabuka** [comment]
And you need two steps for this. If you just want to make "ok" message read nothing is less userfriendly. Actually i'd be pretty annoyed even finding "mark as read" button on popup (better right click the whole notification), but it's better than nothing.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4393 better as generic ticket.
