### ISSUE TITLE
UI freeze after searching while uploading grouped files (album?)

### ISSUE THREAD

**Issue by ixzh** [telegramdesktop/tdesktop#16250]
### Steps to reproduce
1. upload some files with "Group Items" ticked
2. ctrl+F to search for a string and jump to any of the results
3. navigate down by clicking the down arrow
![image](https://user-images.githubusercontent.com/14981695/116726775-53fca200-aa16-11eb-81b5-22da581d7380.png)

### Expected behaviour
jump to the latest message

### Actual behaviour
UI freezes, has to restart the app (no it's not uploading the remaining files in the background as after restart the whole unfinished group is gone)

### Configuration
**Operating system:**
Arch + xmonad
**Version of Telegram Desktop:**
2.7.4
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
AUR
**Used theme**:
none
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
i vote another arch only bug, try official package from desktop.telegram.org

**Comment by ixzh** [comment]
> i vote another arch only bug, try official package from desktop.telegram.org

hmmm so it is arch specific...let me try and report back here.

**Comment by ixzh** [comment]
installed from desktop.telegram.org, no such problem.

**Comment by ixzh** [comment]
hrrr I install the latest official desktop app from telegram site. and this problem persists as above...

**Comment by ixzh** [comment]
Version 2.7.5 Beta
