### ISSUE TITLE
Saving file dialog: focus in wrong field causing keyboard Enter not work

### ISSUE THREAD

**Issue by mikkovedru** [telegramdesktop/tdesktop#16256]
### Steps to reproduce
1. Have a picture in a chat (even with yourself)
2. Right click on the picture and chose "Save image as...". The saving window shows up with the file name selected.
3. BUG. Unfortunately pressing Enter does not save the file in the default directory because the focus is still in the "chat text typing" field.
![image](https://user-images.githubusercontent.com/2521942/116791161-291b5800-aac1-11eb-8ea8-271ac20987ff.png)

### Expected behaviour
Pressing "Enter" on the keyboard should save the file.

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Linux Mint Cinnamon 20.1

**Version of Telegram Desktop:**
2.7.4.

**Installation source (Linux Only)**:
Official apt.

**Comment by ilya-fedin** [comment]
Sounds like a bug in your window manager

**Comment by ilya-fedin** [comment]
> **Version of Telegram Desktop:**
> 2.7.4.
> 
> **Installation source (Linux Only)**:
> Official apt.

One of these fields is wrong since Linux Mint 20 is based on Ubuntu 20.04 (Focal) and it has telegram-desktop 2.1.7 in its repos
https://packages.ubuntu.com/focal-updates/telegram-desktop

**Comment by ilya-fedin** [comment]
Can't reproduce in my Linux Mint 20 VM with official binary.

**Comment by mikkovedru** [comment]
I was in full belief that the Telegram I have came via apt. I was wrong and I apologize.

I installed the older version (2.1.7) from apt and have confirmed that the bug doesn't exist in that version.

So this issue can be closed.

While I was switching between the apt version and the newest manually installed versions, I was constantly losing settings - I had to constantly change them each time after switching from one version to another. Is this normal? Should I report a bug?

**Comment by ilya-fedin** [comment]
That's normal, downgrade is not supported. Please note two things:
1. If you will encounter any bug with that version, you can't report here, old versions aren't supported.
2. Server-side developers disable message update queues for old versions at some point. You may stop receive message notifications (if they are even work at that version still).
