### ISSUE TITLE
Telegram does not trigger notifications in a certain situationinxi

### ISSUE THREAD

**Issue by uluchann** [telegramdesktop/tdesktop#16263]
### Steps to reproduce
1. assuming you are **device A**; open a conversation with **device B**
2. get that chat window out of focus on **device A** (i.e. open a web browser in front of it)
3. send a message from **device B** to **device A**

### Expected behaviour
it should "always" send a notification when the chat is out of focus.
### Actual behaviour
it does not show a notification at all. also; (from **device B**'s point of view) **device A** instantly shows as "online" and that message which was not notified marks as "read".

### Configuration
**Operating system:** 
Linux, Manjaro XFCE4

**Version of Telegram Desktop:**
this happens in 2.7.2 and 2.7.1 ; but as a temporary solution; I downgraded to 2.6 and this bug is non-existent at the moment.

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Pacman (official repositories) (community)
**Used theme**:
does not matter
<details><summary><b>Logs</b>:</summary>

inxi -Fxz output (just in case):

`System:
  Kernel: 5.9.16-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.0 
  Desktop: Xfce 4.16.0 Distro: Manjaro Linux base: Arch Linux 
Machine:
  Type: Laptop System: ASUSTeK product: X550VC v: 1.0 serial: <filter> 
  Mobo: ASUSTeK model: X550VC v: 1.0 serial: <filter> 
  UEFI: American Megatrends v: X550VC.222 date: 01/22/2014 
CPU:
  Info: Dual Core model: Intel Core i5-3230M bits: 64 type: MT MCP 
  arch: Ivy Bridge rev: 9 cache: L2: 3 MiB 
  flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 20760 
  Speed: 1197 MHz min/max: 1200/3200 MHz Core speeds (MHz): 1: 1197 2: 1197 
  3: 1197 4: 1195 
Graphics:
  Device-1: Intel 3rd Gen Core processor Graphics vendor: ASUSTeK 
  driver: i915 v: kernel bus-ID: 00:02.0 
  Device-2: NVIDIA GF117M [GeForce 610M/710M/810M/820M / GT 
  620M/625M/630M/720M] 
  vendor: ASUSTeK driver: nouveau v: kernel bus-ID: 01:00.0 
  Device-3: Chicony USB2.0 HD UVC WebCam type: USB driver: uvcvideo 
  bus-ID: 1-1.3:4 
  Display: x11 server: X.Org 1.20.11 driver: loaded: intel,nouveau 
  unloaded: modesetting resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 4000 (IVB GT2) 
  v: 4.2 Mesa 21.0.3 direct render: Yes 
Audio:
  Device-1: Intel 7 Series/C216 Family High Definition Audio vendor: ASUSTeK 
  driver: snd_hda_intel v: kernel bus-ID: 00:1b.0 
  Sound Server-1: ALSA v: k5.9.16-1-MANJARO running: yes 
  Sound Server-2: JACK v: 0.125.0 running: no 
  Sound Server-3: PulseAudio v: 14.2 running: yes 
Network:
  Device-1: Qualcomm Atheros AR9485 Wireless Network Adapter 
  vendor: AzureWave driver: ath9k v: kernel port: e000 bus-ID: 03:00.0 
  IF: wlp3s0 state: up mac: <filter> 
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: ASUSTeK driver: r8169 v: kernel port: d000 bus-ID: 04:00.2 
  IF: enp4s0f2 state: down mac: <filter> 
Bluetooth:
  Device-1: IMC Networks Atheros AR3012 Bluetooth 4.0 Adapter type: USB 
  driver: btusb v: 0.8 bus-ID: 1-1.1:3 
  Report: bt-adapter ID: hci0 rfk-id: 1 state: down 
  bt-service: enabled,running rfk-block: hardware: no software: no 
  address: <filter> 
Drives:
  Local Storage: total: 698.64 GiB used: 82.59 GiB (11.8%) 
  ID-1: /dev/sda vendor: Western Digital model: WD7500BPVT-75A1YT0 
  size: 698.64 GiB 
Partition:
  ID-1: / size: 686.38 GiB used: 82.59 GiB (12.0%) fs: ext4 dev: /dev/sda2 
  ID-2: /boot/efi size: 299.4 MiB used: 280 KiB (0.1%) fs: vfat 
  dev: /dev/sda1 
Swap:
  Alert: No swap data was found. 
Sensors:
  System Temperatures: cpu: 61.0 C mobo: N/A 
  Fan Speeds (RPM): cpu: 2900 
Info:
  Processes: 213 Uptime: 56m Memory: 3.73 GiB used: 2.09 GiB (55.9%) 
  Init: systemd Compilers: gcc: 10.2.0 Packages: 1431 Shell: Bash v: 5.1.0 
  inxi: 3.3.04 ` </details>

**Comment by ilya-fedin** [comment]
it's already fixed in 2.7.4
