### ISSUE TITLE
Instant crash 

### ISSUE THREAD

**Issue by feiercrack** [telegramdesktop/tdesktop#16264]
Steps to reproduce:
just start TelegramDesktop Windows x64

Expected behaviour:
Normal use of the App

Actual behaviour:
instant crash 

Configuration:
Operating system: Windows 10 21h1 build 19043.928  16GB DDR4 RAM

Version of Telegram Desktop:
newest 2.7.4 x64 from 28th April 2021

Used theme:
Dark/Night

crash log sent via App.

Why is there "Platform: Windows32Bit" standing? I used the x64 .exe !

**Comment by ilya-fedin** [comment]
> crash log sent via App.

Post the crash report tag.

**Comment by shapeshifterincontext** [comment]
I am also experiencing crashing on MX Linux desktop.
I ran it from the terminal and received the following when it crashed:

> $ telegram-desktop
> corrupted size vs. prev_size
> Aborted

**Comment by ilya-fedin** [comment]
@shapeshifterincontext provide a backtrace from gdb

**Comment by shapeshifterincontext** [comment]
Hi sorry I've never done a backtrace before, been trying to work out how to do it. GDB has a fault in it at present, I've downloaded EDB but can't seem to find any lay instructions.

**Comment by ilya-fedin** [comment]
```
gdb ./Telegram
run
```
make it crash
```
bt full
```

**Comment by shapeshifterincontext** [comment]
I use 'gdb telegram-desktop'
It responds saying (amongst lots of stuff) 'warning unable to demangle', 'unable to dump core', 'problem internal with dgb has been detected', if I continue with the debugging, it then tells me 'no debugging symbols found'.

**Comment by ilya-fedin** [comment]
> I use 'gdb telegram-desktop'

where you got telegram-desktop from?

**Comment by shapeshifterincontext** [comment]
I use Linux not Windows, I realise I tacked on my comment to a Windows complaint, I thought it was helpful to say that others have the same? issue. I probably shouldn't have should I, sorry about that.

**Comment by ilya-fedin** [comment]
> I use Linux not Windows

That's why I'm asking that. The fact you saying you start it via `telegram-desktop` looks like you're using some third-party package instead of official binary from https://desktop.telegram.org. These third-party packages aren't supported here since usually they're old or have modified code.

**Comment by shapeshifterincontext** [comment]
Hang on I'll check where I installed it from.

**Comment by shapeshifterincontext** [comment]
Sorry for delay, it came from the Debian Buster stable repo, version 1.5.11-1, I installed it through the MX-Linux package installer.

**Comment by ilya-fedin** [comment]
You should migrate to the official version in order to be able to report here

**Comment by shapeshifterincontext** [comment]
Okay I downloaded the latest version, I'll uninstall the other one and install this one, see how it goes.
Thank you for going through it with me.

**Comment by ilya-fedin** [comment]
so waiting for answer from @feiercrack

**Comment by feiercrack** [comment]
yep, works, fine. thanks -close
