### ISSUE TITLE
problem loop never ending - v 0.9.24 stable

### ISSUE THREAD

**Issue by Saleh7** [telegramdesktop/tdesktop#1626]
The problem of never ending loop :disappointed_relieved:

gif :point_down:

![Telegram](http://i.imgur.com/yRdzQr7.gif)

**Comment by Mouamle** [comment]
that is me :3

**Comment by telegramdesktop** [comment]
@Mouamle Wow, looks really bad. I'll look that through, thanks.

**Comment by DaFri-Nochiterov** [comment]
This not works for me O.o

**Comment by telegramdesktop** [comment]
@Saleh7 Is it a group or a supergroup?

**Comment by telegramdesktop** [comment]
Does not work for me in any way.. @Saleh7 can you contact me at https://telegram.me/preston so I could ask you for debug logs and see why this is happening?

**Comment by Saleh7** [comment]
@telegramdesktop SuperGroup and Channel
yes, not everything is repeated

ok that is me https://telegram.me/rrRrr

thanks

**Comment by Saleh7** [comment]
@DaFri-Nochiterov 
not everything is repeated :exclamation:

i do not even know what the exact problem
in sometimes does not repeated :neutral_face:

:point_down:
- gif

![Imgur](http://i.imgur.com/l28KVrl.gif)

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
