### ISSUE TITLE
Linux: Blurry on fractional scaling

### ISSUE THREAD

**Issue by ai** [telegramdesktop/tdesktop#16260]
### Steps to reproduce
1. `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`
2. Open Telegram

### Expected behaviour

Should be the same as on 200% scaling

### Actual behaviour

Font is blurry

### Configuration
**Operating system:** Fedora 33

**Version of Telegram Desktop:** 2.7.4

**Installation source (Linux Only):** Flatpak

**Used theme**: Day

**Comment by ilya-fedin** [comment]
AFAIK GNOME scales up XWayland apps, so that's not a bug

**Comment by ai** [comment]
@ilya-fedin what I should do to have readable text?

Is it possible to use Wayland in Telegram client?

2K/3K screens are very popular on modern laptops. Fractal scaling is the main way to use this resolution (200% scaling will make windows bigger).

**Comment by ilya-fedin** [comment]
> what I should do to have readable text?

You should find in GNOME docs how to exclude Telegram from compositor-side scaling and set scale in Telegram settings instead

> Is it possible to use Wayland in Telegram client?

I think you can use some Qt variable to force it to run on Wayland, but AFAIK Qt on Wayland is not ready for GNOME and buggy.
