### ISSUE TITLE
Telegram keeps stealing focus even if "Draw attention to the window" is unchecked

### ISSUE THREAD

**Issue by datafl4sh** [telegramdesktop/tdesktop#16269]
OS: Debian testing
Telegram version: 2.6.1
DE: Mate 1.24.1
Used theme: default

### Steps to reproduce
1. Install telegram: `apt install telegram-desktop`
2. Uncheck Settings -> Notifications -> Draw attention to the window
3. Wait for a message

### Expected behaviour
Telegram should not steal focus.

### Actual behaviour
Telegram steals focus.

There are already so many issues on this: #7885, #7887, #7900, #7922, #7964, #8006, #8268, #8346, #8372, this "feature" is really annoying.

**Comment by ilya-fedin** [comment]
Upgrade to 2.7.4, 2.6.1 is not supported
