### ISSUE TITLE
Crash while recording voice message

### ISSUE THREAD

**Issue by Thinker2021** [telegramdesktop/tdesktop#16279]
### Steps to reproduce
1. Click on the microphone icon
2. Start talking to record message

### Expected behaviour
Record and send voice message
### Actual behaviour
Application crashes immediately every time

### Configuration
**Operating system:** Garuda Linux x86_64, Kernel: 5.11.16-zen1-1-zen

**Version of Telegram Desktop:** 2.7.4 (the latest)

**Installation source (Linux Only)** - the official repository (community)

**Used theme**: dark/night

<details><summary><b>Logs</b>:</summary>
[2021.05.04 13:41:08] Audio Error: Unable to avcodec_send_frame for capture, error -22, Недопустимый аргумент
</details>

**Comment by ilya-fedin** [comment]
Switch to official binary, your package is broken
