### ISSUE TITLE
Grouping similar groups or channels 

### ISSUE THREAD

**Issue by tavrij** [telegramdesktop/tdesktop#1627]
Hi All,

Scenario is this:
I have 21 groups and 67 channel and more then 600 chats in my telegram. This is a very busy account and I some times hang or miss a chat, group or channel!

Solution:
I can categories all of this groups and channels and chats for decrees the traffic of them.

Best regards,
Amir Taheri

**Comment by auchri** [comment]
#1107?

**Comment by aaomidi** [comment]
Unfortunately it seems the devs don't want to do it which is very annoying :(

**Comment by stuntguy3000** [comment]
This feature is definitly a must. I don't know why they are so against it.

**Comment by tavrij** [comment]
That idea is nice. but, Similar to G+ Circles users can categories any persons or  groups or channels in custom  categories for example "job friends", "Work friends", "Bourse", "news" and ... .
Mixing [#1107](https://github.com/telegramdesktop/tdesktop/issues/1107) and this is great and good job real.
