### ISSUE TITLE
File Chooser Dialog for Telegram 2.7.4 no longer opens in the last used directory 

### ISSUE THREAD

**Issue by slumbergod** [telegramdesktop/tdesktop#16272]
### Steps to reproduce
1. Click the attachment icon for the conversation thread
2. The File Chooser Dialog no longer starts in the last used directory
3. You have to navigate back to the directory you are using for each file you want to upload

### Expected behaviour
Tell us what should happen

Clicking the attachment icon should open the File Chooser Dialog in the last used location. That was normal behaviour prior to 2.7.4

### Actual behaviour
Tell us what happens instead
Since 2.7.4 it defaults to Recent Files.

**Operating system:**
Manjaro Linux
**Version of Telegram Desktop:**
2.7.4
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
> **Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

You haven't specified that, but that's required.

**Comment by slumbergod** [comment]
Official Website

**Comment by ilya-fedin** [comment]
DE?

**Comment by slumbergod** [comment]
Desktop Edition.
But the original installation was long ago. I just upgrade it when prompted. 2.74. was the first I experienced this change in behaviour

**Comment by ilya-fedin** [comment]
> Desktop Edition.

I asked you what desktop environment are you using.

**Comment by slumbergod** [comment]
let someone else report it.
