### ISSUE TITLE
Crash when maximizing a picture to full screen

### ISSUE THREAD

**Issue by steuerlexi** [telegramdesktop/tdesktop#16277]
### Steps to reproduce
1.  click on any pictures in a chat and go into fullscreen view.
2. 
3. 

### Expected behaviour
Tell us what should happen
the application should not crash

### Actual behaviour
Tell us what happens instead
the application is crashing

### Configuration
**Operating system:**
Windows 10 65bit

**Version of Telegram Desktop:**
latest version

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
official website

**Used theme**:
dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
provide crash report tag

**Comment by steuerlexi** [comment]
> provide crash report tag

How do I do this?

**Comment by ilya-fedin** [comment]
On next launch after the crash you will see crash reporter with crash report tag. Copy the crash report tag, send crash report and post that crash report tag here.

**Comment by steuerlexi** [comment]
It freezes when i open a picture for the first time after the application was started. when i click then it crashes. Now i found out when i wait for 5-10 seconds it does not crash and afterwards i can open every picture like it should without freezes. So thats why i not getting a crash report tag.

**Comment by ilya-fedin** [comment]
> So thats why i not getting a crash report tag.

You mean it freezes and not crashes?

**Comment by steuerlexi** [comment]
yes. And when you try to click on the fullscreen pictures then it crashes.

**Comment by ilya-fedin** [comment]
Find Telegram process in task manager when it freezed, open context menu and generate a dump. Then send it @john-preston (`@preston` there) at Telegram

**Comment by steuerlexi** [comment]
I just realized that i have installed the 32bit version. With the 64bit version the problem is gone. So you can close this ticket. Thank you
