### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by m4tkv** [telegramdesktop/tdesktop#16283]
v 2.7.2.

It used to be extremely convenient to send screenshots using the built-in windows scissors tool (win + shift + S). Now the image from the clipboard is sent to the chat as a file, and not as an image, which is less convenient. Will the ability to send screenshots as images return in this way?

**Comment by RememberTheAir** [comment]
Screenshots pasted from the clipboard are still sent as photos, unless you untoggle the "compress image" option, or the screenshot has a side significantly longer than the other

**Comment by m4tkv** [comment]
> Screenshots pasted from the clipboard are still sent as photos, unless you untoggle the "compress image" option, or the screenshot has a side significantly longer than the other

Оh, thanks! :)
