### ISSUE TITLE
"Can't send an empty file" via drag'n'drop on KDE Neon 5.51 

### ISSUE THREAD

**Issue by light-and-ray** [telegramdesktop/tdesktop#16287]
### Steps to reproduce
1. drag a (non empty) file from Dolphin and drop in char

### Expected behaviour
A window should appear the same as if this file was selected by clicking on the paperclip icon

### Actual behaviour
The message "unable to send empty file" appears and the correct path to the file

### Configuration
**Operating system:** KDE neon User Edition 5.21 x86_64 

**Version of Telegram Desktop:** 2.7.4 (flatpak)

**Installation source (Linux Only)** - the official website / flatpak 

**Used theme**: -

Can't find the log.txt

**Comment by ilya-fedin** [comment]
https://github.com/flathub/org.telegram.desktop/issues/23
