### ISSUE TITLE
No notifications for selected chats, when telegram is minimized

### ISSUE THREAD

**Issue by rhergenreder** [telegramdesktop/tdesktop#16285]
### Steps to reproduce
1. Open Telegram and switch to one chat
2. Minimize telegram/Focus another window
3. Receive a new message in the previously selected chat

### Expected behaviour
A notification should be shown and a sound should be played.

### Actual behaviour
No notification is sent and no sound is played. Telegram messages are marked as read.

### Configuration
**Operating system:** Arch Linux 5.11.16, KDE plasma 5.21.4

**Version of Telegram Desktop:** 2.7.3

**Installation source (Linux Only)** - distribution package: Arch Linux package: telegram-desktop 2.7.3-1

**Used theme**: Tinted

<b>Additional Info:</b>
In the view of the chat partner, I quickly come online, read the message, and go offline again, even if telegram desktop is minimized / not the focused window. This issue occurs only for the selected chat. Notifications for other chats are created correctly.

**Comment by ilya-fedin** [comment]
2.7.3 is outdated, upgrade to 2.7.4

**Comment by rhergenreder** [comment]
Seems like upgrading to the latest version fixed the issue. Thanks!
