### ISSUE TITLE
Segmentation Fault when clicking in the telegram icon on the panel - v 0.9.24 stable

### ISSUE THREAD

**Issue by chmercesmoreira** [telegramdesktop/tdesktop#1628]
I did a video showing the problem, so that I can explain the problem in a better way, because English isn't my native language.
[telegram.mkv.zip](https://github.com/telegramdesktop/tdesktop/files/133464/telegram.mkv.zip)

**Comment by chmercesmoreira** [comment]
The problem is not happening anymore, I don't know why, I'm closing this issue.

**Comment by Fenisu** [comment]
I have the same problem, using latest Telegram 0.9.24.
