### ISSUE TITLE
[Feature Request] Emoji autoupdater

### ISSUE THREAD

**Issue by zarEclEC** [telegramdesktop/tdesktop#16291]
See https://github.com/telegramdesktop/tdesktop/issues/5617 for reference to understand where this feature request come from.

I want a feature that, when an emoji pack is updated by the vendor, telegram desktop auto-updates it, without needing the whole app to be updated

**Comment by ArmeF97** [comment]
keep it open

**Comment by zarEclEC** [comment]
keep it open

**Comment by soredake** [comment]
Is this fixed or not?
