### ISSUE TITLE
[Feature Request]  Export - Import Settings Configuration

### ISSUE THREAD

**Issue by rizaumami** [telegramdesktop/tdesktop#16293]
Adjusting settings is my ritual whenever I have to login to a new Telegram Desktop session.
Everything synced, except the settings. Which is a good thing.

So, here is the feature request: add an export and import settings configuration into and from a configuration file.
Or perhaps, just create a config file and save it inside Telegram Desktop config directory (or anywhere else depend on the Operating System in use). This config file should be OS agnostic so the user can use it on Linux, Windows, etc.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8658
