### ISSUE TITLE
telegram is always crash after the last update 

### ISSUE THREAD

**Issue by itsDARKSAMA** [telegramdesktop/tdesktop#16299]
When I Open Telegram-Desktop It's ALWAYS CRASH AFTER The Last Update. Actually I Found This Problem When I was try to Record a Voice Note

> Operating System: Manjaro Linux
> KDE Plasma Version: 5.21.4
> KDE Frameworks Version: 5.81.0
> Qt Version: 5.15.2
> Kernel Version: 5.10.34-1-MANJARO
> OS Type: 64-bit
> Graphics Platform: X11
> Processors: 8 × Intel® Core™ i7-8565U CPU @ 1.80GHz
> Memory: 7.6 GiB of RAM
> Graphics Processor: Mesa Intel® UHD Graphics 620

[telegram-log.txt](https://github.com/telegramdesktop/tdesktop/files/6448530/telegram-log.txt)

**Comment by ilya-fedin** [comment]
Arch packaging bug, switch to official binary.
