### ISSUE TITLE
Question about WebRTC in telegram

### ISSUE THREAD

**Issue by itZzenXX** [telegramdesktop/tdesktop#16292]
Hello! A couple weeks ago WebRTC can be fully disabled in telegram-desktop version 2.4.11, allowing me to use telegram with a LibreSSL migrated Gentoo system. But with newer releases the patch to disable WebRTC no longer works because of changes from newer versions. Is there a newer patch available that works with newer versions of telegram-desktop? Thanks.

**Comment by ilya-fedin** [comment]
WebRTC is a required dependency for a core feature, you can't build Telegram without WebRTC.
