### ISSUE TITLE
Sent messages on left side

### ISSUE THREAD

**Issue by atis** [telegramdesktop/tdesktop#16309]
### Steps to reproduce
1. Send message in chat

### Expected behaviour
Sent messages should be aligned to right side, as on mobile client

### Actual behaviour
Sent messages are aligned on left side

### Configuration
**Operating system:** Ubuntu 16.04.7 LTS

**Version of Telegram Desktop:** 2.7.5 beta

**Installation source (Linux Only)**: the official website

**Used theme**: Classic

![Selection_875](https://user-images.githubusercontent.com/1108226/117831838-a55e2a00-b27d-11eb-8f2f-4607a8ac6326.png)

**Comment by Aokromes** [comment]
disable adaptative layout on settings.
