### ISSUE TITLE
Image is automatically downloaded?!!

### ISSUE THREAD

**Issue by crazeann** [telegramdesktop/tdesktop#16306]
### Steps to reproduce
1.  Goto Settings-Advanced-automatic Media download
2.  Set off to all slider in Private chats, Groups and Channels
3.  Scrolling / viewing messages in groups with images, the image is not downloaded ( blurred )
4.  When the message/post contains image had passed my view windows, and scrolled up, the image is not blurred ( had been downloaded ). 
It's behavior against what it means in Automatic Media Download, it's always automatically downloading images even has been set OFF

### Configuration
**Operating system:**
Windows 7 64 bit

**Version of Telegram Desktop:**
2.7.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Tinted

**Comment by H3n-beep** [comment]
i have this problem too,sometimes

**Comment by ilya-fedin** [comment]
#10371

**Comment by crazeann** [comment]
> #10371

Same issue since Feb 2021, and not yet resolved.
