### ISSUE TITLE
Can't send uncompressed image

### ISSUE THREAD

**Issue by wruggeri** [telegramdesktop/tdesktop#16304]
### Steps to reproduce
1. Drag an image to the telegram chat window (or paste it)
2. De-select the "compress image" option
3. Send the image

### Expected behaviour
The image should be sent as an uncompressed image

### Actual behaviour
The image is sent as a generic file

### Configuration
**Operating system: Windows 10

**Version of Telegram Desktop: 2.7.4

**Comment by ilya-fedin** [comment]
That's intended, uncompressed means "send as file"
