### ISSUE TITLE
Telegram crash on Audio record!

### ISSUE THREAD

**Issue by Graham1384** [telegramdesktop/tdesktop#16313]
### Steps to reproduce
1. press audio record button
2. lock audio recorder
3. wait for telegram to crash

I'm on Linux Manjaro and the last update that released two days ago can't record audio and closes itself.

### Configuration
OS: Manjaro Linux x86_64
Kernel: 5.10.34-1-MANJARO 
DE: Plasma 5.21.4 
WM: KWin 

**Version of Telegram Desktop: 2.7.4**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Manjaro official repository

**Comment by ilya-fedin** [comment]
Arch/Manjaro packaging bug, switch to official binary

**Comment by Graham1384** [comment]
please keep issue open till I re install Telegram

**Comment by ilya-fedin** [comment]
There's no need, there are a lot of closed duplciate

**Comment by Graham1384** [comment]
ok thanks
