### ISSUE TITLE
Bug: Flatpak version doesn't use proper cursor theme

### ISSUE THREAD

**Issue by SaucySauce** [telegramdesktop/tdesktop#16317]
Distro: Debian Bullseye with unstable repo, Telegram version 2.6.1.
Theming: AdwMod Gtk theme and Newaita Icon theme and Default Adwaita Cursor theme.
DE: GNOME Shell 3.38 with Wayland session

Bug: Cursor isn't following proper theme and or size.

Expected result: Cursor theme should be default Adwaita as in every other application.

Side note: Bug not affecting repo based Telegram.

**Comment by ilya-fedin** [comment]
Bug reports from old versions aren't, accepted, latest version is 2.7.4
