### ISSUE TITLE
Telegram writes some crap to ~/.config/mimeapps.list

### ISSUE THREAD

**Issue by mikhailnov** [telegramdesktop/tdesktop#16311]
I have the following in `~/.config/mimeapps.list` on Linux (ROSA 2019.1 XFCE):

`x-scheme-handler/tg=userapp-Telegram Desktop-DIKH20.desktop;`

Other users report more crap inside it (using an official blob, not a distro package):

```
$ grep tg .config/mimeapps.list 
x-scheme-handler/tg=userapp-Telegram Desktop-IYW220.desktop
x-scheme-handler/tg=userapp-Telegram Desktop-VX48Y0.desktop;userapp-Telegram Desktop-LWKNZ0.desktop;userapp-Telegram Desktop-Z0MB30.desktop;userapp-Telegram Desktop-ED1V20.desktop;userapp-Telegram Desktop-55BW20.desktop;userapp-Telegram Desktop-PPMZ20.desktop;userapp-Telegram Desktop-O2G420.desktop;userapp-Telegram Desktop-IYW220.desktop;
```

I am using a distro package of telegram-desktop, no additional desktop files must be created, `/usr/share/applications/*.desktop` should be enough:
```
$ cat /usr/share/applications/telegramdesktop.desktop | grep /tg
MimeType=x-scheme-handler/tg;
```

**Comment by Aokromes** [comment]
try official package instead distro package.

**Comment by mikhailnov** [comment]
I am not gonig to use blobs.

**Comment by mikhailnov** [comment]
The same problem is also with an official blob, I've updated the description above.

**Comment by arisudesu** [comment]
You could compile "blobs" from the sources in this repository. Distro builds are basically, repacks of software with some ill-coded patches applied, like, splitting static build to shared libraries. They only increase maintenance costs for themselves, and also complicate bug reporting for users and original devs. Of course devs won't support modified versions for you, because they don't work as they indended to be.

**Comment by mikhailnov** [comment]
I am building telegram-desktop myself (https://abf.io/import/telgram-desktop) and there are no relevant patches applied. Maybe some ifdefs in the code are missing or are incorrect. This bug is also relevant for official releases. Please do not try to get rid of bug reports just if you see that a distro package is being used. It looks strange.

**Comment by Aokromes** [comment]
> Please do not try to get rid of bug reports just if you see that a distro package is being used. It looks strange.

the problem is when bug report comes from the packager and doesn't exist on official package.

**Comment by ezdev128** [comment]
> > Please do not try to get rid of bug reports just if you see that a distro package is being used. It looks strange.
> 
> the problem is when bug comes from the packager and doesn't exist on official package.

The problem persists also in official binary.

**Comment by FabianPastor** [comment]
And what is your bug?
That your distro is trying to show you, for the "open with" menu, more options?
As you might know you can use multiple TDesktop instances at the same time and there are some links like tg://joinchat/<hash> that only will be managed by Telegram Apps. So there is a reason to create a sheme handler for tg:// links on to Telegram Desktop AND if you use more than 1 TDesktop you will be able to select one of them if you edit your .desktop files on "~/.local/share/applications/"

Not sure what the issue really is. Can you explain more? please?

**Comment by mikhailnov** [comment]
The problem is that some **not existing** desktop files are added to ~/.config/mimeapps.list

**Comment by FabianPastor** [comment]
Did you looked on "~/.local/share/applications/"?

**Comment by mikhailnov** [comment]
Hm, yes, there are files:

```
$ cat ~/.local/share/applications/userapp-Telegram Desktop-G3K9W0.desktop
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
NoDisplay=true
Exec=/usr/bin/telegram-desktop -workdir /home/user/.local/share/TelegramDesktop/ -- %u
Name=Telegram Desktop
Comment=Особое определение для Telegram Desktop
```

and the same `userapp-Telegram Desktop-DIKH20.desktop`. Both files have the same text.

So I was wrong that it is a not existing file. It does exist. Then why did it appear? I did not set custom workdirs via CLI and the workdir inside them is a standard one.

**Comment by mikhailnov** [comment]
By the way, `Comment=Особое определение для Telegram Desktop`  would better be:

```
Comment=English text
Comment[ru]=Russian text
```

**Comment by ilya-fedin** [comment]
That's intended behavior. This file is created by glib API, the same firefox uses to be default browser, with the difference tdesktop calls it for tg protocol.

**Comment by mymedia2** [comment]
The bug is in the RegisterCustomScheme() function, because it ignores passed `force` flag.

https://github.com/telegramdesktop/tdesktop/blob/680a9a7ca7d9dde6c79a6340e3ca003e6ccfd8a5/Telegram/SourceFiles/platform/linux/specific_linux.cpp#L829

**Comment by mymedia2** [comment]
@mikhailnov Look at my patch, it could fix the bug for you.

https://salsa.debian.org/debian/telegram-desktop/-/blob/0cd57ffdf6ec627842e08d51b5f80c6a1eb92d1a/debian/patches/Disable-register-custom-scheme.patch

**Comment by mikhailnov** [comment]
@mymedia2 thanks, I will apply this patch, it looks useful anyway, but I do not know how to trigger creating new desktop files and registering schemes to check how this patch works.

**Comment by mymedia2** [comment]
The patch modifies tdesktop so it creates no \*.desktop files at start, and tdesktop does not touch user's mimeapps.list file. However, you can trigger the function if you blindly type `registertg` when Settings box is open.

By the way, `tg://...` links would still work thanks to a global scheme handler set in a system \*.desktop file.

https://github.com/telegramdesktop/tdesktop/blob/a8807bc915f2439acc7c84f06d931d96d6ca602a/lib/xdg/telegramdesktop.desktop#L12

**Comment by ilya-fedin** [comment]
> The bug is in the RegisterCustomScheme() function, because it ignores passed `force` flag.

It is not a bug, it's meant to work on distro packages.

**Comment by ilya-fedin** [comment]
> By the way, `tg://...` links would still work thanks to a global scheme handler set in a system *.desktop file.

The purpose of RegisterCustomScheme is to make current running instance the default handler, not only to install it to the system. Not to say that it can work even when no .desktop file installed.

**Comment by mymedia2** [comment]
I believe Telegram should not change user preferences silently without a confirmation. Moreover in the current shape, it scattets redundant *.desktop files even if they contain default path.

No other apps do such things.

**Comment by ilya-fedin** [comment]
> I believe Telegram should not change user preferences silently without a confirmation.

Well, it's cross-platform tdesktop behavior :man_shrugging:

**Comment by mikhailnov** [comment]
14 мая 2021 г. 8:49:19 GMT+03:00, Nicholas Guriev ***@***.***> пишет:
>I believe Telegram should not change user preferences silently without
>a confirmation. Moreover in the current shape, it scattets redundant
>*.desktop files even if they contain default path.
>
>No other apps do such things.

+1

**Comment by ezdev128** [comment]
> I believe Telegram should not change user preferences silently without a confirmation. Moreover in the current shape, it scattets redundant *.desktop files even if they contain default path. No other apps do such things.

+1

**Comment by mikhailnov** [comment]
Here it is not clear to me which problem is being solved by creating custom desktop files and registering schemes for them.

If add another account to the same profile of tdesktop, will it be useful? Probably no.

If a user wants to have another instance of tdesktop with another working directory, he manually copies /usr/share/applications/*.desktop to ~/.local/share/applications (or $XDG_DATA_HOME/applications) and modifies cli args in ExecStart. Do you try to automate registering tg:// in this case? I think the user, who did this, would better register them himself.

The described trick had sense when  tdesktop did not support multiple accounts, nowadays it does support multiple accounts, there should be no need in multiple instances of tdrsktop on most syatems.

**Comment by ilya-fedin** [comment]
> No other apps do such things.

I copied the algorithm from firefox, so at least firefox does that (as soon as you answer "Yes" in the dialog to make firefox the default handler)

**Comment by ilya-fedin** [comment]
> Here it is not clear to me which problem is being solved by creating custom desktop files and registering schemes for them.

It ensures that current tg:// handler is the current instance of tdesktop.

**Comment by mikhailnov** [comment]
14 мая 2021 г. 15:55:08 GMT+03:00, ilya-fedin ***@***.***> пишет:
>> Here it is not clear to me which problem is being solved by creating
>custom desktop files and registering schemes for them.
>
>It ensures that current tg:// handler is the current instance of
>tdesktop.

How can another instance with a different desktop file appear?

**Comment by ilya-fedin** [comment]
When you have relocatable binary as well or when you have other telegram clients
