### ISSUE TITLE
Badge counter looking wrong on Linux Zorin OS Core Beta 16

### ISSUE THREAD

**Issue by DanyGee** [telegramdesktop/tdesktop#16319]
### Steps to reproduce
1. Open TG
2. Wait for new message
3. Observe counter badge

### Expected behaviour
Counter badge should look like red circle with number corresponding to new messages.

### Actual behaviour
Counter badge looks like a pill with 3 dots in it.
![Screenshot from 2021-05-10 12-29-18](https://user-images.githubusercontent.com/26818551/118267993-18a1af00-b4bd-11eb-9eff-ca12174c0358.png)

### Configuration
**Operating system:**
OS: Zorin OS 16 x86_64 
Kernel: 5.8.0-53-generic 
Shell: bash 5.0.17 
Resolution: 3840x2160 
DE: GNOME 
WM: Mutter 
WM Theme: ZorinBlue-Light 
Theme: ZorinBlue-Light [GTK2/3] 
Icons: Papirus-Light [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-6700K (8) @ 4.300GHz 
GPU: NVIDIA GeForce GTX 1080 
Memory: 1700MiB / 64257MiB 

**Version of Telegram Desktop:**
2.7.5 Beta

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
The official website.

**Used theme**:
OS:
WM Theme: ZorinBlue-Light 
Theme: ZorinBlue-Light [GTK2/3] 
Icons: Papirus-Light [GTK2/3] 

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Looks like a bug in your system theme

**Comment by DanyGee** [comment]
Yeah, for me too, but wanted to report it to TG devs just in case they had a similar issue in the past.
Of course I reported this to Zorin devs as well.
