### ISSUE TITLE
[Notebook Xiaomi Mi Notebook Air 13.3] Microphone does not work 

### ISSUE THREAD

**Issue by kasru** [telegramdesktop/tdesktop#16310]
Steps to reproduce
1. Make video call to/from notebook Xiaomi Mi Notebook Air 13.3 

Micriphone does not work

Operating system: Windows 10
Microsoft Windows [Version 10.0.18363.1500 

Version of Telegram Desktop:
2.7.5 beta

**Comment by Aokromes** [comment]
> Steps to reproduce
> 
> 1. Make video call to/from notebook Xiaomi Mi Notebook Air 13.3
> 
> Micriphone does not work
> 
> Operating system: Windows 10
> Microsoft Windows [Version 10.0.18363.1500
> 
> Version of Telegram Desktop:
> 2.7.5 beta

check you have the mic selected as default communication device.
