### ISSUE TITLE
Webp image format not recognized in link previews (og:image)

### ISSUE THREAD

**Issue by jonata** [telegramdesktop/tdesktop#16312]
### Steps to reproduce
1. Share a link with a webp image as og:image meta (like this: https://livreeaberto.com/eol-sabores-ubuntu) or use Webpage Bot
2. You can check that there is no image preview
3. To make sure the meta info is correct, you can check some opengraph checker like this: https://www.opengraph.xyz/url/https:%2F%2Flivreeaberto.com%2Feol-sabores-ubuntu/

### Expected behaviour
The image preview (the image from og:image) sould be shown.

### Actual behaviour
The image preview (the image from og:image) does not appear.

### Configuration
**Operating system:** Ubuntu 20.04

**Version of Telegram Desktop:** 2.7.4

**Installation source (Linux Only)** - distribution package

**Used theme**: Tinted

**Comment by homeworkprod** [comment]
I can confirm this behavior. According to my direct sources, this (WebP preview image not shown) happens both in the Telegram Desktop client on macOS as well as in the iOS client.

**Comment by rubenalonsoes** [comment]
It's happening to me too. If the image is webp, it doesn't show up in the preview.

**Comment by yvoictra** [comment]
Same issue here.

**Comment by wiperawa** [comment]
Same issue. we have all images converted to webp on our site, and images from og:image meta tag doesn't show up in telegram previews

**Comment by simongomes** [comment]
This is happening for us too.

**Comment by alvdev** [comment]
Same here. No fixes yet?

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
