### ISSUE TITLE
Bug: Telegram-desktop CSD mode not casting shadows

### ISSUE THREAD

**Issue by SaucySauce** [telegramdesktop/tdesktop#16316]
Distro: Debian Bullseye with unstable repo, Telegram version 2.6.1.
Theming: AdwMod Gtk theme and Newaita Icon theme.
DE: GNOME Shell 3.38 with Wayland session

Bug: Telegram window doesn't cast shadows on the background when CSD is enabled. QtWayland package is installed and working fine/enabling Wayland compatibility just fine.

Expected result: shadows are cast as every other application window.

Side note: Bug not affecting Flatpak based Telegram (on the right).

![Screenshot from 2021-05-13 22-00-07](https://user-images.githubusercontent.com/38703177/118193883-f87bdc80-b437-11eb-8ca4-bdbbd03dcba6.png)

**Comment by ilya-fedin** [comment]
Shadows require custom Qt patches. If you want to have shadows, ask your distributor to patch Qt with our patches.
