### ISSUE TITLE
Bug in date picker

### ISSUE THREAD

**Issue by mnameghi** [telegramdesktop/tdesktop#16318]
Hi. In search, I tried selecting the previous year. As you can see, the year is incorrect and when I selected it, Telegram crashed.
I use the latest version on my Mac.
This might be because I used Persian calendar. If I use the Gregorian calendar, it works.

![image](https://user-images.githubusercontent.com/6780440/118232486-e173d380-b4a5-11eb-8bc3-b980d0a1c681.png)

**Comment by 23rd** [comment]
Sorry, you are using the [Telegram for macOS](https://macos.telegram.org), not the [Telegram Desktop](https://desktop.telegram.org).
You can report your issue to [the group](https://t.me/macswift) or to [the repository of Telegram for macOS](https://github.com/overtake/TelegramSwift).
