### ISSUE TITLE
[Question] about buld system and release page.

### ISSUE THREAD

**Issue by angelskieglazki** [telegramdesktop/tdesktop#16326]
@john-preston hello.

Are you create release on release page by hand?  And  "DesktopPrivate" folder with some secret exists only on your pc?  Did I get it right?
I found github action "https://github.com/softprops/action-gh-release" maybe it would be usefull for tdestop

regards, max

**Comment by john-preston** [comment]
Hi. Yes, DesktopPrivate exists only on PCs that I use to build the release versions of tdesktop.

I use custom-written shell/python scripts to deploy the built versions, including uploading releases to github. This one uploads the releases:

https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/build/release.py
