### ISSUE TITLE
Message balloons layout broken when increasing window's width

### ISSUE THREAD

**Issue by espositofulvio** [telegramdesktop/tdesktop#1632]
The following happens in windows 10 after I updated Telegram Desktop to 0.9.24. I tested it on my personal laptop (ASUS with an Intel i5 and 8Gb of Ram) and my work laptop (Lenovo T400) with identical result. I'm sure previous version was fine.
When main window's width goes over 1100 or thereabout the layout in the chat panel breaks, see images below where in the first image width is slightly less than 1100 while in the second the windows has been resize to be just slightly over 1100 px:

![telegram narrower 1100](https://cloud.githubusercontent.com/assets/11587761/13107449/b8ca2eb8-d565-11e5-9856-61f7c116350e.PNG)

![telegram wider 1100](https://cloud.githubusercontent.com/assets/11587761/13107477/cd21c0b0-d565-11e5-9269-85ac51f26d69.PNG)

**Comment by telegramdesktop** [comment]
@espositofulvio This is a feature, starting from version 0.9.24 in the wide window sizes (like most fullscreen sizes) the messages have one side layout.

We thought through and tested that change and we are sure that this way is better than it was before, although everyone is used to the old way and the new layout seems strange and unfamiliar at first. It is easier to read the conversation when the messages go one after another and not at the different sides of a large window (which is twice as wide as the widest message), the incoming and outgoing can be easily differentiated by user photo and by bubble background color (white vs green). In the wide windows the conversation area always looked ridiculous and there is no way to fill it with content in a reasonable and usable way, but at least now messages are not thrown to the different parts of the screen at random.

So it will be left that way at least for now, with no additional settings for returning to the old layout or smth like that. Sorry if someone strongly dislikes it :(

**Comment by auchri** [comment]
Please search for existing issues before creating new ones.
#1620

**Comment by espositofulvio** [comment]
@telegramdesktop Well, I thought it wasn't intended, sorry. Now I can see that you're probably right when the panel becomes too wide, it seemed just odd at first, even because at 1300 px wide it didn't look very hard to read since part of the screen estate is taken by the contact list. Anyway, thanks for the clarification.

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.
