### ISSUE TITLE
Chat messages do not align on left and right side of the screen on bigger screen

### ISSUE THREAD

**Issue by deepakdaneva** [telegramdesktop/tdesktop#16327]
### Steps to reproduce
1. Open Telegram app on Windows 10 OS with monitor resolution 1920 x 1080 or more
2. Open any chat

### Expected behavior
Chat messages from another person should align to the left and messages from the current user should align on the right side of the screen

### Actual behavior
All messages in the chat screen are aligned on the left side of the screen, which confuses the user to find its own messages.

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 2.7.2 x64
**Used theme:** Dark
**Screen Resolution:** 1920 x 1080

**Comment by Aokromes** [comment]
disable adaptative layout

**Comment by teohhanhui** [comment]
I think what we're trying to say is, the responsive layout is broken. Chat messages should still be aligned left / right even on larger screens. Disabling responsiveness is only a workaround to avoid hitting the problem.

**Comment by Aokromes** [comment]
> I think what we're trying to say is, the responsive layout is broken. Chat messages should still be aligned left / right even on larger screens. Disabling responsiveness is only a workaround to avoid hitting the problem.

no, adaptative layout is a setting what enabling it, makes text to be show on that way, it's not a bug, not a workaround to disable it, it's how it's intended to work.

**Comment by teohhanhui** [comment]
Perhaps that should be disabled by default then... Can't find it anywhere in the Settings.
