### ISSUE TITLE
TDesktop deletes leading and trailing space characters even if they are links

### ISSUE THREAD

**Issue by liferooter** [telegramdesktop/tdesktop#16328]
### Steps to reproduce
1. Open TDesktop
2. Type a message starting with whitespace
3. Make this whitespace a link
4. Send message

### Expected behaviour
TDesktop won't delete this whitespace because it's a link and links is informative and shouldn't be trimmed.

### Actual behaviour
TDesktop deletes this whitespace.

### Configuration
**Operating system:** Fedora Linux 34

**Version of Telegram Desktop:** 2.7.5 beta

**Installation source (Linux Only)**: Flathub

**Used theme**: Night

**Comment by ilya-fedin** [comment]
I believe it is intended, to avoid scam

**Comment by liferooter** [comment]
> I believe it is intended, to avoid scam

Anyone can do it using API. Some peoples do it this way (e.g. some channels insert zero-length whitespace with link to get preview without link). This anti-feature doesn't protect users because if somebody really need it, he can do it, but less conveniently. Moreover, I can't imagine how scams can use whitespace link.
