### ISSUE TITLE
Telegram desktop client does not respect the windows text scaling settings

### ISSUE THREAD

**Issue by FlorianJa** [telegramdesktop/tdesktop#16322]
Telegram desktop client does not respect the windows text scaling settings. This important when having multiple Monitors with different DPI values and windows scaling options.

For example: I have one 24" 2k monitor (1) with 100% scaling and one 27" 4k monitor (2) with 150% scaling. when moving telegram from the first  to the second monitor I expect that the text will adjust accordingly 

to the monitors' DPI/scaling settings. 

### Steps to reproduce
Having multi monitor setup with different DPI settings:
1.  Move telegram from one to anothe monitor
2. measure text/font size in pixel. -> same for both settings

without multi monitor setup:
1. change text scaling setting in windows
2. measure text/font size in pixel. -> same for both settings

see here: https://drive.google.com/file/d/1Nb37H91N1dACmc0WfM5OpofPNbow6hw7/view?usp=sharing

### Expected behaviour
The text/font size should be scaled accordingly to the windows DPI/text scaling option PER monitor. 
100% scaling = 9 pixel
200% scaling = 18 pixel

### Actual behaviour
Text/Font size stays the same pixel size

### Configuration
Windows 10 - Version 20H2 (Build 19042.985)

Telegram Version: 2.7.4 x64 from offical website

classic theme

This is probably related to #6804 and #16209

**Comment by ilya-fedin** [comment]
#1121
