### ISSUE TITLE
Telegram Desktop (Beta) keeps crashing

### ISSUE THREAD

**Issue by MatthiasSchm** [telegramdesktop/tdesktop#16325]
Hey, maybe someone in here may help me. I already reinstalled everything, but it keeps crashing. See log below: 
<img width="491" alt="ScreenShot_20210515202942" src="https://user-images.githubusercontent.com/84246280/118374526-e2e3ef80-b5bc-11eb-84ff-8525c544da62.png">

**Comment by ilya-fedin** [comment]
#10353

**Comment by MatthiasSchm** [comment]
Sorry, I am new to this community. Why did my request got closed? I couldn't find any solution in the thread ilya-fedin linked to. Did I miss something?

**Comment by ilya-fedin** [comment]
> Why did my request got closed?

It's a duplicate.

**Comment by MatthiasSchm** [comment]
Duplicate of what?

**Comment by MatthiasSchm** [comment]
Ah, I just saw the log. Thank you.
