### ISSUE TITLE
Desktop App Secret Chat Allows Screenshots

### ISSUE THREAD

**Issue by davidclarke-au** [telegramdesktop/tdesktop#16334]
### Steps to reproduce
1. Setup a new secret chat on Telegram Desktop 
2. Take screenshot of secret chat
3. Paste to other app

### Expected behaviour
Screenshots should be prohibited if possible, otherwise the other party should receive a notification a screenshot has been taken etc...

### Actual behaviour
A screenshot is allowed

### Configuration
**Operating system:** Mac OS Big Sur 11.3.1

**Version of Telegram Desktop:** - 7.7 (215786) Stable

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: - offical website

**Comment by ilya-fedin** [comment]
tdesktop doesn't support secret chats, you're using other app...

**Comment by davidclarke-au** [comment]
> tdesktop doesn't support secret chats, you're using other app...

7.7 (215786) Stable does, it must be a new feature?

**Comment by davidclarke-au** [comment]
Ah @ilya-fedin I think I need to log this under https://github.com/overtake/TelegramSwift/issues instead...

**Comment by ilya-fedin** [comment]
exactly
