### ISSUE TITLE
[Feature Request] automatically lock telegram when the computer is locked

### ISSUE THREAD

**Issue by notes365** [telegramdesktop/tdesktop#16332]
### Is your feature request related to a problem?
n/a

### Describe the solution you'd like
 automatically lock telegram

### Describe alternatives you've considered
n/a

### Additional context
telegram will not be locked when I use` win+L`to lock the computer

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5884
