### ISSUE TITLE
Telegram hangs with emply window.

### ISSUE THREAD

**Issue by gregheade** [telegramdesktop/tdesktop#16337]
Ive installed the latest version of telegram desktop (7.7 (215786) Stable) on MacOS Mojave 10.14.5. I cannot get it to work correctly as the application hangs as per the image attached.

![Screenshot 2021-05-17 at 20 14 16](https://user-images.githubusercontent.com/76463055/118543778-a1824a00-b74c-11eb-958c-3da5abe39689.png)

**Comment by ilya-fedin** [comment]
You installed some other app, latest version of tdesktop is 2.7.4...

**Comment by Aokromes** [comment]
you have instaled swift telegram, not telegram desktop.

**Comment by gregheade** [comment]
I installed this version https://macos.telegram.org/

**Comment by ilya-fedin** [comment]
> I installed this version https://macos.telegram.org/

it's not tdesktop, tdesktop is https://desktop.telegram.org
