### ISSUE TITLE
Message position

### ISSUE THREAD

**Issue by badoualy** [telegramdesktop/tdesktop#1633]
In conversation, all the messages are now stacked on left side of the window,

please, can we have an option to set it as before (outgoing/ingoing messages separated in different sides) as it has become really hard to read.

Thanks

**Comment by telegramdesktop** [comment]
@badoualy This is a feature, starting from version 0.9.24 in the wide window sizes (like most fullscreen sizes) the messages have one side layout.

We thought through and tested that change and we are sure that this way is better than it was before, although everyone is used to the old way and the new layout seems strange and unfamiliar at first. It is easier to read the conversation when the messages go one after another and not at the different sides of a large window (which is twice as wide as the widest message), the incoming and outgoing can be easily differentiated by user photo and by bubble background color (white vs green). In the wide windows the conversation area always looked ridiculous and there is no way to fill it with content in a reasonable and usable way, but at least now messages are not thrown to the different parts of the screen at random.

So it will be left that way at least for now, with no additional settings for returning to the old layout or smth like that. Sorry if someone strongly dislikes it :(

**Comment by DaFri-Nochiterov** [comment]
telegramdesktop, 7 issues about that >_<
How many still it will proceed?

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov ¯\\_(ツ)_/¯

**Comment by ivanOne** [comment]
please make options for displaying messages in the settings

**Comment by Hertie22** [comment]
@telegramdesktop I too notices this change and I strongly dislike it.
What is wrong with a small checkbox whether I'd like to use the old layout?

Please bring back the old design, even as an option. You think it's "easier to read", I find it more difficult to read, as MY messages are now in one line with the others, especially in group chats it's difficult to differentiate and have a quick overlook.

PLEASE bring it back...

**Comment by marcovr** [comment]
Just make it optional and everyone is happy!

**Comment by Valansch** [comment]
> Just make it optional and everyone is happy!
Yes please.

**Comment by DaFri-Nochiterov** [comment]
Discussion about this: #1587 

> Please search for existing issues before creating new ones.

**Comment by yuredd** [comment]
@DaFri-Nochiterov From what I can see I think the issue you are referencing to was for centering the chat history in the window, instead this issue is for your sent chat being aligned and visualized with the icon as if it was another person chat. For me this is a problem because it isn't easy to distinguish between sent and received messages.

**Comment by jhalt** [comment]
It should either be optional, reverted, or display your own messages with a different background color bubble..

**Comment by GriffinPvP** [comment]
Make it optional guys, we were all used to the old positions.

**Comment by St3eT** [comment]
Optional or revert please ;(

**Comment by UnAfraid** [comment]
> Just make it optional and everyone is happy!
Exactly!

**Comment by Mrwebente** [comment]
Please as everyone else said, make this an option. because i'm more irritated by that than by how it was before. And DON'T port it to android without the option addet. because people will loose their *** about it. My brother for instance refuses to update now.

**Comment by auchri** [comment]
Please search for existing issues before creating new ones.
#1587

**Comment by yuredd** [comment]
@auchri I may be wrong but it's not about the new layout. It's about the visualization of the sent messages. This is the proble I (and the issue opener IMHO) am talking about this:
![error align](https://cloud.githubusercontent.com/assets/657980/13112747/79cf6ef4-d58c-11e5-8db4-8e169f8430e3.png)
My user icon never showed up in my sent messages (making sent messages identical to received messages; I think it is a real bug. The issue you referenced talks about the general layout of the application that isn't the problem discussed here IMHO. The issue reads "all the messages are now stacked on the left" and not "all the messages are now centered".

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.

**Comment by UnAfraid** [comment]
Awesome!

**Comment by St3eT** [comment]
<3

**Comment by ivanOne** [comment]
coooooooooooooool

**Comment by DaFri-Nochiterov** [comment]
Thanks ☺
