### ISSUE TITLE
There is no "show NSFW content" switch in the settings on masOS Telegram Desktop

### ISSUE THREAD

**Issue by xm4dn355x** [telegramdesktop/tdesktop#16346]
### Steps to reproduce
1. Go to macOS settings
2. Disable all system NSFW content filters
3. Go to Telegram Desktop for macOS
4. Go to Telegram Desktop settings
4. Where is sensitive content switch?

### Expected behaviour
User need to disable NSFW content filters.

### Actual behaviour
User can't disable sensitive content filters. Apple technical support says that is only telegram problem.

### Configuration
**Operating system:**
macOS BigSur

**Version of Telegram Desktop:**
latest

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Apple macOS App Store

**Used theme**:
Any

**Comment by Aokromes** [comment]
for sure you are using native macos application and not telegram desktop (telegram lite for macos).

**Comment by xm4dn355x** [comment]
> for sure you are using native macos application and not telegram desktop (telegram lite for macos).

Yes, official telegram application from macos appstore with "Telegram Messenger LLP" as author. Not a "telegram lite" or etc.

**Comment by Aokromes** [comment]
that's telegram swift, not telegram desktop.
