### ISSUE TITLE
Can't open quizzes.

### ISSUE THREAD

**Issue by harshverma27** [telegramdesktop/tdesktop#16348]
### Steps to reproduce
1. 
2. 
3. 

### Expected behavior
Whenever I try to open run a quiz or vote on the application,  it says "This message is not supported by your version of Telegram. Please update to the latest version in Settings > Advanced, or install it from https://desktop.telegram.org".

### Actual behavior
The quiz or vote should have shown as in my mobile app.

### Configuration
Ubuntu

**Version of Telegram Desktop:**
1.8.9

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
I used Flatpak.

**Used theme**:
Tinted.
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
update your version you are running extreme ancient version.
