### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by pH142857** [telegramdesktop/tdesktop#16344]
### Is your feature request related to a problem?
Some time ago it was possible to register to Telegram without a smartphone, by receiving an SMS. Now the option disappeared from Telegram Desktop, thus making it impossible for people without a smartphone to use Telegram. It was, imho, one of the main advantages of Telegram over other messaging apps.

### Describe the solution you'd like
Please revert this design regression and make it possible again to register without a smartphone by receiving an SMS.

### Additional context
People that don't have a smartphone [do exist](https://www.statista.com/statistics/219865/percentage-of-us-adults-who-own-a-smartphone/) and are as legitimate as anyone to use Telegram.
(Also I might be missing something because I didn't find any information on this feature - or disappearance thereof - anywhere.)

**Comment by Aokromes** [comment]
server change, nothing telegram desktop can do.

**Comment by pH142857** [comment]
> server change, nothing telegram desktop can do.

Can you provide me with an official source for such change please?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16153#issuecomment-822042148
