### ISSUE TITLE
HTML Export Creates Thumbnails for Animated Stickers (.tgs) But doesn't create <img tags in HTML file for Animated Sticker Thumbnails

### ISSUE THREAD

**Issue by psychosys** [telegramdesktop/tdesktop#16340]
### Steps to reproduce
1. Export a Chat with Animated Sticker (.tgs)

### Expected behaviour
HTML Export should push **img** tags for Animated Stickers (.tgs) Thumbnails

### Actual behaviour
HTML Export Code generates Thumbnails for Animated stickers in **JPG**  format ( Writes both Sticker file .tgs and Thumbnail .JPG inside the **stickers** folder ) but doesn't include them in HTML file ( it doesn't create <IMG tag for Animated Stickers (.tgs) Thumbnails, instead it writes static **Sticker** text 

### Configuration
Telegram Latest Version
Linux / Centos or Windows

### Suggestion
I see that you are converting even .GIFs to .MP4 during the export, that would be FANTASTIC if you convert .tgs to either **.WEBP** or **.MP4** , currently export code create <a href for STICKER file directly

**Comment by john-preston** [comment]
@psychosys Nothing is converted during the export, the files are written to disk as they are provided by the API.

**Comment by psychosys** [comment]
> 
> 
> @psychosys Nothing is converted during the export, the files are written to disk as they are provided by the API.

![image](https://user-images.githubusercontent.com/58204209/118910695-eea02080-b8f2-11eb-9478-65bdf5cd7b76.png)

Thank you,
So in this case API provides Thumbnails for Animated Stickers ( .TGS ) files as you can find them inside stickers folder with **.JPG** extension BUT the HTML Generator doesn't utilize these Thumbnails, it uses the generic placeholder **Stickers** for them.

![image](https://user-images.githubusercontent.com/58204209/118910831-2909bd80-b8f3-11eb-844f-4398daa16b0b.png)
