### ISSUE TITLE
Clipboard problems

### ISSUE THREAD

**Issue by DaniilHouser** [telegramdesktop/tdesktop#16345]
Telegram Desktop 2.7.4
Windows 10 19042.985

Problems with the clipboard, when navigating in folders with chats in the telegram client. 
Telegram does not see the current state of the clipboard

**Comment by iqfareez** [comment]
May I ask, why does Telegram need to see the current state of the clipboard?

**Comment by ilya-fedin** [comment]
The problem seem to be really poorly described...
