### ISSUE TITLE
Telegram hovers over other windows even when focus is lost

### ISSUE THREAD

**Issue by nickolay-yakovliev** [telegramdesktop/tdesktop#16341]
### Steps to reproduce
1. Open the application
2. Press Alt+Tab to switch to the next available window

### Expected behaviour
The next available window should be focused and displayed over Telegram.

### Actual behaviour
The next available window is focused, but Telegram is displayed over it.

### Configuration
**Operating system:**
Windows 10 Pro

**Version of Telegram Desktop:**
2.7.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Night

**Comment by ilya-fedin** [comment]
#3253?

**Comment by nickolay-yakovliev** [comment]
Seems relevant. However, I'm not sure if it is the same case, because I'm talking about Telegram "Home" window (see "Steps to reproduce" section), I don't mean to open some picture.

**Comment by ilya-fedin** [comment]
> I'm talking about Telegram "Home" window (see "Steps to reproduce" section), I don't mean to open some picture.

That issue actually combined. That bug with viewer fixed a long time ago and people (because blind?) use that issue for this bug as well.

**Comment by nickolay-yakovliev** [comment]
Well, I couldn't reproduce that old issue (with the picture viewer) on my PC with the configuration mentioned in the description. So I would keep current ticket separate from it. Are you ok with that?

**Comment by ilya-fedin** [comment]
I'll repeat myself, but that issue is not about media viewer actually, it also covers main window due to the people who reused that issue (look at last message). There's no reason in a duplicate.
