### ISSUE TITLE
Открытие URL в разных браузерах из разных чатов

### ISSUE THREAD

**Issue by timda** [telegramdesktop/tdesktop#16347]
По умолчанию работать с системным браузером по умолчанию.
В настройках пользователя сделать возможность на каждую группу назначить свой браузер для открытия ссылок. 

Юзер-стори заключается в том, что для разных "проектов" использую разные браузеры, в основном для разных типов аутентификации + демо экрана. На работе хочу использовать Opera - ссылки из определенных чатов или от группы людей, а для домашней навигации Вивальди, а в системе Chrome по умолчанию.

**Comment by Aokromes** [comment]
english only plz.

**Comment by timda** [comment]
> english only plz.

Why only? 
Я бы понял, если это был твитер. 
Но с чего великий свободный русский ТЕЛЕГРАМ ограничивает меня? 

Не буду писать, что про это думаю, и то какие есть варианты для англоязычной аудитории.

**Comment by Aokromes** [comment]
> > english only plz.
> 
> Why only?
> Я бы понял, если это был твитер.
> Но с чего великий свободный русский ТЕЛЕГРАМ ограничивает меня?
> 
> Не буду писать, что про это думаю, и то какие есть варианты для англоязычной аудитории.

because not everyone can read russian.

**Comment by aleksusklim** [comment]
> По умолчанию работать с системным браузером по умолчанию.
> В настройках пользователя сделать возможность на каждую группу назначить свой браузер для открытия ссылок.

Just always use your right mouse button to copy the link URL to paste it in any browser you want.
