### ISSUE TITLE
Messages are too narrow on wide screens

### ISSUE THREAD

**Issue by makkarpov** [telegramdesktop/tdesktop#1634]
A recent update that removed two-side layout on wide screens is really nice, but there should be another one that will expand messages to full width, instead of leaving them in a narrow column.

![image](https://cloud.githubusercontent.com/assets/1329592/13112242/043cbbf6-d59b-11e5-83b5-fb7f8361e5d9.png)

**Comment by auchri** [comment]
Please search for existing issues before creating new ones.
#1587

**Comment by telegramdesktop** [comment]
This won't be good :( If you make text really wide (for example text will use full screen width on your screenshot) it will be almost impossible to read any multi-line text (when you finish the line, you can't find the beginning of the next line).

**Comment by makkarpov** [comment]
I haven't any problems on such layouts with, for example, Skype. And anyway, it can be added via a setting, so those who feel uncomfortable with wide messages can turn them off.

**Comment by kirsan31** [comment]
@telegramdesktop When you post formatted text with ``` it's nearly useless because of very thin message width. All code will mess up with word wrap? For example, I copy text from your source and past it with formatting: 
![tc](https://cloud.githubusercontent.com/assets/17767561/13675561/3b902228-e6f3-11e5-966f-d1496478fb58.jpg)

**Comment by takahser** [comment]
@kirsan31 maybe you should stop producing such long one-liners, it's not really clear readable anyway :)
however, you're not totally wrong, imho it should support at least 80 chars though

**Comment by kirsan31** [comment]
@takahser Ahhha, this code from telegram's source ;) see url at the screenshot ;)

**Comment by makkarpov** [comment]
@takahser Maybe I should also stop buying wide screens? Why do I need wide screen if Telegram does not use it? It's not one-liners issue, it's Telegram issue.

**Comment by nocturnal3d** [comment]
I totally agree with @makkarpov and @kirsan31. This would be a great feature for those users used to chat apps like Slack or Hipchat - make text full width.

At our company some of the developers refuse to use Telegram because of exactly this.....too Whatsappy :) and it's a shame since Telegram rocks! and in my opinion is way better than Slack/Hipchat.

**Comment by matteomartelli** [comment]
I totally agree with @makkarpov. I am constantly using telegram desktop on a wide screen and frequently sending code messages. @telegramdesktop if you are worried about readability I think it might be nice to let the users decide. For example an option that allows users to set the number of linewrap characters and toggle full-width messages would be very useful in my opinion.

Anyway since I can understand this is considered a low priority feature, please consider to change the default number of linewrap characters to 80 or 100, instead of 60 which it seems to be the current default value. 

https://en.wikipedia.org/wiki/Characters_per_line#In_programming

**Comment by ppparadox** [comment]
+1

**Comment by F43nd1r** [comment]
Could somebody point me to the sourcefile defining that maximum width? I planned to experiment with different widths, but was unable to find the relevant code.

**Comment by matteomartelli** [comment]
@F43nd1r this might be the file you are looking for: https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/boxes/boxes.style

**Comment by F43nd1r** [comment]
@matteomartelli I Don't think so, I've already checked that file, and none of the widths I think could be relevant have any effect if I change them.

**Comment by kirsan31** [comment]
@F43nd1r there was a [PR](https://github.com/telegramdesktop/tdesktop/pull/2339) (rejected :( ) about this. You can check modified files there.

**Comment by F43nd1r** [comment]
@kirsan31 thanks. Sadly, the code has changed too much, I wasn't able to locate the relevant lines. 
As I'm not really a c++ developer, I'll have to hope that the developers will change their mind about this.

Frankly I don't understand why there is no option for this, as there are clearly a lot of users unsatisfied with the current state. The only counterargument I've seen is that it would clutter the options. If that is a problem, hide it in a configuration file.

**Comment by tau0** [comment]
Maybe It's better idea to add this setting to the theme configuration file.

**Comment by afabri** [comment]
I would also be glad to see wider messages. After all it is something that the user should be able to configure in a menu, and not something I would have to compile from source. 
And THANK YOU, dear telegram developers, for making telegram!!!

**Comment by kirsan31** [comment]
@F43nd1r if you still interested, you can check my repo, I tried to address this issue (and one more) there...

**Comment by F43nd1r** [comment]
Sure, I'm still interested. Do you plan to pull these changes into the official version? If not, could you upload binaries somewhere?

**Comment by kirsan31** [comment]
@F43nd1r 

> Do you plan to pull these changes into the official version?

No reason to make a PR because:

- The main reason - It will be rejected any way :(
- My fixes are fast and aimed to windows, so not tested on other platforms.

> If not, could you upload binaries somewhere?

I have made a release with binary.

**Comment by F43nd1r** [comment]
Alright, I just tried that release, and does not achieve what I wanted. It doesn't work if adaptive layout is disabled, but I like to have my messages on the other side.

**Comment by kirsan31** [comment]
Yea, it all depends on adaptive layout. IMHO, on wide screen, messages on 2 sides look very ugly. You can check my changes and try to do as you wish. But with standard layout, it will be _a bit_ harder to achieve...
