### ISSUE TITLE
Freezing when "Remote NDIS based Internet Sharing device" is connected

### ISSUE THREAD

**Issue by Muhammadyusuf96** [telegramdesktop/tdesktop#16352]
### Steps to reproduce
1. Connect any/some Remote NDIS based Internet Sharing device via USB. In my case TPLINK M7200. I plug it in when there is no charger.
2. Telegram gets freezes

### Expected behaviour
Normal working state

### Actual behaviour
Freezing and unfreezing after disconnect

### Configuration
**Operating system:**
Windows 8.1

**Version of Telegram Desktop:**
2.7.4 and earlier versions

**Comment by ilya-fedin** [comment]
Get a dump from task manager when the process is freezed and send it to @john-preston via Telegram (`@preston` there)

**Comment by Muhammadyusuf96** [comment]
@ilya-fedin I tried send dumps created with Task Manager but failed. Looks like dumps corrupted so i dumped with Scylla

**Comment by ilya-fedin** [comment]
What's Scylla?

**Comment by Muhammadyusuf96** [comment]
[Scylla](https://github.com/NtQuery/Scylla) is a [plugin](https://github.com/x64dbg/x64dbg/wiki/Plugins) for debugger [x64dbg](https://x64dbg.com/#start)

**Comment by ilya-fedin** [comment]
> [Scylla](https://github.com/NtQuery/Scylla) is a [plugin](https://github.com/x64dbg/x64dbg/wiki/Plugins) for debugger [x64dbg](https://x64dbg.com/#start)

Are you sure these dumps have the same format as task manager? @john-preston won't be able to use the dump if it has a custom format. Have you already sent it?

**Comment by Muhammadyusuf96** [comment]
Yes, I forgot to say that I then sent the dumps from the task manager. I somehow hastily decided that the dumps were damaged. In fact, Telegram was unable to read these files due to the lack of access rights.

**Comment by john-preston** [comment]
@Muhammadyusuf96 

Looks like this device interferes with network availability from Windows-s point of view (somehow). One dump sits on this method call:

https://docs.microsoft.com/en-us/windows/win32/api/netlistmgr/nf-netlistmgr-inetworklistmanager-getconnectivity

![image](https://user-images.githubusercontent.com/17900494/119398209-4f12d180-bce8-11eb-962c-ba218b3e9055.png)

The other waits for a background thread, and a bunch of background threads are sitting in QNetworkAccessManager->system calls as well:

![image](https://user-images.githubusercontent.com/17900494/119399175-a1082700-bce9-11eb-997d-9c9b5891e227.png)

I have no idea how I can fix that.

**Comment by Muhammadyusuf96** [comment]
This device was released in three revisions. I have a second revision. Before it had one problem. When I opened the control panel and clicked on a new SMS, it [froze](https://community.tp-link.com/en/home/forum/topic/202338). Then they corrected it, but i'm faced a new issue: after reset it is impossible to configure in a web browser. These were internal problems, then this problem appeared.

**Comment by ilya-fedin** [comment]
Why did you tell this? :thinking:
