### ISSUE TITLE
Messages i sent are on the left instead of the right

### ISSUE THREAD

**Issue by LaszloVO** [telegramdesktop/tdesktop#1635]
i am talking about the messages i sent, they should be on the right side of the window

**Comment by javierabreu** [comment]
It happens to me too on Linux (Ubuntu 15.10 x64) for Telegram version 0.9.24. 0.9.18 is OK

**Comment by danwad** [comment]
I have also noticed this bug after updating today. I am using 0.9.24 dev on Windows 10 Pro.

**Comment by marcovr** [comment]
Sadly that's not a bug - they call this mess a "feature".
See the main discussiun on #1587

**Comment by LaszloVO** [comment]
Then it still doesnt work propperly because its all on the right side of the screen instead of centered

**Comment by DaFri-Nochiterov** [comment]
> Please search for existing issues before creating new ones.

![image](https://cloud.githubusercontent.com/assets/10401817/13114130/5588ff80-d5bc-11e5-9af3-ce21b93ff963.png) It's so hard?

**Comment by danwad** [comment]
#1587 #1620 #1621 #1623 #1629 #1632 #1634 #1633

**Comment by AmirBitaraf** [comment]
Another thing about this is that, if you change window mode from full screen to normal it would be fixed and your messages would float to right as last versions.
Debian stretch/sid

**Comment by auchri** [comment]
@DaFri-Nochiterov yes really :angry:

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.
