### ISSUE TITLE
Dynamic, large and uninformative socket name with no subdirectory, which makes it impossible to create a universal rule for firejail

### ISSUE THREAD

**Issue by IlyaIndigo** [telegramdesktop/tdesktop#16350]
If I launch telegram-desktop via firejail from any browser (firefox, chromium) via firejail (previously enabling dbus), a problem appears, the 2nd instance is launched.
This is due to the directive `include whitelist-runuser-common.inc` in the browsers profile.
The contents of this file.
```
whitelist ${RUNUSER}/bus
whitelist ${RUNUSER}/dconf
whitelist ${RUNUSER}/gdm/Xauthority
whitelist ${RUNUSER}/ICEauthority
whitelist ${RUNUSER}/.mutter-Xwaylandauth.*
whitelist ${RUNUSER}/pulse/native
whitelist ${RUNUSER}/wayland-0
whitelist ${RUNUSER}/wayland-1
whitelist ${RUNUSER}/xauth_*
```

It would seem that one should simply ask the firejail developer to add something to this list
`whitelist ${RUNUSER}/telegram-desktop`
But the socket name isn't `telegram-desktop` at all, but some ugly windows registry-style `d937f37639639c4916b9e587fdf17f18985-{87A94AB0-E370-4cde-98D3-ACC110C5967D}`.
Everyone else in `/run/user/1000/` has nice, short and clear names everywhere but this one.

This name should be either shortened and understandable, for example (telegram-_short_instance_number_) and/or make a directory (telegram-desktop or telegram or tg) to make it clear whose socket it is and it was possible to write a universal rule for `firejail`. `whitelist ${RUNUSER}/telegrem-desktop-*` or `whitelist ${RUNUSER}/tg/*`.

It would be like having the home directory not `~/.local/share/TelegramDesktop` but `~/.local/share/d937f37639639c4916b9e587fdf17f18985-{87A94AB0-E370-4cde-98D3-ACC110C5967D}`.

There is also a maximum socket limit of 108 characters and it's just a time bomb on top of the problem I described.

P.S. Here https://github.com/telegramdesktop/tdesktop/issues/16349 in a dialogue with the developer I did not find understanding and decided to publish this as a bug.

**Comment by ilya-fedin** [comment]
> Here #16349 in a dialogue with the developer

I'm not 'the developer', I'm a third-party contributor.

**Comment by ilya-fedin** [comment]
@Aokromes I suggest to close this issue with wontfix, there's no need to change socket name to run tdesktop with firejail and changing socket name just because someone doesn't know how firejail works doesn't have sense.
