### ISSUE TITLE
Missing audio output options in Call Settings

### ISSUE THREAD

**Issue by Techn0core** [telegramdesktop/tdesktop#16355]
### Steps to reproduce
1. View Call Settings (Settings > General > Call Settings OR Calls Tab > Gear icon)

### Expected behaviour
Audio input and output settings

### Actual behaviour
There are input settings for Camera and Microphone, but there are no settings for Speaker / Output

### Configuration
**Operating system:**
macOS Big Sur 11.2.3

**Version of Telegram Desktop:**
Version: 7.7 (215786) AppStore

![Telegram_MacOS_AppSore_CallSettings](https://user-images.githubusercontent.com/2213107/119038299-2ef1b400-b970-11eb-97f1-38344f15a8d0.jpg)

**Comment by ilya-fedin** [comment]
You're using not telegram desktop

**Comment by Techn0core** [comment]
Do you close all tickets labeled TG macOS Swift? I saw the label and assumed that meant this was the correct place to report a bug.

**Comment by ilya-fedin** [comment]
![изображение](https://user-images.githubusercontent.com/17829319/119151111-97a76200-ba3e-11eb-815c-25fd6d1a89af.png)

**Comment by Aokromes** [comment]
> TG macOS Swift

Telegram macOS Swift is a different program than telegram desktop (telegram lite on macos)

**Comment by Techn0core** [comment]
is it this repo? https://github.com/overtake/TelegramSwift

**Comment by ilya-fedin** [comment]
yeah
