### ISSUE TITLE
Telegram Desktop window resolution remains unchanged after changing it in Windows

### ISSUE THREAD

**Issue by serg-157** [telegramdesktop/tdesktop#16359]
### Steps to reproduce
Variant 1
1. Launch Telegram Desktop on the Windows machine having 1920x1080 or any other display resolution
2. Go to Settings\Display\Scale and layout and change it from 100% to 200%
3. Telegram Desktop window resolution remains unchanged

Variant 2
1. Launch Telegram Desktop on the Windows Machine 1 having 2560x1440 or any other high resolution
2. Using Remote Desktop, Connect to Machine 1 from Machine 2 having 1920x1080 or any other low resolution
3. Telegram Desktop window resolution remains unchanged (high)

### Expected behavior
Telegram Desktop should process the WM_DPICHANGED Windows message and change its resolution accordingly

### Actual behavior
Telegram Desktop doesn't change its own resolution after changing it in Windows

### Configuration
Windows 10 Pro, build 20H2/19042.985

**Version of Telegram Desktop:**
2.7.4

**Used theme**:
Dark

**Comment by ilya-fedin** [comment]
#1121

**Comment by serg-157** [comment]
Ok then please fix this guys, this is insanely annoying

**Comment by ilya-fedin** [comment]
It's unlikely to be fixed any time soon, implementing runtime scale change is a huge task
