### ISSUE TITLE
2.7.4 Freezing constantly.

### ISSUE THREAD

**Issue by gakun17** [telegramdesktop/tdesktop#16351]
Started a few hours ago. Every 5-6 seconds the software's window freezes and displays the "Not Responding" message. This is every time you are typing a message or navigating through other menus. Currently using Windows 10 Home 1909.

**Comment by Muhammadyusuf96** [comment]
how you connected to the internet?

**Comment by ilya-fedin** [comment]
Get a dump from task manager when the process is freezed and send it to @john-preston via Telegram (`@preston` there)

**Comment by gakun17** [comment]
Sadly I can not do what it was instructed due to my internet being too slow to upload the file. Another thing I notice is that the HDD activity is around 100% every time Telegram freezes.

**Comment by ilya-fedin** [comment]
> Sadly I can not do what it was instructed due to my internet being too slow to upload the file.

Find a way to upload it, it's impossible to move issue forward without a dump.

**Comment by Aokromes** [comment]
> Sadly I can not do what it was instructed due to my internet being too slow to upload the file. Another thing I notice is that the HDD activity is around 100% every time Telegram freezes (no other software is affected).

try to upload the file to mega.nz

**Comment by Aokromes** [comment]
also, you may try to download 2.7.0-2.7.3 portable to see if it stops freezing and send the file there.

**Comment by ilya-fedin** [comment]
sending the file publicly is not a good idea

**Comment by Aokromes** [comment]
> sending the file publicly is not a good idea

he can send the link to preston on telegram if fast enough.
