### ISSUE TITLE
[Question] Why does '🥲' emoji look weird on telegram?

### ISSUE THREAD

**Issue by ShrirajHegde** [telegramdesktop/tdesktop#16354]
🥲 emoji works fine everywhere except telegram. In telegram, it is blurry and small.

![image](https://user-images.githubusercontent.com/66936172/119035568-53c84480-b9cd-11eb-85ab-81f3e89e013b.png)
compared to 🥲🙃  on github / everywhere else:
![image](https://user-images.githubusercontent.com/66936172/119035676-72c6d680-b9cd-11eb-9663-f81c711ac15e.png)

**Comment by ilya-fedin** [comment]
#9775
