### ISSUE TITLE
[Question] Time for QML Interface Rewrite yet?

### ISSUE THREAD

**Issue by LeonnardoVerol** [telegramdesktop/tdesktop#16366]
> Using QML would make the UI way more maintainable - it would likely also attract people to contribute who are put off by the interface code right now (i couldn't even find it!).

Reference: #352

**Comment by john-preston** [comment]
@LeonnardoVerol I think the task of rewriting on QML has a complexity of the same order of magnitude that writing from scratch a new app based on tdlib has.

**Comment by nuclight** [comment]
LOL, the next "feature" request will be using tdlib... well, try and go writing new client with both technologies yourself.
