### ISSUE TITLE
Sticker packs not able to add after clicking

### ISSUE THREAD

**Issue by Arunachala-Ramana** [telegramdesktop/tdesktop#16362]
I use telegram desktop in ubuntu 20.04. Whenever my friends use to share a new sticker and I wanted to add it to my stickers list i just have to click on the sent sticker and then it use to show up the sticker pack and the "add sticker" option. 

Has this option been disabled now? This option of clicking on the sticker and adding it to your sticker pack seems disabled atleast to me.

**Comment by ilya-fedin** [comment]
Template removed -> issue is invalid

**Comment by Arunachala-Ramana** [comment]
Issue is invalid? Needs user action? I am new to this could someone please explain what this means?

**Comment by ilya-fedin** [comment]
This means you haven't provided required information due to removing entire issue template and filling the issue in a free form. Ideally the issue should be closed...

**Comment by Arunachala-Ramana** [comment]
Hold on. Where do I get the issue template?. I can refill it right now if you want.

**Comment by ilya-fedin** [comment]
> Where do I get the issue template?

You should get it when you creating an issue
![изображение](https://user-images.githubusercontent.com/17829319/119529501-b0cb4e00-bd71-11eb-917b-14b04867a464.png)

**Comment by Arunachala-Ramana** [comment]
No this never appeared when I wrote the issue. Sorry. What should i do now?

**Comment by ilya-fedin** [comment]
Probably close this issue and open a new one, with the template

**Comment by Arunachala-Ramana** [comment]
Sure. Thank you.
