### ISSUE TITLE
2.7.4 Crashes while recording a voice message

### ISSUE THREAD

**Issue by codiflow** [telegramdesktop/tdesktop#16365]
### Steps to reproduce
1. Open any chat and slide up on the button for "recording voice message" in the bottom right corner.

### Expected behaviour
Voice message should be recorded

### Actual behaviour
Telegram Desktop crashes

### Configuration
**Operating system:**
Manjaro Linux
Linux PC 5.4.118-1-MANJARO #1 SMP PREEMPT Tue May 11 17:46:18 UTC 2021 x86_64 GNU/Linux

**Version of Telegram Desktop:**
2.7.4
(2.7.2 worked like expected)

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Manjaro updater (community/telegram-desktop)

**Used theme**:
Dark theme

<details><summary><b>gdb log</b>:</summary>
[ALSOFT] (EE) Failed to set real-time priority for thread: Die Operation ist nicht erlaubt (1)
[Thread 0x7fff8e5dc640 (LWP 47616) exited]
Thread 15 "QThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9ffff640 (LWP 47593)]
0x00007fffede2081d in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fffede2081d in __memmove_avx_unaligned_erms () at /usr/lib/libc.so.6
#1  0x0000555556e9f4fd in  ()
#2  0x000055555753ae42 in  ()
#3  0x00007fffefb8925f in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#4  0x00007fffef20c762 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#5  0x00007fffefb5c81a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#6  0x00007fffefbb46a5 in QTimerInfoList::activateTimers() () at /usr/lib/libQt5Core.so.5
#7  0x00007fffefbb4f8a in  () at /usr/lib/libQt5Core.so.5
#8  0x00007fffee35c02c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#9  0x00007fffee3afb59 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007fffee359781 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#11 0x00007fffefbb5321 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#12 0x00007fffefb5b17c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#13 0x00007fffef972ea2 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#14 0x00007fffef97408f in  () at /usr/lib/libQt5Core.so.5
#15 0x00007ffff0c8f299 in start_thread () at /usr/lib/libpthread.so.0
#16 0x00007fffeddbb053 in clone () at /usr/lib/libc.so.6
</details>

**Comment by Aokromes** [comment]
distribution package only bug, they need to update to telegram desktop 2.7.6 source or you must change to webpage (desktop.telegram.org) package.
