### ISSUE TITLE
telegram-desktop file browser changed

### ISSUE THREAD

**Issue by dm17** [telegramdesktop/tdesktop#16367]
I recall there being a file browser that had search functionality & matched telegram-desktop & system theme. It disappeared last year and I never figured out why. What decides which file browser functionality telegram-desktop has? The old one was great and search made it super quick to file the right files to attach.

Thanks!

**Comment by ilya-fedin** [comment]
> matched telegram-desktop & system theme

Well, tdesktop itself never matched system theme

> What decides which file browser functionality telegram-desktop has?

Well, I assume you mean file chooser dialog by 'file browser'. Choosing algorithm changes frequently, as of 2.7.4 it's:
1. XDG Desktop Portal always preferred
2. If XDG Desktop Portal is not installed and you're using a GTK DE, tdesktop uses gtk library to open dialog
3. If that fails or you're not using GTK DE, it uses the common QFileDialog.

**Comment by dm17** [comment]
Thanks! Now I found this page: https://github.com/telegramdesktop/tdesktop/wiki/Environment-variables
Installing those two packages doesn't get me the nice file browser, but exporting TDESKTOP_USE_GTK_FILE_DIALOG=1 does! Any idea why?

**Comment by ilya-fedin** [comment]
> Installing those two packages

I don't which 'those two packages' you mean, but you should have `xdg-desktop-portal` (the frontend) and one of its backends that provide FileChooser intarface (e.g. `xdg-desktop-portal-kde` or `xdg-desktop-portal-gtk`) installed. You should also have working dbus session instance, of course.

**Comment by dm17** [comment]
@ilya-fedin Ya, I meant that installing ```xdg-desktop-portal``` & ```xdg-desktop-portal-gtk``` does not get me a different file browser, while ```TDESKTOP_USE_GTK_FILE_DIALOG=1``` does.

**Comment by ilya-fedin** [comment]
Maybe session dbus instance is not running?

**Comment by dm17** [comment]
I don't this dbus is a requirement for telegram-desktop. Is it?

**Comment by ilya-fedin** [comment]
it's a requirement for xdg desktop portal. It works via dbus.

**Comment by dm17** [comment]
We can close this I guess. I try not to have flatpak-related-stuff installed. And ```TDESKTOP_USE_GTK_FILE_DIALOG=1``` makes it work anyway (despite the other pkgs not being installed).
Thanks :)

**Comment by meklonets** [comment]
Sorry,
But could you tell what package is fault for the issue I have?
Wayland. Sway. Telegram. Two monitors: first one UltraHD and second one FullHD. 
And file-chooser window is weird drawing in UHD monitor. If I move it to FullHD - everything is ok.
Made scrrencast: https://youtu.be/tD0DfGIZ734

**Comment by ilya-fedin** [comment]
> But could you tell what package is fault for the issue I have?

It's Qt
