### ISSUE TITLE
[Archlinux][0.9.24] Segfault when clicking on trayicon

### ISSUE THREAD

**Issue by zeronote** [telegramdesktop/tdesktop#1636]
Got a segmentation fault when clicking on trayicon.

`uname -a`
`Linux archtest 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux
`

`gnome-shell --version`
`GNOME Shell 3.18.3`

here a [strace_log.txt](https://github.com/telegramdesktop/tdesktop/files/134851/strace_log.txt)

**Comment by definetti** [comment]
+1

**Comment by ARamsey118** [comment]
I am also having this issue.

```uname -a```
```Linux aragorn 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux```

```xfce4-about --version```
```xfce4-about 4.12.1 (Xfce 4.12)```

I am using the prebuilt binary from the website. Here's another 
[strace_log.txt](https://github.com/telegramdesktop/tdesktop/files/135690/strace_log.txt)

**Comment by va-al** [comment]
bug affected to me(+1)

**Comment by Aokromes** [comment]
Very likely the same as https://github.com/telegramdesktop/tdesktop/issues/1630

**Comment by chmercesmoreira** [comment]
I was having the same bug, but now it disappear.
#1628

**Comment by OpenCode** [comment]
Me too. This happen on Debian 8 (Gnome Shell) and Ubuntu 15.04 (Unity), too.

**Comment by Fenisu** [comment]
I have the same problem, using latest Telegram 0.9.24 and Arch linux with gnome3.

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It should be fixed there (e.g. if 0.9.18 worked fine for you, this one should be working as well).

**Comment by ARamsey118** [comment]
0.9.25 is working, thank you!
