### ISSUE TITLE
[Feature Request] Virtual keyboard overlay on application support

### ISSUE THREAD

**Issue by espidev** [telegramdesktop/tdesktop#16368]
### Is your feature request related to a problem?
Context: Usage in Plasma Mobile, but applies to desktop as well

Currently, telegram relies on the window being resized to being above the virtual keyboard.

### Describe the solution you'd like

While this "works", the optimal way to implement this is to have the application itself support adding a bottom margin where the keyboard would be (Qt.inputMethod.keyboardRectangle.height in QML returns the height of the keyboard over the app window, not sure what the C++ equivalent is).

This is the already the case for Android and iOS, I just think the desktop app should also support this, especially since the app works quite well on Linux mobile.

### Additional context

The input bar is covered if window resizing is disabled in KWin:

![Screenshot_20210524_155919](https://user-images.githubusercontent.com/7444510/119401220-32a37480-bca9-11eb-97c3-c0f62b491208.png)

Adding the reported height of the keyboard below the textfield would fix the issue on this page.

An easy(?) fix would be to add an application bottom margin that is always the keyboard height.

**Comment by ilya-fedin** [comment]
#3274

**Comment by ilya-fedin** [comment]
I think tdesktop should somehow indicate that linux phones is not a supported target to stop these stupid issues appearing...

**Comment by espidev** [comment]
> I think tdesktop should somehow indicate that linux phones is not a supported target to stop these stupid issues appearing...

Apologies for the duplicated issue, but it's more about the virtual keyboard, not anything linux mobile specific...

**Comment by ilya-fedin** [comment]
tdesktop design is not so adaptive, of course it won't work good on such small screens. And even on tablets with virtual keyboards.

**Comment by ilya-fedin** [comment]
I can't get why you don't disable window border though

**Comment by espidev** [comment]
> tdesktop design is not so adaptive, of course it won't work good on such small screens. And even on tablets with virtual keyboards.

This issue doesn't have anything to do with screen size, it's a request to support virtual keyboards on top of apps rather than having them being two separate entities with window managers being responsible for resizing telegram's window each time the keyboard opens.

Sorry for dragging it out, I didn't want to pressure about it or anything... was just seeing if it was viable

**Comment by ilya-fedin** [comment]
> This issue doesn't have anything to do with screen size

It is. tdesktop designed in a way it gets graphical artifacts when window size is less than some value.

> it's a request to support virtual keyboards on top of apps rather than having them being two separate entities with window managers being responsible for resizing telegram's window each time the keyboard opens

That sounds weird. Virtual keyboards are separate apps, they decrease the window size and open themselves. tdesktop's minimal size hint is bigger than the size virtual keyboard wants resize the window to (due to the not-so-adaptive design), that's why you're getting a part of the window under the keyboard. You can decrease scale factor and it will work as it should most likely.

**Comment by espidev** [comment]
> That sounds weird. Virtual keyboards are separate apps, they decrease the window size and open themselves. tdesktop's minimal size hint is bigger than the size virtual keyboard wants resize the window to (due to the not-so-adaptive design), that's why you're getting a part of the window under the keyboard. You can decrease scale factor and it will work as it should most likely.

:facepalm: oops

I realize I forgot to include any context with why the keyboard is like that. I disabled window resizing for the keyboard in KWin in that screenshot.

The keyboard with tdesktop does work fine, even on mobile actually (when window resizing for the keyboard is enabled), apologies.

I was looking into having support for the keyboard on top to skip the window resize needed (since that's how it is done on most mobile platforms), but it's not really an issue if the window manager can deal with apps that do and don't support it simultaneously...

**Comment by ilya-fedin** [comment]
> I realize I forgot to include any context with why the keyboard is like that. I disabled window resizing for the keyboard in KWin in that screenshot.

Oh. Your feature request doesn't apply to desktop then, desktop virtual keyboards just resize the window.
