### ISSUE TITLE
GIFs sent from the GIF panel still send from @gif

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#16379]
### Steps to reproduce
1. open the emoji panel
2. switch to GIFs
3. search for a GIF
4. send a GIF from the GIFs search results

### Expected behaviour
GIFs are sent without proxing them through the @gif bot, as any other client does since a few years

### Actual behaviour
GIFs sent from the search look like GIFs sent using the inline mode of the @gif bot

### Configuration
**Operating system:** any

**Version of Telegram Desktop:** 2.7.5

**Comment by john-preston** [comment]
@RememberTheAir The search in the GIF panel is really a search in the inline bot results, that's why they're sent from inline bots.

**Comment by RememberTheAir** [comment]
@john-preston thanks for the answer, I guessed so. Isn't there a way to send the GIF in the same way the mobile apps do? A lot of people who are not used to telegram search for gifs and then see this weird "via @gif" and they have no idea what it means and why it appears above their messages while other people's gif's are normal

**Comment by RememberTheAir** [comment]
I am going to leave a Kotatogram commit here that fixes this issue, for future reference: https://github.com/kotatogram/kotatogram-desktop/commit/7505a6c6fcf9e215392e047ee70de6e04ccbe55a

**Comment by RememberTheAir** [comment]
Figured out mobile apps perform a search using the @gif bot too, but they simply send the result picked by the user without displaying the "via @gif" tag. tdesktop's missing the method flag to do that

**Comment by RememberTheAir** [comment]
Ping about this. Yesterday I had to explain again to a friend of mine why the gif search from Telegram Desktop always attaches a "sent via @gif" to their message. This is confusing for the sender and the receivers too, if they are not familiar with the concept of inline bots. And it's confusing even if they are familiar with them, since you wouldn't expect the gif search to work this way (and I guess this is why the mobile apps hides that). You literally can't make sense of it if you're not very much into Telegram

**Comment by RememberTheAir** [comment]
Fixed with 173fdf8 on 3.5.6
