### ISSUE TITLE
I think there should be a way to attach a subtitle in Telegram internal video player.

### ISSUE THREAD

**Issue by PranavBhattarai** [telegramdesktop/tdesktop#16372]
A lot of educational content which are shared on Telegram like University lecture videos, etc because, for some reason, their country might have banned the website which is hosting these free non-licensed videos.

YouTube is one example that is banned in countries like China, Syria, North Korea, Iran, Tajikistan, etc. 

The problem with these videos is, students can't just stream them. They have to download it first and attach the caption on the video using external players like VLC or MPV. This consumes a lot of time because it's not a real-time solution.

The real-time solution is, play a video, and if the video does contain an embedded subtitle, play it as it is, else provide an option to can attach the subtitle on it. This reduces the amount of time required to learn something.

This will help non-native English speaker like us because American accent is a bit different to listen and understand each word.

This will also help deaf students to watch and learn from videos where they can attach subtitles.

I don't think Telegram recognizes a video embedded subtitle, first Telegram devs need to do something about this.
Second, they should make the video player a bit more dynamic. 

Telegram is not just a messaging app anymore. It's much more. It can be used for voting, college meetings, college submission, college projects, etc sh*t tons of things. 

We need these features which doesn't violate any laws by far.

**Comment by Aokromes** [comment]
i think this needs server side support.

**Comment by tomyangsh** [comment]
> i think this needs server side support.

Can the local video player just load the MPEG-4 Timed Text(see https://en.wikipedia.org/wiki/MPEG-4_Part_17) subtitle tracks within the mp4 file?

**Comment by derekdai** [comment]
Please~ please~ implement embedded subtitle rendering for player
