### ISSUE TITLE
Unordered messages and sync delays (only in TDesktop, not in Telegram Android)

### ISSUE THREAD

**Issue by brauliobo** [telegramdesktop/tdesktop#16375]
Hi, many times when coming back to Telegram-Desktop I see unordered message like in the screenshot below.

Also very common is a almost a minute delay between messages appearing in Android and messages appearing in Telegram Desktop

![image](https://user-images.githubusercontent.com/41740/119695690-d06f7e80-be24-11eb-87eb-f868118b4169.png)

**Comment by ilya-fedin** [comment]
#2797

**Comment by ilya-fedin** [comment]
If you have such problem persistently, check that you're running the newest versions, old versions are disabled from message queues

**Comment by brauliobo** [comment]
Yes I am using the latest version always with Archlinux
