### ISSUE TITLE
Sticker packs don't add into the list after clicking

### ISSUE THREAD

**Issue by Arunachala-Ramana** [telegramdesktop/tdesktop#16371]
### Steps to reproduce
1. Friend chats with me.
2. He sends a new sticker which I don't have.
3. I click on the sent sticker by my friend

### Expected behaviour
Once i click on the sticker the sticker should show me the full sticker set and give me an option of adding that sticker to my list. 

### Actual behaviour
Nothing happens. 

### Configuration
**Operating system:** Ubuntu 20.04 LTS

**Version of Telegram Desktop:** Version 2.7.4 

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Official website

**Used theme**: Standard theme which was there during download. I haven't altered anything at all.

**Comment by RememberTheAir** [comment]
Some stickers don't have a pack: maybe it's just a webp file your friend uploaded and you see it as a sticker (stickers are webp files)

**Comment by ilya-fedin** [comment]
Yeah, looks like you got a sticker without a stickerpack

**Comment by Arunachala-Ramana** [comment]
No. I have seen that sticker before and used also. But this issue i am recently facing.

**Comment by ilya-fedin** [comment]
> I have seen that sticker before and used also

There's no guarantee it's the same sticker. The same picture can be in multiple packs and can be sent without a pack.

**Comment by RememberTheAir** [comment]
Can you forward that sticker to [@jsondumpbot](https://t.me/JsonDumpBot) and paste the output here?

**Comment by Arunachala-Ramana** [comment]
{
  "update_id": 144032719,
  "message": {
    "message_id": 362775,
    "from": {
      "id": 864158582,
      "is_bot": false,
      "first_name": "Chandrasekhar",
      "language_code": "en"
    },
    "chat": {
      "id": 864158582,
      "first_name": "Chandrasekhar",
      "type": "private"
    },
    "date": 1621961385,
    "forward_from": {
      "id": 121198808,
      "is_bot": false,
      "first_name": "Kannan",
      "last_name": "R"
    },
    "forward_date": 1621960714,
    "text": "👍"
  }
}

**Comment by ilya-fedin** [comment]
It's not a sticker, it's a big emoji

**Comment by Arunachala-Ramana** [comment]
Is it so? It is also animated and I don't have it in my desktop though :(

**Comment by Arunachala-Ramana** [comment]
Looks like it's a feature only for the smartphones is it so?

**Comment by ilya-fedin** [comment]
> Is it so? It is also animated and I don't have it in my desktop though :(

It's a big animated emoji, you can dsiable "Large emoji" option in Settings -> Chat Settings and it will look like common emoji.

> Looks like it's a feature only for the smartphones is it so?

What are you talking about?

**Comment by Arunachala-Ramana** [comment]
Right. I got the point. I was under the impression that the "large animated emoji" was only a feature in the mobile version and not on the desktop version. Thanks for clarifying and biggggggggg thanks for your time. Apologies for taking your time. I am closing the issue. :)
