### ISSUE TITLE
[Feature Request] File sending queue

### ISSUE THREAD

**Issue by HackcatDev** [telegramdesktop/tdesktop#16373]
When I send multiple files on bad upstream internet channel, I have a problem to prioritize sendings (pause some uploads). I'm able just to cancel some, but not pause.

I'd like to see a PAUSE button to suspend specific uploads. Also it'll be great to automatically send smallest files first

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/809
