### ISSUE TITLE
Partially copy a text

### ISSUE THREAD

**Issue by ticoti** [telegramdesktop/tdesktop#1637]
I remember I could partially copy a text selecting the text and clicking with the right button but now I don't have that option. Why this changed?

**Comment by SDKiller** [comment]
+1

This is a huge regression and is definitely a bug.

After last desktop update to 0.9.24 'Copy selected text' disappeared from context menu if you selected only part of the message.

**Comment by SDKiller** [comment]
@ticoti 

`Ctrl-C` - `Ctrl-V` are still available for copy-pasting partially selected text (at least on Windows 7)

**Comment by ticoti** [comment]
@SDKiller Thanks in Windows 10 too, but I actually preferred the context menu :/

**Comment by telegramdesktop** [comment]
@ticoti This is a bug and it will be fixed in the next version, currently you can use Ctrl+C (Cmd on OS X) for that.

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It should be fixed there.
