### ISSUE TITLE
Virus in the downloaded Windows version?

### ISSUE THREAD

**Issue by JasonGross** [telegramdesktop/tdesktop#16374]
Downloading either the portable or the desktop version from https://desktop-messenger.me/ gives me "Failed - Virus detected".
![image](https://user-images.githubusercontent.com/396076/119693931-c47ebf00-be1a-11eb-8671-4d7c985be4cc.png)

Windows Defender details:
![image](https://user-images.githubusercontent.com/396076/119694104-ec6e2280-be1a-11eb-9f76-60f2a3443c40.png)

Trojan:Win32/AgentTesla!ml
webfile: D:\Downloads\TelegramInstaller.exe|https://cdn.discordapp.com/attachments/847105350708887565/847105885951229982/TelegramInstaller.exe|pid:11912,ProcessStart:132665186088109016
webfile: D:\Downloads\TelegramInstaller.exe|https://cdn.discordapp.com/attachments/847105350708887565/847105885951229982/TelegramInstaller.exe|pid:29396,ProcessStart:132665187657263954

Learn more links to https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Win32/AgentTesla!ml&threatid=2147760503

**Comment by Aokromes** [comment]
false positive.

**Comment by john-preston** [comment]
@Aokromes Maybe not. What is this website?

**Comment by john-preston** [comment]
@JasonGross https://desktop-messenger.me is not Telegram Desktop website.

**Comment by HackcatDev** [comment]
Fake website. Official is telegram.org

**Comment by JasonGross** [comment]
It's the first result in google for me (as an ad)
![image](https://user-images.githubusercontent.com/396076/119700247-f5fa8900-be20-11eb-99f0-bd23db9d41f9.png)

Maybe it should be reported to Google or issued a DMCA takedown or something?  Note that this fake website has a link to this GitHub repo as the sourcecode, which seems like strong evidence that they're trying to pretend to be Telegram

**Comment by JasonGross** [comment]
I've reported the Ad as violating Google Ad policies

**Comment by HackcatDev** [comment]
@JasonGross why don't you use adblocker? It's a must nowadays. I use it for years and really don't understand why others can't spend 3 minutes setting it up

**Comment by JasonGross** [comment]
I haven't been bothered to set it up.  It's not a big deal for me, now that I know what the telegram website is supposed to be I know to watch out for this.  I'm more concerned about other users who are not as tech savvy as us who may be told by an employer or friend group "we use telegram for messaging" and then end up getting a virus rather than the telegram client.
