### ISSUE TITLE
[Feature Request] count read message in group chat

### ISSUE THREAD

**Issue by long76** [telegramdesktop/tdesktop#16389]
### Is your feature request related to a problem?
i can't see all users of group read message or not

### Describe the solution you'd like
vv [1] vv [x]  x - count users of group

### Describe alternatives you've considered
change vv - anyone read vvv - all read. smth like required message for all but not keep in head.

**Comment by RememberTheAir** [comment]
This is out of the scope of this project (desktop client) because it requires the server to support this. It's probably related to [this suggestion](https://bugs.telegram.org/c/84) in the official platform, you can upvote it
