### ISSUE TITLE
Music playlist view - ID3 tag Title is shown as Unknown Track

### ISSUE THREAD

**Issue by champmit** [telegramdesktop/tdesktop#16386]
### Steps to reproduce
1. Upload/View Any music playlist in channel/group
2. Observe the music files (flac/mp3) displayed in the list
3. The Title is always displayed as Artist - Unknown Track

### Expected behaviour
The playlist view should display Artist - Track title (e.g. Emniem - Bad guy)

### Actual behaviour
The playlist view is always displaying Artist - Unknown Track

### Configuration
**Operating system:**
Windows 10 latest update

**Version of Telegram Desktop:**
The version downloaded from Microsoft App Store in Windows 10 

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Default Theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>
How telegram show:

![bug view](https://user-images.githubusercontent.com/1648624/120078273-52350580-c0cc-11eb-84b1-b19f206e88eb.JPG)

ID3 tags parsed for the first file in Windows property sheet viewer.

![actual id3 tags](https://user-images.githubusercontent.com/1648624/120078294-7264c480-c0cc-11eb-919a-cf46e143ac90.JPG)

**Comment by ilya-fedin** [comment]
The file on second screenshot is definitely not the files shown on first screenshot since tdesktop doesn't support FLAC files as music files

**Comment by champmit** [comment]
Closing issue, as this was fixed while posting new media via API.
