### ISSUE TITLE
Badge counter display unread messages for an inactive account despite "Show notifications from all accounts" is off

### ISSUE THREAD

**Issue by Deilan** [telegramdesktop/tdesktop#16385]
### Steps to reproduce
1. Add first telegram account.
2. Add second telegram account.
3. **Settings** → **Notifications** → **Show notifications from**: **All accounts** — OFF
4. Switch to the first account. Mark all messages as read (so there's no unread messages).
5. Get a new (unread) message for the second account.

### Expected behaviour
1. App's taskbar icon's badge counter is not displayed (since there's no messages for the first account).
2. App's system tray icon's badge counter is not displayed (since there's no messages for the first account).

### Actual behaviour
1. App's taskbar icon's badge counter is displayed and displays 1 (or more) unread message.
2. App's system tray icon's badge counter is displayed and displays 1 (or more) unread message.

### Configuration
**Operating system:** Windows 10 Version 21H1

**Version of Telegram Desktop:** 2.7.4 x64

**Used theme**: Tinted

**Comment by Deilan** [comment]
Expected behavior relies on the same case for the Android and iOS apps.

**Comment by aahnik** [comment]
this is very important. Someone, please fix it. I badly need this to be fixed. I don't know enough to fix this myself. I hope that someone from the community will fix it soon. 

**thanks in advanced** to the person/persons who will fix this

**Comment by aahnik** [comment]
this is same https://github.com/telegramdesktop/tdesktop/issues/8189
