### ISSUE TITLE
All messages are on the same side in chat.

### ISSUE THREAD

**Issue by TotalKrill** [telegramdesktop/tdesktop#1638]
All messages are on the same side in chat. Version 9.24 in linux.

It only happens when the chat window is larger than half the size of the screen in width. 1920x1080px screen.

Below is a cutout of how it looks.

![strange](https://cloud.githubusercontent.com/assets/3248006/13122727/bad3ae66-d5b8-11e5-8c27-45289baac9e7.png)

**Comment by telegramdesktop** [comment]
@TotalKrill This is a feature, starting from version 0.9.24 in the wide window sizes (like most fullscreen sizes) the messages have one side layout.

We thought through and tested that change and we are sure that this way is better than it was before, although everyone is used to the old way and the new layout seems strange and unfamiliar at first. It is easier to read the conversation when the messages go one after another and not at the different sides of a large window (which is twice as wide as the widest message), the incoming and outgoing can be easily differentiated by user photo and by bubble background color (white vs green). In the wide windows the conversation area always looked ridiculous and there is no way to fill it with content in a reasonable and usable way, but at least now messages are not thrown to the different parts of the screen at random.

So it will be left that way at least for now, with no additional settings for returning to the old layout or smth like that. Sorry if someone strongly dislikes it :(

**Comment by auchri** [comment]
Please search for existing issues before creating new ones.

![image](https://cloud.githubusercontent.com/assets/10401817/13114130/5588ff80-d5bc-11e5-9af3-ce21b93ff963.png)


Discussion about this there: #1587

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.
