### ISSUE TITLE
Can't build TDesktop in WSL 2, Ubuntu

### ISSUE THREAD

**Issue by Muaath5** [telegramdesktop/tdesktop#16397]
### Steps to reproduce
1. Install WSL 2
2. Go to ~ directory using `cd`.
3. Clone tdesktop repo 
4. Try to run second 

### Expected behaviour
No error, And build completed.
Or note that TDesktop can't be built in Ubuntu in WSL 2

### Actual behaviour
This error is shown:
```
unable to prepare context: path "Telegram/build/docker/centos_env/" not found
```

### Configuration
**Operating system: Windows 10 Pro, 20H2**.
**Linux version: WSL 2, Ubuntu 20.04**.

**Version of Telegram Desktop:** Latest from repository.
**Installation source (Linux Only):** Git clone

**Comment by ilya-fedin** [comment]
> unable to prepare context: path "Telegram/build/docker/centos_env/" not found

Are you sure you executed the command from the root of the repository?

**Comment by Muaath5** [comment]
@ilya-fedin 
I re-executed the command from the root of the repo, This error is shown:
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by ilya-fedin** [comment]
docker is not running

**Comment by ilya-fedin** [comment]
You should know how to work with docker before building tdesktop

**Comment by ilya-fedin** [comment]
If Docker doesn't support WSL, you can't build tdesktop

**Comment by Aokromes** [comment]
> If Docker doesn't support WSL, you can't build tdesktop

It does.
https://docs.docker.com/docker-for-windows/wsl/

**Comment by ilya-fedin** [comment]
It's a @Muaath5 job to learn how to build tdesktop on WSL then

**Comment by Muaath5** [comment]
> 
> 
> It's a @Muaath5 job to learn how to build tdesktop on WSL then

How can I know? From where? **TDesktop should has a full-explained How To Build TDesktop**.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md

**Comment by ilya-fedin** [comment]
> **TDesktop should has a full-explained How To Build TDesktop**.

It's assumed whoever wants to build already is enough experienced. It is not a good idea to build tdesktop if you're a newbie.

**Comment by ilya-fedin** [comment]
> How can I know? From where?

well, you can google "how to use docker" and etc
