### ISSUE TITLE
[Feature Request] can't edit poll after send

### ISSUE THREAD

**Issue by long76** [telegramdesktop/tdesktop#16390]
### Is your feature request related to a problem?
i can't add/remove/edit option in poll

### Describe the solution you'd like
add ability to edit poll

### Describe alternatives you've considered
add ability reset poll with edit

**Comment by RememberTheAir** [comment]
The API doesn't support polls editing, after they are sent. There's already [a suggestion](https://bugs.telegram.org/c/966) on the official suggestions platform, but I believe it's a design choice that is hardly going to change
