### ISSUE TITLE
error while loading shared libraries: librnnoise.so.0 ?

### ISSUE THREAD

**Issue by repsorp** [telegramdesktop/tdesktop#16398]
### Steps to reproduce
1. Try to open telegram-desktop in terminal

### Expected behaviour

- telegram-desktop application opens

### Actual behaviour

- Nothing happens

### Configuration
**Operating system:** Ubuntu 20.10
**Version of Telegram Desktop:** 2.7.6-beta-209-g46b4a5fc5 (2696)
**Installation source (Linux Only)**: snap
<details><summary><b>Logs</b>:</summary>
telegram-desktop: error while loading shared libraries: librnnoise.so.0: cannot open shared object file: No such file or directory

</details>

**Comment by drupol** [comment]
Same issue.

**Comment by klipitkas** [comment]
Same issue here as well.

**Comment by ilya-fedin** [comment]
Do you you're using edge channel that has builds from dev branch and can stay broken for weeks?

**Comment by repsorp** [comment]
clearly, but does that exempt you from reporting errors?

**Comment by ilya-fedin** [comment]
> Clearly

I hope others know as well.

**Comment by klipitkas** [comment]
Thank you @ilya-fedin I know but I hope I can report stuff before it gets to the stable release.
