### ISSUE TITLE
[Feature Request] Ability to add Tags to people in groups when sending images

### ISSUE THREAD

**Issue by mohamad97-alhomsi** [telegramdesktop/tdesktop#16391]
**Problem:**

In the Desktop version when sending a photo in groups, A user can't mention any member in this said group, however, In the mobile version, this is possible,
So currently in Telegram Desktop App, I have to send the image first then reply to it in order to tag someone in this group.
 
 **Suggestion:**
 
Bring this feature to Telegram Desktop.

**Comment by RememberTheAir** [comment]
More or less a duplicate of #9020, which is about documents but can be extended to all captioned medias
