### ISSUE TITLE
ERROR: [029]: page size is 16384 but must be 8192 

### ISSUE THREAD

**Issue by nkumar381** [telegramdesktop/tdesktop#16394]
### Steps to reproduce
1. Postgrease database  is in 16K block size / page size . When I try to create a pgbackrest stanze, we are getting error as mentioned below  - 

[fems_owner@1173285-SITDatabase data]$ pgbackrest --stanza=SIT --log-level-console=error stanza-create
ERROR: [029]: page size is 16384 but must be 8192
[fems_owner@1173285-SITDatabase data]$

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Linux
**Version of Telegram Desktop:**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
i vote this doesn't looks telegram desktop

**Comment by ilya-fedin** [comment]
\+1, it doesn't

**Comment by nkumar381** [comment]
Do we have any fix for this issue ?

**Comment by ilya-fedin** [comment]
@nkumar381 this is not a postgres bugtracker, it's a tdesktop bugtracker
