### ISSUE TITLE
[Feature Request] People Nearby for telegram desktop

### ISSUE THREAD

**Issue by kolor4do** [telegramdesktop/tdesktop#16404]

**Comment by ilya-fedin** [comment]
Nearby of what? Your IP address?

**Comment by nicolasmenegoni** [comment]
> 
> 
> Nearby of what? Your IP address?

Maybe using the cell's location...

**Comment by nicolasmenegoni** [comment]
> 
> 
> > > Perto de quê?  Seu endereço IP?
> > 
> > 
> > Talvez usando a localização do celular ...
> 
> A área de trabalho do telegrama deve funcionar em computadores, não em telefones celulares.

Wow! Really? WHAT NEW!

I'm saying it's possible, maybe they could just put it for those who have a cell phone connected to the telegram or use the location of their own ip. But the second is not needed

-Sorry my bad english

**Comment by ilya-fedin** [comment]
> maybe they could just put it for those who have a cell phone connected to the telegram or use the location of their own ip

If you mean using location of one of your phones Telegram app is installed on, this needs server API and is not applicable to this bugtracker

**Comment by p0358** [comment]
Some computers have a built-in or external GPS devices, most notably tablet devices with full x86 CPU and systems, but I don't know if it's a group big enough to make it worth implementing. Some OSs provide location services or even such services could be used manually too, but their location accuracy might be limited. Maybe better if PC has a Wi-Fi card (more frequent than GPS). But imo it should make sense to implement location sharing to chats sooner, without live update when there's no GPS, but with the ability to adjust it manually, if anything

**Comment by nicolasmenegoni** [comment]
> 
> 
> Some computers have a built-in or external GPS devices, most notably tablet devices with full x86 CPU and systems, but I don't know if it's a group big enough to make it worth implementing. Some OSs provide location services or even such services could be used manually too, but their location accuracy might be limited. Maybe better if PC has a Wi-Fi card (more frequent than GPS). But imo it should make sense to implement location sharing to chats sooner, without live update when there's no GPS, but with the ability to adjust it manually, if anything

Exactly. But you don't necessarily need to use the computer's location. It could simply detect the location of some mobile device that the account is connected to. If you don't have any, the function will be disabled.

**Comment by ilya-fedin** [comment]
> Exactly. But you don't necessarily need to use the computer's location. It could simply detect the location of some mobile device that the account is connected to. If you don't have any, the function will be disabled.

That needs to be implemented server side, server side developers don't look at that tracker. Your feature request is useless here.
