### ISSUE TITLE
[Feature Request] "Disable/Enable notifications" for chat folders too

### ISSUE THREAD

**Issue by cuprum-72** [telegramdesktop/tdesktop#16400]
### Describe the solution you'd like
Add "Disable notifications" and "Enable notification" settings to the chat folders' context menu as an alternative to manage the chats and groups member of the selected folder.

### Additional context
Currently on version 2.7.4, it's only possible to disable notifications by selecting chats/groups one by one. It would improve the notification management to add the "Disable notifications" and "Enable notifications" settings to the folder context menu.

**Comment by ilya-fedin** [comment]
#7529
