### ISSUE TITLE
[Question] Converting Telegram Channel Link to RSS

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1640]
Hi
Is it possible to make a feature to convert the telegram channel link into RSS link which let us also follow it by RSS reader?

Thanks

**Comment by Kondra007** [comment]
That's an awesome idea (IMO)
Right now it's definetely possible with third-party bots or services. For example, if you use bot to post messages to channel, you can also write code to form RSS feed. 

And thanks for an idea, will try this tomorrow ;)

**Comment by amiremami** [comment]
@Kondra007 Thank you so much kondra :+1:

**Comment by amiremami** [comment]
@Kondra007 Did you achieve any results on this? It would be great if we can follow channels in RSS readers instead of telegram itself, because the UI is not so good for following too many channels, bots, people, groups.

Thanks

**Comment by thob** [comment]
:+1:

**Comment by Kondra007** [comment]
@amiremami Yeah, there're some positive results, however it's not a public service, so channels owners should do some modifications to their bots, which post to those channels.

**Comment by amiremami** [comment]
Cool man, thanks :+1:

**Comment by Kondra007** [comment]
@amiremami Here's a simple concept. Works fine for me, but it's still in development.
https://github.com/Kondra007/telegram-rss-generation

(Telegram Devs: Sorry for offtop, can't notify this user another way)

**Comment by amiremami** [comment]
@Kondra007 That's great that you made it, but unfortunately I don't have enough knowledge to work with these stuff. But I really appreciate your time and help :) I expected maybe telegram add this and let us converting telegram channels to RSS by adding /feed at the end of the channel links. But thanks anyway man :)

**Comment by thob** [comment]
is it possible to get the RSS from the channel only - for if you don't use a bot?

**Comment by Kondra007** [comment]
@thob There's no such feature in Telegram API (and possibly this won't ever happen, but who knows)

**Comment by lpalgarvio** [comment]
+1

**Comment by Francesco149** [comment]
+1

**Comment by stek29** [comment]
Why is this still open? :)

**Comment by maltsev** [comment]
Still, there is no easy solution, so I created that integration myself: https://notifier.in/integrations/telegram-channel-to-rss You can use it as a service, no need to install anything.

**Comment by amiremami** [comment]
@maltsev 
Hey man, this is great, thanks for this app! I think it has a bug which I emailed you.

**Comment by Nakilon** [comment]
RSS by default always was free to read anonymously. The purpose of Telegram channels is to deanonymise readers. Using signed requests to third-party service that you use to read multiple channels from one account is giving much more data to dataminers. And @maltsev wants you to even pay for that.

**Comment by hillerliao** [comment]
rsshub supports it. https://docs.rsshub.app/en/#telegram

**Comment by squromiv** [comment]
If somebody has some skills in programming, it`s will not require much time. The easiest way - to unite ready solutions: pyrogram (https://github.com/pyrogram/pyrogram) and feedgen (https://github.com/lkiesow/python-feedgen). 

One person I turned to, created created a small program on Python language in about 10 minutes, basing on these two instruments. Basically, It is able to generate RSS from telegram channel without "adding bots". But he said, that he will not finalize that for free.

So, if someone wants to do a good deed, I can share existing code.

**Comment by r78spb** [comment]
https://twitter.com/spb_nord удалось невозможное
сделать rss из канала telegram 

технология
ссылка канала типа https://t.me/severnygorod 
преобразуется в https://t.me/s/severnygorod 
ссылка скармливается например feed43.com
и вот результат https://feed43.com/2115614740420341.xml

**Comment by Nakilon** [comment]
@r78spb did you have to authorize in feed43 (make an account there) to get the final link?

**Comment by r78spb** [comment]
в телеграм канале редко больше 20 записей новых появляется за 6 часов,
ну и конечно если без регистрации создаешь rss бесплатно, то внизу подпись "delivered by feed43.."
но как рабочий инструмент годится в личное пользование

**Comment by r78spb** [comment]
нет, авторизоваться не надо22.05.2019, 16:00, "Victor Maslov" <notifications@github.com>:@r78spb did you have to authorize in feed43 (make an account there) to get the final link?

**Comment by dimqua** [comment]
Можно задействовать [RSS-Bridge](https://github.com/RSS-Bridge/rss-bridge), например, чтобы парсить содержимое, нужно только бридж у нему написать.

**Comment by squromiv** [comment]
@r78spb 
А откуда вы узнали про эти ссылки типа https://t.me**/s/**? Давно такая возможность появилась? Где подробнее можно про это почитать?

**Comment by r78spb** [comment]
несколько дней назад увидел новость о том, что телеграм реализовал режим предпросмотра канала, посмотрел как он работает, увидел, что это можно использовать--------------------20:55, 22 мая 2019 г., squromiv <notifications@github.com>:@r78spb
А откуда вы узнали про эти ссылки типа https://t.me**/s/**? Давно такая возможность появилась? Где подробнее можно про это почитать?

**Comment by squromiv** [comment]
@r78spb 
Можете ссылку на новость дать? На [официальном сайте](https://telegram.org/blog) у них вроде ничего не было.

**Comment by patrickdrd** [comment]
I didn't understand either, what's the link to input in feed43?
after that I know, I'm using feed43 for a while already

**Comment by r78spb** [comment]
https://www.searchengines.ru/telegram-web.html

**Comment by r78spb** [comment]
ссылка канала типа https://t.me/severnygorod
преобразуется в https://t.me/s/severnygorod

т.е. берете ссылку на канал и вставляете s/ перед именем канала
вроде понятно же
![feed43](https://user-images.githubusercontent.com/50915124/58261187-83adc480-7d80-11e9-8594-c63dda745887.jpg)

**Comment by RememberTheAir** [comment]
Interesting conversation

**Comment by patrickdrd** [comment]
it doesn't seem to be working for me,
for example I'm trying with adguard's channel:
https://t.me/s/adguard_en

I input that url in feed43 (and other similar services) but posts aren't shown

**Comment by patrickdrd** [comment]
and this should be the code

`<div class="tgme_widget_message_text js-message_text" dir="auto">{%}<div class="tgme_widget_message_footer compact js-message_footer">`

**Comment by r78spb** [comment]
есть разница между каналом и чатом
AdGuard Chat - это чат, и для https://t.me/adguard_en этот метод не сработает

по поводу кода, у меня такой
<div class="tgme_widget_message_text js-message_text" dir="auto">{%}<{*}href="{%}"{*}<div class="link_preview_description" dir="auto">{%}</div>{*}<a class="tgme_widget_message_date" href="{%}"

**Comment by patrickdrd** [comment]
yeah, I understood the difference, that's why I deleted the message,
also, thanks for the code, yours is much neater :)

**Comment by patrickdrd** [comment]
actually no, your code doesn't work in all, check this one:
https://t.me/s/DroidApks

**Comment by r78spb** [comment]
экспериментируйте
например для droidapks

`<div class="tgme_widget_message_author">{*}<span dir="auto">{%}</span>{*}<div class="tgme_widget_message_text js-message_text" dir="auto">{%}</div>{*}<a class="tgme_widget_message_date" href="{%}">{*}<time datetime="{%}T{%}+00:00">`

https://feed43.com/3661215818631638.xml

**Comment by patrickdrd** [comment]
so each one needs its own?
I thought that there could be a generic pattern

anyway, this one doesn't work properly for me either:
https://t.me/s/lrepacks

**Comment by patrickdrd** [comment]
this for lrepacks:

```
<div class="tgme_widget_message_author">{*}<span dir="auto">{%}</span>{*}
<div class="tgme_widget_message_text js-message_text" dir="auto">{%}</div>{*}
<i class="link_preview_right_image" style="background-image:url('{%})"></i>{*}
<div class="link_preview_title" dir="auto">{%}</div>{*}
<a class="tgme_widget_message_date" href="{%}">{*}<time datetime="{%}T{%}+00:00">
```

**Comment by oldman-x** [comment]
I wrote very simple script for this purpose, any channel should be work.
https://telegram2rss.000webhostapp.com/?c=your_channel_here
For test try:
https://telegram2rss.000webhostapp.com/?c=breakingmash
https://telegram2rss.000webhostapp.com/?c=tvrain

**Comment by Skyross** [comment]
https://node2.feed43.com/profunctor-optics.xml

**Comment by r78spb** [comment]
вот хороший вариант 
https://rsshub.app/telegram/channel/severnygorod

**Comment by squromiv** [comment]
> вот хороший вариант
> https://rsshub.app/telegram/channel/severnygorod
И чем же он хорош? Там вроде админ канала должен должен доступ давать.

**Comment by r78spb** [comment]
не надо доступ
норм работает

**Comment by VillyVonka** [comment]
А для отображения изображений можно что можно придумать?
