### ISSUE TITLE
[Question] Why Desktop hasn't secret chats if Unigram has?

### ISSUE THREAD

**Issue by neelygenet** [telegramdesktop/tdesktop#16409]
You always have said that it's not possible to add secret chat feature to the Desktop app because it is technically complicated. But why has Unigram done it without any money with just an open-source community and you don't?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/871

**Comment by john-preston** [comment]
@neelygenet You need to rewrite the app to use TDlib as Unigram did for that. This is technically complicated 🤷

**Comment by john-preston** [comment]
It is perhaps easier to start a new app based on TDlib than to try to rewrite this one. Some attempts are made, like Unigram or Tok (https://invent.kde.org/network/tok), the second one is even based on Qt and could be built on all platforms.
