### ISSUE TITLE
International Keyboard Layout Stops Working After a Bit

### ISSUE THREAD

**Issue by thevinter** [telegramdesktop/tdesktop#16401]
### Steps to reproduce
1. Set us-intl keyboard layout
2. Open telegram-desktop in a new workspace
3. Wait a couple of minutes

### Expected behaviour
I should be able to use international keys as with any other program.

i.e. when I press \` and then e I should get the character "è"

### Actual behaviour
After a bit telegram-desktop stops recognizing the international keys and they become dead keys. 

i.e. Pressing \` does nothing and pressing \` and then e just prints "e"

### Additional information
This happens about 5 minutes after leaving telegram open. When the issue appears switching to a different workspace on i3 and coming back fixes the problem for a short period of time. I noticed that this issue appears only with telegram so it's not an i3 issue.

### Configuration
**Operating system:** Arch Linux / Kernel: Linux 5.12.8-arch1-1

**Version of Telegram Desktop:** Version 2.7.4

**Installation source (Linux Only)** - pacman 

**Used theme**: N.A.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#1041
