### ISSUE TITLE
Reduce number of desktop notifications

### ISSUE THREAD

**Issue by crandrade** [telegramdesktop/tdesktop#1641]
Please, reduce them to 1 notification, or let us choose the number. There's sometimes when 3 notifications constantly appearing is utterly annoying, but disabling them at all is not the solution.

Thanks in advance.

**Comment by hobarrera** [comment]
On what OS are you having this problem?

**Comment by theus** [comment]
I like this. When I wake my notebook from sleep, all notifications appears
at same time.

**Comment by DaFri-Nochiterov** [comment]
+1
> Smart Notifications allows you configure how you will get notifications. You can change notifications rate, disable sound for some your chats....... 

 Or something like this

**Comment by emadgh** [comment]
I always have just one problem with tg desktop, when I woke my system up, i get lot's of new messages, windows get lot's of notifications... and Telegram act like this

ding,d d d d d d ding,ding...  not responding...d d d d d d ding not ...telegram not responding...
and sometimes it Crash.

**Comment by hobarrera** [comment]
Some of these issues would be fixed by fixing #91 (unless they also occur with other OS's implementations).

**Comment by Aokromes** [comment]
#429 ?

**Comment by auchri** [comment]
It's possible to reduce the number for non-native notifications.
