### ISSUE TITLE
telegram desktop on gentoo no audio output

### ISSUE THREAD

**Issue by darkicekeel** [telegramdesktop/tdesktop#16411]
No audio output on video, voice messages and internal multimedia files. 
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
audio should just play

### Actual behaviour
audio muted but pavucontrol shows some signals during play

### Configuration
 gentoo + pipewire + pulseudio (pulseaudio flag enabled on telegran-desktop package)

**Version of Telegram Desktop:**
2.7.4-r1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
net-im/telegram-desktop on portage
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
can you try downloading from desktop.telegram.org ?

**Comment by ilya-fedin** [comment]
> net-im/telegram-desktop on portage

If you're using downstream package, please use downstream bugtracker.

**Comment by darkicekeel** [comment]
i'm using the in-tree package since the official bin package from telegram website had the same issue

**Comment by darkicekeel** [comment]
someone from gentoo channels suggested to try the portage version but it's the same

**Comment by Aokromes** [comment]
try 2.7.5 beta.

**Comment by darkicekeel** [comment]
ok, hopefully it's already on portage. i'll update here.
if i can provide some logs, just tell me how

**Comment by darkicekeel** [comment]
still not in upstream. can you provide that beta's link?

**Comment by Aokromes** [comment]
> still not in upstream. can you provide that beta's link?

it's on desktop.telegram.org on beta link on bottom.

**Comment by ilya-fedin** [comment]
> official bin package from telegram website had the same issue

Provide log.txt from official website version

**Comment by darkicekeel** [comment]
ok i've done as you said, no effect
where does the official package save that log.txt? is there a way to show it from telegram itself?

**Comment by ilya-fedin** [comment]
> where does the official package save that log.txt?

~/.local/share/TelegramDesktop/log.txt

**Comment by darkicekeel** [comment]
ok i did it
http://dpaste.com//B89YHM7YD
tell me if i can do something more to provide more infos and debug/fix this issue

**Comment by ilya-fedin** [comment]
According to the log, openal sees and uses `UMC404HD 192k Analog Surround 4.0`...
Run tdesktop with `ALSOFT_LOGLEVEL=3`

**Comment by darkicekeel** [comment]
[ALSOFT] (II) Initializing library v1.21.0-116f166 fix_pulse_default
[ALSOFT] (II) Supported backends: pulse, alsa, oss, null, wave
[ALSOFT] (II) Loading config /etc/openal/alsoft.conf...
[ALSOFT] (II) Loading config /etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /home/geminilake/.alsoftrc...
[ALSOFT] (II) Loading config /home/geminilake/.config/alsoft.conf...
[ALSOFT] (II) Got binary: /home/geminilake/Download/Telegram, Telegram
[ALSOFT] (II) Loading config /home/geminilake/Download/Telegram/alsoft.conf...
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Detected max CPUID function: 0x18 (ext. 0x80000008)
[ALSOFT] (II) Vendor ID: ""
[ALSOFT] (II) Name: "Intel(R) Celeron(R) J4105 CPU @ 1.50GHz"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (II) Key drivers not found
[ALSOFT] (II) Key pulse/spawn-server not found
[ALSOFT] (EE) Failed to set real-time priority for thread: Operazione non permessa (1)
[ALSOFT] (II) Initialized backend "pulse"
[ALSOFT] (II) Added "pulse" for playback
[ALSOFT] (II) Added "pulse" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (II) Got device "UMC404HD 192k Analog Surround 4.0", "alsa_output.usb-BEHRINGER_UMC404HD_192k-00.analog-surround-40"
[ALSOFT] (II) Got device "UMC404HD 192k Multichannel", "alsa_input.usb-BEHRINGER_UMC404HD_192k-00.multichannel-input"
[ALSOFT] (II) Got device "Monitor of UMC404HD 192k Analog Surround 4.0", "alsa_output.usb-BEHRINGER_UMC404HD_192k-00.analog-surround-40.monitor"
error: : cannot open
error: : cannot open
error: : cannot open

**Comment by darkicekeel** [comment]
[ALSOFT] (II) Initializing library v1.21.0-116f166 fix_pulse_default
[ALSOFT] (II) Supported backends: pulse, alsa, oss, null, wave
[ALSOFT] (II) Loading config /etc/openal/alsoft.conf...
[ALSOFT] (II) Loading config /etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /home/username/.alsoftrc...
[ALSOFT] (II) Loading config /home/username/.config/alsoft.conf...
[ALSOFT] (II) Got binary: /home/username/Download/Telegram, Telegram
[ALSOFT] (II) Loading config /home/username/Download/Telegram/alsoft.conf...
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Detected max CPUID function: 0x18 (ext. 0x80000008)
[ALSOFT] (II) Vendor ID: ""
[ALSOFT] (II) Name: "Intel(R) Celeron(R) J4105 CPU @ 1.50GHz"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (II) Key drivers not found
[ALSOFT] (II) Key pulse/spawn-server not found
[ALSOFT] (EE) Failed to set real-time priority for thread: Operazione non permessa (1)
[ALSOFT] (II) Initialized backend "pulse"
[ALSOFT] (II) Added "pulse" for playback
[ALSOFT] (II) Added "pulse" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (II) Got device "UMC404HD 192k Analog Surround 4.0", "alsa_output.usb-BEHRINGER_UMC404HD_192k-00.analog-surround-40"
[ALSOFT] (II) Got device "UMC404HD 192k Multichannel", "alsa_input.usb-BEHRINGER_UMC404HD_192k-00.multichannel-input"
[ALSOFT] (II) Got device "Monitor of UMC404HD 192k Analog Surround 4.0", "alsa_output.usb-BEHRINGER_UMC404HD_192k-00.analog-surround-40.monitor"
error: : cannot open
error: : cannot open
error: : cannot open

**Comment by darkicekeel** [comment]
i wanna point that everything was fine before trying pipewire. hopefully this will fix things over situations like mine, since documentation is still poor

**Comment by ilya-fedin** [comment]
The log looks ok, have you tried to play something before copying it? It can return errors on playback.

> i wanna point that everything was fine before trying pipewire.

I use pipewire as pulseaudio replace from 0.3.18, currently I have 0.3.27 and tdesktop works without any issues on my machine.

**Comment by darkicekeel** [comment]
if i try pipewire-pulse ./Telegram this is what i see
`[W][000045417.522518][pulse-server.c:5796 pw_protocol_pulse_new()] pulse-server 0x5575472e6b70: can't create server for unix:native: Device or resource busy
[E][000045417.523764][dbus-name.c:59 dbus_request_name()] D-Bus name org.pulseaudio.Server already taken.`

**Comment by ilya-fedin** [comment]
pipewire-pulse is a server, it should be started by systemd, then all the applications will connect to its socket. Of course, you should make sure that pulseaudio is not installed or that both its autospawn and systemd service are disabled at least.

**Comment by ilya-fedin** [comment]
`ps aux | grep -e pipewire -e pulseaudio` should show all the three services: `pipewire`, `pipewire-pulse`, `pipewire-media-session` started as you user and shouldn't show `pulseaudio`

**Comment by darkicekeel** [comment]
> pipewire-pulse is a server, it should be started by systemd-user, then all the applications will connect to its socket. Of course, you should make sure that pulseaudio is not installed or that both its autospawn feature and systemd-user service are disabled at least.

i'll try to modify the autospawn on /etc/pulse/client.conf

that command you suggested shows as follow:
`````$ ps aux|grep -e pipewire -e pulseaudio
username  2244  3.0  2.4 317216 188976 tty1    S<l  06:24  23:47 pipewire
username  2288  0.0  0.2 173036 22284 tty1     S<l  06:24   0:02 /usr/bin/pipewire-media-session
username  2289 11.4  9.2 1045604 718444 tty1   S<Ll 06:24  88:42 /usr/bin/pipewire -c pipewire-pulse.conf
username 24191  0.0  0.0   7932   728 pts/1    R+   19:16   0:00 grep --colour=auto -e pipewire -e pulseaudio`
`````
i've edited and ready to restart my DE, since in .xinitrc i already did as the gentoo wiki 

`````$ cat .xinitrc 
pipewire & 
exec dbus-launch --exit-with-session xfce4-session`

**Comment by ilya-fedin** [comment]
What version of pipewire are you using? It had a lot of changes regarding audio stuff, e.g. initially it had libpulse replacement, then it had internal pulse-server, then standalone pipewire-pulse daemon appeared. It also had changes regarding pipewire-media-session: initially it was meant to be autolaunched by pipewire, then it became a standalone service.

**Comment by darkicekeel** [comment]
PipeWire 0.3.22

**Comment by ilya-fedin** [comment]
It feels like you have configuration from old pipewire version

**Comment by ilya-fedin** [comment]
btw, are you sure that audio works in other applications that work via pulse?

**Comment by darkicekeel** [comment]
yes, right now i've got mpv, firefox-bin, moc that are working as always.
the only thing that wasn't working as before, beside telegram, is the input selector in pavucontrol, the one that makes possible to switch between speaker's monitor or the actual physical inputs of my usb sound card.
anyway, i followed the indications in gentoo wiki on pipewire

**Comment by ilya-fedin** [comment]
> yes, right now i've got mpv, firefox-bin, moc that are working as always.

are you sure they use pulseaudio?

**Comment by ilya-fedin** [comment]
Anyway, if you say tdesktop was working before you switched to pipewire, it is not an issue with tdesktop since it never claimed it's compatible with pipewire.

@Aokromes can you close the issue?

**Comment by darkicekeel** [comment]
yeah but if you have already tested that pipewire isn't a problem at all, then it's just a matter of proper coordination with the package mantainers. i'm asking support since i'm just a user, not a dev.

**Comment by darkicekeel** [comment]
> > yes, right now i've got mpv, firefox-bin, moc that are working as always.
> 
> are you sure they use pulseaudio?

gentoo's useflags are there and enabled for those programs. telegram on portage has that flag too, that's why someone suggested to use that version, but it's the same. anyway, i hope this will help for next updates

**Comment by ilya-fedin** [comment]
> then it's just a matter of proper coordination with the package mantainers

Since you say pavucontrol shows the signal, it feels like some bug in pipewire

**Comment by ilya-fedin** [comment]
> telegram on portage has that flag too

tdesktop doesn't use pulseaudio directly, it uses openal for audio playback

**Comment by darkicekeel** [comment]
i'll take your precious hints and try to figure out.
