### ISSUE TITLE
[Question] OSX Client had Secret Chat, now it doesn't. Why?

### ISSUE THREAD

**Issue by thanpolas** [telegramdesktop/tdesktop#16412]
Hello,

It used to be the case that the osx/macos telegram client was able to initiate secret chats.

It has been long time now that this is no longer possible.

Why? And are there plans to have secret chat again on osx / macos desktop client?

Please don't lock and reference [#871](https://github.com/telegramdesktop/tdesktop/issues/871). This is an issue from 2015, from when there was no secret chat at all and the last post made there is from 2016. Today we have 2021.

**Comment by john-preston** [comment]
@thanpolas there are two apps for macOS, Telegram Desktop (this repository), which never had secret chats on any platform, and Telegram for macOS (native app), which had them and has them now. You can download the native app from https://macos.telegram.org

**Comment by thanpolas** [comment]
Thank you and apologies. 

Created a new issue on the repository that was directed at: https://github.com/overtake/TelegramSwift/issues/637
