### ISSUE TITLE
Telegram Linux set as Use System proxy settings doesn't work

### ISSUE THREAD

**Issue by zyf0330** [telegramdesktop/tdesktop#16418]
### Steps to reproduce
1. set Ubuntu system proxy in which http proxy and socks5 proxy are both set separatelly
2. set Use system proxy settings for telegram Linux desktop

### Expected behaviour
Telegram should use system proxy.
### Actual behaviour
Telegram keeps Connecting
### Configuration
**Operating system:**
Ubuntu with KDE 21.04
**Version of Telegram Desktop:**
2.7.4
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
GitHub releases
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
What do you mean by 'Ubuntu system proxy'? Can you provide screenshots?

**Comment by zyf0330** [comment]
@ilya-fedin Here it is! I use Ubuntu with KDE.
![image](https://user-images.githubusercontent.com/11958657/120985505-42917d00-c7ae-11eb-90e3-503b450ac03b.png)

**Comment by ilya-fedin** [comment]
"Use manually specified proxy configuration' affects only applications that use KDE frameworks, you should choose 'Use system proxy configuration'

**Comment by zyf0330** [comment]
Oh, maybe it is, I don't actually know. But this is proxy settings panel in
system settings, then how to set system proxy settings?

**Comment by ilya-fedin** [comment]
> you should choose 'Use system proxy configuration'

**Comment by zyf0330** [comment]
Sorry, I misunderstood that option.
