### ISSUE TITLE
Support clearing "mentions" indicator inside chats

### ISSUE THREAD

**Issue by nickaein** [telegramdesktop/tdesktop#16416]
### Is your feature request related to a problem?

Currently, the icon representing "unread mentions" inside a chat (shown below) can only be hidden after reading all mentions. 

![image](https://user-images.githubusercontent.com/8047027/120940834-6a43ff00-c734-11eb-95dc-102311a48f65.png)

However, there are two cases that this will not work:

~~1. The icon cannot be hidden for voice messages just by "seening" them. One has to play voice messages to mark them as seen, which is not always convenient.~~

2. Sometimes the icon is shown incorrectly, even when all mentions are already seen. This bug usually happens when someone replies to a message and his/her message immediately gets deleted by a bot.

### Describe the solution you'd like

The solution on Android app is that one can tap and hold on this icon for a second or two to get rid of it. The same thing (or right-clicking on the icon and clicking on a "Mark all as read" option) can be useful on Telegram Desktop.

### Describe alternatives you've considered

There is no way to get rid of this icon on Desktop for these two cases I mentioned above. The workaround is use the Android app to get rid of icon.

**Update:** The first case is already covered by double-clicking on the icon as mentioned by ilya-fedin.

**Comment by ilya-fedin** [comment]
double-click it

**Comment by nickaein** [comment]
@ilya-fedin 

It doesn't disappear with double-click. 

BTW, I'm on latest (2.7.5) beta version on Ubuntu.

**Comment by ilya-fedin** [comment]
> It doesn't disappear with double-click.

Just checked and it does

**Comment by nickaein** [comment]
@ilya-fedin 

Sorry for not checking this more precisely. Yes, it does resolve the first case (unread voice messages). However, it doesn't work for the second case ("phantom" unread messages). I cannot mark them as read and the icon doesn't disappear with double-click.

One can argue that in these cases, the app shouldn't show the unread icon in the first place, since well, there is no unread messages. However, I don't think this is a bug in client app itself, since I observe the same "unread" count both on Desktop and Android app in the same chat group. It is probably a counter sent by server, incorrectly.

Nevertheless, it would be nice if I can get rid of this icon in this case too, as I can do it on Android app. I don't know how Android client does that (since there is no actual unread message to be marked as read). Maybe there is a `mark-all-as-read` flag that they send to server?
