### ISSUE TITLE
Going offline every time

### ISSUE THREAD

**Issue by IncognitoSecret00038** [telegramdesktop/tdesktop#16413]
I'm new to Telegram, and I have come across a weird bug in Telegram Desktop. When I switch to a different app without minimizing Telegram, it indicates me as **Offline**. It's a really annoying freaking bug! Please fix this freaking bug because it indicates that I'm offline even when I hit the start key.

**Comment by RememberTheAir** [comment]
If the app's window is out of focus, the app doesn't signal the server that you are online anymore. As in, you don't have the app open in front of you. This is the intended behavior
