### ISSUE TITLE
macOS client doesn't recognize any audio device other than default in voice chats

### ISSUE THREAD

**Issue by aisuneko** [telegramdesktop/tdesktop#16419]
### Steps to reproduce
1. Start a voice chat and go to Microphone/Speaker settings

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead
**no audio devices (besides Default and CoreAudio default) are displayed here, including the companion virtual audio devices for Loopback & Background Music.**
<img width="335" alt="屏幕快照 2021-06-07 22 42 44" src="https://user-images.githubusercontent.com/22784008/121037009-b13bfe00-c7e1-11eb-9d62-0b3a95f788ed.png">
("Output device" displays the same thing)
### Configuration
**Operating system:**
macOS 10.14.6
**Version of Telegram Desktop:**
2.7.5 beta
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#16360
