### ISSUE TITLE
[Feature Request] Downloads have subdirectories for each chat.

### ISSUE THREAD

**Issue by frenchiveruti** [telegramdesktop/tdesktop#16417]
### Is your feature request related to a problem?
Similar to #1359 but instead use chat-names to create folders.

### Describe the solution you'd like
I would like to have a toggleable option to separate my downloads into different folders depending on the chat I'm getting the file from.  
I have many college groups that I have files, documents, photos, notes, and it's all a mess because it's mixed with my other downloads or groups, I don't even open the downloads folder because it's a mess.  
If I had an option where I can just have sub-folders inside telegram downloads, with the name of the group I got the download from, I can have a better organization of my files, and also make more use of them.

### Additional context
Say I have Mindy, Group A, John and Group B  
The final scheme would be:
Telegram Downloads
 --> Mindy
    --o Files in mindy's chat
 --> Group A
 --> Group B
 --> John

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5788
