### ISSUE TITLE
No Access to Pinned Items on Linux Desktop Client

### ISSUE THREAD

**Issue by brianjmartin86** [telegramdesktop/tdesktop#16426]
### Steps to reproduce
1. Log into Telegram destop on Linux
2. Try to locate pinned messages in a chat/channel
3. On the most recent Pinned message bar at the top of the chat, there is no thumbtack/Menu icon to click to access pinned messates

### Expected behaviour
Icon expected to be present to access pinned messages, as present on WIN/MAC/Mobile client

### Actual behaviour
No Icon, or other method of pulling up pinned messages

### Configuration
**Operating system:**
Ubuntu 20.10
**Version of Telegram Desktop:**
2.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
> 2.2

Current latest version is 2.7.4, you can't report for old version

**Comment by john-preston** [comment]
This feature is available in the latest version. You can try it from https://desktop.telegram.org
