### ISSUE TITLE
(Only Flatpak) Badge Counter shown even though it is turned off

### ISSUE THREAD

**Issue by Vite** [telegramdesktop/tdesktop#16424]
Ubuntu 18.04
Telegram 2.7.4 (Flatpak https://flathub.org/apps/details/org.telegram.desktop)
Snap package not tested

How to reproduce:
Download Telegram as Flatpak
Sign in
Disable 2 Badge Counter options in settings

**Not reproduceable with standard Telegram package (tar.xz https://telegram.org/dl/desktop/linux)**
It is working fine with that one.

Expected behaviour:
Do not show any badge counter in the dock/taskbar.

Actual behaviour:
There is a badge counter counting unread messages but only from unmuted chats.
![image](https://user-images.githubusercontent.com/25325543/121230681-d424eb80-c88f-11eb-84cb-3afc48e181c3.png)

Settings:
![image](https://user-images.githubusercontent.com/25325543/121230525-a3dd4d00-c88f-11eb-9c0d-d40a27e13724.png)

**Comment by ilya-fedin** [comment]
Maybe it is bug of your panel?

**Comment by ilya-fedin** [comment]
Also, "count unread messages" doesn't enable/disable the counter, it switches between chats count and messages count
