### ISSUE TITLE
10 seconds after opening telegram desktop it gets frozen 

### ISSUE THREAD

**Issue by DaveRoRa** [telegramdesktop/tdesktop#16427]
### Steps to reproduce
1. Open Telegram Desktop

### Expected behaviour
Not get frozen

### Actual behaviour
It gets frozen after 10 seconds

### Configuration
**Operating system: Microsoft Windows V1909 (SO compilation 18363.418)

**Version of Telegram Desktop: 2.7.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Get a dump from task manager after it's frozen and send it to @john-preston via Telegram (`@preston` there)
