### ISSUE TITLE
Mark As Unread

### ISSUE THREAD

**Issue by ericbaobao** [telegramdesktop/tdesktop#16425]
I don't use Telegram mobile since I enjoy the desktop app so much.
Is it possible if you guys can add Mark As Unread for Windows desktop version?
Maybe the setting file can save to current directory or something else.
Because when I just join a group, I want to read from the first message, when I'm not done I wish to resume on the next day.
Anyway I love the desktop App so much, look beautiful, smooth, bunch of functions.

With addition of this feature will be even more awesome.

**Comment by john-preston** [comment]
Thanks!

Unfortunately, there is no API to really mark as unread starting from some time. There is "mark as unread" for a chat, but it just marks the chat, it receives a blue badge without a number - just a reminder that you wanted to do something with that chat later (read something, answer something).

**Comment by ericbaobao** [comment]
> Thanks!
> 
> Unfortunately, there is no API to really mark as unread starting from some time. There is "mark as unread" for a chat, but it just marks the chat, it receives a blue badge without a number - just a reminder that you wanted to do something with that chat later (read something, answer something).

I mean not using telegram api, it is like internal unique feature of desktop telegram will have @john-preston

**Comment by Aokromes** [comment]
> > Thanks!
> > Unfortunately, there is no API to really mark as unread starting from some time. There is "mark as unread" for a chat, but it just marks the chat, it receives a blue badge without a number - just a reminder that you wanted to do something with that chat later (read something, answer something).
> 
> I mean not using telegram api, it is like internal unique feature of desktop telegram will have @john-preston
> I'm not sure if it's same as html with index jump to a chat position, if it is like html then when user long press the message select "mark as unread", then that function will
> 
> 1. save the group chat id with the index to an .ini for example.
> 2. So when the group is open if the .ini got a record, and the telegram desktop will jump to that index instead of telegram unread index. The index is then updated when scroll through another new date index.
> 3. when the .ini index is same as the api index then it can be removed. So the next time when reopen the group chat it jump pack using the server unread index

such features needs server support.

**Comment by ericbaobao** [comment]
> > > Thanks!
> > > Unfortunately, there is no API to really mark as unread starting from some time. There is "mark as unread" for a chat, but it just marks the chat, it receives a blue badge without a number - just a reminder that you wanted to do something with that chat later (read something, answer something).
> > 
> > 
> > I mean not using telegram api, it is like internal unique feature of desktop telegram will have @john-preston
> > I'm not sure if it's same as html with index jump to a chat position, if it is like html then when user long press the message select "mark as unread", then that function will
> > 
> > 1. save the group chat id with the index to an .ini for example.
> > 2. So when the group is open if the .ini got a record, and the telegram desktop will jump to that index instead of telegram unread index. The index is then updated when scroll through another new date index.
> > 3. when the .ini index is same as the api index then it can be removed. So the next time when reopen the group chat it jump pack using the server unread index
> 
> such features needs server support.

I don't understand, why? Isn't it can be bypass?
Since if you jump to older date index first, telegram unread index should not change

**Comment by RememberTheAir** [comment]
> I mean not using telegram api, it is like internal unique feature of desktop telegram will have

This is a problem, features and user experience should be consistent across all clients as much as the clients' platform allows it to be. This feature in particular will make people see different numbers from desktop and android/ios. You should suggest it on https://bugs.telegram.org (a similar suggestion was proposed in [this card](https://bugs.telegram.org/c/34))

**Comment by ericbaobao** [comment]
> > I mean not using telegram api, it is like internal unique feature of desktop telegram will have
> 
> This is a problem, features and user experience should be consistent across all clients as much as the clients' platform allows them to be. This feature in particular will make people see different numbers from desktop and android/ios. You should suggest it on https://bugs.telegram.org (a similar suggestion was proposed in [this card](https://bugs.telegram.org/c/34))

I thought the developer of the desktop client is separate entity?
I don't see it's a harm since this is consider as a productive feature.
There have so many suggestion in there I doubt the Telegram official developer would take any action, as you can see in here: https://bugs.telegram.org/?type=suggestions&sort=rate&query=mark%20as%20unread

I give a scenario, this is rather important like you join a classroom group you can't afford to miss the previous message or discussion by your lecturer, so you wanted to read from the beginning but then when you are unable to finish it you would wished to resume it the next day. Imagine there are lot of message, how painful it is to scroll to its middle.

I really wish this feature can be implemented for Windows Desktop Telegram, please please please please 💖

**Comment by Aokromes** [comment]
> > > I mean not using telegram api, it is like internal unique feature of desktop telegram will have
> > 
> > 
> > This is a problem, features and user experience should be consistent across all clients as much as the clients' platform allows them to be. This feature in particular will make people see different numbers from desktop and android/ios. You should suggest it on [bugs.telegram.org](https://bugs.telegram.org) (a similar suggestion was proposed in [this card](https://bugs.telegram.org/c/34))
> 
> I thought the developer of the desktop client is separate entity?
> I don't see it's a harm since this is consider as a productive feature.
> There have so many suggestion in there I doubt the Telegram official developer would take any action, as you can see in here: [bugs.telegram.org/?type=suggestions&sort=rate&query=mark%20as%20unread](https://bugs.telegram.org/?type=suggestions&sort=rate&query=mark%20as%20unread)
> 
> I give a scenario, this is rather important like you join a classroom group you can't afford to miss the previous message or discussion by your lecturer, so you wanted to read from the beginning but then when you are unable to finish it you would wished to resume it the next day. Imagine there are lot of message, how painful it is to scroll to its middle.
> 
> I really wish this feature can be implemented for Windows Desktop Telegram, please please please please 💖

again, such feature must be implemented platform wide, because if you mark something un read on desktop, it will continue to be marked read on other clients.

**Comment by ericbaobao** [comment]
> > > > I mean not using telegram api, it is like internal unique feature of desktop telegram will have
> > > 
> > > 
> > > This is a problem, features and user experience should be consistent across all clients as much as the clients' platform allows them to be. This feature in particular will make people see different numbers from desktop and android/ios. You should suggest it on [bugs.telegram.org](https://bugs.telegram.org) (a similar suggestion was proposed in [this card](https://bugs.telegram.org/c/34))
> > 
> > 
> > I thought the developer of the desktop client is separate entity?
> > I don't see it's a harm since this is consider as a productive feature.
> > There have so many suggestion in there I doubt the Telegram official developer would take any action, as you can see in here: [bugs.telegram.org/?type=suggestions&sort=rate&query=mark%20as%20unread](https://bugs.telegram.org/?type=suggestions&sort=rate&query=mark%20as%20unread)
> > I give a scenario, this is rather important like you join a classroom group you can't afford to miss the previous message or discussion by your lecturer, so you wanted to read from the beginning but then when you are unable to finish it you would wished to resume it the next day. Imagine there are lot of message, how painful it is to scroll to its middle.
> > I really wish this feature can be implemented for Windows Desktop Telegram, please please please please 💖
> 
> again, such feature must be implemented platform wide, because if you mark something un read on desktop, it will continue to be marked read on other clients.

it is ok, I only use Telegram Desktop

**Comment by reallyuniquename** [comment]
> it is ok, I only use Telegram Desktop

And others don't. Telegram Desktop userbase is miniscule compared to mobile users.

**Comment by ericbaobao** [comment]
> > it is ok, I only use Telegram Desktop
> 
> And others don't. Telegram Desktop userbase is miniscule compared to mobile users.

more people will switch to desktop version if they know the desktop got this feature.
What do it matter? It don't affect the functionality even switch to mobile or other platform.

read carefully "when the unread index (in .ini) same as the api unread index then the unread index (in .ini) is remove. Like this will not have clash"

**Comment by reallyuniquename** [comment]
"Read carefully" this

>such feature must be implemented platform wide
