### ISSUE TITLE
[wayland] Repeated characters with accents.

### ISSUE THREAD

**Issue by juxuanu** [telegramdesktop/tdesktop#16422]
### Steps to reproduce
1. Start Telegram with the following env vars (the ones I use for all my Qt apps): `QT_QPA_PLATFORM=wayland XCURSOR_SIZE=24 QT_STYLE_OVERRIDE=kvantum QT_QPA_PLATFORMTHEME=gnome`
3. Switch between windows and/or close to tray and open again Telegram.
2. Try to write something with accents, such as `à` or `é` in any text input field.

### Expected behaviour
Tell us what should happen:
There should be only one character written with the accent.

### Actual behaviour
Tell us what happens instead:
The characters get repeated. The more I switch windows, the more that appear.
![imatge](https://user-images.githubusercontent.com/24759034/121176980-26004e00-c85d-11eb-92b1-1f80cf8d77f7.png)
This is pressing 
```
` a
```
once.

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 2.7.4 Flatpak.

**Used theme**: Doesn't matter, reproducible with any.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#1041

**Comment by juxuanu** [comment]
It's not the same. Mine work, but get repeated.

**Comment by ilya-fedin** [comment]
How can I reproduce that? My language doesn't have accents and I'm on X11, so I need a detailed step-by-step guide

**Comment by juxuanu** [comment]
What you need to reproduce this bug is:
- A Wayland session (and make sure the app is running under Wayland)
- The ability to type any character such as à è é í ò ó ú

Sometimes I can reproduce it when I open the app, sometimes after a bit of time. I can't seem to find the event that triggers this bug, but what I know is that it's incremental: every time it triggers, more characters are added on type.

For example, right now I have started the app and the first thing I do is go into a chat (or the search bar does the job aswell) and type à, which triggers the bug. Then, I quit the app and open it again, but this time I can't seem to trigger this. After a while, I can see it happening again.

**Comment by ilya-fedin** [comment]
>     * The ability to type any character such as à è é í ò ó ú

I have no idea how to type them, my language doesn't have accents as I already said, I assume your steps to reproduce are incorrect until you provide all the details.

**Comment by juxuanu** [comment]
I can't guess what you have. Provide your keyboard layout, for example, and I might be able to help you.

**Comment by ilya-fedin** [comment]
> Provide your keyboard layout, for example, and I might be able to help you.

english + russian. What I need from you is a detailed guide on how to estabilish Wayland session and your exact keyboard settings. Or you can provide a VM image (in VIrtualBox format) so that I can just run it and see the bug.

**Comment by juxuanu** [comment]
> a detailed guide on how to estabilish your Wayland session

*My* Wayland session is basically Gnome Shell 40.1.

In order to establish the same Wayland session as I have you'll need to:
Install Gnome Shell. How to install it depends on your distribution. Once you have it installed, you'll have to log in (preferably through a display manager such as GDM) with the option "Gnome" selected (not "Gnome on X.Org" nor "Gnome Classic"). Then, you will need to install Flatpak. How to install it depends on your distribution. Then, install Telegram from Flatpak (`flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo` and `flatpak install flathub org.telegram.desktop`).
Once you have both pieces of software, you start Telegram by pressing Super and finding it in the app drawer. Log into your Telegram account. Let's now make sure that you are under a Wayland session: `echo $XDG_SESSION_TYPE` should return "wayland". If not, log out and select the correct session as instructed before.
Finally, to get my keyboard layout, you need to be set it in the Gnome Preferences: go to the top right corner, Settings > Keyboard and add Spanish (Catalan variation). Set it as the only one by removing the previous one.

Now, we can finally reproduce the bug! Start typing on any text input field on the Telegram app characters such as `í`, which you can do by pressing the key on the physical keyboard that is immediately to the left of the Enter key + any vocal. I am attaching an image at the end of this message to illustrate what I mean (a red key pressed, followed by a yellow key pressed).

If you see the correct character (only one of them), switching between different other apps, switch between different workspaces, etc and keep trying, it eventually (and pretty easily) is reproduced.

In case of interest, this is the keyboard config:
```
╰─🚀 localectl             
   System Locale: LANG=ca_ES.UTF-8
       VC Keymap: es
      X11 Layout: es
       X11 Model: asus_laptop
     X11 Variant: cat
```

![photo_2021-06-08_18-54-25](https://user-images.githubusercontent.com/24759034/121226863-4ba44c00-c88b-11eb-8784-80a5c2d4356a.jpg)

**Comment by ilya-fedin** [comment]
> you can do by pressing the key on the physical keyboard that is immediately to the left of the Enter key

Wow, your photo explains a lot why I wasn't able to figure how to use accents

**Comment by ilya-fedin** [comment]
I'll try to reproduce on my KDE Neon VM + spanish layout

**Comment by ilya-fedin** [comment]
Looks like it works OK for me
https://user-images.githubusercontent.com/17829319/121230046-442a7600-c87e-11eb-9a18-4719c6822765.mp4

Maybe it's some incompatibility between qtwayland and GNOME?

**Comment by ilya-fedin** [comment]
Well, there's no reason to have issues about qtwayland bugs since they can be fixed only by Qt devs
@Aokromes can you close the issue?

**Comment by juxuanu** [comment]
This only happens with Telegram...

**Comment by ilya-fedin** [comment]
@juxuanu tdesktop has nothing special about that, that bug can be only at Qt level. The reason you don't have that with other applications is one of:
1. You don't use other Qt applications
2. Your other Qt applications use other widgets for text input (e.g. message input field uses QTextEdit, while most Qt applications use QLineEdit since they don't need formatting, multi-line input and etc)
3. Your other applications use different Qt version (you're using flatpak version, so no surprise its Qt version can have such a bug while your system Qt doesn't)

I don't believe this can be a bug in Telegram, there's just no any accent handling code, everything is done on Qt side.

**Comment by juxuanu** [comment]
I tried the one provided by Arch and a fork called Kotatogram aswell, both present the same issue.

I guess I should open an issue at Qt then, thanks.

**Comment by ilya-fedin** [comment]
> I guess I should open an issue at Qt then, thanks.

They will close your issue if you won't provide a minimal reproducible example.

**Comment by ilya-fedin** [comment]
Search field uses QLineEdit, btw
