### ISSUE TITLE
Telegram is multiplicated on each Windows 10 Task View desktop when 'Show taskbar icon' is unchecked

### ISSUE THREAD

**Issue by notNSANE** [telegramdesktop/tdesktop#1642]
See the screenshot for example:

![image](https://cloud.githubusercontent.com/assets/7162375/13133042/b2774c50-d5d6-11e5-8a77-81a1ac7124a1.png)

Telegram should be stuck to the one Desktop view we choose. 

The software Discord uses a similar approach as Telegram (I think) and it's correctly stuck to the desktop view I choose.

I'm using Windows 10 64 bits, and Telegram portable, latest version.

**Comment by DaFri-Nochiterov** [comment]
I can't confirm it

![image](https://cloud.githubusercontent.com/assets/10401817/13134030/781d1aea-d634-11e5-918c-81e4b6fb21a1.png)

**Comment by notnsane** [comment]
fantastic! You're using portable version? Win 64? 

Ah, I found that this issue happens with the config in settings: 
![image](https://cloud.githubusercontent.com/assets/7162375/13134179/1d622c5a-d5e2-11e5-98e2-aeca8fd6252f.png)

Can you confirm?

**Comment by DaFri-Nochiterov** [comment]
@notnsane, OK. Issue happens when 'Show taskbar icon' unchecked.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
