### ISSUE TITLE
PIP controls display error

### ISSUE THREAD

**Issue by sashacmc** [telegramdesktop/tdesktop#16430]
### Steps to reproduce
1. Open Media 
2. Switch to PIP mode
3. Move mouse cursor over the window

### Expected behaviour
Controls displaying correctly

### Actual behaviour
![Screenshot from 2021-06-11 17-19-55](https://user-images.githubusercontent.com/28735879/121710429-e72afc00-cad9-11eb-96f5-3568cf56f16c.png)

### Configuration
**Operating system:**
Ubuntu 20.04.2 LTS

**Version of Telegram Desktop:**
2.7.7

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
GitHub releases

**Used theme**:
Default

**Comment by Aokromes** [comment]
on windows 10 i see them like https://i.imgur.com/CcrVx9q.png

**Comment by Aokromes** [comment]
must be fixed on 2.7.8
