### ISSUE TITLE
[Feature Request] Hide unread message badge for muted chats

### ISSUE THREAD

**Issue by rdgh8** [telegramdesktop/tdesktop#16431]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.

N/A

### Describe the solution you'd like

Hide unread message only badge for muted chats

### Describe alternatives you've considered

Turning off badges completely, however this also hides badges from unmuted chats

### Additional context

N/A

**Comment by ilya-fedin** [comment]
Such feature already present
