### ISSUE TITLE
Video calls have no Picture-in-Picture support, unlike the normal video player.

### ISSUE THREAD

**Issue by AmadeusK525** [telegramdesktop/tdesktop#16438]
Hi, this has been bothering me for a while now. The Picture-in-Picture feature of the normal video player works well and stays on top of all other applications. However, the video calls don't have the same behavior and don't even stay on top of Telegram itself! I've tried many different things to make this work because I would assume it's something already implemented but I couldn't figure it out. Apparently this is the behavior on the Linux client, but I'm not sure. Is there a way to work around this without installing a third-party program to do it?

### Expected behaviour
The video call frame should stay on top of Telegram and other applications (or at least given the option to), like the normal video player.

### Actual behaviour
The frame is hidden whenever the user clicks outside of it.

### Configuration
**Operating system:**
Windows
**Version of Telegram Desktop:**
2.7.8 beta x64

**Comment by ilya-fedin** [comment]
#10369
