### ISSUE TITLE
Saved messages are not synced properly

### ISSUE THREAD

**Issue by ngsanthosh** [telegramdesktop/tdesktop#16435]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Many of my messaged saved in saved messages of telegram desktop should be synced with mobile app

### Actual behaviour

Many of my messaged saved in saved messages of telegram desktop are not synced with mobile app

### Configuration
Windows

2.7.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ekharisma** [comment]
Uhh, is this issue still persist? If it dont, please close it.

**Comment by ngsanthosh** [comment]
Yes, the issue still persists. Like if I pin some of the messages in the telegram mobile app and when I come to the telegram desktop and click pinned messages. It highlights the wrong message instead highlighting the exact pinned message.
