### ISSUE TITLE
changing status of a status does not change its membership a folder

### ISSUE THREAD

**Issue by nobswolf** [telegramdesktop/tdesktop#16448]
### Steps to reproduce
1. create folder with entries "not in contacts"
2. choose one of the found chats
3. add this chat to contacts

### Expected behaviour
The chat should disappear from the folder.

### Actual behaviour
It does not disappear.

As a workaround, a restart helps

### Configuration
**Operating system:** Debian 10 Linux, XFCE 

**Version of Telegram Desktop:** 2.7.4

**Installation source (Linux Only)** - the official website (incl. automatic updates)

**Used theme**: day

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by nobswolf** [comment]
Sorry, no, it is definitly the official Desktop version for Linux ;-)

**Comment by nobswolf** [comment]
![image](https://user-images.githubusercontent.com/6206276/122521576-48405b80-d015-11eb-8a44-a69d06b1fd3d.png)

**Comment by Aokromes** [comment]
the , on 2 , 7 . 4 made the bot to think you are using 7 . 4 version.

**Comment by john-preston** [comment]
Yeah, I think that's because of first comma instead of a dot.

Thanks for your report.

**Comment by nobswolf** [comment]
> Sorry, but according to the version you specify in this issue, you are using the [Telegram for macOS](https://macos.telegram.org), not the [Telegram Desktop](https://desktop.telegram.org).
> You can report your issue to [the group](https://t.me/macswift) or to [the repository of Telegram for macOS](https://github.com/overtake/TelegramSwift).
> 
> **If I made a mistake and closed your issue wrongly, please reopen it. Thanks!**



> the , on 2 , 7 . 4 made the bot to think you are using 7 . 4 version.

oops, sorry... I shouldn't type such data ... it is corrected now
