### ISSUE TITLE
Unable to copy and paste image from telegram desktop to GIMP

### ISSUE THREAD

**Issue by aerdnar** [telegramdesktop/tdesktop#16444]
### Steps to reproduce
1. Open an image
2. Right click on the image -> copy
3. Paste it on GIMP

### Expected behaviour
Image should be pasted in GIMP

### Actual behaviour
Error: There is no image data in the clipboard to paste

### Configuration
Windows 10 x64

Telegram desktop 2.7.4 portable

![immagine](https://user-images.githubusercontent.com/26771443/122258918-e3301d00-ced1-11eb-8170-54d876cc9e3e.png)

**Comment by Aokromes** [comment]
cannot reproduce with telegram desktop 2.7.4 non-portable and gimp 2.10.24

**Comment by ilya-fedin** [comment]
> Error: There is no image data in the clipboard to paste

This is not reproducible with any image data, probably you have some specific image, please provide it.

**Comment by aerdnar** [comment]
Thanks! 
It was a bug of GIMP from 2.10.14 to 2.10.22
It is not reproducible on gimp 2.10.24

Bug link: https://gitlab.gnome.org/GNOME/gimp/-/issues/4802
