### ISSUE TITLE
Multiple monitor issues (win10) & 2x audio playback request

### ISSUE THREAD

**Issue by LtPatterson** [telegramdesktop/tdesktop#16440]
1. Please allow for 2x audio playback on telegram desktop as is already the case on Android/iOS.

2. When dragging the telegram desktop app to a second monitor in Windows 10, the playback window for media does not scale correctly or appear properly. It is limited to the upper quadrant of the monitor and cannot be viewed correctly. See screenshot below. The app is not scaling media correctly.

![image](https://user-images.githubusercontent.com/31023291/122089004-53587900-cdd4-11eb-8780-f7958b6a041d.png)

**Comment by john-preston** [comment]
@LtPatterson What is the version where you see the second issue?

**Comment by LtPatterson** [comment]
This is present in 2.7.8 beta and was present in the stable build prior to
moving to beta, only worse with screen flickering. This only occurs with
Telegram no other apps I have installed have this issue.

**Comment by Aokromes** [comment]
1st: https://github.com/telegramdesktop/tdesktop/issues/16138
2nd: https://github.com/telegramdesktop/tdesktop/issues/1121
