### ISSUE TITLE
URL with query and without ending / is truncated

### ISSUE THREAD

**Issue by ornic** [telegramdesktop/tdesktop#1644]
http://goggle.com?q=123 - truncated
http://goggle.com/?q=123 - OK

![image](https://cloud.githubusercontent.com/assets/3350070/13139023/6fcfaa04-d63b-11e5-8ab8-ad3dcbf6bd9b.png)

P.S. Windows

P.P.S. The same goes for Android client, so may be this is some library problem.

**Comment by stek29** [comment]
IMO first one should be truncated, it's very confusing and looks wrong for me

**Comment by DaFri-Nochiterov** [comment]
@stek29  But, this link absolutely normal. Any browser should insert `/` symbol before `?`. As we can see github parses this link, Telegram should do same.

**Comment by auchri** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/5092164/17451274/da76f452-5b65-11e6-92d6-30fee601910f.png)
