### ISSUE TITLE
Application does not start

### ISSUE THREAD

**Issue by estheticode** [telegramdesktop/tdesktop#16441]
### Expected behaviour

Application should start! 

### Actual behaviour

Application does not start without trying 3-4 times!

### Configuration
Windows 10

**Version of Telegram Desktop: 2.7.4**

**Used theme**:
Turquoise cloud

![image](https://user-images.githubusercontent.com/59923296/122164915-12746900-ce95-11eb-8fcb-1699f25b2a14.png)

**Comment by ilya-fedin** [comment]
Make sure Telegram process is not already running

**Comment by estheticode** [comment]
No Telegram process is running. When I power on the system and try to open the application, it does not start directly.

**Comment by ilya-fedin** [comment]
Provide log_start*.txt

**Comment by estheticode** [comment]
[log_start0.txt](https://github.com/telegramdesktop/tdesktop/files/6668619/log_start0.txt)

**Comment by ilya-fedin** [comment]
It says Telegram process is already running

**Comment by Aokromes** [comment]
> No Telegram process is running. When I power on the system and try to open the application, it does not start directly.

check into background process, sometimes when icon fails to be created it's stuck there.

**Comment by ilya-fedin** [comment]
Or he sent some old log. It is better to send all the log*.txt files in the directory.

**Comment by estheticode** [comment]
> Or he sent some old log. It is better to send all the log*.txt files in the directory.

All the log_start*.txt files say that the process is running.

**Comment by estheticode** [comment]
> > No Telegram process is running. When I power on the system and try to open the application, it does not start directly.
> 
> check into background process, sometimes when icon fails to be created it's stuck there.

This seems to be the reason for the issue. The problem is with start menu of windows since I run the application from the icon in start menu. The application runs fine from the directory.
