### ISSUE TITLE
Forwarding separate photo from an album always sends first image

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#16447]
### Steps to reproduce
1. Upload photos as an album
2. Open any photo of this album, except first
3. Select `Forward` or `Delete`

### Expected behaviour
Opened photo will be forwarded/deleted

### Actual behaviour
The first photo is actually forwarded/deleted

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 2.7.9 beta

**Installation source (Linux Only)** - the official website

**Used theme**: Any

**Comment by 23rd** [comment]
Thanks for your report.
