### ISSUE TITLE
[Feature Request] Ability to disable Echo cancellation and Nouse Suppression

### ISSUE THREAD

**Issue by Devocub** [telegramdesktop/tdesktop#16456]
### Is your feature request related to a problem?
In private call: noise suppression might reduce quality and comfort and echo cancellation does mute another party when I talk.

### Describe the solution you'd like
Checkmarks in settings to disable Echo cancellation and Nouse Suppression. I would like streams of audio from microphone pass between us without any effects added. (on PC)

### Describe alternatives you've considered
no

**Comment by Aokromes** [comment]
https://i.imgur.com/VXWpd7H.png you already can on settings.

**Comment by Devocub** [comment]
I'm sorry but where I can find this menu? Is it only for groups? I meant private tet-a-tet calls
