### ISSUE TITLE
[Feature Request] Install Telegram for All users

### ISSUE THREAD

**Issue by xmha97** [telegramdesktop/tdesktop#16452]
Please add a option to install Telegram for all users (per machine):
![image](https://user-images.githubusercontent.com/23485114/122639413-ec59fd80-d10e-11eb-9c48-c1ed3b85d35c.png)
![image](https://user-images.githubusercontent.com/23485114/122639425-fed43700-d10e-11eb-9e7e-cf99b7935df6.png)

**Comment by ilya-fedin** [comment]
#5718
