### ISSUE TITLE
Sinhala Unicode Error

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#16451]
### Steps to reproduce
1. Changing Unicode To Sinhala
2. Typing

### Expected behaviour
Sinhala Should Be Typed Correctly Like The Android Version 

### Actual behaviour
Only The First Base Form The Letter Being Typed So Can't Make Up Words Like In Android Version

### Configuration
**Operating system:** Windows / Arch Linux / Debian Based Ones

**Version of Telegram Desktop:** Both New And Old Versions

**Installation source (Linux Only)** - the official website / Snap / Microsoft Store / Linux Repositories:

**Used theme**: Default

**Comment by ilya-fedin** [comment]
> Only The First Base Form The Letter Being Typed So Can't Make Up Words Like In Android Version

What do you mean?

**Comment by nxthsara** [comment]
I Mean That Sinhala Language Typing Doesn't Really Work On Telegram Desktop

**Comment by ilya-fedin** [comment]
Your explanations aren't clear, I don't understand what the bug is

**Comment by nxthsara** [comment]
Are There Any Sri Lankan Developers In Your Team ? I Hope They Will Understand

**Comment by ilya-fedin** [comment]
> Are There Any Sri Lankan Developers In Your Team ?

no, tdesktop is developed only by @john-preston

**Comment by nxthsara** [comment]
Oh I See It's a Language Issue To Put This Simply "Sinhala" Language Unicode Doesn't Work I Don't Know How To Explain This Further Anyways It's a Language Issue

**Comment by ilya-fedin** [comment]
>  Don't Know How To Explain This Further

you can make screenshots

**Comment by nxthsara** [comment]
![correct](https://user-images.githubusercontent.com/66399609/122666302-115f7680-d1ca-11eb-934b-2d8eaa522340.jpg)
![incorrect](https://user-images.githubusercontent.com/66399609/122666303-13293a00-d1ca-11eb-94a0-c2982801bb70.jpg)


The Correct One Shows When Copied And Pasted From Somewhere It Works 
And the Incorrect One Shows When You Tried Type The Same Thing In The Typing Area :(

This Is The Issue Typing Doesn't Work Screenshots Are From Windows In Linux Ones Issue Is Still The Same

**Comment by ilya-fedin** [comment]
> And the Second One Shows When You Tried Type The Same Thing In The Typing Area :(

Can you check whether this bug is happening in other Qt applications, e.g. qBittorrent?

**Comment by nxthsara** [comment]
Yeah I Tried & It's Happening on qBittorrent Also :(

**Comment by ilya-fedin** [comment]
It's a Qt bug then

**Comment by nxthsara** [comment]
Will You Fix This ?

**Comment by ilya-fedin** [comment]
no

**Comment by nxthsara** [comment]
:(

**Comment by Aokromes** [comment]
> :(

it needs to be fixed by QT guys.

**Comment by nxthsara** [comment]
Okay :)
