### ISSUE TITLE
Newly connected microphone doesn't detectec by telegram until program restart

### ISSUE THREAD

**Issue by Devocub** [telegramdesktop/tdesktop#16458]
### Steps to reproduce
1. Run telegram
2. Get a call
3. Connect microphone to pc (it is marked as default)
4. Anwser the call
5. Another party can't hear you
6. Restart telegram
7. Call again - now it works

### Expected behaviour
Mic should be redetected on any change or you should be able to choose what mic to use

### Actual behaviour
Mic wasn't detected

### Configuration
**Operating system:** Win10 1903 x64

**Version of Telegram Desktop:** 2.7.4 but probably same on latest beta

**Comment by lokpozzta** [comment]
ក
