### ISSUE TITLE
Can't listen audio messages with Asus xonar u7

### ISSUE THREAD

**Issue by Ansem93** [telegramdesktop/tdesktop#1645]
Hi. I have windows 10 64bit.
Since I started to use my asus xonar U7 as audio card, I can't listen audio messages anymore. When I click on play they will stop immediately without even starting.
how can I resolve?

**Comment by mirh** [comment]
What is selected as default playback device?

**Comment by Ansem93** [comment]
the asus xonar u7. When i select my TV connected by HDMI as playback device the audio messages begin to works until I don't return to the xonar U7

**Comment by mirh** [comment]
Make sure to close and re-open again Telegram, due to #1044

**Comment by Ansem93** [comment]
Ok after cling and re-open they works! :D I even tried to uninstall and reinstall it but didn't tried that

**Comment by mirh** [comment]
This should be fixed in latest version, check.
