### ISSUE TITLE
Music Column not Available in Search Section

### ISSUE THREAD

**Issue by New-dev0** [telegramdesktop/tdesktop#16462]
### Steps to reproduce
1. telegram Desktop doesnt allow to Search in Chat by filtering music
2. open any chat
3. Views its Group Info 

### Expected behaviour
Filtering Music should be made available, as other Clients Provide.

### Actual behaviour
Its Not there <br><p align="center"><img src="https://telegra.ph/file/e832f5cbcfbcb1c2023d3.jpg"></p>

### Configuration
**Operating system:** Window

**Version of Telegram Desktop:** 2.7.9-beta

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:  Doesnt Matter / Night Mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RememberTheAir** [comment]
Click on "audio files", there's a search bar at the top

**Comment by New-dev0** [comment]
> Click on "audio files", there's a search bar at the top

Ya, sorry & thanks, just got confused between the names, Telegram Android Calls the Section as "Music"

**Comment by RememberTheAir** [comment]
@New-dev0 I didn't think about that, maybe it's worth to point this out on the translation platform

**Comment by lokpozzta** [comment]
Ok
