### ISSUE TITLE
Some letters is missing in entered words in Tg Desktop for win 10.

### ISSUE THREAD

**Issue by 5x3** [telegramdesktop/tdesktop#16465]
on local machine:
Telegram Desktop (last version) under Windows 10 (default config).
on machine used TightVNC (last ver with default config).

on remote machine:
vncviewer local-machine
vinagre  local-machine
Now open Telegram, open chat with anybody, change languare to Russian and start type
if you typing fast (as me) you will see BUG1:
some letters will be missed even if you absolutely sure that you typed it.
BUG2:
some letters will be doubled  and some missed even if you absolutely sure that you typed word correctly.

Workaround:
You can type letters very slow to avoid this bugs.

note, in other apps everyting is fine, I can type as fast as I can, no missing, no doubled.

**Comment by ilya-fedin** [comment]
Check other Qt applications like qBittorrent

**Comment by 5x3** [comment]
>Check other Qt applications like qBittorrent
works like a charm. no bugs in internal edit boxes and text areas. not the QT issue, but TG issue.
