### ISSUE TITLE
Tiled background is being enabled after every auto-update

### ISSUE THREAD

**Issue by yurikoles** [telegramdesktop/tdesktop#16468]
### Steps to reproduce
1. Setup some chat background.
2. Disable background tiling.
2. Apply in-app update.

### Expected behaviour
Tile background setting should be preserved.

### Actual behaviour
Tile background is keeping enabled after every in-app update.

### Configuration
**Operating system:**
macOS from 10.15 (Catalina) through 12.0 (Monterey). Windows 10 and 11.

**Version of Telegram Desktop:**
Still an issue in 2.7.9, but I observe this for at least one year.

**Used theme**:
Tinted.

**Comment by yurikoles** [comment]
I can confirm this on Windows 10 and 11.

**Comment by cyberpunkrocker-zero** [comment]
It is still happening on telegram-desktop-3.2.3, on Arch Linux... This is getting really annoying. I need to uncheck the 'Chat backround > Tile backgound'-setting every f*****g time there's an update.

**Comment by woomiez** [comment]
It seems that every update inverts this setting. I'm on Win10, and use a tiled chat background, and after every update TDesktop reverts this to a stretched instead of tiled background.

**Comment by lordrex34** [comment]
This is a really annoying issue. I can confirm the same here.

**Comment by d1vanov** [comment]
Same for me, very annoying really.

**Comment by john-preston** [comment]
@yurikoles @cyberpunkrocker-zero which wallpaper are you using that gets the "Tile background" enabled after an update?

Also, can anybody reproduce that on a fresh install? Like, on Windows download some older portable version from https://github.com/telegramdesktop/tdesktop/releases unpack it to a clean folder and try to reproduce the bug.

Is it reproducible on a freshly unpacked old->to->new version?

**Comment by cyberpunkrocker-zero** [comment]
> So, each time it was a custom chat background ("Choose image..." etc) and it was resetting from non-tiled to tiled?

That's correct.

**Comment by woomiez** [comment]
In my case, I have the same background image (own one) on both Android and desktop (Win10), and it keeps happening on all updates, including the most recent a few days ago. for some reason, I also have this background image in the chat background chooser about 50 times.. so it seems to create a new theme entry each time I switch back to tiled..

**Comment by laikoni** [comment]
For me the issue also happens with one of the default images (Choose from gallery) as background, with the 'blurred' option enabled. (Telegram Desktop on Windows 10)

**Comment by john-preston** [comment]
@woomiez Ok, looks like it uploads each time as a new cloud background. For you it is resetting from tiled to non-tiled, right? (not like the previous reporter)

If you're on Windows:

Can you please check if it reproduces on a fresh portable version from a clean folder? Like, download portable version 3.5.0:

https://github.com/telegramdesktop/tdesktop/releases/download/v3.5.0/tportable-x64.3.5.0.zip

log in, set the desired background and try to autoupdate the app (it should update to 3.5.1), will the problem be reproduced?

**Comment by john-preston** [comment]
@laikoni Can you provide details: which image exactly (there are mostly cloud-synced backgrounds, but there are some hard-coded to the binary with completely different handling in code), and do you try to keep it tiled / non-tiled and what value you get after the autoupdate?

Also, please check if it is reproduced on a fresh portable version from a clean folder, like I've described in the comment above.

**Comment by woomiez** [comment]
> @woomiez Ok, looks like it uploads each time as a new cloud background. For you it is resetting from tiled to non-tiled, right? (not like the previous reporter)

yes. I want it tiled, and it resets to stretched.

> If you're on Windows:
> Can you please check if it reproduces on a fresh portable version from a clean folder? Like, download portable version 3.5.0:
> 
> https://github.com/telegramdesktop/tdesktop/releases/download/v3.5.0/tportable-x64.3.5.0.zip
> 
> log in, set the desired background and try to autoupdate the app (it should update to 3.5.1), will the problem be reproduced?

I have done that, and the problem did not occur there.

**Comment by GideonUng** [comment]
lol why is this still an issue?

**Comment by firnen0** [comment]
This is still happening for me

**Comment by k-kruglov** [comment]
Happens on Windows 10, 4.2.4. x64.

**Comment by 7nik** [comment]
This still happens on 4.3.1, annoying

**Comment by ilya-fedin** [comment]
It seems #5944 is mostly about this, so this apparently should be closed as a duplicate to have "still happens" messages in only one place.

**Comment by john-preston** [comment]
Please check by updating 4.5.1 to 4.5.2.
