### ISSUE TITLE
Wrong media order when scrolling through media in viewer

### ISSUE THREAD

**Issue by Rebel028** [telegramdesktop/tdesktop#16469]
### Steps to reproduce
1.  Find any post with multiple media files attached to it (as an album).
2.  Click on any image or video except for the first one in the album so that the viewer shows up. 
3.  Try scrolling up or down.

### Expected behaviour
1. When scrolling down - next media item show up in viewer, when scrollin up - previous one.
2. Bottom thumbnails highlight the currently selected media item.

### Actual behaviour
1. Scrolling down brings up **second** element of the album, instead of next in the sequence. If the second one was selected then nothing happens on the first scroll. When scrolling up, the last media in the previous post is shown.
2. Bottom thumbnails highlignt first media item in the album.

### Configuration
**Operating system:** Windows 10 1909

**Version of Telegram Desktop:**  v2.7.9 beta

**Comment by 23rd** [comment]
Should be fixed in 2.7.10.

**Comment by Rebel028** [comment]
I can confirm it is fixed now (v2.7.10 beta), thanks!
