### ISSUE TITLE
[Feature Request]  Option to display the pinned message(s) banner of a channel

### ISSUE THREAD

**Issue by Philibre2020** [telegramdesktop/tdesktop#16461]
### Is your feature request related to a problem?
In a __channel I've subscribed to__,  in which there is/are some __pinned message(s)__, if __I close the banner__ (by clicking on the right cross), there is __no option to have it back__.

### Describe the solution you'd like
In the channel contextual menu (icon with 3 dots vertically), there should be a item :
- "display the pinned messages".

### Describe alternatives you've considered
None.

### Additional context
None.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5526
