### ISSUE TITLE
MacOS taskbar icon becomes distorted on focus loss

### ISSUE THREAD

**Issue by tijnrenders** [telegramdesktop/tdesktop#16463]
### Steps to reproduce
1. Launch the Telegram Client 
2. Focus on another window / app, but leave the MacOS taskbar in view
3. The taskbar icon should lose it's dimensions, and distort the icon and its notification count
4. Click on the taskbar. The icon should fix itself.

### Expected behaviour
The icon and its notification count should remain the same dimensions, no matter the focus state.

### Actual behaviour
After focusing on another app / window, the Telegram taskbar icon and its notification count become distorted

### Configuration
**Operating system:**
macOS 11.4 (20F71)

**Version of Telegram Desktop:**
2.7.4

**Used theme**:
Tinted (build in theme)

<img width="351" alt="Screenshot 2021-06-21 at 13 09 14" src="https://user-images.githubusercontent.com/6113193/122754037-67e4b780-d293-11eb-9fe2-f38d4b35e4e3.png">

**Comment by lokpozzta** [comment]
@sreyleak
