### ISSUE TITLE
[Feature Request] Allow for more than 100 chats in a folder

### ISSUE THREAD

**Issue by AlexanderAmelkin** [telegramdesktop/tdesktop#16475]
### Is your feature request related to a problem?

In my company we use Telegram as an official means of communication.
I have a real lot of work-related chats (many workgroups, a lot of colleagues who may write to me).
When I tried to add all of them into a 'Work' folder I hit the limit of just 100 chats per foler.

### Describe the solution you'd like

No artificial limit on the size of a folder

### Describe alternatives you've considered

Creating multiple folders, each containing just a part of work chats, and then click-switching between them. Not very convenient.

### Additional context

None

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by RememberTheAir** [comment]
I think this is more or less the same request: https://bugs.telegram.org/c/6256

**Comment by AlexanderAmelkin** [comment]
Thanks for the links. Before I saw ticket 6256 there, I've created another one: https://bugs.telegram.org/c/6608
Posting it here for the others to find as they search.
