### ISSUE TITLE
32-bit webcam drivers do crash telegram sound

### ISSUE THREAD

**Issue by Devocub** [telegramdesktop/tdesktop#16470]
### Steps to reproduce
1.  Use 32-bit OBS virtual cam or use webcam with 32-bit only driver
2. Start a call
3. Start video
4. In case of 32-bit webcam drivers telegram doesn't play sound from interlocutor until program restart

### Expected behaviour
Sound shouldn't be affected by webcam drivers

### Actual behaviour
No sound from other party if 32-bit webcam driver is used. (I still can be heard)

### Configuration
**Operating system:** w10 x64

**Version of Telegram Desktop:** 2.7.9 beta

**Comment by ilya-fedin** [comment]
Provide crash report tag

**Comment by Devocub** [comment]
I can't do it right now but when I checked there were nothing valuable regarding bug. Is there any bots/test accounts I can call?

**Comment by ilya-fedin** [comment]
no, there's none

**Comment by ilya-fedin** [comment]
Ah, you say it doesn't play, I thought you got a crash. You should enable debug logs and provide last_openal_log.txt then

**Comment by Devocub** [comment]
Yeah, I can't hear interlocutor as soon as I choose PS3 eye webcam with CL-EYE driver ("CL-Eye-Driver-5.3.0.0341-Emuline") even after calling again but I can play and hear music. The Telegram did not quit completely after that, was forced to kill process.
[last_openal_log.txt](https://github.com/telegramdesktop/tdesktop/files/6708951/last_openal_log.txt)
[log_strip.txt](https://github.com/telegramdesktop/tdesktop/files/6708952/log_strip.txt)
[last_call_log_strip.txt](https://github.com/telegramdesktop/tdesktop/files/6709021/last_call_log_strip.txt)
according to "last_call_log_strip.txt" it seems it is in infinite loop

**Comment by ilya-fedin** [comment]
> but I can play and hear music

You mean you can play music in Telegram?

**Comment by Devocub** [comment]
Yes, I guess all sounds do work except sound in any private call

**Comment by ilya-fedin** [comment]
so it's probably webrtc stuck somewhere rather than openal...
