### ISSUE TITLE
Monowidth formatting is lost when you start editing a message

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#16474]
### Steps to reproduce
1. Send a message with monowidth formatting (for example:
Regular message
**bold**
_italic_
`mono`

2. Press Up key to edit it (or right click and select 'edit')

### Expected behaviour
An input field should contain that message with all applied formatting

### Actual behaviour
Monowidth formatting is lost unless you re-apply it manually.
The original message
![image](https://user-images.githubusercontent.com/2780044/123233732-f8650700-d4e2-11eb-8ea6-bc17aa87a5a6.png)
Press "up" to edit it (mono formatting is lost already)
![image](https://user-images.githubusercontent.com/2780044/123233806-0c106d80-d4e3-11eb-9cae-b5dd4774702e.png)
Press Enter without making any modifications (mono is lost)
![image](https://user-images.githubusercontent.com/2780044/123233875-1c284d00-d4e3-11eb-97ac-317bde362d83.png)

### Configuration
**Operating system:** Manjaro
**Version of Telegram Desktop:** 2.7.10 beta

**Comment by Marzal** [comment]
Same problem in ArchLinux using the official binary from the website.
There is also a strange behavior with mono when you format a sentence with emojis.

**Comment by Marzal** [comment]
Fixed in 2.8 (at lest for me)

**Comment by MasterGroosha** [comment]
@Marzal yep, seems to be fixed for me as well. Thanks for noticing and thank you devs for the fix.
Closing the issue
