### ISSUE TITLE
Add ability to set profile photo as main

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#16477]
### Is your feature request related to a problem?
Android version have feature that allows me to set older profile photos as main.
![изображение](https://user-images.githubusercontent.com/5204968/123299682-74cb0a80-d522-11eb-882c-21029826e4ae.png)

### Describe the solution you'd like
Adding such feature to tdesktop.

**Comment by soredake** [comment]
Not stale.

**Comment by 23rd** [comment]
Hi, please check 3.7.1+ version.

**Comment by soredake** [comment]
@23rd thanks, option is now present in latest version, closing.
