### ISSUE TITLE
All screens are detected as one in screensharing on Linux

### ISSUE THREAD

**Issue by p0358** [telegramdesktop/tdesktop#16482]
### Steps to reproduce
1. Go into a group chat and start/join a voice chat
2. Open menu and click on "share screen", or click on the button if sharing is already happening, doesn't matter
3. You see that among screens and windows, there's only Screen 1, but it has both of your screens combined as one image.

### Expected behaviour
I have two monitors, I should see two separate screens, rather than both combined into one. Even if such combined area was a feature, I still expect to be able to share them independently.

### Actual behaviour
![image](https://user-images.githubusercontent.com/5182588/123453614-064c8200-d5e0-11eb-93b7-6c8c4a6d6bb3.png)

### Notes
Discord had a similar issue across many systems for a long time, very long time actually. They have recently fixed it. In their case the screen list was showing two screens, but starting the share showed the combined image. One workaround that worked for some was disabling hardware acceleration in settings, but that had a potential to cause other issues for them.

### Configuration
**Operating system:** Linux 5.10.34-1-MANJARO x86_64, X11 session, KDE, AMD GPU, OpenGL 4.6 (Compatibility Profile) Mesa 21.1.2 [last thing as in log]

**Version of Telegram Desktop:** 2.8

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
AUR which downloaded bin version from official website, but I re-enabled built-in auto-updater, and this release was updated with it, so it's compiled by Telegram

**Used theme**:
One of the defaults with an adjusted color

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
Not sure if necessary, I will include if it's not reproducible or I'm asked to, because not sure which files should I include. There's nothing in the main log.txt after I click share screen itself.

[2021.06.25 17:46:28] OpenGL: [TRUE] (Ui::GL::Window)
[...]
[2021.06.25 17:57:25] Getting DE, XDG_CURRENT_DESKTOP: 'KDE'
[2021.06.25 17:57:25] Getting DE, DESKTOP_SESSION: 'plasma'
[2021.06.25 17:57:25] Getting DE, KDE_SESSION_VERSION: '5'
[2021.06.25 17:57:25] DE: KDE5
</details>

**Comment by ilya-fedin** [comment]
> They have recently fixed it.

If there's no any info about how they fixed that then it's a useless note :(

**Comment by rafalbednarczuk** [comment]
On ubuntu 18.04 it works as it suppose to work with 2 monitors. I can share either whole display or a single window

**Comment by p0358** [comment]
> On ubuntu 18.04 it works as it suppose to work with 2 monitors. I can share either whole display or a single window

Interesting, the Discord issue used to plague Ubuntu users too. I'd be curious to know if it works on 21.04 on Ubuntu, since it uses Wayland, and I've heard something about some weirdness there when it comes to monitor support (or at least the ability to get window's position on the screen)

> If there's no any info about how they fixed that then it's a useless note :(

@ilya-fedin I've dug into the threads again and it appears the cause was the underlying electron/chromium and their code, and I found URLs to relevant bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=396091 (status: fixed)
Here's some code in Qt's API and the underlying code for multi-monitor things from that thread:
https://doc.qt.io/archives/qt-4.8/qdesktopwidget.html
https://code.qt.io/cgit/qt/qt.git/tree/src/gui/kernel/qdesktopwidget_x11.cpp#n272
Also from chromium:
https://source.chromium.org/chromium/chromium/src/+/main:ui/base/x/x11_display_manager.cc;l=85?q=BuildDisplaysFromXRandRInfo&ss=chromium
https://source.chromium.org/chromium/chromium/src/+/main:ui/base/x/x11_display_manager.cc;l=85?q=BuildDisplaysFromXRandRInfo&ss=chromium
https://source.chromium.org/chromium/chromium/src/+/master:ui/views/widget/desktop_aura/desktop_screen_x11.cc
There's also a bug for Firefox for this, and it's still in the works:
https://bugzilla.mozilla.org/show_bug.cgi?id=1552456#c12

**Comment by ilya-fedin** [comment]
> Here's some code in Qt's API and the underlying code for multi-monitor things from that thread:

tdesktop uses webrtc for screen sharing

> https://bugs.chromium.org/p/chromium/issues/detail?id=396091 (status: fixed)

according to the thread, the bug was fixed a year or two ago in webrtc, so tdesktop shouldn't have it

**Comment by ilya-fedin** [comment]
I see the code proposed as the fix do exist in webrtc that is used (at least in offical builds) by tdesktop: https://github.com/desktop-app/tg_owt/blob/f03ef05abf665437649a4f71886db1343590e862/src/modules/desktop_capture/linux/screen_capturer_x11.cc#L151-L184

You're either using a third-party build or the linked bug report is not your case

**Comment by p0358** [comment]
> You're either using a third-party build or the linked bug report is not your case

It's definitely first party, since I used the updater (and it only works in official builds), and version in Arch repos is still 2.7.4 without screensharing.

> https://github.com/desktop-app/tg_owt/blob/f03ef05abf665437649a4f71886db1343590e862/src/modules/desktop_capture/linux/screen_capturer_x11.cc#L151-L184

This may explain some things then:
<details><summary><b>Fragment of DebugLogs/last_group_call_log.txt</b>:</summary>

2021-6-27 0:9:0:986 (basic_port_allocator.cc:1142): All candidates gathered for pooled session.
2021-6-27 0:9:2:80 (x_server_pixel_buffer.cc:202): Failed to get icc profile
2021-6-27 0:9:2:80 (screen_capturer_x11.cc:176): Unable to link XRandR monitor functions.
2021-6-27 0:9:2:320 (x_server_pixel_buffer.cc:202): Failed to get icc profile
2021-6-27 0:9:2:323 (screen_capturer_x11.cc:176): Unable to link XRandR monitor functions.
2021-6-27 0:9:2:382 (thread.cc:715): Message to WebRTC-DesktopCapturer took 59ms to dispatch. Posted from: runAsync@/usr/src/tdesktop/Telegram/ThirdParty/tgcalls/tgcalls/desktop_capturer/
DesktopCaptureSourceHelper.cpp:82
2021-6-27 0:9:2:388 (x_server_pixel_buffer.cc:202): Failed to get icc profile
2021-6-27 0:9:2:396 (x_server_pixel_buffer.cc:202): Failed to get icc profile
2021-6-27 0:9:2:409 (x_server_pixel_buffer.cc:202): Failed to get icc profile
2021-6-27 0:9:2:439 (x_server_pixel_buffer.cc:202): Failed to get icc profile
2021-6-27 0:9:2:457 (x_server_pixel_buffer.cc:202): Failed to get icc profile
2021-6-27 0:9:2:471 (x_server_pixel_buffer.cc:202): Failed to get icc profile
2021-6-27 0:9:2:510 (x_server_pixel_buffer.cc:202): Failed to get icc profile
2021-6-27 0:9:2:539 (x_server_pixel_buffer.cc:202): Failed to get icc profile
2021-6-27 0:9:4:45 (GroupNetworkManager.cpp:87): Outgoing DataChannel message: {"colibriClass": "ReceiverVideoConstraints", "constraints": {}, "defaultConstraints": {"maxHeight": 0}, "onS
tageEndpoints": []} 
2021-6-27 0:9:5:947 (x_server_pixel_buffer.cc:202): Failed to get icc profile
2021-6-27 0:9:5:947 (screen_capturer_x11.cc:176): Unable to link XRandR monitor functions.
2021-6-27 0:9:5:947 (field_trial.cc:140): Setting field trial string:WebRTC-Audio-Allocation/min:32kbps,max:32kbps/WebRTC-Audio-OpusMinPacketLossRate/Enabled-1/WebRTC-TaskQueuePacer/Enabl
ed/WebRTC-VP8ConferenceTemporalLayers/1/WebRTC-Audio-MinimizeResamplingOnMobile/Enabled/
2021-6-27 0:9:5:948 (openssl_key_pair.cc:38): Making key pair
2021-6-27 0:9:5:948 (openssl_key_pair.cc:91): Returning key pair
2021-6-27 0:9:5:948 (openssl_certificate.cc:59): Making certificate for WebRTC
2021-6-27 0:9:5:948 (openssl_certificate.cc:109): Returning certificate
</details>

```
(screen_capturer_x11.cc:176): Unable to link XRandR monitor functions.
```

I'm a little confused, because it seems to use some thing from libxrandr above just fine. I see it mentions Debian, so in case it matters, Arch has the lib in
```
/usr/lib/libXrandr.so
/usr/lib/libXrandr.so.2
/usr/lib/libXrandr.so.2.2.0
```
while Debian at:
```
/usr/lib/x86_64-linux-gnu/libXrandr.so.2
/usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
```

Or perhaps Telegram statically links libxrandr rather than just linking the library import, and if the system library isn't loaded, the call to link the function from loaded modules fails?

Compiling a simple program seems to confirm my above suspicion:
```cpp
#include <iostream>
#include <dlfcn.h>

int main()
{
    auto get_monitors_ = reinterpret_cast<void*>(
          dlsym(RTLD_DEFAULT, "XRRGetMonitors"));
    auto free_monitors_ = reinterpret_cast<void*>(
          dlsym(RTLD_DEFAULT, "XRRFreeMonitors"));
    if (get_monitors_ && free_monitors_)
        std::cout << "ok";
    else
        std::cout << "not ok";
    return 0;
}
```
```
$ g++ test.cpp -lstdc++ -Wl,--no-as-needed -ldl -lXrandr -o test
$ ./test 
ok
```
But it outputs `not ok` if I remove `-lXrandr` from the command line.

**Comment by ilya-fedin** [comment]
> Unable to link XRandR monitor functions.

So their fix doesn't work :/

**Comment by ilya-fedin** [comment]
show the result of `readelf -a /usr/lib/libXrandr.so.2.2.0 | grep -e XRRGetMonitors -e XRRFreeMonitors`

**Comment by ilya-fedin** [comment]
Stop, xrandr is built statically in official builds. Since it uses dlsym, these symbols are stripped most likely...

**Comment by p0358** [comment]
```
$ readelf -a /usr/lib/libXrandr.so.2.2.0 | grep -e XRRGetMonitors -e XRRFreeMonitorsrs
    76: 0000000000008130   833 FUNC    GLOBAL DEFAULT    9 XRRGetMonitors
    98: 0000000000008690     6 FUNC    GLOBAL DEFAULT    9 XRRFreeMonitors
```

> Stop, xrandr is built statically in official builds. Since it uses dlsym, these symbols are stripped most likely...

Exactly what I wanted to say, and that's why the minimum example works, and with static link it has no way to dynamically load the symbols. It could if the system library was loaded in addition to that. So options would either include loading both, dropping Debian 8 support, or somehow not linking it statically at all and then replacing all the static calls to dynamic calls (with some static loads with dlsym), only options that come to my mind

**Comment by ilya-fedin** [comment]
> So options would either include loading both, dropping Debian 8 support, or somehow not linking it statically at all and then replacing all the static calls to dynamic calls (with some static loads with dlsym), only options that come to my mind at the moment

Since the library is linked statically, this debian 8 hack has no sense, it will work on debian 8 even without this hack

**Comment by p0358** [comment]
Right, makes sense. So simply replacing dynamic load to static call should help with this

**Comment by p0358** [comment]
Still the same in 2.8.6 beta, was the lib updated?

**Comment by ilya-fedin** [comment]
only @john-preston knows whether he rebuilt the library or not

**Comment by ilya-fedin** [comment]
I see that Dockerfile is still on old commit: https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/build/docker/centos_env/Dockerfile#L740
