### ISSUE TITLE
Media Viewer with activities in KDE

### ISSUE THREAD

**Issue by mazunki** [telegramdesktop/tdesktop#16480]
### Steps to reproduce
1. Have multiple Activities (similar to virtual desktops, but not exactly the same) in KDE
2. Open Telegram Desktop
3. Show Telegram on all activities (right click Telegram in applications bar, and submenu to activities)
4. Go to any contact, and press to open an image or video
5. Bug

### Expected behaviour
The video or image should be shown in the currently active activity.

### Actual behaviour
The image viewer is (often) shown in another activity.
I'm not exactly sure how it selects where to show the media viewer, but my first guess would be that it selects the one where you initially opened the application. 

![image](https://user-images.githubusercontent.com/32819373/123398568-fca52900-d5a3-11eb-9fb9-e4ae5d810992.png)

Currently, I swap over to where I know it will be open, but the reason I have multiple activities is so I can focus on whatever I'm working on:

![image](https://user-images.githubusercontent.com/32819373/123397803-227dfe00-d5a3-11eb-9836-bf8a02ed311b.png)

### Configuration
**Operating system:** `Linux caromanjaro 5.11.4-1-rt11-MANJARO #1 SMP Fri May 21 00:10:17 CEST 2021 x86_64 GNU/Linux`

**Version of Telegram Desktop:** `2.7.4-1`

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: `telegram-desktop-bin` in AUR repository

**Used theme**: Tinted in Telegram. Breeze Dark in KDE.

<details><summary><b>Logs</b>:</summary>
I can provide any logs if asked for
</details>

**Comment by ilya-fedin** [comment]
tdesktop's code has nothing related to activities, you should report this to KDE instead

**Comment by mazunki** [comment]
@ilya-fedin 
Are you saying KDE / the desktop manager is responsible for where a new spawned window should be opened, and Telegram just uses default "location"? I guess that makes more sense.

**Comment by ilya-fedin** [comment]
all media viewer does is chooses the same screen where main window is placed (this is done via Qt API and Qt fails here very frequently, here's a lot of reports that Qt chooses the wrong screen), the code doesn't know anything about any 'activities'

**Comment by mazunki** [comment]
Thanks for the help, I will look into the integration between Qt and KDE then. Closing since this is not Telegram's fault.
