### ISSUE TITLE
Settings in group calls have no camera section

### ISSUE THREAD

**Issue by p0358** [telegramdesktop/tdesktop#16486]
### Is your feature request related to a problem?
When you're in a group call, the shortcut settings (3-dots menu -> Settings) have no section for setting the current camera to use. (on screenshot we can see only speakers and microphone input devices are settable there)
![image](https://user-images.githubusercontent.com/5182588/123497649-f8721d80-d62e-11eb-98c6-b9c737d5ea34.png)

### Describe the solution you'd like
It should include the camera section to be able to set up the current camera easily. It should display regardless of whether any cameras are attached (to let users know no cameras are detected) and regardless of current call being voice only (as the user may want to set up current camera before starting it). There could be no preview if there's no camera attached or something to keep the dialog simple, or it could be enabled on demand or something. (on screenshot we see the camera as the first option, in addition to speakers/headphones and microphone)
![image](https://user-images.githubusercontent.com/5182588/123497748-9cf45f80-d62f-11eb-8481-87bcb3ac7a6a.png)

### Describe alternatives you've considered
Going into Settings -> Advanced -> Call settings. Not really intuitive, but it's there.

### Additional context
It was probably just forgotten while updating the group chat UI for video things.

**Comment by guillecro** [comment]
+1 to this. Its not possible to change cameras, unless you go to something like https://webcamtests.com/ and you make your other cameras "busy" so telegram detects the one that you want as the only available.

**Comment by Aokromes** [comment]
you can change cameras already on calls -> 3 dots.

**Comment by p0358** [comment]
> you can change cameras already on calls -> 3 dots.

I'm on latest 2.8.1 and I don't see the option anywhere, the 3-dots menu only has settings for speaker and mic, while the option exists in regular settings. Can you show me a screenshot? Maybe the invisibility of the option on my side is a bug

**Comment by Aokromes** [comment]
https://i.imgur.com/OYrZJdg.png
https://i.imgur.com/iVLDTxZ.png

**Comment by p0358** [comment]
> https://i.imgur.com/OYrZJdg.png
> https://i.imgur.com/iVLDTxZ.png

Oh, but this is from the last calls screen and it opens the screen from regular settings (settings -> advanced settings -> calls). But the UI I meant was the one which is shown during the group call:

![image](https://user-images.githubusercontent.com/5182588/123525572-ff9e3780-d6d1-11eb-8222-9e0178664ff0.png)

or same menu during screensharing/video session:

![image](https://user-images.githubusercontent.com/5182588/123525601-383e1100-d6d2-11eb-9360-185b4ffea3e0.png)

and this opens a _different_ UI than the one from regular settings, and this one has the camera option missing (same screenshot as 1st one in this thread, but in English):

![image](https://user-images.githubusercontent.com/5182588/123525609-54da4900-d6d2-11eb-9d77-bcc890819364.png)

**Comment by Aokromes** [comment]
> > [i.imgur.com/OYrZJdg.png](https://i.imgur.com/OYrZJdg.png)
> > [i.imgur.com/iVLDTxZ.png](https://i.imgur.com/iVLDTxZ.png)
> 
> Oh, but this is from the last calls screen and it opens the screen from regular settings (settings -> advanced settings -> calls). But the UI I meant was the one which is shown during the group call:
> 
> ![image](https://user-images.githubusercontent.com/5182588/123525572-ff9e3780-d6d1-11eb-8222-9e0178664ff0.png)
> 
> or same menu during screensharing/video session:
> 
> ![image](https://user-images.githubusercontent.com/5182588/123525601-383e1100-d6d2-11eb-9360-185b4ffea3e0.png)
> 
> and this opens a _different_ UI than the one from regular settings, and this one has the camera option missing (same screenshot as 1st one in this thread, but in English):
> 
> ![image](https://user-images.githubusercontent.com/5182588/123525609-54da4900-d6d2-11eb-9d77-bcc890819364.png)

you are looking into a total incorrect place, the calls i say is here https://i.imgur.com/2ssxkuH.png

**Comment by p0358** [comment]
> you are looking into a total incorrect place, the calls i say is here https://i.imgur.com/2ssxkuH.png

Yes, I acknowledged that. I'm not saying the option to change a camera doesn't exist at all in the app.
The issue is about the in-call settings missing the options, I'm aware the full settings have that, but the purpose of that handy second options screen is to not dig into full settings/other places to find it, but to have input device settings by hand, where the camera is missing from the list

**Comment by guillecro** [comment]
Actually, I don't know if it has been told, but there is a way to change your camera in the settings:

Settings > Advanced > Call settings

![image](https://user-images.githubusercontent.com/8771166/123526741-41b68180-d6b0-11eb-8198-0e8716973632.png)

**Comment by p0358** [comment]
bruh

**Comment by jonbesga** [comment]
It is possible to change the default camera in Telegram permanently from:

Settings → Advanced → Call settings (in system integration section)

However, I agree there should be an option in the Settings available from the video conference.

**Comment by mirh** [comment]
I'm fairly sure there still isn't any button.
