### ISSUE TITLE
Crash on changing audio volume

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#16483]
### Steps to reproduce
1. Play an audio
2. Change volume with the slider

### Expected behaviour
Volume should change

### Actual behaviour
App crashes 

### Configuration
**Operating system:** Arch Linux, Windows 10

**Version of Telegram Desktop:** 2.8

**Installation source (Linux Only)** - the official website

**Used theme**: Any

**Comment by Aokromes** [comment]
supply crash id on next restart.

**Comment by Aokromes** [comment]
Your Report Tag: 8a3da6f0-8663-4389-b258-b6303af3f20b

**Comment by Graham1384** [comment]
this also happens for me on manjaro linux. I'm using official binary from telegram website

**Comment by Aokromes** [comment]
very likely fixed on https://github.com/telegramdesktop/tdesktop/commit/14f25fc997506e2e1cd5d918826c931e6e82f820

**Comment by Graham1384** [comment]
why it's not available on AUR? still waiting.

**Comment by Aokromes** [comment]
> why it's not available on AUR? still waiting.

idk, i recomend you to use the official telegram package instead linux distribution package.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v2.8.1

**Comment by aNNiMON** [comment]
> supply crash id on next restart.

Sorry, I sent a report from the crash screen, including my nickname, but forgot to mention the Report Tag here.
Thanks for fixing this quickly!
