### ISSUE TITLE
release 2.8.1 binarys are missing

### ISSUE THREAD

**Issue by iMonZ** [telegramdesktop/tdesktop#16497]
The Binaries for the normal operating systems are missing for the 2.8.1 release.

**Comment by p0358** [comment]
It's available if you check for updates in the app itself

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v2.8.1

**Comment by iMonZ** [comment]
> https://github.com/telegramdesktop/tdesktop/releases/tag/v2.8.1

Perfect now it’s there!
