### ISSUE TITLE
[Feature Request] "Add to folder" - why is it not already part of the desktop app? or am I missing something?

### ISSUE THREAD

**Issue by borisplotkin** [telegramdesktop/tdesktop#16495]
I didn't find a way to add chat to a folder from the desktop app, using windows.
Is this missing feature or I didn't find a way to do that?

Thanks for the great support!

**Comment by Aokromes** [comment]
right click over folder, edit folder, add desired chat.

**Comment by ilya-fedin** [comment]
#7927
