### ISSUE TITLE
linux 64 bit version cannot show chinese words

### ISSUE THREAD

**Issue by beenotung** [telegramdesktop/tdesktop#165]
linux 64 bit version cannot show chinese words in the application.
if i copy chinese from other place , and send it , it still cannot show chinese word (all turn into square char) , but those sent words can not shown on mobile client

**Comment by aguegu** [comment]
@SafaAlfulaij 

I can not type in Chinese characters on ubuntu 15.04 with the default pinyin input method. Should I open a new issue for that? 

Or it is just me.

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.
