### ISSUE TITLE
4k screen sharing, too low quality

### ISSUE THREAD

**Issue by wOvAN** [telegramdesktop/tdesktop#16503]
### Steps to reproduce
1. 4k display, scaling 200%
2. Share the screen
3. View the result

### Expected behaviour
Tell us what should happen
Decent resolution
![actual](https://user-images.githubusercontent.com/3645104/123535476-6f95d780-d73d-11eb-8e56-12015f10f138.jpg)

### Actual behaviour
Tell us what happens instead
Very low resolution
![low](https://user-images.githubusercontent.com/3645104/123535447-3d847580-d73d-11eb-9a72-e14776160e82.jpg)

### Configuration
**Operating system:**
Win64

**Version of Telegram Desktop:**
2.8.1
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by kirsan31** [comment]
#16487
