### ISSUE TITLE
Full screen mode bug: all messages (of both participants) show on a single side : mac os x

### ISSUE THREAD

**Issue by agoyaliitk** [telegramdesktop/tdesktop#1650]
this is only when in full screen mode.
working normally in small window mode.

**Comment by trijin** [comment]
yep. Windows 7 same trouble.
my message jump to left side if chat window(w/o Contacts) more 900px

**Comment by DaFri-Nochiterov** [comment]
#1587 -- Discussion about this
Please, search for existing issues before open new ones!

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.

**Comment by agoyaliitk** [comment]
Thanks!!
