### ISSUE TITLE
Two massive issues MUST A FIX !!! add an option for multi-select deleting chats and groups 

### ISSUE THREAD

**Issue by search620** [telegramdesktop/tdesktop#16502]
Two massive issues MUST A FIX !!! 

1. Add an option for multi-select deleting chats and groups.
2. must a different default video player for telegram. The current video player is simply unusable and not comfortable.

In the meantime only FIX these two and you have made progress :)

**Comment by Aokromes** [comment]
duplicate.

**Comment by ilya-fedin** [comment]
1. #4079
2. if you want to use system video player, you can enter `videoplayer` cheat code in the settings

**Comment by search620** [comment]
> 1. [Select multiple chats #4079](https://github.com/telegramdesktop/tdesktop/issues/4079)
> 2. if you want to use system video player, you can enter `videoplayer` cheat code in the settings

Thank you for your reply
Where can I find it in the setting? can't find it

**Comment by ilya-fedin** [comment]
it's a hidden feature, you should enter `videoplayer` like a cheat code in a game

**Comment by search620** [comment]
> it's a hidden feature, you should enter `videoplayer` like a cheat code in a game

What do you mean? What do I need to do to apply it?
