### ISSUE TITLE
sent message and incomming message on same side 

### ISSUE THREAD

**Issue by sutirthaghosh** [telegramdesktop/tdesktop#1651]
after the last update in telegram for ubuntu the sent message and received message appears on the same side that is left side it is irritating too much

**Comment by DaFri-Nochiterov** [comment]
#1587 -- Discussion about this
Please, search for existing issues before open new ones!

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.
