### ISSUE TITLE
[Feature Request] Add option for allowing admin to toggle inline message permissions in groups.

### ISSUE THREAD

**Issue by MidAutumnMoon** [telegramdesktop/tdesktop#16517]
### Is your feature request related to a problem?
Inline bots can be annoying sometimes, and admins may want to ban inline messages without disabling the right to send stickers in groups.

### Describe the solution you'd like
Add an individual option for toggling the inline message permission instead of depending on the sticker permission.

**Comment by RememberTheAir** [comment]
The permissions toggles should be consistent on every Telegram app. You should bring this suggestion to the official suggestions platform, or upvote [an existing one](https://bugs.telegram.org/c/5145)
