### ISSUE TITLE
Bot commands set with BotCommandScope not shown

### ISSUE THREAD

**Issue by javad94** [telegramdesktop/tdesktop#16516]
### Steps to reproduce
1. set commands for your bot using the new BotCommandScopeChat API with your chat_id
2. go to your bot on the Telegram desktop and click the forward slash button
3. your new set command not shown or the old one will shown

### Expected behaviour
Telegram desktop should show newly set commands with  BotCommandScope api

### Actual behaviour
Telegram desktop won't show newly set commands with BotCommandScope api

### Configuration
**Operating system:** Windows 10 20H2

**Version of Telegram Desktop:** 2.8.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by MasterGroosha** [comment]
It appears upon TDesktop restart (which is still not what you expect)

**Comment by javad94** [comment]
@MasterGroosha oh, checked it, that's correct. Thanks.
