### ISSUE TITLE
Note to Self Private Chat like SignalApp

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#16514]
### Is your feature request related to a problem?
a limitation.

### Describe the solution you'd like
Note to Self Private Chat like SignalApp
created automatically, by Default

### Describe alternatives you've considered
create a Private Channel, 
Skip people.
Too much workaround for something that should be created by Default.

**Comment by ilya-fedin** [comment]
You mean "Saved messages" channel that already exists?

**Comment by juanpc2018** [comment]
Telegram is Not intuitive,,

You Open Signal in Android,
Pum, Already configure, ready, 
Note to Self

the only problem with Signal is that cannot transfer old conversations to New Linked Devices,
making Note to Self, useless.

**Comment by ilya-fedin** [comment]
You haven't answered the question

**Comment by juanpc2018** [comment]
i think i did.

if Telegram was intuitive, you would never tell me how to use telegram.

Note to Self, should be a priority, 1st in the chat.
call it Sticky Notes or whatever is called in Russia.
Sticky Notes / Note to Self are useless if are hidden, nested somewhere under something.

the idea is to make them as Visible as possible, as easy as possible.

Makes No sense to have them hidden in a sub menu, double click, cant see immediately.

**Comment by ilya-fedin** [comment]
The issue is about adding a feature (that is already implemented), not about whether Telegram is intuitive or not

**Comment by RememberTheAir** [comment]
> You Open Signal in Android,
> Pum, Already configured, Ready,
> Note to Self

I have to tap on the pecil icon to access it, how's it more accessible than having to go to the side menu? From desktop it isnt even on top of the contacts list, it's placed in alphabetical order which makes it even less easier to access. Anyway, as in Signal, you can pin Saved Messages on top of your chats list to have it always accessible.
