### ISSUE TITLE
v2.8+ hijacks media keys on Mac OS

### ISSUE THREAD

**Issue by qtist** [telegramdesktop/tdesktop#16511]
Following the recent update, Telegram seems to hijack the media keys (play/pause, prev/next etc.) on Mac OS, meaning no other application (iTunes/Spotify or video players etc.) can be controlled using the keyboard. 

### Steps to reproduce
1. Open Telegram Desktop 2.8.0 or 2.8.1

### Expected behaviour
Media keys should continue to work as normal, controlling the most recently active media application. 

### Actual behaviour
Telegram Desktop swallows all pressed of media keys so nothing happens when pressed. Functionality returns to normal when Telegram Desktop is quit. 

### Configuration
**Operating system:**
Mac OS 10.13.6 (High Sierra)

**Version of Telegram Desktop:**
2.8.1

**Comment by qtist** [comment]
This continues to be an issue with Telegram Desktop. Setting the media keys in `shortcuts-custom.json` to NULL doesn't help. The best workaround seems to be to install a 3rd party application called BeardedSpice; however, this doesn't support all media applications so isn't an ideal solution.

**Comment by john-preston** [comment]
@qtist Is it possible to try a newer OS version? It should have a common API for different apps that wish to be controlled by media keys, looking like this:

![image](https://user-images.githubusercontent.com/17900494/141074014-91246a02-dc54-4036-ace5-d4a59a639281.png)

I don't know if it is the same on 10.13.

**Comment by qtist** [comment]
Thanks John. I guess Apple must have changed the API and Telegram no longer respects the older style, it has been fine for the last 5 years. I'm expecting my new machine to arrive in a week or 2 so I'll try it out on the new OS and I expect to close this issue then :)

**Comment by qtist** [comment]
No longer an issue on recent MacOS
