### ISSUE TITLE
High CPU usage spikes in group voice or video calls

### ISSUE THREAD

**Issue by pbaykalov** [telegramdesktop/tdesktop#16524]
### Steps to reproduce
1. Join group voice call or group video call (for me the problem happens regardless whether video is present or not).
2. Wait for a minute at most.
3. CPU usage will periodically spike approximately 30 seconds apart, for approximately 5 seconds each time.
4. CPU usage spikes end when I leave group voice/video call.

### Expected behaviour
The CPU usage should stay approximately same. (30% with video for me and some other background tasks)

### Actual behaviour
There are occasional 100% CPU usage spikes caused by Telegram, even if I set process priority to Idle. Every program almost stops responding when such spike occurs, Alt-Tab does not work, mouse cursor is very slow. There was nothing like this ever before 2.8.0.

### Configuration
**Operating system:**
Windows 10 2004, Core 2 Duo T9600.
**Version of Telegram Desktop:**
2.8.1 but I noticed it in 2.8.0 too (the one which introduced group video chats).
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Github Release long ago and undated in place ever since.
**Used theme**:
Classic.
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Eric-01** [comment]
> CPU usage spikes end when I leave group voice/video chat.

Could you please check if the CPU usage also drops after you unfocus the voice chat window?

**Comment by pbaykalov** [comment]
Yes it does, I was writing this issue with group call in background and could not do it.

**Comment by Eric-01** [comment]
Your issue looks similar to mine (reported as #16545), but you describe it a bit differently, and in my case the CPU usage never reaches 100%.

**Comment by pbaykalov** [comment]
> 
> 
> Your issue looks similar to mine (reported as #16545), but you describe it a bit differently, and in my case the CPU usage never reaches 100%.

Could be because you have quad thread CPU, mine is only dual thread.

**Comment by Eric-01** [comment]
My CPU is the legendary Core 2 Duo E8400, which has 2 cores and 2 threads as well, and is only a little better than yours.

**Comment by Eric-01** [comment]
My CPU has 2 cores and 2 threads as well, and is only a little better than yours.
