### ISSUE TITLE
[Windows] Crash loop on media viewer, AMD GPU

### ISSUE THREAD

**Issue by markuznw** [telegramdesktop/tdesktop#16521]
Hello, just reporting that even after updating to 2.8 and then consequently to 2.8.1 on win10 I'm having constant, if not always crashes as soon as I open a media or often even on group videocalls.
I guess this is due to using opengl which is known to have a super bad support by amd windows drivers (which are solved with vulkan but guess that'll take time/have other issues)

I've just submitted 2 crash reports from the app from the computer at work (rx570 + win10 like said) but the same happens also at home (5700xt + win10 latest).

Hopefully you can fix those, thank you for the work on tdesktop meanwhile :)

**Comment by john-preston** [comment]
The crashes are inside the graphics drivers indeed. You can disable OpenGL in Settings > Advanced > Performance, I'm afraid there is nothing else I can offer for now.

**Comment by Aokromes** [comment]
> Hello, just reporting that even after updating to 2.8 and then consequently to 2.8.1 on win10 I'm having constant, if not always crashes as soon as I open a media or often even on group videocalls.
> I guess this is due to using opengl which is known to have a super bad support by amd windows drivers (which are solved with vulkan but guess that'll take time/have other issues)
> 
> I've just submitted 2 crash reports from the app from the computer at work (rx570 + win10 like said) but the same happens also at home (5700xt + win10 latest).
> 
> Hopefully you can fix those, thank you for the work on tdesktop meanwhile :)

can you try searching for updated amd drivers?

**Comment by markuznw** [comment]
@Aokromes Sorry forgot to insert it into the first post, using latest ones 20.6.1 :)

**Comment by ilya-fedin** [comment]
You can try to use mesa: https://github.com/pal1000/mesa-dist-win/releases
Download mesa3d-21.1.3-release-msvc.7z, go to x64 folder or to x86 folder depending on the bitness of Telegram you're using (if you're using x64 version, that will be specified in the drawer, right after version), take `openglon12.dll`, `libglapi.dll` and `dxil.dll`, copy them to the folder with Telegram.exe, rename `openglon12.dll` to `opengl32.dll`, after restart Telegram should that shim OpenGL -> D3D12 layer, you can check log.txt to ensure that opengl is used or is it software fallback

**Comment by Ingwar121** [comment]
Also found on GeForce RTX 3070 Laptop. After starting video app causes graphics card troubles - screen blinks, explorer restarts and app crashes.
Laptop - ASUS TUF Dash F15 FX516PR-HN033, tg app version 2.8.1 x64

**Comment by markuznw** [comment]
> You can try to use mesa: https://github.com/pal1000/mesa-dist-win/releases
> Download mesa3d-21.1.3-release-msvc.7z, go to x64 folder or to x86 folder depending on the bitness of Telegram you're using (if you're using x64 version, that will be specified in the drawer, right after version), take `openglon12.dll`, `libglapi.dll` and `dxil.dll`, copy them to the folder with Telegram.exe, rename `openglon12.dll` to `opengl32.dll`, after restart Telegram should that shim OpenGL -> D3D12 layer, you can check log.txt to ensure that opengl is used or is it software fallback

Thanks, I've tried following your instructions and yeah, it crashes much less often but still does. Here is what it says in the logfile

`[2021.06.29 12:43:55] OpenGL Profile: Compatibility.
[2021.06.29 12:43:55] OpenGL Renderer: Radeon RX 570 Series
[2021.06.29 12:43:55] OpenGL Vendor: ATI Technologies Inc.
[2021.06.29 12:43:55] OpenGL Version: 4.6.14739 Compatibility Profile Context 21.6.1 27.20.22001.14011`

**Comment by Aokromes** [comment]
> @Aokromes Sorry forgot to insert it into the first post, using latest ones 20.6.1 :)

https://www.guru3d.com/files-details/amd-radeon-adrenalin-21-6-2-driver-download.html idk if this can help you

**Comment by ilya-fedin** [comment]
> It seems to me it still reports 21.6.1 (?) but dll files are placed and renamed

maybe you misunderstood something and renamed the wrong file

**Comment by ilya-fedin** [comment]
You can enable debug logs via `debugmode` cheat code and look at what Qt says about the library

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Dovchik** [comment]
> this bug is still valid?

Something similar started recently, a week ago maybe, when opening any image in full screen I got hard lags and eventually, video driver crashes.
