### ISSUE TITLE
[Question] Native version of Telegram

### ISSUE THREAD

**Issue by 0xF6** [telegramdesktop/tdesktop#16539]
Are you planning to develop a native version of Telegram using Project Reunion (WinUI 3) with new Fluent Design (Windows 11 apps like)?

As a like native application for macOS 🤔

_Perhaps the question is not for your team, but all the same, suddenly you are aware of such plans?_

**Comment by john-preston** [comment]
@0xF6 I'm not planning. Maybe Unigram can be transformed to such in an easy way.

**Comment by 0xF6** [comment]
Sad.

Unigram is not part of the Telegram development team, is it?

**Comment by john-preston** [comment]
@0xF6 Well, there is no way I can do that, because I have to maintain TDesktop.

**Comment by MarcAnt01** [comment]
@0xF6 just to clarify, Windows 11-like design is not available to WinUI 3 and Windows App SDK (formerly Project Reunion) is only for APIs, currently the whole Windows 11-like Fluent Design is built with UWP + WinUI 2.6 and is already available in Unigram to try it out.
