### ISSUE TITLE
Binary downloads are missing on https://desktop.telegram.org/

### ISSUE THREAD

**Issue by lemmy04** [telegramdesktop/tdesktop#16530]
The official downloads are missing

### Steps to reproduce
1. Try to download telegram 2.8.3 from the official website

### Expected behaviour
Downloads of telegram 2.8.3 should be available for all platforms

### Actual behaviour
2.8.3 is available only for Mac OS, all other downloads are still 2.8.1

**Comment by john-preston** [comment]
@lemmy04 2.8.2 and 2.8.3 were released only for macOS, because they were (2.8.2) attempting and (2.8.3) fixing a crash that happened only on macOS version.

**Comment by lemmy04** [comment]
oh well that explains it :)
