### ISSUE TITLE
icons of telegram

### ISSUE THREAD

**Issue by MarioTK** [telegramdesktop/tdesktop#1653]
Hi,
I have problems with icons of telegram in system tray of Lubuntu 15.10

**Comment by auchri** [comment]
and which problems? :unamused:

**Comment by MarioTK** [comment]
the icon is different from the usual.
![icon telegram](https://cloud.githubusercontent.com/assets/17342926/13186162/1d099cf2-d745-11e5-93bc-5731ac6e1c75.png)

**Comment by auchri** [comment]
See #1716
