### ISSUE TITLE
Scroll bar disappears

### ISSUE THREAD

**Issue by hookzof** [telegramdesktop/tdesktop#16537]
### Steps to reproduce
1. Launch Telegram, open a channel/chat where you can scroll down (see members, etc.)
2. Remove the right window by clicking on ![image](https://user-images.githubusercontent.com/22233835/123981550-0c20d980-d9cb-11eb-93cc-5ff10dc4093a.png)

3. Click on this icon again, and the scroll bar disappears
4. To reset this scroll bar state, press ![image](https://user-images.githubusercontent.com/22233835/123982306-949f7a00-d9cb-11eb-8369-8d638ffb3984.png)

### Expected behaviour
Scroll bar does not disappear
![image](https://user-images.githubusercontent.com/22233835/123981085-b9dfb880-d9ca-11eb-9ddb-f89a534f6c82.png)

### Actual behaviour
Scroll bar disappears. I only notice this on my laptop. Can't check it on my PC at the moment.

### Configuration
**Operating system:** Windows 10 64bit (21H1, 19043.1081) // 1366x768

**Version of Telegram Desktop:** 2.8.1 x64

**Used theme**: Night mode (default)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by hookzof** [comment]
Switching between different channels has the same effect.

**Comment by mvrogachev** [comment]
same for me at couple computers. it looks like this behavior is by design.
would be great if this can be adjusted.

**Comment by hookzof** [comment]
The problem is still relevant to them at the moment.
