### ISSUE TITLE
[Feature Request] Live Streaming Video Chat with Open Broadcast Software (OBS)

### ISSUE THREAD

**Issue by mikkyjekky** [telegramdesktop/tdesktop#16536]
request group video chat support using Open Broadcast Software (OBS) for live streaming

**Comment by zakiloki0** [comment]
Yes please

**Comment by FloPinguin** [comment]
Just use the OBS virtual webcam. Or do you mean something else?

**Comment by zakiloki0** [comment]
> Just use the OBS virtual webcam. Or do you mean something else?

Hmm yes, could be an option but how can we get sound from both (desktop and mic)?
