### ISSUE TITLE
Paste hyperlink from clipboard to telegram?

### ISSUE THREAD

**Issue by neznakomov** [telegramdesktop/tdesktop#16538]
How to paste preformatted text with hyperlinks and other things from anywhere (word, wordpress, browsers) to the telegram post?

**Comment by ilya-fedin** [comment]
you can't

**Comment by neznakomov** [comment]
> you can't

maybe there is a third party solution? 
at one time I used some kind of post scheduler service for this purpose, but that service was closed

**Comment by ilya-fedin** [comment]
I don't know one
