### ISSUE TITLE
[Question] How to enable 175% scalling on Windows?

### ISSUE THREAD

**Issue by tosziro** [telegramdesktop/tdesktop#16535]
How I can enable 175 % scalling on Windows? I only have 150% and 200%. 175% would be perfect.

**Comment by Aokromes** [comment]
use scale https://github.com/telegramdesktop/tdesktop/wiki/Command-Line-Switches

**Comment by tosziro** [comment]
hmm ok, thanks... but where I'm supposed to put this command on Windows?
