### ISSUE TITLE
[Feature Request] Support for `input_field_placeholder` from Bot API

### ISSUE THREAD

**Issue by harshil21** [telegramdesktop/tdesktop#16547]
### Is your feature request related to a problem?
The recent Bot API update (5.3) provided support for `input_field_placeholder` which replaces the text on the message box to [whatever you set it to](https://telegram.org/blog/animated-backgrounds#bot-menu). This works on Android and iOS, but not on TDesktop. Is there any chance it might come on TDesktop too?

**Comment by john-preston** [comment]
@harshil21 Yes, I hope to add it in one of the upcoming versions.

**Comment by harshil21** [comment]
This has been added in 2.8.6 beta, thank you!
