### ISSUE TITLE
VS 2019 x64 libraries build error in nuget_add_winrt

### ISSUE THREAD

**Issue by kirsan31** [telegramdesktop/tdesktop#16543]
Hi all. 2.8.4 fails to build (Windows, VS 2019 x64) with:
<pre>
Package "Microsoft.Windows.CppWinRT.2.0.210505.3" is already installed.
<b>CMake Error at cmake/nuget.cmake:87 (execute_process):</b>
  execute_process given unknown argument "COMMAND_ERROR_IS_FATAL".
Call Stack (most recent call first):
  Telegram/lib_base/CMakeLists.txt:242 (nuget_add_winrt)

...

Package "Microsoft.Web.WebView2.1.0.864.35" is already installed.
<b>CMake Error at cmake/nuget.cmake:87 (execute_process):</b>
  execute_process given unknown argument "COMMAND_ERROR_IS_FATAL".
Call Stack (most recent call first):
  Telegram/lib_webview/CMakeLists.txt:49 (nuget_add_winrt)
</pre>

In line 87 of `...\tdesktop\cmake\nuget.cmake` I see:

```cmake
execute_process(
COMMAND
    ${winrt_loc}/bin/cppwinrt
    /?
OUTPUT_FILE
    ${winrt_version_test}
COMMAND_ERROR_IS_FATAL ANY
)
```

After build attempt I have `cppwinrt.exe` by path `...\tdesktop\out\packages\Microsoft.Windows.CppWinRT\bin\` and it properly react on manual call like `cppwinrt.exe /?`.
Also, there is empty dir `...tdesktop\out\packages\gen\winrt\`
Any advice?

**Comment by john-preston** [comment]
@kirsan31 Does this happen with a clean out directory?

**Comment by c0re100** [comment]
It look like you're using old version of cmake, so update your cmake to 3.20.5
It should solve `nuget_add_winrt` issue.

**Comment by kirsan31** [comment]
@c0re100 thank you. Updating cmake from 3.17.2 to 3.20.5 have solved the problem.

@john-preston 

> Does this happen with a clean out directory?

Yea this was happing with clean build too. But as @c0re100 said the problem was in old cmake.

**Comment by john-preston** [comment]
@kirsan31 So this doesn't happen with new CMake? Pehaps the minimal version should be fixed in the root CMakeLists.txt then. For Windows at least. I'm not sure everyone in Linux world will be happy with near-the-latest minimal version.

**Comment by kirsan31** [comment]
@john-preston yes with latest CMake (3.20.5) everything is ok, but with 3.17.2 I was getting the above error all the time.

> Pehaps the minimal version should be fixed in the root CMakeLists.txt then. For Windows at least.

And / Or may be point it in the docs.

>  I'm not sure everyone in Linux world will be happy with near-the-latest minimal version.

Indeed.
