### ISSUE TITLE
[Wayland] [KDE-Plasma] Screencast Won't Work

### ISSUE THREAD

**Issue by TakuyaSama** [telegramdesktop/tdesktop#16546]
### Steps to reproduce
1. Launch/Open Telegram Desktop under Wayland session.
2. Enter a voice chat on any group which has it enabled.
3. Click on Screen Share.

### Expected behaviour
Screencast should start or at least, whatever it's supposed to appear, the configuration just previous to start the screenscast, or whatever.

### Actual behaviour
An error appears, showing that Screencast couldn't start, that had an error.

### Configuration
**Operating system:** GNU/Linux

**Version of Telegram Desktop:** 2.8.3

**Installation source (Linux Only)** Distribution Package

**Used theme**: Tinted

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Make sure you have Plasma 5.21 at least, AFAIK it's the minimum Plasma version that doesn't have bugs when screencasting on Wayland (e.g. I know for sure that Plasma 5.20 has a bug when screencasting the whole screen and is able to screencast only windows).

**Comment by TakuyaSama** [comment]
> Make sure you have Plasma 5.22 at least, AFAIK it's the minimum Plasma version that doesn't have bugs when screencasting on Wayland (e.g. I know for sure that both Plasma 5.20 and 5.21 have a bug when screencasting the whole screen and are able to screencast only windows).

Yeah, I use a Rolling Release distribution, so I have every updated to the latest stable release. Yeah, I tried it on Plasma 5.20 initially, a lot months ago, it worked only with Windows, with 5.21 it improved its behavior, I'm not sure that with Plasma 5.22, it improved in that, but I can't say it for sure.

I changed from PulseAudio as the audio server to fully PipeWire, but that didn't solve the issue.

**Comment by ilya-fedin** [comment]
>  I'm not sure that with Plasma 5.22, it improved in that, but I can't say it for sure.

So what Plasma version you reporting this on?

**Comment by TakuyaSama** [comment]
> So what Plasma version you reporting this on?

Plasma 5.22.2

**Comment by ilya-fedin** [comment]
I can't reproduce, screencast works just fine for me. Please provide more info about the issue.

**Comment by TakuyaSama** [comment]
I don't know what more info I could provide. I can attach a screenshot of the message I got every single time I click on the **Share Screen** button.
[Screenshot](https://imgur.com/a/BMSKzgE)

**Comment by ilya-fedin** [comment]
> I don't know what more info I could provide.

distro name and version. Could you please answer more frequently than once a day?

**Comment by TakuyaSama** [comment]
> distro name and version. Could you please answer more frequently than once a day?

Yeah, for sure.
Arch Linux, I provided the Telegram version firstly and KDE Plasma.
I'll try to answer ASAP I see your new comment.
Let me know.

**Comment by ilya-fedin** [comment]
> Arch Linux, I provided the Telegram version firstly and KDE Plasma

Make sure you have these packages installed:
```
xdg-desktop-portal
xdg-desktop-portal-kde
pipewire
```
And make sure pipewire service is running (`systemctl --user status pipewire`)

**Comment by TakuyaSama** [comment]
> Make sure you have these packages installed:
> 
> ```
> xdg-desktop-portal
> xdg-desktop-portal-kde
> pipewire
> ```
> 
> And make sure pipewire service is running (`systemctl --user status pipewire`)

OK, I knew I hadn't installed `xdg-desktop-portal`, either `xdg-desktop-portal-kde`.
That fixed this problem, sorry about that, it wasn't an issue, I was experiencing since the 2.8.x of Telegram Desktop too, another "issue", that wasn't, the file chooser in Telegram Desktop was really ugly, like really really old, (it remembered me to a really old of **Windows** GUI) because of the lack of those 2 packages, now it works again perfectly integrated to Qt/KDE Plasma.
Thank you very much and really sorry for the inconveniences.
Bests ^^.
