### ISSUE TITLE
Focused voice chat window always causes continuous high CPU usage

### ISSUE THREAD

**Issue by Eric-01** [telegramdesktop/tdesktop#16545]
### Steps to reproduce
1. Launch Telegram Desktop.
2. Join any existing voice chat or create your own.
3. Make sure the voice chat window is focused.
4. Observe continuous high CPU usage.

### Expected behaviour
CPU usage should remain low.

### Actual behaviour
Focused voice chat window always causes a continuous high CPU usage (on my hardware, it stays at around 50%). The number of participants, whether the participants are talking or not, and other circumstances don't seem to have any influence on this, it is rock-solid.

CPU usage by Telegram Desktop on my hardware when the voice chat window is focused (CPU usage is in the 4th column):

![Img1](https://user-images.githubusercontent.com/46398175/124162005-54f59280-da9e-11eb-85a0-ad85a741ab7c.png)

CPU usage by Telegram Desktop on my hardware when the voice chat window is unfocused:

![Img2](https://user-images.githubusercontent.com/46398175/124162434-b6b5fc80-da9e-11eb-8ba1-65ddf90af6f3.png)

Graph of CPU usage on all cores when Telegram Desktop is running:

![Img3](https://user-images.githubusercontent.com/46398175/124266780-b0279380-db37-11eb-8563-211b416c8478.png)
From left to right: the voice chat window unfocused, then focused, and then unfocused again.

I suppose that the culprit here is most likely the following fancy multi-layer button:

![Img4](https://user-images.githubusercontent.com/46398175/124160410-853c3180-da9c-11eb-913d-710e3439603a.png)

Why do I think so? Because if the voice chat window is unfocused (or animations are disabled in the settings), this button has a simplified design, and therefore the CPU usage remains low. As soon as the window is focused back, the button becomes fancy again, and the CPU usage raises instantly.

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 2.8.4, x64

**Used theme**: Day

**Comment by pbaykalov** [comment]
What CPU do you have?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16524 ?

**Comment by Eric-01** [comment]
> What CPU do you have?

Legendary Core 2 Duo E8400. Only a little better than yours.

**Comment by Eric-01** [comment]
> What CPU do you have?

Legendary Core 2 Duo E8400 (2 cores, 2 threads). Only a little better than yours.

**Comment by Eric-01** [comment]
Aokromes, I'm not sure if the linked issue is exactly the same as mine. In my case there aren't any CPU usage spikes caused by Telegram Desktop and it never reaches 100%. Instead, the CPU usage instantly raises to around 50% and stays there until I unfocus or close the voice chat window.

Graph of CPU usage when Telegram Desktop is running:
![Img4](https://user-images.githubusercontent.com/46398175/124182093-b1fd4280-dab6-11eb-8fad-3c3292d753e7.png)
Voice chat window unfocused, then focused, and then unfocused again.

**Comment by Eric-01** [comment]
Aokromes, I'm not sure if the linked issue is exactly the same as mine. In my case there aren't any CPU usage spikes caused by Telegram Desktop and it never reaches 100%. Instead, the CPU usage instantly raises to around 50% and stays there until I unfocus or close the voice chat window.

**Comment by Aokromes** [comment]
> Aokromes, I'm not sure if the linked issue is exactly the same as mine. In my case there aren't any CPU usage spikes caused by Telegram Desktop and it never reaches 100%. Instead, the CPU usage instantly raises to around 50% and stays there until I unfocus or close the voice chat window.

maybe your cpu is more powerfull than the other.

**Comment by Eric-01** [comment]
I have an update on this issue. Now in Telegram Desktop 2.8.11, the CPU usage has dropped significantly, and on the same hardware it now ranges between ca. 10-20% (10-15% with DirectX as the ANGLE backend, 15-20% with OpenGL, both with animations enabled).

Graph of CPU usage on all cores when Telegram Desktop 2.8.11 is running and DirectX is the set ANGLE backend:
![Img5](https://user-images.githubusercontent.com/46398175/126308081-ff8dd458-48a4-421f-a07c-f60a75ca6286.png)

**Comment by Eric-01** [comment]
I have an update on this issue. Now in Telegram Desktop 2.8.11, the CPU usage has dropped significantly, and on the same hardware it now ranges between ca. 10-20% (ca. 10-15% with DirectX as the ANGLE backend, ca. 15-20% with OpenGL, both with animations enabled).

Graph of CPU usage on all cores when Telegram Desktop 2.8.11 is running and DirectX is the set ANGLE backend:
![Img5](https://user-images.githubusercontent.com/46398175/126308081-ff8dd458-48a4-421f-a07c-f60a75ca6286.png)

**Comment by Eric-01** [comment]
I think now I can close this issue. The CPU usage by Telegram Desktop is not as bad right now (see my comment above) as it was when I first reported it.
