### ISSUE TITLE
Telegramdesktop massive memory usage, nearly 2GB atm

### ISSUE THREAD

**Issue by JackDinn** [telegramdesktop/tdesktop#16542]
How do i get my Linux Manjaro Telegram-desktop to clean up the memory usage better? i've seen it way over 3GB. I have only just noticed, so I'm not sure how high it will go or how quickly it goes up, but iv just re-started it, and it's already (1 hour) over 1.5GB

**Comment by john-preston** [comment]
@JackDinn Please fill the issue template, it has some required information, like the source of your Telegram Desktop installation.

**Comment by JackDinn** [comment]
Template? Where?

I dont know much, all i can say is i used the community package 

```
community/telegram-desktop 2.7.4-2 (24.6 MiB 66.7 MiB) (Installed)
    Official Telegram Desktop client
```
```
❰greg❙~/testdir❱✔≻ yay -Qi telegram-desktop
Name            : telegram-desktop
Version         : 2.7.4-2
Description     : Official Telegram Desktop client
Architecture    : x86_64
URL             : https://desktop.telegram.org/
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : hunspell  ffmpeg  hicolor-icon-theme  lz4  minizip  openal  ttf-opensans  qt5-imageformats  xxhash  libdbusmenu-qt5  kwayland  gtk3  glibmm  webkit2gtk
Optional Deps   : None
Required By     : None
Optional For    : purpose
Conflicts With  : None
Replaces        : None
Installed Size  : 66.66 MiB
Packager        : Sven-Hendrik Haase <svenstaro@gmail.com>
Build Date      : Sun 16 May 2021 01:10:58 BST
Install Date    : Mon 07 Jun 2021 17:52:58 BST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature


```

**Comment by john-preston** [comment]
@JackDinn Well, you can try the official binary from https://desktop.telegram.org

It is using a custom allocator (mallocng) and it should free the memory correctly.

**Comment by JackDinn** [comment]
Looks good so far. It's remaining under 160MB. I shall keep an eye on it and post again if it starts creeping up too much, but until then thank you :+1:
