### ISSUE TITLE
Telegram Desktop - Linux Flatpak unable to send files

### ISSUE THREAD

**Issue by mmiller7** [telegramdesktop/tdesktop#16559]
### Steps to reproduce
1. Install Telegram Flatpak
2. Open Telegram
3. Attempt to send a file

### Expected behaviour
The file will be sent

### Actual behaviour
If dragging and dropping, an error appears "Could not send empty file"
If clicking the "paperclip" and selecting a file, Telegram locks up and is unable to move, close, minimize, or anything.  Must reboot system to get it working again.

### Configuration
**Operating system:**
Linux Mint 20

**Version of Telegram Desktop:**
2.8.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Flatpak, installed via Mint Software Center

**Used theme**:
Light

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by soredake** [comment]
https://github.com/flathub/org.telegram.desktop/issues/23

**Comment by fighuass** [comment]
> [flathub/org.telegram.desktop#23](https://github.com/flathub/org.telegram.desktop/issues/23)

It's different from that. From what I get the issue that you linked is normal due to the nature of Flatpak, but what the OP mentions is an actual bug that results in Telegram freezing.
