### ISSUE TITLE
[Feature Request] Mac OS Big Sur style Telegram Icon

### ISSUE THREAD

**Issue by jimzenn** [telegramdesktop/tdesktop#16552]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
It's been quite some time since Mac OS Big Sur has been released, but Telegram for Mac OS still have a circular icon.
Let's use a new icon that fits the Big Sur icon design guideline.

**Comment by areiased** [comment]
I don't know for sure which icon the tdesktop version uses, but the other official Telegram app from the Mac App Store (which is made by a different team) already has a Big Sur style icon (or at least it really looks like it). Maybe tdesktop team could ask the mac app store telegram team about using the same icon or something

**Comment by Eric-01** [comment]
When working on this, I would really like to see some progress on #7891 as well.

**Comment by Aokromes** [comment]
it's intended by marketing team to difference telegram desktop from telegram telegram for macos.

**Comment by MatLegat** [comment]
You could differentiate both versions while following the macOS design guideline for both icons, and not just disregard those guidelines in one of them.
Example ([new icon source](https://macosicons.com/telegram)):
<img width="107" alt="image" src="https://user-images.githubusercontent.com/11902693/149399289-b7338a1e-79e1-4e9f-8c13-ec496352415d.png">
