### ISSUE TITLE
Telegram freezes when trying to download video

### ISSUE THREAD

**Issue by ottersarecool** [telegramdesktop/tdesktop#16553]
### Steps to reproduce
1. Have latest up to date Arch Linux installed
2. have Telegram from the repo installed in version 2.8.4
3. Go to any channel/room and try to save a video to your local drive

### Expected behaviour
The video should be downloaded and telegram should continue to function properly

### Actual behaviour
The kde file picker dialog opens, but becomes unresponsive the moment after it opened, when forcing to close the window telegram aswell is unresponsive and needs to be killed via taskmanager, no video was downloaded

### Configuration
**Operating system:** `Linux tyrus 5.12.14-arch1-1 #1 SMP PREEMPT Thu, 01 Jul 2021 07:26:06 +0000 x86_64 GNU/Linux`

**Version of Telegram Desktop:** 2.8.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: distribution package because of kde file picker compatibility

**Used theme**: default night mode

<details><summary><b>Logs</b>:</summary>
(telegram-desktop:5865): lib_base-WARNING **: 05:24:14.337: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
lib_base-Message: 05:24:14.338: This can be ignored by setting DESKTOP_APP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
lib_base-Message: 05:24:14.338: GTK integration can be disabled by setting DESKTOP_APP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to some features being unavailable.

(telegram-desktop:5865): Telegram-WARNING **: 05:24:14.338: Application was built without embedded fonts, this may lead to font issues.
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open

</details>

**Comment by ilya-fedin** [comment]
#16550
