### ISSUE TITLE
Upload freezes after getting the file

### ISSUE THREAD

**Issue by nnn19** [telegramdesktop/tdesktop#16555]
### Steps to reproduce
1.  In any of chat screen - click the file upload button
2.  Choose any of txt / image / pdf / etc
3.  And Click Open

### Expected behaviour
The choosen file will be uploaded into the chat screen.

### Actual behaviour
The Telegram screen freezes locking all the controls - nothing is clickable and nothing is typeable. The application does not respond at all.
As I started this Telegram Desktop through terminal,  I could see that there are no additional error messages.
Also, I could close the Telegram Desktop by pressing Ctrl + C.

All applications / libraries are updated very frequently.
All snaps are updated very frequently.

Please note that the issue popped up only 2-3 days back.
Also note that the issue is not there on installing the same through apt
telegram-desktop/focal-updates,now 2.1.7+ds-2~ubuntu20.04.1 amd64

### Configuration
**Operating system:** Ubuntu 20.04.2 LTS

**Version of Telegram Desktop:** snap 2.8.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: nstalled through snap install

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16550
