### ISSUE TITLE
Download / save does not work for around 2 months

### ISSUE THREAD

**Issue by nnn19** [telegramdesktop/tdesktop#16554]
### Steps to reproduce
1. While in any of chat screen
2. Right click a received file - be it pdf / txt / image / any 
3. Choose "Save file as" and select a folder.

### Expected behaviour
The same file with the same name should be saved under the selected folder.

### Actual behaviour
Does not save and there are no errors displayed in terminal when telegram-desktop is called from a terminal.

All applications / libraries are updated very frequently.
All snaps are updated very frequently.

Please note that the issue popped up only two months back.
Also note that the issue is **not there** on installing the same through **apt**
telegram-desktop/focal-updates,now 2.1.7+ds-2~ubuntu20.04.1 amd64 

### Configuration
**Operating system:**  Ubuntu 20.04.2 LTS

**Version of Telegram Desktop:** snap 2.8.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Installed through snap install

**Used theme**:

<details><summary><b>Logs</b>:</summary>
</details>

**Comment by ilya-fedin** [comment]
#16178
