### ISSUE TITLE
[Question] gclient is not recognized as an internal or external command

### ISSUE THREAD

**Issue by aliforever** [telegramdesktop/tdesktop#16551]
Hi. I'm building for Windows 10 x64, upon running the command:
`python scripts/bootstrap.py`

I receive:
```
'gclient' is not recognized as an internal or external command,
operable program or batch file.
failed command: "gclient config --name change2dot --unmanaged https://chromium.googlesource.com/angle/angle.git"
```
What should I do?

**Comment by john-preston** [comment]
@aliforever Sorry, the instructions aren't updated well for the angle, it is an experiment.

Here gclient is part of depot_tools, you can download and unpack them to ThirdParty and add to your PATH.

In the future perhaps there'll be a single repository with CMake build script, as tg_owt does. But not right now :(

**Comment by aliforever** [comment]
Thanks

> @aliforever Sorry, the instructions aren't updated well for the angle, it is an experiment.
> 
> Here gclient is part of depot_tools, you can download and unpack them to ThirdParty and add to your PATH.
> 
> In the future perhaps there'll be a single repository with CMake build script, as tg_owt does. But not right now :(

Thank you for the description. I installed depot_tools as you said. I'll continue with the rest of the commands. 🙏
