### ISSUE TITLE
[Uduntu, Unity] Telegram does not show message counter in Launcher 

### ISSUE THREAD

**Issue by crw614** [telegramdesktop/tdesktop#1656]
subj
OS Ubuntu 15.10, Unity. Telegram 0.9.24
![702032cff5](https://cloud.githubusercontent.com/assets/17346109/13191001/b64174fe-d771-11e5-814a-4ae884a82375.jpg)

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It should be fixed there (e.g. if 0.9.18 worked fine for you, this one should be working as well).

**Comment by crw614** [comment]
It work. 
Thank you.
