### ISSUE TITLE
Ctrl+A shortcut in text field doesn't work

### ISSUE THREAD

**Issue by rafalbednarczuk** [telegramdesktop/tdesktop#16563]
### Steps to reproduce
1. Write something in the text field
2. Press Ctrl+A (to select whole text)

### Expected behaviour
Whole text in the textfield is selected

### Actual behaviour
Nothing happens.

### Configuration
**Operating system:**
OS: Ubuntu 18.04.5 LTS x86_64 
DE: Unity:Unity7:ubuntu 

**Version of Telegram Desktop:**
2.8.4
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
snap
**Used theme**:
Night mode selected, nothing else changed in terms of theme.

It's broken from recently, a few days ago it was working.

**Comment by ilya-fedin** [comment]
can't reproduce, works juat fine

**Comment by rocka** [comment]
I can confirm this on KDE Plasma 5.22.2.

After pressing Ctrl + A , nothing in textfield is selected; but as soon as you unfocus the window, eg. switch to another window or minimize the window, the text got selected.

**Comment by ilya-fedin** [comment]
> It only happens when using KDE's Global Menu widget. If I remove the widget, Ctrl + A shortcut works fine.

Oh, custom global menu implementation was replaced with QMenuBar, probably it has a bug.

**Comment by Icenowy** [comment]
@ilya-fedin surely it's related to global menu, here global menu on MATE is not working too.

(BTW Unity 7 has global menu by default, so it should be the same reason)
