### ISSUE TITLE
French translation issue

### ISSUE THREAD

**Issue by guillaumecardon** [telegramdesktop/tdesktop#16564]
### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** :  2.8.4 x64

When you want to close Telegram, reduced in system tray, you need to right click on the icon.
In French, we have the label "Quit Telegram".
It should be "Quitter Telegram"

![image](https://user-images.githubusercontent.com/47170797/124419409-b0a17380-dd5d-11eb-84c3-2c2a39cb4599.png)

**Comment by MasterGroosha** [comment]
Are you sure you're using the official cloud translation?
I see the correct translation applied back in 2017: https://translations.telegram.org/fr/tdesktop/settings/lng_quit_from_tray

Try choosing another translation and reverting back to French then.

**Comment by guillaumecardon** [comment]
Yes it's good after changing language French -> English -> French.

However, i just download exe from the official website : https://desktop.telegram.org/, click on this button
![image](https://user-images.githubusercontent.com/47170797/124439540-d472b280-dd79-11eb-9c48-fae5c65644d4.png)

and install it.

No custom install or use of specific translation. Just basic usage.
