### ISSUE TITLE
Specific videos can cause TDesktop to allocate huge amounts of memory or even crash

### ISSUE THREAD

**Issue by Brawaru** [telegramdesktop/tdesktop#16576]
Telegram Desktop is prone to attacks using maliciously crafted videos.

### Steps to reproduce

1. Disable autoplay before the uploading the video
2. Upload the video linked below to any chat (e.g. saved messages)
3. Either enable autoplay or try playing the video in full screen

⚠️ **Do not click link below directly: Chromium browsers are as well affected by this issue.**
Hold <kbd>Alt</kbd> and [click here](https://user-images.githubusercontent.com/10401817/124730328-71307e00-df3b-11eb-8d9c-df7bb508826d.mp4) (or click with secondary (right) mouse button and select ‘Save link as’ in the context menu).

### Expected behaviour

Telegram Desktop would skip the malicious frames that it unable to render.

### Actual behaviour

Telegram Desktop tries to play every frame of the video and allocates huge amounts of memory (up to 5 GiB), which causes serious lags across the host system; worse if system decides to [swap](https://en.wikipedia.org/wiki/Virtual_memory) as this causes the massive disk I/O. The nature of the autoplay is that it repeats, effectively making Telegram Desktop a lag machine. I suspect in low memory conditions TDesktop will just crash. There also might be an issue on Linux low memory configurations as OOM Killer is known for being slow to respond, causing system to freeze<sup>[needs confirmation]</sup>.

![Windows 10 task manager screenshot for memory, a huge spike can be seen when malicious frames play](https://user-images.githubusercontent.com/10401817/124731128-282cf980-df3c-11eb-9601-e84ede042f5a.png)

### Configuration

**Operating system:** Windows 10 20H2 (19042)

**Version of Telegram Desktop:** 2.8.6 beta x64

*P.S. I'm sorry for the contents of the video 😄. This is one of the videos that was spreading across the Discord. Discord [managed to fix](https://github.com/discord/electron/commit/e78c6b3ef0f232ade85159f23bcbf893303dc4df) their crash within few days, there the video goes pitch black and stops playing now.*

**Comment by harshil21** [comment]
The same thing happens when opening it on chrome 😃

**Comment by Brawaru** [comment]
@harshil21 oops, I guess I have to put a disclaimer to not open the link 😄

I wonder how Discord fixed that then, giving that they're using Electron, which is Chromium as well...

**Comment by Nihal247** [comment]
> 
> ⚠️ **Do not click link below directly: Chromium browsers are as well affected by this issue.**
> 
Not only the Chromium browsers,  Firefox is well affected, however VLC media player plays the video.

**Comment by Eric-01** [comment]
> Not only the Chromium browsers, Firefox is also well affected, however VLC media player plays the video.

No, Firefox is not affected. It just refuses to play that video and displays a warning that the video is corrupted.

**Comment by Eric-01** [comment]
> Not only the Chromium browsers, Firefox is also well affected, however VLC media player plays the video.

No, Firefox is not affected. It just refuses to play that video and displays a warning that there is something wrong with the video.

**Comment by Brawaru** [comment]
@Nihal247, exactly as @Eric-01 said, Firefox will refuse to play this video and won't allocate any memory whatsoever. VLC player has a budget for frames as I understand, and while it will play the first frames, it will not render the malicious frames.

**Comment by Nihal247** [comment]
Yes @Brawaru, I realized there wasn't any memory spike when the video played in Firefox.

**Comment by Brawaru** [comment]
This is still an issue worth fixing.

**Comment by Brawaru** [comment]
Well, now people create crash emojis using the similar methods... but of course this bug is no longer relevant because imagine no one commenting on it for 30 days. Wow.

**Comment by Aokromes** [comment]
more 6 months. + 30 days after the bot asked.
