### ISSUE TITLE
Add Persian(فارسی) language to telegram desktop

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [telegramdesktop/tdesktop#1657]
Hi, I am web developer. I like to translate telegram desktop to Persian(فارسی). But one question: Telegram desktop support right to left languages?

**Comment by madl-ash** [comment]
Hello,i agree with @AmirHosseinKarimi ,as far as i know,translations are mostly done for Persian language,and as you(Telegram staff),a high percentage of your users are from Iran and this feature will be definitely welcomed by Iranian users.
i will help in translations and maybe coding as much as i can!

**Comment by AmirHosseinKarimi** [comment]
Oh, very good. But i think do not need coding. I downloaded **[lang.strings](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/Resources/lang.strings)** and translated 1/3 of strings to Persian. But problem is: Telegram desktop support right to left language?

**Comment by auchri** [comment]
@AmirHosseinKarimi you can try it by pressing <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>alt</kbd> + click on `Change language` in the settings

**Comment by telegramdesktop** [comment]
@AmirHosseinKarimi Not yet, sorry.

**Comment by AmirHosseinKarimi** [comment]
Hi, At this time telegram desktop do not support right to left languages yet?
When this feature will add?

**Comment by auchri** [comment]
#1387
