### ISSUE TITLE
Ctrl+[any letter] not working properly?!?

### ISSUE THREAD

**Issue by MaxMatti** [telegramdesktop/tdesktop#16575]
### Steps to reproduce
1. Open chat field or search field, type something in
2. Hit any of the key combinations Ctrl+A, Ctrl+X, Ctrl+C, Ctrl+V, etc

### Expected behaviour
Key combination working immediately

### Actual behaviour
Nothing happens, only after pressing right click and releasing the mouse button again the actions (select all, cut, copy, past, etc) are executed.

### Configuration
**Operating system:** Archlinux with KDE

**Version of Telegram Desktop:** 2.8.4

**Installation source:** AUR

**Used theme**: Amoled Black Theme

Nothing appears in the logs and this issue does not occur with other Qt-Applications (tested with the KDE system settings).

**Comment by ilya-fedin** [comment]
#16563
