### ISSUE TITLE
[Question] Release 2.8.5 (beta?) not present under releases on GitHub

### ISSUE THREAD

**Issue by bearmannl** [telegramdesktop/tdesktop#16572]
Hi,

I received an update for my desktop client, was on 2.8.4, now it's updated to version 2.8.5 (beta it would appear). Neither a stable nor beta release of this version is present in the GitHub repo releases.

Also, as mentioned in #16506, the changelog on the website doesn't mention a new version.

Cheers

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v2.8.5
