### ISSUE TITLE
TDesktop freezes when pasting images copied from TDesktop itself

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#16577]
### Steps to reproduce
1. Send any image to any Telegram chat
2. Copy that image to clipboard
3. Paste it to any Telegram chat

### Expected behaviour
You should see that image ready to be sent

### Actual behaviour
TDesktop freezes for 10-30 seconds before showing image preview ready to be sent

### Configuration
**Operating system:** Manjaro KDE
**Version of Telegram Desktop:** 2.8.6 beta
**Installation source (Linux Only)**: GitHub

**Comment by Aokromes** [comment]
cannot confirm on telegram desktop 2.8.6 + windows 11 trying to paste into paint.

**Comment by MasterGroosha** [comment]
@Aokromes what does Paint have to do with this issue? Could you try the following: send an image to saved messages, then copy it and try to send again. When you paste it the second time, you'll get a freeze

**Comment by Aokromes** [comment]
> @Aokromes what does Paint have to do with this issue? Could you try the following: send an image to saved messages, then copy it and try to send again. When you paste it the second time, you'll get a freeze

you said "paste it somewhere" so, i pasted it on paint xd if you mean "paste it into another telegram chat" cannot reproduce too.

**Comment by MasterGroosha** [comment]
@Aokromes ah, my bad, I've edited issue text, thank you!

Maybe it's Linux-specific issue

**Comment by NotStatilko** [comment]
Hello. There is also same issue with pasting Screenshot maded with **Debian 10 XFCE 64bit 2GB RAM** from clipboard. Sometimes it didn't paste at all, and sometimes the whole system hangs for > 1 minute. Telegram v2.8.1.

I don't know is this PR fixes this, but maybe worth to mention it.
