### ISSUE TITLE
[Feature Request] Disable notifications about users leaving/joining the channel

### ISSUE THREAD

**Issue by Kakadu** [telegramdesktop/tdesktop#16570]
It would be great to configure channels separately in that way. Having a switch would introduce less noise when spammers joining channel and try to do something.

### Is your feature request related to a problem?
Not a problem, but inconvenience

### Describe the solution you'd like
Having a checkbox per channel to configure it

### Describe alternatives you've considered
I tried to google it but only get discussion about notifications when users join the Telegram. i.e. it is not per-channel setting.

**Comment by RememberTheAir** [comment]
You're talking about groups, not channels, right?

Anyway, such a feature, if it ever is introduced, should be available on all apps, not just tdesktop. I suggest you to bring it to https://bugs.telegram.org (actually such a request already [exists](https://bugs.telegram.org/c/2359))

Reference issue here: #10048

**Comment by Kakadu** [comment]
Thanks, I liked all feature requests that I found there. Should I close this one?
