### ISSUE TITLE
Stickers and Images are not loading after update.

### ISSUE THREAD

**Issue by Kgf123** [telegramdesktop/tdesktop#16589]
### Steps to reproduce
1. Updated telegram
2. Tried to open an Image.
3. Tried to look at sticker.

### Expected behaviour
Tell us what should happen
The photos should automatically download and be visible.
![image](https://user-images.githubusercontent.com/79869936/124882154-b7deb080-dfed-11eb-82ee-322ebed66734.png)
The stickers should be visible too.
![image](https://user-images.githubusercontent.com/79869936/124882062-a4334a00-dfed-11eb-91fc-bbc842def8fe.png)

### Actual behaviour
Tell us what happens instead
The photos keep buffering but never download.
Stickers never load even though I have 300Mbps internet speed.

### Configuration
**Operating system:** Windows 7 Ultimate, Version 6.1 (Build 7601: Service Pack 1)

**Version of Telegram Desktop:** v 2.8.4

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Telegram default night mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Austin70** [comment]
Same..most images are not opening but i think for me it was already there before the latest update..started yesterday i think

**Comment by ilya-fedin** [comment]
bruh, you created a duplicate even though the previous issue (#16588) is also about the same problem
