### ISSUE TITLE
[PLASMA 5] Opening a photo blocks the window

### ISSUE THREAD

**Issue by qmmp123** [telegramdesktop/tdesktop#16586]
### Steps to reproduce
1. Open telegram
2. Make it visible in all workspaces
3. Find photo and open it
4. Change workspace
5. You are not able to make something with window while photo is opened

### Expected behaviour
I don't know. I think photo should be opened in all workspaces or clicking in window should close photo

### Actual behaviour
You are not able to make something with window while photo is opened

### Configuration
**Operating system:** Linux archlinux 5.12.14-arch1-1

**KDE Plasma version:** 5.22.3

**Version of Telegram Desktop:** 2.8.6 beta

**Installation source (Linux Only)** - flatpak

**Used theme**: default in night mode

**Comment by ilya-fedin** [comment]
This is intended, media viewer is modal
