### ISSUE TITLE
Hide archived chats

### ISSUE THREAD

**Issue by zakiloki0** [telegramdesktop/tdesktop#16582]
Why on Telegram Desktop can't hide the archive chats folder while on Android it keeps hide unless you swype the screen to see it?

**Comment by RememberTheAir** [comment]
Right click on the archive -> collapse/hide in the side menu

**Comment by zakiloki0** [comment]
> Right click on the archive -> collapse/move to main menu

Oh! Thank you :D 

More better now haha.
