### ISSUE TITLE
contract not save

### ISSUE THREAD

**Issue by zakiloki0** [telegramdesktop/tdesktop#16584]
When you collapse the list of chats and only the images are seen, minimizing and reopening Telegram does not save the contraction.

Linux client.

I mean this (the left avatars) Image of example: 

https://user-images.githubusercontent.com/3866418/36790417-bef114fa-1c62-11e8-9bfa-e7d7f6a99402.png

**Comment by ilya-fedin** [comment]
What do you mean by 'does not save the contraction'?

**Comment by Aokromes** [comment]
he means it doesn't remember collapse of chats.

**Comment by ilya-fedin** [comment]
> he means it doesn't remember collapse of chats.

Maybe I don't understand something, I clicked on the minimize button and then restored from taskbar, the bar is still thin

**Comment by zakiloki0** [comment]
> > he means it doesn't remember collapse of chats.
> 
> Maybe I don't understand something, I clicked on the minimize button and then restored from taskbar, the list is still thin

Yes, that works. But I mean when you clic on close button and Telegram go to system tray icon, when you open again, it not save.

**Comment by ilya-fedin** [comment]
It saves, just open any chat and it will return to the previous size

**Comment by zakiloki0** [comment]
> It saves, just open any chat and it will return to the previous size

Thank for response ilya.

There is no way that the contraction remains permanent without necessarily having to open a chat?

**Comment by ilya-fedin** [comment]
No, this seem to be an intended design solution. I.e. you won't ever need the list to be thin since there's a lot of empty space.

**Comment by zakiloki0** [comment]
> No, this seem to be an intended design solution. I.e. you won't ever need the list to be thin since there's a lot of empty space.

I understand. A shame :(. Thanks for your help, I appreciate it.
