### ISSUE TITLE
Telegram 0.9.24 Not working on Ubuntu 15.10 x64!

### ISSUE THREAD

**Issue by maryayi** [telegramdesktop/tdesktop#1658]
after updating to version 0.9.24 I can't run Telegram desktop on Ubuntu 15.10 x64
I receive this error message:

> Last time telegram desktop was not closed properly

p.s: I found a bad solution! it just worked when I run Telegram with root permission! but I can't run it normally!

**Comment by telegramdesktop** [comment]
@maryayi Looks like that one? https://github.com/telegramdesktop/tdesktop/issues/1630#issuecomment-186337155

I'm looking for help there (testing).

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It should be fixed there (e.g. if 0.9.18 worked fine for you, this one should be working as well).

**Comment by maryayi** [comment]
yeah ... problem fixed! thanks
