### ISSUE TITLE
Telegram hangs for quite a few seconds when copying and pasting images to itself.

### ISSUE THREAD

**Issue by tarcisioe** [telegramdesktop/tdesktop#16587]
### Steps to reproduce
1. Copy an image from Telegram itself.
2. Paste it on any chat.

### Expected behaviour
The image should be pasted instantly as before.

### Actual behaviour
Telegram hangs for a few seconds, CPU usage goes high after some time, window is completely unresponsive, then the image dialog pops up. I have observed this on two different machines and have been told the same happened for some friends since 2.8.6 beta was released. They were also on Linux although I am unsure of the distribution.

Video of behaviour (Image is pasted by Ctrl+V right after copying. Same behaviour happens by right-clicking and selecting "Paste".):

https://user-images.githubusercontent.com/774694/124881477-c0ab9400-dfa5-11eb-9ce7-848a085d7396.mp4

### Configuration
**Operating system:**
Arch Linux

**Version of Telegram Desktop:**
2.8.6 beta

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official Website

**Used theme**:
Custom, but doesn't seem to be relevant here.

**Comment by Aokromes** [comment]
it's fixed on dev.
