### ISSUE TITLE
Telegram Desktop app not loading images and not shwoing Emoji

### ISSUE THREAD

**Issue by VikasGutte** [telegramdesktop/tdesktop#16591]
### Steps to reproduce
1. Open Telegram PC App
2. Open any group/channel
3. Send emoji/image
4. not showing Emoji and Image, also not showing group/channel Icon

### Expected behaviour
It should show Emoji and Image

### Actual behaviour
Not showing Emoji and Image, also not showing group/channel Icon

### Configuration
**Operating system:** Windows 10Pro 64bit

**Version of Telegram Desktop:** 2.8.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: No theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

Image not showing (it's not network issue)

![image](https://user-images.githubusercontent.com/30354348/124951144-b5ea1100-e030-11eb-90d4-e15116fc47da.png)

Group/Channel icon not showing

![image](https://user-images.githubusercontent.com/30354348/124951196-bf737900-e030-11eb-8694-e97f2217b433.png)

Emoji Not showing

![image](https://user-images.githubusercontent.com/30354348/124951254-ce5a2b80-e030-11eb-91fc-b0719faa7eeb.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16588
