### ISSUE TITLE
No code received on mobile phone for login on desktop computer/laptop

### ISSUE THREAD

**Issue by sdwien** [telegramdesktop/tdesktop#16590]
### Steps to reproduce
1. Log out of Telegram Desktop after a successful Telegram session (user is not logged in on any other device) 
2. Restart Telegram Desktop
3. Enter country code and mobile phone number
4. Press "Send code via sms"
5. Wait to receive the code via sms, but nothing arrives (phone is a non-smartphone well connected in the local network of the same county for which it is registered = no roaming; no possibility to install apps or to scan QR codes on the phone).
5a. During some attempts, "internal sever error" shows 
### Expected behaviour
Until now, the 5-digit code was sent to this very same phone and phone number whenever pressing "send code via sms".

### Actual behaviour
No code is received, although mobile phone is connected to the mobile network of the same country where it is registered.

### Configuration
**Operating system:** Ubuntu 18.04.5 LTS and Debian 11

**Version of Telegram Desktop:** Tried with 2.8 and today also with 2.5, both versions are not working in this regard. Last time it worked (=code was sent to this phone) was May 12, 2021, then did not use it again until July 7, 2021.

**Installation source (Linux Only)** - the official website / GitHub releases

**Used theme**: default

**Comment by Aokromes** [comment]
api side

**Comment by surabibio** [comment]
Adding insult to injury, now I get the message "If you haven't signed up for Telegram yet please register from your phone or tablet first" This means non-smart phone users with a valid mobile number cannot use telegram. Absolute bumper. I was using telegram without issues on my windows 10 for 2 years. I formatted my hard disk. Now I cannot log into my telegram account, because no SMS comes to my mobile phone which is a basic Nokia phone. I see excuses like Server issue, API issue. But for a user I am dejected.

**Comment by Aokromes** [comment]
> Adding insult to injury, now I get the message "If you haven't signed up for Telegram yet please register from your phone or tablet first" This means non-smart phone users with a valid mobile number cannot use telegram. Absolute bumper. I was using telegram without issues on my windows 10 for 2 years. I formatted my hard disk. Now I cannot log into my telegram account, because no SMS comes to my mobile phone which is a basic Nokia phone. I see excuses like Server issue, API issue. But for a user I am dejected.

i know you don't like the answer, but there is nothing preston or anyone on this bug tracker can do, the change was done server side.
some people said with kotatogram you can login on desktop without mobile phone application.

**Comment by surabibio** [comment]
Thanks. That was very kind.  BTW what it the cooling period for too many unsuccessful login attempts. I keep getting the message, "Too many tries. Pease try again later." for past 24 hours. How long exactly is "try again later"?

**Comment by Aokromes** [comment]
> Thanks. That was very kind. BTW what it the cooling period for too many unsuccessful login attempts. I keep getting the message, "Too many tries. Pease try again later." for past 24 hours. How long exactly is "try again later"?

i cannot answer that, i sugest you to wait a day.

**Comment by surabibio** [comment]
Kotatogram was able to send an SMS to my non-smart phone and I got back my account and am now able to connect again with friends. As a token of gratitude I will continue to use Kotatogram. Thanks Aokromes for your boundarylessness.

**Comment by surabibio** [comment]
If Kotatogram could work why not Telegram. I don’t believe it could be an API / server side issue.
By insisting that a new use first register from his smart phone you walking away from device and OS neutrality.
It is not a sin. Do you want to do that?

**Comment by Aokromes** [comment]
> If Kotatogram could work why not Telegram. I don’t believe it could be an API / server side issue.
> By insisting that a new user first register from his smart phone you are walking away from device and OS neutrality.
> It is not a sin! Do you want to do that?

it's marketing team decision, preston cannot do nothing.
p.s. kotatogram lacks new features like group video calls.
