### ISSUE TITLE
All messages on the left side

### ISSUE THREAD

**Issue by dentex** [telegramdesktop/tdesktop#1659]
Since v0.9.24 stable (16.02.16), on a given chat, I have all messages on the left side.

OS: Linux Mint 17.3 - 3.13.0-37-generic x86_64
ASUS Notebook N751JK

![sch](https://cloud.githubusercontent.com/assets/2931982/13196991/0724231c-d7e0-11e5-89f0-2a49b43edd29.png)

(Anyway, thanks for the great application)

**Comment by dentex** [comment]
Sorry I didn't search deeper. I actually searched only into open issues.
I also found that narrowing the window, my messages pop to the right side... witch is better.

Thanks,
Bye

**Comment by auchri** [comment]
#1587 is open

**Comment by dentex** [comment]
Thanks.
Il 20/feb/2016 05:10 PM, "auchri" <notifications@github.com> ha scritto:

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.
