### ISSUE TITLE
[Feature Request] Reorder messages that were not read yet

### ISSUE THREAD

**Issue by curala70** [telegramdesktop/tdesktop#16595]
### Is your feature request related to a problem?
Sometimes I write some messages to a person and afterwards I notice, that another order of the messages would be better.

### Describe the solution you'd like
Ability to reorder messages via Drag 'n Drop. The timestamps can stay the same (no reordering of the timestamps -> Rather a new assignment of the timestamps to the reordered messages).

### Additional context
No reordering allowed anymore, if the messages have been read.

**Comment by MasterGroosha** [comment]
This would require changes to API for all apps rather than TDesktop, so it would fit better to https://bugs.telegram.org
Also why don't just edit these messages appropriately?

**Comment by RememberTheAir** [comment]
Such a request belongs to https://suggestions.telegram.org because this would be expected to be available on all apps
