### ISSUE TITLE
[Feature Request] Monochrome Tray Icon option for Mac OSX

### ISSUE THREAD

**Issue by artdarek** [telegramdesktop/tdesktop#166]
Please add monochrome icon option for Mac OSX...

**Comment by slavaveto** [comment]
Please, tell me, can i use my own tray icon?
If i knew icon location i could change it...
Thanks in advance!

**Comment by john-preston** [comment]
@slavaveto I'm afraid there is no way to do so, the icon is embedded in the binary.

**Comment by slavaveto** [comment]
it's a pity((

**Comment by ManuelSchneid3r** [comment]
Please use the same colorcode for the tray icon the system uses.

<img width="281" alt="bildschirmfoto 2016-07-14 um 16 49 38" src="https://cloud.githubusercontent.com/assets/3252315/16844272/c813974e-49e4-11e6-8078-720bd8701456.png">

The icon looks somewhat highlighted.
