### ISSUE TITLE
[Feature Request] Message Text Size Slider in tdesktop (linux) app

### ISSUE THREAD

**Issue by specs32** [telegramdesktop/tdesktop#16602]
### Is your feature request related to a problem?
Cannot read Text, text is too small. If I scale interface, application does not fit on my Desktop anymore and does not respect desktop boundaries.

### Describe the solution you'd like
Message Text Size Slider in Chat settings. Like the Android App.

### Describe alternatives you've considered
Much larger Screen. (Which I don't have)

### Additional context
By popular demand !

**Comment by ilya-fedin** [comment]
#90

**Comment by specs32** [comment]
https://github.com/telegramdesktop/tdesktop/issues/90 is about choosing fonts and stuff.. I don't need / want that. I suggested implementing the chat text size slider like in the mobile app.

**Comment by ilya-fedin** [comment]
"Allow user to choose font and font size", you requesting to change text (font) size

**Comment by specs32** [comment]
I don't care for the Font face, just the Size, Is there a reason why the Desktop app doesn't have the text size Slider in the Settings -> Chat Options like the Mobile App ?
I am sorry to ask, because I can Imagine this question has been asked a lot over the past 6 Years since #90 was opened .. But I couldn't find an explanation. Also #90 is locked so I cannot post there. Maybe explaining that in #90 would be a good thing... It really is difficult to understand. (for me at least)

**Comment by ilya-fedin** [comment]
Only @john-preston knows
