### ISSUE TITLE
Telegram-desktop, can't login using phone number

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [telegramdesktop/tdesktop#16604]
### Steps to reproduce
Open telegram desktop, enter your phone number to receive code

### Expected behaviour
You should receive the activation code

### Actual behaviour
Nothing is happening, no code is being received via sms

### Configuration
**Operating system:**
Arch Linux 

**Version of Telegram Desktop:**
telegram-desktop 2.8.4-3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official website

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/4239
