### ISSUE TITLE
Unread messages counter badge on taskbar icon malformed or missing at 200% system's interface scaling

### ISSUE THREAD

**Issue by DanyGee** [telegramdesktop/tdesktop#16605]
### Steps to reproduce
1. Launch TG
2. Get new message
3. Observe the taskbar icon (not the systray icon)

### Expected behaviour
Telegram's taskbar icon should show a badge with unread messages counter.

### Actual behaviour
Badge gets malformed or missing, depending on the distro used, when system's interface scaling is set to 200%.

### Configuration
**Operating system:**
Zorin OS 16 BETA - badge malformed at 200% system scaling, OK at 100% scaling.
Mint 20.2 (Cinnamon) - badge missing completely on both 100% and 200%.

**Version of Telegram Desktop:** 2.8.6 BETA

**Installation source (Linux Only):** the official website

**Used theme**:
Icon theme - Papirus (Zorin, Mint)
Shell theme - ZorinBlue-Light [GTK2/3] (Zorin) / Mint-Y-Dark (Mint)

**Screens from Zorin OS**
200%
![Screenshot from 2021-07-08 14-07-47](https://user-images.githubusercontent.com/26818551/125201130-0a2e0480-e26e-11eb-9008-05b96e6ccd4a.png)

100%
![Screenshot from 2021-07-11 15-11-32](https://user-images.githubusercontent.com/26818551/125201143-15813000-e26e-11eb-9db5-19ed83d46a7e.png)

**Additional comments**
Please help determine if it is distro or TG specific problem.

**Comment by ilya-fedin** [comment]
This badge is drawn by your panel, tdesktop only sets the digit via dbus
