### ISSUE TITLE
[Feature Request] Show Savegif option by right-clicking in the comments of the channel posts

### ISSUE THREAD

**Issue by M0H4MM4D0UTIS** [telegramdesktop/tdesktop#16609]
### Is your feature request related to a problem?
Show Savegif option by right-clicking in the comments of the channel posts
This button is currently only displayed for in-group or channel gifs
If you enter the comments section of a post on a channel, this button is not in the right-click list (when you right-click on a gif)

**Comment by ilya-fedin** [comment]
#8739
