### ISSUE TITLE
The "disable proxy" option does not work if a proxy is set in IE

### ISSUE THREAD

**Issue by Baltazar500** [telegramdesktop/tdesktop#16600]
### Steps to reproduce
1. Enable the "disable proxy" option
2. Set real or fake proxy in IE settings
3. Restart telegram
4. In addition. When using a "fake" proxy, minimize the telegram to the tray and send the PC to standby mode, then return it from it

### Expected behaviour

The "disable proxy" option should ignore the system proxy (IE) and not switch to it in any case

### Actual behaviour

The "disable proxy" option does not work if a proxy is set in IE. When the "disable proxy" option is enabled, instead of the "Default (TCP Used)" connection type, "Default (HTTP Used)" is displayed in the proxy settings. 

Telegram goes through this proxy! 

If the proxy does not exist (127.0.0.1: random port), the connection goes into a loop. After exiting the standby mode, the telegram hangs when using the "fake" proxy.

### Configuration
**Operating system: Win 7 x64**

**Version of Telegram Desktop: 2.8.1**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

![SNAGIT_2021 07 10_05 14 46_0010](https://user-images.githubusercontent.com/12525093/125127880-8e826980-e140-11eb-9c8b-5a04467bd79f.jpg)
![SNAGIT_2021 07 10_05 14 53_0011](https://user-images.githubusercontent.com/12525093/125127893-93dfb400-e140-11eb-9856-6417af042c64.jpg)

**Comment by sirweazel** [comment]
I also have this same issue.  Upon Telegram startup, it does not ignore the "disable proxy" setting.  Win 10 with a system proxy set via internet options.  But if you, toggle the check box back and forth, it will then use the "disable proxy" setting.  It's almost like upon startup, it is not reading the setting correctly and toggling the options initiates the proper config.  I'm not sure how else to describe it.  Noticed this a couple weeks ago, and there have been 3-5 updates since i noticed it all with the same issue.  This started occurring after one of the updates, but i'm sorry i don't remember which version had the regression.

**Comment by Baltazar500** [comment]
@sirweazel, You do not remember the version?  I would like to roll back to it.  Earlier, before updated at 2.7.4/2.8.1, I used version 1.5.3.

**Comment by sirweazel** [comment]
@Baltazar500 , no i didn't pay attention to version numbers. But i'm usually updated, so it had to be a "recent" version.  When I get some time, maybe this weekend, I'll try reverting back to the last 10 or so versions to see if i can replicate and determine where the regression occurred.  My plan is to grab the last 10 or so portable versions and just try each one stepping back a version until the functionality is restored.  I just need to find the time, lol.  It won't be today, but hopefully in the next couple.  I guess i first need to check that the issue exists in the portable version, but i'm going to assume it does for now.

**Comment by Baltazar500** [comment]
I rolled back to 2.4.0 and update the build every ~ + 10 releases checking for a "proxy" problem after exiting standby mode. There were no problems until build 2.7.3 (including 2.7.3 itself) `*facepalm*`

**Comment by john-preston** [comment]
2.7.4 is the first one broken? 2.7.3 works as expected? I don't see anything in git log for that version and the proxies :(

**Comment by Baltazar500** [comment]
>2.7.4 is the first one broken? 2.7.3 works as expected? I don't see anything in git log for that version and the proxies :(

After my first update from 1.6.3 to 2.7.4, I got a problem with the proxy, which remained in new releases. Before build 2.7.4, there is no problem :( And the fact that nothing is indicated in the changelog about proxy changes does not mean that they were not made

**Comment by Aokromes** [comment]
> > 2.7.4 is the first one broken? 2.7.3 works as expected? I don't see anything in git log for that version and the proxies :(
> 
> After my first update from 1.6.3 to 2.7.4, I got a problem with the proxy, which remained in new releases. Before build 2.7.4, there is no problem :( And the fact that nothing is indicated in the changelog about proxy changes does not mean that they were not made

try downloading 2.7.3 portable and test if it works there, if it doesn't try lower versions.

**Comment by sirweazel** [comment]
Thank you, i never followed through with testing the various versions like i wanted to. I'll give 2.7.3 portable a test.  You did what i wanted to do, but i never took the time as other things have just taken priority.

**Comment by sirweazel** [comment]
I just tested 64bit portable 2.7.3 and 2.7.4 and did not see the issue.  I'll try the 32bit later on and see if that has an effect. Both times with the proxy set to disabled, upon startup and shutdown of the portable version it honored the disabled proxy.

**Comment by Baltazar500** [comment]
>@Aokromes, try downloading 2.7.3 portable and test if it works there, if it doesn't try lower versions.

I used portable all the time and after a rollback I upgraded versions from 2.4.0 to 2.7.3 (update the build every ~ + 10 releases checking for a "proxy" problem after exiting standby mode)

>@sirweazel, I just tested 64bit portable 2.7.3 and 2.7.4 and did not see the issue. I'll try the 32bit later on and see if that has an effect.

The problem is not stable. Often occurs when exiting standby mode (with saved proxy settings in IE, without modification after system startup). 

Win 7 x64, Telegram portable x64 2.7.4 or higher

**Comment by Baltazar500** [comment]
`Damn it. 2.7.3 does not change proxy parameters in the settings, but hangs when exiting standby mode with fake proxy enabled in IE (127.0.0.1: random port). I will roll back again -> 2.7.2 -> ...`

`>_<`
