### ISSUE TITLE
Search doesn't find matches that only differ in accents

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#16603]
The Telegram app (at least the Android version) shares this issue, so I'm not entirely sure whether the issue is on the client side (meaning that both the app and the desktop application have the same bug) or if it's on the server side. If it's the latter, please report this to the folks responsible for that.

All modern search engines, everywhere (e.g. browsers' "find in page", Google, mysql with the default unicode collations, ...) consider characters that only differ in accents to be the same characters for string matching purposes.

That is, for example, when you search for "maria", "maría" matches, and viceversa. Properly matching "equivalent" characters or character sequences gets a little more complex and depends on the language, but the wheel has been invented already, and anyway, anything short of matching characters that only differ in accents/tildes is unacceptable.

### Steps to reproduce
1.  Open a chat where the word "Lucía" appears in at least one message
2.  Search for "Lucia"

### Expected behaviour
The message where the word "Lucía" appears (with an accent on the i) should be found.

### Actual behaviour
It's not.

### Configuration
**Operating system:** Linux (OpenSUSE Tumbleweed)

**Version of Telegram Desktop:** 2.8.1

**Installation source (Linux Only)** - the official website 

**Used theme**: No idea, can't find in Settings. I don't think it's relevant anyway.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
such bug belongs to https://bugs.telegram.org/
