### ISSUE TITLE
Add "Reply to Privately" Feature in Group Chats

### ISSUE THREAD

**Issue by landry314** [telegramdesktop/tdesktop#16617]
Whatsapp has a feature when you select a message in a group chat where you can "Reply Privately" and it quotes the message in a new message to that person directly.

Quite often you need to direct message someone in response to a message in a group chat. In Telegram you need to click on the face of the user then the new message button on the right. This is not immediately obvious how to do this but even once you learn it you still are left with no quote of the message which forces you to explain what you are referring to. This slows down our communication time and hurts the user experience.

Quoting a message to someone directly is a great feature and it is glaringly missing from Telegram. Whatsapp sucks but this is one thing I really miss about it.

It probably should be called something different like:

Reply to Privately
Reply to Directly
Quote to Privately
Quote to Directly
Message Directly with Quote
Message Privately with Quote

This would enhance the user experience not just by allowing quoting but also by making it quicker to direct message someone. Right now it is a bit obfuscated how to do this. It should be a easy thing that quickly opens a private message to someone in a group. This is something I do quite often.

Finally, the quoted portion should link back to the group. In Whatsapp this is exactly what happens so the recipient of the message can quickly look at the conversation the reply is referring to.

Whatsapp is ahead of Telegram in this one respect. Let's crush them.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
