### ISSUE TITLE
Can't Add Group to New Folder When Slow Mode is On And Just Posted

### ISSUE THREAD

**Issue by landry314** [telegramdesktop/tdesktop#16616]
When you are creating a new Chat Folder and adding groups to it in bulk at creation time, if one of the groups has slow-mode enabled and you are not able to currently post in that group because you just posted, you can not include that group in the bulk adding. This doesn't make any sense. It is creating a folder, not posting.

**Comment by Aokromes** [comment]
this is telegram desktop or android?

**Comment by landry314** [comment]
macos desktop
