### ISSUE TITLE
Bug: Every program update "Tile backgroud" checkbox reenabled

### ISSUE THREAD

**Issue by engelsit** [telegramdesktop/tdesktop#16612]
Bug: Every program update "Tile backgroud" checkbox reenabled and I need to uncheck it manually.

**Comment by engelsit** [comment]
Windows 10 64bit

**Comment by bviktor** [comment]
Every. Single. Time. So friggin' annoying.

**Comment by ikskoder** [comment]
I have the same issue on Ubuntu 20.04 LTS 64bit.

**Comment by bviktor** [comment]
WTAF, we didn't "lose interest", we're waiting for you to solve this years-old issue! Should we nag you every month?

**Comment by ilya-fedin** [comment]
#16468
