### ISSUE TITLE
Alternate install location returns error

### ISSUE THREAD

**Issue by MuffinSmith** [telegramdesktop/tdesktop#16613]
I'm a sysadmin attempting to install telegram desktop through winget for my users. In my environment users don't have access to download or execute binaries outside the organization. 

Attempting to set an alternate location via --location does not work and setting --override "/VERYSILENT /NORESTART /DIR='C:\Program Files\Telegram Desktop'" returns with an error message saying "Folder names cannot include any of the following characters: / : * ? " < > |" 

### Expected behaviour
Telegram is installed to the system program files folder and updated by winget

### Actual behaviour
Windows popup error message saying it cannot make a folder with special characters

### Configuration
**Operating system:**
Windows 10 2004
**Version of Telegram Desktop:**
2.8.4 x64

Winget install --id Telegram.TelegramDesktop --override "/VERYSILENT /NORESTART /DIR='C:\Program Files\Telegram Desktop'"

![image](https://user-images.githubusercontent.com/8302046/125369769-d3212700-e331-11eb-95a9-31c7c0513feb.png)

**Comment by ilya-fedin** [comment]
I think you should ask winget maintainers

**Comment by MuffinSmith** [comment]
You're right, sorry
