### ISSUE TITLE
Bluetooth headset play/pause/next etc..  Buttons not working 

### ISSUE THREAD

**Issue by carp3** [telegramdesktop/tdesktop#1661]
Hi,  I have a Bluetooth headset and I listen  to music with telegram occasionally..  
My headset have music control buttons.  But telegram do not recognize them.  
Other apps such as Winamp and KMPlayer  works ok,  

My Headset : LG HBS730
Windows 8.1
Latest telegram release
Bluetooth adaptor : Intel Centrino BT4

**Comment by auchri** [comment]
See #1662
