### ISSUE TITLE
Allow User to Choose Swipe Right or Swipe Left to Reply

### ISSUE THREAD

**Issue by landry314** [telegramdesktop/tdesktop#16618]
All the other messengers are swipe right to reply but Telegram is swipe left.

This is confusing and I make the mistake all the time.

What about adding a user setting for this?

I realize swipe left is already set to go back to the chat list so basically it is a choice to swap these two gestures.

I would like it the other way around. Does anyone else have this desire? Does anyone else feel confused by this difference in Telegram?

**Comment by Aokromes** [comment]
this is telegram desktop not android or ios, and afaik, it's already possible on 7.8.

**Comment by landry314** [comment]
I think you are referring to "Chat list swipe gesture" on Android. That is for when you are in the chat list, not reading a message.

**Comment by landry314** [comment]
Also, I was referring to the desktop version as well as cell phones. You can click and drag left or right to do the same thing as you would on a touch screen.

**Comment by RememberTheAir** [comment]
tdesktop has double-click shortcut which achieves the same thing and it's quicker/more trivial
