### ISSUE TITLE
sometimes get error when launch app

### ISSUE THREAD

**Issue by and-bulk** [telegramdesktop/tdesktop#16611]
sometimes get error when launch app, but after relaunch everything works well it seems.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: the official website

**Used theme**: Night

<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/6800226/log.txt)
</details>

**Comment by ilya-fedin** [comment]
> sometimes get error when launch app, but after relaunch everything works well it seems.

Too little details

**Comment by and-bulk** [comment]
sorry what is missing?

**Comment by ilya-fedin** [comment]
Even the error is missing

**Comment by and-bulk** [comment]
now I get some error after reboot pc and launch telegram

**Comment by Aokromes** [comment]
you added telegram desktop to startup directory? or how you start telegram desktop? also, supply startup logs.

**Comment by ilya-fedin** [comment]
> now I always get same error after reboot pc and launch telegram

Are you kidding? You think others will know what error are you encountering with telepathy?

**Comment by and-bulk** [comment]
I send log file

![image](https://user-images.githubusercontent.com/79831859/125663442-041d16ed-7968-4fa8-bb73-9f3456a7b9fc.png)

**Comment by and-bulk** [comment]
doesn't added
![image](https://user-images.githubusercontent.com/79831859/125663574-e9b3a8fc-0f14-4502-a4fd-6acc8353e188.png)

**Comment by ilya-fedin** [comment]
> I send log file

log file doesn't have any error, you took a log file from other launch apparently

**Comment by and-bulk** [comment]
![image](https://user-images.githubusercontent.com/79831859/125668124-bcd4eb18-90c9-4d91-ada1-31c271d8f6b7.png)

**Comment by ilya-fedin** [comment]
#10353
