### ISSUE TITLE
download "grouped images" at once

### ISSUE THREAD

**Issue by mehdimoradi1500** [telegramdesktop/tdesktop#16620]
hi there 
It will be so great to add this feature: download grouped images and also the caption of it at once. I have a website and i have to download my product's images from telegram desktop, so its so hard and take so much time to download them one by one
I will appreciate it so much, thank you

![Capture](https://user-images.githubusercontent.com/86493591/125609223-d40eeb18-acf3-4027-8213-f3fa2fef0b07.PNG)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1382
