### ISSUE TITLE
shortcut_custom.json short code?

### ISSUE THREAD

**Issue by se7en-x230** [telegramdesktop/tdesktop#16623]
I added some custom shortcuts like `next_chat` and `previous_chat`.

Basically I would want to bind alt+k/j to scroll up and down in a chat.
I have tired `scroll_up/down` but that doesn't work.

Is there a short code list somewhere or has someone managed to find the right command to scroll?

**Comment by ilya-fedin** [comment]
in the wiki of the repo

**Comment by se7en-x230** [comment]
> in the wiki of the repo

Thanks I saw that before I asked.
But this doesn't explain what the short code for inchart navigation is. It just tells me the arrow up/down can be used.
I am looking to add or remap this to Alt+j/k
