### ISSUE TITLE
[Question] Retrieval of Permanently Deleted Chats

### ISSUE THREAD

**Issue by being-anonymous** [telegramdesktop/tdesktop#16624]
So,
There is a peer of mine who deleted some of his important chats by mistake.
The Chats got permanently deleted from both the ends.

Could someone please help me in resolving this issue.
He might get in serious trouble if this is not resolved.

Hope to get a positive response from the community as soon as possible.

**Comment by RememberTheAir** [comment]
There is no way to restore deleted content, unless you backed it up first. Once something is deleted, it's deleted for good. Unfortunately I believe there is no way to recover that content

**Comment by being-anonymous** [comment]
How can I check if it was backed up or not?
Where is the option to check my Backed Up Chats ?

> 
> 
> There is no way to restore deleted content, unless you backed it up first. Once something is deleted, it's deleted for good. Unfortunately I believe there is no way to recover that content

How can I check if it was backed up or not?
Where is the option to check my Backed Up Chats ?

**Comment by RememberTheAir** [comment]
With "backup" I meant tdesktop's built-in [chats exporter](https://www.telegram.org/blog/export-and-more). If you didn't manually launch am export, then there is no backup :(

**Comment by being-anonymous** [comment]
**Thank you so much**
I'll closing the Issue then
