### ISSUE TITLE
Can not request code via SMS.

### ISSUE THREAD

**Issue by mahbd** [telegramdesktop/tdesktop#16628]
### Steps to reproduce
1. Download and install telegram desktop app on Ubuntu 20.04
2. Try to login with your phone number.
3. Click on "Send code via sms"

### Expected behaviour
It should send an SMS to my phone.

### Actual behaviour
It doesn't send any SMS to my phone.

### Configuration
**OS: Ubuntu 20.04.2LTS:**

**Telegram version: 2.8.8:**

**Installation source (Linux Only)** - the official website and updated automatically:

**Used theme: Any**:

<details>
Previously it was possible to request SMS from desktop version but currently It is not available. Unfortunately I lost my phone weeks ago and can not login to my telegram account from then. User should be able to request SMS from desktop app at least
once a day.
</details>

**Comment by ilya-fedin** [comment]
#16153
