### ISSUE TITLE
Cannot select all typed text

### ISSUE THREAD

**Issue by lomby92** [telegramdesktop/tdesktop#16621]
### Steps to reproduce
1. Open a chat
2. Type something
3. Try to select all the typed text with <kbd>Ctrl</kbd> + <kbd>a</kbd>
4. Text is not selected

### Expected behaviour
I should be able to select the whole typed text

### Actual behaviour
Text is not selected

### Configuration
**Operating system:** Linux, KDE Neon 5.22

**Version of Telegram Desktop:** 2.8.4-2-gc22d7ffcf, revision 2841

**Installation source (Linux Only)**: snap

**Used theme**: classic

**Comment by ilya-fedin** [comment]
#16563
