### ISSUE TITLE
Font in 2.8.8 on Linux OS

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#16629]
Hello.

In TDesktop 2.8.8 on Linux Mint 20.02 font is not "Vazir" 

![image](https://user-images.githubusercontent.com/14938202/125894913-f1a82284-5d82-496e-9968-f5ef2a87a07d.png)

![image](https://user-images.githubusercontent.com/14938202/125895084-6921d3a6-bee0-411c-ae78-b0187e9b2f1a.png)

**Comment by TheWeirdDev** [comment]
I have the same problem with English text on Linux. Seems like it only affects bold texts.

![image](https://user-images.githubusercontent.com/6321734/125896420-b74cd58e-fa7b-4a7a-bb15-db6093b7263c.png)

Versions before 2.8.8 were fine.

**Comment by MasterGroosha** [comment]
Same in other languages. Fonts are really messed up in 2.8.8

**Comment by lesykm** [comment]
Same, fonts became ugly as hell.

**Comment by TuxTracer** [comment]
Font loading error in 2.8.8 linux version. Bold fonst are strange now.
Start log 2.8.8 version:

> [2021.07.16 08:24:18] Primary screen DPI: 96
> [2021.07.16 08:24:18] Font Error: could not add ':/gui/fonts/DAOpenSansRegular.ttf'.
> [2021.07.16 08:24:18] Font Error: could not add ':/gui/fonts/DAVazirRegular.ttf'.
> [2021.07.16 08:24:18] Font Error: could not add ':/gui/fonts/DAOpenSansRegularItalic.ttf'.
> [2021.07.16 08:24:18] Font Error: could not add ':/gui/fonts/DAVazirRegular.ttf'.
> [2021.07.16 08:24:18] Font Error: could not add ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf'.
> [2021.07.16 08:24:18] Font Error: could not add ':/gui/fonts/DAVazirMediumAsBold.ttf'.
> [2021.07.16 08:24:18] Font Error: could not add ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf'.
> [2021.07.16 08:24:18] Font Error: could not add ':/gui/fonts/DAVazirMediumAsBold.ttf'.
> [2021.07.16 08:24:18] Font Error: could not add ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf'.
> [2021.07.16 08:24:18] Font Error: could not add ':/gui/fonts/DAVazirMediumAsBold.ttf'.
> [2021.07.16 08:24:18] Font Error: could not add ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf'.
> [2021.07.16 08:24:18] Font Error: could not add ':/gui/fonts/DAVazirMediumAsBold.ttf'.

in 2.8.6 version:

> [2021.07.16 08:56:48] Primary screen DPI: 96
> [2021.07.16 08:56:48] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
> [2021.07.16 08:56:48] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
> [2021.07.16 08:56:48] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
> [2021.07.16 08:56:48] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
> [2021.07.16 08:56:48] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
> [2021.07.16 08:56:48] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
> [2021.07.16 08:56:48] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
> [2021.07.16 08:56:48] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
> [2021.07.16 08:56:48] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
> [2021.07.16 08:56:48] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
> [2021.07.16 08:56:48] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
> [2021.07.16 08:56:48] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'

**Comment by t3mnikov** [comment]
![image](https://user-images.githubusercontent.com/11781965/125901547-b6d95944-1894-4b25-a0db-2a7a6864e5a2.png)
Russian lang ver has same problem.

**Comment by vapespb** [comment]
The font is now terribly bold
2.8.8 vs 2.8.5 beta

![2021-07-16_09-16](https://user-images.githubusercontent.com/58982392/125903155-a410ac6c-01d8-47b8-a0aa-6b3601c79717.png)
![2021-07-16_09-28](https://user-images.githubusercontent.com/58982392/125903158-303b958e-4d03-4fa8-ab58-ba63d0a0b1a1.png)

**Comment by egormkn** [comment]
One more comparison: 2.8.8 vs 2.8.6
![2 8 6-tg](https://user-images.githubusercontent.com/7170781/125903611-93fea222-5fdc-4e45-9c61-7a51d7002384.png)
![2 8 8-tg](https://user-images.githubusercontent.com/7170781/125903617-c9861550-baca-44ae-9e81-e4ada2b90daf.png)

**Comment by alherd-by** [comment]
![image](https://user-images.githubusercontent.com/1499176/125904774-a28d4505-b534-4788-b655-46e04b2f6599.png)
Broken also in Belarusian

**Comment by solodkiy** [comment]
![image](https://user-images.githubusercontent.com/1427813/125904912-3bb18651-56be-44e2-b1cb-cdfcfdd140f1.png)
It's even more ugly in 150% scaling which I use.

**Comment by MasterGroosha** [comment]
Looks like v2.8.9 is going to fix it.

**Comment by meklonets** [comment]
I confirm. Same issue with fonts after update to 2.8.8.

**Comment by fe3dback** [comment]
same issue on 2.8.8 (ubuntu 20.10)

**Comment by ideamk** [comment]
Same issue on 2.8.8 (KDE Neon 20.04)

**Comment by meklonets** [comment]
If somebody want to roll back to 2.8.1 until the developers team fix this font issue, the version 2.8.1 is current version on their website for download `https://telegram.org/dl/desktop/linux` 
After unpacking the archive, remove Update exec file. Replace Telegram exec in your system. 
I understand this is for newbies, but maybe the info will help somebody.

**Comment by muxyrmuc** [comment]
Same issue on 2.8.8 (Ubuntu 21.04).
Also it seems like interface scaling is broken in this release too.

**Comment by Nikakto** [comment]
Same issue. Ubuntu 20.04 lts.

**Comment by SeedPuller** [comment]
Same issue on 2.8.8 (openSUSE 15.3).
Vazir font not loading.

**Comment by vitalif** [comment]
Fonts are absolute shit on 2.8.8. Downgraded to 2.8.6.

**Comment by Aleksandr-ru** [comment]
Same issue on elementary OS 5.1.7 Hera

**Comment by john-preston** [comment]
Should be fixed in 2.8.9.
