### ISSUE TITLE
Support media control hotkeys

### ISSUE THREAD

**Issue by auchri** [telegramdesktop/tdesktop#1662]
Add support for following hotkeys to control music via buttons on the keyboard:

* [ ] Previous Track
* [ ] Play / Pause
* [ ] Stop
* [ ] Next track

**Comment by haevalencia** [comment]
Add playlist/list of songs

**Comment by stek29** [comment]
@haevalencia It's already added, isn't it?

**Comment by haevalencia** [comment]
@stek29 no a hotkey

**Comment by stek29** [comment]
@haevalencia Hotkey to open playlist?
