### ISSUE TITLE
[Question] Anyone know bots that allow searching for groups globally?

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#16635]
Telegram's own global search is awful. 3-10 results, and no filters. Telegram ignores questions about global search on Twitter. I got a recommendation on Reddit for a bot to search globally for channels. But I also need to search globally for groups.

Please share. Thank you.

**Comment by RememberTheAir** [comment]
This has nothing to do with telegram desktop. You might try to ask on suggestions.telegram.org though, althout the right place to do so would be reddit and you already posted there

**Comment by azat11** [comment]
> 
> 
> This has nothing to do with telegram desktop. You might try to ask on suggestions.telegram.org though, althout the right place to do so would be reddit and you already posted there

I'll keep in mind that this is ho place to ask fellow humans for simple help.

**Comment by Aokromes** [comment]
> > This has nothing to do with telegram desktop. You might try to ask on suggestions.telegram.org though, althout the right place to do so would be reddit and you already posted there
> 
> I'll keep in mind that this is no place to ask fellow humans for simple help.

this is bug tracker for telegram desktop, bots arent telegram desktop.
