### ISSUE TITLE
Шрифты поменялись

### ISSUE THREAD

**Issue by Guzya** [telegramdesktop/tdesktop#16630]
### Steps to reproduce
1.  Обновил на 2.8.8

### Expected behaviour
Шрифты стали "вырвиглазными"

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Linux mint 18.3
**Version of Telegram Desktop:**
2.8.8
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Ч\з приложение
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by nfssfn** [comment]
Обнови на 2.9.9 - пофикшено
(настройки - advanced - check updates)

**Comment by Guzya** [comment]
Спасибо, теперь нормально!
