### ISSUE TITLE
2.8.9 Black screen in picture view

### ISSUE THREAD

**Issue by Gnevyshev** [telegramdesktop/tdesktop#16637]
### Steps to reproduce
1. Open chat
2. Click to picture
3. See black screen

### Expected behaviour
Normal picture view

### Actual behaviour
Black full screen

### Configuration
**Operating system:**
Windows 7 pro 64

**Version of Telegram Desktop:**
2.8.9

**Used theme**:
Night

**Comment by john-preston** [comment]
@Gnevyshev Can you please try changing Settings > Advanced > Performance > ANGLE backed to Disabled. Will it help? Will any other of them work?

**Comment by Gnevyshev** [comment]
@john-preston Yes, it helped. Thanks!
But not everyone may know about the need to change the settings.

**Comment by Aokromes** [comment]
what graphics card you have? you have tried to update drivers?

**Comment by john-preston** [comment]
This is temporarily fixed in 2.8.11, but with disabling ANGLE for users without d3dcompiler dll (it is not shipped on Windows 7 by default). I hope to improve it later.
