### ISSUE TITLE
Video calls: Aspect ratio & orientation undefined / random

### ISSUE THREAD

**Issue by DG2YCB** [telegramdesktop/tdesktop#16644]
### Steps to reproduce
1.  Install and run Telegram on an Android smartphone
2.  Install and run Telegram on an Android tablet (in landscape mode) or on a Windows PC (landscape by default)
3. Start video call between the smartphone and either the tablet or the PC

### Expected behaviour
Telegram shall automatically recognize whether the devices are using portrait or landscape mode, and shall adjust the appropriate video aspect ratio (usually 16/9). Alternatively, make it possible that I can set the following parameters manually:
- fixed portrait mode / fixed landscape mode / auto mode.
- fixed aspect ratio 16/9,

### Actual behaviour
For video calls, Telegram is currently neither able to set the aspect ratio correctly, nor the orientation (portrait vs. landscape mode). Behaviour is somewhat random. Very often, on the tablet the video is twisted by 90 degrees, or on the smartphone aspect ratio is portrait although the video sent is in landscape mode. 
When doing video calls between my PC and any Android device, the aspect ratio on my PC camera (16/9 by default) is either transmitted as 4/3, or on the Android smartphone the video is even twisted by 90 degrees.
The same error is there when doing video calls between the Android smartphone and the Android tablet. 

### Configuration
Android 9 (Samsung smartphone and Samsung tablet SM-T590)
Windows 10 Pro, 64-bit

**Version of Telegram Desktop:**
latest from Google Play, or Telegram Auto-update on Windows (as of 2021-07-17)
The error is there as long I can remember. I hoped is was getting fixed, but it has never been fixed through all the various updates.
PLEASE FIX THIS ANNOYING ERROR!

**Installation source (Linux Only)** 
- Telegram for Windows 10 x64 from the official website
- Telegram Android app from Google Play

**Used theme**:
default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by edevyatkin** [comment]
Same problem. Affects 3.1.1 version.

**Comment by arielnmz** [comment]
Still affects flatpak Telegram 3.6.1

```
$ flatpak info org.telegram.desktop

Telegram Desktop - Fast. Secure. Powerful.

          ID: org.telegram.desktop
         Ref: app/org.telegram.desktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.6.1
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 142.8 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: bd5c08674546dca8b9bcaeb45b86b7d10fe5ab1092c09af68eaa13cafa7b8525
      Parent: 5929be119f23dbef7ab04d107904bd37d264ec656c3c82cc46b5f67b6604cea4
     Subject: Add tg_owt updater (0d368518)
        Date: 2022-03-26 18:12:25 +0000
```

**Comment by SwedishBotMafia** [comment]
On my PC windows 10, and on someone elses phone Android (most recent) If I start the video it starts in landscape, if I switch video off and turn it on, it ends up portrait and is unswitchable back to landscape... fun.

**Comment by arielnmz** [comment]
Still present in Telegram 4.5.3 (Flatpak)

```
Telegram Desktop - Fast. Secure. Powerful.

          ID: org.telegram.desktop
         Ref: app/org.telegram.desktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.5
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 190.2 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 95e377ab94eea7a1cd53a53d237e4d88c01cfd9ab6f1ef05fc517a5b4ff41c8b
      Parent: c7b1b652c831573f1947436c88734d93048c45a93afd362bf2da1c2fd6f84df8
     Subject: Update 2 modules (8100c5ce)
        Date: 2023-01-07 07:46:36 +0000
```
