### ISSUE TITLE
0.9.24 shows all messages on left side

### ISSUE THREAD

**Issue by Voyadexon** [telegramdesktop/tdesktop#1664]
After the update, all messages, including ones I sent, are shown on the left side of the chat window. http://i.imgur.com/Npa6Cgk.png

Reinstalling didn't fix the issue

**Comment by 4ndv** [comment]
Same issue, but maybe it's not a bug?

**Comment by Voyadexon** [comment]
If it's a feature, there should at least be the option to go back to the old layout, because it doesn't look good.

**Comment by telegramdesktop** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It adds a checkbox "Adaptive layout for wide screens" below "Tile background" checkbox that can disable the new layout. It is visible only if you have a large window (with the new layout) already.
