### ISSUE TITLE
Video playback.

### ISSUE THREAD

**Issue by nyczkalucking** [telegramdesktop/tdesktop#16640]
### Steps to reproduce
1. Audacity 2.0 possible problem conflict.  unsure.
2. 
3. 

### Expected behaviour
well it was working just fine.  installed Audacity 2.0.  Found a few irregular errors in a game then eventually in telegram itself.
Tried playing back many versions of different video.  Al of which tries to start the video in another window as per normal.  I can hear everything but no video to watch.  I can see the small icon version in telegram itself.  I cannot select the volume, it triggers the video to launch then all hell breaks loose.  No video but audio.  Uninstalled Audacity no joys on video playback.  Ran CCleaner no joys.  Unistalled Telegram and reInstalled it.  to reset and again no joys.  Is their a repair function built into Telegram to fix the issue or something.???????

### Actual behaviour
as above

### Configuration
windows 7

28.10 windows 7 64

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by johnss** [comment]
Same here using version 2.9

Image also not working, when i clicked the image nothing happen, it should show full size image.

**Comment by jacob755** [comment]
settings->advanced->performance>angel graphics backend
change options and test which one work if its old device direct3d 9 is best options
