### ISSUE TITLE
[Feature Request] A way to make a collection of gifs and share it, like sticker packs

### ISSUE THREAD

**Issue by limepixl** [telegramdesktop/tdesktop#16641]
### Is your feature request related to a problem?
Nope, just a feature request.

### Describe the solution you'd like
Have a part of the GIF panel be segmented, like the different sticker packs are segmented in the stickers panel. This segmented part of the GIF panel would contain separate GIF packs, that are just collections of GIFs that you've added from the GIF picker. This way you can share your GIF packs with others and add / remove to them collaboratively.

### Describe alternatives you've considered
For this purpose I've tried to just use the GIF ordering based on the most recently used gifs, or keep the gifs in Saved Messages.

**Comment by RememberTheAir** [comment]
This would be impossible to implement for Telegram Desktop, you can open a new card on https://suggestions.telegram.org
