### ISSUE TITLE
[Feature Request] Admin should be able do deaktivate linking / forwarding a link in a private channel

### ISSUE THREAD

**Issue by LukeLordOfLight** [telegramdesktop/tdesktop#16646]
### Is your feature request related to a problem?
Yes, since there are problems, that users can forward and share links form files, that the admin has uploaded to a PRIVATE Channel. Admin should decide if Invited users should be able to forward and share a link to a file in a private channel.

### Describe the solution you'd like
The admin should be able to activate or deactivate the feature in a private channel, if a file he uploads can be shared via Link or not. Users should not be able to select "copy Link" or "forward", if the Admin does not allow it. These options in the menu should be unavailable if the admin deaktivates this in the private channel settings. As this is a PRIVATE Channel. Users should still be able to download files, but should not be able to forward it directely or Link to it, if that feature is deaktivated by the admin.

**Comment by LukeLordOfLight** [comment]
why has this been closed? Is it already implemented?

**Comment by Aokromes** [comment]
api means it must be done server side, or on all applications.

**Comment by LukeLordOfLight** [comment]
thanks for the the info....
do you think it's possible, that it can be implemented in all telegram versions (destop/mobile)?
