### ISSUE TITLE
Telegram crashes when clicked on hyper text link (Running Telegram using wine on linux)

### ISSUE THREAD

**Issue by prasadpatil25** [telegramdesktop/tdesktop#16653]
### Steps to reproduce
1. Install Telegram (2.8.11) for Windows on Linux (Fedora 34) using Wine (wine-6.0.1) or Use portable Telegram (2.8.11)
2. Open any hyperlink (or click on Version 2.8.11 hyperlink in settings)

### Expected behaviour
Should redirect to the default browser.

### Actual behaviour
Whenever I click on any hyperlink Telegram app crashes.

### Configuration
**Operating system:**
Fedora 34

**Version of Telegram Desktop:**
2.8.11

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Windows installable or Windows portable on Linux using wine.

**Comment by ilya-fedin** [comment]
You can't report when you're running via emulator

**Comment by Aokromes** [comment]
why you want to run one native application (telegram desktop) with wine instead directly????

**Comment by prasadpatil25** [comment]
@ilya-fedin @Aokromes yes I know there is native application available for Linux already, but the thing is my Telegram windows app is installed on C:\ drive that I access from Linux. Note that hypertext link works from other applications installed using wine but doesn't work on Telegram. So I reported this bug here instead of reporting it to wine.

**Comment by ilya-fedin** [comment]
It works on native Windows so this should be reported to wine

**Comment by prasadpatil25** [comment]
@ilya-fedin  Thanks, created a bug: https://bugs.winehq.org/show_bug.cgi?id=51292

**Comment by ilya-fedin** [comment]
I don't understand why you don't just create a TelegramForcePortable folder near Telegram.exe, move tdata folder there (so that there will be TelegramForcePortable/tdata) and place a Linux Telegram binary near the Telegram.exe
