### ISSUE TITLE
Copy the selected text

### ISSUE THREAD

**Issue by Lazek** [telegramdesktop/tdesktop#1665]
Telegram Desktop 0.9.24
Windows 10

After select text, for example:

Text test text

![tlg_screen](https://cloud.githubusercontent.com/assets/10336636/13205224/405198ee-d8f4-11e5-95f8-73790779a1d2.PNG)

Select phrase: test - and click right mouse button - Copy function not available.

If possible, please back / add it.

**Comment by auchri** [comment]
Please check out the latest 0.9.25 dev version from the bottom of this page:

https://desktop.telegram.org/#dev-version

It should be fixed there.

**Comment by Lazek** [comment]
Ohh, thank you.
