### ISSUE TITLE
Telegram doesn't scale after updated to 2.8.11

### ISSUE THREAD

**Issue by duongdominhchau** [telegramdesktop/tdesktop#16659]
In previous versions, Telegram can scale properly when I set 3840x2160 as the resolution. However, after this update, the text become too small to read.

![image](https://user-images.githubusercontent.com/56427890/126096507-7c133c2e-b2bc-4254-a5bd-d37a9ad47a12.png)

I tried downgrading to 2.8.4 and and the text is readable again.

Checking the **Settings**, I found an option for UI scaling, but the largest value is just 150% while I need at least 200%.

I use ArchLinux, Telegram is from official repos (package named `telegram-desktop`). If you need any other information please let me know.

**Comment by ilya-fedin** [comment]
@Aokromes can you close the issue since template was removed?

**Comment by Aokromes** [comment]
it looks arch linux package bug, for me it scales properly on windows. download official package from desktop.telegram.org
