### ISSUE TITLE
Cannot pick up video call when app starts closed

### ISSUE THREAD

**Issue by wparad** [telegramdesktop/tdesktop#16652]
### Steps to reproduce
1. Install telegram desktop for User 1
2. Install telegram desktop for User 2
3. Ensure telegram app is not running
4. Make video call from User 1 to User 2
5. Open desktop app for User 2

### Expected behaviour
Video call should appear on desktop but it does not.

### Actual behaviour
Video call appears in chat log, but user 2 cannot answer the video call.

### Configuration
**Operating system:**
* Linux 
*  Windows

**Version of Telegram Desktop:**
* 2.8.11

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
snap

**Comment by Aokromes** [comment]
> ### Steps to reproduce
> 1. Install telegram for android for User 1
> 2. Install telegram desktop for User 2
> 3. Make video call from User 1 to User 2
> 
> ### Expected behaviour
> Video call should appear on desktop but it does not.
> 
> ### Actual behaviour
> No video call appears. And user 2 cannot answer the video call.
> 
> ### Configuration
> **Operating system:**
> 
> * Linux
> * Windows
> 
> **Version of Telegram Desktop:**
> 
> * 2.1.7
> 
> **Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
> apt telegram-desktop

you need to update to 2.8.11

**Comment by wparad** [comment]
Okay, upgrading 2.8.11 almost fixed the issue, but the problem still exists in another form. It turns out there is no way to answer a call if the app wasn't running when the call was started.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7735
