### ISSUE TITLE
[Question] Why 2.8.10 and 2.8.11 not provide a macOS Installer?

### ISSUE THREAD

**Issue by moonfruit** [telegramdesktop/tdesktop#16658]
As the title, why 2.8.10 and 2.8.11 not provide a macOS Installer?

**Comment by ilya-fedin** [comment]
2.8.11 contains only Windows-specific fixes, I don't know what about 2.8.10 though

**Comment by john-preston** [comment]
@moonfruit I've uploaded binaries for macOS and Linux for 2.8.10 version, 2.8.11 is Windows-only.

**Comment by moonfruit** [comment]
OK, Thank you! @john-preston
