### ISSUE TITLE
Telegram OSX crashes when clicking on position sharing if access is not granted

### ISSUE THREAD

**Issue by and29** [telegramdesktop/tdesktop#16666]
### Steps to reproduce
1. Remove position access from Mac' System Preferences
2. Go to chat
3. Try to send position in a chat
4. Application crash

### Expected behaviour
Require user to allow access to position

### Actual behaviour
Application crash

### Configuration
OSX 11.4

7.8.1 (219462) AppStore

**Comment by Aokromes** [comment]
you are using telegram for mac os, not  telegram desktop.
