### ISSUE TITLE
Dockerfile fails on patches

### ISSUE THREAD

**Issue by mahdi-jfri** [telegramdesktop/tdesktop#16664]
### Steps to reproduce
1. start from fresh docker with no cache
2. run `docker build -t tdesktop:centos_env Telegram/build/docker/centos_env/`

### Expected behaviour
The docker to build correctly and patch stuff.

### Actual behaviour
Docker build errors out on patches.

### Configuration
**Operating system:**
Ubuntu 20
**Version of Telegram Desktop:**
2.8.11
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
log?

**Comment by mahdi-jfri** [comment]
Step 51/463 : RUN git apply ../patches/libproxy.patch
 ---> Running in b6c6a6b802f8
error: can't open patch '../patches/libproxy.patch': No such file or directory
The command 'scl enable devtoolset-9 -- bash -c git apply ../patches/libproxy.patch' returned a non-zero code: 128

**Comment by mahdi-jfri** [comment]
https://github.com/telegramdesktop/tdesktop/pull/16663

this should fix it
