### ISSUE TITLE
Unable to add contact in MacOS

### ISSUE THREAD

**Issue by henrychea** [telegramdesktop/tdesktop#16662]
### Steps to reproduce
1. Click on Window > Add contact
2. Enter contact name and phone number with area code
3. Click save

### Expected behaviour
The contact should be added and the message window appears.

### Actual behaviour
Displays a message that the contact has not yet joined telegram, however creating the same contact in Telegram iOS app has no such issue. 

### Configuration
**Operating system:**
MacOS
**Version of Telegram Desktop:**
2.8.10
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: DMG from official site

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@henrychea Can you contact me at t.me/preston and I'll ask you for your and contact phone number? This looks like a server side issue, I'll be asking server side developers about it with those details.

**Comment by henrychea** [comment]
Yes sure. I'll send you a message
