### ISSUE TITLE
[Feature Request] Telegram haven't sent the SMS code for log in

### ISSUE THREAD

**Issue by qg0** [telegramdesktop/tdesktop#16661]
Telegram haven't sent the SMS code. It send the code only to the another app (on the phone, computer, web).
What if I need to log in on some new device, but lost the phone/notebook with the installed app with logined user? What I suppose to do? 
i.e.: If I lost the phone and bought a new one.
i.e.: What if I use the desktop app for the work with the company's SIM card, but the company's phone doesn't have the app (old phone like Nokia 3210)?

![1](https://user-images.githubusercontent.com/919099/126104379-7c26e6e8-6acf-4713-a569-4b1490a4b66e.png)
![2](https://user-images.githubusercontent.com/919099/126104517-866f35f2-b245-4627-adb1-9aaab07fa9b1.png)

**Comment by Aokromes** [comment]
this belongs to https://bugs.telegram.org/
