### ISSUE TITLE
"Old layout" option missing when window isn't maximized

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#1666]
Hello! 
Running TDesktop 0.9.25dev on Windows. When I first launched new build I couldn't find new option "Use old layout". However, when I maximized window, it appeared for me.

I know that's "feature", not bug, but it's not intiutive for people who start Telegram in not maximized mode.

**Comment by diazbastian** [comment]
@Kondra007 I think it's by design. This option is only useful when using Telegram wide- window or maximized window.

**Comment by Kondra007** [comment]
@diazbastian Yeah, I guess it's by desing. The problem is that it's not user-friendly to hide the setting without any reasons.

**Comment by telegramdesktop** [comment]
@Kondra007 It is not needed for people who start it not in maximized mode.

**Comment by Kondra007** [comment]
Ah, okay then!
