### ISSUE TITLE
Video files are still open by Telegram after sending them

### ISSUE THREAD

**Issue by MouamleH** [telegramdesktop/tdesktop#16675]
### Steps to reproduce
1. get an mp4 video file
2. send the file to a user
3. try to delete or rename the file

### Expected behavior
The file should be released (closed) after Telegram sends it

### Actual behavior
The file remains open by Telegram and can not be deleted or renamed
![Telegram-bug](https://user-images.githubusercontent.com/31666226/126355058-f1849c6c-cc15-40ed-9f07-b2efaffe206b.png)

### Configuration
**Operating system:** Windows 10 20H2

**Version of Telegram Desktop:** 2.8.11 x64

**Used theme**: none

**Comment by ilya-fedin** [comment]
#7818
