### ISSUE TITLE
Desktop App can not distinguish different windows 10 users

### ISSUE THREAD

**Issue by JVK-BHZ** [telegramdesktop/tdesktop#16674]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen
I think telegram app should distinguish between app data for different users of a same Windows 10 system.

### Actual behaviour
Tell us what happens instead
I just noticed whenever two or more windows account exists on one device, the telegram app is shared between them.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.8
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Default 
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Make sure you installed Telegram to a system directory (like Program Files) for multi-user to work
