### ISSUE TITLE
Download channels media + send links in groups

### ISSUE THREAD

**Issue by ThisIsMatin** [telegramdesktop/tdesktop#16687]
Telegram has small but ridiculous problems that need to be fixed. The first problem is with downloading media. When I turn off the media download setting, however, the media is downloaded ! The next problem is sending links in groups. When I post a link in a group, it takes several minutes to submit. But when the link is in the form of a text, this problem no longer exists. (For example, write a dot or a word before the link)

**Comment by RememberTheAir** [comment]
First off, different problems should belong to different issues. You should open a new issue with the urls problems you described.

Second, you got rid of the issue template and didn't include anything useful to investigate/reproduce your issues: no info about your current auto-download settings or which medias you're having issues with, you app version, the operating system you're using. It's practically impossible to try to debug your issues

**Comment by ilya-fedin** [comment]
Third, it's a duplicate
#10371

**Comment by ilya-fedin** [comment]
I also saw some issue about links, but I guess it's closed as stale. Anyway, that most likely means bad connectivity to Telegram servers (so I guess sending links is not the only action that lags in tdesktop for the reporter)

**Comment by ilya-fedin** [comment]
#9949
