### ISSUE TITLE
Google Pinyin 2.7 is Incompatible with Telegram Desktop 2.8.11

### ISSUE THREAD

**Issue by MoeMoesakura68000** [telegramdesktop/tdesktop#16680]
### Problem
When auto upgrade to version 2.8.11,The input method don't work normally.
I don't know why it happened,but in other progs the input method works very perfect.
![图片](https://user-images.githubusercontent.com/31182725/126481424-a02251d7-79f8-49a2-88cf-21469fc51dd3.png)

### Configuration
**Operating system:**
Windows 7 SP1 (NT 6.1.7601) 32bit Simplified Chinese,Google Pinyin 2.7
**Version of Telegram Desktop:**
2.8.11

**Comment by Aokromes** [comment]
but google pinyin was discontinued on 2014.... can you try https://rime.im/ ?

**Comment by MoeMoesakura68000** [comment]
> 
> 
> but google pinyin was discontinued on 2014.... can you try https://rime.im/ or https://pinyin.sogou.com/ ?

Thank you,rime is good.
