### ISSUE TITLE
[Question] Linux build without docker?

### ISSUE THREAD

**Issue by JakeSays** [telegramdesktop/tdesktop#16689]
Can someone please provide detailed build instructions for linux that does not use docker? I need to make a custom version of the desktop client for linux and I do not use docker for development purposes.

**Comment by ilya-fedin** [comment]
tdesktop's cmake files have hardcoded paths to libraries they depend on exact versions of them, so, in that case you will be force to install CentOS 7 in some way and pollute your host system. That's why docker is used.

**Comment by JakeSays** [comment]
Wow. What a mess.
