### ISSUE TITLE
[Question] How to login (no SMS message)

### ISSUE THREAD

**Issue by adevoss** [telegramdesktop/tdesktop#16682]
Yesterday I was locked out.

Used the Telegram Desktop app for weeks by login once and open and close the app.
Yesterday for some reason I was logged out.
Can't login now.
First because I didn't receive the code via SMS. Then I tried too many times.
The code was sent to my Telegram app. But I only use one app and I was logged out.
We're now 24 hours later

What can I do?
- I have Internet access
- I have Access to phone (no smartphone / call/sms only)
- Can receive SMS for other 2FA application
- Both web app and desktop app send a code to my other Telegram application.
- Only using the desktop application (Linux. Can switch to Windows for a temporary workaround)
- When using the option 'Send SMS' I don't receive a SMS.
- Have received SMS messages from Telegram in the past.
- As I searched online there should be an option to receive a call which I didn't see.

Online I see messages Telegram does not send SMS anymore. Is this correct?

Can you please help to login?

**Comment by ilya-fedin** [comment]
#16153
