### ISSUE TITLE
2nd monitor in M1 macbook pro, optional menu opened in another monitor

### ISSUE THREAD

**Issue by DmitryBay** [telegramdesktop/tdesktop#16688]
### Steps to reproduce
1.  Connect 1 extra monitor, right mouse click to alt menu (1). Menu opened in another monitor (2)

### Expected behaviour
... 

### Actual behaviour
...

### Configuration
**Operating system:**
MacBook Pro (13-inch, M1, 2020), BIG SUR 11.4

**Version of Telegram Desktop:**
2.8.3
 
**Used theme**:
dark
 
![IMG_3614](https://user-images.githubusercontent.com/5918164/126758521-b3e41caf-4de7-4103-856c-4adac43758f4.jpg)

**Comment by ilya-fedin** [comment]
#7099
