### ISSUE TITLE
Скоро Telegram.exe будет весить 100 мб!

### ISSUE THREAD

**Issue by SashaGaran** [telegramdesktop/tdesktop#16686]
Вы Долбоёбы! Скоро Telegram.exe будет весить 100 мегабайт, а жрать оперативки 300 мегабайт!
Оптимизируйте код, сделайте сборщик мусора адекватный.
Отличный пример программа Win 10 Tweaker которая весит меньше 2 мегабайт и творит чудеса. А это Говно почти 100 мегабайтовое только умеет делать то, и то, и больше ничего. Можно спокойно вложится в 30 мегабайт.

**Comment by john-preston** [comment]
It will indeed be 100 mb quite soon :(

**Comment by ilya-fedin** [comment]
Это привет из прошлого? :thinking: 
![изображение](https://user-images.githubusercontent.com/17829319/126699273-2792a645-e4f3-4f84-a7af-45de446c3119.png)
![изображение](https://user-images.githubusercontent.com/17829319/126699359-d55b04d8-a01a-4958-a3a2-a40f00b3c677.png)

Всегда так было, вроде...

**Comment by ilya-fedin** [comment]
> Оптимизируйте код, сделайте сборщик мусора адекватный.

Нет никакого сборщика мусора, это же C++

> Отличный пример программа Win 10 Tweaker которая весит меньше 2 мегабайт и творит чудеса.

Она поди не кроссплатформенная и не умеет ни видео воспроизводить, ни фотки показывать, ни анимированные стикеры, не говоря уже о звонках (да, это намек на то, что на каждый из этих пунктов нужно по библиотеке, от которых размер бинарника будет расти, хотя основную часть занимают Qt и webrtc). Не говоря уже о ресурсах, встроенных в бинарник (иконки всякие).

> Можно спокойно вложится в 30 мегабайт.

Ну возьми и вложись, покажи, как нужно делать...

**Comment by john-preston** [comment]
`Telegram.exe (99629680)` 😭

**Comment by SashaGaran** [comment]
Привет, ilya-fedin! 🖐
Пожалуй Ты прав, Я погорячился, извините Меня пожалуйста.

**Comment by SashaGaran** [comment]
Привет, john-preston! 🖐
Что это за цифры 99629680, это размер?

**Comment by john-preston** [comment]
@SashaGaran Yeah, 64 bit version for Windows reached almost 100 MB in 2.8.12 beta. One of the next versions will cross the mentioned boundary. *sigh*

**Comment by SashaGaran** [comment]
Ну Вы хоты не сделаете когда то файл 32-битного Telegram.exe в 1 Gb?

**Comment by nuclight** [comment]
Ха-ха! 100 Мб всего? Слабак! Как насчет 2,0G ?
`-rwxr-xr-x  1 root  wheel  2170184925 22 мая   05:13 /usr/local/bin/telegram-desktop`
