### ISSUE TITLE
Windows v0.9.24 breaks messages layout when maximized

### ISSUE THREAD

**Issue by vekat** [telegramdesktop/tdesktop#1668]
Whenever I have Telegram maximized, all the messages inside the chat area get pushed to the left area, leaving the right area completely empty.

Oddly, the messages go back to normal (sender's messages on the right side, receiver's on the left) when I switch to windowed mode.

I noticed this change the moment I updated to version 0.9.24, as I had Telegram already maximized.

**Comment by Kondra007** [comment]
That's not a bug, but feature. On wide screens messages are pushed to the left to keep them all in one place without you having to shake head.

And it's now optional since 0.9.25 dev.
