### ISSUE TITLE
[Feature Request] Add media / Medien hinzufügen (Cross-Plattform)

### ISSUE THREAD

**Issue by QNET17** [telegramdesktop/tdesktop#16695]
### Is your feature request related to a problem?
Currently, it is possible that media can replace or delete. I would like if you can attach media in case you forget a video or picture.

DE: Derzeit ist es möglich, dass Medien ersetzen  oder löschen kann. Ich würde mir wünschen, wenn man Medien anhängen kann, falls man ein Video oder Bild vergessen hat.

### Describe the solution you'd like
It would be nice to be able to select "Add Media" in addition to "Edit Media" and "Replace Media".

DE: Es wäre schön, dass man neben "Medien bearbeiten" und "Medien ersetzen" auch "Medien hinzufügen" auswählen könnte.

### Describe alternatives you've considered
Until now, unfortunately, you had to delete the post and recreate it or put a post behind it. This is rather inconvenient.

DE: Bisher musste man den Beitrag leider löschen und neu erstellen oder einen Beitrag hinterherschieben. Das ist eher ungünstig.

### Additional context
Android
![photo_2021-07-24_15-59-12](https://user-images.githubusercontent.com/20202798/126870758-7f4a8f2a-1f0f-4702-95f1-dccc5ce7dcae.jpg)

Desktop
![111](https://user-images.githubusercontent.com/20202798/126871311-f8642c58-4a40-4903-84bb-8a5e4061cb82.png)

**Comment by ilya-fedin** [comment]
Are you sure you're talking about tdesktop? Your screenshot doesn't look like it's from tdesktop

**Comment by QNET17** [comment]
> 
> 
> Are you sure you're talking about tdesktop? Your screenshot doesn't look like it's from tdesktop

It's about all platforms. I have added a picture from tdesktop just for you. You are a strange person....

**Comment by 23rd** [comment]
Your suggestions can be sent here: [bugs.telegram.org](https://bugs.telegram.org/).

**Comment by QNET17** [comment]
> 
> 
> Your suggestions can be sent here: [bugs.telegram.org](https://bugs.telegram.org/).

This is not about a mistake.... But ok. Super support...
