### ISSUE TITLE
[Question] Anonymity when you create a group

### ISSUE THREAD

**Issue by zakiloki0** [telegramdesktop/tdesktop#16697]
I've noticed that on the desktop version, when you create a group, the app shows who created it, rather than just saying it was created, as in channels.

For example on Android appears "Group created" which is great
In the desktop "X created the group X"

Could you make it consistent with the mobile versions? Thanks Devs.

**Comment by Aokromes** [comment]
> I've noticed that on the desktop version, when you create a group, the app shows who created it, rather than just saying it was created, as in channels.
> 
> For example on Android appears "Group created" which is great
> In the desktop "X created the group X"
> 
> Could you make it consistent with the mobile versions? Thanks Devs.

you realize that group still have one owner and it's useless to remove X created the group X?

**Comment by zakiloki0** [comment]
> > I've noticed that on the desktop version, when you create a group, the app shows who created it, rather than just saying it was created, as in channels.
> > For example on Android appears "Group created" which is great
> > In the desktop "X created the group X"
> > Could you make it consistent with the mobile versions? Thanks Devs.
> 
> you realize that group still have one owner and it's useless to remove X created the group X?

I understand what you are saying, but then why does it appear anonymously on Android?
