### ISSUE TITLE
white border around telegram

### ISSUE THREAD

**Issue by mohammadjavad948** [telegramdesktop/tdesktop#16694]
### Steps to reproduce
1. open telegram
2. unmaximize telegram
3. you can see a white border around it

### Expected behaviour
it shouldn't have any white border

### Actual behaviour
when i open telegram it shows a white border around it
![bug-image](https://user-images.githubusercontent.com/52201992/126860510-802f19b8-4764-4f7f-ad33-5635190d1341.png)

### Configuration
**Operating system:** Manjaro Gnome 40

**Version of Telegram Desktop:** 2.8.11-2.0

**Installation source (Linux Only)** - distribution package: pacman

**Used theme**: default dark

**Comment by ilya-fedin** [comment]
That means your environment doesn't support window shadows, that's not a bug

**Comment by mohammadjavad948** [comment]
thank you for your help.
is there any way to remove it?

**Comment by ilya-fedin** [comment]
You should have a compatible WM and compositor. GNOME's default mutter should fit. It's also might be kvantum that adds some layer under the window.

**Comment by unnikrishnan-ag** [comment]
To anyone looking to fix this, check Settings > Advanced > System Integration > Use system window frame.

**Comment by unnikrishnan-ag** [comment]
I'm using Gnome as well and window shadow works for all applications except Telegram.
![Screenshot from 2021-07-27 23-52-05](https://user-images.githubusercontent.com/23318485/127207552-483b28a3-b746-4dde-9f95-50c52c226cb6.png)

**Comment by ilya-fedin** [comment]
Try official build from https://desktop.telegram.org, maybe it's a problem with distribution package

**Comment by unnikrishnan-ag** [comment]
Seems like that's the issue. Official build works fine.
