### ISSUE TITLE
[Feature Request] More characters for media / Mehr Zeichen für Medien (Cross-PLattform)

### ISSUE THREAD

**Issue by QNET17** [telegramdesktop/tdesktop#16696]
### Is your feature request related to a problem?
When you upload media, you have fewer characters available.
DE: Wenn man Medien hochlädt, hat man weniger Zeichen zur Verfügung.

### Describe the solution you'd like
It would be nice if the signs were basically raised.
DE: Es wäre schön, wenn die Zeichen grundsätzlich erhöht werden würden.

### Describe alternatives you've considered
The alternative is the use of telegra.ph - This is also great, but for this a possibility should be created that "too long" contributions (normal and with media) are automatically converted into an article for telegra.ph.
So you could link your account with telegra.ph in the settings.

DE: DIe Alternative ist höchsten die Nutzung von telegra.ph - Das ist auch super, aber dafür sollte dann eine Möglichkeit geschaffen werden, dass sich "zu lange" Beiträge (Normal und mit Medien) automatisch in einem Artikel für telegra.ph umwandel. So könnte man in den Einstellungen seinen Account mit telegra.ph verknüpfen.

**Comment by ilya-fedin** [comment]
> ### Describe the solution you'd like
> 
> A clear and concise description of any alternative solutions or features you've considered.

WTF

**Comment by QNET17** [comment]
> 
> 
> > ### Describe the solution you'd like
> > A clear and concise description of any alternative solutions or features you've considered.
> 
> WTF

Very professional... I have edited it

**Comment by 23rd** [comment]
Your suggestions can be sent here: [bugs.telegram.org](https://bugs.telegram.org/).

**Comment by QNET17** [comment]
> 
> 
> Your suggestions can be sent here: [bugs.telegram.org](https://bugs.telegram.org/).

This is not about a mistake.... But ok. Super support...
