### ISSUE TITLE
[Feature Request] WebM Support

### ISSUE THREAD

**Issue by ottersarecool** [telegramdesktop/tdesktop#16693]
### Is your feature request related to a problem?
Send a WebM file to any of your contacts, no thumbnail, no preview, this is confusing

### Describe the solution you'd like
WebM is probably not in the list of supported formats because of Apple, so I'd say only implement it for Android and Desktop, leave Apple behind.

### Describe alternatives you've considered
Crying myself to sleep

### Additional context
Please

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/2364
