### ISSUE TITLE
Linux client failed to start

### ISSUE THREAD

**Issue by c02y** [telegramdesktop/tdesktop#16690]
### Steps to reproduce
1. open telegram-desktop command in terminal
2. 
3. 

### Expected behaviour
Tell us what should happen
Open the GUI client window

### Actual behaviour
Tell us what happens instead
Won't load GUI client window

### Configuration
**Operating system:**
Linux 5.13.4-1-MANJARO
**Version of Telegram Desktop:**
v2.8.11-2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Manjaro official repo, unstable branch

**Used theme**:

<details><summary><b>Logs</b>:</summary>
$ telegram-desktop

(telegram-desktop:608279): Telegram-WARNING **: 18:37:11.011: Application was built without embedded fonts, this may lead to font issues.

(telegram-desktop:608279): GLib-GObject-WARNING **: 18:37:11.108: cannot register existing type 'GtkWidget'

(telegram-desktop:608279): GLib-GObject-CRITICAL **: 18:37:11.108: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(telegram-desktop:608279): GLib-GObject-WARNING **: 18:37:11.108: cannot register existing type 'GtkBuildable'

(telegram-desktop:608279): GLib-GObject-CRITICAL **: 18:37:11.108: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(telegram-desktop:608279): GLib-CRITICAL **: 18:37:11.108: g_once_init_leave: assertion 'result != 0' failed

(telegram-desktop:608279): GLib-GObject-CRITICAL **: 18:37:11.108: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(telegram-desktop:608279): GLib-GObject-CRITICAL **: 18:37:11.108: g_type_register_static: assertion 'parent_type > 0' failed

$ cat ~/.local/share/TelegramDesktop/log_start9.txt
[2021.07.23 18:37:11] Launched version: 2008011, install beta: [TRUE], alpha: 0, debug mode: [FALSE]
[2021.07.23 18:37:11] Executable dir: /usr/bin/, name: telegram-desktop
[2021.07.23 18:37:11] Initial working dir: /home/chz/
[2021.07.23 18:37:11] Working dir: /home/chz/.local/share/TelegramDesktop/
[2021.07.23 18:37:11] Command line: telegram-desktop
[2021.07.23 18:37:11] Executable path before check: /usr/bin/telegram-desktop
[2021.07.23 18:37:11] Logs started
[2021.07.23 18:37:11] Launcher filename: telegramdesktop.desktop
[2021.07.23 18:37:11] IBus portal is present! Using it.

```

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by c02y** [comment]
Yeah, the version from the link works.

**Comment by Translator5** [comment]
Issue regarding Manjaro Repo's Version approved!
