### ISSUE TITLE
Missing include directories for win_directx_helper

### ISSUE THREAD

**Issue by GreenYun** [telegramdesktop/tdesktop#16699]
### Steps to reproduce
1. Follow https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md
2. Stay on HEAD in dev branch

### Expected behaviour
Compilation is finished successfully.

### Actual behaviour
Missing openssl/sha.h for cmake\win_directx_helper\win_directx_helper.cpp

### Configuration
**Operating system:**
Windows 10 x64

**Version of Telegram Desktop:**
Latest dev branch (2.8.13 beta)

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
N/A

**Used theme**:
Default

**Possible Solution**:
Add
```
include_directories(SYSTEM ${libs_loc}/openssl_1_1_1/include)
```
to cmake\win_directx_helper\CMakeLists.txt

An extra Question:
The version number coded in cmake\validate_d3d_compiler.py is higher than the latest Windows 10 SDK, even than Windows SDK preview. Is that Intentional?

<details><summary><b>Logs</b>:</summary>
N/A
</details>

**Comment by john-preston** [comment]
@GreenYun The version number (and the compiler etc) were taken from here: https://bugs.chromium.org/p/chromium/issues/detail?id=920704

**Comment by GreenYun** [comment]
As per the thread, VS2019 does not ship SDK with version 10.0.20xxx.x, and I have successfully build Telegram with 10.0.19041.685; not found any obvious bugs. I have checked the version number of d3dcompiler_47.dll in Windows 11 with VS2022, with Windows 10 SDK 10.0.20348.0, while the version of d3dcompiler_47.dll is 10.0.20348.1.

I also checked some latest version of Chrome Dev, they did not ship this higher version file.

I think we should not check the exact version number for the dll, for future upgrading. Instead, check the version >= 10.0.19041.685.

**Comment by john-preston** [comment]
@GreenYun This exact version is required if you ship this dll to the end users Windows 7 systems. As discussed in the thread I've linked above, previous versions depend on ucrt and won't load on basic Windows 7 setup.

**Comment by john-preston** [comment]
@GreenYun It should be a build warning, not an error, in non official builds.

**Comment by kirsan31** [comment]
@john-preston on  2.9.1 VS2019 x64 build still failing with:
```
Error	C1083	Cannot open include file: 'openssl/sha.h': No such file or directory	win_directx_helper	...\tdesktop\cmake\win_directx_helper\win_directx_helper.cpp	11	fatal	CL	
```
@GreenYun  proposal naturally corrects this.

**Comment by john-preston** [comment]
@kirsan31 Should be fixed now.
