### ISSUE TITLE
[BUG] Voice note playback ignores Telegram output device setting in Windows 10

### ISSUE THREAD

**Issue by misterjoshua** [telegramdesktop/tdesktop#16709]
### Steps to reproduce
1. Set up a computer with two playback devices A and B
2. Set A to the default device for playback
3. Go into Settings > Advanced > Call Settings and change the Output device to device B
4. Listen to a voice note
5. The voice note will come out of the playback device A (the default device) instead of B (the device configured in Telegram settings)

### Expected behaviour
Per @ilya-fedin in https://github.com/telegramdesktop/tdesktop/issues/16708, the system's default communication device is ignored by design and if I need another device, I should choose it in settings. After choosing device B in settings, I expected that the voice note would play on device B.

### Actual behaviour
It ignored the output device selected in settings (B) and played on the system default device (A).

### Configuration
**Operating system:**
Windows 10 21H1

**Version of Telegram Desktop:**
2.8.1 x64

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official website

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
N/A
</details>

**Comment by ilya-fedin** [comment]
I can't reproduce, call goes from the chosen device

**Comment by misterjoshua** [comment]
> I can't reproduce, call goes from the chosen device

It's a voice note not a call.

In the picture below, it's the messages that show in chat when you click the microphone icon (red arrow pointing at it), talk into it, when when you let go, it sends a message with voice that the other side can listen to. (yellow arrow below)

![image](https://user-images.githubusercontent.com/644092/127215841-e55b7e04-936f-4723-b6d2-f800195dc4ee.png)

**Comment by ilya-fedin** [comment]
> It's a voice note not a call.

Oh, it's intended then. Voice record is a media, so it shouldn't use default communication device. And Telegram doesn't have audio settings for anything except of call settings. You should set default device in the system to whatever you want use for voice records.
