### ISSUE TITLE
[BUG] Voice note playback ignores the Windows 10 Default Communication Device

### ISSUE THREAD

**Issue by misterjoshua** [telegramdesktop/tdesktop#16708]
### Steps to reproduce
1. Set up a computer with two playback devices A and B
2. Set A to the default device for playback
3. Set B to the default communication device
4. Listen to a voice note
5. The voice note will come out of playback device A (the default device) instead of B (the default communication device)

### Expected behaviour
I expected that the voice note would play on the default communication device. (B)

### Actual behaviour
It ignored the default communication device and played on the default playback device. (A)

### Configuration
**Operating system:**
Windows 10 21H1

**Version of Telegram Desktop:**
2.8.1 x64

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official website

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
N/A
</details>

**Comment by ilya-fedin** [comment]
Yeah, tdesktop uses the common default device due to a lot of complains from non-technical uses previously, that's intended. If you need another device, choose it in settings.
