### ISSUE TITLE
how to call getMessagesViews

### ISSUE THREAD

**Issue by hosseinab** [telegramdesktop/tdesktop#1670]
hi
I want to calling getMessagesViews method . 
please help me about parameters of this method . 
InputPeer  peer { channelId , accessHash}
Vector<Integer> id
boolean increment

I call ChannelsGetDialogs for parameters and get chat object of my channel and put chat id into channelid and access hash , is it ok ?

after get message object of channel and add message id into vector id .
and equals increment with true

but when I call the method received timeout exception .

thanks a lot

**Comment by majid23** [comment]
hi 
how do you get access_hash?

**Comment by jamesmoriati** [comment]
Hi
I have the same problem.
please help.

**Comment by auchri** [comment]
You should ask questions like this on sites like http://stackoverflow.com/ and not on github.
