### ISSUE TITLE
[Feature Request] Widen the Buttons

### ISSUE THREAD

**Issue by sujithb6** [telegramdesktop/tdesktop#16701]
![Screenshot (62)](https://user-images.githubusercontent.com/72318405/126902871-163d184b-acd3-49ad-ad64-38e0d7cb2821.png)
Please Widen the Miinimize , Exit Button as general desktop softwares.

Its being tough to point cursor fastly.

By the way we are Telegram Fans !

**Comment by Aokromes** [comment]
you can enable the "use system windows frame" setting

**Comment by Eric-01** [comment]
Aokromes, but it doesn't work with sub-windows, unfortunately.
