### ISSUE TITLE
Round icon to square icon on MacOS

### ISSUE THREAD

**Issue by danilinus** [telegramdesktop/tdesktop#16700]
![image](https://user-images.githubusercontent.com/45608534/126890753-bae78260-ab07-4100-8265-d4dc560490fc.png)

This icon does not fit into the general style of all icons and it cannot be replaced manually, because a round icon is returned at startup, please fix it or give a choice. Thanks

**Comment by ilya-fedin** [comment]
#16552

**Comment by Aokromes** [comment]
also, not a bug, intended.
