### ISSUE TITLE
Start error on nvidia-340xx drivers

### ISSUE THREAD

**Issue by alternativniy** [telegramdesktop/tdesktop#16712]
### Steps to reproduce
1. Install nvidia-340xx drivers on Manjaro Linux
2. Start App

### Configuration
**Operating system:** Manjaro Linux KDE 21.1.0

**Linux kernel:** 5.10.52-1-MANJARO (64-bit)

**Version of Telegram Desktop:** 2.8.11

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Snap

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
telegram-desktop: error while loading shared libraries: libnvidia-tls.so.340.108: cannot open shared object file: No such file or directory
</details>

**Comment by ilya-fedin** [comment]
You have a problem in your system
