### ISSUE TITLE
Desktop app going down after logging in

### ISSUE THREAD

**Issue by i4081i** [telegramdesktop/tdesktop#16719]
### Steps to reproduce
1. Log in to the app.

### Expected behaviour
The chat screen should open properly.

### Actual behaviour
The program crashes.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** Telegram Desktop 2.8.13 beta

**Comment by john-preston** [comment]
@i4081i Please send the crash report after the next launch of Telegram Desktop and copy "Your Report Tag" field here.

**Comment by i4081i** [comment]
Report tag: e192cd83-a846-491c-96a5-5e7366f4e7b1

Report: details:

ApiId: 2040
Assertion: "timeout >= 0 && timeout <= std::numeric_limits<int>::max()" timer.cpp:101
Binary: Telegram.exe
Launched: 30.07.2021 11:19:05
Platform: Windows32Bit
UserTag: d5fa1295bd726947
Version: 2008013 beta
Memory-usage: 167 MB (peak), 167 MB (current)
Pagefile-usage: 145 MB (peak), 140 MB (current)

Caught signal 11 (SIGSEGV) in thread 10260

Backtrace omitted.

Google Breakpad caught a crash, minidump written in thread 13832
Minidump: e192cd83-a846-491c-96a5-5e7366f4e7b1

Backtrace omitted.

**Comment by john-preston** [comment]
@i4081i 🤔 I would like to ask you for debug logs (in private chat, you can write me at https://t.me/preston), because I don't understand how it fails that way. Or I can try to fix it somehow in code.
