### ISSUE TITLE
[Feature Request] Option to disable forwarding of messages in channels

### ISSUE THREAD

**Issue by jeffythedragonslayer** [telegramdesktop/tdesktop#16711]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
Admin option that allows admin to disable forwarding in a channel; makes forward button disappear.

### Describe alternatives you've considered
Not sure.

### Additional context
It would be nice if the admin of a channel could disable forwarding of messages, if the channel contains security sensitive information.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
