### ISSUE TITLE
Pin board in group chats

### ISSUE THREAD

**Issue by prinzeigelb2** [telegramdesktop/tdesktop#1671]
In group chats with many people you often have a problem with group coordination. Place and time are discussed, but when you miss several messages, you don't know where and when to meet. 
For this, something like a freetext pin board for each group chat would be useful.

**Comment by auchri** [comment]
No api for that

**Comment by prinzeigelb2** [comment]
Why this answer?

**Comment by telegramdesktop** [comment]
@prinzeigelb2 This is a client app which can do only things that are supported by Telegram API (for example which are already present in official mobile apps, like iOS app or Android app). Nothing server-side-related, which is not supported by the Telegram API, can be done in this app.
