### ISSUE TITLE
[Feature Request] A setting to change the output device for voice recordings

### ISSUE THREAD

**Issue by misterjoshua** [telegramdesktop/tdesktop#16710]
### Is your feature request related to a problem?
Yes. @ilya-fedin has been helping to establish what Telegram Desktop behaviour we should expect in #16708 and #16709. (Sorry for all the notifications. I'm just trying to find a better solution for this problem, and you've been very responsive 🚀)

### Describe the solution you'd like
I want a new setting in the Telegram Desktop app to choose which device voice recordings are played through and not a solution that requires me to change the system default output device. Their current designation as media content notwithstanding, voice recordings are communicating with other people, so like a voice call, I want them coming out of my headset rather than my speakers for the reason of privacy.

### Describe alternatives you've considered
I have tried using the system's default communications device setting. But per @ilya-fedin in #16708, Telegram doesn't honour the Default Communication Device settings by design - to work around non-technical user complaints.

I have tried selecting the output device in Settings > Advanced > Call Settings, but per @ilya-fedin in #16709, this setting is not meant to control voice recording playback.

I have also tried to use the Windows App Volume and Device Preferences settings to tell Telegram that my headset is the default playback device. But, a few times per day, Telegram stops playing through the configured output device, and this requires me to manually switch between sound devices to reset Telegram to get it to output to the correct device again.

I have also considered changing my default sound device to my headset every time I listen to a voice recording, then put it back to speakers after, but by this point, the voice recording playback has very poor usability.

### Additional context
I can't think of any. Thanks for helping so far @ilya-fedin.

**Comment by john-preston** [comment]
@misterjoshua Right now there is a single audio playback context for notifications sounds, music and video sound playback and voice message / round video message sound playback. They're played through one device all together. I was thinking about adding settings for output device for this "all sound". But I'm not sure if it covers your use case.

**Comment by misterjoshua** [comment]
> @misterjoshua Right now there is a single audio playback context for notifications sounds, music and video sound playback and voice message / round video message sound playback. They're played through one device all together. I was thinking about adding settings for output device for this "all sound". But I'm not sure if it covers your use case.

@john-preston I'd be happy for such an "all sound" setting. I neglected to consider the round video message sound playback and that would benefit from this type of setting as well! :)

**Comment by misterjoshua** [comment]
This is not stale. I'd still like this feature. Thanks

**Comment by misterjoshua** [comment]
This is not stale. I'd still like this feature. Thanks.

**Comment by Aokromes** [comment]
superseded by https://github.com/telegramdesktop/tdesktop/issues/25350 since i cannot rename.
