### ISSUE TITLE
[Bug] Broken reminders/scheduled messages on 2.9

### ISSUE THREAD

**Issue by tva10** [telegramdesktop/tdesktop#16726]
### Steps to reproduce
1. Open latest version of TDesktop (2.9.0)
2. Go to the Saved messages and create reminder (As well you can check old reminds or scheduled messages) 
3. Сheck if it is possible to edit this message in Reminders tab
4. Reopen TDesktop
5. Check if it is possible to edit again
... upd ...
6. Exit into main menu with chat list
7. Make Telegram window inactive
8. Wait until reminder happens
9. Open Telegram (this reminder will appear without unread count icon)
10. Click on that chat and have crash (in some cases it is possible to go into reminder/scheduled tab with crash)

### Expected behaviour
On older version (2.8.11) editor for old scheduled messages works fine.
You can edit them, delete, send now or reschedule. 
As well data was synchronised between devices

### Actual behaviour
In my case it is not possible to edit old scheduled messages
There are no options in right click menu (except Edit or Copy text)
When you press edit, you can try to change text of the message, but confirm button will not work

### Configuration
**Operating system:**
Linux, Windows

**Version of Telegram Desktop:**
2.9.0

<details><summary><b>Screenshots</b>:</summary>
<img src="https://user-images.githubusercontent.com/14250295/127732379-9f434176-0ece-473e-8f22-e7f8551ce668.png">
<img src="https://user-images.githubusercontent.com/14250295/127732384-d5040891-6ec9-47bb-a270-0560bbc0cc5d.png">
</details>

<details><summary><b>Screen Record</b>:</summary>
<video src="https://user-images.githubusercontent.com/14250295/127732750-abd9db8b-c935-430c-afa3-c981ae69400b.mp4"></video>
</details>

**Comment by st-den** [comment]
Can confirm. Moreover, I got a crash when I opened my Saved Messages chat with an unread reminder. Failed to replicate, though, so it may be a race condition. Sent the report.
![image](https://user-images.githubusercontent.com/46577620/127733609-08f06dda-bcbb-4d27-a6b0-a8d4e4be5adb.png)

**Comment by Neurotoxin001** [comment]
Same issue

2.9
Win 10

**Comment by Willox25565** [comment]
I have a similar issue, Telegram Desktop is crashing after opening dialog with unread reminder to a bot account. The only difference is that I don't get crash report - an app just instantly closes. Also it is not happening all the time, some dialogs with bots can cause crash and some don't.

Telegram Desktop 2.9 (x64), Windows 10.

**Comment by 23rd** [comment]
All appeared problems with scheduled messages will be fixed in the next version.
