### ISSUE TITLE
[bug] Batch file displays as Album

### ISSUE THREAD

**Issue by sam01101** [telegramdesktop/tdesktop#16727]
### Steps to reproduce
1. Update a batch of file (Any of 2+)

### Expected behaviour
Show as "Files"

### Actual behaviour
Show as "Album"

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** Version 2.9

**Used theme**: Tinted

### Screenshots

![image](https://user-images.githubusercontent.com/25792361/127735101-406798c4-dfa0-4272-8a13-b5b957e770b2.png)

![image](https://user-images.githubusercontent.com/25792361/127735099-56091483-2c44-4600-865c-10b94c18e9bf.png)

**Comment by ilya-fedin** [comment]
sounds like a feature rather than a bug

**Comment by john-preston** [comment]
There should be a checkbox for sending the files that way or separately.
