### ISSUE TITLE
Add new option to left click menu add to folder [Feature Request] 

### ISSUE THREAD

**Issue by Ali7med** [telegramdesktop/tdesktop#16720]
###  After add folders feature its more efficient to spilt type of conversations
if  Add new option to left click menu add to folder direct in main window its more usufll ,
thanks.

**Comment by Ali7med** [comment]
![Screenshot 2021-07-30 121126](https://user-images.githubusercontent.com/10943632/127630563-e0cfa427-4df6-44bb-9ea8-6df2ae157136.jpg)

**Comment by ilya-fedin** [comment]
#7927
