### ISSUE TITLE
[openSUSE TW KDE] [Official Binary] Autostart telegram not allow send voice message

### ISSUE THREAD

**Issue by DevDorrejo** [telegramdesktop/tdesktop#16729]
### Steps to reproduce
1. Download telegram from [Telegram Desktop](https://desktop.telegram.org)
2. Set autostart check on advance settings.
3. Restart the system and wait boot up.
4. Open a chat on Telegram, instead appear a mic icon on where the send button is, it only appear the send button.
5. If i close Telegram and Open Again this work normally and the mic icon appear.

### Expected behaviour
When boot up the desktop telegram have the capabilities of send voice message.

### Actual behaviour
Only can't send text, unless when boot up, close and open telegram

### Configuration
**Operating system:** openSUSE Tumbleweed

**Version of Telegram Desktop:**2.9.0

**Installation source (Linux Only):** the official website

**Used theme**: none

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
tdesktop checks the presence of microphone only on start. If you don't have microphone conencted on start of tdesktop then recording voice messages won't be available.

**Comment by DevDorrejo** [comment]
> tdesktop checks the presence of microphone only on start. If you don't have microphone conencted on start of tdesktop then recording voice messages won't be available.

i use a laptop, and on previous version like -2.6 was working.

**Comment by ilya-fedin** [comment]
> i use a laptop, and on previous version like -2.6 was working

Nothing was changed about that

**Comment by DevDorrejo** [comment]
Doing the next change on the .desktop on the autostart folder of KDE, fix the issue.

`Exec=sleep 3s; /home/wedc/bin/Telegram/Telegram -workdir /home/wedc/.local/share/TelegramDesktop/ -autostart`

**Comment by ilya-fedin** [comment]
The issue can be closed then?
