### ISSUE TITLE
Recent Actions Does Not Include New Members

### ISSUE THREAD

**Issue by landry314** [telegramdesktop/tdesktop#16732]
When you Edit a group and go to Administrators then Recent Actions and are viewing All Actions, I do not see any New Member messages. When an admin adds a new member it should show up here.

This is working in the Android version but not in the MacOS version. They just aren't there.

I tried filtering just the New Members... nothing. New members were just added, I'm sure. It shows in Android client.

**Comment by Aokromes** [comment]
what macos version?

**Comment by landry314** [comment]
the newest one. i am always updated

**Comment by ilya-fedin** [comment]
Say exact version number.

**Comment by landry314** [comment]
im not stupid. i know how to update. 7.8.1. i always update everything immediately.

**Comment by ilya-fedin** [comment]
You're using not tdesktop, latest version of tdesktop is [2.9.0](https://github.com/telegramdesktop/tdesktop/releases)

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift

**Comment by landry314** [comment]
I apologize
