### ISSUE TITLE
Crash during spell check

### ISSUE THREAD

**Issue by l0drex** [telegramdesktop/tdesktop#16735]
### Steps to reproduce
1. Write a misspelled word
2. Right-click the word
3. Hover on "spell check" in the context menu

### Expected behaviour
Suggestions should pop up for a correct spelled word.

### Actual behaviour
The application crashes, terminated by signal `SIGSEV` (segmentation fault).

### Configuration
**Operating system:** Manjaro Linux

**Version of Telegram Desktop:** 2.8.11-2.0

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Distribution Package (Manjaro / Arch, installed via pamac)

**Used theme**: BreezeLight

**Language**: German

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
install official binary, send a crash report and post crash report tag here

**Comment by l0drex** [comment]
With v2.9.0, it doesn't crash anymore.
