### ISSUE TITLE
[Feature Request] New symbolic version of icon

### ISSUE THREAD

**Issue by andirsun** [telegramdesktop/tdesktop#16739]
### Describe the solution you'd like
Im on linux and telegram indicador is the only indicator that is different from all, maybe you can add an option in settings to change red icon to a symbolic ones (white-black version)

### Additional context
![Screenshot from 2021-08-02 01-41-34](https://user-images.githubusercontent.com/22928302/127815671-cf735d80-1cae-4e29-a4fd-59c0887b05e8.png)

**Comment by ilya-fedin** [comment]
The problem is you can't detect whether you should use white icon or black icon automatically and tdesktop avoids adding new settings. So, until some API from DEs appear so that there wouldn't be needed an option, this is a no-go most likely.

**Comment by andirsun** [comment]
Thanks for answer, so How can I change it manually ?

**Comment by ilya-fedin** [comment]
Telegram asks system icon theme for `telegram-{attention-,mute-}panel` icons for tray icon and fallbacks to app icon that is asked as `telegram` from icon theme. If your icon theme has such icons, they will be used.
