### ISSUE TITLE
[Question] Why screenshare audio doesn't work on Linux ("Share System Audio" Option Missing).

### ISSUE THREAD

**Issue by abish7643** [telegramdesktop/tdesktop#16730]
# Works on Windows (2.9)
![photo_2021-07-31_20-12-26](https://user-images.githubusercontent.com/42410225/127743492-d620888b-fb4b-4821-97cc-6efcd064ef16.jpg)

# No "Share System Audio" on Ubuntu (2.9)
![Screenshot from 2021-07-31 20-08-14](https://user-images.githubusercontent.com/42410225/127743522-3c1051ce-a5f9-44a1-b14b-d2574acc156f.png)
![Screenshot from 2021-07-31 20-08-26](https://user-images.githubusercontent.com/42410225/127743532-0a060fbd-dbab-4e29-b411-75828b6ed980.png)

**Comment by KaveriTS** [comment]
Same issue for me. Kindly fix this, since we are being vulnerable to switch to Windows just for accessing this feature.

**Comment by Aokromes** [comment]
no yet implemented.

**Comment by abish7643** [comment]
Will this be implemented in the future? @Aokromes

**Comment by ilya-fedin** [comment]
> Will this be implemented in the future?

Well, changes are not high since cross platform audio library used by tdesktop (openal) doesn't support that and preston was forced to write native code. He is not on Linux expert, so if no one from the community implement that, then there are high chances that this will remain a Windows (and maybe also macOS) exclusive feature.

**Comment by ilya-fedin** [comment]
> no yet implemented.

I think the question is answered

**Comment by abish7643** [comment]
> > Will this be implemented in the future?
> 
> Well, chances are not high since cross platform audio library used by tdesktop (openal) doesn't support that and preston was forced to write native code. He is not a Linux expert, so if no one from the community implement that, then there are high chances that this will remain a Windows (and maybe also macOS) exclusive feature.

Disappointing to hear that, hope someone can find a way and sort this out.
Closing this question.

**Comment by vimpostor** [comment]
Even when this is not implemented in Telegram itself, it is still very easy to workaround this on Linux. Just use Pipewire, and use a Audio Routing GUI like qjackctl via the Pipewire Jack bridge and connect any Desktop audio to Telegram manually.
Maybe not as easy as clicking a simple checkbox, but certainly more powerful.

<img width="414" alt="Screenshot_20210801_170935" src="https://user-images.githubusercontent.com/21310755/127775943-33cf7a50-3cb8-4c2d-9a9c-8a3c5817e216.png">

**Comment by ilya-fedin** [comment]
I don't understand why one would want such a checkbox when there are so powerful tools

**Comment by abish7643** [comment]
> I don't understand why one would want such a checkbox when there are so powerful tools

Still the easiest way for an end user is a checkbox. There's no denying that. People judge that everyone using linux is a geek, which is never the fact.

**Comment by ilya-fedin** [comment]
There's a problem that complicates the situation in a way: there's a zoo of audio systems in Linux

It seems it's better to let use geek utilities rather than implemeting one specific API (pipewire, for instance) and hearing complains of other audio systems users (ALSA, OSS, pulseaudio)

**Comment by abish7643** [comment]
I thought most distributions use pulseaudio. Apologies for my lack of knowledge.

**Comment by abish7643** [comment]
> There's a problem that complicates the situation in a way: there's a zoo of audio systems in Linux
> 
> It seems it's better to let people to use geek utilities rather than implemeting one specific API (pipewire, for instance) and hearing complains of other audio systems users (ALSA, OSS, pulseaudio)

I thought most distributions use pulseaudio. Apologies for my lack of knowledge @ilya-fedin .

**Comment by ilya-fedin** [comment]
There are always minorities who use alternative audio systems and want support loudier

**Comment by TheTimeBeing** [comment]
> I don't understand why one would want such a checkbox when there are so powerful tools



> > I don't understand why one would want such a checkbox when there are so powerful tools
> 
> Still the easiest way for an end user is a checkbox. There's no denying that. People judge that everyone using linux is a geek, which is never the fact.

Yeah! people like me. The workaround might be more powerful but as far as my knowledge goes, it seems pretty super hard.

**Comment by TheTimeBeing** [comment]
> There's a problem that complicates the situation in a way: there's a zoo of audio systems in Linux
> 
> It seems it's better to let people to use geek utilities rather than implemeting one specific API (pipewire, for instance) and hearing complains of other audio systems users (ALSA, OSS, pulseaudio)

:(

**Comment by KaveriTS** [comment]
> There's a problem that complicates the situation in a way: there's a zoo of audio systems in Linux
> 
> It seems it's better to let people to use geek utilities rather than implemeting one specific API (pipewire, for instance) and hearing complains of other audio systems users (ALSA, OSS, pulseaudio)

That's one hard pill to swallow aspect which I didn't think of. Thanks for pointing it out.

**Comment by john-preston** [comment]
I have no idea how to do that. I did that on Windows using windows-specific code that I wrote based on Chromium loopback audio device code, which also exists only on Windows, not on macOS or Linux.

Discord managed to implement this feature on macOS but in very non-user-friendly way, forcing the user to install system extension which requires the system reboot and in new hardware / macOS versions requiring user to reboot into the Recovery mode to allow the extension (see https://support.discord.com/hc/en-us/articles/1500006741102-macOS-Screen-Share-with-Audio-Update-FAQ).

I'm not ready for that yet :/ And I don't know about the Linux solutions as well.

**Comment by iMonZ** [comment]
On macOS, it doesn't work either for me.
On Linux as I read it correctly you can do that with FFmpeg https://askubuntu.com/a/682793

It would be so great if this is going to be fixed
At least we can keep one issue open for tracking and discussions

**Comment by ilya-fedin** [comment]
> On Linux as I read it correctly, you can do that with this tutorial: https://sites.google.com/site/installationubuntu/audio-and-video-in-ubuntu/record-internal-audio

This tutorial is for end user, it's you who should choose it

> Maybe this can work with this Library: https://doc.qt.io/qt-5/qaudioinput.html

QtMultimedia is a no-go due to its size
