### ISSUE TITLE
Documentation issue: character '\' must be documented as special characters

### ISSUE THREAD

**Issue by KES777** [telegramdesktop/tdesktop#16731]
### Steps to reproduce
1.  goto https://core.telegram.org/bots/api#formatting-options
2. Try to send string: '\\\\.' it is counted as **one \\** and **one .** and I get error that '.' must be escaped.
But notice that . is escaped and \\ is not (because it is not on the list)

When I escape \\ and . then error gone:  '\\\\\\.'

So '\\' must be listed as **required to escape**

### Expected behavior
In all other places characters '\\', '_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!' must be escaped with the preceding character '\\'.

### Actual behavior
'\\' is not listed as **must be escaped**

Sorry, I did not find where I should report documentation bugs

**Comment by ilya-fedin** [comment]
This tracker is tdesktop-only

**Comment by KES777** [comment]
Could you please hint where report bug for API?

**Comment by ilya-fedin** [comment]
I don't know such a place, probably there's no one and you should contact support...
