### ISSUE TITLE
Hearing annoying sound in group Voice Chat

### ISSUE THREAD

**Issue by tumon-art** [telegramdesktop/tdesktop#16733]
I am using Ubuntu 21.4 
In the new update, I am facing this problem.

**Comment by amoxocillina** [comment]
i Confirm the same on Linux Mint 20.1 Cinnamon also. All started since version 2.9.0 upgrade.
Chat members speech sounds like containing clicking spikes or some sort of clipping distortion, however the soundcard sounds fine reproducing any other multimedia stuff like youtube with any browser or mp3s/flacs with vlc or similar players

**Comment by tumon-art** [comment]
> i Confirm the same on Linux Mint 20.1 Cinnamon also. All started since version 2.9.0 upgrade.
> Chat members speech sounds like containing clicking spikes or some sort of clipping distortion, however the soundcard sounds fine reproducing any other multimedia stuff like youtube with any browser or mp3s/flacs with vlc or similar players

I have already downgraded Telegram. This is so annoying.
The new version has become useless for me.

**Comment by kostya1000** [comment]
> i Confirm the same on Linux Mint 20.1 Cinnamon also. All started since version 2.9.0 upgrade.
> Chat members speech sounds like containing clicking spikes or some sort of clipping distortion, however the soundcard sounds fine reproducing any other multimedia stuff like youtube with any browser or mp3s/flacs with vlc or similar players

So have I on Ubuntu 20.04.2 & Telegram Desktop v. 2.9.0. Distortions are audible in voice chats. 
Any other audio in system sounds well.

**Comment by mariosant** [comment]
Same applies here - normal voice calls have cracks and distortion as well. Ubuntu 21.04 & TG desktop 2.9.0.

**Comment by anon5114** [comment]
Same sound problem after update to 2.9.0 but on windows 10

**Comment by amoxocillina** [comment]
> Same sound problem after update to 2.9.0 but on windows 10

Some friends are confirming the same cracking noise on windows 10 also, both on private calls and on chat groups as well

**Comment by tsmukan** [comment]
Confirm problem with cracking noise on Windows 10 after 2.9 update. I have problem only on my laptop (Asus Zephyrus G14) using built-in dynamics. My friend has the same problem on the same laptop. No problems with external dynamic. Also I have no problems on my desktop

**Comment by gleb-chipiga** [comment]
Same problems with calls and voice chats on Ubuntu 18.04 and telegram desktop 2.9 snap.

**Comment by abish7643** [comment]
Same problem on both personal and group chat.

**Comment by KaveriTS** [comment]
Experiencing the same issue.

**Comment by GooseBumpsOS** [comment]
Same problem after update to 2.9.0 on Ubuntu 20.04

**Comment by hgkjshegfskef** [comment]
After bisecting, the responsible commit is https://github.com/telegramdesktop/tdesktop/commit/bbbcd37b8f4c6f8993d3e51a883b5e1494816c5c and in the submodule respectively https://github.com/desktop-app/lib_webrtc/commit/810973807a7f492393e7f9b8ceb3a1e89dc7eb16, authored by @john-preston. Reverting the commit fixes the crackling.

To reproduce, checkout https://github.com/telegramdesktop/tdesktop/commit/bbbcd37b8f4c6f8993d3e51a883b5e1494816c5c and apply [the patch](https://github.com/telegramdesktop/tdesktop/files/6947655/bbbcd37b.txt) for the code to compile. Additionally, revert https://github.com/desktop-app/lib_webrtc/commit/810973807a7f492393e7f9b8ceb3a1e89dc7eb16 in the submodule.

Also, a note to developers: please, don't push the code that doesn't compile to upstream. It makes it a lot harder to bisect if one has to patch every case, and sometimes patch it slightly differently (so one cannot even have one patch saved and apply it over and over again), and in general, the inability to compile stalls the process tenfold. Github provides free continuous integration tools for this purpose.

**Comment by krail** [comment]
Confirm audio problems on xubuntu 21.04 + tg 2.9

**Comment by john-preston** [comment]
@hgkjshegfskef Thanks for the bisecting.

I'll buffer some more data there, I didn't have problem with 5 / 3 myself so I hoped it will be enough. Unfortunately the more you buffer (before it was 20 / 18), the more is the delay between the playback and recording (it was (20-5) * 10 = 150ms more before that commit) which affects echo cancellation :( I hope 7 / 5 will work fine.

**Comment by hgkjshegfskef** [comment]
I have tested with latest commit, 7/5 doesn't crackle for me.

**Comment by john-preston** [comment]
Well, really it should "just work", nobody is going to adjust them by hand (by nobody I mean 99.9% of the users). Audio input / output is a realtime thing, if it doesn't do it well on 50ms buffers it won't work too well anyway :(
