### ISSUE TITLE
Can't keep using new layout in v0.9.26

### ISSUE THREAD

**Issue by Anonymous1157** [telegramdesktop/tdesktop#1673]
My monitor is 1280x1024, and I was able to use the new layout with my messages on the left in v0.9.24. I'm running v0.9.26 now and the minimum width seems to have been changed to 1360px, so I can't use the new layout anymore.

I'm using the official 64-bit Linux stable release on Gentoo.

**Comment by telegramdesktop** [comment]
@Anonymous1157 Yes, it is starting after 1366px now.

**Comment by Anonymous1157** [comment]
@telegramdesktop I want to keep using the new layout. Can the limit be changed back to what it was, or lowered to 1280? It was working well and I liked it that way.

**Comment by pongo** [comment]
+1
