### ISSUE TITLE
Screen sharing video quality is really bad sometimes and  call quality is poor on ubuntu 20.04

### ISSUE THREAD

**Issue by rthiru96** [telegramdesktop/tdesktop#16747]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

- Good screen sharing quality(Video quality must be better while sharing)
- Need to make a call from first attempt without any interruption and call quality needs to be improve

### Actual behaviour
Tell us what happens instead

- while screen sharing video quality is really poor and screen sharing options are really mess .

- Sometimes is really hard to make a call at the first attempt but if I if attempt to call after first attempt(2nd or 3rd attempt) it is working.

### Configuration
**Operating system:**
Ubuntu 20.04

**Version of Telegram Desktop:**
2.9(latest)

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by pran01** [comment]
Same problem. The quality of screen sharing is really bad and voice in voice call keeps breaking

**Comment by john-preston** [comment]
Screencast bitrate should improve in one-on-one calls in version 2.9.2.

**Comment by john-preston** [comment]
It should be released later today.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16487
