### ISSUE TITLE
Export stops due to API error 400 CHANNEL_PRIVATE

### ISSUE THREAD

**Issue by SebiderSushi** [telegramdesktop/tdesktop#16745]
### Steps to reproduce
1. Create a group
2. Convert to megagroup by setting "Chat history for new members" to "Visible"
3. Delete the group
4. Start a chat export of all conversations, groups and channels

### Expected behaviour
The telegram API deletes the group completely. Telegram Desktop remains able to export any remaining groups.

### Actual behaviour
The telegram API still returns the group when querying the chat list. The deleted supergroup is inaccessible and Telegram Desktop stops exporting data when hitting the API error.

### Configuration
**Operating system:** Manjaro Linux

**Version of Telegram Desktop:** 2.8.11

**Installation source (Linux Only)** - distribution package

**Used theme**: Preinstalled "Night mode"

<details><summary><b>Technical info</b>:</summary>

I tried using `pyrogram` to delete the remains of the megagroup, this is what i found:

The offending group appears once as a `types.Chat` and has the attribute `migrated_to` where it mentions the megagroup it was migrated to.

The second entry is of course the migrated supergroup. It is of `types.ChannelForbidden` and has the attributes `"broadcast": false` and `"megagroup": true`.

Since it's a ChannelForbidden i am unable to delete or access it. I can't remove it from the chat list so tdesktop will always fetch it and stumble over it.

I'm not sure whether tdesktop should just be able to ignore the API error in this case and carry on to export other conversations or if the telegram backend should also be fixed so that deleting a megagroup actually removes all traces of it as expected.

Where can such issues with the Telegram backend be reported?
</details>

**Comment by SebiderSushi** [comment]
Okay it turns out that the traces of the deleted groups get cleaned up after some time passes, so the backend seems to be OK.

Would it be useful if `tdesktop` could skip conversations after hitting an API error 400 CHANNEL_PRIVATE when exporting chats and just carry on with the remaining conversations?

This would cause a lot less confusion when cleaning up chats & groups and then running a chat export immediately afterwards.

**Comment by tcNmjeD6SpVrpLC** [comment]
It is the problem of migrated chats @SebiderSushi it shouldn't skip anything.

**Comment by anton-ryzhov** [comment]
I faced with the same issues with a channel (not a group) — it was either deleted or made private, and now export is fully broken for me.

> Would it be useful if tdesktop could skip conversations after hitting an API error 400 CHANNEL_PRIVATE when exporting chats and just carry on with the remaining conversations?

That will definitely solve the issue, hope that would be implemented eventually.

> Okay it turns out that the traces of the deleted groups get cleaned up and removed from the telegram api chat list after some time passes

@SebiderSushi Do you have an estimate how long does it take?

**Comment by john-preston** [comment]
@anton-ryzhov > .. now export is fully broken for me ..

You mean you can start a new export and it still fails on the same channel each time?

**Comment by SebiderSushi** [comment]
> @SebiderSushi Do you have an estimate how long does it take?

For me it took a few hours, mabe even less than one?

**Comment by anton-ryzhov** [comment]
@john-preston yes, that's what happening for last few days — I can't include private channels to a backup now, otherwise the error interrupts the export.

I have logs, it's from v3.4.3:
[logs.zip](https://github.com/telegramdesktop/tdesktop/files/7810787/logs.zip)

**Comment by dm17** [comment]
So seeing this error means the backup finished minus the stuff that error applies to? This would be good to make explicit.
Thanks!

**Comment by anton-ryzhov** [comment]
No, backup stops at this point — other chats / channels aren't exported at all, export output file (when json) is corrupted:
```
$ jq . result.json 
parse error: Unfinished JSON term at EOF at line 13532, column 4
```

BTW, the screenshot of the error:
![image](https://user-images.githubusercontent.com/556933/148662533-3fbab9ab-9422-4854-8bd8-0c435132d19a.png)

**Comment by TheFlanker** [comment]
Hello.

I have the same problem in the latest version of the Telegram Desktop for Windows.
Export fails like @anton-ryzhov screenshot.
And I don't even know which channel is causing this error.
Is there some way to find this private channel? Just to find out its name.

Last time I was doing data export 18/11/2021 and there was no such problem, it completed successfully.

**Comment by john-preston** [comment]
@anton-ryzhov This looks like a server side bug, I've asked about it and I'll get back when I get some information.

**Comment by john-preston** [comment]
@anton-ryzhov Can you please provide your username or user_id (the one that gets the error).

**Comment by anton-ryzhov** [comment]
@john-preston so it was not intended that `channels_getLeftChannels` returns inaccessible anymore channels? Should maybe the client also handle this and skip such on export?

Is your tlg id `@preston`?

**Comment by john-preston** [comment]
@anton-ryzhov Yes it is.

**Comment by anton-ryzhov** [comment]
Sent you my ID. Thanks for help

**Comment by ModischFabrications** [comment]
Same error here. No (active) private chats, public groups or similar, still get "400 private chat". Exporting only bot chats still works, seems like it's some generic chat.

**Comment by john-preston** [comment]
@anton-ryzhov Can you please check again? It should be fixed from the server side.

**Comment by ModischFabrications** [comment]
Not Anton, but it works in my case. Thanks for fixing!

**Comment by anton-ryzhov** [comment]
Works for me as well. Thank you!

**Comment by TheFlanker** [comment]
@john-preston Now working. ty!

**Comment by Aokromes** [comment]
@SebiderSushi  test
