### ISSUE TITLE
[Feature Request] Add close button to sidebar with emoji, stickers and gifs

### ISSUE THREAD

**Issue by amaralex1** [telegramdesktop/tdesktop#16741]
When emoji\sticker\gifs sidebar active there is no easy way to hide it. 
I'd like to have close button in right corner (like in user info sidebar for example). 
Right now I need to call another sidebar and use close button here.

**Comment by Aokromes** [comment]
https://i.imgur.com/Jow3DcO.png

**Comment by ilya-fedin** [comment]
#3399

**Comment by amaralex1** [comment]
> #3399

Didn't saw that issue, was searching by Feature request, my bad.



> https://i.imgur.com/Jow3DcO.png

I mean there, when you click highlighted button "User info" appears when I want to hide all sidebars by this button 
![image](https://user-images.githubusercontent.com/28701974/127862558-cfdcb9cf-4ccd-4711-ade7-75da9261d630.png)

**Comment by john-preston** [comment]
@amaralex1 You show this panel by clicking on the emoji icon in the input field. You can just click it second time.
