### ISSUE TITLE
DESKTOP_APP_DISABLE_GTK_INTEGRATION flag is ignored in version 2.9.0

### ISSUE THREAD

**Issue by livingsilver94** [telegramdesktop/tdesktop#16742]
### Steps to reproduce
1. On Linux, try to build tdesktop with no GTK library installed and with `-DDESKTOP_APP_DISABLE_GTK_INTEGRATION=ON`
2. See tdesktop requiring GTK3 and libwebkit as if `-DDESKTOP_APP_DISABLE_GTK_INTEGRATION=OFF`

### Expected behaviour
tdesktop should build without requiring GTK3 and libwebkit

### Actual behaviour
tdesktop requires unwanted libraries

### Configuration
**Operating system:** Solus

**Version of Telegram Desktop:** 2.9.0

**Installation source (Linux Only):** https://github.com/telegramdesktop/tdesktop/releases/download/v2.9.0/tdesktop-2.9.0-full.tar.gz

[Here](https://dev.getsol.us/source/telegram/browse/master/package.yml$62) is the cmake command we're using on Solus to build tdesktop.

**Comment by ilya-fedin** [comment]
Please don't disable gtk integration if you don't want to give bad UX for your users

**Comment by livingsilver94** [comment]
We shipped Telegram to hundreds or thousands of users without GTK integration without issue, for months. Nobody ever complained, myself included. Even [RPM fusion](https://github.com/rpmfusion/telegram-desktop/commit/83b8cb923398f933c7e9aba84636103294374620) ships Telegram without GTK integration. This is to say that if you provide build options, people will tinker with them. Options exist for this very reason: customization.

With that said, there is a regression in 2.9.0 since in previous versions all was working well.

**Comment by ilya-fedin** [comment]
>  Even [RPM fusion](https://github.com/rpmfusion/telegram-desktop/commit/83b8cb923398f933c7e9aba84636103294374620) ships Telegram without GTK integration.

They also disable Wayland integration. It's not a good example to look up to.

> This is to say that if you provide build options, people will tinker with them.

I understand that if you would be a source-based distro, but you disable subset of features for entire userbase and they don't have possibility to use them.

> With that said, there is a regression in 2.9.0 since in previous versions all was working well.

I can't reproduce anything like that.

**Comment by ilya-fedin** [comment]
> This is to say that if you provide build options, people will tinker with them.

These options are added by community and maintained by community. They may and will break from release to release and there's no guarantee they will be fixed.

**Comment by ilya-fedin** [comment]
>  Options exist for this very reason: customization.

Well, tdesktop follows 'less options is better' paradigm

**Comment by livingsilver94** [comment]
Since tdesktop 2.9.0, `DESKTOP_APP_DISABLE_WEBKITGTK=ON` should be passed as well to disable GTK integration entirely.
