### ISSUE TITLE
Incorrect buttons rendering in title

### ISSUE THREAD

**Issue by pvnhome** [telegramdesktop/tdesktop#16740]
### Steps to reproduce
1. Restore minimized window
2. Click on title
![image](https://user-images.githubusercontent.com/9364110/127816593-6a9aa679-9ec5-4626-b052-5a724683ff1c.png)
3. Look at Minimize, Maximize, and Close buttons
![image](https://user-images.githubusercontent.com/9364110/127816814-92d457c6-a17e-4872-aacb-1e14c40e3625.png)

### Expected behaviour
![image](https://user-images.githubusercontent.com/9364110/127816858-e825b31c-cc92-4b2c-a758-e98984a35881.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/9364110/127816907-52579001-410b-4f4f-a76e-c3f833aad468.png)

### Configuration
**Operating system:** Windows7. Service Pack 1.

**Version of Telegram Desktop:**
![image](https://user-images.githubusercontent.com/9364110/127817269-ec1f87cc-d83a-479c-9f52-31052d9b482e.png)

**Used theme**:
![image](https://user-images.githubusercontent.com/9364110/127817396-2da05aa3-6274-4f20-999c-618b5e2de0aa.png)

**Comment by pvnhome** [comment]
Sometimes title look as on picture below:

![image](https://user-images.githubusercontent.com/9364110/127818125-5b09aeb8-9e86-4602-9bb4-30c1a0a81052.png)

**Comment by ilya-fedin** [comment]
#16721
