### ISSUE TITLE
Does not obey mouse scroll direction

### ISSUE THREAD

**Issue by Anonymous1157** [telegramdesktop/tdesktop#1674]
Telegram Desktop doesn't obey KDE's mouse scroll direction settings. I am using the reversed scroll direction (Push up to go down, like a finger on a touchscreen) and Telegram still scrolls the conventional way around.

I'm using the official 64-bit Linux stable release on Gentoo.

**Comment by telegramdesktop** [comment]
@Anonymous1157 Are other Qt apps obey it?

**Comment by auchri** [comment]
See #827 #508 #494

**Comment by Anonymous1157** [comment]
@telegramdesktop All Qt4 and GTK+2/3 applications work as expected. Telegram Desktop is my only Qt5 application.

According to the bugs @auchri referenced, this is an upstream bug in Qt5.3+. Does anyone know of an upstream bug report? I tried looking but can't seem to find one.

**Comment by Anonymous1157** [comment]
Google recently updated Chrome/Chromium to use xinput2 for smooth scrolling, and that program stopped obeying my and other users' scroll direction settings as well. [See this Chromium bug report.](https://bugs.chromium.org/p/chromium/issues/detail?id=582547)

Interestingly, buried in that report is information about the correct way to change the system-wide scroll direction so that absolutely all applications should obey the scroll settings, including Telegram.
```
xinput set-prop <mouse:id_or_name_here> "Evdev Scrolling Distance" -1 1 1
```
(Hilariously, this re-reversed the reversed mouse in applications that were already working, but fixing that was as simple as disabling KDE's setting.)

As far as I can tell, this is the new "correct" way to change the system scroll direction until the desktop environments have a GUI to do it this way themselves. I wrote a trivial script that runs the `xinput` command and added it as a startup item in KDE, and everything is working the way I want now.

So, essentially, this was never a bug in Telegram, but is actually a side effect of the intended behavior of xinput2, which is used by Qt5.3+, which is used by Telegram. That's my understanding.
