### ISSUE TITLE
Need to share screen with single user instead creating groups and share

### ISSUE THREAD

**Issue by rthiru96** [telegramdesktop/tdesktop#16748]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.

### Describe the solution you'd like

- At the moment user interfaces are bit mess for addition options like screen shre oprions in group and some other adition features too.
- We are expecting screen sharing with single user too.

### Describe alternatives you've considered

- [ ] Need to improve user interfaces
- [ ] Needed screen share options with single user.

**Comment by Aokromes** [comment]
it's already there on 2.9.

**Comment by rthiru96** [comment]
@Aokromes thanks
