### ISSUE TITLE
Scheduled messages

### ISSUE THREAD

**Issue by Kingofki305** [telegramdesktop/tdesktop#16743]
### Expected behaviour
We can delete or immediately send the scheduled messages (scheduled before some time or days) whenever we want.

### Actual behaviour
Cannot delete or "send now" the messages which were scheduled before.

### Configuration
**Operating system:** windows 10

**Version of Telegram Desktop:** 2.9

**Used theme**: tinted
![tg bug](https://user-images.githubusercontent.com/88315963/127836507-5713de26-1245-4b98-9cde-7560841611ce.jpg)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16726

**Comment by Kingofki305** [comment]
> #16726
sorry but is it resolved now? as i am not able to reschedule or delete the messages yet.
![image](https://user-images.githubusercontent.com/88315963/127875701-47f649ba-b4a1-4767-bbc8-9d18a39ab8cc.png)

![image](https://user-images.githubusercontent.com/88315963/127875823-7084a8cd-5cf3-4b37-8cb2-9b82f5d81261.png)
