### ISSUE TITLE
No minimise option in Telegram desktop 2.9

### ISSUE THREAD

**Issue by BryceSteuer** [telegramdesktop/tdesktop#16755]
### Steps to reproduce
1. Download Telegram Desktop 2.9 on Windows 10
2. Open the app
3. 

### Expected behaviour
Tell us what should happen
In the upper right hand corner of the screen when the app is open, there should be (and was in previous versions) an option to minimise the window, restore it down, or close it. 

### Actual behaviour
Tell us what happens instead
I find none of the above mentioned options in the Telegram window; the only way I can exit the window is either by switching to another open window, or else closing the window by hovering over the icon in my toolbar.
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.9
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Dark mode
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
> ### Actual behaviour
> Tell us what happens instead
> I find none of the above mentioned options in the Telegram window; the only way I can exit the window is either by switching to another open window, or else closing the window by hovering over the icon in my toolbar.

what's your video card?

**Comment by BryceSteuer** [comment]
Video card? Sorry, I do not understand what you mean.

**Comment by fcore117** [comment]
I disabled Angle backend at all and i am glad it can be disabled, Telegram works much better and more robust again.

**Comment by kariby** [comment]
> I disabled Angle backend at all and i am glad it can be disabled, Telegram works much better and more robust again.

thanks! your advice helped me
now i can minimize the window 👍

**Comment by Aokromes** [comment]
> Video card? Sorry, I do not understand what you mean.

you have intel, amd or nvidia video card?

**Comment by fcore117** [comment]
NVidia but in my mind i should **not** need GPU for communication app and thus disabled it. Everything functions very well.

**Comment by kariby** [comment]
> > Video card? Sorry, I do not understand what you mean.
> 
> you have intel, amd or nvidia video card?
> cc @kariby @fcore117

i have nvidia graphics card

**Comment by Aokromes** [comment]
what model? because my self i have nvidia 960gtx and no problem.

**Comment by kariby** [comment]
> what model? because my self i have nvidia 960gtx and no problem.

nvidia geforce 840M
today i disabled Angle backend and it helped. now i turned it back on and it works... magic!

**Comment by BryceSteuer** [comment]
@Aokromes 
I have Intel video card; but now I need to disable Angle backend as that seems to be working for most of us

**Comment by john-preston** [comment]
@BryceSteuer Does it happen on 2.9.2? With ANGLE backend set to Auto. Can you provide a screenshot?

**Comment by BryceSteuer** [comment]
@john-preston 
No, on 2.9.2 the issue is resolved.

**Comment by john-preston** [comment]
@fcore117 All features have some sort of CPU fallback, but those fallback implementation may be very slow and CPU-hungry and the default path relies on GPU availability.
