### ISSUE TITLE
Silent message is not silent on an Android receiver sent from the Desktop app

### ISSUE THREAD

**Issue by o1dnik** [telegramdesktop/tdesktop#16754]
### Steps to reproduce
1. install Telegram 2.9.1 on Mac OS BigSur
2. Send a "silent message"
3. Experience a non-silent delivery on an Android app

### Expected behaviour
Silent message should be silent... 🧐

### Actual behaviour
Silent is not silent anymore... 🧐

### Configuration
Mac OS BigSur 11.5.1 (20G80)
Telegram Desktop v.2.9.1
Installed from the official website build.

Should I add logs ? BTW where do I find them on Mac OS ?

**Comment by john-preston** [comment]
I can't reproduce, at least on 2.9.2.

I type in a message, press Send - I get a notification with sound on Android. I mark it as read from the notification.

Then I type in another message, right click Send and press Send without sound - I get a notification without sound on Android.
