### ISSUE TITLE
[Feature Request] Work mode/no fancy mode/simple mode

### ISSUE THREAD

**Issue by fcore117** [telegramdesktop/tdesktop#16756]
Please add option that disables all animated icons and fancy effects, even when receiving it should display no emoticons and stuff. There are certain people who just use Telegram for information, call communication, exchange files, links and those extra things(emoji buttons, emoji from others, flashy things) only distracts and are annoying. Just a suggestion but would be really useful.

In short: Disable fancy mode checkbox, Telegram restarts and no emoji buttons and you wont receive emoji&animations from others too.

**Comment by Aokromes** [comment]
you can disable animations on advanced

**Comment by fcore117** [comment]
> you can disable animations on advanced

Yes i have used that option years, nothing serious but still would liked way to disable fancy(inc emoticons&gifs sent from others) functions 100% but well. For me Telegram goal is to be serious & robust communicator and that's it. Sometimes in speed i often hit emote button and distracts then my work activities. You can decide to close this but i thought it is worth to mention.

**Comment by fcore117** [comment]
I just hope they do it in official version some day as Telegram is world fastest c++ IM app compared to other bloat and is become main work related app too for quickly sending this or that picture from camera or calling and sending files. No use on fancy flashy emoji or whatever stuff, but often hitting that emoji button instead of message or file button. Industry use is quite important.

**Comment by john-preston** [comment]
@fcore117 There definitely won't be a mode without displaying emoji in the messages, they are part of the text. Big / animated emoji could be disabled in Settings.
