### ISSUE TITLE
Desktop 2.9 version crashes with scheduled channel messages

### ISSUE THREAD

**Issue by goedzo** [telegramdesktop/tdesktop#16752]
### Steps to reproduce
1. Create a scheduled message in your channel
2. Wait until this message is published
3. Got to channel after this message appears.
4. Telegram crashes

### Expected behaviour
Tell us what should happen
Also if messages are already scheduled, the reschedule option is no longer present in the queue when you right click a message from other moderators.

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
2.9
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official site, portable version.
**Used theme**:
Dark mode
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by 23rd** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16726#issuecomment-890527658
