### ISSUE TITLE
Telegram desktop client for linux got timeout in receiving messages

### ISSUE THREAD

**Issue by AMV007** [telegramdesktop/tdesktop#16750]
### Steps to reproduce
1. receive message
2. 
3. 

### Expected behaviour
Immideately receive message at the phone and at the desktop client

### Actual behaviour
delay at desktop client receive message 30-150 seconds

### Configuration
**Operating system:**
Ubuntu 20.04

**Version of Telegram Desktop:**
2.9

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
download from website

**Used theme**:
light

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
That's intended, to avoid ding-ing simultaneously

**Comment by AMV007** [comment]
But it very big difference - up to couple minutes.
I see message at my huawei band - go to desktop to answer to it, but it still not here, need to wait couple minutes to answer it ?
Another messengers are better in this case.

**Comment by AMV007** [comment]
Also - programming at PC, cell phone at another room, got message at band, trying to answer - but, no desktop client not have this message )

**Comment by ilya-fedin** [comment]
The notification is delayed, but message itself should be there

**Comment by AMV007** [comment]
I got delay with messages, and this is big problem.

**Comment by ilya-fedin** [comment]
> I got delay with messages, and this is big problem.

You still can open the chat in application and see message there

**Comment by AMV007** [comment]
I'm opening chat at desktop application and no messages here, they appearing in application after 30-150 seconds.
Today record - 5 minutes )

**Comment by ilya-fedin** [comment]
Are you sure you're running 2.9? That sounds like you're using an old version that were disabled in server message queues.

**Comment by AMV007** [comment]
![image](https://user-images.githubusercontent.com/9484737/128055517-96f6f5f1-3412-46b2-ad57-0d6caba8ad9b.png)

**Comment by ilya-fedin** [comment]
Maybe you have network problems?

**Comment by AMV007** [comment]
same behaviour at my home and at my work - different networks, different providers, different PC.

**Comment by ilya-fedin** [comment]
Well, I can't reproduce that, works just fine

**Comment by AMV007** [comment]
I'm happy for you )))
What I should to with it ?

**Comment by ilya-fedin** [comment]
Personally I have no idea, that sounds like networking problems.

**Comment by 23rd** [comment]
Do you have a configured proxy in your client?

**Comment by AMV007** [comment]
not have proxy.
I used proxy before, but now not using it.

**Comment by AMV007** [comment]
Specially disabled proxy in telegram.
Disabled IPv6.

My cell phone connected to the same WIFI network.
Desktop connected to the same network received message 10 minutes later after the phone !?
It's not a netowrk problems, but a desktop problem ))

Any official developer here ?

**Comment by AMV007** [comment]
Additionally - it's not a constant bug, usually all working as expected.
But time-to time, especially if you are not used chat a lot time, it's happen.

**Comment by BohdanK911** [comment]
Exactly same problem.

**Comment by AMV007** [comment]
Additional info:
OS: Ubuntu 20.04 on all PC.
mobile client, 2 PC in local network, 1 remote PC - all have same distro with same image and my telegram account.

Mobile client - instant receive message
1 PC in local network, locked - received same message
1 PC remote, locked - received same message

1 PC - I'm currently working - got delay waiting message about 2 min.

May be the problem, that telegram serve sending messages to same account in circle ?
so it sending my message to all my clients in circle : mobile client, remote PC, local PC, and only after it to my current PC ?

May be it's root cause of the delay ?

**Comment by AMV007** [comment]
additionally - added MTproto proxy in Amazon AWS, for my clients, problem still exist.
Looking like it's definitely server problem, not client.

May be I can try help telegram team to fix it free of charge, pls contact me for details ?

**Comment by AMV007** [comment]
looking like I found root case of the problem: I cloned images with telegram installed to multiple machines.
Need to reenter telegram at each machine for all work as expected
