### ISSUE TITLE
Broken window

### ISSUE THREAD

**Issue by snxx-lppxx** [telegramdesktop/tdesktop#16758]
### Steps to reproduce
1.  Made an update to version 2.9;
2.  Opened the application.

### Expected behaviour
The application window breaks if I click on an empty space in the upper corner.

### Actual behaviour
The application window breaks if I click on an empty space in the upper corner.

### Configuration
**Operating system:** Win7 (x64)

**Version of Telegram Desktop:** 2.9

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Dark Mode (Custom)

![image](https://user-images.githubusercontent.com/67647968/128257072-e7a7a552-4b37-4ac0-8727-af7e6219af03.png)
![image](https://user-images.githubusercontent.com/67647968/128257946-cb78a62c-a8ff-4589-9c8e-ef922fc900b5.png)
and
![image](https://user-images.githubusercontent.com/67647968/128257791-1331cf3b-66e2-42e3-90db-d7e88b4b1b81.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16721
