### ISSUE TITLE
Mute a user

### ISSUE THREAD

**Issue by Pouya47** [telegramdesktop/tdesktop#1675]
Hi
In our Telegram Group two of my frinds became angry and use bad words, I removed them, but they become very angry with me! ...
I think if group admin can mute some users for about 5 or 10 minute or 1 day, they will be calm :)
Can you add mute feature to telegram?

**Comment by DaFri-Nochiterov** [comment]
No API for that!
(-O_O)/ You can ask about new features in [![Twitter icon](https://twitter.com/favicon.ico)Twitter](https://twitter.com/telegram) or by clicking _Options → Ask question_

Just for read: [![Telegram icon](https://desktop.telegram.org/img/td_favicon_16x16.png) Feature Philosophy](https://core.telegram.org/tsi/feature_philosophy)

**Comment by Pouya47** [comment]
OK tnx
