### ISSUE TITLE
[Feature Request] Rearrange profile photos

### ISSUE THREAD

**Issue by nmahdi14** [telegramdesktop/tdesktop#16763]
Hi. Sometimes we need to rearrange our profile pictures, but to do so we have to delete them completely and then add them again. Great if they can be sorted without adding or removing. Thanks for your good program

**Comment by Aokromes** [comment]
wanted

**Comment by 23rd** [comment]
Can be closed?

**Comment by nmahdi14** [comment]
its a good option

**Comment by 23rd** [comment]
@nmahdi14 
Oh, sorry, I didn't expand on my question. 
In the 3.7.0 version users have an ability to set any your previous profile photo as main. So, technically, now you can rearrange profile photos without having to delete them all.
