### ISSUE TITLE
Regression: output sound crackling in 2.9

### ISSUE THREAD

**Issue by hgkjshegfskef** [telegramdesktop/tdesktop#16764]
### Steps to reproduce
1. Upgrade from 2.8 to 2.9.
2. Call somebody or receive a call.
3. Experience output sound crackling.

### Expected behaviour
No sound crackling.

### Actual behaviour
Sound is crackling similar to what was happening with pulseadio some time ago, which was solved by migrating to pipewire. Last good release was 2.8.10 (I haven't bisected), first bad release is 2.9.1. Crackling is always reproducible. I am using telegram-desktop-bin from AUR and started having crackling after upgrade, but also reproduced in 2.9.1 from flatpak. Downgrading to 2.8.10 works around the problem.

### Configuration
**Operating system:** Manjaro Linux

**Version of Telegram Desktop:** 2.9.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: telegram-desktop-bin from AUR, but also reproduced via flatpak one.

**Used theme**: dark

<details><summary><b>Logs</b>:</summary>
log.txt: can collect later if necessary

</details>

```
❯ pactl info
Server String: /run/user/1000/pulse/native
Library Protocol Version: 34
Server Protocol Version: 35
Is Local: yes
Client Index: 342
Tile Size: 65472
User Name: redacted
Host Name: redacted
Server Name: PulseAudio (on PipeWire 0.3.32)
Server Version: 14.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.usb-Audient_iD4-00.analog-stereo
Default Source: alsa_input.usb-Audient_iD4-00.analog-stereo
Cookie: redacted
❯ pipewire --version
pipewire
Compiled with libpipewire 0.3.32
Linked with libpipewire 0.3.32
```

**Comment by ilya-fedin** [comment]
#16733

**Comment by lokpozzta** [comment]
Ok
