### ISSUE TITLE
Poll list section on the group/channel info panel [Feature Request] 

### ISSUE THREAD

**Issue by iasj** [telegramdesktop/tdesktop#16767]
### Is your feature request related to a problem?
No, it's a feature request.

### Describe the solution you'd like
It would be great to have the current Polls displayed somewhere on the group/channel info panel.

The way this feature exists now is in a form of a message. It quickly gets eclipsed by normal messages in a large group. 

Although Telegram still lacks this functionality, the feature would only make sense if whomever created the Poll could set a timeout, after which Telegram would automatically send the result as a message for everyone to see. In this case, the Poll information would be poped out of the Poll list, and go to a history list, which could be a bit hidden away from view.

This, of course, would be somehow controlled by the group/channel creator/admins, ranging from [C.R.U.D](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) operations to setting   a maximum timeout interval in days. But those are just initial ideas.

**Comment by ruv** [comment]
> It would be great to have the current Polls displayed somewhere on the group/channel info panel.

A poll can be pinned and then it be visible at the top of the group.

Another option is to add the link to the poll into the description of the group — so it will be visible in the Group Info panel.

Yet another option is to add a tag into a poll question, like `#poll` — then all polls can be filtered by search to this tag. A missed feature is a link to search results in Telegram.

**Comment by 23rd** [comment]
The server has no API for displaying shared polls.

[bugs.telegram.org/c/1630](https://bugs.telegram.org/c/1630)
