### ISSUE TITLE
[Question] Where all the Voice Messages are stored (Windows)

### ISSUE THREAD

**Issue by Cosmotan01** [telegramdesktop/tdesktop#16762]
Hi,
where Telegram stores all the Voice Messages (on Windows). i don't ask for the "normal" Files.
Thx
Cheers

**Comment by 23rd** [comment]
You can look up the `media_cache` directory in the `tdata` directory.

**Comment by Cosmotan01** [comment]
> You can look up the `media_cache` directory in the `tdata` directory.

I ask for (Windows) not Android or iOS

**Comment by 23rd** [comment]
> I ask for (Windows, Desktop, PC) not Android or iOS

You have an answer to your question.
`%tdesktop_location%\tdata\user_data\media_cache\`

**Comment by Cosmotan01** [comment]
> > I ask for (Windows, Desktop, PC) not Android or iOS
> 
> You have an answer to your question.
> `%tdesktop_location%\tdata\user_data\media_cache\`

Thx
