### ISSUE TITLE
How to move or copy TelegramDesktop to another Linux

### ISSUE THREAD

**Issue by snewsa** [telegramdesktop/tdesktop#16761]
Hello, I have zipped ~/.local/share/TelegramDesktop/ from the old Linux and unpacked it to the new Linux where Telegram is freshly installed but never started. After starting Telegram with the copied folder it still ask for "Start messaging".

How to move TelegramDesktop from Linux Mint Cinnamon to a new Debian (10 with Cinnamon Desktop)?

> [2021.08.05 16:13:20] Launched version: 1005011, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
> [2021.08.05 16:13:20] Executable dir: /usr/bin/, name: telegram-desktop
> [2021.08.05 16:13:20] Initial working dir: /home/snews/
> [2021.08.05 16:13:20] Working dir: /home/snews/.local/share/TelegramDesktop/
> [2021.08.05 16:13:20] Command line: telegram-desktop --
> [2021.08.05 16:13:20] Executable path before check: /usr/bin/telegram-desktop
> [2021.08.05 16:13:20] Logs started
> [2021.08.05 16:13:20] Fontconfig version: 2.13.1.
> [2021.08.05 16:13:20] Connecting local socket to /tmp/4f7f0c9e4e5d4b7c3ea84d1fe2d21bbb-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
> [2021.08.05 16:13:20] This is the only instance of Telegram, starting server and app...
> [2021.08.05 16:13:20] Moved logging from '/home/snews/.local/share/TelegramDesktop/log_start0.txt' to '/home/snews/.local/share/TelegramDesktop/log.txt'!
> [2021.08.05 16:13:20] Primary screen DPI: 96
> [2021.08.05 16:13:20] Error: failed to load 'gdk_x11_drawable_get_xdisplay' function!
> [2021.08.05 16:13:20] Getting DE, XDG_CURRENT_DESKTOP: 'X-Cinnamon'
> [2021.08.05 16:13:20] Getting DE, DESKTOP_SESSION: 'lightdm-xsession'
> [2021.08.05 16:13:20] Getting DE, KDE_SESSION_VERSION: ''
> [2021.08.05 16:13:20] Getting DE, GNOME_DESKTOP_SESSION_ID: 'this-is-deprecated'
> [2021.08.05 16:13:20] DE: Gnome
> [2021.08.05 16:13:20] Tray Icon: Try Qt = [TRUE], Prefer appindicator = [FALSE]
> [2021.08.05 16:13:20] App Info: reading settings...
> [2021.08.05 16:13:20] App Info: reading encrypted settings...
> [2021.08.05 16:13:20] Lang Info: Loaded cached, keys: 3261
> [2021.08.05 16:13:20] Lang Error: Unexpected tag (key 'lng_call_box_status_group:amount')
> [2021.08.05 16:13:21] OpenAL Logging Level: (not set)
> [2021.08.05 16:13:21] Audio Playback Devices: OpenAL Soft
> [2021.08.05 16:13:21] Audio Playback Default Device: OpenAL Soft
> [2021.08.05 16:13:21] Audio Capture Devices: ES1371/ES1373 / Creative Labs CT2518 (Audio PCI 64V/128/5200 / Creative CT4810/CT5803/CT5806 [Sound Blaster PCI]) Analog Stereo;Monitor of ES1371/ES1373 / Creative Labs CT2518 (Audio PCI 64V/128/5200 / Creative CT4810/CT5803/CT5806 [Sound Blaster PCI]) Analog Stereo
> [2021.08.05 16:13:21] Audio Capture Default Device: ES1371/ES1373 / Creative Labs CT2518 (Audio PCI 64V/128/5200 / Creative CT4810/CT5803/CT5806 [Sound Blaster PCI]) Analog Stereo
> [2021.08.05 16:13:21] App Info: reading map...
> [2021.08.05 16:13:21] App Info: reading encrypted map...
> [2021.08.05 16:13:21] App Info: reading encrypted user settings...
> [2021.08.05 16:13:21] App Info: encrypted user settings read.
> [2021.08.05 16:13:21] App Info: reading encrypted mtp data...
> [2021.08.05 16:13:21] MTP Info: read keys, current: 2, to destroy: 0
> [2021.08.05 16:13:21] Map read time: 12
> [2021.08.05 16:13:21] TCP Error: network - Network unreachable
> [2021.08.05 16:13:21] HTTP Error: network error 99 - Network unreachable
> [2021.08.05 16:13:21] Using Qt tray icon.
> [2021.08.05 16:13:21] Tray Icon: Using Qt tray icon, available: [TRUE]
> [2021.08.05 16:13:21] Not using Unity Launcher count.
> [2021.08.05 16:13:21] TCP Error: network - Network unreachable
> [2021.08.05 16:13:21] HTTP Error: network error 99 - Network unreachable
![Screenshot from 2021-08-05 16-43-52](https://user-images.githubusercontent.com/88499227/128370695-f78ae950-31f3-4eb6-9f07-a7ca2f699899.png)
![Screenshot from 2021-08-05 16-44-19](https://user-images.githubusercontent.com/88499227/128370702-eab68c35-d9e6-4fc2-bd1e-2656127ff03e.png)
![Screenshot from 2021-08-05 16-48-56](https://user-images.githubusercontent.com/88499227/128370705-1c68644f-bd70-4cdd-8a02-3a4355b4ec4c.png)
![Screenshot from 2021-08-05 16-49-25](https://user-images.githubusercontent.com/88499227/128370712-6cba1579-b634-4192-b578-0f476ed39e7d.png)

**Comment by 23rd** [comment]
Migrating of your profile from a newer version to an older version of the Tdesktop will reset your profile login.

**Comment by snewsa** [comment]
Source is running Telegram 2.1.7
Target is running Telegram 2.9

I update Source when ever a new version is available.

So i try to migrate from an older version to a newer.

**Comment by 23rd** [comment]
> I made the target telegram bin to (same) version 2.1.7 and it worked like a charme. Thank u!

It's really strange. It means that the version from a year ago (2.1.7) failed to migrate the profile to the modern version (2.9). =(
I just hope it's not a big problem for you.

**Comment by john-preston** [comment]
🤔  2.1.6 auto-updates with authorization to the latest on Windows.
