### ISSUE TITLE
Telegram hangs and crashes down occassionally

### ISSUE THREAD

**Issue by Kingofki305** [telegramdesktop/tdesktop#16760]
### Steps to reproduce
1. Opened telegram.
2. double - triple click on unread group.
3. do it with many groups and channels to mark them read.
4. Telegram hangs, crashes and closes down itself
![image](https://user-images.githubusercontent.com/88315963/128324613-f1d7ef8e-34f4-466a-a40c-eec5cedddda0.png)

### Expected behaviour
Should not happen

### Actual behaviour
The above image stays as a window for 1-2 seconds and telegram is completely closed. We need to open telegram desktop application again put in local password too.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.9

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: tinted

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
plz, enable beta and on next crash send crash id.

**Comment by Kingofki305** [comment]
> plz, enable beta and on next crash send crash id.

how do i get crash id?

**Comment by Aokromes** [comment]
> > plz, enable beta and on next crash send crash id.
> 
> how do i get crash id?

you will get it when enabling beta and restart application on next crash.

**Comment by luisalvarado** [comment]
I am using Telegram 2.9 for Desktop in Ubuntu 20.04 and this started happening after it update to 2.8. So before 2.8 I never had this issue, then after updating to 2.8 the issue started. For example it will always happen if I click on ANY image someone uploads to a chat. The first time I click on an image in a chat it closes the telegram app. Then when it comes back, I can click on the image and see it correctly, I can also click on any following images in that conversation and it will work, but it is only the first time I click on an image that it fails. Very difficult to use telegram for work like this since I could be having a screen sharing or a call and then this happens.

Dmesg output gave me this for telegram the 4 times it crashed when I clicked on an image in the last 2 days:

```
[Aug 4 10:27] Telegram[1903]: segfault at 0 ip 0000000041fa0cc1 sp 00007ffc4499bf38 error 4 in .glXXXXXX (deleted)[41f9f000+2000]
[  +0.000005] Code: 48 8b c6 4c 8b da 48 8b d1 49 8b cb 48 be 38 4c 93 40 00 00 00 00 48 8b 36 48 8b b6 08 03 00 00 48 8b f9 48 c1 e7 04 48 03 f7 <8b> 3e 8b 6e 04 89 38 89 68 04 48 be 38 4c 93 40 00 00 00 00 48 8b
[Aug 4 14:48] Telegram[92118]: segfault at 0 ip 0000000041b7cdc1 sp 00007fff770e51e8 error 4 in .glXXXXXX (deleted)[41b7b000+2000]
[  +0.000006] Code: 48 8b c6 4c 8b da 48 8b d1 49 8b cb 48 be 38 3c 5c 40 00 00 00 00 48 8b 36 48 8b b6 08 03 00 00 48 8b f9 48 c1 e7 04 48 03 f7 <8b> 3e 8b 6e 04 89 38 89 68 04 48 be 38 3c 5c 40 00 00 00 00 48 8b
[Aug 5 08:25] Telegram[115129]: segfault at 0 ip 0000000040fdcdc1 sp 00007ffec17bacd8 error 4 in .glXXXXXX (deleted)[40fdb000+2000]
[  +0.000004] Code: 48 8b c6 4c 8b da 48 8b d1 49 8b cb 48 be 38 fc 7c 40 00 00 00 00 48 8b 36 48 8b b6 08 03 00 00 48 8b f9 48 c1 e7 04 48 03 f7 <8b> 3e 8b 6e 04 89 38 89 68 04 48 be 38 fc 7c 40 00 00 00 00 48 8b
[Aug 5 08:34] Telegram[152604]: segfault at 0 ip 0000000040f99d01 sp 00007fff26b93118 error 4 in .glXXXXXX (deleted)[40f98000+2000]
[  +0.000004] Code: 48 8b c6 4c 8b da 48 8b d1 49 8b cb 48 be 38 ac a3 41 00 00 00 00 48 8b 36 48 8b b6 08 03 00 00 48 8b f9 48 c1 e7 04 48 03 f7 <8b> 3e 8b 6e 04 89 38 89 68 04 48 be 38 ac a3 41 00 00 00 00 48 8b
```

**Comment by Aokromes** [comment]
> I am using Telegram 2.9 for Desktop in Ubuntu 20.04 and this started happening after it update to 2.8. So before 2.8 I never had this issue, then after updating to 2.8 the issue started. For example it will always happen if I click on ANY image someone uploads to a chat. The first time I click on an image in a chat it closes the telegram app. Then when it comes back, I can click on the image and see it correctly, I can also click on any following images in that conversation and it will work, but it is only the first time I click on an image that it fails. Very difficult to use telegram for work like this since I could be having a screen sharing or a call and then this happens.
> 
> Dmesg output gave me this for telegram the 4 times it crashed when I clicked on an image in the last 2 days:
> 
> ```
> [Aug 4 10:27] Telegram[1903]: segfault at 0 ip 0000000041fa0cc1 sp 00007ffc4499bf38 error 4 in .glXXXXXX (deleted)[41f9f000+2000]
> [  +0.000005] Code: 48 8b c6 4c 8b da 48 8b d1 49 8b cb 48 be 38 4c 93 40 00 00 00 00 48 8b 36 48 8b b6 08 03 00 00 48 8b f9 48 c1 e7 04 48 03 f7 <8b> 3e 8b 6e 04 89 38 89 68 04 48 be 38 4c 93 40 00 00 00 00 48 8b
> [Aug 4 14:48] Telegram[92118]: segfault at 0 ip 0000000041b7cdc1 sp 00007fff770e51e8 error 4 in .glXXXXXX (deleted)[41b7b000+2000]
> [  +0.000006] Code: 48 8b c6 4c 8b da 48 8b d1 49 8b cb 48 be 38 3c 5c 40 00 00 00 00 48 8b 36 48 8b b6 08 03 00 00 48 8b f9 48 c1 e7 04 48 03 f7 <8b> 3e 8b 6e 04 89 38 89 68 04 48 be 38 3c 5c 40 00 00 00 00 48 8b
> [Aug 5 08:25] Telegram[115129]: segfault at 0 ip 0000000040fdcdc1 sp 00007ffec17bacd8 error 4 in .glXXXXXX (deleted)[40fdb000+2000]
> [  +0.000004] Code: 48 8b c6 4c 8b da 48 8b d1 49 8b cb 48 be 38 fc 7c 40 00 00 00 00 48 8b 36 48 8b b6 08 03 00 00 48 8b f9 48 c1 e7 04 48 03 f7 <8b> 3e 8b 6e 04 89 38 89 68 04 48 be 38 fc 7c 40 00 00 00 00 48 8b
> [Aug 5 08:34] Telegram[152604]: segfault at 0 ip 0000000040f99d01 sp 00007fff26b93118 error 4 in .glXXXXXX (deleted)[40f98000+2000]
> [  +0.000004] Code: 48 8b c6 4c 8b da 48 8b d1 49 8b cb 48 be 38 ac a3 41 00 00 00 00 48 8b 36 48 8b b6 08 03 00 00 48 8b f9 48 c1 e7 04 48 03 f7 <8b> 3e 8b 6e 04 89 38 89 68 04 48 be 38 ac a3 41 00 00 00 00 48 8b
> ```

plz, try to use gdb to get a crashlog if you don't have a crash id.

**Comment by luisalvarado** [comment]
> > I am using Telegram 2.9 for Desktop in Ubuntu 20.04 and this started happening after it update to 2.8. So before 2.8 I never had this issue, then after updating to 2.8 the issue started. For example it will always happen if I click on ANY image someone uploads to a chat. The first time I click on an image in a chat it closes the telegram app. Then when it comes back, I can click on the image and see it correctly, I can also click on any following images in that conversation and it will work, but it is only the first time I click on an image that it fails. Very difficult to use telegram for work like this since I could be having a screen sharing or a call and then this happens.
> > Dmesg output gave me this for telegram the 4 times it crashed when I clicked on an image in the last 2 days:
> > ```
> > [Aug 4 10:27] Telegram[1903]: segfault at 0 ip 0000000041fa0cc1 sp 00007ffc4499bf38 error 4 in .glXXXXXX (deleted)[41f9f000+2000]
> > [  +0.000005] Code: 48 8b c6 4c 8b da 48 8b d1 49 8b cb 48 be 38 4c 93 40 00 00 00 00 48 8b 36 48 8b b6 08 03 00 00 48 8b f9 48 c1 e7 04 48 03 f7 <8b> 3e 8b 6e 04 89 38 89 68 04 48 be 38 4c 93 40 00 00 00 00 48 8b
> > [Aug 4 14:48] Telegram[92118]: segfault at 0 ip 0000000041b7cdc1 sp 00007fff770e51e8 error 4 in .glXXXXXX (deleted)[41b7b000+2000]
> > [  +0.000006] Code: 48 8b c6 4c 8b da 48 8b d1 49 8b cb 48 be 38 3c 5c 40 00 00 00 00 48 8b 36 48 8b b6 08 03 00 00 48 8b f9 48 c1 e7 04 48 03 f7 <8b> 3e 8b 6e 04 89 38 89 68 04 48 be 38 3c 5c 40 00 00 00 00 48 8b
> > [Aug 5 08:25] Telegram[115129]: segfault at 0 ip 0000000040fdcdc1 sp 00007ffec17bacd8 error 4 in .glXXXXXX (deleted)[40fdb000+2000]
> > [  +0.000004] Code: 48 8b c6 4c 8b da 48 8b d1 49 8b cb 48 be 38 fc 7c 40 00 00 00 00 48 8b 36 48 8b b6 08 03 00 00 48 8b f9 48 c1 e7 04 48 03 f7 <8b> 3e 8b 6e 04 89 38 89 68 04 48 be 38 fc 7c 40 00 00 00 00 48 8b
> > [Aug 5 08:34] Telegram[152604]: segfault at 0 ip 0000000040f99d01 sp 00007fff26b93118 error 4 in .glXXXXXX (deleted)[40f98000+2000]
> > [  +0.000004] Code: 48 8b c6 4c 8b da 48 8b d1 49 8b cb 48 be 38 ac a3 41 00 00 00 00 48 8b 36 48 8b b6 08 03 00 00 48 8b f9 48 c1 e7 04 48 03 f7 <8b> 3e 8b 6e 04 89 38 89 68 04 48 be 38 ac a3 41 00 00 00 00 48 8b
> > ```
> 
> plz, try to use gdb to get a crashlog if you don't have a crash id.

Thank you buddy, I did run it with gdb now and clicked on god knows how many images. I even went into old conversations (more likely more than 50 conversations and more than 300 images) and never once did it crashed. The only difference I can see here is that I ran telegram via the terminal (with gdb) versus the common way I was using which was start when the computer or the ubuntu session starts. Don't know if that helps.

**Comment by Aokromes** [comment]
maybe you can attach gdb after start.

**Comment by Kingofki305** [comment]
> plz, enable beta and on next crash send crash id.

i have enabled beta and have not suffered any hangs, crashes or glitches now but still sometimes while scheduling the message the scheduled messages area is blank and once we restart the application after some hours, it appears there.

rest everything is working fine

**Comment by Kingofki305** [comment]
![image](https://user-images.githubusercontent.com/88315963/128609370-b227e45e-ebb8-43de-a3dc-5bd14cad6620.png)

![report 1](https://user-images.githubusercontent.com/88315963/128609376-d7e113dc-e715-457e-b506-cc8500fa06bb.png)

![report 2](https://user-images.githubusercontent.com/88315963/128609383-a0863029-40a3-473e-ab6f-1e3d56c214cf.png)

**Comment by Timstar124** [comment]
Telegram desktop (ver 2.9) randomly crashing – Windows version 20H2
Happening on my desktop and laptop

• App randomly shutting down when I click on certain groups
• Scheduled messages vanished from one group
• Unable to edit/reschedule/delete scheduled messages

Started happening yesterday (7th August 2021)
Telegram is up to date and so is Windows

**Comment by xm4dn355x** [comment]
Same issue
When in my own channel https://t.me/greta_tuborg posting new message and I see that in my channel 0 new messages, but in Greta_Tuborg_chat (for comments) I see new message. I want to open my channel to see this new message, but telegram Desktop is crashing every time. But after reload of client I see "Last time Telegram Desktop was not closed propperly", "Try again" button is not working, I click "skip" and after client are loaded I see that in my channel have 1 new message.

Also "Schedulled Messages" now is broken. I can't edit any message or reschedule, or something else. Button "save" isn't working.

I need help! Please! I think that something like message body escaping is not working propperly in telegram desktop. Or maybe problem in memory management((( I'm not C++ coder, and I'm hard to understand what the problem to help Telegram team...

That was started happening after last update.

Sorry for my English.

```
ApiId: 2040
Assertion: "i != end(_messages)" history.cpp:448
Binary: Telegram.exe
Launched: 09.08.2021 12:21:16
Platform: Windows64Bit
UserTag: 14b13f24c73328a0
Version: 2009000
Memory-usage: 737 MB (peak), 390 MB (current)
Pagefile-usage: 720 MB (peak), 505 MB (current)

Caught signal 11 (SIGSEGV) in thread 35836

Backtrace omitted.

Google Breakpad caught a crash, minidump written in thread 10892
Minidump: ad9f2aba-88e9-4b0d-b8b4-20f8dc69d0c7

Backtrace omitted.
```

**Comment by john-preston** [comment]
This should be fixed in 2.9.2.

**Comment by xm4dn355x** [comment]
Epic Win! Great job guys!

> This should be fixed in 2.9.2.

**Comment by luisalvarado** [comment]
Wow, am too late to the party. Was gonna paste this here from gdb:

`[New Thread 0x7fff80cd9700 (LWP 82816)]
[New Thread 0x7fff804d8700 (LWP 82817)]
[New Thread 0x7fff7fcd7700 (LWP 82959)]
[New Thread 0x7fff7f4d6700 (LWP 82960)]
[New Thread 0x7fff7ecd5700 (LWP 82961)]
[Thread 0x7fff7ecd5700 (LWP 82961) exited]
[Thread 0x7fff7f4d6700 (LWP 82960) exited]
[Thread 0x7fff7fcd7700 (LWP 82959) exited]
Corrupt JPEG data: premature end of data segment
[Thread 0x7fff864e4700 (LWP 82805) exited]
[Thread 0x7fff844e0700 (LWP 82809) exited]
[Thread 0x7fff83cdf700 (LWP 82810) exited]
[Thread 0x7fff834de700 (LWP 82811) exited]
[Thread 0x7fff82cdd700 (LWP 82812) exited]
[Thread 0x7fff824dc700 (LWP 82813) exited]
[Thread 0x7fff81cdb700 (LWP 82814) exited]
[Thread 0x7fff814da700 (LWP 82815) exited]
[Thread 0x7fff80cd9700 (LWP 82816) exited]
[Thread 0x7fff804d8700 (LWP 82817) exited]
[Thread 0x7fff8b4ee700 (LWP 82795) exited]
[Thread 0x7fffeabff700 (LWP 82775) exited]
[Thread 0x7fff8a4ec700 (LWP 82796) exited]
[Thread 0x7fffeb9ff700 (LWP 82797) exited]
[Thread 0x7fff89ceb700 (LWP 82798) exited]
[Thread 0x7fff894ea700 (LWP 82799) exited]
[Thread 0x7fffe98ff700 (LWP 82776) exited]
[Thread 0x7fff88ce9700 (LWP 82800) exited]
[Thread 0x7fffbacef700 (LWP 82777) exited]
[Thread 0x7fff884e8700 (LWP 82801) exited]
[Thread 0x7fffad27c700 (LWP 82778) exited]
[Thread 0x7fff87ce7700 (LWP 82802) exited]
[Thread 0x7fff874e6700 (LWP 82803) exited]
[Thread 0x7fffa6477700 (LWP 82779) exited]
[Thread 0x7fff86ce5700 (LWP 82804) exited]
[Thread 0x7fff9d637700 (LWP 82780) exited]
[Thread 0x7fff91077700 (LWP 82781) exited]
[Thread 0x7fff90876700 (LWP 82782) exited]
[Thread 0x7fff8c4f0700 (LWP 82783) exited]
[Thread 0x7fff8bcef700 (LWP 82784) exited]
[New Thread 0x7fff8bcef700 (LWP 83056)]
[New Thread 0x7fff8c4f0700 (LWP 83057)]
[Thread 0x7fff8c4f0700 (LWP 83057) exited]
[Thread 0x7fff8bcef700 (LWP 83056) exited]
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
[Thread 0x7fffec7ff700 (LWP 82727) exited]
[Thread 0x7fffed47f700 (LWP 82729) exited]
[Thread 0x7fffee8ff700 (LWP 82726) exited]
[Thread 0x7fff85ce3700 (LWP 82806) exited]
[Thread 0x7fff8aced700 (LWP 82788) exited]
[Thread 0x7fffb4f6a700 (LWP 82728) exited]
[Thread 0x7fff84ce1700 (LWP 82808) exited]
[New Thread 0x7fff84ce1700 (LWP 83196)]
[New Thread 0x7fffb4f6a700 (LWP 83197)]
[New Thread 0x7fff8aced700 (LWP 83198)]
[New Thread 0x7fff85ce3700 (LWP 83199)]
[New Thread 0x7fffee8ff700 (LWP 83200)]
[New Thread 0x7fffed47f700 (LWP 83201)]
[New Thread 0x7fffec7ff700 (LWP 83202)]
[New Thread 0x7fffeabff700 (LWP 83204)]
[New Thread 0x7fffe98ff700 (LWP 83205)]
[New Thread 0x7fffbacef700 (LWP 83206)]
[New Thread 0x7fffad27c700 (LWP 83207)]
[New Thread 0x7fffa6477700 (LWP 83208)]
[New Thread 0x7fff91077700 (LWP 83209)]
[New Thread 0x7fff90876700 (LWP 83210)]
[New Thread 0x7fff8c4f0700 (LWP 83211)]
[New Thread 0x7fff8bcef700 (LWP 83212)]
[New Thread 0x7fff8b4ee700 (LWP 83213)]
[New Thread 0x7fff890f5700 (LWP 83214)]
[New Thread 0x7fff888f4700 (LWP 83215)]
[Thread 0x7fff890f5700 (LWP 83214) exited]
[New Thread 0x7fff890f5700 (LWP 83216)]
[Thread 0x7fff890f5700 (LWP 83216) exited]
[Thread 0x7fff888f4700 (LWP 83215) exited]
[Detaching after fork from child process 83219]
[New Thread 0x7fff888f4700 (LWP 83221)]
[New Thread 0x7fff890f5700 (LWP 83222)]
Opening in existing browser session.
[New Thread 0x7fff880f3700 (LWP 83300)]
[New Thread 0x7fff878f2700 (LWP 83301)]
[Thread 0x7fff878f2700 (LWP 83301) exited]
[Thread 0x7fff888f4700 (LWP 83221) exited]
[Thread 0x7fff880f3700 (LWP 83300) exited]
[Thread 0x7fff890f5700 (LWP 83222) exited]
[Thread 0x7fff854e2700 (LWP 82807) exited]
[Thread 0x7fffee8ff700 (LWP 83200) exited]
[Thread 0x7fff85ce3700 (LWP 83199) exited]
[Thread 0x7fff84ce1700 (LWP 83196) exited]
[Thread 0x7fffec7ff700 (LWP 83202) exited]
[Thread 0x7fffed47f700 (LWP 83201) exited]
[Thread 0x7fffb4f6a700 (LWP 83197) exited]
[Thread 0x7fff8aced700 (LWP 83198) exited]
[New Thread 0x7fff8aced700 (LWP 83369)]
[New Thread 0x7fffb4f6a700 (LWP 83370)]
[New Thread 0x7fffed47f700 (LWP 83371)]
[Thread 0x7fffed47f700 (LWP 83371) exited]
[Thread 0x7fffb4f6a700 (LWP 83370) exited]
[Thread 0x7fff8aced700 (LWP 83369) exited]
[New Thread 0x7fffb4f6a700 (LWP 83390)]
[New Thread 0x7fff8aced700 (LWP 83391)]
[New Thread 0x7fffed47f700 (LWP 83392)]
[New Thread 0x7fffec7ff700 (LWP 83393)]
[New Thread 0x7fffee8ff700 (LWP 83394)]
[New Thread 0x7fff890f5700 (LWP 83395)]
[New Thread 0x7fff888f4700 (LWP 83396)]
[New Thread 0x7fff880f3700 (LWP 83397)]
[Thread 0x7fffeabff700 (LWP 83204) exited]
[Thread 0x7fffe98ff700 (LWP 83205) exited]
[Thread 0x7fffbacef700 (LWP 83206) exited]
[Thread 0x7fffad27c700 (LWP 83207) exited]
[Thread 0x7fffa6477700 (LWP 83208) exited]
[Thread 0x7fff91077700 (LWP 83209) exited]
[Thread 0x7fff90876700 (LWP 83210) exited]
[Thread 0x7fff8c4f0700 (LWP 83211) exited]
[Thread 0x7fff8bcef700 (LWP 83212) exited]
[Thread 0x7fff8b4ee700 (LWP 83213) exited]
[New Thread 0x7fff8b4ee700 (LWP 83496)]
[New Thread 0x7fff8bcef700 (LWP 83497)]
[New Thread 0x7fff8c4f0700 (LWP 83498)]
[New Thread 0x7fff90876700 (LWP 83499)]
[Thread 0x7fff90876700 (LWP 83499) exited]
[Thread 0x7fff8bcef700 (LWP 83497) exited]
[Thread 0x7fff8c4f0700 (LWP 83498) exited]
[New Thread 0x7fff8c4f0700 (LWP 83500)]
[New Thread 0x7fff8bcef700 (LWP 83501)]
[New Thread 0x7fff90876700 (LWP 83502)]
[New Thread 0x7fffeabff700 (LWP 83503)]
[New Thread 0x7fffe98ff700 (LWP 83504)]
[New Thread 0x7fffbacef700 (LWP 83505)]
[New Thread 0x7fffad27c700 (LWP 83506)]
[New Thread 0x7fffa6477700 (LWP 83507)]
[New Thread 0x7fff91077700 (LWP 83508)]
QPainter::begin(): QOpenGLPaintDevice's context needs to be current
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "Telegram" received signal SIGSEGV, Segmentation fault.
0x0000000003ca6800 in ?? ()
`

**Comment by luisalvarado** [comment]
At last got one good (Telegram Desktop 2.9.2):

[Thread 0x7fffc2614700 (LWP 33881) exited]
[New Thread 0x7fffc1e13700 (LWP 34039)]
[New Thread 0x7fffc2614700 (LWP 34040)]
[New Thread 0x7fffc1612700 (LWP 34041)]
[New Thread 0x7fffc0e11700 (LWP 34042)]
[Thread 0x7fffc0e11700 (LWP 34042) exited]
[Thread 0x7fffc1612700 (LWP 34041) exited]
[Thread 0x7fffc2614700 (LWP 34040) exited]
[ogg @ 0x7ffff2044000] 727 bytes of comment header remain
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
[New Thread 0x7fffc1612700 (LWP 34043)]
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[New Thread 0x7fffc2614700 (LWP 34044)]
[Thread 0x7fffc1e13700 (LWP 34039) exited]
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "Telegram" received signal SIGSEGV, Segmentation fault.
0x0000000003ca6800 in ?? ()
(gdb)

**Comment by luisalvarado** [comment]
Got another issue on 3.1.0 hopefully tomorrow I can send a debug log.
