### ISSUE TITLE
Add a section for shared GIFs in the "Shared media" section

### ISSUE THREAD

**Issue by wodim** [telegramdesktop/tdesktop#1677]
Shared GIFs are not shown in any of these categories:

![2016-02-23_13-14-55](https://cloud.githubusercontent.com/assets/1001553/13251285/873482da-da2f-11e5-8ea8-e5151a831fe6.png)

It would be nice to have a category for them.

**Comment by emadgh** [comment]
Yes, that would be really great, 
But for now you can search "GIF" and all related messages would be listed.

**Comment by Neurotoxin001** [comment]
Why there is still no this feature?

**Comment by Neurotoxin001** [comment]
Pls...

**Comment by Aokromes** [comment]
stop adding noise to bug tracker, bumping issues doesn't puts them into higher position.

**Comment by wodim** [comment]
This problem still exists in the current version of Telegram.

**Comment by Neurotoxin001** [comment]
Needed

**Comment by Aokromes** [comment]
already implemented on 3.0
