### ISSUE TITLE
DirectX 12 crashing in Telegram Desktop from Microsoft Store

### ISSUE THREAD

**Issue by AyraHikari** [telegramdesktop/tdesktop#16770]
### Steps to reproduce
1. Go to advanced settings
2. In ANGLE graphic backend, select from `auto` to `d3d11on12`
3. Restart, it wont run again

### Expected behaviour
It probably work like dx11

### Actual behaviour
It crashed, no log provided
![image](https://user-images.githubusercontent.com/36266025/128610947-939f32dc-a9dc-4343-a097-d4ca44812867.png)
![image](https://user-images.githubusercontent.com/36266025/128610976-6ae898f0-a07c-401f-9c9b-b20aca8e00f1.png)

### Configuration
**Operating system:** Windows 11 Pro 21H2 build 1000.22000.120.0

**Version of Telegram Desktop:** 2.9.1 x64 
**Used theme**: Night theme

<details><summary><b>Logs</b>:</summary>
Did not know the log path since i'm installed it with microsoft store
</details>

<details><summary><b>Additional information</b>:</summary>
![image](https://user-images.githubusercontent.com/36266025/128611018-da2ae7a3-a9a3-404d-b37e-17d6171fe23c.png)
![image](https://user-images.githubusercontent.com/36266025/128611019-22939488-f460-4bee-85f5-b6300e590f06.png)
</details>

**Comment by Aokromes** [comment]
this bug is still valid on 3.3?

**Comment by AyraHikari** [comment]
The problem was gone in 3.3 x64, thank you
