### ISSUE TITLE
[Feature Request] do not display counts of archived messags on telegram icon

### ISSUE THREAD

**Issue by wsdjeg** [telegramdesktop/tdesktop#16774]
### Is your feature request related to a problem?

no, it should be a new feature request

### Describe the solution you'd like

I want to hide the counts of messages from archived group, 

![image](https://user-images.githubusercontent.com/13142418/128620000-568c3557-8409-4f62-95d2-1f2b4abae482.png)

**Comment by ilya-fedin** [comment]
#6721

**Comment by wsdjeg** [comment]
This not same feature request, I just want to ignore archived group message, insteal of all groups.
--------------
wsdjeg

**Comment by ilya-fedin** [comment]
You can disable muted chats counting
