### ISSUE TITLE
[Feature Request] Hide Archived chats (not at the top)

### ISSUE THREAD

**Issue by superbonaci** [telegramdesktop/tdesktop#16773]
Telegram desktop shows Archived chats at the top, which you risk hitting them by accident. Make them go to the bottom or hide them like on Android client.

**Comment by superbonaci** [comment]
I can be collapsed https://github.com/telegramdesktop/tdesktop/issues/5989

**Comment by john-preston** [comment]
Also I collapsed is still too large it can go straight to the main menu.

**Comment by superbonaci** [comment]
@john-preston what do you mean?

**Comment by john-preston** [comment]
@superbonaci If you right click the archive row you can see a "Move to main menu" context menu item. If you press it then the archive row will disappear completely from the chats list and archive icon will appear in the left menu.
