### ISSUE TITLE
[Feature Request] Typing with styles applied

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#16778]
### Is your feature request related to a problem?
Can not type in _italic_ or **bold**. Can only change the format of the text after it was typed.

### Describe the solution you'd like
I want to be able to enable and disable styles and to type with those styles applied right away.

### Describe alternatives you've considered
For this purpose I can not think of an alternative.

### Additional context
If a style applied to a letter, typing after that letter continues applying that style to new letters/symbols. But after a space the styles get cancelled. I want to be able to enable/disable styles at will with hotkeys.

**Comment by BryceSteuer** [comment]
I agree, this would be a great feature and one most useful.

**Comment by MasterGroosha** [comment]
Can't you choose formatting while typing your message in text box? 
![изображение](https://user-images.githubusercontent.com/2780044/131963610-d96920e7-3ab5-4aa3-943a-2b9eed32d308.png)

**Comment by BryceSteuer** [comment]
Indeed. I must have not noticed, but thank you for pointing it out.

**Comment by BryceSteuer** [comment]
Just highlight the text you want to format after typing it, right click and select "Formatting". Then choose your preferred format option, and the highlighted text will conform to it.

**Comment by RememberTheAir** [comment]
unstale
