### ISSUE TITLE
[Feature Request] Secret Chats on Desktop Client

### ISSUE THREAD

**Issue by j-nicolas** [telegramdesktop/tdesktop#16772]
OK - I know, this is a double request of https://github.com/telegramdesktop/tdesktop/issues/871
which was posted in 2015 (!).

**BUT** the objection mentioned there (https://github.com/telegramdesktop/tdesktop/issues/118#issuecomment-72011592 )
is no longer valid, since a LOT of peope use the messenger on a PC/Laptop not only for special purposes but for routine.
Also, many users have restricted their use of the smartphone since "Corona" as the easiest way to prevent tracking.

So the desktop client should no longer be seen as an alternative to the smartphone, 
but as a full-fledged standalone client.

**Comment by Aokromes** [comment]
it's still duplicate.

**Comment by john-preston** [comment]
Unfortunately it is a much more "addition to the smartphone app", than before. Now you even can't log in to or sign up in the desktop app without having the smartphone app active at the same time.
