### ISSUE TITLE
Application Crash/Stack Smash

### ISSUE THREAD

**Issue by Krutonium** [telegramdesktop/tdesktop#16782]
### Steps to reproduce
1. Open Telegram
2. Wait
3. 

### Expected behaviour
Telegram should not crash

### Actual behaviour
Telegram Crashes

### Configuration
**Operating system:** 
Arch Linux

**Version of Telegram Desktop:** 
2.9

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Official Repo

**Used theme**:
Adwatia? And Dark Mode in the client.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

```
[krutonium@GamingPC ~]$ telegram-desktop 

(telegram-desktop:7309): Telegram-WARNING **: 04:25:25.855: Application was built without embedded fonts, this may lead to font issues.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QFont::fromString: Invalid description '(empty)'
QFont::fromString: Invalid description '(empty)'
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
*** stack smashing detected ***: terminated
Aborted (core dumped)
```

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by denisgolius** [comment]
> plz try downloading official version from https://desktop.telegram.org

I got the same issue from official desktop. It crashed while I press on users nickame like @username and crashed two times while I pressed quit.

**Comment by ilya-fedin** [comment]
@denisgolius the fact you got a crash doesn't mean you got the same crash

**Comment by ilya-fedin** [comment]
> plz try downloading official version from https://desktop.telegram.org

Why are you asking them, you know, there's an already opened duplicate.

**Comment by Krutonium** [comment]
Could you be so kind as to link the duplicate? I looked but didn't see it.

**Comment by ZerdoX-x** [comment]
> Could you be so kind as to link the duplicate? I looked but didn't see it.

Maybe #16673
