### ISSUE TITLE
Graphical Error windows 7

### ISSUE THREAD

**Issue by ITL71** [telegramdesktop/tdesktop#16785]
this is how the upper side of the software appears on windows 7 since the last update of version 2.9 x64
it doesn't happen with other softwares i use only telegram.
it's kind of blinking, sometimes it appears normal and then again like that

![](https://i.imgur.com/spjgvvD.png)

**Comment by Aokromes** [comment]
duplicate, search on settings advanced for use windows system frame as workaround.
