### ISSUE TITLE
GIFs Auto play option

### ISSUE THREAD

**Issue by UnAfraid** [telegramdesktop/tdesktop#1678]
Hello,

Since the @gif bot was introduced lots of people started using (rather abusing) it way too much, and that really annoys me, can there be added an option to disable the auto play?

Thanks!

**Comment by auchri** [comment]
Settings -> Chat options -> download options -> disable "Autoplay"

**Comment by UnAfraid** [comment]
Awesome, didn't knew about this thanks!

**Comment by Nik--** [comment]
QQ, now we cant annoy you :(

**Comment by Sdwz** [comment]
What a noob

**Comment by user890104** [comment]
indeed, RTFM next time @UnAfraid
