### ISSUE TITLE
More Secure Authentication with Yubikey

### ISSUE THREAD

**Issue by danrossi** [telegramdesktop/tdesktop#16792]
The whole identity process requiring phones and mobile numbers including access to parts of the phone is not secure. An OTP code to SMS is out of date and not secure. I never get the OTP codes at all, tried many times. 

Is there a way to not require any phone or phone app and NOT use an identifiable mobile number as a "login" let alone QR codes that can have malware. It would be good to have WebAuthn type authentication and use my Yubikey to login. No mobile number or phone .  

Malware is able to tamper with Whatsapp and Signal. No phone requirement is better. 

This obsolete authentication method has prevented me using this system so far. 

Possible ?

**Comment by Aokromes** [comment]
no-phone requirements are very unlikely to be approved, anyway platform wide requests belongs to bugs.telegram.org

**Comment by danrossi** [comment]
Ok thanks. I can't report there because it requires a mobile number as a login and I mentioned the problems with phones. I don't use phones for such things for a good reason. What is this ?

**Comment by RememberTheAir** [comment]
@danrossi you can use the phone number you registered your Telegram account with. It's just a way to link your telegram account, no SMS/call is involved in the process and the login is handled from inside any of your telegram clients
