### ISSUE TITLE
In audio chat sound is wobbling, an amplitude modulation is altering the sound

### ISSUE THREAD

**Issue by brailateo** [telegramdesktop/tdesktop#16798]
### Steps to reproduce
1. open an audio chat
2. let the other one speak
3. hear his voice with a 3-5 Hz vibrato

### Expected behaviour
The voice should be clean, unmodulated

### Actual behaviour
The sound is altered in amplitude with a 3-5 Hz vibrato envelope

### Configuration
**Operating system:** Ubuntu Linux 20.04 64 bit, AMD processor

**Version of Telegram Desktop:** 2.9

**Installation source (Linux Only)** - the official website:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
please update to the latest version 2.9.2 before reporting

**Comment by brailateo** [comment]
Installed 2.9.2 version, I confirm, the problem is solved, the sound is OK now! Thanks!
