### ISSUE TITLE
In voice/video call interlocutor's voice jams

### ISSUE THREAD

**Issue by dadyarri** [telegramdesktop/tdesktop#16805]
### Steps to reproduce
1. Call to anyone

### Expected behaviour
Tell us what should happen

Normal clean voice

### Actual behaviour
Tell us what happens instead

Interlocutor's voice will be with some spaces (not internet or headphones problem in 2.8.11 all works normally)

### Configuration
**Operating system:** Manjaro Linux

**Version of Telegram Desktop:** 2.9.0

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: distribution package

**Used theme**: not relevant

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by c0re100** [comment]
Update to v2.9.2 before reporting
