### ISSUE TITLE
[macOS] Window focus will activate the telegram window when closed.

### ISSUE THREAD

**Issue by VergeDX** [telegramdesktop/tdesktop#16807]
### Steps to reproduce
1. Open Telegram & another window (like Terminal.app), minimized the others.
2. Switch window focus to Telegram - Terminal - Telegram.
3. Command + W to close Telegram, click Terminal.app, Command + Q to quit terminal.

### Expected behavior
Telegram window reopened.

### Actual behavior
Telegram windows should not be reopened when windows focus is switched to.
When activating (window focus on) an app without windows, do not open the default window.

### Configuration
**Operating system:**
macOS Catalina, 10.15.7 (19H1323).

**Version of Telegram Desktop:**
version 2.9.3

**Used theme**:
Classic | Tinted

**Comment by VergeDX** [comment]
I think that's ok to distinguish them.

Let me summarize most of the macOS app's behavior (like Terminal.app etc):
Launch app, the app shows the window and runs in the background.
Cmd + W closes the running window, but does not exit the app. it still running in the background.
Cmd + Tab will not open the app's window again but click the icon can.

I think That was very difficult to understand...
I suggest you try macOS and watch the behavior, and I will try to finding issues too : )

**Comment by john-preston** [comment]
I'm on macOS for the past seven years.. But I still think that when you switch to Telegram Desktop by Cmd+Tab the window should be brought back.

Maybe it's ok for multi-document / multi-window apps to allow you to hide all their windows and then switch by Cmd+Tab and not see a single window and start your work from scratch using Cmd+N or smth. But Telegram Desktop is really a single-window app, it is a common way to hide the window using Cmd+W, but you can't do anything with the app in that state from the keyboard. So you're forced to go to your mouse / trackpad when you just Cmd+Tab-ed back to Telegram Desktop.

**Comment by VergeDX** [comment]
Oh okay, I accept this behavior.
