### ISSUE TITLE
Cannot PIN more than 5 chats

### ISSUE THREAD

**Issue by xjj1** [telegramdesktop/tdesktop#16809]
### Steps to reproduce
1. Try to pin more than 5 chats
2. Fail

### Expected behaviour
Pin any number of chats

### Actual behaviour
Can pin only 5 chats

### Configuration
Windows 10
Android

**Comment by xjj1** [comment]
Hello,
I do not understand your reluctance to fix this(obviously never).
Are you not users of your own product? Is this good for you?
Thanks,
xjj1

**Comment by 23rd** [comment]
You can upvote the same request here: https://bugs.telegram.org/c/64.
