### ISSUE TITLE
Undefined symbol: qt_assert_x(char const*, char const*, char const*, int)

### ISSUE THREAD

**Issue by yesterdaycode** [telegramdesktop/tdesktop#16817]
I can't build the Telegram Desktop on MacOS Big Sur 11.5.1 (arm architecture - M1)

My actions:
1.  Download repository
2.  Clone source code and prepare libraries
3.  Building the project

I get .xcodeproj project and trying build this in XCODE. 83 errors of Undefined symbol

<img width="259" alt="Screenshot of errors" src="https://user-images.githubusercontent.com/88986681/129491120-35cc195d-33cc-416d-afa3-a78019a650b5.png">

**Comment by ilya-fedin** [comment]
AFAIK Qt 5 doesn't support M1, so you can't do that

**Comment by yesterdaycode** [comment]
Thanks for answer!
