### ISSUE TITLE
[Feature Request]: support languages or dictionaries for spelling check 

### ISSUE THREAD

**Issue by Nehemoth** [telegramdesktop/tdesktop#16812]
I would like to have a way to use the spelling check in a different languages that the UI language. Even better I would like to have an option to select between multiple languages when spelling check.

Thank you

**Comment by ilya-fedin** [comment]
That's already possible if your OS doesn't provide system spellchecker.
![изображение](https://user-images.githubusercontent.com/17829319/129391575-e2142ab7-1e9f-4a51-a70b-4d46af9f8edd.png)

If your OS provides system spellchecker, you should refer to manuals for your OS on how to configure that (or ask your OS vendor to add such a feature if it doesn't exist).

**Comment by Nehemoth** [comment]
It looks there's some kind of miscommunication here.
I'm on Windows 10 21H1 [Build 19043.1165]

Right now I just get the UI language results. In the photo below English.
What I would like it's the option to select another language, for example Spanish without having to change my UI language.

![image](https://user-images.githubusercontent.com/8248452/129392617-7a89147c-5d49-48fd-847e-44d8027e74db.png)

**Comment by ilya-fedin** [comment]
No miscommunication, tdesktop uses system spellchecker when available, it's configured via your system settings and tdesktop can't influence on it.

**Comment by Nehemoth** [comment]
> 
> 
> No miscommunication, tdesktop uses system spellchecker when available, it's configured via your system settings and tdesktop can't influence on it.

I'm trying to understand here.

> "That's already possible if your OS doesn't provide system spellchecker."

What's that possibility if my OS doesn't support spelling check?
tdesktop don't offer me another language for the spelling check which its what I would like.

**Comment by Nehemoth** [comment]
This is in Firefox [as an example]
I get spelling check results based on my desired language.

![image](https://user-images.githubusercontent.com/8248452/129393645-603e1ac5-0f16-45a8-9aaf-6e779bb41b48.png)

**Comment by ilya-fedin** [comment]
> What's that possibility if my OS doesn't support spelling check?

Windows 7 doesn't have one, for instance.

> tdesktop don't offer me another language for the spelling check which its what I would like.

You still should be able to configure spellcheck via your system setitngs.

**Comment by ilya-fedin** [comment]
> This is in Firefox [as an example]

Firefox doesn't use system spellcheck API IIRC, it uses Hunspell instead. tdesktop uses system API.

**Comment by Nehemoth** [comment]
OK. Now I understood. For future reference if someone like me arrive here looking for the same. In windows 10 and above, you have the option for spelling check but by default will only give you options in the UI language, that it if you Windows version it's in English you will receive spelling suggestion in English.

So you must add a new language. For this open windows settings > go to time & language > language > add language in search for your desire language
Please keep in mind that not all languages have all the features.
You want a language with handwriting support.
Then go to Settings > Devices > Typing and enable Multilingual text suggestions
Then in Suggestions & autocorrections be sure to select your languages

Maybe you will need to restart multiple times, in the laptop  that I was testing the spelling function was not available in tdesktop the first time that I restarted.

Sadly tough in this Laptop I can't download new languages and my personal laptop has windows 11 which doesn't have the Suggestions & autocorrections option

Good luck
