### ISSUE TITLE
[Feature Request] Block animated GIFs or pictures altogether

### ISSUE THREAD

**Issue by jorisw** [telegramdesktop/tdesktop#16816]
### Is your feature request related to a problem?
Often when I visit groups in Telegram, the groups are flooded with pointless animated GIFs that are intended to be funny but add no value.

### Describe the solution you'd like
I would like to be able to disable the preview of media in Telegram, especially animated GIFs.

### Describe alternatives you've considered
I have tried to block users that post animated GIFs, but their messages still make it to the group. I have tried to 'collapse' the previews of posted media, but there's no such feature either.

**Comment by clausmichele** [comment]
I ave opened a similar feature request lone long time ago https://github.com/telegramdesktop/tdesktop/issues/6999

**Comment by jorisw** [comment]
Closed because...?

**Comment by Aokromes** [comment]
duplicate.

**Comment by jorisw** [comment]
Disagree. #6999 suggests a text mode. 

I suggested an option to disable media previews.
