### ISSUE TITLE
Image size becomes 5x-8x while uploading from clipboard

### ISSUE THREAD

**Issue by preyasprathap** [telegramdesktop/tdesktop#16815]
### Steps to reproduce
1. go to this URL - https://images.unsplash.com/photo-1629012442785-7b61081374f5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80
2. right click > copy image
3. Ctrl + V in Telegram saved messages or any chat

### Expected behaviour
the actual size of the image is **699 KB** (2000x2501)
so it should be 699 KB while uploading too

### Actual behaviour
but it becomes **4.47MB** while uploading
it also converts it into PNG

![image](https://user-images.githubusercontent.com/63210113/129474168-f447fe09-870a-4190-b8a0-1a2ab8ade1fd.png)

the first is copy - pasted
second one is drag and drop from file viewer

the resolution remains the same (2000x2501)

**Comment by ilya-fedin** [comment]
Part of issue template was removed -> issue is invalid

**Comment by Aokromes** [comment]
other programs like discord have same issue, maybe the problem is somewhere else.

**Comment by ilya-fedin** [comment]
It's not a problem, it's just how clipboard works. When you copy image by content, original format is not preserved, but converted to a predefined format requested by platform protocol

**Comment by john-preston** [comment]
@preyasprathap When you get an image from the clipboard, you get not JPEG this image came from, but raw pixels. After that Telegram Desktop gives you two possibilities: you can send it like a photo, scaled to 1280x1280 and compressed to JPEG, or you can send it lossless, as a file, converting to PNG. I don't know how to do that better, sorry :(

**Comment by john-preston** [comment]
But this happens only if you copy _the image_ to the clipboard. If you copy the file (from the file viewer), then it should be pasted as file, without any changes to format or size.
