### ISSUE TITLE
system freeze on jump back while uploading

### ISSUE THREAD

**Issue by ixzh** [telegramdesktop/tdesktop#16822]
### Steps to reproduce
1. upload a folder of files ( large enough to carry out following steps while uploading)
2. search or jump to latest uploaded file
3. jump back by clicking down arrow

### Expected behaviour
jump to the end of the list (the last yet-to-be-uploaded file)

### Actual behaviour
system freeze, tdesktop cpu usage 25% and not responsive, upload speed drop to 0. need to kill telegram process and start over.

### Configuration
**Operating system:**
voidlinux
 _ \______ -     os     Void Linux
| \  ___  \ |    kernel 5.13.10_1
| | /   \ | |    pkgs   851
| | \___/ | |    memory 959M / 3838M
| \______ \_|    de     xmonad
 -_______\       shell  bash
**Version of Telegram Desktop:**
V2.9.2
**Installation source (Linux Only)** - the official website 64bit

**Comment by ilya-fedin** [comment]
>     1. upload a relatively large folder of files

This doesn't sound accurate enough for a bug report

**Comment by ilya-fedin** [comment]
Ideally, you should provide an archive with example files that should trigger the bug

**Comment by ixzh** [comment]
> Ideally, you should provide an archive with example files that should trigger the bug

hi i have this folder of 5GB size 386 files, how can i send over to you for testing?

**Comment by ixzh** [comment]
> > ```
> > 1. upload a relatively large folder of files
> > ```
> 
> This doesn't sound accurate enough for a bug report

i mean do jump operations while the upload is still in progress, the size is merely to give enough time period to do the operations while uploading

**Comment by ixzh** [comment]
hmmm this is a persisting issue for me: if i searching something while uploading is in progress, the app will freeze if I jump to the searched results.

**Comment by ilya-fedin** [comment]
I don't see anything like this ¯\_(ツ)_/¯
