### ISSUE TITLE
Telegram Windows is not re-drawn when using Windows 11

### ISSUE THREAD

**Issue by yooakim** [telegramdesktop/tdesktop#16828]
When I use Telegram Desktop 2.9.2 on Windows 11 (10.0.22000) the Telegram window will not re-display once minimized. I have to kill the Telegram process in order for the Telegram Desktop window to be visible again.

1. Open Telegram Desktop
2. Read a few message or similar
3. Minimize the Telegram Desktop window
4. Try to open the minimized Telegram 

### Expected behaviour
After the Telegram Windows has been minimzed it should be possible to re-open/show the window.

### Actual behaviour
The Telegram Desktop window will not show again once minimized.

### Configuration

* Windows 11 (10.0.22000)
* Telegram Desktop 2.9.2 (installed via `winget install Telegram.TelegramDesktop` )

#### Workaround

NB: If I change the Settings/Advanced/Use system window frame it works as expected.

**Comment by Aokromes** [comment]
works for me using the downloaded from webpage version, what's your gfx card?

**Comment by john-preston** [comment]
I can't reproduce that as well (on the version from https://desktop.telegram.org, but it should be identical to the winget version).

**Comment by Aokromes** [comment]
Version 10.0.22000.132 here btw.

**Comment by yooakim** [comment]
My graphics card is a NVIDIA GeForce RTX 3070 @Aokromes.

**Comment by yooakim** [comment]
I did the same on another fresh install of Windows 11 and got the same issue (same hardware though).

**Comment by vitaliyistomov** [comment]
I can confirm the same behavior. Windows 11 22000.348, 2xGeForce RTX 3090 (no nvlink, driver 510.06). I started happening ~today, but I do not think I touched anything to break it. Reboot fixes it.
