### ISSUE TITLE
Build on Linux failed

### ISSUE THREAD

**Issue by vladcohen** [telegramdesktop/tdesktop#16821]
### Steps to reproduce
Proceed according to the instruction: https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md 

### Expected behaviour
The process goes through without errors.

### Actual behaviour
The Step "Building the project" is interrupted due to several errors (s. a full output in build.log):
[build.log](https://github.com/telegramdesktop/tdesktop/files/6993662/build.log)

$ docker run --rm -it \
>     -v $PWD:/usr/src/tdesktop \
>     tdesktop:centos_env \
>     /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
>     -D TDESKTOP_API_ID=xxxxxxx \
>     -D TDESKTOP_API_HASH=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \
>     -D DESKTOP_APP_USE_PACKAGED=OFF \
>     -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF
Warn about uninitialized values.
Version: 2.9.3
-- The C compiler identification is GNU 9.3.1
-- The CXX compiler identification is GNU 9.3.1
-- Check for working C compiler: /opt/rh/devtoolset-9/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-9/root/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-9/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-9/root/usr/bin/c++ - works
(...)
[ 58%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/boxes/peers/edit_peer_info_box.cpp.o
[ 58%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/boxes/peers/edit_peer_invite_link.cpp.o
[ 58%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/boxes/peers/edit_peer_invite_links.cpp.o
[ 59%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/boxes/peers/edit_peer_type_box.cpp.o
[ 59%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/boxes/peers/edit_peer_history_visibility_box.cpp.o
[ 59%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/boxes/peers/edit_peer_permissions_box.cpp.o
[ 59%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/boxes/about_box.cpp.o
[ 59%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/boxes/abstract_box.cpp.o
[ 59%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/boxes/add_contact_box.cpp.o
[ 59%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/boxes/auto_lock_box.cpp.o
/usr/src/tdesktop/Telegram/SourceFiles/boxes/auto_lock_box.cpp: In lambda function:
/usr/src/tdesktop/Telegram/SourceFiles/boxes/auto_lock_box.cpp:80:26: error: 'CreateChild' was not declared in this scope; did you mean 'Ui::CreateChild'?
   80 |   const auto timeInput = CreateChild<Ui::TimeInput>(
      |                          ^~~~~~~~~~~
      |                          Ui::CreateChild
In file included from /usr/src/tdesktop/Telegram/lib_ui/ui/rp_widget.h:11,
                 from /usr/src/tdesktop/Telegram/lib_ui/ui/layers/layer_widget.h:9,
                 from /usr/src/tdesktop/Telegram/lib_ui/ui/layers/box_layer_widget.h:11,
                 from /usr/src/tdesktop/Telegram/SourceFiles/boxes/abstract_box.h:10,
                 from /usr/src/tdesktop/Telegram/SourceFiles/boxes/auto_lock_box.h:10,
                 from /usr/src/tdesktop/Telegram/SourceFiles/boxes/auto_lock_box.cpp:8:
/usr/src/tdesktop/Telegram/lib_ui/ui/ui_utility.h:56:15: note: 'Ui::CreateChild' declared here
   56 | inline Value *CreateChild(
      |               ^~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/boxes/auto_lock_box.cpp:80:51: error: expected primary-expression before '>' token
   80 |   const auto timeInput = CreateChild<Ui::TimeInput>(
      |                                                   ^
/usr/src/tdesktop/Telegram/SourceFiles/boxes/auto_lock_box.cpp:84:27: warning: left operand of comma operator has no effect [-Wunused-value]
   84 |     : kDefaultCustom.utf8(),
      |                           ^
/usr/src/tdesktop/Telegram/SourceFiles/boxes/auto_lock_box.cpp:85:8: warning: right operand of comma operator has no effect [-Wunused-value]
   85 |    st::autolockTimeField,
      |    ~~~~^~~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/boxes/auto_lock_box.cpp:86:8: warning: right operand of comma operator has no effect [-Wunused-value]
   86 |    st::autolockDateField,
      |    ~~~~^~~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/boxes/auto_lock_box.cpp:87:8: warning: right operand of comma operator has no effect [-Wunused-value]
   87 |    st::scheduleTimeSeparator,
      |    ~~~~^~~~~~~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/boxes/auto_lock_box.cpp: In member function 'virtual void AutoLockBox::prepare()':
/usr/src/tdesktop/Telegram/SourceFiles/boxes/auto_lock_box.cpp:71:13: error: 'const void timeInput' has incomplete type
   71 |  const auto timeInput = [&] {
      |             ^~~~~~~~~
[ 59%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/boxes/auto_download_box.cpp.o
gmake[2]: *** [Telegram/CMakeFiles/Telegram.dir/build.make:826: Telegram/CMakeFiles/Telegram.dir/SourceFiles/boxes/auto_lock_box.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:2352: Telegram/CMakeFiles/Telegram.dir/all] Error 2
gmake: *** [Makefile:104: all] Error 2

### Configuration
**Operating system:** Ubuntu 18.04.5

**Version of Telegram Desktop:** 2.9.3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
GitHub releases
**Used theme**:

<details><summary><b>Logs</b>:</summary>
[CMakeError.log](https://github.com/telegramdesktop/tdesktop/files/6993634/CMakeError.log)
[CMakeError.log](https://github.com/telegramdesktop/tdesktop/files/6993639/CMakeError.log)
</details>

**Comment by 23rd** [comment]
Should be fine now.

**Comment by vladcohen** [comment]
Sorry, but it still does not work (see also lines 407-591 and 1452-1475 in the output file build2.log):
[build2.log](https://github.com/telegramdesktop/tdesktop/files/7000766/build2.log)

[ 71%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_user_photos.cpp.o
[ 71%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_wall_paper.cpp.o
[ 71%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_web_page.cpp.o
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp: In function 'QImage Data::GenerateWallPaper(QSize, const std::vector<QColor>&, int, float64, Fn<void(QPainter&)>)':
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:711:13: error: 'GenerateGradient' is not a member of 'Images'
  711 |   ? Images::GenerateGradient(size, { DefaultBackgroundColor() })
      |             ^~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:712:13: error: 'GenerateGradient' is not a member of 'Images'
  712 |   : Images::GenerateGradient(size, bg, gradientRotation);
      |             ^~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:714:20: error: 'DitherImage' is not a member of 'Images'
  714 |   result = Images::DitherImage(std::move(result));
      |                    ^~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp: In function 'QImage Data::GenerateDitheredGradient(const std::vector<QColor>&, int)':
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:764:18: error: 'GenerateGradient' is not a member of 'Images'
  764 |   return Images::GenerateGradient(size, { DefaultBackgroundColor() });
      |                  ^~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:766:24: error: 'GenerateGradient' is not a member of 'Images'
  766 |  auto result = Images::GenerateGradient(size, colors, rotation);
      |                        ^~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:768:20: error: 'DitherImage' is not a member of 'Images'
  768 |   result = Images::DitherImage(std::move(result));
      |                    ^~~~~~~~~~~
[ 72%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/dialogs/dialogs_entry.cpp.o
gmake[2]: *** [Telegram/CMakeFiles/Telegram.dir/build.make:2851: Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_wall_paper.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:2352: Telegram/CMakeFiles/Telegram.dir/all] Error 2
gmake: *** [Makefile:104: all] Error 2

**Comment by vladcohen** [comment]
> Should be fine now.

Sorry, but it still does not work (see also lines 407-591 and 1452-1475 in the output file build2.log):
[build2.log](https://github.com/telegramdesktop/tdesktop/files/7000766/build2.log)

[ 71%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_user_photos.cpp.o
[ 71%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_wall_paper.cpp.o
[ 71%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_web_page.cpp.o
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp: In function 'QImage Data::GenerateWallPaper(QSize, const std::vector<QColor>&, int, float64, Fn<void(QPainter&)>)':
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:711:13: error: 'GenerateGradient' is not a member of 'Images'
  711 |   ? Images::GenerateGradient(size, { DefaultBackgroundColor() })
      |             ^~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:712:13: error: 'GenerateGradient' is not a member of 'Images'
  712 |   : Images::GenerateGradient(size, bg, gradientRotation);
      |             ^~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:714:20: error: 'DitherImage' is not a member of 'Images'
  714 |   result = Images::DitherImage(std::move(result));
      |                    ^~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp: In function 'QImage Data::GenerateDitheredGradient(const std::vector<QColor>&, int)':
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:764:18: error: 'GenerateGradient' is not a member of 'Images'
  764 |   return Images::GenerateGradient(size, { DefaultBackgroundColor() });
      |                  ^~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:766:24: error: 'GenerateGradient' is not a member of 'Images'
  766 |  auto result = Images::GenerateGradient(size, colors, rotation);
      |                        ^~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:768:20: error: 'DitherImage' is not a member of 'Images'
  768 |   result = Images::DitherImage(std::move(result));
      |                    ^~~~~~~~~~~
[ 72%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/dialogs/dialogs_entry.cpp.o
gmake[2]: *** [Telegram/CMakeFiles/Telegram.dir/build.make:2851: Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_wall_paper.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:2352: Telegram/CMakeFiles/Telegram.dir/all] Error 2
gmake: *** [Makefile:104: all] Error 2

**Comment by john-preston** [comment]
@vladcohen Can you try adding `#include "ui/image/image_prepare.h"` to `SourceFiles/data/data_wall_paper.cpp` top section? If it helps I'll add it as well in the source.

**Comment by vladcohen** [comment]
> @vladcohen Can you try adding `#include "ui/image/image_prepare.h"` to `SourceFiles/data/data_wall_paper.cpp` top section? If it helps I'll add it as well in the source.

I synchronized repositories (now I have sources from 2.9.4.beta) and then added the include line into SourceFiles/data/data_wall_paper.cpp (attached as .txt). Unfortunately it didn't help: 
[data_wall_paper.txt](https://github.com/telegramdesktop/tdesktop/files/7014842/data_wall_paper.txt)
[build3.log](https://github.com/telegramdesktop/tdesktop/files/7014874/build3.log)

[ 71%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_user.cpp.o
[ 71%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_user_photos.cpp.o
[ 71%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_wall_paper.cpp.o
[ 71%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_web_page.cpp.o
[ 72%] Building CXX object Telegram/CMakeFiles/Telegram.dir/SourceFiles/dialogs/dialogs_entry.cpp.o
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp: In function 'QImage Data::GenerateWallPaper(QSize, const std::vector<QColor>&, int, float64, Fn<void(QPainter&)>)':
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:712:13: error: 'GenerateGradient' is not a member of 'Images'
  712 |   ? Images::GenerateGradient(size, { DefaultBackgroundColor() })
      |             ^~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:713:13: error: 'GenerateGradient' is not a member of 'Images'
  713 |   : Images::GenerateGradient(size, bg, gradientRotation);
      |             ^~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:715:20: error: 'DitherImage' is not a member of 'Images'
  715 |   result = Images::DitherImage(std::move(result));
      |                    ^~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp: In function 'QImage Data::GenerateDitheredGradient(const std::vector<QColor>&, int)':
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:774:18: error: 'GenerateGradient' is not a member of 'Images'
  774 |   return Images::GenerateGradient(size, { DefaultBackgroundColor() });
      |                  ^~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:776:24: error: 'GenerateGradient' is not a member of 'Images'
  776 |  auto result = Images::GenerateGradient(size, colors, rotation);
      |                        ^~~~~~~~~~~~~~~~
/usr/src/tdesktop/Telegram/SourceFiles/data/data_wall_paper.cpp:778:20: error: 'DitherImage' is not a member of 'Images'
  778 |   result = Images::DitherImage(std::move(result));
      |                    ^~~~~~~~~~~
gmake[2]: *** [Telegram/CMakeFiles/Telegram.dir/build.make:2851: Telegram/CMakeFiles/Telegram.dir/SourceFiles/data/data_wall_paper.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:2352: Telegram/CMakeFiles/Telegram.dir/all] Error 2
gmake: *** [Makefile:104: all] Error 2

**Comment by john-preston** [comment]
@vladcohen That's really strange, because if you've added "ui/image/image_prepare.h" to "SourceFiles/data/data_wall_paper.cpp", then it should find those "Images::GenerateGradient" and "Images::DitherImage" here:

https://github.com/desktop-app/lib_ui/blob/master/ui/image/image_prepare.h#L30-L32

Unless lib_ui is on a wrong commit.
