### ISSUE TITLE
[Question] Telegram censorship? Big Brother is watching you?

### ISSUE THREAD

**Issue by Cosmotan01** [telegramdesktop/tdesktop#16820]
Does Telegram use censure and delete channels ????
![Clipboard01](https://user-images.githubusercontent.com/70658006/129570514-2952eaab-9f08-445f-835b-95be22068a6e.jpg)
If this is true we need a Fork of Telegram Desktop to be free! Uncensored!
Now sounds like fu**ing Youtube piece of crap!
Thx
Cheers!

**Comment by RememberTheAir** [comment]
Telegram has always removed/hidden public content that violates their ToS.

Apps downloaded form the store also hide content that violets the stores' policies. If you downloaded tdesktop from the website, and enabled the option to see sensitive content from your Privacy & Security settings, then some content is unlocked. Anyway, some channels are blocked server side so no fork of this app will be able to display them
