### ISSUE TITLE
Wrong/different view on a Callback Answer with alert=False

### ISSUE THREAD

**Issue by New-dev0** [telegramdesktop/tdesktop#16825]
### Steps to reproduce
1. Register a Callback handler with no alert.
2. Click on that Button
3. & done [reproduced] 

### Expected behaviour
Expected Behaviour [output should be come in box, below the chat title] (as in Tg Android)
<p align="center">
<img src="https://telegra.ph/file/8572e66fe56ddc2504ff1.jpg" width="80%">
</p>

### Actual behaviour
It shows the Output same as alert=True/with pop-up
<p align="center">
<img src="https://telegra.ph/file/444006d53e8a33b3d9260.jpg" width="80%">
</p>

### Configuration
**Operating system:** `Windows`

**Version of Telegram Desktop:** `2.9.2`

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: `Dark Mode`

**Comment by john-preston** [comment]
The change is a tooltip or a popup box, I guess. No top bar UI for the callback responses, sorry.
