### ISSUE TITLE
system freeze while uploading

### ISSUE THREAD

**Issue by ixzh** [telegramdesktop/tdesktop#16823]
### Steps to reproduce
1.  upload files from a folder
2.  the file picker will generate the file list 
3.  it choked at file 328, system freeze, RAM 100% 

### Expected behaviour
all 386 files (about 5GB) shall be listed and start uploading.

### Actual behaviour
system freeze with RAM 100% SWAP 100%. hard reset of the computer is required.

I have uploaded bigger folder with larger files with no problem, just this folder 386 files, it always choked at file 328.

I restarted the computer with no other app opened. just telegram. it still failed to upload this particular folder. The list stopped at file 328 and system freeze after RAM all used up.

### Configuration
**Operating system:**
voidlinux 
**Version of Telegram Desktop:**
V2.9.2
**Installation source (Linux Only)** - the official website

**Comment by ixzh** [comment]
i notice when i copy paste 40 JPEG files 158MB, the ram also surge to 100% (4GB) not sure why that is happening...

**Comment by ilya-fedin** [comment]
The client opens images in order to show them to you while uploading, so all of them are decoded and the decoded data is placed to RAM. You can't upload so big amount of images at once.

**Comment by ilya-fedin** [comment]
Duplicate of #16055

**Comment by ixzh** [comment]
> The client opens images in order to show them to you while uploading, so all of them are decoded and the decoded data is placed to RAM. You can't upload so big amount of images at once.

hmmm decoding 100MB jpeg used up 4GB RAM🥶 is that expected behavior?  I'd send them as uncompressed files anyway so can decoding precess be disabled by default 😌😌😌

**Comment by ilya-fedin** [comment]
You can't present the image without decoding it

**Comment by ixzh** [comment]
> You can't present the image without decoding it

:( I find versions before album feature came into being doesn't have this problem... I'll try out earlier version again.. Many thanks! Closing this since it is repeated.

**Comment by john-preston** [comment]
Yes, before it only listed the amount of files, not the previews of files to be sent :( The previews generation could and should be optimized indeed.
