### ISSUE TITLE
No typing status in chats list

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#16826]
This is a copy of locked #14916. Sometimes (but not always) there is no "typing..." status in chat list, only in chat itself. 
I don't know how to reproduce it, sorry.

### Expected behaviour
There should be "typing..." status in chat list when the other party is typing

### Actual behaviour
Sometimes this status doesn't appear even if the other party is typing (can be easily checked by opening chat with them)

### Configuration
**Operating system:** Manjaro

**Version of Telegram Desktop:** 2.9.2 Beta

**Installation source (Linux Only):** Github

**Comment by MasterGroosha** [comment]
There is another issue (#14723) which mentions private chats. I don't remember encountering this bug with groups, however, I'm also not 100% sure. But I do encounter this bug with private chats (one-to-one)

**Comment by MasterGroosha** [comment]
Also one person noticed that it happens with private chats with no "last seen" visible.
I mean, if you see the other person's last seen time, then you will see typing status in chats list
Otherwise, you won't see it.

Is it a new server-side feature?

**Comment by ilya-fedin** [comment]
> This is a copy of locked #14916

it's a copy created by spambot, original one is still open (#8952).
