### ISSUE TITLE
Windows x64 desktop doesn't obey theme and Dark Mode user preferences at start

### ISSUE THREAD

**Issue by tudorminator** [telegramdesktop/tdesktop#16827]
### Steps to reproduce
1. Open hamburger menu and set Night Mode to `ON`;
1. Open Settings, go to Chat Settings, select `Tinted` in the Themes section and some color from the color wells below (mine is `#697b97`, the purple which is the second to last on the right);
1. Enjoy the dark theme while using Telegram;
1. Quit Telegram using the tray icon context menu;
1. Reopen Telegram;
1. Observe how it has now reverted to `Classic` theme (white/green) and Night Mode is **NOT** active, but the menu toggle is still shown as `ON`;

![telegram-2 9 2x64-win_2021-08-17_104125](https://user-images.githubusercontent.com/1481233/129688542-f31ea1fb-33fa-4a16-8b24-790d1d50e8eb.png)
_Note_: Interface scale is set to 150% in the screnshot, but setting it back to default doesn't influence this behaviour.

### Expected behaviour
The application should be in Night Mode, using the user selected theme.

### Actual behaviour
The application starts up with Night Mode `OFF` and using the Classic theme.

### Workaround
Manually toggle Night Mode to `OFF` and then back `ON` and the correct theme is re-applied.

### Configuration
**Operating system:** Windows 10 21H1 (Build 19043.1052)

**Version of Telegram Desktop:** 2.9.2 x64

**Used theme**: `Tinted`, with accent color `#697b97`

**Comment by john-preston** [comment]
I couldn't reproduce that with freshly downloaded and logged-in 2.9.2 portable from https://desktop.telegram.org. When I've reopened the app it was still dark with the selected accent color. Can you try to reproduce with freshly downloaded portable version extracted to some new empty folder?

**Comment by tudorminator** [comment]
Thank you @john-preston. Strangely enough, it doesn't happen with the portable version running from a subdirectory of my home directory. Which shouldn't make any difference really, since the installed one is in `AppData\Roaming\Telegram Desktop`...

**Comment by john-preston** [comment]
@tudorminator Maybe this is something saved in the installation folder, some broken settings. Please try renaming "AppData\Roaming\Telegram Desktop" to "AppData\Roaming\Telegram Backup" and reproduce from a fresh folder?

**Comment by tudorminator** [comment]
I'm sorry, already uninstalled it before seeing your message, which also erased the profile folder. But after re-installing it I can confirm that **I cannot reproduce it anymore** 🥳. I wish I could diff the old and new profile folders to see if I can spot the culprit, but alas...

I'll make sure to open a new issue in case it starts happening again. Thanks again @john-preston for your assistance.
