### ISSUE TITLE
[Bug] UI: White borders around window and context menu widgets.

### ISSUE THREAD

**Issue by j3su5cr1st** [telegramdesktop/tdesktop#16837]
### Steps to reproduce
1. Install Manjaro 
2. Start GNOME 40 Wayland session
3. Start telegram

### Expected behavior
Simple launching without white borders

### Actual behavior
![image](https://user-images.githubusercontent.com/45117783/130202394-ec699de2-97f7-4063-8860-e86354282959.png)

### Configuration
**Operating system:** 
OS: Manjaro 21.1.0 Pahvo
Resolution: 3840x1080
Kernel: x86_64 Linux 5.4.138-1-MANJARO
CPU: AMD Ryzen 5 2600 Six-Core @ 12x 3.4GHz
Drivers: amdgpu-pro

```bash
➜  ~ lsmod | grep amdgpu
amdgpu               5128192  14
```

**Version of Telegram Desktop:** 2.3.9

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: yay

**Used theme**: System depends (black)

<details><summary><b>Logs</b>:</summary>➜  ~ telegram-desktop 2> log.txt
➜  ~ cat log.txt 

(telegram-desktop:19059): Telegram-WARNING **: 11:04:40.969: Application was built without embedded fonts, this may lead to font issues.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
DSvgRenderer::load: XML parse error: Error domain 1 code 4 on line 1 column 1 of data: Start tag expected, '<' not found

DSvgRenderer::load: XML parse error: Input file is too short
QCoreApplication::postEvent: Unexpected null receiver

</details>

**Comment by ilya-fedin** [comment]
Are you using Kvantum themes? That looks like your Qt theme force-overrides transparent background with white one

**Comment by ilya-fedin** [comment]
> 2.3.9

Oh, you can't report for old versions, please update to the latest version (2.9.2).

**Comment by j3su5cr1st** [comment]
Well, updated from Arch repository, version ```2.9.3-1```, seems like nothing changed :) 

> Are you using Kvantum themes?
Yes, I am. But, this behaviour became only after Telegram update. In the kvantum settings, I didn't see anything which may be cause of. But, if you know a certain setting, tell me.

**Comment by ilya-fedin** [comment]
> But, this behavior became only after Telegram update.

This doesn't mean that Kvantum couldn't be the cause

> In the kvantum settings, I didn't see anything which may be cause of.

Well, try to get rid of it. I don't know what can cause in it, but I'm sure Kvantum or platformtheme plugin (like qgnomeplatform) is the cause. There were reports like that, but each time reporters went MIA, so issues were closed.

**Comment by j3su5cr1st** [comment]
Btw, now it really seems like kvantum issue, the borders became "Gnome Dark". BRB with details.

![image](https://user-images.githubusercontent.com/45117783/130349179-53b62ecc-1bbe-45af-8907-613dc894a6c3.png)

**Comment by ilya-fedin** [comment]
Probably you should report that for kvantum instead

**Comment by j3su5cr1st** [comment]
After googling, I found same issues on [reddit](https://www.reddit.com/r/kde/comments/b3otq2/cant_remove_annoying_border/) and [Github](https://github.com/tsujan/Kvantum/issues/242) I've also encountering when I used KDE. Also, I've tried to disable some settings which force overrides appearance features. Seems like Kvantum manager does not use "magic" settings which break the UI. Do u have any ideas?

**Comment by j3su5cr1st** [comment]
UPD:
The solution I found is ```unset QT_STYLE_OVERRIDE telegram-desktop```. Maybe it's a cool idea to force unset this variable before launching app on linux in ```.desktop``` file i think.
![image](https://user-images.githubusercontent.com/45117783/130351145-b7f65585-61a3-4c41-be1a-e305a22cdfc0.png)

**Comment by ilya-fedin** [comment]
> Do u have any ideas?

No, I think only kvantum devs know what's going on

> The solution I found is `unset QT_STYLE_OVERRIDE telegram-desktop`. Maybe it's a cool idea to force unset this variable before launching app on linux in `.desktop` file i think.

Definitely not cool, this makes tdesktop (and all processes started from it) ignore your Qt theme

**Comment by ilya-fedin** [comment]
>  I found same issues on [reddit](https://www.reddit.com/r/kde/comments/b3otq2/cant_remove_annoying_border/) and Github [here](https://github.com/kupiqu/SierraBreezeEnhanced/issues/24) and [here](https://github.com/tsujan/Kvantum/issues/242)

> Oh, that isn't related to Kvantum but to the window decoration you use. Kvantum doesn't draw title-bars or window borders (== decoration); the window manager does.

He misses the fact that kwin is written in Qt, so Kvantum can influence on kwin and change decoration appearance (including adding some sublayer, just like with tdesktop).

**Comment by j3su5cr1st** [comment]
So, is there variant to make an option in settings to ignore custom themes as it did with notification? 
![image](https://user-images.githubusercontent.com/45117783/130355101-c3a3aeb8-b18f-4d02-9a97-a0c4c11c97c5.png)

It can be placed in Advanced -> System Integration.
![image](https://user-images.githubusercontent.com/45117783/130355138-372a5c6e-7aa3-49c8-a059-aaf29cec7404.png)

**Comment by ilya-fedin** [comment]
it doesn't 'ignore custom themes with notification', it has two notifications implementations: QtWidgets based and D-Bus based.

I'm definitely against having such a hack. It's a Kvantum's problem, not tdesktop's one.
