### ISSUE TITLE
Animated chat background isn't animated when messaging to 'Saved Messages'

### ISSUE THREAD

**Issue by pahanus** [telegramdesktop/tdesktop#16831]
### Steps to reproduce

1. Run Telegram 2.9.4. Beta x64
2. Go Settings - Chat Settings - Chat background
3. Choose default background with algebra patterns from gallery
4. Send message to 'Saved Messages'

### Expected behaviour
Background have to be animated and it's get when you send message to anybody, any bot, except 'Saved Messages' chat.

### Actual behaviour
Background isn't get animated in 'Saved Messages' chat.

### Configuration
**Operating system:** Windows 21H1 Build 19043

**Version of Telegram Desktop:** Telegram 2.9.4. Beta x64

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Night mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
Thank you for the report! It'll be fixed in the next version.
