### ISSUE TITLE
Telegram Desktop: Close Window Button Disappeared

### ISSUE THREAD

**Issue by Apollon97** [telegramdesktop/tdesktop#16839]
### Steps to reproduce
1. start telegram app
2. try to close the window
3. try to reduce the seize of window

### Expected behaviour
As a user, I should be able to close and reduce the window size

### Actual behaviour
Can't close the window nor reduce it

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
2.9.2
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
dark
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
> ### Steps to reproduce
> 1. start telegram app
> 2. try to close the window
> 3. try to reduce the seize of window
> 
> ### Expected behaviour
> As a user, I should be able to close and reduce the window size
> 
> ### Actual behaviour
> Can't close the window nor reduce it
> 
> ### Configuration
> **Operating system:**
> Windows 10
> 
> **Version of Telegram Desktop:**
> 2.9.2
> **Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
> 
> **Used theme**:
> dark
> 
> Logs:

plz update to 2.9.5 beta.
