### ISSUE TITLE
Inline (compressed) image is rendered with a black border when replying to a message

### ISSUE THREAD

**Issue by earshinov** [telegramdesktop/tdesktop#16838]
### Steps to reproduce

1. Take this image:
![done](https://user-images.githubusercontent.com/52021/130319532-55cd1803-b74b-479c-8194-c2b4f9bd877e.jpg)

2. Copy and paste it into your Saved messages with "Compress image" checked. Result:
![pasted 1](https://user-images.githubusercontent.com/52021/130319745-c18c272d-4b2d-43b5-b13d-2e1f3268db65.png)

3. Copy it again and paste it into your Saved messages, this time replying to an existing message. Result:
![pasted 2](https://user-images.githubusercontent.com/52021/130319772-4090f4ec-b04c-4ca6-80b0-10e00f404427.png)

### Expected behaviour

There shouldn't be the horrendous black border

### Actual behaviour

There is a horrendous black border

### Configuration

**Operating system:** Windows 20H2 (OS Build 19042.1110)

**Version of Telegram Desktop:** 2.9.2

**Used theme**: "Classic" with a custom background (gray as you can see on the screenshots above)

**Comment by earshinov** [comment]
I think this issue hasn't been resolved yet.

**Comment by earshinov** [comment]
The issue is still reproducible using the steps from the description.

**Comment by john-preston** [comment]
@earshinov This is intended for small (narrow) images. In the next version the black strips on sides will be replaced with blurred image itself, like iOS app does, but there still be such strips for images with small-enough width.

**Comment by earshinov** [comment]
@john-preston , sounds good! Then this issue seems to serve no purpose anymore, feel free to close it as you wish.
