### ISSUE TITLE
Edit messages?

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1684]
In new version of Android Telegram App we can edit messages in channels and supergroups?
Soon this feature will appear in TDesktop?

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov In a couple of days.

**Comment by DaFri-Nochiterov** [comment]
@telegramdesktop, OK, thanks!
We wait :wink:

**Comment by DaFri-Nochiterov** [comment]
Available in 0.9.27 update.
