### ISSUE TITLE
[Question] Slow as hell when GPU is busy, any workaround?

### ISSUE THREAD

**Issue by Razer0123** [telegramdesktop/tdesktop#16846]
I often render so my gpu is at 100% capacity and Telegram becomes unusable, i suppose because it is HW rendered

Any way to disable it? I'm on Linux

**Comment by Aokromes** [comment]
> I often render so my gpu is at 100% capacity and Telegram becomes unusable, i suppose because it is HW rendered
> 
> Any way to disable it? I'm on Linux

disable opengl on settings -> advanced.

**Comment by Razer0123** [comment]
> > I often render so my gpu is at 100% capacity and Telegram becomes unusable, i suppose because it is HW rendered
> > Any way to disable it? I'm on Linux
> 
> disable opengl on settings -> advanced.

I only have an option to disable OpenGL rendering for media

**Comment by ilya-fedin** [comment]
> > 
> 
> I only have an option to disable OpenGL rendering for media

it's the option you need

**Comment by Razer0123** [comment]
> > I only have an option to disable OpenGL rendering for media
> 
> it's the option you need

It's not, Telegram is still slow as hell when gpu is at full load

**Comment by ilya-fedin** [comment]
> It's not, Telegram is still slow as hell when gpu is at full load

That means HW rendering is not the cause

**Comment by Razer0123** [comment]
> > It's not, Telegram is still slow as hell when gpu is at full load
> 
> That means HW rendering is not the cause

Again, it is, tried several times, as soon as i disable gpu load it is fast again

Also it says "OpenGL for media", so it's not relative to the interface

**Comment by john-preston** [comment]
@Razer0123 Yes, but the main window doesn't rely on hardware rendering, it is rendered entirely on CPU.

**Comment by ilya-fedin** [comment]
> Also it says "OpenGL for media", so it's not relative to the interface

because opengl is not used for anything except of media

**Comment by ilya-fedin** [comment]
> Again, it is, tried several times, as soon as i disable gpu load it is fast again

There were such complains even before HW rendering of media was introduced, when tdesktop haven't used GPU for anything, at all. So it's not HW rendering.

**Comment by Razer0123** [comment]
Guys i appreciate you're trying to help, but you're wrong

I've stated above, i have tested a ton of times, works fine, as soon as i start using the gpu it becomes slow. Why do you keep telling me it's not HW rendering related?

Maybe the Linux version is based on something like Electron that uses HW rendering, i don't know

But don't keep telling me HW rendering is not involved, because it is

**Comment by john-preston** [comment]
@Razer0123 Telegram Desktop uses Qt for UI, it paints main window entirely on CPU. Maybe after the window pixmap is fully ready on CPU it is sent to GPU by the window system and there it becomes slow because of that. The UI has a lot of animations that repaint some content in the window frequently, so maybe just composing the updated window pixmap inside your window system makes it slow. You can try disabling animations in Settings > Advanced > Performance, disabling autoplay in Settings > Advanced > Automatic media download. I don't know what else to suggest, no GPU-using code is in the app for the main window, only for media viewer / voice chats / calls.

**Comment by ilya-fedin** [comment]
@Aokromes i think this question can be closed with answer 'No workaround'.
