### ISSUE TITLE
[Feature Request] Dismiss notifications by middle mouse click

### ISSUE THREAD

**Issue by lazurit11** [telegramdesktop/tdesktop#16849]
### Is your feature request related to a problem?
You can dismiss windows notification by middle mouse clicking on it, yet you can't do that with telegram notifications.
That is just faster than aiming on the close icon.

### Describe the solution you'd like
Middle mouse clicking on any place inside telegram notification area should dismiss that notification, as clicking on cross icon does.

### Describe alternatives you've considered
None

### Additional context
None

**Comment by 23rd** [comment]
You can use right click.

**Comment by lazurit11** [comment]
Thanks, didn't try that. But I still think middle click should work too, just to keep things similar.
