### ISSUE TITLE
Gifs will upload but not send to a group if multiple are sent at the same time.

### ISSUE THREAD

**Issue by kaasknak** [telegramdesktop/tdesktop#16844]
### Steps to reproduce
1. Open up a group on the desktop version for linux.
2. Send two or more .gif files to this group at the same time.

### Expected behaviour
The gifs should all upload and then be send to the group.

### Actual behaviour
Uploading happens as normal but the gif becomes stuck and is never sent to the group. This does not happen if you send gifs one by one.

### Configuration
**Operating system:** Ubuntu 20.04.2

**Version of Telegram Desktop:** 2.9.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Official website.

**Used theme**: Light mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by kaasknak** [comment]
What? Why? Nothing got solved.

**Comment by john-preston** [comment]
It is solved in a commit (so, should be fixed in the next released version).

**Comment by kaasknak** [comment]
Ah okay. Thanks for the clarification!
