### ISSUE TITLE
Appearance of the "report spam and exit" button when you voluntarily enter the chat on your own using the link

### ISSUE THREAD

**Issue by AkciumKicum** [telegramdesktop/tdesktop#16843]
### Actions to play
1.create a new chat
2.generate link
3. enter the chat on this link

### Expected Behavior
The user enters the chat and does not see the button with the text "Report spam and exit"

### Actual Behavior
The user enters the chat, and sees buttons with the text "Report spam and exit", as if he did not join voluntarily, but was added to the chat.

### Configuration
** Operating system: Windows 10 (played on windows 7 as well)

** Telegram Desktop version: 2.9.5 beta x64 (first encountered 2.7.4 х32)

** Theme used **: any

![image](https://user-images.githubusercontent.com/32580360/130363109-6808ccec-7ddc-45bf-83a7-fa3952b9c88f.png)
![image](https://user-images.githubusercontent.com/32580360/130363129-46d38d81-b669-4165-a43e-28015f679e86.png)

**Comment by RememberTheAir** [comment]
Are you sure you're using tdesktop? The number of accounts and squared icons doesn't track

**Comment by AkciumKicum** [comment]
I used a custom version for display convenience.
Here is the official TG. The situation is similar.
I can attach any screenshots where needed. The situation will remain the same.

![image](https://user-images.githubusercontent.com/32580360/130602837-2bd21917-b1ff-4cc4-a5fc-4c429e41ba32.png)
![image](https://user-images.githubusercontent.com/32580360/130602878-e08f8b7a-02b7-4bb9-870d-affa0ea92bd9.png)

**Comment by Benzgood77** [comment]
3_4
