### ISSUE TITLE
Telegram does not start

### ISSUE THREAD

**Issue by broadhurstM** [telegramdesktop/tdesktop#16848]
### Steps to reproduce
1.  Start Telegram app

### Expected behaviour
Аpplication launch

### Actual behaviour
Error window, nothing starts

### Configuration
Windows 10 21H1

**Version of Telegram Desktop:**
2.9.2.0  x64

**Used theme**:
Night

<details><summary><b>[2021.08.23] Launched version: 2009002, install beta: [FALSE], alpha: 0, debug mode: [FALSE]
[2021.08.23] Executable dir: E:/Telegram Desktop/New folder/, name: Telegram.exe
[2021.08.23 ] Initial working dir: E:/Telegram Desktop/New folder/
[2021.08.23 ] Working dir: E:/Telegram Desktop/New folder/
[2021.08.23 ] Command line: E:\Telegram Desktop\New folder\Telegram.exe
[2021.08.23 ] Executable path before check: E:/Telegram Desktop/New folder/Telegram.exe
[2021.08.23] Logs started
[2021.08.23 ] Connecting local socket to Global\87bf621edd818927e7fc29847b9cb6e-{87A94AB0-E370-4cde-98D3-ACC110C5967}...
[2021.08.23] This is the only instance of Telegram, starting server and app...
[2021.08.23 ] Could not delete 'E:/Telegram Desktop/New folder/log.txt' file to start new logging: The process cannot access the file because it is being used by another process.
[2021.08.23] Executable path before check: E:/Telegram Desktop/New folder/Telegram.exe
[2021.08.23  FATAL: Could not move logging to 'E:/Telegram Desktop/New folder/log.txt'!
[2021.08.23 ] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2021.08.23 ] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2021.08.23] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2021.08.23 ] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2021.08.23 ] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2021.08.23] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2021.08.23 ] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2021.08.23] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2021.08.23 ] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2021.08.23 ] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2021.08.23] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2021.08.23 ] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'</b>:</summary>
Insert log.txt here (if necessary)
</details>

Same error as here:
https://github.com/telegramdesktop/tdesktop/issues/9837
https://github.com/telegramdesktop/tdesktop/issues/4756

**Comment by Aokromes** [comment]
2021.08.23 ] Could not delete 'E:/Telegram Desktop/New folder/log.txt' file to start new logging: The process cannot access the file because it is being used by another process.

the log is clear, telegram is running on background.

**Comment by GermannPerutskij** [comment]
> 2021.08.23 ] Could not delete 'E:/Telegram Desktop/New folder/log.txt' file to start new logging: The process cannot access the file because it is being used by another process.
> 
> the log is clear, telegram is running on background.

I know, but i can't detect what app using log.txt, and i can't delete this file

**Comment by Aokromes** [comment]
> > 2021.08.23 ] Could not delete 'E:/Telegram Desktop/New folder/log.txt' file to start new logging: The process cannot access the file because it is being used by another process.
> > the log is clear, telegram is running on background.
> 
> I know, but i can't detect what app using log.txt, and i can't delete this file

go task manager, you will find telegram there.

**Comment by GermannPerutskij** [comment]
> > > 2021.08.23 ] Could not delete 'E:/Telegram Desktop/New folder/log.txt' file to start new logging: The process cannot access the file because it is being used by another process.
> > > the log is clear, telegram is running on background.
> > 
> > 
> > I know, but i can't detect what app using log.txt, and i can't delete this file
> 
> go task manager, you will find telegram there.

It is not so easy. It does not display the telegram process running. Also, Windows did not give any results for finding a process that would use the log.txt file

**Comment by ilya-fedin** [comment]
> Also, Windows did not give any results for finding a process that would use the log.txt file

Maybe it's antivirus or similar software?

**Comment by Aokromes** [comment]
> > > > 2021.08.23 ] Could not delete 'E:/Telegram Desktop/New folder/log.txt' file to start new logging: The process cannot access the file because it is being used by another process.
> > > > the log is clear, telegram is running on background.
> > > 
> > > 
> > > I know, but i can't detect what app using log.txt, and i can't delete this file
> > 
> > 
> > go task manager, you will find telegram there.
> 
> It is not so easy. It does not display the telegram process running. Also, Windows did not give any results for finding a process that would use the log.txt file

i am 100% it's stuck on background go scroll near end of task manager, you will see telegram stuck there, right click over it -> create dump and send to https://t.me/preston to see if he can do something about it.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16441#issuecomment-863796473

**Comment by GermannPerutskij** [comment]
> > > > > 2021.08.23 ] Could not delete 'E:/Telegram Desktop/New folder/log.txt' file to start new logging: The process cannot access the file because it is being used by another process.
> > > > > the log is clear, telegram is running on background.
> > > > 
> > > > 
> > > > I know, but i can't detect what app using log.txt, and i can't delete this file
> > > 
> > > 
> > > go task manager, you will find telegram there.
> > 
> > 
> > It is not so easy. It does not display the telegram process running. Also, Windows did not give any results for finding a process that would use the log.txt file
> 
> i am 100% it's stuck on background go scroll near end of task manager, you will see telegram stuck there, right click over it -> create dump and send to https://t.me/preston to see if he can do something about it.

No, sorry, there are nothing. Any other ideas?

**Comment by GermannPerutskij** [comment]
> > Also, Windows did not give any results for finding a process that would use the log.txt file
> 
> Maybe it's antivirus or similar software?

No antivirus are in use

**Comment by ilya-fedin** [comment]
> No antivirus are in use

The fact that the file is in use and there's no process visible means that something is using it and hides itself. So you either have an antivirus (Windows has one out-of-the-box and there's no guarantee you can fully disable it + a lot of other security subsystems like smartscreen) or a virus.

**Comment by neolace** [comment]
try this:
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

Task manager on steroids, when you have it open:
Select the menu option to check with VirusTotal, it should then populate a column next to each running process indicating whether that process could be infected.

As you can take explorer.exe and inject your virus code  while keeping the file name the same.

Please let me know if you have a clean slate, so we can take it from there.

**Comment by GermannPerutskij** [comment]
> try this:
> https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
> 
> Task manager on steroids, when you have it open:
> Select the menu option to check with VirusTotal, it should then populate a column next to each running process indicating whether that process could be infected.
> 
> As you can take explorer.exe and inject your virus code while keeping the file name the same.
> 
> Please let me know if you have a clean slate, so we can take it from there.

Ok, i will try

**Comment by neolace** [comment]
@GermannPerutskij 

Did it help?

**Comment by neolace** [comment]
I haven't received any feedback.

Can we close this one?

**Comment by neolace** [comment]
> @GermannPerutskij
> 
> Did it help?

Please provide feedback?

**Comment by missTao** [comment]
Sup! Similar problem. Log-file is deleted without problems, but lol, this don't affect the fix. Any other ideas?

**Comment by sanovskiy** [comment]
Got the same problem. In my case this file was locked by daemon tools. Dunno why. After DT deletion everything worked fine.
