### ISSUE TITLE
Unwanted feature - string replacements make sending plaintext code difficult

### ISSUE THREAD

**Issue by timkrins** [telegramdesktop/tdesktop#1685]
Noticed that copy and pasting code often causes nightmares for the recipient.

If a line includes double characters of any sort in the middle of two pieces of text it mashes them together

Example:
2 x Less Than Sign (&#60;) becomes Double Left Pointing Angle (&#171;)
2 x Hyphen becomes Em Dash

See here:
```
test -- this
```
becomes 
```
test — this
```

and

```
test << this >>
```
becomes 
```
test « this »
```
If the characters are on the start of the line, it doesn't occur.

This makes it super annoying for coders.
Yeah, I know I could use Slack like the cool kids (I do like Slack)... alas, I enjoy Telegram.

**Comment by telegramdesktop** [comment]
@timkrins You can use triple-backtick wrap for code parts, it won't have those replaces and will use a mono space font. ```like that```

**Comment by timkrins** [comment]
Oh interesting. Cheers for that.

Any chance of a "paste as code" right-click option if the clipboard
contains code-like characters?

**Comment by telegramdesktop** [comment]
@timkrins And what is "code-like characters"?

**Comment by timkrins** [comment]
Oof... Asking the hard questions... I like you Telegram.

Maybe just detecting pasting characters that are going to be mashed
together by the string replacement function?

Short of some crazy heuristic algorithm then I'm not sure ;)

**Comment by pschichtel** [comment]
I think the manual wrapping in ``` is fine, however I'm wondering why the replacement is there in the first place? I think it's the only official client that does it and I don't see where it adds any value.

**Comment by auchri** [comment]
Duplcate #522

**Comment by shadowlmd** [comment]
And how do I paste text containing ``` characters without Telegram treating them specially?

**Comment by AndydeCleyre** [comment]
@shadowlmd is crucially on point here. This makes impossible a simple behavior that many users want -- send the text we type, not what a developer prefers that the stranger types.
