### ISSUE TITLE
App doesn't display messages as highlighted when selecting messages in comment section

### ISSUE THREAD

**Issue by mrcentimetre** [telegramdesktop/tdesktop#16857]
### Steps to reproduce
1. just open a comment section and select any message or messages.

### Expected behaviour
Display messages as highlighted when selecting it

### Actual behaviour
We can see forward, delete buttons in the top (Delete, if you're admin in that group) but it doesn't display messages as highlighted.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.9.5 beta x64

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Classic, Night

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by hookzof** [comment]
Fixed (2.9.14 beta)
