### ISSUE TITLE
Paste is erratic and sometimes broken in Fedora 34 (Wayland)

### ISSUE THREAD

**Issue by scaramouche88** [telegramdesktop/tdesktop#16852]
### Steps to reproduce
1. Run Telegram on a standard Wayland session
2. Copy text outside Telegram (e.g. an url from Firefox or plain text)
3. Paste via crlt+V or right click+Paste

### Expected behaviour
It should paste all the times

### Actual behaviour
Most of the times Telegram freezes for 2 sec and it pastes nothing

### Configuration
**Operating system:** Fedora 34

**Version of Telegram Desktop:** 2.8.8

**Installation source (Linux Only)** rpm from fedora app shop

**Used theme**: dark

I realize this might be already solved, but I have not found any solution in the issues. Very sorry is this issue is redundant.
The point that confuses me is that such behaviour is erratic: most of the times it does not work but sometimes yes and I have not found if there is any particular correlation (if it is an url, plain text or if it depends on the software from which I copy, etc...)

I see that for example in issue [https://github.com/telegramdesktop/tdesktop/issues/9921](url) you advice to avoid snaps etc and to use the tar version: does this apply also for the RPM version?

**Comment by ilya-fedin** [comment]
I think it's some unreported Qt bug, tdesktop uses high-level [QClipboard](https://doc.qt.io/qt-5/qclipboard.html) API. The Qt bug mentioned in #9921 was fixed in 5.13 and is related to handling hotkeys with non-English layouts by Qt rather than clipboard, so if your distro doesn't use old Qt (actual one is 5.15), it couldn't be the same bug.

I don't know how to help you though, I don't know how to debug Wayland.

**Comment by ilya-fedin** [comment]
maybe it's an XWayland bridge bug?

**Comment by scaramouche88** [comment]
According to a check with dnf, Qt5 is at version 5.15.2.
(Btw, I have indeed a non-English layout, but I switch between En, Fr and It, so no particular character.)

Would it help to reinstall from tar instead of rpm?

**Comment by ilya-fedin** [comment]
> Would it help to reinstall from tar instead of rpm?

You mean official binary? Well, you can try. The most obvious diffference is that Fedora patches Qt to run on GNOME Wayland, while upstream Qt blacklists it due to incompatibilities. So official binary will run via XWayland if you're using GNOME.

**Comment by ilya-fedin** [comment]
Looks like the discussion is hanged without any conclusion... Could the issue be closed?

**Comment by scaramouche88** [comment]
Sorry for the late answer.
I'm trying with the binary since a few days now without issues. Since the problem is erratic, I will re-open if the problem persist.
Thanks!
