### ISSUE TITLE
[Feature Request] Downgrade from beta to stable version

### ISSUE THREAD

**Issue by hookzof** [telegramdesktop/tdesktop#16851]
Add the ability to downgrade from beta to stable version by unchecking the "Install beta versions" checkbox.

**Comment by john-preston** [comment]
@hookzof If you uncheck it, you won't be updated to beta versions anymore and will stay on stable versions after the next stable version is released.

**Comment by hookzof** [comment]
@john-preston Yes, but I stay on the unstable beta and have to download the stable version from the website (which isn't exactly convenient).

**Comment by john-preston** [comment]
@hookzof You'll be autoupdated to the stable version automatically when it'll be out.

**Comment by hookzof** [comment]
@john-preston I'm talking about a forced upgrade to the latest stable version rather than a future one.

**Comment by Aokromes** [comment]
every application i know on the world doesn't allows downgrade without reinstall.

**Comment by hookzof** [comment]
@Aokromes There are many solutions to how to implement this, I didn't say "let's do it without reinstalling". I'll close this issue for now, but hopefully we'll get back to it later.
