### ISSUE TITLE
Grouping of chats

### ISSUE THREAD

**Issue by sprrw** [telegramdesktop/tdesktop#1686]
It's an enhancement request. It would be very nice to reduce the clutter and allow the ability to group chats, for example, "Work", "Ingress local", "Bots", etc. It needs to be implemented on a client with a possibility to save groups organization on the cloud.
Such grouping may allow other possibilities, such as notifications default change for all groups at once, changing the order of groups based on the priorities and such.

**Comment by auchri** [comment]
#1107
