### ISSUE TITLE
[Feature Request]  Timer for messages

### ISSUE THREAD

**Issue by perevertysh** [telegramdesktop/tdesktop#16866]
### Is your feature request related to a problem?
Sometimes you need make some notifications about evant or info topic

### Describe the solution you'd like
There is a solution for that case: add possibility for turn on timer in message sending.

**Comment by RememberTheAir** [comment]
The description of your request is not very clear, but it looks like something that should be supported by the server too, so this suggestion belongs to https://suggestions.telegram.org
