### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by lacostya86** [telegramdesktop/tdesktop#16865]
Please, make emoji icon in dialogs hiddenable. IT IS VERY ANNOYING each time you move mouse above emoji-icon and all emojis pop-up and close visible area for text. Terrible, please hide it!

**Comment by lacostya86** [comment]
or let user move this button according as he prefers: at the each corner of dialog window. There are no problems with mic and attachment buttons because they don't have `onmouse-hover`-like event... Thanks! :)

**Comment by antonkomarev** [comment]
I think it might be solved by adding config option to make it auto-expandable on hover or on click only.

**Comment by yggr890** [comment]
Yeah! This would be a great feature!

**Comment by Eric-01** [comment]
A much easier workaround would be to make the emoji popup appear only when a user hovers over the button for a short period of time (now it is instant).

**Comment by ilya-fedin** [comment]
#6783
