### ISSUE TITLE
Downloading to NFS shares is slow

### ISSUE THREAD

**Issue by 35609902357** [telegramdesktop/tdesktop#16862]
### Steps to reproduce
1. Mount a folder via NFS
2. Set the mounted folder as destination for downloads
3. Download a file directly to the NFS share

### Expected behaviour
Downloads on NFS should be as fast as any transfer to NFS

### Actual behaviour
Downloading a file to the home directory is fast as expected, but the download speed is significantly reduced when downloading to NFS shares. The speed drop looks exactly as if the `sync` mount option were used (even if the share is mounted with the `async` option). Does the application do something to override the mount options and use synchronous writes?

### Configuration
**Operating system:** Linux

**Version of Telegram Desktop:** 2.9.3

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Flatpak

**Comment by vitlav** [comment]
Try run telegram-desktop via eatmydata (it disables fsync for a program) to check if there is sync in the code.

**Comment by 35609902357** [comment]
I have no idea how to do it. But I tried different operating systems and it does the same everywhere

**Comment by 35609902357** [comment]
@vitlav Do you use the Flatpak version?

**Comment by 35609902357** [comment]
@vitlav I tried other Flatpaks and they can write to NFS just fine apparently, Telegram seems to be the only one having issues (it has no issue when writing to local storage)

**Comment by m3thm4th** [comment]
@35609902357 I can confirm this bug exists on the official binary version. Not a Flatpak thing.
@vitlav can you share your working mount options for the server and the client?

**Comment by vitlav** [comment]
> @35609902357 I can confirm this bug exists on the official binary version. Not a Flatpak thing.
> @vitlav can you share your working mount options for the server and the client?
```
$ grep /home /etc/fstab
homeserver:/home /home nfs rw,soft,intr,sec=sys,timeo=55,_netdev 0 0
```
I wonder what the mounting options for the server mean.

**Comment by m3thm4th** [comment]
I meant the options in /etc/exports. Anyway I tried your options (except for intr which is deprecated), and the problem persists. I don't know if the reason why it works normally for you is you have it mounted as /home instead of an external storage. Another possible difference is I force NFSv4 and disabled 2 and 3.
