### ISSUE TITLE
[Question] Revoke hidden history for **existing** members

### ISSUE THREAD

**Issue by pcko1** [telegramdesktop/tdesktop#16864]
Is there a way to revoke hidden history for existing members?

Right now, if a new member joins while hidden history is turned ON, there is no way to re-enable it back for them (for example after they have solved a captcha). Strangely, if those members are kicked out, hidden history gets disabled and they rejoin, they **still** cannot see the historical messages.

**Comment by RememberTheAir** [comment]
There is no way to make that chunk of history visible to these users. You should fill a request to https://suggestions.telegram.org
