### ISSUE TITLE
Not all archived chats are listed 

### ISSUE THREAD

**Issue by smirnov-i-SPbAU** [telegramdesktop/tdesktop#16875]
### Steps to reproduce
1. Go to archived chats 
2.  See list of archived chats or number of unread messages

### Expected behaviour
All archived chats should be presented

### Actual behaviour
I can't see 14 of my 34 archived chats. And messages from them are not included to unread counter too. I can see this chats and unread messages in mobile app.
Maybe important, that all 14 unseen chats are marked as unread (left 20 marked as unread too)

### Configuration
Operating system:  Ubuntu 20.04.3 LTS

Version of Telegram Desktop: 3.0 (same for 2.1.7)

Installation source: snap latest/stable

**Comment by enchained** [comment]
Same with Unread folder for me. 
**tdesktop for windows v3.0.0:**
**3** unread channels + 1 muted chat with a mention

**telegram iOS 8.0 (21836):**
**6** unread channels + 1 muted chat with a mention

Settings of the folder:
![image](https://user-images.githubusercontent.com/6181674/131663343-8897d12b-447c-47cb-b374-786666001652.png)

**Comment by john-preston** [comment]
I hope it was the problem that was fixed from the server side earlier today. Please check if it is fine after an app restart right now.

**Comment by john-preston** [comment]
@smirnov-i-SPbAU @enchained

**Comment by smirnov-i-SPbAU** [comment]
> I hope it was the problem that was fixed from the server side earlier today. Please check if it is fine after an app restart right now.

Yep, everything is fine now. Thanks
