### ISSUE TITLE
snap error package under fedora

### ISSUE THREAD

**Issue by boistordu** [telegramdesktop/tdesktop#16879]
### Steps to reproduce
nothing specific just a refreshing of the snap and that's it.
`sudo snap refresh `

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead
`- Mount snap "telegram-desktop" (3036) (snap is unusable due to missing files; contact developer)`

### Configuration
**Operating system:**
fedora 34
**Version of Telegram Desktop:**
snap version 3.0
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
steps to reproduce? expected behaviour?

**Comment by boistordu** [comment]
well expected behaviour that's of course that the install goes trough, I don't even see why I need to mention this.

**Comment by boistordu** [comment]
It's happening on every host and every VM I have under fedora. Are you sure your fedora is up to date?

**Comment by boistordu** [comment]
It should be clear that I m not talking about ubuntu or other distros here but just fedora. The snap packages under ubuntu or Debian are working fine for example. 
It's only under fedora

**Comment by boistordu** [comment]
There is a bug between snapd and unsquashfs. 
You've didn't test with fedora 34 up to date apparently. 

https://forum.snapcraft.io/t/cannot-install-snap-file-snap-is-unusable-due-to-missing-files/25719
