### ISSUE TITLE
Image viewer doesn't properly handle multi-monitor 

### ISSUE THREAD

**Issue by 3v1n0** [telegramdesktop/tdesktop#1687]
The embedded full-screen image viewer should always be shown in the monitor where the parent window is.

Also, it happens to me that when I detach my main monitor (which is the left-most, and primary in general) from the laptop, then I need to restart the telegram app in order to be able to open the viewer, because otherwise it tries to be shown in the old monitor, which isn't there anymore.

**Comment by Arcaena** [comment]
What OS is this happening to you on? It works fine for me on Windows and Arch Linux.

**Comment by 3v1n0** [comment]
This is what happens in Ubuntu (with unity), but this is something all related to the app, it shouldn't have anything to do with the DE.

**Comment by Aokromes** [comment]
This bug is still valid? changes to image viewer where added months ago @auchri
