### ISSUE TITLE
v3.0.0 Windows x64 Installer installiert sich nicht

### ISSUE THREAD

**Issue by Elias481** [telegramdesktop/tdesktop#16871]
### Steps to reproduce
1. Download tsetup-x64.3.0.0.exe
2. Execute
3. Read Error-Message: The setup files are corrupted. Please obtain a new copy of the
program.

### Expected behaviour
Installation succeeds.

### Actual behaviour
Installation of that version not funtioning (v2.9.5.beta works)

### Configuration
**Operating system:** Windows 11, current Dev Channel Version

**Version of Telegram Desktop:**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Modelmat** [comment]
Seems like updating from the v2.9.5 beta works, just not installing directly the v3.0 file.

**Comment by john-preston** [comment]
Thanks! Does the portable work? I'm updating the installer both in GitHub release and on the site right now.

**Comment by john-preston** [comment]
The version on the GitHub releases page should be fine as well now.

**Comment by john-preston** [comment]
Should be fine now.

**Comment by Elias481** [comment]
Thanks, yes, works, and the portable also made the proof.
Will see whether it sufficiently helps to stop the root-cause of messenging issue today.
Installation is to be finished, urgently.
