### ISSUE TITLE
Changing chat wallpaper after application update

### ISSUE THREAD

**Issue by anton-marchenko** [telegramdesktop/tdesktop#16874]
### Description
Thank you a lot for changing my chats wallpaper choice to yours after an application updating! Because I have so much free time and I am ready to spend it for restore my wallpaper preferences in your beautiful application! (it was sarcasm, of course :D )

It happens 2 times. And I wouldn't want it be in 3rd time! 

**For application users**:
Please vote for this message if you also think that this bug (or feature? ;) ) is too annoyed.

**For application developer team**:
I understand that you want to show for us how your wallpaper designer can make his/her job. But it would be better to write about new wallpapers in release notes without any autocratic overwriting user preferences. ;)

### Actual behaviour
New chat wallpaper overwrite user wallpaper after application updating (if some new wallpapers appears in wallpaper gallery)

### Expected behaviour
User wallpaper preferences have not be changed by  application update

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
3.0 and previous

**Used theme**:
Classic

![image](https://user-images.githubusercontent.com/45929621/131634206-f0c87a08-db4c-4b24-b7de-4643227168aa.png)

### Reproducing

I had this wallpaper:

![image](https://user-images.githubusercontent.com/45929621/131631816-c9e54839-c25c-4ed6-b3e6-8eaa9663eca4.png)

After updating the application my wallpaper has been changed to this:

![image](https://user-images.githubusercontent.com/45929621/131631996-6a38c2cd-5330-4da7-a0ca-f8122107ef7b.png)

I changed wallpaper according to my own preferences but after application updating to version 3.0 my wallpaper has been changed again! To this:

![image](https://user-images.githubusercontent.com/45929621/131632212-2cddf684-c5c4-4098-b1ab-4e3963b34899.png)

**Comment by kleuter** [comment]
Same here.

**Comment by john-preston** [comment]
@anton-marchenko Yeah, this was an old (really old) default wallpaper, so it was changed to the new default one. Sorry. Non-default wallpapers were not changed.

If the default wallpaper will be changed again I'll try to limit the change only to current default one, not old defaults as well.

**Comment by anton-marchenko** [comment]
@john-preston Thank you for feedback! I`ll add more information for avoid misunderstanding:

When I installed Telegram Desktop I set this wallpaper explicitly:
![image](https://user-images.githubusercontent.com/45929621/131642195-ed2cd852-a964-4e58-b15f-f90cab57ac8d.png)

Because when I started to use Telegram Desktop default wallpaper was with flowers one:
![image](https://user-images.githubusercontent.com/45929621/131642604-eb2635d3-4724-4108-9d2b-bdd89a74a417.png)

Therefore the wallpaper that I talking about was not default application wallpaper at that time but the wallpaper that I chose as user. And this wallpaper have been overwritten after application update.

**Comment by john-preston** [comment]
@anton-marchenko I see. The one you've chosen was default some time before that, and now all old defaults are replaced. I'll try to tune that the next time the default wallpaper will be changed.

**Comment by anton-marchenko** [comment]
> @anton-marchenko I see. The one you've chosen was default some time before that, and now all old defaults are replaced. I'll try to tune that the next time the default wallpaper will be changed.

@john-preston Okay. What do you mean by "tune"? Does it mean you will fix it? And user choice of default wallpaper will be stored after new default wallpaper appears?

**Comment by john-preston** [comment]
@anton-marchenko I think that in case of a new default wallpaper for versions >= 3.0 only the current default one will be automatically switched to the new one.
