### ISSUE TITLE
[Question] how to make a bridage for other applications sync

### ISSUE THREAD

**Issue by alirayaneh** [telegramdesktop/tdesktop#16877]
I want to build a bridge between TDesktop and other software. 
For example, create a tcp port.
Commands and information can be exchanged through this port. For example, the ability to read the content of a chat through the chat ID
It is also possible to join a chat via chat ID. Or the possibility of creating a verification system such as verification via SMS

But the question is, I need some guidance to do this. Where to start?

**Comment by RememberTheAir** [comment]
It looks like you're looking for something such as tdlib: https://github.com/tdlib/td

**Comment by alirayaneh** [comment]
thanx for replay . i  know there exist many library and alot of way is for telegram cli . 
But I intend to offer it to my users as a professional option on tdesktop.

**Comment by alirayaneh** [comment]
> 
> 
> maybe one bot is the way you are looking to go.
> 
> https://i.imgur.com/G1kg26k.png

Yes, this is a method, but it can not be offered on desktop telegram as an attractive advantage.
I'm going to develop a fork from T Desktop to implement attractive and professional options. Including ideas that have not been implemented in the current version or will never be implemented.
