### ISSUE TITLE
Error When We join vc in any group

### ISSUE THREAD

**Issue by Achu2234** [telegramdesktop/tdesktop#16870]
![image](https://user-images.githubusercontent.com/75154223/131531936-5750375d-92cd-4cde-914e-de0257f3b18f.png)

Here you can see only 3 people there in vc but its show 100o peple in vc and not showing sharing screen

**Comment by Aokromes** [comment]
don't delete template, fill OS, telegram version, anything can help.
if the template fails to be restored on 24h i will close the issue.

**Comment by Achu2234** [comment]
@Aokromes Now Its ok Thanks
