### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by SMSourov** [telegramdesktop/tdesktop#16888]
### Is your feature request related to a problem?
Allow user to choose font and font size #90

### Describe the solution you'd like
Having the ability to change the font size of the displayed font. Also, having the ability to change the font.

### Extra information
There is a workaround. As like it solves the problem, it also creates some problem. I can go to settings and change the default interface scale. Though this increases the default interface scale, it increases the size of everything else with it. Due to this, Telegram desktop looks annoying.

### Describe alternatives you've considered
I couldn't think of any alternative solution.

**Comment by ilya-fedin** [comment]
Do you understand that duplicate issues are just being closed?

**Comment by SMSourov** [comment]
Ok! But the issue is about 7 years old. Why there isn't any solution?
On Android, I can solve this issue very easily. But on Windows, there is no solution at all. I chat with my friend in Bengali. It is a bit hard for me to read texts in my PC due to the font size being smaller than it should be.

**Comment by ilya-fedin** [comment]
> Ok! But the issue is about 7 years old. Why there isn't any solution?

The fact feature request exists doesn't mean it will be ever implemented.

**Comment by SMSourov** [comment]
I hope that the feature will be implemented soon.

**Comment by ilya-fedin** [comment]
No, AFAIK there's no plan to give the ability to change fonts

**Comment by SMSourov** [comment]
:(

**Comment by ilya-fedin** [comment]
> I chat with my friend in Bengali. It is a bit hard for me to read texts in my PC due to the font size being smaller than it should be.

Are you sure there's no way to address this without adding an option? Adding an option is a major blocker for any feature request in tdesktop.

**Comment by SMSourov** [comment]
By "address this" if you mean "solving the problem" then, yes, there is no way to solve this without adding an option.
I've checked every setting to find the solution and I haven't found any solution.
I've googled for the solution. I've only found the way to change the font(by editing the registry) but not the font size.

**Comment by ilya-fedin** [comment]
AFAIK, Qt has a stupid mechanism of choosing fonts on Windows in alphabetical order, so maybe it doesn't choose the font right? Check the font in tdesktop and in other applications, maybe the font is wrong and we can patch Qt to get the right font.

**Comment by SMSourov** [comment]
The font may not be a big issue because it has a solution. I use Noto Sans Bengali. The app uses the system font which is not a big problem for me. But my main problem is the font size.
