### ISSUE TITLE
Black Image Showing on every image

### ISSUE THREAD

**Issue by animeshxd** [telegramdesktop/tdesktop#16889]
### Steps to reproduce
1. Find Any Photo
2. Click on photo
3. No Photo Showing 

### Expected behaviour
Display the photo

### Actual behaviour
no photo is showing, black image
![image](https://user-images.githubusercontent.com/47624427/131951158-80a8c274-5e90-4d26-bc84-f0813c73498c.png)

### Configuration
**Operating system:** Win10 21H (OSBUILD 19044, 1202)

**Version of Telegram Desktop:** 3.0.1 x64

**Installation source**: `ms-windows-store://pdp/?ProductId=9nztwsqntd0s`

**Used theme**: Classic

**Additional**: Tried Reinstall, save issue
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary) (can't find log)
</details>

**Comment by Aokromes** [comment]
what's your gfx card and model? nvidia geforce gtx 2060, amd rx 5600, intel?

**Comment by animeshxd** [comment]
> what's your gfx card and model? nvidia geforce gtx 2060, amd rx 5600, intel?

Ryzen 5 3400G CPU WITH VEGA 11 GPU

**Comment by Aokromes** [comment]
try updating video drivers https://www.guru3d.com/files-details/amd-radeon-adrenalin-21-8-2-driver-download.html
not sure if it will work.

**Comment by animeshxd** [comment]
> try updating video drivers https://www.guru3d.com/files-details/amd-radeon-adrenalin-21-8-2-driver-download.html
> not sure if it will work.

Ok I will inform after installing new driver

**Comment by animeshxd** [comment]
Worked
