### ISSUE TITLE
apparmor="DENIED" snap/telegram-desktop/***/.local/share/TelegramDesktop/tdata

### ISSUE THREAD

**Issue by AndreyKravchina** [telegramdesktop/tdesktop#16887]
### Steps to reproduce
1. install Telegram Desktop from snap
2. open system log
3. ... error appears

### Expected behaviour
no errors from apparmor

### Actual behaviour
message in log:
```
Sep 02 13:03:41 **** kernel: audit: type=1400 audit(1630577021.220:116): apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/home/****/snap/telegram-desktop/***/.local/share/TelegramDesktop/tdata/*****/#****" pid=1522 comm="telegram-deskto" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
```

### Configuration
**Operating system:**
Debian GNU/Linux 11 (bullseye)

**Version of Telegram Desktop:**
3.0.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
snap

**Used theme**:
default

<details><summary><b>Logs</b>:</summary>
Sep 02 13:03:41 **** kernel: audit: type=1400 audit(1630577021.220:116): apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/home/****/snap/telegram-desktop/***/.local/share/TelegramDesktop/tdata/*****/#****" pid=1522 comm="telegram-deskto" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
</details>

**Comment by AndreyKravchina** [comment]
dirty fix:

add to 
`/var/lib/snapd/apparmor/profiles/snap.telegram-desktop.telegram-desktop`

line:
```
profile "snap.telegram-desktop.telegram-desktop" (attach_disconnected,mediate_deleted) {
...
  owner @{HOME}/snap/telegram-desktop/** rw,
...
```

**Comment by ilya-fedin** [comment]
What do you expect by creating an issue? snapd doesn't allow applications to change apparmor profiles.

**Comment by AndreyKravchina** [comment]
> What do you expect by creating an issue? snapd doesn't allow applications to change apparmor profiles.

File `/var/lib/snapd/apparmor/profiles/snap.telegram-desktop.telegram-desktop` already was created by snap or while snap was installed. I have just add one line to fix errors.

I suggest that snap can be modified to fix this trouble

**Comment by ilya-fedin** [comment]
This file is not a part of snap package, it's generated by snapd on the fly. Snap package has no access to apparmor profiles.
