### ISSUE TITLE
Calls crash with Linux kernel options: pci=assign-busses pci=realloc <or> pci=assign-busses pci_pt_e820_access=on

### ISSUE THREAD

**Issue by itoffshore** [telegramdesktop/tdesktop#16881]
### Steps to reproduce
1. Boot with kernel options `pci=assign-busses pci=realloc` or `pci=assign-busses pci_pt_e820_access=on`
2. (this is a workaround for a [BIOS `sr-iov` bug](https://access.redhat.com/solutions/37376))

### Expected behaviour
Make or receive a phone call should work

### Actual behaviour
Make or receive a phone call gives the following error just after '**exchanging keys**':
```
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
```
& the call window crashes / closes (the main Telegram window is unaffected)

### Configuration
**Operating system:**

Arch Linux

**Version of Telegram Desktop:**
`2.8` & `2.9`

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
* distribution package
* snap
* flatpak

(all 3 types have the same error)

**Used theme**:
* dark

This has only started to be a problem recently - most probably related to AMD Ryzen BIOS becoming bigger with the addition of support for the 59xxx series of CPU's (& therefore requiring the [workaround](https://access.redhat.com/solutions/37376) for `sr-iov` to work)

This bug is possibly related to [this issue](https://github.com/telegramdesktop/tdesktop/issues/9984)

**Comment by Aokromes** [comment]
try updating to 3.0.1

**Comment by itoffshore** [comment]
Same issue on `3.0.1` - booting without the kernel options & without `sr-iov` vf's enabled - makes telegram calls work again.

**Comment by ilya-fedin** [comment]
Apparently, these options conflict with the library Telegram uses for calls and you should remove them if you want to use calls.

**Comment by itoffshore** [comment]
I'm investigating the BIOS bug with Gigabyte - for reference it's a bug on the `X570 Aorus Pro` motherboard.
