### ISSUE TITLE
Add shortcut to start and stop/send voice messages in desktop

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1688]
This feature will help improve the functioning of recording voice messages in TDesktop.

Proposal:
⁍ Ctrl + R to start recording
⁍ Ctrl + R to stop and send recording
⁍ Ctrl + shift (⇧) + R cancel recording

Recently, voice messages were improved in the Telegram mobile platform, this proposal would help improve the use of voice messages on the desktop.

Cheers

**Comment by auchri** [comment]
Added to #1060

**Comment by DaFri-Nochiterov** [comment]
-1
I suggest this: 
* Hold Ctrl + Space to record message
* Press Shift to Cancel recording

**Comment by diazbastian** [comment]
@DaFri-Nochiterov The advantage of a desktop is multitasking. It is very uncomfortable hold a key to perform this task, and not much different with the current behavior (press and hold a virtual button with a pointing device).

My proposal aims to have the same freedom to raise-to-speak in a mobile device. Although there may be a configuration which allows both modes.

Moreover, the keyboard shortcut (ctrl + space) is widely used in different systems, for example ibus in gnu / linux.

**Comment by telegramdesktop** [comment]
@diazbastian Ctrl+Space is bad (spotlight in os x, something else in linux etc), I'm not sure about Ctrl+R as well (like it should refresh something :)

**Comment by DaFri-Nochiterov** [comment]
Alt+Space :laughing:
