### ISSUE TITLE
Unable to mark messages as read while uploading video

### ISSUE THREAD

**Issue by eiglow** [telegramdesktop/tdesktop#16885]
### Steps to reproduce
1. Have a chat with unread messages
2. Start uploading a video in another chat
3. Switch to the chat with unread messages

### Expected behaviour
The messages should be marked as read

### Actual behaviour
The messages are not marked as read, the badge indicator on the left pane stays the same instead of clearing.

One workaround for this is to minimise and restore the window, that then clears the badge while the video is still uploading.

### Configuration
**Operating system:** Fedora 34 (KDE Spin - Wayland session)

**Version of Telegram Desktop:** 2.9.3

**Installation source:** Flatpak (Flathub)

**Used theme**: Default night mode

Let me know if you can't reproduce and I'll try to give more detailed reproduction steps.

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org
