### ISSUE TITLE
Telegram desktop was update notification incorrectly show as unread message

### ISSUE THREAD

**Issue by wparad** [telegramdesktop/tdesktop#16891]
### Steps to reproduce
1. Instead desktop client through snap on linux
2. Wait for Telegram to self update
3. See message "Telegram Desktop was updated to version 3.0.1"
4. Look to say there is a hovering `1` on the Telegram icon.

### Expected behaviour
Telegram indicator should not show an unread message from telegram when telegram self updates.

### Actual behaviour
Telegram tells me on all 5 of my devices that it has updated itself everytime. If this was more less frequent it wouldn't be a problem. But since this happens so many times, it is quite disruptive.

At least there should be ability to display getting these messages at all, but realistically I should be able to get this information, but it should be present in the User self tab and not as a message sent from telegram.

### Configuration
**Operating system:** Linux

**Version of Telegram Desktop:** 3.0.X

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Snap

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by wparad** [comment]
I am using the official version through snap, I don't understand how downloading it again will change anything.

**Comment by Aokromes** [comment]
> I am using the official version through snap, I don't understand how downloading it again will change anything.

some people reported snap bugs not present on webpage package.

**Comment by wparad** [comment]
This isn't a snap related bug.

**Comment by Aokromes** [comment]
> This isn't a snap related bug.

i said because 2d ago i closed a ticket with same bug with flakpak.

**Comment by wparad** [comment]
Can you link to the source code that was changed to stop showing telegram self-updates as unread notifications?
