### ISSUE TITLE
Bug #10512 came back! Unexpected window drag while typing and by the mouse move on Linux Mint 20.2, Cinnamon

### ISSUE THREAD

**Issue by Wohlstand** [telegramdesktop/tdesktop#16892]
This is the same issue as #10512, it came back!

## Steps to reproduce

- Keep Telegram window open
- Type anything in any application, type messages in Telegram itself
- Move the mouse around and type anything, move the mouse over Telegram window keeping held no buttons

## Expected behaviour

Telegram stay not touched. The only way to drag and move the Telegram window is to drag the title bar or hold the ALT key together with a mouse button to drag the window at any of its positions.

## Actual behaviour

In a random and sudden moment, the Telegram window gets to be dragged with no keyboard keys held, and no mouse buttons pressed or held. That happens randomly and it's hard to catch. But, happens often and annoying. While typing the message in the Telegram itself, the cursor gets suddenly turned into the "dragging in process" that prevents me to type the message. Then, the mouse move does move the window itself.

This mess got introduced after 2.6.0 or 2.6.1 (don't remind).

The keyboard and mouse replacement didn't help.

### Operating system:
Linux Mint 20.1, Cinnamon

### Version of Telegram Desktop:
3.0.1

### Installation source (Linux Only) - the official website / GitHub releases / flatpak / snap / distribution package:
The ISO image downloaded from the official site https://www.linuxmint.com/edition.php?id=284
All mainstream updates were installed by apt update / apt upgrade.
Using Russian locale, having to set up Russian and Polish layouts (the Polish layout is used instead of well-known English as I do learn and type Polish, and as my Polish friend tells, the Polish layout is used for both English and Polish, the ALT key is used to get access to Polish-specific characters such as "łćóśęą").

The installation of Telegram itself, the first time I downloaded it by the Github Releases (Linux 64 binary tar.gz archive), then, the update gets came by the Telegram itself, I just hit the "Обновить Telegram" to cause it to restart and run the updated version.

**Comment by ilya-fedin** [comment]
#10348

**Comment by Wohlstand** [comment]
Yeah, the bug is similar, thanks @ilya-fedin
