### ISSUE TITLE
[Question] About metadata exposure

### ISSUE THREAD

**Issue by asakura42** [telegramdesktop/tdesktop#16896]
It is important to me as a modern paranoid to keep the amount of metadata that is passed to the network to a minimum. I understand that some data may be needed for correct functionality or even some anonymous analytics (despite my bad attitude towards this, the logic of such is quite understandable). But why would Telegram Desktop sends to servers my desktop environment, kernel version or glibc version? I don't want to pass this information to TG servers but I see it in the "Current session" tab. 

I suppose this would sound like too much concern, but I believe that if Telegram Desktop is processing such unimportant information, it may well be affecting more personal information. Of course, I am not going to parse a huge number of lines of code to figure out what metadata TG Desktop transmits. So I ask: how to minimize the transmission of metadata (e.g. how to hide my DE and kernel version)? And: what metadata does telegram-desktop send to servers?

**Comment by john-preston** [comment]
@asakura42 For Linux it was originally a way to measure how many users I'll cut off if I autoupdate the binary to a version built with a newer version of glibc. On all other platforms it is easy, you just know the system version number and when the amount of users on older one becomes less than some small amount you allow yourself to drop that version. But on Linux I was thinking about glibc version as the thing that'll cut the support.

Right now there are no switches to tune the information shown in Active Sessions. It was chosen mostly for the nice looking sessions list, something similar to mobile apps.
