### ISSUE TITLE
Forwarding messages from a greater timespan crashes TDesktop

### ISSUE THREAD

**Issue by Brawl345** [telegramdesktop/tdesktop#169]
If you are in a group for example and search for messages and select messages from the past (e.g. one from 17th august, one from 20th july, etc. up to 3 messages I think) and forward them, Telegram Desktop crashes. This is reproducible.
Tested on Ubuntu 14.04 64 bit and Windows 8.1 64 bit.

**Comment by auchri** [comment]
Is this still the case? If yes, reopen the issue
