### ISSUE TITLE
Livestream and user volume are not separate

### ISSUE THREAD

**Issue by NotGumballer91** [telegramdesktop/tdesktop#16907]
### Steps to reproduce

1. Start a livestream.
2. Right-click on the livestream and change the volume to anything.

### Expected behaviour

Livestream's volume should be changed.

### Actual behaviour

Both livestream and user's voice volume is changed.

### Operating system

Windows 10 pro 64-bit, 20H2

### Version of Telegram Desktop

3.0.1 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@NotGumballer91 Yeah, API has support only for one volume for a participant, for both his video streams :(

It could be done locally, but it's not easy to combine the synchronized server side volumes logic with some local overrides. I'm not sure it will be done before an API update for such case, but I guess we can leave an issue opened here.

You can ask for that feature being implemented in apps on all platforms with API support on https://bugs.telegram.org
