### ISSUE TITLE
[Question] KDE/Xfce. Use original telegram icon in tray instead system

### ISSUE THREAD

**Issue by snorlax212** [telegramdesktop/tdesktop#16901]
Hello. Can you help, how can i replace tray telegram icon of any KDE/Xfce icon theme (e.g. ![](https://i.imgur.com/fyTB5zh.png)) with original (![](https://i.imgur.com/DoaExMj.png))? Without manual filesystem modifying if possible.

**Comment by ilya-fedin** [comment]
You can remove the icon from the filesystem or change your icon theme.
