### ISSUE TITLE
lake of an emoji

### ISSUE THREAD

**Issue by ARMHMDZD** [telegramdesktop/tdesktop#16909]
Telegram desktop doesn't support this emoji : "🥲"
I am not familiar with programming so much but I liked to report this issue to fix it by help of someone who knows how this problem can be solved.
However, I know that this doesn't take so time to fix.

A picture of this emoji is here:
![Emoji photo](https://user-images.githubusercontent.com/86849461/132221900-65d0ac72-d75b-4bd3-9db0-63b8c8e7a0f8.jpg)

**Comment by john-preston** [comment]
@ARMHMDZD Unfortunately, it is not very easy / very fast to fix :( It requires gathering data and tweaking the software to rebuild sprites for all thousands emoji for all four used emoji sets. Some are built from color fonts that are rendered only on macOS, some only on Linux, some from .png sprites, where file-names-to-code-points mapping should be tweaked.

**Comment by ARMHMDZD** [comment]
@john-preston But the Android version of Telegram supports this emoji. How this process was done in this version?

**Comment by john-preston** [comment]
@ARMHMDZD Almost the way I've described. But Android version doesn't offer to choose which emoji set you use, so it did this thing only with one emoji set (that is read from font on macOS), not for four different ones of them.

**Comment by ARMHMDZD** [comment]
OK , thank u
