### ISSUE TITLE
[Feature Request] Introduce a delay when cursor passes over emoji button

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#16904]
### Is your feature request related to a problem?

The problem being that pop-up emoji window(?) interferes with other actions performed with the mouse, covering other elements of the interface. Examples: when typing messages, when sending files/photos; basically wherever that emoji button(?) exists it can and does interfere simply because a mouse cursor passes over it. Intentionally avoiding by zigzagging the mouse cursor around it is stupid and shouldn't have to be done.

### Describe the solution you'd like

Introduce a brief delay on emoji pop-up window, so that a cursor that just passes over it does not trigger it to..pop-up open.

### Describe alternatives you've considered

Intentionally avoiding the emoji button by zigzagging the mouse cursor around it is stupid and shouldn't have to be done.

### Additional context

I use Telegram mostly from my laptop, I use a mouse, and this is one of those small things that could significantly improve my own user experience. Anyhow, in my experience it's always been done with a slight unnoticeable delay, everywhere, the buttons of this type, with pop-up elements - a delay like that does not interfere with the speed of manipulations, it just prevents undesired elements from keeping popping-up and getting in the way.

**Comment by ilya-fedin** [comment]
#1333

**Comment by Eric-01** [comment]
+1 for this.

It could be a good solution to all of those many issues here on GitHub related to the emoji popup appearing instantly (which seems to be unexpected and unintuitive to a lot of people, including me). Easy to do and effective enough.

**Comment by Eric-01** [comment]
+1 for this.

It could be a good solution to all of those many issues here on GitHub related to the emoji popup appearing instantly (which seems to be unexpected and unintuitive to many people, including me). Easy to do and effective enough.
