### ISSUE TITLE
International (Austria) Telephone Number shown wrong

### ISSUE THREAD

**Issue by dominikpflegerl** [telegramdesktop/tdesktop#16908]
### Steps to reproduce

1. Open Telegram
2. Click on the top left menu icon
3. Topmost account details displaying the telephone number 

Also applies to the user profile page, under [Settings] -> [Edit profile]

### Expected behaviour

Telegram Desktop should show the Austrian international cellphone number with correct spacing, f.ex Austria:

+43 664 1234567
+43 676 12345678

Telegram Android does show the number correctly.

### Actual behaviour

Telegram Desktop shows the Austrian international cellphone number with wrong spacing:

Example #1 - +43 6 64123456 7
Example #2 - +43 6 76123456 78

### Operating system

Windows 11

### Version of Telegram Desktop

3.0.1 x64

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
> Other (unofficial) source

Which unofficial source you got tdesktop from? Why didn't you get tdesktop from official website?

**Comment by dominikpflegerl** [comment]
I use mainly Chocolatey, and installed Telegram Desktop months ago. Since then, it updates itself.

Nevertheless, just booted up my Windows 10 VM and installed Telegram Desktop from the official website, bug is also there.

**Comment by john-preston** [comment]
@dominikpflegerl It should be better now, but still with a redundant space at the end (+43 676 123456 78).

**Comment by john-preston** [comment]
Should be fixed in 3.0.2 beta (it'll be out later today).
