### ISSUE TITLE
Telegram Desktop crashes if OpenALSoft is set to "alsa" using PipeWire.

### ISSUE THREAD

**Issue by KynikossDragonn** [telegramdesktop/tdesktop#16900]
### Steps to reproduce
1. Set `~/.alsoftrc` "drivers" option to just "alsa".
2. Try to play any audio through Telegram.

### Expected behaviour
Audio plays back successfully under PipeWire ALSA plugin.

### Actual behaviour

Crashes with the following: (null pointer de-reference?)

```
[ogg @ 0x7fb59061d000] 727 bytes of comment header remain
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Segmentation fault

Telegram[12513]: segfault at 0 ip 0000000000000000 sp 00007fb5921fce98 error 14 in Telegram[400000+a0d000]
```

Does not crash if "drivers" is set back to "pulse" but this requires running a additional daemon under PipeWire to function as the PulseAudio server. Running OpenALSoft under "alsa" would not require running a additional server. OpenALSoft would need a additional PipeWire backend when things become stable though, so that PipeWire can be used directly without resorting to the ALSA plugin.

### Configuration
**Operating system:** Void Linux - Linux Kernel: 5.13.13

**Version of Telegram Desktop:** 3.0.1

**Installation source:** the official website

**Used theme**: System default

**Comment by ilya-fedin** [comment]
Provide crash report tag

**Comment by KynikossDragonn** [comment]
My crash report tag is: 9a1cc583-a9e3-4f2d-f409f7b6-4af6e24c

**Comment by ilya-fedin** [comment]
@john-preston sent this screenshot to me, looks like it crashes inside of pipewire's alsa plugin, I don't think it's possible to do something on tdesktop side
<img width="640" alt="изображение" src="https://user-images.githubusercontent.com/17829319/132121525-1860f213-f0ea-40d5-850a-a6d62e9838cd.png">

**Comment by KynikossDragonn** [comment]
I'll try investigating this on PipeWire's side, this probably could be a bug worth reporting about the pipewire-alsa plugin. For now, I'll keep `devices = pulse` for Telegram Desktop's case.
