### ISSUE TITLE
[Feature Request] Poll like Zalo

### ISSUE THREAD

**Issue by nguyenngocduy20** [telegramdesktop/tdesktop#16915]
### Is your feature request related to a problem?

No problem

### Describe the solution you'd like

The feature that enable users to create a poll within a group or channel

### Describe alternatives you've considered

The feature that enable users to create a poll within a group or channel

### Additional context

The feature that enable users to create a poll within a group or channel

**Comment by ilya-fedin** [comment]
polls already exist in telegram
