### ISSUE TITLE
[Feature Request] React on messages

### ISSUE THREAD

**Issue by nguyenngocduy20** [telegramdesktop/tdesktop#16914]
### Is your feature request related to a problem?

No problem

### Describe the solution you'd like

The feature that enable users to adding react to messages like Facebook Messenger.

### Describe alternatives you've considered

The feature that enable users to adding react to messages like Facebook Messenger.

### Additional context

The feature that enable users to adding react to messages like Facebook Messenger.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
