### ISSUE TITLE
Unpinned chat still visible at pinned position within unread folder

### ISSUE THREAD

**Issue by SiL3NC3** [telegramdesktop/tdesktop#16916]
### Steps to reproduce

Cannot be reproduced, because it was not occurring on other chats.
Only one specific chat is having this problem.
Also after completely deleting the chat, the problem re-occurs with a next new message from this particular user and it sticks back on unread folder at the top.

### Expected behaviour

Chat will be hidden in unread chats folder after unpinning it and it is read.

### Actual behaviour

Chat stays in unread chats folder even it is unread nor pinned.

### Operating system

Windows 10

### Version of Telegram Desktop

3.0.1

### Installation source

Static binary from official website

**Comment by adhamsulton** [comment]
I also noticed that, i think it is bug. It is possible delete chat only from folder settings.
