### ISSUE TITLE
[Feature Request] Ability to attach photos and music simultaneously to text posts/messages

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#16917]
### Is your feature request related to a problem?

I want to post/send my poetry with images and music attached to ONE MESSAGE, THE SAME MESSAGE. Why can't I do it?!

### Describe the solution you'd like

Let me do that. Do not separate it into separate messages, let it be one message.

### Describe alternatives you've considered

It has none.

### Additional context

Come on, every social media tool allows this. Catch up, please. I can't post on Telegram adequately otherwise.

**Comment by RememberTheAir** [comment]
> Come on, every social media tool allows this

Uh, namely? I'm not aware of any Telegram competitor that allows to do this (Discord, Skype, Slack, WhatApp, Messenger, Element, and so on)

Anyway, tdesktop doesn't allow you to do so because the API doesn't support such messages. You should bring this to https://suggestions.telegram.org
