### ISSUE TITLE
Bug af

### ISSUE THREAD

**Issue by svitbka** [telegramdesktop/tdesktop#16913]
### Steps to reproduce

After unsubscribing some telegram channels, I noticed that the channels from which I unsubscribed still remained in the folders(channels are not deleted from the folders to which I added them once).
![image](https://user-images.githubusercontent.com/49652587/132307274-45bf6ead-2906-464f-93f7-1f247f8cf192.png)
I have deleted these channels.

### Expected behaviour

When deleting channels, they should also be deleted from the folders to which you added them once.

### Actual behaviour

After deleting channels, they are not deleted from the folders.

### Operating system

windows 10 pro

### Version of Telegram Desktop

v 3.0.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
check if they are there on android too, if yes, maybe it's server side bug.
