### ISSUE TITLE
Differences in character limit in captions between TDesktop and Telegram for mobile devices

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1691]
TDesktop 0.9.27 dev
Telegram for Android 3.6.0 (751)

With the new ability to edit messages in channels and supergroups in new versions of Telegram it is possible to add caption to GIF's and Videos (files too, only TDesktop).

However, there is a difference in the character limit that can be added to files.
Tdesktop → 140 characters
Telegram Android → 200 characters

Apparently the limit is artificial and the best supported equate the number of characters (200).

Cheers

**Comment by auchri** [comment]
Fixed
