### ISSUE TITLE
Big cursor in GNOME Wayland

### ISSUE THREAD

**Issue by xscd** [telegramdesktop/tdesktop#16920]
### Steps to reproduce

1. Be on a GNOME Wayland session (e.g. Fedora Linux)
2. Install Telegram (https://telegram.org/dl/desktop/linux)
3. Run Telegram with ```QT_QPA_PLATFORM=wayland ./Telegram```

### Expected behaviour

The cursor size shouldn't change this wasn't happening before v 3.0.1 and v 3.0.0 updates. 

### Actual behaviour

The cursor size changes which makes it too big. 

https://user-images.githubusercontent.com/46658470/132483462-aebb2a25-4beb-4629-880e-cb245ce48921.mp4

### Operating system

Fedora Linux 35 (Workstation aka GNOME)

### Version of Telegram Desktop

v 3.0.1

### Installation source

Static binary from official website

### Logs

```shell
Don't have any logs. Tell me if I can do something to get logs for this.
```

**Comment by xscd** [comment]
As a workaround its possible to set ```XCURSOR_SIZE=24```. Related: https://bugreports.qt.io/browse/QTBUG-67579 

I see comments from @ilya-fedin I am really curious why this started happening now but didn't earlier. Did Telegram updated the QT version or something for v 3.0.0?

**Comment by ilya-fedin** [comment]
There was a hack as part of GTK integration, GTK integration is removed now. I don't think this hack is really needed, it's better to wait for a proper fix from Qt.

**Comment by xscd** [comment]
Agree. Its better to wait for a proper fix than relying on hacks. Could you share the link of the Qt issue?

**Comment by ilya-fedin** [comment]
You already posted it

**Comment by xscd** [comment]
Status seems closed on that one. Couldn't see a following issue there.

**Comment by ilya-fedin** [comment]
Yeah, they think there's no bug since there's no protocol for cursor configuration.

**Comment by xscd** [comment]
That makes sense too since ```xcursor-configuration``` isn't something yet?

**Comment by ilya-fedin** [comment]
It's basically Qt and GNOME can't agree on the way of configuring cursors on Wayland. Qt wants do that through Wayland, GNOME disagrees and blocks merging of the protocol, saying that D-Bus should be used. Qt, mpv and others gave up and just read environment variables. GNOME doesn't set these variables (KDE & sway do).

https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/21

Actual discussion of the protocol is in linked patchwork, AFAIU author gave up and doesn't want to continue developing of the protocol (as seen in the linked wlroots PR).

**Comment by ilya-fedin** [comment]
> That makes sense too since `xcursor-configuration` isn't something yet?

It's abandoned for 4 years in the fact, since 2018

**Comment by xscd** [comment]
Thank you for the information. One more question I have is why does this happens on Flatpak version of Telegram too? Doesn't the freedesktop platform set those variables too? Would it be any different if Telegram was based on KDE platform?

**Comment by ilya-fedin** [comment]
platform doesn't set anything lol, it's just a set of libraries

**Comment by xscd** [comment]
Oh okay, thanks.

**Comment by ilya-fedin** [comment]
> Would it be any different if Telegram was based on KDE platform?

Probably yes, they have some Fedora patches. But it's exactly the reason why it's not used, I don't like how Fedora patches make Wayland the default even though Qt is not really ready for Wayland.

**Comment by xscd** [comment]
I also try to use everything on Wayland (as can be seen lol) in Telegram case everything seems fine except these minor things. Which I will just pass another variable (```XCURSOR_SIZE=24```) from Flatseal. Thank you again for the detailed explanation. Not sure if this issue should stay open or be closed, your call.

**Comment by ilya-fedin** [comment]
When KDE runtime was used, people periodically created issues like "crash when opening menu", "menu is positioned wrongly", "big cursor", "bad window frame", "graphical artifacts", "random crashes", "various problems with text input", "various problems with clipboard". At some point I'm tired of these complains and unified snap & flatpak with self-built Qt that uses the same set of patches official binaries are using. So all official builds behave in one way.

**Comment by xscd** [comment]
I see, maybe things will get better with Qt 6? Don't know much about Telegram stack but are there plans for Qt 6?

**Comment by ilya-fedin** [comment]
No, Qt 6 doesn't solve any of current Wayland bugs :(. It's basically the same. Apparently because no one treat these bugs as bugs.

**Comment by ilya-fedin** [comment]
> Don't know much about Telegram stack but are there plans for Qt 6?

Not in near time, apparently. They dropped ANGLE support since they have RHI, but RHI is only for QML applications, so Telegram basically stuck with Qt 5...

**Comment by xscd** [comment]
Sad to hear :( Lets see what the future will bring us. Closing this issue for these reasons below:

1) Official ways to distribute Telegram don't encourage to use Wayland yet. 
2) The cursor issue only appears when you opt-in with ```QT_QPA_PLATFORM=wayland``` which isn't the default behavior.

If someone from the future reads this a workaround is to use the ```XCURSOR_SIZE``` variable e.g. ```XCURSOR_SIZE=24``` for default GNOME cursor size.
