### ISSUE TITLE
Hotkeys for watching videos

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#16929]
### Is your feature request related to a problem?

Well yes, there's no way to go back and forth on a video and that's not good for long videos.

### Describe the solution you'd like

We can create our own hotkeys or you just add them in like left arrow for 5 secs back or right arrow for 5 secs forward. 

Even shift left & right arrow would be fine.

Space bar for starting & stopping the video, etc.

### Describe alternatives you've considered

The mouse which doesn't work. There's no way to do that properly with such a small play bar.

**Comment by ilya-fedin** [comment]
#6606
