### ISSUE TITLE
[Feature Request] Automatic Reply when away.

### ISSUE THREAD

**Issue by romulofff** [telegramdesktop/tdesktop#16923]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

It would be nice to have an option to write a custom reply when away. Telegram is used a lot as a work tool and sometimes one is away from work, maybe having lunch, on the commute, or even on a day off. 

Therefore, it would be nice to have an option to write a custom message to be automatic sent to anyone that interacts with the user. There could be also an "away" button, to activate this automatic reply. I believe Gmail and Slack have options like these.

### Describe alternatives you've considered

I looked for bots to do that, however, bots can only be used inside groups, not on individual chats.

### Additional context

Example of this feature on Gmail.
![image](https://user-images.githubusercontent.com/20821190/132564511-ed2c89bf-893b-4f99-8272-22c375d8fad8.png)

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
