### ISSUE TITLE
Window drifts towards the top of the screen

### ISSUE THREAD

**Issue by natewind** [telegramdesktop/tdesktop#16921]
### Steps to reproduce

1. Minimize Telegram to tray.
2. Open it back.
3. Goto 1.

### Expected behaviour

The window remembers its position.

### Actual behaviour

The window moves a little higher every time until it reaches the top of the screen (the bottom of the top panel, to be precise) and stops there.

### Operating system

Ubuntu 20.04.3, GNOME 3.36.8

### Version of Telegram Desktop

3.0.1

### Installation source

Snap

**Comment by ilya-fedin** [comment]
It's a GNOME bug
https://gitlab.gnome.org/GNOME/mutter/-/issues/400

**Comment by natewind** [comment]
I see, thanks.
