### ISSUE TITLE
Mobile-to-Desktop Conversation Sync

### ISSUE THREAD

**Issue by Laparka** [telegramdesktop/tdesktop#16932]
### Steps to reproduce

1. Have the mobile (Android) and desktop (Windows 10) apps installed and active
2. Send a message to contact via a mobile app
3. Receive a response from the contact
4. No sent message is visible on the desktop app, but visible only on the mobile app

### Expected behaviour

Sent and received messages are visible on the both platforms - mobile and desktop

### Actual behaviour

The sent message is visible only on the mobile app but not on the desktop

### Operating system

Windows 10 Pro 21H1 19043.1165

### Version of Telegram Desktop

3.0.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can't reproduce, syncs just fine
