### ISSUE TITLE
Scaling at 90% gone?

### ISSUE THREAD

**Issue by ragreenburg** [telegramdesktop/tdesktop#16937]
I am using the Flatpak version of Telegram Desktop on a Pine Phone (Linux native phone) and a week or so ago it seems like the option to have scaling at 90% disappeared so now I can't see when I message and the app doesn't fit the screen anymore (slightly too big). Any chance of getting 90% scaling back?

**Comment by ilya-fedin** [comment]
There were never such option, you can set it only via cmdline argument `-scale`.

**Comment by ragreenburg** [comment]
I swear I had it, maybe I followed a wiki somewhere that had that. What exactly is the command? Trying to run `flatpak run org.telegram.desktop --scale 90` doesn't change anything.

**Comment by ilya-fedin** [comment]
`-scale`, not `--scale`

**Comment by ilya-fedin** [comment]
> I swear I had it

The GUI show the current scaling even if it's not in the list of predefined scale variants. As soon as you change the scale to one of the predefined variants, the custom one goes away from the GUI.

**Comment by ragreenburg** [comment]
Shoot, I misread. Thank you for the quick response and your contributions to Telegram!
