### ISSUE TITLE
Minimize button missing

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#16934]
### Steps to reproduce

So the minimize button isn't showing up, so we went into settings, advanced & checked off use window system frame & it's still not showing up.

I'm on Win 7

### Expected behaviour

I should be able to have minimze TG.

### Actual behaviour

No button

### Operating system

Win 7

### Version of Telegram Desktop

3.0.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@ILoveSkilledCoders Please provide a screenshot of the main window with and without the "Use native window frame" option enabled.

**Comment by ILoveSkilledCoders** [comment]
Ok, here's the window with it checked off.

the minimize - https://i.imgur.com/2Elz9to.png

advanced settings - https://i.imgur.com/fM9TvJV.png

Without it checked off

Minimize - https://i.imgur.com/0fwTTpB.png

advanced settings - https://i.imgur.com/J8zDiQ3.png

Thanks

**Comment by Aokromes** [comment]
what's your video (gfx) card? and what drivers version you are using?

**Comment by john-preston** [comment]
@ILoveSkilledCoders And on those screenshots is the top of the window on top of the screen? So that the window title bar just doesn't fit on screen and perhaps is there, just above the screen space?

**Comment by ILoveSkilledCoders** [comment]
> what's your video (gfx) card? and what drivers version you are using?

It's a 1023MB NVIDIA GeForce GT 710 (Gigabyte)

Driver - 27.21.14.6627

Thanks

**Comment by Aokromes** [comment]
> 4.6

try https://www.guru3d.com/files-details/geforce-471-96-whql-driver-download.html

**Comment by ILoveSkilledCoders** [comment]
> @ILoveSkilledCoders And on those screenshots is the top of the window on top of the screen? 

**Yes**

So that the window title bar just doesn't fit on screen and perhaps is there, just above the screen space?

Could be, but there's no way to fix that. How do you get to it?

I don't have this issue with any other software just to be clear.

WOW, One of your questions got Chris thinking & he had me do Win key up arrow & it FIXED IT. He was shocked.

He still thinks it's a bug though getting out of full screen mode (b/c I've restarted many times since then).

Also, the default UI makes the minimize disappear (keeps the max & X). If you hover over it, it comes back, then disappears after a few secs.

Then we turned on that checkmark in advanced & now it looks better.

Thanks

**Comment by L34T** [comment]
Window minimize/maximize disappeared from title bar after update.
https://i.imgur.com/q34dAGy.png
Debian 11 Bullseye
Telegram Desktop v3.1(self-update, installed .tar.xz package)
