### ISSUE TITLE
win64 build error

### ISSUE THREAD

**Issue by duanhjlt** [telegramdesktop/tdesktop#16939]
C:\BuildPath\ThirdParty\Python39\python.exe gyp-win-tool link-with-manifests environment.x64 True dump_syms.exe "C:\BuildPath\ThirdParty\Python39\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:dump_syms.exe @dump_syms.exe.rsp" 1 mt.exe rc.exe "obj\tools\windows\dump_syms\dump_syms.dump_syms.exe.intermediate.manifest" obj\tools\windows\dump_syms\dump_syms.dump_syms.exe.generated.manifest
Traceback (most recent call last):
  File "C:\BuildPath\Libraries\win64\breakpad\src\out\Release_x64\gyp-win-tool", line 332, in <module>
    sys.exit(main(sys.argv[1:]))
  File "C:\BuildPath\Libraries\win64\breakpad\src\out\Release_x64\gyp-win-tool", line 31, in main
    exit_code = executor.Dispatch(args)
  File "C:\BuildPath\Libraries\win64\breakpad\src\out\Release_x64\gyp-win-tool", line 73, in Dispatch
    return getattr(self, method)(*args[1:])
  File "C:\BuildPath\Libraries\win64\breakpad\src\out\Release_x64\gyp-win-tool", line 202, in ExecLinkWithManifests
    our_data = our_f.read().translate(str.maketrans('', '', string.whitespace))
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

**Comment by LI7XI** [comment]
@duanhjlt I'm not sure but shouldn't you use python 2.7 instead of 3.9? 🤔

**Comment by john-preston** [comment]
Can you try with the latest prepare script? I've patched GYP to work with Python 3.9 there, at least it worked for me. Maybe it is locale-dependent? 🤔

**Comment by Aokromes** [comment]
> @duanhjlt I'm not sure but shouldn't you use python 2.7 instead of 3.9? 🤔

python 2.7? that's end of life since 2020.

**Comment by LI7XI** [comment]
>python 2.7? that's end of life since 2020.

I mean, that what was written in the docs:

>Download Python 2.7 installer from https://www.python.org/downloads/ and install to BuildPath\ThirdParty\Python27

**Comment by john-preston** [comment]
@LI7XI yes, it was required before. Now it should work with python 3.9.

**Comment by taogege** [comment]
who solved it?I also have this error.

**Comment by taogege** [comment]
> Can you try with the latest prepare script? I've patched GYP to work with Python 3.9 there, at least it worked for me. Maybe it is locale-dependent? 🤔

Hello,today,I encounted this error too,I tried python versions from 2.7 - 3.10,this problem exsited all time.

**Comment by StraussLupusson** [comment]
> There's no solution, unfortunately. breakpad doesn't seem to be compatible with chinese Windows.

If I switch the system and vs. to english, will this problem be solved? I will try

**Comment by ilya-fedin** [comment]
If you're talking about changing system language in your system, I'm not sure. It's possible it will work only with a clear english Windows system.

**Comment by StraussLupusson** [comment]
OK, I decided to reinstall my Windows system, wait for my message

**Comment by tor-web3** [comment]
这是一个由中文系统引发的致命错误，事实上这个编译过程仅在纯英文的系统下成功过，这个错误还没有找到准确的方法，仍然值得研究，并且不确定是否能够通过修改系统语言解决这个问题。

**Comment by tor-web3** [comment]
As a workaround you can try set `PYTHONUTF8=1` before `tdesktop\Telegram\build\prepare\win.bat`

```
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
ninja: build stopped: subcommand failed.
[12/15](https://github.com/telegramdesktop/tdesktop/issues/Libraries/breakpad): FAILED
```
这是一个由编码引发的错误，我们目前执行的编译脚本是 `prepare.py`.
我们应当将当前的编译工作环境的字符集进行调整，以此解决编译字符集'gbk'错误
尝试在工作环境中调整字符集，例如命令：`PYTHONUTF8=1`
再重新执行`tdesktop\Telegram\build\prepare\win.bat`，这或许对你有帮助。

#24060

**Comment by tor-web3** [comment]
事实上这个错误显示是滞后的，建议在项目构建前就运行`PYTHONUTF8=1`命令，以避免更多的意外。
由于项目本身编译环境的不确定性，建议在全英文环境下的纯净系统中进行相关的编译工作。
事实上这对编译的成功率以及事故的发生率都有很大的帮助。

---

In fact this error display is lag, it is recommended to run the `PYTHONUTF8=1` command before the project is built to avoid more surprises.
Due to the uncertainty of the compilation environment of the project itself, it is recommended to perform related compilation work in a pure system in an all-English environment.
In fact, this greatly helps the compilation success rate as well as the accident rate.

**Comment by zero-rp** [comment]
run fast "chcp 65001",Re-execute tdesktop\Telegram\build\prepare\win.bat

**Comment by xiedeacc** [comment]
> run fast "chcp 65001",Re-execute tdesktop\Telegram\build\prepare\win.bat

this method not working, fixed by https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window
