### ISSUE TITLE
[Feature Request] Preserve formatting when copying text into another application

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#16930]
### Is your feature request related to a problem?

I write notes in Telegram, and I format the text (bold, italic, etc.). But when copying it to another app (browser, to publish on Telegraph; text editor, to save on disk) the fromatting is removed.

### Describe the solution you'd like

Preserve formatting when copying text into another application.

### Describe alternatives you've considered

Uum..can't think of any.

**Comment by ilya-fedin** [comment]
#5795
