### ISSUE TITLE
no secret chat! there is no button to start a new chat

### ISSUE THREAD

**Issue by deXter9009** [telegramdesktop/tdesktop#16938]
### Steps to reproduce

hello it is missing complete button for start new chat.  The selection for secret chat to start is missing. 
Please correct it. 
many small functions are gone. why desktop version is so different from phone version. 

thx

### Expected behaviour

ok

### Actual behaviour

ok

### Operating system

win10 pro

### Version of Telegram Desktop

3.0.2 beta

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
centuplicated.
