### ISSUE TITLE
[Feature request] Closing confirmation when uploading/downloading without a tray icon.

### ISSUE THREAD

**Issue by Merazi** [telegramdesktop/tdesktop#16931]
### Is your feature request related to a problem?

Hi there! I hope that whoever reads this is having a good day ...
I was wondering if it is possible to add a confirmation dialog by closing Telegram when the icon of the system tray is disabled, and the user is uploading/downloading a file. It is annoying to have to restart the upload/download because it closed the telegram window by mistake. This can improve the experience in environments that do not support the tray icons, such as the GNOME desktop.

Is this viable? 🤔 

### Describe the solution you'd like

If:
1. The tray icon is disabled
2. The user is uploading or downloading a file

Display a confirmation dialog before closing Telegram.

### Describe alternatives you've considered

Another solution may be leaving the app running in the background even if the tray icon is not available.

**Comment by john-preston** [comment]
@Merazi I hope the background work when the tray icon is  ot supported by the system may be added soon.

**Comment by ilya-fedin** [comment]
There was #4187, but it's closed as stale :thinking:

**Comment by Merazi** [comment]
> There was #4187, but it's closed as stale :thinking: 

Ok, I didn't saw it, sorry for opening a similar one.

**Comment by ilya-fedin** [comment]
> > 
> 
> Ok, I didn't saw it, sorry for opening a similar one.

the old one is closed, so no problem

**Comment by Merazi** [comment]
Okay 😄

**Comment by ilya-fedin** [comment]
@Merazi there's close to taskbar option in 3.0.4, feel free to close the issue if it fits your usecase

**Comment by Merazi** [comment]
It does! Thanks 😃
