### ISSUE TITLE
Pool has a bug

### ISSUE THREAD

**Issue by rabinpoudyal** [telegramdesktop/tdesktop#16933]
### Steps to reproduce

1. 6 members telegram group
2. 4 options in pool
3. 4 guys voted on 1 option
4. 1 guy voted on 1 option
5. 1 guy voted on 1 option
6. The result - 67%, 16%, 17% ( why one is 16 and another is 17)
7. It should be 16.5 each

### Expected behaviour

It should be 16.5 each

### Actual behaviour

one result is 16 another is 17

### Operating system

android

### Version of Telegram Desktop

latest

### Installation source

Mac App Store

**Comment by Aokromes** [comment]
android? mac app store?

**Comment by rabinpoudyal** [comment]
> android? mac app store?

Sorry I mean play store

**Comment by Aokromes** [comment]
well. this is telegram desktop bug tracker, not android.
