### ISSUE TITLE
Telegram Desktop for Linux doesn't connect when ExpressVPN is in use.

### ISSUE THREAD

**Issue by Raffles727** [telegramdesktop/tdesktop#16945]
### Steps to reproduce

Run Telegram
Connect to ExpressVPN
After a minute or two, try to send a message or watch to see if new messages are received..
No new messages are received while the VPN is connected

### Expected behaviour

Telegram should maintain the connection and messages should be sent and received as usual.

### Actual behaviour

Telegram displays "Connecting" and a perpetual circle in the top of the main window and is apparently offline as no messages can be sent or received.

### Operating system

Ubuntu 20.04 LTS

### Version of Telegram Desktop

Linux version 3.0.1

### Installation source

Static binary from official website

**Comment by Raffles727** [comment]
> stale

Hello, The issue has not resolved itself. In the meantime there have been several Telegram updates and Expressvpn updates.

The latest versions are 

Telegram version 3.6

Expressvpn version 3.19.0.13-1

What is puzzling is that sometimes messages do get through while the VPN is on but not the attachments, videos or images. 

Are there any other Linux Ubuntu desktop users who are experiencing the same issue?

**Comment by JackYang-hellobobo** [comment]
I also get the same situations ! Can't use the Tg in ubuntu20.04
