### ISSUE TITLE
[Feature Request] Send clipboard text as file

### ISSUE THREAD

**Issue by mojighahar** [telegramdesktop/tdesktop#16944]
### Is your feature request related to a problem?

Sometimes like we copy a config from the server and we want to send it to a teammate multiple large unreadable messages sended when we paste it from clipboard.

### Describe the solution you'd like

Send clipboard text as a text file instead of sending multiple messages. For example when we press Ctrl + Shift + V ask a filename and send clipboard text as a file.

### Describe alternatives you've considered

Paste clipboard to vs code and save it. then select and send the file to the teammate.

**Comment by 23rd** [comment]
#16070.
