### ISSUE TITLE
 [Feature Request] Forward message without quote

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [telegramdesktop/tdesktop#16953]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

A feature that provides the ability to forward messages without quoting the original sender

### Describe alternatives you've considered

It has been implemented in Plus messenger a long time ago.
But, Recently official Telegram app has been added this feature.

### Additional context

According to #8571 which closed by the reason: 
> this isn't going to be added on the desktop app as long as other Telegram apps don't have this option too.

So, It has been implemented in the official Telegram app now.

**Comment by john-preston** [comment]
![image](https://user-images.githubusercontent.com/17900494/133223699-163f20c6-e42d-4f4e-a4e7-caae6df6410b.png)
