### ISSUE TITLE
[Feature Request] Storing chats locally on disk and securely owning our data

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#16951]
### Is your feature request related to a problem?

Others can delete our own messages from our history.

### Describe the solution you'd like

Option to store everything locally, where others can't interfere with it. Of course if others are still allowed to delete messages from **_our_** local storage - it beats the purpose. I want to be in control of my data, not a subject to the whims of others.

### Describe alternatives you've considered

Automatic backups are a crutch. Need local storage with no interference from others.

### Additional context

Also, complete reliance on Telegram for storage is something I'm not entirely comfortable with. I even want an option to store data _**only**_ locally.

**Comment by ilya-fedin** [comment]
This is against Telegram API ToS: https://core.telegram.org/api/terms
> 1.4. It is forbidden to interfere with the basic functionality of Telegram. This includes but is not limited to: making actions on behalf of the user without the user's knowledge and consent, preventing self-destructing content from disappearing, preventing last seen and online statuses from being displayed correctly, tampering with the 'read' statuses of messages (e.g. implementing a 'ghost mode'), preventing typing statuses from being sent/displayed, etc.
