### ISSUE TITLE
Archived chats still on top of list on Mac 

### ISSUE THREAD

**Issue by tueksta** [telegramdesktop/tdesktop#16959]
### Steps to reproduce

Archive a chat
Look at list
Collapse archived chat

### Expected behaviour

Archived chat should be at the bottom and there should be an option to hide it altogether

### Actual behaviour

Stays on top of list, both collapsed or uncollapsed

(see https://github.com/telegramdesktop/tdesktop/issues/5989 for the Windows fix)

### Operating system

OS X 10.14.6

### Version of Telegram Desktop

220932

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> 220932

tdesktop doesn't have such a version, look at https://github.com/telegramdesktop/tdesktop/releases
