### ISSUE TITLE
Telegram-desktop doesn't send registration SMS

### ISSUE THREAD

**Issue by baarkerlounger** [telegramdesktop/tdesktop#16954]
### Steps to reproduce

Steps:

1. Click "Start Messaging"
2. Click "or log in using your phone number"
3. Type phone number and click "Next"

### Expected behaviour

An SMS should be sent to the entered phone number

### Actual behaviour

No SMS is sent

### Operating system

Mobian (Debian Bookworm based)

### Version of Telegram Desktop

3.0.1

### Installation source

Flatpak

**Comment by sc0w** [comment]
the same issue here with official debian package: 2.9.2+ds-1

(mobian bookworm pinephone)

**Comment by Aokromes** [comment]
not a bug, telegram server side limitation.

**Comment by sc0w** [comment]
telegram desktop can't send warning to the user if the sms never is send?

it makes no sense to force the user to wait if no sms is sended

**Comment by RememberTheAir** [comment]
tdesktop waits for the user to receive the verification code on other active sessions (such as, any Telegram app installed on another device). No idea why they decided it should work like that, but it works like that now. This is a server-side configuration as the server decides whether to send the SMS or not based on the client that requested it

**Comment by sc0w** [comment]
The problem is when the user is the first time with telegram, no other active sessions, and no sms, it is unable to active and use telegram.

I can't believe this isn't an valid issue.

Maybe adds the confirmation by email helps.

**Comment by baarkerlounger** [comment]
Does that mean it's impossible to do the registration from Telegram-desktop without having already registered the number on another device? i.e. you can't use it as your only device?

**Comment by john-preston** [comment]
@baarkerlounger Yup :(

**Comment by baarkerlounger** [comment]
That seems like a limitation that isn't advertised at all. If it can't be changed by the client app, the client app should maybe at least make that clear?

Is there an upstream server repo where this could be filed as an API bug?

**Comment by john-preston** [comment]
@baarkerlounger The app should show you that the code was sent on another device in Telegram and if you request a code by SMS it should show you the explanation message.

**Comment by baarkerlounger** [comment]
When I request a code by SMS no explanation is shown, it looks as if one will be sent but never is.

**Comment by RememberTheAir** [comment]
> If it can't be changed by the client app, the client app should maybe at least make that clear?

Here: https://bugs.telegram.org/c/4239

**Comment by john-preston** [comment]
@baarkerlounger Can you please provide your phone number (the one that didn't receive SMS message on Flatpak build, but showed, that it was sent) to me privately at t.me/preston ?

**Comment by Laiteux** [comment]
Does anyone know the exact reason of this "new" limitation, though?

**Comment by Aokromes** [comment]
> Does anyone know the exact reason of this "new" limitation, though?

very likely to kill spammers.

**Comment by ediowar** [comment]
> very likely to kill spammers.
Can't you find out exactly? Maybe if there is only a confirmation code in the SMS, the SMS will come.

**Comment by Aokromes** [comment]
> > very likely to kill spammers.
> 
> Can't you find out exactly? Maybe if there is only a confirmation code in the SMS, the SMS will come.

i am not telegram staff, i cannot guess what durov thinks.
