### ISSUE TITLE
[Feature Request] "Choosing a Sticker" Setting Toggle

### ISSUE THREAD

**Issue by MrPeeperNumber** [telegramdesktop/tdesktop#16957]
### Is your feature request related to a problem?

Telegram has many features that allow a person to customize their privacy settings to whatever degree they like... except when interacting with the stickers panel/menu on both mobile and desktop clients. Telegram shouldn't be forcing people to broadcast that they're "choosing a sticker" whenever there's activity in the menu/panel in either client, when it provides all these other privacy options.

### Describe the solution you'd like

Implementing a toggle in the "Privacy and Security" section of settings that allows you to turn off the "Choosing a Sticker." Similarly to other privacy settings, give a drop-down menu that allows you to select who can see the broadcast: everybody, contacts, nobody, nobody w/ exceptions, and groups.

### Describe alternatives you've considered

N/A

**Comment by 23rd** [comment]
[bugs.telegram.org/c/9068](https://bugs.telegram.org/c/9068).
