### ISSUE TITLE
[Linux] The window does not appear at the top when you click on a notification.

### ISSUE THREAD

**Issue by Akionka** [telegramdesktop/tdesktop#16966]
### Steps to reproduce

1. Minimize the application to the taskbar (not to the tray, imporant) 
2. Receive any notification
3. Click on it

### Expected behaviour

It shows the window at the top.

### Actual behaviour

It doesn't show the window at the top, though it opens the chat and the message I have received notification about. But the window is in the background.

### Operating system

OS: Manjaro Linux x86_64 | DE: Plasma 5.22.5 | WM: kwin

### Version of Telegram Desktop

3.0.5 beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Maybe you're on Wayland? Wayland doesn't allow to focus a window.

**Comment by Akionka** [comment]
> Maybe you're on Wayland? Wayland doesn't allow to focus a window.

Yes, I am on Wayland. No way to fix it?

**Comment by ilya-fedin** [comment]
> No way to fix it?

I don't know one
