### ISSUE TITLE
Having issues when changing the default Download folder in Ubuntu.

### ISSUE THREAD

**Issue by jpafrota** [telegramdesktop/tdesktop#16967]
I am using telegram desktop for Ubuntu 20.04 (stable **snap** version: 3.01).

I've changed my default Download folder to another drive, but the problem is that Telegram can't access those folders, and whenever I try to send or download files, I get an error message. Probably a permission issue. I'm new to Linux so I'd be glad if someone could tell me how to solve this.

![image](https://user-images.githubusercontent.com/81825051/133898445-18e7b008-d656-4d51-87f5-b4899d39def7.png)

Here's how it looks like whenever I try to send or download something.

**Comment by ilya-fedin** [comment]
Yeah, you should give the permission manually: `snap connect telegram-desktop:removable-media :removable-media`

**Comment by jpafrota** [comment]
Thank you so much. Exactly what I was looking for.
