### ISSUE TITLE
Round corners on Windows 11

### ISSUE THREAD

**Issue by HoodyH** [telegramdesktop/tdesktop#16964]
### Is your feature request related to a problem?

With the new os the apps that use the default windows window got round corners automatically.
But i suppose that telegram app is rendereing all itself. 

### Describe the solution you'd like

I suggest to use the default window, and also the default close, reduce, minimize buttons, because in the near feature they will get a redesign to match the new fluent design.

### Describe alternatives you've considered

This will help to make telegram looks better. And using the default window round corners, them will show only on win 11 and not also on win 10

### Additional context

this is just a suggestion <3 , I hope it won't take much work

**Comment by john-preston** [comment]
@HoodyH There is an option to use native window frame.

**Comment by crackedmind** [comment]
Rounded corners can be applied with  DwmSetWindowAttribute
```

// The enum flag for DwmSetWindowAttribute's second parameter, which tells the function what attribute to set.
enum DWMWINDOWATTRIBUTE
{
    DWMWA_WINDOW_CORNER_PREFERENCE = 33
}

// The DWM_WINDOW_CORNER_PREFERENCE enum for DwmSetWindowAttribute's third parameter, which tells the function
// what value of the enum to set.
enum DWM_WINDOW_CORNER_PREFERENCE
{
    DWMWCP_DEFAULT      = 0,
    DWMWCP_DONOTROUND   = 1,
    DWMWCP_ROUND        = 2,
    DWMWCP_ROUNDSMALL   = 3
}
```

From here https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-rounded-corners

**Comment by john-preston** [comment]
@crackedmind it does work indeed 😱 

![image](https://user-images.githubusercontent.com/17900494/134806932-ce3072d4-dabb-4022-958d-fbec102d5b83.png)

But the shadow needs to be adjusted.. And maybe the close button too.

**Comment by john-preston** [comment]
🤔  But I can't fix the shadow for the corners here :( Because painting in this light corner that system rounded isn't available.

**Comment by TrashAccount3424** [comment]
> 🤔 But I can't fix the shadow for the corners here :( Because painting in this light corner that system rounded isn't available.

Seems like the round corner issue is fixed already but regarding the shadow, I think it should be dropped completely under Windows.
The OS automatically puts a shadow under the window (both native and non-native) if enabled in the OS settings.
Under Windows 10 the non-native windows frame however paints a barely visible shadow regardless of OS setting.
So basically with the non-native window you cant turn shadow on properly but also not fully off.
Under Windows 11 it seems to work correctly already.

OS wide windows shadow can be turned on or off under under `About > Advanced system settings > Performance [Settings...] > [  ] Show shadows under windows`

**Comment by john-preston** [comment]
@TrashAccount3424 Yes, on Windows 11 native rounding with native shadow is used. There is no plans to change anything on Windows 10 for now.

**Comment by TrashAccount3424** [comment]
> @TrashAccount3424 Yes, on Windows 11 native rounding with native shadow is used. There is no plans to change anything on Windows 10 for now.

Whats the benefit/reason why its different on Windows 10?
My quick testing seems to indicate that the same code would behave exactly the same under windows 10 i.e. no round corner but still have native shadow that can be turned on or off.

**Comment by john-preston** [comment]
@TrashAccount3424 On Windows 11 the shadow was enabled when I've enabled rounded corners by the new Windows 11 API for that. Don't know what do you mean by "same code" on Windows 10.
