### ISSUE TITLE
[Question] What happened to the tinted theme?

### ISSUE THREAD

**Issue by Laiteux** [telegramdesktop/tdesktop#16969]
Hello,

I'm on a beta version (3.0.5) so I don't know if this is intended, but what's all this white everywhere?
On "Transferred from {name}", on read ticks, on voice messages and much more...

I personally find this very bad to look at, why replace some nice blue colors by some pure #ffffff white? And why does it only seem to affect the tinted theme while the night one is fine?

This commit seems linked to the problem: https://github.com/telegramdesktop/tdesktop/commit/4d267327b8ff7d799a33db7826a402e658dd3c3c

I tried reverting to the default `night.tdesktop-theme` file prior to this commit (can be found [here](https://github.com/telegramdesktop/tdesktop/commits/4d267327b8ff7d799a33db7826a402e658dd3c3c/Telegram/Resources/night.tdesktop-theme)), and it works, however because of the fact it's an imported theme I'm unable to edit the accent color, which still makes it different from the previous theme I had, since it's way brighter now.

This is me switching from the current tinted theme to the previous one linked above:

![](https://i.imgur.com/RgqWikQ.gif)

How can I fully revert to my old good theme? :(
Also, were these changes really intended? Or should this be a bug report?

Thank you, and let me take advantage of this post and end it on a better note by congratulateing everyone working on this project. The Telegram desktop app is so, so amazing, and I'm very happy to use it in my everyday life. There is no better alternative, and I mean it. Thank you!

**Comment by john-preston** [comment]
This theme was updated. But I guess we decided to revert it to the previous one for now. So you're lucky :)

**Comment by john-preston** [comment]
But yes, if you see a commit saying "Update built-in Tinted dark theme." and then the built-in Tinted dark theme gets updated, usually it is intended 🤔
