### ISSUE TITLE
Very limited individual theme support

### ISSUE THREAD

**Issue by zakiloki0** [telegramdesktop/tdesktop#16975]
With the new version we can have individual themes and that is great, but in the desktop version the support does not seem so good, I think it would be better if it was adapted to more elements and not only within the chat.

**Comment by ilya-fedin** [comment]
You created issue of type question, what is the question?

**Comment by zakiloki0** [comment]
> You created issue of type question, what is the question?

Sorry, I mean the question is, can the support invidual theme be better?

Thanks.

**Comment by john-preston** [comment]
@zakiloki0 It is meant to be applied only to the chat, not to the entire app.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by zakiloki0** [comment]
> @zakiloki0 It is meant to be applied only to the chat, not to the entire app.

Ah ok, although I do not mean the whole application, but for example the upper part where the username is and the text box where you type, I expected it to be like this It would have been better in my opinion.

Thanks guys :)
