### ISSUE TITLE
[Question] как выключить эту лгбт раскраску?

### ISSUE THREAD

**Issue by TristisOris** [telegramdesktop/tdesktop#16979]
обновилось и вот.
правильной дорогой идем, товарищи.
![изображение](https://user-images.githubusercontent.com/1270117/133978665-f5511fa3-aaaa-4e4f-b21f-360f88ea9ec9.png)

**Comment by Aokromes** [comment]
english plz.

**Comment by TristisOris** [comment]
how to get back for normal chat view after today update?

**Comment by john-preston** [comment]
@TristisOris You can switch a custom theme off from a mobile Telegram app version 8.1

**Comment by TristisOris** [comment]
i not using any custom themes.

**Comment by john-preston** [comment]
@TristisOris I guess your correspondent does. It is synced between correspondents in one-on-one chats.

**Comment by TristisOris** [comment]
they could use anything they want. why i should see this?
mobile X client have no such option. desktop too. so?

**Comment by john-preston** [comment]
@TristisOris You could say "they could write anything they want, why should I see this?", but this is how things work in Telegram. Both chat messages and chat color theme are synced between you two in your private chat.

In mobiles there should be a Change Colors option, where you can choose "No Theme". You can read more in the blog post:

https://telegram.org/blog/chat-themes-interactive-emoji-read-receipts
