### ISSUE TITLE
Several incoming call notifications lasted until I stopped them

### ISSUE THREAD

**Issue by Teddynet** [telegramdesktop/tdesktop#16970]
### Steps to reproduce

There are no particular steps to reprcoduce it. 
This issue happened about 3 times.

### Expected behaviour

When I receive an incoming call notification on my pc without accept or reject the call, the notification (popup and sound) ends immediately when the caller hangs the call

### Actual behaviour

I received (3 different times) an incoming call notification which lasted until I stopped it. 
If the caller hangs the call, the notification sound continues. Unfortunately the last time, I wasn't at home and the notification sound lasted for three hours and my neighbors were angry a lot. 
When I acted, the program wasn't freezed because it responded to my command when I tried to reject incoming call.
Simply the popup notification was stucked.

### Operating system

MS Windows 10 20H2 (build SO 19042.1237)

### Version of Telegram Desktop

3.05 Beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#8531
