### ISSUE TITLE
Telegram Desktop 3.0

### ISSUE THREAD

**Issue by Damir8886** [telegramdesktop/tdesktop#16973]
Здраствуйте
Telegram Desktop 3.0 , Win. 10
Очень частые зависания . Буквально каждые 5-7 минут приходиться закрывать через диспетчер задач

**Comment by ilya-fedin** [comment]
english only

**Comment by Damir8886** [comment]
Hello
Telegram Desktop 3.0, Win. 10
Very frequent freezes. Literally every 5-7 minutes you have to close it through the task manager. Appeared after update

**Comment by ilya-fedin** [comment]
You removed entire template that asks you for the basic useful info, so the issue is invalid.
