### ISSUE TITLE
[Feature Request] Read Reciepts should be "opt in only" to help protect users privacy

### ISSUE THREAD

**Issue by JustCallMeAD** [telegramdesktop/tdesktop#16974]
### Is your feature request related to a problem?

Read Receipts (introduced in v3.1) are a breach of privacy and should be opt in only.

### Describe the solution you'd like

Please make Read Reciepts "opt in" only to help protect users privacy.

**Comment by RememberTheAir** [comment]
tdesktop can't do nothing about it, please vote [this card](https://bugs.telegram.org/c/9184) on the official suggestions platform

**Comment by JustCallMeAD** [comment]
Thanks. Feel frre to delete this issue if you want.
