### ISSUE TITLE
window dragging on scroll

### ISSUE THREAD

**Issue by L34T** [telegramdesktop/tdesktop#16978]
### Steps to reproduce

1. Drag Telegram window by dragging on title bar with lmb.
2. Drag Telegram window by dragging on title bar with middle mouse button.
3. Click lmb to prevent future dragging.
4. Move mouse pointer inside window on any scrollable element
5. Scroll mouse wheel(do not click any buttons).

### Expected behaviour

Scrolling chats/messages. Window is not in dragging mode.

### Actual behaviour

Window is in dragging mode.
Fixing:
5. Click lmb to prevent future dragging.
6. Select any dialog/chat/etc
7. Mouse scrolling works normal again.

### Operating system

Debian 11, lxde

### Version of Telegram Desktop

3.1, self-updated tsetup.tar.xz(from site, not from repo)

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#10348
