### ISSUE TITLE
[Question] How disable autoupdate for tdesktop from official site?

### ISSUE THREAD

**Issue by x09** [telegramdesktop/tdesktop#16976]
Hi,

I use linux binary from desktop.telegram.org 
How disable check updates?
Am I expecting a 
1. command line parameter (i found -noupdate option, but not worked), 
2. environment variable, 
3. global/user config file,
4. anything?

**Comment by john-preston** [comment]
@x09 Settings > Advanced ?

**Comment by x09** [comment]
> @x09 Settings > Advanced ?

per user solution only? i expect "no interactive" way

**Comment by john-preston** [comment]
@x09 There is no such way right now :(
