### ISSUE TITLE
Thumbs up, thumbs down etc...

### ISSUE THREAD

**Issue by Resonanz** [telegramdesktop/tdesktop#16984]
### Is your feature request related to a problem?

Simple expressions using emojis that attach directly to a chat as per iMessage and other apps.

### Describe the solution you'd like

Thumbs up, thumbs down, "Ha ha", heart, Exclamation marks !!!

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by ilya-fedin** [comment]
They already present

**Comment by Resonanz** [comment]
I guess we are talking about different things then, because they certainly are not there on my devices.  Perhaps we have a misunderstanding -- I meant that the emoji would attach to a specific speech bubble...? As I wrote:

"Simple expressions using emojis that attach directly to a chat as per iMessage and other apps."

To be clear, I am NOT saying there are no emojis... I AM SPECIFICALLY saying that there is no way to attach a single emoji to a single chat balloon.

Thanks.

**Comment by ilya-fedin** [comment]
If you want others to better understand your feature request, you can attach screenshots

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
