### ISSUE TITLE
[Question] Old layout vs. new layout

### ISSUE THREAD

**Issue by jhbecares** [telegramdesktop/tdesktop#1698]
Is there any way and if there is, how to change the view to the "old" layout? I am used to having the things I'm saying appearing on the right hand side of the window and the rest on the left. Having everything on the left but with a different colour is not working out very well for me after trying it for 3 days. Thanks in advance

**Comment by auchri** [comment]
Go to settings -> background image. There's a checkbox to turn the new layout off.
