### ISSUE TITLE
+1

### ISSUE THREAD

**Issue by daKeshra7** [telegramdesktop/tdesktop#16980]
+1

_Originally posted by @yottanami in https://github.com/telegramdesktop/tdesktop/issues/1268#issuecomment-177168649_

I have an issue using telethon, when I run the script it adds members, but the group members does not increase in number... what could be wrong??

**Comment by RememberTheAir** [comment]
That's like the weirdest issue that has ever been opened here. You won't get any help if you're scripting member addition

**Comment by Aokromes** [comment]
this is telegram desktop bug tracker, not telethon.
