### ISSUE TITLE
Telegram accidently uninstalled. 

### ISSUE THREAD

**Issue by Mel39331** [telegramdesktop/tdesktop#16992]
### Steps to reproduce

Accidently uninstalled Telegram
Redownloaded from Telegram for Windows x64
Typed in country code & full phone number but it never sends activation code to phone
Also will not load at times

### Expected behaviour

Telegram should send me activation or access code to my phone. Haven't been able to get onto Telegram for weeks now. 

### Actual behaviour

Nothing happens after I type in country code and full phone number. It just sits there waiting for the code. 

### Operating system

Windows10x64

### Version of Telegram Desktop

Windows x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
you need telegram installed on movile to get sms, if you don't have android or ios mobile try downloading kotatogram.
