### ISSUE TITLE
Window button to left

### ISSUE THREAD

**Issue by zakiloki0** [telegramdesktop/tdesktop#16998]
### Steps to reproduce

I don't know if this is a bug or a change from the app

Usually I have my windows buttons (close, maximize, minimize) set to left in all apps

When I updated to 3.1 they change to right in Telegram only

### Expected behaviour

The buttons should be in left side

### Actual behaviour

The buttons is in right side

### Operating system

Arch Linux with Plasma

### Version of Telegram Desktop

3.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Do you have autostart enabled? Have you tried to quit from autostarted instance and launch it manually?

**Comment by zakiloki0** [comment]
> Do you have autostart enabled? Have you tried to quit from autostarted instance and launch it manually?

Yes, I did, and still the same. Was something related to this feature changed in the update? I've had the buttons on the left for years and they were never changed. It's strange

**Comment by ilya-fedin** [comment]
> Was something related to this feature changed in the update?

Yeah, gtk dependency was removed and replaced with hand-made parts. Do you have xsettingsd installed? If not, install it and reboot.

**Comment by ilya-fedin** [comment]
> I've had the buttons on the left for years and they were never changed.

Well, it's not truth, tdesktop titlebar hadn't support for getting controls position in first versions with it (that was somewhen at start of 2020)

**Comment by zakiloki0** [comment]
> > Was something related to this feature changed in the update?
> 
> Yeah, gtk dependency was removed and replaced with hand-made parts. Do you have xsettingsd installed? If not, install it and reboot.

Thaaaanks! Now is fixed! Thank you very much for helping me so quickly, you are the best!

_Well, it's not the truth, tdesktop titlebar had no support for getting controls position from the system initially (that was somewhere in the beginning of 2020)_

You're right, I meant that I generally always used the buttons on the right with the Plasma window manager, and when Telegram included its own button (which I like a lot more) then I started using that one! :D

Thanks ilya!
