### ISSUE TITLE
Delete for everyone? box showing up even when there's only 1 member

### ISSUE THREAD

**Issue by Presskopp** [telegramdesktop/tdesktop#16996]
### Steps to reproduce

1) Create a group and delete everyone besides yourself so there's only 1 left in the group
2) write a message
3) delete the message
4) Message shows up, if you want to delete for everyone

![image](https://user-images.githubusercontent.com/18373563/134472407-39a90382-8494-4628-8866-798153cdcc35.png)
![image](https://user-images.githubusercontent.com/18373563/134472386-fe968537-5cd2-44d1-ab99-445ad987b8f8.png)

I think this is not needed at this point because yes, it should be deleted for everyone automatically.

looks like this is to be handled in "confirm_box.cpp" around L. 655

### Expected behaviour

The post should be deleted for everyone automatically.

### Actual behaviour

I get asked if I want to delete the post for everyone

### Operating system

Windows 10 Desktop

### Version of Telegram Desktop

3.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
i don't think this is a bug.

**Comment by Presskopp** [comment]
you may be right

**Comment by RememberTheAir** [comment]
The app doesn't know whether the message was sent when there were more than one members in the group, so the box should be always visible (it should revoke the message from the chat history of the members who has been removed but for some reason can still see the messages history (for example, when they have been removed from a bot or an outdated client))

**Comment by Presskopp** [comment]
ok thanks for clarification. I keep my mouth shot then
