### ISSUE TITLE
Add a feature to turn off "joined the group" message 

### ISSUE THREAD

**Issue by nomadus** [telegramdesktop/tdesktop#16990]
### Is your feature request related to a problem?

When a group is large, we get a number of "joined the group" messages, this is a meaningless message and there is no way to turn it off. 

### Describe the solution you'd like

A config variable that allows group admins to turn such messages off

### Describe alternatives you've considered

There is a way to add a bot, but most admins have no knowledge of how to do it. And adding a bot with admin privileges is dangerous

**Comment by RememberTheAir** [comment]
Such requests belong to https://suggestions.telegram.org because tdesktop can't implement them on its own
