### ISSUE TITLE
Regression: Auto-night mode not working on Wayland

### ISSUE THREAD

**Issue by escape0707** [telegramdesktop/tdesktop#17002]
### Steps to reproduce

1. `sudo pacman -Syu` updates telegram-desktop from 3.0.1-1 to 3.1.0
2. Start telegram-desktop with `env QT_QPA_PLATFORM=wayland telegram-desktop`

### Expected behaviour

Auto-night mode setting is missing, and its function is not working.

### Actual behaviour

Auto-night mode setting is showing up at `Settings - Chat Settings`, and is functioning.

Although it still works with `env QT_QPA_PLATFORM=xcb telegram-desktop`.

### Operating system

ArchLinux, GNOME Wayland 40.4.0

### Version of Telegram Desktop

3.1.0

### Installation source

Other (unofficial) source

### Logs

```shell
$ telegram-desktop 

(telegram-desktop:12018): Telegram-WARNING **: 10:45:30.121: Application was built without embedded fonts, this may lead to font issues.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[ALSOFT] (EE) Failed to set real-time priority for thread: 許可されていない操作です (1)
QPainter::begin: Paint device returned engine == 0, type: 3
QWidget::render: Cannot render with an inactive painter
QPainter::begin: Paint device returned engine == 0, type: 3
QWidget::render: Cannot render with an inactive painter
error: : cannot open
error: : cannot open
error: : cannot open
```

**Comment by ilya-fedin** [comment]
xdg-desktop-portal is required for that functionality now

**Comment by escape0707** [comment]
Install any package providing `xdg-desktop-portal` fixed this for me.

Thanks!
