### ISSUE TITLE
telegram recognising small video as gif. unable to save to gallery on phone due to this.

### ISSUE THREAD

**Issue by leonoctem** [telegramdesktop/tdesktop#17000]
I am having the same issue as here. https://github.com/telegramdesktop/tdesktop/issues/2053

I use telegram to quickly transfer small files form my PC to my phone.
I am trying to transfer a video to my phone to use on tiktok. however when I send it in telegram, telegram labels it as a gif and gifs can't be saved to my files. you can only save to gifs or delete which isn't what I need to do. I've transferred the file via another service that takes longer, but I thought I'd bring this issue up as it seems to have been a problem since at least 2016 and still hasnt been fixed.

**Comment by ilya-fedin** [comment]
right click on the gif -> Save File As..
