### ISSUE TITLE
Allow inline reactions similar to Slack reactions

### ISSUE THREAD

**Issue by TimvdLippe** [telegramdesktop/tdesktop#1700]
Sometimes you want to leave a reaction to a funny message in-line, without spamming +1 or a laughing emoticon, because the message would be hidden by all messages sent later.

Therefore a feature similar to [Slack reactions](https://get.slack.help/hc/en-us/articles/206870317-Emoji-reactions) would be very appreciated. So we can show the support/reactions to people, without spamming the message to history.

**Comment by DaFri-Nochiterov** [comment]
No API for this.
(-O_O)/ You can ask about new features in [![Twitter icon](https://twitter.com/favicon.ico)Twitter](https://twitter.com/telegram) or by clicking _Options → Ask question_ in official Telegram apps

Just for read: [![Telegram icon](https://desktop.telegram.org/img/td_favicon_16x16.png) Feature Philosophy](https://core.telegram.org/tsi/feature_philosophy)
