### ISSUE TITLE
Telegram-desktop from Snap Store stopped to work in suse tumbleweed from - glibc error

### ISSUE THREAD

**Issue by akontsevich** [telegramdesktop/tdesktop#17004]
### Steps to reproduce

1. Install in openSuse Tumbleweed latest: https://snapcraft.io/install/telegram-desktop/opensuse
2. Run

### Expected behaviour

Run without a crash

### Actual behaviour

Crashes. Also saw this bug as well there running telegram:

https://forum.snapcraft.io/t/acestreamplayer-mpv-stopped-to-work-glibc-error/23061/5

### Operating system

Linux openSuse Tumbleweed 

### Version of Telegram Desktop

3.1

### Installation source

Snap

### Logs

```shell
>  telegram-desktop 

WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x58c873 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x58c873
stack: frame={sp:0x7ffe65efefa0, fp:0x0} stack=[0x7ffe65700458,0x7ffe65eff490)
00007ffe65efeea0:  00007ffe65efeee0  000000000046b4be <runtime.callCgoMmap+62> 
00007ffe65efeeb0:  00007ffe65efeeb0  00007ffe65efeee8 
00007ffe65efeec0:  00007ffe65efeef8  0000000000572dec 
00007ffe65efeed0:  00000000005fb430  000000001c000004 
00007ffe65efeee0:  000000000057a4d0  0000000000000000 
00007ffe65efeef0:  0000000000000000  00000000005931ee 
00007ffe65efef00:  0000000000000000  0000000000000000 
00007ffe65efef10:  0000000000000010  0000000000000000 
00007ffe65efef20:  0000000000000120  0000000000000110 
00007ffe65efef30:  00007f97c0b17fff  0000000000000012 
00007ffe65efef40:  0020300000000000  00000000005cb831 
00007ffe65efef50:  00007f97c07f7640  00007ffe65eff210 
00007ffe65efef60:  00007ffe65eff07e  00007ffe65eff07f 
00007ffe65efef70:  00007f97c07f7640  000000000058b205 
00007ffe65efef80:  000080c00003dfff  00000000000209a0 
00007ffe65efef90:  00000000003d0f00  000000000058c865 
00007ffe65efefa0: <00007f97c07f7910  0000000000000006 
00007ffe65efefb0:  0000000000000001  000000000057a456 
00007ffe65efefc0:  0000000000802a00  00000000004011ec 
00007ffe65efefd0:  0000000000000020  0000000000000000 
00007ffe65efefe0:  0000000000000000  e25dcb1e01550000 
00007ffe65efeff0:  00007ffe65eff0c0  00007f97c07f7640 
00007ffe65eff000:  0000000000000000  00007ffe65eff210 
00007ffe65eff010:  00007f97c07f7640  000000000058bf1a 
00007ffe65eff020:  00007ffe65eff210  0000000000585ded 
00007ffe65eff030:  0000000000d35650  00000000007bb700 
00007ffe65eff040:  00000000006c3633  0000000000585ded 
00007ffe65eff050:  0000000000000828  00000000007bb700 
00007ffe65eff060:  00000000007bb783  00000000007d30c0 
00007ffe65eff070:  0000000000000828  0000000000584e9e 
00007ffe65eff080:  0000000000000001  00000000007bb700 
00007ffe65eff090:  0000000000d343c0  00007ffe65eff2d0 
runtime: unknown pc 0x58c873
stack: frame={sp:0x7ffe65efefa0, fp:0x0} stack=[0x7ffe65700458,0x7ffe65eff490)
00007ffe65efeea0:  00007ffe65efeee0  000000000046b4be <runtime.callCgoMmap+62> 
00007ffe65efeeb0:  00007ffe65efeeb0  00007ffe65efeee8 
00007ffe65efeec0:  00007ffe65efeef8  0000000000572dec 
00007ffe65efeed0:  00000000005fb430  000000001c000004 
00007ffe65efeee0:  000000000057a4d0  0000000000000000 
00007ffe65efeef0:  0000000000000000  00000000005931ee 
00007ffe65efef00:  0000000000000000  0000000000000000 
00007ffe65efef10:  0000000000000010  0000000000000000 
00007ffe65efef20:  0000000000000120  0000000000000110 
00007ffe65efef30:  00007f97c0b17fff  0000000000000012 
00007ffe65efef40:  0020300000000000  00000000005cb831 
00007ffe65efef50:  00007f97c07f7640  00007ffe65eff210 
00007ffe65efef60:  00007ffe65eff07e  00007ffe65eff07f
00007ffe65efef70:  00007f97c07f7640  000000000058b205
00007ffe65efef80:  000080c00003dfff  00000000000209a0
00007ffe65efef90:  00000000003d0f00  000000000058c865
00007ffe65efefa0: <00007f97c07f7910  0000000000000006
00007ffe65efefb0:  0000000000000001  000000000057a456
00007ffe65efefc0:  0000000000802a00  00000000004011ec
00007ffe65efefd0:  0000000000000020  0000000000000000
00007ffe65efefe0:  0000000000000000  e25dcb1e01550000
00007ffe65efeff0:  00007ffe65eff0c0  00007f97c07f7640
00007ffe65eff000:  0000000000000000  00007ffe65eff210
00007ffe65eff010:  00007f97c07f7640  000000000058bf1a
00007ffe65eff020:  00007ffe65eff210  0000000000585ded
00007ffe65eff030:  0000000000d35650  00000000007bb700
00007ffe65eff040:  00000000006c3633  0000000000585ded
00007ffe65eff050:  0000000000000828  00000000007bb700
00007ffe65eff060:  00000000007bb783  00000000007d30c0
00007ffe65eff070:  0000000000000828  0000000000584e9e
00007ffe65eff080:  0000000000000001  00000000007bb700
00007ffe65eff090:  0000000000d343c0  00007ffe65eff2d0

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib64/go/1.16/src/runtime/asm_amd64.s:339 fp=0xc000042788 sp=0xc000042780 pc=0x467980
runtime.main()
        /usr/lib64/go/1.16/src/runtime/proc.go:144 +0x89 fp=0xc0000427e0 sp=0xc000042788 pc=0x4393a9
runtime.goexit()
        /usr/lib64/go/1.16/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000427e8 sp=0xc0000427e0 pc=0x4697c1

rax    0x0
rbx    0xd343c0
rcx    0x58c873
rdx    0x6
rdi    0x518e
rsi    0x518e
rbp    0x518e
rsp    0x7ffe65efefa0
r8     0x7ffe65efefd0
r9     0x5a2550
r10    0x8
r11    0x206
r12    0x6
r13    0x7ffe65eff2d0
r14    0x6b8092
r15    0x0
rip    0x58c873
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```
```

Bug on snapcraft.io: https://forum.snapcraft.io/t/telegram-desktop-stopped-to-work-in-suse-tumbleweed-glibc-error/26741

**Comment by ilya-fedin** [comment]
I'm not sure what do you except by creating an issue... Do you want to Telegram to replace your system's glibc? I guess snapd won't allow that...

**Comment by akontsevich** [comment]
> I'm not sure what do you except by creating an issue... 

Are from telegram team? If not - do no spam here. There was the only link to report issues: https://snapcraft.io/telegram-desktop:  

![Screenshot_20210924_184205](https://user-images.githubusercontent.com/3843657/134703137-b20e190d-03ac-44bc-9bf8-e37646a4bb7c.png)

> Do you want to Telegram to replace your system's glibc? I guess snapd won't allow that...

What is relation to mine system glibs?! I want whether snap or telegram team fixed this [long term issue](https://forum.snapcraft.io/t/acestreamplayer-mpv-stopped-to-work-glibc-error/23061/6) as it intended to install and work in openSUSE Tumbleweed: https://snapcraft.io/install/telegram-desktop/opensuse - and it worked.

**Comment by ilya-fedin** [comment]
> Are You from telegram team?

I'm not from Telegram team, but I'm the contributor who does most of the Linux-specific work (including changes to snapcraft.yaml).

> What is relation to mine system glibs?!

From what I see, snapd bind mounts system's GL libraries that are linked to system glibc. You glibc is newer than core20's (that is based on libraries from Ubuntu 20.04) glibc, so it doesn't work. tdesktop can't fix core20 nor your system, so there's no way to fix that from tdesktop side.

**Comment by akontsevich** [comment]
>The only thing I can suggest is to migrate to official binary from https://desktop.telegram.org or to flatpak package.

The reason I choose the snap - because tray icon works correctly only there: https://bugs.telegram.org/c/3173

**Comment by ilya-fedin** [comment]
That's false, it works in all the three official builds (static binary, flatpak, snap)

**Comment by ilya-fedin** [comment]
Ah, you're talking about red counter. No, it's lack is a correct behavior, while snap packages lack system theming support.

**Comment by akontsevich** [comment]
> That's false, it works in all the three official builds (static binary, flatpak, snap)

That is true - run it in SUSE: unread messages count visible only with the snap build.

**Comment by ilya-fedin** [comment]
As I said, it's not true, what you saw is the correct behavior. You may not like it, but that's how it works now. If Canonical will once provide system icon theme support to snap, it will behave just like other builds.

**Comment by akontsevich** [comment]
> As I said, it's not true, what you saw is the correct behavior. You may not like it, but that's how it works now. If Canonical will once provide system icon theme support to snap, it will behave just like other builds.

It is VERY inconvenient and stupid.

**Comment by ilya-fedin** [comment]
Well, many people (including me) like that

**Comment by akontsevich** [comment]
Also flatpack version stores settings in different folder - so all the settings are lost which is also very inconvenient and stupid. WHy they can't store all the settings in one place?

**Comment by akontsevich** [comment]
theme icon is ugly.

**Comment by ilya-fedin** [comment]
> Also flatpack version stores settings in different folder - so all the settings are lost which is also very inconvenient and stupid. WHy they can't store all the settings in one place?

Both flatpak and snap are proposed by their authors as sandboxed, so flatpak packages have their own XDG dirs, snap packages have their own home directories.

> theme icon is ugly.

It's a question to the authors of system icon theme you're using. Maybe you should choose another one.

**Comment by akontsevich** [comment]
Also snap updates automatically with `zypper dup`, flatpack - no.

**Comment by ilya-fedin** [comment]
Are you sure? AFAIK it automatically checks updates without integration to system package manager. And you can't disable that.

**Comment by akontsevich** [comment]
thanks

**Comment by ilya-fedin** [comment]
@akontsevich I see there was a snap build on edge channel today, does it work?

**Comment by akontsevich** [comment]
no: https://forum.snapcraft.io/t/telegram-desktop-stopped-to-work-in-suse-tumbleweed-glibc-error/26741/9

**Comment by ilya-fedin** [comment]
Are you sure you're on edge channel with version 3.1.4-beta-3-gf0e8c1e32?

**Comment by akontsevich** [comment]
No, I'm on stable 3.1.1

**Comment by ilya-fedin** [comment]
But I said multiple times that I'm talking about edge channel. You won't see the difference on stable channel.

**Comment by akontsevich** [comment]
Yes, edge works.

**Comment by ilya-fedin** [comment]
ok, thanks for testing
