### ISSUE TITLE
Display off after time in Videochat

### ISSUE THREAD

**Issue by Manaplayer** [telegramdesktop/tdesktop#17007]
### Steps to reproduce

Set time in Energy-option of Windows when display should be off if you do input.
Do Videochat. Display is off after this time.
If i am watching youtube or another with no input, the display is always on.

### Expected behaviour

The display should not be off, or make it a setable option.

### Actual behaviour

The display goes off

### Operating system

Windows 10 21H1 64bit

### Version of Telegram Desktop

3.1.1 64bit

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7790
