### ISSUE TITLE
[Windows] Keep screen active when playing video

### ISSUE THREAD

**Issue by yunfandev** [telegramdesktop/tdesktop#17019]
### Steps to reproduce

Windows 10

- Settings -> System -> Power & Sleep -> Set screen turn off to 1 min

Playing a video and then don't interaction with the computer in 1 mins.

### Expected behaviour

Keep screen active when playing video

### Actual behaviour

Screen turned off.

### Operating system

Windows

### Version of Telegram Desktop

3.1

### Installation source

Microsoft Store

**Comment by ilya-fedin** [comment]
#7790
