### ISSUE TITLE
Telegram does not send SMS to register in the system

### ISSUE THREAD

**Issue by akontsevich** [telegramdesktop/tdesktop#17017]
### Steps to reproduce

Since snap version stopped to work forced to install flatpack or official rpm version, however can't register in the system any more.

1. Install telegram via flatpack or rpm
2. Press send SMS on start - nothing happens

Have only regular cell phone (non-Android) currently for the number.

### Expected behaviour

receive activation code

### Actual behaviour

nothing happens

### Operating system

Linux openSuse Tumbleweed

### Version of Telegram Desktop

3.1.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Use search and find other issue regarding this, this is one another duplciate.

**Comment by Aokromes** [comment]
server side limitation, you can get kotatogram to workaround it.

**Comment by akontsevich** [comment]
> Use search and find other issue regarding this, this is one another duplciate.

Why could not You link them here?

**Comment by ilya-fedin** [comment]
I'm too lazy

**Comment by akontsevich** [comment]
> server side limitation, you can get kotatogram to workaround it.

@Aokromes how if it is a server side problem?!

**Comment by ilya-fedin** [comment]
They blacklisted official API_IDs of desktop & web clients

**Comment by akontsevich** [comment]
> > server side limitation, you can get kotatogram to workaround it.
> 
> @Aokromes how if it is a server side problem?!

Эта дрянь вообще не работает.

**Comment by ilya-fedin** [comment]
Try to pray to sever devs for forgiveness

**Comment by ilya-fedin** [comment]
The thing is, you can't use Telegram without a smartphone now, just like other messengers. You can try workarounds like third-party clients, but the may stop log in (if not already) at any moment as well

**Comment by akontsevich** [comment]
> The thing is, you can't use Telegram without a smartphone now, just like other messengers. You can try workarounds like third-party clients, but the may stop log in (if not already) at any moment as well.

Спасибо, заработало, смогли войти пока что.

**Comment by ediowar** [comment]
> If you are having registration or login problems, please contact us using this form.

https://telegram.org/faq#login-and-sms
