### ISSUE TITLE
Telegram notifications don't disappear when watching full screen videos

### ISSUE THREAD

**Issue by lukasged** [telegramdesktop/tdesktop#17014]
### Steps to reproduce

1. Watch a video (Netflix/YouTube) on you browser (Firefox/Chrome) in full screen mode;
2. Receive a message with the notifications enabled;
3. Continue watching full screen and see that the message window stays visible;

### Expected behaviour

Notification should appear on the corner of the screen and fade away in a few seconds;

### Actual behaviour

Notification stays on the screen until you dismiss it by clicking 'x';

### Operating system

Windows 10

### Version of Telegram Desktop

3.1.1

### Installation source

Static binary from official website

**Comment by lukasged** [comment]
This bug report is pretty much a re-open of https://github.com/telegramdesktop/tdesktop/issues/7855 opened in May 2020, but the issue is still there unfortunately.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2290 ?

**Comment by lukasged** [comment]
> #2290 ?

Yes I guess it's the same issue, just more general, not related to games only.

**Comment by lukasged** [comment]
I guess I will just enable native notifications instead, but I'd prefer Telegram notifications that would just fade away by themselves.
