### ISSUE TITLE
Local password + multiple accounts == broken "Log out" feature

### ISSUE THREAD

**Issue by ratijas** [telegramdesktop/tdesktop#17016]
### Steps to reproduce

1. Login from at least two accounts.
2. Set local password on Telegram Desktop.
3. Lock the app.
4. Forget your password.
5. Resort to "Log out" option on the lock screen.

### Expected behaviour

Telegram Desktop should log you out of all connected accounts, and present you with a landing page.

### Actual behaviour

Dialog "Are you sure?" stuck on a screen, the dangerously red "Log out" button can be clicked but it does seemingly nothing.

### Operating system

Windows 10

### Version of Telegram Desktop

3.0.1.0

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Thanks! I'll fix that in the next version. Broken even with a single account - till relaunch :(
