### ISSUE TITLE
[Feature Request] Add an increase in the size of the uploaded file

### ISSUE THREAD

**Issue by ediowar** [telegramdesktop/tdesktop#17012]
### Is your feature request related to a problem?

Probability of determining the IP by the size of the downloaded file and the time of its download.

### Describe the solution you'd like

Add an increase in the size of the uploaded file by a randomly generated percentage and a delay in publishing the file for a randomly generated time.

### Describe alternatives you've considered

Allow the user to leave an Internet link to the file from the file storage services so that the server can download the file itself.

**Comment by Aokromes** [comment]
do you realize that a lot of files NEEDS to be the size they where uploaded or they will break?

**Comment by ediowar** [comment]
> do you realize that a lot of files NEEDS to be the size they where uploaded or they will break?

The client part packs the file together with randomly generated files into one archive with the possibility of checking its integrity on the server part.

**Comment by Aokromes** [comment]
> > do you realize that a lot of files NEEDS to be the size they where uploaded or they will break?
> 
> The client part packs the file together with randomly generated files into one archive with the possibility of checking its integrity on the server part.

and if someone uploads multiple files with the max supported size?

**Comment by ediowar** [comment]
The client side should keep track of not exceeding the limits.
It's easier to implement the alternative though. What about it?

**Comment by Aokromes** [comment]
> The client side should keep track of not exceeding the limits.
> It's easier to implement the alternative though. What about it?

if file is already max syze how your request will work?

**Comment by ediowar** [comment]
Just like working with archives. Creating volumes.
