### ISSUE TITLE
Sound gone!

### ISSUE THREAD

**Issue by anarchotaoist** [telegramdesktop/tdesktop#17018]
### Steps to reproduce

Click play on video.
No sound plays.
Click 3 dot menu -see desktop icon is muted
Click desktop icon to unmute
No change

### Expected behaviour

Play video.
Hear video.

### Actual behaviour

Play video and no sound.

### Operating system

Kubuntu 20.10

### Version of Telegram Desktop

deb 2.6.1 &  Flatpak 3.1.1

### Installation source

Other (unofficial) source

**Comment by anarchotaoist** [comment]
I have purged the deb.
I installed the flatpak.
This made no difference.
I removed all files from .local.
Still no sound!

**Comment by ilya-fedin** [comment]
> Click 3 dot menu -see desktop icon is muted

What desktop icon are you talking about?

**Comment by anarchotaoist** [comment]
Hello!
I just solved the issue.
I was able to minimise/disconnect the video.
Then with sound playing I could then see it in the desktop audio settings.
It was muted. After turning up the volume in the desktop sound settings it was then working again.
Thanks for the reply!

Kubuntu 21.04
