### ISSUE TITLE
Media downloads stutter on network file systems

### ISSUE THREAD

**Issue by m3thm4th** [telegramdesktop/tdesktop#17027]
### Steps to reproduce

Download any file on network mount points

### Expected behaviour

Downloads should not stutter

### Actual behaviour

Downloading files stutters and its very slow when the download folder is set to be a network mount in Linux. I tried to download to external drives and no issue there. This has been going for several releases of Telegram, since version 1.x.x

### Operating system

Linux

### Version of Telegram Desktop

3.1.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#16862?
