### ISSUE TITLE
[Feature Request] Add :debian: alias to 🍥 (fish_cake) emoji

### ISSUE THREAD

**Issue by MikeWent** [telegramdesktop/tdesktop#17023]
### Is your feature request related to a problem?

It's often needed in conversations to refer to Debian, and there is a convenient emoji for this purpose: 🍥. 

### Describe the solution you'd like

For example, in Telegram `:ass:` and `:dick:`  keywords are replaced with corresponding visual 🍑 (peach) and 🍆 (eggplant),  a replacement of `:debian:` with 🍥 (fish_cake) would be a nice feature, I think. 

### Describe alternatives you've considered

I considered stopping referring to Debian, but it's nearly impossible because of its popularity.

**Comment by aprosvetova** [comment]
Please suggest here: https://translations.telegram.org/en/emoji

**Comment by MikeWent** [comment]
> Please suggest here: https://translations.telegram.org/en/emoji

Already done.
