### ISSUE TITLE
'Use System Window Frame' option missing when setting QT to wayland only

### ISSUE THREAD

**Issue by EncryptedCicada** [telegramdesktop/tdesktop#17026]
### Steps to reproduce

1. Set setting 'Use system window frame' to true in advanced settings (confirmed working).
2. use export QT_QPA_PLATFORM=wayland in ~/.bash_profile to let QT apps use wayland only.
3. After a logout login cycle, telegram window frame reverts to the one provided by the application.
4. The setting toggle 'Use system window frame is missing' now.

### Expected behaviour

Setting export QT_QPA_PLATFORM=wayland should not let telegram reset window frame to default and the setting to use system window frame should still be available.

### Actual behaviour

Setting export QT_QPA_PLATFORM=wayland makes telegram revert to default window frame and the setting to use system window frame is missing. Right click to open menu is bugged in this state too as it stays there for only as long as the right click is pressed.

### Operating system

Arch Linux (linux-zen 5.14.6)

### Version of Telegram Desktop

v3.1.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
If you have no such option, that means your compositor doesn't provide a 'system' frame (doesn't support xdg-decoration protocol), server-side decorations are optional on Wayland and Telegram can't fix the people who designed the protocol.
