### ISSUE TITLE
CMake error while trying to build from source files

### ISSUE THREAD

**Issue by surajsjain** [telegramdesktop/tdesktop#17039]
### Steps to reproduce

I was trying to build the app from the source files using CMake. For that, I did the following:
1. I cloned the repo
2. Created a directory named `build/`
3. Switched to the directory named `build/`
4. Ran the command `cmake ..`

### Expected behaviour

It should have passed and allowed me to run the `make` command.

### Actual behaviour

Running `cmake` threw the following error:
```
CMake Error at CMakeLists.txt:13 (include):
  include could not find load file:

    cmake/validate_special_target.cmake


CMake Error at CMakeLists.txt:14 (include):
  include could not find load file:

    cmake/version.cmake


CMake Error at CMakeLists.txt:15 (desktop_app_parse_version):
  Unknown CMake command "desktop_app_parse_version".
```

### Operating system

macOS Big Sur 11.6

### Version of Telegram Desktop

6adf791b3b054317197227ca1bb2852ef8f23963

### Installation source

Other (unofficial) source

**Comment by john-preston** [comment]
@surajsjain It is not supposed to work that way. There are build instructions in the main README.

**Comment by surajsjain** [comment]
Got it, thanks!
