### ISSUE TITLE
[Linux] Telegram jumps to another workspace on notification click 

### ISSUE THREAD

**Issue by MrXlebNick** [telegramdesktop/tdesktop#17036]
### Steps to reproduce

1. Use POP OS 21.04
2. Open Telegram on workspace 1 
3. Go to workspace 2
4. Wait for a message notification to appear, then click it 

### Expected behaviour

Workspace 1 is shown with Telegram opened

### Actual behaviour

Telegram jumps to

### Operating system

POP OS 21.04, GNOME 3.38.5, X11

### Version of Telegram Desktop

2.6.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
> 2.6.1

Old versions aren't supported, update to the latest one

**Comment by ilya-fedin** [comment]
I see 2.6.1 in Ubuntu 21.04 repositories, so don't use flatpak package. Pleas use you distro bugtracker to report bugs about distro packages instead.

**Comment by RememberTheAir** [comment]
I use gnome and pop-shell too, I've always assumed it was the intended behavior, especially when you have your windows nicely tiled and non-minimized to tray
