### ISSUE TITLE
[Feature Request] When I send a message in a group - don't jump to it

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#17032]
### Is your feature request related to a problem?

I am reading messages in a group and want to respond to one of them, and if I do - it jums to the end, marking all of messages as read, and I lose the place where I was reading in that group chat.

### Describe the solution you'd like

Don't jump to the sent message, when it's sent.

### Describe alternatives you've considered

Not answering as I read is not an alternative, it's awfully inonvenient.

### Additional context

I really don't see the benefit of jumping to the sent message.

**Comment by ilya-fedin** [comment]
> and I lose the place where I was reading in that group chat.

You can create on the quote and it will return you to that place
