### ISSUE TITLE
[Feature Request] Client should ask if the user wants to delete the messages for the bot.

### ISSUE THREAD

**Issue by ingroxd** [telegramdesktop/tdesktop#17033]
### Is your feature request related to a problem?

Kind of.

Telegram APIs have a special error for deleted messages when you try to edit them.
On previous versions of some bots, it would be sufficient to search for that error (`BadRequest` to be more precise, with "Message to edit not found" message).

When deleting a message, the client should ask if the user wants to delete the messages for the bot.

### Describe the solution you'd like

Ask the users if they also want to delete the message for the bot.

Other clients already asks for it:
- `K` Web client does it through a check box before confirmation;
- `Z` Web client does it through a "delete for me and <bot_name>" button;

### Describe alternatives you've considered

I've considered changing client, like `K` or `Z` web clients which support this option

### Additional context

Telegram APIs has a special error for deleted messages when you try to edit them.
In particular you receive a `BadRequest` error with "Message to edit not found" message.

Not asking the user to delete the message for the bot too, nullifies this error and blinds the bot (because the message doesn't cease to exist for it).

**Comment by MasterGroosha** [comment]
I'm not sure how "Delete for {bot}" button will help in this case. There is literally no sense for this option, because you cannot revoke message from bot. Bots don't have access to message history and are able to store every message anywhere outside Telegram

refer to: #3818

**Comment by john-preston** [comment]
@MasterGroosha Really I think apps should always delete messages for bots as well. If bot needed it saved the message anyway. No option needed, but the behavior should be changed. I think.

**Comment by RememberTheAir** [comment]
I agree with what @john-preston said, there should be no checkbox but the app should always ask the server to revoke the message - bots cannot access a chat's history using the methods exposed by the bot API, but nowadays it's extremely trivial to connect directly through mtproto and use methods such as `getMessage`

**Comment by ingroxd** [comment]
Deleting it without choice is actually better, I agree
