### ISSUE TITLE
Can't configure cmake due to tg_owtconfig not being found

### ISSUE THREAD

**Issue by Foxtrot-Uniform** [telegramdesktop/tdesktop#17047]
1. Install Debian Sid
2. git clone --recursive https://github.com/telegramdesktop/tdesktop.git then cd into it and Get all the dependancies from the sid repo non-free contrib main (and build rnnoise from source because apparently it's trained using propiretary programs)
3. cmake-gui
4. Get this
`Version: 3.1.5.beta
Checking for module 'hunspell'
  No package 'hunspell' found
Checking for module 'jemalloc'
  No package 'jemalloc' found
Checking for module 'liblz4'
  No package 'liblz4' found
Checking for module 'minizip'
  No package 'minizip' found
CMake Error at cmake/external/webrtc/CMakeLists.txt:11 (find_package):
  By not providing "Findtg_owt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "tg_owt", but
  CMake did not find one.

  Could not find a package configuration file provided by "tg_owt" with any
  of the following names:

    tg_owtConfig.cmake
    tg_owt-config.cmake

  Add the installation prefix of "tg_owt" to CMAKE_PREFIX_PATH or set
  "tg_owt_DIR" to a directory containing one of the above files.  If "tg_owt"
  provides a separate development package or SDK, be sure it has been
  installed.

Configuring incomplete, errors occurred!
See also "/home/mesut/tdesktop/buil/CMakeFiles/CMakeOutput.log".
See also "/home/mesut/tdesktop/buil/CMakeFiles/CMakeError.log".`

To be frank I am not really much of a coder and only know a few basic things.

**Comment by john-preston** [comment]
@Foxtrot-Uniform I'm not sure you should build it 🙄

But if you really want, I suggest you to follow the instructions from the main README.
