### ISSUE TITLE
After switching accounts, there are no focused elements, all input goes nowhere

### ISSUE THREAD

**Issue by ratijas** [telegramdesktop/tdesktop#17042]
### Steps to reproduce

1. Login from two accounts
2. Open chat list view (main view of the app when logged in)
3. Focus on a search field, e.g. by clicking on it; but normally it should already be focused.
4. Using mouse, open a hamburger menu from the top left, and click on the other account.

### Expected behaviour

After switching accounts, focus should be back at the search field.

### Actual behaviour

Focus is lost, no elements are active, typing keys does nothing: Up/Down does not select chats, normal "text" keys won't go into the search field. And only Tab key can bring the focus back to the search field.

### Operating system

Arch Linux (2021-09-29), KDE 5.87.0 / Plasma 5.23.80

### Version of Telegram Desktop

3.1.1-1

### Installation source

Other (unofficial) source

**Comment by ratijas** [comment]
hello? ping?

**Comment by ratijas** [comment]
Please, I request some prioritization. This should be relatively easy to fix, while it's causing big pain in UX for daily regular account switching. @john-preston @ilya-fedin

**Comment by ilya-fedin** [comment]
Personally I don't use hotkeys, if this an urgent problem for you, you can fix it yourself and PR the fix

**Comment by ratijas** [comment]
It's not about hotkeys, actually. It's just that the normal search and up/down arrows (and yes — the hotkeys like Ctrl+F too) aren't working unless you do something to reinforce focus, like press Tab once or switch back-and-forth between applications.

Theoretically I could've fixed it myself, but I have approximately zero knowledge of the code base (which is huge and full of kinda DSL-like libraries now). So, time-wise it would be quite inefficient if I tried myself (:

**Comment by ilya-fedin** [comment]
I don't use arrow keys to navigate, I use the mouse

**Comment by ilya-fedin** [comment]
> Theoretically I could've fixed it myself, but I have approximately zero knowledge of the code base

Not like I know entire codebase. I know mostly the platform code.

**Comment by 23rd** [comment]
> This should be relatively easy to fix

Yes, it is. Thanks for your report, it will be fixed in the next release.

**Comment by ratijas** [comment]
> Yes, it is. Thanks for your report, it will be fixed in the next release.

Oh, cool! Thanks.

While you are at it, could you, please, also take care of the button's sizing as well? #17423

**Comment by ratijas** [comment]
This is now fixed.  Thanks!
