### ISSUE TITLE
Adding test server account is not working on macOS Monterey beta 8

### ISSUE THREAD

**Issue by D4v1dH03** [telegramdesktop/tdesktop#17044]
Telegram desktop version: 8.1.2 (222017) Beta
OS version: macOS 12 (Monterey) beta 8
Steps to reproduce:
1. While pressing Option+Shift key, right click (double finger tap) on the touchpad
2. Nothing happens, no context menu pops up, and even if a window pops up it says the account is already logged in
(obviously it is still logging in the prod server account, not the test server account)

**Comment by ilya-fedin** [comment]
As you can see at https://github.com/telegramdesktop/tdesktop/releases, latest version of tdesktop is 3.1.1, whatever you're using is not tdesktop

**Comment by D4v1dH03** [comment]
Oops sorry!
