### ISSUE TITLE
[Feature Request] Remove chats from folders after archiving

### ISSUE THREAD

**Issue by asdf2107** [telegramdesktop/tdesktop#17049]
### Is your feature request related to a problem?

Yes, when I archive a chat, it does not get removed from folders

### Describe the solution you'd like

After archiving a chat, it would get removed from all folders

### Describe alternatives you've considered

Add an option to archive chat and remove it from all folders in right-click menu

**Comment by RememberTheAir** [comment]
Folders' settings allow you to exclude archived chats. This works just for folders you didn't include manually (or pin at the top of the list), because manual inclusion has priority over exclusionary filters (as it should be imo)

**Comment by asdf2107** [comment]
Oh, thanks, didn't know about it
