### ISSUE TITLE
sent messages are on the left hand side

### ISSUE THREAD

**Issue by Hi1307** [telegramdesktop/tdesktop#17056]
### Steps to reproduce

1. Open any PM or group chat

### Expected behaviour

Messages that I sent will be on the right side of the chat window

### Actual behaviour

Messages that I sent are on the left side of the chat window

### Operating system

Windows 11 21H2

### Version of Telegram Desktop

3.1.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
disable adaptative layout on settings.
