### ISSUE TITLE
The text displayed in different monitors is not scaled

### ISSUE THREAD

**Issue by Joricde** [telegramdesktop/tdesktop#17052]
### Steps to reproduce

In the multi-monitor setup, if the screen is two monitors with different resolutions (one high resolution and one low resolution). The two screens use different zoom ratios. For example, high-resolution screens use 200%, and low-resolution screens use 125%. When the telegram client moves between two screens.

### Expected behaviour

The client text should be automatically adjusted with the screen zoom ratio

### Actual behaviour

- The text is not scaled, resulting in moving from a normal low-resolution display to a high-resolution monitor, the text is too small to be comfortable to browse.  
- 125% on the left ( low-resolution display ), 200% on the right ( hight-resolution display ) 
![L-125%_R-200%](https://user-images.githubusercontent.com/56040074/135739496-9c97dacb-1c0f-4cfb-9fe3-ac3c6eb87345.png)

### Operating system

window 10

### Version of Telegram Desktop

Version 3.1.1

### Installation source

Static binary from official website

### Logs

```shell
No response
```

**Comment by ilya-fedin** [comment]
#1121
