### ISSUE TITLE
Blocked user and sticker

### ISSUE THREAD

**Issue by AkaiRep** [telegramdesktop/tdesktop#17059]
### Steps to reproduce

1. block user
2. send sticker

### Expected behaviour

You can`t send stickers to blocked user

### Actual behaviour

You can send stickers to blocked user

### Operating system

windows 10

### Version of Telegram Desktop

3.1.1 x64

### Installation source

Static binary from official website

**Comment by AkaiRep** [comment]
Not actual now

**Comment by Aokromes** [comment]
not a bug, it works like that.

**Comment by AkaiRep** [comment]
still work

**Comment by AkaiRep** [comment]
still work
