### ISSUE TITLE
text alignment is not automated

### ISSUE THREAD

**Issue by HamidrezaZMN** [telegramdesktop/tdesktop#17054]
### Steps to reproduce

1. right_ctrl+right_shift -> aligns text to right
2. left_ctrl+left_shift -> aligns text to left
(you have to do it two/three times continuously so it works)

### Expected behaviour

Automatically align text to the side its needed. if it's Persian/Arabic/... it'll be RTL. else it'll be LTR

### Actual behaviour

It does align to the side I chose, but doesn't auto align when typing in a the opposite side language (the alignment stucks to the side I chose once).
It sometimes, randomly gets fixed. But I don't know how should I do that myself. and I suppose it's a bug, cause I didn't even find this "ctrl+shift" shortcut in the telegram shortcuts page.
![-2147483648_-214803](https://user-images.githubusercontent.com/56170822/135748347-47152479-6d15-47c0-af80-05d3e0542f54.jpg)

### Operating system

Microsoft Windows 10 Home | 10.0.19042 N/A Build 19042

### Version of Telegram Desktop

Version 3.1.1 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#9922?

**Comment by HamidrezaZMN** [comment]
> #9922?

I think that's actually another problem. because, for example if my problem gets solved, the thing that happens is that when they type that sentence, it auto-aligns the input text to left, so the output (sent message) is the same as what they wrote. but they actually want to write in RTL and the output be exactly the same as input.
I think you should add a shortcut keyboard so when we press that it auto-aligns whatever input we send. but if we used ctrl+shift, it doesnt auto align and also sends the exact input they wanted.

**Comment by ilya-fedin** [comment]
> if we used ctrl+shift

I don't understand what do you mean by that part?

**Comment by HamidrezaZMN** [comment]
> I don't understand what do you mean by that part?

like the "Steps to reproduce" in the question. when i press them, the alignment stucks to that part. it randomly gets fixed and as i type (for example) in Persian, it detects the language and aligns the input to right, and when i type in English, it aligns the input to left. But as soon as i do those steps, the alignment stucks to the side i chose (same as the picture i attached)

**Comment by ilya-fedin** [comment]
> like the "Steps to reproduce" in the question

These hotkeys do nothing... And if they would do anything how people would use e.g. Ctrl+Shift+Z or Ctrl+Shift+M?

**Comment by HamidrezaZMN** [comment]
> how people would use e.g. Ctrl+Shift+Z or Ctrl+Shift+M?

That usually doesn't happen by doing it once. like, i have to try it 2 or 3 (continuously) so it works. I have asked my friends and they have the same problem too.

**Comment by ilya-fedin** [comment]
I guess this is something specific to your locale, this doesn't happen to me like it happens to you

**Comment by HamidrezaZMN** [comment]
> I guess this is something specific to your locale, this doesn't happen to me like it happens to you

Aha. But it's also mentioned it #9922's question too:
> in cases that user switch the direction and determine it by (CTRL+SHIFT keys)

**Comment by ilya-fedin** [comment]
>  But it's also mentioned it #9922's question too:

Still, it does nothing for me...
