### ISSUE TITLE
Tell us who left the group

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#17051]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I'd like to be able to see who's left the group and when. I don't know why you show when people come into the group, but not when they leave.

I have no clue who comes and goes and I really need to be able to see that.

Sometimes even though people come into the group, my total members number stays the same which confuses me and I'm sure the members.

I heard that you only allow this for groups under X members and I don't understand why. It's no different than showing people who come in and what happens if the same person joins, leaves, joins, leaves, etc. I would never know that.

Thanks

### Describe alternatives you've considered

NA

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by ILoveSkilledCoders** [comment]
Oh, so it's a bug, not something they purposely left out?

**Comment by ILoveSkilledCoders** [comment]
I don't this listed anywhere in that list. Please give me the link

**Comment by ilya-fedin** [comment]
> Oh, so it's a bug, not something they purposely left out?

No, it's not a bug, this issue tracker is only for tdesktop-specific bugs or feature requests. https://bugs.telegram.org is the place for platform-wide bugs/feature requests.

**Comment by ilya-fedin** [comment]
> I don't this listed anywhere in that list.

If it's not then you can create a new one.
