### ISSUE TITLE
Open emotions/stiker bar by Tab

### ISSUE THREAD

**Issue by SergeyAlekseevN** [telegramdesktop/tdesktop#1706]
Pressing the Tab key opens the panel sticker.

**Comment by DaFri-Nochiterov** [comment]
:+1: +1
<kbd>Tab</kbd> (Single press) - Open Emoji menu
<kbd>Tab</kbd> (In Emoji menu _or ultraDoubleTabPressing_) - Open Stickers menu
<kbd>Shift</kbd> + <kbd>**←**</kbd> (in Stickers menu, when focused at first sticker pack) - Open GIFs menu
<kbd>Shift</kbd> + <kbd>**→**</kbd> (in Stickers menu) - Next sticker pack
<kbd>Shift</kbd> + <kbd>**←**</kbd> (in Stickers menu) - Previous sticker pack
<kbd>Shift</kbd> + <kbd>**→**</kbd> (in GIFs menu) - Back to the stickers
<kbd>**↑**</kbd><kbd>**↓**</kbd> - Move Up / Move Down
<kbd>**←**</kbd><kbd>**→**</kbd> - Move Left / Move Right
<kbd>SPACE</kbd> - Insert Emoji (no menu closing) / Send Sticker or GIF (and close menu)
<kbd>Esc</kbd> - Close menu

**Comment by rplansky** [comment]
:+1: +1
