### ISSUE TITLE
open files ignore xdg-mime settings

### ISSUE THREAD

**Issue by 13werwolf13** [telegramdesktop/tdesktop#17064]
### Steps to reproduce

1. send/receive file via telegram
2. open file from telegram

### Expected behaviour

pdf open in okular, text open in kate, etc

### Actual behaviour

pdf open in libreoffice, text open in WINE NOTEPAD.EXE!!!
however, if you open from the file manager or any other application, then the files open as expected

### Operating system

openSUSE Tumbleweed Plasma

### Version of Telegram Desktop

https://build.opensuse.org/package/show/home:Dead_Mozay:telegram/telegram-desktop

### Installation source

Other (unofficial) source

### Logs

```shell
[werwolf@work] ~  
❯ telegram-desktop 

(telegram-desktop:21644): Telegram-WARNING **: 10:00:46.795: Application was built without embedded fonts, this may lead to font issues.
Gtk-Message: 10:00:46.991: Failed to load module "appmenu-gtk-module"
[ALSOFT] (EE) Failed to set real-time priority for thread: Операция не позволена (1)
error: : cannot open
error: : cannot open
error: : cannot open
qt.svg: Error while inflating gzip file: SVG format check failed
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
/usr/bin/atom: строка 190: 21721 Недопустимая инструкция                     (стек памяти сброшен на диск) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
Gtk-Message: 10:01:05.540: Failed to load module "appmenu-gtk-module"
[21721:1006/100106.003852:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
--2021-10-06 10:01:06--  https://atom.io/crash_reports
Распознаётся atom.io (atom.io)… 52.202.168.65, 54.161.241.46, 54.237.133.81, ...
Подключение к atom.io (atom.io)|52.202.168.65|:443... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 204 No Content
2021-10-06 10:01:07 (0,00 B/s) - «/dev/fd/4» сохранён [0]


Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
--2021-10-06 10:01:07--  https://atom.io/crash_reports
Распознаётся atom.io (atom.io)… 52.202.168.65, 54.161.241.46, 54.237.133.81, ...
Подключение к atom.io (atom.io)|52.202.168.65|:443... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 204 No Content
2021-10-06 10:01:08 (0,00 B/s) - «/dev/fd/4» сохранён [0]


Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
^C
```

**Comment by ilya-fedin** [comment]
tdesktop uses glib library that implements XDG specification to open files. If you think it works incorrectly, file a bug for glib.

**Comment by ilya-fedin** [comment]
It's reproducible only in Telegram because you don't use non-KDE applications, I guess. Also, as far as I know, openSUSE patches Firefox to use KDE's mime system rather than XDG. Try Firefox build from Mozilla's website and I'm sure you will see the same behavior.

**Comment by ilya-fedin** [comment]
Or try any program from flatpak. Portals use glib, too.

**Comment by ilya-fedin** [comment]
It seems to me actual bug is in xdg-mime. glib implements XDG spec in the right way, but xdg-mime calls DE-specific binaries for some reason. And, apparently, in KDE, since they violate the XDG spec.
https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/193
