### ISSUE TITLE
Use cloud service in download and upload

### ISSUE THREAD

**Issue by Amirmohammadkazemi** [telegramdesktop/tdesktop#17060]
### Is your feature request related to a problem?

Hi. I have been working with Telegram since the beginning and I must say it is great. But if possible, put a service that we can choose which cloud service to save when downloading.
This will always be available.
Or if possible, publish your own cloud service to make it easier.

### Describe the solution you'd like

To do this, you can connect to Google Drive, Dropbox or Mega accounts and use it when you want to download or upload a file.

### Describe alternatives you've considered

If Telegram can provide cloud storage service, it will both generate good revenue for Telegram and make our work easier.

Rest assured it will be very welcome.

### Additional context

Thank you for caring about people's and users ideas.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
