### ISSUE TITLE
Telegram won't close when clicking on the close button

### ISSUE THREAD

**Issue by mooms06** [telegramdesktop/tdesktop#17063]
### Steps to reproduce

Open Telegram, close it with the red cross, the application will be hidden but not closed, you can see it in the task manager, and you will still receive notifications.

### Expected behaviour

Telegram should close when I close it

### Actual behaviour

It does not

### Operating system

Windows 10 21H1 x64 French

### Version of Telegram Desktop

3.1.1

### Installation source

Static binary from official website

**Comment by mooms06** [comment]
I installed 3.1.1 from scratch, after uninstalling it, still the same behavior.

**Comment by Aokromes** [comment]
disable show tray icon on settings to have it full closed.

**Comment by mooms06** [comment]
Thanks, it was that.

It should be more obviously stated though.
