### ISSUE TITLE
the voice note being played is not stopped when a new voice note is sent

### ISSUE THREAD

**Issue by Emanuele-1998** [telegramdesktop/tdesktop#17066]
### Steps to reproduce

go in private chat or group where there is a voice note
play the voice note and send a voice note, the audio of the voice note played will not be blocked

### Expected behaviour

when a previous voice note is produced and I am sending a new voice note, I expect the old voice note to stop playing

### Actual behaviour

play the voice note and send a voice note, the audio of the voice note played will not be blocked

### Operating system

Windows 11 Pro 21H2 Build 22000.194

### Version of Telegram Desktop

3.15 beta X64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
i don't think this is a bug, why anyone will want to be listening one audio to be interrupted?

**Comment by Emanuele-1998** [comment]
> i don't think this is a bug, why anyone will want to be listening one audio to be interrupted?

I mean that when I send a voice note and a voice note is playing it is annoying that it doesn't stop

**Comment by dreamwhite** [comment]
I can confirm on my side that on macOS Big Sur 11.6 (20G165) with Telegram Desktop v3.1.1 I can reproduce the bug.

> i don't think this is a bug, why anyone will want to be listening one audio to be interrupted?

I think you misunderstood the issue. It's not a matter of listening the audio itself, but rather a matter of "why should a vocal note be played while I'm recording a vocal message? What's the point of doing so?".
