### ISSUE TITLE
Can't copy @test with link-markdown because of hashtag

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#17074]
### Steps to reproduce

Can't copy @test with link-markdown if hashtag #test is written next

1. Write @test and make link on it
2. Next write #test
3. Send it
4. Try to copy @test with link
5. You can't because of hashtag

Example https://t.me/testtesttesttesttesttesttest001/2

https://user-images.githubusercontent.com/39812401/136440847-9d41a0dc-aa2a-45c9-b86d-027acb7ae230.mp4

### Expected behaviour

I can copy @test with link markdown in any case

### Actual behaviour

I can't copy @test with link markdown if hashtag #test is written next

### Operating system

Windows 10

### Version of Telegram Desktop

3.1.7 Beta

### Installation source

Static binary from official website

**Comment by frostmorn** [comment]
Also found that hashtag also seeks for a messages where hashtag is inside markdown quote.
Could be a feature, but I suppose it's a bug, cause it doesn't seemed to be logical.

**Comment by Neurotoxin001** [comment]
`+`

**Comment by Neurotoxin001** [comment]
Still bugged

**Comment by Neurotoxin001** [comment]
fixed
