### ISSUE TITLE
Views count disappears after media edit

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#17073]
### Steps to reproduce

1. Post media (photo/video) in channel
2. Edit media (replace it with other or same photo/video)
3. Save
4. Views count disappears

Only restart helps. Also I have question. Do you read https://bugs.telegram.org? Because I was reported it there 24 sep:
https://bugs.telegram.org/c/9586

### Expected behaviour

Views count should not disappears after media edit

### Actual behaviour

Views count disappears after media edit

### Operating system

Windows 10

### Version of Telegram Desktop

3.1.7 Beta

### Installation source

Static binary from official website

### Logs
https://user-images.githubusercontent.com/39812401/136439968-294ca68a-78ca-4f25-9e5e-9f074fb524dd.mp4

_No response_

**Comment by Neurotoxin001** [comment]
Don't know how to reproduce, but here is another example of this bug:
https://t.me/c/1237513492/21432 (join link https://t.me/joinchat/ScL1FOCgJCbFNJK1)
![image](https://user-images.githubusercontent.com/39812401/136809646-7038b338-9401-495f-bb6e-c93471ac7944.png)
Time of post is hidden.

3.1.8, Windows 10

**Comment by 23rd** [comment]
Should be fixed now.
