### ISSUE TITLE
Invite links access

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#17075]
### Steps to reproduce

I don't have access to invite links in channel from Telegram Desktop if I not owned of this channel (or maybe it's because I don't have "add new admins" permission, but I don't test it). At the same time I have access to it from iOS Telegram app.

1. Be admin without "add new admins" permission in channel
2. You don't have access to invite links from Telegram Desktop
3. But you have access to it from iOS Telegram app

1 screenshot - I don't have access to invite links in channel where I'm not owner and don't have "add new admins" permission (Telegram Desktop)
![image](https://user-images.githubusercontent.com/39812401/136441193-5967a296-ae5c-47c7-8e95-8c538e649726.png)

2 screenshot - I have access to invite links in channel where I'm owner of channel (Telegram Desktop)
![image](https://user-images.githubusercontent.com/39812401/136441202-00ebe919-c846-4213-afc8-efe452dd010b.png)

3 screenshot - I have access to invite links in channel where I'm not owner and don't have "add new admins" permission (iOS)
![image](https://user-images.githubusercontent.com/39812401/136441207-68eda70e-11c9-480f-96b2-a191fb2d3b4c.png)

### Expected behaviour

I must have access to invite links in channel management

### Actual behaviour

I don't have access to invite links in channel management

### Operating system

Windows 10

### Version of Telegram Desktop

3.1.7 Beta

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
I can't understand what the problem is, you can manage your links using the `Invite links` button.

**Comment by Neurotoxin001** [comment]
I don't have this button if I not creator of channel, because this button located here:
Manage channel - channel type - manage invite links.

I don't have "channel type" button if I not creator of channel. At the same time on Telegram for iOS I have "Invite links" button even if I not creator. And also I have this button on un-official client Kotatogram. So it's only visual bug on Telegram Desktop.

**Comment by 23rd** [comment]
Can you provide a screenshot of the whole `Edit channel` window (with blurred sensitive info)?

**Comment by Neurotoxin001** [comment]
![image](https://user-images.githubusercontent.com/39812401/162176996-4d2135e8-fd45-4b85-b5a1-70f13b207815.png)

**Comment by Neurotoxin001** [comment]
Fixed 4.2.4
![image](https://user-images.githubusercontent.com/39812401/194043789-7b6a5e32-6e7c-4433-ac55-5c0db2d68f92.png)
