### ISSUE TITLE
i can since yesterday. Don't click @username.

### ISSUE THREAD

**Issue by JackJatlack** [telegramdesktop/tdesktop#17087]
### Steps to reproduce

my problem is i can since yesterday. Don't click @username. So I push up but it doesn't happen. The problem goes so far that I also press Telegram.im on a channel / group. Nothing opens there either. I deleted it, reinstalled it and it didn't get any better. now i use portable but it still doesn't work. maybe someone has found the solution here. but not me . Thanks in advance

### Expected behaviour

i can since yesterday. Don't click @username.

### Actual behaviour

i can since yesterday. Don't click @username.

### Operating system

i can since yesterday. Don't click @username.

### Version of Telegram Desktop

i can since yesterday. Don't click @username.

### Installation source

Other (unofficial) source

### Logs

```shell
i can since yesterday. Don't click @username.
```

**Comment by JackJatlack** [comment]
I don't know that much about that
Website. Was I forwarded? . or did I do something wrong. that it was closed? @Aokromes

**Comment by john-preston** [comment]
@JackJatlack I can't understand the issue and there are no details. No system name and version, not Telegram Desktop version, nothing.

**Comment by JackJatlack** [comment]
![blaaa](https://user-images.githubusercontent.com/92242590/136687823-01629078-1f4d-4f9a-a352-e1162fdaef00.jpg)
