### ISSUE TITLE
windows build error

### ISSUE THREAD

**Issue by taogege** [telegramdesktop/tdesktop#17085]
env:
system:win10 x64
vs version:VS2019 16.5.0
python:3.9.7
I follow the instructions,but error always.I tried win10,win8 system

注意: 包含文件:    C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\poppack.h
注意: 包含文件:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\set
注意: 包含文件:  D:\work\BuildPath\Libraries\win64\breakpad\src\common/windows/dia_util.h
注意: 包含文件:  D:\work\BuildPath\Libraries\win64\breakpad\src\common/windows/guid_string.h
注意: 包含文件:   C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\guiddef.h
注意: 包含文件:  D:\work\BuildPath\Libraries\win64\breakpad\src\common/windows/string_utils-inl.h
[9/9] LINK_EMBED dump_syms.exe
FAILED: dump_syms.exe dump_syms.exe.pdb
D:\work\BuildPath\ThirdParty\Python27\python.exe gyp-win-tool link-with-manifests environment.x64 True dump_syms.exe "D:\work\BuildPath\ThirdParty\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:dump_syms.exe @dump_syms.exe.rsp" 1 mt.exe rc.exe "obj\tools\windows\dump_syms\dump_syms.dump_syms.exe.intermediate.manifest" obj\tools\windows\dump_syms\dump_syms.dump_syms.exe.generated.manifest
Traceback (most recent call last):
  File "D:\work\BuildPath\Libraries\win64\breakpad\src\out\Release_x64\gyp-win-tool", line 332, in <module>
    sys.exit(main(sys.argv[1:]))
  File "D:\work\BuildPath\Libraries\win64\breakpad\src\out\Release_x64\gyp-win-tool", line 31, in main
    exit_code = executor.Dispatch(args)
  File "D:\work\BuildPath\Libraries\win64\breakpad\src\out\Release_x64\gyp-win-tool", line 73, in Dispatch
    return getattr(self, method)(*args[1:])
  File "D:\work\BuildPath\Libraries\win64\breakpad\src\out\Release_x64\gyp-win-tool", line 202, in ExecLinkWithManifests
    our_data = our_f.read().translate(str.maketrans('', '', string.whitespace))
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
ninja: build stopped: subcommand failed.
[11/14](Libraries/breakpad): FAILED
FAILED

**Comment by john-preston** [comment]
@taogege Hmm, can you remove Python27 from ThirdParty? Maybe uninstall it?

**Comment by john-preston** [comment]
@taogege I'm not sure that VS version plays part in this build failure, but the build of the project itself later won't be successful on an old version of VS, so I suggest you update VS to the latest 16.11.3 and try once again.

**Comment by taogege** [comment]
@john-preston  I also tried the latest VS version,but has the same error too. I think this error not caused by the VS maybe.

**Comment by xuxiandi** [comment]
press space button pause compile process, . modify gy-pwin-tool , add "encoding='utf-8"...
----------------------
with open(our_manifest, 'r', encoding='utf-8') as our_f:
        with open(assert_manifest, 'r', encoding='utf-8') as assert_f:

**Comment by ilya-fedin** [comment]
There's #16939, so apparently this issue should be closed
