### ISSUE TITLE
[Feature Request] A setting to opt-out native Windows notifications Quick Reply and Mark as Read

### ISSUE THREAD

**Issue by vxna** [telegramdesktop/tdesktop#17082]
### Is your feature request related to a problem?

[3.1.8](https://github.com/telegramdesktop/tdesktop/releases/tag/v3.1.8) has introduced Quick Reply and Mark as Read to native Windows notifications and I consider this sort of breaking change as of now notifications are likely up to 2x more tall than it was before and that's a no go.

### Describe the solution you'd like

Add a way to opt-out of Quick Reply for native Windows notifications.

### Describe alternatives you've considered

Built in telegram notifications don't have the Quick Reply and Mark as Read, but it also don't match the current Windows theme, so receiving flashing white notifications while using dark theme is a no go as well.

### Additional context

Neither Discord nor Slack have Quick Reply and Mark as Read enabled with native Windows notifications (or at least it's not enabled by default)

**Comment by ilya-fedin** [comment]
> Built in telegram notifications don't have the Quick Reply and Mark as Read

They have. Quick reply is accessible as soon as you click REPLY. Mark as Read is achieved by sending an empty message via that notification.

**Comment by vxna** [comment]
> They have. Quick reply is accessible as soon as you click REPLY. Mark as Read is achieved by sending an empty message via that notification.

I've double checked and yes, there is. The difference is that Reply button is not visible without user interaction and no height of the notification toast is changed.

To make things clear: purpose of this feature request is to make it possible to opt-out unwanted behavior with increased height of native Windows notification toasts because they are up to 2x more tall and cover the content.

**Comment by ilya-fedin** [comment]
tdesktop avoids adding new settings, so it's unlikely it will be added

**Comment by vxna** [comment]
@ilya-fedin thank you for clarifying! 

Sadly I have no bandwidth to work on this feature myself, although I wish to keep this feature request open for the time being for if something changes or community shows more interest.
