### ISSUE TITLE
Taskbar icon shows with "Show taskbar icon" disabled

### ISSUE THREAD

**Issue by Thunraz** [telegramdesktop/tdesktop#17081]
### Steps to reproduce

1. Set "Show tray icon" option to on
2. Set "Show taskbar icon" option to off. Taskbar icon is being hidden.
3. Close Telegram window with x button. Notification is being shown that Telegram is still running in background.
4. Open Telegram window by clicking on tray icon.

### Expected behaviour

Taskbar icon is not shown.

### Actual behaviour

Taskbar icon is shown.

### Operating system

Windows 10 (21H1)

### Version of Telegram Desktop

since 3.1.6 beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@Thunraz Thanks for your report. Indeed :(
