### ISSUE TITLE
GIFs in current chat result in a high CPU load even when tdesktop has no focus 

### ISSUE THREAD

**Issue by hashworks** [telegramdesktop/tdesktop#1708]
I noticed that the Telegram app has a very high CPU load on my GNU/Linux notebook. The cause seemed to be 3 GIFs in the current chat window. So the load is quite normal, but it was running without focus with some other windows above it for a few hours, never stopping to play the GIFs.

So, I would expect it to either:
A) Pause the GIFs after some while
B) Pause the GIFs when the tdesktop window isn't having focus
C) Pause the GIFs when the tdesktop window isn't on top

**Comment by MaxMatti** [comment]
Also the option to disable autoplay or stop certain gifs would be nice.

**Comment by auchri** [comment]
@MaxMatti see #1678

**Comment by shershennm** [comment]
+

**Comment by Aokromes** [comment]
#1534 ?

**Comment by hashworks** [comment]
So the "fix" is to disable auto-play instead of stopping playback on focus loss?
