### ISSUE TITLE
Why Delete or Break My Sticker Link ?!

### ISSUE THREAD

**Issue by mnrlsd** [telegramdesktop/tdesktop#1709]
Hi

Why Delete or Break My Sticker Url ?! 

( "Stickers Not Found" Errors)

(Im Testing Url In Different Account) 

(Not Filled Sticker)

(Some Of Them Problem) 

For Example : https://telegram.me/addstickers/SnapbackBoyz_SeRaMo

![untit657led](https://cloud.githubusercontent.com/assets/17552516/13403621/1e3133d6-df2b-11e5-839f-a9e4811c1f5f.jpg)

**Comment by stek29** [comment]
And how is it related to TDesktop?

**Comment by DaFri-Nochiterov** [comment]
To explain closing: Your sticker pack can removed by [takedown request](https://telegram.org/faq#q-there-39s-illegal-content-on-telegram-how-do-i-take-it-down) or link can be wrong (check it). So this not an issue of TDesktop, don't ask general questions about Telegram here next time, for this you can contact [support](https://telegram.org/faq#telegram-support) in any official Telegram app.

**Comment by auchri** [comment]
@DaFri-Nochiterov thx!
