### ISSUE TITLE
App icon missing when installing snap on Ubuntu 21.04

### ISSUE THREAD

**Issue by mariosant** [telegramdesktop/tdesktop#17097]
### Steps to reproduce

1. Install telegram-desktop via snap package `snap install telegram-desktop`
2. Try to locate the application by hititng the super key
3. Mind the missing app icon

### Expected behaviour

I would expect the app icon to be visible

### Actual behaviour

The app icon is completely missing

### Operating system

Ubuntu 21.04

### Version of Telegram Desktop

3.1.9

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Well, snap packages don't and can't install shortcuts in your system, they're in sandbox. Installing shortcuts is completely a snapd job and the bug you see is a snapd bug, not a tdesktop bug.

**Comment by mariosant** [comment]
It might be a setting on the snap build file that gone wrong; def. worth taking a look imo.
