### ISSUE TITLE
[Feature Request] Add audio volume control to audio files and 1 minute video messages

### ISSUE THREAD

**Issue by KD276** [telegramdesktop/tdesktop#17094]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

Hello, is possible to add volume control for audio only files and video messages (the ones that last 1 minute)? Actually i'm forced to use windows volume to increase or decrease it. Pop-up videos are fine since they have already on the top left the volume control. Thank you.

I'm on Telegram portable desktop.

### Describe alternatives you've considered

See above.

**Comment by Neurotoxin001** [comment]
> audio files
Do you mean voice messages? Because for mp3 there is already volume control.

For voice messages there is already issue since 2017:
https://github.com/telegramdesktop/tdesktop/issues/3680

**Comment by Hobbix** [comment]
I was shocked when I realized that Telegram Desktop didn't have a volume control feature for voice and video messages (video circles). When watching a video message, your speakers chug at maximum volume. This is very annoying.
Developers, where are you?

**Comment by 23rd** [comment]
Please check the 4.3.1 version.

**Comment by Neurotoxin001** [comment]
![image](https://user-images.githubusercontent.com/39812401/200494380-ba9afe1b-adc9-4d1b-b93c-7b33a1bc5e10.png)

It's working, thanks!

**Comment by KD276** [comment]
This is good, took a lot of time but at least they implemented it. Thank you, working very well.
