### ISSUE TITLE
Telegram is slow during high usage of the GPU by the other processes

### ISSUE THREAD

**Issue by srogatch** [telegramdesktop/tdesktop#17091]
### Steps to reproduce

1. Run a background process with continuous high GPU usage, e.g. a GPU machine learning application or a crypto miner
2. Launch telegram
3. Try to switch chats within Telegram or type something

### Expected behaviour

Chats are switched in less than a second after a click and characters are shown as you type them.
Perhaps by having an option to switch from GTK/Gnome/Cairo to OpenGL.

### Actual behaviour

Telegram lags during all activities with it. It likely happens because Telegram uses GTK/Gnome/Cairo, which are known to hang for Sublime Text and Firefox: https://forum.sublimetext.com/t/ui-lag-under-high-gpu-load/42758/2

### Operating system

Ubuntu 20.04

### Version of Telegram Desktop

3.1.9

### Installation source

Snap

**Comment by GameKyuubi** [comment]
When did this start?  I noticed it maybe 3 months ago for me.

**Comment by srogatch** [comment]
@GameKyuubi it started when I started using the GPU at 100%.
