### ISSUE TITLE
Obsolete window border after the last update

### ISSUE THREAD

**Issue by norlin** [telegramdesktop/tdesktop#17098]
### Steps to reproduce

1. Install the latest public version ( 3.1.8 )
2. Launch Telegram app

### Expected behaviour

Telegram window does not have the border

### Actual behaviour

Telegram window now have an annoying thin light border.
<img width="643" alt="Screenshot_2447" src="https://user-images.githubusercontent.com/370803/137078873-edbd605d-af4a-421d-b6bd-8c005cdbc6ed.png">

The "use system frame" option does not fix the issue.
<img width="673" alt="Screenshot_2448" src="https://user-images.githubusercontent.com/370803/137078922-10358ff9-beaf-4db0-b25e-958d1bbc6eac.png">

If manually resize the window and then snap to a screen edge - the border is disappearing for some time.
<img width="979" alt="Screenshot_2449" src="https://user-images.githubusercontent.com/370803/137078823-8775eac4-4337-4d78-92a9-67fe212db600.png">

### Operating system

Windows 11

### Version of Telegram Desktop

3.1.8

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@norlin Yes, it was not there when the system didn't round the window corners. I opted in having rounded corners on Windows 11 and it added the border.

I'm afraid the removing of the border is either a bug in Windows 11 or a feature. But anyway it is not controlled by the app itself in any way.

If there will appear an API to remove the frame I'll happily use it. But I didn't see any indication that it exists.
