### ISSUE TITLE
[Question] I got an error to build on windows 10

### ISSUE THREAD

**Issue by crocodile305** [telegramdesktop/tdesktop#17102]
I get an error with qt5 when running this command.

configure.bat x64 -D TDESKTOP_API_ID=YOUR_API_ID -D TDESKTOP_API_HASH=YOUR_API_HASH -D DESKTOP_APP_USE_PACKAGED=OFF -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF

```
Version: 3.1.9
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
CMake Error at cmake/external/qt/package.cmake:21 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:45 (include)


-- Configuring incomplete, errors occurred!

```
Please help me.

**Comment by ilya-fedin** [comment]
Are you sure previous steps were successful? It seems the dependencies aren't really built

**Comment by ilya-fedin** [comment]
Can you provide the output of prepare.py?

**Comment by crocodile305** [comment]
![2021-10-14_14h31_56](https://user-images.githubusercontent.com/38894059/137264182-751c9d36-abea-4b19-88eb-8a88a6e301dd.png)
![2021-10-14_14h32_45](https://user-images.githubusercontent.com/38894059/137264187-74150c8a-f9c5-426c-a9de-b4575aab9770.png)
Please check this screen shots.

**Comment by ilya-fedin** [comment]
Are you sure that this version is used in the command line? Have you checked with `cmake --version`?

**Comment by crocodile305** [comment]
![2021-10-15_04h20_03](https://user-images.githubusercontent.com/38894059/137389560-2b62be1b-2777-4394-87b1-0dcc318039d6.png)
Yes.Sure.

**Comment by crocodile305** [comment]
Also, I'm used API_ID and API_HASH like this.

`configure.bat x64 -D TDESKTOP_API_ID=653456 -D TDESKTOP_API_HASH=41ccaae6d8141d6c909dc257151a13c5 -D DESKTOP_APP_USE_PACKAGED=OFF -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF`

**Comment by crocodile305** [comment]
About the cmake version, I had run from x64 native tools command prompt.
I just removed cmake but I can see the cmake version is 3.17.
I'm not sure how to fix that problem....

**Comment by crocodile305** [comment]
Thank you so much.
I just remove and install the CMake again and working fine now.
