### ISSUE TITLE
Flatpak Permissions misalignment for Fedora 34

### ISSUE THREAD

**Issue by digital-michael** [telegramdesktop/tdesktop#17103]
### Steps to reproduce

1. Start Telegram 
2. wait 40+ seconds

### Expected behaviour

1. Application will stay loaded until instructed to close/quit

### Actual behaviour

1. Application closes silently and without emitting an error message

Note: I was able to address this issue by applying details from: https://github.com/telegramdesktop/tdesktop/issues/10418 : 
```
flatpak permissions
flatpak permission-remove background background org.telegram.desktop
flatpak permissions
flatpak permission-set background background org.telegram.desktop yes
```

### Operating system

Fedora 34

### Version of Telegram Desktop

 Telegram version 3.1.9

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Maybe I'm wrong, but as far as I heard, it shouldn't kill the app unless working in background is explicitly denied (what looks like may happen on its own due to various bugs in portal daemons). I never reproduced that, though, maybe it's gnome-specific, but I don't use gnome.
