### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by zakiloki0** [telegramdesktop/tdesktop#17110]
In a group when you disable the embedding of links in the permissions of members, why do they keep coming out?

I thought that option would detect any common link that starts with **https or www** but they keep coming out.

**Comment by zakiloki0** [comment]
> If you are an admin you can violate this rules.
> 
> Or other non admin members can also post embed links?

Yes I know if I am admin I can do it, but i mean normal members, I set the group with this option for not allowing but doesn't work.

I don't really see a difference between having it on or off because people can still put links, so I don't know what the point of this option is.

**Comment by ZerdoX-x** [comment]
Oh, so you don't understand what this toggle does. Here you are: https://telegram.org/blog/link-preview

Hope answered your question

**Comment by zakiloki0** [comment]
> Oh, so you don't understand what this toggle does. Here you are: https://telegram.org/blog/link-preview
> 
> Hope answered your question

Ok, but then it does not make sense that it is called "Embed links" because it gives a meaning that does not allow links (option that should be and is not there). Thanks for the clarification Zerdo ;) Do you know any way to prevent post links?

**Comment by ZerdoX-x** [comment]
> Do you know any way to prevent post links?

Yep, create bot or use one that already exists. He will monitor chat and then will do everything you want, send message, delete author's message or kick/ban him

**Comment by ZerdoX-x** [comment]
Telegram can't disallow to post any links in the chat. But some bots can. You can now close the issue I guess

**Comment by zakiloki0** [comment]
> Telegram can't disallow to post any links in the chat. But some bots can. You can now close the issue I guess

Ok, thanks for you help, I'm going to see if I find something.
