### ISSUE TITLE
 Can't create group in desktop  app  (win7) and in web version too

### ISSUE THREAD

**Issue by phpprobetter** [telegramdesktop/tdesktop#1711]
Hello!)

Why  I can create group in telegram desktop? Old groups i created here work normal. But i cant create new one  - click  on `Create` button has **no effect** after checking contacts for group.
 help pls!

**Comment by telegramdesktop** [comment]
@phpprobetter Does it work in web.telegram.org version?

**Comment by phpprobetter** [comment]
@telegramdesktop Not works too, but (in additional )in **web** version I see error (after select 2 contacts and click on `Create group`):
>Error
One of the params is missing or invalid.

With info:
```
Method: messages.createChat
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"PEER_ID_INVALID"}
Stack: g/u@https://web.telegram.org/js/app.js:29:4512
g/_/<@https://web.telegram.org/js/app.js:29:5813
l@https://web.telegram.org/js/app.js:13:12014
c/<@https://web.telegram.org/js/app.js:13:12186
fn/this.$get</m.prototype.$eval@https://web.telegram.org/js/app.js:13:19588
fn/this.$get</m.prototype.$digest@https://web.telegram.org/js/app.js:13:18015
fn/this.$get</m.prototype.$evalAsync/<@https://web.telegram.org/js/app.js:13:19677
a@https://web.telegram.org/js/app.js:12:3093
at/u.defer/n<@https://web.telegram.org/js/app.js:12:4549
n@https://web.telegram.org/js/app.js:3:16924
```

**Comment by Lavos** [comment]
+1
This happens to me too. I am completely unable to create groups, regardless the app. The web app gives the error outlined above, and every other client either says nothing or "An error occurred."

I am @kcost on telegram.

**Comment by stek29** [comment]
What the [@SpamBot](telegram.me/SpamBot) says? 
And how much channels/supergroups/bots have you create already?

**Comment by Lavos** [comment]
I have created a single bot. I have not been able to successfully create a group. 

Checking with SpamBot now. That's a good heads-up I wasn't aware of.

**Comment by phpprobetter** [comment]
I see this error at mobile app too (in my account - not onli in web or desktop versions). But I can create group using new account.


>What the @SpamBot says? 

Spam bot says:
>Dear telegram,
I’m afraid some Telegram users found your messages annoying and reported them. These messages were forwarded to our team of moderators for inspection and they have confirmed that you’ve been sending spam.

We have zero-tolerance for spammers on Telegram. Unfortunately, your account is now limited. You will not be able to send messages to people who do not have your number in their phone contacts or add them to groups and channels. Of course, when people contact you first, you can always reply to them.



>And how much channels/supergroups/bots have you create already?

I have only 2 small groups (<5 people), 0 bots and 0 supergroups. Only 1 person left one group  nothing more.

**Comment by Lavos** [comment]
It turned in my case that I was indeed spam limited. Maybe the real solution to this ticket is to change the error messaging to say that the user is spam-limited instead of "PEER_ID_INVALID" (or nothing in other clients)

**Comment by formatq** [comment]
Becoming more and more accounts with spam limits. It is a pity that the limit is forever.

**Comment by auchri** [comment]
So there is nothing we can do for you, so I'll close this issue.

**Comment by didyouexpectthat** [comment]
Hi @auchri, I know you closed this as "nothing we can do for you" but I do believe that the Desktop client can return a value that informs the user they are limited. What is problematic about that? I didn't know that I had to message the Spam Info bot until I looked in this bug. The mobile client could also benefit from this.

**Comment by stek29** [comment]
@didyouexpectthat You can check logs if you want. Anyway, it's [api issue] that server doesn't show what's the problem.

**Comment by didyouexpectthat** [comment]
I see, thanks for the clarification, @stek29.

I did end up messaging Spam Info bot and was able to clear the limit (though I wasn't notified when the limit was removed).
