### ISSUE TITLE
[Feature Request] Clear notification from the KDE notification tray

### ISSUE THREAD

**Issue by sudhirkhanger** [telegramdesktop/tdesktop#17111]
### Is your feature request related to a problem?

Clear notification from the KDE notification tray when a message has been read.

### Describe the solution you'd like

If a message has been read then the corresponding notification should be cleared from the notification tray in KDE. My notification tray has 100s of stale telegram notifications even if I have read all messages.

### Describe alternatives you've considered

NA

### Additional context

 Operating System: Kubuntu 21.04
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-37-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-2620M CPU @ 2.70GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 3000

**Comment by ilya-fedin** [comment]
How to clear them? :thinking: 
Notification spec provides a way to close notifications, but it doesn't have any API to clear them. Are you sure it's even possible?

**Comment by ilya-fedin** [comment]
If KDE should clear notification by CloseNotification, then the notification should disappear as soon as it's closed since tdesktop calls CloseNotification right after NotificationClosed signal
https://github.com/telegramdesktop/tdesktop/blob/adb0a9b6f0300428e8de4616b4df84c4370f36a5/Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp#L696-L700

**Comment by ilya-fedin** [comment]
Oh, if CloseNotification clears from the history then it's logical that NotificationClosed should be emitted when notification history is cleared rather than when the notification is closed...

**Comment by john-preston** [comment]
@sudhirkhanger @vimpostor does it work with 3.2.4 version on Linux? I've added clearing of single message notifications that were sent to the system.

**Comment by vimpostor** [comment]
> @sudhirkhanger @vimpostor does it work with 3.2.4 version on Linux? I've added clearing of single message notifications that were sent to the system.

No, Telegram native notifications are only cleared from history if I click on the chat **before** the notification popup vanishes. If the notification is already in the history and I click on the chat, the notification stays in the history.

Telegram Desktop 3.2.4 on Arch Linux
