### ISSUE TITLE
[Question] client closes immediately after going through 2-step verification

### ISSUE THREAD

**Issue by ENF-FullStack** [telegramdesktop/tdesktop#17115]
Interesting issue, desktop client closes immediately after going through 2-step verification through mobile client. Desktop client shows the UI for maybe 0.5 seconds before closing and giving mobile client info on access try. Can't really say if this is desktop client issue at all or maybe some Telegram setting interfering as I am just a casual user of the app.

OS: pop_os 21.04

**Comment by ilya-fedin** [comment]
If you want to report a bug, use the bug report template instead
