### ISSUE TITLE
[Windows] Telegram shouldn't appear in Alt-Tab app list when "Show taskbar icon" is disabled

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#17119]
### Steps to reproduce

1. Uncheck the "Show taskbar icon"
2. Do an alt-tab

### Expected behaviour

Telegram with this option unchecked should not appear on the Alt-Tab app list

### Actual behaviour

Telegram appears in Alt-Tab app list

### Operating system

Windows 10

### Version of Telegram Desktop

3.1.8

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
There was a report about the inability to alt tab: https://github.com/telegramdesktop/tdesktop/issues/2932
So this can be defined as intended behavior.
