### ISSUE TITLE
Editing message only works when first clicking end of line, paragraph or message.

### ISSUE THREAD

**Issue by casperl** [telegramdesktop/tdesktop#17120]
### Steps to reproduce

This does not work:

1. Right-click on message and select Edit.
2. Left-click anywhere in message to edit.
3. Editing functionality inoperable though in open editing window.

### Expected behaviour

1. Right click on message text and selecting Edit
2. Left-click anywhere in text
3. Start editing with full functionality.

### Actual behaviour

1. Right-click on message and select Edit.
2. Left-click right at the end of a line, paragraph or the very end of the message.
3. Now move with cursor keys to the desired place to edit.
4. Editing functionality now works.
5. Left-click anywhere else inside message prohibits editing functionality until the end of line/paragraph/message is clicked again.

### Operating system

Ubuntu 20.04

### Version of Telegram Desktop

2.1.7

### Installation source

Snap

**Comment by casperl** [comment]
This happens in both the Telegram Snap (multiple versions up to current) as well as in the Telegram-Desktop from Ubuntu package (also multiple versions.)

**Comment by ilya-fedin** [comment]
Please provide a screen record with reproducing the bug, from the latest version (3.1.8)
