### ISSUE TITLE
problem with preparing breakpad library

### ISSUE THREAD

**Issue by keyvanarasteh** [telegramdesktop/tdesktop#1712]
win : win8.1
visual studio 2015

when i run this : 

`..\..\..\..\gyp\gyp --no-circular-check`

this error was reported : 

`
input files not found.
unittests\..\..\..\testing\gtest\src\gtest-all.
unittests\..\..\..\testing\src\gmock-all.cc
unittests\..\..\..\testing\src\gmock_main.cc`

help plzz

**Comment by keyvanarasteh** [comment]
@telegramdesktop plz help, tnXXX

**Comment by telegramdesktop** [comment]
Well, this is a google library, I took the instructions from the internet and they worked for me. I'm not sure what is not enough in your case :(

**Comment by keyvanarasteh** [comment]
@telegramdesktop  : just change this line in ("building-msvc.md") : 

`git clone https://chromium.googlesource.com/breakpad/breakpad`

to 

'svn checkout http://google-breakpad.googlecode.com/svn/trunk/ breakpad'

Tnx Solved <3
