### ISSUE TITLE
Ubuntu 21.04 keyboard not working at all after update to 21.04

### ISSUE THREAD

**Issue by Akucuki** [telegramdesktop/tdesktop#17126]
### Steps to reproduce

1. Update Ubuntu to 21.04
2. Open telegram
3. Try typing a message

### Expected behaviour

Typing works

### Actual behaviour

Telegram ignores both internal laptop keyboard and external one.

### Operating system

Ubuntu 21.04

### Version of Telegram Desktop

3.1.9

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Please upload on github instead

**Comment by Akucuki** [comment]
@ilya-fedin Sorry but this video is too big to attach it to the github message even after compressing

**Comment by ilya-fedin** [comment]
Maybe it's a bad Wayland support by Qt :thinking:
