### ISSUE TITLE
[Feature Request] Spam protection mechanisms

### ISSUE THREAD

**Issue by lemmy04** [telegramdesktop/tdesktop#17123]
### Is your feature request related to a problem?

Right now there are no mechanisms in place to protect users from spam of all sorts.
Anyone can send anything to anyone, anyone can join any group, etc etc.

Personally I get at least one illegal offer per day, sometimes more. Drugs, Prostitution, you name it.

### Describe the solution you'd like

There needs to be a way to set an account or a group to "private", i.e. before being able to send on the group or talk to the account there would be something like a "friend request" on other social platforms, which would have to be approved by the account owner or in case of a group by one of the group mods.

only after that the new contact would be able to send anything.

### Describe alternatives you've considered

I am seriously considering using a different messenger at this point.

### Additional context

I'm aware that this would be a feature for the server / the protocol, not the desktop client - where's the issue tracker for that?

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by lemmy04** [comment]
https://bugs.telegram.org/c/10326
