### ISSUE TITLE
[Bug] Can't move window while in Settings

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#1713]
1) Set Telegram window size so that chats list on the left disappears
2) Go to settings
3) Try to move window while dragging its header
Result: All presses in header are treated as press on "Back" button.
![Settings window](https://cloud.githubusercontent.com/assets/2780044/13453813/0cbc50b0-e064-11e5-98d3-5ba678ab7adc.png)

Tested on Windows 7 x64, will try 8.1 later.
Telegram 0.9.28 and 0.9.29dev

**Comment by telegramdesktop** [comment]
@Kondra007 This is a feature :)

**Comment by Kondra007** [comment]
If this is a feature, how can I enable another one, which allows me to move window? :)

**Comment by telegramdesktop** [comment]
@Kondra007 Just go back from settings..

**Comment by Kondra007** [comment]
Ok, got it. Thanks!
