### ISSUE TITLE
Add support for WEBP format similar to JPG. [Feature Request] 

### ISSUE THREAD

**Issue by LXS1986** [telegramdesktop/tdesktop#17140]
### Is your feature request related to a problem?

When I drag and drop a WEBP file into the application window, it is attached as a file, not as a picture (as in the case of other formats)

### Describe the solution you'd like

When you drag an image in WEBP format onto the window of the Telegram application, it automatically detects it as a picture.

### Describe alternatives you've considered

I open the image in an editor and copy the content to the clipboard, then paste the image from the clipboard into the message box.

**Comment by Neurotoxin001** [comment]
Still relevant and annoying when I trying to send webp images and they sending as stickers

**Comment by 23rd** [comment]
@Neurotoxin001 Wanna test the feature in "early access" build?

https://github.com/telegramdesktop/tdesktop/actions/runs/3438213341

**Comment by Neurotoxin001** [comment]
@23rd 


https://user-images.githubusercontent.com/39812401/201164265-d1e479a2-eb24-4efc-b1cc-ab770579cb43.mp4

it's working fine but when I drag&drop webp it's always have unchecked "compress images" checkbox. When I copy-paste webp file from clipboard it's remembers that checkbox. But when I send webp without "compress" it's still sending as sticker, not as document

**Comment by 23rd** [comment]
> But when I send webp without "compress" it's still sending as sticker, not as document

I think that behavior is intended and never will be changed.

**Comment by 23rd** [comment]
Another build.
Would appreciate testing with various file types.

https://github.com/telegramdesktop/tdesktop/actions/runs/3439996307

**Comment by Neurotoxin001** [comment]
Now it's have 2 "drop" options like jpg's/png's etc
![image](https://user-images.githubusercontent.com/39812401/201291876-fa55d60d-29ac-4799-9169-1f4ae8f6e3ea.png)

> various file types

But what you mean? All old images formats working as before

**Comment by Neurotoxin001** [comment]
If I send webp+jpg they sending fine too in all cases

**Comment by Neurotoxin001** [comment]
Released https://github.com/telegramdesktop/tdesktop/commit/3467fe226ff0e640d4ed68d642a7e710c352562c

**Comment by LXS1986** [comment]
When will the Microsoft Store version be updated? Now version 4.2.4 x64 is being loaded from there.
