### ISSUE TITLE
libOpenGL.so.0: No such file or directory

### ISSUE THREAD

**Issue by repsorp** [telegramdesktop/tdesktop#17158]
### Steps to reproduce

open telegram-desktop

### Expected behaviour

telegram-desktop opens

### Actual behaviour

error message on launch:
`telegram-desktop: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory
`

### Operating system

ubuntu 21.04

### Version of Telegram Desktop

3.1.11-8-g9c0bf32b8 2021-10-29 (3279) 

### Installation source

Snap

### Logs

```shell
telegram-desktop: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory
```

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by repsorp** [comment]
latest/stable: 3.1.11 2021-10-29 (3277) is working fine
latest/edge has been working fine till this 3.1.11-8-g9c0bf32b8 2021-10-29 rev. 3279 version
How come did library libOpenGL.so.0 is suddenly missing ? 
Is this not the place to report issues ?

**Comment by FredUA** [comment]
> plz try downloading official version from https://desktop.telegram.org

There is a link to https://snapcraft.io/telegram-desktop where I actually have installed this app. But it doesn't work on Ubuntu 21.10

**Comment by ilya-fedin** [comment]
edge channel is continuous build from dev branch, you can experience issues like that from time to time. Use stable channel for stable experience.

**Comment by FredUA** [comment]
> edge channel is a continuous build from dev branch, so you can experience issues like that from time to time. Use stable channel for stable experience.

I use a stable version

**Comment by ilya-fedin** [comment]
As I just explained, latest/edge is not a stable version, latest/stable is.

**Comment by FredUA** [comment]
> As I just explained, latest/edge is not a stable version, latest/stable is.

I am a little bit confused. I use **latest/stable**. It should work fine, shouldn't it?

**Comment by ilya-fedin** [comment]
> I am a little bit confused. I use **latest/stable**. It should work fine, shouldn't it?

I just checked and I can't reproduce such a bug on latest/stable. Apparently, you think you're using latest/stable, but you're using latest/edge.

**Comment by repsorp** [comment]
latest/stable is ok
latest/edge is not

**Comment by FredUA** [comment]
well, I have reinstalled it one more time and all works fine. It could be my mistake.
I was sure it was a stable version.
Thank you!

**Comment by repsorp** [comment]
latest/edge:      3.1.11-14-gaaafa8b3f 2021-10-30 (3287)

error message on start:
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Abandon (core dumped)
```

**Comment by repsorp** [comment]
Is there any more appropriate place to report such issues ?

**Comment by adhitht123** [comment]
I too have got the same error. Seems like it is an error specific to the latest/edge version for snap. Installing latest/stable doesn't produce any errors. @repsorp I see the same error when I reinstalled the latest/edge version.

**Comment by ilya-fedin** [comment]
> Is there any more appropriate place to report such issues ?

No, this is re appropriate place. The snap is being migrated to Qt 6, so edge channel will be broken most likely for near time
