### ISSUE TITLE
Edited image sending error in Android

### ISSUE THREAD

**Issue by Moldoteck** [telegramdesktop/tdesktop#17159]
Posting here, because Android's repo doesn't have issues tab

If I edit an image in telegram on Android (draw something) and tap to send it without compression, it sends an extremely compressed image(from 5mb file to ~100 kb). On Desktop client this scenario works as expected

Can this be fixed?

**Comment by Aokromes** [comment]
> Posting here, because Android's repo doesn't have issues tab
> 
> If I edit an image in telegram on Android (draw something) and tap to send it without compression, it sends an extremely compressed image(from 5mb file to ~100 kb). On Desktop client this scenario works as expected
> 
> Can this be fixed?

post on bugs.telegram.org
