### ISSUE TITLE
Images and videos cannot be full-screened!

### ISSUE THREAD

**Issue by Mr-Chemist** [telegramdesktop/tdesktop#17152]
Hi, 
When I click on a photo or video to maximize, Telegram does not show anything (But there is no problem in version 1.9), when I open the windows 7 Task manager, the Telegram Media viewer is running there (but Nothing is displayed).

My version is 3.1.9

![Untitled](https://user-images.githubusercontent.com/51885599/139226423-2fe5b27d-38b9-411b-b134-3bd3c711e426.jpg)

**Comment by HarDX** [comment]
Same problem on Win10 21H1
Tested "OpenGL", "Direct3D 9" - no issue
Tested "D3D11on12", "Direct3D 11" - have issue
