### ISSUE TITLE
[Question] Build Windows and Linux Failed 

### ISSUE THREAD

**Issue by nguyennhatdung** [telegramdesktop/tdesktop#17154]
Hi!

I'm trying build telegram from source (Windows + Linux) follow this guide : 
Windows : (Windows 8.1 x64 - VS2019)
[https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md)
Issue at 

>  Could not find a package configuration file provided by "Qt5" with any of
>  the following names:
> 
>    Qt5Config.cmake
>    qt5-config.cmake

CMake File Log : [https://nhatdung.com/public/CMakeOutput.log](https://nhatdung.com/public/CMakeOutput.log)
Full Image : [https://nhatdung.com/public/2.JPG](https://nhatdung.com/public/2.JPG)

Linux (Debian 10)
[https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md)

but the build failed at 
`docker build -t tdesktop:centos_env Telegram/build/docker/centos_env/
`

> make[3]: Leaving directory '/usr/src/Libraries/qt_5_15_2/qtbase/src/widgets'
> make[2]: Leaving directory '/usr/src/Libraries/qt_5_15_2/qtbase/src'
> make[1]: *** [Makefile:51: sub-src-make_first] Error 2
> make[1]: Leaving directory '/usr/src/Libraries/qt_5_15_2/qtbase'
> make: *** [Makefile:50: module-qtbase-make_first] Error 2
> The command 'bash -c . /opt/rh/devtoolset-9/enable; exec bash -c "$@" -s [ -n "${QT6}" ] || make -> > j$(nproc)' returned a non-zero code: 2

Full Image : [https://nhatdung.com/public/1.jpg](https://nhatdung.com/public/1.jpg)

Did i miss something ? I follow all step in the guide. How to fix those error ?

**Comment by nguyennhatdung** [comment]
Thanks for the reply!

For Linux here is full log, can you look to see what's wrong ?
[https://nhatdung.com/public/telegram_build_log.zip](url)

And for windows build i'll check the prepare.py

**Comment by ilya-fedin** [comment]
You know that all links in your posts are broken?

**Comment by nguyennhatdung** [comment]
sorry about that, i just update the link

**Comment by ilya-fedin** [comment]
Actual error is
```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```

Something is killed the compiler, apparently it's an out-of-memory killer

**Comment by nguyennhatdung** [comment]
hmm, i'll increase mem and try again. Many thanks!

**Comment by nguyennhatdung** [comment]
I was success build the Linux, for windows the prepare\win.bat got error at : 

`"D:\teleg\Libraries\win64\openal-soft\build\OpenAL.vcxproj" (default target) (1
) ->
(ClCompile target) ->
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(229,21): erro
r C2760: syntax error: unexpected token 'identifier', expected 'type specifier'
 [D:\teleg\Libraries\win64\openal-soft\build\OpenAL.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(229,21): erro
r C2760: syntax error: unexpected token 'identifier', expected 'type specifier'
 [D:\teleg\Libraries\win64\openal-soft\build\OpenAL.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(229,21): erro
r C2760: syntax error: unexpected token 'identifier', expected 'type specifier'
 [D:\teleg\Libraries\win64\openal-soft\build\OpenAL.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(229,21): erro
r C2760: syntax error: unexpected token 'identifier', expected 'type specifier'
 [D:\teleg\Libraries\win64\openal-soft\build\OpenAL.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(229,21): erro
r C2760: syntax error: unexpected token 'identifier', expected 'type specifier'
 [D:\teleg\Libraries\win64\openal-soft\build\OpenAL.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(229,21): erro
r C2760: syntax error: unexpected token 'identifier', expected 'type specifier'
 [D:\teleg\Libraries\win64\openal-soft\build\OpenAL.vcxproj]

    12 Warning(s)
    6 Error(s)

Time Elapsed 00:01:11.24
[10/14](Libraries/openal-soft#0.2): FAILED
FAILED`

how to fix that ?

**Comment by ilya-fedin** [comment]
Looks like you have an old version of windows kits and it contflicts

**Comment by ilya-fedin** [comment]
This could be a bug in openal build scripts, you can report that to https://github.com/kcat/openal-soft

**Comment by nguyennhatdung** [comment]
I just uninstall the Windows 8.1 sdk and seem compiled ok

Many thanks!
