### ISSUE TITLE
[Feature Request] disable user share screen in live streaming

### ISSUE THREAD

**Issue by alexdhika** [telegramdesktop/tdesktop#17164]
### Is your feature request related to a problem?

Like zoom app, only cohost can share screen in live stream

### Describe the solution you'd like

Like zoom app, only cohost can share screen in live stream

### Describe alternatives you've considered

Like zoom app, only cohost can share screen in live stream

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
