### ISSUE TITLE
Showing previous image if click on new image in saved messages: Linux

### ISSUE THREAD

**Issue by basimaslamts** [telegramdesktop/tdesktop#17167]
### Steps to reproduce

1. open telegram
2. click on chat of "saved message"
3. click on chat heading "saved messages"
4. click on files
5. view one image in document format
6. close it and see another (there is a slight flickering)
7. close it and see another
8. now it will be seeing the picture of 6th step rather than what expected to see in 7th step
9. this continues 

### Expected behaviour

The file the user clicking should be the one actually opening and showing in the window not the previous file/image 

### Actual behaviour

previous image ( as doc) is being showing and not showing the file which I clicked

### Operating system

Ubuntu, LInux, 20.04.3 LTS (Focal Fossa) 64-bit, Mate

### Version of Telegram Desktop

3.1.8

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#17109
