### ISSUE TITLE
Share screen with audio in linux desktop

### ISSUE THREAD

**Issue by alexdhika** [telegramdesktop/tdesktop#17163]
Telegram cannot share audio when i share screen in live streaming in linux desktop

How to fix it?

**Comment by john-preston** [comment]
@alexdhika Implement it and PR 😭😭

**Comment by alexdhika** [comment]
> @alexdhika Implement it and PR 😭😭

Thanks 🙂

**Comment by zakiloki0** [comment]
> Telegram cannot share audio when i share screen in live streaming in linux desktop
> 
> How to fix it?

With pulseaudio you can pass the audio, I don't know if there is much difference in quality in terms of "Share audio" but it does its job.

**Comment by JinsoRaj** [comment]
> Telegram cannot share audio when i share screen in live streaming in linux desktop
> 
> How to fix it?

I think it is possible in settings  !?
There is an option to change Mic. input. Right?
