### ISSUE TITLE
Crashing when clicking on channel subscribers

### ISSUE THREAD

**Issue by 416d72** [telegramdesktop/tdesktop#17165]
### Steps to reproduce

1. Create a new channel
2. View channel info
3. Click on `n subscriber` (Where `n` is the number of subscribers)

### Expected behaviour

Telegram should show subscribers

### Actual behaviour

Crashes with no message, Just needs to be started again

### Operating system

Linux (Opensuse tumbleweed 20211024)

### Version of Telegram Desktop

3.1.9-1.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Please install the official build from https://desktop.telegram.org, reproduce on it and provide crash report tag from crash reporter.

**Comment by 416d72** [comment]
Thanks, I replaced the distro release with the official one and the bug no longer shows.
