### ISSUE TITLE
Rime 0.15.2 can't input on tdesktop 3.1.12 beta 

### ISSUE THREAD

**Issue by EpLiar** [telegramdesktop/tdesktop#17176]
### Steps to reproduce

1. Let the tdesktop auto-update to 3.1.12 beta
2. Install / Reinstall [rime 0.15.2](https://rime.im/)
3. Type anything on the textbox

### Expected behaviour

The Rime input method should work normally

### Actual behaviour

The textbox does not show any text input what I type with the keyboard.

### Operating system

macOS 11.6

### Version of Telegram Desktop

3.1.12 beta

### Installation source

Static binary from official website

**Comment by EpLiar** [comment]
So can I disable the auto-update? 🤔 I can't find this.

**Comment by john-preston** [comment]
@EpLiar Qt 6 regression :(

Settings > Advanced

**Comment by EpLiar** [comment]
> Settings > Advanced

I have already disabled this feature. But I install the old version, it still shows the upgrade telegram below.

![image](https://user-images.githubusercontent.com/23559565/139788625-3f6b4c93-672b-4ce2-9374-70845c1816c7.png)

**Comment by john-preston** [comment]
@EpLiar You can update it, if it shows the button, then install the old version and go to Settings > Advanced to disable the autoupdate.

The old version doesn't read settings, written by a newer version, so if you first disable autoupdate (or change any other settings), then install the old version, it will be launched without all those changes to settings.

**Comment by EpLiar** [comment]
> @EpLiar You can update it, if it shows the button, then install the old version and go to Settings > Advanced to disable the autoupdate.

It works, thanks a lot.

I will keep this issue open before the bug is fixed.

**Comment by john-preston** [comment]
@EpLiar Can you please check this version: https://td.telegram.org/tmac/tsetup.3.2.5.dmg

Does it work fine?

**Comment by cubercsl** [comment]
> @EpLiar Can you please check this version: [td.telegram.org/tmac/tsetup.3.2.5.dmg](https://td.telegram.org/tmac/tsetup.3.2.5.dmg)
> 
> Does it work fine?

LGTM

macos 12.0.1
td 3.2.5
rime 0.15.2

**Comment by EpLiar** [comment]
> @EpLiar Can you please check this version: https://td.telegram.org/tmac/tsetup.3.2.5.dmg
> 
> Does it work fine?

Yes! It works!

Thank you. @john-preston

**Comment by EpLiar** [comment]
> @EpLiar Can you please check this version: https://td.telegram.org/tmac/tsetup.3.2.5.dmg

But this version can't use the command+w shortcut, there is nothing that happened when I use this shortcut.
