### ISSUE TITLE
[Feature Request] Remember the folder for saving media files

### ISSUE THREAD

**Issue by hubaishan** [telegramdesktop/tdesktop#17177]
### Is your feature request related to a problem?

The default save folder is telegram program folder, the is very bad behavior, When you change that folder the program does not remember your chosen folder. And you have to change folder again in next save as.

### Describe the solution you'd like

Set default save as folder to `Downloads` folder or to media type music to music folder documents to documents folder and so on. Telegram must remember last folder I have saved file in. 

### Describe alternatives you've considered

nothing

**Comment by john-preston** [comment]
@hubaishan You've removed all the details from the issue template, like system, environment, installation source :(

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5788#issuecomment-590592069
