### ISSUE TITLE
Artifacts in message fields

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#17178]
### Steps to reproduce

Just opened a channel.

### Expected behaviour

No artifacts.

### Actual behaviour

![2021-11-02-174637_1366x768_scrot](https://user-images.githubusercontent.com/2134486/139887341-8fe3fc18-b7f1-4683-91ef-727901216a1e.png)
![2021-11-02-174836_1366x768_scrot](https://user-images.githubusercontent.com/2134486/139887603-c251d7df-60f5-4f60-96b3-4d6d15eb4ad3.png)
Looks like the buttons are translucent and the underlying window content is revealed through.

### Operating system

Debian GNU/Linux 12, compiz-reloaded 0.8.18

### Version of Telegram Desktop

3.1.12 beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@bodqhrohro What about 3.1.13? The same?

**Comment by john-preston** [comment]
@bodqhrohro I guess so.
