### ISSUE TITLE
telegram not support RTL-LTR 

### ISSUE THREAD

**Issue by Radsms** [telegramdesktop/tdesktop#1717]
What is auto-RTL? Ability to recognize the language (specially first character) to switch typing direction automatically from default to right-to-left or vice versa in the field and showing sent messages in the correct direction: RTL/ltr.

Some RTL languages: Arabic, Hebrew, Kurdish, Persian, etc.

**Comment by Aokromes** [comment]
#1387

**Comment by shapiraman** [comment]
any one fixing this?

**Comment by deadmann** [comment]
I require to manually do this: for example:

I have persian title, with numeric/eng/persian values, which i want to send to our client as a result of the request they made on our service formatted as a table... It is good to be able to make them both start from same side of the box, firstline goes to the right, and others to the left... (I Use \r\n line seperator, same as hitting Shift+Enter on telegram desktop)

Plus that:
i did padding for header and value names of a column, so all of them take their maximum size, and in VS inspector it's all the same, and looks like a table, but in telegram it's unordered, i'm not sure if it's font issue or what
