### ISSUE TITLE
Scroll can drag window

### ISSUE THREAD

**Issue by GDGooD** [telegramdesktop/tdesktop#17174]
### Steps to reproduce

1. Open Telegram Desktop
2. Move window holding to bar
3. Scroll chat list using mouse wheel

### Expected behaviour

Chat list is scrolled

### Actual behaviour

Every second scroll cursor is trying to move window.

### Operating system

Arch Linux, MATE Desktop 1.26

### Version of Telegram Desktop

3.1.11 from AUR, 3.1.8 from telegram.org

### Installation source

Static binary from official website

**Comment by GDGooD** [comment]
Also there is a bug that Telegram window can stick to the cursor even if window is inactive, and the described behaviour can be a representation of root bug.

**Comment by ilya-fedin** [comment]
#10348

**Comment by GDGooD** [comment]
Closed as a duplicate.
