### ISSUE TITLE
PgUp/PgDown broken in 3.1.12

### ISSUE THREAD

**Issue by torkve** [telegramdesktop/tdesktop#17172]
### Steps to reproduce

1. Open any chat
2. Press PgUp to scroll history backwards

### Expected behaviour

History is scrolled

### Actual behaviour

Nothing happens

### Operating system

Ubuntu 21.04, KDE

### Version of Telegram Desktop

3.1.12beta

### Installation source

Static binary from official website

**Comment by elw00d** [comment]
very annoying issue

**Comment by Aokromes** [comment]
try 3.1.13

**Comment by elw00d** [comment]
fixed, thank you

**Comment by torkve** [comment]
same for me, 3.1.13 fixes issue.
