### ISSUE TITLE
Can't open telegram

### ISSUE THREAD

**Issue by aliazani** [telegramdesktop/tdesktop#17182]
### Steps to reproduce

1. Downloaded version 3.2.0 for Linux
2. Try to open telegram-desktop
3. nothing happened

### Expected behaviour

Open the app

### Actual behaviour

Nothing happened

### Operating system

Linux(Manjaro)

### Version of Telegram Desktop

3.2.0

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@aliazani Please launch it from Terminal and post the output.

**Comment by aliazani** [comment]
> @aliazani Please launch it from Terminal and post the output.

I'd tried that too, but no output and no logs nothing

**Comment by john-preston** [comment]
@aliazani No error? Simply instantly quits?

**Comment by aliazani** [comment]
> @aliazani No error? Simply instantly quits?

I don't have telegram as running process.
nothing no output, no running process, no error!

**Comment by john-preston** [comment]
@aliazani Weird.. I guess the cause is the same as #17183, but I'm not sure.

**Comment by alk0** [comment]
Same behavior on Manjaro (Arch), noticed yesterday with beta, downgraded, now the same with stable. Run, "Integrate?", decline, just "Run once" (accepting does work either). Terminal output (may not be relevant):
`qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 560, resource id: 10496371, major code: 40 (TranslateCoords), minor code: 0`
Two processes remain active (run with `./Telegram`), but nothing else happens:
`/usr/lib/appimagelauncher/binfmt-bypass /home/username/Telegram/Telegram`
`/home/username/Telegram/Telegram`

**Comment by noorbala7418** [comment]
Hello.
Unfortunately Same error.

**Comment by ShrirajHegde** [comment]
This seems to be incompatibility with [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher/) appimage launcher installing itself as interpreter for AppImages

# Temporary Fix
For Temporary fix, uninstall AppImageLauncher and run `sudo systemctl restart systemd-binfmt` OR reboot

**Comment by noorbala7418** [comment]
I downgraded to 3.1.8 and disabled updates.

your solution in good. thanks a lot.

**Comment by john-preston** [comment]
Please test if that one launches fine:

https://td.telegram.org/tlinux/tsetup.3.2.1.tar.xz

**Comment by aliazani** [comment]
> Please test if that one launches fine:
> 
> https://td.telegram.org/tlinux/tsetup.3.2.1.tar.xz

looks good to me and everything is working.

**Comment by joelmzj** [comment]
> Please test if that one launches fine:
> 
> https://td.telegram.org/tlinux/tsetup.3.2.1.tar.xz

Thnaks a lot. It's working fine now.
You're the best team! :)

**Comment by anviar** [comment]
```
❯ snap list
telegram-desktop   3.1.11                      3277   latest/stable    telegram.desktop  -
❯ snap refresh
telegram-desktop 3.2.0 from Telegram FZ-LLC (telegram.desktop) refreshed
❯ telegram-desktop
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
❯ snap refresh
All snaps up to date.
❯ snap list --all telegram-desktop
Name              Version  Rev   Tracking       Publisher         Notes
telegram-desktop  3.1.11   3277  latest/stable  telegram.desktop  disabled
telegram-desktop  3.2.0    3323  latest/stable  telegram.desktop  -
❯ snap revert --revision=3277 telegram-desktop
telegram-desktop reverted to 3.1.11
```
snap package broken as well

**Comment by mostafaznv** [comment]
```
➜  ~ telegram-desktop
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
```

problem solved after downgrading to 3.1.11

**Comment by Aokromes** [comment]
> Ubuntu 21.10 Telegram Desktop 3.2.0
> 
> Error:
> 
> ```
> ➜  ~ telegram-desktop
> telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
> ```
> 
> problem solved after downgrading to 3.1.11

https://github.com/telegramdesktop/tdesktop/issues/17182#issuecomment-959801720

**Comment by mostafaznv** [comment]
> Please test if that one launches fine:
> 
> https://td.telegram.org/tlinux/tsetup.3.2.1.tar.xz

Worked fine for me

Ubuntu 21.10

**Comment by aliazani** [comment]
solved by installing v3.2.1 from https://telegram.org/dl/desktop/linux.

**Comment by searleser97** [comment]
> @aliazani Please launch it from Terminal and post the output.

```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
```

This is the output I get in my case

**Comment by searleser97** [comment]
> solved by installing v3.2.1 from https://telegram.org/dl/desktop/linux.

I had to do this as well

**Comment by searleser97** [comment]
This discussion appears to be definitely related: https://bugs.launchpad.net/snapd/+bug/1916745

**Comment by NotStatilko** [comment]
Hello. Recently i updated my Debian 10 to Debian 11, and i faced same issue, the TelegramDesktop doesn't run and in Terminal i recieve 
```
QIBusPlatformInputContext: invalid portal bus.
Fontconfig error: "/etc/fonts/local.conf", line 1: no element found
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
```
Although, when i disable render via OpenGL in Advanced Settings, it works just fine.

I tested `tsetup.3.2.1.tar.xz` with no changes so far. I don't know what's the problem is, but can i disable OpenGL render with some command-line argument?
