### ISSUE TITLE
Windows 11 -  Quitting application on multi-monitor setup does not launch from last window location

### ISSUE THREAD

**Issue by FuryRosewood** [telegramdesktop/tdesktop#17188]
### Steps to reproduce

1. Have a system with more than one monitor on Windows 11 and launch Telegram Desktop on a specific monitor and position (Location of application on my system was Monitor 2 of 4 and in the lower right corner of that monitor)
2. Close the application while positioned in a specific location and press the (x) in the upper right corner and close the application
3. Re-open the application and observe that window appears in the previously closed location
2. With in the desired location from step 2, quit the application via the docked icon with Right Click > Quit
3. Relaunch Application
4. Observe that the application launches on a different monitor (in my case it launched on Monitor 3)

### Expected behaviour

Quitting behavior and closed window behavior will be the same.

### Actual behaviour

Closing the window behavior retains the last monitor and position location, but quitting the application outright does not.

### Operating system

Windows 11: OS Version:                10.0.22000 N/A Build 22000

### Version of Telegram Desktop

v 3.2 03.11.21

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Enable debug logs via `debugmode` cheat code (go to settings and enter the word blindly, like cheat code in a game, it should show a confirmation dialog), reproduce the issue and get lines containing `Window Pos` from the appropriate log_NN_NN.txt (NN_NN is the time, they're created each 15 minutes) file. You can find log files with `viewlogs` cheat code, in the DebugLogs subfolder.
