### ISSUE TITLE
[Feature Request] Add syntax highlighting for programming language code

### ISSUE THREAD

**Issue by kounkou** [telegramdesktop/tdesktop#17187]
### Is your feature request related to a problem?

NA

### Describe the solution you'd like

Hi,
When writing a code snippet on Telegram, no syntax highlighting is made.
The code snippet is created with open and closing  \`\`\`
Having syntax highlighting could be a huge plus for developer communities using Telegram and could
be a competitive alternative to Discord.
Different Syntax highlighting could be activated with \`\`\`cpp, \`\`\`python, \`\`\`bash, etc.

Telegram sample code snippet screenshot :
<img width="507" alt="Screen Shot 2021-11-03 at 5 13 24 PM" src="https://user-images.githubusercontent.com/2589171/140236184-52c1d196-1b02-46c2-9a63-5449455638eb.png">

### Describe alternatives you've considered

Currently, Discord provides syntax highlighting.

### Additional context

NA

**Comment by ilya-fedin** [comment]
#250
