### ISSUE TITLE
[Feature Request] More Protocol Support

### ISSUE THREAD

**Issue by Krutonium** [telegramdesktop/tdesktop#17180]
### Is your feature request related to a problem?

Yes, Specifically it's not currently possible to do somthing like send a link like `steam://rungameid/12110` because Telegram doesn't recognize it as a URL. 

### Describe the solution you'd like

I would like for Telegram to query the registry as described in https://docs.microsoft.com/en-us/windows/win32/search/-search-3x-wds-ph-install-registration for protocols that are valid on the current PC and enable them in chat, making them clickable. Obviously they shouldn't have previews, unless it's a protocol you specifically add support for in that regard, for example making the link I showed above show the iconograhy for Vice City - Possible, but unnecessary. The same thing goes for Linux, though I am not sure how to query it there - In that case it may be simpler to just parse anything resembling a link as a link and let the user try to open it using `xdg-open`.

### Describe alternatives you've considered

I mean, I briefly considered a webserver a user can install to do `http://localhost/steam://rungameid/12110` but that would require everyone to install it and be a bit... dumb.

**Comment by ilya-fedin** [comment]
Protocol whitelist as well as URL parsing is on server side
