### ISSUE TITLE
Failed to register AppImage in system via libappimage

### ISSUE THREAD

**Issue by thob** [telegramdesktop/tdesktop#17183]
### Steps to reproduce

Download Linux tar.xz
Launch w/ Appimagelauncher
Integrate and run 

Result: "Failed to register AppImage in system via libappimage"

### Expected behaviour

Lauch Telegram

### Actual behaviour

Error message

### Operating system

Pop!_OS 21.04

### Version of Telegram Desktop

3.2.0

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Please test if that one launches fine:

https://td.telegram.org/tlinux/tsetup.3.2.1.tar.xz

**Comment by noorbala7418** [comment]
it works. 
thanks a lot

**Comment by joelmzj** [comment]
Thanks a lot. It's working now.
