### ISSUE TITLE
Перестал запускаться

### ISSUE THREAD

**Issue by Drachoon** [telegramdesktop/tdesktop#17191]
4 Ноября 2021.  Перестал запускаться. Вчера работал отлично.
Пробовал удалить и установить заново через Ubuntu Software. Не помогло.
ОС Ubuntu 21.10

Как можно запустить прилажение через консоль, чтобы посмотреть проблемы и зарепортить?

**Comment by ilya-fedin** [comment]
This bugtracker is english only

**Comment by Aokromes** [comment]
update to 3.2.1

**Comment by Drachoon** [comment]
Не шарю по ангийски я живу в России. Так что извиняйте. И насколько мне известно Телеграм создан разработчиками из России так что не вижу проблем.

Спасибо за внимание. Скачал  инсталятор с сайта. Запустил. Прилажение побежало.
