### ISSUE TITLE
"Write a message.." is missing a third dot

### ISSUE THREAD

**Issue by doublejumper** [telegramdesktop/tdesktop#1719]
I feel bad submitting an issue this small, but now that I have noticed it it'll bother me forever. And the web version has 3 dots...

**Comment by DaFri-Nochiterov** [comment]
https://github.com/telegramdesktop/tdesktop/pull/1134#issuecomment-145264228

**Comment by doublejumper** [comment]
Ah ok, sorry. I only searched with "write a message".
