### ISSUE TITLE
[Feature Request] labeling chats and folder accourding to labels.

### ISSUE THREAD

**Issue by mojighahar** [telegramdesktop/tdesktop#17192]
### Is your feature request related to a problem?

Now we can't add a chat to a folder straightly.

### Describe the solution you'd like

We can add labels to chats and create folders that include specific labels.
For example, we have a work folder to organize our business-related chats. Every new person that contacts us about our work should be added separately in the folder setting now.
But we can add a "work" label to it and automatically appear in the work folder.

### Describe alternatives you've considered

Nothing

### Additional context

Nothing

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
