### ISSUE TITLE
Open the app under Fedora 34 are not very compfortable

### ISSUE THREAD

**Issue by tuxmaster5000** [telegramdesktop/tdesktop#17199]
### Steps to reproduce

1. Start the app, minimize it to the icon pane.
2. When an message comes, try to open the app

### Expected behaviour

Simple click on the icon to open the app.

### Actual behaviour

On click at the icon only an sub menu will show, with an entry "Open Telegram". This is not very comfortable, because using Fedora 33 an simple click on the icon was enough.

### Operating system

Fedora 34

### Version of Telegram Desktop

3.2.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This is behavior of your system, not of Telegram. You should report that to your system, not to Telegram.

**Comment by tuxmaster5000** [comment]
It looks not true, because other apps like anydesk and the nextcloud desktop client will work. And both don't comes from OS.

**Comment by ilya-fedin** [comment]
There's two tray protocols: SNI and XEmbed. SNI is a newer protocol and behavior is defined by the panel, XEmbed is older protocol (X11-only) and behavior is controlled by application. Qt (that is used by tdesktop) prefers SNI whenever it's supported by the system.
