### ISSUE TITLE
creating group invite links that need approval is not available

### ISSUE THREAD

**Issue by lemmy04** [telegramdesktop/tdesktop#17190]
### Steps to reproduce

1. manage an existing group
2. create a new invite link
3. there is no option to set it to require admin approval

also, there is not much point to this as long as the default group invite link can be used without approval...

### Operating system

Linux, Windows

### Version of Telegram Desktop

3.2.0

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment]
Is your group public (that is, it has a public username)? If so, that feature is not available for public groups

> also, there is not much point to this as long as the default group invite link can be used without approval...

That's true for public group, this is why it's not available there. In private groups admins can decide not to share the main invite link

**Comment by lemmy04** [comment]
> Is your group public (that is, it has a public username)? If so, that feature is not available for public groups
> > also, there is not much point to this as long as the default group invite link can be used without approval...
> This is true for public group, this is why it's not available there. In private groups admins can decide not to share the main invite link

then why is it available for the same group as soon as I use a mobile client...?

**Comment by RememberTheAir** [comment]
Never mind, forget what I said: it's possible to require the admins approval for public groups too

If you could provide a screen recording of the steps you take to generate an invite link, it would be helpful

**Comment by lemmy04** [comment]
I was just poking around with that group and I see a number of other settings in **new** groups that my existing group does NOT have... Could that be because it's been created several years ago...?

**Comment by lemmy04** [comment]
screen capture is here: https://youtu.be/oEMVrz6EXH8

**Comment by lemmy04** [comment]
I think I know what's going on, the group in question is a location based group, could it be that those are a special type of group that is wide open to anyone who is physically close enough, and impossible to lock down?

**Comment by lemmy04** [comment]
> 
> 
> ~Is your group public (that is, it has a public username)? If so, that feature is not available for public groups~ **wrong**, admins' approval is available in public chats too
> 
> > also, there is not much point to this as long as the default group invite link can be used without approval...
> 
> ~This is true for public group, this is why it's not available there. In private groups admins can decide not to share the main invite link~ see above

So there is no way to hide the main invite link even in a private group, or make the main invite link an "approval required" link?

**Comment by RememberTheAir** [comment]
> So there is no way to hide the main invite link even in a private group, or make the main invite link an "approval required" link?

Exactly, it's not possible. Every private group has a main, permanent invite link that can only be revoked (= recreated). But, if you don't share it nobody will be able to use it to join. You can set up other secondary invite link that require admin approval and share them

> I think I know what's going on, the group in question is a location based group, could it be that those are a special type of group that is wide open to anyone who is physically close enough, and impossible to lock down?

You're right, admins approval is not available for location-based groups

**Comment by lemmy04** [comment]
> > So there is no way to hide the main invite link even in a private group, or make the main invite link an "approval required" link?
> 
> Exactly, it's not possible. Every private group has a main, permanent invite link that can only be revoked (= recreated). But, if you don't share it nobody will be able to use it to join.

Can't anyone who is **in** the group see the invite link?

> > I think I know what's going on, the group in question is a location based group, could it be that those are a special type of group that is wide open to anyone who is physically close enough, and impossible to lock down?
> 
> You're right, admins approval is not available for location-based groups

Just for laughs: go join a few location based groups around your location and check what is going on in there...
I would be surprised if you found ONE that does not have floods of porn & drug spam in them to the point that everybody else has abandoned the group.

**Comment by RememberTheAir** [comment]
> Just for laughs: go join a few location based groups around your location and check what is going on in there...
I would be surprised if you found ONE that does not have floods of porn & drug spam in them to the point that everybody else has abandoned the group.

Ye, I'm very aware of the current state of local groups... I'm also moderating one and it's a constant fight against spam

**Comment by lemmy04** [comment]
and the fact that the developers that do the actual protocol don't care doesn't help - the request for more and better privacy in telegram has been ignored at least a dozen times by now.

it's actually ironic that a messenger that prides itself on privacy has such huge privacy issues.

**Comment by lemmy04** [comment]
anyway i believe this can be closed - not a bug, but a fact with local groups.
