### ISSUE TITLE
snap package ver 3.2.0 is broken

### ISSUE THREAD

**Issue by anviar** [telegramdesktop/tdesktop#17195]
### Steps to reproduce

```
❯ snap refresh
telegram-desktop 3.2.0 from Telegram FZ-LLC (telegram.desktop) refreshed
❯ telegram-desktop
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
```

I tested version 3.2.1 from edge channel - same result.

```
❯ snap refresh --channel=latest/edge telegram-desktop
telegram-desktop (edge) 3.2.1-4-gf4a3d87b5 from Telegram FZ-LLC (telegram.desktop) refreshed
❯ telegram-desktop
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
```

### Expected behaviour

telegram application running

### Actual behaviour

not starting

### Operating system

Ubuntu 21.10

### Version of Telegram Desktop

3.2.0

### Installation source

Snap

**Comment by gabriele2000** [comment]
`gabriele@msi-gp72m:~$ telegram-desktop
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/lib/snapd/lib/gl/libGLX.so.0)
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/lib/snapd/lib/gl/libGLdispatch.so.0)`

Same telegram version, snap, pop_os 21.10

**Comment by ilya-fedin** [comment]
This is a snapd bug, see #17004

**Comment by john-preston** [comment]
Unfortunately this is a snapd problem. You can upvote the relevant bug reports / issues here:

https://bugs.launchpad.net/snapd/+bug/1916745

https://forum.snapcraft.io/t/egl-using-snaps-on-impish-seem-to-be-broken-when-using-the-nvidia-proprietary-driver/25715/39

I was told that they're working on it right now.

**Comment by tommessb** [comment]
telegram-desktop 
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)

i have this error since the telegram-desktop update 2 days ago. Telegram worked perfect before that day in Ubuntu 21.10. The installation is only a week old. Your links are pointing to old issues from feb and jul  2021. They are still not fixed? 
And why did it stop working after an upgrade of the telegram-desktop snap package?. - must be something wrong with that package!

**Comment by ilya-fedin** [comment]
> They are still not fixed?

Yeah, looks like this was a low priority for them since not so much users were affected.

> And why did it stop working after an upgrade of the telegram-desktop snap package?

Qt 6 update, now Qt requires GL.

**Comment by john-preston** [comment]
It looks like @ilya-fedin found a workaround and implemented it.

We should wait for the 3.2.2 update to become available and test it.

**Comment by john-preston** [comment]
Ok, it is available in the stable channel. @anviar @gabriele2000 @tommessb

**Comment by gabriele2000** [comment]
> Ok, it is available in the stable channel. @anviar @gabriele2000 @tommessb

HEHE it's F-I-X-E-D!!!

I'm so happy, thanks a lot man
