### ISSUE TITLE
Part of sticker blurred in preview of pack

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1720]
![image](https://cloud.githubusercontent.com/assets/10401817/13503322/6c38fc12-e1a1-11e5-9351-deff94285881.png)

(I think it's only with unloaded stickers, because if you go to next sticker and go back, you will see normal sticker without blur)

TDesktop version: **0.9.29 dev**

**Comment by DaFri-Nochiterov** [comment]
Some details I've got.
It's happening when you in chat or settings.

**Comment by stek29** [comment]
Can you still reproduce it?

**Comment by DaFri-Nochiterov** [comment]
CNR anymore
