### ISSUE TITLE
Icons looks strange on Kubuntu 21.04 after last update

### ISSUE THREAD

**Issue by goganchic** [telegramdesktop/tdesktop#17200]
### Steps to reproduce

1. Set global scale 125%
2. Install Telegram from snap on Kubuntu 21.04
3. Open Telegram
4. Look at the icons

### Expected behaviour

Icons looks OK

### Actual behaviour

Telegram has updated recently and now icons and avatars look ugly. Several days ago before this update everything looked OK.

![bug1](https://user-images.githubusercontent.com/193946/140485905-cf190f26-c102-4503-adf0-4db416b96ba8.png)
![bug2](https://user-images.githubusercontent.com/193946/140485912-308f78f1-5d37-496d-88ff-bec238507e1b.png)
![bug3](https://user-images.githubusercontent.com/193946/140486521-ed501fad-81dd-4dd2-88a8-80ee712a6e17.png)

### Operating system

Kubuntu 21.04

### Version of Telegram Desktop

3.2

### Installation source

Snap

**Comment by Bezkup** [comment]
I encountered this bug too, but all the icons, chats and media looks blurred. Manjaro 21 KDE

**Comment by ilya-fedin** [comment]
#17173

**Comment by john-preston** [comment]
Please check the 3.2.2 version from https://desktop.telegram.org or when it becomes available as a snap update.

**Comment by goganchic** [comment]
Now everything works fine. Thanks a lot!
