### ISSUE TITLE
telegram from snap stopped working on ubuntu 21.10

### ISSUE THREAD

**Issue by Selmi** [telegramdesktop/tdesktop#17204]
### Steps to reproduce

1. install telegram-desktop
2. launch it 

### Expected behaviour

application works

### Actual behaviour

selmi@selmi-pc:~$ telegram-desktop 
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)

### Operating system

ubuntu linux 21.10

### Version of Telegram Desktop

3.2.0

### Installation source

Snap

**Comment by john-preston** [comment]
Unfortunately this is a snapd problem. You can upvote the relevant bug reports / issues here:

https://bugs.launchpad.net/snapd/+bug/1916745

https://forum.snapcraft.io/t/egl-using-snaps-on-impish-seem-to-be-broken-when-using-the-nvidia-proprietary-driver/25715/39

**Comment by Selmi** [comment]
thanks, i will

**Comment by john-preston** [comment]
It looks like @ilya-fedin found a workaround and implemented it.

We should wait for the 3.2.2 update to become available and test it.

**Comment by john-preston** [comment]
Ok, it is available in the stable channel. @Selmi

**Comment by Selmi** [comment]
it works now, thanks
