### ISSUE TITLE
[Question] is there an ETA of when the snap package will be fixed?

### ISSUE THREAD

**Issue by indirected** [telegramdesktop/tdesktop#17201]
After the recent update of telegram in snap, the app is not opening any more. from where i have looked in the issues this is a libc problem from telegram side. there is the option of downloading the binary from the website but i don't want to setup everything again. is there a fix coming? when?

**Comment by ilya-fedin** [comment]
AFAIK, this is a snapd bug, so you should ask snapd developers. See #17004.

**Comment by indirected** [comment]
So is there a work around?
i would pretty much rather continue using snap for telegram. this happened to me after the last update to 3.2.0. any suggestions on how to downgrade to an older version? would it help?

**Comment by ilya-fedin** [comment]
You can install static binary from https://desktop.telegram.org. It's the main distribution channel of tdesktop and is not dependent on third-party daemons.

> Also what about the apt telegram packages? are those official? the most promising one to me is:
> `telegram-desktop/impish 3.1.1+ds-1 amd64`

No, they're maintained by distribution maintainers.

**Comment by john-preston** [comment]
Unfortunately this is a snapd problem. You can upvote the relevant bug reports / issues here:

https://bugs.launchpad.net/snapd/+bug/1916745

https://forum.snapcraft.io/t/egl-using-snaps-on-impish-seem-to-be-broken-when-using-the-nvidia-proprietary-driver/25715/39

I was told that they're working on it right now.

**Comment by indirected** [comment]
Yeah i have seen those bugs and since snap seems to be very slow at patching bugs i decided to ask here to see if there is a work around or something. I use telegram on daily basis so for now I'm using the binary from the website. I will probably be back on snap when it is fixed.
thanks for the effort by the way. much appreciated.

**Comment by john-preston** [comment]
Ok, it is available in the stable channel. @indirected

**Comment by indirected** [comment]
Awesome. Dropped it a test and it's working perfectly. Thanks!
