### ISSUE TITLE
Telegram Desktop (snap package) doesn't start in Ubuntu 21.10 due to GLIBC_2.33 is missing

### ISSUE THREAD

**Issue by diegolagoglez** [telegramdesktop/tdesktop#17202]
### Steps to reproduce

1. Upgrade Telegram to the latests snap version (snap refresh telegram-desktop): telegram-desktop   3.2.0                       3323   latest/stable    telegram.desktop  -
2. Launch telegram-desktop from console: telegram-desktop.
3. This error is shown: telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)

### Expected behaviour

Telegram Desktop should start and work as expected.

### Actual behaviour

Telegram Desktop indicates that there is a missing library version:

telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)

### Operating system

Ubuntu 21.10 64bit (with all packages upgraded up to the latest version)

### Version of Telegram Desktop

3.2.0 (snap package 3323) - channel: latest/stable

### Installation source

Snap

### Logs

```shell
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
```

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/17004

**Comment by john-preston** [comment]
Unfortunately this is a snapd problem. You can upvote the relevant bug reports / issues here:

https://bugs.launchpad.net/snapd/+bug/1916745

https://forum.snapcraft.io/t/egl-using-snaps-on-impish-seem-to-be-broken-when-using-the-nvidia-proprietary-driver/25715/39

**Comment by john-preston** [comment]
It looks like @ilya-fedin found a workaround and implemented it.

We should wait for the 3.2.2 update to become available and test it.

**Comment by john-preston** [comment]
Ok, it is available in the stable channel. @diegolagoglez

**Comment by diegolagoglez** [comment]
Thanks so much for your comments!
