### ISSUE TITLE
[Question] Is there any way to use direct connection for calls even when proxies are used

### ISSUE THREAD

**Issue by escape0707** [telegramdesktop/tdesktop#17215]
In the place I live, I have to use a proxy to connect to Telegram. I can set up a socks5 or transparent one.

The only thing that bother me to use Telegram to replace my old IM software is when I have to use telegram behind a proxy, I can't use the real IP to direct connect to my friends and establish a clear and low-latency voice call. I'll have to stick with some other software that are not blocked by the ISP.

Is there anyway to set up telegram so that it use the proxy to connect to telegram's STUN server but report my real public IP for other's to establish direct connection with me?

**Comment by escape0707** [comment]
Yes.

**Comment by escape0707** [comment]
bruh

**Comment by ilya-fedin** [comment]
No, there's no such option, but only socks 5 proxies are supported with calls, so you can try to use that lack of support for HTTP proxies as a workaround

**Comment by escape0707** [comment]
> No, there's no way

Oh, thanks for the reply. I was in the middle of editing my new thought about this after half a year but got interrupted by a call and forgot about sending it.

Anyway I originally thought that Telegram can use the way that RFC 5128 said in 3.3.2 that ICE protocol will use multiple endpoints, both private and public to try to P2P connect and use the first established one. I though Telegram can use the same idea that if the user tried to make a direct p2p call, just exchange every interfaces' endpoint information, private, public and proxied public identified by the Telegram rendezvous server with each other and try to connect with each endpoint.

Is that possible to implement? That might be useful if the users are in China or Iran but still want to P2P call without routing to both of their VPN, etc.

**Comment by ilya-fedin** [comment]
I don't have an answer for that question, sorry. You can open a new question issue and maybe someone other will answer (no guarantee though).
