### ISSUE TITLE
Telegram 3.2.2 typing bug on mac os

### ISSUE THREAD

**Issue by nightshadecf** [telegramdesktop/tdesktop#17219]
### Steps to reproduce

1. Add input source Vietnamese - Telex (macOs Keyboard preference)
2. Switch to new input source (Telex)
3. Try to type on the chat input field

-> the chat field doesn't reflect any changes as if nothing is typed

### Expected behaviour

The chat field should display the character being typed

### Actual behaviour

Nothing happens. It works perfectly fine on 3.1.9.

### Operating system

macOs Catalina 10.15.7

### Version of Telegram Desktop

3.2.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/17176

**Comment by john-preston** [comment]
@nightshadecf Can you please check this version: https://td.telegram.org/tmac/tsetup.3.2.5.dmg

Does it work fine?

**Comment by phucnmdng** [comment]
Same problem here but the 3.2.5 version was resolved my problem.
Thank you.
