### ISSUE TITLE
[Feature Request] Disable notification an hide messages under spoiler for blocked users in groups

### ISSUE THREAD

**Issue by Azimov2020** [telegramdesktop/tdesktop#17217]
### Is your feature request related to a problem?

Some users really annoying and spam in group chats.

### Describe the solution you'd like

It's not a "API issue".
Just turn off notification for blocked users and hide their messages under spoiler, goddamn it!
Client can do this!
```
If message.userID in blockedListArray:
    message.Hide()
```

### Describe alternatives you've considered

Tell Durov I ready pay for this, if he lost all his developers team.

**Comment by ilya-fedin** [comment]
> It's not a "API issue".

"API issue" doesn't mean the feature can be implemented only on server, it means the feature _should_ be implemented server-side and clients aren't allowed to implement it client-side. Ans this feature is an API issue.

**Comment by Azimov2020** [comment]
> clients aren't allowed to implement it client-side. Ans this feature is an API issue.
OK, Let it be API, why not?

**Comment by ilya-fedin** [comment]
I'm not tortuing anyone

**Comment by Aokromes** [comment]
> > clients aren't allowed to implement it client-side. Ans this feature is an API issue.
> 
> OK, Let it be API, why not? It is not rocket science, isn't it? Why are you torturing people?

upvote here https://bugs.telegram.org/c/37

**Comment by Azimov2020** [comment]
It is simple feature, which exist in software 20 years ago.
Thousands users already ask your team for this, I'm sure they ready pay for it.
But declare all request. Just wonder  why?

**Comment by Azimov2020** [comment]
Just some Durov whim?

**Comment by ilya-fedin** [comment]
I'm not a part of Telegram team. This is github and anyone can answer you :)

**Comment by Azimov2020** [comment]
Thanks for answer.
Sad that they not allowed to implement it client-side.

**Comment by 411an** [comment]
>Why are you torturing people?
We ask for this more than 6 years, but they dont answer.

I did it for windows desktop version. Maybe it helpps you.
https://sites.google.com/view/ignoram/
