### ISSUE TITLE
Telegram Desktop latest version refuses to boot on Debian 10 buster under Chrome OS Crostini container

### ISSUE THREAD

**Issue by sks316** [telegramdesktop/tdesktop#17210]
### Steps to reproduce

1. Update to latest Telegram Desktop
2. Attempt to open
3. Telegram Desktop never opens

### Expected behaviour

Telegram Desktop should open and I should see my chats.

### Actual behaviour

Telegram Desktop silently fails to open when launched from the app launcher. If launched via the Terminal, it gives the following error:
```
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
qt.qpa.wayland: No shell integration named "xdg-shell" found
qt.qpa.wayland: Loading shell integration failed.
qt.qpa.wayland: Attempted to load the following shells QList("desktop-app-xdg-shell", "xdg-shell")
error: : cannot open
error: : cannot open
error: : cannot open
```
If I use an earlier version of the client, this does not happen and Telegram Desktop opens successfully.

### Operating system

Debian GNU/Linux 10 (buster) on Chrome OS x86_64

### Version of Telegram Desktop

v3.2.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Check that your Wayland compositor supports xdg-shell. It's required due to update to Qt 6, wl-shell is dperecated and is no longer supported.

**Comment by sks316** [comment]
@ilya-fedin How do I check that?

**Comment by ilya-fedin** [comment]
> How do I check that?

What do you want to check?

**Comment by sks316** [comment]
How do I check if my Wayland compositor supports xdg-shell?

**Comment by ilya-fedin** [comment]
I know only two ways:
1. Looking at its source code
2. Trying to run applications that support only xdg-shell (e.g. Telegram)
There's not only xdg-shell and wl-shell though, there's also xdg-shell-v5 and xdg-shell-v6, they're deprecated as well and removed from Qt 6, as well. I don't know which protocols Crostini supports, but it's clear it doesn't support the stable xdg-shell since you can't launch Telegram.

**Comment by sks316** [comment]
Well then, we know Crostini doesn't support xdg-shell
I assume there's no way for me to keep using Telegram Desktop then?

**Comment by ilya-fedin** [comment]
Looks like no way :(
xdg-shell is here for multiple years and all native Linux compositors support it. Why Crostini doesn't? Maybe it is a good idea for you as a user to ask them to support it? More toolkits will remove support for old protocols and more applications will stop running...

**Comment by ilya-fedin** [comment]
Looks like it's possible to make Qt fallback to XWayland with some patching...
