### ISSUE TITLE
Поехали шрифты после одного из последних обновлений

### ISSUE THREAD

**Issue by zorn-v** [telegramdesktop/tdesktop#17214]
### Steps to reproduce

Обновить до версии 3.2.2

### Expected behaviour

Как было раньше хотя бы.

### Actual behaviour

![image](https://user-images.githubusercontent.com/12619075/140627095-b52fb3c7-7a4c-4b0e-a181-764017395a0f.png)
"Пробелы" где попало и буквы друг к другу жмутся.

### Operating system

Ubuntu 21.10

### Version of Telegram Desktop

3.2.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This bugtracker is english-only
