### ISSUE TITLE
[Feature Request] Add "Start secret chat" in the desktop version

### ISSUE THREAD

**Issue by Parmanand96** [telegramdesktop/tdesktop#17216]
### Is your feature request related to a problem?

I'm using Telegram on both my desktop and phone. On phone, I can start a secret chat with anyone but this option seems to be missing in the desktop version of Telegram. Why? Is there any plan on including this feature in the desktop version of telegram in the future?

### Describe the solution you'd like

?

### Describe alternatives you've considered

?

**Comment by john-preston** [comment]
@Parmanand96

For why there is a long and old thread: https://github.com/telegramdesktop/tdesktop/issues/871

Regarding the plan - there is (a very distant one, without any ETAs).
