### ISSUE TITLE
[Themes] Voice message animated recording icon using a different entry for hover

### ISSUE THREAD

**Issue by Henriquelay** [telegramdesktop/tdesktop#17212]
### Steps to reproduce

1. Edit a theme.
2. Use a color for `attentionButtonFg`. It changes the recording voice message animated icon.
3. Use a different color for `attentionButtonFgOver`. Voice message does not change to designated color when hovering.

### Expected behaviour

Voice message animated icon using `Over` version of it's color for hovering.

### Actual behaviour

Voice message animated uses `windowBgActive`, a completely different entry.

### Operating system

Arch Linux 5.14.16-arch1-1

### Version of Telegram Desktop

3.2.2

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@Henriquelay Because it has those colors by design. If absolutely necessary there could be a separate pair of keys in the theme for exactly that button, that would be derived from two currently used keys respectively, but I'd rather not add them, the palette is very large as it is already 😅
