### ISSUE TITLE
how to add a new language in telegram desktop?

### ISSUE THREAD

**Issue by AMP999** [telegramdesktop/tdesktop#17218]

**Comment by ilya-fedin** [comment]
https://translations.telegram.org/

**Comment by AMP999** [comment]
also i've found readLangPack() function which changes _values vector. my question is when for the first time i change the language to other than english. telegram downloads language or all of available languages are hardcoded somewhere? i tried to find them but i couldn't

**Comment by AMP999** [comment]
also i have changed lang.strings values but somehow _values is generated normally. how it recovers it's self when lang.strings is changed?

**Comment by ilya-fedin** [comment]
>  telegram downloads language or all of available languages are hardcoded somewhere?

It downloads. English translation is downloaded from the cloud as well, that's what your changes are overridden.

**Comment by AMP999** [comment]
thank you. one more question. is this repository (https://github.com/desktop-app) a library built and used by telegram or is it a general purpose library?

**Comment by ilya-fedin** [comment]
> s this repository (https://github.com/desktop-app) a library built and used by telegram or is it a general purpose library?

It's a library built by @john-preston and used in his projects
