### ISSUE TITLE
Stickers pack don't work in markdown link on TDesktop

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1722]
When adding a stickers pack link through markdown (bot, inline bot, etc) this works only on Android.
In TDesktop after authorizing open the link, the modal dialog appears and closes automatically in a blink.

Example: https://telegram.me/stickersChannel/927

Tested in: TDesktop 0.9.29 dev (fedora 64 bit)

Cheers

**Comment by telegramdesktop** [comment]
Is there a quick way to test such link?

**Comment by DaFri-Nochiterov** [comment]
Send "Custom markdown" in `@bold [Telegram Stickers](https://telegram.me/addstickers/TGIcons)`
Try to open "Telegram Stickers" link

**Comment by diazbastian** [comment]
@DaFri-Nochiterov Thank you

**Comment by telegramdesktop** [comment]
Should be fixed in the 0.9.31 version (currently dev can update to it, stable will update to 0.9.32 soon).

**Comment by DaFri-Nochiterov** [comment]
Fixed ;3
