### ISSUE TITLE
Inconsistent cursor for snap 

### ISSUE THREAD

**Issue by giammi56** [telegramdesktop/tdesktop#17220]
### Steps to reproduce

1. Install Telegram from snap store
2. Launch Telegram-desktop
3. In a conversation, hoover over a link (e.g. stickers, images, etc.).

### Expected behaviour

Telegram should be consistent with the system theme for cursors.

### Actual behaviour

Telegram has weird black pointer with weirder "hand selection" tool as already pointed out [here](https://github.com/telegramdesktop/tdesktop/issues/10321)

### Operating system

Ubuntu 20.04.3

### Version of Telegram Desktop

3.2.2 

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Do other snapped Qt applications display cursor right? Why do you think this is a Telegram bug and is not snap/Qt bug?

**Comment by giammi56** [comment]
Thank you for pointing this out. Yes, all other Qt software I have uses the same cursors. According to Qt5 config tool, I am running Breeze style with a custom Palette and Breeze Dark icon theme. I am not an expert, thus it could still be a bug of Qt or snap. Which debugging procedure would you suggest me to identify the source of the problem?

**Comment by ilya-fedin** [comment]
> Which debugging procedure would you suggest me to identify the source of the problem?

You can also test snapped gtk applications and host Qt applications
