### ISSUE TITLE
A new instance launches instead of restoring the existing one from tray

### ISSUE THREAD

**Issue by slacking247** [telegramdesktop/tdesktop#17227]
### Steps to reproduce

1. Open Telegram
2. Hide it to tray by closing the window
3. Open Telegram again

### Expected behaviour

Opening Telegram again should bring up the hidden to tray instance of it.

### Actual behaviour

Another instance of Telegram is opened instead, while the existing one continues to stay in the tray.
![](https://user-images.githubusercontent.com/84628426/141074946-a81f10c1-aebd-48b8-8bfc-3f98cf0287c1.png)

### Operating system

Zorin OS 16, GNOME 3.38.4

### Version of Telegram Desktop

3.2.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Ensure that your flatpak version is not less than 1.12.0, older versions won't work with tdesktop right anymore due to update to Qt 6

**Comment by slacking247** [comment]
Thank you, that solved the issue.
