### ISSUE TITLE
Uploading image bug

### ISSUE THREAD

**Issue by dambosin** [telegramdesktop/tdesktop#17224]
### Steps to reproduce

1. drag and drop  90 images without compression
2. Wait until they will be prepared to upload

### Expected behaviour

Images ready to be uploaded

### Actual behaviour

Telegram desktop is closed

### Operating system

Windows 10

### Version of Telegram Desktop

3.2.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta and send crash id on next restart.
