### ISSUE TITLE
Scroll wheel stops working

### ISSUE THREAD

**Issue by jhard** [telegramdesktop/tdesktop#17225]
### Steps to reproduce

Since the most recent update, some actions cause the scroll wheel to no longer scroll. I cannot reliably reproduce it. It seems to happen after a day or two of running the client, and in both cases it happened after the edit area showed additional information.

Two days ago, it stopped working after double-clicking (and cancelling) a message to reply to, today it stopped working after pasting a link into the edit area and seeing the preview.

I can still scroll by dragging the scroll bar or using page up/down keys, but the scroll wheel no longer works, neither on the contacts nor in a chat (no group or chat works, it's not just on one chat).

Restarting Telegram fixes it.

How can I collect useful debugging information the next time it happens to make it easier to debug?

### Expected behaviour

The Scroll Wheel continuously works.

### Actual behaviour

The Scroll Wheel stops working.

### Operating system

Kubuntu 20.04

### Version of Telegram Desktop

3.2.2

### Installation source

Static binary from official website

**Comment by AndreyKopeyko** [comment]
I have the same problem. Was forced to downgrade to 3.1.8 - there wheel scroll works nicely.
Ubuntu-20.04 LTS.

**Comment by gotohx** [comment]
I have the same problem. 
Operating system: Ubuntu 20.04
Version of Telegram Desktop: 3.2.2

**Comment by ilya-fedin** [comment]
> I cannot reliably reproduce it.

I can't reproduce that. Without a reliable way to reproduce this, it's unlikely to be fixed.

**Comment by lauripiisang** [comment]
I had a similar issue, but instead of scroll not working, it also grabbed window handle and started moving the window around at times, randomly.

I am using Ubuntu 21.04, snap, but I'm running regolith (i3-gaps) and have telegram running in scratchpad (floating window mode).

Fixed issue by ticking Settings > Advanced > Use system window frame

**Comment by gotohx** [comment]
> I have the same problem. Operating system: Ubuntu 20.04 Version of Telegram Desktop: 3.2.2

After updating to version 3.2.4, the problem is solved

**Comment by lauripiisang** [comment]
Why close this issue? Such version does not exist on snap

**Comment by ilya-fedin** [comment]
If a version is not in snap, this is not a blocker for closing issues. You can move to static binary from official website for faster updates.

**Comment by AndreyKopeyko** [comment]
After updating to 3.2.5 the problem arrived, again.

**Comment by 31337-4554551n** [comment]
> > I have the same problem. Operating system: Ubuntu 20.04 Version of Telegram Desktop: 3.2.2
> 
> After updating to version 3.2.4, the problem is solved

Running version 3.2.4 on ubuntu 20.04. Mouse scroll is broken

**Comment by Aokromes** [comment]
continue here https://github.com/telegramdesktop/tdesktop/issues/17254
