### ISSUE TITLE
WebM file format support [Feature Request]

### ISSUE THREAD

**Issue by ShrirajHegde** [telegramdesktop/tdesktop#17229]
### Is your feature request related to a problem?

WebM videos have to be played using external player.

### Describe the solution you'd like

 As WebM is widespread, WebM support would be great since even while sending a WebM file, telegram doesn't provide any option to convert it to mp4, so viewing is pretty inconvenient

### Describe alternatives you've considered

If WebM playing in telegram is too hard to implement, telegram could at least provide a feature to convert it to mp4. Right now, sending WebM as an attachment and viewing in external player is the only choice.

### Additional context

WebM sent as file instead of media

![image](https://user-images.githubusercontent.com/66936172/141138711-32d08a26-8d3e-4fee-8ad5-0d224f80724c.png)

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/2364

**Comment by ShrirajHegde** [comment]
@Aokromes what about convert to mp4 feature? That would solve the problem for most use cases.

**Comment by ilya-fedin** [comment]
You can convert with any third-party software, tdesktop shouldn't include all the world
