### ISSUE TITLE
Kerning regression in Qt6

### ISSUE THREAD

**Issue by pandasauce** [telegramdesktop/tdesktop#17221]
### Steps to reproduce

1. Run Ubuntu 20.04
2. Configure to Full hinting, Subpixel RGB AA, ClearType rendering (default in Ubuntu's FreeType), lcdlight filter
3. (may not be needed for Telegram) Configure the following `~/.Xresources`:

```
Xft.antialias: 1
Xft.hinting: 1
Xft.hintstyle: hintfull
Xft.lcdfilter: lcdlight
Xft.rgba: rgb
Xft.autohint: 0
```

4. Run Telegram Desktop
5. Open a chat with lots of messages
6. Observe kerning broken in some messages

Note that in this configuration "full hinting" is [not actually full hinting](https://freetype.org/freetype2/docs/hinting/subpixel-hinting.html) as it

> simply ignores all horizontal hinting instructions

However, subpixel RGB AA may still affect advance widths, so I would look in the direction of subpixel positioning changes. It needs to be switched on in this configuration (subpixel AA) and it's usually down to the application whether it chooses to do so in its UI toolkit.

### Expected behaviour

Fonts render as they did in earlier releases

### Actual behaviour

![tg-kerning](https://user-images.githubusercontent.com/7682940/140805316-e3411cb0-9889-4802-8e04-d9230f941bd6.png)

### Operating system

Ubuntu Linux 20.04

### Version of Telegram Desktop

3.2.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Apparently, a Qt 6 regression :(
It's unlikely tdesktop can fix it on its own

**Comment by Ristovski** [comment]
FWIW, can confirm on Gentoo as well (currently on version 3.2.4), however my `.Xresources` contains only these (relevant) settings:
```
Xft*antialias: True
Xft*hinting:   Full
```

@ilya-fedin Any ideas on how to narrow this down?

**Comment by ilya-fedin** [comment]
> Any ideas on how to narrow this down?

this is a question for Qt developers, apparently...

**Comment by ilya-fedin** [comment]
This issue is now a part of #25126

**Comment by ilya-fedin** [comment]
Is this still valid with 4.6.7?
