### ISSUE TITLE
scrolling via mouse wheel not working

### ISSUE THREAD

**Issue by aliazani** [telegramdesktop/tdesktop#17233]
### Steps to reproduce

1. open telegram desktop
2. scroll via mouse wheel

### Expected behaviour

scroll

### Actual behaviour

nothing

### Operating system

Linux(Manjaro)

### Version of Telegram Desktop

3.2.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/17225
