### ISSUE TITLE
Cease server limitation to register for desktop clients - stop this techno-discrimination

### ISSUE THREAD

**Issue by nick87720z** [telegramdesktop/tdesktop#17236]
### Steps to reproduce

1. Start registration by phone, enter phone, proceed.
2. Page to enter code is displayed. Nothing happens.

### Expected behaviour

Must not require mobile client, word by word as is.
Showing limitation info in same SMS could suffice for half-measure, which is not final correct solution.

### Actual behaviour

Registration works via SMS, but only mobile clients have success granted. Desktop clients fail silently.

I have regular phone, which is not smart. What is the hell may be intelligeble reason to require specific client (mobile), if it still uses such outdated feature as sms? As long as SMS are standard in mobile messaging (as telegram FAQ states) - it MUST work on ALL sms clients, be it phone or just sms messager (is such things ever exist).
That limitation is sure not against virtual numbers, since I know they are used now as well - blocking them requires completely different, more complicated approach, so I see no intelligeble reason for current server limitation.

This is bug. Intentional bug.
Add to this possible future blacklisting of unofficial clients like kotatogram, and there's no more difference from MS and Apple. Privacy-carrying app can't be such, just as reverse is true.

### Operating system

Gentoo, self-made DE

### Version of Telegram Desktop

3.1.1 (exact source - updates.tdesktop.com, used by ebuild for my arch)

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
not a bug, nothing preston can do to "fix" it.

**Comment by nick87720z** [comment]
Oh, yeah.
I wrote this just prior discovering different bug tracker for issues, related to infrastructure rather than client apps, bugs.telegram.org. That would be proper place for this issue.
