### ISSUE TITLE
Let us open sticker packs in editing section

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1723]
Hi
I want to remove some sticker packs, I think I reached the limit. So I want to see which pack is not good enough and I delete it. But I can't view sticker packs in editing section. It's really useful to let us view them. In this way we can decide immediately delete or keep them.

![telegram_2016-03-03_20-54-25](https://cloud.githubusercontent.com/assets/15929497/13507458/ee381f6e-e182-11e5-90f5-10ee2a890ab5.png)

Thanks

**Comment by amiremami** [comment]
I noticed this feature is already available for mobile. not for PC yet. Thanks anyway.

**Comment by amiremami** [comment]
No update on this? :(

**Comment by stek29** [comment]
@amiremami You could look at [this fork](/stek29/tdesktop-plus) to adopt it's code and make a pull request.

**Comment by amiremami** [comment]
This is working on mobile, but not on desktop. Why? :(

**Comment by amiremami** [comment]
Has already been done, close this 😄

**Comment by stek29** [comment]
@amiremami you can close it too :)
