### ISSUE TITLE
Cannot edit a scheduled message

### ISSUE THREAD

**Issue by AivanF** [telegramdesktop/tdesktop#17238]
### Steps to reproduce

Write a scheduled message and try to find a way to edit it on Telegram Desktop MacOSX [version 2.3.2](https://desktop.telegram.org/changelog#v-3-2-03-11-21).

The problem is the same on 2 installations on different computers. However, everything worked fine with the previous version on these computers. Also, I'm still able to edit messages that are already sent.

<img width="210" alt="Tg-no-edit" src="https://user-images.githubusercontent.com/16814592/141609501-10b2588b-6ba8-4bb0-a5ff-b0c91d6dc4b8.png">

### Expected behaviour

An "Edit" option on right-click menu of a scheduled message

### Actual behaviour

There are Copy / Send now / Delete / Select / Reschedule options, but not "Edit"

### Operating system

MacOSX

### Version of Telegram Desktop

3.2.3

### Installation source

Mac App Store

**Comment by john-preston** [comment]
Thanks for your report!

This bug should be fixed by https://github.com/telegramdesktop/tdesktop/commit/2f48fe920e105f6c1159250c98d89732d8c37179 and the fix should become available in the version 3.2.4 later today.

**Comment by edmundlaugasson** [comment]
Same issue is with 3.2.3 version in Linux as well... Does 3.2.4 fix also Linux version?

**Comment by john-preston** [comment]
@edmundlaugasson Yes.
