### ISSUE TITLE
Telegram freezes and crashes when uploading media to a channel

### ISSUE THREAD

**Issue by veratone** [telegramdesktop/tdesktop#17231]
### Steps to reproduce

1. open Telegram Desktop
2. go to a channel
3. upload media album
4. while uploading go to old posts by searching and scroll down by arrow

### Expected behaviour

Telegram shouldn't crash and scroll normally.

### Actual behaviour

While uploading a media content to a channel and at the same time scrolling up to an old posts and scrolling down by clicking the arrow - Telegram crashes. Idk if it's happens every time or not, or if it depends on the progress/type of media but...

### Operating system

Windows 10 64

### Version of Telegram Desktop

3.2.2 x64

### Installation source

Static binary from official website

**Comment by ambisinistra** [comment]
Have the same bug for Ubuntu 18.04.6 LTS. For both telegram snap versions 3.4.3 and 3.5.1-7-gbef20ba4a

After trying to upload several media files to channel telegram freezes to death with whole system. If I am trying to upload single file that is not gonna to happen

**Comment by den-krupsky** [comment]
I have installed Telegram Desktop v3.4.3 from official site on Ubuntu 20.04 LTS.

And from time to time my system is stucking when Telegram client is just opened or sometimes when I'm trying to upload files

**Comment by Aokromes** [comment]
latest official version is 3.5.2

**Comment by den-krupsky** [comment]
> latest official version is 3.5.2

Yeah, I already upgraded my client to latest version. And it's look that all works (no system stuck)

**Comment by den-krupsky** [comment]
> latest official version is 3.5.2

It still goes my system in stuck when i want to send picture to chat
