### ISSUE TITLE
IMEs stop working after updating to v3.2.4

### ISSUE THREAD

**Issue by dsh0416** [telegramdesktop/tdesktop#17242]
### Steps to reproduce

Known affected IMEs:
1. Google Japanese Input (Google 日本語入力)
2. Squirrel (鼠鬚管)

Reproduce steps:
1. Using Telegram Desktop v3.2.4
2. Switch the Input method to affected IMEs
3. Type something in the window

### Expected behaviour

Candidate words should be prompt from the IME for typing Chinese or Japanese.

### Actual behaviour

No keys including shortcuts could be entered.

### Operating system

macOS 12.0.4

### Version of Telegram Desktop

3.2.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#17176

**Comment by dsh0416** [comment]
Going to close this issue, since it's duplicated with #17176

**Comment by john-preston** [comment]
I hope I've found a workaround.

**Comment by john-preston** [comment]
@dsh0416 Can you please check this version: https://td.telegram.org/tmac/tsetup.3.2.5.dmg

Does it work fine?

**Comment by dsh0416** [comment]
> @dsh0416 Can you please check this version: [td.telegram.org/tmac/tsetup.3.2.5.dmg](https://td.telegram.org/tmac/tsetup.3.2.5.dmg)
> 
> Does it work fine?

It works! Thanks a lot.
