### ISSUE TITLE
[Question] Windows pre-compilation of ffmpeg failed

### ISSUE THREAD

**Issue by StevenMichael3213** [telegramdesktop/tdesktop#17247]
When I followed the **Build instructions for Windows 64-bit**, I encountered the following error.
How can I fix it? thanks.
![image](https://user-images.githubusercontent.com/31765462/141696143-b3708283-6061-491c-b3e5-997d21c4c088.png)

**Comment by john-preston** [comment]
Are you sure you've installed msys correctly? It should know pacman.

**Comment by StevenMichael3213** [comment]
Yes, my msys is installed correctly. I confirmed it again, but this error still appears when compiling.

But I will not continue to compile the desktop version now, I will try again later if I have a chance.

Thanks.
