### ISSUE TITLE
Emulator detection

### ISSUE THREAD

**Issue by wolverine013** [telegramdesktop/tdesktop#17244]
### Is your feature request related to a problem?

Yes it is related to a problem.

The problem is for self-destructing photos & videos in a personal chat, when you log in ro telegram using a computer it says "please view this message from your phone"
But 

> When you log in to telegram by a android emulator ( i.e. BlueStacks etc.) it shows the self-destructing picture or video you sent and normally like a phone after a particular time it disappears.. but in the meantime you can take your screenshot or screen-recording whatever you want from it

I haven't checked for secret chats 

### Describe the solution you'd like

 By detecting emulators this problem may be solved

### Describe alternatives you've considered

I haven't considered any alternatives

**Comment by Aokromes** [comment]
this bug tracker is for telegram desktop, not for telegram android.
