### ISSUE TITLE
'Disable proxy' option didnt work when app is starts

### ISSUE THREAD

**Issue by russtam** [telegramdesktop/tdesktop#17249]
### Steps to reproduce

1. Set manual proxy in Ubuntu (proxy does not allow to connect for Telegram)
2. Start Telegram with 'Disable proxy' option turned on
3. Telegram can't connect
4. Open Setting -> Advanced -> Network and Proxy
5. Select 'Use system proxy settings' and immediately choose "Disable proxy" again
6. Telegram connects successfully

### Expected behaviour

When manual proxy used in Ubuntu - Telegram connect successfully at startup when "Disable proxy" selected.

### Actual behaviour

When manual proxy used in Ubuntu - Telegram can't connect at startup when "Disable proxy" selected.

### Operating system

Ubuntu 20.04

### Version of Telegram Desktop

3.2.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#16600
