### ISSUE TITLE
wavpack

### ISSUE THREAD

**Issue by 82d** [telegramdesktop/tdesktop#17241]
### Is your feature request related to a problem?

at the moment there is support for flac and m4a audio formats. these are good formats. but these are not all open source formats. I'm going to keep my collection in wavpack format. this is a wonderful format.

### Describe the solution you'd like

 I really want to see the same good support in Telegram.

### Describe alternatives you've considered

of course, you can always convert.

### Additional context

wv

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
