### ISSUE TITLE
Download link for linux on desktop.telegram.org still delivers 3.2.4

### ISSUE THREAD

**Issue by lemmy04** [telegramdesktop/tdesktop#17259]
### Steps to reproduce

1. try to download telegram desktop for linux 3.2.5 from the official website

### Expected behaviour

The current release is 3.2.5 so that is what should be downloaded

### Actual behaviour

the download for 64bit linux is still version 3.2.4

### Operating system

n/a

### Version of Telegram Desktop

n/a

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@lemmy04 3.2.5 was supposed to be only for Windows and macOS, the version from GitHub releases was a test gcc-10 build without any changes, I guess I should remove it.

**Comment by lemmy04** [comment]
ah ok - that makes sense.

**Comment by henning-schild** [comment]
Thanks! I ran into the same trying to deliver 3.2.5 to gentoo, but will stay on 3.2.4 there

https://github.com/gentoo/gentoo/pull/22959
