### ISSUE TITLE
Immediate crash on startup (Kubuntu 21.04)

### ISSUE THREAD

**Issue by JPT77** [telegramdesktop/tdesktop#17256]
### Steps to reproduce

Well, no idea. Just start.

### Expected behaviour

Not crash ;)

### Actual behaviour

Crash few miliseconds after main window opened.

### Operating system

Kubuntu 21.04, KDE 5.80.0, Qt 5.15.2

### Version of Telegram Desktop

2.6.1+ds-1ubuntu2

### Installation source

Other (unofficial) source

### Logs

```shell
...
[New Thread 0x7fffa09f4640 (LWP 4361)]
error: : cannot open
error: : cannot open
error: : cannot open
[New Thread 0x7fffa19f6640 (LWP 4362)]
[New Thread 0x7fffa11f5640 (LWP 4363)]
[Thread 0x7fffa19f6640 (LWP 4362) exited]
[Thread 0x7fffa11f5640 (LWP 4363) exited]
qt.svg: Error while inflating gzip file: SVG format check failed

Thread 1 "telegram-deskto" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Comment by JPT77** [comment]
Does the crash dump help? Where do I find it?
how do I add more info to the GDB output?

**Comment by Aokromes** [comment]
plz try downloading latest official version from https://desktop.telegram.org

**Comment by JPT77** [comment]
Thanks, that helped. sorry to have bothered with such a problem :o)
