### ISSUE TITLE
[Feature Request] Groups of Chats

### ISSUE THREAD

**Issue by icariantk** [telegramdesktop/tdesktop#1725]
it would be very nice if we could get groups of chats, to manage privacy and multiple accounts, like this awesome production ready for an Oscar:

https://dl.dropboxusercontent.com/u/35415058/Telegram.gif

**Comment by memboc** [comment]
I support this suggestion

**Comment by DaFri-Nochiterov** [comment]
#1107

**Comment by code88899091** [comment]
very good suggestion

**Comment by mattmezza** [comment]
:+1: seems fair!

**Comment by auchri** [comment]
No api for that. See #1107

**Comment by icariantk** [comment]
I see the thread you and the other user mention. Using that thread, i cant imagine why is not posible to do a local grouping, not need an api to categorize, is tdesktop a sole api interface?

**Comment by ross999** [comment]
This is over 1.5 years old and nothing has been done? I realize Telegram is free and I should be so happy and joyful but I'd gladly pay .99 and so would everyone else if you guys could add this feature. Almost every group I'm a part of I see people wishing this feature was available.

I'm a UX designer in NYC. If you need help conceptualizing let me know. It's pretty simple UI.

**Comment by EdgarSedov** [comment]
+1 for this in any way. It becomes really hard to navigate through conversations, groups, channels, bots, contacts..
