### ISSUE TITLE
Camera selection

### ISSUE THREAD

**Issue by AtomicNess123** [telegramdesktop/tdesktop#17269]
### Is your feature request related to a problem?

This feature does not seem to exist. Any plans to include it for calls?

### Describe the solution you'd like

Basically, the ability to select in settings which camera source to use.

### Describe alternatives you've considered

In the meanwhile, I have been using other thirdparty chat providers different from Telegram when I need effects.

**Comment by Aokromes** [comment]
it's already there on settings -> advanced -> calls settings.

https://i.imgur.com/ad9LIIa.png
https://i.imgur.com/mlnmZmf.png

**Comment by AtomicNess123** [comment]
Thanks, I am on 8.2 (223044) Stable, and does not seem to work. It gets hanging in there.

**Comment by john-preston** [comment]
@AtomicNess123 8.2 is not Telegram Desktop, but a different Telegram app for macOS. You can try Telegram Desktop from https://desktop.telegram.org

**Comment by AtomicNess123** [comment]
Ok, thanks! It works!
