### ISSUE TITLE
Touch keyboard overlaps the message input field on touchscreen.

### ISSUE THREAD

**Issue by usernameak** [telegramdesktop/tdesktop#17261]
### Steps to reproduce

1. Tap the message input field on any touchscreen device running Windows.

### Expected behaviour

The keyboard is right below the field.
![image](https://user-images.githubusercontent.com/8577347/142206477-73f3c251-dede-45e3-a4fe-bca0534811a8.png)

### Actual behaviour

The keyboard overlaps the field. The extent depends on screen resolution.

### Operating system

Windows 10 21H1 x64

### Version of Telegram Desktop

3.2.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3274
