### ISSUE TITLE
choosing sticker status sent when not actually choosing (macOS)

### ISSUE THREAD

**Issue by Y-T04KA** [telegramdesktop/tdesktop#17265]
### Steps to reproduce

1. be online
2. sticker panel closed

### Expected behaviour

choosing sticker status sent only when actually choosing

### Actual behaviour

choosing sticker status sent in chat when user not choosing sticker and even in another chat. Also, status sometimes sends in two chats at one time

as a quick fix, the option to hide this status at all can be added

### Operating system

masOS Monterey

### Version of Telegram Desktop

8.2 (223045)

### Installation source

Mac App Store

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
