### ISSUE TITLE
[Question] Custom image viewers?

### ISSUE THREAD

**Issue by TruncatedDinosour** [telegramdesktop/tdesktop#17267]
I want to make my image viewer as MPV, any way to do that on telegram desktop orrrrr?

I know you can use `open with` link on FILES, but not compressed pictures and I don't want to download the image to view it all the time

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/wiki/Hidden-modes

**Comment by ilya-fedin** [comment]
#1111

**Comment by ilya-fedin** [comment]
> and I don't want to download the image to view it all the time

I hope you understand that you can't open a file in third-party program without downloading it

**Comment by TruncatedDinosour** [comment]
> > and I don't want to download the image to view it all the time
> 
> I hope you understand that you can't open a file in third-party program without downloading it

ofc i know that, i meant I don't want to manually press "save as" and all of that jazz haha

**Comment by TruncatedDinosour** [comment]
> https://github.com/telegramdesktop/tdesktop/wiki/Hidden-modes

thanks <3

**Comment by ilya-fedin** [comment]
There's no such feauture and that's answer for your question, so no need to reopen

**Comment by TruncatedDinosour** [comment]
> There's no such feature and that's answer for your question, so no need to reopen

oh, sad, I will fork it myself If I can't find an active fork that supports it 👍
