### ISSUE TITLE
[Feature Request] Upload speed boost

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#17272]
### Is your feature request related to a problem?

Problem is very slow upload speed. I was using unofficial client of Telegram Desktop - [Kotatogram](https://github.com/kotatogram/kotatogram-desktop/releases) and this client is have "Upload speed boost" feature:
![image](https://user-images.githubusercontent.com/39812401/142733553-022b6bb2-c239-4ee4-b8a0-43ea5d15e264.png)

This is how it works. Kotatogram video uploading:

https://user-images.githubusercontent.com/39812401/142733557-ee0368d7-4b76-4032-9804-3d07d61be4f0.mp4

Telegram Desktop video uploading:

https://user-images.githubusercontent.com/39812401/142733571-09a13049-1f25-4ebd-8a7c-aa6a048d30a3.mp4

20Mbps vs 5Mbps. It's still low even with boost because I have 100Mbps from my provider:
![image](https://user-images.githubusercontent.com/39812401/142733668-60850491-64ce-4ff3-b555-53b174f6e53c.png)
But this is still 4 times more.

### Describe the solution you'd like

Get the speed boost code from the Kotatogram. Give people a choice in settings.

### Describe alternatives you've considered

There is no alternatives, now Telegram Dekstop just unusable with that upload speed.

**Comment by Aokromes** [comment]
indeeed, kotatogram is far faster with the boost than telegram desktop.

**Comment by Neurotoxin001** [comment]
This is not funny. Upload speed 7Mbps when I have 80+

![image](https://user-images.githubusercontent.com/39812401/178209377-7de95a40-05ce-4ebe-ac7d-5c17a2c6d74b.png)

**Comment by Aokromes** [comment]
dunno, i see up to 26 Mbps still slow but not that slow.

**Comment by Neurotoxin001** [comment]
Try to upload album with 5 videos 100mb+.

On first video it's 26mbps
On second it's down to 5-6mbps
That's a bug

**Comment by Neurotoxin001** [comment]
This will be fixed (and won't need a «boost» crutch) when we move to tdlib (soon)
