### ISSUE TITLE
Compact side-by-side view (without contact name & last message) not retained when having viewed settings or other pages.

### ISSUE THREAD

**Issue by sarensabertooth** [telegramdesktop/tdesktop#17276]
### Steps to reproduce

1. Make the telegram window large enough to show recent conversations and chat window side-by-side
2. Drag the separator to the left, so the conversations collapse into just thumbnails (without contact name and last message showing)
3. Open the calls tab or settings tab (any other view should cause the bug)
4. Go back to the regular chat/contacts view, now the thumbnails have re-expanded into showing the contact name & last message 

How I want it to look:
<img width="725" alt="Screenshot 2021-11-21 at 16 46 34" src="https://user-images.githubusercontent.com/9402883/142769264-a7794a09-4941-4f98-bb40-c2637ffbbe0c.png">

What it keeps going back to if any other view (settings,calls…) has been opened:
<img width="725" alt="Screenshot 2021-11-21 at 16 50 07" src="https://user-images.githubusercontent.com/9402883/142769259-0ff42d79-867f-4104-a3b1-df8fc61089ea.png">

### Expected behaviour

Keep collapsed contacts thumbnails with chat to the right side (no contact names or last message shown)

### Actual behaviour

Expands contacts back into the wider view where names and last messages are shown.

### Operating system

macOS

### Version of Telegram Desktop

8.1.3

### Installation source

Mac App Store

**Comment by ilya-fedin** [comment]
As you can see in https://github.com/telegramdesktop/tdesktop/releases, latest version of tdesktop is 3.2.5, you're using some other application
