### ISSUE TITLE
[unexpected behaviour] Unable to view some images from link preview in media viewer

### ISSUE THREAD

**Issue by Younes-L** [telegramdesktop/tdesktop#17279]
### Steps to reproduce

1. send or receive a link which has an image preview (example : https://en.wikipedia.org/wiki/File:Lake_Toba_from_Samosir.JPG)
2. click on the link's image preview

### Expected behaviour

image is viewed in media viewer on click

### Actual behaviour

link is opened in browser

### Operating system

fedora 34 + cinnamon 4.8 / any OS / any version

### Version of Telegram Desktop

3.2.5 / any version

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3488
