### ISSUE TITLE
'Telegram-desktop' terminated by signal SIGABRT (Abort)

### ISSUE THREAD

**Issue by alefvanoon** [telegramdesktop/tdesktop#17270]
### Steps to reproduce

1. Install & Run Telegram-desktop
 

### Expected behaviour

The app is started and the first page is displayed

### Actual behaviour

The software does not run.
Also show me this error 'Telegram-desktop' terminated by signal SIGABRT (Abort)

### Operating system

Archlinux

### Version of Telegram Desktop

3.2.2-

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
You said:
> Static binary from official website

But it's definitely not an official build on your screenshot.

**Comment by alefvanoon** [comment]
Opppss, yes.
Installed with this package https://archlinux.org/packages/community/x86_64/telegram-desktop/

**Comment by alefvanoon** [comment]
![image](https://user-images.githubusercontent.com/53198048/142672997-e1502f7d-f5a5-4b39-9de4-d407896aa9b4.png)
Trying with official binary.
Same problem

**Comment by ilya-fedin** [comment]
Why do you open so much instances?

**Comment by alefvanoon** [comment]
> Why do you open so much instances?

I only run once!

**Comment by ilya-fedin** [comment]
Maybe htop shows threads? Can you disable that?

**Comment by alefvanoon** [comment]
![image](https://user-images.githubusercontent.com/53198048/142674385-510eb6ce-3a10-4e4a-9511-1873078fe84b.png)

**Comment by ilya-fedin** [comment]
Telegram can start multiple minutes if you have problems with dbus. Timeout for each dbus request is 30 seconds.

**Comment by alefvanoon** [comment]
> Maybe htop shows threads? Can you disable that?

![image](https://user-images.githubusercontent.com/53198048/142674538-914e3d1c-2bc9-4fd2-bbdd-ab29f1b5831d.png)
With top

**Comment by ilya-fedin** [comment]
1.2g? :thinking: 
Try to run it in gdb, interrupt it (with Ctrl+C) when it reaches some big-but-stable memory consumption and get traces with `thread apply all bt full`.

**Comment by alefvanoon** [comment]
![image](https://user-images.githubusercontent.com/53198048/142675189-91f52c4b-5e0d-4ec3-9991-59173ab41be7.png)
Some log...

**Comment by alefvanoon** [comment]
lol, The problem was solved spontaneously today.
