### ISSUE TITLE
Weird transparent line in the background 

### ISSUE THREAD

**Issue by matilde-t** [telegramdesktop/tdesktop#17277]
### Steps to reproduce

I don't know, but after the last update the background is like this. I rebooted the system, killed Telegram etc and it's still there.

![image](https://user-images.githubusercontent.com/61622827/142774510-5c52be6a-0a8c-4984-8f86-303f087b1822.png)

### Expected behaviour

A uniform background.

### Actual behaviour

There's this weird vertical transparent line.

### Operating system

Pop!_OS 21.04, GNOME 3.38.5, X11

### Version of Telegram Desktop

3.2.5

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
I can't reproduce this :(
Maybe this is specific to your interface scale or window size?

**Comment by plibither8** [comment]
This is a problem for me too!

* OS: `Ubuntu 20.04.3 LTS x86_64, Linux 5.11.0-40-generic`
* Telegram version: `3.2.2`

Tried it on my friend's macOS, it has the same issue. I'll request them for more information but it seems that multiple devices are facing it for some reason. I'd be happy to share more technical details and dive deep if requested!

**Comment by ilya-fedin** [comment]
> I'd be happy to share more technical details and dive deep if requested!

Please answer the question in https://github.com/telegramdesktop/tdesktop/issues/17277#issuecomment-974878133

**Comment by plibither8** [comment]
@ilya-fedin I don't think so. I've tried resizing the window, scaling the interface up - the problem persists :/

**Comment by plibither8** [comment]
@ilya-fedin If you would like, I could DM (on Telegram?) you a screenshot/recording of my window. A little uncomfortable to do it publicly :P.

**Comment by ilya-fedin** [comment]
Do you have the same background image as @matilde-t or another? Which Telegram theme are you using?

**Comment by matilde-t** [comment]
> I can't reproduce this :( Maybe this is specific to your interface scale or window size?

@ilya-fedin I also tried different window sizes and interface scales, same issue

**Comment by ilya-fedin** [comment]
> I also tried different window sizes and interface scales, same issue

Which Telegram theme are you using? Will the issue be reproducible if you try e.g. the flowers background from older versions (you can find it in the gallery)?

**Comment by matilde-t** [comment]
> > I also tried different window sizes and interface scales, same issue
> 
> Which Telegram theme are you using? Will the issue be reproducible if you try e.g. the flowers background from older versions (you can find it in the gallery in settings -> chat settings)?

This is my theme: https://t.me/addtheme/ujWHLUgybjw43HQ2
If I change the background the line isn't there, if I change back to my background is there again

**Comment by ilya-fedin** [comment]
What if you try to set standard theme with your background?

**Comment by Aokromes** [comment]
cannot reproduce on telegram desktop 3.3 with intel gfx.

https://i.imgur.com/XlmDQLj.jpeg

**Comment by relative** [comment]
occurs when using new chat themes/the backgrounds, you might have to resize the window for it to happen
using telegram desktop 3.4.3
gnome 41.2, X11, nvidia proprietary drivers 495.46
![Screenshot from 2022-01-10 09-05-12](https://user-images.githubusercontent.com/59253100/148779861-83cc7a90-9ac9-49de-a518-bc0c7bac171f.png)
![Screenshot from 2022-01-10 09-06-29](https://user-images.githubusercontent.com/59253100/148779867-11d2a5be-1d4c-47ed-8174-31e37cb86f6f.png) (tinted theme, changed chat background)
