### ISSUE TITLE
how to find out which function has been triggered by returned exec()?

### ISSUE THREAD

**Issue by AMP999** [telegramdesktop/tdesktop#17271]
I'm trying to trace telegram workflow from main.cpp with visual studio 2019 debugger. but when I reach at the line 157 of sandbox.cpp sandbox::start() return exec(); telegram will launch and i can't trace line by line anymore. I guess return exec() start another thread so I can't trace but I don't know which function in telegram source code it triggers

**Comment by john-preston** [comment]
@AMP999 It is QCoreApplication::exec, which launches the event loop. It is still on the main thread. If you're not familiar with the concept of event loop you should read some articles about the GUI application architecture.
