### ISSUE TITLE
scrool not working after suspend

### ISSUE THREAD

**Issue by AMV007** [telegramdesktop/tdesktop#17278]
### Steps to reproduce

1. check scroll working - ok
2. go to suspend
3. resume from suspend
4. mouse scroll not working

### Expected behaviour

scroll working

### Actual behaviour

scroll not working

### Operating system

Ubutnu 20

### Version of Telegram Desktop

3.2.4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/17254

**Comment by AndreyKopeyko** [comment]
I have the same problem. Ubuntu 20.04.3 LTS, GNOME Shell 3.36.9, telegram 3.2.5
For more details, including debug logs, see issue #17254 

Interesting thing - scrolling via 2-finger gesture on touchpad continues working.
