### ISSUE TITLE
[Feature Request] Notify by keyword

### ISSUE THREAD

**Issue by memboc** [telegramdesktop/tdesktop#1727]
If user has a large group, and do not want to keep track it and do not receive notifications. But user wants to be the notified when addressing him by name, or report the news or the problem. This can be done conveniently through the list of keywords, for example:
Robert, news, trouble, error, help
![screenshot_1](https://cloud.githubusercontent.com/assets/7403119/13523020/a2c83144-e1fb-11e5-98ec-07c7a0ce9c81.png)

**Comment by TiagoDanin** [comment]
+1 Nice :+1:

**Comment by theus** [comment]
It would be nice :blush:

**Comment by neesti** [comment]
+1

**Comment by auchri** [comment]
Duplicate #554
