### ISSUE TITLE
Random freeze of telegram when exiting from standby mode (S3)

### ISSUE THREAD

**Issue by Baltazar500** [telegramdesktop/tdesktop#17285]
### Steps to reproduce

1. Start the telegram with the command Telegram.exe -startintray 
2. Put the PC into standby mode (I am using psshutdown.exe -d -t 00), S3. 
3. Turn on the PC and if you are lucky (or unlucky) - the telegram will freeze (with random) in the tray and stop responding to clicking on the icon after exiting standby mode 

### Expected behaviour

It is necessary not to freeze when exiting standby mode

### Actual behaviour

the telegram will freeze (with random) in the tray and stop responding to clicking on the icon after exiting standby mode.

### Operating system

Windows 7 x64 SP1

### Version of Telegram Desktop

3.2.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#16093 #16647
