### ISSUE TITLE
[Feature Request] Please change conversation layout

### ISSUE THREAD

**Issue by avinashkkumar** [telegramdesktop/tdesktop#17288]
### Is your feature request related to a problem?

<h1>Chats view can be improved </h1>
<p> The chat in the smaller window in the desktop app looks good but when full screen the chat that I send and recieve gets to the same side and makes it harder to distinguish between the what is incomming and what is outgoing</p>

### Describe the solution you'd like

<h1> Solution that I can think of ...... </h1>
<p> Scale the window and dont change the chat to left aligned when full screen </p>

### Describe alternatives you've considered

<p> the app window of the Google Messages looks good to me in even in the full screen the chat stay where they are expected and even the iMessage and WhatsApp</p>

### Additional context

<p> -- regards <br> Avinash Kumar </p>

**Comment by Aokromes** [comment]
disable adaptative layout on settings.
