### ISSUE TITLE
[Question] High CPU When Share Screen in Voice Chat

### ISSUE THREAD

**Issue by alexdhika** [telegramdesktop/tdesktop#17282]
100% CPU load when share screen in voice chat in manjaro linux

**Comment by ilya-fedin** [comment]
What's the question?

**Comment by alexdhika** [comment]
> What's the question?

how to fix it?

**Comment by ilya-fedin** [comment]
I don't think you can

**Comment by Aokromes** [comment]
if you want to report a bug, fill a proper bug report, questions aren't for bug reports.
