### ISSUE TITLE
Adding 'Always on Top' feature to Telegram Desktop

### ISSUE THREAD

**Issue by BornaKalhor** [telegramdesktop/tdesktop#17289]
### Is your feature request related to a problem?

Sometimes, I want to chat with a friend and in the meantime, watch a video or browse the internet. so I open Telegram beside my browser to do so. the problem is, when I click anywhere in my browser, Telegram minimizes to Taskbar. I can set my browser to the left and Telegram to the right but that shrinks my screen too much and it's not so convenient.

### Describe the solution you'd like

Please consider adding an 'always on top' feature like in most media players such as PotPlayer, etc. to prevent minimization to Taskbar.
![alwaysontop](https://user-images.githubusercontent.com/47133206/143293933-dde6e7de-57a5-4761-aa08-632cd99f5f1e.jpg)

### Describe alternatives you've considered

I have not considered any.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/368
