### ISSUE TITLE
Add feature to pin and edit messages on T-desktop[Feature Request] 

### ISSUE THREAD

**Issue by sid4618** [telegramdesktop/tdesktop#17286]
### Is your feature request related to a problem?

Can't find a option to pin and edit msgs on desktop app.

### Describe the solution you'd like

Option to ping and edit messages.

### Describe alternatives you've considered

Will suggest more featues later. Everything else is Awesome.

**Comment by sid4618** [comment]
Request to add ping msg and edit msg feature.

**Comment by Aokromes** [comment]
pin or ping? if pin already present, the same for edit, unless you mean pin and edit on a single step.

**Comment by RememberTheAir** [comment]
I guess what @sid4618 is trying to ask is the ability to edit messages from the pinned messages screen. tdesktop doesn't let you do that (you have to right-click on the message -> "got to message"), but it's possible on other apps (eg. android)

**Comment by sid4618** [comment]
> pin or ping? if pin already present, the same for edit, unless you mean pin and edit on a single step.

I Guess pin and edit on a single step is not a good idea, thanks for your response.
