### ISSUE TITLE
could not initialize WebView

### ISSUE THREAD

**Issue by kasumiru** [telegramdesktop/tdesktop#17290]
### Steps to reproduce

1. select checkout in telegram channel
2. press "PAY xxx,xx RUB" button 
3. some second await and I see: "Error: Could not initialize WebView."

### Expected behaviour

open payments web site or paymets window

### Actual behaviour

see erorr: "Error: Could not initialize WebView"

### Operating system

windows 10 build 19042.1348

### Version of Telegram Desktop

3.2.5

### Installation source

Static binary from official website

### Logs

```shell
I can attach full log if it needed.

[2021.11.25 00:42:55] OpenGL: QOpenGLContext created, version: 3.3.
[2021.11.25 00:42:55] OpenGL: [TRUE] (OverlayWidget)
[2021.11.25 00:42:56] Message Info: bad message notification received (error_code 33) for msg_id = 7034255246324421704, seq_no = 42
[2021.11.25 00:42:56] Message Info: bad message notification received, msgId 7034255246324421704, error_code 33
[2021.11.25 00:42:56] API Warning: not loaded minimal channel applied.
[2021.11.25 00:42:56] API Warning: not loaded minimal channel applied.
[2021.11.25 00:43:29] WinRT Error: -2147023170 (The remote procedure call failed.)
[2021.11.25 00:43:29] WinRT Error: -2147023170 (The remote procedure call failed.)
[2021.11.25 00:43:29] WinRT Error: -2147023170 (The remote procedure call failed.)
[2021.11.25 00:43:29] WinRT Error: -2147023170 (The remote procedure call failed.)
```

**Comment by Serge-Mazur** [comment]
I confirm:
https://i.imgur.com/KxArLA3.png

Tested [the ShopBot](https://t.me/shopbot) on my desktop app and if I tick the option `Webview` then I can not finish my payment.

Version of the desktop app is [up to date 3.2.5](https://desktop.telegram.org/changelog#v-3-2-03-11-21).

**Comment by jackvote** [comment]
I confirm.
Operating system: windows 7
Version of Telegram Desktop: 3.5.1

The same problem on win10 was solved by an update Microsoft Edge.

On win7, I installed webview2. After that, I installed MS Edge.
The problem has not been fixed.

People can't use Telegram Bot Payments on Win7

Tested on https://t.me/niloffffbot and others. Different payment systems.

**Comment by kasumiru** [comment]
tumbleweed

**Comment by lp85d** [comment]
Durger King
Error: Could not initialize WebView.
How to solve the problem?
Telegram Desktop 💕
Версия 3.7 x64 - О программе

**Comment by IlhomjonMuxtorov** [comment]
> Durger King Error: Could not initialize WebView. How to solve the problem? Telegram Desktop 💕 Версия 3.7 x64 - О программе

I have same problem

**Comment by Aokromes** [comment]
try 3.7.1

**Comment by IlhomjonMuxtorov** [comment]
> try 3.7.1

Again same problem

**Comment by ilya-fedin** [comment]
> Again same problem

Can you take a screenshot of the error?

**Comment by IlhomjonMuxtorov** [comment]
![web_app_wrong](https://user-images.githubusercontent.com/34705227/165914185-4c5cb557-2951-4f3c-b29b-0f06829ca733.jpg)

**Comment by ilya-fedin** [comment]
> My desktop telegram version 3.7.3

Can you provide the logs?

**Comment by IlhomjonMuxtorov** [comment]
> > My desktop telegram version 3.7.3
> 
> Can you provide the logs?

[2022.04.30 09:10:21] WinRT Error: -2147023170 (Сбой при удаленном вызове процедуры.)

**Comment by ilya-fedin** [comment]
> [2022.04.30 09:10:21] WinRT Error: -2147023170 (Сбой при удаленном вызове процедуры.)

Is it possible that you use some kind of shrunk/modificated version of Windows (debloated, despyed, etc)?

**Comment by IlhomjonMuxtorov** [comment]
You are right, my windows is not offical

**Comment by ilya-fedin** [comment]
> You are right, my windows is not offical

That's most likely the reason. Apparently the service tdesktop uses was 'debloated'.

**Comment by IlhomjonMuxtorov** [comment]
Web view working on offical windows

**Comment by ilya-fedin** [comment]
@kasumiru can you confirm you use non-offical Windows, too?

**Comment by IlhomjonMuxtorov** [comment]
> That's most likely the reason. Apparently the service tdesktop uses was 'debloated'.

How can I fix it?

**Comment by ilya-fedin** [comment]
> How can I fix it?

Well, don't use shrunk OS

**Comment by IlhomjonMuxtorov** [comment]
Thank you!!!

**Comment by IlhomjonMuxtorov** [comment]
But payment method web view working on my windows

**Comment by ilya-fedin** [comment]
> But payment method web view working on my windows

Are you sure? Can you provide a screenshot?

**Comment by IlhomjonMuxtorov** [comment]
> > But payment method web view working on my windows
> 
> Are you sure? Can you provide a screenshot?

![image](https://user-images.githubusercontent.com/34705227/166091643-7686d71b-cc94-430d-bded-cd0b48d72249.png)

**Comment by ilya-fedin** [comment]
This is not a webview.

**Comment by IlhomjonMuxtorov** [comment]
> This is not a webview.

Understood, thank you

**Comment by lp85d** [comment]
> Ошибка Durger King : не удалось инициализировать WebView. Как решить проблему? Телеграмма для рабочего стола💕 Версия 3.7 x64 - О программа

А всего та надо было установить [MicrosoftEdgeWebview2](http://parserposter.ru/blog/telegram-web-bot/)

**Comment by ilya-fedin** [comment]
It's for Windows 11+. On Windows 8.1-10 tdesktop prefers the built-in Edge engine.
