### ISSUE TITLE
[Feature Request]  Mute channels at "night time"

### ISSUE THREAD

**Issue by Ezri** [telegramdesktop/tdesktop#17295]
### Is your feature request related to a problem?

Some channels are important enaugh not not mute but not important enaugh to disturb sleep while others should continue to ping, so it is not really possible to mute the device completely and it is quite an effort to mute all those channels before bed time.

### Describe the solution you'd like

A) An general option to define quiet times: ideally multiple times depending on day of week but at a minimum a set night time.

B) A further option in the "Mute channel" dropdown setting the channel to "mute at quiet times" (or similar wording) 

### Describe alternatives you've considered

Muting the device (not practical due to Alert channels)
Muting individual channels every evening (takes too long)

**Comment by RememberTheAir** [comment]
This looks like something that should be supported by the server, and it's more related to mobile apps. You should post this to https://suggestions.telegram.org, or upvote similar tickets already submitted by other users (this one is very similar/overlaps with the request: https://bugs.telegram.org/c/3198)
