### ISSUE TITLE
Prevent someone unknown from writing me

### ISSUE THREAD

**Issue by zakiloki0** [telegramdesktop/tdesktop#17299]
I'm in public location-based groups, they do events sometimes and it's great, the problem is that there are certain individuals who constantly write privately, is there a way that only my contacts write to me?

**Comment by AnshumanFauzdar** [comment]
Hey @zakiloki0 you can set privacy in settings menu -> Privacy and security -> Phone Number -> Nobody.
 It will prevent your contact to be displayed but still they can contact through your username.

**Comment by zakiloki0** [comment]
> Hey @zakiloki0 you can set privacy in settings menu -> Privacy and security -> Phone Number -> Nobody. It will prevent your contact to be displayed but still they can contact through your username.

You have misunderstood the question, the phone is obviously hidden, but in location-based groups, there is no way to prevent strangers from sending you private messages.

**Comment by AnshumanFauzdar** [comment]
@zakiloki0 you can use user bots for this problem.

**Comment by zakiloki0** [comment]
> @zakiloki0 you can use user bots for this problem.

Ok, can you give me a example? Because i doubt that

**Comment by AnshumanFauzdar** [comment]
@zakiloki0 use https://github.com/UsergeTeam/Userge and whitelist your saved contact only.

**Comment by zakiloki0** [comment]
> @zakiloki0 use https://github.com/UsergeTeam/Userge and whitelist your saved contact only.

I'm not going to give something like that access to my account. I do not see it convenient, too bizarre to do all that to achieve something as simple as blocking private messages, I do not understand how Telegram does not have this option at this point natively.

**Comment by AnshumanFauzdar** [comment]
@zakiloki0 Yes currently it is only possible with 3rd party integrations, but other messengers also lack this feature!
Lets see if this feature comes in future :)

**Comment by Younes-L** [comment]
@zakiloki0 make sure to upvote this request : [New privacy option to not allow private messages from non-contacts.](https://suggestion.telegram.org/c/10548)

**Comment by zakiloki0** [comment]
> @zakiloki0 make sure to upvote this request : [New privacy option to not allow private messages from non-contacts.](https://suggestion.telegram.org/c/10548)

I have voted, hopefully they will put it because not having this option is nonsense.
