### ISSUE TITLE
drag file from telegram desktop on linux

### ISSUE THREAD

**Issue by kasumiru** [telegramdesktop/tdesktop#17291]
### Steps to reproduce

1. install any linux desktop (kde, gnome, xfce), install all updated.
2. download binary telegram desktop from telegram.org OR install from snap, or another install
3. drag the mouse file "config.json" or any zip files, pictures FROM telegram TO destop, or dolphin, or thunar, or konqueror.
4. nothing happens or appear small red crossed circle.

### Expected behaviour

file moving and copyed to desktop or dolphin

### Actual behaviour

nothing happens

### Operating system

kde, ubuntu 20.04.3 LTS

### Version of Telegram Desktop

3.2.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Yeah, I can confirm it doesn't work, but tdesktop seem to do a reasonable thing, it throws path to the file to QMimeData:
https://github.com/telegramdesktop/tdesktop/blob/9308615361c77d983bac458e48196646b0660c3b/Telegram/SourceFiles/history/history_inner_widget.cpp#L1330-L1342
That seem to work fine on Windows, maybe Qt doesn't implement some protocol for DnD or implements it incorrectly? :thinking: 
Don't you know how to debug this on file managers' side?

**Comment by kasumiru** [comment]
@ilya-fedin Thank You for answer! 

`That seem to work fine on Windows`: 
-- it work very cool, quickly and perfect in windows. but so sad in linux. I so love telegram drag&drop files if you knew it... 

`Don't you know how to debug this on file managers' side?`:
-- from terminal run strace dolphin (or another file manager) ? ptrace, dmesg, show logs; run dolphin in debug mode (from Dolphin official github repo: -d, --debugger Show the debugger pane and additional View menu options)
but what will it change? I seems it need change or telegram code or doplhin code, or linuxt plazma code..

**Comment by ilya-fedin** [comment]
> -- from terminal run strace dolphin (or another file manager) ? ptrace, dmesg, show logs; run dolphin in debug mode (from Dolphin official github repo: -d, --debugger Show the debugger pane and additional View menu options)

I don't think strace/ptrace are helpful in this situation, they show kernel syscalls while we need a reason why it doesn't accept DnD, so looking  at kernerl syscalls is useless.

> but what will it change? I seems it need change or telegram code or doplhin code, or linuxt plazma code..

Well, I don't know why they don't accept DnD from Telegram, so we should find either a way to see how to debug that (I don't know how to debug DnD) or ask help from file manager developers...
