### ISSUE TITLE
Scrolling with mouse whell sometimes doesn't work

### ISSUE THREAD

**Issue by timur-enikeev** [telegramdesktop/tdesktop#17298]
### Steps to reproduce

1. Install Telegram Desktop 3.2.4 Linux (https://telegram.org/dl/desktop/linux)
2. Use it (or leave launched) for some hours.
3. Open any dialog with many messages
4. Try to scroll with mouse wheel

### Expected behaviour

Scrolling the dialog

### Actual behaviour

The dialog is not scrolled. It only can be scrolled by a scrollbar.

### Operating system

Ubuntu 20.04.3 LTS 

### Version of Telegram Desktop

3.2.4

### Installation source

Static binary from official website

**Comment by timur-enikeev** [comment]
There was not the problem earlier. It appeared some weeks ago after Telegram update.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/17254
