### ISSUE TITLE
Characters are broken for some of sprachraum

### ISSUE THREAD

**Issue by darkcircle** [telegramdesktop/tdesktop#173]
in some cases of using any kind of east-asia area language(Chinese, Japanese, Korean and Vietnamese...), many characters are broken usually and it looks like a blank square stream. we cannot suggest to change force font-binding for specific case(or application) to the linux distribution maintainer, and It will not be efficient.

so I suggest to change default font family to the Source Han Sans(a.k.a Noto Sans CJK, 本Gothic), which can make to show more characters correctly. If my suggestion is applied, Chinese, Japanese, Korean and Vietnamese(in alphabetical order) can uses bugfixed application. and they can see the correct character string.

Considering this suggestion will be better to enlarge the user base.

**Comment by auchri** [comment]
Is this still the case? If yes, reopen the issue
