### ISSUE TITLE
Download icon stuck at 100%

### ISSUE THREAD

**Issue by archit5846** [telegramdesktop/tdesktop#17308]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/43984656/143873378-c0cf9d44-2f46-4dee-ba54-06d3644827c4.png)
been there waiting for hours, changed wifi and all, it is stuck right there, it was working fine in the morning 

### Expected behaviour

The file should be downloaded

### Actual behaviour

The download is stuck at 100%

### Operating system

Win 7

### Version of Telegram Desktop

3.2.5

### Installation source

Static binary from official website

**Comment by ho-229** [comment]
I also had same problem, it looks like the file has been downloaded but the status is not updated.
