### ISSUE TITLE
[Feature Request] Enable to schedule posts in channel

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1730]
It would be great if you let us to schedule posts in channels for sending later, something same as facebook.

Thanks

**Comment by neesti** [comment]
+1

**Comment by auchri** [comment]
@neesti 

stop that `+1` please

![image](https://cloud.githubusercontent.com/assets/5092164/13647557/f9a7d50e-e634-11e5-9a3a-9fd34490322e.png)

**Comment by auchri** [comment]
btw. no api for that feature
