### ISSUE TITLE
this especial charecter "⃞" can go beyond the message box

### ISSUE THREAD

**Issue by rayanlancelotap** [telegramdesktop/tdesktop#17304]
### Steps to reproduce

use telegram desktop or android version
try to send a message
use too many of this character "⃞"(at least 35 or 50)

### Expected behaviour

the text should be inside the message box with correct line breaks

### Actual behaviour

text goes beyond the message box border and has no line breaks
[example1](https://s4.uupload.ir/files/telegram_852w.jpg)
[example2](https://s4.uupload.ir/files/telegram2_lkre.jpg)
some of my friends said that made their phones when they see these messages.
actually "⃞" is not something I use but some people abuse it in groups.

### Operating system

windows 7

### Version of Telegram Desktop

3.2.5

### Installation source

Static binary from official website

**Comment by 1289da** [comment]
****

**Comment by 1289da** [comment]
```
> ``
```

**Comment by 1289da** [comment]
Yes

**Comment by 1289da** [comment]
""

**Comment by 1289da** [comment]
"⃞

**Comment by 1289da** [comment]
f8af0-94272

**Comment by rayanlancelotap** [comment]
> f8af0-94272

hi, what that means?

**Comment by Aokromes** [comment]
strange spam i cannot delete xd

**Comment by 1289da** [comment]
"
