### ISSUE TITLE
does desktop-app repository have any documentation for it's libraries?

### ISSUE THREAD

**Issue by AMP999** [telegramdesktop/tdesktop#17303]
I want to modify the telegram desktop app source code and I need to use your libraries but I haven't found any documentation around your libraries. is there any?
at this time I need lib_rpl and lib_base documentations specifically
thank you

**Comment by john-preston** [comment]
@AMP999 No, there is no documentation, sorry.

**Comment by 0xNima** [comment]
@AMP999 what kind of modification? maybe I could help you

**Comment by AMP999** [comment]
do you consider to make one? and if you do can I help?

**Comment by AMP999** [comment]
> @AMP999 what kind of modification? maybe I could help you

thank you. how can I contact you?

**Comment by 0xNima** [comment]
> 

My telegram id @uncle_nima
