### ISSUE TITLE
How to generate compile_commands.json for clangd?

### ISSUE THREAD

**Issue by XiangQingW** [telegramdesktop/tdesktop#17309]
I'm using emacs with clangd to read the code, however, I can't find a method to generate compile_commands.json.

**Comment by john-preston** [comment]
@XiangQingW Google suggests to set CMAKE_EXPORT_COMPILE_COMMANDS environment variable before invoking configure.sh from the instructions (which calls CMake). Or maybe -D CMAKE_EXPORT_COMPILE_COMMANDS=ON in configure.sh arguments will work?..

**Comment by XiangQingW** [comment]
It doesn't work. When I remove the -GXcode argument, compile_commands.json can be generated. But clangd has many `Couldn't build compiler invocation` error messages when loading the compile_commands.json file.

**Comment by XiangQingW** [comment]
I use ggtags and dumb-jump as a workaround.
