### ISSUE TITLE
[Feature Request] Easy move channels/contacts to the particual folder using drag'n'drop

### ISSUE THREAD

**Issue by nickzcv** [telegramdesktop/tdesktop#17301]
### Is your feature request related to a problem?

UX issue

### Describe the solution you'd like

Add a handler to d'n'd action for foldr editing without searching how/where to do it.

### Describe alternatives you've considered

Any other better idea how to improve editing of the folders?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7463
