### ISSUE TITLE
Linking failure.

### ISSUE THREAD

**Issue by xavetar** [telegramdesktop/tdesktop#17306]
### Steps to reproduce

1. Parallels Desktop (M1).
2. Gist: https://gist.github.com/xavetar/c1560ac8f7a0bd3496a762e09c340d6b

### Expected behaviour

I tried to recompile all the components in various ways, but the error occurs anyway when linking these components. This error also occurred: "undefined reference to `epoxy_load_egl'", but after disabling some epoxy QT5 patches, it disappeared. Configuration for build: 

CMAKE_PREFIX_PATH=$QT5_PREFIX/lib/cmake cmake -B build . \
	-DJPEG_LIBRARY=$LibrariesPath/mozjpeg-cache/lib64/ \
	-DJPEG_INCLUDE_DIR=$LibrariesPath/mozjpeg-cache/include \
	-DOPENAL_LIBRARY=$LibrariesPath/openal-cache/lib64 \
	-DOPENAL_INCLUDE_DIR=$LibrariesPath/openal-cache/include/AL \
	-Dtg_owt_DIR=$LibrariesPath/tg_owt-cache/lib64/cmake/tg_owt \
	-DECM_DIR=$LibrariesPath/extra-cmake-modules-cache/share/ECM/cmake \
	-DDESKTOP_APP_QT6=off \
	-DTDESKTOP_API_ID=17349 \
	-DTDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb

### Actual behaviour

[1892/1892] Linking CXX executable telegram-desktop
FAILED: telegram-desktop 
: && /usr/bin/c++  -Wl,--as-needed -pthread @CMakeFiles/Telegram.rsp -o telegram-desktop  && :
/usr/bin/ld: /usr/src/Libraries/Qt-5.15.2-cache/lib/libQt5Gui.a(qtextengine.o): in function `QTextItemInt::QTextItemInt(QGlyphLayout const&, QFont*, QChar const*, int, QFontEngine*, QTextCharFormat const&)':
/home/parallels/Downloads/Workdir/qt_5_15_2/qtbase/src/gui/text/qtextengine.cpp:4100: multiple definition of `QTextItemInt::QTextItemInt(QGlyphLayout const&, QFont*, QChar const*, int, QFontEngine*, QTextCharFormat const&)'; Telegram/lib_ui/liblib_ui.a(qtextitemint.cpp.o):qtextitemint.cpp:(.text+0x0): first defined here
/usr/bin/ld: /usr/src/Libraries/Qt-5.15.2-cache/lib/libQt5Gui.a(qtextengine.o): in function `QTextItemInt::QTextItemInt(QGlyphLayout const&, QFont*, QChar const*, int, QFontEngine*, QTextCharFormat const&)':
/home/parallels/Downloads/Workdir/qt_5_15_2/qtbase/src/gui/text/qtextengine.cpp:4100: multiple definition of `QTextItemInt::QTextItemInt(QGlyphLayout const&, QFont*, QChar const*, int, QFontEngine*, QTextCharFormat const&)'; Telegram/lib_ui/liblib_ui.a(qtextitemint.cpp.o):qtextitemint.cpp:(.text+0x0): first defined here
/usr/bin/ld: /usr/src/Libraries/Qt-5.15.2-cache/lib/libQt5Gui.a(qtextengine.o): in function `QTextItemInt::initWithScriptItem(QScriptItem const&)':
/home/parallels/Downloads/Workdir/qt_5_15_2/qtbase/src/gui/text/qtextengine.cpp:4112: multiple definition of `QTextItemInt::initWithScriptItem(QScriptItem const&)'; Telegram/lib_ui/liblib_ui.a(qtextitemint.cpp.o):qtextitemint.cpp:(.text+0x104): first defined here
/usr/bin/ld: /usr/src/Libraries/tg_owt-cache/lib64/libtg_owt.a(screen_capturer_x11.cc.o): undefined reference to symbol 'XFixesCreateRegion'
/usr/bin/ld: /usr/src/Libraries/libXfixes-cache/lib/libXfixes.so.3: error adding symbols: DSO missing from command line

### Operating system

Fedora 35

### Version of Telegram Desktop

master/dev/ci2 etc...

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Switch to Qt 6 build, Qt 5 build is abandoned (at least I don't do any checks and improvements for it)

**Comment by vexaroniter** [comment]
> Switch to Qt 6 build, Qt 5 build for Linux is abandoned (at least I don't do any checks and improvements for it)

Okey, thx, i will try. I tried to use QT6, but when specifying -DQT6_DIR=.... An error occurred, in QT5 there is pkgconfig, but no in QT6 and get error: "Qt6::Concurrent" etc.

**Comment by ilya-fedin** [comment]
you don't need to specify anything like this, are you following official instrustions for Docker?

**Comment by vexaroniter** [comment]
> you don't need to specify anything like this, are you following official instruсtions for Docker?

The Dockerfile has been completely rewritten (Gist). In order not to use docker. He gives me mixed emotions. The bottom line is that the docker file is only for the x86_64 architecture.

**Comment by ilya-fedin** [comment]
Doesn't centos image exist for other architectues? If yes, it should work after chainging url to cmake binary.

**Comment by vexaroniter** [comment]
> Doesn't centos image exist for other architectues? If it does, it should work after changing url to cmake binary.

It's not about the binary, it's about the package:

"RUN yum -y install https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm && yum clean all".

Considering this and the pull request created in another section, a similar error will occur after the patch, which will cause the inability to compile.

**Comment by ilya-fedin** [comment]
This repo is used for newer version of git, you can replace it with any other way of getting newer git if you know any. I don't understand though why are you creating a custom script based on Dockerfile rather than using flatpak or snap package.

**Comment by vexaroniter** [comment]
> This repo is used for newer version of git, you can replace it with any other way of getting newer git if you know any. I don't understand though why are you creating a custom script based on Dockerfile rather than using flatpak or snap package.

I want to compile, not use the off-the-shelf. Why publish your code if it can't be compiled.

**Comment by ilya-fedin** [comment]
You can build your own package with flatpak-builder. The thing is flatpak manifest is adapted for other arches and it's more logical to use it rather than creating a script based on build method not adapted for such usage.

**Comment by vexaroniter** [comment]
> You can build your own package with flatpak-builder. The thing is flatpak manifest is adapted for other arches and it's more logical to use it rather than creating a script based on build method not adapted for such usage.

Thanks for the advice, I didn't know that this is can be.
