### ISSUE TITLE
[Feature Request] About privacy settings

### ISSUE THREAD

**Issue by sakurayz** [telegramdesktop/tdesktop#17300]
In the privacy settings, some items only have everybody and my contacts. For security purposes, there should be a nobody option in all items, which is left to the user to decide.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by sakurayz** [comment]
> such feature belongs to https://bugs.telegram.org/

I think this is not a bug, but a design idea

**Comment by RememberTheAir** [comment]
@sakurayz you can post it on https://suggestions.telegram.org
