### ISSUE TITLE
Add a dynamic blocking/report feature to prevent hackers/trolls from re-entering a group[Feature Request] 

### ISSUE THREAD

**Issue by mechanator** [telegramdesktop/tdesktop#17311]
### Is your feature request related to a problem?

I am a QA, coder, and tester for Oxen.io. I administrate the chat for the Oxen Community channel and for service node information.
It's a crypto project.
Recently there has been a rash of silent users that join, don't say anything and retrieve the list of all members.
Then they either offer spam/scam invite with another account pretending to be the admin or dev of the project.
The usually do this in direct message mode.
No matter how we pin a message or educate the community users, these hackers persist.
We warn the regular users that Admins do not DM first.

If they are removed from the group, they come back with a different username.
Sometimes referring to being banned and came right back. Sometimes using the same automated bot in DM to users to attempt to steal their crypto coins or tokens.
One particular disgruntled user has been evading ban and reports to telegram for the content he has posted in channel.
Either the report and ban feature is broken or they have a way to change phone numbers or credentials that Telegram uses.
This is a security concern since the hacker(s)/trolls might be able to login as an administrator of the group and wreak havoc.

I don't want to know the identity of the offenders, as that would go against the privacy principles of the project.
However, I want to be able to permanently ban the user/hacker/troll using maybe the mac address of the device(that can be changed), the IMEI of the phone(that is really hard to change on phones), or IP range of the ISP they use.

Is there a way to construct such a bot or a process to submit the information to Telegram for banning which is persistent from certain groups.

I am not asking for a global ban for a user of the whole Telegram network. Although the administrators of Telegram should have a link on their homepage to report constant abuse and hacker attacks.
There has to be another way to control entry into a chat group or supergroup.
There are misfits selling old, unused accounts online for as little as 2k IDs for $9 USD.
This is a security and code concern. There's no point in using the product if there are devils breaking the harmony of civil chat all the time.
This is a project engineering failure on both UX and UI. Priority 2

### Describe the solution you'd like

An escalation tool within telegram so that the offending hacker/troll is tracked and banned by known methods, and prevented from coming back in in real-time.  The admin of that channel doesn't need to know the name of the offender, but an identification is possible within Telegram internally.   The offending user is immediately warned with a new escalated message explaining that they are under a higher level of scrutiny.

A ban preferably at the ISP level or country level.   Or multi-isp ban within the same geographic area since it's easy for the trolls/hackers to change to a different  mobile network or wifi AP.

### Describe alternatives you've considered

Stop using Telegram or make a zombie channel for support advising users  to go to a public Session group chat for support.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
