### ISSUE TITLE
snap telegram-desktop fails to start, seccomp violation detected.

### ISSUE THREAD

**Issue by qtlin** [telegramdesktop/tdesktop#17312]
### Steps to reproduce

$ sudo snap install telegram-desktop
$ snap run telegram-desktop 
Gtk-Message: 19:06:24.763: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:06:24.764: Failed to load module "pk-gtk-module"
Gtk-Message: 19:06:24.764: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:06:24.764: Failed to load module "pk-gtk-module"
$ journalctl --since=today | grep 'audit.*telegram' | tail -1
Nov 29 19:06:24 localhost audit[46616]: SECCOMP auid=1500 uid=1500 gid=1500 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=46616 comm="telegram-deskto" exe="/snap/telegram-desktop/3343/usr/bin/telegram-desktop" sig=0 arch=c000003e **syscall=314** compat=0 ip=0x7f4e5222b89d code=0x7ffc0000
$ /var/lib/snapd/snap/core/11993/usr/bin/scmp_sys_resolver **314**
**sched_setattr**
$ snap run --shell telegram-desktop
bash-5.0$ grep sched_setattr /var/lib/snapd/seccomp/bpf/snap.${SNAP_NAME}*src
bash-5.0$ sudo sh -c 'for i in  /var/lib/snapd/seccomp/bpf/snap.${SNAP_NAME}*src;do echo sched_setattr >> $i;done'
bash-5.0$ sudo /usr/lib/snapd/snap-seccomp compile /var/lib/snapd/seccomp/bpf/snap.telegram-desktop.telegram-desktop.src /var/lib/snapd/seccomp/bpf/snap.telegram-desktop.telegram-desktop.bin 
/usr/lib/snapd/snap-seccomp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/lib/snapd/snap-seccomp)
/usr/lib/snapd/snap-seccomp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/snapd/snap-seccomp)
bash-5.0$ 

Reference: https://snapcraft.io/docs/debug-snaps Seccomp violations section.

### Expected behaviour

Normal startup.

### Actual behaviour

silent exit

### Operating system

Fedora 35

### Version of Telegram Desktop

telegram-desktop   3.2.2 3343 latest/stable  telegram.desktop

### Installation source

Snap

### Logs

```shell
Nov 29 19:06:24 localhost audit[46616]: SECCOMP auid=1500 uid=1500 gid=1500 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=46616 comm="telegram-deskto" exe="/snap/telegram-desktop/3343/usr/bin/telegram-desktop" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7f4e5222b89d code=0x7ffc0000
```

**Comment by qtlin** [comment]
any updates?

**Comment by ilya-fedin** [comment]
> any updates? snap v3544 same behavior.

I don't quite understand what do you expect from tdesktop; according to the log you provided a binary from your system called '/usr/lib/snapd/snap-seccomp' is incompatible with glibc from your system

**Comment by qtlin** [comment]
1. '/usr/lib/snapd/snap-seccomp' is provided by snap, not my system.
2. SECCOMP settings are provided by telegram-desktop snap files and they are missing **sched_setattr** attribute.
3. an attempt to add **sched_setattr** by following instructions found in a snap manual fails but that seems to be a snap bug.

**Comment by ilya-fedin** [comment]
> 1. '/usr/lib/snapd/snap-seccomp' is provided by snap, not my system.

No, tdesktop snap has no such binary, it's definitely a part of your system.

> 2\. SECCOMP settings are provided by telegram-desktop snap files

That's false. tdesktop snap has no seccomp settings and I believe snap doesn't allow snaps to provide custom seccomp settings/apparmor profiles.

It seems you have problems with snapd, not with tdesktop snap.

**Comment by qtlin** [comment]
well, there seems to be a confusion between **telegram-desktop snap** and **snap** environment. when I say **snap** by itself it means snap environment.
At the end telegram-desktop snap and snap itself result in SECCOMP sched_setattr error. Snap own instructions explain how to add sched_setattr to a snap which supposedly missing it.
Again, I am not an expert in snap internals but if telegram-desktop snap by design supposed to run on any system where snapd is installed then telegram-desktop snap should take care of all cases or know how to fix them. No other snap packaged application causes SECCOMP sched_setattr error on this system and I tested quite a few.

**Comment by ilya-fedin** [comment]
Look at your errors:

> /usr/lib/snapd/snap-seccomp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/lib/snapd/snap-seccomp) /usr/lib/snapd/snap-seccomp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/snapd/snap-seccomp)

It's clear your snap environment is broken, snap's utility can't launch due to incompatibilities with you system's glibc

**Comment by qtlin** [comment]
1. /lib/x86_64-linux-gnu/libc.so.6 is provided by snapd core
2. why do I need to deal with snap-seccomp? telegram-desktop snap should provide sched_setattr to begin with.

**Comment by ilya-fedin** [comment]
I don't know why do you deal with snap-seccomp. tdesktop snap works perfectly fine on Ubuntu. It seems there are some bugs in snapd on Fedora. Maybe some incompatibilities with SELinux or etc.

**Comment by qtlin** [comment]
No other snaps fail.

**Comment by ilya-fedin** [comment]
I don't believe you checked all the snaps in the snap store
