### ISSUE TITLE
[Feature Request] Show the number of clicks on links in channel

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1731]
Hi
Please show number of clicks on links in channels for admins. This is known as engagement factor. And it's really important for webmasters to know how many users click on their links in channels.

Thanks

**Comment by neesti** [comment]
+1

**Comment by stek29** [comment]
bit.ly ?

**Comment by DaFri-Nochiterov** [comment]
@stek29 goo.gl x)
This is `API issue`?

**Comment by auchri** [comment]
Yes, I don't think that's possible with the current api.
