### ISSUE TITLE
[Feature Request] Add the ability to select an arbitary scale through the UI

### ISSUE THREAD

**Issue by AlexByte** [telegramdesktop/tdesktop#17326]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

Add the ability to select an arbitrary interface scale through the UI 

### Describe alternatives you've considered

or add a tooltip hint that you can use the command line parameter `-scale`

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/ff331c040a8e73dbcd6adfff696ea2af9f0f6a08

**Comment by john-preston** [comment]
This should be possible in the new 4.5.5 beta version.
