### ISSUE TITLE
no 32bit for linux but still for windosh**

### ISSUE THREAD

**Issue by mckaygerhard** [telegramdesktop/tdesktop#17328]
### Steps to reproduce

i try to connect using 32bit linux and cannot do

### Expected behaviour

connect to telgram network

### Actual behaviour

there's 3 king of build for windo but none of 32bit for linux:
![image](https://user-images.githubusercontent.com/1571724/144442287-cf6aa217-1f4d-497a-867a-00edffeb90c7.png)

### Operating system

linux 32bit

### Version of Telegram Desktop

2.6

### Installation source

Static binary from official website

### Logs

```shell
RPCError 406: UPDATE_APP_TO_LOGIN
```

**Comment by ilya-fedin** [comment]
yeah, 32-bit Windows has a way bigger market share, so it's still supported. All I can to suggest is either switch to 64-bit Linux or to 32-bit Windows.

**Comment by mckaygerhard** [comment]
> yeah, 32-bit Windows has a way bigger market share, so it's still supported. All I can suggest is to switch to either 64-bit Linux or 32-bit Windows.

my laptop is 32bit only.. of course is 3GHZ cpu with radeon gpu enought to use in office.. upgrade to 64bit is buy a new one.. is nonsense..

**Comment by ilya-fedin** [comment]
is it a hello from 2002?

**Comment by mckaygerhard** [comment]
> is it a hello from 2002?

i buy it in 2012 .. please!

**Comment by mckaygerhard** [comment]
> is it a hello from 2002?

i buy it in 2012.. windo xp still support many laptops and is widelly used in some countires.. windows still made 32bit apps. for those devices.. but linux developers just forgotten that? what a kind of vision is that?

**Comment by a316i** [comment]
I have 32-bit laptop too. Why I can't use telegram? I live in a poor family, and can't buy new laptop and phone. Please, back 32-bit linux support.

**Comment by ilya-fedin** [comment]
> i buy it in 2012..

You bought Pentium 4 in 2012? Well, it's a pity. My condolences.

> windo xp still support many laptops and is widelly used in some countires..

Windows XP is not supported by tdesktop, as well.

> what a kind of vision is that?

It's a pragmatic vision: at the time of dropping support, market share of 32-bit Linux builds was 0.1% IIRC according to statistics @john-preston got from server developers. No one will make a build for you personally.

**Comment by mckaygerhard** [comment]
> > i buy it in 2012..
> You bought Pentium 4 in 2012? Well, it's a pity. My condolences.
give me the money then! puff what a response is that?

the real big world is poor! and tech only get to most confortable people not to "all" people! incredible why M$ is ruled the world with piracy programs!

> Windows XP is not supported by tdesktop, as well.
in any case still works in win7 32bit

> > what a kind of vision is that?
> It's a pragmatic vision: at the time of dropping support, market share of 32-bit Linux builds was 0.1% IIRC according to statistics @john-preston got from server developers. No one will make a build for you personally.

unfair and pretty bad.. now i uderstand mr robot series!!

**Comment by ilya-fedin** [comment]
> give me the money then! puff what a response is that?

The fact you're not the target audience doesn't mean someone should give you money...

**Comment by a316i** [comment]
Ok, I will compile on my shit laptop client without ad (and it will no blocked) with 32-bit support. Special for my friend.

**Comment by Newbytee** [comment]
> It's a pragmatic vision: at the time of dropping support, market share of 32-bit Linux builds was 0.1% IIRC according to statistics @john-preston got from server developers. No one will make a build for you personally.

Were there difficulties keeping the 32-bit Linux build building, or was it just dropped because of few people using it?

**Comment by ilya-fedin** [comment]
> Were there difficulties keeping the 32-bit Linux build building, or was it just dropped because of few people using it?

I don't really remember. But dropping a build means -4 hours of building when doing a release

**Comment by mckaygerhard** [comment]
> Ok, I will compile on my shit laptop client without ad (and it will no blocked) with 32-bit support. Special for my friend.

i guess it cannot be.. cos the only work ins on w2in32 api.. not in linux one.. of course i not seen the code .. cos i am here as user

**Comment by ilya-fedin** [comment]
there are distributions that still have 32-bit builds, I guess you can install one and ask its maintainers to add tdesktop to their repositories. So mr. robot-ish, right?

**Comment by mckaygerhard** [comment]
> There are distributions that still have 32-bit builds, I guess you can install one and ask its maintainers to add tdesktop to their repositories. So mr. robot-ish, right?

problem are in 32bit in my firend's person.. is a bad thinking that hole world has money to upgrade hardware.. that machine is windo7 32bit with desktop telegram 32bit.. i have no access, he chat me!


![image](https://user-images.githubusercontent.com/1571724/144453933-64f4c60a-9874-4aba-a5bc-95208ae03162.png)

**Comment by ilya-fedin** [comment]
> is a bad thinking that hole world has money to upgrade hardware..

ask to support Windows 98 :see_no_evil:

**Comment by Newbytee** [comment]
> ask to support Windows 98

It's Windows 7.

**Comment by mckaygerhard** [comment]
> > is a bad thinking that hole world has money to upgrade hardware..
> 
> ask to support Windows 98 see_no_evil

again .. do you check the update complete pictur5e. are you playing or take it in serious? win7 with lasted updates!

**Comment by ilya-fedin** [comment]
> It's Windows 7.

I mean ask to support Windows 98 because someone somewhere uses a PC from 90's

**Comment by ilya-fedin** [comment]
It was ~20 years from the last 32-bit processor has been manufactured, c'mon!

**Comment by mckaygerhard** [comment]
> > It's Windows 7.
> 
> I mean ask to support Windows 98 because someone somewhere uses a PC from 90's

please stop cringle.. is a computers firends: windows7 with dual core 2 duio .. 8Gb ram..

**Comment by ilya-fedin** [comment]
> please stop cringle.. is a computers firends: windows7 with dual core 2 duio .. 8Gb ram..

core 2 duo is a 64-bit processor

**Comment by mckaygerhard** [comment]
> > please stop cringle.. is a computers firends: windows7 with dual core 2 duio .. 8Gb ram..
> 
> core 2 duo is a 64-bit processor

i mean is a person that is not in my side.. is not the point of the topic.. my point is that we cannot force people to made complete upgrade is a cost that is ridicule! puff well thanks in any case! is clear whay M$ rule the world!
@ilya-fedin

**Comment by ilya-fedin** [comment]
> my point is that we cannot force people to made complete upgrade is a cost that is ridicule!

imagine your friend used Windows 98 and you came here to support Windows 98 because he is poor...

**Comment by mckaygerhard** [comment]
@Aokromes you closed cos a person like @ilya-fedin  just take the issue as a jocke.. i guess is related to #17330 so all of you are wrong ther's more people wanted this

**Comment by yPhil-gh** [comment]
> It was ~20 years since the last 32-bit processor has been manufactured, c'mon!

That is widly incorrect : As of 2022, the _current_ Raspberry Pi model runs a 32bit distro due to its 32bit GPU. And that is just the first example that comes to mind.

**Comment by ilya-fedin** [comment]
rpi is arm while the talk here is about x86
