### ISSUE TITLE
Use keyboard layout for shortkeys

### ISSUE THREAD

**Issue by Huluk** [telegramdesktop/tdesktop#1732]
On OS X, the telegram shortkeys do not follow the selected keyboard layout but (presumably) use a QWERTY layout. This is confusing, and on my specific layout I can't press cmd+C to copy text, because my C key is located on the position of the QWERTY R key (telegram cmd+R for recording a voice message).

**Comment by stek29** [comment]
Are you sure it's about TDesktop?

> CMD+R for recording a voice message

This never existed in TDesktop, only in native macOS app

**Comment by Huluk** [comment]
Ah, they are not the same? I'm sorry, I only found this bug tracker and assumed this app is the same as the native one. Closing.

**Comment by stek29** [comment]
The native is [here](/overtake/telegram)
But it has private bug tracker, so you'd have to use "Ask a question" button and contact support.

**Comment by Huluk** [comment]
Thanks!
