### ISSUE TITLE
Cannot read long names completely

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#17327]
### Steps to reproduce

Spot a user with a shamelessly long name (this phrase itself would be a shamelessly long name).

### Expected behaviour

Make them tickers, or wrap, or extend to an enough extent to fit, or limit the length like it was with the RTL switcher in my name, I don't know.

### Actual behaviour

![telegram_long_names1](https://user-images.githubusercontent.com/2134486/144303026-9434b717-1d8b-46be-8a83-7d5a78de62cf.gif)

### Operating system

Debian GNU/Linux 12, compiz-reloaded 0.8.18

### Version of Telegram Desktop

3.2.6 beta

### Installation source

Static binary from official website

**Comment by bodqhrohro** [comment]
Still relevant.
![2022-07-07-123656_1366x768_scrot](https://user-images.githubusercontent.com/2134486/177743705-e9ab8072-0870-4f14-9162-d9fad22ebda3.png)
![2022-07-07-123813_1366x768_scrot](https://user-images.githubusercontent.com/2134486/177743714-ebe47918-fa84-4252-ac48-3c7f5f6a09de.png)

**Comment by Aokromes** [comment]
duplicate and api, telegram have filenames limited to 60 chars.

**Comment by bodqhrohro** [comment]
@Aokromes excuse me, how is this related to filenames?

**Comment by Aokromes** [comment]
oh misssread.

**Comment by bodqhrohro** [comment]
Totally relevant.

**Comment by bodqhrohro** [comment]
Meh, how did I miss it?
