### ISSUE TITLE
Telegram doesn't support appstream:// links

### ISSUE THREAD

**Issue by shdwchn10** [telegramdesktop/tdesktop#17323]
![Screenshot from 2021-12-01 14-59-33](https://user-images.githubusercontent.com/79763381/144230774-40e7e916-b5e8-4dec-af88-81b90bdf9098.png)
Link example: appstream://org.telegram.desktop

appstream links can be opened in GNOME Software and KDE Discover apps and it's useful for sharing purposes.

**Comment by shdwchn10** [comment]
Im still interested in this issue!

**Comment by Aokromes** [comment]
such issue belongs to https://bugs.telegram.org/
