### ISSUE TITLE
Old version 1.8.15 "about to stop working" but still listed in Readme

### ISSUE THREAD

**Issue by ssb22** [telegramdesktop/tdesktop#17338]
### Steps to reproduce

Look at the README.md in the tdesktop repository

### Expected behaviour

README.md should link to versions of Telegram Desktop that are still expected to work

### Actual behaviour

README.md links to Version 1.8.15 as the last version that supports Mac OS 10.6 through 10.9 and Windows XP/Vista.  But Version 1.8.15 on my old 10.7 Mac is now nagging me "The version you are using is out of date and will stop working soon".  No information is provided about why it's about to stop working (is the protocol due to change?), which other clients might be affected by this change (will third-party clients like telegram-cli be affected for example?) or when the change will take place.

### Operating system

Mac OS 10.7.5

### Version of Telegram Desktop

1.8.15

### Installation source

Static binary from official website

**Comment by mckaygerhard** [comment]
related to https://github.com/telegramdesktop/tdesktop/issues/17330

**Comment by Aokromes** [comment]
no

**Comment by ssb22** [comment]
Looking at the tdesktop git history, there was a tgcalls protocol update in July 2020 (tdesktop v2.3), I guess Telegram could now be sending nags to anyone using a version older than that, although I haven't found any announcement on their website (but just because I haven't found it doesn't mean it's not there somewhere).

If true, this would mean v1.8.15 would need the tgcalls change backported to it to keep working, otherwise old machines will have to run it on a more recent OS in a VM.

**Comment by ssb22** [comment]
Oh hold on, it's more complicated.  I just tried installing FreeBSD's `telegram-desktop` package v2.8.11 on a FreeBSD 12.2 VM (running in VirtualBox on the 10.7 Mac) and that one *also* won't let me log in: it lets me type in my phone number and then says "You are using an outdated app that is no longer supported. To access your messages, please update your app to the latest version." then "Internal server error"

So whatever this is, it seems it's also affecting v2.8.11 from July 2021.  It can't be the July 2020 tgcalls change to blame.

**Comment by Aokromes** [comment]
> Oh hold on, it's more complicated. I just tried installing FreeBSD's `telegram-desktop` package v2.8.11 on a FreeBSD 12.2 VM (running in VirtualBox on the 10.7 Mac) and that one _also_ won't let me log in: it lets me type in my phone number and then says "You are using an outdated app that is no longer supported. To access your messages, please update your app to the latest version." then "Internal server error"
> 
> So whatever this is, it seems it's also affecting v2.8.11 from July 2021. It can't be the July 2020 tgcalls change to blame.

afaik 3.2.5 is the minimum version needed to don't get the nag.

**Comment by ilya-fedin** [comment]
In case of macOS, old versions can theoretically be supported with [XQuartz](https://www.xquartz.org/releases/index.html). tdesktop will feel even more non-native, though. But not sure whether @john-preston wants support such kind of support or not.

**Comment by john-preston** [comment]
@ssb22 @mckaygerhard versions 1.8.15 on OS X 10.6, 10.7, 10.8, 10.9, Windows XP, Windows Vista and 2.4.4 on OS X 10.10, 10.11 and 32 bit Linux systems should allow you to log in (using another already logged in Telegram session) and use it except for chatting with newly registered users. They were allowed from the server side, but to be able to chat with all users you still need a new version on a (relatively) modern OS (Windows 7+, macOS 10.12+, Linux x86_64).

**Comment by mckaygerhard** [comment]
> @ssb22 @mckaygerhard versions 1.8.15 on OS X 10.6, 10.7, 10.8, 10.9, Windows XP, Windows Vista and 2.4.4 on OS X 10.10, 10.11 and 32 bit Linux systems should allow you to log in (using another already logged in Telegram session) and use it except for chatting with newly registered users. They were allowed from the server side, but to be able to chat with all users you still need a new version on a (relatively) modern OS (Windows 7+, macOS 10.12+, Linux x86_64).

sorry but @john-preston  i noted but seems today there's no more tricks! i am unnable to login inclusivelly using scan code.. so this becomes a mayor issue in all sides.. in open BSD and haiku i cannot able to login neither in 32bit machines.. i need 32bit build on linux, using GLIBC 2.19

and now @Aokromes  thi is definitivelly related to #17330

**Comment by ssb22** [comment]
We have not had any more warnings from Telegram saying the old version is about to stop working.  I don't know if that means they've changed their mind or what.

**Comment by mckaygerhard** [comment]
interesting.. my older version 1.8.55 is working.. but my 2.4.4 is not working anymore.. so @ssb22  i guess nothing is changed yet
