### ISSUE TITLE
Telegram Desktop has not button "Go to Begin" in calendar

### ISSUE THREAD

**Issue by kasumiru** [telegramdesktop/tdesktop#17332]
### Steps to reproduce

Open any chat in Telegram Desktop, click "find" buttom, next click "calendar" button. Past versions of Telegram Desktop had a button "Go to Begin" - in left-bottom place. 

### Expected behaviour

See button "Go to Begin"

### Actual behaviour

button is missing

### Operating system

windows 10 build 19042.1348

### Version of Telegram Desktop

3.2.8

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@kasumiru You can press-n-hold the up arrow in the calendar box title.
