### ISSUE TITLE
Voice message does not adhere to voice call input device selection

### ISSUE THREAD

**Issue by jtsiomb** [telegramdesktop/tdesktop#17337]
### Steps to reproduce

Without having configured the correct microphone as a system default (not using pulse audio, and not having configured it as default through the ALSA configuration files), and while having selected the correct audio input device under advanced->call settings (voice call audio input works fine), try to send a voice message from the microphone icon in the chat text field.

### Expected behaviour

Message being recorded through the device selected in the audio input settings.

### Actual behaviour

Nothing is being recorded, probably trying to record from the "default" audio input device which has no microphone connected.

### Operating system

Debian GNU/Linux, no desktop environment, no global audio daemon (ALSA audio only).

### Version of Telegram Desktop

3.1.8

### Installation source

Other (unofficial) source

**Comment by jtsiomb** [comment]
Also tested 3.2.5 from the official releases, same behaviour.

**Comment by ilya-fedin** [comment]
Yeah, voice call settings are only for voice calls, this is not a bug. You can file a feature request for an option for voice messages (don't forget to check whether it's already exists, though).

**Comment by jtsiomb** [comment]
I don't care enough to request it as a new feature. I only reported it because I assumed it is a bug, and wanted to help you out in case nobody noticed it. I'll leave it up to you to decide if it makes sense to have two different options for the same thing, in which case certainly consider this not a bug and leave it closed, or if it would be better to have a single microphone input option for both, in which case feel free to re-open it.
