### ISSUE TITLE
System hangs when sending a video

### ISSUE THREAD

**Issue by nextuponstream** [telegramdesktop/tdesktop#17331]
### Steps to reproduce

1. open telegram flatpak
2. open any chat
3. try to send any video (I tested one internet video and one screen recording I did)
4. wait a few seconds

### Expected behaviour

The video is sent. 

### Actual behaviour

The system freezes completely, forcing a hard reboot. No video is sent.

When using desktop entry, the computer fails to send the first video.

When running telegram with `flatpak run org.telegram.desktop`, the first video can be sent. Then when sending another video, the system hangs. 

### Operating system

Pop!_OS 21.04 x86_64

### Version of Telegram Desktop

3.2.5

### Installation source

Flatpak

### Logs

Excuse the phone screen share but I can't screenshot when the system hangs. These are the last logs: 
![image](https://user-images.githubusercontent.com/78037645/144586026-5085583a-c7de-4e35-841c-c86e97e58df0.png)

**Comment by ilya-fedin** [comment]
Have you checked what's going on with system load on freeze?

**Comment by Opendreas** [comment]
I have the same on OpenSUSE Leap 15.3 with Telegram flatpak 3.2.5 and 3.3.0.
The system freezes when uploading any files.

**Comment by GUOguocai88** [comment]
是的，兄弟&nbsp;&nbsp;我现在尝试破解密码。


---Original---
From: ***@***.***&gt;
Date: Fri, Dec 10, 2021 01:42 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [telegramdesktop/tdesktop] System hangs when sending a video(Issue #17331)




 
I have the same on OpenSUSE Leap 15.3 with Telegram flatpak 3.2.5 and 3.3.0.
 The system freezes when uploading any files.
 
&mdash;
