### ISSUE TITLE
Getting please update messages when no update is available

### ISSUE THREAD

**Issue by void-spark** [telegramdesktop/tdesktop#17336]
### Steps to reproduce

Install and use telegram on debian (using apt), either bullseye, or bullseye-backports

### Expected behaviour

Only get please update messages if updating is in fact possible

### Actual behaviour

Get please updated messages, but do not have a way to update

### Operating system

debian

### Version of Telegram Desktop

2.6.1(debian)/2.9.2(backports)

### Installation source

Static binary from official website

**Comment by void-spark** [comment]
It's not my intent to complain here, just maybe Telegram could reach out to debian to at least make sure the version they provide, and the required version, are in sync? :)

**Comment by RussianNeuroMancer** [comment]
This message is there even on latest Ubuntu (21.10) with latest stable package. I don't even talk about LTS releases...

**Comment by Aokromes** [comment]
this is server side message, nothing preston can fix, sub 3.2.5 clients will stop working soon.
