### ISSUE TITLE
When executing prepare.py to compile breakpad, an error is reported,

### ISSUE THREAD

**Issue by StraussLupusson** [telegramdesktop/tdesktop#17344]
![image](https://user-images.githubusercontent.com/47448295/144738137-caeb8d22-3040-45b6-be70-1f39668ec79a.png)
When executing prepare.py to compile breakpad, an error is reported, how can I solve this problem?

**Comment by ilya-fedin** [comment]
Duplicate of #16939

**Comment by StraussLupusson** [comment]
ok，thanks
