### ISSUE TITLE
Change position of notifications in RTL languages

### ISSUE THREAD

**Issue by tuxitop** [telegramdesktop/tdesktop#1734]
Currently there are no options to change the notifications behavior and position. Since RTL languages start from the right of the screen, when you start writing an RTL message, Telegram automatically moves the text to the right of the screen which is (if the window is maximized) the place where notifications are shown. So when you are writing a message in a maximized telegram window, any notification would block the text that you are writing.
I suggest implementing an option to change the position of the notification messages to the other corners of the screen.

PS: I saw #140 and I decided to open a new issue, I think the position of notifications is a bug in case of RTL languages and It shouldn't be considered as a feature request.

**Comment by srazi** [comment]
+1

**Comment by Aokromes** [comment]
#1387 ?

**Comment by neesti** [comment]
+1

**Comment by tuxitop** [comment]
@auchri I apologize for asking if you could please reopen this issue,  #1387 is a feature request which requires a complete redesign of the application, whereas the current position of notifications could be annoying in LTR languages if someone is typing a long text. It is not a redesign or anything specific to RTL languages.

**Comment by auchri** [comment]
But

> I suggest implementing an option to change the position of the notification messages to the other corners of the screen.

is the same as #140

**Comment by tuxitop** [comment]
I see. I was hoping for something with a "bug" label though. I hope we can have that feature sometime soon. Thank you and all the other great people working on this awesome service.
