### ISSUE TITLE
Can I fork tdesktop and add documentation to it?

### ISSUE THREAD

**Issue by AMP999** [telegramdesktop/tdesktop#17345]
as you know without documentation and tests it's painstaking to comprehend a large-scale code like telegram.
as I asked you earlier there is no documentation around telegram codes and also desktop app toolkit repositories.
so I decided to fork your code and add documentation comments in the code. maybe by the effort of community we make an acceptable documentation.
my question is am I allowed to do this? Are there any legal issues around this work?

**Comment by john-preston** [comment]
@AMP999 No legal issues, you're more than welcome to.

**Comment by AMP999** [comment]
Thank You
