### ISSUE TITLE
Multiple language spell checking stopped working in version 3.2.4

### ISSUE THREAD

**Issue by duritia** [telegramdesktop/tdesktop#17341]
### Steps to reproduce

1. Corrector for only one language active (my language: Portuguese(Br)). Have only its dictionary active and downloaded (their counter is 1).

2. Close Telegram (not its windows, it has to end execution).

3.  Open Telegram again using an empty test folder. In linux, you can use the command:

`mkdir /dev/shm/test; telegram -workdir /dev/shm/test`

3.1. Login to your account (menu > settings > devices > qr code).

3.2. Change theme (this is probably unrelated, but the default theme hurts).

3.3. Change language to my language (Portuguese - Brasil).

4. 'menu > settings > advanced:  "use corrector" will be enabled; "automatically download dict" also; it says 2 dictionaries are downloaded.

5. Go to "manage dictionaries".

5.1. Disable "English" corrector.

5.2. Enable "English (United Kingdom)". Notice that it shows that a dictionary will be downloaded (a "0%/something", but nothing happens. It gets enabled but, below the language name, it still shows "Download 170,3 KB".

5.3. Check that for my language (pt-br), the corrector is enabled, and below its name is written "Dictionary activated".

5.4. Scroll down and click "Save" button, to save our changes.

6. Close advanced settings windows. Open "saved messages" chat and typed 2 sentences, in the 2 languages we chose to have enabled, as i had before: portuguese (br) and english (uk):

==
Olá, eu gosto muito de conversar no Telegram.

Hello, i like to talk in Telegram very much.

==

7. The corrector is wrong, but strange: no word is marked in the first sentence, which is correct; it marked almost all words wrong in the second sentence. It did not mark "i", "to" and "in" (and "Telegram", but this one is expected). The words "to" and "in" do not exist in portuguese. A lonely letter or symbol should be correct in any language, i guess. So, my way to write the second sentence seems to be correct.

8. I have a different result with my settings. See: https://t.me/TelegramDesktopTalk/76027 . I can give a copy of my settings in use, if anyone helps me removing unnecessary and private information from it, before copying.

9. I was using the corrector for En(UK) only normally since several versions of Telegram Desktop. Id est, it marks a words as wrong, if it exists only in En(USA) and/or other countries' variations. I **noticed** the change in behaviour in version 3.2.4, but i cannot say it is where it began.

### Expected behaviour

Marks no word as wrong.

### Actual behaviour

Marks a strange set of words as wrong (see example in the "steps to reproduce").

### Operating system

Debian

### Version of Telegram Desktop

3.2.4

### Installation source

Static binary from official website

### Logs

```shell
Is any log useful? How and which should i put here?
```

**Comment by sian80** [comment]
Having this issue to, Telegram trying to make me spell everything in 'Mercan. Can't enable UK English dictionary. In the app it's not even an option.
