### ISSUE TITLE
tg stuck when using ctrl+v or right-click in tg on gnome 40.4 wayland

### ISSUE THREAD

**Issue by AndyFreedom** [telegramdesktop/tdesktop#17343]
### Steps to reproduce

tg stuck when using ctrl+v or right-click in tg on gnome 40.4 wayland

### Expected behaviour

it shouldn't stuck

### Actual behaviour

it stuck

### Operating system

ubuntu 21.10 wayland

### Version of Telegram Desktop

3.2.2

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Can you explain in a more comprehensive way or upload a screencast?

**Comment by AndyFreedom** [comment]
tg stop responding when pressing ctrl+v or right-clicking on tg

**Comment by AndyFreedom** [comment]
it's back to normal after I restart my ubuntu , looks like a occasional situation

**Comment by ilya-fedin** [comment]
> tg stop responding when pressing ctrl+v or right-clicking on tg

This is not comprehensive enough, upload a screencast of how to reproduce the issue
