### ISSUE TITLE
[Question] Is the Linux version being updated?

### ISSUE THREAD

**Issue by nre-ableton** [telegramdesktop/tdesktop#17351]
Telegram keeps nagging me, "Please update your app to the latest version. The version you are using is out of date and will stop working soon." I'm using version 2.6.1, which is the latest one offered from my distro's app store (in this case, Pop!_OS' "Pop Shop"), as well as the download link on https://desktop.telegram.org.

Is the Linux version not being maintained anymore?

**Comment by RememberTheAir** [comment]
Just tried to download Telegram from Pop!OS from https://desktop.telegram.org and it downloads version 3.2.5 🤔 

By the way, Pop Shop should let you install the flatpak version, which as far as I know it's officially maintained and can be updated through Pop Shop. Flatpak is not the default installation method though, you might check it out

**Comment by Aokromes** [comment]
maybe he is running some ancient popos

**Comment by roelandjansen** [comment]
I got the same. Ihe latest version is not 3.x  while the file gives you a different idea. It's reported as 2.4.7 and yes, nags the whole time.

-rw-r--r-- 1 roeland users  40143108 Dec  6 13:27 tsetup.3.2.4.tar.xz

(and no, no flatpack or snaps.)

**Comment by roelandjansen** [comment]
https://telegram.org/dl/desktop/linux   is the link from above.

**Comment by nre-ableton** [comment]
I am in fact running the latest version of Pop!_OS, but indeed, I was using the deb package and not flatpack. I guess the deb version isn't being updated anymore? If so, that's a shame, I much prefer native packages to flatpack/snaps. Anyways, to get rid of the nag (and avoid being cut off in the future), I'll switch to the flatpack version.

**Comment by ilya-fedin** [comment]
deb package is provided by Debian maintainers and maintained by them (third-parties). The only official versions are at desktop.telegram.org.

**Comment by roelandjansen** [comment]
@ilya-fedin

I downloaded an official version on that link   ("get linux for x*86_64)

Downloads: -rw-r--r-- 1 roeland users 40143108 Dec  6 17:29 tsetup.3.2.4.tar.xz

unpacked it. executed it:

roeland@snowpa:~/Telegram> ls -l 
total 114808
-rwxr-xr-x 1 roeland users 112168120 Nov 13 12:36 Telegram
-rwxr-xr-x 1 roeland users   5391312 Nov 13 12:33 Updater

and ./Telegram directly starts nagging it's old version  (v2.4.7)

same for ./Updater (v2.4.7 pos up)

Telegram Desktop was updated to version 2.4.7

— Bug fixes and other minor improvements

Full version history is available here:
https://desktop.telegram.org/changelog

so am I missing something here or....

**Comment by ilya-fedin** [comment]
Check actual version in the sidebar

**Comment by nre-ableton** [comment]
I also got version 2.6.1 from the binary version of Telegram (in the sidebar) when running `./Telegram`.

**Comment by Aokromes** [comment]
find / -name Telegram

**Comment by ilya-fedin** [comment]
Apparently you haven't quit from the system version, guys. When you close the window, app doesn't quit, it runs in the background with a tray icon. If Telegram is already running, clicking on the binary won't launch another instance, window of the previous instance will be opened instead.

**Comment by roelandjansen** [comment]
ok. time to hit myself. that indeed is the issue. I feel stupid. Thanks!
