### ISSUE TITLE
media fails to open unless you change your desktop

### ISSUE THREAD

**Issue by aliafshany** [telegramdesktop/tdesktop#17355]
### Steps to reproduce

just click on any media you want ( images + video )

### Expected behaviour

not showing the media for the first time unless you change your desktop and return

### Actual behaviour

not showing the media for the first time unless you change your desktop and return

### Operating system

mac os monterey 12.0.1

### Version of Telegram Desktop

TG Desktop Version 3.2.8 beta

### Installation source

Static binary from official website

**Comment by aliafshany** [comment]
here is a video demo of the issue

https://user-images.githubusercontent.com/40741745/145016378-4e3b552d-9f35-43bf-a73d-9574f8640aca.mp4

**Comment by john-preston** [comment]
I can't reproduce :(

**Comment by aliafshany** [comment]
your comment rings a bell
let me reinstall my tg desktop to check it

**Comment by aliafshany** [comment]
i reinstalled it and i get the same result

**Comment by aliafshany** [comment]
just installed the 3.2.5 normal release and again i faced the issue.
i am suspecting that it is Monterey that causes this thing not TG itself
idk btw

**Comment by XomaDev** [comment]
I had the same issue on Windows 10 yesterday, none of the media would show up.

**Comment by aliafshany** [comment]
i have 3.3 beta and i think it has been fixed at his version.
but i gotta test more

**Comment by aliafshany** [comment]
i confirm that there is no problem in beta 3.3 
so my problem solved.
