### ISSUE TITLE
Open "Recents" in Finder while attaching file cause crash on MacOS

### ISSUE THREAD

**Issue by Agrailag** [telegramdesktop/tdesktop#17350]
### Steps to reproduce

1. Open any chat and click on "add attachment" button
2. Select "Recents" in Finder

### Expected behaviour

Open list of recent files

### Actual behaviour

App crash

### Operating system

MacOS 11.6 (20G165)

### Version of Telegram Desktop

3.2.5

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Thanks for your report! It should be fixed in 3.2.8 beta version, you can try it out from Settings -> Advanced -> Install beta versions.
