### ISSUE TITLE
Re-enable Desktop App Without Needing Mobile 

### ISSUE THREAD

**Issue by SCLDGit** [telegramdesktop/tdesktop#17353]
### Is your feature request related to a problem?

You shouldn't need a mobile app to run a desktop app.

### Describe the solution you'd like

I should be able to create an account and run the desktop app without any necessity for a smartphone.

### Describe alternatives you've considered

None

### Additional context

In my organization, the Telegram mobile app is disallowed. Because of my position, this rule governs my personal devices as well. My desktop, however, is free from such limitations, but because of the mobile app requirement, I'm entirely unable to use Telegram to track certain code projects that I need to be able to follow. Who thought creating a reliance on a smartphone app was a good decision for the desktop app?

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
