### ISSUE TITLE
Kubuntu 20.04 Telegram desktop 3.2.5 Flatpack and 3.2.2 Snap

### ISSUE THREAD

**Issue by antenac** [telegramdesktop/tdesktop#17352]
### Steps to reproduce

1. I choose option Download file
2. Save on network folder
. 

### Expected behaviour

Save files on network folders.

### Actual behaviour

3. A message says "Only local folder"
4. On Ubuntu-KDE Software manager settings there is no option to Set up network access to Telegram app.
5.  Telegram 2.1.7 Desktop version works well on Ubuntu-KDE
6. I tried mounting net folder, and message doesn't appears but it doesn't save too

### Operating system

GNU/Linux Kubuntu 20.04

### Version of Telegram Desktop

2.3.5 Fltpack and 3.2.2 Snap

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
I have no network mountpoints, maybe you can describe in more details or add screenshots?
