### ISSUE TITLE
No Audio-Telegram Desktop 

### ISSUE THREAD

**Issue by newsaba** [telegramdesktop/tdesktop#17354]
### Steps to reproduce

Telegram Desktop won't play the sound of music or audio and video massages also have no sound. Re-installing the program did not help either.

### Expected behaviour

should be able to play audio but its not happening 

### Actual behaviour

does not play any kind of sound or audio

### Operating system

Nitro 5

### Version of Telegram Desktop

Version 3.2.5 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> Nitro 5

What OS is this?

**Comment by newsaba** [comment]
> Windows 10 version 21h2

**Comment by ilya-fedin** [comment]
Provide log.txt

**Comment by Aokromes** [comment]
cannot reproduce on windows 11 on 2 diferent computers and windows 10 on 2 diferent computers.

**Comment by newsaba** [comment]
I only have the app on my phone and on my laptop, nowhere else.

**Comment by ilya-fedin** [comment]
You need to provide log.txt anyway

**Comment by DjSteveOhh** [comment]
i solved my sound troubles by uninstalling telegram and download a fresh copy of 3.3 from the website.
