### ISSUE TITLE
[feature request] - disable URL parsing

### ISSUE THREAD

**Issue by draeath** [telegramdesktop/tdesktop#1736]
When sharing technical outputs (eg logfiles, directory listings, etc) occasionally telegram will incorrectly parse a line as a link. This results in the text being shortened and replaced with an (invalid) link.

It would be wonderful if there was a means to (temporarily) disable URL parsing, forcing a message to be sent and viewed as plain text only.

A workaround involved sending a text file instead, which is not ideal.

Example text string that is *not* a URL, but is detected as such:

    ./bugs.example.com/library/ezc/Graph/src/options/renderer_2d.php

This being the product of some shell script output on a filesystem that includes a directory with periods in the name.

**Comment by telegramdesktop** [comment]
@draeath You can use wrapping in single ticks or triple ticks for that. Or the links are parsed in monospace font blocks as well?

**Comment by draeath** [comment]
Would I wrap the whole block of text to be sent in them, similar to markup?

Here's what it looks like on my platform (Windows desktop client).

![output](https://cloud.githubusercontent.com/assets/987449/13552862/62d0a69c-e341-11e5-9c63-3c676c247ab3.png)

**Comment by telegramdesktop** [comment]
@draeath Yes, all the text in three ticks, like markdown:
\`\`\` your multi line text \`\`\`
