### ISSUE TITLE
Запрос на функцию ограничений в чатах

### ISSUE THREAD

**Issue by machinsoft** [telegramdesktop/tdesktop#17368]
### Ваш запрос функции связан с проблемой?

Да есть небольшая проблема со спамом

### Опишите желаемое решение

Нужно в админки чата добавить подразделы где отправка медиафайлов
1 отправка звука
2 отправка картинок
3 отправка видео
4 отправка голосового сообщение 
Что бы каждую функцию можно было отключить по отдельности. 

### Опишите альтернативы, которые вы рассмотрели

Управление группой - > Разрешение - > Отправка медиафайлов, галочка сейчас отвечает за все.
Люди спамят картинками, бот удаляет их, люди кидают видео, бот удаляет их.
Отключить отправку медиафайлов нельзя, нужна отправка музыки и голосового сообщение в чате.

**Comment by GUOguocai88** [comment]
嗯，不好意思兄弟我忘了可能网络不好。


---Original---
From: ***@***.***&gt;
Date: Thu, Dec 9, 2021 12:31 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [telegramdesktop/tdesktop] Запрос на функцию ограничений в чатах (Issue #17368)




 
Is your feature request related to a problem?
 
Да есть небольшая проблема со спамом
 
Describe the solution you'd like
 
Нужно в админки чата добавить подразделы где отправка медиафайлов
 1 отправка звука
 2 отправка картинок
 3 отправка видео
 4 отправка голосового сообщение
 Что бы каждую функцию можно было отключить по отдельности.
 
Describe alternatives you've considered
 
Описал выше, все.
 
Additional context
 
Управление группой - &gt; Разрешение - &gt; Отправка медиафайлов галочка, сейчас отвечает за все.
 Люди спамят картинками, бот удаляет их, люди кидают видео, бот удаляет их.
 Отключить отправку медиафайлов нельзя, нужна отправка музыки и голосового сообщение в чате.
 
&mdash;

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by GUOguocai88** [comment]
我要发的是因为我现在是显示器装了两个，然后我有一台连接不上。


---Original---
From: ***@***.***&gt;
Date: Thu, Dec 9, 2021 12:31 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [telegramdesktop/tdesktop] Запрос на функцию ограничений в чатах (Issue #17368)




 
Is your feature request related to a problem?
 
Да есть небольшая проблема со спамом
 
Describe the solution you'd like
 
Нужно в админки чата добавить подразделы где отправка медиафайлов
 1 отправка звука
 2 отправка картинок
 3 отправка видео
 4 отправка голосового сообщение
 Что бы каждую функцию можно было отключить по отдельности.
 
Describe alternatives you've considered
 
Описал выше, все.
 
Additional context
 
Управление группой - &gt; Разрешение - &gt; Отправка медиафайлов галочка, сейчас отвечает за все.
 Люди спамят картинками, бот удаляет их, люди кидают видео, бот удаляет их.
 Отключить отправку медиафайлов нельзя, нужна отправка музыки и голосового сообщение в чате.
 
&mdash;
