### ISSUE TITLE
[Feature Request] Ignore notifications for duplicate forwarded messages

### ISSUE THREAD

**Issue by enervated** [telegramdesktop/tdesktop#17366]
### Is your feature request related to a problem?

If you have joined more than a few channels, it can be very common for a message posted by one channel to be forwarded to other channels.

When a given message is forwarded many times by separate channels you are a member of, it can be quite annoying: You get a notification in each separate channel, and have to view the same message over and over to dismiss them each separately.

### Describe the solution you'd like

The client should only notify for the first occurrence of any given message.

If the user is a member of the originating channel, then the notification should occur for the message in that channel only, even if other channels the user is subscribed to later forward it.

If the user is not a member of the originating channel, but multiple subscribed channels forward the same message, the client should only notify for the forwarding that occurred _first_.

### Describe alternatives you've considered

N/A

**Comment by enervated** [comment]
Is this feature suggestion _really_ so obscure or unworkable that it deserves not a reply? How could I _possibly_ be the only one who has the complaint outlined above?

**Comment by enervated** [comment]
Nothing. Silence. Too busy adding shit emojis and the ability to upvote them?

I'm asking for a CLIENT-LEVEL thing. Simply don't display the same post multiple times. This is so utterly insane--SO FANTASTICALLY FRINGE--that I can't get a whit of support for it?

**Comment by Aokromes** [comment]
> Nothing. Silence. Too busy adding shit emojis and the ability to upvote them?

those shit emojis and upvote them is mandated by boss.

**Comment by 23rd** [comment]
The feature you are asking for, should be rolled out to all clients on every platform for consistency. Therefore, your request is more relevant to the [bugs.telegram.org](https://bugs.telegram.org/?type=suggestions) tracker.

If you want this feature only on desktop, then you better ask to implement it in any fork.

**Comment by enervated** [comment]
Done. Thank you.

https://bugs.telegram.org/c/14783

Please pardon my bad mood earlier.
