### ISSUE TITLE
Отключить в чатах возможность отправлять сообщение от канала

### ISSUE THREAD

**Issue by machinsoft** [telegramdesktop/tdesktop#17369]
### Ваш запрос функции связан с проблемой?

Это новая функция вызвала постоянный спам в чатах от имени канала, более того бот не всегда перехватывает ссылки сообщений от канала.
Люди создают левый канал и там пишут свою рекламу, дальше пишут от имени канала.
Но проблема не в этом, а то что бот не понимает спам и не удаляет ссылки от имени канала.

### Опишите желаемое решение

Возможность в админки чата, отключить возможность пользователю писать сообщение от своего канала

### Опишите альтернативы, которые вы рассмотрели

Улучшить ботов удалять спам ссылки сообщения от имени канала, но они могут спамить другим способом, например: нажми на меня или что то в этом роде.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

p.s. this bugtracker and the linked one is english only.

**Comment by machinsoft** [comment]
@Aokromes  можете переотправить за меня, я там не зарегистрирован.
