### ISSUE TITLE
Telegram new update problem: spamming inside groups as channel

### ISSUE THREAD

**Issue by BaseMax** [telegramdesktop/tdesktop#17365]
Hi there,

We have biggest group/community of developer/programmers inside Telegram.

And after latest update of Telegram, everyone able to spam and send many messages while we are not able to ban/block them.

Have you thought about it? Is there a solution?
It look like a bug inside telegram platform, since its needed for groups to able to ban/limit the users. (It's about when users send message as channel and not personal account)

Best,
M.

**Comment by Aokromes** [comment]
afaik if someone spams with one channel and that channel is banned, every other channel the owner owns will be banned as well.

**Comment by Mikaela** [comment]
How can this feature be disabled?
