### ISSUE TITLE
Bug: No reply with double click at the side of the bubble on groups with protected content

### ISSUE THREAD

**Issue by DMJWorld** [telegramdesktop/tdesktop#17378]
### Steps to reproduce

In groups with protected content actived is not possible to reply to message with the double click outside the bubble.

### Expected behaviour

Reply on message

### Actual behaviour

disabled

### Operating system

Windows and Linux

### Version of Telegram Desktop

v. 3.3

### Installation source

Static binary from official website

**Comment by mihailmariusiondev** [comment]
Please fix this, it's so annoying. Switching between groups with privacy mode enabled and disabled is a pain in the ass. You have to manually click "Reply" button or click inside the message bubble to reply.
