### ISSUE TITLE
Missing "Beginning" button in chat search's search by date box

### ISSUE THREAD

**Issue by Younes-L** [telegramdesktop/tdesktop#17374]
### Steps to reproduce

1. open any chat
2. ctrl + F
3. tap the calendar button

### Expected behaviour

the usual Beginning button appears left of the Close button.

### Actual behaviour

No Beginning button appears. 
Only in 1-1 chats, a "Select" button takes its place, but in all other chats (groups & channels, where the beginning button is even more useful), this place is now empty.

### Operating system

all OS, all versions, all DEs

### Version of Telegram Desktop

3.3.0 (latest)

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/17372

**Comment by Younes-L** [comment]
everytime (;_;)
one day i'll find something new to bug about, but that day is not today...
