### ISSUE TITLE
Build instructions for Windows 64-bit  execute tdesktop\Telegram\build\prepare\win.bat  get KeyError: 'Platform'

### ISSUE THREAD

**Issue by 16889920** [telegramdesktop/tdesktop#17373]
### Steps to reproduce

Prepare folder  ok
Install third party software  ok
python -m pip install pywin32 ok
git clone --recursive https://github.com/telegramdesktop/tdesktop.git  ok
tdesktop\Telegram\build\prepare\win.bat error

### Expected behaviour

Build sucess

### Actual behaviour

Build failed

### Operating system

windows server 2016 64bit

### Version of Telegram Desktop

v3.3.0

### Installation source

Static binary from official website

### Logs

```shell
D:\TBuild>tdesktop\Telegram\build\prepare\win.bat
Traceback (most recent call last):
  File "D:\TBuild\tdesktop\Telegram\build\prepare\prepare.py", line 17, in <module>
    win32 = win and (os.environ['Platform'] == 'x86')
  File "D:\TBuild\ThirdParty\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'Platform'
FAILED
```

**Comment by john-preston** [comment]
I guess you're launching it not from the correct command prompt.

**Comment by GUOguocai88** [comment]
对的


---Original---
From: &quot;John ***@***.***&gt;
Date: Fri, Dec 10, 2021 20:13 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [telegramdesktop/tdesktop] Build instructions for Windows 64-bit execute tdesktop\Telegram\build\prepare\win.bat  get KeyError: 'Platform'(Issue #17373)




 
I guess you're launching it not from the correct command prompt.
 
&mdash;

**Comment by 16889920** [comment]
> 对的
> […](#)
> ---Original--- From: &quot;John ***@***.***&gt; Date: Fri, Dec 10, 2021 20:13 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: Re: [telegramdesktop/tdesktop] Build instructions for Windows 64-bit execute tdesktop\Telegram\build\prepare\win.bat get KeyError: 'Platform'(Issue #17373) I guess you're launching it not from the correct command prompt. &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

能详细点吗？

**Comment by 16889920** [comment]
> I guess you're launching it not from the correct command prompt.



> I guess you're launching it not from the correct command prompt.

Can you give me more information

**Comment by john-preston** [comment]
https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win.md#prepare-folder

"All commands (if not stated otherwise) will be launched from x86 Native Tools Command Prompt for VS 2022.bat (should be in Start Menu > Visual Studio 2022 menu folder). Pay attention not to use any other Command Prompt."

https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md#prepare-folder

"All commands (if not stated otherwise) will be launched from x64 Native Tools Command Prompt for VS 2022.bat (should be in Start Menu > Visual Studio 2022 menu folder). Pay attention not to use any other Command Prompt."

**Comment by GUOguocai88** [comment]
因為我的電腦鎖住了，所以沒有發英語。


---Original---
From: ***@***.***&gt;
Date: Fri, Dec 10, 2021 20:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [telegramdesktop/tdesktop] Build instructions for Windows 64-bit  execute tdesktop\Telegram\build\prepare\win.bat  get KeyError: 'Platform' (Issue #17373)




  
I guess you're launching it not from the correct command prompt.
   
I guess you're launching it not from the correct command prompt.
  
Can you give me more information

**Comment by 16889920** [comment]
> 因為我的電腦鎖住了，所以沒有發英語。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Dec 10, 2021 20:27 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [telegramdesktop/tdesktop] Build instructions for Windows 64-bit execute tdesktop\Telegram\build\prepare\win.bat get KeyError: 'Platform' (Issue #17373) I guess you're launching it not from the correct command prompt. I guess you're launching it not from the correct command prompt. Can you give me more information — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

pls help me

**Comment by 16889920** [comment]
> https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win.md#prepare-folder
> 
> "All commands (if not stated otherwise) will be launched from x86 Native Tools Command Prompt for VS 2022.bat (should be in Start Menu > Visual Studio 2022 menu folder). Pay attention not to use any other Command Prompt."
> 
> https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md#prepare-folder
> 
> "All commands (if not stated otherwise) will be launched from x64 Native Tools Command Prompt for VS 2022.bat (should be in Start Menu > Visual Studio 2022 menu folder). Pay attention not to use any other Command Prompt."
![1639154023(1)](https://user-images.githubusercontent.com/19298301/145608643-6a0c5b52-c228-4d23-800c-b73ce0ab35da.jpg)

**Comment by 16889920** [comment]
> https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win.md#prepare-folder
> 
> "All commands (if not stated otherwise) will be launched from x86 Native Tools Command Prompt for VS 2022.bat (should be in Start Menu > Visual Studio 2022 menu folder). Pay attention not to use any other Command Prompt."
> 
> https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md#prepare-folder
> 
> "All commands (if not stated otherwise) will be launched from x64 Native Tools Command Prompt for VS 2022.bat (should be in Start Menu > Visual Studio 2022 menu folder). Pay attention not to use any other Command Prompt."



> pls help me



> https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win.md#prepare-folder
> 
> "All commands (if not stated otherwise) will be launched from x86 Native Tools Command Prompt for VS 2022.bat (should be in Start Menu > Visual Studio 2022 menu folder). Pay attention not to use any other Command Prompt."
> 
> https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md#prepare-folder
> 
> "All commands (if not stated otherwise) will be launched from x64 Native Tools Command Prompt for VS 2022.bat (should be in Start Menu > Visual Studio 2022 menu folder). Pay attention not to use any other Command Prompt."

pls help me

**Comment by 16889920** [comment]
> https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win.md#prepare-folder
> 
> "All commands (if not stated otherwise) will be launched from x86 Native Tools Command Prompt for VS 2022.bat (should be in Start Menu > Visual Studio 2022 menu folder). Pay attention not to use any other Command Prompt."
> 
> https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md#prepare-folder
> 
> "All commands (if not stated otherwise) will be launched from x64 Native Tools Command Prompt for VS 2022.bat (should be in Start Menu > Visual Studio 2022 menu folder). Pay attention not to use any other Command Prompt."

pls help me, thanks!

**Comment by john-preston** [comment]
Everything is written in the build docs, sorry.
