### ISSUE TITLE
[Feature Request] Get the "beginning" button back to search

### ISSUE THREAD

**Issue by Nabeel20** [telegramdesktop/tdesktop#17372]
### Is your feature request related to a problem?

yes

### Describe the solution you'd like

In the previous versions, there was a button to take you back to the beginning of channel messages. Now you have to scroll the whole calendar to get the first message. 

### Describe alternatives you've considered

A new way to get the first message back in time.

**Comment by john-preston** [comment]
@Nabeel20 Press and hold on the previous month arrow.

**Comment by VetaLioSTV** [comment]
@john-preston yes, but in reality its absolutely other feature which scrolls you back on initial month, but not initial date, plus you need to make redundant actions which costs ~8 seconds of your life,lol:
1) Press and hold 4 sec
2) You're now on initial month, find initial date of discussion
3) Manually choose first date

So just compare previous scenario and current with lack of usability? It was super awesome functionality, please revert it back or make combobox with two list item selection:
1) Go to start
2) Choose dates for removing chat history

I think this is best solution to keep previous functionality with adding new stuff.

UPD:
I just checked, after removing chat history (e.g. for one specific day, lets 5 december), for some reason it still remains accessible(can be chosen/clicked) in calendar.
