### ISSUE TITLE
[Feature Request] send message without sound by default

### ISSUE THREAD

**Issue by TohidHeshmati** [telegramdesktop/tdesktop#17389]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

At the moment Telegram offers this great possibility to send messages without sound. but If the user wants to do that couple of times s/he has to do that more than one time which is annoying. It would be greate to have an option to send all private messages without sound or select a user to send messages to him/her without sound permanently.

### Describe alternatives you've considered

setting for all messages to be sent without sound or selecting specific user

### Additional context

example: I don't want to bother my friend who lives in a different time zone and I forget to send him messages without sound so it might wake him up in the middle of the night.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16363
