### ISSUE TITLE
[Revert Feature] 

### ISSUE THREAD

**Issue by VetaLioSTV** [telegramdesktop/tdesktop#17385]
### Is your feature request related to a problem?

Actually its not a problem, but lack of usability which are not "user friendly"

### Describe the solution you'd like

Please revert feature with calendar control,  button "Go to start"(in chat\channel) are now missing which brakes usability..

### Describe alternatives you've considered

So for now (latest 3.3 version) you should manually scroll back to first available date when chat has been started, which is annoying.

### Additional context

Why this button has been removed? It had a great functionality(usability) which was used frequently..

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/17372#issuecomment-989876369

**Comment by VetaLioSTV** [comment]
@Aokromes can you add combobox where end-user can choose through selection :
1) "go to start"
2) "choose dates"(for removing chat)

This "press and hold back arrow" is super strange.. Everytime waste 4 seconds of waiting sounds ridiculous plus annoying.

Any thoughts? :\
