### ISSUE TITLE
Please Implement End-To-End Encryption By Default[Feature Request] 

### ISSUE THREAD

**Issue by Nihal247** [telegramdesktop/tdesktop#17384]
### Is your feature request related to a problem?

Using "end-to-end encryption" by default means, messages can’t be undecrypted by anyone other than the intended receiver, and if it's not, a person with access to the server, can know the message, and not using end-to-end encryption (by default) has various other disadvantages.

### Describe the solution you'd like

We all know using by end-to-end encryption, the security of the messages and the privacy of users receive a significant huge boost, and I know "Secret Chats" enable us to get this feature, but this requires a little extra work, and probably most people message directly without creating a "Secret Chat". I believe Telegram can also implement this, if other messengers are able to adopt it by default.

### Describe alternatives you've considered

Creating a "Secret Chat".

**Comment by theyashl** [comment]
Telegram is cloud based application where your normal messages are stored un encrypted! When you enable End-to-End encrypted secret chats, those messages do not get stored on telegram server.
Even if we stored encrypted texts over cloud anyone with access to your device or private key can retrieve those messages! Which quetions end-to-end encryption. 

For secret chat, everytime you use it, you have your own public key and private key. And everytime you create new secret conversation, different keys gets generated. Which makes connection secure as no other person have those keys. And if you can retrieve encrypted texts from cloud with key then there is no difference between normal texts and encrypted texts!

**Comment by Nihal247** [comment]
Thanks @theyashl for your help 😊 After doing a bit of research, I realized that some of the features that Telegram provides such as groups with up to 200,000 members and or channels with no limit on max size, aren't possible with e2ee, and "Secret Chats" exist anyways.

Closing this!
