### ISSUE TITLE
linux: missing in xdg menu fix requires just rename a file

### ISSUE THREAD

**Issue by digitalfredy** [telegramdesktop/tdesktop#17381]
### Steps to reproduce

1. Install any Sway + Mako menu or any other light window manager with a menu in debian 11
2. Launch the menu and search for Telegram (missing)
3. Rename xdg `telegramdesktop.desktop` file as `telegram-desktop.desktop` to fix the issue ([source](https://bugs.launchpad.net/ubuntu/+source/telegram-desktop/+bug/1715185/comments/3))
4. Launch the menu and search for Telegram, now is there!

### Expected behaviour

By default any menu that follow the freedesktop xdg supposed to show Telegram in his menu

### Actual behaviour

Some menus show telegram (gnome, kde) others don't

### Operating system

Linux Debian 11, Sway Window Manager with Mako menu

### Version of Telegram Desktop

3.1.1

### Installation source

Other (unofficial) source

### Logs

```shell
Related bug shows that Linux users at least Ubuntu and Debian reported consistently this issue since 2017:

https://bugs.launchpad.net/ubuntu/+source/telegram-desktop/+bug/1715185

As I can remember I got also the issue while using the static binary from Telegram (official)
```

**Comment by ilya-fedin** [comment]
It should be shown doesn't matter what's the name is, it's apparently a bug in Mako

**Comment by ilya-fedin** [comment]
Looking at the bug report you mentioned, the problem is not in naming, but in a redundant file in your $HOME.

**Comment by digitalfredy** [comment]
I know you guys have to do your best to keep the backlog clean but closing this way?

1. I want to say I mixed up things and you do not even noticed, the menu name is wofi (is not mako)
2. Users have issues even before Wofi where writen then not a but in the window manager
3. I have no menu or `.desktop` files in my $HOME and it supposed to work using the main system files then not a user issue

I feel  do not care about the minority that does not uses the main Linux desktops then, if I do the MR myself you will consider it or you will just close it same way you did with this issue? (I'm asking because I do not want to waste my time).

**Comment by ilya-fedin** [comment]
The XDG spec doesn't have any restriction regarding the desktop file name, if your menu application does, it's a bug in menu application and should be reported to it, not to tdesktop.
