### ISSUE TITLE
`Contact joined Telegram` notification setting is ignored

### ISSUE THREAD

**Issue by Leksat** [telegramdesktop/tdesktop#17387]
### Steps to reproduce

1. Install Telegram Lite (desktop, Mac OS)
2. Turn off `Contact joined Telegram` setting
3. Wait for your contact to join

### Expected behaviour

No notification badge is seen on the Telegram dock icon

### Actual behaviour

The badge is there

### Operating system

macOS 11.6.1

### Version of Telegram Desktop

Telegram Lite 3.2

### Installation source

Mac App Store

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
