### ISSUE TITLE
[Feature Request] Japanese characters hard to read in Telegram desktop

### ISSUE THREAD

**Issue by Adam-Kay** [telegramdesktop/tdesktop#17399]
### Is your feature request related to a problem?

Japanese text, especially complex kanji, can be quite difficult to read when typed in Telegram messages, or received. The font doesn't appear to have the right smoothing on it and it can become a mess of pixels. This problem extends also to Chinese characters (hanzi)
<details>
    <summary>Example:</summary>

   
![Telegram_gUn6An0EV4](https://user-images.githubusercontent.com/10010491/145998804-3437c6c0-755a-40d7-966b-72d07f4f5b40.png)
 </details>

### Describe the solution you'd like

Perhaps a different font or different smoothing on the font / character rendering could prevent this from happening to the characters?

### Describe alternatives you've considered

I have tried installing the proofing tools for Windows for Japanese to see if it fixed it, which did nothing.

I've also tried turning up the UI scale in the settings, which helps only marginally
<details>
    <summary>Example with UI scale up:</summary>

   
![Telegram_zPwjsDkaeY](https://user-images.githubusercontent.com/10010491/145999516-56517cdf-f9f1-4661-8d6a-7d9c29a376f1.png)

 </details>

**Comment by ilya-fedin** [comment]
Well, the characters on screenshot look ok to me

**Comment by Adam-Kay** [comment]
Here might be a better example:

![Telegram_UpJcHiYQEH](https://user-images.githubusercontent.com/10010491/146001284-6e9aa3b7-fcf9-4ce6-9e0f-37080efb61dd.png)

<details>
<summary> Sample text used: </summary>
実用姓氏辞典
菅原義三

効む要社マラナ相付ヤ今草いぞわ側無稿トエシ帰社認にラめ海短コカク刊松ナ春壮ふた強同ほぐぽ障15羽競整みゅ。
</details>

For some of the words you have to pixel hunt to read them properly. I get that they're more complex than latin characters but I figure there must be a solution of some kind.

**Comment by ilya-fedin** [comment]
Well, it still looks ok to me. Apparently, I won't see it since I can't read these characters anyway. You filed your issue like you think everyone knows how it should look like, only samples of how it looks like and no samples of  how it should look like.
