### ISSUE TITLE
MediaView does not show

### ISSUE THREAD

**Issue by RomanKornev** [telegramdesktop/tdesktop#17398]
### Steps to reproduce

1. Click on an image in chat
2. MediaView does not show

### Expected behaviour

MediaView does show

### Actual behaviour

It feels like it opens up off-screen, but I can't see or move it.
A white line appears at the very bottom when I click on an image (in fullscreen mode) and disappears when I click somewhere.
Mouse loses all interactivity (no hovers, no cursor changes) until I click somewhere or hit Esc (see gif).
https://user-images.githubusercontent.com/5807561/145997579-0d969765-a3c5-4710-9063-c999b6de0fed.mp4
I can see Media Viewer in Alt-Tab menu, but switching to it does nothing, and its preview is blank.

I've hooked up another monitor recently but I already disabled it, so there's only 1 active display.

### Operating system

Windows 10 x64

### Version of Telegram Desktop

3.3 x64

### Installation source

Static binary from official website

**Comment by RomanKornev** [comment]
Found a temporary workaround: Alt+F4 after clicking on an image. Then click the image again and it opens correctly. 
But now it shows the previously opened image for about a second before showing the correct one. This "ghost effect" seems to be connected to the image size. Small images don't have this issue.

**Comment by suxscribe** [comment]
I got the same here. I use two monitors with "Extend" setting. Telegram is on the first monitor.

### Steps to reproduce: 
1. Switch to "Show only on 2" in Windows display settings 
2. then switch back to "Extend"
3. Click on a media in Telegram chat -> Media viewer opens on screen 2. If screen 2 is off, Media viewer opens offscreen. It stays offscreen until I restart Telegram.

**Comment by john-preston** [comment]
@humANdroid95 Don't switch there 😅 something is not compatible in angle on d3d11over12 and the way qt uses opengl.

**Comment by d-Rickyy-b** [comment]
I'm also having issues with the media viewer not showing.

Task switcher (Alt+Tab):
![grafik](https://user-images.githubusercontent.com/5798157/167276597-198b7eba-f5d3-488c-a9da-d814a5a2d44a.png)

Hovering over windows task bar:
![grafik](https://user-images.githubusercontent.com/5798157/167276572-d4b5916d-8648-41b5-abd7-4a3495bc07f6.png)

I got Telegram 3.7.4 beta - ANGLE graphics backend is set to Auto.
Restarting Telegram fixes the issue.

**Comment by ilya-fedin** [comment]
#17206
