### ISSUE TITLE
[Question] Dev Environnment

### ISSUE THREAD

**Issue by tilibougnia** [telegramdesktop/tdesktop#17395]
Hi All,

I would like to configure a dev environnment to make some test with the source code. I work on linux and I have install QT Creator, but it's seems this is not a good tools to use the source code. What did you use on linux ?

Kind regards

**Comment by john-preston** [comment]
@tilibougnia https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md

**Comment by tilibougnia** [comment]
Hi Johm, Thanks for your answer, I found this, but it's for build. I wand to prepare a dev environnement to work on it. I know that for mac Os you use Xcode, Windows VS2022, but on linux I suppose it's Qt, but it's don't seem to work. So what's tools you use for it ?

Kind regard

**Comment by john-preston** [comment]
@tilibougnia I use just the tools for the build. And VS Code to make changes to the source code before building. It should be possible to setup debugging using VS Code as well, but I didn't try to do that.

**Comment by tilibougnia** [comment]
Oh ok :) thanks you very much. I will try that.

Kind regards
