### ISSUE TITLE
[Feature request] - allow to choose camera and sound device.

### ISSUE THREAD

**Issue by maratbakirov** [telegramdesktop/tdesktop#17393]
Good morning, I have 2 cameras and 3 sound cards, and i only use one of them.
is it possible to choose the device for audio/video calls? like skype does?
I cannot call anyone from my computer as it seem to use some audio device that is not really used. 
thank you!

**Comment by maratbakirov** [comment]
OS Windows 10 x64.

**Comment by ilya-fedin** [comment]
Settings -> Advanced -> Call Settings
