### ISSUE TITLE
Eye issues after switching to version 3.X

### ISSUE THREAD

**Issue by CannyDuck** [telegramdesktop/tdesktop#17394]
I am one of the members on the forum "ledstrain.org" where people meet who have eye/headache issues with new led displays and rendering.

When looking at newer displays I have aching, burning and tiring eyes with increasing tension to nausea and hypersensitivity. Headache has also increased recently. After just a few minutes of using, it often takes hours/days until the feeling of pain/adjustment has subsided completely.

I suspect the reason of the symptoms in the area of ​​temporal dithering/FRC and/or font rendering/subpixel rendering. I've done a lot of research and tests and I think I can rule out a lot of other causes like PWM.

I can used Version 2.x without issues on Windows after switching to version 3.x I get symtoms in Windows. Disable to ANGLE engine has no effect. Under Linux version 3.x is still fine.

You have an idea what changed with version 3 that I am triggered by my symptoms?

**Comment by john-preston** [comment]
@CannyDuck I don't know, nothing regarding the underlying rendering was changed in 3.x on Windows 🤔

**Comment by CannyDuck** [comment]
Maybe an update of QT or other ui related libraries?

**Comment by ilya-fedin** [comment]
Maybe it's the new default background?

**Comment by ilya-fedin** [comment]
> Maybe an update of QT or other ui related libraries?

Qt was updated in 3.2, but only on Linux and macOS

**Comment by CannyDuck** [comment]
> > Maybe an update of QT or other ui related libraries?
> 
> Qt was updated in 3.2, but only on Linux and macOS

When was the last QT update for Windows? Is the ANGLE engine used for the whole ui or just for video calls?

**Comment by CannyDuck** [comment]
> Maybe it's the new default background?

I changed it already. This is not the cause of issues.

**Comment by ilya-fedin** [comment]
> When was the last QT update for Windows?

2.4.8

**Comment by ilya-fedin** [comment]
> Is the ANGLE engine used for the whole ui or just for video calls?

video calls, media viewer

**Comment by steffomix** [comment]
LED's don't emit constant light. They blink a short bright flash in a given frequency to reduce energy consumtion and heat. So most likely there has to be something about the way they blink.

**Comment by Aokromes** [comment]
> I am one of the members on the forum "ledstrain.org" where people meet who have eye/headache issues with new led displays and rendering.
> 
> When looking at newer displays I have aching, burning and tiring eyes with increasing tension to nausea and hypersensitivity. Headache has also increased recently. After just a few minutes of using, it often takes hours/days until the feeling of pain/adjustment has subsided completely.
> 
> I suspect the reason of the symptoms in the area of ​​temporal dithering/FRC and/or font rendering/subpixel rendering. I've done a lot of research and tests and I think I can rule out a lot of other causes like PWM.
> 
> I can used Version 2.x without issues on Windows after switching to version 3.x I get symtoms in Windows. Disable to ANGLE engine has no effect. Under Linux version 3.x is still fine.
> 
> You have an idea what changed with version 3 that I am triggered by my symptoms?

can you try downloading this portable windows and test?

https://sergeistrelec.ru/winpe-10-8-sergei-strelec-english/211-winpe-10-8-sergei-strelec-x86-x64-native-x86-20211015-english-version.html

**Comment by Aokromes** [comment]
@CannyDuck
