### ISSUE TITLE
InApp PDF opener for Telegram Desktop[Feature Request] 

### ISSUE THREAD

**Issue by sid4618** [telegramdesktop/tdesktop#17403]
### Is your feature request related to a problem?

It would be great if telegram desktop/web has a feature of opening documents inapp. No need to download them and see later.
Adding this would be of great help and save downloading time as well

### Describe the solution you'd like

Inbuild PDF opener in Telegram desktop application
PDF or any other docs should open on single click

### Describe alternatives you've considered

As of now telegram works well, but would be great if there is a PDF opener, as downloading and then opening the PDF is headache.

**Comment by GregorKopka** [comment]
I disagree. Basically every system has the ability to open PDF, with the user having control over which app/program to use. 
Thus a built-in viewer would just bloat the app and, as PDF viewers had some interesting security issues in the past, needlessly increase the attack surface.

**Comment by sid4618** [comment]
Got it.
