### ISSUE TITLE
Incorrect message "seen" status.

### ISSUE THREAD

**Issue by EaredRodent** [telegramdesktop/tdesktop#17402]
### Steps to reproduce

1. Two abstract interlocutors Tanya and Danya
2. Tanya writes the message "Cat"
3. Danya DOES NOT open the dialog, clicks on the dialog and selects the "Clear history" option
4. Tanya writes the message "Dog"
5. Danya opens a dialogue

P.S. The described error is probably reproduced in groups.

### Expected behaviour

1. The message "Cat" has 1 check mark
2. The message "Dog" has 2 check marks

### Actual behaviour

1. The message "Cat" has 2 check marks
2. The message "Dog" has 2 check marks

### Operating system

Windows 10

### Version of Telegram Desktop

3.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@EaredRodent This is the platform limitation. There is only "read till message" mark really, not individual read status for each message.
