### ISSUE TITLE
[Feature Request] Add command line option to make telegram desktop not update automatically

### ISSUE THREAD

**Issue by valia0906** [telegramdesktop/tdesktop#17400]
### Is your feature request related to a problem?

Now telegram by default enables update automatically to newer version.

### Describe the solution you'd like

Add command line option to disable Update automatically settings.

### Describe alternatives you've considered

Create configuration file with such option.

**Comment by ilya-fedin** [comment]
Why for?

**Comment by valia0906** [comment]
As latest version does not work through my proxy it infinitely connect to it.

**Comment by ilya-fedin** [comment]
Why can't you just disable the option in UI?

**Comment by ilya-fedin** [comment]
You understand that commandline option won't be specified if e.g. tdesktop is autostarted or session-restored? This is a bad solution to such a problem.

**Comment by valia0906** [comment]
I create own deb package for ubuntu and want to run telegram destkop using special command line options, which is not visible for users.

**Comment by ilya-fedin** [comment]
user can enable autostart in settings or DE can restore session and automatically launch Telegram. It will be started without your option being specified.

**Comment by valia0906** [comment]
That is right, but this option will be usefull too.

**Comment by ilya-fedin** [comment]
I don't think so, it will be a hack that is easy to skip. Not to say you would need to create wrappers and etc. There was such an option, but was removed exactly due to these problems. If you want to disable autoupdates, it's better to build tdesktop from sources.

**Comment by valia0906** [comment]
I want to create wrapper which always run telegram witch such option. As telegram desktop deb package available on ubuntu.com is legacy. So I need to create own deb package with newer telegram version. Not easy to skip because users do not have admin roles.

**Comment by ilya-fedin** [comment]
Wrapper is a hack, it can't guarantee that tdesktop will be always run via it. tdesktop itself uses path to its real binary internally and features like DE's session restoring uses it, as well. No, this is not a reliable way.

**Comment by valia0906** [comment]
It will be great to create configuration file with settings and make it be changable, such as proxy update and othe available through UI.

**Comment by ilya-fedin** [comment]
I believe this request is invalid, this is present since v1.3.10 (year 2018).

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/52e7ddf079d292f0470673f392e6e057eb508bf8
