### ISSUE TITLE
Incomplete code removal broke LibreSSL build

### ISSUE THREAD

**Issue by klemensn** [telegramdesktop/tdesktop#17406]
89765340c3d74c45a49e79c64f2be8bf8b56600c removed code including the functions
`_ssl*()`, https://github.com/telegramdesktop/tdesktop/blob/e7e34d50ba1a73c14962cdc4c3dd5ad7a3da74a7/Telegram/SourceFiles/core/utils.cpp#L109 (and further down) still reference them.

Most likely, this was not detected (on Linux using OpenSSL) since OpenSSL
defines the wrapping `CRYPTO_set_locking_callback()` macros as NOOPs, i.e.
the offending code was effectively dead code: https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/include/openssl/crypto.h#L213

On at least OpenBSD 7.0 using LibreSSL however, those are still actual
functions and the code thus fails to build.

**Comment by ilya-fedin** [comment]
Maybe LibreSSL support should be completely removed given that its development slowed down and Qt doesn't support it

**Comment by klemensn** [comment]
Not sure where this stems from, but development is still active and at least on OpenBSD all Qt related packages use LibreSSL.

Also, as seen here, it uncovers real issues that did not surface with OpenSSL -- I'd consider this valuable.
(Sadly, #17407's commit message neither mentions this nor references this issue, so this information is lost in history and only available if one digs through closed issues and pull requests.)

**Comment by ilya-fedin** [comment]
> Not sure where this stems from

https://voidlinux.org/news/2021/02/OpenSSL.html

AFAIK it doesn't even support DTLS 1.2 that is required for Telegram calls

**Comment by klemensn** [comment]
Both audio and video calls do work on OpenBSD using Telegram Desktop 3.3.0 with LibreSSL.

**Comment by ilya-fedin** [comment]
I know that on void linux they didn't work when calling to non-void clients

**Comment by noiseless** [comment]
> AFAIK it doesn't even support DTLS 1.2 that is required for Telegram calls

I probably misled you with my comment on opennet. More precisely, at that time it was relevant and there really was no support for dtls 1.2 in libressl, but now this is [no longer the case](https://github.com/libressl-portable/portable/issues/380#issuecomment-822632039).
The real reason the calls didn't work even after dtls 1.2 appeared in libressl is that OpenBSD [doesn't support](https://man.openbsd.org/OpenBSD-current/ip6#IPV6_V6ONLY) dualstack sockets.
Now I have a [patch](https://github.com/noiseless/tgwip/blob/master/telegram-desktop/patches/patch-Telegram_ThirdParty_libtgvoip_os_posix_NetworkSocketPosix_cpp) that adds support for calls over ipv4, I will try to finish ipv6 in the near future and make a pull request in tdesktop.

**Comment by ilya-fedin** [comment]
Do we really need three variants of OpenSSL (OpenSSL, LibreSSL, BoringSSL)? Can't you guys stop and work on OpenSSL?

**Comment by janbrennen** [comment]
> Do we really need three variants of OpenSSL (OpenSSL, LibreSSL, BoringSSL)? Can't you guys stop and work on OpenSSL?

Can we get the OpenSSL people to stop instead?

**Comment by ilya-fedin** [comment]
OpenSSL is standard here and the parent

**Comment by janbrennen** [comment]
> OpenSSL is standard here and the parent

So the codebase should be in ANSI C and you should drop cmake for a configure script and Makefile?

**Comment by ilya-fedin** [comment]
wat

**Comment by janbrennen** [comment]
Well clearly older and more standard tools are better and everything else should be ignored?

**Comment by ilya-fedin** [comment]
I haven't said older is better...

**Comment by janbrennen** [comment]
Ah, I forgot parents can be younger than children.

**Comment by ilya-fedin** [comment]
OpenSSL is a parent since LibreSSL/BoringSSL are forks

**Comment by janbrennen** [comment]
I think C might potentially be an ancestor to C++

**Comment by ilya-fedin** [comment]
You can congratulate it when Father Day comes

**Comment by janbrennen** [comment]
I'm pretty sure C is a mom actually

**Comment by noiseless** [comment]
> > AFAIK it doesn't even support DTLS 1.2 that is required for Telegram calls
> 
> I probably misled you with my comment on opennet. More precisely, at that time it was relevant and there really was no support for dtls 1.2 in libressl, but now this is [no longer the case](https://github.com/libressl-portable/portable/issues/380#issuecomment-822632039). The real reason the calls didn't work even after dtls 1.2 appeared in libressl is that OpenBSD [doesn't support](https://man.openbsd.org/OpenBSD-current/ip6#IPV6_V6ONLY) dualstack sockets. Now I have a [patch](https://github.com/noiseless/tgwip/blob/master/telegram-desktop/patches/patch-Telegram_ThirdParty_libtgvoip_os_posix_NetworkSocketPosix_cpp) that adds support for calls over ipv4, I will try to finish ipv6 in the near future and make a pull request in tdesktop.

I apologize for necroposting.
In the quoted message I promised a patch, however, there is no need for it, because my patch refers to the so-called "legacy calls", the actual code for audio/video calls works correctly without any additional patches.

The patch I referred to is removed from our repository with the tdesktop port for openbsd.

Thanks for your work!
