### ISSUE TITLE
Unable to Cancel uploading process in v3.3

### ISSUE THREAD

**Issue by foremtehan** [telegramdesktop/tdesktop#17408]
### Steps to reproduce

1. Upload something
2. Try to cancel it by left click

### Expected behaviour

it should cancel the process

### Actual behaviour

left click not working and doesnt do anything

### Operating system

Windows 10

### Version of Telegram Desktop

v3.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
confirmed.

**Comment by john-preston** [comment]
@foremtehan Thanks for your report! It'll be fixed in the next version.
