### ISSUE TITLE
A problem with the HTTP proxy

### ISSUE THREAD

**Issue by SysMan-One** [telegramdesktop/tdesktop#17409]
Hello, There!

I have a problem with passing TG's stream over my simple HTTP proxy .
(follows a 2 hexdumps with mashed authorization fields)

TG - Proxy leg:

```
0000000  50 4f 53 54 20 68 74 74  70 3a 2f 2f 31 34 39 2e   POST htt p://149.
00000010  31 35 34 2e 31 36 37 2e  39 31 3a 38 30 2f 61 70   154.167. 91:80/ap
00000020  69 20 48 54 54 50 2f 31  2e 31 0d 0a 48 6f 73 74   i HTTP/1 .1..Host
00000030  3a 20 31 34 39 2e 31 35  34 2e 31 36 37 2e 39 31   : 149.15 4.167.91
00000040  3a 38 30 0d 0a 43 6f 6e  74 65 6e 74 2d 54 79 70   :80..Con tent-Typ
00000050  65 3a 20 61 70 70 6c 69  63 61 74 69 6f 6e 2f 78   e: appli cation/x
00000060  2d 77 77 77 2d 66 6f 72  6d 2d 75 72 6c 65 6e 63   -www-for m-urlenc
00000070  6f 64 65 64 0d 0a 43 6f  6e 74 65 6e 74 2d 4c 65   oded..Co ntent-Le
00000080  6e 67 74 68 3a 20 31 33  32 0d 0a 43 6f 6e 6e 65   ngth: 13 2..Conne
00000090  63 74 69 6f 6e 3a 20 4b  65 65 70 2d 41 6c 69 76   ction: K eep-Aliv
000000A0  65 0d 0a 41 63 63 65 70  74 2d 45 6e 63 6f 64 69   e..Accep t-Encodi
000000B0  6e 67 3a 20 67 7a 69 70  2c 20 64 65 66 6c 61 74   ng: gzip , deflat
000000C0  65 0d 0a 41 63 63 65 70  74 2d 4c 61 6e 67 75 61   e..Accep t-Langua
000000D0  67 65 3a 20 72 75 2d 52  55 2c 65 6e 2c 2a 0d 0a   ge: ru-R U,en,*..
000000E0  55 73 65 72 2d 41 67 65  6e 74 3a 20 4d 6f 7a 69   User-Age nt: Mozi
000000F0  6c 6c 61 2f 35 2e 30 0d  0a 50 72 6f 78 79 2d 41   lla/5.0. .Proxy-A
00000100  75 74 68 6f 72 69 7a 61  74 69 6f 6e 3a 20 42 61   uthoriza tion: Ba
00000110  73 69 63 20 51 6e 4a 76 aa aa aa aa aa aa aa   sic zzzzzzzzzzzzzzzzzzz
00000120  aa AA aa AA aa aa AA aa  BA d0 55 aa aa aa a zzzzzzzzzzzzzzzz=
00000130  0d 0a 0d 0a                                        ....
00000134  00 00 00 00 00 00 00 00  18 33 83 a0 c2 21 bb 61   ........ .3...!.a
00000144  70 00 00 00 78 97 46 60  0e 71 84 86 ed d5 d8 46   p...x.F` .q.....F
00000154  83 5a fd b1 a4 80 92 b9  3e 75 bf 96 3b 50 a8 1c   .Z...... >u..;P..
00000164  c3 16 62 d3 a8 73 ea 9d  55 2f c5 b3 43 cc 7e cc   ..b..s.. U/..C.~.
00000174  17 b8 f4 f7 8e aa a9 06  bd 86 3d c9 a5 53 ed 69   ........ ..=..S.i
00000184  1b 82 af ce 44 6e d8 b0  5c ef 58 ab 9a a5 4e 4b   ....Dn.. \.X...NK
00000194  30 67 94 76 c1 60 c5 9f  c4 04 c7 35 f2 b4 28 d2   0g.v.`.. ...5..(.
000001A4  f8 2e 48 8c af d0 19 92  3e 75 ee 40 58 51 f5 ab   ..H..... >u.@XQ..
000001B4  6e be d7 1d                                        n...
    00000000  48 54 54 50 2f 31 2e 31  20 34 31 34 20 52 65 71   HTTP/1.1  414 Req
    00000010  75 65 73 74 20 55 52 49  20 54 6f 6f 20 4c 6f 6e   uest URI  Too Lon
    00000020  67 0d 0a 53 65 72 76 65  72 3a 20 6e 67 69 6e 78   g..Serve r: nginx
    00000030  2f 30 2e 33 2e 33 33 0d  0a 44 61 74 65 3a 20 54   /0.3.33. .Date: T
    00000040  68 75 2c 20 31 36 20 44  65 63 20 32 30 32 31 20   hu, 16 D ec 2021 
    00000050  31 31 3a 32 33 3a 34 36  20 47 4d 54 0d 0a 43 6f   11:23:46  GMT..Co
    00000060  6e 74 65 6e 74 2d 54 79  70 65 3a 20 74 65 78 74   ntent-Ty pe: text
    00000070  2f 68 74 6d 6c 0d 0a 43  6f 6e 6e 65 63 74 69 6f   /html..C onnectio
    00000080  6e 3a 20 6b 65 65 70 2d  61 6c 69 76 65 0d 0a 43   n: keep- alive..C
    00000090  6f 6e 74 65 6e 74 2d 4c  65 6e 67 74 68 3a 20 31   ontent-L ength: 1
    000000A0  39 31 0d 0a 0d 0a 3c 68  74 6d 6c 3e 0d 0a 3c 68   91....<h tml>..<h
    000000B0  65 61 64 3e 3c 74 69 74  6c 65 3e 34 31 34 20 52   ead><tit le>414 R
    000000C0  65 71 75 65 73 74 20 55  52 49 20 54 6f 6f 20 4c   equest U RI Too L
    000000D0  6f 6e 67 3c 2f 74 69 74  6c 65 3e 3c 2f 68 65 61   ong</tit le></hea
    000000E0  64 3e 0d 0a 3c 62 6f 64  79 20 62 67 63 6f 6c 6f   d>..<bod y bgcolo
    000000F0  72 3d 22 77 68 69 74 65  22 3e 0d 0a 3c 63 65 6e   r="white ">..<cen
    00000100  74 65 72 3e 3c 68 31 3e  34 31 34 20 52 65 71 75   ter><h1> 414 Requ
    00000110  65 73 74 20 55 52 49 20  54 6f 6f 20 4c 6f 6e 67   est URI  Too Long
    00000120  3c 2f 68 31 3e 3c 2f 63  65 6e 74 65 72 3e 0d 0a   </h1></c enter>..
    00000130  3c 68 72 3e 3c 63 65 6e  74 65 72 3e 6e 67 69 6e   <hr><cen ter>ngin
    00000140  78 2f 30 2e 33 2e 33 33  3c 2f 63 65 6e 74 65 72   x/0.3.33 </center
    00000150  3e 0d 0a 3c 2f 62 6f 64  79 3e 0d 0a 3c 2f 68 74   >..</bod y>..</ht
    00000160  6d 6c 3e 0d 0a                                     ml>..

```

Proxy-target-TG-host leg:

```
00000000  50 4f 53 54 20 68 74 74  70 3a 2f 2f 31 34 39 2e   POST htt p://149.
00000010  31 35 34 2e 31 36 37 2e  39 31 3a 38 30 2f 61 70   154.167. 91:80/ap
00000020  69 20 48 54 54 50 2f 31  2e 31 0d 0a 48 6f 73 74   i HTTP/1 .1..Host
00000030  3a 20 31 34 39 2e 31 35  34 2e 31 36 37 2e 39 31   : 149.15 4.167.91
00000040  3a 38 30 0d 0a 43 6f 6e  74 65 6e 74 2d 54 79 70   :80..Con tent-Typ
00000050  65 3a 20 61 70 70 6c 69  63 61 74 69 6f 6e 2f 78   e: appli cation/x
00000060  2d 77 77 77 2d 66 6f 72  6d 2d 75 72 6c 65 6e 63   -www-for m-urlenc
00000070  6f 64 65 64 0d 0a 43 6f  6e 74 65 6e 74 2d 4c 65   oded..Co ntent-Le
00000080  6e 67 74 68 3a 20 31 33  32 0d 0a 43 6f 6e 6e 65   ngth: 13 2..Conne
00000090  63 74 69 6f 6e 3a 20 4b  65 65 70 2d 41 6c 69 76   ction: K eep-Aliv
000000A0  65 0d 0a 41 63 63 65 70  74 2d 45 6e 63 6f 64 69   e..Accep t-Encodi
000000B0  6e 67 3a 20 67 7a 69 70  2c 20 64 65 66 6c 61 74   ng: gzip , deflat
000000C0  65 0d 0a 41 63 63 65 70  74 2d 4c 61 6e 67 75 61   e..Accep t-Langua
000000D0  67 65 3a 20 72 75 2d 52  55 2c 65 6e 2c 2a 0d 0a   ge: ru-R U,en,*..
000000E0  55 73 65 72 2d 41 67 65  6e 74 3a 20 4d 6f 7a 69   User-Age nt: Mozi
000000F0  6c 6c 61 2f 35 2e 30 0d  0a 0d 0a                  lla/5.0. ...
000000FB  00 00 00 00 00 00 00 00  18 33 83 a0 c2 21 bb 61   ........ .3...!.a
0000010B  70 00 00 00 78 97 46 60  0e 71 84 86 ed d5 d8 46   p...x.F` .q.....F
0000011B  83 5a fd b1 a4 80 92 b9  3e 75 bf 96 3b 50 a8 1c   .Z...... >u..;P..
0000012B  c3 16 62 d3 a8 73 ea 9d  55 2f c5 b3 43 cc 7e cc   ..b..s.. U/..C.~.
0000013B  17 b8 f4 f7 8e aa a9 06  bd 86 3d c9 a5 53 ed 69   ........ ..=..S.i
0000014B  1b 82 af ce 44 6e d8 b0  5c ef 58 ab 9a a5 4e 4b   ....Dn.. \.X...NK
0000015B  30 67 94 76 c1 60 c5 9f  c4 04 c7 35 f2 b4 28 d2   0g.v.`.. ...5..(.
0000016B  f8 2e 48 8c af d0 19 92  3e 75 ee 40 58 51 f5 ab   ..H..... >u.@XQ..
0000017B  6e be d7 1d                                        n...
    00000000  48 54 54 50 2f 31 2e 31  20 34 31 34 20 52 65 71   HTTP/1.1  414 Req
    00000010  75 65 73 74 20 55 52 49  20 54 6f 6f 20 4c 6f 6e   uest URI  Too Lon
    00000020  67 0d 0a 53 65 72 76 65  72 3a 20 6e 67 69 6e 78   g..Serve r: nginx
    00000030  2f 30 2e 33 2e 33 33 0d  0a 44 61 74 65 3a 20 54   /0.3.33. .Date: T
    00000040  68 75 2c 20 31 36 20 44  65 63 20 32 30 32 31 20   hu, 16 D ec 2021 
    00000050  31 31 3a 32 33 3a 34 36  20 47 4d 54 0d 0a 43 6f   11:23:46  GMT..Co
    00000060  6e 74 65 6e 74 2d 54 79  70 65 3a 20 74 65 78 74   ntent-Ty pe: text
    00000070  2f 68 74 6d 6c 0d 0a 43  6f 6e 6e 65 63 74 69 6f   /html..C onnectio
    00000080  6e 3a 20 6b 65 65 70 2d  61 6c 69 76 65 0d 0a 43   n: keep- alive..C
    00000090  6f 6e 74 65 6e 74 2d 4c  65 6e 67 74 68 3a 20 31   ontent-L ength: 1
    000000A0  39 31 0d 0a 0d 0a 3c 68  74 6d 6c 3e 0d 0a 3c 68   91....<h tml>..<h
    000000B0  65 61 64 3e 3c 74 69 74  6c 65 3e 34 31 34 20 52   ead><tit le>414 R
    000000C0  65 71 75 65 73 74 20 55  52 49 20 54 6f 6f 20 4c   equest U RI Too L
    000000D0  6f 6e 67 3c 2f 74 69 74  6c 65 3e 3c 2f 68 65 61   ong</tit le></hea
    000000E0  64 3e 0d 0a 3c 62 6f 64  79 20 62 67 63 6f 6c 6f   d>..<bod y bgcolo
    000000F0  72 3d 22 77 68 69 74 65  22 3e 0d 0a 3c 63 65 6e   r="white ">..<cen
    00000100  74 65 72 3e 3c 68 31 3e  34 31 34 20 52 65 71 75   ter><h1> 414 Requ
    00000110  65 73 74 20 55 52 49 20  54 6f 6f 20 4c 6f 6e 67   est URI  Too Long
    00000120  3c 2f 68 31 3e 3c 2f 63  65 6e 74 65 72 3e 0d 0a   </h1></c enter>..
    00000130  3c 68 72 3e 3c 63 65 6e  74 65 72 3e 6e 67 69 6e   <hr><cen ter>ngin
    00000140  78 2f 30 2e 33 2e 33 33  3c 2f 63 65 6e 74 65 72   x/0.3.33 </center
    00000150  3e 0d 0a 3c 2f 62 6f 64  79 3e 0d 0a 3c 2f 68 74   >..</bod y>..</ht
    00000160  6d 6c 3e 0d 0a                                     ml>..

```

**So, what I'm need to check ?**

**Comment by ilya-fedin** [comment]
This hexdump is unreadable for me

**Comment by ilya-fedin** [comment]
What's the problem?

**Comment by SysMan-One** [comment]
Тзе проблем в том, что телега не работает через HTTP, сервак шлёт в зад 414.
Как телегу заставить ходить через HTTPS по CONNECT не ясно.

**Comment by ilya-fedin** [comment]
It's not clear for me, too. Looks like a Qt bug and a duplicate of #17316

**Comment by SysMan-One** [comment]
Да, похоже.
Однако,  как сделать что бы телеграм делал коннект в прокси методом CONNECT ?

**Comment by ilya-fedin** [comment]
Someone interested in fixing this should look at the code, find where the bug is and fix it

**Comment by SysMan-One** [comment]
Айм из  хайли интерестед, но не размовляю на плюсавом. Кабы на Си - поправил бы и не мутил воду. :-)
Может есть какая-то настройка или если прокси ответит типа 503, то телеграм перейдёт на HTTPS/CONNECT ?

**Comment by ilya-fedin** [comment]
Telegram uses high-level QtNetwork APIs, so I have no idea what you should do to make it use CONNECT

**Comment by SysMan-One** [comment]
За QT мы не говорим. 
В TDLib есть поддержка HTTPS/CONNECT прям таки . В десктопе, КМК, имеет смысл сделать HTTPS пипочку. Удобно жеж.

**Comment by ilya-fedin** [comment]
tdesktop doesn't use tdlib, tdesktop has custom mtproto implementation written on top of QtNetwork APIs. All code related to proxy handling is in Qt (except of mtproto), all tdesktop does is sets proxy URL via Qt APIs (Core::Sandbox::refreshGlobalProxy)

**Comment by SysMan-One** [comment]
Ясно. Ну, короче, я написал за проблему. Очень надеюсь на фикс-помощ.

**Comment by ilya-fedin** [comment]
There's no any progress in fixing this, unfortunately. This should be reported to Qt, but that would need writing a minimal reproducible example. And you can't write a minimal reproducible example when you can't reproduce the bug.

**Comment by SysMan-One** [comment]
Ситуёвина тут вот какая: не поддерживается метод HTTPS/CONNECT - и не баг, а отсутствие фичи.

**Comment by ilya-fedin** [comment]
Well, it worked previously. Complains started after a Qt update. And what is funny, complains are only from Linux users. Windows/macOS don't seem to be affected.

**Comment by SysMan-One** [comment]
Ок, сейяас я говорю за виндовую версию.

**Comment by ilya-fedin** [comment]
Can you provide what you provided in your first post, but in a readable format?

**Comment by SysMan-One** [comment]
Дэк там hexdump-ы из wireshark. Какая форма нужна никак не соображу ?
Дампы двух плеч, первое : тгдесктоп - прокси, второе: прокси-целевой-сервер-ТГ.  В первом запикана строчка с логин-паролем.
414 типа про то, что в  URI надо отрезать http://<хост:порт> и оставить только "/api" ,  что будет если отрезать - совсем другая история и, прям скажем, неприглядная будет.

Я бы ратовал за то, что добавить (или восстановить)  поддержку HTTPS/CONNECT.

**Comment by ilya-fedin** [comment]
> Дэк там hexdump-ы из wireshark. Какая форма нужна никак не соображу ?

I can't read your hexdump, it has little columns and I can't read the text :see_no_evil: 
Can't you post plain text?

**Comment by ilya-fedin** [comment]
> Я бы ратовал за то, что добавить (или восстановить) поддержку HTTPS/CONNECT.

mtproto can work via plain HTTP, so it's expected it doesn't use CONNECT I think

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/blob/b2fb5424ed4dbd3a19bc497aa5af07b329f91951/Telegram/SourceFiles/mtproto/connection_http.cpp#L248-L255

**Comment by SysMan-One** [comment]
> > Дэк там hexdump-ы из wireshark. Какая форма нужна никак не соображу ?
> 
> I can't read your hexdump, it has little columns and I can't read the text 🙈 Can't you post plain text?

Не ну я смекну какой ещё плайн текст ? в строчках что ли,  так там бинарные данные в запросе.

**Comment by ilya-fedin** [comment]
> Не ну я смекну какой ещё плайн текст ? в строчках что ли, так там бинарные данные в запросе.

Can you post headers in plain text?

**Comment by ilya-fedin** [comment]
> Как телегу заставить ходить через HTTPS по CONNECT не ясно.

Looks like I got what you meant. If you specify HTTP proxy in tdesktop settings, tdesktop will try to connect only with HTTPS. If you set to use system setitngs, it will try both HTTP and TCP (what you thought as HTTPS, apparently).

> 414 типа про то, что в URI надо отрезать http://<хост:порт> и оставить только "/api" , что будет если отрезать - совсем другая история и, прям скажем, неприглядная будет.

It seems Qt does that on a reason
https://github.com/qt/qtbase/blob/dev/src/network/access/qhttpnetworkrequest.cpp#L135-L137

**Comment by ilya-fedin** [comment]
It's not clear for me how your proxy would find the host without it being specified after POST

**Comment by SysMan-One** [comment]
Да, правильно копаете.

**Comment by SysMan-One** [comment]
Мой прокси берёт целевой хост из URI делает дута TCP-коннект и пересылает запрос как есть.

**Comment by SysMan-One** [comment]
Целевой хост не разбирает URI, типа в нём есть хост и ругается 414-ым кодом, что мне представляется полным жлобством со стороны целевого хоста.

**Comment by ilya-fedin** [comment]
Well, it seems to be some extension for HTTP proxies, so it's expected that target host can't parse that. The question is where it should be reported: to Qt or to your proxy server.

**Comment by SysMan-One** [comment]
Бахталэс ромалэ!

**Comment by SysMan-One** [comment]
Тем более что и TDLIB и QT наверняка всё это умеют делать прозрачно. 100 пудов.
Подумайте чутка, там небось пару мэтодов дёрнуть или ещё чё. А людям приятно буить.

**Comment by ilya-fedin** [comment]
> **Осталось за кадром вот что, таки можно добавить CONNECT ?**

You can switch to "Use system proxy" and tdekstop will try both methods: HTTP and TCP

**Comment by SysMan-One** [comment]
Ну это конечно, можно "посылать" юзверя и в систем прокси на виндах с его идиотским синтаксисом, а можно сделать "прозрачно".  Подумайте, плиз. К НГ как раз подарком будет! :-)

**Comment by ilya-fedin** [comment]
Well, I'm not the one who can decide that

**Comment by ilya-fedin** [comment]
I'm a third-party contributor

**Comment by SysMan-One** [comment]
Who can ? Can i ask u provide a right contact ?

**Comment by ilya-fedin** [comment]
@john-preston

**Comment by SysMan-One** [comment]
Как ему можно написать ? Не очень понимаю как тут на гитхабе персонально кому-то что послать .

**Comment by ilya-fedin** [comment]
GitHub has no private messages AFAIK, so you can't

**Comment by SysMan-One** [comment]
Лады. Тогда как его привлечь к рассмотрению проблемы ?

**Comment by ilya-fedin** [comment]
You can try to ask him in https://t.me/TelegramDesktopTalk
