### ISSUE TITLE
Crashes when clicking video-sliderbar

### ISSUE THREAD

**Issue by jk-85** [telegramdesktop/tdesktop#17405]
### Steps to reproduce

1. Install latest telegram version (3.3) on Windows 7 (64 Bit).
2. Click on a video
3. Click on video window-in-window button: https://abload.de/img/1h3j8l.jpg
4. Click on any position in the slider: https://abload.de/img/210juo.jpg
5. Happy crashing.

I got this bug for years now.

### Expected behaviour

Should show video at clicked position.

### Actual behaviour

Telegram crashes.

### Operating system

Windows 7 64 Bit

### Version of Telegram Desktop

3.3

### Installation source

Static binary from official website

**Comment by jk-85** [comment]
It crashes also when you watched the video to the end, make it smaller with the button in step 3 (see above) and click in the middle of that video (big play button).

**Comment by john-preston** [comment]
@jk-85 Can you enable installing beta versions in Settings, then reproduce the crash and then on the next launch send the crash report and copy the Crash Report Tag string here? Thank you.

**Comment by jk-85** [comment]
I did so, I hope this is the right one:
UserTag: f2802569429d638f

**Comment by john-preston** [comment]
@jk-85 Not user tag but crash report tag please.

**Comment by jk-85** [comment]
Oh, sorry. I did a new report.
Your Report Tag: eb655936-ece3-4f22-bd7e-466557c4a816

**Comment by john-preston** [comment]
Thanks for the report. This crash is on this assert:

https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/media/view/media_view_pip.cpp#L1584-L1585

This assert is part of the debugging of a strange crash, that I don't know, how happens (and I can't reproduce myself). It looks like decoding a video frame on the main thread there causes some sort of memory corruption, right now I don't understand, what to do with that, sorry.

**Comment by jk-85** [comment]
I found out, reinstalling would fix the problem. Strange, I have to reinstall about 3 Windows 7 machines. But it's fixed on computer 1 now ;-)
