### ISSUE TITLE
Large part of notification not clickable on Ubuntu Desktop when using bottom taskbar

### ISSUE THREAD

**Issue by RuurdBijlsma** [telegramdesktop/tdesktop#17413]
### Steps to reproduce

1. Use Ubuntu 20.04 with bottom position selected for task bar
2. Receive notification
3. It appears partly over the taskbar at the bottom
4. I can't click the part of the notification that is over the bottom taskbar

![image](https://user-images.githubusercontent.com/5478546/146582443-17821df3-2398-493a-b9ed-b1f38533d7b3.png)

### Expected behaviour

I click the notification on any part and it opens Telegram to that chat

### Actual behaviour

I click the notification on the part that's over the taskbar and nothing happens

### Operating system

Ubuntu 20.04 GNOME

### Version of Telegram Desktop

3.3

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Have you tried to restart Telegram after changing taskbar position? Have you tried logout-login (or reboot) after changing taskbar position?

**Comment by RuurdBijlsma** [comment]
Yes, it's always been this way (i've used ubuntu about a week now). So there have been multiple reboots and restarts

**Comment by ilya-fedin** [comment]
Do you have multiple screens by any chance?

**Comment by RuurdBijlsma** [comment]
Yes, 3

**Comment by ilya-fedin** [comment]
Accoring to [Qt documentation](https://doc.qt.io/qt-5/qscreen.html#availableGeometry-prop), X11 has no way of getting the geometry without system panels when the system has more than one screen. So there's no way to fix this.
