### ISSUE TITLE
[BUG] Unread number is not cleared, when computer resume from suspended mode (linux)

### ISSUE THREAD

**Issue by nadavkav** [telegramdesktop/tdesktop#17417]
### Steps to reproduce

1. Resume computer from suspended mode (Ubuntu Linux)
2. Open Telegram, choose a channel with unread messages, and read (scroll) all of them.
3. Unread number not cleared
4. Restart Telegram, choose a channel with unread messages, and read (scroll) all of them.
5. Unread number clears.

### Expected behaviour

1. Resume computer from suspended mode.
2. Open Telegram, choose a channel with unread messages, and read (scroll) all of them.
3. Unread number should be cleared.

### Actual behaviour

Unread number not cleared, after reading all messages.

### Operating system

Kubuntu 20.04 Linux, KDE

### Version of Telegram Desktop

3.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Unread number is in a lot of places, where exactly it's not cleared?

**Comment by nadavkav** [comment]
I am referring to the "Unread number" in all places: (1) left side Icon Toolbar, (2) List of channels/groups names (3) Lower right side of channel messages panel.
