### ISSUE TITLE
[Question] How to adjust font weight on default font for chat?

### ISSUE THREAD

**Issue by casper** [telegramdesktop/tdesktop#17416]
Having recently upgraded to version 3.3 from the 1.8.15 client I have used for many years, I noticed the default font in the 3.3 chat is extremley thin and much less contrasty than the old 1.8.15 client.

The difference is annoying enough it affects text legibility. The font is simply too thin, razor like. It affects readability.

I tried adjusting ClearType contrast in the Windows control panel, but it seems to have no effect on Telegram. 

How can I tweak the weight so it is more like 1.8.15? 

![20211218-024001-001](https://user-images.githubusercontent.com/25386/146623212-5f796f9a-bb7f-4738-a8e5-89af2787ff6c.png)

**Comment by ilya-fedin** [comment]
I guess it's the changes in the underlying toolkit (Qt). 1.8.15 used Qt 5.6, 3.3 on Windows uses Qt 5.15 (but Qt 6.2 on Linux/macOS)

**Comment by ilya-fedin** [comment]
I don't think you can tweak weight

**Comment by casper** [comment]
I figured out how to fix this. 

On Windows Qt adjusts it's overall font weight at startup based on the ClearType registry value for font smoothing contrast. There is a key `GammaLevel` in the registry located here: 

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Avalon.Graphics\\\<displayName>

In my case I needed to set GammaLevel to 1000 to match my original setup.
Restart Telegram and problem solved.
