### ISSUE TITLE
[Feature Request] Playback Speed in Channels with protected contents

### ISSUE THREAD

**Issue by chromer030** [telegramdesktop/tdesktop#17414]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

Currently in channels with protected content introduced in Telegram Desktop 3.3.0 when playing audios, there is no option for playback speed control, please implement this options as it is essential for some users.

### Describe alternatives you've considered

Nothing.

**Comment by john-preston** [comment]
Are you sure there is a difference in case of protected or not protected channels?

Because right now for audio files the playback speed controller is available for files of 20 minutes or longer (podcasts). It works the same in restricted for sharing channels and for non-restricted.

**Comment by RememberTheAir** [comment]
I think @chromer030 is talking about voice messages' playback speed specifically

**Comment by chromer030** [comment]
@john-preston , You are right , the feature is OK and working , all of files in channel i'm talking about is shorter than 20 minutes and i thought something is broken. thank you for clarifying.
But why this feature is not available for files shorter than 20 minutes ?

**Comment by john-preston** [comment]
@chromer030 Well, usually you listen in an increased speed for the podcasts, but not for the music.

**Comment by chromer030** [comment]
@john-preston , some podcasts are shorter than 20 minutes :) , closing the issue.
but i hope you consider speed controller option for all of kind of audio files , it's an option and options usually are useful.
thank you.
