### ISSUE TITLE
Current DEV does not build on Windows x64

### ISSUE THREAD

**Issue by shurrman** [telegramdesktop/tdesktop#17418]
### Steps to reproduce

Followed current build for windows x64 instructions. Also done git submodule init/update. 

### Expected behaviour

Builds successful

### Actual behaviour

Errors:

modules/rtp_rtcp/source/rtp_util.h: No such file or directory,	lib_tgcalls C:\TBuild\tdesktop\Telegram\ThirdParty\tgcalls\tgcalls\MediaManager.cpp	21	

media/sctp/sctp_transport_factory.h: No such file or directory, (компилируется исходный файл C:\TBuild\tdesktop\Telegram\ThirdParty\tgcalls\tgcalls\SctpDataChannelProviderInterfaceImpl.cpp)	lib_tgcalls	C:\TBuild\tdesktop\Telegram\ThirdParty\tgcalls\tgcalls\SctpDataChannelProviderInterfaceImpl.h	7	

media/base/sdp_video_format_utils.h: No such file or directory,	lib_tgcalls	C:\TBuild\tdesktop\Telegram\ThirdParty\tgcalls\tgcalls\v2\InstanceV2Impl.cpp	36	

pc/video_track_source_proxy.h: No such file or directory,	lib_tgcalls	C:\TBuild\tdesktop\Telegram\ThirdParty\tgcalls\tgcalls\platform\tdesktop\DesktopInterface.cpp	8	

modules/rtp_rtcp/source/rtp_util.h: No such file or directory,	lib_tgcalls	C:\TBuild\tdesktop\Telegram\ThirdParty\tgcalls\tgcalls\group\GroupInstanceCustomImpl.cpp	39	

pc/video_track_source_proxy.h: No such file or directory,	lib_tgcalls	C:\TBuild\tdesktop\Telegram\ThirdParty\tgcalls\tgcalls\platform\tdesktop\VideoCapturerInterfaceImpl.cpp	10	

I have a cloned DEV version when it was 3.2.1 - it builds just ok following exactly same procedure.

### Operating system

Windows 11 x64

### Version of Telegram Desktop

dev (=3.3.0)

### Installation source

Other (unofficial) source

**Comment by john-preston** [comment]
@shurrman I think you have an old version of tg_owt dependency. Try running the prepare script again.

**Comment by shurrman** [comment]
@john-preston yes, prepare checks out new versions, one needs to rebuild deps. Thanks!
