### ISSUE TITLE
trackpoint scroll freeze

### ISSUE THREAD

**Issue by algroznykh** [telegramdesktop/tdesktop#17421]
### Steps to reproduce

1. launch Telegram on a device with a trackpoint (tested with Thinkpad)
2. open any chat
3. scroll with trackpoint

### Expected behaviour

chat scrolls infinitely

### Actual behaviour

scroll freezes after a couple of screens

### Operating system

ubuntu 20.04, i3

### Version of Telegram Desktop

3.3

### Installation source

Static binary from official website

**Comment by acestudiooleg** [comment]
Linux acestudio-XPS-15-9500 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - 
Telegram Desktop - 3.2.5 vesrion

the same issue
