### ISSUE TITLE
[Feature request] A setting so admins can change their own custom title

### ISSUE THREAD

**Issue by Wanny** [telegramdesktop/tdesktop#17425]
I'm a "grey star" admin in  a chat and I can't change my custom title (heck, I don't even SEE the section)

![image](https://user-images.githubusercontent.com/569307/146988035-5e8d79c2-1e34-4d2a-a657-e7e565afa433.png)

Only "blue star" admins can change my title, but if I'm an admin regardless I'd like to change my user title instead of asking someone to change it for me.

Can it be possible to add a "Change own custom title" setting?

**Comment by RememberTheAir** [comment]
> Only "blue star" admins can change my title

Actually, everyone in the admins hierarchy above you has the ability to change your title. The "blue star" admin is the chat creator, which sits on top of the hierarchy and can change anyone's admin title - but your title can also be changed by the admin who promoted you, or the admin that promoted the admin that promoted you, and so on and so on

Clarifications aside - the API doesn't allow admins to change their own title. You should open a ticket on https://suggestions.telegram.org

**Comment by Wanny** [comment]
So, I will be able to change my title if *I* promote someone?

**Comment by RememberTheAir** [comment]
No, the user who promotes you will be able to change _your_ title. If you promote another user to administrator aswell, you will be able to change _their_ title

**Comment by Wanny** [comment]
Ugh, that's really annoying. I added a suggestion in the link you gave me, hope it's taken into account.
