### ISSUE TITLE
Wrong changelog link (or unupdated changelog)

### ISSUE THREAD

**Issue by LucianoHanna** [telegramdesktop/tdesktop#17422]
### Steps to reproduce

1. Click in menu bar
2. Click in "Version 3.3"

### Expected behaviour

This will open https://desktop.telegram.org/changelog but the last update of this changelog was v2.8.8 (15/07/2021)

### Actual behaviour

Updated changelog

### Operating system

Ubuntu

### Version of Telegram Desktop

3.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
i see 3.3 there.

**Comment by john-preston** [comment]
![image](https://user-images.githubusercontent.com/17900494/146909634-56b6ddcb-3955-46f7-a448-d7d78db78749.png)

🤔

**Comment by LucianoHanna** [comment]
I checked again and there's an issue on i18n of the site, I see v3.3 on en version but not on pt-br version, probably should open another issue, but I didn't find which repository I should report.

![image](https://user-images.githubusercontent.com/22209724/146931586-1ef19bca-2155-4199-afd7-f1e373c7c5aa.png)
