### ISSUE TITLE
Long pressing key should display character selector on OS X

### ISSUE THREAD

**Issue by anunez** [telegramdesktop/tdesktop#1742]
When long pressing a key for about 1 second on OS X apps, a character selector with different variants for the corresponding character is commonly displayed. This is UX pattern in OS X that helps people write special characters without having to switch to a different keyboard layout. Right now, the telegram desktop client fast repeats the character instead.

**Comment by evolvah** [comment]
Yes, I support this request. A long press invokes the autorepeat mode instead of offering alternate characters with diacritics. It is impossible to type the Cyrillic letter "ё" this way. Behavior that is consistent with OS X would be very much appreciated.

**Comment by telegramdesktop** [comment]
@evolvah It is not supported in Qt library in the input fields as I know :(

**Comment by nickmelis** [comment]
it used to work on my Mac. Now it stopped though after an update. Has something changed recently?

**Comment by stek29** [comment]
@nickmelis Maybe you used native app for macOS?

**Comment by nickmelis** [comment]
@stek29 I am using the native Mac OSX app. After an update I started experiencing the problem described in this issue.

**Comment by stek29** [comment]
@nickmelis This repo is for TDesktop and not for native macOS app, sorry.

**Comment by auchri** [comment]
@nickmelis This repo is for the native app: https://github.com/overtake/telegram

**Comment by ironicmoka** [comment]
Still not working on TDesktop (not the MAS version)

**Comment by stek29** [comment]
@ironicmoka stick to #2886.
Also see #3377 and #2830, #2587 and #1939
