### ISSUE TITLE
List of hashtags

### ISSUE THREAD

**Issue by AlexanderZhirov** [telegramdesktop/tdesktop#17427]
### Is your feature request related to a problem?

When messages with hashtags are left in chats, it is impossible to remember a correctly written hashtag to search for the desired message.

### Describe the solution you'd like

I would like to store all the hashtags specified in the chat in some kind of sheet (chat tab) for each chat, when calling which it was possible to filter out messages by the desired hashtag in the current chat.

### Describe alternatives you've considered

Unfortunately, there are no alternatives. This function is very lacking.

**Comment by RememberTheAir** [comment]
Very similar to #5191 and #794 - but both of them have been closed and locked. By the way, my [old comment](https://github.com/telegramdesktop/tdesktop/issues/5191#issuecomment-424854959) still stands

The same suggestion has been submitted on the official suggestions platform btw:

- https://bugs.telegram.org/c/3698
- https://bugs.telegram.org/c/1532
- https://bugs.telegram.org/c/9177
- https://bugs.telegram.org/c/11225
- https://bugs.telegram.org/c/11224

**Comment by AlexanderZhirov** [comment]
@RememberTheAir It is very inconvenient without this mechanism. There are a lot of messages with hashtags, and how to find the right message without having a hashtag name is unclear.
