### ISSUE TITLE
Arabic song name is behind UI elements

### ISSUE THREAD

**Issue by Nabeel20** [telegramdesktop/tdesktop#17426]
### Steps to reproduce

1. play any Arabic song, the file title should be Arabic

### Expected behaviour

To be able to read the name of song(s) playing

### Actual behaviour

the name is behind UI of shuffle and other elements

### Operating system

Windows 8.0 

### Version of Telegram Desktop

3.3

### Installation source

Static binary from official website

**Comment by SMSadegh19** [comment]
Is it must be Arabic or in any RTL language?

**Comment by Nabeel20** [comment]
after testing; any RTL language
