### ISSUE TITLE
[Question] Which API id/hash to use for OS packages

### ISSUE THREAD

**Issue by klemensn** [telegramdesktop/tdesktop#17435]
Telegram's API registration requires a private account to gain API access, which is undesirable for official packages in Linux Distributions and BSD derivatives.

Looking at those packages I often see them reusing Snap's id/hash, altough it isn't clear to me whether they just copied the credentials from publically accessible sources or whether there is written permission from the Snap team to do so.

I am packaging tdesktop for OpenBSD but am reluctant to copy the id/hash values like others and/or use my personal API token for the OpenBSD package that can be used by everyone.

I could not find any official documentation (or way of contact in this matter) to find out, hence my question here:
What API id/hash should or can be used by OS packages that are not officially supported by Telegram (everything but those mentioned on https://desktop.telegram.org)?

**Comment by john-preston** [comment]
Hi. I was told that the official response is using your personal API token. Every Telegram app requires api_id / api_hash credentials and the only way to get those is for individual Telegram users.

**Comment by klemensn** [comment]
What does that mean for existing non-Snap packages already using Snap's id/hash?
Must they switch to personalised maintainer IDs?

What are the implications of using my personal API token for official OS packages that will be used by everyone?
My assumption is that I would be held responsible for any harm done via this token.

What about OS packages like the following which use Snap's id/hash?
- NixOS: https://github.com/NixOS/nixpkgs/blob/d00918ccaf7e1532d35db2f1e3d44db3da39b851/pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix#L152
- Arch: https://github.com/archlinux/svntogit-community/blob/packages/telegram-desktop/trunk/PKGBUILD#L24
https://build.opensuse.org/package/view_file/openSUSE:Factory/telegram-desktop/telegram-desktop.spec?expand=1
- Gentoo: https://gitweb.gentoo.org/repo/gentoo.git/tree/net-im/telegram-desktop/telegram-desktop-3.3.0.ebuild#n121

Some claim they're allowed to use it, some thank GitHub user @primeos, although I don't see what for.
More place use Snap's id/hash as per https://github.com/search?q=d524b414d21f4d37f08684c1df41ac9c.

I understand how personal usage should be bound to personalised API access,
the common situation package maintainers find themselves in however seems different to me.

Any chance it would be officially allowed to use a common API id/hash?
I don't want to publish an OS package for everyone that is inherently tied to me as a natural person.
If I get banned the package stops working for every OS user and if OS users do stupid things I might be the one tha gets banned -- neither should ever happen, imho.

**Comment by primeos** [comment]
Oops, those packages should actually thank @john-preston and @ilya-fedin. IIRC I was just the first one to ask @john-preston for permission thanks to a hint from @ilya-fedin that this might be possible/allowed. Thanks again to both of you! :)

Anyway, before that I tried to contact some Telegram officials regarding this but didn't get anywhere:
https://github.com/NixOS/nixpkgs/issues/55271#issuecomment-462166610

Your best option might be https://twitter.com/telegram but it'll possibly require some "angry mob" to even get their attention... :o :D
(On a personal note (SCNR): I'm just glad I got to escape that "proprietary" ecosystem - mostly at least.)

**Comment by klemensn** [comment]
> Oops, those packages should actually thank @john-preston and @ilya-fedin. IIRC I was just one of the first ones to ask @john-preston for permission to use that ID for Linux distribution packages (thanks to a hint from @ilya-fedin that this might be possible/allowed). Thanks again to both of you! :)

So does that mean you got permission from @john-preston or @ilya-fedin to use Snap's id/hash?
That's what I get from comments in the above linked package descriptions in combination with your comment here.
But it doesn't align with that @john-preston stated here, i.e. that I'd have to get my own credentials rather than using existing ones.

> Anyway, before that I tried to contact some Telegram officials regarding this but didn't get anywhere:
NixOS/nixpkgs#55271 (comment)

It's a bummer really that your attempts to contact someone from Telegram lead nowhere.
Thanks a lot for your efforts!

**Comment by ilya-fedin** [comment]
I want to mention that I can't give permission since I'm a third-party contributor

**Comment by primeos** [comment]
> So does that mean you got permission from @john-preston or @ilya-fedin to use Snap's id/hash?

I guess the situation's a bit complicated but yes.

> But it doesn't align with that @john-preston stated here, i.e. that I'd have to get my own credentials rather than using existing ones.

IMO there's no contradiction. @john-preston wrote:
> Hi. I was told that the official response is using your personal API token. Every Telegram app requires api_id / api_hash credentials and the only way to get those is for individual Telegram users.

And that is true / the official response. So far no one seems to have managed to successfully contact a Telegram official regarding this so there's still no proper solution for Linux distributions.

**Comment by klemensn** [comment]
> > But it doesn't align with that @john-preston stated here, i.e. that I'd have to get my own credentials rather than using existing ones.
> 
> IMO there's no contradiction. @john-preston wrote:
> 
> > Hi. I was told that the official response is using your personal API token. Every Telegram app requires api_id / api_hash credentials and the only way to get those is for individual Telegram users.

He proxied a supposedly official response that states using "your personal API token".

> And that is true / the official response. So far no one seems to have managed to successfully contact a Telegram official regarding this so there's still no proper solution for Linux distributions.

Which directly contradicts what at least three different OS packages do, i.e. reusing yet another package's API token rather than (the maintainer's?) personal one.

As I see things now, package maintainers can either break with Telegram's official expectation and abuse someone else's token (bad thing) or provide public packages using a single person's token (bad thing as well).

Or am I missing something?

**Comment by primeos** [comment]
Update: I'm not using Telegram-Desktop anymore but as a last attempt I've quickly wrote the following email (just a quick draft to see what happens) to recover@telegram.org (it was linked here: https://core.telegram.org/api/obtaining_api_id):
```
Subject: API IDs for Linux distributions

Hi *,

is it possible to request API IDs to package Telegram apps for Linux
distributions? On Linux, users should use a package manager to install
applications instead of downloading them from websites, etc. (this is
important for automatic (security) updates, consistency, independent
verification by the Linux distribution, reproducible builds (ideally),
etc.). Linux distributions build apps like Telegram-Desktop from source
but don't modify them (apart from minor patches, if necessary, to fix
build issues, etc.).

Personal API IDs (tied to ones Telegram account / phone number) are not
suitable for this purpose (e.g. there might be multiple package
maintainers, they usually change over time, and they're not developing
the app, just packaging it). Instead, those API IDs should be tied to
the Linux distribution (/ a public email address associated with it).
This is already possible for other packages, like Google's Chromium for
example. They also publicly track downstream maintainers here:
https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/linux/chromium_packages.md

Alternatively it would be fine if we were allowed to re-use the API ID
of the apps we're packaging.

I've kept this request brief so please let me know if you need
additional information regarding the motivation, etc.
I'm writing this request because multiple Linux distributions (e.g.
NixOS, Arch Linux, openSUSE, and OpenBSD - I can provide sources for
that, if you want, and include them in this discussion) want a proper
solution for this special and important case.

Kind regards,
Michael
```

I've also amended the following via a reply (I didn't link to this issue though because they might not like the current situation and I don't intend to make this worse for Linux distributions):
```
PS (FYI): I intend to publicly share replies on GitHub (where this
discussion started) because of the other Linux distributions(/maintainers)
that are interested in a proper/official solution for this issue.
```

I'll post updates here.
If someone wants to publicly (or privately) tweet at https://twitter.com/telegram that'd be welcome as well.

**Comment by primeos** [comment]
cc (FYI, hope you don't mind if I involve/ping you here - feel free to unsubscribe - this just seems like a good place for a public discussion):
- NixOS: @oxalica @VergeDX
- Arch Linux: @svenstaro
- openSUSE: @DimStar77
- Gentoo: @mid-kid

**Comment by john-preston** [comment]
@klemensn Well, the official response I got was to use personal credentials. My personal opinion is that you can use your personal credentials or take the ones that are used for snap build, they're already publicly available, so I think it is fine to use them for the packages.

**Comment by VergeDX** [comment]
Yes, NixOS packaging with the token from Snap:
https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix#L152

**Comment by ilya-fedin** [comment]
> it was linked here

Well, I guess supoort contacts better fit than the email for account recovers
https://telegram.org/faq#telegram-support

**Comment by ilya-fedin** [comment]
The link in "If you can't log in to your account, please use this form." seem actually refer to generic support URL

**Comment by klemensn** [comment]
> Yes, NixOS packaging with the token from Snap: https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix#L152

Yes, I see nixpkgs does it, but I have yet to see proper official permission to do so.

> The related commit: [NixOS/nixpkgs@a86d317](https://github.com/NixOS/nixpkgs/commit/a86d317da859bfcef5c96e049d4f803cabb0591f) related issues of nixpkgs: [NixOS/nixpkgs#55271](https://github.com/NixOS/nixpkgs/issues/55271)

NixOS/nixpkgs@a86d317 says
```
Thanks to Ilya Fedin and John Preston we're now allowed to reuse the
API ID of the Snap package to avoid hitting rate limits. This finally resolves #55271 #YAY \o/
```
But here in this thread, @ilya-fedin already stated his non-official position  (thanks) and @john-preston referred to someone else's statement saying to do otherwise rather than reconfirming that using Snap's API id/hash is allowed.

I hate to be picky here, but: @john-preston, can you speak for Telegram officially and is your permission you supposedly granted as per the nixpkgs commit still valid and can be expanded to OpenBSD as well?
Or can you not make an official statement on behalf of Telegram and are you thus merely suggesting, as your personal opinion, to use someone else's API token?

**Comment by john-preston** [comment]
@klemensn Yes, I think you can use Snap tokens for this package, they're mine.

**Comment by ilya-fedin** [comment]
> they're mine

Isn't that token was created by the person added snapcraft.yml?

**Comment by mid-kid** [comment]
Not sure why I was pinged, nor what the issue is exactly, but I'm comfortable using whatever unless I'm specifically told not to.

This key was added by a previous Gentoo contributor, anyway.

**Comment by klemensn** [comment]
> > they're mine
> 
> Wasn't that token created by the person added snapcraft.yml?

Would that be @3v1n0 who authored https://github.com/telegramdesktop/tdesktop/commit/e781b29d5785177f4a34058dd79dc4780923ed14 adding the id/hash as committed by @john-preston ?

**Comment by john-preston** [comment]
@klemensn Hmm, indeed, mine are the public test only credentials for the github source code.

Sorry then, my bad. Still I think you can use them, although they're not mine.

**Comment by ilya-fedin** [comment]
> Would that be @3v1n0 who authored [e781b29](https://github.com/telegramdesktop/tdesktop/commit/e781b29d5785177f4a34058dd79dc4780923ed14) adding the id/hash as committed by @john-preston ?

Yeah, it should be he

**Comment by klemensn** [comment]
> @klemensn Hmm, indeed, mine are the public test only credentials for the github source code.
> 
> Sorry then, my bad. Still I think you can use them, although they're not mine.

Thanks for clarifying this.

So, AFAICT, Snap's API token is currently being reused without permission.

Even if allowed by whoever owns it, Telegram's official stance seems to remain that each package (distribution) use their own token, which does not align with reuse, imho.

**Comment by ilya-fedin** [comment]
If you choose to follow the official requirements, you would need to establish some secret key system for package builders since API_ID/API_HASH can't be published according to their official rules.

**Comment by klemensn** [comment]
> If you choose to follow the official requirements, you would need to establish some secret key system for package builders since API_ID/API_HASH can't be published according to their official rules what I guess a bigger problem than finding someone in your distribution who would agree to create a token on his/her account.

I doubt some hand-waving "secret key system" makes any sense,
`grep -Ex '[[:xdigit:]]{32} $(which telegram-desktop)` shows the API hash and
https://github.com/telegramdesktop/tdesktop/blob/dad1f196bae3a24c44656a03141f6d9c2baa95c5/Telegram/SourceFiles/core/crash_report_window.cpp#L512 should make it trivial to get the API id as well.

Put differently, I'd consider any API token used in public builds to be public knowledge, i.e. they're subject to potential reuse by anyone.
Which, imho, is a rather strong argument for dedicated maintainer/distribution tokens....
Or no tokens at all, given that you can just use any of the publicly accessible tokens in circulation anyway -- so why bother with registering one in the first place?

**Comment by ilya-fedin** [comment]
Well, I don't understand why do you care about the requirement to have your _own_ token and doesn't care about another requirement at the same time :thinking:

**Comment by klemensn** [comment]
> Well, I don't understand why do you care about the requirement to have your _own_ token, but don't care about another requirement at the same time 🤔

I care about the requirement because I care about a potential OpenBSD package adhering to Telegram's official requirements.

But I also care about not binding someone's personal token (and thus further their Telegram account) to a package that is (ab)used by others.

I tried to make a point about the usefulness of Telegram's API access design,
given it's implications outlined in this thread.

**Comment by xvitaly** [comment]
@klemensn If you use your own token, you will receive dozens of reports from users who are unable to register a new account, because registration is(was) disabled at the API level for all unofficial API tokens.

That's why use Snap tokens. They works fine without any restrictions.
