### ISSUE TITLE
macOS: images stop pasting from the clipboard

### ISSUE THREAD

**Issue by diversys** [telegramdesktop/tdesktop#17432]
### Steps to reproduce

I'm using `CMD+Shift+3` shortcut to copy a picture of selected area to the clipboard but I don't think this is relevant:

![image](https://user-images.githubusercontent.com/1316513/147292891-07d90b4d-c33c-4ed6-89b7-4e20e92da9bc.png)

### Expected behaviour

Pasting images should work every time

### Actual behaviour

Pasting images from the clipboard work for some time but suddenly Telegram stops pasting new images and paste text from the clipboard instead. This has been the case for several years but I never reported it.
Today I noticed that if I copy an image from Telegram then pasting images magically start to work again until the next time pasting breaks. Then I have to do the same to "fix" it again.

### Operating system

macOS Mojave 10.14.6

### Version of Telegram Desktop

3.3

### Installation source

Static binary from official website

**Comment by diversys** [comment]
This is still and issue with 4.0.2.

**Comment by ilya-fedin** [comment]
This issue is now a part of #25126

**Comment by diversys** [comment]
This is still an issue.

**Comment by vonDubenshire** [comment]
Still an issue

**Comment by kelavrik** [comment]
Still issue
