### ISSUE TITLE
[Feature Request] Option to build without libdispatch

### ISSUE THREAD

**Issue by noiseless** [telegramdesktop/tdesktop#17437]
### Is your feature request related to a problem?

There is a new mandatory dependency in the tdesktop 3.3.1 release - libdispatch. Now there is no working libdispatch port on *BSD (on FreeBSD and OpenBSD at least), so we have no simple (i.e. without rolling back libdispatch-related commits) way to build actual versions of tdesktop.

### Describe the solution you'd like

As far as I know, libdispatch ports for both [OpenBSD](https://github.com/apple/swift-corelibs-libdispatch/pull/559) and [FreeBSD](https://github.com/apple/swift-corelibs-libdispatch/pull/561) are being worked on, but at this point, being able to build a tdesktop without libdispatch seems like a faster solution.

### Describe alternatives you've considered

I'm not sure there are any alternative solutions for this problem. They will appear when libdispatch is successfully ported to OpenBSD/FreeBSD.

### Additional context

I am willing to help write a patch to be able to build tdesktop without libdispatch if this solution itself is acceptable to you.

**Comment by ilya-fedin** [comment]
> As far as I know, libdispatch ports for both [OpenBSD](https://github.com/apple/swift-corelibs-libdispatch/pull/559) and [FreeBSD](https://github.com/apple/swift-corelibs-libdispatch/pull/561) are being worked on, but at this point, being able to build a tdesktop without libdispatch seems like a faster solution.

Well, maybe this will speedup the porting process. I believe if the option would be added, most maintainers will be just enable the option instead of packaging libdispatch. So it's better if that would be a downstream BSD patch, for the time being at least.

**Comment by klemensn** [comment]
We can always carry local patches, but with rather big/complicated ports such as tg_owt and tdesktop it quickly becomes a burden and hinders the usual porting/testing effort.

Most of our changes have been submitted via PRs already, the rest is work-in-progress still.

I am less pessimistic about such a new options, especially since dispatch is already ported to Linux and distributions should have less trouble making use of it.

**Comment by ilya-fedin** [comment]
It should enough to specify `CXXFLAGS=-DCRL_FORCE_QT` (or `-DCMAKE_CXX_FLAGS=-DCRL_FORCE_QT`) and add a return() just after add_library in external_dispatch's CMakeLists.txt. Then, when dispatch is ported, you can remove this flag and one-line patch.

**Comment by ilya-fedin** [comment]
> I am less pessimistic about such a new options, especially since dispatch is already ported to Linux and distributions should have less trouble making use of it.

I wish this was the true. Some maintainers prefer to disable parts of functionality just because it's using libraries they don't like. So it sometimes feels that it's better to avoid having build options to have less situations when people complaining due to the fact their maintainer disabled that functionality.

**Comment by klemensn** [comment]
> It should be enough to specify `CXXFLAGS=-DCRL_FORCE_QT` (or `-DCMAKE_CXX_FLAGS=-DCRL_FORCE_QT`) and add a return() just after add_library in external_dispatch's CMakeLists.txt. Then, when dispatch is ported, you can remove this flag and one-line patch.

Thanks, that seems like the easiest way for now and I just confirmed this works, running 3.3.1 without dispatch on OpenBSD at the moment!

**Comment by noiseless** [comment]
Thank you very much for the solution you suggested, it seems to be +/- what we wanted.
Of course, when/if the libdispatch port for OpenBSD is completed, we will prefer to enable it and remove the options/modifications you suggested now.
