### ISSUE TITLE
[Feature Request] Monochrome Icon for Windows

### ISSUE THREAD

**Issue by livejamie** [telegramdesktop/tdesktop#17438]
### Is your feature request related to a problem?

The current blue telegram icon looks out of place in the Windows 10 system tray:

![image](https://user-images.githubusercontent.com/49513/147396207-31fabc6f-9fc9-435a-b99a-a447a8c91d51.png)

### Describe the solution you'd like

You should consider replacing it with black and white to blend in like this and make that configurable in the settings:

![image](https://user-images.githubusercontent.com/49513/147396212-9eaa6a31-033c-47b9-9596-f41a12644e1a.png)

### Describe alternatives you've considered

n/a

### Additional context

There are a few issues that mention this for windows but they're closed #1353 #3301

There's one for Linux in #1908 but it doesn't apply to windows

**Comment by ilya-fedin** [comment]
What if the taskbar is white? :thinking: 
White on white would look ugly

**Comment by livejamie** [comment]
The request is for a monochrome icon, not a white icon.

The best practice would be for it to follow the system theme. (Black icon for light theme, white icon for dark theme)

Allowing the user to manually select from blue, white or black would be a good solution as well.

**Comment by ilya-fedin** [comment]
> The request is for a monochrome icon, not a white icon.

White icon is a monochrome icon since it has only two colors.

> The best practice would be for it to follow the system theme. (Black icon for light theme, white icon for dark theme)

The question is how to follow it? You have a pixmap icon, you set it, you don't what's the color of the taskbar, result will be unpredictable, it may end white on white.

**Comment by livejamie** [comment]
Thanks for your comments.

I know that other programs have the ability to skin their app based on the system theme so I know it's possible somehow.

**Comment by ilya-fedin** [comment]
You mean apps written in WinAPI, right? tdesktop is written in Qt. And then even apps using system theme don't have monochrome icon.

**Comment by igor-kobzev** [comment]
@ilya-fedin Monochrome icons on Linux would also be much appreciated.

**Comment by ilya-fedin** [comment]
> Monochrome icons on Linux would also be much appreciated.

You can install an icon theme with monochrome icons (e.g. Papirus) on Linux

**Comment by abb128** [comment]
> > Monochrome icons on Linux would also be much appreciated.
> 
> You can install an icon theme with monochrome icons (e.g. Papirus) on Linux

This does not seem to affect the status icon
![image](https://user-images.githubusercontent.com/65567823/172621873-24f84641-147b-4c6d-a254-5309e5a9cc8c.png)

**Comment by ilya-fedin** [comment]
It's supposed to.
![изображение](https://user-images.githubusercontent.com/17829319/172622537-f853e8b4-f4bc-4a1f-8e37-98b65280ad51.png)

**Comment by igor-kobzev** [comment]
Same for me as for @abb128 . I dunno how @ilya-fedin got it to change like that. Must have been something other than Papyrus.

**Comment by igor-kobzev** [comment]
doesn't seem like this windows-specific issue is progressing towards any kind of resolution. you're just making every excuse to not do anything imao.

**Comment by ilya-fedin** [comment]
It doesn't mean you can discuss a completely unrelated issue (a problem in existing feature implementation on one platform is not related to feature request on other platform) here.

**Comment by igor-kobzev** [comment]
i wouldn't say it's unrelated. this is a feature request for monochrome icons for windows. i added that the same feature for gnome would be really nice, too. you claim it exists on gnome already, but it doesn't. a Papyrus icon hack - which doesn't work - is a hack, not a feature implemented by telegram-desktop.

**Comment by igor-kobzev** [comment]
um... a feature is when i can find a tickbox in telegram settings 'use monochrome icons', a hack is when i have to use a totally unrelated icon pack to achieve the same goal.
i get your point that the solution to my problem exists and i can obtain it by opening a bug report on papyrus github or whatev. but this is beside the issue. since telegram is cross-platform, i don't get why feature requests have to be windows-specific or linux-specific. i think 'make using monochrome icons an optional feature of telegram-desktop on all platforms' is a reasonable request. but maybe we should hear a third opinion.

**Comment by ilya-fedin** [comment]
1. You don't need to open issue on Papirus repository, you need to open a new issue (of bug report type & filling all the required by issue template information) in tdesktop repository if you need help in finding out why tdesktop doesn't follow the chosen icon theme for you.
2. This is OS-specific as every OS has different APIs. It's already implemented on macOS as it provides known APIs to detect the color of the panel. It's also implemented on Linux with icon theming so anyone can choose the appropriate icon for themselves by choosing the appropriate icon theme. There's no check for this feature on any platform as this feature is active out-of-the-box and @john-preston prefers not to add settings (there are feature requests for such option to disable the feature, though).

**Comment by bravechamp** [comment]
I'd like to remind that this is still not done and it also affects Windows 11. For those who reminded that this is a Qt project (not a WinAPI project), Qt allows detecting dark mode since [Qt 6.5](https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5). So, it is possible to implement this as most of the Qt based applications implemented it already.

**Comment by ilya-fedin** [comment]
Can you point to those applications? Is system dark mode guaranteed to match the taskbar color?

Also, tdesktop is stuck with Qt 5.15 due to Windows 7 support.

**Comment by bravechamp** [comment]
I saw dark mode support on [qBittorrent](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/uithememanager.cpp#L45) but it looks more of a hack than a proper solution. [KeepassXC](https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/osutils/winutils/WinUtils.cpp#L104C10-L104C10) doesn't rely on Qt to detect dark mode which could be the way to go in Telegram as well.

**Comment by ilya-fedin** [comment]
SystemUsesLightTheme key looks like exactly what's needed. Currently tdesktop uses only AppsUseLightTheme.

**Comment by zelosleone** [comment]
It does not need to detect, but allowing users to change the tray icon from settings should be at least added to telegram. As it's a must tbh.

**Comment by ilya-fedin** [comment]
@zelosleone don't expect a settings would be added

**Comment by zelosleone** [comment]
> @zelosleone don't expect a setting would be added

Eh, why not?

**Comment by ilya-fedin** [comment]
@zelosleone the practice is to avoid adding new settings

**Comment by zelosleone** [comment]
> @zelosleone the practice is to avoid adding new settings

As far as i see, experimental settings under advanced settings can be used for this. Also, some telegram alternative clients support this too, although they are extremely old and not updated in over 2 years. It's not that much of a change and i find it bad faith to not to include this tbh.

**Comment by ilya-fedin** [comment]
@zelosleone i don't think this will be allowed to be in experimental settings. Detecting the system taskbar color is the only realistic way.

**Comment by ildar170975** [comment]
With my all due respect - that was a dumb change.
1. Can you find the icon here?
![изображение](https://github.com/telegramdesktop/tdesktop/assets/71872483/df81663d-01bd-4646-a46f-37223d192ff6)
2. What makes you believe that 100% of users have "modern apps with modern monochrome icons"?

If you decided to change the icon - at least consider a user option to change it.
But no, you want others to experience your poor taste.

**Comment by john-preston** [comment]
@ildar170975 Maybe counter should be replaced with a small dot, like on Windows Update.

**Comment by ilya-fedin** [comment]
@john-preston maybe just make the font smaller? It works on macOS after all.

**Comment by john-preston** [comment]
@ilya-fedin It was there from the beginning, so nothing unusual there.

**Comment by lazynooblet** [comment]
Please revert this, or like the original request asked, "and make that configurable in the settings". I can't distinguish telegram from other icons. I use Telegram all the time and this is the only change that has made me sad.

**Comment by Pathfinder9021** [comment]
Could you please revert this change. The message counter is now unreadable and it's difficult to quickly distinguish the Telegram icon from other tray icons. 

![image](https://github.com/telegramdesktop/tdesktop/assets/43930265/e4bc228b-cae0-4de9-b377-a5842303fd18)

PS What a stupid tendency to make everything monochrome. Monochrome icons don't look good and lose their individuality. Even Microsoft acknowledged this in the Windows 11 Settings app.
![image](https://github.com/telegramdesktop/tdesktop/assets/43930265/44411419-f70d-46bc-a405-53f1cd8d826e)

**Comment by ildar170975** [comment]
@john-preston you tread on my dreams...
Please leave the counter.
And make icon colored again.
Do not follow trends which are wrongly considered as "modern & common".
Also, read about people who may distinguish objects by its colorS, not by its shape. Keyword - "accessibility".

**Comment by OpenSpaghettiSauce** [comment]
This whole Issue makes no sense. The Microsoft icons are monochrome and this makes them easy to distinguish from other apps. It makes no sense to turn everything monochrome. 

Besides. The Telegram icon was modern, it looked great, it was easy to spot from 12-20 icons in the tray. Now? It's a quest to find it.

**Comment by navossoc** [comment]
Same...

![image](https://github.com/telegramdesktop/tdesktop/assets/2457338/fd57e26c-67a3-43d5-81a4-451cfa4d3344)

Its the white icon... but which one?

**Comment by scorpion421** [comment]
Who the hell thought this was a good idea? "Settings > Select Tray-Icon Style" "Monochrome [_]" "Colored [_]" < This is the correct way. Jesus Christ. This is the first time considering searching for a forked version. Yes: It's this bad.

**Comment by navossoc** [comment]
@scorpion421 I saw the new option now... 
![image](https://github.com/telegramdesktop/tdesktop/assets/2457338/28bd7324-5265-4cbe-b371-a74c2f9863d7)

It's boring do this kind of stuff (customization), but this is the proper way to introduce new concepts without infuriating the old user base.

**Comment by scorpion421** [comment]
Correct. This remembered me of Windows 8 because one wise guy said: "Yeah, it's good, make it" and then we had a menu looked like some pre-school kid did design. If you do a new design: Fine. But always leave the old one for users, managing the app with muscle memory. That also includes a simple icon. Yes, they fixed it now. But imagine nobody would have mentioned the bad decision.
