### ISSUE TITLE
[Feature Request] Delete multiple selected proxies.

### ISSUE THREAD

**Issue by SMSadegh19** [telegramdesktop/tdesktop#17434]
### Is your feature request related to a problem?

I want to select multiple proxies and delete them. But I can't. I have to delete them one by one.

### Describe the solution you'd like

Add an option to select multiple proxies and delete them.

### Describe alternatives you've considered

Option to delete all proxies from the proxy list.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5028
