### ISSUE TITLE
Public (Not Private) Instagram Links' Previews Not Shown

### ISSUE THREAD

**Issue by stanislawru** [telegramdesktop/tdesktop#17444]
### Steps to reproduce

1. Copy any link to an Instagram publication of a **public** (**not** private) account, either to a photo (https://www.instagram.com/p/CIoZXGYH55W/) or a video (https://www.instagram.com/p/CX_JAiYBBnw/).
2. Paste it into the message edit box.
3. Send it to any of your contacts.

### Expected behaviour

In the sent message you see the link's preview (some text with a picture).

### Actual behaviour

In the sent message you see only the link itself, **no** preview.

### Operating system

Windows 7, 8, 10

### Version of Telegram Desktop

3.3

### Installation source

Static binary from official website

**Comment by stanislawru** [comment]
![Instagram Link Without a Preview](https://user-images.githubusercontent.com/58035665/147493611-fa63a81d-b8f2-40ad-9b88-f4254526e9ad.png)

**Comment by Aokromes** [comment]
very likely server side issue.

**Comment by stanislawru** [comment]
@Aokromes, do you mean Telegram servers or Instagram ones?
- Telegram servers can be, as the bug exists in the Android application as well.
- Instagram server can**not** be, as the bug is constant in any day/time.

**Comment by Aokromes** [comment]
> @Aokromes, do you mean Telegram servers or Instagram ones?
> 
> * Telegram servers can be, as the bug exists in the Android application as well.
> * Instagram server can**not** be, as the bug is constant in any day/time.

telegram ones ofc.

**Comment by RememberTheAir** [comment]
I believe Instagram is somehow stopping Telegram's crawler from scraping the webpage preview. All other previews works, but Instagram's are often broken, then fixed, then broken again and so on and so on: https://t.me/s/tginfoen/1043

**Comment by SpEcHiDe** [comment]
Instagram now needs login to access the contents. 

https://github.com/yt-dlp/yt-dlp/issues/2093
