### ISSUE TITLE
Tray Icon Bug [Linux]

### ISSUE THREAD

**Issue by alkaris2** [telegramdesktop/tdesktop#17446]
### Steps to reproduce

The Tray Icon for Telegram Desktop on Linux is bugged. Everytime Telegram starts up the Tray Icon never displays, even though it's checked in  **Settings > Advanced > System Integration > Show tray icon** I have to go to my settings every time, just to make it show up when it should already display when the box is checked.

### Expected behaviour

Expected behaviour is that it should always start up when the **Show tray icon** is enabled from the settings by default.

### Actual behaviour

It doesn't actually show when you launch Telegram, or is auto-launched from Startup Applications.

### Operating system

Manjaro 21.2.0 Qonos - Cinnamon

### Version of Telegram Desktop

3.2.5

### Installation source

Static binary from official website

### Logs

_-_

**Comment by ilya-fedin** [comment]
Provide log.txt when tray icon is not shown and when it's shown

**Comment by rogerlga** [comment]
I'm facing exactly this same issue now. Maybe a regression?
It started on version 3.5.0. Today it updated to 3.5.2, but the issue persists.
I'm on openSUSE Tumbleweed, with KDE Plasma 5.24.1. Telegram installed from distro's official repo.
