### ISSUE TITLE
Telegram does not open from tray icon

### ISSUE THREAD

**Issue by LiohMoeller** [telegramdesktop/tdesktop#17447]
### Steps to reproduce

1. Install latest enlightenment desktop (0.25.0) which uses appindicator tray icons
2. Install current Telegram client (stable or beta)
3. Close the Telegram window to the tray icon
4. Try to open it again

![grafik](https://user-images.githubusercontent.com/1267594/147567922-afe32a5a-9c81-48b3-a9e9-34524a92dcf5.png)

### Expected behaviour

The application should open on a right click on the appindicator icon / open

### Actual behaviour

The application is not shown when trying to activate from the tray icon

### Operating system

Linux

### Version of Telegram Desktop

3.3.1 beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Maybe your DE has some focus prevention mechanism? You should disable it in order to avoid such kind of problems
