### ISSUE TITLE
WebP and WebM still not treated as media

### ISSUE THREAD

**Issue by AlexFundorin** [telegramdesktop/tdesktop#17445]
### Steps to reproduce

Drag media file into desktop app from a file explorer/browser or attach it via the clip icon.

### Expected behaviour

Both formats should be treated as regular media.
As for now, webp is treated as sticker, so it's not possible to zoom in on mobile.
webm is treated as document, so not possible to preview/scroll immediately, until the file is fully downloaded.
This issue was addressed numerous times, throughout the years, but it's still not fixed. Issues are being auto closed, one by one.
For example, this one: #6276 - https://github.com/telegramdesktop/tdesktop/issues/6276

### Actual behaviour

images and videos in webp and webm formats are treated as stickers and documents, instead of media

### Operating system

android, ios

### Version of Telegram Desktop

3.3.1

### Installation source

Static binary from official website

**Comment by DarkDot** [comment]
Having this issue as well. Please fix.

**Comment by soredake** [comment]
.webm are now supported as of 3.5.0 version

**Comment by KelseyDH** [comment]
This is becoming a big issue, [as Chrome browsers on reddit now download all images by default as .webp](https://www.reddit.com/r/chrome/comments/edmdqz/tutorial_how_to_force_images_to_be_save_as_png/).  This is ruining my telegram chats.  The issue raised in #6278 are not resolved.

**Comment by jgaztelu** [comment]
Can confirm, this has been an issue for a long time and it's getting worse as more websites switch to WebP for their images. Shouldn't be so difficult to fix, when pasting a webP ask if you want to send it as image/file/sticker, similar to what happens with other images prompting the compressed/file dialog.

**Comment by soredake** [comment]
Webp are still a problem.

**Comment by Aokromes** [comment]
such issue belongs to https://bugs.telegram.org/

**Comment by soredake** [comment]
https://bugs.telegram.org/c/21363
