### ISSUE TITLE
Spoiler messages are difficult to read

### ISSUE THREAD

**Issue by Brawaru** [telegramdesktop/tdesktop#17454]
### Steps to reproduce

1. Write a message and use spoiler formatting
2. Send it and reveal spoiler in the outgoing message

### Expected behaviour

Spoilers have a highlight that does not affect text contrast too much. For example, a brighter highlight in light themes and darker in darker themes.

### Actual behaviour

<table>
<tr>
	<td align="center"><h4>Screenshot
    <td align="center"><h4>Problem
<tr>
	<td align="center"><img src="https://user-images.githubusercontent.com/10401817/147733017-223c09e4-57cf-4ca3-9520-cc71029adf7d.png" alt="Screenshot demonstrating spoiler formatting in message input field; it's displayed as a black text is on the dark grey background">
    <td>Black text is difficult to read on a dark grey background
<tr>
    <td align="center"><img src="https://user-images.githubusercontent.com/10401817/147733136-523729da-3127-4492-bdc0-60f35814dbe8.png" alt="Screenshot demonstrating spoiler formatting in sent message; it's displayed as a white text on the light grey background">
    <td>White text is difficult to read on a light grey background
<tr>
    <td colspan="2" align="center"><strong>Since 3.4</strong>
<tr>
    <td align="center"><img src="https://user-images.githubusercontent.com/10401817/147772731-427c0d07-4388-4525-9fbb-3ce76716ba82.png" alt="Screenshot demonstrating spoiler formatting in sent messages; there's no difference between normal message and opened spoiler message">
   <td>There is no difference between normal message and opened spoiler message</td>
</table>

### Operating system

Windows 10 20H2 (19042)

### Version of Telegram Desktop

3.3.2-beta, 3.4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
try on 3.4

**Comment by Brawaru** [comment]
It's even weirder on 3.4: opened spoilers now show as regular messages. The message input hasn't changed.

**Comment by john-preston** [comment]
The same as on mobiles.

**Comment by Brawaru** [comment]
I don't use mobile clients to know, but I don't think you should completely copy them, not such poor design choices at least. But if you have to, can we at least have options to fix these issues manually through themes?
