### ISSUE TITLE
indication for disabled notifications missing

### ISSUE THREAD

**Issue by eworm-de** [telegramdesktop/tdesktop#17450]
### Steps to reproduce

1. start Telegram desktop
2. right-click on a contact or group
3. select "Disable notifications"

### Expected behaviour

The Android app shows an icons next to contact/group name indicating the disabled notifications.

### Actual behaviour

... and this icon for indication is missing in Telegram desktop.

### Operating system

Arch Linux x86_64 with Xfce

### Version of Telegram Desktop

3.3.0-1 (Arch Linux package)

### Installation source

Other (unofficial) source

**Comment by eworm-de** [comment]
To show the difference... This is the Android app where an icon is displayed next to the channel name:
![Screenshot_20220426-181901](https://user-images.githubusercontent.com/970853/165348407-e9967871-229b-4c17-8463-ee0037379857.png)

And this is the desktop application where the icon is missing - for both, the channel list on the left and the heading on the right:
![Screenshot_2022-04-26_18-18-38](https://user-images.githubusercontent.com/970853/165348401-fb2cd799-15ed-4776-89e6-76d2652e4391.png)

**Comment by eworm-de** [comment]
This is still an issue.

**Comment by eworm-de** [comment]
Still an issue, let's keep it open.

**Comment by eworm-de** [comment]
Still an issue, let's keep it open.

**Comment by ilya-fedin** [comment]
#5981

**Comment by dimas1980200** [comment]
***@***.***

вт, 16 апр. 2024 г., 20:53 ilya-fedin ***@***.***>:
