### ISSUE TITLE
Posts with spoilers showing as simple text in private messages on old telegram clients

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#17453]
### Steps to reproduce

1. Send text with spoiler formatting to someone in private message
2. Spoiler working on telegram desktop beta 3.3.2
3. But not working on 3.3, it's just text, there is even no "This message is not supported" like in public groups

Telegram desktop beta 3.3.2:
![image](https://user-images.githubusercontent.com/39812401/147728732-0d3a7b2a-82c1-4e21-acd8-6b1051a76fca.png)

Telegram desktop 3.3:
![image](https://user-images.githubusercontent.com/39812401/147728740-099cb186-a8a8-4594-81fd-dbf649ffcc55.png)

### Expected behaviour

Text with spoiler on old telegram clients give you "This message is not supported" in private messages like it does in public groups

### Actual behaviour

Text with spoiler showing like simple text on old telegram clients in private messages

### Operating system

Windows 10

### Version of Telegram Desktop

3.3.2 Beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I can't reproduce that :( Is it still happening?

**Comment by Neurotoxin001** [comment]
> Is it still happening?

Yes. Btw you must test it in real user private messages, you can't reproduce it in your saved messages.

**Comment by Neurotoxin001** [comment]
Update. After I login into new telegram desktop client (copy-pasted exe to another folder) issue is disappeared and now I get "This message is not supported by your version" even in PM.
