### ISSUE TITLE
Cursor is excessively large on Wayland HiDPI

### ISSUE THREAD

**Issue by nyuszika7h** [telegramdesktop/tdesktop#17457]
### Steps to reproduce

1. Log in to the default Wayland session
2. Set display scaling to 125% or above
3. Install Telegram Desktop v3.3.2 or newer (using `snap install telegram-desktop --beta` or `snap install telegram-desktop --edge`)
4. Launch Telegram Desktop
5. Observe the cursor size

### Expected behaviour

The cursor should have a normal size that matches the rest of the system, just like it did in v3.3.0.

### Actual behaviour

The cursor is excessively large. (It seems slightly larger even on 100% scaling with Wayland, but that's completely tolerable compared to the HiDPI cursor.)

Tested versions:
* 3.3.0 - Good
* 3.3.2-beta-87-g2c20e7bb0 - Bad
* 3.4.0-12-g450f9ca91 - Bad

Cursor in Telegram Desktop:
![Photo](https://i.imgur.com/9i8dEzd.jpg)

Cursor elsewhere:
![Photo](https://i.imgur.com/AcW18dy.jpg)

(Apologies for taking a photo of the screen, but screenshots do not accurately reflect the cursor size difference.)

It's also worth noting that in v3.3.0 the default interface scale is 100%, while in v3.3.2/3.4.0 it's 200% and I am unable to pick a lower scale. However, the overall interface scale (apart from the cursor) seems to be the same.

### Operating system

Ubuntu 21.10

### Version of Telegram Desktop

3.4.0-12-g450f9ca91

### Installation source

Snap

**Comment by ilya-fedin** [comment]
GNOEM doesn't set cursor theme & size for Qt applications on Wayland and Qt defaults to theme named 'default' (/usr/share/icons/default) and size of 32. You have to set XCURSOR_THEME and XCURSOR_SIZE variables.

**Comment by nyuszika7h** [comment]
Hmm, indeed, this seems to fix it:
```sh
echo 'XCURSOR_SIZE="24"' >> /etc/environment
```
And then logging out and back in again.

**Comment by hynet-mel** [comment]
Can report it too, for some reason before the last update it was fine and now the cursor is enormous in v3.4
This and the default cursor font is used, which is different per window.
I am not sure what happened, but did anything in specific get changed?

Also running on GNOME, but whatever is happening, it's isolated to Telegram and other Qt programs are working fine

**Comment by ilya-fedin** [comment]
I believe Qt was using wasn't defaulting to Wayland before Qt 6.2.2. I guess you have no more Qt applications using version 6.2.2.

**Comment by hynet-mel** [comment]
> I guess you have no more Qt applications using version 6.2.2.
Actually.... Could very much be the case, I'll investigate for a bit.

**Comment by cichy1173** [comment]
I have the same issue with cursor. Also I can't switch to native titlebar and use not-native notfications

**Comment by ilya-fedin** [comment]
Yeah, GNOEM Wayland doesn't provide native titlebar, that's a [famous thing](https://gitlab.gnome.org/GNOME/mutter/-/issues/217). Custom notifications don't support Wayland and support couldn't be added since Wayland protocol lacks positioning APIs (i.e. you can't set x and y coordinates for a window, only size)

**Comment by cichy1173** [comment]
> Yeah, GNOEM Wayland doesn't provide native titlebar, that's a [famous thing](https://gitlab.gnome.org/GNOME/mutter/-/issues/217). Custom notifications don't support Wayland and support couldn't be added since Wayland protocol lacks positioning APIs (i.e. you can't set x and y coordinates for a window, you can set only window size)

I am using this things on GNOME Wayland with Telegram 3.3.

**Comment by ilya-fedin** [comment]
> I am using this things on GNOME Wayland with Telegram 3.3.

Have you read the thread? Look at [this](https://github.com/telegramdesktop/tdesktop/issues/17457#issuecomment-1003190398) post.

**Comment by cichy1173** [comment]
> > I am using this things on GNOME Wayland with Telegram 3.3.
> 
> Have you read the thread? Look at [this](https://github.com/telegramdesktop/tdesktop/issues/17457#issuecomment-1003190398) post.

Oh, I see the point now.

**Comment by pooyasa** [comment]
Can confirm this problem. Ubuntu 20.04, Wayland.
Happened after today's update to 3.4
Also 3.4.1 did not fix it.

**Comment by ilya-fedin** [comment]
No tdesktop update will fix it, it's GNOEM who doesn't set settings for non-gtk applications

**Comment by teohhanhui** [comment]
>  it's GNOEM who doesn't set settings for non-gtk applications

Actually it's Qt which refuses to support setting the correct cursor theme / size for GNOME on Wayland:

https://bugreports.qt.io/browse/QTBUG-67579?focusedCommentId=440118&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-440118

But yeah, not much Telegram Desktop can do about it.

**Comment by ilya-fedin** [comment]
It's more logical for DEs to set de-facto standard environment variable than for toolkits to implement every DE's settings API

**Comment by john-preston** [comment]
Ok, I've created a fresh Qt bug report, I hope they'll make some changes:

https://bugreports.qt.io/browse/QTBUG-99535

**Comment by cichy1173** [comment]
Telegram Desktop 3.4.3 solves this problems.

**Comment by hynet-mel** [comment]
> Telegram Desktop 3.4.3 solves this problems.

Can confirm! It's fixed for me :)

**Comment by nyuszika7h** [comment]
Indeed, seems fine on 3.4.3 even without that environment variable now.
