### ISSUE TITLE
problem with spoiler links

### ISSUE THREAD

**Issue by ehsan2003** [telegramdesktop/tdesktop#17456]
### Steps to reproduce

send a message with spoiler entity with a link inside

### Expected behaviour

telegram should not display preview for spoiler links

### Actual behaviour

the telegram desktop displays links previews for spoiler highlighted links 

### Operating system

ubuntu 

### Version of Telegram Desktop

3.3.2

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@ehsan2003 How is it in mobile apps? The sender can always remove the preview.

**Comment by ehsan2003** [comment]
> @ehsan2003 How is it in mobile apps? The sender can always remove the preview.

I don't have access to a phone 

although it could be removed but its good to be there after the link appeared 
it is not a serious bug , but it's kind of annoying and risky when it comes to spoilers
