### ISSUE TITLE
Packaged build failure with Qt 6 and Wayland integration

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#17460]
### Steps to reproduce

Run standard packaged build with Qt 6 and Wayland integration.

### Expected behaviour

Successful build.

### Actual behaviour

Build failure:

```
[4/1074] cd /builddir/build/BUILD/tdesktop-3.4.0-full/redhat-linux-build/cmake/external/kwayland/kwayland-prefix/src/kwayland && patch -p1 < /builddir/build/BUILD/tdesktop-3.4.0-full/cmake/external/kwayland/../../patches/kwayland-qt6.patch && /usr/bin/cmake -E touch /builddir/build/BUILD/tdesktop-3.4.0-full/redhat-linux-build/cmake/external/kwayland/kwayland-prefix/src/kwayland-stamp/kwayland-patch
FAILED: cmake/external/kwayland/kwayland-prefix/src/kwayland-stamp/kwayland-patch /builddir/build/BUILD/tdesktop-3.4.0-full/redhat-linux-build/cmake/external/kwayland/kwayland-prefix/src/kwayland-stamp/kwayland-patch 
cd /builddir/build/BUILD/tdesktop-3.4.0-full/redhat-linux-build/cmake/external/kwayland/kwayland-prefix/src/kwayland && patch -p1 < /builddir/build/BUILD/tdesktop-3.4.0-full/cmake/external/kwayland/../../patches/kwayland-qt6.patch && /usr/bin/cmake -E touch /builddir/build/BUILD/tdesktop-3.4.0-full/redhat-linux-build/cmake/external/kwayland/kwayland-prefix/src/kwayland-stamp/kwayland-patch
/bin/sh: line 1: /builddir/build/BUILD/tdesktop-3.4.0-full/cmake/external/kwayland/../../patches/kwayland-qt6.patch: No such file or directory
```

### Operating system

Fedora 35

### Version of Telegram Desktop

3.4.0

### Installation source

Other (unofficial) source

**Comment by xvitaly** [comment]
This [patch](https://github.com/desktop-app/cmake_helpers/blob/815bdb2fb5751cf59daf576a4d6c5a3882a4173f/external/kwayland/CMakeLists.txt#L21-L24) is not a part of the official tarball.

I think it would be better to fork it, patch and bundle patched version.

**Comment by ilya-fedin** [comment]
That would be a nightmare for updating, KDE frameworks update monthly

**Comment by xvitaly** [comment]
> That would be a nightmare for updating, KDE frameworks update every multiple months

Maybe you should send Qt 6 patch directly to KDE upstream? They will start moving to Qt 6 soon. I think such PR will be accepted.

**Comment by ilya-fedin** [comment]
All I did is replaced Qt5 with Qt6 in cmake for client libraries and disabled building of tests, server libraries and etc. I believe they can do such a simple replace on their own when it will be the time.

**Comment by john-preston** [comment]
@xvitaly thanks for the report! I should learn to pack the patch as part of the tarball.
