### ISSUE TITLE
Dark theme does not work with Reactions for stickers

### ISSUE THREAD

**Issue by masreplay** [telegramdesktop/tdesktop#17466]
### Steps to reproduce

Reaction color does not change to dark on a dark theme with sticker
![image](https://user-images.githubusercontent.com/55885230/147784479-a8f71a7c-f9f9-423b-b0a4-6f04c553c938.png)

### Expected behaviour

sticker's reaction still white color with a sticker 

### Actual behaviour

white color appears for sticker's reaction instead of black

### Operating system

Windows 11

### Version of Telegram Desktop

Version 3.3.2 beta x64

### Installation source

Microsoft Store

**Comment by john-preston** [comment]
Fixed by 9486c266b will be in the next version. Thanks for your report.

**Comment by masreplay** [comment]
@john-preston 
I'm sorry but does the fix work for gif too?
![image](https://user-images.githubusercontent.com/55885230/147787760-87e5e240-3f5a-4bef-bc97-9c42e0a080f1.png)

**Comment by john-preston** [comment]
It should.
