### ISSUE TITLE
Animated Reaction Emojis!!

### ISSUE THREAD

**Issue by Hessam-Koucheki** [telegramdesktop/tdesktop#17462]
### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/24957423/147777108-2830c92c-525e-45fe-aa63-ef1cfdff6996.png)
These Emojis are not animated and totally static and senseless.

### Describe the solution you'd like

make them moving please :)

### Describe alternatives you've considered

Animated Emojis.

**Comment by mr-tafreshi** [comment]
This is a request that applies to all clients and I think you should submit it here:
https://bugs.telegram.org

**Comment by john-preston** [comment]
Cmon, they're animated in mobile apps.

**Comment by Hessam-Koucheki** [comment]
well, Fortunately they animated Reaction Emojis in beta version 3.4.4.
thanks for participating.
