### ISSUE TITLE
HiDPI scaling issue with GNOME+Wayland starting from 3.4

### ISSUE THREAD

**Issue by pabl0** [telegramdesktop/tdesktop#17468]
### Steps to reproduce

1. Install Telegram from Flatpak or desktop.telegram.org
2. Start Telegram
3. 

### Expected behaviour

UI looks the same as with previous version (correct scaling, no huge window decoration, things render normally).

### Actual behaviour

After upgrading to 3.4, all UI elements are tiny on GNOME+Wayland with 4K monitor (Debian 10). There are very thick black borders around the app window that did not exists there before (3.3).

I am able to change the scaling settings to 150% which fixes the scaling issue somewhat, but it seems everything renders bit weirdly (sometimes menu items are drawn only when you hover the cursor over). Furthermore, I cannot resize the window at all.

This is a clear regression from the previous version where the UI worked perfectly on this setup.

### Operating system

Debian 10.11

### Version of Telegram Desktop

3.4

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
> I am able to change the scaling settings to 150% which fixes the scaling issue somewhat, but it seems everything renders bit weirdly (sometimes menu items are drawn only when you hover the cursor over).

Can you provide a screenshot?

**Comment by pabl0** [comment]
> Can you provide a screenshot?
![tdesktop-scaling1](https://user-images.githubusercontent.com/2339734/147812001-25e3a4c1-5bce-4803-b9ec-c6be8fddd239.png)
![tdesktop-scaling2](https://user-images.githubusercontent.com/2339734/147812002-b4a00196-54ed-4e5c-9526-43dcae3e252f.png)

**Comment by ilya-fedin** [comment]
What's your GNOEM version? 3.4 has newer Qt version and, apparently, it started defaulting to Wayland. If your GNOEM version is very old (what I guess is very likely since you're using Debian), it can have a lot of bugs affecting Qt on Wayland. Then I can suggest to switch to X11 or update to a newer distro version.

**Comment by pabl0** [comment]
> What's your GNOEM version? 3.4 has newer Qt version and, apparently, it started defaulting to Wayland. If your GNOEM version is very old (what I guess is very likely since you're using Debian), it can have a lot of bugs affecting Qt on Wayland. Then I can suggest to switch to X11 or update to a newer distro version.

Yeah, this is still oldstable that has Gnome 3.30.2. Need to test with current stable that has 3.38 if it's any better. This is not the first time when Qt software has rendering issues.

BTW I'm running the flatpak version with org.freedesktop.Platform runtime 21.08, but I guess most gnome stuff is in the actual host OS?

Is it possible to fall back to X11 rendering (Xwayland) with some env variable  for just this software?

**Comment by ilya-fedin** [comment]
> BTW I'm running the flatpak version with org.freedesktop.Platform runtime 21.08, but I guess most gnome stuff is in the actual host OS?

It's the compositor who bugs, not libraries

> Is it possible to fall back to X11 rendering (Xwayland) with some env variable for just this software?

I guess you can use `QT_QPA_PLATFORM=xcb`, but I have no idea how you would set so it won't affect other Qt software

**Comment by pabl0** [comment]
> I guess you can use QT_QPA_PLATFORM=xcb, but I have no idea how would you set it so it won't affect other Qt software

That's easy: 

`flatpak override --user --env=QT_QPA_PLATFORM=xcb org.telegram.desktop`

And it does seem to indeed help!

**Comment by ilya-fedin** [comment]
oh, flatpak, yeah

**Comment by pooyasa** [comment]
Can confirm this problem. Ubuntu 20.04, Wayland.
Happened after today's update to 3.4
Also 3.4.1 from snap did not fix it.
Another problem: telegram app is suddenly closed when using other programs or switching to other workspaces.

**Comment by ilya-fedin** [comment]
Yeah, 20.04 has too old GNOEM. You have to switch to X11/update your system/ask your distro maintainer to backport relevant fixes from newer GNOEM.

**Comment by Ratio2** [comment]
> Yeah, 20.04 has too old GNOEM, too. You have to switch to X11/update your system/ask your distro maintainer to backport relevant fixes from newer GNOEM.

It is rather strange to send users to update the operating system, because:
1. Everything worked great in version 3.3
2. Ubuntu 20.04 is the latest LTS version and is pretty fresh. Changing the operating system every six months is not normal.

Ignoring many Linux users is not a good solution.

**Comment by ilya-fedin** [comment]
Well, there's nothing could be done since the underlying toolkit (Qt) updates and adopts new technologies. Not to say that Wayland is considered too unstable for 20.04 to be default and therefore when you switched to it, you're on your own.

**Comment by ilya-fedin** [comment]
Having to stick with an old Qt is not an option. If you think this should be fixed without system update or switching to X11, you have two options:
1. Ask your distro maintainer to backport the fix of [the issue](https://gitlab.gnome.org/GNOME/mutter/-/issues/199) that causing the flicker in GNOEM.
2. Report this to Qt, so if they fix this, next time tdesktop will update Qt you will see this fixed.

**Comment by pabl0** [comment]
It seems the workaround of falling back to X11 (QT_QPA_PLATFORM=xcb) is reasonable and  works fine. However, I think it would be great if tdesktop itself could somehow detect that the user is running too old gnome version with this issue and do it automatically, since I suspect not many non-technical people will figure this out by themselves (or happen to find this GH issue).

This might be affecting a relatively large user base, since we're not really talking about _ancient_ OS versions, but ones (Debian 10, Ubuntu 20.04, probably others) that are still widely used and not EOL. (Also this version of Wayland seem to work just fine with non-Qt software.)

Of course, doing the fallback simply based on the gnome version might not take into account the possibility of future backported fix to this flicker issue, so it is not entirely reliable. OTOH perhaps it would not be too bad to fall back unnecessarily in that case.

**Comment by ilya-fedin** [comment]
Unfortunately, Qt provides no programmatic API to force xcb. Setting environment variable in the code would make that variable to leak to child processes. In other words, all Qt applications started by Telegram (when you e.g. click on a link or open some file) will be forced to use xcb, as well. I don't think this is a good solution. The only good solution is to report this to Qt so they revert the change.

**Comment by john-preston** [comment]
Ok, I've created a fresh Qt bug report, I hope they'll make some changes:

https://bugreports.qt.io/browse/QTBUG-99535

**Comment by mymedia2** [comment]
Gnome 3.30.2 which comes with Debian 10 (oldstable now) has been released 3.5 years ago. In those days, Wayland support was considered experimental. The same applies to Ubuntu 20.04 (latest LTS), where Wayland session is disabled by default.
If you encounter any bugs with old Wayland, either switch it off or update your system.

**Comment by Alexhhhc** [comment]
This issue can happen on gnome 41.2.I'm using archlinux and this problem also occurs to me.

**Comment by ilya-fedin** [comment]
You have flickering on gnome 41.2 just like @pabl0?

**Comment by Alexhhhc** [comment]
> You have flickering on gnome 41.2 just like @pabl0? Are you sure it's the same?

Yes exactly.Setting QT_QPA_PLATFORM=xcb fixes it and I'm quite sure it is because the latest version uses wayland as default.This introduced another issue #17260

**Comment by pabl0** [comment]
Wayland might have been considered experimental back when buster was released, but I believe it was still enabled by default: 

[Debian 10 release notes](https://www.debian.org/releases/buster/amd64/release-notes/ch-whats-new.en.html#wayland-by-default-on-gnome)

It's not an ideal situation, but it means that many users will experience this issue, and it is possible that a large portion of those don't even know what is the difference between X11 and Wayland, or which one their systems are running currently (the Linux GUI stack is not always easy to understand ever for experienced hackers). 

So, much thanks for taking the effort to report this to Qt folks and at least trying to solve this regression.

**Comment by ilya-fedin** [comment]
> This introduced another issue #17260

I don't quite understand how mac-specific issue is related to this

**Comment by ilya-fedin** [comment]
> Yes exactly.Setting QT_QPA_PLATFORM=xcb fixes it and I'm quite sure it is because the latest version uses wayland as default.

Can you say that at the Qt bug report then? Because everyone else is sure this was fixed long time ago and is not present in latest versions of GNOME, so they seem to consider this a non-blocker.

**Comment by Alexhhhc** [comment]
> 

Oh sorry,the number is wrong.The currect is #17026.
And #17022 is also related.
I could say that this issue is caused by "default using wayland in the new version" + #17022 + #17026

**Comment by ilya-fedin** [comment]
These ones aren't bug, it's just how Wayland works

**Comment by alekseymykhailov** [comment]
I have hidpi scaling (enabled by `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`) on Fedora 35/Gnome 41.2. To fix blurry telegram app UI I used `flatpak override --env=QT_QPA_PLATFORM=wayland org.telegram.desktop`. This "fix" does not work since most recent update to `3.4.3 (45deeb86)`. Rolling back  to previous version (`3.4.2 (e9adad97)`) using `lfatpak update --commit=45977570427e792ae027fad41f5a072628140fc5cc2d06099acfd6c638b62ec8  org.telegram.desktop && flatpak mask org.telegram.desktop`  fixes the issue
