### ISSUE TITLE
[Linux][Wayland] Context Menu Drawn Off-Screen

### ISSUE THREAD

**Issue by dshcherb** [telegramdesktop/tdesktop#17478]
### Steps to reproduce

1. Start Telegram desktop on Ubuntu 21.10 (Wayland session) and enlarge it to occupy the whole screen;
2. Right click on the lowest message in a chat window to invoke a context menu so that items in that menu will definitely not fit under the place of the click;
3. Observe that context menu items are not drawn upwards.

### Expected behaviour

The expected behavior is for context menu list items to be drawn upwards, not downwards off-screen.

![image](https://user-images.githubusercontent.com/12861810/147826910-5399d5df-4ca5-4f98-a08b-8489c3143fab.png)

```
➜  ~ grep VERSION= /etc/os-release
VERSION="20.04.3 LTS (Focal Fossa)"

➜  ~ printenv XDG_SESSION_TYPE  
x11

➜  ~ glxinfo | grep "OpenGL renderer"
OpenGL renderer string: llvmpipe (LLVM 12.0.0, 256 bits)
```

### Actual behaviour

![image](https://user-images.githubusercontent.com/12861810/147826244-d401a967-4f04-4f98-ab9a-6f4db7a08c8d.png)

Telegram Desktop `v3.4.1`.
![image](https://user-images.githubusercontent.com/12861810/147826320-e7c9fe40-7d48-48de-9ee2-7f70802bbf6b.png)

```
➜  ~ grep VERSION= /etc/os-release
VERSION="21.10 (Impish Indri)"

➜  ~ printenv XDG_SESSION_TYPE 
wayland

➜  ~ glxinfo | grep "OpenGL renderer"
OpenGL renderer string: AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.41.0, 5.13.0-22-generic, LLVM 12.0.1)
```

### Operating system

Ubuntu 21.10

### Version of Telegram Desktop

3.4.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Yeah, a Qt bug
https://bugreports.qt.io/browse/QTBUG-87303
https://bugreports.qt.io/browse/QTBUG-92200
https://bugreports.qt.io/browse/QTBUG-95637

**Comment by john-preston** [comment]
Ok, I've created a fresh Qt bug report, I hope they'll make some changes:

https://bugreports.qt.io/browse/QTBUG-99535

**Comment by dshcherb** [comment]
@john-preston 

Confirmed that this issue is no longer reproducible with `v3.4.3` (which has https://github.com/telegramdesktop/tdesktop/commit/102c0a96ed5cbc1288e1654b7e12811f1ea378b5) on Ubuntu 21.10.

Thanks a lot for the quick workaround!
