### ISSUE TITLE
[Feature Request] Add the option to globally disable Spoiler in the settings.

### ISSUE THREAD

**Issue by reiuyfan** [telegramdesktop/tdesktop#17475]
### Is your feature request related to a problem?

yes

### Describe the solution you'd like

When you want to view Spoiler messages, you need an extra click. This is not friendly. In fact, strikethrough is enough. Spoiler does not conform to the kiss philosophy to a certain extent, so I propose to add an option to the settings to disable it globally. and directly show Spoiler messages.
By the way, Spoiler broke the compatibility of lower versions and different clients that can show messages normally.

### Describe alternatives you've considered

Add the option to globally disable Spoiler in the settings.

**Comment by Aokromes** [comment]
i am quite sure this is a won't fix, because disabling it will defeat the purpose of spoiler.

**Comment by reiuyfan** [comment]
> i am quite sure this is a won't fix, because disabling it will defeat the purpose of spoiler.

And so that’s why it’s an option. This option is disabled by default, but those who don’t like Spoiler and know exactly what will happen can enable it instead of putting up with a lot of Spoiler.

**Comment by Neurotoxin001** [comment]
Try to suggest it here, because it's must be applied to all telegram apps:
https://bugs.telegram.org/

**Comment by reiuyfan** [comment]
> Try to suggest it here, because it's must be applied to all telegram apps: https://bugs.telegram.org/

A stupid question: How do I need to submit suggestions? I have logged in to my telegram account, but I can’t find an option like add my card

**Comment by Neurotoxin001** [comment]
Click on any card and there is 2 buttons:
![image](https://user-images.githubusercontent.com/39812401/147827551-d434926b-6a0e-4e8e-b752-36ff99c930c9.png)
