### ISSUE TITLE
Grey notification bubble displayed for archived+muted chats on system tray icon

### ISSUE THREAD

**Issue by morris-t** [telegramdesktop/tdesktop#17471]
### Steps to reproduce

1. Mute a chat.
2. Archive the muted chat. 
2. If that chat then receives messages, a grey notification bubble appears on the system tray icon, indicating the number of messages received.
 

### Expected behaviour

When a muted chat is archived, no notification bubble will be displayed on the system tray icon, when the chat receives messages.

If the user wishes to see new messages in the chat, they can look in archived chats.

### Actual behaviour

When a muted chat is archived, a grey notification bubble is displayed on the system tray icon, when the chat receives new messages.

This is a confusing user experience, as when the user opens the app, they may well see none of their un-archived chats have notifications and may not realise the the notifications have come from archived chats.

### Operating system

Windows 10 Pro 21H1

### Version of Telegram Desktop

3.3 X64

### Installation source

Microsoft Store

**Comment by GuglielmoFelici** [comment]
I agree with this, it should not display any notification.

**Comment by ilya-fedin** [comment]
Settings -> Notifications -> Include muted chats in unread count

**Comment by morris-t** [comment]
> Settings -> Notifications -> Include muted chats in unread count

I have "Include muted chats in unread count" set to off currently as a workaround, however this means I miss the grey bubble notification for un-archived muted chats, which I would like to see.

Ideally the badge functionality would be changed so that muted archived chats never showed a badge.  So "Include muted chats in unread count" only applied non-archived chats.
