### ISSUE TITLE
Better reactions element alignment

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#17474]
### Steps to reproduce

1. Open latest Telegram Desktop.
2. Go to any channel with enabled reactions

### Expected behaviour

Reactions should be displayed on the same line with views count and date:
![Telegrams reactions alignment (better version)](https://user-images.githubusercontent.com/7080928/147824005-10e4a91d-21d5-4b6d-a0cf-b18c530d26b9.png)

Or even reactions count should be on the same line:
![Telegrams reactions alignment (better+1 version)](https://user-images.githubusercontent.com/7080928/147824420-1afd0156-dfa6-417e-ae7f-0aba5038038e.png)

### Actual behaviour

Reactions element seems to be displayed 2 pixels higher:
![Telegrams reactions alignment (original)](https://user-images.githubusercontent.com/7080928/147824077-76129a17-8ca3-4983-b18f-a84fda9a4a20.png)

### Operating system

Windows

### Version of Telegram Desktop

3.4.1

### Installation source

Static binary from official website

**Comment by PeterNjeim** [comment]
I'm pretty sure they've been designed to have larger margins than the text on the right., to try to make its distance between the text above it and the bottom of the message be the same. Don't think this is a bug, but I may be wrong.
