### ISSUE TITLE
Part of menu is not showing after right click

### ISSUE THREAD

**Issue by mostafaznv** [telegramdesktop/tdesktop#17476]
### Steps to reproduce

1. Move telegram window to bottom side of monitor
2. Right click on a message
3. Part of menu is hidden

![photo_2021-12-31_17-07-12](https://user-images.githubusercontent.com/7619687/147826316-367aa6dc-1b31-43ce-af93-232a776ab614.jpg)

### Expected behaviour

Menu should open from bottom to up and should be visible completely

### Actual behaviour

Part of menu is hidden

### Operating system

Uubuntu 21.10

### Version of Telegram Desktop

3.4.1

### Installation source

Snap

**Comment by mostafaznv** [comment]
another report 
#17478

**Comment by john-preston** [comment]
Ok, I've created a fresh Qt bug report, I hope they'll make some changes:

https://bugreports.qt.io/browse/QTBUG-99535
