### ISSUE TITLE
Size and color of cursor is different from ubuntu's default size and color

### ISSUE THREAD

**Issue by mostafaznv** [telegramdesktop/tdesktop#17477]
### Steps to reproduce

1. mouse move on all parts of telegram window
2. cursor is larger than default.

**Default**:
![photo_2021-12-31_17-20-15](https://user-images.githubusercontent.com/7619687/147826623-8f9c7a36-fe5a-4c7f-9aec-8753e585fd88.jpg)

-------

**Telegram**:
![photo_2021-12-31_17-20-11](https://user-images.githubusercontent.com/7619687/147826619-fe32492b-34ea-4ebb-9951-92dad24d05d7.jpg)

![photo_2021-12-31_17-20-07](https://user-images.githubusercontent.com/7619687/147826617-9a37affe-7d46-48f5-a792-508e86b631b8.jpg)

![photo_2021-12-31_17-20-00](https://user-images.githubusercontent.com/7619687/147826614-f1d7feac-9976-4622-aaf9-699f9d3cac32.jpg)

### Expected behaviour

Display just like default. smaller and in black

### Actual behaviour

Size is very large and color is in white

### Operating system

Uubuntu 21.10

### Version of Telegram Desktop

3.4.1

### Installation source

Snap

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/17457

**Comment by john-preston** [comment]
Ok, I've created a fresh Qt bug report, I hope they'll make some changes:

https://bugreports.qt.io/browse/QTBUG-99535
