### ISSUE TITLE
The "UPDATE TELEGRAM" button covers the proxy indicator and the reconnect button

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#17479]
### Steps to reproduce

1. Enable some SOCKS5 proxy.
2. Wait until an update becomes available.
3. Put the proxy offline for a long time.

### Expected behaviour

The proxy indicator and the reconnect button are shown above the "UPDATE TELEGRAM" button.

### Actual behaviour

The "UPDATE TELEGRAM" button covers the proxy indicator and the reconnect button.

### Operating system

Debian 12

### Version of Telegram Desktop

3.3.1 beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Perhaps Updating is more important than reconnect, since maybe the connection issues are fixed in the update 🤔

**Comment by bodqhrohro** [comment]
> maybe the connection issues are fixed in the update

How should they be, if the network or the proxy itself were down?

> Updating is more important

Updating is a slow process, especially on HDD, and an update has a chance of breaking things rather than fixing them. If a user is in a hurry, it's undesirable, and that's also the case when pressing the reconnect button manually instead of just waiting through the reconnect interval makes more sense than usual.

If you think updating ASAP is important, what's the purpose of the button at all? just mandatorily restart in the midst of the work, like Windows does xDDDDDD

**Comment by bodqhrohro** [comment]
Oh, nevermind, I ran into a much more brilliant UI. This is the official Ukrainian laws website:
![2022-02-22-210644_1366x768_scrot](https://user-images.githubusercontent.com/2134486/155202058-12bd5eb4-dd3f-444f-b79f-ca70d18cffb2.png)
So your approach is not the worst in the world, at least! Gotta even become a trend soon!

**Comment by bodqhrohro** [comment]
Probably still relevant.

**Comment by bodqhrohro** [comment]
Yup, still relevant for sure, 4.3.
