### ISSUE TITLE
Telegram deletes all files from download path regardless of what program saved the file

### ISSUE THREAD

**Issue by Sopor** [telegramdesktop/tdesktop#17484]
### Steps to reproduce

I have a common download directory i use for all my programs including Telegram.
I was looking around in the settings and i found, `Clear files older than: Never`.
I thought this was too much so i lower it and pressed OK.
When i now looked in my download directory 70% of my files/directories was deleted from my download directory 😢

I use this folder to store newly and ongoing project and Telegram deleted almost the whole directory. I have never seen this happen since i started with computers back in the 80s.

### Expected behaviour

It seems that Telegram delete files by date without even warn me that all files older than X will be deleted and regardless of which program that has saved the file.

### Actual behaviour

Telegram should only delete files it has downloaded or at least show a big big warning that it will delete all files older than X days, even files that other programs have downloaded or you have manually copied to the directory.

### Operating system

Windows 10 version 1909 x64

### Version of Telegram Desktop

3.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Where did you choose "Clear files older than"? I remember only the setting about media cache being cleared, not the downloaded files. No downloaded files are deleted by Telegram Desktop, including its own.

**Comment by Sopor** [comment]
![image](https://user-images.githubusercontent.com/5789283/147863515-a3bab536-ce69-4b95-8231-b7e0e8fa191f.png)

![image](https://user-images.githubusercontent.com/5789283/147863517-88ed7d2f-a3b3-4c65-ae1b-e2489909350e.png)

![image](https://user-images.githubusercontent.com/5789283/147863523-053b9508-2aab-4f26-b594-a3bb44720889.png)

So, when i changed it from `Never` to `1 week` all files and folders in my download path older than 1 week was deleted.

**Comment by GregorKopka** [comment]
As a data point: I have the Download Path in 'advanced' set to `Default folder`, which translates to a `%userprofile%\Downloads\Telegram Desktop`. `Clear Files older than` is set at 1 Month, `%userprofile%\Downloads` and the `Telegram Desktop` folder within contain files dating back to 2020.

Telegram is set to auto-update, currently at **3.4.2**, so it should have hit me - which did not happen. Was also unable to trigger it by changing the `Clear Files older than` slider. 

Can not reproduce.

**Comment by Aokromes** [comment]
yeah what it deletes is 
AppData\Roaming\Telegram\tdata\user_data\cache

**Comment by john-preston** [comment]
@sopor this setting only relates to the specified local cache of media items that are auto downloaded, they're stored in an encrypted form in the app folder. No user-facing files are deleted using this setting, also this setting reads dates from this encrypted cache database, it doesn't look on file creation or modification time. I think something different happened in your case.

**Comment by Sopor** [comment]
I haven't test it on my computer it happened on (i don't want to lose my files again), but i'm unable to reproduce it on another computer.

I'm 100 percent sure it was Telegram that deleted almost all my files. I was changing the settings in Telegram to 12 month when i saw my files/directories disappear and i could see that all files/directories older than 12 month was deleted.
Maybe it was a bug in that specific version i was running? I run the portable version of Telegram.

I manage to get 95% of the files back again, though.

Nothing more to do if it isn't there anymore.

Thanks for your help!

**Comment by john-preston** [comment]
@Sopor I'm 100% (ok, 99%) sure tdesktop couldn't do it. There is nothing in the source code I can think of that could produce such behavior and never was.

**Comment by Sopor** [comment]
There must be some delete function as it can empty the folder on logout and uninstall
![image](https://user-images.githubusercontent.com/5789283/147964953-37cda708-3820-4c37-ac7a-7ece4fc1e870.png)

I don't run any other cleaning program and as i explained before. All files older than 12 month was deleted. The same value i selected in Telegram.

**Comment by Aokromes** [comment]
i have that setting enabled, and ofc to a diferent folder than cache one and never got any file deleted.

**Comment by Sopor** [comment]
@john-preston I have heard that before that there is nothing in the code that could do this 😉

It can clear the cache, so it is possible something got wrong and instead it deleted the files in the download path?
