### ISSUE TITLE
make an option to hide the "reactions element" button popping on every message read

### ISSUE THREAD

**Issue by ITL71** [telegramdesktop/tdesktop#17487]
### Is your feature request related to a problem?

This is super annoying. 

please find a  solution for that. 

### Describe the solution you'd like

On the settings page, there will be an option to hide the popping button.

### Describe alternatives you've considered

likes that were given will be still presented but the button won't pop on every message.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/17461
