### ISSUE TITLE
Debian 10 Screen flickering 

### ISSUE THREAD

**Issue by JamJarChris** [telegramdesktop/tdesktop#17481]
Recently accepted latest updates from Debian, and Telegram Desktop for Linux pretty difficult to use.
Please see attached screen recording. 
I searched and found similar issues before which have been closed now.
If you need any more info about my set up please let me know.
Thanks.

https://user-images.githubusercontent.com/62396337/147834202-3b671853-98ec-47a7-908b-a287251435c3.mp4

**Comment by ilya-fedin** [comment]
#17468

**Comment by JamJarChris** [comment]
Thank you - how did I not see this report? Doh.

**Comment by john-preston** [comment]
Ok, I've created a fresh Qt bug report, I hope they'll make some changes:

https://bugreports.qt.io/browse/QTBUG-99535
