### ISSUE TITLE
[Question] Suggestion about reactions button position

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#17482]
https://github.com/telegramdesktop/tdesktop/commit/3dac08d34ff10f89bd06b1a6621e00eeb022e38b

This is still awful and even don't have shadow:
![image](https://user-images.githubusercontent.com/39812401/147837368-60b5297b-6114-410b-aa7c-2f70a43d4459.png)
![image](https://user-images.githubusercontent.com/39812401/147837371-90b51c2d-aec5-4cce-949a-6bf58fe70016.png)

Can you please ask Telegram designers to think where it can be placed in a better way?

Or implement it somehow differently. Like on iOS for example, by long tap (click) or by showing reactions in right click menu.

Also in reactions list we don't have scroll bar to make it easier to see:
![image](https://user-images.githubusercontent.com/39812401/147837421-a43cd9a5-084c-485d-b6d1-f5cce01eeabc.png)

And we don't have "fast reaction" feature from iOS (by double tap on post):
<details>

![image](https://user-images.githubusercontent.com/39812401/147837480-d2e5705d-e259-4ad7-b0db-4359b88c5f93.png)

</details>

**Comment by Neurotoxin001** [comment]
This is how it's done in viber

![image](https://user-images.githubusercontent.com/39812401/147846284-50d2c58b-8d50-4ba5-bd83-9e4eb50195ca.png)

**Comment by Aokromes** [comment]
maybe put it on top right for others top left for own? (i still don't see the point of allow to reaction own messages but oh well) xd

**Comment by john-preston** [comment]
This IS the fast reaction :) double click is taken by the reply feature, not planned to use it for reactions on desktop.

**Comment by not-holar** [comment]
Above / below the forward button (or next to it if the message is a one-liner) would be a good spot. The current long-hover doesn't feel like good ux at all

**Comment by harshil21** [comment]
> This IS the fast reaction :) double click is taken by the reply feature, not planned to use it for reactions on desktop.

Is it possible to assign double click for reactions in channels where you're only a subscriber / in groups where you can't send messages?

**Comment by not-holar** [comment]
Or let people reassign it altogether, there's a dedicated reply button on every message, a lot of people probably never use the double-click anyway

**Comment by john-preston** [comment]
@not-holar This is planned later.
