### ISSUE TITLE
Last time Telegram Desktop was not closed properly.

### ISSUE THREAD

**Issue by rappsi** [telegramdesktop/tdesktop#1748]
I have installed Telegram Desktop version 0.9.28 on Windows 7 x64 in the Folder %progrm files%. Everytime i reboot my computer i get this Error and Telegram dosn't start. I have to start it manualy.

I have tryed to switching "Auto-Updates" on and off and i tryed to delete "Updater.exe" but nothing changed.

![telegram desktop error](https://cloud.githubusercontent.com/assets/9280727/13631267/0daf17b6-e5e4-11e5-9695-97174dc39698.png)

**Comment by telegramdesktop** [comment]
@rappsi Can you please install the dev version from the bottom of https://desktop.telegram.org/#dev-version and do the same? It should suggest you to send a crash report, please send it and copy your "Crash Report Tag" here (from the report window).

**Comment by rappsi** [comment]
I have installed the dev-version and until now no more error message.
