### ISSUE TITLE
Mouse cursors different from users preferences

### ISSUE THREAD

**Issue by zehrique** [telegramdesktop/tdesktop#17498]
### Steps to reproduce

Just install the version 3.4.2 on GNOME 3.38.5 on Debian 11 with customized mouse cursors.

### Expected behaviour

Telegram should follow GNOME's system-wide mouse configuration.

### Actual behaviour

Telegram seems to default to the GNOME's mouse cursors.

### Operating system

Debian GNU/Linux 11 (bullseye)

### Version of Telegram Desktop

3.4.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Telegram shouldn't read GNOEM coniguration, it's GNOEM who should set configuration for other toolkits

**Comment by john-preston** [comment]
Ok, I've created a fresh Qt bug report, I hope they'll make some changes:

https://bugreports.qt.io/browse/QTBUG-99535
