### ISSUE TITLE
Impossible to switch to native title bar on Fedora 35 Flatpak version

### ISSUE THREAD

**Issue by WhiteCzar** [telegramdesktop/tdesktop#17491]
### Steps to reproduce

1. Fedora 35
2. Flatpak Telegram
3. Can't change the title bar to native in the settings

### Expected behaviour

It used to be possible to enable native title bar in Gnome. A very useful option. The original Telegram title bar is ugly, stands out too much on Gnome DE, and impossible to use with a touchscreen (too narrow).

### Actual behaviour

There's no such option in the Settings.

### Operating system

Fedora GNU/Linux 35

### Version of Telegram Desktop

3.4.2

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
tdesktop 3.3.1+ uses Qt 6.2.2 that defaults to Wayland and GNOEM on Wayland [doesn't support native titlebar](https://gitlab.gnome.org/GNOME/mutter/-/issues/217). You can't enable something doesn't exist.

**Comment by WhiteCzar** [comment]
Oh so the issue is Wayland. I read that issue on Gnome Gitlab. Very unfortunate.
