### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by carlson-a-r** [telegramdesktop/tdesktop#17499]
Hello, Might be a feature re-request. 

Telegram Desktop 8.4 on macOS no longer has the option to view post history of a single person on the right click menu. Is there a hotkey equivalent that still exists? If not, can this feature be added back in? It's quite helpful for moderating a larger group, and was al to quicker than going through the standard search function w/contact set.

Thank you.

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
