### ISSUE TITLE
docker prepare libraries script failed

### ISSUE THREAD

**Issue by x09** [telegramdesktop/tdesktop#17492]
### Steps to reproduce

on step 139 
```
docker build -t tdesktop:centos_env Telegram/build/docker/centos_env/
......
Step 139/492 : RUN git clone -b 0.4.0 --depth=1 --recursive https://gitlab.freedesktop.org/xorg/lib/libxcb-util.git
 ---> Running in 80fc4cb9c8c8
Cloning into 'libxcb-util'...
fatal: unable to access 'https://gitlab.freedesktop.org/xorg/lib/libxcb-util.git/': The requested URL returned error: 504

```
and nothing.. 

### Expected behaviour

work

### Actual behaviour

failed

### Operating system

linux

### Version of Telegram Desktop

last 3.4.2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Apparently, the git server where this library hosted is unreachable right now ¯\_(ツ)_/¯

**Comment by x09** [comment]
> Apparently, the git server where this library hosted is unreachable right now ¯_(ツ)_/¯

No,
```
git clone -b 0.4.0 --depth=1 --recursive https://gitlab.freedesktop.org/xorg/lib/libxcb-util.git.
Cloning into 'libxcb-util.git.'...
fatal: unable to update url base from redirection:
  asked for: https://gitlab.freedesktop.org/xorg/lib/libxcb-util.git./info/refs?service=git-upload-pack
   redirect: https://gitlab.freedesktop.org/users/sign_in
```

**Comment by ilya-fedin** [comment]
you have a dot after the URL, it doesn't present in the script

**Comment by x09** [comment]
OK,
but

git clone --recursive https://gitlab.freedesktop.org/xorg/lib/libxcb-util.git
work

git clone -b 0.4.0 --recursive https://gitlab.freedesktop.org/xorg/lib/libxcb-util.git
not work

**Comment by ilya-fedin** [comment]
It works for me just fine right now

**Comment by x09** [comment]
gitlab.freedesktop.org problems..

https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/407

**Comment by john-preston** [comment]
I've updated the image to use github mirrors instead.
