### ISSUE TITLE
Emoji/Stickers/GIFs overlay sometimes is misplaces & resized

### ISSUE THREAD

**Issue by ratijas** [telegramdesktop/tdesktop#17495]
### Steps to reproduce

Exact steps are unknown. Sometimes it happens at runtime, after a while during normal usage of Telegram Desktop. It seems to break on a per-peer basis, but that's not consistent either.

Additional information, although probably irrelevant: My KWin and Telegram are set to have no window decoration whatsoever (Telegram Desktop believes it has server-side decorations, but KWin has a rule to turn them forcefully off).

### Expected behaviour

Overlay panel should be normally sized, and positioned right above the message input field. There should be no gap pixels between emoji "button" and the overlay that shows up on that button's mouse hover.

### Actual behaviour

https://user-images.githubusercontent.com/6737986/147879713-b64b67be-9463-4e01-978b-f2e28337f3af.mp4

### Operating system

Arch Linux, KDE/Plasma/X11

### Version of Telegram Desktop

3.3.0-1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Can you install latest version from official source?

**Comment by ratijas** [comment]
I have just upgraded Arch Linux to the latest 3.4.2, let's wait and see if the bug will trigger itself again. Not sure a source of build really matters here, but I sure can do it too.

**Comment by ilya-fedin** [comment]
It matters, official builds have patched Qt with fixes for bugs tdesktop encounter in Qt

**Comment by ratijas** [comment]
Oh, riiight… sounds pretty cursed for distros :-\

I will check it.
