### ISSUE TITLE
Not synced chats/accounts issue with iOS Telegram (official)

### ISSUE THREAD

**Issue by romx** [telegramdesktop/tdesktop#175]
I've used two different iOS device with Telegram (official client) on iPad and iPhone, These clients completely synced, one to another. My contacts same on both devices, my chat history updates in sync at both and everything is OK.
I've used unofficial Telegram messenger as an App for Chrome browser too, and everything was OK for all three clients together.

Unfortunately my Telegram Desktop application, logged in with the same phone number looks like a different account.
Other side client see me like a new person. It lost avatar pic, chat history sync, etc.
I'm using the same phone number for authorization by SMS code.

This is my side Telegram Desktop view:
![telegram-issue-01](https://cloud.githubusercontent.com/assets/5270139/4410096/6eec3192-44e3-11e4-8b5e-eb7070c3281b.png)

This is Telegram iOS view from "other side" of chat:
![telegram-issue-02](https://cloud.githubusercontent.com/assets/5270139/4410097/6f294f82-44e3-11e4-8ab1-a79d29928b2d.jpg)

This is my "original" Telegram view (official, iOS, for iPad)
![telegram-issue-03](https://cloud.githubusercontent.com/assets/5270139/4410220/4ff51d98-44e4-11e4-9450-99cb856567f5.png)

Actually it's so strange behaviour, so I've many troubles to explain it clearly.
I try to explain it as I see this issues, but don't hesitate to ask me about needed detail. I hope solving this issue will help to make Telegram Desktop perfect. Thank you for your job.

**Comment by auchri** [comment]
Is this still the case? If yes, reopen the issue
