### ISSUE TITLE
Worse interface scaling options after the update.

### ISSUE THREAD

**Issue by w1png** [telegramdesktop/tdesktop#17500]
### Steps to reproduce

1. Update to v3.4.2

### Expected behaviour

The interface scale options were (if I remember correctly) 100, 125, 150, 175, 200. This scale range has a better viewability than the new one (200, 220, 240, 260, 280, 300).

### Actual behaviour

The interface scale options are too high (200, 220, 240, 260, 280, 300).

### Operating system

OS: Arch Linux x86_64 | Kernel: 5.10.88-2-lts | DE: Gnome 41.2

### Version of Telegram Desktop

v3.4.2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Apparently you're using Wayland with 2x scale, that means you can't scale less than 200%

**Comment by w1png** [comment]
But It used to work perfectly before the update. Guess I will have to deal with it from now on :(

**Comment by ilya-fedin** [comment]
It was using X11

**Comment by Leny1996** [comment]
Why it's closed? I've the same issue using 156.25% scaling on X11.

**Comment by Aokromes** [comment]
> Why it's closed? I've the same issue using 156.25% scaling on X11.

try 3.4.3

**Comment by ilya-fedin** [comment]
> Why it's closed? I've the same issue using 156.25% scaling on X11.

What are you talking about? There's no such option like 156.25% in tdesktop

**Comment by Leny1996** [comment]
@ilya-fedin fractional scaling on X11, in tdesktop it's just 150%

**Comment by ilya-fedin** [comment]
I don't quite understand what do you mean...

**Comment by Leny1996** [comment]
@ilya-fedin it's global scaling on X11. Not sure if the same issue exists on Wayland. Telegram automatically selects correct scaling option on previous version. Will check on 3.4.3 when it will be available.

**Comment by ilya-fedin** [comment]
Can you describe this in more details? Because it sounds like you assume everyone knows what happens on your PC. I don't understand what the problem is for you.

**Comment by Leny1996** [comment]
Okay, maybe @w1png issue is not the same, but I think it's connected.
My setup:
```
OS: Arch Linux x86_64
Kernel: 5.15.12-arch1-1
DE: Plasma 5.23.4
WM: KWin
```
![image](https://user-images.githubusercontent.com/8152038/147980327-c810774e-9e6c-4f0a-a756-e869f3243e33.png)

Before update to 3.4.2:
![image](https://user-images.githubusercontent.com/8152038/147980161-4e0da014-9cbc-4c64-bada-3c4f4a9e999a.png)
Everything is sharp and no visual glitches.

After update to 3.4.2:
![image](https://user-images.githubusercontent.com/8152038/147980443-e3440228-9d4c-490f-a9a7-b15ce819c920.png)
Visual glitch on message input, "read indicator" is blurred.

When using 3.4.1:
default scale is automatically selected to 150%. On 3.4.2:
![image](https://user-images.githubusercontent.com/8152038/147980611-cf100b3b-ffd1-4eb2-9112-47fe1b735f0f.png)
blurred icons, weird glitched line

**Comment by ilya-fedin** [comment]
I guess you're using a distro package, apparently it has Qt built with high DPI scaling support. Unfortunately, tdesktop doesn't support that, you can switch to official builds that have Qt with disabled high DPI scaling support.

**Comment by w1png** [comment]
I would recommend disabling the unusual highDPI values because they are really bad on linux for now. Just stick with 100%/150%/200% @Leny1996

**Comment by Leny1996** [comment]
Yes, I'm using community repo - never changed package. If I downgrade to 3.4.1 everything looks great.
![image](https://user-images.githubusercontent.com/8152038/147981074-00645221-e09f-4e86-a9d3-730e4764f422.png)
As you can see, only community package is the highest version available.

**Comment by ilya-fedin** [comment]
I can't suggest anything other than to migrate to official builds that don't have this problem

**Comment by Leny1996** [comment]
@w1png yea, mixed DPI is a pain in the ass on linux, I regret buying 4K Monitor... Changed global scaling to 150%, no visual glitches, but still all of icons are blurred.
Looking at https://archlinux.org/packages/community/x86_64/telegram-desktop/ it says official. So it's build problem? I see it's using Qt6, maybe 3.4.1 was build using Qt5?

**Comment by ilya-fedin** [comment]
Official for who? Apparently, it's official for arch linux, but it's definitely not official for Telegram

**Comment by Leny1996** [comment]
Okay, I will try to report issue on archlinux package, maybe change to Qt6 build messed something. I can live with blurred icons for now.
Thanks :)

**Comment by Aokromes** [comment]
> Okay, I will try to report issue on archlinux package, maybe change to Qt6 build messed something. I can live with blurred icons for now. Thanks :)

i suggest you to use official package downloaded from desktop.telegram.org

**Comment by ilya-fedin** [comment]
I created a Qt bug report, maybe they will fix this disabling HighDPI scaling won't be needed
https://bugreports.qt.io/browse/QTBUG-99546
