### ISSUE TITLE
[bug] Messages lost layout

### ISSUE THREAD

**Issue by cisarpavel** [telegramdesktop/tdesktop#1750]
If app is fullscreen, all messages got sticked on the left instead of standard layout my messages on the right, another person messages on the left.

Linux Mint / Ubuntu 14.04. x64

Pavel Cisar

**Comment by diazbastian** [comment]
@cisarpavel This is a design feature and was much discussed in the past. In resolutions higher than 1366x768 messages design changes. You can change the previous design with an option that appears in Telegram Desktop config.

**Comment by auchri** [comment]
See #1666 and #1587
