### ISSUE TITLE
Right click not working on message when Window maximized

### ISSUE THREAD

**Issue by fulopm** [telegramdesktop/tdesktop#17503]
### Steps to reproduce

1. Maximize Telegram window, by double clicking on the title bar
2. Right click on a message (either in a group or one-to-one chat)

### Expected behaviour

A context menu should appear, just like in downsized mode, where I can reply, forward etc. the clicked message

### Actual behaviour

Nothing happens when I right click on a message.

### Operating system

Fedora 35, Gnome 41.2

### Version of Telegram Desktop

3.4.2

### Installation source

Flatpak

### Logs

```shell
Nothing gets logged that can be connected to the issue.
```

**Comment by ilya-fedin** [comment]
Wayland? Can you reproduce with X11?

**Comment by fulopm** [comment]
Yeah, it's Wayland. Tried to reproduce with X11, I couldn't.

**Comment by john-preston** [comment]
@fulopm Should be fixed in 3.4.3 (by defaulting to XWayland on GNOME again).
