### ISSUE TITLE
no notification for reactions

### ISSUE THREAD

**Issue by eworm-de** [telegramdesktop/tdesktop#17505]
### Steps to reproduce

1. receive a reaction to one of your messages

### Expected behaviour

A desktop notification should be shown. (The Android app does notify.)

### Actual behaviour

The reaction is visible in chat, but no notification is shown.

### Operating system

Arch Linux x86_64 with Xfce

### Version of Telegram Desktop

3.4.2

### Installation source

Other (unofficial) source

**Comment by eworm-de** [comment]
Looks like this has been fixed... Currently running version 3.5.0, that does show notifications for reactions.
Thanks!

**Comment by kirsan31** [comment]
Yea but _seeing_ them on TD - will not dismiss notification on other devises...
