### ISSUE TITLE
Interface scale - disappeard scale factors belos 200%

### ISSUE THREAD

**Issue by alpiua** [telegramdesktop/tdesktop#17518]
### Steps to reproduce

Install recent update 3.4.3 with pacman
Restart Telegram-desktop

### Expected behaviour

I beleive I should see the scale factors starting from 100% as it was before update

### Actual behaviour

freaky scaled

![2022-01-06_00-51](https://user-images.githubusercontent.com/14225967/148301011-e1f99b8a-10ba-4ca3-aa8a-08ff22d44c06.png)

### Operating system

Arch Linux, i3-gaps, qhd screen

### Version of Telegram Desktop

3.4.3

### Installation source

Other (unofficial) source

**Comment by alpiua** [comment]
for now I installed telegram-desktop-bin from AUR and it working well
![image](https://user-images.githubusercontent.com/14225967/148304258-cdb21293-50ca-4c8c-91c6-9fd02df61d65.png)

**Comment by ilya-fedin** [comment]
Check Qt environment variables in your environment. If there are any variables enabling scaling, tdesktop will not be able to scale less than Qt scale factor.

**Comment by OJFord** [comment]
I have `QT_AUTO_SCREEN_SCALE_FACTOR=1`, and haven't changed that - all that changed was updating Telegram, and then the new higher scale took effect on restart.

It defaulted to 300%; 200% is a bit better, but still bigger & worse-looking than it was before.

**Comment by ilya-fedin** [comment]
> all that changed was updating Telegram, and then the new higher scale took effect on restart.

Yeah, now Telegram uses Qt 6 and the scaling works in another way. If you want to choose scaling less than 200%, you should remove `QT_AUTO_SCREEN_SCALE_FACTOR=1` and set `QT_ENABLE_HIGHDPI_SCALING=0` in order to disable Qt scaling

**Comment by OJFord** [comment]
@ilya-fedin Is this a limitation of Qt? From a user's perspective it seems like an odd & arbitrarily restricted set of choices.

**Comment by ilya-fedin** [comment]
> Is this a limitation of Qt?

No. The interface scale option configures tdesktop's own scale engine. Its scaling applied on top of Qt scaling (official builds have Qt built without HiDPI scaling support, though). The minimum scale percent tdesktop's scaling engine supports is 75% (what would be 150% with Qt scale factor = 2).
