### ISSUE TITLE
weird pixellous scaling with kde xorg 

### ISSUE THREAD

**Issue by andrew-ld** [telegramdesktop/tdesktop#17517]
### Steps to reproduce

1. install the latest stable version (3.4.3)
2. enable kde scaling to 175% (useful if you have a 4k screen)
3. magic

attached a screenshot of the problem, they are not artifacts caused by image compression, it really looks like that.
![Screenshot_20220105_225432](https://user-images.githubusercontent.com/43882924/148295115-ad30958d-99ce-4ca4-9ce6-645cdcb0a521.png)

### Expected behaviour

it should show up without artifacts or pixelation even using scaling, on previous releases it didn't happen.

### Actual behaviour

weird pixellous

### Operating system

archlinux, kde 5.23.5

### Version of Telegram Desktop

3.4.3

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
tdesktop is not capable of Qt's fractional scaling, unfortunately. You have to disable it. :(

**Comment by ilya-fedin** [comment]
See #17173 for the previous discussion
