### ISSUE TITLE
Telegram run on Xwayland only after update to version 3.4.3 in arch linux

### ISSUE THREAD

**Issue by Crandel** [telegramdesktop/tdesktop#17512]
### Steps to reproduce

Run telegram with QT_QPA_PLATFORM=wayland on swaywm

### Expected behaviour

Run as wayland native window as it runs before

### Actual behaviour

Run only in Xwayland

### Operating system

Arch linux

### Version of Telegram Desktop

3.4.3

### Installation source

Other (unofficial) source

### Logs

```shell
telegram-desktop

(telegram-desktop:11968): Telegram-WARNING **: 23:58:43.337: Application was built without embedded fonts, this may lead to font issues.
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
```

**Comment by Aokromes** [comment]
not a bug.
https://github.com/telegramdesktop/tdesktop/commit/102c0a96ed5cbc1288e1654b7e12811f1ea378b5

**Comment by ilya-fedin** [comment]
:thinking: Telegram forces XWayland, but only on GNOEM, due to very bad experience. Are you by any chance have GNOME set in XDG_CURRENT_DESKTOP? If you want to run Telegram with native Wayland, you should remove that or Telegram (legitimately) would think you're on GNOEM and force XWayland.

**Comment by Crandel** [comment]
@ilya-fedin 
```
XDG_CURRENT_DESKTOP=sway
GNOME_DESKTOP_SESSION_ID=1
```

**Comment by Crandel** [comment]
unset `GNOME_DESKTOP_SESSION_ID=1` fixed this issue. Thank you @ilya-fedin

**Comment by lilydjwg** [comment]
This affected me because I used to set `GNOME_DESKTOP_SESSION_ID=0` and then `XDG_CURRENT_DESKTOP=gnome` to make telegram use GTK's file dialog. I switched to set `XDG_CURRENT_DESKTOP=xfce` and it's working. (My desktop is mostly GTK's program and the Qt file dialog looks old-fashioned and lacks functionality.)

**Comment by ilya-fedin** [comment]
You can use QT_QPA_PLATFORMTHEME=gtk3 instead

**Comment by lilydjwg** [comment]
On Thu, Jan 06, 2022 at 10:41:42AM -0800, ilya-fedin wrote:
> You can use `QT_QPA_PLATFORMTHEME=gtk3` instead

Great, thanks!
