### ISSUE TITLE
apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/sys/firmware/efi/efivars/SecureBoot...

### ISSUE THREAD

**Issue by tosiara** [telegramdesktop/tdesktop#17515]
### Steps to reproduce

1. Install Telegram 3.4.3 from Snap store
2. Launch
3. AppArmor blocks access to `/sys/firmware/efi/efivars/SecureBoot...`

### Expected behaviour

Telegram Desktop messenger tries to access `/sys/firmware/efi/efivars/SecureBoot...`

### Actual behaviour

Why would ever Telegram need to access `/sys/firmware/efi/efivars/SecureBoot`?
This rises security concerns

### Operating system

Ubuntu 20

### Version of Telegram Desktop

3.4.3

### Installation source

Snap

**Comment by ilya-fedin** [comment]
You can check tdesktop source and find it doesn't have such code. Whatever is accessing it, it's not tdesktop itself.

**Comment by tosiara** [comment]
If it's not in the code - then it may be a dependency library. Or, at the end, the build machine may have been compromised

So far I see this:

```
/snap/telegram-desktop/3544$ grep efivar * -r
Binary file bin/systemctl matches
Binary file usr/bin/bootctl matches
Binary file usr/bin/systemd-analyze matches
Binary file usr/lib/systemd/boot/efi/linuxx64.efi.stub matches
Binary file usr/lib/systemd/boot/efi/systemd-bootx64.efi matches
Binary file usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.6400.6 matches
```

**Comment by ilya-fedin** [comment]
> If it's not in the code - then it may be a dependency library.

That's possible.
