### ISSUE TITLE
Copying media does not work

### ISSUE THREAD

**Issue by RLst** [telegramdesktop/tdesktop#17519]
### Steps to reproduce

1. Right click an image or video
2. Select "Copy Media"
3. Cmd + V does not paste the media into an appropriate application

### Expected behaviour

You should be able to copy media and then be able to paste it anywhere the appropriate media can be pasted.

### Actual behaviour

Copy Media function does nothing so when you go to paste it nothing gets pasted. 
You have to save the media then load it in instead.

### Operating system

MacOS 11.4

### Version of Telegram Desktop

8.4.1 (225801)

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
