### ISSUE TITLE
[Question] "View profile" option under context menu of users

### ISSUE THREAD

**Issue by 0x416c69** [telegramdesktop/tdesktop#17516]
In the more recent versions I noticed that the "View profile" option was deleted from the context menu.
It was such a nice feature which enabled us to view the user's profile without actually seeing the user's message and it was a lot better than adding several more buttons in the context menu to make up for it. Can we get it back?

![2022-01-05_11-01-50-PM](https://user-images.githubusercontent.com/10671711/148277489-f3fa2640-bc93-4893-89ae-0cf7fb11cee6.png)

**Comment by Aokromes** [comment]
click on avatar or title bar of conversation.

**Comment by 0x416c69** [comment]
> click on avatar or title bar of conversation.

That goes straight into the message. If this is the expected behavior does this mean that this is a bug? I'm using the latest version and I'm on the beta channel.

**Comment by mustafa519** [comment]
I am surprised too when it has disappeared after the latest update. Now, I have to read the conversation to see the profile section. This kind of details have made telegram the best. May I know the reason why that has changed?

**Comment by Remu-rin** [comment]
Same for channels and groups. This allowed to check shared media, description, members without opening chat. Please add it back.

**Comment by TryV** [comment]
I was also looking for it recently, please return it back,

**Comment by parhamapk** [comment]
This feature was very effective, especially when an anonymous person was sending a message, you could see the profile and respond to her message immediately if she was familiar.
Please restore the profile view from the chat section

**Comment by LeonTheOriginal** [comment]
Regarding that the new "cleaned up" context menu still contains many items which you only use once per chat or never (like delete/leave, clear or report) it's a pity that instead a rather useful feature which some people regularly use has been removed.

**Comment by yahsa-rshahsavand** [comment]
Please add this feature back it was useful.thx

**Comment by aleksusklim** [comment]
Totally agree! Please, bring it back.

This shortcut allows to open profile info in channels and groups **that are restricted in some countries** along with iOS restriction.
Simply clicking the dialog is not an option here, because it only shows a warning, without actually opening the chat.

**Comment by Sominemo** [comment]
Was useful to view a chat without loosing previous chat context. Now you can't do that.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/37cd4f51eb7df28f17d7cfbbec1860df0d079c11 ?

**Comment by Remu-rin** [comment]
> [37cd4f5](https://github.com/telegramdesktop/tdesktop/commit/37cd4f51eb7df28f17d7cfbbec1860df0d079c11) ?

Doesn't appear on any chat for me.

**Comment by 0x416c69** [comment]
> [37cd4f5](https://github.com/telegramdesktop/tdesktop/commit/37cd4f51eb7df28f17d7cfbbec1860df0d079c11) ?

Yay! It's back now.
![2022-02-05_03-12-02-AM](https://user-images.githubusercontent.com/10671711/152617516-808f278e-d77a-4e4e-9459-ae245b8bf0e4.png)

Since this is added to the experimental settings, does this mean that it's not gonna stay? At some point I wanted to build my own fork and use addInfo() for good but keeping up with the upstream branch commits is just so much hassle 😢

**Comment by reallyuniquename** [comment]
IMO this should be reopened. Even experimental setting doesn't enable "View profile" menu unless you disable/hide side panel on the right. Never happened in previous versions.
