### ISSUE TITLE
Cannot type Korean(Hangul) in telegram-desktop - Ubuntu 20.04/uim-byeoru

### ISSUE THREAD

**Issue by lyh16** [telegramdesktop/tdesktop#17513]
### Steps to reproduce

1. Install Ubuntu 20.04 on your PC.
2. Install uim, uim-byeoru as IME and set as default IME.
3. Add Korean (Hangul) in Ubuntu "Region & Language" input sources settings.
4. Modify the key mapping of RALT and RCTL to Hangul and Hangul_Hanja, respectively, in /usr/share/X11/xkb/symbols/altwin -> xkb_symbols "meta_alt".
5. Reboot your PC.
6. Install and run the latest version of telegram-desktop using snap, flatpak, or the official binaries.
7. Try typing Korean(Hangul) anywhere possible within the telegram-desktop app.

### Expected behaviour

There should be no problem typing Korean(Hangul).

### Actual behaviour

Only English can be typed within telegram-desktop.

### Operating system

Ubuntu 20.04.3 LTS

### Version of Telegram Desktop

v3.4.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
tdesktop doesn't support uim in official builds, you should switch to ibus or fcitx

**Comment by sftblw** [comment]
I was on somewhat different situation, but for record purpose and I don't know where to leave issue, I'm leaving a comment here.

- OS: ArchLinux (around 2022.01) / KDE Plasma, reproduced in two installation.
- Input Method: fcitx with fcitx-hangul
- Installation: ArchLinux built official package `telegram-desktop` (`pacman -S telegram-desktop`)
- Symptom: Can't input korean, even with installed `fcitx` and `fcitx-hangul` with correct setup (It happened recently)
- Not reproducible on: static linux build which is downloaded from this repo's Readme.md
- Fix: install `fcitx-qt6`

**Comment by RickWayne1125** [comment]
install fcitx-qt6 worked for me too :)
thanks pal!
