### ISSUE TITLE
how to bulk download a channel's whole content?

### ISSUE THREAD

**Issue by bit-scientist** [telegramdesktop/tdesktop#17520]
I would like to download one channel's whole content (text data only) that was broadcasted by the channel admin (excluding forwarded messages) as one txt/json file. Since it's my first time here in desktop applications, I would like to know where to start and what to do, basically.

I would like to sort the words and do some analysis with them. Thank you.

**Comment by RememberTheAir** [comment]
Open the channel -> three dots menu -> "Expost channel history" option

**Comment by bit-scientist** [comment]
Thanks, but I was hoping to write a code (python, or cpp) that gets some args like @username of the channel and options of date ranges.

**Comment by RememberTheAir** [comment]
I guess for this kind of scripting you should have a look at libraries/frameworks such as [tdlib](https://core.telegram.org/tdlib) or [pyrogram](https://docs.pyrogram.org/)
