### ISSUE TITLE
Spotify song preview not working after last update

### ISSUE THREAD

**Issue by KMatuszak** [telegramdesktop/tdesktop#17522]
### Steps to reproduce

1. Send link to Spotify song to someone

### Expected behaviour

![image](https://user-images.githubusercontent.com/86327285/148377813-70d46975-ec98-43b9-b45f-2410182e9066.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/86327285/148377872-39a5a171-fa0a-42e9-b0c5-a1db35378da2.png)

### Operating system

Windows 10 Pro 21H2 (19044.1415) x64

### Version of Telegram Desktop

3.4.3 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
i vote 3rd party bug and if telegram can fix it must be fixed platform wide.

**Comment by 23rd** [comment]
https://bugs.telegram.org.
