### ISSUE TITLE
Commad + w can not close window on macOS

### ISSUE THREAD

**Issue by wogong** [telegramdesktop/tdesktop#17523]
### Steps to reproduce

1. Open Telegram
2. CMD + W

### Expected behaviour

Telegram window close

### Actual behaviour

Nothing happen

### Operating system

macOS 12.1

### Version of Telegram Desktop

Version 3.4.3

### Installation source

Static binary from official website

**Comment by wogong** [comment]
Weird, after closing all other APPs, quit and restart tgdesktop several times, it works now.
Maybe something wrong with my env.

**Comment by bruce3x** [comment]
+1
