### ISSUE TITLE
Low resolution app icon in task switcher 

### ISSUE THREAD

**Issue by dellmonitor** [telegramdesktop/tdesktop#17525]
### Steps to reproduce

1. Download official binary
2. Run binary
3. Switch program using alt+tab

### Expected behaviour

Normal resolution app icon appear in task switcher.

### Actual behaviour

Low resolution app icon appear in task switcher.

### Operating system

Linux Mint 20.2 Cinnamon

### Version of Telegram Desktop

3.4.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can you provide screenshots for those who doesn't have Cinnamon?

**Comment by dellmonitor** [comment]
![TelegramIconIssue png](https://user-images.githubusercontent.com/69437048/148440523-c424b21a-231b-47d5-9bce-4c4d65affae2.png)

**Comment by ilya-fedin** [comment]
`xprop _NET_WM_ICON` and choose Telegram window

**Comment by dellmonitor** [comment]
[icon.txt](https://github.com/telegramdesktop/tdesktop/files/7824355/icon.txt)

**Comment by ilya-fedin** [comment]
I see icons up to 128x128, is this not enough for task switcher?

**Comment by dellmonitor** [comment]
Sorry. Looks like it fixed now. I tried to make new Telegram.desktop file several times with different parameters (launch in termianl, another icon). Now the icon is o
![TelegramIcon](https://user-images.githubusercontent.com/69437048/148446451-be9159ba-c9d3-4a4b-8ad6-194604728089.png)
k
