### ISSUE TITLE
UTF-8 support for music file's name

### ISSUE THREAD

**Issue by chalist** [telegramdesktop/tdesktop#17529]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/1072154/148545900-30b3473d-b9d5-4104-84b6-08a9cfb3065b.png)

### Expected behaviour

Display music file's name in the player.

### Actual behaviour

Does not display music file's name in the player.

### Operating system

Linux (Manjaro)

### Version of Telegram Desktop

3.4.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
🤔  Please send me this file at https://t.me/preston

**Comment by chalist** [comment]
Has been sent.

**Comment by chalist** [comment]
Not fixed yet.
