### ISSUE TITLE
Online, Typing and "Read" are crazy unreliable with at least one (essential) contact.

### ISSUE THREAD

**Issue by U-Go-7** [telegramdesktop/tdesktop#17524]
Hi, I have an issue which as far as I know is not common. It already caused LOT of misunderstandings.

The issue is, the online status, the "message read" status, and the typing status of at least one person (the only one I contact constantly and longly enough to notice) is almost never displayed correctly. This person has no Smartphone anymore since a couple of months and therefore uses only Telegram Desktop.

Typically, I write something, this person comes online, I see the online status correctly, I see my messages becoming read, and then shortly after the person appears offline, although actually is right there with the chat open still reading my messages.
Eventually this person starts typing, this is displayed for a while, then no more. So I see the person as offline and not typing for very long time, and wonder wtf is going on for this person to disappear in the mid of an important urgent conversation.
And I write again, and my message appears not read. Then suddenly, often almost immediately, this person appears again online or typing, and says to have been there reading or typing all the time.

To be clear, this also happens when I use Telegram for Android.
And this only happens on one side. I mean, this person can see me online all the time, and typing too.

Few days ago something even more creepy happened. 
We were writing, then this person had to go to talk with the flatmates, and just closed telegram's window but not the program.
I wrote something while this person was appearing offline. My message appeared as not read. Then suddenly this person appeared online, and my message read. Than again offline. I wrote again, and again my message appeared as not read.
HOURS later this person comes and says to have been gone the whole time. Meaning, when this person appeared online and my message appeared as read, actually this person was NOT online at all.

So, WTF is happening there?
What kind of setting in this person's Windows 10 or Notebook (Lenovo) or Telegram can ever possibly make this happen???
Or is the problem on my side?

Please help.
Thanks

**Comment by saibakobito** [comment]
Hey @U-Go-7 

I was searching the web for the exactly same problem u described.  
In my case, my mate and i use both telegram for Android.
Often when i wrote him some messages, he received the text, appeared online, read it, then suddenly came up with the "is typing" status and the out of nowhere he disappears and then nothing..
I was very wondering about that and asked him, he answered: " I was only reading it, but never typing"..
and i was noticing this a few times! 

Very spooky ..

**Comment by Aokromes** [comment]
so, not a bug?

**Comment by RememberTheAir** [comment]
There's for sure some misunderstanding in how the online status works. I would waif for an answer
