### ISSUE TITLE
Lags when scrolling

### ISSUE THREAD

**Issue by bymaer** [telegramdesktop/tdesktop#17526]
### Steps to reproduce

1. Open Telegram
2. Open any chat or channel
3. Scroll down or up slowly

https://user-images.githubusercontent.com/37290594/148436463-2959b6e1-8695-472f-8b91-95b9fbc535d1.mp4

### Expected behaviour

smooth scrolling

### Actual behaviour

jerky scrolling

### Operating system

MacOS Monterey 12.1

### Version of Telegram Desktop

3.4.3

### Installation source

Static binary from official website

**Comment by foremtehan** [comment]
I also experience lags, But only when the some media is playing in the background within the telegram player

**Comment by bymaer** [comment]
Hello! I see a pattern of why this happens. Please watch the video. If I scroll and then touch the touchpad while scrolling it stop, and then when I release the touchpad it continues to scroll.

https://user-images.githubusercontent.com/37290594/149161264-f094a59c-7d00-40e0-b6a1-683cd7ddc240.mp4
