### ISSUE TITLE
Sender messages are left aligned when the sticker panel is undocked.

### ISSUE THREAD

**Issue by amajaying** [telegramdesktop/tdesktop#17532]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/78684754/148562446-aa5f95e2-5b12-40c0-9e51-8e22c71f55e1.png)

The sender messages are left-aligned when the emoji panel is undocked.

Steps to Reproduce:
1. Open Telegram
2. Go to any conversation and undock the emoji panel clicking on the emoji icon. 

### Expected behaviour

The sender message should be right-aligned as expected.

### Actual behaviour

But when the emoji panel is docked, the sender message is right-aligned.

![image](https://user-images.githubusercontent.com/78684754/148563619-f9d321fe-eabc-4c17-b79a-669ac67f6f40.png)

### Operating system

Windows 10

### Version of Telegram Desktop

Version 3.4.3

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
This is not a bug

**Comment by Aokromes** [comment]
disable adaptative layout
