### ISSUE TITLE
Sending a block of code crashes the app on MacOS X

### ISSUE THREAD

**Issue by vaurdan** [telegramdesktop/tdesktop#1755]
I'm trying to send the following message to a group, and it's crashing the app when I press enter:

```
 \```
		// Test if site was reported in the last 5 minutes
		if( Cache::has('ip-reported-' . $site ) ) {
			$response = Response( ['error'=>'site reported in less than 5 minutes']);
			$response->setStatusCode('420', "Enhance Your Calm");

			return $response;
		}
 \```
```
(ignore the `\`, I sent it without the slashes)

It crashed, and here's the log: https://gist.github.com/vaurdan/9a916b5f3fb4b4ddf908

I'm running Telegram for OSX, Version 2.01.38707.

I'll be happy to do more testing if you want.

**Comment by vaurdan** [comment]
I did some testing, and I believe it's because of the first character being a `\t`. If I test it without that tab, it wont crash.

**Comment by telegramdesktop** [comment]
This is github about another Telegram app (multiplatform app based on Qt library), you can try it out from https://desktop.telegram.org :)

**Comment by vaurdan** [comment]
Oh! Sorry about that, I got lost on the multiple github repositories hehe :) I'm going to report it there. And I'm surely test this app.
