### ISSUE TITLE
Stuck at 100% download

### ISSUE THREAD

**Issue by doylefermi** [telegramdesktop/tdesktop#1759]
The file is stuck at 100% download.

OS: Arch Linux 
Kernel: x86_64 Linux 4.4.5-1-ARCH
CPU: Intel Core i5-4200U CPU @ 2.6GHz
RAM: 1674MiB / 3840MiB

Telegram version: 0.9.28

![telegram bug](https://cloud.githubusercontent.com/assets/8755940/13719709/036db10c-e820-11e5-8853-782fc92b8d98.png)

**Comment by ElTopo** [comment]
This also happens on Windows version, just saw it with 0.9.32

**Comment by devianpctek** [comment]
The file download completes (I need to copy the file from the downloads folder to a different folder so it doesn't get deleted if I click the cancel button), but yes the progress circle gets stuck, still present on 0.10.6 I'm on Debian amd64

**Comment by john-preston** [comment]
@devianpctek I'm afraid not the full file is downloaded then. This is some server flood control I'm afraid :( I'll try to find out.

**Comment by MichaelTiebesl** [comment]
Same as #1703
