### ISSUE TITLE
[Feature Request] Add Remove Pack Option to Pack Info Box

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1763]
Please add remove pack option to pack info box, managing a lot of packs is not so easy for now.

![telegram_2016-03-13_12-33-43](https://cloud.githubusercontent.com/assets/15929497/13728431/bf2205da-e918-11e5-9737-ebc8ffcaf616.png)

Thanks

**Comment by Kondra007** [comment]
There's "Manage stickerpacks" option in settings where you can delete stickerpacks of your choice.

**Comment by amiremami** [comment]
Yes @Kondra007 , but for example someone sent you a sticker, and you know that you have that pack and want to delete the pack. For now, you have to right click on it, see the name of the pack (image above) , then click on manage stickerpacks as you said, find that pack which is not easy at all, and then delete it.

But if they add this option in the box I said, you only right click on the sticker and remove it from your sticker packs, very easy and fast.

Thanks @auchri :)

**Comment by stek29** [comment]
Afaik it was added in android app new beta.

**Comment by amiremami** [comment]
I hope you add this guys, not a very big deal but it would be better with this option.

**Comment by amiremami** [comment]
Maybe to add this in future? Thanks 😄

**Comment by amiremami** [comment]
Not yet on desktop?!
