### ISSUE TITLE
Channel 200 user limit display

### ISSUE THREAD

**Issue by bliz937** [telegramdesktop/tdesktop#1765]
If my understanding is correct, then this should be easy to fix.
I know that groups have a 200 user limit, until super groups, but I am not aware of any limitations on channels. When adding someone to a channel, I noticed there is a user counter until 200.

![image](https://cloud.githubusercontent.com/assets/4072820/13729717/8115e06e-e944-11e5-8da4-1f82faa77849.png)

### Steps to reproduce
1. Go to channel you administrate
2. Click on channel name -> members
3. Add members

### Expected behaviour
Just show the number of users in the channel, without the 200 limit.

### Actual behaviour
\# users / 200

### Configuration
**Operating system:**
Win 8.1
**Version of Telegram Desktop:**
0.9.30 dev
0.9.28

**Comment by auchri** [comment]
See #1597 :)

**Comment by telegramdesktop** [comment]
This is maximum count of members you can add to the channel by yourself (after that users can only join by themselves using invite link or public telegram.me link).

**Comment by comtralink** [comment]
why i cant join more channels  , limitation of channel?

**Comment by stek29** [comment]
@comtralink there's also a server side limit on number of channels you can join

**Comment by DrakeTDL** [comment]
and what is the server-side limitation? if you dont mind me asking.

**Comment by RememberTheAir** [comment]
@DrakeTDL afaik 500 supergroups and channels (summed togheter)

**Comment by kishorekichu006** [comment]
how do I add more than 200 members in a telegram group from a different group even they are not in my contact? Please anybody help me

**Comment by RememberTheAir** [comment]
@kishorekichu006 that sounds like spam. Just pin the new chat's invite link in the old group. People who care will join
