### ISSUE TITLE
Non-FQDN links are broken

### ISSUE THREAD

**Issue by Raifeg** [telegramdesktop/tdesktop#1768]
For example:
http://somehost/link

### Expected behaviour
It expected to be link, highlighted and active.

### Actual behaviour
Some time (just several moments after post) it appears as link, but then transforms to usual text.

### Configuration
Windows 8.1
Telegram Desktop: 0.9.28

**Comment by telegramdesktop** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1054

The links are currently parsed at server side, so it is not a Telegram Desktop issue. I've informed the server side devs of the request, perhaps they'll add this links some day.

**Comment by Raifeg** [comment]
Somehow Telegram Mobile on IOS does not have this issue.

**Comment by telegramdesktop** [comment]
It still does not use server side links parsing, but it will eventually.
