### ISSUE TITLE
Windows Sound device change is ignored

### ISSUE THREAD

**Issue by Mimoja** [telegramdesktop/tdesktop#1769]
### Steps to reproduce
1. Start Telegram for Desktop
2. Change default Audio device
3. Recieve Message

### Expected behaviour
Sound is played on the (new) default device

### Actual behaviour
Sound is played on the old device

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
0.9.28

**Comment by auchri** [comment]
#418 :)
