### ISSUE TITLE
Hard lags in the list of members in supergroups v2

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1770]
### Steps to reproduce
1. [Join "Telegram Party"](https://telegram.me/publictestgroup)
2. Click "Info"
3. ???
4. ~~PROFIT!~~ Lags

### Expected behaviour
Big lags

### Actual behaviour
No lags

### Configuration
**Operating system:** Linux 4.2.0-30 Ubuntu 15.10 (DE: Cinnamon)
**RAM**: 12Gb

**Version of Telegram Desktop:** 0.9.31

### Logs
It is needed?

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov Looks pretty fine in OS X.. What do you mean by lags?

**Comment by DaFri-Nochiterov** [comment]
Video: https://youtu.be/6ylYTAsBlT8
_Sorry, I do not set up a screen recording app and you can see many glitches_

- App freeze (?) when open info
- Freezes when scroll (fast scroll with the bar)
- Hard (like app stopped work) freezes (up to 2 seconds) when scroll first time (slow scroll)

**Comment by john-preston** [comment]
Is it fine in 0.9.34 dev? Sort by online was disabled for large groups there..

**Comment by DaFri-Nochiterov** [comment]
Yes, it's fine.
