### ISSUE TITLE
When you banned in the supergroup and unbanned - you can't see new messages

### ISSUE THREAD

**Issue by Brawaru** [telegramdesktop/tdesktop#1772]
### Steps to reproduce
1. Admin of the group ban you and now you can't join by link
2. When you're get unban and someone add you back chat are still unseen in list, you join by link - you see old messages
3. You can type messages - others can see your messages, but you don't see others people messages.
4. Restart TDesktop and all goes fine
### Expected behaviour
- You see new messages
- You see changes in your messages
- Group doesn't appear in list
### Actual behaviour
- You don't see new messages
- You don't see changes in your messages
### Configuration

**Operating system:** Linux Ubuntu 15.10 (DE: Cinnamon)

**Version of Telegram Desktop:** 0.9.31 dev

**Comment by stek29** [comment]
Same bug on OS X 10.11.2, 0.9.31 dev

**Comment by john-preston** [comment]
I can't reproduce that. Is it so in the latest dev version?

**Comment by azmankudus** [comment]
Hi, any progress on this bug? It is still happening using version 1.3.7.
