### ISSUE TITLE
overlapping localisation - lng_settings_update_ready

### ISSUE THREAD

**Issue by Skaronator** [telegramdesktop/tdesktop#1773]
The "New version is ready" message in german overlaps with the "Restart now" message but **only on high-resolution monitors**
### Screen details to my surface pro 4

_Resolution: 2736 x 1824 (267 PPI)_
_Aspect Ratio: 3:2_
### Configuration

**Operating system:**
Windows 10 (on both)
**Version of Telegram Desktop:**
Updated from 0.9.28 -> 0.9.32

---
## This looks fine on my 1080p desktop:

![1080p](https://cloud.githubusercontent.com/assets/2886913/13758987/7a380cca-ea2c-11e5-968c-a2d3ddc55c8e.png)
## But on my surface does it overlap:

![surface](https://cloud.githubusercontent.com/assets/2886913/13758983/77d18286-ea2c-11e5-8961-2b88f3f92989.png)

---

I would just move `lng_settings_update_ready` a bit to the left so it is on the same level as the A from "Auto-Update"
![surface2](https://cloud.githubusercontent.com/assets/2886913/13759135/287e38b8-ea2d-11e5-856a-25d39262a608.png)

**Comment by RadRussianRus** [comment]
I think this problem doesn't exist anymore since there is new settings menu layout.

**Comment by Skaronator** [comment]
You're probably right. I'm closing this.
