### ISSUE TITLE
Not able to start Telegram

### ISSUE THREAD

**Issue by Polynomdivison** [telegramdesktop/tdesktop#1774]
### Steps to reproduce
1. Start Telegram

### Expected behaviour
The Telegram window should open.

### Actual behaviour
There is no Telegramwindow but the programm is running with no gui.

### Configuration
**Operating system:**
Xubuntu 15.10 (64 Bit)
4.2.0-34-generic

**Version of Telegram Desktop:**
Newest... (v 0.9.32)
64 Bit

### Logs
Terminal:
    
    (Telegram:2001): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'    

    (Telegram:2001): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed    

    (Telegram:2001): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

Log:

    [2016.03.14 22:35:31] Launched version: 9032, dev: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
    [2016.03.14 22:35:31] Executable dir: /home/nick/Telegram/, name: Telegram
    [2016.03.14 22:35:31] Initial working dir: /home/nick/Telegram/
    [2016.03.14 22:35:31] Working dir: /home/nick/.TelegramDesktop/
    [2016.03.14 22:35:31] Arguments: "./Telegram"
    [2016.03.14 22:35:31] Logs started
    [2016.03.14 22:35:31] Connecting local socket to /tmp/43ff3541779f85ce6e63441761e985cf-{87A94AB0-E370-4cde-98D3-ACC110C5967D}..
    [2016.03.14 22:35:31] This is the only instance of Telegram, starting server and app..
    [2016.03.14 22:35:31] Moved logging from '/home/nick/.TelegramDesktop/log_start0.txt' to '/home/nick/.TelegramDesktop/log.txt'!
    [2016.03.14 22:35:31] Opened '/home/nick/.TelegramDesktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 0

**Comment by chorca** [comment]
I was just about to post this.. Having the same problem across two linux desktops.

Both running Xubuntu 15.10 Wily, 4.2.0-30-generic #36-Ubuntu SMP

Before the update, telegram ran fine, after the update, getting the same error as above:
`~/bin/Telegram$ ./Telegram 
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

(Telegram:21667): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(Telegram:21667): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(Telegram:21667): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
`

Tested on two different machines, same issue on both. Telegram process still runs, not using any CPU.

**Comment by auchri** [comment]
With a quick google search I found this: https://www.dropboxforum.com/hc/en-us/community/posts/201858939-dropbox-failing-to-start-on-Ubuntu-14

> I had the same problem in Kubuntu, I just changed in "application appearance -> Style ->Applications" the style. The problem was with GTK + .  

Maybe it helps you

**Comment by Polynomdivison** [comment]
I'm running Xubuntu not Lubuntu. ^^ Fixed this mistake...

I had the problem with the fonts too and then I found this on github;

> Try rm -rf the relevant fontconfig file that Telegram complains about. After that, run fc-cache -fv. Should work for just about every distro, but if not, google how to do a font cache rebuild for your specific distro.
> This should resolve the fontconfig error for you.

#517 
This fixed the font problem

**Comment by chorca** [comment]
Was able to fix the font issue with that, however, as @Polynomdivison mentions, that is not the main issue. The GUI still does not display.

**Comment by Skeptyc** [comment]
I am having the same issue with the GLib warnings and no GUI appearing, 64bit Linux Telegram.  As a temporary work-around, I have found that the 32bit version *does* work, though in Xubuntu 15.10 it does not display a proper tray icon.

**Comment by klrkdekira** [comment]
Deleting the font file removes the error messages but the UI still not appearing.

**Comment by abracadaber** [comment]
Same problem on ubuntu 15.10 + Xfce

**Comment by Polynomdivison** [comment]
I tried the 32Bit version and it works.
You have to install

    apt-get install libglib2.0-0:i386

bevor you can start Telegram 32bit.

**Comment by wdog** [comment]
I've the same problem with Ubuntu 15.10 - Linux 4.2.0-30-generic x86_64 GNU/Linux

**Comment by Polynomdivison** [comment]
Just tried it with other desktop enviroment lxde and the 64 bit version is working.
So it only affects xfce and like @wdog wrote: unity?

**Comment by wdog** [comment]
Sorry I'm also using xfce 4.12

**Comment by Skeptyc** [comment]
As am I. Xfce on Xubuntu15.10

Interesting note: if I run the 64bit telegram as root via sudo, it *does* start with the GUI. It's only when run as my user account that it does not. 

Deleting the ~/.TelegramDesktop directory didn't make a difference for if my user account could run Telegram. Nor did trying the latest dev version.

**Comment by wdog** [comment]
this solves the problem for me .... a workaround obviously 
```
unset XDG_CURRENT_DESKTOP
```

**Comment by dario86** [comment]
Same problem here
I'm running Xubuntu 15.10 64bit, Xfce 4.12

From shell i get this error:

```
dario@dario-desktop:~/Telegram$ ./Telegram
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
```

**Comment by ismtabo** [comment]
Same problem here.

Also using Xubuntu 15.10, Xfce 4.12.

Terminal shows this error running `Telegram` executable:
```bash
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

(Telegram:22818): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(Telegram:22818): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(Telegram:22818): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```

**Comment by telegramdesktop** [comment]
What does ~/.TelegramDesktop/log.txt say when you run Telegram binary and wait for like ten seconds with no main window displayed? Is the process still running after that or did it crash silently?

**Comment by wdog** [comment]
Is still running. no crash

**Comment by thiaramus** [comment]
I have exact same issue with 0.9.32 and latest Xubuntu. Had to rollback to 0.9.18, which is working perfectly.

**Comment by ismtabo** [comment]
@telegramdesktop my log:

```
[2016.03.15 13:52:49] Launched version: 9032, dev: [FALSE], beta: 0, debug mode: [TRUE], test dc: [FALSE]
[2016.03.15 13:52:49] Executable dir: /home/destroid/Programas/Telegram/, name: Telegram
[2016.03.15 13:52:49] Initial working dir: /home/destroid/Programas/Telegram/
[2016.03.15 13:52:49] Working dir: /home/destroid/.TelegramDesktop/
[2016.03.15 13:52:49] Arguments: "./Telegram" "-debug"
[2016.03.15 13:52:49] Logs started
[2016.03.15 13:52:50] Connecting local socket to /tmp/1d06aad8d648d6523142d77abab343e9-{87A94AB0-E370-4cde-98D3-ACC110C5967D}..
[2016.03.15 13:52:50] Socket connect error 0, starting server and app..
[2016.03.15 13:52:50] Moved logging from '/home/destroid/.TelegramDesktop/log_start0.txt' to '/home/destroid/.TelegramDesktop/log.txt'!
[2016.03.15 13:52:50] Opened '/home/destroid/.TelegramDesktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 0
```

**Comment by crackedmind** [comment]
Same issue with 0.9.31, 0.9.32 versions on Xubunu 15.10. 0.9.28 works fine

**Comment by telegramdesktop** [comment]
@crackedmind Works perfectly in Xubuntu 14.04 for me :(

**Comment by abracadaber** [comment]
unset XDG_CURRENT_DESKTOP works, but tray icon is missed

**Comment by telegramdesktop** [comment]
I can confirm the issue on Xubuntu 15.10 (working fine in Xubuntu 14.04). I'll investigate that, thanks for your reports.

**Comment by MertcanGokgoz** [comment]
Always Error Font error and not start telegram gui for xubuntu 15.10

```
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
```

**Comment by telegramdesktop** [comment]
Font errors are irrelevant, they have nothing to do with the problem.

**Comment by simonaldrich** [comment]
This issue also occurs on Mate Desktop (14.04). The workaround to set XDG_CURRENT_DESKTOP to "GNOME" used to work (it's set to "MATE" by default) but no longer does.

**Comment by telegramdesktop** [comment]
I found the moment when it all broke and I have an idea why. Currently I'll rollback the style changes from here: https://github.com/telegramdesktop/tdesktop/issues/987 because it is incompatible with working under Xubuntu 15.10 with a good-looking tray icon.

This will be done in the next release, I hope to deploy a dev version tomorrow.

**Comment by slavafomin** [comment]
I have the same issue on `Xubuntu 15.10`. Looking forward for an update. Thanks for your hard work!

**Comment by telegramdesktop** [comment]
Everybody on Xubuntu 15.10 please check out the 0.9.33 stable version from https://desktop.telegram.org, it should work fine now.

**Comment by telegramdesktop** [comment]
(can anyone confirm?)

**Comment by chorca** [comment]
Confirmed, this update fixes the issue. I am able to see the Telegram GUI in Xubuntu 15.10 now.

**Comment by CirKu17** [comment]
Fix confirmed

**Comment by Polynomdivison** [comment]
Confirmed.
