### ISSUE TITLE
Animated stickers not working

### ISSUE THREAD

**Issue by paoletto** [telegramdesktop/tdesktop#1776]
### Steps to reproduce
1. Create a sticker pack
2. Add a new sticker
3. Upload an animated gif as file

### Expected behaviour
Tell us what should happen

The sticker should be added

### Actual behaviour
Tell us what happens instead

The sticker is not added

### Configuration
**Operating system:**

Any

**Version of Telegram Desktop:**

0.9.32

### Logs
Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

**Comment by telegramdesktop** [comment]
@paoletto Animated stickers are not supported, stickers are static .webp images in Telegram.

**Comment by paoletto** [comment]
I see. I opened this issue because in the android client i can see a special "gif" tab on the sticker menu, where i can actually see those gifs i tried to upload as sticker from telegram desktop as files, but of course couldn't see there.

So okay, stickers are static. But what's that tab then?

**Comment by john-preston** [comment]
@paoletto It is for GIFs, Telegram Desktop has it too. You can search for gifs by "@gif " command or save any gifs you like to that tab by right-pressing them and clicking Save GIF.

**Comment by woj-tek** [comment]
Is there any plan to enable animated stickers? .webp supposedly supports animation (tho, according to this: http://littlesvr.ca/apng/gif_apng_webp.html it's not such a great option size-wise...)

**Comment by john-preston** [comment]
@woj-tek No such plans right now.

**Comment by lifehome** [comment]
Will there be gif packs? Something similar to animated stickers?

**Comment by chewenkai** [comment]
I hope that telegram can add gif sticker package too. Because I want to share my gifs as share my static png. But there does not have a good method for now. Expect one day I can create a gif sticker package. Thanks.

**Comment by tycho01** [comment]
To clarify, would pull requests for this be accepted?

**Comment by stek29** [comment]
@tycho01 Pull requests for what exactly? How are you going to add support for gif packs without changing telegram API?

**Comment by tycho01** [comment]
@stek29: I see -- I was under the impression playback of animated webp might be a client-side change.

**Comment by bviktor** [comment]
So how does one submit a request to change the Telegram API? This is such a basic feature in any IM solution. There's GIFs, they now even autoplay videos, but animated stickers? Hell no!

Doesn't make any sense.
