### ISSUE TITLE
Issue with pasted image from clipboard

### ISSUE THREAD

**Issue by tropicoo** [telegramdesktop/tdesktop#1777]
### Steps to reproduce
1. Press Prinstscreen key, paste and send image from clipboard to Telegram chat (uncompressed)
2. Try to click on appeared and sent message with image - no reaction at all and no download icon, "OPEN WITH" button doesn't work too.
3. Restart Telegram
4. Look at message again - download icon is now present, after clicking image is being downloaded.

### Expected behaviour
Download icon is visible after sending image, clicking on that icon should start downloading.

### Actual behaviour
Download icon is absent and clicking on any part of sent message results in nothing.
After restarting Telegram everything works as should, while you don't paste and send new image.

### Configuration
Windows 10 x64 1511 Eng

**Version of Telegram Desktop:**
0.9.32

First screenshot shows how message looks after sending, second - after restarting.
![1](https://cloud.githubusercontent.com/assets/888784/13778444/79a88fd6-eabe-11e5-9362-7e8dabe8bc38.PNG)
![2](https://cloud.githubusercontent.com/assets/888784/13778443/79a84602-eabe-11e5-8697-c6123806860d.PNG)

**Comment by Kondra007** [comment]
Same here. And if you look into "Downloads" folder (which is set by default in app) you'll see lots of copies of an image (if you pressed "Open with" multiple times)

**Comment by FloodCode** [comment]
I have same issue on same configuration (Windows 10 x64 1511 Eng).

**Comment by tropicoo** [comment]
It's fixed in 0.9.40
