### ISSUE TITLE
[Feature Request] Ability to Merging Channels

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1778]
This is one of the most important features for admins and webmasters. They have multiple channels and want to merge all of them together. It will be great if you add this feature.

This feature exists on facebook which you can merge pages together.

Thanks

**Comment by telegramdesktop** [comment]
@amiremami Sorry, this has nothing to do with Telegram Desktop.

**Comment by amiremami** [comment]
Oh sorry, I thought we should post all suggestions here, sorry again!

**Comment by DaFri-Nochiterov** [comment]
forEach-forward all mesages to new channel
forEach add *new* admins to new channel from old channel
delete old channel
???
~~PROFIT~~ merged :smiley:
