### ISSUE TITLE
[Feature request] Edit last message by 'up arrow' key in supergroups

### ISSUE THREAD

**Issue by zulman** [telegramdesktop/tdesktop#1779]
### Expected behaviour
When the message was sent (if you are in supergroup) pressing the 'up arrow' key will open message editing UI. 
Reference behaviour - Skype client for Windows/Mac.

### Actual behaviour
'up arrow' scrolling chat history

### Configuration
Windows 0.9.32

Thank you :)

**Comment by telegramdesktop** [comment]
@zulman I'm afraid it is far from «Expected» behaviour — I would be very surprised by such behaviour. As it can be seen through the issues, some users think that the up key should substitute the last sent message like console apps substitute the last commands. If they will think, that this is done by the up key, while really it is a message edit, a mess will start %)

**Comment by zulman** [comment]
Hi,
Thank you. Got your point. For me it looks like "expected" behaviour just because when i'm in messenger i expect messenger like behaviour (e.g. like in Skype and Slack) and when i'm in the terminal (e.g. bash) i expect console like app behaviour. As i understand Telegram audience - there are a lot of users who never even heard about console apps but definitely familiar with Skype :)

Thank you :)

**Comment by bo0tzz** [comment]
+1

**Comment by aschekatihin** [comment]
related enhancement: #1060

**Comment by f1ztech** [comment]
+1, may be not the up key, just any shortcut, it's really useful feature

**Comment by stek29** [comment]
#853 duplicate?

**Comment by DaFri-Nochiterov** [comment]
@stek29, no. Because this issue just about copying text of latest sent message (not edit)

**Comment by LendLord** [comment]
+1

**Comment by edmundlaugasson** [comment]
Perhaps CTRL+arrow would be better choice. Arrow is currently scrolling messages and this should remain. But yes - shortcut key to easily edit last message would be very much appreciated!

**Comment by toxsedyshev** [comment]
Yep, Ctrl+arrow would be ok too.

**Comment by DaFri-Nochiterov** [comment]
Discord app behavior as example of best behavior (for me):
```
if message text field is empty
   on pressing ↑ up arrow key:
       edit latest message
else
   default behavior (cursor moving)

when editing message:
  on press Esc:
      cancel editing

when typing message:
  on press Enter:
     if inside of  "```" construction:
         new line
     else
         default behavior (send or new line (in settings))
```

**Comment by zulman** [comment]
Thank you guys for implementing this feature, i'm happy now :)

**Comment by hmvs** [comment]
Is it implemented only for supergroups? Seems I can't quick edit messages for private chats, 
Telegram Desktop for Windows Version 1,2.6

**Comment by stek29** [comment]
You should be able to edit them, but only ones you wrote using the same app.

**Comment by hmvs** [comment]
@stek29 Just checked, unfortunately it doesn't work.

**Comment by Anton-V-K** [comment]
This behavior works for chats, and this is very inconvenient, because it is impossible to scroll the history with up/down keys... How to disable this feature?

**Comment by hmvs** [comment]
> This behavior works for chats, and this is very inconvenient, because it is impossible to scroll the history with up/down keys... How to disable this feature?

Stupid question: can you just use **page up** and **page down** keys?

**Comment by Anton-V-K** [comment]
Yes, PgUp and PgDown work for scrolling. They are easier to use than touchpad. I willl use them as a workaround until the UP key behavior is sorted out.
Thanks for the hint.
