### ISSUE TITLE
Telegram crashes every time network changes...

### ISSUE THREAD

**Issue by mareg** [telegramdesktop/tdesktop#1780]
### Steps to reproduce
1. Connect to the network (at the office, with multiple access points)
2. Start telegram desktop
3. Move to another part of the office (switching the network)

### Expected behaviour
Telegram should reconnect and continue to work

### Actual behaviour
Telegram crashes

### Configuration
Fedora 23 64bit
Telegram 0.9.28

**Comment by mareg** [comment]
Another way to reproduce it:

1. when logged in at work, suspend the laptop
2. go home
3. resume

Expected behaviour
Telegram continues to work.

Actual behaviour
Telegram crashes.

**Comment by john-preston** [comment]
Can you please submit a crash report? I can't reproduce that myself.

**Comment by mareg** [comment]
How can I create a crash report?

I am working from the client's office where for security reasons we have no access to the wifi - so I am using wired (cable) connection. Every time I disconnect cable, and then reconnect it again Telegram crashes. Note - it crashes on re-connect rather then disconnect. Then when I try to start telegram it shows it's usual "network connection..." popup trying to update itself (but fails, which is good) and when I click "skip", it closes. So I need to start it again - this time it works.

Very annoying and cumbersome procedure to be honest!

1. It should not crash in the first place
2. It should not try to update itself, just start

Happy to submit a crash report but not sure what exactly you are expecting!

**Comment by john-preston** [comment]
@mareg You can download dev version from https://desktop.telegram.org bottom of the page and crash it — after the next launch it will suggest to submit a crash report. Please copy your Crash Report Tag (from the reporting window) here, so I can watch exactly at this report. Thanks.
