### ISSUE TITLE
"Last time Telegram Desktop was not closed properly" and auto-update

### ISSUE THREAD

**Issue by mareg** [telegramdesktop/tdesktop#1781]
### Steps to reproduce
1. Make Telegram Desktop crash (for example, change wifi network)
2. Start it again

### Expected behaviour
Telegram should start silently as if nothing happened.

### Actual behaviour
Telegram shows a window with "Last time Telegram Desktop was not closed properly" and starts auto-update despite the fact auto update was disabled in settings.

### Configuration
**Operating system:** Fedora 23 64bit

**Version of Telegram Desktop:** 0.9.28

### Additional info
I have Telegram Desktop installed through the repository https://copr.fedorainfracloud.org/coprs/rommon/telegram/ - I assume this is default repository managed by the author of the app.
While auto-update is expected and make sense on Windows and OS X platforms, it's not recommended on Linux. If you look at Firefox - there's no auto update for Firefox installed from the repository on Fedora and other Linux distros. Hence Telegram Desktop should not update itself automatically on Linux desktop.

**Comment by telegramdesktop** [comment]
@mareg No, this is not a repository managed by me. I don't know who manages it, actually, and what app is placed there. If someone builds versions for a repository, they should disable autoupdating by define TDESKTOP_DISABLE_AUTOUPDATE, then it won't even try to autoupdate and there won't be such a setting. Current implementation is not supposed to be used from the repository, it is supposed to be downloaded from site and autoupdate.

**Comment by telegramdesktop** [comment]
Regarding the issue: the issue is in the first step "to reproduce" -- the app should not crash. If it crashes it should generate crash report and suggest to send it (currently only in dev version). So it will be great if you download a dev version from the bottom of this page: https://desktop.telegram.org/#dev-version then make it crash, then launch once again, send the crash report and copy the crash report tag here.

**Comment by mareg** [comment]
Thanks, I'll install the dev version!

My problem here is though - it should not auto-update on Linux desktop ever. I don't like it downloads an executable binary from the net and then it executes it from the user's folder. On Linux desktops updates should be pushed via repositories, where packages are signed and my package manager can warn me if they're not.

**Comment by john-preston** [comment]
@mareg tdesktop automatic downloaded updates are signed as well :) At least here you get the app that was built by me, while from the repository you currently get a version that was built by someone else, if I understand correctly what is going on.

**Comment by mareg** [comment]
@john-preston you understand correctly - I believe the app from repository is built from the source code, hence it should be like yours.

On Linux desktop I do not want apps to auto-update whenever the app wants - this should be handled through the repository. Maybe you should consider creating an official repository to host linux builds? There are tools out there which automate that for you, for example https://en.opensuse.org/Package_repositories can build packages for different distributions.

As a Linux user I do not want the app to auto update, it should not try to auto update ever. I trust you've built a solid auto-update system, but the problem here is - you make user to execute binary from user's folder.

**Comment by john-preston** [comment]
@mareg Thank you for the link, I'll look into that. Though I don't know when and if I'll be able to move to that Linux way.

**Comment by and-semakin** [comment]
Oh gosh, got the same issue on Fedora 29, I just changed Wi-Fi network and now Telegram is not starting anymore. I tried to enable VPN, so Telegram servers should be accessible, but it doesn't matter.

![image](https://user-images.githubusercontent.com/9129071/56484388-c57cee00-64e8-11e9-9fc9-a195b64e7bd9.png)

By the way, it didn't suggest me to send crash report. I use latest Telegram from official site.

**Comment by pras92** [comment]
> UPD: wow, I've just noticed that "Skip" button is clickable. Telegram successfully launches now. But here is still an issue with crashing on Wi-Fi network changes.

Thanks. Hadn't been for your reply, I'd have never found the skip button wasn't disabled. Poor Colour choice. 

As for me, I'm using the same Wi-FI but i dual booted into Win10 and then back to Ubuntu 20.04.1 LTS and that occasionally triggers this error in Telegram Desktop v2.3. Skipping solves it though.
