### ISSUE TITLE
An option to copy user's first name and last name

### ISSUE THREAD

**Issue by Kolahzary** [telegramdesktop/tdesktop#1783]
The problem is when one of my friends writes his name in Chinese and I want to search his name in google in order to find what is his real name. It's impossible! because simply I can't read or write Chinese characters and Telegram doesn't have **An option to copy user's first name and last name**!
Regards,

**Comment by telegramdesktop** [comment]
@Kolahzary You can select his message (right click -> Select Message) and then Ctrl+C, his message text will be copied together with his name and date the message was received.

**Comment by DaFri-Nochiterov** [comment]
![image](https://cloud.githubusercontent.com/assets/10401817/13810738/836692ce-eb9b-11e5-81af-b878577cbddd.png)

Can you add this to menu, when right click on username, please? :blush:

> * Copy name
> * Copy phone number
> * Copy username

**Comment by k4ml** [comment]
Found this issue when I want to copy my contact's phone number, but I can't select it and use Command + C to copy it. Turn out you can copy it using context menu like in screenshot above. What I can say is that the feature is not easily discoverable. It's common when people want to copy something, they will select (highlight) it first, and then open up the context menu, or immediately using Ctrl/Cmd + C to copy it.

**Comment by stek29** [comment]
@auchri It was added in last version (0.9.34)

**Comment by auchri** [comment]
@stek29 oh yes, thank you!

**Comment by stek29** [comment]
@auchri Np
