### ISSUE TITLE
Tray icon

### ISSUE THREAD

**Issue by imaggg** [telegramdesktop/tdesktop#1784]
How change icon in tray from blue to gray?

![qqqw](https://cloud.githubusercontent.com/assets/5354328/13798571/9e0365f6-eb20-11e5-8f60-d7c7aef0b05a.png)
![qqqw](https://cloud.githubusercontent.com/assets/5354328/13798572/9e088464-eb20-11e5-993a-efaba963a074.jpg)

**Operating system:** Intel i3, gt630m, 4gb, elementary os 0.3.2
**Version of Telegram Desktop:** 0.9.33

**Comment by DaFri-Nochiterov** [comment]
Use magic of waiting, my friend

**Comment by telegramdesktop** [comment]
No way to do that yet :(

**Comment by agdemore** [comment]
@imaggg what theme of elementary os do you use

**Comment by imaggg** [comment]
@agdemore Theme: Arc Darker; Icons: Paper; and custom conky on desktop.

**Comment by agdemore** [comment]
@imaggg thanks! it's nice

**Comment by auchri** [comment]
Duplicate of #1199
