### ISSUE TITLE
[service request] Remove the distinction between regular and super groups.

### ISSUE THREAD

**Issue by chungy** [telegramdesktop/tdesktop#1785]
First off, I'm sorry that this may be a bit out of scope on this repo, but sadly I can't find any better venue to make suggestions.

Splitting groups and supergroups causes confusion, and worse, offers different sets of features depending on the type.

Regular groups:
 * Only up to 200 members
 * Supports everyone-as-admin operation
 * Messages are deleted only on the user's side that had deleted it
 * If individual admins are selected, then only admins can invite back into the group

Super groups:
 * Up to 5000 members
 * Does not support everyone-as-admin
 * Deleted messages affect everyone's view
 * Supports post editing
 * Pinned posts
 * Allows non-admins to invite people

Each group type has its own set of advantages, and deciding between the two means trading off other features. I think it would be best if all groups were merged into a unified kind, the unique features of each shouldn't require this sort of technical split; on the backend, this would probably just require regular groups be all converted to what are currently termed supergroups, and giving them the features to run with everyone-as-admin and the ability to *hide* messages from view per-user, not necessarily delete them (in fact, I'd go as far to say the Delete option should be removed if everyone-as-admin is used, or reserve it for the group creator).

I had converted a group I made for a bunch of friends, to a supergroup. It has only 19 people, and for the large part it went smoothly, except for one person that got fairly ornery about why such a small group was being converted. Post editing was the primary benefit, but the confusion did make things rather annoying to deal with.

**Comment by diazbastian** [comment]
@chungy I do not think the solution is to unify the systems. I think the groups are an ideal tool for work teams, it's more personal and democratic. 

What is needed is an indicator that differentiates a group of a supergroup, in TDesktop is difficult to distinguish easily. What is needed is an indicator that differentiates a group of a supergroup. Perhaps a different symbolic icon to chat list, and indicate directly if a group or supergroup in contact information (also for channels).

![supergrupo](https://cloud.githubusercontent.com/assets/5126124/13800761/00babe58-eb0b-11e5-9151-b2d0979026c9.png)

**Comment by chungy** [comment]
> I do not think the solution is to unify the systems. I think the groups are an ideal tool for work teams, it's more personal and democratic.

I don't think unifying the systems would negate that. I don't see any real reason that supergroups couldn't gain the features unique to regular groups and remove any disadvantages.

**Comment by diazbastian** [comment]
@chungy Groups and supergroups use different technologies, this would be impossible without rewriting everything (I do not see necessary). In groups each user has a different history and can be managed by the user without affecting the others, however, in a supergroup it is a unique history, etc. They are very different things.

**Comment by mirh** [comment]
Service requests have nothing to do with telegram desktop. 
Ask in-app support for that.

**Comment by auchri** [comment]
yes

**Comment by chungy** [comment]
Where is in-app support?

**Comment by auchri** [comment]
@chungy Settings -> Ask a question
