### ISSUE TITLE
compile qt

### ISSUE THREAD

**Issue by vendforce** [telegramdesktop/tdesktop#1786]
Im running arch

can anyone telling me why everytime theres an update to telegramdesktop qt has to be recomplied
Ive had two updates to telegram in the last week and the recomplied of qt when its installed and its a bit of a process just for one application
 I dont have the slowest of computers but its takes more than 5 minutes to compile and thats from doing pacaur -Syu 

telegram is getting like atom editor it has to check all and reinstall  and check npm modules .. scrap that Ive no time for an application that takes more than 2 minutes to install

if this is the process for every update , Im out  ill use something else, I dont have time for something to be hoggin the process of an installation

**Comment by auchri** [comment]
Because Telegram Desktop uses a custom version of Qt.
