### ISSUE TITLE
Issue with autocompleting commands that contain numbers

### ISSUE THREAD

**Issue by bo0tzz** [telegramdesktop/tdesktop#1787]
When autocompleting a command that contains numbers (for example: /8ball@myexamplebot), the entire command is inserted upon pressing TAB.

### Steps to reproduce
1. Type "/8" in text field
2. Press TAB key to autocomplete the command

### Expected behaviour
Text box now contains "/8ball@myexamplebot"

### Actual behaviour
Text box now contains "/8/8ball@myexamplebot"

### Configuration
**Operating system:**
Win 10

**Version of Telegram Desktop:**
0.9.32

**Comment by mattrick16** [comment]
Can confirm, this happens to me as well.

**Comment by telegramdesktop** [comment]
@bo0tzz Thanks! I will fix that with the next version.

**Comment by stuntguy3000** [comment]
Can confirm @bo0tzz makes shit bots
