### ISSUE TITLE
Make media hotkey support toggleable

### ISSUE THREAD

**Issue by FrozenTux** [telegramdesktop/tdesktop#1788]
Telegram has apparently recently acquired support for media hotkeys to control music playback within the app.

While this is certainly a wanted feature for some users, it would be nice if there would be an **option to disable media key support in Telegram**, as it can get quite frustrating for an user that does not play media in Telegram on a regular basis and that uses media keys to control a media player running in the background.

This behaviour is not media-player or keyboard dependant, as I believe media hotkey support in Windows is universal.

### Steps to reproduce
1. Open media player (VLC, Spotify, foobar2000 for instance) and start playback
2. Select Telegram window
3. Try to use media keys to control playback

### Expected behaviour
Media hotkeys affect the music player (at least there should be an option to make it so).

### Actual behaviour
Media hotkeys affect Telegram, if music is currently playing. Otherwise, they do nothing.

### Configuration
**Operating system:** Windows 10 Education x64

**Version of Telegram Desktop:** 0.9.32

**Comment by telegramdesktop** [comment]
@FrozenTux Currently you can look into the «tdata/shortcuts-default.json» (near the Telegram.exe file) to see the shortcuts and then you can override them in «tdata/shortcuts-custom.json». You can specify "null" (without quotes) instead of the command name to disable the shortcut usage, like this:

[
    {
        "command": null,
        "keys": "media play"
    },
    {
        "command": null,
        "keys": "media stop"
    },
    {
        "command": null,
        "keys": "media previous"
    },
    {
        "command": null,
        "keys": "media next"
    },
    {
        "command": null,
        "keys": "media pause"
    },
    {
        "command": null,
        "keys": "toggle media play/pause"
    }
]

**Comment by beschoenen** [comment]
It would be nice if Telegram only captured the media keys when its media player is active, so when music is playing or paused.

**Comment by FrozenTux** [comment]
@telegramdesktop Thanks for your answer, it works. It would be nice to implement it as an actual option, or as @beschoenen suggested automatically capture them when media is playing

**Comment by wildweasel486** [comment]
I would like to chime in with my desire for this to be a supported option. I wasn't even aware Telegram had its own media player built-in; I have foobar2000 constantly open and playing and had to struggle for a bit to figure out why I couldn't skip tracks.

I can only hope that the devs haven't forgotten about this...unless they're busy with other stuff. I'm not trying to be impatient. =P

**Comment by beschoenen** [comment]
What happened here?

**Comment by auchri** [comment]
> It would be nice if Telegram only captured the media keys when its media player is active, so when music is playing or paused.

this.

**Comment by jovobe** [comment]
This seems to be a problem on macOS now.

**Comment by auchri** [comment]
@jovobe Update to the latest version, it's fixed.

**Comment by jovobe** [comment]
@auchri I'm on 0.10.16 on macOS. I think this is the latest version. This Issues is back since the last update.

**Comment by auchri** [comment]
Latest version is 0.9.19

**Comment by jovobe** [comment]
@auchri thank You for Your hint! It seems I was stuck on a very old version that the auto updater could not update. I'm now on version 2.27.51120 (which looks more like a native app) and the bug is gone.

**Comment by auchri** [comment]
That's another app 😁
