### ISSUE TITLE
Bots appear twice in the list when they were used recently

### ISSUE THREAD

**Issue by stuntguy3000** [telegramdesktop/tdesktop#1789]
### Steps to reproduce
1. Use an inline bot in another group chat or private message
2. Add that bot to the group
3. Type out the bots name

### Expected behaviour
The bot should only appear _once_ in the list, not twice.

### Actual behaviour
The bot appears _twice_!
![image](https://cloud.githubusercontent.com/assets/1522389/13833807/23f70820-ec39-11e5-885c-31b8be600cce.png)

### Configuration
**Operating system:**
Windows 10 Home Premium 64Bit

**Version of Telegram Desktop:**
0.9.32

**Comment by bo0tzz** [comment]
+1, have experienced the same issue.

**Comment by stuntguy3000** [comment]
Solved in https://github.com/telegramdesktop/tdesktop/commit/c8f2f6bc2bd784925d90722d90c4302c47b05382

**Comment by telegramdesktop** [comment]
@stuntguy3000 Fixed in 0.9.34 dev version.
