### ISSUE TITLE
Problems with docs

### ISSUE THREAD

**Issue by stek29** [telegramdesktop/tdesktop#1794]
There is some problem in [docs, building-xcode, Installing gyp](https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-xcode.md#install-gyp)
`sudo setup.py install`
It would give `sudo: setup.py: command not found` or run `setup.py` from path as root
It should be `sudo ./setup.py install`
Previous line has `./`, but line with `sudo` doesn't.
_PS: Sorry for overriding template :)_

**Comment by stek29** [comment]
One more issue in the same file: zlib occurs two times ([1](https://github.com/telegramdesktop/tdesktop/blob/dev/doc/building-xcode.md#zlib-128) and [2](https://github.com/telegramdesktop/tdesktop/blob/dev/doc/building-xcode.md#zlib-128-1))

**Comment by auchri** [comment]
@john-preston which one is right? ([1](https://github.com/telegramdesktop/tdesktop/blob/dev/doc/building-xcode.md#zlib-128) or [2](https://github.com/telegramdesktop/tdesktop/blob/dev/doc/building-xcode.md#zlib-128-1))?

I'll update my PR

**Comment by stek29** [comment]
I'm sure that 1 is right, because without external zlib build failed.
But it also required some changes in project, so maybe there is more problems
