### ISSUE TITLE
Old references to Resources/lang.txt 

### ISSUE THREAD

**Issue by stek29** [telegramdesktop/tdesktop#1798]
In `genlang.cpp` [L394](../blob/master/Telegram/SourceFiles/_other/genlang.cpp#L394) and [L478](../blob/master/Telegram/SourceFiles/_other/genlang.cpp#L478)
Also in README.md at [L83](../blob/master/README.md#L83)
They all have `Resources/lang.txt`, but this file is `Resources/lang.strings` now.

**Comment by john-preston** [comment]
Fixed in dev branch, will be merged to master eventually.
