### ISSUE TITLE
sounds use speakers even with usb headset plugged in

### ISSUE THREAD

**Issue by LiamDawe** [telegramdesktop/tdesktop#1803]
As the title says, if I plug in a USB headset (Ubuntu) and set my default audio to it, everything but Telegram uses it. Telegram decides to keep using my speakers.

**Comment by auchri** [comment]
Does Telegram use the headset if you restart it?

**Comment by LiamDawe** [comment]
Yes it does.

**Comment by auchri** [comment]
Duplicate of #776 then :)
