### ISSUE TITLE
Telegram chat window on Full Screen

### ISSUE THREAD

**Issue by S1AnGeR** [telegramdesktop/tdesktop#1807]
### Steps to reproduce
1. HDMI монитор 1920 х 1080
2.  Telegram на весь экран

### Expected behaviour
Tell us what should happen
Диалоги должны быть с разных сторон?

### Actual behaviour
Tell us what happens instead
Сейчас диалоги сливаются
http://take.ms/kYUVs
http://take.ms/z7mRR

### Configuration
**Operating system:**
Windows 10 x64

**Version of Telegram Desktop:**
0.9.32

### Logs
Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

**Comment by Kondra007** [comment]
This is **normal** behaviour since 0.9.2x versions.
You can push your messages to the right by unchecking "Adaptve layout" option in Settings.

Duplicate: #1651, #1663, #1638, #1664 and many more.

**Comment by stek29** [comment]
Обновите приложение до последней версии

**Comment by Kondra007** [comment]
@stek29 Это не поможет. 0.9.32 давно поддерживает адаптивный вид чатов. Проблема в том, что человек не зашел в настройки и не снял одну галочку.
Nope, the problem in that @S1AnGeR hasn't unchecked one tick in Setting. 0.9.32 supports disabling adaptive layout.

**Comment by auchri** [comment]
write english please
