### ISSUE TITLE
[Bug] Admin of supergroup can delete all creator's messages

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#1808]
### Steps to reproduce
1. Create supergroup with account A
2. Add contact B to supergroup and make him admin
3. Post some messages from A
4. Right-click on A's message (from B) and tick "Delete all messages from this user"

### Expected behaviour
You **can't** delete creator's messages
"Ban user" option shouldn't present when deleting creator's messages (it's not working for him)

### Actual behaviour
You **can** delete creator's messages

### Configuration
Windows 8 x64, Telegram Desktop 0.9.35dev
**And this problem is also present in Android version, so it looks like API bug**.

**Comment by auchri** [comment]
I don't think that's a bug, because there are two kinds of users in a supergroup:

* Normal users
* Admins

And why should admins not be allowed to delete messages of another admin?


Anyway, it's an api issue.

**Comment by Kondra007** [comment]
@auchri Please, read again: Admin can delete **creator's** messages.
Isn't this hierarchy correct?
Creator -> Admins -> Users

The situation when one **admin** can delete other **admin's** messages is normal of course.

**Comment by mintux** [comment]
it's very bad i need to delete message for myself in supergroup i have to see worst message from other users because of i can delete message from supergroup
