### ISSUE TITLE
Feature Request : option to disable authentication to prevent account hack attempts

### ISSUE THREAD

**Issue by sveinburne** [telegramdesktop/tdesktop#1810]
Someone is attempting to hack my account. Would be great if I could switch a button to prohibit new logins from unknown devices for, let's say, 1 week or X days... 

### Configuration
**Operating system:** Kubuntu 15.10

**Version of Telegram Desktop:** 0.9.24

**Comment by john-preston** [comment]
@sveinburne This has nothing to do with Telegram Desktop app, I'm sorry. You can try to reach out by «Ask a question» button in Settings or on official twitter https://twitter.com/telegram
