### ISSUE TITLE
Emacs key binding no longer working on 0.9.32

### ISSUE THREAD

**Issue by shouya** [telegramdesktop/tdesktop#1811]
Hi, it seems after upgrading to 0.9.32, emacs bindings (C-k, C-a, C-e, etc) in the text input doesn't work any more. Is this a bug or a feature?

Platform: OS X

**Comment by shouya** [comment]
Someone also mentioned this issue on #729

**Comment by stek29** [comment]
I have 0.9.34 dev, and they work for me.
Btw what OS X version are you using? Are you using TDesktop from AppStore or from tdesktop.com?

**Comment by tkimnguyen** [comment]
Not working for me an 0.9.49 on OS X 10.11.5

**Comment by auchri** [comment]
#729
