### ISSUE TITLE
Issue with duplicate download when opening the attachment again

### ISSUE THREAD

**Issue by rheech** [telegramdesktop/tdesktop#1812]
### Steps to reproduce
1. Send any video file (avi) to a friend as an attachment
2. Download the attachment by clicking the video icon in the chat room
3. After download completes, the video opens automatically; then, close the video
4. Click the video icon again in the chat room

![image](https://cloud.githubusercontent.com/assets/16962525/13975435/bddd2730-f0f8-11e5-825f-0164b924836e.png)

### Expected behaviour
If the attachment is already downloaded in the local, the application does not download the attachment again; instead, the application opens the local file.

### Actual behaviour
Telegram re-downloads the (duplicate) file and opens.

### Configuration
**Operating system:**
Windows 7 Enterprise SP1 x64
**Version of Telegram Desktop:**
0.9.32

**Comment by DaFri-Nochiterov** [comment]
> If the attachment is already downloaded in the local, the application does not download the attachment again; instead, the application opens the local file.

It's fine

> Telegram re-downloads the (duplicate) file and opens.

For what?

**Comment by rheech** [comment]
I found that most video attachments do not display previews like the screenshot above. I will report again if same thing happens again. Thanks.
