### ISSUE TITLE
Combin File Image text to geather in one message.

### ISSUE THREAD

**Issue by omoridi** [telegramdesktop/tdesktop#1816]
Hello
We need a feature to add one image with text and attached one file or music or movie to that.
can create this feature?

**Comment by john-preston** [comment]
@omoridi No way to make one message with an image, text and file inside.

**Comment by omoridi** [comment]
what about file with description. 
Like Video or Mp3 files.

**Comment by john-preston** [comment]
@omoridi You can paste an .mp3 file (first copy it in file explorer) and then you can add a caption to it.

**Comment by john-preston** [comment]
@omoridi But many Telegram apps (like mobile apps) still don't display that captions for files. They do display captions for video files.

**Comment by omoridi** [comment]
I think it's good idea to add file with description and photo cover. not only desktop for all devices.
and some device can add video with description but desktop can not.
some bot make some messages have no normal message. like hidden link

**Comment by john-preston** [comment]
@omoridi Desktop can't send files as video at all. But if you send video file just as file, it will be sent and if you paste it you can add caption.

You can send any image file with a thumbnail and a caption.

**Comment by omoridi** [comment]
suggest to telegram team to add this feature.

**Comment by auchri** [comment]
You can do this yourself via twitter or with the "Ask a question" feature in one of the official apps.
