### ISSUE TITLE
Telegram Desktop doesn't open and no meaninful error message ir shown

### ISSUE THREAD

**Issue by mariobaldini** [telegramdesktop/tdesktop#1819]
Hi all,

After an update a few weeks ago, my telegram stopped to open. No GUI or error message is shown. I searched for the possible cause or other related issue, but I'm not sure what is happening. 

Probably is something specific with my system and should not be treated as critical. 

But I'm willing to help to debug it, because even being specific/rare, I think that at least a meaninfull error should be displayed. 

**I tried to complete delete ~/.TelegramDesktop and download Telegram again, but the error persists. It's very frustating because it simply won't work anymore in this computer and I can't debug why. **

What further steps could I do to discover what error/conflict is happening in this machine?

Thank you all,

Mario

### Steps to reproduce
1. Open Telegram (by link for command line).
(started after an update a few weeks ago)

### Expected behaviour
Telegram GUI should appear or an error message be presented. 

### Actual behaviour
No GUI our Error message is shown (if it was open by a link, the user doesn't receive any feedback).
If it's by command line, the messages aren't clear about the error.

### Configuration
**Operating system:**
$ uname -a
Linux ideapad 4.5.0-040500-generic #201603140130 SMP Mon Mar 14 05:32:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"

Installed packages: http://hastebin.com/osaceqeyoh.hs

**Version of Telegram Desktop:**
Can't obtain it. App won't start. 
$ md5sum *
1417b6754104fb12079e531a05db67f7  Telegram
23d2e82fecccb0fb684d781439ae9f5d  Updater

### Logs
$ ./Telegram 
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
(Telegram:2722): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'
(Telegram:2722): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(Telegram:2722): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

Aldo tried to remove ~/.TelegramDesktop but the error persists.

**Comment by john-preston** [comment]
@mariobaldini What OS do you use? This did happen on the 0.9.32 version on Xubuntu 15.10, but was fixed in 0.9.33.

**Comment by mariobaldini** [comment]
@john-preston I do use Xubuntu 15.10. 

After updating the binaries and removing ~/.TelegramDesktop now the client works (v 0.9.36 dev).

Probably I tried updating before with the unfixed version. 

Thanks!

**Comment by mutuadavid93** [comment]
Solved it. 
Download Iobit Uninstaller. Then Powerful scan the remnants and shred them. Installer a new copy of telegram for PC.
then you are up!

**Comment by ReverseSun** [comment]
my telegram after a while well you know, just it won't load my account! I don't know what's the problem I just have to log on with another session...
