### ISSUE TITLE
Can't see hidden stickerpacks

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#1821]
### Steps to reproduce
1. Add stickerpack
2. Using Android version, hide it
3. Open "Arrange stickerpacks" menu on Desktop

### Expected behaviour
I should see hidden stickerpacks with ability to re-enable them

### Actual behaviour
I see only enabled stickerpacks and official "Great minds" disabled (it's really disabled)

### Configuration
**Operating system:** Windows 8.1 x64
**Version of Telegram Desktop:** 0.9.34 dev

**Comment by john-preston** [comment]
@Kondra007 Currently tdesktop can only delete not official sticker packs, not hide them. So I can't show them in the box, otherwise saving the (unchanged) state will delete all of them, while they were only hidden :(

**Comment by Kondra007** [comment]
Ah, that's okay then.
Thanks!
