### ISSUE TITLE
Allow emoticons without minus symbol

### ISSUE THREAD

**Issue by matteomigliore** [telegramdesktop/tdesktop#1822]
### Expected behaviour
Please allow to insert short emoticons text, for example :) :D ;), without the minus symbol, to be faster sending messages.

### Actual behaviour
Minus required in all or a lot of emoticons.

**Comment by auchri** [comment]
See #307

**Comment by stek29** [comment]
Why everyone is making duplicates?
Is it so hard to search before creating?

**Comment by auchri** [comment]
Seems so :angry:

**Comment by matteomigliore** [comment]
When all users in my system are doing something wrong I start to think that the problem is my system, not the users.
In this case, there are too many issues and no auto suggestion from github that helps to prevent to insert duplicates.
Also on Stackoverflow you can find a lot of duplicates, without controversy of anyone, just close the issue.
Thank you.
