### ISSUE TITLE
[UI] Change chat info link in compact mode

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#1824]
### Steps to reproduce
1. Open Telegram
2. Switch to compact mode (minimum)
3. See info link next to the new search button

### Actual behaviour
In compact mode the word "info" appears as a link to the contact/group/channel info. On the other hand, in normal mode an arrow appears. This is strange, because in compact mode is necessary to minimize the interface elements.
One downside is that the use of a word is affected by its translation into another language. For example in Spanish would be "**información**", the length of the word interferes with other interface elements such as the name of the chat and actions of other users: "John Williams is writing..."

![current](https://cloud.githubusercontent.com/assets/5126124/14058558/2c954b92-f303-11e5-8881-bfaebf45ca61.png)

### Expected behaviour
The word "info" can be replaced by a symbolic icon or the contact profile picture.

![proposal](https://cloud.githubusercontent.com/assets/5126124/14058627/4d709130-f305-11e5-8a6a-4fa0a97a5497.png)

### Configuration
Fedora 23 64 bit (gnome 3.18)

**Version of Telegram Desktop:**
0.9.35 dev

**Comment by john-preston** [comment]
And it is there! In 0.9.41 version :)
