### ISSUE TITLE
OSX build - @gif bot gifs do not animate

### ISSUE THREAD

**Issue by draeath** [telegramdesktop/tdesktop#1827]
On OSX Telegram Desktop 2.05.41261, from [App Store on El Capitan](https://itunes.apple.com/us/app/telegram/id747648890), it seems that linked gifs do not animate correctly anymore.

Previously, gifs would stand by until clicked, at which point they would download and animate until focus switched away from the client. Now, they immediately return to idle after the download animation.

I [recorded a short clip of the behavior.](http://screencast.com/t/dNsVqLakAyi7)

**Comment by stek29** [comment]
OS X native app is **different app**, it's **not** TDesktop

**Comment by draeath** [comment]
Ah, sorry about that. There seems to be another one on the App Store as well. Is either of these more "official" than the other?

I'll go post this issue on the correct tracker as well, thanks - and I apologize about flash. The only thing I know about quicktime is the nightmares it gave me in the 90s, I won't go anywhere near it since heh)

**Comment by stek29** [comment]
I don't think so.
I recommend using TDesktop because it's development is much more active, and also it's crossplatform
The only benefit is secret chats, but everything else is a nightmare IMHO.

It's better than Flash Player. Just use it to record screen, nothing else.
