### ISSUE TITLE
[feature request] Square avatar

### ISSUE THREAD

**Issue by lakitu13** [telegramdesktop/tdesktop#1828]
I don't like this trend of round avatars or think they're an improvement. Please make it optional.

**Comment by stek29** [comment]
Heh, may this one became as popular as "messages on left side" was?)

**Comment by diazbastian** [comment]
@lakitu13 The new style of rounded avatars is a feature that was asked many times before, also the design is equated with mobile versions (Android/iOS). I think this helps unify the user experience.

**Comment by SolG00dguy** [comment]
I don't see any reason to force this feature. Making it optional and just a simple tick in the settings is a much easier and understandable approach, those that want square avatars get what they want, and everybody stays happy.

**Comment by stek29** [comment]
@diazbastian OS X native and Telegram Web clients also have this style)

@SolG00dguy It just makes code more complicated and may cause new bugs.
Also it requires developer's time which could be spend for other, more important things.

**Comment by auchri** [comment]
It's not good for user experience to add option for every little thing.

Also, as @stek29 stated, all other telegram apps have rounded avatars. So it's just logical to add rounded avatars to tdesktop too.

**Comment by lakitu13** [comment]
I use Telegram for group messaging, exclusively. That's not just a little thing to me, looking at avatars to identify multiple users is pretty much half of my experience and rounded avatars are simply disgusting to me. If square avatars can't be done I'd rather be able to hide them.

**Comment by f242** [comment]
@auchri 
> It's not good for user experience to add option for every little thing.
plus messenger on android with a lot of little options have higher rating than original telegram app
4,4 https://play.google.com/store/apps/details?id=org.telegram.plus
4,2 https://play.google.com/store/apps/details?id=org.telegram.messenger

**Comment by DaFri-Nochiterov** [comment]
@f242 
> 4,4 https://play.google.com/store/apps/details?id=org.telegram.plus

33,777 total

> 4,2 https://play.google.com/store/apps/details?id=org.telegram.messenger

1,734,734 total

**Comment by f242** [comment]
@DaFri-Nochiterov 
because it's unofficial app, but 33,777 is enough for an objective assessment

**Comment by diazbastian** [comment]
@f242 The design goal of Plus Messenger is very different from Telegram. All official applications should follow the same design guidelines.

Plus Messenger is a unofficial Telegram app and only for Android platform.

**Comment by f242** [comment]
@diazbastian 
>The design goal of Plus Messenger is very different from Telegram

wrong, plus messenger based on source code of original telegram app

i talk about messenger just to show you an example, that "add option for every little thing" is not bad

**Comment by diazbastian** [comment]
@f242 Yes, Messenger Plus is a fork of Telegram and is exactly a fork to add different features to the official application. Plus Messenger has another design, other criteria to add features and mainly prioritizes customization by the user.

What I wanted to show is that your example was not appropriate, as they remain different applications (fork) with different design objectives. Telegram has to deal with different platforms. This should maintain guidelines similar design to deliver a similar user experience across all platforms.

**Comment by f242** [comment]
>Plus Messenger has another design
lol, i think you don't saw this ANOTHER design, i show you
![clipboard](https://cloud.githubusercontent.com/assets/10371194/14161176/5a99bc04-f6ea-11e5-90be-de4a4bdc00a2.png)
i will repeat that if we have two similar applications and one with more customisable than second then users prefer first because there are "options for every little thing"

**Comment by diazbastian** [comment]
@f242 Come on, you have lost the focus of discussion. You can look at 10 Telegram users and will have the same design, however, you can look at 10 users of Messenger Plus and find 10 different configurations (those little changes that you were defending). 

Please see: https://core.telegram.org/tsi/feature_philosophy

**Comment by f242** [comment]
@diazbastian 
at start 10 users of messenger plus will have same default configurations, and if they want to change some options for more comfort - they do that or not, they decide for themselves
you say that ability to fine tuning of program is bad and i don't understand why

**Comment by diazbastian** [comment]
@f242 I did not say that customization is a bad thing, however, I said that is not relevant or does not meet the design goals of Telegram, particularly Telegram Desktop (Yes, this is Telegram Desktop and not of Plus Messenger ).
Moreover remember that we are talking about viewing profile photos. Now it is the same as other official applications. Is it so important for developers to spend time to add a configuration section to change rounded avatar to square avatar? 
I do not see sense. For my part I will leave the discussion over here. Thank you.

Cheers

**Comment by auchri** [comment]
I you want more options in Telegram Desktop, someone could create a fork and add options to it ... "Plus Desktop Messenger" :grinning: 

The Android and iOS App also doesn't have the option, so it won't be included in telegram desktop.

**Comment by DaFri-Nochiterov** [comment]
@auchri, "Telegram Desktop+"

**Comment by stek29** [comment]
@DaFri-Nochiterov "TDesktop Plus" IMO

**Comment by disharmonized** [comment]
it s a pity...

**Comment by f242** [comment]
also
**Guidelines for user names and account pictures**
https://msdn.microsoft.com/en-us/library/windows/apps/jj649134.aspx
![default](https://cloud.githubusercontent.com/assets/10371194/14406326/4fc2ced6-fead-11e5-8e1b-9c42082bd6e9.PNG)

**Comment by auchri** [comment]
![image](https://cloud.githubusercontent.com/assets/5092164/14406350/7c4afd3c-fea5-11e5-96df-3e22b1ab5858.png)

![image](https://cloud.githubusercontent.com/assets/5092164/14406353/86882770-fea5-11e5-9a30-5fc82f15c1a9.png)

**Comment by f242** [comment]
@auchri but we talk about square avatars in desktop application, right? mobile android & ios may have own ui guidelines

**Comment by stek29** [comment]
@f242 OS X guidelines suggest rounded ones.
TDesktop != TWindows

**Comment by f242** [comment]
@stek29 you didn't posted link to osx ui guidlines
windows is the number one desktop os with [90% marketshare](https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=8&qpcustomd=0)

**Comment by stek29** [comment]
@f242 Lets make everything for mustdie only then because it has "90% marketshare"!
_It's getting off topic..._

**Comment by aphirst** [comment]
I would also love to see an option to toggle between Circle and Square avatars. It's even encroached onto Twitter, and although there are userscripts which can help that in the browser, with the official App you're stuck with the "trend" no matter how much you hate it.
