### ISSUE TITLE
e guidelines for contributing

### ISSUE THREAD

**Issue by okofob** [telegramdesktop/tdesktop#1830]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

### Logs
Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

**Comment by auchri** [comment]
Guidelines are (here)[https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md]
