### ISSUE TITLE
Problem with OpenSSL during telegram compilation

### ISSUE THREAD

**Issue by Beshkarev** [telegramdesktop/tdesktop#1832]
Hello.
I tried build telegram under linux with QtCreator. I used the [instruction](https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-qtcreator.md).
I opened Telegram.pro file and changed build directory in project settings.
After, during compilation telegram, I receive error
`qsslsocket_openssl_symbols.cpp:-1: error: undefined reference to `SSL_accept'`
 and many other linked with OpenSSL in "qsslsocket_openssl_symbols.cpp" file.

Please, help me solve this problem.

**Comment by Beshkarev** [comment]
![screenshot at 2016-03-30 10 53 10](https://cloud.githubusercontent.com/assets/10604455/14135376/c478ed5a-f665-11e5-8985-a56c3802e2b3.png)

**Comment by john-preston** [comment]
Yeah, I've moved ssl libs to a build script, sorry. In fact, I can make Qt Creator to build it only with dynamically linked openssl, while I use static linked openssl. I think I'll modify the instructions to use dynamic linked so at least it will build.

**Comment by Beshkarev** [comment]
I compiled Telegram successfully.
When configured QtStatic, instead
`OPENSSL_LIBS='/usr/local/ssl/lib/libssl.a /usr/local/ssl/lib/libcrypto.a' ./configure -release -force-debug-info -opensource -confirm-license -qt-zlib -qt-libpng -qt-libjpeg -qt-freetype -qt-harfbuzz -qt-pcre -qt-xcb -qt-xkbcommon-x11 -no-opengl -static -openssl-linked -nomake examples -nomake tests`
I used
`OPENSSL_LIBS='-L/usr/local/ssl/lib -lssl -lcrypto' ./configure -release -force-debug-info -opensource -confirm-license -qt-zlib -qt-libpng -qt-libjpeg -qt-freetype -qt-harfbuzz -qt-pcre -qt-xcb -qt-xkbcommon-x11 -no-opengl -static -openssl-linked -nomake examples -nomake tests`

Changed only 
`OPENSSL_LIBS='/usr/local/ssl/lib/libssl.a /usr/local/ssl/lib/libcrypto.a'`
to
`OPENSSL_LIBS='-L/usr/local/ssl/lib -lssl -lcrypto`

After run
`make -j4`
`sudo make -j4 install`


Found the in [Qt Documentation](http://doc.qt.io/qt-4.8/ssl.html)

**Comment by john-preston** [comment]
@Beshkarev Great! Thanks, I'll update the instructions accordingly.

**Comment by Beshkarev** [comment]
@john-preston Thanks for your answers!
