### ISSUE TITLE
[feature request] searching text for Asian languages

### ISSUE THREAD

**Issue by kenga** [telegramdesktop/tdesktop#1834]
In several Asian languages (e.g. Chinese, Japanese, Korean, etc.), unlike English or others, spaces are never strict word dividers. 

For example, for a message like this:
中文測試
I guess currently the whole phrase is indexed for Chinese, therefore, by searching "中文測試" the message can be found out. However, searching "中文" or "中" is no good, which we Chinese people usually do in searching. 
In order to do text searching for these languages, string tokenization is required during indexing, which will segment the message to 中 文 測 試 . This will definitely requires coding for the server side.

I don't know if here is the right place to request this feature. If there is a more suitable place to request this feature, please kindly let me know.

Thanks for your good work!

**Comment by stek29** [comment]
I think you should use "Ask a Question" button in app...

**Comment by taijuin** [comment]
same as：#1562

**Comment by stek29** [comment]
@auchri Duplicate here.

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/724
