### ISSUE TITLE
[feature] Mark listened speech/audio message as listened

### ISSUE THREAD

**Issue by AduchiMergen** [telegramdesktop/tdesktop#1836]
### Expected behaviour
User should see that message was played.

### Actual behaviour
Played message is no different from the new.

**Comment by john-preston** [comment]
Works fine for me. When the message was not played by the recipient it is marked with a dot. When it was played by the recipient the dot disappears:

![image](https://cloud.githubusercontent.com/assets/17900494/14101016/3719e444-f59a-11e5-9cca-6710c256753f.png)

**Comment by AduchiMergen** [comment]
I mean messages listened by me. 
like:
<img width="416" alt="2016-03-29 13 41 47" src="https://cloud.githubusercontent.com/assets/2733470/14101130/77838f40-f5bc-11e5-8c2a-39ae138ce41a.png">
here i don't know what messages i already listened

**Comment by john-preston** [comment]
In the channels the listened / not listened status for voice messages is not supported by Telegram API :(

**Comment by AduchiMergen** [comment]
@john-preston @auchri 
But Telegram Desktop can mark the message, which played? without sync with api

**Comment by stek29** [comment]
@AduchiMergen  AFAIK TDesktop doesn't have LocalStrorage, so it's just nowhere to store this.
That's also prevents from adding secret chats.
