### ISSUE TITLE
Cannot view images normally when using windows remote desktop

### ISSUE THREAD

**Issue by XGowe** [telegramdesktop/tdesktop#1838]
### Steps to reproduce
1. Run Telegram Desktop client normally;
2. Click any images in chat window in order to view it of a bigger or full size;
3. Then close that view window;
4. Use windows RDP (mstsc.exe on windows or other clients) (may be from a lower resolution device, I have not verified it) to connect to the computer which Telegram Desktop client is running on;
5. Repeat step 2.

### Expected behaviour
View images normally as the same as what it is without RDP.

### Actual behaviour
- The image clicked did not appear in the center of the screen as usual. It appeared actually in the left bottom, and some of it exceeded the screen.
- Besides, the image viewer showed the image previously clicked rather than the image wanted and the next/last button could not take effect.

### Configuration
**Operating system:**
Windows 10 Pro (Build 10586.164) with 1920*1080px resolution

**Version of Telegram Desktop:**
version 0.9.32

**Comment by f242** [comment]
+1
also after rdp session sound doesn't work

**Comment by Torvin** [comment]
same as #1542. this should be closed as a duplicate

**Comment by XGowe** [comment]
As @Torvin said, this should be the same problem as #1542 .

**Comment by Torvin** [comment]
@f242 could you please report this as a separate bug? If one does not exist already.
