### ISSUE TITLE
Upload Queue lost after search somethings

### ISSUE THREAD

**Issue by omoridi** [telegramdesktop/tdesktop#1839]
If I had a upload queue in channel and waiting until the upload was finished. if while upload working I search somethings, when I back to channel I can not see the upload queue. but upload do it only displaying have problem.
And in this mode if add a post! insert my post after last post queue and do not add in end of queue.

**Comment by auchri** [comment]
Please use our template next time, important information is now missing.

Which version of telegram desktop do you use?

**Comment by omoridi** [comment]
this bug in on version 0.9.32 and previous version.

**Comment by john-preston** [comment]
@omoridi Yes, there is such problem, all the temporary messages (that are not sent yet, but sending) and all the client side messages (like the "new features" message from Telegram Notifications when updating to a new version) are lost when you go to the old part of the messages history and then back to the end of the conversation :(
