### ISSUE TITLE
Forward message to multiple people

### ISSUE THREAD

**Issue by mahdiG** [telegramdesktop/tdesktop#1841]
Hi. Imagine it's new year. You wanna say happy new year to 20 (or more) of your contacts. So it would be good to send (or forward) a message to many (or all) of your contacts.

**Comment by stek29** [comment]
You mean Broadcast's?

**Comment by mahdiG** [comment]
Yeah‌, but not like channels. Like you press forward and then select multiple contacts and then send to them. No need to make a channel only for that one time and then make another channel for some other people...

**Comment by stek29** [comment]
Yea, I've got it)

**Comment by stek29** [comment]
Yea, I've got it)
Like in iOS for channel messages

**Comment by DaFri-Nochiterov** [comment]
May rename this issue to "Quick Share Button"?

**Comment by Aokromes** [comment]
I like the idea, sometimes i wanna share one link to multiple groups/individuals and this feature will ease this :)

**Comment by amiremami** [comment]
Yeah, this is a must. Because many times I want to share an item with many contacts.

**Comment by kirsan31** [comment]
In 1.**2** the forwarding interface was redesigned, but sadly no multi-forwarding yet :(

**Comment by Aokromes** [comment]
i was thinking, can't we have a drag and drop like thing for forward messages like when we select multiple photos or files on the lists?

**Comment by SmartManoj** [comment]
[Using telethon](https://smartmanoj.blogspot.com/2019/06/broadcast-message-in-telegram.html)

**Comment by adrianopol** [comment]
> i was thinking, can't we have a drag and drop like thing for forward messages like when we select multiple photos or files on the lists?

@Aokromes, drag and drop works perfectly for a long time in desktop version, but the topic is about selecting some messages, and selecting some contacts/chats to forward them to.

Your humble has to switch from desktop client to the mobile one when he needs to send something to 4+ contacts...

**Comment by mdan312** [comment]
See how it is in WhatsApp => we shoud have something similar

**Comment by graphixillusion** [comment]
This is something that we really need. What about a dedicated option to also create a special "forwarding group"? I mean, if i need to forward a message to always the same group of people/groups, i can save them in a group so when i need to forward i can select the group instead. What do you think about it?

**Comment by azzimuth** [comment]
Why is this still not implemented? It is present in all mobile clients and even Webogram.

**Comment by AhyaH-YHWH** [comment]
why Bots and Channels have this Feature Available ( tapping on share arrow in each post)
but not for messages in Private chats and groups?

Telegram Web already Allows choosing multiple Chats when Forwarding, for years

**Comment by O-Smudo-O** [comment]
Please make this real. Forwarding to multiple Contacts is a main feature for all messenger tools!!

**Comment by luke123it** [comment]
This limitation is very annoying! And it isn't reasonable that this feature is missing from the desktop version while being available on the mobile version (of course, else it would be a major missing feature compared to whatsapp and other competitor apps)

**Comment by Izofeu** [comment]
It's 2022. Can we get this feature?

**Comment by dansouza** [comment]
It's August 2022. Can we get this feature?

**Comment by foad322** [comment]
it is available in Telegram web old version (legacy) , but in version Z or K switch this is not possible to forward messages to multiple contacts and groups. Isn't it implemented yet?

**Comment by greenpark-code** [comment]
> Why is this still not implemented? It is present in all mobile clients and even Webogram.

(~two years later, ~6 years after the thread was started, but the feature is still not there despite the owner of the platform announcing he wants to develop decentralized apps to help fight censorship)

Do you mean https://webogram.ru/ ?

**Is it a legit alternative or a honey pot to collect Telegram users login data?**

**Comment by greenpark-code** [comment]
It's December 2022. Can we get this feature?

**Comment by azzimuth** [comment]
> Do you mean https://webogram.ru/ ?
> 
> **Is it a legit alternative or could it be a honey pot to collect Telegram users login data?**
I mean this https://github.com/zhukov/webogram. But I see that it's archived but I have myself implemented the multiple forward functionality there https://github.com/zhukov/webogram/pull/1588.

**Comment by greenpark-code** [comment]
> > Do you mean https://webogram.ru/ ?
> > **Is it a legit alternative or could it be a honey pot to collect Telegram users login data?**
> 
> I mean this https://github.com/zhukov/webogram. But I see that it's archived but I have myself implemented the multiple forward functionality there [zhukov/webogram#1588](https://github.com/zhukov/webogram/pull/1588).

Thank you.
Wow, your code has been merged, that would be good news, I'm trying Webogram...

After selecting various posts in a chat, I click on the arrow pointing to the right, but how would I select more than one receipt? When I select the first one, it enters that chat, if I press the "send" button the posts get forwarded to that chat, finished, I don't see a chance to select more than one receipt before sending.

**Comment by greenpark-code** [comment]
@azzimuth Thnks again. I've cloned [the repository to which you contributed](https://github.com/zhukov/webogram), but it seems as I can't install the required npm-related packages on this Ubuntu 18.04.5, there is apparently some version number conflict that apt-get can't resolve without breaking the system.

**Comment by greenpark-code** [comment]
@azzimuth Thanks again. I've cloned [the repository to which you contributed](https://github.com/zhukov/webogram), but it seems as I can't install the required npm-related packages on this Ubuntu 18.04.5, there is apparently some version number conflict that apt-get can't resolve without breaking the system.

**Comment by azzimuth** [comment]
Why don't give a try to newer clients? Zhukov's is marked as legacy for a reason.

**Comment by azzimuth** [comment]
@greenpark-code, yes, I meant K and Z. Pity that they do not have that functionality. I can see that there is an open issue for [K](https://github.com/morethanwords/tweb/issues/166) but none for Z.

**Comment by greenpark-code** [comment]
Thank you again @azzimuth (it's unbelievable that Telegram doesn't have such a basic feature).

**Comment by azzimuth** [comment]
But Telegram has this feature. At least the mobile apps and some of other clients.

**Comment by greenpark-code** [comment]
I really need it on desktop.

**Comment by 23rd** [comment]
> I really need it on desktop.

It is available since v4.4.0.

**Comment by azzimuth** [comment]
> It is available since v4.4.0.

Why is this issue still open then?

**Comment by graphixillusion** [comment]
> > I really need it on desktop.
> 
> It is available since v4.4.0.

I have version 4.4.1 installed and still not possible. How to do that? Is there a specific way to do?

**Comment by greenpark-code** [comment]
> > > I really need it on desktop.
> > 
> > 
> > It is available since v4.4.0.
> 
> You are right. Right click on the chat will enter in selection mode. Thank you for the update

WOOOOW THANK YOU A LOT!!!!!
