### ISSUE TITLE
[Feature Request] Force to send Messages in right Order

### ISSUE THREAD

**Issue by Falk5T** [telegramdesktop/tdesktop#1844]
### Steps to reproduce
1. Upload several Files like Pictures in Areas with bad reception (Slow upload)
2. Comment Text between pictures, relating to the right Order of pictures
3. Observe how others receive the entire Text and finally the Images in a wrong order

### Expected behaviour

It should be possible to prioritise sending in desired order or messages should go out with some
sort of timestamp and let the receiving client sort the messages correspondingly

### Actual behaviour
Clients send and receive as fast as possible, disregarding message order

![wrong](https://cloud.githubusercontent.com/assets/18178258/14160534/1dfb55e4-f6dd-11e5-8290-b638729b4407.jpg)

Here for example I sent a sticker, then a photo, then again a sticker and after that another photo.
On my mobile client It displayed in the right order, receiving clients showed the order in the picture.

**Comment by stek29** [comment]
So they should be send synchronized, and not async like now?

**Comment by Falk5T** [comment]
That would be one way to solve it, but I think that's not optimal. Imagine you send a really big file like a video clip. No text messages could be sent before the File is fully uploaded. 

The best solution I think would be to send a system message to all receiving clients, so those know that a  file is being sent. This should cause the chat to either just reserve the space or already display the type of file as a placeholder. (For example you send a picture, it's not fully uploaded but all receiving clients already display a placeholder for Images, which also shows that it's still uploading.

**Comment by stek29** [comment]
Then it's [api issue]
