### ISSUE TITLE
Accents disappearing in spanish

### ISSUE THREAD

**Issue by DukeVante** [telegramdesktop/tdesktop#1845]
### Steps to reproduce
1. Open the Telegram Desktop app for Linux
2. Enter a conversation
3. After a while, you won't be able to write using any letter with accents in spanish keyboard (not checked with french or other keyboards with accents)

### Expected behaviour
You should be the letter written with the accents in the text field for the message

### Actual behaviour
After a while using the app, the accents simply stop working

### Configuration
**Operating system:**
Ubuntu GNU Linux 14.04 LTS
**Version of Telegram Desktop:**
0.9.33
### Logs
Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

**Comment by stek29** [comment]
#1360 Duplicate?
