### ISSUE TITLE
No indication that message has been edited or deleted

### ISSUE THREAD

**Issue by Cassolotl** [telegramdesktop/tdesktop#1846]
Hello!

Editing or deleting messages in supergroups is great, but it's open to abuse. When there is no indication that a message has been deleted or edited, it's really quite easy to make someone else look bad.

A "message deleted" placeholder would be good. So would a "message edited by [user] [timestamp]" comment on edited messages.

If this isn't the place to mention this, please point me at the place where I should request this feature. I know some things have to be changed further up rather than just in the client, but I don't know what!

 
### Steps to reproduce
1. Post message.
2. Someone else replies to message that makes sense in context.
3. Delete original message.

### Expected behaviour
When a message is deleted, it is replaced by a message that says "message deleted by [user], [timestamp]".

When a message is edited, it has a comment added that says "message edited by [user], [timestamp]".

### Actual behaviour
Deleted messages and edited messages leave no trail. There is no indication that a message has been edited or deleted.

### Configuration
**Operating system:** Mac OS X 10.11.3.

**Version of Telegram Desktop:** 0.9.32

### Logs
Logs not needed, I think?

**Comment by john-preston** [comment]
@Cassolotl Well, actually there is a "Deleted message" reply placeholder, so if you've replied to a deleted message you should see it (at least in Telegram Desktop).

All other mentioned things are not support by Telegram API. There is an official twitter account https://twitter.com/telegram and «Ask a question» button in Settings of every official app.

**Comment by Cassolotl** [comment]
@john-preston Ohh, I didn't know about the "Deleted message" reply placeholder - that's good.

I will tweet at the Telegram Twitter account with a link to this conversation, in the hope that they'll see it and provide API possibilities. Thank you!
