### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by mhspace** [telegramdesktop/tdesktop#185]
Please implement a setting that allows us to change the colorful Telegram color palette into a darker theme, such as the new Windows 10 apps. Black, white, 2-3 shades of grey (not 50! :laughing:) and deep-blue.

The following theme from the Windows 10 Photo's app is an example of a very appealing, eye-friendly colour palette.

![screenshot_1](https://cloud.githubusercontent.com/assets/5364372/9370139/3fb7f314-46ce-11e5-854d-ab01e5c360c0.png)

(Description by @BAPostma)

**Comment by SirGamlet** [comment]
Plus one. Dark theme is needed.

**Comment by KindWizzard** [comment]
It would be nice.

**Comment by X-NoNAME** [comment]
+1

**Comment by ProstoKorol** [comment]
+1

**Comment by JonathanMH** [comment]
+1

**Comment by Drakulix** [comment]
+1

**Comment by intrd** [comment]
+1

**Comment by formatq** [comment]
+1

**Comment by joshery420** [comment]
+1

**Comment by branderxero** [comment]
+1

**Comment by DarkAbsolutE** [comment]
+1

**Comment by intrd** [comment]
+1

**Comment by bil-elmoussaoui** [comment]
+1

**Comment by BAPostma** [comment]
+1 (made accidental duplicate in #1019)

**Comment by lindhe** [comment]
+1

**Comment by ErikThorsell** [comment]
+2

**Comment by foxmajik** [comment]
It's been almost a year and this basic functionality hasn't been added.

**Comment by mudrd8mz** [comment]
+1, TIA

**Comment by TiagoDanin** [comment]
I miss a dark theme, +1

**Comment by aalmiramolla** [comment]
+1

**Comment by joshery420** [comment]
@foxmajik To be clear, it's a style issue, not a functionality issue. If it was a missing or problematic feature it'd be another story. As it stand, a dark theme doesn't change what the program can do, only how it looks doing it.

If anyone here was really that desperate for it I'm pretty sure they could make a dark theme in their own fork. Might even get lucky and get it merged back into the master branch. ;)

**Comment by auchri** [comment]
@joshery420 +1

**Comment by vitorgrs** [comment]
Would be very nice. Better yet, an universal app.

**Comment by Thermionix** [comment]
I'd be very pleased with just an option to 'Use system colours'

**Comment by lawrencegs** [comment]
That would make some of the stickers... really ugly

**Comment by thexbasic** [comment]
+1, probably overread this

**Comment by saeidscorp** [comment]
+1, actually this would be very nice!

**Comment by Francesco149** [comment]
yes please

**Comment by maxomaniak** [comment]
Very yes! Very please! +1

**Comment by Marty** [comment]
+1
General theming functionality would be very nice.
I would love a SSH theme :D

**Comment by vital-dhaveloose** [comment]
+1

**Comment by wadecore** [comment]
Please do this. My mole man eyes cannot stand the brightness at night.

**Comment by electricessence** [comment]
+1 (even though I love Telegram as is)

**Comment by aechchiki** [comment]
+1

**Comment by Kylllyk** [comment]
+1

**Comment by jordan30001** [comment]
+1

**Comment by VegaDeftwing** [comment]
+1, pleeeeeaaasssseeeeee

**Comment by AGrab** [comment]
+1

**Comment by DaFri-Nochiterov** [comment]
+1, my eyes are bleeding, when I open Telegram at night.
(for Chrome I use extension) :D

**Comment by VegaDeftwing** [comment]
+1 again, seriously, as a person who looks at 3 monitors all day that blob of white gives me headaces even with twilight or flux. To me this is less of a visual feature and more of an accesability one for those who get headaches like me.

**Comment by odlas** [comment]
+1

**Comment by royrov** [comment]
+1

**Comment by mazxim** [comment]
Any chance to get this option for Christmas gift? Who we have supposed to ask this, to Santa?.. come on, it's almost 2016! Where to look at the code to enable this option? Would be more simple patch the binary?..

**Comment by luisalvarado** [comment]
I second this option although they might be working on a theme manager for both, Android and Desktop. Might be why it is taking a bit longer and the priority of it, since is not an issue is lower.

**Comment by dahlskebank** [comment]
1+ Can we pool together to pay for this feature? Telegram is free, but I'll happily pay for the Dark Telegram. I wasn't brought up in DOS to live my older days in blinding white light...

I'm currently using the web-version of Telegram, since I can open that in a pop-up and add whatever styling I want to it. But that doesn't work at all on my phone... Seeing as how [Discord](https://discordapp.com/) has a beautiful dark theme, it's about time Telegram also joins the dark side.

**Comment by VegaDeftwing** [comment]
All of my friends use Telegram and it's the only secure but user friendly option I have; however I'm about to just tell my friends to message me elsewhere because of the headaches. Please, this shouldn't be overly difficult to implement.

**Comment by iii00** [comment]
+1 hard to use at night. don't be like skype with its 90s interface. people want matching app look and 70% use dark themes, other 30 just don't know how to switch it or never use PC at night!

**Comment by bronlund** [comment]
+1 Please make this happen. I do like Telegram, but this is the one issue making me look elsewhere. And how hard can it be? I don't need more stickers and what not, I need this application to not burn my eyes.

**Comment by gtrindade** [comment]
+1

**Comment by pooya-eghbali** [comment]
+1

**Comment by psydwannabe** [comment]
+1!

**Comment by drigger** [comment]
+1

**Comment by LuigiR0jas** [comment]
+1

**Comment by sergioad** [comment]
Could be cool have one completely dark and other with dark eements but with the normal telegram blue toolbar / headerbar

**Comment by yeah568** [comment]
+1

**Comment by Mistero5050** [comment]
+1

**Comment by cooperpellaton** [comment]
+1

**Comment by 0916174** [comment]
+1, Mac support please :)

**Comment by darkneon2002** [comment]
add this asap

**Comment by spirinvladimir** [comment]
+1

**Comment by Carighan** [comment]
Another +1 from me, would love a dark mode.

**Comment by zestyr** [comment]
+1

**Comment by roobre** [comment]
As a dark desktop theme user, this would be amazing.

**Comment by jakobmaier** [comment]
+1

**Comment by j00ch** [comment]
Give white themes the finger.

I am actually using Plus messenger (fork of this app) because of the absence of a dark theme in Telegram.
Remember that a screen is NOT a piece of paper, therefore it should NOT be white. IBM got that right with the first PC screen. No more headaches and eye fatigue.

**Comment by malaniz** [comment]
+1

**Comment by mazxim** [comment]
Has the FUTURE already happened?... :-)
We have something, folks: https://github.com/NXij/tdesktop-dark
Here's the Windows binary: https://github.com/NXij/tdesktop-dark/releases
GOD bless this guy. No other words. Happy easter time ;-)

**Comment by zestyr** [comment]
@mazxim [this patch](https://git.mel.vin/melvin/telegram-desktop) is better imo

**Comment by intrd** [comment]
Wow, push this to official tdesktop pls.. https://github.com/NXij/tdesktop-dark

**Comment by mazxim** [comment]
@zestyr: Nice! It seems just based on a more updated official source. Thanks. Anyway.. a really news for me today. Problem finally solved! :-)

**Comment by stek29** [comment]
I'm not sure, but isn't there **style.txt file with colors**?

**Comment by joshery420** [comment]
Although that's a nice enough looking dark theme, it's also over 300 commits behind. :cry:

**Comment by bronlund** [comment]
Yeah :(
Me, family and friends went to Slack a month ago and I don't think we're coming back.

**Comment by stek29** [comment]
@bronlund Only because of Dark theme?)

**Comment by bronlund** [comment]
No, not only. There were a couple of issues, the most important being; how you front privacy, but then broadcast to whoever in my contact list where they can find me! Not everyone in my contact list is a friend of mine you know %]

Then there was your questionable security. I've read a lot of articles about that and it just made me uncomfortable. What I really want to do is running Mattermost myself, but I just haven't had the time to set this up yet - I guess that will be the next step for me.

B

**Comment by mazxim** [comment]
Is there a download location for a Windows binary, based on latest dev source (0.9.33)? If I chose to update from patched version (0.9.19) it reverts back to white theme.

**Comment by stek29** [comment]
@mazxim I don't think so, but you could update fork to last version and build on your own

**Comment by melvinvermeeren** [comment]
Hi guys.

I maintain a patched Telegram with dark theme and bigger sticker panel patches.

More information and downloads can be found below.
https://git.mel.vin/melvin/telegram-desktop

Builds for GNU/Linux and Windows exist, more developers welcome.
Telegram me at [at]vermeeren if you need more info.

**Comment by Exey** [comment]
+1

**Comment by orangeudav** [comment]
+1

**Comment by stek29** [comment]
@Storm-Engineer justgetflux and use dark room mode :)

**Comment by maja42** [comment]
Flux is a good start, but doesn't solve the issue of white applications. If you are using black GUIs everywhere, switching forth and back to Telegram is a pain.

**Comment by melvinvermeeren** [comment]
Kind of looking for someone that can compile tdesktop on Windows for new dark versions.

**Comment by zestyr** [comment]
hi

**Comment by wildcolin** [comment]
@melvinvermeeren check out https://github.com/NXij/tdesktop-dark/releases

**Comment by melvinvermeeren** [comment]
@wildcolin I maintain my own set of patches (which are also more up-to-date), see a few posts above.
Just have nobody to compile them for windows right now.

**Comment by formatq** [comment]
@melvinvermeeren can you compile this code for windows, please?

**Comment by jeroenpraat** [comment]
+1

**Comment by joshpennington** [comment]
+1

**Comment by stek29** [comment]
Please don't leave `+1` comments, use reactions (not available in mobile version, yup)

**Comment by Storm-Engineer** [comment]
Telegram, just like most companies say lot of nice things but in reality all they care about is following trends at all cost, even if the trend is something that burns your eyes and is totally uncomfortable to look at.

**Comment by mazxim** [comment]
@melvinvermeeren ...can you, or at least any of you here - please - provide us a linux 32-bit (because i'm using a 32 bit system by choice) and/or 64-bit binary file, synched with latest tdesktop source?..

**Comment by saeidscorp** [comment]
Guys, I forked [NXij](https://github.com/NXij/tdesktop-dark/) and tweaked it a little bit (mostly reverted his changes) to better look like original bright version. It's based on version 0.10.19 of the canonical repository.

Take a look at [my version](https://github.com/saeidscorp/tdesktop/) to see if you like it.

[Winows binary](https://github.com/saeidscorp/tdesktop/releases) available (release configuration - MSVC 2015 x86 Tool-chain)

**Comment by acidhunter** [comment]
@mazxim i got a old x32 netbook, i could supply you a x32 binary

i supply x32 build to @melvinvermeeren 's repo in near future
https://git.mel.vin/telegram_desktop/

**Comment by goofcunt** [comment]
shure

________________________________

**Comment by JuanPotato** [comment]
So Tdesktop finally added themes in the latest alpha builds. You can check out https://telegram.me/desktopThemes for some dark themes

**Comment by AndydeCleyre** [comment]
Are the color files documented anywhere? Where can I find out what, for example, `windowSubTextFgOver` corresponds to?

**Comment by JuanPotato** [comment]
I wish, but sadly not yet. Just trial and error. Someone should document their findings with screenshots

**Comment by bil-elmoussaoui** [comment]
@auchri was this released ? i

**Comment by auchri** [comment]
yes https://desktop.telegram.org/changelog

**Comment by electricessence** [comment]
Huge thanks guys.
