### ISSUE TITLE
[Feature Request] Transform links to audiofiles to play button

### ISSUE THREAD

**Issue by t-smirnov** [telegramdesktop/tdesktop#1850]
Sorry, if it'll duplicate 

### Steps to reproduce
1. Send to contact message that contains link for example http://api.test.com/sampleaudiofile.mp3

### Expected behaviour
1.This message transforms to "Play" button

### Actual behaviour
1. Now link doesnt transforms and showing as is

### Configuration
MS Windows 10 x64

**Comment by auchri** [comment]
No api for that
