### ISSUE TITLE
cant apply patch

### ISSUE THREAD

**Issue by surbiks** [telegramdesktop/tdesktop#1852]
i want to compile Telegram for desktop in windows 7 32bit , but when i want apply patch (openal patch) has error : 
 trailing whitespace .
error : patch faild
error : patch not apply.

need apply all patch ?

**Comment by artem-chilin** [comment]
The similar issue for:
Build instructions for Visual Studio 2015 ->
Prepare libraries ->
OpenSSL ->
...
git apply ./../../tdesktop/Telegram/_openssl_patch.diff

Win7 x64 sp1, Git-2.8.1-64-bit

**Comment by oleg-mongol** [comment]
привет есть предложения


05.04.2016, 16:41, "Artem" <notifications@github.com>:

**Comment by 3ngineer** [comment]
hello everyone!
is there any help with this patch failed error in openssl lib?

**Comment by stek29** [comment]
[Check this comment](https://github.com/telegramdesktop/tdesktop/issues/1888#issuecomment-210034558)

**Comment by surbiks** [comment]
my problem solved. before apply patch , open patch file with notepad++ and change EOL setting to unix.

**Comment by 3ngineer** [comment]
@surbiks I've changed EOL conversion to unix and i dont get trailing whitespace error anymore but patch failed and does not applied.

**Comment by stek29** [comment]
You don't need this patch, be sure to get latest code.
I'll recommend downloading zip instead of git, because it's very weird on Windows...

**Comment by 3ngineer** [comment]
@stek29  ok thnx
which zip u mean? 
I've downloaded a zip from "https://github.com/telegramdesktop/tdesktop" but this file contains the tdesktop files not the libraries.

you know I've got errors for most of the patch files and I decided to ignore them and follow the instructions but at the end the qt5 didnt add in VS there's an error " qmake not found", dont know what to do!!!
I'll be very grateful for any help.

**Comment by stek29** [comment]
Instead of   
```git clone https://github.com/foo/bar
cd bar
git checkout baz```
download zip from `https://github.com/foo/bar/archive/baz.zip`, extract it, and rename `bar-baz` to `bar`

**Comment by 3ngineer** [comment]
@stek29  thnx but this site"https://github.com/foo/bar/archive/baz.zip" is not reachable.

**Comment by stek29** [comment]
foo, bar and baz are just placeholders...
Never mind, use git)

**Comment by 3ngineer** [comment]
Oh got it, silly mistake, thank you:)
