### ISSUE TITLE
Remove disabled menu items

### ISSUE THREAD

**Issue by aristidesfl** [telegramdesktop/tdesktop#1854]
![screen shot 2016-04-05 at 11 29 29](https://cloud.githubusercontent.com/assets/208149/14277075/c8eab5d8-fb21-11e5-8fd8-8b99904632f2.png)

The `Paste and Match Style` menu item is grayed out when writing messages. 
This is a problem if you have remaped ⌘V to `Paste and match style`, because it becomes impossible to paste text using the shortcut.

If this menu item is not available for use, ideally it would be removed, so that ⌘V can default to the normal behaviour. 

Is this a possibility?

**Comment by DaFri-Nochiterov** [comment]
It's TDesktop?

**Comment by aristidesfl** [comment]
Sorry, I thought this was the official Telegram client.
