### ISSUE TITLE
Messages are grouped into a single column

### ISSUE THREAD

**Issue by artem-chilin** [telegramdesktop/tdesktop#1855]
### Steps to reproduce
1. Open telegram desktop, then any conversation.
2. Expand window or maximize it to full-screen

### Expected behaviour
Two columns should be displayed in any window size. 
One for "Alice" messages and the second one - for "Bob" messages. 

### Actual behaviour
One ugly column when window exceeds some size. For small window appearance is fine.

### Configuration
Win7 Ultimate x64, service pack 1

**Version of Telegram Desktop:**
v 0.9.40 stable
The issue appeared with update v 0.9.24 stable. 
Suspicious commit: 7de5e24df538ff6e69a74ed91a5929d0f8acd827

**Small window - expected appearance:**
![small_window_2_columns expected](https://cloud.githubusercontent.com/assets/720454/14283118/73a3638a-fb4a-11e5-8824-564a5305bd6a.png)

**Bigger window - unwanted appearance:**
![bigger_window_1_column](https://cloud.githubusercontent.com/assets/720454/14283120/7a66c324-fb4a-11e5-9603-cd1413fb5ad3.png)

**Comment by DaFri-Nochiterov** [comment]
![image](https://cloud.githubusercontent.com/assets/10401817/14290780/b1ccccce-fb8a-11e5-8ca4-505862a3fde7.png)

This is not a bug.. Check settings

**Comment by artem-chilin** [comment]
There is no such checkbox in my settings.
![2016-04-05_20-11-12](https://cloud.githubusercontent.com/assets/720454/14291116/a28d9ed4-fb6a-11e5-8ed3-ed0797f7f339.png)

**Comment by auchri** [comment]
It's only there if you maximize the windows.

**Comment by artem-chilin** [comment]
> It's only there if you maximize the windows.

Yes and I mentioned that in description. And what? Is it a feature? If I want to chat in fullscreen mode and have two orderly columns(like in good old days) but not a mess of messages? 

Besides not only if maximize, it's enough to expand it a bit
![2016-04-05_20-30-55](https://cloud.githubusercontent.com/assets/720454/14291723/8861bf24-fb6d-11e5-9689-a3896889d73a.png)
.

**Comment by auchri** [comment]
I meant: The checkbox in the settings is only there if you maximize the window.

btw. please search for existing issues before creating new ones: #1651, #1663, #1638, #1664 and many more.

**Comment by artem-chilin** [comment]
Thanks, got it. 
Sure, I've searched, looked throug several pages of open issues, but not in closed. My fault, sorry.
