### ISSUE TITLE
Audio name is missing

### ISSUE THREAD

**Issue by shembelcut** [telegramdesktop/tdesktop#1857]
### Steps to reproduce
basically you just need to search for any audio file in any groups or channels, without taking these steps (but in case you are not a member of any group/channel then) : 
1. Send any supported audio file (like mp3)
2. Search for the sent file 

### Expected behaviour
I am expecting to see the audio details which would be really useful specially when you search for some audio file
![image](https://cloud.githubusercontent.com/assets/1249548/14288144/cc5b9d66-fb55-11e5-8372-cdd4e12ce701.png)

### Actual behaviour
on version 0.9.40 it shows "audio file" for all the results which make the searching function totally useless.
![image](https://cloud.githubusercontent.com/assets/1249548/14288216/0f8ba7a2-fb56-11e5-8bac-d4cbeee0bb03.png)

### Configuration
Windows 10

**Version of Telegram Desktop:**
0.9.40

**Comment by stek29** [comment]
So first screenshot is from older version?

**Comment by shembelcut** [comment]
@stek29 Yes
everything was fine before version 0.9.40

**Comment by shembelcut** [comment]
You may close this issue. 
v0.9.42 fixed it.
