### ISSUE TITLE
[UI] [Feature Request] Add option for icon shape

### ISSUE THREAD

**Issue by rusins** [telegramdesktop/tdesktop#1858]
Telegram's latest update (0.9.40) changed a lot of icons to be circular instead of square. Some people like this change, others don't. Would be cool to have an option for it. (Options to customize how messages look in general [speach bubbles/classical lines] would be also cool)
![Uploading circle.png…](How it looks now with circular icons)
![Uploading square.png…](How it used to look with square icons)

### Configuration
**Operating system: Arch Linux**
**Version of Telegram Desktop: 0.9.40**

**Comment by auchri** [comment]
Duplicate #1828
