### ISSUE TITLE
New channel doesn't work

### ISSUE THREAD

**Issue by puraminy** [telegramdesktop/tdesktop#1859]
### Steps to reproduce
1. Create as many as possible public channels until you can't create a new one
2. Delete a channel and try to create a new one
3. You get stuck when you enter the name , the "create" button doesn't proceed

**Comment by auchri** [comment]
Does it work in https://web.telegram.org?

**Comment by puraminy** [comment]
It just occurred once, later as I tried it was resolved (without any restart or reopening the software), maybe a network or connection problem occurred at that time
