### ISSUE TITLE
"Read by" in supergroups.

### ISSUE THREAD

**Issue by Niklan** [telegramdesktop/tdesktop#1861]
I converted today conference in supergroup and drop in issue. Now my message marks as readed (double check) when i send it, but no one read it. Anyway, this feature not needed in supergroups, cuz i don't understand who read this.

I think will be great if on hover of message status, or anyway else add list of users who reads this message like in Gitter.

![_175](https://cloud.githubusercontent.com/assets/2356744/14306471/d9f95e0a-fbe0-11e5-9440-d9390d60dfe6.png)

**Comment by stek29** [comment]
@auchri [API issue]?

**Comment by auchri** [comment]
yes I think so, there is no api for that.
