### ISSUE TITLE
Missing option to switch between round and square user icons

### ISSUE THREAD

**Issue by disharmonized** [telegramdesktop/tdesktop#1862]
After 9.40 "visual improvements" update square user icons has been uncompromisingly replaced by round ones... So i want old icons back! Bring me back my lovely square icons, please! All I want is option in settings to switch between them.

### Configuration
**Operating system:**
Win7 x64
**Version of Telegram Desktop:**
9.40

**Comment by ewgenius** [comment]
If possible, make it just an option in settings. Personally for me, rounded avatars is better than square.

**Comment by auchri** [comment]
Duplicate #1828
