### ISSUE TITLE
start in systray for Linux

### ISSUE THREAD

**Issue by edmundlaugasson** [telegramdesktop/tdesktop#1865]
### Steps to reproduce
1. start Linux
2. set up start Telegram Desktop at logon
3. there is no setting to start Telegram Desktop in systray

### Expected behaviour
Telegram Desktop will start in systray (like currently MS Windows version does).

### Actual behaviour
Telegram Desktop will start with maximized window and user should close/minimize her-/himself, which is quite boring.

### Configuration
Linux. I am using 64-bit Linux Mint 17.3 MATE and also Lubuntu 14.04 LTS but it applies to all Linux versions

**Version of Telegram Desktop:**
0.9.40

### Logs
Logs are not necessary for current case.

**Comment by auchri** [comment]
Try the "-startintray" option :)

**Comment by edmundlaugasson** [comment]
Great - it works - thank you! Actually looked before making that issue from [FAQ](https://telegram.org/faq) and [Advanced FAQ](https://core.telegram.org/techfaq) and could not find it. It would be good to mention it there also. Why not also add such option into Telegram Desktop Linux version settings.
