### ISSUE TITLE
start automatically with system for Linux

### ISSUE THREAD

**Issue by edmundlaugasson** [telegramdesktop/tdesktop#1866]
### Steps to reproduce
1. start Linux system
2. start Telegram Desktop
3. try to configure to start automatically from Telegram Desktop settings
### Expected behaviour

There is no such setting at Telegram Desktop settings that allows set up Telegram Desktop to start automatically when user will log into Linux. Usually it means to create symlink into `~/.config/autostart/` folder:
`ln -s ~/.local/share/applications/telegramdesktop.desktop ~/.config/autostart/`
Did not investigate all desktop environments but I guess the behaviour would be same.
### Actual behaviour

There should be manually create such link or use desktop environment's tool (if it exists) to add application to start automatically.
### Configuration

Linux. I am using 64-bit Linux Mint 17.3 MATE and also Lubuntu 14.04 LTS but it applies to all Linux versions

**Version of Telegram Desktop:**
0.9.40
### Logs

Logs are not necessary for current case.

**Comment by edmundlaugasson** [comment]
Also here applies to start automatically minimized in Linux (#1865, #948 )

**Comment by AndydeCleyre** [comment]
Is it not satisfactory to use the desktop environment's autostart dialog, where you can manage all such services?

**Comment by stek29** [comment]
IMO It's not a good idea to make Telegram handle autostart on it's own on Linux.
It tries to handle it's .desktop file already, and it's so painful.

**Comment by Aokromes** [comment]
#422
