### ISSUE TITLE
long minus instead of two short minuses

### ISSUE THREAD

**Issue by edmundlaugasson** [telegramdesktop/tdesktop#1867]
### Steps to reproduce
1. start Telegram Desktop
2. write `sudo dpkg --configure -a` and press enter (send the message)
3. there will be `sudo dpkg —configure -a` which is wrong and does not work and causes confusion among recipients - cannot guide users in Linux through Telegram currently.

### Expected behaviour
There should be written two short minuses

### Actual behaviour
There will be one long minus.

### Configuration
Linux. I am using 64-bit Linux Mint 17.3 MATE and also Lubuntu 14.04 LTS but it applies to all Linux versions

I guess this applies to all platform versions but could not test all platforms.

**Version of Telegram Desktop:**
0.9.40

### Logs
Logs are not necessary for current case.

**Comment by auchri** [comment]
Duplicate #522 

(Solution: https://github.com/telegramdesktop/tdesktop/issues/522#issuecomment-154837695)

**Comment by edmundlaugasson** [comment]
Actually very poor workaround and not solution actually. When entering ` sign then also other users guess that they need to enter it - they will copy my text and again there is error already encoded in.

**Comment by stek29** [comment]
@edmundlaugasson If you send code, use code escape.

**Comment by DaFri-Nochiterov** [comment]
Telegram can't escape \` symbol

Github: `` SELECT * FROM `something` WHERE ID=1``
Telegram: ` SELECT * FROM `something` WHERE ID=1 `

**Comment by DaFri-Nochiterov** [comment]
or you not about this?

**Comment by stek29** [comment]
@DaFri-Nochiterov triple ` ?

**Comment by DaFri-Nochiterov** [comment]
Without new lines -.-

```
Telegram can't escape \` symbol

Github: `` SELECT * FROM `something` WHERE ID=1``
________^^ Telegram doesn't support this       ^^

Telegram: ` SELECT * FROM `something` WHERE ID=1 `
__________^ Telegram supports only this          ^

```

**Comment by stek29** [comment]
@DaFri-Nochiterov ![screen shot 2016-04-07 at 22 46 27](https://cloud.githubusercontent.com/assets/11808223/14364676/f44795d4-fd1a-11e5-87b4-739aa311ff1d.png)

**Comment by DaFri-Nochiterov** [comment]
@stek29 I not about big codeblocks, look at my message ._.
