### ISSUE TITLE
allow activate without mobilephone number

### ISSUE THREAD

**Issue by edmundlaugasson** [telegramdesktop/tdesktop#1868]
### Steps to reproduce
1. install Telegram Desktop
2. try to activate without mobilephone
3. it is not possible

### Expected behaviour
There would be possible activate Telegram Desktop also without mobilephone - e.g. using regular (fixed) phone, IP phone etc. There could be also voice activation used.
I understand that initially Telegram Desktop were for mobilephones but there exist people who have computer and perhaps also fixed phone but no mobilephone. But it would be useful to have in such case regular username and passphrase. There could be even two-step verification enabled by default in such cases in order to ensure in security.
Also there could be great to add e.g. [mobile-ID](http://id.ee/index.php?id=36882), [ID-card](http://id.ee/index.php?id=30470), [OpenID](http://openid.net/), [HarID](https://harid.ee/), [etc secure identity support](http://alternativeto.net/software/openid/).
There is [special corner for developers](http://id.ee/index.php?id=30469).

### Actual behaviour
Not possible activate without having mobilephone number

### Configuration
Linux. I am using 64-bit Linux Mint 17.3 MATE and also Lubuntu 14.04 LTS but it applies to all Linux versions

**Version of Telegram Desktop:**
0.9.40

### Logs
Logs are not necessary for current case.

**Comment by auchri** [comment]
Duplicate #1430 and #435

**Comment by edmundlaugasson** [comment]
At least I offered some good (secure) authentication ideas.

**Comment by auchri** [comment]
You should send them to the Telegram Team via [Twitter](https://twitter.com/telegram) or with the "Ask a question" feature in one of the official apps.

**Comment by edmundlaugasson** [comment]
Thanks for suggestion - done via Telegram Desktop app.

**Comment by dandv** [comment]
Why is Telegram so obsessed with phone numbers? [Wire and other messaging apps that actually care about privacy allow registering with an email address](https://www.reddit.com/r/privacy/comments/76rl31/are_there_any_secure_messaging_apps_that_dont). I understand the convenience of phone numbers for non-technical users, but Telegram is just a non-starter for those who don't want to expose their phone number.
