### ISSUE TITLE
Visual Studio 2013 Build issue

### ISSUE THREAD

**Issue by praveenflash** [telegramdesktop/tdesktop#187]
On building the telegram solution, i am getting the below issue. Please help

qrc_telegram.cpp
2>GeneratedFiles\qrc_telegram.cpp(550692): fatal error C1060: compiler is out of heap space
========== Build: 1 succeeded, 1 failed, 4 up-to-date, 1 skipped ==========

Please help!!!!

![image](https://cloud.githubusercontent.com/assets/8555982/4516697/da0e330e-4c03-11e4-892a-04799de336a0.png)

**Comment by peiraz** [comment]
Hi everyone!
I'm facing same problem.
So at the moment is it impossibile build on Win7-32 using Visual Studio 2013?
