### ISSUE TITLE
[Bug]Arabic Tatweel doesn't Show Correctly

### ISSUE THREAD

**Issue by madl-ash** [telegramdesktop/tdesktop#1875]
### Description
There is an Arabic/Persian Character Which the name is : "Arabic Tatweel"(Unicode : 1600,[more information here](http://unicode-table.com/en/0640/)).Telegram Desktop Doesnt Show it correctly,what i mean by showing correctly is that this character should connect the letter before and after it but in Telegram Desktop it doesnt.but Telegram for android shows it correctly.see excepted behavior and actual behavior.i have this issue for long time,maybe from 0.8.0,but i just made an issue now.
### Steps to reproduce
1.copy this string (without quotations) : "تــســت"

2.paste it in chat (group/channel/user) and send.

3.Now look at the text you send in Android and Desktop,you can see the difference.

### Expected behaviour
![excepted](https://cloud.githubusercontent.com/assets/13733900/14361866/36f2882a-fd12-11e5-9ade-420895671b84.png)
### Actual behaviour
![actual](https://cloud.githubusercontent.com/assets/13733900/14361863/34e4e78a-fd12-11e5-96fd-b077c59ab69c.png)

### Configuration
**Operating system:**Windows 7 x64

**Version of Telegram Desktop:**0.9.40 Stable

### More Information
I guess it is an Font issue.

**Comment by stek29** [comment]
@auchri #728 duplicate?
