### ISSUE TITLE
Telegram handles GIFs like JPG sometimes

### ISSUE THREAD

**Issue by Kolahzary** [telegramdesktop/tdesktop#1876]
### Steps to reproduce
Send following link to someone using telegram
https://upload.wikimedia.org/wikipedia/commons/8/85/Weighted_A_star_with_eps_5.gif

### Expected behaviour
Telegram must show full animation as preview
just like other GIF URLs, for example this link ==>
https://upload.wikimedia.org/wikipedia/commons/5/5d/Astar_progress_animation.gif

### Actual behaviour
It show's only first frame of animated gif...
![capture](https://cloud.githubusercontent.com/assets/6261271/14364855/fc657e02-fd1f-11e5-8bbc-674298591454.PNG)

### Configuration
Windows 10
**Telegram Desktop Version 0.9.40**
Also tested on **Telegram for Android v3.7.0 (767)** and got exact same result...

**Comment by stek29** [comment]
Looks like API issue, same behavior on iOS.

**Comment by auchri** [comment]
Yes, the server converts the gif wrong.
