### ISSUE TITLE
9.40 redesign

### ISSUE THREAD

**Issue by p-hash** [telegramdesktop/tdesktop#1877]
I hope that image will describe the issue well:

![image](https://cloud.githubusercontent.com/assets/3995232/14365189/0a687fd2-fd15-11e5-951f-16aea97cdd00.png)

Happens on all platforms with narrow dialog width in group chats.

I know that the green bg color marks self messages but it is too light.
I know that only self messages have green checkmarks, but they're at the end of the message while your attention focus is on the top of it.

**Comment by stek29** [comment]
Is it a feature or bug?)

**Comment by ResPasha** [comment]
I and some more users have problems with determining the sender of the message, so the gap could be a marker. There is no need for wide gap like we have in PM but the opponents' messages should not have been aligned exactly same as self messages are.
