### ISSUE TITLE
Rounded contact photos

### ISSUE THREAD

**Issue by prppedro** [telegramdesktop/tdesktop#1880]
Well, looks like "Visual improvements" includes cutting 20% of each thumbnail. Which is pretty cool, some people may think. Not me, however... But that's okay, there are a bunch of users outta here. My question is: why not putting a switch at settings panel that would let us choose between rounded or square contact thumbs? 

Thanks, 
t. r. p.

**Comment by stek29** [comment]
Duplicate?
