### ISSUE TITLE
Missing avatars during search posts in history 

### ISSUE THREAD

**Issue by EXL** [telegramdesktop/tdesktop#1881]
### Steps to reproduce
1. Enter any search phrase which present in the group messages history;
2. Click for go to result;
3. Avatars from users will be lost.

### Expected behaviour
Showing users avatars.

### Actual behaviour
Don't showing users avatars.

### Configuration
**Operating system:**
MS Windows 7 Ultimate;
Arch Linux -> KDE Plasma 5.6.0.

**Version of Telegram Desktop:**
0.9.40

![Avatars Bug](http://wstaw.org/m/2016/04/09/Capturae.PNG)

**Comment by EXL** [comment]
The bug appeared in one of the latest updates.

Related issues: #1863, #1862

**Comment by john-preston** [comment]
I see such bug in the case:

You have a group that was converted to a supergroup and you go to the old messages in this group (before it was converted).

You can test this by trying to reply to such message. If it is a message from an old history part (before conversion) you will see such error:
![image](https://cloud.githubusercontent.com/assets/17900494/14403947/31311b80-fe7b-11e5-9802-047d905d15c6.png)

Is this correct -- you see this bug only together with such error if you try to reply to a message there?

**Comment by EXL** [comment]
@john-preston Yeah, right. I see an error that is shown on your screenshot. Also the group has recently been transformed into a supergroup.

BTW, if you click on an empty space on the left side posts (where there must be an avatar), you normally move to the user profile.

**Comment by EXL** [comment]
@john-preston Can't reproduce on 0.9.42, bug fixed?
Please close this issue, if so.
