### ISSUE TITLE
Incorrect frame duration on GIFs from link previews

### ISSUE THREAD

**Issue by decade21** [telegramdesktop/tdesktop#1882]
### Steps to reproduce
1. Send a link to a GIF
2. Wait for a frame with distinct duration to show
3. Notice the duration does not change

### Expected behaviour
Take the following GIF: https://k60.kn3.net/taringa/0/1/9/9/6/3/neoryu/839.gif
The last frame should last a longer time.

### Actual behaviour
The last frame has the same duration as the others.

### Configuration
**Operating system:**
Ubuntu 16.04 64-bit
**Version of Telegram Desktop:**
0.9.40

**Comment by john-preston** [comment]
Is it working correctly on iOS / Android / WinPhone / OS X native app? As I see, it works the same in the iOS and in Telegram Desktop.

When you send a link to a gif, server downloads that gif and converts it to .mp4, which is after that attached to the message (and displayed on all apps). As I understand, this conversion to .mp4 looses the different frame durations. Sorry, but this has nothing to do with Telegram Desktop.

**Comment by stek29** [comment]
Maybe this should be marked as API issue?

**Comment by auchri** [comment]
@stek29 Are you happy now?

**Comment by stek29** [comment]
@auchri Sorry, I didn't want to offend you...
(And yes, I am :smiley:)
