### ISSUE TITLE
[Feature Request] Option to not show emojis in users's name

### ISSUE THREAD

**Issue by rafaelsoaresbr** [telegramdesktop/tdesktop#1883]
![screenshot at 2016-04-10 00 51 14](https://cloud.githubusercontent.com/assets/13059863/14408162/6246a948-feb6-11e5-9889-904c64bfc30d.png)

Please add a option to not show emoji on user's name, mainly in groups.

**Comment by stek29** [comment]
And what to show? Little squares? 
![photo_2016-04-11_01-16-25](https://cloud.githubusercontent.com/assets/11808223/14413479/89296ed4-ff8c-11e5-8079-d1f26490527c.jpg)

**Comment by rafaelsoaresbr** [comment]
Show an alternative text. It's getting like the messenger plus.

**Comment by auchri** [comment]
Someone should create a fork to include such features which will not be implemented in the official app.
