### ISSUE TITLE
Privacy Issue: Sender's profile is clickable on forwarded messages on public groups

### ISSUE THREAD

**Issue by koyuawsmbrtn** [telegramdesktop/tdesktop#1884]
### Steps to reproduce
1. Forwarding message to people
2. Clicking on the sender's profile
3. Bam.

### Expected behaviour
Link to sender's profile shouldn't be clickable. It's a massive privacy issue.

### Actual behaviour
The link to the sender's profile was clickable.

### Configuration
**Operating system: Ubuntu 15.10**

**Version of Telegram Desktop: 0.9.33**

### Logs
Insert logs here (if necessary)

Nope :3

**Comment by auchri** [comment]
Please try 0.9.40 and confirm this issue still exists.

**Comment by john-preston** [comment]
@koyuawsmbrtn Please try other official Telegram apps and confirm that this is an issue of Telegram Desktop, not the way it works everywhere. https://web.telegram.org for example.

**Comment by stek29** [comment]
Why it should be like this? Just copy and paste if you need to hide origin.
Also, IMO it's also API issue, maybe it can _(pls no)_  have flag for hiding origin for Forwarding messages.

**Comment by koyuawsmbrtn** [comment]
Yep, it's everywhere. Not only Telegram Desktop. I never knew where I should post it, so I did it here. It's a general issue.

**Comment by dragetd** [comment]
Erm, why should it not be linked? If you forward a message, it also says the sender. That is the point of forwarding compared to copy&pasting!

The 'profile' just shows a page with their name and online status which is available for everyone any time. Just search for the nickname and click on it.

Enlighten me if I misunderstood your issue. But the way I understand it, this issue is expected behaviour and should be closed.

**Comment by AlefPhard** [comment]
Use "Plus Messenger"(An unofficial Telegram version) "Forward without Quoting" or Telegram bots  "@binam_bot ,@hazf_bot  " which hides the sender of message

**Comment by R0of** [comment]
now telegram has option - hide link to user if his message forwarded - see Settings->privacy

**Comment by derigel23** [comment]
How to control this setting for telegram bot account? Now forwarded messages by bot are with hidden sender's name.

**Comment by RememberTheAir** [comment]
@derigel23 you can't, but why would you want such an option? If you don't want your bot to be used by unknown people, just ignore updates coming from unverified users. You would have to do that anyway because bots can be found from the global search
