### ISSUE TITLE
[Feature Request] Show other person's message while typing

### ISSUE THREAD

**Issue by mahdiG** [telegramdesktop/tdesktop#1885]
Hi. It's a cool feature to see what the other person is typing before sending it (like in IMO app). You enable this option in settings and others can see what you type and erase.

**Comment by stek29** [comment]
It's bad for bandwidth, it's bad for privacy (it's bad for user experience in my opinion)
I don't know any messenger with this feature.
And It's also API issue afaik, not TDesktop one.

So use "Ask question" button in app or ping Telegram on Twitter.

**Comment by auchri** [comment]
> And It's also API issue afaik

this.

**Comment by mahdiG** [comment]
Actually I mentioned that IMO chat app has it. Thanks anyway I got it. And isn't there any github page for submitting requests these kind of requests?

**Comment by auchri** [comment]
@mahdiG no, sadly not :(

**Comment by stek29** [comment]
@mahdiG IMO doesn't look popular, I've ever never heard about it.
And it has reviews on stores close to 3 of 5!

**Comment by mahdiG** [comment]
@stek29 I don't use IMO. I just wanted you to have an idea of what I was talking about and in case i wasn't clarifying enough :)
