### ISSUE TITLE
Won't edit messages

### ISSUE THREAD

**Issue by BreadMaker** [telegramdesktop/tdesktop#1887]
### Steps to reproduce
1. Write a message in a supergroup.
2. Try to edit it.

### Expected behaviour
The message should change

### Actual behaviour
The message doesn't change

### Configuration
Debian 8.1
Telegram Desktop 0.9.41

### Logs
[log_00_00.txt](https://github.com/telegramdesktop/tdesktop/files/214256/log_00_00.txt)
[mtp_00_00.txt](https://github.com/telegramdesktop/tdesktop/files/214257/mtp_00_00.txt)
[tcp_00_00.txt](https://github.com/telegramdesktop/tdesktop/files/214258/tcp_00_00.txt)

**Comment by john-preston** [comment]
@BreadMaker Yes, it is a bug in the new 0.9.41 version. Thanks!

**Comment by john-preston** [comment]
@BreadMaker This is fixed in 0.9.42 stable. Thanks for your report!
