### ISSUE TITLE
About the git apply patch some problem

### ISSUE THREAD

**Issue by xoxoj** [telegramdesktop/tdesktop#1888]
Win7 64bit vs2015

G:\TBuild\Libraries\openssl>git apply ./../../tdesktop/Telegram/_openssl_patch.diff
_openssl_patch.diff:10: trailing whitespace.
#    if (_MSC_VER>=1300) && (_MSC_VER<=1800)
error: patch failed: e_os.h:315
error: e_os.h: patch does not apply

**Comment by stek29** [comment]
I'm seeing 5th person with this problem already
They all have _Windows_ btw

**Comment by auchri** [comment]
Maybe there is an issue with the line breaks.

**Comment by stek29** [comment]
It's not needed at all!
Check this out:
OpenSSL has:
`#    if _MSC_VER>=1300 && _MSC_VER<1600`
While patch tries to replace:
`#    if _MSC_VER>=1300`
With this:
`#    if (_MSC_VER>=1300) && (_MSC_VER<=1800)`
Of course it does not apply! It's already fixed!

**Comment by john-preston** [comment]
@stek29 No, it doesn't apply because of some newlines problem. It is not needed in the different version of source files, in the ones that are checked in the instructions the patch is needed.

**Comment by stek29** [comment]
@john-preston `OpenSSL_1_0_1-stable` branch is checked in the instructions, and it has it.
I just did everything according to the instructions, and line 318 is like the one I send.
![image](https://cloud.githubusercontent.com/assets/11808223/14536355/a63695c4-027a-11e6-8b97-2445ff9ba85f.png)

**Comment by john-preston** [comment]
You're right, shame on me. I'll fix that in the instructions.

**Comment by john-preston** [comment]
I've removed the patch.
