### ISSUE TITLE
Linux app log user off.

### ISSUE THREAD

**Issue by 4rlekin** [telegramdesktop/tdesktop#189]
Almost every time i boot my system i have to link my telegram app all over again (you know, pass phone number, enter sms code). i was half-expecting to find opened issue here, so im little discouraged.
Any confirmation would be appreciated.
It is not a major bug, but hell of inconvenience,
Thanks in advance

**Comment by 4rlekin** [comment]
I recently moved to Mint 17 with cinnamon, installed telegram and even performed update to 0.7.7 and it worked great. 
So i guess it must some kind of very specific bug

**Comment by anubhavsahoo** [comment]
Mine is fixed too. Though I am not sure if its because of any fix in Telegram or maybe after I aded a desktoip entry

**Comment by Strate** [comment]
For a long time I didn't see any problem. So, I want to withdraw my confirmation.

**Comment by 4rlekin** [comment]
Well, I personally, would like some confirmation about this problem being fix from author before closing this issue

**Comment by Jille** [comment]
I also have this nearly every time I restart tdesktop. Directly after an update always works, but the attempt after that always fails.

**Comment by Jille** [comment]
Hmm, I noticed I have two telegram binaries: Telegram and telegram. (I was pigheaded and had to rename it to lowercase.) The lowercased binary was from 17 oktober, the uppercased one from today. So that could mean that I'm alternating versions and every time I do it can't decrypt the localstorage and I need to log in again.

Could you check whether that was your case as well?

**Comment by 4rlekin** [comment]
@Jille I suffered similar condition as @cippaciong has described in his entry, BUT it was under Xubutnu, now with Mint 17 with Cinnamon everything works fine regardles of updates restarts and such.

**Comment by Jille** [comment]
I highly doubt the distribution to be of much impact to this bug.

**Comment by 4rlekin** [comment]
Sure it sounds weird, but since Updater seems to work differently across distros i assume it may be something lib related
