### ISSUE TITLE
[Improvement] Pinned the date of the messages in chat at the top centered

### ISSUE THREAD

**Issue by slowaways** [telegramdesktop/tdesktop#1893]
### Steps to reproduce
1. Log in Telegram Desktop
2. Enter in any chat
3. View message history in chat
### Expected behaviour

Pinned the date of the messages in chat at the top centered
This facilitates the reading of the date of the messages when a there is a **large number of messages per day** in a chat and you **go up or go down the scroll bar** to view the message history. 
It is even harder when messages do **not follow a day after one by one** in the same conditions.
This already exists in WhatsApp and can be taken as an example there.
### Actual behaviour

The dates are not fixed at the top.
![message date](https://cloud.githubusercontent.com/assets/9668277/14473246/798f9182-00cd-11e6-8ba8-4e0484703878.png)
### Configuration

**System operation: Windows 7**
**Telegram Desktop version: 0.9.42**

PS:
If anyone has contact with the developers of the mobile version and this request was accepted, I ask you to report them.

**Comment by stek29** [comment]
Just move your mouse to Time and you'll see full date:
![screen shot 2016-04-07 at 22 46 27](https://cloud.githubusercontent.com/assets/11808223/14478143/f97f2d0c-0123-11e6-8f34-4d8577112484.png)

**Comment by rowaraujo** [comment]
It should not be so. Common users does not know how to do it... and in Telegram Mobile to do that?

**Comment by stek29** [comment]
Can you provide a screenshot? Not everyone has whatsapp.

**Comment by rowaraujo** [comment]
@stek29 You can check in this video:
https://www.youtube.com/watch?v=IS0UIP3_7SM
