### ISSUE TITLE
Missing chat bot icons of Bot Platform 2.0 Update

### ISSUE THREAD

**Issue by slowaways** [telegramdesktop/tdesktop#1894]
### Steps to reproduce
1. Log in Telegram Desktop
2. Use any bot -> https://www.telegram.me/music
3. Check bot icon
### Expected behaviour

Add new bot icons of Bot Platform 2.0 Update
### Actual behaviour

Chat bots has no icons in list chat
![bot icons](https://cloud.githubusercontent.com/assets/9668277/14472972/3057429a-00cc-11e6-912d-50699d5f0c77.png)
### Configuration

**Operating system: Windows 7**

**Version of Telegram Desktop: 0.9.42**

**Comment by rowaraujo** [comment]
This issue was fixed in the last update 0.9.49!
Thanks!

**Comment by stek29** [comment]
I don't have them on OS X (0.9.49)

**Comment by stek29** [comment]
Bug? It looks like a unusual feature for me...
Anyway, I could make a PR, but I'm not sure where (on Sprite) to place Bot's icon and how should it look.
