### ISSUE TITLE
StickerSetBox show preview of sticker over the window border

### ISSUE THREAD

**Issue by Dyvoker** [telegramdesktop/tdesktop#1899]
### Steps to reproduce
1. Hold right mouse button on sticker in "stickers box";
2. Move cursor down and continue holding right mouse button;
4. ???
5. Profit!

### Expected behaviour
Preview must be closed
   or 
show last sticker, which cursor is choose before leave window border.

### Actual behaviour
Stickers changes in preview, when cursor leave window border.
![screenshot-1](https://cloud.githubusercontent.com/assets/8245958/14523974/6078e45c-0260-11e6-802b-f60985e38116.png)

### Configuration
**Operating system: Linux Mint 17.2**

**Version of Telegram Desktop: 0.9.42**

**Comment by john-preston** [comment]
@Dyvoker Well, it's a feature :) You can see more stickers if you like that way, while you still have no problem closing the preview (by unpressing the mouse button).

**Comment by Dyvoker** [comment]
@john-preston Okay, it's unusual feature :) Usually features like this is a bags :smiley_cat:

**Comment by john-preston** [comment]
@Dyvoker Yes, sure, perhaps this can be named a bug. But I don't see anything bad in it, so I'll let it be that way (at least for now).

**Comment by stek29** [comment]
I like this feature, and always use it)
