### ISSUE TITLE
I can not input Chinese in Telegram desktop chat windows on Ubuntu 16.04

### ISSUE THREAD

**Issue by taijuin** [telegramdesktop/tdesktop#1900]
iBus ... OK!

but fcitx,gcin ....NO!

By iBus,fcitx and gcin , I can input Chinese in Telegram desktop chat windows on Ubuntu 15.10

**Comment by john-preston** [comment]
So in Ubuntu 15.10 all they work well, while in Ubuntu 16.04 they do not work for Telegram Desktop?

**Comment by taijuin** [comment]
yes!

**Comment by hrzhu** [comment]
I can input Chinese with fcitx in Telegram on 16.04. But it's buggy. Sometimes I can't switch IME when using Telegram, sometimes fcitx stops responding. I have to switch to other program and switch IME in that program to make fcitx works properly again in Telegram. And sometime Telegram just crashes when I'm typing with fcitx. I don't have any fcitx issues in other programs.
[0fc23ab9-72de-33fa-2e5e0ad1-0e24325f.dmp.zip](https://github.com/telegramdesktop/tdesktop/files/224218/0fc23ab9-72de-33fa-2e5e0ad1-0e24325f.dmp.zip)

**Comment by CzBiX** [comment]
After search, I found this issue: #1035. 
So I try add `QT_IM_MODULE=fcitx` into telegram.desktop, then problem resloved. It's like this:
```
Exec=env QT_IM_MODULE=fcitx /home/user/Apps/telegram/Telegram -- %u
```

**Comment by taijuin** [comment]
Yes!The problem is solved!

But that would be better if Telegram desktop can do the work.😄

................

I execute the command in GNOME Terminal:


Exec=env QT_IM_MODULE=fcitx /home/taijuin/下載/Telegram/Telegram -- %u
