### ISSUE TITLE
[Feature-Request] Shortcut for Fullscreen-Mode

### ISSUE THREAD

**Issue by nicho90** [telegramdesktop/tdesktop#1904]
### Steps to reproduce
1. Start Application on a Mac
2. Press `CMD + CTRL + F`
3. No Fullscreen-Mode

### Expected behavior
By pressing `CMD + CTRL + F` the native Mac Apps starts in the fullscreen-mode, so that you are able to swipe through your apps. Currently the Telegram App provides fullscreen-mode, but you have to do it manually by clicking on the green Fullscreen-Icon on the left upper corner of the window. I think it would be nice to have a Shortcut for it. I use them all the time and was wondering, why nothing happened in the Telegram App. Maybe it is a bug, but I don't think it. I think it might be missing in the code ;)

### Actual behavior
Manually fullscreen-mode

### Configuration
**Operating system:**
MacOS 10.11.4

**Version of Telegram Desktop:**
v0.9.40

### Logs
- no logs needed -

**Comment by auchri** [comment]
Added to #1060
