### ISSUE TITLE
[BUG] I don't receive anymore from telegram stickers channel on desktop

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#1906]
Since April 14, I didn't receive anymore stickers from this channel:
https://telegram.me/tstickers

The last one was Albercht sticker pack, but this channel published 4 more sticker packs after Albercht which I didn't receive on desktop. On mobile it is okay.

Thanks

**Comment by auchri** [comment]
Please use the issue template and provide some screenshots.

**Comment by amiremami** [comment]
Thanks @auchri , I didnt understand the issue template part, You mean instead of BUG? Here is the screenshot.

![ejyyy5g](https://cloud.githubusercontent.com/assets/15929497/14580710/60c0c44e-03d6-11e6-98b8-1d9671ca7df2.png)

**Comment by john-preston** [comment]
@amiremami If you relaunch the Telegram Desktop app, do you see the stickers in the channel?

**Comment by auchri** [comment]
@amiremami 

> I didnt understand the issue template part

When you create an issue, there is already a template to use. It contains some important informations for us (e.g. the version of Telegram Desktop)

![image](https://cloud.githubusercontent.com/assets/5092164/14580717/fcb9398a-03d6-11e6-9216-6613a02441b9.png)

**Comment by amiremami** [comment]
@auchri ok sorry about this, next time I will use template issue. 
@john-preston and also sorry about this! Yes I relaunched it and they appear. [But this was the second time this is happening]

Thanks to you guys

**Comment by amiremami** [comment]
Close this, thanks 😄

**Comment by Aokromes** [comment]
you can close it youself xD
