### ISSUE TITLE
Make selecting emojis easier on Mac

### ISSUE THREAD

**Issue by daanbeverdam** [telegramdesktop/tdesktop#1911]
Right now, there is no way to select emojis by using the keyboard on the Mac desktop client other than memorising all the shortcuts like :name_of_emoji:. Tab or control + cmd + space will bring up the emoji selector but i can only select one via mouse clicks (arrow keys don't work). What I would like to see for the Mac desktop app is an autocomplete function similar to that of the web client:

<img width="394" alt="screen shot 2016-04-17 at 12 12 24" src="https://cloud.githubusercontent.com/assets/13944585/14586363/f3f4c656-0495-11e6-9ac9-bb681ad1a349.png">

For good measure, I'm using:
OS X El Capitan 10.11.4
Telegram for Mac version 2.09.45032

**Comment by auchri** [comment]
Duplicate #627

**Comment by stek29** [comment]
It's not just duplicate, it's even not about TDesktop!
Telegram for Mac is different client, please use "Ask a Question" button to suggest this.
