### ISSUE TITLE
ugly open\save file dialog in linux

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#1913]
Telegram dialog
![mint](https://cloud.githubusercontent.com/assets/10371194/14587902/2c685a7e-04c4-11e6-99ba-157675c6ec30.PNG)

Other programs (Firefox, Midori, LibreOffice...)
![firefox midori](https://cloud.githubusercontent.com/assets/10371194/14587895/00fa4e9c-04c4-11e6-98f5-87277c73e734.PNG)

**Comment by auchri** [comment]
See #987

**Comment by john-preston** [comment]
In the latest 0.9.57 version gtk file chooser should be used if it is available. Please check.

**Comment by f242** [comment]
all fine in linux mint 18 cinnamon x64
![default](https://cloud.githubusercontent.com/assets/10371194/16685307/fecf0178-4512-11e6-82d1-b969d862c66f.PNG)
