### ISSUE TITLE
Feature request: editable group info paragraph

### ISSUE THREAD

**Issue by gmrple** [telegramdesktop/tdesktop#1914]
It would be nice to have a area in the group info page where we could add a paragraph explaining the purpose of the group or adding shared information.

Here's my use case:
I have a telegram group devoted to the game Rocket League. We occasionally add new people to the group. I would like to add a paragraph explaining how to connect to my mumble server.

### Steps to reproduce
N\A, not a bug

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

### Logs
Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

**Comment by john-preston** [comment]
@gmrple There is a way to add a description to a supergroup, so if you convert you'll have that. No such feature in the regular groups.
