### ISSUE TITLE
Bold doesn't work for Persian & chinese languages

### ISSUE THREAD

**Issue by ahmadalli** [telegramdesktop/tdesktop#1917]
### Steps to reproduce
1. type `@bold *سلام*`
2. type سلام
### Expected behaviour

this first one must be **سلام**.
### Actual behaviour

It would be like like the second one (that is ordinary).
### Configuration

**Operating system:** Windows 10

**Version of Telegram Desktop:** 0.9.42

**Comment by auchri** [comment]
Please add some screenshots.

**Comment by ahmadalli** [comment]
![image](https://cloud.githubusercontent.com/assets/2167301/14601974/7c1af584-057a-11e6-987a-c4317c6aceb0.png)
the first one is `@bold *سلام*`
the second one is `سلام`
the third one is `@bold hi`
the forth one is `hi`

**Comment by bliz937** [comment]
For some reason I cannot get bold working on Linux client version **0.9.49**

![image](https://cloud.githubusercontent.com/assets/4072820/15923822/57283e0c-2e2f-11e6-9ea1-a595c8bccf7a.png)

Works fine on Windows Phone client.

**Comment by stek29** [comment]
@bliz937 i think it's another bug, and you should create an issue
My friend has it too.

**Comment by neesti** [comment]
There is this bug in Telegram 0.10.23-Alpha on Linux Mint 18.3 too.

**Comment by srazi** [comment]
+1
Also please remove label "waiting for answer" so you will not ignore this issue in the future.

**Comment by arieljannai** [comment]
[Same for Hebrew](#4445) - no bold.
Not working with the builtin formatting (two asterisks), nor with the bots [@bold](https://t.me/bold) or [@TgTextBot](https://t.me/TgTextBot).

**Comment by arieljannai** [comment]
It's not a Telegram Desktop thing - but it's also **not working on [Telegra.ph](http://telegra.ph/)** 😱 
There's no bold in the Instant view of telegraph articles in Hebrew

**Comment by NabiKAZ** [comment]
Telegram Desktop 1.3.10
I have this problem.
I send by bot.
```
$message .= 'Normal: English' . PHP_EOL;
$message .= '<b>Bold: English</b>' . PHP_EOL;
$message .= 'Normal: فارسی' . PHP_EOL;
$message .= '<b>Bold: فارسی</b>' . PHP_EOL;
$data['text'] = $message;
$data['parse_mode'] = 'html';
```

![image](https://user-images.githubusercontent.com/246721/44617833-b96c5e00-a87f-11e8-864f-6ad8195cded6.png)

You can see in last line, just the english chars was bold.

There is not problem on iOS.

**Comment by sputnik63** [comment]
This problem is also for Italian language. I think it's independent from the character set.
If I type **my text** on Telegram desktop, it appears normal on the desktop but bold on android chat.
If I type ** my text** on android, it's correctly bold on the smartphone but not in Telegram desktop.
No problems with __italic text__
I use telegram Desktop for Linux rel. 1.4.3 just updated

**Comment by stek29** [comment]
@sputnik63 that's another issue: #4095

**Comment by mortezae** [comment]
The bug is not resolved after a year in Telegram 1.8.15
I'm using Ubuntu, not sure about windows version.

**Comment by NabiKAZ** [comment]
After 4 years:
Telegram Desktop 1.9.3
![rY9hKKuO5o](https://user-images.githubusercontent.com/246721/72153574-9cc4bd80-33c3-11ea-92ba-c9aaf2ecc2e5.gif)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2128 generic ticket.
