### ISSUE TITLE
Customizable short date format in session list

### ISSUE THREAD

**Issue by SaltfishAmi** [telegramdesktop/tdesktop#1920]
![default](https://cloud.githubusercontent.com/assets/14184974/14605221/956857a6-05b2-11e6-940b-3b3c6da6f6b5.png)
As shown in the picture, the short date in the red box meant 17 Apr 2016, not 16 Apr 2017. This may  be very confusing for some users as they are generally used to year/month/day format short dates. Like me :(
Currently I can't find anything related to this in the language file so I guess it was uncustomizable. It would be nice if you make it customizable. Thank you.

current configuration: 0.9.42 on Windows 10

**Comment by Royal2000H** [comment]
+1. I'm curious where you use YY/MM/DD. I know most of the world uses DD/MM/YY.

In the US (where I'm from), it's generally MM/DD/YY. Would love an option to set that as the date format. Perhaps you can even pull the localization settings from the computer to automagically set it to the correct format.

**Comment by stek29** [comment]
[Here it is.](/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/dialogs/dialogs_layout.cpp#L72)

**Comment by Royal2000H** [comment]
@stek29 Thank you for finding that.

I don't have any experience with Qt and don't have time to play with it, but if anyone has the project set up and is willing to make changes, I found two possible ways to easily make this change.

First:
There's the [overloaded QDate::toString()](http://doc.qt.io/qt-5/qdate.html#toString-1) function that seems to involve locale. And could replace the toString linked by stek29.

Or second:
There's the [QLocale::DateFormat()](http://doc.qt.io/qt-5/qlocale.html#dateFormat) which would return the date time format used in the locale which can be passed into toString linked by stek29.

**Comment by SaltfishAmi** [comment]
@Royal2000H 
China.

**Comment by XP1** [comment]
Hardcoding the date format "d.MM.yy" is a bad idea. I would rather have the ISO 8601 "YYYY-MM-DD" date format be hardcoded.

ISO 8601 is the far superior standard date format and is great for computer and human filing and sorting.

Don't forget that the date format is hardcoded in other places as well:
https://github.com/telegramdesktop/tdesktop/search?utf8=✓&q="d.MM.yy"

**Comment by Royal2000H** [comment]
Rather than choose the best hardcoded format, I'd say making it match the system should be the priority.

**Comment by BryanEllis** [comment]
At least matching the system short-date format.  Maybe future there could be an option in the Settings page.  ISO 8601 would definitely be a better hard-coded format than the current one.

**Comment by stek29** [comment]
What about using localization files for such things? If user doesn't like existing format he can make modified `.strings` file and use `loadlang`.

**Comment by Aokromes** [comment]
#618 maybe setting to allow choice between system configuration and custom?

**Comment by Aokromes** [comment]
#618
