### ISSUE TITLE
Don't reorder conversation list while hovering

### ISSUE THREAD

**Issue by tecywiz121** [telegramdesktop/tdesktop#1921]
### Steps to reproduce
1. Have three chats open: A (newest), B, C (oldest). Make C the active chat.
2. Hover mouse over chat A, but wait before clicking.
3. Receive a chat on B.
4. Click.

### Expected behaviour
You should end up in chat A because that's what you expected when you clicked.

The chat list shouldn't reorder while the mouse is hovering over it, or else you'll end up in chats you don't expect when messages arrive. It's especially annoying when you're a member of a very active group.

### Actual behaviour
The message on chat B bumped it to the top of the list, so you enter chat B instead.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 0.9.42

**Comment by Kondra007** [comment]
Could I add some requests: Please "freeze" chat re-ordering when selecting chat to forward message.

**Comment by stek29** [comment]
#1504 duplicate
