### ISSUE TITLE
[Feature Request] Quick edit

### ISSUE THREAD

**Issue by toxsedyshev** [telegramdesktop/tdesktop#1925]
### Steps to reproduce
1. Send a message to SuperGroup with a mistake.
2. Try to edit.
3. Suffer.

### Expected behaviour
Quick edit, eg. by top-arrow like in Skype.

### Actual behaviour
No quick edit.

### Configuration
**Operating system:**
Any
**Version of Telegram Desktop:**
0.9.42

**Comment by auchri** [comment]
duplicate #1779
