### ISSUE TITLE
Cannot change channel type for big channel

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#1927]
I have two channels. One has 14 subscribers and the other has 1800+ subscribers. In Telegram desktop I see "Create public link" option only for the first channel (small one). However, in Telegram for Android both channels have this option (though I haven't tested it for the big one on Android)

### Configuration
**Operating system:** Windows 8.1 x64

**Version of Telegram Desktop:** 0.9.43dev

**Comment by auchri** [comment]
As I understand the [FAQ](https://telegram.org/faq_channels#q-how-do-i-add-people-to-my-channel), this is the expected behavior.

> As the channel‘s creator, you may invite the first 200 members to your channel. Once the member count reaches 200, the channel is on its own. If it’s a public channel, it will have a username and a telegram.me/ link (e.g. telegram.me/telegram) – you can post this link on social networks, advertise it in magazines, or tattoo it on your back. If you have a private channel, you can send its invite link to your friends.

**Comment by Kondra007** [comment]
Well, I couldn't find out what exactly "it's on your own" means regarding Telegram channels. Now you explained to me. Thanks! 
Maybe F.A.Q. should be a little more detailed?

**Comment by auchri** [comment]
> Maybe F.A.Q. should be a little more detailed?

yes, maybe. But that's not an issue of Telegram Desktop.

**Comment by john-preston** [comment]
@auchri I'm not sure it is not a bug :)

**Comment by Kondra007** [comment]
@john-preston A friend of mine reported (with screenshots) that he managed to convert channel with 1000 members to private and then to public back again, using Telegram for iOS (on iPad)

**Comment by john-preston** [comment]
@Kondra007 Can you actually tap on this button in the android version? So that you can see it works (at least it asks you for the username and checks the username availability). There is a server-side param in a channel (can_set_username) which perhaps is ignored in displaying that button on Android, but not in Telegram Desktop.

**Comment by Kondra007** [comment]
@john-preston I managed to convert 1800+ users' channel to private one now. And back to public.
But that channel was still reachable by original username. 
So thanks for nice explanation!

**Comment by Kondra007** [comment]
Well, sorry, no!
With TDesktop I managed to change its type now. So it became fully private.
