### ISSUE TITLE
Personal messages on the wrong side

### ISSUE THREAD

**Issue by biscofil** [telegramdesktop/tdesktop#1929]
### Steps to reproduce
1. open telegram chat

### Expected behaviour
My messages should be on the right side of the chat panel

### Actual behaviour
My messages are on the left side of the chat panel, the same side of interlocutor's messages

### Configuration
windows 8.1

![telegram](https://cloud.githubusercontent.com/assets/1677625/14669541/b008b9ec-06e9-11e6-8338-7f22e6fa7e83.PNG)
0.9.42

**Comment by DaFri-Nochiterov** [comment]
This is not bug, this is feature. 
You can disable it in settings.

![image](https://cloud.githubusercontent.com/assets/10401817/14671060/10edcb0a-071a-11e6-9e90-910539c3b9eb.png)


Discuss about this there: #1587
