### ISSUE TITLE
Why is unity not using libappindicator?

### ISSUE THREAD

**Issue by wa4557** [telegramdesktop/tdesktop#1932]
While trying to fix #1908 I discovered 
https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/pspecific_linux.cpp#L1252

in the code. Since Unity has a very good appindicator support, is there a reason why only xfce is using appindicator and not unity (and probably other DEs)?

**Comment by john-preston** [comment]
tryAppIndicator variable means try it before Qt tray icon support (which was broken in xfce as I remember), so I needed appindicator to have higher priority. At least in Ubuntu current tray icon (by Qt) behaves exactly like libappindicator one. But in some systems Qt tray icon allows to activate app by left click while showing menu by right click, while appindicator does not have activate-by-click at all, it only shows menu (by any click). So where it is possible (and not broken) I use Qt tray icon, where I can't I fallback to appindicator.

**Comment by wa4557** [comment]
Thanks, makes sense :+1:
