### ISSUE TITLE
[BUG] New update is broken

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#1933]
After updating telegram to the recent version I get this error message:

```
/Telegram: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /Telegram)
```

- Linux Mint 17.3 x64 xfce

**Comment by R-omk** [comment]
Same on ubuntu 14.04

**Comment by mbnoimi** [comment]
It seems this issue related to stupid patch of Qt which Telegram desktop does... any way I'm working now on [this link](https://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-on-ubuntu-14-04) hope this may fix the issue

**Comment by mbnoimi** [comment]
I'm really frustrated of Telegram Desktop guys. Many users/developers asked them to use the standard Qt while they insist to use freaken patch.

**Comment by brainlid** [comment]
I had the same issue. Downloaded the previous version here... 

https://tdesktop.com/linux/tsetup.0.9.42.tar.xz

**Comment by mbnoimi** [comment]
Don't revert back... just fix this issue using the following command:

```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y gcc-4.9 g++-4.9 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4
```

depending on [this link](https://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-on-ubuntu-14-04)

**Comment by Jusix** [comment]
Installing system libs from a third party repo is a realy bad workaround! Telegram devs should fix the issue in the application!

**Comment by R-omk** [comment]
:neutral_face:   :see_no_evil:

```
git clone https://github.com/R-omk/docker-telegram
cd docker-telegram
docker build -t mytelegramm
xhost +si:localuser:root
docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -v /dev/snd:/dev/snd --privileged mytelegramm
```

**Comment by achiang** [comment]
Thanks for providing the link to 0.9.42.

Installing a brand new gcc / libstdc++ just to work around this issue adds a lot of complications, especially if you develop other software on your machine.

**Comment by LibertyPaul** [comment]
LOL guys you have actually killed tdesktop for common users

**Comment by john-preston** [comment]
I've rolled back the 0.9.42 on site, sorry :/ I didn't expect, that upgrading from gcc 4.8 to gcc 4.9 won't make it.

@mbnoimi this has nothing to do with Qt or patch :)

**Comment by ppparadox** [comment]
Broken for me too.
DO NOT APPLY THAT WORKAROUND!
Telegram should start releasing a standalone statically compiled executable to avoid issues like this.

**Comment by ppparadox** [comment]
Great testing guys, i thought using an LTS version meant stability but it really looks like you didn't bother testing on this.

**Comment by rmad17** [comment]
Linux Mint 17.3 has the same issue. Really bad from Telegram not to test on LTS.

**Comment by ppparadox** [comment]
Indeed Linux Mint MATE 17.3 x64

**Comment by bahbka** [comment]
Same problem Ubuntu 14.04.4 LTS

**Comment by john-preston** [comment]
@ppparadox @rmad17 @bahbka currently the 0.9.42 which should work should be available as the last version. Did you update before I removed 0.9.44? Or is there some other way you got this update? Because I've removed it long before your comments.

**Comment by rmad17** [comment]
@john-preston  I got the update via the desktop app itself.

**Comment by john-preston** [comment]
@rmad17 Yes, it was available for a couple of hours :( can you please install the last version from site and confirm that it doesn't update to the broken version anymore? Thanks!

**Comment by john-preston** [comment]
@mbnoimi @R-omk @brainlid @Jusix @achiang @LibertyPaul @ppparadox @bahbka @rmad17 

Please check out 0.9.45 dev version from the bottom of https://desktop.telegram.org/#dev-version page, it should be working fine now, I've linked libstdc++ from g++ 4.9 statically.

**Comment by rmad17** [comment]
Its working fine. Thanks @john-preston . :+1:

**Comment by wunderlich** [comment]
The 0.9.45 dev version works for me, too! Thanks @john-preston!

Does it update automatically as a stable version?

**Comment by ppparadox** [comment]
0.9.45.dev looks good on Linux Mint Mate 17.3 x64. Thank you for the prompt fix!

**Comment by mbnoimi** [comment]
Guys I'd like to point to you about a very disturbing bug because I'm one of the users who use Telegram on daily basis.

https://github.com/telegramdesktop/tdesktop/issues/1944
