### ISSUE TITLE
[feature request] Attaching videos like on Mobile :)

### ISSUE THREAD

**Issue by gwpl** [telegramdesktop/tdesktop#1936]
I'd love to send short video message (like I can on Mobile), similarly to voice messages, but just with video to show handwaving :).

**Comment by auchri** [comment]
duplicate #781 ?

**Comment by gwpl** [comment]
Not really... imho making video (and eventually showing dialog for cropping and selecting compression like on Android) is more complex (not only because it's webcam+microphone) than making photo or might be done via different programming libraries/interfaces. Anyhow, both are somehow related, as both are about using webcam .

**Comment by stek29** [comment]
#1106
