### ISSUE TITLE
Feature-Request: Ubuntu Indicator + emoji shortcut editor

### ISSUE THREAD

**Issue by ChaosMarc** [telegramdesktop/tdesktop#194]
Hi there,

I would love to see an ubuntu indicator (like the windows tray-icon) that shows a new messages count like it was realized in Sigram or an integration into the already existing messaging indicator like Webapp Telegram does (see screenshots below).

<a href="https://github.com/sialan-labs/sigram">Sigram</a>: 
<img src="http://s14.directupload.net/images/141010/3z24rwbo.png" title="Sigram">
<a href="http://www.webupd8.org/2014/04/telegram-unity-webapp-integrates.html">Webapp Telegram</a>: 
<img src="http://2.bp.blogspot.com/-PMAAnreGhUg/U1j1SiSHlzI/AAAAAAAASbI/ezPA3G18qao/s1600/telegram-messaging-menu.png" title="Webogram">

another thing (already mentioned here: https://github.com/telegramdesktop/tdesktop/issues/116 ) that would be great is a shortcut editor for emojis. I imagine something like a popup window in the settings menu, that lists all emojis below each other on the left hand, and on the right hand the user can enter the replacement strings like ; ) and ; - ) for the respective emoji. 
multiple replacements per emoji would be awsome! 

I already took a look into the code but could not find the correct place to fiddle around a bit. could someone point out some directions for my emoji editor idea? I dont think I can develop much, as my dayjob keeps my pretty busy, but I like to try out some things :)

**Comment by edubxb** [comment]
+1

I use GNOME 3

**Comment by chuckbutler** [comment]
I just got started with telegram this evening, and this would provide a nice layer of integration with my desktop. +1

**Comment by ChaosMarc** [comment]
the indicator feature is now implemented (since 0.7.7)

**Comment by chuckbutler** [comment]
I'm using it, and it works extremely well. Its not quite native with messaging menu support - but this broad implementation works pretty well. :+1:   

Thanks for that!

**Comment by nplezka** [comment]
+1
