### ISSUE TITLE
All messages in supergroup became read even if nobody reads them.

### ISSUE THREAD

**Issue by luc1ph3r** [telegramdesktop/tdesktop#1940]
### Steps to reproduce
Write any message to supergroup

### Expected behaviour
Message should stay unread until somebody read it.

### Actual behaviour
Even if all members are offline, message will be marked as read immediately

### Configuration
_Operating system_: **ArchLinux**

_Version of Telegram Desktop_: **0.9.42**

**Comment by john-preston** [comment]
@luc1ph3r Supergroups do not have read / unread message status in API :(

**Comment by DaFri-Nochiterov** [comment]
What the... Why?

**Comment by stek29** [comment]
So... API issue?

**Comment by DaFri-Nochiterov** [comment]
Why it isn't fixed yet?

**Comment by stek29** [comment]
How can it be?

**Comment by Gollam** [comment]
I think this is fixed in the latest version. Please verify.

**Comment by DaFri-Nochiterov** [comment]
Yep, fixed. @luc1ph3r close your issue :)
