### ISSUE TITLE
Problem with authentication  

### ISSUE THREAD

**Issue by lobocode** [telegramdesktop/tdesktop#1941]
As a user, I don't think it's practical to have to send an sms to enter the application because, in my work for example, there's no sign of the telephone operator to use. So, you cannot access the desktop application of the telegram. Could implement another function to facilitate authentication.

**Comment by Aokromes** [comment]
If you are logged into telegram on a mobile phone it sends you the pin on telegram mobile.

**Comment by lobocode** [comment]
Oh, right. Sorry but I haven't noticed it. @Aokromes
