### ISSUE TITLE
OS X: Attach File filter does not allow files whose names lack extensions (or files without any periods in the filename)

### ISSUE THREAD

**Issue by andlabs** [telegramdesktop/tdesktop#1943]
### Steps to reproduce
1. Click on the attach icon, click Attach File
2. Open the Options for the file dialog and make sure All Files is selected
3. Try to choose a file with no file extension

### Expected behaviour
I should be able to attach the file

### Actual behaviour
The file is grayed in the file dialog and cannot be selected

### Configuration
**Operating system:**
OS X 10.11.4
**Version of Telegram Desktop:**
0.9.44

### Suggested Fix
Change the All Files filter from `*.*` to `*`?

**Comment by GordeevArt** [comment]
I have the same on Fedora 22 linux 64x. Telegram Desktop: 0.9.49

**Comment by john-preston** [comment]
This should be fine in 0.10.1 version.
