### ISSUE TITLE
Pulseaudio: Telegram Audio Stream not moveable

### ISSUE THREAD

**Issue by davidmehren** [telegramdesktop/tdesktop#1946]
### Steps to reproduce
1. Start Telegram on a system with pulseaudio installed (Antergos Linux in my case)
2. Try to move the audio stream to another output (eg from analog output to HDMI) using `pacmd` or `pavucontrol`
3. It does not work.

### Expected behaviour
I can change the output

### Actual behaviour
In `pavucontrol `nothing happens.
`pacmd move-sink-input` outputs `Moved failed.`

I noticed that `pacmd list-sink-outputs` shows `DONT_MOVE` as a flag for Telegram. 
Maybe this disallows moving the audio stream to another sink?

### Configuration
**Operating system:**
Antergos/Arch Linux, Kernel 4.5.1-1
pulseaudio 8.0

**Version of Telegram Desktop:**
0.9.44

**Comment by Kondra007** [comment]
Duplicate #776 ?
