### ISSUE TITLE
Minor: tray icon in Linux + i3wm

### ISSUE THREAD

**Issue by giacecco** [telegramdesktop/tdesktop#1949]
### Steps to reproduce
1. run Telegram on Linux using [i3wm](https://i3wm.org/) as your window manager

### Expected behaviour
The tray icon looks ok.

### Actual behaviour
The tray icon looks like it is surrounded by a cloud of pixels of various colors, as in the picture below. If the other tray icons had the same issue, I would have said that it was an i3wm bug, but it is just Telegram's.

![telegram dithering](https://cloud.githubusercontent.com/assets/303693/14762648/71400914-0977-11e6-9de3-27192a57e4be.png)

### Configuration
Fedora 23 on Lenovo T450s.
Telegram 0.9.42

Thanks!

**Comment by lunix4** [comment]
Did you try to run it with a composite manager, such as xcompmgr ?

**Comment by giacecco** [comment]
No I am not using xcompmgr. If the other icons look fine, adding more movable parts would only make debugging more difficult, wouldn't it?

My guess is that whoever worked on the icon was not very careful in making the background homogeneous, so that transparency worked correctly.

**Comment by giacecco** [comment]
I've found a second application that occasionally behave in the same way as Telegram: Dropbox. This suggests this is more likely an i3wm issue than a Telegram one, I've created [a new bug there](https://github.com/i3/i3/issues/2325).
