### ISSUE TITLE
Linux Control Bar integration

### ISSUE THREAD

**Issue by TheAppService** [telegramdesktop/tdesktop#195]
Hi,

it would be great if you could add an ubuntu control bar integration(File attached(I know it looks horrible)), so the application runs in the background till you close it through the button in the bar at the top.

Thank you very much

Daniel 

![bildschirmfoto vom 2014-10-08 19 49 07](https://cloud.githubusercontent.com/assets/6033570/4563995/c3ee5cb2-4f13-11e4-8bb9-23857b164376.png)

**Comment by Dryvenn** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
already fixed @auchri

**Comment by auchri** [comment]
thanks @bil-elmoussaoui!
