### ISSUE TITLE
Magnifier overlaps group's name

### ISSUE THREAD

**Issue by Warchant** [telegramdesktop/tdesktop#1950]
### Steps to reproduce
1. Find any group with long name.
2. Make Telegram width equal to a half of the desktop resolution.
### Expected behaviour

Magnifier should not overlap group's name.
### Actual behaviour

Magnifier overlaps group's name.
### Configuration

**Operating system:**
Windows 10
**Version of Telegram Desktop:**
0.9.44

![image](https://cloud.githubusercontent.com/assets/1867551/14762963/4c1c2c12-0990-11e6-8cac-15b77d389bdf.png)

**Comment by stek29** [comment]
Fixed afaik
