### ISSUE TITLE
Where is v0.9.42 -> v0.9.44 for linux

### ISSUE THREAD

**Issue by cyberkatze** [telegramdesktop/tdesktop#1951]
Hi! There is
> Version history
> v 0.9.44 stable 20.04.16
> 
>     Bug fixes and other minor improvements

[https://desktop.telegram.org/#changelog](https://desktop.telegram.org/#changelog)

But we can downloads only v0.9.42 for Linux!

**Comment by auchri** [comment]
It was removed because of #1933
