### ISSUE TITLE
removing the app

### ISSUE THREAD

**Issue by DivPro** [telegramdesktop/tdesktop#1953]
### Steps to reproduce
1. Download Telegram's source code and launch telegram's main script (not updater)
2. Remove source code folder
### Expected behaviour

First - user can choose where to install app (official .deb or .rpm package is not so difficult)
Second - Menu entry missing after removing the app
### Actual behaviour

Menu entry exists - is says - "error executing command ... telegram -- %u"
### Configuration

Ubuntu 16.04

**Version of Telegram Desktop:** latest

**Comment by stek29** [comment]
Telegam adds its' own .desktop file to `~/.local/share/applications`.
So it's #306 duplicate.
About the deb/rpm package -- #2122
