### ISSUE TITLE
You are not being written ? Can't use Telegram on Linux

### ISSUE THREAD

**Issue by Tchey** [telegramdesktop/tdesktop#1955]
### Steps to reproduce
1.sudo Telegram
2.error, "You are not being written"
3.nothing else

Hi, i've installed Telegram Desktop from the officiel website, it was fine until a few days ago. Then for no obvious reason, Telegram was not starting anymore. Nothing happened at all. From Terminal, message to install orville-write instead.

Did that (sudo install orville-write) and now with the command Telegram, Terminal returns message "You are not being written".

No idea what to do now.

I have the same Telegram installed on another Linux computer, same Mint 17.3 up to date, and it's working fine.

**Comment by auchri** [comment]
Which version are you using?

**Comment by Tchey** [comment]
How strange, i don't know what happened i tried again the exact same way i did about 15 times before : download from the website, extract, install. But this time it worked, unlike all previous attempts past week...

So now, Telegram is working again (with tsetup.0.9.42.tar.xz freshly downloaded).

**Comment by john-preston** [comment]
@Tchey Perhaps the problem was with 0.9.44 stable, built by g++ 4.9.

Please check if 0.9.45 dev from the bottom of https://desktop.telegram.org/#dev-version works for you or not.
