### ISSUE TITLE
 [feature request] end-to-end encryption

### ISSUE THREAD

**Issue by Proton-Byte** [telegramdesktop/tdesktop#1958]
-- No issue -- Just a feature request --

It would be pretty nice, if the desktop version have also end-to-end encrypted Chats.

**Comment by TiagoDanin** [comment]
this #871 ?

**Comment by Proton-Byte** [comment]
@TiagoDanin yes, thanks.

But I mean the Telegram team advertise with security and better privacy, but then do it better then the other Messenger [like whatsapp] - even Whatsapp have end-to-end encryption in groups and on PC!

I know programming is not easy, but please try to add secret chats on the PC and encrypted group-chats.

**Comment by auchri** [comment]
No need to keep two issues open.
