### ISSUE TITLE
Korean character is missing

### ISSUE THREAD

**Issue by itanoss** [telegramdesktop/tdesktop#196]
I'm using version 0.6.2 on Ubuntu 14.04 x64.
It looks broken as all of Korean characters have been replaced with simple rectangle.
For instance, 한글날 looks like ㅁㅁㅁ. (I'm wondering if you cannot see this well.)
I guess it is from charset problem or font problem.
Hence if the font does not support Korean, the main font could be changed hopefully.

**Comment by mxa** [comment]
I think this issue is solved as I can see Korean characters just fine in Telegram Desktop. However I can't write them, but that's another bug.
