### ISSUE TITLE
Keyboard issues in telegram on surface when detach keyboard

### ISSUE THREAD

**Issue by Saovorak** [telegramdesktop/tdesktop#1961]
### Steps to reproduce
1. Open Telegram on Surface Pro or Surface Book
2. Detached the type cover or keyboard
3. The onscreen keyboard is not pop up when we set focus on the message box

### Expected behaviour
We expected to have onscreen keyboard popup as in mobile phone. And when we press onscreen keyboard, it pop over the message box that user support to see their statement. It should behave like mobile version when user using onscreen keyboard

### Actual behaviour
It does nothing

### Configuration
Window 10 (Surface Pro or Surface Book)

**all version even developer version**

**Comment by willywill** [comment]
This happens on my touch screen laptop as well. When I tap the text field in Telegram, the on-screen keyboard doesn't pop up.

Configuration: Windows 10 build 10586, HP Spectre X360

**Comment by auchri** [comment]
Duplicate #218
