### ISSUE TITLE
How obtain ChannelForbidden object

### ISSUE THREAD

**Issue by jamesmoriati** [telegramdesktop/tdesktop#1962]
Hi
I use channels.getDialogs#a9d3d249 offset:int limit:int = messages.Dialogs;

In response, Instead of returning object channelForbidden, chatForbidden object returns.
In addition, instead of returning object chatForbidden#7328bdb (In the file mtproto/scheme.tl), returns the object chatForbidden#fb0ccc41 (In the url https://core.telegram.org/schema).

please help me.
Thank you.

**Comment by auchri** [comment]
I don't understand your issue. You can find the current scheme here: https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/mtproto/scheme.tl

https://core.telegram.org/schema is really outdated.

**Comment by jamesmoriati** [comment]
thank you :)

I've used some of the requests contained in the address https://core.telegram.org/schema.
I Should switch to /Telegram/SourceFiles/mtproto/scheme.tl.
