### ISSUE TITLE
I do not see recent messages but messages from 1970

### ISSUE THREAD

**Issue by Marvimoto** [telegramdesktop/tdesktop#1963]
### Steps to reproduce
1.  I used the search function and scrolled to older messages I think

### Actual behaviour
The in-chat search function worked as expected but after it it kind of jumps back to unix timestamp 0 and shows me "no messages", although I message this contact every day.
![bildschirmfoto 2016-04-27 um 22 50 57](https://cloud.githubusercontent.com/assets/18257952/14867804/929b390c-0cca-11e6-9466-16ab981d7e2d.png)

### Configuration
**Operating system:**
OS X 10.11 Beta (15A279b)
**Version of Telegram Desktop:**
Version 2.10.45133

**Comment by auchri** [comment]
You are using the native client for OS X, not Telegram Desktop: https://github.com/overtake/telegram

**Comment by john-preston** [comment]
@Marvimoto You can try Telegram Desktop from https://desktop.telegram.org :)
