### ISSUE TITLE
[Windows] Telegram Desktop update to dev version every time

### ISSUE THREAD

**Issue by ItachiSan** [telegramdesktop/tdesktop#1964]
### Steps to reproduce
1. Install Telegram Desktop (stable version) using Windows official installer.
2. Use Telegram Desktop as usual and wait for development update.

### Expected behaviour
Telegram Desktop should update to only stable version, as the downloaded version is the stable one.

### Actual behaviour
Telegram Desktop updates to the development version.

### Configuration
**Operating system:**
Windows 10 64-bit.
If you need more specific information, I can provide them.
**Version of Telegram Desktop:**
0.9.46 (previously 0.9.44)

**Comment by john-preston** [comment]
@ItachiSan It happens that way if you already have installed dev version once and install the stable above it. You need to completely uninstall previous and install stable for it not to update to dev.
