### ISSUE TITLE
"Instant camera" photos are not properly rotated before posting

### ISSUE THREAD

**Issue by iklimchuk** [telegramdesktop/tdesktop#1966]
### Steps to reproduce
1. open instant camera
2. rotate device to the landscape mode
3. make a shot and post it to the chat

### Expected behaviour
I expect to have the image rotated before posting.

### Actual behaviour
Image is posted as it is. See the screenshot for details.
![screenshot - 4_29_2016 1_59_27 pm](https://cloud.githubusercontent.com/assets/10230808/14915471/8f301ffe-0e13-11e6-8cf6-1317fa3d514e.png)

### Configuration
iOS

**Version of Telegram Desktop:**
3.8.1

Sorry for posting mobile issue to desktop thread, but i cannot find appropriate one for iOS app.

**Comment by stek29** [comment]
Use "Ask a question" button in app.

**Comment by iklimchuk** [comment]
"Ask a question" seems to be unresponsive. Already reported few cases there without any feedback.

**Comment by stek29** [comment]
@iklimchuk TSF members are volunteers, and sometimes they just ~~ignore~~ don't notice message. So you could ping [@telegram on Twitter](https://twitter.com/telegram).

**Comment by auchri** [comment]
https://twitter.com/telegram/status/726035278457126914

:+1:
