### ISSUE TITLE
Other group members might see the phone numbers of newly added members even if they don't have each other's!

### ISSUE THREAD

**Issue by TheVorlon** [telegramdesktop/tdesktop#1967]
### Steps to reproduce
1. Have someone add a person with whom you do not share phone numbers
2. Go to the group members list
3. Click on that person's name

### Expected behaviour
Not to see their phone numbers when you do not have each other's phone numbers.

### Actual behaviour
You see their phone numbers (probably especially if they had not created a username for themselves).

### Configuration
**Operating system:** Windows 10 Pro (10.0.10586 Build 10586)

**Version of Telegram Desktop:** 0.9.44 (Not a fresh installation or installing the updates manually by downloading the exe files from the site. It's been updating itself for a few months now.)

- - - - - -

I've already heard people are abusing this problem to scam other users (even claiming they are Telegram employees and that's why they have their phone numbers)! I guess you should do something to make sure either all Telegram Desktops affected by this bug get forcefully updated or find a way to force them to clear cache or whatever to retrieve their data again from the servers to update and overwrite the data that's causing this behavior (Some of them even say they're not gonna install new updates anymore to be able to continue abusing this bug)!

**Comment by stek29** [comment]
What time it was? Do you still have this issue?

**Comment by TheVorlon** [comment]
> What time it was? Do you still have this issue?

I've noticed it recently after someone (whom I've never visited his profile before, so no cached version or anything of that person stored on my device) was added to a normal group that I'm also a member of and then I noticed that I can see his phone number, so I asked him and he said that he can't see mine cuz he doesn't have my phone number in his contacts (neither do I have his) and this was a few days ago after that long server downtime across Europe and kept on going (I still say his phone number every time I relaunched the program and even after system reboots).

Today I overheard other people mention the same behavior and how some of them have abused it so then I realized that this is not just a random bug that just happened to me and that particular person! All of them experienced this on the Windows version of Telegram Desktop 0.9.44 during the past few days and it's not like something temporary! They can see the phone numbers of the new people who get added to groups (again only the ones whom profiles were never visited by them before = total strangers).

A while after I posted the initial post, I saw there was a new version on the site (0.9.46) but didn't notice that it's an alpha version so I clicked on Download and after installing it just realized that it's the same version 0.9.44! The interesting thing is that I do not see the phone number of that guy anymore, so unless there had been a secret fix to this version, I should probably see it happen again but then I'm just on a few small groups so I can't test whether it still happens or not soon. I guess installing the exe file probably refreshed my Telegram Desktop's local cache (more than just relaunching the program) to sync the data with the servers (assuming that there hasn't been a secret bug fix).

It's most probably just a client-side bug in this particular Desktop version because I've not seen/heard it happen on the mobile versions and all of those who have experienced it and still are, are on Windows version 0.9.44.

**Comment by TheVorlon** [comment]
Nope it's not happening anymore after I've reinstalled the version 0.9.44 from the exe file on the site. It means that if there had not been any secret fixes to this exe file, then it only affects the [Windows] Desktop clients that were "updated" to the version 0.9.44 automatically by the program itself. And as far as I could gather information from people, this probably started after the recent server downtime that lasted an hour or so! I don't know how Telegram's servers operate so I can't imagine the relevance between servers going down such behavior getting triggered in Telegram Desktop 0.9.44 [Windows] (that were probably open during the downtime, assuming that the two are related)!

**Comment by john-preston** [comment]
@TheVorlon They are identical (updated and reinstalled). This can't be a client side issue, all clients show all information that server has shared with them.

**Comment by TheVorlon** [comment]
> @TheVorlon They are identical (updated and reinstalled). This can't be a client side issue, all clients show all information that server has shared with them.

Then I guess probably something during the recent downtime happened (a glitch or whatever you might call it) that gave at least some users on [running] Telegram Desktop 0.9.44's, including me before reinstalling the 0.9.44 exe, access to such information. Seems like it happens only on normal groups (not supergroups and such) and last time I asked about it, they're still capable of seeing the phone numbers of newly added members in normal groups on TD 0.9.44.

I hope you find a way to force the Desktop clients affected by this to fully update and re-sync their cached data with the servers to stop this behavior on them that's being abused by some!

Thank you

**Comment by john-preston** [comment]
@TheVorlon Can you contact me privately at https://telegram.me/preston and give an example? Two users (two phone numbers) who definitely never were in contacts list of each other, but one of them can see the phone number of the other one.

I'll try to ask a server side developer about this issue with that example.
