### ISSUE TITLE
can't make telegram channel or group while I'm not limited!

### ISSUE THREAD

**Issue by ITakinnz** [telegramdesktop/tdesktop#1969]
I have made some groups before and one channel, which I removed it when I couldn't make another channel (just tried) but the problem was still there. The error is short: "Sorry, this action is not available."
This error appears on desktop version(0.9.44 on mac) , but on the android app it's just a loading window and nothing happens then!

**Comment by ITakinnz** [comment]
why is it invalid really?

**Comment by auchri** [comment]
Because the issue had no description initially.

**Comment by ITakinnz** [comment]
It was a mistake.

**Comment by auchri** [comment]
what happens if you try it in the web version? https://web.telegram.org?

**Comment by ITakinnz** [comment]
There is no channel option, 
and
for creating new group It say's : 

Access denied
You are not allowed for this action.

technical details:

Method: messages.createChat
Url: N/A
Result: {"_":"rpc_error","error_code":403,"error_message":"USER_RESTRICTED"}
Stack: Error
    at Object.g [as invokeApi] (https://web.telegram.org/js/app.js:31:11150)
    at m.e.createGroup (https://web.telegram.org/js/app.js:38:22906)
    at https://web.telegram.org/js/app.js:17:26445
    at https://web.telegram.org/js/app.js:22:1736
    at m.$eval (https://web.telegram.org/js/app.js:16:3938)
    at m.$apply (https://web.telegram.org/js/app.js:16:4168)
    at HTMLButtonElement.<anonymous> (https://web.telegram.org/js/app.js:22:1718)
    at HTMLButtonElement.ie.event.dispatch (https://web.telegram.org/js/app.js:5:2788)
    at HTMLButtonElement.f.handle (https://web.telegram.org/js/app.js:4:31558)

**Comment by auchri** [comment]
> USER_RESTRICTED

So your account is limited, there is nothing we can do for you.

**Comment by ITakinnz** [comment]
But this is really unfair, I have not made a single spam massage till now. how can I request to check this?

**Comment by auchri** [comment]
I don't know, maybe `@SpamBot` tells you more details.

**Comment by stek29** [comment]
@ITakinnz Or use "Ask a question" button in app.
