### ISSUE TITLE
Improvement for chat-specific notification settings

### ISSUE THREAD

**Issue by VBelozyorov** [telegramdesktop/tdesktop#197]
It's would be great to have `Desktop notifications` checkbox in chat-specific settings.
Example:
I'm using tdesktop on work PC and prefer to disable notifications for only this client from some non work-related chats. But if I disable `Notifications` checkbox (which already presented in chat settings) those notifications will be disabled for all my clients (mobile, home PC) at once.

Thank you!

**Comment by Aokromes** [comment]
not sure if this must be done api side.
