### ISSUE TITLE
Missing files art/sprite_125x.png, art/sprite_150x.png

### ISSUE THREAD

**Issue by xypron** [telegramdesktop/tdesktop#1972]
```
git clone https://github.com/telegramdesktop/tdesktop telegram-desktop
cd telegram-desktop/Telegram
qmake
```
results in
```
RCC: Error in 'Resources/telegram.qrc': Cannot find file 'art/sprite_125x.png'
RCC: Error in 'Resources/telegram.qrc': Cannot find file 'art/sprite_150x.png'
```

This problem was already reported in #864 but unfortunately the issue was close.

**Comment by auchri** [comment]
Here are instructions to build tdesktoop with qmake: https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-qmake.md

**Comment by john-preston** [comment]
@xypron It should not be a problem, this files will be generated by codegen_style project, when you'll build all other parts by instructions.

**Comment by ifreedom** [comment]
@john-preston I also met this problem when compile use xcode, and I found the script execution order is wrong, these two file is generated by codegen_style, but Preprocess is executing before codegen_style step.

**Comment by john-preston** [comment]
@ifreedom yes, looks like you're right! Thanks, I'll fix the project.
