### ISSUE TITLE
[Feature Request] bash like behavior for chat windows. for better/easier usage of bot commands or messages

### ISSUE THREAD

**Issue by timsamart** [telegramdesktop/tdesktop#1974]
### Feature explanation

It would be great if you could use arrow up and down to navigate earlier commands/texts. I am imagining a bash like behavior. This would be totally awesome and enable so much more possibilities. Especially when handling telegram bots.

Maybe even use the TAB to automatically switch between bot commands?

### Steps to reproduce

- remember last commands in each chat
navigate previous commands with up/down arrow on the keyboard like in bash/cmd

### Configuration

Operating system: Windows 8.1

Version of Telegram Desktop: 0.9.44

**Comment by auchri** [comment]
See #1060
