### ISSUE TITLE
Irrelevant Ubuntu Mate tray icon appearance: as N/A icon

### ISSUE THREAD

**Issue by anon5** [telegramdesktop/tdesktop#1975]
### Steps to reproduce
1. Run Mate Desktop Environment 1.8.2
2. Under it, run the Telegram Desktop: .../Telegram/Telegram -- %u

### Expected behaviour
Icon would draw properly with Tg logo

### Actual behaviour
N/A icon is shown

If I restart Telegram with "killall Telegram" and relaunch it, the icon is still N/A after relaunch.

### Configuration
**Operating system:**

Ubuntu 14.04.3 LTS

**Version of Telegram Desktop:**

0.9.42

### Logs
Nothing relevant

**Comment by anon5** [comment]
![tg_mate_systray_icon](https://cloud.githubusercontent.com/assets/16508513/14944714/5dffecda-102e-11e6-9497-90339c2717f0.png)

**Comment by stek29** [comment]
Related to #1411?

**Comment by egphilippov** [comment]
I researched this issue. There is a couple of qt bugs about tray icons. Under mate, Qt 5.6.0 generates the issue reported above. I tried to build another Qt app with tray icon under Qt 5.0.2, the tray icon appears normally, without any issue.

I will try to rebuild Telegram Desktop with Qt 5.0.2, will tell whether I succeeded with build process and tray icon.

One can get Qt 5.0.2 at https://download.qt.io/archive/qt/5.0/5.0.2/

**Comment by egphilippov** [comment]
Does not build under Qt 5.0.2 =)) codegen_style fails to build due to " http://doc.qt.io/qt-5/qmap.html#QMap-1 This function was introduced in Qt 5.1. " and also due to other errors.

So I might try to find another Qt >= 5.1 which has sane tray icons for Mate

**Comment by john-preston** [comment]
@egphilippov You can try Qt 5.3.2. Code branch mac32 is built against that Qt version for OS X 10.6 and 10.7 support.

**Comment by egphilippov** [comment]
A failure. Qt 5.3.2 build another tray icon app so that the tray icon is invisible at all.

**Comment by egphilippov** [comment]
Qt 5.5.1 behaves exactly like Qt 5.6.0 wrt tray icon.

**Comment by egphilippov** [comment]
https://download.qt.io/archive/qt/5.5/5.5.0/qt-opensource-linux-x64-5.5.0-2.run behaves seemingly exactly like Qt 5.5.1 and 5.6.0.

**Comment by egphilippov** [comment]
Qt 5.1.1 behaves like Qt 5.3.2.

**Comment by egphilippov** [comment]
Under Qt 5.7.0 ( 15-Jun-2016 ), the icon's image displays okay, but the mouse signals are not delivered (trigger, double click, middle click do not generate the signal `activated(QSystemTrayIcon::ActivationReason)`)

**Comment by egphilippov** [comment]
The following comment might be a bit relevant: "I have builded QT-5.5.0-alpha1(on Linux Mint 17.1 64-bit) and tested showing of icon in system tray with kadu (polish instant messenger, http://www.kadu.im). I've been starting many times kadu on Mate desktop environment and 100% working." from here https://bugreports.qt.io/browse/QTBUG-35658

**Comment by hypnosis-i2p** [comment]
I found a great solution:

`dbus-launch ~/bin/TelegramDesktop/Telegram -- %u`

It works completely OK under Mate. The icon displays Telegram logo and mouse clicks are handled as they should.

Thanks to http://askubuntu.com/questions/732967/dropbox-icon-is-not-working-xubuntu-14-04-lts-64 .

**Comment by auchri** [comment]
@hypnosis-i2p https://github.com/telegramdesktop/tdesktop/issues/1716#issuecomment-219225923 🙈

**Comment by anon5** [comment]
I have a report that the dbus-launch solution also works in KDE for Dropbox icon.
