### ISSUE TITLE
Support for Universal Windows Platform (UWP)

### ISSUE THREAD

**Issue by lukap3rcic** [telegramdesktop/tdesktop#1979]
Hi, i was wondering what is your timeline for this, since you did update to Qt 5.6, which by itself does support UWP.

Unfortunately, Telegram CLI looks half dead and we lost any hope that they will support it (in the foreseeable future).

Best,
Luka

**Comment by auchri** [comment]
> Hello friends why not porting the TDesktop Win32 program trough the progect Centenial to the Windows 10 Universal Windows Platform? doing this the resulting app will look as normal but will be enclosed in a sandbox by security purposes and will get some improved features like automatic update trough the store, live tile, a wider use of the new Windows aniversary update's notifications (wich has more functions like direct reply hero image and even the posibility to display the stickers on the notification) and even the posibility to have a section for the app in the Windows feedback app wich can be used similarly to GitHub's issues page, if you want to try the progect Centenial app converting you only need an insider build of Win10 and this apps wich is cold windows app installer https://www.microsoft.com/en-us/store/apps/microsoft-desktop-app-installer/9nblggh4nns1

C/P from #1989

**Comment by sergioad** [comment]
And even with this migration the app could be installed with not a traditional .exe instalation process and also with the movement to the UWP platform you get the benefit of being discoverable in store and be voted by the users

**Comment by lukap3rcic** [comment]
@sergioad that is good short term solution, but I do believe we need something that will run on whole windows ecosystem and not just on x86 desktop one.

Not using win32 api means that telegram desktop can be run on Windows 10 Mobile (arm with Continuum- external monitor desktop mode), Xbox, HoloLens and even Windows 10 IoT Core (system for Raspberry Pi and other boards). 

Centennial still uses win32 api and would not work on these systems. There is also no solid information on that if the 3rd party centennial apps would be really allowed in the store ([one source](http://mspoweruser.com/microsoft-desktop-app-installer-now-available-in-the-windows-store/)), though it would be at least very easy to side-load using this [windows store app](http://microsoft.com/store/apps/9nblggh4nns1).

.appx instead of .exe would be the first step, but what I am really asking is to rewrite (most) dependencies from win32 api to UWP. 
(you can still use win32 through centennial for some non-essential desktop-only features).

**Comment by sergioad** [comment]
@lukap3rcic I totally agree but for the short term could be a nice solution; there are some Telegram web wrapers and one unofficial telegram web so could be nice to get at least for the short term an official WIn10 app for telegram, obviously a totally integrated UWP Telegram app would be even better than a project Centenial one but this could be a "good" fix for (again) the short term

**Comment by jessenic** [comment]
Bumping this up now that the Desktop App Converter has been released and desktop apps have started showing up in the Store.

https://developer.microsoft.com/en-us/windows/bridges/desktop

As an example here's how Team Kodi does it: https://github.com/xbmc/xbmc/tree/master/project/Win32BuildSetup

You could upload the converted store app package on the same Store app as the Windows Phone version of Telegram: https://www.microsoft.com/store/p/telegram-messenger/9wzdncrdzhs0
So users on Windows Phone get the phone version and PC users get the converted Telegram Desktop from the same link and when you eventually have a proper UWP app, both will get upgraded to that.

**Comment by ban1shed** [comment]
Anything new? I would love to see this happen!

**Comment by AntonioLov** [comment]
Waiting to see uwp telegram app...

**Comment by auchri** [comment]
Contribute to https://github.com/UnigramDev/Unigram ;)

**Comment by auchri** [comment]
https://www.microsoft.com/en-us/store/p/telegram-desktop/9nztwsqntd0s

**Comment by stek29** [comment]
@auchri it's on Microsoft Store, but it is not UWP.

**Comment by lukap3rcic** [comment]
Have to agree. It's a (good) start, but the main job still remains; removing win32 calls from the code (qt is ready).

**Comment by db2k** [comment]
@auchri thanks already, thats a good start! Looking forward for your support on the Windows Store since the Store is a really good and safe way to keep computers clean.

Are there any plans for a real UWP app? Or is that open for someone else?

**Comment by john-preston** [comment]
@db2k There is an unofficial project targeting UWP: https://github.com/UnigramDev/Unigram
It is possible for this application to become a real UWP app, but no such plans or work is done yet and this is not planned in the near future.

**Comment by Acid-Crash** [comment]
Hi here.
It's been a while since this conversation happened.
Are there any updates on this matter?
