### ISSUE TITLE
Audio messages and Mic funcionalities even for the Desktop version

### ISSUE THREAD

**Issue by PUOjACKz** [telegramdesktop/tdesktop#198]
Hi, I would suggest you to introduce the possibility, for who have the microphone in their PCs, Macs, Linuxs, to send audio messages, like its already present on the Android counterpart of the software.

**Comment by rezapc** [comment]
+1. Please add this function soon. very useful

**Comment by jayallen** [comment]
+1 I love this function on iOS.

**Comment by Katzen-Gott** [comment]
@PUOjACKz It was added in v0.19.8. Cold you please close the issue? (there is a button below the comment box)

**Comment by mirhl** [comment]
I guess you meant 0.8.18
