### ISSUE TITLE
Taskbar icon not displayed in Windows 10

### ISSUE THREAD

**Issue by vitorcanova** [telegramdesktop/tdesktop#1980]
### Steps to reproduce

I installed and reinstalled the app and the problem persists. When I open it the taskbar icon shows a default app icon instead of the Telegram icon.
### Expected behaviour

The app should show the Telegram icon in Taskbar. Overlay is shown.
### Actual behavior

It shows a default app icon.
![capture](https://cloud.githubusercontent.com/assets/10546504/14983358/20bfe0f6-1113-11e6-9b17-a06bfdb7852d.PNG)
### Configuration

Windows 10 Pro version 1511 build 10586.218

Telegram 0.9.44

**Comment by dgadelha** [comment]
Confirmed to be working with Telegram 0.9.48 (dev) and Windows 10.0.14332

**Comment by maxomaniak** [comment]
Got the same problem with Telegram 0.9.48 and Win10

**Comment by vitorcanova** [comment]
After some days (and no app update) it started to work by itself.

**Comment by romangr** [comment]
Still not working for me.
v.0.9.49
Win 10.10586
![314](https://cloud.githubusercontent.com/assets/2869334/15456446/0595ba92-2079-11e6-8e48-f71178c534ad.png)

**Comment by liquidblasted** [comment]
Same here, but I have default windows icon on taskbar only if I close Telegram app with close button (and it still works in tray)
If app is open at the screen or minimized, it has Telegram icon as it should.
v.0.9.49
Win 10 Pro 10586

**Comment by Aokromes** [comment]
works for me on 0.10.19 alpha and never combine buttons on RS2 Version 10.0.14959 and on 0.10.16 on windows 10 anniversary edition with always combine, hide labels.

**Comment by auchri** [comment]
I experienced the same behavior with other apps too, so it seems to be a windows issue.

**Comment by zafrulizham** [comment]
![fix_taskbar_telegram](https://cloud.githubusercontent.com/assets/10254372/21769866/bb6e02ea-d6bb-11e6-9755-d77e726ae857.png)

Right click > pin to taskbar, it works for me

**Comment by ssdd28561** [comment]
> ![fix_taskbar_telegram](https://cloud.githubusercontent.com/assets/10254372/21769866/bb6e02ea-d6bb-11e6-9755-d77e726ae857.png)
> 
> Right click > pin to taskbar, it works for me

Thanks from the future. Two years later, same problem on fresh windows 10 installed.
Spent several days trying to fix it, re-installing etc doesn't help, your fix does work.

**Comment by XeZrunner** [comment]
> > Right click > pin to taskbar, it works for me
> 
> Thanks from the future. Two years later, same problem on fresh windows 10 installed.
> Spent several days trying to fix it, re-installing etc doesn't help, your fix does work.

Can confirm - in 2020, this worked.
