### ISSUE TITLE
User being reported without solid reason

### ISSUE THREAD

**Issue by rasoolsn** [telegramdesktop/tdesktop#1981]
### Steps to reproduce
1. I enter a group
2. Choose one of the users
3. Go to their info page
4. Block that user

### Expected behaviour
The person should be simply blocked

### Actual behaviour
The person gets reported!
With this anyone can report the other without any solid reason.
This is what happened to us Iranians.
We are witnessing people being unnecessarily reported every day.
Abusers just enter one's info page and get them reported.
Reporting should be done by reporting spam, not blocking.
Why a non-spammer should be reported?
I have tested it.
I sent a text to someone I know and they forwarded it to others, then others went into my info page and reported me.
Without me even talking to them!
This is not fair.
Even if users never talk to strangers on Telegram, they get reported.

### Configuration
**Operating system:**
All of them

**Version of Telegram Desktop:**
0.9.42

Sorry but this is not only limited to Telegram Desktop. It's because of Telegram's options that lets users abuse it.
I had nowhere else to say this. I hope the problem gets fixed

**Comment by stek29** [comment]
Please use <kbd>Ask a question</kbd> button in Settings.

**Comment by rasoolsn** [comment]
Thank you :)
