### ISSUE TITLE
Message counter

### ISSUE THREAD

**Issue by c143** [telegramdesktop/tdesktop#1985]
Hello
Sorry for reposting, but i saw many people want this to happen: https://github.com/telegramdesktop/tdesktop/issues/1296. Since you closed the post, i guess you don't get notifications anymore.

It could look like this:
<img width="822" alt="screen" src="https://cloud.githubusercontent.com/assets/9988714/15018516/243dcefc-121a-11e6-8339-8d79bd63782d.png">

Feel free to delete this post.

Greetings

**Comment by stek29** [comment]
> Since you closed the post, i guess you don't get notifications anymore

Nope, notifications are received for comments on closed issues too.

**Comment by anthonylake** [comment]
It's a great idea, would love to see it implemented.
