### ISSUE TITLE
on linux desktop: icon is gray and no system notification anymore

### ISSUE THREAD

**Issue by badpenguin** [telegramdesktop/tdesktop#1986]
### Steps to reproduce
1. just receive any message

### Expected behaviour
The icon used to have a red circle with the notification number and there was a system toast message

### Actual behaviour
No system notification, no toast
The icon is gray now and the notification number is unreadable

### Configuration
Debian Jessie with Cinnamon

**Version of Telegram Desktop:**
0.9.4.2

**Comment by john-preston** [comment]
@badpenguin Maybe the conversation is muted? The counter is gray then.

**Comment by badpenguin** [comment]
@john-preston sorry :-( it seems the case... i think that the APP on the mobile phone created this problem on the desktop. I will investigate and remove the mobile phone APP because its annoying to have notifications on both dekstop and mobile at the same time.
