### ISSUE TITLE
[SUGGESTION] port TelegramDesktop via the Windows 10 desktop app installer / progect centenial to the WIndows store

### ISSUE THREAD

**Issue by sergioad** [telegramdesktop/tdesktop#1989]
Hello friends why not porting the TDesktop Win32 program trough the progect Centenial to the Windows 10 Universal Windows Platform? doing this the resulting app will look as normal but will be enclosed in a sandbox by security purposes and will get some improved features like automatic update trough the store, live tile, a wider use of the new Windows aniversary update's notifications (wich has more functions like direct reply hero image and even the posibility to display the stickers on the notification) and even the posibility to have a section for the app in the Windows feedback app wich can be used similarly to GitHub's issues page, if you want to try the progect Centenial app converting you only need an insider build of Win10 and this apps wich is cold windows app installer https://www.microsoft.com/en-us/store/apps/microsoft-desktop-app-installer/9nblggh4nns1

**Comment by auchri** [comment]
#1979

**Comment by sergioad** [comment]
@auchri but I added important information wich is not in your mentioned issue (#1879) please reconsider re-opening thi issue or otherwise mix them into one

**Comment by auchri** [comment]
I've copied the text for you in the other issue.

**Comment by sergioad** [comment]
Ok :smile:
