### ISSUE TITLE
Touchscreen support

### ISSUE THREAD

**Issue by 123RaZoR321** [telegramdesktop/tdesktop#1995]
There are some problems I've found when using Telegram on Windows Tablet (Win10).
- [x] Keyboard doesn't pop up automatically when tapping on a field (it works in other win32 apps so I believe it's not a limitation)
- [x] "Right-clicking" with touchscreen is a bit tricky (you have to release your finger at a very specific time)
- [ ]  It's impossible to choose between sending File or Photo, the button just open file picker (probably this would work with a stylus, but you can't "hover" with a finger)
- [ ] Touching the Telegram icon in the taskbar results in Exclamation sound, have to tap the icon again to minimize.

**Comment by auchri** [comment]
> Keyboard doesn't pop up automatically when tapping on a field (it works in other win32 apps so I believe it's not a limitation)

#218

**Comment by auchri** [comment]
> "Right-clicking" with touchscreen is a bit tricky (you have to release your finger at a very specific time)

#989

**Comment by alecuba16** [comment]
Same problem, no softkeyboard opens on any input text on telegram desktop,there is some work-arround?

**Comment by Aokromes** [comment]
the 3rd, i must say it's really hard, but doable.

**Comment by cherepets** [comment]
Touch doesn't respond in this app in any manner on Surface Pro 3

**Comment by pitlochry** [comment]
I can confirm that touch does not respond in any manner on Surface Pro 3 on linux/fedora

**Comment by r-darwish** [comment]
![telegram keyboard](https://user-images.githubusercontent.com/1383193/79608235-47542700-80fd-11ea-805b-41b1535015a6.png)
 I'm experiencing a different problem. They keyboard actually pops up but telegram does not reposition the text box above the keyboard, so writing is impossible. In addition, the windows stays shrinked after the keyboard is gone

**Comment by pitlochry** [comment]
still an issue

**Comment by laozhoubuluo** [comment]
**"Right-clicking" with touchscreen now is not tricky, this feature cannot be used in 2.5.8.**

**Comment by Aokromes** [comment]
4.2.1 added some touch improvements, test there when ready.
