### ISSUE TITLE
Audio output

### ISSUE THREAD

**Issue by luc1ph3r** [telegramdesktop/tdesktop#1996]
### Steps to reproduce
1. Open pavucontrol (or any other sound manager)
2. Change "Built-in Audio Analog Stereo" output to prefered audio output for Telegram.

### Expected behaviour
Audio stream changes to prefered one.

### Actual behaviour
It doesn't change at all. So, in my case, I can not listen audio files from Telegram (my laptop's jack is broken and I have to stream audio to another audio output).

### Configuration
**Operating system:** ArchLinux

**Version of Telegram Desktop:** 0.9.42

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#418
