### ISSUE TITLE
telegram wont start

### ISSUE THREAD

**Issue by Sebastian43** [telegramdesktop/tdesktop#1997]
1. When I click on Telegram.exe, I expect it to launch 
2. There is no response
3. Win7 Ultimate, 32bit; telegram v0.9.44 or higher
This non-responding has happened several times recently, starting early April. It seemed to be a reaction to installing Viber, but has operated alongside Viber quite well since. Since Telegram wont launch, I can not "type "debugmode" in settings" and therefore can not attach a log.

**Comment by stek29** [comment]
What if you start it in command line?

**Comment by Sebastian43** [comment]
No need.
It came good after a reboot.
Joe
