### ISSUE TITLE
[UI] [Improvement] Using new color palette used in Android version

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#2001]
### Proposal

In version 3.8 of Telegram for Android, is used a new color palette slightly changing the "look and feel" of the interface. It would be great that Telegram Desktop will use the same color palette to provide consistency across platforms.

Cheers
### Configuration

**Operating system:** Fedora 23 Workstation 64 bit 
**Version of Telegram Desktop:** 0.9.47 alpha

**Comment by stek29** [comment]
@diazbastian Why do you "thumbs-up" your own comments? I notice it second time...

**Comment by diazbastian** [comment]
@stek29 It is obvious, it is because I agree with the proposal. The Github system reactions allows estimating the positive/negative reactions on the comments.

Why bother to ask why? ... But better do you agree or disagree with the proposal?

**Comment by stek29** [comment]
@diazbastian It's confusing... You wrote it, of course you agree.

**Comment by diazbastian** [comment]
@stek29 Come on, it's not a facebook like or a Tumblr favorite, etc ... on Github is used more as a head count and of course I want to add my vote.

It seems silly to discuss this, is totally offtopic.
