### ISSUE TITLE
Switch to inline mode not working correctly

### ISSUE THREAD

**Issue by MalekAlrwily** [telegramdesktop/tdesktop#2002]
### Steps to reproduce
1. Click an inline keyboard button which should switch the user to inline mode
2. Choose a chat

### Expected behaviour
It should put the bot username in the message field with the parameter provided by the bot (if any).

### Actual behaviour
In groups: the button won't work at all.
In one-to-one chat: It will put the other party username instead of the bot name.

### Configuration
**Operating system: Linux**

**Version of Telegram Desktop: 0.9.42**

### Logs
Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

**Comment by stek29** [comment]
Can you test 0.9.44?
Can't reproduce in 0.9.47...

**Comment by MalekAlrwily** [comment]
Bug fixed today when Telegram Desktop has been updated to version 0.9.48.
