### ISSUE TITLE
[Feature request] Pinned messages

### ISSUE THREAD

**Issue by antonsteenvoorden** [telegramdesktop/tdesktop#2009]
It would be nice to have a "Pinned messages" of some sort for groups. Sometimes important messages get lost quickly. And ofcourse a way to pin messages.

**Comment by john-preston** [comment]
@antonsteenvoorden You can convert your group to a supergroup, where pinned messages are available.

**Comment by stek29** [comment]
Type "tosupergroup" in group info page to do it.

**Comment by john-preston** [comment]
@stek29 There is no need to do that now. There is a link in any group profile (for the group creator only) to convert to supergroup.
