### ISSUE TITLE
Telegram Desktop (0.9.4.8) constantly losing connection behind proxy

### ISSUE THREAD

**Issue by docholiday** [telegramdesktop/tdesktop#2010]
### Steps to reproduce
1. Start Telegram behind proxy
2. Usually it works for some minutes.
3. Then suddenly the connection is lost, and it takes between 2 up to 15min before its connected again.

Sometimes the connection is lost from the beginning, then it seems to be better, to shutdown telegram and start another instance.
### Expected behaviour

No connection loss
### Actual behaviour

Telegram loses the connection very often and takes very long before it gets reconnected.
This was not the case about a month ago, so I guess one or two versions earlier.
### Configuration

**Operating system:**
Windows 7 SP1
with proxy

**Version of Telegram Desktop:**
0.9.4.8

Interesting notice: I went into debugmode and had no connection problems at all. After about 15 minutes, I stopped the debogmode again and instantly the connection problems were back.

**Comment by julianxhokaxhiu** [comment]
This is no more the case. I'm using Telegram everyday behind a proxy and it works ok.

Maybe it's time to close this :)
