### ISSUE TITLE
Disable notification sound when "Do Not Disturb" is enabled in OS X

### ISSUE THREAD

**Issue by julioolvr** [telegramdesktop/tdesktop#2011]
### Steps to reproduce
1. In OS X, enable "Do Not Disturb"
2. Receive a message
### Expected behaviour

No sound or notification popup should show up. The icon bouncing and the unread counter increasing are fine as other apps do the same (e.g. Slack).
### Actual behaviour

The notification doesn't pop up, but the sound is heard anyway.
### Configuration

**Operating system:** OS X El Capitan 10.11.4

**Version of Telegram Desktop:** 0.9.48

---

_Edit:_ Updated version, still happening in 0.9.48.

**Comment by 123RaZoR321** [comment]
The same happens on Windows 10 with Quiet hours enabled. No notification, but the sound is there.

**Comment by nDmitry** [comment]
Still actual for 1.0.0 for macOS.

**Comment by john-preston** [comment]
@nDmitry In Windows it should be fixed already.. can anyone point to the macOS APIs that could be used to know if DND is currently enabled?

**Comment by stek29** [comment]
@john-preston http://stackoverflow.com/a/39095105/5279817
