### ISSUE TITLE
Add a setting to disable the new up key -> edit message

### ISSUE THREAD

**Issue by Robadob** [telegramdesktop/tdesktop#2012]
### Steps to reproduce
1. Send a message (to a supergroup?)
2. Press up arrow key
### Expected behaviour

Scroll up through previous messages
### Actual behaviour

It changes the message typing box into an edit last message if supergroup, else does nothing. This is not the desired behaviour, in my own case I scroll up through messages in a super group far more often than I edit the last message I sent (and I find the use of page up/down undesirable, due to them jumping a whole page).

It would make far more sense to bind the edit message to left or right arrow key, rather than breaking the existing (useful) hotkey across all chat types to add a minor function that can only benefit super groups, even if that isn't symmetric to a console/irc.
### Configuration

**Operating system:** Windows

**Version of Telegram Desktop:**  0.9.48

**Comment by stek29** [comment]
Maybe it should be <kbd>Ctrl</kbd> + <kbd>Up</kbd> as in #1060?

**Comment by Robadob** [comment]
That's another suitable possibility (I would personally use it so rarely I'd probably just right click the offending message, I'm not particularly bothered with correcting minor typos that don't affect comprehension). 

The removal of `up` to scroll messages is driving me nuts.

**Comment by Kondra007** [comment]
Even though we can still scroll chats using `PageUp` and `PageDown`, I'd like the shortcut to be changed to `Ctrl+Up`

**Comment by Robadob** [comment]
#2017 
New issue seems to make the same complaint.

**Comment by mirh** [comment]
Given I don't see a correspondent "`down` action" for edit action and given how (especially on a laptop with no mouse wheel) I probably scroll tens of times more than I would ever require to edit, I would reserve `Ctrl+Up` for the later.

**Comment by SDKiller** [comment]
> They've also specifically mentioned it in their latest blog post, so it might not be going anywhere :(

That's too bad as it is UI regression, IMO.

> I probably scroll tens of times more than I would ever require to edit

:+1: 

@ tdesktop devs 

Consider this common scenario:

1) you open telegram and see "You have N new messages" 
2) you use arrow **down** to scroll new messages from start
3) you overscroll 2-3 lines and just want to bring this few lines back into view - its natural to press **up** button - if you used down button previously.

I suppose most would expect up and down arrows to work in similar way (just in opposite directions).

This "magic" with using **Up** to bring last message to edit is unexpected UI behavior and breaks functionality everybody got used to.

Probably this is skype-like behavior, I'm not sure.
But if me or anyone wanted to use skype for messaging - they won't use Telegram.

**Comment by shark0der** [comment]
Came here to open an issue exactly for this. Glad it's open already. I was about to suggest a modifier for scroll up, but @SDKiller brings up a good point. I think an option would be to make it configurable so the users will be able to choose whether to scroll with `up` or `ctrl+up`, but please, definitely bring the scroll feature back.

I caught myself pressing up and editing the messages. Even more than this, I started to press `up`, the edit box appears, I keep the `up` button pressed and it scrolls! annoying that I have to hit `esc` when I scrolled enough.

**Comment by ryabina** [comment]
It drives me nuts. I don't use a mouse on my laptop and it's getting hard to find  a needed message in a group.

**Comment by b9sk** [comment]
My experience about the new "edit on Up arrow button" feature. When you use arrow keys for scrolling the new feature become an annoying because you can't use scrolling by arrow keys properly. When you want to scroll up the message screen (by one line or two) you have to use Pg Up button and then Down arrow button. Sometimes you forget about this complicated rule and press Up arrow button again.

How about an optional setting feature that disables "edit last message on Up arrow button"?
It would be a nice alternative.

**Comment by Kondra007** [comment]
@b9sk Lifehack (for now): Just enter any symbol (even space) in message box, and then `up` key will scroll up as usual.

**Comment by b9sk** [comment]
@Kondra007 Thank you! It's a very useful workaround.

**Comment by nickaein** [comment]
One of the principals for a user-friendly UI is that it should behave as the way the user commonly expects. This _feature_ is prime example of violating this principal. 

Nobody expects the **Up** to work as a shortcut for editing for the last message. You have to _teach_ the users this shortcut, and I am sure they have a hard time remembering it. 

Even assuming the users get used to this shortcut, every new new user will be always annoyed with this since almost no other user-interface has this behavior. 

In the contrary, almost everybody expects the **Up** key work similarly to **Down** key. If pressing **Down** do something, the **Up** should usually undo that.

Currently, no only the intuitive meaning of **Up** key is violated, but also the designer have been inconsistent in assigning tasks to these two keys. The **Up** key edits the last message while the **Down** key scrolls down.

If this doesn't get resolved, we can fork and remove this stupid shortcut.

**Comment by b9sk** [comment]
@nickaein Pretty good explanation. Besides Left and Right arrow keys still has no bind actions.

**Comment by SDKiller** [comment]
Any planned work on this?

I'd better prefer to have this feature in settings rather then rounded message boxes after last update ;)

**Comment by stek29** [comment]
@SDKiller no milestone, no one assigned. No one created a PR, developer haven't even participate.
So I think the answer is "No".

**Comment by aeiris** [comment]
Please remove this annoying antipattern, at least add an option to disable it as other people proposed.

**Comment by luckydonald** [comment]
If you press <kbd>up</kbd> again it will start to scroll, just as expected.

**Comment by SDKiller** [comment]
> If you press up again it will start to scroll, just as expected.

Yes, but previous message text is still in edit field

**Comment by fidelt** [comment]
I don't think pressing up should immediately mean editing the previous sent message.
Most of the time, a person would press up when they want to scroll up.
It's also quite ugly to have to scroll up this way with the edit field blocking part of the view already, and even more so when you've just sent a lengthy message.

I believe that ctrl+up or any other key combination would be more appropriate to edit the message rather than simply pressing up.

**Comment by fbt** [comment]
In a lot of older chat clients, pressing the up cursor key means “put the last message into the buffer so I can edit it”, which is probably why Telegram, Slack and some others treat it as “edit my last message”. This behaviour is well-understood and people are used to it.

Maybe go the other way and make ctrl+up scroll up?

**Comment by SDKiller** [comment]
@fbt 
> In a lot of older chat clients...

This issue was open because telegram **did not do this initially** and people got used to it.

> Maybe go the other way and make ctrl+up scroll up?

The best way - to implement an option, like send by Enter or Ctrl+Enter

Anyway - this issue is more than 8 months old and no hope that anything will be done.

**Comment by luckydonald** [comment]
First of it is still an open source project, so this feature could be contributed by someone who think it is worth the effort.
That is, if @telegramdesktop (@auchri, @john-preston) would be willing to merge just setting. (Please give feedback!)

#### To give my two cents:
I actually like the up-to-edit-but-scroll-afterwards-if-cursor-is-at-the-top-of-the-edit-message (current),
But I am the opinion, that a setting for changing that locally wouldn't hurt.

### What is the proposed setting?
Mapping editing to be only on <kbd>ctrl</kbd>+<kbd>up</kbd>, making the scrolling via <kbd>up</kbd> instant?

**Comment by nachoparker** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  pkbrister@zoho.com
    Domain ownyourbits.com has exceeded the max emails per hour (3/3 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:44460 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by skywalker.onesite.co with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWMsS-000U1E-QF
	for nacho@ownyourbits.com; Wed, 25 Jan 2017 07:40:40 -0500
Date: Wed, 25 Jan 2017 04:40:00 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485348000;
	bh=uJdj172J1jeuz4Lw4K7+C0E3fX1NN/s4Dxfb6y5WhlQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=gSMHTKVws/vmFhxkModUxLjRtVdHa9rPgEavLWB4PKD0CO0gpMTP0TzqoJHocqKFc
	 xbIESl6BqohWQRtw1kappei7Z6FDvWUMjoTqDH+L4HB7R1T5ySM22ODxU9lDfxxsfM
	 x+tKqwPsOMPO7UtUxCylr+RQTfe+BMMJjvS8twZ0=

**Comment by danog** [comment]
LOL
RIP zoho, use yandex mail instead.

**Comment by mirh** [comment]
> In a lot of older chat clients, pressing the up cursor key means “put my last message into the input buffer”

I had never really noticed this terminal analogy.. Which I mean, it has its sense. 
And after all, what's telegram input box, if not a command line?

It's the remainder of the UI though that clashes with this paradigm. For starters, your messages indented on the right and only others on the left.. Nope, this ain't mIRC or cmd. 

Hence, I'd say ctrl+up for edit seems to make the most reason.

**Comment by stek29** [comment]
@mirh Skype had it. Also, in some cases your messages are indented on left with other messages.

**Comment by aeiris** [comment]
In a command line tool the behavior is Up key put my last message into the input line and Down key viceversa, this isn't what happens here, in Telegram Desktop, the last message remains in the input so if you only are using up key to scroll, and then you want to write a new message that means that you have to delete the previuos message first. Thats inefficient and annoying.
Also, when you are pressing up key to scroll, the program process the "edit last message" event first showing the "edit message" area first if not shown, so you need a second key up event to scroll, in every case, there's a delay in the scroll that is perceived as a program block, and it's annoying too.

**Comment by Aokromes** [comment]
better ticket https://github.com/telegramdesktop/tdesktop/issues/3366#issuecomment-299989401
