### ISSUE TITLE
Pulseaudio output switch not affecting Telegram

### ISSUE THREAD

**Issue by Fenisu** [telegramdesktop/tdesktop#2015]
### Steps to reproduce
1. Use telegram normally, and play a sound message.
2. Go to sound settings in your DE using pulseaudio, change the output device, ie: from computer speaker to bluetooth device.
3. All music and sounds goes to the new output device (bluetooth), but telegram keeps outputing to same first output device.

### Expected behaviour
Telegram should use pulseaudio's server to follow the changes of outputs devices.

### Actual behaviour
Telegram keeps using the same output device. The same device it was active when Telegram was opened.

### Configuration
**Operating system:**
ArchLinux

**Version of Telegram Desktop:**
All of them until now, 0.9.44

### Logs
Nothing shows up in debugmode.

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#776
