### ISSUE TITLE
Arrow Up does not scroll messages list on windows 7 (while arrow Down does)

### ISSUE THREAD

**Issue by SDKiller** [telegramdesktop/tdesktop#2017]
### Steps to reproduce
1. Place caret into "Write a message" field
2. Try to press arrows **Up** and **Down** to scroll messages list
3. You'll see that arrow **Up** does not scroll messages list while arrow **Down** does

### Expected behaviour

Arrow **Up** should scroll messages list

### Actual behaviour

Arrow **Up** does not scroll messages list.
Now only **Page Up** is working or you have to drag scrollbar with mouse.

### Configuration
**Operating system:**

windows 7

**Version of Telegram Desktop:**

0.9.48

### Logs
Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

**Comment by Kondra007** [comment]
That's because `up` button will be used to edit messages in the upcoming update (not 100% sure btw)

**Comment by SDKiller** [comment]
But it may work just like arrow **Down** works right now - if there is some text in the input field, scroll is disabled.

**Comment by PhoenixAlx** [comment]
bad, bad, bad idea the change of Arrow Up does not scroll messages list.
 Please, your return the functions original

**Comment by ali-shamakhi** [comment]
Up arrow scroll is working only in channel's you've joined, not those you are admin, and it is not working in private chats, groups and bots.
Sounds like some planned feature, maybe what @Kondra007 said.
BTW I prefer using arrows for scrolling

**Comment by auchri** [comment]
See #2012
