### ISSUE TITLE
[feature request] ability to rename contact in desktop application

### ISSUE THREAD

**Issue by abcdenis** [telegramdesktop/tdesktop#2018]
Hi,
I have to use Telegram for chatting in work purposes. I have plain mobile phone (not smartphone) so I am using desktop Telegram client under Mac OS. Unfortunately it does not have ability for renaming contact names thats why I have a lot of contacts without pictures and names and have to lookup contact author using my phone address book :)
It will be nice to rename (or even give name to) contacts in desktop.
Thank you.

**Comment by john-preston** [comment]
@abcdenis Actually you can name and rename them, if you have their phone number. Do you use the version from https://desktop.telegram.org?

**Comment by yrahul3910** [comment]
I think you can rename the contact by opening their chat, clicking on their name at the top, and then going to Edit. You should be able to change their name there.

**Comment by abcdenis** [comment]
It works, thank you.

**Comment by gelldur** [comment]
Why I can't edit come contact with I'm writing ? In other contacts I see `edit`

**Comment by RememberTheAir** [comment]
@gelldur see #3503
