### ISSUE TITLE
Window class (WM_CLASS)

### ISSUE THREAD

**Issue by pitje** [telegramdesktop/tdesktop#2019]
### Steps to reproduce
1. Start Telegram Desktop
2. Wonder why my i3 keybind to show/hide the Telegram Desktop window does not work
3. Find out that the used window class for Telegram Desktop has changed. Again.

Is this really bad? No. I can edit my i3 config, and it works again. But I should not need to do this every X updates.

### Expected behaviour
The window class for the Telegram Desktop client should not change.

### Actual behaviour
The window class for the Telegram Desktop client changes every few updates.

### Configuration
Arch Linux

**Version of Telegram Desktop:**
0.9.48

**Comment by remijouannet** [comment]
Hi,
I had the same problem, just add this two line
for_window [class="^telegram"] floating enable
for_window [class="^Telegram"] floating enable
to you i3 config file to fix this

**Comment by pitje** [comment]
Hi, as I already stated: "Is this really bad? No. I can edit my i3 config, and it works again. But I should not need to do this every X updates." (And also, in your example, I don't see the need for regexes in the window class name)

It's the, for me, completely illogical change in window class name (and, in one or 2 updates after that, another change) that I don't understand.
It would at least be nice to mention it in a commit message, so I know *that* it has changed.

**Comment by john-preston** [comment]
@pitje Where does it change in the source code? I'm afraid I don't quite understand what changes you are talking about and where this window class is set, whatever it is.
