### ISSUE TITLE
/top command doesn't work properly.

### ISSUE THREAD

**Issue by WvTongeren** [telegramdesktop/tdesktop#2022]
### Steps to reproduce

1.Have a self-made stickerset
2.use the command /top or /top N (where N is a number 1-20)
3.You can now see the top N of your most used stickers.
### Expected behaviour

Normally I'd get a list of stickers in this format:

/#1 
Today: 20
Yesterday: 34
(the most used sticker is placed here)

/#2 
Today: 23
Yesterday:25
(the second most used sticker is placed here)

etc, repeating for N amount of times.
### Actual behaviour

Instead of having a devision of Today:21/Yesterday:23 or something similiar, all my stickers are used exactly 100 times. Meaning that it looks like this:

/#1 
Today:0
Yesterday:100
(random sticker?)

/#2
Today:100
Yesterday:0
(a different sticker)

That, repeating N times. Normally I'd be flattered that my stickers are used so much but I doubt that all of my stickerset users have been using my stickers exactly 100 times every day for the past week or so.

![image](https://cloud.githubusercontent.com/assets/17336874/15250477/3b91dc62-1925-11e6-8b6e-e937e125b8f7.png)
I'm sorry for the harsh language in the image, that just happens to be the first sticker right now.

Sometimes it fuzzes the top even more, and a bunch of stickers end up in the top 20 that literally weren't used at all. (small stickersets that were made for friend requests, so their non-use is probably correct)  These usually end up in the lower half of the top 20 like this:
#19

Today: 0
Yesterday: 0
(random sticker)
#20

Today: 0
Yesterday: 0
(random sticker)

![image](https://cloud.githubusercontent.com/assets/17336874/15250945/78204c8e-1927-11e6-9056-a44e50748025.png)

Although I'm fairly certain that the non-used stickers really aren't used, those top few stickers always being used exactly 100 times is very strange. On top of that, my top 20 has been a slow gradient ranging between 60 and 20 uses each for months until this started happening.
### Configuration

**Operating system: Happens on both windows 10 and Android 5.0.2:**

**Version of Telegram Desktop: 0.9.48**
### Logs

Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

^I honestly can't figure out how to get to debugmode, sorry guys.

**Comment by WvTongeren** [comment]
Oh, for a timeframe, this started happening somewhere between 3 and 10 may. 3 may it was still working properly, 10 may it did this. Sorry for the wide window, I just didn't check inbetween.

**Comment by stek29** [comment]
It's wrong place for report :(
Use ask a question button in settings or ping telegram on twitter.

**Comment by Arcaena** [comment]
> It's wrong place for report :(
Use ask a question button in settings or ping telegram on twitter.

That almost never gets responses; I've had problems with the bot API not sending all messages to bots  that hasn't gotten a response there for several days... There's no proper way to disclose telegram api bugs to the devs :<
