### ISSUE TITLE
[Feature Request] Ability to disable previews, stickers, images

### ISSUE THREAD

**Issue by Zenexer** [telegramdesktop/tdesktop#2023]
Group chats end up flooded with previews, stickers, and other messages that consume a lot of space very quickly.  There's currently no option for the receive to disable these potential annoyances.  They're particularly problematic on mobile devices--small ultrabooks, Surface tablets, etc.--where screen real estate is limited.  When one or two group members are in a YouTube mood, conversations become impossible to follow on small screens.

Sure, it's possible for group admins to kick anyone using these features, but that'd be ridiculous: the majority of users like previews and stickers.  But for those of us on small screens, this "spam" quickly becomes intolerable.  Options to disable previews, stickers, and images within the client would solve this problem.

*Please don't comment to say "+1"; use the thumbs up reaction instead.  Click the smile icon on the top-right of this post's header, then choose the thumbs up symbol*

**Comment by aaomidi** [comment]
+1

**Comment by bo0tzz** [comment]
+1

**Comment by dvoris** [comment]
really need. graphical flood is problem

**Comment by psymargo** [comment]
think the stickers are too big for the phone , the optimal size of the average between the current emoticons and stickers . It can be an advantage , if the function is completely turn off the display of stickers

**Comment by Aokromes** [comment]
#687 #1203
