### ISSUE TITLE
Editing messages should leave an indication

### ISSUE THREAD

**Issue by Cassolotl** [telegramdesktop/tdesktop#2024]
Editing messages should leave an indication that a message has been edited. At the moment editing messages is very open to abuse because there is no way to know that a message has been edited.

If this is not the place to suggest Telegram-wide changes, please direct me to the place to make suggestions! Thanks. :)

**Comment by stek29** [comment]
They already have it on mobiles, and TDesktop would have them too (work started on "Moved to Qt5.6" commit)

**Comment by Cassolotl** [comment]
Oooo, so it's on the way? :D I love! Thank you!

**Comment by Cassolotl** [comment]
@stek29 

>They already have it on mobiles, and TDesktop would have them too (work started on "Moved to Qt5.6" commit)

I just tested it on my mobile (Nexus 5, Android 6.0.1, Telegram 3.8.0) and there was no indication that I had edited a message. :S

**Comment by stek29** [comment]
Try plus messenger or wait for update.

**Comment by john-preston** [comment]
Should be done in 0.9.49 stable.
