### ISSUE TITLE
Can one-to-one chats have some supergroup and channel capabilities?

### ISSUE THREAD

**Issue by Cassolotl** [telegramdesktop/tdesktop#2025]
I would really like if we could edit messages and send silent messages in one-to-one chats. I'm aware that it took a lot of work and supergroups and channels work on a very different system, but I wanted to say it anyway because those features are awesome and very useful. :)

I also think that [editing messages should leave some indication](https://github.com/telegramdesktop/tdesktop/issues/2024) that the message has been edited. It's very much open to abuse.

If this is not the place to suggest Telegram-wide changes, please direct me to the place to make suggestions! Thanks. :)

**Comment by stek29** [comment]
Well, according to rumors, it would be available soon.

**Comment by fallerOfFalls** [comment]
Also can groups and supergroups have channel capabilities? i.e. the silent message feature.

**Comment by stek29** [comment]
@fallerOfFalls You should use "Ask a question" button in settings, or ping telegram on twitter

**Comment by Cassolotl** [comment]
Wow awesome. Thank you, I will wait a couple of months and follow up if it doesn't happen. :)

**Comment by fallerOfFalls** [comment]
Maybe this is two (?) separate issues:

* Send muted messages in groups, supergroups, and one-to-one chats (currently only possible in channels)
* edit messages in groups and one-to-one chats (currently only possible in channels and supergroups)

**Comment by fallerOfFalls** [comment]
@stek29 won't they see this thread eventually?
