### ISSUE TITLE
Feature request: Ability to search emoji

### ISSUE THREAD

**Issue by thewhitetulip** [telegramdesktop/tdesktop#2026]
Currently, for emoji you either need to be an expert on their location, or have to patiently scroll through till the bottom. We are missing out on a critical search feature.

**Comment by DaFri-Nochiterov** [comment]
emoticons: ( ͡° ͜ʖ ͡°)
emoji: :cat:

**Comment by thewhitetulip** [comment]
Thanks! @DaFri-Nochiterov

**Comment by stek29** [comment]
IMO #627 would be better.

**Comment by thewhitetulip** [comment]
That'll do
