### ISSUE TITLE
[Bug?] Hashtags are differently parsed for different types of messages

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#2027]
![image](https://cloud.githubusercontent.com/assets/2780044/15270147/7fbb3cc8-1a1d-11e6-8b78-0b7a250b7384.png)

### Steps to reproduce
1. Open channel
2. Write text message with #digit_digit_digit hashtag, e.g. #3_2_1 (Hashtag isn't highlighted)
3. Send image with #digit_digit_digit hashtag. (Hashtag **is** highlighted)

### Expected behaviour
Hashtag should be highlighted in both situations

### Actual behaviour
Only image caption's hashtag is highlighted

### Configuration
**Operating system:** Windows 8.1 x64
**Version of Telegram Desktop:** 0.9.48alpha

**Comment by stek29** [comment]
#1529 Duplicate
