### ISSUE TITLE
[Feature Request] Disable selected notifications

### ISSUE THREAD

**Issue by thekrotek** [telegramdesktop/tdesktop#2028]
Please, add an option to tun off some notifications or only stupid ones, like the one about contacts who joined telegram. This is EXTREMELY annoying, because it's not just a notification, it's a new conversation! I have 3K+ contacts and constantly have to delete such conversations, because I absolutely don't care, who or what joined telegram. Need other notifications though.

In general, more control on notifications would be nice.

**Comment by auchri** [comment]
Duplicate #964 and others
