### ISSUE TITLE
Pressing Esc when replying should cancel the reply instead of closing the chat

### ISSUE THREAD

**Issue by jtojnar** [telegramdesktop/tdesktop#2029]
### Steps to reproduce
1. Right-click a chat message
2. Select Reply
3. Press Escape key
### Expected behaviour

Reply should be cancelled (similarly to when message is edited).
### Actual behaviour

Chat is closed.

**Version of Telegram Desktop:** 0.9.48, it has been like this since I remember.

Related issues: #1500

**Comment by lindhe** [comment]
I'd really not like to see that. I Esc all the time to use Alt+[Down/UP] to move between conversations. I'd hate to have to plug in a mouse just to move between conversations.

**Comment by jtojnar** [comment]
@lindhe You can use <kbd><kbd>Alt</kbd>-(<kbd>Up</kbd>|<kbd>Down</kbd>)</kbd> or <kbd><kbd>Ctrl</kbd>-(<kbd>Shift</kbd>-)?<kbd>Tab</kbd></kbd> even without pressing the <kbd>Escape</kbd> key. Either way, you will still be able to close chat, it will just cancel a reply first, if you started writing one.

Implementing this will enable us to cancel the reply using keyboard only (which is currently impossible AFAIK) and will make the behaviour of the application more consistent.

**Comment by lindhe** [comment]
Ah, you are right! I misremembered. It's getting to the search field that I do using Esc. Any suggestion for that?

(Puh, I can breath out now)

**Comment by jtojnar** [comment]
@lindhe you can jump between the message field and the search field using <kbd>(<kbd>Shift</kbd>-)?<kbd>Tab</kbd></kbd> (or <kbd><kbd>Ctrl<kbd>-<kbd>F</kbd></kbd> if searching the current chat is enough).

**Comment by PandorasFox** [comment]
Can we get this looked into more now?

We have `up` to edit, and `escape` to cancel editing.

We have `ctrl+up/down` for replies, so it makes sense to have `escape` for cancelling replies, too.

(Sure, we can hit `ctrl+down` a bunch to cancel a reply, but if `escape` is being used to cancel stuff, it should _consistently_ be used to cancel stuff).
