### ISSUE TITLE
About dialog on dark desktop theme

### ISSUE THREAD

**Issue by poofeg** [telegramdesktop/tdesktop#2032]
About dialog on dark desktop theme looks like that:
![telegr-dark-theme](https://cloud.githubusercontent.com/assets/586294/15281524/ed4275b8-1b5d-11e6-894d-24699b6fec6b.png)
### Configuration

**Operating system:** Kubuntu 16.04

**Version of Telegram Desktop:** 0.9.49

**Comment by john-preston** [comment]
@poofeg There is no dark desktop theme in telegram desktop yet, only in some forked applications based on it.

**Comment by poofeg** [comment]
I just want to make the text can be read.

**Comment by john-preston** [comment]
@poofeg Well, it can be read in the official version from https://desktop.telegram.org

**Comment by poofeg** [comment]
@john-preston I think we do not understand each other. I'm using official version of Telegram. And I can't read text in about dialog.

**Comment by poofeg** [comment]
@john-preston I think #2033 can fix this issue.

**Comment by z3ntu** [comment]
@poofeg How did you set a "dark mode" in Telegram desktop?

**Comment by poofeg** [comment]
@z3ntu I set it in system, not in Telegram.

**Comment by stek29** [comment]
And did it work? Can you provide some screenshots?
Is About popup the only one with white background?

**Comment by poofeg** [comment]
The only color from system theme is text color in about dialog. All other colors is redefined.
