### ISSUE TITLE
[enhancement] using the camera to send images over Windows client like MacOS version

### ISSUE THREAD

**Issue by ozanyolyapar** [telegramdesktop/tdesktop#2046]
I could not find the function to take a photo using the inserted cam. Until now, I have to take a photo with the camera app, save it and then send it using Telegram.

Please give us the possibility.

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#781
