### ISSUE TITLE
High CPU usage when a group chat has focus

### ISSUE THREAD

**Issue by lindquest** [telegramdesktop/tdesktop#205]
Since the last update, every time I focus on a group chat (any group chat), the CPU usage locks at 25% (which is a full core in a quad-core processor). This happens even when the program is minimized   to the tray. Private and Secret chats are fine, as far as I tested.

I tested on an AMD Phenom II 955 BE, 6 GB RAM, NVIDIA GTX 550 Ti, running Windows 7 x64 and also on a Macbook Air 11" with a Core i5 2467M, 4 GB RAM, Intel HD 3000, Windows 7 x64. And, to discard problems with my account, I asked to a friend to test in his PC (an AMD FX-6300 @ W7 x64, but I think this problem is not related to the CPU model) and he encountered the same problem.

**Comment by auchri** [comment]
Is this still the case? If yes, reopen the issue
