### ISSUE TITLE
Edit text link to post stuck under main chat window

### ISSUE THREAD

**Issue by KonstantinBerkow** [telegramdesktop/tdesktop#2051]
### Steps to reproduce
1.  Open dialog, if there was no messages from you before update write one
2. After sending it tap 'up', now you can edit text
<img width="794" alt="screen shot 2016-05-18 at 5 27 00 pm" src="https://cloud.githubusercontent.com/assets/8669019/15362437/c7133be0-1d1d-11e6-835d-37b1868bf4e5.png">
3. Close link to message
<img width="790" alt="screen shot 2016-05-18 at 5 27 48 pm" src="https://cloud.githubusercontent.com/assets/8669019/15362461/df84a704-1d1d-11e6-8a92-5832deecaffd.png">

### Expected behaviour
Text from link to post cleared

### Actual behaviour
Text from link to post wasn't cleared and there is no way to remove it

### Configuration
**Operating system:**
OS X El Capitan 10.11.5

**Version of Telegram Desktop:**
Version 2.12.46701

**Comment by john-preston** [comment]
@KonstantinBerkow You are using not Telegram Desktop, but another OS X app. You can try Telegram Desktop from here: https://desktop.telegram.org

**Comment by Bullsquid** [comment]
I told you so, Kostya, but you didn't believe me.

**Comment by KonstantinBerkow** [comment]
Oh, my bad. When I tried to install TelegramDesktop there was a conflict so I thought it is same app.
