### ISSUE TITLE
Emojis typed out don't change to image form

### ISSUE THREAD

**Issue by yrahul3910** [telegramdesktop/tdesktop#2054]
**Steps to reproduce**
1. Send an emoji, example :-) from Windows Phone version, to Windows Desktop version
2. Emoji doesn't change as it happens when sent from Desktop version.

**Expected behaviour**
The emoji should change to the image version.

**Actual behaviour**
The emoji remains as ":-)"

**Configuration**
Telegram 0.9.49 on both devices

**Version of Telegram Desktop:**
0.9.49

**Comment by john-preston** [comment]
@yrahul3910 The replacement when sending is done before sending. Sender decides, what exactly does he send — text or emoji. It could be a request for Windows Phone app or other apps.

**Comment by yrahul3910** [comment]
So I should open this issue for the Windows Phone version?

**Comment by john-preston** [comment]
@yrahul3910 Well, you may. But on the phones it is not typical to auto-replace emoji, usually system built-in emoji keyboard is used there for sending emoji.
