### ISSUE TITLE
problem in telegram-sergiusens

### ISSUE THREAD

**Issue by 2020s2020** [telegramdesktop/tdesktop#2059]
I install telegram-sergiusens by snap!
but have a little!! problem
see below pictures:
![snap telegram](https://cloud.githubusercontent.com/assets/10254404/15426331/137daa84-1ea3-11e6-8394-35c279355efa.png)
![tel-snap](https://cloud.githubusercontent.com/assets/10254404/15426349/3fadae1a-1ea3-11e6-806d-c00a7cddd57a.png)

I use ubuntu16.04

**Comment by auchri** [comment]
Please ask the maintainer of this unofficial package for support.
