### ISSUE TITLE
implement --help

### ISSUE THREAD

**Issue by karlsebal** [telegramdesktop/tdesktop#2061]
### Steps to reproduce
1. start Telegram with option --help

### Expected behaviour
some text should be printed on screen, ideally describing usage and options.

### Actual behaviour
telegram just starts up

### Configuration
**Operating system:**
Linux
**Version of Telegram Desktop:**
0.9.49
### Logs
Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#901
