### ISSUE TITLE
Auto edit with Up arrow is bad

### ISSUE THREAD

**Issue by omoridi** [telegramdesktop/tdesktop#2064]
### Steps to reproduce
1.Press Up Arrow key for reading previous messages

When I pressed Up Arrow to reading previous messages automatically show the edit last message. please change the Up Arrow to Ctrl+Up Arrow

Windows 10

**Version of Telegram Desktop:**
0.9.49

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#2012
