### ISSUE TITLE
Telegram leaves a broken shortcut in the Windows Start Menu when run portably

### ISSUE THREAD

**Issue by JohnTHaller** [telegramdesktop/tdesktop#2066]
When run portably (not installed and from a USB drive or cloud drive), Telegram is creating a shortcut to itself in the Windows Start Menu.  This results in a broken shortcut left behind on every computer that Telegram is run on as the user moves on. A shortcut should only be created as part of a standard installer or if the user selects to create a shortcut specifically within the Telegram UI.

**Comment by john-preston** [comment]
@JohnTHaller Currently only with a shortcut the Windows toast notifications can work :(

**Comment by JohnTHaller** [comment]
You could internally track whether the shortcut was there on launch (as well as whether the user selected to create it during that run) and if it didn't exist at launch or was selected to be created during this session, remove it as Telegram exits.  That would ensure the toast notifications work and that a broken shortcut isn't left behind :)

Source: We do this for a couple of packaged apps at PortableApps.com that use the existence of their shortcut and/or the existence of their uninstall entry in Control Panel to determine whether or not they will run without triggering their installer.

**Comment by stek29** [comment]
What about forcing custom notifications for portable app, like on Windows 7.

**Comment by S-ed** [comment]
Why this one is closed? The issue still there, no explanation whatsoever.

**Comment by auchri** [comment]
It's not closed, lop

**Comment by S-ed** [comment]
Oh. My mistake. Messed up with #3057.

So. My issue is very similar. I just want to move the shortcut from the root of the menu.
Toast notifications require Application to have pinned shortcut to Start Screen. But, It could be pinned from anywhere. There's also a shortcut in Startup folder.

**Comment by JohnTHaller** [comment]
I forgot to mention that the Telegram package in PortableApps.com Format was updated last year to automatically remove the shortcut on exit if it was created by Telegram run in portable mode. Telegram still creates it while running to ensure that notifications work. If there was an existing shortcut in the Start Menu for a local copy of Telegram, it is restored as the portable version exits. Note again that this only affects the PortableApps.com package of Telegram, not the standard zip version that will still leave a broken shortcut behind after your removable drive is removed.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by klepp0906** [comment]
yes, just updated.

deleted my hidden shortcut, re-opened.  It was re-created again.

**Comment by klepp0906** [comment]
Was this ever fixed?
