### ISSUE TITLE
Double tick on app vs single tick on Telegram Desktop

### ISSUE THREAD

**Issue by apagano93** [telegramdesktop/tdesktop#2067]
### Steps to reproduce
1. Open chat with a friend
2. Compare ticks of a message with mobile version

### Expected behaviour
I expect to see two ticks on a message which instead is marked with one single tick on the desktop version.

### Actual behaviour
Some messages show one tick on Telegram Desktop instead of two (Android version). What is the correct one?

### Configuration
Ubuntu 15.10

**Version of Telegram Desktop:**
0.9.49

**Comment by stek29** [comment]
#977 ?

**Comment by john-preston** [comment]
@stek29 This should be fixed now (a server-side bug). Please check.
