### ISSUE TITLE
Delete message on all devices (my and companion)

### ISSUE THREAD

**Issue by VladimirBLR** [telegramdesktop/tdesktop#2068]
### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 0.9.49

Hello!

Since editing the message has been added, it is logical to add ability of delete message on all devices (my and companion). You can leave a note **[deleted]** instead of removed message in chat.

**Comment by stek29** [comment]
> You can leave a note [deleted] instead of removed message in chat.

You just solved your own issue

**Comment by menkow** [comment]
Its really basic and logical chatting feature. Isnt it?

**Comment by RNagaev** [comment]
Absolutely agree with @menkow. This feature should not be forgotten or disregarded. it's so difficult to implement?

**Comment by john-preston** [comment]
@RNagaev If you're talking about really deleting the message — it is not difficult but simply impossible to implement without changes to the API (so the discussion simply doesn't belong here).

If you're talking about deleting a text message by editing it, then you can just edit it, without complicating the interface with some new "delete like this / delete like that" buttons.

**Comment by VladimirBLR** [comment]
But, for example, in the Viber it is implemented as two separated menu items:
- Delete
- Delete on all devices

It is clear and not so difficult. May be add the option "Always delete on all devices".

**Comment by john-preston** [comment]
@VladimirBLR Make a button for a feature that does not perform the real action ("Delete on all devices" which does not delete anything, but edits if possible with text "[ deleted ]") is a bad UI idea. You can edit it with "[ deleted ]" text yourself.

You cannot delete a photo or any other media in that way, because editing them only edits the caption text. So the option "always delete on all devices" won't work for media messages which will be even more confusing.

**Comment by RNagaev** [comment]
@john-preston I just want to say that function "Delete" must delete message on both devices. Mine and my contact. And nothing else cant replaced this like alternative function "edit message". I don't want edit my message and wrote something on it.

**Comment by john-preston** [comment]
@RNagaev Then I just want to say that it is useless to write about that here, where an application based on server side API is discussed and ask for features, that are not supported by that server side API.

**Comment by RNagaev** [comment]
So can u help with correct place to ask this question?

**Comment by john-preston** [comment]
@RNagaev «Ask a Question» in the app settings or the official Twitter account at https://twitter.com/telegram I guess..
