### ISSUE TITLE
Up key skips image caption

### ISSUE THREAD

**Issue by Zloool** [telegramdesktop/tdesktop#2073]
Arrow up opens for edit last message, instead of oppening last editable text(like caption for picture)
![2016-05-24_18-40-22](https://cloud.githubusercontent.com/assets/6265787/15510249/564c2ed2-21df-11e6-807e-8a4497c27050.png)
Also, edit caption should be reworked or something?
![2016-05-24_18-45-47](https://cloud.githubusercontent.com/assets/6265787/15510399/c25e44fc-21df-11e6-98dc-62f21193dc01.png)

Telegram PC v 0.9.49 16.05.16

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#2012

**Comment by Kondra007** [comment]
Can confirm on 0.10.8

**Comment by Zloool** [comment]
Fixed as for 1.13.14
