### ISSUE TITLE
[Feature request] Quickly go to chat with bot which sent inline message

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2074]
Look at this screenshot.

![image](https://cloud.githubusercontent.com/assets/2780044/15516887/94360b46-21fd-11e6-8c22-276ca6a312ca.png)

Here you see the inline message sent via `@vote` bot. If I press bot's nick name near "via" word, Telegram will start the bot in inline mode. If I want to view my votes or to close on of them, I need to search for `@vote` in "Search" field and select chat with it.
Okay, but what if bot has nickname like `@ThisIsMyWonderfulLovelyBot` ? I can't even select text with its nickname to paste into Search field.

So, I suggest adding "Open chat with bot" option in context menu when user clicks on inline message from bot.

**Comment by SmartManoj** [comment]
Is there any roadmap for enhancement labels?

**Comment by MasterGroosha** [comment]
Lol, no

**Comment by 23rd** [comment]
Now you can open bot info with `Ctrl` key.
