### ISSUE TITLE
Image thumbnail disappears (inline keyboards, bot message editing)

### ISSUE THREAD

**Issue by jacklul** [telegramdesktop/tdesktop#2075]
**Steps to reproduce**

1. Create a new message with image link in it via @like bot (not photo message!)
2. Post the reaction voting in any group
3. Ask some people to vote
4. Thumbnail will be randomly hidden for users in the group

Post in group: https://i.imgur.com/NDMdNc7.png
After me and several others voted some people reported thumbnail disappearance: https://i.imgur.com/3U8a7F8.png

**Expected behaviour**
Thumbnail stays visible

**Actual behaviour**
Thumbnail disappears, restarting Telegram shows it back

This appears to happen on mobile (Android) too.

**Comment by auchri** [comment]
It would be helpful if you provide some screenshots.

**Comment by jacklul** [comment]
>It would be helpful if you provide some screenshots.

Here you go.
>Post in group: https://i.imgur.com/NDMdNc7.png
>After me and several others voted some people reported thumbnail disappearance: https://i.imgur.com/3U8a7F8.png


In my bot each time it edits the message with image link in it via editMessageText it hides thumb:

1. User XYZ clicks +1 under that message, he still sees the thumbnail but for other members it becomes hidden
2. Another User (which doesnt see the thumb) QWE clicks +1 under that message, XYZ no longer sees the thumb, QWE still doesnt see the thumb

(after button is clicked bot edits whole message using editMessageText, for failsafe it sends disable_web_page_preview=false but it doesnt make any difference)

Restarting Telegram on both users makes the thumb show up again.

**Comment by jacklul** [comment]
It seems like this bug is gone now (at least for Windows desktop and Android, can't say about other platforms)
