### ISSUE TITLE
Emoji buttons are not displayed correctly when previews are small

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#2078]
### Steps to reproduce
1. Use a @like bot and add a small video
2. Use 6 emoji reactions
3. Share a group
### Actual behaviour

As displayed in TDesktop, the emoji buttons are not displayed correctly (@like #fc8c5c6c631c21963)

![tdesktop](https://cloud.githubusercontent.com/assets/5126124/15522185/1cb88550-21e7-11e6-9886-fb4c3308dd95.png)
### Expected behaviour

Emoji buttons are displayed correctly, like Android.

![android](https://cloud.githubusercontent.com/assets/5126124/15522203/3626f5d0-21e7-11e6-81fd-4f366a8b43ff.jpg)
### Configuration

Fedora 23 Workstation 64-bit

**Version of Telegram Desktop:**
Telegram Desktop 0.9.49

**Comment by stek29** [comment]
Wasn't this fixed looong time ago?

**Comment by diazbastian** [comment]
@auchri This continues to happen when the compact mode is used... (v. 1.0.25 alpha)

![captura de pantalla_2017-03-23_16-12-08](https://cloud.githubusercontent.com/assets/5126124/24265788/1b5d6b8e-0fdb-11e7-827d-85a36f6789b0.png)
