### ISSUE TITLE
[Feature Request] Mention all users in group

### ISSUE THREAD

**Issue by toxsedyshev** [telegramdesktop/tdesktop#2081]
### Steps to reproduce
1. Type @channel or @here (like in Slack) or @all in a group chat.

### Expected behaviour
All members of the group are mentioned even if it's muted for them (like many @username mentions).

### Actual behaviour
Nothing happened.

**Comment by DaFri-Nochiterov** [comment]
* `@everyone` - Mention all members of group
* `@here` - Mention only online members

**Comment by Kondra007** [comment]
Downvote it. This will cause "notification spam" in big groups.

**Comment by auchri** [comment]
What happens if someone sets his username to `channel`? :wink:

**Comment by toxsedyshev** [comment]
About "notification spam" and "channel" username - how Slack handle it? :)

How could I send a feature request to api team?

BTW, client could replace "@channel" with all usernames before sending the message, just not to type it by hands. And you could limit a number of users in a group where that feature could be used.

**Comment by stek29** [comment]
@toxsedyshev You can do that on your own: Use "Ask a question" button in settings, or ping telegram at Twitter

**Comment by chris13524** [comment]
I'd like this feature. Especially when there are usually several users that have notifications off.

I noticed that all members are notified when pinning a message. I then thought it would be possible to have a bot pin all messages containing @all, but it doesn't seem bots are capable of doing this...

**Comment by stek29** [comment]
@chris13524 
> there are usually several users that have notifications off

And they have them disabled for a reason :)

**Comment by chris13524** [comment]
@stek29 Well I figured so, but pinning something ignores that setting (they still get notified). You usually pin something when you want to get everybody's attention (like an announcement or something). It only makes sense to do the same for @everyone mentions. The mentioner is trying to get the attention of everyone.

**Comment by stek29** [comment]
@chris13524 It's much easier to write `@everyone` or `@all` then to pin a message. 
You'd have to make more clicks to pin a message, and that's why you'd think twice.

**Comment by ivan0013** [comment]
When I think about pin, I see it more like a very important announcement that has to be keep on view. Using `@everyone` is fast way to put atention on a punctual message

**Comment by john-preston** [comment]
@chris13524 @ivan0013 I'm afraid that won't be added in such a way, because it was tried once (at the very beginning, when mentions were only added) and it worked awful with large groups (there were always some guys using it for fun). Yes, I see the relation with pinned messages, but for now this @everyone feature was disabled for a reason.

**Comment by adioslabs** [comment]
Why not give @everyone feature for admin/group creator alone. I have moved from slack to Telegram with 200+ community members but I miss this feature to notify all about some event we are launching and we have group rules in Pinned Message so can't change it.

**Comment by stek29** [comment]
@adioslabs you can have rules in group description.
It may also have a link to a private channel with rules and related stuff.

**Comment by adioslabs** [comment]
we have a large set of rules and a separate description about our community. How Slack manages this option and why can't we? limit @everyone to be called only by the admins this solves the SPAM problem. When a pinned message also doesn't care about members mute notification option, Why not @everyone should?

**Comment by phraymond** [comment]
Perhaps go with @here instead, where it only send alerts to people actually using Telegram at the time of the message? Or as far as "recently seen" being within, say, an hour?

**Comment by stek29** [comment]
@phraymond Notifying only people who were online recently seems to be a nice feature, at least for pinned messages. I'd recommend you to suggest it by using "Ask a question" button in settings, or on Twitter.

**Comment by nyuszika7h** [comment]
I strongly disagree with the inclusion of a feature like this, but if it's included, at the very least, there should be an option to opt out of these notifications, just like on Discord. It's already bad enough that pinned messages can override the user's notification preferences and it is the *default* option when pinning a message, even though Telegram shows notifications for all pinned messages by default, even those sent without "Notify all members".

**Comment by erikbsap** [comment]
I'm really surprised that this is a feature under discussion. Of course it should be there. And of course one should be able to opt out of being notified.

**Comment by cidwel** [comment]
Yeah, I feel that people would disagree on that just because they think that a opt-out wouldn't exist

**Comment by drreen** [comment]
How about group admins get the possibility to configure permissions to use @all mention:
- Off
- Admins only
- Everyone

**Comment by fliptheweb** [comment]
Find nice bot for that purposes https://github.com/aquibm/everyone-bot
@aquibm Thank you!

**Comment by deeplybrown** [comment]
Hey, @auchri, why was this ticket closed? Just curious. I, too, really want to see this feature implemented on every native version of Telegram.

**Comment by auchri** [comment]
@deeplybrown Because it has to be implemented on the server side.

**Comment by DaFri-Nochiterov** [comment]
@deeplybrown We also have Pinned Message function which does the same what this idea brings (except `@here`)

**Comment by deeplybrown** [comment]
@DaFri-Nochiterov Cool. Does that functionality exist in Telegram for macOS and iOS? Those are the only native apps I use and I don't see the functionality to pin messages in a private group.

**Comment by stek29** [comment]
@deeplybrown you have to be admin and it has to be a supergroup. check group settings.

**Comment by jez9999** [comment]
I like the proposal from @drreen - or maybe just "off" and "admins only".  If admins were allowed to do it, it would greatly reduce the potential for abuse.  And if a user didn't like the way admins were using it, they could just leave the group.

**Comment by mkyukov** [comment]
+1 For this feature request. It can be really useful.

**Comment by mohamadbozorgi** [comment]
> Nothing happened.

**Comment by lhunnelSpiral** [comment]
+1 also, for now i will try to create a work arround

**Comment by MichaelTunnell** [comment]
@auchri :
> @deeplybrown Because it has to be implemented on the server side.

unless it is implemented or your team refuses to do it, you should **not** be closing this because people might only search for open issues.

Since the server is closed source, we obviously cant submit issues to it so at the very least this should stay opened until it is either completed or refused.

**Comment by RememberTheAir** [comment]
> you should not be closing this because people might only search for open issues

Well, people should also search for closed issues. Issues like these should be closed and labeled as API issue because they are considered refused for this client, since things like these are not going to be implemented client-side only (you can consider them as refused for tdesktop). There is no issue tracker for the server code because platform-wise implementations are decided by Telegram itself and new features and stuff are not community driven, although Telegram accepts suggestions on Twitter and through the in-app support. So yes closing these issues and cotrrectly labeling them is the most explicit thing that can be done because there isn't going to be any work on that from tdesktop's dev

**Comment by LunarWhisper** [comment]
> There is no issue tracker for the server code because platform-wise implementations are decided by Telegram itself and new features and stuff are not community driven, although Telegram accepts suggestions on Twitter and through the in-app support.

This is counterintuitive. :(

**Comment by AlexanderKositsyn** [comment]
But when API will be improved, this issue will be useful for creating mentioned feature.

**Comment by banderlog** [comment]
The https://github.com/everyone-bot/everyone-bot is a bad substitution for `@all`
