### ISSUE TITLE
Availability Options

### ISSUE THREAD

**Issue by inexuscore** [telegramdesktop/tdesktop#2082]
It would be great if Telegram supported availability options.
Something like Skype: Available, Away, Busy, etc.

Also, why not go one step further and enable us to go invisible? remember Yahoo Messenger, that was great.

Thanks y'all!

**Comment by stek29** [comment]
That's all API issues, except invisible.

Invisible is already partially available: you can hide your "last seen" status. 
But you can't be fully invisible unless you don't send any message.
