### ISSUE TITLE
Deep linking

### ISSUE THREAD

**Issue by aryanbaghi** [telegramdesktop/tdesktop#2083]
### Steps to reproduce
1.Add Bot with deep linking, example: https://telegram.me/botname?start=someparameter
2.start bot with link

### Expected behaviour
When I use other telegram bot I receive paramter I sent bot when use this client I could not receive the parameter.

### Actual behaviour
I could not receive parameter on bot side. Only receive /start

### Configuration
**Operating system:**

**Version of Telegram Desktop:**
0.9.49

**Comment by john-preston** [comment]
@aryanbaghi What characters do you use in the parameter? Are you sure you do not get such simple values like "someparameter"? Note that docs specifically forbid any characters except [a-zA-Z0-9_-] (see https://core.telegram.org/bots#deep-linking)

**Comment by aryanbaghi** [comment]
This is exact parameter I tested:
Z2l2ZV9tZV9iaWxsOjU3MjQ3MWJmODU3YzExNTFjZWZlYjhlMA%3D%3D

**Comment by stek29** [comment]
@aryanbaghi Isn't `%` forbidden?

**Comment by aryanbaghi** [comment]
@stek29 According to doc yes, bot all other client support it because when encode parameter with base64 `=` make url messy and some developer replace it with `%3D`

**Comment by john-preston** [comment]
@aryanbaghi '=' character is not allowed by the docs as well, only '-' and '_'.

You are suggested to use base64url, not base64, which uses '-' and '_', without pad character '='.

Telegram Desktop allows only the characters that are allowed by docs.
