### ISSUE TITLE
[Feature Request] Chat Backups

### ISSUE THREAD

**Issue by leleckso** [telegramdesktop/tdesktop#2084]
### Steps to reproduce
1. You have a chat you want to backup, just in case

### Expected behaviour
I click a button, Telegram does some magic and I get a chat log. ..something like that.

### Actual behaviour
I have to select every single message and copy it through Telegram Web.. since you can't even select more than 100 messages in the Desktop version.

I know, Telegram stores everything in the cloud and all.. but you never know nowadays. I don't feel like losing some 20,000 messages with people, and I don't feel like selecting them all just to copy them either.

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#126
