### ISSUE TITLE
Windows client not handling change of playback device

### ISSUE THREAD

**Issue by Zloool** [telegramdesktop/tdesktop#2085]
Telegram continues to use prefered playback device from the time of its startup, not the actual one.
### Steps to reproduce
1. Turn on Telegram
2. Start playing some audio track
3. Plug in new playback device

### Expected behaviour
Expected to use the new device, as it`s marked as primary in winows.
![photo_2016-05-26_00-48-33](https://cloud.githubusercontent.com/assets/6265787/15557432/9c850a48-22db-11e6-8f18-42fa9e80d323.jpg)

### Actual behaviour
Instead, Telegram will continue to use the old one
![photo_2016-05-26_00-45-23](https://cloud.githubusercontent.com/assets/6265787/15557359/28d89326-22db-11e6-9a0c-93fe537f9619.jpg)

### Configuration
Windows 10 

Telegram v 0.9.49 16.05.16

**Comment by Kondra007** [comment]
Duplicate #418
