### ISSUE TITLE
Changing screen makes the image viewer behave improperly

### ISSUE THREAD

**Issue by DarthJahus** [telegramdesktop/tdesktop#2087]
This happens when we plug a new screen, unplug a screen, or just move the client from a screen to another.

The image viewer doesn't fit, and going to next or previous image either make it remain on a same image, or show images from other chats, channels, sometimes very old images.

System: Windows 10 x64 (noticed the bug on all builds since 10240 to 14342).
Actual Telegram version: 0.9.49 (noticed the bug on all versions until now).

**Comment by 123RaZoR321** [comment]
Somewhat similar experience happens when you try to rotate the screen on a tablet. The image viewer doesn't rescale.

**Comment by Torvin** [comment]
Same happens when I connect via RDP with a different screen resolution. Very annoying. Please fix!

**Comment by Torvin** [comment]
Same issue as #1838

**Comment by Torvin** [comment]
same as #1542
