### ISSUE TITLE
Problem with maximizing the window in high resolution

### ISSUE THREAD

**Issue by 6d696c** [telegramdesktop/tdesktop#2089]
### Actual behavior
Maximizing the telegram's window in high resolution, puts my dialogs and others in one side (left side)

![1](https://cloud.githubusercontent.com/assets/10987736/15582936/b5f553c2-2388-11e6-8e19-5a2effaf01d7.png)
![2](https://cloud.githubusercontent.com/assets/10987736/15582937/b5f5fce6-2388-11e6-907c-2cd47f79cb42.png)

### Expected behavior
I expect changing resolution, do not change dialog style (my posts in right and others in left)

### Configuration
I'm using telegram desktop in Windows 10 (Version 1511 - OS Build 10586.318) Pro with resolution 2736x1824.

Telegram Version: v 0.9.49

**Comment by stek29** [comment]
Check settings, there are an option for this.
