### ISSUE TITLE
Are there any rules about which feature will enter to tdesktop?

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#2090]
Are the features derived from what's inside telegram mobile, or by the road map of telegram's core developers? Or they are independent and decided as per this project?
What I mean - if someone will introduce a new feature via a pull request (like categorized chats / tabs / favorites / archive / etc.), will it be considered as the value and road map for `tdesktop` and how you the owners of the project sees the development, or by telegram's core team road map?

Thanks,
Ariel

**Comment by stek29** [comment]
[Feature philosophy](https://core.telegram.org/tsi/feature_philosophy) maybe?

**Comment by arieljannai** [comment]
@stek29 Thanks, I saw it. It just wasn't clear for me if it's on all official telegram services (e.g. including tdesktop).
And what are the rules if someone propose a pull request for a feature wasn't planned? Means that some features might be only on that specific telegram app

**Comment by john-preston** [comment]
@arieljannai Generally only bug fix pull requests are accepted, see the contribution policy.

**Comment by john-preston** [comment]
@arieljannai Exceptions may occur, but they are rare.
