### ISSUE TITLE
Problems with applying qt patch

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#2091]
### Steps to reproduce
1. Follow instructions at the section [Qt 5.6.0, slightly patched](https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-msvc.md#qt-560-slightly-patched) from [building-msvc.md](../blob/master/doc/building-msvc.md)
2. Arrive to [Apply the patch](https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-msvc.md#apply-the-patch)
3. Run the `git apply` command

### Expected behaviour
Patch applied

### Actual behaviour
Applying patch failed - `fatal: corrupt patch at `[`line 85`](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/Patches/qtbase_5_6_0.diff#L85)

### Configuration
**Windows 10 x64:**

I tried figure out whats wrong with the patch, but it seems just fine.
Any idea? someone else have experienced that?

**Comment by john-preston** [comment]
@arieljannai Something with the line endings I guess. I was taking the patch in Windows, so git converts the line endings somehow.

You can try this: in Git Bash (http://git-scm.com/downloads) go to the patch directory (TBuild/tdesktop/Telegram/Patches) and run:

perl -pi.bak~ -e 's/\\r\\n/\\n/g' qtbase_5_6_0.diff

**Comment by arieljannai** [comment]
Thanks!
It really was the crlf
