### ISSUE TITLE
Build client on the platform libui

### ISSUE THREAD

**Issue by gargullia** [telegramdesktop/tdesktop#2093]
I would like to see the client rewritten with the help of this library https://github.com/andlabs/libui
The advantages that the customer will have a native form in different systems.

**Comment by john-preston** [comment]
@gargullia I'm afraid it is easier to write a new app :)

**Comment by igor-dyatlov** [comment]
@john-preston Who are some of the telegrams team will undertake the work? If yes, then Durov support the initiative?

**Comment by john-preston** [comment]
@igor-dyatlov I'm afraid third-party developers will have to do this, no team inside Telegram for that.
