### ISSUE TITLE
Reply keyboard button clicks send normal messages

### ISSUE THREAD

**Issue by ttsda** [telegramdesktop/tdesktop#2099]
### Steps to reproduce
1. use a bot that has reply keyboards like @pollbot
2. click an option

### Expected behaviour
the option text should be sent as a reply to the bots' message as stated in the bot api documentation

### Actual behaviour
the message is sent normally, not as a reply

### Configuration
**Operating system:** mac os

**Version of Telegram Desktop:** 0.9.49

**Comment by john-preston** [comment]
@ttsda Yes, this is a bug in the latest version :( will be fixed in the next one.
