### ISSUE TITLE
Telegram Desktop on Windows 10: Empty contact name when contact was added

### ISSUE THREAD

**Issue by lospejos** [telegramdesktop/tdesktop#2100]
### Steps to reproduce
1. Unfortunately, I cannot reproduce exact steps to reproduce an error. I didn't noted what is the exact cause of this. I suppose steps:
2. Have some nonsaved contacts in calls history  
3. Have one of this unsaved contact register to Telegram
### Expected behaviour

Phone number is displayed as contact name when there is no contact name.
### Actual behaviour

Empty string displayed as contact name. Phone number displayed correctly.
### Configuration

**Operating system:**
Microsoft Windows [Version 10.0.10586] x86_64
**Version of Telegram Desktop:**
0.9.49
### Logs

Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

**Comment by lospejos** [comment]
![image](https://cloud.githubusercontent.com/assets/4608475/15642458/2aefcc4c-2650-11e6-99a9-d8c89009b309.png)
Screenshot displaying this behaviour is attached.

**Comment by auchri** [comment]
What is displayed in some other app? (e.g. in the Android app)

**Comment by stek29** [comment]
Can you please use "Copy name" option and paste name here?
I doubt he has empty name, it should be some unicode magic.

**Comment by lospejos** [comment]
In Android App it displays contact phone number, as I expected (when contact has no displayable name, display it's phone number). 
I've copied contact name, but clipboard is empty (cannot paste into command line, utf-8 aware editor etc).
Android app somehow recognized that contact has no displayable name and displayed phone number.

**Comment by john-preston** [comment]
@lospejos There should not be a contact without a name :( displaying phone number currently may confuse some users, because we display a phone number instead of a name for those your conversations, that are NOT in your contacts list.

**Comment by lospejos** [comment]
Well, I've done some deeper research:
1) This contact (that has empty name in my Telegram Dekstop) is recorded in my phone address book. It has only Cyrillic symbols in it's name, but I have plenty of contacts with cyrillic only names that are correctly displayed in my Telegram Desktop.
2) I have 3 contacts in my phone address book with names "(unknown)" (but written in cyrillic - russian is my primary phone language - exactly it is "(неизвестно)") without a phone number.

**Comment by lospejos** [comment]
I exported contacts to CSV, and found no differences between those contact that has cyrillic only names and that names displayed in Telegram Desktop correctly and those that has cyrillic only names and has no display name in Telegram Desktop. Both have CHARSET=UTF-8 and displayed correctly in my utf-8 aware edlitor.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
