### ISSUE TITLE
Crash when resizing desktop with the presence of resizable ReplyKeyboardMarkup in chat with Bot

### ISSUE THREAD

**Issue by halaei** [telegramdesktop/tdesktop#2101]
### Steps to reproduce
1. Find a bot that sends you back a message with ReplyKeyboardMarkup having 5 keys in the first row, each with a couple of emojies. The keyboard must have true in its `resize_keyboard` (refere to the bot API). 
2. Resize the desktop window: shrink the width until the desktop client crashes.

### Expected behaviour
Nothing

### Actual behaviour
Crash

### Configuration
**Operating system:**
Ubuntu 14.04
**Version of Telegram Desktop:**
0.9.49

**Comment by john-preston** [comment]
Do you have an example of such bot?

**Comment by halaei** [comment]
send /reproduce command to @toolkitbot

**Comment by zumoshi** [comment]
tested with telegram v0.9.49 on windows 8.1 x64. it crashed...

**Comment by john-preston** [comment]
@zumoshi Thanks for your report! This will be fixed in the upcoming version, I hope it will be this week.

**Comment by halaei** [comment]
In which version is it going to fixed? Not fixed in 0.9.51
@auchri

**Comment by john-preston** [comment]
=(

**Comment by halaei** [comment]
No milestone :cry: ?

**Comment by john-preston** [comment]
There is of course, next version :) I was disappointed that I didn't fix it in that one, I was sure it was fine there, but looks like I've missed something.

**Comment by halaei** [comment]
:)

**Comment by john-preston** [comment]
This one should be fixed in 0.9.52 alpha (but there is one other crash with bot keyboard :)

**Comment by halaei** [comment]
Is it possible to link issues to the related commits? If it is not a
security concern, it can increase the chance of contribution. Not that I am
currently a C/C++ programmer, but generally it may help.

**Comment by auchri** [comment]
@halaei 

https://github.com/telegramdesktop/tdesktop/commit/963000386fdcd5b94dc6523501235aa5d5df12ae :)

**Comment by halaei** [comment]
😏🇨🇲
