### ISSUE TITLE
Displaying message edit history

### ISSUE THREAD

**Issue by lindhe** [telegramdesktop/tdesktop#2102]
Sorry if this has been posted before. I did a search and couldn't find any obvious issue on it before. It's also quite a bad one, so I think it needs fixing.

### Expected behaviour
When editing messages, the entire edit history should be available to all that can see the message. Otherwise this could lead to some quite unfortunate situation where someone writes something bad, and is accused for it but nothing can be proven.

### Actual behaviour
There is a small text (only on mobile as far as I can tell) notifying that it has been edited, but not what it said before.

### Configuration
All platforms, but I'm running it on Arch Linux and on Android phone.

**Comment by john-preston** [comment]
@lindhe API only returns the flag that message was edited and the date of last edit. This info is available from Telegram Desktop.

**Comment by dehghani-mehdi** [comment]
@john-preston it's NOT available even in desktop app. is it available for you? if so, please share the download link.

**Comment by stek29** [comment]
@dehghani-mehdi it's shown on hover on "edited"

**Comment by dehghani-mehdi** [comment]
@stek29 on hover over on `edited`, popup shown & only show the details about edited date. not access to message(s) history. in other word, we can not see the prev. message(s) & this is the reported issue here.

**Comment by john-preston** [comment]
@dehghani-mehdi you replied to my message, where I said about what is available from API and THAT information is available in Telegram Desktop. Please read my previous message (the one you replied to) carefully.

**Comment by dehghani-mehdi** [comment]
@john-preston you right. my bad. but I didn't get why before fixing the issue, the issue was closed. (of course I say this to the whole team, not just you)

**Comment by john-preston** [comment]
@dehghani-mehdi Because this whole repository is just for me, not for the whole team and this issue does not belong here, in the Telegram Desktop repository.

**Comment by stek29** [comment]
@john-preston 
>Because this whole repository is just for me  

XD
For TDesktop or for **you**?
