### ISSUE TITLE
Scrolling history backwards causes TD hangs after loading some number of messages

### ISSUE THREAD

**Issue by adrianopol** [telegramdesktop/tdesktop#2103]
### Steps to reproduce
1. Open any chat with large history (over ~1700 messages).
2. Keep pressing `PageUp` key.
3. After loading ~1500 messages, scrolling stops for a few tens of seconds before loading earlier ones. This happens again and again for each portion of messages.

### Expected behaviour
TD should not stop when browsing history.

### Configuration
**Operating system:** Gentoo GNU/Linux.
**Version of Telegram Desktop:** telegram-desktop-0.9.49 (built from https://github.com/gavv/gv-overlay/tree/master/net-im/telegram-desktop).

P.S.: Moreover, history is not loaded without Internet connection. Should I post a separate bug about it? Or it is a feature and it won't be fixed?

**Comment by john-preston** [comment]
@adrianopol It works like browser, without storing the history on your hard drive, so I guess no way to load history without internet connection right now.

About the hanging — we can see logs, but I'm pretty sure it is a server side flood control. Please try the official client from desktop.telegram.org (it can have different API call limits on the server-side), perhaps it will work better.. perhaps not.. anyway, I can't do anything about the limits right now.

**Comment by adrianopol** [comment]
I understand, thank you.
