### ISSUE TITLE
[Feature-request] Notification on message with hashtag from custom userlist

### ISSUE THREAD

**Issue by YaakovTooth** [telegramdesktop/tdesktop#2104]
1. The user create custom hashtag list. Manually in the settings or from other people's messages.
2. If hashtag from user list used in all channels and chat rooms user is notified.

**Comment by FranklinWhale** [comment]
This feature will be especially helpful to channel members (the user) because the user may not be interested in all messages in the channel but some with specific hashtags. I do want to see this implemented.

**Comment by stek29** [comment]
I think this issue may be closed too, just like zhukov/webogram#1299.
