### ISSUE TITLE
cut/copy and paste is broken

### ISSUE THREAD

**Issue by ousado** [telegramdesktop/tdesktop#2107]
### Steps to reproduce
1. type a message in a chat window
2. select (some of) what you've typed with e.g. Ctrl+A
3. cut it with ctrl+X or copy with ctrl+C
4. paste it with ctrl+V

### Expected behaviour
Tell us what should happen
the typed and cut /copied text should be inserted (again)

### Actual behaviour
Tell us what happens instead
whatever was in the clipboard before is pasted instead - the text that has been cut/copied in step 3. is lost.

Using the context menu for above actions yields the same results.
This is a regression, I think it broke when editable messages were introduced.

### Configuration
**Operating system:**
Linux, Debian Jessie, X86_64, Gnome Version 3.14.1

**Version of Telegram Desktop:**
0.9.49

**Comment by stek29** [comment]
So paste works properly, but copy/cut doesn't?

**Comment by ousado** [comment]
@stek29 probably

**Comment by ousado** [comment]
seems fixed after update to 0.9.50
