### ISSUE TITLE
Compose Key not working on Ubuntu

### ISSUE THREAD

**Issue by MaxNoe** [telegramdesktop/tdesktop#2112]
### Steps to reproduce
1. Use Telegram on Ubuntu
2. Set Keyboardsettings to use a Compose Key
3. Type `<compose> - >`
### Expected behaviour

A nice unicode arrow: `→`
### Actual behaviour

The compose key press seems not to be registered
So just `->` 
### Configuration

**Operating system:**
XUbuntu 16.04

**Version of Telegram Desktop:**
0.9.49

**Comment by Rom4nB** [comment]
Same behaviour here.

**Operating System**
Ubuntu 16.04 64-bit

**Telegram Desktop Version**
0.9.49

**Comment by evenfrost** [comment]
Same on Ubuntu 16.04.

**Comment by angelog** [comment]
Still an issue here. Instead of it showing © for example, it's just like I typed "oc" (`<compose> o c`)

**Comment by MaxNoe** [comment]
This might be related: https://ubuntuforums.org/showthread.php?t=2010785

**Comment by MaxNoe** [comment]
I had to install `sudo apt instal libqt5gui5 ibus` and do `export QT_IM_MODULE="xim"`. Now it works.

**Comment by MaxNoe** [comment]
Closing because it's a general QT problem, not a Telegram problem
