### ISSUE TITLE
Space key bug

### ISSUE THREAD

**Issue by Artem7virus** [telegramdesktop/tdesktop#2113]
### Steps to reproduce
1. Win7
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

### Logs
Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

People, noticed that when you press the space bar to enter the field he called is displayed, if the cursor is at the far right edge of the field.

**Comment by auchri** [comment]
Can you attach an screenshot or something? I don't understand your description.

**Comment by gvozdyov** [comment]
Steps to reproduce

**Comment by Artem7virus** [comment]
Check  the input place, please. 
If u type any string, and right symbol matched with border of type place - spases not shown, and does not move sursor

**Comment by Artem7virus** [comment]
![image](https://cloud.githubusercontent.com/assets/17015176/15791794/205fdcfa-29e2-11e6-8e31-b515b621cb28.png)
After string 15 spases

**Comment by Artem7virus** [comment]
but cursor on the qurent line

**Comment by john-preston** [comment]
@Artem7virus This is the way Qt text input field works. It is a common way, for example Safari web browser input fields on OS X work the same way.

**Comment by Artem7virus** [comment]
I just reported on incorrect application. In any case, I am a developer ))
