### ISSUE TITLE
Receive message when bot is mentioned

### ISSUE THREAD

**Issue by Frederick888** [telegramdesktop/tdesktop#2117]
### Steps to reproduce
1. Open a group chat
2. Send  `@bot_name whatever`

### Expected behaviour
Bot can get the message despite the privacy mode.

I think users definitely want the bot to see their messages when they mention the bot.

I'm adding some functions to my bot which are apparently different from commands. I have something like `@bot_name tell me who you are` or `@bot_name give me a quiz` and I can only do this by turning privacy mode off currently. They can be implemented by Commands but then the command list would be extreme long.

Would you please consider delivering the messages where the bot is mentioned? I think this can make bots more powerful

**Comment by z3ntu** [comment]
I am pretty sure, that this is not a bug/whatever of Telegram **Desktop** but of Telegram generally, where this is the wrong place.

**Comment by john-preston** [comment]
@z3ntu In the docs it is meant to work that way.

**Comment by z3ntu** [comment]
I meant, that this is definitely not a Telegram Desktop bug, but more likely a feature/bug/behaviour of Telegram itself.

**Comment by Frederick888** [comment]
@z3ntu I know this is a feature request rather than a bug report.
Sorry but where can I send the feature requests?

**Comment by stek29** [comment]
@Frederick888 Look for "Ask a question" in settings, or reply telegram in twitter

**Comment by Frederick888** [comment]
@stek29 Thanks a lot, I'll close the issue and send the request by Twitter.
