### ISSUE TITLE
[bug] Bold not working

### ISSUE THREAD

**Issue by bliz937** [telegramdesktop/tdesktop#2128]
### Steps to reproduce
1. Get a message with bold markup from a bot (ex, bold)
### Expected behaviour

Bold message.
![image](https://cloud.githubusercontent.com/assets/4072820/15930609/23007a52-2e54-11e6-9aa9-ecd2bccf3f38.png)
### Actual behaviour

No bold words. 
Italics works, however.

![image](https://cloud.githubusercontent.com/assets/4072820/15930575/f5f4e516-2e53-11e6-8c74-5cd1a82cf332.png)
### Configuration

**Operating system:**
Linux (Antergos)
Windows 10
**Version of Telegram Desktop:**
0.9.49
#1917 Appears to have a similar issue.

**Comment by bliz937** [comment]
Works on Linux client *0.9.42*

**Comment by zumoshi** [comment]
displays correctly in windows 8.1, v0.9.49

**Comment by vozzurg** [comment]
windows 10, tdesktop 0.9.49 alpha
![screenshot_978](https://cloud.githubusercontent.com/assets/14953243/15960625/26993d18-2f1a-11e6-83ec-c6653553e474.png)

**Comment by stek29** [comment]
@vozzurg @zumoshi I'm sure it's only Linux problem, because it works on OS X too.

**Comment by zumoshi** [comment]
maybe he has some custom font or accessibility feature that affects the way it is displayed.
you can see in the screenshot that `via @bold` is also displayed differently from @vozzurg's image

@stek29 he listed windows 10 as an operating system also , i wouldn't have reported if only linux was listed.

**Comment by john-preston** [comment]
@stek29 I think some of the distros doesn't load my "Open Sans Semibold" font, I had to patch Qt in OS X / Ubuntu to make it work. But perhaps it uses some different font database plugin :(

**Comment by john-preston** [comment]
It does work on 0.9.42? Are you sure? Qt version has changed from 0.9.42 to 0.9.49 from 5.5.1 to 5.6.0, perhaps some of my patches were forgotten or stopped working there :(

**Comment by bliz937** [comment]
@john-preston I have [5.6.0-7 installed](https://www.archlinux.org/packages/extra/x86_64/qt5-base/).

**0.9.42** is on a Debian machine.

**Comment by EhsaanF** [comment]
No bold texts at all (elementary 0.3.2).
v0.9.49

Also Persian/Arabic texts don't get bold on Windows client (same version).

**Comment by stek29** [comment]
Some guy (@vozzurg) said that installing Infinality broke bold for him too.
Uninstalling didn't help.

**Comment by EhsaanF** [comment]
Updated to v0.9.51

Bold still not working at all (elementary 0.3.2 based on Ubuntu 15.04)

**Comment by EhsaanF** [comment]
These are the errors and warnings I get when launching on terminal:
```
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

** (Telegram:3840): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-5iyDBewLxp: Connection refused
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
```

**Comment by bliz937** [comment]
Telegram desktop version **0.9.56** appears to still have this issue.

**Comment by TiagoDanin** [comment]
Same problem. I don't have this error on Linux (Deepin 15.1 and Ubuntu14.02), only on Windows
**Operating system:** Windows 10
**Version of Telegram Desktop:** 0.9.56
**Images:**
![image](https://cloud.githubusercontent.com/assets/5731176/17297017/2a1d3e88-57da-11e6-99ab-503a0c078ebc.png)
Web
![image](https://cloud.githubusercontent.com/assets/5731176/17297047/56fd54ce-57da-11e6-8336-69b7dbdceaf7.png)
Desktop

**Comment by bliz937** [comment]
Issue still exists in **0.10.1**.

**Comment by Darkhogg** [comment]
This is still an issue for me in 1.0.6, Linux.  Is there a particular font or family of fonts I should install to make it work?

**Comment by neesti** [comment]
Persian texts don't get bold on Linux and Windows client. (Version 1.0.13)

**Comment by jh0ker** [comment]
I have the same issue on Fedora 25. Is there anything we can do to help figure out the problem?

**Comment by EhsaanF** [comment]
This problem is still here on elementary 0.4.1 based on Ubuntu 16.04.

**Comment by devsware** [comment]
I confirm that Linux version (on Mint 18.1) even after the last update doesn't show bold text (neither the text I send nor the text I receive).
The two asterisks before and after the words are not shown but no bold text appears.

Italic instead works as expected.

**Comment by JosXa** [comment]
1.1.19 alpha on Arch Linux. Bold text has never been visible in any of the previous versions for me.

**Comment by Aokromes** [comment]
#1917 generic bug?

**Comment by othiman** [comment]
Hi,
we had the same problem on some of our CentOS 7 system and removing the open-sans-fonts package withyum remove open-sans-fonts

**Comment by GreenRobot777** [comment]
I had the same problem on **Telegram 1.1.23** and
```
Elementary OS 0.4.1 Loki
Based on "Ubuntu 16.04.3 LTS"
Linux 4.10.0-37-generic
GTK+ 3.18.9
```
and removing the open-sans-fonts package with
`sudo apt remove fonts-open-sans-elementary`
solved the problem for us.

**Comment by devsware** [comment]
So it seems to be a font related problem and not something about the asterisks not being interpreted.

On Linux Mint 18.2 there's no fonts-open-sans-elementary package, so the tipical Linux Mint user should check (by trial and error, with just a hint that it's not a serif/handwritten one) which font is actually used to display text and then uninstall it from the system, hoping that the "next one" automatically chosen can correctly display bold text.

Maybe adding the possibility to choose the font among the ones installed on the system could be more user friendly that finding the "offending font" and uninstall it from the system completely.

If is not too complex to implement maybe that could be the easiest solution for the user.

As an example:  in my office some employees use Telegram Desktop to communicate with the customers and I doubt that any of them is able to understand the concept of "uninstalling a font from the PC" (and yes... there is an IT dept, but uninstalling a system font on many PCs is not practical), while "choosing a font" from (let's say) a select inside "Settings" could be easier to understand.

**Comment by auchri** [comment]
@devsware #90

**Comment by Lonami** [comment]
Same here, bold isn't shown on my Arch Linux installation but it is for a friend (using Arch Linux too). Not sure which font can be causing the issue but doesn't seem to be a Telegram Desktop issue.

**Comment by diazbastian** [comment]
I have had this problem for some time and I solved it by uninstalling the Open Sans font (`open-sans-fonts`) from my system and magically now Telegram shows bold text correctly.

Tested on:
fedora 26 & 27 Workstation (GNOME)
Telegram 1.1.23

![opensans-bold-tdesktop](https://user-images.githubusercontent.com/5126124/32978725-a1ef593e-cc26-11e7-84f4-41e3406beb4d.png)

**Comment by NickLion** [comment]
Telegram 1.2.6 and still no bold text. Removing Open Sans isn't a solution. Why all other Qt apps in my KDE has no problem with bold text and Telegram does? Why it uses patched Qt anyway? If that's a good patches maybe it's better to push them upstream.

**Comment by whoozle** [comment]
Putting my twopence worth, it's not likely relevant to asterisk parsing, because I'm using HTML markup in my bot(<b>/</b>), and it's failing to display bold as well.

**Comment by marcogiannini** [comment]
the bug is still present on elementary OS 5.0 Juno

**Comment by igrmk** [comment]
Following helps in Ubuntu

`sudo apt remove fonts-open-sans`

**Comment by marcogiannini** [comment]
Removing the font is not a good solution, also because that font is the default font of the distro

**Comment by infoman** [comment]
This started happening to me in 1.8.3 and 1.8.4

**Comment by BARTlab** [comment]
Make new folder for telegram fonts:
```bash
mkdir  ~/.fonts_telegram
```

Copy all system fonts to new folder:
```bash
cp -r  /usr/share/fonts/* ~/.fonts_telegram
```

Remove open-sans font from new folder:
```bash
rm -rf ~/.fonts_telegram/truetype/open-sans/
```

Open telegram config in text editor (need root rights)
```bash
sudo nano ~/.local/share/TelegramDesktop/tdata/fc-custom-1.conf
```

and replace row
```
<dir>/usr/share/fonts</dir>
```
to
```
<dir>~/.fonts_telegram</dir>
```

Restart telegram app. First start may take 3-5 minutes

**Comment by Lonami** [comment]
In addition to @BARTlab's comment, if you don't have `fc-custom-1.conf`, you can right click in [`fc-custom.conf`](https://github.com/telegramdesktop/tdesktop/raw/2cadabd60cb04c17c4e83468e3346720c760495a/Telegram/Resources/fc-custom.conf) and "Save Link As…". Here's the relevant code making use of that file:
https://github.com/telegramdesktop/tdesktop/blob/1e5aa2a78d0a0ba06d95c63e746d7b795fe838b8/Telegram/SourceFiles/platform/linux/specific_linux.cpp#L53

**Comment by JayXT** [comment]
@BARTlab, @Lonami, your suggestions worked, thanks.
However, removing Open-Sans from custom folder may introduce a different issue for some users. In elementary OS Hera (probably other versions as well) a file selection dialog will have broken fonts as on the attached screenshot when attaching files from Telegram.
![Screenshot from 2019-12-22 10-29-33](https://user-images.githubusercontent.com/8045344/71319378-4b04d380-24a6-11ea-9e5f-20ef29a4283d.png)

**Comment by Lonami** [comment]
Yes, I noticed. And if I open a link with the web browser not open beforehand, it will open also with the custom fonts and it may look broken.

**Comment by JayXT** [comment]
Current temporary resolution could be changing system font to something different like Noto Sans using Elementary Tweaks or other utility/configuration files (depending on the distro), but of course it doesn't solve the root-cause, namely certain bug in Telegram Desktop.

**Comment by NabiKAZ** [comment]
After 4 years:
Telegram Desktop 1.9.3
![rY9hKKuO5o](https://user-images.githubusercontent.com/246721/72153574-9cc4bd80-33c3-11ea-92ba-c9aaf2ecc2e5.gif)

**Comment by JayXT** [comment]
Indeed, the latest Telegram Desktop version (1.9.3) has this issue fixed. Just removed custom fonts folder and fc-custom-1.conf, relaunched Telegram and can see now that the bold text is displayed correctly. Can anyone else confirm this?

**Comment by devsware** [comment]
Finally working with Telegram Desktop (1.9.3) on Linux Mint 18.1

**Comment by NabiKAZ** [comment]
@JayXT 
I use persian language in windows.
I can not find "fc-custom-1.conf" file or custom font folder..

**Comment by JayXT** [comment]
@NabiKAZ, I also didn't have one. To support custom fonts from your own folder it's needed to create this file by following the [suggestion](https://github.com/telegramdesktop/tdesktop/issues/2128#issuecomment-540052176) by @Lonami. So in general if you have font issues you should stick to these steps:
1) https://github.com/telegramdesktop/tdesktop/issues/2128#issuecomment-540004365
2) https://github.com/telegramdesktop/tdesktop/issues/2128#issuecomment-540052176

**Comment by Aokromes** [comment]
@devsware so this can be closed? cc @NabiKAZ @JayXT be sure you use 1.9.9 from desktop.telegram.org and not 1.8.15 or lower from some linux distribution package.

**Comment by devsware** [comment]
@Aokromes as far as I'm concerned it can be closed.
I've tested version 1.9.9 on various releases of Linux Mint (from 18.1 to 19.3) and bold is working everywhere now.

**Comment by arieljannai** [comment]
[Still not working with Hebrew](https://github.com/telegramdesktop/tdesktop/issues/4445):

TDesktop 2.0.1 beta

![image](https://user-images.githubusercontent.com/3811594/78988316-4b020f80-7b39-11ea-82f1-ff960e27ebfd.png)
