### ISSUE TITLE
Incomplete feature: @username and groups

### ISSUE THREAD

**Issue by MarcosBL** [telegramdesktop/tdesktop#213]
There seems to be no way of adding an @username to a group, even if I'm in a chat with a @username I can't find any way to add them; if I go trought the "Add contact" menu, it only suggests me "full contacts" with phone, so in the end I can't add him/her.

**Comment by jfs** [comment]
Another vote for this feature. Any plans to implement this?

**Comment by fyahfox** [comment]
Im also interested in some feedback aobut the plans to implement this.

**Comment by TwoWholeWorms** [comment]
+1 more for this. :)

**Comment by HostFat** [comment]
any news about this feature?

**Comment by Aokromes** [comment]
added already.

**Comment by chichidori** [comment]
Tried joining some group and say no telegram account with this username but i can see that its active here is the link [](https://t.me/bitsyncio)

**Comment by Aokromes** [comment]
I vote banned on your country.

**Comment by mseibert** [comment]
Why is this closed? Would be a helpful feature.

**Comment by Aokromes** [comment]
because you can add username already.

**Comment by mseibert** [comment]
Ah, I see. My problem then is rather that you cannot add people that did not choose a username yet. How do you get them in a group?
