### ISSUE TITLE
Problem to converting a real link to link!

### ISSUE THREAD

**Issue by m-kermani** [telegramdesktop/tdesktop#2130]
I wanted to send a link to my friend but Telegram could not convert the link to link! I mean it was a link (standrad) but Telegram could not convert it to link and showed half of it as text.
This is the link I sent: **http://ariapix.net/dl/Mohsen%20Yeganeh_Mah%20Asal%2095[AriaPix.net].mp3**

You can open that link and that is a real link but just sent it by Telegram and that won't know it fully as a link

**Comment by zumoshi** [comment]
hello, 
brackets `[]` are reserved characters and must be escaped in links. 
the correct escaped version of your link is : 
http://ariapix.net/dl/Mohsen%2520Yeganeh_Mah%2520Asal%252095%5BAriaPix.net%5D.mp3
which is detected correctly in telegram.

you must replace `[` with `%5B` and `]` with `%5D`
this is not a telegram limitation , as it is part of RFC 3986.

see also: http://stackoverflow.com/a/1547922/1461004

**Comment by auchri** [comment]
The correct one: http://ariapix.net/dl/Mohsen%20Yeganeh_Mah%20Asal%2095%5BAriaPix.net%5D.mp3
