### ISSUE TITLE
Unable to compile QT 5.6.0 on Windows

### ISSUE THREAD

**Issue by XenHat** [telegramdesktop/tdesktop#2131]
I'm following the provided instructions and I get this error:
```
..\..\include\QtCore/qsystemdetection.h(1): fatal error C1083: Cannot open include file: '../../../../../../../cygdrive/d/TBuild/Libraries/qt5_6_0/qtbase/src/corelib/global/qsystemdetection.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.
```
The path created by the configure command exists and can be accessed using bash` (cygwin or else), so I'm not really sure what's broken in there.

Can I get some assistance?

**Comment by XenHat** [comment]
For the next person who stumbles upon this: Make sure you install python 3.x and add it **as well as the git for window's \bin directory** to your path.

**Comment by auchri** [comment]
There is a checkbox in the installers of git and python to add them to the PATH.

**Comment by XenHat** [comment]
I'm well aware. I develop other software that is incompatible with this environment so I did not add them initially.
