### ISSUE TITLE
Force_reply does not work when used with reply_keyboard

### ISSUE THREAD

**Issue by zumoshi** [telegramdesktop/tdesktop#2133]
### Steps to reproduce
1. add @Fatherhelpbot or any bot that uses `keyboard` and `force_reply` together for `reply_markup` to a group
2. write `/start`
3. press one of bots keys

### Expected behaviour
key message is sent as a reply to the bot's message

### Actual behaviour
key's message is sent normally (not as a reply)
even though the reply ui is shown and messages typed manually are sent as reply
but keys won't get replied

screenshot: 
![image](https://cloud.githubusercontent.com/assets/4184939/15959317/775a5cc4-2f0f-11e6-90fa-dccf942942cb.png)

this behavior does not happen in android version.

### Configuration
**Operating system:** Windows 8.1 x64
**Version of Telegram Desktop:** 0.9.49

**Comment by stek29** [comment]
#2099 duplicate

**Comment by zumoshi** [comment]
i searched for `force_reply` before posting... should've searched for reply keyboard also... my bad.

**Comment by stek29** [comment]
@zumoshi Well, at least you searched for something :)

**Comment by john-preston** [comment]
@zumoshi Thanks for your report! This will be fixed in the upcoming version, I hope it will be this week.

**Comment by stek29** [comment]
@auchri This issue's duplicate is already in Next version milestone...
