### ISSUE TITLE
Sent messages on the left

### ISSUE THREAD

**Issue by K1njulien** [telegramdesktop/tdesktop#2135]
### Steps to reproduce
1.Open Telegram on Windows
2.Expand the Window to full size
3.Enter a chat and you will see all messages on the left side( including your own)

### Expected behaviour
Receved messages on the left and sent messages on the right

### Actual behaviour
All messages are displayed on the left

### Configuration
**Operating system:**
Windows 10 Home

**Version of Telegram Desktop:**
0.9.49

![telegram bug](https://cloud.githubusercontent.com/assets/16562333/15973916/0ba523f6-2f46-11e6-9451-2994085fdd5b.png)

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#1587
