### ISSUE TITLE
custom socket5-proxy only works with localhost ?

### ISSUE THREAD

**Issue by pyed** [telegramdesktop/tdesktop#2136]
the country I'm currently living in blocks Telegram, so the quickest way to by-pass it was to use my server ssh, so I used the following command 
`$ ssh -vTND 4711 user@serverip`

now I went to my telegram desktop, changed `Connection type` to `TCP with custom socket5-proxy` set the `host` to `localhost` and the port to `4711` and it works just as expect, awesome.

now I wanted to setup a socket5 on my server so I don't have to execute that `ssh` command every time I want to use my telegram.

so I went and installed [Dante](https://www.inet.no/dante/index.html) on my server, now I can connect directly to my socket5 server, awesome right ? No !! Telegram desktop doesn't work with this configuration for some reason, it only works when the host is `localhost` ? I'm not sure why.

firefox seems to be happy with my socket5 server, it works as expected, but not Telegram Desktop, it tells me that it's connected, but telegram is still blocked !

**Comment by auchri** [comment]
Please provide a log:

> You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files. Type "debugmode" in settings again to disable logs.

**Comment by pyed** [comment]
@auchri I can't find any directory called `~/.TelegramDesktop` after turning that debug mode ON, I'm on a Mac

**Comment by auchri** [comment]
I don't know where the logs are stored on a mac, maybe @john-preston knows it.

**Comment by pyed** [comment]
@auchri they're at `~/Library/Application Support/Telegram Desktop/DebugLogs`

**Comment by pyed** [comment]
@auchri these logs has some pretty sensitive data :-/ I can't provide them publicly

**Comment by pyed** [comment]
@auchri sorry, I did not notice that the TCP logs are separated, you can find my tcp log here: http://sprunge.us/FYIX

I opened telegram turned the debug mode on, then connected to my socket-5 proxy, then waited sometime.

the block that this country apply is not complete block, it just throttles telegram to something like 1-2 Kb

**Comment by pyed** [comment]
here's another: http://sprunge.us/eFNU

**Comment by pyed** [comment]
here's another one using `localhost` which is the way that works: http://sprunge.us/MZMP

**Comment by john-preston** [comment]
@pyed Looks like it is almost working, but deadly slow: it took more than a second to receive 1.7 Kb packet. So perhaps it connects and tries to receive the chat list with the last messages, but never waits enough, decides that the connection is not working and resets it.

**Comment by pyed** [comment]
@john-preston Yes, that's the normal behavior of Telegram here in this country, it is throttled.

if you check my last log with the `localhost` you'll see that it is fast.

so my point is that, when I use socket5 proxy with external IP as the hostname it will just ignore it and connect using `Auto` maybe ? because `localhost` works.

**Comment by auchri** [comment]
@pyed 

What happens if you edit your [hosts file](https://www.tekrevue.com/tip/edit-hosts-file-mac-os-x/) and add something like `x.x.x.x    myproxy` (x.x.x.x = ip of your proxy server) and then set the proxy in telegram to myproxy?

**Comment by pyed** [comment]
@auchri My server has a domain name, same results, still slow.

I also tried `squid` which is a proxy server, installed it on my server, telegram is fast using `http-proxy` but I know for a fact that `socket5` is way more responsive, this `http-proxy` seems to have some annoying delay.

**Comment by john-preston** [comment]
@pyed Well, maybe connection from you to your remote server by telegram is still slow, not only from you to telegram servers by telegram.

**Comment by pyed** [comment]
@auchri Just tried the `hosts file` way, same thing, it will connect, but same thing

**Comment by pyed** [comment]
@john-preston I'm not sure if I entirely understand that, but connecting to my server is as fast as it should be, also my server to telegram is as fast as it should be and I know that because I have also a VPN setup on that server and when I connect to that VPN telegram will of course be fast as my whole OS is going through the VPN.

**Comment by pyed** [comment]
I really couldn't figure out why Telegram Desktop isn't going fast while I'm using socket-5 proxy, when I check `Dante`'s logs I can see that telegram is actually connected to it, but the connection is still throttled !! also I tried some free socket5 proxies and the same thing happened, I can't by-pass the throttle using an external socket5-proxy, while a localhost one will work !! this remains mystery.

**Comment by john-preston** [comment]
@pyed Well, maybe some real time protocol analysis is used to slow it down. Then after localhost proxy it is just an ssh, which is not recognized?

**Comment by pyed** [comment]
@john-preston I thought about that, but then how would explain the fact that using non-localhost socket5-proxy with Firefox will by-ass the throttling in `web.telegram.org` ?

**Comment by john-preston** [comment]
@pyed Web version always uses http-wrapped protocol (even https), so it can't be compared with tcp protocol of tdesktop. It can be compared with http protocol of tdesktop.

**Comment by pyed** [comment]
I see, the http protocol of tdesktop does by-pass the throttling. but the socket5 is way more responsive. which is why I'm trying to get it to work, I guess the best solution is just to use `ssh` and localhost to achieve the best telegram experience. Thank you.

**Comment by john-preston** [comment]
@pyed Currently there is no way to use http protocol with socket5 proxy in telegram desktop :(
