### ISSUE TITLE
Contact profile pictures

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#2138]
Good afternoon,

Quick question in relation to Telegram Desktop. Is there a particular piece of code that I am able to edit that will allow me to NOT display contact profile pictures in all views? Happy with just a blank white box.

May sound like a strange question, however some of my contacts have profile images that I don't honestly wish to see. :-)

Please do let me know.

Thanks

**Comment by stek29** [comment]
You mean profile pictures?

**Comment by Woodzrul** [comment]
Indeed. I doubt this is achievable, but thought I would ask the question.

In an ideal world I'd like to force an individual picture of my choosing for all my contacts.

**Comment by bliz937** [comment]
That's not a bad suggestion!

**Comment by john-preston** [comment]
@bliz937 There should be something like a paintUserpic() method in structs.cpp

**Comment by Woodzrul** [comment]
If this could be raised as a feature request then I'd really appreciate it. Not entirely sure who I would have to inform to get this approved...

**Comment by Woodzrul** [comment]
Skype for Business has this really cool feature re profile pictures. Would love this in Telegram please.

![pic](https://cloud.githubusercontent.com/assets/15090471/16459312/47eaed22-3e1a-11e6-8569-e2771beee629.PNG)

**Comment by Aokromes** [comment]
#430

**Comment by Cameri** [comment]
It could show the initials of the user instead of a profile picture.
