### ISSUE TITLE
[Feature Request] Allow Groups to have description

### ISSUE THREAD

**Issue by ccsadegh** [telegramdesktop/tdesktop#2141]
### Steps to reproduce
It is a feature request (really simple to implement).

### Expected behaviour
_Groups_ should have _description_ just like _Super-groups_ and _Channels_.

### Actual behaviour
It is not allowed to add a _description_ for a _Group_, we have to first convert it to a _Super-group_.

It should be really helpful to allow a _Group_ to have a _description_, some information must be shared among all members of the _Group_, of course without needing to convert it to a _Super-group_ (which is inefficient for a small _Group_).

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#1914

**Comment by ccsadegh** [comment]
It is not duplicate, I am asking to add this feature for normal Groups, not Super-groups. As you know it is not efficient to convert a Group to Super-group only for adding a description.

**Comment by john-preston** [comment]
@ccsadegh Why not?

**Comment by ccsadegh** [comment]
@john-preston Because it is inefficient to convert a small Group to a Super-group just only to add a description. Isn't it?

**Comment by john-preston** [comment]
@ccsadegh What do you mean by "inefficient"? If you need a description it just takes two clicks to convert it to a supergroup and you have the description.

**Comment by ccsadegh** [comment]
@john-preston Do Super-groups have any overhead for Telegram server?

**Comment by ccsadegh** [comment]
If Groups are going to be deprecated in favor of Super-groups, then it is OK, Groups don't need any description. But if Groups are going to be used forever, then for _unification_, Groups also should have descriptions.

**Comment by Kondra007** [comment]
@ccsadegh (I may be wrong)
Supergroups need **less** space for messages on Telegram servers because they [messages] are stored in one copy only. If you delete your message, it's gone for everyone.

Normal groups seem to be "group broadcasts" when every message is copied for every group participant.
