### ISSUE TITLE
Add the ability to mark important messages.

### ISSUE THREAD

**Issue by C-A-T9LIFE** [telegramdesktop/tdesktop#2143]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Add the ability to mark important messages. 
Example in VK
![photo_2016-06-14_18-59-07](https://cloud.githubusercontent.com/assets/16851877/16049882/163e56d8-3262-11e6-8136-1daebc4a642f.jpg)

### Actual behaviour
Tell us what happens instead

### Configuration
Windows 10

**Version of Telegram Desktop:**
0.9.49
### Logs
Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

**Comment by auchri** [comment]
Duplicate, no api for that
