### ISSUE TITLE
[feature request] custom solid color in chat background options

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#2145]
want to see **Choose color** in background options
![solid_color](https://cloud.githubusercontent.com/assets/10371194/16063994/1d6b01b0-32a6-11e6-9f39-56c81452ca36.PNG)

http://doc.qt.io/qt-5/qcolordialog.html#details

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#820
