### ISSUE TITLE
Time of edited message not changed

### ISSUE THREAD

**Issue by loentar** [telegramdesktop/tdesktop#2148]
### Steps to reproduce
1. Post some message to user-to-user or group chat. Picture or text.
2. Wait 1 or more minutes
3. Edit your last sent message or any earlier allowed to edit.
4. Text "edited" appeared near the time but time itself won't changed.

### Expected behaviour
Time should be the time of last edit.

### Actual behaviour
Displayed the time of original message sent.

### Configuration
**Operating system:** Linux Ubuntu 14.04 x86_64

**Version of Telegram Desktop:** 0.9.50

**Comment by john-preston** [comment]
@loentar This is intended, sorry. It works like in mobile apps. If it changes in iOS / Android it will change in tdesktop as well.

**Comment by loentar** [comment]
Well.. OK then..

**Comment by Kondra007** [comment]
@loentar By the way, if you hover cursor over message time, you'll see when it was last edited.
