### ISSUE TITLE
Notifications cover scroll to bottom button

### ISSUE THREAD

**Issue by chrjguill** [telegramdesktop/tdesktop#2150]
### Steps to reproduce
1.  Have the 'scroll to bottom' button be visible
2. Get a tdesktop notification
3. Notice the notification cover the button
### Expected behaviour

The notification shouldn't obscure other parts of the app - either the notifications should be elsewhere, or elements of the interface shouldn't be behind the notifications. 
### Actual behaviour

Notifications cover up the scroll-to-bottom button (as well as the emoji/sticker panel, but that's tangent to this issue)
### Configuration

**Operating system:** Arch linux x64

**Version of Telegram Desktop:** 0.9.5.1

**Comment by AndydeCleyre** [comment]
Would resolving #91 fix this for you? I know for sure Plasma Desktop lets you choose your notification area.

**Comment by chrjguill** [comment]
Ah yeah, definitely. My notification server displays notifs over my bar at the top of my workspaces, instead of over applications.
