### ISSUE TITLE
Cannot build MetaLang.xcodeproj because of QT version problem. (OSX)

### ISSUE THREAD

**Issue by strike2** [telegramdesktop/tdesktop#2151]
Installed QT5.6.0 but current source code is depended on QT 5.5.1
So I cannot build MetaLang.xcodeproj.

How can I build it?
![screen shot 2016-06-16 at 12 26 01](https://cloud.githubusercontent.com/assets/19915400/16105501/8f76dea6-33bd-11e6-875b-32aa49d868f0.png)

Thank you.

**Comment by TonyStarkBy** [comment]
Same problem

**Comment by john-preston** [comment]
@strike2 I've fixed the projects, see dev branch.
