### ISSUE TITLE
drag and drop for forwarding is broken

### ISSUE THREAD

**Issue by ahmadalli** [telegramdesktop/tdesktop#2153]
1. Drag a photo from a channel (I hadn't test dragging from a user)
2. Drop it in a chat with person (I hadn't tried dropping in a group or a channel)

### Expected behavior
Forward the photo

### Actual behavior
Nothing happens

### Configuration
**Operating system:** Windows 10  Insider Preview Build 14361

**Version of Telegram Desktop:** 0.9.51

**Comment by auchri** [comment]
Should be fixed
