### ISSUE TITLE
Feature: global search direct shortcut

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#2159]
Feature request:
Add Control-Shift-F for direct global search.
Currently for global search I need to unfocus a chat, and it could be nice to have that option in on keystroke.

**Comment by john-preston** [comment]
@arieljannai Escape?

**Comment by arieljannai** [comment]
yeah, it exist, I just thought it's a small and comfortable thing

**Comment by Aokromes** [comment]
#1060 ?
