### ISSUE TITLE
[Feature Request] hide dock counter for groups without notifications

### ISSUE THREAD

**Issue by francho** [telegramdesktop/tdesktop#2160]
### Steps to reproduce
1. Disable notifications a group (for example one with hight volume of messages)
2. When one new message arrives to this group, the docker's icon has an unread counter

### Expected behaviour
I would like that when I disable notifications for a group, this counter don't show unread messages for this "disabled" groups. This way the counter really means than an "important" message arrives

This could be an configurable user preference

### Actual behaviour
The dock icon counts all unread messages (not only the messages from conversations with notifications enabled)

### Configuration
OS X 10.11.5
Telegram  2.13.46728

**Comment by john-preston** [comment]
@francho Your report is not about this app. There is such checkbox in settings in Telegram Desktop app. You can download it from https://desktop.telegram.org
