### ISSUE TITLE
Add a way to lock the recording without the necessity to keep pressed the record buttom

### ISSUE THREAD

**Issue by ryukinix** [telegramdesktop/tdesktop#2166]
Well, sometimes I need to\* record something without my hands on computer (like a guitar session)  AND **IT'S REALLY HARD...**  here's what happens: When I try do this, I need put my feet on the mouse to click (recording) while I'm playing my guitar. Try to imagine this... My leg is suffering D:
 This doesn't works fine, guys. Would be possible to do something like that?

Thanks for the patiance to develop this delicious app. Big project and the best chat app native ever.

**Comment by diazbastian** [comment]
@ryukinix is related to #1060

**Comment by stek29** [comment]
@diazbastian I'd even say it's a duplicate.
