### ISSUE TITLE
program clash when resize window

### ISSUE THREAD

**Issue by sajad-deris** [telegramdesktop/tdesktop#2168]
when i resize the window, the program is crashed.
its are when the chat have keyboard,
watch this video

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5092164/16174121/e0fed752-35b5-11e6-93dd-fccf001cebb0.gif)

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#2101
