### ISSUE TITLE
Edit message with Up Arrow key not always works

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#2169]
### Steps to reproduce
1. Send message
2. Press <kbd>↑</kbd> key
### Expected behaviour

You able to edit your latest message
### Actual behaviour

Scroll
### Configuration

**Operating system:** Ubuntu 16.04 (Cinnamon DE)

**Version of Telegram Desktop:** 0.9.52 Alpha
### Logs

:heavy_multiplication_x:

**Comment by DaFri-Nochiterov** [comment]
> not always works

It's works in chat with your friend, in some `Lorem Ipsum`\* chats, but not works in `Telegram Party` and other chats. BUT! For some it works and in `Telegram Party`. It's why I created an issue. This is very strange behavior.

![image](https://cloud.githubusercontent.com/assets/10401817/16175233/e37cff36-360f-11e6-8095-741d8d69e69f.png)

\* - just for example name

**Comment by stek29** [comment]
Is it still here? Maybe it's caused by #2455?

**Comment by DaFri-Nochiterov** [comment]
Closed in favor of issues #2455 and #2454
