### ISSUE TITLE
RTL Reply quoted text isn't RTL direction-ed, but LTR

### ISSUE THREAD

**Issue by SafaAlfulaij** [telegramdesktop/tdesktop#2170]
### Steps to reproduce
1. Write some bidi text like "تجربة test نصية" and send it to any contact
2. Reply to the text with anything
### Expected & Actual behaviour

The reply quoted text should be treated as RTL text, but it is shown as LTR text.
(First line's direction is correct, the quoted text's direction is wrong)
![telegramreplaybidibug](https://cloud.githubusercontent.com/assets/3509617/16178518/4908ec64-3653-11e6-94b0-794866fe5519.png)
### Configuration

**Operating system:** Windows 10 - 64 bit

**Version of Telegram Desktop:** 0.9.52 Alpha

**Comment by auchri** [comment]
#1387
