### ISSUE TITLE
[Feature request] Double click should do something on computer versions.

### ISSUE THREAD

**Issue by oxydron** [telegramdesktop/tdesktop#2172]
Double click on someone's messages should:

- reply it
- foward it
- select it

On Windows/Linux/Mac versions.

**Comment by auchri** [comment]
I disagree, double click should *not* perform such actions. Double click is for opening files in Windows Explorer, but not for the actions you mentioned.

**Comment by oxydron** [comment]
So single/double click should do nothing?

**Comment by auchri** [comment]
No, because messages aren't links.

**Comment by oxydron** [comment]
And yet on a smartphone, you touch a message on Telegram and you get options.
On webpages (on a smartphone), you touch a text and nothing happens.
So, the right click on computers is the equivalent of the simple touch on smartphones?

**Comment by Trost123** [comment]
Yes, because you use left click to select text in messages and double\triple click to select word\sentence.

**Comment by stek29** [comment]
There's was a request about quick actions in corner of the bubble, and I like it better.
However, I think reply on double click next to the bubble on the same height won't harm. But I guess it's not worth the effort.
