### ISSUE TITLE
Tray icon doesn't remove unread messages notifications

### ISSUE THREAD

**Issue by tanty** [telegramdesktop/tdesktop#2177]
### Steps to reproduce
1. Open Telegram Desktop. The tray icon is shown with no notifications.
2. Eventually, some new message arrives. The tray icon changes to show the amount of unread messages.
3. Open Telegram clicking on the tray icon. Read the unread message(s)
### Expected behaviour

The tray icon is updated to show no unread messages pending
### Actual behaviour

The tray icon keeps showing that there are unread messages.
### Configuration

Debian Testing GNU/Linux on GNOME Shell 3.20.2-3. Latest TopIcons Plus extension installed:
https://extensions.gnome.org/extension/1031/topicons/

Telegram Desktop 0.9.53 alpha

---

Notice that I didn't have the tray icon until very recently, when I upgraded GNOME Shell to the 3.20.2-3 version so I cannot say if this is a regression.

**Comment by tanty** [comment]
I have test disabling the TopIcons Plus extension and the problem is still reproducible.

**Comment by tanty** [comment]
This seems to be fixed in 0.9.54 alpha

**Comment by tarpan** [comment]
Seems to reappear in 1.5.4.

**Comment by stek29** [comment]
see #5525
