### ISSUE TITLE
Window flickering while typing letter "n"

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#2180]
### Steps to reproduce
1. Open any chat in TDesktop
2. Start typing text containing English "n" letter or Russian "т" letter (they're both on the same keyboard button!)
3. Watch TDesktop window

### Expected behaviour
Everything goes OK

### Actual behaviour
TDesktop windows flickers when you enter that letter. I've made a video how it looks like: https://youtu.be/_UHKx8-NtuQ

### Configuration
**Operating system:** Windows 8.1 x64
**GPU**: NVidia GTX 970
**Version of Telegram Desktop:** 0.9.53 alpha

**Comment by auchri** [comment]
Maybe you assigned some action to your <kbd>n</kbd> key?

**Comment by john-preston** [comment]
@Kondra007 Strange :) I have no idea how this can happen and how to fix anything like that. And of course it doesn't reproduce in my case.

**Comment by Kondra007** [comment]
@auchri Yes, I have "N" button mapped for Push-to-talk in Team Speak, but I closed all other apps (even antivirus) before testing. So that's not the reason, I think.

@john-preston I guessed you can't reproduce this :( Well, I'll try other configurations and see if this still persists. Did you update QT version in some previous builds? If yes, could you give me download link for "before-update" one?

**Comment by john-preston** [comment]
@Kondra007 You can compare this two portable versions:

https://updates.tdesktop.com/tsetup/tportable.0.9.45.dev.zip is the last Qt 5.5.1 version

https://updates.tdesktop.com/tsetup/tportable.0.9.46.alpha.zip is the first Qt 5.6.0 version

(they'll start to autoupdate when you launch them, so you need to disable the autoupdate in settings)

**Comment by Kondra007** [comment]
@john-preston Both versions flicker :( 
So, looks like that's Windows (or GPU) problems. Should I close this issue?

**Comment by john-preston** [comment]
@Kondra007 I guess so :( At least, I'm not going to do anything about that (at least for now, with a single unreproducable report).
