### ISSUE TITLE
Draft is saved when using bots

### ISSUE THREAD

**Issue by Gollam** [telegramdesktop/tdesktop#2182]
A draft is saved when using inline bots, for example the @gif bot, and I think this is not a feature.

Steps to reproduce:
1. type "@gif asd" in a chat window
2. wait for gifs to appear
3. after 10-15 seconds, the draft is saved with text "@gif asd"
4. delete the text from the chat window, without sending it
5. the draft remains there for some time, and after 10-15 secs, it is deleted automatically

**Comment by john-preston** [comment]
@Gollam Well, this works as intended. It is cleared if you send an inline result, just like other drafts.

**Comment by Gollam** [comment]
All right, it's ok then.
