### ISSUE TITLE
[Feature Request] Automatic Respond Messages

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#2183]
For example for one week I can not access telegram, so when my friends send me message, an automatic message will be send to them, for example:

I'm in travel and reach you soon!

PS. I know this is not dekstop issue but anyway I wanted to tell you guys my idea. Thanks anyway.

**Comment by auchri** [comment]
You should create a bot for this task: https://medium.com/chatfuel-blog/how-to-create-your-own-telegram-bot-who-answer-its-users-without-coding-996de337f019#.h7jbhof7r

> PS. I know this is not dekstop issue but anyway I wanted to tell you guys my idea. Thanks anyway.

Then please don't open an issue here :wink:

**Comment by amiremami** [comment]
Ok sorry auchri, I wont do it again. And really appreciate your help. Thanks man.
