### ISSUE TITLE
 Crashes while opening a chat (OS X)

### ISSUE THREAD

**Issue by pcambra** [telegramdesktop/tdesktop#2184]
### Steps to reproduce
1. Open a chat with a particular person
2. App closes unexpectedly

### Expected behaviour
It should not crash.

### Actual behaviour
It closes down.

A couple more of detais, this is happening after adding a link to an image. I can't delete the chat (nothing happens) and if I try to open it in a new window, the app also crashes.

### Configuration
**Operating system:**
OSX 10.11.5

**Version of Telegram Desktop:**
Version 2.14.47289

### Logs
Attaching crash report
[Crash report telegram.txt](https://github.com/telegramdesktop/tdesktop/files/329508/Crash.report.telegram.txt)

**Comment by john-preston** [comment]
@pcambra You're using not Telegram Desktop, but other OS X Telegram app. You can try out Telegram Desktop from https://desktop.telegram.org

**Comment by pcambra** [comment]
Oh that's confusing, it says that is the official one and I assumed it was this one.
