### ISSUE TITLE
Alpha app not remembering window size on restart

### ISSUE THREAD

**Issue by Sushubh** [telegramdesktop/tdesktop#2185]
### Steps to reproduce
1. Resize the app window to your liking
2. Quit the app
3. Restart the app

### Expected behaviour
The app should restore itself to the previous window size. 

### Actual behaviour
The app starts at a different size. Basically the two column layout. I keep the app to single column layout. 

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
0.9.54 alpha

**Comment by john-preston** [comment]
@Sushubh Thanks, I guess I've found a bug. Should be fine in the next version.

**Comment by z3ntu** [comment]
Fixed?

**Comment by Sushubh** [comment]
Yup. The latest alpha fixed this.
