### ISSUE TITLE
scale option is gone and UI not working on windows

### ISSUE THREAD

**Issue by junesaku** [telegramdesktop/tdesktop#2186]
### Steps to reproduce

Unknown cause
I think Scale problem on HIDPI or hidden Windows setting problem

1080p normal pc not happen this issue
'surface pro 3', 'alienware 17 r3 4k monitor' happened this issuse
### Expected behaviour

Scale option work, mouse click work
### Actual behaviour

Scale option is gone, 
mouse click work only... 
uh... see img link

[update 160624 17:32] drag n drop work fine only mouse click

normal capture 
http://wiki.junus.kr/t_nor.png

err capture
http://wiki.junus.kr/t_err.png

mouse work only top left, other area not working, only work sizing

option name translate
'show tray icon'
'show taskbar icon'
'auto start telegram when windows start'
'minimize...'
'send to ...'
[normal telegram show here, scale options]
'Chat setting'
'emoji...'
...
not show scale option

top left work, and other is only work sizing and pointer only sizeing pointer
sometimes telegram window border broken
and sometimes telegram window pos, size broken

telegram reinstall not resolve problem
delete "%appdata%\telegram desktop\" not resolve problem
i found, only reinstall windows resove this issue 
other apps work fine
### Configuration

**Operating system:**
Windows 10 x64, 10586
**Version of Telegram Desktop:**
0.9.51
### Logs

Insert logs here (if necessary)

enter 'Debug Mode', 
leave 'Debug Mode', 
enter 'Debug Mode' and restart telegram

log move to https://gist.github.com/anonymous/2dcf6dc9b32a8cb9af7cc7cfa1036301

 -- update 2016-11-08
log move to gist ( is this right? )

and

i think current version solved this problem. (not happen this problem)

Should I close this?

**Comment by Aokromes** [comment]
Works for me (TM)

http://i.imgur.com/T8RJWMJ.png

**Comment by stek29** [comment]
@junesaku can you please move logs to gist?

**Comment by auchri** [comment]
> i think current version solved this problem. (not happen this problem)
>Should I close this?

Yes.
