### ISSUE TITLE
Can't type '^' in Chatwindow

### ISSUE THREAD

**Issue by PolynomialDivision** [telegramdesktop/tdesktop#2189]
### Steps to reproduce
1. Open Chat Window
2. Try to enter ^
### Expected behaviour

You should be able to enter ^
### Actual behaviour

Noting.
Copy and Paste is working.
### Configuration

**Operating system:**
Linux
Xubuntu 16.04

**Version of Telegram Desktop:**
 0.9.51

**Comment by z3ntu** [comment]
Normally it works for me entering the ^ key in telegram desktop, but sometimes the client just crashes instantly when entering this character. I am using the keymap "de" (with `setxkbmap`).

**Comment by auchri** [comment]
@z3ntu Does it work in 0.9.55 alpha version?

**Comment by z3ntu** [comment]
Yes it works but it also worked before. I can't test the random ^ crashes as they are random and I have not found a reproducible procedure (I always send a crash report when it happens).

**Comment by z3ntu** [comment]
This could also be related to #1360

**Comment by Aokromes** [comment]
works for me (TM) on 0.10.19 alpha.

**Comment by Aokromes** [comment]
So it toes on 0.10.16 alpha on slackware linux.

**Comment by PolynomialDivision** [comment]
Still not working for me under version 0.10.19 with Xubuntu 16.04 and German Keyboard Layout on a Lenovo X220.
