### ISSUE TITLE
Linux settings under ~/.TelegramDesktop

### ISSUE THREAD

**Issue by Trippler** [telegramdesktop/tdesktop#219]
The linux settings are currently located under ~/.TelegramDesktop
They should be located under ~/.local/share/TelegramDesktop OR ~/.config/TelegramDesktop

~/.local/share/ is for user data
~/.config/ is for configuration files
~/.cache/ is for non-essential data files

**Comment by bil-elmoussaoui** [comment]
this is the same as #624

**Comment by auchri** [comment]
Duplicate of #107
