### ISSUE TITLE
Tray icons should not be used on gnome

### ISSUE THREAD

**Issue by antony** [telegramdesktop/tdesktop#2191]
### Steps to reproduce
1. Load application
2. See tray icon
### Expected behaviour

Tray icons are deprecated [https://bugzilla.gnome.org/show_bug.cgi?id=747034](https://bugzilla.gnome.org/show_bug.cgi?id=747034) on gnome and should not be used.
### Actual behaviour

A tray icon appears
### Configuration

**Operating system:**
Ubuntu 16.04

**Version of Telegram Desktop:**
0.9.51
### Logs

Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

**Comment by z3ntu** [comment]
I am not using GNOME, so I still want my tray icons even though it doesn't go with the "design philosophy" of GNOME.

**Comment by antony** [comment]
Sorry, maybe it isn't immediately obvious. The goal would be to be
consistent with Gnome UX only on Gnome.

Other desktop environments would remain on line with their UX guidelines.

This is simply dropping the use of a deprecated GTK component.

**Comment by diazbastian** [comment]
@antony I am also Gnome user and I think you are wrong in your perspective. Consider that most Telegram users use Windows and macOS. Minority of users come from GNU/Linux and only part of them use Gnome , it would be a waste of resources for TDesktop developers adapt the client to each user interface of each popular desktop environment...

If you do not want to see an icon in the system tray, you have two options now:
* Uncheck "Show tray icon" option in the application settings
* Uninstall the "libappindicator" of the system

Cheers

**Comment by antony** [comment]
Am I wrong in assuming that there are already some sort of per-environment settings which are applied?

I think we have to be careful to differentiate between a 'waste of time' and something which makes for a comfortable experience on all environments.

For instance the attachment picker TDesktop when run on Gnome isn't the native one, and has no preview pane in it, meaning you end up picking blind.

My personal opinion is that minor tweaks to ensure that native toolkits are used where necessary to avoid this sort of problem are not a waste of time, and will do a lot to improve adoption, and make users transition from other clients such as WhatsApp considerably more likely.

**Comment by diazbastian** [comment]
@antony 
>Am I wrong in assuming that there are already some sort of per-environment settings which are applied?

Yes. If you take the time using GNU/Linux, you know well that there are different kits to build graphics  interfaces and not all are integrated equally to the different desktop environments available. Telegram Desktop uses QT.

>I think we have to be careful to differentiate between a 'waste of time' and something which makes for a comfortable experience on all environments.

You assume that developers must provide the best integrated experience for each system and partly true, however the idea is to provide a similar experience across platforms (Not only in Linux). Do not forget that in this case there is *already a configuration* option that *solves* the problem.

>For instance the attachment picker TDesktop when run on Gnome isn't the native one, and has no preview pane in it, meaning you end up picking blind.

I think that would be another improvement report. Consider that TDesktop uses QT and has its own "file chooser dialog" that differs from the native dialogue of each platform. If you do not know the name of the file you want to share, you can use alternative methods such as DND.
QT framework is very versatile and can be possible to use native dialogs on each platform. If still interested can consult with developers or send a PR.

>My personal opinion is that minor tweaks to ensure that native toolkits are used where necessary to avoid this sort of problem are not a waste of time, and will do a lot to improve adoption, and make users transition from other clients such as WhatsApp considerably more likely.

This is my personal opinion and does not reflect the opinion of developers, however, for any reason you can't determine the priorities of a project and doing a simple analysis, it is more important to offer the same features across platforms to modify the client which is integrated into each platform.

**Comment by auchri** [comment]
> I think that would be another improvement report. Consider that TDesktop uses QT and has its own "file chooser dialog" that differs from the native dialogue of each platform. If you do not know the name of the file you want to share, you can use alternative methods such as DND.
QT framework is very versatile and can be possible to use native dialogs on each platform. If still interested can consult with developers or send a PR.

#982, #987

**Comment by john-preston** [comment]
https://github.com/telegramdesktop/tdesktop/issues/944

Well, I already have an issue about the tray icon not working in gnome, this issue is about the tray icon working in gnome, but it should not -- now the pack is complete.. Linux one love <3

**Comment by lindhe** [comment]
Are the tray icons different from the top bar? Does and should the icon appear there?

**Comment by antony** [comment]
Hi, The tray icons are stuffed into a horrible little widget in the corner of Gnome Shell

![tray icons](https://cloud.githubusercontent.com/assets/218949/17521896/fac56d3a-5e4c-11e6-8a2e-13b9257a05f5.png)

The reason for this widget is because they want to phase the concept of tray icons out. It's a 'legacy' container for older applications that they hope to remove.

So this issue was raised really as a way of saying - on gnome, we should be looking to integrate telegram with the status notifier which is a dropdown menu which comes from the top of the gnome shell. This is the direction that tray icons are going in Gnome.

**Comment by lindhe** [comment]
Woooaaaa! You scared me. That's horrible, and it's good that that tray dies. I was blissfully unaware in i3wm (but running Gnome in background, that's why I was curious).

**Comment by kgizdov** [comment]
I just wanted to add to the discussion that with the removal of the notification icon, Telegram does not exit when the close button is clicked. It stays running forever in the background. The only way to stop it is to send SIGTERM directly to the process.

**Comment by john-preston** [comment]
@kgizdov In what DE do you experience this? I create tray icon if it is supported by the system and only in that case leave the app running when window is closed.

**Comment by kgizdov** [comment]
@john-preston I'm on Gnome 3.22.1 on Wayland (XWayland essentially) as it is the default now.

**Comment by john-preston** [comment]
@kgizdov I was told my build doesn't support Wayland at all, are you using the version from https://desktop.telegram.org?

**Comment by kgizdov** [comment]
@john-preston yes, that's why GNOME actually opens it through XWayland. Its purpose is to open X applications in a Wayland env. Telegram just doesn't have native Wayland support, which is annoying, but is not currently catastrophic (depending on how you look at it). My problem is that no tray icon appears, but Telegram apparently thinks it does and thus does not quit on window close.

**Comment by john-preston** [comment]
@kgizdov Well, it looks like GNOME tells Qt that tray icon is supported (or libappindicator with gtk is loaded successfully and respond on create icon calls), so I think that it is working. You can share ~/.local/TelegramDesktop/log.txt and we'll know (I hope) which one works as a false positive.

There can be "Using appindicator tray icon." or "Using GTK status tray icon." or "Using Qt tray icon."

**Comment by kgizdov** [comment]
@john-preston there is no `~/.local/TelegramDesktop/log.txt`, however there is `~/.TelegramDesktop/log.txt`. So I ran Telegram both in Wayland and XServer and here are the logs:

XServer Log:
```
[2016.11.09 15:14:17] Launched version: 10011, alpha: [FALSE], beta: 0, debug mode: [TRUE], test dc: [FALSE]
[2016.11.09 15:14:17] Executable dir: , name: 
[2016.11.09 15:14:17] Initial working dir: /home/user/
[2016.11.09 15:14:17] Working dir: /home/user/.TelegramDesktop/
[2016.11.09 15:14:17] Arguments: "telegram-desktop" "--"
[2016.11.09 15:14:17] Logs started
[2016.11.09 15:14:17] Connecting local socket to /tmp/9e548a309ec1f70d666d8f46d62175a0-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2016.11.09 15:14:17] This is the only instance of Telegram, starting server and app...
[2016.11.09 15:14:17] Moved logging from '/home/user/.TelegramDesktop/log_start0.txt' to '/home/user/.TelegramDesktop/log.txt'!
[2016.11.09 15:14:17] Error: failed to load 'gdk_x11_drawable_get_xdisplay' function!
[2016.11.09 15:14:17] App Info: reading settings...
[2016.11.09 15:14:17] App Info: reading encrypted settings...
[2016.11.09 15:14:17] App Info: reading map...
[2016.11.09 15:14:17] App Info: reading encrypted map...
[2016.11.09 15:14:17] App Info: reading encrypted user settings...
[2016.11.09 15:14:17] App Info: encrypted user settings read.
[2016.11.09 15:14:17] App Info: reading encrypted mtp data...
[2016.11.09 15:14:17] Map read time: 1
[2016.11.09 15:14:17] TCP Error: network - Network unreachable
[2016.11.09 15:14:17] HTTP Error: network error 99 - Network unreachable
[2016.11.09 15:14:17] Not using Unity Launcher count.
[2016.11.09 15:14:17] Getting difference! no updates timer: 0, remains: -1
[2016.11.09 15:15:06] Explicitly closing main log and finishing crash handlers.

```

Wayland Log:
```
[2016.11.08 10:41:37] Launched version: 10011, alpha: [FALSE], beta: 0, debug mode: [TRUE], test dc: [FALSE]
[2016.11.08 10:41:37] Executable dir: , name: 
[2016.11.08 10:41:37] Initial working dir: /home/user/
[2016.11.08 10:41:37] Working dir: /home/user/.TelegramDesktop/
[2016.11.08 10:41:37] Arguments: "telegram-desktop" "--"
[2016.11.08 10:41:37] Logs started
[2016.11.08 10:41:37] Connecting local socket to /tmp/9e548a309ec1f70d666d8f46d62175a0-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2016.11.08 10:41:37] This is the only instance of Telegram, starting server and app...
[2016.11.08 10:41:37] Moved logging from '/home/user/.TelegramDesktop/log_start0.txt' to '/home/user/.TelegramDesktop/log.txt'!
[2016.11.08 10:41:38] Error: failed to load 'gdk_x11_drawable_get_xdisplay' function!
[2016.11.08 10:41:38] App Info: reading settings...
[2016.11.08 10:41:38] App Info: reading encrypted settings...
[2016.11.08 10:41:38] App Info: reading map...
[2016.11.08 10:41:38] App Info: reading encrypted map...
[2016.11.08 10:41:38] App Info: reading encrypted user settings...
[2016.11.08 10:41:38] App Info: encrypted user settings read.
[2016.11.08 10:41:38] App Info: reading encrypted mtp data...
[2016.11.08 10:41:38] Map read time: 3
[2016.11.08 10:41:38] TCP Error: network - Network unreachable
[2016.11.08 10:41:38] HTTP Error: network error 99 - Network unreachable
[2016.11.08 10:41:38] Not using Unity Launcher count.
[2016.11.08 10:41:38] Getting difference! no updates timer: 0, remains: -1

```
I personally don't see any difference. However, when running in XServer I do get an icon, but in Wayland - I do not.

**Comment by rsenna** [comment]
Btw, if you, dear Telegram user, like me, could not care less about tray icons or status notifiers or whatever: just turn off "Show tray icon" in the settings dialog. Seriously, that may be obvious, but I just noticed that Telegram actually **shuts down** when I close it, but only if "Show tray icon" is turned off (otherwise, if "Show tray icon" is on, Telegram stays resident, and since I cannot see any tray icon in Gnome, I can only terminate it by sending a SIGTERM).

**Comment by Aokromes** [comment]
@john-preston cannot this be fixed on 1st run with a if gnome disable tray icon?

**Comment by jhasse** [comment]
Starting with GNOME 3.26 the tray icon doesn't appear: The GNOME devs removed them completely. So I would close this issue as I don't think there should be more hard-coding of different bahaviour depending on the desktop environment in Telegram.

**Comment by antony** [comment]
@jhasse that's not quite right.

They've removed it because it was a workaround *whilst developers updated their apps to use newer apis*. So it's removal is really the last warning that status indicators are no longer supported under gnome, and that the notification method should have been changed by now.

So actually if anything the course of action should be to update Telegram to use the notifications area under Gnome.

However, it's entirely up to the developers if they want to do this or not, and I appreciate that.

Without the new APIs however, the features on the status icon's context menu are now sadly gone, and minimising it will lose the window with no way to get it back. So it's a bit annoying.

**Comment by jhasse** [comment]
> So actually if anything the course of action should be to update Telegram to use the notifications area under Gnome.

That is discussed in #3830 though, so I stilll think that *this* issue should be closed.

**Comment by antony** [comment]
Wasn't aware of that issue - yes, this issue should be closed as it is a moot point now :)
