### ISSUE TITLE
Image pasted was sent in the wrong method

### ISSUE THREAD

**Issue by rexx0520** [telegramdesktop/tdesktop#2194]
### Steps to reproduce

1.copy an image on a web page(I use Chrome)
2.paste on TG
3.
### Expected behaviour

The image which was pasted should be sent by image method
### Actual behaviour

The image was sent by file method
### Configuration

Windows 10 x64

**Version of Telegram Desktop:0.9.51**

**Comment by auchri** [comment]
@rexx0520 Can you provide a example image which gets send as file?

**Comment by rexx0520** [comment]
[](https://www.youtube.com/watch?v=tii8PZj5FJI)
I just record a video that reproduce the issue.
