### ISSUE TITLE
Ctrl-A and Ctrl-E do not work as usual

### ISSUE THREAD

**Issue by davidgomes** [telegramdesktop/tdesktop#2195]
### Steps to reproduce
1. Press Ctrl-A or Ctrl-E in the text box to send a message
2. Cursor does not jump to the start or end of the text box, as expected, respectively
### Expected behaviour

The cursor should jump to the start or end of the text box as it is the default behaviour in macOS.
### Actual behaviour

Nothing happens.
### Configuration

**Operating system:**
OS X El Capitan

**Version of Telegram Desktop:**
0.9.51

**Comment by lazywei** [comment]
Confirmed with version 0.9.56. The "Home" / "End" keys work though.

**Comment by jutkko** [comment]
To add more shortcuts I use and does not work: Ctrl + h deletes a character, Crtl + b goes back by one character and Ctrl + f does forward by a character...

Hi, is this functionality taken out by design? If so, why?

**Comment by stek29** [comment]
#729 duplicate.
