### ISSUE TITLE
A group administrator can't see the list of all administrators

### ISSUE THREAD

**Issue by haevalencia** [telegramdesktop/tdesktop#2196]
Telegram Desktop 0.9.51

In previous versions, a group administrator could see the list of all the administrators, however, this feature is currently missing. For example, the Android version is still available in Group info, Edit, Administrators.

Another cool missing feature is the ability to see the link to pinned message in a group.

**Comment by auchri** [comment]
Use the template next time.

**Comment by haevalencia** [comment]
Sorry @auchri, but the template is not for general use, it seems to report bugs and not for improvement reports. I do not know if it is a regression or a design feature.

**Comment by auchri** [comment]
I can still see the list of administrators.

![image](https://cloud.githubusercontent.com/assets/5092164/16363703/dea09c7a-3bd2-11e6-8ed1-e234a0af21ba.png)

![image](https://cloud.githubusercontent.com/assets/5092164/16363704/104594e2-3bd3-11e6-80ef-de25992670e7.png)

**Comment by haevalencia** [comment]
Only the creator of the group/supergroup has access to these options. Any other administrator, can not see the list of managers like Android or iOS.

**Comment by Aokromes** [comment]
I can see all the admins on a group where i am admin and admins on a group where i am user.

**Comment by haevalencia** [comment]
@Aokromes Can you show a screenshot of the list you say access?
When I am the creator of a group I can see the section, "manage administrators" in the group info, however when I'm just an administrator have to look for administrators in the general list members (looking for the stars).

**Comment by diazbastian** [comment]
I can confirm that this option is missing.

Android
![photo_2016-06-27_00-54-58](https://cloud.githubusercontent.com/assets/5126124/16370312/fcd385c6-3c14-11e6-83a2-fd6d9ad0eaea.jpg)

TDesktop
![final](https://cloud.githubusercontent.com/assets/5126124/16370321/09a878c4-3c15-11e6-9c7f-edcc19538e0c.png)

**Comment by Aokromes** [comment]
https://i.imgur.com/da5oQag.png
