### ISSUE TITLE
Turning Caps Lock on prevents backspace from working on Linux

### ISSUE THREAD

**Issue by perk11** [telegramdesktop/tdesktop#2199]
### Steps to reproduce
1. Type some text in message window
2. Turn Caps Lock on
3. Press backspace
### Expected behaviour

Typed text is deleted
### Actual behaviour

Nothing happens
### Configuration

**Operating system:**
Kubuntu 14.04
**Version of Telegram Desktop:**
0.9.56

**Comment by z3ntu** [comment]
@perk11 Is this still an issue? I do not experience this on KDE.

**Comment by perk11** [comment]
Still have this on KDE5 (Kubuntu 16.04) with Telegram 0.10.1

**Comment by z3ntu** [comment]
What locale are you using? (command `locale`)

**Comment by perk11** [comment]
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
➜  ~

**Comment by jenie-jenie** [comment]
Having the same problem on two different machines running Arch Linux (x86_64) with Openbox

**Comment by atomAltera** [comment]
Same issue with 1.1.18 on BunsenLabs (Debian 7) with Openbox

**Comment by stek29** [comment]
I remember having this issue on Arch with xfce and Mac ISO keyboard layout, with en_US.UTF-8 layout.

**Comment by agur4ik** [comment]
Same here on ArchLinux with KDE.

**Comment by mxa** [comment]
Don't have this issue (Mint cinnamon).

**Comment by perk11** [comment]
Still happens in Kubuntu 18.04, both when Caps Lock is used for keyboard layout switching and when it's not.

**Comment by klimentyev** [comment]
Still happens in Gentoo and Calculate Linux, Telegram version 1.4.7 and earlier.

**Comment by Sergey305** [comment]
Still happens in openSUSE Tumbleweed with KDE

**Comment by PgLoLo** [comment]
gUyS, iN YoUr fUcKiNg mEsSaNgEr tHe fUcKiNg kEyBoArD DoEs nOt wOrK. aRe yOu pLaNnInG To sOlVe tHiS PrObLeM?

**Comment by PgLoLo** [comment]
Still sane, exile?

**Comment by HUMZZY** [comment]
This a scam hackers got in bro don’t use it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mxa** [comment]
Backspace when in Caps Lock works well in the distro supplied version of Telegram 1.5.11 on (K)ubuntu. Can you try?

**Comment by mxa** [comment]
I suspect this Caps Lock issue is another problem caused by not using the official QT from the system but a slightly patched one. https://github.com/telegramdesktop/tdesktop/issues/1815

**Comment by Sergey305** [comment]
> Backspace when in Caps Lock works well in the distro supplied version of Telegram 1.5.11 on (K)ubuntu. Can you try?

Half a year since my last comment. Recent Tumbleweed (new installation, btw), same issue.

**Comment by mxa** [comment]
Instead of moaning it would be better to confirm if the issue is indeed related to https://github.com/telegramdesktop/tdesktop/issues/1815 or not. Unfortunately afaik there is no Telegram distro version for Suse (yet).

**Comment by 3cky** [comment]
Fedora (RPMFusion) latest version 1.8.1 still have this problem too.

**Comment by mxa** [comment]
> Fedora (RPMFusion) latest version 1.8.1 still have this problem too.

Are you sure you are using the distro repository version, because that seems to be still at 1.6.7-2.fc30 according to https://pkgs.org/download/telegram. If you downloaded and extracted Telegram from their website, then it comes with its own QT which is causing all this trouble with Caps, compose keys and intl. language input like fcitx, nimf, etc.

**Comment by 3cky** [comment]
@mxa yes, please see http://koji.rpmfusion.org/koji/packageinfo?packageID=492

**Comment by mxa** [comment]
> @mxa yes, please see http://koji.rpmfusion.org/koji/packageinfo?packageID=492

Has this version been patched to use the system QT? Or does it come including the Telegram-QT?

**Comment by 3cky** [comment]
> Has this version been patched to use the system QT? Or does it come including the Telegram-QT?

According to ldd, it uses system Qt libs:
```bash
$ ldd /usr/bin/telegram-desktop | grep Qt
	libQt5Network.so.5 => /lib64/libQt5Network.so.5 (0x00007f1be3a00000)
	libQt5Widgets.so.5 => /lib64/libQt5Widgets.so.5 (0x00007f1be3360000)
	libQt5Gui.so.5 => /lib64/libQt5Gui.so.5 (0x00007f1be2e28000)
	libQt5DBus.so.5 => /lib64/libQt5DBus.so.5 (0x00007f1be2d8c000)
	libQt5Core.so.5 => /lib64/libQt5Core.so.5 (0x00007f1be286e000)
```

**Comment by ilya-fedin** [comment]
I did some investigating, there are an ancient Qt bug that prevents from working backspace if caps lock is layout switcher and actual caps lock is shift + caps lock
https://bugreports.qt.io/browse/QTBUG-49771
The only solution is to not using caps lock as a layout switcher.

**Comment by mxa** [comment]
Can't reproduce this bug with Telegram 2.0.1 on Kubuntu.

**Comment by klimentyev** [comment]
Can't reproduce this bug with Telegram 1.9.22 on Calculate Linux (KDE). I used Gentoo ebuild for build Telegram.

**Comment by ilya-fedin** [comment]
I'm glad to hear it, but I can reproduce this issue with 100% success if I set caps lock as a key for layout switching and enable caps lock with shift+caps lock

**Comment by mxa** [comment]
> I'm glad to hear it, but I can reproduce this issue with 100% success if I set caps lock as a key for layout switching and enable caps lock with shift+caps lock

Ah, I use the caps lock key as compose key and enable caps lock by pressing both shift keys simultaneously.

**Comment by ilya-fedin** [comment]
@Aokromes can you reopen this since the fix was reverted?

**Comment by ilya-fedin** [comment]
Qt bug is workarounded by https://github.com/desktop-app/lib_ui/commit/b5fb343d6cea52df8cde00e8e3ca1008c05e4589, should work fine in 2.5.3
