### ISSUE TITLE
Show recent chats on desktops with no internet connection (temporarily in offline mode)

### ISSUE THREAD

**Issue by Bezejmenny** [telegramdesktop/tdesktop#2201]
### Steps to reproduce
1. Put PC to offline mode (no internet connection)
2. Quit Telegram
3. Start Telegram

### Expected behaviour
Start Telegram (in some kind of offline mode) and show all recent (cached/stored) chat rooms, texts, downloaded pictures etc. Let user to browse and search all history.

### Actual behaviour
Telegram starts, but shows no chat rooms. User cannot access recent communication, whole app is totaly blank/empty for the user.

### Configuration
**Operating system:**
Windows 7 Pro x64 SP1
**Version of Telegram Desktop:**
0.9.56
but this is older issue

**Comment by dgadelha** [comment]
I think that this could also be a vulnerability. A user could access the chats offline even if the session was disconnected from another device.

**Comment by auchri** [comment]
And tdesktop stores no message on your hard drive, so it's not possible to implement this.

**Comment by XenHat** [comment]
What if the connection drops while the client is still open? In my experience, it seems to purge them from memory (or at least hide them from the user). I would prefer to retain access to already-received data for the rest of the application lifetime.

**Comment by dgadelha** [comment]
Still opens a vulnerability door.

**Comment by Bezejmenny** [comment]
The usecase is simple - I have to access my chat history on places with no internet connection. There is still a lot of places with no 3G/LTE coverage in Czech. The same issue is with roaming. It's silly to pay for data just to access chat history o my own PC. This is why I prefere Outlook rather than webmail.

**Comment by Aokromes** [comment]
#1087
