### ISSUE TITLE
Power consumption optimisation.

### ISSUE THREAD

**Issue by hr111** [telegramdesktop/tdesktop#2202]
I use Debian 8, telegram 0.9.56, ALSA sound (pulseaudio is not installed).

Telegram always makes an audio device open, even if the options are turned off audio alerts and of audiocodec can not go to sleep. I think it is useless waste of battery power. Why can not release the audio device and always using it?

cat /proc/asound/card0/pcm0p/sub0/hw_params

access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 1024
buffer_size: 8192

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#1044
