### ISSUE TITLE
Nonpersistent login

### ISSUE THREAD

**Issue by matheussilvapb** [telegramdesktop/tdesktop#2203]
### Expected behaviour
Login should be persistent through executions of the app.

### Actual behaviour
Several times I execute the app and it asks my phone number and sends me the code to activate.

### Configuration
**Operating system: Debian 8**

**Version of Telegram Desktop: 0.9.56**

**Comment by auchri** [comment]
Try the steps from https://github.com/telegramdesktop/tdesktop/issues/1426#issuecomment-166275883

**Comment by matheussilvapb** [comment]
Apparently working with the shortcut it creates (I'm using gnome).
