### ISSUE TITLE
Stop update chat order when mouse over chat lists

### ISSUE THREAD

**Issue by freeseacher** [telegramdesktop/tdesktop#2216]
I is very annoying behavior when you have several chats with lots of activity and you want to select one of them. the delay between pointing and clicking can lead to select different chat that tou wish.

I propose setting or maybe default behavior that will stop update chat order unless mouse is in chat list.

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#1504
