### ISSUE TITLE
Notifications shown on locked screen and on screensaver

### ISSUE THREAD

**Issue by Katzen-Gott** [telegramdesktop/tdesktop#222]
Hi. I'm running KUbuntu 14.04 and Telegram 0.6.5 and I've noticed, that when I lock screen (leave -> lock screen), notifications from telegram are still shown. And even when screensaver starts, notifications are shown above the screensaver.
It is not very important for me personally, but I think it can be viral for some people.

**Comment by ozanyolyapar** [comment]
+1
@auchri, this happens for Windows too. I am using Win10.
