### ISSUE TITLE
Maximum "Interface Scale" is not enough for an HDPI screen

### ISSUE THREAD

**Issue by eimanip** [telegramdesktop/tdesktop#2227]
Hi,
I have a Windows laptop with an HDPI screen (resolution: 3200x1800, 13" display). Even setting the Interface Scale in Telegram Desktop settings to the max value %200, it still looks very small and the messages cannot be read easily. I would be appreciated if you provide upper scales in the Windows application.
Thanks for your support

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#2144
