### ISSUE TITLE
[Feature request] Allow any user to change supergroup picture and name

### ISSUE THREAD

**Issue by MathyM** [telegramdesktop/tdesktop#2228]
Hello,

I do not know if it is already possible to do this. If it is, I'm sorry, but I wasn't able to. I manage a medium-sized group of approximately 60 people, and we recently turned our group into a supergroup so we could delete messages (we have a strict rule against pornography during work hours, but sometimes people forward stuff to the wrong group, and we end up receiving NSFW content when lots of us are at work with people around). I also got a second admin to help me out filtering this content.

However, we found out that now only the two of us can change the group title and display picture, and being a medium-sized group of friends, this is getting very frustrating for our users. We wish that it was possible to allow an intermediate level of moderator that can change these like they previously could, but that still hadn't got the power to delete messages and ban users (we fear that this might turn our group into chaos).

Another option would be to revert to a normal group, but that's not possible directly (or is there anyone I can reach in hopes of achieving this conversion? Even if the messages that were sent between the conversion to super group and now were to be lost, we would prefer this). I know that I was warned that this wouldn't be possible, but what I was *not* informed of was that the members would lose certain ability.

Thanks for the time to read and respond, and I hope this can help many others!

**Comment by MathyM** [comment]
As a kludge, is there any method that allows a bot to change the group title or picture?
I'm reading the manual, and there are some admin privilege level methods like kicking users, but I can't seem to find one to set chat status. Is there any way to do so?

**Comment by stek29** [comment]
It's not TDesktop issue, it's an [API issue].
