### ISSUE TITLE
Xubuntu 16.04: ugly fonts in contact list

### ISSUE THREAD

**Issue by disharmonized** [telegramdesktop/tdesktop#2234]
### Steps to reproduce
1. Open app in Xubuntu 16.04
2. Look at contact list.

### Expected behaviour
Smoothed, pretty fonts expected.

### Actual behaviour
Pixelated, ugly fonts actual.

### Configuration
**Operating system:**
Xubuntu 16.04
**Version of Telegram Desktop:**
0.9.56
### Screenshot

![](http://i.imgur.com/xNEBtjU.png)

**Comment by png2378** [comment]
This is Xubuntu issue, not Telegram.
