### ISSUE TITLE
Make "round" message bubbles toggleable

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2235]
### Steps to reproduce
1. Update to <s>0.9.57 alpha</s> 0.10
2. Cry

Please, make new rounded message bubbles toggleable (old/new style). IMO new bubbles are waaaay too rounded.

**Comment by TiagoDanin** [comment]
New bubbles is very ugly... :(

**Comment by Geobert** [comment]
Looks like a bug to me…

**Comment by Kondra007** [comment]
@Geobert that's not a bug: https://telegram.me/desktop/31

**Comment by matteocontrini** [comment]
The idea might not be bad but the borders are way too rounded.
An option for choosing between different styles would be an idea as well.

**Comment by diazbastian** [comment]
I think the idea of rounded corners on chat bubbles is not a bad idea, but based on the design of iOS was not very successful. I think better to have an option to change design is to improve the idea of the current, perhaps something similar to the Android design.

* Corners chat bubbles less rounded
* Add the tail of the chat bubble

**Comment by Kondra007** [comment]
@diazbastian I personally will be **very happy** if TDesktop gets Android-like bubbles. They seem almost perfect

**Comment by Dragory** [comment]
What happened to "Next version"?

**Comment by Geobert** [comment]
I think the dev just told us "deal with it"

**Comment by Defman21** [comment]
The release just got the round style. I think the next release will be the one without this styling.

**Comment by Sithdown** [comment]
The round chat bubbles are ugly as fuck. Turn them The images shouldn't be rounded at all.

**Comment by Geobert** [comment]
I'm just wondering what's the point of testing alpha channel and giving feedback if they don't give a f*ck about it.

**Comment by Lazek** [comment]
+1

**Comment by Noiwex** [comment]
Yes it's indeed ugly. Even images are rounded, what were you thinking?

**Comment by limenet** [comment]
The text bubbles are one thing (they're ugly) - but the images (still or animated/GIF - even videos) are especially bad since the rounded corners crop off a part of the image. This is unpleasant and annoying, as I consider this "not displaying the message I sent correctly/completely". I don't want to click on the image/video, just to see it - nor do I want the recipient of my message to have to do so.

Telegram is great in a lot of respects, and one of them is the open-source aspect and listening to the community (as evident by [this update](https://telegram.org/blog/trending-stickers#personal-storage)). Seeing so many people responded to this issue, I think it's a safe bet to say, people have mixed feelings towards this new design. Hopefully, the developers take note of this :)

**Comment by Geobert** [comment]
@limenet unfortunately, we can't be sure. Many things are not done despite a big shout from users. Exemple: Secret chat on desktop. See issue 871…

**Comment by JokerQyou** [comment]
Ok, "next version" tag removed, so I guess I'll have to use Android version instead of tdesktop for a few months. Good job.

**Comment by Noiwex** [comment]
There is also web.telegram.org

**Comment by Geobert** [comment]
@Noiwex unfortunatly, Web version does not have the edit feature (or I'm imssing it?)

**Comment by matteocontrini** [comment]
@Geobert https://github.com/zhukov/webogram/issues/1155

**Comment by FichteFoll** [comment]
Unfortunately, the best part about a "native" app for me is that it doesn't require a browser (and is also not built using electron, which is just another browser), so web.telegram.org is not an option.

**Comment by dreit-p** [comment]
Now my eyes cling to the partitions created by rounding, and earlier had a chance at all to ignore the message separator.

**Comment by KeatonKafei** [comment]
The new bubbles might match iOS/Mac OS design principles, but they really clash with Windows, Ubuntu, Gnome, KDE and many other operating systems. All of these use hard corner or low corner-radius rounded boxes for similar elements. 

https://developer.microsoft.com/en-us/windows/design
https://design.ubuntu.com/apps
https://developer.gnome.org/hig/stable/
https://community.kde.org/KDE_Visual_Design_Group/HIG

They were perfectly fine the way they were before. Please let users set the radius or consider reverting the changes.

**Comment by felixfoertsch** [comment]
Copy paste from my duplicate:

Hey guys,

I just updated tdesktop to find out, that you changed the look and feel of the chat. You switched from the nice individual looking rectangular design to chat bubbles, but even without the thingy that shows thats a chat bubble. It's just rounded squares.

This reminds me of the widescreen issue, that was one of the most discussed issues here:
#1587

Just WHY? Please stop messing with stuff the user doesn't request changing. To me, it looks super ugly. Ofc I will get used to it. But why do you spend hours changing stuff like this in the first place? And if you change it, why don't you allow switching to this "new" design instead of forcing it again.

Please focus on technical issues and if you change the user interface, do it for a reason. Not just because.

**Configuration**
Operating system:
macOS 10.11.6
Version of Telegram Desktop:
0.10

**Comment by omggga** [comment]
Terrible changes, that's real ugly now.

**Comment by lgommans** [comment]
I have yet to hear a single positive response about this from my peers, and heard several unprompted negative reactions.

Many people ask for a configurable setting. This could be done, but while I am a general fan of more settings and customization options, I frankly think the old version was just fine. Grander features like custom themes could be cool (though off-topic in this issue), but a separate setting in the UI just for border radius is silly. It seems everyone except the person who made the change was fine with the old chat layout.

Personally I think this is bugfix worthy. No need to wait for a future release, just revert and the vast majority will be happier. Settings or long-term solutions can be done in future releases.

**Comment by lindhe** [comment]
This would be a great time to implement themes! I really want my Telegram to be dark, and I can not stand these new awful bubbles. It can not live on my secondary monitor currently, but must be minimized.

**Comment by Noiwex** [comment]
Pull requests are welcome?

**Comment by lgommans** [comment]
@Noiwex You mean like this one? https://github.com/telegramdesktop/tdesktop/pull/2321

**Comment by john-preston** [comment]
@Noiwex Pull requests are welcome for (at least):

— crash fixes
— memory leak fixes
— freezes fixes
— fix for "default audio device change doesn't switch audio device in tdesktop" issues (many)
— fix for "input methods / compose / accents problems in different Linux distros / desktop environments / window managers" issues (many)
— fix for "Telegram hangs on W10 Anniversary Update" issue #2296
— fix for "Telegram interrupts full screen games with notifications" issue #2290
— fix for "Input prompt is not cleared when typing Japanese" issue #2280
— fix for "Telegram desktop not sending media files" issue #2279

.. and many others .. :)

**Comment by matteocontrini** [comment]
.__.

**Comment by KeatonKafei** [comment]
Two styles that would in my opinion work better across multiple systems:
![bubble styles](http://i.imgur.com/xp3ulw9.png)

I also think the darker color below a bubble makes more sense as a transparent shadow instead of a 3D effect, so it should be black for green bubbles as well.

**Comment by Noiwex** [comment]
I don't think that whoever made 16px bubbles got a sane mind, at least
currently.

I mean, any person with aesthetic taste is disgusted by these sausages. 00s
are over.

**Comment by JordyValentine** [comment]
You guys had it looking pefect and then this?
Radius needs to be more like 3 or 4px.

Is there a build of the pervious version available to roll back to? I prefer the desktop app, but I don't want to look at this mess.

**Comment by hamsta007** [comment]
Just download previous release from filehippo or some other site and turn off the automatic update.

**Comment by Sithdown** [comment]
@hamsta007 This one works fine (Windows): [http://filehippo.com/es/download_telegram/download/7153b3c41636aa16a257f7033c626423/](FileHippo - Telegram 0.9.56)

**Comment by src386** [comment]
+1 for a setting.

**Comment by littleguga** [comment]
This commit changed everything :D

https://github.com/telegramdesktop/tdesktop/commit/1904a4f48ac41f25a903253e6152d6419ed1b532

**Comment by littleguga** [comment]
https://updates.tdesktop.com/tsetup/tportable.0.9.56.zip

@JordyValentine You can get old normal version here.

**Comment by alexladerman** [comment]
+1 preferred rectangles

**Comment by JordyValentine** [comment]
@littleguga Thanks mate!

**Comment by codefuhrer** [comment]
While everything in this app is moving to Material Design, these bubbles are clearly taken from iOS design. Looks awful :-1:

**Comment by Dragory** [comment]
Could we just get a reply from a dev on this? The design change was pushed to stable against all alpha feedback and no dev even bothers to reply to the thread with almost 100 thumbs up. Why do you deliberately ignore your community like this? The old design was better! Change it back!

**Comment by Noiwex** [comment]
Is there any conspiracy theories about this?

**Comment by JokerQyou** [comment]
Well I think maybe there is a conspiracy of silence. 😆

**Comment by MrMetric** [comment]
Here is a GDB script to fix it (GNU/Linux only):

    tbreak _ZN3App9initMediaEv
    commands
    	set {int}_ZN2st9msgRadiusE=3
    	continue
    end
    run
    detach
    quit

Run it like this, assuming it is saved to `msgRadius.gdb` and Telegram is `/usr/bin/telegram-desktop`:

    $ gdb -x msgRadius.gdb /usr/bin/telegram-desktop

After Telegram opens, you can press Ctrl+c to close GDB, then close the terminal (dunno how to automate that part)

**Comment by Defman21** [comment]
You can edit a desktop file to run that command.

**Comment by MrMetric** [comment]
New script for 0.10.6:

    tbreak _ZN3App9initMediaEv
    commands
    	set {char}_ZN3App9msgRadiusEv=0xB8
    	set {int}(_ZN3App9msgRadiusEv+1)=3
    	set {char}(_ZN3App9msgRadiusEv+5)=0xC3
    end
    run
    detach
    quit

This replaces the start of `App::msgRadius` with

    mov $0x3, %eax
    retq

In C++, that is `return 3;`

Explanation: 0xB8 means mov to %eax, 3 is the border radius, and 0xC3 is retq

**Comment by earendilsomet** [comment]
Worked for me on Ubuntu-based Linux, thanks fam. c:

**Comment by Defman21** [comment]
@MrMetric thanks a lot man! Works fine for 0.10.8.

**Comment by shikhov** [comment]
Here are some examples for your inspiration. Hope to see them in new versions!
![image](https://cloud.githubusercontent.com/assets/9966764/19105266/9486ffd6-8afa-11e6-961f-18e61247e1c5.png)
![image](https://cloud.githubusercontent.com/assets/9966764/19105279/a1b26880-8afa-11e6-8578-cbf465fa73d0.png)
![image](https://cloud.githubusercontent.com/assets/9966764/19105282/a739a7d2-8afa-11e6-8e17-908dc2b4946f.png)
![image](https://cloud.githubusercontent.com/assets/9966764/19105296/b1487fd2-8afa-11e6-8174-b93d32b2729a.png)

**Comment by Geobert** [comment]
0.10.19, still here: DO something, either fix it or say you'll never fix it but do not let this bug without action

**Comment by john-preston** [comment]
@Geobert Some day there can be added some kind of "work mode", where there will be no bubbles at all. But currently no changes are planned.

**Comment by Geobert** [comment]
@john-preston thanks for the answer, I suggest closing this bug as "won't fix" then as this "work mode" thing is a different subject (here the demand is either revert to the old design or some slider in the setting to choose our own radius).

**Comment by KeatonKafei** [comment]
@john-preston Is there any reason other than personal preference for the bubbles? From what I can gather, of the major clients only this and the i/macOS ones use them. The web client uses a border radius of 2px.

Since this is a PC/Mac/Linux multi-platform client, forcing the (very distinct) Apple design language on everyone just seems like a very bad decision. It looks bizarre on Windows and Linux distributions. Maybe set the radius based on the OS the client is installed on?

If I'm beating a dead horse here, I agree with @Geobert  that the issue should be closed.

**Comment by john-preston** [comment]
@KeatonKafei A lot of design decisions are just personal preference.

Some day there will be a way to configure this I guess (along with some others geeky settings without UI), but not in the near month or two.

**Comment by MerbauOzLink** [comment]
Are developers gonna fix this awful thing?

**Comment by auchri** [comment]
> Some day...

:wink:

**Comment by Geobert** [comment]
0.10.21a 
Thank you for the material design, love the message's look. 
Maybe need some kind of color on header, it seems a bit visually lost with le contact col being white as well. 
Otherwise, good stuff.

**Comment by MasterGroosha** [comment]
Fixed after TDesktop redesign (0.10.22 alpha and newer)
