### ISSUE TITLE
[Feature request] "Alternative layout" option rework

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2236]
Hello.  
I think that option "Use alternative layout" which moves your messages to the left or to the right on wide screens is not intuitive. If user sees it for the first time, he may think "Hm..and how it will look like?" and after checking he might revert back to compare.

The thing I suggest is making this option not a check, but a separate modal view, which looks like this (sorry for ugliness, my art skills are something like zero): 

![image](https://cloud.githubusercontent.com/assets/2780044/16687130/50d69fce-451f-11e6-9b36-9a3b65a1558d.png)

This way one can easily compare between layouts and choose one which he likes more.

**Comment by XenHat** [comment]
I attempted to implement this a year ago but I wasn't successful in creating the UI for the user settings, I couldn't wrap my head around the framework the telegram code uses.

Heavily wanted feature in my circles.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/321 lol even older.
