### ISSUE TITLE
[Windows] Ugly Japanese characters rendering

### ISSUE THREAD

**Issue by ItachiSan** [telegramdesktop/tdesktop#2239]
### Steps to reproduce
1. Download Telegram Desktop on a Windows computer and use it.
### Expected behaviour

Font rendering should work normally, as in Linux.
See:
![linux](https://cloud.githubusercontent.com/assets/1223421/16708709/d8d2895a-45fc-11e6-8c47-5d9299b2e523.png)
### Actual behaviour

Japanese (Chinese also?) characters are displayed in a wrong way.
See:
![windows](https://cloud.githubusercontent.com/assets/1223421/16708716/e934a774-45fc-11e6-9eee-0fa9412a5362.png)
### Configuration

**Operating system:** Windows 10, standard edition (no Pro or N)

**Version of Telegram Desktop:** 0.9.56
### Logs

Seems not necessary, as it is a rendering issue.

Feel free to ask any useful information :smile:

**Comment by john-preston** [comment]
@ItachiSan I'm afraid this is a system fallback font that Qt selects :( Perhaps there is a way to specify it, by I currently don't know exactly, how. Can you post the characters here as well?

**Comment by ItachiSan** [comment]
@john-preston if the question is "what are the default fonts", they are *Segoe UI* and they are the default of Windows 10.
I tried changing the default fonts using the tool present here:
http://winaero.com/blog/how-to-change-system-font-in-windows-10/
but without success.

Also, I don't want to try to switch to Japanese characters as default. :laughing:

**Comment by john-preston** [comment]
Can you post the characters here as well? Looks like Qt doesn't select Segoe UI as a fallback font :(

**Comment by ItachiSan** [comment]
Do you mean the TTF?
I hope so; here is a zip of all seg*.ttf :smile: 
[Segoe.zip](https://github.com/telegramdesktop/tdesktop/files/356030/Segoe.zip)

**Comment by john-preston** [comment]
The test characters, that you used in the screenshots. As a string, here.

**Comment by ItachiSan** [comment]
Here it is:
わかりました

**Comment by Acris** [comment]
Chinese characters have the same problems, it's very ugly to shown.

**Comment by Acris** [comment]
This is some test characters:
你好世界
Thanks alot.

**Comment by fqdb** [comment]
![capture](https://cloud.githubusercontent.com/assets/2826336/19560454/d96fe398-96d4-11e6-8cf1-5601ba07ef8d.PNG)

**Comment by Aokromes** [comment]
#90 ?

**Comment by Aokromes** [comment]
#3575 generic of this.
