### ISSUE TITLE
Can't send wide images

### ISSUE THREAD

**Issue by Dvornik** [telegramdesktop/tdesktop#224]
Can't send wide images like this:
![image](https://cloud.githubusercontent.com/assets/1733249/4825732/458e7626-5f68-11e4-9fb3-bf22b10c4392.png)
from the clipboard with compession.

How to repid:
Copy the image, paste to chat and click "send" with compression. 

Tested on Win7x64, ver 0.6.5

**Comment by auchri** [comment]
@Dvornik it's fixed, pls close the issue

**Comment by Dvornik** [comment]
Good job!
