### ISSUE TITLE
Wrong size of local storage

### ISSUE THREAD

**Issue by srazi** [telegramdesktop/tdesktop#2244]
### Steps to reproduce
1. You need to have a big local storage, I'm not sure `big` means a lot of files or for example a local storage bigger than 1 GB 
### Expected behaviour

It should show correct size of local storage
### Actual behaviour

It shows negative size.
![bug-tdesktop-0 9 56](https://cloud.githubusercontent.com/assets/1328454/16760352/8fec4d26-4830-11e6-9f29-6b0f0098ce74.PNG)
### Configuration

**Operating system:**
Windows 10 - 64 Bit
**Version of Telegram Desktop:**
0.9.56 and also all other versions

**Comment by z3ntu** [comment]
Looks like there is a signed long in use. Max should be `2147483647` then (which is 2.14 Gigabytes).

**Comment by srazi** [comment]
It seems @z3ntu is right, and fix is as easy as changing `int32` to `qint64` at [localstorage.cpp#L586](https://github.com/telegramdesktop/tdesktop/blob/a89185565a233fb51e31558e18262ab6cb3865b7/Telegram/SourceFiles/localstorage.cpp#L586)

**Comment by z3ntu** [comment]
@john-preston This should be easy to fix, right?

**Comment by stek29** [comment]
And what if int64 overflows too? 
IMO it should be better to use float and show approximate size...

**Comment by puppy0cam** [comment]
This appears to still be an issue.
![image](https://user-images.githubusercontent.com/7194673/56937845-2f794100-6b42-11e9-9907-49e2e2bb38e9.png)
