### ISSUE TITLE
[Usability] Grouping in chats list

### ISSUE THREAD

**Issue by VladimirPobedinskiy** [telegramdesktop/tdesktop#2245]
Make possible create groups for chat's list - Family, Work, Bots and so on.
It can be as tree view (subitems with indent)
Each group can show total num of messages.
Each group can have icon and notification setting and may be muted.

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#1107
