### ISSUE TITLE
Client downloaded from official telegram website should not upgrade to alpha

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#2246]
### Steps to reproduce
1. Download the installer (0.56) from https://desktop.telegram.org/
2. Install it
3. Run the authentification and wait for the update check
4. It says we have an update, and it's alpha version

### Expected behaviour
Should not update to alpha from the official client

### Actual behaviour
I ended with 0.57 alpha

### Configuration
**Operating system:** Win 7 64bits

**Version of Telegram Desktop:**
0.56

**Comment by john-preston** [comment]
@Geobert It updates to the alpha version if you already had alpha installed to the same location. In that case you need to completely remove Telegram (uninstall or delete the program folder, if it was a portable version) and freshly install the stable version.
