### ISSUE TITLE
wider or with-adjustable chat message boxes

### ISSUE THREAD

**Issue by matanster** [telegramdesktop/tdesktop#2247]
I see little reason for having arbitrarily narrow chat boxes in the desktop UI, that cannot be tweaked on the fly. Sometimes it makes sense to read messages in a wider box (e.g. when some content that is meant to have distinct separate unwrapped lines, is pasted into the chat).
(I am using the linux version).

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#2060

**Comment by matanster** [comment]
I think I did

Sent from my mobile

-------- Original Message --------
