### ISSUE TITLE
telegram systray icon used wrong  background (only) after login.  (lilac instead of light grey)

### ISSUE THREAD

**Issue by alleehol** [telegramdesktop/tdesktop#2250]
### Steps to reproduce
1. Start telegram in a KDE Plasma session
2. logout
3. login

### Expected behaviour
Telegram systray icon uses same background color as rest of systray icons (i.e. the bg color of the panel)

### Actual behaviour
Telegram systray icon used liliac square as bg color (see attached screenshot)
Maybe it's transparent and the liliac is the color from desktop background picture

When I quit telegram and start it again, the systray icon background okay (see exptected behaviour)

### Configuration
Kubuntu 16.04 default (Plasma 5.5.5, KF5 5.18) Desktop, Intel Gfx, 27" 2560x1440 (std res)
Kubuntu 16.04 +ppa (Plasma 5.6.5, KF5 5.23) Laptop, Intel Gfx, 15" 1366x 768 (low res)

0.9.56 and a few versions before

![screenshot-telegram-wrong-bg-after-login](https://cloud.githubusercontent.com/assets/5500644/16870993/b9e5d984-4a84-11e6-965f-f88ed2e57876.png)

**Comment by alleehol** [comment]
I've changed the desktop background to blue, and after login the systray icon background is still lilac, not blue.  So either the color is picked from the login screen background image with is the default desktop background with is lilac below the panel.

**Comment by Aokromes** [comment]
same as #1059 https://github.com/telegramdesktop/tdesktop/issues/1059#issuecomment-164278384 ?

**Comment by Aokromes** [comment]
If you notice, the comment before you talks about corrupted background :)

**Comment by alleehol** [comment]
@auchri why did you close it?  #1059 is about not systray icon at all.   I see it but with wrong bg Color.
