### ISSUE TITLE
"Ask a question" simply doesn't works

### ISSUE THREAD

**Issue by andersbateva** [telegramdesktop/tdesktop#2254]
I asked at least 3 questions, on April and May, in English and Portuguese. They were never replied. I know, this support is made by volunteers... But I don't know how can one become a volunteer, and I see there are not sufficient volunteers to answer the questions. Appears it would be better to remove this feature, than keep it and makes users think it works!

**Comment by Kondra007** [comment]
That's **not** Telegram Desktop Issue. Maybe you should tell this in twitter to `@telegram` account?

**Comment by DaFri-Nochiterov** [comment]
@Kondra007 nice suggestion, to ensure you always will absolutely ignored by Telegram 😆

**Comment by andersbateva** [comment]
Done, asked on Twitter about the removal of the feature.
