### ISSUE TITLE
Notification badge size too large 

### ISSUE THREAD

**Issue by hazim1093** [telegramdesktop/tdesktop#2257]
After upgrading to 0.9.56 on ubuntu 16.04, The notification badge size appears to be quite large. 
It covers the telegram logo in the task bar.
![selection_082](https://cloud.githubusercontent.com/assets/11160747/16941208/21908e14-4da8-11e6-806d-ab94b904da13.png)

**Comment by john-preston** [comment]
@hazim1093 This always was like that for small tray icons, I think that count is more important, than the icon — so I wanted to make it readable.

**Comment by hazim1093** [comment]
Alright makes sense, It was a bit smaller before this update for me, on the bottom right corner
