### ISSUE TITLE
Last seen time not updated when reconnecting

### ISSUE THREAD

**Issue by matteocontrini** [telegramdesktop/tdesktop#2258]
#1211 was fixed but a new bug was introduced
### Steps to reproduce
1. Launch Telegram
2. Put it in the background
3. Put computer to sleep
4. Resume from sleep
5. Bring Telegram to the foreground and make it reconnect
### Expected behaviour

The last seen time of the users of the chats should be updated.
### Actual behaviour

A wrong time is shown, probably the last loaded from the previous Telegram session.
The only way to update the value (if the user stays offline) is to force close and restart Telegram.
### Configuration

**Operating system:** Windows 10

**Version of Telegram Desktop:** 0.9.57

**Comment by ars543210** [comment]
Same on Windows 10 Telegram Desktop Version 1.0.6

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by zeroxx1986** [comment]
I can confirm this is present in 1.9.8 also - has never been solved actually. I'm facing this issue each and every day. Telegram cannot connect after the computer comes back from sleep / hibernation (in my daily use case, it's hibernation, but I confirm sleep is affected also). Only workaround is to exit Telegram and start it again. It's really annoying..
