### ISSUE TITLE
Broken ASCII Character Support for "<<" / ">>"

### ISSUE THREAD

**Issue by phi1010** [telegramdesktop/tdesktop#226]
When sending the character sequences "<<" or ">>", all clients show a "�" symbol instead. "<>" or "><" are not affected, as well as alphanumeric characters before or after this sequence.
Receiving this sequence (via the android app) shows no problems.
In the input line, the characters are still readable.

My client runs under Ubuntu 14.04 with Unity.

**Comment by telegramdesktop** [comment]
Still showing "�"? Should be « and » now.
