### ISSUE TITLE
Not all packages with stickers are displayed

### ISSUE THREAD

**Issue by NightEugene** [telegramdesktop/tdesktop#2260]
I don't see images from some sticker packs. Only blanks instead this

![screenshot](https://cloud.githubusercontent.com/assets/19973416/16981223/4410dab4-4e72-11e6-9b3f-cb5a3efbfdbd.png)
![screenshot2](https://cloud.githubusercontent.com/assets/19973416/16981226/473b9a76-4e72-11e6-81d0-078a9edb7c3f.png)
### Configuration

**Operating system:** Debian GNU/Linux 8.4 (jessie)

**Version of Telegram Desktop:** 0.9.51

**Comment by z3ntu** [comment]
You should really upgrade Telegram Desktop to a newer version (either 0.9.57 if you live binary, or 0.9.56 if you live source)

**Comment by NightEugene** [comment]
I got Telegram 0.9.56, but it didn't help(

**Comment by matteocontrini** [comment]
I think you should give at least an example, otherwise the report is pretty useless...

**Comment by NightEugene** [comment]
What do you mean?
When I try to setup this https://telegram.me/addstickers/simpsons I don't see pictures in preview and while messaging.
When I try to setup this https://telegram.me/addstickers/simpsonfamily all right.

Now I have Telegram 0.10

**Comment by auchri** [comment]
@NightEugene maybe your Internet is slow?

Reopen this issues if you have the same problem in 1.0.29
