### ISSUE TITLE
when i was build MetaEmoji.xcodeproj  drop error

### ISSUE THREAD

**Issue by 314829125** [telegramdesktop/tdesktop#2261]
when  i was build MetaEmoji.xcodeproj  drop this error：
/usr/local/tdesktop/Qt-5.6.0/bin/moc -D_DEBUG -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -D__APPLE__ -D__GNUC__=4 -I/usr/local/tdesktop/Qt-5.6.0/mkspecs/macx-clang -I/usr/local/tdesktop/Qt-5.6.0/include/QtGui/5.6.0/QtGui -I/usr/local/tdesktop/Qt-5.6.0/include/QtCore/5.6.0/QtCore -I5.6.0/include -IGeneratedFiles/Debug -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/5.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include SourceFiles/_other/genemoji.h -o GeneratedFiles/Debug/moc_genemoji.cpp

moc: Cannot create GeneratedFiles/Debug/moc_genemoji.cpp
make: *** [GeneratedFiles/Debug/moc_genemoji.cpp] Error 1
Command /bin/sh failed with exit code 2

what should i do ？
help me， thanks！！！！

**Comment by 314829125** [comment]
![bd62e1d1-2d30-4f2c-8699-0a5c24bc73d5](https://cloud.githubusercontent.com/assets/12060830/17026897/4abe71be-4f94-11e6-8bcd-3a1107c53624.png)

**Comment by auchri** [comment]
Did you try some solutions from [google](https://www.google.at/search?q=moc+error+1)

**Comment by 314829125** [comment]
I tried, but I didn't use it. 
thanks

**Comment by ifreedom** [comment]
I also met it, and finally found that moc can't create directory, you need `mkdir -p GeneratedFiles/Debug` in Telegram directory. 

to @auchri : I think add this to Preprocess is a better choice.

**Comment by john-preston** [comment]
1. You don't need to build MetaEmoji project, results are already in the source code here.
2. It is legacy directory path used by Qt, because the moc files in theory can be different for different build configurations (because they respect preprocessor definitions), so originally Qt makes different moc files for different build configurations. But I used only the first one, Debug, for them for all configurations.
