### ISSUE TITLE
Phone numbers instead of nicknames

### ISSUE THREAD

**Issue by Djaler** [telegramdesktop/tdesktop#2263]
If I know the someone's phone number (for example, if he added me to his contacts), but he is not in my contacts, his phone displayed instead of his nickname. An example can be seen in the images.
![a86b9d4a-502b-11e6-82eb-b0e8d7ae4d39](https://cloud.githubusercontent.com/assets/7964583/17068399/6eeeff3e-5059-11e6-9c32-068e8f5e933e.png)
![a8691c28-502b-11e6-8383-83e31d30faac](https://cloud.githubusercontent.com/assets/7964583/17068400/6f096770-5059-11e6-9051-bcb988ea0ce1.png)

**Comment by Aokromes** [comment]
I think it's intended.

**Comment by 314829125** [comment]
you add him to you contact  ,  he  will  have nickname

**Comment by stek29** [comment]
Btw, this is not a duplicate of #1096.
But #2927 exists now, so it doesn't matter tbh.
