### ISSUE TITLE
Error in Apply the patch

### ISSUE THREAD

**Issue by vahidazadegan** [telegramdesktop/tdesktop#2267]
### Steps to reproduce
1. compile telegram in windows (VS2015)
2. Qt 5.6.0, slightly patched
3. Apply the patch

it showed this error messages -> // CopyFile2 returns HRESULT, not BOOL, so it should be tested for S_OK, not 0.
fatal: git apply: bad git-diff - expected /dev/null on line 423

### Configuration
Windows 10 
Visual studio 2015 Community 2015 Version 14.0.25422.01
Qt 5.6.0 

### Logs
**C:\TBuild\Libraries\qt5_6_0>cd qtbase && git apply  ../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff && cd ..**
../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff:12: trailing whitespace.
#Make this build use static runtime library.
../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff:13: trailing whitespace.
QMAKE_CFLAGS_RELEASE    = -O2 -MT
../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff:14: trailing whitespace.
QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += -O2 -MT -Zi
../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff:15: trailing whitespace.
QMAKE_CFLAGS_DEBUG      = -Zi -MTd
../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff:29: trailing whitespace.
    // CopyFile2 returns HRESULT, not BOOL, so it should be tested for S_OK, not 0.
fatal: git apply: bad git-diff - expected /dev/null on line 423

**Comment by auchri** [comment]
Try `cd qtbase && git git apply --whitespace=warn ../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff && cd ..`

**Comment by vahidazadegan** [comment]
It's not ok 
I got same error

**Comment by auchri** [comment]
Yes but the patch should have been successfully applied.
