### ISSUE TITLE
Newline in replyKeyboard not showing

### ISSUE THREAD

**Issue by HassanHeydariNasab** [telegramdesktop/tdesktop#2271]
### Steps to reproduce
1. make a bot!
2. send a replyKeyboard contains \n (newline)
3. compare message produced by clicking on Button and what is showing on Button

### Expected behaviour
It should show newline in text of the replyKeyboard 
## Example
first line
second line

### Actual behaviour
A space character showing in the replyKeyboard instead of a newline.
But when I click on it, it produces a message containing newline
## Example
first line second line

### Configuration
**Operating system:**
Ubuntu 16.04
**Version of Telegram Desktop:**
0.9.56

**Comment by john-preston** [comment]
@HassanHeydariNasab Yes, newlines are not supported in the buttons (at least in tdesktop), multiline buttons would significantly complicate the layout of the keyboards.

**Comment by HassanHeydariNasab** [comment]
Why you closed the issue?!
Android client works properly but Desktop client has this issue.

**Comment by stek29** [comment]
@HassanHeydariNasab can you please upload a screenshot (Android)?

**Comment by HassanHeydariNasab** [comment]
Android:
![android](https://cloud.githubusercontent.com/assets/8642505/17164117/58ae6aaa-53da-11e6-8702-00d4c26f98fa.jpg)

Desktop:
![tdesktop](https://cloud.githubusercontent.com/assets/8642505/17164194/118340b4-53db-11e6-9abf-6dca2fc8b8c5.png)
