### ISSUE TITLE
Problem in 4k display

### ISSUE THREAD

**Issue by alireza1375** [telegramdesktop/tdesktop#2272]
Hello,
I can't speak english very good if i have any problem excuse me.
I'm using Asus laptop (N552 VX). The screen quality is 4k. when i use 1920*1080 resolution my Telegram don't have good quality and near of letters has shadow. and When i use 4k resolution the letters are too small.
![untitled](https://cloud.githubusercontent.com/assets/14851447/17084647/62224650-51d8-11e6-96c9-db14ccfaf1c7.png)
Please fix this problem for next update.
thanks
Version of Telegram :  0.9.56

**Comment by jhasse** [comment]
I can't see anything wrong with the letters in your screenshot. What exactly do you mean?
