### ISSUE TITLE
Fontconfig and pulseaudio warning at startup

### ISSUE THREAD

**Issue by shakaran** [telegramdesktop/tdesktop#2273]
### Steps to reproduce
1. Download fresh Telegram
2. Execute Telegram Binary
3. Inspect the terminal output
### Expected behaviour

No warnings with fornts or pulseaudio
### Actual behaviour

Warnings and errors at startup
### Configuration

**Operating system:** Ubuntu 16.04 32 Bit

**Version of Telegram Desktop:** 0.9.56
### Logs

```
$ ./Telegram 
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
mv: ¿reemplazar '/home/shakaran/.local/share/applications/mimeapps.list', sustituyendo el modo 0644? (rw-r--r--) (s/n) s
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Conexión finalizada

AL lib: (EE) ALCcaptureAlsa_open: Could not open capture device 'default': Conexión rehusada
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Conexión negada

AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Conexión rehusada
```

**Comment by Aokromes** [comment]
part #517

**Comment by shakaran** [comment]
Why the issue is mark as duplicated and closed? The part related to pulseaudio is not in #517:

```
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Conexión finalizada

AL lib: (EE) ALCcaptureAlsa_open: Could not open capture device 'default': Conexión rehusada
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Conexión negada

AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Conexión rehusada
```

**Comment by stek29** [comment]
@shakaran then make a separate issue just about pulseaudio.

**Comment by shakaran** [comment]
@stek29 I cannot reproduce the pulseaudio warnings, so if I have again the issue, I will open another

**Comment by auchri** [comment]
>  I cannot reproduce the pulseaudio warnings

Why should I reopen the issue then? 🤣

**Comment by shakaran** [comment]
@auchri I said "if I have the issue *again*, I will reopen it". Ergo, if no issue, no reopen. But of course, it takes more than 6 months to resolve the issue, it is dificult know the bug status or if solved in new code each day. Also probably if it depends of third party problems or other bugs related to other software.
