### ISSUE TITLE
Telegram in the Gnome 3.20.2 tray bar

### ISSUE THREAD

**Issue by WyRe** [telegramdesktop/tdesktop#2275]
I'm running on ArchLinux with Gnome 3.20.2 I've installed telegram-desktop binary from AUR

https://aur.archlinux.org/packages/telegram-desktop-bin-dev/

And all of its dependencies, but I think from the last update, have failed notification tray icon as you can see in this pic:

http://i.imgur.com/AZA3RDU.png

Maybe could it be thing of 

https://aur.archlinux.org/packages/libappindicator-gtk3/

But I'm not sure. Thank you so much! :D

**Comment by auchri** [comment]
Please try the official version from https://desktop.telegram.org/

**Comment by WyRe** [comment]
Does its auto-updater works? I think this is the same https://aur.archlinux.org/packages/telegram-desktop-bin/

I prefer to use my distro repos :D

**Comment by auchri** [comment]
Since this is no official aur, you should ask the maintainer of the aur for help @ItachiSan

**Comment by ItachiSan** [comment]
@auchri @WyRe auto-updater is not included in my AUR packages.
Also, the client included is the official one, it is just repackaged.
The icon is broken in almost all packages, also the one built from scratch (I maintain a PKGBUILD for it).
Not sure why.
