### ISSUE TITLE
Telegram desktop not sending media files

### ISSUE THREAD

**Issue by ProtoxiDe22** [telegramdesktop/tdesktop#2279]
### Steps to reproduce
1. try to send any media file (voice message, images, video)
2. 
3. 
### Expected behaviour

the media files should be sent
### Actual behaviour

most of the times the loading icon pops up on the media message but never increase, and the file is never sent
### Configuration

**Operating system:**
windows 10 pro 64 bit
**Version of Telegram Desktop:**
0.9.56
### Logs

i don't exactly know what log to insert

**Comment by Aokromes** [comment]
you are using killer E2200 nic? if yes i suggest to change killer network drivers by atheros version, killer's driver have one huge memory leak causing a lot of problems.

https://www.google.es/search?client=opera&q=killer+network+memory+leak&sourceid=opera&ie=UTF-8&oe=UTF-8
