### ISSUE TITLE
Full screen applications minimized

### ISSUE THREAD

**Issue by Christilut** [telegramdesktop/tdesktop#228]
Some full screen applications, mostly games, get taken out of full screen mode when a notification happens. In my case I've noticed it in Battlefield 3 and 4. 

I think the notification should not happen if there is a full screen program running.

**Comment by Aokromes** [comment]
I agree for a setting for this.

**Comment by programcoder** [comment]
I also go for a setting

**Comment by jonnius** [comment]
On Ubuntu this also happens when watching a Movie in the Browser.
