### ISSUE TITLE
Is there any possibility to disable Edit/delete for an user in a Telegram supergroup?

### ISSUE THREAD

**Issue by iahoo** [telegramdesktop/tdesktop#2282]
Hi
I want to restrict an user in my Telegram super group to edit or delete his messages. Is there any possibility for this?

**Comment by stek29** [comment]
No. It's API issue.
You can make a bot which would delete all messages by that user just after receiving, and send them like "User: Message"
So user won't be able to edit or delete messages.

**Comment by stek29** [comment]
@auchri why no label? :)
