### ISSUE TITLE
select Multiple Files/Select All for Download/Delete/etc.

### ISSUE THREAD

**Issue by RaudelJr** [telegramdesktop/tdesktop#2286]
Sorry if this isn't the correct method to ask if this is possible.

Running Telegram Desktop Version 0.9.56

I was meaning to upload to a channel hundreds photos and invite family and friends to it so that they had access to view/download them as they liked to.

But downloading one at a time can take for ever.  Having the Auto-download is not always convenient.
Is there a way to select all images in a channel and choose to download them all at once?
or 
Is  that something still in the works for the future.

Also, at the moment, though selecting multiple files can be quite difficult if you mean to select a whole lot.  After selecting them it would be nice to get the option to download all selections that contain downloadable content.

Once again, my apologies if this is the incorrect place to mention this.

And thank you for your time in advance.

Raudel Jauregui, Jr.

### Expected behaviour
Am hoping to be able to Multi-Download messages with downloadable content.
Am hoping to be able to Select All Feature, (I currently beging by Click/drag/PgUp/or/PgDn to select faster.

### Actual behaviour
Selecting more than one message only allows you to forward or Delete. but not to download.

### Configuration
Windows 10.

**Version of Telegram Desktop:**
0.9.56

**Comment by auchri** [comment]
#818
