### ISSUE TITLE
[Enhancement] when a user is mentioned in a silent group, he/she should be notified regardless the group setting.

### ISSUE THREAD

**Issue by dmarrazzo** [telegramdesktop/tdesktop#2288]
### Steps to reproduce
1. User1 switch off the group notification
2. User2 send a message with a mention **"@user1"**
3. User1 has no evidence about the message that is mentioning him/her

### Expected behaviour
User1 should receive a notification and the telegram icon should have a badge with incoming message.
*Optionally 1:* to define a different sound for mentioning notification
*Optionally 2:* to use a different colour for the icon badge when a mention is present (yellow?)

### Actual behaviour
User1 has no evidence about the message that is mentioning him/her

**Comment by john-preston** [comment]
@dmarrazzo There should be a notification (sound+toast) is , but currently without a different or active color.

**Comment by dmarrazzo** [comment]
Hello @john-preston, I cannot see them in Android version and in the Desktop one either. (Please notice that the **group notifications are off**)

**Comment by ralesk** [comment]
I have notifications on, and pretty much all groups I'm in are muted.  This means I don't get any normal message notifications, but whenever I'm replied to or mentioned, I do, both on Android and on Desktop.

I have not messed with other notification settings deeper in the chat's settings, as far as I remember.

**Comment by dmarrazzo** [comment]
Wow

**Comment by dmarrazzo** [comment]
I finally was able to test it, and it works.
I will open a new issue because I'd like the same behavior for the reply message.
