### ISSUE TITLE
Telegram interrupts full screen games with notifications

### ISSUE THREAD

**Issue by ethaniel** [telegramdesktop/tdesktop#2290]
When I am playing a full-screen game in Windows and a incoming message comes in, the notification minimizes the game.

Notifications need to be not shown when there are other full-screen apps using the system.

**Comment by auchri** [comment]
If you are using, enable the "system notifications" in the settings. 

**btw. use the template next time.**

**Comment by ethaniel** [comment]
Windows 7 here. Sorry.

**Comment by kotep** [comment]
Also have this problem, had to turn off desktop notifications to prevent stealing focus.  Other messaging programs I use (Steam, Skype, Trillian) either hide notifications while screen is maximized or display without stealing focus.

**Comment by auchri** [comment]
#473 <=> #2290

**Comment by Yanrishatum** [comment]
Bump this as well. While for me it's not that big of a deal, considering I usually have telegram on secondary screen, on rare occasions that is a problem. There should be an option to disable notifications if there's something running in fullscreen.

**Comment by Nexen23** [comment]
Same here. It would be good to make `busy mode` as in skype to prevent notifications to popup while in fullscreen with another app.

**Comment by gorghino** [comment]
UP. Any progress?

**Comment by mbenlioglu** [comment]
Any progress on this?

**Comment by sgb** [comment]
This is the reason I'm not using the Telegram on my PC any more.

**Comment by 0trenixjetix** [comment]
Had this problem right now and i pissed off.

**Comment by sgb** [comment]
It's ok; I just stopped using Telegram.  A fix that works for everyone!

**Comment by gorghino** [comment]
Telegram 2.5.1 Windows 10
I'm playing GRIS - Fullscreen and I had Telegram notification on top of the game.
I don't know if it's relevant, but if I alt+tab and switch to desktop, I can listen to GRIS's music playing.

**Comment by gorghino** [comment]
This shall be closed when #10043 is added IMHO

**Comment by fireattack** [comment]
It's still an issue and very annoying.

**Comment by RememberTheAir** [comment]
by the way, as @auchri mentioned some years ago, enabling the setting to use native notifications _should_ help. I'm re-upping the comment because it's buried under all the rest of the conversation, it might help the people who land on this issue

**Comment by fireattack** [comment]
Yeah, native notifications don't have this problem. 

Unfortunately besides the bug, I actually prefer the way Telegram's notification looks.
