### ISSUE TITLE
Telegram build failure on Ubuntu

### ISSUE THREAD

**Issue by EhsaanF** [telegramdesktop/tdesktop#2291]
I'm trying to build Telegram Desktop in Ubuntu 14.04 by following instructions [in this page](https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-qtcreator.md). I've done everything, but when I'm trying to build, I get this error:
`./../codegen/Release/codegen_style Command not found`

I think my I've configured the project wrong, here is my Telegram.pro:

```
CONFIG(debug, debug|release) {
    DEFINES += _DEBUG
        OBJECTS_DIR = /home/ehsaan/TBuild/tdesktop/Linux/DebugIntermediate
    MOC_DIR = ./GeneratedFiles/Debug
    RCC_DIR = ./GeneratedFiles
    DESTDIR = ./../Debug
}
CONFIG(release, debug|release) {
#   DEFINES += CUSTOM_API_ID
        OBJECTS_DIR = /home/ehsaan/TBuild/tdesktop/Linux/ReleaseIntermediate
    MOC_DIR = ./GeneratedFiles/Release
    RCC_DIR = ./GeneratedFiles
    DESTDIR = ./../Release
}
```

Is that correct?

**Comment by EhsaanF** [comment]
OK I solved previous issue somehow, but now I'm getting this error:
`private/qfontengine_p.h: No such file or directory`

I double-checked Qt Engine, saw nothing weird, the project doesn't get built anyway, it's getting really boring.

P.S.: Building the project is a real pain in ass, could you make it more easier? :sob:

**Comment by rmoog** [comment]
I'm with @EhsaanF on this. I tried building on Gentoo and it drives me nuts.

**Comment by Aokromes** [comment]
#117
