### ISSUE TITLE
updateChannelPinnedMessage for broadcast channels

### ISSUE THREAD

**Issue by halaei** [telegramdesktop/tdesktop#2292]
Does the API support updateChannelPinnedMessage() for broadcast channels or it is just for supper-gropups?

In case it is supported can the current clients see the pinned message in broadcast channels, if somebody pin a message by a customized client?

Thanks for your time.

**Comment by Kondra007** [comment]
If I remember correctly, it's not possible to pin messages in channels, so why would API support this?

**Comment by stek29** [comment]
API has this method, but it haven't worked when I tried, can't remember exact error.
@Kondra007 API has methods to set or get bio for user. But it's not supported much.

**Comment by stek29** [comment]
This is api issue indeed, server won't allow you to pin a message in a channel.
