### ISSUE TITLE
All files (*.*) selection is not what you think outside of Windows

### ISSUE THREAD

**Issue by ralesk** [telegramdesktop/tdesktop#2293]
### Steps to reproduce
1. Open file selector on Linux (or, I assume, also on OS X)
2. Choose `All files (*.*)` for filter

### Expected behaviour
All files should appear

### Actual behaviour
Only files with at least one period character appear: and this is actually **correct**.

### Solution
Change the filter to be `*` instead of `*.*`, as this works even on Windows, and means what you think it should mean.

**Comment by john-preston** [comment]
Thanks for your report!

**Comment by ralesk** [comment]
Related, I just looked at the code hoping to create a PR of it, but I think my C++ and Qt is rusty enough that I have to leave it as it is.  But I found these in the code:

```	QString filter(qsl("Image files (*") + imgExtensions.join(qsl(" *")) + qsl(");;All files (*.*)"));```

Looks somewhat convoluted to add the `*` to the extensions this way pretty much every time they're used; maybe it'd be better to include the asterisk in the imgExtensions static string in the first place?  Also I noticed that while imgExtensions calls `QStringList::reserve(4)`, photoExtensions doesn't do `QStringList::reserve(2)`.

**Comment by Storm-Engineer** [comment]
On Linux, files don't need to have an extension, and as such, many doesn't have one, this *.* is not working.

Also, in Linux programs typically identify files by their MIME type rather than extension, which makes checking for extension needless, and is more failsafe too. I suggest that the filtering, like "image files" when posting a photo, is done my file headers instead of extensions.

**Comment by ralesk** [comment]
MIME Filtering is indeed superior, and apparently available in Qt since 5.2: http://doc.qt.io/qt-5/qfiledialog.html#setMimeTypeFilters

**Comment by john-preston** [comment]
This should be fine in 0.10.1 version.
