### ISSUE TITLE
Chat window layout inconsistent

### ISSUE THREAD

**Issue by ralesk** [telegramdesktop/tdesktop#2294]
I use the Android and the Desktop Telegram a lot, and there's something that throws me off all the time: on Android, the order of the buttons on the bottom of the chat window is the opposite of that of the desktop client.

![screenshot_20160803-151340](https://cloud.githubusercontent.com/assets/1564502/17368027/ba08977c-5992-11e6-96aa-6856ae91818d.png)
![screenshot at 2016-08-03 15-25-15](https://cloud.githubusercontent.com/assets/1564502/17368040/c4cd65ca-5992-11e6-90e3-583b248d40ed.png)

Are there any plans to consolidate this, one way or the other?

**Comment by Aokromes** [comment]
maybe a setting with 4 possible "locations"
left, right, top right, disable.

**Comment by ralesk** [comment]
Not sure I get it.  This was an issue about the _bottom_ bar:
Phone app is: Emoji, Input, Attachment, Voice
Desktop is: Attachment, Input, Emoji, Voice

The top bar has since become consistent with the Android app (Back, ProfilePic, Name, [Extras], Menu)

Not sure we'd want any of those on the bottom to move to the top at all, it's just that the order has been inconsistent since the beginning of times (and I'm aware that this will mess up people's muscle memory if it's fixed, but it's also been an open issue for **3.5 years** and it would have had a much smaller impact back then had anyone bothered to read it).  And adding settings has always been shot down by moderators and developer alike — it's really strange to hear a setting suggestion from one.

**Comment by Aokromes** [comment]
> Not sure I get it. This was an issue about the _bottom_ bar:
> Phone app is: Emoji, Input, Attachment, Voice
> Desktop is: Attachment, Input, Emoji, Voice
> 
> The top bar has since become consistent with the Android app (Back, ProfilePic, Name, [Extras], Menu)
> 
> Not sure we'd want any of those on the bottom to move to the top at all, it's just that the order has been inconsistent since the beginning of times (and I'm aware that this will mess up people's muscle memory if it's fixed, but it's also been an open issue for **3.5 years** and it would have had a much smaller impact back then had anyone bothered to read it). And adding settings has always been shot down by moderators and developer alike — it's really strange to hear a setting suggestion from one.

i mean a setting to put it on bottom left (android like) bottom right (current way), top right (where other icons are), disable.

**Comment by ralesk** [comment]
What does "it" refer to?  Or do you mean a setting for all the various icon components?
Either way, a setting here would feel superfluous.

**Comment by ralesk** [comment]
The issue still exists, it's not the user that lost interest, it's the devs that showed no interest since it was reported over four years ago.

**Comment by 23rd** [comment]
> The issue still exists, it's not the user that lost interest, it's the devs that showed no interest since it was reported over four years ago.

I'm afraid it will never be "fixed." Chat layout in [Telegram for macOS](https://macos.telegram.org) looks the same and I think this design decision is considered intentional.

**Comment by john-preston** [comment]
Yes, sorry.
