### ISSUE TITLE
libopus.so.0 cannot open shared object file

### ISSUE THREAD

**Issue by Babyy** [telegramdesktop/tdesktop#2295]
after Update to version 32.0.10.0 ; telegram no run ang get a error:

`./Telegram: error while loading shared libraries: libopus.so.0: cannot open shared object file: No such file or directory`

**Comment by john-preston** [comment]
@Babyy Does it show libopus as a dependency if you run "ldd Telegram" in Terminal? What OS / version do you try?

**Comment by john-preston** [comment]
@Babyy This was a problem in 32 bit Linux version, it should be fixed now. Please download the latest version from https://desktop.telegram.org and test if it does work for you now.

**Comment by Babyy** [comment]
@john-preston  yes, worked
