### ISSUE TITLE
Language & Problems

### ISSUE THREAD

**Issue by rasubuntu** [telegramdesktop/tdesktop#230]
Hello.
Thank you very much for the software Telegram. Really great.
Only issue is that I wanted to say about the version of the Linux desktop.
01- Korean language is not supported in the version of Ubuntu
02- Copy and paste off and not working ctrl+c and ctrl+v in the Persian language
03- Not deb version (Since Linux version is in development, so do not expect much from him)

Thank you so much for making this wonderful software ;-)

**Comment by tonghuix** [comment]
IME disabled in input, only english available. I use ibus-libpinyin in Debian.

**Comment by Riteme** [comment]
I met the same situation, too.
I can't input any Chinese characters in any textbox. I'm using ibus-pinyin.
Hope this bug can be solved as possible as early.

**Comment by sunng87** [comment]
This might be an ibus issue that it doesn't support qt5 applications.

**Comment by auchri** [comment]
So it's maybe fixed with 0.8.50? (IBus added to TDesktop)
