### ISSUE TITLE
Ugly rounded chat bubbles

### ISSUE THREAD

**Issue by LendLord** [telegramdesktop/tdesktop#2301]
Please remove ugly rounded chat bubbles

**Comment by Romansev** [comment]
+1 
Telegram is not iMessenger

**Comment by AlvaroLarumbe** [comment]
Or at least give an option to set rounded or squared.

**Comment by Lazek** [comment]
Yes, +1...

**Comment by gMickey** [comment]
+1
Back to 2000...

**Comment by Nipoto** [comment]
it's very bad :|

**Comment by hamsta007** [comment]
0.10.0 is a great disappointment. Almost all of my friends  is upset about this new chat design. Please fix.

**Comment by CyberMew** [comment]
The developer need to add options to make it customisable and configurable instead of a one size fit all. I don't think it is hard to add it to Options.

**Comment by Noiwex** [comment]
Yes it's indeed ugly. Even images are rounded, what were you thinking?

**Comment by Sithdown** [comment]
Remove that crap.

**Comment by zaps166** [comment]
Messages are too rounded, and images shouldn't be rounded (e.g. make it squared in half-rounded message bubble).

**Comment by Geobert** [comment]
already reported 28 days ago on beta channel, it seems they do not care
https://github.com/telegramdesktop/tdesktop/issues/2235

**Comment by Defman21** [comment]
I'm not sure why would you want to report issues twice.

https://github.com/telegramdesktop/tdesktop/issues/2235#issuecomment-237495952

**Comment by cawa-93** [comment]
+1

**Comment by Dabuka** [comment]
This looks terrible. Please reconsider this decision.

**Comment by KevinMarques** [comment]
+1
