### ISSUE TITLE
 Improve method to save content in our "personal cloud"

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#2302]
In version 3.11 on Android customized design of our chat to call it personal cloud. For ease of use could be added ways to help save content into our personal cloud.
### Steps to reproduce (current method)
1. Select a message from a chat, group or channel
2. Select forward message (from the button on the top bar or context menu)
3. Choose a recipient (our own chat)
### Expected behaviour

A simple method for storing contents of other chats, groups and channels:
• Add Entry "save to my cloud" from the context menu to select messages (and add button with the same function on the top bar)
• Pinned our own contact at the top of the contacts then select the option "forward Message" with the caption "my cloud".
### Actual behaviour

The saved (forwarding) message is the same for any contact.
### Configuration

**Operating system:**
Fedora Workstation 24 XFCE

**Version of Telegram Desktop:**
0.10

**Comment by Aokromes** [comment]
Implemented long time ago:
https://i.imgur.com/TM69eyx.png
