### ISSUE TITLE
Where is 0.10 release?

### ISSUE THREAD

**Issue by rinaldus** [telegramdesktop/tdesktop#2303]
Telegram 0.10 was released yesterday 3rd August, according to desktop.telegram.org. I don't see this release on GitHub. I'd like to update it on my Gentoo Linux, but I don't want to edit ebuild linked to releases on GitHub. Did you forget to add this release on GitHub or decided to cancel it for some important reasons?

**Comment by john-preston** [comment]
@rinaldus I've merged it with master, added a tag and created a release.

**Comment by rinaldus** [comment]
@john-preston Thanks!
