### ISSUE TITLE
Some bots broken after upgrade to v0.10

### ISSUE THREAD

**Issue by dverbru** [telegramdesktop/tdesktop#2305]
### Steps to reproduce
1. Start conversation with `@IconAIBot` and try "Show styles" command.
2. Compare the response in TD 0.10 and previous version or a mobile client.
### Expected behaviour

Response should look similar across clients.
### Actual behaviour

Message is corrupted in v0.10: no content, no command buttons UI, just reads "Empty Message".
### Configuration

Tested on Linux and Mac.

**Version of Telegram Desktop:** 0.10

**Comment by john-preston** [comment]
I've just tried on Mac, works fine for me:

![image](https://cloud.githubusercontent.com/assets/17900494/17416902/469c098a-5a88-11e6-8f3d-f6e3f2ca52f4.png)

I'll ask, maybe this is server side related.

**Comment by Babyy** [comment]
and i have this problem
OS: linux 32 bit
![img](https://i.imgsafe.org/3f09e7aec2.jpg)

**Comment by Kondra007** [comment]
Works fine for me, Kubuntu 16.04, TDekstop 0.10

**Comment by auchri** [comment]
@dverbru Fixed? It works fine for me

**Comment by dverbru** [comment]
No. I've just upgraded to 0.10.1 and no change. It looks like in Babyy's screenshot.

**Comment by dverbru** [comment]
I observed something else: when clicking "Show styles" command in that bot, the emoji selection dialog appears very briefly.
