### ISSUE TITLE
Add more than 4k member to channel from file

### ISSUE THREAD

**Issue by mortezaa** [telegramdesktop/tdesktop#2307]
hi 
how can I add more than 4k member with their mobile numbers to my channel only with a file like Excel or... and only with a few time :)  ??

**Comment by Babyy** [comment]
نمیتونی :) اگه مخاطبینی که قصد داری اضافه اشون کنی شماره شما رو نداشته باشند؛ اجازه ادد کردن اون افراد به شما داده نمشه و بلوک میشی

**Comment by mortezaa** [comment]
mer30 :)

**Comment by Aokromes** [comment]
#2003

**Comment by easy-o** [comment]
please,

can s.o. open a new issue for adding contacts from files?

**Comment by Babyy** [comment]
Use tg cli  for add from file ..

**Comment by mortezaa** [comment]
@marsII how can I install tg cli on windows ?
I have some problem on that!
and after that how I add ??
