### ISSUE TITLE
Move Messages Up/Down in Channels

### ISSUE THREAD

**Issue by RaudelJr** [telegramdesktop/tdesktop#2309]
Hi, 

I was hoping to provide a suggestion that can somewhat help with the design of Channels. 

Maybe a feature can be implemented as to allowing messages and uploads, to selected & be moved up/down in the thread, if possible even to move several selections at a time in groups. 

This will give the Channel Owner the ability to at least design in what order things are organized.

What do you think?

**Comment by stek29** [comment]
Well, it's not supported by API.
Use "Ask a question" button in settings or ping telegram on Twitter to suggest this.
