### ISSUE TITLE
User's name and surname in Settings are white

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#2311]
### Steps to reproduce
1. Open Settings
2. Look at your name / surname

![screenshot_20160805_105015](https://cloud.githubusercontent.com/assets/2780044/17430181/75e5c8e8-5afb-11e6-98b0-683535fa9ba7.png)

### Expected behaviour
Font color for name/surname is black

### Actual behaviour
Font color (at least, for me) is white. Maybe this field shouldn't follow OS theme colors?

### Configuration
**Operating system:** Kubuntu 16.04, Plasma DE  
**Version of Telegram Desktop:** 0.10 alpha

**Comment by john-preston** [comment]
@Kondra007 please check out this build:

https://updates.tdesktop.com/other/Telegram.zip

Does it work fine for you? Thanks.

**Comment by Kondra007** [comment]
@john-preston Could you please send me **Linux** binaries? I mentioned Kubuntu, not Windows.  

There're no such problems on Windows (at least, for me)

**Comment by john-preston** [comment]
@Kondra007 Wow, sorry, my mistake. I've built the Windows version because of a different issue, but there I've made an attempt to fix this as well, so I just asked to test it. I guess we'll see that in the next version then.

**Comment by Kondra007** [comment]
@john-preston No problem, I've tested your build on Windows and it works fine as usual :)   
Should I install Wine on Kubuntu and test this exe in Wine?

**Comment by john-preston** [comment]
@Kondra007 Only if your issue reproduces there :) I think this is not necessary, I'm sure it will be fixed in the next version.

**Comment by Kondra007** [comment]
Fixed in 0.10.1
