### ISSUE TITLE
Telegram WorkOffline Mode

### ISSUE THREAD

**Issue by MrMehdi** [telegramdesktop/tdesktop#2312]
hi
i have a question.
how to change telegram desktop source code to work in offline mode?
i have tdata folder from my oldest chat history.
how can i access to my oldest message and chat?
my account was removed and now i need tdata content 
anybody can help me?

**Comment by john-preston** [comment]
@MrMehdi I'm afraid you can't do that, tdata doesn't hold messages at all, only some cached images.

**Comment by MrMehdi** [comment]
tnx john-preston
really!! so you said all msg is online fetch from telegram servers?
so i have a question,when you work with telegram without access internet,you can saw msg you loaded before and your chat history,where this data saved?

**Comment by john-preston** [comment]
@MrMehdi Other Telegram apps store the messages for offline access, but Telegram Desktop works only with messages from the online cloud. While it runs it holds all the messages in memory, they all are forgotten once you quit the app.

**Comment by MrMehdi** [comment]
@john-preston tnx a lot
so i can change android version of telegram to access my old message??
i have a catch folder of my old msg for android version on my android device.
catch folder on android/org.telegram/ and content a lot file...
so how can i change telegram android source code to load my msg?

**Comment by MrMehdi** [comment]
@john-preston i can compile android version of telegram but i don't know how must be changed to load old message from catch,pls help me

**Comment by john-preston** [comment]
@MrMehdi Sorry, I know nothing about the android version and how it is built and working except that it does store messages in a database on the device.

**Comment by MrMehdi** [comment]
@ @john-preston  thx for your help :+1:
