### ISSUE TITLE
Illogical design of chat balloon

### ISSUE THREAD

**Issue by littleguga** [telegramdesktop/tdesktop#2314]
### Configuration
**Operating system:** Win7 64x
**Version of Telegram Desktop:** 0.10

Everything is square: telegram window, sections, inputs(search, message), panels, selections, but chat balloon is circled. It's really seems awful. 

Check old 'common style' vs new 'chat balloons'

![image](https://cloud.githubusercontent.com/assets/12018713/17437342/dbe15f52-5b25-11e6-98bc-460b52c08ac3.png)
![image](https://cloud.githubusercontent.com/assets/12018713/17437395/1eac7b14-5b26-11e6-82a3-1963a0d28dd8.png)

**Comment by littleguga** [comment]
@auchri which issue is already about this?

**Comment by auchri** [comment]
Because another issue about the rounded message bubbles already exists

**Comment by auchri** [comment]
Use search: #2235
