### ISSUE TITLE
My draft is rarely overwritten with an older version

### ISSUE THREAD

**Issue by jaekyeom** [telegramdesktop/tdesktop#2315]
### Steps to reproduce
I don't know, but I was writing a draft for my channel. And I didn't use my phone at that time.

### Expected behaviour
My latest draft should have been kept.

### Actual behaviour
The draft was replaced by an older one.

### Configuration
**Operating system:** OS X 10.10.5

**Version of Telegram Desktop:** 0.9.56

**Comment by auchri** [comment]
Please update to the latest version 0.9.10 and reopen the issue if the error occurs again.

**Comment by jaekyeom** [comment]
@auchri OK, I've been waiting for 0.10 on macOS app store.
