### ISSUE TITLE
"Improved" design for chats.

### ISSUE THREAD

**Issue by felixfoertsch** [telegramdesktop/tdesktop#2316]
Hey guys,

I just updated tdesktop to find out, that you changed the look and feel of the chat. You switched from the nice individual looking rectangular design to chat bubbles, but even without the thingy that shows thats a chat bubble. It's just rounded squares.

This reminds me of the widescreen issue, that was one of the most discussed issues here:
https://github.com/telegramdesktop/tdesktop/issues/1587

Just WHY? Please stop messing with stuff the user doesn't request changing. To me, it looks super ugly. Ofc I will get used to it. But why do you spend hours changing stuff like this in the first place? And if you change it, why don't you allow switching to this "new" design instead of forcing it again.

Please focus on technical issues and if you change the user interface, do it for a reason. Not just because.

### Configuration
**Operating system:**
macOS 10.11.6

**Version of Telegram Desktop:**
0.10

**Comment by felixfoertsch** [comment]
At least link to the issue. FFS
https://github.com/telegramdesktop/tdesktop/issues/2235

**Comment by auchri** [comment]
Use search before creating an unnecessary issue :wink:
