### ISSUE TITLE
Reply from Windows notifications

### ISSUE THREAD

**Issue by auchri** [telegramdesktop/tdesktop#2317]
### Steps to reproduce
1. Enable "Use Windows notifications" in the settings
2. Receive a new message
3. View the notification at the Windows Action center
### Expected behaviour

There should be an input field to quick reply to the new message.

![image](https://docs.microsoft.com/de-de/windows/uwp/design/shell/tiles-and-notifications/images/adaptivetoasts-xmlsample05.jpg)

See https://docs.microsoft.com/de-de/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts#inputs-and-buttons for examples.
### Actual behaviour

There is only the text of the new message.
### Configuration

**Operating system:** Windows 10.0.14393

**Comment by cawa-93** [comment]
+1

**Comment by iKenshu** [comment]
This should be good to have

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by auchri** [comment]
I don't know, try it

**Comment by tooomm** [comment]
Yes, it is still valid

**Comment by tooomm** [comment]
Yes, it is still valid

**Comment by Aokromes** [comment]
3.1.6
