### ISSUE TITLE
[feature] auto-dismiss for notification

### ISSUE THREAD

**Issue by xtumiox** [telegramdesktop/tdesktop#232]
Is it possible to hide desktop notification automatically after 5-10 seconds that are displayed? I think of Outlook when sends me notification for new mail or something like that.

**Comment by JuanPotato** [comment]
I think this has been implemented, my notifications go away automatically

**Comment by xates** [comment]
> Sometimes they won't be hidden, if app thinks you're "away". Is a feature though.

Would it be possible to add an option to disable this "feature"?

When watching videos/movies, reading or simply not interacting with the keyboard and mouse for a while, Telegram notifications stay on top and this is very frustrating.
