### ISSUE TITLE
Telegram icon on KDE's system tray appears blurry

### ISSUE THREAD

**Issue by pliniohcc** [telegramdesktop/tdesktop#2322]
Hi!

In my default KDE panel's height, Telegram icon in the system tray is the only one that appears blurry. It is good when I reduce the panel's height. Is it possible to make the tray icon's resolution better? I prefer my panel a little more high otherwise my other task manager icons seems too small. Screenshots below.

Thanks for the great work!!!

### Configuration
**Operating system:** Manjaro Linux 4.7.0-0 with Plasma 5.7.2
**Version of Telegram Desktop:** 0.10.1 alpha

### Screenshots
KDE default panel's height (icon blurry)
![tdesktop-systray-01](https://cloud.githubusercontent.com/assets/20880624/17459684/f95d568c-5c18-11e6-8d5e-a791d3c6d3f0.png)
![tdesktop-systray-02](https://cloud.githubusercontent.com/assets/20880624/17459682/f95c8e78-5c18-11e6-84ea-dd35822c2be4.png)

Reduced panel's height (seems good)
![tdesktop-systray-03](https://cloud.githubusercontent.com/assets/20880624/17459681/f95b832a-5c18-11e6-9234-f1f78956e6e7.png)
![tdesktop-systray-04](https://cloud.githubusercontent.com/assets/20880624/17459683/f95c9148-5c18-11e6-9607-6f3bbbf339c7.png)

**Comment by vmorenomarin** [comment]
Will be great a monochrome icon!!

**Comment by stek29** [comment]
#2230 duplicate
