### ISSUE TITLE
clipping number of messages through logo

### ISSUE THREAD

**Issue by amotbh** [telegramdesktop/tdesktop#2323]
### Steps to reproduce
1. Be in multiple large supergroups.
2. Have an excess amount of messages.
3. 
### Expected behaviour

Have a good total of unread messages, completely visible.
### Actual behaviour

http://i.imgur.com/RwheDXb.png
Numbers are clipping through the logo, breaking the telegram logo AND not showing the numbers properly
### Configuration

Windows 10 Professional

Telegram Desktop 0.10.1

**Comment by john-preston** [comment]
@stek29 1.5K tells you nothing more than "there are many", while the last digits also tell you when the count is changing, if you need that.

**Comment by amotbh** [comment]
@john-preston I'm not sure why anyone would like to know the final two digits on such a great number. Especially considering these are all actual messages. Imagine going to an online banking site where one was only able to see the final two digits on their balance. Absolutely ridiculous.

**Comment by john-preston** [comment]
@amotbh Right now you can notice by this counter if a message arrives. If it displays "1.5k" — you can't. And that is the only difference between them regarding the information they bring to the user.

Perhaps this will be changed in the future. But I don't see a lot of sense in that change, you'll just remove the only possible usefulness this counter can have.
