### ISSUE TITLE
Touchscreen scroll

### ISSUE THREAD

**Issue by horosgrisa** [telegramdesktop/tdesktop#2325]
### Steps to reproduce
1. Try to scroll messages in TD
2. All scrolled messages are selected
### VIdeo

https://www.dropbox.com/s/pont9fauizrkd3r/Screencast_07.08.2016_11%3A24%3A24.webm?dl=0
### Configuration

Arch Linux
TD: 0.10.1

**Comment by stek29** [comment]
Is touchscreen supposed to show pointer like a mouse?

**Comment by horosgrisa** [comment]
No. It's bug (or feature) of screencast program.

**Comment by RussianNeuroMancer** [comment]
I guess you have Wacom touchscreen and doesn't set "Gesture" "off" for wacom input driver: http://linuxwacom.sourceforge.net/wiki/index.php/Multitouch
