### ISSUE TITLE
Restore window position and size after click to close button

### ISSUE THREAD

**Issue by Bournwog** [telegramdesktop/tdesktop#2327]
I like to stay telegram into the tray. And when i resize window and click to close button (telegram minimize to tray) and after that open again i receive random windows size of app. I need that telegram restore window position and size after reopen from tray like a skype. 
Thanks

**Comment by stek29** [comment]
Please use issue template next time, important information is now missing.

OS type? OS version? TDesktop version?

**Comment by Bournwog** [comment]
Windows 8.1 x64 build 9600
TDesktop version 0.10.1
