### ISSUE TITLE
{Feature Request} Broadcast List Support

### ISSUE THREAD

**Issue by ByteShare** [telegramdesktop/tdesktop#234]
{Feature Request} Would like to see the ability to have broadcast lists on the desktop version like on the mobile.
Don't know if there is a reason this couldn't be done or not.

**Comment by telegramdesktop** [comment]
Server-side sync for broadcasts lists is not supported by API, client-side broadcast support in tdesktop is not on the task-list right now.

**Comment by mbnoimi** [comment]
Where we've to ask for this feature request?

**Comment by auchri** [comment]
On twitter: https://twitter.com/telegram

**Comment by SmartManoj** [comment]
[Broadcast Message in Telegram](http://smartmanoj.blogspot.com/2019/06/broadcast-message-in-telegram.html)
