### ISSUE TITLE
Sporadic extreme slowness to connect / download images

### ISSUE THREAD

**Issue by qgates** [telegramdesktop/tdesktop#2342]
### Steps to reproduce

Two issues, connected, sporadic
1. tdesktop installed on Win7, vanilla, wired LAN
2. fire up telegram, enter local passcode
3. Issue 1. Chat window sometimes takes ages (20+ seconds) to appear. Sometimes immediate
4. Issue 2. Pictures sometimes come down instantly, sometimes I get the 'X' spinner with blurred picture for 20+ seconds.

Often, issue 2 will become apparent over time. So pics load up quickly just after loading telegram, but minimising to tray for a while, someone sends me a pic, open it up and the pic just hangs there, blurred, for up to a minute. Then suddenly it will download.

Running tdesktop on Linux Mint and Mac OS machines (some wired, some wireless) behind the same router has no problems.

Checked TCP configuration (standard Win7), hosts file. Disabled windows firewall. 

tdesktop 0.10.1 Win7 (x64) Standard TCP connection.

Running tdesktop in debugmode reveals nothing unusual when comparing network log between the offending Win7 machine and a local linux machine working faultlessly.

Tried removing / reinstalling and also running a second copy portable. Same problems. Problem has exhibited on this machine since first installing tdesktop (since almost a year).

Frustrating! any ideas?

**Comment by stek29** [comment]
Please check #1320

**Comment by Zenexer** [comment]
@stek29 Pretty sure @qgates is talking about receiving images, not sending them.  I've encountered the second issue sporadically on every version of Telegram for the past year or so, on all three supported platforms.  Doesn't matter how fast or reliable the connection is; sometimes images just won't load properly.  Relaunching the app fixes it.  It's gotten better; it's relatively rare now, but it still happens from time to time, especially if my computer has been sleeping awhile.  Sometimes, if I wait long enough, the images will eventually load, but often they won't load until I restart the app.

**Comment by qgates** [comment]
@Zenexer Yes exactly. I'm seeing no major issue with uploads, except occasional slowness uploading large files.

The problem seems to be when downloading images, files or other media (including stickers and animated GIFs) after telegram has been logged in a while. I'll receive a pic while telegram is minimised, open it, then see the 'spinning X' for a good 20-30 seconds before the picture appears. Switching chats, or scrolling back through old chats with pics makes no difference. If I quit and restart tdesktop though, the problem goes away for a while.

Possibly related, I also often see a long delay when logging in to tdesktop initially. I'll type my passcode in and tdesktop 'hangs' for 20+ seconds before the chats appear.

In all cases I only see these issues in tdesktop running under Windows 7 (x64). Running behind the same router on OSx or Linux I see no delays logging in or with pics/other media appearing.

I've tried debug mode but nothing obvious appears wrong in the logs, when compared with a session running on a non-problematic OS.

**Comment by stek29** [comment]
Do you have any issues with notifications?
@Zenexer what if you test on nonwindows via other device? Not just other connection, but other "ethernet/wifi card"

**Comment by Zenexer** [comment]
@stek29 I'm not dual-booting.  These are all separate devices by separate manufacturers.  Apple, Lenovo, custom-built desktop with Intel NIC, etc.  They're all using the same Telegram account, and they're all using Telegram Desktop.  They get wiped frequently, so they're not junked up with garbage programs.  They're all up-to-date.  Doesn't seem to matter how I'm connected to the internet, what ISP I'm using, etc.

Native Windows 10 notifications often crash for me with the Anniversary Update.  The same version of Telegram Desktop running on an older version of Windows 10 doesn't encounter issues.  That's only on Windows, though, and there's a separate bug for that kicking around somewhere, I believe.  Otherwise, notifications are fine.

**Comment by john-preston** [comment]
@Zenexer Can you check 0.10.2 alpha on the anniversary update? It crashes as well?

**Comment by Zenexer** [comment]
@john-preston Let's move this to #2296

**Comment by john-preston** [comment]
@Zenexer At the bottom of https://desktop.telegram.org there are download links for it.

**Comment by Zenexer** [comment]
@john-preston I replied in #2296, since that's the issue for the notification crashing.

**Comment by qgates** [comment]
Back on topic ;-) The 'stuck' behaviour I'm seeing seems to apply to all situations where tdesktop needs to communicate with the network. So in addition to downloading new images I'll see the same delay checking for updates from within settings, or when uploading an image/file. Behaviour is always the same; after a period of inactivity, tdesktop lags on its initial network connection. Once the connection is made, downloads/uploads/whatever will generally happen quickly again, but when tdesktop is minimised for a few minutes, someone sends me a pic, I can be staring at the spinner/blurred image for 20+ seconds before the pic will appear.

As I said before, the strange part is I only see this behaviour in tdesktop under Win7, and not running the same build in Linux (Ubuntu/Mint) or OSx (latest). The irony is that the Win7 machine is networked over cat5, where the other (non-problematic) machines are wireless. In the case of the Mac, the wireless signal is poor as well :-)

**Comment by qgates** [comment]
A little more info. It's not just getting stuck downloading images, although this is the most common behaviour. Whenever tdesktop has been idling for a while and it needs to make a network connection, it can get 'stuck' and the entire tdesktop window becomes unresponsive.

For example I've encountered this when in Settings and I click 'Check for updates' or 'Change cloud password'

**Comment by qgates** [comment]
I tried the fix [mentioned here](https://github.com/telegramdesktop/tdesktop/issues/1320#issuecomment-205839763) and in addition to fixing #1320 it seems to fix this issue.

So I investigated went further and updated my Realtek RTL8111 (Realtek PCIe GBE Family Controller) drivers from those supplied with my mobo to the latest version available on Realtek's site. The new driver has reset NIC settings back to defaults (ie. re-enabling Large Send Offload) and tdesktop is working perfectly.

So I assume that there are a number of NICs out there with old drivers that have buggy Large Send Offload behaviour which close connections in error. To anyone encountering long delays downloading/uploading images and other media, or tdesktop getting 'stuck' communicating (leading to window not responding), I suggest the following:

1. If you can, update your windows NIC drivers to the latest available
2. If that isn't possible, use the workaround indicated in the link above

Footnote. To those with integrated NIC supplied on motherboard, be sure to check the NIC manufacturer site and not the mobo manufacturer site for drivers . Mobo makers are not updating their websites with the latest drivers for older mobos.

**Comment by fcFn** [comment]
Disabling LSO didn't help me, but disabling Interrupt Moderation seemed to help. Not sure if both LSO and IM should be disabled or only IM. Hope this helps someone.
