### ISSUE TITLE
tdesktop protected with local passcode won't receive messages until first signin

### ISSUE THREAD

**Issue by qgates** [telegramdesktop/tdesktop#2343]
### Steps to reproduce
1. Turn on local passcode
2. Quit tdesktop completely
3. Set 'launch minimised' and 'launch on startup'
3. Boot machine, log in. Telegram appears in tray

### Expected behaviour
Received messages should notify on the tray

### Actual behaviour
No messages are received, no notifications given. However, if I sign in once, then hit the padlock to lock, then 'X' to close to tray, everything works as expected.

### Configuration
**Operating system:**
Win7, x64, SP1

**Version of Telegram Desktop:**
0.10.1

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by john-preston** [comment]
@qgates This is intended. The auth key is encrypted by your passcode and the cloud can't be accessed until you enter it. But when you do the auth key is remembered in memory till the termination of the app.

**Comment by qgates** [comment]
@john-preston thanks for the info - understood.

It's a little weird with tdesktop running at startup to have to remember to unlock it for the first time before it will receive messages, especially since it **will** receive them when locked generally. It's a convenience thing.. is there value in leaving this open as a FR?

Could you take a look at #2342 as that's really been frustrating me for a while; appreciate some help in trying to nail what's going on there - thanks :)

**Comment by stek29** [comment]
@qgates if app can read your keys after restart without the passcode any other soft would be able to read it without passcode too.
Then why do we even need passcode if keys can be extracted without it? Fake security?
