### ISSUE TITLE
[CR] Make it possible to use only username / password for login (disable phone login option).

### ISSUE THREAD

**Issue by maxim-boligatov** [telegramdesktop/tdesktop#2344]
I understand that phone number helps to avoid bulk registration by bots.

But we have different ways for that - ip filters, captcha... in any case we can still use phone verification but for **registration** only.

It is very frustrating to use phone for login. I prefer to use username and password... And for now I am using that with 2-factor authentication. But I cannot disable login by phone number and use only password authentication.

Why do I need to disable phone logins? I cannot login in case when my phone is unavailable for any reason (discharged, left in a car / at home, busy by flashing firmware). Also I cannot login if I am abroad where I can use local mobile operator SIM. Even I can have 2+ different numbers (devices) and use any of them in my country.

Also it is obvious that phone is not secure way to authenticate due to SS7 issues... So we cannot trust it... final "guard" to prevent unauthorized access will still be a password...    

Not so important..  but sometimes mobile phone message can unveil the fact of login itself.

What is about account transferring? I am using Skype for 10 years with the same username and I changed my phone 3 times already for different reasons.

Microsoft can make good products... but with Skype they will lose... They dropped P2P, privacy...  So this acquisition finally will kill Skype totally... I am sure MS will not stop... So for me personally it is time to move on.. away from Skype.

Please make Telegram a bit more flexible and friendly for such users as I am.

P.S. I am not sure that desktop app repository is good start for this issue. But I have not found any more appropriate way to inform authors.

**Comment by DaFri-Nochiterov** [comment]
Has nothing with TDesktop. Please, contact support.
Settings -> Ask a Question
