### ISSUE TITLE
Opportunity to edit message on "ctrl+arrow up" (as well as in slack)

### ISSUE THREAD

**Issue by aseredenko** [telegramdesktop/tdesktop#2347]
Editing messages is very cool and useful feature, I propose to make it easier to use. I like realization of this feature in slack, when you press `ctrl + arrow up` you are able to edit previous message.

**Comment by john-preston** [comment]
@aseredenko Now you just press the arrow up (which is also like in Slack).

**Comment by aseredenko** [comment]
@john-preston Wow. thanks! I didn't know about this opportunity.
