### ISSUE TITLE
Never ending "recording audio" loop

### ISSUE THREAD

**Issue by fheuer** [telegramdesktop/tdesktop#2348]
### Steps to reproduce
1. Write someone to kindly reply random text to you within the next five to ten seconds
2. Start recording audio and wait for the reply
3. Audio recording will stop on your side but not on recipient side

### Expected behaviour
Record audio and send it

### Actual behaviour
When recipient sends you a text while you record audio the process of recording will be interrupted and no audio will be sent. Altough the status on the recipient side is still "recording audio...".

### Configuration
**Operating system: OS X El Capitan 10.11.6**

**Version of Telegram Desktop: Version 2.19.48909 for mac OS**

**Comment by john-preston** [comment]
@fheuer This is an issue for another OS X app, not Telegram Desktop.

You can see it on GitHub here: https://github.com/overtake/telegram

You can download and try Telegram Desktop here: https://desktop.telegram.org
