### ISSUE TITLE
Add an option to disable internal player in Telegram Desktop

### ISSUE THREAD

**Issue by ea4eoz** [telegramdesktop/tdesktop#2349]
### Steps to reproduce
1. Click in any video someone sent to you.
2. Try to do any other thing with your desktop while the video is playing
### Expected behaviour

Telegram Desktop should open an external player to display the video as it previously did.
### Actual behaviour

Telegram Desktop opens an internal player in full screen, blocking any iteraction with any other program making your desktop single task while playing the video, preventing you to continue to talk to your friends or just doing stuff. This is ok for a phone but **NO** for a Desktop. A checkbox must be placed in the configuration to disable internal player and use an external player just as previous versions did.
### Configuration

**Operating system: Linux Debian Jessie**

**Version of Telegram Desktop: 0.10.0**

**Comment by stek29** [comment]
You could use "Show in Folder".
IMO adding an ability to "pop out" the player into other window would be better than an option to disable it completely.

**Comment by ea4eoz** [comment]
I'd prefer to view videos in the player I'm used to than in Telegram's player.

**Comment by stek29** [comment]
Well, TDesktop is open source software, feel free to add the option and make a PR.

**Comment by ea4eoz** [comment]
I only want to return to the old behavior. It was just perfect.

**Comment by stek29** [comment]
But for me and lots of other users the new behavior is just perfect.

**Comment by ea4eoz** [comment]
That's exactly why an option should be added to the configuration panel: to choose the perfect settings for anyone.

**Comment by stek29** [comment]
But adding too much options is bad too.
Also, adding an option takes developer's time, which could (and should) be spend on something more important. 
This issue isn't really popular, got only one :+1: in 5 days.
That's why I asked you to make a PR.

**Comment by ea4eoz** [comment]
This is the typical response of a user asking a feature in a open source project: do it youself.

Sir, I'm not a programmer and a really few percentage of Telegram Desktop are. I only want to take your attention about a wondeful feature that was overriden with a horrible one. If people want to be monotask in their desktops that's ok. If the new feature continue to disturb me, I'll search for another Telegram client programmed in a more rational way.

Thank you for nothing.

**Comment by stek29** [comment]
Good luck in searching for other client :)
And please notify me when you find one, I'd like to see it.

**Comment by gowhari** [comment]
> But adding too much options is bad too.

I agree, but at least an option in a config file outside GUI is not bad. The internal player on my PC has no sound and I can't change it to system default player.

**Comment by john-preston** [comment]
@gowhari Does sound work in other places? (like sound notifications / voice message playing)?

**Comment by diazbastian** [comment]
An option "open with..." from the context menu for different multimedia content help solve this and other problems of choice by the user (or something similar to that option comes with uncompressed images).

 A use case is to open a video in an external player and use a sistem method for sharing

**Comment by Aokromes** [comment]
#1710 ?

**Comment by AlirezaHaghshenas** [comment]
The problems is not just the full-screen mode. Playing videos is a serious task, many players have been created and evolved to deal with different users' use cases. You can't just cover them all with just an internal player. For instance, vlc media player allows you to increase the volume beyond 100% which is useful for many poorly recorded videos. With an external player, you can drag the player to a different monitor and keep working with the messaging app, are you going to support all these scenarios?
The open in folder and then double-click scenario is frustrating if you want to play many videos.

In my opinion, Telegram is a fantastic messaging app, but the decision to include everything built-in is just wrong. It will take lots of developer time, and will just alienate the user experience. When the android version introduced the internal map, my brother sent me a location, which my slightly outdated app opened in google maps. It was off by a kilometer! The problem went away in later versions, but the bug sent me somewhere I really shouldn't have gone.

My suggestion is to add an option to disable every built-in non-messaging thing you add to your app. This way, people can continue using their preferred application for their own use case.

Thank you very much.

**Comment by BehnamEmamian** [comment]
What do you think about adding a new option like this
![image](https://cloud.githubusercontent.com/assets/9818491/22859323/d2e3b872-f12b-11e6-83d5-31fe441558f6.png)

**Comment by BehnamEmamian** [comment]
I have added this feature but it is rejected.

support me on this link https://github.com/telegramdesktop/tdesktop/pull/3004

**Comment by auchri** [comment]
FIxed #3021

**Comment by mbasaglia** [comment]
So it looks like there's that "hidden setting" added in the merge request.
How is that setting toggled?

**Comment by stek29** [comment]
@mbasaglia Open settings and type "videoplayer"

**Comment by AlirezaHaghshenas** [comment]
Is there any cheat-sheet for these hiddent settings?

**Comment by mbasaglia** [comment]
I think it's these https://github.com/telegramdesktop/tdesktop/blob/55e56a6788870e6d67d9938eaabdf87f2ebddb17/Telegram/SourceFiles/settings/settings_widget.cpp#L37

**Comment by Behnam-Emamian** [comment]
This feature is not working in version 1.6.3 anymore!!!

**Comment by john-preston** [comment]
@Behnam-Emamian It should work if the video is downloaded, but it can't work if the video was not downloaded and is streamed instead.

**Comment by Behnam-Emamian** [comment]
Ok, I see. Thanks for your prompt respond.
