### ISSUE TITLE
how to make telegram text linked with username?

### ISSUE THREAD

**Issue by icalhalim** [telegramdesktop/tdesktop#2351]
how to make telegram text linked with username?

**Comment by auchri** [comment]
Please explain what are you trying to do.

**Comment by icalhalim** [comment]
![this](https://cloud.githubusercontent.com/assets/20992967/17626512/bb268f00-60d7-11e6-8665-535e8b1aeac4.png)
ilinked to someone profile

**Comment by EhsaanF** [comment]
This can be done via @bold bot.
Simply type `@bold [My profile](https://telegram.me/myuser)` in chat, wait for the list and then choose "Custom", Tada!
