### ISSUE TITLE
Image preview not working for random links

### ISSUE THREAD

**Issue by LuukEsselbrugge** [telegramdesktop/tdesktop#2352]
### Steps to reproduce
1.  Copy image from url
2. Paste in telegram
3.  url does not show preview

### Expected behaviour
Url should show image preview

### Actual behaviour
Url does not show image preview
https://esselbr.nl/d/w7Y8q8.jpg

### Configuration
**Operating system: Windows**

**Version of Telegram Desktop: 0.10.1 **

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by auchri** [comment]
Works for me:
![image](https://cloud.githubusercontent.com/assets/5092164/17628500/d263b282-60b5-11e6-847d-a735410c9c09.png)

**Comment by LuukEsselbrugge** [comment]
Look's like it happens sometimes appears to be working again

**Comment by LuukEsselbrugge** [comment]
Seems like it is happening to random images for example: http://img.memecdn.com/star-killer_o_6079053.jpg Does not work

**Comment by LuukEsselbrugge** [comment]
@auchri I have included an image

**Comment by john-preston** [comment]
Loading image from link and attaching it to the message (the way it looks like in @auchri example above) is server side logic. If the server can't load and store the image (or failed to do) it is not attached.

Better to copy the image to clipboard and paste to the input field.

**Comment by bl4ckh47h4ck3r** [comment]
Its a serious problem. I am also facing it badly. My github account when shared it's not showing others pic instead of showing my profile pic
