### ISSUE TITLE
Ugly font for Persian/Arabic texts

### ISSUE THREAD

**Issue by EhsaanF** [telegramdesktop/tdesktop#2354]
### Steps to reproduce
1. Open Telegram Desktop
2. View an Arabic/Persian text
3. Throw it all in a pocket.
### Expected behavior

TDesktop must use configured default system font for Persian/Arabic texts, even for English characters.
### Actual behaviour

It insists in using Open Sans font for English characters and ugly font for Persian/Arabic text.
### Configuration

**Operating system:** Windows 8/Windows 10/Ubuntu 16.04.1/elementary OS 0.3.2

**Version of Telegram Desktop:**All versions ever released
### Shots

![image](https://cloud.githubusercontent.com/assets/2109385/17647401/0384e25c-6203-11e6-9dd2-9913dc20035f.png)
elementary OS 0.3 / TDesktop 0.10.1

As you can see, for italic text it uses a really ugly font :cry:

**Comment by Aokromes** [comment]
#90

**Comment by hosseinmoazami** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5172
