### ISSUE TITLE
Unlock code send to chat

### ISSUE THREAD

**Issue by Whitebock** [telegramdesktop/tdesktop#2358]
### Steps to reproduce
1. Open a chat
2. Long Standby (Unknown how long)
3. Insert unlock code

### Expected behaviour
The Telegram client should unlock.

### Actual behaviour
The code (or parts of it) are send into the last open chat.

### Configuration
**Operating system:**
Windows 10 x64
**Version of Telegram Desktop:**
Version 0.9.56

I tried to reproduce it myself, but never was able too so I didn't publish this report.
It just happened again but I cannot really say what was different.
I had multiple programs open and inserted my code quickly (I write four numbers on numpad and then press enter)
I saw that the textbox lost focus while writing, so I assume that the actual chat was getting the input.

**Comment by stek29** [comment]
But was code really sent to chat? I doubt you can focus on non-visible inputs.
Maybe other app gets the focus?

**Comment by Whitebock** [comment]
@stek29 yes, I can say for certain that it was send to the chat.
It happened to me three times in the last weeks, maybe even months.
In group chats it can [confuse](http://imgur.com/a/MgXD1) some people.

**Comment by stek29** [comment]
So, #622 isn't mac os x specific, it happens on all platforms.
And this issue is some kind of duplicate.

**Comment by Whitebock** [comment]
Alright, thanks!
