### ISSUE TITLE
[Feature Request] Add tree-like custom chat sorting

### ISSUE THREAD

**Issue by UnoYakshi** [telegramdesktop/tdesktop#2359]
# Gist
Since I'd started to use Telegram I've added tons of chats, groups, and conversations. It is really annoying to search for the exact chat, and it would be great to see some tree-like chat sorting. It would nice to have a possibility to separate groups and one-to-one conversations.
I know I am not alone with such an idea.

# Demonstration

### Custom Folder A

- Chat 1
- Chat 2

### Custom Folder B

- Chat 3
- Chat 4

### Converstations

- Custom Conversation Folder A

1. Chat with user 1
2. Chat with user 2

- Custom Conversation Folder B

1. Chat with user 3

**Comment by DaFri-Nochiterov** [comment]
#1107 :wink:

**Comment by UnoYakshi** [comment]
Are they custom or predefined?

**Comment by UnoYakshi** [comment]
Alright, thanks.
