### ISSUE TITLE
Deleting stuff in a supergroup for myself

### ISSUE THREAD

**Issue by Bradan** [telegramdesktop/tdesktop#2361]
### Steps to reproduce
1. User Alice creates a supergroup
2. User Bob joins the supergroup
3. Alice writes some stuff, Bob is not interested in or doesn't want to see and his children might see it, so he wants to delete that stuff on his device.

### Expected behaviour
Bob can not delete stuff that Alice has written.

### Actual behaviour
Bob should be able to delete any message, but just for himself if he is not an admin.

### Configuration
**Operating system:**
Android
Linux
probably All others, too.

**Version of Telegram Desktop:**
0.10.1

### Logs
Not necessary

**Comment by john-preston** [comment]
@Bradan Looks like a server side feature request. Currently supergroups have only single copy of data for all the participants, so no local ("for himself") deletion is possible.

**Comment by Bradan** [comment]
@john-preston: Yes it is a feature request, but also an issue. For this to work you could save the message id's which got deleted per user in the database. Usually the amount of deleted messages is much smaller than the amount of non deleted messages.

**Comment by john-preston** [comment]
@Bradan Anyway, this has nothing to do with Telegram Desktop, sorry.

**Comment by Bradan** [comment]
@john-preston where shall I report it then? I just found this tracker.

**Comment by stek29** [comment]
@Bradan use "Ask a question" button in settings
