### ISSUE TITLE
iphone 5s_by  hitting on sticker sign on text box of chat  , the app crash 

### ISSUE THREAD

**Issue by hamidehh** [telegramdesktop/tdesktop#2362]
### Steps to reproduce
1.type word  in a group and delete it by back space
2.  then hit on sticker sign on text box of chat
3. the app crash 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by hamidehh** [comment]
![photo_2016-08-17_11-15-05](https://cloud.githubusercontent.com/assets/21075244/17727082/1df0d752-646c-11e6-9238-e8b5c5f01939.jpg)

**Comment by stek29** [comment]
It's TDesktop repo. Please, use "Ask a question" button in settings to report this bug. You can also report it on Twitter.

**Comment by stek29** [comment]
Also, please note that I can't reproduce this. Maybe you should also tell iOS version, phone model and telegram app version?
But please don't do it here.
