### ISSUE TITLE
Doubtful privacy

### ISSUE THREAD

**Issue by rmoog** [telegramdesktop/tdesktop#2365]
Consider the following: https://www.eff.org/deeplinks/2016/07/russia-asks-impossible-its-new-surveillance-laws

How is this software going to provide privacy when the grandchildren of NKVD and KGB agents can read my lewd texts?

**Comment by john-preston** [comment]
@rmoog Russia can ask anything it likes, it has nothing to do with Telegram. No one can read texts from Telegram messages.

**Comment by rmoog** [comment]
@john-preston Aren't Telegram's servers in Russia?

**Comment by john-preston** [comment]
@rmoog Telegram doesn't have any servers in Russia.

**Comment by stek29** [comment]
Issue title can be confusing...
