### ISSUE TITLE
how fix windows platform qt static plugin not found?

### ISSUE THREAD

**Issue by Ass3mblage** [telegramdesktop/tdesktop#2368]
I Build Telegram Desktop with Visual 2015, but build failed with this error.
 unresolved external symbol "struct QStaticPlugin const __cdecl qt_static_plugin_QWindowsIntegrationPlugin(void)" (?qt_static_plugin_QWindowsIntegrationPlugin@@YA?BUQStaticPlugin@@XZ) referenced in function "public: __thiscall StaticQWindowsIntegrationPluginPluginInstance::StaticQWindowsIntegrationPluginPluginInstance(void)" (??0StaticQWindowsIntegrationPluginPluginInstance@@QAE@XZ)

It seems that qtwindows.lib doesn't contain _static_plugin_QWindowsIntegrationPlugin

**Comment by Ass3mblage** [comment]
Fixed. I forget configure qt before build.
configure -debug-and-release -force-debug-info -opensource -confirm-license -static -I "D:\TBuild\Libraries\openssl\Release\include" -L "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Lib" -l Gdi32 -no-opengl -openssl-linked OPENSSL_LIBS_DEBUG="D:\TBuild\Libraries\openssl_debug\Debug\lib\ssleay32.lib D:\TBuild\Libraries\openssl_debug\Debug\lib\libeay32.lib" OPENSSL_LIBS_RELEASE="D:\TBuild\Libraries\openssl\Release\lib\ssleay32.lib D:\TBuild\Libraries\openssl\Release\lib\libeay32.lib" -mp -nomake examples -nomake tests -platform win32-msvc2015

**Comment by auchri** [comment]
Thanks for sharing your solution:+1:
