### ISSUE TITLE
problem in adding contacts to my channel

### ISSUE THREAD

**Issue by sadeghi8579** [telegramdesktop/tdesktop#2372]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
I need to add my contacts to my channel even though if we are not mutual contacts.

### Actual behaviour
Telegram drop out again the contacts that are not mutual contacts and they dont have my phone number!

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by john-preston** [comment]
@sadeghi8579 It is a server side restriction and it has nothing to do with Telegram Desktop.

**Comment by sadeghi8579** [comment]
Ok thank U . is there a way to add contacts to the channel ?
