### ISSUE TITLE
Strange GUI Windows 10

### ISSUE THREAD

**Issue by Flozi95** [telegramdesktop/tdesktop#2373]
I've changed the Windows scaling settings from 150% to 125%. Since this change my GUI looks like this:
![image](https://cloud.githubusercontent.com/assets/1878362/17836751/d4386596-679d-11e6-84d7-071b665ef2d7.png)

Any idea/solution? :wink:

**Comment by stek29** [comment]
What if you change it in Telegrsm settings too?

**Comment by Flozi95** [comment]
Where should i change? :see_no_evil: I don't find a option for this.

**Comment by gandreadis** [comment]
I've got the same problem (similar UI glitches) on Windows 10 as well, without even having changed the Windows zoom settings recently. I've tried reinstalling, but the glitches are still present, and they make using the app quite difficult. Any ideas on what the cause might be (and how to fix it)?

**Comment by gandreadis** [comment]
Fixed itself for me seemingly, the glitches are gone now... No idea what the cause was.

**Comment by patrickklug** [comment]
same problem here. Disabling high DPI scaling for the app does not seem to work either. I seem to be stuck with this. Makes the app unusable.
