### ISSUE TITLE
Download sometimes glitch

### ISSUE THREAD

**Issue by JGBX** [telegramdesktop/tdesktop#2375]
### Issue, some possibles solutions and suggestions

When you download bigs files some time telegram just glitch, keep download forever and don't finish to donwload even when just need the last 100KB to do it, and you need to start to download over again.
1. My suggestion is don't delete any donwload and ask if you want to delete, resume or start over again when you try to download again.
2. Also telegram can download everything adding the extension .tmp until is full downloaded, then just quit this extension and getting the propper type of file extension.
3. Would be nice if the app can show the speed (KB/s) when you donwnload or upload something, you can see how Plus Messenger for android (fotk of telegram) do it.
4. This is a beautifull idea, but i'm not sure if is possible. but some kind of way to increase the download spped.
### Expected behaviour

N/A
### Actual behaviour

N/A
### Configuration

**Operating system:**
Windows 10

**Version of Telegram Desktop:**
0.10.1
### Logs

N/A

**Comment by stek29** [comment]
Please look at #809 and #1965

**Comment by Aokromes** [comment]
#1703
