### ISSUE TITLE
USER_NOT_MUTUAL_CONTACT error when adding user back to group

### ISSUE THREAD

**Issue by adrianopol** [telegramdesktop/tdesktop#2378]
I cannot add user back to the group.

### Steps to reproduce
1. Create a group.
2. Add contacts to it.
3. One contact leaves the group. I see his phone number, he also sees mine.

### Expected behaviour
I can add this contact back to the group.

### Actual behaviour
Telegram-desktop shows an error:
> Sorry, if a person leaves a group, only a mutual contact can bring them back (they need to have your phone number, and you need theirs).

Logs:
> RPC Info: error received, code 403, type USER_NOT_MUTUAL_CONTACT, description:  (facade.cpp : 529)
> RPC Error: request 5110 got fail with code 403, error USER_NOT_MUTUAL_CONTACT

### Configuration
net-im/telegram-desktop-0.9.56

### P.S.
telegram-android also shows an error, but another one:
> Sorry, this user decided to leave this group, so you cannot invite them back here.

**Comment by auchri** [comment]
Yes, that's the spam protection.

**Comment by adrianopol** [comment]
Why do I have a `USER_NOT_MUTUAL_CONTACT` error while he is? Also, where can I read about it? There is nothing in official documentation.

**Comment by adrianopol** [comment]
So, there is a bug anyway: either in text of the error message (we *are* mutual because we do have each other's phone numbers), or in the inappropriate `USER_NOT_MUTUAL_CONTACT` error.
