### ISSUE TITLE
[Mac Client] After switching from external non-Retina display to Retina, images are pixelized

### ISSUE THREAD

**Issue by artyom-veselov** [telegramdesktop/tdesktop#2383]
### Steps to reproduce
1. Launch telegram on Retina display
2. Drag telegram to external non-Retina display (or just close Mac so that external non-Retina display will be the only output video device)
3. Switch to Mac's Retina display again (or open Mac and turn off external non-Retina display so that the only output video device will be Mac's Retina display)
### Actual behaviour

Avatars and all images (like ✓ icon of send message) are pixelized.
### Expected behaviour

Images should be adjusted so that they will not be pixelized on Retina display.
### Configuration

**Operating system:**
OS X 10.11.5 (15F34)

**Version of Telegram Desktop:**
v 0.10

**Comment by auchri** [comment]
#1121
