### ISSUE TITLE
Telegram Desktop does not focus on password field after launch via Start Menu

### ISSUE THREAD

**Issue by dem23step** [telegramdesktop/tdesktop#2384]
### Steps to reproduce
1. Press Start button
2. Type `Telegram`
![untitled](https://cloud.githubusercontent.com/assets/18378425/18025201/70bee0ee-6c2a-11e6-8bdb-75da8427ee34.png)

3. Choose Telegram

### Expected behaviour
![image](https://cloud.githubusercontent.com/assets/18378425/18025191/3ec7161a-6c2a-11e6-8f60-75134c6351a0.png)

### Actual behaviour
![untitled](https://cloud.githubusercontent.com/assets/18378425/18025192/45dca4e2-6c2a-11e6-9404-d5702cf9d9a3.png)

### Configuration
**Operating system:**
Windows 10 Pro 64-bit

**Version of Telegram Desktop:**
version 0.10.1

**Comment by dem23step** [comment]
Same behaviour on `Ubuntu 16.04 LTS` with `Telegram Desktop 0.10.1` installed.

**Comment by stek29** [comment]
Isn't it #622 duplicate?
