### ISSUE TITLE
Leaving private groups but they are still in the list

### ISSUE THREAD

**Issue by foremtehan** [telegramdesktop/tdesktop#23866]
### Operating system

Windows 10

### Version of Telegram Desktop

3.4.3

### Installation source

Static binary from official website

**Comment by bymaer** [comment]
The same situation

**Comment by Aokromes** [comment]
i don't think this is a bug.

**Comment by RememberTheAir** [comment]
@Aokromes why?

**Comment by foremtehan** [comment]
@Aokromes when you leave the group, it should be disappeared from the list, look at the video, it remains in the list
