### ISSUE TITLE
PageUp/PageDown stopped working inside chat (messages) view

### ISSUE THREAD

**Issue by ratijas** [telegramdesktop/tdesktop#23867]
### Steps to reproduce

1. Open any chat / channel, which has some history to scroll
2. Clean the message input field, so that there is no text no navigate with those keys.
2. Press PageUp/PageDown.

### Expected behaviour

The view should scroll, just like the chat list view.

### Actual behaviour

It doesn't scroll.

### Operating system

Arch Linux, KDE/Plasma/X11

### Version of Telegram Desktop

3.4.3

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Can you reproduce on official binary?

**Comment by john-preston** [comment]
@ratijas there was a bug in Qt 6.2.0 that disabled PageUp/PageDown scroll. It was patched in Qt for the official builds using Qt 6.2.0 and it was fixed in Qt 6.2.2. I'm sure it is that bug and you should use the official build from https://desktop.telegram.org or update you Qt version.

Please confirm that it isn't reproduced in the official build.

**Comment by ilya-fedin** [comment]
No, it's not fixed in Qt 6.2.2, we still patch Qt 6.2.2 for PgUp/PgDown to work

**Comment by john-preston** [comment]
Indeed, the fix is merged for the Qt 6.2.3 upcoming release:

https://bugreports.qt.io/browse/QTBUG-97908

**Comment by john-preston** [comment]
Then I guess the only option is to migrate to the official build.

**Comment by ratijas** [comment]
Why is it every time I have problems with Telegram Desktop, turns out it is already fixed in official builds, but not upstreamed yet xD

wait_it_is_all_patched__always_have_been.jpg

Thanks for the explanations. I guess we can close this now as #resolved #upstream.

By the way, Qt 6.2.3 is planned for 18.01.2022, which means hopefully it'll be available on rolling distros by February.
