### ISSUE TITLE
Dragging instead of Scrolling

### ISSUE THREAD

**Issue by some0nenew** [telegramdesktop/tdesktop#23872]
### Steps to reproduce

Move window by dragging the title bar.
Scrolling through the contacts list or normal chat log while moving the mouse.

### Expected behaviour

Normal scrolling.

### Actual behaviour

I start dragging the window instead of scrolling, the mouse cursor changes from "normal" to "drag mode" and i don't scroll anymore but drag the window around.

Video quality is a bit shitty i know, but it should get the problem across i think:

https://user-images.githubusercontent.com/87366654/148690847-e40a576f-4a22-4de6-aa5a-03c3d4d316ea.mp4

The problem is Present for a long time by now and i hoped it would just disappear on its own at some point. 

I have the setting for moving and resizing windows by holding down "alt" enabled, maybe that is to blame. But even setting the "alt"+"left click" action to nothing or changing the modifier key to "meta" doesn't solve the problem.  

### Operating system

Operating System: Manjaro Linux ; KDE Plasma Version: 5.23.4 ; KDE Frameworks Version: 5.89.0 ; Qt Version: 5.15.2 ; Graphics Platform: X11 

### Version of Telegram Desktop

3.4.0-1 (from the Manjaro community rep.)

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
#10348

**Comment by some0nenew** [comment]
So that's a know problem already, i guess i can close the issue then?
Thanks a lot anyway
