### ISSUE TITLE
Telegram doesn't respect QT_QPA_PLATFORM=wayland anymore

### ISSUE THREAD

**Issue by eyalzek** [telegramdesktop/tdesktop#23877]
### Steps to reproduce

Run telegram with native wayland, e.g:

```bash
env QT_QPA_PLATFORM=wayland telegram-desktop -- %u
```
either from cli or by updating the desktop file.

This worked up until 3.4.3.

### Expected behaviour

Telegram should run as a wayland application.

### Actual behaviour

Telegram runs as X

### Operating system

Debian 11

### Version of Telegram Desktop

3.4.3

### Installation source

Apt installation from Debian sources.

### Logs

```shell
$ env QT_QPA_PLATFORM=wayland telegram-desktop -- %u

(telegram-desktop:10145): Telegram-WARNING **: 12:27:53.254: Application has been built with foreign rlottie, animated emojis won't be colored to the selected pack.

(telegram-desktop:10145): Telegram-WARNING **: 12:27:53.254: Application was built without embedded fonts, this may lead to font issues. On Debian-based systems, make sure you have the fonts-open-sans package installed
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
error: : cannot open
error: : cannot open
error: : cannot open
qt.svg: Error while inflating gzip file: SVG format check failed
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
```

**Comment by ilya-fedin** [comment]
> Static binary from official website

> ```shell
> (telegram-desktop:10145): Telegram-WARNING **: 12:27:53.254: Application has been built with foreign rlottie, animated emojis won't be colored to the selected pack.
> 
> (telegram-desktop:10145): Telegram-WARNING **: 12:27:53.254: Application was built without embedded fonts, this may lead to font issues. On Debian-based systems, make sure you have the fonts-open-sans package installed
> ```

It seems there's some confusion since static binary from official website can't print these lines.

**Comment by eyalzek** [comment]
Hey, sorry. It's installed via apt (debian sources):
```bash
$ apt policy telegram-desktop 
telegram-desktop:
  Installed: 3.4.3+ds-1
  Candidate: 3.4.3+ds-1
  Version table:
 *** 3.4.3+ds-1 500
        500 http://deb.debian.org/debian testing/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by ilya-fedin** [comment]
Can you fix info in your first post?

**Comment by hgaiser** [comment]
I am seeing the same thing on Arch Linux:

```
env QT_QPA_PLATFORM=wayland telegram-desktop

(telegram-desktop:141091): Telegram-WARNING **: 16:24:34.392: Application was built without embedded fonts, this may lead to font issues.
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
QCoreApplication::postEvent: Unexpected null receiver
```

This was working on 3.3.0 and lower. Might be that the switch to Qt6 caused this?

**Comment by ilya-fedin** [comment]
Partially yes. Qt 6 started defaulting to Wayland on GNOME what caused a lot of complains and GNOME was blacklisted i tdesktop code.

**Comment by hgaiser** [comment]
I suppose you mean [this](https://github.com/telegramdesktop/tdesktop/commit/102c0a96ed5cbc1288e1654b7e12811f1ea378b5) ?

**Comment by hgaiser** [comment]
I build telegram-desktop from source, excluding [this](https://github.com/telegramdesktop/tdesktop/commit/102c0a96ed5cbc1288e1654b7e12811f1ea378b5) commit and it seems to work fine for me. What were the issues you encountered on Wayland + Gnome? Or was it a specific Gnome version? Regardless, should we allow to override defaulting back to X? As it seems to work in my situation.

**Comment by ilya-fedin** [comment]
Flickering, another cursor theme & size, troubles with menu positions (can be out-of-screen or not visible at all if Telegram window is fullscreen)

**Comment by hgaiser** [comment]
Hmm interesting, haven't noticed any of those issues yet. I'll keep an eye out for them. Were they incredibly noticeable, or very rare? The only issue I noticed (though that was also present in earlier versions) is that the default interface scaling is set to 200% (possibly because I'm using 150% fractional scaling?), making the cursor twice as big (the rest of the interface seems normally sized to me).

Is there something I can do to help debug these issues?

Would a PR that respects `QT_QPA_PLATFORM` again, defaulting to XWayland like before, be accepted?

**Comment by ilya-fedin** [comment]
> Were they incredibly noticeable, or very rare?

https://github.com/telegramdesktop/tdesktop/issues/17468#issuecomment-1003306225
https://github.com/telegramdesktop/tdesktop/issues/17481

Firstly I thought it's an old bugged version of GNOME, but then a person with GNOME 41 confirmed it's still an issue.

> making the cursor twice as big (the rest of the interface seems normally sized to me).

Well, it's not scale, Qt just has another default cursor size and doesn't respect GNOME settings on Wayland

> Would a PR that respects `QT_QPA_PLATFORM` again, defaulting to XWayland like before, be accepted?

I don't know, ask @john-preston

**Comment by john-preston** [comment]
@hgaiser Yes, QT_QPA_PLATFORM should be respected, if set.

@ilya-fedin suggested a to fix it in the code from the mentioned above commit in such way:

if (Platform::DesktopEnvironment::IsGnome() && qEnvironmentVariableIsEmpty("QT_QPA_PLATFORM")) ...

You can PR such change.

**Comment by hgaiser** [comment]
Making the PR too easy :p 

https://github.com/telegramdesktop/tdesktop/pull/23897 should fix this issue.
