### ISSUE TITLE
Icon disappears from desktop after update

### ISSUE THREAD

**Issue by russiandesman** [telegramdesktop/tdesktop#23878]
### Steps to reproduce

1. Install telegram-desktop via snap
2. Create desktop shortcut for it via "add to desktop" from start menu (XFCE, but should be relevant for other desktops)
3. Everything fine
4.  .....
5. update happen
6. Icon on desktop replaced to default one

### Expected behaviour

Icon remains the same after snap update

### Actual behaviour

Icon replaced by default one

Observation:
/var/lib/snapd/desktop/applications/telegram-desktop_telegram-desktop.desktop file contains icon link as:
Icon=/snap/telegram-desktop/3544/meta/gui/icon.png

After adding it to desktop this file actually copied to ~/Desktop

After upgrade, file on desktop remains as it is, as snap does not track copying, which is expectable.

Easy way to avoid this annoyance is to put "Icon=/snap/telegram-desktop/**current**/meta/gui/icon.png" to .desktop file

### Operating system

Xubuntu 20.01

### Version of Telegram Desktop

3.4.3

### Installation source

Snap

**Comment by ilya-fedin** [comment]
The current path is the right one. I think the bug is on XFCE or snapd side so that one of them doesn't inform the DE after changing the files or the DE itself is not capable of updating the icons on-the-fly (you need to log out and log in after each update then).

**Comment by russiandesman** [comment]
There is no bug in DE nor snapd.
Actually none of them will be able to track all file copying operations.
I am talking about different thing. Path with numbers valid only for current release, while path with **current** remains valid for any release (like /home/user vs ~). So if somebody _copies_ .desktop file and uses it on their own -- why make them cry after each update?

**Comment by ilya-fedin** [comment]
You shouldn't copy it, this is not by design of snapd

**Comment by ilya-fedin** [comment]
> why make them cry after each update?

It looks like `${SNAP}` in the source code and then snapd does autoreplace

**Comment by russiandesman** [comment]
> You shouldn't copy it, this is not by design of snapd
Ok, that's maybe about XFCE vs snapd.
It is pretty straightforward action -- place shortcut to desktop. Seems like under the hood XFCE uses copy for this, as none of files in ~/Desktop are links of any kind. And seems like since this is done, snapd knows nothing about copy of telegram-desktop_telegram-desktop.desktop
And this can be mitigated as described above.

**Comment by ilya-fedin** [comment]
> Ok, that's maybe about XFCE vs snapd.

It's more likely about your login shell. snapd installs a script to /etc/profile.d that adds its directories to XDG environment variables. If you're using not bash, that may not work. And a lot of other scripts from that directory.

> It is pretty straightforward action -- place shortcut to desktop.

You can use `ln -s`. KDE even let to do that from UI.

> And this can be mitigated as described above.

I don't think this should be mitigated at tdesktop side since this would be a hack. This should be mitigated in either snapd or XFCE.

**Comment by russiandesman** [comment]
Ok, understood, thanks!
