### ISSUE TITLE
Telegram icon is shaking

### ISSUE THREAD

**Issue by makhalin** [telegramdesktop/tdesktop#23876]
### Steps to reproduce

On my Ubuntu 21.10 with GNOME Shell 40.5 Telegram icon in dash is shacking. I can't figure out why and how to disable it.

![Screencast_10-01-22_12_24_33](https://user-images.githubusercontent.com/2647652/148745307-c65cffb8-2ac7-4e4f-9186-97ac87101416.gif)

### Expected behaviour

Telegram icon is not shaking and there is an option to disable it.

### Actual behaviour

Telegram icon is shaking and it is impossible to turn it off.

### Operating system

Ubuntu 21.10

### Version of Telegram Desktop

3.3

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Latest version is 3.4.3, please upgrade before reporting

**Comment by makhalin** [comment]
3.4.3 has same problem

**Comment by ilya-fedin** [comment]
Maybe such an option is in GNOME/dock settings?

**Comment by russiandesman** [comment]
Hello @makhalin, could you please check one my suspicion?
check if telegram-desktop_telegram-desktop.desktop file in /home/<you>/Desktop contain Icon=/snap/telegram-desktop/<XXXX>/meta/gui/icon.png string, where XXXX is digits.
If so, could you please replace digits to word "current" and check if it solves problem.

I am not related to Telegram, but noticed that in my Xubuntu the icon disappears from desktop after each update, I was going to file a bug, but found your very similar issue.

**Comment by russiandesman** [comment]
Sorry, @makhalin, seems like for Gnome launchers are at ~/.local/share/applications, please check there instead of ~/Desktop

**Comment by ilya-fedin** [comment]
I guess, shaking is a GNOME feature that indicates new messages, so changing icon path shouldn't help

**Comment by russiandesman** [comment]
Oops, sorry, then I'm going to file separate bug

**Comment by makhalin** [comment]
> Sorry, @makhalin, seems like for Gnome launchers are at ~/.local/share/applications, please check there instead of ~/Desktop

For snap apps path is `/var/lib/snapd/desktop/applications/`.

> I guess, shaking is a GNOME feature that indicates new messages, so changing icon path shouldn't help

Maybe, but I can't find an option to disable it. I only discovered that dash-to-dock gnome extension has [same problem](https://github.com/micheleg/dash-to-dock/issues/1568), but I don't use it.

**Comment by ilya-fedin** [comment]
What's on your screenshot if not dash-to-dock extension?

**Comment by makhalin** [comment]
> What's on your screenshot if not dash-to-dock extension?

This is a default gnome dash layout.

**Comment by ilya-fedin** [comment]
AFAIK GNOME doesn't have dash by default and Ubuntu preinstalls dash-to-dock

**Comment by makhalin** [comment]
> AFAIK GNOME doesn't have dash by default and Ubuntu preinstalls dash-to-dock

Dash is a panel on the left side.
Dock is a panel on the bottom side.

I have a left-sided panel with icons.

**Comment by ilya-fedin** [comment]
According to its description:
> A dock for the Gnome Shell. This extension moves the dash out of the overview transforming it in a dock for an easier launching of applications and a faster switching between windows and desktops. 

If I understand right, 'overview' is that fullscreen thing. So the extension transforms the fullscreen thingie into a dock that could be at any side of the screen.

**Comment by Aokromes** [comment]
so, no telegram bug?

**Comment by ilya-fedin** [comment]
Yeah, I think it's a bug of dash-to-dock
