### ISSUE TITLE
is there any option to enable right to left mode in telegram desktop?

### ISSUE THREAD

**Issue by AMP999** [telegramdesktop/tdesktop#23871]
i have found a function style::SetRightToLeft(bool RTL) in file style_core_direction.CPP and used it just before the event loop begins. this function made the telegram somewhat right to left but the scroll area hasn't moved also counter badges and other things.
should I fix it myself or there is any function that I have not found?

**Comment by john-preston** [comment]
@AMP999 I'm afraid this is not supported :( a huge amount of changes is required for this to work properly.

**Comment by AMP999** [comment]
I'm trying to do it. is it possible to ask about details in code when something goes wrong?

**Comment by john-preston** [comment]
If there are specific questions I can try answering them, you can ask at https://t.me/preston. But I don't have time to actually work on that right now :(

**Comment by AMP999** [comment]
thank you
