### ISSUE TITLE
[Question] Compiling READ-ONLY Version

### ISSUE THREAD

**Issue by psychosys** [telegramdesktop/tdesktop#23884]
Hi
Is there any way to compile the restricted version of Telegram Desktop which is a **READ-ONLY** version ( that means you can not do any interaction, no writing, no voice/emoji/ .... just READING )
Currently I am building such client with a lot of trouble searching everywhere / removing inputs or keyboard actions .. 

thought you may have such secret feature builtin 👍

**Comment by 23rd** [comment]
No, there is no such thing.
