### ISSUE TITLE
[Feature Request] Exclude chat from "All chats" folder after included it in some other folder

### ISSUE THREAD

**Issue by grimcap** [telegramdesktop/tdesktop#23883]
### Is your feature request related to a problem?

sbj

### Describe the solution you'd like

Option in Settings menu

### Describe alternatives you've considered

It mb default behavior

**Comment by RememberTheAir** [comment]
You can archive the chat

**Comment by grimcap** [comment]
> You can archive the chat

It's different sense
And useless clicks

**Comment by 23rd** [comment]
https://bugs.telegram.org/c/11592
