### ISSUE TITLE
[Question]  Config changes in TG or client TCP/IP to address "TCP Info: not enough" ineffeciencies

### ISSUE THREAD

**Issue by jmscraig** [telegramdesktop/tdesktop#23880]
Hello,  I searched open and closed issues and did not find a single post on this question.  

**Note the in-efficiency, only ~20% read.  "TCP Info: not enough 4468 for packet! full size 5708 read 1240"**

Any configuration changes I should look at on the TG Desktop config of client TCP/IP to improve TG's read efficiency?

Thanks!

**Comment by ss007hacks** [comment]
![Screenshot_2013-03-24-00-53-31-1](https://user-images.githubusercontent.com/76266492/148880764-4440433c-b900-4568-8bd3-88d72358746d.jpg)
alles klaar ne

**Comment by john-preston** [comment]
There is no in-efficiency, this log line just says that a part of the packet was already received, while some part of the packet is still not received from the network.

**Comment by jmscraig** [comment]
Thanks!
