### ISSUE TITLE
Shortcuts for scrolling a page down/up in chat disappeared

### ISSUE THREAD

**Issue by Hi-Angel** [telegramdesktop/tdesktop#23887]
### Steps to reproduce

1. Open any chat with lots  of messages
2. Press <kbd>Page Up</kbd>

### Expected behaviour

The chat will scroll up one page

### Actual behaviour

Nothing is happening

### Operating system

Archlinux

### Version of Telegram Desktop

3.4.2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Switch to official binary, it doesn't have such a bug

**Comment by Hi-Angel** [comment]
> Switch to official binary, it doesn't have such a bug

Oh indeed, I confirm that. So it is a packaging bug, sorry for the noise.

**Comment by ilya-fedin** [comment]
It is a Qt bug and official binary has patched Qt

**Comment by Hi-Angel** [comment]
Just for reference, do you have a link to the discussion about that bug?

**Comment by ilya-fedin** [comment]
https://bugreports.qt.io/browse/QTBUG-97908

**Comment by Hi-Angel** [comment]
Thanks!
