### ISSUE TITLE
Problem with Git apply

### ISSUE THREAD

**Issue by gilsefidi** [telegramdesktop/tdesktop#2388]
git apply ./../../tdesktop/Telegram/Patches/openal.diff

when i use this code in vs 2015 console  , i get error :

./../../tdesktop/Telegram/Patches/openal.diff:10: trailing whitespace.
        if (!self->killNow) while(GetMessage(&msg, NULL, 0, 0))
./../../tdesktop/Telegram/Patches/openal.diff:19: trailing whitespace.
        if (!self->killNow) while(GetMessage(&msg, NULL, 0, 0))
error: patch failed: Alc/backends/winmm.c:221
error: Alc/backends/winmm.c: patch does not apply

**Comment by gilsefidi** [comment]
Error 2 : 

D:\TBuild\Libraries\qt5_6_0>cd qtbase && git apply ../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff && cd ..


../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff:12: trailing whitespace.
# Make this build use static runtime library.
../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff:13: trailing whitespace.
QMAKE_CFLAGS_RELEASE    = -O2 -MT
../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff:14: trailing whitespace.
QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += -O2 -MT -Zi
../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff:15: trailing whitespace.
QMAKE_CFLAGS_DEBUG      = -Zi -MTd
../../../tdesktop/Telegram/Patches/qtbase_5_6_0.diff:29: trailing whitespace.
    // CopyFile2 returns HRESULT, not BOOL, so it should be tested for S_OK, not 0.
fatal: git apply: bad git-diff - expected /dev/null on line 423

**Comment by Aokromes** [comment]
I sugest to use sourcetree or gitextensions to apply patches.
This issue is unrelated to telegram, instead to git. @auchri

**Comment by gilsefidi** [comment]
how  ?

**Comment by Aokromes** [comment]
In case of soucetree: http://i.imgur.com/Y96VwX2.png
(git for windows don't likes to much patches with /dev/null 
(maybe you can try to rename .diff to .patch and check if it works)

**Comment by gilsefidi** [comment]
git -c diff.mnemonicprefix=false -c core.quotepath=false apply -v --reject -p 1 --directory=D:/TBuild/Libraries/openal-soft/ C:\Users\Pouya\Documents\tdesktop\Telegram\Patches\openal.diff
C:\Users\Pouya\Documents\tdesktop\Telegram\Patches\openal.diff:10: trailing whitespace.
	if (!self->killNow) while(GetMessage(&msg, NULL, 0, 0))

C:\Users\Pouya\Documents\tdesktop\Telegram\Patches\openal.diff:19: trailing whitespace.
	if (!self->killNow) while(GetMessage(&msg, NULL, 0, 0))
Checking patch D:/TBuild/Libraries/openal-soft/Alc/backends/winmm.c...
fatal: invalid path 'D:/TBuild/Libraries/openal-soft/Alc/backends/winmm.c'

**Comment by zikasak** [comment]
Change CLRF to LF and if will works

**Comment by stek29** [comment]
@zikasak so this issue can be closed?
