### ISSUE TITLE
Fix #17324 appears to have regressed, issue #16884 is back

### ISSUE THREAD

**Issue by gbcox** [telegramdesktop/tdesktop#23898]
### Steps to reproduce

Problem was fixed, but with today's update (January 14, 2022) #16884 is back.

### Expected behaviour

Upgrade successful

### Actual behaviour

Update is downloaded, but is corrupted.  You have to delete the Telegram directory and reinstall manually from the website.

### Operating system

Fedora Linux 

### Version of Telegram Desktop

3.4.4 Beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
There were no changes to the updater since then

**Comment by gbcox** [comment]
Weird update a few weeks ago worked perfectly, today the update failed with the same issue of corrupted/partial download.  Had to delete the Telegram directory, go to the website, download the tsetup then extract the Telegram directory.

**Comment by ilya-fedin** [comment]
I have a feel that this is going to be like the famous Linux kernel bug 12309

**Comment by gbcox** [comment]
On the bright side there is an easy workaround.  It's more of an annoyance than anything else.

**Comment by john-preston** [comment]
@gbcox Does it reproduce from scratch? Like, download the previous version from github releases and try to autoupdate in Settings.

**Comment by Marzal** [comment]
I was affected by #16884 and I didn't have any problems updating to 3.4.4 beta.

ArchLinux + KDE Plasma

**Comment by gbcox** [comment]
@john-preston Hey John, that worked - so maybe I had something in my configuration left over from the previous installations.  Noticed this time I had to reconfigure.  Can we keep this open until the next release to be sure?  Thanks!

**Comment by gbcox** [comment]
Guess it was some kind of fluke with my configuration, just upgraded to 3.4.5 beta with no issues, so closing.  Thanks much!

**Comment by ilya-fedin** [comment]
...or the issue was never fixed for your case and it appears randomly

**Comment by xelld** [comment]
I have the same issue.
Updated to 3.5 today via updater and the binary has been corrupted.
Kernel 5.15.6, Fedora 34.
So I guess the #16884 still persists.

**Comment by mwoodson** [comment]
same problem here.  Fedora 35 FWIW.

Update button in telegram, pushed it hoping it would work THIS time...it didn't. 

Seems to be broken most upgrades for me.

**Comment by john-preston** [comment]
Can anybody with the problem please check if you:

- download 3.4.8 from GitHub releases: http://github.com/telegramdesktop/tdesktop/releases/v3.4.8
- unpack it to a separate folder ~/TestUpdate
- create an empty folder ~/TestUpdate/TelegramForcePortable (so that this separate version won't kill your auth session)
- launch the app from terminal with `~/TestUpdate/Telegram -debug`
- try to update it in Settings to 3.5.0

Will it work that way? If not - can you .zip and upload logs here from ~/TestUpdate/TelegramForcePortable/DebugLogs ?

**Comment by mwoodson** [comment]
> Can anybody with the problem please check if you:
> 
> * download 3.4.8 from GitHub releases: [http://github.com/telegramdesktop/tdesktop/releases/v3.4.8](https://github.com/telegramdesktop/tdesktop/releases/v3.4.8)
> * unpack it to a separate folder ~/TestUpdate
> * create an empty folder ~/TestUpdate/TelegramForcePortable (so that this separate version won't kill your auth session)
> * launch the app from terminal with `~/TestUpdate/Telegram -debug`
> * try to update it in Settings to 3.5.0
> 
> Will it work that way? If not - can you .zip and upload logs here from ~/TestUpdate/TelegramForcePortable/DebugLogs ?

I am one who has issues upgrading every time the button appears.  So I tried these steps, and I couldn't get it to fail.  I tried it 3 times and it worked every time.   Happy to try something else if suggested.

**Comment by gbcox** [comment]
> > Can anybody with the problem please check if you:
> > 
> > * download 3.4.8 from GitHub releases: [http://github.com/telegramdesktop/tdesktop/releases/v3.4.8](https://github.com/telegramdesktop/tdesktop/releases/v3.4.8)
> > * unpack it to a separate folder ~/TestUpdate
> > * create an empty folder ~/TestUpdate/TelegramForcePortable (so that this separate version won't kill your auth session)
> > * launch the app from terminal with `~/TestUpdate/Telegram -debug`
> > * try to update it in Settings to 3.5.0
> > 
> > Will it work that way? If not - can you .zip and upload logs here from ~/TestUpdate/TelegramForcePortable/DebugLogs ?
> 
> I am one who has issues upgrading every time the button appears. So I tried these steps, and I couldn't get it to fail. I tried it 3 times and the upgrade worked every time. Happy to try something else if suggested.

Same here.  Apparently, something is happening in the existing install that doesn't show up when you try to recreate from scratch - and I'm guessing whatever that is, is happening during the auto-update download.  So, how about:
1.  Turning off auto-update
2.  Wait for notification that update is available
3. Restart Telegram with the debug feature
4. Then turn on auto-update

I would think that should capture the issue... at least, worth a shot unless anyone else has a better idea.

**Comment by john-preston** [comment]
You can enable debug logs permanently (until the next update) by typing "debugmode" in Settings. Then wait for the next update and look into "~/.local/share/TelegramDesktop/DebugLogs".

**Comment by xelld** [comment]
Updated today to 3.7.1 without any problems.

**Comment by mwoodson** [comment]
Failed for me on 3.7.1.  I am having a real hard time collecting the debug on this too.

**Comment by xelld** [comment]
Okay, it's broken, again.

**Comment by ilya-fedin** [comment]
We're still waiting for the logs
