### ISSUE TITLE
Music after 36min skips to the begin. Fails on podcasts and dj mixes

### ISSUE THREAD

**Issue by webportnoy** [telegramdesktop/tdesktop#23892]
### Steps to reproduce

Telegram Desktop ver. 3.4.3
System:    Kernel: 5.4.0-94-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal

Trying to listen podcasts on any channels, but after 36 minute music skips to the begin of track.
Some channels for example: 
https://t.me/BassBuzz 
https://t.me/djmixshare

On mobile version of telegram it's ok

### Expected behaviour

play till the end of track and after play next track

### Actual behaviour

skips after 36 minutes to the begin of track. Next track not played.

### Operating system

Kernel: 5.4.0-94-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7             wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal

### Version of Telegram Desktop

3.4.3

### Installation source

Static binary from official website

**Comment by webportnoy** [comment]
updated to 3.4.8 bug still exists
On windows 11 and MacOS this bug is not exists.
Only Linux version has this bug

**Comment by webportnoy** [comment]
3.5.2 bug still exists
Log has no special string for skipping audio event
[log.txt](https://github.com/telegramdesktop/tdesktop/files/8030113/log.txt)

**Comment by john-preston** [comment]
@webportnoy Does this happen if you start the playback and skip in the player to 35-th minute and from there listen a couple of minutes? Doesn't happen for me. Or that only happens if you listen for 36 minutes straight?

**Comment by webportnoy** [comment]
@john-preston it happens actualy on 35:57. Nevermind if i skip to 35min or listening all over 36 minutes. After 35:57 track skips to begin. I recorded it on video: https://disk.yandex.ru/d/aBnkXFODYSbBgQ

**Comment by webportnoy** [comment]
@john-preston yes, i using only official version. Can it depends of Mint or Cinnamon? What distro did you test on?

**Comment by john-preston** [comment]
I tested Ubuntu with KDE, I doubt it can depend in the distro.

**Comment by webportnoy** [comment]
@john-preston I tested on Fedora/Gnome - no bug. So, this is really depend in the distro. Telegram desktop use it's own audio player or integrated component of OS?

**Comment by john-preston** [comment]
@webportnoy It's own.

**Comment by webportnoy** [comment]
@john-preston finaly i found who is responsible for this bug - Cinnamon. I tested on Fedora/Cinnamon and 36 min was max time to play. If Telegram desktop use it's own player - how it can be happen?

**Comment by ilya-fedin** [comment]
audio player is exposed via MPRIS, Cinnamon can send stop command
