### ISSUE TITLE
On three monitors, the context menu flies to the main screen

### ISSUE THREAD

**Issue by agorshkov23** [telegramdesktop/tdesktop#23893]
### Steps to reproduce

1. Connect three monitors
2. Move the telegram window from the main window
3. Open the context menu

### Expected behaviour

Opening the context menu near the cursor

### Actual behaviour

Opening the context menu on the main window

### Operating system

Windows 10 x64

### Version of Telegram Desktop

v3.4.3 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#7099
