### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by 2shaar2059** [telegramdesktop/tdesktop#23890]
### Is your feature request related to a problem?

The Telegram tar file for linux does not come with a .desktop file

### Describe the solution you'd like

I'd like the tar to come with a .desktop file

### Describe alternatives you've considered

N/A

**Comment by ilya-fedin** [comment]
Why for?

**Comment by 2shaar2059** [comment]
I thought it would be convenient for launching. Many other applications come with .desktop files

**Comment by ilya-fedin** [comment]
You can just double click the binary and then it will install itself to system menu

**Comment by 2shaar2059** [comment]
I tried that on Ubuntu 20.04 but the the telegram icon did not show up in "Show Applications"

**Comment by ilya-fedin** [comment]
What's "Show Applications"? :thinking:

**Comment by 2shaar2059** [comment]
![show_applications](https://user-images.githubusercontent.com/33207092/149241081-9abc95f4-fc97-4094-8390-e70b50095125.jpg)

**Comment by ilya-fedin** [comment]
Does .desktop file in ~/.local/share/applications exist?

**Comment by 2shaar2059** [comment]
nope

**Comment by ilya-fedin** [comment]
Is it possible that you copied tdesktop data from other computer? It will create the shortcut only on first launch or after update.

**Comment by 2shaar2059** [comment]
No I did not copy it. I tried untarring the tar installation file from the telegram website to start fresh and still no icon. I think it would be simpler for the user if the application just came with a .desktop file.

**Comment by ilya-fedin** [comment]
> Many other applications come with .desktop files

Can you name those? I don't know any

**Comment by ilya-fedin** [comment]
> I think it would be simpler for the user if the application just came with a .desktop file.

I think auto-creation is simpler for the user than manual intervention

**Comment by ilya-fedin** [comment]
> nope

Show the result of ` ls -lh ~/.local/share/applications`

**Comment by 2shaar2059** [comment]
![image](https://user-images.githubusercontent.com/33207092/149248309-3484415e-9062-4737-8850-8ee9e41f5694.png)

**Comment by 2shaar2059** [comment]
> > I think it would be simpler for the user if the application just came with a .desktop file.
> 
> I think auto-creation is simpler for the user than manual intervention

I agree. The shortcut should be automatically created under the circumstance that it doesn't already exist

**Comment by ilya-fedin** [comment]
`env | grep DESKTOPINTEGRATION`

**Comment by ilya-fedin** [comment]
That's really, really weird. Try to fully close Telegram and remove ~/.local/share/TelegramDesktop to make a first launch.

**Comment by 2shaar2059** [comment]
Thanks for the guidance. I just did that but still no telegram shortcut in "Show Applications" or anything pertaining to telegram under ~/.local/share/applications

**Comment by ilya-fedin** [comment]
`cat /etc/tdesktop/externalupdater`

**Comment by 2shaar2059** [comment]
![image](https://user-images.githubusercontent.com/33207092/149249438-793052fc-8d10-486e-8dca-ddc489800df6.png)

**Comment by ilya-fedin** [comment]
What's your tdesktop version?

**Comment by 2shaar2059** [comment]
ok so I had a TelegramDesktop folder somewhere other than  ~/.local/share . I moved it to an irrelevant directory, ran the Updater instead of Telegram executable, removed all other connected devices from my phone's Telegram app, then added my telegram desktop device via the QR code. I now have a telegram shortcut in "Show Applications".
