### ISSUE TITLE
Please, remove hovering sticker panel

### ISSUE THREAD

**Issue by ivmazurenko** [telegramdesktop/tdesktop#23891]
### Steps to reproduce

1. Try to click on your message
2. You accidentally hovered sticker panel

### Expected behaviour

Sticker was not sent

### Actual behaviour

Sticker was sent because i accidentally hovered panel.

My interlocutor does understands me, he was not expected this sticker

### Operating system

linux, mac, windows

### Version of Telegram Desktop

31.12.21

### Installation source

Static binary from official website

**Comment by ivmazurenko** [comment]
Excuse me, but I will create this task again and again, each time, after my colleagues will send me dicks, vomit, hitler, condoms and other stickers which I shouldn't see

**Comment by john-preston** [comment]
@ivmazurenko oh, those colleagues.. nice tdesktop version btw

I'm considering a setting for that.

**Comment by Aokromes** [comment]
anyway, duplicate.
