### ISSUE TITLE
Telegram takes a very long time to start and the UI constantly locks up (Debian) [Possibly fixed]

### ISSUE THREAD

**Issue by exikyut** [telegramdesktop/tdesktop#23896]
### Steps to reproduce

1. Start Telegram on Debian Stable using `./Telegram` or `./Telegram -noupdate`
2. Discover issues
3. Try different things while writing up bug report
4. Possibly accidentally discover solution to problem (???)
5. Submit report anyway in case the problem is widespread

### Expected behaviour

Telegram should work normally :face_with_thermometer: for users running a wide variety of desktop environments and windowmanagers.

### Actual behaviour

- The window doesn't appear for approximately two minutes
- When Telegram finally starts up, the UI has an odd characteristic tendency for *certain* things to cause freezes:
  - Resizing the window when custom window frame is enabled
  - Occasionally clicking the close button on the settings pane (regardless of custom window frame)
  - Occasionally clicking the "start messaging" button
  - Occasionally scrolling inside the settings pane

The freezes seem to hover around the ~25 second range.

If I induce a freeze then right-click the systray icon, the menu appears after the UI fixes itself.

If I add `-debug`, I see absolutely nothing interesting relating to UI lockups or freezes in the log(s). I did see a point where Telegram noted it lost its connection. Poking around with `strace` suggests Telegram runs a bunch of different threads, so either the UI and network logic run distributed amongst the same (set of) thread(s), or this issue is causing the network thread to block.

I'm happy to share the debug log info, but I unfortunately have to say that while running `tail -F log.txt DebugLogs/*`, the only significant thing happening while the UI frezes is that that nothing is being printed to the log! :(

My conclusion is

- potentially something Qt-related (although checking Debian Stable's repo, I see nothing involving `*qt*` that needs upgrading right now)
- a runaway futex/mutex deadlock or hang somewhere (nooo)

I vaguely recall that Qt's behavior can sometimes be changed with environment variables, but have not had much luck finding any lists of what environment variables are available. I did find and try `QT_QUICK_BACKEND=software QT_OPENGL=software ./Telegram -noupdate`, which did not produce any different results (2 minute wait for window to appear, 20 second freezes).

Looking through the log I noticed the line

> `[2022.01.14 20:39:50] XDP File Dialog Error: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.portal.Desktop': timed out (service_start_timeout=120000ms)`

which seemed kinda interesting given the ridiculous timeout value, so after googling that I found https://bbs.archlinux.org/viewtopic.php?id=224787, which suggested I

```
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
```

and Telegram *seems* to be back to its normal self, launching within 1 second and generally not locking up all over the place.

I'm not sure whether this "fix" is a red herring or if it actually nailed the problem. Attempting to rerun the above command with bogus values doesn't seem to un-fix the fix, and I'm less than enthused by the idea of rebooting at this exact moment, so I guess I'll update this when I next reboot if everything breaks again.

### Operating system

Debian Stable

### Version of Telegram Desktop

3.4.3 via auto-update

### Installation source

Static binary from official website

### Logs

```shell
Unfortunately I forgot to save the copy of the log when it was showing errors D':
```

**Comment by ilya-fedin** [comment]
Yeah, dbus can block startup, but there's no fix as these requests are required to be done before the UI is shown (e.g. getting system dark mode setting value)

**Comment by ilya-fedin** [comment]
The only way to avoid this is ensure your system properly configured and no dbus service times out

**Comment by NXij** [comment]
```method return time=1642176882.470359 sender=org.freedesktop.DBus -> destination=:1.106 serial=3 reply_serial=3
**method call time=1642176882.470367 sender=:1.106 -> destination=org.freedesktop.portal.Desktop serial=4 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.Settings; member=Read
   string "org.gnome.desktop.wm.preferences"
   string "button-layout"**
method call time=1642176907.488474 sender=:1.108 -> destination=org.freedesktop.DBus serial=113 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
```
yep, seems like dbus times out with that call. Oddly, telegram only starts slow when launching it the first time after starting the dbus service/rebooting.

**Comment by ilya-fedin** [comment]
> Oddly, telegram only starts slow when launching it the first time after starting the dbus service/rebooting

Some versions of xdg-desktop-portal have a deadlock on launch. If you have such a version, that behavior is expected.

**Comment by NXij** [comment]
Yeah seems to be an issue with the session, you can close this ticket; I'll leave another url for whoever trips on the same problem and finds this issue.

https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start

**Comment by exikyut** [comment]
@NXij: This was incidentally using Xorg (haven't braved Wayland yet, and I reach for `xdotools` at least twice a year in any case).

@ilya-fedin: it could be a nice-to-have (and ultimately harder than just making this a documentation problem :D), but if D-Bus calls can be done asynchronously, using a wrapper that prints a message to the log (or stdout?) if the D-Bus call is still in progress after 5 seconds could allow for straightforward discovery of this problem. \*Shrug\*

**Comment by ilya-fedin** [comment]
> it could be a nice-to-have (and ultimately harder than just making this a documentation problem :D), but if D-Bus calls can be done asynchronously

This is not possible due to tdesktop architecture and would be wrong with a call like getting dark mode value (or you can get a race when the window blinks in white before switching to dark mode on start)

**Comment by ilya-fedin** [comment]
> using a wrapper that prints a message to the log (or stdout?) if the D-Bus call is still in progress after 5 seconds could allow for straightforward discovery of this problem.

Oh, you would to wrap _a lot_ of code... I don't think this is something I would do.

**Comment by exikyut** [comment]
> This is not possible due to tdesktop architecture and would be wrong with a call like getting dark mode value (or you can get a race when the window blinks in white before switching to dark mode on start)

That makes absolutely perfect sense.

> Oh, you would need to wrap _a lot_ of code... I don't think this is something I personally would do.

Having a poke around I see heavy use of `get_sync` and `call_sync()` that would be a lot of work to refactor with very little gain.

Thanks for the info. I agree that this is most straightforward to regard as a documentation problem, if I've correctly diagnosed this (I'm reasonably sure I have). Hopefully the title of this issue helps out others that might be using odd desktop environments.

**Comment by exikyut** [comment]
Well, that reboot happened quite a bit more quickly than I expected: the newer kernel version I started running a little while back decided to chuck a wobbly when I attempted ACPI standby last night. No page faults for me thanks, back to 4.19 I go lol

So I can confirm that the `dbus-update-activation-environment` command was necessary before Telegram would start up happily.

While idly considering the (now confirmed) situation as I wrote the above, I realized... the error state causing the problem might exist before Telegram starts and then be resolved (eg user fixes D-Bus environment after Telegram launches and then everything promptly catches up (?) - didn't think to test this, but would likely work), but by definition the reverse can never be the case (D-Bus is fine but then breaks).

This means that the error state only has to be checked for once (most practically at startup, to inform the user immediately).

So, wrapping a throwaway D-Bus "nop" RPC of some kind (a request for the dark mode config?) within an alarm/timeout would very likely be completely sufficient to "fix" this (inasmuch as the "fix" would be handing the user the relevant bit of the documentation). Timeout fires? Print to stderr (I had no idea the logfile existed before I went debug-spelunking, FWIW), *mayyyybe* even put a Qt messagebox on the screen - and then job done, call it a day.

I'm honestly perplexed that this is the only bug report about this issue. I'm hitting it with Openbox, which is pretty mainstream as lightweight environments go; there are even more minimal configurations out there (i3, awesome, Xmonad) that definitely would not perform this bit of D-Bus initialization out of the box.

**So, "request for comments" :) from anyone else who's hit this D-Bus issue and fixed it by running the command above!**

I'll reopen this if anyone does so.

**Comment by ilya-fedin** [comment]
> I'm honestly perplexed that this is the only bug report about this issue. I'm hitting it with Openbox, which is pretty mainstream as lightweight environments go; there are even more minimal configurations out there (i3, awesome, Xmonad) that definitely would not perform this bit of D-Bus initialization out of the box.

I believe the initialization is done by systemd, that's how it works on Arch at least. So it works properly out-of-the-box even with lightweight environments. Maybe you screwed your installation somehow.
