### ISSUE TITLE
Custom macOS app icon is ignored when launching the app

### ISSUE THREAD

**Issue by MatLegat** [telegramdesktop/tdesktop#23895]
### Steps to reproduce

1. Add Telegram to Dock ( Right click -> `Options`  -> `Keep in Dock`
1. Right click Telegram dock app icon -> click `Options` -> click `Show in Finder`
1. Right click `Telegram.app` -> click `Get Info`
1. Replace app icon by dragging or pasting a new icon file
    <img width="538" alt="image" src="https://user-images.githubusercontent.com/11902693/149405025-5d04916c-9f72-4e68-af3d-d4b93ff50cee.png">
1. Launth Telegram app

### Expected behaviour

The user-set custom icon should be displayed on the Telegram Dock App at all times

### Actual behaviour

The Telegram dock app icon is reset to the default while the application is open

### Operating system

macOS Monterey 12.1

### Version of Telegram Desktop

3.4.3

### Installation source

Static binary from official website

**Comment by MatLegat** [comment]
This seems to be an old issue, but I couldn't find any related report here on the GitHub Telegram Desktop project.

Old reports of this bug that I've found on Reddit (with screen capture videos):
- [r/MacOs - Custom telegram dock icon switching back to original... (1 year ago)](https://www.reddit.com/r/MacOS/comments/l6u3f2/custom_telegram_dock_icon_switching_back_to/)
- [r/Telegram - ... custom telegram icon always switch back to original when opened ? (4 months ago)](https://www.reddit.com/r/Telegram/comments/pqs1fw/do_you_know_why_custom_telegram_icon_always/)

**Comment by ilya-fedin** [comment]
I believe this is intended behavior, you can't change the icon just by replacing .icns file (shortcut icon), you should also replace the icon in Qt resources used in setWindowIcon API (what is impossible without recompiling the app)

**Comment by foobarna** [comment]
> I believe this is intended behavior, you can't change the icon just by replacing .icns file (shortcut icon), you should also replace the icon in Qt resources used in setWindowIcon API (what is impossible without recompiling the app)

But why is this needed (the fact that is changing the app icon after startup)?

**Comment by ilya-fedin** [comment]
I don't quite understand the question. If you want your Qt application to have window icon, you will call that API. Do you want Telegram window to be without icon?

**Comment by foobarna** [comment]
What I mean is: why it needs to call that API to explicitly set it after app startup? As seen in the Reddit video posted ([here](https://v.redd.it/06y2jp8q12e61/HLSPlaylist.m3u8?a=1645306125%2CMTEzM2FkNjFkMGNjODZhODMyMWNlMTc1NTg3ZjNjNzViZjA0NjI4ZDQ4NzIyNmE4MWMyY2JhM2M5ZThkOWEyNA%3D%3D&v=1&f=sd)). For example, Slack or iTerm does not change the custom set icon in the Applications folder.

From what I gathered on the internet, is that it needs it to display the unread count - but I'm not sure.

**Comment by ilya-fedin** [comment]
> What I mean is: why it needs to call that API to explicitly set it after app startup?

Because that's how Qt works. The window won't have icon without calling this API.

**Comment by foobarna** [comment]
Can confirm that the icon is no longer forced when Telegram starts. It keeps the custom application icon.

Thanks @john-preston! 🎉
