### ISSUE TITLE
Archived chats with unread messages no longer bold in the main message list

### ISSUE THREAD

**Issue by GranPC** [telegramdesktop/tdesktop#23906]
### Steps to reproduce

1. Archive and mute a chat
2. Receive a message in that chat
3. Look at the main chat list

### Expected behaviour

The chat's name should be bold and pure black, like in previous releases of Telegram Desktop. I believe 3.4.3 exhibits the correct behavior.

### Actual behaviour

All chat names under the "Archived chats" header are gray and not bold, regardless of whether there are unread messages.

### Operating system

elementary OS 5.1.7 Hera running the Pantheon Desktop Environment

### Version of Telegram Desktop

Telegram Desktop 3.4.5 beta

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Thanks for your report.

**Comment by GranPC** [comment]
Thanks for the fix!

**Comment by GranPC** [comment]
Can confirm this is solved in beta 3.4.6. Thanks everyone!
