### ISSUE TITLE
Telegram Desktop Crashing Everytime I open It

### ISSUE THREAD

**Issue by TheAlpha7020** [telegramdesktop/tdesktop#23905]
### Steps to reproduce

Telegram Desktop is Crashing each and Everytime I open it, attaching crash report below. 

### Expected behaviour

This problem started a few days ago, whenever I open Telegram, Showing it has encountered a crash, and when I continue, while hovering through chats or while opening groups or  being ideal for more than 1 minute, it is closing on its own and showing crash. Using Latest Updated version of Telegram (3.4.4 beta x64) (Installed from Official website) 
Current OS: Windows 10 x64 bit.
Tried many ways to fix it like Restarting the System, Re-Installing Telegram several Times, still continuing the same.  
Please kindly help me to solve this issue.

### Actual behaviour

Crash Report: 

Your Report Tag: 97918da9-3593-4940-97c5-e554a955223a
ApiId: 2040
Binary: Telegram.exe
Launched: 16.01.2022 14:33:29
OpenGL ANGLE: Auto
OpenGL Renderer: ANGLE (AMD, AMD Radeon(TM) R3 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.11026.12001)
Platform: Windows64Bit
Version: 3004004 beta
Memory-usage: 307 MB (peak), 307 MB (current)
Pagefile-usage: 304 MB (peak), 294 MB (current)

Caught signal 11 (SIGSEGV) in thread 6104

Backtrace omitted.

Google Breakpad caught a crash, minidump written in thread 10964
Minidump: 97918da9-3593-4940-97c5-e554a955223a

Backtrace omitted.

### Operating system

Windows 10

### Version of Telegram Desktop

Telegram Desktop Version:   3.4.4 beta x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@TheAlpha7020 Thanks for your report! I hope to deploy a beta with a fix later today.

**Comment by TheAlpha7020** [comment]
Okay, Thank You @john-preston

**Comment by TheAlpha7020** [comment]
> @TheAlpha7020 Thanks for your report! I hope to deploy a beta with a fix later today.

Dear @john-preston 
it was shown that my issue was solved in 'Actions' corner in GitHub, but still I'm facing the same, no updates also came for me, what should I do, I think the issue was resolved from your side according to the image attached below
![Img_1](https://user-images.githubusercontent.com/97828315/149667824-358b6303-b4e6-49a3-9a6d-9ef0392bcfbc.JPG)
![Img_2](https://user-images.githubusercontent.com/97828315/149667825-254a2c09-54c1-4912-8fc1-f7380fc1e500.JPG)
![Img_3](https://user-images.githubusercontent.com/97828315/149667827-428ce967-5cb7-46fd-9fd8-4d7c1c03ebf3.JPG)

**Comment by john-preston** [comment]
@TheAlpha7020 The fix is in the repository, but no release with it was being made yet.

**Comment by TheAlpha7020** [comment]
> @TheAlpha7020 The fix is in the repository, but no release with it was being made yet.

@john-preston I thought there was problem with my pc that's why I'm not getting the update, now got it, you meant the update will be available soon right? Thank You for the above information.

**Comment by TheAlpha7020** [comment]
Thank You Very Much For Resolving My Issue @john-preston 
I've got the update😃.

![image](https://user-images.githubusercontent.com/97828315/149704159-a3ec9ba1-03de-4b41-9963-74e8165a1f65.png)
