### ISSUE TITLE
automatic media download disabled but not fully work 

### ISSUE THREAD

**Issue by jacob755** [telegramdesktop/tdesktop#23902]
### Steps to reproduce

1. all automatic media download disabled
2. click on Channel info or open Channel info section
3. click on 'photos' or 'gif'
4. image start downloading, gifs start downloading

other problem
on grouped image like when several image uploaded
1.click on  image  open it image next and before it also download automatically 

### Expected behaviour

like older version when you open Channel info
just show a small square thumbs of image and not downloading images
and when you open an image in grouped  item it don't open image next and before it.

### Actual behaviour

image start downloading even if all automatic media download disabled

### Operating system

win 8.1 32 bit

### Version of Telegram Desktop

3.4.4 beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@jacob755 When you open any image in viewer the images around are also preloaded to be able to switch quickly.

**Comment by jacob755** [comment]
> @jacob755 When you open any image in viewer the images around are also preloaded to be able to switch quickly.

can you make an option for it not to do this?

**Comment by john-preston** [comment]
@jacob755 Why? What is the use case?

**Comment by jacob755** [comment]
> @jacob755 Why? What is the use case?
because i open an image to see then if i want to see rest of that click on left right button then it get downloaded if not then its save my traffic plus if pic is inappropriate wont get downloaded too, and because telegram have automatic media download control feature i think it should control this too.
although this feature can called timesaver too.
