### ISSUE TITLE
[Question] Hello dear staff. When I was building telegramdesktop, I encountered a problem, please give me some pointers, thank you.

### ISSUE THREAD

**Issue by fish6688** [telegramdesktop/tdesktop#23908]
Hello dear staff.
When I was building telegramdesktop, I encountered a problem, please give me some pointers, thank you.
Which version of Visual Studio 2022 should I install? I am using Visual Studio 2022 17.0.5 now. During the build process, the following problems occur. Please give me more advice.
![image](https://user-images.githubusercontent.com/61409802/149718717-3211253a-f144-4e9a-a197-97651989201b.png)
Please help me, thanks a lot.

**Comment by 23rd** [comment]
There are already enough pointers in the error output on how to solve your problem.
```
git config --global user.email "you@example.com"
git config --global user.name "Sample"
```

**Comment by fish6688** [comment]
First of all thank you for your answer, can I configure my username and email in git?

**Comment by fish6688** [comment]
I am Windows 64 system

**Comment by 23rd** [comment]
> First of all thank you for your answer, can I configure my username and email in git?

Yes, you can.

**Comment by fish6688** [comment]
That's it, thank you very much for your pointers. In the next builds, I may have other problems. I will trouble you at that time. Thank you very much for helping me, thank you.

**Comment by fish6688** [comment]
Dear 23rd, Hello. Still have to trouble you. In the process of building, I encountered the following problem again, please help me to take a look and see how to solve it, thank you again.
![image](https://user-images.githubusercontent.com/61409802/149810498-1dade196-2fba-4dc8-902e-c3592fca4259.png)
![image](https://user-images.githubusercontent.com/61409802/149810536-522f637c-dcd1-454c-85c8-f85319eee014.png)
![image](https://user-images.githubusercontent.com/61409802/149810567-e8160fe1-c68a-4392-9cf5-12128c737b34.png)
![image](https://user-images.githubusercontent.com/61409802/149810592-3a45094c-c432-4c53-97ce-a4374328eb21.png)
