### ISSUE TITLE
VEX.Webshell in tsetup.3.4.3.tar.xz's `Updater`

### ISSUE THREAD

**Issue by jurdanetac** [telegramdesktop/tdesktop#23907]
### Steps to reproduce

1. Download tsetup.3.4.3.tar.xz binary for Linux => https://github.com/telegramdesktop/tdesktop/releases/download/v3.4.3/tsetup.3.4.3.tar.xz
2. Extract the file and upload the updater to VirusTotal => https://www.virustotal.com/gui/home/upload
3. Have a look at the results

### Expected behavior
No vendors flag the file as malicious

### Actual behavior
Bkav Pro flags the file as malicious (VEX.Webshell)

https://www.virustotal.com/gui/file/4c5cd3c48389840d9a20b72d8d9df09b9606b7979e41e7f9319222b534b8545b/detection

**Comment by Aokromes** [comment]
it must be reported as false positive to the antivirus vendor.
