### ISSUE TITLE
Text in Lao rendered incorrectly

### ISSUE THREAD

**Issue by fqdb** [telegramdesktop/tdesktop#23900]
### Steps to reproduce

1. Paste text in Lao in the input field, or view messages in Lao

### Expected behaviour

Text should be rendered as ອ່າງນໍ້າງິ້ນ

### Actual behaviour

Text is rendered as
![image](https://user-images.githubusercontent.com/2826336/149615985-76de0d33-2010-4c58-899b-6bf15dbe9b12.png)

This does not happen in most other places in the OS

### Operating system

Edition	Windows 10 Home Version	21H1 Installed on	‎14-‎Sep-‎20 OS build	19043.1466 Experience	Windows Feature Experience Pack 120.2212.3920.0

### Version of Telegram Desktop

3.4.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I guess this is due special character replacements in https://github.com/desktop-app/lib_ui/blob/master/ui/text/text.cpp, but this is something that unlikely to be changed :(
