### ISSUE TITLE
Telegram keeps stealing focus even if "Draw attention to the window" is unchecked

### ISSUE THREAD

**Issue by datafl4sh** [telegramdesktop/tdesktop#23915]
### Steps to reproduce

Already reported the same bug in #16269. Suggested to update telegram, nothing changed.

1. Install telegram from website by downloading the latest binary
2. Uncheck Settings -> Notifications -> Draw attention to the window
3. Wait for a message

### Expected behaviour

Telegram should not steal focus.

### Actual behaviour

Telegram steals focus.

There are already so many issues on this: #7885, #7887, #7900, #7922, #7964, #8006, #8268, #8346, #8372, #16269 this "feature" is driving me nuts, please fix it once for all.

### Operating system

OS: Debian 11, Telegram version: 3.4.3 DE: Mate 1.24.1 Used theme: default

### Version of Telegram Desktop

3.4.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I use MATE as my daily-driver myself (though I use a rolling release distro and I have MATE 1.26.0, maybe this is a bug of old MATE?) and was never able to reproduce such an issue despite I have this option enabled. Are you sure your issue is related to this option?

**Comment by datafl4sh** [comment]
Well, I do not know sufficiently well the Telegram internals to assure you that the issue is related to this option. I am pretty sure however that the issue is not Mate-related, as I observe the same thing on another machine running Xfce: as soon as you receive a message on an unmuted chat, Telegram pops up in foreground and takes the focus independently of the value of the option "Draw attention to the window".

**Comment by ilya-fedin** [comment]
Maybe you're hitting #10348? The window may start moving/resizing when the cursor over it, of course that will lead to 'stealing focus' as you say.

**Comment by datafl4sh** [comment]
Nope, the window neither moves nor resizes. The problem is that if telegram is below any window, when a message is received it pops in foreground. It does not depend on the fact that the cursor is over it, because normally I keep telegram on the right screen and I work on the left screen. Telegram pops up even if the cursor is in another screen.

I'll tell you something more: if telegram is the *last* window I minimized, when I receive a message it un-minimizes and appears in foreground (this only happens in mate).

**Comment by ilya-fedin** [comment]
Unfortunately, I have to state that I can't reproduce your issue and have no idea what is happening on your system

**Comment by datafl4sh** [comment]
I just finished installing a fresh Debian 11 VM + telegram, the problem immediately reproduced for me...

**Comment by ilya-fedin** [comment]
I don't use Debian 11. Maybe old software of Debian 11 is the reason why you get such a problem. I recommend you to install a distro with fresh software that has the latest version of MATE.

**Comment by datafl4sh** [comment]
I understand that you don't use Debian 11, and I am sure you have plenty of legitimate reasons for using a rolling release. This is not the case for everyone however, as for some people rolling-releases are a no-go.

Don't take me wrong: I appreciate telegram and I am thankful for your work, but IMHO a project of this breadth should support officially the main, more conservative distros. Answers like yours, which translate to "works for me, update to my same system config" sound pretty amateurish...

**Comment by ilya-fedin** [comment]
Well, I work for interest here and conservative distros out of my interest... Linux in tdesktop is mainly supported by the community.

**Comment by datafl4sh** [comment]
@john-preston I didn't spot that option, thank you for the suggestion. Just enabled native, I'll let you know.

**Comment by john-preston** [comment]
I have a feeling that activating a custom popup notification window for it to be shown above everything etc in your case triggers showing the main application window as well. Doesn't work like that on other systems or where I've tested, but maybe that's the case.

**Comment by ilya-fedin** [comment]
If that's the case, Ui::Platform::ClearTransientParent should help (theoretically Qt may automatically assign a parent just like with the PiP)

**Comment by john-preston** [comment]
Although it doesn't call "activateWindow" unless you click on the notification, so that's a really strange thing to do for the window manager.

**Comment by ilya-fedin** [comment]
Might be a bug in old MATE. I don't experience such a behavior with MATE 1.26

**Comment by john-preston** [comment]
@datafl4sh So how is it going with native notifications?
