### ISSUE TITLE
[Feature Request] add home button

### ISSUE THREAD

**Issue by Sveagruva** [telegramdesktop/tdesktop#23912]
### Is your feature request related to a problem?

since "mark as read" button was deleted from notifications the only way to let people know that you saw a message is to click on it. overtime it accumulates chats that i clicked on top of each other and when time comes to message myself to somebody you have two options: 1 swipe left for two minutes to get to list of chats, 2 quit telegram and open it.

### Describe the solution you'd like

home button next to back button when nesting is greater than 3

### Describe alternatives you've considered

replace current chat with opening chat instead of placing it on top.

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
