### ISSUE TITLE
Telegram Desktop and Telegram android is stuck at sending images

### ISSUE THREAD

**Issue by FahimFBA** [telegramdesktop/tdesktop#23913]
### Steps to reproduce

1. Open telegram desktop/android app
2. Send an image to anyone
3. It keeps on loading even though I am getting more than 45Mbps in other websites easily.

### Expected behaviour

The images should be uploaded and sent instantly based on the internet speed.

### Actual behaviour

It keeps on loading, and never stops.

### Operating system

Windows 11, Android 10

### Version of Telegram Desktop

3.4.3 x64

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment]
One of the datacenters is currently experiencing some problems. Check https://t.me/connectivity_test out: you shouldn't be able to download the 5th green gif

**Comment by FahimFBA** [comment]
Thanks a lot. I think it is okay now.
