### ISSUE TITLE
Broken markdown entites parsing on 3.4.5

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#23911]
### Steps to reproduce

1. write a message containing some words
2. select a word in the message (not the first one)
3. apply monospace formatting
4. send the message

### Expected behaviour

The message is rendered correctly

![image](https://user-images.githubusercontent.com/16143208/149776446-96e383e6-4255-45a6-be48-3d42d43d16fb.png)

(screenshot from the Android app)

### Actual behaviour

The text before the `monospace` portion of the message is rendered as an inline link

![image](https://user-images.githubusercontent.com/16143208/149776359-501c2a30-1f99-4688-ae53-cfc72d57e27f.png)

### Operating system

Widnows 10, Pop!OS 21.10

### Version of Telegram Desktop

3.4.5

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@RememberTheAir Thanks for you report! This will be fixed in the next version.

**Comment by bodqhrohro** [comment]
IT'S WONDERFUL PLEASE DON'T FIX
