### ISSUE TITLE
【Build】Hello dear staff. During the build process, I ran into a problem and asked for your help, thank you.

### ISSUE THREAD

**Issue by fish6688** [telegramdesktop/tdesktop#23918]
Hello dear staff. During the build process, I ran into a problem and asked for your help, thank you.
The specific error is as shown below, please help me, thank you.
![image](https://user-images.githubusercontent.com/61409802/149876579-7c88b7fe-67ea-4798-b788-333391b87e02.png)
![image](https://user-images.githubusercontent.com/61409802/149876595-cfc997c4-34de-461f-a580-e01fc181c9ab.png)
![image](https://user-images.githubusercontent.com/61409802/149876608-aeda9130-c698-4385-a6a6-bc0bbcf170df.png)
![image](https://user-images.githubusercontent.com/61409802/149876620-c41d9ca4-d121-4b79-a50f-085c00852918.png)

**Comment by ilya-fedin** [comment]
#23914

**Comment by fish6688** [comment]
Can anyone help me? thanks.
