### ISSUE TITLE
Make basic media playback controls via command line

### ISSUE THREAD

**Issue by mshamsi502** [telegramdesktop/tdesktop#23926]
### Is your feature request related to a problem?

Mostly I use Telegram Desktop as a Media Player (my OS is Linux) but is not any options for global controlling playback media from Telegram Desktop.
My control keyboard shortcut sound and media not working for Telegram Desktop (other opened media players have more priority or not working for Telegram Desktop). I cant find any not global shortkey, not command line that work.

### Describe the solution you'd like

I use linux os and need make custome shortcut for the playin' media from telegram desktop (v3.4.3) or used in other apps.
I request make some command for :

- Play (or Play/Pause) Media
- Next
- Previous
- Volume Up
- Volume Down
- Volume Mute/Unmute
- Microphone Mute/Unmute
- Forward Seeking Playback (for ex. 5 seconds )
- Back Seeking Playback (for ex. 5 seconds )

### Describe alternatives you've considered

can be like Spotify Command Line Controller
Play:
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Play`

Pause:
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause`

Play/Pause toggle:
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause`

Previous:
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous`

Next:
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next`

[Solution Issue in Community.Spotify.com](https://community.spotify.com/t5/Desktop-Linux/Basic-controls-via-command-line/m-p/4360856#M15590)

**Comment by ilya-fedin** [comment]
tdesktop owns org.mpris.MediaPlayer2.tdesktop when in-app player is active

**Comment by mshamsi502** [comment]
> tdesktop owns org.mpris.MediaPlayer2.tdesktop when in-app player is active
thanks, its work:

- Play/Pause toggle:
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.tdesktop /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause`

- Previous:
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.tdesktop /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous`

- Next:
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.tdesktop /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next`
