### ISSUE TITLE
Telegram is unable to switch theme when Breeze Light is selected, works with Breeze.

### ISSUE THREAD

**Issue by edfloreshz** [telegramdesktop/tdesktop#23929]
### Steps to reproduce

1. Enable `Match the system settings`

![image](https://user-images.githubusercontent.com/22224438/150195888-acbd22e8-3324-4396-baab-941ec7aee6f3.png)

2. Switch to `Breeze Dark`, the app should switch to dark mode.

![image](https://user-images.githubusercontent.com/22224438/150195940-0ceb15c5-64c6-4125-80ac-93d36ff9cb1a.png)

3. Switch back to `Breeze Light`, the app should stay dark.

![image](https://user-images.githubusercontent.com/22224438/150195999-53c21b3c-c90f-444f-9178-cc8023642cc1.png)

4. Switch to `Breeze`, the app should switch to light mode.

![image](https://user-images.githubusercontent.com/22224438/150196045-24e0fa46-2ac9-465f-8d4c-2bd333c1f59b.png)

### Expected behaviour

The app should be able to determine the right color scheme for any theme.

### Actual behaviour

Every theme works except `Breeze Light`, it should be supported since Plasma uses it as the default now, instead of `Breeze`.

The app should be able to determine which theme is selected regardless of the `ColorScheme` key, using [`qGray`](https://doc.qt.io/qt-5/qcolor.html#qGray) should resolve this.

### Operating system

Arch Linux 2022.01.01 with KDE Plasma 5.23.5

### Version of Telegram Desktop

3.4.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
What's `ColorScheme` key? :thinking: 
tdesktop is not a KDE application and doesn't use KDE frameworks...

**Comment by edfloreshz** [comment]
I know, but it's being used here.

https://github.com/telegramdesktop/tdesktop/blob/dc892624616b2e8901c3df1f707f0132c1e5dcdf/Telegram/SourceFiles/platform/linux/specific_linux.cpp#L450

**Comment by ilya-fedin** [comment]
It's a signal watcher, it watches for a color scheme change. I don't understand how qGray here would help.

**Comment by ilya-fedin** [comment]
I checked on my VM with KDE neon and the bug seem to be on KDE side. Changing color scheme from BreezeDark to BreezeLight doesn't emit org.freedesktop.portal.Settings.SettingChanged signal, so tdesktop is unable know whether color scheme is changed.

**Comment by edfloreshz** [comment]
Got it! I'll fill an issue to them. 

Thanks for replying, feel free to close.

**Comment by edfloreshz** [comment]
Issue has been filled! [#449096](https://bugs.kde.org/show_bug.cgi?id=449096)
