### ISSUE TITLE
[Feature Request] Add registration from desktop

### ISSUE THREAD

**Issue by atauenis** [telegramdesktop/tdesktop#23927]
### Is your feature request related to a problem?

I'm found that Windows version of Telegram cannot register an account. So it is impossible to register in Telegram without a Android or iOS device. Not all people have such devices, many humans still using old phones like Nokia 3310. But even such persons want to talk via Telegram using PC.

### Describe the solution you'd like

Add ability to register via SMS code or via a friend.

### Describe alternatives you've considered

Use another messengers instead of Telegram. :)

### Additional context

![2022-01-09_22-19-32](https://user-images.githubusercontent.com/4800266/150086937-43775bf0-532a-47a3-a892-38335f347d54.png)

Translated:
> Enter the code that was sent To you via Telegram, or use QR code for entry.
If you don't have a Telegram account yet, please register from your phone or tablet first.

What a discrimination of people with button cell phones...

**Comment by Aokromes** [comment]
duplicate, nothing preston can do.

such feature belongs to https://bugs.telegram.org/
