### ISSUE TITLE
is:issue is:open audio source doesnt switch if the device change (more then a year this bug is around)

### ISSUE THREAD

**Issue by ElMurte** [telegramdesktop/tdesktop#23924]
### Steps to reproduce

i mainly used bluetooth devices for those senarios:
First:
1-Connect a device audio
2-Switch device while app open
3-try to call someone (you hear them but they cant hear you)

second:
check no device audio is connected
1-open the app 
2-connect headphones
3-try to call someone

### Expected behaviour

audio and microfone should be changed as i change source the main source device (headphones...)
so you gonna hear them and they gonna hear you

### Actual behaviour

you can only hear them but they cant hear you

### Operating system

Windows 10

### Version of Telegram Desktop

3.4.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#9814
