### ISSUE TITLE
Opening multiple instances on Pop OS! 20.04 Flatpak version

### ISSUE THREAD

**Issue by nelson-ion** [telegramdesktop/tdesktop#23923]
### Steps to reproduce

1. Open Telegram;
2. Minimize Telegram using `x` button on conner top right to send application to tray;
3. Press "super-key button/win-key" and use search with Telegram value;
4. A 'new instance' is opened instead bring back the older instance.

### Expected behaviour

Recovery back the actual instance of Telegram instead of new instance when use the "search" on Pop OS 20.04.

### Actual behaviour

On Pop OS 20.04, after I click on `x` button to minimize the Telegram to **"system tray"**, if I use the "search option of system" to bring Telegram to foreground again, a new instance is opened instead of the reopen the instance already opened before.

### Operating system

Pop OS 20.04 LTS 64bits

### Version of Telegram Desktop

Telegram Desktop | org.telegram.desktop | 3.4.2 | stable

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Are you sure you have flatpak 1.12.0+? Old versions aren't compatible with tdesktop anymore due to upgrade to Qt 6.

**Comment by nelson-ion** [comment]
Hi, I think my software versions are updated. Below more details for my flatpark commands.
I can execute more commands to obtain more details (if necessary) to help detect/confirm/discard the bug. Do you have any suggestion?

Output for command `flatpak list`
```
Nome                            ID de aplicativo                     Versão  Ramo   Instalação
Freedesktop Platform            org.freedesktop.Platform             21.08.9 21.08  user
Mesa                            org.freedesktop.Platform.GL.default  21.3.3  21.08  user
ffmpeg-full                     org.freedesktop.Platform.ffmpeg-full         21.08  user
openh264                        org.freedesktop.Platform.openh264    2.1.0   2.0    user
Pop Gtk theme                   org.gtk.Gtk3theme.Pop-dark                   3.22   user
Telegram Desktop                org.telegram.desktop                 3.4.2   stable user
Telegram Desktop Webview Add-on org.telegram.desktop.webview         2.34.3  stable user
```
Output for command `flatpak --version`
```
Flatpak 1.8.5
```

**Comment by christianmtr** [comment]
This is also happens when you open a chat, group or channel from the browser with a link.

Same flatpak version (1.8.5) in Pop OS!.
App versions:
```
Telegram Desktop                                  org.telegram.desktop                                            3.5.2                stable             user
Telegram Desktop Webview Add-on                   org.telegram.desktop.webview                                    2.34.5               stable             user
```

**Comment by KindHeartedTraveler** [comment]
I got the same problem in ubuntu 20.04.1.But  flatpak's version is 1.6.5.
```
org.telegram.desktop                       3.5.2 
org.telegram.desktop.webview               2.34.5
```

**Comment by ilya-fedin** [comment]
Have you read the post above your one?
