### ISSUE TITLE
[Question] Hello dear staff. I'm having trouble building, please help, thanks a lot.

### ISSUE THREAD

**Issue by fish6688** [telegramdesktop/tdesktop#23925]
Hello dear staff. I'm having trouble building, please help, thanks a lot.
Can any experts give pointers? Thank you so much.
The specific error is as shown below, please help me, thank you.
![image](https://user-images.githubusercontent.com/61409802/150061101-85567b54-28c4-4f20-a3ee-6895cacbda35.png)
![image](https://user-images.githubusercontent.com/61409802/150061105-d735b42a-a347-4cd3-babd-05dcd35f89ff.png)
![image](https://user-images.githubusercontent.com/61409802/150061115-e1d65159-5fce-480d-b072-b880108f21c4.png)
![image](https://user-images.githubusercontent.com/61409802/150061126-6dde3784-73ec-4d4a-9911-0aa59869d319.png)

**Comment by Aokromes** [comment]
hell, stop opening new tickets, stay on one.

**Comment by fish6688** [comment]
Okay, mainly because no one helped me, I was in a hurry. Sorry to trouble you. Feel sorry.

**Comment by fish6688** [comment]
Have you encountered this problem during the build process? Also please advise, thank you very much. Or to build now, which version of Visual Studio 2022 do I need to use? Do you have any friends who have successfully built it yourself, please give more advice, thank you very much.

**Comment by 23rd** [comment]
Please provide which native tools command prompt you open (a command line title).

**Comment by fish6688** [comment]
![image](https://user-images.githubusercontent.com/61409802/150078982-687577a2-c542-4753-b61e-7bd76d293207.png)

Finally waiting for you, please help me take a look, thank you very much.

**Comment by 23rd** [comment]
Can you run in the command line and check an output?
`C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat amd64 x86 && set`

**Comment by fish6688** [comment]
How to enter it? I do not understand. I am afraid that the prompt after entering is not an internal or external command.

**Comment by fish6688** [comment]
![image](https://user-images.githubusercontent.com/61409802/150085392-93bfb202-a48e-4d8b-b8ab-530961587528.png)

**Comment by fish6688** [comment]
![image](https://user-images.githubusercontent.com/61409802/150089259-c756e872-a675-4e8a-829f-8787ba4d9c06.png)

Hi, is this how it works? thanks.

**Comment by fish6688** [comment]
Hello dear 23rd. Sorry for your inconvenience, I have done what you said, but still report the same error, please help me to look at it again, thank you. Also, am I using the wrong version of Visual Studio 2022, I'm using Visual Studio 2022 17.05 now
![image](https://user-images.githubusercontent.com/61409802/150118898-093c72e7-db28-40b1-a85c-0abbfe2c9763.png)

**Comment by 23rd** [comment]
What if you'll try to build x86 version?

**Comment by fish6688** [comment]
Hello, Windows is basically 64-bit now. So I need to build 64 bit. Is it my computer's problem?

**Comment by fish6688** [comment]
Is it a problem with the Visual Studio 2022 version? Which version should I use? Community 2022 or Professional 2022 or Enterprise 2022? Which specific version of 2022 to use? Such as: 17.0.5
