### ISSUE TITLE
Links with '$' sign in URL are broken

### ISSUE THREAD

**Issue by lucidium** [telegramdesktop/tdesktop#23921]
### Steps to reproduce

1. While writing a new message create a link with a CTRL+K shortcut. URL must contain dollar sign ('$')
![изображение](https://user-images.githubusercontent.com/7923337/149921546-0f25bdc6-1ee6-4995-8bcb-3bc76cbfe4be.png)
2. Result: a new message was sent without a link
![изображение](https://user-images.githubusercontent.com/7923337/149922079-e6f8edf0-9a9e-45b2-a5ff-f93efb972bd0.png)
If a message contains a link without a dollar sign - it works as intended:
![изображение](https://user-images.githubusercontent.com/7923337/149922400-fb241530-98a2-4b7e-b651-feba2deb757c.png)
![изображение](https://user-images.githubusercontent.com/7923337/149922457-d5c59d67-52cc-4296-aa35-69195455c7b5.png)

### Expected behaviour

According to the [RFC3986](https://www.rfc-editor.org/rfc/rfc3986) links with dollar sign ('$') in them should work.

### Actual behaviour

Links with dollar sign ('$') in them are lost after sending a message. Bug appeared after updating to telegram desktop v3.4.3.

### Operating system

MS Windows 10 x64 (21H2)

### Version of Telegram Desktop

3.4.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Thanks for your report!
