### ISSUE TITLE
Partially select monospace text

### ISSUE THREAD

**Issue by Wirtos** [telegramdesktop/tdesktop#23938]
### Steps to reproduce

1. Try to select mono text while holding LMB

### Expected behaviour

Should let you select text partially

### Actual behaviour

Copies text to clipboard

### Operating system

Windows 10

### Version of Telegram Desktop

3.4.8

### Installation source

Static binary from official website

**Comment by oldherl** [comment]
Paste from #23968

> Also, the code block is only copied to the CLIPBOARD selection but not PRIMARY one, despite it's selected briefly.
> 
> I don't care what a click on the code block does, but if I drag over text on it, the dragged-over part should be selected.

**Comment by 23rd** [comment]
Please use `LMB + Alt`.
