### ISSUE TITLE
[Fearure request] Multiple aliases for account

### ISSUE THREAD

**Issue by mdziczkowski** [telegramdesktop/tdesktop#2393]
My idea is to add a possibility that the user can create many aliases to his phone number. For example:

@username1, @username2,..., @usernameN

**Comment by auchri** [comment]
No api for that

**Comment by mdziczkowski** [comment]
it wasn't meant as API, but request of feature for the next update of Telegram

**Comment by stek29** [comment]
@mdziczkowski then ask using "Ask a question" in settings or on Twitter

**Comment by Kondra007** [comment]
Nicknames cybersquatting will become much worse then. Bad feature request.

**Comment by mdziczkowski** [comment]
@stek29 I very rare use twitter, mostly because the messages are too limited to put ideas there (the messages will get cut-off)

@Kondra007 not realy... it would be usefull if the user has only one phone number and need to contact two different groups and don't want to reveal his orginal id to both of them, with could have sometimes tragic consequences

**Comment by Kondra007** [comment]
@mdziczkowski That's not the intended use of messengers.
By the way, write your suggestion, screenshot it and attach as photo in Twitter. This way you can overcome 140 symbols limit

**Comment by mdziczkowski** [comment]
@Kondra007 I think that could work... I haven thought about it this way ;)
