### ISSUE TITLE
[Feature Request] lean mode

### ISSUE THREAD

**Issue by philiparvidsson** [telegramdesktop/tdesktop#23930]
### Is your feature request related to a problem?

As the story goes with ALL software these days - the same has finally happened to Telegram. It's a piece of shit bloated softare. Back in 2016, it used to be rather lean. Quick startup, lean on features - efficient and non-distracting. No bloat in terms of code, no bloat in terms of UI features.

Where are we now? We're approaching the same piece of shit state that every software does these days. Buttons everywhere. Mindless, unnecessary buttons. Reactions, smileys, emojis. EVERYWHERE. Hover any pixel, and something pops up.

No, I don't need to be able to react to every single message with a particular feature. I don't need a poop emoji reaction - I can just type (hey, go figure, it's a CHAT APP) - "you're a dumbass". 

### Describe the solution you'd like

Either revert this piece of shit software a couple of thousand commits or implement some form of "lean mode" which disables features targeted towards retarded users or users who are of age < 12.

### Describe alternatives you've considered

Signal, Session and hanging myself.

### Additional context

Clown world.

**Comment by Younes-L** [comment]
see i totally understand and share your frustration, but tdesktop has no choice : it must follow the directives of telegram designers/marketing/management etc...
instead i suggest you make this request to an independent fork such as [forkgram](https://github.com/forkgram/tdesktop) or a client made from scratch such as [telegrand](https://github.com/melix99/telegrand) or [tok](https://invent.kde.org/network/tok) (the latter two are already lean , you can start using them today, byebye bloat !)

**Comment by etircopyh** [comment]
> byebye bloat

Yeah, right, especially since every telegram app has been made obliged to embed ads into itself.
