### ISSUE TITLE
[Feature Request]  Option to reset cloud password /  prove I`m the owner?

### ISSUE THREAD

**Issue by pingogeek** [telegramdesktop/tdesktop#23937]
### Is your feature request related to a problem?

Yes, just terminated session on my 2nd PC now can`t login again, even though I didn`t deleted my portable TG folder.
Funny thing I used it long enought and so was easy to lose access. Yes I forgot my cloud pass but I have 2 pretty working devices with TG, have lot of chats, info and sorted channels. Even more funny thing  I don`t remember setting cloud password, just confirmed by cell number and set local password

### Describe the solution you'd like

Any possible way to reset cloud password / check if it was ever set/ bug?

### Describe alternatives you've considered

Resetting account = like formatting your precious HDD drive

**Comment by 23rd** [comment]
As far as I know you can reset your cloud password.
