### ISSUE TITLE
Internal Video player doesn't send audio to currently enabled default audio device

### ISSUE THREAD

**Issue by BinaryKitten** [telegramdesktop/tdesktop#2394]
### Steps to reproduce
1. open telegram desktop
2. use usb or bluetooth audio output, connect and use as audio output
3. play audio/video in other app, audio goes to desired output
4. play video from telegram in internal player

### Expected behaviour
Audio from internal player goes to usb/bluetooth audo device

### Actual behaviour
Audio from internal player goes to standard sound card

### Configuration
**Operating system:** Windows 10 Home
**Version of Telegram Desktop:** 0.10.1

### Additional notes
If Telegram is opened AFTER the usb/bluetooth connection is made, then the internal player sends to them, but then upon disconnection of usb/bluetooth audio the audio does not return to standard sound card.

**Comment by auchri** [comment]
Duplicate #776
