### ISSUE TITLE
PDF files open in GIMP by default, cannot change files associations

### ISSUE THREAD

**Issue by olegantonyan** [telegramdesktop/tdesktop#23948]
### Steps to reproduce

1. Receive PDF file
2. Click on it - by default it will be open in GIMP
3. Click "OPEN WITH" - PDF reader (Okular) is hidden under "See More"

So to open PDF file I have to always click "OPEN WITH", then "See More" in xdg-desktop-portal-kde, scroll down to find appropriate PDF reader.

### Expected behaviour

PDF should be open in default PDF reader. Or there should be a way to configure default associations.

`xdg-open /path/to/file/pdf` opens file in default pdf reader as expected.

### Actual behaviour

Telegram doesn't use configured in KDE default file associations. PDF files open in GIMP by default. PDF reader (Okular) is hidden in "OPEN WITH" dialog. No way to configure default files associations to be used by telegram.

### Operating system

openSUSE Tumbleweed, KDE

### Version of Telegram Desktop

3.4.8

### Installation source

Static binary from official website

### Logs

```shell
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
error: : cannot open
error: : cannot open
error: : cannot open
Plug-in "script-fu"
(/usr/lib64/gimp/2.0/plug-ins/script-fu/script-fu) is installing procedure "script-fu-save-android-icons" with a full menu path "<Image>/Script-Fu/Android/Save Android Icons ..." as menu label, this deprecated and will be an error in GIMP 3.0
```

**Comment by ilya-fedin** [comment]
tdesktop uses XDG spec implementation from a library. xdg-open is a malicious bash script that launches DE's executable (so couldn't be really treated as an reference implementation, it's not even an implementation) that can have custom DE's logic rather than conforming to the XDG spec, that's what happens on KDE: KDE's mime system is not fully XDG-conforming and tdesktop doesn't support that (and won't). This is not a bug, at least not a tdesktop bug.

**Comment by olegantonyan** [comment]
Then how to change these file associations?

**Comment by olegantonyan** [comment]
```
xdg-mime query default application/pdf
okularApplication_pdf.desktop
```

**Comment by ilya-fedin** [comment]
Unset all the environment variables that can say xdg-mime that you're using KDE, then it will go to the generic XDG-conforming path

**Comment by olegantonyan** [comment]
This doesn't change anything:
```
XDG_CURRENT_DESKTOP='' XDG_CONFIG_DIRS='/etc/xdg:/usr/etc/xdg' XDG_SESSION_DESKTOP='' /home/oleg/bin/Telegram/Telegram
```

Which variable should also be unset?
```
env | grep XDG
XDG_CONFIG_DIRS=/home/oleg/.config/kdedefaults:/etc/xdg:/usr/etc/xdg
XDG_CURRENT_DESKTOP=KDE
XDG_DATA_DIRS=/usr/share
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=KDE
XDG_SESSION_ID=1
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE=x11
XDG_VTNR=7

```

**Comment by ilya-fedin** [comment]
Any variable that can say you're on KDE (i.e. any variable that has kde or plasma in it's name or value)

**Comment by olegantonyan** [comment]
Still no luck. I've unset all variables with "plasma" or "kde". (`unset KDE_SESSION_UID` and so on for each variable)
```
$ env | grep -i plasma
oleg@home:~  
$ env | grep -i kde   
oleg@home:~  
$ env | grep -i xdg
XDG_DATA_DIRS=/usr/share
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_SESSION_ID=1
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE=x11
XDG_VTNR=7
XDG_CONFIG_DIRS=/etc/xdg:/usr/etc/xdg
```

**Comment by ilya-fedin** [comment]
XDG moment :pensive:

**Comment by ilya-fedin** [comment]
I don't know what to suggest, blame the state of the cross-desktop integration in Linux. You can report this is a bug to the library tdesktop uses to open files (glib) or to KDE.

**Comment by olegantonyan** [comment]
Ok, got it. Thank you!

**Comment by olegantonyan** [comment]
Somehow I managed to find a solution
Add
```
application/pdf=okularApplication_pdf.desktop
```
to `~/.local/share/applications/mimeapps.list` section `[Default Applications]`

So this file looks like this:
```
[Added Associations]
application/x-sqlite3=SQLiteStudio.desktop;
audio/ogg=mpv.desktop;smplayer_enqueue.desktop;smplayer.desktop;audacity.desktop;deadbeef.desktop;mplayer.desktop;
audio/x-flac+ogg=mpv.desktop;smplayer_enqueue.desktop;smplayer.desktop;audacity.desktop;deadbeef.desktop;mplayer.desktop;
audio/x-opus+ogg=mpv.desktop;smplayer_enqueue.desktop;smplayer.desktop;audacity.desktop;deadbeef.desktop;mplayer.desktop;
audio/x-speex+ogg=mpv.desktop;smplayer_enqueue.desktop;smplayer.desktop;audacity.desktop;deadbeef.desktop;mplayer.desktop;
audio/x-vorbis+ogg=mpv.desktop;smplayer_enqueue.desktop;smplayer.desktop;audacity.desktop;deadbeef.desktop;mplayer.desktop;
text/x-c++hdr=kde4-kwrite.desktop;qtcreator.desktop;writer.desktop;kde4-okularApplication_txt.desktop;
text/x-c++src=kde4-kwrite.desktop;qtcreator.desktop;writer.desktop;kde4-okularApplication_txt.desktop;
video/x-ogm+ogg=mpv.desktop;smplayer_enqueue.desktop;smplayer.desktop;audacity.desktop;deadbeef.desktop;mplayer.desktop;
video/x-theora+ogg=mpv.desktop;smplayer_enqueue.desktop;smplayer.desktop;audacity.desktop;deadbeef.desktop;mplayer.desktop;
x-scheme-handler/tg=telegramdesktop.desktop;

[Default Applications]
x-scheme-handler/tg=telegramdesktop.desktop;
application/pdf=okularApplication_pdf.desktop
```
