### ISSUE TITLE
censorship free version? Question for linux and android?

### ISSUE THREAD

**Issue by crosselch** [telegramdesktop/tdesktop#23941]
Hi,
these days the censorship at telegram app within apple and android store is not acceptable but going on.
What about the linux version?
Is there a difference, if I install Telegram Desktop for Linux (ubuntu) 
from 
- ubuntu-software or 
- snapcraft.io or 
- ppa or 
- even better only to download it from telegram.org directly?
Are all the versions censorship-free?

I appreciate any tipp and help.

Second question for android smartphones.
If I once installed the Android APK directly via the telegram.org website.
What about the message within Telegram, that there is a newer version.
Can I directly click on that and start the update, or do I have to go directly to telegram.org to re-download the newest APK?

**Comment by RememberTheAir** [comment]
I don't think that any of the installation sources you mentioned apply any restriction, but I would suggest to download the binaries from https://desktop.telegram.org anyway, if you want to be sure no store-level restriction is applied

> Can I directly click on that and start the update, or do I have to go directly to telegram.org to re-download the newest APK?

The app will update itself automatically when a new version is available, you don't need to re-download anything from the website
