### ISSUE TITLE
[Feature Request] Option to disable reactions.

### ISSUE THREAD

**Issue by VasVadum** [telegramdesktop/tdesktop#23949]
### Is your feature request related to a problem?

No. Other than annoying reaction popups and clutter.

### Describe the solution you'd like

I want to disable all reactions in all private chats so that I don't have that stupid popups thing in my private chats. There's absolutely no point to have a reaction in a private chat in the first place. Reactions are a group feature, and should remain in groups/channels only. These little icons that pop up when I hover over a message for even half a second are annoying, and even worse when I move the mouse across the screen and accidentally hover over just the right spot having that stupid reaction string pop up. 

Not to mention the very limited range of the reactions is kinda pointless anyway, even for the voting feature I use it as in one group where I can only have thumb up and thumb down without any way to "abstain". If you end up adding more reactions in the future, this feature will get even more cluttered too, which I know you will, because people will request it. Especially the kiddies these days.

A simple option in the settings to disable reactions in private chats / direct messages / whatever you wanna call it, would be great. This should be account wide, not device specific. I don't want to be able to send reactions or see the reaction icon, in my private chats.

### Describe alternatives you've considered

There isn't any.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by VasVadum** [comment]
Excuse me? No. No it doesn't. Its a suggestion. This isn't a bug.

Telegram's client does not have a function in it to disable reactions in private chats. Thats what this suggestion is asking for. Explain to me, how this is a bug.

**Comment by VasVadum** [comment]
Oh I see what you mean, sorry but I was told by the volunteer support in telegram that this place is the best place to post my suggestion because such things are best carried out on one client first before they get adopted by the others. But fine, I'll copy paste everything over there where you guys can ignore it for eons.

**Comment by Aokromes** [comment]
> Excuse me? No. No it doesn't. Its a suggestion. This isn't a bug.
> 
> Telegram's client does not have a function in it to disable reactions in private chats. Thats what this suggestion is asking for. Explain to me, how this is a bug.

even the url is "bugs" it's for all.
