### ISSUE TITLE
[Feature Request] Ask for confirmation when user quits during file upload

### ISSUE THREAD

**Issue by AndydeCleyre** [telegramdesktop/tdesktop#23945]
### Is your feature request related to a problem?

Sometimes I have a long-running upload task, and hours later I'll forget and quit the app.

This quits immediately, not only cancelling the upload of the file(s) in progress, but the entire "album"/group of files, so that if 9/10 files in such a group have completely uploaded and the 10th is in progress, quitting means 0/10 are effectively uploaded, and I must upload all 10 from the beginning.

### Describe the solution you'd like

If I try to quit the app while a file is uploading, I would like a confirmation dialog to present, warning me of the ongoing operations and consequences of quitting.

Optionally, this could introduce a setting to disable said dialog, but I don't care either way, as I would keep it enabled.

### Describe alternatives you've considered

Trying to remember to poke around my chatlist before each time I quit to see if I'm about to mess up an upload.

**Comment by AndydeCleyre** [comment]
![TG_UPLOADING](https://user-images.githubusercontent.com/1787385/150421620-5f12f3d8-acef-433a-bbe9-187b45bbf10f.png)

For reference, this is what it looks like just before I quit, and you may (or may not) notice the indicator that uploads are in progress.

**Comment by 9px** [comment]
recently added a confirmation alert before exit if a file being uploaded!
i hope Telegram also add a confirmation before exit if some file is DOWNLOADing...

**Comment by Aokromes** [comment]
file upload quit confirmation implemented on 3.5.1
