### ISSUE TITLE
[Feature Request] Add option to disable formatting in a chat.

### ISSUE THREAD

**Issue by mmfedotov** [telegramdesktop/tdesktop#23951]
### Is your feature request related to a problem?

Formatting is seriously breaking software developer chats where copy snippets or logs are often pasted.

### Describe the solution you'd like

Need to add the option to chat groups to disable/deactivate formatting in a group. Whatever text is copied into a group chat, it will be present as is, as it was before.

### Describe alternatives you've considered

The only alternative it to post screenshots of the code. This is not a good alternative.

### Additional context

-

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by john-preston** [comment]
@mmfedotov You didn't describe what app you're using. If you paste any code snippets in Telegram Desktop it shouldn't get any formatting 🤔  If you mean the markdown that is parsed after you send, you can use the so-hated formatting to fix that - just paste whatever, then press Ctrl+A and Ctrl+Shift+M, then it will be sent as monospace without even markdown formatting applied after sending.

**Comment by mmfedotov** [comment]
@john-preston 
Telegram desktop 3.4.3 in ubuntu. This is the same as with entering double dashes, they are now a pain to enter, need to use delete each time, and there was not a single case for the last few decades where I would need a long dash instead of a double dash, while there are a lot of cases where I need the latter as it is a common part of command line syntax.

**Comment by mmfedotov** [comment]
@Aokromes if the message in sent to the server in the cleartext, then maybe you are right. But if the client modifies it by turning some symbols into formatting commands, then not really, perhaps changes are needed on both sides. And the client must display the message in cleartext before the message is sent, without any formatting applied. Otherwise any code exchange will have to happen via email, discord etc - telegram becomes unusable for that.

**Comment by john-preston** [comment]
@mmfedotov When you paste text how is it replaced? What if you send it in a monospace block? (that's the only supposed way to send code and other technical snippets)

**Comment by mmfedotov** [comment]
@john-preston 
Sending text like "if (abc() || cbd() || edf())" always worked fine before. Now it treats || as a formatting character, eats it up, and hides the part in the middle from the view.

**Comment by john-preston** [comment]
@mmfedotov Ah, indeed, new markup =(

Well, for now I can only suggest monospace formatting for the code snippets. In single or ternary ticks.

**Comment by AndydeCleyre** [comment]
![image](https://user-images.githubusercontent.com/1787385/153655893-1adb17ab-b573-4976-ab6b-8d601152cfc2.png)

I thought something looked off

**Comment by mmfedotov** [comment]
@AndydeCleyre Thing is, this whole formatting thing is a very exotic functionality which none I know uses at all. People were playing with for a couple days when it first appeared and then forgot about it. It is nothing but a nuisance. The formatting might be useful at (very rare) times when activated by hotkeys and explicit buttons usage but the whole auto markup thing is awful.
