### ISSUE TITLE
Not possible to paste bot command via commands suggestion list

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#2395]
### Steps to reproduce
1. Open chat with bot or group chat with bot added
2. Press `[ / ]` button to open list of commands suggestions
3. Try to paste any command **without** sending it to chat.

### Expected behaviour
Command should be pasted to message box without sending it. There's no (?) shortcut now to copy selected command to message box. Left click sends command, right click asks to "Select message". 
Look how it's made on Android: short tap sends command, long tap just pastes command to input box

### Actual behaviour
Bot command is sent to chat.

### Configuration
**Operating system:** Windows 10 LTSB x64 (does this really matter now?)
**Version of Telegram Desktop:** 0.10.2 alpha

**Comment by stek29** [comment]
<kbd>Tab</kbd>?

**Comment by Kondra007** [comment]
@stek29 Thanks for the tip!
