### ISSUE TITLE
Security Issue: Reaction Exposes Admins with Anonymous Status

### ISSUE THREAD

**Issue by foremtehan** [telegramdesktop/tdesktop#23952]
### Steps to reproduce

1. Comment somewhere
2. React on the comment with another account that has anonymous Status (admin)

### Expected behaviour

It should set anonymous account in the list and hide the real account name

### Actual behaviour

It exposes the real account behind the anonymous account and shows the real bio in the list

### Operating system

Windows 10

### Version of Telegram Desktop

v3.4.8

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment]
This is most likely intended, and tdesktop implemented it correctly. If you think this behavior should be changed, you should bring this to https://bugs.telegram.org

**Comment by foremtehan** [comment]
So we cannot anonymously react on messages ? and the only option is creating another account ? doesnt really make sense

**Comment by foremtehan** [comment]
This is 100% wrong decision, I reported the issue
