### ISSUE TITLE
QT6 fractional scaling in new versions results in pixilated images on linux

### ISSUE THREAD

**Issue by chermnyx** [telegramdesktop/tdesktop#23953]
### Steps to reproduce

0. Build telegram with qt6
1. Enable fractional scaling on x11 in KDE settings
2. Check "Default interface scale" in telegram
3. Restart telegram

### Expected behaviour

Telegram uses built-in scaling and pictures are scaled properly

### Actual behaviour

Pictures are pixilated
![Screenshot_20220121_202333](https://user-images.githubusercontent.com/27727194/150552947-84c5e9be-1984-4ac5-a2c0-34a35da99155.png)
![Screenshot_20220121_202407](https://user-images.githubusercontent.com/27727194/150553041-4e2f8720-c9a2-4ee9-9cc2-1f626b076a49.png)

### Operating system

ArchLinux

### Version of Telegram Desktop

3.4.8

### Installation source

[ArchLinux packages](https://archlinux.org/packages/community/x86_64/telegram-desktop/)

**Comment by ilya-fedin** [comment]
Yeah, fixing this requires too much changes, actually almost full rewrite of all the UI widgets of tdesktop I guess. So the only thing I can suggest is to disable Qt scaling on your system.

**Comment by chermnyx** [comment]
Is it possible to turn off qt scaling for telegram only? (the default behavior for qt5 builds of telegram)

**Comment by ilya-fedin** [comment]
No, Qt removed the possibility to disable scaling in app code in Qt 6. Although, it's still possible to disable fractional scaling and Telegram uses `QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::Floor);`, so Qt shouldn't apply fractional scaling, but KDE doesn't uses intended ways of telling DPI to Qt, instead, KDE uses [environment variables intended for debugging](https://doc.qt.io/qt-6/highdpi.html) and bypasses whatever application sets.

**Comment by vimpostor** [comment]
You could try using `export PLASMA_USE_QT_SCALING=1`

**Comment by ilya-fedin** [comment]
This is a variable for plasmashell, it won't affect Telegram (and, moreover, will enable Qt's broken scaling on Plasma itself just like on Telegram)

**Comment by vimpostor** [comment]
FYI if you have fractional scaling set in KDE, you can work around this issue by unsetting `QT_SCREEN_SCALE_FACTORS` just for tdesktop again. For example, put in your desktop file the following line:
`Exec=env 'QT_SCREEN_SCALE_FACTORS=' telegram-desktop -- %u`
And don't forget to run `update-desktop-database ~/.local/share/applications`.

This fixed the blurry icons on Qt6 for me.

**Comment by ilya-fedin** [comment]
That would lead all child processes to lose scaling capability. E.g. if you run Okular by opening a pdf file in tdesktop, it would run unscaled.

**Comment by vimpostor** [comment]
> That would lead all child processes to lose scaling capability. E.g. if you run Okular by opening a pdf file in tdesktop, it would run unscaled.

I know, still better than those horribly scaled icons. I am fine with opening downloaded files with a file manager.
