### ISSUE TITLE
In calling, plug in the headphones, and the sound output did not auto switch

### ISSUE THREAD

**Issue by chifandeyu** [telegramdesktop/tdesktop#23959]
### Steps to reproduce

1. Call the voice whit my contact
2. Enter the voice call
3. Plug in the headphones into your laptop

### Expected behaviour

Sound does not automatically switch to the headphones. then no output audio

### Actual behaviour

The output audio should be automatically switch to the headphones.

### Operating system

windows 10/11

### Version of Telegram Desktop

3.4.8

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#9814
