### ISSUE TITLE
[Question] latest windows VS x64 build is blocked by windows defender

### ISSUE THREAD

**Issue by kirsan31** [telegramdesktop/tdesktop#23957]
![image](https://user-images.githubusercontent.com/17767561/150585362-fa529d8b-057d-456e-9240-b3eaf2a8d31e.png)
[Trojan:JS/WinShow.N](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aJS%2fWinShow.N&threatid=2147537751)

Error from VS: 
```
The system cannot open the device or file specified.
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(242,5): error MSB8066: Custom build for '...\TBuild\tdesktop\out\CMakeFiles\363dde0837510b0dae0b1dc48455efde\td_ui_style.timestamp.rule;...\TBuild\tdesktop\out\CMakeFiles\f52b63bf3af1a90a2eb4e40a25e6ffc1\td_ui_styles.rule' exited with code 1.
Done building project "td_ui_styles.vcxproj" -- FAILED.
```

I understand that this is false positive, but any way...

**Comment by Aokromes** [comment]
report false positive to microsoft.

**Comment by john-preston** [comment]
@kirsan31 yup, I see the same.

I reported it as a false positive and didn't get any response yet.

It instantly removes a batch script with .cmd extension in a temp folder that apparently cmake generates yo execute the custom build rule for style code generator.
