### ISSUE TITLE
[Feature Request] Gif Sorting / Folders

### ISSUE THREAD

**Issue by VasVadum** [telegramdesktop/tdesktop#23950]
### Is your feature request related to a problem?

The problem is Gifs have randomness to them based on when you last clicked and are hard to filter.

### Describe the solution you'd like

I would like to see the ability to create folders inside the Gif tab, that work account wide and spread to other devices you use, then the ability to move gifs into those folders so that you can sort between animal gifs, meme gifs, food gifs, whatever else you might have. I've prepared an example ages back before this place was ready for feedback. I will put those at the bottom.

It would also be good, to edit gifs to add tags to them, so that you can search for them by tag instead of by their file name which could be literally anything even a string of numbers and random characters.

### Describe alternatives you've considered

I deleted my gifs, and created a special channel to store them all in and sent them there with hash tags to describe them, but its an inefficient system and kinda sucks. I'd rather we just fix the existing system to be better.

### Additional context

![image](https://user-images.githubusercontent.com/1490797/150507789-3f9dcdb1-9565-4e63-8341-d2e7b1a0ff95.png) 
![image](https://user-images.githubusercontent.com/1490797/150507913-8d890ad6-68ca-4b91-9def-30af3589cb33.png)

**Comment by 23rd** [comment]
https://bugs.telegram.org/c/2479

**Comment by VasVadum** [comment]
Yes, lets close this which has detailed examples and previews and use a slight detailed bug report with no images or anything to help the dev teams figure out what I meant for a good working gif system.
