### ISSUE TITLE
Only the first image of a tweet can be previewed

### ISSUE THREAD

**Issue by bpierre** [telegramdesktop/tdesktop#2396]
### Steps to reproduce
1. Open a discussion
2. Paste a tweet URL containing several images
3. Only the first image appears in the preview
### Expected behaviour

I would like to have a direct access to the other images in the tweet, or at least an indication that other images are missing and the tweet need to be clicked.

A solution could be to display more images in the tweet preview:

![](https://scri.ch/ukt.png)

Or to have a way to expand from one image to several:

![](https://scri.ch/uky.png)
![](https://scri.ch/ukv.png)
### Actual behaviour

The current solution does not provide enough information:

![](https://scri.ch/uks.png)

**Comment by bpierre** [comment]
👋 Any update?

**Comment by dogancelik** [comment]
Yes, this would be very nice feature! 👍

**Comment by 23rd** [comment]
This issue can be closed now.
https://github.com/telegramdesktop/tdesktop/commit/bf31722931b6cae2ac56bc52de53679c98ef19fd
https://github.com/telegramdesktop/tdesktop/commit/251f51ca1bae3788f84e41dd7b40b44081ac4c3e

**Comment by bpierre** [comment]
@23rd are these commits merged / released?
