### ISSUE TITLE
Window doesn't restore to last used position with 'close to tray' enabled

### ISSUE THREAD

**Issue by TKIPisalegacycipher** [telegramdesktop/tdesktop#23963]
Telegram Desktop v3.4.8 x64 (Windows 11)

Expectation: Window always restores to last used window position, including snap layouts, when restoring from taskbar or tray. Especially with the announcement of Win11 Snap Layout support 

Actual: If you enable 'close to tray' then the client simply will not remember the window position. Doesn't seem to matter if you used snapping or not. Confirmed on Windows 11 21H2 (OS Build 22000.434) and Telegram desktop client. This is similar to #1693, #4475, and #8999. 

Disabling close to tray, and using close to taskbar instead, is a workaround. But dang, this bug is annoying.

**Comment by ilya-fedin** [comment]
Nothing changed since then, this is still a Qt bug https://bugreports.qt.io/browse/QTBUG-59668
