### ISSUE TITLE
ability to change group or chanel names for personal use [Feature Request] 

### ISSUE THREAD

**Issue by gmareater** [telegramdesktop/tdesktop#23964]
### Is your feature request related to a problem?

I want to subscribe to some channels, but because of their name (mostly impolite), and that I need to open Telegram in public places, I can't join them.
so it would be handy if I could rename them for my personal uses

### Describe the solution you'd like

F2 :) 

### Describe alternatives you've considered

hide some channel name by default (just name and logo)
if you hide them I will forget about them

### Additional context

In home office with children it is very handy thing to have

**Comment by Aokromes** [comment]
i suggest you to archive them.

such feature belongs to https://bugs.telegram.org/

**Comment by gmareater** [comment]
why you close [feature request] if you dont get what it suppose to do?
I already know and do archive them, but it's not solving solution.
if you start to read the channel and some child or coworker came to room, it create unwanted situation.
but with renaming, you have control
