### ISSUE TITLE
Font/text rendering issues

### ISSUE THREAD

**Issue by Ryder17z** [telegramdesktop/tdesktop#23969]
### Steps to reproduce

unknown.

### Expected behaviour

Proper spacing. 

### Actual behaviour

the word "they" does not look right. the E is too close to the Y
![image](https://user-images.githubusercontent.com/2000703/150816706-52d0d9a9-937d-40b8-b1a5-d3b0ea4d6318.png)

Same goes for "even" when E has a V after it
![image](https://user-images.githubusercontent.com/2000703/150817068-15918b28-bc18-4f1a-8695-90d83f12c219.png)

### Operating system

Manjaro Linux 21.2.1

### Version of Telegram Desktop

3.4.8

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#17221

**Comment by Ryder17z** [comment]
I did not find that because of the obscure title.
