### ISSUE TITLE
Unread message count doubled after standby

### ISSUE THREAD

**Issue by Mezgrman** [telegramdesktop/tdesktop#23973]
### Steps to reproduce

1. Put computer in standby or hibernate mode while Telegram Desktop is running
2. Next day, wake up from standby/hibernate
3. Look at Telegram Desktop

### Expected behaviour

The message counters in all chats show the actual number of unread messages.

### Actual behaviour

The message counters show exactly twice the number of unread messages. e.g. if there are three unread messages in a group, it will show 6. If there's one new message in a private chat, it will show 2. After reading the messages, the counter will work normally again.

### Operating system

Windows 10 20H2

### Version of Telegram Desktop

3.4.8 x64

### Installation source

Static binary from official website

**Comment by Mezgrman** [comment]
This has been consistently happening for around a year or maybe even longer. I have multiple devices attached to my account, in case it should matter.

**Comment by ms-fastlta** [comment]
I've been seeing this on Ubuntu in the web client for quite a while (months?)

**Comment by vimpostor** [comment]
Can't reproduce on Linux, can you be more specific how to get to that broken state?
Does the computer need to be on standby for a certain amount of time?
If I open Telegram, and have an unread message, then go to Standby, immediately wakeup the computer, the counter still shows 1 for me.

**Comment by Mezgrman** [comment]
Might need a night of rest... I always get it when resuming from hibernate / standby the next morning. So I think time plays a role.
