### ISSUE TITLE
Creating a call invitation in a group.

### ISSUE THREAD

**Issue by Yosh11** [telegramdesktop/tdesktop#23979]
### Steps to reproduce

1. Create video chat room.
2. Select the users to invite for video call.
3. Send an invitation to a group.
4. Try to click on the user names that are listed in the invitation.

### Expected behaviour

If you click on the name referring to the profile of the invitee then go to his profile.
![image](https://user-images.githubusercontent.com/26243797/151144042-3c1f6792-b418-422c-9016-56ed6c665607.png)

### Actual behaviour

You go to the user profile that is in the list in front of the user you click on.
If you click on the user who created the invitation, go to the call window, and not to the profile of this user.

### Operating system

Windows 10 Pro, 20H2

### Version of Telegram Desktop

v 3.4.8 x64

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment]
It seems that the link to the video chat and the invited user are swapped, even if a single person is invited
