### ISSUE TITLE
Scrolling not possible

### ISSUE THREAD

**Issue by michaelhjulskov** [telegramdesktop/tdesktop#23974]
### Steps to reproduce

start app and try to scroll

### Expected behaviour

I cant scroll in the linux app
Suddently i cant scroll. 
Neither in contacts in left side - Nor in messages in right side of screen. 
I havent tried restart computer yet.
But I restarted the TG app and that didnt help

### Actual behaviour

Nothing happens when I scroll. 
I tested my scroll in other software - it works fine.
I can click on the replied messages, and it scrolls up to the message, but still i cant croll down again.

### Operating system

Linux Xubuntu updated

### Version of Telegram Desktop

3.4.3

### Installation source

Snap

**Comment by ilya-fedin** [comment]
https://bugreports.qt.io/browse/QTBUG-98720
