### ISSUE TITLE
scroll in reactions

### ISSUE THREAD

**Issue by motahharm** [telegramdesktop/tdesktop#23985]
### Steps to reproduce

1. in messages
![Uploading Screenshot 2022-01-28 110019.png…]()

### Expected behaviour

# Emoji 🎉 better available.

### Actual behaviour

# Emoji 🎉 is not well seen in reactions

### Operating system

Windows 10 , 64bit

### Version of Telegram Desktop

3.4.8

### Installation source

Static binary from official website

**Comment by motahharm** [comment]
![Screenshot 2022-01-28 110019](https://user-images.githubusercontent.com/78138597/151506170-91a42388-92ac-4325-a81d-a44fdfa04af1.png)
![Screenshot 2022-01-28 110048](https://user-images.githubusercontent.com/78138597/151506177-d51df452-36e0-45dc-850a-96dd30e79da4.png)
This is images

**Comment by john-preston** [comment]
Thanks for your report. I think I need to limit a single scroll action to three reactions at most.

**Comment by motahharm** [comment]
> Thanks for your report. I think I need to limit a single scroll action to three reactions at most.

Yes, it's great and the graphics of the Telegram program are also great. Thank you very much to your team for your good program
