### ISSUE TITLE
Failed to build on Linux (failed to prepare libraries)

### ISSUE THREAD

**Issue by Henry-ZHR** [telegramdesktop/tdesktop#23980]
### Steps to reproduce

Just follow the [build instructions](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md)

### Expected behaviour

It builds successfully

### Actual behaviour

When executing `docker build -t tdesktop:centos_env Telegram/build/docker/centos_env/`, it fails

```text
...
Step 23/475 : RUN yum -y install https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm && yum clean all
 ---> Running in 93c70f2edda3
Loaded plugins: fastestmirror, ovl
Cannot open: https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm. Skipping.
Error: Nothing to do
The command '/bin/sh -c yum -y install https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm && yum clean all' returned a non-zero code: 1
```

### Operating system

Debian GNU/Linux 10 (buster)

### Version of Telegram Desktop

v3.4.8

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
It seems, the domain is no longer valid :thinking:

**Comment by Aokromes** [comment]
domain have ip removed, it looks amazon broke something.
