### ISSUE TITLE
[Feature Request] Quote phrase from message

### ISSUE THREAD

**Issue by Gnevyshev** [telegramdesktop/tdesktop#23984]
### Is your feature request related to a problem?

Quoting the entire message of the interlocutor is not useful. When you want to show exactly one of the phrases in his message.

### Describe the solution you'd like

If you selected the phrase - clicked Reply - you answered exactly this phrase.

### Describe alternatives you've considered

I think everything is clear here without alternatives.

### Additional context

Please add the ability to respond to messages with the display of exactly the right quote (phrase) from the interlocutor's message.
If you selected the message phrase - clicked Reply - you answered exactly this phrase.

My previus issue (closed): https://github.com/telegramdesktop/tdesktop/issues/16638

**Comment by Aokromes** [comment]
it must be implemented plataform wide.
such feature belongs to https://bugs.telegram.org/
