### ISSUE TITLE
The Socks5 feature of ClashX cannot be used

### ISSUE THREAD

**Issue by tangxiaona** [telegramdesktop/tdesktop#23981]
![image](https://user-images.githubusercontent.com/26104576/151300518-37c4f9e0-c966-428f-bb74-92f9c94e985b.png)
![image](https://user-images.githubusercontent.com/26104576/151300540-e18b0ea0-afdd-4301-aaf0-f26f0c39c360.png)
**It is always loaded. What is the reason**

**Comment by Aokromes** [comment]
what's the version of telegram you use? 8.x? if yes, you are using https://github.com/overtake/TelegramSwift

**Comment by john-preston** [comment]
This is another application, https://github.com/overtake/TelegramSwift

You can try Telegram Desktop from https://desktop.telegram.org
