### ISSUE TITLE
59ed41a <Alt> modifier conflicts with (and loses to) DE's window move/resize modifier 

### ISSUE THREAD

**Issue by Younes-L** [telegramdesktop/tdesktop#23983]
### Steps to reproduce

1. launch telegram on a cinnamon session
2. open a chat
3. send or receive a message with a link or a single line of `monospaced` text (to activate the click-to-copy feature)
4. Hold `Alt` and click/double-click/drag the link or monospaced text

### Expected behaviour

normal text selection occurs (nothing on single click, select word on double click, ...)

### Actual behaviour

mouse pointer transforms into window mover, and telegram window is moved on `Alt+drag`, due to this default setting in `grouped-window-list@cinnamon.org`

![image](https://user-images.githubusercontent.com/23421600/151479028-064b032a-db5b-4928-b752-ddd6eaa473bc.png)

I do understand that this new 59ed41a alt+click behaviour/modifier is undocumented, subject to change, and may never make it to any pre-release or release, just thought i'd point this out preemptively x)  
As `Alt` is often used for system functionality (and both `Ctrl` and `Super` are alternatives to `Alt` in grouped-window-list), would it be possible to use `Shift` instead ? It's pretty safe and currently select + shift click doesn't work so no functionality would be lost by using Shift as the modifier

### Operating system

fedora, 34, cinnamon

### Version of Telegram Desktop

built from source 7170bec

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
This feature was made for people who use the hold Alt selection to select parts of links in browsers (both Firefox and Chromium). If you have the window manager set up instead, then you don't need this feature.
