### ISSUE TITLE
Includes in Windows build

### ISSUE THREAD

**Issue by shurrman** [telegramdesktop/tdesktop#23986]
Hi! I am trying to build a TDesktop  on Windows 11 (VS 2022)
Following th readme, I have all 3rd party tools installed, checkout things, submodules, prepare .bat, configure...
However when building - I get errors because of missing `base/qt*` stuff
And indeed - there are [includes](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/core/local_url_handlers.cpp#L15) - there is no "base/" in SourceFiles.
Am I missing somthing?
Thanks in advance

**Comment by john-preston** [comment]
@shurrman git submodule update
