### ISSUE TITLE
Linux not building

### ISSUE THREAD

**Issue by shurrman** [telegramdesktop/tdesktop#23988]
### Steps to reproduce

 docker run --rm -it -v $PWD:/usr/src/tdesktop tdesktop:centos_env /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh -D TDESKTOP_API_ID=XXXXX -D TDESKTOP_API_HASH=YYYYYYYYYY -D DESKTOP_APP_USE_PACKAGED=OFF -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF

--   No package 'webkit2gtk-4.0' found
CMake Error at /opt/cmake/share/cmake-3.21/Modules/FindPkgConfig.cmake:562 (message):
  A required package was not found
Call Stack (most recent call first):
  /opt/cmake/share/cmake-3.21/Modules/FindPkgConfig.cmake:784 (_pkg_check_modules_internal)
  Telegram/lib_webview/CMakeLists.txt:57 (pkg_check_modules)

### Expected behaviour

build success

### Actual behaviour

no errora

### Operating system

Windows 11 x64 WSL2

### Version of Telegram Desktop

dev (=3.3.0)

### Installation source

Static binary from official website

### Logs

```shell
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.22.30
-- Checking for module 'webkit2gtk-4.0'
--   No package 'webkit2gtk-4.0' found
CMake Error at /opt/cmake/share/cmake-3.21/Modules/FindPkgConfig.cmake:562 (message):
  A required package was not found
Call Stack (most recent call first):
  /opt/cmake/share/cmake-3.21/Modules/FindPkgConfig.cmake:784 (_pkg_check_modules_internal)
  Telegram/lib_webview/CMakeLists.txt:57 (pkg_check_modules)
```

**Comment by shurrman** [comment]
That is a Dockerfile!
Tried to add

RUN yum -y install webkitgtk4

no help

**Comment by ilya-fedin** [comment]
> dev (=3.3.0)

But dev is far away from 3.3.0 now...

**Comment by shurrman** [comment]
> > dev (=3.3.0)
> 
> But dev is far away from 3.3.0 now...

mistake, it is fresh clone

**Comment by shurrman** [comment]
trying to add  webkitgtk4-devel also
However... it is a Dockerfile - everyone should have the same result...

**Comment by shurrman** [comment]
Worked... anyone interested in a PR? Or am I the olny one with this problem (suppose not)?

**Comment by ilya-fedin** [comment]
> mistake, it is fresh clone

It can't be because webkit2gtk is not needed on build time in recent versions

**Comment by shurrman** [comment]
> > mistake, it is fresh clone
> 
> It can't be because webkit2gtk is not needed on build time in recent versions

Are you saying that I invented error lines myself? 
1. "Got -- No package 'webkit2gtk-4.0' found"
2. Added "yum install webkitgtk4-devel"
3. Build became successfull.
Will try on another box from scratch and may be record the video ))

**Comment by shurrman** [comment]
Let me double check, thanks. Quite sure that I pulled latest dev...

**Comment by shurrman** [comment]
Cloned from scratch - there is also an issue with endpoint repo. I had to change the repo URL in the Dockerfile:
`RUN yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm && yum clean all
RUN sed -i 's#packages\.endpoint\.com#packages\.endpointdev\.com#' /etc/yum.repos.d/endpoint.repo`

**Comment by ilya-fedin** [comment]
If the initial issue is solved, please close the issue

**Comment by Aokromes** [comment]
yeah that endpoind repo thing is because https://github.com/telegramdesktop/tdesktop/pull/23989 not yet merged.
