### ISSUE TITLE
I can no longer send private messages because I am blocked

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#23997]
### Steps to reproduce

Hi,

So I belong to tons of groups, and sometimes I reach out to people in the group if we seem to have the same interests or they need help with something or they offer help or I need to ask them a question privately.

Well I reached out to two people just now to tell them something they didn't know, and within less than 5 minutes I was now BLOCKED from sending anyone who's not a mutual contact a message. 

This is TERRIBLE.

I am NOT a spammer!

This now means I wont be able to reach out to people if I need help with something & right now I do need help, and even with people I've already PMed with because I'm sure not everyone adds me to their contact because I myself don't add everyone to my contact until we've been talking for at least a month.

Please, how do I get out of this. 

To block me from doing this for 24 hours, okay, but until May??? 

Please help.

Thanks

### Expected behaviour

Not block me, or at least give a warning.

### Actual behaviour

Blocked for months

### Operating system

Win 8.1

### Version of Telegram Desktop

3.5x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
this is a BUG tracker, not an user support i sugest you to contact support in app.
