### ISSUE TITLE
[Feature Request] Deleting multiple chats

### ISSUE THREAD

**Issue by Arunachala-Ramana** [telegramdesktop/tdesktop#23991]
### Is your feature request related to a problem?

Is it possible to delete multiple chats while using Telegram-desktop?

### Describe the solution you'd like

Would like to delete multiple chats all at once my first marking them and then pressing the delete button. 

### Describe alternatives you've considered

The only alternatives that is available now is deleting each chat individually which is boring and laborious process.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4079
