### ISSUE TITLE
[Behaviour] Notifications on every device despite desktop being active

### ISSUE THREAD

**Issue by ToothyDev** [telegramdesktop/tdesktop#23999]
### Steps to reproduce

Open Telegram desktop and mobile
Ask a friend send you a message
Receive the notifications on both platforms at the same time, which is not cool, especially if you have loud notifications

### Expected behaviour

When Desktop is active, there shouldn't be mobile notifications. Once Desktop is detected as inactive (the same way Discord does) it will only then send it on mobile

### Actual behaviour

Notifications appear on both devices simultaneously

### Operating system

Windows 10 21H2

### Version of Telegram Desktop

3.5 x64

### Installation source

Static binary from official website

**Comment by electrofloat** [comment]
https://github.com/telegramdesktop/tdesktop/issues/277
