### ISSUE TITLE
how to configure email

### ISSUE THREAD

**Issue by ruv** [telegramdesktop/tdesktop#2399]
How to change the recovery email address in Telegram Desktop?

**Comment by auchri** [comment]
It's not possible atm.

**Comment by ruv** [comment]
Thank you for the info.
Does it make sense to fill a feature request as separate issue?

**Comment by auchri** [comment]
No, there's already one.

**Comment by john-preston** [comment]
@ruv Just remove the password and set it once again with another email.

**Comment by ruv** [comment]
@john-preston thanks for the hint — this workaround is working and acceptable.
Although, it seems that ideally there should be UI to change the email address only.
