### ISSUE TITLE
Emoticons

### ISSUE THREAD

**Issue by auchri** [telegramdesktop/tdesktop#24]
Please use the same emoticons as the Android client: http://apps.timwhitlock.info/emoji/tables/iphone#apple , because they look very different some times

**Comment by duub** [comment]
the apple emoticons are very uggly!!! Please let android users have nice emojis! :+1:

**Comment by auchri** [comment]
Thats Telegram for Desktop.

**Comment by duub** [comment]
sorry... I said it wrong! I wanted to say that let desktop users enjoy de android emojis :P

**Comment by auchri** [comment]
Have a look at this discussion: https://github.com/DrKLO/Telegram/pull/625

**Comment by duub** [comment]
Everything is ok, there are other issues more important...

**Comment by mahdiG** [comment]
These emojis are ugly IMO. What about ability to import emojis? Then like stickers people can create a lot of them and use them.

**Comment by auchri** [comment]
@mahdiG Feel free to implement it yourself
