### ISSUE TITLE
Window Opening to wrong size

### ISSUE THREAD

**Issue by lasmaty07** [telegramdesktop/tdesktop#24006]
### Steps to reproduce

1. open telegram desktop
2. resize windows to desired size
3. quit telegram
4. reopen telegram. 

- This happens on my second monitor, on portrait mode, with 100% scaling (on windows and telegram), HD resolution.

- does not happen on my first monitor, UDH resolution, 150% scaling (windows and telegram)

I belive this is similar to [#6924](https://github.com/telegramdesktop/tdesktop/issues/6924) and [#6804](https://github.com/telegramdesktop/tdesktop/issues/6804)

### Expected behaviour

The window should open with the configured size on step 2.

### Actual behaviour

- The window opens on the "default" size.

This is before closing, with te configured window size:
![imagen](https://user-images.githubusercontent.com/25487723/152087441-4107fc42-5625-4a4c-90bc-04b0c2df0324.png)

after closing and reopening, this is how it looks like

![imagen](https://user-images.githubusercontent.com/25487723/152087572-326b256b-e345-4d2b-93ad-12c3d8ff73b3.png)

### Operating system

Windows 10 x64

### Version of Telegram Desktop

3.5 x64

### Installation source

Static binary from official website

**Comment by richardmtl** [comment]
This is happening to me as well, on macOS. Every time I open, it changed to being Full screen after a few seconds.

**Comment by richardmtl** [comment]
I just had this happen to me in Tweetbot! So I think maybe it's a macOS issue and not Telegram-specific.
