### ISSUE TITLE
Problems with non-sticker webm with VP9

### ISSUE THREAD

**Issue by Remu-rin** [telegramdesktop/tdesktop#24003]
### Steps to reproduce

1. Open https://t.me/webm_tdesktop_bug

### Expected behaviour

Should play normally.

### Actual behaviour

VP9 + vorbis/opus are shown as video, but won't play internally. They are downloaded and opened in external player.
VP9 without audio plays, but displayed duration is bugged and/or bugs/slows when seeking.

VP8 + vorbis/opus seems to work.

### Operating system

Windows 10

### Version of Telegram Desktop

3.5

### Installation source

Static binary from official website

**Comment by MatthewRobertDunn** [comment]
Interestingly the example given all 100% works for me on windows 10 version 3.7.3

Some of my friends using the same version of telegram NONE of them work.

![image](https://user-images.githubusercontent.com/15967209/171077125-d04352d8-4278-4113-aca0-1ad7c6a93dab.png)

**Comment by Aokromes** [comment]
maybe the bug is lack of system codecs?

try downloading https://get.daum.net/PotPlayer/Codec/OpenCodecSetup64.exe or https://get.daum.net/PotPlayer/Codec/OpenCodecSetup.exe

**Comment by Remu-rin** [comment]
I thought it is a server-side thing now. When I created this issue, vp9 was bugged/not supported in tdesktop. Then vp9 got fixed, but video/file behavior became inconsistent. Sometimes all posts in that channel are files, sometimes all are videos. And most of the time part of them are videos and part of them are files. Even vp8 ones are fluctuating.

On Android webm are always still a file, so if anyone wants webm as video on every Telegram client, vote here: https://bugs.telegram.org/c/2364

**Comment by egzakharovich** [comment]
TDesktop 4.3.3 Windows 10
It's even worse at this moment, webm's don't play as videos at all.

![image](https://user-images.githubusercontent.com/68099035/204229298-c4497324-b4a5-4c86-8ee6-45c503382264.png)

**Comment by john-preston** [comment]
This is regulated by the server :( It has attributes with a thumbnail and with a flag that the file is streamable. For now it returns no thumbnail and no flag, I guess because Android in some versions was showing any such file as a sticker and it was bad.
