### ISSUE TITLE
[Feature Request] notification popup screen and direct reply

### ISSUE THREAD

**Issue by flint002** [telegramdesktop/tdesktop#2400]
I work in customer service
I think this will facilitate me and similar  job

**Comment by stek29** [comment]
What is "this"? Can you please explain it?

**Comment by flint002** [comment]
popup dialog ? popup modal ?
similiar like this link http://plnkr.co/edit/NuggyhaObqCjsBmBfrRo?p=preview
i hope you understand
thank you

**Comment by stek29** [comment]
@flint002 Your demo is awesome XD
But I'm not sure users would like to see pop-ups on top of everything every time they receive a message.
I can't imagine when it may be useful for customer services either.

But TDesktop is open source, and you can implement this on your own :)

**Comment by flint002** [comment]
@stek29 thank you .. i will learn hard for that :D


awesome update on tdekstop v 0.10.16 
thank you for telegram developer
