### ISSUE TITLE
Linux app doesn't respect system scroll speed

### ISSUE THREAD

**Issue by christodenny** [telegramdesktop/tdesktop#24007]
### Steps to reproduce

1. Modify touchpad scrolling speed in settings
2. Scroll in telegram
3. Regardless of scroll speed set in OS settings, telegram scrolls at the same (overly sensitive) speed

### Expected behaviour

Telegram scroll sensitivity should change proportional to OS scroll speed setting

### Actual behaviour

Telegram scroll sensitivity stays the same regardless of OS scroll speed sensitivity. For me this speed is personally too fast (e.g. makes it hard to precisely scroll to the right emoji when trying to react to a message. I overshoot since it scrolls so fast)

### Operating system

Manjaro, KDE 5.23.5, Wayland

### Version of Telegram Desktop

3.5.0

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Telegram doesn't use system settings for anything in UI, this is not a bug
