### ISSUE TITLE
Packaged Building page lacks latest dependencies

### ISSUE THREAD

**Issue by catdevnull** [telegramdesktop/tdesktop#24001]
### Steps to reproduce

Suggested changes:

```markdown
    * [Mesa3D](https://www.mesa3d.org/) (required)
    * [libepoxy](https://github.com/anholt/libepoxy) (required)
    * [libdrm](https://dri.freedesktop.org/wiki/) (required)
```

### Expected behaviour

Should have new dependencies

### Actual behaviour

Doesn't

### Operating system

.

### Version of Telegram Desktop

.

### Installation source

Other (unofficial) source

**Comment by john-preston** [comment]
Which page? 🤔

**Comment by catdevnull** [comment]
https://github.com/telegramdesktop/tdesktop/wiki/The-Packaged-Building-Mode

**Comment by ilya-fedin** [comment]
Well, it doesn't need entire mesa, it needs only libgbm from it

**Comment by catdevnull** [comment]
I guess that's true. All of mesa headers in Alpine Linux are packaged into `mesa-dev` although gbm itself is in `mesa-gbm`.

**Comment by ilya-fedin** [comment]
Ok, I updated the page
