### ISSUE TITLE
snap is not working on CentOS 7

### ISSUE THREAD

**Issue by qtlin** [telegramdesktop/tdesktop#24017]
### Steps to reproduce

$ snap install telegram-desktop
$ snap run telegram-desktop

### Expected behaviour

normal start up

### Actual behaviour

telegram-desktop: error while loading shared libraries: libQt6Core.so.6: cannot open shared object file: No such file or directory

### Operating system

CentOS 7.9, kernel 3.10

### Version of Telegram Desktop

telegram-desktop   3.4.3            3544   latest/stable

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Well, snaps are mostly Ubuntu-oriented, I'd suggest to switch to the official binary from https://desktop.telegram.org

**Comment by qtlin** [comment]
Well, snaps are designed to be platform independent. That is the whole purpose of a snap. If snap does not work on an OS then it is either snapd or snap creator problem. Since several other snaps I tried on CentOS 7.9 work without complains then it is clearly telegram-desktop snap error.

**Comment by ilya-fedin** [comment]
But if your OS can't find Qt libraries then something is really bad with your OS :(

**Comment by qtlin** [comment]
Incorrect. All libraries are provided by snap and are verified as present, including  `libQt6Core.so.6`, in snap. The error message says `No such file or directory` because loader prints this message on any error it encounters upon failed library load. 
```
$ snap run --shell telegram-desktop
bash-5.0$ ldd /snap/telegram-desktop/3544/usr/lib/x86_64-linux-gnu/libQt6Core.so.6           
	linux-vdso.so.1 (0x00007ffd3bf9c000)
	libicui18n.so.66 => /snap/telegram-desktop/3544/usr/lib/x86_64-linux-gnu/libicui18n.so.66 (0x00007ff4352eb000)
	libicuuc.so.66 => /snap/telegram-desktop/3544/usr/lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007ff435105000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff4350e9000)
	libglib-2.0.so.0 => /snap/telegram-desktop/3544/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007ff434fc0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff434f9d000)
	libz.so.1 => /snap/telegram-desktop/3544/lib/x86_64-linux-gnu/libz.so.1 (0x00007ff434f7f000)
	libpcre2-16.so.0 => /snap/telegram-desktop/3544/usr/lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007ff434efc000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff434d1a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff434bcb000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff434bb0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff4349be000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff435bbe000)
	libicudata.so.66 => /snap/telegram-desktop/3544/usr/lib/x86_64-linux-gnu/libicudata.so.66 (0x00007ff432efb000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007ff432e88000)
bash-5.0$
```
However
```
bash-5.0$ ldd /snap/telegram-desktop/3544/usr/bin/telegram-desktop | grep not
	libQt6Core.so.6 => not found
	libQt6Core.so.6 => not found
	libQt6Core.so.6 => not found
	libQt6Core.so.6 => not found
	libQt6Core.so.6 => not found
	libQt6Core.so.6 => not found
	libQt6Core.so.6 => not found
	libQt6Core.so.6 => not found
	libQt6Core.so.6 => not found
	libQt6Core.so.6 => not found
bash-5.0$ 
```

**Comment by ilya-fedin** [comment]
> because loader prints this message on any error it encounters upon failed library load

How to get actual error though? :thinking:

**Comment by qtlin** [comment]
I have no idea how to get actual error. I believe that libQt6Core.so.6 provided by telegram-desktop snap is incompatible with CentOS 7 kernel-3.10.0. I have never seen that a library fails to load in one kernel but not in newer but here it is definitely the case. Please recompile libQt6Core.so.6 and make it compatible with CentOS 7.

**Comment by ilya-fedin** [comment]
Apparently, Qt uses some APIs from newer kernel. Sorry, but it seems you should update kernel in order to use tdesktop snap.

**Comment by qtlin** [comment]
CentOS does not officially provide newer kernel. A snap customer is dead in the water because telegram-desktop fails to check basic compatibility. At the same time a binary from telegram web site works  just fine with kernel-3.10.

**Comment by ilya-fedin** [comment]
> At the same time a binary from telegram web site works just fine with kernel-3.10.

Hmm...

**Comment by qtlin** [comment]
@Aokromes please don't close unresolved tickets.

**Comment by ilya-fedin** [comment]
Maybe some arguments from KDE's flatpak runtime would help...
