### ISSUE TITLE
Incorrect USER_NOT_MUTUAL_CONTACT error

### ISSUE THREAD

**Issue by adrianopol** [telegramdesktop/tdesktop#2401]
(Further to #2378.)

1. There is no formal definition of what is a _mutual contact_. The only one is an error in telegram-desktop:

    > Sorry, if a person leaves a group, only a mutual contact can bring them back (**they need to have your phone number, and you need theirs**).
2. We see each other's phone numbers. According to (1), we **are** mutual.
3. Anyway, I continue getting the `USER_NOT_MUTUAL_CONTACT` error:

    > RPC Info: error received, code 403, type USER_NOT_MUTUAL_CONTACT, description: (facade.cpp : 529)
    > RPC Error: request 5110 got fail with code 403, error USER_NOT_MUTUAL_CONTACT
4. @auchri told me it was a spam protection. I have written to spam@telegram.org 10 days ago -- nobody has answered.

### Configuration
* Gentoo GNU/Linux, net-im/telegram-desktop-0.9.56;
* Android 4.4.4 (cyanogenmod), org.telegram.messenger-3.11.2;
* https://web.telegram.org.

**Comment by john-preston** [comment]
@adrianopol Well, you get an error from server, so tdesktop can't do anything with it.

Mutual contacts don't only know each other phone numbers, but have added each other to their contacts list.

**Comment by adrianopol** [comment]
Yes, we have each other in our contact lists.

> you get an error from server

How can I post a bug to server developers?

**Comment by john-preston** [comment]
@adrianopol You can contact me at telegram.me/preston and I'll ask for both your phone numbers to ask to check them.

**Comment by adrianopol** [comment]
OK, @john-preston found out, that we really were not mutual. I have shown him some screenshots, and it turned out that my pal saw my phone number in our conversation view instead of my nick or name. That was the cause of being not mutual.
Solution: press button "Add to contacts".

Thank you!
