### ISSUE TITLE
[Feature Request] Setting for scroll speed in app

### ISSUE THREAD

**Issue by christodenny** [telegramdesktop/tdesktop#24013]
### Is your feature request related to a problem?

Opened https://github.com/telegramdesktop/tdesktop/issues/24007 recently since Telegram doesn't seem to obey scroll speed settings in KDE under wayland/libinput. However that issue was closed with the explanation that telegram made a conscious decision "not to use system settings for anything in the UI." Unfortunately this means that right now scrolling in the app is overly sensitive. This is bad enough to the point that it's very hard to scroll to a certain element, I overshoot since the scroll is so sensitive.

### Describe the solution you'd like

If telegram has already made a deliberate choice to not respect system settings for things like scroll speed, would it be possible to have an app specific setting to tune this?

### Describe alternatives you've considered

I don't know of any alternatives to solve this without either respecting system scroll speed settings or offering a configuration in telegram settings. If you know of a workaround I'd be fine using that.

**Comment by lashkevi** [comment]
After the update to 3.6.1 mouse wheel scrolling became boringly slow.

**Comment by ilya-fedin** [comment]
Looks like it's a Plasma bug after all: changing scroll speed on Windows does change it in Telegram while changing scroll speed in Plasma doesn't affect any application on my machine.
