### ISSUE TITLE
Customizable emojis [Feature Request] 

### ISSUE THREAD

**Issue by swrbin** [telegramdesktop/tdesktop#24010]
### Is your feature request related to a problem?

Nope

### Describe the solution you'd like

I would like something similar to creating sticker packs, we could create emoji packs. Stickers are nice but pretty big and push messages up.

### Describe alternatives you've considered

Using the sticker pack creation system to send images with a lower resolution, the same resolution as the emojis.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
