### ISSUE TITLE
Telegram [snap] crashes when try share a screen on wayland 

### ISSUE THREAD

**Issue by EndrII** [telegramdesktop/tdesktop#24018]
### Steps to reproduce

* run telegram (from snap-store) on wayland 
* share screen  

### Expected behaviour

Telegram should be share a screen without issues.

### Actual behaviour

Telegram crashes when try share screen on wayland 

### Operating system

ubuntu 21.10

### Version of Telegram Desktop

4.3.4

### Installation source

Snap

### Logs

```shell
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
can't load /usr/lib/x86_64-linux-gnu/spa/support/libspa-support.so: /usr/lib/x86_64-linux-gnu/spa/support/libspa-support.so: cannot open shared object file: No such file or directory
```

**Comment by bjorn** [comment]
Issue should be reopened. @EndrII probably just wrote the version number the wrong way around (4.3.4 instead of 3.4.3).

**Comment by Aokromes** [comment]
a new issue was made and it was already fixed
https://github.com/telegramdesktop/tdesktop/issues/24022
https://github.com/telegramdesktop/tdesktop/issues/24022#issuecomment-1030824416
