### ISSUE TITLE
why no one help me ?

### ISSUE THREAD

**Issue by gilsefidi** [telegramdesktop/tdesktop#2402]
libexif 0.6.20
*  Building library

git apply ./../../tdesktop/Telegram/Patches/openal.diff

why i cant apply this patch ?

err : 

D:\TBuild\Libraries\openal-soft>git apply ./../../tdesktop/Telegram/Patches/openal.diff
./../../tdesktop/Telegram/Patches/openal.diff:10: trailing whitespace.
        if (!self->killNow) while(GetMessage(&msg, NULL, 0, 0))
./../../tdesktop/Telegram/Patches/openal.diff:19: trailing whitespace.
        if (!self->killNow) while(GetMessage(&msg, NULL, 0, 0))
error: patch failed: Alc/backends/winmm.c:221
error: Alc/backends/winmm.c: patch does not apply

**Comment by z3ntu** [comment]
Please don't open seperate issues for the same problem. Thanks. For reference, #2388 is meant by @gilsefidi .

But I can't help you with your problem, as I am not using Windows (10).

And why do you want to build Telegram Desktop from Source in the first place?
