### ISSUE TITLE
Tdesktop [Linux] hangs after viewing a profile photo

### ISSUE THREAD

**Issue by iestynapmwg** [telegramdesktop/tdesktop#24029]
### Steps to reproduce

This only happens after Telegram has been running for some time. Not sure exactly how long, but as little as 20 minutes has resulted in this. If I try to replicate this immediately after restarting Telegram, i'm able to view a profile without issues.

1. Open a chat view after receiving a message.
2. Click on user's name in the top of the right panel to bring up their profile
3. Click on user's icon to view photo.
4. Interface is completely unresponsive. "Quit Telegram" in systray icon's menu does work, though.

### Expected behaviour

Should be able to view profile and then click on the thumbnail image to view user photos.

### Actual behaviour

After clicking on thumbnail image viewer does not open. Entire interface is unresponsive: profile window and main Telegram window do not respond to any mouse clicks. Systray icon menu is available, however, and can be used to quit.

### Operating system

Linux (Arch), with Enlightenment WM.

### Version of Telegram Desktop

My current version is 3.5.0, and this was also a problem in at least the previous version (3.4.8). Can't be sure how long ago this did work correctly, as i don't often view profiles.

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
#17206

**Comment by iestynapmwg** [comment]
> #17206

That seems to be relevant only to Wayland, and i'm using Xorg. Also, there is no window covering the entire screen, i can interact with the desktop immediately next to the Telegram window.

**Comment by ilya-fedin** [comment]
Maybe #17296 then?

**Comment by iestynapmwg** [comment]
> Maybe #17296 then?

That applies to viewing two images in a row. I am not able to even view the first image. Unless it's immediately after starting Telegram, and then i can view any number of images as usual. And, also, the problem i'm running into seems to be specific to profile pictures. Other images (including multiple images) in group postings, for example, show without problems.

**Comment by ilya-fedin** [comment]
Maybe it's just you encounter that only on profile pictoures by accident. I don't think such a minor detail worths a separate issue.

**Comment by iestynapmwg** [comment]
Experimenting a bit, and i've found a way to reproduce this every time:

1. Open Telegram
2. Click on username in any group chat to open their profile
3. Click on the thumbnail image and the photo opens in the full-screen viewer
4. Close viewer.
5. Click on thumbnail again.
6. Interface is frozen.

And, yes, it does appear to occur with the second opening of the full screen viewer, so it seems #17296 is relevant here.

**Comment by ilya-fedin** [comment]
I can't reproduce this, btw. Not with steps from #17296 nor with yours.
