### ISSUE TITLE
Has the f..... Nazi-Regime crash the anonymity of Telegram???

### ISSUE THREAD

**Issue by Cosmotan01** [telegramdesktop/tdesktop#24023]
Has the f..... Nazi-Regime crash the anonymity of Telegram???

Translate it : 

Nancy Faeser
@NancyFaeser
Wir haben Kontakt zur Konzernspitze von #Telegram hergestellt. In einem ersten konstruktiven Gespräch zur weiteren Zusammenarbeit haben wir vereinbart, den Austausch fortzusetzen und zu intensivieren. Dieser Schritt ist ein guter Erfolg, auf dem wir aufbauen werden.

2/4/2022, 5:23:00 AM via Twitter 

the whole article : https://www.heise.de/news/Telegram-Messengerdienst-will-mit-Bundesinnenministerium-kooperieren-6349050.html

it was such a good messenger, now the Nazis will read all you messages ... such a shame!

We need something new, any proposition ?

Cheers

**Comment by Cosmotan01** [comment]
How the hell you can close it??? Such importan thing!

**Comment by Cosmotan01** [comment]
ok lets bring this to the telegram mainstream ....

**Comment by Cosmotan01** [comment]
Aokromes! dont like the true?

**Comment by RememberTheAir** [comment]
Nowhere in the article is mentioned that Telegram is giving the government access to your chats. From what I can understand, Telegram acknowledged the government request for a tighter moderation of its content. This is off-topic, anyway. If you want to be vocal about it, go on Twitter

**Comment by john-preston** [comment]
@Cosmotan01 this has nothing to do with Telegram Desktop.
