### ISSUE TITLE
[Feature Request] Add an option to disable tg:// protocol

### ISSUE THREAD

**Issue by xmha97** [telegramdesktop/tdesktop#24034]
### Is your feature request related to a problem?

Hi,
I using the portable version of Telegram.
The tg:// protocol is added every time I open the app.
This causes the protocol to malfunction.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/23485114/152691802-d08427f8-a937-45b3-b4ec-996335d1093d.png)
Please add an option to disable tg:// protocol

### Describe alternatives you've considered

I created the file below and have to run every time:
```ini
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\tg]
"URL Protocol"=""
@="URL:Telegram Link"

[HKEY_CLASSES_ROOT\tg\DefaultIcon]
@="\"C:\\Users\\User\\AppData\\Roaming\\Telegram Desktop\\Telegram.exe,1\""

[HKEY_CLASSES_ROOT\tg\shell]

[HKEY_CLASSES_ROOT\tg\shell\open]

[HKEY_CLASSES_ROOT\tg\shell\open\command]
@="\"C:\\Users\\User\\AppData\\Roaming\\Telegram Desktop\\Telegram.exe\" -workdir \"C:/Users/User/AppData/Roaming/Telegram Desktop/\" -- \"%1\""
```

### Additional context

I know that Telegram does not pay any attention to users' requests, and this issue will be closed for a few more days without being checked. 😶

**Comment by 3xploiton3** [comment]
+1 compatible for portable telegram

**Comment by Twilightssuperb** [comment]
Yep, even TDesktop portable makes registry traces almost every time after launch.
`[HKEY_CLASSES_ROOT\tg]`
Why? I forced to refresh regedit and manually delete it. I don't need it. I specially use portable version that supposed no registry traces by default.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/17bb430006c155305dbb5407fd3d081326af9b1b
