### ISSUE TITLE
[Feature Request] Don't mark message as read when mouse is moving on other screen in multi monitor setup

### ISSUE THREAD

**Issue by akaltar** [telegramdesktop/tdesktop#24030]
### Is your feature request related to a problem?

I don't notice messages when they are received monitor 1 while looking at another monitor 3 as there is no notification popping up and the message is immediately marked read.

### Describe the solution you'd like

Don't mark messages as read unless the mouse movement is happening on the same monitor as telegram is opened on.

### Describe alternatives you've considered

Closing/hiding telegram window every time so that it doens't mark messages as read works, but is very tedious/easy to forget.
If there was a way to play notification sound even when telegram window is focused that would also be a workaround, but not ideal

**Comment by ilya-fedin** [comment]
But they're not marked as read when the window loses focus, why don't you just click outside of the window?

**Comment by akaltar** [comment]
Oops, I didn't know that. That's a way better workaround. I just never noticed because my workflow usually just involved scrolling an already open window while telegram stayed focused.
Thank you, I think that's a good enough solution for me.
