### ISSUE TITLE
Sound freezes when another video played + when calling someone (ARCHLINUX)

### ISSUE THREAD

**Issue by Skycader** [telegramdesktop/tdesktop#24031]
### Steps to reproduce

Download official binary from pacman. (3.4.8)

### Expected behaviour

I do not excpect freezes. 

### Actual behaviour

Sound is freezing when another source of sound is played on (Linux ARCH 5.15.18-1-lts #1 SMP Sat, 29 Jan 2022 12:13:13 +0000 x86_64 GNU/Linux). Also, when calling someone even without other sources of sound the sound from call is freezing. 
There is no such problem with kotatogram, for example. 

### Operating system

Linux ARCH 5.15.18-1-lts #1 SMP Sat, 29 Jan 2022 12:13:13 +0000 x86_64 GNU/Linux

### Version of Telegram Desktop

3.4.8. official

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
try on 3.5.1/2

**Comment by Aokromes** [comment]
https://td.telegram.org/tlinux/tsetup.3.5.2.tar.xz
