### ISSUE TITLE
Fullscreen image view launches Nvidia GeForce Experience Shadowplay Overview

### ISSUE THREAD

**Issue by TonyDecvA180XN** [telegramdesktop/tdesktop#24036]
### Steps to reproduce

Nvidia GeForce Experience In-game overlay usually launches along with the game as a little memo in the upper-right corner of the screen.
When I open any image in Telegram, this animation of this overlay pops up, as well as post-processing filters appear on the image (e. g. I use modified gamma in games). Also, trying to manually open the overlay causes both applications to freeze until I close them.
Apparently, Nvidia drivers treat Telegram as a game.

### Expected behaviour

Nvidia overlay ignores the application.

### Actual behaviour

The opening image in fullscreen gets graphics effects applied by Nvidia GeForce Experience overlay as well as annoying animation shows up every time.

### Operating system

Windows 10 21H1

### Version of Telegram Desktop

v 3.5.1 x64

### Installation source

Microsoft Store

**Comment by john-preston** [comment]
@TonyDecvA180XN But.. what can I do about it? 😭

**Comment by TonyDecvA180XN** [comment]
Hmm, maybe there is some API call that the Nvidia driver is hooking to on entering fullscreen. Because not all fullscreen apps have a similar issue.

**Comment by cbraga99** [comment]
Had the same issue. Managed to disable the use of the GPU going to "Settings -> Advanced -> ANGLE graphics backend" and set it to "Disabled". No more issues with the images 💪

**Comment by Reonu** [comment]
I'm also getting this issue. Super annoying. The ANGLE workaround works though

**Comment by kennyt6** [comment]
Lol why does this program need to use the GPU? Make that the default.

**Comment by ilya-fedin** [comment]
@kennyt6 so you can watch high resolution video

**Comment by mich2k** [comment]
Following since I am experiencing this exact issue

**Comment by vvdrak** [comment]
I'm also getting this issue.

I turned off the ANGLE. Now the images open in a separate empty window

Operating system
Windows 11 22 H2

Telegram desktop version
4.6.5 x64

**Comment by Austint30** [comment]
Having this issue as well. Used to not happen. It also causes videos and images to appear transparent and overexposed.

**Comment by norlin** [comment]
That issue is causing full-screen photos overlay to be broken when its opened first time after the Telegram launch, Got fixed automatically after ~30 sec, then working normally until app is closed and launched again

![image](https://github.com/telegramdesktop/tdesktop/assets/370803/fdc0f290-50ed-4011-b7b1-a6180bd332e7)

**Comment by kulinicha** [comment]
> That issue is causing full-screen photos overlay to be broken when its opened first time after the Telegram launch, Got fixed automatically after ~30 sec, then working normally until app is closed and launched again
> 
> ![image](https://private-user-images.githubusercontent.com/370803/293476324-fdc0f290-50ed-4011-b7b1-a6180bd332e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODkwMjQsIm5iZiI6MTcwNDI4ODcyNCwicGF0aCI6Ii8zNzA4MDMvMjkzNDc2MzI0LWZkYzBmMjkwLTUwZWQtNDAxMS1iN2IxLWE2MTgwYmQzMzJlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxMzMyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzFlYWFjZDY4MWVjMTRiMGU5MzNiMjg0YjdjZGQ0OWNlZGVmNzc2ZTJmMmMwNzg0YzdlNmY2MzgzZGEzNmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tM4heoQHcVNvTZNPRB2BWPy9PNmXra6hkicvWfirB5c)

https://github.com/telegramdesktop/tdesktop/issues/24036#issuecomment-1092129723

**Comment by Aokromes** [comment]
maybe this must be reported to nvidia instead here.

**Comment by kulinicha** [comment]
The solution @cbraga99 wrote about above is working: "Had the same issue. Managed to disable the use of the GPU going to "Settings -> Advanced -> ANGLE graphics backend" and set it to "Disabled". No more issues with the images 💪"

**Comment by Aokromes** [comment]
> The solution @cbraga99 wrote about above is working: "Had the same issue. Managed to disable the use of the GPU going to "Settings -> Advanced -> ANGLE graphics backend" and set it to "Disabled". No more issues with the images 💪"

that ain't a solution, it's a workaround causing lower performance on high res videos.
