### ISSUE TITLE
Gifs are replaced when they have the same name

### ISSUE THREAD

**Issue by mreduar** [telegramdesktop/tdesktop#24038]
### Steps to reproduce

1. Have on hand two gifs with exactly the same name.
2. Upload one to your Saved Messages chat (You will notice that this gif appears in the saved gifs.)
3. Now copy your other gif to the same directory where your first gif was and replace it.
4. Upload the other gif with the same name and you will see that in the saved gifs panel you will have the last gif repeated N times.
5. Do this with as many gifs as you want and they will repeat as many times as you do.

### Expected behaviour

The gif should not be repeated

### Actual behaviour

The gif is repeated every time you upload one with the same name.
This is solved by opening and closing Telegram completely.
[Example Gif](https://i.imgur.com/xvuxUGV.gif)

### Operating system

Windows 10

### Version of Telegram Desktop

3.5.1

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5910

**Comment by mreduar** [comment]
> Contributor
Uhmn, essentially yes, it is the same problem, but with different steps. 
Biscotally the gifs cannot be in the same directory, and with the same name.
