### ISSUE TITLE
Animations to navigate between replies are inconsistent

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#2403]
### Steps to reproduce
1. Go to a group where there is a couple of replies
Compac Mode
2.  Press a replie and go to the message (animation: cover from right to left)
3.  Press arrow back (next to the group name) to return to the original message (animation: cover from left to right)
4. Press again and chat history is displayed (animation: cover from left to right).
5. Press a replie and go to the message (animation: cover from right to left). Press a mention againt and go to the message (animation: cover from right to left).
6. Press arrow back and chat history is displayed (not return to the previous message)
Note: The behavior varies between even and odd messages.

Normal mode:
The same, but instead of displaying the list of chat in steps 4 and 6, shows the group information.

### Expected behaviour
Back to previous jump animation. I must clarify that this use is not appropriate, because to go back in replies to use the "scroll to bottom" buttom (animation remains inconsistent), but the new animation "cover to..." encouraged to use interface otherwise.

### Actual behaviour
Animation to navigate between replies is inconsistent.

### Configuration
**Operating system:**
Fedora 24 (XFCE) 64 bit

**Version of Telegram Desktop:**
0.10.3 alpha

**Comment by john-preston** [comment]
By mentions you mean replies?

**Comment by john-preston** [comment]
The issue with the replies should be fixed in 0.10.4 alpha.

**Comment by diazbastian** [comment]
@john-preston thank you. 
Sorry for confusing the concepts ... I wrote the report very late at night.
