### ISSUE TITLE
Video stucks at timecode

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#24035]
### Steps to reproduce

1. Post video with timecode (0:05 for example)
2. Click on timecode
3. Video will start playing from your timecode
4. To open this video that starts from the begining you need restart Telegram client
5. Watching video untill the end or watch other videos is not helping
Example:
https://t.me/teeeeeeeest111/2

### Expected behaviour

There must be ability to reset timecode that user clicks on without restarting Telegram client

### Actual behaviour

You can't reset clicked timecode without restarting Telegram client

### Operating system

Windows 10

### Version of Telegram Desktop

3.5.1

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Please check the v3.5.3 beta version.

**Comment by Neurotoxin001** [comment]
Fixed in 3.5.3
