### ISSUE TITLE
[Feature request] 4 suggestions

### ISSUE THREAD

**Issue by Salkin2** [telegramdesktop/tdesktop#2404]
Hello.

Ths is the first time I write in Github, so, excuse if I'm not following the protocol correctly and don't hesitate telling me the right way, I'm rather newbie in commenting in a developers' site.

I'm using Telegram desktop client 0.10 on Linux. I think that Telegram has become much more than a chatting app; thanks to channels and groups it's now a small "Internet" were there are thousands of thematic channels, bots, groups and supergroups. That's great and makes it a plattform with a brilliant future much beyond a simple messenger, but the clients (or should I say "browsers"?) aren't on pair. It's a mess to be subscribed to half a hundred channels, a similar amount of bots, 20 or 25 groups and supergroups and also have the conversations with our contacts, everything mixed in the same window. I wanted to propose some ideas related to usability like the former that I think would make Telegram client much better in terms of usability and organization:
1. **Tabs** to cleanly separate the different types of conversations. It could be this way: a "General" or "All" one, that behaves like now, showing all the conversations in a single place, and then one tab "Groups", another "Channels", "Bots" and a fourth, "Conversations". Think in mail clients: you have a "common" inbox for all your mail accounts, but besides that you can show each account's inbox separately.
   In the desktop version I think it could be interesting too to have tabs to separate our conversations with our contacts individually. Pidgin and many other messengers have this feature, and theres an unofficial TG client for linux that I think it does too (sorry, I can't remember its name but can search it if you were interested).
2. **Browse history**. In some channels that have links to other channels, if you click on those links and then visit another channel, at the left top, over the message list, there's a left pointing arrow to go back, like the "back" button in Android. Lamentably this only happens in a small minority of channels. Well, it's very annoying to have a look to a bot/channel/group your are not subscribed to, click on some link that addresses to some other channel you aren't subscribed to either, and then in this channel, another link, and so on for as many steps as you want; and then you want to go back to some of the visited channels, groups, etc, but you can't, and you surely don't remember all of thse visited "places" not even the one where you started. Could it be added a browse history and back and forth arrows like in the web and file browsers?
3. **Bookmarks**. As I said, TG has become a sort of browser to navigate through channels, bots, etc. Could be possible to bookmark those we are interested in but not so much, or we're not decided yet, to subscribe? I think many of us are subcribed to too many channels and bots that we only visit once or twice a month; if a bookmark option were possible we could unsubscribe and clean our convesations list a little without missing those places we like to visit from time to time.
4. **Respect the desktop's conventions**. If I select a message and then press Shift and click on other message 5 messages away, TG must add it to the selection and select also all the other 4 messages in between. If I click and drag and drop to my file manager an attached file from some chat TG should do as every other app and copy the file to the folder opened in my file browser (curiously enough, it works perfectly the opposite way: file manager -> chat window in TG); if I'm dropping it to a new mail window, it should be attached to said mail. Telegram should not break the expected behavior of the apps.

Thanks for your attention, and excuse if my post is too long, I wanted to explain mi ideas as good as possible.

**Comment by john-preston** [comment]
@Salkin2 2. Should work for all channel links in the latest alpha version. You can try it from the bottom of https://desktop.telegram.org page.

**Comment by stek29** [comment]
1. #1107 duplicate

**Comment by Salkin2** [comment]
@stek29 Yes, more or less that's the idea. Thanks for pointing.

So, 1 is already proposed and 2 is solved in the alpha version. What do developers think of the other two, could them be implemented?

**Comment by john-preston** [comment]
2 should be fine in the latest stable 0.10.7

**Comment by stek29** [comment]
3 -- #296

**Comment by stek29** [comment]
Ok, so:
1. #1107 
2. Fixed
3. #296 
4. Moved to #1060
