### ISSUE TITLE
Background image does not scale properly

### ISSUE THREAD

**Issue by pryhodkin** [telegramdesktop/tdesktop#24042]
### Steps to reproduce

Hi, Telegram Team,

I want to report a bug I guess: on high-definition displays telegram desktop (v.3.5.1) (windows 10, 21H1, build 19043.1466) does not scale background image right, is it an expected behavior and if no, can you fix it, please, in the future versions?

![photo_2022-02-08_13-17-55](https://user-images.githubusercontent.com/48391393/152977477-77754ded-a11f-4998-a817-61b7c84c3a31.jpg)

### Expected behaviour

The background image scales with window-straching.

### Actual behaviour

The background image duplicates with window-straching.

![photo_2022-02-08_13-17-55](https://user-images.githubusercontent.com/48391393/152977477-77754ded-a11f-4998-a817-61b7c84c3a31.jpg)

### Operating system

windows 10, 21H1, build 19043.1466

### Version of Telegram Desktop

3.5.1

### Installation source

Microsoft Store

**Comment by Remu-rin** [comment]
Try to disable "Tile background" checkbox.

**Comment by pryhodkin** [comment]
Oh, thank you, it works for me and I'm sorry for this silly inconvenience!
