### ISSUE TITLE
Telegram does not respect Windows setting for focus assist

### ISSUE THREAD

**Issue by azzimuth** [telegramdesktop/tdesktop#24048]
### Steps to reproduce

1. Set focus assist to Alarms only
2. Receive a message in Telegram

(I'm not familiar with how notification system in Windows works. It could be of course a Windows issue rather than Telegram but would be good to investigate)

### Expected behaviour

No Telegram notifications are shown

### Actual behaviour

The Telegram notifications are shown despite the Windows setting

### Operating system

Windows 11, Version 21H2, Build 22000.469

### Version of Telegram Desktop

3.5.1 x64

### Installation source

Static binary from official website

**Comment by LyraLover** [comment]
I don't use Telegram on Windows, but on Linux there is an option (Settings > Notifications > Native notifications, last entry) to use native notifications. Check if it is enabled, this may solve your issue.

**Comment by ilya-fedin** [comment]
This is not a bug. Telegram doesn't follow focus assist preferences with custom notifications for a reason, see #16215
