### ISSUE TITLE
Tray icon missing after upgrade

### ISSUE THREAD

**Issue by thalesmaoa** [telegramdesktop/tdesktop#24046]
### Steps to reproduce

Using elementary OS, install Telegram Flathub. Tray icon will be missing:

![image](https://user-images.githubusercontent.com/14074573/153113601-210e6118-41de-4ec9-88d0-5bdbb566d8df.png)

Same behavior was fixed for other programs.
https://github.com/flathub/com.valvesoftware.Steam/issues/322
https://github.com/flatpak/flatpak/issues/4495
https://github.com/flathub/org.remmina.Remmina/issues/84
 

### Expected behaviour

Show telegram icon as previous versions.

### Actual behaviour

No icon is showing.

### Operating system

elementary OS 6.1 Jólnir

### Version of Telegram Desktop

3.5.2

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
:thinking: I can't reproduce on MATE, can you check permission overrides, maybe you revoked access for something?

**Comment by thalesmaoa** [comment]
Hi @ilya-fedin , thanks for your feedback. In fact, this happened for all three elementary OS machines that I use. As soon I upgrade, it looses it icons. Probably some elementary OS overrides something. Can you help me to run some diagnostics? 

```
$ flatpak run -v org.telegram.desktop 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/thales/.local/share/flatpak
F: Opening user flatpak installation at path /home/thales/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/thales/.local/share/flatpak
F: Regenerating ld.so.cache /home/thales/.var/app/org.telegram.desktop/.ld.so/76260cc6ab905cc24a3a219bdfee0d9a79142af96ada71728f3f32a5f8133bae
F: /home/thales/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/21.08/7eae5cd0909215ab896309abf9c6716875f0d012c84f73d44ddd1163a1de286d/files/lib32 does not exist
F: Running: 'bwrap --args 26 ldconfig -X -C /run/ld-so-cache-dir/76260cc6ab905cc24a3a219bdfee0d9a79142af96ada71728f3f32a5f8133bae.vlcCz2'
F: /home/thales/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/21.08/7eae5cd0909215ab896309abf9c6716875f0d012c84f73d44ddd1163a1de286d/files/lib32 does not exist
F: Cleaning up unused container id 778783462
F: Cleaning up per-app-ID state for org.telegram.desktop
F: Allocated instance id 2958509470
F: Add defaults in dir /org/telegram/desktop/
F: Add locks in dir /org/telegram/desktop/
F: Allowing host-fs access
F: skipping export for path /usr/libx32
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/thales/.config/pulse/client.conf': Erro ao abrir arquivo /home/thales/.config/pulse/client.conf: Arquivo ou diretório inexistente
F: Running 'bwrap --args 43 xdg-dbus-proxy --args=45'
F: Running 'bwrap --args 43 telegram-desktop'
Gtk-Message: 09:56:23.271: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:56:23.272: Failed to load module "canberra-gtk-module"
QIBusPlatformInputContext: invalid portal bus.
QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: Windows, Fusion
[ALSOFT] (EE) Failed to set real-time priority for thread: Operação não permitida (1)
error: : cannot open
error: : cannot open
error: : cannot open
```

**Comment by ilya-fedin** [comment]
From which version of tdesktop do you upgrade? What's version of flatpak (`flatpak --version`)? You can check permission overrides with `flatpak override --show org.telegram.desktop` for  tdesktop, `flatpak --user override --show` user-wide, `flatpak --system override --show` system-wide

**Comment by thalesmaoa** [comment]
The previous of 3.5.2 I got icon problem. I decided to wait for the next update (3.5.2) to see if the problem was fixed. Since I still got the error, I've filled the bug report.

 ```
$ flatpak --version
Flatpak 1.12.4
$ flatpak override --show org.telegram.desktop 
$ flatpak --user override --show org.telegram.desktop
[Context]
filesystems=~/.TelegramDesktop
$ flatpak --system override --show  org.telegram.desktop
```
Just got output from `--user`.

**Comment by ilya-fedin** [comment]
What about user-wide/system-wide commands (i.e. without specifying app ID)?

**Comment by thalesmaoa** [comment]
Nothing.
```
$ flatpak --system override --show
$ flatpak --user override --show
```

**Comment by ilya-fedin** [comment]
That's weird...

**Comment by ilya-fedin** [comment]
Looks like I need to reproduce that myself, but eOS doesn't install in a VM, it hangs at 35% :(

**Comment by thalesmaoa** [comment]
Good point.
Using a old version of my eOS I got the same error:

![image](https://user-images.githubusercontent.com/14074573/153231195-7b8ef160-5709-44c7-a505-0241de03203d.png)

![image](https://user-images.githubusercontent.com/14074573/153231283-c8c7dc6f-451c-4f82-8e79-97549255c7b8.png)

Don't forget to activate the tray icons
https://www.reallinuxuser.com/how-to-show-app-indicators-on-the-system-tray-in-elementary-os/

**Comment by ilya-fedin** [comment]
I can't find how to get an old version on the site...

**Comment by thalesmaoa** [comment]
Try this http://osarchive.sda1.eu/elementary-os

**Comment by ilya-fedin** [comment]
Looks like Qt creates icon file in /run/user/1000 and flatpak doesn't share that directory with host :(

**Comment by thalesmaoa** [comment]
That makes sense, but doesn't explain why you didn't get this behavior using Mate. Can you explain how did you debug it? Maybe I can help.

**Comment by ilya-fedin** [comment]
The instruction to install system tray support suggests to install an applet implementing AppIndicator protocol. MATE's built-in applet implements StatusNotifierItem (SNI) protocol. I debugged it with D-Feet: found tdesktop on session bus and checked IconName.
