### ISSUE TITLE
Can't play media files after last update

### ISSUE THREAD

**Issue by rustamwin** [telegramdesktop/tdesktop#24043]
### Steps to reproduce

1. Play audio/video messages

### Expected behaviour

Play media files [audio, video]

### Actual behaviour

Crash after clicking media

### Operating system

Debian GNU/Linux 10 (buster), GNOME 3.30.2

### Version of Telegram Desktop

3.5.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Provide a crash report tag, please

**Comment by john-preston** [comment]
If it crashes can you please .zip the .dmp files in ~/.local/share/TelegramDesktop/tdata/dumps and send them to me at t.me/preston ?

After that, can you please check this version:

https://td.telegram.org/tlinux/tsetup.3.5.2.tar.xz

**Comment by rustamwin** [comment]
> If it crashes can you please .zip the .dmp files in ~/.local/share/TelegramDesktop/tdata/dumps and send them to me at t.me/preston ?

There are no such files.


![image](https://user-images.githubusercontent.com/16498265/153029528-faca52c2-4711-428a-9883-d1955bc5f0a7.png)

**Comment by rustamwin** [comment]
> After that, can you please check this version:
https://td.telegram.org/tlinux/tsetup.3.5.2.tar.xz

This version worked for me :+1:

**Comment by mmetak** [comment]
@john-preston Still the same even with latest 3.5.2 official binary. (I've sent the crash dump files via tg)
