### ISSUE TITLE
[Feature Request] Handle timezones in JSON Export

### ISSUE THREAD

**Issue by andreymal** [telegramdesktop/tdesktop#24054]
I just noticed that exported `result.json` uses my local time without any information about time zone (Europe/Moscow in my case).

```
...
 "messages": [
  {
   "id": 13,
   "type": "message",
   "date": "2019-06-04T00:01:59",
   "edited": "2019-06-04T00:03:14",
...
...
```

It should use UTC:

```
   "date": "2019-06-03T21:01:59Z",
   "edited": "2019-06-03T21:03:14Z",
```

or at least add offset information of the current time zone:

```
   "date": "2019-06-04T00:01:59+03:00",
   "edited": "2019-06-04T00:03:14+03:00",
```

**Comment by 23rd** [comment]
Please check the 3.7.6 version.

**Comment by andreymal** [comment]
@23rd oops, I didn't notice it, sorry. It contains correct unixtime which fits my needs 👍
