### ISSUE TITLE
Github for Android?

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#24057]
i have a problem...
there is a Telegram channel blocked in Germany...

Android9 Telegram v8.5.1 say:
 does Not allow to see that channel,
because Apk was installed from Google Play Store...
BUT....
i don´t have Play Store.
Apk was downloaded or direct or huawei app gallery or apkpure apk
https://telegram.org/dl/android/apk
https://telegram.org/android

No Google Play Store.
No Google account.
There is a Bug.

Blocked Channel:
https://t.me/AttilaHildmannFreedom

**Comment by ilya-fedin** [comment]
> Apk was downloaded or direct or huawei app gallery or apkpure apk

I guess they both have apk from play store

**Comment by Aokromes** [comment]
this bug tracker is for telegram desktop, nothing we can do to fix it.
contact in app ask a question.
