### ISSUE TITLE
Media reattach and go to fullscreen in wrong monitor

### ISSUE THREAD

**Issue by srazi** [telegramdesktop/tdesktop#24051]
### Steps to reproduce

1. You have to more than one monitor available.
2. Open telegram window in monitor 1
3. Load a video and detach it.
4. Move video window to monitor 2
5. Click fullscreen button. it will reattach video to main widow that is in monitor 1 (so moved video from monitor 2 to 1)
6. Click fullscreen button again to have video in fullscreen mode in monitor 1

### Expected behaviour

We want to have video in fullscreen mode on monitor 2 without moving main window to monitor 2. So, in step 5 it should directly go to fullscreen on monitor 2, or show it in reattached mode but in monitor 2. Then, in step 6 by second click it go to fullscreen mode on monitor 2.

Maybe a more logical solution is that there can be another button for fullscreen. So, a fullscreen button and an attach/reattach button. The attach/reattach button works in current way without fullscreen function. And the fullscreen button directly change state of media to fullscreen in current monitor of media player.

### Actual behaviour

In step 5 it reattaches media and move it to monitor 1

### Operating system

Windows 10

### Version of Telegram Desktop

3.5.1

### Installation source

Static binary from official website

**Comment by qazomardok** [comment]
I support it. Unfolding any media file to the full screen leads to its cropping.

![1](https://user-images.githubusercontent.com/1916649/170355268-5efe249e-c2eb-44c5-ac48-bd8ae928200d.png)
![2](https://user-images.githubusercontent.com/1916649/170355278-ac2845c1-e92c-40ec-b6c4-d07242c31e33.png)

**Comment by ilya-fedin** [comment]
It works just as it's supposed to. The fullscreen viever is attached to main window screen, not to the screen of PiP when you go back to fullscreen. It also blocks main window, so having it on another screen is useless.
