### ISSUE TITLE
Flatpak version on KDE doesn't show tray icon without mouse hovering

### ISSUE THREAD

**Issue by PolGZ** [telegramdesktop/tdesktop#24050]
### Steps to reproduce

When telegram-desktop is opened, and "show tray icon" option (in advanced options) selected, the icon doesn't "show" (it ocupates the space, and shows if hovering with mouse, but not by default)

### Expected behaviour

To be always visible

### Actual behaviour

It is only visible if one hovers the mouse over it

### Operating system

GNU/Linux Manjaro 5.15.19-1 KDE 5.23.5 (but happened on previous ones)

### Version of Telegram Desktop

3.5.2 (but it also happened on previous ones)

### Installation source

Flatpak

### Logs

[normal](https://ibb.co/DCw1pyd)
[hovering mouse](https://ibb.co/wRn8QpR)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/24046

**Comment by PolGZ** [comment]
> #24046

Is it the same? I can see the correct icon, but it doesn't show if you don't point at it with the mouse

**Comment by ilya-fedin** [comment]
It's #24009, lol
