### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by rezaparsad** [telegramdesktop/tdesktop#24059]
### Is your feature request related to a problem?

I want to login in with Infinite Telegram, which source file should I change?
Please help me 

### Describe the solution you'd like

I want to login in with Infinite Telegram, which source file should I change?
Please help me 

### Describe alternatives you've considered

I want to login in with Infinite Telegram, which source file should I change?
Please help me 

### Additional context

I want to login in with Infinite Telegram, which source file should I change?
Please help me

**Comment by Aokromes** [comment]
what do you mean?

**Comment by grishka** [comment]
This Telegram is finite, he wants an infinite one, duh

**Comment by rezaparsad** [comment]
I want to be able to login and have an account indefinitely

**Comment by FabianPastor** [comment]
Buy infinite phone numbers and login Telegram. Done.
Has nothing to do with Telegram Desktop at all.

**Comment by rezaparsad** [comment]
How can you guide us?

**Comment by rezaparsad** [comment]
How can I have an infinite account in Telegram Linux

**Comment by rezaparsad** [comment]
> #10272

thanks
