### ISSUE TITLE
[Question] Telegram Does Not Recognize Custom Fonts

### ISSUE THREAD

**Issue by The-0Day** [telegramdesktop/tdesktop#24069]
Hi.
After Updating To Version `3.5.0-1`, The Persian Font has Changed To [Vazir Font](https://github.com/rastikerdar/vazir-font).
Also, I Have Already Created A File Called `local.conf` In `/etc/fonts`, And Before Updating Telegram To The Last Version Using Pacman, It Had Been Working Fine With My Fonts, But Now It's Not!
My [`local.conf`](https://termbin.com/q1ea)  [For Persian Font, I Am Using [Sahel Font](https://github.com/rastikerdar/sahel-font)] 

Is There Any Way To Fix This Problem?

Distro: ‍`ArchLinux‍‍`
Telegram Version: `3.5.0-1`

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by The-0Day** [comment]
@Aokromes @ilya-fedin 
Thanks For The Answers.
I Always Download Telegram From ArchLinux Repos, It Used To Work Fine Before Updating To The Latest Version.
BTW, I Already Tried The Official Version On The Website, It Does Not Match With The Font I Want And I Don't Like Vazir, I Want To Use My Favorite Persian And English Fonts, This Is What I Used To Do In The Previous Versions And It Worked Fine!
Before Updating To The Last Version, We Could Change The Fonts By Creating ‍`/etc/fonts/local.conf‍‍` And Customizing It, But Now On This New Version, It's Not Working! I Think IT'S A BUG!
