### ISSUE TITLE
Wayland session Window Sharing not working

### ISSUE THREAD

**Issue by FattyNess** [telegramdesktop/tdesktop#24064]
### Steps to reproduce

1. Open telegram-desktop-3.5.2 version on GNOME-Wayland session.
2. Start a Live stream
3. Click "Share Screen"
4. Select "Single Window" tab at xdg-desktop-portal-gtk application
5. Select window.

### Expected behaviour

![pr](https://user-images.githubusercontent.com/37911092/153676472-3ef1f5de-41fb-4879-83c8-55cbff59983f.png)

### Actual behaviour

![prev](https://user-images.githubusercontent.com/37911092/153675847-f9f99f3e-d7e2-4a13-9802-50b7b8444a1e.png)

It will pause screen sharing if I don't move a cursor.  

### Operating system

OS: EndeavourOS Linux x86_64 DE: GNOME 41.3 

### Version of Telegram Desktop

3.5.2

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Yet another webrtc bug, apparently

**Comment by ilya-fedin** [comment]
Is this still an issue?
