### ISSUE TITLE
Buttons are offset when reactions are present, while button click area is not offset

### ISSUE THREAD

**Issue by Kirisummer** [telegramdesktop/tdesktop#24068]
### Steps to reproduce

1. Create a post with buttons
2. Add reactions to it
3. Check is button click area corresponds to button position

### Expected behaviour

Button click area must be the same as button position

### Actual behaviour

Button click area remains the same as if there were no reactions, while buttons are offset down

https://user-images.githubusercontent.com/21143379/153750463-5aa9771d-6524-4523-b763-e549d703c962.mp4

### Operating system

Arch Linux x86_64, Xfce

### Version of Telegram Desktop

3.5 from arch repo (I'm sure non-repo version has the same issue)

### Installation source

Other (unofficial) source

**Comment by 23rd** [comment]
Please check the v3.5.3 beta version.
