### ISSUE TITLE
Chat scrolls down after file replacement

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#24067]
### Steps to reproduce

1. Create chat and upload a file and then post ~800 messages
2. Try to replace file
3. After you replace the file chat will scroll down

https://user-images.githubusercontent.com/39812401/153744013-aa423ca1-4b08-4f7d-9f25-b2dd3da7c113.mp4

On video I replace the file from clipboard.

It's only happens if after message with uploaded file users send unknown number of messages, but I flood ~800 messages to test it and reproduce.

### Expected behaviour

Chat is not scrolls down after file replacement

### Actual behaviour

Chat scrolls down after file replacement

### Operating system

Windows 10

### Version of Telegram Desktop

3.5.1

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
not fixed

**Comment by Neurotoxin001** [comment]
Remove stale label, it's not fixed

**Comment by Neurotoxin001** [comment]
4.3.1 still have it

**Comment by 23rd** [comment]
Please check a nightly build.
https://github.com/telegramdesktop/tdesktop/actions/runs/3650565920

**Comment by Neurotoxin001** [comment]
> Please check a nightly build.

Fixed.

**Comment by Neurotoxin001** [comment]
So I think it will be fixed in next release so I close it
https://github.com/telegramdesktop/tdesktop/commit/66926ba25e8ff296fa6eb6d4e674e7ffd9ee1cc2
