### ISSUE TITLE
Cannt build on windows

### ISSUE THREAD

**Issue by XiangQingW** [telegramdesktop/tdesktop#24060]
### Steps to reproduce

Run `tdesktop\Telegram\build\prepare\win.bat`.
The same issue on stackoverflow: https://stackoverflow.com/questions/71047980/when-compiling-telegram-desktop-it-shows-me-failed-dump-syms-exe-dump-syms-e

### Expected behaviour

The breakpad libray can be built.

### Actual behaviour

FAILED: dump_syms.exe dump_syms.exe.pdb
E:\TBuild\ThirdParty\Python39\python.exe gyp-win-tool link-with-manifests environment.x64 True dump_syms.exe "E:\TBuild\ThirdParty\Python39\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:dump_syms.exe @dump_syms.exe.rsp" 1 mt.exe rc.exe "obj\tools\windows\dump_syms\dump_syms.dump_syms.exe.intermediate.manifest" obj\tools\windows\dump_syms\dump_syms.dump_syms.exe.generated.manifest
Traceback (most recent call last):
  File "E:\TBuild\Libraries\win64\breakpad\src\out\Release_x64\gyp-win-tool", line 332, in <module>
    sys.exit(main(sys.argv[1:]))
  File "E:\TBuild\Libraries\win64\breakpad\src\out\Release_x64\gyp-win-tool", line 31, in main
    exit_code = executor.Dispatch(args)
  File "E:\TBuild\Libraries\win64\breakpad\src\out\Release_x64\gyp-win-tool", line 73, in Dispatch
    return getattr(self, method)(*args[1:])
  File "E:\TBuild\Libraries\win64\breakpad\src\out\Release_x64\gyp-win-tool", line 202, in ExecLinkWithManifests
    our_data = our_f.read().translate(str.maketrans('', '', string.whitespace))
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
ninja: build stopped: subcommand failed.
[12/15](Libraries/breakpad): FAILED

### Operating system

windows10

### Version of Telegram Desktop

dev

### Installation source

Other (unofficial) source

**Comment by 23rd** [comment]
As a workaround you can try `set PYTHONUTF8=1` before `tdesktop\Telegram\build\prepare\win.bat`.

**Comment by XiangQingW** [comment]
Thanks
