### ISSUE TITLE
Translate incoming messages

### ISSUE THREAD

**Issue by Ziggizag** [telegramdesktop/tdesktop#24075]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

The inability of incoming message translation is a serious problem, blocking Telegram Desktop users from following groups in foreign languages. I would see this as an urgent feature that should be a top priority - much more urgent than stupid emoji or stickers!

### Describe alternatives you've considered

There is no real alternative.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6707
