### ISSUE TITLE
application window freezes in Enlightenment

### ISSUE THREAD

**Issue by gecheim** [telegramdesktop/tdesktop#24073]
### Steps to reproduce

1. Run application
2. Open chat
3. Open image
4. Close image
5. Repeat step 3-4 random number
6. Window not reacted for any actions

### Expected behaviour

Normal run application for any opened images

### Actual behaviour

Window is frezes and not reopening without restart application.
In system journal more errors from telegram for any actions.

### Operating system

ArchLinux

### Version of Telegram Desktop

3.5

### Installation source

Other (unofficial) source

### Logs

```shell
фев 14 12:03:37 zarand-arch telegram-desktop[159875]: QApplication: invalid style override 'gtk2' passed, ignoring it.
                                                                 Available styles: kvantum-dark, kvantum, Windows, Fusion
фев 14 12:03:37 zarand-arch telegram-desktop[159875]: qt.svg: Error while inflating gzip file: SVG format check failed
фев 14 12:03:37 zarand-arch telegram-desktop[159875]: qt.svg: Error while inflating gzip file: SVG format check failed
фев 14 12:03:37 zarand-arch telegram-desktop[159875]: qt.svg: Error while inflating gzip file: SVG format check failed
фев 14 12:03:38 zarand-arch telegram-desktop[159875]: qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
```

**Comment by ilya-fedin** [comment]
#17296
