### ISSUE TITLE
Conversations being deleted or someone can't see the conversations

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#24078]
### Steps to reproduce

So with 2 different people:

1. The entire conversation I had with her was wiped CLEAN and she wasn't on my contact list anymore. She said I was still on her contact list & she could see our conversation.
2. The other one I messaged her 2-3 times after several messages she did get and BAMM, she couldn't see them. This went on for over a month, meaning we started conversing in December & even in January she never got the messages.

Does this happen when someone's account is blocked by TG?

This is a HUGE bug. Who knows how many other people can't see my messages or the entire conversation has been wiped clean.

### Expected behaviour

Nothing should ever be deleted or wiped clean.

### Actual behaviour

Deleted conversations 

### Operating system

Win 8.1 I don't know what version she is on

### Version of Telegram Desktop

the latest 

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by ILoveSkilledCoders** [comment]
@Aokromes - where can I post re: bugs on Android?

Thanks

**Comment by Aokromes** [comment]
> @Aokromes - where can I post re: bugs on Android?
> 
> Thanks

just where i linked you.

**Comment by ILoveSkilledCoders** [comment]
> > @Aokromes - where can I post re: bugs on Android?
> > Thanks
> 
> just where i linked you.

Ok, I thought was only for desktoop.

So are any of those bugs ever fixed or only if others rate them?

Thanks

**Comment by ILoveSkilledCoders** [comment]
Hi,

Can you answer my last question please.

Thanks

**Comment by ILoveSkilledCoders** [comment]
Hello?
