### ISSUE TITLE
Replace two characters >> to one character »

### ISSUE THREAD

**Issue by nikolos777** [telegramdesktop/tdesktop#2407]
### Steps to reproduce
1. Write message in yourself chat two characters >>

### Expected behaviour
Expected two characters >>

### Actual behaviour
Instead two characters >> make one character »

### Configuration
GNU/Linux Debian 8 Jessie x86_64

**Version of Telegram Desktop:**
0.10.1 x64
![message](https://cloud.githubusercontent.com/assets/22007125/18250957/04dc4c24-738f-11e6-90f9-5beedeeb0116.png)
![version](https://cloud.githubusercontent.com/assets/22007125/18250958/0505d9a4-738f-11e6-907c-672255721221.png)

**Comment by auchri** [comment]
duplicate

**Comment by Kondra007** [comment]
Use backticks to preserve 2 characters

**Comment by stek29** [comment]
It's a feature. <<, >> and -- are replaced.

**Comment by AndydeCleyre** [comment]
Please reconsider! I just spent a long time trying to figure out why my bot wasn't processing user-sent messages correctly before I realized tdesktop decides the user doesn't know best what they mean to type.
