### ISSUE TITLE
Incorrect Object Scaling

### ISSUE THREAD

**Issue by Balrrach** [telegramdesktop/tdesktop#24084]
### Steps to reproduce

1. Change global scale to any value different from 100%
2. Open telegram-desktop and see icons and pictures blurred

### Expected behaviour

Normal rederization

### Actual behaviour

Blurred icons and pictures. Font is alright.

![image](https://user-images.githubusercontent.com/35852847/154368676-68416476-62dc-492d-b552-22511c62a3c0.png)
![image](https://user-images.githubusercontent.com/35852847/154368699-ec27dc5e-bd68-4bce-94fb-37bf8724a12f.png)

### Operating system

Manjaro Qoonos 21.2.3 kde

### Version of Telegram Desktop

3.5

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Switch to official builds, they don't have such problems

**Comment by Balrrach** [comment]
The build is from the one from the pacman repositories. That can't be the problem.

**Comment by Balrrach** [comment]
You were absolutely right, the official build works correctly, my apologies. I'll contact the repository owners to inform them about the problem. Thanks a lot.

**Comment by ilya-fedin** [comment]
I don't think they can do something. This is fixed in official builds by building Qt without High DPI scaling support. Doing that in a distro package would lead to negative consequences for other Qt apps.
