### ISSUE TITLE
Feature request: save favorite posts

### ISSUE THREAD

**Issue by mohsenmim** [telegramdesktop/tdesktop#2408]
Hi,
I see some posts in channels which I really like to save for future reference.
How about adding a feature to let users save their favorite posts to a list?

**Comment by diazbastian** [comment]
@mohsenmim You can save your favorite messages in your [Personal Storage](https://telegram.org/blog/trending-stickers). This is the path taken by Telegram and I feel much better than the "Whatsapp favorite messages".
In #2302 I describe possible improvement consistent with other platforms.

Cheers

**Comment by mohsenmim** [comment]
@diazbastian. Makes sense. Thank you.l
