### ISSUE TITLE
[Feature Request] Change the folder order

### ISSUE THREAD

**Issue by farazsahebdel** [telegramdesktop/tdesktop#24088]
hi
Please allow all chats to be moved to other folders, for example, the folder that is created will come to the first folder.
thank you

**Comment by farazsahebdel** [comment]
Yes, but you can not change above all chats
This means that the desired folder can not be defaulted when the program is opened

**Comment by RememberTheAir** [comment]
If this issue boils down to replacing the default folder, then it's a duplicate of #7533

**Comment by 23rd** [comment]
This was implemented in the 3.7.6 version as the premium feature.
