### ISSUE TITLE
pasted images appear as image_date-time.png file on Linux

### ISSUE THREAD

**Issue by bart9h** [telegramdesktop/tdesktop#24090]
### Steps to reproduce

1. copy an image to the clipboard (for example by taking a screenshot, or copying from the browser or an image editor)
2. paste it on a chat

### Expected behaviour

an image should appear on the chat

### Actual behaviour

a file appears instead, with a square thumbnail of the image, the file name as `image_yyyy-mm-dd_hh-mm-ss.png`, the file size, and a "OPEN WITH" button

### Operating system

Devuan 4.0 (based on Debian 11.1), MATE 1.24.1

### Version of Telegram Desktop

3.5.2

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
I guess you forgot to check `Compress images`.

**Comment by hessam-kk** [comment]
an image may help to clarify...

**Comment by bart9h** [comment]
> I guess you forgot to check `Compress images`.

Bingo!
