### ISSUE TITLE
[Feature Request] Add view profile in chats context menu

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [telegramdesktop/tdesktop#24096]
### Is your feature request related to a problem?

Not a real problem. But sometimes may need to check the user profile without opening the chat and seeing the message.

### Describe the solution you'd like

Add an item to the context menu in the chats list. when the user right-clicks on the chat item, he/she can select the "View Profile" item to checkout that user/chat profile or info.

### Describe alternatives you've considered

Nothing.

**Comment by 23rd** [comment]
#17516.
