### ISSUE TITLE
Long launch on first start

### ISSUE THREAD

**Issue by dydyamotya** [telegramdesktop/tdesktop#24091]
### Steps to reproduce

1. Start OS
2. Launch telegram-desktop
3. Wait like 30 seconds

### Expected behaviour

Launch telegram-desktop and wait just a second

### Actual behaviour

It takes to long for a start. I didn't notice, after what update precisely it begins, but I collect some strace logs. They show, that there are some long waits on polls to some fds. First place is attached to logs, later will find and attach the another one. I have noticed to time lags.

### Operating system

Linux motyapc 5.16.10-arch1-1 #1 SMP PREEMPT Wed, 16 Feb 2022 19:35:18 +0000 x86_64 GNU/Linux

### Version of Telegram Desktop

3.5.2

### Installation source

Other (unofficial) source

### Logs

```shell
Logs from strace, where the waiting occurs. 


...
openat(AT_FDCWD, "/usr/share/mime/types", O_RDONLY|O_CLOEXEC) = 26
statx(26, "", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=20977, ...}) = 0
statx(26, "", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=20977, ...}) = 0
statx(26, "", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=20977, ...}) = 0
read(26, "application/andrew-inset\napplica"..., 16384) = 16384
read(26, "age/wmf\nimage/x-3ds\nimage/x-adob"..., 16384) = 4593
read(26, "", 11791)                     = 0
statx(26, "", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=20977, ...}) = 0
close(26)                               = 0
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
poll([{fd=6, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=6, revents=POLLOUT}])
writev(6, [{iov_base="\20\0\6\0\r\0\0\0_XSETTINGS_S0\0\0\0", iov_len=24}], 1) = 24
futex(0x7fff42429018, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = 0
futex(0x7f5415143298, FUTEX_WAKE_PRIVATE, 1) = 0
poll([{fd=6, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=6, revents=POLLOUT}])
writev(6, [{iov_base="\27\0\2\0\275\1\0\0", iov_len=8}], 1) = 8
futex(0x7f5415143298, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f5415143298, FUTEX_WAKE_PRIVATE, 1) = 0
write(7, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0x7f541502dc00, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f54150e7c00, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f5415124198, FUTEX_WAKE_PRIVATE, 1) = 1
eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 26
write(26, "\1\0\0\0\0\0\0\0", 8)        = 8
write(7, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0x7f541502dc00, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f54150e7c00, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f5415124198, FUTEX_WAKE_PRIVATE, 1) = 1
poll([{fd=26, events=POLLIN}], 1, 25000) = 1 ([{fd=26, revents=POLLIN}])
read(26, "\1\0\0\0\0\0\0\0", 16)        = 8
poll([{fd=26, events=POLLIN}], 1, 25000) = ? ERESTART_RESTARTBLOCK (Interrupted by signal) #Wait occurs on this line
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
restart_syscall(<... resuming interrupted poll ...>) = 0
write(26, "\1\0\0\0\0\0\0\0", 8)        = 8
...
```

**Comment by dydyamotya** [comment]
Another one place, where the waiting occurs. Line is marked by comment
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 49
write(49, "\1\0\0\0\0\0\0\0", 8)        = 8
write(7, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0x7f541502dc00, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f54150e7c00, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f5415124198, FUTEX_WAKE_PRIVATE, 1) = 1
poll([{fd=49, events=POLLIN}], 1, 25000) = 1 ([{fd=49, revents=POLLIN}])
read(49, "\1\0\0\0\0\0\0\0", 16)        = 8
**poll([{fd=49, events=POLLIN}], 1, 25000) = 1 ([{fd=49, revents=POLLIN}])** # Here it waits

**Comment by ilya-fedin** [comment]
> Linux motyapc 5.16.10-arch1-1 #1 SMP PREEMPT Wed, 16 Feb 2022 19:35:18 +0000 x86_64 GNU/Linux

Can you provide the OS how tdesktop detects it (in the session list from Privacy & Security)?

**Comment by ilya-fedin** [comment]
And, please, read the hints
![изображение](https://user-images.githubusercontent.com/17829319/154817158-8a771393-29fe-4414-9704-e29941bb0ca7.png)

**Comment by dydyamotya** [comment]
Ops, sorry,
Telegram shows: TM1604
ArchLinux, linux kernel is mentioned above, i don't use desktop environment, though display manager: lightdm, window manager: i3wm.

**Comment by ilya-fedin** [comment]
> Telegram shows: TM1604

It's your hardware (apparently motherboard model), I talked about OS version field

**Comment by ilya-fedin** [comment]
> ArchLinux, linux kernel is mentioned above, i don't use desktop environment, though display manager: lightdm, window manager: i3wm.

lightdm is abandoned for multiple years AFAIK, so it has problems with PAM and likely to have problems with dbus session initialization what would lead to such problems. I suggest to switch to sddm.

**Comment by dydyamotya** [comment]
> > Telegram shows: TM1604
> 
> It's your hardware (apparently motherboard model), I talked about the OS version field

I've just posted, what you asked me. That's what was shown in sessions list in Privacy settings.

> > ArchLinux, linux kernel is mentioned above, i don't use desktop environment, though display manager: lightdm, window manager: i3wm.
> 
> lightdm is abandoned for multiple years AFAIK, so it has problems with PAM and likely to have problems with dbus session initialization what would lead to such problems. I suggest to switch to sddm.

Though, I turned off lightdm, rebooted, so no display manager was presented, but the problem still there. It took nearly 30 seconds to launch. How else can I help?

**Comment by ilya-fedin** [comment]
> Though, I turned off lightdm, rebooted, so no display manager was presented, but the problem still there.

How did you start the graphics then?

**Comment by dydyamotya** [comment]
Ohh, probably you've mentioned this line:
![image](https://user-images.githubusercontent.com/49689233/154910949-c090560b-60a5-4c13-ba10-770d1314b5fe.png)

**Comment by ilya-fedin** [comment]
Yeah, that was enough though

> ArchLinux, linux kernel is mentioned above, i don't use desktop environment, though display manager: lightdm, window manager: i3wm.

**Comment by dydyamotya** [comment]
> > Though, I turned off lightdm, rebooted, so no display manager was presented, but the problem still there.
> 
> How did you start the graphics then?

Using ~/.xinitrc init script.

**Comment by ilya-fedin** [comment]
Is your .xinitrc based on /etc/X11/xinit/xinitrc so systemd integration is working?

**Comment by dydyamotya** [comment]
> Is your .xinitrc based on /etc/X11/xinit/xinitrc so systemd integration is working?

Partially, yes, the last part looks like:
`if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &

exec i3`

**Comment by ilya-fedin** [comment]
Maybe xdg-desktop-portal is launching too long?

**Comment by dydyamotya** [comment]
I'll try it as soon as possible. Thanks.

**Comment by dydyamotya** [comment]
Yeah, deleting the xdg-desktop-portal has solved the issue. Thanks.

**Comment by GabenCrying** [comment]
> xdg-desktop-portal

Had this problem after installing debian today, 
Removing xdg-desktop-* solved Telegram not opening and pavucontrol. Thank you!
