### ISSUE TITLE
[Feature Request] Reorder messages on own channels

### ISSUE THREAD

**Issue by IdontKnoware** [telegramdesktop/tdesktop#24093]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

I have some **private** channels with documents/music... As new things related to the channel comes out, I upload them. But sometimes I already uploaded some content that is not related to the last upload thread.

i.e: You create private channel and upload some content there, music for example. You upload some albums, but when you notice you forgot a song of the first album, you need to delete them all and upload at the right place. If not, you cannot play an  entire album in the right order, if you like.

I would like to be able to select a message and put at position I will like/need.

### Describe alternatives you've considered

Drag & Drop method + change message position, like the Valve Steam wishlist
![telegramfeature](https://user-images.githubusercontent.com/26889336/154842730-c24bac6f-a597-428d-8bf7-dadfc1b429a3.png)

**Comment by 23rd** [comment]
https://bugs.telegram.org/c/3694
