### ISSUE TITLE
Job 1, 'telegram-desktop' terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by 0trenixjetix** [telegramdesktop/tdesktop#24107]
### Steps to reproduce

1. Open Telegram
2. Open a certain chat (Only one of my chats)
3. Inmediatly crashes

### Expected behaviour

Open the conversacion normally

### Actual behaviour

Crashes instantly
I opened telegram with -debug and these are the logs.
[last_openal_log.txt](https://github.com/telegramdesktop/tdesktop/files/8128322/last_openal_log.txt)
[log_23_30.txt](https://github.com/telegramdesktop/tdesktop/files/8128323/log_23_30.txt)

### Operating system

Debian bookworm with i3-wm

### Version of Telegram Desktop

3.5.2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
If you have a crash, logs are useless, you should install the official binary and send a crash report

**Comment by 0trenixjetix** [comment]
Okay, i tested with the debian package for telegram and at the moment when i click the chat it gives the me this:
```
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
fish: Job 1, 'telegram-desktop' terminated by signal SIGSEGV (Address boundary error)

```
But i tried the official binary and nothing happend, no logs, no svg format check failed.
Okay, the problem solved itself. What did debian packagers do?

**Comment by ilya-fedin** [comment]
It's a question for debian packagers...

**Comment by 0trenixjetix** [comment]
I sent a report to debian mailing lists. Thank you for your time.
