### ISSUE TITLE
Implement desktop client with Electron

### ISSUE THREAD

**Issue by akashnimare** [telegramdesktop/tdesktop#2410]

**Comment by akashnimare** [comment]
Electron is very powerful when it comes to building desktop app. Now a days many apps are being build on top of this framework. @john-preston @auchri any plans for this? I would love to get involve in this project 🎅 .

**Comment by john-preston** [comment]
@akashnimare You offer me to start a completely new project on html/js instead of this one? What for? How is it related in any way to this app?

**Comment by john-preston** [comment]
@akashnimare You're always welcome to start your own desktop telegram app using electron. You can even take open source web version web.telegram.org to get started and get involved in it.

**Comment by akashnimare** [comment]
@john-preston I have built a basic prototype of telegram desktop app and it works great. I'll make it open source once it's stable. It was just a suggestion to start a experimental project using electron. That's it.

**Comment by auchri** [comment]
@akashnimare I'm looking forward to it 👍

**Comment by akashnimare** [comment]
@auchri I'll let you know.

**Comment by stek29** [comment]
@akashnimare Qt is much more powerful than Electron. 
Btw, Why won't you just use [official Web client](/zhukov/webogram)?

**Comment by stek29** [comment]
@akashnimare have you seen [official web app](/zhukov)?

**Comment by frenchbread** [comment]
@akashnimare Any update on telegram built with electron? I'd like to try it out :)

**Comment by stek29** [comment]
I still can't understand what's the problem with official web client wrapped in electron.
Or maybe even [treact](https://github.com/goodmind/treact)

**Comment by frenchbread** [comment]
@stek29 Thanks for sharing `treact`.

> I still can't understand what's the problem with official web client wrapped in electron.

Official web app & tdesktop do not have secret chat feature. So in order to have it, gotta use Telegram for mac os while dropping tweaks like themes etc.

**Comment by akashnimare** [comment]
Here you go -

https://github.com/akashnimare/telectron

Features included -
* spellchecker - 

![spell](https://cloud.githubusercontent.com/assets/2263909/24840730/65bea040-1d90-11e7-9f75-376cfa512849.jpg)
* Desktop notifications

More features would be added please give feedback and keep an eye on the project ❤️
