### ISSUE TITLE
how to disable notification counter in groups and tray?[Question] 

### ISSUE THREAD

**Issue by optimis3232** [telegramdesktop/tdesktop#24105]
Eng:
The counter of new messages in the tray and in the list of groups distracts from waiting for a new private message, how to turn off these notifications in groups, but leave them in private messages? right click and "unmute" doesn't help
Rus:
Cчётчик новых сообщений в трее и в списке групп отвлекает от ожидания нового личного сообщения, как отключить эти уведомления в группах, но оставить в личных сообщениях ? правый клик и "unmute" не помогает

**Comment by john-preston** [comment]
@optimis3232 You can mute the groups and remove counting muted chats in the global unread badge in Settings > Notifications.

**Comment by optimis3232** [comment]
but its not helped...
i dont receive sms from private messages
