### ISSUE TITLE
Telegram crashes after a while of using

### ISSUE THREAD

**Issue by BaseMax** [telegramdesktop/tdesktop#24118]
### Steps to reproduce

1. Open telegram
2. Use it
3. spend time and use it
4. Crash!

### Expected behaviour

No crash!

### Actual behaviour

Crash!

### Operating system

Linux, Manjaro, Xfce4

### Version of Telegram Desktop

Arch pacman package manager, 3.5.0-1

### Installation source

Other (unofficial) source

### Logs

```shell
$ uname -a
Linux workstation 5.15.12-1-MANJARO #1 SMP PREEMPT Wed Dec 29 18:08:07 UTC 2021 x86_64 GNU/Linux

$ pacman -S telegram-desktop
warning: telegram-desktop-3.5.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) telegram-desktop-3.5.0-1

Total Installed Size:  69.10 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                     [####################################################################] 100%
(1/1) checking package integrity                                                                                   [####################################################################] 100%
(1/1) loading package files                                                                                        [####################################################################] 100%
(1/1) checking for file conflicts                                                                                  [####################################################################] 100%
(1/1) checking available disk space                                                                                [####################################################################] 100%
:: Running pre-transaction hooks...
(1/1) Creating Timeshift snapshot before upgrade...
==> skipping timeshift-autosnap due skipRsyncAutosnap in /etc/timeshift-autosnap.conf set to TRUE.
:: Processing package changes...
(1/1) reinstalling telegram-desktop                                                                                [####################################################################] 100%
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating icon theme caches...
(3/3) Updating the desktop file MIME type cache...
```

Its while other running applications works well. like chrome.
Yes now my telegram crashed by I am reporting this bug.

This problem harm me in recent weeks and I cannot handle it. Any guide or advise?

Let me know if you need any more log or data needed. I don't know where telegram save the logs.

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
Please switch to the official static build. If crashes will continue, enable 'Install beta versions', it will activate built-in crash reporter, send a crash report and post your crash report tag here.

**Comment by lfom** [comment]
It has been happening for a while using the official static build (third party builds seem to be more stable IMO). Maybe it is related to #24103, what still happens? Videos autoplay without audio in the app, but they get stuck and freeze the whole app for a while if the audio/video is clicked.

**Comment by ilya-fedin** [comment]
> If crashes will continue, enable 'Install beta versions' option, it will activate built-in crash reporter, send a crash report and post your crash report tag here.

Please do.
