### ISSUE TITLE
[Feature Request] Support right-click emulation on Linux touch-screen devices running Wayland

### ISSUE THREAD

**Issue by tiol11** [telegramdesktop/tdesktop#24116]
### Is your feature request related to a problem?

Hi and thank you for developing Telegramdesktop, it is working really well on my laptop. I am also using it in my Pinephone 3GB, using Manjaro Linux Plasma mobile beta10. Telegram-desktop is at version 3.5.0-1.
In the latter case, I have found no way so far to emulate right-click in the message input box. Usecase is that in order to share an URL, I copy it from the browser, then I open chat in Telegramdesktop and try to trigger the contextual menu in input box, but with no success.
I have checked that system-wide copy and paste works by pasting the link into another app (terminal).

### Describe the solution you'd like

Contextual menu to be triggered in the input box doing whatever applicable touch procedure in Telegramdesktop interface

### Describe alternatives you've considered

Workaround is to have virtual keyboard to support function keys in order to do Ctrl+V to paste. I was able to activate function keys in Phosh keyboard, but not in the Plasma mobile one.

**Comment by ilya-fedin** [comment]
Telegram Desktop is for desktops/notebooks, not for phones
