### ISSUE TITLE
GTK3 FileChooser is the worst

### ISSUE THREAD

**Issue by KAMiKAZOW** [telegramdesktop/tdesktop#2411]
The GTK3 FileChooser has the worst usability of all FileChoosers, incl. Qt's built-in one.
I get that masochists who like Gnome applications like it but why does TDesktop force that thing under proper DEs like KDE Plasma, LXQt, etc.?

**Comment by chrjguill** [comment]
there's a lot I could say, but QT's built-in file picker that used to be used in the linux builds was actually far less usable (ugly as fuck, as well as not being able to send files that were missing extensions, among a few other 'nice' quirks) than GTK's. 

Look at [this](https://github.com/telegramdesktop/tdesktop/issues/987) issue for reference, but until an unpatched QT framework is used, you're kinda stuck.

You're in the vast minority of users that complain about the gtk filepicker over the old, shitty, broken filepicker.

**Comment by KAMiKAZOW** [comment]
I want the KDE's native, far superior file picker which, among other things, displays thumbnails for images.

Users of GTK desktops should get a GTK version of Telegram and not force GTK practices onto a Qt application, just because they happened to shout loudest first.

**Comment by john-preston** [comment]
@KAMiKAZOW Does Qt apps show KDE native file picker? (as I see it is different from custom Qt file picker).

I saw code working with it in google chrome codebase, but not in Qt codebase.

**Comment by KAMiKAZOW** [comment]
Yes, all other Qt5 applications just use the KDE file picker, like QupZilla here:

![screenshot_20160921_165025](https://cloud.githubusercontent.com/assets/3259076/18716089/cdd41df8-801b-11e6-887a-f4a5d05ebbde.png)

**Comment by AndydeCleyre** [comment]
I can confirm that other Qt5 cross platform programs use the KDE file picker, such as [qbittorrent](https://github.com/qbittorrent/qBittorrent).

**Comment by Aokromes** [comment]
#987 ?

**Comment by c-cesar** [comment]
Since 2008 Qt is aware of the DE, and open a GTK file dialog under gnome and a KF5 file dialog under Plasma. So, the best is letting Qt handle this. 
But as @chrjguill pointed, maybe using a bundled Qt lib broke this feature.  
http://blog.qt.io/blog/2008/10/01/native-file-dialogs-in-gnome/

**Comment by john-preston** [comment]
@c-cesar I have to disable GTK support when I build Qt, because I have to be able to load GTK 2 or GTK 3 depending on what version of libappindicator (for GTK 2 or GTK 3) I've found — but Qt loads always GTK 2, and if I try to load GTK 3 for libappindicator and Qt loads GTK 2 for its stuff — everything crashes.

**Comment by paolomi** [comment]
@john-preston 
is it possible to build telegram-desktop without libappindicator/gtk? if there is a patch, then kde users can build a "pure qt" client, so everybody is happy ;-)

**Comment by KAMiKAZOW** [comment]
A pure client is possible since quite some time. ArchLinux has a package for that. https://aur.archlinux.org/cgit/aur.git/tree/?h=telegram-desktop-systemqt uses the system's Qt (hence the package name). Apparently it works well. Don't know it it helps against GTK3 FileChoosers, though.

**Comment by paolomi** [comment]
@KAMiKAZOW
Thanks, but that package depends on libappindicator-gtk2 and now you can't compile it without it.  My question is: is there a patch to build  telegram-desktop without libappindicator/gtk?  or is too hard to make such a patch? (I'm not a programmer, so I'm just asking). Thanks.

**Comment by msva** [comment]
@paolomi Well, it is possible to disable libindicator binding.
But unfortubatelly, it is really hard to replace all current gtk-related code with analogous non-gtk :-/
We definitelly need that @john-preston with the team take our position and implemented possibility to disable GTK crap and at least add a possibility to return Qt dialogs back (so, KDE should take care of replacing it with native KDE dialogs then).

For now, gtk dialogs are VERY useless under KDE (even because they don't inherit saved "places" and also doesn't support network KIOs (like `sftp://`,`webdavs://` and so on)).

**Comment by msva** [comment]
By the way, the patch to revert the dialogs is really oneliner ( https://github.com/msva/mva-overlay/blob/master/net-im/telegram-desktop/files/patches/9999/conditional/no-gtk/0001_disable-gtk-dialog.patch (actually, it is enough to just replace condition with false, instead of removing entire block)).

But there will still be (unneded in my opition) linking to gtk and build-dependency on libindicator..

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2958 ?

**Comment by joaopauloalbq** [comment]
Can this help?
[https://youtu.be/zA7tO4SsTHg](url)

**Comment by msva** [comment]
@joaopauloalbq I'd vote for current status-quo, when you can select whether to use (and link to) gtk-crap on build-time.
Otherwise (if devs will add checkbox to select dialogs appearance) - tdesktop will always link against gtk, which isn't nice :-/

**Comment by tehnick** [comment]
> And from maintainer point of view it is much easier to maintain one version of package

Few links:
https://pkgs.org/download/telegram-desktop
https://repology.org/metapackage/telegram-desktop/versions

Of course ebuilds for Gentoo and unofficial packages for Arch Linux (from AUR) allow easily build and install program with desired configuration options... But the most of users use prepared builds and do not devote too much attention to extra dependencies.

**Comment by joaopauloalbq** [comment]
Why not use the native system file dialogs like Kid3 does?
https://youtu.be/mBqS7DmBqmI

PS: I'm not a dev

**Comment by ognarb** [comment]
Opensuse provides the native file dialog for telegram.

**Comment by joaopauloalbq** [comment]
Now it's using native file dialog on KDE Plasma <3
Telegram 1.7.3
![Screenshot_20190605_190317](https://user-images.githubusercontent.com/9905202/58993793-1701e380-87de-11e9-8427-8d4ac4ad15ee.png)

**Comment by msva** [comment]
> Now it's using native file dialog on KDE Plasma <3
> Telegram 1.7.3

Yeah, it's good. But with GTK bindings enabled it uses Qt filechooser too.

Now, it's GTK'ers who offended :-)

Well, we, on Gentoo fixed it by adding corresponding CXXFLAGS definition on gtk-enabled builds, but I bet GTK'ers from other distros will spam issue tracker with issue about "Qt filechooser is ugly and bad" or something like that :-/

// And, actually, Qt's one is really worst than KDE's one, and GTK users deserve some kind of consystency.
But yes, it is impossible to make everyone happy without simultaneous link to both toolkits and choosing right dialogs in runtime (... and anyway, that will make **ME** unhappy :D)

**Comment by tehnick** [comment]
> Now, it's GTK'ers who offended :-)

I saw few programs which look and behavior depend on environment variables: 
```
$ env | grep DESKTOP
DESKTOP_SESSION=/usr/share/xsessions/plasma
XDG_SESSION_DESKTOP=KDE
XDG_CURRENT_DESKTOP=KDE

$ env | grep DESKTOP
DESKTOP_SESSION=/usr/share/xsessions/xfce
XDG_SESSION_DESKTOP=xfce
XDG_CURRENT_DESKTOP=XFCE
```
But I do not know is this solution standardized in any way.

> But yes, it is impossible to make everyone happy without simultaneous link to both toolkits and choosing right dialogs in runtime (... and anyway, that will make **ME** unhappy :D)

**You** may compile program from sources with special build flag to avoid unneded dependencies. This is one on main features of Gentoo. But for binary disros and for users of official builds from Telegram developers the solution with choosing program look and behavior in runtime -- the most convenient solution.

**Comment by msva** [comment]
> **You** may compile program from sources with special build flag to avoid
> unneded dependencies. This is one on main features of Gentoo. But for
> binary disros and for users of official builds from Telegram developers the
> solution with choosing program look and behavior in runtime -- the most
> convenient solution.

Exactly that. But looking on how developers writing the code, I doubt it will 
be easy to return the status-quo (only use single toolkit) even on compile 
time...

**Comment by andrew-phi** [comment]
As far as I know, tg-desktop is written using QT, why the hell is it showing GTK file dialog in Plasma-based Kubuntu!?!? Not only it is ugly, but also annoying as I always have to look and change settings to show directories first, show hidden files, sort by name. That's too damn annoying and I have to use it for work!!

**Comment by WhyNotHugo** [comment]
This is very odd, I'm seeing what I've come to know as "The telegram filepicker".

It's not the GTK one, even though all other apps use the GTK one for me (looks like the windows one).

![2020-05-30T22:47:41,925389204+02:00](https://user-images.githubusercontent.com/730811/83338754-d6d12600-a2b6-11ea-9b39-798f947d8f15.png)

Any hints on how I _could_ get the GTK one? I do miss the image previews in the file picker.

**Comment by KAMiKAZOW** [comment]
Install the desktop portal package of your distribution. The exact name you have to figure out yourself (it differs from distribution to distribution).

That said, now that Telegram Desktop moved to portals by default, the issue is now resolved as far as I’m concerned.

**Comment by WhyNotHugo** [comment]
I do have a desktop portal installed (`xdg-desktop-portal-wlr`), but I only installed that since it was required for screen-sharing with pipewire and some flatpak-only stuff.

I don't quite see how it fits in here.

How does that fit into telegram? How did you manage to change which filechooser it uses?

**Comment by KAMiKAZOW** [comment]
Apparently it’s the wrong portal package. Portals are what handle file dialogs since https://github.com/telegramdesktop/tdesktop/pull/7112

**Comment by WhyNotHugo** [comment]
`xdg-desktop-portal-wlr` is the right portal for my desktop, that's quite certain.

But that's exactly why I don't understand how it interacts with the filepicker -- what did you configure on telegram? Or on the portal? My only interaction with it so far was for screensharing.

**Comment by AndydeCleyre** [comment]
@WhyNotHugo It's not only for flatpak. You have the `wlroots` backend installed. You might try uninstalling that, and installing the one for GTK or KDE. I don't know what distro or DE you're running, but `wlroots` may not be the portal backend you want.

**Comment by KAMiKAZOW** [comment]
I’m unsubscribing from this issue now. It’s not a Telegram bug (it falls back to the GTK file chooser if no portal is present). it’s either a bug in your portal package or a distribution-specific configuration problem you possibly messed up yourself by doing lower-level stuff you have no clue about (and honestly, your confused comments point to the latter). Whichever it is, it should be discussed in a forum targeted towards that distribution/portal, not here.

**Comment by ilya-fedin** [comment]
> looks like the windows one

It is default Qt filepicker

> Any hints on how I _could_ get the GTK one?

QT_QPA_PLATFORMTHEME=gtk3

**Comment by WhyNotHugo** [comment]
Beautiful, thanks! :)
