### ISSUE TITLE
Telegram does not process mime during installation

### ISSUE THREAD

**Issue by saber716rus** [telegramdesktop/tdesktop#24117]
### Steps to reproduce

Opening telegram links in the browser

### Expected behaviour

Opening telegram links in the program

### Actual behaviour

Error writes: Unknown mime protocol

### Operating system

Mageia 8 KDE Plasma Version: 5.20.4 KDE Frameworks Version: 5.76.0 Qt Version: 5.15.2 OS Type: 64-bit Process

### Version of Telegram Desktop

3.5.2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
This is a known long-standing KDE bug...
