### ISSUE TITLE
Ukraine crisis 🇺🇦🇺🇦🇺🇦

### ISSUE THREAD

**Issue by kyrylich** [telegramdesktop/tdesktop#24113]
Russia uses telegrams channels to spread fake information against Ukraine. Thousand reports were send by Ukrainians, but no reaction. Telegram do nothing

Durov and your team, are you really against the Putin’s regime and Russians aggression not?! Do something!!

**Comment by ArchiGn98** [comment]
Block disinformation channels!

**Comment by ZorgikUA** [comment]
Block disinformation channels!

**Comment by Aokromes** [comment]
this is telegram desktop bugtracker, not a complain place.
