### ISSUE TITLE
Reactions Show Profile of Anonymous admin

### ISSUE THREAD

**Issue by ZekXtreme** [telegramdesktop/tdesktop#24110]
### Steps to reproduce

1. Send Any message 
2. Make an anonymous admin react to it.

### Expected behaviour

Reactions Should not reveal the profile of anonymous admin.

### Actual behaviour

Reactions Revealed the Profile of anonymous admin 
![image](https://user-images.githubusercontent.com/83297638/155826957-074f39c5-fc6e-4db1-bf9b-c5a2915819ee.png)
The Levi Guy is Anonymous admin But Reaction revealed His Profile

### Operating system

Windows 10

### Version of Telegram Desktop

3.5.1 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@ZekXtreme Reactions can be only from users right now :( You can escalate this issue on bugs.telegram.org, there is nothing that can be done in TDesktop code to resolve it, sorry.

**Comment by ZekXtreme** [comment]
@john-preston Thanks for the Clarification
