### ISSUE TITLE
Mouse scrolling does not work

### ISSUE THREAD

**Issue by junaidbinfarooq** [telegramdesktop/tdesktop#24127]
### Steps to reproduce

Open any existing chat and try to scroll up/down.

### Expected behaviour

I should be able to scroll up and down.

### Actual behaviour

The scrolling does not work in any existing chats after (perhaps) the latest update.

### Operating system

Linux (Ubuntu)

### Version of Telegram Desktop

3.5.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#17254

**Comment by ilya-fedin** [comment]
Yes
