### ISSUE TITLE
config reset at reboot

### ISSUE THREAD

**Issue by R0flcopt3r** [telegramdesktop/tdesktop#2412]
### Steps to reproduce
1. reboot
2. launch Telegram

### Expected behaviour
Stuff should be exactly how they were.

### Actual behaviour
Settings reset, like local password, replace emoji. Doesn't happen all the time, some times only emojis, sometimes only password.

### Configuration
Ubuntu 16.04

Telegram 0.10.1

**Comment by sergekhakhin** [comment]
I have almost the same situation, but on Windows 10 (10.0.14393.187).

You even don't have to reboot the computer: just quit Telegram Desktop, then launch it, go to Setting of Telegram. If the setting hasn't changed repeate quiting and lauching again. Usully it happens after two times restarting Telegram. The settings that go to default are the whole group 'Notifications',  'Replace emoji'. The other setting don't change.

**Comment by john-preston** [comment]
@sergekhakhin Can you specify from which to which settings are they changed?

**Comment by sergekhakhin** [comment]
@john-preston, 
[Here's](https://s14.postimg.org/dhreug701/2016_09_14_20_41_50.png) my current settings.

What I'm doing now:

1. Quit Telegram;
2. Launch Telegram;
3. Go to the settings — settings are fine.
4. Quit Telegram;
5. Launch Telegram;
6. Go to the settings — and my settings go to [this](https://s21.postimg.org/7m9yvf6x3/2016_09_14_20_51_40.png).

**Comment by john-preston** [comment]
@R0flcopt3r @sergekhakhin is it true you both have "Tile background" checkbox enabled in the settings that are reset from time to time? I think I've found one bug.

**Comment by sergekhakhin** [comment]
@john-preston, you're goddamn right! If checkbox "Tile background" is not checked the settings don't change after restarting Telegram Desktop.

**Comment by jaekyeom** [comment]
@john-preston I'm also having a problem that tdesktop loses its download history: downloaded files still exist on the disk, but it doesn't think so and tries to download again when I click it.
Is that bug related to this download issue, too? My "Tile background" setting is enabled.

**Comment by john-preston** [comment]
@jaekyeom Perhaps it is. You can check it ;)

**Comment by john-preston** [comment]
Please check the latest version.

**Comment by Masoud-MSK** [comment]
Telegram auto-updated to v1.5.12 and 'Automatic media download' settings reset after update. I remember the same issue after the latest update, too.

**Comment by john-preston** [comment]
@Masoud-MSK So it does remember the settings between launches, but forgets after an update? Or forgets on system restart (for example) as well?

**Comment by Masoud-MSK** [comment]
Just after the last two updates. Relaunch and system reboot doesn't reset the settings and works fine.
