### ISSUE TITLE
[Question] New settings icons have low contrast

### ISSUE THREAD

**Issue by PeterNjeim** [telegramdesktop/tdesktop#24121]
I updated to the beta version 3.5.3 to get the new titlebar padding, which works wonderfully, however I noticed new icons in the side menu and in the settings. These icons feel like they come from an iOS/macOS style, and the background is too bright for the white icon in the middle. It honestly makes them harder to recognize than the previous monotone wireframe icons. Is this a feature that you must implement? Or was it out of your own volition, thanks.

**Comment by PeterNjeim** [comment]
For example, on the Chat Settings icon, it fails all contrast checks:
![image](https://user-images.githubusercontent.com/26418974/156069336-34343a87-2879-4bf9-add4-2b3c1e2f453e.png)

**Comment by PeterNjeim** [comment]
Out of all the backgrounds, the red is the best, though it still fails most tests:
![image](https://user-images.githubusercontent.com/26418974/156069698-eb1d8d1a-4fc3-488c-8aaa-dd7a9d325106.png)

**Comment by john-preston** [comment]
Those are official design mockups, so I'm sorry. But I'll forward your feedback.

**Comment by PeterNjeim** [comment]
Due to the (now-old) addition of monotone icons, closing
