### ISSUE TITLE
Incorrect phone number spacing on 3.5.4 beta

### ISSUE THREAD

**Issue by nyuszika7h** [telegramdesktop/tdesktop#24131]
### Steps to reproduce

1. Install Telegram Desktop 3.5.4 beta (snap edge channel)
2. Log in to an account registered with a Hungarian phone number (might also apply to other countries)
3. Open Settings

### Expected behaviour

The phone number should be separated like this, like in the older versions:
```
+36 20 123 4567
```

### Actual behaviour

The phone number is now separated like this:
```
+36 201 234 567
```

Note that `20` is the carrier code for Yettel (formerly Telenor) here, so it's wrong to group it with the rest of the number, and it looks weird too.

This is just a small cosmetic thing, but it's technically incorrect and not just a personal preference, and it is shown correctly in the Telegram iOS app.

### Operating system

Ubuntu 21.10

### Version of Telegram Desktop

3.5.4-beta (3748)

### Installation source

Snap

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by nyuszika7h** [comment]
Yes, still happens on 3.6.2.
