### ISSUE TITLE
Audio & Video Voice Recognition --> Automatic Subtitle Generator & Translator

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#24136]
### Is your feature request related to a problem?

Da

### Describe the solution you'd like

In YouTube, if you upload a video, and select video language in settings before posting,
it will use voice recognition to create subtitles "closed caption" with time code .srt

also can translate subtitles .srt text file, to other languages.

There are many videos on Telegram that could benefit form that feature.

### Describe alternatives you've considered

None

**Comment by 23rd** [comment]
https://bugs.telegram.org/c/12146
