### ISSUE TITLE
Automatic Bidirectional Translation

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#24135]
### Is your feature request related to a problem?

si

### Describe the solution you'd like

There are many Channels on Telegram in other languajes, italia, Russia, German
i don´t understand...
i only understand english & spanish

i´m Not a News reporter that knows 9 languages.

https://duckduckgo.com/?t=ffab&q=translator&ia=web
copy & paste is too much latency & much effort for a channel with 1000 of comments.

https://translate.google.com/
has banned some webpages.

Bidirectional...
i write in english or spanish and translates automatically
like duckduckgo web translator, has a split windows to see the translation.
i can detect errors i wrote more easy.

### Describe alternatives you've considered

https://duckduckgo.com/?t=ffab&q=translator&ia=web
select text from T.Desktop
Copy
& Paste in Webrowser 

too tedious.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6707
