### ISSUE TITLE
A.I. Video & Photo OCR

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#24137]
### Is your feature request related to a problem?

Yes,

### Describe the solution you'd like

YouTube search engine:
if you search words that are on the video or photo, 
but Not on the title, Not on the Tags, Not on the video description, Not in the video comments.

are detected anyway,
even if the video is totally unrelated and shows the thing i´m looking for only 1 second in the screen,
A.I. detects that thing i´m searching.

https://en.wikipedia.org/wiki/Optical_character_recognition

in Telegram can be used for Search engine
but also to translate photos & video text.

### Describe alternatives you've considered

None.

**Comment by 23rd** [comment]
https://bugs.telegram.org/c/5203
