### ISSUE TITLE
Download bar stays open after download is finished

### ISSUE THREAD

**Issue by hessam-kk** [telegramdesktop/tdesktop#24132]
### Steps to reproduce

1. start a download (like music)
2. close telegram (using ctrl+w or by clicking on X button)
3. wait a few seconds to download be completed
4. reopen the telegram

### Expected behaviour

download bar disappears after download is finished

### Actual behaviour

leave a blank section like this:
![1](https://user-images.githubusercontent.com/24957423/156396323-c92d50b7-3488-4eb4-ba91-699297c4c57d.png)

as you see it covers a chat with blue avatar...

that blank section stays open and you cannot get rid of it without resizing the entire telegram window or completely closing (from tray) and reopening the app..

### Operating system

windows 11

### Version of Telegram Desktop

3.5.4 beta x64

### Installation source

Static binary from official website

**Comment by aAsumA** [comment]
1

**Comment by aAsumA** [comment]
2

**Comment by aAsumA** [comment]
3

**Comment by aAsumA** [comment]
4
