### ISSUE TITLE
[Feature Request] Open each chat in separate window (third try)

### ISSUE THREAD

**Issue by ClaudiuHNS** [telegramdesktop/tdesktop#24141]
### Is your feature request related to a problem?

Allow Telegram users to open chat in separate windows.

Why?
1. Very comfortable to switch from one chat to another (with Alt+Tab)
2. Users can have multiple conversations at the same time without having to switch between each other to read messages. Very useful when awaiting a message response from someone.

### Describe the solution you'd like

Similar with the old "Yahoo! Messenger". 

### Describe alternatives you've considered

Anything similar with the old "Yahoo! Messenger".

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2105

**Comment by Dangalramsham** [comment]
Hi

**Comment by Dangalramsham** [comment]
> https://github.com/telegramdesktop/tdesktop/issues/2105

https://mail.google.com/mail/u/0/#spam?compose=CllgCJlGTkbDrVVzRPwFGNQbKmcZDVgQgwPdwJrHdmxjCLGGqMstSfkVZPvXcpBPGSnbcxvslDB0xA7eEbFf8e4399D1b3D1d60a7D826cCf061D2f90b
