### ISSUE TITLE
mp3: high frequency sags

### ISSUE THREAD

**Issue by Nammehub** [telegramdesktop/tdesktop#24145]
### Steps to reproduce

-

### Expected behaviour

-

### Actual behaviour

I played mp3 in windows. And then uploaded to telegram and played in the application.
It seemed to me that the high frequencies were muffled.
Check self with an objective test:
Put the [sawtooth waveform](https://en.wikipedia.org/wiki/Sawtooth_wave) (reference) in mp3. Play mp3 and record the signal sounding in Windows. Check the spectrograms. The spectrograms of records must be absolutely identical.
In the image editor, I superimposed two images of the spectrograms of played mp3.  So can see even the smallest differences. However, the differences were significant. So significant that they are perceptible to the ear.
It can be assumed that the players has an influence. However, I tried different players for Windows. And the situation repeats itself: the players have an equal spectrogram. (combined spectograms of [AIMP](https://en.wikipedia.org/wiki/AIMP) and ["Groove Music"](https://en.wikipedia.org/wiki/Groove_Music)  Windows 10 native audio player- [screenshot](https://i2.paste.pics/f34e3b60a89986b893fb852e112049ff.png))
The telegram apps spectogram is different.

spectrum Telegram app, spectrum AIMP
combined

please ask for more information.
![Untitled](https://user-images.githubusercontent.com/58394819/156881361-8112eea0-fbdf-4867-bde8-6f68fe48a143.png)

 

### Operating system

Windows 10

### Version of Telegram Desktop

3.5.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Is this a regression or something that always has been?

**Comment by Nammehub** [comment]
> 

I can't answer you, I don't know. Since I reported the very next day after finding

**Comment by Nammehub** [comment]
comparing Telegram Web Z and Telegram Desktop (Windows 10)

if necessary, I'll screencast steps to reproduce - how to carry out such measurements[ (spectral analyze of audio signal)](https://www.google.com/search?q=spectral+analysis+of+audio+signal). But any specialist/sound engineer knows what to do.
![Untitled](https://user-images.githubusercontent.com/58394819/157101360-06397d86-49e2-41fc-8585-f5afd1492ebd.png)
