### ISSUE TITLE
Telegram crashes after playing song

### ISSUE THREAD

**Issue by ImAmirreza** [telegramdesktop/tdesktop#24143]
### Steps to reproduce

1. Open telegram
2. Play voice or song
3. Switch account 
4. Crash!

### Expected behaviour

to continue playing song and opening desired account.

### Actual behaviour

Crash

### Operating system

Windows 10 64bit 

### Version of Telegram Desktop

3.5.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by beglort** [comment]
I was about to report same bug for the Flatpak version: 3.5.2
Fedora 35 - KDE Plasma 5.24.2 - KDE Frameworks 5.91 - Qt version 5.15.2 - Kernel 5.16.12
The bug occurs with any media that has audio (voice, music, video)
