### ISSUE TITLE
Telegram KDE - Kubuntu tray icon

### ISSUE THREAD

**Issue by hesediel84** [telegramdesktop/tdesktop#2414]
hello that is how i see the tray icon of telegram in Kubuntu 16.04 with plasma 5
https://s13.postimg.org/80eqwbrzr/Screenshot_20160910_100322.png
is there a way to fix it and get a better icon?

 
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by Kondra007** [comment]
Please, use `Search` next time.
Duplicate #2230
