### ISSUE TITLE
Slaw downlad in the RDP

### ISSUE THREAD

**Issue by xMA3x** [telegramdesktop/tdesktop#24149]
So i'm using an RDP(win server 2019) to download some stuff form telegram desktop 
anyway, in the recent time when i download any file the download form the telegram it download in like 200kb/s 
in the other hand, When i do speed test it shows that the internet is perfect and reach to 500MB/S !

i tread to :
 1- restart the computer
 2- run an Antispayware software
 3- reinstall the telegram app 
 4- open telegram web 
and nothing was fixed the problem 

note : idk why but anything related to the telegram is being limited, when i download the telegram desktop app it download in like 200kb/s but when i download any other file or software it download in 20 or even 30 mb/s
![Capture](https://user-images.githubusercontent.com/56519023/156941928-6179f21e-47a6-40ca-8b98-c670b354b2da.PNG)
so that problem is NOT form the internet!

that bug happened our of suddenness it not used to be like that!

**Comment by Aokromes** [comment]
this is telegram desktop repository, not telegram web.
such issue belongs to https://bugs.telegram.org/
