### ISSUE TITLE
Snap version on channel latest/stable outdated

### ISSUE THREAD

**Issue by jzmp** [telegramdesktop/tdesktop#24147]
### Steps to reproduce

1. Install Telegram Desktop (snap channel latest/stable)

### Expected behaviour

The installed version is 3.5.2 as this is [currently latest](https://github.com/telegramdesktop/tdesktop/releases/latest).

### Actual behaviour

The installed version is 3.4.3.

### Operating system

Ubuntu 20.04

### Version of Telegram Desktop

3.4.3 (3544)

### Installation source

Snap

**Comment by krushnaj** [comment]
Any update on this?

**Comment by webarchitect609** [comment]
Current situation:

1) Snap:
```
$ snap info telegram-desktop
...
channels:
  latest/stable:    3.4.3               2022-01-03 (3544) 339MB -
  latest/candidate: ↑                                           
  latest/beta:      ↑                                           
  latest/edge:      3.6.2-49-ge8748986b 2022-03-30 (3860) 339MB -
```

2) Downloading from telegram.org:

```
$ wget --content-disposition https://telegram.org/dl/desktop/linux
...
tsetup.3.6.1.tar.xz
...
```

**3.4.3 via snap vs. 3.6.1 via direct binary download**

Please, fix!

**Comment by garro95** [comment]
I can confirm this issue

**Comment by raphaelbernardino** [comment]
The following workaround can be used until stable is fixed.

```$ snap refresh --channel=edge telegram-desktop```

source: https://snapcraft.io/docs/channels

**Comment by webarchitect609** [comment]
@raphaelbernardino , nope. I wish things could be so easy, but that's not a workaround. You'll get risky unstable `3.6.2-49-ge8748986b` instead of stable `3.6.1`.

**Comment by webarchitect609** [comment]
`3.7.0 === 3.7.0`
Resolved! Thanks!

```
$ snap info telegram-desktop
...
channels:
  latest/stable:    3.7.0              2022-04-17 (3905) 335MB -
...

```
```
$ wget --content-disposition https://telegram.org/dl/desktop/linux
...

tsetup.3.7.0.tar.xz
...

```
