### ISSUE TITLE
[Feature Request] Add a spell check

### ISSUE THREAD

**Issue by Pub4Game** [telegramdesktop/tdesktop#2415]
I write messages very quickly and miss some letters. I think it will be helpful to many. (Russian) 

![image](https://cloud.githubusercontent.com/assets/11244874/18410231/0040b0ea-7765-11e6-9882-6a272dd05656.png)

For example, I took the word - сообщение

**Comment by stek29** [comment]
Please search for existing issues before creating duplicates.
See #96.
