### ISSUE TITLE
"trade" folder icon was a growing histogram, now it's bitcoin's icon

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#24151]
Hello there,

Commit a6d59fc updated the folders icons' design to a more modern one, but it also changed the "trade" icon: from a generic growing histogram to the bitcoin's icon.

Given the lack of generic icons about common categories (#7997), I believe a generic graph has often been used by many people as the icon of folders that do not necessarily contain "cryptocurrencies trade" chats/channels (I was personally using it for my "news" folder).

Is this change intended? Are there any plans to bring the histogram icon back, or to provide a broader selection of icons?

**Comment by Aokromes** [comment]
this is already fixed no?

**Comment by RememberTheAir** [comment]
yes
