### ISSUE TITLE
Using the built-in input method to check the compatible version of typing will occasionally turn into English

### ISSUE THREAD

**Issue by yangyang0223** [telegramdesktop/tdesktop#24150]
### Steps to reproduce

Using the built-in input method to check the compatible version of typing will occasionally turn into English

### Expected behaviour

Hope to repair

### Actual behaviour

Using the built-in input method to check the compatible version of typing will occasionally turn into English

### Operating system

win10

### Version of Telegram Desktop

3.5.1

### Installation source

Mac App Store

**Comment by ttygde** [comment]
If I use non english lang in tdesktop and then press Space it will automatically switch to english while at other apps it is still non-english. Arch linux, 3.6.
