### ISSUE TITLE
Nickname gets cropped in the Pin Message dialog box if it's too long

### ISSUE THREAD

**Issue by RDKRACZ** [telegramdesktop/tdesktop#24153]
### Steps to reproduce

1. Change someone's nickname to something long
2. Try to pin a message in this chat
3. 
![image](https://user-images.githubusercontent.com/43277609/157037581-14fef0e3-3718-45cc-bf6f-3456ff8bc6aa.png)

### Expected behaviour

The text should wrap to the next line

### Actual behaviour

The text is cut

### Operating system

openSUSE Leap 15.3, KDE 5.24.2

### Version of Telegram Desktop

3.5.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> 2.5.2

2.5.2?

**Comment by 23rd** [comment]
> 2.5.2?

Still occurs anyway.

**Comment by RDKRACZ** [comment]
*3.5.2 sorry

**Comment by 23rd** [comment]
Should be better in 3.6.0.
