### ISSUE TITLE
Update Telegram Please

### ISSUE THREAD

**Issue by huezo** [telegramdesktop/tdesktop#24162]
### Is your feature request related to a problem?

![2022-03-09_13-39](https://user-images.githubusercontent.com/15940634/157520720-7c7795c0-f2d1-4477-9fec-c13200b386ac.png)

**Update Telegram Please**
https://snapcraft.io/telegram-desktop

### Describe the solution you'd like

Update Telegram Please

**Comment by ilya-fedin** [comment]
#24147
