### ISSUE TITLE
[Visual] Stream window shadow after unpin

### ISSUE THREAD

**Issue by c0re100** [telegramdesktop/tdesktop#24163]
### Steps to reproduce

1. Pin stream window
2. Move to another window (Telegram is ok too!)
3. Go back stream window and unpin it
4. Move to another window

### Expected behaviour

Window shadow should not exist.

### Actual behaviour

Window shadow on my screen :(
![{1FB781A6-4AED-4B0B-AACC-54AF7734B910}](https://user-images.githubusercontent.com/5726473/157526933-6f7dbf5e-feec-404d-acfc-146e0c361b2d.png)

### Operating system

Windows 10 1909

### Version of Telegram Desktop

3.5.6 Beta

### Installation source

Static binary from official website

**Comment by c0re100** [comment]
still reproduce.

**Comment by c0re100** [comment]
still reproduce.

**Comment by ilya-fedin** [comment]
FYI Windows 11 has native resize now
