### ISSUE TITLE
YouTube Timestamps with two decimal hours doesn't work

### ISSUE THREAD

**Issue by BANOnotIT** [telegramdesktop/tdesktop#24167]
### Steps to reproduce

1. Create a message with a long youtube video link
2. Create a timestamp with two digitss for hours, e.g. 12:01:00 and timestamp with one digit for hours, e.g. 9:00:00

### Expected behaviour

Both timestamp appear to be links for timestamps

### Actual behaviour

Only 9:00:00 becomes a link

[Example failed message](https://t.me/aws_notes/2083)

### Operating system

Linux Ubuntu

### Version of Telegram Desktop

3.5.6 beta

### Installation source

Static binary from official website

Feature request for this functionality #8048

**Comment by john-preston** [comment]
There is no duration information for youtube videos right now (in the webpage preview) the duration was chosen as 10 hours, so the timecodes later than 10 hours are not highlighted. I'll ask for the duration information if it can be provided or if not, I'll just increase it to 100 hours.
