### ISSUE TITLE
macos icons appear in non-macos tdesktop builds

### ISSUE THREAD

**Issue by Younes-L** [telegramdesktop/tdesktop#24176]
### Steps to reproduce

1. Install tdesktop linux binary or window binary on respective system
2. open the side navigation drawer (aka "main menu")
3. open settings screen

### Expected behaviour

icons should not look like macos. Only macos tdesktop build should show macos style icons (if that's your thing). 
There are already many differences and changes between the tdesktop for macos build and tdesktop for windows or linux. This should be one of such differences.
The previous icons were fine for this job :

like this in drawer 
![image](https://user-images.githubusercontent.com/23421600/157989599-ea291021-edcd-4090-9b72-c923b9c075b0.png)

and this in settings screen 
![image](https://user-images.githubusercontent.com/23421600/157989371-aac1b56e-aac9-41a5-ab08-e2bf0ffa71eb.png)

### Actual behaviour

icons look like macos , even in non-macos tdesktop builds, which does not fit with the rest of the system or any other program

here in drawer ![image](https://user-images.githubusercontent.com/23421600/157988528-1afd34c0-be2c-46ce-8300-6ee4d7fe714b.png)

here in settings screen ![image](https://user-images.githubusercontent.com/23421600/157988217-df6ee808-8d2d-4091-8223-03f99935e839.png)

### Operating system

fedora, 34, cinnamon

### Version of Telegram Desktop

3.6.0

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
This is intended, sorry. Has nothing to do with macOS.

**Comment by Younes-L** [comment]
@john-preston alright, i don't blame you and i knew coming in the situation was hopeless xD  
i wish having enough voices against this would make telegram reconsider these unnecessary changes... the goal may not have been to make it look like macos, but the results speak for themselves.  
it's especially frustrating to see telegram talking so much crap about apple, and yet all of telegram's designs and designers follow apple religiously.  
i'll throw in some more evidence if it helps :

1) macos users agree that these icons come straight from macos : (#24121)
    <details><summary> "these icons feel like they come from an iOS/macos style" </summary>
    
    ![image](https://user-images.githubusercontent.com/23421600/158069262-b8f1bfec-5eec-4161-a620-cd7381faac35.png)
    
    </details>

2) here's a comparison with the macos client 
    
| tdesktop 3.5.0 | tdesktop 3.6 | tmacos |
|-------------|-----------|-----------|
| ![image](https://user-images.githubusercontent.com/23421600/158069450-e172ddbf-636f-474f-9f3f-c7dd1b414687.png) | ![image](https://user-images.githubusercontent.com/23421600/158068670-b4360b19-abb3-43a8-a08f-5e443d622b8b.png) | ![image](https://user-images.githubusercontent.com/23421600/158069118-ae1467ce-8a62-4c66-b9c8-2d948a27b3fc.png) |
| ![image](https://user-images.githubusercontent.com/23421600/158070151-4f0c3507-312e-45cb-b144-abd327b2ebbb.png) | ![image](https://user-images.githubusercontent.com/17455618/157985018-7537b80c-ef43-4cfa-ba22-224e36bf5506.png) | ![image](https://user-images.githubusercontent.com/23421600/158069922-9fa7f803-2b3a-4eee-9187-59a5e8f21288.png) |
| (wireframe folder icons) |  (solid folder icons) | (solid folder icons) |

**Comment by john-preston** [comment]
![image](https://user-images.githubusercontent.com/17900494/158115255-e625fdae-c480-4b63-8ee6-695d3996e6a1.png)

=)
