### ISSUE TITLE
[Feature Request] Add the "Add to Folder" button to the chat context menu

### ISSUE THREAD

**Issue by kr-ilya** [telegramdesktop/tdesktop#24171]
### Is your feature request related to a problem?

It is inconvenient to add a chat to a folder.

### Describe the solution you'd like

Add a menu item to
![image](https://user-images.githubusercontent.com/42733472/157873079-f6507716-83a5-4fd8-9c25-46dec570c0f2.png)
and to
![image](https://user-images.githubusercontent.com/42733472/157873410-922c54b6-335a-4024-af08-f235b6be8486.png)

### Describe alternatives you've considered

-

**Comment by ilya-fedin** [comment]
#7927
