### ISSUE TITLE
[Feature Request] Allow user to pause message receiving + autoreplay

### ISSUE THREAD

**Issue by Archirk** [telegramdesktop/tdesktop#24170]
### Is your feature request related to a problem?

I have a lot of channels, groups and chats - they are not essential and so they are muted. However, sometimes I can not control urge to check them every time i see new notifictation (e.g. Russia-Ukraine conflict updates). It drastically reduces my productivity and psychological health.  
It also can be usefull for remote who go on vacation and do not want be bothered by work routine.

### Describe the solution you'd like

Delayed message receiving with optional autoreply feature for selected chat/bots/channels/groups.  

**Details:  
Delayed message**
In settings user can choose chats from which telegram will stop receiving  messages for user.
User sets preferable delay: it could like "every 1\2\3\.. hour" or at specific time e.g. 21:00., so every specific period or at specific time user's client will collect all delayed messages and send him notifications.  

From user perspective: In this "mode" he see no sign of messages on hold - he only have some push reminder that telegram client in delayed mode.  

From sender perspective: It's better to let sender now not just message is unread but that user in "delayed" mode. It could be some indicator near prifle picture, OR new status for messages (read/unread/in process + delayed)  

**Autoreplay:**
If this feature would be implemented it can be usefull to let user create custom message for auto-replay during delayed mode. So, for example, user can say that he will read message at 21:00 , or he is on vacation, or he can provide "emergency contact"  

User, of course can'not see that his client is sending this messages, because it would be like notification for hiv, that some chat has message for him.

### Describe alternatives you've considered

Deleting chats to prevent checking, but it does not help - i just spend extra seconds to find them again and check without joining channels\groups

**Comment by RememberTheAir** [comment]
Not sure if you are aware about this feature so I will mention it: if you right-click on a chat, there's an option to archive it. If they are muted, archived chats will not appear in your main chats list unless you are mentioned by username, or someone replies to one of your messages. The archive can be placed at the top of your chats list, or inside the sidebar.

Telegram has also an additional level of organization which is called "folders", that can be used to categorize chats (search for it in the settings)

**Comment by Archirk** [comment]
Archieved and folders still sent notifications. Core thought of feature - eliminate notifications at all

**Comment by RememberTheAir** [comment]
Aren't they muted already? Correct me if I'm wrong but you seem to imply that in the opening of the ticket

Btw I'm afraid that what you're asking for needs to be supported on every app and not on tdesktop alone - so it belongs to https://suggestions.telegram.org

**Comment by Archirk** [comment]
You probably right. I did thought about desktop\general feature. I close issues and open it in suggestions. 

Few times when some one writes in archived groups i get notifications anyway.
