### ISSUE TITLE
Feature Request] Control audio volume in RTMP streams

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#24177]
### Is your feature request related to a problem?

It's not possible currently to adjust audio volume while watching RTMP streams

### Describe the solution you'd like

Add a volume controller to such streams 

### Describe alternatives you've considered

Change volume system-wide (like on Instagram)

**Comment by 23rd** [comment]
Did you try right click to open context menu?

**Comment by MasterGroosha** [comment]
@23rd lol, it’s counterintuitive, but yeah, I see volume control there
