### ISSUE TITLE
right click -> view profile is gone

### ISSUE THREAD

**Issue by siamak2** [telegramdesktop/tdesktop#24175]
### Steps to reproduce

right click on a chat from chat list 

### Expected behaviour

show an option called view profile

### Actual behaviour

view profile doesn't exist

### Operating system

windows 10

### Version of Telegram Desktop

3.6

### Installation source

Static binary from official website

**Comment by siamak2** [comment]
I've updated from 3.4 to 3.6 so I don't know in which version this happened.

**Comment by Younes-L** [comment]
it was removed in v3.4.3 c1d948e

while it's not a solution, you can restore it by doing the following : 
* go to settings > advanced > version and updates
* enable automatic updates (necessary but illogical requirement) 
* enable beta versions (necessary but illogical requirement)
* open experimental settings and enable the view profile button

**Comment by siamak2** [comment]
@Younes-L thanks. I didn't know experimental settings existed!
you are right it's not a solution but it works for now so I'm closing the issue
