### ISSUE TITLE
[Bug] Deep Linking not working when switching chats starting from bot

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#2417]
Before we start. Consider BOT as one particular bot and CHANNEL as one particular channel

### Steps to reproduce
1. BOT sends you username of `@CHANNEL`
2. In CHANNEL, you see URL Inline Button with link `https://telegram.me/BOT?start=whatever` (deep linking)
3. You press this link

### Expected behaviour
You should return to chat with BOT with "START" button instead of input field
**Update**: Same thing happens with supergroups

### Actual behaviour
You return to chat with BOT with input field instead of START button.
**Hint.** If you add step zero: "Open CHANNEL", then you can press button - see "START" - see username `@CHANNEL` and so on without any problems.
Bug occurs only if you start "chat switch history" from BOT

### Configuration
**Operating system:** Windows 10 x64 LTSB (non-Anniversary update)
**Version of Telegram Desktop:** <s>0.10.4 alpha</s> 0.10.16 alpha/stable

**Comment by stek29** [comment]
Does it happen for users/groups too or only for channels?

**Comment by Kondra007** [comment]
@stek29 I've tested this for supergroups too and the bug is present there as well. Thanks, updated issue.

**Comment by Kondra007** [comment]
Still here: 0.10.16

**Comment by Kondra007** [comment]
Fixed in 0.10.17 alpha. Thanks!
