### ISSUE TITLE
[Feature Request] Create an option to toggle new and old icons

### ISSUE THREAD

**Issue by TheHumphrey** [telegramdesktop/tdesktop#24186]
### Is your feature request related to a problem?

Icons update on 3.6 version

### Describe the solution you'd like

The icons in version 3.6 is so visually polluted.

### Describe alternatives you've considered

looking for theme

### Additional context

the new icons in the new version are so polluted compared 
to the previous ones, and there is no option in the app to switch 
to the previous icons.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/24174#issuecomment-1066333620

**Comment by john-preston** [comment]
Well, old ones won't be done, but I've added a re-coloring experimental setting.
