### ISSUE TITLE
How about some instructions to clean out build artifacts? [Feature Request] 

### ISSUE THREAD

**Issue by paxe** [telegramdesktop/tdesktop#24185]
### Is your feature request related to a problem?

I'm attempting to compile according to docs/building-linux.md, so far unsuccessfully, but the major ongoing problem seems to be that disk requirements are infinite. Every re-attempt with more space fills up the space I just added.

### Describe the solution you'd like

Instructions to perform equivalent of a make clean.

### Describe alternatives you've considered

I've looked under my /var/lib/docker/, but I also use docker for another purpose which I don't really know internals for, therefore clearing space isn't apparent without some suitable description as to what file the tdesktop build puts into docker.

**Comment by ilya-fedin** [comment]
https://docs.docker.com/engine/reference/commandline/images/
https://docs.docker.com/engine/reference/commandline/ps/
https://docs.docker.com/engine/reference/commandline/rm/
https://docs.docker.com/engine/reference/commandline/rmi/

**Comment by paxe** [comment]
Thanks... so the answer to my question seems to be docker image prune and docker container prune.
Is it worth me patching the doc? I'm not sure I know enough about docker to say anything intelligent.

**Comment by ilya-fedin** [comment]
I don't think we need to teach people the basics of docker, it's something they have to learn on their own if they want

**Comment by paxe** [comment]
OK, but one thing that would've saved me a lot of grief would've been some kind of warning about the tens of gigabytes of disk space that are consumed by this. I prefer to leave only a few gigs of free space on each filesystem, then grow with LVM as needed.
