### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by hleft** [telegramdesktop/tdesktop#24184]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

now in hidden modes (https://github.com/telegramdesktop/tdesktop/wiki/Hidden-modes), have `videoplayer | Use internal or external video player`

hope also support `imageviewer | Use internal or external image viewer` for see image

### Describe alternatives you've considered

nothing else

**Comment by ilya-fedin** [comment]
#1111
