### ISSUE TITLE
URLs don't open by xdg assocations

### ISSUE THREAD

**Issue by Pound-Hash** [telegramdesktop/tdesktop#24188]
### Steps to reproduce

1. Click URL
2. Chromium opens instead of qutebrowser.

### Expected behaviour

qutebrowser should open because it is associated with http, https, and html file types in my xdg settings.

I've done:
```
$ xdg-mime default _qutebrowser.desktop_ x-scheme-handler/http
$ xdg-mime default _qutebrowser.desktop_ x-scheme-handler/https
```
And,
```
xdg-settings set default-url-scheme-handler http _qutebrowser.desktop_
xdg-settings set default-url-scheme-handler https _qutebrowser.desktop_
```
I've also added the line, `MimeType=application/x-xdg-protocol-tg;x-scheme-handler/tg;`, to the end of the `telegram.desktop` file.

`$BROWSER` is set to `qutebrowser`.

### Actual behaviour

Chromium opens instead of qutebrowser.

### Operating system

Arch, Sway 1.7, Wayland

### Version of Telegram Desktop

3.6

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop uses glib library that implements the XDG mime spec specification to open URLs and files. If you think it works wrongly, you should open an issue at glib bugtracker.

**Comment by ilya-fedin** [comment]
A note: $BROWSER is not a part of [the specification](https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html), so if you rely on that, the fact it doesn't work as you want is intended

**Comment by Pound-Hash** [comment]
> A note: $BROWSER is not a part of [the specification](https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html), so if you rely on that, the fact it doesn't work as you want is intended

I was merely providing information I presumed may be of help. The reason for its possible relevance was that running `xdg-settings set default-web-browser <browser.desktop>` fails with the message, `xdg-settings: $BROWSER is set and can't be changed with xdg-settings`. Now I don't know enough to know what effect the variable $BROWSER has with respect to xdg's specs, hence my submission of this information.

It's unlikely that the developers intended the feature to fail to work for me. What is likely is that they intended the feature to work the way it works. These are not equivalent. If the feature doesn't work for me, that could be for several reasons. None of those reasons are intended.

**Comment by ilya-fedin** [comment]
> It's unlikely that the developers intended the feature to fail to work for me.

I mean $BROWSER is a non-stamdard thing, so not all applications would respect it. Whatever Chrome uses respects it, glib doesn't respect it. So if you want you associations to work with all applications, you shouldn't rely on non-standard things.

**Comment by pleshevskiy** [comment]
@ilya-fedin 
I have the same issue

```
➜  ~ xdg-settings get default-web-browser
librewolf.desktop
➜  ~ xdg-mime query default x-scheme-handler/https
librewolf.desktop
➜  ~ xdg-mime query default x-scheme-handler/http
librewolf.desktop
```

`xdg-open https://google.com` opens link via `librewolf.desktop`, but links from telegram opens via `firefox.desktop`

**Comment by ilya-fedin** [comment]
Don't you use KDE? It sets the browser to its configs rather than to XDG associtaions and then xdg-open/xdg-mime/xdg-settings detect they're running on KDE and uses KDE binaries that read KDE configs instead of XDG associations...

**Comment by pleshevskiy** [comment]
I use x11.

- display manager: xdm
- window manager: xmonad

**Comment by ilya-fedin** [comment]
Does `gio open` opens in firefox, too?

**Comment by pleshevskiy** [comment]
I've tried. In librewolf. 

Also I opened gnome-control-center and librewolf is default here too
![image](https://user-images.githubusercontent.com/7839004/163805702-599d73d1-c47c-4562-83a0-dd21a7ce32ef.png)

**Comment by ilya-fedin** [comment]
Maybe you installed tdesktop via flatpak or snap? glib uses xdg-desktop-portal to open files/links in that case and portal's vision of defaults may be completely another

**Comment by ilya-fedin** [comment]
I think you can reproduce that with `GTK_USE_PORTAL=1 gio open`

**Comment by pleshevskiy** [comment]
```
➜  ~ which xdg-desktop-portal
xdg-desktop-portal not found
```

`GTK_USE_PORTAL=1 gio open https://google.com` opens in Librewolf

**Comment by pleshevskiy** [comment]
Yes, I installed tdesktop using snap

**Comment by ilya-fedin** [comment]
> ➜  ~ which xdg-desktop-portal

You won't find it in $PATH lol

> Yes, I installed tdesktop using snap

That's the cause apparently

**Comment by ilya-fedin** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> `GTK_USE_PORTAL=1 gio open https://google.com` opens in Librewolf

I dunno then, some snap magic apparently.

**Comment by pleshevskiy** [comment]
ok. I'll reinstall tdesktop and let you know if it works for me. :) thank you

**Comment by pleshevskiy** [comment]
Yesterday I compiled from [source](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md) and installed compiled version from [release](https://github.com/telegramdesktop/tdesktop/releases/tag/v3.7.0).

it doesn't seem to be about snap

**Comment by ilya-fedin** [comment]
Maybe you start tdesktop from different environment than terminal? E.g. firejail/buublewrap/any other cointainer technologies or your DE pass other environment to Telegram when you launch it from menu/file manager rather than terminal.
