### ISSUE TITLE
Broken media viewer if ANGLE graphics backend is set to D3D11on12

### ISSUE THREAD

**Issue by PlastMan420** [telegramdesktop/tdesktop#24180]
### Steps to reproduce

1. Set ANGLE graphics backend to D3D11on12.
2. Try opening media, picture or video.
3. media viewer will not appear. there's overlay and it will capture click. but you can't see it. overlay will appear as a separate telegram window and you can close it, but it does not show anything.

### Expected behaviour

Media overlay should appear.

### Actual behaviour

media overlay window is created and it "covers" the telegram desktop app, but you can neither see nor interact with it.

### Operating system

Windows 11 22000.556

### Version of Telegram Desktop

3.6 X64

### Installation source

Microsoft Store

**Comment by j2h4u** [comment]
Still exists in 4.2.4 x64
