### ISSUE TITLE
Build failure under Fedora

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#2418]
### Steps to reproduce
1. Build static Qt-5.6.0 and required libs (including qtimageformats).
2. Build telegram-desktop 0.10.1 from sources with static Qt 5.6.0.

### Actual behaviour
Got build error:
```
/home/builder/tgx/prep/ccz5f9hM.ltrans4.ltrans.o: In function `StaticQWebpPluginPluginInstance::StaticQWebpPluginPluginInstance()':
/home/builder/tgx/tdesktop/Linux/ReleaseIntermediate/../../Telegram/SourceFiles/stdafx.cpp:44: undefined reference to `qt_static_plugin_QWebpPlugin()'`
```

### Configuration
**Operating system: Fedora 24**
**Version of Telegram Desktop: 0.10.1**

**Comment by auchri** [comment]
See #916

**Comment by stek29** [comment]
Are you sure you've build qwebp? Is libwebp installed?
Do you get any warnings from linker (about not finding some libs)?

**Comment by xvitaly** [comment]
> Are you sure you've build qwebp?

Yes:
```libqdds.a
libqdds.prl
libqicns.a
libqicns.prl
libqtga.a
libqtga.prl
libqtiff.a
libqtiff.prl
libqwbmp.a
libqwbmp.prl
libqwebp.a
libqwebp.prl
```

> Is libwebp installed?

Yes.

>  Do you get any warnings from linker (about not finding some libs)?

No. Only one error.

**Comment by xvitaly** [comment]
Problem solved.

**Comment by auchri** [comment]
how?

**Comment by xvitaly** [comment]
> how?

Executed make install for qtbase, qtimageformats and then fixed all paths to /usr/local/Qt-5.6.0.

**Comment by stek29** [comment]
@xvitaly so you installed it to `/usr/local` and not `/usr/local/tdesktop`?

**Comment by xvitaly** [comment]
> so you installed it to /usr/local and not /usr/local/tdesktop?

Installed only Qt-5.6.0 (with qtimageformats) and all required libs (libav, ffmpeg, etc.). Then build as usual.
