### ISSUE TITLE
No video preview for Odysee links

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#24183]
### Steps to reproduce

paste any Odysee video link in any Telegram channel/conversation.

### Expected behaviour

show a preview window/screen shot, like any YouTube link.

### Actual behaviour

No preview Window..

i contacted Odysee repo,
and they claim it´s a Telegram BUG...
https://github.com/OdyseeTeam/odysee-frontend/issues/1084

### Operating system

Windows8.1

### Version of Telegram Desktop

latest

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Can't reproduce, do you have an example link?

**Comment by juanpc2018** [comment]
https://odysee.com/@dirtyworkz:0/unsenses-glow-(official-video):6

**Comment by Aokromes** [comment]
if you mean, no video preview, it's the same on android, so it's server side bug.

**Comment by 23rd** [comment]
https://bugs.telegram.org
