### ISSUE TITLE
[Feature Request]  Is it possible to insert the photo button, taking a photo using the webcam?

### ISSUE THREAD

**Issue by AgostinoA** [telegramdesktop/tdesktop#24182]
### Is your feature request related to a problem?

You can use it on your smartphone, because not even on a Linux pc. Having a tablet with Linux, this feature seems to me to be actually absent

### Describe the solution you'd like

The solution is to integrate the photo loot function, like the one on mobile, using the webcam of the pc / tablet (linux / windows).

### Describe alternatives you've considered

Alternative is to take the photo from a separate program and attach it as a file. But the solution seems to me to be quite slow

**Comment by ilya-fedin** [comment]
#781
