### ISSUE TITLE
Cropped Image on a big monitor in fullscreen

### ISSUE THREAD

**Issue by eltsovaad** [telegramdesktop/tdesktop#24195]
### Steps to reproduce

1. You need to have a smaller and bigger monitors.
2. Make a smaller one main in windows settings
3. Launch Telegram, it will open on a smaller monitor
4. Drag and drop the window on a bigger monitor
5. Open any image in a message

### Expected behaviour

![image](https://user-images.githubusercontent.com/46975666/158416414-f4717a0d-e8e1-4830-aaff-fd22d3301b5d.png)
Image is not cropped

### Actual behaviour

![image](https://user-images.githubusercontent.com/46975666/158416173-ab1433e0-be15-494e-89d2-d6442954f1a4.png)
Image is cropped

### Operating system

Windows 10

### Version of Telegram Desktop

3.6

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I just tried to reproduce in a VM, but it opens fullscreen

**Comment by eltsovaad** [comment]
> I just tried to reproduce in a VM, but it opens fullscreen

Ok, it's more complicated to repeat. 
1. You need to have a smaller and bigger monitors.
2. Make a smaller one main in windows settings _(close settings window, it may be important)_
3. **Important** _On a big monitor open Start Menu of Windows, type Telegram,_ Launch Telegram Desktop. Make sure it was opened on a smaller monitor
4. Drag and drop the window on a bigger monitor, _do not open images_
5. Open any image in a message

Actually, I couldn't understand how to make an app 100% open on a smaller monitor, but it is the main case. I use this display parameters for a small monitor 
![image](https://user-images.githubusercontent.com/46975666/158458274-b4e32a12-e907-4129-ad4d-607e12dcd775.png)
and this for a bigger one
![image](https://user-images.githubusercontent.com/46975666/158458368-0bb08270-b848-41b0-9d71-00448761be12.png)
Hope you don't mind Cyrillic

**Comment by ilya-fedin** [comment]
> 3\. **Important** _On a big monitor open Start Menu of Windows, type Telegram,_ Launch Telegram Desktop. Make sure it was opened on a smaller monitor

It it really important? Does statrting the exe directly makes the issue disappear?

**Comment by eltsovaad** [comment]
> > 3. **Important** _On a big monitor open Start Menu of Windows, type Telegram,_ Launch Telegram Desktop. Make sure it was opened on a smaller monitor
> 
> It it really important? Does statrting the exe directly makes the issue disappear?

I'll try, but when open start on a small monitor, it works fine

**Comment by ilya-fedin** [comment]
I have bad news: logs report that the media viewer window is being resized to the right screen resolution, so something happens under the hood of Qt and it doesn't render the window right. At this point this is non-trivial and someone has to dig into Qt in order to fix this.

**Comment by ilya-fedin** [comment]
If this happens not only with Qt applications, this might be a Windows bug actually. There was a long-standing bug in Windows 10 when it screwed restoration of window size on applications launching adding or removing multiple pixels.

**Comment by aamadorj** [comment]
I'm seeing the same issue, just as described at the OP. My computer OS is Windows 10.

**Comment by Ragnar-II** [comment]
Windows 11, the same problem. Setting the graphical engine to DirectX 11 helped. However, didn't test it after reboot, maybe it won't remember the setting.

**Comment by aamadorj** [comment]
> Windows 11, the same problem. Setting the graphical engine to DirectX 11 helped. However, didn't test it after reboot, maybe it won't remember the setting.

Changing the ANGLE Graphics Backend to DirectX 11 fix the issue in my case and it seems the configuration change sticks even after closing Telegram. Thanks, @Ragnar-II.

**Comment by Mirmidon** [comment]
> Windows 11, the same problem. Setting the graphical engine to DirectX 11 helped. However, didn't test it after reboot, maybe it won't remember the setting.

Windows 10, changing graphical engine to dx11 didn't worked for me, but changing it to OpenGL did. Now everything showing fine.

**Comment by AlexRU18** [comment]
Any solutions for Windows 10 not works, but i "fix" this by:
Right click on Desktop -> display settings -> click to second screen and set as default. Then click to primary screen and set as 
default back. Restart Telegram and it's works.

**Comment by ilya-fedin** [comment]
Is this issue still present on tdesktop 3.7?

**Comment by anton-ryzhov** [comment]
Was something changed recently?
Seems like another sizing issue popped up after last update — "media viewer" isn't showed on fullscreen mode, so everything is shifted/cropped by height of top bar and window title. Could it be related?

**Comment by ilya-fedin** [comment]
@anton-ryzhov it opens in fullscreen for me

**Comment by anton-ryzhov** [comment]
I've checked now on another machine. On ubuntu 20.04 works fine but on 16.04 it doesn't. I assume latter isn't supported, not a big problem then

**Comment by ilya-fedin** [comment]
Apparently Qt starts removing workarounds for Unity, it was a very buggy DE. It's really the time to stop using it.
