### ISSUE TITLE
Drag-and-drop contacts

### ISSUE THREAD

**Issue by VitaliyAT** [telegramdesktop/tdesktop#24191]
### Is your feature request related to a problem?

Problem is that it's not useful add contacts to Folders, Groups and other contacts.
Проблема в том, что добавление контактов в Папки, Группы и пересылка контактов другим контактам организованна неудобно. Много кликов мышкой и вообще надо куда-то заходить и что-то натыкивать и искать.

### Describe the solution you'd like

I'd like have ability drag-and-drop them in interface. Drag it to Folder - mean add this contact to this Folder. Drag it to Group - mean add contact in group. Drag contact to contact - mean send info about contact to contact.
Мне бы хотелось иметь возможность перетаскивать контакты драг-энд-дропом. Кинул на папку - контакт прикрепился к папке, кинул в группу - контакт был в неё приглашён. Кинул контакту - поделился контактом. Разумеется это всё для Десктоп версии программы.

### Describe alternatives you've considered

Нone or pain in the neck ways by lot of clicks and typing.
Альтернативы предлагаемому сейчас нет, либо как говорил выше геморрой с накликиванием мышкой и печатаньем на клавиатуре (когда ищешь контакт в списке)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7463
