### ISSUE TITLE
Crash when MPRIS media position append request

### ISSUE THREAD

**Issue by alihardan** [telegramdesktop/tdesktop#24194]
### Steps to reproduce

1. Run Telegram Desktop and play a audio in it.
2. execute `playerctl position 5+` in Terminal.
3. tdesktop crashes.

### Expected behaviour

Forward audio position 5 seconds.

### Actual behaviour

Closes with following error:

```
(Telegram:5576): glibmm-ERROR **: 17:43:36.092:
unhandled exception (type std::exception) in signal handler:
what: VariantContainerBase::get(): Index out of bounds.

Trace/breakpoint trap (core dumped)
``` 

### Operating system

Arch Linux, Up-to-Date (2022-03-15), dwm

### Version of Telegram Desktop

3.6.0

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.
