### ISSUE TITLE
[Question] The view count is growing in a private channel having only one subscriber. Why!

### ISSUE THREAD

**Issue by offstate** [telegramdesktop/tdesktop#24202]
The view count in each post in my private channels grows randomly as they age

![изображение](https://user-images.githubusercontent.com/16996529/158519705-0fa003ea-7424-4036-807b-74e82cd26e2e.png)
Telegram Desktop 3.6 
Linux KDE Neon 5.24

**Comment by 23rd** [comment]
#10350.
