### ISSUE TITLE
Spoiller placeholders sizing in reply preview

### ISSUE THREAD

**Issue by BANOnotIT** [telegramdesktop/tdesktop#24206]
![изображение](https://user-images.githubusercontent.com/11363215/158908277-73edea88-4b0d-4438-852f-93fba0a0b0e6.png)
This error can be found in [this message](https://t.me/c/1319942247/22506).

Telegram 3.6.1
Ubuntu 18.04

**Comment by BANOnotIT** [comment]
Still have this bug in Telegram 3.7.4 beta
Also copy [reproduced the bug in public channel](https://t.me/tg_msg_bugs/3) to be easily accessible

**Comment by BANOnotIT** [comment]
The bug is still not solved

**Comment by john-preston** [comment]
Can you show a screenshot from version 4.3?

**Comment by ilya-fedin** [comment]
@john-preston I can reproduce using his link from the first comment
![изображение](https://user-images.githubusercontent.com/17829319/200322304-273958f5-c115-4d79-9124-02abd900ecd9.png)
