### ISSUE TITLE
Full screen image/video view makes frozen flatpak version 

### ISSUE THREAD

**Issue by dziaineka** [telegramdesktop/tdesktop#24204]
### Steps to reproduce

1. Click on any photo or video to watch it

### Expected behaviour

Telegram show image/video

### Actual behaviour

Telegram freezes

[Video on Youtube](https://youtu.be/6TTEfaB0510)

### Operating system

Fedora Linux 35

### Version of Telegram Desktop

3.6

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Downgrade pipewire, 0.3.48 is bugged
