### ISSUE TITLE
Install path and data path. (* again )

### ISSUE THREAD

**Issue by thctlo** [telegramdesktop/tdesktop#24203]
Please provide the option to .. 

1) select the program location
2) select the user data location. 

Im using Telegram in a network and it sucks big time as it is now. 
All my "ROAMING" data of telegram is slowing my login SOOOO much.. 
and logical since it copies OVER 3 GB of CACHE in profiles.. 
*( yes i know i can set limitations, and these are set for me.) 

We have such nice variables, why dont we use them. 
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files

LOCALAPPDATA=C:\Users\UserName\AppData\Local
ALLUSERSPROFILE=C:\ProgramData
APPDATA=\\servername.internal.dom.tld\users\USERNAME\AppData\Roaming

1) An all users install ( telegram program ) should go to 
  a) No UAC (Ease upgrades) : $ProgramData\TelegramProgramHere
  b) UAC control : $ProgramFiles 
2) User data : 
  a) a one user setup :  $ALLUSERSPROFILE\Telegram\tdata
  b) Per user Data : $LOCALAPPDATA
  c) Ask for network compilance, add note about big user profiles and longer logings.  : $APPDATA

See also close bug #2355

**Comment by ilya-fedin** [comment]
> 1\. select the program location

You already have possibility to change install location in the installer

> 2\. select the user data location.

If you install tdesktop in a directory where it has write access, it should write the data to this directory

**Comment by thctlo** [comment]
Thanks for the reply, i'll test this again on a new clean pc. (* still on old installation.) 
I'll close this ticket.
