### ISSUE TITLE
Whole X freezes on media click

### ISSUE THREAD

**Issue by ShyLionTjmn** [telegramdesktop/tdesktop#24211]
### Steps to reproduce

Linux Mint 19.3
After some time running, when i click video or photo on telegram channel - whole system freezed.
Only thing i can do is to switch to console CTRL-ALT-F1 (any of F1-F6) and login to console.
Killing Telegam does not resolve problem, after switching back to X using ALT-F7 only black screen an cursor present.
This started right after latest Telegram update 3.6.1

### Expected behaviour

Should not freeze

### Actual behaviour

X system freezes

### Operating system

Linux Mint 19.3, Cinnamon, latest updates

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Maybe it was a system update that added a bug to X? :thinking:

**Comment by ShyLionTjmn** [comment]
Maybe, but it happens when i click in Telegram app. All other apps function just fine.
Anything i can do to collect logs from Telegram?

**Comment by ilya-fedin** [comment]
I don't imagine how an application can freeze entire X so that it doesn't recover after a kill attempt. The reason you don't see this in other applications might be just the fact you don't use much applications (i.e. Telegram is frequently the only Qt application on user's PC)

**Comment by ShyLionTjmn** [comment]
Cant argue much, just the fact that i'm facing problem with Telegram app. The other concedence is that happend when chrome was playing youtube.
Any ideas where to look at when this happens?

**Comment by ilya-fedin** [comment]
I have only one display. Can you reproduce with one display?

**Comment by ShyLionTjmn** [comment]
Just few seconds after i posted my last message, i tried again and viola - it freezed

**Comment by ilya-fedin** [comment]
It might be related to your graphics drivers since media viewer uses OpenGL

**Comment by ShyLionTjmn** [comment]
This is what was in syslog at the moment of freeze
`Mar 18 21:02:22 lion-home-pc acpid: client 1400[0:0] has disconnected
Mar 18 21:02:27 lion-home-pc gnome-terminal-[9656]: gdk_event_set_source_device: assertion 'GDK_IS_DEVICE (device)' failed
Mar 18 21:02:27 lion-home-pc kernel: [22475.937056] show_signal_msg: 41 callbacks suppressed
Mar 18 21:02:27 lion-home-pc kernel: [22475.937058] gnome-terminal-[9656]: segfault at 90 ip 00007f444f2eb285 sp 00007ffe0f831eb0 error 4 in libgdk-3.so.0.2200.30[7f444f28d000+eb000]
Mar 18 21:02:27 lion-home-pc kernel: [22475.937062] Code: 48 8b 7d 30 e8 5c c6 fc ff 4c 89 e7 48 89 c6 48 89 c5 e8 2e a8 fd ff 4c 89 ef e8 76 32 fd ff 4c 89 e7 48 89 c6 e8 db b3 fd ff <48> 8b b5 90 00 00 00 4c 89 e7 e8 5c b4 fd ff 49 8b 74 24 08 49 8b
Mar 18 21:02:27 lion-home-pc systemd[1924]: gnome-terminal-server.service: Main process exited, code=dumped, status=11/SEGV
Mar 18 21:02:27 lion-home-pc systemd[1924]: gnome-terminal-server.service: Failed with result 'core-dump'.
Mar 18 21:02:27 lion-home-pc systemd-coredump[31933]: Process 9656 (gnome-terminal-) of user 1000 dumped core.#012#012Stack trace of thread 9656:#012#0  0x00007f444f2eb285 n/a (libgdk-3.so.0)#012#1  0x00007f444f2f5810 n/a (libgdk-3.so.0)#012#2  0x00007f444f2f53e1 n/a (libgdk-3.so.0)#012#3  0x00007f444f2bfd70 gdk_display_get_event (libgdk-3.so.0)#012#4  0x00007f444f2f4f82 n/a (libgdk-3.so.0)#012#5  0x00007f444e031537 g_main_context_dispatch (libglib-2.0.so.0)#012#6  0x00007f444e031770 n/a (libglib-2.0.so.0)#012#7  0x00007f444e0317fc g_main_context_iteration (libglib-2.0.so.0)#012#8  0x00007f444e5f2f3d g_application_run (libgio-2.0.so.0)#012#9  0x000055ef7d84e162 n/a (gnome-terminal-server)#012#10 0x00007f444d7efc87 __libc_start_main (libc.so.6)#012#11 0x000055ef7d84e20a n/a (gnome-terminal-server)#012#012Stack trace of thread 9657:#012#0  0x00007f444d8e2bb9 __GI___poll (libc.so.6)#012#1  0x00007f444e0316e9 n/a (libglib-2.0.so.0)#012#2  0x00007f444e0317fc g_main_context_iteration (libglib-2.0.so.0)#012#3  0x00007f444e031841 n/a (libglib-2.0.so.0)#012#4  0x00007f444e0592a5 n/a (libglib-2.0.so.0)#012#5  0x00007f444dbc66db start_thread (libpthread.so.0)#012#6  0x00007f444d8ef61f __clone (libc.so.6)#012#012Stack trace of thread 9658:#012#0  0x00007f444d8e2bb9 __GI___poll (libc.so.6)#012#1  0x00007f444e0316e9 n/a (libglib-2.0.so.0)#012#2  0x00007f444e031a82 g_main_loop_run (libglib-2.0.so.0)#012#3  0x00007f444e61f2d6 n/a (libgio-2.0.so.0)#012#4  0x00007f444e0592a5 n/a (libglib-2.0.so.0)#012#5  0x00007f444dbc66db start_thread (libpthread.so.0)#012#6  0x00007f444d8ef61f __clone (libc.so.6)#012#012Stack trace of thread 9659:#012#0  0x00007f444d8e2bb9 __GI___poll (libc.so.6)#012#1  0x00007f444e0316e9 n/a (libglib-2.0.so.0)#012#2  0x00007f444e0317fc g_main_context_iteration (libglib-2.0.so.0)#012#3  0x00007f4442c4236d n/a (libdconfsettings.so)#012#4  0x00007f444e0592a5 n/a (libglib-2.0.so.0)#012#5  0x00007f444dbc66db start_thread (libpthread.so.0)#012#6  0x00007f444d8ef61f __clone (libc.so.6)
`

**Comment by ShyLionTjmn** [comment]
Video driver version is the same as week ago. 470.103.01

**Comment by ilya-fedin** [comment]
Use three ` for code tag

**Comment by ilya-fedin** [comment]
> This is what was in syslog at the moment of freeze

It has only gnome-terminal crash lines

**Comment by ilya-fedin** [comment]
> Video driver version is the same as week ago. 470.103.01

Well, proprietary NVIDIA driver is very problematic with Qt apps, it loses context frequently and causes random crashes

**Comment by data-man** [comment]
> click video or photo on telegram channel - whole system freezed
> Well, proprietary NVIDIA driver is very problematic with Qt apps

I've never had this problem.
But I'm using Telegram on Devuan/KDE Plasma.

**Comment by ShyLionTjmn** [comment]
Can i revert back to previous version of Tg to see if problem repeats?

**Comment by ilya-fedin** [comment]
> I've never had this problem.

Well, it's actually blacklisted, but if you would disable the blacklist, you will have a lot of funny bugs I guess

> Can i revert back to previous version of Tg to see if problem repeats?

Sure, but that will log you out

**Comment by ShyLionTjmn** [comment]
Is there a way to prevent it showing Update Telegram button?

**Comment by data-man** [comment]
> Well, it's actually blacklisted

If you mean `modprobe.d/blacklist.conf`, I don't have it.

**Comment by ilya-fedin** [comment]
> If you mean `modprobe.d/blacklist.conf`, I don't have it.

I mean Telegram has a blacklist and it won't use hardware acceleration with proprietary NVIDIA driver

**Comment by ilya-fedin** [comment]
> Is there a way to prevent it showing Update Telegram button?

Disable autoupdate in settings

**Comment by ShyLionTjmn** [comment]
No freezes on 3.6.0 yet
