### ISSUE TITLE
Image viewer has incorrect height when on second monitor that is in different orientation from the primary (cutting image off in half)

### ISSUE THREAD

**Issue by ShizCalev** [telegramdesktop/tdesktop#24218]
`Temporary workaround for folks who want to skim: settings -> advanced -> set ANGLE backend to OpenGL or disabled.`

### Steps to reproduce

1) Have two monitors
2) Monitor 1 (primary) set to landscape orientation, monitor 2 set to portrait. 
3) Open the image viewer on monitor 2.

### Expected behaviour

Image viewer should fill the screen.

### Actual behaviour

(Mon 1 is 1920x1080, Mon 2 is 1080x1920)
Image viewer opens with it's resolution set to the height of the primary monitor (1080) instead of the full height of the secondary monitor (1920). Since it is more or less centered in my case, half the image is cut off. The image viewer cannot be resized.

(Mon 2)
![image](https://user-images.githubusercontent.com/6209658/159143400-4ef93fc9-0538-4b57-a9c4-d29fb8ee0518.png)

(Mon 1)
![image](https://user-images.githubusercontent.com/6209658/159143438-4823a2b8-338a-434f-a34a-7e6eea625a04.png)

### Operating system

Windows 10 Pro x64 | build 19044.1586 (latest)

### Version of Telegram Desktop

3.6.1 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> * Have two monitors
> 
> * Monitor 1 (primary) set to landscape orientation, monitor 2 set to portrait.
> 
> * Open the image viewer on monitor 2.

Are you sure it's that simple? There's a similar issue with more complicated reproduce steps: https://github.com/telegramdesktop/tdesktop/issues/24195#issuecomment-1068395205. Maybe you have the same issue?

**Comment by ShizCalev** [comment]
Their reproduction steps are a little convoluted, but it does seem to be the same issue at heart:

Primary monitor is larger than second monitor
Have telegram on second monitor
Open image viewer
Image viewer opens with the size of the primary monitor instead of the secondary.

**Comment by ilya-fedin** [comment]
The thing is that #24195 doesn't happen if another monitor is just bigger. It only happens if monitors have different scale and Telegram is launched with defined steps (it won't reproduce if you just run Telegram and won't move it between monitors)

**Comment by ShizCalev** [comment]
To note, the issue does seem to go away when ANGLE graphics backend is set to Open GL & Disabled. (All the d3d modes present the issue)

**Comment by ilya-fedin** [comment]
So, do you confirm it's the same as #24195 or is it different (e.g. it reproduces even when Telegram started on that second monitor and you don't move the window between displays)?

**Comment by ShizCalev** [comment]
My scales are all the same (100%) It occurs regardless of if it's launched during startup, or opened directly. It's started on the secondary monitor and is not moved.

**Comment by ilya-fedin** [comment]
You have a different issue then, apparently

**Comment by warlord29a** [comment]
I have this issue too.

In the previous version, the media viewer works perfectly, but in 3. 6.1, open only a half of photos.

I have 3 monitors, and I have the same problem in all of them.

**Comment by ilya-fedin** [comment]
in 3.6.0 or 3.6.1?

**Comment by ShizCalev** [comment]
It worked correctly in 3.6.0 for me.

**Comment by ilya-fedin** [comment]
Can you enable debug logs with the `debugmode` cheat code, reproduce it, find all the lines with `Viewer Pos` and post them here?

**Comment by ShizCalev** [comment]
[16:00:48.693 00-0005013] Viewer Pos: Shown, screen number: 2 (media_view_overlay_widget.cpp : 25)

**Comment by ilya-fedin** [comment]
It couldn't be the only such line

**Comment by ShizCalev** [comment]
Line 601: [16:32:57.351 00-0000523] Viewer Pos: Moved to 2140, 720 (media_view_overlay_widget.cpp : 25)
	Line 602: [16:32:57.352 00-0000524] Viewer Pos: Setting 0, 0, 1920, 1081 (media_view_overlay_widget.cpp : 25)
	Line 603: [16:32:57.354 00-0000525] Viewer Pos: Resized to 1080, 1920 (media_view_overlay_widget.cpp : 25)
	Line 606: [16:32:57.381 00-0000528] Viewer Pos: Moved to 1920, 0 (media_view_overlay_widget.cpp : 25)
	Line 5588: [16:33:28.238 00-0006099] Viewer Pos: Moved to 1920, 0 (media_view_overlay_widget.cpp : 25)
	Line 5589: [16:33:28.238 00-0006100] Viewer Pos: Resized to 1080, 1920 (media_view_overlay_widget.cpp : 25)
	Line 5590: [16:33:28.245 00-0006101] Viewer Pos: Shown, screen number: 2 (media_view_overlay_widget.cpp : 25)
	Line 7056: [16:34:55.662 00-0007757] Viewer Pos: Shown, screen number: 2 (media_view_overlay_widget.cpp : 25)

**Comment by ilya-fedin** [comment]
And there's no 'Setting' after 'Shown' lines?

**Comment by ShizCalev** [comment]
From viewer pos? If so, no, that is all.

**Comment by ilya-fedin** [comment]
It's weird, then. It says it's moved to 1920, 0 and resized to 1080, 1920. But the code checks after show that it's 1920, 0, 1080, 1921 and if it's not, it should set it. I don't see how it can not to set in such case.

**Comment by ilya-fedin** [comment]
I believe you missed some lines

**Comment by ieatrainbow** [comment]
I had the same problem, fixed it by disabling "ANGLE graphics bakend" in SETTINGS -> Advanced (was in "AUTO")

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/159376451-1de1c618-5c66-460a-8289-762442023a26.png)
No missing lines unless you're looking for something that doesn't start with `Viewer Pos`.

**Comment by ilya-fedin** [comment]
Looks like we need some additional logging

**Comment by iBreadInside** [comment]
Hello! I have similar issue: 2 monitors, same orientation, different resolutions (1080 and 2k). MV shows media perfectly with lower resolution monitor, but cut it on 2k.
![image](https://user-images.githubusercontent.com/66948071/160241896-cb6fb413-d612-4e6d-b824-9bf3e08467b7.png)

**Comment by preyasprathap** [comment]
I have this issue but with video too.

after setting ANGLE to openGL the issues seems to go away
but both the monitors flicks when I click the close button to close the video/photo.(when clicked on primary monitor)

and my primary monitor is bigger than secondary.
maybe because I have AMD GFX card

**Comment by ilya-fedin** [comment]
@ShizCalev can you get the logs in the same way on 3.6.3 beta?

**Comment by ilya-fedin** [comment]
Is this issue still present on tdesktop 3.7?

**Comment by ShizCalev** [comment]
My environment changed (different primary monitor, now a 2560x1440.)

Have yet to replicate it on 3.6.1. Will play around with it for a few more days with 3.7 and see if I can get it to trigger.

**Comment by Sp0i3eR** [comment]
Similar issue on linux, since 3.6.3, still present in 3.7 (no workaround though) with two monitor configuration (on screenshot). Media viewer think that screen is  horizontal:
![image](https://user-images.githubusercontent.com/972159/163713346-2bef2054-edfe-4bd2-8a8c-7ff4ae5ebe7e.png)![image](https://user-images.githubusercontent.com/972159/163713637-5d513abc-a4cb-4706-bf2c-a0939e3d0d09.png)
This also affects right click menu, right click not working below 1080's pixel on second monitor

**Comment by ilya-fedin** [comment]
@Sp0i3eR do this
https://github.com/telegramdesktop/tdesktop/issues/24218#issuecomment-1073313513

**Comment by Sp0i3eR** [comment]
Here you go
```
[16:45:27.294 00-0000567] Viewer Pos: Setting 0, 480, 2560, 1080 (media_view_overlay_widget.cpp : 25)
[16:45:52.861 00-0000544] Viewer Pos: Setting 0, 480, 2560, 1080 (media_view_overlay_widget.cpp : 25)
[16:46:03.578 00-0000544] Viewer Pos: Setting 0, 480, 2560, 1080 (media_view_overlay_widget.cpp : 25)
[16:47:08.872 00-0017433] Viewer Pos: Currently on screen 0, moving to screen 1 (media_view_overlay_widget.cpp : 25)
[16:47:08.872 00-0017434] Viewer Pos: New actual screen: 1 (media_view_overlay_widget.cpp : 25)
[16:47:08.872 00-0017435] Viewer Pos: Setting 2560, 0, 1920, 1080 (media_view_overlay_widget.cpp : 25)
[16:47:08.873 00-0017436] Viewer Pos: Moved to 2560, 0 (media_view_overlay_widget.cpp : 25)
[16:47:08.873 00-0017437] Viewer Pos: Resized to 1920, 1080 (media_view_overlay_widget.cpp : 25)
[16:47:08.874 00-0017438] Viewer Pos: Shown, geometry: 2560, 0, 1920, 1080, screen number: 1 (media_view_overlay_widget.cpp : 25)
[16:47:08.889 00-0017450] Viewer Pos: Resized to 1920, 1080 (media_view_overlay_widget.cpp : 25)
[16:47:10.246 00-0017519] Viewer Pos: Setting 2560, 0, 1920, 1080 (media_view_overlay_widget.cpp : 25)
[16:47:10.247 00-0017520] Viewer Pos: Resized to 1920, 1080 (media_view_overlay_widget.cpp : 25)
[16:47:10.247 00-0017521] Viewer Pos: Shown, geometry: 2560, 0, 1920, 1080, screen number: 1 (media_view_overlay_widget.cpp : 25)
[16:47:10.272 00-0017533] Viewer Pos: Resized to 1920, 1920 (media_view_overlay_widget.cpp : 25)
[16:47:14.902 00-0017603] Viewer Pos: Setting 2560, 0, 1920, 1080 (media_view_overlay_widget.cpp : 25)
[16:47:14.903 00-0017604] Viewer Pos: Resized to 1920, 1080 (media_view_overlay_widget.cpp : 25)
[16:47:14.903 00-0017605] Viewer Pos: Shown, geometry: 2560, 0, 1920, 1080, screen number: 1 (media_view_overlay_widget.cpp : 25)
```

**Comment by ilya-fedin** [comment]
Looks like either Xorg or Qt report that your screen has horizontal orientation

**Comment by ilya-fedin** [comment]
3.6.3 has updated Qt to 6.3.0, so apparently yet another Qt regression

**Comment by cristian-tamblay** [comment]
> Is this issue still present on tdesktop 3.7?

Yes it's still present.
tdesktop 3.7 removed the disable "ANGLE graphics backend" in Settings so we have no workaround this time.

**Comment by ilya-fedin** [comment]
@cristian-tamblay no, it's still here

**Comment by cristian-tamblay** [comment]
> @cristian-tamblay no, it's still here

Oh yeah my bad, the first time I did the workaround I was on windows and it still works there.

On linux the option ANGLE graphics backend is worded differently

![opengl](https://user-images.githubusercontent.com/30818944/163859295-f153351a-3b98-4261-831c-3ccb017be902.png)

I've tried enabling and disabling that option but with no avail.

**Comment by ilya-fedin** [comment]
> Oh yeah my bad, the first time I did the workaround I was on windows and it still works there.

What if you revert ANGLE to the default on Windows?

**Comment by cristian-tamblay** [comment]
> > Oh yeah my bad, the first time I did the workaround I was on windows and it still works there.
> 
> What if you revert ANGLE to the default on Windows?

Can confirm that its working on windows with the "Auto" option in ANGLE graphics backend

**Comment by ilya-fedin** [comment]
So initial issue is fixed, nice

**Comment by ilya-fedin** [comment]
Is this issue still present on tdesktop 3.7.1?
