### ISSUE TITLE
Tag listing should not include posts with no instance of the tag.

### ISSUE THREAD

**Issue by ThomasLeigh** [telegramdesktop/tdesktop#24213]
### Steps to reproduce

Suppose we have three posts:

1. First post has the “#cat” tag.
2. Second post has no tags - **but it has the link to the first or the third post**.
3. Third post has the “#cat” tag.

### Expected behaviour

If You click on the “#cat” tag or perform the search for it - only two posts should show up.

### Actual behaviour

If You click on the “#cat” tag or perform the search for it - You’ll end up with three posts, **although one of them is not cat-tagged**.

This highly disturbs the clarity and usability of tagging and organizing content within channels or groups via tags. Could You please fix that?

### Operating system

Windows 7 32-bit

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment]
I believe this is intended since it has always worked like that: search is also done on web preview's content

By the way, search is done on the cloud: Telegram apps like tdesktop only list the search results returned by the server. I suggest to bring this to https://suggestions.telegram.org
