### ISSUE TITLE
Can't write backticks with italian keyboard layout since QT 6.2.3

### ISSUE THREAD

**Issue by chrooti** [telegramdesktop/tdesktop#24210]
### Steps to reproduce

1. Download the prebuilt telegram app
2. Set the keyboard layout to italian (```setxkbmap -layout it```)
2. Launch it
3. Press alt gr + '
4. ' appears and not `

Note:
The bug appears since the 6.2.3 version of QT, I've tried both the prebuilt app and the dynamically linked Arch version (with both 6.2.3 and 6.2.2) and only the 6.2.3 versions exhibit the problem.
Further investigation shows that the other characters requiring alt gr are also broken (e.g. @)

### Expected behaviour

The backtick should appear

### Actual behaviour

A single quote appears.

### Operating system

Arch Linux

### Version of Telegram Desktop

3.4.2 onwards (since the qt6 switch)

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
And what do you want in tdesktop bugtracker if you diagnosed that the bug in Qt?

**Comment by chrooti** [comment]
I'm not sure whether the bug is in QT or in Telegram usage of QT and I'm not sure what to check.
Doesn't matter, thanks for the answer anyway.
