### ISSUE TITLE
🧑‍🤝‍🧑 Does not render properly

### ISSUE THREAD

**Issue by JuanPotato** [telegramdesktop/tdesktop#24217]
### Steps to reproduce

1. Send 🧑‍🤝‍🧑

### Expected behaviour

It should render as 🧑‍🤝‍🧑
![image](https://user-images.githubusercontent.com/9531780/159133679-d4a0eead-9a4c-4dff-ae36-aaed4277918b.png)
Taken from TAndroid

### Actual behaviour

It instead renders as 🧑🤝🧑
![image](https://user-images.githubusercontent.com/9531780/159133673-221c61fb-ba91-4162-b342-f2f04a784a68.png)
Taken from tdesktop

### Operating system

Windows 10

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
still bugged
