### ISSUE TITLE
Inline bots and ```blocks of code``` markdown

### ISSUE THREAD

**Issue by luc1ph3r** [telegramdesktop/tdesktop#2421]
### Steps to reproduce
1. Send to @bold (or any other inline bot supporting markdown) message like this:

\`\`\`word1 word2\`\`\`

2. Select **custom markdown** in @bold's options list

### Expected behaviour
@bold bot sends markdown-rendered message with all words appeared in input

### Actual behaviour
The first word of the message disappears in resulting answer. 

### Configuration
Operating system: **OS X**

Version of Telegram Desktop (Qt version): **0.10.1**

**Comment by auchri** [comment]
Seems to be an api issue, the same is happing on the android version. /cc @john-preston

**Comment by john-preston** [comment]
@auchri Or maybe a bot bug.

**Comment by luc1ph3r** [comment]
@john-preston what do you mean by saying "bot problem": only @ bold problem itself or a bug in the whole telegram bots platform? I just wanted to say that this dilemma happens with any inline bot supporting markdown input.

Btw, is there any place where people can submit API / platform issues?

**Comment by luc1ph3r** [comment]
Oh, I noticed an "api issue" label added by @auchri. My question isn't relevant anymore (:

**Comment by john-preston** [comment]
@luc1ph3r You mentioned "select custom markdown", so I thought it was a specific single bot problem. If none of the bots get the right text then it is a bot platform problem. If they do get correct text on some Telegram apps, but not on Telegram Desktop, then it is a Telegram Desktop problem and it can be discussed here :)

**Comment by auchri** [comment]
Happens on android too:

![screenshot_20160911-213047](https://cloud.githubusercontent.com/assets/5092164/18419949/5fe10510-7867-11e6-9e6e-19471262c08c.png)

**Comment by s3c** [comment]
I'm having the same problem, when using something like:

`*Title:* ``` a b c d ```\n'`

I only get:

**Title**: `b c d`
