### ISSUE TITLE
Unable to use accent marks and XCompose sequences

### ISSUE THREAD

**Issue by IvanRenison** [telegramdesktop/tdesktop#24228]
### Steps to reproduce

When I try to write a accented letter, like `à`, I press the \` key and then the `a` key, but only an `a` is inserted in the text. Also, when I tray to use a XCompose sequence, it does not function.

### Expected behaviour

The `à` should be inserted.

### Actual behaviour

An `a` is inserted.

### Operating system

Linux Mint 20.3 Cinnamon

### Version of Telegram Desktop

3.6.1

### Installation source
I have tried with `Flatpak` version and with `Linux static build for 64 bit`

**Comment by ilya-fedin** [comment]
#1041
