### ISSUE TITLE
Telegram on Wayland sends many messages to dbus if no notification daemon is found

### ISSUE THREAD

**Issue by simonedegiacomi** [telegramdesktop/tdesktop#24222]
### Steps to reproduce

1. Kill any notification daemon, for example `mako`
2. Start `dbus-monitor`
3. Start `telegram-desktop`

### Expected behaviour

I expect Telegram to either:
1. provide some error message that says that no FreeDesktop Notifications Specification implementation has been found, or
2. continue to run without trying to use the FreeDesktop Notifications Specification

### Actual behaviour

Telegram starts to send many messages to dbus, and this is visible from the terminal running `dbus-monitor`.

### Operating system

Sway on NixOs 21.09

### Version of Telegram Desktop

3.1.1

### Installation source

NixPkgs

### Related issues

Probably relate to issue #16236

**Comment by ilya-fedin** [comment]
Update to the latest versions, bugreports from old versions aren't accepted

**Comment by simonedegiacomi** [comment]
I updated to version `3.6.1`, but unfortunately I can confirm that the bug is still present, with the same behavior I specified before.

**Comment by ilya-fedin** [comment]
I can't reproduce on X11 and the only Wayland environment I have has notification daemon embedded in the compositor

**Comment by ilya-fedin** [comment]
I remembered about weston, but still, I can't reproduce. I don't see many dbus messages (maybe you consider less messages 'many' though?), tdesktop does exactly that:

> 2\. continue to run without trying to use the FreeDesktop Notifications Specification

**Comment by ilya-fedin** [comment]
I use bustle instead of dbus-monitor though as I can't parse its output and I just don't launch notification daemon instead of full removal, but I don't think it really matters.

**Comment by simonedegiacomi** [comment]
Thank you for suggesting `bustle`, I did not know about that tool! I can see "many" messages also in `bustle`.

You are are right that my "many messages" definition is not clear, so I will try to be more specific: by looking at a `bustle` capture, I see bursts of 1-5 messages every ~50ms. This causes telegram and dbus to load the CPU. Indeed, the reason why I noticed the issue in the first place was that my laptop would start spinning the fan with only telegram running.

I want to point out that, since I started running a notification daemon, the issue is completely resolved. The only thing is that it took me a couple of hours figuring it out, so an error/warning message would have been really appreciated :-)

I can try to isolate the issue and provide more steps to reproduce on a clean setup, but only later/in the next few days. Should I close this is issue and open it again if needed?

**Comment by ilya-fedin** [comment]
All I see on tdesktop start is 10-20 calls to xdg-desktop-portal and then no dbus messages. Well, you can save your dbus record with bustle or dbus-monitor --pcap, upllocad it on github and then I will inspect it myself in bustle.

**Comment by simonedegiacomi** [comment]
Sure, here are my recordings of dbus, both with and without notifications daemon running.
I had to rename both of them with `txt` extension, otherwise I was not able to attach them as issue comment.

[with notification daemon running.txt](https://github.com/telegramdesktop/tdesktop/files/8319464/with.notification.daemon.running.txt)
[without notification daemon.txt](https://github.com/telegramdesktop/tdesktop/files/8319466/without.notification.daemon.txt)

**Comment by ilya-fedin** [comment]
Bustle doesn't seem to display all the messages for some reason, so I opened the record with Wireshark and I see that d-bus daemon sends NameOwnerChanged before each iteration of tdesktop's dbus call, so this doesn't seem a tdesktop bug, something acquires and loses org.freedesktop.Notifications in a loop and tdesktop just reacts to that.

**Comment by simonedegiacomi** [comment]
Oh, I see. Then I have to do some more debugging on my system to find the root cause, or I guess soon I will encounter a similar issue with a different program.

Thank you for taking the time to follow the issue and inspecting the dumps :-)
