### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by askomaev** [telegramdesktop/tdesktop#24229]
Hello

I can’t find the ability to transfer dialogue lines in the current version of Telegram Desktop (version 3.6.1) on macOS Monterey 12.3. This is how it was before:
![photo_2022-03-16_17-47-03](https://user-images.githubusercontent.com/81448995/159345675-59e5f43f-5d53-44c0-87fd-720b83f62841.jpg) 
![photo_2022-03-16_17-49-22](https://user-images.githubusercontent.com/81448995/159345796-c7f5839a-a3fa-4a93-9ca4-fa6fa01517ae.jpg)
![photo_2022-03-16_17-49-17](https://user-images.githubusercontent.com/81448995/159345802-6530f5fc-d3d6-4dfd-94f6-f390b4d13203.jpg)

Now, unfortunately, I can not find these buttons and the ability to return the dialog to its previous form.
Do not tell me how this can be done?

**Comment by ilya-fedin** [comment]
The dialog should be wide enough for this option to be shown

**Comment by askomaev** [comment]
> The dialog should be wide enough for this option to be shown

How to do this on a MacBook Air M1 / macOS Monterey 12.3 / Telegram Desktop version 3.6.1? 
I do it on the whole Telegram screen, this function still does not appear.

**Comment by ilya-fedin** [comment]
> I do it on the whole Telegram screen, this function still does not appear.

1. Check that the chat list is not wide enough (it checks for the dialog widget to be wide enough, not entire window)
2. If you have scaling more than 100%, the window might never be wide enough

**Comment by askomaev** [comment]
> > I do it on the whole Telegram screen, this function still does not appear.
> 
> 1. Check that the chat list is not wide enough (it checks for the dialog widget to be wide enough, not entire window)
> 2. If you have scaling more than 100%, the window might never be wide enough

What do you mean by point 1? I don't quite understand.

**Comment by ilya-fedin** [comment]
You have chat list at left and dialog widget at right. You also may have enable third closable column with chat info or emojis.

**Comment by askomaev** [comment]
> You have chat list at left and dialog widget at right. You also may have enable third closable column with chat info or emojis.

![image](https://user-images.githubusercontent.com/81448995/159478595-11cd3de7-0532-4d0f-958f-35cc92a516d3.png)

**Comment by ilya-fedin** [comment]
Yeah, that's why you don't have the option. Close the third column and make chat list narrow.

**Comment by john-preston** [comment]
@askomaev Also you can try using 100% interface scale, the default is 110%. Maybe it'll allow the smallest third column / smallest chats list in this case.
