### ISSUE TITLE
[Feature Request] Scalable sound tempo without pitch change synced to playback speed

### ISSUE THREAD

**Issue by idMysteries** [telegramdesktop/tdesktop#24220]
### Is your feature request related to a problem?

Pitch changes as sound accelerates

### Describe the solution you'd like

Scalable sound tempo without pitch change. On the example of how it is [implemented in mpv](https://mpv.io/manual/master/#audio-filters-scaletempo[).
[Here is the mpv code](https://github.com/mpv-player/mpv/blob/6265724f3331e3dee8d9ec2b6639def5004a5fa2/audio/filter/af_scaletempo2.c)

### Describe alternatives you've considered

There is no decision

### Additional context

I find it difficult to perceive the changed pitch in accelerated video and audio. Voice and music become squeaky

**Comment by sergeyotro** [comment]
Especially considering that mobile apps work fine when speeding up videos - yeah, this is a must.

**Comment by idMysteries** [comment]
Looks like this has been fixed. At least the pitch doesn't change in Windows 11.
