### ISSUE TITLE
Decryped Media Cache

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#24223]
### Is your feature request related to a problem?

yes,
when someone creates a chat, and there is a link with an image you want,

but chat owner deteles the chat.
i need to recover the image from my HDD

### Describe the solution you'd like

Not Encrypted Media Cache

have a setting Optional near Cache Size.

### Describe alternatives you've considered

https://github.com/atilaromero/telegram-desktop-decrypt/releases

**Comment by john-preston** [comment]
There is no plans to introduce unencrypted cache of the photos, sorry. Maybe some fork will do that.
