### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by paxe** [telegramdesktop/tdesktop#24224]
### Steps to reproduce

I'm following instructions as per https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md,
the "docker run" step fails as follows:

CMake Error at /usr/local/desktop-app/Qt-6.2.3/lib/cmake/Qt6/QtFeature.cmake:1135 (message):
  Feature xcomposite_egl is already defined to be "ON" and should now be set                                                                                             
  to "OFF" when importing features from Qt6::WaylandClient.

### Expected behaviour

Success.

### Actual behaviour

Fails with message above. Any reason to include call stack as well?

### Operating system

Debian Linux bullseye.

### Version of Telegram Desktop

Current from git as on 2022/03/20.

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Clear the build cache

**Comment by john-preston** [comment]
Try to fully clear the tdesktop/out folder and run again.

**Comment by paxe** [comment]
I've done a newer pull since the other day, but things have regressed severely since then...
The docker run fails immediately, like so:
Traceback (most recent call last):
  File "/usr/src/tdesktop/Telegram/configure.py", line 13, in <module>
    import run_cmake
ImportError: No module named run_cmake
Error: /usr/src/tdesktop/out is not a directory

**Comment by ilya-fedin** [comment]
Looks like you forgot `--recursive` while cloning the repository

**Comment by paxe** [comment]
D'oh! Thanks, I finally got it to finish.
