### ISSUE TITLE
[Bug]Input method selection box crash with Mac OS

### ISSUE THREAD

**Issue by ChrisHK** [telegramdesktop/tdesktop#24225]
### Steps to reproduce

1. Using input methods has a selection words box.
2. Enter a punctuation mark between the input text
3. You will find that the selection box will crash

### Expected behaviour

Should disappear normally after normal input

### Actual behaviour

The selection words box does not disappear

### Operating system

Mac OS 12.3

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Can you please provide a more detailed steps? Like:

1. add an input method "..." in system settings.
2. choose it.
3. write this to the input field.
4. write that to the input field.
5. click somewhere or idk.

So that I could reproduce that easily.
