### ISSUE TITLE
Messages translation

### ISSUE THREAD

**Issue by Bedrou** [telegramdesktop/tdesktop#24221]
### Is your feature request related to a problem?

No message translation like in Telegram android app.

### Describe the solution you'd like

Please can you add message translation like in android app. This is a very important feature since the channels or groups are multilingual and it is not easy to go through translation bots every time. Thank you.

### Describe alternatives you've considered

No alternative.

**Comment by xingleiwu** [comment]
Support adding translation function, you can more easily view the messages you need
