### ISSUE TITLE
[Feature Request] Change domain resolver test from google.ru to something more open

### ISSUE THREAD

**Issue by redgryphon** [telegramdesktop/tdesktop#24236]
### Is your feature request related to a problem?

As of today the application tests if the resolution of domain names is working by querying `www.google.ru`. This would not be great, privacy-wise even if it was pinging `www.google.fr` or `www.google.com`. With the last geopolitical tensions and the chance of Russia being disconnected by the global internet not zero this would create a couple of days of chaos. 

### Describe the solution you'd like

Substitute the domain with something more appropriate. I'd say `telegram.org` would at least a lot better than the current situation.

### Describe alternatives you've considered

If a constant "phoning home" is not deemed sufficient in terms of privacy it could be possible to create a list of normal domains that can be randomly picked to be the check (`microsoft.com` for Windows computers could be one of the domains in the list, for example).

**Comment by ilya-fedin** [comment]
> As of today the application tests if the resolution of domain names is working by querying `[www.google.ru](http://www.google.ru)`.

That's false, there's nothing like that. tdesktop doesn't ping these domains for tests, tdesktop uses them for DoH. tdesktop also would try to use the .com domains if the .ru is not accessible.

**Comment by redgryphon** [comment]
> That's false, there's nothing like that. 

You decided not to literally read my words and to reply to what yo understood of them.

> tdesktop doesn't ping these domains for tests, 

I didn't say that it pings those domains. I said that it try to resolve them to test if domain resolution is working.

>tdesktop uses them for DoH.

DoH doesn't matter here. Even if it was plain old DNS my issue would be the same.

> tdesktop also would try to use the .com domains if the .ru is not accessible.

I know it. I can read the code.

> And [www.google.ru](http://www.google.ru) is not the first one, the first one is dns.google.com that apparently is blocked in your network. 

My network doesn't matter. I am reporting the issue by reading the code.

> It also would try Cloudflare if Google is not accessible.

Same here. The server it's trying to call to get the resolution doesn't matter. It matters the domain name it's asking the resolution for.

**Comment by ilya-fedin** [comment]
> I said that it try to resolve them to test if domain resolution is working.

I already said that's false, it's not used to test whether domain resolution is working, there's no such kind of test at all. I'm forced to repeat that this is used for DoH.

> I didn't say that it pings those domains.

![изображение](https://user-images.githubusercontent.com/17829319/162280000-5351788d-a789-4ff0-a76e-dc7a074131db.png)

> I know it. I can read the code.

I don't understand what you request then. It will work even if google.ru is not accessible.

> My network doesn't matter. I am reporting the issue by reading the code.

Well, you wrongly read the code it seems.

> The server it's trying to call to get the resolution doesn't matter. It matters the domain name it's asking the resolution for.

wat?

**Comment by redgryphon** [comment]
> I already said that's false, it's not used to test whether domain resolution is working, there's no such kind of test at all. I'm forced to repeat that this is used for DoH.

Please then explain what the code [here](https://github.com/telegramdesktop/tdesktop/blob/e8748986bf69113fe39083aa3c5836b67019ac6c/Telegram/SourceFiles/mtproto/details/mtproto_domain_resolver.cpp#L193) is trying to do. 


> > I didn't say that it pings those domains.
> 
> ![изображение](https://user-images.githubusercontent.com/17829319/162280000-5351788d-a789-4ff0-a76e-dc7a074131db.png)

The two sentences "it pings" and "even if it was pinging" mean two totally different things in the English language. The former is a fact, the second is regarding something that it is not and that if it was instead a fact then it would imply the other part of the sentence you didn't quote.

> > I know it. I can read the code.
> 
> I don't understand what you request then. It will work even if google.ru is not accessible.

Accessing google.ru is a thing, querying the DNS to ask for a resolution of google.ru into an IPv4 or IPv6 address is another.

> > My network doesn't matter. I am reporting the issue by reading the code.
> 
> Well, you wrongly read the code it seems.

As stated before, what does the code say then?

> > The server it's trying to call to get the resolution doesn't matter. It matters the domain name it's asking the resolution for.
> 
> wat?

Easy, I'll try to explain it further. The application is trying to ask the DNS server, whatever it is, if the DNS resolution is working. I hope this is not questioned. The domains into the query could be whatever. It could be example.com for what it's worth. The only important thing is that a proper answer comes or not.
Everything boils down to this simple question: what would be different into the application behavior if instead of `google.com` and `google.ru` there was `telegram.org`, `youtube.com` or `bbc.com`?

**Comment by ilya-fedin** [comment]
> Please then explain what the code [here](https://github.com/telegramdesktop/tdesktop/blob/e8748986bf69113fe39083aa3c5836b67019ac6c/Telegram/SourceFiles/mtproto/details/mtproto_domain_resolver.cpp#L193) is trying to do.

Resolves a domain with the built-in DoH resolver

> Everything boils down to this simple question: what would be different into the application behavior if instead of `google.com` and `google.ru` there was `telegram.org`, `youtube.com` or `bbc.com`?

Those domains aren't DoH servers...

**Comment by john-preston** [comment]
@redgryphon > The application is trying to ask the DNS server, whatever it is, if the DNS resolution is working.

No, it doesn't try to ask the DNS server if the DNS resolution is working.

It tries to resolve a domain name and get the response from any of the several public DNS-over-HTTPS services listed in the code.

It needs the resolve result that wasn't messed with by the local ISP or anyone, true response directly from Google or Mozilla or Microsoft.
