### ISSUE TITLE
An addition to Schedule Messages

### ISSUE THREAD

**Issue by Bharath1910** [telegramdesktop/tdesktop#24238]
### Is your feature request related to a problem?

There are currently two ways to schedule messages in Telegram,
- We can either specify which time we should send a message, or
- We can schedule a message to be sent if a person comes online.

But there is no way to schedule a message if a person sends a message to us.

### Describe the solution you'd like

If we can schedule a message to be sent **only if** a person sends us a message, it will be more useful.

### A use case scenario will be,
If I am out of station and I want to send  ``I am out of station, I will text you back when I reach home``  to my friend **only** when he texts me a message.

### Describe alternatives you've considered

I Don't have any alternatives for this feature

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
