### ISSUE TITLE
[Feature Request] Hide message or antibot

### ISSUE THREAD

**Issue by Potracheno** [telegramdesktop/tdesktop#24234]
### Is your feature request related to a problem?

In some countries because of a situation we have kind a spam with a political related opinions. They stand strongly on the propaganda opinion.  

### Describe the solution you'd like

If you strictly decided to yourself that telegram user is a spammer just mark it so and never see posting from it.

### Describe alternatives you've considered

Long tap on a message and menu "Ban and Report Spam" or "Ban"

### Additional context

Thanks if community find it request useful. I do believe it can make telegram much useful and save some time for users.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
