### ISSUE TITLE
Flatpak version creates new instance instead of using currently openned

### ISSUE THREAD

**Issue by ilyachch** [telegramdesktop/tdesktop#24240]
### Steps to reproduce

1. Install latest version from flathub
2. Minimize to tray
3. Click on icon in dash or in applications view

OR
1. Install latest version from flathub
2. Minimize to tray
3. Open any link https://t.me/...

### Expected behaviour

Launched instance comes to foreground

### Actual behaviour

Now the new instance of application is openning
![image](https://user-images.githubusercontent.com/1570221/159765293-e280a928-430e-4d1f-bf00-b65ffb226e36.png)

### Operating system

Ubuntu 20.04.4, Gnome 3.36.8, Flatpak version 1.6.5

### Version of Telegram Desktop

3.6.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
You need Flatpak version minimum 1.12.0 for tdesktop to work correctly
