### ISSUE TITLE
Sending Animated PNG file breaks it by converting it to JPG

### ISSUE THREAD

**Issue by RDKRACZ** [telegramdesktop/tdesktop#24246]
### Steps to reproduce

Here is an example file
![ezgif com-gif-maker](https://user-images.githubusercontent.com/43277609/159806545-1d589bdb-4556-4898-81c6-f47b2f05f8ed.png)

### Expected behaviour

The image should stay in its format or be converted to GIF, WebP, or a video file.

### Actual behaviour

Image gets destroyed

### Operating system

linux

### Version of Telegram Desktop

3.6

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Uncheck "Compress image" checkbox to send original

**Comment by RDKRACZ** [comment]
This doesn't change anything? The file is still not being played when you preview it, and even if it would that's just a walkaround.

**Comment by ilya-fedin** [comment]
> This doesn't change anything?

Changes, it would

> The image should stay in its format

**Comment by RDKRACZ** [comment]
It should stay in its format (and be animated) if Telegram doesn't want to convert it to the webp or gif that is.

**Comment by RDKRACZ** [comment]
I already said it - even if I send the file as a "file" instead of the compressed version it is still not being animated in the preview.

This doesn't change the main issue - lack of support for APNG.

**Comment by ilya-fedin** [comment]
The fact preview is static is intended, you need to open the image for it to be animated.

If you want support for APNG, you need to submit a feature request.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by RDKRACZ** [comment]
Done - https://bugs.telegram.org/c/15907
