### ISSUE TITLE
TDesktop Windows Not parsing links

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#24249]
### Steps to reproduce

click any link...

### Expected behaviour

open link in default browser

### Actual behaviour

nothing

### Operating system

Windows8.1x64

### Version of Telegram Desktop

3.6.1x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by juanpc2018** [comment]
uninstalled the program...
downloaded again the installer.exe x64
installed..
and works again ok.

problem was the update inside Telegram.
