### ISSUE TITLE
Cannot change group picture

### ISSUE THREAD

**Issue by mbasaglia** [telegramdesktop/tdesktop#24244]
### Steps to reproduce

1. Create a new group chat
2. go to the settings to change the picture
3. select a file / crop
4. click "done"

### Expected behaviour

the profile picture should change

### Actual behaviour

it doesn't change

### Operating system

Ubuntu 21.10, KDE

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by furll** [comment]
On 3.6.1 for windows I have the same behaviour. Profile pics also don't change without error.

**Comment by RememberTheAir** [comment]
Should be fixed in 3.6.2, which hasn't been released yet
