### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by rouLior** [telegramdesktop/tdesktop#24243]
### Is your feature request related to a problem?

  As a member of a large Telegram group I am facing issue with navigating through ocean of posts.

### Describe the solution you'd like

                    It would be great if we have a combined search features like date and sender.  

### Describe alternatives you've considered

Thanks.

**Comment by Justinzobel** [comment]
Please add a title so it isn't just `[Feature Request]` in the list view.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
