### ISSUE TITLE
Пропадают подписчики!

### ISSUE THREAD

**Issue by Artem4ik85** [telegramdesktop/tdesktop#24259]
### Steps to reproduce

hello. I have a channel. I put the information there through the bot. Subscribers have recently appeared, there weren't any before, so I didn't notice this problem. In the morning 70 people came, and in the evening almost all were blacklisted and it is shown that I did it, but I did not do it. Then 20 people came again, the next day they all disappeared, as if they had never been, they were not on the blacklist. I have already reinstalled Telegram on my phone and on my PC. What could it be?
![Снимок экрана (36)](https://user-images.githubusercontent.com/49896129/160268321-cb53fd10-9c53-4eeb-8cc0-4419de8e2ed9.png)
![Снимок экрана (37)](https://user-images.githubusercontent.com/49896129/160268324-eaa8a28e-9614-48e5-95f9-d8bce23874d0.png)
![Снимок экрана (38)](https://user-images.githubusercontent.com/49896129/160268325-580b6aa6-2d5b-4463-9330-c30816d14c58.png)
 
![Снимок экрана (42)](https://user-images.githubusercontent.com/49896129/160268837-9c7f89c1-c024-418d-8028-7fb7abfc5de6.png)
![Снимок экрана (43)](https://user-images.githubusercontent.com/49896129/160268839-3ca3178e-1bb5-40db-b29f-8086dc8ea766.png)

![Снимок экрана (45)](https://user-images.githubusercontent.com/49896129/160268877-0e6905ce-7aaf-4705-a85a-7c10c4ef3120.png)

Pay attention to the time when they signed up and when they were blocked. I didn't do it. Could it be because of a bot?

### Expected behaviour

They shouldn't just be blocked.

### Actual behaviour

This happens all the time as soon as several people are recruited.

### Operating system

WIN 10

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
english plz.

**Comment by dsgsdg3** [comment]
:-D
![Снимок экрана от 2022-03-27 09-37-41](https://user-images.githubusercontent.com/96667633/160270087-59dbae78-9e5d-4034-9db3-4765db763731.png)
