### ISSUE TITLE
Green lines on video stickers in some cases

### ISSUE THREAD

**Issue by HellbringerOnline** [telegramdesktop/tdesktop#24257]
### Steps to reproduce

i encode stickers using these parameters:
-c:v libvpx-vp9 -pix_fmt yuv420p
and lossless or 1- or 2-pass encoding so that the file size is less than 250 kb

### Expected behaviour

everything should work well

### Actual behaviour

everything works fine for me, but some users complained that green stripes appear on top of the sticker

Stickers
[1.zip](https://github.com/telegramdesktop/tdesktop/files/8354341/1.zip)
[2.zip](https://github.com/telegramdesktop/tdesktop/files/8354343/2.zip)

Fine for me
![image](https://user-images.githubusercontent.com/14059683/160216489-64b5db28-0734-4f6a-a835-3cfeafc4109b.png)
Problems for users
![image](https://user-images.githubusercontent.com/14059683/160216643-ce143e28-618e-43b3-986f-dad8703bd190.png)
![image](https://user-images.githubusercontent.com/14059683/160216661-f7061fe9-07c6-430e-9828-1d731cab074c.png)
The problem is for some users of the desktop version of the application and iPhone users, mainly iPhone users.
Screens from iphone XS

### Operating system

Windows 10

### Version of Telegram Desktop

3.6 x64

### Installation source

Microsoft Store

**Comment by john-preston** [comment]
Hmm.. you encode stickers using ffmpeg and see artifacts on the iPhone app? I don't see how this is related to Telegram Desktop. And I don't know how to help you with that..
