### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by meklonets** [telegramdesktop/tdesktop#24258]
OS: Arch Linux.
Wayland, swaywm.
Official Telegram Desktop app. Updated.

I have two monitors: FullHD and UHD. 24" both. 
In swaywm for UHD I have "scale 2" set.
When I start telegram on UHD monitor there is transparent areas showing desktop background.
But if I move telegram app workspace to FullHD and get it back to UHD again the problem is fixed.

If I start telegram app on FullHD monitor it's fine as it should be.

If I remove "scale 2" setting for UHD monitor in swaywm configuration file. And start telegram app on UHD monitor its fine as well.

![11h_57m_34s_26_Mar_22](https://user-images.githubusercontent.com/13570880/160233109-a70961a6-a846-48f6-9f58-e02d941e838d.png)

The screencast https://www.youtube.com/watch?v=5zIymAPV70o

Could you help where to dig?

**Comment by ilya-fedin** [comment]
Maybe you're hitting https://bugreports.qt.io/browse/QTBUG-93380?

**Comment by meklonets** [comment]
the issue still exists. I just havn't been visiting github lately.

**Comment by ilya-fedin** [comment]
@meklonets you have got the answer to your question
