### ISSUE TITLE
Bigger Sticker preview.

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#24251]
### Is your feature request related to a problem?

yes.

### Describe the solution you'd like

Bigger sticker preview...
looks too small, preview should have same size as real sticker..
tiny sticker makes No sense.

### Describe alternatives you've considered

purchasing a magnifier glass.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4117
