### ISSUE TITLE
[Question] Is the proxy server of Telegram mtproto faulty?

### ISSUE THREAD

**Issue by fish6688** [telegramdesktop/tdesktop#24260]
Is the proxy server of Telegram mtproto faulty? Now many normal proxies can't connect, and when connected, the delay number is not displayed. The proxies added before will show a delay of milliseconds, and now the proxies are showing that they are connecting.

**Comment by fish6688** [comment]
Now many normal proxies are always connecting, and the connection will only be displayed when the link is clicked. The proxies added before will show a delay of milliseconds, and now the proxies are showing that they are connecting.

**Comment by fish6688** [comment]
@alexandernst @jhasse @ForNeVeR

**Comment by fish6688** [comment]
@john-preston

**Comment by john-preston** [comment]
OS?
