### ISSUE TITLE
[Question]  is libtgvoip support dropped?

### ISSUE THREAD

**Issue by tgtglove** [telegramdesktop/tdesktop#24262]
apparently support for libtgvoip has been discontinued and it will no longer be developed and used?

noticed that all third party clients
that use libtgvoip like Telegram X
can't make voice calls to latest versions of android apps versions 8.6.0, 8.6.1, 8.6.2.

seems Telegram removed support libtgvoip recently judging by the removal of legacy code

https://github.com/TelegramMessenger/tgcalls/commit/6250a8d541208297828c8d85111c2735525b7043

can you confirm that now only the webrtc implementation remains working?

**Comment by 23rd** [comment]
https://bugs.telegram.org/c/15678

**Comment by tgtglove** [comment]
>https://bugs.telegram.org/c/15678

are you suggesting that this is a bug and not a deliberate cessation of libtgvoip support?

**Comment by 23rd** [comment]
I suggest asking questions about other clients in the relevant places.
