### ISSUE TITLE
Win 10:: App crash while resizing

### ISSUE THREAD

**Issue by pulsar14** [telegramdesktop/tdesktop#24261]
trying to resize the App, the App stop responding. It can be maximized only.

**Comment by Aokromes** [comment]
restore template, state gfx card, telegram version, etc

**Comment by pulsar14** [comment]
Hi Aokromes, thank U very much for your advices. I fix the issue by setting "Use System Windows Frame" in Advance settings. Now I can resize the App!
The App version is 3.6.1 x64 running with the internal Intel graphic card.
Regards
