### ISSUE TITLE
[Feature Request] Don't remove and ban users from a voice chat in a group

### ISSUE THREAD

**Issue by Miqueas** [telegramdesktop/tdesktop#24266]
### Is your feature request related to a problem?

Yes (a bit I guess)

### Describe the solution you'd like

Instead of remove (and ban) an user in a group, just kick it from the voice chat

### Describe alternatives you've considered

I'm not sure what to put here, but maybe allow admins kick users from a voice chat and have another option to prevent some users to enter the voice chat (?)

### Additional context

An example of what I mean

![a](https://user-images.githubusercontent.com/31262466/160511315-619e0193-5cf3-4856-8fcb-eb4bf495557e.jpg)

![b](https://user-images.githubusercontent.com/31262466/160511318-fe586f39-83a8-4874-b0cd-db0fd571aa72.jpg)

The admin just want to kick me from the voice chat, not ban me lol

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
