### ISSUE TITLE
Not able to select more than 100 chat messages at once

### ISSUE THREAD

**Issue by ohhai** [telegramdesktop/tdesktop#24268]
### Steps to reproduce

It's a known issue and was reported before, but that tickets are now closed by bot.

I came here since it's frustrating and takes a lot of time to export big discussions dividing them by smaller chunks because of this limit.
Built-in export doesn't help since I need to export discussion of a specific post in a public channel.
Tickets #2045 and #2692 describe other usecases.

Server limit is not related here, since it's possible to fetch and select 1000 messages with 10 requests to server.

If it would consume a lot of client resources - it might be configured in telegram-desktop UI or config file. Value of 100 is too small anyway.

### Expected behaviour

More than 100 messages are selected.

### Actual behaviour

Selection does not extend over 100 messages.

### Operating system

Linux

### Version of Telegram Desktop

3.6.1

### Installation source

Other (unofficial) source

**Comment by ohhai** [comment]
> That's false, I see it's closed by human. [#2045 (comment)](https://github.com/telegramdesktop/tdesktop/issues/2045#issuecomment-252281122)

Now I see, thanks. Looked at this lock and resolution: "github-actions bot locked as resolved and limited conversation to collaborators on Mar 4, 2021". I would have commented any of them if it was possible.

**Comment by ilya-fedin** [comment]
There's no reason to comment. It's a server-side limitation thus this wouldn't be changed as it won't work anyway.

**Comment by ohhai** [comment]
> There's no reason to comment. It's a server-side limitation thus this wouldn't be changed as it won't work anyway.

Do you mean server side limitation for one (fetch) request?
Selection does work without internet connection (just checked it), so server is not involved for this specific action.
So it might be still possible to make several requests and select all results in telegram-desktop, I guess

**Comment by ilya-fedin** [comment]
You can't make several requests or the server will ban you with FLOOD_WAIT

**Comment by ohhai** [comment]
> You can't make several requests or the server will ban you with FLOOD_WAIT

But it doesn't ban me somehow when I fetch messages by constantly pressed pageup/pagedown keys?

Just checked how it works for a thread with 1700 comments. Scrolling stops once in the middle and this might be this ban (if it is very short). But then I'm able to scroll the entire thread from start to end backward and forward without any interruptions - all 1700 comments at once, by pageup/pagedown. At this moment it seems to be only the client side limit which prohibits me from selecting all messages.

**Comment by ilya-fedin** [comment]
Well, you see, the previous issue was closed with wontfix and I don't think this decision has been changed

**Comment by RememberTheAir** [comment]
The hard-coded 100 messages limits is weird because while it's true that the server doesn't allow you to forward more than 100 messages in one go, there are still actions that allows to pass more than 100 messages at once and will be accepted by the server (eg. deleting messages). Right now, if you select a message and extend the selection by dragging the pointer, you can select the entire chat history - but tdesktop will act as if you selected just the last 100 messages. Not sure why this works this way. Maybe the app should let you select more than 100 messages (like the android/ios app do) and warn you if you want to perform an action that is limited by the server, like forwarding messages

**Comment by ohhai** [comment]
"the user has lost interest or resolved the problem on their own" - no.

**Comment by soredake** [comment]
Still valid.
