### ISSUE TITLE
Smooth Scroll Not smooth enough

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#24271]
### Steps to reproduce

with a trackpad or mouse 3rd wheel,
scroll fast a large channel.

### Expected behaviour

smooth scroll like browser.yandex.
or firefox,
at 60fps.

### Actual behaviour

some images, videos, emoticons, or comments update.
create interrupts that affect scrolling.

### Operating system

Windows8.1x64

### Version of Telegram Desktop

3.6.1x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#6746?

**Comment by juanpc2018** [comment]
yes, my issue is related to Kinetic scroll code,
part of kinetic scroll.,
Needs "fine tuning", clean up, optimization, maybe a change in priority levels or disable realtime monitoring of comments while scrolling? maybe, increase pre-load cache area.?

**Comment by ilya-fedin** [comment]
I don't quite understand what you're talking about. Can you provide a screencast? I thought you mean that there's no kinetic scrolling what is already reported as #6746, but if you think your issue is not a duplicate, a screencast is required then.

**Comment by juanpc2018** [comment]
i have bad news...

Kubuntu 20.10 Groovy Gorilla,
Mac Mini 2014 
Iris Graphics 5100 GPU

Scroll jitter is insane...
like 3 frames per second.
everything is chopped,
skipps frames like crazy.

i know the GPU is inferior to Nvidia GT 730,
Yandex browser also feels strange,
but Not this insane...

Telegram Latest Edge version 3.6.2x64

https://en.wikipedia.org/wiki/Mac_Mini#Third_generation_(Unibody)
https://en.wikipedia.org/wiki/Intel_Graphics_Technology#Haswell

i can recor a video if you want to cry.

**Comment by juanpc2018** [comment]
https://odysee.com/tdesktop30fps_1:dc5cbc0e0864de7da6fb11fd8f29a4a057928c9e

**Comment by juanpc2018** [comment]
problem seems related to the type of USB Mouse or Trackpad...

i changed to a Microsoft Wireless Mouse 5000
does Not slip & slide like the Microsoft Trackpad with 2 fingers,
BUT... moving the 3rd wheel fast, looks smooth, same Wheel settings 2 per click.
when moving slow, the stepness / staircase feeling can be detected, but smaller.

**Comment by juanpc2018** [comment]
found a way to better explain the problem..

mouse wheel
1 vs 10 scroll lines.

lines are not pixels,
1 line still feels a bit semi-coarse when moving slow, at 1 line step at 1080p
but visually acceptable, almost fools human eye.
vs. 10 jumps "coarse", No smooth transition.

with 1 setting i need to move very fast the mouse wheel to scroll in the screen at an acceptable speed.
does Not increase speed dynamically.
does Not have smooth transition between 1 line and the next.

Same happens with MIDI volume cc7,
MIDI its 7-Bits
0 to 127 steps "128", 
coarse enough to be noticeable when making a fade-in or fade-out,
DSP mixers like Yamaha DSP Factory pci or Digital consoles 01v 03d 02r,
implemented decades ago an algorithm to make smooth volume transitions between midi steps.
for example, 
Audio is 16-Bits, has 65536 steps,
MIDI 7-Bits 128 steps = 512 steps jumped.

Smooth Volume algorithm, gradually change values 
between MIDI steps, Not jumping 512 steps.

**Comment by juanpc2018** [comment]
tested pearOS Monterrey in acer Aspire 5 Touchpad,
scroll looks smooth.

each hardware scroll algorithm behaves differently.
Mouse Wheel Jumps,
acer Touchpad is smooth.
microsoft aio touchpad has weird jitter, jumps like a mouse wheel when slow, and slides like a touchpad when fast.
etc...
