### ISSUE TITLE
Некорректное отображение мультимедиа на дополнительном мониторе

### ISSUE THREAD

**Issue by abhyrz** [telegramdesktop/tdesktop#24270]
### Steps to reproduce

при наличии двух мониторов с разными расширениями настройки при отображении мультимедиа берутся с основного монитора. у меня на основном мониторе разрешение 1680*1050, на дополнительном мониторе 1920*1200. если телеграм расположен на дополнительном мониторе, то при открытии картинок или видео они не растягиваются до 1920*1200, а отображаются только на части доступного разрешения, у видео при этом пропадает управление воспроизведением. если перетащить клиент телеграм на основной монитор, то отображение корректное 

### Expected behaviour

ранее мультимедиа растягивалось под разрешение того монитора, на котором открывается

### Actual behaviour

мультимедиа использует разрешение с основного монитора, а не с того, на котором открывается 

### Operating system

win10

### Version of Telegram Desktop

3.6.1

### Installation source

Other (unofficial) source

**Comment by abhyrz** [comment]
у меня основной стоит бета версия, установил с сайта версию для Win10 (x64), в ней проблема так же воспроизводится

**Comment by ilya-fedin** [comment]
Only English is allowed here

**Comment by abhyrz** [comment]
> Only English is allowed here

мой уровень английского не позволяет это описать. если ты сможешь это перевести, будет просто прекрасно

**Comment by ilya-fedin** [comment]
@Aokromes can you close this issue since reporter refuses to use English?
