### ISSUE TITLE
Tamil Language preview not working

### ISSUE THREAD

**Issue by TamilNeram** [telegramdesktop/tdesktop#24279]
### Steps to reproduce

1) visit "https://translations.telegram.org/ta/"
2) if required login with your registered telegram user id. 
3) Click on the link which says "[Use Telegram in Tamil (beta)](https://t.me/setlanguage/ta-beta)" 
4) Or directly visit this page "https://t.me/setlanguage/ta-beta"
it is broken page

### Expected behaviour

Telegram in Tamil language

### Actual behaviour

page not found

### Operating system

Windows and MAC

### Version of Telegram Desktop

Latest Version of Telegram

### Installation source

Static binary from official website

**Comment by TamilNeram** [comment]
This is unwatched for long time. Someone please look into the issue.

**Comment by ilya-fedin** [comment]
I can't reproduce
![изображение](https://user-images.githubusercontent.com/17829319/193198031-4014ae0a-b1dc-46b3-9541-f8b2b440003e.png)
And honestly saying this is not a place for this issue as this doesn't look like a tdesktop bug
