### ISSUE TITLE
[Feature Request] an option to disable particular contact's avatar

### ISSUE THREAD

**Issue by igorMIA** [telegramdesktop/tdesktop#24283]
### Is your feature request related to a problem?

Some users might have questionable (NSFW) avatars in group chats. It could create a nasty situation. For eg, I was in a meeting with my colleagues, sharing my screen, and some crazy dude from my local BMW lover club tagged me in the chat. That dude has really nasty profile avatar :) 

### Describe the solution you'd like

A simple way to hide avatars of particular users.

### Describe alternatives you've considered

Not found any reliable(i know that some users may disable their avatars to non-contact users)

### Additional context

Old issue: https://github.com/telegramdesktop/tdesktop/issues/430

**Comment by Aokromes** [comment]
this must be implemented platform wide.
