### ISSUE TITLE
[Feature Request] Option to disable Archived chats showing up in icon's unread count

### ISSUE THREAD

**Issue by Justinzobel** [telegramdesktop/tdesktop#24284]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

In some desktop's it shows the unread count on your taskbar/dock. This includes archived chats. They are archived for a reason and shouldn't be included in the unread count. A toggle to show/hide archived chats from the unread count would be desirable.

### Describe alternatives you've considered

None

**Comment by ilya-fedin** [comment]
Settings -> Notifications -> Include muted chats in unread count

**Comment by Justinzobel** [comment]
My apologies, how I did not see that is beyond me. Thank you!
