### ISSUE TITLE
send code via sms dosent work

### ISSUE THREAD

**Issue by Gurenduben** [telegramdesktop/tdesktop#24287]
### Steps to reproduce

![telegram](https://user-images.githubusercontent.com/80658157/161869647-e3e43bee-c809-4191-a713-558b07f95294.png)

thats what i get when i try to send the code via sms

### Expected behaviour

it should have sent a text so i can login

### Actual behaviour

see screenshot

### Operating system

windows 10 

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
not a bug, like screenshot states you must be signed on phone.
