### ISSUE TITLE
what is hidden sender?

### ISSUE THREAD

**Issue by AMP999** [telegramdesktop/tdesktop#24281]
in file dialogs_layout.cpp at line 369 in the paintRow function there is a if condition if(hiddenSenderInfo).
what is hiddenSenderInfo?
thank you

**Comment by 23rd** [comment]
https://telegram.org/blog/filters-anonymous-admins-comments#anonymous-group-admins

**Comment by john-preston** [comment]
For example a forwarded message from a user, who disabled forwarded links in his privacy settings, is displayed as this hidden sender info.
