### ISSUE TITLE
Right clicking on a non-main display will cause a popup to appear on the main display.

### ISSUE THREAD

**Issue by Kuass** [telegramdesktop/tdesktop#24290]
### Steps to reproduce

1. Place the telegram client on the monitor, not the main display.
2. Right click on the client to interact with it.

### Expected behaviour

The popup should occur at the location where you right clicked.

### Actual behaviour

Popup windows only occur on the main display.

### Operating system

Windows 11 Pro 21H2 22000.556

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

https://youtu.be/2vrOF3RCzhU

**Comment by ilya-fedin** [comment]
#7099
