### ISSUE TITLE
D3D11on12 make media viewer freezes

### ISSUE THREAD

**Issue by KateHanami** [telegramdesktop/tdesktop#24298]
not sure how explain in detail, but setting graphics backend to DirectX 12 emulation causes pictures to not display, the program comes unclickable, and in the taskbar, I can see media viewer (not responding)
playing a video will not display anything, but I can hear the audio
reverse to DirectX 11 fixed it

windows 11 pro
AMD FX 8150
AMD RX 460
8GB ram

**Comment by ilya-fedin** [comment]
#24180

**Comment by demoix** [comment]
I'm having this issue too whenever I click on the picture in a telegram on the most recent version. It literally freezing my whole PC and bricking for a few minutes can't do anything, even ctrl alt del doesn't work. Win10, Asus ROG, Geforce 3060 laptop, Amd ryzen 5900HX CPU, 16gb ram
