### ISSUE TITLE
[Question] je veux lire les discussions envoyer et reçu que j'ai sur mon application telegram merci

### ISSUE THREAD

**Issue by Neuftta08** [telegramdesktop/tdesktop#24306]

**Comment by Aokromes** [comment]
english only, and what?

**Comment by Neuftta08** [comment]
Non je parle que le français

**Comment by mopitithomne** [comment]
Quel est le problème exactement ?
Tu peux installer l'application desktop.telegram.org pour cela. Tu te connectes avec ton numéro pour avoir accès à tes discussions.
