### ISSUE TITLE
Can not render CJK characters on Linux

### ISSUE THREAD

**Issue by oodzchen** [telegramdesktop/tdesktop#24305]
### Steps to reproduce

1. Use Manjaro
2. Install telegarm-desktop by pacman
3. Login telegram

### Expected behaviour

Normally show all characters

### Actual behaviour

All the Chinese characters render as squares.
![Selection_003](https://user-images.githubusercontent.com/9650699/162602700-2197115d-e4d3-4924-a105-ba496eef65c9.png)

![Selection_004](https://user-images.githubusercontent.com/9650699/162602716-60fbbfb4-7b6c-44cb-96e7-44df829a8d18.png)

### Operating system

Manjaro, GNOME 41

### Version of Telegram Desktop

3.6

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
pacman or static binary from official website?
also at least on fedora and telegram desktop  3.6.1 works for me.

**Comment by Aokromes** [comment]
also works on manjaro from 2021 and xfce.

**Comment by oodzchen** [comment]
@Aokromes OK, it's a problem cause by myself. Several days ago I've remove all the adobe font files from `/usr/share/fonts` for some reason, I recover the font files just now, and everything back to normal.
