### ISSUE TITLE
[Feature Request] Add a `--register-app` subcommand for Linux, like Tor Browser does

### ISSUE THREAD

**Issue by xegulon** [telegramdesktop/tdesktop#24303]
### Is your feature request related to a problem?

When installing the version from https://telegram.org/dl/desktop/linux, I have to manually create a desktop entry for me to see it like any other app.

### Describe the solution you'd like

When downloading the Tor Browser app for Linux, the `./start-tor-browser.desktop --register-app` command sets this up for me:

```
Launching './Browser/start-tor-browser --detach --register-app'...
Tor Browser has been registered as a desktop app for this user in ~/.local/share/applications/
```

### Describe alternatives you've considered

Create the desktop entry myself, but I don't like this.

**Comment by ilya-fedin** [comment]
> I have to manually create a desktop entry for me to see it like any other app.

tdesktop automatically creates desktop entry after first launch and after every update

**Comment by xegulon** [comment]
Ow, I didn't know that. Much thanks!
