### ISSUE TITLE
telegram loads one or more processor cores during the playback of an animated sticker

### ISSUE THREAD

**Issue by grisha765** [telegramdesktop/tdesktop#24307]
### Steps to reproduce

1) start telegram
2) dialog with an animated sticker
3)  the sticker doesn't move
4) the load on one or more processor cores begins

### Expected behaviour

I would like the sticker to move and not load the CPU cores

### Actual behaviour

the sticker does not move and loads the processor cores [https://imgur.com/a/ciHQjVt](https://imgur.com/a/ciHQjVt) [https://imgur.com/a/QdZSl7q](https://imgur.com/a/QdZSl7q)

### Operating system

Arch Linux x64

### Version of Telegram Desktop

3.6.1

### Installation source

Other (unofficial) source

### Logs

```shell
[libvpx-vp9 @ 0x7fe3a5e60000] v1.11.0
[matroska,webm @ 0x7fe3a5daf700] File extends beyond end of segment.
qt.svg: Error while inflating gzip file: SVG format check failed
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
```

**Comment by ilya-fedin** [comment]
Your CPU is probably just not enough for animated stickers

**Comment by Iife85dr1** [comment]
same issue

**Comment by ilya-fedin** [comment]
Are you using unofficial build, too? What if you try the official build from https://desktop.telegram.org?

**Comment by Iife85dr1** [comment]
> Are you using unofficial build, too? What if you try the official build from https://desktop.telegram.org?

3.6.1-2 version from archlinux repo. Okay i will try

**Comment by Iife85dr1** [comment]
> Are you using unofficial build, too? What if you try the official build from https://desktop.telegram.org?

with official build no problem no "[matroska,webm @ 0x7f1a8700a000] File extends beyond end of segment." in log

**Comment by grisha765** [comment]
> 

xeon l5420, exactly a quad-core processor should pull animated stickers

**Comment by ilya-fedin** [comment]
See other messages, this seem to be a bug of third-party build you're using

**Comment by svenstaro** [comment]
I think this issue is going to hit Telegram official builds as well once it's built against ffmpeg 5. No reason to think it's immune somehow. I think it'd be worthwhile for you to track this here.

**Comment by ilya-fedin** [comment]
AFAIK there's no plan to switch to ffmpeg 5 yet. And when this would happen, this will be tested so it's unlikely this will hit stable official builds.

**Comment by svenstaro** [comment]
What I mean is: It's just a question of time when telegram will switch. At that point, it'd be good to know about the reported issues with that so you don't start from a blank slate. Better collect known issues to make sure you know what to watch our for.

**Comment by ilya-fedin** [comment]
Well, it's a question for @john-preston and @Aokromes whether they want to reopen this or not.

**Comment by Fenimoure** [comment]
Have the same issue also on the official build

**Comment by ilya-fedin** [comment]
> Have the same issue also on the official build

I think that's false as I can't reproduce.
