### ISSUE TITLE
Media View shows media in incorrect full screen size

### ISSUE THREAD

**Issue by birdy-spb** [telegramdesktop/tdesktop#24312]
### Steps to reproduce

1. Launch telegram at left horizontally-oriented display
2. View any media. MediaViewer shows it correctly
![image](https://user-images.githubusercontent.com/60095202/162830148-3aef25a9-02d6-4634-8e82-5769f951a5d6.png)
3. Drag-n-drop application to right vertically-oriented display
4. View any media. MediaViewer shows only cropped part of media in upper half of display
![image](https://user-images.githubusercontent.com/60095202/162830280-647aa2b4-d9cc-4d17-9ecd-33e7bcf3b407.png)

### Expected behaviour

MediaViewer shows full media without cropping in correct full screen mode.

### Actual behaviour

MediaViewer shows only cropped part of media in upper half of vertically-oriented display 

### Operating system

Windows 10

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#24218
