### ISSUE TITLE
Searching by hashtags does not work for files that are not images

### ISSUE THREAD

**Issue by C0rn3j** [telegramdesktop/tdesktop#24316]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/1641362/162989835-cbc33693-3296-43aa-ac9e-0b33302a5fea.png)

Try uploading some messages and tag them with a #hashtag, the ones that are for example archives will not be searchable.

### Expected behaviour

Searching by hashtag works no matter the filetype

### Actual behaviour

Searching by hashtag does not work if the message is a certain file type

### Operating system

Arch Linux

### Version of Telegram Desktop

3.6.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
The search is server-side

**Comment by C0rn3j** [comment]
Thanks - reported here https://bugs.telegram.org/c/16416
