### ISSUE TITLE
Translation feature [Feature Request] 

### ISSUE THREAD

**Issue by AbhiTheModder** [telegramdesktop/tdesktop#24314]
### Is your feature request related to a problem?

I'm a reverse engineer and I use telegram for my many uses and within that i chat with most of the people around the world sometimes they came who only know Chinese, Japanese, French etc. and it's difficult to learn so many language still I learnt chinese because there are more people who came in my inbox are Chinese but how much I learn

and 
* The android and iOS versions got translation feature

### Describe the solution you'd like

So I recommend to implement it for PC users also

### Describe alternatives you've considered

i've to open browsers to translate or use a userbots or mouseover translator butproblem is:
* The browser if we see through task manager opens three or more processes but displays only one process which does a load on DISK it starts showing disk 100% with red
* The mouseover translators does affect the functions in chats
* The userbots are not allowed by telegram officially so maybe my account can get a ban

**Comment by ilya-fedin** [comment]
#6707
