### ISSUE TITLE
Keyboard layout changes automatically

### ISSUE THREAD

**Issue by sarmong** [telegramdesktop/tdesktop#24319]
### Steps to reproduce

1. Set layout with `setxkbmap us,ru`
2. Switch layout to `ru`
3. Start typing in Telegram app
4. At some random point you start typing English characters. However, xkb layout is remained unchanged - it is Russian
5. It will either go back to Russian at some point, or you can switch it to English and then back to Russian to fix.

### Expected behaviour

Telegram app doesn't interfere with keyboard layout

### Actual behaviour

Telegram changes keyboard layout to English randomly

### Operating system

Arch Linux

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Looks like a Qt bug :see_no_evil:

**Comment by ilya-fedin** [comment]
https://bugreports.qt.io/browse/QTBUG-102493

**Comment by HumanUser** [comment]
if there is any workarounds for this untill bugifx?

**Comment by ilya-fedin** [comment]
I don't know any

**Comment by HumanUser** [comment]
Is it possible to build 3.7 telegram with 6.2.1 < QT?

**Comment by ilya-fedin** [comment]
It should be. But I plan to use new APIs from Qt 6.3 for better Wayland support.

**Comment by elamperti** [comment]
The linked ticket (QTBUG-102493) was recently closed, the issue should be resolved using Qt 6.3.1 and greater (although desktop-app/cmake_helpers seems to be pointing to 6.3.0 at the moment), so the fix is around the corner 😃

**Comment by ilya-fedin** [comment]
This shouldn't be a problem for a long time in official builds since the bug was fixed by patching Qt in official builds
