### ISSUE TITLE
new setting design bug

### ISSUE THREAD

**Issue by bardiarastin** [telegramdesktop/tdesktop#2431]
### Expected behaviour
after setting automatic download option to none (don't download anything automally) the changes doesn't save . (after restart everything goes like before)
### Actual behaviour
it should save that settings !
### Configuration
** ubuntu 16.04 :**

**Version of Telegram Desktop:**
latest

**Comment by john-preston** [comment]
@bardiarastin Do you have "Tile background" option enabled? Is the bug still in place if you disable Tile background in Settings? There is a bug with settings overwritten by default if this options is set.

**Comment by bardiarastin** [comment]
the problem solves after disabling " tile background " ...

**Comment by john-preston** [comment]
@bardiarastin Ok, then it will be fixed in the next version. Thanks for your report!

**Comment by bardiarastin** [comment]
thank you for answering quickly .
