### ISSUE TITLE
PNGs are not included in chat export when Photos category is selected

### ISSUE THREAD

**Issue by mrdc** [telegramdesktop/tdesktop#24321]
### Steps to reproduce

1. Select a chat
2. Try to Export the selected chat with Photos category
3. PNGs are not included in export

### Expected behaviour

Images in PNG format should be included in Photos category for export.

### Actual behaviour

Images in PNG format are not exported when Photos category is selected during export.

### Operating system

Windows 10 x64

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@mrdc If they're in Files section of Shared Media then they should be exported with Files option chosen.
