### ISSUE TITLE
Bug in Per-Monitor DPI Awareness

### ISSUE THREAD

**Issue by minusium** [telegramdesktop/tdesktop#24327]
### Steps to reproduce

1. Start Telegram on a PC with 2 monitors and different DPIs
2. Move Telegram to another monitor
3. Open a photo

### Expected behaviour

Photo should take whole monitor's screen

### Actual behaviour

Photo takes space available to first monitor.

![image](https://user-images.githubusercontent.com/21140798/163329040-11cb40c6-07c0-4862-a0ca-4515c35e3c9b.png)

Also Telegram needs to have support for dynamic changing of DPI, currently it only uses the DPI provided in its Settings and changing it requires a restart of app.

### Operating system

Windows

### Version of Telegram Desktop

3.6

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
duplicate...

**Comment by minusium** [comment]
At least add link to original issue, I tried to search before btw.
