### ISSUE TITLE
[feature request] Don't reset stickers tab after sending a sticker (like on Android version)

### ISSUE THREAD

**Issue by Bullsquid** [telegramdesktop/tdesktop#2432]
This would allow to sent multiple stickers in a row in a convenient way, similar to how it works on Android: after you send a sticker, the sticker tab stays open and you can quickly select another one.
Alternatively, to preserve current behavior, the window can close after sending, but when you hover the emoji button, open stickers tab right where you were before sending the sticker, and maybe reset back to emoji after some timeout passes.
Using current sticker interface, it's pretty tedious to send multiple stickers from the same sticker pack, because every time you have to hover emoji button, press "stickers", scroll to desired stickerpack (again), select it, find desired sticker (again) and post it.
It gets even worse considering that current sticker interface has very small sticker-pack selection area (only 4.5 sticker packs on the screen) which you can not expand.

**Comment by leomwa** [comment]
The macOS version has this behaviour iirc.

**Comment by auchri** [comment]
#1076
