### ISSUE TITLE
[Site issue] Version history - not updated

### ISSUE THREAD

**Issue by Lazek** [telegramdesktop/tdesktop#2433]
Little issue in download page:
https://desktop.telegram.org/

Via download button, available version: 0.10.5
https://telegram.org/dl/desktop/win

In version history:
https://desktop.telegram.org/#changelog

Latest version:
v 0.10 03.08.16

**Comment by john-preston** [comment]
@Lazek Well, the minor updates (with not a great changelog or smth) are not shown in the version history.

**Comment by Lazek** [comment]
@john-preston Thanks for this information, I'm closed this issue.
