### ISSUE TITLE
message_silently in shortcuts-custom.json doesn't work on Mac OS

### ISSUE THREAD

**Issue by yadvlz** [telegramdesktop/tdesktop#24339]
### Steps to reproduce

shortcuts-custom.json:

// This is a list of your own shortcuts for Telegram Desktop
// You can see full list of commands in the 'shortcuts-default.json' file
// Place a null value instead of a command string to switch the shortcut off

[
   {
      "command": "message_silently",
      "keys": "cmd+s"
   }
]

### Expected behaviour

A silent message has been sent

### Actual behaviour

Nothing happens

### Operating system

macOS 12.2.1 Intel

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I don't think Qt's parser knows `cmd`, try `ctrl+s`

**Comment by yadvlz** [comment]
ctrl+s also doesn't work.
cmd+s worked a few months ago.

**Comment by ilya-fedin** [comment]
Have you tried to press Cmd+S when you specify ctrl+s? Qt swaps them under the hood.

**Comment by yadvlz** [comment]
This trick worked. Thanks.
