### ISSUE TITLE
[BUG] No window border, unable to resize and minimize, always fullscreen, introduced in 3.6.3 beta

### ISSUE THREAD

**Issue by atis** [telegramdesktop/tdesktop#24334]
### Steps to reproduce

Launch Telegram Desktop

### Expected behaviour

Should have window controls

### Actual behaviour

Takes all desktop (no window borders), unable to resize

### Operating system

Ubuntu 16.04 Mate Desktop

### Version of Telegram Desktop

3.6.3 beta

### Installation source

Static binary from official website

**Comment by atis** [comment]
![Workspace 1_999(029)](https://user-images.githubusercontent.com/1108226/163426652-6dc94506-9f3e-42f5-89e1-4b1e118b27c0.png)

**Comment by atis** [comment]
Workaround: downgrade to 3.6.1 and upgrade again. Causes re-login and reset of settings

**Comment by ilya-fedin** [comment]
So you can't reproduce anymore?

**Comment by atis** [comment]
Yes, issue is gone for me
