### ISSUE TITLE
Video has incorrect size on the second monitor

### ISSUE THREAD

**Issue by Pulkinen** [telegramdesktop/tdesktop#24348]
### Steps to reproduce

1. Attach second display. The 2nd display resolution should be larger than 1st display's one.
2. Play video on the second display

### Expected behaviour

Video shoud plays in its actual size.

### Actual behaviour

Video playing cropped

### Operating system

windows 10 64bit

### Version of Telegram Desktop

3.6.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
#24195
