### ISSUE TITLE
Cannot login without a phone ?

### ISSUE THREAD

**Issue by SkybuckFlying** [telegramdesktop/tdesktop#24340]
### Steps to reproduce

1. Download app.
2. Install app.
3. Try to login.
4. Cannot get passed these two screens without a phone:

Screen 1:
![TelegramScreen1](https://user-images.githubusercontent.com/34254801/163542713-f191fc31-6d0c-4023-a298-77003d5e8337.png)

Screen 2:
![TelegramScreen2](https://user-images.githubusercontent.com/34254801/163542715-f433b6f2-1caa-427a-ab98-336eba7c90e3.png)

### Expected behaviour

Should be more friendly for PC-users who don't have a "tracker/radiation device" aka mobile phone ;)

### Actual behaviour

Useless QR crap screens.

### Operating system

Goold Old Stable and Reliable Windows 7

### Version of Telegram Desktop

tsetup-x64.3.6.1.exe

### Installation source

Static binary from official website

**Comment by SkybuckFlying** [comment]
Your bot is wrong.

**Comment by Aokromes** [comment]
well, anyway it's duplicate issue and not a bug.
