### ISSUE TITLE
Multi Connection Download

### ISSUE THREAD

**Issue by MG-Token** [telegramdesktop/tdesktop#24343]
hi everyone
i have a request from telegram developers
at lastet update telegram added download manager 
Now I am requesting to add a multi-download connection for Telegram like IDM (Internet download manager)
i think this future can help to improve download speed 
we have connecting to telegram with proxy/vpn and its harder to download a big file with 300kb speed (1 connection or stream...) but we have more then 2MB speed in IDM or other site and application like WhatsApp

Thanks From Telegram Developers

**Comment by ilya-fedin** [comment]
tdesktop already uses multiple threads for download, what you see is probably bad speed from your proxy to Telegram's DC

**Comment by MG-Token** [comment]
> tdesktop already uses multiple threads for download, what you see is probably bad speed from your proxy to Telegram's DC

hi uhhh sorry for my bad english 
i created multiple threads download from WTelegramClient (its have not a multi download i added in code for my project and publiced in github) for c# and i have a download speed more then 2MB speed with own application and own vpn but telegram have less then 1MB download speed with own vpn i used for my app
why?

**Comment by ilya-fedin** [comment]
The logic to get optimal thread count returns less number of connections than your client has apparently
