### ISSUE TITLE
Question mark coming as /

### ISSUE THREAD

**Issue by astroty** [telegramdesktop/tdesktop#24346]
### Steps to reproduce

Press ? on the "Write a message" input box

### Expected behaviour

? should show up in the input box

### Actual behaviour

Type ? on the "Write a message..." input box
Telegram types out / instead

### Operating system

Manjaro Unstable, KDE Plasma 5.24.4

### Version of Telegram Desktop

3.6.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Well, I type ? and get ?, please provide more info

**Comment by astroty** [comment]
I don't really know how to provide more info, as I don't know how I'd be able to debug that
My LANG is set to pt_BR.UTF-8 I guess? abnt2 keyboard 
I installed through Flatpak just to confirm it wasn't anything weird with my install (I have another instance of Telegram, so the Flatpak one is completely new and untouched) and it happened there.
Alt Gr+W works properly

**Comment by ilya-fedin** [comment]
> My LANG is set to pt_BR.UTF-8 I guess?

Well, I think there are needed layout settings (`setxkbmap -query`) rather than locale settings

**Comment by astroty** [comment]
rules:      evdev
model:      pc105
layout:     br
options:    terminate:ctrl_alt_bksp

My output from that

**Comment by ilya-fedin** [comment]
What should I press to get question mark on this layout?

**Comment by astroty** [comment]
![image](https://user-images.githubusercontent.com/1356321/163659452-6065392a-1a84-476b-b28e-e0bd305da019.png)
Key next to right shift

**Comment by ilya-fedin** [comment]
I don't have that :/; button and get ; when I press the ?// button

**Comment by astroty** [comment]
I'm unsure how I can be of further assistance
I might try spinning up a virtual machine and see what happens

**Comment by ilya-fedin** [comment]
The next should be reporting to Qt as it's most likely a Qt issue, but since I can't reproduce that, I can't report to Qt. So the only way to move forward this issue is for you to manually build Qt 6.2.4 and reproduce the bug on their examples (I sugget the `lineedits` example). Then, you can create a Qt bug report and specify the example you reproduced on as the minimal reproducer.
