### ISSUE TITLE
Hardware acceleration doesn't work as expected

### ISSUE THREAD

**Issue by tissole** [telegramdesktop/tdesktop#24345]
### Steps to reproduce

Enable hardware acceleration in settings, select Direct3D 11 or Direct3D 9 as ANGLE graphics backend, then play a 1080p video encoded in H.264.

### Expected behaviour

Video plays fine.

### Actual behaviour

Video plays sluggish, like is dropping frames with Direct3D 11 enabled, and with Direct3D 9 the image is green. Plays OK with OpenGL enabled.

### Operating system

Windows 10 21H2, Intel Core i3-4160 

### Version of Telegram Desktop

3.6.3 beta x64

### Installation source

Static binary from official website

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
It looks like it was because of this commit: https://github.com/telegramdesktop/tdesktop/commit/27d9f7856653e90ed1c9ca60187cce6481667f7a
On systems with an old GPU (like Intel HD Graphics) only the Open GL backend works without issues.

**Comment by tissole** [comment]
Still an improvement, the CPU stays now at 10%, before stayed at 20%. But I hope that Direct3D 11 gets fixed because it consumes less resources.

**Comment by tissole** [comment]
Not fixed.
