### ISSUE TITLE
Can't open bot's web app menu

### ISSUE THREAD

**Issue by amirrh6** [telegramdesktop/tdesktop#24356]
### Steps to reproduce

Start [DurgerKingBot](https://t.me/durgerkingbot) and click on `Order Food` button.

### Expected behaviour

Bot's web app menu should be displayed!

### Actual behaviour

Following dialog is displayed:

"Unfortunately, you can't open such menu with current system configuration. ..."

![image](https://user-images.githubusercontent.com/65363030/163706262-e5abeb4a-56b6-4cd6-86eb-e3fe6234f3e1.png)

### Operating system

Linux Mint 20.3 Cinnamon

### Version of Telegram Desktop

3.7.0

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Yeah, sorry, but as the message says, you can't use web bots :(

You need change your DE to one that doesn't uses mutter (or a fork of mutter) as its WM (i.e. anything what is not a GNOME fork).

**Comment by amirrh6** [comment]
@ilya-fedin Oh I see. So the only workaround is changing the DE.
I am using Linux Mint, Would you mind suggesting a well known alternative DE?

**Comment by ilya-fedin** [comment]
KDE

**Comment by rtix** [comment]
Well, I don't see even that message. Using snap package, i3wm, Fedora 34.
![1650187519](https://user-images.githubusercontent.com/28888263/163708623-eab0692f-ef7c-4aad-bb59-034372b56916.png)
![1650187555](https://user-images.githubusercontent.com/28888263/163708626-a1870a5f-64f5-4b0b-b962-c2c1e666ade0.png)

**Comment by ilya-fedin** [comment]
@rtix well, it's not 'even', you went further

**Comment by rtix** [comment]
I mean I don't see "Unfortunately, you can't open such menu with current system configuration."(`"lng_bot_no_webview"`)

**Comment by ilya-fedin** [comment]
Well, because you can (so it launched webview for you when it doesn't even try in @amirrh6), but it seems snap package doesn't have all the needed dependencies

**Comment by rtix** [comment]
Oh, now I get it. Thank you!

**Comment by erfanium** [comment]
@ilya-fedin As Ubuntu (that uses Gnome WM) is the most popular linux based OS, most of Linux users will face this problem.
Is there any plan to fix it?

**Comment by ilya-fedin** [comment]
> Is there any plan to fix it?

not I or @john-preston have any idea how to fix this, so unless someone else would help with that, it's unlikely to be fixed
