### ISSUE TITLE
Anti-SpyBots "Are You Human?" [Request] 

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#24352]
### Is your feature request related to a problem?

since millions of people flee Western BigTech,
millions closed WhatsApp, FB, TW, IG, Google accounts.
millions use anonymous front-end websites to surf/see those networks:
nitter.net, invidious.io, gramhir.com, loader.to, etc...
millions disable spell check, 
since millions disable cookies, personalized ads, do Not track, usage statistics... 
and some even use VPN Not in the 14.-eyes,

there is a flood, a tsunami of SpyBots on Telegram,
designed to listen everything you say,
and try to phish you, 
suggesting fake Channels,
like Fake RT News Channel, 
fake famous politicians, 
fake popular social personality.
even the same channel but fake 
"decoy fake channels"

Not all Bots are Spyware,
some are very useful,
like Yandex 360 Mail,
translate.Yandex
twitter image/video downloader bots. "evidence bots"

but there is too much Spy / Phishing Bots on Telegram.
example:
in a channel about Ukraine / Russia War,
created by well known reporter in Australia, Not affiliated with Main Stream Media.
if i write "Key words" like:
vaccines,
vaccination,
doses

Bots jump in to conversation.
there are bots that try to fake the channel owner, 

all im asking, is that:
there should be a way to stop spy bots.
and fake decoy bots.

ALSO official / verified channels should have a unique Icon / Badge... Next to the Name.
https://support.opensea.io/hc/en-us/articles/4415562648851-How-do-I-set-my-NFT-as-my-Twitter-profile-picture-
https://www.coindesk.com/business/2022/01/20/twitter-launches-nft-profile-picture-verification/

### Describe the solution you'd like

create are you human anti-bot capcha.
yandex.cpm has it...
Telegram is missing that.

### Describe alternatives you've considered

move to the farm, forget about technology.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by juanpc2018** [comment]
is Not a Bug,
is a Feature enhancement request.

**Comment by 23rd** [comment]
https://suggestions.telegram.org/
