### ISSUE TITLE
No context menu on some messages with Wayland and 2 screens with different resolutions.

### ISSUE THREAD

**Issue by Lorak-mmk** [telegramdesktop/tdesktop#24350]
### Steps to reproduce

My setup: Fedora 35 with Sway (wayland), 2 screens, one is 1920x1080, other is 2560x1440.
1. Launch Telegram on a bigger screen.
2. Messages near the bottom of the screen can't be right-clicked.

I suspect that it doesn't work when clicking more than 1080 pixels from top of screen - meaning that Telegram uses dimensions of other screen.
Everything is displayed correctly, only right-clicking is affected.
Besides Flatpak version, I also tested this with official binary.

### Expected behaviour

Context menu shows up when clicking message near bottom of the screen.

### Actual behaviour

Nothing happens.

### Operating system

Fedora 35, Sway 1.7

### Version of Telegram Desktop

3.6.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Can you check the beta version?

**Comment by Lorak-mmk** [comment]
Beta fixes this issue, thanks! It however introduced another one: mouse cursor becomes bigger than normal when it is over Telegram window.

**Comment by ilya-fedin** [comment]
It's not a new issue, it's always was like that since GNOME doesn't set cursor theme/size for non-gtk applications

**Comment by ilya-fedin** [comment]
Ah, you're using sway. I dunno, then. Maybe it does. I don't use sway.

**Comment by Lorak-mmk** [comment]
Should I open a new issue about cursor problem?

**Comment by ilya-fedin** [comment]
I don't think I would be able to help you with that, it's Qt who handles the cursor. It has sense for you to check other Qt applications with Qt 6.3 and report to Qt directly.

**Comment by Lorak-mmk** [comment]
Never mind, this is a non-issue - setting XCURSOR_SIZE to proper value fixes the issue, sorry. So thanks again for help, I'll be waiting for the new release.
