### ISSUE TITLE
version `GLIBC_2.33' not found after system update

### ISSUE THREAD

**Issue by 11Firefox11** [telegramdesktop/tdesktop#24355]
### Steps to reproduce

1. Start telegram-desktop

### Expected behaviour

App starts

### Actual behaviour

Terminal says it can't find GLIBC_2.33, see Logs for more info.

I refreshed my system yesterday with `pacman -Syu`, now I can't start telegram.
My glibc version is 2.35-3.
Telegram//snap did not set the GLIBC version to 2.35? 
I tried to downgrade glibc to 2.33 but other apps use 2.35 already.
Maybe it will be just a full system runback before I updated my packages...

### Operating system

Garuda Linux

### Version of Telegram Desktop

3.7.0

### Installation source

Snap

### Logs

```shell
telegram-desktop: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
```

**Comment by ilya-fedin** [comment]
Looks like you have old snapd version that has a bug with nvidia drivers

**Comment by 11Firefox11** [comment]
Always those nvidia drivers...
How should I update it then?
I tried `snap refresh snapd` but it wrote it has no updates.

**Comment by 11Firefox11** [comment]
My snapd version is `2.53.1-1`

**Comment by ilya-fedin** [comment]
Latest version seem to be 2.55.3

**Comment by 11Firefox11** [comment]
It is very interesting beacause `snap list` writes that `snapd` has version of `2.54.4` but snap `version` writes `2.53.1-1`.
How should I update if refresh does not work?

**Comment by ilya-fedin** [comment]
AFAIK snap can update itself only on Ubuntu

**Comment by 11Firefox11** [comment]
Hm...so now I am stuck here.

**Comment by 11Firefox11** [comment]
I am just going to delete it and download it from [archlinux.org](https://archlinux.org/packages/community/x86_64/telegram-desktop/) 
Thanks for the help!

**Comment by ilya-fedin** [comment]
I recommend to use the static build from https://desktop.telegram.org. It has first-class support and updates faster than anything else.

**Comment by 11Firefox11** [comment]
Nice. I downloaded just the executable, now everything is great.
Thanks.
