### ISSUE TITLE
Green dot for users which are online

### ISSUE THREAD

**Issue by devianpctek** [telegramdesktop/tdesktop#2435]
Please add a marker on the contact screen when contacts are online, take for example Plus messenger, it has a green dot in front of the contact and different shades of grey depending on when a contact has been online.

**Comment by daslicht** [comment]
When I disable Notifications for a channel , I still get the message count  shown on the dock icon under osx. It would be great if we only get notified when someone mentioned us,

**Comment by stek29** [comment]
@devianpctek Can you please change title to something like "Green dot for users which are online", so people can understand what's the issue about without opening the description?

@daslicht Settings -> Include muted chats in unread count

**Comment by arieljannai** [comment]
+5 !

**Comment by Aokromes** [comment]
Alternative added (online text)

**Comment by stek29** [comment]
There's no reliable way to keep track of users' status unless they're in your contact list without polling server all the time, so it's also an API issue.

**Comment by arieljannai** [comment]
@stek29 As I also wanted this feature (and this is how I found it), I can tell what are the things that are important to me in this feature, and maybe it could help. From the most important to less:

1. **Contacts status** - related to what you've said:
> There's no reliable way to keep track of users' status unless they're in your contact list without polling server all the time, so it's also an API issue.
2. **Bots status** - are they alive? (I know it might be a bit different from the regular users' behavior)
* There are too many offline/inactive bots and it's pretty frustrating to check multiple bots just to discover they're not working.
3. **All users status** - personally for me it's not really important.

**Comment by tooomm** [comment]
This is now available on Android and iOS, and it's awesome.
Please consider adding to Telegram Desktop as well!

**Comment by 23rd** [comment]
Fixed in 1.7.8.
