### ISSUE TITLE
[Feature Request] Sending the default reaction by a double click only if reply is not allowed and separation of this setting for channels and chats

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#24353]
### Is your feature request related to a problem?

I want to send reaction by a double click only in chats where I can't reply.

### Describe the solution you'd like

Separate this new setting for chats and channels or detect automatically can user reply in this chat\channel or no

### Describe alternatives you've considered

No

**Comment by Alirezaaraby** [comment]
related to #23920
