### ISSUE TITLE
Qt-6.3.0 completely breaks fullscreen view

### ISSUE THREAD

**Issue by cyberpunkrocker-zero** [telegramdesktop/tdesktop#24365]
Distribution: Arch Linux
Tested with: telegram-desktop-3.6.1 and 3.7.0 (Arch builds) and the official static binary 3.7.0

I'm using a dual-monitor setup with the secondary monitor in a portrait mode. That secondary monitor is also where I run Telegram. So far the fullscreen view of photos and videos has worked reasonably well, but the recent qt6 update to version 6.3.0 broke it completely. I've included screenshots of the secondary monitor here:

First, that's how it looked with telegram-desktop-3.6.1 https://ibb.co/xJc05NT
There is two fullscreen-views (kind of) on top of each other, the correct portrait-oriented at the bottom and on top of it another oriented like the primary landscape-mode monitor.

Today, telegram-desktop-3.7.0 was released and its fullscreen view was even more broken. Here's how its idea of 'fullscreen' looks https://ibb.co/pJ61Y1Q
There's still two views on top of each other, but now both are in the (wrong!) landscape-mode. This is equally broken on both the Arch build of 3.7.0 and the official Linux binary of 3.7.0

**Comment by ilya-fedin** [comment]
I don't quite understand what you expect by opening issue here if you know that the bug is in Qt.

**Comment by cyberpunkrocker-zero** [comment]
I really did NOT know whether the issue is with Qt or Telegram, all I knew that they do not like each other. But OK, I'll report this issue to Qt people, then. Thanks anyway.

**Comment by ilya-fedin** [comment]
I think you have problems due to their new code for xrandr 1.5 support and I think they already fixed this on dev branch (I see some commits about screen orientation at least)
