### ISSUE TITLE
Application randomly crashing after opening video after last update

### ISSUE THREAD

**Issue by spookyrecharge** [telegramdesktop/tdesktop#24366]
### Steps to reproduce

1. Open any videofile in chat or public group
2. **SOMETIMES VIDEO BECOME PINK** like there is another layer of color on top of it

_notes:_ 
no additional software/drivers were installed/updated for a long time
it started right after the update this week

so I think there is a problem with a software itself

### Expected behaviour

View a video and enjoy it

### Actual behaviour

Telegram crashing randomly
It is not tied to the specific video, after crashing the same video may play normally, and another can cause a crash

### Operating system

Windows 10 20H2 19042.1466

### Version of Telegram Desktop

3.7

### Installation source

Static binary from official website

### Logs

```shell
windows event viewer

Faulting application name: Telegram.exe, version: 3.7.0.0, time stamp: 0x625afac3
Faulting module name: Telegram.exe, version: 3.7.0.0, time stamp: 0x625afac3
Exception code: 0xc0000005
Fault offset: 0x00123639
Faulting process id: 0x4950
Faulting application start time: 0x01d852828f53e137
Faulting application path: C:\Users\spook\AppData\Roaming\Telegram Desktop\Telegram.exe
Faulting module path: C:\Users\spook\AppData\Roaming\Telegram Desktop\Telegram.exe
Report Id: 56305a22-7968-490b-bfee-7884bc383118
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Clone of #24360 and #24345.

**Comment by spookyrecharge** [comment]
> plz enable beta, restart telegram and send crash id on next start and post id here.

ApiId: 2040
Binary: Telegram.exe
Launched: 20.04.2022 11:56:34
OpenGL ANGLE: OpenGL
OpenGL Renderer: [not-initialized]
Platform: Windows32Bit
UserTag: 50a58ec4f13ec489
Version: 3007000
Memory-usage: 2891 MB (peak), 2880 MB (current)
Pagefile-usage: 3227 MB (peak), 3215 MB (current)

Google Breakpad caught a crash, minidump written in thread 13068
Minidump: 80486d16-c094-4460-9a40-6304e535a425

Backtrace omitted.

Caught signal 22 (SIGABRT) in thread 13284

Backtrace omitted.
