### ISSUE TITLE
Cursor not visible in WebApps input text fields

### ISSUE THREAD

**Issue by brailateo** [telegramdesktop/tdesktop#24362]
### Steps to reproduce

Write a simple WebApp with a <input type="text">
Run WebApp from a KeyboardButton
Click on that input
No caret present, cursor not visible thought text appears

### Expected behaviour

cursor should blink in input fields  (tried on Android version the same WebApp and cursor is visible)

### Actual behaviour

characters are entered but we don't see where the cursor is

### Operating system

Ubuntu Mate Linux 20.04 64 bit

### Version of Telegram Desktop

3.7

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@brailateo Yes, valid report. I don't know, how to fix that :(

**Comment by ilya-fedin** [comment]
This issue is now a part of #25126

**Comment by slavafomin** [comment]
I'm having the same problem on:
`Ubuntu 22.04.1 LTS, Linux 5.15.10-051510-generic, XFCE 4.16`
