### ISSUE TITLE
Two people can have the same @username breaking the identity verification most people do

### ISSUE THREAD

**Issue by michaelmoebryan** [telegramdesktop/tdesktop#24369]
### Steps to reproduce

Steps to reproduce
I have come across an account with different telegram id and the exact same @username
clicking on the fake profiles link to their own name switches you to the real one
clicking message on the fake profile links to the real one
dm me for details if this is a novel issue and you need specific personal info

### Expected behaviour

Expected behaviour
user should not be able to use the same @username as anyone else

### Actual behaviour

Actual behaviour
Two people share the same username

### Operating system

 Operating system Macos, 12.0.1

### Version of Telegram Desktop

telegram desktop

### Installation source

Mac App Store

**Comment by michaelmoebryan** [comment]
this is a network issue its the same on any client.

**Comment by 23rd** [comment]
https://bugs.telegram.org

**Comment by Aokromes** [comment]
very likely you found someone using i I l not a bug.

**Comment by michaelmoebryan** [comment]
Its not an I bug - I found out they were not setting a username and putting the @username in profile text - it looks so simiilar to the regular screen i think it would be wise to change the layout or colour so they know whether the @name in their profile is there username and clearly distinguish profile bios so they dont look so similar

**Comment by michaelmoebryan** [comment]
![IMG_0911](https://user-images.githubusercontent.com/18048770/163779641-c91c774a-9a2f-49c7-b0f8-b8ffdd4f90dc.jpg)
![IMG_0913](https://user-images.githubusercontent.com/18048770/163780131-206c46d0-60a2-4fec-aff6-5d28b7d00989.jpg)
