### ISSUE TITLE
It is possible for two people to have the same telegram username

### ISSUE THREAD

**Issue by michaelmoebryan** [telegramdesktop/tdesktop#24368]
### Steps to reproduce

- I have come across an account with different telegram id and the exact same @username 
- clicking on the fake profiles link to their own name switches you to the real one
- clicking message on the fake profile links to the real one
- dm me for details if this is a novel issue and you need specific personal info

### Expected behaviour

user should not be able to use the same @username as anyone else

### Actual behaviour

Two people share the same username

### Operating system

Macos, 12.0.1

### Version of Telegram Desktop

8.6.228674 Stable

### Installation source

Static binary from official website

**Comment by michaelmoebryan** [comment]
This is a network issue not a client issue. Where should I contact to report the bug?
'

**Comment by RememberTheAir** [comment]
you can report it on https://bugs.telegram.org
