### ISSUE TITLE
Problem with contacts which have accent marks

### ISSUE THREAD

**Issue by braisCouce** [telegramdesktop/tdesktop#2436]
### Steps to reproduce
1. Add a contact with an accent mark in the first letter of the contact name.
2. Open contact list.
3. You can see that the contact is shown at the end of the list.
### Expected behaviour

The accent mark should not affect to the contact position on the list.
### Actual behaviour

Using the webapp and the desktop version the contact is shown at the end of the list. With the Android app the problem does not appear.
### Configuration

**Operating system:**

Ubuntu and Windows

**Version of Telegram Desktop:**

0.10.1

**Comment by Aokromes** [comment]
#2014

**Comment by Aokromes** [comment]
maybe https://stackoverflow.com/questions/35061496/orderby-ignoring-accented-letters can help someone to fix this bug.

**Comment by braisCouce** [comment]
Hi, the issue is still present.
