### ISSUE TITLE
Frequent Telegram Desktop Crash when returning string results from WebApp

### ISSUE THREAD

**Issue by brailateo** [telegramdesktop/tdesktop#24363]
### Steps to reproduce

Design a simple WebApp that will be run from a KeyboardButton
Return a simple string value from WebApp with sendData("something")
Telegram crash in 2 of 5 cases (the robot, written in Go has no problem, continues working)

### Expected behaviour

not crashing

### Actual behaviour

Telegram crash in 2 of 5 cases 

### Operating system

Ubuntu Linux Mate 20.04 64 bit

### Version of Telegram Desktop

3.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Enable installation of beta version, trigger the crash, you should get crash reporter on next launch, copy "Your Report Tag" value (don't confuse with user tag!) send the crash report and paste the tag here

**Comment by brailateo** [comment]
I'm always testing with beta versions enabled, I have already sent crash reports on this bug!

**Comment by brailateo** [comment]
Your Report Tag: 82d1eac4-70f6-4579-000406a2-8149bc7e
Your User Tag: 846d377418a92451

**Comment by john-preston** [comment]
@brailateo Can you please provide a sample bot for me so that I can crash it myself? Because the official test bots don't crash for me on KDE over Ubuntu 20.04. You can contact me at https://t.me/preston to provide the sample.

**Comment by brailateo** [comment]
Seems that it doesn't crash on other machines (Kubuntu, Linux Mint).
I'll close the issue for the moment and will repeat the tests on a fresh Ubuntu Mate 22.04 install!

**Comment by netbriler** [comment]
## Telegram.WebApp.sendData() not working on windows 

Test bot https://t.me/brilerbot `/web_app_test` - to get web app menu
Source code https://github.com/netbriler/aiogram-sqlalchemy-template/blob/master/web_app_echo.html#L248

It works on android 11 but not on windows 10 Pro 64 bit 21H2

<img src="https://i.imgur.com/1EwbFXI.png"/><img src="https://i.imgur.com/aC2tHzJ.png"/>

**Comment by john-preston** [comment]
@netbriler according to docs this is a bug in Android app:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/17900494/163958190-c2a7f0fd-0896-40f6-890f-d52aad2ed8a8.png">
