### ISSUE TITLE
What to do if a channel is blacklisted?

### ISSUE THREAD

**Issue by machinsoft** [telegramdesktop/tdesktop#24364]
You seem to have a vulnerability in Telegram, the bot adds channels to the black list (shadow ban) automatically.
Fraudsters use methods to cheat views and subscribers who subscribe en masse and then exit en masse.
After that, the channel flies to the ban.
I have not yet understood exactly how it works, but scammers require payment if a person does not want to get banned.
Competitors who are in the top 1-3 and hold search queries also use money to ban someone else's channel through cheating.

I also noticed that some people make empty twisted channels with only one logo.
As I understand it, this was done so that competitors would not wind up views and demolish the channel.
There are whole channel retention schemes, I spoke with a couple of people and was surprised by what they told me.

I want to know, don't you think it's wrong when ordinary people find it difficult to promote their channel honestly?
And even if you promote it, competitors immediately demolish honest channels because they don’t want to see competitors.

**Comment by Aokromes** [comment]
sorry, but, this is a bug tracker for telegram desktop client. not about how platform works.
