### ISSUE TITLE
Chat menu "Mute for ..." does nothing

### ISSUE THREAD

**Issue by brailateo** [telegramdesktop/tdesktop#24361]
### Steps to reproduce

Enter in a chat
Click on ...
Choose "Mute notifications / Mute for ..."
Nothing happens

### Expected behaviour

Should see a dialog for choosing time interval

### Actual behaviour

nothing happens

### Operating system

Ubuntu Mate Linux 20.04 64 bit

### Version of Telegram Desktop

3.7

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Can you check the "Select Sound" menu item? Do you have the same effect for it?

**Comment by brailateo** [comment]
I checked the "Select sound" menu item, nothing happens. I expected some dialog window to appear, but there isn't.
