### ISSUE TITLE
WebApp does not support no-comma colors.

### ISSUE THREAD

**Issue by chipslays** [telegramdesktop/tdesktop#24372]
### Steps to reproduce

I am using Tailwind CSS framework to develop webapp interface.

Faced a problem that the desktop version does not support the color like `color: rgb(34 197 94 / 1)`.

But it works well on Android.

1. Create page:

```html
<style>
    .green-rgb {
        color: rgb(34 197 94 / 1);
    }
    .green-rgba {
        color: rgba(34, 197, 94, 1);
    }
</style>

<p class="green-rgb">
    Hello World
</p>
<p class="green-rgba">
    Hello World
</p>
```

### Expected behaviour

Both texts are expected to be green.

### Actual behaviour

But `rgb(34 197 94 / 1)` not work.

#### Desktop WebApp
![image](https://user-images.githubusercontent.com/19103498/163771366-46954d73-144a-43b9-ae76-7d926df3b48d.png)

#### Android WebApp
![image](https://user-images.githubusercontent.com/19103498/163771678-5524dad8-2e7f-4fbf-b368-d0f0b796a192.png)

### Operating system

Windows 10

### Version of Telegram Desktop

3.7 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop uses system libraries on every platform for web features, so it means web engine of your platform just doesn't support that and you have to adapt to that.
