### ISSUE TITLE
Media is between two displays

### ISSUE THREAD

**Issue by shatll-s** [telegramdesktop/tdesktop#24371]
### Steps to reproduce

1. Click on media

### Expected behaviour

Media viewer is located on same display with main window

### Actual behaviour

![Screenshot_20220418_093001](https://user-images.githubusercontent.com/37956983/163765589-c23fc714-3055-4f2f-b9c6-d22b545d644f.png)

Media is located between two displays, no way to move/resize media viewer.

### Operating system

Ubuntu 20.04

### Version of Telegram Desktop

3.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#24218
