### ISSUE TITLE
Move to an emoji set that's current with the spec

### ISSUE THREAD

**Issue by chrjguill** [telegramdesktop/tdesktop#2437]
Currently, Telegram uses Apple's emoji set for its emoji across all platforms. However, they're currently rather behind spec (there's several emojis from the unicode 9 missing from the iOS 10 release, with no apparent plans to add them, since they've already done the rest of their redesign).

An alternative would be to use something like [twemoji](https://github.com/twitter/twemoji), which is currently up to spec and, additionally, is open source, unlike Apple's emojis. 
- This has several benefits over using Apple's emoji, one of which being not tied to a proprietary solution which can be unreliable for updates, as it is currently.
- It supports the skin color things, unlike Android
- It can be used across _all_ of telegram's clients, which will maintain its uniform look

**Comment by Peque** [comment]
I would rather propose [Emoji One](http://emojione.com/) instead. :stuck_out_tongue_winking_eye:

**Comment by chrjguill** [comment]
Which solution is used is more stylistic and depends on what the Telegram devs go with (ideally, I'd like to see options like twemoji/emoji one/system, with apple being officially dropped - it's not great for a messaging app to stick to an emoji set that lags behind the standards).

**Comment by chrjguill** [comment]
The september 23rd update for telegram mobile brought it to have the iOS 10 emojis. This is kinda bad for a handful of reasons (one of which being that now the desktop and mobile clients are now using different emoji sets).

I still think moving to an open-source and platform independent emoji set would be the best for telegram in the long run for the aforementioned reasons.

**Comment by john-preston** [comment]
@chrjguill Telegram Desktop anyway will stick to mobile apps in the emoji set. So currently it should catch up with iOS 10.

**Comment by chrjguill** [comment]
Why stick to iOS 10 emojis at all, though? Forcing users across platforms to use one platform's emojis is the opposite of consistent UI across platforms. A third-party, platform independent emoji set would be better for keeping telegram's look and feel consistent independent of platforms.

**Comment by john-preston** [comment]
@chrjguill Well, looks like the iOS app was the first one who got any emoji support at all (and the first one that was released), so all other apps (including tdesktop) should provide consistent experience across all the platforms, using the emoji set that is currently in production. I have nothing to do with iOS app, but I can't use any other emoji set, because it will be inconsistent with other Telegram apps.

**Comment by Peque** [comment]
@chrjguill Would it be hard to implement this as an option? (i.e.: leave Apple emojis by default, but let the user switch to another set if the prefer so).

**Comment by chrjguill** [comment]
No idea, but there'd be problems arising from the iOS 10 emoji set not including some parts of the Unicode 9 specs ([this](http://emojipedia.org/fox-face/) being one of them, among another handful). Some people could end up sending emojis that are part of the spec and are in other sets, but aren't in the iOS 10 set.

I find it rather odd that a messaging service uses an emoji set that's both proprietary, and is missing emojis from the spec.

**Comment by Peque** [comment]
@chrjguill Sorry, when I wrote:

> @chrjguill Would it be hard to implement this as an option? (i.e.: leave Apple emojis by default, but let the user switch to another set if they prefer so).

 I wanted to write "@john-preston"... :sweat_smile:

**Comment by z3ntu** [comment]
I am also for the option (if possible) to manually switch to other emoji pack(s).

**Comment by phaux** [comment]
I don't care which set we will use. I just need the fox emoji because reasons.

**Comment by chrjguill** [comment]
>I don't care which set we will use. I just need the fox emoji because reasons.

Same actually, it kinda matters to me for reasons

**Comment by chrjguill** [comment]
Update: Apple's latest iOS dev seed has the rest of the Unicode 9 [emojis](http://blog.emojipedia.org/ios-10-2-emoji-first-look-shrug-fingers-crossed-face-palm/). They'll probably tweak some of the emojis before finalizing the build, but it'll be nice to finally be on an emoji set thats current, even if it's like 5-6 months late.

(_Windows_ has had most or all of the Unicode 9 emojis since the Linux subsystem update in mid/late May, iirc)

**Comment by flippinger** [comment]
Emojis differ wildly between platforms, for example this one:
![sketch](https://cloud.githubusercontent.com/assets/3148313/19907855/ec8e4f9a-a080-11e6-886f-d901590d6c6d.png)
For me, the two versions have a completely different meaning.

**Comment by chrjguill** [comment]
Note: this includes the iOS 10 emoji set now, since that's being used in the Android version of the client now. Kinda surprised that updating the emojis wasn't included in the 1.0 release...

**Comment by john-preston** [comment]
@chrjguill Yes, I didn't manage to update them :(

**Comment by chrjguill** [comment]
It happens ❤️

**Comment by john-preston** [comment]
@chrjguill I personally don't like the new apple emoji, I like the old ones, so I delayed the iOS 10 emoji as long as I could 😭

**Comment by z3ntu** [comment]
I don't like the Apple Emojis at all but consistency is still important...

**Comment by Bustycat** [comment]
The outdated Emoji set is the only reason why I do not use Telegram Desktop on my macOS.
