### ISSUE TITLE
Telegram aborted with multiscreen desktop on linux

### ISSUE THREAD

**Issue by stanislavvv** [telegramdesktop/tdesktop#24377]
I have two different videocards on workstation (intel + nvidia) and join its into one big screen by Xinerama.
After last update (3.7.0) i see this at Telegram launch:

stas@stas:~$ bin/Telegram/Telegram 
QXcbConnection: no screens available
Aborted

Try previous v 3.6.3 - same result. Rollback to 3.6.1 helps

**Comment by ilya-fedin** [comment]
Qt regression, apparently...

**Comment by ilya-fedin** [comment]
Ah, you say Xinerama. I saw Qt removed support for Xinerama. So you can't use tdesktop anymore without migrating to xrandr.

**Comment by ilya-fedin** [comment]
@stanislavvv if you want to test, there's a Qt patch backported from their gerrit on current tdesktop dev branch, so you can try to build tdesktop from dev branch and if it starts (it wouldn't work correctly with your screens, though), I'll report back at https://bugreports.qt.io/browse/QTBUG-102637 and they should merge the fix faster

**Comment by ilya-fedin** [comment]
@stanislavvv ping?

**Comment by stanislavvv** [comment]
> @stanislavvv ping?

Sorry for waiting.
I can't build any desktop app now, but 3.7.3 work fine for me.

I think. issue may be closed.
