### ISSUE TITLE
Build error with KWayland 5.94

### ISSUE THREAD

**Issue by K900** [telegramdesktop/tdesktop#24375]
### Steps to reproduce

1. Have KWayland 5.94
2. Try building tdesktop

### Expected behaviour

Build is fine

### Actual behaviour

Build is not fine: https://invent.kde.org/frameworks/kwayland/-/commit/de442e4a94e249a29cf2e005db8e0a5e4a6a13ed relocated the headers, so `#include <connection_thread.h>` etc. no longer works - it should be `#include <KWayland/Client/connection_thread.h>`, which works with both older and newer versions.

### Operating system

NixOS 22.05-unstable

### Version of Telegram Desktop

master

### Installation source

Other (unofficial) source

**Comment by K900** [comment]
A fix would look something like: https://github.com/NixOS/nixpkgs/blob/a77406f1f203da1c423adb25ea48fea634a206ef/pkgs/applications/networking/instant-messengers/telegram/tdesktop/kf594.diff

But it's spread out over a lot of submodules.

**Comment by ilya-fedin** [comment]
Oh, well, it's non-trivial as we use the bundled version without installation and directory layout is completely another in sources: https://github.com/desktop-app/cmake_helpers/blob/8ca7ff848477ccd8687a5ed0fe3dabf1070f7726/external/kwayland/CMakeLists.txt#L101-L105

But building with Qt 5 is no longer supported anymore anyway and Qt 6 build allows to use only the bundled version, so I think it's a non-issue actually.

**Comment by K900** [comment]
Unfortunately we're stuck on Qt5 in Nixpkgs for now...

**Comment by ilya-fedin** [comment]
Then you can't build new tdesktop releases anymore, sorry :(

**Comment by K900** [comment]
Yeah, I'll try and poke people to get Qt6 merged and I guess we'll have to keep the patch for now.

**Comment by ilya-fedin** [comment]
Even with that patch tdesktop won't build with Qt 5.

**Comment by K900** [comment]
Version 3.6.0 will, which is what nixpkgs currently has.

**Comment by ilya-fedin** [comment]
yeah, 3.6.0 definitely will
