### ISSUE TITLE
How to debug Web Apps for Bots?

### ISSUE THREAD

**Issue by polRk** [telegramdesktop/tdesktop#24389]
I want to debug my app, but i don't know how. And the next question is do telegram web app support http urls (localhost) or ips 127.0.0.1 ?

**Comment by WINOFFRG** [comment]
Upvote! It is very difficult to debug WebApps ! We need to close and reopen the window! 
**Change needed or recommended:** 

1. Custom User-Agent 
2. No Support for DevTools or any other way to Debug.
3. Prevent other bots from accessing our site.
4. Missing Reload button on Desktop Devices
5. Missing Float Window on top of screen feature.
6. Integrated Back Button in Title Bar

**Comment by polRk** [comment]
> Prevent other bots from accessing our site.

Yes, telegram should add CSRF Token, generate base on bot token and user id,

**Comment by samarets** [comment]
I fully agree with all of the above. I also support the @WINOFFRG, and in particular regarding the back button, DevTools and the refresh button (but ctrl + r works)

**Comment by Aokromes** [comment]
i think such request must be done platform wide on https://bugs.telegram.org instead here

**Comment by WINOFFRG** [comment]
Hey @Aokromes ! I dont think that site is still accepting issues or request. Even I see last issue created somewhere around 2021.

**Comment by Aokromes** [comment]
> Hey @Aokromes ! I dont think that site is still accepting issues or request. Even I see last issue created somewhere around 2021.

https://i.imgur.com/YK2KYcQ.png

**Comment by john-preston** [comment]
@polRk @WINOFFRG @samarets Please try beta version 3.7.4, it should have a new option in Settings > Advanced > Experimental > Enable webview inspecting (it should work on Windows with new Edge and on Linux) with right click -> Inspect.
