### ISSUE TITLE
Memory leak, nvidia 510 drivers,RTX 3070

### ISSUE THREAD

**Issue by AMV007** [telegramdesktop/tdesktop#24387]
### Steps to reproduce

Look multiple videos with telegram.

### Expected behaviour

memory freeing after every video finish

### Actual behaviour

in result all GPU memory (8 Gb) are in use by telegram

### Operating system

Ubuntu 20.04

### Version of Telegram Desktop

3.7

### Installation source

Static binary from official website

**Comment by kr-ilya** [comment]
Same problem.
After watching the video
![image](https://user-images.githubusercontent.com/42733472/163972182-046f1280-9aea-40fb-8877-e08a5e42777e.png)
After closing the telegram
![image](https://user-images.githubusercontent.com/42733472/163972363-38ab3fb6-4d69-403d-87ca-e568fe24cdab.png)

Nvidia GTX 1050. Windows 10. Telegram v3.7.0

**Comment by Akkihi** [comment]
Try disabling hardware accelerated video decoding.
 I ran into this on an amd rx 570
![image](https://user-images.githubusercontent.com/31794830/163976790-af36f91b-77ea-46a6-ae3a-cb55ee13955f.png)

**Comment by kr-ilya** [comment]
> Try disabling hardware accelerated video decoding. I ran into this on an amd rx 570 ![image](https://user-images.githubusercontent.com/31794830/163976790-af36f91b-77ea-46a6-ae3a-cb55ee13955f.png)

Yes, if you turn it off, everything will stabilize. (It's understandable :))
