### ISSUE TITLE
After updating to version 3.7.0 stop playing video

### ISSUE THREAD

**Issue by dmitry-bas** [telegramdesktop/tdesktop#24381]
### Steps to reproduce

1. Play any video

### Expected behaviour

Video playback. Buffering if necessary.

### Actual behaviour

the preview working well, but when I try to enter to video, it does not play, and the play button is not pressed. Only part of the video is not played, as I understand it, it depends on the codec, because in some channels the video plays normally.

### Operating system

MacOS 12.2 on Apple M1 Max

### Version of Telegram Desktop

3.7.0

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Can you provide an example of non-playing video? In a public group / channel?
