### ISSUE TITLE
[Feature Request] Silent Messages in Any Type of a Chat

### ISSUE THREAD

**Issue by dshcherb** [telegramdesktop/tdesktop#2438]
Hi,

When you are sending a message to somebody, sometimes it is more convenient to send a silent message as you may be completely sure that the person is sleeping, busy or otherwise does not want to get an audible notification from anybody.

Right now this is only implemented in channels and only for a publisher of a channel.
https://telegram.org/blog/channels-2-0#silent-messages

Please add a support for silent messages everywhere.

Thanks,
D.

**Comment by chrjguill** [comment]
I feel like it should be up to the person who's receiving messages to do that, and not give the option to those sending them.

**Comment by auchri** [comment]
This has nothing to do with Telegram Desktop btw.
