### ISSUE TITLE
Telegram Desktop auto-update?

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#2439]
Dear all, 

I installed Telegram Desktop for my older family members.

They don't pay attention and don't notice the `Update` notification.

Can we think of adding an auto-update for older people?

Warmly,

-Robert

![photo488502386633058268](https://cloud.githubusercontent.com/assets/170947/18617492/ef20d430-7dd0-11e6-9a46-c09761a014cf.jpg)

**Comment by auchri** [comment]
It get's updated when you start Telegram the next time.

**Comment by orschiro** [comment]
That's useful to know. 

Thank you!

-Robert
