### ISSUE TITLE
[Feature Request] Save files/contents of a channel or group to corresponding sub folders

### ISSUE THREAD

**Issue by shines99** [telegramdesktop/tdesktop#24393]
### Is your feature request related to a problem?

In telegram desktop, the contents of a group or channel are stored/downloaded to a single folder.
With multiple groups and channels, the files are ever increasing and not organized.

### Describe the solution you'd like

it would be good, if the files downloaded automatically or manually are saves to a subfolder with the channel/group name by default.

### Describe alternatives you've considered

had to manually export chat history/files to specific folder for each group/channel

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5788
