### ISSUE TITLE
automatically adding a channel to the black list by changing the title

### ISSUE THREAD

**Issue by machinsoft** [telegramdesktop/tdesktop#24392]
### Steps to reproduce

1. Create a channel or chat
2. Change the name of the channels as long as possible and with different characters
3. Exit and return to telegram

If you can't repeat it, try the web version, there you can make more characters in the channel name.
https://web.telegram.org/

### Expected behaviour

nothing will happen

### Actual behaviour

The channel is blacklisted :)

### Operating system

Windows 10 or web version

### Version of Telegram Desktop

v 3.7

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
this looks more api than telegram clients.

**Comment by machinsoft** [comment]
@Aokromes Then I suggest closing it or redirecting where they are working with api

**Comment by RememberTheAir** [comment]
The correct place is httsp://bugs.telegram.org

**Comment by tgdesktop** [comment]
Where to write if I received a shadowban that was made automatically.
At the moment, I think that telegrams do not treat users correctly enough, this is of course their right to ban everyone.
But after such a ban, people will leave and will no longer create channels or chats, especially if there is no support, and at the moment there is none.
Honestly, I accidentally banned my chat and channel, and the support does not even respond.
