### ISSUE TITLE
malicious sticker pack?

### ISSUE THREAD

**Issue by VaGNaroK** [telegramdesktop/tdesktop#24395]
### Steps to reproduce

Using telegram pc click on sticker pack link. https://t.me/addstickers/totallynormalvideostickers
wait a few seconds...
see telegram crash and soon the pc becomes inaccessible (at least here)

### Expected behaviour

application and computer crash (probably)

### Actual behaviour

crash

### Operating system

win10x64

### Version of Telegram Desktop

Telegram Desktop v3.7 x64

### Installation source

Static binary from official website

**Comment by c0re100** [comment]
It need to fixed by ffmpeg.

**Comment by VaGNaroK** [comment]
> It need to fixed by ffmpeg.

Thanks for the reply, is there any plan to fix this?

**Comment by Neurotoxin001** [comment]
This shit is crashing iOS telegram too.

![image](https://user-images.githubusercontent.com/39812401/164215000-10347786-efcc-4928-b816-64f379131892.png)

**Comment by Quuake** [comment]
On Windows 11, just a collapse of telegrams and that's it. the system has apparently prevented code execution on the system. Does not work as stated. Apparently so only 10 windows there is a vulnerability

**Comment by john-preston** [comment]
@Quuake There is no some vulnerable code execution, it just eats up RAM, lots of it.

**Comment by allenrosed** [comment]
> @Quuake There is no some vulnerable code execution, it just eats up RAM, lots of it.

How did you know? That webm
```
sha256 94fe79d61132d994dd098a9ca5258baa007f5e0c6fc48dd8a508f3397befb1bc
```
is 236 KiB in size, while ~1.2 KiB LZMA compressed, not much like usual video. I found two distinct frames, total ~300 bytes of storage.

**Comment by OverShifted** [comment]
@allenrosed Without compression, each frame takes about 600MB and each sticker takes about 27GB.
Each frame is a fully red 15000x1500 image. So it can be compressed a lot, but takes a lot of storage if stored uncompressed.

**Comment by allenrosed** [comment]
@OverShifted
My point was about abnormal compression rate for already compressed webm/vp9, not about memory to store raw frames.
How did you come up with 15000x15000 or 1500x1500 or maybe 15000x1500? I see 512x512, entire raw video costs about 90 MiB for rgb24.

**Comment by OverShifted** [comment]
@allenrosed I found the dimension using my browser's inspector (on the Webk client).
I found the same dimension after using the "Export chat history" item. (which saved the sticker as a video file)
