### ISSUE TITLE
[Question] Building based on instructions fails

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#24397]
I'm trying to build on Linux based on these instructions: https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md

I built the dedicated docker image: `docker build -t tdesktop:centos_env Telegram/build/docker/centos_env/`

And then ran:

```
docker run --rm -it \
    -v $PWD:/usr/src/tdesktop \
    tdesktop:centos_env \
    /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
    -D TDESKTOP_API_ID=17349 \
    -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb \
    -D DESKTOP_APP_USE_PACKAGED=OFF \
    -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF
```

This failed with error:

```
Traceback (most recent call last):
  File "/usr/src/tdesktop/Telegram/configure.py", line 13, in <module>
    import run_cmake
ImportError: No module named run_cmake
Error: /usr/src/tdesktop/out is not a directory
```

Maybe the instructions are out of date? I can't imagine anything in my local env would mess this up, given that it's built inside a container.

**Comment by 23rd** [comment]
> git clone **--recursive** https://github.com/telegramdesktop/tdesktop.git

**Comment by WhyNotHugo** [comment]
Oh, I though I'd replied and closed this.

Thanks for the pointer. I'd cloned many months ago and never noticed I was missing the submodules.
