### ISSUE TITLE
Problems with sending data via sendData() in Web Apps

### ISSUE THREAD

**Issue by haabbaah** [telegramdesktop/tdesktop#24390]
### Steps to reproduce

For example, we send such data on the frontend:
```
const data = {
    type: 'counter',
    counter: 1,
}
window.Telegram.WebApp.sendData(JSON.stringify(data))
```

### Expected behaviour

On the backend, we expect the object that is specified in the documentation [Link](https://core.telegram.org/bots/api#webappdata)

### Actual behaviour

From Android such data comes to web_app_data:
```
...message.web_app_data {
  button_text: 'Button Name',
  data: '{"data":"{\\"type\\":\\"counter\\",\\"counter\\":1}"}'
}
```
From IOS such data is returned in web_app_data:
...message.web_app_data {
  button_text: 'Button Name',
  data: '{"type":"counter","counter":1}'
}

On Windows, the sendData() method doesn't work at all.

### Operating system

Windows 10 Pro (version 21H2), Android (version 10 QKQ1.190910.002, MIUI), IOS (version 14.8.1)

### Version of Telegram Desktop

3.7

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
In which webview do you try to call this method? Because the docs state that it should work only in a Keyboard Button:

https://core.telegram.org/bots/webapps#initializing-web-apps

(not bot menu button, not inline keyboard button, etc)

**Comment by haabbaah** [comment]
Yes, I used "inline keyboard button". It's just weird that it partially works. And in the future, is it planned to support this method on all buttons?

**Comment by john-preston** [comment]
IDK to be honest.
