### ISSUE TITLE
[Question] win64 build faild

### ISSUE THREAD

**Issue by qyxcumt** [telegramdesktop/tdesktop#24391]
Hello dear staff. I'm having trouble when build submodule **breakpad** , please help, thanks a lot.
Can any experts give pointers? Thank you so much.
Enviroment:
Visual Studio 2022 Enterprise 17.1.4
python 3.9.12
pywin32 version 303
![image](https://user-images.githubusercontent.com/9052445/163995924-721ef002-822b-4eab-b422-00bcb1394576.png)

**Comment by ilya-fedin** [comment]
Do you have errors like in #16939?

**Comment by qyxcumt** [comment]
No, I think its like #7405 and #23925
In #16939, there is a comment
> There's no solution, unfortunately. breakpad doesn't seem to be compatible with chinese Windows.

But I build success in VM using chinese windows 10.
The one that failed was in windows 11.
