### ISSUE TITLE
Auto-night mode broken in 3.7

### ISSUE THREAD

**Issue by michel-slm** [telegramdesktop/tdesktop#24394]
### Steps to reproduce

After upgrading to 3.7, Telegram Desktop starts in the default day theme even though my GNOME desktop is set to Adwaita Dark.

### Expected behaviour

Auto-night mode should work as it did on the previous version

### Actual behaviour

Day theme used. I had to disable auto-night mode and pick a dark theme (tinted or night) manually.

### Operating system

Fedora 35

### Version of Telegram Desktop

3.7

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
tdesktop now uses the XDG standard to check whether the system is in dark that is supported only since GNOME 42, so you need to update your system to continue to use this feature.

**Comment by doctorcolossus** [comment]
@ilya-fedin: Thanks for opening this issue. Coincidentally I tried Telegram's "auto-night-mode" for the first time today, and couldn't figure out why it wasn't working until I found this. Then I had to figure out how to change the XDG setting, which also took me a while. In case it is helpful for you, here is how you can do so:

`gsettings set org.gnome.desktop.interface color-scheme prefer-dark`
`
gsettings set org.gnome.desktop.interface color-scheme prefer-light`

Auto-night-mode in Telegram is working for me with these commands.

**Comment by doctorcolossus** [comment]
@ilya-fedin: Thanks for opening this issue. Coincidentally I tried Telegram's "auto-night-mode" for the first time today, and couldn't figure out why it wasn't working until I found this. Then I had to figure out how to change the XDG setting, which also took me a while. In case it is helpful for you, here is how you can do so:

`gsettings set org.gnome.desktop.interface color-scheme prefer-dark`
`
gsettings set org.gnome.desktop.interface color-scheme prefer-light`

Auto-night-mode in Telegram is now working for me with these commands.

**Comment by doctorcolossus** [comment]
@ilya-fedin: Thanks for opening this issue. Coincidentally I tried Telegram's "auto-night-mode" for the first time today, and couldn't figure out why it wasn't working until I found this. Then I had to figure out how to change the XDG setting, which also took me a while. In case it is helpful for you, here is how you can do so:

`gsettings set org.gnome.desktop.interface color-scheme prefer-dark`
`
gsettings set org.gnome.desktop.interface color-scheme prefer-light`

Auto-night-mode in Telegram is now working for me with these commands.

**Comment by doctorcolossus** [comment]
@michel-slm Thanks for opening this issue. Coincidentally I tried Telegram's "auto-night-mode" for the first time today, and couldn't figure out why it wasn't working until I found this. Then I had to figure out how to change the XDG setting, which also took me a while. In case it is helpful for you, here is how you can do so:

`gsettings set org.gnome.desktop.interface color-scheme prefer-dark`
`
gsettings set org.gnome.desktop.interface color-scheme prefer-light`

Auto-night-mode in Telegram is now working for me with these commands.

**Comment by michel-slm** [comment]
> @michel-slm Thanks for opening this issue. Coincidentally I tried Telegram's "auto-night-mode" for the first time today, and couldn't figure out why it wasn't working until I found this. Then I had to figure out how to change the XDG setting, which also took me a while. In case it is helpful for you, here is how you can do so:
> 
> `gsettings set org.gnome.desktop.interface color-scheme prefer-dark` ` gsettings set org.gnome.desktop.interface color-scheme prefer-light`
> 
> Auto-night-mode in Telegram is now working for me with these commands.

Oh nice, thanks. That should allow it to keep working on older GNOMEs (though I probably will upgrade to 42 soon)

**Comment by sakralbar** [comment]
Unfortunately, many users of ubuntu 20.04 will only be able to upgrade to the new version 22.04 (with gnome 42) in the summer (with the release of 22.04.1). All this time auto-dark mode in Telegram will be unavailable for them.

**Comment by ilya-fedin** [comment]
Well, it's their choice. They can wait on old version of the distro without additional features or update to the latest version of the distro and use latest features.

**Comment by MadWalnut** [comment]
I recently upgraded my Arch system to GNOME 42.1 and Telegram Desktop 3.7.3. I can switch between light and dark mode and all applications respect the setting, except Telegram.

`gsettings set org.gnome.desktop.interface color-scheme prefer-dark` doesn't work either.

How do I get Telegram to respect the dark mode? Even when dark mode is set when starting Telegram, it just defaults to light mode.

**Comment by vimpostor** [comment]
> How do I get Telegram to respect the dark mode?

Make sure that additionally the xdg portal is running:
```bash
systemctl --user status xdg-desktop-portal
```

**Comment by MadWalnut** [comment]
Good hint @vimpostor. The service was running, but then I disabled it, rebooted, enabled it again and now it seems to be working. Weird. Thanks!
