### ISSUE TITLE
Selecting notification sound for a chat does nothing when sounds are disabled

### ISSUE THREAD

**Issue by TiGR** [telegramdesktop/tdesktop#24401]
### Steps to reproduce

1. Make sure that Settings → Notifications and Sounds → Play Sound is **Off**
2. Go to any chat and select a notification sound for that chat

### Expected behaviour

Selected chat produces sound when meassages received. That is supposed to be the way you make only some chats produce sound. Currently there is no way to achieve this - either all chats produce sound and some have different sounds, or no sounds for all chats.

### Actual behaviour

The chat is silent.

### Operating system

Linux, kde Neon 5.24

### Version of Telegram Desktop

3.7.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
i believe it works as intended. You can create a feature request if you want such a feature.
