### ISSUE TITLE
Segmentation fault (core dumped) using telegram bin from telegram.org

### ISSUE THREAD

**Issue by DevDorrejo** [telegramdesktop/tdesktop#24404]
### Steps to reproduce

1. Download telegram from https://telegram.org/dl/desktop/linux
2. Try open telegram

### Expected behaviour

Telegram being running

### Actual behaviour

Not open, when try open by terminal it will show:

Segmentation fault (core dumped)

### Operating system

openSUSE Tumbleweed, KDE Plasma 5.24.4

### Version of Telegram Desktop

3.7.1

### Installation source

Static binary from official website

### Logs

```shell
./Telegram 
Segmentation fault (core dumped)
```

**Comment by ilya-fedin** [comment]
Can you try to run the binary in gdb?

**Comment by DevDorrejo** [comment]
> Can you try to run the binary in gdb?

BFD: warning: /home/wedc/bin/Telegram/Telegram has a corrupt string table index - ignoring
Reading symbols from Telegram...
(No debugging symbols found in Telegram)
