### ISSUE TITLE
Files opened in wrong application (Ubuntu)

### ISSUE THREAD

**Issue by daccess1** [telegramdesktop/tdesktop#24403]
### Steps to reproduce

1. Set Google Chrome (or anything else, firefox etc) as default application for PDF files in Ubuntu
2. Open the file from a chat with the left-click

### Expected behaviour

File opens in the default app of my choice

### Actual behaviour

File opens in Ubuntu's built-in "Document Viewer"

### Operating system

Ubuntu 20.04

### Version of Telegram Desktop

3.7

### Installation source

Snap

**Comment by ilya-fedin** [comment]
tdesktop has no control on what opens your files. It's either snap runtime, xdg-desktop-portal or glib bug.
