### ISSUE TITLE
[Bug] version 0.10.5 - some settings reset after 2 app restarts

### ISSUE THREAD

**Issue by kirsan31** [telegramdesktop/tdesktop#2441]
Version 0.10.5, portable, windows 7 prof. sp1.
After last small update, I notice, that some settings revert to defaults after my pc reboot.
Settings that are reset:

Desktop notification
Download path
Auto-Lock if away for

Tested on 2 different pc. After 1 reboot after update all was ok, but after every next reboot settings are reset.
**UPDATE**
No need to reboot pc.
**Steps to reproduce:**
1) Turn off "Desktop notification".
2) Close app.
3) Run app - open settings - all ok.
4) Close app.
5) Open app - open settings  - "Desktop notification" is on :)

**Comment by SKUndef** [comment]
I can confirm this, for me settings that don't stick are "Show message preview" and Download path.

**Comment by kirsan31** [comment]
Sorry, duplicate with: https://github.com/telegramdesktop/tdesktop/issues/2412
P.s. When I posted this, I searched for duplicate with _bug_ Label...

**Comment by john-preston** [comment]
This one should be fixed in 0.10.7 stable, available from https://desktop.telegram.org
