### ISSUE TITLE
Dropdown menus do not work on Raspberry OS

### ISSUE THREAD

**Issue by stranno** [telegramdesktop/tdesktop#24418]
### Steps to reproduce

I have installed TG from snapd, both 3.7.1 and 3.7.1 dev build, and neither of both have dropdown menus (three vertical dots menus) or context menus both on chats and tray icon. Left or right click does nothing. Could de related to missing fonts?

It is a fresh, updated and upgraded, RPI OS install with just snapd and Telegram-desktop.

### Expected behaviour

Dropdown menus, like on Windows/Android client. I need the export channels option.

### Actual behaviour

It does not show anything left or right clicking the menu buttons, the chat window or the tray icon.

### Operating system

Raspberry OS

### Version of Telegram Desktop

3.7.1 or dev build

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Please provide screenshot or screencast that demonstrates the problem

**Comment by stranno** [comment]
Sure.

https://user-images.githubusercontent.com/6293197/164949615-3ec1f90d-dd30-4275-a1d3-370892759b8d.mp4

When I hover the tray icon I'm also clicking with the right button of the mouse.

I launched it from the terminal just in case that the log helps.

**Comment by ilya-fedin** [comment]
What's your WM?

**Comment by stranno** [comment]
Default Raspberry OS one, LXDE I suppose, not a big expert on Linux tbh.

**Comment by ilya-fedin** [comment]
I recommend to change it. Maybe it bugs with Qt.

**Comment by stranno** [comment]
Really? It's weird since default WM is what most people use. Maybe there isn't a lot of Telegram-Desktop userbase on RPI.

Let me check another WM.

**Comment by ilya-fedin** [comment]
> Really?

I don't know what else to suggest. If the menu doesn't open, there's most likely something wrong in communication between Qt and your WM and I don't know how to debug that. The only thing I can suggest is to ask developers of your DE.

**Comment by stranno** [comment]
Unfortunately it happens the same on XFCE and Mate. In these, unlike LXDE, windows borders are displayed properly and tray icon has a context menu, but Telegram menus are still not displayed.

![stranno_20220424_1304471](https://user-images.githubusercontent.com/6293197/164973521-1a6337a9-41fe-419a-9f24-dd374de70b8f.png)

**Comment by ilya-fedin** [comment]
Oh, I forgot to ask, what do you use for input? Is it a mouse? Touch support is not great in Qt/tdesktop. IIRC Qt doesn't even provide right click emulation.

**Comment by stranno** [comment]
Yes, it is a mouse. I will try with the kb once I arrive home.

**Comment by mirmalis** [comment]
I too have the same problem, just to ensure that it happens for other too.
rpi4 4gb, rpi400 4gb both default OSes

**Comment by ilya-fedin** [comment]
I can't reproduce this on x86 machine and no one else here has an RPI I guess, so looks like you guys have no other choice than debug on your own

**Comment by trialuser02** [comment]
I have same issue under Lubuntu 18.04 (x86-64). Tray menu works fine after application startup, but suddenly breaks after hide/show cycle.

**Comment by stranno** [comment]
Sorry, I forgot this.

Keyboard, unfortunately, does not work for navigating on Telegram, at least on RPI, so I wouldn't be an option.

Given it can't be debugged by the team and I don't know how to do that, I'm not sure if I should close this or leave it open.

**Comment by outfrost** [comment]
I have just upgraded from 3.6.1 to 3.7.3, and context menus in tdesktop main window are now broken. This prevents me from doing "save as" on a file I've received.

The only context menu I can open is the three dots menu in the fullscreen image viewer. Right-clicking things still definitely works (e.g. I can double right-click to reply). Context menu on the tray icon works.

Manjaro, KDE Plasma 5.24.5, Qt 5.15.4 (just upgraded from 5.15.3), X11, Linux 5.17.9 amd64.

I have rebooted since upgrading the packages.

Launching from terminal produces:
```
error: : cannot open
error: : cannot open
error: : cannot open
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.svg: Error while inflating gzip file: SVG format check failed
(...)
```

**Comment by ilya-fedin** [comment]
> Qt 5.15.4 (just upgraded from 5.15.3)

tdesktop supports only Qt 6 on Linux

> The only context menu I can open is the three dots menu in the fullscreen image viewer.

> Context menu on the tray icon works.

Image viewer's context menu is not a separate window like most menus in tdesktop and tray icon's context menu is drawn by the tray host in some environments. That's most likely why they still work.

**Comment by mirmalis** [comment]
I managed to get it working by booting rasberry pi with monitor. After booting you can detach the monitor and vnc in, it still works. 
If this helps somehow

**Comment by ilya-fedin** [comment]
Ah, these menus check screen bounds, so if xrandr doesn't report valid screen information, the menus won't work, yeah

**Comment by outfrost** [comment]
If I were to debug this and try to find where tdesktop is getting bad information from, where would I look in the code?

**Comment by ilya-fedin** [comment]
I don't think the bug is in tdesktop, it seems to be in your vnc server. You can check the `xrandr` output, it provides wrong information most likely.

**Comment by outfrost** [comment]
Sorry, I'm not using vnc, and I'm after _where tdesktop is getting bad information **from**_.

<details><summary><code>xrandr</code> output</summary>
<p>
```
Screen 0: minimum 320 x 200, current 5560 x 1920, maximum 16384 x 16384
DisplayPort-0 connected primary 2560x1440+1920+400 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95 + 143.86*  119.88    69.92  
   2048x1280     59.99  
   1920x1200     59.88  
   1920x1080    143.85    60.00    50.00    59.94  
   1600x1200     60.00  
   1680x1050     59.95  
   1600x1000     59.96  
   1600x900      60.00  
   1280x1024     75.02  
   1440x900      59.89  
   1280x800      59.95  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
DisplayPort-1 disconnected (normal left inverted right x axis y axis)
HDMI-A-0 connected 1080x1920+4480+0 left (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+
   1680x1050     60.00  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1440x900      60.00  
   1280x800      60.00  
   1152x864      75.00  
   1280x720      60.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
HDMI-A-1 connected 1920x1080+0+840 (normal left inverted right x axis y axis) 531mm x 299mm
   1920x1080     60.00*+  50.00    59.94  
   1600x1200     60.00  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      74.98    59.90  
   1280x960      60.00  
   1280x800      60.00  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1440x576      50.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
```
</p>
</details>

I've now noticed that the problem seems to only occur when right-clicking the Telegram window on my rotated monitor. On any of the other two (both in normal orientation), context menus function just fine.

Should I file a separate bug? Evidently `xrandr` reports the correct information (`1080x1920+4480+0 left`).

Also,

> tdesktop supports only Qt 6 on Linux

My bad, didn't realise. I've got Qt 6.3.0 on my system.

**Comment by ilya-fedin** [comment]
> Should I file a separate bug?

No, it's a Qt bug

**Comment by ilya-fedin** [comment]
You may want to switch to one of the official builds where Qt is patched and the bug doesn't exist

**Comment by outfrost** [comment]
Found the Qt bug. Looks like it's been resolved in 6.3.1 and 6.4.

[QTBUG-103558](https://bugreports.qt.io/browse/QTBUG-103558)

**Comment by john-preston** [comment]
@outfrost Please check beta version 3.7.6, it is based on Qt 6.3.1.

**Comment by outfrost** [comment]
@john-preston Is there a binary build I can try without an installer? I'd rather not mess up my existing installation, so if using the installer (or signing up for api keys and building locally) is the only option, then I'll wait until my distro ships a new version.

**Comment by outfrost** [comment]
@ilya-fedin Then what is the `tsetup` binary? When I used it in the past it acted as an installer, adding menu shortcuts and such.

**Comment by ilya-fedin** [comment]
It's just a binary build. tdesktop installs menu shortcuts by itself, without any installers.

**Comment by outfrost** [comment]
If the fix is just in Qt, then I'll get that once Manjaro ships Qt 6.3.1. If there is another fix in tdesktop itself, then it makes sense to test separately.

**Comment by ilya-fedin** [comment]
It's in Qt

**Comment by outfrost** [comment]
I've received Qt 6.3.1 and tdesktop 4.0.0 and can confirm that context menus are working again.
