### ISSUE TITLE
Telegram crashes on loading a suspicious sticker set

### ISSUE THREAD

**Issue by OverShifted** [telegramdesktop/tdesktop#24417]
### Steps to reproduce

1. Open Telegram desktop (also happens on the Android app and Webk browser-based client and possibly on all other clients unless the hardware has plenty of RAM).
2. Open this sticker set: https://t.me/addstickers/totallynormalvideostickers
3. Telegram allocates too much memory and will crash.
Depending on the hardware, different on-screen stickers are needed to make the telegram (and whole device) crash.
My phone crashes with just 2 stickers sent in a chat; But my laptop requires a lot of them (It only crashes when I open the sticker set, which shows a lot of them at the same time)

Each sticker; is a 100% red, 1500x1500 pixels animated sticker. (1 frame costs about ` (15000*15000*3) / (1024 ** 2) ~= 643MB` of memory) Because of its color, it can be compressed to just a few hundred kilobytes. My guess is that Telegram tries to render it on a frame buffer (probably a CPU-side one). So it needs an insane amount of memory. (Similar to an Instagram post that made low-memory devices crash) 

### Expected behaviour

These sticker packs should not be allowed to be created in the first place.
Or an error message should be shown when rendering it requires such a large amount of memory.

### Actual behaviour

Telegram allocates a lot of memory until the entire OS crashes.
(It does not really crash, It just freezes and requires a restart)

### Operating system

Kubuntu 20.04.4 LTS with KDE Plasma v5.18.8. Also happens on Windows10 and Android and Webk and possibly all other clients (They should be reported and discussed some where else)

### Version of Telegram Desktop

3.7.1

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Please, use search next time. #24395
