### ISSUE TITLE
Video or Picture windows does not fit screen

### ISSUE THREAD

**Issue by VladimirMrzv** [telegramdesktop/tdesktop#24416]
### Steps to reproduce

open picture or video from message

![image](https://user-images.githubusercontent.com/81020401/164885813-3db97f16-94db-4bc7-90ac-859f162b6370.png)
![image](https://user-images.githubusercontent.com/81020401/164885861-2ecdb965-56d5-49f8-9ed6-414b93413093.png)

### Expected behaviour

Resizing to screen resolition for working area, include panels

### Actual behaviour

Picture or Video does not fit screen, controls too

### Operating system

Ubuntu 22.04 Unity Desktop

### Version of Telegram Desktop

3.7.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can you check `xprop _NET_WM_STATE` on the media viewer window?

**Comment by VladimirMrzv** [comment]
How to do it?

**Comment by ilya-fedin** [comment]
Execute the command and click on the media viewer window

**Comment by VladimirMrzv** [comment]
Могу на русском?

Запускаю в терминале?
$ xprop _NET_WM_STATE
_NET_WM_STATE(ATOM) = 

когда нажимаю на картинку в окне телеграмма, то он завершает команду

**Comment by ilya-fedin** [comment]
> _NET_WM_STATE(ATOM) =

Это очень странно. Кажется, у Unity какой-то баг и она сбрасывает окно до обычного состояния. Надо, чтобы кто-то им зарепортил...

**Comment by VladimirMrzv** [comment]
можете подробнее расписать, напишу сам.

**Comment by ilya-fedin** [comment]
Ну, чего тут расписывать, вьювер показывается с помощью QWidget::showFullScreen: https://github.com/telegramdesktop/tdesktop/blob/bb75a6a31b091a299a484962ad2a8ac0eff9e991/Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp#L2683
Вроде как он должен ставить _NET_WM_STATE_FULLSCREEN, по крайней мере это то, что я вижу у себя. Unity его по какой-то (неизвестной мне) причине сбрасывает.

**Comment by VladimirMrzv** [comment]
Спасибо. Дам ссылку сюда. 

Поломалось в последних версиях telegram, до этого влазило в окно.

**Comment by ilya-fedin** [comment]
Ну, были изменения для улучшения работы с несколькими экранами. Скорее всего Unity на что-то реагирует неадекватно.
