### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by L422Y** [telegramdesktop/tdesktop#24425]
### Is your feature request related to a problem?

More of a annoyance of how to persist important information than a problem

### Describe the solution you'd like

There should be a way to create a "sticky" panel at the bottom of the chat above or below the text entry, so we can render important notes, links, live prices, leader boards, any other data. Like the commands panel for bot chats, but more customizable. Would love to see it be able to use HTML5 and/or canvas capabilities. 

Group setting could have it always on, on by default and toggleable, off by default and toggleable, or off

### Describe alternatives you've considered

Pinned messages are kind of a hacky way to persist data in the chat interface, and they are constantly unpinned / replaced with the latest pins, so people always have to say "check pinned messages"

**Comment by RememberTheAir** [comment]
This is out of the scope of a single client app, such suggestions belong to https://suggestions.telegram.org
