### ISSUE TITLE
RTMP streaming do not work with old channels

### ISSUE THREAD

**Issue by sohaiblaraba** [telegramdesktop/tdesktop#24426]
### Steps to reproduce

1. Launch streaming on channels created before this feature was released.

### Expected behaviour

a list asking to start live streaming, schedule a live streaming or stream with (RTMP).

![image](https://user-images.githubusercontent.com/3787230/165075992-8ba7c2b3-b83f-47c2-a542-8ab1fb42d9ac.png)

### Actual behaviour

A pop up asking to launch or schedule a streaming, which is not the case with new channels.
![image](https://user-images.githubusercontent.com/3787230/165076186-f8a2dcca-1343-40c1-9bdb-63bcfe9a8280.png)

### Operating system

Windows 11

### Version of Telegram Desktop

3.7.1

### Installation source

Static binary from official website

**Comment by MasterGroosha** [comment]
Are you sure it's a bug? Are you able to start a live stream when you press "Create" button?

**Comment by sohaiblaraba** [comment]
> Are you sure it's a bug? Are you able to start a live stream when you press "Create" button?

I can lanch stream directly or schedule it, but I cannot use the RTMP to stream from OBS or Restream. I can do this only for newly created channels. However, for older ones, It is not available.

**Comment by Aokromes** [comment]
works for me on a group created on 2016

**Comment by MasterGroosha** [comment]
@sohaiblaraba maybe a screencast (video) will help us understand, what exactly happens with your TDesktop

**Comment by sohaiblaraba** [comment]
> @sohaiblaraba I've just opened one of my channels created back in 2017 and "Stream with..." opens a menu with RTMP URL and token.
> 
> Again, if you select "Stream" -> "Stream with...", what happens?

I don't have this option on old channels. This is also the case with multiple people I tried this option with. 

Check in the attached video.

Thank you for your help.

https://user-images.githubusercontent.com/3787230/165299521-c62b3c1e-0815-4de9-980a-f038a89f31c4.mp4

.

**Comment by sohaiblaraba** [comment]
> > @sohaiblaraba I've just opened one of my channels created back in 2017 and "Stream with..." opens a menu with RTMP URL and token.
> > Again, if you select "Stream" -> "Stream with...", what happens?
> 
> I don't have this option on old channels. This is also the case with multiple people I tried this option with.
> 
> Check in the attached video.
> 
> Thank you for your help.
> 
>  InkedMedia1_Trim.mp4 
> .

@MasterGroosha Have you seen the above video that shows my problem?

**Comment by MasterGroosha** [comment]
@sohaiblaraba Wow, just wow.
I hope @john-preston knows the answer

**Comment by 23rd** [comment]
I guess you are not a creator.

**Comment by sohaiblaraba** [comment]
> I guess you are not a creator.

@MasterGroosha Mistery resolved by @23rd . Indeed it only works when I am the creator.
Do you think that it's possible to allow admis to have this option too?

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
