### ISSUE TITLE
Bad support for multi-monitor with different orientatons

### ISSUE THREAD

**Issue by leonekmi** [telegramdesktop/tdesktop#24428]
### Steps to reproduce

1. Setup a multi-monitor display environment with a vertical and a horizontal screen
2. Open a media, try to right-click areas not covered properly
3. The context menu does not appear, is wrongly placed, and the media viewer is placed like a horizontal display.

### Expected behaviour

Telegram 3.6 was working properly: the media viewer was scaling correctly according to screen settings.

### Actual behaviour

![image](https://user-images.githubusercontent.com/20224422/165146190-6f48bb95-6e1b-4277-b55f-927600c20d28.png)

The context menus works only in the dimmer zone of the media viewer, even if the media viewer is closed. The context menus opened with three dots buttons have an offset on the screen.

![image](https://user-images.githubusercontent.com/20224422/165147193-06acb4e4-f060-409a-a05d-7f09aecb6386.png)

### Operating system

Arch Linux rolling, GNOME 42 on X.org

### Version of Telegram Desktop

3.7.1

### Installation source

Other (unofficial) source: [Arch Linux community repository](https://archlinux.org/packages/community/x86_64/telegram-desktop/)

### Notes

I have similar issues with other Qt applications (especially context menus), so it's maybe Qt-related

**Comment by Aokromes** [comment]
duplicate. and yes, 3rd party.
