### ISSUE TITLE
Received an SMS while I didn't login ?

### ISSUE THREAD

**Issue by Imadlekal** [telegramdesktop/tdesktop#2443]
Okey , so here is the thing guys.
It's being some time since I didn't login into my Telegram account . Today , I received an SMS at 17:04 and another one at 17:05 giving me the **SAME** code of Telegram (the one I should type to connect) , I was without an internet connection at that time so I'm not sure how this could've happened.

I'm not sure If there is a way to know If I'm hacked or what (I don't think so) , so It might be a bug. 

Till now , I didn't connect back to my account to see what happened exactly as I'm afraid that could trigger something to get my messages logged or something.

**Comment by john-preston** [comment]
It looks like someone used your phone number and made an attempt to log in. This has nothing to do with Telegram Desktop, sorry.
