### ISSUE TITLE
[Feature Request] Support more proxy protocols like shadowsocks, vmess and trojan

### ISSUE THREAD

**Issue by EDK-Rise** [telegramdesktop/tdesktop#24434]
### Is your feature request related to a problem?

in my country telegram is blocked and i need new proxy protocols (shadowsocks, vmess and trojan) to connect telegram

### Describe the solution you'd like

there are many library that implemented in different programming languages, so it would be easy to integrate in telegram desktop.   

### Describe alternatives you've considered

nothing.

**Comment by ilya-fedin** [comment]
Proxy support is based on QtNetwork library, in order to support them, QtNetwork should support them first

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4577#issuecomment-381395921
