### ISSUE TITLE
Unable to build tdesktop, centos mirrors are too slow

### ISSUE THREAD

**Issue by gibcheesepuffs** [telegramdesktop/tdesktop#24431]
I am trying to build tdesktop with docker on linux. But when I run the step to prepare libraries, which is,

`docker build -t tdesktop:centos_env Telegram/build/docker/centos_env/`

It takes very long time to query mirrors and install even a single package inside docker. I waited for an hour just to see only two packages got downloaded out of 300+. I have a fast internet connection and I have even tried using VPN but the result stays the same.

**Comment by ilya-fedin** [comment]
It's quite a wrong place to complain about centos servers...

**Comment by ilya-fedin** [comment]
It doesn't have debug symbols for Qt and debug version of tg_owt though
