### ISSUE TITLE
Telegram no longer starts minimized

### ISSUE THREAD

**Issue by Qu1goN** [telegramdesktop/tdesktop#24439]
### Steps to reproduce

Start Windows with Windows start enabled and start minimized in Telegram Options.

### Expected behaviour

Telegram should start automatically with windows and start minimized,

### Actual behaviour

For two days it started with windows but no longer minimized.

Start with windows and minimized is activated in the settings. Switching it off and on again doesn't do anything,
not even a de- and installtion. Anyone have a solution please?

### Operating system

Windows 10 x64

### Version of Telegram Desktop

3.7.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Maybe you have a duplicate shortcut somewhere?

**Comment by Qu1goN** [comment]
This are the two Telegram.lnk shortcuts i have found on my system
\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by Qu1goN** [comment]
Sorry, i found a second one in Startup. Now it works! Thank you very much my friend. :-)
