### ISSUE TITLE
flatpak environment is not compatible with bot's Web App display

### ISSUE THREAD

**Issue by aurium** [telegramdesktop/tdesktop#24440]
### Steps to reproduce

1. Open the Telegram Desktop installed by flatpak.
2. Start a chat with @DurgerKingBot.
3. Click at "Order Food" button.

### Expected behaviour

Open the Bot's Web App interface.

### Actual behaviour

This error notification is displayed:

_Qt's window embedding doesn't work well with Mutter window manager. Please switch to another window manager or desktop environment._

### Operating system

Debian bullseye with GNOME

### Version of Telegram Desktop

3.7.3

### Installation source

Flatpak

**Comment by Aokromes** [comment]
well, it's clear not a bug, instead WM limitation.

**Comment by aurium** [comment]
No, it's a packing limitation. Read: **"Flatpak"**

That problem must to be solved by the packager. As it is pointed at https://flathub.org/apps/details/org.telegram.desktop here is the issue traker.

**Comment by ilya-fedin** [comment]
> No, it's a packing limitation. Read: **"Flatpak"**
 
The fact you use flatpak doesn't mean anything is a package limitation

**Comment by eKluev** [comment]
Same issue with snap package and native version https://telegram.org/dl/desktop/linux

**Comment by SamimSdz** [comment]
Same issue with snap package and native version
