### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by ringo32** [telegramdesktop/tdesktop#24446]
### Is your feature request related to a problem?

not really but something fun for in agroup

### Describe the solution you'd like

subgroups

### Describe alternatives you've considered

possible to make subgroups in a group. you cand devine parts to use as support and offtopic etc.

### Additional context

dont got but if you add some code for subgroup telegram could sort it if a group is enabled for use subgrouping... people can look in the subgroup automatically.

**Comment by ringo32** [comment]
its just handy in big groups :) without deviding in new groups thats not helpful

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
(such issue for it already exists there)
