### ISSUE TITLE
Bot WebView don't working

### ISSUE THREAD

**Issue by 0xCatPKG** [telegramdesktop/tdesktop#24445]
### Steps to reproduce

1. Try to open any bot webview

### Expected behaviour

Working bot Web App

### Actual behaviour

(null) in WebView and errors in logs
![image](https://user-images.githubusercontent.com/42083774/165550354-ad8ab0bf-13a8-4e05-abde-8c880a0eb485.png)

### Operating system

Arch Linux, linux-lqx 5.17.5, KDE Plasma 5.24.5

### Version of Telegram Desktop

3.7.3

### Installation source

Static binary from official website

### Logs

```shell
**
GLib-GIO:ERROR:../glib/gio/gsocketclient.c:1982:g_socket_client_enumerator_callback: assertion failed: (data->error_info->best_error)
Bail out! GLib-GIO:ERROR:../glib/gio/gsocketclient.c:1982:g_socket_client_enumerator_callback: assertion failed: (data->error_info->best_error)
**
GLib-GIO:ERROR:../glib/gio/gsocketclient.c:1982:g_socket_client_enumerator_callback: assertion failed: (data->error_info->best_error)
Bail out! GLib-GIO:ERROR:../glib/gio/gsocketclient.c:1982:g_socket_client_enumerator_callback: assertion failed: (data->error_info->best_error)
```

**Comment by ilya-fedin** [comment]
> Linux polosatyi 5.15.35-xanmod1-1 #1 SMP Fri, 22 Apr 2022 10:06:56 +0000 x86_64 GNU/Linux

![изображение](https://user-images.githubusercontent.com/17829319/165589321-a479fd69-8608-40b5-b2ec-6295f0a4cfd6.png)

**Comment by 0xCatPKG** [comment]
Report Tag: 3a3d6409-f95f-44a8-ddbb288b-f6a536b2

**Comment by ilya-fedin** [comment]
What I asked is to replace the useless kernel version string with useful info like asked by the issue template (operating system name, version and desktop environment).

**Comment by ilya-fedin** [comment]
And please notify when you fix the info as github doesn't notify when you edit messages. Thanks.

**Comment by 0xCatPKG** [comment]
I changed "Operating System" in description

**Comment by ilya-fedin** [comment]
Googling for the error on your screenshot, I found [this](https://gitlab.gnome.org/GNOME/glib/-/issues/2597). Can you confirm you don't have an IPv6 proxy set anywhere?

**Comment by 0xCatPKG** [comment]
I've checked my proxy settings in every place I know of, they're all off.
nmcli:
![image](https://user-images.githubusercontent.com/42083774/167752738-37404cc2-ebd7-423e-837d-eec3767a0927.png)

gsettings:
![image](https://user-images.githubusercontent.com/42083774/167753013-875ab3cc-258d-43d6-88d5-f6e7bf7085e9.png)

Environment Variables:
![image](https://user-images.githubusercontent.com/42083774/167753224-95b563b5-3c4e-4649-a4ca-89d8648d2123.png)

**Comment by ilya-fedin** [comment]
It seems you have got some bug in glib. All I can suggest is ensure the URL you pass to the webview can't be treated as invalid by glib (i.e. try a completely another URL). If that doesn't help, try another distro with another glib version. If nothing helps, the only thing you can is report the bug to glib apparently. Or switch to another OS.
