### ISSUE TITLE
HEIC and WebP files are treated as files instead of Images

### ISSUE THREAD

**Issue by mt-izadi** [telegramdesktop/tdesktop#24444]
### Steps to reproduce

1. Go to any chat/group/channel
2. Try to attach a .HEIC photo

### Expected behaviour

It will treat the image as a file and it won't be possible to add it to albums, compress etc... Telegram mobile handles this correctly and treats these formats as regular images.

### Actual behaviour

The photo is treated as a file and can't be used as part of an album.

![image](https://user-images.githubusercontent.com/97925165/165473169-98d6e90e-095f-49c6-b056-61266b5ca2a6.png)

I've also reported this in [Telegram Bugs](https://bugs.telegram.org/c/15470).

### Operating system

macOS 12.3.1 (21E258)

### Version of Telegram Desktop

3.7.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#5522
