### ISSUE TITLE
After update resets "Include muted chats in unread count"

### ISSUE THREAD

**Issue by miraslau** [telegramdesktop/tdesktop#2444]
Hi there,

After one of last updates I have simple but unpleasant issue: after update setting "Include muted chats in unread count" sets yourself to true and I see muted chats in unread counts. When I turn it off, muted chats are not showing as needed, but after update it enables again.

OS: Windows 7 x64
Version: 0.10.15

**Comment by john-preston** [comment]
@mirasalu Thank you for your report! You'll need to wait for the next update or disable «Tile background» checkbox in your settings, it will fix the problem.

**Comment by john-preston** [comment]
This one should be fixed in 0.10.7 stable, available from https://desktop.telegram.org
