### ISSUE TITLE
[Feature Request] System Wide Installer

### ISSUE THREAD

**Issue by hypercube33** [telegramdesktop/tdesktop#24447]
### Is your feature request related to a problem?

The current installer puts the app in appdata. Every user has their own install on a system. We'd like one in Program Files that only stores its data in AppData.

### Describe the solution you'd like

Create a System-Wide Installer.

### Describe alternatives you've considered

Not using the desktop app.

**Comment by ilya-fedin** [comment]
Can't you just change the installation directory in the installer?

**Comment by krivchenkovboris66** [comment]
krivchenkovboris66 gihub.com Boris 28/04/2022
