### ISSUE TITLE
can not decode phone.checkGroupCall response

### ISSUE THREAD

**Issue by qingsong-he** [telegramdesktop/tdesktop#24455]
### Steps to reproduce

1. open client
2. open group call
3. open client mtp*.txt log file

### Expected behaviour

when response type is Vector int , client can not decode it.

### Actual behaviour

![image](https://user-images.githubusercontent.com/59381037/165890806-b7fc290b-a538-4a73-acb5-f0e2e26fa2a8.png)

### Operating system

ubuntu 20.04

### Version of Telegram Desktop

v3.7.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@qingsong-he Sorry, my logger can't decode response of type vector<smth>.

**Comment by qingsong-he** [comment]
@john-preston Strange, I can appear here. Is it that the client on your side doesn't call phone_checkGroupCall, so you don't see the log of decoding errors.

**Comment by john-preston** [comment]
@qingsong-he It does call and I can see the decoding error. This is not a problem. My MTP logger doesn't have context (what it decodes), it just looks on the bytes and tries to decode by the scheme. But this request returns Vector<int>.

The code knows response to which request is decoded, so Vector<int> is decoded successfully there and everything works as expected. But the logger (different code, not the one that handles requests / responses) doesn't know what exactly it writes to the log. And "Vector<int>" can't be decoded if you don't know that there should be Vector<int>. So this response fails to be logged. It's not very cool, ofc, but it is fine.
