### ISSUE TITLE
[Feature Request] Pop-out Chats for Desktop

### ISSUE THREAD

**Issue by kylemcisaac** [telegramdesktop/tdesktop#24454]
### Is your feature request related to a problem?

Using Telegram Desktop for both personal and work reasons, there are times in which you need to monitor two or more chats at a time. Having the ability to pop chats to separate windows so that you can either tile them on one screen or move them to separate screens would allow multi-tasking between chats.

### Describe the solution you'd like

An option to right-click on a chat and allow a "pop out" feature, thus taking the chat and opening it in a separate window dedicated to that chat; whether it is a channel, personal chat, bot commands, etc.

### Describe alternatives you've considered

Using multiple devices (mobile and desktop app), which does work but not efficiently.

### Additional context

![image](https://user-images.githubusercontent.com/86158698/165871319-5c31fb03-a396-4344-837e-badbd1d0f714.png)
Example mockup

**Comment by ilya-fedin** [comment]
No, of #2105
