### ISSUE TITLE
Doesn't work through proxy anymore

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#24450]
### Steps to reproduce

Try to connect to telegram by giving the desktop app a correct proxy URL(which worked before and still works in firefox).

### Expected behaviour

Telegram connects.

### Actual behaviour

Telegram can't connect.

### Operating system

Ubuntu 20.04

### Version of Telegram Desktop

Can't check it.

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> Can't check it.

Why can't you?

**Comment by llamas111** [comment]
> > Can't check it.
> 
> Why can't you?

Because I can't get to the side panel where it'd show it.

**Comment by llamas111** [comment]
I found it elsewhere: 3.7.3
