### ISSUE TITLE
Bot WebView browser version

### ISSUE THREAD

**Issue by Isgeny** [telegramdesktop/tdesktop#24469]
I tried to run my blazor app in the bot webview, but it's not working. I found that webview uses chrome v70.0.3538.102 which is very old and many new javascript features not available (that is actually the reason why I can't startup blazor). Is it possible to raise chrome version in bot view?

**Comment by ilya-fedin** [comment]
Webview uses whatever browser is provided by your system.
Windows 8.1-10: EdgeHtml
Windows 11: EdgeChromium
macOS: Cocoa WebKit
Linux: WebKitGTK

Exact version depends on user's system version and system's libraries versions.

**Comment by john-preston** [comment]
@Isgeny Now (try beta version 3.7.4) tries using Chromium Edge on all Windows versions. But anyway it can fallback to Legacy Edge if it is available and the new WebView2 not available.

**Comment by Isgeny** [comment]
> @Isgeny Now (try beta version 3.7.4) tries using Chromium Edge on all Windows versions. But anyway it can fallback to Legacy Edge if it is available and the new WebView2 not available.

Great, it's working now! This is my environment:
Windows 10 21H2
Telegram beta 3.7.4
Microsoft Edge WebView2 Runtime installed

Tried to delete Microsoft Edge WebView2 Runtime and install only Chromium Edge. In that case it really fallback to Legacy Edge.
