### ISSUE TITLE
Crashes on screencast (linux)

### ISSUE THREAD

**Issue by NotYasho** [telegramdesktop/tdesktop#24468]
### Steps to reproduce

1. Start telegram desktop (through command-line or through launcher)
2. Make a voice call
3. As soon as the other party tries to screenshare, telegram crashes.

### Expected behaviour

well, it should not crash ¯\_(ツ)_/¯

### Actual behaviour

telegram-desktop crashes with the log:
```bash
# when the other person tries to screenshare
SkipFrames(3) is large
[1]    6239 segmentation fault (core dumped)  telegram-desktop
# *crashes*
```

### Operating system

Manjaro Linux x86_64

### Version of Telegram Desktop

3.6.1-1

### Installation source

Snap

### Logs

```shell
# when the other person tries to screenshare
SkipFrames(3) is large
[1]    6239 segmentation fault (core dumped)  telegram-desktop
# *crashes*
```

Installed telegram with:
```console
$ sudo pacman -S telegram-desktop
```

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by NotYasho** [comment]
works! thank you
