### ISSUE TITLE
[MacOS] On a double monitor setup, changing monitor A resolution when the app is running on monitor B makes the app unusable.

### ISSUE THREAD

**Issue by danilolutti** [telegramdesktop/tdesktop#24463]
### Steps to reproduce

1. open telegram
2. switch the monitor to a different resolution
3. [BUG] the mouse cursor doesn't hover on the right UI elements
4. I need to restart the app to make it working properly again

### Expected behaviour

change the monitor resolution shouldn't affect the app

### Actual behaviour

change the monitor resolution broke the app normal behaviour

### Operating system

MacOs 11.6.5 (same bug on all mac os versions)

### Version of Telegram Desktop

3.7.3

### Installation source

Mac App Store

**Comment by danilolutti** [comment]
[bug video demo](https://youtu.be/QEk4UCC5P-0)

**Comment by JDTm** [comment]
I have the same problem, when the mac returns from hibernate. 
The app is not crashing, the mouse cursor is not on the same position, it is moved (you see it also in your video). 
**Telegram Version**
4.0.2
**MacOS** 
11.6.6 Big Sur
