### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Barmarel** [telegramdesktop/tdesktop#24462]
### Is your feature request related to a problem?

No, this is a request for improvement.

### Describe the solution you'd like

Please add an AppImage version of the application for Linux. Apps of this kind are more user-friendly. 

### Describe alternatives you've considered

The AppImage container, this is the best solution.

**Comment by ilya-fedin** [comment]
What's the problem with the static binary?

**Comment by Barmarel** [comment]
> 

No problems at all. 
AppImage is easier to integrate into the system.

**Comment by ilya-fedin** [comment]
What could be easier than just run the binary?

**Comment by Barmarel** [comment]
AppImage also only needs to be started. 
That said, if AppImageLauncher is installed on the system, when first started, the application can be automatically integrated into the Start menu, context menu and register MIME-types if required.
Also AppImage work isolated from the system, but are a 'lighter' and more flexible option than Flatpack or Snap.
All in all it is convenient. Many people also use AppImage.

**Comment by ilya-fedin** [comment]
I don't see how AppImage is better. Static binary automatically integrates into the system on first launch (start menu and MIME types are implemented, I haven't seen APIs to integrate with context menu on Linux, but if you provide a link for documnetation about such API, that could be added, too), there's also nothing special that would prevent you from isolating static binary. And static binary is even lighter than AppImages as the libraries are heaviliy stripped during static linking (and there's no need to compress/mount anything!).

**Comment by Barmarel** [comment]
Okay then. Thank you for your responsiveness.
