### ISSUE TITLE
"Cannot open shared library" error when I start live stream

### ISSUE THREAD

**Issue by Alireza-Gerami** [telegramdesktop/tdesktop#24470]
Hi,
I have an error when I start the live stream on Telegram Desktop. It doesn't work.

OS: Fedora35

![Screenshot from 2022-05-03 16-12-39](https://user-images.githubusercontent.com/43993145/166447370-7a25c75d-e243-46cc-b21f-13c30223875d.png)
![Screenshot from 2022-05-03 16-13-58](https://user-images.githubusercontent.com/43993145/166447374-818d8e7c-4e64-4c95-8476-2a6478c365f1.png)

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
I'd say entire report is invalid as question template is used

**Comment by Alireza-Gerami** [comment]
> plz try downloading official version from https://desktop.telegram.org

I installed the latest version from snap. also, I just download tsetup.3.7.3.tar.xz but it doesn't woork too.

**Comment by ilya-fedin** [comment]
You should re-create the issue with the appropriate bug report template as it asks for the basic required infromation

**Comment by Alireza-Gerami** [comment]
> You should re-create the issue with the appropriate bug report template as it asks for the basic required infromation

Ok, thanks.
