### ISSUE TITLE
voice messages

### ISSUE THREAD

**Issue by xtimech1234** [telegramdesktop/tdesktop#24474]
after updating the telegram, the sound quality in voice messages became poor, the sound became poor quality, the high frequencies of the sound dropped. in desktop version.

**Comment by xtimech1234** [comment]
> after updating the telegram, the sound quality in voice messages became poor, the sound became poor quality, the high frequencies of the sound dropped. 
in desktop version

**Comment by ilya-fedin** [comment]
Please re-open the issue using bug report template
