### ISSUE TITLE
Tray icon menu appears only onece, linux.

### ISSUE THREAD

**Issue by 5x3** [telegramdesktop/tdesktop#24477]
### Steps to reproduce

1. right click on tray icon - menu appears, click disable notifications.
2. right click on tray icon - menu DOES NOT appears, bang.

### Expected behaviour

menu appears always.

### Actual behaviour

menu appears once after start app.

### Operating system

Linux * 5.0.9-301.fc30.x86_64 #1 SMP Tue Apr 23 23:57:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Version of Telegram Desktop

3.7.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> Linux * 5.0.9-301.fc30.x86_64 #1 SMP Tue Apr 23 23:57:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/17829319/166689485-2919a1db-df41-43aa-9389-58d7ed7afe8d.png)

**Comment by john-preston** [comment]
@5x3 Also, please try 3.7.4 beta version and report if something changed.

**Comment by 53R3n17Y-serenity** [comment]
Works as expected.

_OS: Ubuntu 20.04.4 LTS x86_64
Kernel: 5.13.0-40-generic 
Static binary from official website 3.7.3_

**Comment by 5x3** [comment]
don't work as expected
cat /etc/redhat-release 
Fedora release 30 (Thirty)
and apparently in others OS too.
few upgrades before all was ok.
p.s. oh, yes, and just don't start please about unsupported os ver. etc.

**Comment by ilya-fedin** [comment]
> cat /etc/redhat-release
> Fedora release 30 (Thirty)

You also need to specify desktop environment

**Comment by 5x3** [comment]
desktop environment: **icewm**.
thanks.

**Comment by ilya-fedin** [comment]
> desktop environment: **icewm**.

Please answer the question from https://github.com/telegramdesktop/tdesktop/issues/24477#issuecomment-1118230762
