### ISSUE TITLE
[Question] custom folder 

### ISSUE THREAD

**Issue by tst32** [telegramdesktop/tdesktop#24489]
How do I create a "Sent" folder in Telegram to contain all messages from me? Like I do in email?

**Comment by tst32** [comment]
i doubt too. but... What if it is still possible?

**Comment by tst32** [comment]
do it make sense to open Feature req?

**Comment by ilya-fedin** [comment]
I don't think so

**Comment by Aokromes** [comment]
> do it make sense to open Feature req?

such feature belongs to https://bugs.telegram.org/
