### ISSUE TITLE
Tray icon missing on Wayland

### ISSUE THREAD

**Issue by PAI5REECHO** [telegramdesktop/tdesktop#24483]
### Steps to reproduce

1. Open telegram

### Expected behaviour

A tray icon to appear

### Actual behaviour

A tray icon to appear

### Operating system

NixOS Unstable

### Version of Telegram Desktop

3.6

### Installation source

Other (unofficial) source

**Comment by john-preston** [comment]
@PAI5REECHO Try 3.7.4 beta please.

**Comment by h0tc0d3** [comment]
I don't have this problem in sway + waybar.

**Comment by PAI5REECHO** [comment]
Works fine on `3.7.3`
