### ISSUE TITLE
Questions about libvpx appear through the source build

### ISSUE THREAD

**Issue by x12901** [telegramdesktop/tdesktop#24481]
### Steps to reproduce

reference : https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md

1. Prepare folder
2. Install third party software
3. Clone source code and prepare libraries

### Expected behaviour

Successful construction

### Actual behaviour

An error occurred

### Operating system

 Windows-10-10.0.19042-SP0

### Version of Telegram Desktop

dev

### Installation source

Other (unofficial) source

### Logs

```shell
https://github.com/x12901/error/blob/master/libvpx.md
```

**Comment by den777-d** [comment]
I have the same problem
