### ISSUE TITLE
UX: The Interface scale is unsuitable

### ISSUE THREAD

**Issue by WeberAlex** [telegramdesktop/tdesktop#24485]
### Is your feature request related to a problem?

I am having difficulty using Telegram Desktop on Windows 11 because the text renders either too small, either too big. The interface scale is unsuitable. My eyes are not young. I am looking to increase the text between 130~140%. I cannot do it. Either 125% either 150%.

![SCR_20220505_135134](https://user-images.githubusercontent.com/28292190/166973172-ccc7d94b-8224-40c4-b2f6-c634ed5ef6ef.png)

### Describe the solution you'd like

On the Android app, I can slide with +1 increment, to increase the font size of Telegram to my need. I would like the same on Windows.

### Describe alternatives you've considered

Or I would like to be able to type a zoom value to my need.

### Additional context

To me it seems more like a UX bug due to the poor usability of the interface scale, than a feature request, but I will let you do the triage.

**Comment by 23rd** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6055#issuecomment-496599363.

**Comment by WeberAlex** [comment]
> [#6055 (comment)](https://github.com/telegramdesktop/tdesktop/issues/6055#issuecomment-496599363).

Hi and thanks for that! `-scale n` only accept 5% increments from my testing. It's better than nothing, but I expect more font size settings from a popular messaging app.

On Windows I have to kill the Telegram task every time I want to change the scale value. There is probably a setting for that too in the prefs?

I am fine editing a `.json` file on a text code editor to set my font size preferences, but on a instant messaging app, I would welcome to have a slider or a text field to choose between 133% or 134%, etc. In addition, with dual monitor with different resolution, I often need to adjust the font size on the go, depending on the monitor the app is on.

**Comment by rkiddy** [comment]
I run Telegram on Ubuntu 22.04.1 LTS. I to launch with the -scale option and it has no effect. Should it?

The reasonable way to set the font size is to have the 'ctl-plus' and 'ctl-minus' key increase and decrease the default font size.

It is less helpful, but better than nothing, to have a place in Settings to set the default font, including the size.

Neither has been done. I would rather not have to use a magnifying glass to use the app.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/ff331c040a8e73dbcd6adfff696ea2af9f0f6a08

**Comment by john-preston** [comment]
This should be possible in the new 4.5.5 beta version.
