### ISSUE TITLE
[Feature Request] Logarithmic volume controls

### ISSUE THREAD

**Issue by lazurit11** [telegramdesktop/tdesktop#24488]
### Is your feature request related to a problem?

I'm finding myself using very low volume values in-app, because volume becomes too high too quick. This leads to poor lower-volume control.

### Describe the solution you'd like

Consider implementing logarithmic volume control, meaning that slider wouldn't change volume linearly, but with a logarithmic curve. This behavior is already implemented in (what i'm aware of) Spotify (Windows and Linux), AIMP (Windows music player, option in volume settings), Volume2 (Advanced volume control utility for Windows), GNOME (both PipeWire and PulseAudio afaik).

### Describe alternatives you've considered

None

### Additional context

Further reading:
https://techsupport.cambridgeaudio.com/hc/en-us/articles/360000105437-Amplifiers-Linear-Logarithmic-Volume-Control
https://ux.stackexchange.com/questions/79672/why-dont-commercial-products-use-logarithmic-volume-controls
https://www.dr-lex.be/info-stuff/volumecontrols.html

**Comment by haasn** [comment]
I might take a stab at implementing this, because I also find linear volume controls unusable.

For what it's worth, a good technical implemtation of a quasi-logarithmic volume curve is to use the third power of the gain. This is trivial to implement and preserves the nice property that 0% volume translates to 'no sound'.

**Comment by lazurit11** [comment]
> a good and simple technical implementation of a quasi-logarithmic volume curve is to use the third power of the gain.

Good thing to know, thanks for implementing it!
