### ISSUE TITLE
No "edited" when post was edited

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#24487]
### Steps to reproduce

1. Go to https://t.me/c/1237513492/30020 (https://t.me/joinchat/ScL1FOCgJCbFNJK1)
2. There is no "edited" text, but this post was edited
3. Mouseover on time and you will see

![image](https://user-images.githubusercontent.com/39812401/167103224-52138a1e-149f-484d-bc68-b8f387e37b00.png)
![image](https://user-images.githubusercontent.com/39812401/167103267-6d8684db-d10c-4f34-af4e-e553c9310b11.png)

This is how it must work:
![image](https://user-images.githubusercontent.com/39812401/167103599-9048b505-2e0a-40bc-9088-ec9267f2a40e.png)
https://t.me/c/1237513492/30019 (https://t.me/joinchat/ScL1FOCgJCbFNJK1)

Idk how to reproduce this exactly but I see it regularly. Maybe thing is because in this post caption written on last media, not first.

### Expected behaviour

There is must be "edited" text near time if post was edited

### Actual behaviour

There is no "edited" text near time if post was edited

### Operating system

Windows 10

### Version of Telegram Desktop

3.7.4 beta

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
Another example:
![image](https://user-images.githubusercontent.com/39812401/168609070-6b8f01b6-b28a-44d2-87ed-56df3b34af80.png)

https://t.me/c/1237513492/30462 (https://t.me/joinchat/ScL1FOCgJCbFNJK1)

**Comment by 23rd** [comment]
Please check the 3.7.6 version.

**Comment by Neurotoxin001** [comment]
Yes there is "edited" label on posts that I mentioned above. And I don't catch this bug after 16 may, so I think it's fixed now
