### ISSUE TITLE
[Feature Request] Add external link in bio

### ISSUE THREAD

**Issue by hossein13m** [telegramdesktop/tdesktop#24499]
### Is your feature request related to a problem?

-

### Describe the solution you'd like

It would be great if we could have external links in our bio. At the moment, we can provide an internal link for telegram groups, channels, and user ids, but we can not use an external link (e.g., hmousavi.dev) in our bio that users can click on.

### Describe alternatives you've considered

Another solution can be having an extra section for links alongside text in the bio. Personally, I prefer this approach, but having external links in our bio would be good enough.

**Comment by 23rd** [comment]
https://bugs.telegram.org/c/899
