### ISSUE TITLE
[Question] [Bug] Telegram automatically adds people I don't know to my contacts.

### ISSUE THREAD

**Issue by IlyaIndigo** [telegramdesktop/tdesktop#24495]
Sometime about 4 years ago I asked a friend's phone to call my girlfriend via Telegram, where I logged into my Telegram account on his phone.

After that, to this day, he and I have a kind of invisible connection. Contacts from his phone book under the names. that were in his phone book at the time automatically start being added to my contact list when they sign up for telegram.

Here's an article on habr about this
https://habr.com/ru/post/370679/

Here's a closed bug on github https://github.com/telegramdesktop/tdesktop/issues/3725

The developers have known about this problem for a long time, but do not want to do anything about it.

Why does Telegram keep some hidden, unclearable and inaccessible contact list that it automatically adds to me?

How to break this connection or clear this list, or generally prohibit Telegram to automatically add any contacts?

**Comment by Aokromes** [comment]
not a bug, delete synced contacts.

**Comment by IlyaIndigo** [comment]
> not a bug, delete synced contacts.
So the ability for another user to spy on my contacts, or for someone to spy on my contacts is not a bug but normal behavior?
How do I delete these hidden synchronized contacts?
