### ISSUE TITLE
Memory leak with Windows server 2012

### ISSUE THREAD

**Issue by theelectricsoul** [telegramdesktop/tdesktop#24492]
### Steps to reproduce

Hello

I use TG Desktop daily and I get every update I can, including beta. The memory leak issue appeared 2-3 month ago and never disappeared in any version. The RAM usage grows and grows until my whole memory is consumed. Today it reached 5 GB. 

The only think I tried, was deleting everything but the telegram.exe file. Cache and profile files were swiped. 

I attached debug and log

[Telegram.zip](https://github.com/telegramdesktop/tdesktop/files/8643107/Telegram.zip)

### Expected behaviour

--

### Actual behaviour

--

### Operating system

Microsoft Windows Server 2016 Standard, 10.0.14393 Build 14393

### Version of Telegram Desktop

3.7.4 beta x64

### Installation source

Static binary from official website

**Comment by Indil** [comment]
I got similar issue on Windows 10 Pro. Telegram sometimes fills my RAM and stuck the OS. I can't kill the process, cause the system does not respond anymore.

**Comment by theelectricsoul** [comment]
![grafik](https://user-images.githubusercontent.com/10260832/176857952-f453bd9e-1d3a-4e00-bb72-bf656061ebe0.png)
