### ISSUE TITLE
[Question] How to build Telegram from source if Mageia has decided to stop using static packages (libseccomp-static for instance)?

### ISSUE THREAD

**Issue by Umeaboy** [telegramdesktop/tdesktop#24496]
I can't seem to build Telegram locally from source as my Linux distribution called Mageia has decided to NOT use static packages anymore (I have no clue as to why) in their repos for the future.

I've tried to build libseccomp-static through the attached spec file, but it fails due to conflicts.
If I at least could get help in solving the conflicts I'd be fine building.

I am using the flatpak that you're providing, but I love building programs from source code so I prefer not having to many old libs with each flatpak update.

Had to change my spec file to .txt since .spec is not allowed.
[libseccomp.txt](https://github.com/telegramdesktop/tdesktop/files/8646062/libseccomp.txt)

**Comment by ilya-fedin** [comment]
I don't quite understand what's the problem as tdesktop doesn't use libseccomp
