### ISSUE TITLE
Spambot restrict people without good reason  

### ISSUE THREAD

**Issue by red0bear** [telegramdesktop/tdesktop#24498]
I gote restricited by spam bot fopr good time; i think there is a good reason and still dont know why, recently  on twitter same issue appeared where person got restricted. Am almost one month with that problem. :scammers have so much power they can silence people if ask telegram ? :am worried about that possibility.

**Comment by Aokromes** [comment]
this is telegram desktop bug tracker, nothing can be done here.

**Comment by red0bear** [comment]
Am aware about that; but since all channels to me talk seems closed i come here to notice you guys. :)
