### ISSUE TITLE
[WINDOWS] Voice messages arent being played in the default sound device

### ISSUE THREAD

**Issue by tiosolid** [telegramdesktop/tdesktop#2449]
### Steps to reproduce
1. Open Telegram
2. Change default sound device (Control Panel > Sound > Playback)
3. Play a voice message

### Expected behaviour
The message should be played in the CURRENT default sound device (set in step 2)

### Actual behaviour
The message is played in the default sound device that was set when the telegram app was OPENED.

What is happening (i guess) is that the Telegram Desktop for Windows chooses it sound device (to reproduce voice messages) only when it is opened, not when the voice message is about to be played. Closing and opening the app after the sound device changes "fix" this problem (since, probably, the app re-read the default sound device config from windows again).

### Configuration
**Operating system:**
Windows 10, 1607 - build 14393.105

**Version of Telegram Desktop:**
0.10.7

### Logs
No logs needed I guess

**Comment by Kondra007** [comment]
Duplicate #776
