### ISSUE TITLE
Links open in Chrome instead of Firefox (Ubuntu 22.04)

### ISSUE THREAD

**Issue by Psychosynthesis** [telegramdesktop/tdesktop#24506]
### Steps to reproduce

I have a problem similar to these two cases:
https://github.com/telegramdesktop/tdesktop/issues/8982
https://github.com/telegramdesktop/tdesktop/issues/9825

But in reverse. The default browser on the system is Firefox:
```
user@Laptop:~$ xdg-settings get default-url-scheme-handler https
firefox.desktop
user@Laptop:~$ xdg-settings get default-web-browser
firefox.desktop
user@Laptop:~$ xdg-settings get default-url-scheme-handler http
firefox.desktop
```
In the system settings for opening links, only Firefox is also specified (I removed the mapping for Chromium)

But Telegram stubbornly opens links in Chromium, which is terribly annoying.

### Expected behaviour

Web links opens in Firefox.

### Actual behaviour

Web links opens in Chromium.

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

3.7.3

### Installation source

Snap

**Comment by ilya-fedin** [comment]
What about `gio open`? It also might be because you use snap.

**Comment by Psychosynthesis** [comment]
@ilya-fedin command `gio open http:\\www.google.com` opened the Firefox...

**Comment by ilya-fedin** [comment]
It's snap then, most likely. Use tdesktop from satic bainry.

**Comment by Psychosynthesis** [comment]
@ilya-fedin  I downloaded the binary from the offsite and now I'm running through it, so now it's definitely NOT a snap.

Links still openigs in Chromium.

**Comment by ilya-fedin** [comment]
It's weird, tdesktop uses `Gio::AppInfo::launch_default_for_uri` as well as `gio open`, are you sure you check on the same URL?

**Comment by Psychosynthesis** [comment]
@ilya-fedin I have a feeling that Ubuntu lives its own life on my computer...

The system offered to update, after which I lost the Telegram shortcut from the launcher on the left panel (btw maybe someone knows how to make a link to the binary?), in addition, now the following happens:

`gio open https:\\www.google.com` - opens the Chromium, but
`gio open http:\\www.google.com` - opens the Firefox. And...

```
xdg-settings get default-url-scheme-handler https
xdg-settings get default-url-scheme-handler http
xdg-settings get default-web-browser
```
Still showing that the Firefox is default...

It looks like there is some other setting (where the GIO get data from), and for some reason it is different for **http** and **https**

**Comment by ilya-fedin** [comment]
> https:\\

Are you really using these slashes? They should be `//`.

> xdg-settings get default-url-scheme-handler https

```
xdg-mime query default x-scheme-handler/https
gio mime x-scheme-handler/https
```

**Comment by ilya-fedin** [comment]
> btw maybe someone knows how to make a link to the binary?

Go to Telegram settings and type blindly `installlauncher`

**Comment by Psychosynthesis** [comment]
`Are you really using these slashes? They should be //.`

I made a mistake when I posted here. However, now I checked, even with backslashes everything works exactly as written - http opens in Firefox, https in Chromium.

`Go to Telegram settings and type blindly installlauncher`
Thank you! Although I wouldn't call it too user-friendly...

**Comment by ilya-fedin** [comment]
> Although I wouldn't call it too user-friendly...

It's for debug purposes mostly, normally shortcut install automatically after first launch

**Comment by Psychosynthesis** [comment]
![изображение](https://user-images.githubusercontent.com/32971513/168492739-a7ba7daa-dd0a-4644-b291-ccbc223b8724.png)

**Comment by ilya-fedin** [comment]
Looks like a bug in either:
* xdg-utils
* glib
* your DE binaries (xdg-utils is a DE-dependent bash script and DE not always fully conform to the [mime-apps-spec](https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html) and when they don't, the result between glib and xdg-utils will be different)

**Comment by Psychosynthesis** [comment]
@ilya-fedin but I didn't do anything with DE binaries (whatever that means)...

I didn't include any additional repositories as sources of updates or packages (as for example I had to do on a my working machine to get an old version of PHP, I did not install any programs on this machine, except for those available in Ubuntu Software or via apt...

All I did with the system itself was upgrade it from 20.04 LTS to 22.04 LTS and after that these bug beginin...

How to find out where the root of the trouble is?

**Comment by ilya-fedin** [comment]
> but I didn't do anything with DE binaries (whatever that means)...

Well, I never said you did anything with DE binaries.

> I didn't include any additional repositories as sources of updates or packages (as for example I had to do on a my working machine to get an old version of PHP, I did not install any programs on this machine, except for those available in Ubuntu Software or via apt...

If you didn't do anything of that it doesn't mean your system can't have bugs :)

> How to find out where the root of the trouble is?

First we should find the codepath xdg-utils uses to detect the default on your system I guess...
```
bash -x $(which xdg-mime) query default x-scheme-handler/https 2>&1 | grep DE=
```

**Comment by ilya-fedin** [comment]
During inspecting xdg-utils code I found that xdg-mime and xdg-open logic is no synchronized. So I wonder what `xdg-open https://www.google.com` does...

**Comment by Psychosynthesis** [comment]
@ilya-fedin 
```
user@Laptop:~$ bash -x $(which xdg-mime) query default x-scheme-handler/https 2>&1 | grep DE=
+ DE=gnome
+ DE=gnome3
```

`xdg-open https://www.google.com` - Opens the Chromium

**Comment by ilya-fedin** [comment]
So Chromium seem to be actual default on your system for https as both gio and xdg-open open it :D 
And xdg-utils seem to be totally bugged even that xdg-open, xdg-mime and xdg-settings have different opinion about your deafults.

**Comment by Psychosynthesis** [comment]
Wow. Every day I love Ubuntu more and more.

**Comment by ilya-fedin** [comment]
> Wow. Every day I love Ubuntu more and more.

It's interesting though that xdg-mime says `firefox.desktop` while gio mime has `firefox_firefox.desktop` in the list. So maybe firefox.desktop doesn't exist and the next application in the priority gets used while xdg-mime doesn't check that.

**Comment by ilya-fedin** [comment]
Changing the default browser to something other and back even in the UI should help then.

**Comment by Psychosynthesis** [comment]
> It's interesting though that xdg-mime says firefox.desktop while gio mime has firefox_firefox.desktop in the list. So maybe firefox.desktop doesn't exist and the next application in the priority gets used while xdg-mime doesn't check that.

In principle, it is possible, because when they last updated Firefox, they kind of changed the installation method to snap, maybe firefox.desktop was left from the previous installation, and the new one simply did not update all the settings.

> Changing the default browser to something other and back even in the UI should help then.

Thanks, I'll try
