### ISSUE TITLE
Telegram Windows App v3.7.3 x64 crashing while opening/ closing media in app

### ISSUE THREAD

**Issue by dikshansh13** [telegramdesktop/tdesktop#24502]
### Steps to reproduce

In any chat, Open any photo/video
Try closing it though cross icon on top right corner.
Telegram stops responding and crashes.

### Expected behaviour

Shouldn't crash, get back to chat normally.

### Actual behaviour

![image](https://user-images.githubusercontent.com/51121709/167548216-496ead35-e0d1-4e84-9260-58cbfebeef1c.png)

### Operating system

Windows 11 Home Single Language 21H2  OS Build: 22000.613

### Version of Telegram Desktop

version 3.7.3 x64

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org then enable beta, restart and try to get crash, if you get crash post crash id here.
