### ISSUE TITLE
Telegram sporadically block window compositor during video playback

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [telegramdesktop/tdesktop#24509]
### Steps to reproduce

1. Normal usage of tg desktop
2. in average 2 weeks time tg desktop lock compositor. Ie not possible to switch between different application windows using mouse .
3. Issue completely random but in most cases happen during video playback

Steps to continue to work without reboot : 

1) Switch to console ctrl+alt+f1
2) login
3) find telegram process
4) kill it with -15 signal
5) After it window manager continue to work without any problem

### Expected behavior

have to work like normal application

### Actual behaviour

Locked compositor until kill -15 <tg desctop pid>

### Operating system

manjaro

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> 3.6.1

You have old version. Update to the latest version before reporting.
