### ISSUE TITLE
Cannot copy my own phone number

### ISSUE THREAD

**Issue by Weker01** [telegramdesktop/tdesktop#24501]
### Steps to reproduce

A while ago (I don't know which version changed that) you could open the settings and
under `edit profile` one could copy their phone number.

This is not the case anymore. Neither can you "highlight" the number to copy it.

This feature was requested and implemented w.r.t. issue #1131.

### Expected behaviour

The number in `edit profile` should be copyable (or at least highlightable).

### Actual behaviour

It is not copyable.

### Operating system

ArchLinux

### Version of Telegram Desktop

3.7.3

### Installation source

Other (unofficial) source

**Comment by 23rd** [comment]
As a workaround you can copy your phone number from the side main menu in 3.7.4 beta.

**Comment by 23rd** [comment]
Please check 3.7.5 beta.

**Comment by Weker01** [comment]
I've checked 3.7.5 beta and cannot copy or even highlight my number from the side menu but can highlight and therefore copy my number from the settings menu.

Then again I cannot copy my number under `Edit profile` nor can I copy my number in the change number screen.

For my use case it suffices that I can copy my number anywhere but I would suggest rethinking this design choice as it is not completely intuitive ihmo.
