### ISSUE TITLE
message notification sound = system sound "charging connection" OS

### ISSUE THREAD

**Issue by shredd0r** [telegramdesktop/tdesktop#24505]
### Steps to reproduce

1. disable notifications via tray icon
![image](https://user-images.githubusercontent.com/102915481/167789067-e9943d0e-1667-4294-8d04-11fdcc2131e9.png)
2. enable notifications via tray icon
![image](https://user-images.githubusercontent.com/102915481/167789183-065ed2f8-5c01-4606-936e-8a6f300f0a7f.png)
3. get new notification

### Expected behaviour

notification sound = configuration sound for chat

### Actual behaviour

notification sound = system sound for charging connection 

### Operating system

Ubuntu 20.04 LTS

### Version of Telegram Desktop

3.7.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
so, not a bug?

**Comment by ilya-fedin** [comment]
The question is what the topic of the bug report. If the topic is "charging connection" then it's not a bug as the reporter incorrectly verified this. If the topic is the fact that notification sound doesn't re-enable from this menu after app restart then it's a valid bug. Alhough, that bug always has been and is unlikely to be solved as it's a minor one and requires too much effort to solve.

**Comment by shredd0r** [comment]
> It's not "charging connection", it's message-new-instant
this notification sound should work if the in settings "notification and sound" -> "play sound" set "no sound" ?

**Comment by ilya-fedin** [comment]
> this notification sound should work if the in settings "notification and sound" -> "play sound" set "no sound" ?

In case you're using native notifications, your notification daemon can still produce sound, you need to also disabled sound in its settings
