### ISSUE TITLE
[Question] Telegram Desktop version

### ISSUE THREAD

**Issue by popov895** [telegramdesktop/tdesktop#24504]
Currently, on the Releases page I see that the latest stable version is 3.5.2, but the application I have installed (on Linux) has version 3.7.3. Why does the installed Telegram Desktop have a larger version than the latest released one?

**Comment by Brawl345** [comment]
The latest released version is 3.7(.3): https://desktop.telegram.org/changelog#v-3-7-16-04-22 The current beta version is 3.7.4 as indicated by the tags: https://github.com/telegramdesktop/tdesktop/tags

Not sure what happened here as you can still find 3.7.4 through the tags page: https://github.com/telegramdesktop/tdesktop/releases/tag/v3.7.4 but https://github.com/telegramdesktop/tdesktop/releases lists 3.5.4 (stable 3.7.3 is here: https://github.com/telegramdesktop/tdesktop/releases/tag/v3.7.3 but https://github.com/telegramdesktop/tdesktop/releases/latest points to 3.5.2...)

**Comment by Aokromes** [comment]
really strange, few days ago that was ok.

**Comment by popov895** [comment]
Yep, there's something wrong with the Releases page.

**Comment by mina354** [comment]
I agree, something must have went wrong.

**Comment by batmont** [comment]
good case to remind that verified channel https://t.me/desktop isn't updating since 2019, that's may be another alternative way to update

**Comment by mina354** [comment]
The Releases page now shows the latest released one!

**Comment by Aokromes** [comment]
it was github bug.
