### ISSUE TITLE
"The folder contents could not be displayed" when saving files

### ISSUE THREAD

**Issue by emmmhx** [telegramdesktop/tdesktop#24508]
### Steps to reproduce

1. Open Telegram Desktop
2. Save a file

### Expected behaviour

Files should be saved without prompt

### Actual behaviour

![image](https://user-images.githubusercontent.com/29679353/167993256-6c135a69-9169-40e1-8825-f6b45087e572.png)

### Operating system

Ubuntu 22.04 LTS x86_64

### Version of Telegram Desktop

3.7.3

### Installation source

Static binary from official website

**Comment by emmmhx** [comment]
Download path is set to _Default folder_. Switching between other options and changing path don't resolve the issue.

**Comment by ilya-fedin** [comment]
#24491
