### ISSUE TITLE
top-right menu doesn't open when window is maximized on Gnome 42

### ISSUE THREAD

**Issue by pmoieni** [telegramdesktop/tdesktop#24515]
### Steps to reproduce

1. Install the latest version from flathub or Fedora repo
2. open telegram and maximise the window
3. open any chat
4. click on the top-right menu icon

### Expected behaviour

Menu must open

### Actual behaviour

Menu doesn't open in maximized window

https://user-images.githubusercontent.com/62774242/168421760-ea7e9dda-d7e9-4431-8569-ba3a8b68cec9.mp4

### Operating system

Fedora Workstation 36 with Gnome 42

### Version of Telegram Desktop

3.7.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Can you switch to static binaries and find the first static binary version where it broken? Thanks.
https://github.com/telegramdesktop/tdesktop/releases

**Comment by pmoieni** [comment]
> Can you switch to static binaries and find the first static binary version where it broken? Thanks. https://github.com/telegramdesktop/tdesktop/releases

I checked binaries. the problem occurs in v 3.6.3 pre-release and later versions.

**Comment by ilya-fedin** [comment]
> the problem occurs in v 3.6.3 pre-release and later versions.

you mean there's no problem in 3.6.1?

**Comment by pmoieni** [comment]
> > the problem occurs in v 3.6.3 pre-release and later versions.
> 
> you mean there's no problem in 3.6.1?

No. There isn't.

**Comment by ilya-fedin** [comment]
Oh. In version 3.6.3, that menu got a submenu and became a separate window therefore. These kind of menus check screen bounds and looks like your windowing system returns incorrect information for this point on the screen, so Qt can't retrieve the screen from the point and the menu can't be shown therefore. I don't know what we can do. Apparently a bug in your window manager or in Qt.

**Comment by pmoieni** [comment]
@ilya-fedin  looks like it only happens in Wayland session.

**Comment by ilya-fedin** [comment]
That's logical. Window manager doesn't control that on native X.

**Comment by Sarisan** [comment]
I don't have this issue on Arch Linux, GNOME 42.1, Wayland 1.20.0

**Comment by delight-aug** [comment]
I don't have this issue either, running Telegram 4.3.1 on Fedora 37 with GNOME 43.0

**Comment by Aokromes** [comment]
@pmoieni can you try with 4.3.1?
