### ISSUE TITLE
No right-click function on telegram icon in message tray or panel

### ISSUE THREAD

**Issue by fabianHAW** [telegramdesktop/tdesktop#2451]
### Steps to reproduce
1. Start Telegram client
2. Login
3. Right click on telegram icon in message tray or panel
### Expected behaviour

It should open a little window where I can choose to open or close Telegram client.
### Actual behaviour

Nothing happens.
When I do a left-click on the icon this happens: ![screenshot from 2016-09-23 12 36 19](https://cloud.githubusercontent.com/assets/5648818/18783906/e0700318-818e-11e6-8bf9-6abf54ba48c4.png)
### Configuration

**Operating system:** 
Debian Jessie 8.6 with Gnome 3.14.1; Kernel: 3.16.36

**Version of Telegram Desktop:**
0.10.7 (last upgrade is some minutes ago)
### Workaround

In `~/TelegramDesktop/tdata/shortcuts-default.json` I found out, that it is possible to close Telegram by pressing `CTRL+q` . Thats my workaround for this, but it would be nice to get some informations about the "right-click-problem"

**Comment by AndydeCleyre** [comment]
@fabianHAW This already works in general. For example, here's a screenshot on the plasma desktop with telegram 0.10.8.

![spectacle ge7086](https://cloud.githubusercontent.com/assets/1787385/19052424/b9d44c34-8984-11e6-93f3-19620d515b0e.png)

Is that tray whatever the official gnome tray is, or some extension?

Also it looks like the current version of gnome is ~3.20.2, but the "debian-stable" version is about 2 years old. Have you tried building telegram from source and seeing if the behavior is any different?

While I can't explain your right-click or left-click behavior, I can add that the left click behavior here is pretty bizarre.

If the window is not focused/raised, the first click on the icon keeps the window out of focus and behind others, but makes the text cursor within telegram blinky. The second click on the icon then hides the telegram window. The third click raises and focuses the window, without the blinky text cursor. All subsequent clicks do nothing, unless/until the window gets out of focus.

**Comment by vanitasvitae** [comment]
It works as intended in Debian testing (Gnome Shell 3.22.1). The only negative point for me is, that both right and left click do open the dropdown menu. I'd prefer, if left click would toggle bringing the app to background/foreground.

**Comment by Aokromes** [comment]
c1aa1c5 ?
