### ISSUE TITLE
[Feature Request] Show "message not found" if forwarded message from channel is deleted

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#24517]
### Is your feature request related to a problem?

When I click on forwarded message and go to channel that forwarded from if forwarded message was deleted I don't see that it was removed. I can find out that message was deleted from channel only by guessing — just because I can't find it in channel.

You can check it by yourself here:
https://t.me/ujisdijkjisdjifsdf/2
Just click on channel name "test 1" on iOS and on Telegram Desktop. On iOS you will see popup with info about message is not found.

https://user-images.githubusercontent.com/39812401/168602088-57c51919-8417-490b-acdd-1e9600a73f37.MP4

### Describe the solution you'd like

Make popup window like it's done on iOS.

### Describe alternatives you've considered

No

**Comment by SpL1Ne** [comment]
Already implemented:
![image](https://user-images.githubusercontent.com/8836461/170548018-9dd777df-dc2f-4311-ba55-7acc6c8e0420.png)
Got this message when went to channel from deleted forwarded message.
Notification appears in the middle of the screen.

**Comment by Neurotoxin001** [comment]
Tested it on 3.7.5 beta, yes, it's already implemented.

**Comment by SpL1Ne** [comment]
I'm on stable (3.7.3 now) and this notification has be there as long as I remember.
