### ISSUE TITLE
[Feature Request]  offers "replys check" not only in the first topic message

### ISSUE THREAD

**Issue by mckaygerhard** [telegramdesktop/tdesktop#24514]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

normally telegrams offer to check the replies of a message (check first picture)
but we cannot check the chain inter-reply (check second one)

![imagen](https://user-images.githubusercontent.com/1571724/168314791-e0b9786e-6b05-4a64-ad92-4f276ecba035.png)

in first picture we have a first reply, then with right click, we found the replies (2) but as we can check in second picture, we cannot do the same in the chain messages:

![imagen](https://user-images.githubusercontent.com/1571724/168315066-ef608798-6482-4a69-a17d-dd13b84cd00d.png)

### RESUMED:

we want to see the reply option inside the second and subsequent replies too!

### Describe alternatives you've considered

errr of course in phone too.. (but write in a phone are pretty unconfortable)

same for audios.. currently does not offers same behaviour

**Comment by RememberTheAir** [comment]
This option is available just in supergroups that are linked to a channel. The option used to be available _everywhere_ for a short time after messages threads were first introduced, but was later removed, so it's a design choice that won't be rolled back, most likely. By the way, this is out of the scope of tdesktop. I suggest you to open a new ticket on https://suggestions.telegram.org
