### ISSUE TITLE
[Feature Request] hidden more! opts to disable "I have read your message" & typing status & online status

### ISSUE THREAD

**Issue by MisteryMonster** [telegramdesktop/tdesktop#24522]
### Is your feature request related to a problem?

Some time people just want seeing some message but didn't want to let you know, Last seen recently is not enough for hiding because if you have read the message you will be reveal in the little double checked! Typing status still shown, if you stop typing, it will be online again in a among of time.

### Describe the solution you'd like

you could change "do not share I have read the messages status" to on, then just single checked in the message others send it to you even you have read. But i think the better idea is corporate with "Last seen recently". When that have set, the default behavior will be not sending checked indicator & typing status in the messages.

### Describe alternatives you've considered

In a large group chat, the read message status is meaning-less, because you don't know who has read or how many were read. If that's matters, will need a new indicator design, for example a people filled with ink in percentage just like charging battery XD.

**Comment by RememberTheAir** [comment]
This would brea Telegram's Terms of Service

**Comment by MisteryMonster** [comment]
If you are talking about this:
 https://github.com/telegramdesktop/tdesktop/issues/10279#issuecomment-770389306
I would say i’m not trying ”making actions on behalf of the user without the user's knowledge.” and Last seen & online is already can be setting to prevent anyone to see in Privacy and Security

**Comment by Aokromes** [comment]
ghost mode is again ToS.
