### ISSUE TITLE
Telegram Desktop 3.7 Fails to Launch

### ISSUE THREAD

**Issue by agentl074** [telegramdesktop/tdesktop#24524]
### Steps to reproduce

Install Flathub Telegram Desktop 3.7
Attempt to Launch App
App Fails to Launch

### Expected behaviour

App Should Launch

### Actual behaviour

App Fails to Launch

### Operating system

Linux Mint 20.3 Cinnamon

### Version of Telegram Desktop

3.7

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Logs?

**Comment by agentl074** [comment]
They don't make it simple to copy and paste specific logs, but I managed these:

/var/tmp/flatpak-cache-M6BPM1/org.telegram.desktop.webview-78BPM1/repo-WPgqKc: Pulled runtime/org.telegram.desktop.webview/x86_64/stable from flathub

var-tmp-flatpak\x2dcache\x2dM6BPM1-org.telegram.desktop.webview\x2d78BPM1.mount: Succeeded.

libostree pull from 'flathub' for runtime/org.telegram.desktop.webview/x86_64/stable complete
security: GPG: summary+commit 
security: SIGN: disabled http: TLS
delta: parts: 1 loose: 6
transfer: secs: 291 size: 35.8 MB

**Comment by ilya-fedin** [comment]
What's that though? That doesn't look like tdesktop terminal output nor like tdesktop logs from the profile directory.

**Comment by agentl074** [comment]
![image](https://user-images.githubusercontent.com/102109024/168905888-a4603e43-ce7c-48b9-82cf-bf80c4e70536.png)

**Comment by agentl074** [comment]
I removed the app as soon as it failed to open. I feared that it may have been compromised.

**Comment by ilya-fedin** [comment]
Well, that's absolutely useless. tdesktop terminal output + tdesktop's log.txt file is what's needed

**Comment by agentl074** [comment]
Well, I'm not going to reinstall it if it may be compromised.

**Comment by ilya-fedin** [comment]
Without that info the issue couldn't be moved forward

**Comment by ilya-fedin** [comment]
The issue will be closed in 14 days if the requested info won't be provided. Thanks.

**Comment by agentl074** [comment]
Well, I am closing with a warning comment about the app until the situation is rectified, safely.
