### ISSUE TITLE
Incoming call hangs on a VT switch

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#24520]
### Steps to reproduce

1. Receive an incoming call.
2. Switch to a text VT.
3. Accept the call on another device.
4. End the call.

### Expected behaviour

The ringing sound is either frozen along with the X window or follows the call state independently.

### Actual behaviour

The ringing sound is being repeated all the way through, even after the call is ended, until switching back to the XOrg's VT.

### Operating system

Debian 12, compiz-reloaded 0.8.18

### Version of Telegram Desktop

3.7.5 beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Sound is processed on the main thread as well as the graphics, so if calls to X freeze the event loop, fixing that would require rewriting all the code related to sound in the application. And such a small bug doesn't worth such effort.

**Comment by bodqhrohro** [comment]
100% relevant and annoying.

**Comment by ilya-fedin** [comment]
I just checked on my VM with Linux Mint 21 Cinnamon and I can't reproduce

**Comment by bodqhrohro** [comment]
It may depend on the video driver and if the actual framebuffer console via DRM is working, I suppose.

**Comment by bodqhrohro** [comment]
It's also worth noting that compiz-reloaded suspends AIGLX cilents on the VT switch.

**Comment by bodqhrohro** [comment]
Or I was wrong, X.Org does.

**Comment by ilya-fedin** [comment]
> It may depend on the video driver and if the actual framebuffer console via DRM is working, I suppose.

It's not a tdesktop issue then

**Comment by bodqhrohro** [comment]
Why? I find it very frustrating actually that desktop software is monolith in general, and depends on GUI. I'd like to have a tiny daemon which always keeps a network connection, and launch the GUI only when needed, like it's done on Android with separate services and activities. To circumvent this, I use Pidgin, transports or so to remain always online in heavy IMs, with all their limitations, and launch the official clients only when I need rich functionality.

AFAIK, the UWP version of Skype was done this way (tiny service + full GUI), so TelegramDesktop can be split too, why not? I realize it's a major refactoring, of course.

**Comment by ilya-fedin** [comment]
> Why?

That's just how the stack works I believe, so this is not fixable. And given that you claim this is hardware dependent and I don't have such a hardware, I wouldn't be able to reproduce that, what is required to fix, so this issue will just be open forever. Given that this issue is very minor and niche, I don't think it should remain open.

> why not?

This is not a goal, sorry.

> I realize it's a major refactoring, of course.

This won't happen if you're not ready to do that on your own.

**Comment by bodqhrohro** [comment]
https://user-images.githubusercontent.com/2134486/201797800-09afa4d9-1c46-47d2-8395-a277306780e8.mp4
