### ISSUE TITLE
Window not maximized properly via top "sticky" edge 

### ISSUE THREAD

**Issue by mrkeuz** [telegramdesktop/tdesktop#24523]
### Steps to reproduce

1. Drag'n'drop telegram window to top of screen (with short hold timeout)

See screencast:

![Telegram_sticky_edge_issue](https://user-images.githubusercontent.com/6247921/168820080-cfbfae8d-886c-472c-a15f-47288b5fd946.gif)

### Expected behaviour

- Window do maximized on top sticky edge with any holding timeout

Any other app windows reacted fine with any timeouts (include Electron app like VSCode). 
You need just "drop" window to top bar.

### Actual behaviour

- Window only draw borders and "blur" whole screen 
- Window is NOT maximized, but also NOT in window mode (see screencast above)
- Maximized only if you hold the window long enough (sometimes)

Any other app windows reacted fine (include Electron app like VSCode)

### Operating system

Ubuntu 20.04.4 LTS (Gnome 3.36.8, X11)

### Version of Telegram Desktop

3.7.3

### Installation source

Snap

**Comment by mrkeuz** [comment]
I can. But I have no idea how to change qt version. It needs to get some nightly build or what? There are some instructions for this?

**Comment by mrkeuz** [comment]
upd: I ran qbittorrent v4.4.2 (qt 6.2.4) - it has no any issues.

**Comment by ilya-fedin** [comment]
This is yet another appearance of #10348

**Comment by mrkeuz** [comment]
As mentioned in https://github.com/telegramdesktop/tdesktop/issues/10348#issuecomment-926984167

`Preference -> Advanced -> Use system window frame` - solve the problem

Thanks folks! 🚀

**Comment by mrkeuz** [comment]
Just FYI. Just in case.

"Voice call" window still has problems even with `Use system window frame` option.
