### ISSUE TITLE
[Question] Misclick on call button

### ISSUE THREAD

**Issue by kvlvgg** [telegramdesktop/tdesktop#24530]
Is it possible to set not 100% height for this buttons? I often misclick on call button, then I want to minimize the window.

![image](https://user-images.githubusercontent.com/80147461/169279298-4de2dbcb-04e9-4933-a461-55799ddf1814.png)

**Comment by Aokromes** [comment]
no.
https://github.com/telegramdesktop/tdesktop/issues/24607
