### ISSUE TITLE
[Feature Request] Increase or remove the account limit on 64 bit builds?

### ISSUE THREAD

**Issue by BitesizedLion** [telegramdesktop/tdesktop#24532]
### Is your feature request related to a problem?

The 3 account limit is not enough for some users, like me, there have been past issues about this however I cannot comment on them as they have been closed and the discussion locked, #2405, #9038, #9868, #10272, #13937, #14770.

### Describe the solution you'd like

I would like you to remove or increase the account limit (to maybe 10), at least on 64bit builds.

### Describe alternatives you've considered

I myself have edited and compiled tdesktop myself to up the limit, however this means I do not get updates.

I know the portable version is also an alternative (however that is too much of a nuisance to switch between).

### Additional context

The past issues have been closed because 32bit builds tend to crash when they hit the 2GB memory limit, however as a solution, can you not check if the application is 32bit or 64bit and then increase the limit if it is 64bit?

@ilya-fedin I know you have commented on previous issues about this, what do you think? Would it be possible...?

**Comment by ilya-fedin** [comment]
> I know you have commented on previous issues about this, what do you think?

What I think is completely irrelevant since I'm not who decides

**Comment by john-preston** [comment]
@BitesizedLion It will be a paid feature 🙈

**Comment by RadRussianRus** [comment]
But it's the client-side limit. Could that mean that any unofficial app that increase account limit should stick to 3 accounts too? 🤔

**Comment by bydlome** [comment]
> But it's the client-side limit. Could that mean that any unofficial app that increase account limit should stick to 3 accounts too? 🤔

It's too bad that telegram began to use ugly methods of monetization of its functionality. I understand the ban on blocking ads, more pins too. Restrictions on accounts are stupid, there are no positive emotions, only irritation and a feeling that the messenger is going the wrong way.

**Comment by john-preston** [comment]
@RadRussianRus Idk

**Comment by RadRussianRus** [comment]
Well, probably we need to wait until the release to see where it it all goes.

**Comment by nikitasius** [comment]
> But it's the client-side limit
@RadRussianRus 
All TG's "features" are mostly client side. The only stuff they control is the api limitations and api restrictions.
As i see it use same code as a simple TG. Well, looks i need to fork the desktop client.
You can easily increase to 32 w/o any issues and even more. Just check before sessions code.

**Comment by RadRussianRus** [comment]
@nikitasius 

> All TG's "features" are mostly client side.

I've meant "purely client-side". For example, cloud folders without server will lose it's sync ability, so they're not purely client-side. But things like account limit couldn't be controlled by server in any way. Even if some function is introduced, you can simply forge the request without losing anything.

> As i see it use same code as a simple TG. Well, looks i need to fork the desktop client.

Forks are already increasing account limit. The question is if it counts as Telegram API ToS violation or not. With upcoming Telegram Premium the question "will there be more restrictions" is interesting.

> You can easily increase to 32 w/o any issues and even more.

If you don't count high RAM consumption, that is.

**Comment by nikitasius** [comment]
> If you don't count high RAM consumption, that is.
Original code should be modified, sure.

TG TOS: remember that they can change it the way they want when they want. So just ignore it.

**Comment by ilya-fedin** [comment]
@nikitasius have an empty line after quote

**Comment by nikitasius** [comment]
> @nikitasius have an empty line after quote

done. So personally just ignore the TOS.

**Comment by aditya-yadav-27** [comment]
> It's too bad that telegram began to use ugly methods of monetization of its functionality. I understand the ban on blocking ads, more pins too. Restrictions on accounts are stupid, there are no positive emotions, only irritation and a feeling that the messenger is going the wrong way.

How is it bad? a normal user will never feel restricted with current telegram features, the proffesional users who want to play with telegram can buy premium and those who want to support telegram. It's been more than 8 years that telegram is serving it users with many features more than any other app for free. There are 2 ways telegram can earn money
1. By selling your data like facebook
2. By introducing premium features (current features will remain free forever.)
Choice is yours. I am completely happy with this feature.

**Comment by Aokromes** [comment]
> > But it's the client-side limit. Could that mean that any unofficial app that increase account limit should stick to 3 accounts too? 🤔
> 
> It's too bad that telegram began to use ugly methods of monetization of its functionality. I understand the ban on blocking ads, more pins too. Restrictions on accounts are stupid, there are no positive emotions, only irritation and a feeling that the messenger is going the wrong way.

as power user, not related to telegram at all, i only help preston to maintain bugtracker clean:
durov understimated the grow of users and costs, that's why he is charging for features only few users use, hell, those "restrictions on accounts" are already there, he is not adding new restrictions, if you need > 3 accounts on telegram very likely you are doing commercial  use of telegram.

**Comment by BitesizedLion** [comment]
> if you need > 3 accounts on telegram very likely you are doing commercial use of telegram.

Personally, I don't (I just like to keep some pseudonyms separate), don't get me wrong I understand that most >3 acc users are commercial

**Comment by Aokromes** [comment]
> > if you need > 3 accounts on telegram very likely you are doing commercial use of telegram.
> 
> Personally, I don't (I just like to keep some pseudonyms separate), don't get me wrong I understand that most >3 acc users are commercial

you know, now with talk as channel you don't need different accounts for that :)

**Comment by davtur19** [comment]
Will the parameters to use multiple telegram instances (therefore multiple accounts) remain or be removed to avoid having multiple accounts?
`-many -workdir`

**Comment by ilya-fedin** [comment]
`-many` was removed long time ago

**Comment by bydlome** [comment]
> > > But it's the client-side limit. Could that mean that any unofficial app that increase account limit should stick to 3 accounts too? 🤔
> > 
> > It's too bad that telegram began to use ugly methods of monetization of its functionality. I understand the ban on blocking ads, more pins too. Restrictions on accounts are stupid, there are no positive emotions, only irritation and a feeling that the messenger is going the wrong way.
> 
> as power user, not related to telegram at all, i only help preston to maintain bugtracker clean:
> durov understimated the grow of users and costs, that's why he is charging for features only few users use, hell, those "restrictions on accounts" are already there, he is not adding new restrictions, if you need > 3 accounts on telegram very likely you are doing commercial  use of telegram. 

This is a restriction for third-party applications, not against commercial use. people who earn money in telegram have the money to circumvent any restrictions. companies are willing to just pay for them. business accounts are good, or just not bad.

I want telegram to be financially independent and have no problems with money, but this restriction on accounts is disgusting towards users, not commerce. I'm sorry if my words offended someone.

**Comment by nikitasius** [comment]
TG use closed-source nodes :popcorn:

**Comment by BitesizedLion** [comment]
![image](https://user-images.githubusercontent.com/42980888/170690703-471e6431-5220-4b72-9710-ab68830a3f6a.png)
