### ISSUE TITLE
[Question]Complie tdesktop and execute "tdesktop\Telegram\build\prepare\win.bat" and print error "KeyError: 'Platform'"

### ISSUE THREAD

**Issue by ChenMoGe2** [telegramdesktop/tdesktop#24537]
I use the markdown [https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md](url) and execute the code.When I "tdesktop\Telegram\build\prepare\win.bat" it print KeyError: 'Platform' FAILED.

I execute the code using "x64 Native Tools Command Prompt for VS 2022" in "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2022\Visual Studio Tools\VC" and all the thridparty I install already.

The tdesktop version is 3.7.3.Os version is win10 x64.My BuildPath is "D:\CppProjects\tdesktop"

I see the issue [https://github.com/telegramdesktop/tdesktop/issues/17373](https://github.com/telegramdesktop/tdesktop/issues/17373) is seem like mine but it solve nothing

Someone can help me?Thank you

**Comment by 23rd** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16939.

**Comment by chienbinhso14** [comment]
Just try: **set Platform=x64** on x64 Native Tools Command Prompt for VS 2022
