### ISSUE TITLE
Add to spam list if add many admin rights to group

### ISSUE THREAD

**Issue by verificatorrus** [telegramdesktop/tdesktop#24534]
### Steps to reproduce

1. Create public group
2. Share link with your friends
3. Wait for 20 users in group
4. Give admin rights for every iser in group

### Expected behaviour

Telegram add your account to spam list

### Actual behaviour

It's normal for everyone have admin rights in group. It's called democracy.

### Operating system

Any

### Version of Telegram Desktop

Any

### Installation source

Mac App Store

**Comment by Aokromes** [comment]
such issue belongs to https://bugs.telegram.org/
