### ISSUE TITLE
Save File Dialog does NOT suggest default file names to save downloaded files

### ISSUE THREAD

**Issue by soviet-man** [telegramdesktop/tdesktop#24535]
### Steps to reproduce

Right click to save any image or video.

### Expected behaviour

Save File Dialog should suggest file name before downloading file

### Actual behaviour

Save File Dialog does NOT suggest file name. Every time I want to save any file I have to invent file name including extension. It's unconvinient.

### Operating system

Manjaro XFCE

### Version of Telegram Desktop

3.7.3

### Installation source

Static binary from official website

**Comment by emmmhx** [comment]
Can confirm this issue on Manjaro Gnome as well.

**Comment by emmmhx** [comment]
@soviet-man is telegram-desktop package from Pacman affected too? What about previous versions of telegram-desktop?

**Comment by soviet-man** [comment]
> @soviet-man is telegram-desktop package from Pacman affected too? What about previous versions of telegram-desktop?

I install Telegram Desktop from official Manjaro repo. Previous vesrion 3.7.1 was with normal save dialog. This bug occured in latest 3.7.3 version.

**Comment by ilya-fedin** [comment]
> Previous version 3.7.1 was with normal save dialog.

This might be other package updated in your system. Have you checked 3.7.1 after the bug happened? I would bet that's the case as nothing related to save dialog was changed in these version.

**Comment by emmmhx** [comment]
@ilya-fedin I've checked 3.7.1 right now, and it's affected too

**Comment by ilya-fedin** [comment]
So it's a regression in one of system packages, not in tdesktop.

**Comment by emmmhx** [comment]
@ilya-fedin how to keep track of this?

**Comment by ilya-fedin** [comment]
@emmmhx I dunno, apparently you need to find your distro bugtracker or forum and raise your problem there. If the community would find the cause, you're lucky, if not, you're out of luck...

**Comment by ilya-fedin** [comment]
Apparently something is wrong with new versions of gtk as it's the second issue about save dialog in a GTK-based envrionment

**Comment by mareg** [comment]
Telegram 4.0.2 here - issue still persists.

Firefox and Chrome seem to be using same new GTK toolkit and it works fine with them to save files, but not with Telegram.

I appreciate it may be a `3rd party issue`, but has it been reported upstream?

**Comment by emmmhx** [comment]
No updates?

**Comment by soviet-man** [comment]
@emmmhx, my Telegram Desktop 4.0.2 has normal File Save Dialog with default names

**Comment by emmmhx** [comment]
> @emmmhx, my Telegram Desktop 4.0.2 has normal File Save Dialog with default names

On Manjaro XFCE?

**Comment by soviet-man** [comment]
@emmmhx, yes, exactly. Manjaro XFCE, Telegram Desktop 4.0.2

**Comment by olegon-ru** [comment]
The same trouble with Fedora 36 (Gnome). I resolved it by removing xdg-portal-desktop-gnome some time ago, but nowaday it's not installed, but problem exists... Is any ideas, how to find workaround for this? Very strange SaveAs dialog...
![gnomesave](https://user-images.githubusercontent.com/2420162/181245344-d7abe185-6777-4fd0-bc0f-6944345d860a.png)

**Comment by ilya-fedin** [comment]
This is closed as a duplicate of #24491. #24491 has links to issues in the affected components. Please move the dicussion to affected components' bugreports, nothing colud be from tdesktop side.

**Comment by ilya-fedin** [comment]
@olegon-ru it's xdg-desktop-portal-gnome on you screenshot. It's somehow still installed on your system.
