### ISSUE TITLE
Autodelete doesn't work

### ISSUE THREAD

**Issue by mayeaux** [telegramdesktop/tdesktop#24539]
### Steps to reproduce

Set autodelete for one week

### Expected behaviour

Messages older than a week should be deleted

### Actual behaviour

All the messages remain

### Operating system

All platforms

### Version of Telegram Desktop

Irrelevant

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
> ### Steps to reproduce
> Set autodelete for one week
> 
> ### Expected behaviour
> Messages older than a week should be deleted
> 
> ### Actual behaviour
> All the messages remain

messages before you enabled autodelete will remain, and it's not a bug. if "all platforms" means android and ios too for messages created after you enabled autodelete remains it belongs to https://bugs.telegram.org

**Comment by mayeaux** [comment]
So how do you delete the ones that already exist but are more than a week old? Like I said, it's functionally broken, since there is no way to do that

**Comment by RememberTheAir** [comment]
you can just select the message, delete them, and toggle the "also delete for" checkbox. This works in private chats and also in groups/channels where you're admin

**Comment by mayeaux** [comment]
So go back and manually select hundreds if not thousands of messages? For me, the feature is functionally broken, and I don't think 'well this is how other apps do it' is a good argument thankfully Telegram doesn't base their decision making on that.
