### ISSUE TITLE
Hyperlink Mention doesnt work on tdesktop

### ISSUE THREAD

**Issue by aditya-yadav-27** [telegramdesktop/tdesktop#24536]
### Steps to reproduce

1. Try to mention a user without username in a supergroup/group

### Expected behaviour

The user should be mentioned and on clicking on the mention text user's profile should be opened

### Actual behaviour

The user's name is being sent as plain text and the user is not mentioning nor the hyperlink is created
reference video:
https://www.veed.io/view/4c18b67e-b95e-4918-9b66-d479afbd7011?sharingWidget=true

### Operating system

Fedora Workstation 36 linux

### Version of Telegram Desktop

tdesktop 3.7.5 beta

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
works for me on windows 11... if i get correctly the report.

**Comment by c0re100** [comment]
I guess it's not a bug.
If a user enabled Forwarded messages privacy,
those user and you should be in the same group,
otherwise you can't mention a user without username in that group.

**Comment by aditya-yadav-27** [comment]
> I guess it's not a bug. If a user enabled Forwarded messages privacy, those user and you should be in the same group, otherwise you can't mention a user without username in that group.

the user is in the group where I am trying to mention him

**Comment by aditya-yadav-27** [comment]
I am closing this issue as this is not happening anymore :D
