### ISSUE TITLE
Two separate landing pages for Mac OSX desktop client download.

### ISSUE THREAD

**Issue by cyoung** [telegramdesktop/tdesktop#2453]
### Steps to reproduce
1. Go to https://desktop.telegram.org/ on a Mac OSX device using Chrome. Same for https://macos.telegram.org/.
2. Download the files.
3. Compare the two versions.

### Expected behaviour
The two file downloads should be the same, or the two different download landing pages should be merged.

### Actual behaviour
Two different versions are served, one file "tsetup.0.10.7.dmg" did not have the Secret Chat feature, the other download "telegram.dmg" contained "Official Telegram Messenger client for macOS Version 2.22.50247".

### Configuration
Mac OSX El Capitan 10.11.6

**Version of Telegram Desktop:** who knows.

### Logs
None.

**Comment by john-preston** [comment]
@cyoung The version from https://macos.telegram.org/ is a separate macOS app, that has its own github repository and has nothing to do with Telegram Desktop.
