### ISSUE TITLE
Tdesktop uses the raw server entropy to establish E2EE calls

### ISSUE THREAD

**Issue by sergiotarxz** [telegramdesktop/tdesktop#24540]
### Steps to reproduce

1. Look at https://github.com/telegramdesktop/tdesktop/blob/36b8d03b1d455f9cca8d32ae5b33c419a104d6fa/Telegram/SourceFiles/calls/calls_instance.cpp#L392
2. At https://github.com/telegramdesktop/tdesktop/blob/36b8d03b1d455f9cca8d32ae5b33c419a104d6fa/Telegram/SourceFiles/calls/calls_instance.cpp#L350
3. https://github.com/telegramdesktop/tdesktop/blob/36b8d03b1d455f9cca8d32ae5b33c419a104d6fa/Telegram/SourceFiles/calls/calls_call.cpp#L264

### Expected behaviour

The randomness should be generated in the device instead so the server cannot intercept those comunications.

### Actual behaviour

The randomness used for the key comes only from the server thus compromising the privacy of users.

### Operating system

Gentoo GNU Linux

### Version of Telegram Desktop

master

### Installation source

Other (unofficial) source

**Comment by sergiotarxz** [comment]
In android server randomness is used but it is randomized further in the device:
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/18d0f5e43537c0c9e02a33d12889d030abac2290/TMessagesProj/src/main/java/org/telegram/messenger/voip/VoIPService.java#L907
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/18d0f5e43537c0c9e02a33d12889d030abac2290/TMessagesProj/src/main/java/org/telegram/messenger/voip/VoIPService.java#L930
In desktop there is no need to get server entropy at all since desktop computers are not constrained in the entropy they can get for example from urandom.

**Comment by sergiotarxz** [comment]
Just citing docs:

https://core.telegram.org/api/end-to-end

```
If the client needs additional entropy for the random number generator, it can pass the random_length parameter (random_length> 0) so the server generates its own random sequence random of the appropriate length. Important: using the server's random sequence in its raw form may be unsafe, it must be combined with a client sequence.
```

**Comment by john-preston** [comment]
@sergiotarxz You've stopped your research at a generateModExpFirst call. But if you look further you'll see that passed random is named randomSeed and it is used as an additional random, not the only one.

**Comment by sergiotarxz** [comment]
@john-preston I looked further and I am happy to know I am wrong, I am still getting used to the codebase I am closing this issue.
