### ISSUE TITLE
Broken russian dictionary

### ISSUE THREAD

**Issue by timsofteng** [telegramdesktop/tdesktop#24544]
### Steps to reproduce

1. Install tdesktop 3.7.3
2. Download russian dictionary.

### Expected behaviour

Spell checking should work

### Actual behaviour

Spell checking doesnt work.
Infinite loading.

### Operating system

Alpine edge

### Version of Telegram Desktop

3.7.7

### Installation source

Other (unofficial) source

### Logs

```shell
codecForName: ucnv_open failed KOI8-R U_FILE_ACCESS_ERROR
```

**Comment by ilya-fedin** [comment]
Can you check the official binary? That sounds like a problem of third-party build.

**Comment by timsofteng** [comment]
> Can you check the official binary? That sounds like a problem of third-party build.

does it binary works on musl?

**Comment by ilya-fedin** [comment]
No, it depends on glibc

**Comment by timsofteng** [comment]
> No, it depends on glibc

Got it. Tell me if I can help somehow to debug it.

**Comment by ilya-fedin** [comment]
I don't think you need to debug it, the error looks like your distro just lacks KOI8-R converting capability that is required for your dictionary.
