### ISSUE TITLE
[Question] Why does Telegram allow list on German provider of internet?

### ISSUE THREAD

**Issue by DeafMan1983** [telegramdesktop/tdesktop#24542]
Hello Telegrammers,

I don't care about Telegram in Germany because Telegram already banned in Germany since abuser insults to kill to politicians that is why It doesn't allow list in Ubuntu Software if you live in Germany.

**Please respect German government!**
If you are publisher then you should set disallowed country as Germany. Thank you!

I hope you understand because German politicians are scared to Telegram. If I use Ubuntu 22.04 They can catch me if they think I have Telegram on Ubuntu. Please remove Telegram from Software in Germany. Thank you!

Kind regards!

**Comment by Aokromes** [comment]
telegram doesn't maintains linux distribution packates.

**Comment by Jinnaix** [comment]
> Hello Telegrammers,
> 
> I don't care about Telegram in Germany because Telegram already banned in Germany since abuser insults to kill to politicians that is why It doesn't allow list in Ubuntu Software if you live in Germany.
> 
> **Please respect German government!** If you are publisher then you should set disallowed country as Germany. Thank you!
> 
> I hope you understand because German politicians are scared to Telegram. If I use Ubuntu 22.04 They can catch me if they think I have Telegram on Ubuntu. Please remove Telegram from Software in Germany. Thank you!
> 
> Kind regards!

Fake news.
Telegram is not banned in Germany and you also dont get on a goverments list for having or using it.

**Comment by DeafMan1983** [comment]
@Aokromes You say wrong! 
![image](https://user-images.githubusercontent.com/57066679/170224756-29b926d0-8944-4de7-9f9e-4549b31fe11e.png)

@Jinnaix are you criminally? Have fun! You will see in German jailhouse. "Fake-News" that is not correctly. If you violate this then you will get punishment.
