### ISSUE TITLE
Up key text edit bug (1/2)

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2454]
### Steps to reproduce
1. Write message 1 via TDesktop and close chat.
2. Write message 2 via another client (I used Android version) and close chat.
3. Open chat and press "Up" key.
### Expected behaviour

An editor for message 2 should be opened
### Actual behaviour

An editor for message 1 is opened
### Configuration

**Operating system:** Windows 10 x64 LTSB (Not Anniversary update)  
**Version of Telegram Desktop:** <s>0.10.8</s> 0.10.17 alpha

**Comment by Kondra007** [comment]
This and #2455 are still here: 0.10.17 alpha.

**Comment by asgeirrr** [comment]
I can still reproduce this bug in version 1.0.14. It's a little quirk but it can surprise you;)

**Comment by MasterGroosha** [comment]
@asgeirr unfortunately this is intended behaviour (as explained in #3104), however the dev said it might be changed in future, so I keep the issue open.

**Comment by auchri** [comment]
Should be fixed by https://github.com/telegramdesktop/tdesktop/commit/e6c0f0f774c328f6c5b991040aed79f00859d3dd.
