### ISSUE TITLE
Personal account is not listed in the "Send message as" dialog

### ISSUE THREAD

**Issue by ruv** [telegramdesktop/tdesktop#24548]
### Steps to reproduce

1. Be an owner of a public channel and a private channel having a connected group for discussion (where you are also an owner).
2. Open the private channel (you are an owner).
3. Click the "Leave a comment" link for some message.
4. Click on an avatar icon at the left of the input box (to open the "Send message as..." dialog).

### Expected behaviour

The caption says: "Choose whether you want to be displayed as your personal account or as your channel".

Your personal account should be shown in the list among the channels.

### Actual behaviour

The caption says: "Choose whether you want to be displayed as your personal account or as your channel".

Your personal account **is not shown** in the list, only your channels are shown.

This same issue is reproducible in Telegram Desktop on Windows, and in Telegram for Android.

### Operating system

Windows 10

### Version of Telegram Desktop

3.7.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I think this is intended, but you can find out / report on https://bugs.telegram.org
