### ISSUE TITLE
Schedule support

### ISSUE THREAD

**Issue by woltron** [telegramdesktop/tdesktop#24546]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

It would be nice if the telegram implemented the ability to maintain a calendar in a group or chat for planning events. As well as importing dates / times / event names into the phone / computer calendar (for example, through the .ics format

### Describe alternatives you've considered

No alternatives

**Comment by RememberTheAir** [comment]
this feature request belongs to https://suggestions.telegram.org
