### ISSUE TITLE
Save as... dialog is broken on Fedora 36

### ISSUE THREAD

**Issue by mareg** [telegramdesktop/tdesktop#24549]
### Steps to reproduce

1. right click on image and select "save as..."

### Expected behaviour

Native OS save as modal window that works appears with filename pre-filled (as it used to work).

### Actual behaviour

Not native modal window opens.
File name is not selected.
When I start typing name of the file, it switches to search box and starts searching instead.
Usability nightmare.

### Operating system

Fedora 36 (Linux) with MATE Desktop

### Version of Telegram Desktop

telegram-desktop-3.7.3-1.fc36.x86_64

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by mareg** [comment]
I've installed it from the rpmfusion rpm repository, which contains repacked official build as an rpm package, so I can get updates automatically when they're available. Is that not good enough?

**Comment by Aokromes** [comment]
no, distribution shipped versions a lot of times have bugs official versions doesn't.

**Comment by mareg** [comment]
Removed one installed from rpmfusion, installed one from flatpak, lost all settings annoyingly, but problem is not resolved - same issues remain:
1) filename is not pre-filled
2) when I start typing anything, it switches to search
3) it's not native modal window

Here's what I'm seeing - similar colours/style to Telegram, yet the moment I pressed letter `s` it opened a search and started searching for files which names start with letter `s`:
![telegram-incorrect-save-as-window](https://user-images.githubusercontent.com/533217/170672012-b3650358-05a9-4943-8741-2e4235ec1366.png)

Here's what I was expecting to see:
![telegram-expected-save-as-window](https://user-images.githubusercontent.com/533217/170672026-c394c36b-58c2-451b-a5ec-d6b5674084c0.png)

**Comment by mareg** [comment]
Tried the tsetup.3.7.3.tar.xz too, as expected - it picked up settings of the original installation from the rpmfusion repository (so proves rpmfusion version is just a repack of the original binary).

Unfortunately, problem persists.

**Comment by xvitaly** [comment]
> Tried the tsetup.3.7.3.tar.xz too, as expected - it picked up settings of the original installation from the rpmfusion repository (so proves rpmfusion version is just a repack of the original binary).

No. RPM Fusion's package [built from sources](https://github.com/rpmfusion/telegram-desktop/blob/master/telegram-desktop.spec) and not a repack.
