### ISSUE TITLE
Not possible to start telegram-desktop

### ISSUE THREAD

**Issue by thyeun** [telegramdesktop/tdesktop#24553]
### Steps to reproduce

1. Run at terminal ```telegram-desktop```

### Expected behaviour

should start telegram-desktop

### Actual behaviour

getting error message below
```
telegram-desktop: symbol lookup error: /usr/lib/libgiomm-2.4.so.1: undefined symbol: _ZN4GliB11VariantBaseC1EP9_GVariantb
```

### Operating system

Arch linux (5.17.9-arch1-1)

### Version of Telegram Desktop

3.7.3

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
This is a problem of your third-party build, no one here can help you.

**Comment by thyeun** [comment]
@ilya-fedin thanks, and i found out the solution also
