### ISSUE TITLE
Images and videos are not opening in full screen mode

### ISSUE THREAD

**Issue by amaralex1** [telegramdesktop/tdesktop#24550]
### Steps to reproduce

1. Get message with video or image
2. Try to click on it to open in full screen

### Expected behaviour

3. Image opened in full screen, video starts in full screen with sound

### Actual behaviour

3. See that image\video are not opening in front
4. Telegram works like media was opened (telegram ico in bottom bar shows another window (like second layer))
5. To use another functions of app you should first use one click to refocus on app, ico shows that there is now second window and you can work as before
6. You can see in video that behavior

https://user-images.githubusercontent.com/28701974/170665495-726f5c1b-2aeb-49c1-9842-f37ba9bc693c.mp4

7. To make it work you need to reload app from "Quit Telegram" from system tray, cross button don't solve the issue.
8. Same problem occur for me couple of months once or twice in week

### Operating system

Windows 10

### Version of Telegram Desktop

3.7.3 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#17206
