### ISSUE TITLE
[Feature Request] Press "F" to full screen video

### ISSUE THREAD

**Issue by kr-ilya** [telegramdesktop/tdesktop#24557]
### Is your feature request related to a problem?

There is no hotkey to open the video in fullscreen mode

### Describe the solution you'd like

Add a hotkey (F) to open the video in full-screen mode

### Describe alternatives you've considered

-

**Comment by 23rd** [comment]
> There is no hotkey to open the video in fullscreen mode

Did you try `Ctrl + F`?

**Comment by kr-ilya** [comment]
> > There is no hotkey to open the video in fullscreen mode
> 
> Did you try `Ctrl + F`?

Yes, it works. It is strange that there is no clue that there is such a hotkey
