### ISSUE TITLE
Chats return from archive after new messages

### ISSUE THREAD

**Issue by ogoun** [telegramdesktop/tdesktop#24558]
### Steps to reproduce

1. Move chat to Archive
2. Send or receive message in this chat

### Expected behaviour

Chat stay in archive

### Actual behaviour

Chat go out from archive in general chat list.
This behavior causes confusion in chat lists. This was not the case in previous versions.

### Operating system

Windows 11

### Version of Telegram Desktop

3.7.3 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
cannot reproduce on 3.7.5.
maybe some of the archived chats notified you?

**Comment by ilya-fedin** [comment]
> maybe some of the archived chats notified you?

I think he forgot to disable notifications before archiving the chats. The reason why this wasn't the case in 'previous versions' might be because he archived previously only from other clients. Or maybe he did that long time ago and forgot the details.
