### ISSUE TITLE
Up key text edit bug (2/2)

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2455]
### Steps to reproduce
1. Write message via TDesktop
2. Close application completely
3. Start application.
4. Enter that chat where you wrote message
5. Press "up" button
### Expected behaviour

An editor for message should be opened
### Actual behaviour

You scroll up with every button press
### Configuration

**Operating system:** Windows 10 x64 LTSB (Not Anniversary update)
**Version of Telegram Desktop:** <s>0.10.8</s> 0.10.17 alpha

**Comment by MasterGroosha** [comment]
Still here: 0.10.26 alpha

**Comment by jt3k** [comment]
This error is very annoying. And it sometimes arises even if you do not close the application, but between sending the previous one.

You expect that the editing will open, but instead it scrolls the chat log up

**Comment by auchri** [comment]
Should be fixed by https://github.com/telegramdesktop/tdesktop/commit/e6c0f0f774c328f6c5b991040aed79f00859d3dd.
