### ISSUE TITLE
Feature Request: More Zoom Option for Hi-Res Displays

### ISSUE THREAD

**Issue by ch3ckmat3** [telegramdesktop/tdesktop#2456]
### Steps to reproduce
1.  Zoom function
2. 
3. 

### Expected behaviour
More than 200% zoom for very Hi-Res Displays

### Actual behaviour
Only 200% zoom in allowed

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** New

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by auchri** [comment]
Duplicate #2144
