### ISSUE TITLE
[Feature Request] Please add the Chinese language package to the official installation package

### ISSUE THREAD

**Issue by CNMan** [telegramdesktop/tdesktop#24562]
### Is your feature request related to a problem?

Fake installation packages containing viruses and Trojans appear every day.
https://bbs.kafan.cn/forum-31-1.html
![Screenshot from 2022-05-31 17-33-41](https://user-images.githubusercontent.com/8692234/171143794-11834b9e-83e9-4f98-9d43-a64e2ac620f1.png)
![Screenshot from 2022-05-31 17-49-32](https://user-images.githubusercontent.com/8692234/171146029-a1644fd9-66dd-420a-bc4c-45a38d21ecb5.png)

### Describe the solution you'd like

add the Chinese language package to the official installation package

### Describe alternatives you've considered

nothing

**Comment by CNMan** [comment]
https://github.com/Jirehlov/IoCs/blob/main/fake_telegram.txt

**Comment by john-preston** [comment]
https://t.me/setlanguage/zh-hans-beta
https://t.me/setlanguage/zh-hant-beta

I guess only that for now.
