### ISSUE TITLE
Error message after opening Telegram via terminal in Distro Deepin 20.6

### ISSUE THREAD

**Issue by serial02** [telegramdesktop/tdesktop#24569]
### Steps to reproduce

After opening Telegram via terminal, error messages appear in the terminal.
 Please check the error messages if they have any relevance and, if so, make the necessary corrections.
 Language change was only possible after rebooting the system

### Expected behaviour

I wish that after opening the application via terminal the error messages that appear are corrected.
 That after opening the application the QR appears immediately.  The delay in appearing the QR is too long!

 After installation, it was necessary to restart in order to change the language from English to PT_BR

### Actual behaviour

After opening Telegram via terminal, error messages appear in the terminal.
 Please check the error messages if they have any relevance and, if so, make the necessary corrections.
 Language change was only possible after rebooting the system

Attached logs, images and videos

![Capturar_deepin-terminal_20220602195958](https://user-images.githubusercontent.com/32621790/171754173-d6b047da-6528-448f-a92c-5f030f622d56.png)

![Capturar_telegram-desktop_20220602195715](https://user-images.githubusercontent.com/32621790/171754149-36dcd2c3-8f75-4a50-b1f5-0c3dd5b02020.png)

https://user-images.githubusercontent.com/32621790/171756290-aa221695-5e8a-45ad-bd6f-4218b20bc436.mp4

### Operating system

Deepin 20.6

### Version of Telegram Desktop

May 2, 2022 Version 3.7.3 

### Installation source

Flatpak

### Logs

```shell
Deepin@Deepin-PC:~$ flatpak run org.telegram.desktop
QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700

(telegram-desktop:3): GLib-GObject-CRITICAL **: 20:08:12.875: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(telegram-desktop:3): dbind-WARNING **: 20:08:12.947: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700
[ALSOFT] (EE) Failed to set real-time priority for thread: Operação não permitida (1)
QPainter::begin: Paint device returned engine == 0, type: 3
QWidget::render: Cannot render with an inactive painter
QPainter::begin: Paint device returned engine == 0, type: 3
QWidget::render: Cannot render with an inactive painter
```

**Comment by ilya-fedin** [comment]
Apparently you just have not-so-fast connectivity to Telegram servers or maybe the servers were overloaded when you tried to get QR code

**Comment by john-preston** [comment]
I think that the problem with QR may be unrelated to any messages in the terminal and was fixed by this:

https://github.com/telegramdesktop/tdesktop/commit/06e2724731f1aa4f6c1cb0b53e0947c2d03ebb3c
