### ISSUE TITLE
Telegram stealing Ubuntu lock screen input

### ISSUE THREAD

**Issue by gizahNL** [telegramdesktop/tdesktop#24565]
This should be an opt-in feature. This behaviour easily captures passwords by accident

_Originally posted by @jaybuidl in https://github.com/telegramdesktop/tdesktop/issues/7887#issuecomment-683514428_

This is stealing input from the lock screen in Ubuntu.

**Comment by ilya-fedin** [comment]
If something steals input on your screen, it's either a bug in your lock screen or window manager
