### ISSUE TITLE
[Feature Request] Incremental backups of telegram export (marker for last backup, and diff between old and current export)

### ISSUE THREAD

**Issue by anacondaq** [telegramdesktop/tdesktop#24560]
### Is your feature request related to a problem?

My problem -> I'm extremely old user of Telegram, and Telegram my main messanger for many years.
I have hundreds of conversations, with a lot of files there.

Exporting all chats takes up to 20-25 hours. That is way too much.

### Describe the solution you'd like

Ability to avoid FULL export. Instead - export only data were added AFTER last full export.

I.E.: first time i export all telegram data on for example Feb 12, 2022. Export size ~50GB (inside all chats history since 2016)
Next time I export all telegram data on May 20, 2022. Export size must be NEW_CURRENT_SIZE - 50GB = or around 50-100MB (just numbers from air, related to a new chats history since 12 Feb up to date when the current export done).

Some kind of incremental backups, or differental backups. Not full chat export, but parically. 

### Describe alternatives you've considered

Exporing 1 by 1 chat - bad idea, because data added to all chats & conversations.
Ability to add FROM WHAT date to export - great must-have feature.
It will reduce total BW for downloading, and total size for downloading, and total time for downloading for having latest backups of telegram account.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/10497
