### ISSUE TITLE
[Feature Request] Auto-Scroll Down to Newest Message!!!!

### ISSUE THREAD

**Issue by c133** [telegramdesktop/tdesktop#24572]
### Is your feature request related to a problem?

Yea a huge problem, I have multiple instances of telegram open across several monitors and it's very annoying having to click the down arrow to check the latest message....here is an issue from SIX YEARS AGO asking for this feature....not really sure how this is still not a feature yet.

https://github.com/telegramdesktop/tdesktop/issues/1553

### Describe the solution you'd like

A mode in settings where telegram will automatically scroll down to latest message, even when window isn't focused

### Describe alternatives you've considered

Taking my own life

**Comment by ilya-fedin** [comment]
#753
