### ISSUE TITLE
"View profile"/"View group info" missing from chat context menu

### ISSUE THREAD

**Issue by S-U-M-1** [telegramdesktop/tdesktop#24571]
### Steps to reproduce

1. Right-click on a chat

### Expected behaviour

The option "View profile"/"View group info" should be visible as the third option in the context menu, allowing the user to view the profile or group info dialogue of the chat without having to enter it and/or mark messages as read.

### Actual behaviour

Since some version shortly after 3.3.0 (8 December 2021), the option is missing, meaning users must enter the chat and click on the user/group's name or the in-chat dropdown menu to access their info page.

This means they must view the messages and/or mark them as read, which could be unsafe if the user/group is a known sender of indecent or abusive messages, for one example.

### Operating system

Windows 7

### Version of Telegram Desktop

Affected version: some version shortly after 3.3.0 (8 December 2021) (I therefore use 3.3)

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
https://github.com/telegramdesktop/tdesktop/issues/24175, please use the search next time.

**Comment by S-U-M-1** [comment]
> #24175, please use the search next time.

Used it more than once, this didn't show up.
