### ISSUE TITLE
Skipping packages with conflicts

### ISSUE THREAD

**Issue by Ronkaplan** [telegramdesktop/tdesktop#24574]
[root@localhost Ron]# dnf update
Last metadata expiration check: 0:44:18 ago on Sat 04 Jun 2022 09:32:04 AM SAST.
Dependencies resolved.

 Problem 1: package telegram-desktop-3.7.3-1.fc36.x86_64 requires qt6-qtbase(x86-64) = 6.2.3, but none of the providers can be installed
  - cannot install both qt6-qtbase-6.3.0-1.fc36.x86_64 and qt6-qtbase-6.2.3-2.fc36.x86_64
  - cannot install the best update candidate for package telegram-desktop-3.7.3-1.fc36.x86_64
  - cannot install the best update candidate for package qt6-qtbase-6.2.3-2.fc36.x86_64
 Problem 2: problem with installed package telegram-desktop-3.7.3-1.fc36.x86_64
  - package telegram-desktop-3.7.3-1.fc36.x86_64 requires qt6-qtbase(x86-64) = 6.2.3, but none of the providers can be installed
  - cannot install both qt6-qtbase-6.3.0-1.fc36.x86_64 and qt6-qtbase-6.2.3-2.fc36.x86_64
  - package qgnomeplatform-qt6-0.8.4-9.fc36.x86_64 requires libQt6Core.so.6(Qt_6.3)(64bit), but none of the providers can be installed
  - package qgnomeplatform-qt6-0.8.4-9.fc36.x86_64 requires qt6-qtbase(x86-64) = 6.3.0, but none of the providers can be installed
  - cannot install the best update candidate for package qgnomeplatform-qt6-0.8.4-8.fc36.x86_64
=================================================================================
 Package                  Architecture Version               Repository     Size
=================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 qt6-qtbase               x86_64       6.3.0-1.fc36          updates       3.8 M
Skipping packages with broken dependencies:
 qgnomeplatform-qt6       x86_64       0.8.4-9.fc36          updates       147 k

Transaction Summary
=================================================================================
Skip  2 Packages

**Comment by Aokromes** [comment]
that's not telegram issue, report on  the bug tracker of your linux distribution.
