### ISSUE TITLE
Windows unkown error while Opening Telegram Desktop App.

### ISSUE THREAD

**Issue by WINOFFRG** [telegramdesktop/tdesktop#24579]
### Steps to reproduce

1. Just by opening the App from Taskbar

### Expected behaviour

App should open without any such error.

### Actual behaviour

Whenever I open Telegram Desktop from Taskbar I get an Error message saying as shown below. 
![image](https://user-images.githubusercontent.com/61311751/172130047-b1bbbc93-52bf-431a-b25a-edf9a9982b86.png)
This comes when the TG Window appears on the screen. Even app app is not forced close from Taskbar and reopened it throws the same error.

### Operating system

Windows 11 21H2

### Version of Telegram Desktop

3.7.3 x64

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by WINOFFRG** [comment]
Actually not, The windows 11 is a genuine one (Licensed). And downloaded from Windows Setting App itself.

**Comment by ilya-fedin** [comment]
I can't reproduce this on a fresh install of Windows 11. There's definitely something you damaged your system with. Maybe you installed something that damaged your system and you didn't even know about that.
