### ISSUE TITLE
As of the day of filing this issue, the telegram version (.deb) is not updated in the Pop!_Shop of the pop os.

### ISSUE THREAD

**Issue by SmartyGrasshopper** [telegramdesktop/tdesktop#24576]
### Is your feature request related to a problem?

Yes

### Describe the solution you'd like

Update the .deb package of telegram in Pop!_Shop

### Describe alternatives you've considered

None

**Comment by ilya-fedin** [comment]
You opened an issue in a wrong place it seems as tdesktop has no official package for pop os. You can see all the official installation options at https://desktop.telegram.org.
