### ISSUE TITLE
No notifications on mobile when logged in using desktop in same place

### ISSUE THREAD

**Issue by VRJNCO** [telegramdesktop/tdesktop#24573]
### Is your feature request related to a problem?

when using desktop version, mobile notifications are double on desktop and mobile. it is a distraction. 

### Describe the solution you'd like

Bitrix 24 has a similar feature. I want you to consider. "A smart filter will make notifications less intrusive. you will not receive notifications while browsing the internet or the desktop app without noticeable pause. "

### Describe alternatives you've considered

I have to keep mobile data off while using telegram desktop. 

### Additional context

![image](https://user-images.githubusercontent.com/104243779/171987881-c2272b74-5904-43a7-a1da-f441c5987e0d.png)

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
