### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by logigin** [telegramdesktop/tdesktop#24578]
### Is your feature request related to a problem?

It would be great to be able to configure custom shortcuts in the Telegram version from the App Store

### Describe the solution you'd like

Make `shortcuts-custom.json` work. 
Or add menu in the app. 
Or just make default shortcut with `Option + J` hotkey

### Describe alternatives you've considered

-

**Comment by ilya-fedin** [comment]
> Telegram version from the App Store

Are you sure you're using tdesktop? Provide application version.

**Comment by Yzabhellnelton** [comment]
Manloloko kyo

**Comment by logigin** [comment]
> > Telegram version from the App Store
> 
> Are you sure you're using tdesktop? Provide application version.

8.7.1.229827 AppStore

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
