### ISSUE TITLE
Add method to edit message's replyKeyboardMarkup.

### ISSUE THREAD

**Issue by denikryt** [telegramdesktop/tdesktop#24575]
### Is your feature request related to a problem?

I want to edit `replyKeyboardMarkup` in interactive way. Every time to delete and send a new message with new `replyKeyboardMarkup` is seems silly. 

### Describe the solution you'd like

Just a new method or ability to edit `replyKeyboardMarkup` type in `editMessageReplyMarkup` method, for example. 

### Describe alternatives you've considered

The only way for today to change the `replyKeyboardMarkup` is to delete and send a new message with new `replyKeyboardMarkup`.
In the case of changing the keyboard dynamically by pressing buttons, this way is slow and annoying. 

### Additional context

Would be great, if every `KeyboardButton` had it's own ID. It would give more flexibility and interaction to them.

**Comment by 23rd** [comment]
[suggestions.telegram.org](https://suggestions.telegram.org/)
