### ISSUE TITLE
GIFs are not sent from an idle GIF search

### ISSUE THREAD

**Issue by gruianovac** [telegramdesktop/tdesktop#24586]
old bug that is very annoying.  

steps 
1 . search for gif. 
2 wait 15 30 min 
3 send one of the gifs from the search  
4 notice it doesnt get sent

you have to close the search or re do it

**Comment by john-preston** [comment]
I'm afraid this is how inline bots API work :( Can you check on mobile apps? If it's the same, this issue belongs to https://bugs.telegram.org
