### ISSUE TITLE
[Feature Request] Repost counter for posts next to views counter

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#24583]
### Is your feature request related to a problem?

It seems like all the statistics for posts in the channel goes through api and it would be possible to display the number of fonext to the number of views.

It would be very convenient - you wouldn’t have to go to your phone every time to see how many reposts have come up (I remind you that there are still [no statistics](https://github.com/telegramdesktop/tdesktop/issues/7678) in TDesktop)

### Describe the solution you'd like

Make reposts counter near views counter

### Describe alternatives you've considered

No

### Additional context

This is already implemented in some mobile clients, I don't know in what exactly, but here is some screenshots that I found:

![image](https://user-images.githubusercontent.com/39812401/172374929-b821c00b-617b-4ffc-941d-247d364f1aaf.png)

![image](https://user-images.githubusercontent.com/39812401/172374940-1f9599ec-b652-48c3-bd54-7c1a72724433.png)

It's showing even for non-admins. Some users says it's "tgx".

Here is method in api:
https://core.telegram.org/constructor/updateChannelMessageForwards

**Comment by 23rd** [comment]
I'm not really sure there is enough space for another icon+text, so it was added as a tooltip to the eye icon of post views.

**Comment by Neurotoxin001** [comment]
Omg it's already implemented!? Thanks!

**Comment by Neurotoxin001** [comment]
![image](https://user-images.githubusercontent.com/39812401/200136238-f8f2ba78-9834-4062-9a4f-a802ba2c31d3.png)

Yes it's here, but need to think how to release it more beauty without need to mouseover every time

**Comment by Neurotoxin001** [comment]
Maybe at least reduce the amount of time before displaying a pop-up window with the number of reposts and views? Now it's about 3 seconds. Maybe make it instant?

**Comment by Neurotoxin001** [comment]
This is how it done in android app (idk what exactly):
![image](https://user-images.githubusercontent.com/39812401/203520721-948ddfdc-a67d-46c9-bc3a-145ac9fbef08.png)
![image](https://user-images.githubusercontent.com/39812401/203520749-1f9b6add-b05b-465e-ab77-0e12b4ee0cfe.png)

Why it can't be done on TDesktop like this or like in screenshots frop op-post?
