### ISSUE TITLE
[Feature Request] Publish installer files hashes to verify when downloading

### ISSUE THREAD

**Issue by mahmoud-syr** [telegramdesktop/tdesktop#24580]
### Is your feature request related to a problem?

No, it's not.

### Describe the solution you'd like

It would be cool to follow the same approach as git-for-windows https://github.com/git-for-windows/git/releases, as you can see for each release there is a table of hashes for the download files, where you could verify the downloaded file hash.

### Describe alternatives you've considered

Well

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2063
