### ISSUE TITLE
[Question] How can I make a custom peer to appear in the chatlist before any message is sent?

### ISSUE THREAD

**Issue by sergiotarxz** [telegramdesktop/tdesktop#24581]
https://github.com/sergiotarxz/tdesktop
Hi, I am trying to implement secret chats in a fork, I created a new peer type named `EncryptedChatData` and I showHistory it as soon as the Encrypted chat has been confirmed in api/api_updates.cpp

But until I attempt to send the first message the peer doesn't appear listed in the chat list I would like something like happens in groups to happen when you create one, the secret chat is opened with a advice text and the chat is immediately shown in the chatlist.

Regards, Sergio.

**Comment by sergiotarxz** [comment]
I don't know if this is the correct channel to ask questions about the telegram-desktop source code, but I didn't find other channel and I am somewhat frustrated because nothing I do appears to work.

My last attempt was:

```c++
       if (encryptedChat.type() == mtpc_encryptedChat) {
            auto &encryptedChatCasted = encryptedChat.c_encryptedChat();
            const auto window = session().windows().front();
            auto id = encryptedChatCasted.vid().v;
            auto otherPeerId = encryptedChatCasted.vparticipant_id().v;
            auto otherUser = _session->data().user(UserId(otherPeerId));
            auto gotPeer = _session->data().peer(EncryptedId(id));
            if (gotPeer) {
                printf("%s\n", "Got Peer in chat creator.");
            }
            auto encrypted = gotPeer->asEncrypted();
            encrypted->setEncryptedChatTitle(otherUser->name + QString("🔏"));
            encrypted->setUserPicFromUser(otherUser->asUser());
            auto folder  = _session->data().folder(1);
            auto history = _session->data().history(gotPeer);
            history->setFolder(folder);
            session().data().histories().requestDialogEntry(history);
            session().data().refreshChatListEntry(history);
            session().data().sendHistoryChangeNotifications();
    
            Ui::showPeerHistory(
                gotPeer,
                ShowAtUnreadMsgId);
        }
```

That didn't work.

**Comment by Aokromes** [comment]
maybe you can get more feedback into https://t.me/TelegramDesktopTalk

**Comment by sergiotarxz** [comment]
Thank you.

**Comment by john-preston** [comment]
@sergiotarxz I'd add a custom client-side message to that history for it to appear in the chats list. Something like a service message "Chat started".

**Comment by sergiotarxz** [comment]
Thank you.
