### ISSUE TITLE
Add a keyboard shortcut for recording voice messages

### ISSUE THREAD

**Issue by Lesik** [telegramdesktop/tdesktop#2458]
One can already change the chat using `Ctrl+Tab`/`Ctrl+Shift+Tab` or `Ctrl+PgUp`/`Ctrl+PgDn`. This is great, thanks.

It would be great if one could also start recording a voice message, send a file or send a compressed picture using a keyboard shortcut. `Ctrl+R` could be recording; `Ctrl+F` is already used for searching, so another shortcut should be found. I'll leave the shortcuts to the developer's likings. :)

The current way of recording a voice message is quite annoying for laptop users, because on a touchpad it is very easy to accidentally slide out of the text area, aborting the voice message.

This change is easy to implement code-wise, and it has only upsides – those who don't like to use the shortcuts can simply not use them. It does not affect them in any way.

**Comment by ymmer** [comment]
you´re hitting the same spot i just posted in #476 

absolutely like the idea of having a voice message recording hotkey... are we going to hold it down then or do we toggle the recording on and off?

**Comment by timocov** [comment]
Skype has `Ctrl+R` for call and it is awful

**Comment by stek29** [comment]
Looks like #1060 duplicate
