### ISSUE TITLE
Telegram doesn't catch Papirus theme monochrome icon

### ISSUE THREAD

**Issue by igor-kobzev** [telegramdesktop/tdesktop#24584]
### Steps to reproduce

1. Install Papirus (dark or light) theme pack
2. Install tdesktop
3. Install AppIndication and KStatusNotifierIterm Gnome extention

### Expected behaviour

Telegram icon in the tray should be monochrome. As such:
https://user-images.githubusercontent.com/17829319/172622537-f853e8b4-f4bc-4a1f-8e37-98b65280ad51.png

### Actual behaviour

The icon is still full-color. As such:
https://user-images.githubusercontent.com/65567823/172621873-24f84641-147b-4c6d-a254-5309e5a9cc8c.png

### Operating system

Manjaro Gnome (latest updates)

### Version of Telegram Desktop

3.7.3

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
> No response

This is not filled

> Other (unofficial) source

Please test on official binary.

**Comment by ilya-fedin** [comment]
> 1. Install Papyrus

Is this a typo? I was talking about Papirus, are you sure Papyrus has monochrome icon for tdesktop?

**Comment by igor-kobzev** [comment]
Yeah, my typo. I meant Papirus.

**Comment by igor-kobzev** [comment]
Tried with the Flatpak version. This worked.
But can you still help me with the Manjaro package version? Or should I open a bug report on Manjaro website?

**Comment by igor-kobzev** [comment]
Not sure where to find the logs for that.

> > No response
> 
> This is not filled

**Comment by igor-kobzev** [comment]
[log.txt](https://github.com/telegramdesktop/tdesktop/files/8863228/log.txt)
is this it? (from ~/.local/TelegramDesktop)

**Comment by ilya-fedin** [comment]
Maybe Manjaro uses qt5ct/qt6ct and you haven't changed its settings?

**Comment by igor-kobzev** [comment]
How do I change qt5ct/qt6/ct settings?

**Comment by ilya-fedin** [comment]
Well, open the configurator and change the settings?

**Comment by igor-kobzev** [comment]
I checked the configurator, and the 'Icon theme' is set to Papirus-Dark, just like everything else.

**Comment by ilya-fedin** [comment]
`echo $QT_QPA_PLATFORMTHEME`

**Comment by igor-kobzev** [comment]
qt5ct

**Comment by ilya-fedin** [comment]
Well, it's weird, qt5ct shouldn't work with qt6 applications, so qt should fallback to gtk settings just like official binary, but that doesn't happen with Manjaro build for some reason...

**Comment by igor-kobzev** [comment]
Yeah, I tried reinstalling it, tried reinstalling Papirus, tried reinstalling AppIndicator, still the same.

**Comment by ilya-fedin** [comment]
There's some problem with Manjaro's Qt build apparently, it doesn't detect that you're running GNOME and doesn't think it should get theme from gtk. I suggest to just use official build.

**Comment by igor-kobzev** [comment]
Oh! I actually had qt6ct installed as well. I changed the icon theme there, and now it works! Thanks a bunch.
