### ISSUE TITLE
Custom notification sound not saved between sessions

### ISSUE THREAD

**Issue by keerah** [telegramdesktop/tdesktop#24597]
### Steps to reproduce

1. Set a custom sound for chats
2. Restart the client
3. The sound setting looks ok, but the actual sound is back the default one

### Expected behaviour

custom sound should be used

### Actual behaviour

telegram plays the default sound

### Operating system

windows 10

### Version of Telegram Desktop

3.7.3 x64

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
try updating to 3.7.5 beta. if works, close this issue.

**Comment by keerah** [comment]
yes, the beta solves it
