### ISSUE TITLE
When I click Reply, nothing can be entered

### ISSUE THREAD

**Issue by martrix78** [telegramdesktop/tdesktop#24591]
### Steps to reproduce

1. go to chat
2. select "reply" from the menu
3. enter something...

### Expected behaviour

Characters will appear in the input field

### Actual behaviour

nothing happens, if you collapse and expand the application, then a search box opens in which my response text is entered.
Apparently, when answering, the focus moves to a hidden search input

### Operating system

Linux Mint 20.3 Una xfce4

### Version of Telegram Desktop

3.7.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Hi, I can't reproduce with the steps you provided, the text enters just fine. It seems you missed something.

**Comment by martrix78** [comment]
Probably yes. The bug is unstable. I will try to remember the sequence of actions in detail with the next such bug

**Comment by ilya-fedin** [comment]
If you're using accentuated letters, it's might be #1041

**Comment by martrix78** [comment]
нет, я пишу по русски и обычно не использую декорации символов :)
