### ISSUE TITLE
[Feature Request] Don't let others delete your chats

### ISSUE THREAD

**Issue by LoganDark** [telegramdesktop/tdesktop#24599]
### Is your feature request related to a problem?

One of my friends just completely wiped all my message history, it's extremely stressful and I'm almost crying. Telegram should not have this feature. I should be able to turn this off. This is disgusting

### Describe the solution you'd like

Let me turn off the ability for other people to delete my messages and chats. Keep the logs on my computer regardless

### Describe alternatives you've considered

I shouldn't have to export every 2 hours just in case someone decides to delete all my messages. Backups are inconvenient, manual and slow

**Comment by 23rd** [comment]
> it's extremely stressful and I'm almost crying

Personally, I'm sorry for your painful loss.
But this should be done by server-side. There is an existed already suggestion.
https://bugs.telegram.org/c/1086

**Comment by LoganDark** [comment]
> But this should be done by server-side.

This is effectively a backdoor in the client, I should have the option to have my client reject the server's requests to  delete my messages and logs.

**Comment by 23rd** [comment]
>  I should have the option to have my client reject the server's requests to delete my messages and logs.

Let us imagine that such a possibility would exist. Then it would make sense until the next time the application is opened, since the Telegram Desktop does not store the history locally. The next time you open the Telegram Desktop, the server just won't give back the deleted history and you won't get it.

**Comment by LoganDark** [comment]
> > I should have the option to have my client reject the server's requests to delete my messages and logs.
> 
> Let us imagine that such a possibility would exist. Then it would make sense until the next time the application is opened, since the Telegram Desktop does not store the history locally. The next time you open the Telegram Desktop, the server just won't give back the deleted history and you won't get it.

That's fine, you could display a banner and let me export the data before it's gone. :(

**Comment by 23rd** [comment]
> That's fine, you could display a banner and let me export the data before it's gone.

At the time a banner is displayed, the history will no longer exist. For the history export the Telegram Desktop requests entire history from the server and does not generate it from a local cache.

**Comment by LoganDark** [comment]
> > That's fine, you could display a banner and let me export the data before it's gone.
> 
> At the time a banner is displayed, the history will no longer exist. For the history export the Telegram Desktop requests entire history from the server and does not generate it from a local cache.

Oh... that is sad. :(

maybe I could open a new feature request for periodic data exports?

**Comment by ilya-fedin** [comment]
#10338, it was rotated by stalebot due to the lack of interest

**Comment by LoganDark** [comment]
> #10338, it was rotated by stalebot due to the lack of interest

well stalebot is stupid and I can't comment on that issue now

**Comment by ilya-fedin** [comment]
Well, it really helps with the amount of the issues on the repo since reporters of most issues disappear with time and there's just no sense for them to be open (moreover, as it's impossible to read all the issues, people create duplicate and issues go >1000 really quickly). There's no problem, if you see stale bot closed an issue, you can create a new one.

**Comment by LoganDark** [comment]
> if you see stale bot closed an issue, you can create a new one.

So the issue is that people create duplicates, solution is to create new duplicates??

**Comment by ilya-fedin** [comment]
As soon as old issue is closed, new issue is not a duplicate.
