### ISSUE TITLE
Right click menu shown on different screen

### ISSUE THREAD

**Issue by aargnaxx** [telegramdesktop/tdesktop#24590]
### Steps to reproduce

1. Open Telegram desktop and put it on a secondary screen
2. Right click a chat or in-chat element
3. Menu is shown on the main screen

### Expected behaviour

The menu is shown on the same screen as parent window

### Actual behaviour

The menu is shown on the primary screen

### Operating system

Windows 11 x64

### Version of Telegram Desktop

3.7.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
amd gfx?

**Comment by ilya-fedin** [comment]
Can you provide a screenshot? Thanks

**Comment by aargnaxx** [comment]
Sure
![image](https://user-images.githubusercontent.com/16093484/172870948-f5b24c72-3776-4731-84b4-ebe41b483e93.png)
![image](https://user-images.githubusercontent.com/16093484/172870981-17e48dd4-b814-4aad-a3e1-fd7df7cb3184.png)
![image](https://user-images.githubusercontent.com/16093484/172871038-92281035-55f9-440c-a996-829906c3fd10.png)
The menu placement seems to be correct, its just displaying on the wrong screen
The main window is maximised on another screen
