### ISSUE TITLE
Scroll doesn't work

### ISSUE THREAD

**Issue by Jabca** [telegramdesktop/tdesktop#24593]
### Steps to reproduce

Doesn't work from start

### Expected behaviour

Be able to scroll scroll-able widgets

### Actual behaviour

Mouse scroll doesn't work on any widgets.

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

3.7.3

### Installation source

Snap

**Comment by ilya-fedin** [comment]
#17254
