### ISSUE TITLE
[Feature Request] separate "call button" from "minimize button"

### ISSUE THREAD

**Issue by ngmip** [telegramdesktop/tdesktop#24607]
### Is your feature request related to a problem?

I often unintentionally start a call with the person I'm chatting with just because I click a few pixel bellow the "minimize" button.

I then immediately end the call and apologize for "miss click"

### Describe the solution you'd like

I suggest a "margin" are around the "call" icon where click does nothing

### Describe alternatives you've considered

rezizing the window do not help as the buttons are anchored the same way

### Additional context

It's the Windows App version, I bet other OS where the minimize button is on the left of the panel do not have the issue obviously.

**Comment by alloky** [comment]
Very needed feature, please it it somewhere, or just swap with "search" button as hotfix. I'm really tired of miss click calls on desktop telegram.

**Comment by oleksiy-galas-sp** [comment]
![Code_d9nr0RZkpR](https://user-images.githubusercontent.com/67313652/200116814-539ab068-1dff-4b99-a4e0-d407c1a79c9b.gif)
 
Or at least decrease padding to make buttons area smaller to have space between window controls and call panel

**Comment by PsychicSmurf** [comment]
This really needs addressing. I've lost count of the amount of times I've accidentally called someone trying to minimise the app.

**Comment by binokaryg** [comment]
Please address this soon. I'm tired of saying "sorry, misclick".

**Comment by sluzynsk** [comment]
Same issue on the Linux version, I drive my wife crazy accidentally calling her when I just want to minimize the app.
