### ISSUE TITLE
[Question] CONTACT TELEGRAM SUPPORT TEAM 

### ISSUE THREAD

**Issue by DMT-512** [telegramdesktop/tdesktop#24601]
HII 
**MY FIRST POST ON GITHUB**
My sister's telegram account was banned . In her best knowledge she had not done anything wrong .
she send mails to telegram , wrote on support page of teegram and also messeged on twitterr 
but got no reply form anywere.[its 10 days now}

What to do now plz help ??

**Comment by Aokromes** [comment]
this is a bug tracker, nothing posted here can help you to get account unbanned.

**Comment by DMT-512** [comment]
WHAT SHOULD I DO NOW?
