### ISSUE TITLE
Failed to build qt5 with error "Unknown command line option '-prefix'"

### ISSUE THREAD

**Issue by shensr** [telegramdesktop/tdesktop#24619]
I'm trying build tdesktop on windows10 64bit. Everything goes well except qt5, it raises the following error:

> Info: creating super cache file D:\Telegram\Libraries\win64\qt_5_15_4\.qmake.super
> Info: creating cache file D:\Telegram\Libraries\win64\qt_5_15_4\.qmake.cache
> ERROR: Unknown command line option '-prefix'.
> [15\16](Libraries\qt_5_15_4): FAILED
> 

I checked the prepare.py, the above error should be caused by the flowing command:

>     configure -prefix "%LIBS_DIR%\\Qt-5.15.4" ^
>         %CONFIGURATIONS% ^
>         -force-debug-info ^

This command build qmake.exe then execute it with the above args, while qmake.exe does not accept -prefix option. Why this happened?

Would anyone give me some tips, thx in advance.

**Comment by john-preston** [comment]
"D:\Telegram\Libraries\win64\qt_5_15_4.qmake.super" strange path, it looks like qt_5_15_4 repository wasn't cloned properly.

**Comment by shensr** [comment]
> "D:\Telegram\Libraries\win64\qt_5_15_4.qmake.super" strange path, it looks like qt_5_15_4 repository wasn't cloned properly.

Thx for the answer.

You are right. Since the network problem, I cloned and executed the flowing commands on another machine, then copy the whole folder to my local:
>     perl init-repository --module-subset=qtbase,qtimageformats,qtsvg
>     git checkout v5.15.4-lts-lgpl
>     git submodule update qtbase qtimageformats qtsvg

And marked the above commands during building.

I had done the same things on all the third modules and works fine except qt.

Is that mean I have to do these just on my local machine? For the poor network, the clone will expend one whole day :<

Would you please give me some further advices, thanks again.

**Comment by john-preston** [comment]
@shensr Every step of the prepare script if decides to rebuild some dependency first deletes the related folder in Libraries folder. So I'm not sure it is an easy thing to do to clone the folder on one machine and run the prepare script on another.
