### ISSUE TITLE
index out of range on Debian Jessie

### ISSUE THREAD

**Issue by seraphyn** [telegramdesktop/tdesktop#2461]
Using Telegram 64bit Desktopclient on Debian Jessie.
Tried to reproduce the Error by strace the app.
### Steps to reproduce
1. start the app via bash with telegram
2. start chatting insert some icons, gifs etc.
3. After a while the window silently kills himself
### Expected behaviour

Have a nice conversation
### Actual behaviour

Telegram kills himself with 

```
./Telegram 
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element

Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element

Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element

Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element

Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

ASSERT failure in QList<T>::operator[]: "index out of range", file /usr/local/tdesktop/Qt-5.6.0/include/QtCore/qlist.h, line 539

Abgebrochen

```

IMo the fontconfigerrors could be ignored
### Configuration

Debian Jessie
Telegramversion 0.10.8

**Comment by devianpctek** [comment]
Is working fine with me, didn't try version 0.10.8 but 0.10.11 doesn't crash
