### ISSUE TITLE
Animation missing

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#24618]
### Steps to reproduce

1. Go to https://t.me/Neurotoxin_001/46 with disabled animations
2. Freezed background is showing for few seconds without animations
3. Now enable animations and go to https://t.me/Neurotoxin_001/46 again
4. There is animations
5. Now downgrade to 3.5.2 and go to link again, with disabled animations
6. There is animations even with disabled animations

Here is videos:

Telegram 3.7.6 beta with disabled animations:

https://user-images.githubusercontent.com/39812401/174169851-1cae8600-c5d4-45f1-9fe6-647d59ea5f5e.mp4

Telegram 3.7.6 beta with enabled animations:

https://user-images.githubusercontent.com/39812401/174169857-9c3bd44d-37c6-4035-a777-7c323be4e64b.mp4

Telegram 3.5.2 with disabled animations:

https://user-images.githubusercontent.com/39812401/174169858-7873b5ab-c7cc-42aa-9418-7134c2fd0ebc.mp4

### Expected behaviour

Is this bug or did you just fix a bug? I mean if you disable animations - there is no animations even when you go to post from link. On older versions of Telegram there is animations even with disabled animations.

### Actual behaviour

-

### Operating system

Windows 10

### Version of Telegram Desktop

3.7.6

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Please read #8311.
