### ISSUE TITLE
[Feature Request] Show chat icon in taskbar for separate windows

### ISSUE THREAD

**Issue by TryV** [telegramdesktop/tdesktop#24621]
### Is your feature request related to a problem?

I recently reviewed this new feature that opens a chat in a new window, which is great, but I think switching between them is a bit difficult.

### Describe the solution you'd like

I suggest expanding the Telegram windows in the taskbar and showing the chat avatars as Icon for each of them.

### Describe alternatives you've considered

It is much easier to find them when each window has icons.

### Additional context

Note: I am a Windows user and I checked this feature in Windows.

**Comment by yurii-sio2** [comment]
I would also request to add different titles to every window. Show a contact name or a channel name and count of new messages IN THAT EXACTLY chat or channel.

![image](https://user-images.githubusercontent.com/6487195/176659180-db1f45fe-d654-4564-8fcd-53a067130a57.png)

**Comment by john-preston** [comment]
Channel name is there already. I'm not sure about avatars though.

**Comment by yurii-sio2** [comment]
I have the latest version of Telegram for now:
![image](https://user-images.githubusercontent.com/6487195/215988957-21dd4fd9-cf81-4022-a3b0-d0a1f9f71980.png)

And the is no group chat name and unread messages count is wrong:
![image](https://user-images.githubusercontent.com/6487195/215990412-5c3e7120-5f08-4a91-86e7-a67af768779d.png)

**Comment by john-preston** [comment]
@yurii-sio2 It is available in the latest beta version.

**Comment by yurii-sio2** [comment]
Ok, thank you.
I'll wait for a stable release and then check this enhancement.
