### ISSUE TITLE
[Bug/Regresion] Use System Window Frame, Kubuntu 21.10

### ISSUE THREAD

**Issue by juanpc2018** [telegramdesktop/tdesktop#24629]
### Steps to reproduce

$ sudo snap install telegram-desktop
telegram-desktop 3.7.3 from Telegram FZ-LLC (telegram.desktop) installed

Click Open Telegram Desktop. 3.7.3
Dark Mode
[X] Use System Window Frame.
[X] HW Decoder Acceleration
[X] OpenGL

Nvidia Propietary Driver 470 tested.
PNY GT 740
Thunderbolt 2
Razer Core X Chroma eGPU
Apple TB2 TB3 Bi-directional adapter.

$ uname -a
Linux 5.13.0-51-generic #58-Ubuntu SMP Tue Jun 14 03:23:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

3.7.6-Beta also Does Not work.

Problem is:
[_] Enable OpenGL Rendering for Media.
Disabled [X] System Window Frame Works Ok,

### Expected behaviour

Show Kubuntu System Window Frame

### Actual behaviour

Nothing.
No System Windows Frame.
Empty.

### Operating system

Kubuntu 21.10

### Version of Telegram Desktop

3.7.3 - 3.7.6-Beta

### Installation source

Snap

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
Please provide screenshots of the issue

**Comment by paai** [comment]
Same here: telegram does not show a contrasting frame when the window is open (Bionic Beaver). When I tried newer versions of Telegram, I had the same problem, but also right-clicking for editing lines and such did not work any more.
Now I use Telegram 3.5.0, which works fine, but still does not have a visible window frame.

**Comment by ilya-fedin** [comment]
I don't understand why you made a screenshot with the option disabled, it works just as intended

**Comment by paai** [comment]
OK, ilya, I will wait until somebody who is really interested in the problem comes along...

**Comment by juanpc2018** [comment]
In Linux the Problem is:
[_] Enable OpenGL Rendering for Media.
Disabled.
[X] System Window Frame Works Ok,
with Nvidia GT 740, propietary driver 470 tested.

with AMD HD7950 No problem.
OpenGl works Ok,

Old / Low End Video cards have issues with OpenGL EGL GLX, Xrender in Linux..
example:
intel iHD 4th gen has problems, requires a VAAPI to OpenGL driver VDPAU to make FireFox have HW acceleration.


Easy to test in Linuix Desktop KDE effects like Wobbly Window 
if HW acceleration Work or does Not work.
Kubuntu KDE allows to select OpenGL3.1, OpenGL2, or Xrender,

same as VLC player, and VP9 codecs...
solution:
buy GT1030
or
AMD 5300XT 5500XT,

the minimum with VP9 HW Decoder, required for most .mkv

CPU HW decoder works, but... eats 40% CPU when Playback video with No HW acceleration.

**Comment by ilya-fedin** [comment]
I don't quite understand what should I do on a freshly installed tdesktop to reproduce the problem. You write a lot, but I don't understand what should I do from that wall of the text. Can you describe step-by-step?

**Comment by juanpc2018** [comment]
1) buy a PNY Nvidia GT 740,
2) install Kubuntu 21.10
3) Select Nvidia Propietary Drivers 470 tested.
4) install Telegram
5) Enable:
[X] OpenGL Rendering for Media.
[X] System Window Frame,
6) Done.

if you use a different Video card, the bug wont happen,
because the problem is HW acceleration.

HW acceleration has many variables.
Video card,
Video card drivers,
VAAPI, VDPAU, Xrender, OpenGL, etc...

Drivers may have support but if HW does Not,
wont work.
Nvidia & AMD have programmed obsolescence,
they Delete driver support for old HW,

Linux has X.org Open Source drivers for Nvidia,
but does Not work well with GT 740.

**Comment by ilya-fedin** [comment]
> if you use a different Video card, the bug wont happen,

I don't think this bug will be ever fixed then as it's unreproducible

**Comment by juanpc2018** [comment]
Just wait and see.
https://en.wikipedia.org/wiki/Planned_obsolescence

**Comment by ilya-fedin** [comment]
> 5\. OpenGL Rendering for Media.

Btw, are you sure it's actually enabled? The proprietary driver is blacklisted and unless you disabled this blacklist explicitly via experimental settings (that are available only to users of the static binary while you seem to use snap), it shouldn't use OpenGL. Have you checked that Telegram log files don't contain the line that OpenGL is disabled?
