### ISSUE TITLE
Close button doesn't work in Stickers 'remove confirmation dialog'

### ISSUE THREAD

**Issue by mirvel** [telegramdesktop/tdesktop#24624]
### Steps to reproduce

Repro:
1. Open Stickers
2. Click "X" button to remove set
3. Click "Cancel"in confirmation dialog

Expected:
@3 Close confirmation dialog

Actual
@3 Doesn't close. 

![image](https://user-images.githubusercontent.com/3902177/174292716-cea9174b-a191-43ea-8809-957d7d157b07.png)

### Expected behaviour

@3 Close confirmation dialog

### Actual behaviour

@3 Doesn't close. 

### Operating system

Windows 10 Pro 21H2 19044.1766

### Version of Telegram Desktop

3.7.3 x64

### Installation source

Static binary from official website

**Comment by magicxor** [comment]
"Remove" button closes the dialog, but not removes the sticker pack.
