### ISSUE TITLE
The cursor icon is pointer, even though Web App's MainButton is disabled

### ISSUE THREAD

**Issue by boohba** [telegramdesktop/tdesktop#24628]
### Steps to reproduce

1. Open Web App
2. show() & disable() the MainButton
3. Move your cursor onto the MainButton

### Expected behaviour

The cursor icon should be default

### Actual behaviour

The cursor icon is pointer

### Operating system

macOS Monterey

### Version of Telegram Desktop

3.7.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
The behavior is provided by your system web engine

**Comment by tehcneko** [comment]
> The behavior is provided by your system web engine

The MainButton is a native control

**Comment by ilya-fedin** [comment]
What MainButton are you talking about?

**Comment by tehcneko** [comment]
> What MainButton are you talking about?

https://core.telegram.org/bots/webapps#mainbutton
