### ISSUE TITLE
Can I run export channel chats job every day?

### ISSUE THREAD

**Issue by zydjohnHotmail** [telegramdesktop/tdesktop#24627]
Hello:
I am using Telegram Desktop Version 3.7.3 (x64).
I have joined a few telegram channels.  Some channels have a lot of chats almost every minute.  I want to export the chats for the underlying channel every day.
I am using Windows 10 (x64), I can do this by hand, but I don’t want to export the chats every day by hand, it is rather boring to repeat the same job by human.
Can we have some Windows command line to set the export chats as a job, and run it every day using Windows built-in scheduler?
Please advise,
Thanks,

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/24600
