### ISSUE TITLE
Allow enabling Experimental Settings without Automatic Updates

### ISSUE THREAD

**Issue by hmnd** [telegramdesktop/tdesktop#24623]
### Is your feature request related to a problem?

Currently, enabling Experimental Settings requires that Automatic Updates are enabled. It is impossible to enable Automatic Updates on versions of tdesktop distributed through package managers (eg. flatpak, snap, etc.), making it impossible to enable Experimental Settings.

### Describe the solution you'd like

Allow enabling Experimental Settings via an alternate, more universal method. One of the most common methods for accessing hidden "developer" settings in other apps seems to be *click the version number X number of times*.

### Describe alternatives you've considered

Could use environment variables or command line args, though that would not be as accessible to the average user.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25659
