### ISSUE TITLE
Stuck on connecting

### ISSUE THREAD

**Issue by DrSevenX** [telegramdesktop/tdesktop#24630]
### Steps to reproduce

1. Open Telegram
2. Attempt to login
3. Stuck on connecting 

### Expected behaviour

Login successfully

### Actual behaviour

Telegram is stuck on connecting loop. 
Have reset all network drivers.
OS is on latest update.
Tried latest version of telegram, both stable and beta.
Still unable to login.

Tried connecting via IPV6, with and without proxy. 

https://puu.sh/J6ssx/68ac7e0d2a.png

https://puu.sh/J6ssy/11d737c408.png

### Operating system

Windows 10 Pro 21H2  OS Build 19044.1766

### Version of Telegram Desktop

3.7.3, 3.7.6

### Installation source

Static binary from official website

**Comment by alexthrust** [comment]
The same behavior with those tg versions on windows 10

**Comment by Aokromes** [comment]
works for me
New login. Dear Aokromes, we detected a login into your account from a new device on 19/06/2022 at 21:49:37 UTC.

Device: Telegram Desktop, 3.7.6 x64, OptiPlex 755, Windows 10

**Comment by Demetri0** [comment]
I'm also have troubles with telegram stuck on connecting, but it's a bit different than described in the issue.

In my experience telegram sometimes stuck on connection when my laptop wake up after suspend, and I found a solution in tick-untick ipv6 checkbox in telegram settings.

Not very annoying, but not very cool, this bug I facing for a several years.

**Comment by Kangaroux** [comment]
> In my experience telegram sometimes stuck on connection when my laptop wake up after suspend, and I found a solution in tick-untick ipv6 checkbox in telegram settings.

I experience the same issue across three devices, all running popOS

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16093
