### ISSUE TITLE
[Question] [URGENT]Telegram not responding to any type of support requests

### ISSUE THREAD

**Issue by Rakavanlohee** [telegramdesktop/tdesktop#24634]
So, I have been trying to reach out telegram support through different modes, I have tried mailing 20 times, tried volunteer support within the app, tried to reach out via Twitter but never received a single response from Telegram.

I use telegram since two year but two weeks ago I can't able to create channel, group and I can't message for new people's it's mean my friends if I check in @spambot it's show me your account is limited and I asked for that's bot to why this mistake after few hours they will me replying " Good news, no limits are currently applied to your account. You’re free as a bird! " after I few minutes I trying to create group it's show me you not able to create group again I go @spambot and check my status it's show me again your account has been limited after I contact bot , volunteers and support still they're not replying me . So please any admin in there please check my full telegram : @kingmaker_23 analysis after tell me I can't send any spam my account was clear no unwanted message sent so please consider my request please give me the best solution because this telegram account use for education purpose other than normal check my account and please reply me

**Comment by Aokromes** [comment]
this is a bug tracker for a client no one here can help you.

**Comment by Rakavanlohee** [comment]
What is the bug tracker please explain me

**Comment by Aokromes** [comment]
bug tracker is to report failures on software, not lack of answer on user support.

**Comment by Rakavanlohee** [comment]
If any chance to get my account back
