### ISSUE TITLE
build error: no matching function for call to rtc::Thread::PostTask

### ISSUE THREAD

**Issue by milahu** [telegramdesktop/tdesktop#24637]
### Steps to reproduce

build tdesktop 3.7.6 (45caa25e5518c8b0bece8cdfc9be22aed17858d3) with qt 6.3.1  in nixpkgs

nixpkgs branch: https://github.com/milahu/nixpkgs/tree/qt6-631
tdesktop: [pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix](https://github.com/milahu/nixpkgs/blob/qt6-631/pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix)

### Expected behaviour

build

### Actual behaviour

```
/build/source/Telegram/ThirdParty/tgcalls/tgcalls/ThreadLocalObject.h:22:34: error: no matching function for call to 'rtc::Thread::PostTask(tgcalls::ThreadLocalObject<tgcalls::Manager>::ThreadLocalObject<tgcalls::InstanceImpl::InstanceImpl(tgcalls::Descriptor&&)::<lambda()> >(rtc::Thread*, tgcalls::InstanceImpl::InstanceImpl(tgcalls::Descriptor&&)::<lambda()>&&)::<lambda()>)'
   22 |                 _thread->PostTask([valueHolder = _valueHolder.get(), generator = std::forward<Generator>(generator)]() mutable {
      |                 ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   23 |                         valueHolder->_value.reset(generator());
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   24 |                 });
      |                 ~~                
```

### Operating system

linux

### Version of Telegram Desktop

3.7.6

### Installation source

Other (unofficial) source

### Logs

[tdesktop-45caa25e5518c8b0bece8cdfc9be22aed17858d3-qt631-error.log.gz](https://github.com/telegramdesktop/tdesktop/files/8934079/tdesktop-45caa25e5518c8b0bece8cdfc9be22aed17858d3-qt631-error.log.gz)

**Comment by ilya-fedin** [comment]
Apparently you have wrong tg_owt version

**Comment by milahu** [comment]
yes! thanks : )

**Comment by milahu** [comment]
does it make sense to add tg_owt as a git submodule to tdesktop?

**Comment by ilya-fedin** [comment]
This won't happen, sorry :(
