### ISSUE TITLE
Debian 11: Telegram start up very slow, ~50 seconds wait while no CPU/disk activity

### ISSUE THREAD

**Issue by dusthillresident** [telegramdesktop/tdesktop#24632]
Environment: 
* Using Debian GNU/Linux 11,
* Using the Linux desktop version of telegram (from 'tsetup.3.7.3.tar.xz')
* On an IBM Thinkpad T400 (Core2Duo, Intel Corporation Mobile 4 Series Chipset Integrated Graphics, SSD)

Telegram takes average of 50 seconds to start. During this time, there is no CPU usage, and no disk usage, it just seems to be sleeping/hanging.

I even tried using "strace" on it -- during the time it's waiting/hanging/sleeping/whatever, nothing is printed to the terminal.

Steps to reproduce
* Start telegram
* Notice a brief spike of CPU activity on the CPU usage graph lasting about one second, then it goes flat. Notice that the HDD light on the laptop doesn't flash. Notice that nothing appears to be happening at all basically.
* Wait ~50 seconds.
* The Telegram window finally appears and telegram works normally from then on.

This appears in the terminal immediately after launching the telegram command and immediately before Telegram starts sleeping/delaying:
`[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)`
`error: : cannot open`
`error: : cannot open`
`error: : cannot open`

**Comment by ilya-fedin** [comment]
Please close the issue and open a new one using the bug report template. Thanks.
