### ISSUE TITLE
Do not send GIF on right click in "Saved GIFs"

### ISSUE THREAD

**Issue by johnnysay** [telegramdesktop/tdesktop#2463]
### Steps to reproduce
1. Go to "Saved GIFs"
2. Right click on a GIF.

### Expected behaviour
Maybe add a menu to delete the GIF.

### Actual behaviour
The GIF is sent.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
0.10.8

**Comment by stek29** [comment]
Can't Reproduce on OS X.
But on Windows GIFs, Emojis and Stickers are sent on Right Click.
So looks like it's a *Windows* specific *bug*.

**Comment by john-preston** [comment]
Should be fixed in 0.10.13.alpha.
