### ISSUE TITLE
TG Desktop crashing on opening since yesterday 

### ISSUE THREAD

**Issue by missemily2022** [telegramdesktop/tdesktop#24631]
### Steps to reproduce

Start the Application

### Expected behaviour

Should have started

### Actual behaviour

![image](https://user-images.githubusercontent.com/97376138/174431196-b5317d5f-686b-4bc9-a8bf-1a6a5b355b84.png)

### Operating system

Windows 10 Pro 21H2

### Version of Telegram Desktop

3.7.6 Beta

### Installation source

Static binary from official website

### Logs

```shell
ApiId: 3722065
Assertion: "_localKey == nullptr" storage_domain.cpp:92
Binary: Telegram.exe
Launched: 18.06.2022 11:54:56
Platform: Windows64Bit
UserTag: ac0197ce74ea46
Version: 1000036 beta
Memory-usage: 98 MB (peak), 98 MB (current)
Pagefile-usage: 103 MB (peak), 102 MB (current)

Caught signal 11 (SIGSEGV) in thread 10404

Backtrace omitted.

Google Breakpad caught a crash, minidump written in thread 7096
Minidump: 7adaecc1-3951-4c1d-bda7-d4a33a8d9f28

Backtrace omitted.
```

**Comment by john-preston** [comment]
@missemily2022 How did Version: 1000036? 😳

**Comment by missemily2022** [comment]
@john-preston God knows

**Comment by missemily2022** [comment]
@Younes-L What do you mean?

**Comment by ilya-fedin** [comment]
> is a fork , safe to close :3

Oh, it's tdesktop-x64 apparently, its latest version is 1.0.36

**Comment by john-preston** [comment]
@missemily2022 can you reproduce the crash on the official binary from https://desktop.telegram.org/changelog#beta-version and send the crash report and post the report tag here?

**Comment by c0re100** [comment]
> @missemily2022 can you reproduce the crash on the official binary from https://desktop.telegram.org/changelog#beta-version and send the crash report and post the report tag here?

It's safe to close now :')

Cause I found the reason.
64Gram has raised account limit to 100, but start at v3.7.6, tdesktop will be counting accounts total when startup (Telegram Premium feature).
So it will be failed to open telegram desktop if someone login with more than 6 accounts.
https://github.com/telegramdesktop/tdesktop/blob/3e5b52bc2e498f45b13729b29197e07be1da9623/Telegram/SourceFiles/storage/storage_domain.cpp#L163

You can leave it to fork maintainer and let them deal with it LOL

**Comment by john-preston** [comment]
@c0re100 That's funny that it'll crash in that case. Should be fixed anyway.

**Comment by 0363687994** [comment]
0939368520
***@***.***

Vào 11:09, CN, 19 thg 6, 2022 John Preston ***@***.***> đã
viết:

**Comment by 0363687994** [comment]
0939368520

Vào 5:43, CN, 19 thg 6, 2022 ɥnsʞʎ ***@***.***> đã viết:
