### ISSUE TITLE
[Feature Request] p2p file transfer when both users are online

### ISSUE THREAD

**Issue by fcore117** [telegramdesktop/tdesktop#24649]
### Is your feature request related to a problem?

I really understand strain on Telegram servers about files.

### Describe the solution you'd like

Possible to establish direct connection between users (only personal contacts) when both are online then file transfer could use maximum bandwidth thus ignoring telegram servers at all. It is idea to think about and pass to Telegram developers. p2p type of features can really reduce Telegram server load and in future Telegram should consider more ways to use p2p serverless **backup** connection systems overall. Calls already works similarly as most of them are p2p and zero effect on Telegram server then.

### Describe alternatives you've considered

*Same applies as in solution*

### Additional context

It is solution to conserve Telegram servers, are more private, highly effective speeds when working in LAN environment.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
