### ISSUE TITLE
[Feature Request] Emoji Unicode 14

### ISSUE THREAD

**Issue by olaims** [telegramdesktop/tdesktop#24643]
### Is your feature request related to a problem?

Some of the new Emojis Unicode 14 are being displayed as squares.

### Describe the solution you'd like

Make Telegram Desktop compatible with the new Emojis of Unicode 14

### Describe alternatives you've considered

nothing

**Comment by andrrms** [comment]
up

**Comment by earendil02** [comment]
I don't know how difficult it is to add support to newer versions of unicode, but given the importance of emojis and characters in general for a messaging app I would say that this should be quite a priority...

**Comment by john-preston** [comment]
The JoyPixels set (which is one of four sets available in TDesktop) doesn't support those yet. So, waiting.

**Comment by myyc** [comment]
wouldn't it be possible to at least support falling back to the system theme?

**Comment by Twilightssuperb** [comment]
> The JoyPixels set (which is one of four sets available in TDesktop) doesn't support those yet. So, waiting.

Today they've just updated emojis and fonts. Finally! 

https://blog.joypixels.com/joypixels-7-0-now-available/

**Comment by Aokromes** [comment]
already on 4.0.4
