### ISSUE TITLE
Huge memory consumption

### ISSUE THREAD

**Issue by Alukardd** [telegramdesktop/tdesktop#2464]
### Description of problem

At this moment tdesktop runs 7days on my laptop.
I use suspending (not hibernating).
And now I have this:
alukardd  2000  1.6 20.6 3985188 1620220 ?     Sl   Sep19 159:57 Telegram

1.5Gb RSS !!!

I can provide u some additional info until I closed app.
### Configuration

Debian stretch/sid

Tdesktop v0.9.56

**Comment by hdhog** [comment]
getnoo Telegramm v 0.10 03.08.16 memory leak over 5Gb on week

**Comment by Alukardd** [comment]
AFAIK, it's because I have several channels with hundreds of thousands messages. And tdesktop has not any garbage collector and never return memory to OS.

**Comment by Aokromes** [comment]
On the past i used valgrind vs telegram, the result was.. pain.
On windows, atm i have 21d of uptime without close windows and no leak at all.

**Comment by hemee** [comment]
I think it depends on amount of data (texts and media) and amount of contacts. Mine rarely goes over 300 MB on x64 Debian Stretch.

**Comment by zaps166** [comment]
Telegram 0.10.11 on Linux (custom build), load history from a few weeks/moths containing links, files, GIFs, stickers, sounds, etc and scroll up and down using mouse for a few minutes.
Example result (~46 min of run time, but only a few minutes of scrolling): 
![spectacle h25737](https://cloud.githubusercontent.com/assets/6239090/19057496/86830d2e-89d0-11e6-9519-abde3e55096e.png)

**Comment by dagmoller** [comment]
2.6Gb of RAM after 4 days...
Running on Linux...

**Comment by strangeman** [comment]
Debian Jessie, Telegram Desktop consuming about 2.5 Gb of RAM after 5 days.

**Comment by lorien** [comment]
Debian Stretch. Telegram Desktop eats few Gb in few days. So now every 2-3 days my system freezes for few minutes and OOM Killer kills some processes. Nightmare.

**Comment by POPSuL** [comment]
I've same issue =(

**Comment by dzmitry-kankalovich** [comment]
Same happens for me on MacOS actually.

**Comment by igormp** [comment]
Can confirm this.
After about a day of usage, it's using over 1gb of RAM.

![myimage](https://user-images.githubusercontent.com/5247904/38233713-dd724fa8-36f1-11e8-99fe-5ae3d801baa6.png)

**Comment by Su33ke** [comment]
FreeBSD 11-0. ~15mb leak after 1 day

**Comment by koderrr** [comment]
Hogs RAM and gets killed:
```
[320827.895088] Out of memory: Kill process 889 (telegram-deskto) score 918 or sacrifice child
[320827.897542] Killed process 889 (telegram-deskto) total-vm:17257476kB, anon-rss:7434276kB, file-rss:0kB, shmem-rss:0kB
[320828.866089] oom_reaper: reaped process 889 (telegram-deskto), now anon-rss:16kB, file-rss:0kB, shmem-rss:0kB
```
Telegram Desktop running for 3 days:
![ss-2018-09-07-15-38-16](https://user-images.githubusercontent.com/7849982/45217341-c85a0400-b2b4-11e8-8abc-0cd581bdc295.png)

aur/telegram-desktop-dev 1.3.15-1 on Arch.

**Comment by koderrr** [comment]
Must say this is pretty rare. Also it's achieved this state in less than 24h.

![photo_2018-09-26_12-15-20](https://user-images.githubusercontent.com/7849982/46067156-380e3100-c187-11e8-845a-3019c925d20f.jpg)

The laptop (8 gig of RAM, 8 gig of swap) became completely unresponsive and was swapping heavily, I had to kill the process via ssh.

**Comment by yermulnik** [comment]
Is this issue going further? Same memory consumption here for me on Linux Mint =(

**Comment by korangu** [comment]
![image](https://user-images.githubusercontent.com/36361542/53680754-ba39ed00-3d05-11e9-96d3-a0a40f3f9bea.png)

see my memory usage :|

**Comment by xp-vit** [comment]
Seen similar today on MacOs and Telegram Desktop 1.5.15: Telegram was running for about a week/1.5 and was consuming 3Gb of memory before system rebooted itself after hang.

**Comment by yermulnik** [comment]
I've switched to [Franz](https://meetfranz.com/) meanwhile though would prefer using _native_ app.

**Comment by Lonedone** [comment]
I have few contacts and my telegram uses 3GB. 
<img width="801" alt="Screenshot 2019-04-23 at 16 42 18" src="https://user-images.githubusercontent.com/22933197/56585715-0fe49480-65e7-11e9-8749-242c76d20684.png">
Meanwhile my friend's installation uses up to 10GB.
<img width="812" alt="Screenshot 2019-04-23 at 14 59 14" src="https://user-images.githubusercontent.com/22933197/56585802-3acee880-65e7-11e9-9819-5848ecb66c83.png">
Such a significant memory leaks you have.

**Comment by ssarkisy** [comment]
<img width="288" alt="Screenshot 2019-06-25 14 22 39" src="https://user-images.githubusercontent.com/8457295/60094558-190ff000-9755-11e9-9371-773ac1c31365.png">

**Comment by selivandex** [comment]
same here

**Comment by AydarAkhmetzyanov** [comment]
7gb )

**Comment by ayozemr** [comment]
any news on this? 2-3 gb on telegram desktop mac

**Comment by ulitiy** [comment]
> any news on this? 2-3 gb on telegram desktop mac

Probably the best solution is to switch to the "Telegram" client, not the "Telegram desktop". It seems it doesn't leak.

**Comment by saeedesmaili** [comment]
same here

**Comment by ayozemr** [comment]
> > any news on this? 2-3 gb on telegram desktop mac
> 
> Probably the best solution is to switch to the "Telegram" client, not the "Telegram desktop". It seems it doesn't leak.

You mean the iOS like one? The more complete client is this one :-(

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1317

**Comment by nuruder** [comment]
Guys, 10,88Gb... :(

**Comment by PlugIN73** [comment]
5 gb :( what the fuck?

**Comment by drupaladmin** [comment]
2,2 Gb MacOs 10.15.1

**Comment by MrRTi** [comment]
7,45 Gb MacOs  10.15.1

**Comment by xpoback** [comment]
Over 6Gb on Ubuntu

**Comment by lelvisl** [comment]
Any updates?

**Comment by Aokromes** [comment]
no, this ticket is closed because duplicate, if anyone knows how to read valgrind and supply fixes check the opened ticket.

**Comment by Firsto** [comment]
how to fix it?

**Comment by asomir** [comment]
I have the same problem, 1.47Gb

**Comment by Jacke** [comment]
Same problem, Fucking Durov's brother, hire normal brogrammers

**Comment by E011011101001** [comment]
Telegram For Mac, 2.94 GB now

**Comment by siemarell** [comment]
![image](https://user-images.githubusercontent.com/13420325/74535407-cf278480-4f46-11ea-9adc-dee957d3121a.png)

**Comment by Firsto** [comment]
I use beta version now, and memory consumption is about 500MB

**Comment by IRGC** [comment]
![image](https://user-images.githubusercontent.com/36361542/77385647-b8c6e100-6dae-11ea-982b-29a387d41419.png)
almost 1.4GB

**Comment by moeatsy** [comment]
4 years of development since this thread start, extra small messenger still use more memory than few windows of webstorm

**Comment by sartyukhov** [comment]
![image](https://user-images.githubusercontent.com/23495999/78036121-9ca8de00-7372-11ea-9984-0e18ac3d12b2.png)

yeah, problem still exists! (650 Mb just the beginning)
Durov, please help :D

**Comment by Merujan99** [comment]
<img width="1539" alt="image" src="https://user-images.githubusercontent.com/4623322/78937764-13a44c00-7ac2-11ea-861f-250fa2bf9bd3.png">
60GB

**Comment by danialkeimasi** [comment]
![image](https://user-images.githubusercontent.com/33510850/80316174-73645c00-8811-11ea-945a-b2e99a0fea66.png)
just after i open telegram the process started with 800MB ram minimum
telegram desktop version 1.9.3
pop_os gnome

**Comment by hanbule** [comment]
![image](https://user-images.githubusercontent.com/53240270/81235002-a0c7bb80-9002-11ea-9489-25d82b86b01f.png)

**Comment by Limman** [comment]
<img width="561" alt="изображение" src="https://user-images.githubusercontent.com/9432322/83567003-90373200-a529-11ea-98b3-a4c7fb3afbbb.png">
Telegram Desktop v2.1.5.
Huge memory leaks started after update to v2.x from v1.x. The same situation on 2 Macs (10.12 and 10.13).

**Comment by dmikushin** [comment]
MacOS 10.15 same

**Comment by avatar-lavventura** [comment]
Any solution or advice for this huge memory leak?

**Comment by pickfire** [comment]
Disable animations? I tried disabling some stuff then memory dropped from 600 MB to 150 MB.

**Comment by avatar-lavventura** [comment]
How could I disable them? @pickfire

**Comment by danialkeimasi** [comment]
ظاهرا مشکل به دلیل محدودیت تعداد ساخت دیتابیس بوده
فقط یک دیتابیس میشه ساخت با نوع سرویس خریداری شده
ممنون

**Comment by pickfire** [comment]
> How could I disable them? @pickfire

Settings > Advanced > Performance

![2020-07-31-010517_387x678_scrot](https://user-images.githubusercontent.com/4687791/88952361-e9250b80-d2c9-11ea-9d88-3783bc7fd6fe.png)

**Comment by avatar-lavventura** [comment]
@pickfire  I have Telegram 6.3 (downloaded from here: https://macos.telegram.org ), which does not have any `Advanced` option.

**Comment by Aokromes** [comment]
telegram 6.3 for macos is a different application.

**Comment by pickfire** [comment]
Oh, the telegram in linux have this option which I downloaded from archlinuxcn repo with megumifox patch have that option.

**Comment by shithappens2016** [comment]
Telegramdesktop using [Qml ](http://en.wikipedia.org/wiki/QML)for gui and [Qml ](https://doc.qt.io/qt-5/qmlapplications.html)have a lot of  bugs cause memory leak.
App build of Qml with a simple textedit and put some text int it, keep scroll up and scroll down for few times then stop and you will see the memory usage keep growing itself.
Sadly the [qt company](https://www.qt.io) seems never bother to fix them:

> 
https://stackoverflow.com/questions/61378389/qml-memory-leak-sending-xmlhttprequest
https://bugreports.qt.io/browse/QTBUG-43005
https://bugreports.qt.io/browse/QTBUG-50231
https://bugreports.qt.io/browse/QTBUG-83857

**Comment by john-preston** [comment]
@shithappens2016 But tdesktop doesn't use QML 😔

**Comment by bzeller** [comment]
I have this issue as well, this morning tdesktop was using over 20Gig!! of my memory... now after 40 mins of use its back to over 3Gig already with 35 threads...
