### ISSUE TITLE
Flickering on XWayland

### ISSUE THREAD

**Issue by the-Mitu** [telegramdesktop/tdesktop#24646]
I have an issue with different things flickering. Flickering is random, but often – visible on scrolling, video previews, opening/closing the sidebar.

Configuration:

- Fedora 36
- Telegram Desktop 3.7.3 (installed via Flatpak)
- Wayland (Telegram runs on XWayland)
- NVidia with 515 drivers
- 4K@120Hz screen

If there is any further data I can provide, please tell me what and how can I check it.

**Comment by ilya-fedin** [comment]
Maybe it's a bug of NVIDIA drivers?

**Comment by the-Mitu** [comment]
It is possible. Could this be verified somehow?

**Comment by ilya-fedin** [comment]
Apparently by checking on native X?

**Comment by ilya-fedin** [comment]
I think it's due to NVIDIA drivers
