### ISSUE TITLE
Music player title bug

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [telegramdesktop/tdesktop#24640]
### Steps to reproduce

1. Play a music with Persian title.
2. Look at the music player's top bar

![image](https://user-images.githubusercontent.com/17345129/174499194-c62ac49d-e735-43d2-8516-c337f012e89e.png)

### Expected behaviour

Show the title correctly

### Actual behaviour

The music title won't show

### Operating system

Ubuntu 20.04

### Version of Telegram Desktop

3.7.6 Beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#17426
