### ISSUE TITLE
The HTTP-Proxy client should not reuse the connection

### ISSUE THREAD

**Issue by SuzukiHonoka** [telegramdesktop/tdesktop#24645]
### Steps to reproduce

I've made a simple HTTP-PROXY program to satisfy my needs.
The other kind of chatting application like LINE is working well except the telegram.

1. Add HTTP proxy in the settings
2. Select it

### Expected behaviour

Not reconnecting to HTTP proxy infinitely

### Actual behaviour

telegram is reconnecting to HTTP proxy infinitely

### Operating system

Windows 11

### Version of Telegram Desktop

3.7.3

### Installation source

Static binary from official website

### Logs

```shell
The following logs are generated from my application.
Each connection is marked with a unique UUID.


3501b3b1-a7fd-483d-9bfd-bef59c0075dc
<----- 
POST /api HTTP/1.1
Host: 149.154.175.50:80
Content-Type: application/x-www-form-urlencoded
Content-Length: 96
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,en,*
User-Agent: Mozilla/5.0


3501b3b1-a7fd-483d-9bfd-bef59c0075dc
<-----
`�l�R�bLx�F`#�}G��=&V��
Ӣ7;n�Xe�Ӝ�E�3K��n��(���"�ereiӵ�oJ
4�����ǈ�""/�J3�nt-Length: 96
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,en,*
User-Agent: Mozilla/5.0


3501b3b1-a7fd-483d-9bfd-bef59c0075dc
<----- 
POST http://149.154.175.50:80/api HTTP/1.1
Host: 149.154.175.50:80
Content-Type: application/x-www-form-urlencoded
Content-Length: 104
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,en,*
User-Agent: Mozilla/5.0
```

As you can see, after the first request, the telegram is still using the same connection.
By the standards, it should not.
The HTTP proxy standards support CONNECT method to create a tunnel. 
It should use CONNECT instead.
```

**Comment by ilya-fedin** [comment]
tdesktop has no control over HTTP proxy client code, it lives in Qt.
