### ISSUE TITLE
No system native notifications support for Wayland

### ISSUE THREAD

**Issue by the-Mitu** [telegramdesktop/tdesktop#24648]
### Steps to reproduce

1. Install Telegram via Flatpak
2. Open the application and turn on native window decorations
3. Run flatpak run --env=QT_QPA_PLATFORM=wayland org.telegram.desktop
4. Open settings

### Expected behaviour

The switch "use native notifications" on the bottom of the panel is visible, can be activated and will work

### Actual behaviour

The mentioned switch is hidden

### Operating system

Fedora 36, GNOME 42 on Wayland

### Version of Telegram Desktop

3.7.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
It's hidden because only native notifications are supported on Wayland. There's no way to implement non-native notifications as Wayland doesn't provide positioning APIs.

**Comment by the-Mitu** [comment]
At the same time when sending an image, I can see purely native GTK file choosing dialog. Doesn't it come from the Flatpak portal?

It seems like Telegram Desktop uses org.freedesktop.Platform runtime. Woudn't [this](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Notification) allow to implement notification on Wayland as well?

**Comment by ilya-fedin** [comment]
I don't want to implement org.freedesktop.portal.Notification, I think the current implementation of org.freedesktop.Notifications is enough, it provides far more features than the portal API.
