### ISSUE TITLE
[Feature Request] Allow user to determine ArchiveAndMute for noncontact

### ISSUE THREAD

**Issue by gzqx** [telegramdesktop/tdesktop#24641]
### Is your feature request related to a problem?

Currently it is determined by server API whether an user is qualified for it (if I understand the code correctly).

### Describe the solution you'd like

Let user to decide it directly.

(To be specific, I get 4 spam this week, how on earth am I still not qualified for this?)

### Describe alternatives you've considered

I really can't think of alternative, I don't even think this design can reduce server load, so, why?

### Additional context

Telegram by most function is a masterpiece among IMs, and I do love it. However the decision on this feature really confuses me.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by 0363687994** [comment]
0939368520

Vào 7:33, Th 2, 20 thg 6, 2022 Aokromes ***@***.***> đã viết:

**Comment by john-preston** [comment]
@gzqx It is a premium feature, if I understand correctly.

**Comment by gzqx** [comment]
> @gzqx It is a premium feature, if I understand correctly.

As I understand it the option shows when a certain unknown threshold of non contact message frequency is reached.
(I don't know if the new premium update changes it)

**Comment by john-preston** [comment]
@gzqx Yes, but for premium subscription users the option will always be there.
