### ISSUE TITLE
System window decoration not supported with native Wayland

### ISSUE THREAD

**Issue by the-Mitu** [telegramdesktop/tdesktop#24647]
### Steps to reproduce

1. Install Telegram via Flatpak
2. Open the application and turn on native window decorations
3. Run `flatpak run --env=QT_QPA_PLATFORM=wayland org.telegram.desktop`

### Expected behaviour

The window has native window decoration, as I have set

### Actual behaviour

There is custom decoration, the option to switch it in settings is not displayed

### Operating system

Fedora 36, GNOME 42 on Wayland

### Version of Telegram Desktop

3.7.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
It's unsupported on GNOME side, unfortunately.

**Comment by ilya-fedin** [comment]
But you say 'with native Wayland' in the title :thinking:

**Comment by the-Mitu** [comment]
> But you say 'with native Wayland' in the title

Oops, I must have messed someting up in the previous comment :thinking: Yes, I do mean native Wayland here.

So if that's a missing thing in GNOME even for native wayland only, what the problem is and where could the issue be raised in the GNOME project?

**Comment by ilya-fedin** [comment]
It was raised multiple times I think, GNOME developers rejected it every time... You can search 'xdg-decoration' in mutter's GitLab.

**Comment by the-Mitu** [comment]
Too bad :disappointed:

[Discussion on GNOME's GitLab is here](https://gitlab.gnome.org/GNOME/mutter/-/issues/217).
