### ISSUE TITLE
AdaptiveForWide is missing in new Settings panel

### ISSUE THREAD

**Issue by julianxhokaxhiu** [telegramdesktop/tdesktop#2465]
### Steps to reproduce
1. Open Telegram
2. Go to Settings
3. Feel sad that you don't find the option

### Expected behaviour
The option should be there, clickable and working.

### Actual behaviour
No option available.

### Configuration
**Operating system:**
Windows 10 AU
**Version of Telegram Desktop:**
0.10.8

https://github.com/telegramdesktop/tdesktop/commit/2aab8bbae8670785aca39c75e06298b270767e82#diff-d1d9157a9d81dc4de401d0426a81acb9L189 this commit killed the option

Best regards,
Julian

**Comment by john-preston** [comment]
@julianxhokaxhiu It is there. Visible when the window is wide enough to switch to the adaptive layout for wide screens — just as in the old settings page.

**Comment by julianxhokaxhiu** [comment]
Uhm allright, not really clear then...

**Comment by Dreeg** [comment]
Honestly, with 1600x900, I do not see the option

**Comment by john-preston** [comment]
@Dreeg And are your messages on the left side (like in the adaptive layout for the wide screens enabled)?

**Comment by Dreeg** [comment]
Yes @john-preston. My messages are on the left side together with the other messages.

**Comment by john-preston** [comment]
@Dreeg I have the checkbox in "Chat Background" section, under the "Tile Background". What interface scale do you use?

**Comment by Dreeg** [comment]
@john-preston I have that check too. With full screen I have the problem with messages on left side.
If I use telegram with 2/3 of the width of the screen (or less) my messages are moved to the right side.

**Comment by julianxhokaxhiu** [comment]
I agree, I have the same issue.

**Comment by john-preston** [comment]
@Dreeg Then what is the problem about the new settings? Everything is working like before?

**Comment by Dreeg** [comment]
No, I can't see my messages to right side in a full screen.
I have a lot of empty space and my messages mixed with messages from others is not beautiful.

**Comment by john-preston** [comment]
@Dreeg 

When you see your messages on the left side together with the others and open Settings you should see this:

![image](https://cloud.githubusercontent.com/assets/17900494/18880325/2ce98d28-84e0-11e6-87bc-758ba4186bc4.png)

**Comment by Dreeg** [comment]
@john-preston the problem is that in telegram 0.10.8 we haven't this option. In that place I have only "Tile background" option.

**Comment by Dreeg** [comment]
@john-preston i just found that the option in question appear only when telegram is in fullscreen.
The program settings are different depending on the size of window?

**Comment by julianxhokaxhiu** [comment]
I can confirm I can also see the option just when this layout kicks in. Although, personally I do not agree to show/hide options based on the context.

Any other application in the world, shows ALWAYS the options, then when you trigger them is another story. IMHO you should consider showing this doesn't matter the resolution.

**Comment by julianxhokaxhiu** [comment]
@auchri I updated the title, please consider this issue to be re-opened, this decision doesn't make any sense.

**Comment by Dreeg** [comment]
I agree with @julianxhokaxhiu

**Comment by john-preston** [comment]
@julianxhokaxhiu This has nothing to do with the app version and it was discussed a long time ago, when this feature was first added. No need for yet another checkbox in Settings when it does nothing being changed.

I've specifically highlightened this behavior in the first reply to that issue even before it was closed and got many answers after that, so I can suggest I'm just not being read carefully.

**Comment by 0xpr03** [comment]
> @julianxhokaxhiu This has nothing to do with the app version and it was discussed a long time ago, when this feature was first added. No need for yet another checkbox in Settings when it does nothing being changed.

I'd agree, but I've searched now around 5 minutes to find out I can't disable that functionality as long as the window isn't maximized. So I maximize it, don't like how it looks, half screen it, go into the settings and can't find a way to turn it off.
Sorry @john-preston but this isn't user friendly at all. Wouldn't have found it without the help of a friend who just happened to have maximized his window.

**Comment by Dreeg** [comment]
For an application in the top 10 in the world, the minimum would be a user friendly approach.
For example if the option "not needed" in certain resolutions, it becomes non-clickable (like others). But if it disappears completely, you risk not being aware of its existence by terribly boring in useless online searches.
Otherwise known as people are left with a negative idea.

If you need to find an issue on github to discover the existence of a setting: maybe we're right.
This is just my honest opinion.

**Comment by Dreeg** [comment]
For an application amongst the top 10 in the world, the minimum would be a user friendly approach.
For example if the option "not needed" in certain resolutions becomes non-clickable (like others). But if it disappears completely, the risk of not being aware of its existence, and thus, becoming terribly annoying in useless online searches. Otherwise known as people being left with a negative idea.

If there's the need of finding an actual issue on github in order to discover the existence of a setting: maybe we're right.
This is just my honest opinion.
