### ISSUE TITLE
[Question] Download media and files at the fastest possible speed

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#24654]
I have premium and updated to 4.0, but download speed is still limited.

25-30Mbps when downloading video:
![image](https://user-images.githubusercontent.com/39812401/174764353-5cd54254-9e23-48e2-ab85-7d51a2222a99.png)

Speedtest with Amsterdam server:
![image](https://user-images.githubusercontent.com/39812401/174764386-9e89e8c5-1c1b-4d2c-8b6c-e3eb840ded95.png)

Is this fine? From iOS have fastest download:

https://user-images.githubusercontent.com/39812401/174764622-4a19bf66-37c2-4dda-a97a-42d8e40e059c.MP4

**Comment by Neurotoxin001** [comment]
Upload the same:
![image](https://user-images.githubusercontent.com/39812401/174765414-d5b561e4-10cf-431a-97dc-9899b233bf1c.png)

But there is nothing about upload speed in premium, I understand it, but this is still the problem. Even custom clients like Kotatogram have upload speed boost.

**Comment by AkciumKicum** [comment]
![image](https://user-images.githubusercontent.com/32580360/174765922-c0107cea-3cf2-4f8e-958b-e43f9a34a946.png)
![image](https://user-images.githubusercontent.com/32580360/174767024-6468050f-5b69-412b-b87f-c1380b198905.png)

**Comment by Neurotoxin001** [comment]
I tested download again and I can say it's ~80mbps on tdesktop, but only with FILES. Videos is still on ~25-35mbps.

**Comment by Aokromes** [comment]
better post here https://github.com/telegramdesktop/tdesktop/issues/24700
