### ISSUE TITLE
Telegram Premium different price from Mobile Apps

### ISSUE THREAD

**Issue by michele-grifa** [telegramdesktop/tdesktop#24659]
I updated to the version 4.0.0 and opened the Telegram Premium in Settings, but the price showed is different than the mobile apps. Is an error or the price are different?

### Android and iOS: 5,99€.
![iphone](https://user-images.githubusercontent.com/33720244/174796174-c85e8541-2d56-4c6b-bc6a-2d5aedcd3796.jpg)

### Telegram Desktop: 3,99€
![tgdesktop](https://user-images.githubusercontent.com/33720244/174796195-cdebfb2b-ebc4-4055-8b32-682ec8708d71.png)

**Comment by john-preston** [comment]
@michele-grifa because Telegram Desktop is better!

(that's a joke) In store versions on iOS and Android it is an in-app subscription with commission to Apple / Google etc, while in Telegram Desktop it is more direct than in mobile apps.

**Comment by michele-grifa** [comment]
@john-preston thanks for the explanation.

**Comment by Biruk-hub** [comment]
@john-preston ahh that's why it's different then. thanks
