### ISSUE TITLE
Missing unread count on the taskbar icon

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [telegramdesktop/tdesktop#24666]
### Steps to reproduce

The icon on the Windows Taskbar doesn't display the unread count. Only the tray icon displays them. This issue appeared after updating to 4.0.
![Telegram taskbar icon](https://user-images.githubusercontent.com/5282741/174853769-13e43723-4259-4e12-874e-f88a3858ab7b.png)

### Expected behaviour

The taskbar icon should display the unread count.

### Actual behaviour

The taskbar icon always is a regular telegram icon regardless the unread count.

### Operating system

Windows 7 SP1 (64-bit)

### Version of Telegram Desktop

4.0

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I can't reproduce that :( For me it shows the counter just fine.

Does a relaunch fix it? Does toggle/untoggle "Show taskbar icon" in Settings fix it?

**Comment by JDGon** [comment]
Same here, with Win7 too, and after update to latest version.

I've tried toggle different notification options (even enabling desktop popups) but it doesn't work.
