### ISSUE TITLE
[Feature Request] Movable undread messages bar

### ISSUE THREAD

**Issue by korvin14** [telegramdesktop/tdesktop#2466]
Hi! 
I have been using telegram for almost a year and I would like to suggest the following:
It would be nice to have **"movable" unread message** bar.

For example, if i have many messages in my channel and i have not read it all, it would be nice if this bar could be displayed over/under last viewed message and i could correct it(slide up and down if i need to).

Thank you guys for amazing work!

**Comment by stek29** [comment]
I think it would be better if app would mark messages as read only if you actually read them (remembers where you've closed the chat)
And I'm sure there was an issue for this already, but I can't find it :(

**Comment by korvin14** [comment]
@stek29 totally agree with you! It would be nice as well. Has anyone took this issue?

**Comment by auchri** [comment]
@stek29 @korvin14 #775?

**Comment by stek29** [comment]
@auchri yes, that's what I meant.
