### ISSUE TITLE
[Feature Request] Spam of notifications

### ISSUE THREAD

**Issue by 1Dradon1** [telegramdesktop/tdesktop#24669]
### Is your feature request related to a problem?

most users when they write to you in the messenger, instead of putting an end to it, they simply send a message. As a result, in a few seconds you get a bunch of notifications at once, it's annoying

### Describe the solution you'd like

create a func that creates a 5-10 second delay for notification when you receive one

### Describe alternatives you've considered

-

**Comment by ilya-fedin** [comment]
#429
