### ISSUE TITLE
System Window Frame Not Used After 4.0 On KDE

### ISSUE THREAD

**Issue by DarkArc** [telegramdesktop/tdesktop#24667]
### Steps to reproduce

1. Upgrade to 4.0
2. Make sure "Use System Window Frame" is checked in advanced settings

### Expected behaviour

KDE Window Frames are used.

e.g.

![image](https://user-images.githubusercontent.com/778012/174863273-c5d2adce-5d17-4074-98e7-1f85c9371653.png)

### Actual behaviour

An unknown window frame is used. 

![image](https://user-images.githubusercontent.com/778012/174863316-ba8c49d6-0225-4c19-9f9c-2a96c8f99c48.png)

### Operating system

Fedora 36 - KDE 5.24.5

### Version of Telegram Desktop

4.0

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This always was on Wayland, it's a Wayland protocol issue
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/9

**Comment by DarkArc** [comment]
> Well, I can say for sure this always was a thing, you haven't tried to change the option previously apparently. Just close the window, open it again and it should be ok.

I literally just said, that does not work.

**Comment by DarkArc** [comment]
> Well, you edited the message and GitHub doesn't notify when you edit a message...

Yeah I did that for clarity just to emphasize the problem. Communication is hard. Sorry.

> I suggest to use QT_QPA_PLATFORM=xcb 

That seems silly (other than as a temporary workaround), there's clearly a regression here.

> or switch to X session

Definitely, no thanks :)

**Comment by ilya-fedin** [comment]
Looks like I found it, it changes the hint only when the window is shown now
