### ISSUE TITLE
Problem with the application window frame (again)

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [telegramdesktop/tdesktop#24664]
### Steps to reproduce

Appeared immediately after update to 4.0. Also appears after exiting and running it again. Related to #16721.

### Expected behaviour

The frame should not mix with the system one.

### Actual behaviour

The frame is mixed with the system one.
![Mixed frame](https://user-images.githubusercontent.com/5282741/174851814-6172a39a-289b-4bfb-9363-44b033d53453.png)

### Operating system

Windows 7 SP1 (64-bit)

### Version of Telegram Desktop

4.0

### Installation source

Static binary from official website

**Comment by asen1987** [comment]
Windows 7 SP1 (64-bit)
4.0 x64 version

Same issue

**Comment by Marsi4eg** [comment]
Same bug again, it already happened before, and now again. 
Win7x64

**Comment by john-preston** [comment]
This should be fixed by https://github.com/telegramdesktop/tdesktop/commit/5738998310c10780568de77a8217cb1b524bebfa
