### ISSUE TITLE
[Question] How can I keep the contact column when the window is narrow?

### ISSUE THREAD

**Issue by mondalaci** [telegramdesktop/tdesktop#24679]
I love Telegram's [compact mode](https://telegram.org/blog/desktop-compact), but the contact column disappears when the window is narrower than 1280 pixels. I want to have the contact column in a narrower window because I have multiple apps side by side in a workspace.

Is this 1280 pixel breakpoint configurable? If not, please point me to the relevant value in the source code, and I'll recompile it. I was unable to find this value.

**Comment by duskwuff** [comment]
I think this is a bug. The breakpoint is 640px on macOS, which feels much more reasonable.

What OS are you running on, and are you using a high-DPI display?

**Comment by mondalaci** [comment]
I'm using Linux Mint 20.3 on a 4K display in high-DPI mode.

**Comment by Aokromes** [comment]
you can use lower dpi, if that's not enough you can run sub 100% dpi.

**Comment by mondalaci** [comment]
The current DPI results in optimal text size, so I won't change the DPI. If this is a bug, it should be fixed.

**Comment by mondalaci** [comment]
Closing this issue as a duplicate of #25068.
