### ISSUE TITLE
New Update 4.0 Breaks The Menu Bar

### ISSUE THREAD

**Issue by Rajbir98** [telegramdesktop/tdesktop#24673]
### Steps to reproduce

Update Telegram
Check The Menu Bar

### Expected behaviour

![image](https://user-images.githubusercontent.com/84771149/174966908-bd5115fd-2259-496f-afc9-364ccda1cbd2.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/84771149/174966846-ea5652e7-35ef-4dee-9348-693e6f61f56d.png)

### Operating system

Windows 7

### Version of Telegram Desktop

4.0

### Installation source

Static binary from official website

**Comment by Rajbir98** [comment]
it happens at start but it fixes it self later

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/24664
