### ISSUE TITLE
[Question] Failed to obtain the login verification code

### ISSUE THREAD

**Issue by xiaopeng520** [telegramdesktop/tdesktop#24672]
Help me, why can't the mobile phone number in China get the login verification code. Now I have sent an email to sms@telegram.org, but the problem still exists

**Comment by Aokromes** [comment]
try downloading kotatogram to see if you can get activation code....

**Comment by xiaopeng520** [comment]
Does Kotatogram require registration？

**Comment by xiaopeng520** [comment]
I registered my telegram contact before Kotatogram, is there any on it?

**Comment by xiaopeng520** [comment]
help me.
