### ISSUE TITLE
[Feature Request] Programmatically reload telegram

### ISSUE THREAD

**Issue by guillaumeboehm** [telegramdesktop/tdesktop#24675]
### Is your feature request related to a problem?

From what I could tell there is no way to programatically trigger a reload of the interface if the theme changes in the filesystem.

### Describe the solution you'd like

The possibility to reload the interface from outside telegram, maybe with a process signal if possible.

### Describe alternatives you've considered

Watching for the current theme file changes and reloading the interface on change. (Thx @ilya-fedin)

### Additional context

I am using a theme generation program (wal-telegram) that modifies the theme file used by telegram when the wallpaper changes. The only way to load the newly generated theme is to restart telegram, which is not ideal.

**Comment by ilya-fedin** [comment]
> The only alternative is to kill and restart telegram.

Isn't watching for file change an alternative?

**Comment by guillaumeboehm** [comment]
Oh I'm sorry I thought this section was for work arounds. My bad.

**Comment by ilya-fedin** [comment]
I implemented the alternative variant (QFileSystemWatcher)
