### ISSUE TITLE
[Feature Request] Can you please disable auto full screen/pin for medias

### ISSUE THREAD

**Issue by RaSan147** [telegramdesktop/tdesktop#24684]
### Is your feature request related to a problem?

Whenever i try to open a image it turns full screen on desktop (which hampers my multi tasking)

And again when i play a video, it pops out and always stay on top. Imagine watching a movie at office and someone comes and you can't hide it *pain*

### Describe the solution you'd like

For Images: add a full screen button, and when not full screen show the image in the full window of the program

For videos: add stay on top (📌) button (enabled by default and can disable while playing or permanently disable from settings

### Describe alternatives you've considered

Had to switch to web.telegram.com for these reasons since they atleast don't make things full screen.

### Additional context

Please consider it 🛐

**Comment by ilya-fedin** [comment]
#1710
