### ISSUE TITLE
My Voice Sounds Like Robotic/Distorted/Deep on Voice Messages and Voice Chats 

### ISSUE THREAD

**Issue by eddysnjack** [telegramdesktop/tdesktop#24689]
### Steps to reproduce

Open any chat start to record voice
or
join a voice/video conversation

### Expected behaviour

Recorded voice shouldn't be robotic/fake, it should be natural as it's possible.

### Actual behaviour

My voice sounds like robotic/fake(exactly sounds like a hacker voice in a movie who try to hide it's voice)

### Operating system

Windows 10, 1703, Windows

### Version of Telegram Desktop

4.0 (x64)

### Installation source

Static binary from official website

### Additional Information:
 - I'm using a Lenovo g50 machine. 
 - Driver is Conexant Smart Audio HD
 - I tried to reinstall telegram many times
 - I tried to update my audio drive
 - Voice recording or voice calls are just fine with windows recorder, audacity, skype and microsoft teams
 
 This issue is similar to the #1233 btw but I'am using way newer version and have the same problem.

**Comment by buzhangjiuzhou** [comment]
I've encountered the same problem.

with :

win 10

and

telegram 4.0.2 (x64) download automatically by the app.

**Comment by AlekseiSmirnov** [comment]
Same problem on Mac (Telegram 9.0.1.237033 Stable)
When I use Airpods for voice messages, voice is distorted and becomes robotic

**Comment by Aokromes** [comment]
> Same problem on Mac (Telegram 9.0.1.237033 Stable) When I use Airpods for voice messages, voice is distorted and becomes robotic

you are using https://github.com/overtake/TelegramSwift

**Comment by Aokromes** [comment]
> I've encountered the same problem.
> 
> with :
> 
> win 10
> 
> and
> 
> telegram 4.0.2 (x64) downloaded automatically by the app.

what's your windows version and used hardware?

**Comment by buzhangjiuzhou** [comment]
> > I've encountered the same problem.
> > with :
> > win 10
> > and
> > telegram 4.0.2 (x64) downloaded automatically by the app.
> 
> what's your windows version and used hardware?

win 10 up-to-date, before I switch to my win11 new laptop, which doesn't have this problem, and I can't remember the exact version of it now, as well as the hardware info.

**Comment by Aokromes** [comment]
> > > I've encountered the same problem.
> > > with :
> > > win 10
> > > and
> > > telegram 4.0.2 (x64) downloaded automatically by the app.
> > 
> > 
> > what's your windows version and used hardware?
> 
> win 10 up-to-date, before I switch to my win11 new laptop, which doesn't have this problem, and I can't remember the exact version of it now, as well as the hardware info.

try to go to control panel, sound, record, advanced setting, and put one screenshot of that tab.

**Comment by Aokromes** [comment]
@eddysnjack read the post over this.

**Comment by buzhangjiuzhou** [comment]
> i don't have problems with:

Thanks for your efforts, but I just throwed it away(which is too old, I bought it 8 years ago), so I can't access it now, and this is why I said I can't remeber the exact version and hardware info of it.
