### ISSUE TITLE
[Question] about sorting contacts by last seen

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#24686]
Hello there, I was going through my list of contacts (which is sorted by default by last seen). My "last seen" privacy settings are set to "hidden" and I have one contact whitelisted (my mom 🥰)

I was expecting the list to be sorted this way (this is how it's sorted on android):
1. people I can see the exact last seen time
2. "last seen recently"
3. "last seen within a week"
4. "last seen within a month"
5. "last seen a long time ago"

It is actually sorted this way:
1. people I can see the exact last seen time
2. "last seen a long time ago"
3. "last seen recently"
4. "last seen within a week"
5. "last seen within a month"
6. some people with "last seen recently" that were recently active in some common groups

**Some examples**:

"last seen a long time ago" at the top of the list:
![image](https://user-images.githubusercontent.com/16143208/175263524-f2dc5b53-8069-4c5b-b026-d42abbaa08b2.png)

"last seen recently" after "last seen a long time ago":
![image](https://user-images.githubusercontent.com/16143208/175263930-f1622f81-a3ac-4d17-80f6-b7705c8bea05.png)

_some_ people with "last seen recently" after "last seen within a month" (contacts that recently wrote a message in a common group):
![image](https://user-images.githubusercontent.com/16143208/175264189-6751a300-78c4-46d4-a227-cf6c3d57d20c.png)

**Comment by RememberTheAir** [comment]
Re-reading the whole thing, I believe this should be submitted as a bug probably

**Comment by Aokromes** [comment]
i think one issue for this already exists...
