### ISSUE TITLE
The Flatpak version of Telegram 4 remains running in background after to close the window on Wayland and GNOME Shell vanilla

### ISSUE THREAD

**Issue by cold-distance** [telegramdesktop/tdesktop#24681]
### Steps to reproduce

1. Open the Flatpak version of Telegram 4 on GNOME Shell vanilla (I use Fedora 36 Silverblue without any extension).
2. Close the window.
3. You can see the app working in background even deactivating the permission with Flatseal.

Hi, in the previous versions of the Flatpak compilation of Telegram Desktop the app closed after closing the window, but in Telegram Desktop 4 the app now remains running in background after closing the window.

I don't see any option to close the process after closing the window and forbidding Telegram to run in background with Flatseal doesn't work either.

### Expected behaviour

I hope to see the app closed after closing the window or at least to have an option to deactivate the running in background.

### Actual behaviour

Telegram Desktop 4 always runs in background after closing the window on GNOME Shell vanilla (without any extension or modification) and Wayland.

### Operating system

Fedora 36 Silverblue, GNOME 42.2 and Wayland

### Version of Telegram Desktop

4.0

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
@23rd looks like you forgot to port https://github.com/telegramdesktop/tdesktop/blob/73af96e9c3aded665cb08e9a81b403963d6e1af1/Telegram/SourceFiles/window/main_window.cpp#L906
