### ISSUE TITLE
OSX: Ctrl + Option + "Б" and Ctrl + Option + "Ю" not works

### ISSUE THREAD

**Issue by vkdev** [telegramdesktop/tdesktop#2468]
For Russian keyboard this shortcuts are not works.
ctrl + option  + "б" should to print ","
ctrl + option + "ю" should to print "."

**Comment by vkdev** [comment]
Telegram Desktop: version 0.10.7

**Comment by Aokromes** [comment]
#1060 ?

**Comment by vkdev** [comment]
Yes, you right, @Aokromes , #1060 .

[See picture](http://store.storeimages.cdn-apple.com/4974/as-images.apple.com/is/image/AppleInc/aos/published/images/M/LA/MLA22RS/MLA22RS?wid=1200&hei=630&fmt=jpeg), symbol "Ю" is "." for us keyboard, "Б" – ",".

**Comment by Aokromes** [comment]
you can close yourself the ticket :)
