### ISSUE TITLE
The error of building Telegram 

### ISSUE THREAD

**Issue by JQUP20** [telegramdesktop/tdesktop#24685]
### Steps to reproduce

1、use VS2022 open the Telegram.sln
2、build

### Expected behaviour

there should have no errors and I get the Telegram.exe in the 'out' directory.

### Actual behaviour

when I used the Visual Studio 2022 build Telegram,there were some  errors:

E1696	Could not open source file "styles/style_basic.h"	lib_ui	C:\TBuild\tdesktop\Telegram\lib_ui\ui\painter.h	9	

E1696	Could not open source file "emoji.h"	lib_ui	C:\TBuild\tdesktop\Telegram\lib_ui\ui\emoji_config.h	12	

what's wrong is here?

### Operating system

Windows10, Visual Studio2022

### Version of Telegram Desktop

the newest

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
You cloned the repo without `--recursive`?

**Comment by JQUP20** [comment]
@ilya-fedin ,  I had,but maybe not all sub-module were cloned successfully.I cloned some sub-module  manually.Are you sure if I don't clone all the repo with--recursive, it will appear such errors?If that so,the first thing I need to do is solve the network problem...

**Comment by ilya-fedin** [comment]
you can use `git submodule update --init --recursive` to clone submodules later

**Comment by JQUP20** [comment]
I had tried it, finally there were no errors but I haven't gotten all sub-module

**Comment by ilya-fedin** [comment]
It's weird, maybe git entered some broken state

**Comment by Aokromes** [comment]
> I had tried it, finally there were no errors but I haven't gotten all sub-module

try deleting the directory and reclone again.

**Comment by JQUP20** [comment]
Ok,I will try again later,thanks a lot.

**Comment by mianhuadada** [comment]
I also encountered the same error. It seems that there is something wrong with the Lib_ui project

**Comment by mianhuadada** [comment]
Brother, has this problem been solved?

**Comment by ilya-fedin** [comment]
> E1696 Could not open source file "styles/style_basic.h" lib_ui C:\TBuild\tdesktop\Telegram\lib_ui\ui\painter.h 9
> 
> E1696 Could not open source file "emoji.h" lib_ui C:\TBuild\tdesktop\Telegram\lib_ui\ui\emoji_config.h 12

Those headers are generated by the codegens during build process
