### ISSUE TITLE
4.0: Freeze with pipewire

### ISSUE THREAD

**Issue by srakitnican** [telegramdesktop/tdesktop#24690]
### Steps to reproduce

Started noticing freezes after Telegram self updated to 4.0.

1. Telegram starts
2. Browse group chat content
3. Post with video sometimes freezes with errors in system messages

[journalctl.txt](https://github.com/telegramdesktop/tdesktop/files/8968446/journalctl.txt)

### Expected behaviour

Application renders video content and works without freezes.

### Actual behaviour

Telegram freezes frequently without recovery.

### Operating system

CentOS 8

### Version of Telegram Desktop

4.0

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#24678
