### ISSUE TITLE
fonts problem

### ISSUE THREAD

**Issue by vvchumanov** [telegramdesktop/tdesktop#24695]
### Steps to reproduce

1. any fonts don't support 

### Expected behaviour

font not showing in app

### Actual behaviour

font not showing in app

### Operating system

MacOS

### Version of Telegram Desktop

4.0.0

### Installation source

Static binary from official website

**Comment by vvchumanov** [comment]
<img width="1145" alt="Снимок экрана 2022-06-24 в 01 29 42" src="https://user-images.githubusercontent.com/10966892/175425837-b772354c-ce92-4060-bd93-10462647974a.png">

**Comment by vvchumanov** [comment]
also not premium supported, no status icon display

**Comment by ilya-fedin** [comment]
It's a Qt bug, it skips some fonts when (semi)bold style is used. Nothing could be done about that.
