### ISSUE TITLE
Video chat connection error

### ISSUE THREAD

**Issue by alextenyakov999** [telegramdesktop/tdesktop#24698]
### Steps to reproduce

1. install version 4 of telegram on ubuntu 20 via snap
2. create a video chat

### Expected behaviour

connecting to video chat

### Actual behaviour

can't connect to video chat

### Operating system

ubuntu 20

### Version of Telegram Desktop

4.0

### Installation source

Static binary from official website

**Comment by webarchitect609** [comment]
[4.0.1 is also affected by this bug](https://github.com/telegramdesktop/tdesktop/issues/24678#issuecomment-1165666298).

**Comment by ilya-fedin** [comment]
How about 4.0.2?

**Comment by webarchitect609** [comment]
> How about 4.0.2?

Still endless connecting to video chat 😢

[telegram-desktop.log](https://github.com/telegramdesktop/tdesktop/files/8984019/telegram-desktop.log)

**Comment by ilya-fedin** [comment]
well, I wonder what @alextenyakov999 would answer

**Comment by webarchitect609** [comment]
> well, I wonder what @alextenyakov999 would answer

OK, but I have tested the exact same environment twice: PC and laptop with Ubuntu 20.04 LTS and Telegram Desktop installed via snap. And the endless video chat connection bug repeats in versions 4.0.0, 4.0.1 and 4.0.2.

It's important for me to keep using video chats, so forgive me my persistance. For me it looks like you don't believe me that I'm also affected by this bug.

**Comment by john-preston** [comment]
@webarchitect609 If you create a group and start your own voice chat there, does it connect?

**Comment by webarchitect609** [comment]
@john-preston , no, it doesn't. I've tried two accounts with freshly created groups in each of them.

**Comment by john-preston** [comment]
@webarchitect609 Please contact me at t.me/preston and I'll ask you for logs.

**Comment by webarchitect609** [comment]
New info:

1. The bug occurs on TD **installed via snap**, but doesn't when installed/started from "Static binary from official website".

2. Giving all permissions to snap via GUI or `snap connect` commands doesn't help.

![](https://i.imgur.com/uwzX1lp.png)

[last_group_call_log.txt](https://github.com/telegramdesktop/tdesktop/files/8987234/last_group_call_log.txt)

**Comment by ilya-fedin** [comment]
> For me it looks like you don't believe me that I'm also affected by this bug.

I believe you have a different bug that should have separate issue

**Comment by webarchitect609** [comment]
> I believe you have a different bug that should have separate issue

OK. Here it is: #24721

But @alextenyakov999 most likely has the same environment(Ubutnu 20, TD v4 via Snap). He mentioned that in "Steps to reproduce", although selected "Static binary from official website" as a source. All what I wanted is to not create doubles.

**Comment by alextenyakov999** [comment]
sorry if I confused what I chose "Static binary from official website". I didn't know what to choose correctly

**Comment by alextenyakov999** [comment]
> Итак, вы подтверждаете, что в версии 4.0.2 все в порядке?
unfortunately, upgrading to 4.0.2 didn't help me

**Comment by ilya-fedin** [comment]
> unfortunately, upgrading to 4.0.2 didn't help me

Can you switch to https://telegram.org/dl/desktop/linux?

**Comment by alextenyakov999** [comment]
I can. I checked the desktop version the connection is working.
