### ISSUE TITLE
can not build succeed mac os 0.10.7

### ISSUE THREAD

**Issue by 314829125** [telegramdesktop/tdesktop#2469]
when i build 0.10.7
![2016-09-27 7 27 27](https://cloud.githubusercontent.com/assets/12060830/18871559/76b2b184-84e8-11e6-9cbc-8d17428144e4.png)
what  should i do ?
help me

**Comment by john-preston** [comment]
@314829125 Did you build crashpad successfully? You should have "../TBuild/Libraries/crashpad/crashpad/out/Debug" with "libbase.a".

**Comment by stek29** [comment]
@314829125 is the issue solved? If yes, what about closing it?

**Comment by auchri** [comment]
Reopen the issue if it's not solved.
