### ISSUE TITLE
Corrupt title bar in W7, bug not fixed in 4.0.1 

### ISSUE THREAD

**Issue by axopoulos** [telegramdesktop/tdesktop#24699]
### Steps to reproduce

1. Install update 4.0.0
2. Install fix 4.0.1
3. Title bar is corrupted
![image](https://user-images.githubusercontent.com/19383172/175555425-79ac513f-797c-4d0b-954e-06fa61a00296.png)

### Expected behaviour

Having a normal title bar as pre 4.0.0 update
![image](https://user-images.githubusercontent.com/19383172/175556453-417ef6ef-cfc6-4bc3-a391-645b974f3303.png)

### Actual behaviour

It can be temporary fixed by enabling and disabling "use native window" option but if you restart the app, the title bar is corrupt again.

### Operating system

Windows 7 64

### Version of Telegram Desktop

4.0.1

### Installation source

Static binary from official website

**Comment by cisko99za** [comment]
yes, confirmed. with win7 x64 and version 4.01 title bar is corrupt again (i use night mode, no tested on normal mode)

**Comment by asen1987** [comment]
confirmed ,w7 x64, ver4.0.1

**Comment by Kommprog** [comment]
![bug](https://user-images.githubusercontent.com/84424346/175655712-0f1c0865-80f5-47c2-af73-b21213e4f7b3.jpg)

Yes, the same bug is here again on Win 7 x64.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/ee1a80abd72890b326df35d6dea178b593b6364b

**Comment by axopoulos** [comment]
Confirmed its fixed in 4.0.2. Thanks.

**Comment by axopoulos** [comment]
> [ee1a80a](https://github.com/telegramdesktop/tdesktop/commit/ee1a80abd72890b326df35d6dea178b593b6364b)


Confirmed its fixed in 4.0.2. Thanks.

**Comment by cisko99za** [comment]
fixed on 4.02 version. thank you
