### ISSUE TITLE
No server-side decoration in Plasma on Wayland

### ISSUE THREAD

**Issue by zzag** [telegramdesktop/tdesktop#24697]
### Steps to reproduce

1. Check "Use system window frame" in settings

### Expected behaviour

Telegram has a server-side decoration

### Actual behaviour

Telegram uses client-side decoration provided by QtWayland. Telegram doesn't issue `zxdg_decoration_manager_v1.get_toplevel_decoration` requests.

### Operating system

Arch Linux

### Version of Telegram Desktop

4.0

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Apparently a bug in QtWayland then

**Comment by zzag** [comment]
> Apparently a bug in QtWayland then

It worked as expected in 3.7.1

**Comment by ilya-fedin** [comment]
Well, Telegram doesn't talk to Wayland directly. Yes, there were changes in QWindow::setFlag call order, but if that makes qtwayland fail, it's a qtwayland bug.

**Comment by zzag** [comment]
Anyway, this issue can be marked as a dup #24667, which looks to be fixed. Looking forward to the next release. :)
