### ISSUE TITLE
Telegram Desktop not starting on Arch Linux

### ISSUE THREAD

**Issue by Phylu** [telegramdesktop/tdesktop#247]
When I try starting TelegramDesktop, I only get the following error. The application does not start:

FT_New_Face failed with index 0 : 1
FT_New_Face failed with index 0 : 1
FT_New_Face failed with index 0 : 1
FT_New_Face failed with index 0 : 1

The version installed is: telegram-desktop 0.6.7

My system is Arch Linux: Linux 3.17.2-1-ARCH #1 SMP PREEMPT Thu Oct 30 20:49:39 CET 2014 x86_64 GNU/Linux

Any idea, what might cause the problem? I am willing to help debugging if needed and you provide me with information, what I can do.

**Comment by xapundel** [comment]
got the same error
Linux Linux 3.2.0-67-generic #101-Ubuntu SMP Tue Jul 15 17:46:11 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
fix with the same solution. Look like I tried to start 2 copies from different location of Telegram

**Comment by Pablohn26** [comment]
The same here with Fedora 20 Linux  3.17.8-200.fc20.x86_64 x86_64 x86_64 x86_64 GNU/Linux
killing the process with ps aux | grep -i telegram and kill telegram_pid seems fix the problem .
