### ISSUE TITLE
macOS regressions in 4.0.1

### ISSUE THREAD

**Issue by duskwuff** [telegramdesktop/tdesktop#24702]
### Steps to reproduce

1. Update from Telegram Desktop 4.0.0 to 4.0.1.

### Expected behaviour

* Menus should be present
* Option+Left/Right should jump to the previous/next word
* Option+Backspace should delete the previous word
* Cmd+Left/Right should jump to the beginning/end of a line

### Actual behaviour

* Menus are absent
* Option+Left/Right do nothing at all
* Option+Backspace deletes an unpredictable amount of text
* Cmd+Left/Right jump to the previous/next word

### Operating system

macOS 12.4 (ARM)

### Version of Telegram Desktop

4.0.1

### Installation source

Static binary from official website

**Comment by Antoha-GS** [comment]
Same on macOS Intel

**Comment by ilya-fedin** [comment]
How about 4.0.2?

**Comment by duskwuff** [comment]
That seems to have fixed it.  🎉 

Any idea what it was? I don't see anything obviously relevant in the commit history…

**Comment by john-preston** [comment]
@duskwuff https://github.com/desktop-app/patches/commit/38af8ef4c61f06f79b53af20a567dadd790896c3
