### ISSUE TITLE
Option+Backspace on macOS does Undo instead of deleting the previous word

### ISSUE THREAD

**Issue by yukuku** [telegramdesktop/tdesktop#24708]
### Steps to reproduce

1. Open any chat message field.
2. Type "hi you", remove all by pressing backspace multiple times, type "hi me"
3. Press option+backspace

### Expected behaviour

"me" is deleted. This is the same behavior as in Google Chrome, TextEdit, and pretty much all other text editors.

### Actual behaviour

The whole text box is cleared. If we press option+backspace again, "hi you" appears again. It is actually doing an "undo".

### Operating system

macOS 12.3.1

### Version of Telegram Desktop

4.0.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
There's 4.0.2 already

**Comment by yukuku** [comment]
@ilya-fedin thanks! It seems to have been fixed in 4.0.2.
