### ISSUE TITLE
Animated stickers with negative scales aren't rendered correctly on linux desktop

### ISSUE THREAD

**Issue by mbasaglia** [telegramdesktop/tdesktop#24715]
### Steps to reproduce

Look at this sticker https://t.me/premium/71

The sticker has a negative x scale on one of the layer (`layers[1].ks.s.k`) which I assume is what causing the issue

### Expected behaviour

Reference rendering from lottie-web (cropped because I'm not sure if the sticker counts as nsfw)
![Screenshot_20220625_205721](https://user-images.githubusercontent.com/2465791/175787011-9f664c22-b0cd-402d-a0f0-102069253422.png)

(It looks the same on the android client)

### Actual behaviour

Again, cropped
![Screenshot_20220625_205844](https://user-images.githubusercontent.com/2465791/175787056-ea58cc0e-cceb-45af-b35a-285741c8975d.png)

### Operating system

Ubuntu 22.04, KDE

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by vimpostor** [comment]
Then it renders incorrectly on Android too, doesn't it?

**Comment by mbasaglia** [comment]
No, on Android it's the correct way round

**Comment by vimpostor** [comment]
> No, on Android it's the correct way round

For me, the dogs are facing to the right on Android. I am using the official Telegram for Android, are you perhaps using a different client?

**Comment by mbasaglia** [comment]
Odd, for me on Android the message itself is rendered incorrectly but if you send a link to the message it's rendered correctly
