### ISSUE TITLE
Wrong input chat when clicking via inline query bot

### ISSUE THREAD

**Issue by 01101sam** [telegramdesktop/tdesktop#24717]
### Steps to reproduce

1. Prepare a "via bot" message
![image](https://user-images.githubusercontent.com/100821827/175828579-4c998e31-76d9-45e8-919f-90acf054d0ad.png)

2. Click on the "via bot" message

### Expected behaviour

The via input should stay on current chat window
![image](https://user-images.githubusercontent.com/100821827/175828705-388f1446-a761-40ee-b09d-59bb08d99dcc.png)

### Actual behaviour

The input jumps back to main window
![image](https://user-images.githubusercontent.com/100821827/175828605-87f3033e-5d28-4cae-a319-4b9c49a285b1.png)

### Operating system

Windows 10 LTSC

### Version of Telegram Desktop

4.0.2 x64

### Installation source

Static binary from official website

**Comment by mb6ockatf** [comment]
I guess it is a normal behaviour

**Comment by 01101sam** [comment]
> I guess it is a normal behaviour

I don't agree. How this is "normal"? Every window should be independent from its chat input

**Comment by mb6ockatf** [comment]
> > I guess it is a normal behaviour
> 
> I don't agree. How this is "normal"? Every window should be independent from its chat input

Well, it is not possible to launch 2 instances of Telegram desktop (non-portable) so as they work in parallel. Tried in windows 10, windows 11 Home 22000.778, Debian 11.
Probably, it is possible with portable telegram and related to this.

**Comment by 01101sam** [comment]
> > > I guess it is a normal behaviour
> > 
> > 
> > I don't agree. How this is "normal"? Every window should be independent from its chat input
> 
> Well, it is not possible to launch 2 instances of Telegram desktop (non-portable) so as they work in parallel. Tried in windows 10, windows 11 Home 22000.778, Debian 11. Probably, it is about portable telegram and related to it.

No, I'm not meaning the both of the window should be 2 instances,
I mean 2 chat input should be standalone with their chat.
In my reproduction I showed when interacting with "via bot" the result showed in first chat input but not the targeted one.

**Comment by mb6ockatf** [comment]
So, when you enter some text to the text field and then push a button which leads to other chat, you have all your text in a new field. The text should have left at the previous chat (probably saved as a draft). Am I right?
It'd be difficult for me to reproduce as everyone who I know on telegram have restricted getting a link to their accounts from their forwarded messages.

**Comment by 01101sam** [comment]
> So, when you enter some text to the text field and then push a button which leads to other chat, you have all your text in a new field. The text should have left at the previous chat (probably saved as a draft). Am I right? ~It'd be difficult for me to reproduce as everyone who I know on telegram have restricted getting a link to their accounts from their forwarded messages.~

https://user-images.githubusercontent.com/100821827/176884759-764cdc48-35fc-4c71-9ae4-d090dd4e0397.mp4

**Comment by mb6ockatf** [comment]
Thank you much for the video. I got what do you mean.
There must be a problem with ctrl-click window behaviour (i guess so).

**Comment by 01101sam** [comment]
Related:

https://user-images.githubusercontent.com/100821827/180278982-ee9c3226-ffaa-462b-af1c-248a2496d7a6.mp4
