### ISSUE TITLE
Sounds/Music after upgrading to version 4.x+ not have any output sound

### ISSUE THREAD

**Issue by amingholami** [telegramdesktop/tdesktop#24710]
### Steps to reproduce

checked sounds output in telegram and check all output devices, no sounds output.

### Expected behaviour

Sounds/Music after upgrading to version 4.x+ playing but has no sound.

### Actual behaviour

Sounds/Music after upgrading to version 4.x+ playing but has no sound.

### Operating system

Windows 10 Enterprise 21H2 build 19044.1766 Windows Feature Experience Pack 120.2212.4180.0

### Version of Telegram Desktop

4.0.2 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can you show the log.txt?
