### ISSUE TITLE
Source code and git tag for 0.10.8?

### ISSUE THREAD

**Issue by gavv** [telegramdesktop/tdesktop#2471]
Hi,

It seems that the latest version in this repo is 0.10.7, while desktop.telegram.org suggests to download 0.10.8, and "Alpha version" section from that page suggests to download 0.10.4.

So the questions are:
* is the source code available for 0.10.8?
* what is the right place to look for a stable release, github repo or desktop.telegram.org?
* what is the right place to look for the latest alpha?

**Comment by john-preston** [comment]
@gavv The right place to look for the latest official versions is https://desktop.telegram.org website. Alpha version can be smaller than the stable, if stable was out later — alpha will just auto-update to stable after launch. Source code will be uploaded in a couple of days, sorry.

**Comment by gavv** [comment]
Thanks.
