### ISSUE TITLE
Big window size → all messages on the left

### ISSUE THREAD

**Issue by zlodes** [telegramdesktop/tdesktop#2472]
### Steps to reproduce
1. Display more 1366px width
2. Resize messenger window more then 1366px 

### Expected behaviour
Chat messages looks good → ![screenshot](https://s22.postimg.org/r8ccvn9w1/261a093388.png)

### Actual behaviour
All messages located on the left → ![screenshot](https://s10.postimg.org/do7emmqah/123.png)

### Configuration
Ubuntu 16.04 x64

**Version of Telegram Desktop:**
0.10.8

**Comment by auchri** [comment]
There's a setting for this behaviour. Duplicate BTW.
