### ISSUE TITLE
[Feature Request] Paid corporate messaging features

### ISSUE THREAD

**Issue by forsaled** [telegramdesktop/tdesktop#24726]
### Is your feature request related to a problem?

For now Telegram has almost everything to be a Slack-Zoom-killer, but in unstable state. Lags in video, voice delays etc don't allow Telegram to be the first considered option of the corporate messaging, replacing Zoom and Slack.

### Describe the solution you'd like

Telegram should add paid freatures to become a corporate messaging app number 1. Those are:
* stable video calls p2p and group conferences
* stable desktop sharing
* smooth google docs, ms office etc extentions

The point is - it should be paid (because it is really a small but valuable segment of all users, there is no need to make it for everybody) and stable (for the price you will have to use additional servers and resources for those features).

### Describe alternatives you've considered

Slack, MS Teams and Zoom which are still poor and not worthy, but only options on the big and rich market. I, been a faithfull and inspired user (and even inspiring evangelist) of Telegram for years, still cannot use it for teams on my projects because of unstable p2p and p2g video calls.

### Additional context

If there are some other channels for requesting features - please, head me in the right direction.

**Comment by RememberTheAir** [comment]
This is out of the scope of this client, you should bring it to https://suggestions.telegram.org
