### ISSUE TITLE
Endless video chat connection for Snap

### ISSUE THREAD

**Issue by webarchitect609** [telegramdesktop/tdesktop#24721]
### Steps to reproduce

1. Install TD version 4.0.0 or 4.0.1 or 4.0.2 via Snap.
2. Make your own group.
3. Start new video chat in this group.

### Expected behaviour

Video chat started and connection is established.

### Actual behaviour

Video chat is started, but endless "Connecting..." is shown.

https://user-images.githubusercontent.com/11293610/175873059-faa46ecb-8a5b-4306-b318-f2057e115fa8.mp4

### Operating system

Ubuntu 20.04.4 LTS. ubuntu:GNOME

### Version of Telegram Desktop

4.0.2

### Installation source

Snap

### Logs

[last_group_call_log.txt](https://github.com/telegramdesktop/tdesktop/files/8989152/last_group_call_log.txt)

### Additional info

1. If TD is installed from the static binary from official website, this bug will disappear.

2. Giving all permissions to snap via GUI or `snap connect` commands doesn't help.

**Comment by ilya-fedin** [comment]
It seems video chats are incompatible with openssl 3.0 and core22 runtime doesn't have openssl 1.1 anymore. Can't you just migrate to one of other installation methods?

**Comment by webarchitect609** [comment]
> Can't you just migrate to one of other installation methods?

Yes, I had to and already did. But I hope Snap version will be fixed one day.

**Comment by ilya-fedin** [comment]
Maybe... It seem to be non-trivial though.
