### ISSUE TITLE
snap version can't connect to videochats

### ISSUE THREAD

**Issue by al-zatv** [telegramdesktop/tdesktop#24736]
### Steps to reproduce

1. install snap version on linux
2. press "join" on any video chat in progress
3. and, you see infinite "connecting..." 

But, in .tar.gz version, everything goes fine.

### Expected behaviour

it should connect to videochats:) 

### Actual behaviour

It can't connect to videochat. I see infinite "connecting..." message.

### Operating system

ubuntu 22.04

### Version of Telegram Desktop

4.0.2

### Installation source

Snap

**Comment by Aokromes** [comment]
fixed on future 4.0.3
