### ISSUE TITLE
[Feature Request] Camera selection function for video message

### ISSUE THREAD

**Issue by yashaka** [telegramdesktop/tdesktop#24733]
### Is your feature request related to a problem?

It's possible to select camera source for calls, but no way to change camera source for video messages... 

### Describe the solution you'd like

Being able to set default video source to be used in video messages

### Describe alternatives you've considered

I don't know any alternative...

**Comment by ilya-fedin** [comment]
tdesktop doesn't support recording video messages

**Comment by yashaka** [comment]
@ilya-fedin 
Please, help me to understand where I am wrong in my understanding...
<img width="553" alt="image" src="https://user-images.githubusercontent.com/1961118/176612602-60f98ec9-d164-4d73-8c81-a2c3a0c2d3e7.png">

I thought that the 'camera' button in the bottom right corner, that appears after "microphone" button was clicked – is the button to trigger video message. Once recordered the "video message circle-bubble with video" will appear in the chat.

**Comment by ilya-fedin** [comment]
It's not tdesktop on your screenshot... You can get tdesktop here from GitHub Releases and compare.

**Comment by yashaka** [comment]
Ah... I see! Got it! Thank you!
