### ISSUE TITLE
Callback Query Answer string cut off for specific accounts

### ISSUE THREAD

**Issue by Poolitzer** [telegramdesktop/tdesktop#24739]
### Steps to reproduce

1. Write to the https://t.me/CutOffAnswerStringsBot
2. Pick one of the two buggy answer strings
3. Click on the button to check if the string shown in the query answer is the same as in the message

### Expected behaviour

See the full same string

### Actual behaviour

The last word is cut off at least for two users who reported this to me. I can not reproduce this on my own account.
![image](https://user-images.githubusercontent.com/25934244/176651206-42342c3b-c3be-4b77-a4e6-ff86ddaf9878.png)
and
![image](https://user-images.githubusercontent.com/25934244/176651230-abaa6e10-416c-46b4-a21d-6d8658dec927.png)

Both users reported back that it works fine for them using different clients on their phones

### Operating system

Windows 10

### Version of Telegram Desktop

Version 4.0.2

### Installation source

Static binary from official website

### Logs

```shell
I do not have their logs, if it is important I can ask.
```

**Comment by Poolitzer** [comment]
A third string has been found and added to the bot. Same behavior: I see the full string, the both reporting users do not,

**Comment by Poolitzer** [comment]
Both of them on 4.0.2, both of them on 100% scale in OS as well as app, one interface in German, one in English.

Both remember being able to see the answer strings fully sometime in the past. They are part of a game bot I manage.

**Comment by 23rd** [comment]
Can you please check the latest version?

**Comment by Poolitzer** [comment]
This has been confirmed fixed by both parties.
