### ISSUE TITLE
[Question] How to switch screen share to letterbox?

### ISSUE THREAD

**Issue by dancojocaru2000** [telegramdesktop/tdesktop#24730]
When the call window is small, the screen share is shown in a letter box way, but if I maximize it, the screen share is shown zoomed in, and I can't see stuff at the edge of the screen.

**Comment by ilya-fedin** [comment]
Are you sure you're using actual screen share provided by the client and not some kind of virtual webcam? Screen share is always letterboxed exactly to see stuff at the edge.

**Comment by dancojocaru2000** [comment]
I'm pretty sure the person I was talking with used the screen cast option in Telegram Desktop. Will update in a bit to confirm with certainty and provide screenshots.

Even if it was a virtual webcam, I'd argue there should still be an option to letterbox the webcam image.

**Comment by dancojocaru2000** [comment]
Tested myself, all I did between the two screenshots was making the window bigger:

![Small window](https://user-images.githubusercontent.com/9626761/176366334-6abaebee-4687-49f5-b932-633bebab88a3.png)

![Big window](https://user-images.githubusercontent.com/9626761/176366368-4ecb0a65-798e-400c-be99-6fdcdc4b6eff.png)

**Comment by dancojocaru2000** [comment]
Ideally, I should be able to switch between zoom and letterbox myself (perhaps through an icon or a right click menu?)
