### ISSUE TITLE
Wrong amount of "max reactions" on chat messages

### ISSUE THREAD

**Issue by oplexz** [telegramdesktop/tdesktop#24737]
### Steps to reproduce

1. Send a message in some chat
2. Have 2 people see the message
3. Add a reaction to your message
4. Right-click the message to see how many reactions it has received

### Expected behaviour

Should be 1 out of 3 people (you (reacted), user 1, user 2)

### Actual behaviour

1 out of 2 people (your reaction counts, but neither user 1, nor user 2 have reacted to this message)

### Operating system

Windows 11 Build 22621.105

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by oplexz** [comment]
Some screenshots to make this issue a bit easier to understand:

![image](https://user-images.githubusercontent.com/12859907/176495282-d2f2313d-d183-44a5-9607-2a13bb9f7105.png)

![image](https://user-images.githubusercontent.com/12859907/176495364-2a2a9a9d-6a4c-4d14-a450-e0a067b6905f.png)

**Comment by mb6ockatf** [comment]
Have the same:
<img width="400" alt="Screenshot 2022-07-01 123400" src="https://user-images.githubusercontent.com/104227451/176868496-549ad9f3-1bf7-4137-961d-17c66aa47988.png">

**Comment by RememberTheAir** [comment]
This is consistent with the android app, I'm starting to believe it is the intended behavior. Indeed it's a little confusing, especially when only one person has seen the message. I first reported it in December 2021: https://t.me/tgbetachat/957372

**Comment by oplexz** [comment]
@RememberTheAir well, the count is obviously wrong, so it can't be the intended behavior. I'm pretty positive this is just too small of an issue to fix right now.

**Comment by RememberTheAir** [comment]
un-stale

**Comment by RememberTheAir** [comment]
still relevant I guess

**Comment by mb6ockatf** [comment]
idk, works ok now

**Comment by oplexz** [comment]
unstale

**Comment by RememberTheAir** [comment]
un-stale, but I wonder whether this is still relevent or not. It hasn't been addressed for a few years now so probably it's how it is supposed to work

**Comment by mb6ockatf** [comment]
version 5.2.3, cannot reproduce, works as intended. is it still an issue?

**Comment by oplexz** [comment]
Cannot reproduce on version 5.2.3; closing the issue.
