### ISSUE TITLE
[Feature Request] [UI] add Muted icon to the user box in chat list

### ISSUE THREAD

**Issue by hessam-kk** [telegramdesktop/tdesktop#24732]
### Is your feature request related to a problem?

There is no indicator to figure out if a user is muted or not. In mobile version, an icon will be appeared when a user becomes mute,  but in desktop version not.

### Describe the solution you'd like

An icon like a crossed out Speaker appear in front of a muted user:
_My Friend 🔇_
![asas](https://user-images.githubusercontent.com/24957423/176302220-6316669f-012a-41b6-b981-5f40705e7b9d.png)
something like this.

### Describe alternatives you've considered

fade out or lowering transparency for that user in chat list... :/

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5981
