### ISSUE TITLE
Groups. When "Send media" permission is off, you can still post images' previews via links

### ISSUE THREAD

**Issue by roaddust2** [telegramdesktop/tdesktop#24738]
### Steps to reproduce

1. Disable "Send media" in "Permissions" in group/chat settings (Manage group)
2. Copy image link url from the Internet
3. Paste link in message input field
4. Send
5. Preview will be available under the posted link (What is a media actually in a "preview" form)

### Expected behaviour

Only the link of picture should be sent, not the picture itself (even as a preview)

### Actual behaviour

Image preview is displayed below the link when the media is disabled in group settings

### Operating system

Pop!_OS 22.04 LTS (Ubuntu 22.04 actually)

### Version of Telegram Desktop

4.0.2

### Installation source

Flatpak

**Comment by RememberTheAir** [comment]
There's a specific permission to disable webpage previews, "embed links"

**Comment by Aokromes** [comment]
not a bug.

**Comment by roaddust2** [comment]
Okay thank you for the answer
