### ISSUE TITLE
Strange behavior after enabling autostart in wayland

### ISSUE THREAD

**Issue by KotoWhiskas** [telegramdesktop/tdesktop#24731]
### Steps to reproduce

If running telegram from repos:

1. Load boot kde wayland session
2. In telegram settings, enable autostart
3. Logout and login

If running telegram from binary file:

1. Go to KDE setting > Startup and shutdown > Autostart > Add telegram binary file
2. Logout and login

### Expected behaviour

Telegram tray icon shows and after opening and closing telegram tray icon is still there

### Actual behaviour

After loading DE, telegram tray icon doesn't appear. After opening telegram from application launcher (or executable) it seems to be already loaded, but when you after that press X button, it exits completely. Only after opening it again it's behavior becomes normal.

### Operating system

Arch Linux KDE Plasma 5.25.2

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
It's https://bugs.kde.org/show_bug.cgi?id=425315 / https://bugreports.qt.io/browse/QTBUG-94871

**Comment by ilya-fedin** [comment]
Nothing we can do about that :man_shrugging:
