### ISSUE TITLE
[Feature Request] [Telegram Android] Option to disable screen overflow round chat links

### ISSUE THREAD

**Issue by CODER591** [telegramdesktop/tdesktop#24748]
### Is your feature request related to a problem?

Make an option in settings to disable these round chat links Telegram-wide or at least for each chat.

It is very irritating, when you
1) occasionally push on that notification, and application which is currently opened is closing.
2) when you are deleting them from the screen, and they recreating themselves after some time.

![image](https://user-images.githubusercontent.com/33939665/177031238-7d26e677-8cdc-4345-9f69-8f0552b4e146.png)

### Describe the solution you'd like

Additional option in chat-settings with the person/group/channel, to turn off the overflow-chat links.
Also provide the general list in settings "Notification and sounds" with disabled ones.
However, It could be the same list with "notification exceptions" which exist already.

### Describe alternatives you've considered

The separate chapter in the settings "Notification and sounds" with on/off flag
And list of chats-exeptions

### Additional context

Please, do not make this feature exclusively for the telegram premium.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
