### ISSUE TITLE
Music search doesn't do partial match on Desktop, works on Mobile

### ISSUE THREAD

**Issue by f3flight** [telegramdesktop/tdesktop#24745]
### Steps to reproduce

1. open any chat with sufficient amount of music shared
2. click on username, then XX Audio files
3. scroll a bit to get a search bar, enter any partial match (part of audio title)

### Expected behaviour

You should see all music which has your string as part of their name.

Important note - this search feature works correctly on Android!

### Actual behaviour

Nothing found

### Operating system

Windows

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by didich72598** [comment]
Mold otvorete go
