### ISSUE TITLE
[Feature Request] Control over notification volume

### ISSUE THREAD

**Issue by FinecoFinit** [telegramdesktop/tdesktop#24749]
### Is your feature request related to a problem?

Too loud samples. I can't lower all volume for tdesktop because I sometimes play music from it

### Describe the solution you'd like

Volume control over all custom notification sounds

### Describe alternatives you've considered

Master volume for notification sounds

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/151
