### ISSUE TITLE
The generated telegram project file is incomplete

### ISSUE THREAD

**Issue by mianhuadada** [telegramdesktop/tdesktop#24742]
### Steps to reproduce

1 use VS2022 open the Telegram.sln
2 build

### Expected behaviour

No project dependent files were generated under folder Gen

### Actual behaviour

During the process of generating the project file, no error is reported, but no file is generated in the e:\tbuild\buildpath\tdesktop\out\telegraph\gen directory, Therefore  When compiling the Telegram.sln project ,the error of missing four files such as emoj.h will be reported

### Operating system

win10-21H2 Visual Studio2022

### Version of Telegram Desktop

the newest

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> \telegraph

telegraph?

**Comment by mianhuadada** [comment]
Both  E:\TBuild\BuildPath\tdesktop\out\Telegram\gen   and  E:\TBuild\BuildPath\tdesktop\out\Telegram\lib_ui\gen   folders are empty

**Comment by mianhuadada** [comment]
> Both E:\TBuild\BuildPath\tdesktop\out\Telegram\gen and E:\TBuild\BuildPath\tdesktop\out\Telegram\lib_ui\gen folders are empty

**Comment by ilya-fedin** [comment]
They're filled during build process

**Comment by mianhuadada** [comment]
These two folders have been empty

**Comment by mianhuadada** [comment]
![1](https://user-images.githubusercontent.com/44740248/176844544-4a321796-0a75-4da5-8cf2-52aefae0fa05.png)

**Comment by mianhuadada** [comment]
![2](https://user-images.githubusercontent.com/44740248/176844705-896874dc-c065-42fd-91df-3515a0e0263d.png)

**Comment by mianhuadada** [comment]
However Thank you very much

**Comment by LemonPG** [comment]
I encountered the same problem as you. Have you solved it?
