### ISSUE TITLE
Constant bouncing of icon on KDE Wayland when window is activated

### ISSUE THREAD

**Issue by hiornso** [telegramdesktop/tdesktop#24744]
### Steps to reproduce

1. I am uncertain of whether this issue occurs on other distros, but I know it occurs for me using Manjaro KDE, so it may be necessary to install Manjaro KDE.
2. Install Telegram 4.x
3. Open Telegram.
4. Activate the application with the mouse, e.g. by right clicking or clicking on a menu or double clicking a message. (Does not occur if nothing is activated, e.g. single clicking on background.)

NB: This only occurs on Wayland. If I launch with `QT_QPA_PLATFORM=xcb telegram-desktop` to force use of X11, this does not occur.

Also, I did not have this issue with Telegram 3.7.3. Upgrading to 4.0.0 or 4.0.2 makes the issue appear, downgrading back to 3.7.3 makes it go away again. So the issue was introduced somewhere between 3.7.3 and 4.0.0.

Also, I am no expert, so I may be wrong (if I am, my apologies) but I did do a bit of hunting through commits and thought https://github.com/telegramdesktop/tdesktop/commit/d353e110776dee0e54398944abd12bec71961e7d looked like it might be related.

### Expected behaviour

Whatever you clicked on got activated.

### Actual behaviour

As well as the expected behaviour, a bobbing telegram icon appears next to the mouse and continues bobbing for about 5s.

### Operating system

Manjaro, KDE Plasma 5.24.5 on Wayland.

### Version of Telegram Desktop

4.0.0

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
This is a KDE bug, they play application launch animation on every focus request on Wayland

**Comment by KotoWhiskas** [comment]
It's duplicate of [#24711](https://github.com/telegramdesktop/tdesktop/issues/24711)
