### ISSUE TITLE
add participant to supergroup

### ISSUE THREAD

**Issue by sinaprog** [telegramdesktop/tdesktop#2475]
hi 
in schema.tl UpdateChatParticipantAdd gets ChatId as int but supergroup has chatid in long format 
how to add participant to super group???

**Comment by john-preston** [comment]
@sinaprog There is a channels.inviteToChannel method.

**Comment by sinaprog** [comment]
It works for supergroup too???

**Comment by stek29** [comment]
@sinaprog Supergroups are channels too :)

**Comment by T3rminat0r** [comment]
Guess this is solved? ;)

**Comment by sinaprog** [comment]
i used invitetochannel method but it returns peer_flood error
please tell what this means???
