### ISSUE TITLE
Microphone works in calls but not when recording a voice msg

### ISSUE THREAD

**Issue by adnanhaddad** [telegramdesktop/tdesktop#24755]
Hello!

Title says it all actually. I'm on the latest stable Telegram windows version (win 10). During calls the microphone works perfectly but somehow not when recording a voice message. There seem to be no way to change the setting for that specific thing only, just the input device in general. Any idea how to solve this? 

Thank you

**Comment by ilya-fedin** [comment]
> just the input device in general

Well, there's no 'general input device' settings, there's only 'calls input device' setting. If you changed input device for calls and expected that the setting will be applied to voice messages as well, that assumption was wrong. Ensure that the microphone is your default device.
