### ISSUE TITLE
Gifs do not play in new chat windows

### ISSUE THREAD

**Issue by groig** [telegramdesktop/tdesktop#24757]
### Steps to reproduce

1. Enable "New chat window by Ctrl+Click" in Experimental settings
2. Open a new chat window by Ctrl+Click on any conversation
3. Send a gif
4. Try to play it 

### Expected behaviour

The gif plays

### Actual behaviour

The gif does not play

### Operating system

Arch Linux, bspwm

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by glpzzz** [comment]
same behavior here

**Comment by nesty92** [comment]
same here

OS: Manjaro Linux x86_64 
DE: Plasma 5.24.5 
WM: KWin

**Comment by aNNiMON** [comment]
Reproducible in 4.5.2 on Windows
