### ISSUE TITLE
[bug] Kicked/banned admins can still see old/new messages on private group

### ISSUE THREAD

**Issue by EDM115** [telegramdesktop/tdesktop#24752]
### Steps to reproduce

1. Be on a group
2. Write something, then hold <kbd>shift</kbd>, <kbd>ctrl</kbd> or <kbd>command</kbd>
3. Be kicked/banned

### Expected behaviour

The user no longer is in the chat, and can't see messages (old, and above all new)

### Actual behaviour

The user is still able to read messages anterior to his ban/kick, plus he can see new messages
Moreover, his name doesn't appear on "seen list"

*fix* : when an user is kicked/banned, the concerned chat must be deleted on his side

### Operating system

Windows 10 

### Version of Telegram Desktop

v4.0.2, also happen on previous ones and seen list bug appears on every platform

### Installation source

Static binary from official website

**Comment by EDM115** [comment]
From what I know, it's also reproducible on MacOS  
Plus, this bug can lead to conversation leaks, which haolebed to me recently

**Comment by RememberTheAir** [comment]
Is the group chat public (that is, the chat has a public username)?

**Comment by EDM115** [comment]
> Is the group chat public (that is, the chat has a public username)?

No, private chat  
+ links for joining are revoked every week, tho it doesn't change anything on the kicked user side

**Comment by EDM115** [comment]
Seems to happen only if the member were admin (title of issue modified in consequence)
