### ISSUE TITLE
Chat orientation changes when entering full screen or resizing window to a certain width

### ISSUE THREAD

**Issue by mubashirtanveerayon** [telegramdesktop/tdesktop#24759]
### Steps to reproduce

1. open a chat
2. enter full screen mode/ expand window width
3. messages sent by me are shown on the left with the messages the other person sent where normally it should be on the right side.
4. Here is how it looks when I enter fullscreen
![tg_bug](https://user-images.githubusercontent.com/76165265/177474851-e45b5a83-1ff9-4b56-9d20-00554e111c03.png)

### Expected behaviour

Messages that I sent should be on the right side separated from the other person's messages.

### Actual behaviour

Messages sent by me are shown on the left with the messages the other person sent where normally it should be on the right side.

### Operating system

Windows 10 pro x64, Pop_!OS, DE : Gnome

### Version of Telegram Desktop

4.0.2-x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
not a bug, disable adaptative layout.
