### ISSUE TITLE
Cannot connect to group video chat

### ISSUE THREAD

**Issue by leonidgo** [telegramdesktop/tdesktop#24754]
### Steps to reproduce

Open any group with running video chat and click join or
Create a group, then start a video chat

### Expected behaviour

Connect and be able to speak and listen to other users

### Actual behaviour

Window with a list of users in video chat pops up but telegram keeps connecting endlessly, while you can't hear and be heard by other users

### Operating system

Ubuntu 20.04.4

### Version of Telegram Desktop

4.0.2

### Installation source

Snap

**Comment by Aokromes** [comment]
this will be fixed on the future 4.0.3 or on snap dev.
