### ISSUE TITLE
Recovering the Downloads Folder ("Telegram Desktop") after reinstalling Telegram in Windows 10

### ISSUE THREAD

**Issue by zavareh89** [telegramdesktop/tdesktop#24769]
Hi guys. Today I uninstalled telegram and reinstalled its latest version (4.0.2). I understand that Telegram deletes all cached images and messages while uninstalling. However it hasn't deleted the Download folder (C:\Users\Username\Downloads\Telegram Desktop) which contains videos, files, pdf and so on. Now after reinstalling, Telegram can't recognize and can't find the downloaded files from the previous version. My question is that **is there any solution so that my current version of Telegram can recognize and open the downloaded files (e.g. old videos, or pdfs) without redownloading it?** Note that both versions have the same directory for download folder (Downloads\Telegram Desktop).

**Comment by john-preston** [comment]
No, sorry, no way for that right now. It is theoretically possible to check hashes instead of re-downloading of files, but this requires a lot of work.
