### ISSUE TITLE
[URGENT] TELEGRAM SUPPORT + TELEGRAM VOLUNTEER + TELEGRAM BOTS INFINITE ISSUES

### ISSUE THREAD

**Issue by imperiumsecurity** [telegramdesktop/tdesktop#24761]
### Steps to reproduce

Sorry guys: And please '' spare '' me with the generic response: '' Hey pal: Not a telegram desktop issue ''

I have SERIOUS issue with my account SINCE THOUSANDS of years !
I paid for this PREMIUM telegram membership for what ?
Just to GIVE YOU GUYS / GIVE TELEGRAM = FREE $$$$ / MY HARD EARNED money
And when i need '' PREMUM '' support (you are selling the premium for what then?) then i can't get it ? 

I'm admin of BIG SUPER GROUPS on telegram in latin america (With over 75.000+ and was 110.000 before i had to LOCK DOWN THE group because of DISGUST / DISAPPOINTMENT with such UNEXISTANT '' CARE '' and RESPECT from the telegram support with it's own users !) and i get attacked EACH AND EVERY SINGLE DAY

By COMPETITORS, JEALOUS / ST****D people, and all sorts / likes !

And this people POWERS to truly = DESTROY / MAKE A '' SERIOUS '' telegram user account
completely UNUSABLE + THE TOTAL '' LACK OF RESPONSIBILITY, RESPECT & CARE '' by the so called telegram support

Is very funny to see.....

Specially now the  = PAID ONES

(if you start charging for something you have MORAL DUTY of providing at last a MINIMALLY ACCEPTABLE help, to such SUPPORTERS / USERS who put food on your table / contributed with your project)

This is basic matter of = HONOR / GENTLEMAN-ISH attitude....
(Which is unexistant by them)

So i'm having my account ATTACKED over and over and over by stu**** people for = No valid reason at all

And then they get my account EVERY WEEK 
Completely LIMITED BY '' ETERNAL '' SPAM condition = FOREVER !

And yes ONE single report is enough, for get your account SHUTDOWN PERMANENTLY !

I'm gonna reference TWO THREADS right now on below, from REDDIT community
talking about this ISSUES.

This threads are from THOUSANDS OF YEARS AGO (6 years to be more precisely, which is quite RIDICULOUS for you / for such a company like telegram)

`https://www.reddit.com/r/Telegram/comments/5gv58v/metatelegrams_reporting_system_is_stupid_and/`

`https://www.reddit.com/r/Telegram/comments/5dqwke/does_telegram_support_exist/`

AND WORSE ?

THERE'S = CHILD PORNOGRAPHY !
BEING '' FREELY PERMITTED / ALLOWED + FREELY SPREAD + FREELY MAINTAINED " = WITHIN YOUR SERVERS !

Which even for the LACK OF CARE / OMISSION towards this could render mister durov THOUSANDS of years behind bars / in jail, for being = COMPLIANT

With such bizarre and totally IN-HUMAN activity going thru / happening and being hosted FREELY through his dear platform !
(i know THEM ALL, i have investigated + hunted + took down SOME of them myself (their channels, accounts, groups etc)

but when it's a LEGITIMATE person doing SERIOUS work they don't care, right ?!

Been trying to reach out telegram support through different modes: FOR THOUSANDS OF YEARS !
AND I'M TRULY = TIRED !

Of having my WORK ACCOUNT = COWARDLY ATTACKED
And locked up / becoming TOTALLY UNUSABLE, for no valid reason at all ! 

I have tried mailing 1000 times, tried volunteer support within the app, tried to reach out via Twitter but never received a single response from Telegram !

THIS IS A = BIG JOKE !!!!!!!!!!!!!
OK ?

I WANT A RESPONSE FROM A = RESPONSIBLE HUMAN BEING !
ABOUT THIS = FUNNY / RIDICULOUS SITUATION

When you launched / users (LIKE ME ! WHO NEED TELEGRAM FOR = BUSINESS / WORK ! )
are = DIRECTLY SUPPORTING YOUR PROJECT WITH FUNDS NOW $$$$$$$$

And are being = TOTALLY IGNORED
As if they were complete PIECES OF USELESS S********** !

Hope to hear / see a  = JUSTICE-ORIENTE / SERIOUS / HUMAN OF HONOR / MAN OF HONOR / WOMEN-OF-HONOR

To see this and to offer some help to a TELEGRAM PROJECT SUPPORTER /ADVOCATE (MYSELF ! ) and help me solve this issue
as well as SHED SOME LIGHT on SOME of the = SERIOUS / URGENT MATTERS / ISSUES i mentioned within this post here today

(About the CHILD PORN among the other things like a UNRESPONSIVE, UNFAIR, AND '' USELESS / ARBITRARY '' TELEGRAM @SPAMBOT APPEAL SYSTEM + THE UNRESPONSIVE AND NO F******** GIVEN SUPPORT STAFF, EVEN FOR PAID MEMBERS / PREMIUM SUPPORTERS ! )

Thanks.

### Expected behaviour

YOU SHOULD HAVE MORE RESPECT TO YOUR PLATFORM, AND TO YOUR USERS !
(SPECIALLY THE PAID ONES)

### Actual behaviour

YOU SHOULD HAVE MORE RESPECT TO YOUR PLATFORM, AND TO YOUR USERS !
(SPECIALLY THE PAID ONES)

### Operating system

LINUX UBUNTU

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
por mucho que comprenda tu problema, este no es el sitio donde informar sobre problemas de tu cuenta.
esto es un sitio para reportar bugs del cliente, no para reportar problemas con tu cuenta.
