### ISSUE TITLE
[privacy] auto-closing current chat

### ISSUE THREAD

**Issue by klkvsk** [telegramdesktop/tdesktop#2477]
"Close window" button should also close current chat like ESC key does, so when you open it up again from tray, you have a clean window with no dialog opened.
Also it makes sense to do the same when locking.

**Comment by diazbastian** [comment]
It is similar to mobile versions of Telegram (landscape format) function. To avoid this I always use the compact mode in TDesktop.

**Comment by stek29** [comment]
> Also it makes sense to do the same when locking.

This should also fix issues like #622.

**Comment by john-preston** [comment]
@stek29 It won't — the passcode will appear in the search box then.

**Comment by stek29** [comment]
@john-preston It's better to send your passcode to Telegram than to people that may have physical access to your PC.
So it won't fix the issue in case someone is watching your screen, but at least it would not send your passcode to other users.

**Comment by stemar94** [comment]
@john-preston
Isn't that the feature of close to tray?
If one wants to have it "clean" one just had to hit ESC, and that's really all one had to do.
Now one is forced to waste a tab in ones task bar for the messaging client you know is open all the time anyway. And for example when using multiple working spaces in Linux Mint Cinnamon I really enjoyed closing Telegram and being able to be click the notification of the new income message without being dragged to the working space, where Telegram is open.
Or if one closes to tray one is forced to always select the chat again one was using.

I really don't get the benefit of this change, and at least for me it only makes things worse.

**Comment by stek29** [comment]
[Looks like this issue can be closed](https://github.com/telegramdesktop/tdesktop/issues/2541#issuecomment-254799140)
