### ISSUE TITLE
Can't add link with cyrillic domain name

### ISSUE THREAD

**Issue by sergey-tikhonenko** [telegramdesktop/tdesktop#24779]
### Steps to reproduce

1. Press Ctrl-K inside the message edit field. 
2. Enter any name and a link with the cyrillic domain name to the URL field, e.g. https://рука-кремля.рус/%d1%87%d1%82%d0%be-%d1%82%d0%b0%d0%ba%d0%be%d0%b5-%d0%bd%d0%b5%d0%be%d0%ba%d0%be%d0%bb%d0%be%d0%bd%d0%b8%d0%b0%d0%bb%d1%8c%d0%bd%d0%b0%d1%8f-%d0%bf%d0%be%d0%bb%d0%b8%d1%82%d0%b8%d0%ba%d0%b0-%d0%b7/
3. Press Add

### Expected behaviour

The link should be inserted as a message into a chat

### Actual behaviour

The validation marks the URL field as erroneous (in the red color) 

As a workaround such link might be encoded using [Punycode](https://en.wikipedia.org/wiki/Punycode) transcription. E.g. https://xn----7sbqrchg0aez4l.xn--p1acf/%d1%87%d1%82%d0%be-%d1%82%d0%b0%d0%ba%d0%be%d0%b5-%d0%bd%d0%b5%d0%be%d0%ba%d0%be%d0%bb%d0%be%d0%bd%d0%b8%d0%b0%d0%bb%d1%8c%d0%bd%d0%b0%d1%8f-%d0%bf%d0%be%d0%bb%d0%b8%d1%82%d0%b8%d0%ba%d0%b0-%d0%b7/

### Operating system

Ubuntu 20.04.4 LTS

### Version of Telegram Desktop

4.0.2

### Installation source

Snap

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6823
