### ISSUE TITLE
I'm trying to reinstall telegram desktop in Windows 7

### ISSUE THREAD

**Issue by ednja** [telegramdesktop/tdesktop#24778]
### Steps to reproduce

I'm trying to reinstall telegram desktop in Windows 7 because my windows 7 got corrupt and had to reinstall.   I can get as far as the point where I try signing in with my phone number.  It says it sent the code to my phone, but it never gets to my phone.

### Expected behaviour

I should get a code sent to my phone

### Actual behaviour

I never receive a code in my phone

### Operating system

Windows 7 64bit

### Version of Telegram Desktop

telegram-for-desktop-4-0-2.exe

### Installation source

Other (unofficial) source

**Comment by ednja** [comment]
I downloaded from Microsoft Store.  The file name is the same and still the same issue.

**Comment by ilya-fedin** [comment]
The server doesn't really send the SMS when logging from tdesktop, you need to login in mobile app first

**Comment by ednja** [comment]
The first time that I installed telegram, a few years ago, I was able to install from pc only.  I only used the cell phone to retrieve the code.






On Saturday, July 9, 2022 at 10:16:48 p.m. PDT, ilya-fedin ***@***.***> wrote: 







The server doesn't really send the SMS when logging from tdesktop, you need to login in mobile app first

**Comment by ilya-fedin** [comment]
You can't use Telegram without client installed on a phone anymore

**Comment by ednja** [comment]
Okay, I installed on phone first and now it works on my PC.  Thanks for your help.






On Saturday, July 9, 2022 at 10:52:41 p.m. PDT, ilya-fedin ***@***.***> wrote: 







You can't use Telegram without client installed on a phone anymore
