### ISSUE TITLE
[Feature Request]  move the call button somewhere else .

### ISSUE THREAD

**Issue by JeelRajodiya** [telegramdesktop/tdesktop#24775]
### Is your feature request related to a problem?

sometime instead of minimizing the window i accidently click call button because they are very close.
![telegram buttons](https://user-images.githubusercontent.com/63534268/178112289-0159cee4-5a96-4dc5-8526-14a739c1d01a.PNG)

### Describe the solution you'd like

probably swamping the search button and call button will do the trick

### Describe alternatives you've considered

alternatively you can simply ask for user's confirmation when he clicks the call button.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/24607
