### ISSUE TITLE
Group calls not working on Ubuntu 22.04 (both snap and .deb version)

### ISSUE THREAD

**Issue by tylnesh** [telegramdesktop/tdesktop#24774]
### Steps to reproduce

1. Open a group
2. Start or join a call
3. Watch it fail to establish connection...

### Expected behaviour

Connecting to a group call

### Actual behaviour

Stuck on the spinning connection

### Operating system

Ubuntu 22.04, Gnome Shell

### Version of Telegram Desktop

4.0.2

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Already fixed on dev branch for snap. It won't help .deb version though as the problem in how they build tdesktop.

**Comment by tylnesh** [comment]
Thanks, that's good enough for me, as I usually use telegram-desktop snap. I only tried out .deb package to see if it was an issue with snap, or Telegram itself.

**Comment by ilya-fedin** [comment]
It's better to use the static binary that is primary distribution method and doesn't have such bugs usually. You can download it from https://desktop.telegram.org.

**Comment by tylnesh** [comment]
Thanks, but that's quite a regression in terms of installing software. Going back to hunting for executables on random sites is something I was not looking forward to since I abandoned Windows.

**Comment by Aokromes** [comment]
> Thanks, but that's quite a regression in terms of installing software. Going back to hunting for executables on random sites is something I was not looking forward to since I abandoned Windows.

you don't need to hunt executables on ramdom sites, they are all here on releases.

**Comment by dmitry-karpik** [comment]
Hello,

Are there any updates on this issue?

Thanks.

**Comment by Aokromes** [comment]
> Hello,
> 
> Are there any updates on this issue?
> 
> Thanks.

it's fixed on 4.0.3 beta.
