### ISSUE TITLE
Telegram PC crashes when downloading

### ISSUE THREAD

**Issue by silverm6** [telegramdesktop/tdesktop#24776]
### Steps to reproduce

Start file download of file >2GB

### Expected behaviour

File downloads

### Actual behaviour

File crashes when 2gb is downloaded

### Operating system

PC

### Version of Telegram Desktop

latest 4.02

### Installation source

Static binary from official website

### Logs

```shell
Assertion Failed! "offset >= 0 && offset < _fullSize" streamed_file_downloader.cpp:111
```

**Comment by simon-zhangmuye** [comment]
I have the same error. Do you find a solution?

**Comment by simon-zhangmuye** [comment]
@john-preston Please check out this issue.

**Comment by Decimation** [comment]
This is still an issue.

**Comment by john-preston** [comment]
Is this about a video download or a file download?

**Comment by john-preston** [comment]
For video files I hope this fixes the problem: https://github.com/telegramdesktop/tdesktop/commit/88393eb77b7da19a116bc5a7a613603146c30db2

**Comment by simon-zhangmuye** [comment]
@john-preston Hey John, how to use source code in win10?

**Comment by Aokromes** [comment]
compiling yoursef. or waiting for next beta.

**Comment by Decimation** [comment]
This is an issue for me as well.

**Comment by Aokromes** [comment]
try updating to 4.0.3 beta.

**Comment by simon-zhangmuye** [comment]
@Aokromes I cannot find 4.0.3 beta. Do you mean waiting for the update?

**Comment by Decimation** [comment]
> try updating to 4.0.3 beta.

@Aokromes This resolves the crashes but downloads now appear to be in some sort of deadlock when they should be marked as complete.

![image](https://user-images.githubusercontent.com/4624891/181698655-0c35cd94-ed5c-4615-882c-486caa8ea4d3.png)

**Comment by Decimation** [comment]
> try updating to 4.0.3 beta.

@Aokromes This resolves the crashes but downloads now appear to be in some sort of deadlock when they should be marked as complete.

**Comment by simon-zhangmuye** [comment]
@john-preston I hope the next version can fix the crash and deadlock issue.

**Comment by Decimation** [comment]
> > try updating to 4.0.3 beta.
> 
> @Aokromes This resolves the crashes but downloads now appear to be in some sort of deadlock when they should be marked as complete.

I can confirm that it is an issue with Telegram never releasing the handle on the download. Forcefully closing the handles resolves the issue.

![pQsrRjyDhZ_2022-07-30_(02h15m37s)](https://user-images.githubusercontent.com/4624891/181879478-e83f87ec-25a9-4595-aa2c-bb4c5352eef9.png)

![LockHunter_7yQ9OfQXtX](https://user-images.githubusercontent.com/4624891/181879531-3824e0e7-e748-4d6b-a90d-1403c2017ac8.png)

@john-preston
