### ISSUE TITLE
Sent with silent works?

### ISSUE THREAD

**Issue by zakiloki0** [telegramdesktop/tdesktop#24777]
I ask this because i send some things to my channel with silent, and I notice that some suscribers writes me and gets online just in that moment.

This thing is working? Maybe a bug?

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by zakiloki0** [comment]
> works for me (TM)

Strange, I'm in Linux version and happens again some minutes ago.

**Comment by kawazoe** [comment]
@zakiloki0 I just tried this on Garuda Linux using system notifications and they were correctly silenced.

**Comment by john-preston** [comment]
@zakiloki0 maybe those subscribers saw the (silent) toast notification?

**Comment by zakiloki0** [comment]
> @zakiloki0 maybe those subscribers saw the (silent) toast notification?

Uhm... Maybe but too much casuality haha, as I understand it, the silent option sends content without sending any notification, is that right?

Anyway, thanks for respond :)

**Comment by john-preston** [comment]
@zakiloki0 No, it has a notification, but without sound.
