### ISSUE TITLE
Screen sharing does not initialise on first attempt

### ISSUE THREAD

**Issue by 2000thflamingo** [telegramdesktop/tdesktop#24787]
### Steps to reproduce

1. Start a video call
2. Click Screencast
3. Choose a screen to share with the other person(s)
4. Click Share Screen

### Expected behaviour

The other person(s) in the call should be able to see your selected screen.

### Actual behaviour

The screen is not shared with the other person(s). You need to go back to the Screencast menu, click Stop Share, and then try a second time. After sharing your screen for the second time, it works correctly.

### Operating system

Behaviour occurs on Windows 10 21H2 and Windows 11 22H2

### Version of Telegram Desktop

4.0.0.0

### Installation source

Microsoft Store

**Comment by artemious7** [comment]
I have the same bug. Sometimes Telegram crashes, sometimes it doesn't.
