### ISSUE TITLE
Nearby vowel sign disappear when send / publish a text with emoji

### ISSUE THREAD

**Issue by Aikatsui** [telegramdesktop/tdesktop#24785]
**Affected apps:** Telegram Desktop
Mobile apps { (android - no), (iOS - not sure) }

**Problem Description**

When user send or publish a text with an emoji then nearby vowel sign disappear (disappear after sent).
**Note: no such problem when send or publish any text without emoji**

Language: Sinhalese / Sinhala
Script name: Sinhala
Preferred keyboard: Wijesekara
Steps to enable (ubuntu): settings --> keyboard --> input sources --> + --> sinhala --> sinhala (wijesekara (m17n))

**How to reproduce**
For testing - you can copy and paste

(i) bug | (ii) original word
1. කසිවෙක් | කිසිවෙක්
2. මල | මිල (e.g. මල means flower | මිල means price)
3. දර්ඝ | දීර්ඝ
4. පළිතුර | පිළිතුර
5. පරතික්‍රියා | ප්‍රතික්‍රියා
6. සමාසහිත | සීමාසහිත
7. නති | නීති

**ශරී ලංකාව - ශ්‍රී ලංකාව (country name)

![image](https://user-images.githubusercontent.com/63988538/178576306-68df6d05-255a-4032-8171-4219f704dce2.png)
![image](https://user-images.githubusercontent.com/63988538/178576371-512da983-9484-4128-b363-e3783af3d7ad.png)
![image](https://user-images.githubusercontent.com/63988538/178576411-762ab6d1-a3dd-41a3-8303-65a88080df8b.png)

**Affected areas:** 
Conversation / Chat areas 
Group descriptions and chats 
Channel descriptions and contents
Bots etc

**Affected OS:** Linux, Windows etc

Operating system: Ubuntu 22.04 | TDesktop: 4.0.2 | Installation source: Static binary from official website / snap

**Comment by Aikatsui** [comment]
@john-preston @ilya-fedin

**Comment by ilya-fedin** [comment]
Well, I think I've seen a lot of reports about this (now all closed due to being stale), so it's a long-standing issue somewhere in unicode-to-image replacement. Given that this wan't fixed before, this has a very low priority I guess and is unlikely to be fixed (any time soon? ever?).

**Comment by Aikatsui** [comment]
> Well, I think I've seen a lot of reports about this (now all closed due to being stale), so it's a long-standing issue somewhere in unicode-to-image replacement. 

🤔

>Given that this wan't fixed before, this has a very low priority I guess and is unlikely to be fixed (any time soon? ever?).

Anyway no such problem on other chat apps

**Comment by john-preston** [comment]
It'll be fixed in the next release. Thanks for your report.
