### ISSUE TITLE
Clicking on teletype or telegra.ph articles' links opens it in the app (Windows)

### ISSUE THREAD

**Issue by elias-xenakis** [telegramdesktop/tdesktop#24788]
### Is your feature request related to a problem?

Clicking on teletype or telegra.ph articles links opens it in the browser (Windows).

### Describe the solution you'd like

As far as I know, on Mac, these articles open in the application itself. Therefore, I suggest implementing the same in the Windows application itself.

### Describe alternatives you've considered

There is such a function in unigram, but I didn’t like the application, I returned to the official application

**Comment by ilya-fedin** [comment]
#3492

**Comment by elias-xenakis** [comment]
@Aokromes  Why closed? The feature has been gone for a long time, but it is very much needed.

**Comment by ilya-fedin** [comment]
You see it's a duplicate

**Comment by ilya-fedin** [comment]
It doesn't mean there should be an open duplicate issue

**Comment by elias-xenakis** [comment]
> It doesn't mean there should be an open duplicate issue

Оk, you are right. Anyway, I don't think the problem will be solved
