### ISSUE TITLE
Crash while connecting/disconnecting USB device

### ISSUE THREAD

**Issue by zaps166** [telegramdesktop/tdesktop#2478]
### Steps to reproduce
1. Run Telegram.
2. Connect or disconnect USB mouse (or probably keyboard, too).
3. Telegram closes with X11 error.
### Expected behaviour

Don't crash.
### Actual behaviour

Telegram closes with error code 1. It is X11 error, so no backtrace.
### Configuration

**Operating system:**
Arch Linux, xorg-server 1.18.4

**Version of Telegram Desktop:**
Telegram 0.10.8
### Logs

```
$ ./Telegram
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
The program 'Telegram' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 639 error_code 10 request_code 131 minor_code 46)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
AL lib: (EE) alc_cleanup: 1 device not closed
$ echo $?
1
```

**Comment by unera** [comment]
The bug is reproducible in the latest max 2-3 telegram-release.
I think that the problem has appeared two or three weeks ago.

**Comment by lionax** [comment]
I can still reproduce this problem with Telegram Desktop 1.1.23. It also appears when my notebook webcam and microphone get disconnected. (It's kind of broken which leads to a disconnect when touching the screen...)

I'm running Manjaro (arch-based) Linux, xorg-server 1.19.3

**Comment by pavlepiramida** [comment]
I can confirm it too,running Antergos and Telegram Desktop 1.1.23,xorg-server 1.19.3-3,happens when I disconnect my usb keyboard from laptop.

**Comment by amankhoza** [comment]
@lionax @pavlepiramida Try and install libappindicator-gtk3 see if that fixes it, it worked for a similar issue #3287.

**Comment by pavlepiramida** [comment]
@amankhoza 
Nice,its not crashing anymore!

**Comment by lionax** [comment]
@amankhoza 
I can also confirm, that this works :+1:

**Comment by nicholascw** [comment]
Arch Linux
Linux 4.13.5-1-ARCH #1 SMP PREEMPT Fri Oct 6 09:58:47 CEST 2017 x86_64 GNU/Linux
GNOME Shell 3.26.1
Xorg-server 1.19.4-1 (package version showing in pacman)
(bumblebee with proprietary nVidia Driver )

**Version of Telegram Desktop:**1.1.23 alpha

Confirmed installing **libappindicator-gtk3** works!

**Comment by RAHMANINkolesi** [comment]
it is closing when you connect usb microphone while making telegram voice call. I have this issue currently(18/5/2018) with Telegram Desktop 1.2.17 on Ubuntu 18.04 ....

I did not try it with mouse... There is no relation between mouse and telegram call,
even so it could able to crash for mouse connection too...

**Comment by RAHMANINkolesi** [comment]
telegram desktop app is not closing itself when you connect or disconnect usb mouse at least in ubuntu 18.04
it is closing only when you connect usb micropone camera and it is closes itself only while you making a voice call in ubuntu 18.04

**Comment by Alex-Malkov** [comment]
Linux version 3.16.0-7-amd64 (debian-kernel@lists.debian.org) (gcc version 4.9.2 (Debian 4.9.2-10+deb8u1) ) #1 SMP Debian 3.16.59-1 (2018-10-03)
Telegram v 1.4.3

[1205/133622.737174:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to launch GPU process.
The program 'Telegram' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 85418 error_code 10 request_code 131 minor_code 46)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
