### ISSUE TITLE
Only 56 blocked users appears in settings

### ISSUE THREAD

**Issue by olesya-wo** [telegramdesktop/tdesktop#24783]
### Steps to reproduce

- Block more than 56 users
- Settings -> Privacy and security -> Blocked users

### Expected behaviour

All blocked users has to be available in this list  
If you scroll down, the new batch will load

### Actual behaviour

Only the first 56 users are visible  
If you scroll down, the new batch doesn't load

### Operating system

Windows 10, Linux Mint 20.2

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
Same issue 4.0.3 beta.

On 3.5.2, for example, I can see all blocked users. I have 146.
