### ISSUE TITLE
Can't copy monospace text

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#24784]
### Steps to reproduce

1. Go to https://t.me/dvachannel/96553
2. Try to copy monospace text by click on it
3. You can't
4. At the same time I can copy monospace text from here - https://t.me/dvachannel/96506

Telegram for iOS (8.8.3) can copy that text.

### Operating system

Windows 10

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
Even if I select all these links and press CTRL+Shift+M I can't copy it by click. And I can do it from iOS Telegram app.

**Comment by schakhboz** [comment]
This won't work
```
telegra.ph/file/a43dbaf75a225a95b95c5.jpg
telegra.ph/file/e3de3414901d56481c61b.jpg
telegra.ph/file/127bb5064449cb99aef82.jpg
```

Do it in this way
`telegra.ph/file/a43dbaf75a225a95b95c5.jpg telegra.ph/file/e3de3414901d56481c61b.jpg telegra.ph/file/127bb5064449cb99aef82.jpg`

Split links by space bar

**Comment by Neurotoxin001** [comment]
You can try to do it by yourself. Result the same.

**Comment by schakhboz** [comment]
I tried it in Telegram Desktop (Version 4.0.2). It worked

**Comment by Neurotoxin001** [comment]
Hmm, tried it again, yes, this is works:
`telegra.ph/file/a43dbaf75a225a95b95c5.jpg telegra.ph/file/e3de3414901d56481c61b.jpg telegra.ph/file/127bb5064449cb99aef82.jpg`

But on iOS it works even like this:
```
telegra.ph/file/a43dbaf75a225a95b95c5.jpg
telegra.ph/file/e3de3414901d56481c61b.jpg
telegra.ph/file/127bb5064449cb99aef82.jpg
```

**Comment by john-preston** [comment]
@Neurotoxin001 I don't copy-on-click monospace blocks, only inline monospace text parts. I don't think that multiline blocks should be copied by click, it's too much.

**Comment by Neurotoxin001** [comment]
@john-preston ok but I still can't copy monospace text even if I apply monospace markdown on these links separately. For example:
`telegra.ph/file/a43dbaf75a225a95b95c5.jpg`

`telegra.ph/file/e3de3414901d56481c61b.jpg`

`telegra.ph/file/127bb5064449cb99aef82.jpg`

When I write that post I found another "bug" — I can copy only last link:


https://user-images.githubusercontent.com/39812401/178754821-60fa84af-b63e-4509-a607-df10370018bf.mp4

**Comment by Neurotoxin001** [comment]
Update about it:
> I can copy links only if there is any words between them

When I select all text and apply to it monospace, and then remove monospace from words between links, it's copy-on-click fine.
But when I apply monospace only to links, I can't copy two frist links even with words between them.

video:
https://user-images.githubusercontent.com/39812401/178755759-447daf33-7d88-476f-9083-1a7238b410c1.mp4

**Comment by PoweredByAndrox** [comment]
I agree with it that it is stupid bug and nothing changes at all with it
Please make it copy as one line works well
