### ISSUE TITLE
System Audio Sharing is not working while connected to a Bluetooth Speaker

### ISSUE THREAD

**Issue by FeeeeK** [telegramdesktop/tdesktop#24797]
### Steps to reproduce

1. Connect your device to a Bluetooth Speaker or to a wired earphones/headset.
2. Start a call.
3. Start Screen Sharing.
4. Select a Screen or Window that produces the sound/audio you also wanted to share.
5. Tick "Share System Audio" checkbox.
6. Click "Share Screen" button.
7. Call participant/s will not be able to hear the audio from the screen/window you are sharing.

### Expected behaviour

Anyone can hear audio from my computer

### Actual behaviour

Audio on screen share doesn't work unless you disconnect from bluetooth speaker

### Operating system

Windows 11

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
try to plug speaker before you start telegram

**Comment by FeeeeK** [comment]
It didn't help.

**Comment by amaau** [comment]
Maybe same maybe related - When pc connected to bluetooth earphones all telegram audio is muted, been so for years

**Comment by Seniorsimo** [comment]
confirm, very frustrating to disconnect bluetooth headphones if you wish to share audio in a call

**Comment by DimaDDM** [comment]
Still reproducable in version 4.6

**Comment by FeeeeK** [comment]
Issue is still relevant.

**Comment by byquip** [comment]
I experienced this problem after some update this or last year.
Does not have any Bluetooth devices. Same with Android client.

**Comment by N1ckn1ght** [comment]
The issue is still relevant.
