### ISSUE TITLE
Fullscreen photo is covered by the laptop's notch

### ISSUE THREAD

**Issue by Thoufak** [telegramdesktop/tdesktop#24795]
### Steps to reproduce

1. Have a laptop with a notch (e.g. MacBook Pro 14″)
2. Open a photo in the built-in media viewer, so that it takes up the whole screen height.

### Expected behaviour

The photo appears under the notch.

### Actual behaviour

The photo is covered by the notch.

<img width="984" alt="image" src="https://user-images.githubusercontent.com/40132582/179207975-f13b3f1e-02e9-4445-9a3c-d4f2f5230045.png">

### Operating system

macOS 12.3; M1 Pro chip

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by Charoenchai2518** [comment]
**__**

**Comment by WantD998** [comment]
Have the same issue

**Comment by shelbyKiraM** [comment]
I personally love that it fills the entire display

for instance, you can watch 3:2 video using almost the entire screen like this (notch doesn't render as black in screenshots so it's the top part): <img width="1512" alt="image" src="https://user-images.githubusercontent.com/202692/202053555-6ca73e9a-8759-4d60-9e71-c089fc62707a.png">

But I do think there should be an option to toggle safe area on and off, like mentioned in my issue in [IINA](https://github.com/iina/iina/issues/4083), where that app renders black bars above the top of display like this:<img width="1512" alt="image" src="https://user-images.githubusercontent.com/202692/202053733-9e46e1c4-e2ce-48a9-ac00-1dc3680efbf8.png">

*Both is good* (heh), there's use cases for either option.

Found the below via https://appleinsider.com/articles/21/10/19/apps-can-use-full-screen-area-around-new-macbook-pros-camera-notch:

According to newly published HIG [documents](https://developer.apple.com/documentation/bundleresources/information_property_list/nsprefersdisplaysafeareacompatibilitymode), MacBooks that include a camera housing in the screen bezel provide a special operating mode that prevents full screen apps from placing content under the notch. When active, compatibility mode automatically changes the active area of the system's display to avoid the housing cutout, ensuring that content is not obscured.

Developers [can opt](https://developer.apple.com/design/human-interface-guidelines/macos/app-architecture/fullscreen-mode/) for a custom full-screen experience, but they will need to define safe areas in their code using new tools. For example, app makers can specify a large safe area with an inset at the top of the screen that leaves the entirety of the app unobscured. Alternatively, new properties can be set to identify rectangular portions of screen to the right and left of the notch, areas that will be earmarked for active content.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/8cc90c3373811549c4bb50f8d1239c7d00f5f3f0
