### ISSUE TITLE
Fix client window auto-maximizing

### ISSUE THREAD

**Issue by retueZe** [telegramdesktop/tdesktop#24794]
### Steps to reproduce

1. Start Telegram client in full-screen
2. Start watching any video
3. Minimize the video to a widget
4. Hide the client window
5. Maximize and minimize the widget

### Expected behaviour

I expected that maximizing-minimizing of video widget wouldn't cause some changes of client window state.

### Actual behaviour

After the last step the previously hidden client window shows and prevents me. Every time I maximize-minimize my widget, and I do it frequently, the client pops up, and I have to hide it again and again.

### Operating system

Windows 10 x64

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> 3\. Minimize the video to a widget

You apparently mean switching to PiP mode here?

> 5\. Maximize and minimize the widget

Here you mean switching out of PiP mode and back to PiP mode?

**Comment by retueZe** [comment]
Yes, I didn't know how it's called

**Comment by ilya-fedin** [comment]
And one more question: title says "client window auto-maximizing", does it actually maximize (i.e. goes fullscreen except of taskbar) or just restores?

**Comment by retueZe** [comment]
It was hidden in my taskbar, and then it went to full-screen. I was in full-screen, I don't know, but it should work the same way not in full screen.

**Comment by retueZe** [comment]
According to WinAPI docs, it goes from minimized (before step 5) to maximized (after step 5). And I just tested this in restored window. It works the same way, but after step 5 it obviously gets restored, not maximized.
