### ISSUE TITLE
[Feature Request] Fix client window auto-maximizing

### ISSUE THREAD

**Issue by retueZe** [telegramdesktop/tdesktop#24792]
### Is your feature request related to a problem?

I'm watchng a video in minimized widget with minimized client window, and when I maximize and minimize the widget again, the client window maximizes for no reason. Usually, I maximize-minimize the widget frequently, and this option prevents me.

### Describe the solution you'd like

Disable this unneccessary maximizing.

### Describe alternatives you've considered

If it's a design feature, add an option to experemental settings to switch it off.

**Comment by ilya-fedin** [comment]
What are you talking about? Is this a feature request or a bug report? If the second, it makes really hard to help you as you have chosen the wrong issue template that doesn't asks the required information.

**Comment by retueZe** [comment]
I moved this issue to #24794
