### ISSUE TITLE
Why the command is not working ?

### ISSUE THREAD

**Issue by sujeethmoolya** [telegramdesktop/tdesktop#24791]
I am not able to install the telegram desktop using command "flatpak install flathub org.telegram.desktop" Error says "No Remote refs found similar to 'flathub' ".

**Comment by ilya-fedin** [comment]
Apparently you need to read flatpak documentation or ask in some flatpak support channel. If you don't know, I recommend to install the static binary from https://desktop.telegram.org, that's the recommended installation method.
