### ISSUE TITLE
telegram: Memory/CPU Leak

### ISSUE THREAD

**Issue by Meghthedev** [telegramdesktop/tdesktop#24803]
### Steps to reproduce

1. On Debian Bookworm/Sid (testing), install the telegram-desktop package from the official repos
2. open telegram and log in
3. Eventually within 10 minutes it consumes 100% of my cpu, also around 1gb of ram at one moment

### Expected behaviour

The Telegram-desktop app should open, and should not use 100% of my cpu, and its not a bottleneck issue, as my system specs are good enough to run telegram , they are core i7 2600, 4 cores, 8 threads, and 12gbs of ram, that should not be completely capped out by telegram

### Actual behaviour

after opening telegram, it repeatedly happens that my whole system lags out, when checking system monitor/top/any other kind of program it shows telegram consuming 100% of my cpu and 500-1gb of ram

![photo1658249470](https://user-images.githubusercontent.com/96943033/179809301-ad7d0d9e-0176-4f9b-a306-01d7be9e677e.jpeg)

### Operating system

Debian GNU/Linux bookworm/sid x86_64 KDE

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by OlehPaduchak** [comment]
the same here on Archlinux with KDE plasma and telegram desktop 4.0.2. It is installed from official arch repo

**Comment by ilya-fedin** [comment]
Can you check the official website build?

**Comment by Meghthedev** [comment]
Using the official package from telegrams website fixed the issue for me
