### ISSUE TITLE
Some strange bug: strange window movement behaviour

### ISSUE THREAD

**Issue by Intrigger** [telegramdesktop/tdesktop#24805]
### Steps to reproduce

Just watch the video about this bug: https://youtu.be/8LUjYZtN99Q

### Expected behaviour

Normal resizing

### Actual behaviour

Ok, some strange movement when resizing window, watch the video: https://youtu.be/8LUjYZtN99Q

### Operating system

KDE Ubuntu

### Version of Telegram Desktop

3.6.1 + ds-2build1 released 16.03.20..

### Installation source

Snap

**Comment by ilya-fedin** [comment]
It's https://bugreports.qt.io/browse/QTBUG-102488
