### ISSUE TITLE
couldn't compile, Qt vulkan unresolved externals

### ISSUE THREAD

**Issue by tigros** [telegramdesktop/tdesktop#24806]
### Steps to reproduce

follow Windows compile instructions

### Expected behaviour

compile, no errors

### Actual behaviour

unresolved externals for codegen_emoji and telegram projects: QWindowsVulkanInstance etc

Work around: add ....\Libraries\win64\Qt-5.15.4\lib\Qt5VulkanSupport.lib for release, Qt5VulkanSupportd.lib for debug in both project's Linker/Input

### Operating system

windows 10

### Version of Telegram Desktop

4.0.2.0

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Qt has autodetection system, so you have to either remove Vulkan from your system or add -no-feature-vulkan to Qt builds
