### ISSUE TITLE
Buttons of min, close an max change after each reboot

### ISSUE THREAD

**Issue by zakiloki0** [telegramdesktop/tdesktop#24814]
I don't know why this happens but I have the close, minimize and maximize buttons configured on the left but every time the computer is turned on it changes places and it only happens with Telegram.

With each ignition it turns to one side or the other. Any idea why?

Telegram Desktop Linux version on KDE.

**Comment by ilya-fedin** [comment]
Apparently KDE starts Telegram before X settings daemon is launched?

**Comment by zakiloki0** [comment]
> Apparently KDE starts Telegram before X settings daemon is launched?

Hey!

Well, I have no idea, I have to investigate, I remember that something happened to me some time ago with the native title bar and you had told me to install a package, but I think this is different. I'll keep looking to see what it could be.

**Comment by zakiloki0** [comment]
> Apparently KDE starts Telegram before X settings daemon is launched?

Thanks ilya, apparently it was this, I solved the problem with a script that makes Telegram start a few seconds after the desktop and it works.

I think something similar should be added to the native options of the Telegram app so as not to resort to scripts.

**Comment by ilya-fedin** [comment]
> I think something similar should be added to the native options of the Telegram app so as not to resort to scripts.

No. I don't think this should be done, it's a dirty hack and you can't know when it would be started exactly. That hardly depends on hardware configuration. KDE should fix startup order instead.

**Comment by zakiloki0** [comment]
I come back here to say that it has happened again, so it was not solved as I thought. Just in case anyone else has this and knows how to fix it.
