### ISSUE TITLE
Invalid display of 'Ə' letter in channel messages

### ISSUE THREAD

**Issue by rahimlis** [telegramdesktop/tdesktop#24811]
### Steps to reproduce

Just type the letter 'Ə' in the channel and look at how it is displayed. 
[Ə letter wiki](https://en.wikipedia.org/wiki/%C6%8F)

### Expected behaviour

Should display the letter same way as others

### Actual behaviour

Displays letter Ə incorrectly
<img width="391" alt="image" src="https://user-images.githubusercontent.com/13980807/180142750-c7b14e12-5039-4db4-aafe-79a343c6c1a9.png">
<img width="255" alt="image" src="https://user-images.githubusercontent.com/13980807/180142872-bf99ed51-ccc2-4152-bb08-7164b876be3b.png">

### Operating system

MacOS Monterey 12.4

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
same bug https://github.com/telegramdesktop/tdesktop/issues/8140 ?

**Comment by ilya-fedin** [comment]
maybe I'm blind, but I don't see anything wrong on the screenshot
