### ISSUE TITLE
Unwanted character e

### ISSUE THREAD

**Issue by ShinjiIkari256** [telegramdesktop/tdesktop#24812]
### Steps to reproduce

Sometimes, when deleting or pasting text, the letter e appears in the reported field.

### Expected behaviour

I would like to just write without interference

### Actual behaviour

well, an unwanted character appears, interfering with editing.
It is impossible to get rid of it by deleting or restarting the application, only sending a message.

### Operating system

Ubuntu 22.04, X11

### Version of Telegram Desktop

4.0.2

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Maybe your keyboard is broken? I can't reproduce

**Comment by ShinjiIkari256** [comment]
hmm, maybe, of course. But I tried to reproduce this error in other applications and also nothing. But it occurs consistently 2-4 times a working day.

Although I will still try to reproduce the error on another computer with the same OS version. But it does not occur so constantly that I would be sure that I could prove its absence by this.

I hope someone with the same error will come and prove it.

**Comment by kirizdev** [comment]
I encountered this problem when I was using Gnome. It's a built-in feature for writing emojis, you can remove it: `gsettings set org.freedesktop.ibus.panel.emoji hotkey "[]"`. Telegram Desktop has nothing to do with it.
