### ISSUE TITLE
There is no default name when save files 

### ISSUE THREAD

**Issue by nikzad-avasam** [telegramdesktop/tdesktop#24818]
When I try to save a file has no name by default ! 
i use telegram in my linux :  
this is my telegram info : 
![Screenshot_2022-07-24_20-10-36](https://user-images.githubusercontent.com/13311003/180654988-b8b9a510-8cdd-4727-89c0-195b5429826c.png)
and when i want to save files : 
![Screenshot_2022-07-24_20-11-19](https://user-images.githubusercontent.com/13311003/180655051-469c798d-6575-46d7-8b9f-3b229d1d6b30.png)

my system : 
Arch linux + xfce4 desktop

**Comment by ilya-fedin** [comment]
#24491
