### ISSUE TITLE
Incorrect members count of channels

### ISSUE THREAD

**Issue by bdmbdsm** [telegramdesktop/tdesktop#2482]
![screenshot - 09302016 - 04 41 35 pm](https://cloud.githubusercontent.com/assets/7142689/18993667/048cf5c8-872d-11e6-9f72-aca61240a6b6.png)

### Steps to reproduce
1. Start Telegram
2. Click RMB on any channel
3. Choose "View channel info"

### Expected behaviour
Members count should be equal 1091 (may change)

### Actual behaviour
Members count is equal to 1. After opening channel chat, channel info displays
right count of members.

### Configuration
Debian Linux 8
Kernel version 3.16.0-4-amd64

**Version of Telegram Desktop:**
0.10.8

**Logs**
[log_16_45.txt](https://github.com/telegramdesktop/tdesktop/files/503110/log_16_45.txt)
[mtp_16_45.txt](https://github.com/telegramdesktop/tdesktop/files/503109/mtp_16_45.txt)
[tcp_16_45.txt](https://github.com/telegramdesktop/tdesktop/files/503108/tcp_16_45.txt)

**Comment by stek29** [comment]
Wow, what a weird bug.
It took me a while to understand description, so here's the screencast
![output](https://cloud.githubusercontent.com/assets/11808223/19165351/15e7db38-8c0c-11e6-9a34-55523bb60c55.gif)

**Comment by john-preston** [comment]
Should be done in 0.10.13.alpha.
