### ISSUE TITLE
Auto-lock doesn't work

### ISSUE THREAD

**Issue by Serproger** [telegramdesktop/tdesktop#24827]
### Steps to reproduce

1. Set option "Auto lock if away for..." to some value, for example, 1min.
2. Close app's window with system close button at top right corner.
3. Wait for a while (longer than 1min).
4. Reopen app by clicking icon in system tray.

### Expected behaviour

User should enter passcode to continue using the app.

### Actual behaviour

Main window of app was opened without any requests of passcode.

### Operating system

Windows 10 Pro 21H1 build 19043.1766

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by Serproger** [comment]
@john-preston  User interaction doesn't make any difference here. Even without interaction Telegram is not getting locked.

**Comment by Serproger** [comment]
@john-preston Can i provide some logs for further investigation?

**Comment by john-preston** [comment]
@Serproger Well, maybe someone else can confirm this? I'll ask some other users. I still think that the test wasn't clear enough and something was happening (like, video was playing in the app in that time or the mouse was moved or smth else). Otherwise I could add some debug logs for the next release for the code that should perform auto-lock, but it did work fine for many years for a huge amount of computers / users.

**Comment by Serproger** [comment]
@john-preston I'v very keen on understanding what exactly prevents Telegram from locking because this feature is crucial for me. No chat was opened during the test and I was away from computer.

**Comment by emiryasm** [comment]
> @Serproger Then I couldn't reproduce. I made a local passcode for tdesktop 4.0.2, enabled Auto-Lock for 1 minute, closed the window (the tray icon was enabled, so the app was still working) and didn't touch mouse and keyboard for about 1.5 minutes, then clicked on the tray icon and the app was locked with the passcode 🤷🏻

hi! I had the same problem, I installed version 4.0.2 today, followed same steps, but app wasn't locked after a minute

I had to close the app enterily (from the tray icon) and then, when I reopened the app, the auto-lock was working!

Maybe this works for you too @Serproger

**Comment by Serproger** [comment]
> Maybe this works for you too @Serproger

Of course the app requests passcode after reopening. But such behaviour is hardly acceptable, it's too easy just to forget to close minimized app when leaving a computer.

@john-preston please note, there are already two of us :)

**Comment by emiryasm** [comment]
@Serproger I closed the app, reopened it, unlocked the app, waited a minute and then it auto locked
Having said that now it's not working again :/ ... There must be something not working properly

**Comment by Serproger** [comment]
@john-preston Could you please clarify when above-mentioned changes to logging will be released?
