### ISSUE TITLE
Telegram crashed while trying to open any menu item with 2 or more opened accounts

### ISSUE THREAD

**Issue by f1reSong** [telegramdesktop/tdesktop#24824]
### Steps to reproduce

Try to add 2 accounts to telegram desktop and click to the arrow for opening account list and select any item in menu, telegram will crashed

### Expected behaviour

All menu items needed to be openable

### Actual behaviour

Application crashed

### Operating system

Ubuntu 22.04 LTS

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Enable installation of beta versions in the settings, reproduce the crash, copy the crash report tag (not the user tag!), send the crash report and post the tag here.

**Comment by john-preston** [comment]
@f1reSong Version 4.0.2 is the latest stable BTW.
