### ISSUE TITLE
[Question] How Telegram desktop reads font family

### ISSUE THREAD

**Issue by foxhoundsk** [telegramdesktop/tdesktop#24838]
I'm on ArchLinux with Plasma as DE, I don't have Chinese font installed on my machine by the time I install TG, and Chinese fonts rendered as unreadable square, which is as expected. Then I got Chinese font (`noto-fonts-cjk`) installed (w/ pacman), and TG automatically renders Chinese properly.

Later, I manually installed another font into `/usr/local/share/fonts/`, this time I'm struggling with changing TG to use the font I just installed.

For browsers, it can be set within the browser settings. But on TG, AFAIK, there doesn't exist such setting for one to specify the font.

This brings me a question, how TG found the Chinese font I installed for the first time (which is mentioned above)? Does TG come with, for example, a config file that allows user to manually specify the font?

Thanks!

My current TG version: 4.0.2

**Comment by ilya-fedin** [comment]
tdesktop uses open sans as the preferred font, if it doesn't have a glyph, Qt fallback to some other in your system using its internal algorithm.
