### ISSUE TITLE
A proposal to improve Telegram from being abused by bots

### ISSUE THREAD

**Issue by machinsoft** [telegramdesktop/tdesktop#24837]
### Is your feature request related to a problem?

English, (bad translation)
This idea is for improvement.
People abuse bots that would banish other people's channels and chats, as well as promote their own in the top search.
Scheme working has been tested many times by me personally, I have banned more than 10 channels

### Describe the solution you'd like

I propose to improve the functionality

### Describe alternatives you've considered

I have a really working idea how to solve this, a million dollar idea so to speak.
1. You need to remove the count of subscribers on the channel if there are deleted accounts, count only accounts that are not deleted, the rest are not counted as subscribers.
2. You need to add a power system to each account, for example:
if a user subscribes to a channel or chat for the first time, he transfers 10 power to the channel, this power will be needed to promote the channel in the search.
Now, if a user has subscribed to another channel and he already has 2 channels, he transfers 9 strength to the second channel.

The scheme is such that the more channels a user has in his account, the more each time the power decreases, in the end he transfers 0 power to the channel.

How it will work.
Bots subscribe to many channels, 10 channels will receive power from them, the rest will receive only subscribers and then for a while, I will describe why a little lower.
Now the most interesting thing is, if the bot has become a deleted account, the subscriber will be removed from the channel and the strength will decrease.

If a channel has 200,000 subscribers and little power, and another channel has 5,000 subscribers and a lot of power, it will be higher in the search.
Usually those who spin bots, their bots become deleted accounts within a couple of days, I answer that this scheme will save telegrams from bot waters.

3. It is required to turn off the shadowban, people abuse bots to ban other people's channels of competitors and are even willing to pay money for it.

------------------------------------------------ RUS --------------------------------------------------------

### Связана ли ваша заявка на функцию с проблемой?

Эта идея направлена на улучшение.
Люди злоупотребляют ботами что бы банить чужие каналы и чаты, а так же продвигать свои в топ поиска.
Схема рабочая была проверена неоднократно лично мной, я забанил больше 10 каналов

### Опишите решение, которое вы хотели бы получить

Я предлагаю улучшить функционал

### Опишите альтернативы, которые вы рассматривали

У меня есть реально рабочая идея как это решить, идея на миллион так сказать.
1. Нужно убрать подсчет подписчиков на канале если там удаленные аккаунты, считать только аккаунты которые не удаленные, остальные не считаем за подписчиков.
2. Нужно добавить систему силы в каждый аккаунт, например:
если пользователь подписался первый раз на канал или чат он передает 10 силы на канал, эта сила понадобиться для продвижение канала в поиске.
Теперь, если пользователь подписался на другой канал и у него уже 2 канала, на второй канал он передает 9 силы.

Схема такая, чем больше у пользователя каналов в аккаунте, тем с каждым разом сила уменьшается, в конечном итоге он передает 0 силы на канал.

Как это будет работать.
Боты подписываются на многие каналы, 10 каналов получат от них силу, остальные получат только подписчиков и то на время, почему чуть ниже опишу.
Теперь самое интересно, если бот стал удаленным аккаунтом, в канале убираться подписчик и уменьшается сила.

Если на канале 200 000 подписчиков и мало силы, а у другого канала 5000 подписчиков и много силы, он будет выше в поиске.
Обычно те кто крутят ботов их боты становятся удаленными аккаунтами в течении пару дней, я отвечаю что эта схема избавит телеграм от ботоводов.

3. Требуется отключить теневой бан, люди злоупотребляют ботами что бы банить чужие каналы конкурентов и даже готовы платить за это деньги.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
