### ISSUE TITLE
Mouse-wheel scrolling broken on wlroots compositors

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#24835]
Scrolling with a mouse wheel seem to have be broken on sway since this was merged upstream:

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3461

However, other Qt applications like KeePassXC continue to scroll fine, which leads me to think the issue might be here (I can cross-report to wlroots if you think that would help).

Buildilng sway with a wlroots prior to that protocol being implemented and running Telegram works fine.

**Comment by ilya-fedin** [comment]
I have no idea what could be problem on Telegram side, scrolling even is gotten using Qt high-level API: https://doc.qt.io/qt-5/qwidget.html#wheelEvent

**Comment by WhyNotHugo** [comment]
> depends on Telegram widget in question

Scrolling doesn't work anywhere, nor the contact list nor message details.

> this report has too few details and the template is ignored

There's no template showing up for new issues:

![image](https://user-images.githubusercontent.com/730811/181708397-1857552a-1e4e-4312-8d58-31ab23fb9261.png)

I do recall seeing one in the past, maybe GH broke something?

> i believe it's either a compositor or Qt bug most likely.
 
I'll cross-report to both of these. I can't repro this on other Qt apps though, so I wanted to be sure that Telegram isn't doing anything unusual for scrolling.

**Comment by ilya-fedin** [comment]
> There's no template showing up for new issues:

![изображение](https://user-images.githubusercontent.com/17829319/181710477-ce91fa23-f6ca-42df-bbdb-9a889a47ebba.png)
That's what opens when you click on the new issue button on the top of issues

> I'll cross-report to both of these. I can't repro this on other Qt apps though, so I wanted to be sure that Telegram isn't doing anything unusual for scrolling.

I can't say there's nothing unusual for sure, it may be some unusual combination of API usage that is not enough tested by Qt, but if it doesn't work only with concrete compositor, that's too low-level to be a bug in Telegram code.

**Comment by WhyNotHugo** [comment]
>  That's what opens when you click on the new issue button on the top of issues

Huh, apparently if you are not logged in and click on "New issue", the, after the login flow you are not presented with the above template choice. It is only shown if you're logged in BEFORE trying clicking the "New issue" button.

I'll try to work around this in future somehow.

> if it doesn't work only with concrete compositor, that's too low-level to be a bug in Telegram code.

I haven't tried any other compositor. I'm not aware of any other compositor that supports high-resolution scroll wheel yet.

**Comment by ilya-fedin** [comment]
> Huh, apparently if you are not logged in and click on "New issue", the, after the login flow you are not presented with the above template choice. It is only shown if you're logged in BEFORE trying clicking the "New issue" button.

Nice to know, I was always thinking how people don't see the template choice

> I haven't tried any other compositor. I'm not aware of any other compositor that supports high-resolution scroll wheel yet.

Qt doesn't support it and doesn't reflect this in public API in any way, so Qt applications shouldn't see any difference to fail in their code

**Comment by WhyNotHugo** [comment]
Continuing discussion on the compositor side, seems to be an issue with mpv as well.
