### ISSUE TITLE
[question] where to find cached images ?

### ISSUE THREAD

**Issue by bardiarastin** [telegramdesktop/tdesktop#2484]
when we open an image next time that we launch telegram it does not download it again . so the images are stored in a directory . where is that directory ? (saving images one by one takes too much time)
**Version of Telegram Desktop:**
latest
os : debian

**Comment by Kondra007** [comment]
They're stored in unreadable form

**Comment by bardiarastin** [comment]
but in android devices they are stored in telegram/images . is it not better for desktop version to be the same ?

**Comment by Zenexer** [comment]
I believe they're encrypted for security.

**Comment by bardiarastin** [comment]
at least there should be a save button for more quickly saving .

**Comment by Zenexer** [comment]
For the time being, if you happen to know Lua, you could use that to download recent images: https://github.com/vysheng/tg/blob/master/README-LUA  It'd have to load the history from the servers, though, which takes time.  If you go that route, I recommend rate limiting it on your end so you don't risk hard rate limiting by the servers.

**Comment by belegnar** [comment]
`~/.local/share/TelegramDesktop`
