### ISSUE TITLE
Telegram Desktop memory leak

### ISSUE THREAD

**Issue by jelly8173** [telegramdesktop/tdesktop#24849]
### Steps to reproduce

1. Use Latest stable Telegram Desktop
2. Join group with live stream served through rtmps
3. Stay for some time, notice memory use

### Expected behaviour

Telegram Desktop memory consumption should stay in reasonable limits

### Actual behaviour

Telegram Desktop constantly consumes memory, here is screenshot:

![process manager screenshot](https://files.catbox.moe/nzgps4.png)

### Operating system

Windows 10 x64 21H2 19044.1826

### Version of Telegram Desktop

4.0.2 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> * Join group with live stream served through rtmps
> 
> * Stay for some time, notice memory use

That sounds like just big consumption rather than a memory leak. And I guess you can't stay in 'reasonable limits' if the source is high quality (you should store the source pixels somewhere)

**Comment by jelly8173** [comment]
you sound like an expert here but cant distinguish big consumption with a memory leak

fyi -- memory leak occures when someone forget to clear used memory and it grows over time

or you want to say that 11gb is just for storing rendered frame? btw bitrate is 3Mbit/s

**Comment by ilya-fedin** [comment]
> memory leak occures when someone forget to clear used memory and it grows over time

You haven't mentioned that it grows over time. You said 'constantly consumes memory' and I've read this as "constantly consumes definite but big amount of memory".

**Comment by ilya-fedin** [comment]
> or you want to say that 11gb is just for storing rendered frame?

Well, there are video stickers that consume such amount of memory (causing OOM on low-profile systems), so who knows which parameters your stream has.

**Comment by jelly8173** [comment]
yeah, of couse, thats user problem lol

**Comment by ilya-fedin** [comment]
Well, the choice in this situation is bool: consume the memory or don't play the content :man_shrugging:

**Comment by jelly8173** [comment]
so you said this with such a big certainty that i started to think that you already found a solution and that initially stated problem is not a problem at all

**Comment by ilya-fedin** [comment]
So does it grow over time or is it constant?

**Comment by jelly8173** [comment]
i thought first it is neccessary to locate the leaking component

**Comment by jelly8173** [comment]
> So does it grow over time or is it constant?

dont play dumb with me, i already said that it grows over time beyond usual limits, and only when playing livestream

**Comment by ilya-fedin** [comment]
> i already said that it grows over time beyond usual limits

You said it's constant in your issue. Then I clarified how I read and you haven't confirmed what exactly you meant (until now, thanks).

**Comment by jelly8173** [comment]
i will make control measurement for 1h, here is current consumption:
private: 2,500,616K
working: 2,484,612K

**Comment by jelly8173** [comment]
after 13 minutes:

priate: +400M
working: +400M

![13m later](https://files.catbox.moe/zdebf1.png)

**Comment by jelly8173** [comment]
after 30 minutes:
private/working + ~1G

![after 30 mins](https://files.catbox.moe/zntsye.png)

**Comment by jelly8173** [comment]
1h: now at this point i closed translation window

still have +2G of private bytes more than hour ago, working set returned to normal

dont look at the rise in the middle of timegraph, its not related to telegram

![](https://files.catbox.moe/km8dz1.png)

**Comment by john-preston** [comment]
@jelly8173 Thanks for your report! Found at least one memory leaks in tgcalls ffmpeg. I hope this will be fixed in the next version.

**Comment by jelly8173** [comment]
Tested on x64 linux

Memory consumption during live-stream significally reduced. Delta for 30 minutes about 40MB
