### ISSUE TITLE
WebApps PC version not working

### ISSUE THREAD

**Issue by temirovgroup** [telegramdesktop/tdesktop#24840]
### Steps to reproduce

I attach 2 videos, everything works for the bot developer, but don't works me. (Win 10 x64), the latest version of telegram

### Expected behaviour

Video:
https://disk.yandex.ru/i/J1re7oKdJO5zlA

### Actual behaviour
scroll bar is old, animation and styles don't work
Video:
https://disk.yandex.ru/i/vD6DU14_3cKnJg

### Operating system

Windows 10 x64

### Version of Telegram Desktop

4.0.2 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Bot developer uses Win11's webview while you're using the webview engine embedded in Win10
