### ISSUE TITLE
Suggest popular stickers by emoji option is not working

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#24841]
### Steps to reproduce

1. Disable "Suggest popular stickers by emoji"
2. Click on emojis to send them
3. It's still suggest stickers

![Y5tMv2oJw6](https://user-images.githubusercontent.com/39812401/181876242-ef79a826-ebae-416f-b904-85152213189c.png)

![image](https://user-images.githubusercontent.com/39812401/181876248-208a772f-974a-48c8-8f63-154a7027f635.png)

### Operating system

Windows 10

### Version of Telegram Desktop

4.0.3 beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
It suggests stickers from your packs anyway. It suggests stickers from popular packs according to the setting. This is intended behaviour.

**Comment by Neurotoxin001** [comment]
Telegram for iOS allow to disable suggests even for my packs:
![image](https://user-images.githubusercontent.com/39812401/183159693-2df96881-df2e-4aaa-a366-9ff524ab716b.png)
