### ISSUE TITLE
Reaction notification keeps coming back

### ISSUE THREAD

**Issue by chrisan** [telegramdesktop/tdesktop#24844]
### Steps to reproduce

I have done a reinstall of telegram and confirmed there is no "Telegram Desktop" folder in C:\Users\Chris\AppData\Roaming prior to reinstalling and the problem persists.

I have a reaction "notification" marker in my channel list view.  When I go into that channel there is no indicator for me to click that normally takes you up to the message that was reacted to.  I go back to the channel list and the notification is gone.

When I restart telegram, the notification is back (no new messages have been made to the channel, its a channel of friends and I checked all their online statuses making sure no one was awake yet)

When I launch telegram on iOS there is no notification either.

I had a friend join a new group, I spammed a bunch of messages and asked him to  react to the first one then I closed telegram

After opening telegram I see this
![1](https://user-images.githubusercontent.com/3704774/181918257-a736598a-f089-464b-aa0d-eef23a41a595.jpg)

I click into test channel and see notification indicator for me to be scrolled to message
![2](https://user-images.githubusercontent.com/3704774/181918259-6b03a9b6-4e4f-45aa-98dc-a8e56729755b.jpg)

Click that and go see the reaction
![3](https://user-images.githubusercontent.com/3704774/181918258-b0b37cb0-a1ac-4cd0-a28d-0b130e99b692.jpg)

Next I go to the non-blurred channel that has a notification next to it but I DONT see one in the actual channel for me to scroll up to
![4](https://user-images.githubusercontent.com/3704774/181918256-e6f3b2c7-31e5-4cc0-bb98-49a40052f564.jpg)

However when I go back to the list view, the notification is removed
![5](https://user-images.githubusercontent.com/3704774/181918255-20b1e756-a999-44c2-a20a-a43cae4ca9c5.jpg)

I close and restart telegram and the test channel notification is gone, but the non blurred channel is still back again
![6](https://user-images.githubusercontent.com/3704774/181918253-fa5b485f-e016-4ffa-b685-71987a0e7b97.jpg)

### Expected behaviour

These notifications should either 

- not display (like they don't in iOS)
- give a marker to allow me to scroll to whatever message it was so it gets "read" or "seen"

### Actual behaviour

notifications keep coming back

### Operating system

Windows 10 x64

### Version of Telegram Desktop

4.0.2 x64 

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@chrisan It looks like server tells that there is one (when loading chat list), then returns nothing (when loading the real new reactions list). I'll have to ask for debug logs in private, you can write me at t.me/preston and I'll provide the details.

**Comment by chrisan** [comment]
Thx for your help, server side fix working!
