### ISSUE TITLE
[Feature Request] Filter out messages from blocked users

### ISSUE THREAD

**Issue by github12101** [telegramdesktop/tdesktop#24854]
### Is your feature request related to a problem?

Problem:
If one decide to hide messages from one person, one can use Block function.
This will disable personal messages with that person.

However, all groups, channel comment chats are not affected. Everything is as normal and you can have conversations with blocked person like nothing happened.

### Describe the solution you'd like

Extend Block functionality so it hides all messages from blocked person in group and channel chats.

### Describe alternatives you've considered

There is no alternative. Currently, this feature is missing. Blocking person means personal messages don't work, nothing more. Group chats are working as usual and you can have conversation with blocked person all day.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
