### ISSUE TITLE
[Feature Request] Auto detect and apply monitor's scale setting

### ISSUE THREAD

**Issue by spyhunter88** [telegramdesktop/tdesktop#24852]
### Is your feature request related to a problem?

OS: Windows Pro 11 22622.440.
Version: 4.0.2 x64.

Describe: I use 2 monitors with different scale, one is 3200x2000 and use 175%, the other is 1920x1080 and use 100%. When I drag Telegram app between desktop, it keeps the same scale and it's not convenient to use Telegram in both monitors.

### Describe the solution you'd like

Telegram desktop app should detect current scale and auto apply to this when I drag it via monitor.

### Describe alternatives you've considered

Or at least it can set the scale for each screen, but I don't like it much, because I usually bring only laptop.

**Comment by ilya-fedin** [comment]
#1121
