### ISSUE TITLE
High CPU usage when built against ffmpeg 5.x

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#24855]
### Steps to reproduce

1. Build Telegram Desktop against packaged ffmpeg 5.x (5.0 or 5.1, doesn't matter).
2. Run built app.
3. Join supergroup/channel with a lot of video stickers/avatars.
4. Check CPU usage in top/htop.

### Expected behaviour

Standard CPU usage.

### Actual behaviour

100% CPU usage on all CPU cores. The official binary is not affected yet, but it will after upgrading from ffmpeg 4.4 to 5.x.

Downstream bug report with some logs: https://bugzilla.rpmfusion.org/show_bug.cgi?id=6273

### Operating system

Fedora 36

### Version of Telegram Desktop

4.0.2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
ffmpeg 5 is not supported yet. Please switch to ffmpeg 4 or fix ffmpeg 5 on your own.

**Comment by xvitaly** [comment]
@Aokromes Why did you close this issue? The official package will be affected too after upgrading from ffmpeg 4.4 to 5.x. It should be opened for tracking purposes.

**Comment by ilya-fedin** [comment]
It will be upgraded to ffmpeg 5 only after precise testing and fixing any obvious bugs. Until then, this is an unsupported configuration.

**Comment by xvitaly** [comment]
> Please switch to ffmpeg 4

Impossible. Most distributions already moved to 5.1. 4.x branch will reach EOL very soon.

**Comment by ilya-fedin** [comment]
Well, if you need it, implement it.

**Comment by xvitaly** [comment]
@ilya-fedin Please stop being so rude.

**Comment by ilya-fedin** [comment]
You can't requisite something on GitHub and then saying someone is rude just because one doesn't want to implement something you want. People implement what they want. you want ffmpeg 5? Go ahead. You can't force anyone else to do that work _you're_ interested in.

**Comment by xvitaly** [comment]
@ilya-fedin Flatpak runtime 22.08 will have ffmpeg 5. Two weeks left.

**Comment by ilya-fedin** [comment]
It won't be used until preston would like to migrate to ffmpeg 5

**Comment by john-preston** [comment]
@xvitaly BTW did you report it to ffmpeg bug tracker?

Looks like an ffmpeg regression when the same code works fine with ffmpeg 4.4 and works bad with ffmpeg 5.x 🙄

**Comment by GeorgesStavracas** [comment]
@ilya-fedin first please allow me to apologize for the confusion above. The fact that the FreeDesktop runtime 22.08 will ship with FFmpeg 5 is only a minor inconvenience, since Telegram can bundle the precise FFmpeg version it needs to (OBS Studio needs to ship a patched version of FFmpeg, so there's precedent for it.)

I see that you're actively committing to this repository, and maintaining the Flathub build, so you're probably in position to determine which version of FFmpeg the Flathub build will ship. So for the sake of clarity, do you think you or anyone could document this strict FFmpeg 4 dependency somewhere? REAME.md perhaps? So that least other packagers will know what to expect from this app's dependencies.

**Comment by ilya-fedin** [comment]
> Looks like an ffmpeg regression when the same code works fine with ffmpeg 4.4 and works bad with ffmpeg 5.x

There was a big API break, maybe the code is not valid anymore?

> So for the sake of clarity, do you think you or anyone could document this strict FFmpeg 4 dependency somewhere?

There's no place where supported versions are documented the only way s to look at the Dockerfile the official binary is created from

**Comment by ilya-fedin** [comment]
> since Telegram can bundle the precise FFmpeg version it needs to (OBS Studio needs to ship a patched version of FFmpeg, so there's precedent for it.)

I don't like to build ffmpeg manually due to all that argument hell. I would rather perfer to stick to 21.08 until tdesktop starts working with fmpeg 5.

**Comment by GeorgesStavracas** [comment]
Sticking to 21.08 is absolutely fine too

**Comment by ilya-fedin** [comment]
@GeorgesStavracas do you know what openssl version will be, btw? openssl 3 is also a blocker, group calls don't work with it.

**Comment by GeorgesStavracas** [comment]
According to [their GitLab project](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/openssl.bst), that'll be openssl 3.0.5

**Comment by xvitaly** [comment]
> do you know what openssl version will be in 22.08, btw?

From changelog:

> Update openssl to openssl-3.0.5.

> since Telegram can bundle the precise FFmpeg version it needs

Don't forget to resolve licensing issues, like paying patent royalties to MPEG LA for H.264, H.265 and AAC.

**Comment by GeorgesStavracas** [comment]
Sure

**Comment by ilya-fedin** [comment]
Telegram is residing in a country where codec patents don't exist

**Comment by xvitaly** [comment]
> Telegram is residing in a country where codec patents don't exist

But US users can still download and use it. That's why devs must pay royalties.

> Looks like an ffmpeg regression when the same code works fine with ffmpeg 4.4 and works bad with ffmpeg 5.x roll_eyes

There are a lot of ffmpeg deprecation warnings due compilation.

**Comment by ilya-fedin** [comment]
No one would pay royalties. I also don't think flathub pays any royalties.

**Comment by xvitaly** [comment]
> I also don't think flathub pays any royalties.

It depends on where they are legally registered. Also they don't provide ffmpeg-full by default. `org.freedesktop.Platform.ffmpeg-full` is a separate extension.

**Comment by ilya-fedin** [comment]
It's still provided :man_shrugging:
