### ISSUE TITLE
[Feature request] Add keyboard shortcut to move onto the next contact

### ISSUE THREAD

**Issue by xuhdev** [telegramdesktop/tdesktop#2485]
For example, we can use `Ctrl-n` or `Ctrl-p` to move to the next or previous contact for fast switching conversations. My OS is GNU/Linux.

**Comment by Columpio** [comment]
Have you tested `Ctrl+Tab` / `Ctrl+Shift+Tab` ?

**Comment by xuhdev** [comment]
That works, thanks!
