### ISSUE TITLE
"Open in new window" feature

### ISSUE THREAD

**Issue by singleDeveloper63** [telegramdesktop/tdesktop#24860]
### Is your feature request related to a problem?

This can be a problem if you are reading one important message and another important message comes in and you have to read them both in parallel.

### Describe the solution you'd like

Guys , you need to create "Open in new window" like menu item in chat lists context menu.
![image](https://user-images.githubusercontent.com/63005771/182428081-503cc05b-2205-4674-9ed1-5e3fc53ecda9.png)

### Describe alternatives you've considered

Unfortunately there's no alternatives for this problem.

**Comment by ilya-fedin** [comment]
This feature is already exist, you can enable it in experimental ettings
