### ISSUE TITLE
Last time Telegram Desktop was not closed properly

### ISSUE THREAD

**Issue by Dimezis** [telegramdesktop/tdesktop#24879]
### Steps to reproduce

1) MacOs 12.5
2) Launch Telegram
3) See a dialog blink for fraction of a second - "Last time Telegram Desktop was not closed properly"

Reinstall and reboot didn't help.
The regular dedicated Macos Telegram version works fine.
This started happening after today's update to MacOs 12.5

### Expected behaviour

Work

### Actual behaviour

Crash

### Operating system

Macos 12.5

### Version of Telegram Desktop

Latest from here https://desktop.telegram.org/

### Installation source

Static binary from official website

### Logs

```shell
For some reason there are no logs in the Console app
```

**Comment by john-preston** [comment]
@Dimezis Please try the beta version from https://desktop.telegram.org/changelog#beta-version

**Comment by Dimezis** [comment]
@john-preston still the same problem unfortunately

**Comment by Dimezis** [comment]
This time however it shows more info. I also sent the report

<img width="623" alt="image" src="https://user-images.githubusercontent.com/1433500/183244285-706e8ad5-ece3-4abf-990f-70b36da1fe50.png">

```
ApiId: 2040
Binary: Telegram.app
Launched: 06.08.2022 11:59:37
OpenGL Renderer: [not-initialized]
Platform: MacOS
UserTag: 35002cb3da3d3faf
Username: Dimezis
Version: 4000004 beta
OS-Version: 2113.5999
Caught signal 6 (SIGABRT) in thread 4423435648

Backtrace omitted.

```

**Comment by john-preston** [comment]
@Dimezis Please contact me at t.me/preston, I'll ask you to send me .zip-ed folder "~/Library/Application Support/Telegram Desktop/tdata/dumps"

**Comment by john-preston** [comment]
@Dimezis Please also submit the report and copy the "Your Report Tag" string from the crash report window and post it here.

**Comment by Dimezis** [comment]
Report tag
96a42322-160d-4d1d-9293-358952166bdc

**Comment by Dimezis** [comment]
Seem to be caused by this - https://issuehint.com/issue/kovidgoyal/kitty/5302
Works fine without an external monitor or without a custom color profile

**Comment by john-preston** [comment]
@Dimezis I can't really know how to fix this right now :( Perhaps OpenGL became broken in 12.5 in such setups. Possibly Qt 6.4 with Metal widgets backed is the answer for that. But this is a very new tech, I'm a bit afraid to dive in that right now, this may have huge amount of bugs + requires a lot of rewriting, because right now all hardware-accelerated rendering on all platforms uses OpenGL directly.

**Comment by vandpurnama** [comment]
i got same problem on linux 

installed using aur package : telegram-dekstop-bin
installed version : 4.3.1-1

[dump core file ](https://anonymfile.com/Na6xZ/829bb8fe-b8e3-4a0a-d523b590-00fa3d7ddmp.7z)

![2022-11-14_13-38](https://user-images.githubusercontent.com/33601181/201592023-67e83dfa-150d-4353-93fb-2f0695d3cba8.png)

**Comment by vandpurnama** [comment]
I got same problem on linux
![2022-11-14_13-38](https://user-images.githubusercontent.com/33601181/201593117-8fbd5df5-48d9-4d30-8c4d-69cbb4654040.png)

Installed using aur package : telegram-desktop-bin
Installed version : 4.3.1-1  (Lastest version)

[dump core file](https://anonymfile.com/Na6xZ/829bb8fe-b8e3-4a0a-d523b590-00fa3d7ddmp.7z)

**Comment by Aokromes** [comment]
> I got same problem on linux ![2022-11-14_13-38](https://user-images.githubusercontent.com/33601181/201593117-8fbd5df5-48d9-4d30-8c4d-69cbb4654040.png)
> 
> Installed using aur package : telegram-desktop-bin Installed version : 4.3.1-1 (Lastest version)
> 
> [dump core file](https://anonymfile.com/Na6xZ/829bb8fe-b8e3-4a0a-d523b590-00fa3d7ddmp.7z)

plz try downloading official version (non snap, non flakpak) from https://desktop.telegram.org

**Comment by vandpurnama** [comment]
> > I got same problem on linux ![2022-11-14_13-38](https://user-images.githubusercontent.com/33601181/201593117-8fbd5df5-48d9-4d30-8c4d-69cbb4654040.png)
> > Installed using aur package : telegram-desktop-bin Installed version : 4.3.1-1 (Lastest version)
> > [dump core file](https://anonymfile.com/Na6xZ/829bb8fe-b8e3-4a0a-d523b590-00fa3d7ddmp.7z)
> 
> plz try downloading official version (non snap, non flakpak) from https://desktop.telegram.org

i'm installing directly from [aur package...](https://aur.archlinux.org/packages/telegram-desktop-bin) it's desktop native that clone and build from this repo release and it's not from snap or flakpak version

**Comment by Aokromes** [comment]
> > > I got same problem on linux ![2022-11-14_13-38](https://user-images.githubusercontent.com/33601181/201593117-8fbd5df5-48d9-4d30-8c4d-69cbb4654040.png)
> > > Installed using aur package : telegram-desktop-bin Installed version : 4.3.1-1 (Lastest version)
> > > [dump core file](https://anonymfile.com/Na6xZ/829bb8fe-b8e3-4a0a-d523b590-00fa3d7ddmp.7z)
> > 
> > 
> > plz try downloading official version (non snap, non flakpak) from [desktop.telegram.org](https://desktop.telegram.org)
> 
> i'm installing directly from [aur package...](https://aur.archlinux.org/packages/telegram-desktop-bin) it's desktop native that clone and build from this repo release and it's not from snap or flakpak version
> 
> is this repo release different from [desktop.telegram.org](https://desktop.telegram.org) release ?

arch packages are known causing issues official versions don't have, that's why i ask you to try static binary instead.

**Comment by vandpurnama** [comment]
nope still error and got force close

terminal log :
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by periwinkleFTW** [comment]
Have the same error for all of november 2022. annoying af.
Redownloaded and reinstalled latest version. Still the same error

**Comment by Chupaka** [comment]
MacOS 13.0.1 here. TD is working in background and then sometimes disappears w/o any messages. When I launch it, it shows the same window with "last time telegram desktop was not closed properly" message.

I checked `~/Library/Application Support/Telegram Desktop/tdata/dumps/completed` folder - since Oct 26 I have almost 70 dumps, sometimes several times a day.

**Comment by BotBY** [comment]
It's the same for me. Almost every time I close the lid of my macbook Telegram closes with an error

**Comment by Flake174** [comment]
Hello! I had the same problem.
The following steps helped me
1. Terminate desktop session throught mobile app
2. Open desktop version, wait for login screen
3. Close desktop app(important!)
4. Open desktop app again and log in

After that app stopped crashing

**Comment by ederdeivid** [comment]
Try this following steps:

**WINDOWS**:
1- Windows key > type "Telegram"  > Right Click > Go to file location
    1.1 - Right click on Telegram shortcut > Go to file location (once again)

 _Now you are in the real file location_ 

2- **GO TO:**  tdata > user_data > cache > (select your cache folder) > CTRL + A  _(there are a lot of folders, right?_) > SHIFT + DEL > Confirm > Relaunch


**LINUX**
_idk_

**Comment by BotBY** [comment]
@john-preston Any updates? It's been almost a year now.

**Comment by ilya-fedin** [comment]
@BotBY wasn't this fixed on macOS side?

**Comment by BotBY** [comment]
@ilya-fedin No. In spite of all the macOS (Intel) and Telegram updates I still get this error

**Comment by ilya-fedin** [comment]
I guess this won't be solved any time soon as first Qt version with Metal is 6.4 but its minimal macOS version is 10.14. tdesktop has planned to deprecate 10.12 in July and make 10.13 the minimal supported version. Deprecates are very rare what means tdesktop is blocked on older Qt for multiple next years.

**Comment by john-preston** [comment]
@BotBY Do you have dumps in tdata/dumps/completed after those closings? The same folder that is mentioned in the conversation above.

If you do, please enable installing beta versions in Settings Advanced. After that it should offer you to send crash report after the next crash. Send it and send here the Crash ID from the sending box. Maybe now it gives something fixable 🫣

**Comment by informagico** [comment]
@john-preston same thing happens to me every time.
I'm on macOS 13.4 Beta (22F5027f).
Telegram version 4.7.0 (beta enabled)

**Crash ID:** 11f24154-3d7c-4515-aca4-b55854e69c63

```
ApiId: 2040
Assertion: "_eventNestingLevel >= _loopNestingLevel" sandbox.cpp:577
Binary: Telegram.app
Launched: 11.04.2023 19:07:54
OpenGL: Enabled
OpenGL Renderer: [not-initialized]
Platform: MacOS
Version: 4007000
OS-Version: 2299.5000
Caught signal 11 (SIGSEGV) in thread 140704440714880
```

If you need I can share the dumps folder, just let me know where I can reach you.

**Comment by Nguyenpham89** [comment]
Tôi ở việt nam .hình như ban thuộc trang web thứ ba

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: Alessandro Magoga ***@***.***>
Đã gửi: Thursday, April 13, 2023 2:43:36 AM
Đến: telegramdesktop/tdesktop ***@***.***>
Cc: Subscribed ***@***.***>
Chủ đề: Re: [telegramdesktop/tdesktop] Last time Telegram Desktop was not closed properly (Issue #24879)


@john-preston<https://github.com/john-preston> same thing happens to me every time.
I'm on macOS 13.4 Beta (22F5027f).
Telegram version 4.7.0 (beta enabled)

Crash ID: 11f24154-3d7c-4515-aca4-b55854e69c63

ApiId: 2040
Assertion: "_eventNestingLevel >= _loopNestingLevel" sandbox.cpp:577
Binary: Telegram.app
Launched: 11.04.2023 19:07:54
OpenGL: Enabled
OpenGL Renderer: [not-initialized]
Platform: MacOS
Version: 4007000
OS-Version: 2299.5000
Caught signal 11 (SIGSEGV) in thread 140704440714880


If you need I can share the dumps folder, just let me know where I can reach you.

**Comment by Nguyenpham89** [comment]
18

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: Nguyen Pham ***@***.***>
Đã gửi: Thursday, April 13, 2023 2:46:36 AM
Đến: telegramdesktop/tdesktop ***@***.***>; telegramdesktop/tdesktop ***@***.***>
Cc: Subscribed ***@***.***>
Chủ đề: Re: [telegramdesktop/tdesktop] Last time Telegram Desktop was not closed properly (Issue #24879)

Tôi ở việt nam .hình như ban thuộc trang web thứ ba

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: Alessandro Magoga ***@***.***>
Đã gửi: Thursday, April 13, 2023 2:43:36 AM
Đến: telegramdesktop/tdesktop ***@***.***>
Cc: Subscribed ***@***.***>
Chủ đề: Re: [telegramdesktop/tdesktop] Last time Telegram Desktop was not closed properly (Issue #24879)


@john-preston<https://github.com/john-preston> same thing happens to me every time.
I'm on macOS 13.4 Beta (22F5027f).
Telegram version 4.7.0 (beta enabled)

Crash ID: 11f24154-3d7c-4515-aca4-b55854e69c63

ApiId: 2040
Assertion: "_eventNestingLevel >= _loopNestingLevel" sandbox.cpp:577
Binary: Telegram.app
Launched: 11.04.2023 19:07:54
OpenGL: Enabled
OpenGL Renderer: [not-initialized]
Platform: MacOS
Version: 4007000
OS-Version: 2299.5000
Caught signal 11 (SIGSEGV) in thread 140704440714880


If you need I can share the dumps folder, just let me know where I can reach you.

**Comment by BotBY** [comment]
@john-preston Crash ID: 5cbfe7ab-4c79-437d-8108-53b99f89e378

**Comment by Gennady-G** [comment]
This bug is also occurs on Telegram desktop 4.7.1 on Windows Server 2019 (portable telegram version). If I reinstall full (non-portable) version will it resolve, what do You think?

**Comment by ilya-fedin** [comment]
@Gennady-G you can't have the problem discussed here, the issue is about a crash on macOS systems with color-managed displays.

**Comment by informagico** [comment]
@ilya-fedin Sorry for the dumb question, what do you mean with color-managed displays?

**Comment by ilya-fedin** [comment]
@informagico non-sRGB color profile

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/24879#issuecomment-1207209923

**Comment by ksa-real** [comment]
I have official Telegram Desktop 4.8.1 on MacOS and Telegram constantly silently crashes when the laptop gets suspended (lid is closed). I cannot tell when this happens exactly - right after the lid is closed or some other conditions must be met. I have this issue since the upgrade to macOS Ventura.

**Comment by dzentota** [comment]
I have the same issue as @ksa-real (MacOs Ventura) for a long time

**Comment by ksa-real** [comment]
Still have the issue on two different Macbooks with Ventura. Almost every time I open the laptop lid, I have to open Telegram again.

**Comment by Aokromes** [comment]
try with the latest 4.8.9 version.

**Comment by ksa-real** [comment]
The latest I see in this repo or on the official site is 4.8.8. Where to get it?

**Comment by Chupaka** [comment]
@Aokromes the same situation on 4.8.9

**Comment by ksa-real** [comment]
Actually, may be a bit different now. The app crashed a few times during normal work, like switching between windows. Previously I associated the issue with suspend mode / lid closure only.
