### ISSUE TITLE
Telegram Crash for unknown reason

### ISSUE THREAD

**Issue by HaMo0n** [telegramdesktop/tdesktop#2487]
Hi
sometimes telegram stop working for unknown reason.
This is my log.txt Details:
terminate called after throwing an instance of 'mtpErrorWrongTypeId'
  what():  MTP Wrong type id 2652479990 for this data conversion, must be 3231442015

### Configuration
Linux
**Version of Telegram Desktop:**
0.10.1

### Logs
terminate called after throwing an instance of 'mtpErrorWrongTypeId'
  what():  MTP Wrong type id 2652479990 for this data conversion, must be 3231442015

**Comment by john-preston** [comment]
@HaMo0n Please check out the lastest version 0.10.8.

**Comment by HaMo0n** [comment]
Thank you @john-preston.
In fact I changed a few files for custom my Telegram App.
I want to know Which files is changed in 0.10.8.

**Comment by john-preston** [comment]
@HaMo0n Quite a lot %)

**Comment by HaMo0n** [comment]
Sorry @john-preston but The master branch has until 0.10.7 version and after upgrade to 0.10.7 the problem still exist

**Comment by john-preston** [comment]
@HaMo0n This problem is in your additions to the code, not the existing code of tdesktop. You call .c_message() somewhere, where .type() == mtpc_messageService, not mtpc_message, but it requires .type() == mtpc_message.

Does 0.10.7 built from code without any changes crash as well?

**Comment by HaMo0n** [comment]
@john-preston Yes you right. Thanks
