### ISSUE TITLE
Telegram bot enable voice chat

### ISSUE THREAD

**Issue by Berrylicious67** [telegramdesktop/tdesktop#24877]
![Screenshot_2022-08-06-16-34-36-227](https://user-images.githubusercontent.com/110717973/183241552-7eefabe9-6da3-4a79-a643-9810f974d947.jpeg)
The bot is telling me this: "Error Joining Voice Chat. Make sure Voice Chat is Enabled." but there's no voice chat, but there is video chat and that doesn't work. Please help

**Comment by Berrylicious67** [comment]
![Screenshot_2022-08-06-16-36-55-325](https://user-images.githubusercontent.com/110717973/183241622-9e381b93-ffef-4d3b-8eb9-6a08faf15a10.jpeg)
It says "Start Video chat" instead of "Start Voice chat" or whatever

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
