### ISSUE TITLE
Auto-updating the app on Windows 10 resets (some) user preferences

### ISSUE THREAD

**Issue by tudorminator** [telegramdesktop/tdesktop#24887]
Today I have clicked the update button in the interface, bringing the desktop app to version 4.0.4 beta x64 on Windows 10 Version 21H2 Build 19044.1826. After the update finished, my preferences for "Large emoji", as well as for "Loop animated stickers" were set to ON, although I always have them set to OFF!

I have noticed this for other past updates too, but unfortunately I didn't think to take note of the details. I don't know if other preferences are affected, but these two really bug me. I would really appreciate if my preferences were not reset on update. Thank you.

**Comment by ilya-fedin** [comment]
#5944

**Comment by john-preston** [comment]
@tudorminator does it happen if you:

- take a fresh 4.0.2 stable portable version from https://desktop.telegram.org in a separate folder
- log in and set your preferences as you like them
- restart the app to check that they don't reset on a simple restart
- and then enable updating to beta versions in Settings and autoupdate to 4.0.4 beta

Does it happen as well? Does it reproduce in that case?

**Comment by ilya-fedin** [comment]
I would rather ask to check with `-freetype` argument

**Comment by tudorminator** [comment]
@john-preston I have followed the steps exactly. It does not reproduce after a simple restart, and it also doesn't reproduce after auto-updating to 4.0.4 beta.
