### ISSUE TITLE
TelegramDesktop opening with the wrong window size

### ISSUE THREAD

**Issue by cas4ey** [telegramdesktop/tdesktop#24889]
### Steps to reproduce

1. Put Telegram Default interface scale to 125%
2. Resize Telegram to an okay size for the monitor
3. Shut down Telegram
4. Open Telegram
5. Notice that it's now 25% bigger than before
6. Repeat step 3 and 4 and Telegram will eventually grow to cover the entire monitor

### Expected behaviour

I expect Telegram to start with the same window size as when I closed it

### Actual behaviour

It keeps growing in window size and eventually covers the entire monitor

### Operating system

Ubuntu 20.04.4 LTS

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by cas4ey** [comment]
Same as #6924, still reproduces for linux

**Comment by ilya-fedin** [comment]
I believe this is already fixed on dev branch

**Comment by cas4ey** [comment]
Checked additionally: the behavior doesn't depend on scaling factor, I have changed Telegram scaling factor to 100% (OS scaling factor is 100% also) and it still increases window size on every restart.

**Comment by cas4ey** [comment]
@ilya-fedin does it mean it should be fixed in version 4.0.3 ?

**Comment by ilya-fedin** [comment]
No, it's fixed on dev branch not in any released version

**Comment by cas4ey** [comment]
Any chance it would be released?

**Comment by ilya-fedin** [comment]
It will be in whatever version will be created from the current dev branch state

**Comment by cas4ey** [comment]
@ilya-fedin @Aokromes after updating to Telegram v4.1.0, window size started to decrease on every Telegram restart :)

**Comment by ilya-fedin** [comment]
Yeah, there's a new attempt to fix this on dev branch
