### ISSUE TITLE
[Feature Request] 175% interface scaling option

### ISSUE THREAD

**Issue by 98mohitkumar** [telegramdesktop/tdesktop#24884]
### Is your feature request related to a problem?

150% scaling is too small and 200% is too big.

### Describe the solution you'd like

can we have 175% scaling option, or maybe telegram should adapt to dpi scaling of the monitor ? 

related : [#1121](https://github.com/telegramdesktop/tdesktop/issues/1121), [#10588](https://github.com/telegramdesktop/tdesktop/issues/10588)

### Describe alternatives you've considered

tried some third party clients which solved the scaling issue, but they have some other serious bugs so not really a fair trade off.

### Additional context

Platform : Windows 11 
Telegram Version : 4.0 x64

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/wiki/Command-Line-Switches

**Comment by mohitkumar29** [comment]
@Aokromes i am using the microsoft store version, can you guide me how to use these commands.

**Comment by 98mohitkumar** [comment]
@Aokromes  i am using the microsoft store version, can you guide me how to use these commands.
