### ISSUE TITLE
The problem of touch control of discussions in the publication.

### ISSUE THREAD

**Issue by Vldm11r** [telegramdesktop/tdesktop#24880]
### Steps to reproduce

Go to the comments of any post and try to scroll through them. 

### Expected behaviour

Scrolling through comments should be done by swiping with one finger, and a long hold should bring up the context menu.

### Actual behaviour

One touch instead of flipping comments - you select them, which is not convenient and not logical, and flipping works with only two fingers.

### Operating system

Windows 11 21H2 x64

### Version of Telegram Desktop

4.0.2 x64 (windows)

### Installation source

Static binary from official website

**Comment by sleirsgoevy** [comment]
Confirmed.

**Comment by yuyoyuppe** [comment]
same issue on surface pro x
