### ISSUE TITLE
Tray icon menu appears only once

### ISSUE THREAD

**Issue by kirizdev** [telegramdesktop/tdesktop#24891]
### Steps to reproduce

1. Open Telegram Desktop
2. Right click on tray icon
3. Click Disable notifications or just close the menu
4. Right click on tray icon again

### Expected behaviour

Menu should appear every time I right click on it

### Actual behaviour

Menu doesn't appear every time I right click on it

### Operating system

Fedora Linux 36 (Thirty Six) x86_64, bspwm

### Version of Telegram Desktop

4.0.4 beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can't reproduce, tested the following environments, appears every time: KDE Neon, NixOS with MATE, Manjaro Xfce

**Comment by kirizdev** [comment]
I have tried several versions of Telegram Desktop. The latest version on which the menu works is 3.7.1. I also noticed a commit that may be causing the problem, e96731be117839d42c2dd1ca8cb80df6977c8525. Installing the compositor solved the problem (but I don't want to use it)

**Comment by ilya-fedin** [comment]
Indeed, I can reproduce without compositing
