### ISSUE TITLE
[Feature Request] "Notify Me When Contacts Join" Makes Users in Authoritarian Countries in Danger

### ISSUE THREAD

**Issue by TelegramInsecurity** [telegramdesktop/tdesktop#24896]
### Is your feature request related to a problem?

You've been always advertising your privacy and security. But now, a feature in Telegram is killing users from authoritarian countries!
(Screenshots: https://files.catbox.moe/yxygoh.png https://files.catbox.moe/alt49w.png)
Look. If someone has my phone number, you'll notify him/her when I join Telegram with the number. The Iranian government once imported almost all the Iranian phone numbers to Telegram, in order to receive notifications when its people signed up for Telegram. After that you've limited the frequency of importing phone numbers per account. However, it won't work because governments can register a huge number of accounts for importing numbers. Today I found that even if I change the number, users who have my new number will be notified.
Not everyone in authoritarian countries like China and Iran has an anonymous virtual number like mine. Many Chinese dissidents love chatting in public groups, and some of them got arrested by the police because their +86 numbers were leaked. If we buy Google Voice numbers using WeChat Pay or Alipay to sign up for Telegram, it's also insecure because the sellers can import the numbers to Telegram and get notified when we register.

### Describe the solution you'd like

Therefore, I strongly advise you: Give users a choice whether to notify those who have their numbers when registering; When adding contacts, please make "Share my number" unselected by default.
By the way, you've banned registering on PC. However, many Chinese dissidents don't have secure phones or tablets. I strongly advise you to allow registering on PC, and make the Telegram IDs invisible in Settings -> Passwords & accounts on Android phones, because many Chinese phones upload the information in it to the servers controlled by the Chinese Communist Party.

### Describe alternatives you've considered

Alternatives? I think Element is the most privacy friendly instant messenger.

### Additional context

We Are Privacy Advocators from Authoritarian Countries.

**Comment by TelegramInsecurity** [comment]
People who care about privacy can upvote https://bugs.telegram.org/c/19612

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
