### ISSUE TITLE
[Feature Request] Add the option to rename UserBots sessions

### ISSUE THREAD

**Issue by tissole** [telegramdesktop/tdesktop#24899]
### Is your feature request related to a problem?

Currently, the users can only rename the sessions in which they are logged. This is fine for the Telegram Desktop and Mobile clients, but for UserBots it is impossible. 

### Describe the solution you'd like

I would like an option to rename these sessions too. In many occasions I have ended the sessions for userbots by mistake because it is difficult to differentiate between them. If we can rename those, it makes it easier for management.

### Describe alternatives you've considered

None.

**Comment by RememberTheAir** [comment]
This is out of the scope of this client, as the API doesn't allow to rename a session from within another session. By the way, you should be able to rename the session programmatically from the script running the bot

**Comment by tissole** [comment]
Thanks for the info. You mean the name will be changed in Telegram active sessions menu? Can you give me some hints? Is sounds very interesting.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by RememberTheAir** [comment]
> You mean the name will be changed in Telegram active sessions menu?

Yes. I don't know what's the method name to rename a current session, but each client (userbots running on an mtproto implementation included) can rename its _own_ session. That means that if you're running a bot on an account, you can configure that bot to rename its session on startup (or at any moment)
