### ISSUE TITLE
Telegram Beta fills up ram without no reason

### ISSUE THREAD

**Issue by NRanjan-17** [telegramdesktop/tdesktop#24890]
### Steps to reproduce

Open Telegram desktop or run it for sometimes
Sometimes while opening the app or after sometimes the app used to hang and fill up the whole memory
the whole system used to hang and needs to be shutdown through power off 
force shutdown also didn't work

### Expected behaviour

the app should not hang and should not eat so much memory 

### Actual behaviour

instead app used to hang and fills up memory

### Operating system

Windows 11

### Version of Telegram Desktop

4.0.4 Beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@NRanjan-17 I don't know how to reproduce that :(

**Comment by NRanjan-17** [comment]
1. Open Telegram Desktop 
2. It will hang the whole system in the loading period or after sometimes

**Comment by john-preston** [comment]
Well, this doesn't happen with me. Something should cause it and for now I have no idea what this could be.

**Comment by NRanjan-17** [comment]
It happens to me multiple times

**Comment by ilya-fedin** [comment]
> 2\. It will hang the whole system in the loading period or after sometimes

This sounds like your system has too much fonts. It's known that Qt tries to load all the fonts on the system, so if you have around ~1 GB of fonts or even more, that's quite expected.

**Comment by NRanjan-17** [comment]
> > 2. It will hang the whole system in the loading period or after sometimes
> 
> This sounds like your system has too much fonts. It's known that Qt tries to load all the fonts on the system, so if you have around ~1 GB of fonts or even more, that's quite expected.

Using my system with default fonts
