### ISSUE TITLE
[Feature Request] Window dimensions lower than minimal

### ISSUE THREAD

**Issue by frostmorn** [telegramdesktop/tdesktop#24904]
### Is your feature request related to a problem?

Some window managers, like an i3wm doesn't have a propper way to limit minimum window size, also them could use non-standart way to change window dimensions at all.
So, eventually u could change window size lower than limited in tdesktop, which causes a crash.

### Describe the solution you'd like

Draw a simple message inside window that dimensions r lower than possible, make a way not to fall in a dirty crash.

### Describe alternatives you've considered

Paint a dog inside with text (I can't fit in such a dimension-limited space :D)

**Comment by ilya-fedin** [comment]
tdesktop sets minimum size with Qt APIs that should advertise further with X11 APIs. If your window manager doesn't respect that, it's a bug that you should report to window manager, not to tdesktop.

**Comment by john-preston** [comment]
@frostmorn If it crashes on the official build please enable Install beta versions in Settings, reproduce the crash and send the crash report on relaunch + post "Your report tag" here, I can try to fix it if I see where it crashes.

**Comment by frostmorn** [comment]
@john-preston  Report tag cf18b12b-def6-4557-c09b3abf-5eaa517c
