### ISSUE TITLE
about Secret Chats

### ISSUE THREAD

**Issue by sakurayz** [telegramdesktop/tdesktop#24905]
Some people think secret chat (peer-to-peer encryption) will be more secure, is this a misconception?

The data of secret chat is stored locally, while non-secret chat is stored on the cloud server. It is difficult to see the difference from the UI of the telegram program. Users mistakenly believe that non-secret chats are unsafe.

Is it possible to add a global option, or an option for each contact to let the user decide if the data is stored in the cloud server or locally (secret chat)

**Comment by dm17** [comment]
https://github.com/marcovelon/tdesktop/issues/2

**Comment by eyalroz** [comment]
@dm17  so... what's happening and when? Is there a timeline for this being added?

**Comment by Aokromes** [comment]
duplicate, someone is working on a implementation for telegram desktop, no idea of completion state.

**Comment by eyalroz** [comment]
@Aokromes : Ok, but - duplicate of which issue number?

**Comment by dm17** [comment]
> @Aokromes : Ok, but - duplicate of which issue number?

https://github.com/marcovelon/tdesktop/issues/2#issuecomment-1471433229

**Comment by ilya-fedin** [comment]
> Ok, but - duplicate of which issue number?

#871

> duplicate, someone is working on a implementation for telegram desktop, no idea of completion state.

@john-preston is working on a tdlib rewrite in his spare time (without acknowledgement of the team AFAIK), but there's no ETA.
