### ISSUE TITLE
Can't record voice message in my "Saved Messages"

### ISSUE THREAD

**Issue by fatimafiras** [telegramdesktop/tdesktop#24906]
### Steps to reproduce

Record  voice message from the mic icon in my "Saved Messages" ![image](https://user-images.githubusercontent.com/73543807/184130631-d314064b-d740-4565-960b-ce63a19d84a4.png)

 will show this message:
![image](https://user-images.githubusercontent.com/73543807/184129984-5e18617e-0faa-4769-9567-c839f0c7fd2f.png)

I'm not a premium user, and this is my privacy settings
![image](https://user-images.githubusercontent.com/73543807/184130449-0e17cdf9-0975-4e4c-bafc-9f88cdda117b.png)

note:
forwarding a voice message to my saved messages:
if the voice message was recorded by anyone else, it works fine
if the voice message was recorded by me in another chat, then forwarded to my saved messages, it won't work. the same message above is shown " ..... doesn't accept voice messages."

### Expected behaviour

it was working before.. so the Expected behavior is:
I can send voice messages in my Saved Messages because  I'm not a premium user, and everone can send my voice messages.

### Actual behaviour

I can't record voice message in my saved messages, and this message is shown when i click on the mic icon, or forwarding a voice I recorded in another chat to my saved messages.
![image](https://user-images.githubusercontent.com/73543807/184129984-5e18617e-0faa-4769-9567-c839f0c7fd2f.png)

### Operating system

windows 10 and windows 11

### Version of Telegram Desktop

4.0.4 beta

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
fixed on 4.1
