### ISSUE TITLE
Build error v4.0.4

### ISSUE THREAD

**Issue by blackcross86** [telegramdesktop/tdesktop#24902]
### Steps to reproduce

When cmake is called, it throws an error.
Compilation on qt5 is successful.On q6 there will be an error

### Expected behaviour

How to solve the problem

### Actual behaviour

How to solve the problem

### Operating system

linux

### Version of Telegram Desktop

4.0.4

### Installation source

Other (unofficial) source

### Logs

```shell
CMake Error at Telegram/CMakeLists.txt:7 (add_executable):
  Target "Telegram" links to target "EGL::EGL" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
CMake Error at Telegram/lib_base/CMakeLists.txt:11 (add_library):
  Target "lib_base_crash_report_writer" links to target "EGL::EGL" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
CMake Error at Telegram/lib_base/CMakeLists.txt:7 (add_library):
  Target "lib_base" links to target "EGL::EGL" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
CMake Error at Telegram/lib_ui/CMakeLists.txt:14 (add_library):
  Target "lib_ui" links to target "EGL::EGL" but the target was not found.  
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
CMake Error at Telegram/lib_spellcheck/CMakeLists.txt:7 (add_library):
  Target "lib_spellcheck" links to target "EGL::EGL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
CMake Error at Telegram/lib_waylandshells/waylandshells/xdg-shell/CMakeLists.txt:7 (add_library):
  Target "lib_waylandshells_xdg_shell" links to target "EGL::EGL" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
CMake Error at Telegram/lib_webview/CMakeLists.txt:7 (add_library):
  Target "lib_webview" links to target "EGL::EGL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing? 
CMake Error at Telegram/codegen/codegen/emoji/CMakeLists.txt:1 (add_executable):
  Target "codegen_emoji" links to target "EGL::EGL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing? 
CMake Error at Telegram/codegen/codegen/lang/CMakeLists.txt:1 (add_executable):
  Target "codegen_lang" links to target "EGL::EGL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
CMake Error at Telegram/codegen/codegen/style/CMakeLists.txt:1 (add_executable):
  Target "codegen_style" links to target "EGL::EGL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
CMake Error at cmake/external/qt/qt_static_plugins/CMakeLists.txt:7 (add_library):
  Target "external_qt_static_plugins" links to target "EGL::EGL" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
CMake Error at Telegram/cmake/td_ui.cmake:7 (add_library):
  Target "td_ui" links to target "EGL::EGL" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  Telegram/CMakeLists.txt:40 (include)
CMake Error at Telegram/cmake/lib_stripe.cmake:7 (add_library):
  Target "lib_stripe" links to target "EGL::EGL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
```

**Comment by blackcross86** [comment]
> Looks like your Qt 6 installation is broken, cmake can't find Qt's 3rdparty cmake helpers

So qt6 itself is broken? Maybe you can tell me approximately what exactly, I would be grateful.

**Comment by ilya-fedin** [comment]
> So qt6 itself is broken? Maybe you can tell me approximately what exactly, I would be grateful.

cmake fails to find EGL target that is provided by Qt, e.g. on Arch it has path `/usr/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules/FindEGL.cmake`, cmake can't find it on your system for some reason.

**Comment by ilya-fedin** [comment]
According to the error, your Qt install didn't even try to import it, so it may exist, but stil is not used by your Qt cmake configuration files for some reason

**Comment by blackcross86** [comment]
> > So qt6 itself is broken? Maybe you can tell me approximately what exactly, I would be grateful.
> 
> cmake fails to find EGL target that is provided by Qt, e.g. on Arch it has path `/usr/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules/FindEGL.cmake`, cmake can't find it on your system for some reason.

Is it possible to somehow specify the path with the cmake flag?

**Comment by ilya-fedin** [comment]
You shouldn't do that, Qt should specify all the the paths automatically.

**Comment by ilya-fedin** [comment]
If you don't know what's going on with Qt installation, maybe you should [follow the instruction](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md)?

**Comment by blackcross86** [comment]
> If you don't know what's going on with your Qt installation, maybe you should [follow the instruction](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md)?

It seems to me that he sees from qt5 Findel.cmake .Could it be that?

**Comment by ilya-fedin** [comment]
Qt 5 doesn't provide FindEGL.cmake, it used qmake to build itself and didn't use native cmake features when generating cmake config files therefore

**Comment by ilya-fedin** [comment]
Why don't you just follow the instruction? It will build pre-configured environment for you.

**Comment by blackcross86** [comment]
> Why don't you just follow the instruction? It will build pre-configured environment for you.

Yes , I 'll read it .Thank you.
