### ISSUE TITLE
Build failure of Telegram Desktop 4.1.0 using GCC 10.3.0 (on Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by savoury1** [telegramdesktop/tdesktop#24917]
### Steps to reproduce

Attempt to build Telegram Desktop 4.1.0 with GCC 10.3.0 in clean Ubuntu 20.04 LTS chroot (using pbuilder).

### Expected behaviour

Successful build of Telegram Desktop 4.1.0 using GCC 10.3.0 as with earlier versions (ie. 4.0.2).

### Actual behaviour

Build fails on two source files (key part of build log relating to ffmpeg_emoji.cpp failure included below):

Telegram/SourceFiles/ffmpeg/ffmpeg_emoji.cpp
Telegram/lib_lottie/lottie/lottie_emoji.cpp

This is due a missing <memory> header in both cases, in these files:

Telegram/SourceFiles/ffmpeg/ffmpeg_emoji.h
Telegram/lib_lottie/lottie/lottie_emoji.h

Adding ```#include <memory>``` to both mentioned headers fixes the build. Log of successful build with patched source here:
https://launchpad.net/~savoury1/+archive/ubuntu/telegram/+build/24276790

### Operating system

Ubuntu 20.04 LTS

### Version of Telegram Desktop

4.1.0

### Installation source

Other (unofficial) source

### Logs

```shell
[ 36%] Building CXX object Telegram/CMakeFiles/lib_ffmpeg.dir/SourceFiles/ffmpeg/ffmpeg_emoji.cpp.o

...

In file included from /build/telegram-desktop-4.1.0+ds/Telegram/SourceFiles/ffmpeg/ffmpeg_emoji.cpp:8:
/build/telegram-desktop-4.1.0+ds/Telegram/SourceFiles/ffmpeg/ffmpeg_emoji.h:30:7: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   30 |  std::unique_ptr<Impl> _impl;
      |       ^~~~~~~~~~
/build/telegram-desktop-4.1.0+ds/Telegram/SourceFiles/ffmpeg/ffmpeg_emoji.h:13:1: note: ‘std::unique_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
   12 | #include <QtGui/QImage>
  +++ |+#include <memory>
   13 | 

...

/build/telegram-desktop-4.1.0+ds/Telegram/SourceFiles/ffmpeg/ffmpeg_emoji.cpp: In constructor ‘FFmpeg::EmojiGenerator::EmojiGenerator(const QByteArray&)’:
/build/telegram-desktop-4.1.0+ds/Telegram/SourceFiles/ffmpeg/ffmpeg_emoji.cpp:358:3: error: class ‘FFmpeg::EmojiGenerator’ does not have any field named ‘_impl’
  358 | : _impl(std::make_unique<Impl>(bytes)) {
      |   ^~~~~
/build/telegram-desktop-4.1.0+ds/Telegram/SourceFiles/ffmpeg/ffmpeg_emoji.cpp: In member function ‘virtual Ui::FrameGenerator::Frame FFmpeg::EmojiGenerator::renderNext(QImage, QSize, Qt::AspectRatioMode)’:
/build/telegram-desktop-4.1.0+ds/Telegram/SourceFiles/ffmpeg/ffmpeg_emoji.cpp:371:9: error: ‘_impl’ was not declared in this scope
  371 |  return _impl->renderNext(std::move(storage), size, mode);
      |         ^~~~~
make[3]: *** [Telegram/CMakeFiles/lib_ffmpeg.dir/build.make:79: Telegram/CMakeFiles/lib_ffmpeg.dir/SourceFiles/ffmpeg/ffmpeg_emoji.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```

**Comment by ilya-fedin** [comment]
Why not to create PR instead of issue?

**Comment by joecool1029** [comment]
I patched it for gentoo, I'll open a PR for upstream here I guess. Here's the patch if you don't want to wait: https://raw.githubusercontent.com/joecool1029/gentoo/4432e35154f668c058d64b0411f4ae8e64b9e2de/net-im/telegram-desktop/files/tdesktop-4.1.0-fix-gcc12-math.patch

**Comment by savoury1** [comment]
Thanks @joecool1029, had just cloned repos (tdesktop and lib_lottie) pushed commits to fix build issue, and was getting going on a couple pull requests myself when I noticed your own pull requests were already done, so you beat me to it! Good job.
