### ISSUE TITLE
OSX: Ctrl + Option + "Б" and Ctrl + Option + "Ю" not works

### ISSUE THREAD

**Issue by dm3ch** [telegramdesktop/tdesktop#24915]
### Steps to reproduce

Try to print dot or comma using described below key combinations on macOS standard Russian layout.

### Expected behaviour

`.` should be printed when ctrl+option+> (ю) pressed
`,` should be printed when ctrl+option+< (б) pressed

### Actual behaviour

Nothing printed when specified key combinations pressed

### Operating system

MacOS 12.4

### Version of Telegram Desktop

v4.1

### Installation source

Static binary from official website

**Comment by dm3ch** [comment]
Actually, there is an old already closed issue describing the same problem https://github.com/telegramdesktop/tdesktop/issues/2468

The only information I found there is to look into https://github.com/telegramdesktop/tdesktop/issues/1060 , but I wasn't able to find any related info.

P.S. Key combinations described in this issue are not some custom shortcuts, but a official way of printing this characters on macOS standard Russian layout (for me it works in all applications except Telegram Desktop)

**Comment by ilya-fedin** [comment]
Have you checked other Qt applications like qBittorrent or VLC?

**Comment by dm3ch** [comment]
> Have you checked other Qt applications like qBittorrent or VLC?

Just checked in VLC 3.0.17.3 in playlist search input these combinations work fine.

**Comment by ilya-fedin** [comment]
It's better to check qBittorrent. I don't know what Qt version VLC uses on macOS, but on Windows it still uses Qt 4 while tdesktop uses Qt 6, no surprise if there would be big differences in behavior. It's better to check qBittorent built with Qt 6.

**Comment by dm3ch** [comment]
Created an issue in QT bug tracker, maybe we would find some help there - https://bugreports.qt.io/browse/QTBUG-106393

**Comment by ilya-fedin** [comment]
It seems VLC on macOS doesn't use Qt: https://en.wikipedia.org/wiki/VLC_media_player#Interfaces
So it's not really known whether Qt 4 is affected or not

**Comment by dm3ch** [comment]
QT closed the issue as fixed. They wrote that fix version is: `6.5.0 Beta1`

**Comment by ilya-fedin** [comment]
How fast

**Comment by ilya-fedin** [comment]
It's sadly not that simple, first the patches in https://github.com/desktop-app/patches should be updated as there are new API uses that break macOS 10.12+ build in Qt. Then ui_window_mac, main_window_mac should be prepared for winId change in runtime as it changes now due to QtWidgets refactoring in Qt 6.4 to support RHI.

**Comment by 23rd** [comment]
> QT closed the issue as fixed. They wrote that fix version is: `6.5.0 Beta1`

Are you sure that the `6.4.1` version fixes the problem?

**Comment by ilya-fedin** [comment]
It seems the fix will be only in 6.4.2

**Comment by dm3ch** [comment]
Ahh, you are right, just realized that fix version is marked as 6.5.0-Beta1.

About using pipelines for test purposes - I got your point. It seems I'm too much out of scope/experience to do this version bump by myself. :(

**Comment by dm3ch** [comment]
By the way, if you are already managing patches for Qt in a separate repo, maybe it would be easier to backport a bugfix as a patch to currently used version instead of working on a QT version upgrade?

**Comment by dm3ch** [comment]
Just checked today, dot and comma key combinations finally works, TY
