### ISSUE TITLE
Can not click on stickers which are behind the animated emoji suggestions

### ISSUE THREAD

**Issue by Laiteux** [telegramdesktop/tdesktop#24914]
### Steps to reproduce

![hItZCREw6Z](https://user-images.githubusercontent.com/33204743/184432140-bbc0c4d6-e1a0-4f9c-8525-dbf42cd631a6.gif)

### Expected behaviour

Should be able to click on the sticker(s) behind.

### Actual behaviour

Not able to click on the sticker(s) behind.

### Operating system

Windows 10

### Version of Telegram Desktop

4.1 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@Laiteux Escape closes the emoji suggestions.

**Comment by Laiteux** [comment]
@john-preston so is this the intended behavior? Seems more like a "hitbox" issue, check my GIF
