### ISSUE TITLE
Sticker hint doesn't turn off when typing animated emoji

### ISSUE THREAD

**Issue by minsk21** [telegramdesktop/tdesktop#24913]
### Steps to reproduce

Не отключается подсказка стикеров при вводе анимированные эмоджи
В настройках подсказки стикеров отключены
Sticker hint doesn't turn off when typing animated emoji
Sticker hints are disabled in settings

![image](https://user-images.githubusercontent.com/26014600/184417290-2bc57508-da96-401e-a127-47855aee6ca2.png)

### Expected behaviour

Do not show

### Actual behaviour

Shows

### Operating system

Win 10

### Version of Telegram Desktop

4.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Stickers from your installed packs are always suggested by emoji. Only cloud-based popular stickers not from your packs are disabled by that setting. A new setting for all suggestions may be requested as an enhancement, but for now this is not in plans.
