### ISSUE TITLE
Incorrect display of premium emoji when there are too many of them

### ISSUE THREAD

**Issue by xbt573** [telegramdesktop/tdesktop#24919]
### Steps to reproduce

1. Use Telegram Desktop with premium
2. Send message with many of premium emoji from "Alphabet" pack (https://t.me/addemoji/alphabet_ru_mini)

### Expected behaviour

Correct display of emoji

### Actual behaviour

Premium emoji replaced with default emoji (😀)
Screenshot: https://imgur.com/a/pWk4MOt

### Operating system

Linux Mint 20.2, i3wm

### Version of Telegram Desktop

4.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Sorry, this is a server side limitation, only 100 custom emoji can be in a single message. Perhaps it should be shown somehow while you write the message, but the fact itself can't be changed from Telegram Desktop.
