### ISSUE TITLE
Close notification by right mouse click

### ISSUE THREAD

**Issue by memboc** [telegramdesktop/tdesktop#2491]
Sometimes i have many notifications in one moment and its cover all right part of screen, and I havent time to read it all. But i need my part of work-screen.

And sometimes i can miss close notification button, and accidentally close my work application

Example:
![screenshot_3](https://cloud.githubusercontent.com/assets/7403119/19032282/7673ba9c-8961-11e6-8b3f-1ed3d8e53609.jpg)

### Configuration
Operating system: Windows 8.1
Version of Telegram Desktop: 0.10.8

**Comment by john-preston** [comment]
Those are Windows notifications, so Windows controls how they behave. But you can switch to custom tdesktop notifications in Settings, they are closed by right mouse button.
