### ISSUE TITLE
Telegram Premium misleading recurring period (360 days instead of 1 year, 30 days instead of 1 month)

### ISSUE THREAD

**Issue by timocov** [telegramdesktop/tdesktop#24921]
### Steps to reproduce

Monthly subscription:

1. Buy a premium subscription in desktop app
2. Remember the next payment date
3. Wait for that date

Gifting a subscription:

1. Gift 1 year premium to a friend
2. Check the date when the premium subscription will be expired for a friend

### Expected behaviour

- For monthly subscription - the payment is made on exact date from the message about the next payment (i.e. +1 month from the date of first payment for monthly subscription)
- For a gift the date of expiry is the exact date from the date of payment +1 year

Alternatively, which is also fine for me, change the texts to the actual values, i.e. 360 days, 30 days, etc - just to be consistent between texts and the actual actions.

### Actual behaviour

Even though the bot says that the next payment will be made on the same date but next month you will be charged in 30 days instead.

For 1 year gift the date of expiry will be 360 days since the payment date (I bought a gift today and the end date is 8 August 2023 instead of 13 August 2023).

![image](https://user-images.githubusercontent.com/3112183/184479410-16b0796f-e737-4da0-9708-7a113a0ac4d4.png)

_(note here that I was charged a day before than it was stated in the previous payment message)_

![image](https://user-images.githubusercontent.com/3112183/184479428-66448dff-675b-4f21-aa7f-cd2276b936ca.png)

_(the payment made on 13 Aug 2022 for 1 year premium gift will be expired on 8 August next year)_

![image](https://user-images.githubusercontent.com/3112183/184479607-278c4002-5aed-4a2e-9ba4-c0c41289bad0.png)

_(the app uses different variations of representing 1 year: 1 year, 12 months, but the actual length is less than any of them - 360 days)_

Another problem there is that the app shows the price is US dollars (for gifts) while the actual charge is in a currency of your card (I believe?) instead, which is a bit misleading. I'd personally prefer to be able to select the currency I'd like to be charged in (the card's one or USD). In my case, my bank allows me to have multiple currencies in the account and I can exchange my local currency into USD in a better rate than you provide (or the payment system?). But this is not that critical IMO, just nice to have. Also it might be solved by showing the price in a local currency instead of USD (like it works for monthly subscriptions for example).

I'm really sorry if this is not the best place to raise this kind of issues, but I didn't find any kind of support (free or paid or for premium users to report issues). In this case, I'd really appreciate if you share this feedback with the team and can address it somehow (to avoid misleading and misunderstanding - especially the first image looks like a bug).

### Operating system

Any

### Version of Telegram Desktop

The latest

### Installation source

Static binary from official website

**Comment by timocov** [comment]
_I'm not sure about the mobile payments, but I believe this problem exists only with you're paying via the premium bot (I don't have a mobile subscription for Telegram, but at least for other services it works in way that 1 month is 1 month, 1 year is 1 year, etc)_

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by timocov** [comment]
@Aokromes Many thanks! For anyone interested here is the link https://bugs.telegram.org/c/19755
