### ISSUE TITLE
Telegram freezes when open image in fullscreen - know how to fix

### ISSUE THREAD

**Issue by IgorDuino** [telegramdesktop/tdesktop#24924]
I had the same problem as the author of the original issue.
OS - Ubuntu LTS 22.04 (clean. just installed)
Telegram Desktop installed from snap
After playing with the settings, I noticed that the problem disappears if you remove the checkbox
Advanced -> Performance -> Enable OpenGL rendering for media

_Originally posted by @ilya-fedin in https://github.com/telegramdesktop/tdesktop/issues/7754#issuecomment-669590361_

**Comment by ilya-fedin** [comment]
It apparently means you graphics driver is bugged

**Comment by IgorDuino** [comment]
I just installed ubuntu and selected in the program
Software Updates -> Additional Drivers
"Using NVIDIA driver metapackage from nvidia-driver-515 (proprietary, tested"

But in general it is clear. Apparently this is really not a Telegram Desktop problem

**Comment by ilya-fedin** [comment]
Qt works badly with proprietary drivers. It's weird that this option has a difference though as proprietary drivers are blacklisted by tdesktop code. Can you provide the log.txt?

**Comment by IgorDuino** [comment]
Of course, if you tell me where to get it from)

**Comment by ilya-fedin** [comment]
`viewlogs` should open the directory in the file manager
