### ISSUE TITLE
Window position forcefully moved down after quitting Telegram

### ISSUE THREAD

**Issue by PeterNjeim** [telegramdesktop/tdesktop#24928]
### Steps to reproduce

1. Open Telegram
2. Move the window to any position where the titlebar is at the top of the screen
3. Quit Telegram
4. Open Telegram
5. The Telegram window has been moved down

### Expected behaviour

The Telegram window should retain its position after quitting.

### Actual behaviour

The Telegram window position is moved down after quitting.

### Operating system

Windows 11 21H2 22000.856

### Version of Telegram Desktop

4.1 x64

### Installation source

Static binary from official website

**Comment by ctp9** [comment]
Can confirm - window position has been changed (moved down) and window geometry is no longer remembered upon quitting Telegram.

**Comment by FFreestyleRR** [comment]
Can confirm this on Win 10 21H2 as well with the latest version of Telegram.

Pls fix ASAP.

**Comment by Krendelev** [comment]
It's actually worse: window size becomes smaller with every launch. macOS 11.6

**Comment by PeterNjeim** [comment]
Note that I'm not talking about other issues related to "keep getting bigger" or "keep getting smaller" which is due to scaling, I'm specifically talking about the issue where the window cannot remain at the top of the screen at 100% scaling. Please do not mix these two issues

**Comment by sviperz** [comment]
As a workaround you can enable _Use system window frame_ in Advanced Settings. It preserves window size and positions, at least on Linux.

**Comment by ilya-fedin** [comment]
Fixed on dev branch

**Comment by PeterNjeim** [comment]
> As a workaround you can enable _Use system window frame_ in Advanced Settings. It preserves window size and positions, at least on Linux.

While it does, another issue with it, at least on Windows, is that it makes the top pixel of the window the resizable section, meaning I can't move my cursor to the top and click the X Burton for example, I have move my cursor 1 pixel down.

Regardless, I'll test the dev branch and report back if the issue is resolved on my end.

**Comment by PeterNjeim** [comment]
> Fixed on dev branch

Confirmed fixed on version 4.1.1 x64, thanks
