### ISSUE TITLE
Build with Poetry.. -  Unknown flag: link

### ISSUE THREAD

**Issue by x09** [telegramdesktop/tdesktop#24927]
### Steps to reproduce

 ~/.poetry/bin/poetry run gen_dockerfile |  docker build -t tdesktop:centos_env -
Sending build context to Docker daemon  27.14kB
Error response from daemon: dockerfile parse error line 141: Unknown flag: link

p.s. docker-engine-20.10.14

### Expected behaviour

build process

### Actual behaviour

build proccess failed

### Operating system

Linux

### Version of Telegram Desktop

last

### Installation source

Other (unofficial) source

### Logs

```shell
docker-engine-20.10.14
```

**Comment by ilya-fedin** [comment]
Please look at the command in the instruction carefully. If you don't see the difference anyway, copy the command instead of entering manually.

**Comment by x09** [comment]
x09@new citto $ cd tdesktop/Telegram/build/docker/centos_env
x09@new centos_env $  ~/.poetry/bin/poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: centos_env (0.1.0)

x09@new centos_env $  ~/.poetry/bin/poetry  run gen_dockerfile | docker buildx build -t tdesktop:centos_env -
unknown shorthand flag: 't' in -t
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default
                           "/home/anton/.docker")
  -c, --context string     Name of the context to use to connect to the
                           daemon (overrides DOCKER_HOST env var and
                           default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level
                           ("debug"|"info"|"warn"|"error"|"fatal")
                           (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default
                           "/home/anton/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default
                           "/home/anton/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default
                           "/home/anton/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go/guides/

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/anton/Work/citto/tdesktop/Telegram/build/docker/centos_env/gen_dockerfile.py", line 7, in main
    print(Environment(loader=FileSystemLoader(dirname(__file__))).get_template("Dockerfile").render(
BrokenPipeError: [Errno 32] Broken pipe

**Comment by ilya-fedin** [comment]
Looks like your docker is not new enough and you can't build tdesktop on this system therefore

**Comment by x09** [comment]
What version is needed?

**Comment by ilya-fedin** [comment]
Sorry, but I don't know when this feature was added to Docker. Any version that will accept this command should work I guess.

**Comment by x09** [comment]
> 20.10.15
> 2022-05-05
> This release of Docker Engine comes with updated versions of the compose, buildx, containerd, and runc components, as well as some minor bug fixes.

buildx was added to  20.10.15

p.s. Why are you only using the newest versions when building?
I don't think it's necessary.

**Comment by x09** [comment]
Solved a problem.
buildx - This is an additional plugin. 
Downloaded from https://github.com/docker/buildx/releases/tag/v0.8.2 and put into /usr/lib/docker/cli-plugins/
