### ISSUE TITLE
Emojis are animated, even when "Enable Animations" is disabled

### ISSUE THREAD

**Issue by Pingger** [telegramdesktop/tdesktop#24925]
### Steps to reproduce

1. Go to settings
2. Advanced
3. Disable "Enable Animations"
4. Restart Telegram for good measure
5. Notice that Emojis are still animated

### Expected behaviour

Emojis to not be animated

### Actual behaviour

Emojis are animated

### Operating system

Windows 10, Manjaro 21.3.6 Cinnamon 5.4.9

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
The option is about UI animations, not about content like stickers or emoji.

**Comment by Pingger** [comment]
This option is clearly for ALL Animations, as it is located in "Advanced" > "Performance"

**Comment by ilya-fedin** [comment]
No, you misunderstood that

**Comment by Pingger** [comment]
And by the way: Emojis are part of the UI. Thus: Emoji-Animation should also be disabled

**Comment by ilya-fedin** [comment]
It's content here. Anyone can create emojis.
