### ISSUE TITLE
Use system window frame option not shown

### ISSUE THREAD

**Issue by jakafle** [telegramdesktop/tdesktop#24926]
### Steps to reproduce

1. Launch Telegram 4.1.0.
2. Go to Settings -> advanced
3. There is no "Use system window frame" in the "System integration" option.

### Expected behaviour

The "Use system window frame" option should be shown so that Telegram can use the decorations of the respective desktop environment.

### Actual behaviour

Without the "Use system window frame" option, the app does not have consistent look with the system theme like the earlier versions.

### Operating system

Ubuntu 22.04 (x86_64), GNOME Desktop Environment

### Version of Telegram Desktop

Version 4.1.0

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Yeah, GNOME doesn't provide system decorations to applications anymore, see the discussion at https://gitlab.gnome.org/GNOME/mutter/-/issues/217

**Comment by ThomasLobker** [comment]
Workaround that worked for me:

1. Cleanup any Telegram files on your desktop, assuming you have access to Telegram from your phone
2. Download tsetup.4.0.2.tar.xz from the [releases page](https://github.com/telegramdesktop/tdesktop/releases)
3. Extract and execute Telegram, go to settings and disable the automatic update feature
4. Login to Telegram, go to Settings, Advanced, System integration and enable `Use system window frame`
5. Go to Settings, Notifications and sounds, Native notifications and enable `Use native notifications`
6. Finally go to Settings, Advanced, Version and updates and enable `Update automatically` again

For me Telegram now updated to Telegram 4.1.1 and kept the window frame and native notifications. Hope this helps! And hopefully Telegram will bring back these options in newer versions, so we won't need the workaround.

**Comment by ilya-fedin** [comment]
It was working due to XWayland, GNOME doesn't support that with native Wayland. tdesktop won't revert to native Wayland umless bigger problems are found.

If you want system window frame with newer versions, you have two options:
1. Ask GNOME developers to reconsider their decision of not supporting xdg-decoration (the system window frame Wayland protocol)
2. Switch to X11 session
