### ISSUE TITLE
Option to stop showing HUGE emoji dialog on mouse over

### ISSUE THREAD

**Issue by LexaGV** [telegramdesktop/tdesktop#24932]
### Is your feature request related to a problem?

When I move mouse around text input area and mouse appears above "smile icon", a huge dialog with smiles/emoji selection appears. It's annoying!

### Describe the solution you'd like

Let me first CLICK on smiles icon and only then show this clownish smiles selection.

### Describe alternatives you've considered

There is no alternatives.

### Additional context

Before you do ANY functionality, based on "mouse hover", think 10 times before implement it. It's quite annoying to interact with UI when everything pop-out without your intention. Mouse is FREE TOOL, it's not positioned exactly at one place - user move mouse and eventually hovers some areas - it's normal behaviour of human. But people don't want to see all those limitless functions you hide until mouse appears.
Same related scrollbar - I want to see it ALWAYS! I have no time to put mouse on right edge and wait until you show me where I am. It's NOT A TOY for developers!!! It's tool to scroll window - GET OFF THE SCROLLBAR and show it permanently.

**Comment by Aokromes** [comment]
enable experimental settings on advanced, "show tabbed panel by click"
