### ISSUE TITLE
Stop stupid stickers!

### ISSUE THREAD

**Issue by LexaGV** [telegramdesktop/tdesktop#24931]
### Is your feature request related to a problem?

When I chat in channel or private chat, I do not want to see idiotic stickers! **They are annoying**.

### Describe the solution you'd like

I want checkbox in settings "hide any stickers".

### Describe alternatives you've considered

There is no alternatives. Sticker must be completely removed from my vision.

### Additional context

When you try to amuse teenagers, don't forget that many ADULT PEOPLE chat too and they do not support stupid entertainment.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
