### ISSUE TITLE
run "tdesktop\Telegram\build\prepare\win.bat" error [Question] 

### ISSUE THREAD

**Issue by jmzqwh** [telegramdesktop/tdesktop#24937]
Platform: win x64.
Why I can't build the breakpad? The branch dfcb7b6799 didn't exist, or any other problem?

---------------------------------COMMANDS-LIST----------------------------------
if exist breakpad rmdir /Q /S breakpad
if exist breakpad exit /b 1
git clone https://chromium.googlesource.com/breakpad/breakpad
cd breakpad
git checkout dfcb7b6799
git apply ../patches/breakpad.diff
git clone -b release-1.11.0 https://github.com/google/googletest src/testing
if "%X8664%" equ "x64" (
SET "FolderPostfix=_x64"
) else (
SET "FolderPostfix="
)
cd src\client\windows
gyp --no-circular-check breakpad_client.gyp --format=ninja
cd ..\..
ninja -C out/Debug%FolderPostfix% common crash_generation_client exception_handler
ninja -C out/Release%FolderPostfix% common crash_generation_client exception_handler
cd tools\windows\dump_syms
gyp dump_syms.gyp --format=ninja
cd ..\..\..
ninja -C out/Release%FolderPostfix% dump_syms
--------------------------------------------------------------------------------
Cloning into 'breakpad'...
remote: Total 20598 (delta 15408), reused 20598 (delta 15408)
Receiving objects: 100% (20598/20598), 44.09 MiB | 1.16 MiB/s, done.

Resolving deltas: 100% (15408/15408), done.
Note: switching to 'dfcb7b6799'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at dfcb7b67 Revert "Fix incorrect source file name for inlined frames"
warning: src/build/gyp_breakpad has type 100644, expected 100755
Cloning into 'src/testing'...
remote: Enumerating objects: 24838, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 24838 (delta 19), reused 39 (delta 17), pack-reused 24784
Receiving objects: 100% (24838/24838), 10.64 MiB | 1.71 MiB/s, done.

Resolving deltas: 100% (18366/18366), done.
Note: switching to 'e2239ee6043f73722e7aa812a459f54a28552929'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\TBuild\ThirdParty\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\TBuild\ThirdParty\Python39\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "D:\TBuild\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 2467, in CallGenerateOutputForConfig
    GenerateOutputForConfig(target_list, target_dicts, data, params, config_name)
  File "D:\TBuild\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 1973, in GenerateOutputForConfig
    cl_paths = gyp.msvs_emulation.GenerateEnvironmentFiles(
  File "D:\TBuild\ThirdParty\gyp\pylib\gyp\msvs_emulation.py", line 1056, in GenerateEnvironmentFiles
    raise Exception('"%s" failed with error %d' % (args, popen.returncode))
Exception: "['C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Auxiliary\\Build\\vcvarsall.bat', 'amd64_x86', '&&', 'set']" failed with error 255
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\TBuild\ThirdParty\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\TBuild\ThirdParty\gyp\pylib\gyp\__init__.py", line 552, in script_main
    return main(sys.argv[1:])
  File "D:\TBuild\ThirdParty\gyp\pylib\gyp\__init__.py", line 545, in main
    return gyp_main(args)
  File "D:\TBuild\ThirdParty\gyp\pylib\gyp\__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "D:\TBuild\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 2493, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "D:\TBuild\ThirdParty\Python39\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\TBuild\ThirdParty\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
Exception: "['C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Auxiliary\\Build\\vcvarsall.bat', 'amd64_x86', '&&', 'set']" failed with error 255
[13\16](Libraries\breakpad): FAILED
FAILED

**Comment by ilya-fedin** [comment]
Is this still a problem?
