### ISSUE TITLE
Telegram Desktop doesn't respect "notify about new contacts"

### ISSUE THREAD

**Issue by Zombieff** [telegramdesktop/tdesktop#24942]
### Steps to reproduce

Do nothing

### Expected behaviour

Nothing happens

### Actual behaviour

Dimitry joined Telegram!

### Operating system

Windows, Linux, macOS

### Version of Telegram Desktop

any

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
https://bugs.telegram.org/c/65
