### ISSUE TITLE
[Feature Request] Replied messages in channels

### ISSUE THREAD

**Issue by WebPajooh** [telegramdesktop/tdesktop#24944]
### Is your feature request related to a problem?

No, actually.

### Describe the solution you'd like

In groups, we can right click on a message and click on `View n replies` to see all replies on the message.
It will be good to have **such a feature in channels** as well!

### Describe alternatives you've considered

Add a menu item for doing the same thing in channels.

**Comment by john-preston** [comment]
@WebPajooh I don't understand, you want to read replies to a message in a channel from the same channel? This happens, like, never?

**Comment by WebPajooh** [comment]
![image](https://user-images.githubusercontent.com/17279395/185137521-8cc81fa3-9289-4d80-8c76-57a3d69e4388.png)

I want to have this in the channels to see the replied messages on a specific message.

**Comment by WebPajooh** [comment]
Did you understand me, John?

**Comment by WebPajooh** [comment]
Did you understand me, @john-preston ?

**Comment by john-preston** [comment]
@WebPajooh No. This button in group shows other members of group replying to that message. The messages inside the same group, not somewhere outside. So in case of channels this would mean other **same channel** posts, _replying_ to this channel post. I don't see any sense in that, almost nobody almost never make a reply posts to their channel posts in the same channel. Why would they make them.
