### ISSUE TITLE
[Linux] Not using tray icon from icon theme

### ISSUE THREAD

**Issue by PoisonFrog** [telegramdesktop/tdesktop#24948]
### Steps to reproduce

1. Install icon theme that has a tray icon for telegram-desktop and activate it
2. Open telegram

### Expected behaviour

Telegram using the tray icon from theme like it was using some versions ago

### Actual behaviour

Telegram is not using the proper tray icon

### Operating system

Arch Linux

### Version of Telegram Desktop

4.1.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
> Other (unofficial) source

Can you check the official binary?

**Comment by PoisonFrog** [comment]
> > Other (unofficial) source
> 
> Can you check the official binary?

I got it from Arch Linux official repositories.

**Comment by ilya-fedin** [comment]
> I got it from Arch Linux official repositories.

It's official to Arch Linux, but not to Telegram. The only official installation sources are at https://desktop.telegram.org

**Comment by PoisonFrog** [comment]
> > I got it from Arch Linux official repositories.
> 
> It's official to Arch Linux, but not to Telegram. The only official installation sources are at https://desktop.telegram.org

Ohh, didn't know about that. Getting the tarball from telegram website actually fixed the issue.. Thank you!
