### ISSUE TITLE
[Feature Request] Some Scroll bar customization please !

### ISSUE THREAD

**Issue by iBeny** [telegramdesktop/tdesktop#24947]
### Is your feature request related to a problem?

The vertical scrollbar in the message pane is WAY TOO thin ! and the scroll button is WAY TOO difficult to see on dark backgrounds. Please add customization section for the scrollbar in the parameter section to customize the width/color of the scrollbar AND the opacity of it AND... color/opacity of the scroll **BUTTON**.

Many thanks
iBeny

### Describe the solution you'd like

Add a customization section in the parameter section for the scrollbar & button 

### Describe alternatives you've considered

I don't see any alternative...

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/17367
