### ISSUE TITLE
[Bug] show another unicode symbol

### ISSUE THREAD

**Issue by evgenstein** [telegramdesktop/tdesktop#24951]
### Steps to reproduce

1. Copy symbol with code U+2661 from browser and paste in mobile telegram (ios) eg. in Saved Message
2. Send message
3. Open Saved messages on desktop telegram

### Expected behaviour

You see symbol with code U+2661

### Actual behaviour

You see symbol with code U+2261

### Operating system

Windows

### Version of Telegram Desktop

4.1.1 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This is a bug in the Tahoma font provided by Windows
