### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by lshaton** [telegramdesktop/tdesktop#24950]
### Is your feature request related to a problem?

There is no way to enlarge the sticker to see it before sending
![Screenshot_26](https://user-images.githubusercontent.com/10957561/185347332-efa8f930-64f0-4371-9d2b-675956b708df.jpg)
.

### Describe the solution you'd like

Make large picture when one hover cursor over the sticker.

### Describe alternatives you've considered

Make large picture when one right click over the sticker.

**Comment by john-preston** [comment]
@lshaton Press and hold left mouse button.

**Comment by lshaton** [comment]
Thank you!


________________________________
