### ISSUE TITLE
[Question] i cant see more witch users have bean seen on my group

### ISSUE THREAD

**Issue by senkron24** [telegramdesktop/tdesktop#24955]
hi 
i have a mini group with 100 peaple 
befor i can see my post witch peaple have bean seen and with user have give a reackt 
bud now i can only the how many peaple show it thad all no names no reackt name i cant the witch peaple give me tomsup example the name missing 

can any budy help to slove this for me its very importent 

kind regarts

**Comment by ilya-fedin** [comment]
It's probably a good sign if your group doesn't have witches anymore? Or the witches are still here, just don't have beans anymore?
