### ISSUE TITLE
Clean history chat deletes entire group

### ISSUE THREAD

**Issue by zakiloki0** [telegramdesktop/tdesktop#24958]
I just discovered that if I delete the message history in a group, it automatically deletes the group. This is either a bug or done on purpose because it doesn't make much sense.

**Comment by Neurotoxin001** [comment]
API issue, not only tdesktop
https://bugs.telegram.org/c/10680

**Comment by Neurotoxin001** [comment]
Seems like it's API issue (not only tdesktop affected)
https://bugs.telegram.org/c/10680
