### ISSUE TITLE
Own messages being shown at the left

### ISSUE THREAD

**Issue by Toshik** [telegramdesktop/tdesktop#24957]
### Steps to reproduce

1. open any chat or group
2. post a message

### Expected behaviour

Own messages should be shown at the right side

### Actual behaviour

Own messages are being shown at the left side

### Operating system

Windows 11

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

**Comment by Toshik** [comment]
![image](https://user-images.githubusercontent.com/170579/185610787-8e4d6a5e-5b04-4f84-82b3-f5d9e1f25c3c.png)
It seems behavior depends on window width

![image](https://user-images.githubusercontent.com/170579/185610846-c0589e40-f22d-4e2b-8e60-797bfe97298f.png)

**Comment by Aokromes** [comment]
disable adaptative layout.
