### ISSUE TITLE
Web App not showing up on ubuntu i3

### ISSUE THREAD

**Issue by WhatIsThisBreakfast** [telegramdesktop/tdesktop#24953]
### Steps to reproduce

1. I downloaded telegram-desktop from here: [](https://github.com/telegramdesktop/tdesktop/releases/tag/v4.1.0 ). 
2. Install libwebkit2gtk-4.1-0/jammy-updates,jammy-security,now 2.36.6-0ubuntu0.22.04.1 amd64
3. Running /tsetup.4.1.0/Telegram/Telegram
4. Open Web App  durger king bot

### Expected behaviour

![image](https://user-images.githubusercontent.com/90184510/185449506-87855290-05e4-4de9-82c8-463c5e429d02.png)

### Actual behaviour

I get this result. Just a white window and a message in the console "Could not determine the accessibility bus address"
![telegram-error](https://user-images.githubusercontent.com/90184510/185448804-d8ea4d24-3fc9-468c-8506-58ddfbe91c02.png)

### Operating system

ubuntu 22.04 LTS with "i3" window manager

### Version of Telegram Desktop

4.1.0

### Installation source

Static binary from official website

### Logs

```shell
In ~/.local/share/TelegramDesktop/DebugLog/log_*_*.txt:

[21:46:55.257 00-0004272] BotWebView Error: Could not parse """".
[21:46:55.257 00-0004273] BotWebView Error: Could not parse """".
[21:46:55.290 00-0004274] BotWebView Error: Could not parse """".

In terminal:
Could not determine the accessibility bus address
```

**Comment by ilya-fedin** [comment]
Please report to i3 first if you can't reproduce on something mainstream like KDE Plasma. If they will say it's a bug in Telegram and say what Telegram can do, feel free to open a new issue.

**Comment by Aokromes** [comment]
better, if they say what telegram can do about that, post here again and i will reopen.

**Comment by WhatIsThisBreakfast** [comment]
> better, if they say what telegram can do about that, post here again and i will reopen.

They didn't help me
[https://github.com/i3/i3/issues/5090](https://github.com/i3/i3/issues/5090)

What should I do?

i forgot to attach journalctl
<pre>
авг 19 18:03:14 egorka-P5K WebKitWebProces[32702]: Locale not supported by C library.
                                                              Using the fallback 'C' locale.
авг 19 18:03:14 egorka-P5K WebKitNetworkPr[32699]: GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox
авг 19 18:03:14 egorka-P5K audit[32702]: SECCOMP auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="WebKitWebProces" exe="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKit>
авг 19 18:03:14 egorka-P5K kernel: audit: type=1326 audit(1660914194.306:167): auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="WebKitWebProces" exe="/usr/lib/x86_64-l>
авг 19 18:03:14 egorka-P5K audit[32702]: SECCOMP auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKit>
авг 19 18:03:14 egorka-P5K audit[32702]: SECCOMP auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKit>
авг 19 18:03:14 egorka-P5K audit[32702]: SECCOMP auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKit>
авг 19 18:03:14 egorka-P5K audit[32702]: SECCOMP auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKit>
авг 19 18:03:14 egorka-P5K audit[32702]: SECCOMP auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKit>
авг 19 18:03:14 egorka-P5K kernel: audit: type=1326 audit(1660914194.490:168): auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-l>
авг 19 18:03:14 egorka-P5K kernel: audit: type=1326 audit(1660914194.490:169): auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-l>
авг 19 18:03:14 egorka-P5K kernel: audit: type=1326 audit(1660914194.490:170): auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-l>
авг 19 18:03:14 egorka-P5K kernel: audit: type=1326 audit(1660914194.490:171): auid=1000 uid=1000 gid=1000 ses=9 subj=? pid=32702 comm="eadedCompositor" exe="/usr/lib/x86_64-l>
авг 19 18:03:14 egorka-P5K xdg-desktop-por[31148]: Realtime error: Could not map pid: Mapping pids is not supported.
авг 19 18:03:14 egorka-P5K audit[32702]: AVC apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/sys/devices/virtual/dmi/id/chassis_type>
авг 19 18:03:14 egorka-P5K WebKitWebProces[32702]: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied
авг 19 18:03:14 egorka-P5K audit[32702]: AVC apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/sys/firmware/acpi/pm_profile" pid=32702>
авг 19 18:03:14 egorka-P5K WebKitWebProces[32702]: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
авг 19 18:03:18 egorka-P5K audit[32685]: AVC apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/proc/zoneinfo" pid=32685 comm="Pressure>
авг 19 18:03:18 egorka-P5K audit[32685]: AVC apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slic>
авг 19 18:03:18 egorka-P5K audit[32685]: AVC apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slic>
авг 19 18:03:18 egorka-P5K audit[32685]: AVC apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slic>
</pre>

**Comment by WhatIsThisBreakfast** [comment]
I found one more log
<pre>
(process:37581): dconf-CRITICAL **: 21:09:36.140: unable to create directory '/run/user/0/snap.telegram-desktop/dconf': Permission denied.  dconf will not work properly.

(process:37581): dconf-CRITICAL **: 21:09:36.141: unable to create directory '/run/user/0/snap.telegram-desktop/dconf': Permission denied.  dconf will not work properly.

(process:37581): dconf-CRITICAL **: 21:09:36.141: unable to create directory '/run/user/0/snap.telegram-desktop/dconf': Permission denied.  dconf will not work properly.

(process:37581): dconf-CRITICAL **: 21:09:36.142: unable to create directory '/run/user/0/snap.telegram-desktop/dconf': Permission denied.  dconf will not work properly.

(process:37581): dconf-CRITICAL **: 21:09:36.142: unable to create directory '/run/user/0/snap.telegram-desktop/dconf': Permission denied.  dconf will not work properly.

(process:37581): dconf-CRITICAL **: 21:09:36.154: unable to create directory '/run/user/0/snap.telegram-desktop/dconf': Permission denied.  dconf will not work properly.

(process:37581): dconf-CRITICAL **: 21:09:36.155: unable to create directory '/run/user/0/snap.telegram-desktop/dconf': Permission denied.  dconf will not work properly.

(process:37581): dconf-CRITICAL **: 21:09:36.156: unable to create directory '/run/user/0/snap.telegram-desktop/dconf': Permission denied.  dconf will not work properly.

(process:37581): dconf-CRITICAL **: 21:09:36.156: unable to create directory '/run/user/0/snap.telegram-desktop/dconf': Permission denied.  dconf will not work properly.

(process:37581): dconf-CRITICAL **: 21:09:36.157: unable to create directory '/run/user/0/snap.telegram-desktop/dconf': Permission denied.  dconf will not work properly.

</pre>

**Comment by ilya-fedin** [comment]
> What should I do?

If you checked with mainstream DE and you're sure it's i3-specific, you should been mention that in the i3 bug report. If they don't want to help anyway, switch to mainstream DE, what to say.
If you checked with mainstream DE and it doesn't work on it as well, you should been mention that here.
If you haven't checked with mainstream DE, you should check.

**Comment by Airblader** [comment]
> If they don't want to help anyway, switch to mainstream DE, what to say.

It's funny you don't see the hypocrisy in that statement after you closed this initial bug report immediately just because it works on KDE. 

KDE is a DE. i3 is a window manager. Please don't confuse those two.

**Comment by ilya-fedin** [comment]
If it doesn't work as-is, there's nothing actionable as tdesktop project doesn't have low-level X11 experts, so no one would be able to help you. So the issue is closed.

**Comment by WhatIsThisBreakfast** [comment]
> > What should I do?
> 
> If you checked with mainstream DE and you're sure it's i3-specific, you should've been mention that in the i3 bug report. If they don't want to help anyway, switch to mainstream DE, what to say. If you checked with mainstream DE and it doesn't work on it as well, you should've been mention that here. If you haven't checked with mainstream DE, you should check.


I installed i3wm on kde using this guide: [https://github.com/heckelson/i3-and-kde-plasma](https://github.com/heckelson/i3-and-kde-plasma)

Tried to run WebApp on such setup but got bad result again. 
When running normal KDE startup with plasma-x11 everything works fine

**Comment by WhatIsThisBreakfast** [comment]
The problem is with the window manager

**Comment by Airblader** [comment]
DEs behave very differently sometimes when you use a different WM with them. Running something like Openbox outside of a DE would be a better test.

**Comment by ilya-fedin** [comment]
It works flawlessly only on Windows and macOS. On Linux there's a zoo as always and Qt doesn't seem to work ok with all that zoo 😔

**Comment by ilya-fedin** [comment]
Maybe the feature should have a whitelist of known working&tested environments rather than a blacklist...

**Comment by WhatIsThisBreakfast** [comment]
> Иногда DE проводил себя по-разному, когда вы присутствовали с другими WM. Запуск чего-то вроде Openbox DE был бы самым лучшим тестом.

I tried openbox and awesome. WebApp shows empty output window (null). Looks like WebApps only work with KDE Plasma

**Comment by Airblader** [comment]
Which means it's not a window manager issue.

**Comment by ilya-fedin** [comment]
It shows really empty window or it prints `(null)`? The latter is printed by webkit2gtk in case of networking problems usually.

**Comment by ilya-fedin** [comment]
> Which means it's not a window manager issue.

Maybe kwin is the only WM here that works correctly with window embedding

**Comment by WhatIsThisBreakfast** [comment]
> It works flawlessly only on Windows and macOS. On Linux there's a zoo as always and Qt doesn't seem to work ok with all that zoo pensive

I am new to linux. I like to separate work space and leisure space as much as possible. So I use windows and linux on the same computer. Therefore, I have been trying for three days to achieve the display of the Telegram WebApp

**Comment by WhatIsThisBreakfast** [comment]
> It shows really empty window or it prints `(null)`? The latter is printed by webkit2gtk in case of networking problems usually.

He prints (null)

**Comment by WhatIsThisBreakfast** [comment]
I installed clean openbox and awesome

**Comment by ilya-fedin** [comment]
> He prints (null)

Do you check on the same machine (VM)? Do you remove any packages in process?

**Comment by Airblader** [comment]
> > Which means it's not a window manager issue.
> 
> Maybe kwin is the only WM here that works correctly with window embedding

I don't see that as probable. My guess is that whatever this feature does requires some piece of infrastructure that the DE provides that isn't related to window management.

But for this someone would have to debug what the actual error is that is happening.

**Comment by WhatIsThisBreakfast** [comment]
> > He prints (null)
> 
> Do you check on the same machine (VM)? Do you remove any packages in process?

Yes. No

**Comment by WhatIsThisBreakfast** [comment]
I don't remove packages

**Comment by ilya-fedin** [comment]
Do you have glib-networking installed?

**Comment by WhatIsThisBreakfast** [comment]
> > > Which means it's not a window manager issue.
> > 
> > 
> > Maybe kwin is the only WM here that works correctly with window embedding
> 
> I don't see that as probable. My guess is that whatever this feature does requires some piece of infrastructure that the DE provides that isn't related to window management.
> 
> But for this someone would have to debug what the actual error is that is happening.

I had an idea to fully build tdesktop p and run it in debug mode, but I'm postponing this idea until the last

**Comment by ilya-fedin** [comment]
> My guess is that whatever this feature does requires some piece of infrastructure that the DE provides that isn't related to window management.

Given that it's known now that it prints (null), that seems more likely

**Comment by ilya-fedin** [comment]
I wonder why the screenshots don't have that...

**Comment by WhatIsThisBreakfast** [comment]
> Do you have glib-networking installed?

![image](https://user-images.githubusercontent.com/90184510/185703373-95751165-a6db-4f99-8e5f-3c467e977a6e.png)
Yes!

**Comment by WhatIsThisBreakfast** [comment]
> > My guess is that whatever this feature does requires some piece of infrastructure that the DE provides that isn't related to window management.
> 
> Given that it's known now that it prints (null), that seems more likely

This is not on i3

**Comment by WhatIsThisBreakfast** [comment]
All screens from i3

**Comment by Airblader** [comment]
Given that there's no shred of evidence that this is window management related but both reason to believe and evidence that it isn't, I'm going to unsubscribe from this issue as it's a bit too chatty for me.

Feel free to tag me back in should anything arise that hints towards window management issues.

**Comment by ilya-fedin** [comment]
Do you still try to run Telegram with sudo? That won't give you anything good for sure. But will give any kinds of bugs due to inaccessible sockets in XDG_RUNTIME_DIR.

**Comment by WhatIsThisBreakfast** [comment]
> Do you still try to run Telegram with sudo? That won't give you anything good for sure. But will give any kinds of bugs due to inaccessible sockets in XDG_RUNTIME_DIR.

No, I don't run telegram via sudo. Just installed with a team. The only use was when installing
<pre>
sudo snap install telegram-desktop
</pre>

**Comment by ilya-fedin** [comment]
Well, I see sudo on the screenshot, I also see this in your logs

> (process:37581): dconf-CRITICAL **: 21:09:36.140: unable to create directory '/run/user/0/snap.telegram-desktop/dconf': Permission denied.  dconf will not work properly.

uid 0 = root

**Comment by ilya-fedin** [comment]
I'd ask to try the binary. Maybe snap doesn't have something.

**Comment by WhatIsThisBreakfast** [comment]
> Well, I see sudo on the screenshot, I also see this in your logs
> 
> > (process:37581): dconf-CRITICAL **: 21:09:36.140: unable to create directory '/run/user/0/snap.telegram-desktop/dconf': Permission denied.  dconf will not work properly.
> 
> uid 0 = root

at this point I tried to run via sudo. I tried a lot

I ran the binary from github. The result is the same

**Comment by WhatIsThisBreakfast** [comment]
So far, the only place where WebApp has worked is KDE Plasma

**Comment by ilya-fedin** [comment]
How do you run your session when it work and when it doesn't?

**Comment by WhatIsThisBreakfast** [comment]
> How do you run your session when it works and when it doesn't?

All from gdm3

**Comment by WhatIsThisBreakfast** [comment]
I'm trying sddm. Still only works on Plasms

**Comment by ilya-fedin** [comment]
I mean, what do you change? The i3-and-kde-plasma repo has multiple guides, I'm not sure which one exactly you follow. If you still follow it.

**Comment by WhatIsThisBreakfast** [comment]
> I mean, what do you change? The i3-and-kde-plasma repo has multiple guides, I'm not sure which one exactly you follow. If you still follow it for `(null)`.

Web Apps only work on pure KDE Plasma. This guide has not yielded any results.

**Comment by ilya-fedin** [comment]
I already heard that. Not sure why repeat.

**Comment by WhatIsThisBreakfast** [comment]
> I already heard that. Not sure why you repeat.

I'm sorry, I just want to say that this guide(i3-and-kde-plasma repo) is useless for me.
I only get null on openbox and awesome. On any version of i3wm I get a clean window

**Comment by ilya-fedin** [comment]
What do you change in your boot process to boot openbox/awesome?

**Comment by WhatIsThisBreakfast** [comment]
> 
> What do you change in your boot process to boot openbox/awesome?

Nothing. I install and run immediately

**Comment by WhatIsThisBreakfast** [comment]
> What do you change in your boot process to boot openbox/awesome rather than Plasma?

I select them on the login screen

**Comment by ilya-fedin** [comment]
Excuse me? In order to run, you should restart your session and something change in order to not to get into Plasma again.

**Comment by WhatIsThisBreakfast** [comment]
![image](https://user-images.githubusercontent.com/90184510/185706475-4d03b199-39f1-41fa-a610-8ea98b9d667b.png)
Here

**Comment by ilya-fedin** [comment]
> I select them on the login screen

Ah, ok. Can you send the files from /usr/share/xsessions?

**Comment by WhatIsThisBreakfast** [comment]
> > I select them on the login screen
> 
> Ah, ok. Can you send the files from /usr/share/xsessions?

Okay, second

**Comment by WhatIsThisBreakfast** [comment]
[xsession.zip](https://github.com/telegramdesktop/tdesktop/files/9385422/xsession.zip)

**Comment by ilya-fedin** [comment]
The following info will also be helpful:
1. `env` from Plasma
2. `env` from openbox/awesome
3. `systemctl --user show-environment` from Plasma
3. `systemctl --user show-environment` from openbox/awesome

You can redirect the output to files with bash. I'd like to process those files with `sort` and `diff` then.

**Comment by ilya-fedin** [comment]
That's weird, I don't see Plasma session...

> Yes. No

At least one of those answers seem to be false?

**Comment by WhatIsThisBreakfast** [comment]
Oh, sorry
I no longer have plasma. I have reinstalled ubuntu. Now I will install plasma

**Comment by WhatIsThisBreakfast** [comment]
I didn't change the plasma session when the webapps were running

**Comment by ilya-fedin** [comment]
Use the `kubuntu-desktop` package. Not the `plasma-desktop` one.

**Comment by WhatIsThisBreakfast** [comment]
> kubuntu-desktop

Okay, I'll install it now.

**Comment by WhatIsThisBreakfast** [comment]
> That's weird, I don't see Plasma session...
> 
> > Yes. No
> 
> At least one of those answers seem to be false?


No, all answers are correct.

**Comment by ilya-fedin** [comment]
Just checked Openbox on my KDE Neon VM:
![изображение](https://user-images.githubusercontent.com/17829319/185708601-e40767c9-3341-40a5-badb-1076141a01ed.png)
It's based on Ubuntu 20.04 though, maybe something is wrong with 22.04...

**Comment by WhatIsThisBreakfast** [comment]
> KDE Neon VM:

clean openbox?

**Comment by ilya-fedin** [comment]
Yeah

**Comment by WhatIsThisBreakfast** [comment]
> Yeah

Okay, now I will send what you asked and try to install ubuntu 20.04. If it doesn't work, I'll install KDE Venom

**Comment by ilya-fedin** [comment]
It's reproducible with the snap though. Apparently because it uses packages from 22.04.

**Comment by WhatIsThisBreakfast** [comment]
> It's reproducible with the snap though. Apparently because it uses packages from 22.04.

do not quite understand

**Comment by ilya-fedin** [comment]
I see the snap package tries to make the request with the ProxyResolver portal. As openbox doesn't provide any portal, network request fails and webview displays `(null)`.

**Comment by ilya-fedin** [comment]
> do not quite understand

Snap package is built on core22 runtime that is based on Ubuntu 22.04 packages.

**Comment by ilya-fedin** [comment]
Oh, webview in snap package doesn't actually work at all. The problem is not that openbox doesn't provide portals, the problem is the portal forbids the ProxyResolver request for snap. So this feature is totally broken in snap not depending on the environment.

**Comment by ilya-fedin** [comment]
> авг 19 18:03:14 egorka-P5K WebKitNetworkPr[32699]: GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox

This is the line indicating ProxyResolver request failed and therefore network request as well.

**Comment by ilya-fedin** [comment]
So it's apparently a bug in one of those ubuntu packages:
1. webkit2gtk
2. libsoup
3. xdg-desktop-portal

**Comment by ilya-fedin** [comment]
Ok, looking at the xdg-desktop-portal code, this seem to be a snapd bug. It doesn't provide information to xdg-desktop-portal that the snap has network access.
https://github.com/flatpak/xdg-desktop-portal/blob/90d041a2de5add60b32b4d26b857c20beeb43c4d/src/proxy-resolver.c#L64

**Comment by WhatIsThisBreakfast** [comment]
> So it's apparently a bug in one of those ubuntu packages:
> 
> 1. webkit2gtk
> 2. libsoup
> 3. xdg-desktop-portal

I found information about the problem with the portal

[https://forum.snapcraft.io/t/help-gdbus-error-this-call-is-not-available-inside-the-sandbox/29969](https://forum.snapcraft.io/t/help-gdbus-error-this-call-is-not-available-inside-the-sandbox/29969)

**Comment by WhatIsThisBreakfast** [comment]
> Ok, looking at the xdg-desktop-portal code, this seem to be a snapd bug. It doesn't provide information to xdg-desktop-portal that the snap has network access. https://github.com/flatpak/xdg-desktop-portal/blob/90d041a2de5add60b32b4d26b857c20beeb43c4d/src/proxy-resolver.c#L64

Oh, sounds like a big problem. Is it solvable?

**Comment by ilya-fedin** [comment]
> I found information about the problem with the portal
> 
> https://forum.snapcraft.io/t/help-gdbus-error-this-call-is-not-available-inside-the-sandbox/29969

Oh, so we need the network-status plug

**Comment by WhatIsThisBreakfast** [comment]
> > I found information about the problem with the portal
> > https://forum.snapcraft.io/t/help-gdbus-error-this-call-is-not-available-inside-the-sandbox/29969
> 
> Oh, so we need the network-status plug

I googled this option but did not understand how to do it. Obviously I googled wrong, I admit

**Comment by ilya-fedin** [comment]
You can't do that. Without rebuilding the snap at least.

**Comment by WhatIsThisBreakfast** [comment]
env files still needed?

**Comment by ilya-fedin** [comment]
> env files still needed?

Well, the binary should still work, if it doesn't work, then yeah

**Comment by WhatIsThisBreakfast** [comment]
> > env files still needed?
> 
> Well, the binary should still work, if it doesn't work, then yeah

Wow, I tried to run the openbox binary and it worked for the webapp! Previously, I tried to run the binary only on i3. On openbox and awesome only snap version

**Comment by WhatIsThisBreakfast** [comment]
the conclusion is that I will not be able to use i3?

**Comment by ilya-fedin** [comment]
:rofl:

**Comment by ilya-fedin** [comment]
> the conclusion is that I will not be able to use i3?

Apparently it's the time to tag @Airblader and say that you mis-tested and it works on openbox/awesome?

**Comment by WhatIsThisBreakfast** [comment]
> > the conclusion is that I will not be able to use i3?
> 
> Apparently it's the time to tag @Airblader and say that you mis-tested and it works on openbox/awesome?

Yes!

**Comment by WhatIsThisBreakfast** [comment]
but the main question was about i3. Can I forget about this window manager?

**Comment by ilya-fedin** [comment]
Well, wait for @Airblader? He's (one of?) i3 developer.

**Comment by WhatIsThisBreakfast** [comment]
> Well, wait for @Airblader? He's an i3 developer.

okay,  thanks a lot

**Comment by Airblader** [comment]
I think easiest would be to create a new issue in i3. It'd be great if you could mention

1. This issue (just linking to it)
2. That you have tried it in Openbox and Awesome and it works there
3. Maybe some kind of summary on what you have found out on what it is that doesn't work (I don't know this app at all so I barely understand what it is that doesn't work)

Since you already had a log file etc in the original issue you can just use the same one again.
