### ISSUE TITLE
webrtc threads still running after voice call was done

### ISSUE THREAD

**Issue by tg2sipfork** [telegramdesktop/tdesktop#24954]
### Steps to reproduce

1. rug tdesktop and run ps
2. make call - it will add webrtc threads
3. hungup call - webrtc threads still will be running

**### Where is the webrtc exit \ close \ kill threads  code in tdesktop?**

### Expected behaviour

webrtc threads will stoped \ killed

### Actual behaviour

```
   PID   SPID TTY          TIME CMD
345146 345182 pts/0    00:00:00 tg_client
345146 345426 pts/0    00:00:00 WebRTC-Manager
345146 345427 pts/0    00:00:00 tgc-media
345146 345428 pts/0    00:00:00 tgc-work
345146 345430 pts/0    00:00:00 rtc-low-prio
345146 345431 pts/0    00:00:00 TaskQueuePacedS
345146 345432 pts/0    00:00:00 rtp_send_contro
345146 345433 pts/0    00:00:00 ModuleProcessTh
345146 345434 pts/0    00:00:00 AudioEncoder
345146 345447 pts/0    00:00:00 DecodingQueue
345146 345448 pts/0    00:00:00 IncomingVideoSt
```

### Operating system

linux

### Version of Telegram Desktop

latest

**Comment by john-preston** [comment]
@tgcallsproject They're spawned forever, the threads.

**Comment by john-preston** [comment]
@tgcallsproject In legacy calls through libtgvoip they were stopped, in tgcalls through webrtc they weren’t.

**Comment by john-preston** [comment]
@tgcallsproject Yes, this is intended.
