### ISSUE TITLE
Trying to Open Media Cause A Blank Window to Come Up on ChromeOS Linux Container

### ISSUE THREAD

**Issue by windowz414** [telegramdesktop/tdesktop#24965]
### Steps to reproduce

Open any type of visual media (an image or video) sent in a chat.

### Expected behaviour

The media opens up just fine on Telegram's own media previewer.

### Actual behaviour

A blank window comes up with this message being logged on terminal;
```
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
```

### Operating system

Debian GNU/Linux 11 (bullseye) on Chrome OS x86_64 (DE is named "Generic" in neofetch)

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Apparently your device has problematic OpenGL drivers?

**Comment by windowz414** [comment]
> Apparently your device has problematic OpenGL drivers?

I don't really think so, because all other apps; whether it's Discord or even a full-blown browser like Opera; works as perfectly as it would on a regular Debian install.

**Comment by ilya-fedin** [comment]
Are you sure they're using OpenGL?

**Comment by ilya-fedin** [comment]
Browsers usually have advanced blacklists. Discord is based on browser, too.

**Comment by windowz414** [comment]
> Are you sure they're using OpenGL?

Quoting Arch Linux "Chrome OS Devices/Crostini" page,

> *Audio (in/out) & OpenGL are supported, but USB devices support in only partially supported and development is still in progress.*

Means they do support use of OpenGL, which in this case I made sure I was using.

> Browsers usually have advanced blacklists. Discord is based on browser, too.

Well, I can't say anything for that part though... 😅

**Comment by ilya-fedin** [comment]
I bet OpenGL is the problem, try to run Telegram with `LIBGL_ALWAYS_SOFTWARE=1`

**Comment by windowz414** [comment]
> I bet OpenGL is the problem, try to run Telegram with `LIBGL_ALWAYS_SOFTWARE=1`

Sure, let's see how it goes.

**Comment by windowz414** [comment]
@ilya-fedin, same logs dropped, but also noticed this one being outputted on terminal as well;
```
qt.qpa.wayland: Ignoring unexpected wl_surface.enter received for output with id: 7 screen name: "Screen5" screen model: "06A5" This is most likely a bug in the compositor.
```

Additionally, a visual change is that the taskbar's place is no longer transparent but completely white, that also includes the cursor itself as well, which turns into a white full square.

**Comment by ilya-fedin** [comment]
At that point I think there's some incompatibility between Qt's and ChromeOS Wayland implementations :(

**Comment by windowz414** [comment]
> At that point I think there's some incompatibility between Qt's and ChromeOS Wayland implementations :(

Then I think I should raise this to Chromebook support instead, right?

**Comment by ilya-fedin** [comment]
Try doing that. Reporting this to Qt side would be non-trivial as they would require a minimal reproducible example and the media viewer widget is a very convoluted widget, so it would be nearly impossible to find the bugged piece to create such example.

**Comment by windowz414** [comment]
> Try doing that. Reporting this to Qt side would be non-trivial as they would require a minimal reproducible example and the media viewer widget is a very convoluted widget, so it would be nearly impossible to find the bugged piece to create such example.

Roger that. Thank you for the help so far! I'm now launching the feedback tool and reporting to Google with a link to this issue thread.

Good luck with your work in general by the way!

**Comment by windowz414** [comment]
Little update on this: [I also posted on /r/Crostini about this](https://www.reddit.com/r/Crostini/comments/wuw7p0/telegram_desktop_cannot_view_images_full_screen/) and [I've been told to disable OpenGL rendering for media from Telegram Settings > Advanced](https://www.reddit.com/r/Crostini/comments/wuw7p0/comment/ilbx6cx/). Never have I thought it would work, and it works just perfect!

CC: @ilya-fedin (CC'ing just to ensure you're updated about this as well.)

**Comment by ilya-fedin** [comment]
Hmm, I wonder whether `LIBGL_ALWAYS_SOFTWARE=1` works on Chrome OS at all? If it does, `es2_info | grep GL_RENDERER` should return llvmpipe or swrast. And if it works, it means there's some incompatibility between Qt's OpenGL Wayland integration and Chrome OS Wayland compositor, so it doesn't work even with llvmpipe driver that is known to work perfectly on real Linux machines...

**Comment by ilya-fedin** [comment]
> so I think it's just not implemented by Qt developers at all

Not implemented what?

**Comment by ilya-fedin** [comment]
LIBGL_ALWAYS_SOFTWARE=1 is a mesa's variable, not Qt's

**Comment by ilya-fedin** [comment]
if you don't enter the variable at the beginning of the command, but as a separate command, you should `export` it

**Comment by windowz414** [comment]
> if you enter the variable not at the beginning of the command (`LIBGL_ALWAYS_SOFTWARE=1 ./Telegram`, `LIBGL_ALWAYS_SOFTWARE=1 es2_info | grep GL_RENDERER`), but as a separate command, you should `export` it (`export LIBGL_ALWAYS_SOFTWARE=1`)

Well, I launched a new shell since I closed existing when running the `es2_info` command, my bad! Let me just `export` and see what I get again.

**Comment by windowz414** [comment]
Now here's the actual result: llvmpipe is used.
```
kobayashiberu@penguin:~$ LIBGL_ALWAYS_SOFTWARE=1 es2_info | grep GL_RENDERER
GL_RENDERER: llvmpipe (LLVM 11.0.1, 256 bits)
```

**Comment by ilya-fedin** [comment]
I wonder whether you set the variable when testing with Telegram :D

**Comment by windowz414** [comment]
> I wonder whether you set the variable when testing with Telegram :D

xD I mean I did set it when launching Telegram, exactly with this command;
```
kobayashiberu@penguin:~$ LIBGL_ALWAYS_SOFTWARE=1 Telegram/Telegram
```

P.S I have `Telegram` and `Updater` executables extracted at `~/Telegram`, that's why I run it like this when I need to launch from shell.

**Comment by windowz414** [comment]
> So it's apparently a problem with compatibility between Qt's EGL Wayland integration and Chrome OS Wayland compositor

And since it works all fine on regular Linux installs, I have done the right choice by raising it to Google by using Feedback tool. Phew, that's a relief at least...
