### ISSUE TITLE
Window keeps being dragged after letting go of left mouse button

### ISSUE THREAD

**Issue by soypat** [telegramdesktop/tdesktop#24969]
### Steps to reproduce

1. Open any telegram desktop window (can be before logging in)
2. Left click and begin dragging window across screen (click on telegram top bar)
3. Let go of left mouse button

### Expected behaviour

Window stops being dragged

### Actual behaviour

Window keeps being dragged across screen until left or right mouse button is clicked.

If right mouse button is clicked window stops being dragged but mouse cursor on screen remains in drag mode (appears as a dot with four arrows pointing in cardinal directions).

### Operating system

Linux Mint 21 XFCE on amd64/x86 (replicated on various computers)

### Version of Telegram Desktop

4.0.2

### Installation source

Static binary from official website or flatpack

**Comment by ilya-fedin** [comment]
https://bugreports.qt.io/browse/QTBUG-102488
