### ISSUE TITLE
red filter on gif profile photo

### ISSUE THREAD

**Issue by masreplay** [telegramdesktop/tdesktop#24963]
### Steps to reproduce

1. Update profile photo to gif
2. open profile photo in full view
3. image will be covered with red

### Expected behaviour

remove red filter

### Actual behaviour

there is a red filter on the profile image
<img width="1512" alt="Screen Shot 2022-08-20 at 11 40 10 PM" src="https://user-images.githubusercontent.com/55885230/185765329-6e941b78-23b2-4215-ac70-48ef74e80390.png">

### Operating system

macOS Monterey 12.2.1 (21D62)

### Version of Telegram Desktop

v4.1.1

### Installation source

Static binary from official website

**Comment by v-svg** [comment]
Also, all GIF images in the channel feed have a red filter.

![DeepinScreenshot_20220902081336](https://user-images.githubusercontent.com/55928919/188063805-ddd1abdf-4088-42af-9556-6f16c27df390.png)

Telegram Desktop Linux v4.1.1
