### ISSUE TITLE
name use's UTF-8 Unicode characters don't appear correctly

### ISSUE THREAD

**Issue by masreplay** [telegramdesktop/tdesktop#24964]
### Steps to reproduce

1. go to profile settings and rename your account to 𝑚𝑚𝑚𝑚𝑚𝑚𝑚𝑚
2. go to any place in the app name will appear as squares

### Expected behaviour

should appear as 𝑚𝑚𝑚𝑚𝑚𝑚𝑚𝑚

### Actual behaviour

name appear as rectangles
<img width="125" alt="image" src="https://user-images.githubusercontent.com/55885230/185765592-8c8d5b67-c8e8-4a0b-8557-c6a276598617.png">

### Operating system

macOS Monterey 12.2.1 (21D62)

### Version of Telegram Desktop

v4.1.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
qt bug.

**Comment by masreplay** [comment]
@Aokromes no, I think it's not because it apear in some places as the correct representation
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/55885230/185782227-38b889ac-2716-47e9-b9e8-06f65bf837d0.png">

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6056
