### ISSUE TITLE
[Linux | Gnome] Telegram 4.1 doesn't show appindicator and options to enable native window decorations

### ISSUE THREAD

**Issue by GetAHat** [telegramdesktop/tdesktop#24960]
### Steps to reproduce

1. Have Linux OS with Gnome 3 or 40+.
2. Install Telegram 4.1 from repo or from TG's website
2. Log in.
3. See no appindicator and options to enable native window decorations

### Expected behaviour

After starting Telegram desktop, there is an appindicator in tray and options to enable native window decorations.

### Actual behaviour

This started, with no declaration of war (meaning I haven't seen anything about it in the release notes), with 4.2 update or previous. Everything worked just fine before. I've searched a bit but wasn't able to find even if it is a bug or a feature. But it definitely makes user experience quite horrible and looks out of touch.

### Operating system

Fedora w\Gnome 42.3, Debian w\Gnome 3.38.x, Arch Linux w\Gnome 42.3

### Version of Telegram Desktop

4.1

### Installation source

Static binary from official website

**Comment by kirizdev** [comment]
Take a look at #24926

**Comment by kirizdev** [comment]
A possible solution is to start tdesktop with xwayland. `QT_QPA_PLATFORM=xcb telegram-desktop`. Haven't tested it, but I think it works.

**Comment by GetAHat** [comment]
> A possible solution is to start tdesktop with xwayland. `QT_QPA_PLATFORM=xcb telegram-desktop`. Haven't tested it, but I think it works.

Thanks! I'll try it. But there is still a problem with appindicator that doesn't work anymore for some weird reason. I mean, everything else works just fine, so it's obviously TG's specific behaviour.

**Comment by kirizdev** [comment]
Which extension do you use?
