### ISSUE TITLE
build error: can not find qt

### ISSUE THREAD

**Issue by yoking1341** [telegramdesktop/tdesktop#24966]
### Steps to reproduce

just following the guide to compile the tdesktop on win10 64bit

### Expected behaviour

build pass

### Actual behaviour

CMake Error at cmake/external/qt/package.cmake:22 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake
    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)

### Operating system

win10

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

### Logs

```shell
CMake Error at cmake/external/qt/package.cmake:22 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake
    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)
```

**Comment by kirsan31** [comment]
Same problem, and  no errors during prepare. `4.0.2` building fine.

**Comment by 23rd** [comment]
You can update `cmake` git submodule to its latest commit from the default branch and retry a full rebuild.

**Comment by kirsan31** [comment]
> You can update `cmake` git submodule to its latest commit from the default branch and retry a full rebuild.

If I undertand you correctly - switch [cmake](https://github.com/desktop-app/cmake_helpers) from [0702ef4cdd8ab888fdadaa4f5b2eb0c9d5844b69](https://github.com/desktop-app/cmake_helpers/tree/0702ef4cdd8ab888fdadaa4f5b2eb0c9d5844b69) to [6f77ab1f864373dac2a10743a6f7f1e60adf9a3c](https://github.com/desktop-app/cmake_helpers/tree/6f77ab1f864373dac2a10743a6f7f1e60adf9a3c)

then no - it doesn't helped :(

```
Version: 4.1.1
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19043.
CMake Error at cmake/external/qt/package.cmake:28 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake
    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)
```

**Comment by 23rd** [comment]
You can try to add `force` to your `configure.bat ...` command.

**Comment by kirsan31** [comment]
> You can try to add `force` to your `configure.bat ...` command.

Still  no luck:(

```
Cleared previous.
Warn about uninitialized values.
-- Building for: Visual Studio 17 2022
Version: 4.1.1
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.32.31332.0
-- The CXX compiler identification is MSVC 19.32.31332.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/external/qt/package.cmake:28 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake
    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)
```

**Comment by 23rd** [comment]
Then you can try to add `QT` env manually, something like `set QT=5.15.4`.

**Comment by kirsan31** [comment]
> Then you can try to add `QT` env manually, something like `set QT=5.15.4`.

I found the real problem:
The `libs_loc` variable for `x64` build is `.../Libraries`, but must be `.../Libraries/win64`

Previously it was set here:
https://github.com/desktop-app/cmake_helpers/blob/d8442d4d968f55e8804fea3cc2d2d84f60595982/variables.cmake#L90-L94

I don't know where is it now 🤷‍♂️

**Comment by ilya-fedin** [comment]
Does `CMAKE_VS_PLATFORM_NAME STREQUAL x64` work?

**Comment by ilya-fedin** [comment]
Oh, it's due to being called before project is initialized.. What is a pity given that DESKTOP_APP_USE_PACKAGED is needed to compute CMAKE_OSX_DEPLOYMENT_TARGET that must be computed before project is initialized...
