### ISSUE TITLE
Links are opened in wrong browser in Linux/KDE Plasma

### ISSUE THREAD

**Issue by Ri0n** [telegramdesktop/tdesktop#24976]
### Steps to reproduce

1. Set default browser in gnome-settings to Google Chrome
2. Set default browser plasma settings to Firefox
3. Start plasma session, start Telegram, click any link in any message.

### Expected behaviour

The has to be opened in Firefox after detection current desktop session type and its settings.

xdg-open for example does it properly.

### Actual behaviour

The link is opened in Google Chrome. Telegram fully ignored current desktop session settings.

### Operating system

Kubuntu 22.04

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Telegram uses glib that implements the XDG [mime-apps-spec](https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html). If you think there's a problem in their specification implementation, feel free to open report to them.

**Comment by Ri0n** [comment]
thanks for the reply @ilya-fedin. It's definitely a glib bug then since xdg utils return correct values.

**Comment by Ri0n** [comment]
@Aokromes, @ilya-fedin, is there any easy way to switch to `xdg-open` instead of buggy glib?

**Comment by ilya-fedin** [comment]
> It's definitely a glib bug then since xdg utils return correct values.

I wouldn't be so sure that this is a glib bug on your place, this might be KDE who violating the spec. Only checking the files mentioned in the spec will give you the correct answer as xdg-utils is a collection of very buggy shell scripts with a lot of escaping errors and calling DE-dependent binaries, there's no guarantee those binaries follow the spec.

> is there any easy way to switch to `xdg-open` instead of buggy glib?

No, tdesktop needs the result of opening the file to show open with dialog for a good UX, xdg-open script doesn't provide such possibility. And glib is the only library (except of KDE frameworks that have recursive dependencies) implementing the spec AFAIK.
