### ISSUE TITLE
[Feature Request]  Can we blur the background for pop-up on Android?

### ISSUE THREAD

**Issue by nguyenngocduy20** [telegramdesktop/tdesktop#24970]
### Is your feature request related to a problem?

No. But this feature request improves visibility effectiveness for users.

### Describe the solution you'd like

We should blur the background for pop-up on Android, like on iOS. Like this:

![Screenshot_20220822-112011_Telegram](https://user-images.githubusercontent.com/18401853/185839759-30d6da75-b8e3-409f-93f1-b2e37a456473.png)
.

### Describe alternatives you've considered

We should blur the background for pop-up on Android, like on iOS.

### Additional context

We should blur the background for pop-up on Android, like on iOS.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
