### ISSUE TITLE
Stickers are pixelized

### ISSUE THREAD

**Issue by BANOnotIT** [telegramdesktop/tdesktop#24972]
### Steps to reproduce

Send cherry crying sticker to saved messages

### Expected behaviour

Expect sticker to be rendered as animated SVG like on other clients

### Actual behaviour

Sticker is pixelized which can be seen at tears on cheeks
![image](https://user-images.githubusercontent.com/11363215/185929854-e0a9beda-a836-4a0e-a473-0a4e9430b341.png)

### Operating system

Ubuntu 18.04 Gnome

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
It's cached to raster images with YUV compression. Some quality loss is expected.

**Comment by BANOnotIT** [comment]
But that's a big quality regression. The antialiased date text has more quality then "revolutionary animated stickers":

![image](https://user-images.githubusercontent.com/11363215/185995687-b9903b87-bdab-4aed-9fec-82b0bfcbc821.png)

During animation this regression looks more digusting:

https://user-images.githubusercontent.com/11363215/185996233-838f60fd-41cb-400f-ba1d-468f3a391428.mp4

([original quality screen record](https://ipfs.io/ipfs/QmZJpLPYUdUBDyBBwBA78uhUWWjrkySLYhihzhqf7NJThv?filename=cherry%20crying.mp4))

**Comment by BANOnotIT** [comment]
@ilya-fedin It looks like it has less pixel dimensions then screen has. Like 1 sticker pixel occupies 4 screen pixels. YUV compression should affect colors not image size.

**Comment by john-preston** [comment]
@BANOnotIT in YUV compression each pixel has a Y value, but only each 4 pixels have U and V values. I wonder if this is the reason..

**Comment by BANOnotIT** [comment]
@john-preston yeah, makes sense. But this compression artifacts are very noticeable for previously smooth vector graphics. Can't you take another compressions algorithm for vectors? They mostly have planes of same color but sharp borders and so on. Wouldn't smth like gif with pixel repeats do better here?
