### ISSUE TITLE
Recieve verification code without smart phone[Feature Request] 

### ISSUE THREAD

**Issue by konsumopfer77** [telegramdesktop/tdesktop#24973]
### Is your feature request related to a problem?

At the moment its impossible to receive an verification code via SMS for existing telegram accounts. That has been a big problem for many people over the years, as you will notice, if you look up that issue in the web. For example if a device with existing account is destroyed or lost.

### Describe the solution you'd like

**It would be really useful if there was a way to receive the code as actual SMS , email  or an phone-call to restore an account.**

### Describe alternatives you've considered

The option given option to request the code via SMS or call doesnt work, since its sending the code straight to the inaccessible account via direct message.
Its pretty rare to get an answer from support via mail or the official Telegram LoginHelp twitter account. _(@smstelegram)_

### Additional context

For people without smartphone its pretty much impossible to regain lost access to their accounts at the moment.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
