### ISSUE TITLE
Invalid json export of custom emoji messages

### ISSUE THREAD

**Issue by BANOnotIT** [telegramdesktop/tdesktop#24984]
### Steps to reproduce

1. Send custom emoji in message
2. Export chat to json

### Expected behaviour

document_id should be a string

### Actual behaviour

```json
    {
     "type": "custom_emoji",
     "text": "😁",
     "document_id": video_files/sticker.webm
    },
```

### Operating system

Ubuntu 18.04 Gnome

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/24961
