### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by rafzmk** [telegramdesktop/tdesktop#24981]
plataform: win x64
I'm trying to build , but I'm getting stuck on this:

build the project
Go to BuildPath\tdesktop\Telegram and run (using your api_id and api_hash)
configure.bat x64 -D TDESKTOP_API_ID=YOUR_API_ID -D TDESKTOP_API_HASH=YOUR_API_HASH

**1° I didn't find the place to change API ID and API HASH.**

---------------

Open BuildPath\tdesktop\out\Telegram.sln in Visual Studio 2022
Select the Telegram project and press Build > Build Telegram (Debug and Launch Settings)
The Telegram.exe result will be located in D:\TBuild\tdesktop\out\Debug (and Release)

**2° I couldn't find this folder \out\Telegram.sln, so I couldn't find the Telegram.sln project to run it in Visual Studio 2022**

**Comment by Aokromes** [comment]
you must replace YOUR_API_ID and YOUR_API_HASH by your values.
