### ISSUE TITLE
64+32 in one folder

### ISSUE THREAD

**Issue by Deadooshka** [telegramdesktop/tdesktop#24989]
### Steps to reproduce

install x32+x64 portables in single folder with exe renaming and run one after another

### Expected behaviour

normal using of the same settings and cache on different systems as it was before the latest updates

### Actual behaviour

authorization and settings lost

### Operating system

Windows 7x32/10x64

### Version of Telegram Desktop

4.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Authorization will be lost if one data folder (even if copied) is used by multiple instances simultaneously. This always was a thing.
