### ISSUE TITLE
[Question] Premium doubled limits

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#24992]
Why TDesktop shows "100 / 200" pinned chats and "3 / 6" accounts when iOS shows "5 / 10" pinned chats and "3 / 4" accounts?

TD:
![image](https://user-images.githubusercontent.com/39812401/187028545-96ae940a-8761-4fe9-b23e-388b12ca746e.png)
![image](https://user-images.githubusercontent.com/39812401/187028550-17500331-0303-4c3f-846a-07936231454b.png)

iOS:
![image](https://user-images.githubusercontent.com/39812401/187028573-ce93556b-7e99-43e8-a915-b15aaa77f067.png)
![image](https://user-images.githubusercontent.com/39812401/187028568-176fa0fa-4cc0-46d9-bb41-3e584364e204.png)

**Comment by john-preston** [comment]
For accounts it shows for me this:

![image](https://user-images.githubusercontent.com/17900494/187029511-598be7b1-7dc3-4033-be39-1e98cf4371b6.png)

Meaning that first premium gives you 4 accounts, second gives 5 and three premium accounts give you 6 total.

The pinned chats looks like a bug, like numbers from pin-in-archive or pin-in-folder is used.

**Comment by Neurotoxin001** [comment]
For premium maybe it's because I already added 3 accounts with premium. Btw it's on 4.1.1 x64

**Comment by john-preston** [comment]
It'll be fixed in the next version.

**Comment by john-preston** [comment]
(the pinned chats one, the accounts work like expected)

**Comment by Neurotoxin001** [comment]
Fixed 4.2.4
![image](https://user-images.githubusercontent.com/39812401/194044285-87fd8da3-5f05-4302-98bd-46c5d15d973d.png)
