### ISSUE TITLE
[Question] Proxy connection ok, but cannot login

### ISSUE THREAD

**Issue by CindyZhouYH** [telegramdesktop/tdesktop#24991]
I entered this problem when installing telegram on macOS.
## Operating System
macOS monterey 12.5.1

## telegram version
![image](https://user-images.githubusercontent.com/60092417/187021172-b620e230-5ea6-40cc-a271-cea118ff520a.png)

## behavior
![image](https://user-images.githubusercontent.com/60092417/187021096-aa50bc46-ee84-40cf-9ab9-4cc20a2f522b.png)
![image](https://user-images.githubusercontent.com/60092417/187021122-f7b97971-dc9b-4b5a-a546-8e72e2281d7c.png)

It seems that the proxy connection is ok, but it still shows a white screen.

**Comment by ilya-fedin** [comment]
It's not tdesktop on your screeshots, you can download tdesktop here from github and compare
