### ISSUE TITLE
Can not play any music

### ISSUE THREAD

**Issue by thegreathir** [telegramdesktop/tdesktop#24997]
### Steps to reproduce

1. Open the telegram
2. Find a music message
3. Click on the play button

### Expected behaviour

Music is played and you can listen to it

### Actual behaviour

No sound output at all

### Operating system

Arch Linux

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

### Logs

```shell
[mp3 @ 0x7fdcfc82ae00] Could not find codec parameters for stream 1 (Video: png, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
```

**Comment by ilya-fedin** [comment]
Can't reproduce, music plays just fine

**Comment by thegreathir** [comment]
Do you know what is the log message talking about?

**Comment by ilya-fedin** [comment]
Well, it's not a log message, Telegram's log has completely another format. That more looks like noise from terminal. I guess it says ffmpeg can't decode file's thumb.

**Comment by thegreathir** [comment]
OK, How can I access telegram logs?

**Comment by ilya-fedin** [comment]
You can enter the `viewlogs` [cheat code](https://github.com/telegramdesktop/tdesktop/wiki/Cheat-Codes).

**Comment by thegreathir** [comment]
```
[2022.08.28 14:30:06] Audio Info: recreating audio device and reattaching the tracks
```
I found this when I click on the play button

**Comment by ilya-fedin** [comment]
It's ok

**Comment by thegreathir** [comment]
![2022-08-28-143944_503x404_scrot](https://user-images.githubusercontent.com/30614715/187068771-9d28e59c-04fb-4bae-bf4d-b154675cf419.png)

In Pavucontrol it seems telegram is not sending anything to the output device. (Comparing to chromium that sound bar is shaking)

**Comment by thegreathir** [comment]
I installed it from snap and the problem solved!
