### ISSUE TITLE
Why I can't login using http proxy anymore

### ISSUE THREAD

**Issue by k79e** [telegramdesktop/tdesktop#24990]
### Steps to reproduce

1. Use http proxy to login
2. It fails.
3. But soccks5 is fine.
4. It's a same proxy server so it's abnormal.

### Expected behaviour

It should login by using http proxy

### Actual behaviour

It can't login

### Operating system

win7

### Version of Telegram Desktop

Tried newest version and it's same

### Installation source

Static binary from official website

### Logs

```shell
[2022.08.27] HTTP Error: content error 203 - Error transferring http://91.108.56.156:80/api - server replied: Not Found
[2022.08.27] MTP Info: -404 error received in 5 with temporary key, assuming it was destroyed.
```

With newest version it don't have http error but only mtp 404.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by k79e** [comment]
If looks fine now.
I don't update to new version and it worked fine.
So it's the server's problem?
