### ISSUE TITLE
Deleted messages should be removed on the other side of conversation if they are not readed by the recipient

### ISSUE THREAD

**Issue by yuriimuratov** [telegramdesktop/tdesktop#2499]
Deleted messages should be removed on the other side of conversation, if they are not readed by the recipient

### Steps to reproduce
1. Recepient should be offline
2. Sender sends message to recepient
3. Sender deletes this message

### Expected behaviour
Deleted messages should be deleted in recepient's telegram client by the fact of it's deletion in senders' client

### Actual behaviour
Recepient became online and able to read sender's deleted message

### Configuration
**Operating system:**
Microsoft Windows 7, Android

**Version of Telegram Desktop:
Tested in versions:
Telegram for Desktop 0.10.5 - 0.10.11
Telegram for Android 3.11.12 (837) arm-v7a - 3.13.0 (848) arm-v7a

**Comment by yuriimuratov** [comment]
Additional expected behaviour:

Additional menuitem "Delete everywhere" must be present for realizing this feature
"Delete" menuitem must be renamed to "Delete from myself" for solving inconvenience of issue.

**Comment by Kondra007** [comment]
That looks like API issue, not TDesktop issue.

**Comment by auchri** [comment]
Yes, it has to be implemented in the api (https://telegram.org/faq#q-how-are-secret-chats-different)

**Comment by yuriimuratov** [comment]
Anybody knows how to contact support of API ?

**Comment by stek29** [comment]
Use "Ask a question" button in settings.

**Comment by raistlinmaestre** [comment]
This is not an API issue anymore since last update. It would be nice to have it on TDesktop.

**Comment by stek29** [comment]
@raistlinmaestre Install TDesktop Alpha.
