### ISSUE TITLE
The heart symbol displays in wrong way

### ISSUE THREAD

**Issue by guaNa228** [telegramdesktop/tdesktop#25001]
### Steps to reproduce

1. Copy and paste this symbol ♡, which unicode is U+2661

### Expected behaviour

It should have been a hearth emoji...

### Actual behaviour

It displays as triple bar: ≡

### Operating system

Windows 10

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
It's a bug in Windows Tahoma font
