### ISSUE TITLE
[Feature Request] Allow users to change default fonts

### ISSUE THREAD

**Issue by godlikeSwan** [telegramdesktop/tdesktop#25005]
### Is your feature request related to a problem?

Sometimes current default fonts looks ugly (especially monospace one)

![image](https://user-images.githubusercontent.com/14862534/187520593-018b8173-d18b-4e50-8813-206a3b7c5bf4.png)
this a, s, e and uppercase letters have strange thick parts and others have not
& is not in the middle

### Describe the solution you'd like

It would be great if the app let users to choose their installed fonts in settings menu

### Describe alternatives you've considered

May be there will be a command line option or a settings file to choose font where
Also fonts could be stored as separate files so they could be replaced manually

**Comment by Aokromes** [comment]
#90
