### ISSUE TITLE
Gif bot causes app to become unresponsive / sluggish whilst loading

### ISSUE THREAD

**Issue by ben-xo** [telegramdesktop/tdesktop#2500]
### Steps to reproduce
1. Activate @gif bot (e.g. something like @gif cat curl sun)
2. Whilst the previews are loading, try to edit the content of the text box, or click anywhere else in the UI, or try scrolling the partially loaded preview list
### Expected behaviour
- The edit box should remain instantly responsive to keypresses
- the preview box should scroll smoothly
### Actual behaviour
- everything becomes jerky and unresponsive, sometimes for a long time, whilst GIF previews load
- sometimes even closing the preview box becomes difficult
### Configuration

**Operating system:**
OSX El Capitan 10.11.6 (15G1004)

**Version of Telegram Desktop:**
0.10.8
### Logs

Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by john-preston** [comment]
@ben-xo Can you try it in macOS Sierra?

**Comment by ben-xo** [comment]
@john-preston Unfortunately I can't at the moment, as I'm staying on El Capitan (on my work laptop) until advised to upgrade by corporate, and I'm staying on El Capitan (on my home laptop) until advised to upgrade by Serato / Rane (https://serato.com/latest/blog/20136/dont-upgrade-to-macos-sierra-yet)

**Comment by ben-xo** [comment]
I'd just like to point out that I'm no longer having any issues with gif bot on macOS Sierra.

I'm suffering from the emoji / text-input panel being missing due to bugs in QT, but GIFfing is smooth.
