### ISSUE TITLE
[Windows Build] take a long time, and exe too large

### ISSUE THREAD

**Issue by pugongying** [telegramdesktop/tdesktop#25007]
When I open Telegram.sln and build the project with the default configuration, it takes about an hour.
And out\Debug Telegram.exe 326MB。

What can i do to change those.

**Comment by ilya-fedin** [comment]
Re-write tdesktop to have less code? I don't think you can do anything else, build time and binary size depends on the codebase size.

**Comment by john-preston** [comment]
@pugongying Binary size is less for the Release build, but then build time gets even longer 😞

**Comment by pugongying** [comment]
@ilya-fedin @john-preston I see, thanks very much.
