### ISSUE TITLE
Bug in RTL on lines starting with flag emoji

### ISSUE THREAD

**Issue by alishirmohammadi** [telegramdesktop/tdesktop#25004]
### Steps to reproduce

Write a message with paragraph starting with a flag emoji continues with characters of RTL language e.g. Persian or Arabic then send the message, that line displays LTR! but for other emojis it works correct.
![image](https://user-images.githubusercontent.com/44928403/187379870-c2259658-112e-46ff-ad71-74ab8b769f2d.png)
![image](https://user-images.githubusercontent.com/44928403/187380155-92fbc427-e087-46ec-9db6-baa634aeabac.png)

### Expected behaviour

If the paragraph contains RTL Language characters and starts with any emoji, displays in RTL format.

### Actual behaviour

RTL format for RTL languages!

### Operating system

Windows 11 Pro 21H2

### Version of Telegram Desktop

Version 4.1.1 x64

### Installation source

Static binary from official website

**Comment by awohsen** [comment]
![image](https://user-images.githubusercontent.com/93778317/187853078-db45082b-be21-4bc8-a264-3add9bff8590.png)

It's not only flags and there are a few more emojis behaving like this.

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
This bug is old af
I guess they know it but they don't like to fix it like many other problems
