### ISSUE TITLE
JSON export produces very dynamic JSON

### ISSUE THREAD

**Issue by CrazyHackGUT** [telegramdesktop/tdesktop#25000]
### Steps to reproduce

1. Open any chat.
2. Do "Chat export" in JSON format.
3. Open JSON.
4. See very dynamic type in `text` field for messages.

### Expected behaviour

I expected see static `string` or array with objects only, what can be parsed without any issues on .NET via [JSON.NET](https://www.newtonsoft.com/json).
It requires declare types for every field in classes, but i can't describe type without scratches.

### Actual behaviour

`text` can be two different types:
- `string`, if message don't contains any message entities (bold/italic markup and etc.)
- `array` with mixed types (`string` and `object`)

### Operating system

Windows 11

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Please check the latest beta version.
