### ISSUE TITLE
When I change the display screen, the picture preview has problems

### ISSUE THREAD

**Issue by alongw** [telegramdesktop/tdesktop#25003]
### Steps to reproduce

Use telegram normally, then use remote desktop or parsec to control this computer remotely, they will change the screen resolution of this computer, then disconnect them and continue using telegram, open a picture at will

### Expected behaviour

Normal display of the preview of the image

### Actual behaviour

No matter which picture is opened, it will be displayed in the upper left corner of the last previewed picture before the screen resolution was changed, and cannot be zoomed in or out (this problem is not necessarily triggered 100% of the time, this problem also has a chance to appear after updating the graphics card driver)

### Operating system

Windows 11 Professional Edition

### Version of Telegram Desktop

v4.1.1 x64 16.08.22

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Do those applications create new virtual screen or they change the resolution of existing screen?

**Comment by alongw** [comment]
Microsoft's remote desktop connection is to create a new virtual screen and parsec is to change the resolution of an existing screen. When I ended the remote connection, it was like they restarted the driver of the graphics card

**Comment by ilya-fedin** [comment]
Will viewer size be normal if you try to move the main window on the screen (e.g. a little left or a little right) just after driver reset?
