### ISSUE TITLE
Delete message does not delete the message at recipient

### ISSUE THREAD

**Issue by drdaffey** [telegramdesktop/tdesktop#2501]
### Steps to reproduce
1. Post a message or sticker.
2. Delete the message
3. Message is deleted on client end, still remaining on receiver end.

### Expected behaviour
I'm not certain if this is a bug, but deleting messages only deletes them on the sender's end. The only way to change the message on both ends is to edit it.

**Version of Telegram Desktop:**
0.10.11

**Comment by auchri** [comment]
Works as expected: https://telegram.org/faq#q-how-are-secret-chats-different

>  And when you delete messages on your side of the conversation, the app on the other side of the secret chat will be ordered to delete them as well.

**Comment by drdaffey** [comment]
Deleting doesn't delete at both ends but editing edits at both ends? Doesn't really make sense.

**Comment by VSG24** [comment]
Wait a minute, If the expected behaviour is to only delete messages on the client side and not on the recipient's side, then why is there a dialog that pops up and asks if you would like to delete it for the other side too? I just don't get it...

**Comment by stek29** [comment]
@VSG24 This issue is outdated, see https://telegram.org/blog/unsend-and-usage
