### ISSUE TITLE
hardware video acceleration is not working with Libva

### ISSUE THREAD

**Issue by userofryzen** [telegramdesktop/tdesktop#25018]
### Steps to reproduce

1 download the telegram package from official website
2. open it
3. enable the video acceleration
4. telegram plays the video but without any type of GPU use to decode

### Expected behaviour

Like on arch/manjaro  package the action of enable the acceleration option on the official package from telegram website should decode the video through the GPU 

### Actual behaviour

$ telegram-desktop -- %u
error: : cannot open
error: : cannot open
error: : cannot open
QObject::~QObject: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
$ /tmp/firefox/Telegram/Telegram -workdir /home/albertogm/.local/share/TelegramDesktop/ -- %u
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
[AVHWDeviceContext @ 0x7f6566ed9b40] Cannot load libcuda.so.1
[AVHWDeviceContext @ 0x7f6566ed9b40] Could not dynamically load CUDA

The first is from the arch package from repos, there is no " error" and libva is used(working with amd and intel)
The second one is from the package downloaded from the website
The option appears but tries to load libcuda instead of libva for no reason. 

### Operating system

Manjaro stable on latest updates with plasma wayland

### Version of Telegram Desktop

4.1.0

### Installation source

Static binary from official website

**Comment by userofryzen** [comment]
I cant help anymore if there is no questions here...

**Comment by RafaelLinux** [comment]
> I cant help anymore if there is no questions here...

Sometimes it's like developers were not interested in resolve issue and the way is not asking nothing about. I saw it before (like  "[Feature Request] Add hardware video acceleration on Linux").

I must say that I needed to disable "OpenGL" in Telegram to get smooth video play.

[Feature Request] Add hardware video acceleration on Linux

**Comment by Aokromes** [comment]
> > I cant help anymore if there is no questions here...
> 
> Sometimes it's like developers were not interested in resolve issue and the way is not asking nothing about. I saw it before (like "[Feature Request] Add hardware video acceleration on Linux").
> 
> I must say that I needed to disable "OpenGL" in Telegram to get smooth video play.
> 
> [Feature Request] Add hardware video acceleration on Linux

you missed the pull request over your comment that will close this issue.

**Comment by ilya-fedin** [comment]
The best outcome if ffmpeg become friendly to such universal binary usages and wouldn't hard-require those libraries but I guess that's unrealistic, Linux infrastructure developers seem to do everything to make such user-friendly software distribution as hard as possible.

**Comment by RafaelLinux** [comment]
Thanks for fixing. I am sorry that it has been complex to solve. I didn't know that the use of FFMPEG libraries were so dependent on each Linux distribution.

**Comment by ilya-fedin** [comment]
Well, it might be too early for thanks. It's highly likely the approac might be unstable and reverted.
