### ISSUE TITLE
PLEASE fix it so that the reactions menu is not a moving target anymore, I am sick of accidentally reacting with Thumbs Down

### ISSUE THREAD

**Issue by dusthillresident** [telegramdesktop/tdesktop#25022]
### Is your feature request related to a problem?

The reactions menu moves up the screen as new messages come in. This makes it a moving target. As it is a vertical list of buttons corresponding to emoji reactions, the user may be aiming at, for example, the Heart emoji, and as they try to click on it at an inopportune moment, a new message comes in, sending the emoji list up the screen a bit, and as a result they end up clicking on Thumbs Down instead of Heart. 

### Describe the solution you'd like

Design it sensibly and properly so it isn't a moving target and so that telegram stops making me react with thumbs down on the most inappropriate possible messages at the worst possible moments which has been happening to me for many months now.

### Describe alternatives you've considered

This is just a design flaw, there is no alternative to you fixing the design of your app. It's broken. Fix it.

### Additional context

https://user-images.githubusercontent.com/872076/188271880-34ba4089-061a-4968-aade-acec68adc590.mp4

**Comment by ilya-fedin** [comment]
Already fixed on dev branch
