### ISSUE TITLE
 Add section called "games" in Shared Media

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#2502]
### Steps to reproduce
1. See Shared Media
### Expected behaviour

There is no efficient way to find shared games in current chat. The games are "special" links, but neither are in the links section in shared media.
It would be good idea to add a new section called **games.**
### Actual behaviour

Games are not found in any section
### Configuration

**Operating system:** Fedora 24 64 bit

**Version of Telegram Desktop:** Telegram 0.10.11
### Additional info

GIF's also is needed

**Comment by auchri** [comment]
> GIF's also is needed

https://github.com/telegramdesktop/tdesktop/issues/1677
