### ISSUE TITLE
File name is blank when I try to save a file

### ISSUE THREAD

**Issue by chalist** [telegramdesktop/tdesktop#25035]
### Steps to reproduce

1. Just try to save a file from a channel or private message.

### Expected behaviour

I think the file name must be set as the default file name in the saving dialog box. 
![2022-09-08_06-25_1](https://user-images.githubusercontent.com/1072154/189016397-ab8640e4-c6bf-4b6c-8722-de9e41f3be82.png)

### Actual behaviour

File name is blank when I try to save a file

### Operating system

Manjaro i3

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#24491
