### ISSUE TITLE
telegram_desktop not working under proxy

### ISSUE THREAD

**Issue by v-kas-dangi** [telegramdesktop/tdesktop#25034]
### Steps to reproduce

The issue came up 2-3 weeks ago. The app works well when I use my own internet but when it comes to the institute internet(which needs proxy), it just keeps reconnecting for forever.
Also if i install it again, it connects successfully for the first time.
In the proxy settings, it shows me that the ping is available for my proxy but when i click on custom proxy it doesn't work at all.
I tried installing it with snap, apt and direct file
### Expected behaviour

Should start and work properly.

### Actual behaviour

![image](https://user-images.githubusercontent.com/74185086/188963992-f9466637-81b4-4b52-abe6-9427dae2a7d8.png)
![image](https://user-images.githubusercontent.com/74185086/188964776-718c852c-6d59-4dcd-9054-f3a13d1ce6e2.png)
![image](https://user-images.githubusercontent.com/74185086/188964864-0fcd4eba-5569-4045-ab17-21227daf488e.png)

When i go for the custom proxy it just keep 'reconnecting'.

### Operating system

Ubuntu 20.04

### Version of Telegram Desktop

4.1.1

### Installation source

Snap

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/24990

**Comment by v-kas-dangi** [comment]
> #24990

But it is working fine in windows for me.
