### ISSUE TITLE
Screen sharing not working in a video call

### ISSUE THREAD

**Issue by lashahub** [telegramdesktop/tdesktop#25037]
### Steps to reproduce

1. Use a voice or video chat option on two Windows 10 laptops
2. Click on the share screen option

### Expected behaviour

The shared screen doesn't show up on the first try. Only after the second or multiple tries

### Actual behaviour

Share the screen (current window, whole display) right away.

### Operating system

Windows 10 Build 19044

### Version of Telegram Desktop

4.1.0.0

### Installation source

Microsoft Store

**Comment by ilya-fedin** [comment]
#24787
