### ISSUE TITLE
Option to enable join requests in private group is shown when it should not be

### ISSUE THREAD

**Issue by foxscotch** [telegramdesktop/tdesktop#25030]
### Steps to reproduce

I don't know how to reproduce this, exactly.

I have a private group, and in the settings for it I see the option to enable join requests. However, to my understanding, private groups shouldn't have this setting. And indeed, when I try to _save_ it with this setting enabled, nothing happens. In the logs (included at the bottom), there's an error message that indicates the cause, but nothing is actually shown in the UI.

I'll add that the group is a bit old, I created it in June 2016. I know a lot's changed about how groups operate in that time, so maybe that's related? It's also a small group, only 16 members currently, and it's probably never been higher than that. I'm happy to provide details about the values of the chat's other settings, if that would be helpful.

### Expected behaviour

I should not to see the checkbox for join requests

### Actual behaviour

I do see the checkbox for join requests

### Operating system

Windows 11 21H2

### Version of Telegram Desktop

4.1.1 x64

### Installation source

Static binary from official website

### Logs

```shell
[03:08:51.982 06-0023182] (dc:1_main) Send: { core_message
  msg_id: redacted [LONG],
  seq_no: 236 [INT],
  bytes: 96 [INT],
  body: { msg_container
    messages: [ vector<0xffffffffffffffff> (2)
      { core_message
        msg_id: redacted [LONG],
        seq_no: 235 [INT],
        bytes: 28 [INT],
        body: { channels_toggleJoinRequest
          channel: { inputChannel
            channel_id: redacted [LONG],
            access_hash: redacted [LONG],
          },
          enabled: { boolTrue },
        },
      },
      { core_message
        msg_id: redacted [LONG],
        seq_no: 236 [INT],
        bytes: 28 [INT],
        body: { msgs_ack
          msg_ids: [ vector<0x22076cba> (2)
            redacted [LONG],
            redacted [LONG],
          ],
        },
      },
    ],
  },
} (dc:1,key:redacted)
[03:08:52.017 06-0023188] (dc:1_main) Recv: { core_message
  msg_id: redacted [LONG],
  seq_no: 555 [INT],
  bytes: 44 [INT],
  body: { rpc_result
    req_msg_id: redacted [LONG],
    result: { rpc_error
      error_code: 400 [INT],
      error_message: "CHAT_PUBLIC_REQUIRED" [STRING],
    },
  },
} (dc:1,key:redacted)
```

**Comment by john-preston** [comment]
@foxscotch Thanks for your report!
