### ISSUE TITLE
Web App returns (null) on linux and android

### ISSUE THREAD

**Issue by WhatIsThisBreakfast** [telegramdesktop/tdesktop#25048]
### Steps to reproduce

1. Go to @test_teel_bot
2. click menu button
3. ![image](https://user-images.githubusercontent.com/90184510/189547096-71660d12-c89d-452f-8084-d502fba5bc96.png)

### Expected behaviour

![image](https://user-images.githubusercontent.com/90184510/189547115-c4ae2df6-dc98-48e3-aa19-9a9bb9695aec.png)

### Actual behaviour

 ![image](https://user-images.githubusercontent.com/90184510/189547096-71660d12-c89d-452f-8084-d502fba5bc96.png)

but on windows and in the web version of telegram it works fine

Web app: [https://yogamed-course.ru/](https://yogamed-course.ru/)

### Operating system

Ubuntu, Android

### Version of Telegram Desktop

v4.1.1

### Installation source

Static binary from official website

**Comment by WhatIsThisBreakfast** [comment]
the server is nginx which serves static files with gzip compression

**Comment by WhatIsThisBreakfast** [comment]
logs do not contain information about web view at all

**Comment by WhatIsThisBreakfast** [comment]
and it works great on ios

**Comment by ilya-fedin** [comment]
Maybe you're using HTTP/2? For HTTP/2 to work, you need to install webkit2gtk-4.1 or webkit2gtk-5.0 that are not provided by Ubuntu yet (but provided by rolling release distros like Arch).

**Comment by WhatIsThisBreakfast** [comment]
> Maybe you're using HTTP/2? For HTTP/2 to work, you need to install webkit2gtk-4.1 or webkit2gtk-5.0 that are not provided by Ubuntu yet (but provided by rolling release distros like Arch).

but android?

**Comment by ilya-fedin** [comment]
I have no idea about android, it's a completely different client.

**Comment by WhatIsThisBreakfast** [comment]
> I have no idea about android, it's a completely different client.

i have seen similar issue with glib and url. Could this be related to my problem?

**Comment by WhatIsThisBreakfast** [comment]
because durger king bot works great for me

**Comment by ilya-fedin** [comment]
> i have seen similar issue with glib and url. Could this be related to my problem?

I don't know what issue you're talking about. I suggest to check whether you server can accept HTTP/1.1 requests.

**Comment by WhatIsThisBreakfast** [comment]
> > i have seen similar issue with glib and url. Could this be related to my problem?
> 
> I don't know what issue you're talking about. I suggest to check whether your server can accept HTTP/1.1 requests.

sec

**Comment by WhatIsThisBreakfast** [comment]
> > i have seen similar issue with glib and url. Could this be related to my problem?
> 
> I don't know what issue you're talking about. I suggest to check whether your server can accept HTTP/1.1 requests.

![image](https://user-images.githubusercontent.com/90184510/189547733-27d40920-2e2d-4ce8-82be-46cf5989d5e5.png)

**Comment by WhatIsThisBreakfast** [comment]
ye, he can

**Comment by ilya-fedin** [comment]
Apparently there's some bug in webkit2gtk library or down the stack... I suggest to check any webkit2gtk-based web browser and if you can reproduce, report this to Ubuntu or webkit

**Comment by WhatIsThisBreakfast** [comment]
> Apparently there's some bug in webkit2gtk library or down the stack... I suggest to check any webkit2gtk-based web browser and if you can reproduce, report this to Ubuntu or webkit

but why is durger king bot working fine?

**Comment by WhatIsThisBreakfast** [comment]
when running a web app through linux or android, the entry in the nginx access log is not even displayed

**Comment by ilya-fedin** [comment]
> but why is durger king bot working fine?

There may be any other web server configuration feature not supported by webkitgtk

**Comment by ilya-fedin** [comment]
> when running a web app through linux or android, the entry in the nginx access log is not even displayed

Well, maybe webkitgtk doesn't like some character in your url

**Comment by WhatIsThisBreakfast** [comment]
> > but why is durger king bot working fine?
> 
> There may be any other web server configuration feature not supported by webkitgtk


i launched webkit2gtk-4.0/MiniBrowser and opened my page there. It displays great

**Comment by ilya-fedin** [comment]
:(

**Comment by ilya-fedin** [comment]
Unfortunately, I have no idea what we can do as all webkitgtk says is `(null)`

**Comment by WhatIsThisBreakfast** [comment]
> Unfortunately, I have no idea what we can do as all webkitgtk says is `(null)`

So, I noticed that Webkit2Gtk MiniBrowser is posting a problem with the TLS certificate. Let's say google it opens without this error

**Comment by WhatIsThisBreakfast** [comment]
In any case, you gave me this problem. Thank you
