### ISSUE TITLE
[Feature Request] Add grouping of the channels

### ISSUE THREAD

**Issue by johngull** [telegramdesktop/tdesktop#25043]
### Is your feature request related to a problem?

It is hard to manage a list of the channels and contacts.

### Describe the solution you'd like

It will be great to have the ability to create a group of channels/contacts.
For example, I may group all news channels into a common group, and professional channels into another one.
I would like to close these 2 groups and mute them during work. 
But when I want to read news from channels I will expand the group of news channels and see them in the list.

### Describe alternatives you've considered

An easier, but not so handy solution is tagging of the channels and then filtering by tags.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
