### ISSUE TITLE
Copy Paste functions suddenly stop working

### ISSUE THREAD

**Issue by PeterBorisenko** [telegramdesktop/tdesktop#25041]
### Steps to reproduce

1. Actively use group chat, switch languages (by Option+Space keys), use "```" formatting
2. Copy paste something from Eclipse

### Expected behaviour

Works fine from launch till closing

### Actual behaviour

After some use Ctrl+V stopped working,
As well a context menu look like following
![image](https://user-images.githubusercontent.com/2276908/189315201-732d4e60-a33c-462d-9fff-85e5dd870188.png)

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

Telegram v4.4.1

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Is there a way to reproduce without Eclipse? I'm not an Eclipse user.

**Comment by PeterBorisenko** [comment]
As for now I haven't noticed any other ways.

**Comment by ilya-fedin** [comment]
Are you sure Telegram is at fault? Couldn't this be compositor or XWayland?

**Comment by PeterBorisenko** [comment]
Is there a way to check it? I am able to paste it anywhere else but Telegram.

**Comment by ilya-fedin** [comment]
> Is there a way to check it?

Well, first check whether Eclipse is running via native Wayland or via XWayland, then check whether Telegram is running via native Wayland or XWayland (this is specified in the session list from the Privacy & Security section). It's not a rare situation when compositors have bugs in the clipboard synchronization between native Wayland and XWayland applications.

**Comment by PeterBorisenko** [comment]
From Eclipse info:
```
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.F4D7R1
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_CURRENT_DESKTOP=ubuntu:GNOME
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=ubuntu
XDG_SESSION_TYPE=wayland
XMODIFIERS=@im=ibus
_=/usr/bin/gnome-session
```
From Telegram session:
![image](https://user-images.githubusercontent.com/2276908/189488637-34826d82-7f85-45cb-9b30-6aa2a163a5af.png)

It is not clear for me but seems both run on Wayland.

**Comment by ilya-fedin** [comment]
> From Eclipse info:

It's just your environment variables, you can also get them with `env` command in Terminal, this has nothing to do with what Eclipse uses. You can try to check whether xeyes or xwininfo detect Eclipse window.
