### ISSUE TITLE
[Feature Request] Add group permission for enable/disable sending voice messages

### ISSUE THREAD

**Issue by bogdanbebic** [telegramdesktop/tdesktop#25047]
### Is your feature request related to a problem?

When changing group permissions, there is no option to restrict users from sending voice messages:

![Telegram_group_permissions](https://user-images.githubusercontent.com/36513588/189534362-ef3a84bc-74a4-444d-9bee-b5fb3bd9ca04.png)

### Describe the solution you'd like

Add a new switch for enable/disable "Send voice messages" in group chat permissions, same as already exists for:
- Send messages
- Send media
- Send stickers & GIFs

### Describe alternatives you've considered

This is a missing feature for group chats - I don't see an alternative.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by bogdanbebic** [comment]
Thanks! I wasn't aware of the general telegram bugs tracking page.
