### ISSUE TITLE
Restrict User that 1 User can create not more than 10 Bots

### ISSUE THREAD

**Issue by HackersCardgame** [telegramdesktop/tdesktop#25046]
### Steps to reproduce

1. See Running Attack in the Chat https://t.me/SuizidChat
2. We have Admins but they can not do anything
3. it's a Group of vulneable People that suffer from Depression and Suicide thoughts

### Expected behaviour

Something like Zoom-Bombing but in Telegram Channel with Content of people commiting suicide. There is a second group that helps doing Terror, this group is hidden and called "Fraud V2"

### Actual behaviour

Restrict BOT Count a user can create, so we would have just 10 instead of 7000 Bots

### Operating system

Linux, Windows, OSX not tested

### Version of Telegram Desktop

4.1.1 x86

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by HackersCardgame** [comment]
@Aokromes thank you i will move it there

**Comment by Aokromes** [comment]
you may want to enable aprove joining to throotle spammers.
