### ISSUE TITLE
[Question] Does "Mute forever" action actually mutes a chat for one year?

### ISSUE THREAD

**Issue by ali-shamakhi** [telegramdesktop/tdesktop#25051]
Recently, I have noticed that if I mute a chat using the "Mute forever" action:

![image](https://user-images.githubusercontent.com/10486368/189830667-caf450a4-00d1-44bf-8ebd-a500b28c06a4.png)

the context menu of the chat will show `1y` in front of the "Unmute" action:

![image](https://user-images.githubusercontent.com/10486368/189830887-52d74fda-bec9-4b09-88f5-2dee385c23de.png)

This behavior is new, as my old muted chats are not like this.

Is this a new limitation of the Telegram API?

**Comment by RememberTheAir** [comment]
I don't see any limitation from the API schema side, but apparently tdesktop's default muting time is 84600 * 365 (one year):

https://github.com/telegramdesktop/tdesktop/blob/9933d1ff3a5156aeba470f2407344f90d030633d/Telegram/SourceFiles/data/notify/data_peer_notify_settings.h#L32

https://github.com/telegramdesktop/tdesktop/blob/898edad09ba93b8cceaa4613b2d53a81cb3d5762/Telegram/SourceFiles/menu/menu_mute.cpp#L84-L120

(these might not be the relevant snippet of code that handles how the chats are muted)

**Comment by 23rd** [comment]
> Is this a new limitation of the Telegram API?

I would say that the server has expanded the limits. All previous years, the tdesktop was sending muting of chat to the server for 365 days and it was recognized as "forever". Now 365 days should really mute for that period.

Please check the latest beta, it should be better now.

**Comment by ali-shamakhi** [comment]
So, shouldn't the UI reflect the situation correctly? For example, the "Mute forever" action should be renamed to "Mute for 1 year".

Although, I prefer being able to actually mute a chat forever (if possible).

**Comment by john-preston** [comment]
@ali-shamakhi

> Please check the latest beta, it should be better now.
