### ISSUE TITLE
build on mac m1 failed

### ISSUE THREAD

**Issue by 0Litost0** [telegramdesktop/tdesktop#25058]
### Steps to reproduce

Execute Build instructions for macOS:
./tdesktop/Telegram/build/prepare/mac.sh
report:
/opt/homebrew/opt/llvm/bin/llvm-ranlib: error: Invalid option: '-no_warning_for_no_symbols'
when i build Libraries/qt_6_3_1

### Expected behaviour

build succeed

### Actual behaviour

build failed

### Operating system

macos(m1) Monterey 12.5.1

### Version of Telegram Desktop

branch:dev commit 9923cc9b312bcd0808c1db821a1254faabe03e3d

### Installation source

Static binary from official website

### Logs

```shell
/opt/homebrew/opt/llvm/bin/llvm-ranlib: error: Invalid option: '-no_warning_for_no_symbols'
[230/3456] Building CXX object qtbase/src/3rdparty/harfbuzz-ng/CMakeFiles/BundledHarfbuzz.dir/RelWithDebInfo/src/hb-aat-layout.cc.o
ninja: build stopped: subcommand failed.
```

**Comment by landaire** [comment]
Hit this same issue. It's intended to be built with Xcode's `libtool`, not the one from Homebrew.

Running `PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/:$PATH" ./tdesktop/Telegram/build/prepare/mac.sh` should work.
