### ISSUE TITLE
IPA characters displayed incorrectly

### ISSUE THREAD

**Issue by PKholyavin** [telegramdesktop/tdesktop#25054]
### Steps to reproduce

1. Send a message containing IPA characters ˈ U+02C8, ˌ U+02CC, ː U+02D0 (and possibly others)
2. Send a message containing combining IPA characters ̩ U+0329, ͡ U+0361 (and possibly others)

### Expected behaviour

For 1, I expect each character to occupy a separate spot in the line (as these characters are not combining). Example: fiːl ˈsɪti
For 2, I expect them to be displayed correctly over one or two characters. Example: t͡s n̩

### Actual behaviour

Non-combining characters combine with following characters
![image](https://user-images.githubusercontent.com/66316855/189962064-e904c2c7-bd10-4aac-a0ad-785ba687c8fa.png)
Combining characters are offset
![image](https://user-images.githubusercontent.com/66316855/189963855-737521a8-690e-461f-995c-07387cf4c4c1.png)

### Operating system

Windows 10 v 21H2

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Sounds like a Qt bug
