### ISSUE TITLE
Multi window chat - taskbar new message notification - no flash - incorrect message count

### ISSUE THREAD

**Issue by R1gg4** [telegramdesktop/tdesktop#25056]
I use telegram to chat on several open chat windows, i find the ctrl+click to open a new chat window excellent.. and have now ditched skype completely as this was the feature i was waiting for.

However the notification of new messages is not quite right. 

- It displays the wrong message count - if i receive a single message in one of the windows it displays the same number on both open chat windows. (as shown in the attached image, this was from a single message being received in one of the chat windows.)

![TelegramNotifications](https://user-images.githubusercontent.com/52033287/190106755-32cd3777-6919-44ba-aebe-f7abd46247ed.png)

- It also no longer highlights the task bar icon when new messages are received (which i think it used to do!)

It would be perfect if the relevant taskbar icon would highlight and show the correct new message number from only that chat.

**Comment by R1gg4** [comment]
Update: the correct task bar button does now highlight and flash, when it receives a message. 

![image](https://user-images.githubusercontent.com/52033287/224948614-c0eead29-78f2-49cd-a54d-70cd3f49fb94.png)

However as you can see the number is still incorrect. In the above situation i only received a message from 'Chris Aucken' there is no message on the 'InTouch' group, yet it still shows (1).

**Comment by john-preston** [comment]
@R1gg4 " — (1)" is the total unread count in the whole app. The chat-only unread count goes before the name.
