### ISSUE TITLE
Telegram window is smaller and smaller, constantly changes the size of the window

### ISSUE THREAD

**Issue by xawex465** [telegramdesktop/tdesktop#25053]
### Steps to reproduce

1. Put telegram in fullscreen
2. Reinstall
3. I held down shift and pressed x to exit

### Expected behaviour

I expect Telegram to start with the same window size as when I closed it

### Actual behaviour

Like in the topic: telegram window is smaller and smaller, constantly changes the size of the window

### Operating system

Windows 10 Enterprise LTSC 2021

### Version of Telegram Desktop

v4.1.1

### Installation source

Microsoft Store

**Comment by xawex465** [comment]
https://youtu.be/hc19hMUKJk8
 
this video shows what is going on more precisely the window from closing the application to the next closing is getting smaller which is terribly annoying

**Comment by xawex465** [comment]
Update: everything is fine on the native version

**Comment by ilya-fedin** [comment]
Are you sure the store version is really 4.1.1? Maybe it's 4.1.0 actually?

**Comment by xawex465** [comment]
> Are you sure the store version is really 4.1.1? Maybe it's 4.1.0 actually?

When i had microsoft store installed it shows 4.1 only so I thought it was the latest release, so it comes out to be 4.1.0? the microsoft store version is less frequently updated?

**Comment by ilya-fedin** [comment]
Well, check in the application itself

**Comment by xawex465** [comment]
yes you are right in 4.1.1 has fixed the problem which describes
