### ISSUE TITLE
Collapsible contact sidebar disappears when window width is reasonably large

### ISSUE THREAD

**Issue by mondalaci** [telegramdesktop/tdesktop#25068]
### Steps to reproduce

1. Open Telegram
2. Open a conversation
3. Collapse the sidebar so that only contact icons are visible
4. Decrease the width of the Telegram window to 1314 px or less (according to `xwininfo -id $(xdotool getactivewindow)`
5. The sidebar disappears

I use the Cinnamon desktop environment on Linux Mint 20.3 on a 4K display with high DPI enabled.

### Expected behaviour

The breakpoint below which the collapsed contact sidebar disappears should be much less than 1314px.

### Actual behaviour

The sidebar disappears when the window width is reasonably large. This bug makes Telegram occupy more space than needed, and my other applications don't have sufficient space.

### Operating system

Linux

### Version of Telegram Desktop

4.1.1

### Installation source

Snap

**Comment by ilya-fedin** [comment]
> The breakpoint below which the collapsed contact sidebar disappears should be much less than 1314px.

I see at that point the history view is about to be too narrow to display anything readable, so this is not a bug.
