### ISSUE TITLE
Terrible UI unresponsiveness when viewing a screenshare on Linux

### ISSUE THREAD

**Issue by PAI5REECHO** [telegramdesktop/tdesktop#25066]
### Steps to reproduce

1. Start a call with a user
2. Have other user in call begin screensharing
3. Experience extreme UI responsiveness lag (~3 FPS)

### Expected behaviour

Viewing a screenshare shouldn't effect UI responsiveness

### Actual behaviour

Viewing a screenshare causes terrible UI unresponsiveness. The client spends tons of time inside `Webrtc::details::AudioDeviceOpenAL::processRecordedPart` when a screenshare is ongoing by another user.
## Without screenshare
![flamegraph](https://user-images.githubusercontent.com/96688573/190616529-6628201d-25bd-4ecd-a86a-3c29217d0f3a.svg)
## With screenshare
![flamegraph laggy](https://user-images.githubusercontent.com/96688573/190616572-f6512bfb-9d51-452d-b852-38dfd240aa86.svg)

### Operating system

NixOS 22.11 Raccoon (22.11.20220910.93a0067) & SwayWM (1.8-dev)

### Version of Telegram Desktop

4.1.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Do you mean this is Wayland-specific and is not reproducible on X11 by specifying Wayland in the title?

**Comment by PAI5REECHO** [comment]
@ilya-fedi I haven't tested this with Xorg, so I'm unsure if it's Wayland specific. I've edited the issue title.

**Comment by ilya-fedin** [comment]
I wonder what application provides those graphs as on your screenshot?

**Comment by PAI5REECHO** [comment]
> I wonder what application provides those graphs as on your screenshot?

https://github.com/flamegraph-rs/flamegraph (`timeout --signal INT 30s flamegraph --freq 3000 --pid $(pidof telegram-desktop)`)

**Comment by ilya-fedin** [comment]
Are you sure this is the cause though? This code executes on a separate thread that has nothing to do with UI.

**Comment by PAI5REECHO** [comment]
I just tried to reproduce this again and the UI isn't being unresponsive (using 3.6 instead of 4.X currently) so Idk what was causing this previously. I will reopen if I come across this again.
