### ISSUE TITLE
Application hangs up completely when clicking notifications too fast

### ISSUE THREAD

**Issue by Lillecarl** [telegramdesktop/tdesktop#2506]
### Steps to reproduce
1. Get a message
2. Click notification ("instantly")
3. See Telegram hang up

### Expected behaviour
It should not hang up

### Actual behaviour
It hangs up completely, 

taskkill /F /IM telegram.exe
Then starting telegram "solves" the problem (it doesn't recrash for awhile)

### Configuration
**Operating system:**
https://gist.github.com/Lillecarl/3852eedfcb17f905b41bb0eb4af9e0e0
**Version of Telegram Desktop:**
0.10.11
### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.
Enabled debug mode, though where are they located on Windows so i can submit them once i get them?

**Comment by john-preston** [comment]
@Lillecarl I'm afraid this are windows toast notifications hanging somewhere =( In the near update I'll have to disable them by default (you can disable them in Settings right now to try if it fixes the issue).

**Comment by Lillecarl** [comment]
http://i.imgur.com/lb4xBgx.png

Ill try disabling "Use Windows notifications" at first and report back =)

@john-preston Thanks for the quick and honest response! :)

**Comment by Lillecarl** [comment]
Using telegrams own notifications seem to resolve the issue, though they do not seem to always appear, i **guess** this might have something to do with maybe that im switchin between phone and desktop alot and it doesn't wanna send notifications everywhere.
