### ISSUE TITLE
[Feature Request] Replace crop with blur

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25061]
### Is your feature request related to a problem?

Some pictures showing cropped and I must open them to fullscreen to see all content. Example:
https://t.me/pul_1/6745

Cropped:
![image](https://user-images.githubusercontent.com/39812401/190383757-b49b15dd-847c-4591-8a7d-0b3b42fce7e2.png)

Full:
![image](https://user-images.githubusercontent.com/39812401/190383826-edbd19f8-167f-4709-9838-10658053860c.png)

I think all because of new blur effect (https://github.com/telegramdesktop/tdesktop/commit/20b5138e006bb9fce0329dcdd70e09570a9e7fed or https://github.com/telegramdesktop/tdesktop/commit/00ee31ce2d4125d60593bb8a4fa20645604a8103)

### Describe the solution you'd like

Replace crop for images with blur effect that was added in 4.1.2 beta. Example:
![image](https://user-images.githubusercontent.com/39812401/190384199-b2d524fa-72c9-473f-8192-53aad410c7f2.png)

On iOS these posts looks fine even without blur:
![image](https://user-images.githubusercontent.com/39812401/190504691-d7d423ea-f81e-4bb8-a707-b1671da5142c.png)

### Describe alternatives you've considered

No

**Comment by Laiteux** [comment]
Yep.

Noticed the same here with friends who also updated to 4.1.2 beta:

![Telegram_m2On6HgSUa](https://user-images.githubusercontent.com/33204743/190501523-359caa0a-c724-44af-8aa1-07289f06ab1f.jpg)

While on 4.1.1:

![image](https://user-images.githubusercontent.com/33204743/190501498-b6d70fbf-f083-4eda-8e82-18ca7c3aac41.png)

Very annoying and imo a regression if this was done on purpose. The black bars were super useful and a lot better.

I would guess it is 00ee31ce2d4125d60593bb8a4fa20645604a8103 by @john-preston which introduced this.

Can we get any dev input on this? Hopefully this wasn't done on purpose, really sucks having to click on every image to see it entirely.

**Comment by Neurotoxin001** [comment]
I think this is too https://github.com/telegramdesktop/tdesktop/commit/20b5138e006bb9fce0329dcdd70e09570a9e7fed

**Comment by Laiteux** [comment]
Why would a commit supposed to introduce side blur also remove top and bottom black bars?

Was this on purpose or is it a mistake / omission?

If not happy with the black bars, couldn't these also be replaced by blur then, just like the side blur effect we now have?

**Comment by Neurotoxin001** [comment]
On iOS we have blur also, but I never seen black bars here

![image](https://user-images.githubusercontent.com/39812401/190503483-24cd47d1-6ab5-497b-bc29-c73409a94d4c.png)

**Comment by Neurotoxin001** [comment]
> Very good job with the side blur effect while we're at it, I think this was really needed! No more multi-line captions even for small ones (:


Yes, blur is fine, but not crop

**Comment by Laiteux** [comment]
Black bars were for vertical media on desktop, before 4.1.2 beta.

You're right, it looks like iOS already had a blur effect for vertical media as well!

Would be very nice having the same on desktop. I guess this is just an omission from the devs then, and hopefully nothing to worry about 😄

**Comment by Laiteux** [comment]
Actually, it looks like it also is a thing on tdesktop.

![Telegram_2zuXK2JGXn](https://user-images.githubusercontent.com/33204743/190504187-d9fdf3e3-aea1-4351-a6f4-5f310731cb85.jpg)

And this is how it looks on iOS:

![image](https://user-images.githubusercontent.com/33204743/190504345-9de1b01f-af12-4e88-a9e1-5f5451fb6e47.png)

Confused then. Seems to depend on the width/height ratio?

**Comment by john-preston** [comment]
Now the width of the media depends on the caption to let it fit in. If the blurred lines on sides happen to be too thin the media is zoomed instead. This happens if less than 0.25 of the photo is cropped.

You can see the same thing with video files with captions on mobile.

**Comment by Neurotoxin001** [comment]
> You can see the same thing with video files with captions on mobile.

I can't remember photos being cropped on iOS. Video - yes, maybe, but not a photo.

**Comment by Neurotoxin001** [comment]
> This happens if less than 0.25 of the photo is cropped.

On iOS even that little area with blur, not crop:
![image](https://user-images.githubusercontent.com/39812401/190590696-f4e718db-9a2d-4e51-b842-27d0f72b44cb.png)

https://t.me/dvachannel/101437

**Comment by Laiteux** [comment]
An other example as to why this is a bad thing: My friends now all have to click on a picture if they want to be able to read what's written.

![Telegram_JdCJPhcfSQ](https://user-images.githubusercontent.com/33204743/190708097-9212bf95-9a9a-497b-8ccc-581b0c4186c7.jpg)

**Comment by Neurotoxin001** [comment]
Really...
https://t.me/topor/22901

![image](https://user-images.githubusercontent.com/39812401/190852392-3c59a124-6e52-46e2-bc3f-061afd644fd9.png)
![image](https://user-images.githubusercontent.com/39812401/190852400-3699777a-3b39-480b-88e1-c58c2ca8f9b3.png)

**Comment by Neurotoxin001** [comment]
Really...

![image](https://user-images.githubusercontent.com/39812401/190867347-6e648988-6267-4a4a-8593-2f46fd3e59f3.png)
![image](https://user-images.githubusercontent.com/39812401/190867353-6128451c-6b1f-4cfb-814e-56e5a3c7fe65.png)

https://t.me/c/1237513492/35902 (https://t.me/+mXumAD42hYpkOWUy)

**Comment by Neurotoxin001** [comment]
Press play on it https://t.me/kepka_support/124050

It's cropped even when playing. Users must open it in full screen to see all content.

**Comment by Neurotoxin001** [comment]
No answers about these ridiculous examples above?

**Comment by Neurotoxin001** [comment]
This is literally CRINGE. I can't write posts like this:

Long text

Shortest text

https://user-images.githubusercontent.com/39812401/190914317-d300adc2-fb9d-4e3e-9b80-915c7a67ed6e.mp4

**Comment by Laiteux** [comment]
I think they understood. Sending multiple messages a day will never help with getting a faster response.

**Comment by Neurotoxin001** [comment]
> I think they understood. Sending multiple messages a day will never help with getting a faster response.

I just showing more examples...

**Comment by Neurotoxin001** [comment]
![image](https://user-images.githubusercontent.com/39812401/190921445-843f6651-b6fd-4e32-ab8c-809acfc6ec5b.png)

https://t.me/dvachannel/101673

**Comment by Neurotoxin001** [comment]
Thanks ❗️❗️❗️

**Comment by Laiteux** [comment]
❤️‍🔥

**Comment by john-preston** [comment]
Ok, I hope this way it'll be better.

The photos now should not crop:

For vertical crop - now they should either become larger vertically (if it was going to be cropped before) or be like before with blurred sides.

For horizontal crop - just allow blurred top and bottom strips even if they're very thin, I don't think very thin horizontal photos are frequently used.

But the videos are cropped as before (because having blurred strips on videos is not CPU friendly at all, so I try to use them only for very thin videos).

**Comment by john-preston** [comment]
Maybe videos could be allowed to have 3x2 aspect ratio with max width as well (as was done for photos) then they'll be less cropped (cropped as well sometimes, but not that frequently).

**Comment by Laiteux** [comment]
Amazing, thanks a lot!

About videos... Maybe you could them cropped, and only allow GIFs to always be full size (uncropped)?

The reasoning behind this would be that GIFs do not have sound, and therefore, unlike videos, do not require you to click on them to show them full-sized and with sound.

Since videos require you to click on them to watch them with sound, it would make sense. However, GIFs do not have sound and therefore could be shown full-size by default anyway.

GIFs are also very often someone demonstrating something on a computer, or these GIFs Telegram offers by default. I think it would make sense to have them uncropped.

After all, GIFs are just photo frames put together, so maybe they should behave just like photos (:

_Yeah, videos are also photo frames put together and with an audio track on top, but let's not get too political. Or maybe just do both, after all?_

**Comment by Laiteux** [comment]
@john-preston I'm not really sure about how GitHub notifications behave when an issue is closed, so I'll ping you this one time just to make sure you see this. (:

**Comment by john-preston** [comment]
> After all, GIFs are just photo frames put together, so maybe they should behave just like photos (:

The videos (and GIFs) are cropped in more cases than left with blurred background because blurring the auto-playing videos (= GIFs) is very CPU-consuming and I'd like to do that less often. I've allowed the height of videos / GIFs to expand 33% more, but if the video has a long caption (so that full available width is used) and the height is more than width * 1.33 it still will be cropped.. until it won't, if the height is more than width * 2, in that case we'll show blurred strips on the sides.

**Comment by Neurotoxin001** [comment]
I think now videos is too big.

Example:
https://t.me/dvachannel/102079

4.2.1 beta:
![image](https://user-images.githubusercontent.com/39812401/191910176-f3f5c145-2972-47f8-9e9a-73e9d213abf1.png)


3.5.2:
![image](https://user-images.githubusercontent.com/39812401/191910157-2db597da-c37a-406a-ba7b-d88f74c90f6e.png)

**Comment by Neurotoxin001** [comment]
Same with photos
https://t.me/c/1460007515/63487 (https://t.me/+fG_afcLq6t5lYTFi)

4.2.1 beta:
![image](https://user-images.githubusercontent.com/39812401/191929576-c41ec9d5-8fcc-4a55-ae1e-bc1f0f9239df.png)

1.4.9:
![image](https://user-images.githubusercontent.com/39812401/191929661-518946a0-0405-460c-853d-ae3efaa93931.png)

**Comment by Neurotoxin001** [comment]
New example:
https://t.me/po_memes/9604

It's not enlarged and stay cropped.
[![image]()](https://user-images.githubusercontent.com/39812401/195060141-a29d3284-29dd-4ed2-b119-9e3610c157db.png)

**Comment by Neurotoxin001** [comment]
Another example:
https://t.me/jolymemes/16281

![image](https://user-images.githubusercontent.com/39812401/196030258-f2ffbc48-aebb-455e-8297-c32784a2f371.png)

Text is cropped

**Comment by john-preston** [comment]
@Neurotoxin001 The last examples are without captions so it’s some different case. I’ll look into that.

**Comment by Neurotoxin001** [comment]
With caption:
https://t.me/retra/17475
![image](https://user-images.githubusercontent.com/39812401/196364974-ba8413a1-ca2e-4ac9-883e-b1e3cd541363.png)

**Comment by Neurotoxin001** [comment]
Btw, on iOS videos don't even adds blur if their cropped. It's just play while cropped.

![image](https://user-images.githubusercontent.com/39812401/200309307-d1d658e0-bb01-48b6-869f-de8d52869ef2.png)
![image](https://user-images.githubusercontent.com/39812401/200309317-ca6b7675-b2b3-46fb-bcad-ccfe9f645cd9.png)

Example:
https://t.me/dvachannel/105382

**Comment by Neurotoxin001** [comment]
>The last examples are without captions so it’s some different case. I’ll look into that. 

@john-preston Should I create new ticket to improve that change or you can reopen this? For example in Gram64 client (https://github.com/TDesktop-x64/tdesktop) posts that I mentioned above it have blurred borders and it's look fine. Btw I tested autoplay for videos with blurred borders and they eating CPU just like videos without blurred borders - ~10-11% usage.

![1616 2022-11-16 11-33-04-762](https://user-images.githubusercontent.com/39812401/202129270-a5ae64ab-fa0e-4cc9-8696-50eaafba16b1.png)
![1618 2022-11-16 11-33-13-898](https://user-images.githubusercontent.com/39812401/202129290-f8773a6c-187a-4df1-b47f-e4c40f832bb3.png)

**Comment by Neurotoxin001** [comment]
Another strange example:
https://t.me/chtddd/57815
![image](https://user-images.githubusercontent.com/39812401/203751767-554a14a7-f1df-47bc-8566-5d1836f480b9.png)

![image](https://user-images.githubusercontent.com/39812401/203751795-0e866e93-a481-48c9-baac-d0ae232e1752.png)

Small video become very large and cropped without blur

**Comment by john-preston** [comment]
You can create. I don't have time for those right now and the captions are better visible now which I believe is an improvement. Maybe some more improvements are necessary.

**Comment by Neurotoxin001** [comment]
Another with caption:
https://t.me/memeblogteam/936
![image](https://user-images.githubusercontent.com/39812401/208412159-fcd4307c-5005-449b-87ed-6c8fe381d954.png)

**Comment by Neurotoxin001** [comment]
I haven't seen a buggy images/gif in almost a year, so I think we can close it.
