### ISSUE TITLE
React with the premium reaction for free in v4.1.2 beta

### ISSUE THREAD

**Issue by masreplay** [telegramdesktop/tdesktop#25060]
### Steps to reproduce

1. open any chat on a mac
2. hover over the message and select premium reaction

### Expected behaviour

![Uploading image.png…]()

### Actual behaviour

Remove premium reaction on free tier

### Operating system

mac os

### Version of Telegram Desktop

v4.1.2 beta

### Installation source

Mac App Store

**Comment by Aokromes** [comment]
old premium reactions aren't premium now.
