### ISSUE TITLE
Custom emoji status disappears after re-enter in chat

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25062]
### Steps to reproduce

1. Write something in chat
2. Users will see your custom emoji icon instead of premium star
3. When they re-enter in chat they will see premium star
4. Custom emoji will show only for new messages until users close the chat

Custom emoji:
![image](https://user-images.githubusercontent.com/39812401/190402830-3f509c37-6bdf-4522-80d6-15950e869588.png)

After re-enter in chat:
![image](https://user-images.githubusercontent.com/39812401/190402863-1e3a89bf-46b0-4210-ba14-5f768a007f3d.png)

### Operating system

Windows 10

### Version of Telegram Desktop

4.1.2 beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@Neurotoxin001 Thanks! Fixed for the stable version.
