### ISSUE TITLE
[Feature Request] FIX the close button. Properly, please! 

### ISSUE THREAD

**Issue by Ryder17z** [telegramdesktop/tdesktop#25065]
### Is your feature request related to a problem?

Continuation on #17063

Tray icon **should not** dictate how the "close" button should behave. It's called "close" for a reason.

### Describe the solution you'd like

Add the needed setting to avoid confusion and letting users keep the try icon

### Describe alternatives you've considered

N/A

**Comment by john-preston** [comment]
@Ryder17z Close button closes the window, but doesn't quit the application. It is a close button, not a quit button, quit button is in the tray menu.

**Comment by Ryder17z** [comment]
> @Ryder17z Close button closes the window, but doesn't quit the application. It is a close button, not a quit button, quit button is in the tray menu.

What do you think it does in other applications?

**Comment by john-preston** [comment]
@Ryder17z It closes the window and if the application doesn't have any functions when all its windows are closed it quits the application as well. In case of messengers the app has a very important feature (core app feature) to receive messages and show notifications about the new messages, so it usually doesn't quit the application, just closes the window. If you really don't need notifications about new unread messages you can always quit the application from tray.

**Comment by john-preston** [comment]
@Ryder17z You can also use "Ctrl+Q" shortcut to quit.

**Comment by Aokromes** [comment]
> ### Is your feature request related to a problem?
> Continuation on #17063
> 
> Tray icon **should not** dictate how the "close" button should behave. It's called "close" for a reason.

every application with "minimize to tray" i know works on that way.

**Comment by Ryder17z** [comment]
> > ### Is your feature request related to a problem?
> > Continuation on #17063
> > Tray icon **should not** dictate how the "close" button should behave. It's called "close" for a reason.
> 
> every application with "minimize to tray" i know works on that way.

IceChat, Tixati, etc do not do this, they do what they should do.
