### ISSUE TITLE
Abnormally large mouse cursor in GNOME 42

### ISSUE THREAD

**Issue by proninyaroslav** [telegramdesktop/tdesktop#25075]
### Steps to reproduce

1. Install Fedora 36, install latest Telegram version (4.2) from Flathub https://flathub.org/apps/details/org.telegram.desktop
2. Open the app window and hover the mouse cursor over it

### Expected behaviour

The mouse cursor must match the system size cursor

### Actual behaviour

The mouse cursor in Telegram window is larger than in the system:

![Снимок экрана от 2022-09-17 10-21-19](https://user-images.githubusercontent.com/7840559/190845634-9cd057db-ebc5-4d30-b0c5-e4fd7b9af87b.png) ![Снимок экрана от 2022-09-17 10-21-24](https://user-images.githubusercontent.com/7840559/190845639-fcd5fd84-7bff-4d92-87f8-172935e4e926.png)

![Снимок экрана от 2022-09-17 10-18-17](https://user-images.githubusercontent.com/7840559/190845652-7d311321-370c-4ee7-9aa6-2d1ca7dcd9b2.png)

### Operating system

Fedora 36, GNOME 42.4

### Version of Telegram Desktop

4.2

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Unfortunately, GNOME doesn't set cursor theme and size settings for non-gtk applications operating in native Wayland mode. You need to do one of three things:
1. Ask your DE to support setting cursor settings for non-gtk applications
1. Ask your distribution to support setting cursor settings for non-gtk applications
1. Set XCURSOR_THEME and XCURSOR_SIZE environment variables manually (that's how Qt, mpv and SDL get those settings on Wayland)

**Comment by proninyaroslav** [comment]
@ilya-fedin 
But it worked before updating to version 4.2

**Comment by ilya-fedin** [comment]
Apparently it used XWayland

**Comment by proninyaroslav** [comment]
@ilya-fedin 
Yes, you are right, I found your bug report:
https://bugreports.qt.io/browse/QTBUG-67579
Do I understand correctly that there is currently no solution other than setting the `XCURSOR_*` environment variable?

**Comment by ilya-fedin** [comment]
Well, it's not my bug report. Yeah, there's no solution, it's DE that should set the variable (like Plasma & sway do), but GNOME seem to ignore everything that is not gtk unfortunately.

**Comment by proninyaroslav** [comment]
Ok, I think I can close this issue.

**Comment by proninyaroslav** [comment]
I made this solution in the `.bashrc` file and it works fine:

`export XCURSOR_SIZE="$(gsettings get org.gnome.desktop.interface cursor-size)"`

**Comment by cichy1173** [comment]
> I made this solution in the `.bashrc` file and it works fine:
> 
> `export XCURSOR_SIZE="$(gsettings get org.gnome.desktop.interface cursor-size)"`

You can also downgrade Telegram if you want.

```bash
sudo flatpak update --commit=57c03c9a20a7537028ec8c344d52b287f41487a507678f61c0a8cebb4eaf7702 org.telegram.desktop
```

**Comment by carlocastoldi** [comment]
@ilya-fedin fyi over [at GNOME](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5894) want to push for using the appropriate desktop Portal.
However, they are aware of the issue that the the keys are in the gnome namespace. As far as i understood they'll try to push a key name that is desktop agnostic for cursor settings

**Comment by ilya-fedin** [comment]
Oh, I feel this will have a hard time being implemented in Qt... Don't they want to consult with Qt first? This may end in situation staying the same after all.

**Comment by carlocastoldi** [comment]
> I feel this will have a hard time being implemented in Qt

why you think so? Does Qt have a record of not wanting to support desktop portals?

**Comment by ilya-fedin** [comment]
It's not 'not wanting', it's rather a problem with Qt architecture to add support of new portals. Cursor setting are being gotten in QPA (Qt Platform Abstraction), as far as I heard, d-bus code is not allowed in QPA, it should go to QPT (Qt Platform Theme). Thus, cursor API should use the same libraries as other code of the platform (i.e. libxcb in xcb platform, libwayland in wayland platform).

**Comment by ilya-fedin** [comment]
I can be a deaf phone here, it's really better to consult with Qt before designing the API if they don't want Qt and other toolkits to be blocked for years on implementing this.

**Comment by carlocastoldi** [comment]
oh, i understand. Thank you for the clarification!
I will probably try to make it clear over on GNOME's issue, if you won't do it. The last thing we need is a "standard" that is not applicable by everybody.

P.S. fyi the proposed portal is [org.freedesktop.portal.Settings](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Settings). For example:
```bash
~
❯ gdbus call -e -d org.freedesktop.portal.Desktop -o /org/freedesktop/portal/desktop -m org.freedesktop.portal.Settings.Read '"org.gnome.desktop.interface"' '"cursor-theme"'
(<<'Adwaita'>>,)
```

**Comment by ilya-fedin** [comment]
Yeah, I know about the portal

**Comment by carlocastoldi** [comment]
[This issue](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/58) looks like a good starting point for a cross-toolkit discussion

**Comment by ilya-fedin** [comment]
Apparently
