### ISSUE TITLE
Collapsible contact sidebar disappears when window width is reasonably large

### ISSUE THREAD

**Issue by mondalaci** [telegramdesktop/tdesktop#25070]
### Steps to reproduce

I'm reposting this bug as it was falsely closed by @ilya-fedin. The view is *not* too narrow to display anything readable. See the following screenshot:

![Untitled](https://user-images.githubusercontent.com/300402/190717408-6df9e3bf-a8af-42b2-8f19-e36abc05838b.png)

Reducing the width of the above window even by a single pixel makes the left sidebar disappear.

1. Open Telegram
2. Open a conversation
3. Collapse the sidebar so that only contact icons are visible
4. Decrease the width of the Telegram window to 1314 px or less (according to `xwininfo -id $(xdotool getactivewindow)`
5. The sidebar disappears

I use the Cinnamon desktop environment on Linux Mint 20.3 on a 4K display with high DPI enabled.

### Expected behaviour

The breakpoint below which the collapsed contact sidebar disappears should be much less than 1314px.

### Actual behaviour

The sidebar disappears when the window width is reasonably large. This bug makes Telegram occupy more space than needed, and my other applications don't have sufficient space.

### Operating system

Linux

### Version of Telegram Desktop

4.1.1

### Installation source

Snap

**Comment by ilya-fedin** [comment]
It's not a bug, please stop creating duplicates

**Comment by mondalaci** [comment]
@ilya-fedin Would you explain why it's not a bug?

If, for any reason, you don't want to fix this, would you please point me to the relevant breakpoint integer so that I can create a custom build for myself?

**Comment by ilya-fedin** [comment]
> Would you explain why it's not a bug?

The current limit is intended AFAIK. Maybe you don't think it's about to be too narrow, but that's just your opinion.

> would you please point me to the relevant breakpoint integer so that I can create a custom build for myself?

https://github.com/telegramdesktop/tdesktop/blob/645ae69220fd0c0ef23e198499197b67099c5d13/Telegram/SourceFiles/window/window_session_controller.cpp#L1053-L1057
https://github.com/telegramdesktop/tdesktop/blob/645ae69220fd0c0ef23e198499197b67099c5d13/Telegram/SourceFiles/window/window.style#L21-L26
