### ISSUE TITLE
Telegram window becomes decorationless and skipTaskbar

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#25078]
### Steps to reproduce

I'm not sure how to reproduce it yet, maybe I occasionally press something (is that yet another easter egg, like the "chef is coming" mode?) It started recently and happened twice this week.

I'm also not sure if this is a Telegram or Compiz bug, but I didn't upgrade neither Compiz-Reloaded nor the system libraries for many months, so I'm likely to blame the former.

### Expected behaviour

No occasional loss of decorations.

### Actual behaviour

![2022-09-17-150229_1366x768_scrot](https://user-images.githubusercontent.com/2134486/190856175-897f6be7-8489-4c36-b6a6-ae3abfd8ba27.png)

The window becomes always-on-top, skipTaskbar, skipPager, and sticked to all virtual desktops (maybe it gets all possible NET_WM flags actually!), like a splashscreen, with a size it had when it was decorated. Keyboard focus always goes to the underlying window, but the Telegram window can still be controlled with a pointer device. When Compiz is restarted, Telegram becomes a normal window again.

### Operating system

Debian GNU/Linux 12, compiz-reloaded 0.8.18

### Version of Telegram Desktop

4.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can you reproduce by opening and closing context menu?

**Comment by bodqhrohro** [comment]
> Can you reproduce by opening and closing context menu?

Yes.

**Comment by ilya-fedin** [comment]
Apprently this is a side-effect of an attempt to fix #1041. The fix sets Qt::X11BypassWindowManagerHint while closing the menu and then unsets it, but apprently your WM doesn't correctly handle that.

**Comment by bodqhrohro** [comment]
Yeah, a side-effect ×D
https://www.youtube.com/watch?v=2UxNcSzAOXk
