### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by AlenaZuk** [telegramdesktop/tdesktop#25074]
### Steps to reproduce

When the channel is added to the folder, an emergency completion of the program occurs

### Expected behaviour

.

### Actual behaviour

.

### Operating system

debian 11 xfce

### Version of Telegram Desktop

4.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Provide crash report tag

**Comment by AlenaZuk** [comment]
[log.txt](https://github.com/telegramdesktop/tdesktop/files/9591058/log.txt)
[33a1da2c-ee1b-4e5c-4eb6ba85-86282950.dmp.zip](https://github.com/telegramdesktop/tdesktop/files/9591063/33a1da2c-ee1b-4e5c-4eb6ba85-86282950.dmp.zip)

**Comment by vsile** [comment]
The same issue while adding Telegram group to the folder.
Telegram Desktop 4.2

**Comment by ilya-fedin** [comment]
This couldn't be investigated without crash report tag, sorry

**Comment by vsile** [comment]
@ilya-fedin 
Your Report Tag: 350868f5-aca8-4019-abdbe399-078921b1 
Your User Tag: 70c3fed4d9431184

**Comment by john-preston** [comment]
@vsile Nothing can be read from there, sorry :( It shows one stack frame without any source information.

It shows some corrupted string as the binary name, specifically "~/Загрузки/Telegram/Telegram^@^@^@^@^@^@^@^@".

Is it possible you move and rename it to something like "~/Tmp/Telegram"? And then send one more crash report and post one more tag here.

I doubt this is the reason of a bad crash dump, but who knows.

**Comment by vsile** [comment]
I moved Telegram directory (with Telegram and Updater files) to ~/go/Telegram and launched it from the terminal.
After adding the Telegram group to the folder it crashed again.
```
Your Report Tag: f5a4d09d-2033-455d-44525b8b-a297b64d 
Your User Tag: 70c3fed4d9431184
```
In the terminal I got this error:

vera@fedora:~/go/Telegram$ ./Telegram 
Ошибка сегментирования (стек памяти сброшен на диск)

**Comment by bskydive** [comment]
see ~/.local/share/TelegramDesktop/tdata/working.txt

**Comment by bskydive** [comment]
upvoting: crash after trying to delete the empty folder, maybe incorrect folder limitation for free account?

**Comment by bskydive** [comment]
steps: open tg, open folder settings, remove all groups from folder, delete folder. click to popup close button or outside popup window

**Comment by bskydive** [comment]
BTW, please, add in FAQ section how to make crash tag report and where the logs placed

**Comment by ilya-fedin** [comment]
Do we have FAQ?

**Comment by bskydive** [comment]
Donno)
@AlenaZuk rename ticket to "crash on settings popup close" please

**Comment by bskydive** [comment]
@ilya-fedin do you need my crash dump?

**Comment by ilya-fedin** [comment]
That's a question for @john-preston, only he has access to debug symbols
