### ISSUE TITLE
[Feature] Download many medias once

### ISSUE THREAD

**Issue by laccf** [telegramdesktop/tdesktop#2507]
### Steps to reproduce
1. click in a contact
2. click left button on a media
3. click select message
   - repeat step 3 as you want
### Expected behaviour

Tell us what should happen
1 - It should appear a button on the top bar for download media
### Actual behaviour

Tell us what happens instead
1 - it's only showed "forward" and "delete" button
### Configuration

**Operating system:**
windows 10

**Version of Telegram Desktop:**
0.10.11
### Logs

Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by Aokromes** [comment]
#809 ?
