### ISSUE TITLE
Telegram Flatpak version is not working on background on Fedora 36 and Gnome 42. No tray icon there.

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [telegramdesktop/tdesktop#25083]
### Steps to reproduce

1, Install telegram from Flathub
2. Run it and login
3. Close the telegram window (or windows)
4. Check tray icon is not shown. (using Tray Icons: Reloaded (https://extensions.gnome.org/extension/2890/tray-icons-reloaded/)

### Expected behaviour

Telegram leaves in tray and will work on background

### Actual behaviour

It is completely closing. Permission for background tasks is given through Flatseal

### Operating system

Fedora 36

### Version of Telegram Desktop

4.2

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
According to its readme, it's not compatible with Wayland: https://github.com/MartinPL/Tray-Icons-Reloaded#compatibility
And flatpak package has enhardened permissions starting with 4.2, so you need an extension compatible with Wayland.

**Comment by muhammadyusuf-kurbonov** [comment]
Thanks
