### ISSUE TITLE
Mouse scrolling is not working in TWA on Linux

### ISSUE THREAD

**Issue by slavafomin** [telegramdesktop/tdesktop#25086]
### Steps to reproduce

1. Start the @DurgerKingBot
2. Open the TWA
3. Try to use the scroll wheel

### Expected behaviour

It should scroll as usual.

### Actual behaviour

It's not reacting to any mousewheel events.

### Operating system

Ubuntu 22.04.1 LTS, Linux 5.15.10-051510-generic, XFCE 4.16

### Version of Telegram Desktop

4.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
TWA?

**Comment by lesykm** [comment]
From time to time scrolling stops working in Both in chat window and contact list.
Cannot find exact steps to reproduce, will try to find tomorrow.
Version - 4.2.0
OS - Kubuntu 22.04
DE - KDE

**Comment by ilya-fedin** [comment]
@lesykm this report is about some 'TWA', not about chat window or contact list

**Comment by slavafomin** [comment]
@ilya-fedin TWA is a [Telegram Web App](https://core.telegram.org/bots/webapps).

**Comment by ilya-fedin** [comment]
I can reproduce, but this doesn't happen on KDE, looks like a xfwm bug, can you report to xfwm?

**Comment by slavafomin** [comment]
I'm not sure what is the `xfwm`, so I won't be a able to properly file a bug report I'm afraid. I'm not a desktop developer and I'm not familiar with all the details regarding X window system, windows managers and all the related abstraction layers.

**Comment by ilya-fedin** [comment]
xfwm is Xfce's window manager, you can report to https://gitlab.xfce.org/xfce/xfwm4/-/issues/. Unfortunately, I'm not an Xfce user and I don't think my X11 knowledge is any better than you (note that there's not so much people really knowing X11 on this planet), so I won't report as well. Note that tdesktop project has no X11 experts, so if you won't report to xfwm, your issue will stuck and I'll add it to #25126. Should I do that?

**Comment by slavafomin** [comment]
I really don't know how to file an actionable bug report regarding this. Of course, I can just copy the report that I've done here, but it will lack any technical/debugging details and will probably be ignored/closed.

I think the person knowing how Telegram Desktop actually integrates with the window system should be more suitable for escalating this report.

**Comment by ilya-fedin** [comment]
This issue is now a part of #25126

**Comment by ilya-fedin** [comment]
> I think the person knowing how Telegram Desktop actually integrates with the window system should be more suitable for escalating this report.

A note: no one knows how it actually integrates in tdesktop. We're using Qt's QWidget::createWindowContainer method and then Qt does some magic. We don't know what it actually doing.

**Comment by slavafomin** [comment]
@ilya-fedin it looks like we should escalate this to the Qt then.

**Comment by ilya-fedin** [comment]
Someone has to write a minimal reproducible example, unfortunately. I don't know how to make one as tdesktop connects Qt and gtk what requires a lot of code with multiprocessing and IPC.

**Comment by ilya-fedin** [comment]
I think It's much easier to report to xfwm. But I'm unfortunately not an Xfce user, so I wouldn't be able to do things they will ask.

**Comment by Myralllka** [comment]
I have the same issue. 
Arch Linux + i3wm
Arch Linux + Gnome3

**Comment by ilya-fedin** [comment]
@Myralllka web bots aren't supported on GNOME, so you can't have this issue

**Comment by Myralllka** [comment]
> @Myralllka web bots aren't supported on GNOME, so you can't have this issue

Omg my mistake, sorry, it is not in bots in TWA but everywhere (chats, main page, settings) in "community/telegram-desktop" application. Should I make a new Issue regarding that, if I wouldn't be able to fix it myself? 
Because I can not see anything related, and it was the closest one.

**Comment by ilya-fedin** [comment]
Please look the pinned issue

**Comment by alexkuz** [comment]
I have a similar issue in desktop application (Linux Mint 21.1 / Cinnamon / Flatpak, v4.6.5)  - mouse scrolling doesn't work, but touchpad scrolling works just fine.

**Comment by ilya-fedin** [comment]
@alexkuz in webview? Note that this issue is about scrolling not working in webview exclusively.

**Comment by alexkuz** [comment]
In a desktop app, not in a webview, it seems to be fixed in the latest version though, so nevermind. Should have checked it from the start, my bad.
