### ISSUE TITLE
Lost system window frame and noticed a bigger mouse cursor after last update

### ISSUE THREAD

**Issue by CCaroV** [telegramdesktop/tdesktop#25089]
### Steps to reproduce

Open telegram desktop. 

### Expected behaviour

Get system window frame and "normal" size mouse cursor. 

### Actual behaviour

No system window frame and a bigger mouse cursor. 

### Operating system

Fedora 36

### Version of Telegram Desktop

4.2

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
It seems Telegram is switched to native Wayland mode for you. This behavior is expected as GNOME doesn't provide system window frame for Wayland applications and doesn't set cursor settings for non-gtk applications. You have to request those features in GNOME bugtracker.

**Comment by CCaroV** [comment]
I've been using Fedora on Wayland for about a year and this is the first time I encounter this "issue". I guess Telegram was running using XWayland? Is it possible to run it again using XWayland then?

**Comment by ilya-fedin** [comment]
> When I do that I get `telegram-desktop killed by SIGABRT`

and nothing more? can you check tdesktop log?

**Comment by CCaroV** [comment]
```
$ flatpak run org.telegram.desktop 
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.
```

**Comment by ilya-fedin** [comment]
Can you show all override you made?

**Comment by CCaroV** [comment]
I used Flatseal
![Screenshot from 2022-09-19 09-01-06](https://user-images.githubusercontent.com/51457651/191036534-8cfd6c54-3edc-40c5-b112-877eb8828723.png)

**Comment by CCaroV** [comment]
TDesktop launches using Wayland when the socket is enabled.

**Comment by ilya-fedin** [comment]
Have you attempted to clear tdesktop data after the update?

**Comment by CCaroV** [comment]
Well... It just updated and the first thing I noticed was the big mouse cursor and all my info was there as usual. So I guess I didn't remove any data.

**Comment by ilya-fedin** [comment]
`flatpak override --show org.telegram.desktop`

**Comment by CCaroV** [comment]
```
$ flatpak override --show org.telegram.desktop
[Environment]
QT_QPA_PLATFORM=wayland
```

**Comment by ilya-fedin** [comment]
:rofl:

**Comment by ilya-fedin** [comment]
`flatpak override --reset org.telegram.desktop`

**Comment by ilya-fedin** [comment]
And then you can switch the sockets

**Comment by CCaroV** [comment]
Well.. It didn't work. I guess I'll get used to Telegram on Wayland then. Thanks for your assistance and the fast responses btw.

**Comment by ilya-fedin** [comment]
If it still doesn't launch without wayland socket permission, it means you have QT_QPA_PLATFORM set anywhere else as Qt does fallback to xcb by default if Wayland socket is not accessible
