### ISSUE TITLE
Telegram doesn't start (Flatpak, Ubuntu 22.04)

### ISSUE THREAD

**Issue by janopae** [telegramdesktop/tdesktop#25095]
### Steps to reproduce

I'm not sure if this is reproducible on every system. It should be, because Flatpak, but it shouldn't be, otherwise someone would have noticed.

I can reproduce it on my system using the following steps
1. Install current org.telegram.desktop Flatpak stable or beta from Flathub (`flatpak install org.telegram.desktop `)
2. `flatpak run org.telegram.desktop `

### Expected behaviour

I expect Telegram to open the main application window and not complain

### Actual behaviour

It doesn't start, but outputs the following:

```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, eglfs, offscreen, wayland-egl, minimalegl, vnc, xcb, wayland, vkkhrdisplay, minimal.
```

### Operating system

Ubuntu 22.04, Gnome 42.0, Wayland

### Version of Telegram Desktop

Commit 4a6e6a7334b4b25547519b2425fa6ec7bf07580d0a62254af76f8078e5be4781

### Installation source

Flatpak

### Logs

```shell
Where do I find the log.txt file?
```

**Comment by ilya-fedin** [comment]
Apparently you have an override of `QT_QPA_PLATFORM` variable. It's expected to fail as now the permissions are hardened and the package won't see the X11 socket if there's Wayland socket.

**Comment by janopae** [comment]
@ilya-fedin Thanks, i totally forgot that I once set this using `flatpak override`. Had to execute `flatpak override --user --unset-env=QT_QPA_PLATFORM` to get rid of it.

The reason I set this environment variable was that on Wayland, Telegram still has some issues, like the mouse pointer being too small on High DPI (and I liked the fact that you could use native window decorations on X11). I think the issue for this is #3350 and has been auto closed.

**Comment by ilya-fedin** [comment]
It's actually a GNOME issue, it doesn't set cursor settings for non-gtk applciations. You can set them manually with XCURSOR_THEME and XCURSOR_SIZE environmnent variables.

**Comment by janopae** [comment]
XCURSOR_SIZE worked only after I set XCURSOR_THEME (to Yaru). On a High DPI factor of 2, 24 was the correct cursor size.

Can you link this issue in #3350, so people finding this are going to know the solution?

**Comment by ilya-fedin** [comment]
> XCURSOR_SIZE worked only after I set XCURSOR_THEME (to Yaru).

That's logical, I guess Qt fallbacks to some embedded bitmaps that have only one size.

> Can you link this issue in #3350, so people finding this are going to know the solution?

No, it's locked. And I don't think it's about Wayland given the year :)

**Comment by ilya-fedin** [comment]
The GNOME Wayland problem is usually titled as 'too big cursor' as the default Qt's cursor size is 32 and the `default` (what is Qt's default) theme is defined on Fedora (what was the main source of Wayland users before)

**Comment by janopae** [comment]
> No, it's locked. And I don't think it's about Wayland given the year :)

Seems plausible. Thanks for the help!

**Comment by janopae** [comment]
In case someone is interested in the cursor issue: At Wayland, there's a discussion about offering protocol that would allow server side cursor themes: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/58

This would avoid issues like this one.

**Comment by ilya-fedin** [comment]
It seems, it's more silence than discussion
