### ISSUE TITLE
[Feature Request] Do not show "Reply" button when notification sender/text is hidden

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#2509]
![image](https://cloud.githubusercontent.com/assets/2780044/19198222/ab5ce8f6-8cc6-11e6-9c94-42d56cb3fc94.png)

### Steps to reproduce
1. Update to 0.10.12 alpha
2. Uncheck "Show sender name" and "Show message text" in settings  
3. Recieve some messages

### Expected behaviour
You shouldn't have "Reply button" since replying to unknown person or, if you allow sender name, replying to unknown message is hilarious.

### Actual behaviour
Hide "Reply" button when message text is hidden

### Configuration
**Operating system:** Windows 10 LTSB x64
**Version of Telegram Desktop:** 0.10.12 alpha

**Comment by john-preston** [comment]
@Kondra007 Yes, I guess it is correct to change the behavior that way.

**Comment by Kondra007** [comment]
Fixed in 0.10.13 alpha. Thanks!
