### ISSUE TITLE
Сrashes out of the "Telegram" on "Windows"

### ISSUE THREAD

**Issue by AnatoliiYarovyi** [telegramdesktop/tdesktop#25092]
### Steps to reproduce

1. Play some video in Telegram;
2. Waiting for the end of the video;
3. Press the play button again.

### Expected behaviour

Play the video again.

### Actual behaviour

When the video ends and you click on the video play button to play it again, the program will close itself.

### Operating system

Windows 10 21H2

### Version of Telegram Desktop

4.2 and previous versions

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by AnatoliiYarovyi** [comment]
I have enabled the beta.
But I didn't find "crash id", so I sent  "Your Report Tag": 8f81e945-66b4-4e85-8840-89998f067b89
I can send a screenshot of the report if needed.

**Comment by Aokromes** [comment]
that's the crash id :)

**Comment by john-preston** [comment]
@AnatoliiYarovyi Do you have 32 bit OS version? If not, can you try the same with the x64 version of the app, you can get it from:

https://telegram.org/dl/desktop/win64?beta=1

If it still crashes please post one more crash report tag.

**Comment by AnatoliiYarovyi** [comment]
@john-preston  I have followed your advice, reinstalled Telegram and everything works great now!
Thanks a lot!
