### ISSUE TITLE
Notifications are sometimes not clickable in MATE

### ISSUE THREAD

**Issue by Brawl345** [telegramdesktop/tdesktop#251]
With the MATE desktop environment, notifications aren't clickable sometimes. They are shown but nothing happens when you click on them. It happens not everytime, but very often and is really annoying.

**Comment by auchri** [comment]
Fixed?

**Comment by Brawl345** [comment]
Totally forgot about this issue, sorry!
It's fixed! Tested on Debian Testing.

**Comment by auchri** [comment]
Nice to hear :)
