### ISSUE TITLE
[Question] How can I remove beta version completely on archlinux?

### ISSUE THREAD

**Issue by Neo-29** [telegramdesktop/tdesktop#25107]
I removed entirely the dev version from my system and reinstalled the official stable version from arch repo>

Unfortunately, it's still the dev beta version which start.

I removed all the config as well.
Nothing works.

An idea?

**Comment by Aokromes** [comment]
i suggest you to ask on arch forums or whatever they use.

**Comment by Neo-29** [comment]
Well... If I asked here it's because I thought it was linked to something exclusive to the app itself or a special setting somewhere.
That being said, I solved it rebooting on Xorg instead of waykand and signing in again.
Closing the issue.
