### ISSUE TITLE
Problem with graphics on MacOS 10.15.7

### ISSUE THREAD

**Issue by alexanderstarling** [telegramdesktop/tdesktop#25106]
After last update Telegram emoji and photos looks like on screens. Black lines on pictures and no emoji

<img width="236" alt="Screenshot 2022-09-21 at 19 32 30" src="https://user-images.githubusercontent.com/73884683/191504884-d385c687-100d-4ff3-a47e-651b3f37b589.png">
<img width="350" alt="Screenshot 2022-09-21 at 19 33 59" src="https://user-images.githubusercontent.com/73884683/191504891-2efddf33-a010-4006-9d57-351d8b202a21.png">

**Comment by john-preston** [comment]
This looks like native macOS Telegram version, which is https://macos.telegram.org

This repository is about Telegram Desktop, cross-platform app, which is https://desktop.telegram.org, you can try it out :)

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
