### ISSUE TITLE
crash on mac after telegram update

### ISSUE THREAD

**Issue by lebed2045** [telegramdesktop/tdesktop#25101]
### Steps to reproduce

update the last version and try to open

### Expected behaviour

opened telegram

### Actual behaviour

<img width="256" alt="image" src="https://user-images.githubusercontent.com/1270800/191407533-06ec2ffb-412f-48a0-82a1-64d5fe7ca4ab.png">
logout doesn't help

### Operating system

mac

### Version of Telegram Desktop

last one, can't check right now because i can't open it

### Installation source

Mac App Store

**Comment by jay584584** [comment]
Same. Waiting for answer.

**Comment by ilya-fedin** [comment]
The icon on your screenshot doesn't look like the tdesktop, are you sure you're actually using [tdesktop](https://telegram.org/dl/desktop/mac_store)?

**Comment by jay584584** [comment]
> The icon on your screenshot doesn't look like the tdesktop one, are you sure you're actually using [tdesktop](https://telegram.org/dl/desktop/mac_store)?

From Telegram Mac (9.0.1 2022-09-19) version. This issue also forward to bugs.telegram.org/ , but no response yet.

**Comment by ilya-fedin** [comment]
It doesn't look like you're using tdesktop, latest version of tdesktop is 4.2.0: https://github.com/telegramdesktop/tdesktop/releases

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
