### ISSUE TITLE
Tray on Wayland (Sway)

### ISSUE THREAD

**Issue by kirizdev** [telegramdesktop/tdesktop#25103]
### Steps to reproduce

1. Open tg desktop
2. focus any other window
3. right click on the tray icon

### Expected behaviour

The menu should have Open Telegram if tg desktop is minimized. 

### Actual behaviour

The menu has Open Telegram if you focus any other window. 

### Operating system

Fedora Linux 36 (Thirty Six) x86_64, sway

### Version of Telegram Desktop

4.2.0

### Installation source

Static binary from official website

**Comment by kirizdev** [comment]
feb6107ce668c8baca8445f2a085de47f5bc9bb1 is related. I haven't tested it in GNOME, but I guess it does the same thing

**Comment by ilya-fedin** [comment]
Your panel needs to implement xdg-activavtion support for new versions of tdesktop to work correctly

**Comment by kirizdev** [comment]
> Your panel needs to implement xdg-activation support for new versions of tdesktop to work correctly

Yeah. You're right. Waybar doesn't support it yet, ig.
