### ISSUE TITLE
Emoji in name is elided in hamburger menu

### ISSUE THREAD

**Issue by ratijas** [telegramdesktop/tdesktop#25116]
### Steps to reproduce

I used to have a tent "⛺️" emoji as the only character of my "last name" field.

![edit name form](https://user-images.githubusercontent.com/6737986/191714219-9bb08912-0ee9-492d-a324-d5938771f7b8.png)

Since some months ago (and certainly before Telegram officially introduced status emoji feature) it started eliding my name in hamburger menu. Every other place seems fine though.

![Elided](https://user-images.githubusercontent.com/6737986/191714508-6778e096-8be1-44ca-be10-e780c66a85c9.png)

### Expected behaviour

Last name should not be elided

### Actual behaviour

Last name is elided.

### Operating system

Arch Linux

### Version of Telegram Desktop

4.2

### Installation source

Flatpak

**Comment by ratijas** [comment]
I've tracked this issue down to the layout calculations in `ComposedBadge` class.

```c++
		const auto &st = button->st();
		const auto skip = st.style.font->spacew;
		const auto textRightPosition = st.padding.left()
			+ st.style.font->width(text)
			+ skip;
		const auto minWidth = unreadWidth + premiumWidth + skip;
		const auto maxTextWidth = buttonSize.width()
			- minWidth
			- st.padding.right();
```

Logging all the variables showed that the text is drawn at its full intended width. `textRightPosition` is not reduced `min(max)` expression. So, `st.style.font->width(text)` must be lying about trailing emoji.

**Comment by ratijas** [comment]
If I add an extra skip — something that has been reverted some time ago — that a label can fit one single trailing emoji. But if I set the name to have two trailing emojis, they elide again. So the font width math is definitely wrong.

**Comment by ratijas** [comment]
https://github.com/telegramdesktop/tdesktop/blob/1350fa64f3d78ac639cc5e940ea2cda799648855/Telegram/SourceFiles/settings/settings_information.cpp#L145-L159

These are the lines I'm referring to.

**Comment by john-preston** [comment]
@ratijas Does it happen in 4.2.4? I can't reproduce.

![image](https://user-images.githubusercontent.com/17900494/195576109-dbc46bb8-8ffa-4f4e-9280-66e28e9e3a8c.png)

**Comment by john-preston** [comment]
Ok, I see, it happens with two.

**Comment by john-preston** [comment]
I'll fix that in the next version.
