### ISSUE TITLE
[Feature Request] Option to Categorize/Separate/Hide different types of messages (Private Messages, Group Chat, Bots, Channels)

### ISSUE THREAD

**Issue by DRSDavidSoft** [telegramdesktop/tdesktop#2511]
### Synopsis
Telegram can get crowded quickly over time. I feel a need to separate different message threads based on their type. This can be easily implanted on the client side.

There's no need to sync anything to the server. Since Telegram Desktop is just a "viewer" client, this should be available as an option.

### How to implant
The method is similar to most well-known file explorers.
Telegram should have an option to group, sort and display message threads by several factors:

- Thread contains *unread* messages
- *Date* of last message sent/received in the thread
- *Type* of thread, (private message, group chat, bots and channels)

The app should have the option to expand and collapse the groups and the option to filter and hide threads based on their attributes.

### Advantages of this option

- If we have missed an important message on Telegram, we can just group the messages and collapse all categories except the private message.
- If we are bored and want to see what's new in the Channels, we hide the other groups.
- If something is received but left unnoticed, sorting by "unread" puts them at the top of the list.
- etc.

Please implant this feature. This is something important, really useful, and doesn't need any kind of server APIs. It's purely client-based.

**Comment by stek29** [comment]
#1107.

**Comment by DRSDavidSoft** [comment]
So many duplicates to #1107, and yet no actual work done from the telegramdesktop team. Why?!
