### ISSUE TITLE
Setting @username error

### ISSUE THREAD

**Issue by loganbaby** [telegramdesktop/tdesktop#25118]
### Steps to reproduce

1. Signing in Telegram app (desktop / mobile)
2. Go Profile -> Settings -> Change profile -> Username

### Expected behaviour

I try to set any username from this list:
_@ mynameish
@ mynamei
@ mynameisp
@ mynamejk_

I will get any username from this list, or each different username by this logic.

### Actual behaviour

After trying to set username, we will see, that the given username is entered incorrectly. But I can use symbols a-z A-Z 0-9 _. So, it  is misbehavior of validation process from client-side. Actually, I guess that you should to make review in valid() method, after using regex_match here:

https://github.com/telegramdesktop/tdesktop/blob/9ef2f370ac19953d74760cd0ce1f17f2ec82d1d6/Telegram/SourceFiles/core/local_url_handlers.cpp#L328  

### Operating system

Arch linux, KDE Plasma 5.25.5

### Version of Telegram Desktop

4.1.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I've tried those usernames and I see in tdesktop log that the client does a request to the server and it returns USERNAME_INVALID error.
