### ISSUE TITLE
open/save window are not redirected when using DISPLAY variable on linux

### ISSUE THREAD

**Issue by Martin-Furter** [telegramdesktop/tdesktop#25117]
### Steps to reproduce

1. Start telegram desktop with the display redirected to another machine:

```DISPLAY=10.0.0.13:0.0 Telegram```

2. Choose a chat.
3. Press the paper-clip to upload a file.
4. Wait until the "Choose Files" window appears.

### Expected behaviour

All windows opened must appear on the display chosen using the DISPLAY variable.

### Actual behaviour

The "Choose Files" window appears on the default display and not on the one chosen with the DISPLAY variable.

### Operating system

Linux, Debian Sid

### Version of Telegram Desktop

4.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop calls your system service to show the dialogs, this is expected

**Comment by Martin-Furter** [comment]
No, it is not expected. I guess it forgets to forward the value of the DISPLAY variable.

**Comment by Martin-Furter** [comment]
Right now I tried the same with gimp and it works as expected. The windows for opening and saving files appear on the display the main window is also located. And there are many more applications that work correctly.

**Comment by ilya-fedin** [comment]
No, sorry, but it's expected. Those services are started on your session start and use $DISPLAY variable set in your session. Since those services use either gtk or qt, they can't switch to another value on the fly as those toolkits don't support that.

> And there are many more applications that work correctly.

Not all applications are using this service. This is the only way for tdesktop to display the dialog as it can't use system libraries.

**Comment by Martin-Furter** [comment]
OK. I started telegram under a different user account. It takes 3 minutes for a window to appear. But then the file dialogs appear on the right display. I wonder what it is doing in that case...
Btw. what's the name of that system service telegram uses?

**Comment by ilya-fedin** [comment]
> I wonder what it is doing in that case...

Most likely Qt fallbacks to the built-in gtk3 dialog implementation

> Btw. what's the name of that system service telegram uses?

xdg-desktop-portal
