### ISSUE TITLE
Regression: unwanted window decoration and wrong window size on Phosh

### ISSUE THREAD

**Issue by tendays** [telegramdesktop/tdesktop#25111]
I'm using Telegram Desktop on the Phosh window manager (which I use on a Librem5). Until version 4.1.1 included, enabling "Use native window decorations" would correctly let the window fill the entire screen and not show any window decoration. When opening the on-screen keyboard it would correctly reduce the window (allowing to see the input field at the bottom in conversation screens).

Since version 4.2, window decorations have appeared, and the window is slightly too wide and too tall. Most annoying is that I can't see what I'm typing when the on-screen keyboard is open, so I have to type blindly, then hide the keyboard to see if there's any typo.

I've seen some recent tickets about window manager hints, would that be related?

This shows version 4.1.1 (slightly masked for privacy), note lack of window decorations:

![telegram-41](https://user-images.githubusercontent.com/1023779/191685468-16bfd351-fe19-4a2d-b0a5-2ea026ff9acc.png)

This is the conversation window in version 4.1.1 with the keyboard open. Note that the input field is visible and there are no window decorations:

![telegram41-chat](https://user-images.githubusercontent.com/1023779/191685990-a08485d4-ad44-4144-8bd8-7a2707f18770.png)

Finally this is version 4.2. Note the window decoration on top, the fact that the input field is hidden and that the three-dot menu is too much on the right (because the window is too wide).

![telegram-42](https://user-images.githubusercontent.com/1023779/191686230-1fe6114c-5926-4125-bb8c-b7f03fd4f806.png)

I installed Telegram Desktop from Flathub. Flatpak gives the following information about the latest version (which triggers the issue):

```
        ID: org.telegram.desktop
       Ref: app/org.telegram.desktop/aarch64/stable
      Arch: aarch64
    Branch: aarch64
Collection: org.flathub.Stable
  Download: 57.2 MB
 Installed: 140.2 MB
   Runtime: org.freedesktop.Platform/aarch64/21.08
       Sdk: org.freedesktop.Sdk/aarch64/21.08

    Commit: 664ef4ed8dc4e8e757dd4f45c7d4fa91dbc4c4ab356078243749baebf8186c65
    Parent: 49457c38bd9fcb7f4748ffca85e7b2fce0359d0716311944a984c53c40e128c4
   Subject: Update glibmm-2.66.4.tar.xz to 2.66.5 (09036d75)
      Date: 2022-09-19 11:30:14 +0000
```

**Comment by ilya-fedin** [comment]
Sorry, but tdesktop is a desktop application, the fact you launched it on mobile doesn't mean mobile devices are supported. You're free to investigate the problem on your own though and PR a fix.
