### ISSUE TITLE
[CRASH] Spoiler reveal leads to crash in messages with images since Telegram v4.2.1

### ISSUE THREAD

**Issue by Mixaill** [telegramdesktop/tdesktop#25119]
@john-preston 

### Steps to reproduce

1. Post message with image + spoiler
![Screenshot_20220923_012823](https://user-images.githubusercontent.com/704382/191862403-3bd2cb13-b5b6-49d6-a9d6-17bff1c26a74.png)

2. Reveal spoiler

### Expected behaviour

1. Spoiler reveals

### Actual behaviour

1. Telegram crashes

### Operating system

Windows 11, OpenSuse Tumbleweed

### Version of Telegram Desktop

4.2.1

### Installation source

Static binary from official website

### Logs
crash report tags:  
   * 8f35bba1-73f0-40f3-9422-d5cc5ed63a2a (Windows 11)
   * b565e55b-1f88-4e2d-68033481-f2d6a9d6 (OpenSuse Tumbleweed)

**Comment by luccascomvoce** [comment]
This bug also affects me on Windows 10 21H2

**Comment by aditya-yadav-27** [comment]
Bug also effects endeaour os (Arch linux 5.19.9-arch1-1)

**Comment by Neurotoxin001** [comment]
Your Report Tag: 9b893afb-0b44-49b9-b827-f6d375505155
Your Report Tag: 5745d46c-60d3-48f4-b2d6-c79087a32751

Same Windows 10 21H2.

But only with enabled animations.

**Comment by POLIROID** [comment]
Your Report Tag: 11bd5f00-22bc-492b-88ab-709eb787882a

Same on Windows 11 22H2.

**Comment by Aokromes** [comment]
there is no need of post more and more report tags preston already knows the issue existance xd

**Comment by Neurotoxin001** [comment]
On videos I can't even reveal spoiler, but there is no crash with video.

Example:
https://t.me/moslentaru/15307

**Comment by john-preston** [comment]
Fixed in 4.2.2 beta.
