### ISSUE TITLE
Cannot interact with group video chat window

### ISSUE THREAD

**Issue by leonidgo** [telegramdesktop/tdesktop#25114]
### Steps to reproduce

Open any group with running video chat and click join or
Create a group, then start a video chat

### Expected behaviour

After connecting be able to mute and unmute yourself and use group video chat interface

### Actual behaviour

When trying to click on group chat window, it hides and mouse falls through it interacting with next window right under the one.
Even if all windows are minimized expect group chat, clicking on it makes actions on desktop.
As the result you hear other participants, but you can't unmute yourself to start communicating

### Operating system

Linux Mint 20.3 Cinnamon

### Version of Telegram Desktop

4.2

### Installation source

Snap

**Comment by ilya-fedin** [comment]
That sounds like a bug of your window manager, try to minimize and restore the window. If nothing helps, please report to cinnamon.
