### ISSUE TITLE
Notification sound ignores quiet hours in Windows 10

### ISSUE THREAD

**Issue by flippinger** [telegramdesktop/tdesktop#2512]
### Steps to reproduce
1. Enable "quiet hours" in the Action Center of Windows 10
2. Receive Message

### Expected behaviour
No notification toast and no sound should appear

### Actual behaviour
No notification toast, but sound still rings

### Configuration
**Operating system: Windows 10 Pro 1607**
**Version of Telegram Desktop: 0.10.11**

Telegram should use the system notification sound.

similar to #2011 for OSX

**Comment by john-preston** [comment]
@flippinger Is there API to query system silent hours maybe?

**Comment by flippinger** [comment]
@john-preston I don't think so, but using the Windows built-in toast sound would probably solve the problem, since Windows manages when to play the sound.

```XML
<toast [...]>
   <visual>[...]</visual>
  <actions>[...]</actions>
  <audio src="ms-winsoundevent:Notification.IM"/>
</toast>
```

[Adaptive and interactive toast notifications for Windows 10](https://blogs.msdn.microsoft.com/tiles_and_toasts/2015/07/02/adaptive-and-interactive-toast-notifications-for-windows-10/)
[audio - Windows app development](https://msdn.microsoft.com/en-us/library/windows/apps/br230842.aspx?f=255&MSPPError=-2147217396)

**Comment by nop144d** [comment]
@john-preston `QUERY_USER_NOTIFICATION_STATE` structure, which is already used in `psSkipDesktopNotify()` function for Windows has `QUNS_QUIET_TIME` field.

**Comment by john-preston** [comment]
@nop144d looks like it is something else. But there is a registry key reported here:

http://stackoverflow.com/questions/35600128/get-windows-quiet-hours-from-win32-or-c-sharp-api

together with this:

https://github.com/felixrieseberg/windows-quiet-hours/blob/master/lib/quiethours.cc

I guess it should work.

**Comment by flippinger** [comment]
Wouldn't it be way easier to use the built-in notification sound? Why don't you want to use it? It would provide some consistency across windows apps.

**Comment by john-preston** [comment]
@flippinger Because I can't use windows toast notifications by default (they freeze the app from time to time) + the behaviour should be consistent across native (built-in) and non-native (self-made) notifications.

**Comment by auchri** [comment]
Fixed by https://github.com/telegramdesktop/tdesktop/commit/0902741b856a89887db1a3d770826e3fc6871cba

**Comment by john-preston** [comment]
Starting from 0.10.14 alpha version the quite hours should be respected by both sounds and toasts.

**Comment by stek29** [comment]
Now #2011 please :)
