### ISSUE TITLE
telegram crashes on folder create

### ISSUE THREAD

**Issue by alex-kurochkin** [telegramdesktop/tdesktop#25120]
### Steps to reproduce

Open telegram
Click Edit on folders panel (left side)
Click "Create new folder"
Enter new folder name and click "Add chats"
Select anyone chat and click "Save"
Click "Create" - new folder created
Close folders list.

### Expected behaviour

Folder created with selected chat.
Telegram app stay work on.

### Actual behaviour

Telegram crashed.
On restart app no new folders added.

### Operating system

Linux / Kubuntu

### Version of Telegram Desktop

v4.2 17.09.22

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
already fixed

**Comment by suwermave** [comment]
no it's not?

**Comment by ilya-fedin** [comment]
it is

**Comment by it-kurochkin-a** [comment]
But Telegram still crash on it.

**Comment by Aokromes** [comment]
update to 4.2.2

**Comment by ilya-fedin** [comment]
> But Telegram still crash on it.

in version 4.2.2?

**Comment by it-kurochkin-a** [comment]
From Settings - Advanced:
Version 4.2
Check for updates - Latest version is installed.
Update automatically is On.

Installed as v4.2 17.09.22. downloaded from official website (static binary).

Для вашего спокойствия могу попробовать скачать и установить снова, если на сайте уже есть версия 4.2.2.
Should I try it?

**Comment by ilya-fedin** [comment]
you can just enable "Install beta versions"

**Comment by it-kurochkin-a** [comment]
Ok. Checked.
Yes, this point works correctly in beta 4.2.2

But I'm not tg developer / QA to use betas.

Anyway thanx. )
