### ISSUE TITLE
Synchronization issues

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25128]
### Steps to reproduce

1. Open Telegram Desktop and https://web.telegram.org/z/
2. Wait until new posts in channels that you subscribed (I subscribed to ~70 channels)
3. On web version new post is showing, on tdesktop - no
4. Tdesktop shows new posts only after I open a channel with new post

For example here is channel on web:
![image](https://user-images.githubusercontent.com/39812401/192133490-bc84a3bf-d655-4cd9-b602-8899e1ab2e49.png)

And on tdesktop:
![image](https://user-images.githubusercontent.com/39812401/192133497-c8b89f6a-a6e9-4f77-a256-a77f94f6fb10.png)

It's started today and only tdesktop affected. Now it's unusable.
Maybe it's because I have added 3 accounts and I switch between them.

### Expected behaviour

-

### Actual behaviour

-

### Operating system

Windows 10

### Version of Telegram Desktop

4.2.2 beta

### Installation source

Static binary from official website

**Comment by valorex28** [comment]
I have the same thing since yesterday, some channels are not synchronized in Telegram Desktop

**Comment by Neurotoxin001** [comment]
@john-preston any news? My friends have this issue too, but they don't have github account...

**Comment by john-preston** [comment]
@Neurotoxin001 I could reproduce, it looks like a server side issue. I don't see the updates about new messages in log. I've asked the server side developers about this.

**Comment by Aokromes** [comment]
yeah i confirm this issue, 1st it was less noticeable but now yes.

**Comment by Neurotoxin001** [comment]
Will test it

**Comment by Neurotoxin001** [comment]
Seems like fixed
