### ISSUE TITLE
Telegram Mobile (Android) Font Size Reset

### ISSUE THREAD

**Issue by ArkTuberGL** [telegramdesktop/tdesktop#25122]
Since the last update, the font size is reset to standard again and again at irregular intervals. I have not been able to determine an exact sequence that triggers this event. If you close the app completely and open it again, the font size is correct again. Or you go into the settings and change it again. But both are very annoying...

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
