### ISSUE TITLE
Launching Telegram with the system does not spawn a tray icon

### ISSUE THREAD

**Issue by FridgeRacer** [telegramdesktop/tdesktop#25124]
### Steps to reproduce

1. Enable "Launch Telegram when system starts"
2. Restart the computer
3. Log in and check the system tray

### Expected behaviour

When logged in to the desktop environment, the tray icon should spawn alongside all the other icons.

### Actual behaviour

The Telegram tray icon doesn't spawn, however the application is still running in the background. Opening Telegram via a .desktop file will create a window using the running process, but closing it doesn't spawn a tray icon or exit the application.

Terminating the auto-started Telegram process and launching it again via the .desktop file will successfully spawn a tray icon.

### Operating system

Arch Linux, KDE Plasma 5.25.5

### Version of Telegram Desktop

4.2.1 Beta

### Installation source

Static binary from official website

### Logs

Note: This log is from a machine running KDE Plasma 5.26 beta (5.25.90), but the behaviour remains the same.
[log.txt](https://github.com/telegramdesktop/tdesktop/files/9637711/log.txt)

**Comment by ilya-fedin** [comment]
It's https://bugreports.qt.io/browse/QTBUG-94871 / https://bugs.kde.org/show_bug.cgi?id=425315

**Comment by FridgeRacer** [comment]
> It's https://bugreports.qt.io/browse/QTBUG-94871 / https://bugs.kde.org/show_bug.cgi?id=425315

Oops, sorry, and thanks for clearing that up for me!
