### ISSUE TITLE
[Feature Request] Report about spam-reactions

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25123]
### Is your feature request related to a problem?

iOS Telegram have report button when you go to user profile from reactions, tdesktop don't have it.

![image](https://user-images.githubusercontent.com/39812401/192063160-1e528f04-cae1-4826-8d9d-f9d5d9a48143.png)
![image](https://user-images.githubusercontent.com/39812401/192063175-ba23607c-47f0-439d-8544-5ec85f84844c.png)

### Describe the solution you'd like

Make report button for reactions-spammers

### Describe alternatives you've considered

No

**Comment by Aokromes** [comment]
and this is why we need slate bot lol
