### ISSUE TITLE
[Question] why don't you update app in Microsoft Store?

### ISSUE THREAD

**Issue by Sarisan** [telegramdesktop/tdesktop#25125]
![image](https://user-images.githubusercontent.com/63128024/192084036-4099850b-f790-48a2-ba10-598e9a0bf00e.png)
![image](https://user-images.githubusercontent.com/63128024/192084074-ec138044-2320-4d87-9b28-6453257a36b3.png)
![image](https://user-images.githubusercontent.com/63128024/192084096-1e269467-47d6-4c5f-9dc0-b953835a727d.png)

**Comment by john-preston** [comment]
@Sarisan Soon. I hope Monday.

**Comment by vonDubenshire** [comment]
Why use it there

**Comment by ShervanN** [comment]
@john-preston John Preston 
When the new version of Telegram Desktop will release in Microsoft Store?

**Comment by Dark345** [comment]
well, time to push this update 🤦‍♂️

**Comment by yunfandev** [comment]
@john-preston When the new version of Telegram Desktop will release in Microsoft Store?

**Comment by onurbbr** [comment]
@yunfandev @ShervanN @Sarisan Telegram Desktop update is released on Microsoft Store. You can update it.
