### ISSUE TITLE
svg is not included into the dafault filter when setting group avatar

### ISSUE THREAD

**Issue by mikhailnov** [telegramdesktop/tdesktop#25137]
### Steps to reproduce

1. Create a new group
2. Click choosing image (its avatar)

### Expected behaviour

svg (MIME image/svg+xml) are included into the default filter of files

### Actual behaviour

svg are not included. I had to set showing all files to choose the svg. It was chosen and set as an avatar successfully. GTK+3 file dialog was used/

### Operating system

Linux

### Version of Telegram Desktop

4.2.2

### Installation source

Other (unofficial) source

**Comment by mikhailnov** [comment]
this svg was used: https://new-api.pik-software.ru/media/36_yJjgkWn.svg

**Comment by ilya-fedin** [comment]
I believe this is not a bug, svg is not a popular format and is won't ever be recognized as an image in official builds.

**Comment by mikhailnov** [comment]
Do you mean that official builds cannot set svg on avatar, while unofficial ones can?

**Comment by ilya-fedin** [comment]
Official ones can't. Unofficial ones' image support is undefined as it depends on Qt plugins set.

**Comment by mikhailnov** [comment]
I can attach an svg file, telegram asks whether to compress it (send as an image) or not (send as file). Is this not available in official builds?!

**Comment by ilya-fedin** [comment]
No, it's not
