### ISSUE TITLE
[Feature Request] Don't apply Mono format to line breaks when it is a single line

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#25130]
### Is your feature request related to a problem?

The text is not clickable when it is applied.

### Describe the solution you'd like

Don't apply. 

(Why is this mandatory? as the answer is repeated from the title)

### Describe alternatives you've considered

-
(Again why is this mandatory?)

### Additional context

version 1.0.47 beta x64 | v4.2.0

**Comment by ilya-fedin** [comment]
#24985
