### ISSUE TITLE
The app still consumes an unexpectedly large amount of RAM

### ISSUE THREAD

**Issue by pboettcher** [telegramdesktop/tdesktop#25135]
### Steps to reproduce

Run Telegram 4.2 x64 for Windows.
Do something.
Look at the RAM usage. It is around 270 MB for a messenger that is no more complex than the comparable ones.

### Expected behaviour

RAM consumption should be around 10-20-30 MB when idle.

### Actual behaviour

RAM consumption is around 270 MB

### Operating system

Windows 7 64x

### Version of Telegram Desktop

4.2 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> than the comparable ones

What do you compare tdesktop with? I believe most moden messengers (e.g. Discord) consume a comparable amount of RAM or even more.

**Comment by ilya-fedin** [comment]
> RAM consumption should be around 10-20-30 MB when idle.

I don't think this is achievable given that how much pictures, videos and animations tdesktop presents on the screen. That's all should be stored in the RAM, in RAW uncompressed format.

**Comment by pboettcher** [comment]
I am comparing with Skype (currently 50MB) and custom Jabber-based messenger (15 MB). Probably it is better just to uninstall Telegram.

**Comment by ilya-fedin** [comment]
> I am comparing with Skype

The latest one? I believe it is using Electron, so it should have multiple processes, so you should find all its processes and sum their consumption.

> custom Jabber-based messenger (15 MB).

I don't believe it's even near comparable to tdesktop, jabber is pretty much outdated and usually supports only text-based messaging.

**Comment by Aokromes** [comment]
https://i.imgur.com/EKE4U71.png
