### ISSUE TITLE
Telegram fails to start: 'undefined symbol: hb_buffer_set_cluster_level'

### ISSUE THREAD

**Issue by jokuNimi** [telegramdesktop/tdesktop#2514]
### Steps to reproduce
1. Download Telegram from [desktop.telegram.org](desktop.telegram.org) or install through [aur](https://aur.archlinux.org/packages/telegram-desktop-bin/) (Arch User Repository).
2. Attempt to start telegram (from desktop environment, running `telegram-desktop`, or running `./Telegram` in the unzipped directory).
### Expected behaviour

Telegram should start up.
### Actual behaviour

Telegram flashes on the screen for about 1 ms and then closes.
### Configuration

**Operating system:**
Linux (Arch Linux, kernel version 4.7.6-1, running under gnome 3.20.2)

**Version of Telegram Desktop:**
Latest as of today, but am not sure of the exact version. The name of the downloaded file is `tsetup.0.10.11`. `telegram-desktop -v` doesn't print a version.
### Logs

I don't know how to type `debugmode` into settings when I can't get Telegram to start at all. Here is what is printed into a terminal when I attempt to open Telegram:

```
% telegram-desktop
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
telegram-desktop: symbol lookup error: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: hb_buffer_set_cluster_level
```

There is some more information that may be of interest at an [arch linux forum thread](https://bbs.archlinux.org/viewtopic.php?pid=1656454#p1656454) I posted about this issue. I didn't have time to compile Telegram from source as I said I would do on the forum.

**Comment by stek29** [comment]
Is `harfbuzz` installed?

**Comment by jokuNimi** [comment]
Harfbuzz is installed. Trying to install it prints `warning: harfbuzz-1.3.1-1 is up to date -- reinstalling` and `pacman -Qi harfbuzz` exits with 1 [(exact output)](https://gist.github.com/jokuNimi/54e02bacc3c1182632b6deeed96f965b).

I forgot to mention that Telegram worked before; this problem only showed up a couple of weeks ago, without me doing any drastic changes to the system (other than a standard  update).

**Comment by Zenexer** [comment]
What's the contents of `/etc/fonts/conf.d/10-scale-bitmap-fonts.conf`?  Can you put it in a [gist](https://gist.github.com/)?

**Comment by jokuNimi** [comment]
The contents are [here](https://gist.github.com/jokuNimi/6e8ccbda24bf6362c0ca3e479dfe4e42).

**Comment by stek29** [comment]
@jokuNimi what if you downgrade the harfbuzz?

**Comment by Zenexer** [comment]
Looks like a bad merge.  Delete line 71.

**Comment by Zenexer** [comment]
Sorry, made a suggestion previously, but it was based on an older version of fontconfig.  I've deleted that comment.

According to [this issue](https://bugs.freedesktop.org/show_bug.cgi?id=70258), it does appear to be on Telegram Desktop to fix this, unless you're able to safely downgrade a few packages.  I wouldn't recommend doing that on Arch, though.

**Comment by john-preston** [comment]
@Zenexer Any clues how this could be fixed?

**Comment by Zenexer** [comment]
@john-preston It's being compiled against an outdated version of fontconfig that doesn't support referencing font properties in `<matrix>`.  The latest version does something similar to [this](http://marc.info/?l=freedesktop-fontconfig&m=135613953230670&w=2), but it looks like that trick didn't work in 2012, so it must be new.  However, I'm not sure you can compile it for the latest version without breaking compatibility with other distros.

**Comment by Zenexer** [comment]
@stek29, are you installing telegram-desktop-bin from AUR?  If so, can you try telegram-desktop-git?

**Comment by Zenexer** [comment]
@jokuNimi, which package are you installing from AUR?  Can you try each of these and let me know which ones work and which don't?

* telegram-desktop-bin: Shouldn't work
* telegram-desktop: Unknown; key to determining solution
* telegram-desktop-git: Should work

**Comment by jokuNimi** [comment]
Originally I installed it from `telegram-desktop-bin`, and that didn't work. The same happened for the version downloaded from the telegram page. I can't get telegram to build from either of the others (using `aura`).

- For `telegram-desktop` the main problem seems to be
  ```
   HarfBuzz system library support cannot be enabled due to functionality tests!
   Turn on verbose messaging (-v) to ./configure to see the final report.
   If you believe this message is in error you may use the continue
   switch (-continue) to ./configure to continue.
  ````
  The whole output is given [here](https://gist.github.com/jokuNimi/6eb611e09ca0f8f8e3184e69d6817019).

- For `telegram-desktop-git` the culprit seems to be
  ```
  ==> Starting prepare()...
  cp: cannot stat 'tdesktop/Telegram/_qt_5_5_0_patch.diff': No such file or directory
  ==> ERROR: A failure occurred in prepare().
  ```
  The whole output is given [here](https://gist.github.com/jokuNimi/5535c6ae31999e6e8b1d0917bc4656f7).

Maybe I should be opening up issues about both of these? Would that be helpful? I could also try a `harfbuzz` downgrade, though I've understood that that may be dangerous.

**Comment by stek29** [comment]
@jokuNimi I took my words back, better wait for fix.

**Comment by jokuNimi** [comment]
@stek29 I ended up trying anyway. Simply downgrading `harfbuzz` to version 1.2.7-1 and then `fontconfig` to version 2.12.0-1 (versions from a time when telegram worked for me) didn't help.

**Comment by jokuNimi** [comment]
Disabling 10-scale-bitmap-fonts.conf (as per the [fontconfig issue](https://bugs.freedesktop.org/show_bug.cgi?id=70258) mentioned earlier) gets rid of the fontconfig errors, but
```
telegram-desktop: symbol lookup error: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: hb_buffer_set_cluster_level
```
remains and Telegram still crashes. That seems to suggest that fontconfig isn't the main issue here?

**Comment by jokuNimi** [comment]
This issue no longer affects me. I just noticed today that telegram works, with no error messages shown in the terminal. I am not sure what changed since I haven't been checking if telegram works after each update.
