### ISSUE TITLE
Telegram messages are auto-read with no notification 

### ISSUE THREAD

**Issue by azumirukat** [telegramdesktop/tdesktop#25147]
### Steps to reproduce

1. Receive message 

### Expected behaviour

A notification should pop-up and message is not labeled as read

### Actual behaviour

No notification pops up and message is labelled as read

### Operating system

iOS 16

### Version of Telegram Desktop

4.2.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> iOS 16

How do you use tdesktop on iOS?

**Comment by azumirukat** [comment]
It happens on both telegram desktop and iOS regardless of which is signed in

**Comment by ilya-fedin** [comment]
You need to specify the operating system you use tdesktop on, not iOS

**Comment by azumirukat** [comment]
Sorry, the macOS version is Catalina 10.15.7

**Comment by ilya-fedin** [comment]
If you're sure you have no Telegram client you with this conversation open, this may mean someone else uses your account. I'd suggest to terminate all the sessions via Privacy&Security settings and set two-factor password.

**Comment by azumirukat** [comment]
I've checked the linked devices and only these 2 devices are active

**Comment by easyproger** [comment]
Bump, also have this bug - Mac OS 12.6 telegram 9.0.1.237033 AppStore

**Comment by RememberTheAir** [comment]
Make sure you're using tdesktop and not the native MacOS app. @easyproger `9.0.1.237033` is not a valid tdesktop version number so I guess you're using the other app

**Comment by xnextx** [comment]
Bump, also have this bug - MacOS 12.4 telegram 9.0.1.237033 AppStore.
I have only 2 sessions (ios and macbook). I reinstalled telegram (previously I used the version downloaded from the website and the problem was the same). The problem appeared recently.

**Comment by ilya-fedin** [comment]
Folks, the latest release of Telegram Desktop is 4.2.4: https://github.com/telegramdesktop/tdesktop/releases/tag/v4.2.4
If you see 9.x.x, you're not using tdesktop. You can install it using the link above.

**Comment by MazzMat** [comment]
Version 9.x is Telegram client Macos native made in Swift
https://github.com/overtake/TelegramSwift
https://macos.telegram.org/

Anyway I have this bug too but I think it's better to fill a new issue here
https://github.com/overtake/TelegramSwift/issues
