### ISSUE TITLE
RPC Error in getDifference: 406 AUTH_KEY_DUPLICATED:

### ISSUE THREAD

**Issue by rocheldebbrarmke** [telegramdesktop/tdesktop#25144]
windows10/telegram4.2.3
--------------
I copy my tdata folder into another pc , but i got "Logout" error,
---
RPC Error: request 79 got fail with code 406, error AUTH_KEY_DUPLICATED
RPC Error in getDifference: 406 AUTH_KEY_DUPLICATED:

----

how opening multiple instances ?

**Comment by RememberTheAir** [comment]
You can't use the same session files simultaneously on different machines. This is a security measure and btw it's not related to tdesktop
