### ISSUE TITLE
The copy-pasted image from telegram is broken

### ISSUE THREAD

**Issue by zsdedan** [telegramdesktop/tdesktop#25140]
### Steps to reproduce

1. Copy any image from telegram message
2. Paste image in any program which can read images from clipboard (ex. gimp)

### Expected behaviour

Full image is pasted.

### Actual behaviour

Broken (not full) image is pasted.

Copied image
![image](https://user-images.githubusercontent.com/3087460/193102491-7fcd3fb9-725a-46e6-aa8c-8a9b897dacb6.png)
Pasted image (in gimp)
![image](https://user-images.githubusercontent.com/3087460/193102655-551fe4dc-1a0b-4101-a4e4-6e78c7630258.png)

### Operating system

Ubuntu 22.04.01

### Version of Telegram Desktop

4.2

### Installation source

Flatpak

**Comment by Aokromes** [comment]
works for me on 4.2.2 on windows with paint. try enabling beta.

**Comment by ilya-fedin** [comment]
Are you sure this is not XWayland bug? Have you tried pasting to native Wayland applications?

**Comment by zsdedan** [comment]
Is Evolution native wayland app? Or what app should I use to check this bug?

**Comment by ilya-fedin** [comment]
I reported this as https://bugreports.qt.io/browse/QTBUG-107076 and added to #25126

**Comment by ilya-fedin** [comment]
@zsdedan Qt 6.4.1 claims to have a fix for this issue, can you check whether this is still valid?

**Comment by zsdedan** [comment]
Hi! Issue solved! Thanx!
