### ISSUE TITLE
Image preview too small

### ISSUE THREAD

**Issue by jw-dbc** [telegramdesktop/tdesktop#25156]
### Is your feature request related to a problem?

When a graphics image is posted via Telegram Desktop, the resulting onscreen display size is too small, forcing use of the Telegram app if you want a decent display size. 

### Describe the solution you'd like

Adjust the code so images posted using Telegram Desktop appear larger, same as per the Telegram apps.

### Describe alternatives you've considered

N/A

**Comment by Aokromes** [comment]
you know you can click image to see larger size and control + / control - keys to enlarge / reduce it?

**Comment by jw-dbc** [comment]
Yes, but I'm wanting it to display larger inline versus itty-bitty, like if you post the same image using the phone app.

My desktop machine has 1440px width. I just posted an image using the Telegram phone app. It displays on my desktop at 400px width. However, the same image posted using the Telegram desktop client displays as a 75px wide thumbnail with a hyperlink. Definitely doesn't look good. I don't want people to have to click the graphic to see it, so have to fire up my phone to post images so they look decent. 

Telegram export code uses inline CSS to give all IMG tags hard-coded WIDTH and HEIGHT values. Not good. Much better to have a single IMG tag CSS declaration setting MAX-WIDTH to the desired value using the % then set HEIGHT to AUTO, which makes all the images "responsive" at the preferred viewport width.

This said, Telegram Desktop displaying itty-bitty images must involve using an overly small thumbnail along with A tags to hyperlink to the larger image. Hyperlinking to a larger image is okay but the image placed on the channel needs to be bigger to be legible and match what the phone app does.

![telegram-desktop](https://user-images.githubusercontent.com/114873366/193479774-3b8657f9-d34b-402d-ae7a-865eeffa5555.jpg)

**Comment by jw-dbc** [comment]
Screenshot above shows a small image posted using Telegram desktop. The wider image above it is the width it displays at if  instead posted from the phone app.

**Comment by Aokromes** [comment]
enable send compresed image.

**Comment by john-preston** [comment]
@jw-dbc When you paste the image you can choose to send an uncompressed file (the second one, "agenda2030.jpg", is an uncompressed file) or a compressed image (photo, the first one).
