### ISSUE TITLE
the sound of the video often disappears after the first seconds of playback

### ISSUE THREAD

**Issue by ac3p** [telegramdesktop/tdesktop#25151]
### Steps to reproduce

play video

### Expected behaviour

video playback with sound

### Actual behaviour

the sound of the video often disappears after the first seconds of playback

### Operating system

windows 7, windows 10

### Version of Telegram Desktop

4.2.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#7063?

**Comment by ac3p** [comment]
> #7063?

yes, looks like it
