### ISSUE TITLE
[Question] Telegram not responding to any type of support requests 

### ISSUE THREAD

**Issue by mert1256** [telegramdesktop/tdesktop#25158]
Telegram not responding to any type of support requests

My channel, which could not find any copyrighted content, was given a copyright penalty.I have 7 channels with 1 million members. but there is no copyrighted content on my channels..  I wrote many times but no answer. The appointing company admitted that it did not look at the content and only increased the copyright upon the complaint.

And I am threatened every day. They say if you don't do what we say, we will report other channels and close them. My channel with 1 million members, my 4-year-old channel was closed in vain. and i can't do anything

This is a bug. Anyone can close the channels.

I wrote with this e mail. Please response me;  
mertborta@gmail.com

**Comment by mert1256** [comment]
Don't close this subject please.

**Comment by mert1256** [comment]
This week, 1000 channels were closed in Turkey for no reason.  we tire of making our voices heard.

**Comment by Aokromes** [comment]
complaining here won't fix your issue at all, this is a BUG tracker of TELEGRAM DESKTOP, your problem aint a bug or problem with TELEGRAM DESKTOP.

**Comment by mert1256** [comment]
What can we do?  1000 groups and channels were unfairly closed in Turkey this week.  Who can take care of it?

**Comment by mert1256** [comment]
Telegram employees read this place please doesn't close

**Comment by mert1256** [comment]
> İZLEYİCİDİR
What can we do? 1000 groups and channels were unfairly closed in Turkey this week. Who can take care of it?

Telegram employees read this place please doesn't close

**Comment by mert1256** [comment]
> burada şikayet etmek sorununuzu hiç çözmez, bu TELEGRAM MASAÜSTÜ HATA İZLEYİCİDİR, sorununuz TELEGRAM MASAÜSTÜ ile ilgili bir hata veya sorun değildir.

What can we do? 1000 groups and channels were unfairly closed in Turkey this week. Who can take care of it?

Telegram employees read this place please doesn't close

**Comment by mert1256** [comment]
> complaining here won't fix your issue at all, this is a BUG TRACKER of TELEGRAM DESKTOP, your problem aint a bug or problem with TELEGRAM DESKTOP.

What can we do? 1000 groups and channels were unfairly closed in Turkey this week. Who can take care of it?

Telegram employees read this place please doesn't close
