### ISSUE TITLE
[Question] Telegram not responding to any type of support requests 

### ISSUE THREAD

**Issue by mert1256** [telegramdesktop/tdesktop#25157]
So, I have been trying to reach out telegram support through different modes, I have tried mailing 1000 times, tried volunteer support within the app, tried to reach out via Twitter but never received a single response from Telegram.

The issue is that; 
My channel, which could not find any copyrighted content, was given a copyright penalty.I have 7 channels with 1 million members. but there is no copyrighted content on my channels..  I wrote many times but no answer. The appointing company admitted that it did not look at the content and only increased the copyright upon the complaint.

And I am threatened every day. They say if you don't do what we say, we will report other channels and close them. My channel with 1 million members, my 4-year-old channel was closed in vain. and i can't do anything

**Comment by Aokromes** [comment]
sorry, but this is a bug tracker for telegram desktop, not a place to complain about the network support.
