### ISSUE TITLE
Telegram Desktop uses 14+ GB RAM.

### ISSUE THREAD

**Issue by its-monotype** [telegramdesktop/tdesktop#25162]
### Steps to reproduce

1. OS: Windows 11 22H2 (Build 22621.608)
2. Telegram Desktop 4.2.4 x64
3. That never happened to me before.

### Expected behaviour

RAM usage should be normal

### Actual behaviour

Telegram Desktop uses 14+ GB RAM.

### Operating system

Windows 11 22H2 (Build 22621.608)

### Version of Telegram Desktop

4.2.4 x64

### Installation source

Static binary from official website

**Comment by its-monotype** [comment]
![Screenshot 2022-10-03 182248](https://user-images.githubusercontent.com/79363260/193631150-3517ee15-1150-4e89-b281-85c905012e16.png)

**Comment by idonotknowwhoiam** [comment]
same for me, usage of ram isn't normal
arch, version is 4.2.4-1

**Comment by vonDubenshire** [comment]
No issue here I'm using 300mb at first open

**Comment by its-monotype** [comment]
@vonDubenshire This does not happen all the time, but sometimes, it also happens to me that everything is fine, but sometimes like this

**Comment by Igor2399** [comment]
16GB ram usage on windows when wathing screen shared

**Comment by john-preston** [comment]
Does it happen for anyone not after using video chats / calls?

**Comment by Seenshadow** [comment]
> Does it happen for anyone not after using video chats / calls?

For me it happened now during a videocall. Bought this laptop with 16 gb of ram yesterday and installed telegram right from the start. Today it tells me during a call that most of my ram is used up even when i barely had anything running. 7gb of ram usage just by Telegram after it only ran for 15 min...

**Comment by realestninja** [comment]
Version 4.5.3 and it is using 1.4 GB of RAM. Way too much.

**Comment by samchor** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/126976313/bafdb534-da59-4a78-b6ce-91a539b01a5e)


same here

**Comment by john-preston** [comment]
@its-monotype @idonotknowwhoiam @Igor2399 @Seenshadow @samchor I've deployed a new 4.8.11 beta version:

https://github.com/telegramdesktop/tdesktop/releases/tag/v4.8.11

it has updated ANGLE and a workaround for a possibly huge memory allocations. Can you please try it and see if the memory usage goes up like that as well or is it relatively low? I mean, it shouldn't go to several GB no matter how you use it.
