### ISSUE TITLE
telegram desktop app not sending verification code.

### ISSUE THREAD

**Issue by bajechele** [telegramdesktop/tdesktop#25167]
### Steps to reproduce

open desktop portable version exe
run the exe
give the mobile number and wait for god knows how long for the code

### Expected behaviour

should get the code within in a minute

### Actual behaviour

sms with code not received

### Operating system

windows 10

### Version of Telegram Desktop

4.2.4

### Installation source

Static binary from official website

**Comment by bajechele** [comment]
i used to have an account long ago but it got deleted i guess coz of inactivity....but now i want to get back to it and this verification code sms just not showing up.....sign up with email and password would be way better option at this point...

**Comment by ilya-fedin** [comment]
Only mobile apps are permitted to send SMS. For other types of clients, you have to have an already active session.

**Comment by bajechele** [comment]
tried with mobile app also downloaded from play store same problem didn't received any verification code ..
