### ISSUE TITLE
[Feature Request] Emoji panel - show ONLY after click

### ISSUE THREAD

**Issue by LexaGV** [telegramdesktop/tdesktop#25161]
### Is your feature request related to a problem?

When I type message, I move away mouse pointer, but once it crosses "smile icon", huge panel of idiotic faces popup on my screen!   It annoys me and I want this panel to popup ONLY after I specially click on the smile icon.

### Describe the solution you'd like

Just checkbox in settings [x] Popup emoji after click

### Describe alternatives you've considered

No alternatives, popup can be managed only if developer implement this feature.

**Comment by Aokromes** [comment]
enable experimental settings to allow you to enable that setting.

**Comment by LexaGV** [comment]
@Aokromes : thank you, it works!! Surprised it's "experimental". I would say "experiment is successful" - you can make this setting generally available. :)
