### ISSUE TITLE
[Urgent] Telegram not responding to any type of support requests

### ISSUE THREAD

**Issue by mert1256** [telegramdesktop/tdesktop#25160]
Telegram not responding to any type of support requests

My channel, which could not find any copyrighted content, was given a copyright penalty.I have 7 channels with 1 million members. but there is no copyrighted content on my channels.. I wrote many times but no answer. The appointing company admitted that it did not look at the content and only increased the copyright upon the complaint.

And I am threatened every day. They say if you don't do what we say, we will report other channels and close them. My channel with 1 million members, my 4-year-old channel was closed in vain. and i can't do anything

This is a bug. Anyone can close the channels.

I wrote with this e mail. Please response me;
[mertborta@gmail.com](mailto:mertborta@gmail.com)

**Comment by john-preston** [comment]
Please stop creating new issues or I'll be forced to block you in this repository.

This place doesn't relate to Telegram Support in any way, nothing can be done about support requests here.

This repository is ONLY about client-side issues in Telegram Desktop application.

**Comment by mert1256** [comment]
@john-preston .
Bro I read a subject 3 years ago. And telegram response from here. My issue is not personel. About 5 million people

**Comment by john-preston** [comment]
@mert1256 Bro even if the issue is about 5 billion people this is not the right place to report it. I suggest you report it to Mozilla Firefox project, IDK. Or to Adobe Acrobat issues. Anywhere other than here.

**Comment by mert1256** [comment]
> @john-preston I have 5 million follower. My 4 years of labor was garbage.

5 million people don't matter to telegram?  I can't reach.  You are a telegram developer.  You have friends from telegram team.  you can reach them.  @akrepkral my telegram account.  it really drives away telegram content creators.

**Comment by mert1256** [comment]
@john-preston 5 million people don't matter to telegram? I can't reach. You are a telegram developer. You have friends from telegram team. you can reach them. @akrepkral is my telegram account. it really drives away telegram content creators.
