### ISSUE TITLE
"System Windows Decorations" not available on Gnome 43

### ISSUE THREAD

**Issue by xisberto** [telegramdesktop/tdesktop#25171]
### Steps to reproduce

On Gnome 43, Telegram uses foreign window titles. On the Settings, Advanced, System integration there's no option to use the system windows decorations, as seen below:

![image](https://user-images.githubusercontent.com/1914956/194301282-5df3f55e-b479-4c33-abbf-6c30e335d2a7.png)

### Expected behaviour

Option should be present.

### Actual behaviour

Option not visible.

### Operating system

Gnome 43 on Arch Linux

### Version of Telegram Desktop

Version 4.2.4

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
GNOME Wayland doesn't provide system decorations, there's nothing we can do about that
https://gitlab.gnome.org/GNOME/mutter/-/issues/217

**Comment by Aokromes** [comment]
imho that thing must be show on gnome and disabled, with tooltip with that explication since every few days a new ticket because this "issue" is post.

**Comment by ilya-fedin** [comment]
Well, it becomes rare and rare, maybe this will become a well-known thing once

**Comment by xisberto** [comment]
Well, this is unfortunate, and I believe @Aokromes is correct. The user should be informed of this.
