### ISSUE TITLE
#urgent whoever write too fast to this group, their accounts are  deleted

### ISSUE THREAD

**Issue by adalacee** [telegramdesktop/tdesktop#25175]
l have  a group with 60000 members. İf the New accounts write fastly , their accounts are deleted. You will say that they shouldn't write so fastly , but almost 600 New account join the group daily .100-200 account are deleted among them. 
Can you fix this

The group link: t.me/muhabbet_sohbet_arkadasli

**Comment by Aokromes** [comment]
not telegram desktop bug.
also if accounts are deleted maybe they where reported because spam.

**Comment by mert1256** [comment]
@Aokromes We tried it.  Anyone who writes to the group with a new account is deleted without exception.  It has nothing to do with spam.
