### ISSUE TITLE
[Question] High RAM usage on send photos (>150)

### ISSUE THREAD

**Issue by Erapchu** [telegramdesktop/tdesktop#25179]
![image](https://user-images.githubusercontent.com/37536541/194713512-7ea0b1c8-4147-4e4e-9646-99dcf10f5924.png)

Is it OK when I tried to send ~500 photos this greatly affects RAM consumption and disk usage ~1500 Mb per second on read in two minutes, while full size of photos is ~1,5 Gb.

**Comment by ilya-fedin** [comment]
tdesktop needs to decode and place to RAM them all in order to  present them to you

**Comment by ilya-fedin** [comment]
RAW (decoded) image size is way large than what you see on HDD (as well as with video, audio and any other compressed content)

**Comment by Erapchu** [comment]
Thank you
Doesn't it support any virtualization to not show them all here? I just want to send them all. Do I need to select and send them in a batch? 100 pieces each

**Comment by ilya-fedin** [comment]
> Doesn't it support any virtualization to not show them all here?

I don't quite understand what do you mean by virtualization

> I just want to send them all. Do I need to select and send them in a batch? 100 pieces each

Yeah, looks like that
