### ISSUE TITLE
Telegram desktop scroll not working with Logitech MX Vertical under Ubuntu

### ISSUE THREAD

**Issue by ibmua** [telegramdesktop/tdesktop#25170]
### Steps to reproduce

1. Use Ubuntu 22.04
2. Open current Telegram Desktop version (4.2.4)
3. Use Logitech MX Vertical mouse
4. Witness that scrolling is ignored. Works with other mice, but not this one. No such problems in any other apps I encountered.

### Expected behaviour

Scrolling

### Actual behaviour

Not scrolling

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.2.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#25126
