### ISSUE TITLE
"qt.svg: Error while inflating gzip file: SVG format check failed" 

### ISSUE THREAD

**Issue by Cbhihe** [telegramdesktop/tdesktop#25173]
This error is spamming my Linux' boot log (as acessed by `journalctl -b`.
It looks similar to  **Error while inflating gzip file: SVG #17034**, but I could not find a resolution path based on # 17034.
I went looking for the _telegram.svg_ file in _/usr/share/icons/hicolor/..._ subtree, and here is what I found:

```
> sudo find /usr/share/icons/hicolor/ -iname "telegram*"
/usr/share/icons/hicolor/512x512/apps/telegram.png
/usr/share/icons/hicolor/32x32/apps/telegram.png
/usr/share/icons/hicolor/256x256/apps/telegram.png
/usr/share/icons/hicolor/128x128/apps/telegram.png
/usr/share/icons/hicolor/48x48/apps/telegram.png
/usr/share/icons/hicolor/16x16/apps/telegram.png
/usr/share/icons/hicolor/64x64/apps/telegram.png

```
There is no svg file in _/usr/share/icons/hicolor/scalable/apps/_. Is it just a matter of me creating an SVF Telegram icon and dropping it in _/usr/share/icons/hicolor/scalable/apps/_ ?

**Comment by ilya-fedin** [comment]
This error is printed by Qt. The cause is not necessary the telegram.png, one has to debug Qt to find the real cause.

**Comment by ilya-fedin** [comment]
I don't think it's a bug in Telegram

**Comment by Cbhihe** [comment]
ok, I will look in the direction of qt, thank you. But before closing, allow me just one question you probably can answer effortlessly:  what ownership properties should the svg file have in _/usr/share/icons/hicolor/scalable/apps/_ ? "root:root" or something else ? Or does that depend on the Qt ressource wanting to access it ?
Closing. Tx.
