### ISSUE TITLE
Json export escapes too much

### ISSUE THREAD

**Issue by ololoe** [telegramdesktop/tdesktop#25183]
### Steps to reproduce

Slashes do not need to be escaped in json.

### Expected behaviour

    "https://t.me/

### Actual behaviour

    "https:\/\/t.me\/

### Operating system

windows 10

### Version of Telegram Desktop

xxx

### Installation source

Static binary from official website

**Comment by ololoe** [comment]
Всем похуй?

**Comment by john-preston** [comment]
@ololoe In code I can't see I escape '/', also I can't reproduce that:

![image](https://user-images.githubusercontent.com/17900494/233301368-9d0be354-34ff-4842-8155-232b459e6ccb.png)
