### ISSUE TITLE
Try icon randomly switches to dark on dark background, becoming almost invisible

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#25180]
### Steps to reproduce

1. Install Telegram Desktop on Manjaro Linux via the AUR
2. run it
3. wait

### Expected behaviour

The tray icon should always be the same, and it should be visible.

### Actual behaviour

This is what the Telegram tray icon initially and normally looks like, which is correct:

![image](https://user-images.githubusercontent.com/13969584/194728200-e45e1cb3-ef6d-45b0-801a-67b114ffb768.png)

After a while, seeming randomly, it becomes like this:

![image](https://user-images.githubusercontent.com/13969584/194728226-2fef0c7a-a6bc-4f48-b619-0b45a677f77c.png)

which is practically invisible.

### Operating system

Manjaro Linux

### Version of Telegram Desktop

4.2.4-1

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
This icon recoloring happens on Plasma side, so this likely to be a Plasma bug

**Comment by php4fan** [comment]
> This icon recoloring happens on Plasma side, so this is likely to be a Plasma bug

None of the other icons get recolored. Telegram's is the only one. I'm not saying it _can't_ be a Plasma bug, but it seems _very_ unlikely.

**Comment by ilya-fedin** [comment]
As I said, Telegram is unaware of this recoloring, thus I don't imagine what we can do here.

**Comment by ilya-fedin** [comment]
> None of the other icons get recolored. Telegram's is the only one.

It's the other way around I believe. The svg on hard disk is black and Plasma applies its black magic to some of theme to make them follow the color scheme. It's a non-standard thing and no other DE does this.
