### ISSUE TITLE
Where is Telegram.sln?

### ISSUE THREAD

**Issue by Kolahzary** [telegramdesktop/tdesktop#2518]
I'm trying to open TelegramDesktop source in VS2015, but unfortunately i have no idea where the solution file is :/

> just open Telegram solution at D:\TBuild\tdesktop\Telegram.sln
https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-msvc.md

**Comment by auchri** [comment]
You have to generate it first: https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-msvc.md#setup-gypninja-and-generate-vs-solution
