### ISSUE TITLE
linux版本，中文输入法不能输入

### ISSUE THREAD

**Issue by jianghukuangke** [telegramdesktop/tdesktop#25181]
### Steps to reproduce

- 通过 AUR 在 Manjaro Linux 上安装 Telegram Desktop
- 运行
- 等待
- 输入法框架使用的是fcitx
- 操作系统是manjaro
- 输入法使用 googlepinyin 和搜狗输入法都不行。
- 尝试使用`env QT_IM_MODULE=fcitx telegram-desktop`命令启动还是不行

### Expected behaviour

应该可以正常使用输入法输入中文

### Actual behaviour

不能使用输入法输入中文

### Operating system

5.13.19-2-MANJARO

### Version of Telegram Desktop

4.2.4-1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
english only plz.

**Comment by ilya-fedin** [comment]
@Aokromes close
