### ISSUE TITLE
Can't stop GIF in discussion

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25185]
### Steps to reproduce

1. Go to https://t.me/DailyUkrainianNews/41184?comment=2081389 for example
2. Play GIF (autoplay must be disabled)
3. Try to stop it
4. You can't

https://user-images.githubusercontent.com/39812401/195328948-0ddb41a2-44f9-4050-af19-bf40aa5ee47e.mp4

### Operating system

Windows 10

### Version of Telegram Desktop

4.2.4

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Can't reproduce.

**Comment by Neurotoxin001** [comment]
Now me too. Maybe it was temporarly bug…
