### ISSUE TITLE
Telegram On Fedora 36 Workstation look like slightly zoomed in, UI doesnt scale properly on GNOME

### ISSUE THREAD

**Issue by Raul1198** [telegramdesktop/tdesktop#25186]
### Steps to reproduce

1. open telegram
2. check the pointer size i outside telegram 
3. move the pointer over telegram
4. check the pointer & ui scaling

### Expected behaviour

the pointer and application ui scaling remains same as any other app

### Actual behaviour

telegram looks slightly zoomed in with a bigger pointer when on telegram here is example

![Screenshot from 2022-10-13 18-25-39](https://user-images.githubusercontent.com/29801315/195602289-3a521e35-79c9-45e2-a6e1-358989bb610f.png)
![Screenshot from 2022-10-13 18-25-48](https://user-images.githubusercontent.com/29801315/195602306-2db4b25a-0158-4f69-a203-9c1c173e76a5.png)
![Screenshot from 2022-10-13 18-34-29](https://user-images.githubusercontent.com/29801315/195604262-3ef6c1e3-8508-44fd-b3fb-f9661025cc97.png)
![Screenshot from 2022-10-13 18-34-38](https://user-images.githubusercontent.com/29801315/195604292-0ca12be1-e78d-48ba-aa96-6361ec531e18.png)

 

here in  image check the pointer when it in telegram and compare it when its outside telegram, tried with both Application UI scaling set to 100% and 125%

### Operating system

Fedora 36 Workstation

### Version of Telegram Desktop

4.2.4

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
The pointer is bigger because GNOME doesn't set cursor theme and size for non-gtk applications, not because scale.
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5894
