### ISSUE TITLE
(Linux) File Chooser not showing image preview anymore

### ISSUE THREAD

**Issue by scarf** [telegramdesktop/tdesktop#25193]
Telegram Desktop 4.2.4
Gnome 43.0
GTK 4.8.1

When I try to send an image with the paperclip button, a gtk4 File Chooser ("Choose Files") opens up.  However when I select the image, it doesn't show a preview thumbnail to the right like it used to.  I thought that would be part of the File Chooser but apparently this is Telegram's responsibility:

[Emmanuele Bassi](https://discourse.gnome.org/u/ebassi) ([GNOME Team](https://discourse.gnome.org/g/foundation-members)) [said](https://discourse.gnome.org/t/file-chooser-gtk-4-image-preview/11510/2):
> Application developers can reimplement the same functionality using a GtkFileChooserWidget inside a GtkDialog, and adding the same preview widget directly to the dialog; then they can listen to the selection changes on the file chooser widget to update the preview, just like the old preview widget did.

Is it something you can implement so we can have previous preview functionality back?  Perhaps you could make it even better by adding support for other files like a video preview, document preview, etc.
Thanks

**Comment by Aokromes** [comment]
i see @ilya-fedin blaming gnome again LOL

**Comment by ilya-fedin** [comment]
By default, official builds use xdgdesktopportal Qt platformtheme, so your dialogs are what your system provides, `QT_QPA_PLATFORM=gtk3` may help, although relying on Qt's gtk intergration is not something I would suggest as I would like to remove it as soon as there's better alternative appear (e.g. xdg-desktop-portal starts providing cross-desktop keys for basic settings like icon theme) as there's a huge Qt patch to make the binary to not hard-depend on gtk (without patching, Qt hardly links gtk, yes) and rebasing it is not fun.

So I recommend to file this against your xdg-desktop-portal backend.
