### ISSUE TITLE
Telegram Desktop should follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by Self-Perfection** [telegramdesktop/tdesktop#25194]
### Steps to reproduce

1. Run Telegram Desktop
2. Observe it stores its data at `$HOME/.TelegramDesktop/tdata`
3. Caches are stored in `$HOME/.TelegramDesktop/tdata/user_data/cache` and `$HOME/.TelegramDesktop/tdata/user_data/media_cache`

Flatpak installation uses non-standard locations as well.

### Expected behaviour

Telegram Desktop should adhere to [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

That means:
* User specific data should be stored in `$XDG_STATE_HOME` subdirectory (this `$HOME/.local/state` by default)
* Caches should be stored in `$XDG_CACHE_HOME` subdirectory

Well at least I'd hope caches will follow https://bford.info/cachedir/ spec. This spec requires marking cache directories by placing `CACHEDIR.TAG` with specific header to let backup software know that this directory may be skipped.

### Actual behaviour

Standard file location conventions are ignored.

### Operating system

GNU/Linux

### Version of Telegram Desktop

3.x, 4.x

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
#107

**Comment by ilya-fedin** [comment]
There's no plan to implement this feature request though, so unless someone interested would volunteer, this is unlikely to be ever implemented
