### ISSUE TITLE
Allow to resize message block in chat window (Relive #2060)

### ISSUE THREAD

**Issue by mb6ockatf** [telegramdesktop/tdesktop#25197]
### Steps to reproduce

Open chat window

### Expected behaviour

User can change width of message with mouse

### Actual behaviour

Message width is fixed

### Operating system

Linux Mint 21 (Vanessa); Windows 10 21H2

### Version of Telegram Desktop

4.2.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Sorry, but as was mentioned in #2060, this is wontfix
