### ISSUE TITLE
How can I solve error build: Command CodeSign failed with a nonzero exit code?

### ISSUE THREAD

**Issue by MarcoCode23** [telegramdesktop/tdesktop#25191]
I am trying to build the project on my MacBook M1, but it fails with this error build: Command CodeSign failed with a nonzero exit code.
I did not anything different from the guide [building-mac.md](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-mac.md).
Anyone know how can I solve this problem?
Thanks.

**Comment by AndresHN** [comment]
Bro, Did you solve your problem?, I'm having the same problem.

**Comment by MarcoCode23** [comment]
Nope!

**Comment by Codeman-from-unknown-city** [comment]
Hi! Any updates?

**Comment by john-preston** [comment]
This looks like a problem with too large binary file. I'm not sure how to fix that in Xcode, I know that if I strip the resulting binary and after that signing works.

**Comment by IgorKey** [comment]
@john-preston hi. can u help me with a guide, how to strip the resulting of binary file... thx.

**Comment by kucaca** [comment]
@IgorKey 
Select Targets Telegram
Architectures  x86_64 arm64 -> x86_64
clean -> Run or Build

**Comment by landaire** [comment]
I think @john-preston is right. The resulting Telegram binary size on my machine is a whopping 4.8GB... Stripping it brings the size down to 643MB.

There is a concept of "dSYM" files which work similarly to PDB files on Windows -- i.e. the DWARF debugging info is in a separate file from the main binary. You can change the Debug Information Format settings to use this. I had some troubles, but maybe someone else can use it as a start (or use it to strip the binary while retaining debugging info):

<img width="722" alt="image" src="https://user-images.githubusercontent.com/1313522/224567756-fc668b15-6f82-440b-91a4-f1be39bcd609.png">

**Comment by 315567599** [comment]
> @john-preston hi. can u help me with a guide, how to strip the resulting of binary file... thx.

how to ？
