### ISSUE TITLE
Weird hand cursor in Flatpak tdesktop

### ISSUE THREAD

**Issue by serjflint** [telegramdesktop/tdesktop#25196]
> Looked online for the solution with flatpack. This is a known issue with flatpack but finally found a solution:
> https://github.com/flatpak/flatpak/issues/709#issuecomment-741883444
> `flatpak --user override --filesystem=/home/$USER/.icons/:ro`
> `flatpak --user override --filesystem=/usr/share/icons/:ro`
> 
> This makes flatpack access the same cursor style as the systems. Leaving the solution here in case anyone comes from a web-search. As this has been pointed out many times in the past here on the "Tdesktop issue", this would save time both for you and the users.

_Originally posted by @erebus-oneiros in https://github.com/telegramdesktop/tdesktop/issues/10321#issuecomment-774667429_

That solution didn't help me. 
Are there any more ideas? Should I use a specific system theme?

**Comment by ilya-fedin** [comment]
hand? Do you mean the generic pointer is ok?

**Comment by erebus-oneiros** [comment]
> That solution didn't help me. Are there any more ideas? Should I use a specific system theme?

The latest version of flatpak Telegram (v4.2.4) on KDE Neon 5.25 with kernel 5.15.0-48 doesn't show any weird behavior for me. I do not know how to reproduce the problem, so I don't think I can help you with this.

**Comment by lowitea** [comment]
I have the same problem

```
$ neofetch --off

------------ 
OS: Fedora Linux 36 (Workstation Edition) x86_64 
Host: MRGF-XX M1010 
Kernel: 5.17.5-300.fc36.x86_64 
Uptime: 7 hours, 16 mins 
Packages: 2080 (rpm), 24 (flatpak) 
Shell: zsh 5.8.1 
Resolution: 3120x2080 
DE: GNOME 42.5 
WM: Mutter 
WM Theme: Flat-Remix-Blue-Dark 
Theme: Flat-Remix-GTK-Blue-Dark [GTK2/3] 
Icons: Flat-Remix-Blue-Dark [GTK2/3] 
Terminal: tmux 
CPU: 12th Gen Intel i7-1260P (16) @ 4.700GHz 
GPU: Intel Alder Lake-P 
Memory: 11236MiB / 15719MiB

$ flatpak --version
Flatpak 1.12.7

$ flatpak info org.telegram.desktop                                               

Telegram Desktop - Fast. Secure. Powerful.

          ID: org.telegram.desktop
         Ref: app/org.telegram.desktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.2.4
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 145,4 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 7fe9364426699ce62ec74663fc756a533057367855ddb14a52580f17afcbce27
      Parent: 6555e2bf44383579268d7f5d359a6208597779f53b4f1152117ebdf113868203
     Subject: Update tdesktop.git to 4.2.4 (5eecfef9)
        Date: 2022-09-30 15:33:33 +0000
```

**Comment by ilya-fedin** [comment]
can you answer the question?

**Comment by ilya-fedin** [comment]
I guess you have https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5894

**Comment by lowitea** [comment]
Yes. This seems to be true in my case. Thanks.
