### ISSUE TITLE
Desktop App won't send code via SMS

### ISSUE THREAD

**Issue by ShervanN** [telegramdesktop/tdesktop#25190]
### Steps to reproduce

Launch desktop App and Login with phone number and click next
Code gets sent via telegram to other device (No access to other device, hard disk failed and had to format it)
Click send code via sms (Since I have access to the mobile phone number)

### Expected behaviour

Should send code to the phone number

### Actual behaviour

Got dialog with "Please enter the code that was sent to you via telegram or login via QR code. If you haven't signed up for telegram yet, please register from your phone or tablet first"

### Operating system

Windows 10

### Version of Telegram Desktop

4.2.4.0

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
not a bug

**Comment by ShervanN** [comment]
What do I do? I want to login to my account in Telegram Desktop.

**Comment by Aokromes** [comment]
> If you haven't signed up for telegram yet, please register from your phone or tablet first"

^^

**Comment by ShervanN** [comment]
> > If you haven't signed up for telegram yet, please register from your phone or tablet first"
> 
> ^^

What is the purpose and benefit of this policy?
