### ISSUE TITLE
[Question] Why in Russified version of TD the tooltips and dialog boxes are in English language?

### ISSUE THREAD

**Issue by soviet-man** [telegramdesktop/tdesktop#25195]
**Tooltip with date of the post**

![изображение](https://user-images.githubusercontent.com/33825590/196016504-fd3bf490-3992-4aa9-91b4-38bbdbf1802a.png)

**Dialog box**

![изображение](https://user-images.githubusercontent.com/33825590/196016511-c9e52878-e532-4889-a983-e5993800da3c.png)

**Comment by ilya-fedin** [comment]
This bugtracker is English-only
@Aokromes can you close the issue?

**Comment by soviet-man** [comment]
OK. I will duplicate it in English

**Comment by ilya-fedin** [comment]
You can edit the title and content

**Comment by soviet-man** [comment]
Done

**Comment by ilya-fedin** [comment]
The date uses QLocale that as far as I understand gets names for embedded CLDR tables according to your system locale settings, so it's most likely a system misconfiguration

The buttons on the dialog are just not exposed to the translation platform, a valid bug you can report probably.

**Comment by ilya-fedin** [comment]
It seems the date/time format is actually bugged, too. Due to Qt 6 API behavior change. Fixed on dev branch.
