### ISSUE TITLE
Launch at Startup option broken on OS X

### ISSUE THREAD

**Issue by cimm** [telegramdesktop/tdesktop#252]
The `Launch at Startup` check-box in `Settings → Advanced Settings` doesn't work on OS X Mavericks (haven't tested on Yosemite yet). I can select the check-box but it gets deactivated immediately.

**Comment by auchri** [comment]
Fixed?

**Comment by cimm** [comment]
I can't seem to find the `Launch at Startup` option anymore. Was the option removed or am I completely failing to find it?

**Comment by auchri** [comment]
I think it was removed. But you can right click on the symbol in the dock and selected "Options -> Open at login"

**Comment by auchri** [comment]
Or go to settings -> Accounts -> Login Items and select Telegram Desktop there

**Comment by telegramdesktop** [comment]
This issue is about other application (OS X native app), it has nothing to do with Telegram Desktop (which at least does not have Settings -> Advanced Settings menu) and which does not support in-app setting for starting app with system start.
