### ISSUE TITLE
Abnormal CPU usage when Animated Sticker reaches the last frame when "Loop animated stickers" is off.

### ISSUE THREAD

**Issue by KynikossDragonn** [telegramdesktop/tdesktop#25200]
### Steps to reproduce

1. Turn off "Enable animations", under "Advanced" in Settings.
2. Turn off "Loop animated stickers" under "Chat Settings" in Settings.
3. Have a animated sticker sent in a currently selected chat.
4. Have the application remain focused in the foreground for as long as it takes for the initial animation to play out and not loop.
5. Continue having the chat selected and program focused in the foreground after the animated sticker stops.

### Expected behaviour

CPU usage shouldn't immediately max out a single core when the animated sticker finishes playing once.

(Animated stickers should also be disabled if "Enable animations" is turned off as well?)

### Actual behaviour

A thread appears to lock at 100% userland CPU usage as long as the chat with the animated sticker is selected and the program is in the foreground.

CPU usage returns to normal only when the animated sticker is deleted from history, or is scrolled past history and the chat re-selected after it has been buried enough back in chat history for it to not show up when the chat is re-selected.

CPU usage also returns to normal if the program is unfocused, or a different chat is selected once the abnormal CPU usage begins.

### Operating system

Void Linux, Xfce 4.16

### Version of Telegram Desktop

4.2.4

### Installation source

Static binary from official website

**Comment by qmmp123** [comment]
There is the same problem on MacOS client
Telegram version: 9.1.1.238861 Stable
MacOS: 12.3.1

**Comment by Aokromes** [comment]
> There is the same problem on MacOS client Telegram version: 9.1.1.238861 Stable MacOS: 12.3.1

you are using https://github.com/overtake/TelegramSwift

**Comment by qmmp123** [comment]
> you are using https://github.com/overtake/TelegramSwift
Oh I'm sorry
