### ISSUE TITLE
Unicode Characters not created with key combination

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#2520]
When pressing the key combination of CTRL+ALT+U and entering the unicode code, it simply prints out the letters and numbers of the code, not the actual unicode character.

**Operating system:**
Ubuntu 16.10

**Version of Telegram Desktop:**
0.10.11

**Comment by diazbastian** [comment]
See #1033 and #1288... Unicode input is a GTK+ feature (Telegram uses QT). Try to setting ibus correctly (ibus-qt is necessary sometimes) This solve your problem.

![ibus](https://cloud.githubusercontent.com/assets/5126124/19299845/28eb204e-902d-11e6-8bd5-46624c69fc4a.png)

Note: Ubuntu 16.10 is developing a distribution and as such may have independent problems.

**Comment by luisalvarado** [comment]
Thank you.
