### ISSUE TITLE
Double quotes around $EnvVars

### ISSUE THREAD

**Issue by Egor-Skriptunoff** [telegramdesktop/tdesktop#25202]
There is a minor mistake in the Linux build instructions.  

Building telegram desktop from sources in a directory containing spaces in its name results in error.  
How to fix: wrap `$PWD` with double quotes in `building-linux.md` instructions.

**Comment by Egor-Skriptunoff** [comment]
Bot, please don't close as "completed" issues which are not completed yet.  :-)

**Comment by Aokromes** [comment]
if you don't answer when bot asks you it will be closed.

**Comment by ilya-fedin** [comment]
@Egor-Skriptunoff I don't understand what's the point of this to be open, it's trivial to do a PR for this and it feels like this is bumping the number of issues for no good.
