### ISSUE TITLE
[Question] Windows Build 

### ISSUE THREAD

**Issue by av100** [telegramdesktop/tdesktop#25201]
Which version of Qt to install and which components to choose when installing?
![image](https://user-images.githubusercontent.com/33670005/196061137-06360576-2ca0-4499-a8d0-bbd215cb4fba.png)

**Comment by john-preston** [comment]
The only supported way to build Windows version: https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md
