### ISSUE TITLE
Telegram calls only rings but not get connected

### ISSUE THREAD

**Issue by mostafaznv** [telegramdesktop/tdesktop#25207]
I'm using Telegram Desktop through internal socks5 proxy (main proxy protocol is v2ray-vmess) with turned-on "Use for Calls"
Telegram call rings, but not get connected. it stopes on exchanging keys ...

The fun part of this story is when I want to make a call with my iPhone, there is no problem (I'm using the same proxy in my phone, using socks5/vmess)

What is the exact problem?
Why I can't make calls in Telegram Desktop and even Telegram Mac?
What is the difference?

> note: My VPN and socks5 can handle UDP (UDP relay)

**Comment by ilya-fedin** [comment]
#23916
