### ISSUE TITLE
[Feature Request] Option to disable animated emoji

### ISSUE THREAD

**Issue by LexaGV** [telegramdesktop/tdesktop#25209]
### Problem

In the contact list I see Name and Last message from this contact. IT IS COOL. But... some stupids overuse right to put emoji and start using ANIMATED emoji at start of the message. As a result, I see contacts list and flashing bulbs, which distract me from selecting contact!
Obviously this "look at me first" annoys.

### Describe the solution you'd like

Please make option to enable/disable all animation/stickers related content!

Ideally if it will look like this:
::: Contact list :::

[x] Show emoji
[x] Enable animated emoji

::: Message Panel :::

[x] Show stickers
(o) Never animate sticker
( ) Animate sticker once
( ) Animate sticker infinitely

[x] Show emoji
[x] Enable animated emoji

### Describe alternatives you've considered

No alternatives.

### Additional context

This is red BLINKING idiotic emoji I talked about!
![Capture](https://user-images.githubusercontent.com/105804544/196715145-b7f460d8-1ed2-4aa7-8dca-ca233ec842e9.PNG)

ATTENTION TO DEVELOPERS: please BEFORE introducing ANY "blinking", "rolling", "animated" or any other "taking attention" features THINK TWICE how to make 'em OPTIONAL. I understand your wish to make Telegram as "Christmas tree" to satisfy young lemmings/advertizers, but many ADULT PEOPLE use Telegram too - think about us, we're not idiots to play emoji, stickers, etc. BE SERIOUS!

**Comment by BoffinBrain** [comment]
I want this too.

Shortly after animated stickers were created, we've had a setting for "**Loop animated stickers**" which, when unchecked causes them to only play once. This setting also applies to animated emoji, but animations will still always play once, and they can theoretically be very long. The "**Enable animations**" setting also doesn't affect any of this.

We need these settings to be improved, especially now people with Telegram Premium can put arbitrary custom emoji at the end their display names.

**Comment by axhan** [comment]
This. I'm at the point where I most days close the application in a fit of annoyed rage a short time after my daily computer bootup and application autostart. TBH I consider gratuitous moving, blinking, animated thingies in an application with no possibility of turning them off completely to be a form of abuse, especially against those of us with attention-deficit disorders.

**Comment by Ratfink** [comment]
I am very in favor of this option.  It's actually an accessibility issue, because as mentioned, people with attention-deficit disorders and related conditions can be adversely affected by all the little moving things.  There's a switch in the advanced settings to "enable animations", but turning this off seems to leave most animations in the app enabled.

**Comment by ShadowJonathan** [comment]
To be completely honest, I don't believe telegram has a good-faith interest in getting this resolved, as their recent "features" - which are driven with subscriptions - seem to only increase the visual noise and animations on the screens of other users (full-screen sticker animations, animated avatars, animated emoji, animated stickers, etc.)

On top of that it seems that this change (animated emoji) were introduced without any regard for accessibility in the first place, and on top of that accessibility was not a priority to be cross-platform consistent, as you can see that some things are availible for ios, some for android, and some for desktop, but not in all.

So I believe that it's safe to say that Telegram does *not* have *any* interest in spending development resources in accessibility at all, especially if their monetary features are only driving in the opposite direction.

**Comment by LexaGV** [comment]
While I completely support what @ShadowJonathan said, I still CANNOT BELIEVE somebody thinks that he can increase sells by ANNOYING customers with all that sh%%%t - animations, flashing background, scrolling text, etc and advertising as a whole. Practice of advert shows that people rather study AdBlocker than allow pages annoy 'em with "buy our elephants". Advert doesn't work, let's loudly confirm it.

**Comment by Neurotoxin001** [comment]
Animated emoji in user status (near nickname) is runs again when I scroll chat. And if user puts epylepsy blinking emoji it's looks awful every time user write in chat or when I scroll the chat.

**Comment by Neurotoxin001** [comment]
It's already released in 64Gram so you can just copy-paste it https://github.com/TDesktop-x64/tdesktop/commit/5c7e5609bf9acfb33be8f766305ee2e306845439

**Comment by Neurotoxin001** [comment]
This commit is buggy btw https://github.com/telegramdesktop/tdesktop/commit/991fe491c5ae62705d77aa8fdd44a79caf639c45
After post with animated emoji gets first reaction from users — it's start animation in chats list again.

**Comment by john-preston** [comment]
It's fine, more or less. The message gets edited, so the regular edition logic applies. The idea was not to animate infinitely.

**Comment by Neurotoxin001** [comment]
> It's fine, more or less. The message gets edited, so the regular edition logic applies. The idea was not to animate infinitely.

Can you check this issue with more details about this bug:
https://github.com/telegramdesktop/tdesktop/issues/25638

**Comment by Neurotoxin001** [comment]
Will be available in next version https://github.com/telegramdesktop/tdesktop/commit/2a4c39b9d7e6ac8df2d474de6693581fdd2ab78f

**Comment by Neurotoxin001** [comment]
This https://github.com/telegramdesktop/tdesktop/commit/2a4c39b9d7e6ac8df2d474de6693581fdd2ab78f does not include disabling animated emoji near user nickname and in user profile, so this issue must be reopened…

**Comment by Neurotoxin001** [comment]
Now it's finally released https://github.com/telegramdesktop/tdesktop/commit/e6b92eaf37e07f3d6c4acf13c547d09bdd6fe111

**Comment by ShadowJonathan** [comment]
It was released as an optimisation feature, not an accessibility one...

**Comment by Neurotoxin001** [comment]
> It was released
