### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by indiebio** [telegramdesktop/tdesktop#25206]
### Is your feature request related to a problem?

When I want to minimise the window on Ubuntu I often accidentally call someone, because the call and the minimise button are too closely together for my clumsy fingers

### Describe the solution you'd like

The search, call, etc toolbar moved to the other side of the minimise/maximise/close toolbar.

### Describe alternatives you've considered

I have considered being more careful of where I point and click... but I am not good at it. Especially when I am annoyed at someone, want to remove myself from the situation and end up calling them instead! An introvert's nightmare!

### Additional context

Thanks :) I think this is mainly an issue in later versions, I think I have only been annoyed by this more recently. So perhaps revert to whatever was done previously?

**Comment by Aokromes** [comment]
duplicate.
