### ISSUE TITLE
[Question] Telegram PDB

### ISSUE THREAD

**Issue by WLKFN** [telegramdesktop/tdesktop#25208]
Hey,

I'm trying to look into something and currently need to correlate the IDA Pro output and the source code.
A PDB would simplify this process 1000 times.

I'll be honest, I'm too lazy to set up the whole dev. environment just to get the .exe + .pdb.

I've tried to get them via GitHub actions, but it seems like the artifacts are not getting uploaded.

So, can someone please provide a telegram.exe with the associated .pdb.
Anything from the last year or two would actually do the job just as fine as the current release.

It would help out quite a lot, thanks in advance :)

**Comment by 23rd** [comment]
It can be done via Github actions with the simples changes.

**Comment by WLKFN** [comment]
> can someone please provide a telegram.exe with the associated

how exactly I've tried but I could not get it to work.

**Comment by ilya-fedin** [comment]
@23rd won't it fail due to the lack of the storage space?
@WLKFN I think you have no other choice than setting up development environment and build Telegram on your machine.

**Comment by 23rd** [comment]
@WLKFN https://github.com/23rd/tdesktop/actions/runs/3282121230

**Comment by 23rd** [comment]
For future references: 7a4ffa8892ca2994cbbbf6be4dda0ac1e742860b.
