### ISSUE TITLE
[Question] Why emoji has low quality?

### ISSUE THREAD

**Issue by milden6** [telegramdesktop/tdesktop#25218]
Hi! I have created emoji in SVG format, then I have exported it to PNG with 100x100 resolution, like described here https://core.telegram.org/stickers#static-stickers-and-emoji

But my emoji has low quality and blurred. But I saw another emoji with perfect quality. So, my question is how to create emoji with best quality?

![Screenshot 2022-10-22 182145](https://user-images.githubusercontent.com/39964648/197347380-6c801bb2-bf64-4796-b0a9-03eb58dd8002.png)
My emoji is second

**Comment by john-preston** [comment]
@milden6 Best quality is lottie animated emoji, they're in vector format.

**Comment by milden6** [comment]
@john-preston ok, how to upload emoji in vector format? I see only PNG and WEBP
https://core.telegram.org/stickers#static-stickers-and-emoji

**Comment by milden6** [comment]
I found solution. Need to upload emoji in .TGS format and quality will be great
