### ISSUE TITLE
Telegram snap for armhf is an old version

### ISSUE THREAD

**Issue by archisman-panigrahi** [telegramdesktop/tdesktop#25217]
### Steps to reproduce

Telegram for snap for armhf is still at version 4.0.2, whereas other architectures host the latest version 4.2.4.

Please update the armhf version of snap to the latest version.

### Expected behaviour

The armhf snap should offer the latest telegram. Except snap, there is no other way to get the latest telegram on Raspberry Pi OS (armhf), since flatpak has stopped offering armhf builds. However, the snap hosts an older version of Telegram.

### Actual behaviour

The armhf snap installs an older version of telegram.

### Operating system

Raspberry Pi OS (bullseye)

### Version of Telegram Desktop

4.0.2

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Here's the build log of failing build attempt on Launchpad: https://launchpad.net/~telegram.desktop/+snap/telegram-desktop-master/+build/1896902/+files/buildlog_snap_ubuntu_jammy_armhf_telegram-desktop-master_BUILDING.txt.gz

Feel free to fix it if you know how to, personally I don't see a way.

**Comment by apandada1** [comment]
I asked a question in Launchpad, and someone pointed out some compiler flag which might be causing the issue. I was also asked to contact the people in the team https://launchpad.net/~telegram.desktop, but I don't know if they are the same people as you.

https://answers.launchpad.net/launchpad/+question/703579

**Comment by ilya-fedin** [comment]
Yeah, launchpad repository is owned by @john-preston, but I don't think he even looks there. Unfortunately, we have no idea what to do with this flag, we're just trying to build openssl 1.1 (as we're not compatible with openssl 3 provided by core22) and it fails on armhf. We unfortunately don't have enough experience in ARM-specific compiler flags to fix this on our own.

**Comment by xvitaly** [comment]
> We unfortunately don't have enough experience in ARM-specific compiler flags (nor in openssl build system) to fix this on our own.

Can you try [this patch](https://src.fedoraproject.org/rpms/openssl1.1/blob/rawhide/f/openssl-1.1.1-arm-update.patch)?

**Comment by ilya-fedin** [comment]
That patch seem to touch only armv8 (arm64) assembler code while the problem is with armv7 (armhf). arm64 builds just fine.

**Comment by ilya-fedin** [comment]
And I don't understand how patching assembler code would help with building C code

**Comment by xvitaly** [comment]
@ilya-fedin On Fedora it builds fine for armv7hl: https://koji.fedoraproject.org/koji/buildinfo?buildID=1997398

You can check all patch set here: https://src.fedoraproject.org/rpms/openssl/tree/f35

**Comment by ilya-fedin** [comment]
I believe it's related to Ubuntu gcc's embedded compiler flags as the flags it complains at is not present in command line

**Comment by ilya-fedin** [comment]
I don't think this is fixable... Even though snap no more builds openssl, it now fails at building libyuv. It seem to fail in assembler code with the following creepy errors. It looks like the dependencies tdesktop relies on just don't care about armv7 anymore, so providing armv7 builds is no more feasible.
![изображение](https://user-images.githubusercontent.com/17829319/235512564-92fb644a-8c4a-4aa0-9d58-afc75d98ac36.png)

**Comment by ilya-fedin** [comment]
Looks like it go fixed after the last dependency update round
![изображение](https://github.com/telegramdesktop/tdesktop/assets/17829319/1a1626e7-6fdf-4567-92f0-65b8d2ed7471)
