### ISSUE TITLE
Fail to Build...

### ISSUE THREAD

**Issue by XJL0930** [telegramdesktop/tdesktop#25224]
It seems like many files didn't download correctly.What should I do?
![image](https://user-images.githubusercontent.com/102529729/197936736-fed44182-2992-45e7-a70f-c45f6ca1fd46.png)

**Comment by ILG2021** [comment]
Please fellow the instructions strictly. Things will going well.
https://github.com/telegramdesktop/tdesktop#build-instructions

**Comment by XJL0930** [comment]
> Please fellow the instructions strictly. Things will going well. https://github.com/telegramdesktop/tdesktop#build-instructions

ummmm......Actually,I follow every step of it.But it still lack these files :(
Should I restart this?Or try to install the tools again?

**Comment by ilya-fedin** [comment]
Those files will appear only after building

**Comment by XJL0930** [comment]
> 

I followed the previous steps...but in sln I meet this problem :(

**Comment by ilya-fedin** [comment]
This is not a problem, you still can start the build process and it should success. Once tdesktop is built, those errors should disappear.

**Comment by XJL0930** [comment]
> This is not a problem, you can still start the build process and it should success. Once tdesktop is built, those errors should disappear.

So I should build Telegram again?

**Comment by XJL0930** [comment]
> The fact you see those errors means Telegram is not built as these files are generated by codegens

ummm.....So how can I solve this?qwq

**Comment by ilya-fedin** [comment]
> So how can I solve this?

Actually build Telegram. And ensure it's built successfully.

**Comment by XJL0930** [comment]
> > So how can I solve this?
> 
> Actually build Telegram. And ensure it's built successfully.

Ok.I will try it again.Thank you very much.  :)

**Comment by ilya-fedin** [comment]
It may be a good idea to build from command line as you may not see actual build errors when you have a lot of IntelliSense errors

**Comment by XJL0930** [comment]
I try again and it still worked as above.Should I add this files mannually?The codegen seems didn't work....

**Comment by XJL0930** [comment]
> 

![image](https://user-images.githubusercontent.com/102529729/198171704-0a5e9411-39d0-4754-b217-ffd557cb3378.png)
I think this represents a successful operation.
And my friend just run it successfully,so I think maybe I can copy some files from his...？

**Comment by ilya-fedin** [comment]
`cmake --build out --config Debug`

**Comment by XJL0930** [comment]
> `cmake --build out --config Debug`

In D:\TBuild\tdesktop\Telegram?

**Comment by ilya-fedin** [comment]
Have you tried `Build -> Build Solution` in Visual Studio?

**Comment by XJL0930** [comment]
> cmake --build out --config Debug

Actually yes,and the above is the result of it.Many files couldn't be found.

**Comment by ilya-fedin** [comment]
> In D:\TBuild\tdesktop\Telegram?

No, it's a command for the parent directory, but you can do `cmake --build ../out --config Debug` in this directory

**Comment by ilya-fedin** [comment]
> Actually yes,and the above is the result of it.Many files couldn't be found.

I guess you made a screenshot of the wrong tab then? I believe Visual Studio should have a tab with build output, but you provided a screenshot of IntelliSense errors.

**Comment by XJL0930** [comment]
![image](https://user-images.githubusercontent.com/102529729/198172995-bfb2f4a4-b06c-400b-bd89-f848c438841b.png)
![image](https://user-images.githubusercontent.com/102529729/198173022-754c6e2a-96b0-423e-b62c-2b2b57259bc4.png)
Oh,those are the build output errors,almost all of them are the "No such file"

**Comment by ilya-fedin** [comment]
No, those aren't build errors, those are IntelliSense errors.

**Comment by XJL0930** [comment]
![image](https://user-images.githubusercontent.com/102529729/198173474-9660934b-23cf-45bb-8beb-b48145e62955.png)
![image](https://user-images.githubusercontent.com/102529729/198173498-0b3d74dc-b6f9-4b32-82ec-02a18d7e89cd.png)
Are those build errors?

**Comment by ilya-fedin** [comment]
Yeah, looks like that, but those don't tell the real problem. It seems codegens resulted with error, but it doesn't provide codegen outputs :thinking:

**Comment by ilya-fedin** [comment]
Or maybe it's written in Chinese (the line under "Generating styles"), but I don't understand Chinese

**Comment by XJL0930** [comment]
> Or maybe it's written in Chinese (the line under "Generating styles"), but I don't understand Chinese

ohoh, It means that The system cannot find the specified path

**Comment by ilya-fedin** [comment]
Oh, yeah, it's likely the actual error. It sounds like it can't find the executable, try to clean the `out` directory, relaunch `configure.bat` and `cmake --build`

**Comment by XJL0930** [comment]
ohoh,Thanks.And how can I clean the out directory ?Just delete all the files in it?

**Comment by ilya-fedin** [comment]
no, delete the directory itself. But I see the path to the codegen_style.exe, can you confirm it exists? If yes, what would happen if you run it manually in console?

**Comment by XJL0930** [comment]
> no, delete the directory itself. But I see the path to the codegen_style.exe on the screenshot, can you confirm it exists? If yes, what would happen if you run it manually in console?

ok,it does exist.I will try to run it manually.

**Comment by XJL0930** [comment]
![image](https://user-images.githubusercontent.com/102529729/198174990-81544464-01ae-4cd5-834d-cdbe99cc5ee1.png)
It is like that

**Comment by ilya-fedin** [comment]
What's the content of lib_ui_styles.rule?

**Comment by XJL0930** [comment]
![image](https://user-images.githubusercontent.com/102529729/198175450-3dbe0df9-d8fe-45d3-859e-c54d97f5423c.png)

**Comment by ilya-fedin** [comment]
Looks broken, try to remove the out folder

**Comment by XJL0930** [comment]
![image](https://user-images.githubusercontent.com/102529729/198176556-d123de53-7b25-4c2e-8b81-ad51b2ba6ec6.png)
![image](https://user-images.githubusercontent.com/102529729/198176600-5dd31fb1-de13-4575-b111-edcf293fb40b.png)
The result seems the same...

**Comment by XJL0930** [comment]
So should I try it again or add these file manually?

**Comment by ilya-fedin** [comment]
The most likely cause is some bug in cmake then, what version of cmake are you using?

**Comment by XJL0930** [comment]
![image](https://user-images.githubusercontent.com/102529729/198178054-a41d2b62-4650-4696-982e-215eceadf2db.png)

**Comment by ilya-fedin** [comment]
Have you installed cmake like mentioned in the building instruction? This cmake seem to be from Visual Studio rather than from official site

**Comment by XJL0930** [comment]
yes,I have.I follow every step of the building instruction.

**Comment by ilya-fedin** [comment]
Why does it use cmake from Visual Studio then?

**Comment by XJL0930** [comment]
![image](https://user-images.githubusercontent.com/102529729/198178915-87327bd6-ab83-40b7-863b-5881d118767c.png)

ummmm....I don't know yet.I did install the cmake above.Should I remove the cmake from VS？

**Comment by ilya-fedin** [comment]
> Should I remove the cmake from VS？

try to do `cmake --version` from tdesktop folder

**Comment by XJL0930** [comment]
![image](https://user-images.githubusercontent.com/102529729/198179299-8352a727-b848-49e1-87cd-7c6efe27c0df.png)

**Comment by ilya-fedin** [comment]
> Should I remove the cmake from VS？

Try to, that may help

**Comment by ilya-fedin** [comment]
Note that cmake version on your screenshot from site is a Release Candidate (not stable), if you scroll the page, you will see "Latest Release" which is stable. Note that the page has multiple "Latest Release" section, the really latest is the first one.

**Comment by XJL0930** [comment]
I found I don't know how to remove the VS cmake...how can I remove or disable it?

**Comment by ilya-fedin** [comment]
Apparently via Visual Studio Installer? The CMake integration component

**Comment by XJL0930** [comment]
It works successfully! Thanks for your patience very much!!!!! 👍
