### ISSUE TITLE
How to support multiple builtin languages?

### ISSUE THREAD

**Issue by ILG2021** [telegramdesktop/tdesktop#25225]
I find only one string file which named lang.strings in resource folder. So it can not support multiple builtin languages like android telegram app?

**Comment by ilya-fedin** [comment]
No, the language framework is entirely cloud-based. tdesktop forks usually implement custom translation systems. You can also adopt a well-known FOSS translation framework for your strings like gettext (there's ki18n framework by KDE that integrates it with Qt), Qt Linguist.
