### ISSUE TITLE
When pluging or unpluging an extra monitor the clicks aren't registered correctly

### ISSUE THREAD

**Issue by DiegoCicconi** [telegramdesktop/tdesktop#25226]
### Steps to reproduce

1. Have your laptop (MBP 13-inch, 2020) connected to an extenal monitor (Dell U2421E) with Telegram Desktop Open. Or, have telegram desktop open and conect to an external monitor. 
2. The window will not register clicks correctly. When trying to click some place, it's always skewed by the same proportion. Let's say: we try to click the first chat, and we end up clicking the 3rd on the list. Same for messages in the chat. 
3. The workaround that I found is clicking twice on the top bar, resulting in a window resizing that covers the entire screen, and clicking it again to resize to its original size. 

### Expected behaviour

We should have a correct clicking behaviour, where we click exactly where the cursor is at. 

### Actual behaviour

Clicks aren't being registered correctly. We end up clicking somewhere else to where the cursor is at. 

### Operating system

MacOs BigSur 11.7

### Version of Telegram Desktop

4.2.4

### Installation source

Mac App Store

**Comment by ilya-fedin** [comment]
I guess it's a Qt bug, can you check qBittorrent?
