### ISSUE TITLE
Non responsive alt+tab on Kubuntu

### ISSUE THREAD

**Issue by zim32** [telegramdesktop/tdesktop#25229]
### Steps to reproduce

1. Open telegram on Kubuntu
2. Use alt tab to switch between applications
3. When current app is telegram, press alt+tab again
4. If will freeze for several seconds

### Expected behaviour

No freezing while using alt tab

### Actual behaviour

It takes several seconds to alt tab from telegram. Other apps are switching fast.

Switching through mouse using app bar is quick. Only alt+tab is slow.

### Operating system

Ubuntu 22.04.1 (Kubuntu). KDE

### Version of Telegram Desktop

4.2.4

### Installation source

Static binary from official website

**Comment by zim32** [comment]
Ok the problem is with keyboard layout settings in Kubuntu. I had language switching policy set to **Application**. So every app has own language. In this case telegram alt+tab is slow.

When I set switching policy to Global issue dissapears and alt+tab is fast again.

**Comment by ilya-fedin** [comment]
I believe you've reported the issue to the wrong place: alt+tab is a system feature, if you have a problem with it, it's a problem with your system.

**Comment by zim32** [comment]
Very unfriendly message. Other apps works fine, this is only telegram app which is freezing. Bad support

**Comment by ilya-fedin** [comment]
As far as I understand your report, it's the system who freezes (that is, the shortcut is processed by your system, not by Telegram), not Telegram.

**Comment by zim32** [comment]
It is possible but because other apps don't freeze, it is also possible that telegram somehow processes locale or something like this. I will try to test more

**Comment by ilya-fedin** [comment]
I believe whatever application is doing, the system shouldn't freeze (unless there's high system load of course), so that's likely to be a bug in the shell.
