### ISSUE TITLE
`Use system proxy settings` does not use system proxy settings

### ISSUE THREAD

**Issue by Master811129** [telegramdesktop/tdesktop#25222]
### Steps to reproduce

- Set a proxy on your system settings.(both http and socks)
- open telegram
- click on spinny thing in the bottom-left
- click on `use system proxy settings`
- it wont connect

### Expected behaviour

Telegram should follow system proxy settings

### Actual behaviour

Telegram does not care and I should make a socks5 proxy inside telegram in order to connect
![Screenshot from 2022-10-24 13-09-45](https://user-images.githubusercontent.com/37829730/197501636-ba09e273-2407-43ac-adb6-d50ca39b41fb.png)
![Screenshot from 2022-10-24 13-32-48](https://user-images.githubusercontent.com/37829730/197501830-5d23df90-bf60-41b5-950b-b0ca0f885e50.png)

### Operating system

Arch Linux, No version (rolling) , GNOME,

### Version of Telegram Desktop

4.2.4

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
can you try disabling try to use ipv6?

**Comment by ilya-fedin** [comment]
I don't think Qt is compatible with GNOME's proxy settings :(
It checks environment variables, you can see the implementation at https://github.com/qt/qtbase/blob/dev/src/network/kernel/qnetworkproxy_generic.cpp.

If you believe Qt should read something different, feel free to report at https://bugreports.qt.io

**Comment by Master811129** [comment]
I tested the issue in KDE. Same thing. Maybe they use the same implementation(?). A LOT of linux users use kde or gnome as their DE. maybe implementing a work-around would be a good idea.

**Comment by ilya-fedin** [comment]
IIRC KDE has two variants of setting the proxy in the checkbox, one that sets with DE-specific configuration and one that sets with environment variables, apparently you have chosen the wrong one (or forgot to log out and log in).

I don't want to dance with DE-specific settings and DE-specific configuration systems, that would likely requires linking libraries of those DEs. If you want that to work in a good way, you should file issues to DEs to cooperate and finally stnadardize this, so all libraries have to look only in one place.
