### ISSUE TITLE
[Feature Request] Abilitly to restore dismissed pinned channel/group message

### ISSUE THREAD

**Issue by donnyquixotic** [telegramdesktop/tdesktop#25228]
### Is your feature request related to a problem?

When a pinned message is dismissed/closed from a channel/group, it cannot be restored without deleting user data and re-joining on fresh account.

### Describe the solution you'd like
Icon in group header indicating current pinned message is present with 'view' option

### Describe alternatives you've considered
- 'Restore pinned message' option from dropdown
- 'See pinned message'  option to auto scroll to currently pinned (but dismissed/closed) message. 
- re-join group to see pinned message without having to purge user data

### Additional context

[_SuperUser SE question from 2018_](https://superuser.com/questions/1367096/how-to-restore-pinned-message-in-telegram-super-group)

**Comment by ilya-fedin** [comment]
#5526
