### ISSUE TITLE
Telegram on Wayland has incorrect CSD and cursor theme

### ISSUE THREAD

**Issue by the-spyke** [telegramdesktop/tdesktop#25231]
### Steps to reproduce

1. Open Telegram Desktop under Wayland
2. Look at the window frame and the cursor

### Expected behaviour

Should work the same way as in case of X11 session. Wayland is now the default session on Ubuntu/Fedora/etc.

### Actual behaviour

There's no option "Use system window frame" in settings. This is how it looks out of the box:

![Screenshot from 2022-10-29 21-17-31](https://user-images.githubusercontent.com/3014095/198849199-e8cbb3ed-3925-4308-b978-780db3698829.png)

This is how it looks in case of forcing `QT_QPA_PLATFORM=wayland`

![Screenshot from 2022-10-29 21-20-26](https://user-images.githubusercontent.com/3014095/198849228-c2b41882-096d-446d-b6d4-46cf8bd7c407.png)

Notice the cursor become even worse. Also there're some errors in terminal.

I've tried a Flatpak version as well. Mesa 22.2.1, Intel HD 630 (Kaby Lake GT2).

### Operating system

Ubuntu 22.10

### Version of Telegram Desktop

4.2.4

### Installation source

Snap

### Logs

```shell
(telegram-desktop:23292): Gtk-WARNING **: 21:19:56.977: Locale not supported by C library.
	Using the fallback 'C' locale.
[E] pw.loop [loop.c:86 pw_loop_new()] 0x7f486d252850: can't make support.system handle: No such file or directory
[ALSOFT] (EE) Failed to create PipeWire event thread loop (errno: 2)
qt.qpa.wayland: EGL not available
QOpenGLWidget is not supported on this platform.
QOpenGLWidget: Failed to create context
QRhiGles2: Failed to create temporary context
QRhiGles2: Failed to create context
Failed to create QRhi for QBackingStoreRhiSupport
qt.svg: Error while inflating gzip file: SVG format check failed
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.svg: Error while inflating gzip file: SVG format check failed
QObject::~QObject: Timers cannot be stopped from another thread
```

**Comment by ilya-fedin** [comment]
Those are GNOME bugs
https://gitlab.gnome.org/GNOME/mutter/-/issues/217
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5894

**Comment by the-spyke** [comment]
If the App doesn't work well on Wayland it may be beneficial to run under XWayland or have an option for that. Especially when its behavior is different after setting `QT_QPA_PLATFORM=wayland`.

**Comment by ilya-fedin** [comment]
I would say we work well, the problem is GNOME doesn't conform to the standards developed by other players of the Linux desktop (Qt, KDE).

**Comment by the-spyke** [comment]
I've got this variable not from my head. I've googled Telegram on Wayland and found that Wayland is turned off on GNOME. To bypass this you need a variable (which didn't work earlier this year https://github.com/telegramdesktop/tdesktop/issues/23877). My regular user understanding is that Wayland is still turned off by default, as this variable is not defined inside the snap. But it doesn't look like an XWayland app, because in that case there will be a proper window frame and cursors. So, the situation is a little bit confusing.

**Comment by ilya-fedin** [comment]
Qt removed GNOME from Wayland blacklist in version 6.3

**Comment by ilya-fedin** [comment]
> Especially when its behavior is different after setting `QT_QPA_PLATFORM=wayland`.

I believe it's altered due to you tried to run the applications from terminal rather from the UI, not due to the variable. Given that you have multiple versions of Telegram installed, it's likely the version you ran from terminal is different than from the UI.

**Comment by the-spyke** [comment]
I have a single version installed, but you are almost right. Cursor theme changes not because of a terminal, but because of how I run the snap to pass a variable (just rechecked this). Anyway, I found a workaround to force XWayland:

```
$ sudo snap disconnect telegram-desktop:wayland
```

Thanks.

**Comment by ilya-fedin** [comment]
If you want to force Xwayland, there's `QT_QPA_PLATFORM=xcb`

**Comment by the-spyke** [comment]
Variables are difficult to pass into snaps. Regular `name=value command` doesn't work.

**Comment by ilya-fedin** [comment]
Note that Qt 6.x is very bugged with xcb backend, e.g. #17254 and #10348 (random entering into window move mode). Issues like big cursor are just cosmetic at least rather than the X11 ones.

**Comment by ilya-fedin** [comment]
Well, #10348 is since from Qt 5.x in fact (but is X11-specific).

**Comment by the-spyke** [comment]
I've checked and it works fine: snapping to the side, miximize/minimize.

**Comment by ilya-fedin** [comment]
> I've checked and it works fine: snapping to the side, miximize/minimize.

It's random :(. Just like the scrolling bug. The scrolling bug is even hardware dependent.

> Maybe because I'm not forcing any backend.

No, it doesn't make a difference.

**Comment by the-spyke** [comment]
Good to know, thank you.
