### ISSUE TITLE
segmentation fault - Manjaro Gnome Wayland 42.4

### ISSUE THREAD

**Issue by Kitsab77** [telegramdesktop/tdesktop#25234]
Hello since a few weeks I'm experiencing segmentation faults when I try to launch telegram-desktop.
zsh: segmentation fault (core dumped)  telegram-desktop

journalctl -xe:

``
Okt 30 23:00:37 Mate16 systemd[1]: systemd-coredump@8-25205-0.service: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://forum.manjaro.org/c/support
░░ 
░░ The unit systemd-coredump@8-25205-0.service has successfully entered the 'dead' state.
Okt 30 23:00:37 Mate16 kernel: audit: type=1131 audit(1667167237.299:350): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-coredump@8-25205-0 comm="systemd" >
Okt 30 23:00:37 Mate16 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-coredump@8-25205-0 comm="systemd" exe="/usr/lib/systemd/systemd>
Okt 30 23:00:37 Mate16 audit: BPF prog-id=68 op=UNLOAD
Okt 30 23:00:37 Mate16 audit: BPF prog-id=67 op=UNLOAD
Okt 30 23:00:37 Mate16 audit: BPF prog-id=66 op=UNLOAD
Okt 30 23:00:37 Mate16 kernel: audit: type=1334 audit(1667167237.407:351): prog-id=68 op=UNLOAD
Okt 30 23:00:37 Mate16 kernel: audit: type=1334 audit(1667167237.407:352): prog-id=67 op=UNLOAD
Okt 30 23:00:37 Mate16 kernel: audit: type=1334 audit(1667167237.407:353): prog-id=66 op=UNLOAD
Okt 30 23:00:59 Mate16 wpa_supplicant[1300]: wlp1s0: CTRL-EVENT-SIGNAL-CHANGE above=0 signal=-70 noise=9999 txrate=260000
Okt 30 23:01:13 Mate16 wpa_supplicant[1300]: wlp1s0: CTRL-EVENT-SIGNAL-CHANGE above=1 signal=-70 noise=9999 txrate=260000
``

**Comment by ilya-fedin** [comment]
Please install the version from desktop.telegram.org and send a crash report. Post back the report tag here.

**Comment by Kitsab77** [comment]
Hello,
the version from telegram.org is working. I thought this is the version which is distributed by Arch linux AUR.
Sorry for raising an issue for wrong software.
Best regards
Kitsab
