### ISSUE TITLE
[Flatpak] pip window unresizable and also minmize when losing focus so it's no longer stays on top of the other windows

### ISSUE THREAD

**Issue by jkmpariab** [telegramdesktop/tdesktop#25230]
### Steps to reproduce

1. Open a video
2. Click on picture in picture mode icon
3. Now picture in picture window is no longer stays on top of other windows when losing focus

Also i should mention that the pip window is no longer resizable

### Expected behaviour

PIP stays on top when losing control and resizable

### Actual behaviour

PIP minimizes and unresizable

### Operating system

Ubuntu 22.04 

### Version of Telegram Desktop

4.2.4

### Installation source

Flatpak

### Logs

```shell
Have no idea how to enable or capture logs on telegram desktop.
```

**Comment by ilya-fedin** [comment]
Can you provide a screen record? It's barely understandable with your text description.

**Comment by jkmpariab** [comment]
I have problem to recording my screen tried bunch of screen recorders including the official program.
So i think that could be related to my telegram desktop issue too. My bad...
If you could not reproduce my reported issue then its a problem with my setup so feel free to close the thread.
Good luck!

**Comment by ilya-fedin** [comment]
I can't reproduce, but I use KDE Plasma. I'm not going to install Ubuntu to check the issue, that's why screen record is required.

**Comment by Aokromes** [comment]
> I have problem to recording my screen tried bunch of screen recorders including the official program. So i think that could be related to my telegram desktop issue too. My bad... If you could not reproduce my reported issue then its a problem with my setup so feel free to close the thread. Good luck!

you can record with mobile phone :)

**Comment by ilya-fedin** [comment]
I suggest to check whether all of: `pipewire`, `xdg-desktop-portal` and `xdg-desktop-portal-gnome` are installed, their absence is a typical reason of screen recording is not working

**Comment by jkmpariab** [comment]
> > I have problem to recording my screen tried bunch of screen recorders including the official program. So i think that could be related to my telegram desktop issue too. My bad... If you could not reproduce my reported issue then its a problem with my setup so feel free to close the thread. Good luck!
> 
> you can record with mobile phone :)

I can't. github blame that the video is too big but i can't make it lower than this sorry.
BTW lets try to explain more specificly sorry for my bad english:
Q: Does pip window suppose to be always on top of the other windows? cos i used to be such that and maybe the recent updates changed that?
Another issue that is faced is the pip windows is not resizable!

* Always on top window is a window that always stays on top of other windows even when loses focus.

**Comment by ilya-fedin** [comment]
> I can't. github blame that the video is too big but i can't make it lower than this sorry.

Compress it in the archive? Upload to Google Drive?

> Does pip window suppose to be always on top of the other windows?

Yes unless you're using Wayland (it doesn't allow to set always on top hint)

> cos it's used to be such that and maybe the recent updates changed that?

Apparently you were switched from X11 to Wayland during system updates?

> Another issue that i faced is the pip windows is not resizable!

Well I don't quite understand how is it possible, that's why I ask you for a video, may be you resize it in some other way than I am. There's quite a lot of ways to resize the window in Linux I believe...

**Comment by Aokromes** [comment]
> > > I have problem to recording my screen tried bunch of screen recorders including the official program. So i think that could be related to my telegram desktop issue too. My bad... If you could not reproduce my reported issue then its a problem with my setup so feel free to close the thread. Good luck!
> > 
> > 
> > you can record with mobile phone :)
> 
> I can't. github blame that the video is too big but i can't make it lower than this sorry. BTW lets try to explain more specificly sorry for my bad english: Q: Does pip window suppose to be always on top of the other windows? cos it's used to be such that and maybe the recent updates changed that? Another issue that i faced is the pip windows is not resizable!
> 
> * Always on top window is a window that always stays on top of other windows even when loses focus.

you can upload the video to telegram :)

**Comment by ilya-fedin** [comment]
https://t.me/TelegramDesktopTalk

**Comment by jkmpariab** [comment]
> > I can't. github blame that the video is too big but i can't make it lower than this sorry.
> 
> Compress it in the archive? Upload to Google Drive?
> 
> > Does pip window suppose to be always on top of the other windows?
> 
> Yes unless you're using Wayland (it doesn't allow to set always on top hint)
> 
> > cos it's used to be such that and maybe the recent updates changed that?
> 
> Apparently you were switched from X11 to Wayland during system updates?
> 
> > Another issue that i faced is the pip windows is not resizable!
> 
> Well I don't quite understand how is it possible, that's why I ask you for a video, may be you resize it in some other way than I am. There's quite a lot of ways to resize the window in Linux I believe...

Yeah you were right i switched from x11 to wayland for a while but never noticed the impact on telegram desktop until now.
BTW i'm uploading my low-res-still-github-blame-too-big showcase video to the telegram group (uploading speed is so slow sorry)
