### ISSUE TITLE
Telegram always asks for a code after restart.

### ISSUE THREAD

**Issue by Vizakenjack** [telegramdesktop/tdesktop#2523]
### Steps to reproduce
1. I have installed telegram from the app store, name is "telegram", not the "desktop". I have tried the 'telegram desktop' and there is no such problem.
2. I run it, it asks for a phone number and code.
3. If I restart it, it asks for that again.

I have tried to reinstall it, but the problem still remains :(

### Expected behaviour
It should not ask for a code if I restart the app

### Configuration
Operating system: OS X 10.11.6 (El Capitan)

Version of Telegram Desktop:  2.27.51100

**Comment by auchri** [comment]
That's a different app: https://github.com/overtake/telegram
