### ISSUE TITLE
Can't unpin message with button in channels

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25235]
### Steps to reproduce

1. Go to https://t.me/dvachannel for example
2. You will see pinned message with button https://t.me/dvachannel/95794
3. Try to unpin it
4. You can't
5. But you can do it on iOS for example (long tap on pin)
![image](https://user-images.githubusercontent.com/39812401/199001644-87cd4bee-3e1c-4412-9eb2-67bb5f607160.png)
![image](https://user-images.githubusercontent.com/39812401/199001682-8c2a4a58-1137-4422-97e2-e5fd335de6b1.png)

### Operating system

Windows 10

### Version of Telegram Desktop

4.2.4

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
By unpin you mean hide locally? It would be possible from the context menu in the next release.

**Comment by Neurotoxin001** [comment]
> By unpin you mean hide locally? 

Yes

**Comment by Neurotoxin001** [comment]
Fixed, now I can right click on pinned message and there is button "Pinned messages" with "Don't show pinned messages"
