### ISSUE TITLE
Unable to right click on the telegram icon in the lower right corner of Windows 11 to exit telegram.

### ISSUE THREAD

**Issue by rikonaka** [telegramdesktop/tdesktop#25246]
### Steps to reproduce

1. Just download and install the telegram desktop.
2. Open it you will find you can not quit it now.

### Expected behaviour

Shows a small menu and then has the option to `exit`.

### Actual behaviour

Nothing show.

### Operating system

Windows 11 Pro 22H2 22623.875 Windows Feature Experience Pack 1000.22636.1000.0

### Version of Telegram Desktop

4.2.4

### Installation source

Microsoft Store

**Comment by jungalho** [comment]
I'm on Windows 11 Pro 22H2 22621.674 and it works normally

![image](https://user-images.githubusercontent.com/58450254/200124251-75334f2f-a024-4827-8998-d7a5f6f632f8.png)

**Comment by rikonaka** [comment]
@jungalho Thanks for your reply, the problem is solved after updating the latest windows, I should have recorded a screen before.
