### ISSUE TITLE
[BUG] When using mobile to create a group, @name search doesn't work.

### ISSUE THREAD

**Issue by navyguyg** [telegramdesktop/tdesktop#2524]
### Steps to reproduce
1. On android mobile app, when creating a new group using the username search  it doesn't work.
2. On the desktop client the search option is working.
3. 

### Expected behaviour
When creating a new group on mobile, using the @name search should bring up that person to be added to group chat.

### Actual behaviour
While using mobile, using the search brings back no results.

### Configuration
**Operating system:**
Android 6.0 
**Version of Telegram Desktop:**
Telegram for Android v3.13.1 (852) arm-v7a
### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by diazbastian** [comment]
@navyguyg dude, this github is only for Telegram Desktop app, not Android or iOS app.
