### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#25245]
### Is your feature request related to a problem?

Yes

### Describe the solution you'd like

Let me upload an image. On desktop, when you hover the mouse over the emoticon icon / gif icon, it immediately shows the give window. This distracts and loose focus of one trying to write on the chat or clicking on something inside the chat because the gif window just popped open suddenly. The idea is for me to either write the @gif or click on the gif icon to actually get to it, not just hover it because it gets in the way of chatting and working almost 80% of the time in a single day.

![image](https://user-images.githubusercontent.com/29236/199630690-8d58f646-0a6d-4d51-82ea-2c546504086c.png)

### Describe alternatives you've considered

Only show the GIF window if I click on the icon of it, it give the desktop version an option to disable showing it when hovering on top of it.

**Comment by ilya-fedin** [comment]
You can enable such beahvior in experimental settings

**Comment by luisalvarado** [comment]
@Aokromes @ilya-fedin I could kiss you guys. This is AMAZING!. I can work MUCH MORE efficiently now. Thank you so much.
