### ISSUE TITLE
Right Clicking on Scheduled Message page crashes app instantly

### ISSUE THREAD

**Issue by marcus-ong-qy** [telegramdesktop/tdesktop#25243]
### Steps to reproduce

1. Go to a chat or group
2. Create a Scheduled Message, which would redirect you to the 'Scheduled Messages' page for that chat/group
3. When you right click on the empty space (background) within the page, the app crashes immediately

### Expected behaviour

The app should not crash

### Actual behaviour

The app crashed

### Operating system

Windows 11 Home 10.0.22000 Build 22000

### Version of Telegram Desktop

4.2.4 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by john-preston** [comment]
This should be fixed in the upcoming update.
