### ISSUE TITLE
[Feature Request] Changing audio playback speed like in video

### ISSUE THREAD

**Issue by oneumyvakin** [telegramdesktop/tdesktop#25258]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I'd like to increase speed playback of audio files like for video.  

### Describe alternatives you've considered

Not sure.

### Additional context

Sometimes I'm listening podcasts in mp3 files and can't increase playback speed.

**Comment by Aokromes** [comment]
https://i.imgur.com/OY8IFQD.png
