### ISSUE TITLE
Telegram Dekstop Network Unreachable

### ISSUE THREAD

**Issue by axd** [telegramdesktop/tdesktop#2525]
I was on Telegram when suddenly it didn't load any conversation it just say: "Loading..." I closed and open it again and nothing... It seems that doesn't load anything of my session.

### Expected behaviour
Load conversations

### Actual behaviour
It appears "Loading..." message.

### Configuration
**Operating system:** Xubuntu 16.04

**Version of Telegram Desktop:** 0.10.11

### Logs
`[2016.10.13 11:18:36] App Info: reading map...`
`[2016.10.13 11:18:36] App Info: reading encrypted map...`
`[2016.10.13 11:18:36] App Info: could not read encrypted user settings...`
`[2016.10.13 11:18:36] App Info: writing encrypted user settings...`
`[2016.10.13 11:18:36] App Info: reading encrypted mtp data...`
`[2016.10.13 11:18:36] Map read time: 321`
`[2016.10.13 11:18:38] Not using Unity Launcher count.`
`[2016.10.13 11:18:38] TCP Error: network - Network unreachable`
`[2016.10.13 11:18:39] TCP Error: network - Network unreachable`
`[2016.10.13 11:18:39] HTTP Error: network error 99 - Network unreachable`

I've actually deleted all my config folder and now I'm stuck on activating my phone number, it never send the SMS.

**Comment by peitek** [comment]
Might be related to this: https://twitter.com/telegram/status/786620673200455680

**Comment by axd** [comment]
@peitek Exactly. I just saw that. Hahaha what a shame. Regards.
