### ISSUE TITLE
[Question] Innactif Support team? 

### ISSUE THREAD

**Issue by Someone3731** [telegramdesktop/tdesktop#25251]
Hello,

I would like to know if the following teams are still active : TSF, abuse, Telegram Auditions and moderator team (@username_bot).

I have contact each team for more than a month ago and several times but I never had any answer.
I know I'm not the only one in this situation and I think they are understaffed but why are they not doing anything? A lot of people are waiting for Telegram Auditions to answer and be able to help.

Note: I know this is the place but I'm desperate because they don't answer anywere.

Thanks in advance to people who will give me more informations about the situation.

**Comment by Aokromes** [comment]
this is a telegram desktop bug tracker, nothing posted here can help you on your issue.

**Comment by Someone3731** [comment]
Re-open

**Comment by Someone3731** [comment]
Could you re-open it please? It's important to me

**Comment by Aokromes** [comment]
i told you this is telegram desktop bug tracker, not telegram support reach place.

**Comment by Someone3731** [comment]
I told you there no way to contact Telegram and that it's not normal

**Comment by john-preston** [comment]
@Someone3731 But here you didn't find such way. No need to keep this issue open because it will just "be" in the list of issues and nobody will ever write anything meaningful here. You can file it to https://bugs.telegram.org, it will have more sense anyway.

**Comment by Someone3731** [comment]
I think it's will be ignored but I'Il give it a try

Le ven. 4 nov. 2022 à 16:33, John Preston ***@***.***> a
écrit :

**Comment by Someone3731** [comment]
My cards get deleted... Why nobody do something about this issue?

Le ven. 4 nov. 2022 à 16:40, Vincent Belgran ***@***.***> a
écrit :

**Comment by Aokromes** [comment]
again stop posting here, you don't go to get help here.

**Comment by Someone3731** [comment]
So where?
