### ISSUE TITLE
Crash when window is too narrow

### ISSUE THREAD

**Issue by lucasew** [telegramdesktop/tdesktop#25252]
### Steps to reproduce

1. Open Telegram 4.2.4  on Linux
2. Narrow the window. In my case 1/4 the width of a 1366x768 screen triggers the bug
3. Open any chat that has something, like a video
4. `/opt/rh/devtoolset-10/root/usr/include/c++/10/bits/stl_algo.h:3677: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = int]: Assertion '!(__hi < __lo)' failed.`

### Expected behaviour

Not crashing

### Actual behaviour

```
/opt/rh/devtoolset-10/root/usr/include/c++/10/bits/stl_algo.h:3677: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = int]: Assertion '!(__hi < __lo)' failed.
```

Tested with both the _nixpkgs_ package and the static binary

The _nixpkgs_ one gives a slightly different error

```
/nix/store/acbklvmaxi32lj3f7k1m1y00017f89ix-gcc-11.3.0/include/c++/11.3.0/bits/stl_algo.h:3658: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = int]: Assertion '!(__hi < __lo)' failed.
Aborted (imagem do núcleo gravada)
```

### Operating system

NixOS

### Version of Telegram Desktop

4.2.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Enable installation of beta versions in advanced settings to enable the crash reporter and send the crash report. Report back the report tag from crash reporter here.

**Comment by lucasew** [comment]
Your Report Tag: 16c637ef-7906-4067-c11161aa-532a0398 
Your User Tag: df715e6f8dacf8d2

**Comment by ilya-fedin** [comment]
The trace seem to be weird :(

**Comment by ilya-fedin** [comment]
Are you sure you're using exactly the binary from the website? Some distros provide it in a form of package and they can patch the binary what would make them incompatible with the debug symbols.

**Comment by lucasew** [comment]
NixOS is not a FHS compatible distro, so I packaged using a FHS environment thing from nixpkgs.

The binary is running unmodified, and I can reproduce the same problem from the _nixpkgs_ packaged binary.

Here is the definition: https://github.com/nixosbrasil/nixpkgs-brasil/blob/master/pacotes/comunicacao/telegram/default.nix

**Comment by lucasew** [comment]
I think I found the problem. By default mkDerivation strips every binary it finds, or at least the ones inside $out/bin.

That automatic thing cleared the debug symbols, so I enabled `dontStrip`.

```
Your Report Tag: ed44384e-f088-40d6-967e34b2-36e01755 
Your User Tag: df715e6f8dacf8d2
```

**Comment by ilya-fedin** [comment]
the debug symbols aren't in the binary, but on the developer's machine. If the binary is changed in any way (i.e. hashsum no longer equals), applying developer's debug symbols to your crash dumps will give weird results that won't give a light where the crash happenned.

**Comment by ilya-fedin** [comment]
This time minidump-stackwalk can't find debug symbols for your dump at all. Moreover, it claims your binary starts with a dot what is a problem when opening your dump on macOS. Please, run unmodified, unrenamed binary. If you can't do that, please report your issue downstream instead.

**Comment by john-preston** [comment]
@lucasew  UPD I've managed to apply the symbols, I hope I'll be able to fix that.

I'm afraid your "too narrow" may be less than the smallest supported width of the window? Can you provide a screenshot?

**Comment by lucasew** [comment]
![Captura de tela_2022-11-07_10-54-10](https://user-images.githubusercontent.com/15693688/200327441-e83b0b18-5ec9-4f2c-8e44-27b392c9b03a.png)

If I open that chat Telegram will freeze then crash

**Comment by lucasew** [comment]
Maybe instead of crashing, you can do like NCDU does when the terminal window is too much narrow

It shows a warning, and when the window gets wider again it renders normally

![Captura de tela_2022-11-07_12-02-23](https://user-images.githubusercontent.com/15693688/200342815-943f23e2-654b-4df9-a9e3-6c2c1b4e4ba8.png)

**Comment by ilya-fedin** [comment]
If I understand this right, this would mean destroying&recreating all the real widgets in the window (in order for the width calculation code not to be executed) on the fly what would be really non-trivial to implement (@john-preston please correct me if I'm wrong) and given that it is a lot of effort for a little gain, no one would do that work (unless you're ready to implement that on your own). The only realistic way then is for you to report to your WM that it doesn't conforms to the hints set by tdesktop.

**Comment by ilya-fedin** [comment]
Just to be clear: it's not a problem for 99.9% of the userbase as Windows, macOS and major Linux environments conform to the hints (the Linux itself is around 2% of the userbase and I can confirm that it's not a problem for environments used by 97.77% of the Linux userbase at least, according to the statistic).
