### ISSUE TITLE
Switching the driver while turning the microphone on and off.

### ISSUE THREAD

**Issue by AWSinfrastructure** [telegramdesktop/tdesktop#25250]
### Steps to reproduce

1. connect AirPods 2 to MacBook
2. Open TG and do it call
3. Turn on button microphone in interface TG
4. When the second speaker speaks while you have the microphone turned on, you turn off the microphone

### Expected behaviour

The drivers do not switch when the microphone is turned on and off and the sound does not disappear for 2 seconds

### Actual behaviour

When the speaker speaks and you turn off the microphone, the drivers on the Bluetooth headphones change and the sound disappears for two seconds and you often don't know what the speaker said

### Operating system

macOS 13.0 (22A380)

### Version of Telegram Desktop

9.0.1.237033 Stable

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
