### ISSUE TITLE
Linux - Cannot scroll w/ mouse wheel after sleep

### ISSUE THREAD

**Issue by fd-sturniolo** [telegramdesktop/tdesktop#25256]
### Steps to reproduce

1. Open Telegram
2. Suspend & turn back on
3. Now you cannot scroll with the mouse wheel.

This has also been reported in #3859 & #3866 but nothing seems to have come of that. May be a Qt bug, apparently?

### Expected behaviour

Scrolling should work.

### Actual behaviour

Cannot scroll!

### Operating system

Ubuntu 20.04

### Version of Telegram Desktop

4.2.4

### Installation source

Snap

**Comment by francisco-serfe** [comment]
Ended up finding #17254, looks like it's definitely Qt on X11 related. I'll just close.
