### ISSUE TITLE
Reinstalled Telegram to tower computer w/ windows 7, have no code to get back on, no wifi in house only cable net

### ISSUE THREAD

**Issue by sharon618** [telegramdesktop/tdesktop#25253]
### Steps to reproduce

Reinstalled Telegram Desktop to tower computer w/ windows 7, while program still on. Thinking it would fix my pop up problem, i had when i was on Telegram. 

### Expected behaviour

Reinstalled Telegram Desktop and thought it would fix the pop up problem.

### Actual behaviour

Telegram Desktop reinstalled, went to use it. I could not get logged in, due to needing a code. Had no way to retrieve the code, Plus didn't know i was going to need it, by just reinstalling it. I was Wrong!

### Operating system

Windows 7

### Version of Telegram Desktop

4.2.4

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
you need to have telegram installed on a mobile device to get code.
