### ISSUE TITLE
Calls don't go through socks5 proxy with UDP support

### ISSUE THREAD

**Issue by jammy551** [telegramdesktop/tdesktop#25254]
### Steps to reproduce

1. Setup a socks5 proxy with UDP support 
2. Set Telegram to use the socks5 proxy and check "Use Proxy for Calls"
3. Set Peer-to-Peer to "Nobody" in Settings -> Privacy and Security -> Calls 
4. Make a call

### Expected behaviour

The call should connect and work through the socks5 proxy and [Telegram relay servers](https://core.telegram.org/api/end-to-end/voice-calls) 

### Actual behaviour

The call stuck in "Exchanging encryption keys".

### Operating system

Ubuntu 22.10

### Version of Telegram Desktop

4.2.4

### Installation source

Snap

### Notes

I also tested this on Telegram android and Telegram iOS and no calls went through the socks5 proxy running in local network when using this native proxy setting in Telegram. Chats work fine.

This is while if I use a proxifier app such as Trojan on Android, or Shadowrocket on iOS and set it to use the same socks5 proxy, call works fine and I see UDP connection reports in the log of the socks5 server. Therefore there is nothing wrong with the socks5 server and it is merely a problem with socks5 proxy settings in Telegram.

**Comment by ilya-fedin** [comment]
#23916
