### ISSUE TITLE
Telegram doesn't respect title bar accent color settings on Windows 11

### ISSUE THREAD

**Issue by bviktor** [telegramdesktop/tdesktop#25263]
### Steps to reproduce

1. Install Windows 11
2. Set Windows to "Show accent color on title bars and windows borders" like so:

![image](https://user-images.githubusercontent.com/5798552/200122053-44c7f91f-809b-4c7c-94c5-2cd8edc43a06.png)

3. Install Telegram Desktop
4. Set Telegram to "Use system window frame" under Settings / Advanced:

![image](https://user-images.githubusercontent.com/5798552/200122104-23e35ecc-032d-42cb-a917-ab8f69f8a4f9.png)

### Expected behaviour

I expect Telegram to respect Windows' settings for title bar colors, like on Windows 10, where it looks like this when active:

![image](https://user-images.githubusercontent.com/5798552/200122372-755fccea-c73c-4629-877b-7cdb034531af.png)

And when inactive:

![image](https://user-images.githubusercontent.com/5798552/200122464-7b14b7dd-2eee-4bae-831b-647ee4966ecc.png)

---

This is very important because it's MUCH easier to tell if Telegram is the active window or not. Especially on 21:9 displays, where 99% of the time I have 2 windows on display, one swiped to the left, and one swiped to the right. And half the time I end up typing in the WRONG window, because for example, Firefox also suffers from the same bug on Windows 11.

Here's another example of a program that works as expected, Double Commander active:

![image](https://user-images.githubusercontent.com/5798552/200122335-9029f9de-50a2-4a0a-b214-5ecc5e9ed6ca.png)

And inactive:

![image](https://user-images.githubusercontent.com/5798552/200122348-5b550753-abfe-4e8a-8604-41d2de64da56.png)

### Actual behaviour

On WIndows 11, Telegram displays the same black color corresponding to dark theme, without the colors. Both with:

![image](https://user-images.githubusercontent.com/5798552/200122207-90cd468e-284b-4bfa-8e0e-449323cbd84e.png)

or without the system window frame:

![image](https://user-images.githubusercontent.com/5798552/200122213-6b533415-1d10-4c38-b4eb-67c56f144793.png)

### Operating system

Windows 11

### Version of Telegram Desktop

4.2.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Sorry, it's not a bug, this is done on a reason

**Comment by bviktor** [comment]
But it works on Windows 10. Why would you break usability on certain OSes and not others?

**Comment by ilya-fedin** [comment]
tdesktop uses APIs to integrate non-client parts of the window whenever they're available (WIndows 10 doens't provide them unfortunately). There even were code to remove the title and icon in system window frame, maybe it will land some day.

**Comment by bviktor** [comment]
Are you sure we're on the same page? I'm talking about the "Use system window frame" option. Without it, yes, it's up to Telegram, and that's consistent across Windows 10 but 11.

But why do you override system title bar behavior when this option is EXACTLY to avoid that?

**Comment by ilya-fedin** [comment]
Well, this option is to switch between rendering by Telegram and rendering by the system. Titlebar is still drawn by your system, so it works as intended.

**Comment by john-preston** [comment]
@bviktor The option really was because the custom didn't work in some edge cases :( I thought about removing that option many times.

Regarding the difference in focused and non-focused window this is available in themes. It is even used (not visibly enough) in the default dark theme:

![image](https://user-images.githubusercontent.com/17900494/200123922-ee60d2f3-8dcf-4b21-a3c7-2a4cf23c01d3.png)

So you can easily make a custom theme from the default one that will have different title bar colors in active and inactive window state.

**Comment by bviktor** [comment]
Should I open a feature request to maybe revisit your decision to change title bar rendering behavior, and make Telegram behave consistent with itself on other Windows version, and other applications on Windows 11? Or will you close that too? It worked as intended on Windows 10, much like the rest of my applications on Windows 11. So it's a regression, even if you regressed it on purpose.

![image](https://user-images.githubusercontent.com/5798552/200123347-631458d7-6ec9-4496-bfd5-cf1355d10c51.png)

![image](https://user-images.githubusercontent.com/5798552/200123350-ab71e295-d126-4587-a823-e487bc79dd70.png)

![image](https://user-images.githubusercontent.com/5798552/200123358-fa2c920c-e053-4737-94f9-494483f30997.png)

![image](https://user-images.githubusercontent.com/5798552/200123363-08ff6231-6482-4551-b8fd-ad169a213fda.png)

![image](https://user-images.githubusercontent.com/5798552/200123376-1aca287e-3a11-4d42-bb9b-ffa58f9eb00e.png)

![image](https://user-images.githubusercontent.com/5798552/200123387-18acea31-d797-483c-8fb7-6148dee2c139.png)

![image](https://user-images.githubusercontent.com/5798552/200123811-b1526620-4439-4732-af2f-b5bc50c8435c.png)

![image](https://user-images.githubusercontent.com/5798552/200123817-7822598b-f7ca-4980-b433-0df03652d500.png)

But for Telegram it's broken on Windows 11. Broken "by design".

![image](https://user-images.githubusercontent.com/5798552/200123951-174e540d-7416-40a9-afc6-754f0b2e9f88.png)

![image](https://user-images.githubusercontent.com/5798552/200123958-1b047f52-9a62-44e8-b129-b2dc0df18f0e.png)

You may consider it a "feature" to override system settings to paint different colors on the active window, I don't. APIs or not, I still can't quite comprehend why you think it's useful to make it harder for users to tell if the window has focus or not. Now it looks pretty much the same with or without focus. Telegram clearly indicated focus on Windows 10, and now it doesn't. How is that an improvement? If other applications can work as intended on Windows 11, why can't Telegram?

**Comment by bviktor** [comment]
@john-preston thanks, how do I tell it to use Windows' accent color? Because it can change even dynamically, as the wallpaper changes. And my other apps do follow that setting automatically, without me hardcoding a color theme for them every time it changes.

Hate to be a whiner, but it really does seem like a bad decision to make Telegram work the way it does ATM. And only on Windows 11, I might add.

**Comment by ilya-fedin** [comment]
> thanks, how do I tell it to use Windows' accent color?

Contribute the code to integrate Windows' accent color with Telegram's theming engine (I don't think anyone else is interested in that, so if you don't plan to contribute, this is unlikely to be implemented).

**Comment by bviktor** [comment]
I'd like to stress once again, that this **worked** and **continues to work** on Windows 10, so I don't see what you need to "implement" on something that already exists.

**Comment by bviktor** [comment]
Come to think of it, it takes this much effort to "implement" it:

![image](https://user-images.githubusercontent.com/5798552/200124367-54f3f343-bf31-4638-8aed-6eedfa5124ed.png)

So anyone else reading this, I guess this is what we'll have to settle because of the "improvements" made on the Windows 11-specific rework.

**Comment by ilya-fedin** [comment]
As you can see, the system window frame option is unwanted in Telegram, like you that or not. So the only way to achieve what you want is to that in acceptable way (integrate with Telegram theming). Or create a fork.

**Comment by bviktor** [comment]
For your future design decisions, I suggest you to take accessibility / usability into account. Thanks.

**Comment by ilya-fedin** [comment]
@bviktor accessibility is a lost thing in tdesktop given that its codebase needs a complete rewrite to be compatible with screen readers :(
