### ISSUE TITLE
.webp parsing 

### ISSUE THREAD

**Issue by honey-sorry-i-ate-a-bus** [telegramdesktop/tdesktop#25264]
### Steps to reproduce

1. Get any .webp image file
2. Send this file using Telegram

### Expected behaviour

What should happen is parsing .webp files as pictures, unless SOMETHING ELSE is specified by a user. 

### Actual behaviour

All .webp files are considered stickers no matter what the end user wants them to be. 

### Operating system

Windows, Linux, Mac

### Version of Telegram Desktop

4.2.4 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#17410
