### ISSUE TITLE
Crash pic-in-pic when message is deleted

### ISSUE THREAD

**Issue by SpL1Ne** [telegramdesktop/tdesktop#25262]
### Steps to reproduce

1. Forward message with video from public to Saved Messages (I could reproduce with 7+ and 19+ minutes videos. Couldn't with 3-4 minutes).
2. Open video.
3. Click pic-in-pic view.
4. Delete message from Saved while video is playing.
5. Close (meaning minimize) telegram to notification area.
6. Try to expand video to default view with arrows button near close button at pic-in-pic window. (Sometimes you have to repeat again 'click pic-in-pic, close telegram and try to expand' actions)

### Expected behaviour

I guess like with 3-4 minutes video. Video expand to in default view and telegram open it windows from notification area.

### Actual behaviour

7. Telegram crashes.

### Operating system

Windows 10 21H1 19043.95

### Version of Telegram Desktop

4.2.4x64

### Installation source

Static binary from official website

### Logs

```shell
Your Report Tag: 2f0cb759-7849-4d78-991c-d2a72e843806
Your User Tag: 398a50efe4fc4b6a
```

**Comment by SpL1Ne** [comment]
Still reproducible 4.3x64. But with 9+ and 19+ minutes video. Couldn't reproduce with 7+ and 8+ minutes videos.

Your Report Tag: e501017e-b2f3-4157-a736-e2429ce2428c
Your User Tag: 398a50efe4fc4b6a

**Comment by Neurotoxin001** [comment]
4.4.1 still have it

`[2022.12.07 16:41:31] Assertion Failed! "ptr_ != nullptr" pointers:96`
Your Report Tag: a6bb9565-dc19-4d2b-8c79-1a93545c391f
Your Report Tag: 27c73a08-092b-4d1f-a145-b8e74e21b5ea
