### ISSUE TITLE
[Feature Request] Configure message corners

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25265]
### Is your feature request related to a problem?

Yes. I don't want to see too circular message corners:
![image](https://user-images.githubusercontent.com/39812401/200131363-10ca9f63-55c0-4146-8ff7-8d2f64ace91c.png)

### Describe the solution you'd like

Make option to configure message corners like it's done on iOS:
![image](https://user-images.githubusercontent.com/39812401/200131330-abe40393-519d-45ad-a525-ff8b588c5f80.png)
![image](https://user-images.githubusercontent.com/39812401/200131336-c37792b3-8266-41f5-a7b9-f94b29246393.png)
![image](https://user-images.githubusercontent.com/39812401/200131344-e9788656-ba7c-4fff-aecd-8455ec9cad76.png)

### Describe alternatives you've considered

No

**Comment by ShadowJonathan** [comment]
The only reason I used tdesktop over the swift version is so I do not have rounded corners, Telegram iOS also has this feature, why was this removed?

Also, if someone has a bugs.telegram.com issue for this, please link it.

**Comment by ShadowJonathan** [comment]
This was added in https://github.com/telegramdesktop/tdesktop/commit/ba2f92906bb273f57c409b4b886fcf74dbd7bb99, it seems, as part of the topics change.

@john-preston people liked this feature, at least provide a slider like in iOS?

**Comment by natewind** [comment]
Yes please! The old border-radius was perfect.

**Comment by namikiri** [comment]
I support this issue/request as well. 

Although modern™ design guidelines©®™ tell you to make the corners as more round as you can, I still use Windows 10 and it has square windows and UI elements. I'd be happy to have the bubble corner radiuses configurable exactly as in Android app with an option to set it to 0.

**Comment by hatkidchan** [comment]
Also support that issue. I hate round borders everywhere. Our screens are square, and so should be everything else. If you want round corners — sure, make that toggle-able. 

Also, it's not a minor improvement, but a huge downgrade. 
![image](https://user-images.githubusercontent.com/35804000/200299574-5d5c3a49-4b50-4147-9a93-3ca3d751292c.png)

Would also be nice to not just have them "less round", but make them with sharp edges. My entire system has them and having ONE app with them just ruins everything.

**Comment by mironuk** [comment]
I've just updated Telegram and these too-rounded corners look ugly. I would like to have a setting like in Android Telegram, I would like to set corner radius to 5, for example.

**Comment by Pablete1234** [comment]
I've seen the update today and it's clearly a downgrade, side-by-side comparison, left is 4.2.4, right is 4.3.0:

![image](https://user-images.githubusercontent.com/11789291/200353500-fca35f2b-80db-4547-a272-6adab0423afb.png)

if the change is to stay, add a toggle to be able to maintain smaller corners (via either setting, or theme property), like the android app has.

**Comment by natewind** [comment]
Yep, on single-line messages it turns into the horrible `border-radius: 50%` trend.

**Comment by Pablete1234** [comment]
@Neurotoxin001 maybe add reverting to 4.2.4 in "Describe alternatives you've considered"

**Comment by defterade** [comment]
Telegram Desktop [already tried](https://github.com/telegramdesktop/tdesktop/issues/2235) rounded corners in 2016. It wasn't a good idea then and it isn't a good idea now.

**Comment by ShadowJonathan** [comment]
In that thread, @john-preston said:
> A lot of design decisions are just personal preference.

@john-preston While i can understand this statement in 2016, its 2022 now, the platform has millions of users now, this is a repo under the (relatively official) telegramdesktop organisation, and you're making decisions for all those users without first consulting or making it an alternative first.

And like back then, this wasnt a good idea then, and its still not now, make it optional.

**Comment by john-preston** [comment]
@ShadowJonathan The bubbles redesign is not my preference, but the official design mockups given to me. It was really hard implementing them 😅 So I wouldn't do that if I decided.

**Comment by ShadowJonathan** [comment]
Okay, that is fair enough, but could you please then provide a way to toggle between hard corners and round corners?

Like i said, one of the reasons i use tdesktop over the swift version is because the swift version has a bubble UI that doesnt look as trimmed as tdesktop is/was.

**Comment by john-preston** [comment]
@ShadowJonathan It is not planned right now, sorry. I'll ask, if it is required, but really I think this setting in mobile apps wasn't needed and shouldn't be anywhere. But they added it 🤔

**Comment by DragoonAethis** [comment]
> but really I think this setting in mobile apps wasn't needed

Well, at least 60 of us here absolutely do think it's necessary ^^' Would you accept a PR with legacy/round corners toggle in experimental settings?

**Comment by 23rd** [comment]
> Like i said, one of the reasons i use tdesktop over the swift version is because the swift version has a bubble UI that doesnt look as trimmed as tdesktop is/was.

Actually the swift version has an option to disable the bubble mode.

**Comment by john-preston** [comment]
@DragoonAethis Depends on the amount of code added (don't want to make complex logic for the bubbles much more complex), but generally yes, I'll accept it.

**Comment by SpL1Ne** [comment]
> @ShadowJonathan It is not planned right now, sorry. I'll ask, if it is required, but really I think this setting in mobile apps wasn't needed and shouldn't be anywhere. But they added it 🤔

Lol, what? So, to get this straight: official android app has this setting, as I understand, official iOS app also has this setting and you won't add it because you think this setting wasn't needed and should be removed? Nice.

**Comment by SuperZombi** [comment]
I agree with what has been said above. Add a setting for rounded corners!

**Comment by DragoonAethis** [comment]
![image](https://user-images.githubusercontent.com/1546665/200438435-eecba791-8618-4d93-a306-9cf8d0c444e5.png)

This is all pretty much driven from bubbleRadiusLarge and msgFileThumbRadiusLarge being a little toned down. Probably not perfect around bot keyboards and what not, but should be good enough for very little extra code on an experimental feature.

**Comment by SpL1Ne** [comment]
> > > @ShadowJonathan It is not planned right now, sorry. I'll ask, if it is required, but really I think this setting in mobile apps wasn't needed and shouldn't be anywhere. But they added it 🤔
> > 
> > 
> > Lol, what? So, to get this straight: official android app has this setting, as I understand, official iOS app also has this setting and you won't add it because you think this setting isn't needed and should be removed? Nice.
> 
> Bro don't make him angry, he can do whatever he wants, thanks him that not infected us with a wiper or ransomware yet

No, he can't do whatever he wants. This is not his pet-project or something like that. This is OFFICIAL, according to telegram.org, desktop application. And, as far as I can understand, usually every app in one ecosystem of some service has same functionality, features, etc. If he can't maintain application according to ecosystem than he should discuss it with his boss\manager instead of saying basically "I don't like it so I won't do it".

**Comment by DragoonAethis** [comment]
@john-preston Done, check it out: https://github.com/telegramdesktop/tdesktop/pull/25305

**Comment by ShadowJonathan** [comment]
> Actually the swift version has an option to disable the bubble mode.

Right, but the alternative is a "text" mode against one background, not a square-bubble version.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/9d59e42b522b9403994e5b704a4fe4004003c95d

**Comment by ShadowJonathan** [comment]
Nice! I assume this just needs an app update, and then all regular users can use this? Or does it need labs flags?

**Comment by RememberTheAir** [comment]
@ShadowJonathan it's a checkbox under settings -> advanced -> experimental settings. Everyone can use it, but it's a bit hidden

**Comment by mpeter50** [comment]
Why would this have to be in experimental settings? There is nothing experimental in it. This has worked for a long time perfectly fine, and this is also the _preferred_ option for a lot of users. If anything, the option to turn _on_ rounding should be in the experimental settings.

**Comment by DragoonAethis** [comment]
> Why would this have to be in experimental settings? There is nothing experimental in it.

Because there were a lot of changes introduced to support rounding in the first place and many styles were at least subtly modified to fit the new style - disabling rounding toggles just two styles to get back most of the old look, but wasn't comprehensively tested. If everything works fine, it can be moved to chat settings later.

**Comment by dancojocaru2000** [comment]
This is a big case of "if it ain't broke, don't fix it".

Stupidly rounded corners seem to be universally disliked by users. @DragoonAethis How were "a lot of changes introduced to support rounding" viewed as a reasonable thing to spend time on when nobody asked for it and a lot of people dislike it?

**Comment by DragoonAethis** [comment]
@dancojocaru2000 It was not my decision or preference, nor was it [the main dev's](https://github.com/telegramdesktop/tdesktop/issues/25265#issuecomment-1306133442). The redesign was a "product" decision, so the best thing you can do now is [upvote and comment here](https://bugs.telegram.org/c/21787) or let the official support know [here](https://twitter.com/telegram) to voice your disapproval. All I did was to add a toggle that lets you revert this, starting from the next version.

**Comment by dancojocaru2000** [comment]
Since it wasn't obvious to me until I read your reply just now, I apologise if the mention seemed accusatory. I didn't want to put blame on you, and my mention was just because I was quoting you.

Also, thank you for the answer. It is both the best answer I could receive in that it does show me how this was viewed as a reasonable thing to do (namely, because it was an imposed decision), and also because you showed me where I could voice my disapproval.

Thank you as well for adding the toggle. Unlike some of the main devs, I believe that a setting is always better than no setting when no setting means the worst possible option is forced onto everyone, so I appreciate that it was added so quickly.

As others have said, the toggle should be in chat settings to be uniform with the iOS (Appearance serves that page's role there) and Android apps. That being said, a hidden or misplaced setting is still better than no setting, and I do want to end on the positive note of thanking you for the effort.

**Comment by DragoonAethis** [comment]
No offense taken, no worries. As for the toggle, while I'd like to see it in chat settings as well, getting the rounded corners did require a lot of changes all across the codebase - [just look at this diff](https://github.com/telegramdesktop/tdesktop/compare/1401b19994e63994f923dac95c73313dd91292be..1e8dfb73153c8c54536fd5d1c45525babdf4f645), and that doesn't even include some later fixes. Switching just 2 styles from underneath all of that appears to mostly work, but I want to make sure the layout doesn't break first. It can be moved later if nothing explodes.
