### ISSUE TITLE
Feature Suggestion: Allow for 'auto-play' of concecutive audio recordings.

### ISSUE THREAD

**Issue by electricessence** [telegramdesktop/tdesktop#2526]
Currently in iOS this is the default behavior.  Where when playing audio, it will play through consecutive messages.

**Comment by T3rminat0r** [comment]
It's the default on all the mobile clients, I believe.

**Comment by beppe9000** [comment]
This should be offered as an option.

**Comment by Aokromes** [comment]
I think this is already implemented.

**Comment by beppe9000** [comment]
Now it is implemented on Windows too. Good job to whoever did that.
