### ISSUE TITLE
Which computer is suitable for developing tdesktop

### ISSUE THREAD

**Issue by ILG2021** [telegramdesktop/tdesktop#25260]
I use a desktop pc to develop tdesktop, everytime when I change a little code, it cost very long time to build and run, so it is impossible to develop. I don't know why the build is so slow. My computer is powered with a i7-10700 cpu, 16 cores. Is it still not enough?

**Comment by ilya-fedin** [comment]
Are you sure you have enough RAM and the build process doesn't go to swap?
Also, tdesktop uses PCH, so change to a header that is a part of PCH will lead to rebuild of all the target.

**Comment by ILG2021** [comment]
> Are you sure you have enough RAM and the build process doesn't go to swap? Also, tdesktop uses PCH, so change to a header that is a part of PCH will lead to rebuild of all the target.

I have 32G ram. Is it ok? I don't change header file. And it stucks at build one cpp file.

**Comment by ilya-fedin** [comment]
> I have 32G ram. Is it ok?

I'm not quite sure. Then more cores you, then more RAM you need. On Linux with gcc and 12 cores CPU I have around 30 GB RAM consumption.

> And it stucks at build one cpp file.

Which one and how long?

**Comment by ILG2021** [comment]
I have checked it. The compile is fast, obj file is generated soon. But the link will cost about minutes. How about you?

**Comment by 23rd** [comment]
Be sure you are building in Debug configuration.

**Comment by ILG2021** [comment]
> Be sure you are building in Debug configuration.

Of course.

**Comment by ilya-fedin** [comment]
> Which one and how long?

So?

**Comment by ILG2021** [comment]
like calls_group_invite_controller.cpp, when I comment a line, it will cost 7 minutes to build and run. But when I open the comment again, only a few seconds need to build. Sometimes is very fast, sometimes need few minutes. I don't know why.

**Comment by ilya-fedin** [comment]
do you actually check what consumes according to the build output or are you just guessing the file consumes all the build time?

**Comment by ILG2021** [comment]
When I disable parallel compile, it becomes fast.

**Comment by ILG2021** [comment]
I think it is the bug of Visual Studio 2022. The build will stuck and the cpu usage is 1%, build is not go on. I don't know what vs is doing.
![image](https://user-images.githubusercontent.com/93691919/200612027-130e3b5f-053c-48cd-bb38-90c8baca166d.png)
![image](https://user-images.githubusercontent.com/93691919/200612103-b6f29990-9abc-4adc-a719-bc5cf89fdbc9.png)

**Comment by ilya-fedin** [comment]
Try to set `-D DESKTOP_APP_NO_PDB=ON` to configure.bat

**Comment by ILG2021** [comment]
> Try to set `-D DESKTOP_APP_NO_PDB=ON` to configure.bat

Thanks for your reply. I don't think it is a good idea. I have open the log of MSBuild. I find the tiem is wasting on Tracker.exe.
