### ISSUE TITLE
Trying to change group visibility from private to public crashes

### ISSUE THREAD

**Issue by MrNaif2018** [telegramdesktop/tdesktop#25278]
### Steps to reproduce

1. Create a new group
2. Try to click to change visibility
3. The app crashes

### Expected behaviour

The app should not crash

### Actual behaviour

It crashes

### Operating system

Linux mint 21 XFCE

### Version of Telegram Desktop

4.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Provide crash report tag

**Comment by 23rd** [comment]
Can reproduce, so it will be fixed in the next release.

**Comment by MrNaif2018** [comment]
This seems to be fixed with the latest release, thanks!
