### ISSUE TITLE
Crash when trying to mark all messages as read

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25274]
### Steps to reproduce

1. CTRL+Shift+Alt+Right click on account in accounts list
2. Crash

Your Report Tag: abc387bc-f528-4638-b5b3-fc5d553435cd
Your Report Tag: c7ff0464-85fb-4a42-9d8f-d4f82b891f87
Your Report Tag: 3f7e8afc-b22d-4399-83b5-8ca000040bda
Your Report Tag: ae224cdb-b8b5-41e0-849c-aa27ef255cf1

You need to have at least 2 accounts.
### Operating system

Windows 10

### Version of Telegram Desktop

4.3

### Installation source

Static binary from official website

### Logs

```shell
[2022.11.06 11:30:17] Assertion Failed! "ptr_ != nullptr" pointers:83
```

**Comment by 23rd** [comment]
Can reproduce, so it will be fixed in the next release.

By the way, there is enough `Shift+Alt`.

**Comment by Neurotoxin001** [comment]
Fixed
