### ISSUE TITLE
Rounded messages. Why and where is the toggle to turn this ugly mode off?

### ISSUE THREAD

**Issue by RDKRACZ** [telegramdesktop/tdesktop#25277]
### Steps to reproduce

Update

### Expected behaviour

Good looking massages instead of this FB Messenger garbage

### Actual behaviour

Why do I have this design
![image](https://user-images.githubusercontent.com/43277609/200164527-094ac067-dbee-42ba-b394-7204ac54266c.png)

Instead of this:
![image](https://user-images.githubusercontent.com/43277609/200164544-777320f4-5ca9-4b17-b69f-486f860e5a65.png)

### Operating system

Fedora 36

### Version of Telegram Desktop

4.3

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25265

**Comment by RDKRACZ** [comment]
It's not mentioned in the changelog https://telegram.org/blog/topics-in-groups-collectible-usernames so it can be considered a bug (for example it was meant to be an experimental option).

**Comment by Neurotoxin001** [comment]
There is only for Android
![image](https://user-images.githubusercontent.com/39812401/200166222-09e250d5-f399-4b12-a237-d492dbb65d41.png)

But why then it's on TD.

**Comment by ShadowJonathan** [comment]
This was added in https://github.com/telegramdesktop/tdesktop/commit/ba2f92906bb273f57c409b4b886fcf74dbd7bb99, it seems, as part of the topics change.

@john-preston people liked this feature, at least provide a slider like in iOS?
