### ISSUE TITLE
Telegram Desktop version 4.3 suddenly freeze and exits automatically when a file is attached

### ISSUE THREAD

**Issue by Reno-Sifana** [telegramdesktop/tdesktop#25279]
### Steps to reproduce

1. Open Telegram Desktop version 4.3
2. Navigate to the message containing the file attachment
3. The "Choose Download Path" window will appear then select any

### Expected behaviour

Telegram Desktop suddenly freezes and exits by itself a few moments later

### Actual behaviour

Telegram Desktop is freezing

### Operating system

Linux Mint 21 "Vanessa" Cinnamon Edition

### Version of Telegram Desktop

4.3

### Installation source

Flatpak

**Comment by Reno-Sifana** [comment]
Even if I don't activate the "Select Download Path" option, it still behaves like that.
![Screenshot from 2022-11-06 17-53-02](https://user-images.githubusercontent.com/68702583/200167335-ce258297-3ff0-4dec-8965-450b80cceacc.png)

**Comment by ilya-fedin** [comment]
Oops

**Comment by musicislife08** [comment]
This same thing happens for me when clicking on one of my private groups and only for that one.  The moment I click on that one group the download path picker pops up and both choosing a path or canceling the window causes telegram to crash.
