### ISSUE TITLE
Comments in discussion always "not readed"

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25276]
### Steps to reproduce

1. Go to https://t.me/ru2ch_news/60170 for example
2. Open comments
3. Scroll them down to mark them as read
4. Go back to channel from comments
5. Open comments again
6. They still not readed

https://user-images.githubusercontent.com/39812401/200164478-d807ba75-3218-4004-945f-6ee9480bc68d.mp4

### Operating system

Windows 10

### Version of Telegram Desktop

4.3

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
There is also bug with comments. If I press on arrow to read all comments and go to new, it's going only to comments that writted in 12:33. To get new comments I must scroll all of them manually.

**Comment by john-preston** [comment]
I hope the second one had the same cause.
