### ISSUE TITLE
GIF images are not saved to disk

### ISSUE THREAD

**Issue by spam-receiver** [telegramdesktop/tdesktop#25272]
### Steps to reproduce

Click "Save GIF" in context menu of GIF image.

### Expected behaviour

The GIF file should be saved to disk (not as MP4 in "Save As..." !!!)

### Actual behaviour

Nothing happens.

### Operating system

Fedora Linux 36 x86_64
Windows 10 Pro x86_64

### Version of Telegram Desktop

4.2.4 x86_64
4.3.0 x86_64

### Installation source

RPM Fusion for Fedora 36 - Free - Updates
 Windows 64 bit: Installer

**Comment by john-preston** [comment]
@spam-receiver This save is a save in your fast gif sender (third tab on the emoji pop-up panel).

**Comment by spam-receiver** [comment]
> @spam-receiver This save is a save in your fast gif sender (third tab on the emoji pop-up panel).

I want to save GIF files to disk. I don't need GIF files as stickers.

**Comment by Neurotoxin001** [comment]
GIF files in Telegram it's MP4 without sound in most cases (but it can be actual .gif too).

**Comment by ilya-fedin** [comment]
> A new menu option: "Save GIF as GIF".

#1484
