### ISSUE TITLE
Topics groups avatar isn't rounded

### ISSUE THREAD

**Issue by firsturdiev** [telegramdesktop/tdesktop#25281]
### Steps to reproduce

1. Open Telegram Desktop
2. Just look to any topics group in the chats list

### Expected behaviour

The avatar should be rounded like other regular groups
![image](https://user-images.githubusercontent.com/83493139/200180643-1ab9eb69-4405-4f3f-93ec-ba5517162954.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/83493139/200180621-2849c2f8-b33e-4000-af31-72d6a6f5af84.png)

### Operating system

Windows

### Version of Telegram Desktop

4.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
This works like that on all platforms, it is intended. That way you see such groups right from the list and know what happens when you click on it.
