### ISSUE TITLE
Update Telegram

### ISSUE THREAD

**Issue by huezo** [telegramdesktop/tdesktop#25284]
### Is your feature request related to a problem?

![https://i.imgur.com/NizAt39.png](https://i.imgur.com/NizAt39.png)

Update Telegram https://snapcraft.io/telegram-desktop

### Describe the solution you'd like

Update

### Describe alternatives you've considered

Update Telegram snap

**Comment by ilya-fedin** [comment]
Unfortunately, this version is skipped due to the build being broken at the moment of release, you have to wait the next release.
