### ISSUE TITLE
[Question] No auto login after update

### ISSUE THREAD

**Issue by 0unknwn** [telegramdesktop/tdesktop#25282]
After an update of Telegram (from falthub) it does not log me in automatically but I am asked to login. Unfortunately my laptop is my online device running Telegram and I do not receive an SMS. Is there any chance to log in with my profile on my computer?

**Comment by ilya-fedin** [comment]
You must have an active session on a mobile client in order to be able to log in

**Comment by 0unknwn** [comment]
So that would mean my profile is lost, if I don’t have an active session?

**Comment by ilya-fedin** [comment]
well, you have multiple months before your account will be deleted, so you can create a new session with a mobile client

**Comment by 0unknwn** [comment]
Thanks for your answer!

I have tried to get a SMS from the desktop client and the android app, but both tell me that they send a message to my other device. But I have no other device with an active session; I never used Telegram in any other device but my laptop. Is there anything else I could do to get my profile back?

**Comment by ilya-fedin** [comment]
@0unknwn mobile application should let you get SMS if you can't enter the code IIRC. I guess this button/link is barely noticeable on the screen.

**Comment by 0unknwn** [comment]
I found the button. But when I press it I get immediately this message but never receive any SMS.  
![image](https://user-images.githubusercontent.com/45519061/200694387-fb692113-68a8-4f59-91fd-3ce9105323e1.png)

**Comment by ilya-fedin** [comment]
Maybe it's not the button I talk about? It may appear not immediately, but after some time remaining on the screen after the code is sent to another app

**Comment by 0unknwn** [comment]
Thats the button. 
![image](https://user-images.githubusercontent.com/45519061/200695039-90a13fbc-04ba-45b7-b1fe-4f42a9f072e5.png)

**Comment by ilya-fedin** [comment]
Maybe it's because you don't use a real phone (I see cursor)?

**Comment by 0unknwn** [comment]
It’s waydroid. I don’t have a smartphone. So maybe I will need to ask a friend for help.
