### ISSUE TITLE
custom invite link management panel has disapeard for owner of channels since last update (v4.3)

### ISSUE THREAD

**Issue by mr-459** [telegramdesktop/tdesktop#25283]
### Steps to reproduce

1.create a channel
2.go to setting
3.click "channel type"
4.there is no more ability to manage custom invite links here , but its okay in previous versions

### Expected behaviour

it should show links made by you , other admins and show a panel to create new invite links

### Actual behaviour

it only shows changing channel from public to private

### Operating system

Windows 11 22h2

### Version of Telegram Desktop

v4.3

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
There is the "Invite links" button in the "Manage channel" section.

**Comment by mr-459** [comment]
> There is the "Invite links" button in the "Manage channel" section.
please note you are not talking to a donkey
i've been using this abality for month's and i know where the shit is , it has disapeard for owner of channel's and still working for normal admins

DO NOT CLOSE AN UNRESOLVED PROBLEM

**Comment by mr-459** [comment]
this are two photos that may help you:
![image](https://user-images.githubusercontent.com/38500081/200335869-ba0fd6d3-f3a4-43a2-a3af-7caa977b8634.png)
![image](https://user-images.githubusercontent.com/38500081/200335929-205a94a4-279e-4db8-9acc-d752143645a1.png)


and how it was before?
![image](https://user-images.githubusercontent.com/38500081/200336509-ed45fa7a-c31f-4ce5-b4e8-6a27dc3654b2.png)
![image](https://user-images.githubusercontent.com/38500081/200336562-efc7ad9a-5c80-4fe0-9f6a-7f53dd60184c.png)

**Comment by john-preston** [comment]
Should be fixed in the upcoming release.

**Comment by mr-459** [comment]
fixed by the beta update v4.3.1, thanks telegram for really fast fixings and fuck you the guy who closed this issue [Aokromes](https://github.com/Aokromes))
