### ISSUE TITLE
Applying patch files doesn't work because of line endings

### ISSUE THREAD

**Issue by kleuter** [telegramdesktop/tdesktop#2528]
When trying to follow build instructions for Windows 10/MSVC2015, I've encounted the problem that non of .patch files were applied because of incorrect line endings (CR/LF instead of LF). 
After re-saving .patch files with Nodepad++ with specifying Unix LF line endings everything went fine.

Example error:

```
fatal: git apply: bad git-diff - expected /dev/null on line XXX
```

**Comment by Aokromes** [comment]
#2388

**Comment by auchri** [comment]
Worked for me
