### ISSUE TITLE
Issue with stickers

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25291]
### Steps to reproduce

1. Install https://t.me/addstickers/Transparency_test
2. Add first 512x212 sticker to image
3. Add second 512x512 sticker to image
4. First sticker will be a little flattened
![photo_2022-11-07_14-11-40](https://user-images.githubusercontent.com/39812401/200296969-03e1a3b4-e34f-4a94-ada3-fd89772d5647.jpg)
![photo_2022-11-07_14-11-41](https://user-images.githubusercontent.com/39812401/200296974-46eb2129-790e-4b73-abd1-a89706f97e1a.jpg)

https://user-images.githubusercontent.com/39812401/200297067-32dec2b9-530a-42da-993d-4ee28a4ea7ef.mp4

### Expected behaviour

Stickers with any size must showing fine without any flattening.

### Actual behaviour

Stickers that have size not 512x512 is little flattened.

### Operating system

Windows 10

### Version of Telegram Desktop

4.3

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
`+`

**Comment by Neurotoxin001** [comment]
Still bugged

**Comment by 23rd** [comment]
You can try a debug build.
https://github.com/telegramdesktop/tdesktop/actions/runs/6762113948

**Comment by Neurotoxin001** [comment]
It looks a lot better now. It's not flattened now, but it's gotten a little smaller.

https://github.com/telegramdesktop/tdesktop/assets/39812401/b3922952-9560-46c5-91c2-79f72ed6e209
https://github.com/telegramdesktop/tdesktop/assets/39812401/92663fb5-0765-4d48-955e-e42a29384dc6

**Comment by Neurotoxin001** [comment]
> but it's gotten a little smaller.

You're not going to fix it?
