### ISSUE TITLE
[Question] Command to open a chat in a window

### ISSUE THREAD

**Issue by alxlg** [telegramdesktop/tdesktop#25294]
Hi, I enabled the experimental feature that let you open a chat in a window with a Ctrl+click.

Is there a way to open a chat in a window using the command line? Maybe an additional argument to the `tg://` protocol we use to specify the chat?

Thank you

**Comment by alxlg** [comment]
I am still interested

**Comment by Aokromes** [comment]
> 

right click over chat on chats list, open on new window.

**Comment by alxlg** [comment]
> > 
> 
> right click over chat on chats list, open on new window.

Read again my question.

**Comment by ilya-fedin** [comment]
Anyway, issue tracker is no more a place for questions. Questions should now be asked in https://t.me/TelegramDesktopTalk as it's way more likely that someone in the group will answer rather than the developer.

**Comment by alxlg** [comment]
@ilya-fedin 
This issue was marked later as "question" by a collaborator but of course it is meant to express interest for this feature. If it exists, it should be documented somewhere; if it doesn't exist, *this issue should be used to track its development.* I think the kind of questions that makes sense in that chat room and not here is another one.

Anyway this was closed because of a misunderstanding @Aokromes , since I mentioned the Ctrl+click in the GUI and asked if there is an equivalent as a command line argument and I think it is clear why this would be a nice thing to have.

**Comment by ilya-fedin** [comment]
> This issue was marked later as "question" by a collaborator

I see it's you
![изображение](https://user-images.githubusercontent.com/17829319/236804545-114c7a11-57c8-48c9-9b93-dd485645f246.png)
I also see the issue has [Question] in the title since beginning.

**Comment by alxlg** [comment]
> > This issue was marked later as "question" by a collaborator
> 
> I see it's you ![изображение](https://user-images.githubusercontent.com/17829319/236804545-114c7a11-57c8-48c9-9b93-dd485645f246.png) I also see the issue has [Question] in the title since beginning.

Then maybe it was some kind of template because I don't remember to have ever assigned a tag.

**Comment by ilya-fedin** [comment]
Yes, it's a part of template, but again it's you who have chosen the question template instead of bug report or feature request

**Comment by alxlg** [comment]
> Yes, it's a part of template, but again it's you who have chosen the question template instead of bug report or feature request

My bad, this is a question that could turn into a feature request if answered negatively and a request to document if answered positively.

Please, be more pragmatic or don't complain later if you are replaceable by "AI" algorithms.
