### ISSUE TITLE
App automatically try to save file from latest message (after update tg 4.3)

### ISSUE THREAD

**Issue by evgeniyworkbel** [telegramdesktop/tdesktop#25290]
### Steps to reproduce

1. Open app
2. Somebody sends you message with file (for example, my issue fires on pdf files)
3. Click this chat which contains file in the latest message
4. App automatically fires Portal (system linux app) to save file
5. I cannot do anything after that
https://disk.yandex.ru/i/YO1SsJp4XqnskA
https://disk.yandex.ru/i/6foAM0gTQuzmyQ
https://disk.yandex.ru/i/DH-AAxAcvPC9oA

### Expected behaviour

Clicking any chat without automatic saving file from it

### Actual behaviour

i open chat and app automatically try to save file. And immediately it opens Portal (default ubuntu system app for saving files) in a recursive way, so i cannot close window and it drives me nuts because it doesnt allow me to work! If you key up "Esc", app will crash and close.
Please fix issue as soon as possible.

### Operating system

Ubuntu 22.04 LTS

### Version of Telegram Desktop

4.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Already fixed on dev branch
