### ISSUE TITLE
[Feature Request] Give the setting to change the corners of the message bubbles

### ISSUE THREAD

**Issue by Stepashka20** [telegramdesktop/tdesktop#25302]
### Is your feature request related to a problem?

New 50% border radius message bubbles are horrible, disgusting, ugly! Why on mobile we can change border radius, but on PC not?!

### Describe the solution you'd like

Make a setting to change the corners of messages

### Describe alternatives you've considered

-

**Comment by ilya-fedin** [comment]
#25265
