### ISSUE TITLE
 [Question] Docker build last version failed

### ISSUE THREAD

**Issue by x09** [telegramdesktop/tdesktop#25300]
Hi

Tried several times to build (all instructions from https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md) the latest version in docker. The result is always negative. Why? Waht i cad do wrong.

<pre>
#0 8035.2 In member function 'reserve',
#0 8035.2     inlined from 'reserve' at /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h:739:6,
#0 8035.2     inlined from '__ct ' at /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h:415:12,
#0 8035.2     inlined from '__ct ' at /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/qqmltypenamecache_p.h:29:8,
#0 8035.2     inlined from '__ct ' at /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h:271:91,
#0 8035.2     inlined from '__ct ' at /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h:278:98,
#0 8035.2     inlined from 'takeNode' at /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h:521:25,
#0 8035.2     inlined from 'takeNode' at /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h:513:32,
#0 8035.2     inlined from 'createNode' at /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h:640:23,
#0 8035.2     inlined from 'operator[]' at /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h:735:27,
#0 8035.2     inlined from 'operator[]' at /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h:731:4,
#0 8035.2     inlined from 'populateCache' at /usr/src/Libraries/qt_6_4_0/qtdeclarative/src/qml/qml/qqmlimport.cpp:258:77:
#0 8035.2 /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h:747:23: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
#0 8035.2   747 |     nodePool->nodes = new Node[n];
#0 8035.2       |                       ^
#0 8035.2 /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h: In member function 'populateCache':
#0 8035.2 /opt/rh/devtoolset-10/root/usr/include/c++/10/new:128:26: note: in a call to allocation function 'operator new []' declared here
#0 8035.2   128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
#0 8035.2       |                          ^
#0 8035.2 In member function 'reserve',
#0 8035.2     inlined from 'reserve' at /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h:739:6,
#0 8035.2     inlined from 'update' at /usr/src/Libraries/qt_6_4_0/qtdeclarative/src/qml/qml/qqmlpropertycache.cpp:569:24:
#0 8035.2 /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h:747:23: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
#0 8035.2   747 |     nodePool->nodes = new Node[n];
#0 8035.2       |                       ^
#0 8035.2 /usr/src/Libraries/qt_6_4_0/qtbase/include/QtQml/6.4.0/QtQml/private/../../../../../../qtdeclarative/src/qml/qml/ftw/qstringhash_p.h: In member function 'update':
#0 8035.2 /opt/rh/devtoolset-10/root/usr/include/c++/10/new:128:26: note: in a call to allocation fun
#0 8035.2 [output clipped, log limit 1MiB reached]
#0 8360.3 CMake Error at qtdeclarative/src/qml/cmake_install.cmake:95 (file):
#0 8360.3   file INSTALL cannot copy file
#0 8360.3   "/usr/src/Libraries/qt_6_4_0/qtbase/lib/libQt6Qml.a" to
#0 8360.3   "/usr/src/Libraries/qt-cache/usr/local/desktop-app/Qt-6.4.0/lib/libQt6Qml.a":
#0 8360.3   Success.
#0 8360.3 Call Stack (most recent call first):
#0 8360.3   qtdeclarative/src/cmake_install.cmake:57 (include)
#0 8360.3   qtdeclarative/cmake_install.cmake:47 (include)
#0 8360.3   cmake_install.cmake:67 (include)
#0 8360.3 
#0 8360.3 
------
error: failed to solve: executor failed running [bash -c . /opt/rh/devtoolset-10/enable; exec bash -c "$@" -s git clone -b v6.4.0 --depth=1 git://code.qt.io/qt/qt5.git qt_6_4_0        && cd qt_6_4_0  && git submodule update --init --recursive --depth=1 qtbase qtdeclarative qtwayland qtimageformats qtsvg qt5compat qtshadertools  && cd qtbase    && find ../../patches/qtbase_6_4_0 -type f -print0 | sort -z | xargs -r0 git apply        && cd ../qtdeclarative  && sed -i '/add_subdirectory(quickcontrols2)/d' src/CMakeLists.txt      && sed -i '/add_subdirectory(quickdialogs2)/d' src/CMakeLists.txt       && sed -i '/add_subdirectory(quicknativestyle)/d' src/CMakeLists.txt      && cd ..        && ./configure -prefix "/usr/local/desktop-app/Qt-6.4.0"                CMAKE_BUILD_TYPE=None           -opensource             -confirm-license -libproxy                -qt-libpng              -qt-harfbuzz            -qt-pcre                -no-icu                 -no-feature-xcb-sm              -no-feature-egl-extension-platform-wayland              -no-feature-highdpiscaling                -static                 -dbus-runtime           -openssl-linked                 -nomake examples                -nomake tests   && cmake --build . --parallel   && DESTDIR="/usr/src/Libraries/qt-cache" cmake --install .        && cd ..        && rm -rf qt_6_4_0]: exit code: 1
</pre>

![изображение](https://user-images.githubusercontent.com/1303927/200378870-7dd4f813-714f-47d8-94c7-be4522bdd58a.png)

**Comment by ilya-fedin** [comment]
as you can see, docker clipped the output, so actual error is not displayed... Have you checked RAM and storage consumption the time before it fails? Maybe you just have not enough of them (it will release some storage space after build, so checking after is not reliable).

**Comment by x09** [comment]
RAM: 8GB
SWAP: 8GB
HDD in Docker Root Dir more than 65Gb

docker info | grep Root
 Docker Root Dir: /data/docker

LANG=C df -h /data
Filesystem                          Size  Used Avail Use% Mounted on
/dev/mapper/lvm_hdd_vg-lvm_data_lv   96G   31G   65G  33% /data

**Comment by ilya-fedin** [comment]
> it will release some storage space after build, so checking after is not reliable

Are you sure you have checked in the moment before it fails, not after?

8 GB RAM + 8 GB SWAP is highliy liekly to be not enough, check with htop when build in progress, to

**Comment by Henry-ZHR** [comment]
I tried to build it in Github Action and failed on the same step. Instead of RAM issues, `No space left on device` is reported.

**Comment by x09** [comment]
I increase swap*2, but failed again..
What to do it, how to build it?

**Comment by ilya-fedin** [comment]
@x09 i recommend to have 30GB of swap at least

> I tried to build it in Github Action and failed on the same step. Instead of RAM issues, `No space left on device` is reported.

Yeah, GH actions have too less storage space for tdesktop Docker image, it seems you can't use them for this :(

**Comment by Henry-ZHR** [comment]
But docker image for v4.2.4 can be built successfully. What did you change in v4.3.0?

**Comment by ilya-fedin** [comment]
LTO for all the dependencies

**Comment by ilya-fedin** [comment]
Ah, tdesktop now depends on qtdeclarative what is a very big dependency

**Comment by ilya-fedin** [comment]
This is C++
You can limit number of cores available to docker, that should lessen RAM consumption.
You can also disable debug symbols and LTO when building the image by specifying `DEBUG=` and `LTO=` to the poetry command (that's what GH action does)
