### ISSUE TITLE
App automatically try to save file from latest message (after update tg 4.3.1)

### ISSUE THREAD

**Issue by evgeniyworkbel** [telegramdesktop/tdesktop#25308]
### Steps to reproduce

1. Open app
2. Somebody sends you message with any file
3. Click this chat which contains file in the latest message
4. App automatically fires Portal (system linux app) to save file

Recursively behaviour was fixed after 4.3.1, but app continues to automatically fires Portal to save file in case you haven't this file yet on your PC

### Expected behaviour

Clicking any chat without automatic saving file from it

### Actual behaviour

It describes in "Steps to reproduce" section
All my packages on PC are up-to-date, I tried to reinstall telegram.

### Operating system

Ubuntu 22.04 LTS

### Version of Telegram Desktop

4.3.1

### Installation source

Flatpak

**Comment by rolivegab** [comment]
Agree, it stopped to ask recursively, but it still tries to save file

**Comment by ilya-fedin** [comment]
This was always a thing, it's just previously it did silently while it can't due to sandbox. This is not a bug.

**Comment by john-preston** [comment]
@rolivegab This happens due to auto-download being enabled by default and that auto-download can't work without portal giving access to the download folder.

For now you can disable auto-download for files in Settings > Advanced > Automatic media download.

Later I think this should be redesigned so that the auto-download is disabled by default for the sandboxed environments and asking for the folder only when enabling by hand.

**Comment by aminovmunir** [comment]
> @rolivegab This happens due to auto-download being enabled by default and that auto-download can't work without portal giving access to the download folder.
> 
> For now you can disable auto-download for files in Settings > Advanced > Automatic media download.
> 
> Later I think this should be redesigned so that the auto-download is disabled by default for the sandboxed environments and asking for the folder only when enabling by hand.

i have issue, but i've disabled autodownload in advanced settings

**Comment by ilya-fedin** [comment]
The code attmpts to get default download path before checking autodownload settings

**Comment by aminovmunir** [comment]
> The code attmpts to get default download path before checking autodownload settings

fix it pls :)

**Comment by ilya-fedin** [comment]
I don't see any sense given that this bug is already fixed

**Comment by aminovmunir** [comment]
but save dialog opened when i just scrolling chat. It is uncomfortable!
i have disabled autodownload.

**Comment by ilya-fedin** [comment]
unfortunately :(

**Comment by aminovmunir** [comment]
why program don't choose default download path and open save dialog? I set вуаф

**Comment by ilya-fedin** [comment]
there's no default path in sandboxed environments as there's no access to anything in sandboxed environments. The chooser is like a request to allow access to a folder in other system (that's how the Linux stack works, we have no choice here).

**Comment by aminovmunir** [comment]
How can i fix it in ubuntu 22.04?

**Comment by ilya-fedin** [comment]
You need to build a version from code in dev branch

**Comment by aminovmunir** [comment]
thanks, fixed when i choose default path in save dialog
