### ISSUE TITLE
Can't switch pictures in threads

### ISSUE THREAD

**Issue by ScarletS5** [telegramdesktop/tdesktop#25309]
### Steps to reproduce

Upload a group of pictures when replying to some messages,then open the replies to the message and open one of the pictures then you can't switch to the last picture or the next one in the thread. It happens to the first message in the thread, too.

### Expected behaviour

Shoult be able to switch pictures in threads.

### Actual behaviour

Can't switch pictures in threads.

### Operating system

Windows 10

### Version of Telegram Desktop

TG Desktop version 4.3.1 x64

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25275
