### ISSUE TITLE
[Feature Request] Needs a new UI

### ISSUE THREAD

**Issue by aryankashyap7** [telegramdesktop/tdesktop#25307]
### Is your feature request related to a problem?

It's not a resolution to some bug, just an enhancement that we users need.

### Describe the solution you'd like

Telegram is an amazing software but with time, it's also necessary to update the UI that can compete with the latest design we have nowadays. It's a bummer to have such a simple UI for this amazing application.

### Describe alternatives you've considered

Features that can be expected:
1. Rounded Corners
2. Enhanced Dark/Light themes
3. Better UI Boxes
4. 3D Icons with Animated Folders
5. Show Online/Offline Status in the messages screen [May have turn off mode in settings]
6. A option to directly stream media files, instead of downloading the whole document file

**Comment by ilya-fedin** [comment]
This is not a place for design suggestions, use https://t.me/designers
