### ISSUE TITLE
Unable to register new account using Telegram Desktop

### ISSUE THREAD

**Issue by axet** [telegramdesktop/tdesktop#25319]
### Steps to reproduce

1. open telegram
2. enter your phone number
3. wait for sms
4. wait for call
5. nothing happens

### Expected behaviour

sms would come

### Actual behaviour

not comming

### Operating system

debian bookworm

### Version of Telegram Desktop

4.3.1

### Installation source

Flatpak

**Comment by c0re100** [comment]
It's disabled by server side.
Use your smartphone to register first.

**Comment by axet** [comment]
Telegram FOSS android also does not work

**Comment by xvitaly** [comment]
Yes. They want you contacts, geolocation, etc. to sell to third-parties.

**Comment by john-preston** [comment]
@xvitaly That's not true. You can deny contacts access and geolocation access for the Telegram android app and still sign up.

**Comment by xvitaly** [comment]
> You can deny contacts access and geolocation access for the Telegram android app and still sign up.

Yes, but it will ask again until you press "Deny for this application and don't ask again". 99% of users will simply press "Allow".

**Comment by Aokromes** [comment]
maybe a better text there can be

A code was send via Telegram to your other devices if you have any connected.
If this is your 1st account or you don't have Telegram installed on a iOS / Android mobile phone install before Telegram on your mobile phone.
