### ISSUE TITLE
XWayland not available to Telegram (flatpak) when running from the GNOME Wayland session

### ISSUE THREAD

**Issue by why-not-try-calmer** [telegramdesktop/tdesktop#25312]
### Steps to reproduce

```
$ flatpak run org.telegram.desktop
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.
```

### Expected behaviour

The application should run using the Xwayland adapter from the GNOME Wayland session.

### Actual behaviour

The application doesn't find Xwayland and aborts on launch.

### Operating system

Pop!_OS 22.04

### Version of Telegram Desktop

4.3.1, flatpak commit f823114505969fdfd2b374cb33176f665d0bdcc6e036c87e5393983c1fad03d3

### Installation source

Flatpak

**Comment by why-not-try-calmer** [comment]
In many of the other Issues you've recommended using the Xwayland backend in some cases. How is the user supposed to do this if this command fails?

**Comment by ilya-fedin** [comment]
Which ones? I believe a lot of time passed since then, I definitely don't recommend using Xwayland now as it's a door for more bugs.

**Comment by why-not-try-calmer** [comment]
Well [here](https://github.com/telegramdesktop/tdesktop/issues/25231#issuecomment-1295987771) for example. But the more important point is: is it possible to run this flatpak on Xwayland and if so, how, please?

**Comment by ilya-fedin** [comment]
I don't recommend there. I said 'if you want', but I definitely don't recommend. These things will be forever, just get used to. You can't use Xwayland forever, sorry.

**Comment by ilya-fedin** [comment]
> you are making the presupposition that it's possible to run this flatpak on Xwayland

That users uses snap, not flatpak. Snap doesn't have such level of sandboxing.

**Comment by why-not-try-calmer** [comment]
> > you are making the presupposition that it's possible to run this flatpak on Xwayland
> 
> That users uses snap, not flatpak. Snap doesn't have such level of sandboxing.

I see. Thanks
