### ISSUE TITLE
Coredump on Linux sway/wayland+fusuma for swipe gestures

### ISSUE THREAD

**Issue by niktob560** [telegramdesktop/tdesktop#25318]
### Steps to reproduce

1. Start `sway`
2. Start `fusuma` with slide-gestures
3. Start telegram-desktop
4. Swipe sideways
5. Core dumped

### Expected behaviour

Expected no reaction on swipes

### Actual behaviour

Crash on swipe

### Operating system

Linux x86_64 Wayland, sway 1.7

### Version of Telegram Desktop

4.3.1 from ArchLinux official repo

### Installation source

Other (unofficial) source

### Logs

```shell
Crash is present for about half of year 
logs: https://pastebin.com/ML8R3g6c
coredump: https://pastebin.com/Xa06SYrg
```

**Comment by ilya-fedin** [comment]
Get the official version from https://desktop.telegram.org, enable installation of beta versions, reproduce the crash, send crash report and report back the crash report tag
