### ISSUE TITLE
undefined symbol: , version GLIBC_2.2.5

### ISSUE THREAD

**Issue by abate** [telegramdesktop/tdesktop#25320]
### Steps to reproduce

this is a startup problem

### Expected behaviour

telegram should start

### Actual behaviour

it does not. I suspect if a problem with the version of GLIBC_2 . I'm wondering if there is a quick solution or there are plans to recompile the snap package for the new glibc

### Operating system

debian/unstable

### Version of Telegram Desktop

4.3.1 from the snap store

### Installation source

Snap

### Logs

```shell
telegram-desktop: symbol lookup error: /lib/x86_64-linux-gnu/libcap.so.2: undefined symbol: , version GLIBC_2.2.5
```

**Comment by ilya-fedin** [comment]
Last time I tested the snap package on Debian (2 years ago), it didn't work, it returned to me weird errors not having any sense (like your one), it seems Debian patches snap and adds bugs or something, I recommend to switch to official binary or flatpak. Or switch to Ubuntu or an Arch-based distro, it's the only distros where snap worked as intended for me.
