### ISSUE TITLE
error while loading shared libraries: libthai.so.0: object file has no dynamic section

### ISSUE THREAD

**Issue by dmitriyshashkin** [telegramdesktop/tdesktop#25324]
### Steps to reproduce

1. snap install telegram-desktop
2. snap run telegram-desktop

### Expected behaviour

Telegram desktop starts

### Actual behaviour

Telegram desktop crashes with the following error:

ERROR: update-mime-database /home/till/snap/telegram-desktop/4312/.local/share/mime exited abnormally with status 1
telegram-desktop: error while loading shared libraries: libthai.so.0: object file has no dynamic section

### Operating system

Fedora Linux 36 (Workstation Edition)

### Version of Telegram Desktop

4.3.1

### Installation source

Snap

### Logs

```shell
date: date: no version information available (required by date)
date: date: no version information available (required by date)
date: date: no version information available (required by date)
date: date: no version information available (required by date)
date: date: no version information available (required by date)
date: date: no version information available (required by date)
date: date: no version information available (required by date)
date: date: no version information available (required by date)
date: symbol lookup error: date: undefined symbol: 
sed: /lib/x86_64-linux-gnu/libacl.so.1: version `ACL_1.0' not found (required by sed)
sed: sed: no version information available (required by /lib/x86_64-linux-gnu/libacl.so.1)
sed: sed: no version information available (required by /lib/x86_64-linux-gnu/libacl.so.1)
sed: sed: no version information available (required by /lib/x86_64-linux-gnu/libacl.so.1)
sed: sed: no version information available (required by /lib/x86_64-linux-gnu/libacl.so.1)
sed: sed: no version information available (required by /lib/x86_64-linux-gnu/libacl.so.1)
/snap/telegram-desktop/4312/bin/desktop-launch: line 51: /.config/user-dirs.dirs: No such file or directory
cp: /lib/x86_64-linux-gnu/libacl.so.1: version `ACL_1.0' not found (required by cp)
cp: cp: no version information available (required by /lib/x86_64-linux-gnu/libacl.so.1)
cp: cp: no version information available (required by /lib/x86_64-linux-gnu/libacl.so.1)
cp: cp: no version information available (required by /lib/x86_64-linux-gnu/libacl.so.1)
cp: cp: no version information available (required by /lib/x86_64-linux-gnu/libacl.so.1)
cp: cp: no version information available (required by /lib/x86_64-linux-gnu/libacl.so.1)
Directory '/home/till/snap/telegram-desktop/4312/.local/share/mime/packages' does not exist!
/snap/telegram-desktop/4312/bin/desktop-launch: line 538: /flavor-select: No such file or directory
Warning: Qt4 does not support Wayland!
ERROR: update-mime-database /home/till/snap/telegram-desktop/4312/.local/share/mime exited abnormally with status 1
telegram-desktop: error while loading shared libraries: libthai.so.0: object file has no dynamic section
```

**Comment by Aokromes** [comment]
very likely the same as https://github.com/telegramdesktop/tdesktop/issues/25320

**Comment by ilya-fedin** [comment]
That looks like snap is pretty much broken on the system. This is not a surprise given that Fedora is specified as the OS and it uses SELinux while snap is designed for AppArmor. I heard a lot of complains about snap on Fedora, so I recommend to switch to the static binary or flatpak.

**Comment by xvitaly** [comment]
> I heard a lot of complains about snap on Fedora

True. Snap shouldn't be used on other than Ubuntu distributions.

> so I recommend to switch to the static binary or flatpak.

Or you can use a packaged version from the RPM Fusion repository: `sudo dnf install telegram-desktop`.

**Comment by ilya-fedin** [comment]
I can't really recommend your package given how frequently it has problems :(

**Comment by ilya-fedin** [comment]
Search through the issue tracker? It's just I remembered Fedora users frequently report something and they can't reproduce when they replace your build with official binary.

**Comment by xvitaly** [comment]
> Search through the issue tracker? It's just I remembered Fedora users frequently report something and they can't reproduce when they replace your build with official binary.

Yes, please. Show me such issues.

**Comment by ilya-fedin** [comment]
@xvitaly I don't really want to waste time on that as there's around 11k issues in the repo. Feel free to search on your own if you're interested.

**Comment by xvitaly** [comment]
> I don't really want to waste time on that as there's around 11k issues in the repo. Feel free to search on your own if you're interested.

You said that our package has problems, so you must prove your words.

**Comment by ilya-fedin** [comment]
No, I don't know whether it has problems right now, I only said I noticed people frequently report bugs in your package that don't exist in official versions. I don't have any interest in arguing with you, I just say what I see. You're free to do with that information whatever you want.
