### ISSUE TITLE
Emoji reactions don't respect "Enable animations" nor "Loop animated stickers" settings

### ISSUE THREAD

**Issue by torunar** [telegramdesktop/tdesktop#25323]
### Steps to reproduce

1. Go to Settings > Advanced.
2. Disable "Enable animations" setting.
3. Open reactions menu for any message.

or

1. Go to Settings > Chat settings.
2. Disable "Loop animated stickers".
3. Open reactions menu for any message.

### Expected behaviour

1. Emojis are not animated or at least animation is played once.
2. I'm not having a seizure every time this menu is opened.

### Actual behaviour

1. Emojis are animated and animations are looped.

### Operating system

any

### Version of Telegram Desktop

4.3.1

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment]
Unfortunately, it's probably intended - related discussions: #6234 #24925
