### ISSUE TITLE
Save file window opens when viewing attachments

### ISSUE THREAD

**Issue by dimseres** [telegramdesktop/tdesktop#25339]
### Steps to reproduce

1. Open Telegram Desktop
2. Select any chat and click on group or contact information, or select saved messages
3. And Pick File or Audio Attachments

### Expected behaviour

The save file window should not appear, when scroll or click

### Actual behaviour

A window for saving a file opens when clicking on attachments, and when scrolling Audio files or Simple attached files. In the case of voice messages, videos, links, everything works correctly.
![image](https://user-images.githubusercontent.com/18141427/201421603-52525548-71ec-4a02-936c-67aab34de4fd.png)

### Operating system

Ubuntu 22.04.1 LTS

### Version of Telegram Desktop

4.3.1

### Installation source

Snap

**Comment by ilya-fedin** [comment]
yeah, tdesktop tries to save those files
