### ISSUE TITLE
Mic icon just disappeared while I was leaving voice messages for someone

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#25334]
### Steps to reproduce

Nothing is there. Instead I get this blue error. Win 8.1

https://i.imgur.com/bJ7bhFH.png

I even restarted TG. Ever since your last 2 updates, I have been having serious issues. 

I reply to someone using VM and after I send it, TG does a reply to, to the same message again so the text field is waiting for me to do a VM or type. This has been going on for days now & it's very frustrating. 

Please fix.

Thanks

### Expected behaviour

Mic icon should be there.

When I send a VM, TG shouldn't do a reply to that same message again.

### Actual behaviour

See above

### Operating system

Win 8.1

### Version of Telegram Desktop

4.3.1

### Installation source

Static binary from official website

### Logs

```shell
I don't know where these are.

Can you tell me when you are gong to get this fixed please or give me a free month of premium since I am paying for it & now I can't send VMs.

Thanks
```

**Comment by ilya-fedin** [comment]
tdesktop checks whether input device are present only on application start, ensure you have microphone connected before you start the application.

**Comment by ILoveSkilledCoders** [comment]
Ok, now it's working, but I have never had this problem before & I always click my USB hub's button to turn it off & on & I have TG open all the time, so something must have changed, b/c again, no problem ever. 

I don't want to have to restart TG just b/c I want to send a VM. That's nuts.

Thanks

What about this issue? I reply to someone using VM and after I send it, TG does a reply to, to the same message again so the text field is waiting for me to do a VM or type. This has been going on for days now & it's very frustrating.

**Comment by ilya-fedin** [comment]
> so something must have changed

No, there were no changes about this.

**Comment by ILoveSkilledCoders** [comment]
> > so something must have changed
> 
> No, there were no changes about this.

I'm saying there's a bug.

**Comment by ilya-fedin** [comment]
Sorry, but this behavior is expected, that's how audio library tdesktop is using works

**Comment by ILoveSkilledCoders** [comment]
> Sorry, but this behavior is expected, that's how audio library tdesktop is using works

No, I don't think you understand what I'm saying. So, I went to do a video for you to see & now it's not doing that. If it starts up again, I'll comment again. 

Thanks

What about this issue?

https://github.com/telegramdesktop/tdesktop/issues/25335

Thanks

**Comment by ilya-fedin** [comment]
I don't know, sorry

**Comment by ILoveSkilledCoders** [comment]
> I don't know, sorry

You don't know how to fix the problem? Are you in TG's tech department?

**Comment by VetaLioSTV** [comment]
I have the same. When you make reply on voice message and answer with voice message(successfully sent message), then for no reason it make reply again (as like repeats your last action). Thats is annoying :(.

**Comment by ILoveSkilledCoders** [comment]
> I have the same. When you make reply on voice message and answer with voice message(successfully sent message), then for no reason it make reply again (as like repeats your last action). Thats is annoying :(.
> 
> **`Windows 8.1; TG PC Version - 4.3.1 x64`**

Yehhh, it's not just me. I reported this in their TG bug area (not here) & no one ever got back to me. :(

What OS are you using?
