### ISSUE TITLE
number notifications at tray icon have disappeared, recently, gnome43

### ISSUE THREAD

**Issue by iambumblehead** [telegramdesktop/tdesktop#25336]
### Steps to reproduce

1. use telegram desktop [4.3.1-2 on gnome43](https://archlinux.org/packages/community/x86_64/telegram-desktop/) with [latest gnome-shell-appindicator](https://archlinux.org/packages/community/any/gnome-shell-extension-appindicator/)
2. receive a message and leave the message in an unread state
3. notice the telegram icon in the "dash" area shows a red-filled circle "1"
4. **bug:** the telegram icon in the tray does not have red-filled circle "1"

`journalctl -r --user` shows a spam of svg-related failure messages. The blue telegram tray icon is seen at the top-right,

<img src="https://user-images.githubusercontent.com/2058705/201277913-230fcbf6-fd40-49d3-8330-a6dd9aa2d40b.jpg" width="400px" />

thank you for allowing me to submit this issue! :)

### Expected behaviour

the telegram icon in the tray area should have red-filled circle "1"

### Actual behaviour

the telegram icon in the tray does not have red-filled circle "1"

### Operating system

arch-linux, rolling, gnome 43

### Version of Telegram Desktop

4.3.1

### Installation source

Other (unofficial) source

**Comment by iambumblehead** [comment]
related? https://github.com/telegramdesktop/tdesktop/issues/25173

**Comment by ilya-fedin** [comment]
Can you reproduce with the static binary from https://desktop.telegram.org?

**Comment by iambumblehead** [comment]
the notification icon works with the binary

**Comment by ilya-fedin** [comment]
Nice
