### ISSUE TITLE
Starting yesterday I can't hear people's (including mine) voice messages

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#25335]
### Steps to reproduce

I have to jack up the volume to 100% & I still can't hear the messages.

### Expected behaviour

At 50% I should hear VMs fine

### Actual behaviour

No volume and I've tested this on Skype settings & when doing a VM & listening to it with the audio playback (works fine) tested it on the Windows test for playback, works fine. 

### Operating system

Windows 8.1

### Version of Telegram Desktop

4.3.1

### Installation source

Static binary from official website

**Comment by VetaLioSTV** [comment]
Same here. From latest update i have identical problem with voice message. 
**`Windows 8.1 4.3.1 x64`**

By the way, why on official changelog [page](https://desktop.telegram.org/changelog?setln=ru) is not reflected latest version which is 4.3.1?

**Comment by ILoveSkilledCoders** [comment]
> Same here. From latest update i have identical problem with voice message. **`Windows 8.1; TG PC Version - 4.3.1 x64`**
> 
> By the way, why on official changelog [page](https://desktop.telegram.org/changelog?setln=ru) is not reflected latest version which is 4.3.1?
> 
> Also, when you make reply on any type(i guess(?), tried on text and voice message) of message and then answer on it with voice message(successfully sent message), for no reason it make reply again (as like repeats your last action) on that message. Thats is annoying :(.
> 
> **UPD**: Seems to be something happened to settings of volume level. I have been manually increased volume slider to maximum and now it works as expected(same as previous versions)

Are you having volume issues on your computer too? 

I thought it was a Win 8.1 update b/c I didn't have a problem until after that update although I've had audio issues off & on for a while now on 2 different computers.

What OS are you using?

So it's working for you now?

**Comment by ILoveSkilledCoders** [comment]
So since I downgraded to Win 7, this issue has gone away, but it's clear to me that the updates are causing HUGE problems with people on Win 7 & 8, & that's not good.

**Comment by VetaLioSTV** [comment]
@ILoveSkilledCoders i think you can close this issue, since both me and you are not having problem with sound anymore.

**Comment by ILoveSkilledCoders** [comment]
> @ILoveSkilledCoders check this ![image](https://user-images.githubusercontent.com/15155286/206432227-20b34910-3e9c-41da-8966-8bc6d513d016.png)

I already closed it 2 days ago.
