### ISSUE TITLE
In PM, I receive an emoji on one of my messages and after seeing it it doesn't go away from 

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#25342]
### Steps to reproduce

I see I have an emoji next to the person in my personal contacts list, I go to look in the PMing area & either it's not there or after leaving that PM window, it still shows up in the main window as if there's another emoji, but there isn't. I go back into their PMing window & there's nothing.

Please see screenshot. - https://i.imgur.com/1bYOriu.png

### Expected behaviour

Once I see the message & the associated emoji, it goes away.

### Actual behaviour

Also, I think that when I go into the PM window it no longer has button that is supposed to take you to the comment with the emoji & now I can't even find the emoji. Again, all after your update from a week ago or so.

### Operating system

8.1

### Version of Telegram Desktop

4.3.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Still happens in 4.3.3? How to reproduce? Also, the image is not available anymore.

**Comment by ILoveSkilledCoders** [comment]
> Still happens in 4.3.3? How to reproduce? Also, the image is not available anymore.

Yes, I was having issues with it even on Win 7 even after the most recent updates. 

I haven't seen the issue in a maybe a week come to think of it, but it may be intermittent. 

It was a multi prong issue:

1. It would show me there was an emoji inside the thread & yet it didn't give me the white circle to click on it to take me to it.
2. It would give me the white circle, jump up, but there was no emoji where it took me to.
3. I also noted that when I see that there's a new message in a group in the left nav (not all of them) sometimes I have to scroll down to the very very bottom a few times so the notification that there's a new message disappears. I'm going to assume this is the same issue as the emoji issue.
4. There was a 3rd issue with the emojis, but I can't remember what it is now. If it comes up again, I'll try to remember to update this thread here.

Thanks

**Comment by ILoveSkilledCoders** [comment]
@john-preston - it just happened again. It's showing the heart notification that there's an emoji, I click on it (this is in PM) & there's nothing there.

**Comment by ILoveSkilledCoders** [comment]
@svenstaro 
@jhasse 
@alexandernst 

Ok, so I just updated to 4.4.1 & now I'm on Win 7 & this is still happening. 

Here's a SS. https://imgur.com/Qvt0L3g

There is no white icon to take me to an emoji when I go into the messaging area & a few days ago I noticed that if I scroll up looking for a message, the emojis start flashing on the messages. I assume they are the missing emojis.

Please can you fix?

Thanks

**Comment by svenstaro** [comment]
Why ping me? This is not a problem with Arch.

**Comment by ILoveSkilledCoders** [comment]
> Why ping me? This is not a problem with Arch.

Sorry, I was looking for the other person because he never got back to me (no one did) & he was no longer attached to this bug & I saw 3 others, so I just tagged you guys because I thought you were keeping an eye on bugs.

I have no idea what Arch is.

Sorry again.

**Comment by john-preston** [comment]
Please check 4.4.3 beta version.

If it still happens I'll need debug logs :( I'll ask for them in private chat.

**Comment by ILoveSkilledCoders** [comment]
> Please check 4.4.3 beta version.
> 
> If it still happens I'll need debug logs :( I'll ask for them in private chat.

Yes it's still happening & yes, please reach out to me.

Thanks

**Comment by john-preston** [comment]
You can write me at https://t.me/preston and I'll ask for DebugLogs and screenshots.
