### ISSUE TITLE
[Desktop]: Show contact name in window caption

### ISSUE THREAD

**Issue by PetbkA** [telegramdesktop/tdesktop#25345]
### Is your feature request related to a problem?

I'm using [ActivityWatch](https://activitywatch.net/) to time-track my work:
1. Mostly it detects apps where I spent time via process name or process window caption (see [watchers](https://docs.activitywatch.net/en/latest/watchers.html));
2. Depending on this parameters, it assigns spent time to some category (particularly, _Work_ or _Other_).

I have work AND other contacts in my Telegram account, but I can't separate them by AW category 'cause Telegram's window caption is always ``Telegram``

### Describe the solution you'd like

Change window caption to ``<Contact> - Telegram`` instead of ``Telegram``

### Describe alternatives you've considered

Don't see a better alternative

### Additional context

**OS:** Windows 10 LTSC 2021 (version 21H2) x64
**Telegram:** 4.3.1

**Comment by ilya-fedin** [comment]
#10067

**Comment by PetbkA** [comment]
Indeed, sorry
