### ISSUE TITLE
File handles for files uploaded are left open after the upload has completed

### ISSUE THREAD

**Issue by KieranDevvs** [telegramdesktop/tdesktop#25348]
### Steps to reproduce

1. Open a chat
2. Upload a file and send
3. Try and delete the file from your machine
4. See 
![image](https://user-images.githubusercontent.com/21192520/201781176-9624650f-7f14-4daf-91f2-b2660cf52a77.png)

This is a really annoying issue where I have to restart the client to delete unwanted files.

### Expected behaviour

Once the file upload is completed, the file handle should be disposed of.

### Actual behaviour

When an upload is initialized, a file handle is created for the duration of the upload but is never closed.

### Operating system

Windows 10

### Version of Telegram Desktop

4.2.4 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#7818

**Comment by john-preston** [comment]
@KieranDevvs any file? Or a video file specifically?

**Comment by KieranDevvs** [comment]
> @KieranDevvs any file? Or a video file specifically?

I think I recall it happening with images too. Not sure about documents. Ill do some testing tonight and get back to you with a more conclusive answer.
