### ISSUE TITLE
Exclude "Deleted Accounts" chats from forwarding targets

### ISSUE THREAD

**Issue by Aphotic** [telegramdesktop/tdesktop#25349]
### Steps to reproduce

try to forward msg to any chat scroll down till you see Deleted Accounts

### Expected behaviour

Exclude "Deleted Accounts" chats from forwarding targets

### Actual behaviour

why does tlg desktop bring up **_Deleted accounts_** to forward to 
when you cant. it gives an error. waste of space and clutter.      

![image](https://user-images.githubusercontent.com/30921064/201841863-12702b5e-50fd-48b6-a6d6-207927191efc.png)
![image](https://user-images.githubusercontent.com/30921064/201841902-52082a1c-11af-4bff-b663-109cab4534d9.png)

### Operating system

Telegram Desktop Windows 10

### Version of Telegram Desktop

v4.3.1

### Installation source

Static binary from official website

### Logs
[log.txt](https://github.com/telegramdesktop/tdesktop/files/10009872/log.txt)

**Comment by 23rd** [comment]
Please check the latest version.

**Comment by Aphotic** [comment]
> Please check the latest version.
can confirm its fixed in 4.3.2 onwards 
thanks alot 🏝
