### ISSUE TITLE
Some users can not receive sms verification code during registering

### ISSUE THREAD

**Issue by ILG2021** [telegramdesktop/tdesktop#25344]
I have develop and release a custom version of tdesktop.  I find that some users can not register success because they can not receive sms verification code during registering. But when they use offical tdesktop, they can receive. I don't know why, is it have some restrictions for developer? Can I pay some fee to break the limit?

**Comment by john-preston** [comment]
Official tdesktop doesn't allow registering or receiving sms at all, just login using code to another authorized Telegram device or by QR using authorized mobile Telegram app.
