### ISSUE TITLE
[Feature Request] Self-mute option to avoid awkward situations

### ISSUE THREAD

**Issue by Gr0t0s** [telegramdesktop/tdesktop#25340]
### Is your feature request related to a problem?

Quite often people accidentally send messages in a wrong group (work instead of friends, for example), making it awkward for everyone.

### Describe the solution you'd like

A self-mute option. Right now only the admin of the group can decide whether sending messages is allowed. Being able to mute yourself in certain chats by default will practically nullify the chance of misclicking or mistaking one chat for another by acting as a confirmation.

### Describe alternatives you've considered

So far, the described solution seems like the only viable one.

**Comment by Aokromes** [comment]
such thing belongs to https://bugs.telegram.org/
