### ISSUE TITLE
Add possibility to make screens

### ISSUE THREAD

**Issue by linuxes** [telegramdesktop/tdesktop#2534]
Hi, i wonder if you guys implement feature as has "uTox", you choose to make screen of part of your's desktop, it makes a capture and then send it to your opened chat

### Expected behaviour
Click on capture a screenshot, select area, send that (just by 2clicks)

### Actual behaviour
I can make screen, (cut image if i want screen just a part of my desktop), save it, open telegram, send it to chat

### Configuration
Linux preffered :D

Thanks for your reading time ^^

**Comment by matteoalessiocarrara** [comment]
The Unix philosophy says DOTADIW, do one thing and do it well: this is not the task of telegram. First of all I think a cross-platform implementation would be complicated. In addition, the redundancy is the evil: heavier application, more bugs, and less time to innovate :(

**Comment by matteoalessiocarrara** [comment]
On linux you can configure a shortcut to create a screenshot, then send it on telegram via the "recent" option in the gtk file selector. Take a look at the xfce4-screenshoter manual.

**Comment by matteoalessiocarrara** [comment]
I noticed right now that has an option to copy the screenshot to the clipboard! So just create a shortcut to xfce4-Screenshoter, then ctrl-v on telegram and will propose to send the image.

**Comment by Peque** [comment]
Yeah, in Gnome Shell you can just "Control + Mayus + Print" to take a screenshot of an area to the clipboard. Then "Control + V" to send in, as @matteoalessiocarrara mentions.

**Comment by stek29** [comment]
<kbd>⌘</kbd> <kbd>⇧</kbd> <kbd>Ctrl</kbd> <kbd>4</kbd> on OSX btw.
