### ISSUE TITLE
the part of the avatar is cut off from the bottom when new features from the premium subscription are used

### ISSUE THREAD

**Issue by evsiukovn** [telegramdesktop/tdesktop#25354]
### Steps to reproduce

1) use "ABC emoji" from premium version, write short text to one line
2) scroll to bottom
3) chat must be filled for reproduce

### Expected behaviour

the avatar is displayed in full, there is an additional indentation at the bottom for this

### Actual behaviour

![изображение](https://user-images.githubusercontent.com/74744018/202032361-34f6059f-bc24-4806-a2d1-c4b83330f2f3.png)

### Operating system

win 10 

### Version of Telegram Desktop

4.3.1 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Thanks! I'll fix this in the next version.
