### ISSUE TITLE
There is no sound when calling in telegram

### ISSUE THREAD

**Issue by fleimink** [telegramdesktop/tdesktop#25355]
### Steps to reproduce

I can not hear the interlocutor in the telegram

### Expected behaviour

When the interlocutor called, you could hear

### Actual behaviour

Can't hear the interlocutor

### Operating system

Fedora 37

### Version of Telegram Desktop

4.3.1

### Installation source

Flatpak

**Comment by fleimink** [comment]
When calling, the interlocutor is not heard in the telegram*

**Comment by ilya-fedin** [comment]
I heard Fedora 37 got a regression in pulseaudio compatibility, so you have to wait until they fix that

**Comment by fleimink** [comment]
There was an update, everything worked
