### ISSUE TITLE
[Feature Request] show auto-delete duration in private chats/groups/bots

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#25351]
### Is your feature request related to a problem?

Telegram on android shows auto-delete duration in private chats/groups/bots, i think telegram desktop should too.
![изображение](https://user-images.githubusercontent.com/5204968/201927187-df617477-7623-4444-aa8c-7d2600fb25dc.png)

### Describe the solution you'd like

Showing auto-delete duration inside profile picture.

### Describe alternatives you've considered

Not having this feature.

**Comment by RememberTheAir** [comment]
For some reason telegram desktop shows it inside the input box:

![image](https://user-images.githubusercontent.com/16143208/201935910-9a855b16-19ff-4c23-8523-52e093dc1178.png)

**Comment by john-preston** [comment]
It will be in the next release.
