### ISSUE TITLE
[Feature Request] Ability to choose audio input / output device.

### ISSUE THREAD

**Issue by VasyaPupkins** [telegramdesktop/tdesktop#25350]
### Is your feature request related to a problem?

Inability to route Telegram input / output in systems with multiple audio devices or complex audio routing setups.

### Describe the solution you'd like

Ability to choose / override system default audio input / output device.

### Describe alternatives you've considered

Ability to choose / override system default audio input / output device.

**Comment by Aokromes** [comment]
17610  gives 404 for me, maybe reporterer is banned.

**Comment by ilya-fedin** [comment]
Oops, it's #16710

**Comment by Aokromes** [comment]
maybe we replace that with this.

**Comment by ilya-fedin** [comment]
Ideally I'd rename this issue to have separate one for input, but since we can't do that, that seem to be the best choice, yeah

**Comment by nyakze** [comment]
I really need an option to make Telegram respect default communication device, instead of choosing a device manually all the time. All other apps I use for communication use a default communication device, why not Telegram?

**Comment by ilya-fedin** [comment]
Well, there's no such API in the underlying library Telegram uses for audio output/input (https://github.com/kcat/openal-soft) and even if it was, people were constantly creating issues like "doesn't respect default device" or "doesn't respect ducking settings" back in the time when libtgvoip was used for calls which was using default communication device (as it has custom platform audio implementations).

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v4.14.10 is ok for you?

**Comment by nyakze** [comment]
Looks nice! I think that the default option should be to use the same for calls. An option to respect a Windows "default communication device" would also be welcome, if at all possible.
