### ISSUE TITLE
No sound on Fedora 37

### ISSUE THREAD

**Issue by proninyaroslav** [telegramdesktop/tdesktop#25363]
### Steps to reproduce

1. Send a video or voice message. Or open someone's video or voice message
2. Play a video/voice message, try to listen it

### Expected behaviour

The sound should play

### Actual behaviour

The video plays but there is no sound. Voice message isn't playing, it's time progress is stagnant. I ran into this after updating from Fedora 36 to 37.

### Operating system

Fedora Linux 37, GNOME 43

### Version of Telegram Desktop

4.3.1

### Installation source

Flatpak

### Logs

```shell
[ALSOFT] (EE) Failed to set real-time priority for thread
```

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25355
