### ISSUE TITLE
[Feature Request] Style multiple-select polls differently

### ISSUE THREAD

**Issue by septatrix** [telegramdesktop/tdesktop#25367]
### Is your feature request related to a problem?

Often polls may be phrased ambiguously and it is not clear whether they are single- or multiselect.
This can lead to confusing. If I select the first option with the expectation that I can select more options I must now revoke my submission, think about it again and then select the most fitting option.

While this is sometimes the result of a badly authored poll, this must not be the case and the experience can in general be improved.

### Describe the solution you'd like

Styling similar to the web would be ideal as it is already something most people are used to: radio for single select and checkboxes for multiselect

### Describe alternatives you've considered

Another indicator could be used, e.g. directly beneath the poll header. However radio and checkbox inputs are already widely used and do not require additional space.

### Additional context

I guess this request could also be made about polls with quiz-mode enabled as votes cannot be retracted for those though one might argue that hiding this information is actually wanted and I personally have no preference in regards to this. Also I rarely encounter quizzes whereas the confusing between single- and multiselect is something bothering me more frequently.

**Comment by ilya-fedin** [comment]
This is not a place to suggest design changes, use https://t.me/design

**Comment by RememberTheAir** [comment]
Why linking @designers for issues about style suggestions? It's a channel that links a bot in its bio, and if you want to suggest an UI change you are supposed to provide a mockup. For UI suggestions that would break consistency across platforms and would require a change in all clients, it makes more sense to link https://suggestions.telegram.org
