### ISSUE TITLE
[Question] why premium connected accounts limit lower that in telegram for android (direct version)?

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#25361]
Telegram desktop version limits:
![Снимок экрана 2022-11-16 150356](https://user-images.githubusercontent.com/5204968/202188903-43d455bc-cb96-431a-87df-d49bf323174f.png)

Telegram for android from official site (https://telegram.org/android): 
![Screenshot_20221116-150447_Nekogram_reiszed](https://user-images.githubusercontent.com/5204968/202188990-afb7ca7c-ae46-426e-99d5-d1f217b323c4.jpg)

**Comment by 23rd** [comment]
Can't reproduce.

https://github.com/DrKLO/Telegram/blob/0e17caa7a6facd8220077ee708c4acc942a175d1/TMessagesProj/src/main/java/org/telegram/messenger/UserConfig.java#L29

**Comment by soredake** [comment]
> Can't reproduce.
> 
> https://github.com/DrKLO/Telegram/blob/0e17caa7a6facd8220077ee708c4acc942a175d1/TMessagesProj/src/main/java/org/telegram/messenger/UserConfig.java#L29

Why 4 and not 8 like in mobile app?

**Comment by 23rd** [comment]
This source code belongs the Telegram for Android.

**Comment by soredake** [comment]
You're right, it's only 4 in android version,  turns out my client (Nekogram) have higher limit.
