### ISSUE TITLE
[Feature] less appropriate to use the attachment icon

### ISSUE THREAD

**Issue by 14113003** [telegramdesktop/tdesktop#2536]
### Steps to reproduce
1. Click in camera icon
2. Select the camera icon to upload an image file format.
3. Or select the attachment icon to upload an all file format.

### Expected behaviour
Tell us what should happen
I think a camera icon is to upload an image file format only.

### Actual behaviour
Tell us what happens instead
1. Application gives me two choices : 
- The camera icon to upload an image file format.
- The attachment icon to upload an all file format.

###Suggestion
1. This application is good, but it would be better if the application can separate the image upload feature and file upload feature.
or
2. then the application would be better to use as an attachment icon on the pop-up menu instead of using the image icon, because the attachment file also includes image file.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
0.10.11

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by john-preston** [comment]
I didn't understand the bug report, sorry.

**Comment by 14113003** [comment]
This is not a bug.
This is a problem on the display used by the end user.
I thought the problem was solved. 
The Interface has changed.
Thanks.
