### ISSUE TITLE
Message corrupt when adding an emoji right after a word

### ISSUE THREAD

**Issue by JasonRammoray** [telegramdesktop/tdesktop#25365]
### Steps to reproduce

1. Type "Hello" into the "Write a message..." section
2. Press Ctrl + Cmd + Space to invoke an emoji selection dialog
3. Paste the red heart emoji ❤️

### Expected behaviour

The message section should display "Hello❤️".

### Actual behaviour

The message section renders a rectangle instead.
<img width="132" alt="image" src="https://user-images.githubusercontent.com/5477500/202386801-1b46ccc8-acba-4887-a335-67c63655122c.png">

### Operating system

macOS Monterey 12.6.1

### Version of Telegram Desktop

4.3.1

### Installation source

Static binary from official website

**Comment by JasonRammoray** [comment]
The issue is still reproducible in Telegram Desktop [4.8.1](https://desktop.telegram.org/changelog#v4-8-1-24-04-23).

**Comment by JasonRammoray** [comment]
Unable to reproduce the issue in Telegram Desktop 4.11.8 on macOS.

**Comment by Aokromes** [comment]
and this is why slate bot is needed :)
