### ISSUE TITLE
[Feature Request] Propose wildcard search capabilities that can troubleshoot Asian character search

### ISSUE THREAD

**Issue by amblerkr** [telegramdesktop/tdesktop#25369]
### Is your feature request related to a problem?

https://github.com/telegramdesktop/tdesktop/issues/10179
https://github.com/telegramdesktop/tdesktop/issues/7096
https://bugs.telegram.org/c/724

My suggestion
https://bugs.telegram.org/c/21902

---

Telegram is disadvantageous for Korean search. 
A word is transformed into several forms. 
'조사: 은, 는, 이, 가, 을, 를'. 
조사 wikipedia: https://en.wikipedia.org/wiki/Korean_postpositions

example)
"텔레그램이 트위터의 대안입니다." 
"카카오톡은 기능 면에서 텔레그램을 따라갈 수 없습니다."
"텔레그램을 트위터 대신 사용합니다."

Search: 텔레그램
Result: 0

Search: 트위터
Result: 1
"텔레그램을 트위터 대신 사용합니다."

Search: 카카오톡
Result: 0

This is a big barrier for Koreans to come over from KakaoTalk, a Korean messenger. 
Koreans know that Telegram is superior in functionality, but they cannot move to Telegram because the search does not work properly.

I suggest a wildcard search here.

### Describe the solution you'd like

You can use this method to improve functionality. 
'~Keyword Search'
I'll call it a 'Wildcard Search'.

example)
"텔레그램이 트위터의 대안입니다." 
"카카오톡은 기능 면에서 텔레그램을 따라갈 수 없습니다."
"텔레그램을 트위터 대신 사용합니다."

Search: ~텔레그램
Result: 3
"텔레그램이 트위터의 대안입니다." 
"카카오톡은 기능 면에서 텔레그램을 따라갈 수 없습니다."
"텔레그램을 트위터 대신 사용합니다."

Search: ~트위터
Result: 2
"텔레그램이 트위터의 대안입니다." 
"텔레그램을 트위터 대신 사용합니다."

Search: ~카카오톡
Result: 1
"카카오톡은 기능 면에서 텔레그램을 따라갈 수 없습니다."

### Describe alternatives you've considered

**'~Keyword Search'**

**It is contians of data filtering method.**
Displays the results if the keyword is included in the full text.

### Additional context
See How to Filter Data.
![image](https://user-images.githubusercontent.com/67187038/202654067-5b07cc00-b491-4372-a592-35a4c737aa35.png)

Support advanced search. I like the advanced search on Twitter.
https://www.labnol.org/internet/twitter-search-tricks/13693/

It will help you solve the Chinese search.
https://github.com/fxsjy/jieba

**Comment by Aokromes** [comment]
it continues to be api issue.
