### ISSUE TITLE
Missing icon on Flathub

### ISSUE THREAD

**Issue by delight-aug** [telegramdesktop/tdesktop#25378]
### Steps to reproduce

The Telegram icon is missing on the Flathub store. The same goes for when GNOME Software displays Flathub verison

![image](https://user-images.githubusercontent.com/51861383/202837360-6c5ebd78-b3ed-4677-a616-0277850b8e4a.png)

### Expected behaviour

Have an icon on the Flathub store

### Actual behaviour

No icon

### Operating system

Fedora 37, GNOME 43

### Version of Telegram Desktop

4.3.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Yeah, sadly I have no idea how to fix this
