### ISSUE TITLE
telegra.ph links dont work on desktop browsers on windows

### ISSUE THREAD

**Issue by rp1231** [telegramdesktop/tdesktop#25379]
### Steps to reproduce

Click on any telegra.ph link from the telegram desktop app.
The link will open in the browser, but the article wont load and I get an ERR_CONNECTION_RESET error.
Have tried this with multiple browsers.
The only browser that it works on sometimes is naver whale which is chromium based, but even on that, it works unreliably and the article displays only sometimes.

### Expected behaviour

The article should display and not show the ERR_CONNECTION_RESET error

### Actual behaviour

The article does not load and shows the ERR_CONNECTION_RESET error

### Operating system

Windows 11 22H2

### Version of Telegram Desktop

v4.2.4 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Sounds like your provider has bad connectivity with Telegraph servers

**Comment by Aokromes** [comment]
can you try opening the pages with copy url and paste on browser instead?

**Comment by ilya-fedin** [comment]
I hope you understand tdesktop can't influence whether you can open telegra.ph or not

**Comment by Aokromes** [comment]
> Ok, I'll try contacting my ISP then. Thanks

more than isp. i sugest you to try a linux live dvd and test telegram there.
