### ISSUE TITLE
Telegram Crash

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#2537]
When the focus is not on the Telegram software and someone message me, the notification pops up in windows 10 and when I want to click on telegram software it crashes.

**Operating system:**
Microsoft windows 10 64 bit

**Version of Telegram Desktop:**
0.10.11

### Logs
[log_19_15.txt](https://github.com/telegramdesktop/tdesktop/files/534250/log_19_15.txt)
[log_19_30.txt](https://github.com/telegramdesktop/tdesktop/files/534251/log_19_30.txt)
[mtp_19_15.txt](https://github.com/telegramdesktop/tdesktop/files/534255/mtp_19_15.txt)
[mtp_19_30.txt](https://github.com/telegramdesktop/tdesktop/files/534254/mtp_19_30.txt)
[tcp_19_15.txt](https://github.com/telegramdesktop/tdesktop/files/534253/tcp_19_15.txt)
[tcp_19_30.txt](https://github.com/telegramdesktop/tdesktop/files/534252/tcp_19_30.txt)

**Comment by john-preston** [comment]
When you launch the app next time (after the crash) does it ask you to send a crash report?

**Comment by amiremami** [comment]
I have to close it with task manager, and no it does not ask to send crash report. If I disable desktop notifications, it won't crash.

**Comment by john-preston** [comment]
I see. It is named "freezes" / "hands", not "crashes". Please try out the latest alpha version from the bottom of https://desktop.telegram.org/#alpha-version page. It disables windows native notifications by default (they freeze), but gives some nice features to the custom telegram notifications instead :)

**Comment by amiremami** [comment]
Oops sorry man about wrong phrase and thank you so much <3
