### ISSUE TITLE
Can't see new posts in chats

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25384]
### Steps to reproduce

1. Use Telegram for a while and read comments in channels
2. Then go to any channel that you already visit (https://t.me/mudak example) and press "View discussion"
3. You will find yourself somewhere in the middle of the chat, and when you click on the arrow to go to the most recent comments - you will not go to them

Just look at the video:

https://user-images.githubusercontent.com/39812401/202857225-cd843383-207e-4a81-88e0-bd1e72d6d49e.mp4

### Expected behaviour

When I click on the arrow with the number of new messages - I must go to the newest messages and read them all

### Actual behaviour

When I click on the arrow with the number of new messages - I read only ~100 new messages and after few clicks get a "flood wait".

### Operating system

Windows 10

### Version of Telegram Desktop

4.3.1

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
4.5 issue is still here


<details>
  <summary>Video</summary>

  https://user-images.githubusercontent.com/39812401/210095761-d16b0988-1f4a-4d86-8488-1df2e1809f5c.mp4

  
</details>

**Comment by john-preston** [comment]
I can reproduce the unread counter, but not those strange jumps to the bottom of the loaded part :(

I've added some extra debug logs for the next version, I think it'll be beta version 4.5.4 later today.

Can you please reproduce it once again there and after several such jumps (four / five) save the DebugLogs/log_XX_YY.txt file and send it to me at t.me/preston? It should have various "JumpToEnd(...): ..." lines.

**Comment by Neurotoxin001** [comment]
Ok I will wait beta version
