### ISSUE TITLE
[Feature Request] show auto-delete duration in channels

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#25387]
### Is your feature request related to a problem?

Telegram on android shows auto-delete duration in channels 
![ddddd](https://user-images.githubusercontent.com/5204968/202870745-3d1fddfe-9a97-47e4-a4ff-d598b009057a.jpg)

### Describe the solution you'd like

Showing auto-delete duration inside profile picture.

### Describe alternatives you've considered

Not having this feature.

**Comment by ilya-fedin** [comment]
#25351

**Comment by soredake** [comment]
> #25351

This bug report is about channels, which don't have chat.

**Comment by john-preston** [comment]
@soredake should be in the latest releaes (4.4.1).
