### ISSUE TITLE
File chooser dialogs are open behind the Telegram window and unfocused

### ISSUE THREAD

**Issue by delight-aug** [telegramdesktop/tdesktop#25389]
### Steps to reproduce

1. Open a Telegram chat
2. Press the attachment icon to open a file chooser dialog OR press the "Save as" button on some media

### Expected behaviour

The file chooser should open in front of the user, on top of the Telegram window, with an active focus.

### Actual behaviour

The file chooser dialog opens behind the Telegram window with no focus, leaving the user looking at the unresponsive Telegram window.

### Operating system

Fedora 37, GNOME 43

### Version of Telegram Desktop

4.3.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
This is a long-standing bug of xdg-desktop-portal-gtk and xdg-desktop-portal-gnome backends
https://github.com/flatpak/xdg-desktop-portal-gtk/issues/306
https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/16
