### ISSUE TITLE
[Feature Request] Timeout option for TDesktop's own notifications

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#2538]
### Expected behaviour
There should be little timeout (~5 seconds) or even configurable timeout for TDesktop's own notifications.

### Actual behaviour
In most cases notifications seem to be shown for infinite amount of time, which is annoying when you watch films or just don't want to answer message.

### Configuration
**Operating system:** Windows 10 LTSB x64 (Non-anniversary update)
**Version of Telegram Desktop:** 0.10.13 alpha

**Comment by john-preston** [comment]
@Kondra007 They have timeout of 3 seconds after any input event (like mouse movement or keyboard button pressed systemwide). If no input events are generated it is assumed that you're not at the computer at the moment and they stay till there's some input event.

**Comment by Kondra007** [comment]
@john-preston All right, I'll take my mouse with me when I stream films from PC :)

**Comment by john-preston** [comment]
@Kondra007 It would be better to have some way to disable them while you stream movies anyway :( Even hiding in several seconds notifications above a movie should be really annoying.

**Comment by Kondra007** [comment]
@john-preston Fair enough. I personally don't mind seeing notification for several seconds, but you're still completely right.

**Comment by stek29** [comment]
Won't quiet hours solve it?

**Comment by Kondra007** [comment]
@stek29 You're right. However, not everyone has Windows 10 :)
