### ISSUE TITLE
Desktop icon not displayed anymore in AppStream metainfo

### ISSUE THREAD

**Issue by AsciiWolf** [telegramdesktop/tdesktop#25382]
### Steps to reproduce

See for example https://flathub.org/apps/details/org.telegram.desktop or open GNOME Software / KDE Discover (on a system with Flathub enabled) and search for Telegram.

### Expected behaviour

The correct desktop icon should be displayed.

### Actual behaviour

There is no icon displayed anymore in the AppStream metadata.

### Operating system

Fedora 37

### Version of Telegram Desktop

4.3.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
#25378

**Comment by AsciiWolf** [comment]
Oops! :-)
