### ISSUE TITLE
[Feature Request] Sotring Contacts by surname in addition to name

### ISSUE THREAD

**Issue by hooddy** [telegramdesktop/tdesktop#25386]
### Is your feature request related to a problem?

I need option to sort Contatcs by surname in every Telegram client - desktop and mobile.

### Describe the solution you'd like

Add surname sorting.

### Describe alternatives you've considered

I forced to named my Contacts as Surname in Name filed and Name in surname field. Its infrustrates me and brokes Contacts and dialer behaviour.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
