### ISSUE TITLE
Handsfree microphone isn't used after profile switch

### ISSUE THREAD

**Issue by sh7dm** [telegramdesktop/tdesktop#25394]
### Steps to reproduce

0. Have PipeWire + WirePlumber setup with Bluetooth profile autoswitching enabled (default on current Fedora)
1. Connect Bluetooth headphones
2. Make a call
3. Check audio connections

### Expected behaviour

Telegram uses handsfree microphone (mono input stream)

### Actual behaviour

Telegram listens for a stereo stream and gets routed to laptop internal stereo microphone. Needs to be manually switched to make use of headset mic

### Operating system

Fedora 36 KDE

### Version of Telegram Desktop

Flatpak 4.3.1

### Installation source

Flatpak

### Logs

```shell
Note: this might be needed to be resolved at PipeWire/WirePlumber side. If it is so, ask me.
```

**Comment by ilya-fedin** [comment]
Not quite sure, what should we do to fix this? Note we don't have pipewire API experts and are using a cross-platform audio library called OpenAL.

**Comment by sh7dm** [comment]
Does Telegram explicitly ask for a stereo stream from microphone?

**Comment by ilya-fedin** [comment]
Here's what tdesktop asks OpenAL for: https://github.com/desktop-app/lib_webrtc/blob/9b11599c3c56047cfa4c68b69f1fcc93b602c33a/webrtc/details/webrtc_openal_adm.cpp#L526-L530
I don't know what OpenAL asks pipewire for actually.

**Comment by sh7dm** [comment]
`MONO16`. Thank you, I'll try to debug this and likely fix on PipeWire side. Probably this issue should be kept open to avoid duplicates.

**Comment by ilya-fedin** [comment]
It likely works via pulseaudio or jack compatibility layer (openal prefers jack whenever possible) as openal version in flatpak freedesktop runtime doesn't support pipewire natively

**Comment by sh7dm** [comment]
Uses PA protocol for me

**Comment by ilya-fedin** [comment]
> Probably this issue should be kept open to avoid duplicates.

People create duplicates even if the same issue is open and the latest in the list...

**Comment by sh7dm** [comment]
Appears to have been fixed
