### ISSUE TITLE
Window decorations not an option under Wayland.

### ISSUE THREAD

**Issue by 3laws** [telegramdesktop/tdesktop#25391]
### Steps to reproduce

1. In X.org session enable `Use System Window Frame ` (it works)
2. Switch to Wayland (option does not show up)

### Expected behaviour

`Use System Window Frame` option should be available.

### Actual behaviour

`Use System Window Frame` missing

### Operating system

Fedora 37, Wayland, GNOME 43 (mutter 43.1).

### Version of Telegram Desktop

4.3.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
It's not an option because GNOME doesn't provides them
https://gitlab.gnome.org/GNOME/mutter/-/issues/217

**Comment by 3laws** [comment]
@ilya-fedin didn't know, thanks for linking that issue.

**However**, can you explain what's going on here then? Same distro and binary source:

![Screenshot from 2022-11-20 16-36-52](https://user-images.githubusercontent.com/4267075/203015063-5fb2d123-4407-49cc-ac5e-4f1d45c83cfa.png)

Not seeing the spectated behaviour on this one:

![image](https://user-images.githubusercontent.com/4267075/203016494-77797d30-80b0-4c55-b034-b313b23c1de5.png)

**Comment by ilya-fedin** [comment]
Telegram on first screenshot is likely running via Xwayland
