### ISSUE TITLE
[Feature Request] When running inside sandbox, hide "Telegram folder in system «Downloads»" option for storage path

### ISSUE THREAD

**Issue by septatrix** [telegramdesktop/tdesktop#25390]
### Is your feature request related to a problem?

The "Telegram folder in system «Downloads»" option for the target location of downloaded files is nonsensical in sandboxed environments like flatpak. Its existence causes confusion und selecting it can result in unexpected behaviour.

### Describe the solution you'd like

The option should be hidden when the app detects that it is running inside e.g. Flatpak (and probably also Snap).

### Describe alternatives you've considered

* The option could still be shown but grayed out, or a warning could be shown upon selecting it. Hiding it, however, seems easiest.
* The option could be removed completely and only the internal opaque directory as well as the custom directory be left. If the custom directory could default to `~/Downloads/Telegram Desktop` this might not even as bad of an idea.

### Additional context

Ideally this would be implemented such that it would also be hidden if permissions to write inside the download directory are missing (even though it may not be running inside the usual sandboxes) and be shown if it is running inside these sandboxes but the directory can actually be written to (if e.g. the user adjusted sandbox settings using Flatseal or similar methods for Snap).

**Comment by gabriele2000** [comment]
So that's thanks to this that Telegram can't write to ~/Downloads anymore?
NICE

**Comment by septatrix** [comment]
Being passive aggressive does not help anyone and certainly won't make the maintainers respect you and invest their free time for you.

What you are referring to is due to https://github.com/flathub/org.telegram.desktop/commit/e1a0bb0f2ac3937245bf055b2eeb38725c619fd6 and the maintainers already told me that they are unlikely to revert it (as they try to reduce permissions as much as possible).

**Comment by gabriele2000** [comment]
> Being passive aggressive does not help anyone and certainly won't make the maintainers respect you and invest their free time for you.

I didn't mean to sound rude, but I just discovered the culprit of the problem and I had to search it... if something works why break it?
Couldn't they just wait and test it more before trying to "remove useless things" that are actually useful?
At least, give a warning that this doesn't work because of X feature being removed.

> What you are referring to is due to [flathub/org.telegram.desktop@e1a0bb0](https://github.com/flathub/org.telegram.desktop/commit/e1a0bb0f2ac3937245bf055b2eeb38725c619fd6) and the maintainers already told me that they are unlikely to revert it (as they try to reduce permissions as much as possible).

Good, but they're breaking stuff without even trying to advertise that they're breaking stuff... I literally had to search this thing up because it's not even so easy to find this problem... I don't know, pin the issue, make it visible...

**Comment by ilya-fedin** [comment]
> Ideally this would be implemented such that it would also be hidden if permissions to write inside the download directory are missing (even though it may not be running inside the usual sandboxes) and be shown if it is running inside these sandboxes but the directory can actually be written to (if e.g. the user adjusted sandbox settings using Flatseal or similar methods for Snap).

I'm currently looking in a more smart detection and sadly just checking whether the directory is writable doesn't seem to be reliable. E.g. Flatpak has read-write tmpfs environment, so a check whether we can create the directory will pass. On other hand, just checking whether the directory already exists and is writable will lead to false-positives in most lightweight environments (no xdg-user-dirs to pre-create the directory). So, the only safe way seem to check whether we're inside sandbox + whether the directory exists and is readable. Qt doesn't seem to provide API to check whether the directory is writable. And I'm not sure that's really possible without trying to create a file what is awful (I suspect checking Unix permissions won't work whenever they're present, but the directory is mounted read-only or AppArmor denies the access, what is the way to control that in sandboxes).

But there will be a check whether a custom directory is not readable in sandbox to reset the setting to default.

**Comment by ilya-fedin** [comment]
> Good, but they're breaking stuff without even trying to advertise that they're breaking stuff...

Because the stuff is not broken, the chooser asks you once where to download and the download starts.

**Comment by septatrix** [comment]
> I didn't mean to sound rude, but I just discovered the culprit of the problem and I had to search it...

The "NICE" seemed rather sarcastic but I don't want to insinuate that it was written with bad intent.

> I'm currently looking in a more smart detection [...]

Based on your investigation that all does sound rather tedious and imprecise. Maybe asking on Stackoverflow or some mailinglists might yield a bit more information? It would have guessed that Flatpak, Snap and also the AppArmor profiles would allow for better querying of ones permissions...

**Comment by ilya-fedin** [comment]
> It would have guessed that Flatpak, Snap and also the AppArmor profiles would allow for better querying of ones permissions...

I guess it's possible to query /proc/mounts and the AppArmor APIs, but that would mean a lot of code and linking to more third-party for almost no gain.

**Comment by gabriele2000** [comment]
> > Good, but they're breaking stuff without even trying to advertise that they're breaking stuff...
> 
> Because the stuff is not broken, the chooser asks you once where to download and the download starts.

On every file? Oh, so if the behaviour is completely different BUT Telegram doesn't crash anymore like two weeks ago, it's suddenly fine?
No, it's not "working" since I even tried to set another folder and Telegram still asked for EVERY file to be manually saved.
This stuff needs to be tested before removing features, this is not GNOME, this is Telegram.

**Comment by ilya-fedin** [comment]
> On every file?

No, it asks only once if you choose the folder. If you press cancel then of course it will pop up again as it still has no permissions.

**Comment by gabriele2000** [comment]
> The "NICE" seemed rather sarcastic but I don't want to insinuate that it was written with bad intent.

I didn't want to sound rude, I'm sorry.
That "NICE" was indeed sarcastic, because I thought it was a problem with my OS, since I thinker a lot and I don't have time to check every piece of update and stuff like that.
Since snap telegram gave me issues, I switched to flatpak Telegram, faster opening, faster updates and completely integrated in my "update" alias.

When I discovered that this change was deliberate, I was indeed pissed off, because it was made consciously and it's the reason why I have to save everything manually now.
It's a minor inconvenience, that's all.

**Comment by ilya-fedin** [comment]
> This stuff needs to be tested before removing features, this is not GNOME, this is Telegram.

Telegram sadly has no alpha testers for Linux. Because the market share is just too small I guess. When I tested while implementing, I found no bugs of course or I would just not push it.

**Comment by gabriele2000** [comment]
> > On every file?
> 
> No, it asks only once if you choose the folder. If you press cancel then of course it will pop up again as it still has no permissions.

So I guess the behaviour was actually partially corrected... I tested days ago and it asked on every file.
Thanks for the heads-up.

**Comment by ilya-fedin** [comment]
What you say as "every file" is probably the recursive calling of the chooser bug, but it was the cause of the crash, so it couldn't be on a version that doesn't crash :thinking:

**Comment by gabriele2000** [comment]
> What you say as "every file" is probably the recursive calling of the chooser bug, but it was the cause of the crash, so it couldn't be on a version that doesn't crash thinking

When I displayed a new file, the chooser would pop-up.
I have to confirm if choosing manually the "telegram download" folder corrects the behaviour and restores it to the default one.

**Comment by ilya-fedin** [comment]
It seems I wasn't right and in practice with snap even QDir::exists and QDir::isReadable checks return true if the directory is exists on host, but the access is denied. So no smart check is possible, unforutnately. Apparently AppArmor filter actual read/write calls, but not stat.

**Comment by ilya-fedin** [comment]
Ok, std::filesystem::directory_iterator seem to actually work, it's a pity there's no way to get the error while getting directory listing in Qt
