### ISSUE TITLE
Minimal player for videos make forced close

### ISSUE THREAD

**Issue by avisadius** [telegramdesktop/tdesktop#25396]
### Steps to reproduce

opening a video at telegram (not scope)
then click on minimal player

### Expected behaviour

there must be fine at telegram 4.2.4, video pop up has minimalized as usually

### Actual behaviour

i just playing video using telegram and when i tap on minimal play, the telegram app just forced close

### Operating system

Ubuntu 22.04.1

### Version of Telegram Desktop

4.3.1

### Installation source

Flatpak

**Comment by mukkumayc** [comment]
I have the same issue.

### Operating system
Arch Linux, core version 6.0.8

### Window manager
dwm

### Version of Telegram Desktop
4.3.1

### Installation source
pacman

### Logs

This shows when I open telegram
```
$ telegram-desktop
qt.svg: Error while inflating gzip file: SVG format check failed
...
qt.svg: Error while inflating gzip file: SVG format check failed
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.svg: Error while inflating gzip file: SVG format check failed
...
qt.svg: Error while inflating gzip file: SVG format check failed
```

This shows when I open video
```
[AVHWDeviceContext @ 0x7fccd7877300] Failed to initialise VAAPI connection: -1 (unknown libva error).
Failed to open VDPAU backend libvdpau_radeonsi.so: cannot open shared object file: No such file or directory
[AVHWDeviceContext @ 0x7fccd7877400] VDPAU device creation on X11 display :0 failed.
[AVHWDeviceContext @ 0x7fccd7877380] cu->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
```

And this shows when I minimize video and the app crashes
```
zsh: segmentation fault (core dumped)  telegram-desktop
```

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25402 ?

**Comment by thansk** [comment]
Already reported in #25383 and others, not an issue with Telegram.
