### ISSUE TITLE
Cannot forward any message

### ISSUE THREAD

**Issue by danyright** [telegramdesktop/tdesktop#254]
I can't forward a message (written by myself or received) using Telegram Desktop.
I get stuck with the attached screen. I then have to press 'Escape' or click in the darkened zone.
![telegram_forwardbug](https://cloud.githubusercontent.com/assets/4611396/5027066/1d838c42-6b2b-11e4-8ae0-df76539e449c.jpg)

I am using tdesktop 0.6.7 on Arch Linux (installed using AUR - https://aur.archlinux.org/packages/telegram-desktop/), with KDE.
The bug is reproducible every time.

Let me know if you need more info.

D

**Comment by Katzen-Gott** [comment]
@danyright you can close the issue youself (there is a button under the comment box 'comment and close')
