### ISSUE TITLE
Telegram is freezing after notification with sound

### ISSUE THREAD

**Issue by AdamB2023** [telegramdesktop/tdesktop#25405]
### Steps to reproduce

Receive notification with sound.

### Expected behaviour

TG shouldn't freeze when receiving notification.

### Actual behaviour

TG freezing when receiving notification with sound on DELL Xps (15 9520 for me). 
https://www.dell.com/community/XPS/Telegram-desktop-application-problem/td-p/8287484
Switching to another sound, or windows notifications, do not help.
The only way to fix it is disabling notification sounds for Telegram.

### Operating system

W11 Home 22H2 22621.819

### Version of Telegram Desktop

4.3.1

### Installation source

Static binary from official website

### Logs

```shell
[2022.11.21 22:46:29] Audio Info: recreating audio device and reattaching the tracks
[2022.11.21 22:46:33] Audio Info: Closing audio playback device.
```

**Comment by ilya-fedin** [comment]
Sounds like a bug in OpenAL library or sound drivers

**Comment by john-preston** [comment]
I can't reproduce that with Dell XPS and TDesktop 4.4.1 on Windows 11, sorry.

**Comment by mtw20** [comment]
> I can't reproduce that with Dell XPS and TDesktop 4.4.1 on Windows 11, sorry.
There's many XPS models, mine is 15 9520 i9, which one you are using?

**Comment by john-preston** [comment]
dell xps 17 latest model, but I'm not sure I can do anything about that if it reproduces on some single model of a laptop :(

**Comment by john-preston** [comment]
Can you provide OpenAL log? For that you need to:

1. Go to Settings and type "debugmode" from the keyboard.
2. Relaunch the app (completely, right click on tray icon and press Quit Telegram).
3. Reproduce the bug.
4. Quit Telegram completely once again.
5. Attach here "last_openal_log.txt" from "DebugLogs" folder near Telegram.exe

**Comment by mtw20** [comment]
May be more than just one device, maybe it's related to driver or other OS part, but didn't experience it on any other app, and same Telegram portable on different device. Here are the logs.
```
[ALSOFT] (II) Initializing library v1.22.0-58dd5078 wasapi_exact_device_time
[ALSOFT] (II) Supported backends: wasapi, dsound, winmm, null, wave
[ALSOFT] (II) Loading config C:\Users\usr\AppData\Roaming\alsoft.ini...
[ALSOFT] (II) Got binary: C:\Users\usr\Desktop\Desktop\Telegrams\POLS34, Telegram.exe
[ALSOFT] (II) Loading config C:\Users\usr\Desktop\Desktop\Telegrams\POLS34\alsoft.ini...
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Vendor ID: ""
[ALSOFT] (II) Name: "12th Gen Intel(R) Core(TM) i9-12900HK"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key rt-time-limit not found
[ALSOFT] (II) Key game_compat/reverse-x not found
[ALSOFT] (II) Key game_compat/reverse-y not found
[ALSOFT] (II) Key game_compat/reverse-z not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (II) Key drivers not found
[ALSOFT] (II) Starting message thread
[ALSOFT] (II) Message thread initialization complete
[ALSOFT] (II) Starting message loop
[ALSOFT] (II) Initialized backend "wasapi"
[ALSOFT] (II) Added "wasapi" for playback
[ALSOFT] (II) Added "wasapi" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (II) Key eax/enable not found
[ALSOFT] (II) Got message "Enumerate Playback" (0x0006, this=0000000000000000, param=0000000000000000)
[ALSOFT] (II) Got device "Speakers (Logi Z207)", "{F009C1CF-DF6D-4EFC-B676-0FC80DEB99C6}", "{0.0.0.00000000}.{f009c1cf-df6d-4efc-b676-0fc80deb99c6}"
[ALSOFT] (II) Got device "Speakers (Realtek(R) Audio)", "{3DFE417E-CD8F-4FD2-A177-AC8D8F3284CB}", "{0.0.0.00000000}.{3dfe417e-cd8f-4fd2-a177-ac8d8f3284cb}"
[ALSOFT] (II) Got device "ROG PG279Q (3 — HD Audio Driver for Display Audio)", "{B09E9D06-430E-4E78-B43D-B088990CD6B6}", "{0.0.0.00000000}.{b09e9d06-430e-4e78-b43d-b088990cd6b6}"
[ALSOFT] (II) Got message "Enumerate Capture" (0x0007, this=0000000000000000, param=0000000000000000)
[ALSOFT] (II) Got device "Microphone (Realtek(R) Audio)", "{B660D1C1-0B7F-4468-BA78-A8EDBB1F548F}", "{0.0.1.00000000}.{b660d1c1-0b7f-4468-ba78-a8edbb1f548f}"
[ALSOFT] (II) Got message "Open Device" (0x0000, this=000001A6E96FF438, param=0000000000000000)
[ALSOFT] (II) Key frequency not found
[ALSOFT] (II) Key sources not found
[ALSOFT] (II) Key slots not found
[ALSOFT] (II) Key sends not found
[ALSOFT] (II) Created device 000001A6F15548B0, "OpenAL Soft on Speakers (Logi Z207)"
[ALSOFT] (II) Key sample-type not found
[ALSOFT] (II) Key channels not found
[ALSOFT] (II) Key ambi-format not found
[ALSOFT] (II) Key period_size not found
[ALSOFT] (II) Key periods not found
[ALSOFT] (II) Key hrtf not found
[ALSOFT] (II) Pre-reset: Stereo, Float32, 44100hz, 882 / 2646 buffer
[ALSOFT] (II) Got message "Reset Device" (0x0002, this=000001A6E96FF438, param=0000000000000000)
[ALSOFT] (II) Requesting playback format:
    FormatTag      = 0xfffe
    Channels       = 2
    SamplesPerSec  = 44100
    AvgBytesPerSec = 352800
    BlockAlign     = 8
    BitsPerSample  = 32
    Size           = 22
    Samples        = 32
    ChannelMask    = 0x3
    SubFormat      = {00000003-0000-0010-8000-00aa00389b71}
[ALSOFT] (II) Post-reset: Stereo, Float32, 44100hz, 882 / 2646 buffer
[ALSOFT] (II) Key stereo-mode not found
[ALSOFT] (II) Key stereo-encoding not found
[ALSOFT] (II) Key cf_level not found
[ALSOFT] (II) Stereo rendering
[ALSOFT] (II) Channel config, Main: 3, Real: 2
[ALSOFT] (II) Allocating 5 channels, 20480 bytes
[ALSOFT] (II) Enabling single-band first-order ambisonic decoder
[ALSOFT] (II) Max sources: 256 (255 + 1), effect slots: 64, sends: 4
[ALSOFT] (II) Key dither not found
[ALSOFT] (II) Key dither-depth not found
[ALSOFT] (II) Dithering disabled
[ALSOFT] (II) Key output-limiter not found
[ALSOFT] (II) Output limiter disabled
[ALSOFT] (II) Fixed device latency: 0ns
[ALSOFT] (II) Got message "Start Device" (0x0003, this=000001A6E96FF438, param=0000000000000000)
[ALSOFT] (II) Post-start: Stereo, Float32, 44100hz, 882 / 2646 buffer
[ALSOFT] (II) Increasing allocated voices to 256
[ALSOFT] (II) Key volume-adjust not found
[ALSOFT] (II) Created context 000001A6EAFA5150
[ALSOFT] (II) Increasing allocated voice properties to 32
[ALSOFT] (II) Got message "Stop Device" (0x0004, this=000001A6E96FF438, param=0000000000000000)
[ALSOFT] (II) Freeing context 000001A6EAFA5150
[ALSOFT] (II) Freed 2 context property objects
[ALSOFT] (II) Freed 0 AuxiliaryEffectSlot property objects
[ALSOFT] (II) Freeing device 000001A6F15548B0
[ALSOFT] (II) Got message "Close Device" (0x0005, this=000001A6E96FF438, param=0000000000000000)
```

**Comment by ilya-fedin** [comment]
> but didn't experience it on any other app

It's not that easy to find an application using OpenAL, so if it's a bug in the library, you won't see it in other applications. It's mostly used by games.

**Comment by ilya-fedin** [comment]
The log looks just fine by the way, so nothing could be done, sorry.

**Comment by mtw20** [comment]
Well, i ended up disabling sounds for now.
Do you know any other apps where i can check if it's OpenAL?
Are there any other logs which i could provide?
The app is unresponsive, so there must be a bottleneck somewhere in the code in a specific scenario,

**Comment by ilya-fedin** [comment]
I don't know any other application using OpenAL, I heard Minecraft uses OpenAL though, I don't know though whether it's true for Windows and whether they use the same version as tdesktop.

Arch Linux has a good list of packages depending on OpenAL, mostly it's games and emulators, the packages should have links to official sites that may have a Windows version. Be aware though most of them depend not only on openal, but on other audio libraries, either platform ones (so they may have an implementation using Windows native API as well) or sdl2_audio, so maybe you will need to choose OpenAL manually in their settings.
https://archlinux.org/packages/extra/x86_64/openal/

**Comment by ohhai** [comment]
Maybe I have same: Telegram desktop sometimes freezes completely on Fedora 37. Not sure about the reasons, but seems like they are related to sound.
Tried to switch sound notifications off but it freezed all the times I tried to save this setting.
Succeeded only after stopping pipewire process.
Both rpmfusion and official static binary (https://updates.tdesktop.com/tlinux/tsetup.4.6.3.tar.xz) are affected.
Might be related: #25939

**Comment by MorganMLGman** [comment]
Hi, I have I think similar problem, 
I am using Dell XPS 9320 and Dell Latitude 5531, both on Windows 11 and problem occurs on both devices.
Issue also occurred on my previous laptop HP Pavilion X360 with Fedora 36.

Telegram freezes for 1 - 2 seconds when receiving new notification and the issue is the most noticeable when I am using BT headphones.

**Comment by ZakharYA** [comment]
I have a matebook 14s 11370h and when I get a notification with sound it freezes for a couple seconds.

**Comment by VadVergasov** [comment]
I have same issue on different setups:
MacBook Pro 16 M2
Lenovo ThinkPad X1 Carbon 6th gen
Asus ROG Strix Scar II GL704GV

Turned sound off and issue disappears. Maybe you should get more logs to try fix such issue?

**Comment by ilya-fedin** [comment]
Logs won't help, it perhaps should be profiled to find which call takes the itme
