### ISSUE TITLE
Incorrect restriction on account phone number

### ISSUE THREAD

**Issue by j-ds-au** [telegramdesktop/tdesktop#25406]
Telegram is able to support accounts being associated with a landline phone number (or a mobile phone number, of course), sending verification codes to such numbers as an audio message.

However, Telegram Desktop does not accept landline phone numbers being entered for login, saying that these are invalid (at least, that is the case for country code +61 with area code 2).

Telegram Desktop needs to support the same range of phone numbers as Telegram, ie. including landline numbers.

**Comment by john-preston** [comment]
I think any number entered in TDesktop is sent to the server and only if it replies with an error an error is shown. You can try submitting such a phone number and then upload log.txt to see the error.
