### ISSUE TITLE
Bug with pinned message separator

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#2540]
### Steps to reproduce
1. Open Telegram Desktop.
2. Switch to channel with pinned message.
3. Switch to channel without pinned messages.

### Expected behaviour
Pinned msg line should be hidden.

### Actual behaviour
![tgbug](https://cloud.githubusercontent.com/assets/966711/19489275/65860866-958c-11e6-90d0-3f49e6d3638f.png)

### Configuration
**Operating system:** Fedora 24

**Version of Telegram Desktop:** 0.10.14 alpha

**Comment by john-preston** [comment]
@xvitaly Should be fixed in 0.10.15 alpha.
