### ISSUE TITLE
Crash when opening gif avatar

### ISSUE THREAD

**Issue by ho-229** [telegramdesktop/tdesktop#25407]
### Steps to reproduce

Opening gif avatar

### Expected behaviour

Open the avatar normally

### Actual behaviour

Stuck and then crashed

### Operating system

Manjaro 22.0.0 Sikaris KDE (X11)

### Version of Telegram Desktop

4.3.1

### Installation source

Other (unofficial) source

### Logs

telegram stdout:

```txt
qt.svg: Error while inflating gzip file: SVG format check failed
...
qt.svg: Error while inflating gzip file: SVG format check failed
[libvpx-vp9 @ 0x7f116d439100] v1.12.0
[libvpx-vp9 @ 0x7f116d439100] v1.12.0
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
fish: Job 1, 'telegram-desktop' terminated by signal SIGSEGV (Address boundary error)
```

gdb:
```txt
...
Thread 51 "telegram-deskto" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbc2376c0 (LWP 95111)]
0x00007ffff7467874 in XDisplayString () from /usr/lib/libX11.so.6
...
```

**Comment by Aokromes** [comment]
plz try downloading official version from https://desktop.telegram.org

**Comment by ho-229** [comment]
problem is solved, thanks
