### ISSUE TITLE
Archived chats fold abnormal display

### ISSUE THREAD

**Issue by PFCraft-box** [telegramdesktop/tdesktop#25413]
### Steps to reproduce

1. Archive any chat message
2. Right click "Archived chats" and select collapse

### Expected behaviour

![photo_2022-11-22_23-39-54](https://user-images.githubusercontent.com/47564241/203356838-8ac1073a-f6a2-4faa-918a-29448e5435cc.jpg)

### Actual behaviour

![photo_2022_11_22_234221](https://user-images.githubusercontent.com/47564241/203357462-e6078a17-afe1-47d3-b2de-c7d75d732fb9.png)

### Operating system

Windows 22H2 19045.2251

### Version of Telegram Desktop

4.3.2

### Installation source

Static binary from official website

**Comment by sarseev** [comment]
Same issue, reinstall did not help.

**Comment by d-Rickyy-b** [comment]
I am experiencing the same issue - also on 4.3.2.

https://user-images.githubusercontent.com/5798157/203389131-61c1d959-f631-41f7-a133-88ad587e7e7d.mp4

**Comment by Timmyfox** [comment]
Can confirm I'm having this issue as well, seems to have been introduced by version 4.3.2, experienced it with both the x64 and x86 versions.

**Comment by VetaLioSTV** [comment]
Same here, check my [post](https://github.com/telegramdesktop/tdesktop/issues/25408#issuecomment-1324330818)

**Comment by bluemooduser** [comment]
**I am so annoyed by this bug. Lol**
I came just to issue this and found someone already did.

**Comment by DanielRamp** [comment]
> **I am so annoyed by this bug. Lol**

I was frustrated too, since this seems so hard to miss when releasing a stable build. (NOT A BETA! or a small app from someone)

I made the mistake of reinstalling [v4.3.1](https://github.com/telegramdesktop/tdesktop/releases/tag/v4.3.1) and with it resetting the local telegram settings 😢.
I should have just waited. (Hint for future visitors)

**Comment by sujundada** [comment]
I had the same problem after updating to 4.3.2
win10 64

**Comment by Aokromes** [comment]
it must be fixed on 4.3.3

**Comment by PFCraft-box** [comment]
Resolved in version 4.3.3, issue closed
