### ISSUE TITLE
[missing] translations: ability to select multiple languages to ignore  

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#25414]
### Is your feature request related to a problem?

Not really - it's just a missing feature other Telegram apps that support messages translations have

### Describe the solution you'd like

From the translations settings, the ability to select more than one language to ignore

**Comment by 23rd** [comment]
Oh, the apps have a multiselection...

**Comment by GrimArthurius** [comment]
Yes, I have just faced the same - only one language could be ignored for translation. I wish at least three of them.

**Comment by Aokromes** [comment]
i miss something? this is telegram desktop feature request?

**Comment by RememberTheAir** [comment]
This is no longer an issue, language settings allows to select multiple languages
