### ISSUE TITLE
UI breaks when switching accounts with maximized window. Windows 4.3.2 x64

### ISSUE THREAD

**Issue by NeRaG0n7** [telegramdesktop/tdesktop#25410]
### Steps to reproduce

1. Have at least 2 accounts to switch between
2. Have the version 4.3.2 x64
3. Maximize the window
4. Try to switch accounts
5. The UI breaks

### Workaround:
1. Close the window with Alt + F4
2. Open the window from tray
3. Minimize the window
4. Fixed

### Expected behaviour

Switch between accounts with no UI issues.

### Actual behaviour

The UI breaks.
[Images](https://drive.google.com/drive/folders/1I6FOoT_m-kLOHzb-nyUaKNlg5tpklTYL)

### Operating system

Windows 10 Pro 19044.2006

### Version of Telegram Desktop

4.3.2 x64

### Installation source

Static binary from official website

**Comment by Xacnio** [comment]
I have a similiar problem. I maximize the window and I switch to another account. The window's size is changing.

**Comment by brevis-ng** [comment]
I also have a same problem when i up to date newest version.

**Comment by rossnomann** [comment]
I have similar issue on Ubuntu, but it resizes window without any break.

**Comment by firsturdiev** [comment]
I have same issue

**Comment by tunerok** [comment]
Same. Win 10. Tg v4.2.3

**Comment by Aokromes** [comment]
there is no need of bump the issue.

**Comment by sergey-khol** [comment]
A small workaround:
Expand the window manually to the end and then you won't notice this bug when switching even in full-size mode

**Comment by ali-safapour** [comment]
In order to fix this issue, turn on the "Install beta versions" option in "Settings > Advanced" and update Telegram to the latest beta version.

**Comment by Xacnio** [comment]
The beta version looking good. The issue solved for me. (Windows 11 x64 Version 4.3.3)
