### ISSUE TITLE
Media auto-load broken 

### ISSUE THREAD

**Issue by chellothere** [telegramdesktop/tdesktop#25411]
### Steps to reproduce

1.Open telegram random channel
2. See that photo/video not loaded and requires click
3. Check setting of auto-load in all types of channels, settings are ok.

### Expected behaviour

Auto-load works as intended

### Actual behaviour

Photo/video not loaded and requires click

### Operating system

Windows 8.1

### Version of Telegram Desktop

4.3.2

### Installation source

Static binary from official website

**Comment by mzji** [comment]
Same problem with version 4.3.2 . Rollback to 4.3.1 and then photos and videos will be automatically downloaded and played.

**Comment by brevis-ng** [comment]
same me

**Comment by chellothere** [comment]
Reinstalling fixed it for me

**Comment by mzji** [comment]
I'm using the portable version

**Comment by sarseev** [comment]
Same for me, reinstalling helped,

**Comment by maxoku** [comment]
I have a channel with over 200 pics to view and I can't do it by clicking at each.
Eh, reinstalling clears all settings and preferences, I don't have time to set everything again.

**Comment by woomiez** [comment]
yep, broken since 4.3.2, all pictures, link previews etc require clicking the download arrow even if they are significantly below the configured auto-download size.

**Comment by GrimArthurius** [comment]
Same here.

**Comment by Linden10** [comment]
Also same here! I just updated telegram and all photos and videos won't autoload like usual!
Hope this gets fixed soon!

**Comment by Aokromes** [comment]
stop bumping plz, there is no need of confirm more times.

**Comment by TBXin** [comment]
Confirm. It broke after upgrading to 4.3.2.

**Comment by Neurotoxin001** [comment]
Btw why there is no 4.3.2 sources?

**Comment by john-preston** [comment]
Is it only with 32 bit build? Is it fixed if you try 64 bit build?

**Comment by sprunkwallace** [comment]
> Is it only with 32 bit build? Is it fixed if you try 64 bit build?

im on 64 bit build with the same problem

**Comment by web-nick** [comment]
Покращили

**Comment by egrueda** [comment]
Same problem here after 4.3.2 upgrade.
Win10 64

**Comment by sujundada** [comment]
I had the same problem after updating to 4.3.2
win10 64

**Comment by wizard86pz** [comment]
> > Is it only with 32 bit build? Is it fixed if you try 64 bit build?
> 
> im on 64 bit build with the same problem

Hi, can you confirm that you are using the 64 bit build of the app? Or you mean the Windows build is 64 bit and maybe you are using the 32 bit build of Telegram on a Windows 64 bit?

Thanks.

**Comment by Weonidas** [comment]
Same problem here, version 4.3.2 on Windows 10 x64

**Comment by wizard86pz** [comment]
> Same problem here, version 4.3.2 on Windows 10 x64

Are you using the Telegram Desktop build for 32 bit or for 64 bit?

**Comment by Weonidas** [comment]
> > Same problem here, version 4.3.2 on Windows 10 x64
> 
> Are you using the Telegram Desktop build for 32 bit or for 64 bit?

I am using the x64 version

**Comment by seth-rah** [comment]
Also seems to impact the autoplay of media that's already been downloaded onto the system.

TDesktop 4.3.2

Windows 10 64 Bit, V22H2 Build 19045.2311

**Comment by ultrajae** [comment]
How to tell if running 32ibt or 64bit program? About doesn't seem to specify

**Comment by john-preston** [comment]
@ultrajae It has "x64" after the version string if running 64 bit build.

**Comment by ultrajae** [comment]
Thanks. That's absent on mine, so just 4.3.2,, on win 7 64bit..

**Comment by ultrajae** [comment]
Update 4.3.3 pushed out that seems to have fixed it.

Thank you
