### ISSUE TITLE
[Feature Request] Translation: Add secondary language

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#25415]
### Is your feature request related to a problem?

When I set English then all messages are translate automatically to English. But the same goes for English as well. I would like English to be translated to Polish automatically. I can do it manually, but searching Polish every time takes too much time. I would like it to do it automatically.

### Describe the solution you'd like

Adding a secondary language that will be used if the source language is the same as the target language.

### Describe alternatives you've considered

That it would remember what language I used for English and translate to it automatically every time without disturbing the default setting for the rest of languages.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
