### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by torabian** [telegramdesktop/tdesktop#25412]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

In many groups, we receive a lot of unsolidate messages. I want to add a feature in the desktop app, to select specific people and never show the messages are coming from them in my feed.

### Describe alternatives you've considered

We are skipping manually to read peoples message.

**Comment by RememberTheAir** [comment]
might it be related to #1025 #1281 #5492?

**Comment by 23rd** [comment]
https://bugs.telegram.org/c/1524

**Comment by Aokromes** [comment]
better https://bugs.telegram.org/c/37
