### ISSUE TITLE
Weird behavior on version v4.2.3 29.09.22

### ISSUE THREAD

**Issue by the-einstein** [telegramdesktop/tdesktop#25417]
### Steps to reproduce

1. you have to have 2 or more accounts 
2. switch to other account

### Expected behaviour

to switch to other account without any changes in window scale and size

### Actual behaviour

![2022-11-23_01-49-42](https://user-images.githubusercontent.com/44931139/203418287-01ee5653-e4bb-4818-aa99-022cdfb1d974.png)
I am having this kind of window after switching my accounts. 

### Operating system

Windows 11

### Version of Telegram Desktop

v4.2.3 29.09.22

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
duplicate.
https://github.com/telegramdesktop/tdesktop/issues/25410
