### ISSUE TITLE
[Feature Request] Custom Directory for Chat Export

### ISSUE THREAD

**Issue by kenifxyz** [telegramdesktop/tdesktop#25422]
### Is your feature request related to a problem?

Some chat groups that I'm exporting contain large media files. Therefore, exporting to my local machine might cause problems.

### Describe the solution you'd like

There should be an ability to choose the export file path (i.e. an external storage drive), or perhaps follow the "Download path" specified in "Settings > Advanced > Data and storage".

### Describe alternatives you've considered

Allow for the export to be paused, so that there is ample time for the files to be backed up and cleared for the next "batch" to begin.

**Comment by ilya-fedin** [comment]
Such feature is already present
![изображение](https://user-images.githubusercontent.com/17829319/203493321-9ed6c7f1-3512-4c44-9303-86f8a348cb2e.png)

**Comment by kenifxyz** [comment]
It seems to be missing on Mac for some reason, I tried on Windows just now and it is indeed present

**Comment by ilya-fedin** [comment]
Are you sure you're using tdesktop on Mac? Check the version and ensure it's the same as latest one: https://github.com/telegramdesktop/tdesktop/releases/tag/v4.3.1
