### ISSUE TITLE
Folders switching with Ctrl+1...9 wrong after 7

### ISSUE THREAD

**Issue by Dees7** [telegramdesktop/tdesktop#25421]
### Steps to reproduce

1. create 10 folders.
2. try change folders with Ctrl+1..9
3. Ctrl+8 Ctrl+9 strange behavior

### Expected behaviour

* Ctrl+1 - All chats
* ...
* Ctrl+7 - 7th folder
* Ctrl+8 - 8th folder
* Ctrl+9 - 9th folder
* Ctrl+0 - Archive.

### Actual behaviour

* Ctrl+1 - All chats
* ...
* Ctrl+7 - 7th folder
* Ctrl+8 - 10th folder
* Ctrl+9 - All chats again
* Ctrl+0 - Archive.

### Operating system

Windows 10 x64

### Version of Telegram Desktop

4.3 x64 porable

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
ctrl+1...7 - show folder 1...7
ctrl+8 - show last folder
ctrl+9 - archive
ctrl+0 - saved messages
