### ISSUE TITLE
Telegram-desktop can't make or receive voice calls when host is on an IPv6-only network

### ISSUE THREAD

**Issue by cvmiller** [telegramdesktop/tdesktop#25423]
### Steps to reproduce

1. Using the Linux telegram-desktop app (v 3.6.1) on an IPv6-only network (with DNS64 & NAT64 upstream) Start the app
2. Text Chat with a friend, note that this works fine
3. Attempt to call your friend by clicking the "phone" icon
4. Note that the call stalls at "validating encryption", no voice is heard

### Expected behaviour

Expect the Call to go through, and talk to my friend

### Actual behaviour

By switching the host to  a Dual-Stack network, the call goes through just fine, and I am able to talk to my friend.

BTW, I am running the Telegram-desktop from the Linux Mint Repo (although that is not a choice as "installation source"

### Operating system

Linux Mint 21, XFCE Desktop

### Version of Telegram Desktop

3.6.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Please check on the official version

**Comment by cvmiller** [comment]
Just checked on v4.3.1 and it _does_ work on an IPv6-only network. Thanks for the great software. Closing this issue
