### ISSUE TITLE
[Feature Request] Hotkey swhitching accounts Ctrl+F1..F5

### ISSUE THREAD

**Issue by Dees7** [telegramdesktop/tdesktop#25420]
### Is your feature request related to a problem?

There is no key for quick switching accounts no touching mouse.  

### Describe the solution you'd like

Ability quick switching account with Ctrl+F1..F5. 

### Describe alternatives you've considered

Something like it works for folders with Ctrl+1...9 now.

**Comment by ilya-fedin** [comment]
#8179
