### ISSUE TITLE
Telegram MarkdownV2 does not properly display links with top-level domains only

### ISSUE THREAD

**Issue by smolsky** [telegramdesktop/tdesktop#25426]
### Steps to reproduce

1. Try create link (Ctrl-K) with URL: com/   -  UI will say that URL incorrect
2. Try change URL to http://com/ - UI accepts the URL but when you send the message - it will be not a link, but ordinary text
3. The same behavior when you tring to send sessage via bot API  in MArkdownV2 format with  URL like http://localhost:3000/

### Expected behaviour

Correct URLs (even top-level, like  http://localhost:3000/) are displayed as links

Also at least two similar bugs were already closed without fixes, expecting them also to be fixed:
https://github.com/telegramdesktop/tdesktop/issues/10440
https://github.com/telegramdesktop/tdesktop/issues/7827

### Actual behaviour

Top-level domains links (without dots) displays as plain text (not as a link)

### Operating system

Windows 11

### Version of Telegram Desktop

v4.2.4 x64

### Installation source

Microsoft Store

**Comment by ilya-fedin** [comment]
If you would read those issues, you will see it's a server side issue, nothing could be done client side.
