### ISSUE TITLE
[Question] Why lines in replies now colorized even in channels?

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25428]
Tdesktop:
![image](https://user-images.githubusercontent.com/39812401/203765092-eb036764-98fd-4e9c-979d-5b5df99bdc74.png)

iOS:
![image](https://user-images.githubusercontent.com/39812401/203765110-bb7e86e6-34ae-4c0a-8282-b516bfa412ab.png)

And it's does not depend on theme, like on iOS. It's green even with white theme. Before version 4.3.3, I don't remember this existing.

**Comment by 23rd** [comment]
That's a mistake. 😰

**Comment by Neurotoxin001** [comment]
Fixed in 4.4
