### ISSUE TITLE
Telegram does not work after self updating

### ISSUE THREAD

**Issue by lmores** [telegramdesktop/tdesktop#25429]
### Steps to reproduce

1. Install Telegram Desktop with `tsetup4.3.1.dmg` downloaded on 23/22/2022 at 14:28 from [https://desktop.telegram.org/](https://desktop.telegram.org/)
2. Open Telegram desktop and wait for updates being available
3. Click on "Update Telegram" blue button at the bottom left corner of the user interface.
4. Telegram closes but does not restart. Attempting to manually reopen it does not work.

### Expected behaviour

Telegram should update itself and restart.

### Actual behaviour

Telegram does not automatically restart and it can not be opened manually anymore (I must uninstall it an reinstall it).

### Operating system

Mac Os 10.13.6

### Version of Telegram Desktop

4.3.1

### Installation source

Static binary from official website

### Logs

```shell
No error messages appear via user interface.
If I try to open Telegram using a terminal nothing happens (no error messages):


$ open /Applications/Telegram.app
$
```

**Comment by lyicong** [comment]
I encountered the same issue.

When I try to open Telegram from Terminal, I got an error message.
```
$ /Applications/Telegram.app/Contents/MacOS/Telegram 
dyld: Library not loaded: /System/Library/Frameworks/NaturalLanguage.framework/Versions/A/NaturalLanguage
  Referenced from: /Applications/Telegram.app/Contents/Frameworks/Updater
  Reason: image not found
[26544:11125570:20221208,011833.849045:WARNING process_memory_mac.cc:93] mach_vm_read(0x7ffeeac70000, 0x2000): (os/kern) invalid address (1)

$ /Applications/Telegram.app/Contents/Frameworks/Updater 
dyld: Library not loaded: /System/Library/Frameworks/NaturalLanguage.framework/Versions/A/NaturalLanguage
  Referenced from: /Applications/Telegram.app/Contents/Frameworks/Updater
  Reason: image not found
Abort trap: 6
```

I think the issue is caused by the Updater trying to load NaturalLanguage framework, which does not exist in High Sierra. I don't think update program will needed it.

**Comment by john-preston** [comment]
That's bad :/

**Comment by john-preston** [comment]
Is the version 4.5 working?

**Comment by Woundorf** [comment]
I had the same problem and version 4.5.2 takes several seconds to start but works.

**Comment by lmores** [comment]
No, it does not work. 
Last week I had to reinstall MacOS from zero (for other reasons), now I have a clean installation of MacOS 10.13.6 (17G14042).
I have Telegram 4.5.0 and when the blue update button appeared today in the the bottom left corner of the interface I clicked it. Same problem, Telegram closed without restarting and I can not launch it manually anymore.

If I try from terminal I still get this:
```bash
$ /Applications/Telegram.app/Contents/MacOS/Telegram
dyld: Library not loaded: /System/Library/Frameworks/NaturalLanguage.framework/Versions/A/NaturalLanguage
  Referenced from: /Applications/Telegram.app/Contents/Frameworks/Updater
  Reason: image not found
<OMITTED_USER_INFO> [466:8041:20230103,114557.529481:WARNING process_memory_mac.cc:93] mach_vm_read(0x7ffee9067000, 0x2000): (os/kern) invalid address (1)
```
