### ISSUE TITLE
[Question] Telegram Desktop is outdated on Microsoft Store.

### ISSUE THREAD

**Issue by onurbbr** [telegramdesktop/tdesktop#25427]
Telegram Desktop has not been updated from Microsoft Store for about 1 month. When will the update be released?

Microsoft Store Telegram Desktop version: 4.2.4
Latest Telegram Desktop version: 4.3.2

The reason I'm asking this is because I can't use the innovations that came with the last update.

NOTE: I am a Windows Insider Beta user.

I appreciate your work. Have a nice day.

**Comment by Aokromes** [comment]
duplicate

**Comment by john-preston** [comment]
Should be updated now.
