### ISSUE TITLE
[Bug] Can't play games sent via Inline Mode

### ISSUE THREAD

**Issue by Kondra007** [telegramdesktop/tdesktop#2543]
I've recorded video that demonstrates this bug: https://youtu.be/bKbG5akhBVw

### Steps to reproduce
1. Send game via inline mode

### Expected behaviour
There should be "Play %game%" button or game should start when you click on image.

### Actual behaviour
There's no "Play %game%" button and you can't start game clicking on its image. Only restart solves the problem.

### Configuration
**Operating system:** Windows 10 LTSB x64
**Version of Telegram Desktop:** 0.10.15 alpha

**Comment by diazbastian** [comment]
I can confirm this behavior in 0.10.16... however, this does not happen `@gamee` or `@gamebot` but with new bots that are building by independent developers: Ex. `@gameshdbot`, `@awesomebot`, `@microgamesbot`, etc.

As @Kondra007 says, the button to start the game only appears once restarted TDesktop.

Before

![before](https://cloud.githubusercontent.com/assets/5126124/19565432/3491ee5a-96bd-11e6-8f6e-53e7bbb4467d.png)

After

![after](https://cloud.githubusercontent.com/assets/5126124/19565441/3abde824-96bd-11e6-94b8-a8d6d450e5c8.png)

**Comment by john-preston** [comment]
Those bots don't send the required markup in the inline results list. I hope that it will be fixed on the server side (the markup will be forced for the game inline results if there is no such provided by the bot).

The other apps I guess handle this case correctly (by adding the markup when it is returned from server after sending).

**Comment by Kondra007** [comment]
@john-preston 
I think they rely on Bot API description for sendGame, where it's stated that "Play Game" button will be shown even if no reply_markup is passed.
![image](https://cloud.githubusercontent.com/assets/2780044/19565767/b3d473a8-96f0-11e6-9093-ec8f5f31b346.png)

**Comment by john-preston** [comment]
Well, then this is server-side fault :) It should add this "Play game_title" button in the inline results list, I hope it will.

**Comment by Kondra007** [comment]
> «Well, then this is server-side fault»

@john-preston Should I (or you) close the issue then?

**Comment by john-preston** [comment]
No, if the server won't fix it, then I'll fix it in the next version from the client side.

**Comment by john-preston** [comment]
Fixed.
