### ISSUE TITLE
[Question] topics: small dots instead of unread counters

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#25439]
Hello there,

I've noticed that since one of the most recent releases, in the topics list of a topics chat, sometimes unread topics don't have an unread counter but a small dot signaling there's new messages. For example:

![image](https://user-images.githubusercontent.com/16143208/203975178-292b6984-9370-475c-a0ad-0320509639e0.png)

I suppose these are topics I haven't accessed in a while, but it doesn't happen in all such topics.
So, how does it work? What does this dot mean?

**Comment by john-preston** [comment]
It means topics that you didn't ever open yet. Like, you just joined a forum and some new messages appeared in those threads after that.

**Comment by RememberTheAir** [comment]
Thanks!
