### ISSUE TITLE
Telegram crashes while playing video and activating window mode

### ISSUE THREAD

**Issue by brmmm3** [telegramdesktop/tdesktop#25435]
Since one of the latest updates Telegram video playback always starts in full screen mode (first bug). When I activate window mode for video playback Telegram crashes (second bug). This happens always.

OS is Kubuntu Linux 22.04.

**Comment by brmmm3** [comment]
Disabling OpenGL solves the issue.

**Comment by ilya-fedin** [comment]
@Aokromes can you close this due to the lack of template?

**Comment by MrSwed** [comment]
ubuntu 20, kubuntu 22
4.3.2, 4.3.3 - the problem is still there.
downgrade to 4.3.1 helped

**Comment by Aokromes** [comment]
also, it's duplicated.

**Comment by MrSwed** [comment]
where is the link to the duplicate issue?
