### ISSUE TITLE
Indexed images appear dithered in previews

### ISSUE THREAD

**Issue by hatkidchan** [telegramdesktop/tdesktop#25436]
### Steps to reproduce

1. Have a perfect, non-dithered image without any gradients with plain background and some text
2. Send it in some chat and look at a modal window before uploading

### Expected behaviour

Image should look crispy clear

### Actual behaviour

Image looks noisy, almost like it's dithered. Sent image itself is untouched, only previews are suffering.

![image](https://user-images.githubusercontent.com/35804000/203930604-0c5b56a9-bf2f-48d3-8c39-bec69187e90f.png)
![image](https://user-images.githubusercontent.com/35804000/203930712-0a1224f2-8062-4472-ab8d-8eaa6d4a0016.png)

### Operating system

Arch Linux, i3

### Version of Telegram Desktop

4.3.1-2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
I believe such strong compression exists for a reason

**Comment by hatkidchan** [comment]
It's not a compression issue, image itself doesn't look dithered or noisy, that problem happens only in previews. So it's more like a visual glitch than anything else

**Comment by ilya-fedin** [comment]
The preview is jpeg compressed IIRC

**Comment by hatkidchan** [comment]
Is there any reason why images are compressed in previews?

**Comment by ilya-fedin** [comment]
Yeah, I believe there is, I don't know which one exactly though

**Comment by ilya-fedin** [comment]
It's sadly a KDE bug and AFAIK no one still reported it to them. They tell scale factor to Qt in a wrong way that overrides the High-DPI scale factor rounding policy tdesktop sets to Qt. After that override the scaling in tdesktop just can't work properly.

**Comment by ilya-fedin** [comment]
@hatkidchan there was some work relate to color spaces support, do you see any changes? Note that you should use an official build in order to see the difference as all changes were in Qt patches.

**Comment by hatkidchan** [comment]
![image](https://user-images.githubusercontent.com/35804000/210132572-c774aefa-1c54-47e9-8a71-ab1212da6f80.png)
Still happens on latest release from https://github.com/telegramdesktop/tdesktop/releases/tag/v4.5.0

**Comment by ilya-fedin** [comment]
Honestly saying I don't see anything abnormal on the screenshot. Some comparison would be nice.

**Comment by hatkidchan** [comment]
Looks like this happens when there's a lot of colors on the image
![image](https://user-images.githubusercontent.com/35804000/210133220-d3ef02c0-0ae4-4c83-8d76-25361b3868ee.png) ![image](https://user-images.githubusercontent.com/35804000/210133230-af794b2c-0226-44a4-bc40-ad84665d9f22.png)

Maybe it's the problem with image having more than 256 colors and Telegram rendering them as indexed palette for some reason?

**Comment by ilya-fedin** [comment]
I meant comparison with how it should look like

**Comment by hatkidchan** [comment]
~~I don't think I could replicate that in Telegram. Though, I just noticed that it only happens when image is quite large (I'm upscaling them 2x)..~~

I think I found the problem. It happens when Telegram tries to scale down image with indexed palette. When converting same image to rgb24 instead of pal8, it looks like it should:

![image](https://user-images.githubusercontent.com/35804000/210133470-f127b658-e14b-4faa-ba24-eced480a47c5.png)

Though, I don't really get the reason of that problem: there's definitely less than 256 colors on that image, and scaling indexed should not resolve it appearing dithered. Maybe there's a problem somewhere in png/pal8->jpeg/rgb24 conversion? I tried converting it myself to jpeg using imagemagick's `convert` and it's not noisy as on previous screenshots

**Comment by hatkidchan** [comment]
~~I don't think I could replicate that in Telegram. Though, I just noticed that it only happens when image is quite large (I'm upscaling them 2x)..~~

I think I found the problem. It happens when Telegram tries to scale down image with indexed palette. When converting same image to rgb24 instead of pal8, it looks like it should:

![image](https://user-images.githubusercontent.com/35804000/210133470-f127b658-e14b-4faa-ba24-eced480a47c5.png)

Though, I don't really get the reason of that problem: there's definitely less than 256 colors on that image, and scaling indexed should not resolve it appearing dithered. Maybe there's a problem somewhere in png/pal8->jpeg/rgb24 conversion? I tried converting it myself to jpeg using imagemagick's `convert` and it's not noisy as on previous screenshots

**Comment by ilya-fedin** [comment]
I looked at the code generating the preview and there's no conversation in jpeg. It only uses Qt's QImage::scaledToWidth and then writes with white color on transparent pixels if the image has alpha channel
https://github.com/telegramdesktop/tdesktop/blob/23e1c6128b27487651c8be4f2734265b8284e0c9/Telegram/SourceFiles/storage/storage_media_prepare.cpp#L334-L336
https://github.com/desktop-app/lib_ui/blob/3fea35ff19b52da94fa3ed17695f00b79bfb1917/ui/image/image_prepare.cpp#L1180-L1199

**Comment by ilya-fedin** [comment]
> ~I don't think I could replicate that in Telegram. Though, I just noticed that it only happens when image is quite large (I'm upscaling them 2x)..~
> 
> I think I found the problem. It happens when Telegram tries to scale down image with indexed palette. When converting same image to rgb24 instead of pal8, it looks like it should:

Both those findings seem to be right. Since Qt 6.0, it doesn't seem to follow the SmoothTransformation hint if scaling more than 2x down and the format is not one of whitelisted: https://github.com/qt/qtbase/commit/b0b4fcd05cd5ae891da868829c1645acf7589acb

**Comment by ilya-fedin** [comment]
You can try to revert the commit on your system Qt package and install tdesktop via package manager or I can provide a build with the Qt commit reverted for test. What do you want?

**Comment by hatkidchan** [comment]
It's not that significant issue, just a small annoyance. I think it'd be better for me to change title of that issue to more meaningful and close this, since it's a problem in third-party library

**Comment by hatkidchan** [comment]
Though, I just noticed that it also happens in sent images as well, are they being scaled down before sending using the same function as for preview? It doesn't happen when I send the same image using bot, so it may be the case here..

**Comment by ilya-fedin** [comment]
Yeah, compressed images should be affected as well

**Comment by ilya-fedin** [comment]
I've created an Indexed image in GIMP and can confirm the issue. Can also confirm it doesn't happen with Qt 5.

**Comment by hatkidchan** [comment]
Maybe it'd be better to convert image from indexed to rgb24bor any other supported format and then scale it down? I can't imagine any other way of fixing that within app itself without making changes in Qt6

**Comment by ilya-fedin** [comment]
Will see what approach @john-preston will choose. Converting everything to RGB or patching Qt.

**Comment by ilya-fedin** [comment]
I don't see any note in Qt documentation that SmoothTransformation doesn't even apply, wonder whether it could be reported as a Qt bug...
https://doc.qt.io/Qt-6/qimage.html#scaled
https://doc.qt.io/Qt-6/qt.html#TransformationMode-enum

**Comment by ilya-fedin** [comment]
Looking more at the code, it seems the image I test with fits the requirements for smoothScaled (its size is more than 1<<20), so apparently it's caused by Qt converting it back to Indexed8 format.

**Comment by ilya-fedin** [comment]
I can confirm patching Qt to remove `convertToFormat(format())` helps, so apparently Qt doesn't support indexed format good and the conversion is lossy

**Comment by ilya-fedin** [comment]
https://bugreports.qt.io/browse/QTBUG-109736

**Comment by ilya-fedin** [comment]
There's sadly too much candidates for pre-converting to RGB format and I likely miss some of them, there are also may appear new places that may forget converting. Since it would be too easy to regress, I think patching Qt is the best way forward. If they will reject to fix this or request to invest too much time (like requiring a minimum reproducible example), I will leave fixing this in 3rd party builds for 3rd party redistributors (or any other interested party) if they need such a fix (i.e. to pick up the bug report or tdesktop Qt patchset).

**Comment by hatkidchan** [comment]
It's more than enough already for such a small issue. It is an annoyance, for sure, but this should be done on Qt side, since it was working flawlessly in older versions. I'm gonna check from the to time on that bug report in At in hope they fix it eventually, but for the time being I guess I'm just gonna convert images from indexed palette myself, no big deal
