### ISSUE TITLE
Autodownload of multimedia is not working after update

### ISSUE THREAD

**Issue by Rodhos** [telegramdesktop/tdesktop#25434]
### Steps to reproduce

1. Open a channel or group.
2. Autodownload of multimedia is not working.
3. Yes, its enabled in settings and limit is set to 10 mb.
4. Yes, I tried to enable and disable and change the limit to max.
5. Nothing works so far.

### Expected behaviour

Autodownload of multimedia works properly.

### Actual behaviour

Autodownload of multimedia is not working.

### Operating system

Windows 11 22H2 22621.819

### Version of Telegram Desktop

4.3.2

### Installation source

Static binary from official website

**Comment by vlad909** [comment]
hi. I catch this bug too with win 10. You can try to delete and install the client again. After that the media is loaded correctly

**Comment by Aokromes** [comment]
duplicate.
