### ISSUE TITLE
It was there before but was not working, now there is not at all this option - download multiple selected voice records [Feature Request] 

### ISSUE THREAD

**Issue by testoviron2137** [telegramdesktop/tdesktop#25437]
### Is your feature request related to a problem?

Few days ago it was possible to select multiple voice records and click to download them in one run, the telegram was showing that it downloads the files but in reality it was not. Now with the todays update I notice there is no longer this option to download.

### Describe the solution you'd like

Make it possible to download multiple selected voice records with one click.
Also the automatic naming of the files with the date of the recording instead of the date of the downloading the file, seems more logical and better?

### Describe alternatives you've considered

If not in free version, maybe we can make another good selling point for telegram premium subscription?

**Comment by Aokromes** [comment]
https://i.imgur.com/xIH2u5W.png

**Comment by testoviron2137** [comment]
> 

Hmm, then I have to investigate why it disappeared from my telegram.
But still, there is the main issue of telegram not really downloading in bulk.

**Comment by Aokromes** [comment]
> > 
> 
> Hmm, then I have to investigate why it disappeared from my telegram. Or maybe yours was not yet updated? But still, there is the main issue of telegram not really downloading in bulk.

that screenshot is from 4.3.3

**Comment by testoviron2137** [comment]
Same. And I could not find the answer why I don't have this option for any voice recordings on multiple selection (>2)

**Comment by Aokromes** [comment]
> Same. And I could not find the answer why I don't have this option for any voice recordings on multiple selection (>2)

it looks if file type changes the selection ain't show.

**Comment by testoviron2137** [comment]
> > Same. And I could not find the answer why I don't have this option for any voice recordings on multiple selection (>2)
> 
> it looks if file type changes the selection ain't show.

Hmm, Thank you for your interest. I am not sure if I understood you correctly, but how that could be that file type changes? What are the possibilities of file types? And do you mean that every voice record somehow manages to change the file type so every time I select two files, they are of different type?
