### ISSUE TITLE
Native notifications not used (Telegram Flatpak)

### ISSUE THREAD

**Issue by beglort** [telegramdesktop/tdesktop#25448]
Operating System: SteamOS 3.4
KDE Plasma Version: 5.26.1
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 5.13.0-valve31-1-neptune (64-bit)
Graphics Platform: X11
Flatpak commit affected: `95c62bfc53372f66048bc7e23300fb4017f358a9edd1f6d7e3dfb2369934e34c` 

System notifications were working normally before the latest update. 
A downgrade to the previous commit: `ee1f1b49d23f37e292217193d3b41ef6bbdd094e422a694a0b1992fef001ea53` solved the issue

**Comment by ilya-fedin** [comment]
Yeah, they're broken in flatpak right now due to an attemption to implement the portal notifications, #25445 should fix this

**Comment by beglort** [comment]
Good, so it's just matter of time for when is merged. 
Anyway hope i didn't open a duplicate, I thought it was new bug
