### ISSUE TITLE
Build of qt_5_15_4 failed while prepare libraries with message "Failed to run xml sel -D -B -t -c / mimetypes\mime\packages\freedesktop.org.xml"

### ISSUE THREAD

**Issue by vavileno** [telegramdesktop/tdesktop#25441]
Build libraries failed when run tdesktop\Telegram\build\prepare\win.bat from BuildPath described at Build instructions for Windows 64-bit.
Obviously the reason is missing path to XMLStarlet  executable in PATH environment variable.
Which in turn appears not to be installed on my system.

After installing XMLStarlet and set up path to xml.exe to PATH environment variable the build of qt_5_15_4 proceed and finished successfully.

I'm not sure if it is correct to install xmlstarlet-1.6.1-win32 version for this purpose but could not find another options to resolve the issue and besides  it seems reasonable.
Please advise if that's not correct option.

**Comment by ilya-fedin** [comment]
It shouldn't be required, I'm able to build without XMLStarlet
