### ISSUE TITLE
Windows 10 Visual Keyboard Touch devices

### ISSUE THREAD

**Issue by cala2ar** [telegramdesktop/tdesktop#2544]
Hello , 

There is an issue on windows 10 ( latest build at the time , hp specre laptop ) touch devices , when press the reply text area on a message the visual keyboard doesn't popup automatically .

**Comment by john-preston** [comment]
@cala2ar This is a known Qt bug: https://bugreports.qt.io/browse/QTBUG-43190

I hope it will be fixed some day and I could backport the fix.

**Comment by Aokromes** [comment]
#218
