### ISSUE TITLE
Privacy - add option to select custom browser for opening url from telegram

### ISSUE THREAD

**Issue by qwertyuiopzxcvbnmlkjhgfdsa1** [telegramdesktop/tdesktop#25444]
### Steps to reproduce

1. Open any url link
2. Will open in system default browser and user is tracked by google, twitter,.. anywhere he is logged.

### Expected behaviour

1. Open url from telegram
2. Url opens in system default browser **or browser i choose**. If user wants to use other browser, not default for privacy browsing - other installation, tor/..., it should be offered and respected.

### Actual behaviour

Privacy is violated when user cannot choose browser for telegram's url to open in.

Users are logged in browser with twitter, github, google accounts. When the use telegram, they do it because they want more privacy.  Nobody wants to be tracked what url are opened from telegram. Telegram supposed to be safe platform for opening urls

Desired behavior is to be able to choose browser for opening urls, which will serve only for safe browsing. Default browser is mostly used for work, not privacy.

### Operating system

Linux 64

### Version of Telegram Desktop

2.3.4

### Installation source

Snap

**Comment by ilya-fedin** [comment]
> Snap

Sorry, but this is not possible in snap, it sandboxes the application and doesn't let it decide what URL handler to use.

It also doesn't really sounds like a bug, a feature request at best.

**Comment by RememberTheAir** [comment]
@ilya-fedin is it possible to set this from a non-snap installation? eg. static binaries from the website?

**Comment by ilya-fedin** [comment]
@RememberTheAir yeah, but I don't think this will be implemented

**Comment by qwertyuiopzxcvbnmlkjhgfdsa1** [comment]
@ilya-fedin Could be this Secure Web url used if implemented in Gnome Control Center?  https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2225

**Comment by ilya-fedin** [comment]
No, there doesn't seem to be anything in UI that would correspond to this setting (and I don't even think other OS/DE have anything similar, so there's no cross-platform concept for such feature) and I avoid reading DE-specific settings as it would very fast lead to dozens of methods to do something in the code, so this needs a freedesktop standard.

**Comment by ilya-fedin** [comment]
The only way for this feature to exist in tdesktop only if it will require no code changes, i.e. will work through the system "open in default application" APIs. And since tdesktop is not a GNOME application, support for this only in GNOME libraries is not enough, it should also be in Qt.
