### ISSUE TITLE
[Feature Request] Block DMs from random accounts

### ISSUE THREAD

**Issue by alkaris2** [telegramdesktop/tdesktop#25447]
### Is your feature request related to a problem?

As Telegram becomes more popular there are going to be bots who spam users with random DMs. While you can report these bots for spam and block them, it's going to get annoying when you're flooded with messages from anyone without any sort of block prevention from people sending messages randomly unless they're added as a Contact first. While this isn't a problem with Groups on Telegram as they can be moderated by Admins and having the Join Group protection features, this isn't the same for just P2P direct messaging.

### Describe the solution you'd like

Add Privacy & Security Feature for Block Direct Messages from Anyone and the options being:

 - My Contacts (default)
 - Everybody
 - Nobody

Set how you would like to receive Direct Messages. For example Message Request - While allowing "My Contacts" to message someone, Non-Contacts can send a Message Request to the other user WHY they are contacting them. But instead of showing a notification popup message, you instead see a number counter under Message Requests where you can view who's sending a message request to add you where the user can then either click Approve or Deny button. If clicking Deny button give the user a prompt to do the following actions;

- Block & Report Spam
- Do nothing

### Describe alternatives you've considered

There are no alternatives

**Comment by ilya-fedin** [comment]
This feature is already implemented and is available in Telegram Premium
