### ISSUE TITLE
[Feature Request] Remove the download arrow when file has thumbnail

### ISSUE THREAD

**Issue by tissole** [telegramdesktop/tdesktop#25443]
### Is your feature request related to a problem?

Currently, the download arrow covers the file's thumbnail. It is also redundant because there is also a "Download" text button. 

### Describe the solution you'd like

Remove the arrow when the file has a thumbnail. The "Download" button is enough. Now is looking like this
![1](https://user-images.githubusercontent.com/78413495/203998001-13ccd923-81d6-4597-a0d2-7f6e88444a75.png)
It looks better like this
![2](https://user-images.githubusercontent.com/78413495/203998071-56780cec-8218-4ab7-b0a0-b6440ea85c84.png)

### Describe alternatives you've considered

Replace the text "Download" button with the arrow, so the thumbnail remain fully visible.

**Comment by 23rd** [comment]
I'm afraid it will never be done until the other apps have the same design. So this request belongs https://bugs.telegram.org.
