### ISSUE TITLE
[Question] why "Also delete for [username]" is checked by default since version 4.3.3?

### ISSUE THREAD

**Issue by acavalin** [telegramdesktop/tdesktop#25442]
Hello,

when deleting some messages in a chat, till version 4.3.1 the checkbox "Also delete for [username]" is unchecked by default, but now since 4.3.3 it is always checked.

This troubles me a lot because I tend to keep clean my chats by deleting unimportant messages only on my side, and now I am forced to click the checkbox everytime, I can't even deselect it by pressing TAB and spacebar 😢

Is it possibile to restore the previous behavior or add an option for it in the settings area?

Thank you

**Comment by Aokromes** [comment]
because people asked for it.

**Comment by acavalin** [comment]
I imagined that, so is it possibile to either:

- add an option in the settings for selecting the default state of that checkbox
- or make it possible to focus on the checkbox with the keyboard in order to toggle it

**Comment by RememberTheAir** [comment]
@Aokromes are you sure that's the reason? there's plenty, plenty of similar requests here and none of them gets implemented when they break platform consistency, such as the default status of that toggle. Besides, the issue requesting that feature has been cold for quite some months before this change has been pushed - I don't understand why introducing this change now. To me it looks like one of the developers find it convenient (I agree, I like the "toggled" state as the default) and decided to push it, but it definitely shouldn't work like that. If it's unchecked by default on mobile apps, it should be unchecked by default on the desktop app too

I would like to hear a comment from the maintainer on this

**Comment by Aokromes** [comment]
> @Aokromes are you sure that's the reason? there's plenty, plenty of similar requests here and none of them gets implemented when they break platform consistency, such as the default status of that toggle. Besides, the issue requesting that feature has been cold for quite some months before this change has been pushed - I don't understand why introducing this change now. To me it looks like one of the developers find it convenient (I agree, I like the "toggled" state as the default) and decided to push it, but it definitely shouldn't work like that. If it's unchecked by default on mobile apps, it should be unchecked by default on the desktop app too
> 
> I would like to hear a comment from the maintainer on this one

there was one feature request for it, with the logic of, if you delete one message only for yourself and want to delete for everyone you cannot "fix" that.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3334

**Comment by RememberTheAir** [comment]
it goes both ways, if you wanted to delete something just for yourself and forget to uncheck the checkbox, the other user will irrecoverably lose the message you deleted.
I agree the situation you described is possibly the most damaging one, and the one that might occur more frequently - in fact I'm in favor of changing the default. But I don't think that having different defaults and having users get used to this difference between desktop and mobile is a good idea

**Comment by acavalin** [comment]
> #3334

The subject of that ticket is "Have an option to configure default Delete action on app level"... so why the app changed his behavior and doesn't have a config option in the Settings menu?

I think this change in behavior tricked various people too, and a config option can easily satisfy both factions indipendently of the default.

**Comment by ilya-fedin** [comment]
@acavalin there's policy to have as less settings as possible, so it's unlikely an option would be added

**Comment by acavalin** [comment]
> @acavalin there's policy to have as less settings as possible, so it's unlikely an option would be added

I understand, thank you 👍🏻 

By the way this change has generated a different behaviour between telegram desktop and the official mobile and web apps.

Users of both versions might be tricked in the wrong direction when deleting a message: I think all the applications should have the same behavior in order to avoid these pitfalls.

**Comment by ilya-fedin** [comment]
What about the macOS native client? I heard it behaves like tdesktop now

**Comment by acavalin** [comment]
> What about the native macOS client? I heard it behaves like tdesktop now

I read that too on the issue #3334, but this is not the case for Android, iOS, Web Z, K and legacy.

**Comment by RememberTheAir** [comment]
@ilya-fedin the MacOS app should be fixed too, considering how preston stated multiple times that the leading apps in terms of UX are the mobile ones, and also considering that they have the most users (I guess that's why they're the UX landmarks lol) and it is much more likely that a Telegram user uses a mobile app + tdesktop, than the MacOS app + tdesktop

**Comment by john-preston** [comment]
I'm not against an experimental setting :) Or maybe this checkbox state could be remembered locally.

**Comment by john-preston** [comment]
It should be done like this:
- we have a saved hidden setting (not in Settings) value for this checkbox, "on" by default
- in case you change the checkbox state when deleting some messages a new checkbox appears, "Remember this choice", "off" by default
- the saved hidden setting is updated only if the second checkbox is explicitly checked

This will give both of two worlds — no new checkboxes in Settings and no surprising behavior in case you once used a changed value.

**Comment by john-preston** [comment]
In the next version it should ask you if you want to save the changed state of the checkbox.
