### ISSUE TITLE
Telegram-desktop doesn't honor the "ask download path for each file" flag

### ISSUE THREAD

**Issue by ArshiAAkhavan** [telegramdesktop/tdesktop#25456]
### Steps to reproduce

1. upgrade telegram desktop to version 4.3.1
2. set Setting>Advanced>Ask download path for each file to false
3. try to download a new file

### Expected behaviour

Download the file in the predefined directory and doesn't show the file chooser menu

### Actual behaviour

Pops up the file chooser menu for each and every new file

### Operating system

ubuntu 22.04

### Version of Telegram Desktop

4.3.1

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Are you sure it's for every? It should ask one time to get the permission from the sandboxing system and remember it.

**Comment by ArshiAAkhavan** [comment]
You are partially right.
If you select a folder once, it would continue to use that directory for other files as well.
but when i check the settings under advanced>Download path, the download directory is changed from `Telegram folder in systems downloads` to `custom folder` even if i choose default folder in the file chooser menu.

A side effect of this behavior is that telegram won't honor the files already downloaded in my system and tries to re-download them.

On the other hand, if i don't select a folder, telegram would start downloading into the `Telegram folder in systems download` but it would pop up the file chooser menu every time i try to download a file

**Comment by ilya-fedin** [comment]
Yeah, sadly this option is no more available when Telegram is sandboxed, sorry :(
You have to redownload everything.
