### ISSUE TITLE
telegram-desktop requires rtkit daemon

### ISSUE THREAD

**Issue by C138** [telegramdesktop/tdesktop#25455]
### Steps to reproduce

1. remove rtkit daemon (sometime in the past ;-)
2. install telegram-desktop  (e.g. 4.3.4)
3. try to connect with telegram / qrcode does not appear  or  code not sent to telephone
4. install rtkit
5. retry ti connect with telegram / both (qr-code / sent code) are working

without rktkit, a descritive message is displayed in the console, thus the fix is easy to find ;-)
but the snap is not really standalone...
 

### Expected behaviour

Easy (re)connection with telegram-desktop (snap)

### Actual behaviour

(re)connection fails.
QR code is not displayed
Code message is not sent

### Operating system

ubuntu 22.04

### Version of Telegram Desktop

 latest/stable:    4.3.4

### Installation source

Snap

**Comment by ilya-fedin** [comment]
tdesktop doesn't talk to rtkit, so it's a coincedence
