### ISSUE TITLE
[Feature Request] Add a dynamic folder filter for ongoing voice chat

### ISSUE THREAD

**Issue by JonathanPitre** [telegramdesktop/tdesktop#25453]
### Is your feature request related to a problem?

No, just an enhancement to existing folder filters

### Describe the solution you'd like

It would be awesome to be able to have a dedicated folder for ongoing voice chats. It would look at all channels and chat groups you are subscribed to and only shows the ones with ongoing voice chats.

### Describe alternatives you've considered

I have manually created a folder with channels that host voice chats often however it's not as dynamic.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by RememberTheAir** [comment]
The mobile apps show you a list of active voice chats when you open the "calls" screen. It would be cool to have that on tdesktop too
