### ISSUE TITLE
Broken sound-related actions

### ISSUE THREAD

**Issue by suwermave** [telegramdesktop/tdesktop#25452]
### Steps to reproduce

1. Play voice message
2. Play music file
3. Open a video with sound
4. Use telegram normally

### Expected behaviour

1. Voice message plays
2. Music file plays
3. Video plays with sound
4. Nothing weird happens

### Actual behaviour

1. Voice messages don't load
2. Music file don't load
3. Video opens, no sound
4. Saving folder dialog appears often

### Operating system

Fedora Linux 37.20221115.0 (Silverblue)

### Version of Telegram Desktop

From around 4.3 (when smooth corners for messages were introduced) to 4.3.4

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
It's a bug in Fedora 37, you can downgrade to Fedora 36 or wait until they fix the issue

**Comment by suwermave** [comment]
No, it isn't? I had issues since November 8th, Fedora 37 release was in November 15th

**Comment by ilya-fedin** [comment]
There were a couple of issues that tdesktop doesn't produce sound on Fedora since Fedora 37 is released, there were no such issues reported from users of other distros and I can't reproduce it myself on my distro. So it's a Fedora regression and you should report to it.
