### ISSUE TITLE
Opening inbox with video file attachments suddenly freezes and exits instead of playing

### ISSUE THREAD

**Issue by Reno-Sifana** [telegramdesktop/tdesktop#25457]
### Steps to reproduce

1. Open telegram desktop version 4.3.4
1. open the inbox containing the Video attachment
1. Instead of playing the video, the desktop telegram freezes and exits itself a few moments later

### Expected behaviour

Opening an inbox with video attachments should play instead of freezing and exiting itself a few moments later

### Actual behaviour

Telegram desktop freezes and exits itself a few moments later instead of playing the Video file

### Operating system

Linux Mint 21 "Vanessa" Cinnamon Edition

### Version of Telegram Desktop

4.3.4

### Installation source

Flatpak

**Comment by Aokromes** [comment]
plz try downloading official non-flatpak non-snap version from https://desktop.telegram.org

**Comment by Reno-Sifana** [comment]
It seems that after I tried one more time it turned out that I could play videos on the Telegram desktop from flatpak
