### ISSUE TITLE
Crash on Archlinux if remote call turns on video

### ISSUE THREAD

**Issue by alexzk1** [telegramdesktop/tdesktop#25450]
### Steps to reproduce

1. Incoming VIDEO crashes telegram:
telegram-deskto[1302]: segfault at 40 ip 00007f3e8a97dd0d sp 00007ffdc6e89a88 error 4 in libc.so.6[7f3e8a83b000+15b000]

### Expected behaviour

It should not crash

### Actual behaviour

It crashes.

### Operating system

Linux mymsi 6.0.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 16 Nov 2022 17:01:17 +0000 x86_64 GNU/Linux

### Version of Telegram Desktop

4.3.4

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Can you reproduce on the official binary from https://desktop.telegram.org?

**Comment by alexzk1** [comment]
That binary works if launched standalone.

**Comment by ilya-fedin** [comment]
nice, you can use it
