### ISSUE TITLE
Bad tray icon Windows

### ISSUE THREAD

**Issue by grandsilence** [telegramdesktop/tdesktop#2546]
After update tray icon message counter now is unreadable. It's very blurred.
Screen resolution: 1920x1080. 
[![rex.png](https://s12.postimg.org/3m5tdc1j1/rex.png)](https://postimg.org/image/qav0cwiwp/)

**Version of Telegram Desktop:**
0.10.16 (OS: Windows 10).

**Comment by auchri** [comment]
https://github.com/telegramdesktop/tdesktop/commit/20d04a065e8699ddd285565bb1b026c5943a4be7

**Comment by john-preston** [comment]
https://github.com/telegramdesktop/tdesktop/commit/20d04a065e8699ddd285565bb1b026c5943a4be7 fixes this.

**Comment by stek29** [comment]
Why [build]?
