### ISSUE TITLE
Important groups are removed randomly in by the server

### ISSUE THREAD

**Issue by ILG2021** [telegramdesktop/tdesktop#25461]
Recently, some very important groups of mine were disappear when I was in a group call or just send some texts. It caused me a great loss, I don't think I violated any of the terms of service. It just happened recently. Other messenger platform will never dismiss groups even the owner is blocked. Even worse, Telegram give nothing about the removing and it happened randomly, it  scared me. Telegram don't have customer service, so I tried to send emails to the support email, no response. I don't know how to deal with the problem. I think it is may be caused by a bug of the server.
Telegram should make more improvements in the profit model, customer service and spam detection.

**Comment by Aokromes** [comment]
this is telegram desktop client bug tracker, not server bug tracker.
