### ISSUE TITLE
[Feature Request] Reply to the part of message.

### ISSUE THREAD

**Issue by roussak** [telegramdesktop/tdesktop#25464]
### Is your feature request related to a problem?

Let's consider a conversation where I've got a long text message with several sentences or something like. The main thing here is that the source message may contain several different points or ideas and I'd like to respond on one of them. For example, the conversation partner has wrote me something what I can't understand or I'm not sure if he/she has wrote some word right etc, so I'd like to clarify about this only part of his/her message. The Telegram app has no a tool to select a part of the source message and reply exactly on it.
The desired functionality presents in the Skype, for example.

### Describe the solution you'd like

Please, add the functionality described, so that the user can select a part of message and choose "Reply to selection" or something like. The selection only should be quoted instead of whole source message in the reply.

### Describe alternatives you've considered

The existing "Reply to" option isn't convenient sometimes. If consider the scenario with long message described here, I need first retype the quote which I'd like to reply on or query about, then write my message. For example: "You has wrote 'blah-blah-blah' and this is not quite clear to me".

**Comment by 23rd** [comment]
Sorry, such feature requests belong to another tracker. 

https://bugs.telegram.org/c/1050
