### ISSUE TITLE
[Feature Request] Please update version for apt package

### ISSUE THREAD

**Issue by Psychosynthesis** [telegramdesktop/tdesktop#25467]
### Is your feature request related to a problem?

It is not convenient to use standalone builds everywhere (there are many reasons). Snap also does not work satisfactorily.

The most convenient way is to install via apt. The problem is the old version of the application being installed - 3.6.1

The main problem is that if messages contain characters from the new functionality, users of the old version do not see the whole message (see screenshot).
![Screenshot from 2022-11-28 16-16-56](https://user-images.githubusercontent.com/32971513/204287776-c1a39952-770b-4600-88eb-37e02c866827.png)

### Describe the solution you'd like

Update apt package please.

And avoid situations in which users of older versions will not see the entire message BECAUSE OF USELESS EMOJI.

### Describe alternatives you've considered

Add regular updates to apt packages.

**Comment by Aokromes** [comment]
apt package depends on linux distribution, not telegram desktop.

**Comment by Aokromes** [comment]
> @Aokromes where to write, tell please.

debian only updates version x.x.x when they release new debian version (on 12). i recommend you to use static binary from webpage.

**Comment by ilya-fedin** [comment]
Not to mention Debian hardly patches tdesktop and removes various featues, e.g. noise suppresion in calls, `tg://` scheme registration code, wallpaper synchronization, big emojis coloring, custom allocator that gets rid of memory leaks.

They also break various parts of the Wayland integration.
