### ISSUE TITLE
Flatpak Changes have Resulted in Undesired Notification Sound in KDE

### ISSUE THREAD

**Issue by DarkArc** [telegramdesktop/tdesktop#25469]
### Steps to reproduce

1. Install the Telegram Flatpak on a desktop using KDE
2. Ensure desktop notifications are enabled (in Settings -> Notificiations and Sounds)
3. Receive a message

### Expected behaviour

No sound plays.

### Actual behaviour

Oxygen-Sys-Special.ogg plays.

### Operating system

Fedora 37

### Version of Telegram Desktop

v4.3.2

### Installation source

Flatpak

**Comment by DarkArc** [comment]
Additional information can be found here: https://bugs.kde.org/show_bug.cgi?id=462357

**Comment by nicolasfella** [comment]
This is not a Telegram issue. It's an "issue" with Plasma's notification portal implementation

**Comment by ilya-fedin** [comment]
It's not only sound, actually, but also the buttons. While testing the notification behavior I myself filed multiple bug reports in the KDE bugtracker:
https://bugs.kde.org/show_bug.cgi?id=462278
https://bugs.kde.org/show_bug.cgi?id=462283

This should make the behavior way better as a workaround:
```
sed -i 's/org.freedesktop.impl.portal.Notification;//' /usr/share/xdg-desktop-portal/portals/kde.portal
systemctl --user restar xdg-desktop-portal
```

**Comment by DarkArc** [comment]
@ilya-fedin thanks for the response! I was hoping to at least get confirmation that you guys had switched to using this portal. 

Also, thanks a ton for the workaround; that works!

**Comment by ilya-fedin** [comment]
> though I'm not entirely sure how/maybe by taking KDE's portal implementation out of the equation?

Both gtk and kde implementations forward the notification to org.freedesktop.Notifications (the gtk one also tries org.gtk.Notifications first, though), but the gtk implementation does that way better.
