### ISSUE TITLE
Crash when in a video call the other person activates their camera 

### ISSUE THREAD

**Issue by crstian19** [telegramdesktop/tdesktop#25473]
### Steps to reproduce

1. Open a call.
2. The other person have to activate their camera.
3. Telegram crash.

### Expected behaviour

Video calls should work properly.

### Actual behaviour

Telegram crash.

### Operating system

Sway,Wayland on Arch Linux

### Version of Telegram Desktop

4.3.4

### Installation source

Other (unofficial) source

### Logs

```shell
No logs generated when the bug reproduced
```

**Comment by Aokromes** [comment]
distribution bug.
