### ISSUE TITLE
[Question] is it possible to disable visual notification popups for a specific chat?

### ISSUE THREAD

**Issue by of-me-is** [telegramdesktop/tdesktop#25475]
is there a way to disable visual notification popups on windows 10 for a certain chat WITHOUT muting that chat or disabling all desktop notifications completely? it's really annoying when a billion notifications from someone keep popping up on the screen.

i still want to have certain notifications come through so i can see them (for example, from groupchats or bots or other people), just not from a certain person. but i also don't want to mute that person to still get their notifications on my phone.

**Comment by ilya-fedin** [comment]
No, it's not possible
