### ISSUE TITLE
[Feature Request] built-in theme set and selector in settings

### ISSUE THREAD

**Issue by linbows** [telegramdesktop/tdesktop#25478]
### Is your feature request related to a problem?

The mobile app was recently updated with a set of built-in themes and way to change them in app settings. Has adding such option to the desktop client been considered yet?

### Describe the solution you'd like

The ability to change built-in themes from within the app settings

### Describe alternatives you've considered

Manually applying themes from theme channels

**Comment by ilya-fedin** [comment]
tdesktop always had built-in themes
![изображение](https://user-images.githubusercontent.com/17829319/204877690-297d2f3e-ab3b-4823-916e-c053d0bbe14f.png)

**Comment by linbows** [comment]
Wow, never knew it was there. Thank you
