### ISSUE TITLE
[Feature Request] Allow archiving of group topics

### ISSUE THREAD

**Issue by ShizCalev** [telegramdesktop/tdesktop#25479]
### Steps to reproduce

Some users would like the ability to hide certain topics that are not pertinent to them (IE game announcements or something like that), however there is not an option to, meaning the group gets bumped for ALL users regardless if they have the topic muted or not.

### Expected behaviour

Ability to hide topics within groups

### Actual behaviour

You always see all topics.

### Operating system

Windows 10

### Version of Telegram Desktop

4.3.3 x64

### Installation source

Static binary from official website

**Comment by ShizCalev** [comment]
Likewise, having the ability to not automatically open the topic that was last replied to when clicking on the group in the chat list would VERY MUCH be appreciated

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by john-preston** [comment]
@ShizCalev The opening of the latest updated topic was released recently.
