### ISSUE TITLE
[Feature Request] Start Telegram with a specified account using the command line

### ISSUE THREAD

**Issue by xmha97** [telegramdesktop/tdesktop#25474]
### Is your feature request related to a problem?

Not really - it's just a missing feature.

### Describe the solution you'd like

Hello Telegram team,
I want to start Telegram with a specified account using the command line.
In Chrome, this is easily possible:
```
"C:\Program Files\Google\Chrome\Application\chrome.exe" --profile-directory="Profile 1"
```
```
"C:\Program Files\Google\Chrome\Application\chrome.exe" --profile-directory="Profile 2"
```
I need this feature, please implement it.
Thanks.

### Describe alternatives you've considered

I want several shortcuts on my desktop, each opening an account.

**Comment by ilya-fedin** [comment]
What you want is probably `-workdir` and it already exists. It doesn't switch accounts though, but profile directories (when you add multiple accounts via UI, they share profile directory).
