### ISSUE TITLE
Failed download files

### ISSUE THREAD

**Issue by evgeniyworkbel** [telegramdesktop/tdesktop#25485]
### Steps to reproduce

1. a person sents you a file (for instance, pdf)
2. you open chat with him
3. file automatically tries to download
4. it requests fo choosing folder
5. you choose folder
6. download process fails

And it's impossible to repeat download because of no actions for clicking on file

### Expected behaviour

Download files without fails and asking about choosing folder

### Actual behaviour

Download files with fails and asking about choosing folder, although  folder request option switches off in Settings

### Operating system

Ubuntu 22.04 LTS

### Version of Telegram Desktop

4.3.4

### Installation source

Flatpak

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by evgeniyworkbel** [comment]
> plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

I have just downloaded app through command-line `sudo apt install telegram-desktop` version 3.6.1 and i'm surprising: app crashes in moment of switching accounts.

P.S. I wanna install tg using sources .tar, but desktop.telegram.org doesn't contain info about steps of installation

**Comment by ilya-fedin** [comment]
> P.S. I wanna install tg using sources .tar, but desktop.telegram.org doesn't contain info about steps of installation

Like on Windows: extract the archive and run Telegram binary

**Comment by ilya-fedin** [comment]
it should create the launcher on first launch, try to restart your system
