### ISSUE TITLE
Do "not disturb" mode on Gnome Desktop shows Telegram notifications

### ISSUE THREAD

**Issue by ramilrgk** [telegramdesktop/tdesktop#25486]
### Steps to reproduce

1. Enable the use of system notifications in Telegram Desktop
2. Enable Do Not Disturb Mode in Gnome Notification Bar

### Expected behaviour

Notifications should not be displayed. They must pass the content of the notifications to the system notification handler. Which will save them in the Gnome notification center

### Actual behaviour

Notifications are displayed using the Telegram Desktop notification handler. Despite the enabled function of using only system notifications in the Telegram Desktop settings

### Operating system

OS: Pop!_OS 22.04 LTS x86_64. DE: GNOME 42.3.1

### Version of Telegram Desktop

4.3.4

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Can you provide screencast of the issue?
