### ISSUE TITLE
Telegram constantly crashes when Internet connection is unavailable

### ISSUE THREAD

**Issue by skyjack** [telegramdesktop/tdesktop#2548]
### Steps to reproduce
1. Start telegram
2. Turn off Internet connection
3. Try to send message/open received image
### Expected behaviour

TG should not crash
### Actual behaviour

Crash dump is generated
### Configuration

**Operating system:** Darwin MacBook-Pro.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64

**Version of Telegram Desktop:**2.27.51100
[Telegram_2016-10-20-224416_MacBook-Pro.crash.zip](https://github.com/telegramdesktop/tdesktop/files/542751/Telegram_2016-10-20-224416_MacBook-Pro.crash.zip)
### Logs

Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by john-preston** [comment]
@skyjack Can you provide a crash report tag here?

**Comment by skyjack** [comment]
@john-preston I've uploaded crash dump. How to add crash report tag?

**Comment by john-preston** [comment]
@skyjack I guess this is not Telegram Desktop, but another macOS app. You can try Telegram Desktop from https://desktop.telegram.org

**Comment by f-squirrel** [comment]
@john-preston  I guess it is Telegram Desktop..

![screen shot 2016-11-11 at 18 48 31](https://cloud.githubusercontent.com/assets/1248133/20222832/886af524-a83f-11e6-8ce0-873048bc619c.png)

**Comment by john-preston** [comment]
@f-squirrel No, this is another application for macOS. You can try out Telegram Desktop from https://desktop.telegram.org.
