### ISSUE TITLE
Screensharing Games at various qualities (Advanced)

### ISSUE THREAD

**Issue by IRIxAgent47** [telegramdesktop/tdesktop#25483]
### Steps to reproduce

1. Start screenshare
2. Set game to borderless or fullscreen
3. Playback quality is variable quality mb/s @ 3 fps no matter what unless the frames are similar

### Expected behaviour

When you click to capture your screen you should be allowed to change the bitrate, fps, and have a compression method that's quality is not based on still images and can adapt for motion such has h.264

The compression is only being done on the first core which the first 4 are usually the busiest during a game engine running and its affinity is protected by anti-cheat. There is no multi-thread support.

### Actual behaviour

I have tried using the OBS Virtual Camera just to get control over the input resolution to recover some bitrate incase there was a limit all the way down to 720p and 480p.
The result is the similar. Does not matter the resolution and the fps is maxed at 5 fps unless you are standing still.
The video compressor is horrendous.
Did the screenshare/stream feature accidently use a TCP connection and not a UDP?

Specs:
Ryzen 9 5950x (32 cores)
6900xt (16 GB VRAM)
64 GB @ 4000 Mhz
2 TB m.2 @ 7Gb/s

ISP:
200/20
CloudFlare DNS

### Operating system

Windows 10 / 11 Pro

### Version of Telegram Desktop

4.3.3 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#16487
