### ISSUE TITLE
Video control does not auto hide in Windows touch mode, with no mouse.

### ISSUE THREAD

**Issue by tigerinus** [telegramdesktop/tdesktop#25499]
### Steps to reproduce

1. Play a video in any channel 
2. Switch to full screen 

### Expected behaviour

After few seconds the video control auto hides

### Actual behaviour

The video control auto hides occasionally, but not always 

### Operating system

Windows 10

### Version of Telegram Desktop

4.3.3 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
It hides the controls if mouse is not over them and doesn't hide if mouse is over controls. Is this what happens in your case?

**Comment by tigerinus** [comment]
> It hides the controls if mouse is not over them and doesn't hide if mouse is over controls. Is this what happens in your case?

In my scenario there is no mouse cursor. It's a tablet running Windows with touch enabled.

**Comment by john-preston** [comment]
What if you tap outside of the controls area (maybe twice if it pauses the video to resume it), will it definitely hide the controls?

**Comment by tigerinus** [comment]
I tried tapping outside the control area in the first place when I found this issue. No luck.

Also tried rotating screen. Tried different resolutions....also many other things. No luck.

**Comment by john-preston** [comment]
@tigerinus Yes, I can reproduce that. Thank you. I'll try to fix it in one of the upcoming versions (not today's 4.5.1, but maybe the next one after that).
