### ISSUE TITLE
When I copy nickname it's copying it with https://t.me/

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25498]
### Steps to reproduce

1. Go to https://t.me/tassmessage_bot
2. Click on nickname
3. It's copy https://t.me/tassmessage_bot, not @tassmessage_bot as before

Same issue with users nicknames

### Expected behaviour

When user click on user or bot nickname it's must copy @tassmessage_bot, not https://t.me/tassmessage_bot

### Actual behaviour

When user click on user or bot nickname it's copy https://t.me/tassmessage_bot, not @tassmessage_bot

### Operating system

Windows 10

### Version of Telegram Desktop

4.3.3

### Installation source

Static binary from official website

**Comment by c0re100** [comment]
wait for next version
https://github.com/telegramdesktop/tdesktop/commit/c39b9e9635f4fddf7af86438c6fe24e19e788e45

**Comment by Neurotoxin001** [comment]
After the update will be a choice - with or without https://t.me?

**Comment by Aokromes** [comment]
content -> copy username, click t.me
