### ISSUE TITLE
Bot WebView blazor

### ISSUE THREAD

**Issue by M1XGear** [telegramdesktop/tdesktop#25491]
Folow up for existing (closed) question:
https://github.com/telegramdesktop/tdesktop/issues/24469

I'm also trying to run blazor up in the bot webview using Telegram Desctop for Windows verison 4.3.3 x64 and foun out that Telegram is using Chrome 70.

How to force telegram to use newer version of Chromium?

**Comment by ilya-fedin** [comment]
You can only wait until MS will update Chromium version in the OS.

**Comment by ilya-fedin** [comment]
Remember that macOS and Linux provide WebKit, so your bot should be ready for engines not supporting most modern technologies
