### ISSUE TITLE
[BUG] Show Translate Button problem

### ISSUE THREAD

**Issue by APT-ZERO** [telegramdesktop/tdesktop#25496]
### Is your feature request related to a problem?

I set 'Do Not Translate' to English, when a post is in another language, but when there is a single English word in a nonEnglish post, Tg will not show Translate on that post

### Describe the solution you'd like

Add a None option in 'Do Not Translate'
and for selecting the language to translate to, add another list

### Describe alternatives you've considered

When there is even 1 non English word in post, show translate button for post

**Comment by 23rd** [comment]
Can you provide any example?

**Comment by 23rd** [comment]
Okay, will be fixed in the next release.
