### ISSUE TITLE
Freezes on search result / pinned messages

### ISSUE THREAD

**Issue by VetaLioSTV** [telegramdesktop/tdesktop#25494]
### Steps to reproduce

Search something that has a lot of results( lets say 10+) either click on pinned messages in chat which are also more than 10+. 

### Expected behaviour

You can jump(click) on every result / item incrementally with no issue.

### Actual behaviour

After clicking on **5-8 in row results \ items**(if you will do it too faster then you can reach **maybe**(?) more then 8, since something brokes in that time, like HTTP request throw exceptions, i dont know) its became frozen(broken) with zero reaction on interaction.

### Demo

https://user-images.githubusercontent.com/15155286/205484447-96e15331-5069-4741-95b2-36790d4806ed.mp4

### Operating system

Windows 8.1 x64

### Version of Telegram Desktop

v4.1.1 - v4.3.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz, open task manager when telegram freezes, then right click over telegram -> create dump and send to https://t.me/preston

**Comment by VetaLioSTV** [comment]
> plz, open task manager when telegram freezes, then right click over telegram -> create dump and send to https://t.me/preston

Sorry, maybe i explained incorrectly, telegram client(UI) itself not freezes, but searchbar with results \ pinned chats are became freezed, UI is not blocked, but no reaction on search bar\pinned chats.

**Comment by VetaLioSTV** [comment]
@Aokromes still reproduceable on `4.4.1 x64` (try to check it with pinned messages in personal chat, its brakes everytime after 5-7 times of clicking in row)

**Comment by Neurotoxin001** [comment]
Same issue on 4.4.1 windows 10. At first I thought it was because I had a new account (registered less than 2 months ago), but apparently not.

**Comment by VetaLioSTV** [comment]
> Same issue on 4.4.1 windows 10. At first I thought it was because I had a new account (registered less than 2 months ago), but apparently not.
> 
> And no "flood wait" errors in logs btw. Also I have premium (I mention it because of this - https://t.me/tginfo/3519) and don't have any spam ban.

I think this issue has roots from summer/autumn updates. It has the same scenario(i already described here in [#25534 ](https://github.com/telegramdesktop/tdesktop/issues/25534) )for personal chat while searching / jumping at specific date through calendar, which causes unexpected results.(sometimes it show at least something, sometimes it breaks and you see blank screen like there isn't any message in chat and etc)

**Comment by Neurotoxin001** [comment]
> in personal chat, just search something with a lot of results or jump at specific day (which is older than 4-5 months) ?

I don't have such chats

**Comment by VetaLioSTV** [comment]
> an reproduce too on 4.4.1 x64.

Unfortunately i remember such behavior from summer updates(i guess it has roots from **v4.1.1** August release).

In personal chats it easy to reproduce with pinned messages...

**Comment by john-preston** [comment]
I could reproduce but I got a lot of FLOOD_WAIT_X errors in mtp_ logs, so I think this is server limiting the history requests amount. So it looks like a server side restriction to me.

**Comment by VetaLioSTV** [comment]
> I could reproduce but I got a lot of FLOOD_WAIT_X errors in mtp_ logs, so I think this is server limiting the history requests amount. So it looks like a server side restriction to me.

Some breaking change on server side? This problem occurs everywhere and definitively it wasn't like in previous version( i think before august updates~). 
It easy to reproduce in personal chat, when you click on pinned chats (its not required to do it faster, just do it sequently and slow), absolutely the same when you search something with a lot of results or you jump at specific date (lets say several months ago, please check description #25534). I think something broken on server side :(.

**Comment by john-preston** [comment]
@VetaLioSTV How many pinned messages can you see before a significant (like, five-to-ten seconds) delay in a private chat? From app launch.

**Comment by Neurotoxin001** [comment]
I pinned (only for me) 13 messages in private chat with my friend (not a group) then I go to new messages and start clicking on pinned messages by round. I got "flood wait" and can't click anymore (but it's still not in logs with disabled debug) after 15 clicks. All messages was posted in november-december, so they not so old. And yes, this problem is relatively recent.

**Comment by john-preston** [comment]
FLOOD_WAIT don't go to log.txt, only to DebugLogs.

**Comment by VetaLioSTV** [comment]
> @VetaLioSTV How many pinned messages can you see before a significant (like, five-to-ten seconds) delay in a private chat? From app launch.

**Five**!! I even tested without delay (clicks in row, but not ultra fast) and with delay 5 seconds as you proposed, result is the same => five pinned messages is accessible then "flood_wait_x" as you called before.

**Comment by VetaLioSTV** [comment]
@john-preston problem still remains, why issue was closed?...

**Comment by Aokromes** [comment]
it¡s fixed on 4.5.2 not on 4.5.1

**Comment by john-preston** [comment]
@VetaLioSTV It should be better in 4.5.1. Well, it should be the same as before October 2022, when this regression was introduced. New flood wait errors (after version 4.5.1) should be relatively the same as mobile apps or web apps.

**Comment by VetaLioSTV** [comment]
> @VetaLioSTV It should be better in 4.5.1. Well, it should be the same as before October 2022, when this regression was introduced. New flood wait errors (after version 4.5.1) should be relatively the same as mobile apps or web apps.

Sorry, so you just increased constants value from 10/30 to 30/50, but in fact problem still remains and it's not fixed.

```
constexpr auto kMessagesPerPageFirst = 10;
constexpr auto kMessagesPerPage = 10;
```

```
constexpr auto kMessagesPerPageFirst = 30;
constexpr auto kMessagesPerPage = 50;
```

**Comment by Neurotoxin001** [comment]
Now it's not a problem. 10 clicks was a problem, now it's stucks for me only after ~30 clicks. Same as before 1 nov https://github.com/telegramdesktop/tdesktop/commit/1e8dfb73153c8c54536fd5d1c45525babdf4f645#diff-522c93fe30817763ca7097e50ed616c93dc7a4f593887ae705bb66a32376cbe2

**Comment by VetaLioSTV** [comment]
> Now it's not a problem. 10 clicks was a problem, now it's stucks for me only after ~30 clicks. Same as before 1 nov [1e8dfb7#diff-522c93fe30817763ca7097e50ed616c93dc7a4f593887ae705bb66a32376cbe2](https://github.com/telegramdesktop/tdesktop/commit/1e8dfb73153c8c54536fd5d1c45525babdf4f645#diff-522c93fe30817763ca7097e50ed616c93dc7a4f593887ae705bb66a32376cbe2)

but it shouldn't be stuck / blocked, since previously it worked like charm!(no matter after 2-3 clicks or 100+)
I have a lot of pinned messages in personal chats, that increasing values from 10/10 to 30/50 doesn't help me a lot..
