### ISSUE TITLE
[Feature Request] Distribute x64 Windows builds

### ISSUE THREAD

**Issue by kr4us3r** [telegramdesktop/tdesktop#25490]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I understand that there's a guide here on how to do that by yourself, but could you also distribute 64-bit binaries along with 32-bit ones for Windows in releases?

### Describe alternatives you've considered

None

### Additional context

It is quite well known that 64-bit programs run a little bit faster https://stackoverflow.com/questions/2378399/are-64-bit-programs-bigger-and-faster-than-32-bit-versions

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v4.3.3 telegram desktop already ships windows x64 versions.

**Comment by kr4us3r** [comment]
I have been running the 32-bit version for a while and now looked only at 4.3.4 release. Sorry for a dumb issue

**Comment by john-preston** [comment]
@kr4us3r Right now the 64 bit version should be downloaded by default from https://desktop.telegram.org, but the 32 bit version still auto-updates to 32 bit version.
