### ISSUE TITLE
This is what I miss in *Telegram Desktop*:

### ISSUE THREAD

**Issue by akbarjonjorayev** [telegramdesktop/tdesktop#25493]
### Is your feature request related to a problem?

**1. Please add animation when opening media files.
2. Add the ability to make video calls, video message and send geolocation.
3. Add more animation.**

### Describe the solution you'd like

1. Please add animation when opening media files.
2. Add the ability to make video calls, video message and send geolocation.
3. Add more animation.

### Describe alternatives you've considered

1. Please add animation when opening media files.
2. Add the ability to make video calls, video message and send geolocation.
3. Add more animation.

**Comment by akbarjonjorayev** [comment]
Telegram Desktop 4.3.3 x64

**Comment by ilya-fedin** [comment]
tdesktop already capable for video calls, for everything else there are already existing issues

**Comment by Aokromes** [comment]
3 things on a single issue, 3 duplicated.

**Comment by akbarjonjorayev** [comment]
> tdesktop уже способен на видеозвонки, на все остальное уже есть проблемы

But you will add animation, yes ✅.

**Comment by akbarjonjorayev** [comment]
Why https://t.me/preston does not answer?
