### ISSUE TITLE
Telegram hijacking iTunes macOS/OSX media keys

### ISSUE THREAD

**Issue by mcescalante** [telegramdesktop/tdesktop#2549]
Just updated to 0.10.16 with a "new audio player" and noticed that my media keys stopped working when Telegram Desktop was open. They work great the second I quit Telegram Desktop.

### Steps to reproduce
1. Open iTunes and Telegram Desktop on macOS/OSX
2. Leave iTunes in the background for more than 20 seconds with music playing in it
3. Try to pause via the media key, nothing happens
4. Quit Telegram, try pausing again
5. Pausing works

### Expected behaviour
Media keys should not be hijacked by Telegram Desktop

### Actual behaviour
Media keys do not behave when Telegram Desktop is open, even if both iTunes and Telegram are in background.

### Configuration
**Operating system:** OSX 10.11.2
**Version of Telegram Desktop:** 0.10.16

**Comment by mcescalante** [comment]
As a temporary solution for anyone else suffering this issue, you can install the macOS specific application (https://macos.telegram.org/)

I prefer Telegram Desktop and am hoping I can switch back soon :)

**Comment by stek29** [comment]
Can you control TDesktop music player by buttons?

**Comment by mcescalante** [comment]
> Can you control TDesktop music player by buttons?

No it doesn't seem like I can. Just tried it with both audio and video and the controls weren't responding within Telegram Desktop.

I also noticed that if there is another program (for example, VLC) in the foreground the media key functions behave again. But once I click on any other program (like TextEdit) the media keys stop functioning until I quit Telegram Desktop

**Comment by mcescalante** [comment]
Just updated to 0.10.18 and can confirm that this is fixed 🎉. Thank you so much @john-preston! Going to close this, but feel free to reopen it if that's an issue.

**Comment by john-preston** [comment]
@mcescalante Yes, now they're hijacked only when you listen to a music file inside Telegram Desktop.
