### ISSUE TITLE
Missing pinned message of streaming(Live) geolocation

### ISSUE THREAD

**Issue by VetaLioSTV** [telegramdesktop/tdesktop#25507]
### Steps to reproduce

Previously when someone shared geolocation with you ( 15min \ 1 hour \ 8 hours ), above pinned message appeared another one  pinned message of current streaming(live) geolocation with timer which shows remaining time.
It still works as it should on mobile clients (pinned message of live geo is present).

### Expected behaviour

Live geolocation should be shown as pinned message above pinned messages in chat.

### Actual behaviour

Nothing happens, information about live geolocation is missing.

### Operating system

Windows 8.1 x64

### Version of Telegram Desktop

v4.0 - v4.3.2

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
It never worked that way in Telegram Desktop. But this may be a feature request.

**Comment by VetaLioSTV** [comment]
> 

No, it was. Could you check pre v4.0 build and run test? I used it frequently and it worked like how i have described.

**Comment by john-preston** [comment]
@VetaLioSTV You can check yourself, here are all the releases:

https://github.com/telegramdesktop/tdesktop/releases

For example, here is the version 3.5.1:

https://github.com/telegramdesktop/tdesktop/releases/tag/v3.5.1

You can check any other you like. Please show a screenshot (from any version of Telegram Desktop) what are you talking about.

**Comment by VetaLioSTV** [comment]
> @VetaLioSTV You can check yourself, here are all the releases:
> 
> https://github.com/telegramdesktop/tdesktop/releases
> 
> For example, here is the version 3.5.1:
> 
> https://github.com/telegramdesktop/tdesktop/releases/tag/v3.5.1
> 
> You can check any other you like. Please show a screenshot (from any version of Telegram Desktop) what are you talking about.

@Nashev could you confirm my description ?

@john-preston i will try to found my old screenshot with it..

**Comment by Nashev** [comment]
I have tried install and check 3.5.1, and it now does not show Live geolocation info for me.
I have also tried https://github.com/telegramdesktop/tdesktop/releases/tag/v3.0.0, but it request update instead of authorize.

Personally I does not sure it was in desktop. I so often use mobile client, I can miss something.

**Comment by VetaLioSTV** [comment]
> I have tried install and check 3.5.1, and it now does not show Live geolocation info for me. But it can be because it does really not supports, or because any possible protocol changes...
> 
> I have also tried https://github.com/telegramdesktop/tdesktop/releases/tag/v3.0.0, but it request update instead of authorize.
> 
> Personally I does not sure it was in desktop. I so often use mobile client, I can miss something.

No, it was 100% on desktop client. I'm trying to find in my personal chat(screenshot)

**Comment by john-preston** [comment]
It was never implemented in Telegram Desktop, sorry 🙈

**Comment by VetaLioSTV** [comment]
@john-preston no, it was, but you're trying to say that its kinda "Mandela effect"?:)) I used it frequently in from may till august(2022) and message of live streaming was shown on top of pinned messages. 

OK, let me download portable version and i will come back soon.

**Comment by john-preston** [comment]
@VetaLioSTV Livestreaming in channels. Not geolocation.

**Comment by Nashev** [comment]
@john-preston Could You answer to the VetaLioSTV's question? "Can it be easily added on desktop for consistent look as how it works in mobile clients (iOS \ Android) ?"

About share Live Location, not about any live streaming in channels...

**Comment by VetaLioSTV** [comment]
> @VetaLioSTV Livestreaming in channels. Not geolocation.

Ok, maybe i did use incorrect terminology, i meant  `streaming geolocation == live geolocation( 15 min / 1 hours / 8 hours)`. 

As mentioned @Nashev my quote, does it possible to add / implement same consistent look as how it works in mobile client now ?

**Comment by VetaLioSTV** [comment]
@john-preston as desktop client can't provide live geolocation itself, but at least let show provided live geolocation from corresponding client(mobile)...

**Comment by VetaLioSTV** [comment]
@john-preston okay 👌 , i will treat your silence as "**_молчание, знак согласия_**"  😆 , here you go #26060 😸
