### ISSUE TITLE
[Feature Request] Custom time for live geolocation

### ISSUE THREAD

**Issue by VetaLioSTV** [telegramdesktop/tdesktop#25508]
### Is your feature request related to a problem?

Currently when someone\you shares live geolocation for some reason only available three variant of time - 

1. **15 minutes**
2. **1 hour**
3. **8 hour**

Which for a lot of cases aren't enough.

### Describe the solution you'd like

Allow to introduce custom time for premium users and maybe(?) additional possibility to extend it automatically.

### Describe alternatives you've considered

Currently there is no alternatives, since you need to repeat same actions manually when time of live geolocation is passed.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by VetaLioSTV** [comment]
> platform wide bugs / requests belongs to https://bugs.telegram.org/

I'm sorry, but i do not understand what is the point of "feature request" here in github repo, since platform request should be raised on [bugs](https://bugs.telegram.org/) ?

**Comment by Aokromes** [comment]
this is telegram desktop bug tracker, not mobile phone bugtracker. and since telegram desktop doesn't ships live geolocation, you are very likely asking for a phone.

**Comment by VetaLioSTV** [comment]
> this is telegram desktop bug tracker, not mobile phone bugtracker. and since telegram desktop doesn't ships live geolocation, you are very likely asking for a phone.

ah, sorry. You're totally right, lol. I confused myself.
