### ISSUE TITLE
More fractional position for the screen scale.

### ISSUE THREAD

**Issue by vyalyh-oleg** [telegramdesktop/tdesktop#25504]
### Is your feature request related to a problem?

There are many HiDPI screens on the market and even more options for their configuration and use.
For now I use 150% scaling, but the fonts are small. The 200% is already too big.
-----
Desktop App v4.3.4
Linux Mint Cinnamon 20.3
(but i think the behavior is the same for all linux DE)

### Describe the solution you'd like

It would be grate to have the possibility of changing screen scaling with at least 25% step.

### Describe alternatives you've considered

Just use uncomfortable scaling.

**Comment by ilya-fedin** [comment]
#17326, #24485
