### ISSUE TITLE
chat selection resetted after re-opening Telegram window

### ISSUE THREAD

**Issue by stemar94** [telegramdesktop/tdesktop#2550]
### Steps to reproduce
1. Open a chat with some contact in Telegram Desktop.
2. Close the Telegram Desktop window.
3. Open Telegram again by clicking on the tray symbol or any other way.

### Expected behaviour
I should see the window in the state it was when closed, i.e., the chat previously opened should still be open.

### Actual behaviour
No chat is selected and the cursor is active in the search field.

### Configuration
**Operating system:**
Linux xxx-ThinkPad-E460 4.4.0-43-generic #63-Ubuntu SMP Wed Oct 12 13:48:03 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Version of Telegram Desktop:**
0.10.16

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#2541

**Comment by stemar94** [comment]
Sry I only checked the open ones.
What about a feature request then? It was better before.
