### ISSUE TITLE
Video freezes when watching high resolution video

### ISSUE THREAD

**Issue by Murka007** [telegramdesktop/tdesktop#25502]
### Steps to reproduce

I have a cheat laptop with low resolution, so it makes impossible to watch a high-resolution video. Play any video, but resolution of your monitor must be lower than of video.

### Expected behaviour

Video should play smoothly, without constant waiting for playback

### Actual behaviour

When I play a high resolution video, it plays for 2 seconds and loading for 5 seconds. Potentially this is caused by 4k resolution of a video, which makes my laptop run slowly.

### Operating system

Windows 10 Home x64 AMD A6-7310

### Version of Telegram Desktop

1.56.10

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
1.56.10? you must be joking. update to at least 4.3.3.

**Comment by Murka007** [comment]
I don't know, it is browser version of telegram. Probably because I use an old version of chrome `Version 96.0.4664.110 (Official Build) (64-bit)`
![image](https://user-images.githubusercontent.com/54054900/205722316-a24abe67-c936-47eb-b78d-82c6b8171df6.png)

**Comment by Aokromes** [comment]
this is telegram desktop bug tracker, not telegram web z bug tracker.

**Comment by Murka007** [comment]
well sorry for being so fucking stupid
