### ISSUE TITLE
After last update keeps crashing when reply "view in chat"

### ISSUE THREAD

**Issue by infinyao** [telegramdesktop/tdesktop#25518]
### Steps to reproduce

1. Update to 4.4
2. Open "Replies"
3. Press "View in chat"

### Expected behaviour

Opening discussion

### Actual behaviour

Crashing with
[2022.12.07 09:33:31] Assertion Failed! "size != std::nullopt" history_view_message.cpp:1593

### Operating system

Win10x64

### Version of Telegram Desktop

4.4

### Installation source

Static binary from official website

**Comment by infinyao** [comment]
[log.txt](https://github.com/telegramdesktop/tdesktop/files/10173782/log.txt)

**Comment by maiolika** [comment]
Same here.

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by infinyao** [comment]
ce811687-f60c-4c24-b130-31dbf27a30c2

**Comment by infinyao** [comment]
fixed on 4.4.1
