### ISSUE TITLE
desktop file name changes on every version update

### ISSUE THREAD

**Issue by valia0906** [telegramdesktop/tdesktop#25519]
### Steps to reproduce

To reproduce update telegram to newer version which creates desktop file with new name, which caused duplicates links in ubuntu menu Telegram Desktop. For example in version 4.3.4 file is called org.telegram.desktop.079631405c1c99733e2ba2f803a1fde5.desktop, in version 4.4.0 it called - org.telegram.desktop._079631405c1c99733e2ba2f803a1fde5.desktop

### Expected behaviour

Stable name of destop file on ubuntu.

### Actual behaviour

Duplicates menu items in ubuntu menu Telegram Desktop

### Operating system

Ubuntu

### Version of Telegram Desktop

4.3.4, 4.4.0

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Yeah, it was changed multiple times during last update, it deletes old ones though

**Comment by valia0906** [comment]
When I add Telegram Desktop to my panel the icon has dissappeared on each version update. What is the reason of renaming desktop files in each version? Previously Telegram has stable file name.

**Comment by ilya-fedin** [comment]
The reason is to be able to use GApplication (you can enable in experimental settings). Sadly, it wasn't done right first time as it's not compatible with a digit after a dot (what can happen with md5 hashes).

**Comment by valia0906** [comment]
@ilya-fedin  In the future file name will change on each version update?

**Comment by ilya-fedin** [comment]
If such changes will be required then yes. I hope no new bugs will be found with the current naming though.
