### ISSUE TITLE
If disabling `Update automatically` it will keep updating to the same version even if a new version is downloaded

### ISSUE THREAD

**Issue by Sopor** [telegramdesktop/tdesktop#25516]
### Steps to reproduce

You need to have `Update automatically` disabled.
Go to `Settings`.
Click `Advanced`.
Enable Update automatically.
If nothing happens click on `Check for updates` (you also need to have an older version, so it can update).
A new version will start to download.
When finished downloading, disable `Update automatically`.
Close `Settings`.
There will now be a message at the bottom left `UPDATE TELEGRAM`, click on it.
Telegram will close and start again.
Go to `Settings` and it is the same version as before the update.

### Expected behaviour

Telegram should update to version 4.4 (I was running 4.3.3)

### Actual behaviour

If i do as i explained above Telegram won't update.

I was running Telegram 4.3.3 and aften restart of Telegram it is still version 4.3.3.

I have done this several times and it continues to be version 4.3.3 if i update as i described.

Even older versions have the same behavior, so it seems to be an old issue.

### Operating system

Windows 10 x64

### Version of Telegram Desktop

4.3.3 (portable)

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Are you sure it ever behave differently? If yes, can you find first broken version? Otherwise it looks like intended behavior because the history of the relevant code suggests it was always like that (or at least for the most time of tdesktop existing). According to the code, it also seems that it will update if you quit Telegram after it's restarted after you've clicked the button (or if you haven't clicked at all and just quit Telegram), can you confirm that?

**Comment by john-preston** [comment]
Well, there is logic that if we disable automatic updates - that means we don't won't to update, so the downloaded update is ignored and the app is just relaunched.

Maybe it is better to update anyway in such flow. Any in-app update is considered "automatic" right now, the "manual" (non-automatic) update would be to download the new version from the web 😅

**Comment by Sopor** [comment]
@john-preston Disabling automatically updates is not the same as not update. It will not do it automatically, but i see no reason why manually update should not work.

Unfortunately i can't check for updates without enabling `automatically updates` and i can't even use the `Experimental setting` 😢

@ilya-fedin I have no idea when it started with this behavior. I noticed it in the version before 4.3.3, but i wanted to wait to see if it was a temporary issue in that version or not.

I also have to wait until there is a new update to test it again.

**Comment by ilya-fedin** [comment]
> I have no idea when it started with this behavior. I noticed it in the version before 4.3.3, but i wanted to wait to see if it was a temporary issue in that version or not.

the logic wasn't touched in ages, so I guess it's you changed your behavior (maybe previously you haven't checked right after update and it was updated after quit, due to reboot or something).

**Comment by Sopor** [comment]
@ilya-fedin I haven't done it this way before. I was so tired of going in to settings every time i did an update to disable automatically updates, so i was trying another way and first i thought it was working until i noticed that there was updates too often and when i checked the version i could see it was the same version after an update.

**Comment by ilya-fedin** [comment]
It always was like that and sadly according to @john-preston it's the intended behavior. If you want to update, you need to disable auto-updates.

**Comment by Sopor** [comment]
Odd and strange behavior in my opinion ...
