### ISSUE TITLE
Screen share prview is mirrored during call

### ISSUE THREAD

**Issue by BANOnotIT** [telegramdesktop/tdesktop#25515]
### Steps to reproduce

Start screen sharing during  a call

### Expected behaviour

Camera preview should be mirrored and screen share preview should not be mirrored

### Actual behaviour

Preview is mirrored regardless of source

### Operating system

Ubuntu 18.04.6

### Version of Telegram Desktop

4.3.4

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
It should be fine in 4.4.3 beta.
