### ISSUE TITLE
Create Group or Channel is unavailable

### ISSUE THREAD

**Issue by ADarwiesh** [telegramdesktop/tdesktop#25514]
### Steps to reproduce

Menu -> New Group / New Channel
Enter Group / Channel Name
In case of group, select users.
Click «Create»

### Expected behaviour

New Group or Channel was created

### Actual behaviour

Error window: «Sorry, this action is unavailable». Channel or Group doesn't create. This bug always show for a 1.5 years.
![60170098-45913e00-9821-11e9-99d2-def64598e85a](https://user-images.githubusercontent.com/80505122/206051460-4ad7ad92-46dd-45dc-9b4e-952eb5b6d25f.png)

### Operating system

Windows 10

### Version of Telegram Desktop

4.3.3

### Installation source

Static binary from official website

### Logs

```shell
I'm using Telegram since 2018 year, real person, never spam or send messages to unknown peoples.
```

**Comment by RememberTheAir** [comment]
Does it work from other Telegram apps?
