### ISSUE TITLE
Telegram not respecting Phonon GStreamer output settings under Linux

### ISSUE THREAD

**Issue by Sandvich** [telegramdesktop/tdesktop#2551]
### Steps to reproduce
1. Multiple sound cards connected. (Note: I currently have three active - HDMI, PCI sound card and USB headphones).
2. Change default/current sound card for audio stream from Telegram (done via KDE System Settings)

### Actual behaviour
Instead of changing to the selected sound card, Telegram continues to use the default.
Going back to the settings menu and then reselecting Multimedia (the menu under which you can change the sound card for each audio stream) results in the default sound card still being selected.
Changing the preference for sound cards seems not to affect anything (but I haven't experimented much with this).

### Configuration
**Operating System: Fedora 24 KDE spin**

**Version of Telegram Desktop: 0.10.16**

**Comment by stek29** [comment]
#776?

**Comment by Sandvich** [comment]
Yes, that looks right. My mistake.
I had assumed that this was a Linux-only issue, and so searched issues with 'linux' + various linux audio backends. Thanks!
