### ISSUE TITLE
Telegram crashes when trying to view a message from the replies chat

### ISSUE THREAD

**Issue by i701** [telegramdesktop/tdesktop#25520]
### Steps to reproduce

1. Join a channel
2. Join or not join the channel comment chat (optional)
3. click `View in chat` when someone replies to a comment of yours in that channel from the "Replies" Chat

![image](https://user-images.githubusercontent.com/72292943/206138621-83f9c53f-2299-4e66-aaac-44de22e3da8f.png)

4. Once you click, telegram crashes. 

### Expected behaviour

Expected behavior is to redirect user to the channel comments chat without crashing. 

### Actual behaviour

The application crashes and exits automatically. 

### Operating system

Windows 10

### Version of Telegram Desktop

4.4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by i0xHeX** [comment]
Beta enabled, version 4.4 (4004000)
`d62e3551-fbbe-4d93-9f6c-d6ae6f3217ea`

**Comment by goodwin74** [comment]
I have the same problem on Ubuntu 22.04. Version 4.4 Telegram Desktop.
When you click on the "View in chat" button, the application closes.
