### ISSUE TITLE
Notifications come with sound, even if sound is turned off in the settings

### ISSUE THREAD

**Issue by klonwar** [telegramdesktop/tdesktop#25529]
### Steps to reproduce

1. Disable notification sound in global settings
![image](https://user-images.githubusercontent.com/12374932/206421654-95630fec-2e5f-4319-a7b0-65401f84e4ee.png)
2. Disable notification sound in chat settings
![image](https://user-images.githubusercontent.com/12374932/206421766-25400a25-8b7f-48bd-ba2c-ff23778a47e2.png)
3. Wait for a message from the chat

P.S. Bug appeared after updating to 4.4.1.

### Expected behaviour

No sound played

### Actual behaviour

The standard notification sound is played even if the chat is open

### Operating system

Windows 10

### Version of Telegram Desktop

4.4.1 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
cannot reproduce, no sound for me where i have notifications disabled.

**Comment by klonwar** [comment]
Not reproducing anymore
