### ISSUE TITLE
Desktop Client does not show GPS live location sharing last update time and duration

### ISSUE THREAD

**Issue by Nashev** [telegramdesktop/tdesktop#25528]
### Steps to reproduce

1. Start location share live location from friend's mobile
2. Look at this from own moblie - see "updated just now" and (8h)

### Expected behaviour

3. Look at the same from Desktop - see "updated just now" and (8h)

(possibility to send any location from Desktop (#1193) will be also very pleasant, but here I not about this)

### Actual behaviour

3. Look at the same from Desktop - see sent time and nothing more.

And no understanding, is this location actual or it is already very outdated. It's sometimes very frustrating.

### Operating system

Windows

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by VetaLioSTV** [comment]
i already post [about it](https://github.com/telegramdesktop/tdesktop/issues/25507).

**Comment by Nashev** [comment]
@Aokromes, could You give link to commits, which fix this bug?

**Comment by VetaLioSTV** [comment]
> @Aokromes, could You give link to commits, which fix this bug?

I just tested right now, its absolutely in the same condition => doesn't show anything.

@Aokromes may i know why did you close issue?

**Comment by Nashev** [comment]
> > @Aokromes, could You give link to commits, which fix this bug?
> 
> I just tested right now, its absolutely in the same condition => doesn't show anything.

I haven't any updates till that date and still hope to see fixed behavior in the next release.

**Comment by Nashev** [comment]
Yes, I have update from that time and no related changes in it. Thank's for reopen, @john-preston !

**Comment by VetaLioSTV** [comment]
@Nashev but still zero reaction to my last comment at #25507 🔢

**Comment by Nashev** [comment]
This issue may be threated as duplicate for #26060
