### ISSUE TITLE
Crash when close PiP with video from deleted post

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25522]
### Steps to reproduce

1. Find any video that you don't opened and don't download (you must have disable autoplay and auto download)
2. Send it to your saved messages without sender name (to do that you must forward video to any chat, before press "send" open forward settings by clicking on forward preview, uncheck "show sender name", click "change recipient" and choose your saved messages)
3. Press play and open video in PiP (picture-in-picture)
4. Delete post with video from your saved messages
5. Press button on PiP to go back to full screen mode
6. Crash

`[2022.12.07 16:41:31] Assertion Failed! "ptr_ != nullptr" pointers:96`
Your Report Tag: a6bb9565-dc19-4d2b-8c79-1a93545c391f
Your Report Tag: 27c73a08-092b-4d1f-a145-b8e74e21b5ea

### Operating system

Windows 10

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by SpL1Ne** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25262
