### ISSUE TITLE
Anonymous administrator messages reveals it's owner by given custom titles

### ISSUE THREAD

**Issue by rayzru** [telegramdesktop/tdesktop#25532]
### Steps to reproduce

1. Mark admin with custom title
2. Make him anonymous
3. Anonymous admin message is posted 

### Expected behaviour

There is no custom titles for anonymous messages

### Actual behaviour

Anonymous message appeared with personal custom title

### Operating system

MacOS

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Can you check if the mobile application has the same behavior?

**Comment by rayzru** [comment]
Yes, confirm.

The other user perspective have that personal labels on anon messages

**Comment by john-preston** [comment]
This is expected then, the admin titles work that way intentionally. When you edit admin rights and make him anonymous you can remove the custom title as well.
