### ISSUE TITLE
invalid xdg desktop file in 4.4.1

### ISSUE THREAD

**Issue by henning-schild** [telegramdesktop/tdesktop#25533]
### Steps to reproduce

The new version contains a .desktop file which is not useable as is any longer. It seems more like a template where a cmake variable still needs to be filled in.

As a consequence the file can not be copied to /usr/share/applications/ as it is. It seems like the app would create a desktop file somewhere in the homedir. Not sure that is what people might want when the package is kind of coming via a distributions package manager. And that does not work for the "first start" ... very GUI driven users would not even know how to ever start the application when there is no launcher.

This is 4.3.4 vs. 4.4.1

```
@@ -1,8 +1,8 @@
 [Desktop Entry]
 Name=Telegram Desktop
 Comment=Official desktop version of Telegram messaging app
-TryExec=@CMAKE_INSTALL_FULL_BINDIR@/telegram-desktop
-Exec=@CMAKE_INSTALL_FULL_BINDIR@/telegram-desktop -- %u
+TryExec=telegram-desktop
+Exec=telegram-desktop -- %u
 Icon=telegram
 Terminal=false
 StartupWMClass=TelegramDesktop
@@ -16,6 +16,6 @@
 X-GNOME-SingleWindow=true
 
 [Desktop Action Quit]
-Exec=@CMAKE_INSTALL_FULL_BINDIR@/telegram-desktop -quit
+Exec=telegram-desktop -quit
 Name=Quit Telegram
 Icon=application-exit
```

### Expected behaviour

Tell us

### Actual behaviour

Tell us

### Operating system

Linux

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Sorry, but the templating is intended, you're not supposed to get the file from the repository.
