### ISSUE TITLE
Send with Ctrl+Enter not working anymore or random

### ISSUE THREAD

**Issue by Lvceo** [telegramdesktop/tdesktop#25538]
### Steps to reproduce

Under Linux Manjaro GNOME, using the "send with CTRL + ENTER" option in settings is not working anymore most of the time, sometimes yes, but rare. Revert to just "send with ENTER" works fine. Revert back to "send with CTRL + ENTER" doesn't help.

### Expected behaviour

Using the "send with CTRL + ENTER" as before.

### Actual behaviour

Ctrl+Enter is not sending the message anymore or for whatever reason work randomly from time to time

### Operating system

Linux 5.15

### Version of Telegram Desktop

Telegram Desktop 4.3.4

### Installation source

Other (unofficial) source

### Logs

```shell
no logs
```

**Comment by ilya-fedin** [comment]
Can't reproduce
