### ISSUE TITLE
Chat history breaks when searching / jumping on specific date

### ISSUE THREAD

**Issue by VetaLioSTV** [telegramdesktop/tdesktop#25534]
### Steps to reproduce

Hello, as i mentioned here [#25494](https://github.com/telegramdesktop/tdesktop/issues/25494), i began to experience same problems with chat history (i think under the hood it uses/reuses same logic and its server side problem(?)), when i jump to specific date (lets say several months ago), sometimes it shows only small portion of results (one visible page of messages) and after that it breaks, you can't do anything, other case it doesn't show anything at all as blank screen (like there is no messages) and sometimes it shows you more than one visible page of messages, you can scroll up/down, but anyway it will lock *somewhere* later.

My friend on Android tried to do same job with jumping on specific date through calendar, lets say also on three months ago and he had absolutely the same result (in his case he received blank screen, see photo) :
![image](https://user-images.githubusercontent.com/15155286/206472414-5650222e-f000-4e38-96e6-17435a66ce1f.png)

I dont know excatly what happened, but looks like it server side problem(like bottleneck or something else). @Aokromes does it  known problem or not? I remember same experience this summer, but unfortunately didn't paid corresponding attention on it! 

### Expected behaviour

Jump/search on any date you want with no issue.

### Actual behaviour

Sometimes its doesn't show result, sometimes it show only small portion of messages and then blocks/locks.

### Operating system

Windows 8.1 x64

### Version of Telegram Desktop

v4.1 - v4.4.1

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
https://bugs.telegram.org
