### ISSUE TITLE
Telegram crashes with certain window size on videos, etc.

### ISSUE THREAD

**Issue by reezer** [telegramdesktop/tdesktop#25539]
### Steps to reproduce

This will need [wmctrl](http://tripie.sweb.cz/utils/wmctrl/) installed, because it only happens on certain window sizes. 500,500 for example. This crash happens independently of wmctrl usage, it is just just to set the correct resolution for the window.

* Have a YouTube link in Saved Message (so there is a preview of the video)
* Install wmctrl to set position and size of windows
* Open Telegram
* Run wmctrl -l to get the window id of Telegram (the very left value)
* If you are on a tiling window manager (like i3) you have to get it out of tiling (Shift-Meta-Space per default on i3)
* Run wmctrl -i -r <id> -e 0,500,500,300,400 (the 500,500 is position, the 300,400 dimensions)
* This should resize your telegram window
* When you now click on Saved Messages the crash will occur

### Expected behaviour

Telegram should not crash.

### Actual behaviour

Telegram crashes with:
```
/opt/rh/devtoolset-10/root/usr/include/c++/10/bits/stl_algo.h:3677: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = int]: Assertion '!(__hi < __lo)' failed.
```

### Operating system

Linux (Arch Linux on i3)

### Version of Telegram Desktop

4.4.1 (occurs least since 4.0.2) - both official release and package

### Installation source

Static binary from official website

### Logs

```shell
/opt/rh/devtoolset-10/root/usr/include/c++/10/bits/stl_algo.h:3677: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = int]: Assertion '!(__hi < __lo)' failed.
```

**Comment by ilya-fedin** [comment]
Report this to your window manager, tdesktop sets supported minimum and maximum window size, but apparently your WM ignores this.

**Comment by reezer** [comment]
I understand that in general, but maybe a workaround to crashing could be made. Without knowing the details, I am thinking of displaying a message "Please increase your window size", not displaying any elements, if it is smaller, or maybe minimizing to the tray, not displaying messages, just the contact roster or similar.

Since the problem usually occurs during a call and opening either another window or telegram which previously was bigger from the tray. So even not displaying anything reasonable would be very much preferred over crashing.

**Comment by ilya-fedin** [comment]
This would mean all the widgets must be destroyed, so no actual code execution happens, this would mean some refactoring that is unlikely to be easier than refactoring widgets for smaller window sizes. Maybe refactoring to support smaller window sizes would be easier as there are widgets that constructed on application start and are expected to live all the application life time.
