### ISSUE TITLE
App crashes after click on picture in picture if enable OpenGL rendering for media.

### ISSUE THREAD

**Issue by Vladimir-A** [telegramdesktop/tdesktop#25535]
### Steps to reproduce

1. start video;
2. click on picture in picture;
3. app crashes.

### Expected behaviour

video on picture in picture

### Actual behaviour

app crashes

### Operating system

arch

### Version of Telegram Desktop

4.4.1

### Installation source

Other (unofficial) source

### Logs

```shell
App from arch repository

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  6.0.11-zen1-1-zen
    X Server Vendor:  The X.Org Foundation
    X Window Manager:  KWin

Video Card:
    Driver:  AMD AMD Radeon RX 6800 XT (navi21, LLVM 14.0.6, DRM 3.48, 6.0.11-zen1-1-zen)
    Driver Version:  4.6 (Compatibility Profile) Mesa 22.2.3

dmesg -T

telegram-deskto[21496]: segfault at 8 ip 00007efc6a16c84d sp 00007ffc5b9fe568 error 4 in libc.so.6[7efc6a03b000+15b000]
```

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
@Aokromes you can close, it's a crash due to Arch not using the tdesktop Qt patchset
