### ISSUE TITLE
[Feature Request] Automatic Inclusion of created Chats into the Chat Folder by a regexp against Chat Name

### ISSUE THREAD

**Issue by vkuvaev** [telegramdesktop/tdesktop#25530]
### Is your feature request related to a problem?

Using multiple chats following simple naming conventions, to distinguish, ext/int chats, customers etc.: 
Example:

Want to Have Folder with chats grouped by INT or EXT 
Folder: INT Chats
Chat name 1: [INT] <Some chat name>   
Chat Name 2: [INT] <Another chat name>  

Want to Have Folder with chats grouped by Customer
Folder: Acme customer
Chat name 1: [INT][Acme] <some name>
Chat Name 2: [EXT][Acme] <some name>

However have to maintain inclusion into chat Folders manually, upon chat creation.

### Describe the solution you'd like

Would be great to have at least very simplified regexp support to make inclusion of chats into Chat Folders dynamic:

just an example of potential regexp - that will dynamically collect all [INT] chats in single folder 
^\[INT\]

or this one will collect all chats including text in the name into Acme Co Chat folder.
\[Acme\]

This will allow decent functionality for dynamic Chat-to-Folder assignment.
Potentially some markers - search in the name or in the description could be used. But for simplicity of implementation would think of using regexp only against chat names. 

### Describe alternatives you've considered

Manual functionality only: 
1. it is error prone, 
2. requires regular checks 
3. can lead to missing important messages if one is relying on this approach

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
