### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by tonkongz** [telegramdesktop/tdesktop#25547]
### Is your feature request related to a problem?

In ability to archive Topics 

### Describe the solution you'd like

Instead of the only option of deleting the topic, it will be nice to have a way to archive. For example, we have a running group w/ topics for a hackathon group (Hack-a-TONx which is part of the TON Foundation effort), but for a new hackathon with new participants, we would like to archive the prior topics and start fresh (but still keep the userbase growing).

### Describe alternatives you've considered

Tried deleting the topics, but we would like to keep it (just hidden via archive).

### Additional context

TON Foundation will be running a global hackathon in January 2023 and the current group (@hackatonx) has 581 members. New hackathon participants who join the group should be able to see a clean-slate with just running topics such as general or announcements (and not have to scroll through prior hackathon topics).

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by RememberTheAir** [comment]
Btw the topic can be closed and nobody will be able to post new messages there - closed topics will be pushed to the bottom of the list as new messages in opened topics arrive
