### ISSUE TITLE
Incorrect Media Upload When Using Drag

### ISSUE THREAD

**Issue by WaffleMixer** [telegramdesktop/tdesktop#25546]
### Steps to reproduce

1. Upload a media X
2. Upload a different media Y

### Expected behaviour

On the 2nd media upload, it should upload the Y media that was selected.

### Actual behaviour

On the 2nd media upload, it uploads the 1st media X again that was uploaded previously instead of the selected media Y.

### Operating system

OS: Arch Linux, DE: gnome

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
cannot reproduce on windows:
https://i.imgur.com/p0xHAgH.jpeg

**Comment by WaffleMixer** [comment]
Below is the video of the issue on my side shown both with dragging images and using ctrl + C and V

[Video Link](https://dl.dropboxusercontent.com/s/fwbx13u2k8ch135/Screencast%20from%202022-12-11%2002-26-34.webm?dl=0)

**Comment by ilya-fedin** [comment]
It's a bug in kcoreaddons framework, I made a PR with a fix long time ago, but sadly they don't merge it :(
https://invent.kde.org/frameworks/kcoreaddons/-/merge_requests/267
Switching to Wayland should help.
