### ISSUE TITLE
Resubscribe from previously added card - Failed

### ISSUE THREAD

**Issue by bsdave** [telegramdesktop/tdesktop#25541]
### Steps to reproduce

1. Subscribe for telegram Premium 1 month from card
2. Waiting for next payment
3. Balance on card should be not enough to make payment
4. After some tries, retries was canceled

5. Put money on card to be enough for next payment
6. Try to resubscribe again

 

### Expected behaviour

Resubscribing successfull 

### Actual behaviour

Failed
https://youtu.be/4-jMux2Xjfg

### Operating system

Ubuntu 20.04 Desktop

### Version of Telegram Desktop

v4.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
It seems your system web engine can't display your bank's 3D-Secure page. Sadly, since there's no way developers can access the page your bank generates for you, there's no way to debug the problem. So it's unlikely to be ever solved and I recommend to switch to another OS or try with other client.
