### ISSUE TITLE
Inline bots suggestion does not persist after update (#2)

### ISSUE THREAD

**Issue by AlexWayfer** [telegramdesktop/tdesktop#25549]
### Steps to reproduce

1. Have a bot with inline functionallity (auto-completion).
2. Update the Telegram Desktop (version still doesn't matter).
3. See disappearance of your bot completing.

The original (locked) issue: https://github.com/telegramdesktop/tdesktop/issues/16075

### Expected behaviour

There is a bot which I used before an update.

![image](https://user-images.githubusercontent.com/6510020/206915168-f558d5b9-f40c-4b8b-9d25-533572b65285.png)

![image](https://user-images.githubusercontent.com/6510020/206915200-39fcf6ee-2e08-4f5a-966c-2135051cdf75.png)

### Actual behaviour

There are not all bots.

![image](https://user-images.githubusercontent.com/6510020/206914983-1c02fad3-f7b5-42fe-a49a-c34c4a3ba7fd.png)

### Operating system

Windows 11, Windows 10, Arch Linux

### Version of Telegram Desktop

2.7.1 – 4.4.1

### Installation source

Static binary from official website

### Logs

```shell
I'd like to see instruction to collect logs.
```

**Comment by john-preston** [comment]
@AlexWayfer I tried to reproduce by updating from 3.5.1 to 4.5 with "@gif", "@pic" and "@wiki" saved to settings - and it worked correctly. If you can produce a standalone steps to reproduce the issue I can try to fix it, something like:

1. unpack version XX.YY (from https://github.com/telegramdesktop/tdesktop/releases page)
2. log in
3. use bot "@....", "@..."
4. update to the latest version (4.5 at the moment)
5. the bots are gone.

**Comment by ilya-fedin** [comment]
@john-preston could it be a dangling old data layout in the data file causing the migration code to remove the suggestions again, again and again? Maybe he should just remove the data directory and set up tdesktop from scratch to get rid of the bug?

**Comment by john-preston** [comment]
@ilya-fedin I'd say using one more bot should be enough because they should be written modern way after that.

**Comment by ilya-fedin** [comment]
@john-preston couldn't it be that the old way still (half-)presents in the data file making the logic bug?

**Comment by AlexWayfer** [comment]
> Maybe he should just remove the data directory and set up tdesktop from scratch to get rid of the bug?

I should? As you can see, I have this error for a long time. I've reinstalled OSes multiple times, with the disk formating, and even I faced it on another PC I believe.

It doesn't occur _every_ update, but some of them. I don't know the pattern for now.



> @AlexWayfer I tried to reproduce by updating from 3.5.1 to 4.5 with "@gif", "@pic" and "@wiki"

I'm not sure about these half-official (as I understand) bots. As you can see, `@gif` bot is always available for me. But `@odesli_bot` — doesn't. Maybe it depends on bot's implementation, kind of out-of-date specs?



> saved to settings

I'm not sure what do you mean, for me it's just auto-completion, I haven't seen such option in settings.



> If you can produce a standalone steps to reproduce the issue

I'll try a bit later, but… again, as it's inconsistent, not every update, I'm not sure what causes it, I don't think it's a simple fact of updating.

**Comment by AlexWayfer** [comment]
Windows 11, TDesktop v4.5.3, I again see this issue.
