### ISSUE TITLE
Can't delete a video until I exit out of TG

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#25559]
### Steps to reproduce

Can't delete a video I uploaded to someone until I exit out of TG. I tried it several times & only when I exited could I delete it from my computer.

### Expected behaviour

After it's done uploading I should be able to delete it from my computer.

### Actual behaviour

Keeps telling me it's open somewhere else.

### Operating system

Win 7

### Version of Telegram Desktop

4.3.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7818

**Comment by john-preston** [comment]
@ILoveSkilledCoders if you close the chat by escape you can't delete it as well?

**Comment by ILoveSkilledCoders** [comment]
> @ILoveSkilledCoders if you close the chat by escape you can't delete it as well?

What do you mean close the chat by using Esc?

You can't close a chat unless you close the entire program, or is there some feature I'm unaware of?

I couldn't even rename a video the other day without closing/exiting TG.

**Comment by Aokromes** [comment]
> > @ILoveSkilledCoders if you close the chat by escape you can't delete it as well?
> 
> What do you mean close the chat by using Esc?
> 
> You can't close a chat unless you close the entire program, or is there some feature I'm unaware of?
> 
> I couldn't even rename a video the other day without closing/exiting TG.

he means use escape key on the chat where you have the video.
