### ISSUE TITLE
[Feature Request] mark any message as "unread from here"

### ISSUE THREAD

**Issue by ohhai** [telegramdesktop/tdesktop#25557]
### Is your feature request related to a problem?

Problem is related to the following case:
- you have a lot of unread messages in some chat
- you want to read all of them later
- you open chat at some position after the marker: maybe in the middle of unread messages (for example, somebody forwarded channel post to you and you clicked it to read comments); maybe at the very end, at the newest message
- it marks part or all of them read
- now you lost your progress even if you remember initial unread marker position

Telegram currently has "mark as unread" feature, but it does not help for this case because it does not mark where unread messages started.

### Describe the solution you'd like

Just one more item in message's context menu: "mark as unread from here"

### Describe alternatives you've considered

I can only imagine a solution which prevents you from unintentional marking messages read. But can not imagine an implementation.

**Comment by 23rd** [comment]
https://suggestions.telegram.org/
