### ISSUE TITLE
Birthday.

### ISSUE THREAD

**Issue by akbarjonjorayev** [telegramdesktop/tdesktop#25553]
### Is your feature request related to a problem?

It would be nice to save the date of birth of the interlocutor.

### Describe the solution you'd like
Think about it. Perhaps many people forget to wish happy birthday or a person can add their birthday in settings > edit profile and decide who to show it to in settings > privacy and security.

### Describe alternatives you've considered

![image](https://user-images.githubusercontent.com/100585930/207092109-1033fa72-a189-41c3-b381-56706ccf1203.png)

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
