### ISSUE TITLE
Share screen feature on desktop shows in mirror version

### ISSUE THREAD

**Issue by thegrtnx** [telegramdesktop/tdesktop#25552]
![image_2022-12-12_122248984](https://user-images.githubusercontent.com/49532326/207033256-617cf294-d60f-4303-8e6d-17e659dc0fa7.png)
### Steps to reproduce

1. Create a group
2. Create a video chat
3. Share screen and you'll experience what I am experiencing.

Below is an attached image;

![Uploading image_2022-12-12_121735439.png…]()

### Expected behaviour

The video was meant to be show the exact way it not in a mirrored way

### Actual behaviour

The share screen is mirrored

### Operating system

Windows 11

### Version of Telegram Desktop

4.4.1 and 4.3.4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
cannot reproduce:
https://i.imgur.com/B1bL0MA.png

**Comment by ilya-fedin** [comment]
#25515?

**Comment by thegrtnx** [comment]
> cannot reproduce: https://i.imgur.com/B1bL0MA.png

What's your Telegram desktop version?

**Comment by thegrtnx** [comment]
> #25515?

Yes,
this exact same issue.
