### ISSUE TITLE
Channel comments won't open unless someone already commented

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#25568]
### Steps to reproduce

1. open a channel with comments enabled
2. find a post with no comments yet
3. click on the comments bar

### Expected behaviour

tdesktop opens the chat view

### Actual behaviour

Nothing happens when clicking

https://user-images.githubusercontent.com/16143208/207884102-e6c69aa4-fbb9-48c8-a0a4-57abf063147b.mp4

### Operating system

Windows 10

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Is it possible that the forwarded post was deleted in the group? Or that there was a problem on the server at that time and those posts weren't created?

Does it happen from the mobile apps if you try them at the same time with the same posts?

**Comment by RememberTheAir** [comment]
> Is it possible that the forwarded post was deleted in the group?

I confirm it's the case. Nevermind :)
