### ISSUE TITLE
MacOS context service to upload file to cloud storage

### ISSUE THREAD

**Issue by lwis** [telegramdesktop/tdesktop#2556]
How feasible would it be to create a MacOS context service to upload file to personal cloud storage from Finder.

**Comment by auchri** [comment]
It's already possible in windows:

![image](https://cloud.githubusercontent.com/assets/5092164/19598456/330dfe32-979b-11e6-956f-f2d2abfad680.png)

**Comment by lwis** [comment]
@auchri cool, updated my comment also. Thanks!

**Comment by stek29** [comment]
#1983 would be better imo.
You'd be able to pick "cloud storage" or any other chat.
