### ISSUE TITLE
Client crashes on Wayland trying to open web-application inside bot message

### ISSUE THREAD

**Issue by abyss7** [telegramdesktop/tdesktop#25564]
### Steps to reproduce

1. Go to some paywalled bot and press the button in menu.
2. Dialog pops up about running web application or something like this - never saw this term before.
3. Permit to launch (on mobile client it opens some kind of child window inside client).
4. Desktop client crashes and continues to crash on start no matter what.

### Expected behaviour

Client should start.

### Actual behaviour

Client crashes.

### Operating system

Fedora 37

### Version of Telegram Desktop

4.4.1

### Installation source

Flatpak

### Logs

```shell
➤ flatpak run org.telegram.desktop                                                                                                                                13:00:52
F: /run/user/1000/.flatpak/org.telegram.desktop/xdg-run/wayland-0 is not a symlink to "../../flatpak/wayland-0" as expected: readlinkat: Invalid argument
Failed to create wl_display (Connection refused)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.
```

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org
if it still crashes plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by ilya-fedin** [comment]
It's https://github.com/flatpak/flatpak/issues/5167
