### ISSUE TITLE
I can’t create a group chat, telegram does not allow me to press ‘create’ button

### ISSUE THREAD

**Issue by Karolnk** [telegramdesktop/tdesktop#25560]
### Steps to reproduce

I can’t create a group chat, telegram does not allow me to press the ‘create’ button(both on my laptop and phone). 

### Expected behaviour

I need to create a chat group 

### Actual behaviour

I can’t create a group chat, telegram does not allow me to press the ‘create’ button(both on my laptop and phone). 

### Operating system

I don't understand the request 

### Version of Telegram Desktop

v4.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> both on my laptop and phone

You have chosen the wrong option when creating the issue, there's an item for issues affecting more than only Telegram Desktop.
