### ISSUE TITLE
Photos get downloaded automatically with setting disabled

### ISSUE THREAD

**Issue by Sennar02** [telegramdesktop/tdesktop#25574]
### Steps to reproduce

1. Disable automatic download for photos in every type of chat
2. Sometimes photos get downloaded automatically anyway

### Expected behaviour

By disabling "Automatic media download" for photos, they shouldn't be downloaded automatically.

### Actual behaviour

Sometimes photos get downloaded automatically even with "Automatic media download" settings for photos disabled in every type of chat.

### Operating system

Windows 10

### Version of Telegram Desktop

4.4.1 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
If you open a photo perhaps the surrounding photos are downloaded too, preloaded in case you switch to them. Is this the case?

**Comment by Sennar02** [comment]
Unfortunately not. I noticed they also get downloaded when someone quote them or just randomly.

**Comment by cwsilva1** [comment]
I realized that when opening an image or video it **closes automatically**, I checked the version and it is **updated**, what is going on?
