### ISSUE TITLE
No application icon in launcher after installation (Phosh)

### ISSUE THREAD

**Issue by MadameMalady** [telegramdesktop/tdesktop#25575]
### Steps to reproduce

Install Telegram from flathub / Gnome Software Center on a Pinephone Pro running Manjaro Phosh Stable.

Install Telegram and the webview addon (or dont, the same issue will occur)

Wait until your desktop notifies you Telegram has finished installing.

Check the Phosh launcher for the telegram icon.

Realize it is not there.

### Expected behaviour

Install Telegram from flathub / Gnome Software Center on a Pinephone Pro running Manjaro Phosh Stable.

Install Telegram and the webview addon (or dont)

Wait until your desktop notifies you Telegram has finished installing.

Check the Phosh launcher for the telegram icon.

See it is there.

### Actual behaviour

Telegram's icon doesn't show up on phosh post-installation.

If you hit launch from the gnome-software-center, it will indeed launch, but the icon is missing.

### Operating system

Manjaro Arm Phosh Stable

### Version of Telegram Desktop

4.4.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
In case of flatpak, it's flatpak's job to create the launcher, not tdesktop's.

**Comment by MadameMalady** [comment]
> In case of flatpak, it's flatpak's job to create the launcher, not tdesktop's.

Yes, I actually know that. (I make some Linux apps myself).
Unless the gnome software center flatpak listing for telegram has the wrong issue tracker linked, I suspect this project changed something in their flatpak packaging recently that broke the .desktop link creation.

**Comment by ilya-fedin** [comment]
Yeah, there were no changes, but I don't see problems on any desktop environments and mobile environments aren't supported as Telegram Desktop is for desktops as it obvious from its name.

**Comment by MadameMalady** [comment]
> Yeah, there were some changes, but I don't see problems on any desktop environments and mobile environments aren't supported as Telegram Desktop is for desktops as it's obvious from its name.

So that is a yes, recent changes broke mobile compatibility. Weather the telegram project cares about said mobile compatibility or not. Got it.

**Comment by ilya-fedin** [comment]
I believe it's a coincidence as flatpak rewrites the desktop file anyway
