### ISSUE TITLE
Web Z: Error When Trying to Send a Picture on Clipboard

### ISSUE THREAD

**Issue by BoringHacker** [telegramdesktop/tdesktop#25573]
### Steps to reproduce

As the title, when I try to paste a picture in my clipboard (after a screenshot), Telegram Web Z wrongly recognized my picture while Web K goes well.

### Expected behaviour

It should goes like Web K:

![image](https://user-images.githubusercontent.com/57580717/208106359-148e2187-eda9-49c8-9671-299b8472154e.png)

### Actual behaviour

But in fact:

![image](https://user-images.githubusercontent.com/57580717/208105940-f0a838a6-9d77-44bd-a78b-5c709773233f.png)

### Operating system

Windows 10 22H2, Mircrsoft Edge (as for browser)

### Version of Telegram Desktop

Web Z

### Installation source

Other (unofficial) source

**Comment by BoringHacker** [comment]
Btw, I don't know whether I shoud put it in there (for it's Telegram **Desktop**), but I didn't find the project of TG web versions on GitHub or anywhere...

**Comment by ilya-fedin** [comment]
The new issue dialog has "Issue of other client" item, you haven't used it?

**Comment by BoringHacker** [comment]
> The new issue dialog has "Issue of other client" item, why haven't you used it?

Sorry for this... I'd like to close this issue.

**Comment by ilya-fedin** [comment]
I'd like to hear the answer anyway, you're the second person ignoring the item. I don't understand why people ignore them and what to do so they don't ignore.

**Comment by BoringHacker** [comment]
> I'd like to hear the answer anyway, you're the second person ignoring the item. I don't understand why people ignore it and what to do so they don't ignore.

I am not familiar with GitHub manners. I just found a possible bug and wanted to report it. I went to GitHub, clicked Issue button, and there were two big green Get Started button. I smashed one of them and ignored the other three items.
