### ISSUE TITLE
TDesktop is only telegram client which does not support 2560px side images. Is downloading them as 2560px, then down scaling them to 1280px before displaying.

### ISSUE THREAD

**Issue by Lesiuk** [telegramdesktop/tdesktop#25582]
### Steps to reproduce

1. Send image with 2560px side to yourself.
2. Open image and save to disk.
3. Compare them.

### Expected behaviour

We are saving to disk 2560px image like we should but before displaying image is converted to 1280px.
MacOSX, iPhone, Android clients are not converting images to 1280px before displaying them. Only tdesktop does that.

Code responsible for this behavior is inside function below. SideLimit is 1280, image is 2560x1900 image, and we are scaling it to 1280px.

```
void PhotoMedia::set(
		PhotoSize size,
		PhotoSize goodFor,
		QImage image,
		QByteArray bytes) {
	const auto index = PhotoSizeIndex(size);
	**const auto limit = PhotoData::SideLimit();
	if (image.width() > limit || image.height() > limit) {
		image = image.scaled(
			limit,
			limit,
			Qt::KeepAspectRatio,
			Qt::SmoothTransformation);
	}**
	_images[index] = PhotoImage{
		.data = std::make_unique<Image>(std::move(image)),
		.bytes = std::move(bytes),
		.goodFor = goodFor,
	};
	_owner->session().notifyDownloaderTaskFinished();
}
```

### Actual behaviour

Display downloaded images in their native resolutions. Do not downscale them right after downloading.

### Operating system

Windows 10

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by Lesiuk** [comment]
TelegramSwift:
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/543264/208315949-82b1d6d9-bb48-407a-8723-057a5f2a19bf.png">

**Comment by Lesiuk** [comment]
tdesktop:
![image](https://user-images.githubusercontent.com/543264/208315982-c9ea90a4-2d13-4d02-aa54-6d6ef97c8daa.png)

**Comment by ilya-fedin** [comment]
#6520, #2206
although I don't believe the download happens in 2560px as the whole reason tdesktop uses 1280px variant is to save the loading time

**Comment by Lesiuk** [comment]
> #6520, #2206 although I don't believe the download happens in 2560px as the whole reason tdesktop uses 1280px variant is to save the loading time

I have my breakpoint inside PhotoMedia::set. TDesktop is downloading full 2560px image and then downscaling.

**Comment by Lesiuk** [comment]
@ilya-fedin 
![image](https://user-images.githubusercontent.com/543264/208316304-fc356a75-68bd-4e76-87c0-1825b3124d47.png)

**Comment by Lesiuk** [comment]
ByteSize is 1.1197 MB. When I am saving this file to disk, It's 2560x1928.

**Comment by Lesiuk** [comment]
![image](https://user-images.githubusercontent.com/543264/208316456-03b8b683-0cbb-4b27-b7da-943403168206.png)
![image](https://user-images.githubusercontent.com/543264/208316459-4f6aaba3-58f1-42f1-9310-7bd330ff48c3.png)

**Comment by Lesiuk** [comment]
Android, iOS, MacOSX clients are not down scaling those images. How this is not a bug?

**Comment by ilya-fedin** [comment]
Who said this is not a bug?

**Comment by Lesiuk** [comment]
Someone closed this issue. I thought that meant we weren't going to do anything about it.

**Comment by ilya-fedin** [comment]
it's a duplicate, see the previous messages and you will see the one with links

**Comment by ilya-fedin** [comment]
Although it's unlikely anything will be done, yeah. It's quite a non-trivial bug existing all the lifetime of tdesktop.

**Comment by Lesiuk** [comment]
Would you accept a PR which removes this down scaling for downloaded images (like in other clients)? I can prepare one.

**Comment by ilya-fedin** [comment]
This wouldn't be the right way to fix. It's done like that before there's no 2560 variant when displaying the photo in media viewer. tdesktop was saving it in 1280 size, too, but apparently something has changed with the introduction of progressive JPEG support. Although the fact tdesktop still uses 1280 in media viewer suggests to me that there are still some cases 2560px version is not available and then it should be handled appropriately (that is, someone should write a fancy loading animation logic and no one has stepped up to this work in 6 years, and I guess it's unlikely someone will to).

**Comment by ilya-fedin** [comment]
@john-preston should know actual state of things

**Comment by Lesiuk** [comment]
I would really want this to be fixed, so just tell me how the fix should look like, and I will see what I can do. I am sending lots of photos to family living away from home. Just recently noticed that images displayed inside TDesktop look much worse as those I can see on my MacBook or Android/iPhone.

There is also something wrong with scaling image to desktop size logic. Even if I remove this down scaling logic, images are still not as crisp as those saved to disk. It looks like scaling image to desktop is also down scaling image and those details are lost even when zooming.
