### ISSUE TITLE
System-wide installation in windows missing

### ISSUE THREAD

**Issue by marcogaio** [telegramdesktop/tdesktop#25589]
### Steps to reproduce

I'm trying to install Telegram Desktop in unattended mode, via WPKG, on my organization.
I've tried to install it system-wide (in MSI lingo, ALLUSERS=1) but seems that the installer and the program itself is strictly tailored to user installation

### Expected behaviour

Installer can put executables and static data on a system folder (eg, %ProgramFiles%), and when run, telegram desktop must write their data on user profile.

### Actual behaviour

If i install with default options, program (and data) are written to user profile.
If i force the installation on %ProgramFiles%, when i run the program also the data are written to %ProgramFile% (supposing the user have sufficient permission).

### Operating system

Win10 64bit

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> (supposing the user have sufficient permission)

But the user shouldn't have it. That's exactly how system-wide installation is detected in tdesktop.

**Comment by ilya-fedin** [comment]
#5718
