### ISSUE TITLE
Linux built application failed to start with "undefined reference symbol: g_file_make_symbolic_link_async"

### ISSUE THREAD

**Issue by EugenySychev** [telegramdesktop/tdesktop#25580]
### Steps to reproduce

Build linux application by instruction
run it by "out/Release/Telegram"

### Expected behaviour

Application started

### Actual behaviour

Application not started, error is "undefined reference symbol: g_file_make_symbolic_link_async"

### Operating system

Linux Ubuntu 22.04

### Version of Telegram Desktop

4.4.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
#25536

**Comment by EugenySychev** [comment]
Thank you!
