### ISSUE TITLE
Drag&Drop problem with admin privileges

### ISSUE THREAD

**Issue by 23cku0r** [telegramdesktop/tdesktop#25588]
### Steps to reproduce

1. Open telegram with admin privileges
2. Select a file
3. Try to move the file to any chat

### Expected behaviour

A window opens with sending the file

### Actual behaviour

The file does not want to move to telegram

### Operating system

Windows 11 Pro x64 Ver. 10.0.22621 Build 22621

### Version of Telegram Desktop

4.4.1 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I believe it's a Windows limitation, you can't do that. You shouldn't run Telegram as administrator though.
