### ISSUE TITLE
Strange input method box location in wayland.

### ISSUE THREAD

**Issue by Ephemereh** [telegramdesktop/tdesktop#25599]
### Steps to reproduce

1. open telegram in gnome wayland.
2. use input method to input, (ibus pinyin in my case)
3. input method box appears on the left of telegram client.

### Expected behaviour

the box should appear under where we types.

### Actual behaviour

input method box appears on the left of telegram client (or other places for different people according to my friends).
![image_2022-12-24_12-13-53](https://user-images.githubusercontent.com/52552971/209421239-31085214-77d9-41f9-923a-8f484466dcb1.png)
![photo_2022-12-24_12-31-13](https://user-images.githubusercontent.com/52552971/209421263-36494543-3294-4fe7-8f5e-8cbe9f0a83d9.jpg)

### Operating system

Fedora 37

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Is this ibus? If yes then Qt sadly doesn't support it good, it's better to switch to fcitx.

**Comment by Ephemereh** [comment]
Yes, is this incompatibility hard to fix?

**Comment by ilya-fedin** [comment]
It's a bug in Telegram dependency called Qt, it could be fixed only by their developers. You can report them a bug via https://bugreports.qt.io.
