### ISSUE TITLE
Smooth Scroll on certain logitech mice does not work as expected.

### ISSUE THREAD

**Issue by SZCthebandit** [telegramdesktop/tdesktop#25591]
### Steps to reproduce

1.Enable 'Smooth Scroll' in Logitech options/options+ on compatible mouse, for the Telegram desktop app.
2.Scroll on any telegram UI, with the telegram window in focus. It should not work, with the page scrolling in increments like using a conventional mouse wheel.
3. Instead, focus window on another smooth-scroll-supported window, for example chrome, and then scroll on any telegram UI. Observe that the page now scrolls smoothly, with pixel-wise increments, like one would expect telegram to do. Also observe that the smooth scrolling effect ceases once you focus cursor on the Telegram window again.

### Expected behaviour

The Telegram Desktop interface should respond to smooth scroll inputs as other apps would (e.g. chrome), moving the page up or down pixel-wise, like how Telegram currently works with fingers scrolling on a trackpad.

### Actual behaviour

The app currently responds to smooth scroll inputs as conventional scroll events, moving the page up or down in pre-set increments, like scrolling in windows File Explorer.

### Operating system

Windows 10 21H1, environment: logitech master 2s & master 3 mouse

### Version of Telegram Desktop

Windows version 4.4.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Well, that's the way Qt handles inputs of this mouse/driver. I'm not sure I can do anything about that.

**Comment by LinMingkui** [comment]
logitech M546 too
