### ISSUE TITLE
[Feature Request] Accessibility in Telegram Desktop

### ISSUE THREAD

**Issue by fclorenzo** [telegramdesktop/tdesktop#25592]
### Is your feature request related to a problem?

Telegram desktop is not accessible.

### Describe the solution you'd like

Hello. I know I'm not the first to ask this. The official Telegram mobile clients are all accessible, but the desktop client is not. I know there are alternative clients, but none are as complete as the official client. For example, exporting chats is something that only the official Telegram client can do. If the official mobile clients are all accessible, why can't the desktop client be?

### Describe alternatives you've considered

Well, unfortunately, there's not much alternatives when a program is not accessible. There are alternative clients, but none of then is the official Telegram desktop client.

**Comment by ilya-fedin** [comment]
#476
