### ISSUE TITLE
Can't download a video file from a chat, no error message, no progress indicator, simply pathetic

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#25598]
### Steps to reproduce

1. On my phone, I sent myself a video that I had recorded, to "Saved Messages".
2. On my computer, with Telegram Desktop (installed on Manjaro Linux from the community packages), I right-clicked on the video and selected "Download" or "Save As" or whatever it's called, and downloaded it to the desktop.
3. After several minutes I just assumed that it had finished downloading. Tried to play it, but (see expected/observed behavior)

### Expected behaviour

1. Should download the file
2. While it's downloading, I should be able to see the progress, and an estimation of the time remaining. That is if it takes long for whatever reason
3. if it fails to download, or it times out, it should show an error message

### Actual behaviour

1. The file didn't download. After several minutes, it had downloaded only about 120k of 18M. The file is visible in the desktop (the destination folder that I had chosen) with the mp4 extension (that is, with the final filename, not a temporary filename for an incomplete download, like for example Chrome does)
2. there was no error message
3. I right-clicked again on the file in Telegram to try downloading again, but the option available is "Cancel download", as if it's still trying (yeah right, and after several minutes it's stuck at 120k)

I cancelled the download and tried again, and the same happened, only this time instead of just 120k it downloaded 16MB (i.e. almost the entire file but not quite).

Overall the whole thing is a complete disaster.

Now I wonder: maybe the file was still being transferred between my phone and the desktop app?
But if so:
1. that doesn't make sense, as the video was already playing in loop on the desktop app.
2. even if that was the case (in which case what am I looking at? Some sort of preview that was generated in less time that it took to transfer the file from one device to the other? Whatever) then it should have warned me when trying to save the file, and shouldn't have let me.
3. if anything goes wrong at any point in the process, show a ***damn error message.

### Operating system

Manjaro Linux

### Version of Telegram Desktop

4.3.1

### Installation source

Other (unofficial) source

**Comment by john-preston** [comment]
There should've been improvements in downloading for streamable media files. Please try 4.5 version from desktop.telegram.org and tell if it's better.
