### ISSUE TITLE
[Feature Request] Send voice messages with a right or left click option

### ISSUE THREAD

**Issue by sakibarifin** [telegramdesktop/tdesktop#25602]
### Is your feature request related to a problem?

Holding down the button for longer voice messages is tiresome.

### Describe the solution you'd like

It would be extremely helpful if there was a option to send voice messages with a click of the mouse to start and another click to end. Some other apps have similar features. While the default of tap and hold is ok for most users but some may not like the tiresome issue of holding it down for longer messages. The extra option to do it like I proposed would be helpful to many users.

### Describe alternatives you've considered

There are no alternatives for this problem.

**Comment by john-preston** [comment]
You can press and drag the mouse up to lock the recording. Does it resolve your problem?

**Comment by sakibarifin** [comment]
Thanks, it does solve my problem.
