### ISSUE TITLE
Telegram silently fails adding itself to the auto-run on corrupted Windows instance

### ISSUE THREAD

**Issue by DmitriyYukhanov** [telegramdesktop/tdesktop#25608]
### Steps to reproduce

1. Uncheck the "Launch Telegram when system starts" option in Telegram.
2. Remove `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` folder.
3. Go to Telegram and enable "Launch Telegram when system starts" back.
4. See no error appear while Telegram can't add itself to the auto-start.

This causes confusion to the end user - it looks like Telegram is added to the auto-run, but it's not.

### Expected behaviour

Telegram reports it can't add itself to the auto-run or let the user know the operation wasn't successful in some other user-friendly way.

### Actual behaviour

It silently enables "Launch Telegram when system starts" option like it was added to auto-run which isn't a case.

### Operating system

Windows 11 22H2

### Version of Telegram Desktop

4.4.1 portable

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Thanks for the report and for the suggestion. There indeed is an API for creating that folder 🤔
