### ISSUE TITLE
No sound playing video from Telegram

### ISSUE THREAD

**Issue by gbcox** [telegramdesktop/tdesktop#25605]
### Steps to reproduce

1.  Click on Video
2.  Video plays, but no sound

### Expected behaviour

Should be able to hear sound

### Actual behaviour

No sound at all. :-(

I verified video was fine by playing it using the android telegram app.  Works fine there.  

### Operating system

Fedora 37 using KDE Plasma

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

### Logs

```shell
When playing, here is what is displayed in the log file:
[2022.12.24 14:46:25] Audio Info: recreating audio device and reattaching the tracks
[2022.12.24 14:46:39] Audio Info: Closing audio playback device.
```

**Comment by ilya-fedin** [comment]
Run tdesktop with `ALSOFT_LOGLEVEL=3` environment variable, you should see openal output in terminal. Paste it here using code tag.

**Comment by gbcox** [comment]
Thanks for the quick reply.  Not sure what you mean by "code tag", but here is the paste.  If you need something else, or if this isn't what you needed LMK.  Thanks again.

exec env ALSOFT_LOGLEVEL=3 ./Telegram 
[ALSOFT] (II) Initializing library v1.22.2-dc83d99 HEAD
[ALSOFT] (II) Supported backends: pipewire, pulse, alsa, oss, null, wave
[ALSOFT] (II) Loading config /etc/openal/alsoft.conf...
[ALSOFT] (II) Loading config /usr/share/kde-settings/kde-profile/default/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /home/gbcox/.config/kdedefaults/alsoft.conf...
[ALSOFT] (II) Loading config /home/gbcox/.alsoftrc...
[ALSOFT] (II) Loading config /home/gbcox/.config/alsoft.conf...
[ALSOFT] (II) Got binary: "/home/gbcox/Telegram", "Telegram"
[ALSOFT] (II) Loading config /home/gbcox/Telegram/alsoft.conf...
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Vendor ID: "AuthenticAMD"
[ALSOFT] (II) Name: "AMD FX(tm)-8350 Eight-Core Processor"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key rt-time-limit not found
[ALSOFT] (II) Key game_compat/reverse-x not found
[ALSOFT] (II) Key game_compat/reverse-y not found
[ALSOFT] (II) Key game_compat/reverse-z not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (II) Key drivers not found
[ALSOFT] (II) Found PipeWire version "0.3.63" (0.3.25 or newer)
[ALSOFT] (II) Key pipewire/assume-audio not found
[ALSOFT] (II) Ignoring metadata "settings"
[ALSOFT] (II) Ignoring metadata "route-settings"
[ALSOFT] (II) Ignoring node class Midi/Bridge
[ALSOFT] (II) Ignoring node class Video/Source
[ALSOFT] (II) Initialized backend "pipewire"
[ALSOFT] (II) Added "pipewire" for playback
[ALSOFT] (II) Added "pipewire" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (II) Got default playback device "alsa_output.pci-0000_09_04.0.analog-surround-71"
[ALSOFT] (II) Got default capture device "alsa_input.pci-0000_09_04.0.analog-stereo"
[ALSOFT] (II) Got sink device "alsa_output.pci-0000_09_04.0.analog-surround-71"
[ALSOFT] (II)   "CMI8788 [Oxygen HD Audio] (Virtuoso 100 (Xonar DX)) Analog Surround 7.1" = ID 46
[ALSOFT] (II) Device ID 46 sample rate: 48000 (range: 32000 -> 192000)
[ALSOFT] (II) Device ID 46 got 8 positions for 7.1 Surround
[ALSOFT] (II) Got source device "alsa_input.pci-0000_09_04.0.analog-stereo"
[ALSOFT] (II)   "CMI8788 [Oxygen HD Audio] (Virtuoso 100 (Xonar DX)) Analog Stereo" = ID 47
[ALSOFT] (II) Device ID 47 sample rate: 48000 (range: 32000 -> 192000)
[ALSOFT] (II) Device ID 47 got 2 positions for Stereo
[ALSOFT] (II) Got source device "alsa_input.usb-046d_0990_8C125EDA-02.pro-input-0"
[ALSOFT] (II)   "QuickCam Pro 9000 Pro" = ID 48
[ALSOFT] (II) Device ID 48 sample rate: 16000
[ALSOFT] (II) Device ID 48 got 1 position for Mono
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
[ALSOFT] (II) Key frequency not found
[ALSOFT] (II) Key sources not found
[ALSOFT] (II) Key slots not found
[ALSOFT] (II) Key sends not found
[ALSOFT] (II) Created device 0x7fbfca9aef00, "CMI8788 [Oxygen HD Audio] (Virtuoso 100 (Xonar DX)) Analog Surround 7.1"
[ALSOFT] (II) Key sample-type not found
[ALSOFT] (II) Key channels not found
[ALSOFT] (II) Key ambi-format not found
[ALSOFT] (II) Key period_size not found
[ALSOFT] (II) Key periods not found
[ALSOFT] (II) Key hrtf not found
[ALSOFT] (II) Pre-reset: Stereo, Float32, 44100hz, 882 / 2646 buffer
[ALSOFT] (II) Post-reset: 7.1 Surround, Float32, 48000hz, 960 / 1920 buffer
[ALSOFT] (II) Key stereo-mode not found
[ALSOFT] (II) Key stereo-encoding not found
[ALSOFT] (II) Key decoder/surround71 not found
[ALSOFT] (II) Key front-stablizer not found
[ALSOFT] (II) Key decoder/hq-mode not found
[ALSOFT] (II) Channel config, Main: 7, Real: 8
[ALSOFT] (II) Allocating 15 channels, 61440 bytes
[ALSOFT] (II) Enabling dual-band third-order ambisonic decoder
[ALSOFT] (II) Max sources: 256 (255 + 1), effect slots: 64, sends: 2
[ALSOFT] (II) Key dither not found
[ALSOFT] (II) Key dither-depth not found
[ALSOFT] (II) Dithering disabled
[ALSOFT] (II) Key output-limiter not found
[ALSOFT] (II) Output limiter disabled
[ALSOFT] (II) Fixed device latency: 0ns
[ALSOFT] (II) Post-start: 7.1 Surround, Float32, 48000hz, 960 / 1920 buffer
[ALSOFT] (II) Increasing allocated voices to 256
[ALSOFT] (II) Key volume-adjust not found
[ALSOFT] (II) Created context 0x7fbfcd5cef00
[ALSOFT] (II) Increasing allocated voice properties to 32
[ALSOFT] (II) Freeing context 0x7fbfcd5cef00
[ALSOFT] (II) Freed 2 context property objects
[ALSOFT] (II) Freed 0 AuxiliaryEffectSlot property objects
[ALSOFT] (II) Freeing device 0x7fbfca9aef00

**Comment by ilya-fedin** [comment]
`CMI8788 [Oxygen HD Audio] (Virtuoso 100 (Xonar DX)) Analog Surround 7.1` is the device you want to use, yeah? If yes then I see no errors here, it should work. Maybe your device or Telegram stream is muted in system settings?

**Comment by gbcox** [comment]
Yeah, I had thought of that, but it doesn't appear to be muted.  Here is a screenshot of the application volume controls and it shows that it is playing fine, but no sound.  If I try from another app, such as Elisa, it shows as playing and I also hear sound. I'll keep looking to see if I can find anything.  Thanks again for the quick response.  Happy Holidays!
![telegram_volume](https://user-images.githubusercontent.com/4543019/209453224-3e785eda-f16b-4235-8cb2-f9f1c23f0d1c.png)

**Comment by ilya-fedin** [comment]
Try to report this at https://github.com/kcat/openal-soft, maybe audio library developer will see something in the log

**Comment by gbcox** [comment]
ok, Thanks I do that.  Am I missing something within the Telegram app?  Is there a setting somewhere to mute that I'm somehow missing?

**Comment by ilya-fedin** [comment]
Yeah, there's a volume slider with other controls when watching the video

**Comment by gbcox** [comment]
yeah, that's up to 100%... oh well, I'll keep looking.  Thanks again!

**Comment by xvitaly** [comment]
@gbcox Can you try a packaged version from the RPM Fusion repository?

**Comment by gbcox** [comment]
@xvitaly Thanks for the reply.  I'm getting the following message from the rpmfusion build:
error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by xvitaly** [comment]
>  error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

Some of installed packages have broken `Provides` section. Can you post output of the following command:
```
dnf -C repoquery --whatprovides="libssl.so.1.1*"
```

**Comment by gbcox** [comment]
Thanks for the quick reply...

Here is the output from the dnf command:
openssl1.1-1:1.1.1q-2.fc37.i686
openssl1.1-1:1.1.1q-2.fc37.x86_64

**Comment by gbcox** [comment]
> > and hopefully will be fixed by this:
> 
> Fedora uses PipeWire by default and we [recently enabled](https://src.fedoraproject.org/rpms/openal-soft/c/a02978de62009f2560cf924971118dd197ba3a49?branch=rawhide) its native support in openal-soft.

I just checked pipewire b720da77 and it's been included as far as I can tell in the latest upgrade for pipewire (0.3.63) - so that didn't fix it.

**Comment by xvitaly** [comment]
> Here is the output from the dnf command:

```
sudo dnf install openssl1.1
```

Then run `telegram-desktop`.

**Comment by ilya-fedin** [comment]
Official tdesktop builds support openal's pipewire backend since it was released. I don't think Fedora package would have any difference, there's likely a bug in openal, there were similar complaints previously, but the users decided they don't want to report to openal, so the bug is still here.

**Comment by gbcox** [comment]
Yeah, the rpmfusion 

> > Here is the output from the dnf command:
> 
> ```
> sudo dnf install openssl1.1
> ```
> 
> Then run `telegram-desktop`.

Thanks, that got telegram-desktop working, but the bug is still there unfortunately.

**Comment by gbcox** [comment]
> Official tdesktop builds support openal's pipewire backend since it was released. I don't think Fedora package would have any difference, there's likely a bug in openal, there were similar complaints previously, but the users decided they don't want to report to openal, so the bug is still here.
Yeah, I from my searching I was thinking it was with pipewire itself.  I'll report to openal and see what they say.  You're correct, many people are having an issue with this.

**Comment by gbcox** [comment]
openal-soft doesn't believe this is an issue with their software.  When you get the opportunity please review: https://github.com/kcat/openal-soft/issues/802

**Comment by ilya-fedin** [comment]
Yeah, I see, apparently it's the time to create a bug on [pipewire repo](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues)
