### ISSUE TITLE
Crash telegram after click on search icon in a group topics

### ISSUE THREAD

**Issue by mosamadi** [telegramdesktop/tdesktop#25609]
### Steps to reproduce

1- go to a topic of a group
2- enter search icon from top icon 

### Expected behaviour

Since user can search a specific phrase on a group topic, after these step ( mentioned above), telegram search input box should be visible. 

### Actual behaviour

Telegram crash and restart after clicking on the search icon in a group topic.

### Operating system

Windows 10

### Version of Telegram Desktop

Version 4.4.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by mosamadi** [comment]
Your Report Tag: 92031386-cca6-4de4-b6d4-45cfaf6478af
Your User Tag: 4c7a7033b42ec75a

ApiId: 2040
Binary: Telegram.exe
Launched: 25.12.2022 22:10:22
OpenGL ANGLE: Auto
OpenGL Renderer: [not-initialized]
Platform: Windows32Bit
UserTag: 4c7a7033b42ec75a
Version: 4004001
Memory-usage: 288 MB (peak), 256 MB (current)
Pagefile-usage: 267 MB (peak), 234 MB (current)

Caught signal 11 (SIGSEGV) in thread 13768

Backtrace omitted.

Google Breakpad caught a crash, minidump written in thread 3664
Minidump: 92031386-cca6-4de4-b6d4-45cfaf6478af

Backtrace omitted.

**Comment by john-preston** [comment]
Does it still happen in 4.5? If so, can you please send a new dump and post a new crash report tag?

**Comment by cejledka** [comment]
Same issue here, crashing on entering search, v.4.5.2

ApiId: 2040
Binary: Telegram.exe
Launched: 03.01.2023 22:36:10
OpenGL ANGLE: Auto
OpenGL Renderer: [not-initialized]
Platform: Windows32Bit
UserTag: eb1f2a59dde09164
Username: stanislav_anisimov
Version: 4005002
Memory-usage: 335 MB (peak), 278 MB (current)
Pagefile-usage: 363 MB (peak), 283 MB (current)

Caught signal 11 (SIGSEGV) in thread 36260

Backtrace omitted.

Google Breakpad caught a crash, minidump written in thread 8668
Minidump: 89bf6d9a-9b0a-4c7e-9819-9fca8db398c3

Backtrace omitted.
