### ISSUE TITLE
Windows 11 "Launch Telegram when system starts" option fails to create Startup folder

### ISSUE THREAD

**Issue by DmitriyYukhanov** [telegramdesktop/tdesktop#25607]
### Steps to reproduce

1. Uncheck the "Launch Telegram when system starts" option in Telegram.
2. Remove `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` folder.
3. Go to Telegram and enable "Launch Telegram when system starts" back.

### Expected behaviour

It should create the `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` folder and put link to the Telegram in there.

### Actual behaviour

It silently fails, leaving the following record at the DebugLog:
`[15:18:27.073 00-0018728] App Error: could not get CSIDL 7 folder -2147024894`

Most frustrating part it does keep the "Launch Telegram when system starts" tick enabled making user feel it worked fine while it couldn't add itself to the autorun.

### Operating system

Windows 11 22H2

### Version of Telegram Desktop

4.4.1 portable

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
But this folder is system one and should always present

**Comment by ilya-fedin** [comment]
Moreover, it's localized and according to the error, SHGetFolderPath fails, so tdesktop can't retrieve path to the folder and create even if it wanted

**Comment by DmitriyYukhanov** [comment]
Yes, but sometimes Windows installation can corrupt due to HW reasons or due to user error..

I had a case where this folder didn't exist thus making this bug to confuse the end user: Launch Telegram when system starts tick was set just fin but auto-start didn't work.

Once that folder was created (manually), it started to work.

If it's not possible to work this around or create a folder from the Telegram, then I'd hope to see some feedback from the app to let the user know the operation wasn't successful.

**Comment by DmitriyYukhanov** [comment]
Since this one is closed now, I've opened a new ticket about absent feedback from the app causing unexpected behavior:
https://github.com/telegramdesktop/tdesktop/issues/25608
