### ISSUE TITLE
Telegram icon is incorrect under KDE Plasma Wayland session

### ISSUE THREAD

**Issue by Mart-Bogdan** [telegramdesktop/tdesktop#25606]
### Steps to reproduce

1. start KDE Plasma Wayland sesison on some linux system
2. install and open Telegram Desktop

### Expected behaviour

Telegram icon should be shown on taskbar.

### Actual behaviour

Wayland icon is shown.

### Operating system

**Operating System:** Manjaro Linux
**KDE Plasma Version:** 5.26.4
**Qt Version:** 5.15.7
**KDE Frameworks Version:** 5.15.84-1-MANJARO

### Version of Telegram Desktop

4.4.1

### Installation source

Other (unofficial) source (AUR telegram-desktop-bin )

### Logs

```
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
  OpenType support missing for "DAOpenSansRegular", script 15
  OpenType support missing for "davazirregular", script 15
```

### Misc

It's reopen of issue #5180

Which seems to be fixed by PR #5950  but it still shows up.

This actually works properly in LXQt  desktop environemnt with wayland.

I also tryed renaming `telegramdesktop.desktop` to  `telegram-desktop.desktop`, but it didn't help.

**Comment by ilya-fedin** [comment]
There's likely a error in the package you're using. I can't reproduce with the official binary.

**Comment by Mart-Bogdan** [comment]
I've just downloaded binary from here https://github.com/telegramdesktop/tdesktop/releases/tag/v4.4.1 and still observe same behavior :-(

Are using Wayland session as well?

![image](https://user-images.githubusercontent.com/775038/209454179-8e37f8bd-3b43-4318-bf14-c069c7df7048.png)

**Comment by ilya-fedin** [comment]
Have you cleared Telegram data before launching the binary? It won't launch installation code if there was pre-existing data

**Comment by Mart-Bogdan** [comment]
I've just tested Flatpac version and it works properly. Thanks. I guess should file a bug to Arch package maintainer.
