### ISSUE TITLE
Not selecting the correct audio device 

### ISSUE THREAD

**Issue by dllz** [telegramdesktop/tdesktop#2561]
### Steps to reproduce
1. Plug in an external sound card with the internal one active. EG: Use a Xonar U3 with a Laptop
2. Try play a voice note

### Expected behaviour
The voice note should play through the external sound card as this one is currently being used

### Actual behaviour
Plays through the internal laptop sound processor

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
0.10.16
### Logs
I doubt this needs logs as this is a audio device selection issue however they can be provided on request.

**Comment by auchri** [comment]
Duplicate

**Comment by stek29** [comment]
#418 btw

**Comment by dllz** [comment]
I did not realise this had been an issue for so long. I am surprised that it has not been fixed yet.
