### ISSUE TITLE
No RTL option after making it LTR

### ISSUE THREAD

**Issue by somedeveloper00** [telegramdesktop/tdesktop#25616]
### Steps to reproduce

1. Open Telegram Desktop app in windows (I didn't test in other desktops)
2. Open any chat
3. do Ctrl+LShift (hold Ctrl and press LeftShift, then you can release the Ctrl ). by now, texts should appear left to right
4. Then do Ctrl+RShift (same as above, only the right shift button this time). the bug happens here

### Expected behaviour

texts should appear right to left, according to global shortcuts in any desktop platform 

### Actual behaviour

texts do not change their alignment. Could say that the shortcut isn't triggering anything, but I can't be certain about that. could be a bug, could be a missing shortcut. 

### Operating system

Windows (any version)

### Version of Telegram Desktop

4.4.1 (but the bug's been there for as long as I remember)

### Installation source

Microsoft Store

**Comment by somedeveloper00** [comment]
NOTE: installation source was actually winget, I think. But it wasn't in the dropdown menu, so I chose Microsoft Store instead!

**Comment by john-preston** [comment]
Thanks.

Qt should handle this, I'm not sure how to fix that on my side :(

**Comment by somedeveloper00** [comment]
Ah so I'll open an issue about it over at Qt repo 👍👍
