### ISSUE TITLE
Unable to download PDF files in the flatpak version.

### ISSUE THREAD

**Issue by kanansnote** [telegramdesktop/tdesktop#25626]
### Steps to reproduce

Fixing bug in the application.

### Expected behaviour

Snap: No issues 
Deb: Not checked 
Flatpak: Bug exists

### Actual behaviour

By pressing the download button, it displays "Failed" in any pdf files.

![Screenshot from 2022-12-28 23-35-30](https://user-images.githubusercontent.com/99095303/209863906-1f6f2743-a832-4bd9-89ba-cd75daf1ad54.png)

### Operating system

Ubuntu 22.04.1 LTS, 64-bit, x11

### Version of Telegram Desktop

stable

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
xdg-desktop-portal-gnome is known as not capable of providing read-write access to directories. You need to remove it and use set download folder with either xdg-desktop-portal-gtk or xdg-desktop-portal-kde.
https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/41
