### ISSUE TITLE
AVIF animation labeled as GIF

### ISSUE THREAD

**Issue by novomesk** [telegramdesktop/tdesktop#25624]
### Steps to reproduce

Hello,
when I send _animation.avif_
[avif-animation.zip](https://github.com/telegramdesktop/tdesktop/files/10314138/avif-animation.zip)
the animation plays correctly, but there is small label **GIF** in the top-left corner when I move mouse inside the animation.
![telegram-animation](https://user-images.githubusercontent.com/52529860/209810100-6c24fe50-4aee-4f70-94c1-614df365d2cc.png)

Here is other animation in JPEG XL format:
https://github.com/libjxl/conformance/blob/master/testcases/animation_newtons_cradle/input.jxl

### Expected behaviour

I don't know whether the AVIF was indeed converted into GIF format or the GIF label is merely indication of animated picture.

I would rather see there AVIF (instead of GIF) or generic ANIM (or ANIMATION - however I understand that the string is significantly longer than GIF).

### Actual behaviour

GIF label is attached which is slightly surprising because original source was not GIF format.

### Operating system

Win10

### Version of Telegram Desktop

commit b334a1f4fda6cd126d00ef20db4a5e98e20d60bf (Wed Dec 28 14:07:38 2022 +0400)

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Well, audio-less mp4 files are also labeled as GIF. Having GIF label on non-GIF files is by design.

**Comment by novomesk** [comment]
OK, it is by design, I can live with that.
