### ISSUE TITLE
The number of reaction columns is different

### ISSUE THREAD

**Issue by Perlence** [telegramdesktop/tdesktop#25621]
### Steps to reproduce

The number of the reaction columns in a personal chat or in a channel is 7, whereas in a group it's 8.

### Expected behaviour

The reaction menus should be of the same width with 8 columns as in the Android app.

### Actual behaviour

<img width="269" alt="image" src="https://user-images.githubusercontent.com/1044300/209661051-a06cff96-8ba0-4796-bd60-8fe5c353be15.png">

<img width="304" alt="image" src="https://user-images.githubusercontent.com/1044300/209661102-639711f0-de1f-42e6-abe4-1ff1add4ce1b.png">

### Operating system

macOS Ventura 13.1

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Right now the menu adjusts itself to the popup menu width which can be different, so this is intended.

A wide menu with small texts looks bad and the reactions strip much wider than the menu looks bad too.
