### ISSUE TITLE
Sheduled message - lack of unread circle

### ISSUE THREAD

**Issue by Iowerth** [telegramdesktop/tdesktop#25635]
### Steps to reproduce

1. Sending scheduled message in any group by myself.
2. Wait till it appear in group.

### Expected behaviour

Scheduled message appears in group with green circle like on phone:
![2](https://user-images.githubusercontent.com/10152411/210063422-66363225-c69c-467c-a157-1f19db31b402.jpg)

### Actual behaviour

Scheduled message appears in group <ins>without</ins> any circle:
![1](https://user-images.githubusercontent.com/10152411/210063493-4b63ee2f-9a8d-4d6b-bfea-c3c5fe1f66c3.jpg)
Because of this it is hard to understand which of dozens of groups got scheduled message.

**Conclusion: behaviour is different between PC and Android.**

### Operating system

Win 7, Win 10

### Version of Telegram Desktop

From 4.3.3 till 4.4.3 beta

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
This issue https://github.com/telegramdesktop/tdesktop/issues/17079 can be related I think
