### ISSUE TITLE
Archived chat can't be add to a folder excluded chats list

### ISSUE THREAD

**Issue by c0re100** [telegramdesktop/tdesktop#25633]
### Steps to reproduce

1. Create a new folder
2. Add all chat types to this folder
![image](https://user-images.githubusercontent.com/5726473/209992817-6034fb0c-454b-45bf-880d-730ce6eccbd4.png)
3. Add Archived to Excluded Chats
4. Save
5. `Please choose at least one chat for this folder.` alert pop up.
![image](https://user-images.githubusercontent.com/5726473/209992954-a6a50653-f1cb-4dde-a030-3becd51f8114.png)

### Expected behaviour

Can't add Archived chat to excluded list.

### Actual behaviour

It should be added to excluded chats list.

### Operating system

Windows 10

### Version of Telegram Desktop

4.4.3 Beta

### Installation source

Other (unofficial) source

**Comment by john-preston** [comment]
Yes, the chats list for such folder is exactly the same as the "All chats" default list, you can collapse Archive row to a thin button or hide it to the main menu from the right click, so there is no reason to allow such a folder, that is just a duplicate for the main chats list.
