### ISSUE TITLE
move buttons in the context of a dialog

### ISSUE THREAD

**Issue by lepehovsv** [telegramdesktop/tdesktop#25639]
### Is your feature request related to a problem?

on the windows version, it is necessary to shift the buttons in the context of the dialog so that they are away from the window control buttons. When you try to minimize the application, you constantly miss and click on the call.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/73558578/210112474-7258cb68-7c91-4f44-89da-e8c609c95d57.png)

### Describe alternatives you've considered

-

**Comment by Aokromes** [comment]
duplicate
