### ISSUE TITLE
[Feature Request] Add Caps Lock Status Where to enter the password input

### ISSUE THREAD

**Issue by pyAref** [telegramdesktop/tdesktop#25634]
### Is your feature request related to a problem?

It has nothing to do with any problem, And it does not cause a problem

### Describe the solution you'd like

Actually, This feature helps in not entering the wrong password,
And find out if the caps lock for uppercase or lowercase letters is turned off or not

### Describe alternatives you've considered

I think an option to display the password would be better

**Comment by ilya-fedin** [comment]
#17235
