### ISSUE TITLE
Cursor Choice isn't Respected on Flatpak Packages

### ISSUE THREAD

**Issue by windowz414** [telegramdesktop/tdesktop#25632]
### Steps to reproduce

No steps, just check cursor when using in app.

### Expected behaviour

The cursor is the one set on the DE.

### Actual behaviour

The cursor is Adwaita Black.

### Operating system

Linux Mint 21.1 Cinnamon

### Version of Telegram Desktop

4.4.1

### Installation source

Flatpak

### Logs

```shell
Gtk-Message: 11:19:29.087: Failed to load module "xapp-gtk3-module"
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
```

**Comment by ilya-fedin** [comment]
It's respected for me. What's the value of `echo $XDG_DATA_DIRS` from the flatpak package shell? Do you see your system cursor directories and /run/host/share/icons and your user cursor directories in /run/host/user-share/icons? Note that if you have non-system cursor chosen, make sure it's in ~/.local/share/icons, other paths are not a part of XDG standard and aren't passed through to flatpak containers.

**Comment by windowz414** [comment]
> It's respected for me. What's the value of `echo $XDG_DATA_DIRS` from the flatpak package shell? Do you see your system cursor directories in /run/host/share/icons and your user cursor directories in /run/host/user-share/icons? Note that if you have non-system cursor theme chosen, make sure it's in ~/.local/share/icons, other paths are not a part of XDG standard and aren't passed through to flatpak containers.

```

**Comment by windowz414** [comment]
> It's respected for me. What's the value of `echo $XDG_DATA_DIRS` from the flatpak package shell? Do you see your system cursor directories in /run/host/share/icons and your user cursor directories in /run/host/user-share/icons? Note that if you have non-system cursor theme chosen, make sure it's in ~/.local/share/icons, other paths are not a part of XDG standard and aren't passed through to flatpak containers.

@ilya-fedin

```
[📦 org.telegram.desktop ~]$ echo $XDG_DATA_DIRS
/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share
```

Yes, my system cursor is `Bibata-Modern-Classic` by default and is located in `/run/host/share/icons/Bibata-Modern-Classic` when I looked from the Flatpak shell.

I haven't change the cursor, I'm using system default.

**Comment by ilya-fedin** [comment]
Do you see your cursor theme set in `xrdb -query` (on the host)?

**Comment by windowz414** [comment]
> Do you see your cursor theme set in `xrdb -query` (on the host)?

What exact value should I look? Here's the full output;
```
beru@ai:~$ xrdb -query
*customization:	-color
Xft.dpi:	96
Xft.antialias:	1
Xft.hinting:	1
Xft.hintstyle:	hintslight
Xft.rgba:	rgb
```

> What does `echo $XCURSOR_THEME` output in the conainer?

No output.
```
[📦 org.telegram.desktop ~]$ echo $XCURSOR_THEME

[📦 org.telegram.desktop ~]$ 
```

**Comment by ilya-fedin** [comment]
So the issue is Cinnamon doesn't set cursor theme/size settings for non-gtk applications (to xrdb, empty XCURSOR_THEME is good). The Qt version tdesktop uses has compatibility with gtk protocol for getting desktop settings (could explored with dump_xsettings from xsettingsd package), but apparently the code is broken, it doesn't actually fallback to reading gtk cursor setting as Xcursor return a non-null pointer with fallback cursor theme. But the dev branch of Qt has deleted that code due to rewrite from Xcursor library to xcb-cursor library and xcb-cursor library has no API to set custom cursor theme value (it always reads from xrdb internally), so we can't report this to Qt. The only remaining thing is for you to ask Cinnamon developers to provide cursor settings to non-gtk applications via Xcursor.theme and Xcursor.size properties at xrdb.

> Yes, my system cursor is `Bibata-Modern-Classic` by default and is located in `/run/host/share/icons/Bibata-Modern-Classic` when I looked from the Flatpak shell.
> 
> I haven't changed the cursor, I'm using system default.

That's not true, I have a VM with Linux Mint Cinnamon and haven't touched any settings, the cursor theme is DMZ-White.

**Comment by windowz414** [comment]
> The only remaining thing is for you to ask Cinnamon developers to provide cursor settings to non-gtk applications via Xcursor.theme and Xcursor.size properties at xrdb.

I'll see what can I do, thanks for the explanation.

> That's not true, I have a VM with Linux Mint Cinnamon and haven't touched any settings, the cursor theme is DMZ-White.

What version did you clean install from? Maybe they changed the cursor in the most recent release, I don't know. I downloaded the ISO and clean installed just yesterday.

**Comment by ilya-fedin** [comment]
> What version did you clean install from? Maybe they changed the cursor in the most recent release, I don't know. I downloaded the ISO and clean installed just yesterday.

Maybe, I installed multiple months ago.

**Comment by ilya-fedin** [comment]
Cursor themes are sadly a big hassle on Linux. Wayland has no standard protocol at all for cursor settings, so gtk/GNOME and Qt/KDE read using their own ways only. So tdesktop never respects cursor settings of GNOME Wayland users until they manually set cursor theme/size using the way Qt expects.

**Comment by windowz414** [comment]
> Cursors are sadly a big hassle on Linux. gtk uses its own custom way on X11, Wayland has no standard protocol at all for cursor settings, so gtk/GNOME and Qt/KDE read using their own ways only. So tdesktop never respects cursor settings of GNOME Wayland users until they manually set cursor theme/size using the way Qt expects. And apparently this is also a thing for some X11 users. I believe gtk and Qt also use different names for cursors themselves in various situations, so the same cursor theme may look differently in gtk and Qt applications.

I wish they could just make something unified like in Windows or macOS...

**Comment by ilya-fedin** [comment]
wlroots developer has tried to do so via a Wayland protocol, but apparently the others are not interested in such approach. KDE folks has just ignored this attempt while GNOME folks were actively criticizng the approach and insisting on using D-Bus. The result is there's no unifying anymore, each desktop uses their own tech.

**Comment by ilya-fedin** [comment]
Funny enough, Chrome OS has a Wayland protocol with unified approach (default cursors are server-side) and Chrome OS applications work just fine (ironically being based on Wayland).

**Comment by windowz414** [comment]
> wlroots developer has tried to do so via a Wayland protocol, but apparently the others are not interested in such approach. KDE folks has just ignored this attempt while GNOME folks were actively criticizng the approach and insisting on using D-Bus leading to the protocol being abandoned. The result is there's no unifying anymore, each desktop uses their own tech and applications are incompatible with desktops of foreign ecosystems.

And another funny thing, GNOME on Xorg at least passes its cursor through onto Qt apps. Wayland broke it all too.

**Comment by windowz414** [comment]
> Funny enough, Chrome OS has a Wayland protocol with unified approach (default cursors are server-side) and Chrome OS applications work just fine there (ironically being based on Wayland).

Well, Crostini (Chrome OS' Linux container) still uses XWayland and an underlying X server IIRC.

**Comment by ilya-fedin** [comment]
> And another funny thing, GNOME on Xorg at least passes its cursor through onto Qt apps. Wayland broke it all too.

Yeah, GNOME has fixed this over time, but apparently Cinnamon folks haven't picked up the fix in their settings daemon implementation.

**Comment by windowz414** [comment]
> > And another funny thing, GNOME on Xorg at least passes its cursor through onto Qt apps.
> 
> Yeah, GNOME has fixed this over time, but apparently Cinnamon folks haven't picked up the fix in their settings daemon implementation.

Apparently so, I'll try MATE version on my testing machine if it happens there ITMT.

**Comment by ilya-fedin** [comment]
This should be the daemon setting xrdb/xsettings keys if cinnamon has the architecture as other GNOME-based desktops
https://github.com/linuxmint/cinnamon-settings-daemon/issues

**Comment by windowz414** [comment]
> This should be the daemon setting xrdb/xsettings keys if cinnamon has the same architecture as other GNOME-based desktops https://github.com/linuxmint/cinnamon-settings-daemon/issues

Thanks for the quick link! And yes, Cinnamon is based on GNOME 2 so it has the same architecture as GNOME-based DEs.

**Comment by ilya-fedin** [comment]
It's based on GNOME 3. MATE is base don GNOME 2.

**Comment by windowz414** [comment]
> It's based on GNOME 3. MATE is based on GNOME 2.

Wait right. ^^;
