### ISSUE TITLE
[Feature Request] search box for searching reactions

### ISSUE THREAD

**Issue by xscd** [telegramdesktop/tdesktop#25636]
### Is your feature request related to a problem?

Currently premium users cant react to messages easily with their added animated emoji packs since there is no easy way to do it. They manually have to look for their emoji to react and makes using added emoji packs hard since there are lots of them and we want to use any reaction from any pack. 

### Describe the solution you'd like

Have a search box like android has:

![image](https://user-images.githubusercontent.com/46658470/210072789-7645d873-b0dd-43a1-930f-2d078e2ed28c.png)

![image](https://user-images.githubusercontent.com/46658470/210073055-dde687a4-d507-4f06-9c2a-efca31ad33a9.png)

### Describe alternatives you've considered

There is no alternative other than manually looking through all your emoji packs and manually search for the reaction you want which makes it impossible to use animated emoji packs to react. 

### Additional context

To not confuse this is for reacting to messages not sending animated emojis as messages (where you can easily search with a colon ` :thinking`)

**Comment by mikromik42069** [comment]
I was searching for just this in google XD

**Comment by xscd** [comment]
This feature has been implemented now, thanks.
