### ISSUE TITLE
Large amount of memory in use

### ISSUE THREAD

**Issue by Cheeck** [telegramdesktop/tdesktop#2563]
~850Mb! It uses too much!
![telega](https://cloud.githubusercontent.com/assets/23018535/19629562/830e5e22-9980-11e6-9eb4-593faa932d63.jpg)
Ver.: 0.10.16
OS: Windows 7 x64

**Comment by Aokromes** [comment]
29 MB here

**Comment by stek29** [comment]
#1317 ?

**Comment by auchri** [comment]
@Cheeck what happens if you clean the chache in the settings?

**Comment by paolobarbolini** [comment]
@auchri 48 MB here after clearing the cache on v0.10.19
