### ISSUE TITLE
Missing full source tarball in v4.5.0

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#25637]
### Steps to reproduce

Visit https://github.com/telegramdesktop/tdesktop/releases/tag/v4.5.0

### Expected behaviour

`Source code (tar.gz, full)` should present in Assets.

### Actual behaviour

Nothing.

### Operating system

any

### Version of Telegram Desktop

4.5.0

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v4.5.0 it's there for me

**Comment by 23rd** [comment]
> it's there for me

I guess he is looking for the archive of source with all submodules.

**Comment by xvitaly** [comment]
> it's there for me

No. Check [4.4.3](https://github.com/telegramdesktop/tdesktop/releases/tag/v4.4.3) for example.

**Comment by john-preston** [comment]
Yup, the assets script crashed. Fixed.
