### ISSUE TITLE
Crash while setting profile photo privacy

### ISSUE THREAD

**Issue by emiliana32** [telegramdesktop/tdesktop#25645]
### Steps to reproduce

1. Open Setting->Privacy and Security->Profile photo
2. Change to Nobody
3. Save

### Expected behaviour

Changing the visibility of the profile photo

### Actual behaviour

The application crashes and during the restart does not allow the report to be sent due to a lack of connection, although it is working properly.

### Operating system

Ubuntu mate 22.04 64 bit

### Version of Telegram Desktop

4.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by emiliana32** [comment]
Hi,
the beta is already enabled, but I cannot send crashes because there is a network problem (while it works perfectly). I have already sent many crash reports in the past without any problems.

**Comment by Aokromes** [comment]
you can go crashes directory (tdata\dumps) and compress dump and send to https://t.me/preston

**Comment by emiliana32** [comment]
Done. I tried a fresh install of telegram in a virtual machine with lubuntu 22.04 64 bit and it crashed in the same way.
