### ISSUE TITLE
Telegram freezes when open image in fullscreen

### ISSUE THREAD

**Issue by matevarga** [telegramdesktop/tdesktop#25648]
### Steps to reproduce

1. Install Telegram
2. Open a chat that has an image in it
3. Click on the image
4. Telegram hangs, the image is not opened in full-screen

### Expected behaviour

The image should open in full-screen.

### Actual behaviour

Telegram hangs. 

Issue goes away if OpenGL acceleration is turned off.

### Operating system

Ubuntu 22.10, Gnome

### Version of Telegram Desktop

4.5.0

### Installation source

Snap

### Logs

No logs (I've even tried `strace telegram-desktop` and didn't find anything useful). Not even in journalctl.

This a re-open of https://github.com/telegramdesktop/tdesktop/issues/24924 -- I've submitted it again because the original issue was closed with "Qt works badly with proprietary drivers." -- I've tried it on AMD GPU and Intel GPU too, both are open-source drivers that are part of the mainline kernel. I think this is somehow specific to Telegram. I'm happy to assist with further debugging.

**Comment by ilya-fedin** [comment]
The only solution I can offer is to blacklist your graphics drivers. Do you want this? If yes, do the same what was requested in the linked issue: provide log.txt.

**Comment by matevarga** [comment]
[tgram-logs.txt](https://github.com/telegramdesktop/tdesktop/files/10328606/tgram-logs.txt)

**Comment by ilya-fedin** [comment]
Hmm, I wonder what information to use for blacklisting given that I myself use a machine detected as `AMD Radeon Vega 8 Graphics (raven, LLVM 14.0.6, DRM 3.48, 6.0.10-zen2)` and I have no such bug.

**Comment by ilya-fedin** [comment]
Do you have the bug starting tdesktop with `LIBGL_ALWAYS_SOFTWARE=1` enviroment variable?

**Comment by matevarga** [comment]
`LIBGL_ALWAYS_SOFTWARE=1  telegram-desktop` makes the bug disappear.

**Comment by ilya-fedin** [comment]
Blacklisting individual models should be ok then. Waiting for the log with Intel hardware.

**Comment by ilya-fedin** [comment]
You may want to install latest graphics drivers first though
https://itsfoss.com/install-mesa-ubuntu/

**Comment by matevarga** [comment]
I'm on the latest mesa (as per your link), same issue. 
```
→ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: GFX1036 (gfx1036, LLVM 15.0.6, DRM 3.47, 5.19.0-26-generic) (0x164e)
    Version: 22.3.2
    Accelerated: yes
    Video memory: 4096MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 2384 MB, largest block: 2384 MB
    VBO free aux. memory - total: 29922 MB, largest block: 29922 MB
    Texture free memory - total: 2384 MB, largest block: 2384 MB
    Texture free aux. memory - total: 29922 MB, largest block: 29922 MB
    Renderbuffer free memory - total: 2384 MB, largest block: 2384 MB
    Renderbuffer free aux. memory - total: 29922 MB, largest block: 29922 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 34049 MB
    Currently available dedicated video memory: 2384 MB
OpenGL vendor string: AMD
OpenGL renderer string: GFX1036 (gfx1036, LLVM 15.0.6, DRM 3.47, 5.19.0-26-generic)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.3.2 - kisak-mesa PPA
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.3.2 - kisak-mesa PPA
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.3.2 - kisak-mesa PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

```

**Comment by ilya-fedin** [comment]
Oh, it seems snap packages don't use graphics drivers from the host, but instead have their own copy from Ubuntu LTS. Try the static binary from https://desktop.telegram.org.

**Comment by matevarga** [comment]
Yep, that works. All right, thanks a lot for the help -- so the Snap has an outdated driver, how disappointing.

**Comment by ilya-fedin** [comment]
I commited connecting kisak-ppa to the snap an hour ago, but https://snapcraft.io/telegram-desktop reports the lastest build on edge channel is still from yesterday.

**Comment by matevarga** [comment]
Out of curiousity -- 

> I commited connecting kisak-ppa to the snap an hour ago

Where's the source for the snap?

**Comment by ilya-fedin** [comment]
This repository

**Comment by matevarga** [comment]
Thanks :)
