### ISSUE TITLE
Telegram don't restore focus on last active conversation when open from task icon.

### ISSUE THREAD

**Issue by BooTheHamster** [telegramdesktop/tdesktop#2564]
### Steps to reproduce
1. Open conversation.
2. Close telegram window.
3. Open from tray icon.

### Expected behaviour
Open telegram with last active (focused) conversation.

### Actual behaviour
Open telegram with focused on "Search" edit.

### Configuration
**Operating system:**
Windows 7
**Version of Telegram Desktop:**
v 0.10.16 19.10.16
### Logs
No logs.

**Comment by stek29** [comment]
#2541.
Please use search next time.
