### ISSUE TITLE
TDesktop don't respects Windows Locale time format

### ISSUE THREAD

**Issue by CrazyHackGUT** [telegramdesktop/tdesktop#25640]
### Steps to reproduce

1. Change locale time format to another.
2. Restart TDesktop.
3. Open any chat and check time format.

### Expected behaviour

TDesktop respects Windows Locale time format

### Actual behaviour

TDesktop now don't respects Windows Locale time format

### Operating system

Windows 10

### Version of Telegram Desktop

4.5

### Installation source

Static binary from official website

**Comment by CrazyHackGUT** [comment]
On v4.4.3 it works perfectly. :(

**Comment by ilya-fedin** [comment]
It does for me, can you provide any screenshots?

**Comment by CrazyHackGUT** [comment]
v4.5.1:
![image](https://user-images.githubusercontent.com/12576822/210270589-89052f42-e067-4788-8530-da6ec71cdc91.png)

For example, previous release version (v4.4.1):
![image](https://user-images.githubusercontent.com/12576822/210270834-bb434d63-a774-41c9-b419-ee6e5bccb39b.png)

I enabled display of seconds for short time format, but they are not displayed in TDesktop.

**Comment by ilya-fedin** [comment]
Meh, Qt bugs
