### ISSUE TITLE
Video call from Android to Desktop not showing phone's video

### ISSUE THREAD

**Issue by huntertran** [telegramdesktop/tdesktop#25641]
### Steps to reproduce

Versions:
Android: v9.2.2
Desktop: v4.5

Steps:
Make a video call from Android to Desktop or vice versa. On Android, both videos show correctly. On Desktop, only desktop's video showed.
There is no problem with sound

### Expected behaviour

Video should display

### Actual behaviour

Video from Android version 9.2.2 not showing on desktop version 4.5

### Operating system

Windows 11

### Version of Telegram Desktop

4.5

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I cannot reproduce on the latest versions.

I've tried Android 9.3.2 and it works correctly, I see video on Telegram Desktop 4.5.1. Please try both latest versions.

**Comment by BadBoyKilla** [comment]
Got the same issue as you for about a week now. LMK if you find a sollution.

**Comment by huntertran** [comment]
> Got the same issue as you for about a week now. LMK if you find a sollution.

I reinstall telegram to solve the problem

**Comment by miha-mencin** [comment]
Hello, I have the same issue. It works if we're both using Android Phones. Also the screen-share is not working. I tried reinstaling on desktop, purging 'AppData', nothing worked.

My system:
Edition	        Windows 10 Pro
Version	        21H2
Installed on	‎18/‎10/‎2022
OS build	        19044.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0

Telegram Desktop: v4.5.2
I tried both x32 and x64.
PS. Didn't try the portable ones


Android Version: Telegram for Android v9.3.3 (3026) store bundled arm64-v8a
Same version for other party and myself.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25692

**Comment by john-preston** [comment]
@huntertran @BadBoyKilla @miha-mencin @2000thflamingo It should work with the version 4.5.3, please check.

**Comment by BadBoyKilla** [comment]
@john-preston yeah it came back on it's own after a week. didn't have to do anything. i guess they fixed it
