### ISSUE TITLE
[Feature Request] Cannot delete custom profile picture for contacts

### ISSUE THREAD

**Issue by lateus** [telegramdesktop/tdesktop#25642]
### Is your feature request related to a problem?

Yes, you can toggle between custom and default profile picture for contacts, but while you can add more and more custom profile pictures you cannot delete them, cluttering what otherwise can be a normal and clean contact.

### Describe the solution you'd like

And option to delete a custom profile picture for contacts, like the one available for groups.

### Describe alternatives you've considered

Nope.

**Comment by Neurotoxin001** [comment]
![image](https://user-images.githubusercontent.com/39812401/210129950-b2f3abcb-9e75-4135-b9ab-64d5233858dc.png)

**Comment by lateus** [comment]
Well @Aokromes you are right... now. When I first submitted this issue I was able to upload many custom profile pic on a contact, and all of them showed up in the list without a mean to remove any of them. I have the `.3` update and just checked and only the last one is shown. Even though you may think I'm crazy, I'm happy that this bug doesn't exist anymore. Keep pushing 👌 
Cheers.
