### ISSUE TITLE
Can't block spammers

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#25654]
### Steps to reproduce

So I wrote this twice on the other site and it still hasn't been fixed.

I did sort of figure out some of the issues.

If I don't block the person right away, then after a week or 2-3 weeks, the block button is no longer available at the top.

Under the 3 setting dots I can't block them or report them as spammers either.

Sometimes the spammers don't respond back to my blurb right away or they do & I don't see it until later or they write me weeks or months later.

### Expected behaviour

The block button should either stay at the top permanently like it is when someone first PMs me, or at least I should be able to find it under the 3 dots even if I added them as a contact.

### Actual behaviour

I can't block people after they have messaged me & a week+ has passed. This was on all versions of TG & on Win 8.1 too.

### Operating system

Win 7

### Version of Telegram Desktop

44.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
after a time you can block it from user info.

**Comment by ILoveSkilledCoders** [comment]
> after a time you can block it from user info.

I don't see that option all the time and that doesn't mean I can report them as a spammer.

I just don't understand why you remove that option at all.
