### ISSUE TITLE
Inappropiate Camera Access

### ISSUE THREAD

**Issue by alpeer** [telegramdesktop/tdesktop#25650]
### Steps to reproduce

Telegram Desktop Application(Downloaded from telegram.org) took photo of me without any consent.

App was on background and I wasn't using cam related function (eg. take photo/call etc.)

![resim](https://user-images.githubusercontent.com/17167342/210154325-63973374-de38-4227-ad02-ed8fb600d8ef.png)

### Expected behaviour

Shouldn't access camera inappropiately.

### Actual behaviour

Accessed camera for 1 second when it was in background.

### Operating system

Windows 8

### Version of Telegram Desktop

4.5 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Somebody could video-call you and cancel the call.

**Comment by john-preston** [comment]
When somebody videocalls you a window with your camera preview is created so you see what your contact will see if you answer his call.
