### ISSUE TITLE
Automatic update leads to segmentation fault

### ISSUE THREAD

**Issue by bovender** [telegramdesktop/tdesktop#25665]
### Steps to reproduce

With automatic updates enabled on my KDE neon 5.26 system (based on Ubuntu 22.04), an updated executable gets downloaded all right, but does not have the execution bit set. When `chmod`ing with `+x`, any subsequent attempt to execute the binary results in a segmentation fault.

I have bene observing this behavior for quite a while now, and since it does not go away, I thought I'd report it.

Note that Telegram works very well when I manually install it, it's just the automatic updating that causes this situation.

```
$ sha256sum tsetup.4.5.0.tar.xz
68a755d4e8f6018061f2e3c06449decd7291df436395a59f63124a0f49371991  tsetup.4.5.0.tar.xz
```

### Expected behaviour

Automatic update should download a file that does not cause segmentation faults.

### Actual behaviour

Automatic update downloads a file, but does not set the execution bit, and the downloaded file cannot be executed.

### Operating system

KDE neon 5.26

### Version of Telegram Desktop

tsetup.4.5.0.tar.xz

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> an updated executable gets downloaded all right

Are you sure? Have you checked the md5 with the binary inside tar.xz from the website?

**Comment by bovender** [comment]
I did some further investigations. You are right, the update does _not_ get downloaded properly. The download evidently stops after ~35 MB:

```bash
# Automatically updated file (fragment) in Telegram/
# Manually downloaded v. 4.52 in Telegram.452/Telegram/
$ cmp Telegram/Telegram Telegram.452/Telegram/Telegram
cmp: EOF on Telegram/Telegram after byte 34762752, in line 36297
```

**Comment by ilya-fedin** [comment]
Activate debug logs with debugmode [cheat code](https://github.com/telegramdesktop/tdesktop/wiki/Cheat-Codes), do an update, if it fails in the same way, open the logs directory with viewlogs cheat code, open DebugLogs folder, find the update log (%timestamp%_upd.txt), upload it. Also check `coredumpctl` for Update crash dumps (don't upload them though, they're useless outside of your machine).

**Comment by bovender** [comment]
Thanks for your help. Interestingly, when I re-installed version 4.50, all my settings got lost, and I had to log in to Telegram using my cell phone. By the time I had reached the settings, Telegram had been properly updated to version 4.52.

I thought about doing the same thing again, but without internet connection, but then it occurred to me that since this time the upgrade had been performed without problems, I'd just watch the situations.

Should the problem re-occur, I'll investigate the debug logs.

Thanks for your help so far!

**Comment by bovender** [comment]
Oh well, with the update to 4.53 it happened again... (Thanks for pushing updates out so frequently by the way ;-) )

Once again I found an incomplete `Telegram` binary. However and interstingly, when I copied the 4.52 binary over from a backup directory and started Telegram, it _immediately_ and successfully updated to 4.53. Possibly because the 4.53 binary had already been downloaded to the temporary folder and just needed to be copied without errors?

<details><summary>Here's the debug log from the first, failed update:</summary>

```
Updater started, new argments formatting..
Argument: '/home/daniel/local/Downloads/Telegram/Updater'
Argument: '-autostart'
Argument: '-debug'
Argument: '-workpath'
Argument: '/home/daniel/.local/share/TelegramDesktop/'
Argument: '-exename'
Argument: 'Telegram'
Argument: '-exepath'
Argument: '/home/daniel/local/Downloads/Telegram/'
Need to update!
From autostart!
Updater binary full path is: /home/daniel/local/Downloads/Telegram/Updater
Executable path: /home/daniel/local/Downloads/Telegram/
Updater binary dir is: /home/daniel/local/Downloads/Telegram/
Passed workpath is '/home/daniel/.local/share/TelegramDesktop/'
Update started..
Ready file found! Using new path '/home/daniel/.local/share/TelegramDesktop/tupdates/temp'..
Added file '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/Telegram' to be copied to '/home/daniel/local/Downloads/Telegram/Telegram'
Skipped ready file '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/ready'
Skipping 'tdata' path '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/tdata'
Trying to get stat() for '/home/daniel/local/Downloads/Telegram/Telegram'
Unlinking file '/home/daniel/local/Downloads/Telegram/Telegram'
Copying file '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/Telegram' to '/home/daniel/local/Downloads/Telegram/Telegram'..
```

</details>

<details><summary>And here's the log from several seconds later, when the update succeeded:</summary>

```
Updater started, new argments formatting..
Argument: '/home/daniel/local/Downloads/Telegram/Updater'
Argument: '-debug'
Argument: '-workpath'
Argument: '/home/daniel/.local/share/TelegramDesktop/'
Argument: '-exename'
Argument: 'Telegram'
Argument: '-exepath'
Argument: '/home/daniel/local/Downloads/Telegram/'
Need to update!
Updater binary full path is: /home/daniel/local/Downloads/Telegram/Updater
Executable path: /home/daniel/local/Downloads/Telegram/
Updater binary dir is: /home/daniel/local/Downloads/Telegram/
Passed workpath is '/home/daniel/.local/share/TelegramDesktop/'
Update started..
Ready file found! Using new path '/home/daniel/.local/share/TelegramDesktop/tupdates/temp'..
Added file '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/Telegram' to be copied to '/home/daniel/local/Downloads/Telegram/Telegram'
Skipped ready file '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/ready'
Skipping 'tdata' path '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/tdata'
Trying to get stat() for '/home/daniel/local/Downloads/Telegram/Telegram'
Unlinking file '/home/daniel/local/Downloads/Telegram/Telegram'
Copying file '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/Telegram' to '/home/daniel/local/Downloads/Telegram/Telegram'..
Update succeed! Clearing folder..
Fully clearing old path '/home/daniel/.local/share/TelegramDesktop/tupdates/ready'..
Removing dir '/home/daniel/.local/share/TelegramDesktop/tupdates/ready'
Could not open dir '/home/daniel/.local/share/TelegramDesktop/tupdates/ready'
Fully clearing path '/home/daniel/.local/share/TelegramDesktop/tupdates/temp'..
Removing dir '/home/daniel/.local/share/TelegramDesktop/tupdates/temp'
Trying to get stat() for '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/Telegram'
Unlinking file '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/Telegram'
Trying to get stat() for '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/ready'
Unlinking file '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/ready'
Trying to get stat() for '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/tdata'
Removing dir '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/tdata'
Trying to get stat() for '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/tdata/version'
Unlinking file '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/tdata/version'
Finally removing dir '/home/daniel/.local/share/TelegramDesktop/tupdates/temp/tdata'
Finally removing dir '/home/daniel/.local/share/TelegramDesktop/tupdates/temp'
Executed Telegram, closing log and quitting..
```

</details>

The log from the first (failed) attempt never gets to the line "Update succeed! Clearing folder.."

`coredumpctl` shows no Telegram-related dumps.

**Comment by ilya-fedin** [comment]
That's quite weird, according to the log, it crashes while copying the file as it doesn't have any further logging (no success/error messages), but then you say there are no dumps. I don't have any idea what it could be as it's just common code to copy files.
https://github.com/telegramdesktop/tdesktop/blob/08fa6a981578034a078b20eb6775521288fc129a/Telegram/SourceFiles/_other/updater_linux.cpp#L90-L130
Maybe the kernel or libc bugs :thinking:

**Comment by ilya-fedin** [comment]
@bovender it seems there's no other way to debug this than for you to launch the updater in a debugger as many times as needed to reproduce this. This may require for you to build a debug build of tdesktop to get a sane trace.

**Comment by bovender** [comment]
Let's see whether I can hunt this down. Thanks again for all your help. Please decide whether to keep this issue open.

**Comment by anton-yarchuk** [comment]
Happened to me multiple times. Periodically (after updates I guess) the client crashes with "Segmentation fault" during the launch. 
I have KDE neon 5.26 too

**Comment by KaMyKaSii** [comment]
I have this problem too, it's happened a few times. In the next update I will generate the logs. Note that all of us here are KDE Neon users, I don't think it's a coincidence. `coredumpctl` returns the following but I don't know what the next step is to return some useful information.
```
TIME                         PID  UID  GID SIG     COREFILE EXE                                        SIZE
Sat 2023-07-29 14:42:39 -03 8682 1000 1000 SIGSEGV present  /home/matheus/Downloads/Telegram/Telegram 51.7M
```

**Comment by ilya-fedin** [comment]
This is a regular application crash, it should be a crash of Updater

**Comment by ilya-fedin** [comment]
I wonder whether it may actually be that it's not a crash but the system kills updater for some reason? Wonder how to debug that then...

**Comment by ilya-fedin** [comment]
Or maybe you folks are using some kind of sandbox that kills all spawned processes by Telegram when it exits (and so the Updater)?

**Comment by dzek69** [comment]
I'm not aware of any feature like that. I'm using KDE Neon too, which basically should be Ubuntu with latest KDE packages. No extra features.

Can you at least reproduce it on your side with KDE Neon in a VM? That'd be a step forward.

Maybe a workaround would be to not overwrite the main binary when updating but save to tmp file and then remove original one and rename tmp file. This way even if something kills the updater it would have much less chance to kill it at the right moment.

When starting up, Telegram could notice it did not properly update and update again from the downloaded cache like it does now (I'm talking about situation described above by someone when update fails, and I just restore outdated binary when I start Telegram it's already in newest version)

**Comment by ilya-fedin** [comment]
No, I can't reproduce, it updates successfully. I thought we're talking about a not always reproducible issue? That's how it was described in previous reports #16884, #23898. People were unable to trigger the issue when installing an old version and update in order to reproduce specially.

**Comment by ilya-fedin** [comment]
> Maybe a workaround would be to not overwrite the main binary when updating but save to tmp file and then remove original one and rename tmp file.

Actually it should be able to rename directly for most people. Someone just has to change the code to try to rename before copying...

**Comment by dzek69** [comment]
> I thought we're talking about a not always reproducible issue?

Oh... maybe. It broke for me three times in a row. Either I'm unlucky or it's always happening on my computer.

**Comment by dzek69** [comment]
Right. Sorry for being dumb :D It worked few times in a row. But my last update was actually a success anyway so I wonder if a target version might be part of the problem here, i mean it updates correctly to the current version, but it won't update correctly to some future versions. I will try it and report back if another failing update will happen to me.

**Comment by ilya-fedin** [comment]
Continuing the "killed by the system" theory, it happens only when you start tdesktop in a certain way. E.g. it may happen when autostarted/launched via some launcher/etc but not when you click on the binary in file manager or in the application menu.

**Comment by ilya-fedin** [comment]
Hmm, I said that and remembered Plasma uses systemd for autostart. I bet it can kill all tdesktop's child processes given that it creates a service for autostart applications.

**Comment by ilya-fedin** [comment]
Yeah, I've reproduced with autostart. systemd kills the updater.

**Comment by ilya-fedin** [comment]
It even kills Kate if I open a text file in tdesktop and then close tdesktop. I dunno how to solve that...

**Comment by ilya-fedin** [comment]
Maybe this should be reported to KDE? :thinking:

**Comment by dzek69** [comment]
i'm far from being a linux master, but iirc developer can spawn a new process in some kind of a "detached" mode, so the process is no longer tied to a process that spawned it

so you can kill the parent and children will survive. Telegram probably can start Updater this way

Not sure if KDE team will do anything with that - that is probably a common in Linux world [?], i remember having something similar on Linux Mint with Cinnamon. Not with Telegram, but some other app

**Comment by ilya-fedin** [comment]
> i'm far from being a linux master, but iirc developer can spawn a new process in some kind of a "detached" mode, so the process is no longer tied to a process that spawned it

File associations are started exactly in this way by system library yet systemd manages to understand it's a child anyway. Apparently it's something about cgroups and detaching doesn't create a new cgroup nor moves to some other.

**Comment by ilya-fedin** [comment]
Looks like this was already [reported](https://bugs.kde.org/show_bug.cgi?id=433299) and [fixed](https://github.com/systemd/systemd/pull/18782). Apparently that's why Fedora users stopped reporting this. Apparently you have to update to a newer system or ask Ubuntu to backport the fix.

**Comment by dzek69** [comment]
Yeah, I just tried simple node app spawning detached Kate and on process tree they were siblings, not a parent child, but still killing the parent killed the child.

If that's fixed then I believe I will just wait for an update

Still you can consider implementing some workaround to prevent people ending up with corrupted binaries (this will keep happening for years I believe, until everyone is updated and updating OS is more pain in the back than updating just an app) - adding artificial wait, to make sure the process won't get killed should be easy hack that saves 99% of cases from happening or moving updating logic to startup phase instead of when Telegram exits. Idk. Just throwing ideas.

**Comment by dzek69** [comment]
Thanks for your time

**Comment by ilya-fedin** [comment]
> If that's fixed then I believe I will just wait for an update

You won't get an update before 2024 because that's how stable distros work. If you want to get this before 2024, you have to migrate to another distro (a non-LTS ubuntu would give you updates once in 6 months vs once in 2 years via LTS, rolling release distros like Arch deliver updates immediately) or ask your distro maintainers to backport the change.

**Comment by bovender** [comment]
As I will be stuck on systemd v. 249 for a while, here's my workaround:

```
cp ~/.local/share/TelegramDesktop/tupdates/temp/Telegram ~/path/to/my/Telegram/ && chmod +x ~/path/to/my/Telegram/Telegram
```

When Telegram notifies me (again) that an update is available, I terminate the application by right-clicking on the icon in the notification area of my deskop, open a terminal, type <kbd>CTRL+R Tel</kbd> followed by  <kbd>ENTER</kbd>, then <kbd>ALT+SPACE Tel</kbd>. Takes about 5 seconds :-)

HTH anyone.

**Comment by dzek69** [comment]
@bovender but why? the problem happens only when telegram is run by autostart, you can just close it as you do now, then open Telegram again, click the update button, done.

**Comment by ilya-fedin** [comment]
Or do this
https://wiki.archlinux.org/title/KDE#systemd_startup
