### ISSUE TITLE
Force reply bug problem in chat with bots

### ISSUE THREAD

**Issue by DimaDDM** [telegramdesktop/tdesktop#25664]
### Steps to reproduce

1) Try to send from bot to user with ForceReply(selective=True)
2) On user side close Mac OS Lite Telegram client
3) Open Telegram Lite client

### Expected behaviour

No dialog should appear with ForceReply

https://user-images.githubusercontent.com/4531719/210265727-5ad42f79-488d-49f2-b96a-6ac7eb16b97a.MOV

### Actual behaviour

Force reply dialog is always appearing. When message contains command and when does not. Also message can appear after removing force Reply from bot code

### Operating system

Mac OS

### Version of Telegram Desktop

4.4.1 Telegram Desktop Lite

### Installation source

Mac App Store

**Comment by namjug-kim** [comment]
have same problem `9.3.241552 AppStore`

**Comment by asimaranov** [comment]
The same bug. It's critical for my projects also. Reply reappears after detaching and restarting application
<img width="403" alt="image" src="https://user-images.githubusercontent.com/25568730/212535895-01f485b8-4e74-4a23-8d45-acb0c65c4a8a.png">

**Comment by devnulldevzero** [comment]
Same issue, Telegram Desktop on Windows (Latest, not Beta)
After re-open TDesktop it attach latest replymessage
![image](https://user-images.githubusercontent.com/71868093/212536221-f3654b16-c26d-4f5a-a35e-4d7a52b753c2.png)

**Comment by s1rne** [comment]
exactly the same bug. response box appears on restartTelegram 9.1.1.238861 AppStore, which is very difficult for some projects. ОС Mac OS.
<img width="1305" alt="Снимок экрана 2023-01-15 в 14 53 10" src="https://user-images.githubusercontent.com/105210225/212539218-e043ca62-23d3-4c47-8658-ef06c869f34e.png">
<img width="1309" alt="Снимок экрана 2023-01-15 в 14 48 36" src="https://user-images.githubusercontent.com/105210225/212539228-c29456b9-65ab-479f-a5ef-fd3383760581.png">

**Comment by DimaDDM** [comment]
Bump
