### ISSUE TITLE
Telegram Desktop (Windows) - Restore from tray

### ISSUE THREAD

**Issue by j-fonseca** [telegramdesktop/tdesktop#2566]
On Telegram Desktop (Windows), once you close it to the tray, when you restore the window back, it jumps to the search box, instead of leaving it the way it was when closing (with a certain chat selected, for example).

### Steps to reproduce
1. Open telegram and select any chat (individual or group).
2. Close it to the tray (must activate the proper option on settings)
3. Reopen from tray

### Expected behaviour
Telegram should be on the same point you left

### Actual behaviour
Telegram jumps to the seach box, no matter what

### Configuration
**Operating system: Win 8.1**

**Version of Telegram Desktop: 0.10.19**

**Comment by auchri** [comment]
Duplicate
