### ISSUE TITLE
"mark as read" keyboard shortcut doesn't work for topics

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#25669]
### Steps to reproduce

1. open a chat with topics enabled
2. find an unread topic
3. hover on it with the mouse pointer
4. use the keyboard shortcut to mark a chat as read (<kbd>CTRL</kbd> + <kbd>R</kbd>)

### Expected behaviour

Since the option to mark it as read is present in topics' context menu, I would expect the keyboard shortcut to work there too

### Actual behaviour

Nothing happens

### Operating system

Windows 10

### Version of Telegram Desktop

4.5.1

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment]
The keyboard shortcut also doesn't work for topic chats from the chats list

**Comment by john-preston** [comment]
@RememberTheAir does it work in 4.5.3?

**Comment by RememberTheAir** [comment]
Yes!
