### ISSUE TITLE
Snap package update discards all accounts and settings

### ISSUE THREAD

**Issue by azazar** [telegramdesktop/tdesktop#25678]
### Steps to reproduce

1. Allow snap to update telegram-desktop package automatically

### Expected behaviour

Telegram should start from where it was stopped.

### Actual behaviour

All telegram data is discarded and I have to relogin to all accounts and set to night mode again

### Operating system

Distributor ID:	Ubuntu Description:	Ubuntu 22.04.1 LTS Release:	22.04 Codename:	jammy

### Version of Telegram Desktop

4.5.2 (and all previous versions I've used)

### Installation source

Snap

**Comment by ilya-fedin** [comment]
I test the snap package from time to time and it survived a lot of updates during this time, it never discarded accounts or settings. So can't reproduce, sorry :(

**Comment by justabaka** [comment]
I've got the same issue recently on the latest telegram-desktop (4.5.3 installed from snap). Ubuntu 22.04.1 LTS

**Comment by shbmira** [comment]
I've always had this issue, for both 20.04 and 22.04.
