### ISSUE TITLE
Code block font issue

### ISSUE THREAD

**Issue by glebsam** [telegramdesktop/tdesktop#2567]
### Steps to reproduce
1. Write a message, use "```" for code block
2. Check how it looks 
### Expected behavior

Code showed correctly
### Actual behavior

Code replaced with squares (see screenshots below)
### Configuration

**Operating system:**
Ubuntu 16.10 (On Ubuntu 16.04 this function worked fine)

**Version of Telegram Desktop:**
0.10.19
### Logs

[log_14_30.txt](https://github.com/telegramdesktop/tdesktop/files/550586/log_14_30.txt)
[mtp_14_30.txt](https://github.com/telegramdesktop/tdesktop/files/550585/mtp_14_30.txt)
[tcp_14_30.txt](https://github.com/telegramdesktop/tdesktop/files/550584/tcp_14_30.txt)

Telegram Desktop
![telegram_mono_font_issue](https://cloud.githubusercontent.com/assets/10254791/19686585/72986a24-9aca-11e6-8c1c-c34de2d24eee.png)

Telegram on Android
![screenshot_20161025-130350](https://cloud.githubusercontent.com/assets/10254791/19686574/693c911c-9aca-11e6-9d93-f0e5cc05998a.png)

**Comment by dayfuaim** [comment]
Same problem.
TDesktop 0.10.19 @Ubuntu 16.10.

**Comment by ilot999** [comment]
Maybe there is any workaround?

**Comment by confususs** [comment]
Same problem.
TDesktop 0.10.19 Archlinux

**Comment by ilot999** [comment]
Upgrade 0.10.20 - the issue is still present.

**Comment by ilot999** [comment]
**Finally, there is a workaround.** 
In my home directory, I found a directory named `.TelegramDesktop`. And in this directory, another one, named `fontconfig`. It is what you need to remove, and then restart Telegram Desktop. 

```
cd ~/.TelegramDesktop
rm -rf fontconfig
```

![image](https://cloud.githubusercontent.com/assets/10254791/21938755/af6644e8-d9cd-11e6-8652-12c6625dac52.png)

**Comment by fishhead108** [comment]
@glebsam unfortunately, it doesn't works for me: 
- Arch Linux 4.9.8-1-ARCH
- i3WM
- Telegram

**Comment by dayfuaim** [comment]
@glebsam For me too:

- Ubuntu 16.10
- Unity
- Telegram 1.0.5
- fontconfig 2.11.94-0ubuntu2

**Comment by GabMus** [comment]
Same problem here

- Arch Linux 4.9.9-1-ARCH
- GNOME-Shell
- Telegram 1.0.14
- fontconfig 2.12.1-4

Here's a screenshot:

![scrot](http://i.imgur.com/hucq4EE.png)

If I open it up on the terminal here's the output
```
$ ./Apps/Telegram/Telegram
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
```

I have the same setup (os, packages versions etc) on my desktop PC and this problem doesn't seem to happen there.
Please investigate this ASAP as it breaks the user experience.

**Comment by GabMus** [comment]
Ok, small update, seems that the Fontconfig errors I have posted previously also happen on installations where the code blocks are shown correctly, so it should be unrelated

**Comment by glebsam** [comment]
@fishhead108 , @dayfuaim , @GabMus Looks like this issue is not observed on clean installations of recent TD. If so, I guess this instruction will help:

1. Kill Telegram Desktop
2. Remove the whole `~/.TelegramDesktop` directory and the directory, from which TD was run. 
3. Perform clean install from https://desktop.telegram.org/

**Comment by GabMus** [comment]
that's what I did

```
rm -r .TelegramDesktop
rm: cannot remove '.TelegramDesktop': No such file or directory
# found out TelegramDesktop is in .local/share
rm -r .local/share/TelegramDesktop
rm -r Apps/Telegram/
```

I proceeded to download a Telegram Desktop again, I logged in, and still the problem is there.

This method doesn't work for me

**Comment by ilsawa** [comment]
```
/opt/Telegram/Telegram 
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/70-fonts-bpg-georgian.conf", line 12: bad alias
Fontconfig warning: "/etc/fonts/conf.d/70-fonts-bpg-georgian.conf", line 21: bad alias
Fontconfig warning: "/etc/fonts/conf.d/70-fonts-bpg-georgian.conf", line 30: bad alias
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/70-fonts-bpg-georgian.conf", line 12: bad alias
Fontconfig warning: "/etc/fonts/conf.d/70-fonts-bpg-georgian.conf", line 21: bad alias
Fontconfig warning: "/etc/fonts/conf.d/70-fonts-bpg-georgian.conf", line 30: bad alias
```
Hmm, this error occurs if you are using older versions of fontconfig library. Perhaps they are statically linked into the binary file.

**Comment by dikiaap** [comment]
I had a same problem like you all and all methods from above is doesn't work.

**Comment by dikiaap** [comment]
Now, mine is works. But the code snippets becomes italic.
What fonts used in telegram? Maybe I can install related fonts.

![screenshot from 2017-05-31 22-44-10](https://cloud.githubusercontent.com/assets/8542502/26640838/0b8d3370-4653-11e7-9920-95d85140b05e.png)

**Comment by kelytha** [comment]
I started having this issue recently on my Linux machine. Removing `.local/share/TelegramDesktop/fontconfig` didn't solve the issue.

The really weird thing is that it used to work, then the issue just appeared out of nowhere.

**Comment by kelytha** [comment]
Installing `ttf-liberation` solved the issue.

Apparently it's the fallback font selection here that fails for some weird reason:
https://github.com/telegramdesktop/tdesktop/blob/a69304fd2547961f684f249a7ea590bbf604f736/Telegram/SourceFiles/app.cpp#L2284

**Comment by confususs** [comment]
Thank you for that solution @kelytha! I regularly share code in Telegram and this has made my life so much better.

**Comment by shirishag75** [comment]
At least in debian ttf-liberation is a transitional dummy package and fonts-liberation is the real package. 

```
[$] aptitude search liberation                                                                                                    
i   fonts-liberation                                                - Fonts with the same metrics as Times, Arial and Courier                   
v   fonts-liberation:i386                                           -                                                                           
i   fonts-liberation2                                               - Fonts with the same metrics as Times, Arial and Courier (v2)              
i   ttf-liberation                                                  - transitional dummy package                                                
v   ttf-liberation:i386                                             -                  
```

But running telegram from console doesn't improve things at all - 

```
[$] ./Telegram                                                                                                                      
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
```

So the issue still persists. FWIW, I'm running Debian testing i.e. buster.

**Comment by anotherbugmaster** [comment]
Same issue here. Installing ttf-liberation helped, but warnings are still persist.

**Comment by Aokromes** [comment]
Test after https://github.com/telegramdesktop/tdesktop/commit/8ee958bfa08b2ba87cffaf8de4b65b6890e59ea3
