### ISSUE TITLE
Telegram compression is bad for some images with sizes 1280-2560

### ISSUE THREAD

**Issue by Veetaha** [telegramdesktop/tdesktop#25676]
### Steps to reproduce

Enable the "Send large photos" experimental feature of Telegram Desktop, then see [the wiki page](https://github.com/Veetaha/snowpity/wiki/Telegram-images-compression). I am sorry to admit, that the image used for comparison is rather explicit, but I couldn't find an analogous SFW image that shows such a drastic difference in quality.

In my wiki page, I showed a comparison of the image uploaded via telegram using `1200x1600` and `900x1200` variants that were generated by Twitter.

### Expected behaviour

The `1200x1600` image should not have visible "stairs" when viewed on mobile. The contours should be smooth.

### Actual behaviour

The image uploaded via `1200x1600` variant has visible "stairs" on its contours when viewed via a mobile app, where the Telegram-generated variant `960x1280` is displayed.

If we originally upload an image of `900x1200`, then its quality will be better, so clearly, Telegram compresses the image worse than Twitter.

### Operating system

Windows 11, Ubuntu 22.04.1 LTS (tested on both)

### Version of Telegram Desktop

4.5.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This is issue tracker for client while compression happens server-side. You need to report the issue as an API issue.

**Comment by john-preston** [comment]
In case of default settings the image is scaled down to 1280x1280 using QImage::scaled(1280, 1280, keepaspectratio, smoothtransform), it should scale it down well enough. If it scales poorly - perhaps it should be fixed in Qt :(

If the downscaled to 1280 looks worse than uploaded-without-downscaling 1200 then it looks like it's a problem of downscaling in tdesktop.

**Comment by ilya-fedin** [comment]
@john-preston if I understand the report right, he says when the client uploads a 2560px image, the 1280px image generated by the server has worse quality than when the client uploads a 1280px image.

**Comment by mrg21** [comment]
Using QImage::scaled with smoothtransform use the simple bilinear scaling resize algorithms, which has major problems with lines in downscaled images. A better resize algorithm like bicubic or lanczos instead of bilinear might be useful.

**Comment by ilya-fedin** [comment]
QImage::scaled is used for the scaling to the limit (1280px without the option, 2560px with the option). The lower resolutions are generated by the server with the progressive jpeg feature (jpeg_simple_progression likely) when it re-compresses the image.

**Comment by Veetaha** [comment]
@ilya-fedin is right. This is the problem with Telegram's server-side compression. This issue reproduces if I upload an image of sizes 1280-2560 using the telegram bot API. So I reported it at https://bugs.telegram.org/c/23931

**Comment by ilya-fedin** [comment]
Those smaller sizes are generated by [jpeg progression](https://www.liquidweb.com/kb/what-is-a-progressive-jpeg/) what is just information in metadata, it's not really re-scaling, so I have a feel fixing this is not possible. The sizes other than the full size of jpeg image will always be poor and it's something we have to live with.

**Comment by Veetaha** [comment]
What is the rationale for using jpeg progression? Twitter copes with re-scaling quite well without the quality reduction. I'd Telegram could switch to using the algorithm that Twitter does. Both Telegram and Twitter need to deal with huge scale, so I suppose Twitter did their best to select the best algorithm and it works for them both quality and performance-wise.

**Comment by ilya-fedin** [comment]
Traffic and (server-side) storage I suppose. Twitter doesn't let you to send arbitrary data after all, so in Telegram it has sense to aggressively compress the images, you can just uncheck the checkbox if you don't want that. So the server won't waste space whenever you check the compress image checkbox, providing more space for uncompressed images and other files. It's all my speculation, though.
