### ISSUE TITLE
App crashes after selecting the return button in "Add Account" area

### ISSUE THREAD

**Issue by The-Seyed** [telegramdesktop/tdesktop#25672]
### Steps to reproduce

More options button => Add Account => Return button (left arrow-shaped button)

### Expected behaviour

Returning to Chats list

### Actual behaviour

App crashed with error `Aborted (core dumped)` on the terminal.

### Operating system

Ubuntu 20.04

### Version of Telegram Desktop

4.5.0

### Installation source

Snap

**Comment by Aokromes** [comment]
try with 4.5.2 beta download from desktop.telegram.org not snap, not flakpak.

**Comment by The-Seyed** [comment]
Also fixed in `4.5.2` version from `Snap`. So I'm closing this issue. Thank you for the response.
