### ISSUE TITLE
Missing build system requirements

### ISSUE THREAD

**Issue by jelly8173** [telegramdesktop/tdesktop#25677]
### Steps to reproduce

1. Use Linux
2. Open tdesktop/docs/building-linux.md
3. Choose docker way
4. Start preparing build system by issuing cmd from **Prepare libraries** step
5. Receive No space left on device some hours later

### Expected behaviour

docs/building-linux.md should contain remark of free space needed to prepare docker container tdesktop:centos_env

### Actual behaviour

docs/building-linux.md does not contain any information of free space requirements

### Operating system

Gentoo Linux

### Version of Telegram Desktop

git eb0642f569f82370f5cb49a339f64f6be2c1bc0c 

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I'm not quite sure it should and I don't want to take liability of checking the required space after any change. Personally I think this should be wontfix.

**Comment by jelly8173** [comment]
It should not require frequent changes, increments of 100GB is ok. I have 250GB of free space rn and its not enough. How much should i clean more? Is it possible at all if my whole storage is 500GB?

**Comment by ilya-fedin** [comment]
Yeah, it likely needs a lot of space due to debug symbols and LTO. It's not documented, but there's configuration possible (made mainly for GitHub actions) and you can disable debug symbols + debug variants of libraries by setting DEBUG environment variable to empty value and you can disable LTO by setting LTO environment variable to empty value.
https://github.com/telegramdesktop/tdesktop/blob/eb0642f569f82370f5cb49a339f64f6be2c1bc0c/.github/workflows/docker.yml#L34

**Comment by jelly8173** [comment]
Ok, thanks, I'll benchmark it when my docker cache purges

**Comment by jelly8173** [comment]
I thought it is possible to add last build step of build system building process that would calculate space used to build build system but when i run du -c on /var/lib/docker it hangs forever because of too many files. It takes 15 minutes even to delete them, no way to count their size

**Comment by jelly8173** [comment]
This way it took ~160GB

**Comment by ilya-fedin** [comment]
I'm not sure that's the right measurement (if you disabled both debug and LTO) given that GitHub provides only 14 GB of space
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by jelly8173** [comment]
I see what I see. Before start docker builder cache was pruned and I had ~250 GB of free space. Now free space at 90GB, so builder cache and finished image takes remaining 160GB.

During compilation it took more, but you need to build some kind of graph to see that.

Resulting image without builder cache takes only 2.27 GB

**Comment by jelly8173** [comment]
I dont belive that anyone have ever tried to build this outside of github infrastructure.
Docker build should go flawless, right?

![Screenshot 2023-01-05 at 10 57 26](https://user-images.githubusercontent.com/89387840/210730771-db615c1b-38aa-47f0-9830-9d367372d3f2.png)

**Comment by ilya-fedin** [comment]
Looks like you forgot the `--recursive` flag when cloning the repo

**Comment by jelly8173** [comment]
True, my bad
