### ISSUE TITLE
Screen sharing without options (Ubuntu/Wayland)

### ISSUE THREAD

**Issue by khalil-i-o** [telegramdesktop/tdesktop#25674]
### Steps to reproduce

1. Start a video call
2. Share screen (button)

### Expected behaviour

Screen sharing options, to select a specific window or the whole screen.

![imagen](https://user-images.githubusercontent.com/68512577/210455266-9b3034df-8138-43a1-8c93-63cf5b7148ce.png)

### Actual behaviour

The native GNOME screen sharing window, without the screen selection options. Sometimes, in 1-to-1 calls, they don't see what they are sharing screen.

![imagen](https://user-images.githubusercontent.com/68512577/210455478-20cd59a9-15ba-4363-903b-c1f604e1cfc3.png)

### Operating system

Ubuntu 22.04.1 | Gnome 42.5 (Wayland)

### Version of Telegram Desktop

4.5.2

### Installation source

Static binary from official website

### Logs

```shell
$ /Telegram
D/tgvoip: === Updating voip config ===
D/tgvoip: {"enable_vp8_encoder":true,"enable_vp8_decoder":true,"enable_vp9_encoder":true,"enable_vp9_decoder":true,"enable_h265_encoder":true,"enable_h265_decoder":true,"enable_h264_encoder":true,"enable_h264_decoder":true,"audio_frame_size":60,"jitter_min_delay_60":2,"jitter_max_delay_60":10,"jitter_max_slots_60":20,"jitter_losses_to_reset":20,"jitter_resync_threshold":0.5,"audio_congestion_window":1024,"audio_max_bitrate":20000,"audio_max_bitrate_edge":16000,"audio_max_bitrate_gprs":8000,"audio_max_bitrate_saving":8000,"audio_init_bitrate":16000,"audio_init_bitrate_edge":8000,"audio_init_bitrate_gprs":8000,"audio_init_bitrate_saving":8000,"audio_bitrate_step_incr":1000,"audio_bitrate_step_decr":1000,"use_system_ns":true,"use_system_aec":true,"force_tcp":false,"jitter_initial_delay_60":2,"adsp_good_impls":"(Qualcomm Fluence)","bad_call_rating":true,"use_ios_vpio_agc":false,"use_tcp":false,"audio_medium_fec_bitrate":20000,"audio_medium_fec_multiplier":0.1,"audio_strong_fec_bitrate":7000}
Unsupported modifier, resource creation failed.
XXX: resource creation failed
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:Change QP Range from(0,51) to (12,42)
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(3) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(6) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(9) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(12) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(15) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(18) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(21) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(24) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(27) is large
Unsupported modifier, resource creation failed.
XXX: resource creation failed
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(30) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:Actual input framerate 0.000000 is different from framerate in setting 15.000000, suggest to use other rate control modes
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(33) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(36) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(39) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(42) is large
[OpenH264] this = 0x0x7fea4a2c3ac0, Warning:[Rc] iDid = 0,iContinualSkipFrames(45) is large
Unsupported modifier, resource creation failed.
XXX: resource creation failed
```

**Comment by ilya-fedin** [comment]
That's a restriction of Wayland, the API returns a system-provided dialog you see for every request to get screen bytes, so displaying the same dialog as on X11 will lead to multiple system dialogs spawned, for each preview. I believe the current behavior provides the best possible UX Wayland APIs (or at least webrtc APIs, the media framework Telegram uses for this, developed by Google and hiding platform nuances) can provide.

**Comment by ilya-fedin** [comment]
Oh, your first message in the issue sounds like you want the non-system dialog on Wayland what is sadly not possible. The new explanation sounds like a webrtc regression though :(

**Comment by ilya-fedin** [comment]
Looks like webrtc developers made CreateRawScreenCapturer and CreateRawWindowCapturer provide flags to system APIs to show only screens and windows respectively, but made no new API to show everything together. So looks like this bug will stay until webrtc developers fix this (if they plan to fix this at all...).

**Comment by ilya-fedin** [comment]
It was decided to fix this with a patch in webrtc fork

**Comment by john-preston** [comment]
Please check the 4.5.3 version.
