### ISSUE TITLE
Off-center text selection (Ubuntu/Wayland)

### ISSUE THREAD

**Issue by khalil-i-o** [telegramdesktop/tdesktop#25673]
### Steps to reproduce

1. Open a text message from any chat containing one or more lines of text.
2. Try to select part of the text with the cursor (mouse).

### Expected behaviour

The text line to be selected is the cursor line, where it is visually located.

### Actual behaviour

The line selected with the cursor is the line below the one visually indicated.

### Operating system

Ubuntu 22.04.1 | Gnome 42.5 (Wayland)

### Version of Telegram Desktop

4.5.2

### Installation source

Static binary from official website

### Logs

```shell
$ /Telegram
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
QTextCursor::setPosition: Position '8388607' out of range
QTextCursor::setPosition: Position '8388607' out of range
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
```

**Comment by ilya-fedin** [comment]
I can't reproduce the text selection bug on my machine with Plasma Wayland, sorry :(
The big cursor bug is the consequence of GNOME using its own custom settings storage instead of using the way everyone else (Qt, SDL, mpv) uses. Since Telegram is a cross-platform application written in Qt rather than a GNOME application, it's affected as well. https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5894

**Comment by ilya-fedin** [comment]
> In addition, the interface scaling ranges are: 200%, 220%, 240%, 260%, 280%, 300%. While in X.Org the ranges go from 100%, 125%, 150%, 200%, 250%, 300%.

That's due to the technical details of UI scaling on Wayland. Due to them, you can't scale less, sorry.

**Comment by ilya-fedin** [comment]
> I think that putting it as "can't reproduce" is misleading, because in the description of the problem it is stated that it is Gnome 42.5 (Wayland) not KDE Plasma

This shouldn't matter until GNOME has a bug.

> The strange thing is that other Qt-based applications do not have the same problem.

Other Qt-based applications are likely use a different Qt version? Qt removed GNOME from Wayland blacklist very recently, Qt was working on GNOME only using Xwayland previously.

**Comment by ilya-fedin** [comment]
> Probably, but I would have no way of corroborating exactly which version they use.

If they are installed through system package manager, it should say. If they are installed via flatpak or snap, their manifest should say. If they are standalone binaries, their build scripts should say. And you can force native Wayland backend with `QT_QPA_PLATFORM=wayland` environment variable (unless the application in question override the variable value before spawning QApplication).

> It's weird that it's the only application with the bug, many running on Ubuntu/Gnome/Wayland. But hey, tdesktop has nothing to fix here, again everything is external and dependent (in this case on GNOME).

It's quite a widespread thing as people usually have no Qt applications on their computers or these applications use a very outdated Qt version ("stable" distributions say hello). There are also two major Qt versions actively used currently: 5 an 6, tdesktop's official builds are built with Qt 6 for Linux (6.4.1 precisely right now). I also can't reproduce in a clean Ubuntu 22.04 VM though.

**Comment by ilya-fedin** [comment]
> Would installing Qt6 solve any of the problems? Is there a way to force tgdesktop to run with Qt6?

I'm not quite sure what do you mean by this, if you're using tdesktop from official builds, it's already using Qt 6 as I already said.

**Comment by john-preston** [comment]
About the interface scale - you'll be able to scale 0.5 of the current default scale in the next beta version.

**Comment by ilya-fedin** [comment]
@john-preston have you checked these arbitrary scale values on Wayland? When I tried to have the values the same as with 1x scale, but divided by devicePixelRatio (50, 62, 75, 100, 125, 150), I got artifacts on shadows with 62 and 125 values at least (75 may have them as well, didn't check).

**Comment by ilya-fedin** [comment]
There were nothing done for it to solve :thinking:

**Comment by ilya-fedin** [comment]
Maybe it's non-deterministic?

**Comment by ilya-fedin** [comment]
There were previously kinds of bugs that Qt's position detection bugs with multiple screens on Wayland. If you have multiple screens and test on another one now, it could explain.

**Comment by ilya-fedin** [comment]
If you're testing with snap now rather than static binary, it would also explain as snap package uses mesa from PPA now that can directly affect surface behavior

**Comment by ilya-fedin** [comment]
> Correction, if there was a system update

ah, maybe it is

**Comment by ilya-fedin** [comment]
> the cursor is not agiggant

giant?

**Comment by ilya-fedin** [comment]
I mean does "agiggant" means "giant"?

**Comment by ilya-fedin** [comment]
It's apparently not giant because Qt was updated to 6.4.2 and it now gets cursor settings from GNOME... Although I wouldn't expect this to affect click position handling.

**Comment by ilya-fedin** [comment]
idk what has changed, but now I'm able to reproduce this in my Ubuntu 22.04 VM

**Comment by ilya-fedin** [comment]
GNOME seem to do a very weird thing: it changes the cursor anchor for every other cursor than the generic pointer, so it displays it way upper and left than it is. If I try to screenshot with mouse, the screenshot tool displays the cursor where it is in reality. This is most obvious when finding the point to resize the window.

**Comment by ilya-fedin** [comment]
@khalil-i-o are you using Ubuntu in a VM, too? I can assume this is a bug in the virtualization agent (spice-vdagent), I saw such kind of bugs with Plasma Wayland previously in virtualized environments (and, well, it's very fragile and easy to see it even now with multiple virtual screens or by killing spice-vdagent).

**Comment by ilya-fedin** [comment]
I can reproduce this with any application in the system now, in fact

**Comment by ilya-fedin** [comment]
> This is exactly what happened to me before, up and to the left.

This is reproducible in any application for me, not only tdesktop
