### ISSUE TITLE
Animated emojis on the topic icon are not displayed correctly

### ISSUE THREAD

**Issue by luccascomvoce** [telegramdesktop/tdesktop#25670]
### Steps to reproduce

1. Set an animated emoji as a topic icon
2. Telegram will display bad static frame

Emoji pack used:
https://t.me/addemoji/LoadingEmoji
https://t.me/addemoji/AnimatedIcon9

### Expected behaviour

The correct frame should be displayed when there is no animation (telegram android screenshot)

![photo_2023-01-03_09-02-40](https://user-images.githubusercontent.com/65538684/210353678-6c42c5c9-27d2-44d9-bd0b-6c62f15bd406.jpg)

### Actual behaviour

Weird and bad frames are displayed, making emojis unrecognizable

![image](https://user-images.githubusercontent.com/65538684/210353420-ea9284e7-566e-4d7e-8616-1303619f8cbf.png)

### Operating system

Windows 11 22H2

### Version of Telegram Desktop

4.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
try updating to 4.5.2
