### ISSUE TITLE
A bug with my monitor when I looking a photo or video in telegram

### ISSUE THREAD

**Issue by vladivanchik** [telegramdesktop/tdesktop#25684]
### Steps to reproduce

1.I need to open some media in telegram. Whatever, photos or video.
2.My monitor has been turn off

### Expected behaviour

Explaned in first question

### Actual behaviour

So... I'm playing in videogame. and my RAM has refused to work(it happens). So when I revive my PC i noticed my video driver has broken. When I re-install video driver. I check telegram,and noticed the my monitor off, when i open any image or video.

### Operating system

Windows 10, 22h2

### Version of Telegram Desktop

4.52(stable)

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Telegram doesn't use any API to turn off your monitor obviously, so this means the driver crashes whenever you open media viewer (that uses GPU to draw itself), so it's your driver's fault.

**Comment by vladivanchik** [comment]
> Telegram doesn't use any API to turn off your monitor obviously, so this means the driver crashes whenever you open media viewer (that uses GPU to draw itself), so it's your driver's fault.

Yeep. I solve this problem by turn off the Free-Sync in driver setting.
