### ISSUE TITLE
We can see who leaves our groups

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#25682]
### Is your feature request related to a problem?

Yes it is. I need to know who leaves the group & I don't understand why after 100 members you remove this feature.

### Describe the solution you'd like

Just like with groups under 100 members or members who join, we should be able to see who leaves.

### Describe alternatives you've considered

See above.

Please fix.

Thanks

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
