### ISSUE TITLE
Crashes after saving selected

### ISSUE THREAD

**Issue by VetaLioSTV** [telegramdesktop/tdesktop#25689]
### Steps to reproduce

1. Apply setting "Ask for path location before saving"
2. Select several messages with photo
3. Right click to open context menu, choose "save selected"
4. Instant crash

### Expected behaviour

Should be opened default windows dialog box where user can choose path for saving.

### Actual behaviour

Instant crash after clicking to "save selected".

### Operating system

Win 10

### Version of Telegram Desktop

v4.4.1 - v4.5.2

### Installation source

Static binary from official website

### Logs

```
[1003/141219.358:ERROR:crash_report_database_win.cc(428)] unexpected header
[1003/212806.336:ERROR:crash_report_database_win.cc(428)] unexpected header
[0122/171737.739:ERROR:directory_reader_win.cc(43)] FindFirstFile: Системе не удается найти указанный путь. (0x3)
[0122/221327.301:ERROR:file_io.cc(90)] ReadExactly: expected 36, observed 0

```

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by VetaLioSTV** [comment]
@john-preston any ideas when it will go to master/production so i can test it? 
Regards

**Comment by john-preston** [comment]
@VetaLioSTV Please check the latest beta version 4.5.5, it should have this commit.

**Comment by VetaLioSTV** [comment]
@john-preston totally forgot about it. So checked in 4.6 x64, works as expected. Well done. 

The only one thing which are missing is that it shows incorrect toast message "saved to downloads", but in fact path is different.
