### ISSUE TITLE
[Feature Request] Name chat windows with user's name and unread count

### ISSUE THREAD

**Issue by arx8x** [telegramdesktop/tdesktop#25686]
### Is your feature request related to a problem?

Windows of the same app are usually named contextually. On Chrome browser (chrome allows you to rename windows), windows are named based on the active tab, on Terminal, windows are named based on the running program and shell and on code editors, windows are named based on the project name/project directory and current file. 
This make it easy to switch to the window by just looking at the title in window managers. With many windows open, this is a really neat feature when properly implemented.
Telegram added chat windows where you can have multiple windows of telegram dedicated for a particular chat. This is a really helpful feature and I'm really glad we got this. However, when you have a few chats open, it becomes difficult to see which window belongs to which chat in window managers. Every window has the title "Telegram". So you would need to actually go into the chats or look at the small window previews to find out which chat it is. 

Screenshots describing the issue and comparing Telegram's windows to iTerm2 and Chromium

Alt-tab's window switching UI
![image](https://user-images.githubusercontent.com/16128407/210766737-0a2458de-c306-420b-94b6-90851f78fd7d.png)

macOS's native window switching UI. Telegram windows have to titles under them
![SCR-20230105-lvo-2](https://user-images.githubusercontent.com/16128407/210767182-d46ae45c-194f-489e-a261-b7e66a62680a.png)

### Describe the solution you'd like

Name the additional windows with chat's name and unread count of that particular chat. Additionally, indicate with a circular ASCII character if there are unread messages in the window. If possible also show a clipped version of the last message
Examples:

Window title for chat with no unread messages
"John Doe"

Window titles for chat with unread messages 
"● John Doe - I've terminate th..."
"● John Doe (2) - 🧩 Sticker"
"● John Doe (3) - Photo"

"● Tech News (512) - News exciting update..."
"● Family Group (2) - John Doe: Photo"

### Describe alternatives you've considered

none

**Comment by ilya-fedin** [comment]
#10067

**Comment by arx8x** [comment]
I didn't notice that issue. Shall I keep the this Issue open?

**Comment by ilya-fedin** [comment]
No, it's a duplicate

**Comment by arx8x** [comment]
This has been implemented
