### ISSUE TITLE
Session unexpectedly terminated across all clients - can no longer log in

### ISSUE THREAD

**Issue by ctp9** [telegramdesktop/tdesktop#25685]
### Steps to reproduce

Without warning - Telegram has terminated my active login session on all my devices:
- desktop app
- Android app
- macOS app

Now I am unable to login because the phone number that was used to register the account 4+ years ago is no longer in service.

No other login options are provided on either client - desktop or mobile - so my 2FA/login password is essentially useless because I cannot use it to log in.

Please help. I have been using the account for more than 4 years - I have a lot of conversations and important information in there. I am feeling very discouraged upon seeing all my clients terminate my active session. The crazy thing is that it happened while I was actively typing a message to a contact! It kicked me off mid-sentence.

### Expected behaviour

Sessions are not erroneously terminated.

### Actual behaviour

Session suddenly terminated - with no prior warning or expectation. I was unable to finish sending my message to a contact. After changing screens - I was no longer able to access my account. It is asking me to log in on all clients now.

### Operating system

Windows, Android, macOS

### Version of Telegram Desktop

4.5.2 (desktop), 9.3.3 (Android), 9.3 (macOS)

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
this is a bug tracker for telegram desktop. we cannot help you.

**Comment by ctp9** [comment]
Please delete this issue then. You have my permission.
