### ISSUE TITLE
Search on topic comments

### ISSUE THREAD

**Issue by vipermagic** [telegramdesktop/tdesktop#25683]
### Steps to reproduce

1. Go to some channel
2. Choose the post with comments and enter to read some comments in it.

### Expected behaviour

In the upper right corner there must be a search tool icon to search inside chosen topic.

### Actual behaviour

But it is gone :(
Two days ago (2023.01.03) I used Ctrl+F and it worked well.
May be I wrong somewhere but anyway in Android version this search works.

### Operating system

Kubuntu 20.04, KDE Plasma 5.18.8, KDE Frameworks 5.68.0

### Version of Telegram Desktop

4.5.2

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8716
