### ISSUE TITLE
[Feature Request] Internal Browser

### ISSUE THREAD

**Issue by Rahmanism** [telegramdesktop/tdesktop#25696]
### Is your feature request related to a problem?

In countries like Iran, where the internet is restricted and filtered, Telegram users (both mobile and desktop) can use an internal browser that works with a proxy (MTProto or Socks) to access the internet freely.

### Describe the solution you'd like

We use Telegram with proxies (MTProto or Socks), in the filtered and limited internet of Iran. If there was an internal browser in Telegram (both mobile and desktop versions) that worked with those proxies, we could use it to access the free internet.

It would be a perfect and splendid feature for Telegram for ages, and it could solve the problem of accessing to the free internet for people of countries like Iran.

### Describe alternatives you've considered

Now we use some kind of VPNs on our cellphones and desktop computers, but the government filters them every day.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by Rahmanism** [comment]
It's not a bug. It's a feature that I requested. :|
@Aokromes
