### ISSUE TITLE
Closing audio player does not close anymore

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#2569]
### Steps to reproduce
1. play a sound file
2. click on "X"
### Expected behaviour

Audio player should close
### Actual behaviour

It minimize in the title bar.

We should have close AND minimize button, having no way of closing the player makes Telegram stealing all the media keys press events (had to deactivate them altogether in shortcut-custom.json)
### Configuration

**Operating system:**
Win 7

**Version of Telegram Desktop:**
0.10.19 stable

**Comment by john-preston** [comment]
@Geobert You can close it in the online player in the top-right corner, where the time is displayed.

**Comment by Geobert** [comment]
I see, nonetheless, I think that two clicks for closing it a lot, and clicking an "X" button to minimize is anti ergonomic. 

Thank you for the answer

**Comment by Geobert** [comment]
0.10.21a fixes this
