### ISSUE TITLE
Telegram-desktop segfault

### ISSUE THREAD

**Issue by asciiscry3r** [telegramdesktop/tdesktop#25695]
### Steps to reproduce

1. install telegram from github
2. create sanbox for him

#!//usr/bin/env bash

firejail --noroot --seccomp --apparmor --nonewprivs --quiet --private-dev --nogroups \
	--blacklist=/usr/bin/less \
	--blacklist=/usr/bin/more \
	--blacklist=/usr/bin/vim \
	--blacklist=/usr/bin/nano \
	--blacklist=/usr/bin/rndaddentropy \
	--blacklist=/usr/bin/sudo \
	--blacklist=/etc/passwd \
	--blacklist=/etc/sahdow \
	--blacklist=/etc/gshadow \
	--blacklist=/etc/gshadow~ \
	--blacklist=/etc/passwd~ \
	--blacklist=/etc/sahdow~ \
	--blacklist=/usr/bin/dd \
	--blacklist=/usr/bin/echo \
	--blacklist=/dev/mei0 \
	--blacklist=/dev/mei \
	--whitelist=/home/max/Pictures \
	--whitelist=/home/max/Videos \
	--name=telegram telegram-desktop

4. Launch this and if you have enough luck you get error 

### Expected behaviour

I have running telegram desktop in firejail sandbox on Arch Linux
`l1tf=flush,nosmt mds=full,nosmt tsx_async_abort=full,nosmt mmio_stale_data=full,nosmt retbleed=auto,nosmt mitigations=auto,nosmt nosmt=force`

### Actual behaviour

[  +0,000002] telegram-deskto[4604]: segfault at 7d3be2ca2990 ip 00007d3c15d16322 sp 00007ffc26dcd230 error 4 in libc.so.6[7d3c15cb0000+15b000] likely on CPU 2 (core 2, socket 0)
[  +0,000008] Code: 54 24 f8 c3 0f 1f 40 00 f3 0f 1e fa 41 57 41 56 41 55 41 54 55 53 48 83 ec 48 64 48 8b 04 25 28 00 00 00 48 89 44 24 38 31 c0 <8b> 87 d0 02 00 00 85 c0 0f 88 58 01 00 00 49 89 ff 48 39 bf 20 06
[  +0,000006] potentially unexpected fatal signal 11.
[  +0,000001] CPU: 2 PID: 4604 Comm: telegram-deskto Tainted: P     U     OE      6.1.3-zen1-1-zen #1 e84ae47f4a6d6b4d7d2701d8d72f471c5f76a3ff
[  +0,000003] Hardware name: Dell Inc. Precision 5510/08R8KJ, BIOS 1.23.0 07/06/2022
[  +0,000001] RIP: 0033:0x7d3c15d16322
[  +0,000016] Code: 54 24 f8 c3 0f 1f 40 00 f3 0f 1e fa 41 57 41 56 41 55 41 54 55 53 48 83 ec 48 64 48 8b 04 25 28 00 00 00 48 89 44 24 38 31 c0 <8b> 87 d0 02 00 00 85 c0 0f 88 58 01 00 00 49 89 ff 48 39 bf 20 06
[  +0,000002] RSP: 002b:00007ffc26dcd230 EFLAGS: 00010246
[  +0,000001] RAX: 0000000000000000 RBX: 00007d3c134981a8 RCX: 0000000000000000
[  +0,000002] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 00007d3be2ca26c0
[  +0,000001] RBP: 00007ffc26dcd3d0 R08: 0000000000000001 R09: 00007d3be97002b0
[  +0,000001] R10: 0000000000000000 R11: 0000000000000206 R12: 00007d3c134981c0
[  +0,000001] R13: 00007d3be9700268 R14: 00007d3c15e68208 R15: 00007d3be6c6c900
[  +0,000001] FS:  00007d3c15895d00 GS:  0000000000000000

### Operating system

GNU/Linux 6.1.3

### Version of Telegram Desktop

4.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by ilya-fedin** [comment]
> [ +0,000002] telegram-deskto[4604]: segfault at 7d3be2ca2990 ip 00007d3c15d16322 sp 00007ffc26dcd230 error 4 in libc.so.6[7d3c15cb0000+15b000] likely on CPU 2 (core 2, socket 0)
> [ +0,000008] Code: 54 24 f8 c3 0f 1f 40 00 f3 0f 1e fa 41 57 41 56 41 55 41 54 55 53 48 83 ec 48 64 48 8b 04 25 28 00 00 00 48 89 44 24 38 31 c0 <8b> 87 d0 02 00 00 85 c0 0f 88 58 01 00 00 49 89 ff 48 39 bf 20 06
> [ +0,000006] potentially unexpected fatal signal 11.
> [ +0,000001] CPU: 2 PID: 4604 Comm: telegram-deskto Tainted: P U OE 6.1.3-zen1-1-zen #1 e84ae47f4a6d6b4d7d2701d8d72f471c5f76a3ff
> [ +0,000003] Hardware name: Dell Inc. Precision 5510/08R8KJ, BIOS 1.23.0 07/06/2022
> [ +0,000001] RIP: 0033:0x7d3c15d16322
> [ +0,000016] Code: 54 24 f8 c3 0f 1f 40 00 f3 0f 1e fa 41 57 41 56 41 55 41 54 55 53 48 83 ec 48 64 48 8b 04 25 28 00 00 00 48 89 44 24 38 31 c0 <8b> 87 d0 02 00 00 85 c0 0f 88 58 01 00 00 49 89 ff 48 39 bf 20 06
> [ +0,000002] RSP: 002b:00007ffc26dcd230 EFLAGS: 00010246
> [ +0,000001] RAX: 0000000000000000 RBX: 00007d3c134981a8 RCX: 0000000000000000
> [ +0,000002] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 00007d3be2ca26c0
> [ +0,000001] RBP: 00007ffc26dcd3d0 R08: 0000000000000001 R09: 00007d3be97002b0
> [ +0,000001] R10: 0000000000000000 R11: 0000000000000206 R12: 00007d3c134981c0
> [ +0,000001] R13: 00007d3be9700268 R14: 00007d3c15e68208 R15: 00007d3be6c6c900
> [ +0,000001] FS: 00007d3c15895d00 GS: 0000000000000000

These strings are quite useless. Didn't tdesktop create log.txt in its data folder, don't you have any terminal output? If the answer to both of this no then you have to get a trace with gdb. Given that it seem to be broken to the extent it doesn't even load to crash reporter, it's likely you have to build tdesktop from sources with debug build type to get a sane backtrace.

> GNU/Linux 6.1.3

Have you read the description of the field when filing the issue? Kernel version is useless and shouldn't be used as a value for this field.

**Comment by asciiscry3r** [comment]
doesn't  reproduce  after update and i will to close this bug report
