### ISSUE TITLE
[Feature Request] adding email service to telegram for create account with telegram special mail  

### ISSUE THREAD

**Issue by pyAref** [telegramdesktop/tdesktop#25699]
### Is your feature request related to a problem?

No, and it does not cause a problem

### Describe the solution you'd like

This idea helps to prevent the arrival of fake emails to create an account,
And with the help of this email service, you can send messages to Gmail or Yahoo , .....

### Describe alternatives you've considered

I think it has no replacement because it's new idea

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
