### ISSUE TITLE
Issues with Easy Effects + PipeWire

### ISSUE THREAD

**Issue by jazz-it** [telegramdesktop/tdesktop#25697]
### Steps to reproduce

1. Try using telegram-desktop on a linux distro with PipeWire with Easy Effects
2. Add some Input effects for microphone turned ON, e.g. **Speech Processor**, **Echo Canceller**, **Noise Reduction** and **Pitch**
3. Try make an audio call on Telegram and see what happens

### Expected behaviour

The Easy Effects enabled should work with microphone selected without any issues and one should be able to hear the other party without any additional noise or interruption.

### Actual behaviour

The voice of the person I'm talking to starts to crackle and become choppy, so I can't understand them at all.
As soon as I disable all the Input effects for my microphone, the communication become flawless again and there's no issue. Other applications ie. web based talk apps or Audacious don't have any issues with such setup.

### Operating system

Manjaro Linux, v22, KDE 5.101.0 / Plasma 5.26.4

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop uses https://github.com/kcat/openal-soft library to capture audio from audio devices, you need to report there.
