### ISSUE TITLE
build failed in windows, missing qt5 qml

### ISSUE THREAD

**Issue by wxz879526** [telegramdesktop/tdesktop#25701]
### Steps to reproduce

configure.bat x64 -D TDESKTOP_API_ID=my_id -D TDESKTOP_API_HASH=my_hash 

### Expected behaviour

build success

### Actual behaviour

CMake Error in Telegram/codegen/codegen/common/CMakeLists.txt:
  Imported target "external_qt" includes non-existent path

    **"H:/code/TBuild/Libraries/win64/Qt-5.15.7/include/QtQml"**

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

### Operating system

windows 10, visual studio 2022

### Version of Telegram Desktop

build version

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
is it possible you have another Qt installation?
