### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by bluemooduser** [telegramdesktop/tdesktop#25705]
### Is your feature request related to a problem?

I cannot use other apps while video calling someone or a group. You have to arrange all the windows on screen. It is annoying.

### Describe the solution you'd like

The option to enable PiP in video calls, video meetings.
At least to pin the window.

### Describe alternatives you've considered

I have to download a 3rd party program to pin the window.

**Comment by ilya-fedin** [comment]
#17089
