### ISSUE TITLE
I respect the attempt to do a 1x1 preview

### ISSUE THREAD

**Issue by sglazov** [telegramdesktop/tdesktop#25707]
### Steps to reproduce

cold January evening. night?
so I came up with the idea that I really need a 1x1 pixel picture that knows how to generate.

for a test, i threw it in the Saved Message chat and saw that the preview for the 1x1 picture is generated scalably (cool!) but trying to make the "background" is very different every time. i got interested and here i am.

### Expected behaviour

I can only guess, but it seems like it should be:

1. open the url of the picture
2. know the size
3. if it is less than N, don't do anything

but this definitely begs the question: what should be N?

### Actual behaviour

now previews and "background" previews don't make sense?

one more thing: I sent a link to the picture to bot `@WebpageBot`, because it responds to the preview card

and every time I go between the random chat and the transition to the bot, the preview is updated. i mean without clicking on the bot's buttons.

<details>
  <summary>show screenshots</summary>
  
![](https://user-images.githubusercontent.com/8128081/211426348-47d4f0c0-a43e-4185-acb7-f2250369bac6.png)

![](https://user-images.githubusercontent.com/8128081/211427035-c279895b-05b6-44b8-95a2-97a875bb4509.png)
</details>

----
sometimes it looks like art

### Operating system

macOS Big Sur 11.2.3 (20D91)

### Version of Telegram Desktop

4.5.3

### Installation source

Mac App Store

**Comment by ilya-fedin** [comment]
The preview as well as the decision of when to do preview or not is done server-side

**Comment by john-preston** [comment]
This looks like a non-initialized QImage 🤔
