### ISSUE TITLE
[Feature Request] Settings: Notifications: Badge counter: Disabling the “Count unread messages” option should automatically disable the “Include muted chats in unread count” option

### ISSUE THREAD

**Issue by kirisakow** [telegramdesktop/tdesktop#25704]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Settings > Notifications > Badge counter: 

1. Disabling the “Count unread messages” option should automatically disable the “Include muted chats in unread count” option.
2. GUI-wise, it would be more legible for the “Count unread messages” option to show above the “Include muted chats in unread count” option.

![Screenshot from 2023-01-09 18-23-00](https://user-images.githubusercontent.com/11773604/211371015-6c07e461-219b-4d21-825e-92912d35e882.png)

**Comment by kirisakow** [comment]
![Screenshot from 2023-01-09 18-23-00](https://user-images.githubusercontent.com/11773604/211371015-6c07e461-219b-4d21-825e-92912d35e882.png)

**Comment by john-preston** [comment]
Those are unrelated settings. The "count" setting is about counting separate unread messages or only chats with unread messages in the badge, the other one - if the muted chats should be included in (any of those) badges.
