### ISSUE TITLE
[Linux] Sprite is not found.

### ISSUE THREAD

**Issue by hemee** [telegramdesktop/tdesktop#2570]
### Steps to reproduce
1. Follow guide to build Telegram with gyp/cmake on Ubuntu 12.04.
2. Do the final "make".
3. Get the error.
### Expected behaviour

Compilation should end fine.
### Actual behaviour

I get this message:
`[ 11%] historywidget.h..
File not found: ../Resources/art/sprite_125x.png
make[2]: *** [obj/gen/update_dependent_qrc.timestamp] Error 1
make[1]: *** [CMakeFiles/Telegram__update_dependent_qrc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`
### Configuration

**Operating system:**
Ubuntu 12.04 armhf flavour.
**Version of Telegram Desktop:**
0.10.19
### Logs

Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by john-preston** [comment]
Does restart of make help?

**Comment by hemee** [comment]
@john-preston Nope, I did "make clean" twice, even redownload tdesktop master branch. It didn't help.

**Comment by hemee** [comment]
I can't figure out why is it happening. Everything was fine until the final build.

**Comment by john-preston** [comment]
@hemee make -j4 doesn't do as well?

**Comment by john-preston** [comment]
@hemee (there is a very rarely reproduced dependencies bug in Travis build that looks like yours error, it uses -j4 key and so do I for my builds).

**Comment by hemee** [comment]
@john-preston I always use -j4 for large builds since it dramatically reduces compilation time. Maybe you're a wizard but I tried it again... and the problem has gone. Or maybe reboot did the magic)

**Comment by hemee** [comment]
Well, it was too early to close the issue. Now I stuck with some warning message which doesn't allow compilation to proceed though.

cc1plus: warning: /home/professor/TBuild/tdesktop/out/Release/Telegram_pch/stdafx.h.gch/.c: not for GNU C++

**Comment by john-preston** [comment]
The original problem should be gone in dev branch completely: I've removed sprite generation at all.

Don't know about precompiled header problem, should work fine on gcc 4.9
