### ISSUE TITLE
[Feature Request] Changing the messages of another administrator

### ISSUE THREAD

**Issue by Nicolayka** [telegramdesktop/tdesktop#25710]
### Is your feature request related to a problem?

The administrator wrote a text and logged out of the network. Delete and write yourself - it will not be right in relation to another administrator. But if the function is enabled, then it would be possible to edit

### Describe the solution you'd like

I ask you to add functionality to change the message group of another administrator by the administrator. Naturally, to enable/disable this function in the group settings

### Describe alternatives you've considered

No

**Comment by RememberTheAir** [comment]
This should be supported by the API and should be introduced on every Telegram app - you should suggest that on https://suggestions.telegram.org

**Comment by Nicolayka** [comment]
https://bugs.telegram.org/c/23952
