### ISSUE TITLE
Broken CJK fallback font in 4.5.5 beta

### ISSUE THREAD

**Issue by Coxxs** [telegramdesktop/tdesktop#25714]
### Steps to reproduce

1. Launch Telegram Desktop 4.5.3 (or older version), take a screenshot of some CJK text (`Microsoft YaHei UI`):
![image](https://user-images.githubusercontent.com/3007303/211707367-5f5993e3-c2a5-4484-9ee9-2af454aace8b.png)

2. Launch Telegram Desktop 4.5.5 beta, take a screenshot of some CJK text (`SimSun`):
![image](https://user-images.githubusercontent.com/3007303/211707379-4cb480fd-2a6b-4d0a-b9d5-405727625146.png)

Test post link: `https://t.me/zh_CN/294`

### Expected behaviour

Should use `Microsoft YaHei UI` modern font for Simplified Chinese text.

### Actual behaviour

Fallback to `SimSun` font, which is a legacy font.

**It seems that this Qt patch didn't work in new version:**
https://github.com/desktop-app/patches/blob/master/qtbase_5_15_8/0003-fix-cjk-font-fallback.patch

### Operating system

Windows 11

### Version of Telegram Desktop

4.5.5 beta

### Installation source

Static binary from official website

**Comment by tehcneko** [comment]
This bug was supposed to be fixed by Qt6, but TDesktop is still using Qt5 for Windows 7 support 🙄

**Comment by ilya-fedin** [comment]
I doubt this is fixed in Qt 6 btw, that hardcoded CJK fallback list is still present in Qt 6
https://github.com/qt/qtbase/blob/e6693163e5e40668bc4cc5155003c173eea83273/src/gui/text/windows/qwindowsfontdatabasebase.cpp#L810-L859

**Comment by ilya-fedin** [comment]
Qt's font fallback algorithm on Windows is just:
1. System default font
2. That hardcoded fallback list
3. Try all installed font in the system in alphabetical order

Apparently it's because Windows has no public API to decide font fallback.

**Comment by Kimaru-bili** [comment]
The problem reappeared in 4.6.1 X64
