### ISSUE TITLE
Crashes when trying to search in an archived chat with topics

### ISSUE THREAD

**Issue by shevlfs** [telegramdesktop/tdesktop#25719]
### Steps to reproduce

1. Archive a chat with topics
2. Open the chat through the archive
3. Enter a topic
4. Press the search button

### Expected behaviour

A search prompt should open

### Actual behaviour

The app instantly crashes. On next startup there is a message saying that "Last time Telegram Desktop was not closed properly".

### Operating system

Windows 11, 64-bit

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by shevlfs** [comment]
Works as expected in the beta. I am not sure where to find the crash id, but I can post the next start log or the crash log, if it is still needed.

**Comment by Aokromes** [comment]
if it doesn't crashes it means it's fixed.
