### ISSUE TITLE
Transparent Video has background

### ISSUE THREAD

**Issue by Mine181** [telegramdesktop/tdesktop#25711]
### Steps to reproduce

1. Send a video with an alpha channel (done with Shutter Encoder)
2. View Video

### Expected behaviour

Video should appear with no background as it has an alpha channel, and when added as a video sticker shouldn't have background

### Actual behaviour

Video plays with white or black background, and appears with a background as a sticker

### Operating system

Windows 11 22H2

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Only webm video stickers can play video with alpha channel in Telegram, other videos are sent / received / played as non-transparent.

The webm video stickers work correctly.
