### ISSUE TITLE
[Feature Request] Option to disable showing current chat name in the window title

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25713]
### Is your feature request related to a problem?

Yes. It's distracting when you switch between chats, and you see the letters blinking at the bottom of the taskbar.

https://user-images.githubusercontent.com/39812401/211650996-1d2974bf-3e44-485e-918c-b158bb53b08e.mp4

### Describe the solution you'd like

Add at least a setting in the experimental settings to disable this feature:
https://github.com/telegramdesktop/tdesktop/commit/fc26457218d2c92202687cb8c6c8624b55c041dd

### Describe alternatives you've considered

No

**Comment by agoudbg** [comment]
And if you enable **Use system window frame** in settings > advanced the chat title will be shown in the frame title, even shows unread messages count, it's really annoying.
![image](https://user-images.githubusercontent.com/55237525/211720791-eee08ddd-e47d-4c52-9e11-4ee1a6bfb519.png)

**Comment by john-preston** [comment]
*sigh*

**Comment by john-preston** [comment]
@agoudbg Don't enable it 🤷

**Comment by agoudbg** [comment]
> @agoudbg Don't enable it 🤷

my workaround: uninstall beta verison and install 4.5.3 😒

**Comment by john-preston** [comment]
@agoudbg Beta is coming to stable anyway. I guess an option could be added for this, but I don't really get why system window frame is used, perhaps it should be moved to Experimental settings instead 🙈 Nothing is supposed to be in this corner by design, including the window title.

**Comment by agoudbg** [comment]
> @agoudbg Beta is coming to stable anyway. I guess an option could be added for this, but I don't really get why system window frame is used, perhaps it should be moved to Experimental settings instead 🙈 Nothing is supposed to be in this corner by design, including the window title.

I somehow like use system window frame, I have no idea about it 🤣 this version also breaks Chinese font so I rollback

**Comment by john-preston** [comment]
@agoudbg Chinese font will be fixed in the upcoming beta (later today, I hope).

**Comment by agoudbg** [comment]
@john-preston good news, thanks 👍

**Comment by Neurotoxin001** [comment]
Btw when I open comments (for example https://t.me/ru2ch_news/66102) I see (315) count near channel name:
![image](https://user-images.githubusercontent.com/39812401/212060298-d458bd9a-d8a7-44f1-91b7-3b3cd4c78d56.png)

But there is only 41 comments:
![image](https://user-images.githubusercontent.com/39812401/212060326-873c4c5e-eb83-4525-b917-45c9ef153cd5.png)

**Comment by Neurotoxin001** [comment]
Fixed https://github.com/telegramdesktop/tdesktop/commit/94b489835c24a387a31c71be01d5e9a652304c6b

![image](https://user-images.githubusercontent.com/39812401/216752287-6a7515e1-2da6-41cb-a624-4d126d8dd966.png)

**Comment by Neurotoxin001** [comment]
Btw "Total unread count" seems like not working, because I still see (number of messages) in tray even if I disable it:

![image](https://user-images.githubusercontent.com/39812401/216752377-62e0cb9e-9c19-4120-a84c-053e1f62742a.png)

**Comment by john-preston** [comment]
@Neurotoxin001 Unread count in the exact chat is always added, if it's name is added. Total count is the one for all chats (all accounts?) in the end of the title.
