### ISSUE TITLE
Bug while displaying languages

### ISSUE THREAD

**Issue by Super-Baleine** [telegramdesktop/tdesktop#2572]
Hey, look, I have an useless point here : 

![capture du 2016-10-26 04 30 26](https://cloud.githubusercontent.com/assets/13090164/19711263/bfecabe0-9b34-11e6-8b5f-d0346854076b.png)

Under "Portugues".

**Comment by john-preston** [comment]
It is Korean and it seems it is not displayed :( Perhaps it is a font issue. It should be:

한국어

What is displayed in a message if you send a message with such text in Telegram Desktop?

**Comment by Super-Baleine** [comment]
![capture du 2016-10-26 15 29 47](https://cloud.githubusercontent.com/assets/13090164/19727718/dec51fd2-9b90-11e6-9041-0af226bf6978.png)

Okay, no it will be difficult to reset it to french xD

**Comment by Kondra007** [comment]
@Super-Baleine hover mouse 1 cm above 0.10,19 and move right 1-2 cm before right edge. You'll notice cursor change to "Finger". That's "Change language"

**Comment by Super-Baleine** [comment]
@Kondra007 xDDD

I found it, dont worry x)

**Comment by Super-Baleine** [comment]
Should we close this issue so ?

**Comment by Aokromes** [comment]
Strange, for me is show properly on windows 10, what os you use?
http://i.imgur.com/yXti0aN.png

**Comment by Super-Baleine** [comment]
I'm on Debian Jessie (GUI : LXDE) x)

**Comment by Aokromes** [comment]
Indeed, i confirm the bug exists on Debian 8.

**Comment by Super-Baleine** [comment]
Ah, u2 ?

**Comment by Aokromes** [comment]
Still present on 1.0

**Comment by Super-Baleine** [comment]
I approve

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3363 ?

**Comment by Super-Baleine** [comment]
Yea. Still the same, take a look:

![capture du 2018-01-07 13-33-12](https://user-images.githubusercontent.com/13090164/34649425-53eac54c-f3af-11e7-9d78-9495d7d33937.png)

**Comment by Aokromes** [comment]
Still present on 1.3 and debian 9
https://i.imgur.com/8cZG2XE.png

**Comment by Aokromes** [comment]
btw, i just checked on ubuntu 18.04 and works.

**Comment by Super-Baleine** [comment]
good job guys

**Comment by ilya-fedin** [comment]
Is this actual?

**Comment by Aokromes** [comment]
still broken on 2.1.5 and debian 10.
https://i.imgur.com/mGGWeJU.png

**Comment by ilya-fedin** [comment]
> still broken on 2.1.5 and debian 10.

You probably doesn't have korean fonts, since you're not a korean user. Just install fonts-noto-cjk and it should work.

**Comment by Aokromes** [comment]
yup, indeed it's that.
