### ISSUE TITLE
Unable to select export folder

### ISSUE THREAD

**Issue by Yamimono** [telegramdesktop/tdesktop#25720]
### Steps to reproduce

1. Go to any chat.
2. Open the chat history export window.
3. Attempt changing target directory.

### Expected behaviour

Choosing or changing export folder should let us browse the folders to choose a target folder.

### Actual behaviour

Choosing or changing export folder results in an app crash.

### Operating system

Applicable to Windows 11 & Ubuntu 22.10, not tested on macOS yet

### Version of Telegram Desktop

4.5.5

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Thanks!
