### ISSUE TITLE
c77f07239fe5c134824fc869481bfe35c513262e broke wrapper scripts around telegram

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#25727]
### Steps to reproduce

I use a wrapper script around telegram to set its desktop environment and work around some quirks.

I place my script in $PATH with a higher precedence that `/usr/bin/telegram-desktop`, and have the script call the real binary. This is a common technique for "wrapping" executables, and also used by sandboxing mechanisms like `firejail`.

Since c77f07239fe5c134824fc869481bfe35c513262e this broke, because the desktop file hardcodes the absolute path to the binary. Usually, desktop files shouldn't use absolute paths for executables that are expected to be in $PATH.

### Expected behaviour

Path should not be hardcoded; administrator-local or user-local wrappers with the same name should work.

### Actual behaviour

The path of the desktop file is hardcoded and can only be changed by changing a package-owned file (which implies that it will be reverted on the next package update).

### Operating system

Linux 6.1.3-0-edge x86_64 Linux

### Version of Telegram Desktop

4.5.3

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Sorry, but it will be hardcoded :(
If you don't like that, you have to do your own build of tdesktop.

**Comment by WhyNotHugo** [comment]
Out of curiosity (and also wondering if there might be another solution), what purpose does it serve to hardcode the full path?

**Comment by ilya-fedin** [comment]
It's explained in the commit message: it matches URL scheme handler installation code expectations

**Comment by WhyNotHugo** [comment]
"URL scheme handler installation"?

Putting the desktop file in the right place should be sufficient for firefox to pick it up as a handle for `tg://` links. This has works for years.

**Comment by ilya-fedin** [comment]
Well, the base XDG libraries (in face of glib) provide API to generate handlers on the fly, perfectly matching tdesktop cross-platform behavior. This also works, for years.

**Comment by ilya-fedin** [comment]
> What do you mean "generate handlers"? What handler do you need to generate?

.desktop file generated on the fly with random name. That's how tdesktop manages URL scheme handler registration for years. This allows to follow the cross-platform behavior of generating the handler for each set of arguments (currently only -workdir).

> If this has worked for years, why the need for this change on Nov 28, 2022?

Has it? There were various complains from people who don't like tdesktop generates .desktop files for URL scheme handler registration. Now tdesktop got the code to detect whether -workdir is passed or not thanks to snap autostart refactoring and -workdir is no longer set in URL scheme handler if it was launched without the argument. After that, the lack of the path to binary was the latest difference with the expected command line pass to URL scheme handler registration code, leading to creating of new files. So they're not creating now unless you pass -workdir.

**Comment by WhyNotHugo** [comment]
You don't need to create new entries to register URL handlers. The existing one should work.

Where is this "URL scheme handler registration code" coming from? It sounds like it needs to be patched to avoid creating explicate entries with random names.

I really would prefer to avoid doing my own builds of Telegram Desktop for such trivial things (or having to install weird package hooks), so I really want to understand the issue in order to figure out an alternative way to fix it -- one that doesn't involve hardcoding paths, because hardcoding paths like this breaks wrapper scripts (including sandboxing ones).

**Comment by ilya-fedin** [comment]
> You don't need to create new entries to register URL handlers. The existing one should work.

We need this to ensure instances with custom workdirs register handlers for them, not for the main instance.

> Where is this "URL scheme handler registration code" coming from? It sounds like it needs to be patched to avoid creating explicate entries with random names.

This would be an API break. The API is supposed to create the handler with the passed arguments. If you will remove that logic, it won't respect the supposed API guarantees anymore. https://github.com/desktop-app/lib_base/blob/master/base/platform/linux/base_url_scheme_linux.cpp

> I really would prefer to avoid doing my own builds of Telegram Desktop for such trivial things (or having to install weird package hooks), so I really want to understand the issue in order to figure out an alternative way to fix it -- one that doesn't involve hardcoding paths, because hardcoding paths like this breaks wrapper scripts (including sandboxing ones).

A lot of projects use hardcoded paths (e.g. VLC, Spectacle). If this is a problem for you then I believe you should find a different solution than begging every upstream with this. I also heard having hardcoded paths is a good practice from security perspective of view.
