### ISSUE TITLE
Privacy & Security > Privacy > Groups & Channels > Who can add me to group chats?

### ISSUE THREAD

**Issue by CodingFA** [telegramdesktop/tdesktop#25729]
### Is your feature request related to a problem?

I think a **Nobody option** needs to be added in this section:

Privacy & Security > Privacy > Groups & Channels > Who can add me to group chats?

### Describe the solution you'd like

If we select the **My Contacts** option and then select the **Never Allow** option for all users from the bottom of the **Add Exceptions** section, we have to check each one and there is no option to select all on this page.

### Describe alternatives you've considered

Add **Check All** option in the section
Never Allow > Add Users

**Comment by RememberTheAir** [comment]
Currently not supported by the API, you should suggest that on https://suggestions.telegram.org
