### ISSUE TITLE
[Feature Request] Reactions UX overhaul 

### ISSUE THREAD

**Issue by Kardzhilov** [telegramdesktop/tdesktop#25721]
### Is your feature request related to a problem?

The reactions UX on the desktop client is outdated. There are too many reactions to navigate, scrolling up and down in a single column. You often end up scrolling past the one you are looking for.
![image](https://user-images.githubusercontent.com/15326512/212058120-31c21d8d-c2ea-4b74-aacc-1e33d9845899.png)

### Describe the solution you'd like

A copy of the Android reactions UX, or something very similar, is needed. 
There it is a list of the 7 most used reactions. You can expand the list to an 8x7 grid of reaction options (on my device, at least). Additionally, a search feature for reactions would be nice as the list keeps expanding, and finding the right one will just get harder, especially if you have premium.

### Describe alternatives you've considered

There are none. As it is, paying for premium makes no sense if you want to use the premium reactions on desktop.

**Comment by john-preston** [comment]
But the UI similar to Android is there already, in right click menu:

![image](https://user-images.githubusercontent.com/17900494/212063517-da04e926-c742-43d6-9cb4-b98dfe5b2606.png)

**Comment by Kardzhilov** [comment]
> But the UI similar to Android is there already, in right click menu:
> 
> ![image](https://user-images.githubusercontent.com/17900494/212063517-da04e926-c742-43d6-9cb4-b98dfe5b2606.png)

Somehow i missed that feature getting added, thanks!

**Comment by john-preston** [comment]
You can disable the old menu in Settings if it gets in your way. Or you can leave it for a quick leaving of one of default / recent reactions or very-quick leaving of your favorite reaction.
