### ISSUE TITLE
Regression in multi-display setup

### ISSUE THREAD

**Issue by yurikoles** [telegramdesktop/tdesktop#25726]
### Steps to reproduce

1. Have 2 displays with different fractional system scale.
2. Set larger display as main.
3. Launch Telegram, it appears on main display with higher DPI.
4. Optional, second case: set scale to smaller value while you are still on larger display.
5. Move it to second smaller display.

### Expected behaviour

Telegram should be usable on a second, smaller display. Ideally, the app should auto-adjust scale according to display DPI.

### Actual behaviour

In fact, with default scale, the app has a crazy huge scale on a smaller display, which renders it unusable, because most of the UI is behind screen.

Setting scale to a smaller value, e.g. 120-130, which is comfortable for a smaller display, makes UI very small on the main display. But it at least worked until the recent beta update. Now this scenario is broken, after moving the app to a second, smaller display, hamburger menu items and chat folders isn't clickable.

### Operating system

Windows 11

### Version of Telegram Desktop

4.5.6

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
So, did anything change visually in the latest beta or just clicking stopped working, but visually (the interface scale after changing the monitor) works the same as before the latest beta?

**Comment by yurikoles** [comment]
Yes, UI situation is the same, it either small on a larger display, or large on a smaller one. But now clicks are broken after a move to a smaller display.

**Comment by john-preston** [comment]
Also, can you try in Settings > Advanced > Experimental Settings to enable "Enable precise High DPI scaling"? With it enabled, it should:

1. Work slower :( (because of downscaling / upscaling of all the graphics to fractional scale values)
2. Has visual glitches in graphics (because of the same downscaling / upscaling of graphics and images)

But it should follow the screen scale precisely.

Strange thing that it didn't change visually, because it should've started switching to the closes possible non-fractional scale when changing the screen (like, 100%, 200% or 300%). Instead it looks like it started applying the changes to the input, but not to the visual part, which is weird.

**Comment by john-preston** [comment]
It works correctly for me when I change screen scaling within a single screen :( Dragging the window between screens with different scale factors should do the same.

**Comment by yurikoles** [comment]
Nothing has changed with that setting.

**Comment by john-preston** [comment]
Can you please provide which interface scales do your screens have in Windows Settings? Like, one with 125%, another 225%.

**Comment by john-preston** [comment]
I think I can reproduce that.

**Comment by yurikoles** [comment]
> one with 125%, another 225%.

Do you read my mind? Exactly these settings. Larger one "27 4K has 225%, smaller one "24 1080p has 125%.

**Comment by john-preston** [comment]
@yurikoles I've found a problem, it should be much better in the next beta.

**Comment by yurikoles** [comment]
Thank you, that was superfast.

**Comment by john-preston** [comment]
@yurikoles Yeah, the app doesn't really track the scale after launch, as if it doesn't change, and Qt changes the multiplier under the hood (1x, 2x, 3x).

**Comment by yurikoles** [comment]
I'm reporting here a regression I faced in recent betas on my custom display setup, because it seems to be related.

Latest message from me have glitches if any custom per chat theme is enabled, but only on a smaller display.
![Знімок екрана 2023-01-20 210224](https://user-images.githubusercontent.com/922873/213788787-648c09cb-39a5-49c7-9c5a-58567e17faf6.png)

**Comment by john-preston** [comment]
@yurikoles Can you write the interface scales used on both displays? And in app settings.

**Comment by john-preston** [comment]
@yurikoles And log.txt from such launch.

**Comment by yurikoles** [comment]
> I'm reporting here a regression I faced in recent betas on my custom display setup, because it seems to be related.
> 
> Latest message from me have glitches if any custom per chat theme is enabled, but only on a smaller display. ![Знімок екрана 2023-01-20 210224](https://user-images.githubusercontent.com/922873/213788787-648c09cb-39a5-49c7-9c5a-58567e17faf6.png)

I can't no longer reproduce this, maybe because TG now starts first on a smaller display. I'll file a new issue if it occurs again.
