### ISSUE TITLE
[Feature Request] Show exact reaction on message instead of hearth

### ISSUE THREAD

**Issue by Alirezaaraby** [telegramdesktop/tdesktop#25734]
### Is your feature request related to a problem?

The preview chat shows the latest message on your chat and shows a badge like ♥ on the right side of it. it's better to show the latest exact reaction to each message. or show multiple badges.

### Describe the solution you'd like

the solution is to replace the ♥ badge with the exact latest reaction to each message.

### Describe alternatives you've considered

show the exact reaction on the message preview instead of ♥ like the below message.
![image](https://user-images.githubusercontent.com/45128978/212495664-42d19148-dfa1-45d6-8f78-d888a71cbb2d.png)
message

**Comment by 23rd** [comment]
https://bugs.telegram.org/c/14723
