### ISSUE TITLE
Can't suggest profile photo to user that not added me to contacts

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25739]
### Steps to reproduce

1. Add user to contacts.
2. You should not be in this user contacts
3. Click on user photo
4. There is no "suggest profile photo" button

TDesktop, user has not added me to his contacts:
https://user-images.githubusercontent.com/39812401/212612775-bdecf2f0-52a9-48da-bc7b-9c389f6f466a.png

TDesktop, user added me to his contacts, without sharing a phonenumber:
https://user-images.githubusercontent.com/39812401/212612790-a42b6dd8-d468-4937-839a-eb1939b72325.png

iOS:
https://user-images.githubusercontent.com/39812401/212612714-3a48f3e7-5f9f-4ac9-94a9-a355761f368c.png

### Expected behaviour

The "suggest profile photo" button should be present even if the user has not added you to his contacts. On iOS I have this button for these users.

### Actual behaviour

There is no "suggest profile photo" button if the user has not added you to his contacts (even without "share my phone number" checkbox)

### Operating system

Windows 10

### Version of Telegram Desktop

4.5.7 beta

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
`+`

**Comment by john-preston** [comment]
@Neurotoxin001 in code it says that server allows suggesting photos in non-empty chats, unrelated to contact status. Does it happen that way?

**Comment by Neurotoxin001** [comment]
Checked it right now. Button "suggest profile photo" appears only if my contact write me some message, even if he don't add me to contacts we don't share our phone numbers. So it's not a bug?

**Comment by Neurotoxin001** [comment]
But on iOS "suggest profile photo" button available even with contacts that I don't have any messages

**Comment by john-preston** [comment]
@Neurotoxin001 Does it work though? Can the photo suggestion be the all-time-first message in a chat with a guy?

**Comment by Neurotoxin001** [comment]
> Does it work though? Can the photo suggestion be the all-time-first message in a chat with a guy?

No…

https://github.com/telegramdesktop/tdesktop/assets/39812401/556cf467-1af7-4225-b0e7-fad5e0df646e

**Comment by john-preston** [comment]
@Neurotoxin001 Well, then you can close the issue and report it to iOS app =)
