### ISSUE TITLE
Crashes on Ubuntu 22.04 when trying to share screen.

### ISSUE THREAD

**Issue by jotterkain** [telegramdesktop/tdesktop#25738]
### Steps to reproduce

1. Run telegram
2. start a call
3. try to share screen

### Expected behaviour

We are supposed to be able to share screen

### Actual behaviour

The application crashes when i try to share screen

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.5.3

### Installation source

Snap

### Logs

`[E] pw.loop [loop.c:86 pw_loop_new()] 0x7f5d66725690: can't make support.system handle: No such file or directory
Segmentation fault (core dumped)
`

**Comment by ilya-fedin** [comment]
Sadly, snap doesn't provide infrastructure to debug crashes, so you should migrate to the build from https://desktop.telegram.org

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25525
