### ISSUE TITLE
[UX] Incoherent naming of "cloud password" vs "password" vs "Two-Step Verification"

### ISSUE THREAD

**Issue by dreua** [telegramdesktop/tdesktop#25735]
### Steps to reproduce

I believe this is all meaning the same password, but I see different names for it:

1. Telegram Desktop asks for a "Cloud Password"
2. The Android App calls it just "Password" but usually in context with "Two-Step verification".
3. The "Telegram" service Account informs me that my "Two-Step Verification password" has been changed.

It's kind of confusing to have 3 different terms for the same password, actually I was worried that it might refer to different passwords.

### Expected behaviour

Settle on one term and use it consistently.

### Operating system

Fedora Linux 37

### Version of Telegram Desktop

4.4.1

### Installation source

Other (unofficial) source

**Comment by dreua** [comment]
This issue got three upvotes so at least 4 people do care about it. I'm happy to deliver more information or engange in discussion but all you do is send a bloody bot to sweep it under the rug. :disappointed:

**Comment by Aokromes** [comment]
i think this is more localizations project thing than telegram desktop.

**Comment by dreua** [comment]
Can you move this issue to this "localizations project" or at least tell me where to find it?

**Comment by john-preston** [comment]
Well, this is about more than just TDesktop, so you can create a report on https://bugs.telegram.org with some suggestions. Although I'm not sure anything would be changed, I guess it is considered fine at the moment.
