### ISSUE TITLE
[Feature Request] [Folders] Allow to change the position of folders in the window

### ISSUE THREAD

**Issue by Nelonn** [telegramdesktop/tdesktop#25732]
### Is your feature request related to a problem?

I use a small window, similar in size to the phone screen, when there are 1 or more folders, the window becomes too wide and not convenient

### Describe the solution you'd like

You need to add a choice of folder positions in the window, from the top (as in telegram android) or according to the standard on the left

### Describe alternatives you've considered

Folders at the bottom, an exotic idea

### Additional context

![Default](https://user-images.githubusercontent.com/42481486/212476547-881e0765-bbcc-4ad3-8fae-2190fffe7c60.png)
![With Folders](https://user-images.githubusercontent.com/42481486/212476548-47fb47c8-9dac-454c-ae68-c1e4db6da874.png)

**Comment by 23rd** [comment]
Guess it can be closed?

**Comment by Nelonn** [comment]
Yeah, I am very glad that this feature has appeared
