### ISSUE TITLE
[Feature Request] Enable notification on specific time

### ISSUE THREAD

**Issue by Alirezaaraby** [telegramdesktop/tdesktop#25730]
### Is your feature request related to a problem?

Sometimes, users don't want to receive the desktop notification, so it's better to have a feature to toggle it at a specific time of day.

### Describe the solution you'd like

toggle desktop notifications at specific times. for example, turn it on just for 2 P.M. to 4 P.M.

### Describe alternatives you've considered

On `settings`>` Notifications and Sounds` add an option to set the allowed time for desktop notifications

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/151#issuecomment-63627345
