### ISSUE TITLE
Notification  doesn't work

### ISSUE THREAD

**Issue by Partizanin** [telegramdesktop/tdesktop#25748]
### Steps to reproduce

Update to beta 4.5.7 x64

### Expected behaviour

Show notification form 

### Actual behaviour

Notification form doesn't appear

### Operating system

Windows 10 Pro 21H2 19044.2251

### Version of Telegram Desktop

4.5.7 beta x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by Partizanin** [comment]
> works for me (TM) https://i.imgur.com/QAcOhhq.png

What version do you have?

**Comment by Aokromes** [comment]
4.5.7 on windows 10 22h2.

**Comment by SmokeyOdin** [comment]
I'm having the same issue, not getting any notifications from contacts when they message, I'm using the non MS-Store version of the app 4.5.7 beta.

Just downloaded the MS-Store version to see if I get notifications from that (version 4.5.3)

**Comment by rumartcer** [comment]
I figured out how to reproduce it. Notifications stops working due to Windows scale in System settings. If I select scale 175% and higher - notifications stop working. Workaround: select top left corner of the screen for telegram notifications.

Windows 11 22H2 22621.1105
Telegram 4.5.8 beta x64 (static binary from official website)

**Comment by Partizanin** [comment]
> I figured out how to reproduce it. Notifications stops working due to Windows scale in System settings. If I select scale 175% and higher - notifications stop working. Workaround: select top left corner of the screen for telegram notifications.
> 
> Windows 11 22H2 22621.1105 Telegram 4.5.8 beta x64 (static binary from official website)

4.5.8 still not work

**Comment by Partizanin** [comment]
fixed in  [v4.6.0](https://github.com/telegramdesktop/tdesktop/releases/tag/v4.6.0)
