### ISSUE TITLE
Worse sound quality when speeding up voice messages or videos

### ISSUE THREAD

**Issue by mrodal** [telegramdesktop/tdesktop#25743]
### Steps to reproduce

1. Listen to a video or voice message at 1x
2. Listen at different speed. On videos you can set 1.05 or 0.95 to quality difference with almost same speed
3. Do the same on telegram web for example, there the quality is maintained across playback speeds 

### Expected behaviour

Sound quality should be the same across playback speeds

### Actual behaviour

Sound quality feels worse when playback speed != 1x

### Operating system

Windows 10

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop uses openal-soft library to speed up sound, if you don't like how it speeds up, feel free to complain to openal-soft developers
