### ISSUE TITLE
Pressing "Back" when reading a discussion without joining the channel returns the latest post instead of the current one

### ISSUE THREAD

**Issue by testtest123333** [telegramdesktop/tdesktop#25747]
### Steps to reproduce

Pressing "Back" when reading a discussion in a channel without joining the channel always sends you to the latest post in the channel instead of the current one.

1. Open a random channel, don't join the channel
2. Scroll to older posts and view comments on some post
3. Press "Back" button

### Expected behaviour

Returning to the post to which you just read the comments

### Actual behaviour

Returns the latest message in the channel

### Operating system

Windows 10 22H2

### Version of Telegram Desktop

4.5.7 (Beta)

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@testtest123333 Which Back button? The software arrow button in the top of the chat view? Or some sort of hardware mouse or keyboard Back button?

**Comment by testtest123333** [comment]
> @testtest123333 Which Back button? The software arrow button in the top of the chat view? Or some sort of hardware mouse or keyboard Back button?

All of the above. Pressing "Esc" on the keyboard also results in the same behavior as with the software arrow button; same with mouse if assign "Esc" to a key and click.

**Comment by testtest123333** [comment]
Fixed in 4.6.0
