### ISSUE TITLE
Dumped Core Module linux-vdso.so.1 

### ISSUE THREAD

**Issue by stnert** [telegramdesktop/tdesktop#25749]
### Steps to reproduce

1. Generally this never happens, being on NixOS (the operating system I use, in the stable version). 
 
2. The crash occurred just now, and forced the client to shut down.

3. The GNOME log captured the moment of the bug 

### Expected behaviour

After the forced closure, the customer is operating normally. Just reporting and wanting to understand if the bug was the client. 

### Actual behaviour

Running normally, apparently 

### Operating system

NixOS 22.11 Stable

### Version of Telegram Desktop

4.3.1

### Installation source

Static binary from official website

### Logs

```shell
16:12:19 systemd-coredum: Process 2925 (.telegram-deskt) of user 1000 dumped core.

Module linux-vdso.so.1 with build-id 6788e83a9d8f58b16a787799bd801313b1727684
Module im-wayland.so with build-id 269c4a2ba8bbac7a6927242be70724c1ae5685a5
```

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.
