### ISSUE TITLE
[Web Apps] No reaction on viewport_changed and theme_changed events.

### ISSUE THREAD

**Issue by heyqbnk** [telegramdesktop/tdesktop#25752]
### Steps to reproduce

1. Open [Web Apps polygon bot](https://t.me/webapps_polygon_bot) ([source code](https://github.com/Telegram-Web-Apps/bridge-polygon))
2. Open developers tools (F12)
3. Call Web Apps methods:
```typescript
bridge.postEvent('web_app_request_viewport');
bridge.postEvent('web_app_request_theme);
```
4. See no received events in console.

### Expected behaviour

According to official [documentation](https://core.telegram.org/api/web-events#web-app-request-viewport) of these methods, they should return current state of connected entities - theme and viewport. In other words, Telegram desktop application should emit `viewport_changed` and `theme_changed` events.

### Actual behaviour

Telegram Desktop application does not emit `viewport_changed` and `theme_changed` events.

### Operating system

Windows 10 Pro

### Version of Telegram Desktop

Version 4.5.7 beta x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@heyqbnk Thanks, I've found a bug with web_app_request_theme request. I didn't handle web_app_request_viewport, because the viewport never changes on desktop. I think I'll provide the viewport data right from the JS.
