### ISSUE TITLE
Some videos don't play on macOS (mainly .MOV)

### ISSUE THREAD

**Issue by Brawl345** [telegramdesktop/tdesktop#25754]
### Steps to reproduce

1. Make a screen recording on macOS with Command + Shift + 5
2. Send it in Telegram (it's a MOV file)
3. Play it

### Expected behaviour

Video file should play normally.

### Actual behaviour

Playback stops after a second or two. If the video is too small, it will be sent as a "GIF" but the bug is the same (the GIF does not play "inline" but is enlarged like a normal video and playback stops).

Here is a sample file: https://t.me/fuoehfowejfowef/2

Original file here: https://user-images.githubusercontent.com/5049892/213549374-6d208814-6845-42ce-afa6-6e1db86104ff.mov

(related issue: https://github.com/telegramdesktop/tdesktop/issues/24381)

### Operating system

macOS 13.1 Ventura

### Version of Telegram Desktop

v4.5.6 Beta

### Installation source

Static binary from official website

### Logs

```shell
[2023.01.19 21:09:04] Streaming Error: Error in avcodec_send_packet (code: -1313558101, text: Unknown error occurred).
```

**Comment by Thoufak** [comment]
I'm using tdesktop on MacOS and having a problem which produces the same logs:
[2023.02.21 21:33:39] Streaming Error: Error in avcodec_send_packet (code: -1313558101, text: Unknown error occurred).

For me, a lot of videos won't start playing. I open them, but it never plays even a single frame. Pressing the play button doesn't help. I've been having this issue for months.

**Comment by john-preston** [comment]
@Thoufak I hope it'll be fixed in the next update where I'll use the new version of ffmpeg.

**Comment by Brawl345** [comment]
Latest update (v4.6.5) fixed it for me, thanks!
