### ISSUE TITLE
No tray icon when starting Plasma

### ISSUE THREAD

**Issue by simonbcn** [telegramdesktop/tdesktop#25751]
### Steps to reproduce

I have enabled "_Open Telegram when system starts_" and "_Open minimized_". 
But when I enter my desktop (KDE Plasma) there is no tray icon for Telegram although it is running in the background.
Also if I open Telegram (on startup) using the KDE menu and close it, the application terminates. 
It only works fine if I open the application manually from the menu (without using the startup option).

### Expected behaviour

It should show the icon in the notification bar.

### Actual behaviour

It should NOT show the icon in the notification bar.

### Operating system

Arch Linux

### Version of Telegram Desktop

4.5.6

### Installation source

Static binary from official website

### Logs

```shell
Operating System: Arch Linux
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 6.1.7-native_amd-xanmod1-1 (64-bit)
Graphics Platform: Wayland
Processors: 64 × AMD Ryzen Threadripper 3970X 32-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series
Manufacturer: ASUS
```

**Comment by simonbcn** [comment]
It works well if I add a delay to desktop file:
```
$ cat .config/autostart/org.telegram.desktop.desktop
[Desktop Entry]
Actions=Quit;
Categories=Chat;Network;InstantMessaging;Qt;
Comment[es_ES]=Official desktop version of Telegram messaging app
Comment=Official desktop version of Telegram messaging app
Exec=sh -c "sleep 10 && /usr/bin/telegram-desktop -autostart"
GenericName[es_ES]=
GenericName=
Icon=telegram
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
MimeType=
Name[es_ES]=Telegram Desktop
Name=Telegram Desktop
Path=
SingleMainWindow=true
StartupNotify=true
StartupWMClass=TelegramDesktop
Terminal=true
TerminalOptions=
Type=Application
X-GNOME-SingleWindow=true
X-GNOME-UsesNotifications=true
X-KDE-SubstituteUID=false
X-KDE-Username=
```

**Comment by ilya-fedin** [comment]
#25126
