### ISSUE TITLE
[BUG] The PopUp Window Will Break Telegram.

### ISSUE THREAD

**Issue by The-0Day** [telegramdesktop/tdesktop#25766]
### Steps to reproduce

1. Open Telegram Desktop
2. Select a Chat
3. Just Play A Video
4. Click On The PopUp Option  

![image](https://user-images.githubusercontent.com/76570757/213868377-a9c5ef32-0d8d-4eca-ac71-06fa20b54362.png)

### Expected behaviour

When You Click On The PopUp Option, It Should Give You Two Windows, You Should Have The Video Inside Of the Chats.

### Actual behaviour

The Current Behaviour Is When You Click On The PopUp Option, Telegram Will Freeze And You Should Stop It, Like Trying To Open A Terminal And Kill Telegram's Process: ```kill -9 $(pidof telegram-desktop 1 )```

### Operating system

Linux arch 6.0.9-zen1-1-zen

### Version of Telegram Desktop

Telegram Desktop - Version 4.5.3

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by john-preston** [comment]
@The-0Day Please try the version from https://desktop.telegram.orf

**Comment by cdarken** [comment]
I have the same error with the `community/telegram-desktop` package from the repositories. The crash doesn't happen with the official package that you linked.
