### ISSUE TITLE
Not taken directly into conversation

### ISSUE THREAD

**Issue by nighthawk469** [telegramdesktop/tdesktop#2576]
Since update 0.10.19 for macOS

If I am chatting to someone in telegram, and then close the window the application will still be running in the background, which is normal. 

But when I open telegram again the view that is displayed is an unfocused homepage so that I have to select who I want to talk to, instead of previously where I would be taken to the last conversation I was.

This is annoying for rapid conversations.

**Comment by yashpalgoyal1304** [comment]
@auchri duplicate of what???

**Comment by nighthawk469** [comment]
@yashpalgoyal1304 https://github.com/telegramdesktop/tdesktop/issues/2541
