### ISSUE TITLE
[Web Apps] "popup_closed" event contains incorrect payload

### ISSUE THREAD

**Issue by heyqbnk** [telegramdesktop/tdesktop#25767]
### Steps to reproduce

1. Open [Web Apps polygon bot](https://t.me/webapps_polygon_bot) ([source code](https://github.com/Telegram-Web-Apps/bridge-polygon))
2. Open developers tools (F12)
3. Call Web Apps method:
```typescript
bridge.postEvent('web_app_open_popup', {
    title: 'Title',
    message: 'Message',
    buttons: [{type: 'ok', id: 'ok'}]
})
```
4. Close popup by clicking outside or by clicking popup top right cross
5. See log in console:
```
[...] [Bridge] [processEvent] popup_closed undefined
```
It means, application received event `popup_closed` with payload presented as `undefined`.

### Expected behaviour

According to official `popup_closed` [documentation](https://core.telegram.org/api/bots/webapps#popup-closed), in case no button was clicked, we should receive empty object (`{}`), but not `undefined`.

### Actual behaviour

Telegram Desktop application sends `undefined` in event payload.

### Operating system

Windows 10 Pro

### Version of Telegram Desktop

Version 4.5.7 beta x64

### Installation source

Static binary from official website

**Comment by heyqbnk** [comment]
There is some strange magic with `web_app_open_popup` too. As I noticed, in case, when you call this method 3 times in a row during about 2 or 3 seconds, the next calls of `web_app_open_popup` will not work for several seconds. Instead of this, you will instantly receive event stating, that user closed popup by clicking outside.

**Comment by john-preston** [comment]
@heyqbnk There is a flood control for the popup windows so that the app won't stop the user from closing the web app.
