### ISSUE TITLE
[Bug] It's possible to gift premium to official telegram account, it shouldn't be possible

### ISSUE THREAD

**Issue by bob27aggiustatutto** [telegramdesktop/tdesktop#25763]
### Steps to reproduce

1. Go to some official account, like https://t.me/TelegramAuditions
2. Click to "Gift premium"

### Expected behaviour

An error message shows up

### Actual behaviour

Popup shows up

![immagine](https://user-images.githubusercontent.com/120955097/213865910-c143b67e-7d32-474c-8cf2-04da3294c995.png)

### Operating system

Win 10

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by vonDubenshire** [comment]
Is this a Telegram desktop bug or should this be reported to https://bugs.telegram.org/ ?

I notice a difference in the account you picked and something like the normal Telegram or TG Premium accounts (are those bots?)

![Screenshot_20230126-164141](https://user-images.githubusercontent.com/40748193/214967876-9f9f82b0-1f32-4fc7-b1a5-a777609bc3c7.png)![Screenshot_20230126-164407](https://user-images.githubusercontent.com/40748193/214967877-8eea6bf7-f265-42a7-97db-1e4bd27bc451.png)

This TG account is a full-fledged user with a phone number. Although the user account has Premium already, it can still be gifted like any other user by giving extra\MORE Premium pre-paid.

![image](https://user-images.githubusercontent.com/40748193/214968060-12daf441-2918-4409-9f7d-48693617349c.png)
