### ISSUE TITLE
Drag and Drop file to chat "is empty and can't be sent."

### ISSUE THREAD

**Issue by DevDorrejo** [telegramdesktop/tdesktop#25779]
### Steps to reproduce

1. Open a Chat/Group in Telegram Desktop App.
2. Open File Explorer.
3. Drag a file from the File Explorer to the Chat/Group in the Telegram Desktop App.
4. Drop the file.
5. It will pop-up a banner saying: "File: Path_to_file is empty and can't be sent."

### Expected behaviour

Attach file to send it.

### Actual behaviour

only appear a pop up, saying is a empty file and can't be sent.

### Operating system

openSUSE, Tumbleweed, KDE Plasma 5.26.5

### Version of Telegram Desktop

4.5.3

### Installation source

Flatpak

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by ilya-fedin** [comment]
That means the application you're copying from doesn't support copying to sandboxed applications through the [FileTransfer protocol](https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.portal.FileTransfer.xml). You need to either create a feature request to that application and avoid DnDing from it until implemented or install tdesktop unsandboxed.

**Comment by Deemon47** [comment]
@DevDorrejo Hello, I had same issue with flatpak version. I downloaded version from telegram site and now drag and drop works fine
