### ISSUE TITLE
Right click on systray icon shows main window

### ISSUE THREAD

**Issue by TJL73** [telegramdesktop/tdesktop#25778]
### Steps to reproduce

Close or minimize Telegram main window.
Right click on the systray icon.

### Expected behaviour

Should appear context menu, but not main window (at least until the "Open" item is selected) or icon is left clicked.

### Actual behaviour

Main window appears but context menu shows item "Open Telegram" (but it is already been opened by right click).
Right clicking on systray icon, the main window should not be shown.

### Operating system

Microsoft Windows v10.0.19045.2486

### Version of Telegram Desktop

Version 4.5.8 beta x64

### Installation source

Static binary from official website

**Comment by cvertee** [comment]
same

**Comment by cgabba** [comment]
Same here...
Windows 11 22H - 22621.1105
4.5.8 beta x64
