### ISSUE TITLE
Preparing libs before building failed on msys64

### ISSUE THREAD

**Issue by AndreyDaniluk** [telegramdesktop/tdesktop#25771]
### Steps to reproduce

1. Prepare folders
2. Download repository
3. Prepare libs [error]

### Expected behaviour

End preparing without errors?

### Actual behaviour

When i try to prepare project, i get error and after this variable %path% don't work until restart Native Tools
![image](https://user-images.githubusercontent.com/89187230/213943555-76476ad6-1fe3-4b3d-8230-4036e7aa3b3d.png)

### Operating system

Windows Server 2012 R2

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I have two guesses
1. Windows Server 2012 is too old and you need Windows 10 (I don't know which exactly one, probably not one of the first versions) at least
2. You've customized your system and disabled some service, so powershell doesn't work

**Comment by AndreyDaniluk** [comment]
> I have two guesses
> 
> 1. Windows Server 2012 is too old and you need Windows 10 (I don't know which exactly one, probably not one of the first versions) at least
> 2. You've customized your system and disabled some service, so powershell doesn't work

My main PC on Windows 11 can be used for this?

**Comment by ilya-fedin** [comment]
Depends on its hardware. The build process consumes quite a lot of RAM>
