### ISSUE TITLE
cannot access read receipts in groups where topics are enabled

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#25773]
### Steps to reproduce

1. find a group with <100 members
2. enable topics
3. send a message and try to access the list of people who saw it

### Expected behaviour

tdesktop allows you to access the list

### Actual behaviour

it isn't possible to access the list, both from inside a topic and inside the "view as messages" screen (from Android, it works from both the screens)

### Operating system

Windows 10

### Version of Telegram Desktop

4.5.8

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
confirmed on https://t.me/tdesktopbetatest/

**Comment by BrianOfTarth** [comment]
Confirmed on tdesktop as well as android telegram.  Hope this gets fixed soon :(

**Comment by RememberTheAir** [comment]
no longer an issue, thanks!
