### ISSUE TITLE
[Feature Request] Allow untying the backround from the chat color

### ISSUE THREAD

**Issue by Naln1** [telegramdesktop/tdesktop#25781]
### Is your feature request related to a problem?

Basically #8316 again because it was ignored for two years.
I would love to use chat themes, but the extremely busy backgrounds for those themes effectively reduce contrast between the background and the bubbles to near-zero, making the feature unusable for me and other people who are hard-of-sight or hypersensitive to visual stimuli.

### Describe the solution you'd like

A global checkbox toggle in Chat Settings to enable/disable "Background affected by chat color" - similar to what was proposed in #8316 - sounds like the easiest implementation option.

### Describe alternatives you've considered

An option to customize the background for each individual chat theme, perhaps from a list of preset options (perhaps [No Change, Gradient, Solid Color, Pattern]) would be more complex, but I think a better option overall.

Or, the ability to have local-only chat themes so other people can continue to use chat themes without making life more difficult for people who need higher contrast. I dislike this option the most because it means the high-contrast-needing users continue to miss out on this feature.

**Comment by john-preston** [comment]
@Naln1 Can you provide an example with a screenshot of which chat theme are you talking about? With a bad contrast background and bubbles.

**Comment by Naln1** [comment]
These ones.
![Select theme: many themes identified by emoji 🐤⛄💎👨🏼‍🏫🌷💜🎄🎮](https://user-images.githubusercontent.com/43188089/222879972-07a4a082-7109-4583-a698-88ab5d62c387.png)

**Comment by Naln1** [comment]
This appears to have been added in 4.8, despite the lack of activity on this ticket. It's a slightly annoying two-step process which could probably be streamlined, but it gets the job done.
