### ISSUE TITLE
[Feature Request] Portable Linux Version

### ISSUE THREAD

**Issue by amirrh6** [telegramdesktop/tdesktop#25788]
### Is your feature request related to a problem?

I'd like to kindly ask the developers to provide a portable Linux version for Telegram Desktop which stores the data alongside the executable. Furthermore, Is there any workaround using a bash script?

### Describe the solution you'd like

A portable version of Telegram Desktop for Linux.

### Describe alternatives you've considered

I've heard that it may be possible to run Telegram Desktop for Linux as a portable executable by manually specifying some command line arguments.

**Comment by ilya-fedin** [comment]
You can create `TelegramForcePortable` folder near the executable

**Comment by amirrh6** [comment]
That's great! I wish you could document this feature somewhere, so other users may find it easily.
