### ISSUE TITLE
Japanese and Chinese text having weird font making it hard to read

### ISSUE THREAD

**Issue by TebelMeners** [telegramdesktop/tdesktop#25785]
### Steps to reproduce

1. Open any chat
2. Type some japanese/chinese
3. Send to recipient

### Expected behaviour

Characters being clearly readable with no weird bolding
![2023-01-25_22-22](https://user-images.githubusercontent.com/66430898/214588178-3551d341-756c-4111-89e1-061f8ec76f28.png)
Like this (On 3.6.1 from Ubuntu repo)

Arabic looks fine
For example, my friend's message that I replied to(尽量使用马来语，不要使用外语)
The second character, 量 is very much intelligible and recognisable in first sight

### Actual behaviour

![2023-01-25_22-26](https://user-images.githubusercontent.com/66430898/214589274-4c5ffa7a-f1fd-490c-95ef-1894028680af.png)
This is the same portion of the conversation in 4.5.3

Again, the Arabic text looks fine
Font thickness for hiragana and katakana is quite thin, but that I don't mind that much
The kanji(Chinese characters) have weird bolding and these characters have details that are quite important for being able to distinguish one from another, but sometimes this just makes it unintelligible what the character is
Example, my friend's message that I replied to(尽量使用马来语，不要使用外语)
The second character, 量 is bolded in the image above making it unintelligible.

### Operating system

Linux Mint 21.1 x86_64, Cinnamon 5.6.7

### Version of Telegram Desktop

4.5.3

### Installation source

Flatpak

**Comment by Aokromes** [comment]
update to 4.5.8 beta.

**Comment by TebelMeners** [comment]
Ah that fixed the issue. Thanks!

**Comment by ilya-fedin** [comment]
Are you sure? Have you update to 4.5.8 beta flatpak package or have you switched to another installation method? It might be that the bug is flatpak-specific.

**Comment by TebelMeners** [comment]
I installed 4.5.8 beta through the releases from github.
I haven't tried installing other versions through flatpak

**Comment by TebelMeners** [comment]
I added flathub-beta(from https://docs.flatpak.org/en/latest/using-flatpak.html)
`flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`

Then I searched telegram
`flatpak search telegram`

Output:
https://pastebin.com/Bq0GBeM3
(you might need to zoom out to read it properly)
It seems 4.5 is the latest.
(sorry for my lack of knowledge, this is my first month on Linux)

**Comment by ilya-fedin** [comment]
I believe it just lies about the version, check in the app UI

**Comment by TebelMeners** [comment]
I'm not sure what you mean by "the app UI"

**Comment by ilya-fedin** [comment]
I mean open tdesktop and find the version inside its UI (click the hamburger menu icon)

**Comment by TebelMeners** [comment]
I installed telegram from flatpak-beta remote and it says 4.5.8 beta in the UI

**Comment by ilya-fedin** [comment]
Ok, what about the font?

**Comment by TebelMeners** [comment]
Yep it's a flathub specific bug.
![2023-01-29_23-16](https://user-images.githubusercontent.com/66430898/215336078-b9ddeff9-f38c-43de-acd6-5483854f3501.png)
Same exact portion of convo and same bug.

**Comment by TebelMeners** [comment]
![image](https://user-images.githubusercontent.com/66430898/215336182-2ca6fa98-cbbf-4cd1-a40c-1f70b0dd5085.png)
I notice some spacing issues

**Comment by ilya-fedin** [comment]
Apparently flatpak runtime has bad CJK fonts, report this at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues

**Comment by ilya-fedin** [comment]
The spacing issues is #17221

**Comment by TebelMeners** [comment]
Alright. Thanks!
