### ISSUE TITLE
[Feature Request] Auto Translate all messages of a group/channel

### ISSUE THREAD

**Issue by mozilla-firefox** [telegramdesktop/tdesktop#25784]
### Is your feature request related to a problem?

When all messages of a channel or group is in another language, auto translate all messages is a good idea
If this is an expensive feature, you can add this only for premium users

### Describe the solution you'd like

k

### Describe alternatives you've considered

k

**Comment by RememberTheAir** [comment]
https://t.me/betainfoen/1151

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25775
