### ISSUE TITLE
Chat duration shows way more than the real duration

### ISSUE THREAD

**Issue by eliz-iza** [telegramdesktop/tdesktop#25782]
### Steps to reproduce

Videochat duration shows several days, although it did not last more than 5 minutes
It happens a lot

Steps to reproduce:

1. Go to Any chat group
2. Give a video call
3. Video chat ends
 
![image](https://user-images.githubusercontent.com/53395580/214502563-d530ebbf-6ca2-4649-9095-7c177f9dc8fe.png)

### Expected behaviour

Chat duration shows real duration

### Actual behaviour

Chat duration shows way more than the real duration

### Operating system

Windows 10 Home

### Version of Telegram Desktop

4.5.3 64x

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@eliz-iza Are you sure the chat was started 5 minutes before that? Usually there is a video chat "hanging" in the group for weeks without any participants, anyone can join at any time, but it is created already (a service message about video chat creation should be in the message history as well).

**Comment by eliz-iza** [comment]
> @eliz-iza Are you sure the chat was started 5 minutes before that? Usually there is a video chat "hanging" in the group for weeks without any participants, anyone can join at any time, but it is created already (a service message about video chat creation should be in the message history as well).

Ok, thank you
