### ISSUE TITLE
Telegram-desktop dumps core on video call

### ISSUE THREAD

**Issue by z0mb1e-kgd** [telegramdesktop/tdesktop#25780]
### Steps to reproduce

1. Open telegram-desktop app.
2. Start a video call.

### Expected behaviour

A video call starts.

### Actual behaviour

The telegram-desktop app crashes and dumps core to the system journal.

### Operating system

Arch Linux

### Version of Telegram Desktop

4.5.3

### Installation source

Official Arch Linux repository binary

### Logs

```shell
https://pastebin.com/fh4eyhJL
```

**Comment by Aokromes** [comment]
enable beta iirc it's fixed there. close if i am correct.

**Comment by z0mb1e-kgd** [comment]
> enable beta iirc it's fixed there. close if i am correct.

How would I do so? There is no such an option in the app settings (or I could have missed it).

**Comment by Aokromes** [comment]
then i vote you don't use static binary from official website.
try downloading official static beta (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by z0mb1e-kgd** [comment]
> then i vote you don't use static binary from official website. try downloading official static beta (non-flakpak, non-snap) version from https://desktop.telegram.org

I could have missed the point but I use binary from the Arch Linux official repo. There was no such an option in the dropdown, so I picked the closest one (I could edit my initial message to avoid discrepancies). I am not installing any betas or whatever, as I use Telegram messaging daily for work.

**Comment by ilya-fedin** [comment]
@z0mb1e-kgd Arch Linux repo is unofficial from Telegram PoV. The only official binary provider is desktop.telegram.org

**Comment by ilya-fedin** [comment]
> enable beta iirc it's fixed there. close if i am correct.

It's fixed long time ago, but the fix is usually not included in third-party builds, so just migrating to official build is enough.

**Comment by z0mb1e-kgd** [comment]
> > enable beta iirc it's fixed there. close if i am correct.
> 
> It's fixed long time ago, but the fix is usually not included in third-party builds, so just migrating to official build is enough.

Could you please elaborate what dependency causes the issue so I could push implementing the fix on Arch forums?

**Comment by ilya-fedin** [comment]
It's a patch from tdesktop Qt patchset
https://github.com/desktop-app/patches/blob/master/qtbase_6_4_2/0033-Revert-Do-not-use-client-side-data-pointers-in-qopen.patch
