### ISSUE TITLE
[Feature Request] please don't replace -- with — automatically, or need an option to disable it

### ISSUE THREAD

**Issue by lwhuang** [telegramdesktop/tdesktop#25794]
### Is your feature request related to a problem?

please don't replace -- with — automatically,  need to type -- exactly, I wrote telegram bot, use command line argument parser, such as /command1 --try --option=3

### Describe the solution you'd like

just disable this function, or need an option to disable it

### Describe alternatives you've considered

just disable this function, or need an option to disable it

**Comment by ilya-fedin** [comment]
Use the monospace markdown tag or disable 'Replace emoji automatically' option
