### ISSUE TITLE
[Feature Request] Please don't display chat name in taskbar

### ISSUE THREAD

**Issue by cvertee** [telegramdesktop/tdesktop#25793]
### Is your feature request related to a problem?

I think there is a problem. Displaying chat name in taskbar is literally a foundation for situational comedies in offices or at home. What if you work at some BIG Company and your manager/boss sees that you literally just alt-tabbed from Telegram to your favourite VS Code and the first thing he sees in the taskbar is "bluelogo JavaScript jobs - Telegram". Comedy gold right? "Oh there is a misundestanding love your salary and whatever *laughtrack*"

### Describe the solution you'd like

Just don't display chat name in the taskbar. Yeah I can just close window but who really does that? Alt-tab is faster no?

### Describe alternatives you've considered

Maybe a setting for that. Couldn't find one. So...

**Comment by ilya-fedin** [comment]
#25713
