### ISSUE TITLE
Crash on open image or video pop-up window(installed from AUR repo)

### ISSUE THREAD

**Issue by cppshizoidS** [telegramdesktop/tdesktop#25791]
### Steps to reproduce

Open tdesktop
open chat
open image by click on
crash

### Expected behaviour

open image

### Actual behaviour

crash of telegram

### Operating system

Majaro kde 6.1.7

### Version of Telegram Desktop

4.5.3

### Installation source

Other (unofficial) source

### Logs

```shell
95809 segmentation fault (core dumped)  telegram-desktop
```

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org
