### ISSUE TITLE
[26/26](Libraries/protobuf): FAILED

### ISSUE THREAD

**Issue by AndreyDaniluk** [telegramdesktop/tdesktop#25798]
### Steps to reproduce

1. Forked Telegram
2. Edited yml file ./.github/workflows/win.yml (added workflow_dispatch:)
3. Sended to compile in Github Actions - Here error

### Expected behaviour

Successful compile?

### Actual behaviour

```
D:\a\tdesktop_not_for_public\tdesktop_not_for_public\Libraries\win64\protobuf\build\Release\libprotoc.lib : fatal error LNK1108: cannot write file at 0xC0000 [D:\a\tdesktop_not_for_public\tdesktop_not_for_public\Libraries\win64\protobuf\build\libprotoc.vcxproj]
NOT FOUND, BUILDING:
---------------------------------COMMANDS-LIST----------------------------------
if exist protobuf rmdir /Q /S protobuf
if exist protobuf exit /b 1
git clone --recursive -b v21.9 https://github.com/protocolbuffers/protobuf
cd protobuf
git clone https://github.com/abseil/abseil-cpp third_party/abseil-cpp
cd third_party/abseil-cpp
git checkout 273292d1cf
cd ../..
mkdir build
cd build
cmake .. ^
-A %WIN32X64% ^
-Dprotobuf_BUILD_TESTS=OFF ^
-Dprotobuf_BUILD_PROTOBUF_BINARIES=ON ^
-Dprotobuf_BUILD_LIBPROTOC=ON ^
-Dprotobuf_WITH_ZLIB_DEFAULT=OFF ^
-Dprotobuf_DEBUG_POSTFIX=""
cmake --build . --config Release --parallel
cmake --build . --config Debug --parallel
--------------------------------------------------------------------------------
[26/26](Libraries/protobuf): FAILED
FAILED
Error: Process completed with exit code 1.
```

### Operating system

Windows Server 2022 (by yml file in ./.github/workflows/)

### Version of Telegram Desktop

v4.5.3 (forked dev)

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Yeah, the same happens on tdesktop's repo as well, GitHub sadly doesn't provide enough disk space to build tdesktop.

**Comment by AndreyDaniluk** [comment]
> Yeah, the same happens on tdesktop's repo as well, GitHub sadly doesn't provide enough disk space to build tdesktop.

Can i add remote disk, or anything else? If i understand need buy subscription for compile

**Comment by ilya-fedin** [comment]
> Can i add remote disk, or anything else?

I don't know.
