### ISSUE TITLE
Files comment sent as another post when sending >=2 files

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#25796]
### Steps to reproduce

1. Download telegram on windows 11 pro
2. Send >=2 files with comment
3. Comment sent as another post.

### Expected behaviour

I think it should send it like this:
![Снимок экрана 2023-01-28 151757](https://user-images.githubusercontent.com/5204968/215268512-995310a5-83df-46d6-8cf9-626e08ad5229.png)

### Actual behaviour

Now it's like this, comment sent as another post:
![Снимок экрана 2023-01-28 151732](https://user-images.githubusercontent.com/5204968/215268522-54a438ea-2a37-44f7-a506-0ec481c405ec.png)

### Operating system

Windows 11 Pro

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by soredake** [comment]
Not stale.

**Comment by john-preston** [comment]
Well, right now it works as intended. There is long and dull explanation, why, but it is coded like that intentionally.
