### ISSUE TITLE
Last selected chat is lost after restoring from system tray

### ISSUE THREAD

**Issue by xpg934** [telegramdesktop/tdesktop#2579]
Hello.

After one of recent updates, Telegram Desktop ceased to remember the last selected chat (contact), if it is minimized to tray (click the Close button on the title bar). After opening with a double click on the tray icon - last chat is not selected. It is not very convenient. I would like to return to the old behavior, or add a setting (maybe it already is?).

### Steps to reproduce
1. Open Telegram Desktop and select some contact from contact list -> chat is visible
2. Click on X-button (close) on the title bar of the window -> application is minimized to the system tray
3. Click on Telegram icon on the system tray (or right-click on the icon and click Open Telegram) -> application is restored, but last selected chat closed (no one chat is selected), and focus will be on the Search textbox.

### Expected behaviour
3. After restoring from the system stray - last opened chat should be selected, as was in previous versions

### Configuration
Operating system: Windows 10 Pro x64 RU
Version of Telegram Desktop: 0.10.19

**Comment by xpg934** [comment]
Hello, @auchri 

Could you provide a link to issue that I duplicated?
I can't find it.

**Comment by nighthawk469** [comment]
I also posted this issue. I really don't like this functionality. I have stopped using this version of telegram because of this
