### ISSUE TITLE
Clicking on notification in KDE doesn't open app

### ISSUE THREAD

**Issue by IvoryJam** [telegramdesktop/tdesktop#25801]
### Steps to reproduce

1. Receive notification
2. Click

### Expected behaviour

Opens application and takes me to the current that had the notification.

### Actual behaviour

It just acknowledges the notification without opening the Telegram window.

### Operating system

Fedora 37 - KDE Wayland

### Version of Telegram Desktop

4.5.3

### Installation source

Flatpak

**Comment by IvoryJam** [comment]
The issue is not present in the binary version from the website

**Comment by ilya-fedin** [comment]
It's a bug in KDE's portal implementation, it has bad support for portal notifications. You can only not using sandboxed variant of tdesktop.
