### ISSUE TITLE
Audio player upmixes stereo to 5.1

### ISSUE THREAD

**Issue by kathampy** [telegramdesktop/tdesktop#2580]
### Steps to reproduce
1. Receive a stereo audio file some someone
2. Play the audio in telegram
3. Listen to center channel on a 5.1 speaker system
### Expected behaviour

Only left and right channels should play.
### Actual behaviour

Audio is upmixed to 5.1 channels.
### Configuration

Operating system: Windows 10 Anniversary

Version of Telegram Desktop: 0.10.19
### Logs

Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by evgeniyp** [comment]
Also I hear something wrong with sound on common stereo system/headphones.

**Comment by kathampy** [comment]
Yes, the algorithm is attempting to simulate a soundstage with any number of channels.

**Comment by ConradBrean** [comment]
I noticed something wrong with audio too, in the latest updates. Music is distorted in a way which makes  vocals the loudest part. I'm not sure when it's started, but it wasn't the case a couple of months ago.

**Comment by Adambl4** [comment]
Same here

**Comment by cheetah-spottycat** [comment]
I can confirm this with V1.1.7 on Windows 10. Even when your sound device is stereo and you are playing a stereo sound file, some weird mixing between channels occurs.

It makes the internal sound player unusable, no file sounds like it should.

**Comment by Hexawolf** [comment]
Same for me and all my friends.
Sound on TDeskop is broken and there's no excuse.

**Comment by daniel13gh** [comment]
Version 1.3 stable is there, still no fix for this issue. :(

**Comment by Lynesth** [comment]
Having a similar issue with 1.4.3 on Windows 10.

Voice (from calls) is only coming out from central speakers and if I plug my headphones in the front-right speaker (which commands all of them) I don't get any voice.

Any update on this matter ?

Thank you.

**Comment by DJ-ZX** [comment]
Are there any plans to fix this in the near future?

**Comment by Hexawolf** [comment]
I wonder why would Telegram ever need to "simulate a soundstage" especially considering how broken this is.

**Comment by kathampy** [comment]
@john-preston It seems OpenAL Soft always virtualizes sound in a 3D space around the listener. You have to use the AL_SOFT_direct_channels extension to disable this behavior.

http://openal.org/pipermail/openal/2015-February/000331.html
https://github.com/openalext/openalext/wiki/AL_SOFT_direct_channels

**Comment by john-preston** [comment]
@kathampy Thanks! I'll look into that.

**Comment by john-preston** [comment]
@kathampy In the description:

> AL_DIRECT_CHANNELS_SOFT set to AL_TRUE indicates the audio channels are not virtualized and play directly on the matching output channels if they exist, otherwise they are dropped. Applies only when playing non-mono buffers.

I'm a bit worried about **otherwise they are dropped** part. Won't it happen that some systems just stop playing audio completely?

**Comment by kathampy** [comment]
> I'm a bit worried about **otherwise they are dropped** part. Won't it happen that some systems just stop playing audio completely?
No. If the source is mono, it will always be virtualized to the center channel on any speaker configuration. If the source is stereo or greater, only the source channels that have corresponding physicals speakers will play through their respective speakers. i.e. when playing a surround source on stereo speakers you'll only hear the left and right source channels and the surround source channels will be ignored. The only time this will occur is if a user shares a multi-channel AAC or Dolby / DTS file. All web content from previews are usually stereo anyway. For the rare instances where users share multi-channel files, you'll need to manually downmix it from the number of source channels to the number of speakers so that all the source channels are audible. e.g. the center source channel with speech would be inaudible on a stereo system without downmixing.

**Comment by john-preston** [comment]
I'm not sure I support in-app playback of more than two channels (stereo format). So I think this should be ok.

**Comment by DJ-ZX** [comment]
>           I'm not sure I support in-app playback of more than two channels (stereo format). So I think this should be ok.

If needed - I can make different audio-files with channels from 1 to 8 and check direct output for Telegram for each of it. Btw: will be good to know complete list of codecs supported (for ex - PCM, FLAC, OGG Vorbis, Opus, MP3, AAC, what else?) and video containers too, so I will make some video demos as well

**Comment by DJ-ZX** [comment]
Seems bug is fixed. I found that it's not reproducible anymore in 1.5.4 and 1.5.5beta.
Thank you
