### ISSUE TITLE
High CPU usage in idle

### ISSUE THREAD

**Issue by bindoet** [telegramdesktop/tdesktop#25803]
### Steps to reproduce

I use Telegram 4.5.3 x64 for Windows and have a high idle CPU usage. Even when I minimized it, it still stuck at 50% CPU usage. Nothing changed when I used the app or the portable version. 
![tele h](https://user-images.githubusercontent.com/116060563/215402105-8ac9fee5-5102-4500-92c4-484fae73a009.png)

### Expected behaviour

When minimized, the app should use less resources. 

### Actual behaviour

The app is stuck at 50% CPU usage on idle.

### Operating system

Windows 7 64 bit

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#17125

**Comment by bindoet** [comment]
Idk, bro, it still stuck at 50% CPU usage in the background, even when I minimized it.

Telegram's performance is excellent, with no lagging or other issues, but it remains stuck at 50% CPU usage all of the time and is unable to sleep.

**Comment by bindoet** [comment]
I spammed telegram, opened it, and minimized it, and it worked.

I wonder if people who have the same issue can work with this solution.

lmfao,
