### ISSUE TITLE
[Feature Request] Unsubscribe from topics

### ISSUE THREAD

**Issue by TristisOris** [telegramdesktop/tdesktop#25806]
### Is your feature request related to a problem?

topics in group chats created to separate content, job tasks, etc. But it change nothing if they still required my attention.

### Describe the solution you'd like

- never receive any notifications from such topics.
- optionally, hide them (discord like)
- same for whole channels i don't want to read often (news, blogs).

### Describe alternatives you've considered

alternates prohibited.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
