### ISSUE TITLE
[Feature request] GIF in fullscreen

### ISSUE THREAD

**Issue by neelkadia** [telegramdesktop/tdesktop#2581]
### Steps to reproduce
1. Open any chat which has GIF sent or received.
2. Click on the GIF
### Expected behavior

GIF open's in a fullscreen same as Pictures/Videos and .zip/.pdf or so on file open respectively. 
### Actual behavior

Nothing happen when you click on GIF message
### Configuration

**Operating system:** Windows 8.1

**Version of Telegram Desktop:** 0.10.19

**Comment by diazbastian** [comment]
I remember several versions behind this behavior could be achieved by disabling the automatic download of GIF's. Then they would have to press them full screen like any other media.

I like the idea.

**Comment by janglapuk** [comment]
+1 for the this feature.

**Comment by surashu** [comment]
Adding another +1 to this feature 👍

**Comment by stek29** [comment]
@surashu There are github reactions for that :D

**Comment by NabiKAZ** [comment]
Great, This is important feature, And also need to `Ctrl+Mouse Wheel` for zooming, be like about images and videos.

**Comment by stek29** [comment]
Was added in alpha, I guess 🎉

**Comment by neelkadia** [comment]
Feature added. Closing this issue. 🎉🎉
