### ISSUE TITLE
Opening a chat in a new window with an active call crashes Telegram

### ISSUE THREAD

**Issue by nyakze** [telegramdesktop/tdesktop#25817]
### Steps to reproduce

1. Enable option to open chats in a new window in experimental settings
2. Start a voice call
3. Try to open a chat in a new window

### Expected behaviour

Telegram opens a chat in a new window

### Actual behaviour

Telegram crashes

### Operating system

Windows 10 22H2

### Version of Telegram Desktop

4.5.7

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Please try out 4.5.8 beta version (enable installing beta versions from Settings > Advanced).

**Comment by nyakze** [comment]
Fixed in 4.5.8. Thanks!
