### ISSUE TITLE
Erro na Atulização no fedora 37

### ISSUE THREAD

**Issue by serial02** [telegramdesktop/tdesktop#25816]
### Steps to reproduce

Hello

> sudo dnf upgrade --refresh -y
> [sudo] senha para edson: 
> Copr repo for PyCharm owned by phracek                             7.0 kB/s | 3.6 kB     00:00    
> created by dnf config-manager from https://brave-browser-rpm-relea  25 kB/s | 3.3 kB     00:00    
> Fedora 37 - x86_64                                                  54 kB/s |  44 kB     00:00    
> Fedora 37 openh264 (From Cisco) - x86_64                           1.8 kB/s | 989  B     00:00    
> Fedora Modular 37 - x86_64                                          53 kB/s |  43 kB     00:00    
> Fedora 37 - x86_64 - Updates                                        39 kB/s |  39 kB     00:01    
> Fedora Modular 37 - x86_64 - Updates                                46 kB/s |  47 kB     00:01    
> google-chrome                                                      4.4 kB/s | 1.3 kB     00:00    
> RPM Fusion for Fedora 37 - Free                                    3.4 kB/s | 2.4 kB     00:00    
> RPM Fusion for Fedora 37 - Free tainted                            3.1 kB/s | 2.2 kB     00:00    
> RPM Fusion for Fedora 37 - Free - Updates                           12 kB/s |  11 kB     00:00    
> RPM Fusion for Fedora 37 - Nonfree                                 4.5 kB/s | 2.9 kB     00:00    
> RPM Fusion for Fedora 37 - Nonfree - NVIDIA Driver                  14 kB/s |  13 kB     00:00    
> RPM Fusion for Fedora 37 - Nonfree - Steam                         3.9 kB/s | 2.7 kB     00:00    
> RPM Fusion for Fedora 37 - Nonfree tainted                          13 kB/s |  12 kB     00:00    
> RPM Fusion for Fedora 37 - Nonfree - Updates                        13 kB/s |  12 kB     00:00    
> Dependências resolvidas.
> 
>  Problema 1: pacote telegram-desktop-4.5.3-1.fc37.x86_64 requer qt6-qtbase(x86-64) = 6.4.1, mas nenhum dos provedores pode ser instalado
>   - não é possível instalar qt6-qtbase-6.4.2-1.fc37.x86_64 e qt6-qtbase-6.4.1-4.fc37.x86_64
>   - não é possível instalar o melhor candidato à atualização para o pacote telegram-desktop-4.5.3-1.fc37.x86_64
>   - não é possível instalar o melhor candidato à atualização para o pacote qt6-qtbase-6.4.1-4.fc37.x86_64
>  Problema 2: problema com o pacote instalado telegram-desktop-4.5.3-1.fc37.x86_64
>   - pacote telegram-desktop-4.5.3-1.fc37.x86_64 requer qt6-qtbase(x86-64) = 6.4.1, mas nenhum dos provedores pode ser instalado
>   - não é possível instalar qt6-qtbase-6.4.2-1.fc37.x86_64 e qt6-qtbase-6.4.1-4.fc37.x86_64
>   - pacote qgnomeplatform-qt6-0.9.0-8.fc37.x86_64 requer qt6-qtbase(x86-64) = 6.4.2, mas nenhum dos provedores pode ser instalado
>   - não é possível instalar o melhor candidato à atualização para o pacote qgnomeplatform-qt6-0.9.0-6.fc37.x86_64
> ===================================================================================================
>  Pacote                        Arquitetura       Versão                   Repositório         Tam.
> ===================================================================================================
> Ignorando pacotes com conflitos:
> (adicionar --best --allowerasing' a linha de comando para forçar sua atualização):
>  qt6-qtbase                    x86_64            6.4.2-1.fc37             updates            3.8 M
> Ignorando pacotes com dependências quebradas:
>  qgnomeplatform-qt6            x86_64            0.9.0-8.fc37             updates            161 k
> 
> Resumo da transação
> ===================================================================================================
> Ignorar  2 pacotes
> 
> Nada para fazer.
> Concluído!

![Captura de tela de 2023-02-01 08-25-57](https://user-images.githubusercontent.com/32621790/216030052-df844cb3-0a79-46c9-ba4a-7b7ae0461bdd.png)

### Expected behaviour

That it is possible to update the application normally

### Actual behaviour

update error

### Operating system

Fedora 37

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by xvitaly** [comment]
Telegram Desktop uses Qt private API and pinned to exact version of Qt. I will rebuild RPM Fusion packages soon.

**Comment by xvitaly** [comment]
Fixed in [telegram-desktop-4.5.3-2.fc37](https://koji.rpmfusion.org/koji/buildinfo?buildID=24751). Can be closed.

**Comment by serial02** [comment]
Hello Telegram Team

Even after recent update, Telegram crashes after closing or deactivating it are constant on Fedora 37. What can be done if no report can be sent by Fedora program, since it is not a non-free application?

![Captura de tela de 2023-02-14 09-49-46](https://user-images.githubusercontent.com/32621790/218745454-bf34d875-2d9c-4ab4-9cd9-35fa98336803.png)
![Captura de tela de 2023-02-14 09-49-34](https://user-images.githubusercontent.com/32621790/218745462-47602b72-8f87-47fa-8392-0265761088ed.png)
![Captura de tela de 2023-02-14 09-48-20](https://user-images.githubusercontent.com/32621790/218745469-dec89348-4652-4781-840c-764e891f90cc.png)

**Comment by xvitaly** [comment]
@serial02 Please try version 4.6.2 from testing:
```
sudo dnf upgrade --refresh telegram-desktop --enablerepo=rpmfusion-free-updates-testing
```
