### ISSUE TITLE
calls broken (partial) after last update

### ISSUE THREAD

**Issue by 221V** [telegramdesktop/tdesktop#25819]
### Steps to reproduce

calls broken for specific case after last update (maybe last 2 updates):

a friend has disabled the ability to call him first in the settings,
he calls me,

i accept the call,
i see the call window (friend see the same),

and the call window is frozen with "exchanging encryption keys..."

### Expected behaviour

expects - the call instead frozen window with "exchanging encryption keys..."

### Actual behaviour

no frozen window - ok call - when friend has enabled the ability to call him first in the settings,
and next as described in "steps to reproduce" (friend calls to me, i call to friend)

### Operating system

ubuntu 22.04

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz try downloading official static beta (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by 221V** [comment]
> plz try downloading official static beta (non-flakpak, non-snap) version from https://desktop.telegram.org

this is the one - "Get Telegram for Linux x64" - https://telegram.org/dl/desktop/linux

**Comment by Aokromes** [comment]
> > plz try downloading official static beta (non-flakpak, non-snap) version from [desktop.telegram.org](https://desktop.telegram.org)
> 
> this is the one - "Get Telegram for Linux x64" - [telegram.org/dl/desktop/linux](https://telegram.org/dl/desktop/linux)

https://desktop.telegram.org/changelog#beta-version

**Comment by BlackCatDevel0per** [comment]
I have the same problem.. When the video calls will work?

**Comment by BlackCatDevel0per** [comment]
I have the same problem: When will video calls work?

**Comment by BlackCatDevel0per** [comment]
I have the same problem, When will video calls work?

**Comment by BlackCatDevel0per** [comment]
I have the same problem, when will video calls work?

**Comment by Aokromes** [comment]
> I have the same problem, when will video calls work?

get https://desktop.telegram.org/changelog#beta-version
