### ISSUE TITLE
wher all chats with topics was read you can see inappropriate dialogue

### ISSUE THREAD

**Issue by jimdi** [telegramdesktop/tdesktop#25814]
### Steps to reproduce

open chat with topics enabled, read all chats and sometimes you can see related picture with suggestion to edit folders

![image](https://user-images.githubusercontent.com/2002983/215995732-c1c8e454-9ea4-418f-bac2-efcf85fdd000.png)

### Expected behaviour

you must see chat topics list

### Actual behaviour

i see empty folder dialog

### Operating system

Windows 11

### Version of Telegram Desktop

4.5.8 beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@jimdi I'm not sure I understand what you think is wrong here.

You have Unread folder selected on the left, without any unread chats its empty. You can switch to the All Chats folder and see the chats list.

**Comment by jimdi** [comment]
in normal situations it looks like
![image](https://user-images.githubusercontent.com/2002983/216037144-50d12080-1000-47e0-aaa3-721f755ce690.png)
without edit folder

**Comment by john-preston** [comment]
"Edit Folder" should open "Unread" folder edit box. In your report the "Unread" folder is selected in the left column, in your last screenshot the "All chats" is selected. I think it works as expected.
