### ISSUE TITLE
Switching between Telegram windows doesn't switch focus correctly

### ISSUE THREAD

**Issue by nyakze** [telegramdesktop/tdesktop#25818]
### Steps to reproduce

1. Enable opening chats in a new window in experimental settings
2. Open a chat in a new window
3. Place windows on top of each other, or make a windowed chat fullscreen, so it covers the main window fully
4. Try to open a link to another telegram chat in a windowed chat

### Expected behaviour

Focus should switch to a main window, showing a newly opened chat

### Actual behaviour

Focus blinks for a moment and returns to the windowed chat instead

This is a regression in version 4.5.8 (4.5.7 works as expected)

### Operating system

Windows 10 22H2

### Version of Telegram Desktop

4.5.8

### Installation source

Static binary from official website

**Comment by nyakze** [comment]
Also reproduceable with a simple alt-tab.

**Comment by john-preston** [comment]
@nyakze This should be fixed in the next version. Thanks for your report.

**Comment by nyakze** [comment]
Resolved in [v 4.5.9](https://github.com/telegramdesktop/tdesktop/releases/tag/v4.5.9)
