### ISSUE TITLE
Cannot log in Telegram desktop (last version) both via QR and by telephone number on Windows 10 (64bit)  

### ISSUE THREAD

**Issue by Pinchicryak2** [telegramdesktop/tdesktop#25824]
### Steps to reproduce

I'm in Phuket/Thailand. Telegram clients for iPhones, MacBooks, and Web work perfectly fine, but when I download tdesktop version > tried 4.5.3 and 4.6.0 for 64 bit Windows, it does not render QR code and does not send SMS to the provided phone number. I have the same problem as here https://github.com/telegramdesktop/tdesktop/issues/17243. But the new version and the old version don't work for me.

### Expected behaviour

Flow 1

The application renders QR code.

Flow 2

Receive SMS from telegram.

### Actual behaviour

Flow 1

Spinner is shown indefinitely long time
![141676757-8c4282f8-7161-4204-99a8-c9051e581161](https://user-images.githubusercontent.com/19203255/216750801-438f4075-4a5e-44dd-bb3b-dd7004d7c73f.jpeg)
Flow 2

No messages are received within several hours.

### Operating system

Windows 10, 64bit

### Version of Telegram Desktop

4.6.0

### Installation source

Static binary from official website

### Logs

```shell
Dont have
```

**Comment by john-preston** [comment]
@Pinchicryak2 Can you please tell me what do you have in

`HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\BIOS\SystemProductName` ?

**Comment by Pinchicryak2** [comment]
> @Pinchicryak2 Can you please tell me what do you have in
> 
> `HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\BIOS\SystemProductName` ?

Yes, sure! 

![Screenshot 2023-02-04 095644](https://user-images.githubusercontent.com/19203255/216753719-3fad85c2-67f4-42d1-b238-51c3b4ef2c38.png)

**Comment by john-preston** [comment]
@Pinchicryak2 Strange. Please copy the full BIOS section from this registry key?

**Comment by Pinchicryak2** [comment]
@john-preston yeah, very strange situation. 
![Screenshot 2023-02-04 103813](https://user-images.githubusercontent.com/19203255/216755376-0748d729-b11b-4058-adc1-4327b810066d.png)

**Comment by john-preston** [comment]
Ok, can you:
1. Go to Settings
2. Type "debugmode" from your keyboard (like a cheatcode)
3. Accept writing Debug Logs in the confirmation promt
4. Restart the app
5. Reproduce the problem
6. Quit the app
7. Send me to t.me/preston .zip-ed DebugLogs folder that was created near Telegram.exe (using Web version, for example)
8. Write here that you did, so I'd find this new chat with you

Because I don't really see the values I was hoping the fix to work for.

**Comment by Pinchicryak2** [comment]
@john-preston Done! Check my chat please)
