### ISSUE TITLE
[Feature Request] An option to ignore "Archive chats" folder unread count

### ISSUE THREAD

**Issue by ebraminio** [telegramdesktop/tdesktop#25829]
### Is your feature request related to a problem?

I like to have a mode that I just don't see unread count for certain groups/chats/channels and visit them only when I want. I like to be able to archive those chats and don't see their count on the drawer until I decide I like to visit archived chats folder.

### Describe the solution you'd like

I think it would be nice if "Count unread messages" option of "Badge counter" of "Notification and Sounds" could disable the following badge counter of drawer,

<img width="304" alt="image" src="https://user-images.githubusercontent.com/833473/216759710-2d38ab45-3a27-42e0-80e9-0381804c5209.png">

### Describe alternatives you've considered

But when I go to the drawer for settings saved messages etc I still see the counter

**Comment by ilya-fedin** [comment]
#6314
