### ISSUE TITLE
Can't type vietnamese telex on Centos 8

### ISSUE THREAD

**Issue by hoanhdo** [telegramdesktop/tdesktop#25821]
### Steps to reproduce

1.i mean add new input source "vietnamese telex m17n" on region and language setting use Centos 8 Stream, RockyLinux 8 OS
2. Install telegram on machine
3. Type vietnamese but nothing happen.
Eg: type "ee" will be "ê" on chat
type aa will be "â" on chat 

### Expected behaviour

Type vietnamese same as other app
Type ee will be "ê" on chat

### Actual behaviour

I can't type vietnamese, only english
Type ee still "ee" on chat

### Operating system

Centos 8 Stream, RockyLinux 8

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Please provide steps to reproduce like if you would explain how to reproduce this to a non-vietnamese person.

**Comment by ilya-fedin** [comment]
> I add some example to reproduce.

"Install vietnamese telex keyboard" is still vague to me

**Comment by hoanhdo** [comment]
> > I add some example to reproduce.
> 
> "Install vietnamese telex keyboard" is still vague to me

i mean add new input source "vietnamese telex m17n" on region and language setting
![image](https://user-images.githubusercontent.com/5550425/216247448-8b694578-2a85-4541-afa8-6b5ca856e262.png)

**Comment by ilya-fedin** [comment]
:thinking: it seems I don't have such layout on my system
![изображение](https://user-images.githubusercontent.com/17829319/216249353-1cc0bc25-aaad-4568-80c6-190e84b15864.png)
And I don't really want to create a VM with CentOS 7...

**Comment by ilya-fedin** [comment]
Maybe setting `QT_LOGGING_RULES=qt.qpa.input.methods.debug=true` environment variable will make tdesktop output something useful in the terminal

**Comment by hoanhdo** [comment]
``

> thinking it seems I don't have such layout on my system ![изображение](https://user-images.githubusercontent.com/17829319/216249353-1cc0bc25-aaad-4568-80c6-190e84b15864.png) And I don't really want to create a VM with CentOS 8...

This bug only on centos 8, not on centos 7
![image](https://user-images.githubusercontent.com/5550425/216255905-82108994-86ff-4d1f-a499-022f8fdc3e83.png)

**Comment by ilya-fedin** [comment]
> This bug only on centos 8, not on centos 7

I don't use CentOS 7, I use NixOS with KDE.

**Comment by hoanhdo** [comment]
> QT_LOGGING_RULES=qt.qpa.input.methods.debug=true

I see only show log
```

[hoannv@hoannv-desktop Telegram]$ export QT_LOGGING_RULES=qt.qpa.input.methods.debug=true
[hoannv@hoannv-desktop Telegram]$ ./Telegram 
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segmen

```

**Comment by hoanhdo** [comment]
> > This bug only on centos 8, not on centos 7
> 
> I don't use CentOS 7, I use NixOS with KDE.

I use default gnome deskt, i install centos 8 with mode "server with GUI

**Comment by ilya-fedin** [comment]
hmm, have you tried any other Qt application? Maybe the distro doesn't integrate Qt applications? If that's the case then you should probably bug your distro.

**Comment by hoanhdo** [comment]
> hmm, have you tried any other Qt application? Maybe the distro doesn't integrate Qt applications? If that's the case then you should probably bug your distro.

I use many app : microsoft team, text document, vscode etc. All this app i use without bug, only telegram i can't t vietnamese

**Comment by ilya-fedin** [comment]
None of these apps use Qt. You should try a Qt application like qBittorrent or VLC.

**Comment by hoanhdo** [comment]
> None of these apps use Qt. You should try a Qt application like qBittorrent or VLC.

I tried qBittorrent and VLC, i can't type vietnamese :(.

**Comment by ilya-fedin** [comment]
So it seems CentOS doesn't integrate Qt applications :(
You have to report that either for CentOS so they start care about Qt applications or for Qt to somehow adapt to CentOS behavior.

**Comment by hoanhdo** [comment]
> So it seems CentOS doesn't integrate Qt applications :( You have to report that either for CentOS so they start care about Qt applications or for Qt to somehow adapt to CentOS behavior.

ok. i will report o them.
Thanks.

**Comment by ilya-fedin** [comment]
huh? centos stream is not eol

**Comment by Aokromes** [comment]
oh i only have read title, not details.

**Comment by hoanhdo** [comment]
> So it seems CentOS doesn't integrate Qt applications :( You have to report that either for CentOS so they start care about Qt applications or for Qt to somehow adapt to CentOS behavior.

maybe i found problem. I don't find ibus-qt package on centos 8 stream r

**Comment by ilya-fedin** [comment]
ibus plugin is a part of Qt. What is missing is distro to synchronize input settings between gtk and Qt (GNOME it self doesn't do that and a lot of other Qt compatibility things as it seems they try to make Qt applications to work as worse as possible)
