### ISSUE TITLE
Telegram Downloads files repeatedly

### ISSUE THREAD

**Issue by Mistero5050** [telegramdesktop/tdesktop#2582]
### Steps to reproduce
1. Download any file from any chat in windows
### Expected behaviour

After one time that the file is downloaded, it should be available to be opened.
### Actual behaviour

Telegram tries to download it another times, for about 5 times when it works after 4/5 times
See this link https://www.youtube.com/watch?v=gf_WuKRmKtM&feature=youtu.be
### Configuration

**Operating system:** Windows 10

**Version of Telegram Desktop:** This issue is there from 0.9.x, now I'm using 0.10.19

Sorry for bad English

**Comment by john-preston** [comment]
@Mistero5050 If you log out all the saved file locations are lost and we don't know anymore that you've downloaded any of your files.

**Comment by Mistero5050** [comment]
I don't log out

**Comment by Mistero5050** [comment]
Here it is https://www.youtube.com/watch?v=gf_WuKRmKtM&feature=youtu.be

**Comment by Aokromes** [comment]
#747 ?
