### ISSUE TITLE
Telegram crash to add new colour when 4 already exist

### ISSUE THREAD

**Issue by Jeronimo17** [telegramdesktop/tdesktop#25823]
### Steps to reproduce

![Error](https://user-images.githubusercontent.com/4985763/216733224-08367835-a702-4e76-921d-4fcc51b7eafe.png)

### Expected behaviour

No + button

### Actual behaviour

Crash

### Operating system

Linux

### Version of Telegram Desktop

4.6

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by Jeronimo17** [comment]
Your Report Tag: f7696665-e19c-4090-d52050b9-77525b8a

**Comment by john-preston** [comment]
Thanks! Fixed in https://github.com/telegramdesktop/tdesktop/commit/985db8aacfe0571b44faed21791215adb1e64020 for the next version.
