### ISSUE TITLE
Open telegram (not menu) on double-click on system tray icon.

### ISSUE THREAD

**Issue by victorkitov** [telegramdesktop/tdesktop#25826]
### Is your feature request related to a problem?

I have telegram icon after installing it with `sudo apt install telegram-desktop`. Telegram version 3.6.1. OS - Ubuntu 22.04. And instead of default applications dash panel I'm using dash-to-panel ([dash-to-panel][1]) but I think it does not matter for the problem. 

When I was using Ubuntu 18.04 telegram would open chats after double-click on its icon in tray. However now on Ubuntu 22.04 after double-click nothing happens, after single click a menu [Open telegram, Disable notifications, Quit Telegram] is shown. Since I frequently use Telegram to reopen chats, is there any way to restore the old behavior - open telegram chats after double-click?

### Describe the solution you'd like

Since I frequently use Telegram to reopen chats, is there any way to restore the old behavior - open telegram chats after double-click or single click?

### Describe alternatives you've considered

Al tentatively add in settings the option to select - either to open default menu or directly opening telegram after clicking or double-clicking.

### Additional context

![image](https://user-images.githubusercontent.com/10587992/216753833-29989395-ffa3-420b-8347-8339df3cbc67.png)

**Comment by ilya-fedin** [comment]
The behavior is dictated by your tray implementation, not by tdesktop.

**Comment by victorkitov** [comment]
On default menu I observe the same: 
![image](https://user-images.githubusercontent.com/10587992/216755676-881ffdad-bd89-47ea-a79b-d187a086e32d.png)

**Comment by ilya-fedin** [comment]
This doesn't change what I said

**Comment by victorkitov** [comment]
Ok, thank you for feedback.
