### ISSUE TITLE
Hebrew font size changed after upgrading to v4.6.0

### ISSUE THREAD

**Issue by eXoticD** [telegramdesktop/tdesktop#25828]
### Steps to reproduce

After the new update, all text on Hebrew fonts looks too small.
The text size has been changed.

### Expected behaviour

It should be a bigger font size.

### Actual behaviour

very hard to read with small font size

### Operating system

windows 11

### Version of Telegram Desktop

4.6.0

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can you check whether qBittorrent Qt 6 version has the same problem? Ensure to check the Qt 6 version, not Qt 5 version. If yes can you report to https://bugreports.qt.io?

**Comment by john-preston** [comment]
Please provide screenshots Before - After.

Also, can you check if the right font is Tahoma or not.

**Comment by eXoticD** [comment]
> Please provide screenshots Before - After.
> 
> Also, can you check if the right font is Tahoma or not.

Hey,
How can I find out if its Tahoma or not? 
https://i.imgur.com/Kb3xlDI.png

**Comment by ilya-fedin** [comment]
The size looks ok to me. It's changed what's expected but still it looks ok.

**Comment by eXoticD** [comment]
> 

Link to version 6? I can find 4.5
what is the connection between qBittorrent and Telegram?



> The size looks ok to me. It's changed what's expected but still it looks ok.

The size is too small

**Comment by ilya-fedin** [comment]
> what is the connection between qBittorrent and Telegram?

Both are using Qt.

**Comment by ilya-fedin** [comment]
> The size is too small

It's hard to treat it as a bug.

**Comment by eXoticD** [comment]
Please see the sidebar folder's font size.

**Comment by itayganor** [comment]
The Hebrew font is no longer Tahoma. Happens on my end too.

(Windows 11, TD 4.6.0)

**Comment by ilya-fedin** [comment]
> Link to version 6? I can find 4.5

6 is the version of Qt, not of qBittorrent. So you need qBittorrent 4.5 built with Qt 6.

**Comment by itayganor** [comment]
Thai seems to suffer from this issue as well: https://github.com/telegramdesktop/tdesktop/issues/25825

**Comment by eXoticD** [comment]
https://i.imgur.com/yUqgDkr.png

**Comment by Aokromes** [comment]
continue at https://github.com/telegramdesktop/tdesktop/issues/25825
