### ISSUE TITLE
Font chat is very small after update V4.6

### ISSUE THREAD

**Issue by editt26** [telegramdesktop/tdesktop#25836]
### Steps to reproduce

chat everything that is My Thai language is much smaller.

Picture example, I compare Thai and English.
https://imgur.com/a/Q41xbdL

### Expected behaviour

*

### Actual behaviour

*

### Operating system

Windows 10 Pro

### Version of Telegram Desktop

4.6 X64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25825
