### ISSUE TITLE
Telegram desktop v 4.6 on win 10 PC x 64 OS 22H2

### ISSUE THREAD

**Issue by buio2005** [telegramdesktop/tdesktop#25837]
### Steps to reproduce

when pasting a link to a page with an image as default cant see it as preview 

### Expected behaviour

it would appear on top right as usual 

### Actual behaviour

just foir a second's fraction appear "check information" but image doesnt load 

### Operating system

windows 10 x 64 OS  22H2

### Version of Telegram Desktop

v 4.6

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
cannot reproduce:
https://i.imgur.com/Rg5YmO0.png

https://t.me/TelegramDesktopTalk/95519

**Comment by staypov** [comment]
I can not access my account telegram

**Comment by Aokromes** [comment]
also, previews are server side.

**Comment by staypov** [comment]
Why login access acc te telegram
