### ISSUE TITLE
Prefer fcitx5 im module over fcitx4, at least under wayland.

### ISSUE THREAD

**Issue by wengxt** [telegramdesktop/tdesktop#25835]
### Steps to reproduce

Comparing to fcitx5, fcitx4 im module is lacking proper wayland support.

And for the compatibility, the guide from fcitx side is to set QT_IM_MODULE=fcitx, instead of fcitx5.

The current way that telegram-desktop bundles both fcitx4/fcitx5 im module and make fcitx5 doesn't accept QT_IM_MODULE=fcitx is causing issue when people is running under wayland. 

E.g. https://github.com/fcitx/fcitx5/issues/710

To me the easiest way is to simply remove fcitx4 im module in telegram if old fcitx4 is no longer a concern.

### Expected behaviour

use fcitx5 im module under wayland.

### Actual behaviour

fcitx4 im module is used under wayland.

### Operating system

Archlinux 

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop declares support for Ubuntu 14.04+, so fcitx4 is still a concern :(

**Comment by ilya-fedin** [comment]
It's sadly no possible to choose fcitx4/fcitx5 from tdesktop code, Qt just doesn't provide API for that. The only way out I see is to merge fcitx4/fcitx5 plugins and do the necessary checks inside the plugin, choosing the right impl.

**Comment by wengxt** [comment]
I added https://github.com/fcitx/fcitx5-qt/commit/5178d3571626156148cb3eb42b0a2bb093e8df1d fcitx4 service support to fcitx5-qt, so you should be able to deprecate the one from fcitx4.

**Comment by ilya-fedin** [comment]
will try!

**Comment by ilya-fedin** [comment]
I've update fcitx5-qt as a part of the big dependency update. Hope it will work.
