### ISSUE TITLE
Telegram Desktop for Windows 7 & 10 crashes when click on Videos

### ISSUE THREAD

**Issue by Laura444x** [telegramdesktop/tdesktop#25832]
### Steps to reproduce

See a Video
Click on it
and Telegram Desktop crashes

### Expected behaviour

Want to watch a video

### Actual behaviour

Telegram Desktop crashes

### Operating system

Windows 7 and Windows 10

### Version of Telegram Desktop

Version 4.6

### Installation source

Static binary from official website

**Comment by Laura444x** [comment]
Please note that this issue is on both computers: 
On my old Windows 7 and on my Windows 10 Desktop PC.

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by lawlala** [comment]
Telegram Desktop always crashes when clicking the video after updating TG to V.4.6.
Win10

**Comment by Laura444x** [comment]
Hello all,

**for all who have the same problem:**

I have both computers x64.

I have deleted Telegram and downloaded and installed new fresh version from the website.

All is working now. 

This topic can be closed.

**Thank you for your support and have a nice day.**

**Comment by john-preston** [comment]
@lawlala Please try x64 version from the website. Now need to uninstall / delete the crashing version, just install the new one over the existing one.
