### ISSUE TITLE
Telegram crashes after opening "Call Settings"

### ISSUE THREAD

**Issue by Petrprogs** [telegramdesktop/tdesktop#25834]
### Steps to reproduce

1. Open Telegram Desktop and go to settings
2. Click on "Call Settings"
3. After 2 seconds Telegram crashes

### Expected behaviour

"Call Settings" should open normally.

### Actual behaviour

Telegram Desktop crashes in 2 seconds after opening "Call Settings"

### Operating system

MX Linux 21.3 x32, IceWM

### Version of Telegram Desktop

4.2.4

### Installation source

Other (unofficial) source

### Logs

```shell
#
# Fatal error in: ./src/api/video/i420_buffer.cc, line 53
# last system error: 1
# Check failed: height > 0 (-2147483648 vs. 0)
# Аварийный останов
```

**Comment by Petrprogs** [comment]
I know, that this Telegram version is little bit old, but where i can get latest for x32?

**Comment by Aokromes** [comment]
only compiling yourself will give you a 32 bits updated linux binary

**Comment by Petrprogs** [comment]
> only compiling yourself will give you a 32 bits updated linux binary

But docker is not available on linux x32

**Comment by Aokromes** [comment]
no one said it will be easy.

**Comment by ilya-fedin** [comment]
It's possible to build without docker (https://github.com/telegramdesktop/tdesktop/wiki/The-Packaged-Building-Mode), but that instruction requires way more experience, it also requires your distro to have new enough libraries.

**Comment by ilya-fedin** [comment]
A better option for you might be to switch to a distro with more actual software, like Void Linux or Arch Linux 32

**Comment by Petrprogs** [comment]
Ok, i installed latest version, but error still persist. What can id do?

**Comment by ilya-fedin** [comment]
What's the exact version you installed?

**Comment by Petrprogs** [comment]
> What's the exact version you installed?

4.6

**Comment by ilya-fedin** [comment]
Are you sure you built both tdesktop and tg_owt with `-DCMAKE_BUILD_TYPE=Release`?

**Comment by Petrprogs** [comment]
Yes 06.02.2023, 04:32, "ilya-fedin" ***@***.***>: Are you sure you built both tdesktop and tg_owt with -DCMAKE_BUILD_TYPE=Release?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ilya-fedin** [comment]
If you have the same error message as provided in your first post then I can say tg_owt is built without `-DCMAKE_BUILD_TYPE=Release` for sure as there's a debug check at the line error complains about

**Comment by Petrprogs** [comment]
> If you have the same error message as provided in your first post then I can say tg_owt is built without `-DCMAKE_BUILD_TYPE=Release` for sure as there's a debug check at the line error complains about

I tried to build TG with debug and release, but still persist.. Help me.. I need to setup camera settings...

**Comment by ilya-fedin** [comment]
@Petrprogs TG itself? what about tg_owt?

**Comment by Petrprogs** [comment]
> @Petrprogs TG itself? what about tg_owt?

And TG and tg_owt...

**Comment by ilya-fedin** [comment]
> And TG and tg_owt...

Are you 100% sure the error is the same as in your first message? Maybe it's a little different? If it's the same, can you provide CMakeCache.txt of your tg_owt build?

**Comment by Petrprogs** [comment]
> > And TG and tg_owt...
> 
> Are you 100% sure the error is the same as in your first message? Maybe it's a little different? If it's the same, can you provide CMakeCache.txt of your tg_owt build?

ok, I connected my USB camera to the second computer and successfully entered TG "Call Settings". In a sense, this is good, but also bad...

**Comment by Petrprogs** [comment]
> > And TG and tg_owt...
> 
> Are you 100% sure the error is the same as in your first message? Maybe it's a little different? If it's the same, can you provide CMakeCache.txt of your tg_owt build?

Maybe problem in driver.. But in Linux it is quite difficult problem...

**Comment by ilya-fedin** [comment]
Well, the line your first message seems like your driver specifies height that leads to integer overflow
