### ISSUE TITLE
Missing a "t" in the local passcode interface

### ISSUE THREAD

**Issue by WilliamK7** [telegramdesktop/tdesktop#25848]
### Steps to reproduce

1. lock telegram
2. see the bug

### Expected behaviour

see "log out"

### Actual behaviour

see "log ou"
![image](https://user-images.githubusercontent.com/82304956/217135713-e12523e5-e6cb-4b9d-bb1c-731db0f21d93.png)

### Operating system

Windows 10 Pro 19045.2546

### Version of Telegram Desktop

4.6.1 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Did you change the UI language?.. Because it looks fine to me.

Or maybe it is interface scale issue, which one do you have in Settings?

**Comment by WilliamK7** [comment]
I used to have the interface scale on 125%, but after I switched it back, it's the same anyway. And I'm using the official English language.

![image](https://user-images.githubusercontent.com/82304956/217200265-5d498e80-a0fd-4288-a4e5-2b678a6c1869.png)

**Comment by WilliamK7** [comment]
Fixed in 4.6.2
