### ISSUE TITLE
[Windows] Telegram Desktop reacts strangely to slightly-off INPUT/SendInput events

### ISSUE THREAD

**Issue by YellowAfterlife** [telegramdesktop/tdesktop#25845]
### Steps to reproduce

1. Run the following C++ console program:
	```cpp
	#include <Windows.h>
	int main() {
		RegisterHotKey(0, 101, 0, VK_F7);
		MSG msg{};
		while (GetMessage(&msg, 0, 0, 0)) if (msg.message == WM_HOTKEY) {
			 wchar_t chars[] = L"їЇыЫ·—";
			 for (size_t i = 0u, n = wcslen(chars); i < n; i++) {
				 INPUT input; ZeroMemory(&input, sizeof(INPUT));
				 input.type = INPUT_KEYBOARD;
				 input.ki.wScan = chars[i];
				 input.ki.dwFlags = KEYEVENTF_UNICODE;
				 SendInput(1, &input, sizeof(INPUT));
				 input.ki.dwFlags = KEYEVENTF_KEYUP; // <- `=` instead of `|=`
				 SendInput(1, &input, sizeof(INPUT));
			 }
		}
	}
	```
	([compiled version](https://github.com/telegramdesktop/tdesktop/files/10669893/TestTg.zip))
2. Switch to an input field in Notepad, web browser, or _seemingly any non-TD program_, really.
3. Press F7. String `їЇыЫ·—` is inputted.
4. Switch to an input field in Telegram Desktop.
5. Press F7. String `їїїїїї` is inputted.

This is one of those "have you tried not doing that" things and I'm mostly posting it in case anyone else runs into this, but also... why does TD react like _that_? And it gets funkier: if you check this [slightly bigger sample](https://github.com/telegramdesktop/tdesktop/files/10669915/td1.zip), the first entered character "sticks" until you enter something with a different modifier key set (Shift-1/2 vs 1/2) or change window focus. Software is full of mysteries.

### Expected behaviour

String `їЇыЫ·—` is inputted in Telegram.

### Actual behaviour

String `їїїїїї` is inputted in Telegram.

### Operating system

Windows 10, 21H2, 19044.2486

### Version of Telegram Desktop

4.6 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> why does TD react like _that_?

I guess no one will answer that question here as such low-level things are handled by Qt
