### ISSUE TITLE
Font Size of 2nd language is too small

### ISSUE THREAD

**Issue by Plutogithub2022** [telegramdesktop/tdesktop#25840]
### Steps to reproduce

1. After update version 4.6 on desktop ,all our clients got the font size is very small on second language as Thai.

### Expected behaviour

Please fix this issue

### Actual behaviour

I can't find any settings to setup the font size increase in Desktop version.

### Operating system

Windows 10

### Version of Telegram Desktop

4.6

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25825
