### ISSUE TITLE
Changing .desktop file properties are overridden

### ISSUE THREAD

**Issue by isasmendiagus** [telegramdesktop/tdesktop#25850]
### Steps to reproduce

1. Fresh binary installation from website https://telegram.org/dl/desktop/linux
2. Extract content and locate at
`
sudo cp * /opt/Telegram/Work /opt/Telegram/Personal
`
3. Create TelegramForcePortable folder with 
`mkdir -p /opt/Telegram/Personal/TelegramForcePortable /opt/Telegram/Work/TelegramForcePortable`

4. Adjust permissions with `sudo chown -R ubuntu:ubuntu /opt/Telegram`
5. Now I want to change the icon for my Work telegram editing the .desktop file located at `~/.local/share/applications/org.telegram.desktop._<MD5SUM>.desktop`
6. Changing the Icon and Name properties works, I can see the Icons and App name changed in my desktop

### Expected behaviour

The .desktop file is expected not to be overwritten by the application after closing.
It is impossible to differentiate different UIs with multiple instances

### Actual behaviour

Telegram overwrites the edited .desktop file.

### Operating system

Ubuntu 22.04 (Fresh install)

### Version of Telegram Desktop

4.6.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> The .desktop file is expected not to be overwritten by the application after closing.

Sorry, but there are people who expect it to be overwrittern

**Comment by isasmendiagus** [comment]
What workaround would be possible to keep two instances running with different Icons and Name between each other?

**Comment by ilya-fedin** [comment]
Well, I don't think it's a supported feature, I don't see any presence of supporting custom icon in the shortcut in the Windows platform code. It overwrites the shortcut in the menu on every start as well.

**Comment by isasmendiagus** [comment]
Ok, I don't understand why the apps overwrites the .desktop file but I guess you guys have a lot of reason to do that,
Could you please point me out where in the code is locate that section? I can change it and compile by myself. 

Thanks!

**Comment by ilya-fedin** [comment]
the `specific_linux.cpp` file, `InstallLauncher` method

**Comment by ilya-fedin** [comment]
It's being overwrited because people tend to delete it and the complain tdesktop doesn't have window icon and etc.

**Comment by isasmendiagus** [comment]
Thanks for your details!

Wouldn't it be better to add a check if the file doesn't exist to create it?
Instead of overwriting the file at the time the app is closed.

**Comment by ilya-fedin** [comment]
> Wouldn't it be better to add a check if the file doesn't exist to create it?

The file may need an update due to renaming or content change

**Comment by isasmendiagus** [comment]
SOLVED:

As you can see [here](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/linux/specific_linux.cpp#L524) you can setup a ENV variable to avoid the InstallLauncher() call

This is for anyone which is interested in edit the .desktop file of a binary instalation.
You can edit the line Exec in your `~/.local/share/applications/org.telegram.desktop._<MD5SUM>.desktop` file for the following:

`Exec=env DESKTOPINTEGRATION=1 <YOUR_BINARY_LOCATION> -- %u` 

This will avoid that telegram overwrites the .desktop file every time you close the app

**Comment by ilya-fedin** [comment]
I don't really recommend doing that, you will miss any desktop file changes what will lead to application misbehavior when talking with system APIs

**Comment by isasmendiagus** [comment]
@ilya-fedin Thanks for your help, I understand the risk of blocking Telegram binary to write the .desktop file. 
For that reason I disabled the Automatics Updates from the GUI. 

Here are my results:
![image](https://user-images.githubusercontent.com/17660235/217249061-b6a0950e-2075-4402-ad62-2f96e833ee7f.png)
