### ISSUE TITLE
Text from Telegram is not copied to windows clipboard in CF_TEXT format

### ISSUE THREAD

**Issue by waptaxi** [telegramdesktop/tdesktop#25851]
### Steps to reproduce

1. Select and copy text from any telegram message.

### Expected behaviour

Text should be copied to windows clipboard with CF_TEXT format.

### Actual behaviour

Since version 4.6.1 text is copying from telegram messages to windows clipboard with incorrect CF_TEXT format.
As I can see in clipboard viewers it has Unicode Text Format, OEM Text, Locale Identifier and Text format (CF_TEXT).
But the contents of Text format is empty, so we can not paste it in some applications that use Text format.

### Operating system

Windows

### Version of Telegram Desktop

4.6.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
i think it will be fixed on 4.6.2
