### ISSUE TITLE
Window controls on the title bar don't support split arrangement

### ISSUE THREAD

**Issue by TomiOhl** [telegramdesktop/tdesktop#25858]
### Steps to reproduce

1. Setup the title bar on your system to a split arrangement, e.g. close button on the left, maximize button on the right (that's elementary's default btw. I normally add a minimize button to the right, too)
2. uncheck "use system window frame" in Telegram's settings

### Expected behaviour

The close button should appear on the left of the title bar, the minimize and maximize buttons should appear on the right of the title bar (from my example above).
Here is a good example from Chrome:
![image](https://user-images.githubusercontent.com/6696659/217352475-96742f0e-6afe-447b-b867-b272cfbbf9d8.png)

### Actual behaviour

All the window controls appear on the same side:
![image](https://user-images.githubusercontent.com/6696659/217352591-53fd8565-8299-47b0-8611-3b1c73d47a12.png)

### Operating system

Elementary OS 7, Pantheon

### Version of Telegram Desktop

4.6.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
AFAIK there's no intention to support such layout as it's not supported by the mockups provided by the Telegram state designers.

**Comment by TomiOhl** [comment]
Umm, that was quick.. I mean this isn't really a design issue, rather something that doesn't fully follow the system, but it does partially: if I reorder the buttons they get reordered here, if I place all at the right side they all appear correctly on the right side etc...

**Comment by ilya-fedin** [comment]
@TomiOhl it was following such layout at first, but then there was a report about UI artifacts in voice chat window and @john-preston changed it like that. Sadly the design is not adapted for such button layouts.
