### ISSUE TITLE
Video/picture goes to white screen and plays in background when clicked on

### ISSUE THREAD

**Issue by LogicalityDog** [telegramdesktop/tdesktop#25854]
### Steps to reproduce

1. Open any chat (group or personal)
2. Clicking on a photo or video results in a white screen. Videos will play audio in the background.

### Expected behaviour

Video or picture will enlarge.

### Actual behaviour

White screen
![image](https://user-images.githubusercontent.com/88037788/217317355-91da8c21-5df2-482f-b57d-7d70d77f7699.png)

### Operating system

Windows 11 Pro

### Version of Telegram Desktop

4.5.3 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz try downloading latest official static beta (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by LogicalityDog** [comment]
Re-install may have fixed it, I will post here again if the issue happens again.
