### ISSUE TITLE
Flatpak Telegram oppening multiple instances of the app

### ISSUE THREAD

**Issue by raspin0** [telegramdesktop/tdesktop#25855]
### Steps to reproduce

1. Install Telegram via Flatpak
2. Open telegram through the app launcher 
3. Do it again, multiple times

### Expected behaviour

Telegram window opens from system tray.

### Actual behaviour

New instance of telegram desktop is launched. (there are two telegrams running)

### Operating system

Deepin 20.8

### Version of Telegram Desktop

 4.6.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
ensure you have flatpak not older than 1.14.0

**Comment by raspin0** [comment]
Just ran an update, the latest version shipped is Flatpak 1.10.7. If the issue is caused by an outdated package, I believe the issue can be closed and I have to wait for distribution to update the package.
