### ISSUE TITLE
The window is still stick with  the mouse cursor when move it  only if click again in mouse . 

### ISSUE THREAD

**Issue by gakramx** [telegramdesktop/tdesktop#25857]
### Steps to reproduce

- Open telegram window for chat 
- Click on title bar  to see Change in  mouse cursor  to moving cursor  
- Move the window and release the mouse button to let the window

### Expected behaviour

Let the window and restore the mouse cursor to normal state when release the mouse button.

### Actual behaviour

- Moving cursor and window still not released when release the mouse button only after click on mouse again .

### Operating system

Operating System: Arch Linux KDE Plasma Version: 5.26.5 

### Version of Telegram Desktop

4.5.3

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
#25126
