### ISSUE TITLE
Telegram Calling screen stuck while sharing my screen

### ISSUE THREAD

**Issue by rekarromar** [telegramdesktop/tdesktop#25868]
### Steps to reproduce

when i share my screen

### Expected behaviour

My calling screen should not stuck or lag

### Actual behaviour

nothing happens instead, it remains like that

### Operating system

Windows 11

### Version of Telegram Desktop

4.6.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz, open task manager when telegram freezes, then right click over telegram -> create dump and send to https://t.me/preston
