### ISSUE TITLE
A malposition of the thumbnail in the taskbar

### ISSUE THREAD

**Issue by WilliamK7** [telegramdesktop/tdesktop#25860]
### Steps to reproduce

1. Enter the local passcode interface
2. Minimize TG
3. See the thumbnail malpositioned

Got a video for this btw.

https://user-images.githubusercontent.com/82304956/217423929-d93789fe-775b-4e3e-a0ca-2b85e3b8dee3.mp4

### Expected behaviour

See this

![image](https://user-images.githubusercontent.com/82304956/217421869-cf011e10-0379-4257-a2ed-ee7404334fe5.png)

### Actual behaviour

See this

![image](https://user-images.githubusercontent.com/82304956/217422225-e395eba7-b1d1-4438-96bb-c5cc053366d1.png)

### Operating system

Windows 10 Pro 19045.2546

### Version of Telegram Desktop

4.6.1 x64

### Installation source

Static binary from official website

**Comment by WilliamK7** [comment]
Maybe it's a bug of Windows? I'm not sure😂

**Comment by john-preston** [comment]
@WilliamK7 Maybe. I don't do anything specific there, I think. I don't know what this depends on :(

**Comment by CurtisWong458** [comment]
> @WilliamK7 Maybe. I don't do anything specific there, I think. I don't know what this depends on :(

Has the new version 4.6.2 not been pushed yet?

**Comment by WilliamK7** [comment]
> @WilliamK7 Maybe. I don't do anything specific there, I think. I don't know what this depends on :(

OK, it's a small problem.😅

**Comment by WilliamK7** [comment]
> Has the new version 4.6.2 not been pushed yet?

@CurtisWong458 @john-preston It seems that the macOS push failed.

Anyway, I'll close the issue.
