### ISSUE TITLE
пошел нахуй долбоеб который это пилит

### ISSUE THREAD

**Issue by gomep342** [telegramdesktop/tdesktop#25864]
### Steps to reproduce

Как можно было превратить идеальный мессенджер за год в такое уебанское глючное говнище?

### Expected behaviour

Пошел нахуй

### Actual behaviour

Пошел нахуй

### Operating system

Пошел нахуй

### Version of Telegram Desktop

Пошел нахуй

### Installation source

Static binary from official website

### Logs

```shell
Пошел нахуй
```

**Comment by john-preston** [comment]
🥰🥰

**Comment by kravandir** [comment]
@john-preston че 🥰🥰? Правь давай долбоеб

**Comment by ilya-fedin** [comment]
@kravandir expected and actual behavior match

**Comment by nikolaikolosov** [comment]
@gomep342, @kravandir reported and blocked.

**Comment by D13410N3** [comment]
Works as expected, nothing to fix

**Comment by glitchcore** [comment]
LGTM

**Comment by gris-gris** [comment]
GitHub support notified about aggressive and inappropriate behavior.

**Comment by nesesarius** [comment]
>aggressive and inappropriate 
but absolutely suitable

**Comment by ch3rn1k** [comment]
😯😯

**Comment by ilyamodder** [comment]
> GitHub support notified about aggressive and inappropriate behavior.

@gris-gris душнила

**Comment by myslivets** [comment]
https://user-images.githubusercontent.com/60743585/218121698-9bfe7ef0-20cf-4d37-a86b-342fc6c5c11a.mp4

**Comment by Playez** [comment]
> rtjkugtihjrtlkhlr.mp4
АПВПФРФГ

АРОАЛРЬЫВПЬЬЬДЛЬПОЬПЛДОРЛАПРВОПТВПТЫВОЛЛ
РОВЛПДПЬВЛРТЫРВАБЮЫВА

АРВЛЛКЕУКДЛВПООРРДЫЛРЬАЛРДЛАОДЫ

**Comment by grishka** [comment]
Если вам не нравятся существующие клиенты для телеграма, напишите свой, который вам будет нравиться. Я вот когда-нибудь это сделаю. Нескоро, потому что у меня есть более приоритетные и более полезные проекты, но когда-нибудь обязательно.

**Comment by bladeinblood** [comment]
Ладно

**Comment by inspiredx** [comment]
> GitHub support notified about aggressive and inappropriate behavior.

мать свою нотифай)

**Comment by sTiKyt** [comment]
> Если вам не нравятся существующие клиенты для телеграма, напишите свой, который вам будет нравиться. Я вот когда-нибудь это сделаю. Нескоро, потому что у меня есть более приоритетные и более полезные проекты, но когда-нибудь обязательно.

Теперь даже смс аутентификации нету для 3rd party

**Comment by markcda** [comment]
> > Если вам не нравятся существующие клиенты для телеграма, напишите свой, который вам будет нравиться. Я вот когда-нибудь это сделаю. Нескоро, потому что у меня есть более приоритетные и более полезные проекты, но когда-нибудь обязательно.
> 
> Теперь даже смс аутентификации нету для 3rd party

Зато есть почта

**Comment by grishka** [comment]
> Теперь даже смс аутентификации нету для 3rd party

А что обязывает использовать свой собственный api_id в своих клиентах? 😏🌚

**Comment by ilya1st** [comment]
да, память оно кушает на макос нормально так

**Comment by nikolaikolosov** [comment]
> @gris-gris душнила
> мать свою нотифай)

GitHub support notified about aggressive and inappropriate behavior.

**Comment by ilyamodder** [comment]
@nikolaikolosov заплачь ещё

**Comment by nikolaikolosov** [comment]
@ilyamodder бан и ещё один репорт. Встретимся в суде, ха!

**Comment by ilyamodder** [comment]
@nikolaikolosov зарепорть сразу весь раздел issues, ведь недостатки в проекте кого-то могут задеть, это так inappropriate и aggressive

**Comment by nikolaikolosov** [comment]
@ilyamodder я репорчу только тех, кто пишет в ишью оскорбления вместо предметной и конструктивной критики.

**Comment by kravandir** [comment]
> GitHub support notified about aggressive and inappropriate behavior. 

Сыр кухарки спок,

**Comment by john-preston** [comment]
@gomep342 @kravandir а чего конкретно бесит? по пунктам.

**Comment by rkolchakov** [comment]
😱

**Comment by Extazystas** [comment]
> @ilyamodder @inspiredx 
> 
> GitHub support notified about aggressive and inappropriate behavior.
> 
> 

Popłac liarva

**Comment by kinton** [comment]
> @gomep342 @kravandir а чего конкретно бесит? по пунктам.

В Manjaro на KDE все картинки в виде пикселей ![IMG_20230211_112019_999.jpg](https://user-images.githubusercontent.com/14817153/218248164-b69cf7a3-2f60-44fb-a691-ae354cd95b07.jpg)

**Comment by ilya-fedin** [comment]
@kinton это баг KDE, см. #25126, его никто так и незарепортил им

**Comment by baterflyrity** [comment]
Since 8 year finally contact avatars have been added. Absolutely sure other bugs, lag and memory issues (caused by paid features) will have been fixed up to 2040 year (when tg might be already dead).

**Comment by Dubzer** [comment]
> > Теперь даже смс аутентификации нету для 3rd party
> 
> А что обязывает использовать свой собственный api_id в своих клиентах? 😏🌚

Лютый антифрод для официальных кредов

**Comment by grishka** [comment]
> Лютый антифрод для официальных кредов

А как он проявляется?

**Comment by Attorelle** [comment]
я угараю мужики

**Comment by Petrprogs** [comment]
> @gomep342 @kravandir а чего конкретно бесит? по пунктам.

Не тратьте свое время)

**Comment by Choochmeque** [comment]
> да, память оно кушает на макос нормально так

Для мака есть свой клиент.

**Comment by 2trvl** [comment]
@Dubzer а ты вообще кто

**Comment by Viiprogrammer** [comment]
Пробовали включить выключить?

У меня так на лине с мышкой если отключить, то после подключения клиент ее не видит, у знакомого на федоре тоже, но перезапуск помогает

![hello-it-have-you-tried](https://user-images.githubusercontent.com/17622604/218307706-6a9b509d-e719-46b7-a744-e47d59432bac.gif)

**Comment by Alex0nder** [comment]
**Факты о телеграме, почему он стал помойкой:**

- Старый клиент = вечные страдания. Попробуйте поставить телегу на новый комп или телефон, а потом быстро открыть и прочитать сообщение.
- Вылетает, ошибка клиента (когда места не хватает. Неужели с ноутом 125 гб мне важно следить за пространством для телеги?)
- Звонки лагают, а показать экран больше похоже на управление самолетом. Приходится, реально часто заходить в ватсап, чтобы позвонить или гугл мит, чтобы показать экран.
- Реклама и спамеры. Даже с хваленой настойкой приватности тебе может написать кто угодно, если ты в чате или группе засветился. Хотел бы рекламу, сидел бы в вайбере.
- Анимации, эмодзи, стикеры, аудио. Спасибо конечно за них, но в когда твоя переписка состоит из стикеров, видео и аудио, как думаете, сколько весит телеграм? (только не говорите, что не хочешь, не грузи. Надеюсь для вас существует отдельный котел, где вы загружаете весь интернет, например ютуб видео, а потом удаляете чтоб загрузить что-то еще)
- Вечные обновления, когда угодно, без расписания. Я раньше думал такой прикол существует только в макрасофт.
- Группы в группе - рекурсивная помойка.
- Регистрация только по телефону, добро пожаловать, майор. Не удобно, особенно когда страну меняешь на долго. или еще лучше, когда потерял номер телефона. Если не смог восстановиться, любой кто купит твой номер, будет в твоей книжке / контактах онлайн. Ссаная дичь.
- Твой друг использует телеграмм. (Ты специально назвал контакт "Спам", "не брать", "мошенник" или там ненужный контакт. Обязательно, серьезно, надо прислать уведомление, что твой контакт использует телеграм, будто мне это надо.
- Веб версия, у кого 27 дюймов, поймет боль.
- Приватность. Где хваленая защита? Где authenticator или там серекретные ключи как в крипте. Надеюсь web 3.0 вас поимеет.
На фоне всего этого душевного крика, телега нравится, многие вещи прикольные, но с каждым годом все меньше.

Даже слак, который был предназначен для работы, в разы удобнее, так как он сознательно делался как крупная платформа, а не простой мессенджер. Телеграм пытается быть простым месенджером, но при этом по априори пытается в себя впихнуть все что вздумается, что больше похоже на порно.

**Comment by djirik** [comment]
Немного резковато, но думаю, что команде разработчиков стоит прислушаться

**Comment by ilya-fedin** [comment]
> У меня так на лине с мышкой если отключить, то после подключения клиент ее не видит, у знакомого на федоре тоже, но перезапуск помогает

И опять #25126 :(

**Comment by 2trvl** [comment]
@Alex0nder довольно субьективно и для регистрации есть теперь Fragment с его анонимными номерами

я бы сказал, что телеграм стремительно начал расти и вбирать в себя все больше новых функций, потому что деньги заканчиваются и нужно их откуда-то брать

команда не была к этому готова, от чего имеем многочисленные баги в андройд клиенте, низкую производительность анимоджи, долгую загрузку

по багам, которые меня давно бесят
* галерея фотографий в отложенных постах перемешивается, не совместимости между Telegram Desktop и Telegram Android, происходит инверсия и последняя фотка становится первой
* в Telegram Android при скачивании всех документов полоса загрузки делится на равное количество промежутков, но никогда не заполняется до 100 (например, 4 документа, кусочки по 25%, полоса всегда идет с 0 до 25, хоть это 2 или 3 документ)
* проблема со стикерпаками серверная уже давно, ограничение по размеру просто не работает, если указано 250кб, то даже 249кб не всегда прокатывает, нужно урезать с запасом до 230кб или типа того, также не прозрачная ситуация с видеоаватарами, как я помню, лимит здесь 8мб, но он тоже не работает (тут не проблема с MB/MiB)
* на Telegram Desktop с недавнего времени при пересылке более 60 сообщений, они как и фотографии в отложенной галерее перемещиваются, первое сообщение идет с конца
* замечал серверную ошибку, что для канала, у которого уведомления выключены всегда, они неожиданно включаются, но такое было всего пару раз

вроде все, если еще вспомню, обновлю

**Comment by avastium** [comment]
> * Регистрация только по телефону, добро пожаловать, майор.

а потом жалуешься что спамеров много

Кстати звонки в телеграме это действительно кошмар, иногда просто зависают на обмене ключами и все.

**Comment by grishka** [comment]
Ну так потому что кое-кто кое-кого уволил без попыток разобраться в ситуации, а признать свою неправоту и извиниться гордость не позволяет.

**Comment by HellYeah1337** [comment]
> > Если вам не нравятся существующие клиенты для телеграма, напишите свой, который вам будет нравиться. Я вот когда-нибудь это сделаю. Нескоро, потому что у меня есть более приоритетные и более полезные проекты, но когда-нибудь обязательно.
> 
> Теперь даже смс аутентификации нету для 3rd party

Хохла спросить забыли

**Comment by Viiprogrammer** [comment]
> я бы сказал, что телеграм стремительно начал расти и вбирать в себя все больше новых функций, потому что деньги заканчиваются и нужно их откуда-то брать

Вроде раньше его содержали с денег дурова, которых хватило бы наверное содержать его не один десяток лет)

Однако ясно что так продолжатся вечно не может, однако качество тех обновлений которые впиливаются в клиенты для премиум юзеров, достаточно сомнительное например по перформансу. Причем чувствуют это, как обычные пользователи, так и пользователи которые покупают премиум подписку.

> команда не была к этому готова, от чего имеем многочисленные баги в андройд клиенте, низкую производительность анимоджи, долгую загрузкукоманда не была к этому готова, от чего имеем многочисленные баги в андройд клиенте, низкую производительность анимоджи, долгую загрузку

Перед тем как что-то делать наверное нужно подготовиться? А не выкатывать быстрее, часто возникает ощущения, что приложения не тестируют в принципе

-------

Если говорить об телеграме в целом, то все хорошо когда все хорошо) А, как только что-то не так,  Паша выключает реакции в своем канале встречая критику 😁 . 

По поводу того что Bots API, который фактически изначально представлялся, как киллер фича мессенджера:

На текущий момент мы имеем там кое-какой референс, написанный будто полностью от руки и отсутствующую схему, насчет которой говорят, мол юзайте схему TL-schem'у от юзер апи, ведь у нас Bots API это просто врапер над tdlib. И это еще не говоря о выкатывании в ботс апи, вещей вроде [доступа к реакциям](https://t.me/tdlibchat/35949) (дата сообщения 30.01.2022) и прочего, это так в довесок. Взять вот премиум эмодзи, которые внезапно фигурируют в оф ботах.

Хэндлинг ошибок на уровне поиска слова в строке, так как нет ни кодов, ни какого-то способа опознания ошибок на вроне машины, при этом эти сообщения еще и меняются, иногда.

Лимиты, вот это наверное достаточно больная тема. На вопросы о лимитах, обычно можно получить ответы вроде:

- «вам нужно просто ловить 429 и ждать, больше вам знать не надо» 
- «как только будут проблемы, пишите нам», нет никаких данных о них

И вроде как считают что если разработчики будут знать их, значит они будут их обходить. Вот например [внезапно мы узнаем ](https://t.me/BotTalk/267907)от [Bot support](https://t.me/BotSupport) что лимит [sendContact](https://core.telegram.org/bots/api#sendcontact) 2-3 вызова в минуту, но при этом нет ни слова об этом где-то еще.

Написание ботов, часто похоже на разработку методом тыка, потому что даже тот референс не покрывает описанием некоторые параметры, что касается и описаний в ченжлогах, когда бывает надо тупо пробовать, чтобы узнать, как же надо и как правильно.

Да конечно, можно написать в чат того же TDLib и ждать маны небесной, пока например [@levlam](https://t.me/levlam) не осветит вопрос, или не выкинет что-то вроде [такого] (https://t.me/tdlibchat/62793), а потом [узнать](https://t.me/tdlibchat/62804) что `chat_id` может внезапно стать не равен `user_id` в приватном чате, и такое обновление не ситается breaking, так как нигде не написано что они равны в приватном чат, но ведь нигде не написано и того что это может изменится в будущем, отлично! Давайте [посмеемся вместе](https://t.me/tdlibchat/62807)!

**Comment by baryshkov** [comment]
сап телеграммыч, пишу в эпичном треде.

Вообще всё познается в сравнении и десктоп клиент еще ничо, вы бы видели как плохо работает нативный макос клиент, это просто что-то с чем-то.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Несмотря на обилие токсичности в этом топике у меня не получается вспомнить хоть один известный клиент которому бы требовалось для корректной работы пересборка Qt с [нагромождением патчей](https://github.com/desktop-app/patches). Но даже это ещё не настолько критично.

Последние (!) пять лет в TDesktop не могут исправить баг кэширования, который убивает систему. Для этого нужно чтобы ОС и программа стояли на одном HDD-диске (и не обязательно старом). Пока винда нагружает диск (например открыт проводник с RAW-фотками) достаточно открыть и скролить в клиенте канал с тяжёлым контентом - вуаля. Хоть бы BSOD появился, но ничего не происходит.

Даже великий и ужасный Electron не позволяет такой дерзости. От него просто начинает всё тормозить, но не виснет намертво всю систему.

Поверьте мне на слово, я проверил это много раз на всевозможных лаптопах и системниках. Не пытайтесь ничего изменить, всё слишком поздно.

[It doesn't matter.](https://www.urbandictionary.com/define.php?term=It+doesn%27t+matter)

**Comment by ilya-fedin** [comment]
> Несмотря на обилие токсичности в этом топике у меня не получается вспомнить хоть один известный клиент которому бы требовалось для корректной работы пересборка Qt с [нагромождением патчей](https://github.com/desktop-app/patches).

Эти патчи не от хорошей жизни, Qt то и дело бажит и регрессирует, на Qt просто-напросто больше нет опенсорсного софта такого масштаба, чтобы попасть на эти баги (хотя, в принципе, Krita тоже патчит Qt), а проприетарный наверняка тоже патчит Qt.

**Comment by NitMrAnderson** [comment]
Я знаю один хороший клиент телеги, element называется

**Comment by grishka** [comment]
> Я знаю один хороший клиент телеги, element называется

Он на электроне. На электроне ничего "хорошим" не может быть по определению.

(к тому же это клиент для matrix, который сам по себе кривой, не умеет даже одновременно картинку и текст отправлять)

**Comment by NitMrAnderson** [comment]
> > Я знаю один хороший клиент телеги, element называется
> 
> Он на электроне. На электроне ничего "хорошим" не может быть по определению.
> 
> (к тому же это клиент для matrix, который сам по себе кривой, не умеет даже одновременно картинку и текст отправлять)

Ну по факту, отправлять изображение и текст одним сообщением не то что бы прям необходимо, разными тоже вполне норм себе. В чем его "кривость" заключается, я лично хз, вроде норм работает. Да и матрикс хоть и на электроне жрет ресурсов не сильно больше, чем телега =)

**Comment by Amphyby** [comment]
А в чем он не прав? Понапихали emodji со стикерами везде и всюду, и собранный из офиц сорцов ТГ-десктоп крашится едва напоровшись на стикер в имени участника чата.

**Comment by ilya-fedin** [comment]
> собранный из офиц сорцов ТГ-десктоп

А на офсборке хоть проверялось? Может собран не так. С офсборки можно крашрепорт отправить.
