### ISSUE TITLE
Right panel toggle on detached window also triggers the parent window

### ISSUE THREAD

**Issue by decorator-factory** [telegramdesktop/tdesktop#25871]
### Steps to reproduce

1. Open a chat in a new (detached) window
2. Open another chat in the parent window
3. Make sure the chat list in the parent view is not minimized (i.e. you can see message previews on the left)
4. Press the `[ |]` button in the child window:
![image](https://user-images.githubusercontent.com/42166884/217930669-91888294-73c5-40e0-8c01-dca74a9e198e.png)

### Expected behaviour

The group info panel is only toggled on the detached window

### Actual behaviour

The group info panel is toggled on both windows

https://user-images.githubusercontent.com/42166884/217931216-6c5e8a90-d1e9-4fa2-b655-b02bf4f0e76d.mp4

### Operating system

Manjaro Linux, Xfce 4.18

### Version of Telegram Desktop

v4.6.2

### Installation source

Static binary from official website

**Comment by rasputyashka** [comment]
in addition to that, if your chat list is minimized you can reproduce kinda the same behavior (the [  | ] button toggles in the outer chat as well, if you press the inner one. But nothing happens tho) HOWTO:

1. make sure you chat list is minimized.
2. open another chat in a new window.
3. click that [  | ] button in the outer chat.
4. click the [  | ] button in the inner chat two-three times.

I am not sure it is was intended.

**Comment by john-preston** [comment]
@rasputyashka This wasn't intended, just didn't find time to properly implement this yet :(

**Comment by decorator-factory** [comment]
This is still a problem
