### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Mesilin** [telegramdesktop/tdesktop#25886]
### Is your feature request related to a problem?

My friends forward me messages from groups and channels whose content I don't like.

### Describe the solution you'd like

I want to be able to create a personal group blacklist. So that if someone tries to forward me a message from such a group, I will not receive it.

### Describe alternatives you've considered

no alternative ideas

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
