### ISSUE TITLE
Telegram Desktop Flatpak Client not opening tg:// links.

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [telegramdesktop/tdesktop#25881]
### Steps to reproduce

1. Install telegram via Flatpak
2. Open site [https://t.me/rozetked](url) (or any other of course. It isn't ad :))
3. Click View in Telegram

### Expected behaviour

Telegram window should be opened (or focused, if already open) and there should be this chat.

### Actual behaviour

Nothing happens. Also, if Telegram window is open, chat is not being viewed on it. 
I checked `xdg-mime default x-scheme-handler/tg`. It's set to `org.telegram.desktop.desktop`.

### Operating system

Fedora 37 (6.1.10)

### Version of Telegram Desktop

4.6.2

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
> Telegram window should be opened (or focused, if already open) and there should be this chat.

I don't think it will be focused if you're using Wayland, it's still not established, IIRC it's not supported from Firefox side when clicking links and I don't know about the state of Chromium at all.

> Also, if Telegram window is open, chat is not being viewed on it.

You mean not focused or chat is not open even if you manually focus the window?

If you're using Firefox, check its association settings, it has custom ones and it's a widespread thing when people were choosing tdesktop binary manually and then that custom association didn't work of course.

**Comment by muhammadyusuf-kurbonov** [comment]
![image](https://user-images.githubusercontent.com/45625440/218317659-0e2ab623-73b3-480b-8f47-f2c56cc64d54.png)
There are settings of Firefox. Also, Chrome (and chromium) doesn't work too.

**Comment by ilya-fedin** [comment]
@muhammadyusuf-kurbonov please answer the question

> You mean not focused or chat is not open even if you manually focus the window?

**Comment by muhammadyusuf-kurbonov** [comment]
Even I manually focus, it doesn't goto chat. I use Wayland, so not focusing automatically is known issue

**Comment by muhammadyusuf-kurbonov** [comment]
It doesn't receive the handle event at all.

**Comment by ilya-fedin** [comment]
what will happen if you try to open tg:// link manually via xdg-open?

**Comment by muhammadyusuf-kurbonov** [comment]
```
[muhammadyusuf@fedora ~]$ xdg-open tg://resolve?domain=rozetked
gio: tg://resolve?domain=rozetked: The specified location is not supported
[muhammadyusuf@fedora ~]$ xdg-open tg://
gio: tg://: The specified location is not supported
[muhammadyusuf@fedora ~]$ xdg-open tg://resolve?domain=rozetked
gio: tg://resolve?domain=rozetked: The specified location is not supported
[muhammadyusuf@fedora ~]$ 
```

**Comment by muhammadyusuf-kurbonov** [comment]
It can't find telegram?

**Comment by ilya-fedin** [comment]
```
echo $XDG_DATA_DIRS
echo $XDG_DATA_HOME
```

**Comment by muhammadyusuf-kurbonov** [comment]
![image](https://user-images.githubusercontent.com/45625440/218318157-635a7521-413d-4ccb-ba36-4df7b6d9916e.png)

**Comment by ilya-fedin** [comment]
hmm, try
```
update-desktop-database
update-mime-database
```
and try xdg-open again

**Comment by muhammadyusuf-kurbonov** [comment]
```
[muhammadyusuf@fedora ~]$ update-desktop-database
The databases in [/home/muhammadyusuf/.local/share/flatpak/exports/share/applications, /var/lib/flatpak/exports/share/applications, /usr/local/share/applications, /usr/share/applications] could not be updated.
[muhammadyusuf@fedora ~]$ update-mime-database
Usage: update-mime-database [-hvVn] MIME-DIR
```

**Comment by muhammadyusuf-kurbonov** [comment]
And 
```
[muhammadyusuf@fedora ~]$ grep x-scheme-handler/tg -r /var/lib/flatpak/exports/share/
/var/lib/flatpak/exports/share/applications/mimeinfo.cache:x-scheme-handler/tg=org.telegram.desktop.desktop;
```

**Comment by muhammadyusuf-kurbonov** [comment]
Oh, sorry. Should I do with `sudo`?

**Comment by ilya-fedin** [comment]
Well, maybe there's some .desktop file in `/home/muhammadyusuf/.local/share/applications` of other installation of tdesktop and the corresponding mimeinfo.cache?

**Comment by muhammadyusuf-kurbonov** [comment]
It was earlier an AppImage version. And removed it manually. Because AppImage version doesn't exists for a long time

**Comment by ilya-fedin** [comment]
There never were an AppImage, maybe you meant the static binary? If yes, it still exists and could be downloaded from https://desktop.telegram.org or from GitHub releases.

**Comment by muhammadyusuf-kurbonov** [comment]
Yes, it is. Sorry for missnaming

**Comment by ilya-fedin** [comment]
What does `gio mime x-scheme-handler/tg` return?

**Comment by muhammadyusuf-kurbonov** [comment]
```
[muhammadyusuf@fedora ~]$ gio mime x-scheme-handler/tg
No default applications for “x-scheme-handler/tg”
```

**Comment by ilya-fedin** [comment]
It's quite weird, glib doesn't see any handler while xdg-mime does, I don't really know what else to suggest, recommend to ask glib developers.
https://gitlab.gnome.org/GNOME/glib/-/issues
