### ISSUE TITLE
Can't scroll down to the lastest message when clicking comments on channel

### ISSUE THREAD

**Issue by ZeroLin-dev** [telegramdesktop/tdesktop#25889]
### Steps to reproduce

Take https://t.me/TestFlightCN/15941 for example, click comments.

### Expected behaviour

Scroll down to read all the unread messages

### Actual behaviour

It will always stuck somewhere. 42 unread messages for me. But I cannot scroll down anymore. What I can do is click the arrow logo to directly navigate to the bottom.
![1](https://user-images.githubusercontent.com/65212736/218438290-e7816738-4be8-414d-9ae3-7a34ada65d7c.jpg)

### Operating system

Windows 11, ver 22623

### Version of Telegram Desktop

4.6.2

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
4.6.3, windows 10, same. This issue is appears in early January.

**Comment by Neurotoxin001** [comment]
4.9.1 still have it
better test it in large channels like https://t.me/+NW9tienVQI02MWU6

**Comment by VeL1K007** [comment]
4.10 same as well, I had this error for a very long time

**Comment by john-preston** [comment]
I hope I've fixed it for the next version.
