### ISSUE TITLE
Chat messages font is too small to read 

### ISSUE THREAD

**Issue by Yanpas** [telegramdesktop/tdesktop#25885]
### Steps to reproduce

Open a long post on a desktop

### Expected behaviour

Font at least as large as on twitter website. I'm fine with buttons and other elements' font size. But reading longreads is pain

### Actual behaviour

The font is too small, I have to scale app 25% more, to 150% (instead of 125% in Windows settings). This makes interface too big

### Operating system

Windows 11

### Version of Telegram Desktop

4.5.3

### Installation source

Microsoft Store

**Comment by ilya-fedin** [comment]
#90
