### ISSUE TITLE
Telegram crash when clicking back button of archived chat

### ISSUE THREAD

**Issue by IbarakiKasen** [telegramdesktop/tdesktop#25882]
### Steps to reproduce

1. Launch telegram desktop
2. Click "archived chats"
![img](https://user-images.githubusercontent.com/24918484/218289627-34250bf9-b4e1-4695-9a07-d63161cfb0d9.png)
3. Click "back" with both left and right mouse button (like minesweeper chording)
![img](https://user-images.githubusercontent.com/24918484/218289644-8761ad69-8694-4ec3-b124-993c4a342951.png)

### Expected behaviour

Go back to non-archived chat list

### Actual behaviour

Telegram crashs and quits

### Operating system

Windows 10.0.19045.2546

### Version of Telegram Desktop

4.6.2 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.
