### ISSUE TITLE
Font display is jagged

### ISSUE THREAD

**Issue by iivmok** [telegramdesktop/tdesktop#25880]
### Steps to reproduce

Updating to the newest version 4.6.2

### Expected behaviour

Fonts display as smooth as before

### Actual behaviour

Fonts seem to be rendered weirdly, as if they're scaled after or before rendering with nearest neighbour scaling.

I realize the scaling is different, but i think in the new interface none of the scaling options from 200% to 300% matched previous 300% I had. I am running a large 4k display at 200% scaling.

Top is newest version,
Bottom is downgraded to 4.5.3
Capital "S" and loop on "g" I think are most noticeable
![image](https://user-images.githubusercontent.com/5609872/218272615-bf5f9953-8bef-4fbf-85c0-748f0c9880a4.png)
![image](https://user-images.githubusercontent.com/5609872/218272669-10bdb946-00a1-42ee-8848-6cc28a3e138d.png)

Not sure if github compressed the image, here's an imgur upload: https://i.imgur.com/uPaNAKA.png

### Operating system

Windows 10 22H2

### Version of Telegram Desktop

4.6.2

### Installation source

Static binary from official website

**Comment by iivmok** [comment]
Not sure if github compressed the image, here's an imgur upload: https://i.imgur.com/uPaNAKA.png

**Comment by iivmok** [comment]
I realize the scaling is different, but i think in the new interface none of the scaling options from 200% to 300% matched previous 300% I had. I am running a large 4k display at 200% scaling.

**Comment by ilya-fedin** [comment]
Qt uses Direct Write font engine instead of GDI when its High-DPI scaling is active, I don't think anything could be done here, you have to get used to the new font rendering.

**Comment by ilya-fedin** [comment]
And it seems you're right, Qt scales the text after rendering and that's the reason it changes the font engine and disables hinting.
https://github.com/qt/qtbase/commit/6a6c14626df1ccf7838f0b8dd82bc88a1c637d04

Sadly, nothing could be done here.
