### ISSUE TITLE
Build error on Raspbian Jessie

### ISSUE THREAD

**Issue by mdoni** [telegramdesktop/tdesktop#2588]
I'm trying to install telegram-desktop on raspbian-jessie (RPi 3) following [this](https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-cmake.md) guide. All libraries was installed properly (except libunity-dev, which it seems to be a Unity library), and I am able to reach the last paragraph of this guide ("Building Telegram Desktop"). Building stops when I try to run `gyp/refresh.sh`, which returns the following 
`gyp: Call to 'pkg-config 2> /dev/null --cflags dee-1.0' returned exit status 1 while in Telegram.gyp.`
Then the out/Release folder is not created and I am unable to finalize the building.

### Steps to reproduce
1.  Install all the libraries following [this](https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-cmake.md) guide
2. building stops when trying to run `gyp/refresh.sh`in TBuild/tdesktop/Telegram

### Expected behaviour
Creation of out/Release folder in order to run `make`

### Actual behaviour
Nothing happens.

### Configuration
Raspbian GNU/Linux 8 (jessie)

**Version of Telegram Desktop:**
0.10.19

**Comment by alnour-altegani** [comment]
same error in elementry os 0.4

**Comment by auchri** [comment]
Install libdee #3049
