### ISSUE TITLE
Bad animation when closing the chat room

### ISSUE THREAD

**Issue by Pushkin31** [telegramdesktop/tdesktop#25890]
### Steps to reproduce

1. Open any chat room
2. Make the sidebar narrow (change its width)
3. Close the chat with the "back" button by any means (the "ESC" key or the "back" button on the mouse)

### Expected behaviour

Smooth chat exit animation

### Actual behaviour

Broken animation with transparent sidebar background (you can see the window behind the Telegram client).
The closing animation of the dialog, and with it the bug - appeared with version 4.3.3. Previously animation of closing was absent.

In the video below, as an example, behind the telegram window the "thunar" guide was open.

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/35974828/218526220-73ee571c-11ef-48ec-b111-a4162fff010d.mp4

</details>

### Operating system

Arch linux

### Version of Telegram Desktop

4.6.2

### Installation source

Static binary from official website

**Comment by Alexey71** [comment]
I have the same bug

**Comment by Pushkin31** [comment]
The problem is still relevant

**Comment by Pushkin31** [comment]
The problem is still relevant
