### ISSUE TITLE
Mouse scroll is broken 2: Electric boogaloo

### ISSUE THREAD

**Issue by grepwood** [telegramdesktop/tdesktop#25897]
### Steps to reproduce

1. Install Kubuntu 22.04 LTS (this is not my computer)
2. Install Telegram Desktop from Snap
3. Get disappointed that scroll doesn't work and even more disappointed that noob-friendly Linux distros can't hold a candle to Windows 98
4. Research the topic and find out through https://github.com/telegramdesktop/tdesktop/issues/17254 that something is really fishy because your main computer has Gentoo with LXQt with Xorg on it. That computer is configured with extreme prejudice to never enable any Wayland functionality and you know what? Scrolling works flawlessly. So it's not an Xorg issue it seems.

### Expected behaviour

It should scroll the contact list.

### Actual behaviour

Doesn't scroll. Functionality on par with Windows for Workgroups

### Operating system

Kubuntu 22.04 LTS

### Version of Telegram Desktop

4.6.1

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Yeah, it's not a Xorg issue, it's a Qt issue in X11 backend, please don't create duplicates

**Comment by grepwood** [comment]
>Qt issue in X11 backend
Not on Gentoo. I wouldn't put it past suspicion that the problem may stem from the fact that Snap could be using a completely different version of Qt than the rest of the system. I've seen my fair share of cat fights between Boost versions and Qt versions.

**Comment by ilya-fedin** [comment]
@grepwood the issue is hardware-dependent by its nature, you can find the details in Qt bug report comments (see the pinned issue for Qt bugreports)

**Comment by grepwood** [comment]
>>https://bugreports.qt.io/browse/QTBUG-98720
>after migrating from Qt 5.15.2 to Qt 6.2

That's pretty unsurprising. Qt6 is too new, things are guaranteed to be broken. I wouldn't personally move anything there until they get a mid-life crisis version for 6, like 4.10 was for Qt4.

I'll try to apply the suggested fix from https://github.com/telegramdesktop/tdesktop/issues/17254#issuecomment-1198891921 when time permits but in the meantime, is there any way to get a version of tdesktop from Snap that's linked against Qt5?

**Comment by ilya-fedin** [comment]
@grepwood no, there's no way. Sadly, Qt 5 is way more bugged on X11 and now that the default Ubuntu session defaults to Wayland, it has sense to prefer better Wayland support over better X11 support
