### ISSUE TITLE
Crashes on Ubuntu 22.04 when trying to switch between accounts

### ISSUE THREAD

**Issue by PejmanGhafouri** [telegramdesktop/tdesktop#25896]
### Steps to reproduce

1. Add at least 2 accounts on your telegram desktop on ubuntu 22.04 (LTS) 
2. switch between your accounts or go to settings tab

### Expected behaviour

Freezed and Closed after clicked on one of your account and reopened with same account, also you can click on settings tab

### Actual behaviour

switch easily between accounts

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> 3.6.1

This version is too old, the current one is 4.6.3
