### ISSUE TITLE
Network connection is not restored after computer is waked up from sleep

### ISSUE THREAD

**Issue by b-s-a** [telegramdesktop/tdesktop#25895]
### Steps to reproduce

1. Run Telegram
2. Be sure Telegram is connected
3. Switch computer to sleep mode
4. Wait for 2-3 hours at least (lower may not cause issue)
5. Be sure Telegram chats are updated (new messages sent and/or received)
6. Wake up computer
7. Check Telegram Desktop chats

### Expected behaviour

Chats should be updated to recent messages as on other devices

### Actual behaviour

Chats stay same as before sleep for about 15 minutes or more sometime.

### Operating system

Ubuntu 22.04.1 LTS x86_64

### Version of Telegram Desktop

4.6.2 and lower

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#16093?

**Comment by b-s-a** [comment]
> #16093?

No. That issue is about UI. My issue is about network connection. I have no any dependence between tray or not. But I check it today.

**Comment by ilya-fedin** [comment]
It has different manifestation across different system, e.g. #17397, isn't yours like that?

**Comment by b-s-a** [comment]
> It has different manifestation across different system, e.g. #17397, isn't yours like that?

Yes, looks like. But no more "connecting..." for few months.

**Comment by ilya-fedin** [comment]
@b-s-a no one said it's fixed

**Comment by b-s-a** [comment]
Hm, why it is closed as completed then?

**Comment by b-s-a** [comment]
I'm unsure. This bug is about connection restore after the sleep. In my case Telegram may restore it itself, but it may took from 2 seconds (rare), tens of minutes (often) and up to few hours (some time). It is fully responsible even it minimized to tray or shown as active window.

**Comment by ilya-fedin** [comment]
Let's treat it the same as #16093 unless we have a proof it's a completely unrelated issue.
