### ISSUE TITLE
Archived chats appear in foders even if the Archived tag is listed in the folder exclusion rule

### ISSUE THREAD

**Issue by kodabb** [telegramdesktop/tdesktop#25891]
### Steps to reproduce

1. Create a folder
2. Add chats to it
3. Archive one of the chat [the chat stays there]
4. Edit the folder property, set Archived in the Exclude filter

### Expected behaviour

Archived chats should not be listed in folders.
OR
Folders should follow the exclusion filter when Archived is set.

Note that this behavior only affect Telegram Desktop, it works as expected on iOS.

### Actual behaviour

The archived chats still appear in folders.

### Operating system

macOS 12.1

### Version of Telegram Desktop

4.6.2

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment]
Manually added chats have priority over exclusion filters, it's intended

**Comment by kodabb** [comment]
@RememberTheAir but then why don't archived chats appear on iOS? Is the bug that archived chats appear in folders at all then?

**Comment by john-preston** [comment]
@kodabb You can make an auto-filling folder with rules, like "include channels and groups, but don't only with unread messages and not archived" — this way archived chats aren't getting in the folder. Additionally you can specify explicitly that you want some chats to be in the folder — you add them in the special list, just separate chats — and they always are in the folder. Also you can select explicitly chats that won't appear in the folder even if they should appear by the "auto-filling" rules.

**Comment by kodabb** [comment]
@john-preston thanks I'll try that, but I still find the different behavior across platforms a bit puzzling

**Comment by RememberTheAir** [comment]
@kodabb yeah you are right, but I think in this case the app that should be fixed is the iOS one, because it's the only client that behaves like that 🤔

**Comment by RememberTheAir** [comment]
Oh, related issue where we discussed this topic before: #8427
