### ISSUE TITLE
Pins disappear inconsistently in groups with topics

### ISSUE THREAD

**Issue by imposeren** [telegramdesktop/tdesktop#25898]
### Steps to reproduce

1. Create a group with 3 topics
2. Pin 2 or 3 messages in each of the topics except first one
3. Go to second topic
4. go to first topic. Pin first message there
5.  Go to the second topic

### Expected behaviour

All the pins are always visible in each topic

### Actual behaviour

Pins are sometimes visible, and sometimes not. Note: I haven't found a consistent way to reproduce it. Looks like it happens randomly

### Operating system

Windows 11 Pro 22H2

### Version of Telegram Desktop

4.6.3

### Installation source

Static binary from official website

**Comment by bhdnjkz** [comment]
Same issue with the desktop version of Telegram on macOS Ventura 13.0.1.
