### ISSUE TITLE
Fullscreen media shortcut also triggers the Search

### ISSUE THREAD

**Issue by ThigSchuch** [telegramdesktop/tdesktop#25909]
### Steps to reproduce

1. Open a Picture, Video or GIF (new media viewer)
2. CTRL + F (Full-screen)

### Expected behaviour

Only full-screen should happen

### Actual behaviour

Media viewer enters full-screen and the opened chat start to search

- PS.
This happens even before the new media viewer

### Operating system

Linux Mint 21.1

### Version of Telegram Desktop

4.6.4 Beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Should be fixed in the next released version.
