### ISSUE TITLE
Close (X) button of telegram windows has a smaller clickable area when maximized

### ISSUE THREAD

**Issue by Calebestofel** [telegramdesktop/tdesktop#25904]
### Steps to reproduce

1. Maximize application's window through maximize button

### Expected behaviour

When maximized, the close window button has a clickable area that extends until the rightmost upper pixel of the display, telegram was doing that normally some versions ago.

### Actual behaviour

Now when the mouse clicks on the rightmost upper corner of the display, to close application, it does not activate the button.

I think this started on v4.6.0

### Operating system

Windows 10

### Version of Telegram Desktop

4.6.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/671b3bc94e22815bf460fbb5408ce6405d09a78c

**Comment by Calebestofel** [comment]
> 

hm this has been closed as completed, but I still get this error. was this implemented on a future version that hasn't yet been released?
