### ISSUE TITLE
Window location restores on wrong monitor when moved maximized

### ISSUE THREAD

**Issue by Matze177** [telegramdesktop/tdesktop#25901]
### Steps to reproduce

1. Maximize application window on monitor A.
2. Move application window (maximized) to monitor B using Windows + cursor-keys.
3. Quit application on system tray.
4. Restart application.

### Expected behaviour

The application should restore maximized on monitor B.

### Actual behaviour

The application restores maximized on monitor A.

### Operating system

Windows 11 Pro, 22H2

### Version of Telegram Desktop

4.6.3 x64

### Installation source

Static binary from official website

**Comment by Matze177** [comment]
Workaround: Leave maximized state before move the window and maximized after moving to the target monitor.

I would guess it's the problem that maximized windows do not have valid size parameters. Switching the application window to normal during shutdown could help on the issue.

**Comment by grinkevich** [comment]
Yes, the issue is still there on the latest Telegram desktop app (Win 10).
Also, this happens even if the monitor is TURNED OFF which is the most frustrating part. So in order to bring it back you need to power up the monitor and drag the window over to the default monitor.

**Comment by Aokromes** [comment]
> Yes, the issue is still there on the latest Telegram desktop app (Win 10). However, few additions to the original issue description:
> 
> 1. This happens even if the monitor is TURNED OFF which is the most frustrating part. So in order to bring it back you need to power up the monitor and drag the window over to the default monitor.
> 2. My Telegram app window is not maximised, just a small&tall window on the left side (like an old ICQ chat 😄 ). But the bug is still randomly there when I close the tray window and open it back.

in fact, you don't need to power on monitor, if you put cursor on the border of monitor you will see resize arrow and allow you to increase size a bit then move telegram.

**Comment by uaiz** [comment]
> I would guess it's the problem that maximized windows do not have valid size parameters. Switching the application window to normal during shutdown could help on the issue.

This actually solve the problem, tested with my 3 monitor setup.
Switch app to not fullscreen, move the window, close it. It will open on the right monitor. Then maximize it and close it again.
The "move" is "detected" only while not fullscreen.
