### ISSUE TITLE
migrate from flatpak to static binary. logout from all account

### ISSUE THREAD

**Issue by procolost** [telegramdesktop/tdesktop#25905]
### Steps to reproduce

cp -r ~/.var/app/org.telegram.desktop/data/TelegramDesktop ~/.local/share/TelegramDesktop
start  ./Telegram

### Expected behaviour

work

### Actual behaviour

welcome screen

### Operating system

fedora 36

### Version of Telegram Desktop

4.6.3

### Installation source

Static binary from official website

**Comment by kinoher** [comment]
lets try reinstall telegram flatpak, then open and wait to full load.
Exit from telegram.
next in terminal

rm -rf $HOME/local/share/TelegramDesktop/   
cp -r $HOME/.var/app/org.telegram.desktop/data/TelegramDesktop $HOME/.local/share/TelegramDesktop
./Telegram -workdir $HOME/.local/share/TelegramDesktop/

**Comment by procolost** [comment]
it's work

**Comment by Aokromes** [comment]
you mean it works? if yes, close the ticket.
