### ISSUE TITLE
Keyboard switcher is ignored after recent update on linux

### ISSUE THREAD

**Issue by esledov** [telegramdesktop/tdesktop#25902]
### Steps to reproduce

Switch keyboard to a language other than English. Type anything.

I am using ibus keyboard switcher with Russian translit layout (m17n). Everything worked as expected before the last update.

### Expected behaviour

Text is supposed to be entered in the national alphabet.

### Actual behaviour

Text is entered in Latin characters.

### Operating system

Pop!_OS 20.04 (Ubuntu-based), Gnome

### Version of Telegram Desktop

4.6.2

### Installation source

Flatpak

**Comment by esledov** [comment]
It worked on 4.6.1 and stopped working on 4.6.2.

I have another machine on Pop!_OS 22.04. On both machines version 4.6.3 of Telegram Desktop is now installed.  

The problem appears on Pop!_OS 20.04, but not on Pop!_OS 22.04. So, it may be related to the version of ibus or something else 20.04 specific. 20.04 is still under Ubuntu LTS.

Pop!_OS 20.04 ibus version 1.5.22
Pop!_OS 22.04 ibus version 1.5.26

(It doesn't work on 3 different 20.04 machines, so, probably, this is not machine-specific).
The keyboard switch works otherwise, including when I enter text into a textarea in Chrome.

**Comment by ilya-fedin** [comment]
Will it work if you downgrade to 4.6.1? Maybe it's a system update installed at the same time?

**Comment by esledov** [comment]
When I downgrade flatpak Telegram desktop version to the lowest available, keyboard switcher functionality is not getting restored.

flatpak update --commit=99007cfe1c65ca45a70a550538d946a6a098da963dc6e7bb01b05ccc60e08295 org.telegram.desktop

I wanted to say that keyboard with TD 4.6.3 works as expected when I install your binary version or snap version. (The icons look terribly pixelated, but it is another story).

So, the problem is with flatpak 1.8.5 on Ubuntu 20.04. 
But not with flatpak 1.12.7 on Ubuntu 22.04.

And regarding flatpak, sometimes I see
Warning: Not exporting file org.telegram.desktop.appdata.xml of unsupported type.
(Not sure whether it makes a difference or not).

**Comment by ilya-fedin** [comment]
> flatpak update --commit=99007cfe1c65ca45a70a550538d946a6a098da963dc6e7bb01b05ccc60e08295 org.telegram.desktop

It seem to be older than 4.6.1, so apparently it's a system update caused this?

**Comment by esledov** [comment]
I am running your binary version installed from tsetup.4.6.3.tar.xz on the same system and the keyboard switch works.

So, something strange is happening with either flatpak version or flatpak itself on Ubuntu 20.04.

**Comment by esledov** [comment]
> It seem to be older than 4.6.1

I tried to downgrade to a couple of commits in between, before going to the last one.

flatpak update --commit=32ed74a60385220ed221fbcd01be928ecd8e8a0f63521c98b938fa0ddc6aa604 org.telegram.desktop
flatpak update --commit=da9540545c9ae50279eed2ba00f978d793b0b4a18b5d1a2abfdb0cc3c7fefd4f org.telegram.desktop
flatpak update --commit=99007cfe1c65ca45a70a550538d946a6a098da963dc6e7bb01b05ccc60e08295 org.telegram.desktop

**Comment by ilya-fedin** [comment]
Well, you see, downgrading doesn't help, so it's not a bug in tdesktop, but something changed in your system
