### ISSUE TITLE
Double menu item

### ISSUE THREAD

**Issue by AlenaZuk** [telegramdesktop/tdesktop#25906]
### Steps to reproduce

Label menu /usr/share/applications/telegramdesktop.desktop
At each launch, it creates another label /home/user/.local/share/applications/org.telegram.desktop._bla-bla.desktop

As a result, two menu items

### Expected behaviour

Do not create after the first time
I did not create previously

### Actual behaviour

.

### Operating system

Debian 11 XFCE

### Version of Telegram Desktop

4.6.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Apparently you have multiple Telegram binaries installed in your system? Or maybe you're using the `-workdir` argument? Each working directory launch will create its own launcher, that's intended.

**Comment by AlenaZuk** [comment]
Exec=/opt/Telegram/Telegram -- %u One binary
/usr/share/applications/telegramdesktop.desktop
where he should be, and in the home catalog I delete it and until version 4.6.3 it was not created
I cannot explain through the translator, compare the behavior 4.6.1 and 4.6.3 by deleting .desktop file in the home directory launching from another place

**Comment by ilya-fedin** [comment]
It's the expected behavior, sorry. I recommend to avoid launching tdesktop from different locations.

**Comment by AlenaZuk** [comment]
different locations? Then why is there a catalog with an icon here? ~ /.local/share/icons
Place it in the profile then,let each program scatter your tails where it wants, how to litter Windows?

**Comment by ilya-fedin** [comment]
I'm actually thinking about having a postfix with md5 in the icon just like .desktop file has
