### ISSUE TITLE
[Feature Request] Hotkeys for smooth scroll messages of active chat/channel.

### ISSUE THREAD

**Issue by ImNotVafel** [telegramdesktop/tdesktop#25917]
### Is your feature request related to a problem?

It's not critical. But it's very inconvenient.

### Describe the solution you'd like

Add smooth scrolling commands for use it in `tdata\shortcuts-custom.json`.

I see it like this:
```json
[
    {
        "command": "scroll_up_history",
        "keys": "alt+p"
    },
    {
        "command": "scroll_down_history",
        "keys": "alt+n"
    }
]
```

### Describe alternatives you've considered

* I tried using PageUp and PageDown.
  It's more like a jumping on messages.

* I tried using Ctrl+Up for surfing on autoscroll to replied message.
  The best workaround. But it still feels like a jump, not a scroll.

### Additional context

I want hotkeys for **smooth scroll** messages of an active chat/channel (like on press key Down after scroll to old message) .

**Comment by ilya-fedin** [comment]
You can scroll with up/down keys

**Comment by ImNotVafel** [comment]
Yes, i can scroll with up/down keys. But i want map it to another keys
