### ISSUE TITLE
Reverse order and Shuffle menu inaccessible without click and holding left mouse button on main order menu button

### ISSUE THREAD

**Issue by kopoba** [telegramdesktop/tdesktop#25913]
### Steps to reproduce

1. Start playing music
2. Hover order setting button
3. Move mouse to sub menu on Shuffle or Reverse order
4. During movement of mouse menu disappear 

### Expected behaviour

Sub menu doesn't disappear just like volume menu

### Actual behaviour

Menu disappear 

### Operating system

windows 10

### Version of Telegram Desktop

4.6.4 beta x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I hope it'll be fine in 4.6.11 beta.

**Comment by kopoba** [comment]
> I hope it'll be fine in 4.6.11 beta.

Yep fixed in 4.6.11 beta
