### ISSUE TITLE
webview window on wayland doesn't open

### ISSUE THREAD

**Issue by kinoher** [telegramdesktop/tdesktop#25916]
### Steps to reproduce

1. rm $HOME//.local/share/TelegramDesktop/tdata/nowayland
2. open telegram 

---

Start the @DurgerKingBot
Open the TWA

or try buy premium you can't pass 3D secure because window invisible  

### Expected behaviour

webview window 

### Actual behaviour

![Screenshot from 2023-02-19 18-06-05](https://user-images.githubusercontent.com/33186133/219960610-2c1013a9-4651-493a-9a84-b7dbb8978037.jpg)

empty

### Operating system

fedora 36 gnome 42.6

### Version of Telegram Desktop

4.6.3

### Installation source

Static binary from official website

### Logs

```shell
log.txt

2023.02.19 18:22:04] Export Info: Destroy top bar by controller removal.
[2023.02.19 18:22:31] BotWebView Error: Could not parse """".
[2023.02.19 18:22:31] BotWebView Error: Could not parse """".
[2023.02.19 18:22:31] BotWebView Error: Could not parse """".
```
systemlog
```
Feb 19 18:22:30 fedora org.telegram.desktop._4e452d0fb0cb7b22a12f5b4b43da8f48.desktop[7943]: unable to lock lockfile /run/user/1000/wayland-0.lock, maybe another compositor is running
Feb 19 18:22:30 fedora org.telegram.desktop._4e452d0fb0cb7b22a12f5b4b43da8f48.desktop[7943]: unable to lock lockfile /run/user/1000/wayland-0.lock, maybe another compositor is running
Feb 19 18:22:30 fedora org.telegram.desktop._4e452d0fb0cb7b22a12f5b4b43da8f48.desktop[7943]: qrc:/qt-project.org/imports/QtWayland/Compositor/qmlfiles/WaylandCursorItem.qml:23:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Feb 19 18:22:30 fedora org.telegram.desktop._4e452d0fb0cb7b22a12f5b4b43da8f48.desktop[7943]: qrc:/qt-project.org/imports/QtWayland/Compositor/qmlfiles/WaylandCursorItem.qml:23:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Feb 19 18:22:30 fedora org.telegram.desktop._4e452d0fb0cb7b22a12f5b4b43da8f48.desktop[7943]: qrc:/qt-project.org/imports/QtWayland/Compositor/qmlfiles/WaylandCursorItem.qml:23:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Feb 19 18:22:30 fedora org.telegram.desktop._4e452d0fb0cb7b22a12f5b4b43da8f48.desktop[7943]: qrc:/qt-project.org/imports/QtWayland/Compositor/qmlfiles/WaylandCursorItem.qml:23:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Feb 19 18:22:31 fedora rtkit-daemon[817]: Successfully made thread 8121 of process 8109 (/usr/libexec/webkit2gtk-4.0/WebKitWebProcess) owned by '1000' RT at priority 5.
Feb 19 18:22:31 fedora rtkit-daemon[817]: Successfully made thread 8156 of process 8109 (/usr/libexec/webkit2gtk-4.0/WebKitWebProcess) owned by '1000' RT at priority 5.
```
```

**Comment by ilya-fedin** [comment]
I can't reproduce, it's visible for me

**Comment by kinoher** [comment]
> I can't reproduce, it's visible for me
show distro version gnome version gpu driver version gpu model
test again and ensure telegram in wayland mode

**Comment by ilya-fedin** [comment]
I use NixOS unstable with Plasma Wayland

**Comment by ilya-fedin** [comment]
I would indeed assume the drivers are the culprit as the window embeds QML WebView control and so likely managed by the OpenGL drivers.

**Comment by kinoher** [comment]
after switch to  nouveau window work 
but cpu usage 70%

**Comment by ilya-fedin** [comment]
NVIDIA means suffering :(

**Comment by ilya-fedin** [comment]
That's apparently the same as #16830, so apparently we should extend the NVIDIA blacklist to the webview window... The only difference is that the webview window doesn't have non-OpenGL backend for Wayland and the X11 non-OpenGL backend doesn't work on mutter for some reason, so it's blacklisted on mutter (GNOME and GNOME-based DEs) what means GNOME and Wayland NVIDIA users should get a dialog explaining there's no working backend for them instead of the unvisible window.

**Comment by ilya-fedin** [comment]
Hmm, maybe it's worth to try QML's experimental raster backend first...
