### ISSUE TITLE
[Feature Request] Verify Telegram Flatpak in Flathub Beta

### ISSUE THREAD

**Issue by kbdharun** [telegramdesktop/tdesktop#25911]
### Is your feature request related to a problem?

No, But since Flathub is displayed as an official install method I would suggest verifying the application.

### Describe the solution you'd like

Recently [Flathub beta](https://beta.flathub.org/) added support for Verifying applications made by the official developer, I would suggest [Telegram](https://beta.flathub.org/apps/org.telegram.desktop) apply for the same.

Flathub beta is the version that will become Flathub main in future. So adding it now will make it available on the main website in future too. 

Here is a list of [verified applications](https://beta.flathub.org/apps/collection/verified)

## Reference Image

This will show up next to the application name as displayed in the image below.

![image](https://user-images.githubusercontent.com/26346867/219929630-3e172aa6-5206-4b1a-a238-c04485de70a9.png)

I think you can authenticate Telegram using GitHub at the Beta Flathub website.

## Reference links

- https://github.com/flathub/website/issues/44
- https://discourse.flathub.org/t/situation-report-new-flathub-website-work-app-verifications-logins-etc/2259/25
- https://debugpointnews.com/flatpak-flathub-verification/
- https://news.itsfoss.com/verified-flatpak-apps/

**Comment by razzeee** [comment]
> I think you can authenticate Telegram using GitHub at the Beta Flathub website.

That shouldn't work in this case, if my understanding is right. As the app id does not have io.gitlab.telegramdesktop.tdesktop so website verification would be the only one available, which needs you to have access to telegram.org

**Comment by john-preston** [comment]
Thanks for the idea.

**Comment by kbdharun** [comment]
> > I think you can authenticate Telegram using GitHub at the Beta Flathub website.
> 
> That shouldn't work in this case, if my understanding is right. As the app id does not have io.gitlab.telegramdesktop.tdesktop so website verification would be the only one available, which needs you to have access to telegram.org

Yes, thanks for the clarification. Seems like it got verified now 🎉 .
