### ISSUE TITLE
Personal storage

### ISSUE THREAD

**Issue by Lazek** [telegramdesktop/tdesktop#2591]
https://telegram.org/blog/trending-stickers

Please add support Personal storage in Telegram Desktop.

Thanks you.

**Comment by T3rminat0r** [comment]
It's there, currently, you can only access it by searching for your own chat handle, but you can access it like any other chat :)

**Comment by Lazek** [comment]
Now available in 1.0 (after click Menu -> Avatar), please add information from mobile clients about personal storage (at this moment simple dialog, without texts).
