### ISSUE TITLE
WebApp view doesn't scroll via mouse wheel

### ISSUE THREAD

**Issue by kfreiman** [telegramdesktop/tdesktop#25914]
### Steps to reproduce

- Open WebApp via menu button at https://t.me/DurgerKingBot
- Try to scroll goods, using mouse wheel 

### Expected behaviour

- WebApp view is able to scroll via mouse wheel

### Actual behaviour

- WebApp view doesn't scroll via mouse wheel
- Touchpad is ok
- Graging scroll bar is ok

### Operating system

Ubuntu 20.04.4 LTS

### Version of Telegram Desktop

4.6.4 beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#25086
