### ISSUE TITLE
Schedule message button missed in topics

### ISSUE THREAD

**Issue by kudrevatykh** [telegramdesktop/tdesktop#25926]
### Steps to reproduce

1. Go to group with topic enabled
2. Write message
3. Right-click on send button

### Expected behaviour

Two options - "Send without sound" and "Schedule message"

### Actual behaviour

Only "Send without sound" option

### Operating system

debian linux

### Version of Telegram Desktop

4.6.3

### Installation source

Static binary from official website

**Comment by mont06** [comment]
Same, someone has the solution?

**Comment by MasterGroosha** [comment]
Still present in 4.8.1

**Comment by kudrevatykh** [comment]
4.10.3 Still has this issue

**Comment by GolD7777777** [comment]
The problem is still [present](https://github.com/telegramdesktop/tdesktop/issues/27119).

**Comment by tmarnld** [comment]
Problem still exists. Any solutions?

**Comment by GolD7777777** [comment]
The problem is still present.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/a888b8d846cab7d53b63dd3e31f388ba340e9806
