### ISSUE TITLE
[Feature Request]: Update winget-releaser action

### ISSUE THREAD

**Issue by vedantmgoyal2009** [telegramdesktop/tdesktop#25927]
### Is your feature request related to a problem?

@john-preston there have been several updates made to the winget-releaser action, so there are a few things to be done:

- Delete and re-fork winget-releaser repository (updating fork won't work, because it won't pull the new tags)
- Install https://github.com/apps/pull on https://github.com/telegramdesktop/winget-pkgs to keep it updated with upstream.

cc @ilya-fedin

**Comment by john-preston** [comment]
Done that.

**Comment by vedantmgoyal2009** [comment]
@john-preston WinGet Releaser fork is still 86 commits behind of the upstream repo.

**Comment by john-preston** [comment]
@vedantmgoyal2009 Sorry, mistook the repository. Now should be ok.

**Comment by vedantmgoyal2009** [comment]
Thanks! Just want to make sure everything will work as expected on the next release, can you re-run https://github.com/telegramdesktop/tdesktop/actions/runs/4212034295?
