### ISSUE TITLE
[Feature Request] Windows ARM64 Support

### ISSUE THREAD

**Issue by stormenergy91** [telegramdesktop/tdesktop#25923]
### Is your feature request related to a problem?

The acutal x64 version run on Windows ARM64 but is slow. Since there is already an ARM version of the client (macOS) is possibile to ha ve a naitive build for Windows ARM64?

### Describe the solution you'd like

Offer a native build for Windows ARM64

### Describe alternatives you've considered

The only alternative is run the x64 version but is slow.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25266

**Comment by john-preston** [comment]
It is possible, but it requires one more deployment line :( In case of macOS they allow building universal binaries which is nice and removes most of the headache.
