### ISSUE TITLE
Linux build fails due to missing python3

### ISSUE THREAD

**Issue by gibcheesepuffs** [telegramdesktop/tdesktop#25920]
### Steps to reproduce

```
git clone --recursive https://github.com/telegramdesktop/tdesktop.git
cd tdesktop/Telegram/build/docker/centos_env
git reset --hard e78975d770b2d651930e01a327d434632c18aeaa
poetry install
poetry run gen_dockerfile | DOCKER_BUILDKIT=1 docker build -t tdesktop:centos_env -
```

Error: building at STEP "RUN python3 -m pip install meson ninja": while running runtime: exit status 127

### Expected behaviour

It should build

### Actual behaviour

It does not build

### Operating system

Fedora 37 KDE

### Version of Telegram Desktop

Version 4.6.3

### Installation source

Official github [repo](https://github.com/telegramdesktop/tdesktop)

**Comment by ilya-fedin** [comment]
I can't reproduce, this step passes successfully

**Comment by gibcheesepuffs** [comment]
I think you cannot reproduce because of using CI for testing the above steps. Try these steps manually on any distro and I am positive that the bug will appear 👌

**Comment by ilya-fedin** [comment]
I checked locally on my machine

**Comment by gibcheesepuffs** [comment]
¯\_(ツ)_/¯ I give up then, thanks

**Comment by ilya-fedin** [comment]
It might be SELinux or the lack of some CPU instruction support in your hardware
