### ISSUE TITLE
choppy & freezzing video playback on Fedora 37

### ISSUE THREAD

**Issue by lejeczek** [telegramdesktop/tdesktop#25939]
### Steps to reproduce

 1. Play any video.

### Expected behaviour

Video freezes while audio continues to play.
Seems that video might freeze after some inactivity & can be poked to play by moving cursor.
 

### Actual behaviour

Video freezes while audio continues to play.
Seems that video might freeze after some inactivity & can be poked to play by moving cursor.
 

### Operating system

Fedora 37

### Version of Telegram Desktop

org.telegram.desktop.webview 2.38.5

### Installation source

Flatpak

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
> org.telegram.desktop.webview 2.38.5

This is not application package name and version, you should look for org.telegram.desktop

**Comment by ohhai** [comment]
Might be related: #25405

**Comment by ilya-fedin** [comment]
@ohhai I don't think so, I would rather assume it's https://gitlab.freedesktop.org/mesa/mesa/-/issues/8136

**Comment by DiamondDDogs** [comment]
I have this same exact issue on Arch Linux with version 4.6.3-1
