### ISSUE TITLE
Rightmost pixels are not clickable

### ISSUE THREAD

**Issue by rostislaved** [telegramdesktop/tdesktop#25938]
### Steps to reproduce

1. Move cursor to the rightmost position (for example where the scrollbar for stickers or buttons of image viewer: close button or next_image button in fullscreen)
2. try to click - nothing happens
3. move cursor 1 pixel to the left - everything is okay

### Expected behaviour

I expect this area to be clickable as it was in 4.6.3

### Actual behaviour

Nothing happens when click or scroll

### Operating system

5.15.89-1-MANJARO i3wm edition

### Version of Telegram Desktop

4.6.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Please provide a record of the issue

**Comment by rostislaved** [comment]
https://youtu.be/711poqvEMSw

At first I do several clicks in both directions. After that I move cursor to the rightmost position and as you can see "right button" is not highlighted. Consequently when I do clicks nothing happens whether I press near the "right button" or near the close button

**Comment by ilya-fedin** [comment]
I can't reproduce that with Plasma

**Comment by rostislaved** [comment]
But I didn't mention plasma..

**Comment by ilya-fedin** [comment]
@rostislaved that's my Linux host

**Comment by rostislaved** [comment]
Okay, I figured out what was the cause of this behavior.

I have big resolution on my laptop and to scale interface I changed the line in file ~/.Xresources:
Xft.dpi:       200

So, decreasing it back to 150 fixes my problem. But it changes scaling for all other application, so it is possible to change dpi per application:

1. touch ~/.Xresources-Telegram
actually it may be not "Telegram", to know for sure:
1.1 xprop | grep WM_CLASS
1.2 click on telegram window
1.3 pick the first string from result. In my case:
WM_CLASS(STRING) = "Telegram", "TelegramDesktop"

2. Paste in ~/.Xresources-Telegram:
-Xft.dpi:       150
or some other number
3. xrdb -merge ~/.Xresources-Telegram 
4. restart telegram and adjust scaling in TG settings.

**Comment by ilya-fedin** [comment]
I can't reproduce with Xft.dpi set to 200. Apparently i3wm handles fullscreen wrongly and you have to report them about that.

**Comment by rostislaved** [comment]
It seems that my solution above doesn't work. Do you know, how to change dpi for only telegram?

**Comment by ilya-fedin** [comment]
You can change interface scale in settings. I'm not aware of other way.
