### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by JackWu2006** [telegramdesktop/tdesktop#25931]
### Is your feature request related to a problem?

On macOS 13, the "Settings" page still displays as "Preferences".
<img width="250" alt="Screen Shot 2023-02-21 at 23 37 48 PM" src="https://user-images.githubusercontent.com/98635189/220390394-a258f270-692b-4b78-8fec-b57ce06ef20b.png">

### Describe the solution you'd like

Change it to "Settings"!

### Describe alternatives you've considered

Change it to "Settings"!

**Comment by Aokromes** [comment]
what's the telegram version of that screenshot?

**Comment by JackWu2006** [comment]
Latest

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
