### ISSUE TITLE
icon not showing on wayland

### ISSUE THREAD

**Issue by cppshizoidS** [telegramdesktop/tdesktop#25933]
### Steps to reproduce

open telegram
icon of telegram not shows
icon of wayland instead

### Expected behaviour

icon of telegram

### Actual behaviour

![Screenshot_20230222_081515](https://user-images.githubusercontent.com/77567325/220495522-9715671b-b6ea-4885-8fa6-4be4121c4494.png)

### Operating system

Manjaro KDE(wayland) unstable

### Version of Telegram Desktop

4.6.4 beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Are you sure you're using the binary from official website and not some package?

**Comment by cppshizoidS** [comment]
Sorry, double-checked, it turns out no, a build from the AUR. from the official site everything is ok
