### ISSUE TITLE
scaling issue

### ISSUE THREAD

**Issue by av100** [telegramdesktop/tdesktop#25935]
### Steps to reproduce

After the monitor is completely turned off, scaling is not working properly (resets to ~ 100%). 
scaling settings: 
in windows 200% 
in telegram 250%

![image](https://user-images.githubusercontent.com/33670005/220537590-1770c844-cd12-42ef-b4e9-c29adfe6b638.png)

### Expected behaviour

This appeared in recent months, but I do not know with which version. 4.2.4 everything works fine

### Actual behaviour

scaling is not working properly

### Operating system

w11 21h2

### Version of Telegram Desktop

4.6.3

### Installation source

Static binary from official website

**Comment by oleg-indeez** [comment]
Hi all. Quite the same, but other issue data: telegram linux 4.8.10, scaling set to default (240%) ок manually 250%. The main window scale is respected but mouse pointer - it is too small after turning the monitor off and back on. If I restart telegram everything is correctly scaled.
