### ISSUE TITLE
Message gets marked as seen, even in unfocused window

### ISSUE THREAD

**Issue by nimaaskarian** [telegramdesktop/tdesktop#25930]
### Steps to reproduce

1. Unfocused Telegram desktop
2. Go inside a chat
3. A new message from that chat

### Expected behaviour

New messages from a open chat on unfocused Telegram should get marked as new message

### Actual behaviour

New messages from a open chat on unfocused Telegram should get marked as seen, resulting a chat to get seen and no notification gets produced (even on other devices!)

### Operating system

Arch Linux, i3

### Version of Telegram Desktop

4.6.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Ensure you don't have experimental settings enabled

**Comment by MilanRistovski** [comment]
@ilya-fedin 

Hi guys, I'd like to contribute to Telegram if possible... I don't know how to reach out to you (via email or something).
I want to contribute to this project. 

However, I have issues configuring/importing/building the project. 

When I enter configure.bat x64 -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb in command line, I get the following issue : 

![image](https://user-images.githubusercontent.com/60365038/220687532-81a0fff2-f859-40e6-9c0c-d24d306fee92.png)

If I go into CMake, I get the following: 

![image](https://user-images.githubusercontent.com/60365038/220687743-b78f1a8b-97d9-458a-9fe8-9d3616124aaa.png)

I will post the same message in a couple of places in order for the message to be noticed and me to get some help. 
Thanks in advance!

**Comment by ilya-fedin** [comment]
Have you read build instructions? Have you ran prepare\win.bat?

**Comment by ilya-fedin** [comment]
> I don't know how to reach out to you (via email or something).

Please use New issue -> Question for questions, don't try to reach anyone personally

**Comment by nimaaskarian** [comment]
> Ensure you don't have experimental settings enabled

For some reason, the option for reading inactive chat had been activated (not by me, because I DON'T PLAY AROUND WITH STUFF AND JUST FORGET THEY EXIST).
it sounds stupid now lol...
thanks.
