### ISSUE TITLE
Telegram is crashing on fedora 37

### ISSUE THREAD

**Issue by serial02** [telegramdesktop/tdesktop#25949]
### Steps to reproduce

Hello

 When closing telegram it crashes all fedora system
 How to report the error? 
 Shouldn't there be a log in telegram itself to send this type of error or crash?

### Expected behaviour

that does not brake

![Captura de tela de 2023-02-23 18-58-18](https://user-images.githubusercontent.com/32621790/221040345-5b34625d-0bbe-491a-bfa7-785d8af4e460.png)
![Captura de tela de 2023-02-23 18-57-42](https://user-images.githubusercontent.com/32621790/221040354-8a95ed12-6cde-456e-a4af-408382af3f89.png)

### Actual behaviour

Hello

 When closing telegram it crashes all fedora system
 How to report the error? 
 Shouldn't there be a log in telegram itself to send this type of error or crash?

![Captura de tela de 2023-02-23 18-58-18](https://user-images.githubusercontent.com/32621790/221051405-483dde7d-99ca-42c1-80fa-972a19debf1b.png)
![Captura de tela de 2023-02-23 18-57-42](https://user-images.githubusercontent.com/32621790/221051414-514e730c-e978-4db3-8951-f4bbb3f3f321.png)

### Operating system

Fedora 37 flavor gnome 43.3

### Version of Telegram Desktop

4.6.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> When closing telegram it crashes all fedora system

If the system itself is crashed then it's a bug in the system
