### ISSUE TITLE
Lagging UI while recently used stickers is visible

### ISSUE THREAD

**Issue by max-merezhko** [telegramdesktop/tdesktop#25946]
### Steps to reproduce

1. Open the app
2. Open the stickers tab so that Recently user stickers should be visible

### Expected behaviour

No laggs, everything works as expected

### Actual behaviour

When recently used stickers are visible on the screen, Telegram user interface is very slow, if you scroll the stickers a little lower, the lags go away. Both those and other stickers are animated, but there are lags only when the recent ones are not visible on the screen. As soon as they go beyond the scrolling boundaries, the lags instantly disappear. The lasg are expressed in slow-motion typing and slow-motion animation of stickers when I move the mouse over the chat list.

### Operating system

Windows 10

### Version of Telegram Desktop

Version 4.6.3 x64

### Installation source

Static binary from official website

**Comment by Max-tests** [comment]
Any updates?

**Comment by Max-tests** [comment]
@Aokromes @john-preston @ilya-fedin

**Comment by ilya-fedin** [comment]
@Max-tests what do you want?

**Comment by ilya-fedin** [comment]
I'm not sure how I can help you :(

**Comment by Max-tests** [comment]
How should i proceed then, the issue isnt related to PC specs, and also i`m not alone with this issue, the similar ticket was closed a year ago with no response

**Comment by ilya-fedin** [comment]
I guess it's just not a priority

**Comment by Max-tests** [comment]
anyway, thanks for help
