### ISSUE TITLE
Pinned messages aren't displayed properly in forum topics

### ISSUE THREAD

**Issue by SandaruKasa** [telegramdesktop/tdesktop#25945]
### Steps to reproduce

1. Create a new topic in a forum
2. Send a message there

### Expected behaviour

Nothing extraordinary happens

### Actual behaviour

Message gets a pin icon and the context menu allows to unpin it. Yet, there is no "pinned message" bar at the top of the chat.

If you send another message and pin it too, both become visible in the bar at the top. You can then pin and unpin messages all you like, but as soon as the only pinned message is the first one in the topic, the bar disappears.

### Operating system

Arch Linux

### Version of Telegram Desktop

4.6.4 beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@SandaruKasa This is a (possibly, very weird) feature. In topics it was requested to:
- auto-pin the first message (actually, server does it)
- hide the pinned bar if the topic has only this one first message pinned and it is visible on the screen (this mechanics already works in channel comments, the first message — the one the comments are left about — is something-like-pinned in the comments thread, it shows the something-like-pinned-message-bar when it is not visible on the screen).
