### ISSUE TITLE
Video driver crashes when I switch between the Desktop app and Google Chrome [HP VICTUS 16-e0xxx]

### ISSUE THREAD

**Issue by danyakomarov** [telegramdesktop/tdesktop#25941]
### Steps to reproduce

Have Google Chrome (with a video call tab active) & Telegram Desktop app open at the same time
Switch between the apps (the bug was observed more often when I would have some kind of media (e.g. photo) open in the Telegram App and then switch to Chrome)

### Expected behaviour

My screen shouldn't go dark for a minute only to switch back on with video driver settings reset to factory

### Actual behaviour

My screen goes dark for a minute only to switch back on with video driver settings reset to factory

### Operating system

Windows 11 21H2 22000.1574

### Version of Telegram Desktop

4.6

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
try to update your binary to 4.6.4 beta enabling beta.

**Comment by ilya-fedin** [comment]
That means there's a bug in your video driver, nothing tdesktop can do about

**Comment by danyakomarov** [comment]
> try to update your binary to 4.6.4 beta enabling beta.

Did that, will report if the issue remains. Thanks :)

**Comment by MilanRistovski** [comment]
@ilya-fedin @Aokromes 

Hi guys, I'd like to contribute to Telegram if possible... I don't know how to reach out to you (via email or something).
I want to contribute to this project. 

However, I have issues configuring/importing/building the project. 

When I enter configure.bat x64 -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb in command line, I get the following issue : 

![image](https://user-images.githubusercontent.com/60365038/220687532-81a0fff2-f859-40e6-9c0c-d24d306fee92.png)

If I go into CMake, I get the following: 

![image](https://user-images.githubusercontent.com/60365038/220687743-b78f1a8b-97d9-458a-9fe8-9d3616124aaa.png)

I will post the same message in a couple of places in order for the message to be noticed and me to get some help. 
Thanks in advance!
