### ISSUE TITLE
Unread counters misbehaving in forums

### ISSUE THREAD

**Issue by SandaruKasa** [telegramdesktop/tdesktop#25947]
### Steps to reproduce

Sadly, I was not able to come up with a consistent way to reproduce any of the bugs I am about to describe.

### Expected behaviour

Each topic in a forum behaves as essentially a separate chat with separate unread counters, and read statuses.

### Actual behaviour

1. Sometimes a message gets marked as read even though no one has read it. There is no "seen by" section for such a message in its context menu either.

2. Sometimes opening a topic that has been inactive for a while and was fully read by you leads to it getting marked as having hundreds upon thousands of unread messages.

3. 4 digit long unread counters do not fit properly
![image](https://user-images.githubusercontent.com/50824690/220883239-e57d63b0-171e-4618-b929-2aed36e47cbf.png)

4. At times, a fully read topic gets a dot to the right of it in the list of forum's topics. I do not really understand what such a dot is meant to represent. Anyway, opening a topic with such a dot is guaranteed to mark it as having hundreds of unread messages.

5. Just today, I went to open a forum I am a part of to discover that two of its topics got such dots. Opening one of them did indeed gave me hundreds of "unread" messages in that topic, but after I "read" them all, both dots were gone, not just one of them.

All of the above (except for the UI issue) may or may not have something to do with me opening the same forums on Telegram X (which is yet to handle topics properly).

On an unrelated note, while typing this text, I've noticed that the red wavy line (marking the misspelled words) gets cut in half vertically when it appears at the bottom line of text in this input box. Not sure if this is an issue with GitHub's layout or with Chromium's rendering. But, man, do I love bugs.

### Operating system

Arch Linux

### Version of Telegram Desktop

4.6.4 beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I believe I can reproduce 3. reliably 🤣

**Comment by john-preston** [comment]
4. This looks related to 2. and actually a dot means an not-opened-yet topic, so all messages in it are considered unread and the dot means that there were new messages in it since you joined the group.

**Comment by john-preston** [comment]
Yes, when you open the same forum on Telegram X, it may interact with those "dots" (the dots mechanic uses the old "read-ness" of the group), but all of those should apply only to not-yet-opened-by-you topics. But this is a helpful idea, I'll investigate the dependency between opening the group in a legacy (not-yet-topics) format and those per-topic read-ness.

**Comment by FUZIK** [comment]
I also reproduced 3 on win

![изображение](https://user-images.githubusercontent.com/15977008/221447558-c7e61af5-5408-457e-9ca5-0edf3b01c37c.png)

**Comment by zzzephire** [comment]
I've reproduced step 1, but it doesn't seem that simple.
I've group-1 (6 topics inside) and group-2 (3 topics inside).
Notifications in group-1 (topics too) are disabled. I see counter badge on group icon of unread topics and hear no sound notifications.
In group-2 notifications are turned on everywhere but counter badge on group icon or on topic icon is missing. I hear notification sound when group-2 have some activity but counters are disappeared 😀

**Comment by SandaruKasa** [comment]
Bump
