### ISSUE TITLE
[Feature Request] App icon that fits macos design.

### ISSUE THREAD

**Issue by olehmisar** [telegramdesktop/tdesktop#25942]
### Is your feature request related to a problem?

All macos apps use square icons with rounded corners, except Telegram which is rounded and also bigger in size than all other icons.

### Describe the solution you'd like

Replace rounded icon with a square with rounded corners one to match overall system design. 

Here you can see how the current icon does not fit other apps.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/29802592/220748189-a49fc321-d2d4-47e7-8045-1369cbb6ec08.png">

For example, here is an icon that is used by Telegram written in swift. Maybe it can be used for this telegram client too?
<img width="70" alt="image" src="https://user-images.githubusercontent.com/29802592/220747922-37e606e3-13e7-4167-ad9a-d84bea30c92b.png">

### Describe alternatives you've considered

-

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16552#issuecomment-886167780

**Comment by olehmisar** [comment]
@Aokromes any rationale why this won't be fixed? IMO, the bigger round icon looks ugly. As per https://github.com/telegramdesktop/tdesktop/issues/16552#issuecomment-1012457763, the current icon can be adapted to macos design(by making it square with rounded corners). Or at least make it smaller, so will match the size of other apps' icons.

**Comment by john-preston** [comment]
Ok, fine, it was allowed.
