### ISSUE TITLE
[Feature Request] Add dual JSON + HTML export 

### ISSUE THREAD

**Issue by timolins** [telegramdesktop/tdesktop#25954]
### Is your feature request related to a problem?

 I have to choose between JSON and HTML export, which limits the practically of the export. I want my backup to be human readable, as well as machine readable.

### Describe the solution you'd like

A new export option that outputs both JSON and HTML, in a single export.

### Describe alternatives you've considered

Exporting everything twice, one time with JSON and another one for HTML.

* This takes much longer
* Downloads all assets twice, and leads to duplication

**Comment by ilya-fedin** [comment]
#9829
