### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by JLoskin** [telegramdesktop/tdesktop#2595]
### Steps to reproduce
1. Choose create New Channel
2. Next
3. Click choose image
4. Close FileChooser by dialog close
5. Crash

### Expected behaviour
Apply default image

### Actual behaviour
Application crash

### Configuration
**Operating system: Windows 10**

**Version of Telegram Desktop: 0.10.19**

### Logs
Useless

**Comment by john-preston** [comment]
@JLoskin Thank you for your report! This will be fixed in the next version.
