### ISSUE TITLE
Bottom of messages view overlap with message editor widget

### ISSUE THREAD

**Issue by ratijas** [telegramdesktop/tdesktop#25956]
### Steps to reproduce

Not sure how to reproduce. This has only happened once so far.

### Expected behaviour

They should not overlap

### Actual behaviour

![image](https://user-images.githubusercontent.com/6737986/221378664-424a814c-d46a-46aa-b97b-2c72682ac3be.png)

### Operating system

Arch Linux + KDE/Plasma

### Version of Telegram Desktop

4.6.3

### Installation source

Flatpak

### Logs

```shell
❯ flatpak info org.telegram.desktop

Telegram Desktop - Fast. Secure. Powerful.

          ID: org.telegram.desktop
         Ref: app/org.telegram.desktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.6.3
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 191.9 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 5a283346a7707f48b44dc9922bfed9aa8bc2f7f811eb46b4dc03e4a43f46231d
      Parent: 278cdae6f09fcd84ca1e73466ca54a3188e9088fe04c2276bae1dd550dc7d9db
     Subject: Skip aarch64 build (6ef75797)
        Date: 2023-02-18 19:01:50 +0000
```
```

**Comment by john-preston** [comment]
How do I reproduce that?

**Comment by ratijas** [comment]
Honestly, no idea how to reproduce. It only happened once, and I immediately took a screenshot. It was the only window (no "open in new window" chats), and probably after waking from sleep or unminimizing. I remember that the view was scrollable, but apparently, it used window's bottom instead of footer's top for its bottom extent. So I don't think it's a clipping issue; but a sizing / anchors one.

**Comment by ratijas** [comment]
I got it again! So, a bit more info.

Computer was idle for some time, screen got locked and monitors went to sleep. However, OS didn't go into sleep mode — only outputs. 2 monitors/outputs were connected, but one (external TV) automatically turned off, although that shouldn't matter because Plasma still believes it is connected and enabled (and I can move my mouse there too).

Telegram Desktop is running without window decorations (forcefully turned off in KWin window-specific settings), vertically maximized between two panels, on the left side of the left (built-in laptop's) output. Window itself in horizontally narrow enough to fit only one column. No folders.

Now that it is glitched, I can reproduce the bug by opening the same chat again — but only after opening some other chat in between. When I start scrolling, bottom extent of the scroll view somehow updates and does not overshoot anymore. Go back to main menu, and select chat again -> scroll view is glitched. Start scrolling -> it fixes itself. Go back, select the same chat -> not glitched. Go back, select another chat -> not glitched. Go back, select that originally glitched chat -> it is glitched again.

In some more testing, opening a different chat does not necessarily trigger the glitch for original chat again. There's some combination of clicking and scrolling that forces it to re-trigger.
