### ISSUE TITLE
[Regression] Linux/Wayland/sway(1.8) / TG >= 4.5.6 < 4.6.5 -- screen updated only by external events

### ISSUE THREAD

**Issue by alxchk** [telegramdesktop/tdesktop#25955]
### Steps to reproduce

1. Write text in chat 
2. Press enter
3. ?? Nothing happend ??
4. Press any key (or move mouse) -- actual changes drawn to screen

Gifs and other animation active only if keyboard or mouse moved. Version 4.5.3 works fine.

### Expected behaviour

Screen updated regardless I'm moving mouse or pressing keys.

### Actual behaviour

Screen is not updated unless I move mouse or press keys.

### Operating system

Linux

### Version of Telegram Desktop

4.6.3

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Are you sure it's caused by Telegram update and not system libraries update?

**Comment by ilya-fedin** [comment]
> Other (unofficial) source

What source is that? Does the problem reproduce with the static binary from the website?

**Comment by alxchk** [comment]
I'm building telegram-desktop with gentoo (https://gitweb.gentoo.org/repo/gentoo.git/tree/net-im/telegram-desktop). System libraries are the same for 4.5.3 and 4.6.3. When I downgrade to 4.5.3 at same system everything works fine.
Build rules for 4.5.3 and 4.6.3 are same, and system libraries are not updated. So it's high probability that something has been changed at codebase

**Comment by ilya-fedin** [comment]
well, there's a lot of versions between 4.5.3 and 4.6.3, can you find the first bad version?

**Comment by alxchk** [comment]
I may try, however this will take time ~_~
I can't bisect, so probably the best will be last working release..

This looks like WL event loop is stuck, maybe there is a place, which has changed recently? (to reduce amount of releases to try)

**Comment by ilya-fedin** [comment]
> I can't bisect

Why can't you bisect?

> This looks like WL event loop is stuck, maybe there is a place, which has changed recently?

tdesktop doesn't have access to Wayland event loop, it's deeply hidden by Qt, that's why I assumed system libraries to be the culprit.

**Comment by alxchk** [comment]
> Why can't you bisect?
gentoo ebuild uses "release" package, so need to be reworked to be able to build from the git.
Anyway, I will try to find last working release first.

**Comment by ilya-fedin** [comment]
> gentoo ebuild uses "release" package, so need to be reworked to be able to build from the git.

You can clone the repository and build it. You can use gcc10 to ensure every commit builds without additional patches.

**Comment by alxchk** [comment]
Probably I can, however I'm not build-farm owner, so even with releases this looks like to take forever (just built 4.5.5 and it's ok). 

By the way -- I downloaded the binary from the site, and it has +\- same behavior. Messages are rendered, however gifs and other updates are not drawn unless mouse moved or keyboard pressed.

**Comment by ilya-fedin** [comment]
With a cloned repository, you don't have to build from the start each time at least

**Comment by alxchk** [comment]
Looks like 4.5.5 is latest working release

**Comment by ilya-fedin** [comment]
Could it be that you're building Qt without glib? Or maybe you're launching multiple tdesktop instances?

**Comment by alxchk** [comment]
And looking to commits I found out.. If in 4.5.5 I enable GApplication I observe same behaivor.

**Comment by ilya-fedin** [comment]
Can you reproduce on 4.6.5?

**Comment by alxchk** [comment]
Building..

Qt should be with glib:

```
> readelf -d /usr/lib64/libQt6Core.so.6 | grep -i glib
 0x0000000000000001 (NEEDED)             Shared library: [libglib-2.0.so.0]
```

**Comment by alxchk** [comment]
Looks like 4.6.5 works fine with both GApplication enabled and disabled..

**Comment by ilya-fedin** [comment]
> Looks like 4.6.5 works fine with both GApplication enabled and disabled..

Versions starting with 4.5.6 have no GApplication toggle, it's always enabled
