### ISSUE TITLE
bug graphic in Debian 10

### ISSUE THREAD

**Issue by rezaparsad** [telegramdesktop/tdesktop#25967]
### Steps to reproduce

bug graphic in linux.
![Screenshot from 2023-03-01 17-29-09](https://user-images.githubusercontent.com/70529677/222162167-d3a7fdf6-d35d-49ac-aab8-9552b44754b7.png)

### Expected behaviour

thanks of telegram 

### Actual behaviour

not bug fix

### Operating system

debian 10

### Version of Telegram Desktop

4.6.5

### Installation source

Static binary from official website

### Logs

```shell
not log.
i`m use telegram binary
```

**Comment by ilya-fedin** [comment]
Are you using X11 or Wayland? Is it possible you have multiple screens with different scale?

**Comment by rezaparsad** [comment]
> 

no. one screen

**Comment by ilya-fedin** [comment]
Can you answer the first question?
