### ISSUE TITLE
[Regression] After version 4.5.3 all pictures in telegram is scaled and lost quality on HiDPI.

### ISSUE THREAD

**Issue by zvova7890** [telegramdesktop/tdesktop#25961]
### Steps to reproduce

1. Install > 4.5.3

### Expected behaviour

Pictures stay at the same quality as with versions <= 4.5.3 with Qt5 build on Linux. I saw this before on Qt6 build, and all time I'm manually build from source telegram with Qt5 to avoid this bug. But after 4.5.3 it broken everywhere. 

### Actual behaviour

Pictures stay sharp as on versions <= 4.5.3 with Qt5 build, at > 100% scale factor. I'm using 150%

### Operating system

ArchLinux

### Version of Telegram Desktop

4.6.3

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
The only thing that was preventing this KDE bug from happening with Qt 5 is that Qt 5 allows to disable High-DPI scaling. tdesktop no more disables High-DPI scaling, so it's visible with Qt 5 now what is completely expected. Sadly, the only things I can suggest are:
1. Migrate to the official binary that has a Qt patch fixing this behavior
2. Finally report this to Qt, see #25126, needs reporting block, item 5

**Comment by zvova7890** [comment]
I wander why it works before and now it's broken, how that happens? Qt and KDE still with mentioned "bugs", but before telegram had nice look all those years until now.

Also, I don't think KDE will "fix" that, because on X11 there is no other way to tell Qt about scale.

**Comment by ilya-fedin** [comment]
@zvova7890 my previous post explains how that happened only now, feel free to ask concrete questions if something is unclear.

**Comment by ilya-fedin** [comment]
> Also, I don't think KDE will "fix" that, because on X11 there is no other way to tell Qt about scale.

That's not right, see the Qt documentation page mentioned in #25126, it explains how the environment should tell scaling settings to Qt. And KDE does this with debug variable instead.

**Comment by zvova7890** [comment]
Yes, sorry, I'm re-read and understand now. Maybe will be good idea to detect KDE session and use "old" behavior on X11? I'm worried this will never gonna be fixed, at least on X11.

**Comment by zvova7890** [comment]
Documented way, you mean Xft.dpi(or Xft/DPI)? As I can see, there is no way to tell scale factor per-screen on X11 by non testing env variables. It has only global scale or scale calculated by toolkit based on physical size of monitor(which will not respect applied KDE settings). So, KDE devs didn't have many options to choice.

Please, correct me if I'm wrong.

**Comment by ilya-fedin** [comment]
> Documented way, you mean Xft.dpi(or Xft/DPI)?

Yeah

> As I can see, there is no way to tell scale factor per-screen on X11 by non testing env variables.

Funny enough, while that variable technically accepts per-screen scale factors, they use it to tell global scale factor.

> Maybe will be good idea to detect KDE session and use "old" behavior on X11?

Well, Qt 5 is supported only on Windows and Qt 6 has deprecated the API to disable High-DPI scaling, so such a change will have no difference for supported configurations.

**Comment by zvova7890** [comment]
> they use it to tell global scale factor.

That's true. But I can see why - it is not working properly. I'm manually applied different scale for 2 monitors and got more visual artifacts than benefits... I think this is reason why they do it that way.

BTW. You have settings that allows to override scale factor, I can propose if user overrides scale factor, we can unset those env variables on application level, before QApp init:

```
unsetenv("QT_SCREEN_SCALE_FACTORS");
unsetenv("QT_AUTO_SCREEN_SCALE_FACTOR");
```

Or unset this vars unconditionally at all... As it is doesn't work as expected and provide visual glitches.

**Comment by ilya-fedin** [comment]
> BTW. You have settings that allows to override scale factor, I can propose if user overrides scale factor, we can unset those env variables on application level, before QApp init:

This will reintroduce #10487

> But I can see why - it is not working properly. I'm manually applied different scale for 2 monitors and got more visual artifacts than benefits... I think this is reason why they do it that way.

They can do that via the documented way

**Comment by zvova7890** [comment]
Unfortunately, they can not. Setting up scale in such way producing Qt to scale only font's but not interface in common. It is cause small icons on big text. 
I'm sure they do it through env var not just because "they want".

Also, I have no idea, why all Qt app except telegram do not have this bug.

**Comment by ilya-fedin** [comment]
> . Setting up scale in such way producing Qt to scale only font's but not interface in common.

The thing here is scaling is opt-in in Qt 5, the proper way to handle that is to enable High-DPI scaling in the code of all the applications they're interested in.

> Also, I have no idea, why all Qt app except telegram do not have this bug.

Apparently they all support fractional devicePixelRatio... tdesktop is invented before Qt got High-DPI support and has only partial support for it necessary for macOS support. tdesktop's High-DPI support sadly never was good enough for modern use-cases (#1121) and likely never will be as fixing that means rewriting entire tdesktop UI code.

> I'm sure they do it through env var not just because "they want".

We won't know until someone interested reports the problem to them.

**Comment by zvova7890** [comment]
KDE already support for setting up DPI through X11(and that way has been used some time ago, also it can be used right now: instead of setting up Display -> Scale use Fonts -> Force font DPI), but as I'm said before, that produce only font's scaling, and as you said all Qt5 app must manually enable HiDPI scaling trough Qt5 API, but likely it will never happen and most simplest way for now is use Qt env vars. 

I can file the bug on KDE bugtracker, but apparently they can't just stop using those envs, because it will broke entire Qt5 apps, and this bug will be closed as this one. 
With Qt6 situation even worse. Telegram showing twice bigger interface than actual scaling. If manually force scale from tg settings it becomes to normal, but pictures is goes to scale round trip and became not sharp. If unset Qt env var exclusively for tg - we got broken scale for child process. Feels like for Qt6(not patched) based telegram there is no way to solve this problem easelly. Apparently I will continue to build myself a tdesktop(on Qt5) with reverted those lines, until it builds with Qt5 effortlessly, to get usable interface(or will think about official builds)
```
-	QApplication::setAttribute(Qt::AA_DisableHighDpiScaling, true);
-	QApplication::setHighDpiScaleFactorRoundingPolicy(
-		Qt::HighDpiScaleFactorRoundingPolicy::Floor);
```

Thank you for explanation

**Comment by ilya-fedin** [comment]
> I can file the bug on KDE bugtracker, but apparently they can't just stop using those envs, because it will broke entire Qt5 apps, and this bug will be closed as this one.

This bug is closed because the bug is on KDE side. I don't believe they just close it without telling where you should report instead.
