### ISSUE TITLE
Mac download offline

### ISSUE THREAD

**Issue by core-code** [telegramdesktop/tdesktop#25969]
### Steps to reproduce

1.) open https://telegram.org/dl/desktop/mac
2.) => 404 Not Found

### Expected behaviour

no 404

### Actual behaviour

404

### Operating system

Any

### Version of Telegram Desktop

Any

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I can't reproduce, getting a dmg file

**Comment by Aokromes** [comment]
yeah now works, at issue create time it was 404.
