### ISSUE TITLE
Автоматически вылетает из аккаунта и удаляет сообщения

### ISSUE THREAD

**Issue by RERCON0** [telegramdesktop/tdesktop#25968]
### Steps to reproduce

- Ровно каждые 4-5 дней вылетает аккаунт (первый добавленный в клиент, остальных это не касается - всего 4 аккаунта в клиенте), удаляя при этом сообщения за последние 2 дня. Удаляются только мои сообщения у собеседников, их сообщения остаются в целости. И вылетает не только в клиенте, а вообще ВО ВСЕХ клиентах, в том числе мобильных. Такой функции, чтобы прям на всех устройствах был вылет, не припомню. Знаю, что можно отрубать в настройках по одному клиенту, но чтобы все разом, нет.
- Сперва грешил на версию из Майкрософт стор, ибо до этого пользовался версий с официального сайта Телеграм и всё было нормально. Правда версию ДО стора и сторовскую не помню, увы. Но, как правило, всегда сразу обновлял на новую. Поставил обратно версию с сайта, проблема осталась. Версия 4.6.5. У друга стоит 4.6.4, у него такой проблемы не наблюдается. Возможно, что именно в 4.6.5 баг затаился.
- Может совпадение, но вылетает после того, когда написал/пишу пост для канала в избранном. И вылетает внезапно - ни предупреждения, ни окон, просто выходит на всех устройствах разом.
- Проблема наблюдается не только у меня. Общался с рекламодателем, она сказала, что у неё тоже вылетает из аккаунта и удаляются сообщения.
- Вылетает примерно в 21:00 по мск, плюс-минус. После чего требуется входить на всех устройствах снова. 
- Логи, к сожалению, не сохранились - переустановил Телеграм на старую версию. Возможно, что баг не в самом клиенте, а где-то на серверах Телеграма. Но тем не менее, разработчикам виднее.

Google Translate:

- Exactly every 4-5 days an account flies out (the first one added to the client, the rest does not apply - only 4 accounts in the client), while deleting messages for the last 2 days. Only my messages are deleted from the interlocutors, their messages remain intact. And it crashes not only in the client, but in general IN ALL clients, including mobile ones. I don’t remember such a function that there was a crash directly on all devices. I know that you can cut off one client in the settings, but not all at once.
- At first I sinned against the version from the Microsoft store, because before that I used versions from the official Telegram website and everything was fine. True, I don’t remember the version of the DO store and the store, alas. But, as a rule, always immediately updated to a new one. I put back the version from the site, the problem remained. Version 4.6.5. A friend has 4.6.4, he does not have such a problem. It is possible that it was in 4.6.5 that the bug hid.
- Maybe a coincidence, but it crashes after I wrote / am writing a post for the channel in my favorites. And it crashes suddenly - no warning, no windows, just goes out on all devices at once.
- The problem is observed not only at me. I talked with the advertiser, she said that she also flies out of her account and messages are deleted.
- Takes off at about 21:00 Moscow time, give or take. Then you need to log in on all devices again.
- Logs, unfortunately, were not preserved - reinstalled Telegram to the old version. It is possible that the bug is not in the client itself, but somewhere on the Telegram servers. But nevertheless, the developers know better.

### Expected behaviour

-

### Actual behaviour

-

### Operating system

Windows 11

### Version of Telegram Desktop

4.6.5

### Installation source

Static binary from official website

**Comment by RERCON0** [comment]
![image](https://user-images.githubusercontent.com/100621006/222235479-04ac941d-0404-45f6-9347-ea76ca91fb58.png)
Скрин переписки, где нет моих сообщений, но есть сообщения собеседника. У него моих сообщений тоже нет.

**Comment by RERCON0** [comment]
![image](https://user-images.githubusercontent.com/100621006/222241544-7c1664da-d5c7-4300-b917-96e470ea4208.png)
Переписка с рекламодателем, у которой возникает такая же проблема.

**Comment by john-preston** [comment]
@RERCON0 Can you share your username on Telegram? Or just contact me at t.me/preston

**Comment by joreikarr** [comment]
Не решили проблему?

**Comment by RERCON0** [comment]
> Не решили проблему?

По всей видимости, решил. Написал разработчику и обновил десктопную версию на бету. Сейчас стоит последняя бета. По срокам, вчера должен был быть вылет, но его не было. Ну и авторизовался в десктопе первым с 4 аккаунта, тестового. Даже он не вылетел. Хотя обычно, по наблюдениям, именно первый добавленный вылетал

**Comment by joreikarr** [comment]
А есть инфа, как обновиться? 
У меня страдают 5 человек разом от постоянных потерь диалогов с клиентами)

**Comment by RERCON0** [comment]
> А есть инфа, как обновиться? 
> 
> У меня страдают 5 человек разом от постоянных потерь диалогов с клиентами)

В настройках -> продвинутые нужно включить "устанавливать beta-версии". Либо просто с гитхаба скачать самую последнюю версию. Постоянно на бетках сидеть тоже не стоит, но пока нужно обновиться

**Comment by joreikarr** [comment]
Понял, спасибо огромное)

**Comment by Slavka20001** [comment]
> ### Steps to reproduce
> * Ровно каждые 4-5 дней вылетает аккаунт (первый добавленный в клиент, остальных это не касается - всего 4 аккаунта в клиенте), удаляя при этом сообщения за последние 2 дня. Удаляются только мои сообщения у собеседников, их сообщения остаются в целости. И вылетает не только в клиенте, а вообще ВО ВСЕХ клиентах, в том числе мобильных. Такой функции, чтобы прям на всех устройствах был вылет, не припомню. Знаю, что можно отрубать в настройках по одному клиенту, но чтобы все разом, нет.
> * Сперва грешил на версию из Майкрософт стор, ибо до этого пользовался версий с официального сайта Телеграм и всё было нормально. Правда версию ДО стора и сторовскую не помню, увы. Но, как правило, всегда сразу обновлял на новую. Поставил обратно версию с сайта, проблема осталась. Версия 4.6.5. У друга стоит 4.6.4, у него такой проблемы не наблюдается. Возможно, что именно в 4.6.5 баг затаился.
> * Может совпадение, но вылетает после того, когда написал/пишу пост для канала в избранном. И вылетает внезапно - ни предупреждения, ни окон, просто выходит на всех устройствах разом.
> * Проблема наблюдается не только у меня. Общался с рекламодателем, она сказала, что у неё тоже вылетает из аккаунта и удаляются сообщения.
> * Вылетает примерно в 21:00 по мск, плюс-минус. После чего требуется входить на всех устройствах снова.
> * Логи, к сожалению, не сохранились - переустановил Телеграм на старую версию. Возможно, что баг не в самом клиенте, а где-то на серверах Телеграма. Но тем не менее, разработчикам виднее.
> 
> Google Translate:
> 
> * Exactly every 4-5 days an account flies out (the first one added to the client, the rest does not apply - only 4 accounts in the client), while deleting messages for the last 2 days. Only my messages are deleted from the interlocutors, their messages remain intact. And it crashes not only in the client, but in general IN ALL clients, including mobile ones. I don’t remember such a function that there was a crash directly on all devices. I know that you can cut off one client in the settings, but not all at once.
> * At first I sinned against the version from the Microsoft store, because before that I used versions from the official Telegram website and everything was fine. True, I don’t remember the version of the DO store and the store, alas. But, as a rule, always immediately updated to a new one. I put back the version from the site, the problem remained. Version 4.6.5. A friend has 4.6.4, he does not have such a problem. It is possible that it was in 4.6.5 that the bug hid.
> * Maybe a coincidence, but it crashes after I wrote / am writing a post for the channel in my favorites. And it crashes suddenly - no warning, no windows, just goes out on all devices at once.
> * The problem is observed not only at me. I talked with the advertiser, she said that she also flies out of her account and messages are deleted.
> * Takes off at about 21:00 Moscow time, give or take. Then you need to log in on all devices again.
> * Logs, unfortunately, were not preserved - reinstalled Telegram to the old version. It is possible that the bug is not in the client itself, but somewhere on the Telegram servers. But nevertheless, the developers know better.
> 
> ### Expected behaviour
> 
> ### Actual behaviour
> 
> ### Operating system
> Windows 11
> 
> ### Version of Telegram Desktop
> 4.6.5
> 
> ### Installation source
> Static binary from official website
> 
> ### Logs
> _No response_

Здравствуйте! У меня такая же проблема. Вылетает автоматом. Как вы ее решили?

**Comment by lfcbastion** [comment]
Аналогичная проблема, выбило с 4-х аккаунтов разом, до этого пару раз сбрасывало только с основного. Как понял, проблему эту никому не удалось решить и приходится ждать когда получается зайти в канал чтобы тебя мигом не сбрасывало

Вопрос первый, у кого как долго по времени длится проблема с авторизацией? После первого сброса авторизоваться смог только минут через 20, после второго не мог зайти часа два, после последнего сброса не могу зайти уже больше 12 часов. Авторизуюсь и моментально все вылетает.

Вопрос второй, на одном из аккаунтов не было 2-факторки, СМС-ка и звонок не приходят, а тг-просит код из служебного чата (доступа к которому нет), можно с аккаунтом прощаться или есть какие-то костыли как можно вернуть доступ ?

**Comment by Aokromes** [comment]
this bug tracker is english only.

**Comment by akira1401** [comment]
обращаюсь к вам с проблемой по поводу своего рабочего аккаунта телеграмм. На ежедневной основе я обрабатываю порядка 15-30 новых клиентов, помимо этого ко мне обращаются и старые клиенты которых я консультирую.

Где-то в начале апреля 2023 года, мой аккаунт впервые выбило со всех устроиств, на 26 апреля я сталкиваюсь с такой проблемой уже на протяжении трёх дней, обычно выбивает с аккаунта в период с 10:00 до 13:00 по Московскому времени.
Приложение телеграмм есть на Windows, версия телеграмм 4.8.1 x64. 
Приложение телеграмм так же есть на ios, версия обновлена последняя 

Так же после того я захожу на аккаунт, наблюдаю такую проблему что диалоги со многими клиентами у меня стираются, а точнее мои сообщения которые я отправлял клиентам за последние два дня (~48 часов) 
Как мне решить данную проблему?
