### ISSUE TITLE
Add proxy rotation or auto proxy swich like in Telegram for Android

### ISSUE THREAD

**Issue by pouriaksrvi** [telegramdesktop/tdesktop#25978]
### Is your feature request related to a problem?

In some countries, proxies available/unavailable state gets changed too frequently.
So the user should open the proxy window and switch between proxies too many times.

### Describe the solution you'd like

Each time the current proxy gets unavailable, the app should start testing proxies, one by one, from the newest proxy (latest added) to the oldest proxy (least availability chance), and connect to the first available proxy it finds.

**Comment by Aokromes** [comment]
you may want to upvote this
https://bugs.telegram.org/c/23721

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25145
