### ISSUE TITLE
Feature Request: Compact Contact Pane

### ISSUE THREAD

**Issue by SashaGelert** [telegramdesktop/tdesktop#2597]
Linux Mint 18 Sarah 64-bit
Kernel 4.4.0-43-genericx86_64
Telegram 0.10.19

Wasn't sure where else to put this, and it also doesn't quite fit your error reporting form.  While the Telegram API may be nice and open, I'm not a practiced coder, but would love to see the option for a 'compact' contact panel like other messengers allow for.  I keep my GUI at 100%, and at 1080P, that's 14 users, which is only half of all whom I keep up with weekly.  If there was a compact option for the contact pane, removing the icons and recent messages, and thus only showing name, sent/read check-marks, and the time of last message, it's be appreciated.

I could honestly think of a dozen little tweaks I'd make to the gui, but that would be the main one to benefit from.

**Comment by Aokromes** [comment]
#314
