### ISSUE TITLE
[Bug] Can't use second account "telegram search" while the first one has a picture opened

### ISSUE THREAD

**Issue by bob27aggiustatutto** [telegramdesktop/tdesktop#25973]
### Steps to reproduce

1. Own 2 telegram accounts
2. Open both using the new "ctrl+click" feature
3. Open a picture in the first account window
4. Try to use the telegram search bar in the second account

### Expected behaviour

You can use the search bar in the second account

### Actual behaviour

You can't use the search bar in the second account

### Operating system

Win 10

### Version of Telegram Desktop

4.6.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#25909?

**Comment by john-preston** [comment]
Are you talking about multiple-monitor setup with one having a fullscreen picture opened?

Because it works for me if I open picture in a windowed mode viewer (available at 4.6.5 version and later).

**Comment by bob27aggiustatutto** [comment]
> Are you talking about multiple-monitor setup with one having a fullscreen picture opened?
> 
> Because it works for me if I open picture in a windowed mode viewer (available at 4.6.5 version and later).

To be fair it happens in 4.6.3, I haven't tested in 4.6.5.

I'll test it today and I will tell you if we can close this, thank you

**Comment by bob27aggiustatutto** [comment]
Tested and I can confirm it's fixed in 4.6.5.

I'll close this. Thank you.
