### ISSUE TITLE
guys what did you break again in calls

### ISSUE THREAD

**Issue by oksakhartman** [telegramdesktop/tdesktop#25985]
### Steps to reproduce

take any android phone - call the desktop - get a charsh

this happened after yesterday's desktop update

guys, stop breaking your own services, I have never seen such a level of instability in any company in the world

### Expected behaviour

normal operation of calls, as in skype, whatsapp, anywhere

### Actual behaviour

here is the actual behavior for you - you press accept the call, you get a crash

ApiId: 2040
Assertion: "_state.current() == State::Starting" calls_call.cpp:334
Binary: Telegram
Launched: 02.03.2023 12:01:04
OpenGL: Disabled
OpenGL Renderer: [not-initialized]
Platform: Linux
UserTag: 8b340b2bd82146e1
Version: 4006006 beta

Caught signal 6 (SIGABRT) in thread 139899214798272
Google Breakpad caught a crash, minidump written in thread 139899214798272
Minidump: /home/q/.local/share/TelegramDesktop/tdata/dumps/c9842593-42f1-4ef0-d16a3cab-b17943da.dmp

### Operating system

ubuntu lts

### Version of Telegram Desktop

latest

### Installation source

Static binary from official website

### Logs

```shell
ApiId: 2040
Assertion: "_state.current() == State::Starting" calls_call.cpp:334
Binary: Telegram
Launched: 02.03.2023 12:01:04
OpenGL: Disabled
OpenGL Renderer: [not-initialized]
Platform: Linux
UserTag: 8b340b2bd82146e1
Version: 4006006 beta

Caught signal 6 (SIGABRT) in thread 139899214798272
Google Breakpad caught a crash, minidump written in thread 139899214798272
Minidump: /home/q/.local/share/TelegramDesktop/tdata/dumps/c9842593-42f1-4ef0-d16a3cab-b17943da.dmp
```

**Comment by ChankitSaini** [comment]
I am experiencing the same problem with the Windows version of Telegram Desktop application.

**Comment by ChankitSaini** [comment]
> I am experiencing the same problem with the Windows version of Telegram Desktop application.

Logs:

[2023.03.02 15:42:02] OpenGL: [TRUE] (Window)
[2023.03.02 15:42:08] Assertion Failed! "_state.current() == State::Starting" calls_call.cpp:334

**Comment by RememberTheAir** [comment]
As a reminder, you're subscribed to the beta channel. Things are expected to break.

**Comment by oksakhartman** [comment]
seems yes

in 4.6.5 - all is okay

in 4.6.* - it`s broken

**Comment by ChankitSaini** [comment]
> As a reminder, you're subscribed to the beta channel. Things are expected to break.

and we are expected to report them, aren't we?

**Comment by oksakhartman** [comment]
> and we are expected to report them, aren't we?

I have contributed

I hope they didn't break mobile clients as well

**Comment by ilya-fedin** [comment]
> and we are expected to report them, aren't we?

I guess he is written that due to

> guys, stop breaking your own services, I have never seen such a level of instability in any company in the world

**Comment by oksakhartman** [comment]
> Beta testers are exactly who is supposed to prevent such breakages from appearing in stable releases.

are you laughing

your elementary calls do not work between your official clients

your
official
clients

official - means official 

it does not fit into any framework

Do you have someone testing this before rolling it out to release?

I have not seen this anywhere

in February someone broke backwards compatibility with libtgvoip with ios client

libtgvoip is a great library that has worked STABLE for 5 years

And now what's in her place?
tgcalls in which there are several versions of protocols
which are incompatible with each other
and in which something constantly breaks and gets worse and worse

**Comment by ilya-fedin** [comment]
> Do you have someone testing this before rolling it out to release?

That's the thing, you're not using a release version, you're using a beta version. If you want a to get only stable updates, please switch to the stable release.

**Comment by oksakhartman** [comment]
> That's the thing, you're not using a release version, you're using a beta version. If you want a to get only stable updates, please switch to the stable release. Don't forget to disable installation of beta versions in settings if you won't uninstall the current version with all the data first.

it's not even a beta release

the thing is that call in telegram

constantly breaking down

constantly

It's not just about desktop.

just stop doing it

**Comment by ilya-fedin** [comment]
@oksakhartman this is tdesktop-only bugtracker. If you want to raise concerns about other clients, please use in-app support or https://bugs.telegram.org.

**Comment by Aokromes** [comment]
Crash ID: 0d7ea190-a0e2-48d8-a682-c77f525d84b9

**Comment by john-preston** [comment]
Sorry, beta is beta. I'll deploy a fix later today.

**Comment by john-preston** [comment]
(the crash isn't related to libtgovip or it replacement, because it happens in the UI code before any calls library is getting used)

**Comment by oksakhartman** [comment]
> (the crash isn't related to libtgovip or it replacement, because it happens in the UI code before any calls library is getting used)

the argument was that libtgvoip is the most stable part of everything that was created in tg
Grishka knew how to write truly stable things that worked for years without interference.

**Comment by john-preston** [comment]
This week I still fixed another one of "uninitialized memory read" bug in libtgvoip which is one of the possible sources of serious security vulnerabilities. Several years after it was written.

Several hard detected threading problems were debugged and fixed by me in libtgvoip over the years.

I don't want to say anything bad about Grishka, I have no complaints about his work - but we all make mistakes, sometimes serious, sometimes critical.

Praising this library as head taller than all other code in Telegram would be strange to me.

PS. You can go to Settings >Advanced and uncheck "Install beta versions" checkbox. After that you'll be updated only to (next released!) stable versions. Although I suggest installing the next beta release first, which will fix this crash.

Downgrading versions isn't supported, so you can manually install older stable version, but you'll loose authorization and some local settings.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/ccbab25fae81923f7af2b81bb392e22b21d707b9
