### ISSUE TITLE
[Feature Request] Do not count Test Server accounts within connected accounts limit

### ISSUE THREAD

**Issue by condemil** [telegramdesktop/tdesktop#25982]
### Is your feature request related to a problem?

Currently it is possible to create only 3 accounts on free and 6 accounts on premium, no matter is it production server accounts or test server accounts.

### Describe the solution you'd like

It would be nice to allow unlimited account creation for test server and do not count test accounts within production account limit.

### Describe alternatives you've considered

If unlimited account creation is not an option, it could be a higher limit for a test server and still count test accounts and production accounts separately.

**Comment by john-preston** [comment]
Maybe you can "buy" premium for your test accounts? I thought it accepts test payments (without real money), like "4242 4242 4242 4242" card with arbitrary expiration date / name / cvc.

**Comment by condemil** [comment]
I tried to "buy" premium for test accounts, but it doesn't accept test payments.

**Comment by john-preston** [comment]
@condemil I was told that it should work. Can you share a screencast of how it doesn't accept them?

**Comment by condemil** [comment]
![Screenshot from 2023-03-03 18-05-37](https://user-images.githubusercontent.com/722990/222693574-f7192ba9-8063-4368-98d6-d3b0d4597811.png)

![Screenshot from 2023-03-03 18-09-04](https://user-images.githubusercontent.com/722990/222693653-6d1e7cfd-9888-45c5-9c77-f96d78ca2558.png)

![Screenshot from 2023-03-03 18-09-55](https://user-images.githubusercontent.com/722990/222693702-7093e39a-e340-4315-a325-2e08da9317ca.png)

![Screenshot from 2023-03-03 18-10-11](https://user-images.githubusercontent.com/722990/222693736-8deb6bb4-b87c-49da-9612-6ee377a37774.png)

![Screenshot from 2023-03-03 18-10-27](https://user-images.githubusercontent.com/722990/222693754-4cf95b96-8ee4-42a9-8c78-e6cac8f99dc7.png)

![Screenshot from 2023-03-03 18-10-40](https://user-images.githubusercontent.com/722990/222693769-8cac0de8-8005-415d-a0c7-ae0b77cd87ac.png)

**Comment by john-preston** [comment]
Ok, I'll treat all test mode accounts as premium accounts in the accounts limit.
