### ISSUE TITLE
Images have weird dark shadows on macOS

### ISSUE THREAD

**Issue by Brawl345** [telegramdesktop/tdesktop#25988]
### Steps to reproduce

1. Open an image in the default fullscreen viewer

### Expected behaviour

Image should be display normally

### Actual behaviour

Images have weird black shadows over them (looks like folded paper). This seems to be some bug in the overlay (where the next/previous arrows and the description + date + etc.) are because it's displayed correctly when they hide after a few seconds. Happens since 4.6.6 beta I think.

Wrong: 
![wrong](https://user-images.githubusercontent.com/5049892/222532043-6c0fa9ca-8f8a-4b9f-bf9e-3ff4748c280f.png)

Correct (after a few seconds when the overlay is hidden):
![correct](https://user-images.githubusercontent.com/5049892/222532134-4a3a88a5-0f94-4635-9c92-87272e0de17c.png)

### Operating system

macOS Ventura 13.1 (22C65)

### Version of Telegram Desktop

4.6.7 beta

### Installation source

Static binary from official website

**Comment by Brawl345** [comment]
Now images are too small since v4.6.9 beta. They get shown in the lower right corner instead of centered...

**Comment by john-preston** [comment]
Can you show a screenshot please.

**Comment by Brawl345** [comment]
Here:

![image](https://user-images.githubusercontent.com/5049892/224483486-693e8f9f-ed33-4820-87ff-4c5084e93b93.png)

**Comment by john-preston** [comment]
@Brawl345 How do you do that? :)

What is the monitor setup? (how many monitors, which ones are retina and which not, which monitor the Telegram is started on, which monitor is the media viewer opened on)

**Comment by Brawl345** [comment]
I have one external FHD non-Retina monitor. Telegram is started on the external monitor and the media viewer is also there.

**Comment by john-preston** [comment]
@Brawl345 One external and also one main retina screen?

**Comment by Brawl345** [comment]
Yes! Macbook Pro 2021 16"

**Comment by Brawl345** [comment]
It's correct if I move the main Telegram window to the internal screen, open an image, close it and then move Telegram to the external monitor. These weird shadows still overlay the image though:

![image](https://user-images.githubusercontent.com/5049892/224561603-c552a7fc-9119-43a8-abc4-133ddae6fea9.png)

Tested with v4.6.10 beta.

**Comment by john-preston** [comment]
@Brawl345 I hope I've fixed this for the next release.

**Comment by Brawl345** [comment]
Fixed in v4.6.11, thanks!!!

![image](https://user-images.githubusercontent.com/5049892/225520641-87af9e36-2329-493f-bef4-b7c59b491ce4.png)
