### ISSUE TITLE
Without notification sound if the window is open but not with focus

### ISSUE THREAD

**Issue by manalista** [telegramdesktop/tdesktop#25987]
### Steps to reproduce

When I'm using Telegram and in a conversation with a contact. I don't get the notification sound if the window is open but not with the focus.
For getting the sound, I need to close the window.

### Expected behaviour

The app should send the notification sound when the window is not focused.

### Actual behaviour

The app mark the conversation as read without I have seen it.

### Operating system

Fedora 37 (WE) Wayland - Gnome 33

### Version of Telegram Desktop

4.6.5

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Ensure you don't have any experimental setting enabled
