### ISSUE TITLE
Not showing photo after re-opening

### ISSUE THREAD

**Issue by 0-x-f** [telegramdesktop/tdesktop#25989]
### Steps to reproduce

1. Open Telegram
2. Open photo
3. Close photo by click on the top right "x" 
4. Open photo again

### Expected behaviour

Opens window with photo

### Actual behaviour

Opened window without photo, but with my desktop background (or another window in some cases)

https://user-images.githubusercontent.com/112123895/222551413-6aa661ed-dc13-428d-9585-342b9b3ec87a.mp4

### Operating system

Arch Linux x86_64, dwm

### Version of Telegram Desktop

4.6.5-2

### Installation source

Other (unofficial) source

### Logs

```shell
> pacman -Q --info telegram-desktop

Name            : telegram-desktop
Version         : 4.6.5-2
Description     : Official Telegram Desktop client
Architecture    : x86_64
URL             : https://desktop.telegram.org/
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : hunspell  ffmpeg  hicolor-icon-theme  lz4  minizip  openal  ttf-opensans  qt6-imageformats  qt6-svg  qt6-wayland
                  qt6-5compat  xxhash  glibmm-2.68  rnnoise  pipewire  libxtst  libxrandr  jemalloc  abseil-cpp  libdispatch
                  openssl-1.1  protobuf
Optional Deps   : webkit2gtk: embedded browser features [installed]
                  xdg-desktop-portal: desktop integration
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 81.49 MiB
Packager        : Sven-Hendrik Haase <svenstaro@gmail.com>
Build Date      : Mon Feb 27 16:52:59 2023
Install Date    : Thu Mar 2 11:55:09 2023
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by Aokromes** [comment]
plz try downloading official static beta (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by 0-x-f** [comment]
@Aokromes yep, with 3.6.7 it's working correctly. I forget that Telegram updates on AUR with delay.
