### ISSUE TITLE
Enhancement: Disable/Decrease Telegram Sticker Sizes

### ISSUE THREAD

**Issue by popey456963** [telegramdesktop/tdesktop#2598]
Telegram is an amazing chat client, it's the one I use for just about everything, due to the fact it can be used for both company and personal work.  The one issue I have with it though are stickers.

At the moment they are far too large, massively so on my desktop.  I have Telegram in what I assume is the default size (I can get roughly 11 messages on a screen), yet I can only get 2 and a bit stickers?  If even just two people use a sticker, it obliterates any other conversation we're having.

Now, obviously, stickers in modicum are cool.  And in no way am I asking for them to removed, what I was hoping for was an option to either make them appear to be smaller (so as to spam the chat less) or to be able to disable them automatically.  You already have a section which seems to fit well, and even has a topic on Emoji in it:

![](https://puu.sh/s5fH1/340c2c5291.png)

Considering I imagine for the disable option it would literally be just an added option and an `if` statement, I would even be willing to take a shot at doing it myself if people feel this would be a good idea & someone could point me in the right direction.

**Comment by popey456963** [comment]
I do realise this has been asked on two occasions before, but both were before Jan last year, so I was hoping we could have another discussion about this topic.

**Comment by stek29** [comment]
@popey456963 you should never ever create duplicates.
You could "bump" old issue if you want.

**Comment by popey456963** [comment]
Eh, that's a fair point in this situation,  my mistake.  However, I think there are certain scenarios when a duplicate might be the best option.  For instance when the old issue contains so many off-topic discussions that it becomes unmanageable, a newer and more focused issue might be suitable.

In any case, I feel this should still be discussed again, it seems to be a major issue that everyone in my ~40 person group agrees on.  There was a pull request ages ago that was made to add an option, but because it was so long ago it seems that code has now been changed again and this has led to merge conflicts ([#260](https://github.com/overtake/telegram/pull/260/files)).  Was there a reason this wasn't pulled in at the time?  And would it be pulled in now were it to be updated to not have merge conflicts anymore?

**Comment by stek29** [comment]
Wait, are you talking about Native macOS App or TDesktop?

**Comment by popey456963** [comment]
TDesktop, sorry for my lack of mentioning that.

**Comment by stek29** [comment]
@popey456963 You linked to pull request on Native macOS App repo.

**Comment by popey456963** [comment]
@stek29 Oh shoot, so I did.  Would a similar pull request for TDesktop be accepted if it worked?

**Comment by stek29** [comment]
@popey456963 [I doubt it would](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#what-contributions-are-accepted), but we can't know for sure because it wasn't made.

**Comment by armandaneshjoo** [comment]
I agree that stickers are too large.

**Comment by Aokromes** [comment]
#735

**Comment by guai** [comment]
How is it closed? Stickers are still collossal. Was they even bigger?

**Comment by Aokromes** [comment]
duplicate of ticket 735.

**Comment by guai** [comment]
@Aokromes, #735 is locked, lets reopen this one and bump it

**Comment by auchri** [comment]
@guai No

**Comment by stek29** [comment]
@guai Let's unlock #735 so github reactions can work, but delete non-related comments and '+1's without a single warning, and lock it back if amount of spam becomes massive again.

**Comment by guai** [comment]
@stek29, ok, or even better someone to resolve it already

**Comment by Aokromes** [comment]
you are free to send one pull request implementing the feature :P

**Comment by guai** [comment]
@Aokromes, not the best idea, I haven't used cpp for about a decade now.
