### ISSUE TITLE
Telegram doesn't appear in System Tray [Linux Kali/Debian]

### ISSUE THREAD

**Issue by eliasfaisal** [telegramdesktop/tdesktop#25992]
### Steps to reproduce

1 Just run telegram normally, and click close button in the window top bar

### Expected behaviour

telegram minimized to system tray normally

### Actual behaviour

telegram doesn't appear in the system tray, and when click close doesn't minimize to system tray and do not terminate

### Operating system

Kali Linux amd64 4.19.0, Debian 4.19.13-1, XFCE 4.12.0

### Version of Telegram Desktop

v 4.6.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Provide the result of `busctl --user --no-pager status org.kde.StatusNotifierWatcher`

**Comment by DimonBor** [comment]
> Provide the result of `busctl --user --no-pager status org.kde.StatusNotifierWatcher`

I've got the following error:
``` bash
$ busctl --user --no-pager status org.kde.StatusNotifierWatcher
Failed to get credentials: No such device or address
```

**Comment by ilya-fedin** [comment]
can you provide log.txt from the tdesktop data folder?

**Comment by ilya-fedin** [comment]
Maybe you have 'Close to taskbar' setting enabled?

**Comment by DimonBor** [comment]
> Maybe you have 'Close to taskbar' setting enabled?

Nope, I've checked this before
![image](https://user-images.githubusercontent.com/40671393/222750950-ceb1bba2-a6a0-409e-af44-f19a1827bbc1.png)

**Comment by DimonBor** [comment]
> Maybe you have 'Close to taskbar' setting enabled?

Well, yes, it was enabled. But it doesn't make changes. No tray icon in both cases.

**Comment by ilya-fedin** [comment]
Well, there of course won't be tray icon, but without this setting application should exit on window close. There's no tray option as your system has no tray support.

**Comment by DimonBor** [comment]
I have an extension for GNOME, that provides tray functionality. Slack and JetBrains Toolbox are both fine with it.
![image](https://user-images.githubusercontent.com/40671393/222752140-b0c659f0-c285-4b73-82de-80c56b242e24.png)

**Comment by DimonBor** [comment]
> Well, there of course won't be tray icon, but without this setting application should exit on window close. There's no tray option as your system has no tray support.

Even though GNOME has no tray by default, XFCE has one.

**Comment by ilya-fedin** [comment]
> I have an extension for GNOME, that provides tray functionality. Slack and JetBrains Toolbox are both fine with it.

You likely have a tray that works through X11, so only Xwayland applications can use it.

> Even though GNOME has no tray by default, XFCE has one.

@eliasfaisal has likely another issue then

**Comment by DimonBor** [comment]
> > I have an extension for GNOME, that provides tray functionality. Slack and JetBrains Toolbox are both fine with it.
> 
> You likely have a tray that works through X11, so only Xwayland applications can use it.
> 
> > Even though GNOME has no tray by default, XFCE has one.
> 
> @eliasfaisal has likely another issue then

It makes sense. Just checked Slack and JetBrains Toolbox with `xeyes` and they are running through XWayland. That's my bad, sorry.

**Comment by eliasfaisal** [comment]
> > I have an extension for GNOME, that provides tray functionality. Slack and JetBrains Toolbox are both fine with it.
> 
> You likely have a tray that works through X11, so only Xwayland applications can use it.
> 
> > Even though GNOME has no tray by default, XFCE has one.
> 
> @eliasfaisal has likely another issue then

i have noticed that my XFCE PANEL Restarts when i open telegram, sometimes it appears in tray and other times it doesnt.

**Comment by ilya-fedin** [comment]
> i have noticed that my XFCE PANEL Restarts when i open telegram, sometimes it appears in tray and other times it doesnt.

I'm still waiting for the result of the command I aked you to provide in my first message

**Comment by ilya-fedin** [comment]
Are you working from root user?

**Comment by eliasfaisal** [comment]
> Are you working from root user?

yes

**Comment by ilya-fedin** [comment]
Is this a regression from Telegram side (i.e. do you know a version which worked previously and can you check whether it still works?)? If not, given that you have panel restarts, I would assume it's a bug on Xfce side, panel crashes and loses the icons.

**Comment by eliasfaisal** [comment]
> Is this a regression from Telegram side (i.e. do you know a version which worked previously and can you check whether it still works?)? If not, given that you have panel restarts, I would assume it's a bug on Xfce side, panel crashes and loses the icons.

i tried to run from the terminal it works good with no issues and appears in system tray without restarting the panel, but when do from applications menu problem stays the say. the version was working without issues was 3.7.3

**Comment by ilya-fedin** [comment]
Indeed, 3.7.4 had a tray icon code rewrite. Can you bisect it to find the commit at fault?
