### ISSUE TITLE
Ubuntu 22.04 crashes when an image is opened and the window is moved to another monitor.

### ISSUE THREAD

**Issue by laraws** [telegramdesktop/tdesktop#25996]
### Steps to reproduce

1. Open a image on Telegram app.
2. Move the window to another monitor.

### Expected behaviour

No system crash happen.

### Actual behaviour

System crash.

### Operating system

Ubuntu22.04

### Version of Telegram Desktop

4.6.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Enable beta versions in advanced settings, reproduce the crash, copy the crash id from the crash reporter that will appear on next launch. Don't forget to push send button in the reporter.

**Comment by laraws** [comment]
> Enable beta versions in advanced settings, reproduce the crash, copy the crash id from the crash reporter that will appear on next launch. Don't forget to push send button in the reporter.

I updated to the beta version as you suggested, and I was able to reproduce the crash. However, I didn't see any crash reporter on the next launch.

**Comment by ilya-fedin** [comment]
Ah, you say your system crashes. Then it's a bug in your system, tdesktop shouldn't be able to crash your system.

**Comment by Aokromes** [comment]
maybe it's hardware issue, i suggest you to memcheck your system.

**Comment by ilya-fedin** [comment]
Well, there seem to be a lot of reports 'system crahses after some actions' from Ubuntu users lately, so I would say it's just gnome-shell code is buggy.

**Comment by laraws** [comment]
> Well, there seem to be a lot of reports 'system crahses after some actions' from Ubuntu users lately, so I would say it's just gnome-shell code is buggy.

Yes, It could be just gnome-shell's bug. After I updated the system packages using `apt upgrade` command, the issue was fixed.
