### ISSUE TITLE
Telegram Desktop 4.6.5 update brokes built-in Media viewer

### ISSUE THREAD

**Issue by alexeynl** [telegramdesktop/tdesktop#25999]
### Steps to reproduce

1. Update from 4.6.3 to  4.6.5.
2. Open any channel.
3. Click on video or image to view.
4. Settings -> Advanced -> ANGLE graphic backend should be set to Disabled.

### Expected behaviour

Full screen windows with photo or video should appears on screen.

### Actual behaviour

There is no window with photo or video appears. When click on video i listen only sound. Also there no any navigations buttons. To close it only possible with Escape button.

### Operating system

Windows 11

### Version of Telegram Desktop

4.6.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by alexeynl** [comment]
I have already tried install beta. Install it again now - same problem.

**Comment by john-preston** [comment]
@alexeynl Why do you disable ANGLE?

**Comment by alexeynl** [comment]
This only solution (workaround) i found for the following problem. When ANGLE is enabled in Telegram after telegram opened for some time i have the followin behaviour:

1. In Telegram. When i click on video or image in channel to view i see for a second as previous opened video or image appears first.
2. In Telegram. When i click on video or image in channel  to view it start to freeze for a second before opened .
3. In opened Chromium based browsers switching between tabs start to freeze too. Btw Chromium based browsers also uses ANGLE.

**Comment by Aokromes** [comment]
btw, what's your gfx card and drivers version?
i tested on i5-4570 cpu and works for me.

**Comment by alexeynl** [comment]
I have Ryzen 6800h (with 680m integrated graphic) + Nvidia RTX 2050 (mobile). Yes agree i have hardware specific problem. Btw i tried reinstall windows (both 10 and 11), graphic drivers.

**Comment by alexeynl** [comment]
Currently installed drivers:

AMD Adrenaline 23.2.2:

APU - AMD Radeon(TM) Graphics - Основной/Интегрированный
Видеопамять - 512 MB - LPDDR5 800 MHz
Версия драйвера - 22.40.33.01-230217a-388766C-AMD-Software-Adrenalin-Edition
Версия драйвера AMD для Windows - 31.0.14033.1012
Версия Direct3D API - 12.1
Vulkan™ API Version - 1.3.237
OpenCL™ API Version - 2.0
OpenGL® API Version - 4.6
Direct3D® Driver Version - 9.14.10.01525
Vulkan™ Driver Version - 2.0.250
OpenCL® Driver Version - 31.0.14033.1012
OpenGL® Driver Version - 23.02.221211_b5b27f1
Версия 2D-драйвера - 8.1.1.1634
Путь к файлу драйвера 2D - /REGISTRY/MACHINE/SYSTEM/CurrentControlSet/Control/Class/{4d36e968-e325-11ce-bfc1-08002be10318}/0000
Версия пользовательского интерфейса - 2023.0217.1326.1963
Версия аудиодрайвера AMD - 10.0.1.24
Поставщик драйвера - Advanced Micro Devices, Inc.
Версия Windows - Windows 11 Professional (64 bit)
Версия Windows - 22H2

Nvidia Drivers 528.49 Game Ready

**Comment by alexeynl** [comment]
I have found a workaround for problem with Telegram 4.6.5 + ANGLE disabled.

In the Windows display option have 200% as default (recommended) scalling. If i change this setting to 225% or 175% images and videos start to open correctly in Telegram. But this not an option for me. 200% scalling is best comfortable for my display.

**Comment by Aokromes** [comment]
eh amd gfx are known having issues with telegram.

**Comment by alexeynl** [comment]
Ah... Is it possible to fix? Are there any thread to read about how users to solve this?

**Comment by Aokromes** [comment]
> Ah... Is it possible to fix? Are there any thread to read about how users to solve this?

not the same but maybe related.
https://github.com/telegramdesktop/tdesktop/issues/7099 

report bug here https://www.amd.com/es/support/kb/faq/amdbrt
workarround https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-992841213

**Comment by alexeynl** [comment]
> workarround [#7099 (comment)](https://github.com/telegramdesktop/tdesktop/issues/7099#issuecomment-992841213)

Unfortunately it does not work for me.

**Comment by alexeynl** [comment]
What was changed from 4.6.3 to 4.6.5 in term of graphic?

**Comment by alexeynl** [comment]
I reproduced problem with several ways and record a video. You can check it here:

https://youtu.be/7TmNezuC55Q

**Comment by alexeynl** [comment]
During the record this video i notice that Telegram Media viewer interface is defferent in 4.6.3 and 4.6.5. So i guess Media viewer was changed and this cause the problem with it in new version.

**Comment by Perlovka** [comment]
Same on linux. Looks like there is no QA at all. Slap shit together and deploy.

**Comment by alexeynl** [comment]
> try disabling your 2050 GPU from BIOS

This is not possible. This is laptop with limited BIOS. There is no such option.

> there's **only 5%** performance difference between RTX 2050M and Radeon 680M

This is wrong. Difference about twice.

**Comment by alexeynl** [comment]
> feel free to tell TechPowerUp, i'm just saying what's written in their website

I absolutely sure about what i'm saying. I have both in my hand and i ran benchmarks to check.

> you can eliminate bad windows driver problems by booting a recent linux distro Live ISO, with kernel 6.1+ .

I already tried Ubuntu to check. There is no such problems. Using linux instead Windows is not option for daily use. This is absolutely different systems. Linux has a lot of drawback and compromises starting from horrible scrolling to limited set of usefull software.

**Comment by thokr** [comment]
Same on Arch Linux with "Enable OpenGL rendering for media" toggled on in the advanced settings. I have a GTX 1650 SUPER (driver version `525.89.02-7`) and `telegram-desktop` (version `4.6.5-3`).

> I already tried Ubuntu to check. There are no such problems.

I'm pretty sure Ubuntu [is still on 4.1.1](https://packages.ubuntu.com/search?keywords=telegram-desktop&searchon=names&suite=all&section=all). Unless you used snaps of course. Or maybe the OpenGL setting isn't on by default? I don't remember if I set it manually.

**Comment by thokr** [comment]
I just tested on a laptop with Intel iGPU (running Arch Linux as well), with OpenGL rendering enabled, it is not affected by this issue. So yes, it seems to be NVIDIA/driver related.

**Comment by thokr** [comment]
Other interesting thing I forgot to mention is that opening an image/video for the first time after starting the app works just fine. But all subsequent attempts fail. So it *definitely* has the ability to display the images and videos, something just goes wrong after the initialization.

**Comment by ilya-fedin** [comment]
> Same on Arch Linux with "Enable OpenGL rendering for media" toggled on in the advanced settings. I have a GTX 1650 SUPER (driver version `525.89.02-7`) and `telegram-desktop` (version `4.6.5-3`).

Can you provide log.txt? NVIDIA driver is blacklisted by default, so unless you have enabled NVIDIA in experimental settings, this is unexpected behavior

**Comment by thokr** [comment]
Actually... never mind what I said about the OpenGL setting. Turns out OpenGL isn't actually used at all on NVIDIA cards, unless you enable it under Experimental Settings. Without doing that it actually makes no difference whether you have that first OpenGL option toggled. I just didn't test for long enough. Sometimes it works fine for first 2-3 images/videos and only then fails. Very random behavior!

However, enabling *both* "OpenGL rendering for media" in Advanced Settings and "allow OpenGL on the NVIDIA drivers (Linux)" in Expermiental Settings fixes the problem (I tested thoroughly this time).

So it appears to do nothing with NVIDIA but rather AMD CPUs. I have Ryzen 5 5600G.

**Comment by thokr** [comment]
> it seems you are using an unsupported distro package of telegram-desktop, could you confirm that you are actually using the official telegram desktop from the sources mentioned at https://desktop.telegram.org ?

I just tried using the version from the website, same issue there.

> 5600G is an APU with integrated Radeon Vega graphics, there's ambiguity as to which graphics your telegram-desktop is utilising

I'm pretty sure it's rendering on CPU.

**Comment by ilya-fedin** [comment]
log.txt can say whether OpenGL rendering is used and which GPU is used to render for sure

**Comment by thokr** [comment]
Here's the `log.txt` with "OpenGL rendering for media" option enabled and "allow OpenGL on the NVIDIA drivers (Linux)" disabled.

[log_nvidia_disabled.txt](https://github.com/telegramdesktop/tdesktop/files/10949224/log_nvidia_disabled.txt)

**Comment by ilya-fedin** [comment]
I see `OpenGL: Disable on NVIDIA driver on Linux.`, it doesn't use OpenGL at all

**Comment by thokr** [comment]
Yes, that's what I'm saying, it should be rendering on CPU then. The issue vanishes when using OpenGL.

**Comment by john-preston** [comment]
@alexeynl I have no idea how it could break for disabled OpenGL :( It should work exactly as reliable as the main app window. If you have time and desire you can contact me at t.me/preston for long and boring testing of some versions I'll prepare to see at which point it stops appearing.

**Comment by thokr** [comment]
As it turns out, at least on Linux, the issue appears to be solved in 4.6.10. :+1:

**Comment by DarkSilence** [comment]
I've been seeing this problem on my Windows machine for months.
Win 11, Lenovo laptop, RTX3070.
Switching ANGLE mode fixes the problem for some time but it always returns :( Turning ANGLE off doesn't fix the problem permanently.

**Comment by alexeynl** [comment]
The only workaround to use new Media viewer with disabled ANGLE is edit scale factor from default 200% to custom 199% in Display settings:

![image](https://user-images.githubusercontent.com/82229750/226703964-729b29b4-2999-48c8-bdbb-945472157eb2.png)
![image](https://user-images.githubusercontent.com/82229750/226704793-94abff82-3865-45cb-a01e-a9739c73271d.png)

**Comment by alexeynl** [comment]
> @alexeynl Please check 4.7.1 version, it should allow using media viewer with angle disabled with any screen scaling.

Check it just now. The issue is solved. Thank you very much for your support!
