### ISSUE TITLE
Random segfaults while switching desktop with gestures.

### ISSUE THREAD

**Issue by DimonBor** [telegramdesktop/tdesktop#25993]
### Steps to reproduce

1. Open Telegram Desktop
2. Switch a few times to the left/right desktop using three-finger gestures.

### Expected behaviour

No segfaults :)

### Actual behaviour

Segfault

### Operating system

Arch LInux, GNOME 43.3, Wayland

### Version of Telegram Desktop

4.6.5

### Installation source

Flatpak

**Comment by DimonBor** [comment]
Also, there is no difference between Community, AUR, and Flatpak. All the same

**Comment by DimonBor** [comment]
And also I'm experiencing the same issue as described in #25992

**Comment by ilya-fedin** [comment]
```
flatpak install org.freedesktop.Sdk{,.Debug} org.telegram.desktop.Debug
flatpak run --command=sh --devel org.telegram.desktop
gdb /app/bin/telegram-desktop
run
```
After crash: `bt full`

> And also I'm experiencing the same issue as described in #25992

Please discuss in the respective issue

**Comment by DimonBor** [comment]
Here is a log with `WAYLAND_DEBUG=1`. But fir me there are no useful information

[log.txt](https://github.com/telegramdesktop/tdesktop/files/10882353/log.txt)

**Comment by ilya-fedin** [comment]
tdesktop project has no Wayland experts, so it's unlikely to provide useful information for anyone here.

**Comment by DimonBor** [comment]
> ```
> flatpak install org.freedesktop.Sdk{,.Debug} org.telegram.desktop.Debug
> flatpak run --command=sh --devel org.telegram.desktop
> gdb /app/bin/telegram-desktop
> run
> ```
> 
> After crash: `bt full`
> 
> > And also I'm experiencing the same issue as described in #25992
> 
> Please discuss in the respective issue

Hello Ilya,

**Comment by ilya-fedin** [comment]
AFAIK Arch doesn't provide debug symbols, so you can't use Arch package for debugging without rebuilding it from sources.

**Comment by DimonBor** [comment]
OK, give me a few minutes, will reproduce with Flatpak

**Comment by DimonBor** [comment]
OK, it will take a bit more time, since Flatpak downloads are slow for some reason. I will update this as soon as collect the logs.

**Comment by ilya-fedin** [comment]
It might be a better idea to reproduce the crash with https://github.com/telegramdesktop/tdesktop/releases/download/v4.6.7/tsetup.4.6.7.beta.tar.xz and send a crash report. Report back you crash ID here.

**Comment by DimonBor** [comment]
> It might be a better idea to reproduce the crash with https://github.com/telegramdesktop/tdesktop/releases/download/v4.6.7/tsetup.4.6.7.beta.tar.xz and send a crash report. Report back your crash ID here.

Ok, how can I collect the crash report correctly?

**Comment by DimonBor** [comment]
Here it is
Crash ID: `cceeb9b7-4e8c-4af8-c5bd89ad-145ca3c5`

**Comment by ilya-fedin** [comment]
I've asked @john-preston to look into it, in meantime you may have a better success by contributing to #25992

**Comment by DimonBor** [comment]
If it could help @john-preston with his investigation, I could collect coredumps also.

**Comment by ilya-fedin** [comment]
Only he has access to debug symbols of the static binary. The only thing you can do to proceed without @john-preston is to get the trace from flatpak package like I described before.

**Comment by john-preston** [comment]
@DimonBor Unfortunately I don't see such crash in the system :( You can either submit it once again (make sure it did upload successfully and then copy CrashID here) or you can send me at t.me/preston .zip-ed folder ~/.local/share/TelegramDesktop/tdata/dumps with all the crash dumps.

**Comment by DimonBor** [comment]
> @DimonBor Unfortunately I don't see such crash in the system :( You can either submit it once again (make sure it did upload successfully and then copy CrashID here) or you can send me at t.me/preston .zip-ed folder ~/.local/share/TelegramDesktop/tdata/dumps with all the crash dumps.

Hello John, just sent you the dumps

**Comment by ilya-fedin** [comment]
Is this still happening with 4.7.1?

**Comment by john-preston** [comment]
I've seen the dumps, but it crashes somewhere in QWaylandWindow::handleSwipeGesture :( I hope Qt update will fix it.

**Comment by ilya-fedin** [comment]
> Also, @john-preston please note, that issue observed only with telegram client and not any other app

Apparently you have no more Qt 6 applications?

> Hello Illya, yes, I can confirm that the issue is still observed.

This means we somehow have to make a minimal reproducible example to report this to Qt. This is sadly a very time-consuming and I'm not sure anyone would work on that. Although if you would build Qt 6's examples and confirm it's reproducible on those, they could be used instead.

There's also a suspicious thing in the dump: some `linux-gate.so` is being injected between Qt function calls. Is it possible you have some kind of antivirus installed? It's likely to produce the crash.

**Comment by DimonBor** [comment]
@ilya-fedin Yes, you're right. It seems like qt6 issue. I forced my libre office to use qt6 and I can confirm that there is the same issue. 

So is there any change to switch to qt5 in Telegram client?

**Comment by ilya-fedin** [comment]
tdesktop can't work with Qt 5 on Wayland, all the Wayland specific code uses Qt 6 features. The only way forward is to report the bug to Qt. Although, this question is still valid and I still wait for answer on it.

> There's also a suspicious thing in the dump: some `linux-gate.so` is being injected between Qt function calls. Is it possible you have some kind of antivirus installed? It's likely to produce the crash.

It's being injected right before the crashing function. This and the fact no one else has reported this makes me think the problem is in this injection.

**Comment by DimonBor** [comment]
According to [this](https://www.technovelty.org/linux/a-little-tour-of-linux-gateso.html) article it's some shared library for more efficient system calls or something. And no, I don't have any firewalls or antivirus. This issue has been ongoing since my system was installed (before I used Sway for a while). So maybe I'll report this issue to the Qt project. Thank you for your help. You can close it at your discretion.

**Comment by ilya-fedin** [comment]
> According to [this](https://www.technovelty.org/linux/a-little-tour-of-linux-gateso.html) article it's some shared library for more efficient system calls or something.

Ah, I wanted to advice to check `/etc/ld.so.preload` to check whether there's any third-party injection. But if it's really apart of glibc then ok.

> So maybe I'll report this issue to the Qt project.

Well, you can run tdesktop with `WAYLAND_DEBUG=1` and save the output to some log file using `> log.txt 2>&1`. I suspect that happens due to a compositor (i.e. GNOME) bug. The thing is Qt sets `mFocus` variable in `begin` event handler and clears in `end` event handler, accessing the variable in all of `begin`, `update` and `end` events. If it happens that GNOME sends `update` of `end` event before the `begin` one, `mFocus` is unset and the crash will happen: https://github.com/qt/qtwayland/blob/1a548d29e169c91d9f698162dba0cc0fe51d0377/src/client/qwaylandpointergestures.cpp#L111-L182. Qt can do a better thing obviously by checking for `mFocus` and exiting early with maybe some warning about compositor bug. I believe it's worth to check for that.

**Comment by ilya-fedin** [comment]
> Well, you can run tdesktop with `WAYLAND_DEBUG=1` and save the output to some log file using `> log.txt 2>&1`.

(I'm waiting for this)

**Comment by DimonBor** [comment]
> > Well, you can run tdesktop with `WAYLAND_DEBUG=1` and save the output to some log file using `> log.txt 2>&1`.
> 
> (I'm waiting for this)

I'm actually posted it before :upside_down_face:

**Comment by DimonBor** [comment]
Anyway here is another one. Reproduced in 4.8
[log.txt](https://github.com/telegramdesktop/tdesktop/files/11313008/log.txt)

**Comment by ilya-fedin** [comment]
> I'm actually posted it before upside_down_face

Oh, indeed, I forgot. Yes, I looked at it and here's the last message:
```
[3869127.228] zwp_pointer_gesture_swipe_v1@22.update(37684924, 27.53906250, 7.62500000)
```
There were multiple begin-update-end sequences in the log before this line, but they ended no new sequence has began, so it's a GNOME bug (and apparently a Qt one as it probably can just ignore it).

**Comment by ilya-fedin** [comment]
The new one shows the same

**Comment by ilya-fedin** [comment]
https://bugreports.qt.io/browse/QTBUG-113145

**Comment by DimonBor** [comment]
@ilya-fedin 
 Hi, I found one funny thing. It looks like this is caused by the [Blur my shell](https://github.com/aunetx/blur-my-shell) extension. I can confidently reproduce this segfault when this extension is enabled. And everything absolutely OK when it is off. So I suppose this could be submitted to Blur my shell repo.  Although they have enough reports about random GNOME crashes. Therefore, the best solution will be just not to use it for now.
 
 Thanks for your assistance, I think you may close this.
