### ISSUE TITLE
Images are huge

### ISSUE THREAD

**Issue by NeoLegends** [telegramdesktop/tdesktop#260]
Since the newest update (I think I've got the problem since 0.68), previews that previously had a reasonable size, now have a huge size. They take far too much space inside the chat window.

![unbenannt-1](https://cloud.githubusercontent.com/assets/1683034/5057491/d3a2a78a-6cc3-11e4-9011-3c2fbd630961.png)

**Comment by Aokromes** [comment]
I think it's intended to allow you to see the image without having to click on it to enlarge it, but maybe a setting to allow small (25% telegram width)/medium (50% telegram width)/large (75% telegram widht)/extra large (100% telegram width) previews can be a good idea.
