### ISSUE TITLE
[Feature Request] Add possibility of an annoying person hiding in a group chat

### ISSUE THREAD

**Issue by fedorusov** [telegramdesktop/tdesktop#26002]
### Is your feature request related to a problem?

There are plenty of people in group chats which are excessively annoying and create unnecessary spam. This of course is subjective, so these people are not banned. But for me they are just constantly seeking attention by dumb comments.

### Describe the solution you'd like

I would like to click on the user and press a button just like "Block" to hide all of his messages. Which therefore would be marked "Hidden message" similarly like "Deleted message" like it works right now.

### Describe alternatives you've considered

Tried "Block user" and disabled "Notifications", but it doesn't help.

### Additional context

This would preserve my time and nerves.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
