### ISSUE TITLE
[Feature Request] Change program which opens URLs

### ISSUE THREAD

**Issue by Andrew15-5** [telegramdesktop/tdesktop#26001]
### Is your feature request related to a problem?

I want to open URLs in Firefox Private window by default, but instead Telegram opens them in normal window.

### Describe the solution you'd like

There should be a setting menu where all the programs (.desktop files) are shown for user to choose in which program they want to open URLs. But also in the same settings, I would like to see a button for a custom shell command (like the input box when adding custom OS shortcuts).

![image](https://user-images.githubusercontent.com/37143421/222971393-e9ee9684-b306-4ae8-b8d8-82898fa450f4.png)

Or as a bare minimum, add support for a `BROWSER` environment variable that stores the desired command, to which Telegram must pass 1 parameter which is of course the URL. This is probably ways simpler, but still has the same effect (but less GUI-user-friendly). This way I can just do either `BROWSER='firefox --private-window'` (if executed by shell) or `BROWSER=firefox-private` (a custom wrapper in `PATH`).

### Describe alternatives you've considered

There are no alternatives that I can think of. Changing the default web browser from OS default application menu is kind of an option, but it's a global setting and I need a local setting (to 1 app).

### Additional context

I use Pop!_OS 22.04 (with GNOME 42.5)

**Comment by ilya-fedin** [comment]
I'm pretty sure you should supply this request to your system components (glib) to support richer MIME handling rather than inventing custom MIME handling in tdesktop

**Comment by Andrew15-5** [comment]
I didn't say anything about MIME handling. I just want to change what program specifically Telegram uses to open URLs. This can't be done by anyone except Telegram.

**Comment by ilya-fedin** [comment]
That's a part of system MIME handling, yes

**Comment by Andrew15-5** [comment]
So how else I can do this if "inventing custom MIME handling in tdesktop" is no go? Please share.

**Comment by ilya-fedin** [comment]
> This can't be done by anyone except Telegram.

I'm pretty should it could be done by the system, as system frameworks know the request is going from Telegram.

**Comment by Andrew15-5** [comment]
> system frameworks know the request is going from Telegram.

Woah, this is some kind of dbus (or something) stuff that I really don't want to go into. Particularly if it involves something bigger than shell scripting. I'm not familiar with any "system frameworks" and how I can process Telegram requests to the system.

Exposing just a `BROWSER` variable would be much easier for everyone IMO.

**Comment by Andrew15-5** [comment]
From the very beginning, I thought that Telegram is in no way flexible when it comes to opening URLs. You may or may not have a confirmation menu to open a URL and that's all (I don't have one, but some other users do). This is one of Telegram weaknesses IMO. Maybe someone wants to open theirs URLs in non-private mode, maybe they want to open them in private mode, or maybe even in a separate non-default app (other GUI/TUI browser). Sometimes it can be useful to just copy the URL in the clipboard (as an additional button or as a program wrapper for clipboard utility). (Although one can copy URL by using a context menu.)

**Comment by ilya-fedin** [comment]
I say you should supply this request to the respective system component. There's quite a few places that fit this request:
1. glib. This is the basic system library impementing the mimeapps spec. tdesktop uses this library, so a change to it will change tdesktop's behavior for MIME handling. The library also knows that it's operating inside of Telegram, it's possible to retrieve the appid with `g_application_get_application_id(g_application_get_default())` and they can use that internally for this functionality.
2. xdg-specs. In case they wouldn't like to do something not by the spec, you have to request a spec change.
3. xdg-desktop-portal. It has OpenURI portal and glib uses it conditionally. It also has code to get the requester's appid from systemd (cgroups) and flatpak. Implementing this functionality inside the portal + making glib to use the portal unconditionally would work as well.

**Comment by ilya-fedin** [comment]
> Maybe someone wants to open theirs URLs in non-private mode, maybe they want to open them in private mode, or maybe even in a separate non-default app (other GUI/TUI browser).

That really sounds like a candidate for a system feature. Imagine every application implementing custom MIME handling because someone wants to use custom browser or custom PDF viewer from that application. Not to say sandboxed applications don't have the access to the list of installed apps and that won't work in flatpak/snap.

**Comment by Andrew15-5** [comment]
> There's quite a few places that fit this request

Oh man, this is a lot of work I didn't anticipate.

**Comment by ilya-fedin** [comment]
> Oh man, this is a lot of work I didn't anticipate.

You want to say supplying requests to the projects is more work than to tdesktop?

**Comment by Andrew15-5** [comment]
> Imagine every application implementing custom MIME handling

Well, not every application is intended to use external apps (like a PDF viewer or a game). But I do see the problem and overhead in this feature on an application level. And I also do want to have a convenient setting, which I described in the first comment.

**Comment by ilya-fedin** [comment]
Then supply this request to gnome-settings or whatever your system settings application is called?

**Comment by Andrew15-5** [comment]
> You want to say supplying requests to these projects is more work than to tdesktop?

No, I was referring to the potential coding part that I may have to do to make everything work as I wanted. I didn't even know that these "projects" support user suggested features. I thought of them as a separate thing of which I know nothing and can't change anything about it (except downloading source and changing it by myself). I know about GLib, but the other two... I only recognize them by the commands in my shell.

**Comment by ilya-fedin** [comment]
That doesn't really differ from tdesktop. No one will invest time in this likely, so you have to code that yourself.

**Comment by Andrew15-5** [comment]
Okay, I will have to do some research and expand my knowledge about aforementioned projects to at least understand all the basic concepts about handing things such as URLs (on a system-app level or whatever). And if I succeed in this, I can think about sending the request to other projects.

**Comment by Andrew15-5** [comment]
> so you have to code that yourself

Bummer. Anyway, thanks for providing some information with which I can further work on.

**Comment by ilya-fedin** [comment]
Well, maybe GNOME has some resources where you can talk to developers and know where to submit the request better.
