### ISSUE TITLE
Support of MacOS Emoji Picker

### ISSUE THREAD

**Issue by vchkhr** [telegramdesktop/tdesktop#26019]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

MacOS has a built-in emoji picker. To use it, press "Globe + E" or "Control + Command + Spacebar". External keyboards, such as Logitech Key Pop, also support this feature, but it doesn't work in Telegram. 
Screenshot of emoji picker:
![image](https://user-images.githubusercontent.com/33002390/224326928-51b55246-ed6c-4040-8d04-39e5f6b8a219.png)

### Describe alternatives you've considered

Open Telegram's own emoji picker with a mouse. There is no keyboard shortcut

**Comment by vchkhr** [comment]
> What version are you using? What is the `Globe` key?

Version 9.4.2.243859 AppStore.
The Globe key is also fn:
![image](https://user-images.githubusercontent.com/33002390/224359798-a8ab8198-f9df-4d8f-ab25-68629bb42773.png)

**Comment by 23rd** [comment]
> Version 9.4.2.243859 AppStore.

Sorry, but according to the version you specify, you are using the [Telegram for macOS](https://macos.telegram.org/), not the [Telegram Desktop](https://desktop.telegram.org/).
You can report your issue to [the group](https://t.me/macswift) or to [the repository of Telegram for macOS](https://github.com/overtake/TelegramSwift).

> The Globe key is also fn:

But this is an interesting find, I think support for this shortcut will be added to the Telegram Desktop too.
