### ISSUE TITLE
Compose key stopped working from version 4.6.10

### ISSUE THREAD

**Issue by einansgar** [telegramdesktop/tdesktop#26022]
### Steps to reproduce

1. activate any text field in Telegram
2. e. g. type `[compose key]`, `a`, `e`

### Expected behaviour

characters should combine to `æ` (this worked until this version)

### Actual behaviour

characters show up separated as `ae`

### Operating system

Linux (Arch, rolling release), swaywm

### Version of Telegram Desktop

4.6.10

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
are you sure that from 4.6.10, not earlier, e.g. 4.6.6?

**Comment by ilya-fedin** [comment]
As I'm highly doubt any of those changes can affect compose key
https://github.com/telegramdesktop/tdesktop/compare/v4.6.9...v4.6.10

**Comment by einansgar** [comment]
wrong question 🤦  Something else in my system changed and seems like the closing-opening of the updating process made these changes just visible, nothing wrong with the 4.6.10 indeed. But anyway thanks for the response
