### ISSUE TITLE
Transaltion bar: "hide" option doesn't work in normal groups

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#26027]
### Steps to reproduce

1. open a **legacy** group chat where the detected language is not whitelisted from the language settings (tdesktop will ask to translate the chat)
2. hide the translation bar using the "hide" option
3. exit the chat
4. re-open it

### Expected behaviour

The translation bar should not be back

### Actual behaviour

The translation bar always comes back

### Operating system

Windows 10

### Version of Telegram Desktop

4.6.10

### Installation source

Static binary from official website

**Comment by RememberTheAir** [comment]
Apparently it was fixed in 4.6.11

**Comment by RememberTheAir** [comment]
Actually still an issue on 4.7.1 :(

**Comment by nealhead** [comment]
Still occurring on 4.8.3

**Comment by john-preston** [comment]
I've reported to server side developer, looks like a server side bug.

**Comment by john-preston** [comment]
Should be fixed on the server side now.
