### ISSUE TITLE
[Feature Request] Edit scheduled text/attachments in channel messages

### ISSUE THREAD

**Issue by Forever-A-Hermit** [telegramdesktop/tdesktop#26024]
### Is your feature request related to a problem?
Yes

When I right click on a scheduled message, all I see in the dropdown menu is:

Show in Folder
Save As...
Copy Text
Send Now
Delete
Select

On Android, the menu (initiated by pressing the vertical dots) looks like this:

Send Now
Copy
Edit
Reschedule
Delete

### Describe the solution you'd like

I'd like to be able to perform the same edit operations on the Desktop version like I'm able to do on Android.

### Describe alternatives you've considered

Other than using the Android version for edits, there aren't really any I'm aware of.

### Additional context

Using Telegram Desktop Version 4.6.5 x64 on Windows 11

**Comment by serpico** [comment]
I'm using 4.10.1 it seems solved
