### ISSUE TITLE
Mouse scrolling fails after reconnect monitor and mouse with switcher

### ISSUE THREAD

**Issue by hpsaturn** [telegramdesktop/tdesktop#26026]
### Steps to reproduce

1. Install last Telegram Desktop app on Debian - Linux
2. Using the mouse scroll in chat, it works
3. Change to other PC changing the monitor and mouse using switcher hardware
4. Return to Telegram PC using the switcher hardware
5. The scroll mouse fails. (The app is ok, and other apps works well with the scroll mouse)

### Expected behaviour

That the mouse scroll resume ok after connect and disconnect the USB connectors or using switcher hardware.

### Actual behaviour

The mouse scroll fails every time when you return or reconnected the mouse usb.

### Operating system

Debian GNU/Linux 11 (bullseye)

### Version of Telegram Desktop

4.6.5

### Installation source

Static binary from official website

### Logs

```shell
https://termbin.com/egv5
```

**Comment by ilya-fedin** [comment]
#17254
