### ISSUE TITLE
App crash on click on select proxy setting button

### ISSUE THREAD

**Issue by mosamadi** [telegramdesktop/tdesktop#26025]
### Steps to reproduce

1. enable http proxy
2. click on the left side button to select a proxy

### Expected behaviour

show the proxy selection menu

### Actual behaviour

App crashed and restarted!

### Operating system

Windows 10

### Version of Telegram Desktop

4.6.10 beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@mosamadi Thank you for you report. This will be fixed in the next version.
