### ISSUE TITLE
Buttons not enabled in videochat app

### ISSUE THREAD

**Issue by topchyan** [telegramdesktop/tdesktop#26023]
### Steps to reproduce

1. Join any video chat or call someone
2. Try pressing any button, e.g. unmute or start camera

### Expected behaviour

Buttons should be functional

### Actual behaviour

Clicking on buttons does not work

### Operating system

Debian GNU/Linux 11 (bullseye) with Cinnamon

### Version of Telegram Desktop

4.6.10

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Please provide a screen record of the issue

**Comment by topchyan** [comment]
![image](https://user-images.githubusercontent.com/16518288/224586272-519f018b-e726-4c38-9660-48d7a1c6e4ec.png)

Please note: I'm showing this call to "Deleted Account", however, trust me, it's the same on live accounts.
Under Cinnamon (regular) Desktop Environment, clicking on any part of this dialog box has absolutely no effect: nothing responds to clicks and even closing this menu is impossible. Now, Cinnamon "Software Rendering" (whatever that means) seems to have an effect on buttons pressed, however calls still do not go through (sound config issues maybe). 

I have installed tried to use another desktop environment (XFCE) and the dialog does seem to trigger events. So the issue might be isolated to Cinnamon, but I'm not sure. Hope it helps

**Comment by ilya-fedin** [comment]
I asked for a screen record, not a screenshot, it's not possible to show the issue using a screenshot.

**Comment by Aokromes** [comment]
i don't think you can call delete account.

**Comment by Aokromes** [comment]
confirmed, that's only with deleted account, with standard account works fine.

**Comment by topchyan** [comment]
At least you should try to reproduce the error. Sorry I could not provide a recording or call a live person -- don't want to expose handles etc. It's your choice what you want to do with my report, here I'm just reporting this bug. Have a great day.

**Comment by Aokromes** [comment]
> At least you should try to reproduce the error. Sorry I could not provide a recording or call a live person -- don't want to expose handles etc. It's your choice what you want to do with my report, here I'm just reporting this bug. Have a great day.

i tested with multiple targets and they work for me.
even being 2:30am here

**Comment by ilya-fedin** [comment]
Calls are using OpenGL and Debian is a stale distro, so it may have old buggy OpenGL drivers causing a deadlock in this exact environment on this exact hardware. It's not really a good idea to use such a distro on a desktop.

**Comment by topchyan** [comment]
@Aokromes, thank you for testing outside of normal business hours. Much appreciated your hard work and dedication!
@ilya-fedin пожалуй да, воспользуюсь советом. Debian 11 мне в общем-то понравился, однако и он не совершенен. Стоит ли ковыряться в LMDE?

**Comment by Aokromes** [comment]
> @Aokromes, thank you for testing outside of normal business hours. Much appreciated your hard work and dedication! @ilya-fedin пожалуй да, воспользуюсь советом. Debian 11 мне в общем-то понравился, однако и он не совершенен. Стоит ли ковыряться в LMDE?

in fact, i even installed debian 11 Cinnamon on vm and it works for me.

**Comment by ilya-fedin** [comment]
Everything using Debian as the base will be as bad as Debian at actual software. Actually, nothing from the deb family is good for desktop in my opinion.

**Comment by topchyan** [comment]
@ilya-fedin fair enough. Any solid distro recommendations?

**Comment by ilya-fedin** [comment]
Arch, endeavourOS, Fedora, OpenSUSE Tumbleweed

**Comment by topchyan** [comment]
I'll go for EndeavourOS from this list: haven't tried that one yet. Thanks again!
