### ISSUE TITLE
Disable animations is not disabling animated avatars and emoji avatar status

### ISSUE THREAD

**Issue by ECCOsea** [telegramdesktop/tdesktop#26038]
### Steps to reproduce

1. Open telegram go Settings  > Advanced > Enable animations set - Disable

### Expected behaviour

Disable all animations. Make all avatars and emoji status and etc totally statics. No any animation.

### Actual behaviour

Animated avatars still continiously play in loop in chat list, and emoji avatar play single time.

### Operating system

Windows 7 x64

### Version of Telegram Desktop

4.6.5 desktop

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This option is only about UI animations, not content animations

**Comment by ECCOsea** [comment]
> This option is only about UI animations, not content animations

Thank you for response! Should i create feature request? I know lot of people who very distracted of animated avatars (me too). There is lot of chats on second monitor and it looks like a happy new year tree. I hope telegram add disable all animations option. Its will be very usefull.

**Comment by ilya-fedin** [comment]
I believe it's already created, please use GitHub search

**Comment by BoffinBrain** [comment]
> I believe it's already created, please use GitHub search

I came here to report the same issue. Can you point me to the bug/tracker that is intended to fix this? I saw #24658 but that might be overly broad.

**Comment by ilya-fedin** [comment]
#24658 seems like the right issue, yeah. I'm not sure why you say it's overly broad as its content and discussion completely about animated avatars.

**Comment by BoffinBrain** [comment]
I simply said that because 'Reduced Motion' could potentially apply to many aspects of the UI, including animated emoji in names/status messages, which still loop twice when all animation settings are turned off. That's not mentioned in the referenced issue but I assume it's being looked at too.

**Comment by ilya-fedin** [comment]
You can ask the reporter to rename the issue if you think he can get a better title for the provided issue description
