### ISSUE TITLE
Telegram desktop crashes when I click on proxies

### ISSUE THREAD

**Issue by TONTHENOOB** [telegramdesktop/tdesktop#26035]
### Steps to reproduce

open telegram
click on the proxy circle or open proxies from settings

### Expected behaviour

open proxies

### Actual behaviour

crashes on click

### Operating system

Window 10

### Version of Telegram Desktop

4.6.10 beta

### Installation source

Static binary from official website

**Comment by Msrvie** [comment]
me too

**Comment by Aokromes** [comment]
duplicate will be fixed on next version.
