### ISSUE TITLE
Crash telegram desktop when wants to open proxy settings

### ISSUE THREAD

**Issue by ssmns** [telegramdesktop/tdesktop#26036]
### Steps to reproduce

open telegram, when click on proxy button 
or 
click on  settings>advanced> connection type 

### Expected behaviour

open proxy menu to set or change proxies

### Actual behaviour

crash telegram and restarted

### Operating system

ubuntu 22.04

### Version of Telegram Desktop

4.6.10 beta

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
triplicate
