### ISSUE TITLE
ANGLE works in a strange way

### ISSUE THREAD

**Issue by mrquantumoff** [telegramdesktop/tdesktop#26030]
### Steps to reproduce

Select any ANGLE graphics backend option on Windows 10/11 on an AMD GPU
Open a video/photo attachment

### Expected behaviour

Video plays smoothly
Photo is displayed

### Actual behaviour

With some backends I get nothing, meanwhile, with others my screen goes blank and then comes back or it goes blank until I restart my drivers via Win+Ctrl+Shift+B.

### Operating system

Windows 11/10

### Version of Telegram Desktop

4.6.5 beta, but I have been facing this issue for months

### Installation source

Microsoft Store

**Comment by ilya-fedin** [comment]
Why do you switch it if it works by default? The option is for people who have problems using the default as a drivers may have problems using the default backend.

**Comment by mrquantumoff** [comment]
Default one doesn't work as expected either

**Comment by ilya-fedin** [comment]
sounds like a dup of #25999

**Comment by mrquantumoff** [comment]
I'm not sure about that. People there seem to have a similar issue on all OSes. Meanwhile, I didn't have anything similar on Linux, and the actual behaviour is different as well.

**Comment by ilya-fedin** [comment]
do you still have this bug on latest version?

**Comment by mrquantumoff** [comment]
I don't think so
