### ISSUE TITLE
Notification badge for archived chats on Windows

### ISSUE THREAD

**Issue by yuri-galin** [telegramdesktop/tdesktop#26037]
### Steps to reproduce

Archive a chat with unread messages

### Expected behaviour

The message count on the app badge doesn't include the messages in archived chats.

### Actual behaviour

Unlike the Android app which doesn't include messages from archived chats on the badge, Windows app includes them, making the user think that they have relevant unread chats.

![archive_notifications_1](https://user-images.githubusercontent.com/117083475/225240360-3eb766de-f839-44e2-9209-02ac79100077.jpg)
![archive_notifications_2](https://user-images.githubusercontent.com/117083475/225240370-97d0b0d3-5eb3-4dd8-86d0-56c562b5c48a.jpg)

### Operating system

Windows 10

### Version of Telegram Desktop

4.6.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#6314
