### ISSUE TITLE
[Feature Request] Consider leaving closed issues unlocked

### ISSUE THREAD

**Issue by possibilities** [telegramdesktop/tdesktop#26046]
Because you lock issues from further discussion you prevent non-contributors from sharing info and discussing issues. For example because these are locked I had to dig around in the git history to find that the env variable was changed. If the discussion was unlocked I could add this detail and prevent others from doing this research over again.

* https://github.com/telegramdesktop/tdesktop/issues/306
* https://github.com/telegramdesktop/tdesktop/pull/7340

**Comment by ilya-fedin** [comment]
The thing is closed issues are not read by anyone, but people assume it's another way and create comments instead of filing new issues. If you have any questions, you can always ask questions in https://t.me/TelegramDesktopTalk (it's even linked on the page opened by clicking the New issue button).
