### ISSUE TITLE
telegram memory Hug

### ISSUE THREAD

**Issue by rashedheydari2001** [telegramdesktop/tdesktop#26049]
### Steps to reproduce

playing a video
loop stickers

### Expected behaviour

cool application with posix method please down the memory hugs 

### Actual behaviour

memory hug and speed up my laptop fan

### Operating system

archlinux

### Version of Telegram Desktop

4.6.5

### Installation source

Other (unofficial) source

**Comment by rashedheydari2001** [comment]
[URL=https://uupload.ir/view/screenshot_from_2023-03-17_14-21-16_fulj.png][IMG]https://s2.uupload.ir/files/screenshot_from_2023-03-17_14-21-16_fulj_thumb.png[/IMG][/URL]

**Comment by ilya-fedin** [comment]
It's expected as tdesktop has to store multiple RAW frames in RAM and use your CPU for decoding in order to play the video
