### ISSUE TITLE
Ability to override the widget style

### ISSUE THREAD

**Issue by Anixx** [telegramdesktop/tdesktop#26041]
### Is your feature request related to a problem?

Hello!

Is there a way to override the Qt widgets style on Windows to "Windows" style (so it to look like a native app)?

### Describe the solution you'd like

Ability to override the widget style

### Describe alternatives you've considered

Tried to use QT_QUICK_CONTROLS_STYLE environment variable.

**Comment by ilya-fedin** [comment]
tdesktop doesn't use Qt's built-in widgets, it has custom widgets drawn manually with QPainter based on designer's mockups, so Qt themes are not applicable. You can create a tdesktop theme in Chat Settings -> kebab menu -> Create new theme.
