### ISSUE TITLE
[Feature Request] Slight improvement of mouseless usability (scrolling chats with arrow keys)

### ISSUE THREAD

**Issue by pbaykalov** [telegramdesktop/tdesktop#26048]
### Is your feature request related to a problem?

There's no way to scroll a chat by small amount (like I would do with arrow keys in 99% of lists in all programs) and not toggle editor of my last message.

### Describe the solution you'd like

One of:
a) Adding a custom command for scrolling up/down so that I can bind it to some key combination like Alt+Shift+Up/Down which is currently not used. 
b) Adding a custom command for editing last message in chat and giving a choise of unbinding it from Up key.
c) Rebinding "Edit last message" to "Alt+Up".

### Describe alternatives you've considered

Using Page Down and Page Up does not allow fine scrolling.

### Additional context

Maybe rebinding "Edit last message" to "Alt+Up" would be better because I personally need scrolling more often than editing last message. Alt-Up/Down is currently used for same thing as Ctrl+[Shift]Tab and Ctrl+Page Up/Down and even pressing Esc and selecting different chat is a good option because it does not ruin "Unread" status, so if Alt+Up is repurposed for editing last message there are still three alternative binds left. And then the Up/Down would scroll group chats without toggling the editor.  

But adding a new command ((a) or (b) is good too because it does not change established user experience.

**Comment by VladimirMrzv** [comment]
Maybe add buttons + and - for zoom pictures in preview

**Comment by Aokromes** [comment]
> Maybe add buttons + and - for zoom pictures in preview

control + + / control + -

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/16300

**Comment by pbaykalov** [comment]
Vim in Telegram? Phew.
