### ISSUE TITLE
Escaping media caption textbox with the Tab key

### ISSUE THREAD

**Issue by kolayne** [telegramdesktop/tdesktop#26058]
### Steps to reproduce

1. Try sending any attachment to any chat.
2. After the caption textbox is focused, click Tab.

### Expected behaviour

The focus remains in the media attachment dialog. Either the Tab key has no effect, or does something inside that subwindow, say, opens the emoji list.

### Actual behaviour

The focus leaves the caption area and goes to the global search textbox. Shift+Tab won't have any effect, clicking Tab again moves focus to the usual message text area under the media attachment overlay, after that Tab has no effect. The text typed in that message text area is discarded when the attachment dialog is closed.

### Operating system

Arch Linux, i3 version 4.22 (2023-01-02)

### Version of Telegram Desktop

4.6.3, 4.7.0

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
#5405
