### ISSUE TITLE
Upload sound option removed in version 9.4.2 (244138)

### ISSUE THREAD

**Issue by katiejchapman** [telegramdesktop/tdesktop#26057]
### Is your feature request related to a problem?

I am not sure if this feature was removed intentionally, or if it is a bug.

### Describe the solution you'd like

The option to upload a notification sound be back, or at least add the mobile app sound to telegram desktop.

### Describe alternatives you've considered

downloading a previous beta version

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
