### ISSUE TITLE
Messages are read automatically on Windows PC even on a closed to tray and locked machine.

### ISSUE THREAD

**Issue by Pugnator** [telegramdesktop/tdesktop#26050]
### Steps to reproduce

Almost the same as #4664

1. Open a conversation with any user.
2. Close the application to tray.
3. Lock the system via Win + L or wait for automatic lock up
4. Wait for the same user to send you a message.

### Expected behaviour

A message stays in unread state until a conversation with the user is in focus.

### Actual behaviour

The message become read as soon as it was sent. I see no notifications from that user on my Android devices.
I can open a chat list on any of my Android devices and see that all messages from this user is marked as read as soon as they were sent.
It looks like it affects the last user you have opened conversation with.
If I exit the desktop version issue goes away.
Some users report that for them messages stay unread but I can't confirm it personally.
It appeared several months ago, not just now.

I can confirm that issue occurs when system is locked at least in most noticeable cases.

### Operating system

Microsoft Windows [Version 10.0.19045.2604]

### Version of Telegram Desktop

4.6.5 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@Pugnator Strange to hear. When you close the app to tray the current chat is closed so it shouldn't mark anything as read.

Do you close the window by X click? It closes the chat for me and doesn't mark anything as read any more.

**Comment by Pugnator** [comment]
> @Pugnator Strange to hear. When you close the app to tray the current chat is closed so it shouldn't mark anything as read.
> 
> Do you close the window by X click? It closes the chat for me and doesn't mark anything as read any more.

yes I do. I understand that issues seems to be probably environment specific. Or Windows power settings somehow make it happen. I saw you commit, hope it will help, will report as soon it will be released.
