### ISSUE TITLE
[Feature Request] Give access to specific users to edit your message

### ISSUE THREAD

**Issue by sadrahkm** [telegramdesktop/tdesktop#26055]
### Is your feature request related to a problem?

The problem is that when you send a message, sometimes you need to give access to multiple users to be able to edit your message simultaneously.  For instance, you have made a list of new features that are needed to be added to Telegram. But you want to give others access to allow them to edit this list and make contributions to your ideas.

### Describe the solution you'd like

It would be great if there is a feature that can allow the owner of the message to indicate who can edit his/her message. This feature could also be super helpful in private messages.

### Describe alternatives you've considered

There is no alternatives for now.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
