### ISSUE TITLE
Telegram stops and exits in Linux when interlocutor on a call turns on video or screen streaming

### ISSUE THREAD

**Issue by GazimSoliev** [telegramdesktop/tdesktop#26061]
### Steps to reproduce

1. Call to user in Linux
2. Ask to user turn on video or screen streaming

### Expected behaviour

Continues to work and show video or screen streaming

### Actual behaviour

Freezes and exits

### Operating system

6.1.19-1-MANJARO, Gnome 43.3, Windowing system X11

### Version of Telegram Desktop

4.6.2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Switch to the official binary from https://desktop.telegram.org, it doesn't have such problem
