### ISSUE TITLE
MediaView does not show on Windows 7

### ISSUE THREAD

**Issue by zavsc** [telegramdesktop/tdesktop#26065]
### Steps to reproduce

Click on an image in chat
MediaView does not show

### Expected behaviour

MediaView does show

### Actual behaviour

I can see Media Viewer in Alt-Tab menu, but switching to it does nothing, and its preview is blank.
This behavior has only been seen on Windows 7, other systems don't. But since the laptop is old, I don’t want to put Windows 10 there
If this is important, then telegrams have just been installed and at the time of writing the problem is relevant

### Operating system

Windows 7 x64

### Version of Telegram Desktop

4.7 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I hope it'll be fixed in the upcoming version. What screen scale do you have in the system?

**Comment by john-preston** [comment]
@zavsc Please post log.txt of such launch, where the viewer doesn't show up.

Also please contact me at t.me/preston so I could provide you a test build that should fix the issue for testing.
