### ISSUE TITLE
Power saving mode such as in "Telegram from AppStore"

### ISSUE THREAD

**Issue by d1m0s23** [telegramdesktop/tdesktop#26074]
### Is your feature request related to a problem?

No, im using Telegram Desktop client on macOS, and i don't want to use client which presented in App Store. In macOS, power mode cannot be activated when X% battery level passed, only always when laptop is not connected to the charge or when its connected and etc. So, power mode that is presented now desktop client is not what i needed.

### Describe the solution you'd like

I want similar settings of power saving mode as in client from the AppStore, when i can set battery lvl when power save mod needs to be turned on. Is it possible to do this?

### Describe alternatives you've considered

- 

### Additional context

-

**Comment by Aokromes** [comment]
telegram desktop added few power saving lately, they fit your needs?
