### ISSUE TITLE
Deleted message is still visible in contacts pane

### ISSUE THREAD

**Issue by arkadiybag** [telegramdesktop/tdesktop#2607]
![image](https://cloud.githubusercontent.com/assets/16622328/20056897/8e51e6ee-a4f9-11e6-8b5b-d1a718a01908.png)

if I delete a message from a chat - I still see it on the left, if my message last

**Comment by auchri** [comment]
Please use the template next time.

**Comment by Aokromes** [comment]
#1138 ?

**Comment by stek29** [comment]
@Aokromes no, in this issue user deletes last message which was sent by him, but it's preview is in chat list.
