### ISSUE TITLE
Crash in pinned messages list when click on "Go To Message" option

### ISSUE THREAD

**Issue by vkuprin** [telegramdesktop/tdesktop#26079]
### Steps to reproduce

1. Pin the message in saved messages
2. Open pinned messages list
4. Click on one of the messages which is the old one from previous week with the right click
5. Choose option "Go To Message"

### Expected behaviour

There should be no crash

### Actual behaviour

Application closes and crashes completely

### Operating system

mac os - Ventura 13.2.1

### Version of Telegram Desktop

4.7

### Installation source

Mac App Store

### Crash ID
627f7e4f-99c8-4383-9304-f92029d30de9

_No response_

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org enable beta and send crash id on next startup.

**Comment by vkuprin** [comment]
@Aokromes 
Crash ID: 627f7e4f-99c8-4383-9304-f92029d30de9

ApiId: 2040
Binary: Telegram.app
Launched: 23.03.2023 07:34:03
OpenGL: Enabled
OpenGL Renderer: [not-initialized]
Platform: MacOS
UserTag: 7d9e99a80d0f506c
Version: 4007000
OS-Version: 2299.4000
Caught signal 11 (SIGSEGV) in thread 8477131072
