### ISSUE TITLE
Too many steps for a simple call

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#26077]
### Steps to reproduce

So basically it is this new middle page that shows before actually doing a call. When I click to call someone, now this shows to asks if I want a video call or a voice call.

![image](https://user-images.githubusercontent.com/29236/226720288-42bc64ed-c549-4660-acc2-e7268c0681e4.png)

How to remove asking me this because if I click the call icon, I want to start a call right away, not see something ask me to verify if I want to make the call. If I wanted a video call, I can simply click the video icon when I do the call afterwards.

### Expected behaviour

To call right away instead of asking

### Actual behaviour

It asks for a 2nd time if I want to do the call.

### Operating system

Linux

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
not a bug, it was requested because to much people used to click on call by error.

**Comment by zaps166** [comment]
Are there any settings to avoid it?

**Comment by saleyn** [comment]
Please introduce a setting that would be able to trigger the old default behavior of starting a call with a single click.

**Comment by luisalvarado** [comment]
> not a bug, it was requested because to much people used to click on call by error.

There should always be an "option" to set it. This is one of those a bug that is shown as a feature. As you said:

"too much people used to click on call by error"

But not all. Meaning, it would require a setting. Sure, the default is to ask as shown in the picture, but a setting for the users like myself that do not care about making a mistake since most of the time when we click to call, we actually want to click to call, if that makes sense.

**Comment by Aokromes** [comment]
> Why was it closed, it is actually a bug. It can be sold as a "feature" but it is not.

a bug is when the change is not intended, the change was requested, so it's a feature.

**Comment by ilya-fedin** [comment]
@luisalvarado tdesktop prefers to have as less settings as possible, so frequently it has to take the tradeoff of making the app not-so-convenient for the some fraction of people

**Comment by luisalvarado** [comment]
> > Why was it closed, it is actually a bug. It can be sold as a "feature" but it is not.
> 
> a bug is when the change is not intended, the change was requested, so it's a feature.

Look I know, at the end of the day you or your team has the  final saying, but the feature was implemented in a way that you ended up penalizing other users like myself. A simple option to disable it would have been gracefully accepted by the ones that this feature now affects in a bad way.

A simple if statement, checks if they enable or disable that option and it would automatically do the call, instead of a pop-up waiting for an additional confirmation.

That is all. As it currently stands, it confuses me so much when I click to calll and I have to click again to call. Hope that clarifies the issue.

**Comment by luisalvarado** [comment]
So guys, no future setting or option to set it so it does not ask twice for a call?
