### ISSUE TITLE
Linux: native notification shows empty button

### ISSUE THREAD

**Issue by acidnik** [telegramdesktop/tdesktop#26082]
### Steps to reproduce

Enable native notifications
Wait for message in chat

### Expected behaviour

All buttons should have a text or icon on them

### Actual behaviour

First button doesn't have an icon nor text:
![tg-notify](https://user-images.githubusercontent.com/1227955/227015275-389511ef-d7ff-4321-9a25-954311c2a8d0.png)

### Operating system

Linux, xfce

### Version of Telegram Desktop

Version 4.6.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
The latest version is 4.7.1
