### ISSUE TITLE
Stuck on Image Preview hitting [alt]+[tab]

### ISSUE THREAD

**Issue by danbruegge** [telegramdesktop/tdesktop#2608]
### Steps to reproduce
1. Open Telegram
2. View Chat with an Image
3. Open Image
4. Hit [alt]+[tab]

### Expected behaviour
Image Preview should close, after switching to another Programm/App.

### Actual behaviour
Can't close or exit ImagePreview. Only way out is to switch to another tty and kill the telegram process.

### Configuration
**Operating system:** Archlinux, Xfce 4.12
https://aur.archlinux.org/packages/telegram-desktop-bin/

**Version of Telegram Desktop:** 0.10.11

**Comment by auchri** [comment]
#2497

**Comment by danbruegge** [comment]
Didn't found this one. Thanks.
