### ISSUE TITLE
Setting "Setting" -> "Call setting" does not work for headphones

### ISSUE THREAD

**Issue by Vecheslav255** [telegramdesktop/tdesktop#26081]
### Steps to reproduce

For the latest version 4.7.1, I specify in "Speakers and headphones" the name of the sound device of my headphones. At the same time, the default sound device in the windows mixer is set to external speakers. And if I make an audio call, then the caller's sound goes to the external speakers and not to the headphones. 

### Expected behaviour

 I experimented for a long time and found a workaround by reverting to version 4.6.5. It doesn't show this problem.

### Actual behaviour

Apparently the setting "Speakers and headphones" is ignored.

### Operating system

windows 10

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

**Comment by LWChris** [comment]
I confirm, in settings, selected microphone is "Headphone microphone" but the one that's used is always the integrated one.

**Comment by Aokromes** [comment]
test on 4.8

**Comment by axgmsk** [comment]
Had the same issue before 4.8, it's fixed now! Thanks.
