### ISSUE TITLE
background running and GNOME

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#26087]
### Is your feature request related to a problem?

Since GNOME has no tray, the telegram desktop cannot continue to run in the background when the window is closed

### Describe the solution you'd like

I think this problem could be solved by using the environment variable `XDG_CURRENT_DESKTOP`. We can disable tray checking if the user environment is GNOME and have tdesktop try to minimize to tray.
Plus, with the release of GNOME 44, all applications running in the background are now visible in quick settings

### Describe alternatives you've considered

Maybe there are more "elegant" solutions to this problem that I do not know about

**Comment by miah-7** [comment]
> The close to taskbar option does exactly that

Nope
Close to taskbar option just hides the window, but it is still visible in overview mode and still occupies the desktop
GNOME has no "taskbar".

**Comment by ilya-fedin** [comment]
That sounds like a problem with representation of the API which is really on GNOME side. If they have no taskbar then maybe they shouldn't show the window in overview mode as you say.

**Comment by realgrm** [comment]
related https://github.com/telegramdesktop/tdesktop/issues/3830
