### ISSUE TITLE
Can' adjust audio playback speed on Linux

### ISSUE THREAD

**Issue by renato-dl** [telegramdesktop/tdesktop#26084]
### Steps to reproduce

Start the playback of a voice message.

### Expected behaviour

The button for changing playback speed should appear next to the volume button.

### Actual behaviour

The button for changing playback speed is not present.
I believe the issue manifested itself since version 4.7.0.

### Operating system

Fedora 37

### Version of Telegram Desktop

4.7.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
tdesktop has migrated from the openal-soft's pitch shifter effect to the ffmpeg's atempo filter, this depends on https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1567

**Comment by renato-dl** [comment]
Thanks for the quick reply, hopefully this is fixed quickly upstream.
A warning in the changelog or after the update would have been helpful, though. Maybe I'm one of the few using this feature and tdesktop Flatpak, but it seems a rather disruptive issue.

**Comment by ilya-fedin** [comment]
It was not known at the time of changelog creating and now it's too late

**Comment by mxcxpx** [comment]
sind 4.7 Version .
 no more Video speed 
also 
no Audio/ Podcast speed

**Comment by Aokromes** [comment]
> sind 4.7 Version . no more Video speed also no Audio/ Podcast speed

go upvote https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1567

**Comment by ilya-fedin** [comment]
I've added this one to #25126

**Comment by renato-dl** [comment]
With the latest release of freedesktop platform it's working again
