### ISSUE TITLE
User avoids block

### ISSUE THREAD

**Issue by grepwood** [telegramdesktop/tdesktop#26090]
### Steps to reproduce

1. Block Telegram (user with mobile number 42777).
2. Wait for Telegram update.

### Expected behaviour

I should not receive any more updates from Telegram.

### Actual behaviour

I get updates every now and then.

### Operating system

All

### Version of Telegram Desktop

All

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
very likely not a bug.

**Comment by grepwood** [comment]
It is a bug. Blocking a user should prevent them from contacting you.

**Comment by Aokromes** [comment]
> It is a bug. Blocking a user should prevent them from contacting you.

not if who contacts you have administrative powers.

**Comment by grepwood** [comment]
> > It is a bug. Blocking a user should prevent them from contacting you.
> 
> no if who contacts you have administrative powers.

That's abuse and harassment.

**Comment by Aokromes** [comment]
> > > It is a bug. Blocking a user should prevent them from contacting you.
> > 
> > 
> > no if who contacts you have administrative powers.
> 
> That's abuse and harassment.

no, it's how a lot of software works.

**Comment by lukezaa** [comment]
I am confirm the issue. I have same problem. 

I installed telegram as snapd package.

**Comment by Aokromes** [comment]
> > > > > It is a bug. Blocking a user should prevent them from contacting you.
> > > > 
> > > > 
> > > > no if who contacts you have administrative powers.
> > > 
> > > 
> > > That's abuse and harassment.
> > 
> > 
> > no, it's how a lot of software works.
> 
> Example?
> 
> Edit: Anyways. I just really, really don't want to get posts from this user. I don't care if it's the queen of England or the pope, I don't want to hear what they have to say. Is this possible to accomplish?

imagine you have channel with one image with a DMCA, you want to be contacted instead banned if not removed.

**Comment by grepwood** [comment]
Do you realize that this issue opens up an avenue for people to weasel they way into Telegram administratorship so that they can harass people who blocked them?

**Comment by ilya-fedin** [comment]
The updates don't come from the actual user, it's a virtual dialog having the same name and avatar as the service account

**Comment by grepwood** [comment]
Thank you for clearing that up @ilya-fedin! Is there any way to disable that dialog? I don't want to stop and check my phone every time I hear my phone buzz, because I treat all notifications seriously on the off-chance it could be my wife asking for help. I hope you understand.
