### ISSUE TITLE
Videos lagging

### ISSUE THREAD

**Issue by chellothere** [telegramdesktop/tdesktop#26092]
### Steps to reproduce

1.Open video
2. See its lagging

### Expected behaviour

Smoth videos

### Actual behaviour

Videos are lagging

### Operating system

Windows 8.1

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

**Comment by theelectricsoul** [comment]
I suggest closing this ticket, because you are using an operating system that is no longer supported by microsoft.

**Comment by Aokromes** [comment]
it's still supported by telegram desktop.

**Comment by chellothere** [comment]
Disabled angle graphic backend, its good now.

**Comment by vsile** [comment]
I have the same issue with Linux Manjaro.

![изображение](https://github.com/telegramdesktop/tdesktop/assets/9244347/0d157d98-010c-4be4-b3f3-71ae1ab6b283)

Linux manjaro 6.1.26-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Apr 26 22:07:35 UTC 2023 x86_64 GNU/Linux

![изображение](https://github.com/telegramdesktop/tdesktop/assets/9244347/bb5d6870-e5e1-4537-abca-9fe262ea402f)


It seems that Telegram does not use Nvidia Driver. Does it?
