### ISSUE TITLE
Touch pad freezes after starting Telegram Desktop on Linux for some time

### ISSUE THREAD

**Issue by Red1C3** [telegramdesktop/tdesktop#26096]
### Steps to reproduce

1. Start TG desktop on Linux (I had the same issue with Ubuntu and Fedora, both in distro provided builds and Flathub's)
2. Use TG or leave it in the background
3. The touch pad stops sending events to the system except for buttons

### Expected behaviour

The touch pad not to freeze

### Actual behaviour

The touch pad freezes for some time, sometimes it returns to normal after some time, touch pad device name: "ETPS/2 Elantech Touchpad"

### Operating system

Both Fedora 35-37 and Ubuntu 21, on GNOME

### Version of Telegram Desktop

Telegram Desktop 4.6.5 Flatpak

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
> 3\. The touch pad stops sending events to the system except for buttons

I fail to follow how tdesktop is related to this?
