### ISSUE TITLE
Messages in group topics remain unread even after being read

### ISSUE THREAD

**Issue by dmitriybo** [telegramdesktop/tdesktop#26098]
### Steps to reproduce

1. Write a message to the topic of the telegram group
2. Log in from another account on any device
3. Read the written message
4. Go to the first account, your message remained unread

### Expected behaviour

The message should become read, and the user should appear in the list of users who have read the message.

### Actual behaviour

Message remains unread

### Operating system

Windows 10

### Version of Telegram Desktop

4.7.1 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@dmitriybo The list of users who read the message isn't supported correctly in topics on server side :(

Do you check reading / read status from the same app version? Is it possible that you read from some client that doesn't support topics right now, like Telegram X for android?

**Comment by dmitriybo** [comment]
@john-preston I read messages from both iPhone and desktop. This problem is also observed in all chat participants. I noticed that this problem is present only in the "General" topic. In other topics, the message is marked as read, but I do not see who exactly read it. This is sorely lacking.

**Comment by dmitriybo** [comment]
@john-preston The problem has disappeared in the latest version. Users who have read messages are now displayed correctly.
