### ISSUE TITLE
Channels / Supergroups in Telegram Desktop too

### ISSUE THREAD

**Issue by RallyTuning** [telegramdesktop/tdesktop#26091]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

The same channels statistics that we can find in the mobile version, would be good to have also in the desktop version of Telegram

### Describe alternatives you've considered

None

**Comment by Aokromes** [comment]
duplicate.

**Comment by RallyTuning** [comment]
Weird, i have searched before post and didn't found anything
