### ISSUE TITLE
Sound device not reconnected during calls if using USB sound card

### ISSUE THREAD

**Issue by SagePtr** [telegramdesktop/tdesktop#26099]
### Steps to reproduce

1. Connect an external USB sound card to the PC, disable the others
2. Start a call (this USB sound card will be used as default one for both speaker/mic in the given call)
3. Disconnect this USB sound card from PC
4. Connect it back

### Expected behaviour

Telegram should detect the sound device is back and use it again rather than abandoning it until the user restarts the call or switches it manually back and forth in Call Settings.

### Actual behaviour

Telegram doesn't use the sound device anymore for current call until I manually switch the sound device in Call Settings or hang up the call and ring again.

### Operating system

Windows 10 22H2

### Version of Telegram Desktop

4.7.1 and some older versions

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#9814
