### ISSUE TITLE
[LINUX] Video/audio chats and calls do not work when built with OpenSSL 3

### ISSUE THREAD

**Issue by BalkanMadman** [telegramdesktop/tdesktop#26108]
### Steps to reproduce

1. Build from source or otherwise install Telegram Desktop client
(For example have OpenSSL 3 installed on Gentoo GNU/Linux system and "emerge" `telegram-desktop` ebuild)
2. Launch Telegram.
3. Try connecting to group video/audio chat

### Expected behaviour

It connects to a video/audio chat without any issues.

### Actual behaviour

Observe **endless** loading like so
![Screenshot_20230330_172810](https://user-images.githubusercontent.com/103487874/228869014-eb3cfe6f-b4a4-44ff-9264-faaa45d861e8.png)

### Operating system

Gentoo GNU/Linux with KDE Plasma 5.27.3 on Linux 6.2.8

### Version of Telegram Desktop

Telegram Desktop 4.6.5 built from source

### Installation source

Source code obtained from this GitHub repository compiled with Gentoo tooling on my machine

### Crash ID

None

### Logs
[telegram-distro.log](https://github.com/telegramdesktop/tdesktop/files/11112743/telegram-distro.log) <--- These are custom-compiled Telegram Desktop logs

------------
### Reasoning
I was "analysing" (looking through) the logs searching for obvious errors, when I noticed this interesting line (that is the 184th line):
```
(openssl_stream_adapter.cc:967): OpenSSLStreamAdapter::Error(SSL_read, 1, 0)
```
It is unable to read SSL stream, thus connection gets aborted:
```
(channel.cc:849): Changing voice state, recv=1 send=0 for {mid: audio1, media_type: audio}
(channel.cc:965): Changing video state, send=0 for {mid: 1, media_type: video}
(dtls_transport.cc:712): DtlsTransport[transport|0|_W]: Closed by remote with DTLS transport error, code=1
(channel.cc:567): Channel not writable ({mid: audio1, media_type: audio})
(channel.cc:567): Channel not writable ({mid: 1, media_type: video})
```
(These lines immediately follow the error in question)

I tried Flatpak and official (static binary in GitHub releases), but for now what I saved were only Flatpak's logs:
[telegram-flatpak.log](https://github.com/telegramdesktop/tdesktop/files/11112850/telegram-flatpak.log)
They just do not have this error...
```
(channel.cc:547): Channel writable ({mid: audio1, media_type: audio}) for the first time
(channel.cc:547): Channel writable ({mid: 1, media_type: video}) for the first time
<-----> THIS IS WHERE THAT OPENSSL ERROR OCCURRED IN DISTRO'S VERSION <----->
(channel.cc:849): Changing voice state, recv=1 send=0 for {mid: audio1, media_type: audio}
(channel.cc:965): Changing video state, send=0 for {mid: 1, media_type: video}
```

I came across a few bug reports having the same exact issue:
* https://github.com/telegramdesktop/tdesktop/issues/24692#issuecomment-1167000668
* https://github.com/telegramdesktop/tdesktop/issues/24721#issuecomment-1166948241

In every one of them OpenSSL 3 is mentioned, therefore I also think that it causes the problem.

**Comment by msva** [comment]
By the way:
1) I tested that too and also on gentoo (but with telegram-desktop from my overlay), and there is even no errors in log.txt :man_shrugging: 
2) It also fails to connect to 1-to-1 calls and stays on "keys exchange" state...

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by msva** [comment]
@Aokromes we do know that calls works then fine.
Moreover, I've already tested, that issue is exactly in OpenSSL 3.

Rebuilding all the stuff with OpenSSL 1.1 makes calls work again.

But OpenSSL 1.1 is already at [End Of Life](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/) state

**Comment by xvitaly** [comment]
I can confirm this issue on Fedora 37+. Calls are broken when built against OpenSSL 3.x.

**Comment by BalkanMadman** [comment]
Finally this bug gets recognition it deserves!) I will try to build telegram-desktop manually with OpenSSL 3.0 (without using `emerge` and distribution compile flags — so it is "pure"; to confirm it is a real bug) and report results/issues once I figure out how not to get some stupid WebRTC error on linking step.

This might not even be necessary, since it is being successfully reproduced by other people (at least it seems to be).

**Comment by BalkanMadman** [comment]
By the way there were **a lot** (I can't stress it enough) of warnings about using *deprecated functions* during compilation against OpenSSL 3.0.

**Comment by BalkanMadman** [comment]
> It also fails to connect to 1-to-1 calls and stays on "keys exchange" state...

I have also encountered this particular issue numerous times, but it is not consistent at all - sometimes it works and sometimes it does not. 
Group video/audio (what is the official name for it?) chats, on the other hand, do not work **at all** with OpenSSL 3.0

**Comment by DragonSerW** [comment]
Hi pals!
I can not answer to incoming call or perform a call in Fedora 38. In Fedora 35-37 all that stuff worked for sure. https://discussion.fedoraproject.org/t/hello-guys-i-can-not-perform-a-call-in-telegram/81457
`sudo dnf install telegram-desktop -y`

**Comment by BalkanMadman** [comment]
I compiled [tg_owt](https://github.com/desktop-app/tg_owt) (WebRTC library tdekstop uses) with OpenSSL 1.1.1 and tdesktop itself with OpenSSL 3 and... calls and video/audio chats **do work**!
So, the issue seems to be in the tg_owt library, the question is what to do with this?

**Comment by BalkanMadman** [comment]
I filed a bug on tg_owt repo: https://github.com/desktop-app/tg_owt/issues/122

**Comment by ilya-fedin** [comment]
Yes, please close it. It will just hang there forever.

**Comment by ilya-fedin** [comment]
Should be fixed on tg_owt master

**Comment by BalkanMadman** [comment]
Has anybody confirmed the fix yet? If not, then please don't close the issue

**Comment by ilya-fedin** [comment]
If anything, you can open a new one

**Comment by msva** [comment]
> Has anybody confirmed the fix yet? If not, then please don't close the issue

I can confirm

I already built and tested it yesterday (I have custom tdesktop and tg_owt 
packages in my overlay (mva))

(although, new versions not yet pushed. I'll push them today)

**Comment by BalkanMadman** [comment]
Can confirm that calls and video chats work fine when tg_owt and tdesktop are compiled with OpenSSL 3 with the latest commits in tg_owt (https://github.com/desktop-app/tg_owt/commit/6894e86eef8809d42b66eb85e376006f2a816a56 to https://github.com/desktop-app/tg_owt/commit/9d120195334db4f232c925529aa7601656dc59d7).
**The issue seems to be fixed**

**Comment by FranceBB** [comment]
Thank you for fixing it! :)
I look forward for the new build.
