### ISSUE TITLE
about modify the string in type MTPstring

### ISSUE THREAD

**Issue by muskalo** [telegramdesktop/tdesktop#26100]
### Steps to reproduce

1.there have a variable which  the type is MPTstring，this class have a public variable which name is QByteArray v, i use his function   
 append ,but it did not work

### Expected behaviour

change the string in type MTPstring, 

### Actual behaviour

did not work

### Operating system

windows

### Version of Telegram Desktop

4.6.3

### Installation source

Static binary from official website

### Crash ID

no

**Comment by john-preston** [comment]
@muskalo MTP* types are supposed only to be read from, not modify, they're always constant.

**Comment by muskalo** [comment]
think u , I'm in a misunderstanding

**Comment by muskalo** [comment]
> think u , I'm in a misunderstanding
