### ISSUE TITLE
Images won't open on Windows Desktop

### ISSUE THREAD

**Issue by juansgalt** [telegramdesktop/tdesktop#26101]
### Steps to reproduce

-Open telegram on windows 10.
-Click image in a chat
-Image does not expand like on mobile. A second telegram windows tries to open but fails. it shows up stacked on the task bar, but does not open when clicked, then disappears. As if images being opened to zoom in are crashing. 

### Expected behaviour

The images should open in a separate tab or the same tab, but show up bigger in higher resolution and allow zooming in etc, as is possible on mobile. 

### Actual behaviour

Image does not expand like on mobile. A second telegram windows tries to open but fails. it shows up stacked on the task bar, but does not open when clicked, then disappears. As if images being opened to zoom in are crashing. 

### Operating system

Windows 10

### Version of Telegram Desktop

4.7.1 64x

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Which scaling factor do you have set in Windows settings? Which ANGLE backend do you have set in Telegram settings?

**Comment by ilya-fedin** [comment]
Does it bug with ANGLE disabled?

**Comment by juansgalt** [comment]
That solved it, thanks!

**Comment by ilya-fedin** [comment]
Sounds like a dup of #26030

**Comment by juansgalt** [comment]
Perhaps, except I did not install via Microsoft store, but rather by downloading it from the website. Not sure if it is the portable version or not.
