### ISSUE TITLE
Why does the mac client have secret chats but windows and linux don't?

### ISSUE THREAD

**Issue by hous3m4ster** [telegramdesktop/tdesktop#2610]
It's really annoying to not have secret chats on dektop, that was the entire purpose for me to switch to telegram and I don't care about syncing, I just want the damn secret chats!

Even though the implementation of cutegram is horrible, they have secret chats. I am seriously considering switching to cutegram even though their client crashes a lot and looks horrible.

**Comment by stek29** [comment]
Because of reasons. You can read discussion at #871.

**Comment by aBARICHELLO** [comment]
The only Linux option for secret chats that I could find was `telegram-cli`: https://github.com/kenorb-contrib/tg
