### ISSUE TITLE
Not working video in videocall

### ISSUE THREAD

**Issue by ForesterDev** [telegramdesktop/tdesktop#26106]
### Steps to reproduce

1. Make a video call from Android Telegram app
2. There will be no incoming video on the PC

### Expected behaviour

Video call should work. If I call from Telegram desktop to Telegram desktop, then everything works. When I call from the mobile application - there is no video on the PC

### Actual behaviour

Incoming video not working for PC user

### Operating system

Windows 7

### Version of Telegram Desktop

4.7.1 x64

### Installation source

Static binary from official website

**Comment by theelectricsoul** [comment]
It is best to close this ticket, because you are using an unsupported operating systems.

https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962

**Comment by Aokromes** [comment]
it's still supported by telegram desktop.

**Comment by SlithyWithy** [comment]
I have the same issue on Windows 10 build 19045.3448 with desktop telegram v. 4.10.2 when calling on Android or receiving calls from Android, person on the other end can see image from their own webcam in the corner and they can see my camera feed, but i only see my own webcam in the corner and their profile image as if their camera is off
