### ISSUE TITLE
Telegram crashes with code 134 when trying to watch the video (normal view, not autoplaying preview)

### ISSUE THREAD

**Issue by Farxial** [telegramdesktop/tdesktop#26104]
### Steps to reproduce

Upload to Telegram and try to watch the video /\*RU: Загрузить и попытаться посмотреть видео\*/ https://drive.google.com/file/d/1h8hSs0Rkh1mxmE6Ko9GhdeMw8bsLfkAt/view?usp=sharing
This is a video fragment obtained from (renamed) /\*RU: Это фрагмент видео, полученный из (переименованного)\*/
[Magical_Pokahn_TV_[09_of_12]\_[ru_jp]\_[Cuba77_&_AnimeReactor_Ru].avi](https://drive.google.com/file/d/1Buz_cvrQ0-TsKpHE7KlieHpdR0OYrzY3/view?usp=sharing) (Size: 253736960; Hashes: MD5: 7167E387495A886189F4C5EDCE27B7C1, SHA1: 3ED0D17A99F087D1C0C407D9D0CD493974CDF122, SHA256: 687C63B3CA30FE55AF59F75F9780624F2B62FD00E05FD63A19AC6CCCDF54CC96, MD4: 1B431046357CEFAAA484F8E4AE5CCFCE, ED2K-V2: 31FFB6DF0EBF567E020C90AAD016D0E6)
using script /\*RU: скриптом\*/ (ffmpeg-tpart):
```
#!/bin/sh

export NAME="${1}"
export EXT=${2}
export SUB_NAME="${3}"
export START=${4}
export END=${5}
export EXT2=${6}

#ffmpeg -ss ${START} -i "${NAME}.${EXT}" -to ${END} -c copy -copyts "${NAME} ${SUB_NAME}.${EXT}"
ffmpeg -ss ${START} -i "${NAME}.${EXT}" -to ${END} -vcodec libx264 -acodec mp3 -copyts "${NAME} ${SUB_NAME}.${EXT2}"
```
`ffmpeg-tpart "09. 絶交の呪文は色男さんいらしゃーい ̸ 白の呪文はクリスマス" avi Batata 01:29.98 01:59.52 mp4`
The commented line didn't work either. /\*RU: С закомментированной строкой тоже не работало.\*/

### Expected behaviour

Do not crash (and even better play the video: yes, ffmpeg converted it crookedly, but Mozilla Firefox (Linux) and The KMPlayer 4.2.1.4 KMP Plus (Windows) play it).
/\*RU: Чтобы не падал (а ещё лучше воспроизводил видео: да, это ffmpeg криво сконвертировал, но Mozilla Firefox (Linux) и The KMPlayer 4.2.1.4 KMP Plus (Windows) воспроизводят же).\*/

### Actual behaviour

Crashes and does not play video. (Plays only in autoplaying preview.)
/\*RU: Падает и не воспроизводит видео. (Воспроизводит только в автоматически воспроизводимом превью.)\*/

### Operating system

Linux localhost 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

### Logs

```shell
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
  OpenType support missing for "DAOpenSansRegular", script 15
  OpenType support missing for "davazirregular", script 15
  OpenType support missing for "DAOpenSansRegular", script 11
  OpenType support missing for "davazirregular", script 11
  OpenType support missing for "DAOpenSansRegular", script 19
  OpenType support missing for "davazirregular", script 19
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
QTextCursor::setPosition: Position '8388607' out of range
QTextCursor::setPosition: Position '8388607' out of range
/opt/rh/devtoolset-10/root/usr/include/c++/10/bits/stl_algo.h:3677: constexpr const _Tp& std::clamp(const _Tp&, const _Tp&, const _Tp&) [with _Tp = long int]: Assertion '!(__hi < __lo)' failed.
Aborted (core dumped)
```

**Comment by ilya-fedin** [comment]
This bugtracker is English-only

**Comment by Farxial** [comment]
Too many data to translate, I does not know English well, sorry. You may just follow link and exec script, anyway :)

**Comment by Farxial** [comment]
Well, pacman -S / pacman -Syyu _is_ normal, adequate build, isn't it?
Anyway: I discovered a some serious (crashing while processing user content) bug — I reported a bug. But you may not process it, if you don't want.
If so... Sorry for the unrelevant post. And sorry for my speech. v.v

**Comment by ilya-fedin** [comment]
I don't know how much is it normal, the thing is it's third party and I have no idea how to instruct you with debugging using such a build. If you want to proceed with this bugtracker, please install Telegram from https://desktop.telegram.org, modify the issue according to the behavior you will see on the official build and leave a comment as there's no notification for editions.

**Comment by Farxial** [comment]
OK, I have updated the details according to new test environment.

**Comment by Farxial** [comment]
I'm sorry, but I already done testing, deleted the VM snapshot, etc., and I not going to repeat it all again. I did not see any (newly created) files in the working folder with unpacked Telegram executable; the Telegram process just terminated, and left me the output in the console. All instructions for reproduce are present.

**Comment by Farxial** [comment]
I don't want to link my nickname here and my Telegram account info. I don't know how exactly the crash ID feature works, what does it send. I can't orient myself by user agreement, like privacy notice, due to nature of formal agreements on common. So I have to read the Telegram source codes. But I didn't mean to do it. All of this means that if I knew right away that a crash ID was required, I probably wouldn't even have created the issue. But there is no asterisk in the issue form, so I don't need to obtain the crash ID.
