### ISSUE TITLE
Error: org.telegram.desktop needs a later flatpak version

### ISSUE THREAD

**Issue by m3thm4th** [telegramdesktop/tdesktop#26109]
### Steps to reproduce

Run `flatpak update` on version 4.7.1 or `flatpak install` if not installed

### Expected behaviour

The app should be updated or installed

### Actual behaviour

The app is not updated or not installed and this error message is displayed
`Error: org.telegram.desktop needs a later flatpak version`

### Operating system

Debian 11

### Version of Telegram Desktop

4.7.1

### Installation source

Flatpak

**Comment by Aokromes** [comment]
you need to update flatpak.

**Comment by fleminra** [comment]
It fails with flatpak 1.10.7-0+deb11u1 of Debian 11 (bullseye), but FWIW, it works with flatpak 1.14.4-1~bpo11+1 from bullseye-backports.
