### ISSUE TITLE
Allow reordering proxies

### ISSUE THREAD

**Issue by TheWeirdDev** [telegramdesktop/tdesktop#26110]
### Is your feature request related to a problem?

For users who have many proxies added, ordering and organizing them is important and useful. I would like to keep the working proxies at the top of the list but I often have to scroll and find ones that I want.

### Describe the solution you'd like

Both of these are good solutions:

1. Add a drag handle to list items to allow manual ordering
2. Add an option to sort them by ping

### Describe alternatives you've considered

For now, If I want to bring one proxy to the top I have to delete it and manually add it again. This takes time and has a bad UX.

### Additional context

I think the android app has a similar feature, so it makes sense to implement it on desktop as well.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25662
