### ISSUE TITLE
Latest update breaks Debian Stable and Ubuntu LTS and their derivatives

### ISSUE THREAD

**Issue by m3thm4th** [telegramdesktop/tdesktop#26111]
### Steps to reproduce

Run `flatpak update` on version 4.7.1 or `flatpak install` if not installed (Flatpak is at the latest version available in the Debian repos (1.10.7-0+deb11u1) and can't be updated without [breakage](https://wiki.debian.org/DontBreakDebian)

### Expected behaviour

The app should be updated or installed

### Actual behaviour

The app is not updated or not installed and this error message is displayed
`Error: org.telegram.desktop needs a later flatpak version`

### Operating system

Debian Stable and Ubuntu LTS

### Version of Telegram Desktop

4.7.1

### Installation source

Flatpak

**Comment by Aokromes** [comment]
again, it's not a bug, if you want to have updated telegram desktop without problems get static binary version from webpage.

**Comment by ilya-fedin** [comment]
There's https://launchpad.net/~flatpak/+archive/ubuntu/stable for Ubuntu. In Debian case probably nothing could be done, it's just too old for the tdesktop flatpak.

**Comment by ilya-fedin** [comment]
Ah, I see modern flatpak in backports for stable: https://packages.debian.org/bullseye-backports/flatpak

**Comment by ilya-fedin** [comment]
@m3thm4th you can use other installation methods for such distros - static binary or snap

**Comment by ilya-fedin** [comment]
@m3thm4th sorry, but this is non-realistic, Qt does moves in direction of deprecating older systems and fighting with that is non-trivial. If you want for tdesktop to not to deprecate older systems, ask Qt to not to do that, so it's easy for tdesktop to continue to support them. If you pursue Qt to revert [this](https://codereview.qt-project.org/c/qt/qtbase/+/322313) commit, support of your system could be restored.
