### ISSUE TITLE
formatted as "MarkdownV2"

### ISSUE THREAD

**Issue by servim** [telegramdesktop/tdesktop#26122]
### Steps to reproduce

Send message via telegrambot formatting text as "MarkdownV2"
where spaces align the text to the right side. Compare the result in android client and desktop client.

### Expected behaviour

Spaces on client desktop must be the same size as other characters (monospaced text)

### Actual behaviour

Spaces on client desktop are smaller than other characters (non-monospaced text).
android client:
![android](https://user-images.githubusercontent.com/22333446/229323144-e298522c-1033-4b54-90a5-310864d4d28c.jpg)
desktop client:
![desktop](https://user-images.githubusercontent.com/22333446/229323148-05f3f641-a3fd-4f80-a17f-60fd7f512cb6.jpg)

### Operating system

Windows 10 and Windows11

### Version of Telegram Desktop

4.7.1 х 64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> Spaces on client desktop must be the same size as other characters (monospaced text)

Are you sure the spaces are at fault, not emoji?

**Comment by servim** [comment]
here's an underscore instead of a space:
![image](https://user-images.githubusercontent.com/22333446/229324179-0187fa6a-c928-4843-8c77-02232900abab.png)

**Comment by ilya-fedin** [comment]
but before emoji they seem to be the same size?

**Comment by servim** [comment]
I understood the hint, I'll try to study this issue. But if the space is not to blame, then the problem is still there, why does the android and the desktop display this differently? If the problem is in the emoticon, how to solve it? Thanks for the very fast response ;)

**Comment by ilya-fedin** [comment]
> why does the android and the desktop display this differently

They're built using different libraries. The Android application is a native Android application, tdesktop is a Qt application. Qt handles text by itself. And both Android client and tdesktop have custom emoji engines, not using the ones in Android or Qt.

**Comment by servim** [comment]
You're right! If you remove the smiley, then the spaces look right!
Then you need to rephrase the problem:
The space after the emoticon is not monospaced.
![image](https://user-images.githubusercontent.com/22333446/229324542-b76b3b05-11ee-4245-893a-03d7c0ae4867.png)
![image](https://user-images.githubusercontent.com/22333446/229324598-7264a650-4329-410a-91f7-ac70d8fb51d3.png)

**Comment by ilya-fedin** [comment]
> How can I solve this problem?

You can investigate the emoji rendering code at https://github.com/desktop-app/lib_ui/blob/master/ui/text/text_renderer.cpp

**Comment by servim** [comment]
Thank you! But you clearly overestimate my abilities :)
