### ISSUE TITLE
Unable to send image as image

### ISSUE THREAD

**Issue by Sarisan** [telegramdesktop/tdesktop#26124]
### Steps to reproduce

1. download original size of image, [pixiv](https://www.pixiv.net/en/artworks/82576226)
2. try to upload it to any chat

### Expected behaviour

It should show an option to compress the image

### Actual behaviour

You see no option to compress the image, it sends it as file

### Operating system

Debian 12, GNOME 43.3

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I can't access the image
![изображение](https://user-images.githubusercontent.com/17829319/229381411-38c64d12-c528-463d-a3dc-308a91a4ca00.png)

**Comment by 5225225** [comment]
Can reproduce this with a 5000x7000 sized all-black PNG made in GIMP.

I figure this is hitting some limit of the resizer.

**Comment by ilya-fedin** [comment]
> Can reproduce this with a 5000x7000 sized all-black PNG made in GIMP.

I can't paste such an image at all, Qt fails early with the following error in terminal:
```
qt.gui.imageio: QImageIOHandler: Rejecting image as it exceeds the current allocation limit of 128 megabytes
```

**Comment by ilya-fedin** [comment]
Ah, I can't when pasting from clipboard, but I indeed can when pasting from a file. Yes, Qt can't read the image, so it's being interpreted as a file. There's nothing could be done from tdesktop code, it's internal limitation of Qt.

**Comment by Sarisan** [comment]
> Ah, I can't when pasting from clipboard, but I indeed can when pasting from a file. Yes, Qt can't read the image, so it's being interpreted as a file. There's nothing could be done in tdesktop code, it's internal limitation of Qt.

I guess there may be a way to add image resizer that resize image before it goes to Qt?

**Comment by ilya-fedin** [comment]
> I guess there may be a way to add image resizer that resize image before it goes to Qt?

I'm not sure how would you resize _before_ Qt given that the project uses Qt for all the image operations.
