### ISSUE TITLE
Regression: after upgrade to 4.7.1 there is no more audio and video speed control

### ISSUE THREAD

**Issue by gentoo-root** [telegramdesktop/tdesktop#26125]
### Steps to reproduce

1. Play a video or a voice message.

### Expected behaviour

There should be the 2X button for voice messages and the slider for videos that allow to increase and decrease the playback speed, like in the previous version of Telegram.

### Actual behaviour

After the upgrade to 4.7.1, the relevant controls disappeared, and there is no way to control the playback speed.

### Operating system

Arch Linux, GNOME 43.3

### Version of Telegram Desktop

4.7.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1567
