### ISSUE TITLE
Missing emoji / stickers for Suggestion Profile Photos

### ISSUE THREAD

**Issue by VetaLioSTV** [telegramdesktop/tdesktop#26131]
### Steps to reproduce

From update on [03.02.23](https://telegram.org/blog/profile-pics-emoji-translations/ru) which added possibility to use emoji/stickers on profile photos(+suggestion profile photos) and till now, for some reason Desktop client still doesn't have possibility to use emoji/sticker for "Suggestion Profile Photos".

### Expected behaviour

It should be consistent as how it works/implemented on each platform(iOS/Android) and even how it already works for "Replace Photo Profile"(Local change that isn't shown to contact)!

### Actual behaviour

Currently you can only choose "photo" for "Suggestion Profile Photos" in comparison to "Replace Photo Profile" which has two menu items (choose photo \ choose emoji or sticker), so choose emoji or sticker for "Suggestion Profile Photos" is missing.

![image](https://user-images.githubusercontent.com/15155286/229899585-87dce76e-b3c1-4928-8aee-315ba0b28669.png)

### Operating system

Win 10 x64

### Version of Telegram Desktop

v4.6.0 - v4.7.0

### Installation source

Static binary from official website

### Logs

```shell
Not required
```

**Comment by VetaLioSTV** [comment]
@john-preston Any ideas why? Its already implemented and missing UI part ;(

**Comment by ilya-fedin** [comment]
I have no thoughts, I usually don't touch tdesktop UI code (it's hard to read for a person not involved in writing). If you have any questions regarding Linux support then I happy to answer.

**Comment by VetaLioSTV** [comment]
@ilya-fedin clear, but who's then responsible for UI part? 😢 I need to check manually commits to found \ determine person? 😭

**Comment by ilya-fedin** [comment]
Well, tdesktop has only one hired person, @john-preston. Everyone else is volunteering and doing what's interested (including me).

**Comment by john-preston** [comment]
Yes, it wasn't present in the UI mockups, on mobiles the UI is suited better for that. I'll ask my designer.

**Comment by VetaLioSTV** [comment]
@john-preston hey? :)
