### ISSUE TITLE
Menus and tooltips are too large in the latest Flatpak

### ISSUE THREAD

**Issue by hexchain** [telegramdesktop/tdesktop#26133]
### Steps to reproduce

Open Telegram Flatpak and trigger some menus or tooltips.

### Expected behaviour

Menus and tooltips should display in their correct sizes.

### Actual behaviour

Menus and tooltips are too large.

![image](https://user-images.githubusercontent.com/529520/229980715-1d3cbdde-3c0b-40cf-adf7-fdad070f975a.png)
![image](https://user-images.githubusercontent.com/529520/229980766-22f0103c-803d-4dc5-a602-ec877c875a8d.png)

A [similar issue](https://github.com/fcitx/fcitx5-qt/issues/38) has happened to fcitx5-qt before. Maybe the same fix also applies?

### Operating system

Arch Linux, Plasma 5.27.3, Wayland

### Version of Telegram Desktop

4.7.1

```
% flatpak info org.telegram.desktop

Telegram Desktop - Fast. Secure. Powerful.

          ID: org.telegram.desktop
         Ref: app/org.telegram.desktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.7.1
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 199.3 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: c779ebef5304ca28baa5792249a28a5260971b0681efd79fc471b11fd1a4d770
      Parent: 1d03f448b3f4e66b87ea21968f1479675a6d3bbc374f9a0ec72d3330c44bb7e4
     Subject: Update to commit with abstract socket support (0fef1c56)
        Date: 2023-04-03 18:49:06 +0000
```

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
tdesktop indeed actively uses this hint, but I guess we can't just remove it. We also don't support Qt's fractional scaling, so viewporter not being initialized should cause no harm, Qt should just use the core protocol scaling :thinking:

**Comment by ilya-fedin** [comment]
Is it possible you have any experimental settings enabled?

**Comment by hexchain** [comment]
I do have "Enable precise High DPI scaling" turned on without realizing it. Turning it off indeed makes this issue disappear.

Thanks!
