### ISSUE TITLE
Pin topics

### ISSUE THREAD

**Issue by psimonetti** [telegramdesktop/tdesktop#26137]
### Is your feature request related to a problem?

No, it's not.

### Describe the solution you'd like

I'd like group admins to be able to pin topics of a group, so that the members will see them at the top of the topics list. 

### Describe alternatives you've considered

I couldn't think of any others.

### Additional context

In my organization, we use telegram as communication platform. 
We have the following topics, among the others:
- **Communications**, where admins write and discuss news/communications for all the members of the organization; 
- **Ask an admin**, where members can write questions to the admins.
Then, there are all the other topics.
We find the first two topics to be really important for the organization, so we would like those topics to stay always at the top of the list (while the others might keep being ordered based on the chat history, as I think it's now).

**Comment by RememberTheAir** [comment]
Admins with the "manage topics" permission can already pin up to 5 (as far as I remember) topics for everyone: 

![image](https://user-images.githubusercontent.com/16143208/230080334-47958391-5463-4202-b47e-1d8151ecae1b.png)
