### ISSUE TITLE
[regression] broken build of v4.7.1 with glibmm 2.68

### ISSUE THREAD

**Issue by mikhailnov** [telegramdesktop/tdesktop#26148]
### Steps to reproduce

https://github.com/desktop-app/lib_base/commit/0d37d47eca896005eb0a645e0db461f4dafb317b broke building:

```
DEBUG: /builddir/build/BUILD/tdesktop-4.7.1-full/Telegram/lib_base/base/platform/linux/base_url_scheme_linux.cpp: In function â€˜void base::Platform::UnregisterUrlScheme(const base::Platform::UrlSchemeDescriptor&)â€™:
DEBUG: /builddir/build/BUILD/tdesktop-4.7.1-full/Telegram/lib_base/base/platform/linux/base_url_scheme_linux.cpp:176:55: error: â€˜get_recommended_for_typeâ€™ is not a member of â€˜Gio::AppInfoâ€™
DEBUG:   176 |         const auto registeredAppInfos = Gio::AppInfo::get_recommended_for_type(
DEBUG:       |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
```

I failed to understand what and why that commit did, so reporting an issue.
CC @ilya-fedin , please have a look if possible.

Both lib64glibmm2.4-devel and lib64glibmm2.68-devel are installed at build time. `-isystem /usr/include/glibmm-2.68` is present in compiler flags, so 2.68 is used.

### Expected behaviour

.

### Actual behaviour

.

### Operating system

Linux

### Version of Telegram Desktop

4.7.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
you need glibmm 2.76
