### ISSUE TITLE
Automatic interface scale based on Windows

### ISSUE THREAD

**Issue by Chaoscontrol** [telegramdesktop/tdesktop#26146]
### Is your feature request related to a problem?

I work with multiple screens, with different interface scales in between them. Most apps get resized as soon as you move them from one screen to another. 
Telegram doesn't and it makes unreadable when going from 100% to 150% scale screens for example. You need to manually go into Telegram settings and adjust the scale manually. 

### Describe the solution you'd like

Automatic interface scale based on Windows settings, just like most other apps do. So it resizes when moving the window from one screen to another. 

### Describe alternatives you've considered

Manually changing the setting in Telegram each time you move the window.

**Comment by ilya-fedin** [comment]
#1121

**Comment by Chaoscontrol** [comment]
Sorry and thanks. I had searched first, but clearly didn't use the right keywords.
