### ISSUE TITLE
The window doesn't open if Telegram is already running in the background

### ISSUE THREAD

**Issue by proninyaroslav** [telegramdesktop/tdesktop#26141]
### Steps to reproduce

1. Install Telegram from Flathub
2. Launch Telegram and stay it running in the background (I use [libappindicator](https://github.com/ubuntu/gnome-shell-extension-appindicator) extension for GNOME)
3. Launch Telegram again, for example, from GNOME menu or by command in terminal: `flatpak run org.telegram.desktop`

### Expected behaviour

Telegram window opens even if it's already running on the background.

### Actual behaviour

Launching `flatpak run org.telegram.desktop` or launching application icon does nothing, the window doesn't open, in the systemd log I see only this:
```
systemd[2106]: app-flatpak-org.telegram.desktop-40694.scope gestartet.
```
The only way to open the window when the app is in the background is to right click on the icon in the status bar and click "Open Telegram".

### Operating system

Fedora Linux 37

### Version of Telegram Desktop

4.7.1

### Installation source

Flatpak

### Logs

[log.txt](https://github.com/telegramdesktop/tdesktop/files/11173927/log.txt)
[log_start0.txt](https://github.com/telegramdesktop/tdesktop/files/11173928/log_start0.txt)

**Comment by ilya-fedin** [comment]
Please provide the logs like explained in the issue template

**Comment by proninyaroslav** [comment]
@ilya-fedin 
[log.txt](https://github.com/telegramdesktop/tdesktop/files/11173930/log.txt)
[log_start0.txt](https://github.com/telegramdesktop/tdesktop/files/11173931/log_start0.txt)


```
[2023.04.06 22:34:11] Connecting local socket to ace581086d91a2150cf553152709d9f4-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2023.04.06 22:34:11] This is the only instance of Telegram, starting server and app...
[2023.04.06 22:34:11] Failed to start listening to ace581086d91a2150cf553152709d9f4-{87A94AB0-E370-4cde-98D3-ACC110C5967D} server: QLocalServer::listen: Address in use
```

**Comment by ilya-fedin** [comment]
That's quite weird, it can't connect to the socket yet and it can't bind to it, I can't reproduce that locally on NixOS. Maybe SELinux is at fault? Try to switch it to permissive mode.

**Comment by FiestaLake** [comment]
I have a similar issue in flatpak tdesktop, Arch Linux without Selinux enabled/enforced.

**Comment by ilya-fedin** [comment]
> Arch Linux without Selinux enabled/enforced.

maybe you have apparmor enabled or some other security feature?

**Comment by FiestaLake** [comment]
> > Arch Linux without Selinux enabled/enforced.
> 
> maybe you have apparmor enabled or some other security feature?

Tried unloading every apparmor profile, still same issue.

**Comment by ilya-fedin** [comment]
> Tried unloading every apparmor profile, still same issue.

maybe it denies the access to the socket by default? try to disable it

**Comment by FiestaLake** [comment]
> > Tried unloading every apparmor profile, still same issue.
> 
> maybe it denies the access to the socket by default? try to disable it

Disabled the service and lsm module, still not opening the window.

**Comment by ilya-fedin** [comment]
> Disabled the service and lsm module, still not opening the window.

can you provide the logs like @proninyaroslav did?

**Comment by FiestaLake** [comment]
> > Disabled the service and lsm module, still not opening the window.
> 
> can you provide the logs like @proninyaroslav did?
[log_start0.txt](https://github.com/telegramdesktop/tdesktop/files/11176866/log_start0.txt)
[log.txt](https://github.com/telegramdesktop/tdesktop/files/11176867/log.txt)

Same issue with the original issuer's one.

**Comment by ilya-fedin** [comment]
Nevermind, looks like I just not enough tested this previously, I indeed can reproduce this.

**Comment by proninyaroslav** [comment]
> Maybe SELinux is at fault? Try to switch it to permissive mode.

No effect.
