### ISSUE TITLE
Wzlom

### ISSUE THREAD

**Issue by qwasixaid** [telegramdesktop/tdesktop#26147]
### Steps to reproduce

Мой аккаунт в телеграмме взомали и я могу доказать то что это мой аккаунт и его взомали сначала меня выкинуло с акаунта и не не пришло никаких уведомлений я пытаюсь зайти а там стоит облачный пароль и мне пишет ктото и пишет что взломал мой акаунт мой 2ой аккаунт @qwwdjj номер телефона акаунота которого взомали +380988873970
eng:My telegram account was hacked and I can prove that this is my account and it was hacked first I was kicked out of the account and I didn’t receive any notifications, I try to log in and there is a cloud password and someone writes to me and writes that my account was hacked my 2nd account @ qwwdjj phone number of the account who was charged +380988873970

### Expected behaviour

Дать мне доступ к аккаунту
ENG:Give me access to my account

### Actual behaviour

Я создал новый аккаунт 

### Operating system

?

### Version of Telegram Desktop

?

### Installation source

Static binary from official website

### Crash ID

Взом блять тупые дауны

### Logs

```shell
идите нахуй
```

**Comment by Aokromes** [comment]
this a telegram desktop bugtracker, not place to report accounts hacked.
