### ISSUE TITLE
Unable to open Telegram Desktop on EndeavourOS

### ISSUE THREAD

**Issue by manupernas** [telegramdesktop/tdesktop#26149]
### Steps to reproduce

sudo pacman -Syu
telegram-desktop

### Expected behaviour

Open as usual

### Actual behaviour

telegram-desktop: /lib/libQt6WaylandCompositor.so.6: no version information available (required by telegram-desktop)
telegram-desktop: /lib/libQt6Core5Compat.so.6: no version information available (required by telegram-desktop)
telegram-desktop: /lib/libQt6Quick.so.6: no version information available (required by telegram-desktop)
telegram-desktop: /lib/libQt6QuickWidgets.so.6: no version information available (required by telegram-desktop)
telegram-desktop: /lib/libQt6Qml.so.6: no version information available (required by telegram-desktop)
telegram-desktop: /lib/libQt6Svg.so.6: no version information available (required by telegram-desktop)
telegram-desktop: /lib/libQt6Core.so.6: version `Qt_6.5' not found (required by telegram-desktop)

### Operating system

EndeavourOS

### Version of Telegram Desktop

7.1.1

### Installation source

Other (unofficial) source

### Logs

```shell
telegram-desktop: /lib/libQt6WaylandCompositor.so.6: no version information available (required by telegram-desktop)
telegram-desktop: /lib/libQt6Core5Compat.so.6: no version information available (required by telegram-desktop)
telegram-desktop: /lib/libQt6Quick.so.6: no version information available (required by telegram-desktop)
telegram-desktop: /lib/libQt6QuickWidgets.so.6: no version information available (required by telegram-desktop)
telegram-desktop: /lib/libQt6Qml.so.6: no version information available (required by telegram-desktop)
telegram-desktop: /lib/libQt6Svg.so.6: no version information available (required by telegram-desktop)
telegram-desktop: /lib/libQt6Core.so.6: version `Qt_6.5' not found (required by telegram-desktop)
```

**Comment by holydrug** [comment]
@manupernas downgrade to telegram-desktop-4.6.5-3 fixed that problem btw
