### ISSUE TITLE
HiDPI Scaling

### ISSUE THREAD

**Issue by nullptroma** [telegramdesktop/tdesktop#26155]
### Steps to reproduce

1) Install KDE Plasma with common monitor
2)Launch tg
3) Change monitor to HiDPI (27', 2K)
4) Enable system scaling 125%
5)Launch tg

### Expected behaviour

Proportional enlargement of the window and all its elements without loss of quality

### Actual behaviour

Window enlargement, as it should be. The text has not lost quality. All pictures, photos and icons are in very poor quality, pixelated and blurry.
Screenshot: [https://i.imgur.com/n9IWjO9.png](url)

It seems to work as it should sometimes when I experiment with environment variables (I never noticed a pattern). Now I deleted all references to Telegram in the system, ran the app from the official site and it worked. Then I restarted the pc and it blurred again.

Sources:
From snap works perfectly.
From all other sources (aur, pacman, official website) it does not work correctly.

### Operating system

ArchLinux, KDE Plasma (more in logs)

### Version of Telegram Desktop

4.7.1-1

### Installation source

Static binary from official website

### Logs

```shell
Operating System: Arch Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.10-lqx1-2-lqx (64-bit)
Graphics Platform: X11
Processors: 16 × 11th Gen Intel® Core™ i7-11700F @ 2.50GHz
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B560M AORUS ELITE
```

**Comment by ilya-fedin** [comment]
> Static binary from official website

I'm highly doubt this is true, the bug on the screenshot is known to happen only on third-party builds. It's a KDE bug (sadly still no one reported it to them, see #25126 for details), but all official builds have a Qt patch applied to avoid this bug.

**Comment by nullptroma** [comment]
Unfortunately right now I have tried all sources, and on Xorg this problem is everywhere. What could be wrong with my system that is not working for me?

**Comment by ilya-fedin** [comment]
Try to reset experimental settings while using official binary

**Comment by nullptroma** [comment]
How?

**Comment by nullptroma** [comment]
I didn't notice the button)
Now I pressed it, the application restarted, nothing has changed. By the way, the experimental setting "Enable precise Hi-DPI Scaling" does not affect anything.

**Comment by ilya-fedin** [comment]
Are you sure you have done it using the official build, not the Arch Linux's build?

**Comment by ilya-fedin** [comment]
The thing is KDE forces the precise scaling bypassing Telegram logic by using Qt's debugging API. That's why only Qt patching helps.

**Comment by nullptroma** [comment]
> Are you sure you have done this using the official build, not the Arch Linux's build?

I downloaded the linux archive from this site https://desktop.telegram.org/, unzipped it and ran it through the console ./Telegram

**Comment by nullptroma** [comment]
Miss click*

**Comment by ilya-fedin** [comment]
> and ran it through the console ./Telegram

does it immediately return you to the shell prompt? If yes, it means the applciation haven't launched, only focused the window of already running instance.

**Comment by nullptroma** [comment]
> > and ran it through the console ./Telegram
> 
> Does it immediately return you to the shell prompt? If yes, it means the application haven't launched, only focused the window of already running instance (which is probably the Arch Linux build).

Before that, if I have another Telegram running from any source I right click on the tray icon and "Exit". When launching through the console, as I showed above, I do not get control back in the console, that is, everything works as it should, the application is launched from the console.

Another interesting fact: Everything works fine on Wayland

**Comment by ilya-fedin** [comment]
> Another interesting fact: Everything works fine on Wayland

Well yes, KDE doesn't force precise scaling on Wayland fortunately (but it still does weird thing with other Qt debug variables).

I'm not sure what really happens, would like to see the log.txt (issue template describes how to get it).

**Comment by nullptroma** [comment]
[log.txt](https://github.com/telegramdesktop/tdesktop/files/11192223/log.txt)

**Comment by ilya-fedin** [comment]
`QT_SCALE_FACTOR_ROUNDING_POLICY: PassThrough` :cry:

**Comment by ilya-fedin** [comment]
Maybe you have set it manually? I never seen this vairable set on KDE.

**Comment by nullptroma** [comment]
It's really about this variable! I removed it manually and checked, now Telegram looks right. Thanks so much, I'll try to find where I have it set!

**Comment by ilya-fedin** [comment]
Maybe you're using a non-standard display manager and it sets the variable?

**Comment by nullptroma** [comment]
I got deepin packages from somewhere that change QT's behavior. I had to remove the packages in the screenshot
![2023-04-11_19-43](https://user-images.githubusercontent.com/64524860/231288556-eb6216b4-632c-4b06-9f4a-e6500071d606.png)
