### ISSUE TITLE
Telegram desktop does not work for local web applications, returns (null) in the application window.

### ISSUE THREAD

**Issue by averinbox** [telegramdesktop/tdesktop#26159]
### Steps to reproduce

I'm trying to launch telegram web app for local development. I use https self-signed certificates so that telegrams can reach the local web server. In response, I get **(null)** in the application window. Moreover, external applications work fine, such as Durgerking. Everything works fine on MacOS in Windows.

### Expected behaviour

Opening the application for local development.

### Actual behaviour

Good afternoon
I'm trying to launch telegram web app for local development.
I use https self-signed certificates so that telegrams can reach the local web server, but in response I get (null) in the application window. Moreover, external applications work fine, such as Durgerking.

### Operating system

Ubuntu MATE 22.04

### Version of Telegram Desktop

Telegram desktop: 4.7.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Maybe you're using a non-standard (non-80) port? I bet there were reports about this previously.

**Comment by averinbox** [comment]
> Maybe you're using a non-standard (non-80) port? I bet there were reports about this previously.

Yes, I use not 80 but the standard port 443 TLS. These are the telegram requirements for web app applications. The requirement is to use only the certificate and port 443. I don’t really understand why they did it, but when I try to install http:/127.0.0.1 or nttp://locahost into botfatner, I get an error that I need to use https.
