### ISSUE TITLE
Media Viewer opens in the wrong display

### ISSUE THREAD

**Issue by prppedro** [telegramdesktop/tdesktop#26157]
### Steps to reproduce

1. Go to any chat; 
2. Open any media. 

### Expected behaviour

Media Viewer displays the media resource in full screen, in the same display Telegram is currently running. 

### Actual behaviour

If previously open in full screen: goes to the secondary display (that's the hardware primary display, i.e. the laptop screen)
If previously maximized in the primary screen: also goes to the secondary screen. 
If previously windowed and **not** maximized: sometimes opens in the correct display, sometimes not. 

### Operating system

Debian Bookworm

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Are you using Wayland? It's possible that your compositor just ignores the screen Qt passes to set_fullscreen, I don't think we can do something about this then, you have to ask GNOME devs to support this (though since you're using Debian I recommend to go to Debian bugtracker first, maybe this was implemented long time ago and it's just Debian has a very old version and needs to do a backport of the patch).

When you have the viewer windowed, the compositor likely just remembers the screen where you moved the window to.

**Comment by ilya-fedin** [comment]
@prppedro if you have turned the viewer into windowed mode since Telegram launch, it will use the last position/size (even after toggling back into fullscreen mode), not the main window's screen.

**Comment by prppedro** [comment]
> Are you using Wayland? It's possible that your compositor just ignores the screen Qt passes to set_fullscreen, I don't think we can do something about this then, you have to ask GNOME devs to support this (though since you're using Debian I recommend to go to Debian bugtracker first, maybe this was implemented long time ago and it's just Debian has a very old version and needs to backport a patch).
> 
> When you have the viewer windowed, the compositor likely just remembers the screen where you moved the window to.

Hmmm... No, just plain old X.org. 

> @prppedro if you have turned the viewer into windowed mode since Telegram launch, it will use the last position/size (even after toggling back into fullscreen mode), not the main window's screen.

Indeed. But when I maximize it, it **always** goes to the other display. Also, sometimes, depending on the position the window were before closed, it also gets dragged to the other monitor.

**Comment by ilya-fedin** [comment]
Can you enable the debug mode via the `debug` cheat code, reproduce the problem and provide the log lines from the DebugLogs folder having `Viewer Pos`?

**Comment by Nguyenpham89** [comment]
ĐLet me go back and see it, but now too much is it?

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: ilya-fedin ***@***.***>
Đã gửi: Thursday, April 13, 2023 12:54:08 AM
Đến: telegramdesktop/tdesktop ***@***.***>
Cc: Subscribed ***@***.***>
Chủ đề: Re: [telegramdesktop/tdesktop] Media Viewer opens in the wrong display (Issue #26157)


Can you enable the debug mode via the debug cheat code, reproduce the problem and provide the log lines from the DebugLogs folder having Viewer Pos?

**Comment by ilya-fedin** [comment]
oops, the message about turning between modes was actually for @lynrayy. Behavior he sees is intended.

**Comment by Nguyenpham89** [comment]
Is that so. Dying father . Repair is done

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: ilya-fedin ***@***.***>
Đã gửi: Thursday, April 13, 2023 1:01:11 AM
Đến: telegramdesktop/tdesktop ***@***.***>
Cc: Nguyên ***@***.***>; Comment ***@***.***>
Chủ đề: Re: [telegramdesktop/tdesktop] Media Viewer opens in the wrong display (Issue #26157)


Oops, the message about turning between modes was actually for @lynrayy<https://github.com/lynrayy>. Behavior he sees is intended.

**Comment by prppedro** [comment]
Hey, @ilya-fedin, sorry for the delay. 

I tried several operations on Viewer (opening, closing, maximizing, changing screen etc.) during that log session. 

[telegram_viewer.log](https://github.com/telegramdesktop/tdesktop/files/11325893/telegram_viewer.log)

**Comment by ilya-fedin** [comment]
I see mixes of maximized [FALSE] and maximized [TRUE] in the log. Is this a log where the window is maximized since launch and never was in windowed mode (as I mentioned previously, it won't follow the main window but will use last saved position if it was in windows mode at least once during the run time and that's intended)?

**Comment by prppedro** [comment]
> I see mixes of maximized [FALSE] and maximized [TRUE] in the log. Is this a log where the window is maximized since launch and never was in windowed mode (as I mentioned previously, it won't follow the main window but will use last saved position if it was in windows mode at least once during the run time and that's intended)?

Yes. I was maximized some times, but it was windows from the boot. Sometimes, even when the screen is on the “correct” display, it re-opens in the wrong one, depending on which position it was before being closed. It's weird. There's also a occasional bug in which only about a quarter of the window is drawn and the rest is only a shadow. But I'll open a dedicated issue for that eventually.

**Comment by ilya-fedin** [comment]
> telegram_viewer_after_restart.log

Have you opened the viewer a lot of times? If not, I assume there's a loop of fight between Telegram and GNOME: Telegram attempts to move itself to the right screen, GNOME forcefully moves it back to where it wants Telegram to be, Telegram attempts to move itself again and GNOME as well... endlessly. And I don't think we can do anything then, Telegram already attempts all it can: tries to move itself again, again and again. But GNOME reverts it back each time.

**Comment by prppedro** [comment]
> > telegram_viewer_after_restart.log
> 
> Have you opened the viewer a lot of times? If not, I assume there's a loop of fight between Telegram and GNOME: Telegram attempts to move itself to the right screen, GNOME forcefully moves it back to where it wants Telegram to be, Telegram attempts to move itself again and then GNOME as well... endlessly. And I don't think we can do anything then, Telegram already attempts all it can: tries to move itself again, again and again. But GNOME reverts it back each time.

Only one click. That's all. As timestamps show, that happened in a veeeeery short time frame. Thus, I'm guessing you're right, maybe the window manager is the real culprit. I have to test, however.

**Comment by prppedro** [comment]
Just confirmed XFWM4 doesn't display the same behaviour. Seems to be a problem between Telegram and Marco. I'll keep using XFWM4. Not a very good solution, but not a Telegram issue either, so I'm considering that issue closed.
