### ISSUE TITLE
'Use system window frame' option is missing

### ISSUE THREAD

**Issue by b-kamalov-diginavis** [telegramdesktop/tdesktop#26153]
### Steps to reproduce

Open advanced settings

### Expected behaviour

'Use system window frame' option is there

### Actual behaviour

'Use system window frame' option is missing

### Operating system

Fedora Linux 37 (Workstation Edition), Wayland

### Version of Telegram Desktop

4.7.1 (previous versions also had this issue)

### Installation source

Flatpak

**Comment by b-kamalov-diginavis** [comment]
The main reason I miss this is that default titlebar is too tiny and do not sharp the corners in fullsreen mode. Option to fix the default titlebar is also acceptable. Thank you!

![Снимок экрана от 2023-04-10 11-00-01](https://user-images.githubusercontent.com/84175904/230885444-dcc5db6b-45c9-4091-aca7-9fdb1d9afe41.png)

![Снимок экрана от 2023-04-10 11-04-09](https://user-images.githubusercontent.com/84175904/230885456-fafbd513-fbdb-4326-81fb-7ee482aacad1.png)

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by b-kamalov-diginavis** [comment]
> plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

You mean AppImage? Same thing here

![Снимок экрана от 2023-04-10 13-55-28](https://user-images.githubusercontent.com/84175904/230888940-53190a31-9cff-467f-add6-818c11d01c1f.png)

**Comment by ilya-fedin** [comment]
If it's missing it means your system doesn't provide a system window frame. E.g. GNOME is [known](https://gitlab.gnome.org/GNOME/mutter/-/issues/217) to not to provide it.

**Comment by ilya-fedin** [comment]
You can send mockups for the titlebar to https://t.me/designers. If the state designers will like it, it will be implemented.

**Comment by b-kamalov-diginavis** [comment]
So sad :( Thank you for the advise, I will try to push the idea of larger titlebar to that chat

**Comment by ilya-fedin** [comment]
It's a channel, not a chat.

**Comment by anibyl** [comment]
It used to work with Gnome, my Telegram (static version) had a system window frame. After an update this spring, it broke withing the same Gnome session. I am convinced that this is a Telegram Desktop issue.
