### ISSUE TITLE
WebView can not get clipboard data on Ubuntu

### ISSUE THREAD

**Issue by k-dovan** [telegramdesktop/tdesktop#26150]
### Steps to reproduce

1. Use Durger King Bot 
2. Order somethings to eat
3. Try copy and paste some prepared texts to `Add Comment` section but nothing happened. (I can do it on Windows, but Ubuntu).

### Expected behaviour

The text copied to system clipboard should be able to be pasted to `Add Comment` text field of Durger King app.****

### Actual behaviour

The Durger King webview can not get the system clipboard and paste to the `Add Comment` text field.

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.7.1

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Yes, sadly it's QtWaylandCompositor's restriction, I've filed a [request](https://bugreports.qt.io/browse/QTBUG-105589) sometime ago, but it seems to be ignored...

**Comment by k-dovan** [comment]
@ilya-fedin It might not related to this, but I wonder if Qt Webview faces the same issue regarding clipboard things back and forth. Thanks,

**Comment by ilya-fedin** [comment]
No, it doesn't, but I don't think there's any sense in using Qt WebView, it's better to use Qt WebEngine as it could be used in widget applications like tdesktop while Qt WebView is just a high-level QML wrapper around Qt WebEngine, but anyway, we can't use Qt WebEngine as that would mean:
1. We can't use Qt WebEngine from system while having other parts of Qt bundled, so we have to provide entire Chromium with the executable what means huge increase of bundle (it won't be a single binary anymore) size.
2. Impossibility to provide static binary, it will become a binary and a lot of Qt files in the directory as Chromium has its own executable for content renderer and both binaries have to share the same libraries.

Those two are big blockers for using Qt WebEngine.

**Comment by k-dovan** [comment]
Thanks for your info! It's much clearer to me know.
