### ISSUE TITLE
Telegram Desktop is oversaturated on macOs Ventura

### ISSUE THREAD

**Issue by kulakdev** [telegramdesktop/tdesktop#26166]
### Steps to reproduce

I'm using M2 Mac Mini

Issue starts on program start-up, persists through re-launches, re-installations 

### Expected behaviour

![Screenshot 2023-04-12 at 10 54 57](https://user-images.githubusercontent.com/57463058/231390664-8d45d25f-b2fe-43d8-a58c-6c1cf6652f31.png)
Example of how saturated screenshot is in Finder
![Screenshot 2023-04-12 at 10 55 33](https://user-images.githubusercontent.com/57463058/231390801-9e4c882c-7fd7-49b8-8748-bfa2692357af.png)
Example of how saturated screenshot is in Discord (same as Finder basically)

### Actual behaviour

![Screenshot 2023-04-12 at 10 56 03](https://user-images.githubusercontent.com/57463058/231390916-10a1b566-0404-4685-8a10-96afbe549d40.png)
Example of how it looks in Telegram

### Operating system

macOs Ventura 13.2.1 (22D68)

### Version of Telegram Desktop

Version 4.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Qt's color space handling is very bad, unfortunately. There's actually two reasons of why this might happen:
1. The image have ICC profile which Qt can't read. tdesktop has a Qt patch I wrote for it to use lcms, but lcms is built only on Linux atm, someone has to add it to Windows and macOS. cc @23rd 
2. The display is not of sRGB color space while Qt draws everything in sRGB while not setting this by default as the conversion is expensive for raster-based surfaces (they had this by default in early 5.x, but then reverted). But tdesktop opts into compositing raster-drawn widgets with OpenGL, so opting into color space conversion might have sense. I don't know whether any of tdesktop developers have such displays and can test this, so if you build tdesktop with `format.setColorSpace(QSurfaceFormat::sRGBColorSpace);` [here](https://github.com/desktop-app/lib_ui/blob/93957145376d0b7c91ec22f28f9e0b29c527afac/ui/rp_widget.cpp#L49) and confirm this works, this may be solved way more quickly.

**Comment by Nguyenpham89** [comment]
Them vào thôi hihi

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: ilya-fedin ***@***.***>
Đã gửi: Wednesday, April 12, 2023 6:14:28 PM
Đến: telegramdesktop/tdesktop ***@***.***>
Cc: Subscribed ***@***.***>
Chủ đề: Re: [telegramdesktop/tdesktop] Telegram Desktop is oversaturated on macOs Ventura (Issue #26166)


Qt's color space handling is very bad, unfortunately. There's actually two reasons of why this might happen:

  1.  The image have ICC profile which Qt can't read. tdesktop has a Qt patch I wrote for it to use lcms, but lcms is built only on Linux atm, someone has to add it to Windows and macOS. cc @23rd<https://github.com/23rd>
  2.  The display is not of sRGB color space while Qt draws everything in sRGB while not setting this by default as the conversion is expensive for raster-based surfaces (they had this by default in early 5.x, but then reverted). But tdesktop opts into compositing raster-drawn widgets with OpenGL, so opting into color space conversion might have sense. I don't know whether any of tdesktop developers have such displays and can test this, so if you build tdesktop with format.setColorSpace(QSurfaceFormat::sRGBColorSpace); here<https://github.com/desktop-app/lib_ui/blob/93957145376d0b7c91ec22f28f9e0b29c527afac/ui/rp_widget.cpp#L49> and confirm this works, this may be solved way more quickly.

**Comment by kulakdev** [comment]
> 2. The display is not of sRGB color space but Qt draws everything in sRGB while not telling about this to the system by default ...

The display i'm using is Dell Ultrasharp, and i am using sRGB profile inside, so aside from that it's been quite accurate so far? Not sure i can build tdesktop to help you with that （。-＿-。）sorry ...

**Comment by ilya-fedin** [comment]
Is this a problem with any image or with a concrete image?

Note that it's unlikely to be a priority, so you can wait years for some who responsible for macOS to look at your issue or maybe your issue will always be of so little priority that it never happens to be on top of queue and never fixed. While if you will help in fixing this, you can get fix in days.

**Comment by kulakdev** [comment]
It's a problem with the whole window including UI elements, background image and all the content inside. This also affects images, and videos that are being opened in full screen view thingy.

If you can provide me some help on how to build it then i'll gladly cooperate, i don't have any experience with that at the moment.

**Comment by ilya-fedin** [comment]
You can find build instructions at the end of the repo's readme. You can first try to build unmodified sources, then if you succeed go to `Telegram/lib_ui` from the root of the repo and execute `git cherry-pick 93957145376d0b7c91ec22f28f9e0b29c527afac`. This will cherry-pick the commit the adds QSurfaceFormat configuration, so you can easy add the line to it in `Telegram/lib_ui/ui/rp_widget.cpp`, right after the `format.setSwapInterval(0);` line. Then build again and test the changes.

**Comment by kulakdev** [comment]
I'm having issues with building
![Screenshot 2023-04-13 at 14 55 20](https://user-images.githubusercontent.com/57463058/231752301-24122003-ce3f-404a-b716-73dbdea7468e.png)

What i tried : 
1) Installing Qt from here : https://www.qt.io/free-trial
2) Running `brew install qt@5` and then running `echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> ~/.zshrc`
3)Adding 
```
find_package(QT NAMES Qt6 Qt5 COMPONENTS Widgets REQUIRED)

set(CMAKE_PREFIX_PATH "/Users/USERNAME/Qt/6.5.0/macos/lib/cmake")
```
to CMakeLists.txt

**Comment by ilya-fedin** [comment]
Have you launched the `prepare/mac.sh` script according to the instruction? Has it succeed?

**Comment by kulakdev** [comment]
It failed 
![Screenshot 2023-04-13 at 15 51 16](https://user-images.githubusercontent.com/57463058/231764052-e60d7b09-3643-40b7-b8d3-dbe0f8ae146f.png)

**Comment by ilya-fedin** [comment]
`brew install ninja` should help

**Comment by kulakdev** [comment]
Sorry for the delay. 
![Screenshot 2023-04-17 at 14 23 36](https://user-images.githubusercontent.com/57463058/232470651-0f02e107-3ce4-4b67-9ec3-8e7c8443bdc1.png)
Build fails, here are the logs ˆˆˆ

**Comment by ilya-fedin** [comment]
Looks like other people getting the same error when building: #26151.

**Comment by andretagliabue** [comment]
Same issue for me, I find it very frustrating. However I'm too inexperienced to be able to compile the program by myself... I guess I have to suck it up :/

**Comment by kulakdev** [comment]
> Same issue for me, I find it very frustrating. However I'm too inexperienced to be able to compile the program by myself... I guess I have to suck it up :/

Try the one off of AppStore, the Telegram made on swift
Naturally works well cuz it's well.. made with swift

**Comment by pizzabackup** [comment]
I prefer this client for few little reasons but yes, in the meanwhile I'm moving to the swift client. I previously had troubles copying and pasting in that one, which is more frustrating than wrong color profiles, but seems to be sorted now!
