### ISSUE TITLE
Pinned messages in general forum topic are not showing up in pin bar

### ISSUE THREAD

**Issue by bakerzerecordsby** [telegramdesktop/tdesktop#26160]
### Steps to reproduce

1. Create a group
2. Send a message to this group
3. Pin this message
4. Go to the group settings and activate the "Topics" option
5. Create multiple topics in the group
6. Post a new message to the general topic
7. Pin the new message
8. Close the app and log in again

### Expected behaviour

After pinning messages, posts should be displayed in the pin bar in the top of the general topic, regardless of the transfer of the group to the forum or the restart of the application.

### Actual behaviour

After the message is pinned, the post is first shown in the top in the pin bar, and after the application is restarted, the pin bar disappears. At the same time, the pinned message icon is visible in the feed on the post itself.
The same result for other users - they do not see the pin bar with pinned messages.

### Operating system

macOS Ventura 13.2.1 (22D68)

### Version of Telegram Desktop

4.7

### Installation source

Static binary from official website

**Comment by evgeniyworkbel** [comment]
the same problem at Linux - after some period pinned message dissapears from bar, though it is visible as pinned from mobile app
