### ISSUE TITLE
Uploads on certain files gets stuck at 7.0 MB in

### ISSUE THREAD

**Issue by FN32DXer** [telegramdesktop/tdesktop#26164]
### Steps to reproduce

Upload a file, and if it starts going up by 0.8 and 0.9 mb a second, it will freeze at 7.0 MB, requiring the user to have to stop the file in order to continue uploading, which it does the same glitch over and over again.

### Expected behaviour

The files should upload per usual.

### Actual behaviour

The file goes up in intervals, from 0.8 to 1.7 to 2.6 to 3.5 to 4.3 to 5.2 to 6.1 then to 7.0 before completely freezing progress.

### Operating system

Windows 11 Home Insider Preview on a 2021 Laptop

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

**Comment by ntintis** [comment]
Got exactly the same issue for the past 5 hours with the addition that other files stuck at 7mb mark and others at 3mb mark.
Tried to reset my router, clear cache, uninstall/re-install the app all to no avail. 
windows 10 Pro Build 19045
Telegram version - Desktop 4.7.1 x64

**Comment by Nguyenpham89** [comment]
Vâng tôi kiểm tr lại

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: ntintis ***@***.***>
Đã gửi: Wednesday, April 12, 2023 9:30:45 AM
Đến: telegramdesktop/tdesktop ***@***.***>
Cc: Subscribed ***@***.***>
Chủ đề: Re: [telegramdesktop/tdesktop] Uploads on certain files gets stuck at 7.0 MB in (Issue #26164)


Got exactly the same issue for the past 5 hours with the addition that other files stuck at 7mb mark and others at 3mb mark.
Tried to reset my router, clear cache, uninstall/re-install the app all to no avail.
windows 10 Pro Build 19045
Telegram version - Desktop 4.7.1 x64

**Comment by Magnetogenerator** [comment]
same issue, i can not even upload a 3MB photo, it just stuck at 100%

**Comment by Skyraider69** [comment]
Same issue here with all the details mentioned above
Win10 pro build 19045
Telegram desktop 4.7.1 x64

**Comment by kam537** [comment]
Having the same issue recently

**Comment by Aokromes** [comment]
i think it's server issue, i have read reports with telegram android and unigram too.

**Comment by Aokromes** [comment]
it's platform wide bug it belongs to https://bugs.telegram.org/
