### ISSUE TITLE
Ability to hide forwarded messages from subscribed chats and channels

### ISSUE THREAD

**Issue by Mizari** [telegramdesktop/tdesktop#26171]
### Is your feature request related to a problem?

Feature request is not related to a problem

### Describe the solution you'd like

I would like Telegram client to hide forwarded messages from chat/channels, that I am already subscribed to.

For example: I am subscribed to channels A and B. Channel A creates new post, channel B forwards this new post to itself. I as user see duplicate post firstly in channel A and then in channel B.

### Describe alternatives you've considered

I can not come up with a real alternative to this feature. Perhaps some RSS-like chat-feed, that aggregates all new messages in one chat and removes forwarded duplicates. Folders do not really solve the problem, since the only aggregate without duplicates removing.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by Mizari** [comment]
This is neither api issue nor platform request. This is the client feature, nothing changes on backed/platform side.

**Comment by Aokromes** [comment]
ofc it's platform wide, you are requesting things involving more than own client.

**Comment by Mizari** [comment]
I think it requires only messages visibility on client side. All messages are received, they are just not showed to a user.
Continuing example: client knows, that user is subscribed to channel A and B, client chooses not to show message, that is forwarded from channel A, in channel B, since it is already showed to user in channel A. No platform changes required.
