### ISSUE TITLE
Voice notes automatically continue playing even in situations where this does not make sense

### ISSUE THREAD

**Issue by joostvhts** [telegramdesktop/tdesktop#26179]
### Steps to reproduce

1. Receive several voice messages (or send several, or any combination resulting in multiple voice messages, with or without text messages in between)
2. Press play on any of the not-most-recent ones
3. Reproduced. When the intial voice message finishes, the others are played sequentially, including the ones you sent yourself and even if there are text messages in between.

### Expected behaviour

Adhering to a user setting, the messages below do not automatically play when the initial one finishes, or they play on the condition that they are directly consecutive, or they do all play if the user so desired.

### Actual behaviour

All messages are automatically played, resulting in annoyance and confusion.

A lot of discussion has already taken place in [this](https://github.com/telegramdesktop/tdesktop/issues/3649) issue but that case was erroneously marked as resolved.

### Operating system

All

### Version of Telegram Desktop

All

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
You have chosen the wrong issue type when creating the issue: it's an API issue. The previous issue was closed due to the same reason.

**Comment by joostvhts** [comment]
> 

The previous issue shows 'resolved', not posted as wrong type. Thx, I will repost in an appropriate issue type!

**Comment by ilya-fedin** [comment]
GitHub marks all closed issues as resolved. Even this one as you can see.

**Comment by joostvhts** [comment]
For future lurkers: issue now [here](https://bugs.telegram.org/c/27250)
