### ISSUE TITLE
Ability to postpone incoming messages in chats and channels till arbitrary datetime.

### ISSUE THREAD

**Issue by Mizari** [telegramdesktop/tdesktop#26170]
### Is your feature request related to a problem?

Feature request is not related to a problem

### Describe the solution you'd like

I would like to have an option to mute chats/channels (e.g. news and memes) completely till certain time. Would be useful to select time of the day (e.g. 8 a.m.), and get all new messages at once, without worrying about them during the day and constantly checking new messages.

### Describe alternatives you've considered

Alternatives are muting and archiving chats/channels, but still it does not remove the urge to check new hidden messages.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by Mizari** [comment]
This is neither api issue nor platform request. This is the client feature, nothing changes on backed/platform side.

**Comment by Aokromes** [comment]
ofc it's platform wide, you are requesting things involving more than own client.
