### ISSUE TITLE
"Send code via SMS" is doing nothing

### ISSUE THREAD

**Issue by pboettcher** [telegramdesktop/tdesktop#26177]
### Steps to reproduce

Install new Telegram for desktop from scratch
Enter your phone number
Click on sending code via SMS

### Expected behaviour

Telegram either sends the code via SMS or does not display the link to send SMS, in order not to confuse me.

### Actual behaviour

Nothing happens. Telegram suggests to pick the code not from SMS, but from Telegram application installed on the phone.

### Operating system

Windows 7

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
not a bug,

**Comment by jotterkain** [comment]
Same here, it's not suppose to behave like that

**Comment by pboettcher** [comment]
> Same here, it's not suppose to behave like that

Seems that there is no democracy here :)

**Comment by jotterkain** [comment]
> > Same here, it's not suppose to behave like that
> 
> Seems that there is no democracy here :)

did you resolve your problem?

**Comment by pboettcher** [comment]
> > > Same here, it's not suppose to behave like that
> > 
> > 
> > Seems that there is no democracy here :)
> 
> did you resolve your problem?

no
