### ISSUE TITLE
Make context menu touch behaviour native on Linux

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#26173]
### Is your feature request related to a problem?

On a touch device with no mouse, there's no way to open the menu that is usually opened by right-clicking.

### Describe the solution you'd like

Show that same menu when touching-and-holding.

### Describe alternatives you've considered

Nothing obvious comes to mind. Usually right-click is translated as tap-and-hold for this kind of things.

### Additional context

When running with `WAYLAND_DEBUG`, I see that Telegram registers to listen to events from [`wl_touch`](https://wayland.app/protocols/wayland#wl_touch) and actually gets the `down` and `frame` events. I suspect that they're merely not being handled right now.

I believe I've heard that some compositors translate touch events into mouse events for applications that don't support touch events (I'm not sure if this particular case is translated too). But given that Telegram explicitly listens to touch events, these "magic" translations don't happen.

Note that tapping anywhere on telegram works fine; these events to the same as a single left-click.

**Comment by ilya-fedin** [comment]
You're likely encountering https://bugreports.qt.io/browse/QTBUG-73949

**Comment by ilya-fedin** [comment]
Looking at the code, I see it's already implemented
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/history/history_inner_widget.cpp#L1534

**Comment by WhyNotHugo** [comment]
> You're likely encountering https://bugreports.qt.io/browse/QTBUG-73949

Yeah, that seems to be basically the same feature request but for Qt.

> Looking at the code, I see it's already implemented

Seems to work on when long-pressing on messages, but not on the contact list.

> Note that Telegram doesn't do this, it's Qt. And while it registers to listen to events, it doesn't mean the application (or widget) in question listens to them

Right. I mostly meant to point out that, since the process itself listens to touch events, the compositor treats it as "touch-capable" and doesn't do any "touch-to-pointer" translations.

**Comment by WhyNotHugo** [comment]
Actually, it does work on the contact list, but not very reliably (I tried quite a few times more and it worked only a couple).

I think you need to hold your finger **perfectly** steady, and if it slides even a tiny bit, then no menu is shown. The menu is also shown when the touch is _released_ (rather than after a short while), so there's no indicator of when it is okay to "release" the tap, and one has to be very careful to do the motion with great care; sliding the finger even slightly sideways seems to result in no menu being shown.

**Comment by ilya-fedin** [comment]
I'm not aware about touch-to-pointer translations, you better mention that in the Qt bug report so they implement the support for them on Wayland.

**Comment by WhyNotHugo** [comment]
> I'm not aware about touch-to-pointer translations, you better mention that in the Qt bug report so they implement the support for them on Wayland.

There's nothing to implement. Basically, if a client doesn't register handle touch events (i.e.: an application is not touch-capable), `swaywm` will translate touch events into pointer events. I'm not sure about other compositors. This is basically so a tapping counts as a click on clients that don't have explicit touch support.

Because because telegram _does_ register to handle touch events, this translation isn't applied; the touch events themselves are forwarded to the application.

**Comment by WhyNotHugo** [comment]
Looks like this is implemented though, I can go ahead and close this.

> The menu is also shown when the touch is released (rather than after a short while), so there's no indicator of when it is okay to "release" the tap

Do you think this is a valid issue though? Usually menus open after holding the tap for a given amount of time, now when _releasing_ after a given amount of time.

**Comment by ilya-fedin** [comment]
I see that the dialogs have no explicit touch input support, it relies on QContextMenuEvent which on Windows being generated from native WM_CONTEXTMENU event. So it's apparently the platform issue of not having a context menu event (or Qt issue of being a bad cross-platform abstraction).

**Comment by ilya-fedin** [comment]
@Aokromes iirc you have a touch-capable device, do you see the issue on Windows?

**Comment by WhyNotHugo** [comment]
> I see that the Dialogs::InnerWidget has no explicit touch input support

Touch support is application wide. When a client binds to an object of type `WlTouch` it receives all touch events for any surface. The compositor has no understanding of "widgets" or anything at that level. Given that the above code you referenced handles `QEvent::TouchEnd`, then Qt is binding to touch events (otherwise you'd never receive this one).

> Qt issue of being a bad cross-platform abstraction

It would sound like so. From what I've seen, thi is usually the case for most issues.

**Comment by ilya-fedin** [comment]
> Touch support is application wide.

It's widget-wide in Qt. You get mouse events by default, but you can call `QWidget::setAttribute(Qt::WA_AcceptTouchEvents)` and handle touch events manually. tdesktop has some touch support, but it's not ultimate as that's not a priority (you better use some other client if you need touch support, e.g. one of the web ones). The dialog inner widget doesn't set the attribute, so Qt should provide mouch events for touch events.

> Given that the above code you referenced handles `QEvent::TouchEnd`, then Qt is binding to touch events (otherwise you'd never receive this one).

The QPA is in QtGui module while the flag is QWidget-specific, so it can't check that. I believe Qt binds unconditionally.

**Comment by Aokromes** [comment]
works for me on 4.7.1 and on chat list and on chat side.

**Comment by WhyNotHugo** [comment]
> It's widget-wide in Qt.

It's client-wide on Wayland. The compositor has no understanding of "widgets". It gets buffers and render them on-screen, but doesn't care if that buffer is a button, multiple buttons or a video.

> works for me on 4.7.1 and on chat list and on chat side.

Does the menu show up after holding for a few seconds? Or after holding for a few seconds **and** carefully lifting?

It seems to work for me but it's super flaky, since I need to hold on long enough (it's unclear when the menu will trigger), but then also lift my finger without moving it sideways at all. It's rather hard to reliably open the menu. Maybe motion can be ignored if the finger is still on the same widget?

**Comment by Aokromes** [comment]
ah, ok, it's the 2nd case, without carefully xd

**Comment by WhyNotHugo** [comment]
> The chat list is dialogs_inner_widget.cpp. It doesn't process touch, it overrides the QWidget::contextMenuEvent method and handles it.

Ah, so what you're saying is that the event itself is triggered by Qt and the enhancement I'm suggesting needs to be done on the Qt side.

**Comment by ilya-fedin** [comment]
> I wonder if `QApplication::startDragDistance` is platform-dependant

Oops, I was talking about startDragTime, startDragDistance is indeed likely to be different:
* Windows uses default QPlatformTheme value of 10px
* xcb has custom code in QXcbPlatformIntegration to use `10 * dpi / 100` (but it doesn't accept dpi less than 100)
* Wayland uses platform theme as well, tdesktop's official builds default to gtk platform theme that uses https://docs.gtk.org/gtk3/property.Settings.gtk-dnd-drag-threshold.html which maps to `/org/gnome/desktop/peripherals/mouse/drag-threshold` dconf setting which defaults to 8.

**Comment by ilya-fedin** [comment]
> The menu is also shown when the touch is _released_ (rather than after a short while), so there's no indicator of when it is okay to "release" the tap

The current behavior is native to Windows and it does indicate when it's the time to release the tap (@Aokromes has shared a video to me of how it works for him privately). This probably means the logic has to be platform-dependent, but I'm really skeptical Telegram's state developer (@john-preston) will work on this as he doesn't think there's enough touch users to spend time on touch support and then tdesktop's Linux userbase is only 1.82% so this is for really, realy small amount of users. Personally I have no touch-capable hardware and therefore interest. You can change issue title & description though like "make touch behavior native for Linux" for the issue to not to be closed.

**Comment by WhyNotHugo** [comment]
> The current behavior is native to Windows and it does indicate when it's the time to release the tap

What kind of indicator is this? This sounds like another case of Qt doing things differently between platforms, but I'm also curious what kind of queue you'd get -- I suppose it's not a vibration because that wouldn't translate well to many devices.

> You can change issue title & description though to something like "make context menu touch behavior native for Linux" for the issue to not to be closed.

I've updated the issue to reflect all the new findings. I think it's at least actionable, though not very trivial from what I can tell.

**Comment by ilya-fedin** [comment]
> What kind of indicator is this?

It's a transparent square

> This sounds like another case of Qt doing things differently between platforms,

It's not Qt, it's Windows. Well, according to the current findings Qt is not involved at all here: it just sends the touch events. All the touch handling logic is in tdesktop code.

**Comment by ilya-fedin** [comment]
> I've updated the issue to reflect all the new findings

it still says there's no way to open menu :thinking:

**Comment by ilya-fedin** [comment]
@Aokromes has allowed me to upload how it looks like
https://user-images.githubusercontent.com/17829319/232028234-a85b1c0a-517b-48e1-88b7-67503f808e5e.mp4

**Comment by ilya-fedin** [comment]
> though not very trivial from what I can tell

To make this even harder, the context menu touch handling code is duplicated multiple times in different classes, in tdesktop itself and the lib_ui submodule, so the one who would like to rewrite the touch handling to handle multiple approaches native to every platform, would have to modify a lot of places (probably unifying them all somewhere in lib_ui).

**Comment by ilya-fedin** [comment]
Maybe it's better to close the issue and create new ones for each problem: the sensitiveness problem and the unobvious behavior?

**Comment by WhyNotHugo** [comment]
Agreed. The initial question here was answered, repurposing the issue is making it incomprehensible.
