### ISSUE TITLE
Cannot narrow the chats list down to the icons width only anymore

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#26175]
### Steps to reproduce

1. Hover the boundary between the chats list and the chat history view.
2. Hold and drag to the left.

### Expected behaviour

I can collapse it to the icons width only like before.

### Actual behaviour

There's a huge minimal width.

### Operating system

Debian GNU/Linux 12

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can't confirm, it collapses just fine

**Comment by john-preston** [comment]
@bodqhrohro It collapses if a chat is open.

**Comment by bodqhrohro** [comment]
Ah, true.
