### ISSUE TITLE
[Windows] Characters in code blocks are gibberish

### ISSUE THREAD

**Issue by rixtox** [telegramdesktop/tdesktop#26181]
### Steps to reproduce

1. Send a message with code block format, e.g.:

````
```
1234567890-=
qwertyuiop[]\
asdfghjkl;'
zxcvbnm,.
/!@#$%^&*()_+
QWERTYUIOP{}|
ASDFGHJKL:"
ZXCVBNM<>?
```
````

### Expected behaviour

Characters should be displayed correctly.

### Actual behaviour

On Windows Telegram client, it got displayed like this:

![image](https://user-images.githubusercontent.com/2001277/232252111-978d5a6f-a607-4bb2-ba09-a1660c694ca0.png)

### Operating system

Windows

### Version of Telegram Desktop

4.7.1 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://i.imgur.com/beob5XT.png
cannot reproduce on windows 10 x64.

**Comment by ilya-fedin** [comment]
Try to reboot

**Comment by rixtox** [comment]
It went away after a reboot. So not always reproducible.

**Comment by ilya-fedin** [comment]
I believe something breaks in Windows with uptime and GDI starts to draw broken text with some font, I don't think there's anything that could be done at Telegram level.

**Comment by rixtox** [comment]
> I believe something breaks in Windows with uptime and GDI starts to draw broken text with some fonts, I don't think there's anything that could be done at Telegram level.

That's strange. Didn't happen in other apps. Even in telegram, only happened inside code blocks. But you are probably right about it being a Windows bug.

**Comment by ilya-fedin** [comment]
Probably not so much applications use Cascadia Mono?
