### ISSUE TITLE
Close instead of minimize on Ubuntu Gnome

### ISSUE THREAD

**Issue by antonio-petricca** [telegramdesktop/tdesktop#26189]
### Steps to reproduce

1. Run Telegram Desktop.
2. Click on the `X` icon.

### Expected behaviour

It minimizes itself.

### Actual behaviour

It closes.

### Operating system

Ubuntu 22.04.2

### Version of Telegram Desktop

Latest SNAP

### Installation source

Snap

**Comment by xahon** [comment]
I actually expect it to minimize because it's kind of "daemon" application. I think this option should be configurable for all users to make a desired behavior.
