### ISSUE TITLE
Relogin on every Telegram Desktop start

### ISSUE THREAD

**Issue by Mebus** [telegramdesktop/tdesktop#2618]
Hallo,

every time I start Telegram Desktop on the same PC, I have to enter my Phone-Number, do the PIN-Code Validation and enter the Cloud Password again. This isn't convenient. Please fix this.

My operating system is: Fedora 23 Workstation, 
My Desktop Environment is: MATE
Telegram version: 0.10.19

Thanks

Mebus

**Comment by john-preston** [comment]
@Mebus Please try the version from https://desktop.telegram.org unpacked to your home folder.

**Comment by stek29** [comment]
@Mebus and also please use search function next time: #960.
The query was `is:issue label:linux authentication`. Pretty obvious :)

**Comment by Mebus** [comment]
Lot's of text. And a problem that I have to fix manually. Will test.

Mebus
