### ISSUE TITLE
Monospaced font not working

### ISSUE THREAD

**Issue by Orest58008** [telegramdesktop/tdesktop#26184]
### Steps to reproduce

1. Use/see `monospaced` font in a message

### Expected behaviour

Font changing to `monospaced`

### Actual behaviour

Telegram instead displays sans-serif font. Everything else, like Firefox and terminal works

Monospaced section in my fonts.conf:
```
<alias>
 <family>monospace</family>
 <prefer>
  <family>CaskaydiaCove Nerd Font</family>
 </prefer>
</alias>
```

### Operating system

Arch Linux, i3-wm

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Have you tested with any other Qt application? I don't know what terminal you use, but Firefox is a gtk application and what you do may be just incompatible with Qt, Telegram can't do anything in that case (Qt's font handling is not great unfortunately).

**Comment by Orest58008** [comment]
What apps would you reccomend to test this on? I don't use Qt apps often.

**Comment by ilya-fedin** [comment]
QTerminal, Kate, Konsole

**Comment by Orest58008** [comment]
![2023-04-16_14-02-44](https://user-images.githubusercontent.com/63781175/232304061-28fb1ad4-7988-406f-99e1-04fd4c05ad01.png)

**Comment by ilya-fedin** [comment]
Are they built with Qt 6 in your distro?

**Comment by Orest58008** [comment]
No they aren't. There is qutebrowser-qt6-git though, I'll try it too once it compiles

**Comment by Orest58008** [comment]
![2023-04-16_14-16-52](https://user-images.githubusercontent.com/63781175/232305745-f08330a9-f835-4fa4-9ef5-c4d64a29c9c9.png)

Works perfectly

**Comment by ilya-fedin** [comment]
I believe it's blink (the Chromium engine) is responsible for fonts here, not Qt

**Comment by ilya-fedin** [comment]
The problem is I can't reproduce in my system with my fonts
![изображение](https://user-images.githubusercontent.com/17829319/232307161-3ca8bc76-8cda-4f8d-b683-2b08d665f7a8.png)

**Comment by Orest58008** [comment]
I have $XDG_CURRENT_DESKTOP set as "xfce", because if it isn't set, file picker doesn't work correctly. Maybe it is messing up with fonts somehow

**Comment by Orest58008** [comment]
It all just magically works now after reboot. I don't know what happened, but I'll consider this issue closed as it can be fixed with such simple methods.
