### ISSUE TITLE
No video playback speed option available on telegram desktop for linux 

### ISSUE THREAD

**Issue by AnupZN** [telegramdesktop/tdesktop#26183]
### Steps to reproduce

Play any video

### Expected behaviour

Video playback speed icon should be available while playing any video. As of this option is available in windows telegram desktop

### Actual behaviour

No video playback speed option available

### Operating system

Zorin OS 16.2 core

### Version of Telegram Desktop

4.7.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Sorry, but this function is not available in flatpak (#25126). You can get it by migrating to static binary or snap.
