### ISSUE TITLE
Incorrect Character Rendering in Telegram for Windows

### ISSUE THREAD

**Issue by bondarenkod** [telegramdesktop/tdesktop#26191]
### Steps to reproduce

Dear maintainers,

I am writing to report an issue I have encountered with the Telegram for Windows application. When attempting to send a specific Unicode character, "𓆏", in a chat, it is not rendered correctly and appears as a square instead.

Steps to reproduce the issue:

Open a chat in the Telegram for Windows application.
Type or paste the Unicode character "𓆏" into the message input field.
Observe that the character is displayed as a square:
![image](https://user-images.githubusercontent.com/3184414/233221616-d8b90b29-a3f9-4bf7-9e51-2b4ee26cf00a.png)
This issue affects the user experience as it prevents the accurate representation of certain characters in messages. I kindly request your assistance in investigating and resolving this matter.

Please let me know if additional information or clarification is required.

Thank you for your attention to this matter.

### Expected behaviour

When entering the Unicode character "𓆏" in the message input field, it should be displayed correctly, maintaining its original form and appearance.

### Actual behaviour

When entering the Unicode character "𓆏" in the message input field, it should be displayed correctly, maintaining its original form and appearance.

### Operating system

windows 10 22621.1555

### Version of Telegram Desktop

4.7.1 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I can't see the character either, even in my browser. I bet there's just no font on your (and mine) computer for that character.
![изображение](https://user-images.githubusercontent.com/17829319/233229030-e2911d5e-acf4-4f15-86e5-1664ed12f492.png)
There's nothing tdesktop can do about that

**Comment by bondarenkod** [comment]
> I can't see the character either, even in my browser. I bet there's just no font on your (and mine) computer for that character. ![изображение](https://user-images.githubusercontent.com/17829319/233229030-e2911d5e-acf4-4f15-86e5-1664ed12f492.png) There's nothing tdesktop can do about that

well, TG client can embed whatever font they want. 
in my browser (edge, windows 11) it looks like:
![image](https://user-images.githubusercontent.com/3184414/233329962-8fab7d3b-874c-412d-97ec-8d35d219f235.png)

**Comment by ilya-fedin** [comment]
> well, TG client can embed whatever font they want.

Embedding fonts for every character in Unicode is not a way, sorry, as the set of such fonts weights hunderds of megabytes if not gigabytes. So the scope is to display only what Qt can display (in a bug-less world this would mean any font installed on your system, but practically Qt's font handling code has a lot of bugs and it frequently fails to use various fonts, there's nothing reasonable (i.e. not involving a full rewrite to another toolkit) tdesktop can do about).

**Comment by bondarenkod** [comment]
> > well, TG client can embed whatever font they want.
> 
> Embedding fonts for every character in Unicode is not a way, sorry, as the set of such fonts weights hunderds of megabytes if not gigabytes. So the scope is to display only what Qt can display (in a bug-less world this would mean any font installed on your system, but practically Qt's font handling code has a lot of bugs and it frequently fails to use various fonts, there's nothing reasonable (i.e. not involving a full rewrite to another toolkit) tdesktop can do about).

I'm sorry, I don't know many details, but my windows OS, even built-in notepad can handle the next character: 
![image](https://user-images.githubusercontent.com/3184414/233351599-8f5c6878-f83a-45be-bab5-de4b7f8013df.png)
That issue can be resolved, I believe, by adding one or two fonts that support such characters or adding a possibility to change the font in the TG client settings. 
PS even this: 
![image](https://user-images.githubusercontent.com/3184414/233352017-6b337a99-9a7b-46cc-8f87-bfe492364712.png)
or this:
![image](https://user-images.githubusercontent.com/3184414/233352136-e63d8a69-15d5-4230-afbb-69d90967291c.png)

**Comment by ilya-fedin** [comment]
No, sorry adding fonts for every Unicode character is not an option as I already said. For changing the font there's #90, it could be a workaround, but one shouldn't change the font to get a character to be displayed. The actual problem here is Qt's bad font fallback handling and there's nothing we can do about that, that's just something we have to live with.

**Comment by ilya-fedin** [comment]
If displaying this character is a concern for you, there's sadly no other option than migrating to other client not using Qt like Unigram or web clients. This is something unlikely to be ever fixed.

**Comment by bondarenkod** [comment]
Well, even in alt-tab windows previews this character is rendered correctly. 
From the TG application. Because it cannot push its font in there.
![image](https://user-images.githubusercontent.com/3184414/233382782-c26e3e81-9ac7-4c06-a4d2-2954a89a6548.png)

**Comment by ilya-fedin** [comment]
Because it's rendered not by Qt but by Windows
