### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by daiman444** [telegramdesktop/tdesktop#26194]
### Is your feature request related to a problem?

Greetings. The problem is this: in the upper right corner of the dialog, under the "minimize", "full screen", "close" buttons, there are action buttons in the dialog. So, for example, the button "minimize" and "voice call" does not literally share even 1 pixel, and often instead of "collapse" "voice call" is pressed and vice versa.
As you can see from the screenshot, the cursor is already hovering over the "minimize" button, but for some reason the "voice call" button is active

Telegram Desktop Version 4.7.1

![telegram](https://user-images.githubusercontent.com/24240306/233443962-ed4753c4-b059-4ad3-b7c8-b9b7e2cbc559.png)

### Describe the solution you'd like

Move buttons or insert a separator between them

### Describe alternatives you've considered

I don't have any

**Comment by ilya-fedin** [comment]
#24111
