### ISSUE TITLE
Allow running Telegram Desktop on background if there is no AppIndicator support available

### ISSUE THREAD

**Issue by AsciiWolf** [telegramdesktop/tdesktop#26197]
### Is your feature request related to a problem?

On Linux systems without an AppIndicator / KStatusNotifierItem support (for example Fedora Workstation), Telegram Desktop seems to always quit when its main window is closed. Enabling the "Show tray icon" option in Telegram Desktop Advanced Settings results in the main Telegram Desktop window reopening every time it is closed.

Please, consider adding a better approach for these systems. At least in the Flatpak version of Telegram Desktop (there is a new [background portal](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Background) along with [background apps support](https://www.phoronix.com/news/GNOME-Monitor-Background-Apps) in GNOME 44).

### Describe the solution you'd like

For Flatpak version of Telegram Desktop, (there is a new [background portal](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Background) along with [background apps support](https://www.phoronix.com/news/GNOME-Monitor-Background-Apps) in GNOME 44). For non-Flatpak version, at least allow this app to run on background on systems with no AppIndicator support and opening the window for this running session on subsequent runs of Telegram Desktop.

### Describe alternatives you've considered

Other possible solution is to wait until GNOME actually has a proper AppIndicator support. This can never happen and it is not ideal to force stock GNOME users to keep their Telegram Desktop window opened all the time.

**Comment by ilya-fedin** [comment]
dup of #3830

**Comment by AsciiWolf** [comment]
Oops, sorry.

**Comment by ilya-fedin** [comment]
There's "Close to taskbar" option that lets Telegram to run in background with current bad Linux APIs.

**Comment by AsciiWolf** [comment]
Sure, however what I was talking about is support for Telegram to run on background on systems without AppIndicator / KStatusNotifierItem support (or did you mean other APIs?).

**Comment by ilya-fedin** [comment]
yes, this option lets you have Telegram running in background without those extensions at the price of always having the window in taskbar.
