### ISSUE TITLE
Font weight not rendered correctly when using variable font

### ISSUE THREAD

**Issue by kumikooumae** [telegramdesktop/tdesktop#26192]
### Steps to reproduce

I'm experiencing the same problem as https://bugzilla.redhat.com/show_bug.cgi?id=2179854 when using variable font. Please consider fixes in these two posts:
https://bugzilla.redhat.com/show_bug.cgi?id=2179854
https://bugreports.qt.io/browse/QTBUG-112136

### Expected behaviour

This is what the font should look like
![图片](https://user-images.githubusercontent.com/37971934/233302657-e9c897c6-aefc-4286-92e5-e1968670147f.png)
![图片](https://user-images.githubusercontent.com/37971934/233302857-4adee624-d535-4000-b780-dbecd7be52f2.png)

### Actual behaviour

This is what it looks like in Telegram
![图片](https://user-images.githubusercontent.com/37971934/233303090-dd9b865d-7008-4e86-ac23-1a827e0b35cb.png)
The Chinese font is using variable font, and English font is not. When using variable font, bold font weight is thicker than expected, and regular font weight is thinner than expected

### Operating system

Fedora 38 KDE 5.27.4

### Version of Telegram Desktop

4.7.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Qt has a very, very bugged font handling code and I'd like to avoid to patch it as any non-approved change is likely to add more breakages. In other words, I'd like to wait for the patch to be merged to Qt upstream first.
