### ISSUE TITLE
Box, where we typing a message has different position

### ISSUE THREAD

**Issue by magomedik** [telegramdesktop/tdesktop#26196]
### Steps to reproduce

I am not sure (could reproduce)
It happens after unlocking the phone (iOS 16.4.1, Telegram 9.5.4 official). I have unread msg and opened it from a push notification

![IMG_5407](https://user-images.githubusercontent.com/58663516/233618608-b92c0aac-8361-4429-8775-91b4c17cdc91.jpg)

### Expected behaviour

The right position should be

### Actual behaviour

Incorrect position of message box (see screen)

### Operating system

iOS

### Version of Telegram Desktop

9.5.4

### Installation source

Mac App Store

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
