### ISSUE TITLE
finall build error

### ISSUE THREAD

**Issue by mohamad62** [telegramdesktop/tdesktop#2619]
I'm Trying to compile it in Visual Studio 2015 and all steps works, but when I build the project, I get the following errors:

1>------ Build started: Project: Telegram, Configuration: Debug Win32 ------
1>  'ninja.exe' is not recognized as an internal or external command,
1>  operable program or batch file.
1>D:\TBuild\tdesktop\Telegram.vcxproj(932,5): error MSB3073: The command "call ninja.exe -C out\Debug\ -k0 Telegram" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

windows 10
visual studio 2015

**Comment by auchri** [comment]
Did you download ninja?

https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-msvc.md#setup-gypninja-and-generate-vs-solution

**Comment by mohamad62** [comment]
Yes I did and I generated VS solution by that

**Comment by auchri** [comment]
Please post the content of your console

**Comment by mohamad62** [comment]
sorry I have closed everything, is it possible to see the history? I'm sure I did all steps correctly, just got stuck in that last one

**Comment by auchri** [comment]
> is it possible to see the history?

I don't think so.
Please try again, otherwise it's impossible to help you.

**Comment by john-preston** [comment]
@mohamad62 you've generated VS solution by GYP, now you need Ninja (in your PATH) to build it.

**Comment by mohamad62** [comment]
Could you please tell how I can do that, I've already done the following command:
SET PATH=%PATH%;D:\TBuild\Libraries\gyp;D:\TBuild\Libraries\ninja;
but the problem still exists.

**Comment by john-preston** [comment]
@mohamad62 you can go to "System -> Advanced system settings -> Environment variables... -> System variables -> Path" and click Edit. I have Ninja in "C:\Projects\Chromium\depot_tools", perhaps you can just add path to your Ninja there:

![image](https://cloud.githubusercontent.com/assets/17900494/20514083/1492398c-b09b-11e6-9b88-37fb6ea45e5a.png)

**Comment by mohamad62** [comment]
Thank you 👍
