### ISSUE TITLE
Исправления интерфейса

### ISSUE THREAD

**Issue by daiman444** [telegramdesktop/tdesktop#26193]
### Is your feature request related to a problem?

Приветствую. Проблема в следующем: в верхнем правом углу диалога под кнопками "свернуть", "на весь экран", "закрыть" есть кнопки действий в диалоге. так вот, например кнопку "свернуть" и "голосовой звонок" не разделяет буквально даже 1 пиксель и часто вместо "свернуть" нажимается "голосовой звонок" и наоборот.
Как видно по скриншоту курсор уже наведен на кнопку "свернуть", но почему то активна кнопка "голосового звонка"

Telegram Desktop Version 4.7.1

![telegram](https://user-images.githubusercontent.com/24240306/233437096-e0a5a27f-f297-4138-aa31-b1b2c196f0c9.png)

### Describe the solution you'd like

Сместить кнопки или вставить между ними разделитель

### Describe alternatives you've considered

не имею таковых

**Comment by Aokromes** [comment]
this bugtracker is english only.
