### ISSUE TITLE
"spoiler style" text

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#26200]
### Steps to reproduce

1. In a channel that you are subscribed to (or in a chat that you are in, I guess), someone uses the "spoiler styling".

https://www.androidpolice.com/how-to-use-spoiler-styling-in-telegram-for-android/

### Expected behaviour

There should NEVER, under any circumstances, be an animation that keeps playing forever somewhere on the screen that you have no way to stop. That's very distracting while you are trying to read elsewhere on the screen.

If something is going to be there all the time, it should be static. If something is animated, I should have a way to stop it (e.g. by clicking on it).

### Actual behaviour

![image](https://user-images.githubusercontent.com/13969584/233745042-6dc1c146-3487-46e8-adae-d0a49a44cd7e.png)

In the list of chats on the left, the last message of every chat is shown.
Because the last message in that chat has the "spoiler styling", the text shows up obfuscated. And it is **animated**.

The issue is, there is no way to make that thing stop moving.

I click on the chat. The contents of the chat show up on the right.
There I can see the full message, all obfuscated, with the animation.

So now I have two animations:  the one on the right in the actual message in the chat, and the one on the left in the message preview in the list of chats.

Now I click on the obfuscated message on the right. This reveals the text, so the animation on the right disappears.

But the preview animation on the left is still moving! Note that it's also quite stupid that the text in the preview on the left hasn't been revealed at the same time the full message was revealed on the right. But this is the least important issue.

Now I close the chat, and go to another chat. At this point, if the message preview on the left in the chat list had been revealed, I would expect it to return to its obfuscated state. Given that it was never revealed in the first place, it's still obfuscated.

But the problem anyway is that the animation is still moving.

I am now reading an unrelated chat, and this thing on the left never stops moving, and I have no way to stop it. It's absolutely outrageous.

Note that **on the Android app, the effect is entirely static**. There is no animation whatsoever, not even in the full message when you open the chat (which is stupid, because it looks uninteresting, but at least it's not annoying).

### Operating system

Manjaro Linux

### Version of Telegram Desktop

4.7.1

### Installation source

manjaro package

**Comment by ilya-fedin** [comment]
You can disable animations in battery saving settings.

**Comment by php4fan** [comment]
I don't know why you set this to "waiting for an answer".

Anyway, it's great that there is a workaround, which is good enough for me (given that I don't give a **** about the animation), but the behavior is still wrong. And one shouldn't have to waste time looking for settings to disable delirious annoying behavior.

An animation that keeps playing forever is not acceptable. If I need to go to settings and disable it, then it is pointless: its only function is to annoy me.

If the choice is between the animation always playing all the time and never stopping ever under any circumstances (as long as the message with the spoiler is the last one in a given chat), or no animation at all, then the only sensible option is no animation at all. So that should be at least the default. But then, having a setting to turn the animation on would be quite pointless, because who goes to look for it in the settings? (and t hen again, when they do enable it only to find out that it then never stops, they'll be disappointed). So, that's ridiculous: if that is the choice, then just remove the animation altogether.

Now, let's assume that the animation has some value, i.e. it looks cool, it makes the user experience more fun, etc, and therefore it makes sense to have an animation and it's worth it.
In that case, it has to be bearable. That is, it has to stop at some point (if it starts on its own) and/or be stoppable e.g. by clicking on it (if the user has initiated it).

In a well-designed application that is used for anything serious, no animation plays indefinitely. Animated emojis usually play once or a finite number of times; then maybe they play again on roll-over or when clicked. Animated GIFs either do the same or they are initially paused and they only start playing when clicked, and then either stop when finished or can be stopped by clicking again. There are a number of sensible designs possible. Having the animation playing all the time forever with no possibility to stop it other than looking for a setting (not even something that you can discover by right-clicking on the thing that is annoying you) is not one of them.

**Comment by VadimVadimVadim1337** [comment]
I know that they stole it from the messenger in ios, it was the same there.

**Comment by Aokromes** [comment]
then clearly not a bug.

**Comment by php4fan** [comment]
> then clearly not a bug.

What???

**Comment by ilya-fedin** [comment]
> Can you explain the reasoning?

The designers want your battery to be drained, that's intended

**Comment by php4fan** [comment]
> The designers want your battery to be drained, that's intended

I guess you're trying to be sarcastic but I don't get why the issue was closed. Is it because the iOS version of the app (assuming that's true) has the same bug? If the iOS version crashes, will you try to replicate the crash on desktop? Or do you assume that if the iOS version of the app has a certain behavior, that must be the result of a thoughtful decision process and it must be considered as specification? Because I'm pretty sure (again assuming the issue really exists on iOS) they have simply overlooked it and either haven't realized or have had more important things to fix and improve so far. Either that or they are complete idiots, but the latter seems very unlikely.

By the way I strongly doubt this makes any significant difference in battery usage. The important thing is it's a usability issue: an animation that is constantly moving is distracting AF.

**Comment by ilya-fedin** [comment]
The designers provide the mockups with the intended behavior to developers. It has no sense to have an issue about UI behavior given that the developers have no right to alter them, it will just hang there forever. As this issue tracker is a community one, there's no chance Telegram designers will see this.

**Comment by php4fan** [comment]
And in the mockups, they specifically wrote that the animation has to play forever, with no way for the user to stop it?

**Comment by php4fan** [comment]
By the way, just realized: the iOS mobile version is not even comparable. Even if the animation continued playing forever in the chat list, it wouldn't be the same as in desktop, because on mobile, the chat list and the chat contents are separate screens. When you are interacting within a chat, the chat list is not there. On desktop, on the other hand, the chat list and the current chat are side by side.

So it doesn't even make sense to say that the behavior is the same on mobile. It's not comparable. On desktop the issue is that the animation keeps playing in the chat list on the left even while you have a chat open (regardless of whether it's the same chat where the spoiler-ed message is or not). On mobile, having the chatlist visible while one chat is open is not a thing.

It would still be questionable if, on mobile, the animation keeps playing forever in the chat list, but it's not unreasonable. The chat list is not something you interact with for a long time. And if you do, you most likely scroll and the animation goes out of the screen sooner than later.
