### ISSUE TITLE
Interface looks pixelated on Windows 11 2K monitor on versions after 4.5.3 

### ISSUE THREAD

**Issue by pedorich-n** [telegramdesktop/tdesktop#26203]
### Steps to reproduce

1. Open Telegram
2. See the pixelated interface

I have a laptop with 2K screen (2560x1600) with Windows scaling set to 150%. 

On versions of Telegram up to 4.5.3, I used to have the interface scale set to 200%. 
Starting from 4.6.0 interface scaling shows me weird numbers, like the default scale is 153%, next values are 162%, 170%, 179%, 187%... all the way up to 510%.
On any of those values, all the icons, emojis, avatars, and some of the fonts look like they're zoomed in.
I am attaching some screenshots of 4.5.3 (scaling set to 250%) and 4.8.0 (scaling set to 255%), side by side.

<details>
  <summary>Screenshots</summary>

(Click to see full-size)
![context_both](https://user-images.githubusercontent.com/15573098/233781395-93087a87-d404-42a8-aac8-7082e7cd6228.png)

---

![emoji_both](https://user-images.githubusercontent.com/15573098/233780560-7775a01d-c5da-4785-8b73-10d5b37d4b04.png)

---

![avatars_both](https://user-images.githubusercontent.com/15573098/233780556-4e665228-81bb-4c31-a8e7-afd7846dcd2f.png)

---

![settings_both_250](https://user-images.githubusercontent.com/15573098/233780554-dacbab2e-d09a-44d7-ac3c-f3cef7684ea5.png)
</details>

<details>
  <summary>Also a video showing "weird" scaling options available:</summary>

https://user-images.githubusercontent.com/15573098/233781124-971b50a9-b49d-4802-90ad-8efadb5acabe.mp4
</details>

Logs:
[4.5.3.txt](https://github.com/telegramdesktop/tdesktop/files/11301193/4.5.3.txt)
[4.8.0.txt](https://github.com/telegramdesktop/tdesktop/files/11301194/4.8.0.txt)

I saw a similar issue: https://github.com/telegramdesktop/tdesktop/issues/25856, but it was closed without a resolution, and I'm not entirely sure I'm facing the same problem.

Let me know if you need any other debug information.
Thanks!

### Expected behaviour

Crisp interface

### Actual behaviour

Pixelated interface

### Operating system

Windows 11 Home 22H2 22621.1413

### Version of Telegram Desktop

4.6.0, 4.7.0, 4.8.0

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
The log says you have these Qt variables set in your system, they override Qt behavior.
```
[2023.04.22 19:39:43] QT_AUTO_SCREEN_SCALE_FACTOR: 0
[2023.04.22 19:39:43] QT_SCREEN_SCALE_FACTORS: 1.7
```
Please remove them.

**Comment by pedorich-n** [comment]
You are right! I don't how these variables got set.
But removing them didn't help. Looks exactly the same.

Here are the logs without them:
[log.txt](https://github.com/telegramdesktop/tdesktop/files/11301471/log.txt)

**Comment by ilya-fedin** [comment]
Try to reset experimental settings

**Comment by pedorich-n** [comment]
How do I do that? I don't see anything in the "Advanced" settings 🤔

**Comment by ilya-fedin** [comment]
The experimental settings item is in the update section that is either on top or bottom of advanced settings. You should have updates enabled to have access to the settings.

**Comment by pedorich-n** [comment]
Right, I had updates disabled.

Resetting the experimental settings helped! It looks crisp now, and the scaling options now have a step of 5%.
So the 1.7 scale factor from QT env was influencing everything.

Thank you!
