### ISSUE TITLE
Bot disappears from all folders after clearing history

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#26209]
### Steps to reproduce

1. Pin bot in any folder.
2. Clear history with bot.
3. Restart client.
4. Bot will disappear from ALL folders, even from those where bot is pinned.

### Expected behaviour

Bot should not disappear from all folders after clearing history.

### Actual behaviour

Bot is disappearing from all folders after clearing history.

### Operating system

Windows 11 Pro

### Version of Telegram Desktop

4.8.0

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
It's serverside issue
https://bugs.telegram.org/c/10680
