### ISSUE TITLE
Group which exceeds about 50 members will not trigger participant update and not send the system message when someone leave the group, but the join event is ok

### ISSUE THREAD

**Issue by ILG2021** [telegramdesktop/tdesktop#26201]
### Steps to reproduce

1. join a group which exceeds 100 members
2. leave the group

### Expected behaviour

There is a system message tells that the member leave and clients should receive participant change update 

### Actual behaviour

no message, no update

### Operating system

windows, but I have tried on android, I think it is a server bug

### Version of Telegram Desktop

4.8

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@ILG2021 The server is in charge of those service messages, the TDesktop app can’t do anything about that. Also I guess this is intended. You can suggest some other behaviour on https://suggestions.telegram.org
