### ISSUE TITLE
QR Reader in the mobile version

### ISSUE THREAD

**Issue by numeropi** [telegramdesktop/tdesktop#26213]
### Is your feature request related to a problem?

Current App doesn't have support for a QR reader for bots... forcing bots to ask for photo images and process them online to detect QR...

### Describe the solution you'd like

As a bot developer, i'd love to have a Barcode or QR scanner function (like most browsers app) so that we can have interact better with the real world of logistics. 

### Describe alternatives you've considered

Currently the bot is showing links to other .apks or apps that can do that but then the experience to interact with telegram gets interrupted anytime I have to scan for a qr and I have to open other app.

**Comment by ilya-fedin** [comment]
This is a issue tracker of tdesktop. If you report not for Telegram Desktop but for some other client, please use "Issue of other client" when creating issue. If your issue belongs to multiple clients, please use "API issue" type.

**Comment by numeropi** [comment]
It can be closed, I found it here: https://bugs.telegram.org/c/2909

thanks
