### ISSUE TITLE
Incorrect «chat_type» and «chat_instance» parameter passing to Web App

### ISSUE THREAD

**Issue by ershovdev** [telegramdesktop/tdesktop#26212]
### Steps to reproduce

The problem of reproducing is that you will need the created Bot and Web App along with any hosted web page with https

1. Create a link to the Web App - `t.me/{{bot_username}}/{{web_app_name}}` and send it to any private group chat
2. Click on the link, the Web App opens, but the `chat_type` and `chat_instance` parameters contained in `window.Telegram.WebApp.initData` and `window.Telegram.WebApp.initDataUnsafe` are incorrect:

- `chat_type=sender`, although according to the documentation - it should be `chat_type=group`
- `chat_instance` looks correct at first glance, but there is a problem: if you try to do all the same steps for any other private group chat, then `chat_instance` should be different, but it is exactly the same. I can assume, that it's not really private group identifier, but exact user clicked the link identifier.

### Expected behaviour

`window.Telegram.WebApp.initData` and `window.Telegram.WebApp.initDataUnsafe` after opening Web App in private group chat contains correct values:
- `chat_type=group`
- `chat_instance={{private_group_identitfer}}` 

### Actual behaviour

`window.Telegram.WebApp.initData` and `window.Telegram.WebApp.initDataUnsafe` after opening Web App in private group chat contains incorrect values:
- `chat_type=sender`
- `chat_instance={{user_identitfer}}` (unverified information)

### Operating system

macOS 12.2 (21D49)

### Version of Telegram Desktop

9.6.1.245681

### Installation source

Mac App Store

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
