### ISSUE TITLE
Can't make call to account that is also logged into the same tdesktop instance.

### ISSUE THREAD

**Issue by danog** [telegramdesktop/tdesktop#26214]
### Steps to reproduce

1. Log into two accounts A and B using the same tdesktop instance
2. Call account B from account A

### Expected behaviour

The call should start ringing, until B eventually answers from another another device.

### Actual behaviour

B is marked as "busy" and the call is terminated immediately.
This doesn't happen for example on Telegram Android.

### Operating system

Arch linux

### Version of Telegram Desktop

4.8

### Installation source

Static binary from official website

**Comment by kinoher** [comment]
it's not bug  it is defined behavior. 
Please disable receive call   on b account

**Comment by danog** [comment]
But it doesn't match the Android behavior, and either way it's a bit annoying, would love for this limitation to be removed!
