### ISSUE TITLE
clicking on a notification brings up the search box and takes focus from the chat window

### ISSUE THREAD

**Issue by insok1** [telegramdesktop/tdesktop#26223]
### Steps to reproduce

1. click on a notification (it doesn't happen 100% of the time)

### Expected behaviour

focus should be on the "write a message.." input box

### Actual behaviour

search box opens up and waits for input

this was also happening in 4.8 and #25285

### Operating system

win 10

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by VasiliyMooduckovich** [comment]
can confirm, same here after recent update, really annoying

**Comment by BoffinBrain** [comment]
Same here. Definitely a regression from the previous version.

**Comment by VasiliyMooduckovich** [comment]
screw this, im rolling back to version 4.8.0 ( btw, don't forget to disable automatic update)

**Comment by john-preston** [comment]
I can't reproduce that.

1. What type of chat the message comes to when this happens? Private, legacy group, supergroup?
2. What window layout is used? Single column, two column, three column?
3. What notifications are used? Default custom TDesktop notifications (white with blur REPLY button in default theme) or native Windows notifications?

@VasiliyMooduckovich @BoffinBrain @insok1

**Comment by insok1** [comment]
i see the issue is closed now, but i will reply just in case (since i can't test the changes yet).

1. any notification that comes from a chat that isn't the current one does this. (private/supergroup)
2. i'm not sure where i can see that, i checked the settings but i don't see anything relevant
3. the default ones (non native)

**Comment by john-preston** [comment]
@insok1 4. Do you have interface animations disabled in Battery Saving?

**Comment by insok1** [comment]
@john-preston yes they are disabled although i am on a desktop, so i don't think that feature is used

**Comment by VasiliyMooduckovich** [comment]
> 1. What type of chat the message comes to when this happens? Private, legacy group, supergroup?

anything

> 2. What window layout is used? Single column, two column, three column?

single i guess

> 3. What notifications are used? Default custom TDesktop notifications (white with blur REPLY button in default theme) or native Windows notifications?

tdesktop notifications (like in-app interface notifications or whatever it called)
ps
i've recorded this behavior 

how it should be (version 4.7)
https://github.com/telegramdesktop/tdesktop/assets/73686738/a0fe3fcb-3e7c-40fe-9551-c7094c1731df

and how it is now (version 4.8+)
https://github.com/telegramdesktop/tdesktop/assets/73686738/fddbdf41-f474-4162-9589-c365ae48b2b7

> Do you have interface animations disabled in Battery Saving?

yes i have those gddanm animations disabled
