### ISSUE TITLE
Please don't overwrite *.dekstop file

### ISSUE THREAD

**Issue by rossnomann** [telegramdesktop/tdesktop#26221]
### Steps to reproduce

1. Change desktop file:

```
$ sed -i 's/Name=Telegram Desktop/Name=Telegram/' .local/share/applications/org.telegram.desktop._34da10324669d2ed552e30f5e7d02e8c.desktop
$ grep Name .local/share/applications/org.telegram.desktop._34da10324669d2ed552e30f5e7d02e8c.desktop 

Name=Telegram
Name=Quit Telegram
```

2. Run and quit telegram (maybe you need to repeat this step 2 times)

3. Changes disappeared:

```
$ grep Name .local/share/applications/org.telegram.desktop._34da10324669d2ed552e30f5e7d02e8c.desktop 

Name=Telegram Desktop
Name=Quit Telegram
```

### Expected behaviour

Telegram must not overwrite changes in .desktop file

### Actual behaviour

Telegram overwrites .desktop file so I can not change an icon or set an env var, e.g. QT_QPA_PLATFORM=xcb to fix a bug with system window frame.

### Operating system

Ubuntu 22.04.2 LTS

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
You're not supposed to change .desktop file and you're not supposed to force Xwayland. Sorry, but your envirnment creators decided you're not deserving a system window frame and you won't get. Don't like this? Switch from GNOME to something that provides it.
