### ISSUE TITLE
Linux - The button to turn off native OS notifications

### ISSUE THREAD

**Issue by AbyssMoon** [telegramdesktop/tdesktop#26222]
### Is your feature request related to a problem?

Native operating system notifications are not convenient for everyone. On Linux, I've been using notifications from telegram itself for years. With a recent update, native Gnome notifications have been used.
It is not possible to go back and disable native notifications now. I would like to have a button to return notifications to the old state when they were created by the application Telegram itself.

### Describe the solution you'd like

Button disabling native OS notifications

### Describe alternatives you've considered

An additional command line parameter at startup

**Comment by ilya-fedin** [comment]
If you don't see the button, it just means there's nothing to provide when options is disabled (e.g. you're using Wayland where non-native notifications can't be supported).
