### ISSUE TITLE
Dockerfile enhancement for Linux builds

### ISSUE THREAD

**Issue by sryze** [telegramdesktop/tdesktop#26226]
### Is your feature request related to a problem?

Yes. If a host system runs out of space during build, in particular while building Qt which requires A LOT of disk space, it can be very time consuming to restart and wait for the whole build step to run over again. 

### Describe the solution you'd like

IMO it would be better to split the long chained `RUN` commands in the Dockerfile into mulitple `RUN` commands so that previous steps do not need to be repeated again during next build attempt.

e.g.

```
RUN git clone -b {{ QT_TAG }} --depth=1 git://code.qt.io/qt/qt5.git qt_{{ QT }} \
	&& cd qt_{{ QT }} \
	&& git submodule update --init --recursive --depth=1 qtbase qtdeclarative qtwayland qtimageformats qtsvg qt5compat qtshadertools \
	&& cd qtbase \
	&& find ../../patches/qtbase_{{ QT }} -type f -print0 | sort -z | xargs -r0 git apply \
	&& cd ../qtdeclarative \
	&& sed -i '/add_subdirectory(quickcontrols2)/d' src/CMakeLists.txt \
	&& sed -i '/add_subdirectory(quickdialogs2)/d' src/CMakeLists.txt \
	&& sed -i '/add_subdirectory(quicknativestyle)/d' src/CMakeLists.txt \
	&& cd .. \
	&& ./configure -prefix "{{ QT_PREFIX }}" \
		CMAKE_BUILD_TYPE=None \
		-opensource \
		-confirm-license \
		-libproxy \
		-qt-libpng \
		-qt-harfbuzz \
		-qt-pcre \
		-no-icu \
		-no-feature-xcb-sm \
		-no-feature-egl-extension-platform-wayland \
		-no-feature-highdpiscaling \
		-static \
		-dbus-runtime \
		-openssl-linked \
		-nomake examples \
		-nomake tests \
	&& cmake --build . --parallel \
	&& DESTDIR="{{ LibrariesPath }}/qt-cache" cmake --install . \
	&& cd .. \
	&& rm -rf qt_{{ QT }}
```

### Describe alternatives you've considered

Freeing more disk space / building on an external HDD, but I can't do it at the moment / it's very time consuming

**Comment by ilya-fedin** [comment]
it was like that previously, sadly it requires WAY more space then as Docker preserves the data on each step and there's no effect from removing the build directory. I believe other steps are nothing in comparison to build step which will go from 0 every time you restart image build and there's nothing could be done about that. The only solution to this I can think of is migrating Linux build to the prepare.py routine (Dockerfile predates it), but personally I'm not interested in that.
