### ISSUE TITLE
Get freeze when try to reply to a message

### ISSUE THREAD

**Issue by trytolearn51** [telegramdesktop/tdesktop#26229]
### Steps to reproduce

After uninstall and install it many times from snap,  finally it opens on Ubuntu 
even after that it get freeze when i want to reply a message 

after kill, it will take long time to run again with high CPU usage 

### Expected behaviour

i should reply to messages

### Actual behaviour

get freeze

### Operating system

Ubuntu 23.04

### Version of Telegram Desktop

4.8.1-2-g382558671

### Installation source

Snap

**Comment by welchste** [comment]
I didn't want to open a new issue as I think my symptom is closely matched.
Updated to latest Snap package 4.8.3
After an initial interaction, (move window, send a reply) the whole app freezes. Can't move the window, can't type, can't click anywhere and get any response in the UI. 

Reverted back to 4.8.1-2-g382558671 and works fine.
My system

```
 OS: Ubuntu 23.04 lunar
 Kernel: x86_64 Linux 5.10.0-1051-oem
 Uptime: 1h 18m
 Packages: 3016
 Shell: bash 5.2.15
 Resolution: 4480x1440
 DE: GNOME 44.0
 WM: Mutter
 WM Theme: Adwaita
 GTK Theme: Yaru-blue-dark [GTK2/3]
 Icon Theme: Yaru-blue-dark
 Font: Ubuntu 11
 Disk: 135G / 233G (61%)
 CPU: 11th Gen Intel Core i5-1135G7 @ 8x 4.2GHz [41.0°C]
 GPU: Mesa Intel(R) Xe Graphics (TGL GT2)
 RAM: 9248MiB / 15723MiB
```

**Comment by trytolearn51** [comment]
I changed my kernel to 6.1  now everything works fine.
