### ISSUE TITLE
does not keep chat

### ISSUE THREAD

**Issue by Lamadros** [telegramdesktop/tdesktop#2622]
Precondition:
OS: OS X Yosemite ( 10.10.2 (14C109) ) 
telegram desktop version - 0.10.19
device: MacBook Pro (Retina, 15-inch, Mid 2014)

### Steps to reproduce
1. Run telegram desktop
2. select chat ( http://prntscr.com/d5o8p2 ) 
3. Press [x] button ( http://prntscr.com/d5o955 ) ( 
4. open app ( http://prntscr.com/d5o9me )

### Expected behaviour
will open the last used  chat  ( "Telegram" http://prntscr.com/d5ob5s ) . Look at prtscr in step 2

### Actual behaviour
opens "Please select a chat to start messaging" ( http://prntscr.com/d5oc17 )

**Comment by Lamadros** [comment]
pls add link to ticket :)

**Comment by auchri** [comment]
Use search next time: https://github.com/telegramdesktop/tdesktop/issues?utf8=%E2%9C%93&q=is%3Aissue%20tray%20chat%20is%3Aclosed%20created%3A%3E2016-10-16
