### ISSUE TITLE
broken "Tile background" 

### ISSUE THREAD

**Issue by Lamadros** [telegramdesktop/tdesktop#2623]
Precondition:
OS: OS X Yosemite ( 10.10.2 (14C109) )
telegram desktop version - 0.10.19
device: MacBook Pro (Retina, 15-inch, Mid 2014)

### Steps to reproduce
1. Run telegram desktop
2. Press Setting button on the top of desktop app
3. Select "tile background" 

### Actual behaviour
http://prntscr.com/d5oeyi

**Comment by auchri** [comment]
I think that's how "Tile background" should work.

**Comment by john-preston** [comment]
@Lamadros what do you expect from "Tile background"? It does what it supposed to do, some backgrounds are good when tiled, some are good when not.
