### ISSUE TITLE
Telegram Desktop Portable did not close properly last time it was run and will now clean up

### ISSUE THREAD

**Issue by Gennady-G** [telegramdesktop/tdesktop#26233]
### Steps to reproduce

Launch Telegram
Stop telegram by cmd and shut down PC using these commands (I'm trying to kill Telegram processes using standard and /force commands, and then shut PC down):

```
taskkill /im Telegram.exe
taskkill /im TelegramDesktopPortable.exe
timeout /t 5
taskkill /im Telegram.exe /f
taskkill /im TelegramDesktopPortable.exe /f
timeout /t 5
shutdown /s /t 0 
```

### Expected behaviour

Telegram should start normally

### Actual behaviour

It shows this error window:

![telegram-error-window-2023-04-20_135540](https://user-images.githubusercontent.com/5569346/234603764-75ba90fd-b05f-47ec-a590-fa966c3e28aa.png)

and then after click ["Ok"] we need to re-launch Telegram again.

This bug does not always reproduce, sometimes it starts normally.

I found old thread from 2013 year with this problem - do I understand right that this problem could not be fixed? 
https://portableapps.com/node/28953

If I replace portable version with the official application from here ( https://github.com/telegramdesktop/tdesktop/releases ) - would it stop crashing?

Best regards, Gennady

### Operating system

Windows Server 2019 

### Version of Telegram Desktop

v4.8.1 24.04.23 (PortableApps portable version)

### Installation source

Other (unofficial) source

**Comment by Gennady-G** [comment]
@ilya-fedin Ok thank You!

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/wiki/Command-Line-Switches why no simply /quit?

**Comment by Gennady-G** [comment]
> https://github.com/telegramdesktop/tdesktop/wiki/Command-Line-Switches why no simply /quit?

For me this command

`D:\programs\TelegramDesktopPortable\TelegramDesktopPortable.exe /quit`

just starts another instance of telegram..

![quit-2023-04-27_142216](https://user-images.githubusercontent.com/5569346/234844950-a108d53b-58bd-4a54-893e-a8a78b2c68ce.png)


Existing instance still works and visible in tray:

![existing 2023-04-27_151126](https://user-images.githubusercontent.com/5569346/234845116-e3b08f5e-fbe7-4767-98f5-522dd1c92359.png)

or not sure where to use this flag..

**Comment by Gennady-G** [comment]
Thank You much @Aokromes! Looks like it closes correctly now! :)
