### ISSUE TITLE
Keyboard friendliness fully BROKEN on new update

### ISSUE THREAD

**Issue by abrahamadamu** [telegramdesktop/tdesktop#26235]
### Steps to reproduce

* Press **ESC**  on an open conversation
* Press **ESC** while writing on the search bar

* Press Cntrl + L

But All that is not working now.

### Expected behaviour

Telegram used to be Fully usable with a keyboard

If you press **ESC**, which is the most important keyboard shortcut,
* It would close the currently open conversation
* Clear the search bar
* Go back in nested channel opens

If you press CTRL+L, it would let you head to search, just like the URL bar on chrome

But All that is not working now.

### Actual behaviour

* Pressing ESC doesn't do anything, anywhere
*  Hence, keyboard navigation fully broken

### Operating system

Windows 11

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@abrahamadamu I cannot reproduce. If you restart the app or system or idk it fixes as well? I need steps to lead the app to that state.

**Comment by abrahamadamu** [comment]
Caused by other app (Grammarly)
