### ISSUE TITLE
Custom avatars save, but never show. Custom avatars don't work in desktop clients

### ISSUE THREAD

**Issue by TKIPisalegacycipher** [telegramdesktop/tdesktop#26248]
### Steps to reproduce

1. Set a custom avatar for a contact
2. Return to chat list showing the contact's chat in the list, or scroll to a group chat where the contact's message is shown

### Expected behaviour

The avatar shown should be the custom avatar.

This happens in Telegram desktop installed via Microsoft Store as well as several Android clients and Unigram for WIndows

### Actual behaviour

The avatar shown is one of the following:
1. A blurry circle
2. The avatar's initials
3. A white circle

### Operating system

Windows 11

### Version of Telegram Desktop

4.8.1 x64

### Installation source

Microsoft Store

### Logs

```shell
Logs not available on Microsoft Store binary
```

**Comment by ilya-fedin** [comment]
> as well as several Android clients and Unigram for WIndows

Looks like you've chose wrong issue type when reporting, this sounds like API issue

**Comment by TKIPisalegacycipher** [comment]
This bug matches https://bugs.telegram.org/c/27811

**Comment by ilya-fedin** [comment]
The bug is reported as Telegram Desktop-specific but according to the description it's a general one?

**Comment by john-preston** [comment]
@TKIPisalegacycipher Does it work on Android / Unigram or not? Is it NOT working only on Telegram Desktop or on other apps too?

Because it works perfectly fine for me on TDesktop 4.8.1, just tested it, the custom avatar is shown everywhere for that contact.

**Comment by TKIPisalegacycipher** [comment]
Does not work on Android or Unigram. Does not work on TDesktop 4.8.1.
