### ISSUE TITLE
Monospace font does not work properly

### ISSUE THREAD

**Issue by yallxe** [telegramdesktop/tdesktop#26243]
### Steps to reproduce

1. Send a message using monospace font

### Expected behaviour

Normal text, as usually

### Actual behaviour

![image](https://user-images.githubusercontent.com/82591945/235223062-19a6e695-ae7d-475d-918a-4e2c8ce7038b.png)
The text in monospace font is rendered glitchy and unreadable. When I try to copy the text, it copies properly as it should.

### Operating system

Windows 10

### Version of Telegram Desktop

4.8.1 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
what language is your windows? because someone else reported this bug and i am unable to reproduce it.

**Comment by ilya-fedin** [comment]
Try to reboot your computer, this looks like internal bug of Windows

**Comment by yallxe** [comment]
> what language is your windows? because someone else reported this bug and i am unable to reproduce it.

Polish

**Comment by yallxe** [comment]
Rebooted my PC today, the issue seems to be fixed.
