### ISSUE TITLE
GNOME system player missing metadata

### ISSUE THREAD

**Issue by Sarisan** [telegramdesktop/tdesktop#26245]
### Steps to reproduce

1. Open Telegram Desktop
2. Turn on track that contains metadata such as artist, title, cover
3. Open GNOME notifications

### Expected behaviour

![image](https://user-images.githubusercontent.com/63128024/235296763-6891e0d3-035c-493b-bd2e-ca02ff29eb61.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/63128024/235296575-90ac52e5-8ef3-44b0-84c5-690db6f70412.png)

### Operating system

Debian 12, GNOME 43.4

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I guess the track doesn't really contain that metadata, it's rather tdesktop UI gets it via iTunes (and SystemMediaControls is not integrated with iTunes atm).

**Comment by Sarisan** [comment]
> I guess the track doesn't really contain that metadata, it's rather tdesktop UI gets it via iTunes (and SystemMediaControls is not integrated with iTunes atm).

It does, It's the same mp3 file.
```
Input #0, mp3, from 'Music/Camellia - Rain of Amethyst.mp3':
  Metadata:
    track           : 1
    artist          : Camellia
    title           : Rain of Amethyst
    date            : 2015
    album           : crystallized
    encoder         : Lavf59.27.100
  Duration: 00:07:21.02, start: 0.023021, bitrate: 355 kb/s
  Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 320 kb/s
    Metadata:
      encoder         : Lavc59.37
  Stream #0:1: Video: png, rgb24(pc), 1080x1080 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Other
```

**Comment by Sarisan** [comment]
> Does tdesktop show the artist in its UI?

Yes
![image](https://user-images.githubusercontent.com/63128024/235464712-3af53863-8958-4fa1-b436-0c7d24ab7ceb.png)
