### ISSUE TITLE
Non-existent support or abuse handling

### ISSUE THREAD

**Issue by scarlion1** [telegramdesktop/tdesktop#26241]
### Steps to reproduce

1. Select "Ask a question"
2. Select "Ask a volunteer"
3. Ask the volunteers a question

### Expected behaviour

There should be a response from the volunteers promptly after reading the inquiry.

### Actual behaviour

Volunteers see the question and a double check mark is shown at some point, yet there's never any response.  Last received response to a question was in March 2017.  I have asked 8 questions since then that remain unanswered.  

Importantly, I have been the target of ongoing harassment for years and was using my Google Voice number as a secondary account to monitor this harassment and collect evidence.  Over a year ago, without notice, that account disappeared and I was unable to sign up again with my number.  I inquired several times with Telegram why this happened and how to fix it, but never received a response.  Without being able to monitor this ongoing harassment, I had to rely on finding other trusted individuals to do it for me, which was nearly impossible until just a month ago.  By then, this harassment had now escalated to crimes putting my life in danger, which have now been reported to police and FBI, and have required court ordered injunctions to be obtained, etc.  This conduct constitutes ToS violations as well, such as scamming users and promoting violence, and was reported to abuse@telegram.org about 20 days ago and no response there either.  Good job 👏  

I think, with Telegram Premium being a thing for over 10 months now, this area of the application should have improved, but this sort of thing should never have been allowed to happen to begin with.

### Operating system

doesn't matter

### Version of Telegram Desktop

any

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
this is telegram desktop client bugtracker, not related to telegram support.

**Comment by scarlion1** [comment]
I figured as much, but seeing as there's nowhere else to report this, and the support is built into the client, it's at least documented now.
