### ISSUE TITLE
Switch account using keyboard shortcut

### ISSUE THREAD

**Issue by sheldygg** [telegramdesktop/tdesktop#26258]
### Is your feature request related to a problem?

I have two accounts, one main and one for work. I switch between them too often, and I'm tired of pressing too many buttons.

### Describe the solution you'd like

When you press a key combination, the account changes. For example shift + tab, you can also shift + account number in the list.

### Describe alternatives you've considered

There are no alternatives =(

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/8179
