### ISSUE TITLE
notification sound keeps coming when focus mode is activated in windows 11

### ISSUE THREAD

**Issue by bukanspot** [telegramdesktop/tdesktop#26252]
### Steps to reproduce

1.  Telegram is minimized
2.  Enable focus mode in windows 11 (I activated focus mode from clock app)
3.  Notification sounds stay on, while other apps don't

### Expected behaviour

sound does not enter when in focus mode so there is no distraction

### Actual behaviour

sound notifications of received messages keep coming in

### Operating system

Windows 11 Home Single Language (x64)

### Version of Telegram Desktop

4.8.1 x64

### Installation source

Microsoft Store

**Comment by ilya-fedin** [comment]
Do you have Windows notifications enabled in settings?

**Comment by bukanspot** [comment]
> Do you have Windows notifications enabled in settings?

yes, I've tried using native and windows notification in telegram settings and the result is the same

**Comment by bukanspot** [comment]
I have updated Telegram version to 4.11.1 x64 but the problem is not resolved

**Comment by MrDvorak** [comment]
I've got the same issue. The "Use Windows notifications" switch is on.
It feels like handling of notifications sound is still processed by the app itself, not by Windows.

**Comment by ilya-fedin** [comment]
Yes, it is, the focus assist settings are queried via https://www.withinrafael.com/2019/09/19/determine-if-your-app-is-in-a-focus-assist-profiles-priority-list/
