### ISSUE TITLE
Telegram show messages abouve locked screen

### ISSUE THREAD

**Issue by AMV007** [telegramdesktop/tdesktop#26256]
### Steps to reproduce

1. just use telegram as usual
2. lock screen with password prompt appeared
3. Telegram messages appear above lock screen and unauthorized users and anyone can see them

### Expected behaviour

Telegram messages don't show above locked screen.

### Actual behaviour

Telegram messages showed above locked screen

### Operating system

Ubuntu 20.04, 22.04, Metacity window manager

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> Metacity window manager

Are you using WM-only environment? I'm not sure it's possible to detect lock screen then as such lighweight environments are usually not compatible with standardized D-Bus APIs. tdesktop doesn't have lock screen detection implementation on Linux at all though, apparently it should have one, probably using the portal APIs. But if you have a WM-only environment, that won't help you.

**Comment by AMV007** [comment]
this one, for example, easily detects the active splash screen:

dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver',member='ActiveChanged'" | while read line ; do
    if [ x"$(echo "$line" | grep 'boolean true')" != x ] ; then
        EchoInfo "screensaver on"

**Comment by ilya-fedin** [comment]
I don't like to depend on a GNOME protocol when there are standardized alternatives. The question about what the environment is still valid, the issue won't be accepted until you answer.

**Comment by AMV007** [comment]
not clear about environment issue, you can reproduce it, just install "gnome-session-flashback" package in Ubuntu 22.04.
what standardized alternatives do you mean ?
what do you mean about use only WM environment ? is it possible use Telegram client without it ?

may be add anything something as standard, no problem, I can send message for it over dbus with myself?
For now I'm detecting lock screen as highlited above and just killing Telegram and restarting it, but it wrong way anyway.

**Comment by ilya-fedin** [comment]
> what standardized alternatives do you mean ?

[The portal.](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Inhibit)

> what do you mean about use only WM environment ?

You specified "Metacity window manager" instead of "<X> desktop environment", so I assumed you have a handcrafted environment based on the WM.

**Comment by AMV007** [comment]
ok, add reaction for portal as highlited above, no problem.
my version:
xdg-desktop-portal-gtk 1.14.0
