### ISSUE TITLE
Окно не разворачивается через TeamViever

### ISSUE THREAD

**Issue by LittleTofu** [telegramdesktop/tdesktop#2625]
### Steps to reproduce
1. Через TeamViever на удалённом ПК открыть телеграм.
2. Свернуть окно приложения.
3. Развернуть окно приложения.

### Expected behaviour
Окно разворачивается в положение, из которого было свёрнуто.

### Actual behaviour
На панели задач окно отображается активным, но не разворачивается. (или разворачивается за пределами экрана?)

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** v 0.10.16 
**Version of TeamViever:** 12

P.S. Я понимаю, что, возможно, проблема в TV, но такое происходит только с телеграмом.

**Comment by auchri** [comment]
English please.
