### ISSUE TITLE
Takes a while to open, refresh opens it immediately 

### ISSUE THREAD

**Issue by xi-pinmping** [telegramdesktop/tdesktop#26253]
### Steps to reproduce

1. execute telegram-desktop
2. logs show `QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter` 
3. After refreshing sway session, the window draws immediately and output spams `qt.svg: Error while inflating gzip file: SVG format check failed` 

### Expected behaviour

Telegram should open as it is executed like it did previously

### Actual behaviour

Telegram does not open for several minutes unless I refresh my sway session

### Operating system

Arch Linux 6.2.12-arch1-1 
sway version 1.8.1

### Version of Telegram Desktop

telegram-desktop 4.8.1-2.1

### Installation source

cachyos repo

### Logs

```shell
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter

qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
```

In another thread a user suggested

    It's also possible to check whether this command hangs: busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings Read ss org.freedesktop.appearance color-scheme

This command yields
v v u 1

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
> telegram-desktop 4.8.1-2.1

what does this `-2.1` mean? No official build have such version postfix.

**Comment by xi-pinmping** [comment]
Postfix was for a recompiled x86_64-v3 binary, issue has been fixed now with no change however. Thanks!
