### ISSUE TITLE
Accidental deletion should be easier to prevent

### ISSUE THREAD

**Issue by morags** [telegramdesktop/tdesktop#26259]
### Is your feature request related to a problem?

Telegram enables the users to easily delete individual messages and entire chat: simply choose "delete" then click "yes". Unfortunately, this also allows for easy _accidental deletion_, with little chance of recovery. The problem is exacerbated by Telegram's own frequent "new feature" notifications, which many users are used to deleting, since they are impossible to archive.

### Describe the solution you'd like

I suggest redoing the way that Telegram deletes messages, so as to minimize or entirely prevent the chance of accidental deletion of chats.

### Describe alternatives you've considered

1. Allow the user to customize the number of seconds for which the "undo deletion" pop-up appears, and make it so that it cannot be "clicked away" until the time runs out.
2. Add a "bin" or "recover chats" option next to the option to export data, and move both options from the "advanced" settings to the "data and storage" settings. Of course, recovery should only be available for messages deleted by _that_ user, and for a limited - but customizable - time (eg. one hours or one week).
3. Add an option for automatic backups.

In addition, the ability to export individual chats should be available not only from the in-chat three-dot menu, but also by right-clicking on a chat in the chat list; and it should be possible to archive Telegram's notifications like any other chat.

**Comment by ilya-fedin** [comment]
> Unfortunately, this also allows for easy _accidental deletion_, with little chance of recovery.

How do you imagine a non-easy one? Should there be a ten of "are you sure" dialogs instead of one or what? The dialog already calls for the user to verify what it deletes, if he doesn't care, nothing will help.

**Comment by ilya-fedin** [comment]
It's not clear what the solution you would like

**Comment by ilya-fedin** [comment]
The alternative options seem to require too much customization while tdesktop prefers to avoid adding settings

**Comment by morags** [comment]
I'd argue that the risk of losing years' worth of chats in one absent-minded moment is too severe to let pass - certainly more severe than eg. where to animate "stickers", which has at least ten options.

The very least that can be done is to: a) prolong the time that the pop-up shows to 30s (like in Gmail "unsend"); b) make it so that it can only be dismissed by clicking on an "x"; and c) allow Telegram's own notifications to be archived or otherwise dismissed.

**Comment by MikeMilligan** [comment]
This just happened to me and I lost more than 5 years of conversations with a friend.

I was going to delete a message and I guess I wasn't paying attention and deleted the whole chat. I know it was my fault, but at least the Android version gives you an "Undo" option. So it would be nice to have that on the desktop software or a trash like someone else suggested.

**Comment by Harniver** [comment]
Similar thing just happened to me, losing lots of relevant information, cannot overstate how frustrated I currently am. I was on telegram web, so no "undo" banner at all showed up. I wanted to delete a few messages, didn't see the delete on the bottom and went for the delete on top (that was for the chat instead), assumed the banner was asking confirmation for deleting the messages and clicked "yes". This I think is a mistake that can easily happen, and the outcome is so frustrating to make you think switching to a different messaging app...

To me, the "trash" folder showing recently-deleted chat is a must-have feature that should have top priority.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by john-preston** [comment]
@Harniver Can you please share a screenshot with those two Delete buttons? On the web version you are talking about. This isn't relevant to this repository at all, but I'm curious.

**Comment by john-preston** [comment]
Well, it is "Delete Chat" text, not just "Delete". Ok, I see. Anyway, there is nothing I can do. Although in TDesktop there is a "Clear history" / "Delete conversation" buttons as well, with a single warning-confirm box.

**Comment by Harniver** [comment]
Of course if you're not doing things in a rush you'll notice and do the right thing, but it is still a good idea to try to prevent errors that can be easily done if you're rushing a bit!
