### ISSUE TITLE
fullscreen pictures have colors which are inverted

### ISSUE THREAD

**Issue by dm17** [telegramdesktop/tdesktop#26264]
### Steps to reproduce

Using tdesktop on linux click on any profile picture or picture from chats in order to fullscreen it. You'll see its colors are inverted.

### Expected behaviour

Picture displays like in the rest of Telegram with correct colors

### Actual behaviour

Picture has inverted colors. It has been happening for approximately a year, if I recall correctly.

### Operating system

Linux 6.2

### Version of Telegram Desktop

4.6.5

### Installation source

Other (unofficial) source

### Logs

```shell
no logs are printed
```

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org
