### ISSUE TITLE
Media viewer is larger than the display after resuming from sleep (macOS)

### ISSUE THREAD

**Issue by qtist** [telegramdesktop/tdesktop#26268]
### Steps to reproduce

- Using M1 PRO MacBook on Ventura 13.3.1
- Using clamshell mode with two external 3840x2160 displays with 2x scaling on both
- Telegram window fixed in the bottom left corner of the leftmost (main) display (size 380x820)
- Telegram scaling is set to 100%

Good case:
1. Open Telegram 
2. Open some media, a photo or a video
3. The fullscreen viewer should open normally

Bad case:
1. Put PC to sleep and later resume from sleep
2. Open media in Telegram
3. The fullscreen viewer now opens at 2x the size of the display, with only the bottom left corner of the media now visible
4. Restarting Telegram restores original working behaviour

I'm not sure whether this issue started in 4.8.1 or with Ventura but trying to view media and realising I have to quit and reopen Telegram multiple times a day is getting old! Note that this issue is for the cross-platform Telegram Desktop application, the "Telegram for macOS" application doesn't have this issue (I use both at the same time). 

Happy to try more things if you cannot reproduce. 

### Expected behaviour

Fullscreen media viewer should fit the display and the photo/video should be visible in its entirety. 

### Actual behaviour

Fullscreen media viewer appears 2x times larger than the display, with only the bottom left corner of the media visible. Restarting Telegram restores the original working behaviour. 

### Operating system

macOS Ventura 13.3.1

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by LennyLip** [comment]
Same here
<img width="706" alt="Screenshot 2023-05-08 at 21 57 51" src="https://user-images.githubusercontent.com/955994/236909903-7b48c0f6-d1ad-404a-8e0d-bab659df20c8.png">
<img width="589" alt="Screenshot 2023-05-08 at 21 57 58" src="https://user-images.githubusercontent.com/955994/236909914-f741c76f-c69e-4cbd-b19b-586708777a3a.png">

**Comment by CyberAP** [comment]
You don't need to restart telegram to fix this. Just toggle fullscreen view. Yes it's frustrating.

**Comment by qtist** [comment]
Now on **4.8.10**

The toggling fullscreen trick doesn't work for me. This issue is still driving me insane; every day I go to open an image to find out it's time to kill and re-open Telegram again, very frustrating.

**Comment by kolyasya** [comment]
+1, just installed telegram on my new Macbook pro 14 m1 pro and got the same issue. I'm on my external display and thought that it is somehow related. But there was no such issues on the same display with previous Intel based mac.

**Comment by john-preston** [comment]
I really need exact steps to reproduce the issue, starting with launching Telegram, because I can't reproduce it on demand myself. Steps, like:

1. Launch Telegram on MacBook screen.
2. Connect external monitor.
3. Drag Telegram from MacBook screen to external monitor.
4. Open photo in Telegram.

(those steps don't give an issue, I need steps that do give it in a consistent way)

**Comment by john-preston** [comment]
@qtist Was it going to sleep being connected in clamshell mode to external display or going to sleep before connecting? Was it waking up being connected or waking up and later being connected?

**Comment by qtist** [comment]
@john-preston Ah you've triggered a thought! I've just realised something and tested it. 

In my case the internal display is never used. I start off in clamshell mode and stay in clamshell mode the whole time.

**Case 1:** 

1. Lock (shortly followed by sleep)
2. Wake up and there is no issue (I've only tested this once, without a long sleep, so no guarantee this works every time)

**Case 2:**

1. Lock (shortly followed by sleep)
2. **Disconnect external display** during sleep
3. Re-connect external display during sleep
4. Wake up and the issue appears

I disconnect the displays overnight because MacOS likes to occasionally trigger the displays to wake up for no reason. This might be the key to reproducing the issue.

**Comment by john-preston** [comment]
@qtist Ok, thanks! I'll try those steps when I get my hands on UHD external monitor, should be in a week or so.

**Comment by LennyLip** [comment]
> external display
+1 the issue appears on the external display

**Comment by qtist** [comment]
@john-preston Sounds good! 

Today I left tried leaving the displays connected and can confirm that sleeping for a long period of multiple hours, the issue still appears. No need to disconnect/reconnect if you wait long enough.

**Comment by kolyasya** [comment]
@john-preston do you need any help to reproduce the bug?
