### ISSUE TITLE
undefined symbol: qt_resourceFeatureZstd, version Qt_6

### ISSUE THREAD

**Issue by RomanAverin** [telegramdesktop/tdesktop#26260]
### Steps to reproduce

1. Open Telegram Desktop

### Expected behaviour

Normal running Telegram Desktop

### Actual behaviour

Telegram Desktop won't start

logs error:
`
fedora-pc-local org.telegram.desktop.desktop[8137]: /usr/bin/telegram-desktop: symbol lookup error: /usr/bin/telegram-desktop: undefined symbol: qt_resourceFeatureZstd, version Qt_6
`

Repository source `rpmfusion-free-updates`

### Operating system

Fedora 38, Gnome 44.1, Wayland

### Version of Telegram Desktop

4.8.1-1.fc38  

### Installation source

Other (unofficial) source

### Logs

```shell
fedora-pc-local org.telegram.desktop.desktop[8137]: /usr/bin/telegram-desktop: symbol lookup error: /usr/bin/telegram-desktop: undefined symbol: qt_resourceFeatureZstd, version Qt_6
```

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
@Aokromes you can close, it's 100% a bug of third-party build

**Comment by Antiarchitect** [comment]
Fedora release 38 (Thirty Eight)
Linux xxx 6.2.14-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May  1 00:55:28 UTC 2023 x86_64 GNU/Linux

Exactly same.

**Comment by RomanAverin** [comment]
The problem is using the Qt-base 6.5.0 shared library in the fusion repository. Use flatpak or wait :)

**Comment by RomanAverin** [comment]
Thanks, problem on fusion repository side.

**Comment by kadyrov-ir** [comment]
> Thanks, problem on fusion repository side.
And how are you desided this problem?

**Comment by RomanAverin** [comment]
Use flatpak version
