### ISSUE TITLE
Stick to bottom in chat

### ISSUE THREAD

**Issue by Tsopic** [telegramdesktop/tdesktop#26275]
### Is your feature request related to a problem?

Currently, when you have a more active feed, the desktop messenger does not keep the scroll to the bottom. This results in missing out on the latest messages, when user does not manually scroll to the bottom of the chat.

### Describe the solution you'd like

Solution 1, 2
 1) Shortcut key to scroll to bottom
 2) Stick to bottom configuration option - This will scroll the chat to bottom on any new message.

### Describe alternatives you've considered

I've done my research of available features, seems like there is no current solution without clicking around the chat window with the mouse. Yes there is a button to scroll to bottom but it does not take away the pain, finding the chat in wrong position again. 
![image](https://github.com/telegramdesktop/tdesktop/assets/3941909/4ecaf8ea-5be2-45d2-b801-e419fcc0ba5d)

**Comment by ilya-fedin** [comment]
> Currently, when you have a more active feed, the desktop messenger does not keep the scroll to the bottom.

Are you sure? I can't reproduce, if I scroll to the bottom, it keeps at bottom.

**Comment by ilya-fedin** [comment]
I believe there shouldn't be a feature request to hack the behavior that should work not matter how active feed you have, instead you should report this as a bug.

**Comment by Tsopic** [comment]
> > Currently, when you have a more active feed, the desktop messenger does not keep the scroll to the bottom.
> 
> Are you sure? I can't reproduce, if I scroll to the bottom, it keeps at bottom.

Seems like it may be triggered By Images sent by a bot without text content. Not 100% sure but this could be it.

**Comment by ilya-fedin** [comment]
I believe this feature request should be closed and you should report a bug instead
