### ISSUE TITLE
Telegram Lite crashes on click "Go To Message" button

### ISSUE THREAD

**Issue by PinkChampagne17** [telegramdesktop/tdesktop#26273]
### Steps to reproduce

1. Select a group (This issue only occurs in my private group that enabled topic feature and I have not joined other group that enabled topic feature).
2. Select a topic
3. Click the top bar to open the topic info
4. Click "photos" button
5. Right-click any photo and click "Go To Message" button

### Expected behaviour

Go to the messages.

### Actual behaviour

Telegram Lite crashes.

### Operating system

macOS ventura 13.2.1

### Version of Telegram Desktop

4.8.1

### Installation source

Mac App Store

### Logs

```shell
The errors in the log file are related to MTP, I don't know if this crash is related to it.

log.txt

API Warning: not loaded minimal channel applied.
RPC Error: request 56 got fail with code 400, error PEER_ID_INVALID
RPC Error: request 38 got fail with code 400, error WEBFILE_NOT_AVAILABLE
```

log_xx_xx.txt
```
RPC Info: found parser for request 37, trying to parse response... (mtp_instance.cpp : 25)
RPC Info: error received, code 400, type WEBFILE_NOT_AVAILABLE, description:  (mtp_instance.cpp : 25)
RPC Error: request 37 got fail with code 400, error WEBFILE_NOT_AVAILABLE
```
```

**Comment by PinkChampagne17** [comment]
> > ### Crash ID
> > _No response_
> 
> Crash ID?

@ilya-fedin Sorry, I can't find **enable beta versions installation** in Settings -> Advanced so I can't give a crash ID.

**Comment by ilya-fedin** [comment]
@PinkChampagne17 you probably need to install tdesktop from https://desktop.telegram.org to get it

**Comment by PinkChampagne17** [comment]
@ilya-fedin Unfortunately, I couldn't reproduce this issue today, with either the version downloaded from the app store or the version downloaded from the website 😥
