### ISSUE TITLE
x64.4.8.1 There is no sensitive information button option in the setting.

### ISSUE THREAD

**Issue by 1044820212** [telegramdesktop/tdesktop#26277]
### Is your feature request related to a problem?

The button option cannot be disabled without sensitive information in the PC desktop settings

### Describe the solution you'd like

The button option cannot be disabled without sensitive information in the PC desktop settings

### Describe alternatives you've considered

The button option cannot be disabled without sensitive information in the PC desktop settings

### Additional context

The button option cannot be disabled without sensitive information in the PC desktop settings
![image](https://github.com/telegramdesktop/tdesktop/assets/42630237/4867aa29-82aa-46d7-9655-488f9f279cb7)

**Comment by ilya-fedin** [comment]
This means the server doesn't allow it for you
