### ISSUE TITLE
i lost access to my account

### ISSUE THREAD

**Issue by inukaze** [telegramdesktop/tdesktop#26282]
### Is your feature request related to a problem?

Hi there, my operator "Movistar" some days ago remove me the number 
+58 424 2132219

Well the thing is yesterday some new person that number is assigned, i was set passcode and password with the two pass verification. i close the access from another devices i just leaving three devices i am using yesterday.

Well today in this right moment i was kicked from my account, and i not have access with any device i had set up yesterday. looks like the new person have all my data or telegram simple just not ask for passcode and/or password during login

### Describe the solution you'd like

i just want had access to my account. i don't care about the phone number, i had too much personal information on my telegram.

But looks like for telegram just is important the phone number, and really don't check the password and/or passcode. a thing i never had understand is why telegram not allow just register with email, and/or check via registered email

### Describe alternatives you've considered

Can you destroy all data of my account if not possible for me restore the access to my account? well i don't want loss near 10 years of use telegram just because telegram considere too much more important the phone number.

### Additional context

i not have for the next year buy a new phone and/or phone number line because i still searching a new job from the past two years, but here in venezuela the thing is very complicated you get a job

**Comment by Aokromes** [comment]
this is a bug tracker, not a support place.

**Comment by inukaze** [comment]
> this is a bug tracker, not a support place.

Where is the support place, yesterday i write on twitter but i not had answer yet. can you give me a support contant email or something ?

**Comment by inukaze** [comment]
> this is a bug tracker, not a support place.

i Just have a dunno :
How a Telegram ignoring a previously set password and/or passcode if a new user with the same phone number i had before is not a bug ?

**Comment by Aokromes** [comment]
> > this is a bug tracker, not a support place.
> 
> i Just have a dunno : How a Telegram ignoring a previously set password and/or passcode if a new user with the same phone number i had before is not a bug ?

if you don't own the phone number he can delete the account. because you don't own account "login" anymore.

**Comment by inukaze** [comment]
> > > this is a bug tracker, not a support place.
> > 
> > 
> > i Just have a dunno : How a Telegram ignoring a previously set password and/or passcode if a new user with the same phone number i had before is not a bug ?
> 
> if you don't own the phone number he can delete the account. because you don't own account "login" anymore.

i understand that the part 

but i can't understand is if i was stablished a password before from diferent device and public IP. this is just ignored by telegram when the login has been make from a new diferent device with a diferent ip, in that moment telegram just ignore the password and/or passcode i had set before. and how specificially this is not a bug ?
