### ISSUE TITLE
Telegram Web Apps in i3wm

### ISSUE THREAD

**Issue by erfanmola** [telegramdesktop/tdesktop#26288]
### Steps to reproduce

1.Just use the Telegram Desktop in a GNU/Linux Distro that is using i3wm

### Expected behaviour

The WebView should work as normal

### Actual behaviour

The floating window of the WebView appears in an oddly shape, then it's content must be a WebView, right? it isn't, it is just a blank screen, as if the client is failing to render the WebView

### Operating system

Arch Linux

### Version of Telegram Desktop

4.8.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
https://github.com/i3/i3/discussions/5091

**Comment by Aokromes** [comment]
it's i3 bug then?

**Comment by ilya-fedin** [comment]
either i3 or picom bug, yes
