### ISSUE TITLE
No "Sensitive Content" option in "Privacy and Security" settings

### ISSUE THREAD

**Issue by Mortrus** [telegramdesktop/tdesktop#26287]
### Steps to reproduce

1. Download latest Telegram Desktop
3. Go to "Privacy and Security" settings

![image](https://github.com/telegramdesktop/tdesktop/assets/42960438/2ee84b14-6323-49e0-a531-6010c5df00d9)

### Expected behaviour

There should be an option "Sensitive Content" in "Privacy and Security" settings.

### Actual behaviour

There is no option "Sensitive Content" in "Privacy and Security" settings.
![image](https://github.com/telegramdesktop/tdesktop/assets/42960438/cd9a1f9d-c448-4dcb-8bf4-ba5ed2647062)

I have downloaded Telegram from official web site.
The "bug" happens because of this code in **_tdesktop/Telegram/SourceFiles/settings/settings_privacy_security.cpp_** https://github.com/telegramdesktop/tdesktop/blob/37f5576c389a4257917f5621680aac1f46b74ad4/Telegram/SourceFiles/settings/settings_privacy_security.cpp#LL872C1-L873C56
```
#if !defined OS_MAC_STORE && !defined OS_WIN_STORE
	SetupSensitiveContent(controller, content, trigger());
```

### Operating system

Microsoft Windows 10 Home

### Version of Telegram Desktop

4.8.1 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
If you don't have the option, it means the server just doesn't allow it for you

**Comment by Mortrus** [comment]
> If you don't have the option, it means the server just doesn't allow it for you

I've updated my report. Please check "Actual behaviour" section. It's restricted by the code, IDK why.

**Comment by ilya-fedin** [comment]
The code in the snippet you provided looks completely valid

**Comment by Mortrus** [comment]
But behaviour is invalid. 
I downloaded Telegram Desktop 4.8.1 x64 from Microsoft Store, the same problem happens with it.

![image](https://github.com/telegramdesktop/tdesktop/assets/42960438/9a9192e9-c4a8-4827-aa11-e2616730a1d9)

**Comment by ilya-fedin** [comment]
Yes, the store versions aren't supposed to show this option, it's an intended restriction due to store policies. If you don't see this option in non-store builds as well, it means the server has prohibited you to change it, as I already said. Sorry, but it's all is intended and you can't do anything (except from changing the country you live in probably).
