### ISSUE TITLE
Manual Monospace Format doesn't have behavior of "Tap to Copy" on Telegram for Windows

### ISSUE THREAD

**Issue by xtianpu** [telegramdesktop/tdesktop#26280]
### Steps to reproduce

1. You can copy-paste the text below to the text field:

📍@suvpenbot token:
6126118126:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

📍@suvbasebot token:
6130921698:bbbbbbbbbbbbbbbbbbbbbbbbbbbb

📍 @suvdemobot token:
6063282833:cccccccccccccccccccccccccccccccccccc

📍@suvlletbot token:
6030302765:dddddddddddddddddddddddddddd

#aaaaa

2. Block one of fake bot token, for example (6126118126:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
3. Right-click the block
4. Select formatting
5. Select monospace
6. Send the message

### Expected behaviour

The mouse pointer should change to clickable pointer as like as copying Bot Token from BotFather. Monospace formatting and Tap to Copy works well on Telegram for iOS and Android

### Actual behaviour

Hovering to the text doesn't change the pointer visual to clickable pointer

### What I've to do to make it work
I've to write one by one all tokens. For example, I put text below on the text field:

📍@suvpenbot token:
6126118126:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

1. Block the token (6126118126:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa), right-click the block, select formatting, select monospace, and send.

2. Continue with right-click the sent message above, click edit, and append another token for example like below:

📍@suvpenbot token:
6126118126:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

📍@suvbasebot token:
6130921698:bbbbbbbbbbbbbbbbbbbbbbbbbbbb

continue with monospace formatting as above for token (6130921698:bbbbbbbbbbbbbbbbbbbbbbbbbbbb), and so on

### Operating system

Windows 10

### Version of Telegram Desktop

v4.8.1 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> Send any message

Is it an one-line message? Multi-line monospace blocks aren't supposed to be monospace.

> Format to monospace

How exactly? There are multiple ways to apply monospace formatting.

**Comment by xtianpu** [comment]
> > Send any message
> 
> Is it an one-line message? Multi-line monospace blocks aren't supposed to be monospace.
> 
> > Format to monospace
> 
> How exactly? There are multiple ways to apply monospace formatting.

Oops! Sorry, I have edited the steps to reproduce, please check.

**Comment by ilya-fedin** [comment]
They still don't describe how you format it?

**Comment by xtianpu** [comment]
> They still don't describe how you format it?

Edited, with more details. I hope it more clearer.

**Comment by xtianpu** [comment]
I've add **What I've to do to make it work** section for more details
