### ISSUE TITLE
I do not understand if my request was received by support

### ISSUE THREAD

**Issue by godcodehunter** [telegramdesktop/tdesktop#26281]
### Steps to reproduce

My number was stolen by the operator.  Number, I have all proof of ownership of the number in the past. 

I write a request to the support service, but I do not receive a letter stating that my request has gone into circulation.  
I can't figure out if support is listening to me.

### Expected behaviour

Some kind of response generated by an automatic system, with the number of my appeal, or at least confirmation that the appeal was delivered

### Actual behaviour

I don’t know, probably, there’s nothing like that at telegram support service

### Operating system

linux

### Version of Telegram Desktop

latest

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
this is telegram desktop bug tracker, not support request place.

**Comment by godcodehunter** [comment]
> this is telegram desktop bug tracker, not support request place.

But the telegram server does not have a bug trainer.  This is clearly a behavioral error, the user is not notified that a message has been received.
