### ISSUE TITLE
How to get 90-95% zoom of Telegram Desktop interface?

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#2628]
Minimal available zoom value (“Inteface Scale”) is 100%. But for me it's too much. I wanna decrease it to 90-95. Or even 85. Because I need smaller fonts at this UI. Now there are no font settings in Telegram Desktop. Does anybody know is it possible to launch Telegram with shortcut key (e.g.: "Disk:\Directory\telegram.exe" -90%)?

Win 8.1 x64, Telegram Desktop 0.10.19.

**Comment by auchri** [comment]
#1334

**Comment by himanshuxd** [comment]
In [https://github.com/telegramdesktop/tdesktop/issues/1334](#1334) this issue has been cited and referenced as duplicate and closed and the same has done here by citing that issue. This is a bad way to kill of two issues that want people to scale their desktop client <100% and had nothing to do with automatic scaling.

**Comment by Twilightssuperb** [comment]
@himanshuxd, you can launch Telegram with label for exe and added key "-scale 80", e.g. Just create a lnk-file in Telegram folder, then go to Options of it and type key. It could look—«"C:\Telegram\Telegram.exe" -scale 80». Also you can set any scale factor from 75 to...

**Comment by himanshuxd** [comment]
Ty @Twilightssuperb

**Comment by emerson-caitano** [comment]
Tks ! 

> @himanshuxd, you can launch Telegram with label for exe and added key "-scale 80", e.g. Just create a lnk-file in Telegram folder, then go to Options of it and type key. It could look—«"C:\Telegram\Telegram.exe" -scale 80». Also you can set any scale factor from 75 to...

Thx!
