### ISSUE TITLE
[flatpak] Telegram Desktop tray icon too big after the last upgrade (to 4.8.1)

### ISSUE THREAD

**Issue by kli0rf** [telegramdesktop/tdesktop#26297]
### Steps to reproduce

Check the icon size in Fedora's tray.
![t-desktop](https://github.com/telegramdesktop/tdesktop/assets/18033767/64539989-88ec-47ce-b837-cbb6fba3795f)

### Expected behaviour

Should probably be reverted back to previous size.

### Actual behaviour

Now it's just too big. :)

### Operating system

Fedora with Gnome 3.30.X

### Version of Telegram Desktop

4.8.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Is it since 4.8.0 or 4.8.1 or some even older version? There were no changes related to tray icon in 4.8.1 and the only change related to tray icon in 4.8.0 was to [avoid Qt from raster upscaling the counter part in the image](https://github.com/telegramdesktop/tdesktop/commit/8dee2a1c8b0838ec2a9f6e8776e4cb386f476b53) with non-1 device pixel ratios. I can't imagine how it can affect image size itself and, moreover, I can't reproduce that on my machine with KDE. Maybe it is a change on your tray icon extension side?

**Comment by kli0rf** [comment]
I wasn't booting into Fedora too often lately, so there's pretty big chance i missed 4.8.0 and upgraded to 4.8.1 from an even older version. However, it's definitely not a change of my old tray extension (https://extensions.gnome.org/extension/1031/topicons/) as it's been there for ages without any upgrades.
My Fedora is old (29) and the Gnome is even older (3.30.2), so this bug isn't too relevant, i suppose. A fix would be nice, but it's not like it's necessary.

**Comment by ilya-fedin** [comment]
Oh, TopIcons is an extension using the legacy XEmbed protocol if I remember right which practically means each icon is an X window... In that case Qt should draw the image data into that window and it seems it draws it bigger than it should, so that really smells like a Qt bug...

**Comment by ilya-fedin** [comment]
Or maybe it hides actual windows and captures only a fixed part of the window while Qt's window itself is bigger than what it thinks. Then the issue could be on GNOME side as well...

**Comment by kli0rf** [comment]
Either way this hasn't been the case with them older versions of tdesktop. I couldn't say precisely which version it first appeared on, but timewise i'd say this hasn't been the case around 4 to 7 weeks ago.

**Comment by ilya-fedin** [comment]
Please check whether the bug is reproducible with the following Qt example: https://github.com/qt/qtbase/tree/dev/examples/widgets/desktop/systray

tdesktop uses Qt 6.4.0, you have to build the example with exactly this Qt version in order to verify whether this is a Qt bug

**Comment by LordRafa** [comment]
How can you see the Telegram icon on gnome fedora? I am using topicons extension on fedora 38 I cannot see anything at all.... other apps can show the icons but telegram doesnt...

**Comment by ilya-fedin** [comment]
TopIcons uses the legacy protocol based on X11 and you're probably using Wayland, so you need a more modern extension implementing StatusNotifierItem (also known as AppIndicator)

**Comment by kli0rf** [comment]
> How can you see the Telegram icon on gnome fedora? I am using topicons extension on fedora 38 I cannot see anything at all.... other apps can show the icons but telegram doesnt...

Fair question. Sadly, i have no answer for that, i have no idea, to be frank.
![Screenshot from 2023-05-17 18-20-08](https://github.com/telegramdesktop/tdesktop/assets/18033767/cd836916-2e91-4fd9-9d17-62ef466b264e)
![Screenshot from 2023-05-17 18-20-50](https://github.com/telegramdesktop/tdesktop/assets/18033767/a98a954d-1e1a-487b-8404-28474d995cd7)

The one on the left is tdesktop running on my main Fedora, the one on the right is on VM.  Both are running on same Fedora 29, same gnome, same TopIcons Plus (https://extensions.gnome.org/extension/1031/topicons/).
The tdesktop settings -> advanced section menus looks way different, though. And that's a mistery to myself too. Both tdesktops are the same 4.8.1 from flathub.
```
flatpak list | grep -i telegram
Telegram Desktop - Fast. Secure. Powerful.	org.telegram.desktop	4.8.1	stable	x86_64	flathub	system
```

**Comment by kli0rf** [comment]
The only difference between the two is, the one on the left is installed few years ago, and i've been upgrading it via 'flatpak update' command. The one on the right is installed 15 minutes on VM, which is also installed 20 minutes ago. No idea if that's relevant anyhow.

**Comment by kli0rf** [comment]
Alright, the mistery solved. As @ilya-fedin mentioned, the Wayland was the culprit of the different settings menus. Wayland is the default even for Fedora 29, but i had Wayland disabled on my host Fedora (can't remember why, but most likely because of nvidia gpu problems). As soon as i disabled Wayland on my VM Fedora, tdeskop settings menu become the same as on my host Fedora's tdesktop. And the icon on the systray is too big again.
![Screenshot from 2023-05-17 18-57-47](https://github.com/telegramdesktop/tdesktop/assets/18033767/eb0fe777-5fb4-4f89-896e-72140127f979)
As promised, i'm gonna compile the Qt and try the Qt systray example next weekend.
BTW, i also installed skype on VM Fedora just to see if it's systray icon's working the right way. So yeah, it does, you can see it on the screenshot.

**Comment by ilya-fedin** [comment]
If you won't reproduce at first, try to patch Qt with tdesktop patchset (https://github.com/desktop-app/patches/tree/master/qtbase_6.5.0, like `find ../../patches/qtbase_6.5.0 -type f -print0 | sort -z | xargs -r0 git apply`) re-build Qt (not full rebuild, just calling build/install commands again should be enough) and check again

**Comment by kli0rf** [comment]
Sorry, guys, i was unable to build Qt 6.4.0 on Fedora 29 vm. Too many incompatible dependencies to solve. If building Qt systray example with Qt 6.4.0 is the only way to debug this bug, i'd say it's not worth it. My Fedora is way too old to put so much of the effort for this minor bug. So if you guys approve, i'm closing this issue.

**Comment by ilya-fedin** [comment]
Well, I don't see another way... You can use the tdesktop's Dockerfile that includes Qt

**Comment by ilya-fedin** [comment]
> Sorry, guys, i was unable to build Qt 6.4.0 on Fedora 29 vm.

It's not 6.4.0, it's 6.5.0

**Comment by kli0rf** [comment]
> Please check whether the bug is reproducible with the following Qt example: https://github.com/qt/qtbase/tree/dev/examples/widgets/desktop/systray
> 
> tdesktop uses Qt 6.4.0, you have to build the example with exactly this Qt version in order to verify whether this is a Qt bug

I used 6.4.0 'cause you told me so.

**Comment by ilya-fedin** [comment]
Oh, it was a typo

**Comment by kli0rf** [comment]
Alrite, i'll try the same thing again in the few days and will let you know.

**Comment by kli0rf** [comment]
Hehe, somebody was faster.
I installed the new Fedora 29 vm today and i was about to build Qt 6.5.0 and the systray example. I installed the tdeskop before going to compile Qt, just to make sure i can still reproduce this bug, and i couldn't, which was a nice surprise. Then i updated tdesktop on my host Fedora, and the bug on my host Fedora was fixed with this latest update from flathub as well. Whoever did this - thank you so much!
I'm about to close this issue as it's been solved, yet i'm gonna wait until the evening in case anyone wants to add some comments.

**Comment by ilya-fedin** [comment]
There was Qt update today

**Comment by kli0rf** [comment]
Ah, so it was Qt bug after all. Well, glad it's gone. Thanks!

**Comment by ilya-fedin** [comment]
I guess it's rather tdesktop patchset... Some patches were deleted while rebasing on 6.5.1

**Comment by mishurov** [comment]
I had this issue too. X11, i3wm and the installation from the website. I just installed 4.7.1 and disabled updates.
