### ISSUE TITLE
Mark as unread on active not working

### ISSUE THREAD

**Issue by ornic** [telegramdesktop/tdesktop#26299]
### Steps to reproduce

1. Open any chat
2. Read it till the end
3. Try to mark it as unread

### Expected behaviour

1. Focus moves to the next chat
2. Chat from "steps to reproduce" is marked as unread

### Actual behaviour

1. Focus moves to the next chat
2. Chat from "steps to reproduce" is **NOT** marked as unread

### Operating system

Windows

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
How is it "Focus moves to the next chat"? For me it works like this:

- I open a chat
- right click on it in the chats list
- choose "Mark as Unread"
- the chat closes and a blue mark appears on the chat in the list

This is what is expected and it works for me in 4.8.1 on Windows.

**Comment by ornic** [comment]
Ooooook, I suppose that was some rare glitch that I stumbled upon couple of times. And since most times Telegram running several days without restarting, I decided that it's a bug.

Good to have this sorted, thanks! :)
