### ISSUE TITLE
Last seen time not always correctly updated after signing off telegram.

### ISSUE THREAD

**Issue by rimmi21** [telegramdesktop/tdesktop#2629]
My husband finds that my last seen shows him online even when i quit telegram .. and this is happening repeatedly .. it's creating issues between us and he thinks am into something else. Would you kindly clarify this issue? I use IOS. And most of the time my last seen shows like "online" even when am offline for about 20-30 minutes. Please solve this issue. Please provide me with a clear cut clarification regarding this issue, as it's serious enough for me as well as my relationship now. Please help ! :-(

**Comment by Kondra007** [comment]
First of all, this is not iOS app repo. 
Second, use "ask question" button in your iOS Telegram app to contact support.
