### ISSUE TITLE
Turn of youtube preview.

### ISSUE THREAD

**Issue by luckydonald** [telegramdesktop/tdesktop#263]
Hey,
Is there a way to turn off the youtube preview?

**Comment by Aokromes** [comment]
yeah maybe one dropdown "small, medium, large (current size), extra large (taking the whole window width), full screen"

**Comment by luckydonald** [comment]
Also, doesn't a youtube preview in a secret chat expose that information to the internet?
(Not sure if it does that, nobody around to start a secret chat with...)

**Comment by sigod** [comment]
There's no Secret Chats in Telegram Desktop yet.

**Comment by joshery420** [comment]
Correct, no Secret Chats in desktop yet.

Also, +1 for @Aokromes list as long as we add "No preview" that simply shows the hyperlink, since that was the original request.

**Comment by yuergen** [comment]
Maybe this could be resolved together with #687.
