### ISSUE TITLE
Telegram Portable missing version and update in settings

### ISSUE THREAD

**Issue by VetaLioSTV** [telegramdesktop/tdesktop#26308]
### Steps to reproduce

As title says for some reason **tportable** doesn't have "**Version and updates**" section \ category in "**Advanced settings**", but non portable version have it. So for now **tportable** always updates automatically without user interaction. I want to have same consistent posibility to disable \ enabled by myself(user), in otherwords i would like to store **tportable** version X.X.X and not update it automatically.

### Expected behaviour

**tportable** should have the same functionality how it works \ looks on regular desktop version. (see screenshot below)

![image](https://github.com/telegramdesktop/tdesktop/assets/15155286/81d26024-aedc-476c-8d6f-117ac047469e)

### Actual behaviour

Currently "Version and Updates" is missing in tportable version(autoupdates are forced without user interaction), you can't do anything.(see screeshot below)

![image](https://github.com/telegramdesktop/tdesktop/assets/15155286/1acf6e5d-1023-43d3-8fd0-d964e14df9f0)

### Operating system

Any OS

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

### Logs

```shell
Not required
```

**Comment by ilya-fedin** [comment]
Are you sure you use the official version and not some debug versions a developer gave you previously?

**Comment by VetaLioSTV** [comment]
> Are you sure you use the official version and not some debug versions a developer gave you previously?

i have downloaded from here (curren git repo), as release version.

**Comment by ilya-fedin** [comment]
Maybe you're launching multiple instances using the same binary? Only the first launched one will let you update

**Comment by VetaLioSTV** [comment]
> Maybe you're launching multiple instances using the same binary? Only the first launched one will let you update

I'm using usually Desktop version(non portable) and sometimes tportable as second client. There was a funny moment : on 21 april i received "auto update" on portable version(just randomly opened it somewhere in middle of day). meanwhile non portable version(regular desktop client) didn't got notification about it and i have waited until next day i think.

So could you please check, just download current/old version of tportable and take a look into advanced settings -> version and updates ? Does it shows something or the same as i have?

**Comment by ilya-fedin** [comment]
I can't, I'm a Linux user and there's no tportable for Linux

**Comment by ilya-fedin** [comment]
Maybe you have just disabled automatic updates? The switch will then be on top of the menu, not on the bottom.

**Comment by VetaLioSTV** [comment]
> Maybe you have just disabled automatic updates? The switch will then be on top of the menu, not on the bottom.

I have checked and want to say that you're right. Seems to be UI changes, since previously it was at bottom any  time(disabled\enabled).

**UPD** - also, it works the same on regular desktop client, behavior is weird. When you disable auto updates, it remains on bottom(at moment, i mean settings form is not closed yet). Then after your quit from settings and returning back it moves from latest item (from bottom) to first item at top (as disabled). If you enable it then it remains on top( settings form not closed yet), but after your quit it moves back to bottom and remains their unchaged(before you will not disable it).

Does it expected behaviour? I'm not sure, as far as i remember update section always have been at bottom as last section, then when and why it was changed to these weird jumps at top/bottom after disabling / enabling ?

Can you confirm / check my note on your client?(non portable)

**Comment by ilya-fedin** [comment]
> Does it expected behaviour?

Yes, it was always like that IIRC

**Comment by VetaLioSTV** [comment]
> Yes, it was always like that IIRC

Definitively it wasn't like this, section "Version and Updates" has been located at bottom for a long time (before some UI changes, idk).

@Aokromes can you confirm / your thoughts?

**Comment by ilya-fedin** [comment]
> Definitively it wasn't like this

I see it's like this since at least 2018

**Comment by john-preston** [comment]
It was always like this, the section was brought to top in case the autoupdating is disabled - to make it easier for you to enable it :) maybe it's not a great UX decision, but it works like that since the last Settings redesign (many years).

**Comment by VetaLioSTV** [comment]
> It was always like this, the section was brought to top in case the autoupdating is disabled - to make it easier for you to enable it :) maybe it's not a great UX decision, but it works like that since the last Settings redesign (many years)

Thanks for your reply. Seems to  be i didn't disabled auto updates for a long time on my desktop client, so thats why i didn't saw that flow \ changes on UI.
