### ISSUE TITLE
Automatically logs out from all devices and deletes outgoing messages for the last hour

### ISSUE THREAD

**Issue by Kirill-Fazlyev-ext-orion** [telegramdesktop/tdesktop#26301]
### Steps to reproduce

be logged in on multiple devices (IOS, PC)
chat with your contacts

### Expected behaviour

The login status does not disappear, it does not automatically log out.
Outgoing messages are not deleted.

### Actual behaviour

Login status disappears, automatically logs out.
Outgoing messages are deleted.

### Operating system

Windows, IOS

### Version of Telegram Desktop

v4.8.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
i don't think this is client bug, i suggest you to use in app ask a question.
