### ISSUE TITLE
Wrong jump time on caption timestamp in long audio/mp3 files

### ISSUE THREAD

**Issue by glococo** [telegramdesktop/tdesktop#26305]
### Steps to reproduce

Add captions with timestamp to an mp3, like 10 minutes or more, hours.

I took an AudioBook: Thinking, Fast and Slow (Daniel Kahneman, Patrick Egan) of 20h 7m

0:00:19 Introduction
0:04:40 Origins
0:26:40 Where we are now
0:35:15 Whats comes next
0:42:14 PART 1: Two Systems
0:42:21 Chapter 1: The Characters of the Story
1:17:10 Chapter 2: Attention and Effort
1:43:05 Chapter 3: The Lazy Controller
2:17:26 Chapter 4: The Associative Machine
2:45:40 Chapter 5: Cognitive Ease
3:20:25 Chapter 6: Norms, Surprises and Causes
3:44:38 Chapter 7: A Machine for Jumping to Conclusions

### Expected behaviour

Jump to the right time in all Android devices I took.

### Actual behaviour

But in TDesktop jumps to wrong places, even by seconds after just few minutes.
The time span after an hour became a minute or more, making timestamp captions misleading

### Operating system

Windows 11

### Version of Telegram Desktop

4.8.1 x64

### Installation source

Static binary from official website

**Comment by Lyric321** [comment]
[Me-videos.csv](https://github.com/telegramdesktop/tdesktop/files/13719492/Me-videos.csv)
