### ISSUE TITLE
[URGENT] Telegram not responding to any types of support request

### ISSUE THREAD

**Issue by godcodehunter** [telegramdesktop/tdesktop#26304]
### Steps to reproduce

Just write to any types of support request

### Expected behaviour

Any help

### Actual behaviour

It's been a WEEK already
So, I have been trying to reach out telegram support through different modes, I have tried mailing 1000 times, tried volunteer support within app, but never received a single response from Telegram.
I understand that this is not a telegram desktop problem, I already tried to contact the telegram team through familiar TON developers. But I didn’t succeed, my number was withdrawn from circulation by the operator, unfortunately, I don’t have time to keep track of all my equipment and applications (yes, I’m a programmer, a shoemaker without boots, all that), I’m absent-minded and, of course, partly to blame for the situation. But I need help. Telegram is a huge social platform, if this happened to me then it can happen to someone's grandmother. 

Please, help, I just don't know where else to write

### Operating system

linux

### Version of Telegram Desktop

latest

### Installation source

Snap

**Comment by Aokromes** [comment]
this is telegram desktop bug tracker, not support reach place, nothing can be done here.

**Comment by godcodehunter** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4623 but they helped her, or is it because I'm Russian?

**Comment by godcodehunter** [comment]
> 

Well, give me some instructions where to write to me and how to make sure that support received my appeal?

**Comment by ilya-fedin** [comment]
> Are you from the same company?

This is community-maintained bug tracker

**Comment by john-preston** [comment]
If you have access to the account, but not the number, you can change the number from any official mobile app (iOS, Android). If you don't have access to the number and to the account, then you lost the account, sorry.

**Comment by godcodehunter** [comment]
> If you have access to the account, but not the number, you can change the number from any official mobile app (iOS, Android). If you don't have access to the number and to the account, then you lost the account, sorry.

Well, is there a way?  I understand why this problem is so difficult to solve (

**Comment by john-preston** [comment]
@godcodehunter If you don't have access to the account and to the number of that account then there is no way.
