### ISSUE TITLE
Be able to block users client/server side

### ISSUE THREAD

**Issue by Toastermaker** [telegramdesktop/tdesktop#26314]
### Is your feature request related to a problem?

If you block a user they can still mention or reply to you in a group which makes the blocking feature 50% pointless. A way to mute their chat or even response elsewhere would solve this fundamental problem. IRC can do it client/server side so I'm not sure why telegram can't feature one and/or the other.

### Describe the solution you'd like

A way to block users from being able to mention/reply to you in group chats. And don't say that this is a moderator issue because then every moderator would have to be on 24/7 and deal with every user not to mention bots can't help unless it's spam.

### Describe alternatives you've considered
Disabled notifications for 42 millions users in 69 million groups when only 1 person is bothering me because logic.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
