### ISSUE TITLE
Non-UTF-8 link previews are broken

### ISSUE THREAD

**Issue by jtojnar** [telegramdesktop/tdesktop#2631]
### Steps to reproduce
1. Post URL of page using other encoding than UTF-8 (e.g. http://www.lidovky.cz/moskva-doufa-ze-trump-zmirni-tlak-nato-na-rusko-putin-mu-zaslal-krasny-dopis-1sq-/zpravy-svet.aspx?c=A161112_104939_ln_zahranici_ele)

### Expected behaviour
The link preview should display the entire title of the page (Moskva doufá, že Trump zmírní tlak NATO na Rusko. Putin mu zaslal ‚krásný dopis‘)

### Actual behaviour
The title ends when it encounters the first byte that is not compatible with Telegram’s encoding.

![moskva-douf](https://cloud.githubusercontent.com/assets/705123/20238007/bbe95074-a8e1-11e6-8cf1-dd5c10078150.png)

### Configuration
**Operating system:** Reproducible on Linux and Windows

**Version of Telegram Desktop:** 0.10.19

**Comment by stek29** [comment]
Previews are generated on server side + This happens on Android too, so it's not TDesktop's issue.
