### ISSUE TITLE
telegram opens links in a browser that is set as non-default.

### ISSUE THREAD

**Issue by bagasik** [telegramdesktop/tdesktop#26318]
### Steps to reproduce

Hello.
My system:
xfce4 4.18.2
Linux 6.1.28-gentoo x86_64

My programs:
firefox-bin 113.0.1
google-chrome 113.0.5672.126
telegram-desktop-bin-4.8.1

xfce4 has the default browser google-chrome.
In xfce4 settings -> Default settings -> google-chrome browser is selected.

$ xdg-settings get default-web-browser
google-chrome.desktop

egrep 'htt|bro' ~/.config/mimeapps.list
x-scheme-handler/http=xfce4-web-browser.desktop;
x-scheme-handler/https=xfce4-web-browser.desktop;
x-scheme-handler/http=xfce4-web-browser.desktop
x-scheme-handler/https=xfce4-web-browser.desktop

### Expected behaviour

I want links to open in the default browser google-chrome

### Actual behaviour

I want links to open in the default browser google-chrome

In the telegram messenger, links/url open in firefox.
In the Skype messenger, links/url open in google-chrome.

### Operating system

Linux 6.1.28-gentoo x86_64. xfce4 4.18.2

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop uses the `g_app_info_launch_default_for_uri` API of the glib library to open URLs, if you think glib does a wrong thing, feel free to report the glib bug tracker

**Comment by MrPenguin07** [comment]
Confirm for myself, also on Gentoo.

Previously had a single firebox based browser installed and links opened without issue.
Installed brave and now all links forced to open in brave, despite it being non default.

Other apps respect my default browser.

**Comment by MrPenguin07** [comment]
This seems to be a wayland issue, whether with wayland or tg;

qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
[12861:12883:0606/160637.837169:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[12861:12883:0606/160637.837196:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
Opening in existing browser session.
