### ISSUE TITLE
Internal server error on change the phone number

### ISSUE THREAD

**Issue by IceBlackwell** [telegramdesktop/tdesktop#26319]
### Steps to reproduce

Settings - Edit profile - Phone number - Change number - Enter new number

### Expected behaviour

Sending a confirmation code on the new phone number

### Actual behaviour

"Internal server error" message in the change number dialog box, "Error: should not be in-app code!" message in the app log.

### Operating system

Linux Mint 19 Tara, Cinnamon 3.8.9

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
You can do this only using official Android or iOS app

**Comment by IceBlackwell** [comment]
> You can do this only using official Android or iOS app

ок, а как быть, если старый номер больше не доступен? У меня телеграм всю жизнь только на десктопе стоял.

**Comment by john-preston** [comment]
You can log in a new session from iOS or Android app by receiving your code in your TDesktop session and change the number there. In the next versions there'll be a correct message about phone changing from TDesktop, but it'll still be available from iOS and Android only.
