### ISSUE TITLE
default scheduling policies and realtime priorities (SCHED_FIFO, rtprio = 88) of main thread are too extreme

### ISSUE THREAD

**Issue by alesandar** [telegramdesktop/tdesktop#26326]
### Steps to reproduce

1. Start telegram-desktop
2. Inspect the scheduling class and the realtime priority of the process.

a) using `ps` and `grep`:
```shell
$ ps -eLo rtprio,cls,cmd | grep FF | grep telegram-desktop
    88  FF telegram-desktop --
```
b) using `strace`:
```shell
$ strace telegram-desktop  2>&1 | grep FIFO
sched_get_priority_min(SCHED_FIFO)      = 1
sched_get_priority_max(SCHED_FIFO)      = 99
sched_setscheduler(20856, SCHED_FIFO, [88]) = 0
sched_get_priority_min(SCHED_FIFO)      = 1
sched_get_priority_max(SCHED_FIFO)      = 99
```

### Expected behaviour

Is it really that necessary to set such extreme realtime priorities to the main thread?

It might be common for IRQs of hardware peripherals (e.g. PCI ports and bridges), realtime audio tools (like `jackd` and DAWs) and others, but definitely not userspace chat applications, such as `telegram-desktop`.

This behavior can easily cause problems to any other realtime-dependent jobs (e.g. audio dropouts/XRUNs in environments that run `jackd`). Even processes like `jackd` are not started with realtime priorities by default and this is something that should be managed by users. In fact, none of the processes on my system are started with realtime priorities by default, unless I manually set them.

### Actual behaviour

telegram-desktop is spawned with FIFO scheduling policies process and a hard-coded default realtime priority of 88

### Operating system

Arch Linux (kernel: linux-rt)

### Version of Telegram Desktop

4.8.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
I guess it's the audio library (https://github.com/kcat/openal-soft) who changes the priority, if you think it shouldn't do that, feel free to report to it.

**Comment by alesandar** [comment]
@ilya-fedin, you are right, it was [kcat/openal-soft](https://github.com/kcat/openal-soft) indeed. Thank you for your fast response.

To anyone looking at this in the future, the issue can be resolved by disabling the `rt-prio` option in `~/.alsoftrc` by doing so:
```
[general]
rt-prio = 0
```
Note: I had to create the file manually on my system.

In my opinion, it would be nice for `tdesktop` to handle this, since `openal` is not packaged into it, right?
I will consult with the Open AL community to see what might be the right way to do so.

**Comment by ilya-fedin** [comment]
I don't think tdesktop can handle that
