### ISSUE TITLE
Telegram automatically declines calls from any account if at least one is already on call

### ISSUE THREAD

**Issue by oldwizard1010** [telegramdesktop/tdesktop#26329]
### Steps to reproduce

1. Start call or group call from one of your accounts
2. Try to call on your second account
3. Call automatically declines

### Expected behaviour

There should be popup for call acceptence , i have my phone, not only desktop and i can speak to more than one call simultaneously

Would be nice to be able to switch calls even on one account only, but at least for several accounts let it have popup

### Actual behaviour

Very frustrating if you are on a group call for work or whatever, and it just autodeclines every other call, and you can't even see this call, and in chat it appears as declined, not "Already on the phone", so whoever calls me just assumes, that i myself declined it, tries to call several times more and it looks like: "Declined Call, Declined Call, Declined Call..."
And i have no idea that a person tried to call me.

### Operating system

Manjaro Linux, KDE (unimportant, really)

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> ### Version of Telegram Desktop
> 
> 4.7.1

Current latest version is 4.8.1

**Comment by oldwizard1010** [comment]
4.8.1, same behaviour

**Comment by ilya-fedin** [comment]
Current latest version is 4.8.4
