### ISSUE TITLE
Video playback is not optimized, 2.5 times more CPU load than ext video player, overload low perfomance CPU and high battery discharge

### ISSUE THREAD

**Issue by khunpoum** [telegramdesktop/tdesktop#26323]
### Steps to reproduce

Play video in Telegram Desktop and SMplayer (or other external video player) and measure CPU load.

video specs example:

container MOV
Size: 31309 KB (30 MB)
Length: 00:00:38
Demuxer: lavf

Resolution: 1072 x 1920
Aspect ratio: 0.558333
Format: h264
Bitrate: 6345 kbps
Frames per second: 60.000000
Selected codec: h264

Format: aac
Bitrate: 54 kbps
Rate: 44100 Hz
Channels: 2
Selected codec: aac

### Expected behaviour

CPU load is not to much more than play video in any other external video player software.

### Actual behaviour

CPU usage during video playback in Telegram Desktop is 2.5 times higher than in external players
(for example smplayer). 
On slow performance CPU like SOC Intel Core i7-7Y75  (tablet pc Chuwi UBook XPro) it makes slideshow, throttling and high battery discharge.

### Operating system

Windows 11 21H2 build 22000.348

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Most video players use GPU to decode video, tdesktop project has no GPU experts and there's no one to implement it without bugs like green video, so tdesktop uses CPU.

**Comment by john-preston** [comment]
It can't be as effective as custom players right now because it still moves frames through RAM between decoding and rendering, while specialized players can decode on GPU straight to a GPU surface and render it. But you can try enabling hardware video decoding in Settings > Advanced, it should be better than without it. If it works.

**Comment by khunpoum** [comment]
Thanks. After enabling hardware video decoding in Settings > Advanced - its now much better. low battery discharge and have not CPU  throttling now on hard videos.
