### ISSUE TITLE
Message priority in the list and drop-down lists.

### ISSUE THREAD

**Issue by nfs911** [telegramdesktop/tdesktop#2632]
Make the message priority in the list. To chats, bots, groups with disabled notifications always placed at the bottom. Above, active notifications are also divided into 2 groups: people at the top and bots, chat, groups, channels at the bottom.
![2](https://cloud.githubusercontent.com/assets/23433847/20246162/05980734-a9c2-11e6-959d-c1d3470d0fdf.jpg)
I am looking forward drop-down lists (folders) for sorting.

thanks

**Comment by stek29** [comment]
Will #1107, #2440 and #2590 satisfy you?

**Comment by nfs911** [comment]
Perfect! I look forward! Close this Issue?
