### ISSUE TITLE
Fedora38 / Gnome44 / X11 mouse buttons lost after move telegram window

### ISSUE THREAD

**Issue by jonsito** [telegramdesktop/tdesktop#26325]
### Steps to reproduce

1- Start gnome session and open several windows
2- Start telegram-desktop app
3- Move or resize telegram window

### Expected behaviour

Mouse should continue working as usual

### Actual behaviour

Every time you move telegram windows, mouse buttons become mostly unresponsive.
Mouse cursor works, you can put other windows on top, but no action available: nor close, move, resize or select any item inside window. 

To restore behaviour, you must click on top right gnome control icon to display options, and then close this menu. 

Some time ago similar error was reported, With Fedora 37 everything worked fine, but after upgrade to latest Fedora and Gnome, error appears again

### Operating system

Fedora 38, Gnome 44 with Xorg session, telegram from rpmfusion-free repo

### Version of Telegram Desktop

telegram-desktop-4.8.1-2.fc38.x86_64

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
It's not really clear what happens from your description, please provide a screen record
