### ISSUE TITLE
Joxi screenshots are not autoparsed any more

### ISSUE THREAD

**Issue by staleo** [telegramdesktop/tdesktop#2633]
[Joxi](http://joxi.ru) is one of the public and free screeshot share services. 

### Steps to reproduce
1. Take a Joxi screenshot and wait a little once a screenshot link is in your buffer.
2. Paste a link to a Windows-run telegram chat window.

### Expected behaviour
Instead of just a link, the screenshots must also be parsed, and an actual picture should appear, just the way it actually used to be untill recently.

### Actual behaviour
There's just a link in a dialog, not a link together with a copy of the image.

### Configuration
Operating system: Windows 10
Version of Telegram Desktop: 0.10.19 alpha

**Comment by stek29** [comment]
There was a link and a preview with an image before?

**Comment by staleo** [comment]
Absolutely.

Joxi autoparsed screenshots disappeared probably 2, maybe 3 weeks ago.

**Comment by stek29** [comment]
Are you sure it's not Joxi's issue?
Can you provide any Joxi link?

**Comment by staleo** [comment]
e.g. http://joxi.ru/E5mdQwxhM4ZK21

**Comment by john-preston** [comment]
Currently the server uses canonical url if it is provided and joxi has

    <link rel="canonical" href="http://joxi.net/">

in it's head tag.

**Comment by stek29** [comment]
@john-preston so it just shows preview for `http://joxi.net` for any URL?
