### ISSUE TITLE
Not full screen on wayland with Nvidia driver

### ISSUE THREAD

**Issue by NgoHuy** [telegramdesktop/tdesktop#26332]
### Steps to reproduce

1. Open telegram-destop on sway with nvidia driver
2. click full screen, but screen is not full
3. choose system frame
4. see system frame filled the screen where is space previously

### Expected behaviour

Window should be full instead of right and bottom is space

### Actual behaviour

right and bottom are space and show background.

### Operating system

Archlinux

### Version of Telegram Desktop

4.8.1

### Installation source

Other (unofficial) source

**Comment by NgoHuy** [comment]
I added image here:
![image](https://github.com/telegramdesktop/tdesktop/assets/1238112/cb613d9a-3bcd-4895-a367-9c4ca75fe048)

**Comment by ilya-fedin** [comment]
> I added image here:

It's not really clear what the problem here

**Comment by NgoHuy** [comment]
It's maximized. On sway, all windows are maximized. But I got no problem on intel driver. The bug's recently.
On intel laptop, it showed as full screen, but on my PC, when I clicked maximized it still kept this size. When I checked use system border frame, it padded system frame and show as expected - full screen.
Here is image on intel laptop:
![image](https://github.com/telegramdesktop/tdesktop/assets/1238112/cb06d64c-2024-46a7-98eb-614d00984501)

**Comment by ilya-fedin** [comment]
> It's maximized.

No, it's definitely not maximized. That is, there are checks in the code for maximized state and in that state, there's no shadow and no corners rounding. The fact you have corners rounding/shadow means Qt thinks the window is not maximized what is likely caused by the fact the window is not actually maximized.

**Comment by NgoHuy** [comment]
I see, but when I clicked maximized button, it cannot be maximized as expected.
![image](https://github.com/telegramdesktop/tdesktop/assets/1238112/71409d91-fe7f-4bfd-969f-70f5b93a5f88)

But when I choose system frame, it padded and became maximized.
![image](https://github.com/telegramdesktop/tdesktop/assets/1238112/ebfb2db4-ce15-4ac0-a443-4c790564cb5a)
The bug only occured on sway with nvidia, not for kde with nvidia, on kde, it showed full screen.

**Comment by ilya-fedin** [comment]
Maybe your compositor forbids Telegram to maximize? It absolutely can do such a weird thing. I guess you have to report this to your compositor. Also, if there's a difference between NVIDIA and Intel, it also means there's likely a bug in the NVIDIA driver. Either way, tdesktop can't do anything here.

**Comment by ilya-fedin** [comment]
> it showed full screen

Also, fullscreen is yet another completely different window state. Windows don't have titlebars in such mode and occupy all the screen space, including panels.

**Comment by NgoHuy** [comment]
Not sure where is the bug, because same as nvidia, kde renders fine, previously sway rendered fine. I will dig more in QT log and provide info here. only Telegram has this problem, so strange.

**Comment by ilya-fedin** [comment]
I assume KDE allows maximized mode while Sway is not. It also sounds like NVIDIA somehow disregards the xdg_shell_set_window_geometry API. If it does that compositor-independent, on Plasma it should look like gaps when flipping the window to a side.

**Comment by NgoHuy** [comment]
New rebuild telegram and qt6 fixed problem today. Thank you for your support. The problem is on qt6 not telegram.
