### ISSUE TITLE
Telegram-desktop 4.8.2-55 does not run on Ubuntu 23.04

### ISSUE THREAD

**Issue by suprunchuk** [telegramdesktop/tdesktop#26336]
### Steps to reproduce

1. Telegram must be installed via the snap package manager.
2. Update the application to version 4.8.2-55-ge9787170d.
3. Launch the application.

### Expected behaviour

The application should start

### Actual behaviour

Nothing happens

### Operating system

Ubuntu 23.03

### Version of Telegram Desktop

telegram-desktop 4.8.2-55-ge9787170d, 4789

### Installation source

Snap

### Logs

telegram-desktop 
[ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
Ошибка сегментирования (образ памяти сброшен на диск)

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by suprunchuk** [comment]
> 

deleted the app from the snap package. now installed from the official website, everything works fine.
do you propose to abandon snap on ubuntu?

**Comment by Aokromes** [comment]
> > 
> 
> deleted the app from the snap package. now installed from the official website, everything works fine. do you propose to abandon snap on ubuntu?

or wait till they fix it.

**Comment by ilya-fedin** [comment]
You're using edge channel that gets commits from dev branch, such updates that render the application broken are expected.
