### ISSUE TITLE
Flatpak package does not follow default system cursor theme

### ISSUE THREAD

**Issue by guixxx** [telegramdesktop/tdesktop#26339]
### Steps to reproduce

1. Install the [Flatpak package of Telegram](https://flathub.org/apps/org.telegram.desktop)
2. Open the app

### Expected behaviour

Cursor theme should match system defaults.

### Actual behaviour

Cursor theme does not match system defaults.

### Operating system

Arch Linux

### Version of Telegram Desktop

4.8.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Please see #25126
