### ISSUE TITLE
Cannot build due to prepare.py error

### ISSUE THREAD

**Issue by junyussh** [telegramdesktop/tdesktop#26330]
### Steps to reproduce

1. Clone the source code
2. Install cmake and Python
3. Run `tdesktop\Telegram\build\prepare\win.bat`

### Expected behaviour

It should pass the prepare test, but it shows `[ERROR] Make sure to run from Native Tools Command Prompt.`. I don't know what "Native Tools Command Prompt" means, I ran the script in CMD.

To find out the certain error, I reviewed the `prepare.py`. I don't understand the code `if win and not 'Platform' in os.environ:`, because `os.environ` has no key `Platform`.
```
>>> os.environ['Platform']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen os>", line 679, in __getitem__
KeyError: 'Platform'
```

### Actual behaviour

```
[ERROR] Make sure to run from Native Tools Command Prompt.
FAILED
```

### Operating system

Windows 11

### Version of Telegram Desktop

dev@1d2a50c

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Have you read the build instruction? It clearly sates you should use Native Tools Command Prompt and instructs where to find it.

**Comment by junyussh** [comment]
I'm sorry about that. I didn't realize that Native Tools Command Prompt is a VS tool.
