### ISSUE TITLE
Enhancement: Emojis should be diplayed more detailed while hovering over them

### ISSUE THREAD

**Issue by kmel-de** [telegramdesktop/tdesktop#2634]
Emojis should be diplayed more detailed in 200% or 400% while hovering over them.
On a high-resolution display and interface scale of 100% the font size is ok and readable,
but emojis are appropriately downsized and difficult to recognize.
 
### Steps to reproduce
1. Put mouse pointer over an emoji.

### Expected behaviour
Tooltip displays the emoji in 200% or 400% size.

### Actual behaviour
Noting happens.

Telegram Desktop 0.10.19

**Comment by auchri** [comment]
#1321
