### ISSUE TITLE
bottom bar shows confusing/wrong sentence when a topic is locked

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#26344]
### Steps to reproduce

1. lock a topic
2. look at the bottom bar

### Expected behaviour

The bottom bar tells you that "the topic is closed" (like in mobile apps)

### Actual behaviour

tdesktop tells you "sorry, this group is not accessible", which is confusing: the group _is_ accessible (and the topic is too), but you can't post in that specific topic because it is closed

### Operating system

Windows 10

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
still bugged
