### ISSUE TITLE
"Hide Members" should not be a brarrier of usage for the group's members

### ISSUE THREAD

**Issue by t7yang** [telegramdesktop/tdesktop#26354]
### Steps to reproduce

1. enabled "Hide Members" on a big group (more than 100 members).
2. the members of the group can not get autocomplete list when trying to tag (`@`) a member in the group.

### Expected behaviour

the "Hide Members" is good, it should be prevent non-member to get the member list, but not decreasing the group's members chat usability.

### Actual behaviour

the group's members should have the same experience even when the admin enabled the "Hide Members" option.

### Operating system

windows/mac

### Version of Telegram Desktop

4.8.1 (windows)

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
i think this must be platform wide bugs / requests belongs to https://bugs.telegram.org/
