### ISSUE TITLE
Cannot clear history for Channels (in linux app)

### ISSUE THREAD

**Issue by thwerks** [telegramdesktop/tdesktop#26355]
### Steps to reproduce

open channel, click "clear history", see that there is no option to delete history.; only to enable auto deletion. 

accidentally pasted a large log file that somehow got broken up into hundreds of small messages. Now i can see there's no option on Linux Desktop app to delete history. Only on the phone has this option however it doesnt delete history from desktop obviously.  The desktop only has the option to enable auto-deletion, which doesnt work retroactively. So i have no way to delete all these messages except 1 by 1. arrrg 

![image](https://github.com/telegramdesktop/tdesktop/assets/90361336/470c8a02-c05c-497b-abfb-c5c4d872b8b2)

### Expected behaviour

be able to clear history when i click "clear history"

### Actual behaviour

cant clear anything. 

### Operating system

debian 12/ Cinnamon

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> it doesnt delete history from desktop obviously

It means it deletes the history locally but tdesktop doesn't have local storage and so it can't delete the history locally (it will be re-requested from the server on next start).

**Comment by thwerks** [comment]
So deleting the channel is the only way to remove the history? i can individually delete from channels on desktop, i can clear all on the phone app, i can clear all from a bot history in telegram desktop. This doesnt sound like a technical limitation at all; this is clearly a developmental oversight. 

Deleting the entire channel and recreating it just to clear the history in telegram desktop doesnt sound very reasonable.

**Comment by ilya-fedin** [comment]
All I say is implementing the feature you want requires implementing a way bigger lower-level feature (local message database) which there's no plan to implement AFAIK. After all, this clearing from mobile app is fake, the messages are still present on the server as you can see from tdesktop.

**Comment by thwerks** [comment]
well if you can individually delete then the can recursively delete, that is not lower level, somebody just forgot to do it.

**Comment by ilya-fedin** [comment]
One can't use individual delete API requests for bunch deletion, that would lead to FLOOD_WAIT error.

**Comment by thwerks** [comment]
I see what you mean, its possible to add some delay though between iterations; a half ass solution is better than nothing. I mean deleting the channel and recreating it just to remove the content is pretty unreasonable. But

**Comment by ilya-fedin** [comment]
I don't think that's permitted. I guess this could be implemented in an unofficial client but official clients can't implement something until the API is intended for such usage.
