### ISSUE TITLE
Linux - Profile pictures in full screen makes the app transparent

### ISSUE THREAD

**Issue by HardenedSteel** [telegramdesktop/tdesktop#26359]
### Steps to reproduce

1. Enable OpenGL rendering for media.
2. Go anyone's user info.
3. Click the profile picture.

### Expected behaviour

The app wouldn't be transparent. 

### Actual behaviour

The app becomes transparent and unable to view profile pictures properly.
![profilepicture](https://github.com/telegramdesktop/tdesktop/assets/19209715/530c9bc4-1dda-4b80-90a4-723be95c2b2c)

### Operating system

Linux Mint 21.1

### Version of Telegram Desktop

The issue started with 4.8.3 (4.8.1 is fine.)

### Installation source

Static binary from official website

### Crash ID

_N/A_

### Logs

```shell
# This error log may be related with the problem.
[2023.06.02 19:57:27] OpenGL: Allow on NVIDIA driver (experimental).
[2023.06.02 19:57:27] OpenGL: QOpenGLContext created, version: 4.4.
[2023.06.02 19:57:27] OpenGL: [TRUE] (Window)
[2023.06.02 19:57:30] RPC Error: request 100 got fail with code 400, error WEBFILE_NOT_AVAILABLE
```

### Notes
There's similar [issue](https://github.com/ValveSoftware/steam-for-linux/issues/9160) with Steam app. It seems the problem is related with Nvidia drivers.

**Comment by ilya-fedin** [comment]
I'm pretty sure this is NVIDIA bug and you have to report to NVIDIA. All the other drivers work just fine.

**Comment by HardenedSteel** [comment]
> I'm pretty sure this is NVIDIA bug and you have to report to NVIDIA. All the other drivers work just fine.

@ilya-fedin the problem started with new telegram update, not driver update.

**Comment by ilya-fedin** [comment]
Which one?

**Comment by HardenedSteel** [comment]
> Which one?

@ilya-fedin the problem started with 4.8.3 - 4.8.1 doesn't have the issue.

**Comment by ilya-fedin** [comment]
> the problem started with 4.8.3 - 4.8.1 doesn't have the issue.

What about 4.7.1? 4.8.0 and 4.8.1 had Qt built without Xlib and that was reverted due to #26228. Even if this somehow helps NVIDIA, this couldn't be done as @john-preston decided we should continue to support HIME. If you confirm 4.7.1, you have to ask NVIDIA to fix their GLX support or disable OpenGL, sorry.

**Comment by HardenedSteel** [comment]
> > the problem started with 4.8.3 - 4.8.1 doesn't have the issue.
> 
> What about 4.7.1? 4.8.0 and 4.8.1 had Qt built without Xlib and that was reverted due to #26228. Even if this somehow helps NVIDIA, this couldn't be done as @john-preston decided we should continue to support HIME. If you confirm 4.7.1 doesn't work as well, you have to ask NVIDIA to fix their GLX support or disable OpenGL, sorry.

@ilya-fedin yes, there's same issue with 4.7.1, thanks for help.

**Comment by HardenedSteel** [comment]
Disabling FXAA from Nvidia settings fixed the problem. 

Related comment. https://github.com/alacritty/alacritty/issues/1059#issuecomment-757494585
