### ISSUE TITLE
Linux App undesirable install behavior or bug?

### ISSUE THREAD

**Issue by thwerks** [telegramdesktop/tdesktop#26356]
### Steps to reproduce

After downloading the official linux app binary; after extraction i double click the Telegram binary and application opens. Apparently this sorta "installs" the app by creating a application menu entry. Unfortunately it creates a menu entry that points to what is most likely the going to be the telegram binary in the users Downloads folder. 

This is ambiguous behavior, who in their right mind is going to assume an installation process takes place in reference to right where the file lies? I have never seen that behavior in my entire life, its not bad but it catches you completely off guard. I'm now having customers who load the app then delete the telegram folder in their downloads , rightfully assuming its no longer necessary (because of the apparent installation) only to find telegram has then disappeared.  

The file should be automatically placed into somewhere like /usr/bin folder and then execute or have a proper installer. Either way, at present it only leads to confusion and wasted time. 

### Expected behaviour

should either ask the user if they want to install or run portable or place the file into the /usr/bin folder prior to creating application menu entries .

### Actual behaviour

app creates application menu entries pointing to the /home/user/Downloads folder 

### Operating system

Debian 11 and 12

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I don't know what was original intention to behave like that (only @john-preston knows) but I guess it's meant to not to present scary insallation dialogs and (worse!) require a password to copy itself to /usr/bin (and I guess no one here knows the API to call such a dialog on Linux). Yet you can't talk to system APIs not having app ID (which is represented in the form of a shortcut in application list on both Windows and Linux). On Windows you can't have native notifications without app ID, you can't pin the app to taskbar reliably (the second is still broken as currently the app registers the app ID on Windows only when enabling native notifications, #4346, hope this will be moved to startup code like done on Linux). On Linux this is way worse: native notifications require it, mpris requires it, `tg://` handler requires it, taskbar icon requires it, the counter on taskbar icon requires it.

I don't think tdesktop wants to install itself, I don't think tdesktop wants to bother the user with any dialogs (this is my guess though, only @john-preston knows for sure) yet it can't work as intended without the shortcut due to system API restrictions.

**Comment by thwerks** [comment]
I kind figured this might be the case and i completely understand. I will make a wrapper for it and host the file myself for distribution within my circle. Though being asked for a password during installation is the status quo; and having a single prompt asking to install the file into /usr/bin or to run as portable would only be an advantage.  Thanks for the reply.

**Comment by ilya-fedin** [comment]
> and having a single prompt asking to install the file into /usr/bin

I see two problems here:
1. @john-preston might not like this. He usually prefers not to add interrupting dialogs and additional options.
2. It's not known how to spawn such a dialog.

**Comment by rossnomann** [comment]
JFYI: instead of `/usr/bin` you can consider `$HOME/.local/bin`

**Comment by thwerks** [comment]
> JFYI: instead of `/usr/bin` you can consider `$HOME/.local/bin`

that's a very good suggestion; count me for that one.

**Comment by ilya-fedin** [comment]
I'm not sure installation feature is planned... @john-preston seem to have no time to comment on this one.

**Comment by thwerks** [comment]
The behavior of appimages or regular bins is to just run in place. This is already a quasi installer as its creating menu entries, etc, but its behavior is ambiguous or otherwise unpredictable; it leads to confusion and wasted time. Mass deployments should take care to avoid this scenario.  Either it should copy itself to an appropriate location (like $HOME/.local/bin) automatically or prompt the user to do so and then proceed with creating a shortcut. 

Having a permanently created appmenu entry that's pointed to a temporary location like the Downloads folder will only lead to confusion.  Not every linux user is on the watch-out or knows how to deal with programs doing spontaneous things like that, so easily this can be avoided.

**Comment by ilya-fedin** [comment]
> Mass deployments should take care to avoid this scenario.

Well, it's meant to be used by ordinary users, not for mass installations I believe... I don't think mass deployment use-case is supported and I'm not sure there's a will to support it.

> it leads to confusion and wasted time.

So far this was convenient for ordinary users and there were multiple issues with thanks for such simple approach.

**Comment by thwerks** [comment]
by  "mass deployment" i mean the thousands or even millions of regular individuals who are using this application all over the work. It already is a mass deployment, im not talking about a corporate roll-out or whatever your referring to.

The feedback im giving you comes directly from friends and family who just switched to telegram and running into the problem of downloading the app, running it, seeing its installed then deleting it from the downloads folder., then the mess insures. I'm not pulling hypothetical nonsense out of my ass because i have nothing better to do.

**Comment by ilya-fedin** [comment]
Well, maybe there should be a README in the archive with instruction to extract in the home directory and not delete...
