### ISSUE TITLE
After the Telegram update, a huge part of the functionality stopped working

### ISSUE THREAD

**Issue by kynya00** [telegramdesktop/tdesktop#26358]
### Steps to reproduce

1
1.1. update telegram to version 4.8.3
1.2. open any link

2
2.1. open private chat
2.2. try hovering over "View Profile"
(before hover, the "mute notification" menu will drop out and disappear after)

3
3.1. try to open the file via "right mouse button" -> "Open Folder" -> Crash

### Expected behaviour

1. opening a link in a browser
2. the ability to edit the dialogue
3. opening the explorer where the file is located

### Actual behaviour

1. telegram desktop freezes, but if you close telegram, the link will open in the browser (and memory leak).
2. the window disappears
3. crash

### Operating system

Debian GNU/Linux 11 (bullseye), gnome 3.38.5, Wayland

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

### Crash ID

a3c7466a-de59-450e-e92e86b6-3d37a72d

### Logs

```shell
dmesg:
[  696.254545] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-org.telegram.desktop._8ea5ebc64b9a23d3ff91535411caf725-3917.scope,task=Telegram,pid=3917,uid=1000
[  696.254663] Out of memory: Killed process 3917 (Telegram) total-vm:8157112kB, anon-rss:5634124kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:14428kB oom_score_adj:0
[ 1052.280945] Telegram[7027]: segfault at 0 ip 0000000002f69053 sp 00007ffebdf534c0 error 4 in Telegram[727000+60b4000]
[ 1052.280954] Code: 49 8b 06 48 8b 40 40 48 39 d0 75 7b 49 8b 46 08 48 8b 40 08 8b b0 90 01 00 00 48 8d 05 06 3c 4e 01 48 39 c3 75 59 49 8b 7d 58 <48> 8b 07 ff 90 08 01 00 00 48 8b 9d c8 fe ff ff 31 f6 48 89 df e8
[ 1215.927985] Telegram[8121]: segfault at 0 ip 0000000002f69053 sp 00007ffdc0b81d00 error 4 in Telegram[727000+60b4000]
[ 1215.927997] Code: 49 8b 06 48 8b 40 40 48 39 d0 75 7b 49 8b 46 08 48 8b 40 08 8b b0 90 01 00 00 48 8d 05 06 3c 4e 01 48 39 c3 75 59 49 8b 7d 58 <48> 8b 07 ff 90 08 01 00 00 48 8b 9d c8 fe ff ff 31 f6 48 89 df e8
[ 1528.395280] Telegram[8645]: segfault at 0 ip 0000000002f69053 sp 00007fff5f535440 error 4 in Telegram[727000+60b4000]
[ 1528.395288] Code: 49 8b 06 48 8b 40 40 48 39 d0 75 7b 49 8b 46 08 48 8b 40 08 8b b0 90 01 00 00 48 8d 05 06 3c 4e 01 48 39 c3 75 59 49 8b 7d 58 <48> 8b 07 ff 90 08 01 00 00 48 8b 9d c8 fe ff ff 31 f6 48 89 df e8
[ 1556.130854] Telegram[9760]: segfault at 0 ip 00000000066e0dfd sp 00007ffd849eb9c0 error 4 in Telegram[727000+60b4000]
[ 1556.130862] Code: 79 88 04 fa 66 0f 1f 84 00 00 00 00 00 41 57 41 56 53 48 83 ec 10 48 89 f3 49 89 ff 64 48 8b 04 25 28 00 00 00 48 89 44 24 08 <48> 8b 06 25 ff 0f 00 00 48 8d 0d 74 e9 0f 03 4c 8b 34 c1 31 c9 4c
_______________________________
```
UPD: Uncommenting this line helped
$ **sudo nano /etc/gdm3/daemon.conf**
[daemon]
Uncomment the line below to force the login screen to use Xorg
**WaylandEnable=false**
OS: Debian GNU/Linux 11 (bullseye), gnome 3.38.5, X11

**Comment by ilya-fedin** [comment]
sounds like a dup of #26357
