### ISSUE TITLE
Record the health statistics of proxies and sort/remove them by these statistics when they become unavailable

### ISSUE THREAD

**Issue by anotherCrazyGeek** [telegramdesktop/tdesktop#26352]
### Is your feature request related to a problem?

In real life, on the devices of **real proxy users** (i.e. not the software testers at Telegram company), proxy lists contain thousands of dead proxies, and every healthy proxy becomes available/unavailable by internet service providers every 1-2 minutes once (~30 seconds each time), and its availability status becomes switched, frequently.

But users mostly think any unavailable proxy is dead. They cannot distinguish dead proxies from healthy unavailable ones (proxies which are temporarily unavailable for a few seconds).
When users try removing dead proxies manually, they **mistakenly** delete healthy unavailable ones, too.
User decisions are mostly wrong when **too many healthy proxies become temporarily unavailable at the same time** by the ISP.

### Describe the solution you'd like

The solution is mentioned in this comment: https://github.com/telegramdesktop/tdesktop/issues/26347#issuecomment-1567812229
As suggested in that comment, recording the number of failures and successes of each proxy, the latest time when the proxy has passed a ping test successfully (Last Availability Time), and other statistics for the health status of each proxy, then, creating a smart removal feature which distinguishes and deletes unavailable proxies which are more likely to be dead, but lets other unavailable proxies remain undeleted.
For example, a batch proxy removal button, or an option for auto proxy removal, to make removal decisions smarter, decreasing the number of mistaken killed proxies, and easing the job for the user.

### Describe alternatives you've considered

There's also an easier alternative solution for such a smart removal feature which doesn't need to save any history or statistics of proxies on the disk. Therefore, its implementation is much easier for you too (the screenshot is from an Android app but it helps explaining the context):
![image](https://github.com/telegramdesktop/tdesktop/assets/134981060/54364eb9-ac01-4624-847c-384cc6591977)
This alternative solution has been suggested in https://github.com/telegramdesktop/tdesktop/issues/26347
But as suggested in https://github.com/telegramdesktop/tdesktop/issues/26347#issuecomment-1567812229 and the linked Telegram chats, there's a downside to this alternative solution: Its decisions are not 100% precise.
But IMHO, it almost solves the problem and decreases mistaken removals by 90%

None of these two issues have provided a 100% precise solution but each of them is better than user decisions in manual removal. Users cannot distinguish dead proxies from other unavailable proxies at all, so they are always killing healthy proxies (because all healthy proxies become available/unavailable temporarily every 1-2 minutes, for example (30 seconds each time).

**Comment by ilya-fedin** [comment]
There are a lot of issues when searching the word [proxy](https://github.com/telegramdesktop/tdesktop/issues?page=1&q=is%3Aissue+is%3Aopen+proxy). I believe this issue duplicates multiple issue at once, e.g. #25662, #25971 and I guess a lot of others and the list (which probably also duplicate each other a lot as not every issue is checked and their titles seem to be very similar).

**Comment by anotherCrazyGeek** [comment]
> There are a lot of issues when searching the word [proxy](https://github.com/telegramdesktop/tdesktop/issues?page=1&q=is%3Aissue+is%3Aopen+proxy). I believe this issue duplicates multiple issue at once, e.g. #25662, #25971 and I guess a lot of others in the list (which probably also duplicate each other a lot as not every issue is checked and their titles seem to be very similar).

Lets compare your mentioned issues with mine:
1. https://github.com/telegramdesktop/tdesktop/issues/25662
The author of the mentioned issue has asked for sorting **"available proxies"** (not the unavailable ones), while in my issue, I've asked to save the last availability time and health history for sorting **"unavailable proxies"** so this data can be used for removal decisions, later.
Furthermore, in the mentioned issue, the author has not suggested anything about the **"history of proxies"**. The author asked to sort proxies by their **"current status"** only, and ignoring their history.
It cannot solve the problem which I have explained here at all. These two issues are not identical at all.
2. https://github.com/telegramdesktop/tdesktop/issues/25971
In my issue, I didn't ask to hide **"dead proxies"**. There's **no reason for hiding** them. I asked you to delete them. After adding my suggested feature, and deleting dead proxies, then you can add the feature which has been suggested in the mentioned issue, and after doing this, **"healthy unavailable proxies"** (not the "dead proxies") will become hidden at the times when they are asleep or being checked, and they will become visible again when they wake up again. There's **no reason for deleting** them.
These two issues are not identical. Furthermore, they are not even two different alternative solutions to a common problem. The two issues are solving two completely different problems and both of them are needed at the same time.

The only similar issue to my issue, is my earlier issue (https://github.com/telegramdesktop/tdesktop/issues/26347). these two issues are actually alternatives to each other, and solving a common problem (though, still different)

**Comment by anotherCrazyGeek** [comment]
And to be honest, I didn't want to write this issue.
But someone has commented and suggested a better solution to the problem which I have explained in my earlier issue (https://github.com/telegramdesktop/tdesktop/issues/26347). Therefore, I have wrote his suggestion as another issue.

**Comment by anotherCrazyGeek** [comment]
Also https://github.com/telegramdesktop/tdesktop/issues/5028 maybe similar to mine.
But it is not.
They have asked for a button to delete all unavailable proxies.
I have asked to deleted only proxies which are potentially dead, and leaving other unavailable ones.

**Comment by ilya-fedin** [comment]
> 1. sorting unavailable proxies



> 2\. I asked you to delete them

Sounds very similar to #25975

**Comment by anotherCrazyGeek** [comment]
> Sounds very similar to #25975

Yes, you are completely right about this one. Sorry! I didn't notice this issue.
Tell me to close mine, or please close one of these two issues, yourself. thanks.
