### ISSUE TITLE
bug with renaming contact

### ISSUE THREAD

**Issue by 221V** [telegramdesktop/tdesktop#26363]
### Steps to reproduce

1. rename contact in telegram desktop on linux
2. enable internet (wifi) on mobile (android) and chat to somebody, disable internet on mobile after that
3. see how contact in telegram desktop on linux returns to previous name -- like you was not rename in 1.

so what the f**k ?
why telegram desktop no allow to rename contact?

### Expected behaviour

expected -- telegram desktop allow to rename contact

### Actual behaviour

actual -- telegram desktop disallow to rename contact

### Operating system

(l)ubuntu 22.04 LTS, android 10 QKQ1.191014.001 - MIUI Global 12.5.2.0

### Version of Telegram Desktop

4.8.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Maybe it's Android client renames it back?

**Comment by 221V** [comment]
> Maybe it's Android client renames it back?

but why this does??
this is unexpected behavior, this is bug!
server side telegram has bug!

**Comment by ilya-fedin** [comment]
This bug tracker is only for tdesktop issues, not for Android issues or server-side issues

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by 221V** [comment]
> This bug tracker is only for tdesktop issues, not for Android issues or server-side issues
i got this bug using desktop telegram app!

> platform wide bugs / requests belongs to https://bugs.telegram.org/
please do not say me "f**k off, this is not our problem"!
please show this bug report to somebody who can fix this telegram bug!

thank you!
