### ISSUE TITLE
It is too bad that Docker base file of tdesktop is centos7

### ISSUE THREAD

**Issue by mozbananagift** [telegramdesktop/tdesktop#26364]
### Is your feature request related to a problem?

It is too bad that Docker base file of tdesktop is cents7

when I want to extend docker container and install some new features it is not possible
if you change base machine to debian11 or ubuntu22 (latest)
we can do many things

please change this:
FROM centos:7 AS builder-base
to
FROM ubuntu:22.04 AS builder-base

### Describe the solution you'd like

please change this:
FROM centos:7 AS builder-base
to
FROM ubuntu:22.04 AS builder-base

only this and other related commands

### Describe alternatives you've considered

ubuntu22.04 or debial11 is very good for base image of docker

**Comment by ilya-fedin** [comment]
I had a very bad experience with Ubuntu as a base... CentOS has way more modern compilers. Note that if building with Ubuntu, one can't use a version newer than 14.04 as that would raise minimal supported OS which is no-go.

I don't think this should be changed, sorry. CentOS gives the best experience to developers right now.

**Comment by mozbananagift** [comment]
You Can USE DEBIAN11 as Base. It is too good.

**Comment by ilya-fedin** [comment]
It has too new glibc, a binary built on such distro won't run on Ubuntu 14.04

**Comment by mozbananagift** [comment]
but centos7 is too old and a lot of docker applications is based on newer os such as debian11. for example I want to use AFLplusplus on tdesktop docker but unfortunately it is based on ubuntu22.0.4 and e.t.c

**Comment by mozbananagift** [comment]
a lot of applications need llvm11 or newer. could you install llvm15 on cent0s7 ??? !!!
could you? I think no

**Comment by ilya-fedin** [comment]
Yeah, backward compatibility comes with price. Yet it has decided it must be preserved at any cost. It will be very bad if a lot of people will get a broken binary after update.

**Comment by mozbananagift** [comment]
Yes.
so please please please create two Dockerfile;
one based on centos7|
and
another one based on debian:latest or ubuntu:latest

**Comment by ilya-fedin** [comment]
Why? Only the CentOS one will be used anyway.

**Comment by mozbananagift** [comment]
a lot of applications need llvm11 or newer. could you install llvm15 on cent0s7 ??? !!!
could you? I think no

If you change the base of tdesktop to debian:latest or ubuntu:latest so we can add a lot of things to it dockerfile

**Comment by ilya-fedin** [comment]
I'm not sure how 'a lot of applications' are related here, tdesktop builds just fine with gcc 10. And I'm not sure which 'a lot of things' you want to add, the image is already too big for GItHub Actions, it should be shrunk, not enlarged.
