### ISSUE TITLE
virtual webcam

### ISSUE THREAD

**Issue by constantinsobolev7891** [telegramdesktop/tdesktop#26362]
### Is your feature request related to a problem?

virtual camera doesn't work in the latest release. 

### Describe the solution you'd like

bring it back! I guess I am not the only who uses virtual usb camera for streams on Telegram. that's a huge issue. will you change it?

### Describe alternatives you've considered

That would be an awesome thing if brought back the usb virtual camera support

**Comment by nyakze** [comment]
I use OBS Virtual Camera and it works just fine on W11 22H2, Telegram 4.8.10 x64. I'm not sure what do you mean.
