### ISSUE TITLE
Telegram doesn't respect title bar accent color settings on Windows 11 (take 2)

### ISSUE THREAD

**Issue by joric** [telegramdesktop/tdesktop#26369]
### Steps to reproduce

Same as in #25263

### Expected behaviour

Same as in #25263

### Actual behaviour

Same as in #25263

There's been a "workaround" to run telegram in Windows 8 compatibility mode to fix this regression (title bar color) on Windows 11, but it crashes Chrome on launch if links are opened from Telegram so it's not 100% acceptable.

The ticked was closed and supressed for no good reason. I personally wholeheartedly hated the non-system window frame on Telegram Desktop (makes it look like mp3 players from 90s) and was very glad when you added this feature for Windows 10 and losing it again in Windows 11 makes me sad. Could you please reconsider it and fix this regression? cc @ilya-fedin @bviktor.

### Operating system

Windows 11

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by joric** [comment]
At least I still can comment here :) @bviktor have you tried fixing it in code besides setting compatibility mode to Windows 8? Figures compatibility mode somehow crashes Chrome on launch when opening the links from Telegram.

**Comment by bviktor** [comment]
Nah, I'll most likely downgrade my comps to Win10 lol... this is being just one of the several reasons.

**Comment by joric** [comment]
@bviktor found it! It's not in the tdesktop repository but it's the same team, https://github.com/desktop-app/lib_ui here:

* https://github.com/desktop-app/lib_ui/blob/83cab52cd6ba93e9292405b23358d8dde3f95567/ui/platform/win/ui_window_win.cpp#L723

I guess the solution is literally just remove these 3 lines in updateWindowFrameColors:

```cpp
void WindowHelper::updateWindowFrameColors(bool active) {
	if (!::Platform::IsWindows11OrGreater()) {
		return;
	}
... // rest of the code
```

It's called from here:

* https://github.com/desktop-app/lib_ui/blob/83cab52cd6ba93e9292405b23358d8dde3f95567/ui/platform/win/ui_window_win.cpp#L243

```cpp
void WindowHelper::setNativeFrame(bool enabled) {
	if (!::Platform::IsWindows8OrGreater()) {
		window()->windowHandle()->setFlag(Qt::FramelessWindowHint, !enabled);
		if (!enabled) {
			FixAeroSnap(_handle);
		}
	}
	_title->setVisible(!enabled);
	if (enabled) {
		_shadow.reset();
	} else {
		_shadow.emplace(window(), st::windowShadowFg->c);
		_shadow->setResizeEnabled(!fixedSize());
		initialShadowUpdate();
	}
	updateMargins();
	updateWindowFrameColors();
... // rest of the code
```


It happened in this commit 2 years ago:

* https://github.com/desktop-app/lib_ui/commit/a827d9436e9ca258dfdfb9b67ef1ad917c13c5b5

**Comment by joric** [comment]
@bviktor nope, I havent really tried it before and it takes an eternity to build (2+ gigs of sources) and Qt apparently has banned my IP from downloading, besides you need your personal api_id and api_hash to build the app so it doesn't really make much sense to distribute your binaries https://github.com/telegramdesktop/tdesktop/blob/dev/docs/api_credentials.md

**Comment by ilya-fedin** [comment]
The scripts download Qt from github, has github banned your IP?

**Comment by joric** [comment]
Yeah, Qt banned Russia a while ago. it's https://master.qt.io in win.bat:
```--------------------------------------------------------------------------------
iwr : Download from your IP address is not allowed
At line:1 char:1
+ iwr -OutFile ./jom.zip https://master.qt.io/official_releases/jom/jom ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
[5/26](ThirdParty/jom): FAILED
FAILED```

**Comment by ilya-fedin** [comment]
You can download the jom archive by copying the link to Telegram and sending it

**Comment by joric** [comment]
@bviktor @ilya-fedin Ok I've managed to build it.

My initial assumption was wrong. That piece of code is actually only called ONLY on Windows 11. Note the condition

```cpp
	if (!::Platform::IsWindows11OrGreater()) {  // if it's NOT windows 11 then exit
		return;
	}
```

```cpp
void WindowHelper::updateWindowFrameColors(bool active) {
	if (!::Platform::IsWindows11OrGreater()) {
		return;
	}
	const auto bg = active
		? _title->st()->bgActive->c
		: _title->st()->bg->c;
	COLORREF bgRef = RGB(bg.red(), bg.green(), bg.blue());
	DwmSetWindowAttribute(
		_handle,
		kDWMWA_CAPTION_COLOR,
		&bgRef,
		sizeof(COLORREF));
	const auto fg = active
		? _title->st()->fgActive->c
		: _title->st()->fg->c;
	COLORREF fgRef = RGB(fg.red(), fg.green(), fg.blue());
	DwmSetWindowAttribute(
		_handle,
		kDWMWA_TEXT_COLOR,
		&fgRef,
		sizeof(COLORREF));
}
```

So the patch would be actually removing this code altogether, or adding a return, like this:

```diff
diff --git a/ui/platform/win/ui_window_win.cpp b/ui/platform/win/ui_window_win.cpp
index 53c0068..e53e87f 100644
--- a/ui/platform/win/ui_window_win.cpp
+++ b/ui/platform/win/ui_window_win.cpp
@@ -720,6 +720,7 @@ void WindowHelper::updateWindowFrameColors() {
 }

 void WindowHelper::updateWindowFrameColors(bool active) {
+       return; // system frame, always use default colors
        if (!::Platform::IsWindows11OrGreater()) {
                return;
        }
```

This function is only responsible for the system frame. I checked it and the patch doesn't break themes for the custom drawed caption, and it keeps the system frame consistent to system colors automatically (system takes care of it, it doesn't need to be set manually). 

I don't think this patch is usable for the official repository though. The real way would be removing all `updateWindowFrameColors` calls altogether (they are only responsible for the system frame) or guarding function body with another setting, so it would not be called in case if you "take accessibility/usability into account". But without the patch it would always paint system frame with predefined colors from the current Telegram theme for no good reason.

My fork of lib_ui has release Telegram binary with this patch for testing, prebuilt with test API keys. direct link:

* https://github.com/joric/lib_ui/releases/download/joric-win11-fix/Telegram.exe.7z

**Comment by ilya-fedin** [comment]
> The real way would be removing all `updateWindowFrameColors` calls altogether

@john-preston said in the previous discussion that he won't accept titlebar colored not in harmonic with the rest of tdesktop, so such patch won't be accepted. If you want titlebar to use system colors, you have to implement code for tdesktop to use system colors application-wide what in turn will lead updateWindowFrameColors to set the colors you want.

**Comment by ilya-fedin** [comment]
Well, the frame is still rendered by the system and the system allows to customize the color

**Comment by joric** [comment]
That's exactly what the patch does, lets system chose the frame color for the system frame. Custom draw frame is intact,

**Comment by ilya-fedin** [comment]
I mean the system allows the application to customize the color on the system frame. The frame is still the system one even though it matches the app color.

**Comment by ilya-fedin** [comment]
Well, it's you don't understand that the setting is meant to switch who draws the frame: tdesktop itself or the system. It does that, so it works as intended, even though you don't like the design choice for the window to look in the same design with the same colors. There's even work to make system titlebar to not to draw window icon and window label, not pushed yet though. But it could be pushed at some time and system titlebar will even more match the intended design just like the custom one does.

No one will allow you to break the design of the official application, you either have to contribute it without breaking the look between different parts of the window (that is, the whole window content should follow the system color scheme) or you have to create a fork.

**Comment by ilya-fedin** [comment]
> And the app doesn't HAVE to know.

btw, I disagree on this one. Either the application completely transits between color or it doesn't do that at all, even in the titlebar, as it's a part of application's window/

**Comment by bviktor** [comment]
That's exactly why I said you don't understand what the problem is. Anyway, unsubbing from future notifications, as you indicated on several occasions that you don't care either.

**Comment by ilya-fedin** [comment]
Yes, I don't understand why titlebar should change the color automatically while the rest of the window shouldn't

**Comment by ilya-fedin** [comment]
No, it works as intended on Windows 11. Windows 10 and older just have no such API.

**Comment by ilya-fedin** [comment]
The designers apparently think in-window consistency makes the usability better. What they provide on mockups, will be in the application. Not what you personally want, unfortunately.

**Comment by joric** [comment]
I think this is bad UX and it at least should have its own toggle.

**Comment by ilya-fedin** [comment]
The designers don't seem to agree with you or they wouldn't provide such mockups in first place :man_shrugging:

**Comment by joric** [comment]
Could we maybe check if display setting ("Show accent color on Title bars and window borders") is enabled in the registry (HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorPrevalence) and paint (or not paint) the caption accordingly. Would you accept a patch like this?

**Comment by joric** [comment]
Looks like python patch works on today's 4.8.5 as well.
