### ISSUE TITLE
No sound when playing videos on desktop on Win 10

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#26365]
### Steps to reproduce

Just playing videos anywhere in multiple groups, nothing & it was working before. I think the update has something to do with this.

I can hear VMs (mine & other people's) & everything else on my computer. 

### Expected behaviour

Sound LOL

### Actual behaviour

It's playing the video, just no sound & my settings are fine, I never changed anything, but like I said, there was an update the other day, right?

### Operating system

Win 10

### Version of Telegram Desktop

4.83

### Installation source

Static binary from official website

### Logs

```shell
Sorry, I don't know what to do here.
```

**Comment by Aokromes** [comment]
tried a random file and worked for me.

**Comment by ILoveSkilledCoders** [comment]
So my website coder helped me, although I figured it out. 

With the new update, did you guys default it so that all videos are muted now & you have to click on the X to unmute it?

It was never like that before. 

And why isn't the most recent update listed here? https://desktop.telegram.org/changelog
