### ISSUE TITLE
Linux App multiple issues since update to version 4.8.3

### ISSUE THREAD

**Issue by jitclub** [telegramdesktop/tdesktop#26367]
### Steps to reproduce

Install Telegram Desktop for Linux from Telegram website, launch installer, start application. Clicking on any http link in any group or channel, doesn´t open the corresponding link in default browser since automatic update to version 4.8.3. Some profile pictures of groups and channels don´t load, generally the application seems to be lagging.

### Expected behaviour

Hypertext links should open in the default browser. Profile pictures of groups and channels should be displayed.

### Actual behaviour

Clicking on any http link in any group or channel, doesn´t open the corresponding link in default browser since automatic update to version 4.8.3. Some profile pictures of groups and channels don´t load, generally the application seems to be lagging.

### Operating system

Debian GNU/Linux 11 (bullseye)

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#26357
