### ISSUE TITLE
cannot build docker file Error: building at STEP "RUN git clone -b v5.2.5 https://git.tukaani.org/xz.git 	&& cd xz 	&& cmake -GNinja -B build . -DCMAKE_BUILD_TYPE=None 	&& cmake --build build --parallel 	&& DESTDIR="/usr/src/Libraries/xz-cache" cmake --install build 	&& cd .. 	&& rm -rf xz": while running runtime: exit status 1

### ISSUE THREAD

**Issue by gmankab** [telegramdesktop/tdesktop#26368]
### Steps to reproduce

`poetry run gen_dockerfile | DOCKER_BUILDKIT=1 docker build -t tdesktop:centos_env -`

### Expected behaviour

succesfull build

### Actual behaviour

https://pastebin.com/G8imWjXZ

### Operating system

fedora 38

### Version of Telegram Desktop

i dont know

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Looks like something is wrong with your docker it discards the SHELL command that is essential:
```
WARN[0228] SHELL is not supported for OCI image format, [bash -c . /opt/rh/rh-python38/enable; . /opt/rh/devtoolset-10/enable; exec bash -c "$@" -s] will be ignored. Must use `docker` format 
```

**Comment by gmankab** [comment]
```
➜  ~ docker -v
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman version 4.5.0
```

i have no idea how to fix it

**Comment by ilya-fedin** [comment]
Apparently by removing podman and installing the real docker

**Comment by gmankab** [comment]
ok thanks
