### ISSUE TITLE
Audio playback doesn't work right with two or more audio devices on Windows 10

### ISSUE THREAD

**Issue by nfxpnk** [telegramdesktop/tdesktop#2637]
For an example I have two audio playback devices on my pc
- standart speakers with audio jack
- logitech usb headset

### Steps to reproduce
1. Open Telegram
2. Set speakers as a default device
3. Play music
4. Change default audio device to usb headset
5. Play music

### Expected behaviour
Sound should be played on usb headset

### Actual behaviour
Music is still on speakers

### Configuration
**Operating system:**
Windows 10.0.14393 N/A Build 14393
Bug is reproducable on previous versions also

**Version of Telegram Desktop:**
v 0.10.16

**Comment by stek29** [comment]
Please search for existing issues.

**Comment by nfxpnk** [comment]
@stek29 i did a search but not deep enough
i see now that it's known issue/bug
#418, #2561
but it isn't fixed yet
sorry for a duplicate
