### ISSUE TITLE
Cannot enter accented characters

### ISSUE THREAD

**Issue by luporr** [telegramdesktop/tdesktop#26379]
### Steps to reproduce

When using the German E1 keyboard layout with accented characters (https://www.europatastatur.de/e1.html), it is not possible to input them. 

### Expected behaviour

Inputting accented characters by first hitting a dead key and then typing in the base letter. Inputting special characters such as @ and € by hitting the key combination.

### Actual behaviour

Pressing a dead key and then the character to be accented does nothing. Pressing the dead key multiple times sometimes (but not for all dead keys) produces the accent without any base letter. Also inputting € and @ which are available via key combo on German keyboards (without dead keys) only works after repeatedly pressing the key combination. This does only happen in Telegram, not in any other application.

### Operating system

Windows 10 and 11

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> any other application

Is any of those 'other' applications based on Qt 5 as Telegram?

**Comment by luporr** [comment]
There is nothing coming to my mind immediately. Do you have anything in mind? I’ll gladly try it out.

**Comment by luporr** [comment]
Whoops, misclicked.

There is nothing immediately coming to my mind. Do you have any specific application I should try?

**Comment by ilya-fedin** [comment]
qBittorrent (the one built with Qt 5, not Qt 6)

**Comment by luporr** [comment]
Input fields in qBittorrent (Qt 5) seem to work normally. I can input accented characters the way I would expect to.

**Comment by luporr** [comment]
Has the same behaviour as the compose message field.
