### ISSUE TITLE
Crash when connecting to a scheduled broadcast on Linux

### ISSUE THREAD

**Issue by suprunchuk** [telegramdesktop/tdesktop#26374]
### Steps to reproduce

1. Find a channel with a scheduled broadcast.
2. Connect to the broadcast waiting.

### Expected behaviour

The broadcast waiting window should open

### Actual behaviour

After clicking the attach button, the application will crash

### Operating system

Ubuntu 23.04

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

### Crash ID

917d07ce-8afe-4be5-d426e687-adab33d5

### Logs

```shell
ApiId: 2040
Assertion: "_settings != nullptr" calls_group_panel.cpp:2240
Binary: Telegram
Launched: 05.06.2023 15:49:07
OpenGL: Enabled
OpenGL Renderer: Mesa Intel(R) HD Graphics 520 (SKL GT2)
Platform: Linux
Version: 4008003

Caught signal 6 (SIGABRT) in thread 140427788758464
Google Breakpad caught a crash, minidump written in thread 140427788758464
Minidump: /home/...
```

**Comment by john-preston** [comment]
Is there such channel already? It looks like this might happen with a scheduled rtmp livestream, but I don't see a way to make such.

I tried to reproduce on my own channel and couldn't. Can you provide a way to reproduce the crash in your own channel?

**Comment by suprunchuk** [comment]
@john-preston yes. the broadcast was most likely planned using rtmp. it wasn't directly from the telegram app. the broadcast was launched by a large blogger in several resources at the same time. this stream went simultaneously to Telegram, VK, YouTube. I think when they scheduled the broadcast via rtmp and I tried to connect, then I have a stable crash. Now I can't reproduce this problem when I create a broadcast via the built-in menu in Telegram. This is definitely a problem in third-party software. You've got it right.
