### ISSUE TITLE
Admin without ownership on the Channel/Group - "Stream with..." 

### ISSUE THREAD

**Issue by KhaimovMR** [telegramdesktop/tdesktop#26382]
### Steps to reproduce

1. Be the admin without the "Owner" label in the channel or the group.
2. Left click on stream button.
3. There's no submenu that opens for the owner of the chat on the same left mouse click on this button. This menu contains the item "Stream with..." which you can use to get the stream key - that everybody's using to stream over the OBS, vMIX and such...

### Expected behaviour

On the left mouse click of the admin of the group or channel, on the Stream button opens the menu, that has the "Stream with..." item in it.

### Actual behaviour

On the left mouse click of the admin of the group or channel, on the Stream button a simple direct video chat is starting (without the ability to use the streaming software.

### Operating system

Windows

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Is the behavior consistent with the official mobile apps? I think only creator can stream rtmp.
