### ISSUE TITLE
msys64.exe build error

### ISSUE THREAD

**Issue by Robinson0324** [telegramdesktop/tdesktop#26385]
### Steps to reproduce

1. install visual studio community 2022
2. Follow the instructions from https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md

### Expected behaviour

No errors while running tdesktop\Telegram\build\prepare\win.bat

### Actual behaviour

cannot build msys64.exe

- logs
[1/26](Libraries/patches): SKIPPING
[2/26](ThirdParty/msys64): NOT FOUND, BUILDING:
---------------------------------COMMANDS-LIST----------------------------------
if exist msys64 rmdir /Q /S msys64
if exist msys64 exit /b 1
SET PATH_BACKUP_=%PATH%
SET PATH=%ROOT_DIR%\ThirdParty\msys64\usr\bin;%PATH%
SET CHERE_INVOKING=enabled_from_arguments
SET MSYS2_PATH_TYPE=inherit
powershell -Command "iwr -OutFile ./msys64.exe https://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20221028.sfx.exe"
msys64.exe
del msys64.exe
bash -c "pacman-key --init; pacman-key --populate; pacman -Syu --noconfirm"
pacman -Syu --noconfirm mingw-w64-x86_64-perl mingw-w64-x86_64-nasm mingw-w64-x86_64-yasm mingw-w64-x86_64-ninja
SET PATH=%PATH_BACKUP_%
--------------------------------------------------------------------------------

7-Zip SFX 21.03 ZS v1.5.0 R2 (x64) : Copyright (c) 1999-2021 Igor Pavlov, 2016-2021 Tino Reichardt : 2021-10-05

Extracting archive: D:\Work\Telegram\TBuild\ThirdParty\msys64.exe
ERROR: D:\Work\Telegram\TBuild\ThirdParty\msys64.exe
D:\Work\Telegram\TBuild\ThirdParty\msys64.exe
Open ERROR: Cannot open the file as [7z] archive

ERRORS:
Unexpected end of archive
/bin/bash: pacman-key: command not found
/bin/bash: pacman-key: command not found
/bin/bash: pacman: command not found
[2/26](ThirdParty/msys64): FAILED
FAILED

### Operating system

windows 10

### Version of Telegram Desktop

4.8.3

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Looks like the downloaded file is corrupted, you have to restart the download. If the error persists, you have to change your ISP.

**Comment by Robinson0324** [comment]
> Looks like the downloaded file is corrupted, you have to restart the download. If the error persists, you have to change your ISP.

how to hide search bar in telegram desktop app with latest version? If can't, would you like to add this function again for me on next version?

**Comment by ilya-fedin** [comment]
this never was possible
