### ISSUE TITLE
in sway, we need hide the window decoration.

### ISSUE THREAD

**Issue by xux1217** [telegramdesktop/tdesktop#26399]
### Is your feature request related to a problem?

now, in wayland, there is not the button about "use system window frame" or "hide window decoration" by QT standard environment QT_WAYLAND_DISABLE_WINDOWDECORATION="1".

environment:
telegram-desktop version: 4.8.1
kernel version: 6.1.31-gentoo
WM: sway

### Describe the solution you'd like

we can hide the window decoration in sway.

### Describe alternatives you've considered

add some button like "use system window frame" in X11.

### Additional context

I have search some issue, like:
- https://github.com/telegramdesktop/tdesktop/issues/25391 
- https://github.com/telegramdesktop/tdesktop/issues/8310

but not used in sway.

**Comment by ilya-fedin** [comment]
The option is still there.

**Comment by xux1217** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/9280285/518300ca-0c4c-42df-bcf1-cd0eabaa1828)
There is no option, can you tell me how to config it?
@ilya-fedin

**Comment by ilya-fedin** [comment]
It appears only when the system supports it, apparently sway has stopped supporting it for some reason

**Comment by xux1217** [comment]
So, you mean, this is a bug in sway or  it dose modify the default behavior?

> It appears only when the system supports it, apparently sway has stopped supporting it for some reason

**Comment by ilya-fedin** [comment]
I don't know, maybe you have configured sway in that way. I'm really far from all those tiling things.

**Comment by ilya-fedin** [comment]
Maybe you're looking in the wrong place though, the option is in "Window titlebar" block, not in "System integration" block.

**Comment by xux1217** [comment]
This software is a great application.

I think it should support tiling desktop, or be consistent with a normal QT application behavior, right?

> I don't know, maybe you have configured sway that way. I'm really far from all those tiling things.

**Comment by ilya-fedin** [comment]
Well, Qt have no built-in titlebar widget unlike GTK, so tdesktop has to implement all that machinery from scratch.

**Comment by xux1217** [comment]
Understand. 

And can we reopen this issue? Maybe in future, someone can implement this feature in tiling desktop.

**Comment by ilya-fedin** [comment]
The feature requested in this feature request is already implemented, here its code:
https://github.com/telegramdesktop/tdesktop/blob/9c6ffa01015bdb9747a9bb3b7f21369a0154fe00/Telegram/SourceFiles/settings/settings_advanced.cpp#L426-L438

Thus the request is invalid.

**Comment by zilti** [comment]
@ilya-fedin well, there might be code there for it, but obviously, it is broken. Because I also don't have that option anymore now on KDE Plasma Wayland. So why did you close this?

**Comment by ilya-fedin** [comment]
Because it's a feature request and such a feature already exists

**Comment by CheesecakeCG** [comment]
I'm experiencing this bug on Hyprland 0.28.0, Hyprland can create (although pretty simple) window decorations.

I think the real issue is that the option only shows when it thinks the window manager can provide it's own decorations, but there are many cases where the option does not appear and the WM can provide decorations (Sway, Hyprland, KWin Wayland, mentioned so far).

**Comment by ilya-fedin** [comment]
This option is present on Plasma Wayland, I have it.

**Comment by z411** [comment]
Something is wrong here.

After I upgraded to 4.9.3 the option disappeared, even though I'm on Plasma Wayland and Plasma definitely supports window decorations. If I downgrade to 4.8.1 the option appears again. There's something wrong in the detection logic.

**Comment by ilya-fedin** [comment]
I have this option with 4.9.3 on Plasma Wayland. I'd guess you're using not an official build and the person who made the build for you has disabled this feature.

**Comment by ilya-fedin** [comment]
Yeah, Debian is known to disable lots of features. Debian maintainers are really weird honestly.

**Comment by z411** [comment]
..Wow checking the dependencies they really build against Qt5. Not sure why since they've had Qt6 in the repos for a long time. I'll take the issue with them. Thanks for the quick response.

**Comment by ilya-fedin** [comment]
Well, it's not the biggest problem. I saw their patches and they really scared me. They removing wallpaper synchronization, noise suppression in calls, language detector for translator, custom allocator to avoid glibc leaks, colored emojis, tg:// handler registration. I believe Debian package works with very poor quality and it's better to avoid it at any cost.
https://salsa.debian.org/debian/telegram-desktop/-/tree/debian/master/debian/patches

**Comment by ilya-fedin** [comment]
Given that we can't detect system window frame for sure on Wayland anyway and the transition between system and non-system window frame is utterly bugged on Wayland, I've asked @john-preston in a private dialog a permission to replace the check with an experimental option. So it the option will never be seen out of the box on Wayland (due to a potential very bad UX of Qt window frame instead of system window frame) but experienced users would be able to enable an option in experimental settings to make the code think this is supported (and so the option would appear). Not sure he would allow that but we'll see.

**Comment by z411** [comment]
Thanks. I'd appreciate it. The maintainer is saying Wayland has no system decorations and that the difference is that it's now running on Wayland, but I'm pretty sure the older version and also the official tdesktop package runs on Wayland with system decorations. I'll use the official release for the time being.

**Comment by ilya-fedin** [comment]
Yeah, pure Wayland indeed has no system decorations, that's an extension. The Wayland code in tdesktop relies on the native interface introduce in Qt 6.5 and on a codegen introduce in Qt 6.0, given that they use Qt 5, they don't get the Wayland integration and the code assumes the safest (no system window frame support). They should build with Qt 6 to get this feature.

As for the experimental option, we sadly haven't reached a consensus unfortunately.
