### ISSUE TITLE
Alphabet-ordered channels list

### ISSUE THREAD

**Issue by KvantVS** [telegramdesktop/tdesktop#26390]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Why there is no opportunity to enable alphabet sorting in dialogs-list? Also, in "topics" within groups. It is very confusive when try to find needed group/chat or topic. Yes, there is a search bar, but you don’t always want to print something, but sometimes it’s faster to look through your eyes, knowing the order (alphabetic) and click with the mouse.
It should be a setting for an telegram-client, not for backend, not for one chat, only for your whole client.

### Describe alternatives you've considered

Enable / disable "alphabetical sort"

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
