### ISSUE TITLE
Media viewer stays above file manager dialog when you "Save as"

### ISSUE THREAD

**Issue by Goosegit11** [telegramdesktop/tdesktop#26395]
### Steps to reproduce

1. Open some picture in Media viewer
2. Right-click
3. Save as
4. Media viewer window is stuck, you can't close it - probably file manager window is under it. trying to focus on media viewer (with window manager hotkeys) doesn't help.

### Expected behaviour

file manager window appears above Media viewer

### Actual behaviour

4. Media viewer window is stuck, you can't close it - probably file manager window is under it. trying to focus on media viewer (with window manager hotkeys) doesn't help.

### Operating system

Arch Linux, dk

### Version of Telegram Desktop

4.8.3-1 static binary, development version

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can't reproduce
![image](https://github.com/telegramdesktop/tdesktop/assets/17829319/920f7104-d604-4963-85ce-99536e2ffc12)

**Comment by ilya-fedin** [comment]
Well, given that you almost completely ignored the description of the 'Operating system' filed in the issue template, I can't help you.

**Comment by ilya-fedin** [comment]
Wait, dk is a WM? I thought it's some English abbreviation. It's ok, WM version is not important.

**Comment by ilya-fedin** [comment]
Well, I don't really know what to suggest to you... Apparently your WM resets the fullscreen hint after first show (the window is not destroyed as media viewer is heavy and its re-creation takes a lot of time). Apparently it's some WM bug, idk, I'd recommend to report this to your WM.

Actually I don't know what to suggest with the file dialog either, apparently it's some WM bug as well.

**Comment by ilya-fedin** [comment]
@hexando using official build?

**Comment by ilya-fedin** [comment]
@hexando can you provide a screenshot?

**Comment by Goosegit11** [comment]
Problem was stupid simple.

I had to click this button in Media viewer. It controls if the Media viewer is floating (in tiling windows managers, tiled) or fullscreen.

![image](https://github.com/telegramdesktop/tdesktop/assets/89806596/9a2cad80-51a8-4a79-b0ae-f0f30ed4c0c4)

**Comment by ilya-fedin** [comment]
Well, it shouldn't stay above in either mode and it doesn't on Windows, macOS, GNOME and KDE as far as I know

**Comment by Goosegit11** [comment]
https://github.com/telegramdesktop/tdesktop/issues/26395#issuecomment-1586294588
> uhmm, for some reason now it behaves another way, exactly like #5048 - window gets tiled and is not fullscreen

I meant this. Media viewer window was getting tiled because I accidentally pressed the "fullscreen" button in Media viewer.
