### ISSUE TITLE
Lack of AppImage Availability Causing Inconvenience

### ISSUE THREAD

**Issue by WeberAlex** [telegramdesktop/tdesktop#26397]
### Is your feature request related to a problem?

I have encountered an issue with the installation of Telegram on my Chromebook, which is running Debian 11 Bullseye in a Crostini container. The problem lies in the outdated version of Telegram available in the repository.

Additionally, the alternative installation methods using Telegram Flatpak and Telegram Snap are not user-friendly. The process requires installing the respective repositories, then installing the application, and even removing it if necessary.

### Describe the solution you'd like

An alternative solution for running Telegram through AppImage, eliminating the need for traditional installation procedures. This method should provide a simplified user experience, allowing users to test and remove Telegram effortlessly.

### Describe alternatives you've considered

After installing the backport version of the software from the repository, I discovered that it is outdated and lacks essential features.

### Additional context

I encountered a crash issue while using the Flatpak version of Telegram. After installing the Flatpak repository and the Flatpak package for Telegram, I attempted to run the application, but it crashed unexpectedly. The absence of an AppImage resulted in unnecessary troubles and inconveniences.

**Comment by ilya-fedin** [comment]
What's the problem with the static binary offered at https://desktop.telegram.org?

**Comment by WeberAlex** [comment]
I encountered a system crash when using Telegram. Please refer to issue #26396 for more details. Moreover, the problem persists when using the binary version of Telegram (error message below).

Although the binary itself seems to be functioning correctly, I had to use a different command to extract the archive. Among various options, I found AppImage to be the most convenient for testing an application.

```
name@penguin:~/Telegram$ name@penguin:~/Telegram$ ./Telegram
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
ndowChanged(QScreen*)
(Telegram:1619): Gtk-WARNING **: 22:11:05.076: Theme parsing error: <data>:1:0: Expected a valid selector
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segmentdata>:1:0: Expected a valid
Segmentation fault (core dumped)
name@penguin:~/Telegram$ QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
QWidget::render: Cannot render with an inactive painter
(Telegram:1742): Gtk-WARNING **: 22:11:40.721: Theme parsing error: <data>:1:0: Expected a valid selector
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
The Wayland connection broke. Did the Wayland compositor die?
```

**Comment by ilya-fedin** [comment]
AppImage won't magically solve your crash, sorry. Especially given that it's a crash of your system component and Telegram exits gracefully as the connection with your system component is lost.
