### ISSUE TITLE
Telegram Desktop is frozen on Windows 10

### ISSUE THREAD

**Issue by JuKu** [telegramdesktop/tdesktop#2639]
On Windows 10 (with newest updates) Telegram Desktop will be frozen after a few seconds or minutes.
Then i have to restart the application, but after a few minutes the problem is the same.
Also Teamspeak has this problem, but all other applications run.
My computer hasnt many CPU load yet.

### Steps to reproduce
1. Update your Windows 10
2. Use Intel HD / Nvidia GTX960M graphics card.
3. Start the app

### Expected behaviour
App runs normaly.

### Actual behaviour
App is frozen after a few seconds / minutes.

### Configuration
**Operating system:** Windows 10 Build 14393

**CPU**: Intel i7-6700HQ
**RAM**: 8GB
SSD
**Computer**: MSI GL72 6QF

**Version of Telegram Desktop:** newest (0.10.19)

**Comment by stek29** [comment]
Do you use Windows native notifications or TDesktop's ones?

**Comment by JuKu** [comment]
I am using Telegram Desktops one.

**Comment by nixerr** [comment]
Have same issue. Also freezeing qBittorrent and VirtualBox which use qt library too

**Comment by Aokromes** [comment]
can you try updating network drivers?

**Comment by Aokromes** [comment]
no answer after months, if you still have the issue update network drivers, closing.
