### ISSUE TITLE
The contact disappears from the list

### ISSUE THREAD

**Issue by tcount2** [telegramdesktop/tdesktop#26392]
### Steps to reproduce

1. Your contact must delete the history of correspondence with you

### Expected behaviour

Your contact should not disappear from the chat list due to lack of correspondence with him

### Actual behaviour

Your contact disappears from the chat list.
It also disappears from the chat folders.
A contact can only be found through a search.

### Operating system

Windows 10 64 bit 

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
not a bug.

**Comment by tcount2** [comment]
Apparently, this is normal when there is a contact, but it is not visible.
