### ISSUE TITLE
Unable to switch to other applications after copy-pasting an image

### ISSUE THREAD

**Issue by alexkuz** [telegramdesktop/tdesktop#26400]
### Steps to reproduce

1. Copy an image to clipboard in any other application
2. Paste image to the chat, triggering "Send an image" dialog.
3. Press "Cancel" in the dialog

### Expected behaviour

1. Can switch to other applications by clicking app icon in a desktop panel or main menu
2. Can switch to browser by clicking a link in chat message

### Actual behaviour

1. Nothing happens after clicking app icon, the focus stays in chat input field
2. The corresponding page is opened in browser, but in the same manner the focus is not switching to the browser
3. It's still possible to switch to other apps with `alt+tab` keys

### Operating system

Linux Mint 21.1

### Version of Telegram Desktop

4.8.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
This sounds like a bug of your WM, not tdesktop

**Comment by alexkuz** [comment]
That is possible. I wonder why it only applies to tdesktop though.

**Comment by ilya-fedin** [comment]
Apparently because it's the only Qt application on your computer
