### ISSUE TITLE
Telegram hangs after clicking on a link

### ISSUE THREAD

**Issue by fillest** [telegramdesktop/tdesktop#26402]
### Steps to reproduce

1. Click on a link in a chat, for example some youtube link

### Expected behaviour

The links opens in a browser

### Actual behaviour

Telegram window hangs. I can click on its tray icon and exit - it exits and then the link gets opened in a browser.
It happens both with snap and static binary.
Restart or reboot doesn't help.
It doesn't happen in 4.8.1

### Operating system

Ubuntu 21.10, gnome 40.4.0

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
duplicate, will be fixed on next release.
