### ISSUE TITLE
Sending sticker when you want sending emoji.

### ISSUE THREAD

**Issue by hectorlinarestascon** [telegramdesktop/tdesktop#2640]
### Steps to reproduce
1. Select one emoji to send it in a message. (Don't write anymore)
2. It opens the associated stickers. Pulse enter key in keyboard to send the emoji.
3. Telegram desktop sends the sticker where you put the mouse, not the emoji that you want to send.

### Expected behaviour
Send only a emoji.

### Actual behaviour
Telegram desktop sends the sticker where you put the mouse, not the emoji that you want to send.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
0.10.19

**Comment by stek29** [comment]
I'm 99% sure it's duplicate, but I can't find it.
