### ISSUE TITLE
Failed to build, opus not found with pkg-config

### ISSUE THREAD

**Issue by CaledoniaProject** [telegramdesktop/tdesktop#26414]
### Steps to reproduce

I'm following exactly the steps here
https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md

### Expected behaviour

I expect tdesktop\Telegram\build\prepare\win.bat to finish successfully

### Actual behaviour

The prepare script failed

![111](https://github.com/telegramdesktop/tdesktop/assets/1357701/429d2d46-b025-494a-8958-5767164b688e)

### Operating system

Windows Server 2022

### Version of Telegram Desktop

latest

### Installation source

Other (unofficial) source

### Logs

```shell
Packages (1) pkgconf-1.9.4-1

Total Download Size:   0.06 MiB
Total Installed Size:  0.29 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 pkgconf-1.9.4-1-x86_64                          61.6 KiB  65.7 KiB/s 00:01 [#########################################] 100%
(1/1) checking keys in keyring                                              [#########################################] 100%
(1/1) checking package integrity                                            [#########################################] 100%
(1/1) loading package files                                                 [#########################################] 100%
(1/1) checking for file conflicts                                           [#########################################] 100%
(1/1) checking available disk space                                         [#########################################] 100%
:: Processing package changes...
(1/1) installing pkgconf                                                    [#########################################] 100%
sed 's#@@PREFIX@@#C:/Users/Administrator/Desktop/Libraries/win64/local#' ffnvcodec.pc.in > ffnvcodec.pc
install -m 0755 -d '/c/Users/Administrator/Desktop/Libraries/win64/patches/../local/include/ffnvcodec'
install -m 0644 include/ffnvcodec/*.h '/c/Users/Administrator/Desktop/Libraries/win64/patches/../local/include/ffnvcodec'
install -m 0755 -d '/c/Users/Administrator/Desktop/Libraries/win64/patches/../local/lib/pkgconfig'
install -m 0644 ffnvcodec.pc '/c/Users/Administrator/Desktop/Libraries/win64/patches/../local/lib/pkgconfig'
ERROR: opus not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
[20/26](Libraries/ffmpeg): FAILED
FAILED
```
```

**Comment by CaledoniaProject** [comment]
I executed the script multiple times and it finally exited without error. Now I got another problem

```
> configure.bat -D XXX -D XXX

Warn about uninitialized values.
Version: 4.8.4
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.20348.
CMake Error at cmake/external/qt/package.cmake:32 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:64 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by ilya-fedin** [comment]
> and it finally exited without error.

Given that it can't find Qt, I highly doubt it exited without error.

**Comment by CaledoniaProject** [comment]
@ilya-fedin It succeed and the Qt5 library is compiled.

![qqq](https://github.com/telegramdesktop/tdesktop/assets/1357701/6eaf621b-f3af-4d2c-a371-7d85c782dafe)

And when I execute the prepare script again it prompts no error, everything is done already.

```
C:\Users\Administrator\Desktop>tdesktop\Telegram\build\prepare\win.bat
[1/26](Libraries/patches): SKIPPING
[2/26](ThirdParty/msys64): SKIPPING
[3/26](ThirdParty/python#0.3.11.4): SKIPPING
[4/26](ThirdParty/NuGet): SKIPPING
[5/26](ThirdParty/jom): SKIPPING
[6/26](ThirdParty/gyp): SKIPPING
[7/26](Libraries/lzma): SKIPPING
[8/26](Libraries/zlib): SKIPPING
[9/26](Libraries/mozjpeg): SKIPPING
[10/26](Libraries/openssl): SKIPPING
[11/26](Libraries/opus): SKIPPING
[12/26](Libraries/rnnoise): SKIPPING
[13/26](Libraries/dav1d): SKIPPING
[14/26](Libraries/libavif): SKIPPING
[15/26](Libraries/libde265): SKIPPING
[16/26](Libraries/libheif): SKIPPING
[17/26](Libraries/libjxl): SKIPPING
[18/26](Libraries/libvpx): SKIPPING
[19/26](Libraries/nv-codec-headers): SKIPPING
[20/26](Libraries/ffmpeg): SKIPPING
[21/26](Libraries/openal-soft#0.2): SKIPPING
[22/26](Libraries/breakpad): SKIPPING
[23/26](Libraries/tg_angle): SKIPPING
[24/26](Libraries/qt_5_15_9): SKIPPING
[25/26](Libraries/tg_owt): SKIPPING
[26/26](Libraries/protobuf): SKIPPING
```

**Comment by CaledoniaProject** [comment]
@ilya-fedin I'll come back ASAP, I have deleted everything and start over again.

**Comment by CaledoniaProject** [comment]
Qt5Config.cmake is located in the Qt-5.5.19 folder

![1111](https://github.com/telegramdesktop/tdesktop/assets/1357701/b13b9a8f-100c-49cf-8055-025432e33848)

And I tried to specify the directory directly, still won't work

```
C:\Users\Administrator\Desktop\tdesktop\Telegram>configure.bat -DQT_DIR=C:\Users\Administrator\Desktop\Libraries\win64\Qt-5.15.9
Warn about uninitialized values.
Version: 4.8.4
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.20348.
CMake Error at cmake/external/qt/package.cmake:32 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:64 (include)

-- Configuring incomplete, errors occurred!
```

Attached CMakeCache.txt

**Comment by ilya-fedin** [comment]
`# It was generated by CMake: C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe`
CMake provided by Visual Studio is known to not to work with tdesktop build, please uninstall it.

**Comment by CaledoniaProject** [comment]
@ilya-fedin Interesting pitfall, can you update the build document and tell other people not to uncheck cmake in Visual Studio Installer?

![11222](https://github.com/telegramdesktop/tdesktop/assets/1357701/b165cbec-8f7c-4c5b-aac9-e29d646bd9ec)

**Comment by ilya-fedin** [comment]
Well, it's more a question for @john-preston whether he would like to document that

**Comment by CaledoniaProject** [comment]
I've created a PR for this https://github.com/telegramdesktop/tdesktop/pull/26424

**Comment by CaledoniaProject** [comment]
@ilya-fedin It does not solve the problem .... it still couldn't find QT

[cmakecache-new.txt](https://github.com/telegramdesktop/tdesktop/files/11780338/cmakecache-new.txt)

**Comment by ilya-fedin** [comment]
I hope you've cleared the build directory and didn't pass the `-DQT_DIR` option?

**Comment by ilya-fedin** [comment]
Is it possible you somehow launch prepare.py with x64 build tools but tdesktop itself with x86 build tools?

**Comment by ilya-fedin** [comment]
According to your CMakeCache.txt, it's not just x86 build tools but x64_x86 cross tools
```
//Path to a program.
CMAKE_AR:FILEPATH=C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x86/lib.exe
```

**Comment by ilya-fedin** [comment]
If prepare.py was running using x64_x86 cross tools as well then all the dependencies are corrupted

**Comment by CaledoniaProject** [comment]
I don't remember if it's a X64 native environment, I've deleted `Telegram\out, Libraries, ThirdParty` and will start over again.

**Comment by CaledoniaProject** [comment]
@ilya-fedin In the x64 Native environment, prepare.py finished successfully and I instantly started the configure.bat, and it fails with the same error

![shot 2023-06-18 at 14 56 41](https://github.com/telegramdesktop/tdesktop/assets/1357701/9a243a14-86ad-4a7c-b788-e5ab82049eaa)

Attached cmakecache
[cmakecache3.txt](https://github.com/telegramdesktop/tdesktop/files/11780814/cmakecache3.txt)

**Comment by ilya-fedin** [comment]
You're still using `x64_x86 Cross Tools`, NOT the `x64 Native Tools` (or maybe you forgot to clear build cache?).

**Comment by CaledoniaProject** [comment]
@ilya-fedin Hmm, that's weird, see the last screenshot title .... I'm in the x64 Native tools. What do you think is wrong?

I cleared Libraries, ThirdParty and tdesktop\out, is that not enough?

**Comment by CaledoniaProject** [comment]
I'll clear everything and try the x86 steps, just to see if it works

**Comment by ilya-fedin** [comment]
> is that not enough?

cmakecache is in out, so I was talking about out specifically.

> I'm in the x64 Native tools.

Are you sure? CMakeCache says you're not.

**Comment by ilya-fedin** [comment]
Running command line as admin has tendency to reset environment variable, ensure you're not running as admin

**Comment by ilya-fedin** [comment]
> configure.bat -D XXX -D XXX

I have just noticed that none of your snipetts/screenshots have `x64` like mentoned in the instruction
![изображение](https://github.com/telegramdesktop/tdesktop/assets/17829319/287f63a6-fdd9-4f14-b8c4-8b53808c55ab)

**Comment by CaledoniaProject** [comment]
I successfully build it with x86 environment. Weird, not sure what's wrong with x64.

**Comment by ilya-fedin** [comment]
Have you seen my last message?

**Comment by CaledoniaProject** [comment]
@ilya-fedin Yes I saw it, but I think -D is not actually the culprit. In the x86 environment I forget to use these parameters as well, but it prompts the API and HASH is required, instead of missing QT libraries ....

**Comment by CaledoniaProject** [comment]
@ilya-fedin Ahhh, damn, I completely missed the `x64` parameter!

**Comment by CaledoniaProject** [comment]
Closing the case. I've successfully build on both x86 and x64 environment.
