### ISSUE TITLE
Layout issue with audio/voice message close button

### ISSUE THREAD

**Issue by shutuper** [telegramdesktop/tdesktop#26413]
### Steps to reproduce

1. Play some voice message/audio 
2. Hover over the player's close button

### Expected behaviour

"X" should be placed in the center of close circle button

### Actual behaviour

"X" placed not in the center of close circle button
![image](https://github.com/telegramdesktop/tdesktop/assets/70547118/42e562af-c97f-45b6-af2c-776722dd69f5)

### Operating system

macos 12.6.6

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Please check the latest version.

**Comment by shutuper** [comment]
fixed  ✅ @23rd
