### ISSUE TITLE
Add ability to hide message content in notifications

### ISSUE THREAD

**Issue by Aashishkebab** [telegramdesktop/tdesktop#26427]
### Is your feature request related to a problem?

Both WhatsApp and Messenger have the ability to show notifications but not the content of the message in the notification. This is a privacy feature, in case someone else is looking at my laptop screen, which happens frequently.

This feature on Telegram app for desktop would be really useful.

### Describe the solution you'd like

Add a feature to not show message content in notifications.

### Describe alternatives you've considered

NA

**Comment by kolayne** [comment]
Go to Settings -> Notifications -> Uncheck "text":

![image](https://github.com/telegramdesktop/tdesktop/assets/23319866/65c0a2be-059b-4b94-bebe-3020c24be39c)
