### ISSUE TITLE
Unable to add admin to a Telegram Supergroup - "Could not add user. Please try again later."

### ISSUE THREAD

**Issue by cisselic** [telegramdesktop/tdesktop#26429]
### Steps to reproduce

The original Telegram group owner transferred ownership to me on May 26, 2023. I realised that I couldn't promote users to admins or change their titles.

I assumed there was a standard wait time for such rights to be activated to new owners but it seems it is a bug.

My Telegram username is @djibrilww 

### Expected behaviour

I should be able to add admins and edit their titles.

### Actual behaviour

I receive 'Could not add user. Please try again next time.'

### Operating system

Safari and Android

### Version of Telegram Desktop

Latest Version

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
Operating system
Safari and Android

this is telegram DESKTOP application, not android nor webpate.

**Comment by cisselic** [comment]
I am facing the same issue on Desktop.
