### ISSUE TITLE
"Additional" windows in the application does not work correctly

### ISSUE THREAD

**Issue by TarasovSavely** [telegramdesktop/tdesktop#26432]
### Steps to reproduce

1. Open the app
2. For example, choose any of the chats or channels
3. Imagine that you need to delete this chat / exit the channel
4. Click on the chat with the right mouse button (the first "additional" window will appear)
5. Move your mouse down to select "leave chat"
6. Once the mouse reaches "turn off notifications" (a second "additional" window will appear)
7. And as soon as the mouse leaves the "turn off notifications" item, the second "additional" window will close, but the first one will also close with it!

### Expected behaviour

Only the second "additional" window will close

### Actual behaviour

Closes all "additional" windows

### Operating system

Fedora Linux 38 (Workstation Edition) 64-bit

### Version of Telegram Desktop

4.8.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Sounds like #26407 but for windows rather than menus?

**Comment by TarasovSavely** [comment]
Yes, it looks that

**Comment by ilya-fedin** [comment]
Sadly I can't reproduce with windows. I'm able to open multiple windows for multiple chats and close them one-by-one, not only with Plasma but even with Weston.

**Comment by TarasovSavely** [comment]
In lastest version it work normal ;)
