### ISSUE TITLE
bug with foto and video

### ISSUE THREAD

**Issue by bigbaldhead-0day** [telegramdesktop/tdesktop#26439]
### Steps to reproduce

there is no id, and a bug, as soon as I close a photo or video, telegram closes too

### Expected behaviour

there is no id, and a bug, as soon as I close a photo or video, telegram closes too

### Actual behaviour

there is no id, and a bug, as soon as I close a photo or video, telegram closes too

### Operating system

debian 11 bullseye

### Version of Telegram Desktop

v4.8.1

### Installation source

Flatpak

### Crash ID

there is no id, and a bug, as soon as I close a photo or video, telegram closes too

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by bigbaldhead-0day** [comment]
I can't, my computer (Chromebook with Debian 11) It makes me download only .Deb files, and flatpaks via terminal

**Comment by bigbaldhead-0day** [comment]
I can't, my computer (Chromebook with Debian 11) It makes me download only .Deb files, and flatpaks via terminal

**Comment by ilya-fedin** [comment]
You can download the archive with curl and then unpack it with and tar (using -J for xz decompression)

**Comment by ilya-fedin** [comment]
Also, if your issue is the same as #26396 then it's a Chrome OS bug
