### ISSUE TITLE
/bigobj is needed to build the Win32 package

### ISSUE THREAD

**Issue by CaledoniaProject** [telegramdesktop/tdesktop#26430]
I'm following the Win32 build instructions and it won't build the Release version,

![shot 2023-06-19 at 22 38 21](https://github.com/telegramdesktop/tdesktop/assets/1357701/fe6609a2-9fc6-420f-b391-94b4e3010c85)

Can you add /bigobj somewhere in the prepare.py? Right now I had to add it manually.

**Comment by 23rd** [comment]
Can't confirm.

**Comment by ilya-fedin** [comment]
> Try to build 64 build, release version

64-bit version already has it: https://github.com/desktop-app/cmake_helpers/blob/bd556e2a16d34ad876054fb3ab25e83481af652a/options_win.cmake#L43C1-L47
