### ISSUE TITLE
Problem with CMYK JPG colors in preview of uncompressed image

### ISSUE THREAD

**Issue by r10v** [telegramdesktop/tdesktop#26440]
### Steps to reproduce

1. Export Adobe Illustrator image as JPG in CMYK color model
2. Upload to Telegram via Telegram Desktop with unchecked "compress" checkbox

### Expected behaviour

Image must be displayed with correct colors

### Actual behaviour

Colors on in-telegram preview are shifted somehow. Here is the sample jpeg in case if you need it for tests https://github.com/r10v/t/blob/main/before_telegram.jpg

### Operating system

Windows

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Unfortunately, Qt doesn't support color management, so if you need a client with such capabilities, you have to switch to one of the web clients.

**Comment by ilya-fedin** [comment]
Actually, it seems I can't reproduce. Telegram displays it the same as other applications on my computer. So either the issue is not valid or none of my applications support this color model (an image of expected appearance should be provided).

**Comment by r10v** [comment]
Chrome

https://github.com/r10v/t/blob/main/20230623-111019-chrome_8K3BW7hOit.png

Telegram

https://github.com/r10v/t/blob/main/20230623-110958-Telegram_jFhRJwNOeg.png

**Comment by ilya-fedin** [comment]
All applications I've tried (Firefox, Telegram and Gwenview) display it as on your second screenshot. I guess supporting this is non-trivial and doesn't really have sense for something other than a photo editing tool (or software made by big companies like Google's Chrome that can spend time on this). I recommend to convert images to sRGB if you want them to be displayed right by average software like Telegram and use this color model only for the other part to open in a photo editing tool.

**Comment by r10v** [comment]
On iOS it works as expected. So I guess it is really something related to QT, not sure.

https://github.com/r10v/t/blob/main/photo_2023-06-23_11-17-03.jpg

**Comment by ilya-fedin** [comment]
As far as I can see, all requests for CMYK support are closed as "Out of scope" by Qt, so they don't plan to implement this and Telegram can't use this format unless it would migrate from QImage to another image reading library (which means rewriting a big part of the application):
https://bugreports.qt.io/browse/QTBUG-86
https://bugreports.qt.io/browse/QTBUG-896
https://bugreports.qt.io/browse/QTBUG-5199

I guess supporting this doesn't really worth the effort and unlikely to be done.

**Comment by ilya-fedin** [comment]
Looking at Qt sources, it converts CMYK to RGB right when reading jpegs: https://github.com/qt/qtbase/blob/5546f2df538c06f5e7cc3e218f03a9a0ef2d830e/src/plugins/imageformats/jpeg/qjpeghandler.cpp#L350-L359. Apparently its conversion implementation is not right?

**Comment by r10v** [comment]
I've done some research, and it appears that CMYK support is completely broken on Linux, at least in Ubuntu 22.04. I couldn't find an app that correctly displays CMYK images, except for Chrome. Therefore, I believe there might be an issue with the core OSS libraries.

Here's an interesting fact: ImageMagick's display command shows green letters, while GraphicsMagick's displays them as blue.

However, considering that my report may be the first one in 9 years of Telegram Desktop's existence, I don't think it's worth investing time in fixing it.

**Comment by ilya-fedin** [comment]
> ImageMagick's `display` command shows green letters

Well, I've tried to patch Qt to use Little-CMS instead of in-home CMYK->RGB conversion and I've got green letter on black background at first. Then I've found in Little-CMS repo an utility that reads jpegs using libjpeg + lcms, it has a special-case for Adobe-generated files: their software writes CMYK data in non-standard way. Once I've applied this workaround, I've got the same image as on your screenshot.

Patch is here, but it will be applied only to Linux binary builds at best (it's for Qt 6, Windows is still using Qt 5 and it seems no one is interested to add Little-CMS to macOS build): https://github.com/desktop-app/patches/pull/146

**Comment by r10v** [comment]
Great news for Linux users! And thank you for spending your time on this bug.

**Comment by ilya-fedin** [comment]
> I've done some research, and it appears that CMYK support is completely broken on Linux, at least in Ubuntu 22.04.

Is it any better on Windows?

> I couldn't find an app that correctly displays CMYK images, except for Chrome.

GIMP seem to display it right for me.

**Comment by r10v** [comment]
In fact, Telegram is the only app on Windows that experiences this issue. Surprisingly, even Paint is able to open the file correctly (https://github.com/r10v/t/blob/main/20230624-015609-mspaint_aicxy7AbtC.png). However, I cannot guarantee that this is not due to the presence of Adobe apps installed on my system. It wouldn't be surprising if the Adobe installation altered some DLLs.

**Comment by r10v** [comment]
Well, it seems that Windows itself doesn't have this issue at all. In a clean installation of Windows 11, even the Explorer previews display the images correctly (https://github.com/r10v/t/blob/main/20230624-020724-vmware_haaN56ak5l.png). However, Telegram still fails to handle them properly.

**Comment by ilya-fedin** [comment]
Well, those all are examples of built-in apps, I was asking more about third-party apps like Firefox
