### ISSUE TITLE
[Improvement] On 'set image' on a group panel, the window doesn't show thumbnails.

### ISSUE THREAD

**Issue by oxydron** [telegramdesktop/tdesktop#2644]
When you go to change the group avatar, the window that opens do not show the images thumbnails.

This happens on Linux with both Gnome3 and Vala (elementary OS).

**Comment by auchri** [comment]
Please provide some screenshots and use the template next time.

**Comment by oxydron** [comment]
![screenshot from 2016-11-17 11-41-09](https://cloud.githubusercontent.com/assets/331134/20391939/d14fb032-acbc-11e6-9dd5-7426645efdcd.png)
Sorry for not using the template.

**Comment by oxydron** [comment]
Well, my printscreen is above. Telegram Desktop version 1.0 still doesn't do it right, no image preview.
This problem also occurs when you are looking for a image to background conversations.
