### ISSUE TITLE
Input focus

### ISSUE THREAD

**Issue by desempare** [telegramdesktop/tdesktop#26448]
### Steps to reproduce

1. Select some text in chat window.
2. Switch to another app (tested on Linux and Windows client)
3. Switch back to TG and start typing - nothing happen, input focus is not on input field.

### Expected behaviour

1. Select some text in chat window.
2. Switch to another app
3. Switch back to TG Desktop and start typing - all typed in input field.

### Actual behaviour

By default when you reply or switch to TG Desktop, it focus on input field and you can start typing blindly. But if we have some selected text on chat window - focus on input field not started after switch to TG Desktop and it annoyed, you can't start typing blindly and need to manual click to input field and then start typing.

### Operating system

OpenSuse 15.2, Windows 7

### Version of Telegram Desktop

Linux 4.8.4, Windows 4.8.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This sounds like a feature request at best, the current behavior is common for applications while the one you're proposing feels really buggy

**Comment by john-preston** [comment]
Should be better in 4.8.5.

It still saves the focus on the messages, if something was selected, but now when you start typing it jumps to the input field.
