### ISSUE TITLE
Vanishing messages: MESSAGE_ID_INVALID

### ISSUE THREAD

**Issue by shivagnihotri** [telegramdesktop/tdesktop#26445]
### Steps to reproduce

1. Write a message with content taking a longer upload time
2. Set the message for sending at a planned time
3. Make sure that content is still uploading while planned time passes

When the upload of larger files takes longer than the previously set time for that planned message, Telegram Desktop and also Telegram Mobile spit out a "MESSAGE_ID_INVALID". Then, somehow, the content is being published into the chat, but cannot be seen nor edited by the sender, but is present for everyone in the chat.

### Expected behaviour

Telegram should publish the planned content also for the user who sent it, even after the planned time for that message has passed. It seems to be a weird bug under the mentioned special circumstance, but it's extremely annoying having vanishing posts which are being published, but cannot be seen nor edited by me as the sender.

This leads to double posts of the content when information has to be edited in it but can't - which in turn is extra stress on the nerves of everyone reading the chat.

### Actual behaviour

Telegram shortly displays "MESSAGE_ID_INVALID" and the message of the sender vanishes for the sender, but is being displayed for everyone else.

### Operating system

Parrot Security OS, 6.1.0-1parrot1-amd64, KDE

### Version of Telegram Desktop

Version 4.8.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> vanishes for the sender

doesn't client restart help?

**Comment by shivagnihotri** [comment]
If you mean restarting Telegram: No, it doesn't.
