### ISSUE TITLE
Constant CPU usage when closed

### ISSUE THREAD

**Issue by arch-user-france1** [telegramdesktop/tdesktop#26444]
### Steps to reproduce

1. Install telegram
2. Open `htop`
3. See it's using around 8% of one core while it is closed, while Firefox only needs 1% when it is open

### Expected behaviour

Telegram should not have need of that many resources while it is closed.

### Actual behaviour

Telegram uses an increased amount of the CPU while it is closed on MacOS.

### Operating system

MacOS Ventura 13.4

### Version of Telegram Desktop

9.6.3.245683 AppStore

### Installation source

Mac App Store

**Comment by arch-user-france1** [comment]
It seems that Telegram does not free up some scripts or whatever because when Telegram was completely quit and restarted, it only used a constant usage of 0.4%, which is still too high.

**Comment by Aokromes** [comment]
you are using https://macos.telegram.org/ https://github.com/overtake/TelegramSwift not telegram desktop.
