### ISSUE TITLE
Support "Formatting options" in core messages.sendMessage

### ISSUE THREAD

**Issue by Kolsha** [telegramdesktop/tdesktop#26442]
### Is your feature request related to a problem?

I can't write [MarkdownV2](https://core.telegram.org/bots/api#markdownv2-style) messages as a user of telegram.

### Describe the solution you'd like

Support "Formatting options" in core [messages.sendMessage](https://core.telegram.org/method/messages.sendMessage)

Right now bots can send formatted messages in [MarkdownV2](https://core.telegram.org/bots/api#markdownv2-style) format, but regular users can't.
It would be great to have such functionality for example for sharing code snippets, pre-formatted text from other apps, etc.

[bugs.telegram.org](https://bugs.telegram.org/c/29391)

### Describe alternatives you've considered

Slack? 🙈

**Comment by ilya-fedin** [comment]
This is already implemented

**Comment by ilya-fedin** [comment]
The bug on bugs.telegram.org seem to be about Telegram for macOS, not about tdesktop
