### ISSUE TITLE
 Telegram for Win64 installing

### ISSUE THREAD

**Issue by orgcreator** [telegramdesktop/tdesktop#26458]
### Steps to reproduce

![image](https://github.com/telegramdesktop/tdesktop/assets/45131232/6f2a9270-01f0-41c1-af2d-9c10d7c03c66)

I have installed Telegram for Win64 right now - 3 ours😱 

Now I'm on this step: 

Open BuildPath\tdesktop\out\Telegram.sln in Visual Studio 2022
Select Telegram project and press Build > Build Telegram (Debug and Release configurations)

Is that's all right that red minuses in my VS 2022 & that it building about 1 hour right now & continuing?

BR,
Rustam

### Expected behaviour

Open BuildPath\tdesktop\out\Telegram.sln in Visual Studio 2022

### Actual behaviour

Open BuildPath\tdesktop\out\Telegram.sln in Visual Studio 2022

### Operating system

Open BuildPath

### Version of Telegram Desktop

Open BuildPath

### Installation source

Static binary from official website

### Crash ID

Open BuildPath

### Logs

```shell
Open BuildPath
```

**Comment by ilya-fedin** [comment]
I don't quite understand what the bug is. If that's not a bug but a question then please use the appropriate button when creating the issue.

**Comment by orgcreator** [comment]
sure - sorry

**Comment by orgcreator** [comment]
I'm wrote in Telegram Desktop Talk - but nobody answering me

![image](https://github.com/telegramdesktop/tdesktop/assets/45131232/667394df-994f-4c2d-b5c0-dc06a7f53331)

Is tha't all right & I need to waiting or something wrong?

"Hello! I'm just installed Telegram Desktop for development as here: https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md 

Now I'm on this step:

Open BuildPath\tdesktop\out\Telegram.sln in Visual Studio 2022
Select Telegram project and press Build > Build Telegram (Debug and Release configurations)

Is that's all right that red minuses in my VS 2022 & that it building about 1 hour right now & continuing?"

**Comment by orgcreator** [comment]
It doesn't change 
![image](https://github.com/telegramdesktop/tdesktop/assets/45131232/d6d934ac-79c7-480a-b0f0-34067b79851b)

**Comment by ilya-fedin** [comment]
I think it's just no one knows

**Comment by orgcreator** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/45131232/ac60253e-4508-4718-8ecb-52ab70b64f49)


Ok - I'm just repeat all

![image](https://github.com/telegramdesktop/tdesktop/assets/45131232/2fefece9-00e5-4f00-9d7e-2c14d81f4955)

That's all right as you see - but I'm not find **"The result Telegram.exe will be located in D:\TBuild\tdesktop\out\Debug (and Release)"** as you wrote in you docs:

![image](https://github.com/telegramdesktop/tdesktop/assets/45131232/09e7fe8a-0602-4530-8fe4-d700d5cd8841)

So as you see - that's all right with bult? But I can't find Telegram in folder as you describe in you Docs:

![image](https://github.com/telegramdesktop/tdesktop/assets/45131232/1c0c67cb-ef54-45b1-b19f-f362c20d9df8)

![image](https://github.com/telegramdesktop/tdesktop/assets/45131232/e87757bb-d357-427d-830e-0161148f3824)

So what's the problem?

BR,
Rustam
@orgcreator

**Comment by ilya-fedin** [comment]
The problem is you can't expect it will be easy to steal Telegram source code for your gov

**Comment by orgcreator** [comment]
))) I'm not a government man - my project is https://goru.site/ and it's all based on Telegram - I'm just want to rename Telegram as my own messanger for working in Russian Laws as this: https://www.cnews.ru/news/top/2023-06-22_dlya_chinovnikov_i_bankirov Soб can I do that? May be with VPN etc. or it's impossible? And it's all just joke about Telegram source code for all? So, please - write me on Telegram @orgcreator if it impossible to build source code & if it needs something more for honest developers🙏🙏🙏

**Comment by orgcreator** [comment]
Why?

**Comment by ilya-fedin** [comment]
You're too narrow to understand, forget and continue helping Russian laws work

**Comment by orgcreator** [comment]
So I think you are not Telegram developer? And this repo are not official?

**Comment by orgcreator** [comment]
@ilya-fedin - так по делу то в итоге что? Не работают исходники эти? ни с VPN никак? Исходник Telegram - иллюзия? Я и с Голладии попробовал - не генерится "**The result Telegram.exe will be located in D:\TBuild\tdesktop\out\Debug (and Release)**" Лажа всё это?

**Comment by ilya-fedin** [comment]
They're disabled by the universe personally for you

**Comment by aleksusklim** [comment]
Приглашаю в t.me/kepka_support последний раз, на Гитхабе с вами разговаривать больше никто не желает (да и в кепке не факт что).

**Comment by Aokromes** [comment]
this is a bug tracker, not a chat.

**Comment by orgcreator** [comment]
So can you please provide right github link - where right Telegram Developers without negative & with professional knowledge on how to use Telegram source code

**Comment by nuclight** [comment]
Оно разумеется possible, но на месте разработчиков стоило бы за такое дать в морду, а не советы по сборке.

**Comment by ilya-fedin** [comment]
> So can you please provide right github link - where right Telegram Developers without negative & with professional knowledge on how to use Telegram source code

[The right github link](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by orgcreator** [comment]
Успехов Илья - представлял себе разработчиков Telegram более профессиональными - напишите что все исходники бесполезны что ли тогда - зачем в заблуждение вводить людей то)

**Comment by orgcreator** [comment]
Так уважаемый - по-Вашему это ответ на мою проблему? "The problem is you can't expect it will be easy to steal Telegram source code for your gov"

**Comment by ilya-fedin** [comment]
This a bugtracker, not a support forum

**Comment by orgcreator** [comment]
So - please help - with bug 🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by orgcreator** [comment]
I need to repeat the scrinshots?

**Comment by ilya-fedin** [comment]
you have to properly fill the issue template. And even then people are free to ignore your issue.

**Comment by nuclight** [comment]
> I need to repeat the scrinshots?

Кому они нужны, если баг не оформлен как баг? Чо, неужто надо перевести? "expected behavior" - ожидаемое поведение, "actual behavior" - реальное поведение, "matches" - совпадают. Раз совпадают, значит нет никакого бага. И там и без этого нихера нет внятного описания, а в чем собственно проблема. Без этого на скриншоты никто смотреть не будет.
