### ISSUE TITLE
Issue when installing x64 Win

### ISSUE THREAD

**Issue by orgcreator** [telegramdesktop/tdesktop#26454]
### Steps to reproduce

I've installed all as in instruction of build - but after this step:

git clone --recursive https://github.com/telegramdesktop/tdesktop.git
tdesktop\Telegram\build\prepare\win.bat

I'm getting this error:

iwr : Download from your IP address is not allowed
At line:1 char:1
+ iwr -OutFile ./jom.zip https://master.qt.io/official_releases/jom/jom ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
[5/26](ThirdParty/jom): FAILED
FAILED

And then when I've done this step:

configure.bat x64 -D TDESKTOP_API_ID=YOUR_API_ID -D TDESKTOP_API_HASH=YOUR_API_HASH

I also got this error:

Warn about uninitialized values.
Version: 4.8.4
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
CMake Error at cmake/external/qt/package.cmake:32 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:64 (include)

### Expected behaviour

I've got this issues during installing in Visual Stusio 2022 as you discribe in you instruction of build

### Actual behaviour

I've got this issues during installing in Visual Stusio 2022 as you discribe in you instruction of build

### Operating system

Windows x64

### Version of Telegram Desktop

I've got this issues during installing in Visual Stusio 2022 as you discribe in you instruction of build

### Installation source

Static binary from official website

### Crash ID

I've got this issues during installing in Visual Stusio 2022 as you discribe in you instruction of build

### Logs

```shell
I've got this issues during installing in Visual Stusio 2022 as you discribe in you instruction of build
```

**Comment by orgcreator** [comment]
Russia

**Comment by Aokromes** [comment]
yeah maybe that's the problem, banned russian isp.

**Comment by orgcreator** [comment]
Listing of Win32 installing is the same - so all about sunctions?

**Comment by orgcreator** [comment]
Я конешн ничего не имею против - но бл... целый день потратил ведь вчера с Android Studio и Telegrm X сегодня с Win64 - почему просто не написать что для РФ недоступно - зачем эти игры тогда - раз это не по вине разработчика и зачем этот негатив теперь(((

**Comment by ilya-fedin** [comment]
> iwr : Download from your IP address is not allowed

You can't build Telegram due to this error. You have to overcome it somehow and make prepare.py succeed or give up.

**Comment by orgcreator** [comment]
or write your messenger on Delphi?😉
