### ISSUE TITLE
Application crash when renaming an active session

### ISSUE THREAD

**Issue by suprunchuk** [telegramdesktop/tdesktop#26452]
### Steps to reproduce

_Precondition_: You must have at least one active session in your account.

1. Download and install the **portable** version of Telegram v4.8.3 x64 on your PC.
2. Log in to your account.
3. Open "Settings" -> "Privacy and Security" -> "Show all sessions".
4. In the "this device" section, click "rename".
5. Enter any new name. Click the "save" button.

![1](https://github.com/telegramdesktop/tdesktop/assets/57152612/ca52c9a5-097d-4c79-a21d-4e3a000bc1b4)

### Expected behaviour

The new name of your current device should be saved.

### Actual behaviour

When you click the save button, the application crashes.

### Operating system

windows 10 pro

### Version of Telegram Desktop

portable v4.8.3 x64

### Installation source

Static binary from official website

### Crash ID

56b54f7f-28f0-406b-b866-a68b61ba6078

**Comment by 2raghu** [comment]
Seems issue is specific with Windows 10 pro.
I could not reproduce on

Edition	Windows 11 Pro
Version	22H2
Installed on	‎3/‎9/‎2023
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0

Do you see the issue only with portable version ?
I have not tried reproduction on Win10 pro.
