### ISSUE TITLE
Problem with win32 version installing

### ISSUE THREAD

**Issue by orgcreator** [telegramdesktop/tdesktop#26456]
### Steps to reproduce

At the last step after 

git clone --recursive https://github.com/telegramdesktop/tdesktop.git
tdesktop\Telegram\build\prepare\win.bat

I'm getting this error:
![image](https://github.com/telegramdesktop/tdesktop/assets/45131232/be365158-6d07-4a08-9681-382f831ed6be)

### Expected behaviour

tdesktop\Telegram\build\prepare\win.bat

### Actual behaviour

tdesktop\Telegram\build\prepare\win.bat

### Operating system

Windows 2012 DC R2

### Version of Telegram Desktop

tdesktop\Telegram\build\prepare\win.bat

### Installation source

Static binary from official website

### Crash ID

tdesktop\Telegram\build\prepare\win.bat

### Logs

```shell
tdesktop\Telegram\build\prepare\win.bat
```

**Comment by ilya-fedin** [comment]
You have a problem with your Internet connection, the URL is inaccessible for the script

**Comment by ilya-fedin** [comment]
I also don't think you can build with Windows <10 due to old PowerShell, Visual Studio and what not

**Comment by orgcreator** [comment]
Ok thank you - i had built all in Win 10🥳🥳🥳
