### ISSUE TITLE
Issue during install Win64 

### ISSUE THREAD

**Issue by orgcreator** [telegramdesktop/tdesktop#26457]
### Steps to reproduce

I changed my IP & i/m trying to install Win64 Telegram - now - after 

git clone --recursive https://github.com/telegramdesktop/tdesktop.git
tdesktop\Telegram\build\prepare\win.bat

I'm getting this error:

Cloning into 'opus'...
remote: Enumerating objects: 35530, done.
remote: Counting objects: 100% (4333/4333), done.
remote: Compressing objects: 100% (1146/1146), done.
remote: Total 35530 (delta 2665), reused 4288 (delta 2635), pack-reused 31197
Receiving objects: 100% (35530/35530), 11.06 MiB | 577.00 KiB/s, done.
Resolving deltas: 100% (27336/27336), done.
Note: switching to 'e85ed7726db5d677c9c0677298ea0cb9c65bdd23'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Auto-merging CMakeLists.txt
Auto-merging opus_functions.cmake
Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'orgcr@LAPTOP-ISP2NJAL.(none)')
[11/26](Libraries/opus): FAILED
FAILED

-----------------------------------------------------------------

Then I'm trying 
configure.bat x64 -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb

And got this error:

C:\Users\secure\TelegramWin>cd C:\Users\secure\TelegramWin\tdesktop\Telegram

C:\Users\secure\TelegramWin\tdesktop\Telegram>configure.bat x64 -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb
Warn about uninitialized values.
-- Building for: Visual Studio 17 2022
Version: 4.8.4
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.36.32535.0
-- The CXX compiler identification is MSVC 19.36.32535.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find QT (missing: QT_DIR)
CMake Error at cmake/external/qt/package.cmake:35 (message):
  Neither Qt6 nor Qt5 is found
Call Stack (most recent call first):
  CMakeLists.txt:64 (include)

-- Configuring incomplete, errors occurred!
See also "C:/Users/secure/TelegramWin/tdesktop/out/CMakeFiles/CMakeOutput.log".

C:\Users\secure\TelegramWin\tdesktop\Telegram>

--------------------------------------------------------------
Please - contact me on Telegram @orgcreator and help with installing Telegram Desktop for develop mode🙏🙏🙏

### Expected behaviour

Please - contact me on Telegram @orgcreator and help with installing Telegram Desktop for develop mode🙏🙏🙏

### Actual behaviour

Please - contact me on Telegram @orgcreator and help with installing Telegram Desktop for develop mode🙏🙏🙏

### Operating system

Windows x64 10

### Version of Telegram Desktop

Please - contact me on Telegram @orgcreator and help with installing Telegram Desktop for develop mode🙏🙏🙏

### Installation source

Static binary from official website

### Logs

```shell
Please - contact me on Telegram @orgcreator and help with installing Telegram Desktop for develop mode🙏🙏🙏
```

**Comment by ilya-fedin** [comment]
It says what you should do in clear English

**Comment by ilya-fedin** [comment]
And please don't even try to run configure.py until you make prepare.py success

**Comment by orgcreator** [comment]
Ok thank you - i had built all in Win 10🥳🥳🥳
