### ISSUE TITLE
Prepare breakpad  error on win11

### ISSUE THREAD

**Issue by karlcreep** [telegramdesktop/tdesktop#26463]
### Steps to reproduce

1. x64 Native Tools Command Prompt for VS 2022.bat
2. cd BuildPath and run git clone --recursive https://github.com/telegramdesktop/tdesktop.git
3. run tdesktop\Telegram\build\prepare\win.bat

### Expected behaviour

All libraries will be installed. but the breakpad is an error.

### Actual behaviour

breakpad error
background: 1. win11 
                     2. python3.11.4  
                     3. git version 2.35.1.windows.2
                     4. Cmake version 3.27.0-rc3
I have tried setutf8 for shell it doesn't work.
and also set local for English. 

### Operating system

win11 x64 

### Version of Telegram Desktop

master

### Installation source

Static binary from official website

### Logs

```shell
[21/26](Libraries/openal-soft#0.2): SKIPPING
[22/26](Libraries/breakpad): CHANGED, (r)ebuild, rebuild (a)ll, (s)kip, (p)rint, (q)uit?: BUILDING:
---------------------------------COMMANDS-LIST----------------------------------
if exist breakpad rmdir /Q /S breakpad
if exist breakpad exit /b 1
git clone https://chromium.googlesource.com/breakpad/breakpad
cd breakpad
git checkout dfcb7b6799
git apply ../patches/breakpad.diff
git clone -b release-1.11.0 https://github.com/google/googletest src/testing
SET "PYTHONUTF8=1"
if "%X8664%" equ "x64" (
SET "FolderPostfix=_x64"
) else (
SET "FolderPostfix="
)
%THIRDPARTY_DIR%\python\Scripts\activate.bat
cd src\client\windows
gyp --no-circular-check breakpad_client.gyp --format=ninja
cd ..\..
ninja -C out/Debug%FolderPostfix% common crash_generation_client exception_handler
ninja -C out/Release%FolderPostfix% common crash_generation_client exception_handler
cd tools\windows\dump_syms
gyp dump_syms.gyp --format=msvs
msbuild dump_syms.vcxproj /property:Configuration=Release /property:Platform="x64"
deactivate
--------------------------------------------------------------------------------
Cloning into 'breakpad'...
remote: Total 22468 (delta 16993), reused 22468 (delta 16993)Receiving objects: 100% (22468/22468), 41.81 MiB | 6.53 MiBReceiving objects: 100% (22468/22468), 43.91 MiB | 6.22 MiB/s, done.

Resolving deltas: 100% (16993/16993), done.
Updating files: 100% (924/924), done.
Note: switching to 'dfcb7b6799'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at dfcb7b67 Revert "Fix incorrect source file name for inlined frames"
warning: src/build/gyp_breakpad has type 100644, expected 100755
Cloning into 'src/testing'...
remote: Enumerating objects: 26556, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 26556 (delta 71), reused 87 (delta 40), pack-reused 26423
Receiving objects: 100% (26556/26556), 12.36 MiB | 6.66 MiB/s, done.
Resolving deltas: 100% (19708/19708), done.
Note: switching to 'e2239ee6043f73722e7aa812a459f54a28552929'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\input.py:1186: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if the_dict_key is 'variables' and variable_name in the_dict:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\17688\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17688\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 2468, in CallGenerateOutputForConfig
    GenerateOutputForConfig(target_list, target_dicts, data, params, config_name)
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 1974, in GenerateOutputForConfig
    cl_paths = gyp.msvs_emulation.GenerateEnvironmentFiles(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\msvs_emulation.py", line 1061, in GenerateEnvironmentFiles
    raise Exception('"%s" failed with error %d' % (args, popen.returncode))
Exception: "['C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat', 'amd64_x86', '&&', 'set']" failed with error 255
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\__init__.py", line 552, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\__init__.py", line 545, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 2494, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "C:\Users\17688\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17688\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 774, in get
    raise self._value
Exception: "['C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat', 'amd64_x86', '&&', 'set']" failed with error 255
[22/26](Libraries/breakpad): FAILED
FAILED

C:\Users\17688\source\repos\telegram-k>git --version
git version 2.35.1.windows.2

C:\Users\17688\source\repos\telegram-k>which cmake
'which' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\17688\source\repos\telegram-k>cmake  --version
cmake version 3.27.0-rc3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by ilya-fedin** [comment]
> python3.11.4

Ah, I see, it's the mistake, the documentation says you need 3.10, it means you need exactly 3.2.0

**Comment by ilya-fedin** [comment]
Who knows what a error was with 3.10...

**Comment by karlcreep** [comment]
> C

here is python 310,I cant finger out what happen....
---------------------------------COMMANDS-LIST----------------------------------
if exist breakpad rmdir /Q /S breakpad
if exist breakpad exit /b 1
git clone https://chromium.googlesource.com/breakpad/breakpad
cd breakpad
git checkout dfcb7b6799
git apply ../patches/breakpad.diff
git clone -b release-1.11.0 https://github.com/google/googletest src/testing
SET "PYTHONUTF8=1"
if "%X8664%" equ "x64" (
SET "FolderPostfix=_x64"
) else (
SET "FolderPostfix="
)
%THIRDPARTY_DIR%\python\Scripts\activate.bat
cd src\client\windows
gyp --no-circular-check breakpad_client.gyp --format=ninja
cd ..\..
ninja -C out/Debug%FolderPostfix% common crash_generation_client exception_handler
ninja -C out/Release%FolderPostfix% common crash_generation_client exception_handler
cd tools\windows\dump_syms
gyp dump_syms.gyp --format=msvs
msbuild dump_syms.vcxproj /property:Configuration=Release /property:Platform="x64"
deactivate
--------------------------------------------------------------------------------
Cloning into 'breakpad'...
remote: Total 22468 (delta 16993), reused 22468 (delta 16993)
Receiving objects: 100% (22468/22468), 43.91 MiB | 7.09 MiB/s, done.
Resolving deltas: 100% (16993/16993), done.
Note: switching to 'dfcb7b6799'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at dfcb7b67 Revert "Fix incorrect source file name for inlined frames"
warning: src/build/gyp_breakpad has type 100644, expected 100755
Cloning into 'src/testing'...
remote: Enumerating objects: 26561, done.
remote: Counting objects: 100% (138/138), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 26561 (delta 71), reused 92 (delta 43), pack-reused 26423
Receiving objects: 100% (26561/26561), 12.37 MiB | 9.41 MiB/s, done.
Resolving deltas: 100% (19706/19706), done.
Note: switching to 'e2239ee6043f73722e7aa812a459f54a28552929'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\input.py:1186: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if the_dict_key is 'variables' and variable_name in the_dict:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\17688\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\17688\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 2468, in CallGenerateOutputForConfig
    GenerateOutputForConfig(target_list, target_dicts, data, params, config_name)
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 1974, in GenerateOutputForConfig
    cl_paths = gyp.msvs_emulation.GenerateEnvironmentFiles(
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\msvs_emulation.py", line 1061, in GenerateEnvironmentFiles
    raise Exception('"%s" failed with error %d' % (args, popen.returncode))
Exception: "['C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat', 'amd64_x86', '&&', 'set']" failed with error 255
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\__init__.py", line 552, in script_main
    return main(sys.argv[1:])
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\__init__.py", line 545, in main
    return gyp_main(args)
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\17688\source\repos\telegram-k\ThirdParty\gyp\pylib\gyp\generator\ninja.py", line 2494, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "C:\Users\17688\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\17688\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
Exception: "['C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat', 'amd64_x86', '&&', 'set']" failed with error 255
[22/26](Libraries/breakpad): FAILED
FAILED

**Comment by karlcreep** [comment]
> Contributor

@Aokromes
 hello， Why close issue without confirmation？
 I have searched for issues but couldn't find a solution

**Comment by ilya-fedin** [comment]
Because you have opened it while not following the instruction (wrong python version)

**Comment by karlcreep** [comment]
> 

Did you see my previous reply? I upgraded because I used the version specified in the documentation and made an error.

**Comment by karlcreep** [comment]
> 
The command executed when the error occurs is:
 " gyp --no-circular-check breakpad_client.gyp --format=ninja"
Do you have some suggestion？
