### ISSUE TITLE
Downloaded MP4 videos can't be opened by Quicktime

### ISSUE THREAD

**Issue by ixzh** [telegramdesktop/tdesktop#26465]
### Steps to reproduce

1. Upload a MP4 file
2. Download it
3. The default Quicktime player can't open it.

### Expected behaviour

It should be opened in quicktime when double clicking on it

### Actual behaviour

not playable in quicktime as shown below. MPV can play it.
<img width="452" alt="image" src="https://github.com/telegramdesktop/tdesktop/assets/14981695/45467e99-a638-47e5-bd31-9d99c36cb0dd">

Is it because some meta-data gets stripped off during upload?

### Operating system

MacOS

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop uploads and downloads videos as-is

**Comment by ixzh** [comment]
issue closed... 🤔 maybe I should check again and find the reason
