### ISSUE TITLE
Top folder bar option in mobile/compact view

### ISSUE THREAD

**Issue by Rong-Yao** [telegramdesktop/tdesktop#26464]
### Is your feature request related to a problem?

Current folder view stands on a side without an option to be collapsed or expanded and i am trying personally to keep teelgram most compacted at the end of my screen when i am working.

### Describe the solution you'd like

I would love to see additional option if the side folder bar can be changed to be top folder bar with scrolling left and right with the mouse wheel to keep width requirements as minimalistic as possible.

### Describe alternatives you've considered

Collapsable side menu on click or point with mouse over which overlays the contact list instead but i think overlaying the contacts may be more annoying for some people, so introducing a new additional option might be more beneficial.

### Additional context

![image](https://github.com/telegramdesktop/tdesktop/assets/8936268/74b52157-6006-45cb-bcc2-fb6679139a75)
Image mockup of the default behaviour and suggested behaviour.
The mobile version of telegram already have a top folder bar so i would love to see it in the desktop as well.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25732
