### ISSUE TITLE
problem with ./configure build ffmpeg on msys2_shell.bat

### ISSUE THREAD

**Issue by AisakaYue** [telegramdesktop/tdesktop#2646]
The problem is when i run this command for build ffmpeg in msys2_shell.bat

_./configure --toolchain=msvc --disable-programs --disable-doc --disable-everything --enable-protocol=file --enable-libopus --enable-decoder=aac --enable-decoder=aac_latm --enable-decoder=aasc --enable-decoder=flac --enable-decoder=gif --enable-decoder=h264 --enable-decoder=mp1 --enable-decoder=mp1float --enable-decoder=mp2 --enable-decoder=mp2float --enable-decoder=mp3 --enable-decoder=mp3adu --enable-decoder=mp3adufloat --enable-decoder=mp3float --enable-decoder=mp3on4 --enable-decoder=mp3on4float --enable-decoder=mpeg4 --enable-decoder=msmpeg4v2 --enable-decoder=msmpeg4v3 --enable-decoder=wavpack --enable-decoder=opus --enable-decoder=vorbis --enable-decoder=wmalossless --enable-decoder=wmapro --enable-decoder=wmav1 --enable-decoder=wmav2 --enable-decoder=wmavoice --enable-encoder=libopus --enable-hwaccel=h264_d3d11va --enable-hwaccel=h264_dxva2 --enable-parser=aac --enable-parser=aac_latm --enable-parser=flac --enable-parser=h264 --enable-parser=mpeg4video --enable-parser=mpegaudio --enable-parser=opus --enable-parser=vorbis --enable-demuxer=aac --enable-demuxer=flac --enable-demuxer=gif --enable-demuxer=h264 --enable-demuxer=mov --enable-demuxer=mp3 --enable-demuxer=ogg --enable-demuxer=wav --enable-muxer=ogg --enable-muxer=opus --extra-ldflags="-libpath:/c/TBuild/Libraries/opus/win32/VS2010/Win32/Release celt.lib silk_common.lib silk_float.lib"_

Then i get this error:

_./configure: line 3156: uname: command not found
./configure: line 509: tr: command not found
./configure: line 3164: uname: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 517: sed: command not found
./configure: line 3270: sed: command not found
./configure: line 3270: sed: command not found
./configure: line 3270: sed: command not found
./configure: line 3270: sed: command not found
./configure: line 3270: sed: command not found
./configure: line 3270: sed: command not found
./configure: line 3270: sed: command not found
./configure: line 3270: sed: command not found
./configure: line 3270: sed: command not found
./configure: line 3287: sed: command not found
./configure: line 3287: sed: command not found
./configure: line 505: tr: command not found
./configure: line 505: tr: command not found
./configure: line 505: tr: command not found
./configure: line 505: tr: command not found
./configure: line 505: tr: command not found
./configure: line 505: tr: command not found
./configure: line 505: tr: command not found
./configure: line 505: tr: command not found
./configure: line 505: tr: command not found
./configure: line 505: tr: command not found
./configure: line 505: tr: command not found
./configure: line 3427: sed: command not found
Unknown option "--toolchain=msvc".
See ./configure --help for available options._

**Operating system**
Windows 10 Build 14393 with Visual Studio Communiy 2015

What is the problem?

**Comment by stek29** [comment]
Are you sure you're running this in msys bash and not in CMD?

**Comment by AisakaYue** [comment]
Thank you for your answer :) I'm sure i running this in msys bash and you mean the problem is my msys?

**Comment by stek29** [comment]
Yes, I mean the problem is your msys.
Maybe `sed` and `tr` should be installed, but `uname`?...
Maybe something is wrong with `PATH`

**Comment by AisakaYue** [comment]
I will check my msys and PATH,thank you.
