### ISSUE TITLE
no "view stats" button in post context menu

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#26469]
### Steps to reproduce

1. Press RMB on post that has forwards.
2. No "view stats" option.

### Expected behaviour

Have "view stats" button like in telegram for android:
![Screenshot_20230701-080342_Nekogram](https://github.com/telegramdesktop/tdesktop/assets/5204968/2cbb3957-02f1-4054-ad94-da4949306388)

### Actual behaviour

No such option:
![Снимок экрана 2023-07-01 080312](https://github.com/telegramdesktop/tdesktop/assets/5204968/f6ebcda7-3186-4008-8b07-cb5c4007e9e0)

### Operating system

Windows 11 Pro

### Version of Telegram Desktop

4.8.4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
duplicate.

**Comment by soredake** [comment]
Can you at least say duplicated of what?
