### ISSUE TITLE
Auto-night mode checkbox disappears after change scale on linux

### ISSUE THREAD

**Issue by Vyachean** [telegramdesktop/tdesktop#26461]
### Steps to reproduce

1. checking auto-night mode setting
2. change scale in telegram settings
3. checking auto-night mode setting, setting is missing

### Expected behaviour

1. checking auto-night mode setting
2. change scale in telegram settings
3. checking auto-night mode setting, there is an auto-night mode setting

### Actual behaviour

After change scale, there is missing auto-night mode setting. And it comes back after a mode change in the system.

### Operating system

Fedora Linux 38.20230624.0 (Silverblue)

### Version of Telegram Desktop

4.8.4 from flathub

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
This sounds like a GNOME bug to me: apparently GNOME loses the preference and so the option disappears.
