### ISSUE TITLE
Not Working Audio when using multiple devices

### ISSUE THREAD

**Issue by AndreySkyFoxSidorov** [telegramdesktop/tdesktop#26474]
### Steps to reproduce

1. Connect multiple devices (Ensure that you have multiple microphones available for connection.) to the system.
2. Open voice call or sound recording that allows microphone usage, such as a voice recording or video conferencing.
3. Begin recording audio or speaking into the selected microphone to test its functionality.
4. The Telegram application does not allow for microphone selection, especially when using Bluetooth headsets. After connecting Bluetooth headsets, Telegram does not automatically switch to them and does not provide the option to choose audio input and output sources.

### Expected behaviour

 In the audio call window, there should be options available to select the audio input and output devices, as well as the ability to choose from multiple cameras if available.

### Actual behaviour

Telegram does not provide the option to select the device directly. Users are required to go into the system settings, choose the default device, and then completely restart Telegram. This is highly inconvenient, especially when using Bluetooth headphones that are not constantly in use.
Please note that competitors of Telegram, such as Zoom, Discord, and meet.jit, provide the ability to change the audio and video devices during a call without requiring a restart of the application. This feature is greatly missed in Telegram.

### Operating system

Windows 10

### Version of Telegram Desktop

v4.8.1 24.04.23

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#9814, #24802
