### ISSUE TITLE
Hide amount of gift from receiver

### ISSUE THREAD

**Issue by NgoHuy** [telegramdesktop/tdesktop#26477]
### Is your feature request related to a problem?

When I gifted to my friend, the amount is showed on their side. I think we should hide it as politeness.

### Describe the solution you'd like

Just simply the message: [User] sent you a gift for special reason/day.

### Describe alternatives you've considered

It showed on other side: User sent you a gift for xxx currency

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
