### ISSUE TITLE
Video call is broken

### ISSUE THREAD

**Issue by Vlod-github** [telegramdesktop/tdesktop#26471]
### Steps to reproduce

Install telegram on PC
Install a unity camera on your PC
Install telegram on android
Restart PC
Make a call from android to PC or from PC to android 

### Expected behaviour

Firstly, it is expected that regardless of the hardware status of the devices or drivers, the connection will succeed if the internet is available.

Secondly, an inoperative camera on the PC is not expected to interfere with video streaming from the phone.

### Actual behaviour

Actually connection cannot be established between Telegram Desktop 4.8.3 and android versions 9.5.3, 9.6.5, 9.6.7 (On android state reconnect, on PC state exchange encryption keys, and so on infinitely)

For Telegram Desktop version 4.8.3 and android version 9.3.3, a regular voice call may be set. However, trying to enable video broadcasting on the phone has no effect.

### Operating system

Windows 10, Android 7

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by manfred-h** [comment]
I saw similar issues with Telegram Desktop 4.8.4 on openSUSE Tumbleweed which is using openssl3 by default. We explicitly requested to stick with openssl-1_1 and calls are working again. Perhaps this helps to isolate the problem.

**Comment by Vlod-github** [comment]
I added the item "reboot PC" because the bug happens randomly, but if I managed to call at least once, the bug does not appear in that session anymore. (I tested for half an hour) Secondly, the problem is solved by restarting the telegram.

**Comment by Vlod-github** [comment]
So I assume that this is a problem of interaction between telegram and windows, (which may also be on the windows side, but still it is logical to take this into account when interacting)

**Comment by john-preston** [comment]
@manfred-h Calls should be fixed in OpenSSL 3 on the latest code.

**Comment by john-preston** [comment]
@Vlod-github Can you check 4.8.10?

**Comment by manfred-h** [comment]
I just tried to build everything on openSUSE Tumbleweed, which is quite challenging due to:

- glib2 is required to be >= 2.77, but this does not (yet) exist on Tumbleweed
- glibmm2 is required to be >= 2.77, but this also does not exist on Tumbleweed - it's worse that upstream marks this release as "unstable"

I built my own versions for these two packages and used them to build telegram-desktop, but failed compiling <Telegram/lib_base/base/platform/linux/base_network_reachability_linux.cpp> which erroneously uses <sigc::track_object> instead of <sigc::track_obj>, which works with glib-2.77.2, at least.

After successfully building the whole stuff, key-exchange fails the same way as it did before :(

**Comment by ilya-fedin** [comment]
@manfred-h you need to update tg_owt, not tdesktop

**Comment by ilya-fedin** [comment]
Yeah, github sadly doesn't archive submodules so you have to download them manually into the directories. In case of crc32c you can use a system package.

**Comment by manfred-h** [comment]
@ilya-fedin: the submodules are not the problem, as I wrote, their sources are included in the tarball. Trouble is, that e.g. openSUSE Leap 15.4 doesn't provide `cmake(Crc32c)`, so it needs to build the packaged sources itself. The same is true for `cmake(absl)`, which exists in Leap 15.5 and 15.6, but that version is too old, so I need to be able to glue these submodules to the base tree.

**How** do it do it?

**Comment by ilya-fedin** [comment]
I have a question: what would you do if there were no submodules? Most other projects don't provide submodules, they only find a packaged version. Think about that and do exactly what you would do in such case.

**Comment by manfred-h** [comment]
@ilya-fedin: simple answer: I would give up if the distribution provided package does not fulfill the required features.

As I wrote before, I'm by no means cmake capable, how/where do I define these mentioned variables `Crc32c_DIR` or `absl_DIR`? To my understanding, these are the missing pieces to make the submodules available to the rest of the whole tree.

**Comment by ilya-fedin** [comment]
> how/where do I define these mentioned variables `Crc32c_DIR` or `absl_DIR`?

`cmake -DCrc32c_DIR=... -Dabsl_DIR=...`. Or you rather can specify CMAKE_PREFIX_PATH to rule them all.

> To my understanding, these are the missing pieces to make the submodules available to the rest of the whole tree.

To make them work via the submodule code, you just need to download them and copy the content to the tg_owt source tree [as I already said](https://github.com/telegramdesktop/tdesktop/issues/26471#issuecomment-1678742157).

**Comment by ilya-fedin** [comment]
honestly, trying to build newer software on an old distro ends with lots of pain almost always. I recommend to use static binary/flatpak/snap, that's exactly for all this was invented.

**Comment by manfred-h** [comment]
Another thing is, "on an old distro", the referenced versions are still fully supported... New features as requested by some packages may require to find a way to make these features usable on the still supported, but ancient distros. This is my only thing I want to find out!

**Comment by manfred-h** [comment]
BUT, the

`cmake -DCrc32c_DIR=... -Dabsl_DIR=...`

piece really should help me further. Thanks a lot for that!

**Comment by ilya-fedin** [comment]
> Honestly2, are you saying you don't know how to actually make use of the submodules? If so, why are they included at all?

I already said two times how to make use of them.
