### ISSUE TITLE
Message context menu closes after hovering menu items

### ISSUE THREAD

**Issue by cca310** [telegramdesktop/tdesktop#26475]
### Steps to reproduce

1. Right click/open context menu on message box
2. Hover mouse over menu selections
3. Context menu closes

[Screencast from 2023-07-04 01-19-53.webm](https://github.com/telegramdesktop/tdesktop/assets/36178056/8b117f14-4526-4865-b2e0-5fa947f17047)

### Expected behaviour

User can select menu items

### Actual behaviour

Context menu closes after hovering mouse

### Operating system

Fedora 38 GNOME

### Version of Telegram Desktop

4.8.4

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
#26407
