### ISSUE TITLE
Voice messages on Telegram Android are missing on desktop

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#26478]
### Steps to reproduce

I normally rarely send VMs on my cell phone, but yesterday I didn't have access to my computer.

I spent 2 hours sending voice messages & one text to one person & I was wondering why I couldn't see any of the messages prior to July 2nd, but on the desktop I can't see any messages after July 1st.

I can't even take a screenshot of my phone because you guys block SSs & I'm nervous about messaging him on the desktop because what if I lose everything on the cell if I do that?

I'm not even sure he got them.

Help.

That's 2 hours I spent that I don't want to lose. 

### Expected behaviour

Both the android & desktop sync

### Actual behaviour

The messages are missing on both platforms. Each one is missing the other's messages.

### Operating system

Windows 10

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
> I can't even take a screenshot of my phone because you guys block SSs & I'm nervous about messaging him on the desktop because what if I lose everything on the cell if I do that?

if you have "blocked screenshots" it means you are using secret chats and telegram desktop doesn't support secret chats.

**Comment by ILoveSkilledCoders** [comment]
> > I can't even take a screenshot of my phone because you guys block SSs & I'm nervous about messaging him on the desktop because what if I lose everything on the cell if I do that?
> 
> if you have "blocked screenshots" it means you are using secret chats and telegram desktop doesn't support secret chats.

I have no idea what you are talking about. I didn't do anything with secret chats. I don't even know how to use secret chats & if you don't allow secret chats, then how did my VMs b/c secret chats?

I just went to TG & that person & started recording.

So are you going to fix the problem? 

OMG, ALL OF MY VMs on my cell phone are now gone. 

I'm not happy about this at all. 2 hours of my life down the DRAIN!!!
