### ISSUE TITLE
build on asahi linux fails at poetry

### ISSUE THREAD

**Issue by treeshateorcs** [telegramdesktop/tdesktop#26485]
### Steps to reproduce

after i run 

```
poetry run gen_dockerfile | DOCKER_BUILDKIT=1 docker build -t tdesktop:centos_env -
```

### Expected behaviour

build fails

### Actual behaviour

```bash
$ poetry run gen_dockerfile | DOCKER_BUILDKIT=1 docker build -t tdesktop:centos_env -

[+] Building 2.4s (4/4) FINISHED                                                      
 => [internal] load build definition from Dockerfile                             0.0s
 => => transferring dockerfile: 30.49kB                                          0.0s
 => [internal] load .dockerignore                                                0.0s
 => => transferring context: 2B                                                  0.0s
 => resolve image config for docker.io/docker/dockerfile:1                       1.6s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:39b85bbfa7536a5f  0.0s
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: exit code: 1
```

### Operating system

fedora asahi remix (aarch64, arm64)

### Version of Telegram Desktop

8bd9293

### Installation source

Other (unofficial) source

### Logs

```shell
i've tried every possible solution from [this](https://stackoverflow.com/questions/64221861/an-error-failed-to-solve-with-frontend-dockerfile-v0) page to no avail
```

**Comment by ilya-fedin** [comment]
I don't think it will work, the Dockerfile downloads amd64 executables and uses repos that provide only i386 and amd64 builds

**Comment by treeshateorcs** [comment]
so no way to run telegram desktop on asahi fedora?

**Comment by ilya-fedin** [comment]
You can use flatpak, snap, distro package?

**Comment by treeshateorcs** [comment]
flatpak is not an option because of the 16k page size (the same may go to snap too), and it's no longer packaged in fedora.

i'll try archlinuxarm's PKGBUILD!

**Comment by ilya-fedin** [comment]
> and it's no longer packaged in fedora

AFAIK it is

**Comment by dmatora** [comment]
@treeshateorcs I am having same issue with asahi ubuntu, have you solved this?

**Comment by treeshateorcs** [comment]
@dmatora i don't know how to solve this for ubuntu, there must be a third party build, maybe some ppa

**Comment by treeshateorcs** [comment]
as a last resort use the commands from this script https://gitlab.archlinux.org/archlinux/packaging/packages/telegram-desktop/-/blob/main/PKGBUILD

**Comment by ilya-fedin** [comment]
Ubuntu usually has too old libraries to build latest tdesktop as tdesktop is bleeding edge while both Debian and Ubuntu update packages very rarely, so it would require building half of the system libraries with up-to-date versions just like the Dockerfile with CentOS does. and I guess no one really has time to maintain such a PPA.

**Comment by treeshateorcs** [comment]
or you can also try rebuilding jemalloc as i suggested [here](https://github.com/telegramdesktop/tdesktop/issues/24836#issuecomment-1235866478) (but that's for arch, it may or may not work on ubuntu)

**Comment by ilya-fedin** [comment]
You would need to build tdesktop then what seems to be unrealistic for you folks

**Comment by dmatora** [comment]
Well, I'm a Mac guy and this is little above my head

**Comment by ilya-fedin** [comment]
Yeah, that's the general problem with having official ARM builds at all. No one from the community has stepped up to create cross-compilation scripts.
