### ISSUE TITLE
bug: input device from call settings should also be used for voice message recording

### ISSUE THREAD

**Issue by voidpointer0x00** [telegramdesktop/tdesktop#26489]
### Steps to reproduce

1. Set the input device to anything but system's default device. <= everything works as expected
2. Record a voice message. <= fallback to default input stream happens

### Expected behaviour

Telegram should respect it's own settings :)

### Actual behaviour

The application fallbacks to system's default input source avoiding any streams from the configuration.
While changing the settings:
![image](https://github.com/telegramdesktop/tdesktop/assets/43143315/f1a65b62-58b2-4044-8347-4d6cb4ad2e21)
![image](https://github.com/telegramdesktop/tdesktop/assets/43143315/1f45f23a-dd86-4e3f-97b5-3855d5831075)

When recording a vocie message:
![image](https://github.com/telegramdesktop/tdesktop/assets/43143315/cf2a9e6e-ce7d-437e-95ea-c35182089c34)
_system settings:_
![image](https://github.com/telegramdesktop/tdesktop/assets/43143315/b27b3f41-d6ea-4f45-bfb8-816687acf7a9)

### Operating system

EndeavourOS Linux 6.4.1-arch2-1

### Version of Telegram Desktop

4.8.4-2

### Installation source

Other (unofficial) source

### Logs

```shell
The only related lines:

[2023.07.08 22:21:37] Audio Info: recreating audio device and reattaching the tracks
[2023.07.08 22:21:39] Audio Info: Closing audio playback device.
[2023.07.08 22:21:49] Audio Info: recreating audio device and reattaching the tracks
[2023.07.08 22:21:51] Audio Info: Closing audio playback device.
```
```

**Comment by voidpointer0x00** [comment]
A possible solution is to use `CurrentAudioInputName()` function on `alcCaptureOpenDevice(...)` call instead of `nullptr` as the first `device` argument.
https://github.com/telegramdesktop/tdesktop/blob/8bd9293a490332c28b77a3c712f57bb41db780bf/Telegram/SourceFiles/settings/settings_calls.h#L71
https://github.com/telegramdesktop/tdesktop/blob/8bd9293a490332c28b77a3c712f57bb41db780bf/Telegram/SourceFiles/media/audio/media_audio_capture.cpp#L245-L246
```cpp
#include "settings/settings_calls.h"
// ...
using Settings::CurrentAudioInputName;
d->device = alcCaptureOpenDevice(CurrentAudioInputName().toLatin1().data(), kCaptureFrequency, AL_FORMAT_MONO16, kCaptureFrequency / 5);
```

---
It builds, but I cannot test whether it works, because it does not link on my system for the following reason _(perhaps, a protobuf 23.4 related issue https://github.com/Cockatrice/Cockatrice/issues/4825)_:
```
[ 52%] Linking CXX static library liblib_base_crash_report_writer.a
[ 52%] Built target lib_base_crash_report_writer
/usr/bin/ld: ../cmake/external/cld3/libexternal_cld3_bundled.a(sentence.pb.cc.o): undefined reference to symbol '_ZN4absl12lts_2023012512log_internal21CheckOpMessageBuilder7ForVar2Ev'
/usr/bin/ld: /usr/lib/libabsl_log_internal_check_op.so.2301.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by ilya-fedin** [comment]
No, it shouldn't as they're clearly specified as call settings.

**Comment by ilya-fedin** [comment]
> DesktopInterface.cpp:(.text._ZN6webrtc32webrtc_sequence_checker_internal19ExpectationToStringINS_15SequenceCheckerEEENSt9enable_ifIX12is_base_of_vINS0_19SequenceCheckerImplET_EENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE4typeEPKS5_[_ZN6webrtc32webrtc_sequence_checker_internal19ExpectationToStringINS_15SequenceCheckerEEENSt9enable_ifIX12is_base_of_vINS0_19SequenceCheckerImplET_EENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE4typeEPKS5_]+0x2e): undefined reference to `webrtc::webrtc_sequence_checker_internal::SequenceCheckerImpl::ExpectationToString[abi:cxx11]() const'

tdesktop's and tg_owt's CMAKE_BUILD_TYPE must match.

**Comment by voidpointer0x00** [comment]
> No, it shouldn't as it's clearly specified as call settings.

Well, then maybe introduce "voice message input device" setting should be introduced? 😄

**Comment by ilya-fedin** [comment]
There's already a feature request for that

**Comment by voidpointer0x00** [comment]
> There's already a feature request for that

I can't seem to find it, could you please reference the issue or PR?

**Comment by ilya-fedin** [comment]
Really?
![изображение](https://github.com/telegramdesktop/tdesktop/assets/17829319/c036088e-1ea3-436d-b9c5-89935108a6ef)
