### ISSUE TITLE
`t.me/*` links don't open Telegram Desktop from Firefox, but do from Chrome.

### ISSUE THREAD

**Issue by rokejulianlockhart** [telegramdesktop/tdesktop#26482]
https://bugs.telegram.org/c/29732

### Steps to reproduce

1. Visit https://t.me/designers
2. Press View in Telegram in `firefox`.
    It doesn't work.
1. Press View in Telegram in `chrome-browser`.
    It works.

### Expected behaviour

It should still work in both browsers.

### Actual behaviour

It doesn't work in Firefox.

### Operating system

Operating System: openSUSE Tumbleweed 20230703
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.3.9-1-default (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: AMD Radeon RX 5700

### Version of Telegram Desktop

4.8.1

### Installation source

https://software.opensuse.org/package/telegram-desktop

**Comment by ilya-fedin** [comment]
It works for me

**Comment by ilya-fedin** [comment]
Third party distributors like to crop out the scheme registration (Debian does that or sure), so I recommend to test the official build

**Comment by SnowVolf** [comment]
Same issue. Fedora 38 / Gnome 44.1
But for me, all links has been opened with Chrome, ignores GNOME default settings

**Comment by ilya-fedin** [comment]
If firefox ignores your default settings, you should report that to firefox

**Comment by moveonwasd** [comment]
I assume their Firefox is flatpak installation

**Comment by ilya-fedin** [comment]
and? :thinking:

**Comment by rokejulianlockhart** [comment]
**https://github.com/telegramdesktop/tdesktop/issues/26482#issuecomment-1622858376**

> Third party distributors like to crop out the scheme registration (Debian does that for sure), so I recommend to test the official build from [desktop.telegram.org](https://desktop.telegram.org/)

@ilya-fedin,

```
PS /home/rokejulianlockhart> script -a
Script started, output log file is 'typescript'.
rokejulianlockhart@RQN6C6:~> sudo zypper remove telegram-desktop && sudo snap install telegram-desktop
[sudo] password for root: 
Reading installed packages...
Resolving package dependencies...

The following package is going to be REMOVED:
  telegram-desktop

1 package to remove.
After the operation, 86.6 MiB will be freed.
Continue? [y/n/v/...? shows all options] (y): y
(1/1) Removing telegram-desktop-4.8.1-1.4.x86_64 ....................................................................................................................................................................................................................................................................[done]
There are running programs which still use files and libraries deleted or updated by recent upgrades. They should be restarted to benefit from the latest updates. Run 'zypper ps -s' to list these programs.
 
telegram-desktop 4.8.4 from Telegram FZ-LLC (telegram-desktop✓) installed
rokejulianlockhart@RQN6C6:~> sudo snap switch telegram-desktop --channel=latest/edge
[sudo] password for root: 
"telegram-desktop" switched to the "latest/edge" channel

rokejulianlockhart@RQN6C6:~>
```

doesn't change anything, although [I am now using 4.8.4](https://github.com/telegramdesktop/tdesktop/assets/42837531/19eb916b-72c4-4222-8559-756d10d09a69) instead of 4.8.1, so we can be confident that I'm using the latest changes.

**Comment by ilya-fedin** [comment]
The snap doesn't have that code as it's in sandbox. What I meant is you should install what is provided by the big blue button, that's the official build, the remaining is alternative downloads.

**Comment by ilya-fedin** [comment]
Although I feel that it's a problem with firefox as chrome works.. Maybe you should report that to firefox? Or maybe even to your distro as firefox from official website works just fine for me on my distro.

**Comment by rokejulianlockhart** [comment]
@Aokromes, it can't be a sandbox issue, since only Firefox is affected, whereas Chrome works for both the unsandboxed distribution-native and Snap (sandboxed) package.

Also, if https://github.com/telegramdesktop/tdesktop/issues/26482#issuecomment-1629209303 is a known issue with the snap, why not request `--classic` confinement?

**Comment by ilya-fedin** [comment]
Well, feel free to try to request that on snapcraft forum, I bet they will decline that. They haven't allowed the snap to have removable-media permission even though people were unable to share files from flash drives. Just because they think a messenger shouldn't have such rights.

**Comment by ilya-fedin** [comment]
no, I don't think I will find it, there's a 5-digit amount of issues.

**Comment by rokejulianlockhart** [comment]
> https://github.com/telegramdesktop/tdesktop/issues/26482#issuecomment-1629215014 

I'll do so.

**Comment by ilya-fedin** [comment]
I don't think it's a good idea to do. Please try the official build first.

**Comment by rokejulianlockhart** [comment]
@ilya-fedin, I can't. What you link to isn't an installation package. It's a `.tar` archive file.

**Comment by ilya-fedin** [comment]
You don't know how to extract tar archives?

**Comment by rokejulianlockhart** [comment]
Is Telegram entirely self-contained? I don't mind just extracting an archive and running it, but I can't be expected to extract them into their respective HFS structures like `/bin`. You said "installation", so I expected that was what you meant.

**Comment by ilya-fedin** [comment]
Well, it won't work the best in a directory where it can't write, the best way is to install the content of the archive to your home directory

**Comment by Aokromes** [comment]
tested on antix linux, it worked there for me too, downloaded telegram desktop from desktop.telegram.org droped into a directory and firefox opened it.

**Comment by ilya-fedin** [comment]
> is Telegram entirely self-contained?

Not entirely but yeah, it's self-contained to reasonable extents

**Comment by ilya-fedin** [comment]
> Still doesn't work for me, so I expect that the issue is with Firefox, since the Firefox Snap package doesn't work either.

I wonder whether firefox snap uses the same profile as your previous firefox? It has its own mime override system IIRC, so your settings can break this.

**Comment by rokejulianlockhart** [comment]
@ilya-fedin, I've wondered that, but that tabs are separate, and quitting one doesn't quit the other, so I can only guess that at least the caches and binaries are different. Considering that the Flatpak package for Firefox uses self-contained preferences *until* one uses Flatseal or `flatpak` to provide broad filesystem permissions, they might share preferences.

**Comment by ilya-fedin** [comment]
`firefox -p --no-remote`

**Comment by ilya-fedin** [comment]
or `about:profiles`
