### ISSUE TITLE
Image viewer doesn't render to window border when not fullscreen.

### ISSUE THREAD

**Issue by rokejulianlockhart** [telegramdesktop/tdesktop#26481]
https://bugs.telegram.org/c/29731

### Steps to reproduce

1. Click on image to enlarge it whilst using https://wikipedia.org/wiki/KWin

    ![image](https://github.com/telegramdesktop/tdesktop/assets/42837531/56febab5-9a95-479a-a153-da948f974775)

3. Press Alt+F3 and disable fullscreen

    ![image](https://github.com/telegramdesktop/tdesktop/assets/42837531/75d4a4ea-aef2-4056-a08c-18027a61c2c5)

### Actual behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/42837531/2286833f-ef49-4df1-8935-ebcda078f707)

### Expected behaviour

The image, or at least the dark translucent border, should render to the edges of the window.

I believe that the best solution is to:

1. Invoke the image not in fullscreen, but instead in a window that chooses a sane size depending upon the image resolution, since this is way too large by default for large and/or less-than-4K monitors, and thus
3. Remove the black border padding, so that it renders to the window border, and
5. Remove the translucent background and replace it with the regular window background

### Operating system

Operating System: openSUSE Tumbleweed 20230703
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.3.9-1-default (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: AMD Radeon RX 5700

### Version of Telegram Desktop

6.8.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
That's weird, it's supposed to be frameless, the empty space should be transparent

**Comment by ilya-fedin** [comment]
I seem to be unable to reproduce

> 2\. Press F3 and disable fullscreen

This step does nothing on my machine

**Comment by rokejulianlockhart** [comment]
@ilya-fedin, are you using KWin and KDE Plasma?

**Comment by ilya-fedin** [comment]
well, I'm trying using a VM with KDE Neon

**Comment by rokejulianlockhart** [comment]
Apologies, I meant Alt+F3. It's an out-of-the-box keybind.

**Comment by ilya-fedin** [comment]
Now I'm getting a maximized window after step 2, not what no your screenshot

**Comment by rokejulianlockhart** [comment]
Send me a screenshot.

**Comment by ilya-fedin** [comment]
That's what I get with your steps:
![изображение](https://github.com/telegramdesktop/tdesktop/assets/17829319/67842e3e-cf0c-496d-9090-e64821b2efd1)
That's what I get if I unmaximize the window the normal way (via title controls):
![изображение](https://github.com/telegramdesktop/tdesktop/assets/17829319/d29593f6-cc89-415d-bb97-4e7d520b2627)

**Comment by rokejulianlockhart** [comment]
Understood, @ilya-fedin. Thanks.

Import https://github.com/telegramdesktop/tdesktop/files/11962605/ForceEnableWindowTitleBarAndFrame.kwinrule.zip into `kcmshell5 kcm_kwinrules` and ensure it looks like

![image](https://github.com/telegramdesktop/tdesktop/assets/42837531/4151dc16-ef4b-44dd-a682-10db5f61ce60)

This will definitely let you see the issue.

**Comment by ilya-fedin** [comment]
Broken UX after such rules is completely expected. You can't force application do what it's not designed to do and expect it will work as expected. You have voided your warranty.

**Comment by rokejulianlockhart** [comment]
@ilya-fedin, lots of Window Managers force SSD for a lot of reasons. For instance, Windows does it for accessibility purposes. I anecdotally know of two people who the same with KDE for that purpose. They introduced me to the functionality, although I only do it because the makes the system more intuitive.

**Comment by ilya-fedin** [comment]
This window doesn't support server-side decorations, that's just not implemented by designer's request and it won't be. You have to accept that or create a fork.

**Comment by rokejulianlockhart** [comment]
Then I'll close this as not planned, but please remove https://github.com/telegramdesktop/tdesktop/issues?q=is%3Aopen+label%3A%22cant+reproduce%22, @ilya-fedin.

**Comment by ilya-fedin** [comment]
It's another window. This one does support system window frame, yes. Media viewer, call windows are not.

**Comment by rokejulianlockhart** [comment]
Is allowing them to support it such an undesirable feature, @ilya-fedin?

**Comment by ilya-fedin** [comment]
there's already a request for call windows. Although I don't think such requests will be ever implemented. It's way more likely that the main window would lose such ability than the other way around.

**Comment by rokejulianlockhart** [comment]
@ilya-fedin, do you have the link for that request?

**Comment by ilya-fedin** [comment]
#10002

**Comment by rokejulianlockhart** [comment]
I've noticed something interesting about the behaviour when this (unsupported) window rule is enabled - the image viewer now renders at the size it was previously resized to rather than fullscreen, and thus necessitating resizing every time I view an image. I think this is great - it fixes my biggest gripe about the image viewer, it being that the images filled by screen, and provides a proper windowed integrated-into-telegram image viewer.

**Comment by ilya-fedin** [comment]
I don't quite understand what you mean? The custom frame allows you to resize as well.

**Comment by rokejulianlockhart** [comment]
Oh, yeah. I never noticed those dimmed custom titlebar buttons, @ilya-fedin.
