### ISSUE TITLE
Upgrade default link from HTTP to HTTPS

### ISSUE THREAD

**Issue by Inlife-raphael** [telegramdesktop/tdesktop#26499]
### Steps to reproduce

1. Send a link with only the part after `http(s)://`, e.g. example.com (for example in Saved Messages)

### Expected behaviour

https link which is more secure and more common since ~Jan 2017

### Actual behaviour

the link is an HTTP link, e.g. http://example.com

### Operating system

Linux

### Version of Telegram Desktop

4.8.4

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Please reopen with feature request type
