### ISSUE TITLE
Context menu closes automatically

### ISSUE THREAD

**Issue by chirok11** [telegramdesktop/tdesktop#26498]
### Steps to reproduce

1. Open context menu by right-click on personal or group chat.
2. Start moving mouse down.

### Expected behaviour

Context menu is not closed automatically while it is opened and cursor is in area.

### Actual behaviour

It closes if I move through context-menu that has sub-menu, when sub menu opens, application think that area is preferred for determining is context menu should be closed or not (i mean mouse out of specific area).
But If I open context menu, then move cursor on item that placed under menu item with sub-context-menu, it will be ok.
Problem is in items, that has context-menu (add to folder for groups, turn off notifications for personal-chats)

### Operating system

Arch Linux 6.4.2-zen1-1-zen, DE: Gnome 44.3, WM: Mutter.

### Version of Telegram Desktop

4.8.4

### Installation source

Static binary from official website

### Logs

```shell
I could attach video if anybody will be not able to reproduce
```

**Comment by chirok11** [comment]
http://0x0.st/HjoR.webm is video, there is no cursor visible, but it is able to understand where it is. and i am not forcefully closing context menu, it closes automatically

**Comment by ilya-fedin** [comment]
#26407
