### ISSUE TITLE
Self destruct timer in groups available to non admin

### ISSUE THREAD

**Issue by iz3gme** [telegramdesktop/tdesktop#26492]
### Steps to reproduce

Using linux desktop app:
1. go to a group where you are not owner or admin
2. show group info
3. click on group info menu
4. choose Auto-delete
5. select one of the time option and click save
6. timer is now visible and effective for all user in group

### Expected behaviour

Auto delete in group info menu should not be available to non-admin users
APIs should anyway refuse the request

### Actual behaviour

any user can set self destruct timer in group chats using linux desktop app
using android app the Auto-delete option is available only to admins
(not tested on windows and Mac)

### Operating system

Ubuntu 22.04.2 LTS - LXDE

### Version of Telegram Desktop

4.8.4

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
I’m afraid that is an intended behavior.
