### ISSUE TITLE
Can't transfer ownership

### ISSUE THREAD

**Issue by aknight2015** [telegramdesktop/tdesktop#26497]
### Steps to reproduce

That's just it, there's no option to transfer ownership so I can't recreate it. I'm using the latest version of Telegram Desktop for linux, and Android. Neither lets me transfer ownership.

### Expected behaviour

I should have an option to transfer ownership.

### Actual behaviour

There's no option to transfer ownership.

### Operating system

Pop!_OS and Android 12

### Version of Telegram Desktop

4.8.4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
you have 2fa enabled?

**Comment by aknight2015** [comment]
No. I don't own a cellphone.

**Comment by Aokromes** [comment]
that's your problem, to have transfer ownership enabled 2fa must be enabled.
