### ISSUE TITLE
STREAM WITH restream option missing for Admins with Manage Livestream privilege

### ISSUE THREAD

**Issue by jshrek** [telegramdesktop/tdesktop#26496]
### Steps to reproduce

When I login to Telegram desktop or Android app, and I click on the stream icon in the top right of our channel, there is an option that says START LIVE STREAM and SCHEDULE LIVE STREAM and then STREAM WITH so that I can re-stream to Telegram.

I have assigned multiple Administrators with the Manage Live Stream privilege, but the third STREAM WITH option is not present.
I have even tried giving these Administrators ALL admin other admin rights as well, but the STREAM WITH option is still not present. If I login, Stream With appears. When they login, there is no Stream With.

Windows Desktop version 4.8.3 x64
Android version 9.6.7

### Expected behaviour

Admins with the Manage Live Stream privilege should be able to use the STREAM WITH option.

### Actual behaviour

The STREAM WITH option is missing.

### Operating system

windows

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by jshrek** [comment]
Confirmed bug still exists on newest update of Windows Desktop version 4.8.8 x64

**Comment by john-preston** [comment]
This is a platform wide issue I guess, only creators can Stream With. You can report it on https://bugs.telegram.org, there is nothing I can do in the client app to fix that.

**Comment by jshrek** [comment]
Already posted here:
https://bugs.telegram.org/c/30042

**Comment by jshrek** [comment]
Is there a "platfomr wide" github repository where I can repost this bug? No reponse from bugs.telegram.org
