### ISSUE TITLE
Allow disabling the messages snapping to the left side in private chats

### ISSUE THREAD

**Issue by Thoufak** [telegramdesktop/tdesktop#26490]
### Is your feature request related to a problem?

When the tdesktop window gets wide enough, all the messages bubbles start to snap to the left like this:

<img width="565" alt="image" src="https://github.com/telegramdesktop/tdesktop/assets/40132582/7766fc4a-f2c3-4a45-9f5f-6c4de6b0a928">

The problem is that I want to have both a wide window and the messages bubbles on different sides like this:

<img width="954" alt="image" src="https://github.com/telegramdesktop/tdesktop/assets/40132582/b4d0778f-f8ba-49d6-84a0-fc2d71bf898b">

I consider this layout to be more convenient, as it's immediately more intuitive which messages are outgoing and which are incoming. Therefore, I'd like to be able to use it regardless of the window's width (including, in the fullscreen mode).

### Describe the solution you'd like

Add an option in the settings which would allow to disable this snapping behaviour.

### Describe alternatives you've considered

Currently I'm keeping my window as wide as possible, so that it doesn't change the layout.

### Additional context

TDesktop 4.8.3
Mac OS

**Comment by ilya-fedin** [comment]
Such option already exists, it's called "Adaptive layout"

**Comment by Thoufak** [comment]
Where do I find it? There's no such thing in the "Chat settings"

<img width="438" alt="image" src="https://github.com/telegramdesktop/tdesktop/assets/40132582/a8f90a72-e05c-4f10-983b-be109cb6b4b6">

**Comment by ilya-fedin** [comment]
It's at chat settings, yes. If you don't have it then your chat view is too small for adaptive layout and you can't use the feature.

**Comment by Thoufak** [comment]
Thanks, found it. I'd never think that some option will appear based on my window's width, lol
