### ISSUE TITLE
Shadow on window unminimize in Windows 8.1 (and other?)

### ISSUE THREAD

**Issue by kuzorov** [telegramdesktop/tdesktop#265]
In windows 8.1 when you unminimize windows shadow appears before window.

And this looks strange and not native like.

**Comment by uzvermode** [comment]
Can confirm issue present on windows 10(10240) x64

**Comment by tommasov** [comment]
I have this issue too. Windows 10 build 10586 x64

**Comment by Kintull** [comment]
Oh dat frameless

**Comment by ngrcld** [comment]
After many months I installed version 1.1.9 (in the same Windows XP as before) and this bug no longer exhibits.

**Comment by auchri** [comment]
The bug is still present on Windows 10.

**Comment by Aokromes** [comment]
this is valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
