### ISSUE TITLE
Windows onscreen touch keyboard hiding input field in landscape orientation 

### ISSUE THREAD

**Issue by inetkachev** [telegramdesktop/tdesktop#26507]
### Steps to reproduce

1. Touch input field
2. keyboard is appearing over telegram window

### Expected behaviour

Telegram window size decrease enough to see what im typing

### Actual behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/15964681/ca7e916a-f998-4358-9287-87db5400c275)

### Operating system

Windows 11 Home Version	22H2 

### Version of Telegram Desktop

version 4.8.3 хб4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#3274

**Comment by albertkremm** [comment]
Set custom interface scale to 100 - 130%. On my Surface Go it's works properly.  

![image](https://github.com/telegramdesktop/tdesktop/assets/100474614/a8a6d26a-d070-4aa3-a322-20d2be8d9e90)
