### ISSUE TITLE
I join a channel, go to comment and it blocks me from messaging

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#26509]
### Steps to reproduce

While I'm pretty sure this is all the same issue, I'm not 100% sure. I know it has to do with channels, nothing to do with groups, & I have a feeling it only happens when they are linked, but I'm not sure.

I've reported this problem before & it's been happening occasionally since I started on TG at least 2-3 or so years ago.

I was NOT blocked, I hadn't even typed anything to be blocked about & I'm not even sure I've ever comments in these groups/channels b/c I belong to tons & don't have the time to comment in all of them.

And if I was blocked, I wouldn't be able to see the channel or group. Plus it's happening in several channels, not just one.

06-25-23 - First I joined this channel, I think, the day before this happened in June. I reported it, & no one responded, so I'm posting it here b/c it happened again just now. https://t.me/RevealedEye & wrote a comment in the channel. 

I saw I had a reply from someone. I clicked on it, somehow got to this https://t.me/RevealedEye_Chat area (not sure how), signed up, commented in the channel, but then couldn't find the reply I needed to reply to.

I then found it in my TG folder, went back to it & couldn't reply. TG wouldn't even let me click on it. 

It also kept forwarding me to the group chat area & then very fast, taking me back to the channel. I tried this over & over again.

Then I noticed I had been removed by TG from the chat group. I joined again & then FINALLY found the reply to my comment & was able to respond.

I've told you & the others about this huge bug that seems to only happen in channels. TG has had a bug where it removes me (and others) from groups (not channels I don't think). I had this happen 3 years ago & others have told me about it happening to them too.

Then just now I joined another channel & again I can't comment. Here's a recording. https://mega.nz/file/swElnKhC#gG4kdrQU9vzJ0bkeXiKt61jzvwdNfbHSXWUalY9U-QA 

07-15-23 - it just happened with another channel. I went to go comment & it asked me to join the chat group, & I did, & then it restricted me right away. No captcha, nothing. 

https://mega.nz/file/wsdhFKjQ#6ZSa5nJf8d33Nts-RO6IRJfvSvK4MvAk45G2fFue0OA

Please fix this. This is a serious bug & it's been going on for at least 2+ years.

Thanks a ton

### Expected behaviour

I am able to comment in groups & channels

### Actual behaviour

I can't find the replies to my comments in channels or I'm restricted from commenting in a channel probably b/c it's linking to the group, I'm joining, there must be a captcha bot, but I can't see it, so then it stops me from commenting.

### Operating system

WIN 10

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
i don't think this is a telegram desktop bug.

**Comment by ILoveSkilledCoders** [comment]
> i don't think this is a telegram desktop bug.

I don't understand what you are saying. If it happens on my desktop, why wouldn't it be a TG desktop bug?

**Comment by ilya-fedin** [comment]
> If it happens on my desktop, why wouldn't it be a TG desktop bug?

Because if this happens not only on destkop then it's a server-side bug (if a bug at all).

> Then just now I joined another channel & again I can't comment. Here's a recording. https://mega.nz/file/swElnKhC#gG4kdrQU9vzJ0bkeXiKt61jzvwdNfbHSXWUalY9U-QA

Not sure what you want to say with this video? You just enter and leave the chat view without waiting until the timer in the bottom right corner ends.

> https://mega.nz/file/wsdhFKjQ#6ZSa5nJf8d33Nts-RO6IRJfvSvK4MvAk45G2fFue0OA

This one is clearly the channel owner gave you read-only status.

**Comment by ILoveSkilledCoders** [comment]
> > If it happens on my desktop, why wouldn't it be a TG desktop bug?
> 
> Because if this happens not only on desktop then it's a server-side bug (if a bug at all).
> 
> > Then just now I joined another channel & again I can't comment. Here's a recording. https://mega.nz/file/swElnKhC#gG4kdrQU9vzJ0bkeXiKt61jzvwdNfbHSXWUalY9U-QA
> 
> Not sure what you want to say with this video? You just enter and leave the chat view without waiting until the timer in the bottom right corner ends.
> 
> > https://mega.nz/file/wsdhFKjQ#6ZSa5nJf8d33Nts-RO6IRJfvSvK4MvAk45G2fFue0OA
> 
> This one is clearly the channel owner gave you read-only status.

Ok, so I went back into that channel, the same thing happened, but in their description off to the right I saw another link & sure enough, that's the link to their group. I joined there & was able to now comment, so I still maintain that this bug has to do with the fat that the groups & channels are linked & when I join a channel, I have no idea where their group is or how to join there just to be able to comment in the channel. Most channels don't put their group link in their channel link. I know it's hard for me to do in my channels/groups.

Please fix.

Thanks

**Comment by ILoveSkilledCoders** [comment]
And here's another channel where I can't comment or join to comment even though I'm in the channel with no issues. 

https://mega.nz/file/Q50SHbzJ#Bj_uVTf52Ufsi8o-elKfZFJS2xS82RK-n3tN_viumOw

**Comment by ilya-fedin** [comment]
The group owner has banned you. If you see this on a lot of groups this means your account got into some ban list managed by group networks/bots helping with group administration and now when you join groups being a part of those networks or having such a bot, it instantly bans you. It's also possible group moderators maintain some ban lists manually and share between themselves preemptively banning people with the help of userbots.

The easiest way to check is to create a new account and see. Although personally I also encountered bots that were banning based on visible account name so if you choose a similar name for new account, it's likely to continue to be banned.
