### ISSUE TITLE
Clinking on google maps link does not open it if bing maps is not installed

### ISSUE THREAD

**Issue by fcl3** [telegramdesktop/tdesktop#26506]
### Steps to reproduce

1. Use Windows 10 and don't have Bing Maps ("Maps" in menu) installed
2. Click a shared location

### Expected behaviour

If no Bing Maps installed, open Google Maps in default browser

### Actual behaviour

An app store form opens
https://github.com/telegramdesktop/tdesktop/issues/3571 -- issue is closed, but bug still exists

### Operating system

Windows 10 pro 19045.3208

### Version of Telegram Desktop

Telegram Desktop

### Installation source

Static binary from official website

### Crash ID

--

### Logs

```shell
--
```

**Comment by john-preston** [comment]
Yeah, indeed. When I removed Maps while TDesktop was running it worked as expected, but after relaunch it started returning "bingmaps" handler.

I tried to fix it once again, we'll see in the next version.

**Comment by john-preston** [comment]
Please check 4.9.

**Comment by fcl3** [comment]
Yep, it works, thanks!
