### ISSUE TITLE
Telegram flatpak uses 100% CPU, freezes and uses too much CPU on on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by IlgazC** [telegramdesktop/tdesktop#26501]
### Steps to reproduce

1) Install & Update openSUSE Tumbleweed
2) Run KDE (wayland) session
3) Install Telegram flatpak
4) Launch Telegram

### Expected behaviour

 Telegram window displayed

### Actual behaviour

Except "allow to run in background" prompt (I said yes), nothing shown and "top" shows 100% of CPU consumed for a long time until it finally launches however using 80% of CPU while idling.

### Operating system

openSUSE Tumbleweed

### Version of Telegram Desktop

4.8.4

### Installation source

Flatpak

### Logs

```shell
journal when telegram launched:

Jul 13 12:05:31 mbt systemd[1978]: Started Telegram Desktop.
Jul 13 12:05:32 mbt systemd[1978]: Started app-flatpak-org.telegram.desktop-6485.scope.
Jul 13 12:05:33 mbt telegram-deskto[6497]: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Jul 13 12:05:33 mbt xdg-desktop-por[2043]: A backend call failed: No such method 'CreateMonitor' in interface 'org.freedesktop.impl.portal.Inhibit' at object path '/org/freedesktop/portal/desktop' (signature 'ooss')
Jul 13 12:05:33 mbt xdg-desktop-por[2043]: Failed to close session implementation: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/org/freedesktop/portal/desktop/session/1_103/tdesktop487693791'
Jul 13 12:05:36 mbt xdg-desktop-portal-kde[2151]: xdp-kde-settings: Namespace  "org.gnome.desktop.wm.preferences"  is not supported
Jul 13 12:05:36 mbt xdg-desktop-portal-kde[2151]: xdp-kde-settings: Namespace  "org.gnome.desktop.wm.preferences"  is not supported
Jul 13 12:05:36 mbt xdg-desktop-portal-kde[2151]: xdp-kde-settings: Namespace  "org.gnome.desktop.wm.preferences"  is not supported
Jul 13 12:05:36 mbt xdg-desktop-portal-kde[2151]: xdp-kde-settings: Namespace  "org.gnome.desktop.wm.preferences"  is not supported
Jul 13 12:05:38 mbt plasmashell[6497]: QPainter::begin: Paint device returned engine == 0, type: 2
Jul 13 12:05:38 mbt plasmashell[6497]: QWidget::render: Cannot render with an inactive painter
Jul 13 12:05:38 mbt kded5[2102]: Registering ":1.106/StatusNotifierItem" to system tray
Jul 13 12:05:38 mbt xdg-desktop-portal-kde[2151]: xdp-kde-settings: Namespace  "org.gnome.desktop.wm.preferences"  is not supported
Jul 13 12:05:38 mbt xdg-desktop-portal-kde[2151]: xdp-kde-settings: Namespace  "org.gnome.desktop.wm.preferences"  is not supported
Jul 13 12:05:38 mbt xdg-desktop-portal-kde[2151]: xdp-kde-settings: Namespace  "org.gnome.desktop.wm.preferences"  is not supported


```
```

**Comment by ilya-fedin** [comment]
Does this happen only to flatpak or to the official build from https://desktop.telegram.org as well?

**Comment by IlgazC** [comment]
> Does this happen only to flatpak or to the official build from https://desktop.telegram.org as well?

I have tested that binary on openSUSE Tumbleweed, while it really takes long to launch with 200% CPU usage on Core2Duo , once it displays the window, CPU usage is miniscule. I have a Ubuntu 20.04 LTS (Mint) on secondary partition. I will test there and update.

**Comment by ilya-fedin** [comment]
I can't really do the step 1 but with steps 2-4 I can't reproduce. Until someone else who can do step 1 will reproduce and debug this, this is marked as unreproducible

**Comment by da-the-dev** [comment]
I experience the same behavior on Arch with KDE

**Comment by ilya-fedin** [comment]
@IlgazC does this still happen with 4.13?

**Comment by IlgazC** [comment]
I normally follow up my bug reports, but there have been some issues lately. For me, the issue is resolved, Telegram seems to work fine as possible on a core2duo :-). However, I am not closing the issue as there is feedback from @da-the-dev  . Thank you for caring.

**Comment by ilya-fedin** [comment]
@da-the-dev says about suspend what means it's completely unrelated

**Comment by IlgazC** [comment]
OK, thanking again.
