### ISSUE TITLE
Notification shows wrong chat

### ISSUE THREAD

**Issue by wouthoekstra** [telegramdesktop/tdesktop#26503]
### Steps to reproduce

1. Chat with person A. Keep this chat selected in the list of chats
2. Have person B (or group B) send a message.

In the above scenario, you will get a notification saying Person A has sent a message, even though the message came from B.

### Expected behaviour

The expected behaviour is that the notification should mention the correct correspondent.

### Actual behaviour

The notification mentions an incoming message from the wrong chat: the chat you left the focus on in the chat list.

### Operating system

Linux (Ubuntu)

### Version of Telegram Desktop

4.8.4

### Installation source

Snap

**Comment by ilya-fedin** [comment]
> In the above scenario, you will get a notification saying Person A has sent a message, even though the message came from B.

Can you make a screen record of the issue? As I've never seen such behavior.

**Comment by wouthoekstra** [comment]
In the screenshot below I have telegram open in the background, but you can still see the "saved messages" tab is selected. A message is coming in from "Greatspace...", which you can see on top of the list. The notification however, thinks the message is from saved messages.

![wrong_chat_blurred](https://github.com/telegramdesktop/tdesktop/assets/6030296/f13c0555-292b-4944-9049-4e39d839d24d)

**Comment by wouthoekstra** [comment]
Pure speculation on my side:

What might happen is that the windows name is changed when you select a different chat. You can't see the name of the window because telegram desktop uses custom window styling instead of linux native. When in the background something happens in telegram a notification is fired (maybe not even by telegram itself but by the OS?), but without a specific message, so it just tells me the window - in this case 'saved message' is ready?

Whatever the culprit, it is pretty confusing. I found myself replying to the wrong persons because of it.

**Comment by ilya-fedin** [comment]
This is not a notification from Telegram, this seem to be some GNOME service notification about Telegram

**Comment by wouthoekstra** [comment]
My apologies, it indeed seems to be a Gnome issue. It seems that this setting solved it for me: "Show message content in popups". I has to be specifically set for Telegram in Gnomes notifications center.
![notfication_setting](https://github.com/telegramdesktop/tdesktop/assets/6030296/783f3bdc-8192-4c51-822b-db71636eb529)

**Comment by ilya-fedin** [comment]
Wouldn't it just hide the text?

**Comment by ilya-fedin** [comment]
Well, i think you find a lot of issues about this 'is ready' notification if would search all the issues (not only the open ones) in the issue tracker. This is a forever problem with GNOME, they seem to be just unable to get notifications right... While other platforms and other DEs react to the APIs with highlighting the icon in the taskbar or dock or focusing the window after clicking on the normal notification (not the 'is ready' one), GNOME shows the 'is ready' notification in both cases... Maybe it's just for Qt applications as GNOME seem to do everything to make them work as buggy as possible.
