### ISSUE TITLE
muted indicator for private chats

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#26515]
### Is your feature request related to a problem?

Right now tdesktop does not show an indicator when chat is muted:
![изображение](https://github.com/telegramdesktop/tdesktop/assets/5204968/3c548f9b-b437-4271-90e8-6bfbed3adde0)

### Describe the solution you'd like

Showing indicator like in telegram android:
![изображение](https://github.com/telegramdesktop/tdesktop/assets/5204968/ab37617d-9a4c-4132-b5a9-d376a8a3bdac)

### Describe alternatives you've considered

Not having indicator.

**Comment by ilya-fedin** [comment]
#5981
