### ISSUE TITLE
Wrong notifications behavior

### ISSUE THREAD

**Issue by feym78** [telegramdesktop/tdesktop#26510]
### Steps to reproduce

1. create custom folder
2. create folder "New chats" where will be only chats with new messages and muted chats excluded
3. add some personal and group chat in custom folder from piont 1
4. archive these chats so they appear only in custom folder
5. mute group chat (not personal)
6. have a new message in personal chat (unmuted) and muted group chat, but in group chat get a message by replying to your message or tagged with "@*your account*"

### Expected behaviour

1. Chats will apear in default "All chats" folder (leave the archive)
2. Chats will apear in custom "New chats" folder with option to exclude muted chats
3. In custom folder group chat will have green "@" symbol near message counter

### Actual behaviour

1. Chats don't appear in default "All chats" folder (instead stay in archive)
2. Chats don't appear in custom "New chats" folder with option to exclude muted chats (but they do in mobile app! (android))
3. In custom folder group chat have grey "@" symbol near message counter (but it's green in mobile app! (andrtoid))

Expected behavior worked just fine until 14/07/23 (except "New chats" folder, I tried to create it only when noticed problem), then it broke for some reason, as I can see there was no client updates.
If chats archived, but not added in any custom folder then they will be unarchived when new meessages come as it worked before.
But the chats stopped appearing in "All chats" folder from archive for both pc and mobile app if they added in some custom folder. It worked in any cases until 14/07/23.
What happened?
PC app (group chat):
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/06c3f0f8-367c-44a4-8c81-682a6a56214a)
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/0545de5d-6bc9-4e53-bfaa-0beebdacfef6)
Mobile app (same group chat):
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/6015f1fa-63f6-4499-8aaf-bffc75f2bd15)
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/d162e4b7-1f17-4cf0-a197-8ab64f204fe9)

### Operating system

Windows 10

### Version of Telegram Desktop

4.8.3

### Installation source

Static binary from official website

**Comment by maidankin** [comment]
I am having a similar bug. Started on the evening of July 13

**Comment by TheLastochka** [comment]
same

**Comment by feym78** [comment]
Hello. Any ideas?

**Comment by john-preston** [comment]
In the recent release I guess the archive settings have changed (unmuted chats stay in archive by default).

I'm going to add archive settings like on mobile apps later with the ability to return old behavior.

On latest Android app you can open Archive, press "..." in the top-right corner, choose Archive Settings and decide if unmuted chats leave archive on a new message or not.

**Comment by feym78** [comment]
> In the recent release I guess the archive settings have changed (unmuted chats stay in archive by default).
> 
> I'm going to add archive settings like on mobile apps later with the ability to return old behavior.
> 
> On latest Android app you can open Archive, press "..." in the top-right corner, choose Archive Settings and decide if unmuted chats leave archive on a new message or not.

This is awesome! Just tested in mobile app - works great and having possibility to control this behavior is wonderful.
Looking forward to see this setting in desktop app. Thank you!

**Comment by john-preston** [comment]
Archive Settings have been added to Telegram Desktop starting from 4.9 version, in the Archive context menu.

**Comment by feym78** [comment]
> Archive Settings have been added to Telegram Desktop starting from 4.9 version, in the Archive context menu.

Oh, now after update it works wrong.
1. settings are not in sync in mobile and desktop app
It could be different set of settings in mobile and desktop app. For example, when I set all archive settings ON in mobile app - they stay all OFF in desktop app.
2. BUT is a mess now. No matter what I chose in mobile app, chats will get out from archive ONLY with ON setting in desktop app, but it should not according to setting.

Scenario 1:
mobile app settings
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/3f12823a-278a-4baa-b29b-9ead9ca11c26)
desktop app settings
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/21604cb0-c0ce-47fa-bd92-872ddc0ba924)
result:
after recieving message in archived chats (from folder and not in any folder) they are not getting out from archive (both mobile and desktop), but it sould!

Scenario 2:
mobile app settings
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/a41a31e7-157f-46e1-a9c1-4d64a3756b1e)
desktop app settings
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/ebcaef4c-60ef-417d-a03f-cfb05817d651)
result:
after recieving message in archived chats (from folder and not in any folder) they are not getting out from archive (both mobile and desktop), but chat without folder should

Scenario 3:
mobile app settings
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/6696bea9-434e-497c-a338-51f6395b6e50)
desktop app settings
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/a6f2557a-6944-471b-ac12-190c336ab846)
result:
after recieving message in archived chats (from folder and not in any folder) they are not getting out from archive (both mobile and desktop)

Scenario 4:
mobile app settings
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/203f6969-1ccc-45be-8316-187d925a6209)
desktop app settings
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/09557996-8b67-41d4-a252-9d56a6019f71)
result:
after recieving message in archived chats (from folder and not in any folder) chat without folder got out from archive, chat with folder - didn't. As it should according to desktop settings, but mobile settings are different with same chat's behavior.

Scenario 5:
mobile app settings
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/203f6969-1ccc-45be-8316-187d925a6209)
desktop app settings
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/0abd49aa-2ed4-4174-bfbf-72d378eb1736)
result:
after recieving message in archived chats (from folder and not in any folder) both chats got out from archive, but they should not according to desktop settings! And should accordig to mobile settings.

**Comment by john-preston** [comment]
@feym78 ups, sorry.. I'll fix that in the upcoming bug fix version, I hope I'll deploy it later today.

**Comment by feym78** [comment]
@john-preston Hi!
I see, that with version 4.9.1 there is a big improvement. Settings now in sync between mobile and desktop app (it requires to relaunch android app to see changes from desktop app, but behavior works immediately).
For now only one bug left:
There is two separate settings - for unmuted chats and for chats from folders.
In mobile app you can set this settings independently of each other, but:
1. in desktop app if you turn on the "unmuted chats" settings then "chats from folder settings" will be hidden and apparently automatically turned on, based on actual behavior (in this case unmuted chats and chats from folders stop getting out from archive)
2. in mobile app if you turn on only setting "unmuted chats" then setting "chats from folder" will not be hidden, but in desktop app it will and behavior will be the same - all chats (unmuted and from folders) will not get out from archive.
mobile app:
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/8a56651f-7fe5-4b5e-a935-65ed808d5a8c)
desktop app:
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/c3941a72-2b8c-4345-89df-9735542b3401)
desktop add after disable "unmuted chats" setting
![image](https://github.com/telegramdesktop/tdesktop/assets/81779189/fcfdc180-01d6-4d52-ad20-41d17f4b6370)
there is "chats from folders" setting turned on, but it was not in mobile app

So for now there is no way to turn on setting only for unmuted chats.

**Comment by john-preston** [comment]
@feym78 I made this intentionally, I think it is a problem in mobile app. I believe there is only three behaviors and I don't think that server supports the fourth case (for me it doesn't make sense): if you keep all unmuted chats in archive then unmuted chats added explicitly to one or more folders of course stay in archive as well. "Keep unmuted chats in archive unless they are added in at least one folder, move them out of archive on a new message otherwise" doesn't make sense to me.

**Comment by feym78** [comment]
> @feym78 I made this intentionally, I think it is a problem in mobile app. I believe there is only three behaviors and I don't think that server supports the fourth case (for me it doesn't make sense): if you keep all unmuted chats in archive then unmuted chats added explicitly to one or more folders of course stay in archive as well. "Keep unmuted chats in archive unless they are added in at least one folder, move them out of archive on a new message otherwise" doesn't make sense to me.

Looks like you are right.
Turned off all desktop clients and tested in mobile app alone - "unmuted chat" option works as some main setting as you described. Thing is that I use all group chats in folders muted and only want to have notifications from them when someone tagged me, I did not look at case when group chat in folder is not muted, in this case "chats from folders" setting makes sense. When unmute group chat archived and added to some folder then setting "chats from folders" decides if chat will be unarchived or not when new messages arrive (not tagged, usual ones) .
And it is indeed not obvios from mobile client and is less confusing in desktop.

I think now it works great in desktop app. Thank you for your work and responsiveness.
