### ISSUE TITLE
Use separate, properly-tagged playback stream for notification audio (Linux, pulseaudio/pipewire)

### ISSUE THREAD

**Issue by SwooshyCueb** [telegramdesktop/tdesktop#26516]
I'm not actually sure if this qualifies as a bug report or as a feature request. Since the feature request issue template seems to fit better, I'm opening the issue as a feature request.

### Is your feature request related to a problem?

Presently, Telegram sends notification sounds and media playback using the same pulseaudio playback stream. This makes controlling the volume of the notification sounds independent of media playback impossible. Additionally, it goes against best practices.

### Describe the solution you'd like

**Notification audio, call audio, and media playback audio should be on separate playback streams, tagged properly for their role. Notification audio streams should be tagged with the `event` role and call audio streams should be tagged with the `phone` role.**

From the [pulseaudio documentation](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/ApplicationProperties/):
> **PA_PROP_MEDIA_ROLE**
>
> This property should contain a short string that describes the role of a media stream, where role is one of:
> - "video": for movie/video streams from media players
> - "music": for music streams from media players
> - "game": for audio from games
> - "event": for event sounds (i.e. button clicks, ...)
> - "phone": for phone data (i.e. voip speech audio)
> - "animation": for animations (i.e. Flash)
> - "production": for audio production applications.
> - "a11y": accessibility applications (i.e. screen readers, ...) This is a property of the actual streamed data, not so much the application. However usually it is still safe to simply set a process-global environment variable.

From the [pulseaudio documentation for volume control UIs](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/WritingVolumeControlUIs/) (emphasis mine):
> Some types of sounds are very short in nature and hence might appear only for a very short time as a proper stream. That makes it difficult to control them in the volume control UI — before you can grab the slider the slider might already be gone again. Those short sounds are usually event sounds. It hence might make sense to add an explicit slider for event sounds that stays available all the time. To implement this simply manipulate the stream database for the "sink-input-by-media-role:event" key (**assuming that your event sounds are properly tagged, like libcanberra properly does**). You can even make this instant-apply. In future, if more streams are tagged properly you could even show an UI that always controls volume based on the role, and ignores dynamically created streams. i.e. one slider for "Telephony", another one for "Games" and so on.

### Describe alternatives you've considered

I've tried using a quieter notification sound (popped open the default sound in audacity and reduced the volume by 10db), but Telegram seems to apply some sort of volume normalization, as it played back at the same volume as the default notification sound when selected in Telegram.

### Additional context

Related: #151

**Comment by ilya-fedin** [comment]
This is not possible as the underlying audio library (openal) doesn't provide API for that

**Comment by ilya-fedin** [comment]
And even if it provided such API, this probably means a global rewrite of how tdesktop handles audio which sounds like too much work for 1.82% of tdesktop userbase.
