### ISSUE TITLE
Call window unresponsive

### ISSUE THREAD

**Issue by therman89** [telegramdesktop/tdesktop#26513]
### Steps to reproduce

1. Start Telegram desktop on Linux Mint 20
2. Press phone button to show the call window
3. The window focus is lost, cannot click on the call button

### Expected behaviour

The window focus should be on the new call window to be able to start the actual call.

### Actual behaviour

Window focus is lost, cannot start the call or if I'm called I cannot click the answer button. The mouse clicks are recognized by the window behind the Telegram call window.

### Operating system

Linux Mint 20

### Version of Telegram Desktop

4.8.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This sounds like a bug of your WM
