### ISSUE TITLE
Please add the possibility to set a Password and send full size "uncompressed" Images

### ISSUE THREAD

**Issue by Warmuser** [telegramdesktop/tdesktop#26511]
### Is your feature request related to a problem?

Nope.

### Describe the solution you'd like

Hi guys, I would like to ask you If it is possible for you to add the possibility to add password for private Saved Messages and Private Chats/Channels. And the ability send uncompressed images with a normal "compressed" preview.

### Describe alternatives you've considered

I think my question is generic and I don't know how many alternatives are compatible due these specific questions.

**Comment by 23rd** [comment]
https://bugs.telegram.org/c/23028
https://bugs.telegram.org/c/18856
