### ISSUE TITLE
Telegram version 4.8.4 crashing on Linux Ubuntu when shuffling music.

### ISSUE THREAD

**Issue by Vladislav2507** [telegramdesktop/tdesktop#26519]
### Steps to reproduce

Go to the player and select shuffle music

### Expected behaviour

shuffle music

### Actual behaviour

Application crash

### Operating system

Linux Ubuntu

### Version of Telegram Desktop

4.8.4 

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> ### Crash ID
> 
> _No response_

This must be filled

**Comment by AmirMFarhang** [comment]
Same here, no crash id. same on several Debian based distros .

**Comment by tvha23** [comment]
This issue is still persistent in Arch Linux ```telegram-desktop``` [package.](https://archlinux.org/packages/extra/x86_64/telegram-desktop/)

**Comment by ilya-fedin** [comment]
A crash id from official binary or a crash trace with debug symbols are required

**Comment by mehranarji** [comment]
no log was observed after I run it with the `-debug` command

**Comment by ilya-fedin** [comment]
I don't think anything related to shuffling is logged. Crash report is what's needed.

**Comment by mehrdad-dev** [comment]
same here @ilya-fedin 


**Output of gdb:**

[mp3 @ 0x7ffff4270000] Could not find codec parameters for stream 1 (Video: mjpeg, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[New Thread 0x7fff9c8fb640 (LWP 158119)]
[New Thread 0x7fff8c0fa640 (LWP 158120)]
[New Thread 0x7fff8b8f9640 (LWP 158121)]
[New Thread 0x7fff8b0f8640 (LWP 158122)]
[Thread 0x7fff8b0f8640 (LWP 158122) exited]
[New Thread 0x7fff8b0f8640 (LWP 158123)]
[New Thread 0x7fff8a8f7640 (LWP 158125)]
[New Thread 0x7fff8a0f6640 (LWP 158126)]
[Thread 0x7fff8a0f6640 (LWP 158126) exited]
[Thread 0x7fff9f0fe640 (LWP 158112) exited]
[Thread 0x7fff9d8fd640 (LWP 158115) exited]
[Thread 0x7fff9d0fc640 (LWP 158117) exited]
[Thread 0x7fff8a8f7640 (LWP 158125) exited]
[Thread 0x7fff8b8f9640 (LWP 158121) exited]
[Thread 0x7fffbd9fe640 (LWP 158047) exited]
[Thread 0x7fffbe1ff640 (LWP 158046) exited]

**Comment by ilya-fedin** [comment]
That's not a backtrace.

**Comment by alcaravanosu** [comment]
> Same here, no crash id. same on several Debian based distros .

Same behaviour.

Operating system
Fedora Linux 36 (Xfce) x86_64

Version of Telegram Desktop
4.8.9

Installation source
Static binary from official website

Crash ID
No response

Logs
No response

**Comment by saman3d** [comment]
same here still crashes when hitting shuffle button

**Comment by john-preston** [comment]
Can you show a screencast of where you press when it crashes? Because I can't reproduce that :(
