### ISSUE TITLE
Edit box context menu closes when moving from already open submenu to another one (Spelling/Formatting)

### ISSUE THREAD

**Issue by kode54** [telegramdesktop/tdesktop#26523]
### Steps to reproduce

1. Right click on the edit box
2. Hover over either Spelling or Formatting to cause it to open that menu
3. Move the cursor to the other menu
4. The whole menu tree closes

### Expected behaviour

It should close the other submenu and open the newly highlighted one.

### Actual behaviour

The whole menu tree closes, which can happen easily when attempting to open the Formatting menu, but accidentally moving past the Spelling menu.

### Operating system

Arch Linux, Gnome 44.3 Wayland

### Version of Telegram Desktop

4.8.4-2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
#26407

**Comment by kode54** [comment]
Thanks, I'll close it as a dupe.
