### ISSUE TITLE
Crash when working with touchpad on Fedora Gnome Wayland

### ISSUE THREAD

**Issue by VRT-secure** [telegramdesktop/tdesktop#26526]
### Steps to reproduce

1. Start telegram
2. Work in OS and swipe work desktop with 3 fingers
3. Crash Telegram

### Expected behaviour

Doesn't crash

### Actual behaviour

Crash

### Operating system

Fedora Gnome

### Version of Telegram Desktop

4.8.4

### Installation source

Static binary from official website

### Logs

```shell
15:33:38 kernel: Telegram[3851]: segfault at 90 ip 00000000045ce3c0 sp 00007fffc585c200 error 4 in Telegram[727000+6219000] likely on CPU 5 (core 8, socket 0)
15:31:54 kernel: Telegram[2644]: segfault at 90 ip 00000000045ce3c0 sp 00007ffff0f2bd00 error 4 in Telegram[727000+6219000] likely on CPU 0 (core 0, socket 0)
```

**Comment by ilya-fedin** [comment]
#26380

**Comment by VRT-secure** [comment]
Yes, I use that extension. Ok, I'll turn off it.
