### ISSUE TITLE
[Feature Request] Custom emoticon packs

### ISSUE THREAD

**Issue by frozenspider** [telegramdesktop/tdesktop#2652]
I would like to request an ability to import custom (user-imported) emoticon packs in addition to standard emojis. Stickers are fun and stuff, but are very inconvenient because of huge fixed size (512x512) and inability to embed them into messages.
For instance, I would like to use emoticons in this style: http://www.kolobok.us/
If custom emoticon packs will be supported, I'll be able create and upload it myself.

**Comment by stek29** [comment]
@frozenspider api issue.

**Comment by frozenspider** [comment]
Where should I post this feature request then?

**Comment by stek29** [comment]
Twitter or In-app support.
