### ISSUE TITLE
Chat popup menu closed after mouse moving without click

### ISSUE THREAD

**Issue by mpz** [telegramdesktop/tdesktop#26527]
### Steps to reproduce

1. Go to any chat (private, public, channel) 
2. Select input box "Broadcast message..."
3. Open context menu via rigth mouse button
4. Try to move mouse cursor (only move, no clicks) from Undo, Redo to Spelling items

### Expected behaviour

All items can be selected, sub items opens. 

### Actual behaviour

1. After 1-3 seconds menu closed. 

2. It is not possible to past text because buffer cleared and "Past" item become gray. (Ctrl+V is not working also) 

just opens:
![image](https://github.com/telegramdesktop/tdesktop/assets/369032/de6093db-563c-404d-8b09-6f1481000493)

after mouse moving and menu reopen:
![image](https://github.com/telegramdesktop/tdesktop/assets/369032/4b315bcf-6cbf-4be9-a742-bb479a6838dd)

### Operating system

Ubuntu 22.04.2 LTS, Gnome 42.5 

### Version of Telegram Desktop

Telegram Desktop 4.8.4

### Installation source

Static binary from official website

### Logs

```shell
n/a
```

**Comment by alexd73** [comment]
I have noticed the some glitch for the couple of month.
