### ISSUE TITLE
Make an extra option in admin-parameters to enable/disable polls

### ISSUE THREAD

**Issue by jk-85** [telegramdesktop/tdesktop#26521]
### Is your feature request related to a problem?

Since years now I'm missing a feature. If you have a bigger TG-network with dozens of groups and want to prevent that your admins post polls or redirect them, you can't restrict them from doing that. You can only restrict users of that groups from doing that that are no admins.

If you don't have this option you have to constantly watch in every group where you're admin if one of the other admins accidently posted a poll. And the other admins can't remember every group anytime that belongs to the big TG-network where they are admin. I hope someone understands what I'm trying to say xD

![grafik](https://github.com/telegramdesktop/tdesktop/assets/13134932/415d8097-3560-4834-bc42-8381d2d375c1)

### Describe the solution you'd like

See above

### Describe alternatives you've considered

-

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
