### ISSUE TITLE
Flatpak: Invalid checksum of length 0 expected 32

### ISSUE THREAD

**Issue by secretmango** [telegramdesktop/tdesktop#26528]
### Steps to reproduce

try to update telegram desktop using `flatpak update`

### Expected behaviour

updating

### Actual behaviour

```
Invalid checksum of length 0 expected 32
```

### Operating system

Fedora 38

### Version of Telegram Desktop

4.8.4

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
I believe this is some problem on flathub side

**Comment by ilya-fedin** [comment]
https://github.com/flathub/flathub/issues/4340

**Comment by farribeiro** [comment]
A workaround is using the option `--no-static-deltas`
