### ISSUE TITLE
Warn when hiding more than 100 channels from folder

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#26520]
### Is your feature request related to a problem?

Telegram does not warn you that you can't remove more than 100 channels from folder like telegram for android does:
![Screenshot_20230718-181808_Nekogram](https://github.com/telegramdesktop/tdesktop/assets/5204968/d20f207f-37ff-404a-b09f-d6f708bd0db9)

### Describe the solution you'd like

Warn when hiding more than 100 channels from folder like telegram for android does.

### Describe alternatives you've considered

Not warning when hiding more than 100 channels from folder like telegram for android does.

**Comment by 23rd** [comment]
I’m not sure, are you talking about this limitation?
Maybe the spelling is a bit wrong, but it pops up when you exclude more than a hundred chats from a folder.

<details><summary><b>Screenshot</b>:</summary>

![image](https://github.com/telegramdesktop/tdesktop/assets/4051126/430c1113-e53a-4129-a758-137a2dc155e2)
</details>

**Comment by soredake** [comment]
>but it pops up when you exclude more than a hundred chats from a folder.

I have not seen something like this earlier, i will re-test later.

**Comment by soredake** [comment]
Retested, i still don't see this message, chats just "successfully" excluded but brought back on restart. Tdesktop 4.8.10

**Comment by 23rd** [comment]
Well, I have no idea. Perhaps a screen record will help me to understand.

**Comment by john-preston** [comment]
Should be fine in 4.9.
