### ISSUE TITLE
Call window is not responding to pointer events randomly

### ISSUE THREAD

**Issue by rustedwolf** [telegramdesktop/tdesktop#26537]
### Steps to reproduce

1a. Click on a call icon watch where the call window appears.
1b. Receive a call from someone

### Expected behavior

When call window/pop-up is opened, it should respond to pointer events (clicks, grabs, move and etc...)

### Actual behavior

This happens quite random, but most of the time Telegram open a window on other side of the screen (I have my telegram on the right, window opens on the left) and it not responds to clicks like as it had pointer events disabled. The clicks just go right through it on objects behind it. The window buttons don't work as well, the only way to close it is through taskbar. 

After one or two retries, the window appears over the app and it's responding.

Sometime when I receive a call I get the same behavior and I can't to pick up the call.

I use Cinnamon desktop environment.

### Operating system

Linux Mint 20.3, Cinnamon 5.2.7

### Version of Telegram Desktop

grab

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This sounds like a bug of your WM. You're not the first one in a while so I guess Cinnamon made a regression in a recent release.

**Comment by rustedwolf** [comment]
> This sounds like a bug of your WM. You're not the first one in a while so I guess Cinnamon made a regression in a recent release.

You mean other also had the same issue in Cinnamon environment? Because it's kinda weird to blame it on WM, since I have this issue only with Telegram. If I had this issue with other apps - then I would assume it's a WM bug. But this happens only with Desktop Telegram app with it's new call window - I recall clicking on call icon called user instantly, now it opens this window, where I had to press call button. Moreover it's mostly Telegram what I update rather than WM (which is old btw.).

**Comment by ilya-fedin** [comment]
Telegram couldn't transfer clicks to other windows, it just doesn't have such access, it could do only your WM

**Comment by rustedwolf** [comment]
> Telegram couldn't transfer clicks to other windows, it just doesn't have such access, it could do only your WM

I doesn't transfer it just draws a window, that doesn't register pointer events. Something like CSS `pointer-events: none;` property - the clicks and hover events just go right through it, like it wasn't there even  there.
