### ISSUE TITLE
delete  display wrong！

### ISSUE THREAD

**Issue by abcmiao** [telegramdesktop/tdesktop#26536]
### Steps to reproduce

<img width="813" alt="image" src="https://github.com/telegramdesktop/tdesktop/assets/13944985/5b48119c-52ee-48df-a281-f5dccfcd02bf">

### Expected behaviour

右键删除

### Actual behaviour

删除显示成了reschedule

还一个问题是，bold加粗的字体显示不了或者显示有问题。

### Operating system

macOS

### Version of Telegram Desktop

4.8.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
fixed on 4.8.6
