### ISSUE TITLE
Markdown in Telegram-desktop

### ISSUE THREAD

**Issue by nooob-developer** [telegramdesktop/tdesktop#26533]
### Is your feature request related to a problem?

Yes, my feature request is related to a problem. Currently, Telegram Desktop does not support the Markdown format, which can make formatting messages a bit more complicated and time-consuming. By adding Markdown support, users would be able to format their messages more easily and efficiently, which would enhance the overall user experience.

### Describe the solution you'd like

The solution that I would like is for Telegram Desktop to add support for the Markdown format. This would allow users to format their messages more easily and quickly using simple syntax such as Additionally, Markdown supports other formatting options such as 
### headings

- lists

 and 
[links](), which would make messaging on Telegram Desktop more versatile and user-friendly. By implementing this feature, Telegram Desktop would enhance the user experience and make the platform more efficient for both personal and professional use.

### Describe alternatives you've considered

One alternative that I have considered is using HTML to format messages on Telegram Desktop. However, this requires more advanced knowledge of markup languages and can be time-consuming, especially for users who are not familiar with HTML. Another alternative is to use a third-party formatting tool or extension, which can add additional features but may also be less secure and require additional setup. However, neither of these alternatives offers the simplicity and convenience of Markdown, which is a widely used and user-friendly format that would be a valuable addition to Telegram Desktop.

### Additional context

In my opinion, it would be much better if Telegram Desktop supported the Markdown format  This would make the messaging experience more efficient and user-friendly. Additionally, Markdown support would be particularly beneficial for users who frequently use Telegram for work or other professional purposes, as it would allow them to quickly create well-formatted messages without wasting time on formatting. Overall, I believe that adding Markdown support to Telegram Desktop would be a valuable improvement that would enhance the user experience and make the platform more versatile and efficient.

**Comment by ilya-fedin** [comment]
tdesktop does support markdown, you can use e.g. `*bold*` or `~italic~`

**Comment by nooob-developer** [comment]
I am aware that Telegram, like many other messaging apps, supports basic formatting options such as bold and italic. However, I believe that Telegram stands out from other messaging apps due to its unique features and capabilities. One of the reasons I choose Telegram over other messaging apps is because of its potential to support more advanced formatting options, such as Markdown.

In conclusion, while many messaging apps offer basic formatting options, I believe that Telegram's potential to support advanced Markdown features sets it apart from other messaging apps and makes it a more versatile and efficient platform. Adding support for Markdown would enhance the user experience and make messaging more efficient and user-friendly

**Comment by ilya-fedin** [comment]
This is sadly not possible to implement due to the lack of such formatting API. Note that you have chosen the client bug report type when creating the issue, not the API issue type, so it's invalid.
