### ISSUE TITLE
Very simple grammatical fix.

### ISSUE THREAD

**Issue by nikhiljha** [telegramdesktop/tdesktop#2653]
TL;DR Replace both instances of "group is unaccessible" in Telegram/Resources/langs/lang.strings with "group is inaccessible."

Sorry but it's bugging me and CONTRIBUTING.md discourages pull requests for simple things like this.

### Steps to reproduce
1. Get someone to be angry at you.
2. Wait for them to kick you from a group.
3. Notice improper grammar.

### Expected behaviour
It should say "inaccessible"

"unaccessible" is not a word.

### Actual behaviour
It says "unaccessible"

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 0.10.19

**Comment by john-preston** [comment]
@nikhiljha Thanks, I'll fix it in the next release.
