### ISSUE TITLE
Can't open chat in narrow list if user have Stories

### ISSUE THREAD

**Issue by BANOnotIT** [telegramdesktop/tdesktop#26535]
### Steps to reproduce

1. Have a friend with a story published
2. Make window narrow enough so that chat list becomes avatars-only wide
3. Click on chat entry which happens to be user avatar

### Expected behaviour

That it'll open the chat with the friend

### Actual behaviour

It opens first story

### Operating system

Ubuntu 22.04.1

### Version of Telegram Desktop

4.8.5

### Installation source

Snap

**Comment by Flumeded** [comment]
Well.
 
 It's been fixed....... By completely removing the compact view for contacts.
 Any plans to bring it back?

**Comment by BANOnotIT** [comment]
It's been fixed as of 4.8.7

**Comment by foreveRush** [comment]
Same issue for macOS. App store version 9.7 still has this bug.

**Comment by Aokromes** [comment]
> Same issue for macOS. App store version 9.7 still has this bug.

you are using https://github.com/overtake/TelegramSwift
