### ISSUE TITLE
CSD decorations in sway

### ISSUE THREAD

**Issue by alxchk** [telegramdesktop/tdesktop#26547]
### Steps to reproduce

For some unknown reason telegram starts to draw client side decorations in wayland (both official app and built from sources).
Other Qt6 apps doesn't draw CSD. Actually telegram is the single app which is doing that. Is there any way to troubleshoot this?

sway --version
sway version 1.9-dev-a34d785a (Jul 18 2023, branch 'HEAD')

### Expected behaviour

Telegram  should not draw CSD in sway

### Actual behaviour

Telegram draws CSD in sway

### Operating system

Linux

### Version of Telegram Desktop

4.8.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
If your environment supports server side decorations, you should see the "Use system window frame" option in Settings -> Advanced. If this option doesn't exist, it means your environment doesn't support it and you should request your environment to support it.

**Comment by alxchk** [comment]
Well, there is no such option, however until some time ago there were no issues with that (I hadn't update+restart TG for a while, so don't know exactly when this happend). How TG checks that "there is support"?

**Comment by ilya-fedin** [comment]
This: https://github.com/desktop-app/lib_ui/blob/079d966e45922f90de297fc9f7435cbf8b127b09/ui/platform/linux/ui_linux_wayland_integration.cpp#L38-L40

**Comment by alxchk** [comment]
I do see zxdg_decoration_manager_v1 here.. 
[wayland.log](https://github.com/telegramdesktop/tdesktop/files/12131191/wayland.log)

**Comment by ilya-fedin** [comment]
Maybe sway announces it too late? There's a wl_display_roundtrip call in the WaylandIntegration constructor which is a sync primitive, so the compositor should finish all the requests (including the installed wl_registry listener on the line before the roundtrip, so announcing all the globals) before roundtrip returns.
