### ISSUE TITLE
Voice Message recorder

### ISSUE THREAD

**Issue by SadraKhazaei** [telegramdesktop/tdesktop#26548]
### Is your feature request related to a problem?

The quality of voice messages is too low. Not comparable to Android or iOS clients.
 

### Describe the solution you'd like

A better voice message recorder OR an option in experimental settings to send higher-quality voice messages. 

### Describe alternatives you've considered

I use Audacity for voice recording, or use Telegram on Android.

**Comment by ilya-fedin** [comment]
#26388
