### ISSUE TITLE
Show mutual contacts icon in contacts menu

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#26553]
### Is your feature request related to a problem?

Tdesktop does not show mutual contacts icon like nekogram for android:
![Без имени](https://github.com/telegramdesktop/tdesktop/assets/5204968/fe5c1067-09df-4ec7-ac5d-95c4b6567d99)

### Describe the solution you'd like

Showing mutual contacts icon like in telegram for android.

### Describe alternatives you've considered

...

**Comment by john-preston** [comment]
Official Telegram for Android doesn't have such icon as well 🤔

**Comment by soredake** [comment]
My bad, turns out it's a third party client feature.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
