### ISSUE TITLE
people I am calling from mac desktop can't see the video even though it's on 

### ISSUE THREAD

**Issue by vanyamlb** [telegramdesktop/tdesktop#26550]
### Steps to reproduce

1. start a video call
2. other side can't see your video
3. try turning off and on the video, it will say "...camera is on, off", but we can't see the actual video, only profile picture or black screen

### Expected behaviour

companions see each other videos correctly (it works well on telegram from appstore, mac version, telegram lite also doesn't work)

### Actual behaviour

companions can't see the video started from mac desktop

### Operating system

Ventura 13.4.1 (c)

### Version of Telegram Desktop

4.8.7

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I can't reproduce :( TDesktop 4.8.12 beta <-> Android from Store, one-on-one call started from Android, both can see video if enabled.

Can you check the latest beta version and share:
- who is calling (what device is calling, what device is accepting)
- if it's a call or a voice chat in a group

**Comment by vanyamlb** [comment]
@john-preston 

I just tried to install the beta but still the same. 

MacBook Air 2015 13 inch with TDesktop 4.8.12 beta is calling to Xiaomi 11T 9.7.6 in a call.

Friends with other devices (on windows, iphone and other androids) couldn't see me both in calls or group chats. I see them. And they see that I turn on/off the cam from the text notification and sometimes see the black rectangle where it's supposed to be a video from my Mac.

**Comment by john-preston** [comment]
@vanyamlb But you see your video in the app, just they don't?

**Comment by vanyamlb** [comment]
@john-preston yes.

**Comment by vanyamlb** [comment]
The issue is gone. Telegram Desktop 4.9.5

**Comment by vanyamlb** [comment]
I'm sorry. Sadly I was able to see the video from MacBook on a windows computer, but not from my Android

**Comment by b-rhyme** [comment]
So it hasn't been resolved still? I have the same problem with MacBook Pro Mid-15 on Intel processor. When I call in TG somebody - people can't see me. Does anybody have any ideas what it can be? My guess is that a "broken" TG Desktop application.

**Comment by mariagodlevska** [comment]
I also have this issue. MacBookPro early 2015, Monterey 12.6.7
I have my camera turned on but my friend doesn't see me in a video chat, only the screen with my profile pic. It's the same for contacts and non-contacts. People see me in group chats though.

**Comment by vanyamlb** [comment]
@mariagodlevska  my Macbook Air  is also early 2015

**Comment by socialdistortio** [comment]
Same issue here. MacBook Air mid 2012. All permissions for the app granted, I can see the video, but companions do not see me.Tried to have a call both with iPhone and Android devices. Tried Telegram standalone

**Comment by Segrey74** [comment]
I also have this issue. MacBookAir late 2015, Monterey 12.6.7, the latest version on TG

**Comment by john-preston** [comment]
@Segrey74 Can you please provide the exact version, because you may be using a different application.

**Comment by Segrey74** [comment]
@john-preston  macOS Monterey 12.7.3, Telegram 10.7.259037 AppStore

**Comment by Aokromes** [comment]
> @john-preston macOS Monterey 12.7.3, Telegram 10.7.259037 AppStore, Macbook Air 2015.

you are using https://github.com/overtake/TelegramSwift

**Comment by Segrey74** [comment]
I tried this version. The result is the same.

**Comment by ilya-fedin** [comment]
@mariagodlevska the bot says why: no developer was able to reproduce the issue and no action could be done on it therefore. Find what is missing in steps to reproduce, update the information and if any developer will be able to reproduce the issue, it will be reopened.

**Comment by ethaniel** [comment]
I own 3 Macbook Pros 2015 (all on the latest version available - Monterey 12.7.3), all of them have this problem. When the developers say that they can't reproduce, I have doubts that they are testing on the same hardware.

**Comment by john-preston** [comment]
I don't have this hardware, sorry. Did anyone successfully reproduced that in a VM maybe?

**Comment by ml111233** [comment]
If it's of assistance to anyone - have been struggling with this since last year.  MacBook Air 2013 CTO top spec Core i7, 8gb RAM etc.  All of a sudden, can't be seen on video calls.  After all this time I've traced it back to the last working version of Telegram (not desktop) 9.3.1.  Video is restored using that version.  Hopefully that will allow a timeframe to narrow down what was changed, but my money is on GPU or encoding the webcam stream.  In the current verision, group call video did still work, but had terrible frame rate.  

At least Telegram video calls are usable again using this version.  I've raised bugs for this with Telegram as obviously this version is behind on security updates, etc. and needs resolution.

**Comment by maxnzv** [comment]
The same issue at MacBook Air 2017.
Telegram version: 10.10.1.261717 Stable

**Comment by dmitry-semenov** [comment]
I encountered the same issue with my MacBook Pro 2015. While installing previous versions one by one, I discovered that the last working release is 4.6.0, as 4.6.1 is already broken.
https://github.com/telegramdesktop/tdesktop/compare/v4.6.0...v4.6.1
