### ISSUE TITLE
Videos are downloaded as .jpg's

### ISSUE THREAD

**Issue by ivladak** [telegramdesktop/tdesktop#2655]
### Steps to reproduce
1. Have a contact send you a video.
2. Navigate to that contact's detailed info, under `Shared media` click `<n> Photos & Videos`.
3. Select the video (it strats playing), click a menu button below, select `Save as`. Choose a path in the filesystem to save to, etc.

### Expected behaviour
The video should be saved with the extension it was sent to you by the contact.

### Actual behaviour
Videos are saved with `.jpg` extension. Have to guess the actual extension and rename manually.

### Configuration
**Operating system:** Mac OS X 10.11.6

**Version of Telegram Desktop:** 2.23.50447

**Comment by auchri** [comment]
That's not Telegram Desktop.

**Comment by ivladak** [comment]
My bad. Thanks.

**Comment by john-preston** [comment]
@ivladak You can try Telegram Desktop from https://desktop.telegram.org

**Comment by ivladak** [comment]
@john-preston Already checked it out, thanks) (And it doesn't have this issue. It created 2 files however: .mov and .mp4, but that's fine with me)
