### ISSUE TITLE
The touchpad events in media viewer were broken in the latest version 

### ISSUE THREAD

**Issue by agoudbg** [telegramdesktop/tdesktop#26551]
### Steps to reproduce

Open a picture/video and try to switch/zoom it by touchpad

### Expected behaviour

The photo should be zoomed in/out

### Actual behaviour

Actions take no effects

### Operating system

Window 11

### Version of Telegram Desktop

4.8.7 

### Installation source

Static binary from official website

**Comment by Sortam** [comment]
Still broken in 4.8.8 
Very annoying defect. Could it be given some attention please?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/3654c197a9b2de0e92b30a4890abfdefb20c647b

**Comment by r3poz** [comment]
In versions 4.8.4 - 4.8.10 the problem still remains (Windows 10).
Videos / photos do not respond to an attempt to increase / decrease them with the touchpad.
Version 4.8.3 does not have this problem.

**Comment by agoudbg** [comment]
> [3654c19](https://github.com/telegramdesktop/tdesktop/commit/3654c197a9b2de0e92b30a4890abfdefb20c647b)

I can use touchpad to switch between photos but still cannot **zoom in/out** in 4.8.10.

**Comment by Yigitali0902** [comment]
I think they just changed the way it had functioned
you can hold ctrl and scroll down or up with you two fingers together on touchpad to zoom in or out respectively

**Comment by john-preston** [comment]
@agoudbg @r3poz @Sortam It was by Ctrl + Scroll Up / Down, it should work like that now (starting with 4.8.9).

It doesn't zoom by pinch and never did, there was no such code, only with Ctrl+Scroll and with Ctrl+'+' / Ctrl+'-', that way it works now as well.

**Comment by Dmitry10005** [comment]
> @agoudbg @r3poz @Sortam It was by Ctrl + Scroll Up / Down, it should work like that now (starting with 4.8.9).
> 
> It doesn't zoom by pinch and never did, there was no such code, only with Ctrl+Scroll and with Ctrl+'+' / Ctrl+'-', that way it works now as well.

That's not true, it worked until recently.

**Comment by ilya-fedin** [comment]
I can assume some touchpad drivers can translate pinch gesture to WM_MOUSEWHEEL with MK_CONTROL. This obviously never happens when using the modern API.

**Comment by john-preston** [comment]
Well, maybe. For that to work with the modern scrolling API it has to be implemented manually :(
