### ISSUE TITLE
Hiding Story Preview Feature

### ISSUE THREAD

**Issue by Al00X** [telegramdesktop/tdesktop#26552]
### Is your feature request related to a problem?

With the new "Story" feature which is rolled out,
I would like to kindly ask for a minor enhancement.

Story preview on the top of the chat list is very annoying and bothers my focus and attention; it also causes a counter-productive day.
It's important to only see pinned chats on top only. not some random stories of unworthy millions of contacts.

### Describe the solution you'd like

**A toggle to hide story preview bar on the top of the chat list.**

### Describe alternatives you've considered

Currently rolling back to to an older version **(4.8.3)**

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
