### ISSUE TITLE
When using fcitx5 for Chinese input, the candidate selection box does not appear at the cursor position.

### ISSUE THREAD

**Issue by LL-res** [telegramdesktop/tdesktop#26556]
### Steps to reproduce

1.system ubuntu 23.04 telegram version 4.8.7
2.using fctix5,with pinyin input method
3.type chinese in the chat
![image](https://github.com/telegramdesktop/tdesktop/assets/78481036/9314ea4e-b3fa-4f32-aa35-dbc6d45694ea)

### Expected behaviour

the candidate selection box appears at the cursor position

### Actual behaviour

the candidate selection box does not appear at the cursor position

### Operating system

ubuntu 23.04

### Version of Telegram Desktop

4.8.7

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Ensure QT_IM_MODULE is set to fcitx5, not fcitx

**Comment by LL-res** [comment]
i have set like this
Exec=env QT_IM_MODULE=fcitx5 BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/telegram-desktop_telegram-desktop.desktop /snap/bin/telegram-desktop -- %u
but there's still this problem.
the input method is working but the candidate selection box is still at wrong place....

**Comment by ilya-fedin** [comment]
Is this a regression or was forever like this?

**Comment by LL-res** [comment]
since forever ,i didn't update telegram

**Comment by ilya-fedin** [comment]
> Exec=env QT_IM_MODULE=fcitx5 BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/telegram-desktop_telegram-desktop.desktop /snap/bin/telegram-desktop -- %u

But is there QT_IM_MODULE set session-wide? This .desktop file may not be where tdesktop was started from. It's better to set the variable session-wide.

**Comment by LL-res** [comment]
i set this at /etc/environment,then the input method didn't work in telegram ,but i can still type chinese in other place ,in telegram i can only type english......
XMODIFIERS=@im=fcitx5
GTK_IM_MODULE=fcitx5
QT_IM_MODULE=fcitx5

**Comment by ilya-fedin** [comment]
My guess is snapd is not compatible with fcitx5, try unsandboxed binary

**Comment by LL-res** [comment]
I reinstalled through binary ,the problem solved ,thank you very much

**Comment by breakertt** [comment]
Thanks a lot for your work on the Telegram Desktop on Linux.

I am also using fcitx5 to type Chinese on Telegram. As instructed, I am also using the binary version now.

However, I noticed that my .desktop file with the extra "QT_IM_MODULE=fcitx5" will be immediately overwritten by the software. I followed another issue and finally made it work by adding "DESKTOPINTEGRATION=0" and the dbus activation.

I really feel it is not a gentle way to do it, the reason I don't want to use "QT_IM_MODULE=fcitx5" globally is that it is not recommended by fcitx5 (https://wiki.archlinux.org/title/Fcitx5, https://fcitx-im.org/wiki/Setup_Fcitx_5).

May I ask do you have future plans that make the Telegram desktop works correctly on fcitx5 with only  "QT_IM_MODULE=fcitx" environment variable?

Cheers!
