### ISSUE TITLE
Freezing during file download

### ISSUE THREAD

**Issue by obtim** [telegramdesktop/tdesktop#26559]
### Steps to reproduce

You need to start downloading files(archives) of different sizes from different channels. The total volume over 30 gigabytes.

### Expected behaviour

The file queue should download.

### Actual behaviour

One of the files will hang on downloading (only a part of it will be downloaded) and the whole download queue will stand up. Until this file is restarted or deleted from the queue, the download will not continue.

### Operating system

Windows

### Version of Telegram Desktop

no matter

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
cannot reproduce.

**Comment by obtim** [comment]
It doesn't always reproduce. I can record a video?
As far as I know from people I know: I'm not the only one with the problem.
P.S. I do not use antivirus or firewall.
