### ISSUE TITLE
glibmm 2.76.0 build issue

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#26567]
### Steps to reproduce

Build telegram-desktop with current stable version glibmm 2.76.0.

glibmm 2.77.0 is a development branch according to [this answer](https://bugzilla.redhat.com/show_bug.cgi?id=2222901#c2):

> 2.77.x are development snapshots and definitely not suitable for stable Fedoras

### Expected behaviour

Successful build.

### Actual behaviour

Build failure due to this:

https://github.com/telegramdesktop/tdesktop/pull/26419
https://github.com/desktop-app/cmake_helpers/pull/286

### Operating system

Fedora 38

### Version of Telegram Desktop

4.8.7

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Actually, they have provided two solutions, so I don't get what this issue is about.
