### ISSUE TITLE
Telegram Randomly crashing when I'm using it (Linux Ubuntu 22.04.2 LTS)

### ISSUE THREAD

**Issue by luciano2777** [telegramdesktop/tdesktop#26562]
### Steps to reproduce

Just open Telegram

### Expected behaviour

Telegram working properly indefinitely when I use it

### Actual behaviour

Telegram just randomly crash when I'm using it

### Operating system

Ubuntu 22.04.2 LTS

### Version of Telegram Desktop

4.8.7

### Installation source

Static binary from official website

### Crash ID

[2023.07.23 15:38:41] RPC Error: request 144 got fail with code 400, error WEBFILE_NOT_AVAILABLE

### Logs

```shell
#First crash
[2023.07.23 09:58:18] OpenGL: QOpenGLContext created, version: 4.4.
[2023.07.23 09:58:18] OpenGL: [TRUE] (Window)
[2023.07.23 09:58:19] RPC Error: request 67 got fail with code 400, error USER_NOT_PARTICIPANT
#Second Crash
[2023.07.23 15:23:53] OpenGL: QOpenGLContext created, version: 4.4.
[2023.07.23 15:23:53] OpenGL: [TRUE] (Window)
[2023.07.23 15:23:54] API Warning: not loaded minimal channel applied.
[2023.07.23 15:23:54] API Warning: not loaded minimal channel applied.
[2023.07.23 15:23:54] RPC Error: request 75 got fail with code 400, error USER_NOT_PARTICIPANT
[2023.07.23 15:23:54] API Warning: not loaded minimal channel applied.
[2023.07.23 15:24:15] Skipping message, because it is already in blocks!
[2023.07.23 15:24:49] API Warning: not loaded minimal channel applied.
[2023.07.23 15:25:01] Skipping message, because it is already in blocks!
[2023.07.23 15:25:24] Skipping message, because it is already in blocks!
[2023.07.23 15:25:27] Skipping message, because it is already in blocks!
[2023.07.23 15:25:34] RPC Error: request 251 got fail with code 400, error WEBFILE_NOT_AVAILABLE
[2023.07.23 15:25:34] RPC Error: request 252 got fail with code 400, error WEBFILE_NOT_AVAILABLE
[2023.07.23 15:25:49] Skipping message, because it is already in blocks!
Third Crash
[2023.07.23 15:27:06] OpenGL: QOpenGLContext created, version: 4.4.
[2023.07.23 15:27:06] OpenGL: [TRUE] (Window)
[2023.07.23 15:27:07] Message Info: bad message notification received (error_code 33) for msg_id = 7259097859485630204, seq_no = 66
[2023.07.23 15:27:07] Message Info: bad message notification received, msgId 7259097859485630204, error_code 33
[2023.07.23 15:27:07] API Warning: not loaded minimal channel applied.
[2023.07.23 15:27:07] API Warning: not loaded minimal channel applied.
[2023.07.23 15:27:07] RPC Error: request 74 got fail with code 400, error USER_NOT_PARTICIPANT
[2023.07.23 15:27:09] Message Info: bad message notification received (error_code 33) for msg_id = 7259097868270188072, seq_no = 8
[2023.07.23 15:27:09] Message Info: bad message notification received, msgId 7259097868270188072, error_code 33
[2023.07.23 15:27:09] Message Info: bad message notification received (error_code 33) for msg_id = 7259097868616647608, seq_no = 10
[2023.07.23 15:27:09] Message Info: bad message notification received, msgId 7259097868616647608, error_code 33
[2023.07.23 15:27:09] MTP Info: -404 error received in 160002 with temporary key, assuming it was destroyed.
[2023.07.23 15:27:10] RPC Error: request 139 got fail with code 400, error WEBFILE_NOT_AVAILABLE
[2023.07.23 15:27:10] RPC Error: request 140 got fail with code 400, error WEBFILE_NOT_AVAILABLE
[2023.07.23 15:27:25] Skipping message, because it is already in blocks!
[2023.07.23 15:27:47] API Warning: not loaded minimal channel applied.
[2023.07.23 15:28:39] Message Info: bad message notification received (error_code 33) for msg_id = 7259098254877742704, seq_no = 352
[2023.07.23 15:28:39] Message Info: bad message notification received, msgId 7259098254877742704, error_code 33

#Latest Crash (I activated beta versions for it)
[2023.07.23 15:41:55] OpenGL: QOpenGLContext created, version: 4.4.
[2023.07.23 15:41:55] OpenGL: [TRUE] (Window)
[2023.07.23 15:41:56] API Warning: not loaded minimal channel applied.
[2023.07.23 15:41:56] API Warning: not loaded minimal channel applied.
[2023.07.23 15:41:57] RPC Error: request 70 got fail with code 400, error USER_NOT_PARTICIPANT
```

**Comment by tprei** [comment]
same happening here

**Comment by ilya-fedin** [comment]
> ### Crash ID
> 
> [2023.07.23 15:38:41] RPC Error: request 144 got fail with code 400, error WEBFILE_NOT_AVAILABLE

This is not a crash ID. Please re-read the issue template carefully, it has explanation how to get crash ID.

**Comment by luciano2777** [comment]
> > ### Crash ID
> > [2023.07.23 15:38:41] RPC Error: request 144 got fail with code 400, error WEBFILE_NOT_AVAILABLE
> 
> This is not a crash ID. Please re-read the issue template carefully, it has explanation on how to get crash ID.

I have enabled the Beta installation in settings, however I don't see the crash reporter anywhere, where is it?

**Comment by ilya-fedin** [comment]
It appears on the next launch after the crash

**Comment by ilya-fedin** [comment]
If it doesn't appear then try to launch Telegram from terminal whether it really crashes. If it's a crash then you should see a segmentation fault or abort.

**Comment by luciano2777** [comment]
> If it doesn't appear then try to launch Telegram from terminal to check whether it really crashes. If it's a crash then you should see a segmentation fault or abort.

I have run it through the Terminal,and still it doesn't show anything like that

**Comment by ilya-fedin** [comment]
Apparently it's not a crash? Can you provide the terminal output?

**Comment by luciano2777** [comment]
> Apparently it's not a crash? Can you provide the terminal output?

Yes sure 

> $ /home/luciano/Desktop/Telegram/Telegram
> QPainter::begin: Paint device returned engine == 0, type: 2
> QWidget::render: Cannot render with an inactive painter
> qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
> 
> (Telegram:4970): Gtk-WARNING **: 18:18:07.236: Theme parsing error: <data>:1:0: Expected a valid selector

**Comment by ilya-fedin** [comment]
And that's all? Do you have shell prompt after these lines?

**Comment by luciano2777** [comment]
> And that's all? Do you have shell prompt after these lines?

Hmmmm no, That is everything I write for running Telegram from the terminal 
![image](https://github.com/telegramdesktop/tdesktop/assets/124527669/922d48da-819c-4547-a632-7740bdff9142)

**Comment by ilya-fedin** [comment]
is this output after the bug happens? If it is, this means Telegram is still running. Apparently the window is just hidden.

**Comment by luciano2777** [comment]
> is this output after the bug happens? If it is, this means Telegram is still running. Apparently the window is just hidden.

No, that also appears also when Telegram Is run, rn is seemingly working, it hasn't yet crashed.

However I noticed that I got an RPC error in the logs when I launch it
![image](https://github.com/telegramdesktop/tdesktop/assets/124527669/7ecdc0dd-dde1-42a1-a2cb-12b4ef1ef801)

**Comment by ilya-fedin** [comment]
> No, that also appears also when Telegram Is run, rn is seemingly working, it hasn't yet crashed.

I asked for the output after the bug happens. I obviously don't need the output when everything is ok.

**Comment by luciano2777** [comment]
> > No, that also appears also when Telegram Is run, rn is seemingly working, it hasn't yet crashed.
> 
> I asked for the output after the bug happens. I obviously don't need the output when everything is ok.

Just got from errors that might be related to the Issue
![image](https://github.com/telegramdesktop/tdesktop/assets/124527669/fb6ede01-e9bf-4f4c-9f5b-e89161a64d84)

However I will update you with the output when the bug happens again

**Comment by ilya-fedin** [comment]
I don't see anything related. That's all regular Qt grunt.

**Comment by History-exe** [comment]
Same on Ubuntu 20.04.6 LTS

**Comment by thlkmoeller** [comment]
I have the same problem on Linux Mint 20.3 with Cinnamon. Telegram 4.8.7
Crashed already 3 times in 10 minutes

**Comment by mikhashev** [comment]
Same problem Ubuntu 20.04.6 LTS, Telegram 4.8.7
Repeatedly crashes

**Comment by thlkmoeller** [comment]
how to find this Crash ID? I might provide it, too. After the crash, yeah?

**Comment by ilya-fedin** [comment]
After the crash with enabled beta in avanced settings, yes

**Comment by qnxdev** [comment]
Same issue for me

**Comment by thlkmoeller** [comment]
> After the crash with enabled beta in advanced settings, yes

ok i activated beta versions. Now Telegram crashed, what should i do? exactly?

**Comment by thlkmoeller** [comment]
i started Telegram now again, but no crash id and no send button appeared. everything was just normal.

**Comment by thlkmoeller** [comment]
how to start Telegram Desktop from Terminal?

**Comment by ilya-fedin** [comment]
At that point I don't think you're qualified enough to do debugging

**Comment by thlkmoeller** [comment]
i just need the correct binary. i normally start in the GUI. just let me know the answer instead of telling that i cannot do it

**Comment by ilya-fedin** [comment]
Open the terminal, `cd` to the directory containing the binary, run `./Telegram`

**Comment by thlkmoeller** [comment]
i did. when starting, this was shown:
`thlk@thlk-ThinkPad-X260:~$ cd /home/thlk/Downloads/Telegram
thlk@thlk-ThinkPad-X260:~/Downloads/Telegram$ ./Telegram 
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter



`

**Comment by thlkmoeller** [comment]
but the text in the terminal window did not change. When i wanted to type something, also the terminal window crashed.
and by the way, when starting Telegram from Terminal, i had to register the instance newly, i mean i was asked to type my phone number

**Comment by ilya-fedin** [comment]
It was discussed in the issue that the output should recorded when the bug happens, not when you start Telegram

**Comment by rohallah12** [comment]
i have the same problem, happened only after updating recently, this is just ruining my day and works

**Comment by mikhashev** [comment]
> Same problem Ubuntu 20.04.6 LTS, Telegram 4.8.7 Repeatedly crashes

Also, 30-60 mins after update to 4.8.7 version was done, everything work good. Waiting in terminal to repeat problem, but nothing worse happened.

**Comment by ilya-fedin** [comment]
Could it be that what you're seeing is not random crashes but something (apparently some system component) kills telegram after a timeout, only when you launching it the normal way and not via terminal?

**Comment by rohallah12** [comment]
looks like appArmor is having some issue with some snap packages, but my telegram is not snap version i think, idk if this is even related to telegram, but i got this output only right after the crash

> > Could it be that what you're seeing is not random crashes but something (apparently some system component) kills telegram after a timeout (I guess it should be the same after each launch so having a timer is handy to diagnose), only when you're launching it the normal way and not via terminal (as apparently that system component is not supervising telegram is that case)?
> 
> i used dmesg to output system logs right after crash, apprerantly something is denied? i opened telegram through GUI this time, no terminal
> 
> output: [ 6278.050097] audit: type=1400 audit(1690197995.166:75): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/19457/usr/lib/snapd/snap-confine" pid=19463 comm="snap-confine" capability=12 capname="net_admin" [ 6278.050102] audit: type=1400 audit(1690197995.166:76): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/19457/usr/lib/snapd/snap-confine" pid=19463 comm="snap-confine" capability=38 capname="perfmon"

looks like appArmor is having some issue with some snap packages, but my telegram is not snap version i think, idk if this is even related to telegram, but i got this output only right after the crash

**Comment by ilya-fedin** [comment]
i don't think that's related and I don't think dmesg would help here

**Comment by ilya-fedin** [comment]
the overall system log (journalctl) is more likely to have something related. dmesg is only about kernel.

**Comment by rohallah12** [comment]
> the overall system log (journalctl) is more likely to have something related. dmesg is only about kernel.

i used journalctl with this command:
journalctl --since "30 minutes ago" | grep Telegram

 i got this output:
جولای 24 17:43:02 roholah-ASUS-TUF-Dash-F15-FX517ZR-FX517ZR Telegram[3239]: Theme parsing error: <data>:1:0: Expected a valid selector
جولای 24 14:55:08 roholah-ASUS-TUF-Dash-F15-FX517ZR-FX517ZR Telegram[18833]: Theme parsing error: <data>:1:0: Expected a valid selector
جولای 24 15:05:47 roholah-ASUS-TUF-Dash-F15-FX517ZR-FX517ZR Telegram[20591]: Theme parsing error: <data>:1:0: Expected a valid selector

**Comment by ilya-fedin** [comment]
maybe just check with a timer when tdesktop is killed? if it happens after the same amount of time then we would know that it's that for sure.

**Comment by rohallah12** [comment]
i noticed that i have 2 telegrams in my apps menu, one of them crashes while the other one does not (when using terminal).i checked this multiple times and now i am sure that one of this telegram's is broken while the other one is not, so you should either run through terminal or run the correct one from app menu?(mabe i messed up something when i updated telegram). 
i checked 
"/~local/share/applications"
to check the telegram apps i have in my apps menu

**command**
cat ~/.local/share/applications/*.desktop

**outout:**
**[Desktop Entry]**
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/home/roholah/Downloads/Telegram/Telegram
Exec=/home/roholah/Downloads/Telegram/Telegram -workdir /home/roholah/.local/share/TelegramDesktop/ -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
Actions=quit;
DBusActivatable=true
SingleMainWindow=true
X-GNOME-UsesNotifications=true
X-GNOME-SingleWindow=true

**[Desktop Action quit]**
Exec=/home/roholah/Downloads/Telegram/Telegram -workdir /home/roholah/.local/share/TelegramDesktop/ -quit
Name=Quit Telegram
Icon=application-exit
**[Desktop Entry]**
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/home/roholah/Downloads/Telegram/Telegram
Exec=/home/roholah/Downloads/Telegram/Telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
Actions=quit;
DBusActivatable=true
SingleMainWindow=true
X-GNOME-UsesNotifications=true
X-GNOME-SingleWindow=true

**[Desktop Action quit]**
Exec=/home/roholah/Downloads/Telegram/Telegram -quit
Name=Quit Telegram
Icon=application-exit
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
NoDisplay=true
Exec=/home/roholah/Downloads/Telegram/Telegram -workdir /home/roholah/.local/share/TelegramDesktop/ -- %u
Name=Telegram Desktop
Comment=Custom definition for Telegram Desktop

**Comment by mrProper-666** [comment]
same issue for me, found this at journalctl
`dbus-daemon[3203]: [session uid=1000 pid=3203] Failed to activate service 'org.telegram.desktop._d51dfd9f3ce291d2253339b21bdf1c35': timed out (service_start_timeout=120000ms)`

**Comment by ilya-fedin** [comment]
Provide the content of `~/.local/share/applications/org.telegram.desktop._d51dfd9f3ce291d2253339b21bdf1c35.desktop` and `~/.local/dbus-1/services/org.telegram.desktop._d51dfd9f3ce291d2253339b21bdf1c35.service`

**Comment by mrProper-666** [comment]
```
 ~/.local/share/applications  cat org.telegram.desktop._d51dfd9f3ce291d2253339b21bdf1c35.desktop
[Desktop Entry]
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/opt/Telegram/Telegram
Exec=/opt/Telegram/Telegram -workdir /home/mrproper/.local/share/TelegramDesktop/ -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
Actions=quit;
DBusActivatable=true
SingleMainWindow=true
X-GNOME-UsesNotifications=true
X-GNOME-SingleWindow=true

[Desktop Action quit]
Exec=/opt/Telegram/Telegram -workdir /home/mrproper/.local/share/TelegramDesktop/ -quit
Name=Quit Telegram
Icon=application-exit

```

```
 ~/.local/share/dbus-1/services  cat org.telegram.desktop._d51dfd9f3ce291d2253339b21bdf1c35.service
[D-BUS Service]
Name=org.telegram.desktop._d51dfd9f3ce291d2253339b21bdf1c35
Exec=/opt/Telegram/Telegram

```

**Comment by ilya-fedin** [comment]
Oh. There was a fix for that in 4.8.7 but apparently because that instance never launches (the system launches another instance due to the lack of -workdir in the .service file), it never gets fixed...

**Comment by mrProper-666** [comment]
added working directory to .service and still doesn't crash
but very strange - I don't use a custom workdir, looking at the commit https://github.com/telegramdesktop/tdesktop/commit/30c73fbdf29ff8e6f36641f4b4e271c7974ed88e there shouldn't be a workdir in the .service dbus file
perhaps it is worth deleting the workdir in .desktop and in .service?

**Comment by ilya-fedin** [comment]
The -workdir was always passed in the past, apparently it was forgotten to clean up those files when the meaning of -workdir has changed

**Comment by kyilkhor** [comment]
same happens for me, crashes all the time

**Comment by Bevor** [comment]
I can confirm it (Ubuntu 22.04.2 LTS). Since the last update some days ago, it continously crashes when I use the Launcher icon and when I upload a video in a group or just watch a video or something. When I run it in console (to maybe figure out what's wrong and to give debbuging information), there is no crash.

**Comment by ilya-fedin** [comment]
> updating all the time is gonna be boring

all the time?

**Comment by ilya-fedin** [comment]
Is this still a problem?

**Comment by mrProper-666** [comment]
no, after a manual fix or a minor update on another linux machine everything works fine for me
