### ISSUE TITLE
Screen turns off with FreeSync enabled when viewing media

### ISSUE THREAD

**Issue by Aiku1** [telegramdesktop/tdesktop#26569]
### Steps to reproduce

Open any photo/video/gif fullscreen

### Expected behaviour

The content should appear as expected

### Actual behaviour

The display turns off, as if it was disconnected from the computer. Clicking or pressing ESC closes the media viewer and resumes normal activity.

### Operating system

Windows 10

### Version of Telegram Desktop

4.8.7

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
You can try changing ANGLE backend in Settings > Advanced to some other value or disable it completely and see if it helps.
