### ISSUE TITLE
Very low resolution icon in KDE 5 Plasma icon tray

### ISSUE THREAD

**Issue by slowaways** [telegramdesktop/tdesktop#2656]
### Steps to reproduce
1. Download Telegram at https://telegram.org/dl/desktop/linux
2. Open Telegram
3. Set the height of your panel so that the icons in the notification area are larger than 16x16.

### Expected behaviour
Very Low Resolution (only 16x16 supported?)

### Actual behaviour
Resolution of at least 32x32
![spectacle x11033](https://cloud.githubusercontent.com/assets/9668277/20465674/bba435a0-af41-11e6-98eb-acb5341cb89e.png)

### Configuration
**Operating system:**
Ubuntu 16.04.1 with KDE 5 Plasma (installed from "apt install kubuntu-desktop")

**Version of Telegram Desktop:**
0.10.16

### Logs
--- No logs ---

**Comment by Aokromes** [comment]
#2230 ?

**Comment by slowaways** [comment]
@Aokromes, Yes, sorry!

**Comment by Aokromes** [comment]
you can close the ticket yourself :)
