### ISSUE TITLE
Падает через 5-10 минут.

### ISSUE THREAD

**Issue by Guzya** [telegramdesktop/tdesktop#26570]
### Steps to reproduce

Запускаю и спокойно работаю. Через 5-10 минут его уже нет.
Не зависит, был свернут или в трее или развернут.

Если запускаю через терминал, работает. 
В терминал падает несколько ошибок.

### Expected behaviour

Должен работать.

### Actual behaviour

Через небольшой промежуток времени падает (ошибок или сообщений не выводит)

### Operating system

Linux Mint 21.1 Cinnamon

### Version of Telegram Desktop

4.8.7

### Installation source

Static binary from official website

### Logs

```shell
~ $ ./Загрузки/Telegram/Telegram 
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment

(Telegram:5891): Gtk-WARNING **: 22:03:52.796: Theme parsing error: <data>:1:0: Expected a valid selector
Окно или вкладка откроются в текущем сеансе браузера.
```

**Comment by Aokromes** [comment]
duplicate, also this bug tracker is english only.

**Comment by Guzya** [comment]
@Fardek  попробую

I will try.

**Comment by Guzya** [comment]
@Fardek  не помогло.

it didn't help.
