### ISSUE TITLE
Crash on story deletion

### ISSUE THREAD

**Issue by Laiteux** [telegramdesktop/tdesktop#26571]
### Steps to reproduce

Delete all of your stories until the very last one (which will cause the crash)

### Expected behaviour

No crash

### Actual behaviour

Crash

### Operating system

Windows 11

### Version of Telegram Desktop

4.8.7 x67

### Installation source

Static binary from official website

### Crash ID

b1c75625-900d-42aa-a705-825674c1e795

### Logs

```
[2023.07.25 07:37:37] Assertion Failed! "!_pollingSettings.contains(story.get())" data_stories.cpp:725
```

**Comment by jidckii** [comment]
Linux amd64 also Crashed

**Comment by john-preston** [comment]
How exactly do you delete? Is it from "My Stories" or from "Stories Archive"? Is it from the story viewer or from right click menu on a single story or from selecting several stories in a section and deleting by a button in top bar?

**Comment by Laiteux** [comment]
Clicked on my profile picture, which brought up stories.

Tried deleting with both Right Click -> Delete and ••• -> Delete

**Comment by john-preston** [comment]
Thanks. I hope I've fixed that.

**Comment by Laiteux** [comment]
Will attempt to confirm on next update. Thank you! (:

**Comment by Laiteux** [comment]
✅
