### ISSUE TITLE
Telegram generates weird .desktop file

### ISSUE THREAD

**Issue by spicy-hero** [telegramdesktop/tdesktop#26573]
### Steps to reproduce

1. launch it from terminal
2. auto-generated in `~/.local/share/applications` with filename `org.telegram.desktop._3e485da34fc040f9218e3891ecde1e6c.desktop` whenever it does not exist 

The content is as follows:
```
[Desktop Entry]
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/opt/Telegram/Telegram
Exec=/opt/Telegram/Telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
Actions=quit;
DBusActivatable=true
SingleMainWindow=true
X-GNOME-UsesNotifications=true
X-GNOME-SingleWindow=true

[Desktop Action quit]
Exec=/opt/Telegram/Telegram -quit
Name=Quit Telegram
Icon=application-exit
```

the line `Actions=quit;` and the `[Desktop Action quit]` section cause my application launcher (ulauncher) fail to launch Telegram. However, my gnome application launcher works fine.  

### Expected behaviour

other application launchers can work with it. It was perfectly working until today. 

### Actual behaviour

Nothing happened. 

### Operating system

debian 12 bookworm

### Version of Telegram Desktop

4.8.7

### Installation source

Static binary from official website

**Comment by friday** [comment]
No, the problem is `DBusActivatable=true` shouldn't be there unless it's really DBusActivatable (which the debug output says very clearly that it isn't)

**Comment by friday** [comment]
This commit is either what caused the problem directly or related to it @ilya-fedin: https://github.com/telegramdesktop/tdesktop/commit/272d2da04af1e5a98b63cdebae52ea0e5a060407
Looks like it changed the format to remove the hash id from the service file, but not removing/regenerating the desktop file itself.

**Comment by ilya-fedin** [comment]
> No, the problem is `DBusActivatable=true` shouldn't be there unless it's really DBusActivatable (which the debug output says very clearly that it isn't).

tdesktop is d-bus activatable.

**Comment by friday** [comment]
If any Telegram users see this want to fix their apps it's probably just a matter of deleting the old file and then restarting telegram, or renaming it so it follows the spec:

```sh
mv ~/.local/share/applications/org.telegram.desktop._*.desktop ~/.local/share/applications/org.telegram.desktop.desktop
```

I'm not sure it has to run repeatedly or just once. I don't use Telegram. I just maintain an app that falsely got bug reports that belongs here.

**Comment by ilya-fedin** [comment]
It's wrong. tdesktop has app id with the hash postfix.

**Comment by friday** [comment]
Then the service file should have that too.

> error sending Activate message to application: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.telegram._3e485da34fc040f9218e3891ecde1e6c was not provided by any .service files

**Comment by ilya-fedin** [comment]
It has. Both GeberateDesktopFile abd GenerateServiceFile use the same global function QGuiApplication::desktopFileName().

**Comment by friday** [comment]
Do you delete old generated desktop files also? Otherwise this will happen.

**Comment by ilya-fedin** [comment]
What do you mean by old?

**Comment by ilya-fedin** [comment]
> error sending Activate message to application: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.telegram._3e485da34fc040f9218e3891ecde1e6c was not provided by any .service files

Looks like your launcher removes `.desktop` what of course leads to such a bug.

**Comment by friday** [comment]
> Looks like your launcher removes `.desktop` from the middle what of course leads to such a bug.

Thank you :+1: Indeed, this was the case, because we need the app id without the ".desktop" extension, and were doing that in an unsafe way. I just released a new version that removes the extension from the end only. I haven't tested that it runs, but it would cause the issue if the desktop entry has ".desktop" in the middle.

Apologies for blaming this on you. We had many invalid issues filed because of malformed desktop entries leading to issues like this.
