### ISSUE TITLE
link info preview not work with other domain ports

### ISSUE THREAD

**Issue by m0x61h0x64i** [telegramdesktop/tdesktop#26577]
### Steps to reproduce

go to saved messages
put this link in the input and dont send it : https://dl.nothserver.shop:2053/qr-codes/2023-7-26-16-25.png
you can see it does not try to get link info even if you change the name of the image
but clear input and put this link : https://dl.nothserver.shop/qr-codes/2023-7-26-16-25.png
if you try to change the name of the image it shows that its trying to get link info which means thats working correctly this way!
so, in the first case it does not try to get link info because the link has port in it, but in the second case it tries to get link info because it does not have a port.

its a bug, i can not use default port like 80 or 443 to show images using them because these ports are being used by another application on the server, so please fix it

### Expected behaviour

link info preview SHOULD work with other domain ports

### Actual behaviour

Hello, i wanted to report a bug.

Check this link it does not generate preview of link info :
https://dl.nothserver.shop:2053/qr-codes/2023-7-26-16-25.png

I realized that it does not care about image format, direct download or preview only, image size, image name, image height&width, i guess the problem is the port of the domain that it cannot access and get preview of the image.

But, I can only use port 2053 as API endpoint because port 443 and 80 are both in use by another application on the server.

I need to show image preview for my telegram bot users.

### Operating system

all platforms

### Version of Telegram Desktop

all versions

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
i don't see preview on any of the 2 links.

**Comment by m0x61h0x64i** [comment]
@Aokromes yes because i have my image on the port 2083 and thats the only port that can access my image there

using browser it shows the image, check https://dl.nothserver.shop:2053/qr-codes/2023-7-26-16-25.png

using telegram it does not show the image preview

check : https://bugs.telegram.org/c/30530
