### ISSUE TITLE
Drag-to-forward no longer works

### ISSUE THREAD

**Issue by lilydjwg** [telegramdesktop/tdesktop#26576]
### Steps to reproduce

1. select a message
2. drag it to a chat in the chat list

### Expected behaviour

Ready to forward the dragged message to the chat where it was dropped.

(It worked with version 4.8.1.)

### Actual behaviour

Drop does nothing except the mouse cursor becomes `not-allowed` style for some time.

(I tested again telegram.org's updated 4.8.9 version, but another third-party build of 4.8.4 also has this issue.)

### Operating system

Arch Linux

### Version of Telegram Desktop

4.8.9

### Installation source

Static binary from official website

**Comment by makecraft** [comment]
It also happens to me, I hope it will be solved soon

**Comment by Aokromes** [comment]
works for me (TM) you are using touchpad?

**Comment by lilydjwg** [comment]
I'm using a mouse.

**Comment by ilya-fedin** [comment]
> works for me (TM)

I can't reproduce as well on Plasma Wayland with touchpad.

**Comment by lilydjwg** [comment]
No longer happens with latest Telegram build (4.10.2) and unofficial build with Qt 6.5.3.
