### ISSUE TITLE
Cannot close "Please update your operating system" banner.

### ISSUE THREAD

**Issue by galenhuntington** [telegramdesktop/tdesktop#26589]
### Steps to reproduce

Open Telegram.  A giant red banner at the top says,

PLEASE UPDATE YOUR OPERATING SYSTEM.
So Telegram can update to newer versions.

### Expected behaviour

There is an "X" in the upper-right corner of the banner, which one would expect would dismiss it when clicked.

### Actual behaviour

Nothing happens when I click "X".  In fact, there seems to be no way to make the banner go away.  I understand that it wants me to upgrade my OS but that's not always possible.

### Operating system

Ubuntu 18.04

### Version of Telegram Desktop

4.8.9

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/f1ab712f077ec73c42812995056b48c7f9a16ec8
