### ISSUE TITLE
Random order of song not working

### ISSUE THREAD

**Issue by assetkad** [telegramdesktop/tdesktop#26586]
### Steps to reproduce

1. In one telegram channel, I clicked play on a song and chose a random order
2. After clicking, the app crashed

### Expected behaviour

After clicking the music should have continued to play and you could click on the next song

### Actual behaviour

After clicking the app just crashed nothing works.

### Operating system

Linux Xubuntu 22.04

### Version of Telegram Desktop

4.8.9

### Installation source

Static binary from official website

**Comment by assetkad** [comment]
My colleagues also have this problem, all of us work on this operating system

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by alcaravanosu** [comment]
> plz enable beta, restart telegram and send crash id on next start and post id here.

Same behaviour. 

Operating system
Fedora Linux 36 (Xfce) x86_64

Version of Telegram Desktop
4.8.9

Installation source
Static binary from official website

Crash ID
No response

Logs
No response

**Comment by ilya-fedin** [comment]
#26519
