### ISSUE TITLE
Opens (or rather tries to open) PDF files with Wine

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#26581]
### Steps to reproduce

On Linux:
1. click on a pdf file that someone has sent to a chat

### Expected behaviour

Should open it on the system's default application for opening PDF files, which on my system seems to be Okular (I never touched such setting). When double click on a PDF file from Dolphin (the system file browser), for example, it opens it in Okular

### Actual behaviour

For some reason launches Wine, and (unsurprisingly) doesn't open the PDF file at all.

### Operating system

Manjaro Linux

### Version of Telegram Desktop

4.8.4

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
IIRC Plasma doesn't use freedesktop-standardized way of setting pre-installed default applcations but uses its own way so any non-KDE application can't know what's your default application is. The only things you can are switch to another DE or set the default via a non-KDE tool (note that xdg-utils tools are just bash scripts that call DE tools so it's unlikely to work).
