### ISSUE TITLE
Screen Sharing is not working in direct chat mode.

### ISSUE THREAD

**Issue by giobus75** [telegramdesktop/tdesktop#26584]
### Steps to reproduce

1. Call one of your contacts
2. Try to share your screen

### Expected behaviour

The screen is shared

### Actual behaviour

The screen is not shared but a black screen with the avatar is shown. 
Screen sharing only works on group chats.

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.8.8

### Installation source

Static binary from official website

**Comment by giobus75** [comment]
The procedure you described worked for me as well, but a few weeks ago. Now it is impossible for me to share the screen unless I participate in a group chat.

**Comment by mcogoni** [comment]
I can confirm what @giobus75 stated: it's not possible anymore to stop sharing and reshare to bypass the bug. I'm on Manjaro and kernel 6.1.38.

**Comment by vijeetgv** [comment]
I can confirm this is a real issue on Ubuntu 22. Can we prioritize this bug please?

**Comment by mgaggero** [comment]
I'm experiencing the same issue in macOS Ventura 13.4.1(c), Telegram 4.8.10.
Sharing the screen when the video is on lead to no screen visible to the peer.
A workaround that seems working is to STOP the video and THEN share the screen but activating the video after the screen goes away the same.
Still an issue that is not possible to share the screen with the video on.
