### ISSUE TITLE
[Linux] Wrong screen positioning when opening Telegram again

### ISSUE THREAD

**Issue by shayandrg** [telegramdesktop/tdesktop#26591]
### Steps to reproduce

1. Download and install latest version of telegram-desktop from snap store on ubuntu
2. Run telegram
3. Drag telegram window to somewhere on your screen
4. Close (not quit)
5. Open telegram

### Expected behaviour

Telegram should re-open where it was when it was closed

### Actual behaviour

it open somewhere else on screen. for example when you opened it, you drag it to right of screen but when you re-open it, it goes left of screen

### Operating system

Linux, Ubuntu 22 LTS with latest updates

### Version of Telegram Desktop

Currently 4.8.10 (latest)

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Ubuntu 22.04 just doesn't have support for that due to Wayland

**Comment by shayandrg** [comment]
> 

i think it just not about ubuntu. because in older version of telegram like 3.5 it works correctly. on the same environment!

**Comment by ilya-fedin** [comment]
3.5 was before 22.04 is out so you apparently haven't really used it with 22.04
