### ISSUE TITLE
Allow pinning chat opened in separate window to the top layer (always on top) (Windows Desktop client)

### ISSUE THREAD

**Issue by AKrasheninnikov** [telegramdesktop/tdesktop#26596]
### Is your feature request related to a problem?

Some chats may be very important to track, maybe to the point when the window should not be overlapped by any other. 

### Describe the solution you'd like

I'd like to have the option to display such separate chat window 'always on top'.

### Describe alternatives you've considered

having another device or buying one more graphics card + display may solve the issue, but seems overkill.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/368
