### ISSUE TITLE
Screensaver inhibit doesn't work on GNOME, Wayland, Linux

### ISSUE THREAD

**Issue by gentoo-root** [telegramdesktop/tdesktop#26592]
### Steps to reproduce

1. Set the "screen blank" delay to 1 minute: `gsettings set org.gnome.desktop.session idle-delay 60`
2. In Telegram, open a video longer than 1 minute or start a video call.
3. Wait for more than 1 minute without any activity such as moving the mouse pointer or pressing keyboard keys.

### Expected behaviour

The screen saver shouldn't start, the user should be able to watch the video to the end or be present in the video call.

### Actual behaviour

The screen saver kicks in after one minute of inactivity.

It happens for both the latest Flatpak package (4.8.9) and the latest official binary from tar.xz (4.8.10). `systemd-inhibit --list` doesn't show any inhibits related to Telegram. It also reproduces on Ubuntu 23.04 with the Snap package.

I saw a [comment](https://github.com/telegramdesktop/tdesktop/issues/26008#issuecomment-1460291576) about xdg-desktop-portal, but as far as I understand that shouldn't apply to the tar.xz binary (and there is also some vague memory it used to work on an older Ubuntu with the deb package of Telegram, before they switched it to Snap). Therefore, two questions:

1. If my understanding is correct, what could have gone wrong with non-portal inhibits?
2. Can Telegram use at least some workaround to force using the portal when it's known good? For example, an environment variable that the user or the distribution could set.

### Operating system

Arch Linux, GNOME 44.3

### Version of Telegram Desktop

4.8.9 (flatpak), 4.8.10 (tar.xz)

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
As far as I can see, GNOME [still haven't merged](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/111) screensaver inhibit support.

> `systemd-inhibit --list` doesn't show any inhibits related to Telegram. It also reproduces on Ubuntu 23.04 with the Snap package.

I believe this tool shows only programs using the logind API and logind API is for system services. For a user session, the session manager usually inhibits logind power management and controls power on its own so using logind is no-op. GUI applications are supposed to talk to the display server: XResetScreenSaver on X11 and idle-inhibit on Wayland (and that's what Telegram does). systemd knows nothing about that of course and so you won't see GUI applications in `systemd-inhibit` output.

**Comment by ilya-fedin** [comment]
> Could you elaborate why this pull request is important? VLC and Firefox manage to inhibit the screensaver, why Telegram can't use the same APIs?

Personally I have no interest in implementing lots of APIs and supporting the current situation with multiple ways of doing the same thing. If GNOME wants to support all applications, it has to support the standard Wayland way and not forcing everyone to support their handcrafted ones.

**Comment by john-preston** [comment]
If someone would PR an implementation that is used in VLC / Firefox I'll thankfully merge it.

**Comment by ilya-fedin** [comment]
I believe it's better just to wait when GNOME will implement the feature than cluttering the code with intermediate solutions which will bug for sure.

**Comment by ilya-fedin** [comment]
I see https://gitlab.gnome.org/GNOME/mutter/-/issues/20 is closed as fixed in GNOME 45, so tdesktop doesn't need a change

**Comment by ilya-fedin** [comment]
> VLC and Firefox manage to inhibit the screensaver, why Telegram can't use the same APIs?

Are you sure they're not using Xwayland? That would explain how they achieve that. Although Firefox can also use gtk_application_inhibit which tdesktop can't being a Qt application...
