### ISSUE TITLE
When using pipewire backend with default audio sink, telegram-desktop should not configure target.object

### ISSUE THREAD

**Issue by amano-kenji** [telegramdesktop/tdesktop#26599]
### Steps to reproduce

1. Settings -> Notifications and Sounds -> Play sound
2. Pick `No sound` and then `Default`.

### Expected behaviour

A notification sound should be heard.

### Actual behaviour

If pipewire backend's default sink is null-sink, telegram-desktop sets `target.object` to the id of null-sink, thus pipewire stream.rules for assigning a different target.object to a stream that doesn't have target.object are ignored.

With openal's pulseaudio backend, target.object is not set. Thus, pipewire stream.rules can set target.object for streams that don't have target.object.

### Operating system

Gentoo Linux

### Version of Telegram Desktop

4.8.1

### Installation source

Other (unofficial) source

### Logs

With openal pipewire backend
```
$ env ALSOFT_LOGLEVEL=3 telegram-desktop
...
[ALSOFT] (II) Got default playback device "null-sink"
[ALSOFT] (II) Got default capture device "null-source"
...
[ALSOFT] (II) Opening default playback device
[ALSOFT] (II) Created device 0x7fe5edeff340, "null sink"
...
```
With openal pulse backend
```
$ env ALSOFT_LOGLEVEL=3 telegram-desktop
...
[ALSOFT] (II) Opening default playback device
[ALSOFT] (II) Key pulse/allow-moves not found
[ALSOFT] (II) Connecting to "(default)"
[ALSOFT] (II) Created device 0x7f103b2fff00, "default-sink"
...
```

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by amano-kenji** [comment]
I installed telegram-desktop from https://packages.gentoo.org/packages/net-im/telegram-desktop which builds telegram-desktop from this repository.

**Comment by amano-kenji** [comment]
This turns out to be an upstream issue.

https://github.com/kcat/openal-soft/issues/892
