### ISSUE TITLE
GNOME UI freezes/lags for 1-2s after opening Telegram

### ISSUE THREAD

**Issue by Andrew15-5** [telegramdesktop/tdesktop#26594]
### Steps to reproduce

1. Open Telegram via dash-to-dock (GNOME)

Notes:
- Sometimes you have to wait for about 8.5 s, and others it happens right after Telegram window appears.
- This behavior is not new, but I think it's at least 1-year-old or more. This means that it was also present in Ubuntu 20.04 and maybe even in 18.04 or 19.10.
- I also use beta versions (nothing it turned on).
- The binary is self updated (by Telegram Updater, I guess)
- Telegram is started and has icon in the tray.
- Opening via tray icon produces 0 logs and lags
- I don't think that I've touched this `.desktop` file, but maybe it has some issues.

<details><summary>.desktop file</summary>

```desktop
[Desktop Entry]
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/home/user/.local/telegram/telegram
Exec=/home/user/.local/telegram/telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
Actions=Quit;
SingleMainWindow=true
X-GNOME-UsesNotifications=true
X-GNOME-SingleWindow=true

[Desktop Action Quit]
Exec=/home/user/.local/telegram/telegram -quit
Name=Quit Telegram
Icon=application-exit
```

</details>

<details><summary>logs when opening Telegram window</summary>

`journalctl -f`:

```text
Jul 31 00:08:45 pop-os systemd[1871792]: Started Application launched by gnome-shell.
Jul 31 00:08:45 pop-os dbus-broker-launch[1871808]: Noticed file-system modification, trigger reload.
Jul 31 00:08:45 pop-os dbus-broker-launch[1871808]: Service file '/usr/share//dbus-1/services/sessioninstaller.service' is not named after the D-Bus name 'org.freedesktop.PackageKit'.
Jul 31 00:08:45 pop-os dbus-broker-launch[1871808]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored
Jul 31 00:08:45 pop-os dbus-broker-launch[1871808]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated and ignored
Jul 31 00:08:45 pop-os dbus-broker-launch[1871808]: AppArmor enabled, but not supported. Ignoring.
Jul 31 00:08:45 pop-os systemd[1871792]: Reloading D-Bus User Message Bus...
Jul 31 00:08:45 pop-os systemd[1871792]: Starting Tracker metadata extractor...
Jul 31 00:08:45 pop-os dbus-broker-launch[1871808]: Service file '/usr/share//dbus-1/services/sessioninstaller.service' is not named after the D-Bus name 'org.freedesktop.PackageKit'.
Jul 31 00:08:45 pop-os dbus-broker-launch[1871808]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored
Jul 31 00:08:45 pop-os dbus-broker-launch[1871808]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated and ignored
Jul 31 00:08:45 pop-os dbus-broker-launch[1871808]: AppArmor enabled, but not supported. Ignoring.
Jul 31 00:08:45 pop-os systemd[1871792]: Reloaded D-Bus User Message Bus.
Jul 31 00:08:45 pop-os org.telegram.desktop._4319c7a3da3aa27bb8f41b9b357672ec.desktop[3115428]: Could not parse file "/home/user/.local/share/applications/Man.desktop": Key file does not have group ?Desktop Entry?
Jul 31 00:08:45 pop-os systemd[1871792]: Started Tracker metadata extractor.
Jul 31 00:08:46 pop-os org.telegram.desktop._4319c7a3da3aa27bb8f41b9b357672ec.desktop[3115415]: QApplication: invalid style override 'kvantum' passed, ignoring it.
Jul 31 00:08:46 pop-os org.telegram.desktop._4319c7a3da3aa27bb8f41b9b357672ec.desktop[3115415]:         Available styles: Windows, Fusion
```

</details>

<details><summary>logs during the lag</summary>

`journalctl -f`:

```text
Jul 31 00:08:53 pop-os gnome-shell[1872064]: Ignoring length property that isn't a number at line 4, col 20
```

or

```text
Jul 31 00:08:53 pop-os gnome-shell[1872064]: Ignoring length property that isn't a number at line 4, col 20
Jul 31 00:08:58 pop-os gnome-shell[1872064]: Ignoring length property that isn't a number at line 4, col 20
```

</details>

### Expected behaviour

No freezes or lags should be present.

### Actual behaviour

Some icons, whole dash-to-dock background flicks and whole UI except cursor freezes for 1–2 s. (Visually evident during playback of a video.)

### Operating system

Pop!_OS 22.04, GNOME 42.5

### Version of Telegram Desktop

4.8.10

### Installation source

Static binary from official website

### Logs

```text
Nothing new appear in logs.
```

**Comment by Andrew15-5** [comment]
Since video playback stutters during the 1-2 s lag in GNOME (on top of `Xorg`) it also affects playback of the video in Telegram app. User input/response/animation is of course also affected (inside Telegram), but there is no long animation to check, but still. If GNOME animations/video playback stutters, then every other app will too.

If it is a GNOME bug, then it is 1 more reason to hate GNOME (although I want to like it). I can also check COSMIC DE (on Rust) in the future and see if there will be any difference, but by that time I think I will be already running KDE.

**Comment by Andrew15-5** [comment]
Sorry for late reply, kinda busy. I've checked the issues that you've provided. I'm rocking `Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz` BTW.

#26343 — performance issues throughout the whole session, on Wayland (on AMD).

#26366 — issues with fractional scaling "view broken" (Plasma Wayland)

#26393 — Telegram 125% scaling with "Other (unofficial) source" (Wayland)

I have one single 1 s lag/stutter throughout whole GNOME DE (doesn't affect audio) (Xorg, Intel).

Since I did mention that this problem persists for a while now, I'm thinking that it have something to do with Intel/Ubuntu (-based)/GNOME.

I obviously better test this on a fresh OS, but I don't have time for this now. If I will, I'll share my results.

**Comment by ilya-fedin** [comment]
Maybe you have an HDD? I think there were multiple issues that tdesktop lags as hell and makes the system lag on HDD.

**Comment by Andrew15-5** [comment]
SSD all the way.

**Comment by ReillyBrogan** [comment]
I experienced this issue too on KDE Plasma Wayland with a LUKS-encrypted NVME SSD. The entire UI would freeze for a few seconds whenever Telegram was started. It seems to be some kind of resource contention issue between the DE threads drawing the UI and Telegram starting up, if I had to guess perhaps both are using /dev/random and it's running out of entropy? Complete shot in the dark, I'd need to profile it to see for sure.

**Comment by ilya-fedin** [comment]
> #26343 — performance issues throughout the whole session, on Wayland (on AMD)
> 
> #26366 — issues with fractional scaling "view broken" (Plasma Wayland)
> 
> #26393 — Telegram 125% scaling with "Other (unofficial) source" (Wayland)

all of them are closed now is this still happening?

**Comment by Andrew15-5** [comment]
> is this still happening?

You know what? No, but I'm using a different machine with the same OS and DE. Huh, I haven't even noticed that there is no lag (probably **because** there is no lag).

I can't test the other machine as it is broken and require repair.

**Comment by ilya-fedin** [comment]
ok, you can open a new issue if you will encounter it again

**Comment by Andrew15-5** [comment]
Isn't reopening this issue will make more sense? If I will be able to revive the old machine and it will still have this problem?

**Comment by ilya-fedin** [comment]
No one looks into old closed issues. And there's locking mechanism to prevent people to write into old closed issues that won't be noticed anyway.
