### ISSUE TITLE
Video playback speed doesn't work

### ISSUE THREAD

**Issue by dedpawl** [telegramdesktop/tdesktop#26593]
### Steps to reproduce

1. Set video playback speed at 2x
2. Close the video
3. Open the same video or any other video again
4. UI element shows 2x speed, but video and audio are at 1x speed

### Expected behaviour

All the videos should default to the last playback speed that was chosen

### Actual behaviour

UI element shows the last playback speed that was chosen, but it's being actually played on 1x after closing the video where you chose custom playback speed

### Operating system

Windows 11

### Version of Telegram Desktop

4.8.10 x64

### Installation source

Static binary from official website

**Comment by badcodelab** [comment]
confirm same issue on windows 10
previous build v4.8.9 doesn't have this bug

**Comment by d-u-a-l** [comment]
I confirm. Rollback to prev version helped

**Comment by Gigachhad** [comment]
Seems like the latest version has this issue and I am also facing it. Reverting back to older versions fixes the issue (Windows 11)

**Comment by VetaLioSTV** [comment]
> I confirm. Playback speed resets to 1 even after seeking. Rollback to prev version helped. Win 10

i have the same, latest client, video speed 2x and when you scroll it resets to 1x, but still shows as 2x.

**Comment by LtPatterson** [comment]
Same here. Reverted to previous version to fix.

**Comment by Aokromes** [comment]
test https://github.com/telegramdesktop/tdesktop/releases/tag/v4.8.11

**Comment by LtPatterson** [comment]
Beta fixes this issue for me, need additional validators to confirm.

**Comment by badcodelab** [comment]
confirm v4.8.11 fixed the issue for me, x64, win10

**Comment by Black-Semargl** [comment]
confirm v4.8.11 bug fixed, ubuntu 20.04 (x64)

**Comment by dedpawl** [comment]
Yep, issue is fixed for me too
