### ISSUE TITLE
Shift+F10 no longer working when media (video or photo) is being displayed.

### ISSUE THREAD

**Issue by gxrxrdx** [telegramdesktop/tdesktop#26595]
### Steps to reproduce

1. enter any telegram group with images.
2. press on the image to show it enlarged.
3. press shift+F10, nothing happens

### Expected behaviour

the contextual menu is expected to be displayed, just the same as right clicking using the mouse buttons.

### Actual behaviour

when pressing Shift + F10 nothing happens,  this worked in previous desktop telegram versions.

### Operating system

windows 11 pro

### Version of Telegram Desktop

4.8.9 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Thanks. I'll fix that for the next version.

**Comment by gxrxrdx** [comment]
thanks to you! awesome work
