### ISSUE TITLE
Set nickname for channels

### ISSUE THREAD

**Issue by cknood** [telegramdesktop/tdesktop#26604]
### Is your feature request related to a problem?

I'm based English user, I join to multiple channels in other languages. Ex. Arabic, Thai, Rus, etc. I don't understand the channel's name because their name in another language, I have to open every channel to see the contents to know what is the channel.

### Describe the solution you'd like

I hope i can right click on a channel's name and set nickname for it. Ex. ‬A -> nickname(A)

### Describe alternatives you've considered

No other alternatives choice

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
