### ISSUE TITLE
App freezes when switching to "shuffle"

### ISSUE THREAD

**Issue by TarasovSavely** [telegramdesktop/tdesktop#26606]
### Steps to reproduce

1. Open Telegram Desktop
2. Start any audio
3. Switch at the top to "shuffle"

### Expected behaviour

Audio will start playing randomly

### Actual behaviour

App freezes

### Operating system

Fedora Linux 38 (Workstation Edition) 64-bit

### Version of Telegram Desktop

4.8.10

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Please do `kill -ABRT $TELEGRAM_PID` in the frozen state in order to turn the freeze into a crash and do the regular crash reporting actions with crash ID as explained in the issue template.

**Comment by TarasovSavely** [comment]
Ok, I do it: Crash ID: 336a5809-748b-4827-dec4e4ad-856aa317

**Comment by brxoo** [comment]
The same bug is happening to me.
Crash ID: 06b39639-1bd0-43d5-1c14d2ac-d15980a2

**Comment by pmoieni** [comment]
same issue here on Fedora 38 workstation, opensuse tumbleweed and leap, fedora 38 kde both flatpak and official binary

**Comment by AliTajari** [comment]
i have the same problem on ubuntu 22.04 :-(

**Comment by TarasovSavely** [comment]
Now my Telegram Desktop has been updated to 4.8.11 beta. In this version, the "Steps to reproduce" do not work. I will check the function and write

**Comment by TarasovSavely** [comment]
Everything works correctly on this version
