### ISSUE TITLE
Scaling issue with 2 monitors 

### ISSUE THREAD

**Issue by reizy** [telegramdesktop/tdesktop#26603]
### Steps to reproduce

Use 2 monitors with "extend" mode
Monitor with number 1 in Windows (TV) have scale 225%
Monitor with number 2 in Windows (main monitor) have scale 100%
Telegram app is displayed on Monitor 2.

### Expected behaviour

Telegram app uses the scaling of the monitor on which it is displayed (100% from Monitor 2 in my case)

### Actual behaviour

Telegram app is displayed on Monitor 2, but uses scale 225% from Monitor 1. 

### Operating system

Windows 10 x64

### Version of Telegram Desktop

4.8.10 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#1121

**Comment by john-preston** [comment]
Strange, it should scale twice as big on monitor 1 that it is on monitor 2 in that case.

**Comment by john-preston** [comment]
So, not exactly 1x -> 2.25x, but 1x -> 2x.

**Comment by ilya-fedin** [comment]
The person should have been attach a log as the issue template suggests, apparently

**Comment by reizy** [comment]
Issue was fixed by https://github.com/telegramdesktop/tdesktop/issues/1121#issuecomment-1585689315
