### ISSUE TITLE
Can't add newly-created bot as member or admin to chat (of which I'm admin)

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#26611]
### Steps to reproduce

1. Create a bot using Botfather, let's say the name is "My Bot" and the username is @myxxxxxxxbot
2. Go to a group chat where you are admin
3. go to admins, add an admin, and try to add the bot.
4. As that fails, try to add the bot as member (so you can then promote it to admin)

### Expected behaviour

Should allow you to do both

### Actual behaviour

When searching for the member or admin to add, when you type the name or username of the bot it never shows up in the rerults, and even if you type the exact username, it won't let you.

### Operating system

Manjaro Linux

### Version of Telegram Desktop

4.8.4

### Installation source

Other (unofficial) source

**Comment by john-preston** [comment]
Strange, works for me:

![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/b080faa1-28d9-4cfb-8f39-875760ac9437)

I'm creator of this group. Does it work for you if you're a creator?

**Comment by php4fan** [comment]
I was the creator too.

Actually, this worked for me after a few minutes. Note that the issue happened just seconds/minutes after creating the bot. I guess some information had to "propagate" (I guess the server you are "talking to" when creating the bot via BotFather, and the server from which you get search results when adding an admin/member to a chat, are not the same physical machine).

Still there's no excuse for this, as I had created the bot from the same device from which I was attempting to add the bot to the chat, and I had gotten a confirmation message from BotFather. So, the app has at the very least the theoretical ability to add the bot to the search results.
