### ISSUE TITLE
[feature-request] Debounce notifications for same chat

### ISSUE THREAD

**Issue by AoDev** [telegramdesktop/tdesktop#26612]
### Is your feature request related to a problem?

Sometimes, people send a lot of small sentences one after another. That leads to a lot of notifications sounds and vibrations. That gets annoying pretty quickly.

### Describe the solution you'd like

I'd like the app to be smart enough to not notify / ring / vibrate on every message received if they come one after another quickly. 

Ideally, a "debouncing" option can be turned on and a delay specified with a sane default.

For example, don't notify if the last message of the same chat was received 10 seconds ago. (`10 seconds` can be changed by the user.)

### Describe alternatives you've considered

Aside from turning off vibration and looking for less bothering sounds, there is no solution really.

**Comment by ilya-fedin** [comment]
#429
