### ISSUE TITLE
"Auto" or Any Direct3D Variant Selected in ANGLE graphics backend Breaks Image/Video Framing

### ISSUE THREAD

**Issue by DodgeDeBoulet** [telegramdesktop/tdesktop#26616]
### Steps to reproduce

1. In Settings, select "Auto" or any Direct3D variant in Settings | Advanced | ANGLE graphics backend
2. Click on an image or video received or sent in a message

Graphics adapter is an nVidia RTX A3000 GPU using driver version 31.0.15.2890, connected to dual 32" 4K displays via Thunderbolt.

### Expected behaviour

The image or video should be centered in the viewer frame and scale appropriately when directed

### Actual behaviour

The image is not positioned properly nor scaled to fit the transparent window that represents its intended location

### Operating system

Windows 11 22H2 build 22621.1992

### Version of Telegram Desktop

4.8.10 x64

### Installation source

Microsoft Store

**Comment by DodgeDeBoulet** [comment]
Examples

OpenGL/None:
![image](https://github.com/telegramdesktop/tdesktop/assets/4532366/3f16c27d-aeee-4c99-a75e-7e8d4c505bd8)

Auto/Direct3D Variants:
![image](https://github.com/telegramdesktop/tdesktop/assets/4532366/4e873b87-3c4b-4b58-928e-08b6581ee5f3)

Auto/Direct3D Variants Zoomed:
![image](https://github.com/telegramdesktop/tdesktop/assets/4532366/2cf7c277-d17e-4055-9ef8-480a32d73a00)

**Comment by Aokromes** [comment]
be sure you don't have experimental setting enable precise high dpi scalling enable.
