### ISSUE TITLE
Upload file always failed

### ISSUE THREAD

**Issue by sunericwong** [telegramdesktop/tdesktop#26614]
### Steps to reproduce

1. select some files and upload 
2. waiting for finish
3. failed and upload the next file

Finally, cannot upload the grouped files.

![image](https://github.com/telegramdesktop/tdesktop/assets/128568193/406bc057-31a5-4507-b3eb-fd29f99f5016)

### Expected behaviour

Uploaded all files.

### Actual behaviour

Stop upload and cannot retry. 

### Operating system

Windows 10

### Version of Telegram Desktop

telegram desktop version 4.8.10 x64

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
works for me TM

**Comment by sunericwong** [comment]
> works for me TM

This problem occurs on yesterday.
I tried on my home and office desktop; both cannot upload files.  

I keep trying and 99% failed.
![image](https://github.com/telegramdesktop/tdesktop/assets/128568193/70728a21-b4b6-48ca-8c8f-b44c3be90827)

Does it relate to file size? File about 1.5GB

**Comment by NoodlesStamps** [comment]
I'm having the same problem, DC5 server.

**Comment by Aokromes** [comment]
> > works for me TM
> 
> This problem occurs on yesterday. I tried on my home and office desktop; both cannot upload files.
> 
> I keep trying and 99% failed. ![image](https://user-images.githubusercontent.com/128568193/258402435-70728a21-b4b6-48ca-8c8f-b44c3be90827.png)
> 
> Does it relate to file size? File about 1.5GB

i just have upload 2 near 2GB files.

**Comment by 23rd** [comment]
Can you tell us how long an uploading takes time? If your upload speed is veeery slow than the first parts of your file are can be removed by server.

**Comment by Aokromes** [comment]
https://i.imgur.com/X3WPwAZ.png and near 4GB file.

**Comment by Karmylr** [comment]
Maybe something wrong with telegram data center?

**Comment by sunericwong** [comment]
It can complete upload files now.
