### ISSUE TITLE
Support geo: URIs

### ISSUE THREAD

**Issue by bam80** [telegramdesktop/tdesktop#26615]
### Is your feature request related to a problem?

geo: URIs are not handled. That means that map applications that want to share a location in an application independent way can't. To be fair, so far only Matrix/Element Android seems to handle this properly.

Originally reported here:
https://bugs.telegram.org/c/9780

### Describe the solution you'd like

> Supporting automatic highlighting/converting of geo:12.3456,-23.4567 text into a clickable link in the message text like <a href="geo:12.3456,-23.4567">geo:12.3456,-23.4567</a> would be really awesome! Users share geo links from many map apps, see the full list here: https://wiki.openstreetmap.org/wiki/Geo_URI_scheme

by @biodranik

### Describe alternatives you've considered

NA

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
