### ISSUE TITLE
Past problem

### ISSUE THREAD

**Issue by taojet** [telegramdesktop/tdesktop#26625]
### Steps to reproduce

I just copy text or image and try to past it on input message inbox. 
It is not working sometimes. 

After this Past item in popap menu disabled. 

### Expected behaviour

copy & past working

### Actual behaviour

past not working

### Operating system

Ubuntu 22.04.2 LTS, Gnome 42.5 

### Version of Telegram Desktop

Telegram Desktop 4.8.4

### Installation source

Static binary from official website

**Comment by roomonmoon** [comment]
Try to update to latest version

**Comment by taojet** [comment]
I have v4.8.10 ver. 

Seems it is latest

**Comment by ilya-fedin** [comment]
Probably worth to close as a dup of #26826 given that the new one has more details
