### ISSUE TITLE
Cannot login: Telegram sends to non-existent "other device" after its appdata is deleted instead of SMS

### ISSUE THREAD

**Issue by guoyiz23** [telegramdesktop/tdesktop#26626]
### Steps to reproduce

1. Delete all Telegram app data
2. Try to log in again to Telegram

### Expected behaviour

Send an SMS

### Actual behaviour

Sends to non-existent "other device". This happens on Android.

Support also has not responded for over a week.

### Operating system

Windows 11

### Version of Telegram Desktop

tsetup-x64.4.8.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop is prohibited to send SMS by the server, you have to use official mobile apps...

**Comment by guoyiz23** [comment]
> tdesktop is prohibited to send SMS by the server, you have to use official mobile apps...

What do you mean by **official mobile app**? I did use it on Android and when I click on "send code", it sends to "other device" (non-existent) as opposed to an SMS. Also, both https://telegram.org/support and sms@telegram.org have not responded to me for over two weeks.

Thus, much appreciated if a developer of Telegram can get me in contact with one who can resolve this login issue.

And I believe it is fair to regard this as a bug. Maybe, Telegram can deregister a device regarded as "logged in" if Telegram has not been accessed from it for some period of time, so that instead Telegram sends an SMS.

Thank you!

**Comment by ilya-fedin** [comment]
This is a purely client-side bug tracker, such a bug is applicable here.

**Comment by guoyiz23** [comment]
> This is a purely client-side community-maintained bug tracker, such a bug is not applicable here.

Understood. The thing is I have already personally contacted Telegram support over two channels. I also asked a friend to contact some Telegram support within Telegram. There are people in Telegram who I much want to contact. Again, suggestions on this would be much appreciated.

**Comment by guoyiz23** [comment]
I had filed an issue at https://github.com/TelegramOfficial/Support/issues which is the pertinent page, yet no response for 5 days, which of course disappoints me. Given all this, I certainly would not recommend this product to others; however, if someone can assist me with the log in process with the next few days, I would be willing to change my mind.

I have no ill intent at all; when filing this bug, I realized that if an according change was made, probably at least 100 if not over 1000 people later would not run into the same problem. It's not that uncommon for, say, Telegram appdata to be wiped out by a virus or hard drive break. And then, Telegram support is irresponsive (I saw that it is actually run the volunteers).

**Comment by guoyiz23** [comment]
I had also tried https://twitter.com/smstelegram ; again no response for like a week.

Online search does not find me any Telegram support phone number. I am very surprised that a product with, what, 800 million users does not even have a promptly responding support. I also do not rule out that the SMS is for some reason not going thru, but the screenshot of my issue does say, "sent code to another device", so I reasonably conclude that it very likely did not send the SMS.

**Comment by ilya-fedin** [comment]
> I had filed an issue at https://github.com/TelegramOfficial/Support/issues which is the pertinent page

This is a github organization made by a random person. I don't think there are appropriate official channels other than the support form on the website, sms@telegram.org and login@stel.com. If they don't answer then probably you're just out of luck...

**Comment by guoyiz23** [comment]
> > I had filed an issue at https://github.com/TelegramOfficial/Support/issues which is the pertinent page
> 
> This is a github organization made by a random person. I don't think there are appropriate official channels other than the support form on the website, [sms@telegram.org](mailto:sms@telegram.org) and [login@stel.com](mailto:login@stel.com). If they don't answer then probably you're just out of luck...

As for **out of luck**, I am still very disappointed at their irresponsiveness. [login@stel.com](mailto:login@stel.com) I learned from you and no response from them either. In any case, thank you much for taking time to respond to my requests on this matter.

Is there not any phone number I can call for this? Whoever can help me get logged in to Telegram via the right contacts or what not I would even be willing to give some monetary compensation. Also people here are welcome to email me at guoyiz at yandex.ru.

I wonder to what extent Telegram developer team is based in Russia (I do have some programming experience, and I would totally consider applying to make some contributions to the Telegram code base even). I have personally studied in a Russian university before and I am also on VK. As more a confirmation of the aforementioned Russian connection, here is a paper of mine on the arXiv: https://arxiv.org/pdf/2209.13798.pdf

**Comment by ilya-fedin** [comment]
btw personally when I had such a request on mobile, if I wait for some time, a 'Send SMS' button was appearing, isn't it like that for you?

**Comment by guoyiz23** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/126132649/32cf6c07-57fd-496e-ab0c-5f9dd38330f9)
And for me, it's sending to "other device" which does not exist. The screenshot says it all.

**Comment by ilya-fedin** [comment]
"Didn't get the code?"

**Comment by guoyiz23** [comment]
> "Didn't get the code?"

Yes, also nothing in my SMS. I presume Telegram misdetects some other device previously logged in the appdata of which was wiped out as still logged in.

**Comment by ilya-fedin** [comment]
You mean after pressing this button it says it has sent SMS but you got no SMS?

**Comment by guoyiz23** [comment]
> You mean after pressing this button it says it has sent SMS but you got no SMS?

No it only says "sent to other device". Never said sent to SMS, but I checked SMS anyway.

**Comment by ilya-fedin** [comment]
I don't quite understand, can you tell what happens when you press the "Didn't get the code?" button?

**Comment by guoyiz23** [comment]
> I don't quite understand, can you tell what happens when you press the "Didn't get the code?" button?

See screenshot below.

![image](https://github.com/telegramdesktop/tdesktop/assets/126132649/f8932cf4-e28e-400c-a7a4-a26cbf4c81d7)

**Comment by ilya-fedin** [comment]
Hm, ok, I thought it would get you to SMS code

**Comment by guoyiz23** [comment]
> Hm, ok, I thought it would get you to SMS code

Yes, that's what it should do. Thus, I feel like a bug request for this is fitting. In any case, thank you for your time. Of course, resolution of this would be much appreciated.

**Comment by ilya-fedin** [comment]
Well then report this for telegram android? Although you can't report for telegram android without a telegram account (either with in-app support or bugs.telegram.org).

I wonder where did you get telegram android from?

**Comment by guoyiz23** [comment]
> Well then report this for telegram android? Although you can't report for telegram android without a telegram account (either with in-app support or bugs.telegram.org).
> 
> I wonder where did you get telegram android from?

Some APK from online, I do not remember exactly where. And yes, can you report this for Telegram Android on my behalf. Surely, you can easily contact their developers, one of whom may be able to get me in touch with support. Thank you!

**Comment by ilya-fedin** [comment]
Well, I have no contact with Telegram Android developer, sorry. I guess this APK may be not official and only official mobile apps can get SMS...

**Comment by guoyiz23** [comment]
> Well, I have no contact with Telegram Android developer, sorry. I guess this APK may be not official and only official mobile apps can get SMS...

Given the firewall in China, it is difficult for me to download one from a web store. Installation of APK has more or less the same effect; the question is the APK version. In any case, I much believe the server side of Telegram misperceives my having another device logged in.

**Comment by Aokromes** [comment]
can you try downloading from https://telegram.org/android ?

**Comment by ilya-fedin** [comment]
> I much believe the server side of Telegram misperceives my having another device logged in.

When you're logging from an application restricted to get SMS (like tdesktop or unofficial mobile application), it will say that the code is sent to another device even if you have no other device and the server knows that. idk why it's made like that but it's made like that.

**Comment by guoyiz23** [comment]
> can you try downloading from https://telegram.org/android ?

Did that. It is indeed a different from version from that which I had installed, but same response.

**Comment by guoyiz23** [comment]
> > I much believe the server side of Telegram misperceives my having another device logged in.
> 
> When you're logging from an application restricted to get SMS (like tdesktop or unofficial mobile application), it will say that the code is sent to another device even if you have no other device and the server knows that. idk why it's made like that but it's made like that.

Yes, but it directly prompts me to "Check your Telegram messages". And before I do remember receiving verification code via other logged in device. Thus, I doubt that the SMS is not going through for some reason.

**Comment by ilya-fedin** [comment]
Have you tried asking for help the Twitter account?

**Comment by guoyiz23** [comment]
> Have you tried asking for help the Twitter account?

And they also do not respond.

**Comment by guoyiz23** [comment]
> Personally I'm scared to do this. Wouldn't be surprised if they block my account due to disturbing.

You mean block your Telegram account? Could we talk about this more privately over email or private message? My email is guoyiz at yandex.ru. Thank you!

**Comment by Aokromes** [comment]
> > can you try downloading from [telegram.org/android](https://telegram.org/android) ?
> 
> Did that. It is indeed a different from version from that which I had installed, but same response.

you have google play services on that phone?

**Comment by guoyiz23** [comment]
> > > can you try downloading from [telegram.org/android](https://telegram.org/android) ?
> > 
> > 
> > Did that. It is indeed a different from version from that which I had installed, but same response.
> 
> you have google play services on that phone?

No, and with the firewall in China, Google Play would be extremely inconvenient. Again, I welcome people here to send me email.

**Comment by john-preston** [comment]
@guoyiz23 I'm told that there was no email from guoyiz at yandex.ru to sms at telegram.org.

**Comment by guoyiz23** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/126132649/ebc00f71-878c-470b-a8ff-fb439b376051)
Certainly I sent it. Maybe it landed in its spam folder for some reason?

Thank you so much for response!

**Comment by guoyiz23** [comment]
@john-preston @ilya-fedin @Aokromes 
![image](https://github.com/telegramdesktop/tdesktop/assets/126132649/f169e33c-2b4b-4569-8d87-ffe853423a96)

Telegram Support got back to me! Thank you so much for taking the time to help me resolve this.

Part of me doubts how Google Play Services would be relevant to this, or maybe it is more that I am a bit unwilling to go thru the pain of installing it under the Chinese firewall.

https://forums.crackberry.com/showthread.php?t=1155015&s=&p=13268965&viewfull=1#post13268965

![image](https://github.com/telegramdesktop/tdesktop/assets/126132649/87d905e9-b5b8-4d93-8f94-345a2ba9c384)

I guess when filing a bug for this, I should be filing to the server side team. Then again, it seems like that code is proprietary and closed source, so I may kindly ask the people here to relay the message.

**Comment by guoyiz23** [comment]
I was able to log in again by asking someone I know to request code from a phone actually based in Russia (presumably with the Google Play Services installed). Among the sessions listed, the date is the day right after reinstallation of Windows. Also, it seems like if one deletes the app from mobile, the session actually persists, and the default duration of persistence is set for as high as 6 months.

@Aokromes @ilya-fedin @john-preston Thank you again for taking time to help me on this. I guess it indirectly led to its eventual resolution. Also, with some programming experience, I would consider the possibility of contributing to Telegram's development. People here are welcome to email me at guoyiz at yandex.ru

P.S. I do not see any way to configure in app an easier way to log in, such as via email confirmation code. So be it then.

**Comment by vanquocitc** [comment]
i got same issue. I reset my samsung phone without log out Telegram, now i cant receive verify code by SMS because Tele sent code to the Telegram app for my number on your other device.

**Comment by guoyiz23** [comment]
If you are in mainland China, try to have someone physically overseas request the SMS. You send the SMS to him, he uses it to log in, and then you request another code on your end that he can see and send to you.

**Comment by vanquocitc** [comment]
> If you are in mainland China, try to have someone physically overseas request the SMS. You send the SMS to him, he uses it to log in, and then you request another code on your end that he can see and send to you.

But i only using Tele on one phone, no change phone and number phone. Just hard reset and got this issue

**Comment by guoyiz23** [comment]
Yes, you will have to ask another person to log you in while physically abroad (my guess is that this is due to some Google Play Services issue, given that it is somewhat a pain to install it in China).

**Comment by Karine-W** [comment]
你可以尝试下载telegram x app，在其上可以通过短信验证码登入你的telegram账号。如此它便可以用来接收你登入普通telegram账号的验证码。

**Comment by errantmind** [comment]
Sadly, the requirement of Google Play Services means I can't use the app anymore as I will not install it. It didn't not require this before and worked fine on my phone, but one day I found it had logged me out and now there is this new requirement. Just wanted to add this is bad design to require Google Play Services. None of my other apps have a 'hard' requirement on this.

**Comment by chengwuooo** [comment]
> 你可以尝试下载telegram x app，在其上可以通过短信验证码登入你的telegram账号。如此它便可以用来接收你登入普通telegram账号的验证码。

万分感谢！

**Comment by john-preston** [comment]
@matheuswillder Yeah, but really this is a one time thing. If you have a valid session already you can login using codes received in that session without receiving SMS messages and in that case you don't need Google Play services.

**Comment by Gift-Huang** [comment]
> > 你可以尝试下载telegram x app，在其上可以通过短信验证码登入你的telegram账号。如此它便可以用来接收你登入普通telegram账号的验证码。
> 
> 万分感谢！

嘿，哥们，我看了这个问题下的所有讨论，并进行了尝试。
我下载了telegram x app也使用了虚拟机的方式安装，能够确定的事，使用完整Google服务的手机，会发送SMS，但是很奇怪，我使用国内的手机号码无法接收到验证码。
最惨的是，我之前的账号就是使用国内手机号码注册并使用的，因为一次重置手机导致我现在无法登入进去，使用telegram x app提示发送了验证码，但就是没有收到。
打电话给移动运营商，对方也说我并没有关闭境外的通道，我使用国外的手机号码在telegram x上是可以正常获取到短信的。

想请问下，你是用国内手机号码吗？有什么办法能够接受到短信吗？

**Comment by chengwuooo** [comment]
> > > 你可以尝试下载telegram x app，在其上可以通过短信验证码登入你的telegram账号。如此它便可以用来接收你登入普通telegram账号的验证码。
> > 
> > 
> > 万分感谢！
> 
> 嘿，哥们，我看了这个问题下的所有讨论，并进行了尝试。 我下载了telegram x app也使用了虚拟机的方式安装，能够确定的事，使用完整Google服务的手机，会发送SMS，但是很奇怪，我使用国内的手机号码无法接收到验证码。 最惨的是，我之前的账号就是使用国内手机号码注册并使用的，因为一次重置手机导致我现在无法登入进去，使用telegram x app提示发送了验证码，但就是没有收到。 打电话给移动运营商，对方也说我并没有关闭境外的通道，我使用国外的手机号码在telegram x上是可以正常获取到短信的。
> 
> 想请问下，你是用国内手机号码吗？有什么办法能够接受到短信吗？

很抱歉，我用的就是国内的手机号码，不能解决你的问题

**Comment by Gift-Huang** [comment]
> > > > 你可以尝试下载telegram x app，在其上可以通过短信验证码登入你的telegram账号。如此它便可以用来接收你登入普通telegram账号的验证码。
> > > 
> > > 
> > > 万分感谢！
> > 
> > 
> > 嘿，哥们，我看了这个问题下的所有讨论，并进行了尝试。 我下载了telegram x app也使用了虚拟机的方式安装，能够确定的事，使用完整Google服务的手机，会发送SMS，但是很奇怪，我使用国内的手机号码无法接收到验证码。 最惨的是，我之前的账号就是使用国内手机号码注册并使用的，因为一次重置手机导致我现在无法登入进去，使用telegram x app提示发送了验证码，但就是没有收到。 打电话给移动运营商，对方也说我并没有关闭境外的通道，我使用国外的手机号码在telegram x上是可以正常获取到短信的。
> > 想请问下，你是用国内手机号码吗？有什么办法能够接受到短信吗？
> 
> 很抱歉，我用的就是国内的手机号码，不能解决你的问题

感谢回复，我猜测可能是网络环境有关系，我会再次尝试，已经不能登入超过6个月了...

**Comment by Gift-Huang** [comment]
> > > > 你可以尝试下载telegram x app，在其上可以通过短信验证码登入你的telegram账号。这样就可以用来接收你登入普通telegram账号的验证码。
> > > 
> > > 
> > > 万分感谢！
> > 
> > 
> > 嘿，哥们，我看了这个问题下面的所有讨论，并进行了尝试。我下载了telegram x app也使用了虚拟机的方式安装，能够确定的事，使用完整Google服务的手机，会发送短信，但是很奇怪，我国内使用的手机号码无法接收到验证码。 最惨的是，我之前的账号就是使用国内手机号码注册并使用的，一次因为重置手机导致我现在无法登入进去，使用telegram x app提示发送了验证码，但就是没有收到。 打电话给移动运营商，对方也说我并没有关闭境外的通道，我用国外的手机号码在telegram x上是可以正常接收到短信的。
> > 想问下，你是用国内手机号码吗？有什么办法能够接受到短信吗？
> 
> 很抱歉，我用的是国内的手机号码，无法解决您的问题

嘿哥們，我進行了其他的嘗試，使用模擬器，包含完整的谷歌套件，能夠正常的訪問Google Play.包括使用不同的梯子跟節點，虛擬定位設置在美國，telegram x也是在Google Play上面下載的，但是仍然只有顯示發送SMS，但就是沒有收到。

不知道能不能請求幫個忙，在你的環境下，使用telegram x輸入我的手機號碼點擊發送，讓我看看我是否能夠收到短信？
如果你同意的話，麻煩你留下郵箱，我們郵件聯繫。

**Comment by chengwuooo** [comment]
2477376240

> > > > > 你可以尝试下载telegram x app，在其上可以通过短信验证码登入你的telegram账号。这样就可以用来接收你登入普通telegram账号的验证码。
> > > > 
> > > > 
> > > > 万分感谢！
> > > 
> > > 
> > > 嘿，哥们，我看了这个问题下面的所有讨论，并进行了尝试。我下载了telegram x app也使用了虚拟机的方式安装，能够确定的事，使用完整Google服务的手机，会发送短信，但是很奇怪，我国内使用的手机号码无法接收到验证码。 最惨的是，我之前的账号就是使用国内手机号码注册并使用的，一次因为重置手机导致我现在无法登入进去，使用telegram x app提示发送了验证码，但就是没有收到。 打电话给移动运营商，对方也说我并没有关闭境外的通道，我用国外的手机号码在telegram x上是可以正常接收到短信的。
> > > 想问下，你是用国内手机号码吗？有什么办法能够接受到短信吗？
> > 
> > 
> > 很抱歉，我用的是国内的手机号码，无法解决您的问题
> 
> 嘿哥們，我進行了其他的嘗試，使用模擬器，包含完整的谷歌套件，能夠正常的訪問Google Play.包括使用不同的梯子跟節點，虛擬定位設置在美國，telegram x也是在Google Play上面下載的，但是仍然只有顯示發送SMS，但就是沒有收到。
> 
> 不知道能不能請求幫個忙，在你的環境下，使用telegram x輸入我的手機號碼點擊發送，讓我看看我是否能夠收到短信？ 如果你同意的話，麻煩你留下郵箱，我們郵件聯繫。

2477376240@qq.com

**Comment by wangyingkuan** [comment]
Hello, I have also encountered the same problem. After trying to search, I found a solution, which is to download Telegram x. He can directly send SMS, and then use him to accept the official code, so that he can log in to the official app


你好，我也遇到了同样的问题，在尝试搜索后得到了解决方案，就是下载telegram x,他可以直接发sms，然后通过他来接受官方发的code，就可以登录官方app

**Comment by Gift-Huang** [comment]
> 2477376240
> 
> > > > > > 你可以尝试下载telegram x app，在其上可以通过短信验证码登入你的telegram账号。这样就可以用来接收你登入普通telegram账号的验证码。
> > > > > 
> > > > > 
> > > > > 万分感谢！
> > > > 
> > > > 
> > > > 嘿，哥们，我看了这个问题下面的所有讨论，并进行了尝试。我下载了telegram x app也使用了虚拟机的方式安装，能够确定的事，使用完整Google服务的手机，会发送短信，但是很奇怪，我国内使用的手机号码无法接收到验证码。 最惨的是，我之前的账号就是使用国内手机号码注册并使用的，一次因为重置手机导致我现在无法登入进去，使用telegram x app提示发送了验证码，但就是没有收到。 打电话给移动运营商，对方也说我并没有关闭境外的通道，我用国外的手机号码在telegram x上是可以正常接收到短信的。
> > > > 想问下，你是用国内手机号码吗？有什么办法能够接受到短信吗？
> > > 
> > > 
> > > 很抱歉，我用的是国内的手机号码，无法解决您的问题
> > 
> > 
> > 嘿哥們，我進行了其他的嘗試，使用模擬器，包含完整的谷歌套件，能夠正常的訪問Google Play.包括使用不同的梯子跟節點，虛擬定位設置在美國，telegram x也是在Google Play上面下載的，但是仍然只有顯示發送SMS，但就是沒有收到。
> > 不知道能不能請求幫個忙，在你的環境下，使用telegram x輸入我的手機號碼點擊發送，讓我看看我是否能夠收到短信？ 如果你同意的話，麻煩你留下郵箱，我們郵件聯繫。
> 
> [2477376240@qq.com](mailto:2477376240@qq.com)

感謝，添加了你的QQ。

**Comment by Gift-Huang** [comment]
> Hello, I have also encountered the same problem. After trying to search, I found a solution, which is to download Telegram x. He can directly send SMS, and then use him to accept the official code, so that he can log in to the official app
> 
> 你好，我也遇到了同样的问题，在尝试搜索后得到了解决方案，就是下载telegram x,他可以直接发sms，然后通过他来接受官方发的code，就可以登录官方app

我也嘗試了，但是我周邊幾個人的號碼，都沒有接收到來自telegram x的短信，移動、聯通、電信都試過了，aOS\iOS都試了，為了確保不是安裝包的問題，還特地用了新加坡的號碼，是可以收到SMS的

**Comment by wangyingkuan** [comment]
> > Hello, I have also encountered the same problem. After trying to search, I found a solution, which is to download Telegram x. He can directly send SMS, and then use him to accept the official code, so that he can log in to the official app
> > 你好，我也遇到了同样的问题，在尝试搜索后得到了解决方案，就是下载telegram x,他可以直接发sms，然后通过他来接受官方发的code，就可以登录官方app
> 
> 我也嘗試了，但是我周邊幾個人的號碼，都沒有接收到來自telegram x的短信，移動、聯通、電信都試過了，aOS\iOS都試了，為了確保不是安裝包的問題，還特地用了新加坡的號碼，是可以收到SMS的

你好，我使用的是国内移动的号码，可以收到短信，短信提示来着悠余只能，北京的号码，跟是否屏蔽境外短信无关。

**Comment by Gift-Huang** [comment]
> > > Hello, I have also encountered the same problem. After trying to search, I found a solution, which is to download Telegram x. He can directly send SMS, and then use him to accept the official code, so that he can log in to the official app
> > > 你好，我也遇到了同样的问题，在尝试搜索后得到了解决方案，就是下载telegram x,他可以直接发sms，然后通过他来接受官方发的code，就可以登录官方app
> > 
> > 
> > 我也嘗試了，但是我周邊幾個人的號碼，都沒有接收到來自telegram x的短信，移動、聯通、電信都試過了，aOS\iOS都試了，為了確保不是安裝包的問題，還特地用了新加坡的號碼，是可以收到SMS的
> 
> 你好，我使用的是国内移动的号码，可以收到短信，短信提示来着悠余只能，北京的号码，跟是否屏蔽境外短信无关。

你好，我也咨詢了运营商，确定了有开通接收境外短信，因为我之前注册时就是用手机号码短信直接注册的，只是卸载的时候忘记登出，现在搞得很麻烦，一直接收不到，也不知道会不会是地区问题

**Comment by wangyingkuan** [comment]
> > > > Hello, I have also encountered the same problem. After trying to search, I found a solution, which is to download Telegram x. He can directly send SMS, and then use him to accept the official code, so that he can log in to the official app
> > > > 你好，我也遇到了同样的问题，在尝试搜索后得到了解决方案，就是下载telegram x,他可以直接发sms，然后通过他来接受官方发的code，就可以登录官方app
> > > 
> > > 
> > > 我也嘗試了，但是我周邊幾個人的號碼，都沒有接收到來自telegram x的短信，移動、聯通、電信都試過了，aOS\iOS都試了，為了確保不是安裝包的問題，還特地用了新加坡的號碼，是可以收到SMS的
> > 
> > 
> > 你好，我使用的是国内移动的号码，可以收到短信，短信提示来着悠余只能，北京的号码，跟是否屏蔽境外短信无关。
> 
> 你好，我也咨詢了运营商，确定了有开通接收境外短信，因为我之前注册时就是用手机号码短信直接注册的，只是卸载的时候忘记登出，现在搞得很麻烦，一直接收不到，也不知道会不会是地区问题

我可以帮你试试用telegramx发你短信，加个qq试试？ 我的qq：2419128617

**Comment by xuan-ye-zi** [comment]
> 你可以尝试下载telegram x app，在其上可以通过短信验证码登入你的telegram账号。如此它便可以用来接收你登入普通telegram账号的验证码。

Thank you very much!This problem has been bothering me for months, so much so that I feel like crying now as I solve it！Thanks again for your help!

**Comment by allen747423517** [comment]
有同样的问题，我的账户也是登出后，无法有效接收到验证码，始终无法登录。

我测试了国内联通卡，发现北京地区，和其他地方卡有区别，地方卡是可以正常接收的，并且上面有朋友指出了发送验证码的公司是另外一家，我测试地方卡的验证码公司是<沐素智能>发送的。
而北京卡联通移动，都接收不到，以上均是用telegram X进行测试的，并也是在谷歌商店下载的正版。
看到上面有朋友使用X接收到验证码的朋友，也有没有接收到的，可以在这里分别报一下验证这个猜想。
如果确实是这样的话，很可能就是北京地区验证码被什么拦截了，如果搞清楚这个，不知能否绕过拦截，通过telegram X 接收到验证码。
Have the same problem, my account is also logged out, can not effectively receive the verification code, always unable to log in.

I tested the domestic Unicom card and found that the Beijing area is different from other local cards. The local card can be received normally, and a friend pointed out that the company sending the verification code is another company. The verification code company of the local card I tested was sent by < Mu Su Intelligence.
The Beijing card Unicom mobile, are not received, the above are tested with telegram X, and is also the legitimate version of the Google store download.
See the above friends who use X to receive the verification code, and whether they have received it, you can report here to verify this conjecture.
If this is indeed the case, it is likely that the verification code in the Beijing area was intercepted by what, if we figure out this, we do not know whether we can bypass the interception and receive the verification code through telegram X.

**Comment by denglinfu** [comment]
> 有同样的问题，我的账户也是登出后，无法有效接收到验证码，始终无法登录。
> 
> 我测试了国内联通卡，发现北京地区，和其他地方卡有区别，地方卡是可以正常接收的，并且上面有朋友指出了发送验证码的公司是另外一家，我测试地方卡的验证码公司是<沐素智能>发送的。 而北京卡联通移动，都接收不到，以上均是用telegram X进行测试的，并也是在谷歌商店下载的正版。 看到上面有朋友使用X接收到验证码的朋友，也有没有接收到的，可以在这里分别报一下验证这个猜想。 如果确实是这样的话，很可能就是北京地区验证码被什么拦截了，如果搞清楚这个，不知能否绕过拦截，通过telegram X 接收到验证码。 Have the same problem, my account is also logged out, can not effectively receive the verification code, always unable to log in.
> 
> I tested the domestic Unicom card and found that the Beijing area is different from other local cards. The local card can be received normally, and a friend pointed out that the company sending the verification code is another company. The verification code company of the local card I tested was sent by < Mu Su Intelligence. The Beijing card Unicom mobile, are not received, the above are tested with telegram X, and is also the legitimate version of the Google store download. See the above friends who use X to receive the verification code, and whether they have received it, you can report here to verify this conjecture. If this is indeed the case, it is likely that the verification code in the Beijing area was intercepted by what, if we figure out this, we do not know whether we can bypass the interception and receive the verification code through telegram X.

北京联通卡，现在收不到验证码，不知道您这边是否已经收到呢？

**Comment by packpaul** [comment]
Signing in by using other (mobile) devices is a fuckingly annoying thing when you are not using OTHER devices for Telegram app. I don't use any smart phone so for me the only way to log in is via SMS. May I be hoping you to enable back this feature at some point in the future?

**Comment by Aokromes** [comment]
> Signing in by using other (mobile) devices is a fuckingly annoying thing when you are not using OTHER devices for Telegram app. I don't use any smart phone so for me the only way to log in is via SMS. May I be hoping you to enable back this feature at some point in the future?

no, it's telegram's way to cut bills. nothing writen here will make durov change of mind, because he doesn't reads this tracker.

**Comment by packpaul** [comment]
> > Signing in by using other (mobile) devices is a fuckingly annoying thing when you are not using OTHER devices for Telegram app. I don't use any smart phone so for me the only way to log in is via SMS. May I be hoping you to enable back this feature at some point in the future?
> 
> no, it's telegram's way to cut bills. nothing writen here will make durov change of mind, because he doesn't reads this tracker.

Wow I didn't think about bills! Дуров (Fooler in Russian) should have thought about this case when creating his stuff. Now I'm thinking how to remove Telegram out of my business, or is there a way for sending SMS from a business account, is there one?

**Comment by krodelabestiole** [comment]
This issue has been around for at least 3 years. I have 3 friends in my immediate network that has been running into this problem.
Steps to reproduce :
- use telegram only on a privacy friendly system such as grapheneOS or lineageOS.
- break you phone, loose it or get it stolen.

Then it's done. From my understanding you will have to wait 6 month for your non existent session to terminate (is that so&nbsp;?).
I wonder how anyone can think it would be more reliable or secure to send a login code to a stolen phone somewhere than to the owner's phone number...

I tried to help my friends with Kotatogram that strangely enough has more functionalities than the official desktop app and can help in case you don't have a smartphone, but I still have found no solution to help when telegram servers think for no reason that you have an opened session anywhere, and won't let you simply receive a code by SMS.

**Comment by ilya-fedin** [comment]
> but I still have found no solution to help when telegram servers think for no reason that you have an opened session anywhere, and won't let you simply receive a code by SMS.

I believe that's just a dummy error code used for the situation when the server doesn't think the client in question is allowed to receive SMS. You can't do any other thing than getting an Android phone with GAPPS.
