### ISSUE TITLE
Autoupdate does not disable even when option is disabled

### ISSUE THREAD

**Issue by LtPatterson** [telegramdesktop/tdesktop#26624]
### Steps to reproduce

Run telegram
Disable autoupdate
Restart
Telegram will be updated even when not enabled.

### Expected behaviour

Should disable autoupdates when that option is selected.

### Actual behaviour

Autoupdate remains enabled regardless and program receives updates 

### Operating system

Windows 10 x64

### Version of Telegram Desktop

64.4.8.8

### Installation source

Static binary from official website

**Comment by LtPatterson** [comment]
My version was 64.4.8.8 but it always gets updated to the latest version which has bugs related to video playback speed not staying what the user selects.

**Comment by ilya-fedin** [comment]
Are you sure you're using tdesktop? It has no versions starting with 64.

**Comment by LtPatterson** [comment]
Typo on my end with x64. Version is 4.8.8 and up that has the playback issue and I've solved by turning off Internet during install to prevent auto update even when you disable that in settings. The program fetches the download package the instant telegram starts before a user can access the settings to disable auto update.

**Comment by nyakze** [comment]
It does download newer version on the first launch before you are able to disable the auto-update, you are correct. The other solution would be, after disabling auto-update, to delete an update from Telegram directory, it would stop it from updating.
