### ISSUE TITLE
[Issue] telegram.me links wrong behaviour

### ISSUE THREAD

**Issue by FabianPastor** [telegramdesktop/tdesktop#2662]
### Steps to reproduce
1. Write down telegram.me/someusername?domain=somebot&start=something
2.  OR Write down telegram.me/someusername?domain=somechannel&post=somepostnumber
3.  Send the message and click over the link.

### Expected behaviour
The arguments should be ignored and go to the account `someusername` like in Telegram Android App.

### Actual behaviour
The arguments are evaluated and instead of going to `someusername` it goes to `somebot` if it's the first link or to `somechannel` if it's a username of a channel.

### Configuration
**Operating system:** Debian 8

**Version of Telegram Desktop:** 0.10.19 alpha

**Comment by john-preston** [comment]
@FabianPastor Why write such links in the first place?

**Comment by FabianPastor** [comment]
That is not my business. 
I have no idea if someone can make profit of them (like showing an account image and bio and sending them to another channel or a bot ).
I just know that the behaviour is diferent on Android app and tdesktop. 
It's up to you fix it or let it be.

**Comment by john-preston** [comment]
@FabianPastor Ok, thanks for the report.
