### ISSUE TITLE
Excude archived chats from Unread folder

### ISSUE THREAD

**Issue by dsamersoff** [telegramdesktop/tdesktop#26636]
### Steps to reproduce

Mute some chat
Archive some chat
Wait until someone send a message to this chat

### Expected behaviour

The chat doesn't appear in both **All Chats** and **Unread** folders

### Actual behaviour

The chat doesn't appear in **All Chats** folder but **appears** in **Unread** folder

### Operating system

Windows 10

### Version of Telegram Desktop

v4.8.10 x64

### Installation source

Static binary from official website

**Comment by vonDubenshire** [comment]
I believe this has always happened -- in the Notification settings there is this option:

![image](https://github.com/telegramdesktop/tdesktop/assets/40748193/29927545-87cb-4aa9-808d-f5ce116d2451)

The "ALL UNREAD" includes muted chats, and always has, on mobile and desktop. 



If this wasn't what happened before lemme know

**Comment by vonDubenshire** [comment]
also, I forget that we can check https://bugs.telegram.org/?tag_ids=4&type=issues&sort=time for Desktop stuff too

**Comment by vonDubenshire** [comment]
Got it - I forgot the "Unread" folder existed on mobile and was a true "folder"!  I never used it.

Did it previously only show the Unread that was not archived?

**Comment by john-preston** [comment]
@dsamersoff You can edit the folder and decide whether it includes archived chats or not:

![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/7c80ac69-0b1c-4cba-bb9c-79e6cb0c74c5)

If your "Unread" chat has only first one ("Read") exclusion checked, then you'll get archived unread chats in that folder, in other case you won't.

**Comment by john-preston** [comment]
Be aware that if you choose to include some specific chats (selecting them in "Include Chats" section), not chat categories (like Channels, Groups, Bots), then they'll always appear in that folder, no matter if they fall under exclusion conditions (Muted / Read / Archived) or not.

**Comment by dsamersoff** [comment]
> @dsamersoff You can edit the folder and decide whether it includes archived chats or not:

Thank you! It works. 

I'll close the bug
