### ISSUE TITLE
Enlarged image attachments don't deal well with scaled+unscaled monitor combo on Windows

### ISSUE THREAD

**Issue by Coffeeling** [telegramdesktop/tdesktop#26638]
### Steps to reproduce

1. Install Telegram on Win11. 
2. Set 1080p as main display, Windows scaling at 100%
3. Set another higher resolution monitor as the secondary display (Windows scaling >100%)
4. Click on an image attachment.

### Expected behaviour

Telegram opens a full-screen view of the image.

### Actual behaviour

If Telegram is on the main display, it works as expected: Image opened and scaled to fullscreen, with rest of the screen shadowed.

If Telegram is on the secondary display, Telegram reserves the proper amount of space at the center of the screen and shadows the other parts as expected. The image isn't shown in full, however. The top part is not rendered, and Telegram shows the unshadowed screen in the space where the unrendered part of the image attachment should be.

### Operating system

Win11, 22H2

### Version of Telegram Desktop

4.8.10 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Provide a screenshot of the issue, logs as described in the issue template and a screenshot of "experimental settings" menu

**Comment by Coffeeling** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/54371213/aca90591-7d76-4ff9-a10c-602cc5f6756e)

**Experimental Settings**
![image](https://github.com/telegramdesktop/tdesktop/assets/54371213/dc93c56a-9ed1-4789-9c66-3305c8114be0)
Everything else is **Off**.

**Comment by ilya-fedin** [comment]
It's thits option. It's experimental for a reason.

**Comment by ilya-fedin** [comment]
#26616
