### ISSUE TITLE
"Info: runtime org.gtk.Gtk3theme.Breeze-Dark branch 3.22 is end-of-life"

### ISSUE THREAD

**Issue by kanansnote** [telegramdesktop/tdesktop#26630]
### Steps to reproduce

1. Having Breeze Dark theme [GTK 2/3]
2. Opening terminal and trying to update.
3. Acknowledging the error message given in "Actual Behavior" section.

### Expected behaviour

There should be no error messages when doing updates.

### Actual behaviour

When I try to do updates via terminal, I see this message appearing:
` This theme has been replaced by org.gtk.Gtk3theme.Breeze, see README for workaround on using system color schemes. https://github.com/flathub/org.gtk.Gtk3theme.Breeze#workarounds
Info: applications using this extension:
   org.mozilla.firefox, org.telegram.desktop, com.github.tchx84.Flatseal
` (ignore the other ones that doesn't relate to yours).

### Operating system

Debian 12, GNOME 43.6

### Version of Telegram Desktop

4.8.10

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
idk why flatpak says that but tdesktop doesn't use gtk theme, tdesktop is a Qt application.
