### ISSUE TITLE
Can't view photo when stream is open

### ISSUE THREAD

**Issue by 0Z0SK0** [telegramdesktop/tdesktop#26645]
### Steps to reproduce

1. Open any foreign stream in channel
2. Go to profile of somebody, open avatar (profile photo)
3. You cant do second step

### Expected behaviour

Open Photo Preview Window

### Actual behaviour

Photo Preview Window cant open

### Operating system

Windows 11

### Version of Telegram Desktop

4.8.10 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I can't reproduce. Or I didn't understand.

I found a channel with a livestream active. I've opened this livestream, video started playing in the livestream viewer.

I switched to a chat with a contact of mine, opened his profile and clicked on the userpic. It opened in the fullscreen viewer fine.
