### ISSUE TITLE
can't compile tdx on Arch with Docker, submitted here cause tdx repo closed the issue tracker

### ISSUE THREAD

**Issue by k1gen** [telegramdesktop/tdesktop#26647]
### Steps to reproduce

1. `mkdir ~/tbuild && cd ~/tbuild`
2. `git clone --recursive https://github.com/telegramdesktop/tdx.git`
3. wait for `./tdx/Telegram/build/prepare/linux.sh` to complete
4. `docker run --rm -it -v $PWD:/usr/src/tdesktop tdx:centos_env /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh -D TDESKTOP_API_ID= -D TDESKTOP_API_HASH=`
5. get this: https://pastebin.com/rr71JYeP

### Expected behaviour

docker should exit with 0

### Actual behaviour

```
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: Telegram/CMakeFiles/lib_ffmpeg.dir/Release/SourceFiles/ffmpeg/ffmpeg_utility.cpp.o: in function `FFmpeg::MakeCodecPointer(FFmpeg::CodecDescriptor)':
ffmpeg_utility.cpp:(.text+0x20ab): undefined reference to `av_opt_set(void*, char const*, char const*, int)'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: ffmpeg_utility.cpp:(.text+0x20c1): undefined reference to `av_opt_set_int(void*, char const*, long, int)'
collect2: error: ld returned 1 exit status
```

### Operating system

Arch Linux x86_64, Docker 24.0.5

### Version of Telegram Desktop

https://github.com/telegramdesktop/tdx/tree/tdx

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
This sounds like you have pulled new changes but forgot to update sumbodules

**Comment by john-preston** [comment]
Sad.. I built it successfully last time I tried (on 4.8.9 version), I wonder if it'll build fine on the next release. I don't know how the ffmpeg linking was broken, nobody touched it for quite some time.

**Comment by ilya-fedin** [comment]
I can also say it has no sense from the log. The functions is from libavutil, -lavutil is present and after the source file using the function. A mystery.

**Comment by ilya-fedin** [comment]
The only thing I can imagine is some hardware fault has happened and the library is miscompiled (if Dockerfile wasn't modified of course).

**Comment by k1gen** [comment]
I have also changed `Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp` and commented out `extern "C"` on lines 18 and 23, because I had a compilation issue, maybe this is related. I did no more changes to code or Dockerfile

**Comment by ilya-fedin** [comment]
yeah, it likely does C++ mangling given that you have deleted extern "C" and so searches for a completely different symbol.

**Comment by k1gen** [comment]
let me start from scratch, don't modify anything and get back to you, ok?

**Comment by ilya-fedin** [comment]
ok

**Comment by k1gen** [comment]
I'm back, here's docker build from scratch: https://pastebin.com/9YdTbEBn

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/commit/2e6abf0bede8b39c7c066b2db12d5f67b5ee8421

**Comment by k1gen** [comment]
@ilya-fedin: applied https://github.com/telegramdesktop/tdesktop/commit/2e6abf0bede8b39c7c066b2db12d5f67b5ee8421, have this now: https://pastebin.com/AERE216r

**Comment by john-preston** [comment]
@k1gen I don't think it is going to build. I rebase it on top of latest commits now to get a common docker image (that can be used for both TDesktop and Tdx), but I don't check and fix the build, so it's broken right now until I have time to work on it again.

**Comment by ilya-fedin** [comment]
> applied [2e6abf0](https://github.com/telegramdesktop/tdesktop/commit/2e6abf0bede8b39c7c066b2db12d5f67b5ee8421), have this now: https://pastebin.com/AERE216r

looks like the edit_privacy_box.cpp part of the commit has broke it, you have to apply only the ffmpeg_utility.cpp part

**Comment by k1gen** [comment]
@john-preston: I see. well, ping me if you need to test the docker build once you work on it, please

**Comment by k1gen** [comment]
should I build it with LTO? I remember I had issues with it

**Comment by ilya-fedin** [comment]
either build with LTO so it strips unused symbols or install glib 2.77

**Comment by k1gen** [comment]
it built fine with [this change](https://github.com/telegramdesktop/tdesktop/commit/2e6abf0bede8b39c7c066b2db12d5f67b5ee8421#diff-5c92ec8922273faadd6b185846ee285ff425c8d4048c3fe9ed554c107427673eR19) (just `ffmpeg_utility.cpp`) and this command: `docker run --rm -it -v $PWD:/usr/src/tdesktop -e DEBUG=1 tdx:centos_env /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh -D CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -D TDESKTOP_API_ID=<hidden> -D TDESKTOP_API_HASH=<hidden>`, took 1 hour and 34 minutes (on i5-8350U) and 17 gigs of ram. thanks @ilya-fedin for sending that commit and @john-preston for working on tdx!

screenshot: 
![image](https://github.com/telegramdesktop/tdesktop/assets/62500387/a467cd60-85dd-44cc-b94c-d8775505e506)
