### ISSUE TITLE
Telegram remove my contact label

### ISSUE THREAD

**Issue by mpz** [telegramdesktop/tdesktop#26657]
### Steps to reproduce

1. Select any user profile > Add to contact
2. fill any info on First Name 
3. Done button
4. wait for this user deletion and select user

### Expected behaviour

I can read my info that was filled on step 2

### Actual behaviour

My info is not avaible. On "Deleted Account" is present:

![image](https://github.com/telegramdesktop/tdesktop/assets/369032/c554c6f8-a9d3-4d8d-9b6e-18814773cd6b)

### Operating system

Ubuntu 22.04.2 LTS, Gnome 42.5 

### Version of Telegram Desktop

Telegram Desktop 4.8.4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
not a bug, intended. platform wide bugs / requests belongs to https://bugs.telegram.org/
