### ISSUE TITLE
Right-click menu on Windows tray icon with touch devices appearing wrong

### ISSUE THREAD

**Issue by michaelnakamura** [telegramdesktop/tdesktop#26655]
### Steps to reproduce

1. Leave mouse cursor somewhere random on screen, for example the top left quadrant of the screen;
2. Touch-right-click (hold your finger for 2 seconds) on Telegram tray icon;
3. Right click menu will appear where you left your mouse cursor;
4. Windows hides the mouse cursor when you start to touch, so the result is very weird. You touch the icon and the menu appers somewhere else.

### Expected behaviour

Right-click menu should appear on the tray icon

### Actual behaviour

Right-click menu appears where you left the mouse cursor on the screen. Windows 11 hides the cursor when touching, so the effect is weird, you touch the icon and the menu appers somewhere else.

### Operating system

Windows 11 - 22H2 - Build 22621.2134

### Version of Telegram Desktop

4.8.10 x64

### Installation source

Microsoft Store

**Comment by ilya-fedin** [comment]
Do you mean the system menu? If yes, it's a Windows bug, tdesktop can't control it.

**Comment by michaelnakamura** [comment]
I mean this right-click menu here:
![1](https://github.com/telegramdesktop/tdesktop/assets/10209108/8fc37837-cc51-423d-9ab3-cb03cdcc45a6)


Here I left the mouse cursor at the middle of my desktop then I touch-right-clicked the taskbar icon:
![2](https://github.com/telegramdesktop/tdesktop/assets/10209108/aa61f4d6-24cc-4b5c-9a77-fb516a44d05b)

Other apps like Steam and Onedrive works perfectly.

**Comment by ilya-fedin** [comment]
Ah, you mean tray icon, not taskbar icon. Can you fix the issue title?

**Comment by michaelnakamura** [comment]
Yes! Sorry for the mistake.

**Comment by john-preston** [comment]
Thanks for your report!
