### ISSUE TITLE
New titlebar has 1px gap for window buttons

### ISSUE THREAD

**Issue by PeterNjeim** [telegramdesktop/tdesktop#26659]
Same bug was introduced last year: https://github.com/telegramdesktop/tdesktop/issues/23933. It was resolved but has now been reintroduced.

### Steps to reproduce

1. Bring Telegram window to the top of the screen in windowed mode
2. Try to click close, minimize, or maximize buttons while the mouse cursor is at the very top pixel

### Expected behaviour

It should activate the buttons. This is a problem for me since I keep my Telegram window on the right side of the screen, and can easily close it by putting my mouse in the top right corner, no precision necessary. After the 4.9 update, the titlebar has changed and introduced this bug. This makes it quite difficult to close Telegram as almost every window for every app I can just go to the top right corner to close it, but with 4.9, Telegram only has this feature in maximized mode.

### Actual behaviour

Nothing happens, you need to move the cursor one pixel down to press the buttons

### Operating system

Windows 11

### Version of Telegram Desktop

4.9 x64

### Installation source

Static binary from official website

**Comment by PeterNjeim** [comment]
It looks like this: 
![image](https://user-images.githubusercontent.com/26418974/150301823-01d0772e-320f-496e-bdd2-f9e00f0238de.png)

Snapping does make it work, but I can't do that since it doesn't preserve the position when I close and open it (which I do frequently), as Windows handles snapped windows very oddly. What I do is resize the window by dragging the bottom right corner of Telegram to the bottom of the desktop (to the taskbar), and wiggle it left and right repeatedly until the window becomes the full height of the desktop, but without actually triggering the actual snap. Then I make the window the minimum width, and use mouse keys to drag it perfectly to the right edge of my screen. This way, it preserves its location. 

https://user-images.githubusercontent.com/26418974/150313617-8300e110-cfa4-4e7a-8255-729ec2d98d7e.mp4

_Originally posted by @PeterNjeim in https://github.com/telegramdesktop/tdesktop/issues/23933#issuecomment-1017293222_

**Comment by ilya-fedin** [comment]
The very top pixel is now used for window resize just like the controls on native windows.

**Comment by PeterNjeim** [comment]
That's true, but considering how the issue was rectified last year as it was seen as a bug, I believe it should be rectified again. It's a needless change that ruins usability for those who don't use Telegram maximized. Since this is a chat app that works better in a vertical aspect ratio, I'd expect a lot of people not to be using it in a maximized state, unlike most other programs. For anyone who wants the default experience, they can enable the system window frame option. Just my opinion

**Comment by ilya-fedin** [comment]
it's more about bugs with custom resize hacks that were used previously than the default experience. It's just there's no other way to implement top resize edge without such hacks. Whether your bug is more important that the ones the custom resize window was creating is questionable to me.

**Comment by PeterNjeim** [comment]
I didn't know there were "hacks" involved with the previous implementation, thanks for letting me know about that. If this makes the codebase easier to maintain, and wasn't just some minor change that's easily revertible, then that's fine by me

**Comment by ilya-fedin** [comment]
This doesn't make the codebase easier to maintain (at least because this couldn't be used with Windows <11 so there's now two codepaths) but:
1. This makes the window redraw way more rapid while resizing
2. It couldn't happen that the resize substrate is not moved with the Telegram window and its resize handles are in some other place on the screen (as there's no substrate and Windows handles this natively now)
3. This may make the window not so buggy in tablet mode where the substrate might conflict as it's a separate window

**Comment by PeterNjeim** [comment]
I was looking at the release notes and you now confirm that this is only for Windows 11. May I ask, could you make this change optional for users of Windows 11? I would like to use the older implementation that's still being using on Windows 10 if that's possible. I am having trouble downgrading Telegram. I get the old installer and install it, but by the time I re-sign in, it has already downloaded the newest update. Even if I disable the auto-update option, the update has already been downloaded and so the next time I close and open the app it gets updated. Is there any way I can disable the auto-update upon the first opening of the app? The `settingss` file is encrypted, thanks in advance

**Comment by ilya-fedin** [comment]
Personally I can't decide about options but knowing the person wo decides this: it's unlikely such an option would be introduced.

**Comment by PeterNjeim** [comment]
Got it working, you can open the settings from the initial sign in experience, and I disabled auto-update in there. I then deleted the `tupdates` folder in Telegram's `AppData/Roaming` folder.

Thanks for confirming that such an option would be unlikely, however I'll let you know that at the end of the day, the obscure options are usually introduced, like the ability to keep the old monotone icons (https://github.com/telegramdesktop/tdesktop/issues/24176#issuecomment-1086190045) or the ability to remove the reactions icon hover

**Comment by PeterNjeim** [comment]
Although it now seems the experimental options have been removed from the GUI, only accessible from the `experimental_options.json` file

**Comment by ilya-fedin** [comment]
Yeah, they're only for autoupdatable users
