### ISSUE TITLE
Self-destruct messages remain visible in sidebar

### ISSUE THREAD

**Issue by FabianSperrle** [telegramdesktop/tdesktop#2665]
### Steps to reproduce
1. Create a secret chat
2. Set self destruct timer
3. Send a message
4. Wait for the timer to run out, message disappears from the chat window
5. Message stays visible in the sidebar

### Expected behaviour
The message should not be visible in the sidebar after the timer has run out.

### Actual behaviour
"Self destructed" message stays visible forever

### Configuration
**Operating system:**
OS X 10.12.1
**Version of Telegram Desktop:**
2.28.51242

**Comment by auchri** [comment]
That's not Telegram Desktop: https://github.com/overtake/telegram

You can try Telegram Desktop from https://desktop.telegram.org
