### ISSUE TITLE
Message input duplicates after moving window between two displays with different resolution

### ISSUE THREAD

**Issue by Bargest** [telegramdesktop/tdesktop#26652]
### Steps to reproduce

1. Have 2 monitors with different resoluton (I have 2560x1440, 60Hz + 1920x1080 60Hz)
2. Open any chat
3. Drag Telegram window from one display to another
4. See the result
![image](https://github.com/telegramdesktop/tdesktop/assets/13108544/92620a1d-f38c-4d2e-b900-e69e902c8d00)
Resizing the window restores normal UI state.

### Expected behaviour

UI items should not be duplicated

### Actual behaviour

Message input visually duplicates; Some UI elements' "hitboxes" seem to be displaced.

### Operating system

Windows 11

### Version of Telegram Desktop

4.8.11 beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Is it OK in 4.9? There was an update to code managing the window on move between different scaling monitors.

**Comment by Bargest** [comment]
Yes, after today's update to 4.9 this is fixed. Thanks.
