### ISSUE TITLE
Unnecessary animation in replays

### ISSUE THREAD

**Issue by NavernoeDa** [telegramdesktop/tdesktop#26654]
### Steps to reproduce

1. Open post replys
2. Click and hold on the user tag in reply on reply

### Expected behaviour

There is no animation

### Actual behaviour

An animation is triggered, as if you click on the box where the original message is located (just above the replay text itself). How it (not) works, I showed [here](https://i.imgur.com/coxidoT.mp4)

### Operating system

Windows 10, 1909

### Version of Telegram Desktop

4.9

### Installation source

Static binary from official website

**Comment by NavernoeDa** [comment]
Also, the same animation works when you click and hold on the avatar of the person who replied to the message (and it’s also not necessary to look at the replays, this bug works in chat as well)


https://github.com/telegramdesktop/tdesktop/assets/80100455/e90b47dd-9e4e-41ac-940c-316455a26a03

**Comment by john-preston** [comment]
Please check the version 4.9.1, should be available via autoupdate in Settings or from https://desktop.telegram.org

**Comment by NavernoeDa** [comment]
yes everything works as it should, thank you!

**Comment by NavernoeDa** [comment]
yes everything works as it should, thank you!
