### ISSUE TITLE
The abnormal notification behavior of archive and chat.

### ISSUE THREAD

**Issue by xiaoshengshuohua** [telegramdesktop/tdesktop#26656]
### Steps to reproduce

After receiving new notifications, the unmuted chat added to the archive cannot be seen on the homepage interface.

### Expected behaviour

Just like before, the added channels and group notifications can correctly appear on the main interface.

### Actual behaviour

After receiving new notifications, the unmuted chat added to the archive cannot be seen on the homepage interface.

### Operating system

x86, IOS 16

### Version of Telegram Desktop

x86: 4.9, IOS: 10.0.0

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by john-preston** [comment]
@xiaoshengshuohua In the latest version there are Archive Settings in the Archive context menu:

![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/3ee91a70-35f5-49fb-aeb2-5c5bc68290d6)

You can decide when the chats are unarchived:

![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/e7895a80-615c-41eb-ab64-6fa0352e9459)
