### ISSUE TITLE
4.9.0 start error debian

### ISSUE THREAD

**Issue by MetaAbstract** [telegramdesktop/tdesktop#26658]
### Steps to reproduce

1. Update or download version 4.9.0
2. Run Telegram or Updater

### Expected behaviour

Prorgam started

### Actual behaviour

implib-gen: libwayland-client.so.0: failed to resolve symbol 'wl_proxy_marshal_flags' via dlsym: /lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: wl_proxy_marshal_flags
Aborted

### Operating system

Debian

### Version of Telegram Desktop

4.9.0

### Installation source

Static binary from official website

**Comment by dadingid** [comment]
exact same behavior here, so i guess it might be happening to more than a few people?

from the terminal:
$ ./Telegram/Telegram
implib-gen: libwayland-client.so.0: failed to resolve symbol 'wl_proxy_marshal_flags' via dlsym: /lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: wl_proxy_marshal_flags
Aborted

the updater just hangs forever:
$ ./Telegram/Updater
$ implib-gen: libwayland-client.so.0: failed to resolve symbol 'wl_proxy_marshal_flags' via dlsym: /lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: wl_proxy_marshal_flags
^C

i suppose we need another update to fix the bug, but how might we update it if the updater itself isn't working. uninstall and reinstall?

**Comment by ilya-fedin** [comment]
switching to X11 should let it launch in theory

**Comment by dadingid** [comment]
> switching to X11 should let it launch in theory

switching to x11 worked. thanks a lot

i followed this guide the switch from wayland to x11 (in debian):
https://trendoceans.com/how-to-enable-x11-and-disable-wayland-window-system/

this obviously is a workaround. should we expect a quick update to fix this? i suppose it's affecting a lot of people maybe...

**Comment by ilya-fedin** [comment]
well, it's quite complicated the problem is too new wayland library is used to build and this lacking symbols is an API that makes the library thread safe. So it's a choice between old distro support and thread safety.

**Comment by dadingid** [comment]
makes sense, but why it is becoming an issue just now?

**Comment by ilya-fedin** [comment]
There were manual wrappers for libwayland to make it optional but now libva, libva-x11, libva-drm, libvdpau and libdrm are required by ffmpeg, that's not acceptable, they should be optional but this manual approach obviously doesn't scale. A project named [Implib.so](https://github.com/yugr/Implib.so) was found to automatically generate wrappers but such auto-generated wrappers of course don't contain hacks of style "if this symbol is present, just use it, if not, use this shim code with older API" that was done with the manually written wrappers.

**Comment by john-preston** [comment]
Please check the version 4.9.1, should be available via autoupdate in Settings or from https://desktop.telegram.org

**Comment by dadingid** [comment]
yep it works again, thanks everyone. btw while using tg desktop using x11, the crashes were frequent. kind crazy. for example just tapping on a heart for a post would occasionally crash the program. no such issues on wayland tho. maybe it's just my setup. who knows. thanks again
