### ISSUE TITLE
Telegram loads the CPU by 50% at startup and 130% while in use

### ISSUE THREAD

**Issue by mettoa** [telegramdesktop/tdesktop#26663]
### Steps to reproduce

1. Launch Telegram
2. Use it 

### Expected behaviour

Stable operation, without heavy load on the system

### Actual behaviour

Loaded CPU by 50% at startup and growing to 130% while in use

### Operating system

macOS Ventura

### Version of Telegram Desktop

10.0.250522 Stable

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
