### ISSUE TITLE
Telegram Desktop App not opening after update

### ISSUE THREAD

**Issue by mendibox** [telegramdesktop/tdesktop#26666]
### Steps to reproduce

Click the update button on Aug 14 at 22:00 CST
Application closed but never reopen again
Attempted to reopen it by clicking the icon app without success
Opened a Linux terminal and execute:

1.  `./Telegram` but received the following message:

`implib-gen: libwayland-client.so.0: failed to resolve symbol 'wl_proxy_marshal_flags' via dlsym: /lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: wl_proxy_marshal_flags
Aborted
`
2. `./Updater` and received the following message:
`implib-gen: libwayland-client.so.0: failed to resolve symbol 'wl_proxy_marshal_flags' via dlsym: /lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: wl_proxy_marshal_flags`

### Expected behaviour

Reopen the desktop app

### Actual behaviour

The application does not open.

### Operating system

GNU/Linux Debian 11 (bullseye) GNOME 3.38.5

### Version of Telegram Desktop

4.8

### Installation source

Static binary from official website

**Comment by mendibox** [comment]
Can you tell me, at least, which issues is this a duplicate of or where can I fin further information about this Telegram issue?

**Comment by john-preston** [comment]
Please check the version 4.9.1, should be available via autoupdate in Settings or from https://desktop.telegram.org

**Comment by mendibox** [comment]
Telegram 4.9.1 is running again.
Thank you.
