### ISSUE TITLE
Battery burn out on Mac OS

### ISSUE THREAD

**Issue by l3r8yJ** [telegramdesktop/tdesktop#26660]
### Steps to reproduce

I have reproduced this bug on two macbooks - M1 Air and M1 Max Pro.

At the moment of opening telegram, the battery drains almost twice as fast. But I only noticed this on version 13 of macOS. While I was using version 12 of macOS, I didn't have this problem.

### Expected behaviour

Normal battery usage

### Actual behaviour

Battery burning 

### Operating system

macOS Ventura 13.5 (22G74)

### Version of Telegram Desktop

macOS version of telegram, not portable

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
"macOS version of telegram, not portable" aint a proper version.

**Comment by john-preston** [comment]
@l3r8yJ This is repository of Telegram Desktop. You can try it from:

https://desktop.telegram.org

If you use a different version please refer to a different repository, native macOS app is located here:

https://github.com/overtake/TelegramSwift
