### ISSUE TITLE
Changed behavior when using Windows 11 snap

### ISSUE THREAD

**Issue by Adam-Kay** [telegramdesktop/tdesktop#26667]
## Steps to reproduce

1. Update to Telegram Desktop 4.9
2. Attempt to use the Windows 11 Window Snap feature (Preset 2 Right Side Window - picture below)

![NVIDIA_Share_mt6KDyqUqe](https://github.com/telegramdesktop/tdesktop/assets/10010491/70b1bd26-7cf1-4b4a-a4a0-176c1cd3c46a)

3. It is now impossible to set Telegram to have the user pictures/bubbles on the left side of the screen.

### Pre-update behavior
When snapped to the right of the screen using Windows 11 Window Snap Preset 2, I should be able to have the user previews on the left side of the screen, as was the case in Telegram 4.8.

#### Preview:
![NVIDIA_Share_mt6KDyqUqe](https://github.com/telegramdesktop/tdesktop/assets/10010491/51088bc7-e285-4879-bf78-dcffe6476de5)

Out of Chat             |  In Chat
:-------------------------:|:-------------------------:
![Expected_1](https://github.com/telegramdesktop/tdesktop/assets/10010491/997aae54-b37e-43c2-9c4f-7544509fc8d1)  |  ![Expected_2](https://github.com/telegramdesktop/tdesktop/assets/10010491/13d22573-2998-445d-8abc-1896ae76bf76)

### Post-update behavior
Now after the update to Telegram 4.9, when snapped to the right of the screen using Windows 11 Window Snap Preset 2, it is no longer possible to have the user previews or picture "bubbles" pinned to the left. The threshold for window size to allow this seems to have **expanded by maybe 1 or 2 pixels** outside of the snap size in the last update.

#### Preview:
![NVIDIA_Share_mt6KDyqUqe](https://github.com/telegramdesktop/tdesktop/assets/10010491/b12dafe2-2cec-41cc-9921-3f5a43198f10)

Out of Chat             |  In Chat
:-------------------------:|:-------------------------:
![Actual_1](https://github.com/telegramdesktop/tdesktop/assets/10010491/f7f65b70-d112-4a99-863b-4878d2179add) | ![Actual_2](https://github.com/telegramdesktop/tdesktop/assets/10010491/1771c538-f5ac-4be1-8f9f-d440fc0b26eb)

## Operating system

Windows 11 Pro - Version 23H2 (22631.2191)

## Version of Telegram Desktop

4.9

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I guess these pixels belong to the native resize handles now and so this change is intended, not a bug

**Comment by Adam-Kay** [comment]
> I guess these pixels belong to the native resize handles now and so this change is intended, not a bug

Do you think it would be possible to alter the size threshold in the app itself to ensure the same functionality as older versions?

**Comment by john-preston** [comment]
Well, this depends on the interface scale, you can scale it down, like, 5% and it should fit.

**Comment by Adam-Kay** [comment]
> Well, this depends on the interface scale, you can scale it down, like, 5% and it should fit.

This is a good temporary workaround! Though the text does end up looking a little more "pixely" and different, even at just 95%.

100%             |  95%
:-------------------------:|:-------------------------:
![image](https://github.com/telegramdesktop/tdesktop/assets/10010491/d3795387-0ba8-4af4-a9f8-98ad6dab2668) | ![image](https://github.com/telegramdesktop/tdesktop/assets/10010491/6fd45fcd-dda3-4db0-9495-3260c97c3d79)
![Telegram_kttuV3CYp1](https://github.com/telegramdesktop/tdesktop/assets/10010491/fb496cbf-e884-42b4-9362-a9616cb4e015) | ![Telegram_g2RDyJtrtx](https://github.com/telegramdesktop/tdesktop/assets/10010491/891eb994-d011-4def-83bd-8fbfe3b95cfa)

Still, it's readable and perhaps it's just a case of getting used to the way it looks. It would still be preferable to maybe shift the internal threshold for the app (not reverting the code but just adjusting the size at which the window no longer allows left side "bubbles") - but I understand if this is not possible.

**Comment by ilya-fedin** [comment]
There's an alternative text renderer available (thanks to Qt) in experimental settings

**Comment by Adam-Kay** [comment]
> There's an alternative text renderer available (thanks to Qt) in experimental settings

This is a good suggestion! If you mean this option:

![image](https://github.com/telegramdesktop/tdesktop/assets/10010491/83cc9a31-9314-470a-9b04-509368630781)

I have tried it and at 95% it actually looks _worse_ in my opinion, but it's an experimental setting so maybe this will change

**Comment by ilya-fedin** [comment]
I don't think this will change, it's third party code
