### ISSUE TITLE
Telegram 4.9.0 not working on Debian 11 with Wayland

### ISSUE THREAD

**Issue by ftw-soft** [telegramdesktop/tdesktop#26665]
### Steps to reproduce

1. Open telegram
```bash
/opt/Telegram/Telegram
```

### Expected behaviour

Telegram opens successfully

### Actual behaviour

Getting an error
```
implib-gen: libwayland-client.so.0: failed to resolve symbol 'wl_proxy_marshal_flags' via dlsym: /lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: wl_proxy_marshal_flags
Aborted
```

### Operating system

Debian 11 Bullseye

### GNOME Version

3.38.5

### Version of Telegram Desktop

4.9.0

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#26658

**Comment by ftw-soft** [comment]
I suppose that this issue fixed in #26664

**Comment by john-preston** [comment]
Please check the version 4.9.1, should be available via autoupdate in Settings or from https://desktop.telegram.org

**Comment by ftw-soft** [comment]
The 4.9.1 version starts and works great. Thank you!
