### ISSUE TITLE
Errors out when opening up the application

### ISSUE THREAD

**Issue by shahin-hp** [telegramdesktop/tdesktop#26661]
### Steps to reproduce

1. Try to open up the app

### Expected behaviour

Should open up properly

### Actual behaviour

Nothing happens, exits quietly 

### Operating system

Debian 11

### Version of Telegram Desktop

4.9.0

### Installation source

Static binary from official website

### Logs

```shell
implib-gen: libwayland-client.so.0: failed to resolve symbol 'wl_proxy_marshal_flags' via dlsym: /lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: wl_proxy_marshal_flags
```

**Comment by komeilkamal** [comment]
I have same issue on Debian 11

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/26658

**Comment by john-preston** [comment]
Please check the version 4.9.1, should be available via autoupdate in Settings or from https://desktop.telegram.org
