### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by mxdpeep** [telegramdesktop/tdesktop#26662]
### Steps to reproduce

1. run Telegram
2. add ❤️ to a friend's post (mine works)

### Expected behaviour

not crashing 😵

### Actual behaviour

[libvpx-vp9 @ 0x7f809d6ed400] v1.11.0
[libvpx-vp9 @ 0x7f809d6ed400] v1.11.0
Segmentation fault (core dumped)

### Operating system

Ubuntu 22.04.3

### Version of Telegram Desktop

Telegram Desktop 4.9 for Ubuntu

### Installation source

Static binary from official website

### Crash ID

1ea46383-d129-4125-6641a985-174273be

**Comment by ArtDanilov** [comment]
Linux version shutdown after leaving a message reaction. Ubuntu, last version. Downgraded to 4.8.10 - all things working correctly.

**Comment by john-preston** [comment]
Thanks for your report!

**Comment by john-preston** [comment]
Please check the version 4.9.1, should be available via autoupdate in Settings or from https://desktop.telegram.org
