### ISSUE TITLE
UI has gone berserk: cannot select messages, right-click doesn't work

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#26674]
### Steps to reproduce

TEST CASE 1
---

1. click on the empty area of the current chat next to some message, on the right, hold the mouse button pressed, 
2. drag to select one or more messages

TEST CASE 2
---

1. Right-click on some message

### Expected behaviour

TEST CASE 1
---
Should select one or more messages as you drag, as if you were drawing a rectangle selecting the messages that the rectangle intersects (I forget whether the rectangle used to be actually drawn)

TEST CASE 2
---
Should unfold the context menu with options to manage the message you right-click over: such as delete, edit, etc.

### Actual behaviour

TEST CASE 1
---
Behaves as if you had clicked on the "reply" button.

At some point, after this started happening, while I was trying this again and again, I saw the text "Broadcast a message" somewhere, now I'm unable to reproduce that.

TEST CASE 2
---
When you right-click, the context menu flashes for a fraction of a second but disappears immediately.

Now I'm unable to edit or delete any messages, because the only two way I'm aware of to do so, are by either drag-select one or more messages, or with the right-click

This crap has started happening after I rebooted and therefore restarted Telegram Desktop. 
I won't be surprised if it goes away at the next restart.

### Operating system

Manjaro Linux

### Version of Telegram Desktop

4.8.4

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
it might be a bug of your environment, e.g. maybe it has gone into some weird state and was unable to give the focus to Telegram window. In that state you of course can't do selections and menus won't remain open without focus.

**Comment by ilya-fedin** [comment]
try instead of what you was doing, double-click. I.e. double left-click, double right-click. The actions done in such a way seem to behave just like you described.

**Comment by php4fan** [comment]
> Try instead of what you was doing, double-click. I.e. double left-click, double right-click. The actions done in such a way seem to behave just like you described.

If I understand correctly, you are hypothesizing that my clicks when I observed the issue were being somehow mistaken for double clicks, right?

That would indeed work for the case of the left-click. But not quite the right-click: when I double-right-click (now that the app is behaving normally), the context menu remains open (unless I quickly move the mouse to the left between the first and the second click, but I have to do it very on purpose and move it quite a bit)

**Comment by ilya-fedin** [comment]
> If I understand correctly, you are hypothesizing that my clicks when I observed the issue were being somehow mistaken for double clicks, right?

Yeah

> when I double-right-click (now that the app is behaving normally), the context menu remains open (unless I quickly move the mouse to the left between the first and the second click, but I have to do it very on purpose and move it quite a bit)

Hm, it closes for me. Although I use Wayland, its handling of menus seem to be more rapid.
