### ISSUE TITLE
Hamburger menu is rendered incorrectly on a Windows 11 4K display

### ISSUE THREAD

**Issue by ssg** [telegramdesktop/tdesktop#26677]
### Steps to reproduce

1. Run Telegram
2. Observe disproportionate hamburger menu with inconsistent distance between bars:

![image](https://github.com/telegramdesktop/tdesktop/assets/241217/bcb4acda-6ac4-4924-8043-4df786af0355)
![image](https://github.com/telegramdesktop/tdesktop/assets/241217/39b99381-b828-42c1-a8e5-3909c457e5cb)

### Expected behaviour

Hamburger menu should be displayed with consistent spacing between bars.

### Actual behaviour

Incorrect rendering.

### Operating system

Windows 11 Pro

### Version of Telegram Desktop

4.8.10 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Fine in my case:

![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/0d7559e0-f4dd-457f-973b-e3be7a71469a)

This depends on the screen scaling in System Settings and on Interface Scale in Telegram Settings and on "Enable precise High-DPI" in Telegram Settings > Advanced > Experimental Settings. If you have the last one enabled I suggest you disable it. If not - then it looks like icons are not scaled very well in some screen scale / interface scale combination :(

**Comment by ssg** [comment]
@john-preston Yes, disabling "precise High-DPI" fixed this issue. Thanks!
