### ISSUE TITLE
desktop.telegram.org/changelog is outdated in English locale

### ISSUE THREAD

**Issue by OLEGSHA** [telegramdesktop/tdesktop#26670]
### Steps to reproduce

1. Go to https://desktop.telegram.org/changelog
2. Change locale to English if it's not already
3. Note that last version is v4.8.1, not v4.9.1

### Expected behaviour

According to the update notification, changelog should display information about all published versions:
> Full version history is available here:
> https://desktop.telegram.org/changelog

### Actual behaviour

Changelog has apparently not updated since 2023-04-24.

### Operating system

n/a

### Version of Telegram Desktop

4.9.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Yeah, there were some problems with changelogs for the last versions, not really provided. I've added link to the descriptive blog post with 4.9 version.
