### ISSUE TITLE
Telegram doesn't work clearly on Ubuntu 23.04

### ISSUE THREAD

**Issue by mmdmatrix** [telegramdesktop/tdesktop#26686]
### Steps to reproduce

۱. Run 
2. Hang for about 5 minutes
3.hanging ...

### Expected behaviour

work perfectly on my Ubuntu 23.04 without any delay  

### Actual behaviour

Telegram does not work clearly on my Ubuntu 23.04, and Actually take about 5 minute to execution and after execute telegram does not let me login to my account
 
Tnx, developers

### Operating system

Ubuntu 23.04

### Version of Telegram Desktop

version 4.9.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
What does `busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings Read ss org.freedesktop.appearance color-scheme` return? Does it hang?

**Comment by mmdmatrix** [comment]
i didn't test this command yet

**Comment by mmdmatrix** [comment]
i didn't test this command yet

**Comment by mmdmatrix** [comment]
> What does `busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings Read ss org.freedesktop.appearance color-scheme` return? Does it hang?

 i test it in terminal, it return this  "v v u 1"

**Comment by ilya-fedin** [comment]
immediately? without hangs?

**Comment by mmdmatrix** [comment]
> immediately? without hangs?

 yes ...

**Comment by ilya-fedin** [comment]
In login screen, click "SETTINGS", activate "Install beta versions" option, exit Telegram, launch it again and while it hangs, do `pkill -f -ABRT Telegram`. On next launch, it should advice you to send a crash report. First copy the crash ID to clipboard, then send crash report and paste crash ID here.

**Comment by mmdmatrix** [comment]
> In login screen, click "SETTINGS", activate "Install beta versions" option, exit Telegram, launch it again and while it hangs, do `pkill -f -ABRT Telegram`. On next launch, it should advice you to send a crash report. First copy the crash ID to clipboard, then send crash report and paste crash ID here.


okay

**Comment by ilya-fedin** [comment]
It also should be possible to activate the option with `echo 1 > $HOME/.local/share/TelegramDesktop/tdata/devversion` and it should be possible to pick up the crash dump manually from $HOME/.local/share/TelegramDesktop/tdata/dumps (sort by creation date to find the latest) to not to wait until tdesktop would start to activate the option/send the report.

**Comment by mmdmatrix** [comment]
> m $HOME/.local/share/TelegramDesktop/tdata/

 i did what you said, but i did not get the desired result

**Comment by ilya-fedin** [comment]
Can you be more specific? What didn't you get?

**Comment by mmdmatrix** [comment]
> Can you be more specific? What didn't you get?

 the cash dump you said to pickup,  i didn't see nothing on the dump directory

**Comment by ilya-fedin** [comment]
Did you do `pkill -f -ABRT Telegram` when Telegram is in hanged state?

**Comment by mmdmatrix** [comment]
> Did you do `pkill -f -ABRT Telegram` when Telegram is in hanged state?

no, i forget it

**Comment by ilya-fedin** [comment]
Just re-checked, for the dump to appear, it seems you have to try to launch it again in the end. That's the time it saves the dump...

**Comment by mmdmatrix** [comment]
okay

**Comment by ilya-fedin** [comment]
Oops, nevermind my previous message, it's just I removed the dumps directory to check and it has created the directory on next launch. When directory exists, it creates the dump immediately.

**Comment by mmdmatrix** [comment]
> echo 1 > $HOME/.local/share/TelegramDesktop/tdata/devversion

okay

**Comment by mmdmatrix** [comment]
> Oops, nevermind my previous message, it's just I removed the dumps directory to check and it has created the directory on next launch. When directory exists, it creates the dump immediately.

okay
