### ISSUE TITLE
Notifications toggle not responding

### ISSUE THREAD

**Issue by mendibox** [telegramdesktop/tdesktop#26682]
### Steps to reproduce

Open the user, group or channel info.
Click the Notifications toggle.

The toggle works as expected but only if you click near it and not over it.

### Expected behaviour

Allow to enable and disable the the notifications for users, groups and channels.

### Actual behaviour

If you click on the toggle, it does not show the contextual menu

### Operating system

GNU/Linux Debian 11 GNOME 3.38.5

### Version of Telegram Desktop

4.9.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Please provide screencast of the issue
