### ISSUE TITLE
Wrong input size in telegram passport

### ISSUE THREAD

**Issue by komiljonov** [telegramdesktop/tdesktop#26683]
### Steps to reproduce

1. Go to telegram's telegram passport example website
https://core.telegram.org/passport/example
2. select any inputs you want
3. press log in with telegram then opens popup window in telegram desktop
4. go to personal details
5. The date of birth is out of border (Wider width to input)

### Expected behaviour

Input element must be same size with other inputs

### Actual behaviour

Input size (width) is out of berder.

### Operating system

Windows

### Version of Telegram Desktop

4.9.1 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I don't understand, please provide a screenshot.

For me it looks like that:

![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/20c6425d-2570-49e1-ba4a-e8f75de46b1f)

**Comment by komiljonov** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/74716894/176ef852-7cb0-4b66-98bd-a1d9604506dd)

It still look like this
