### ISSUE TITLE
unable to log in

### ISSUE THREAD

**Issue by overtube** [telegramdesktop/tdesktop#26685]
### Steps to reproduce

login on any pc/system with telephonem sim and code
wipe system on desktop where login is. try enter on account from telephone

### Expected behaviour

I wipe mine previous system, with autorized application.
and after I try login from smartphone device where attached sim card with these telephone number I cannot auth bc conformation code sending on account without by the fact that it is sent to an account that was on the erased system

### Actual behaviour

I wipe system where I have auth and cannot have access even from the phone from which the account was registered

### Operating system

Archlinux x86_64, LXDE

### Version of Telegram Desktop

4.9.1

### Installation source

Static binary from official website

### Crash ID

I cant have logs bc system where it installed is wiped

### Logs

```shell
I cant have logs bc system where it installed is wiped
```

**Comment by Aokromes** [comment]
mobile phone needs google services to be installed.

**Comment by overtube** [comment]
> mobile phone needs google services to be installed.

I cannot have gaps, telephone running on LinageOS

**Comment by overtube** [comment]
and all time all work fine, but happen that crap and I cant get access to mine account anymore

**Comment by Aokromes** [comment]
well, not telegram desktop bug.
https://github.com/telegramdesktop/tdesktop/issues/26626

**Comment by overtube** [comment]
and also I cant register new, bc telephone number already used, lol so what I can do for resolve?

**Comment by overtube** [comment]
already try, don't work

**Comment by overtube** [comment]
> well, not telegram desktop bug. #26626

that is don't work

**Comment by ilya-fedin** [comment]
not only gaps, the telegram apk must be official (not foss or something). Don't know whether the one from the official website would fit, safer to get from play store to make sure it has the right to get sms.

**Comment by overtube** [comment]
needed permissions enabled, sms and calls work,

**Comment by overtube** [comment]
the program tells me that the activation has been sent to your account, such as go to your telegram, I mean the messenger on the desktop, but I can’t log in either from the desktop or from the phone, because the message comes to the session to which I have long No access

**Comment by overtube** [comment]
also I write on support, but no one cant ask

**Comment by ilya-fedin** [comment]
> the program tells me that the activation has been sent to your account, such as go to your telegram, I mean the messenger on the desktop, but I can’t log in either from the desktop or from the phone, because the message comes to the session to which I have long No access

The server knows whether the session is really active. Such message usually mean the app you're trying to get the SMS in is not allowed to receive it, not that it's sent to an inactive session.

Although if the computer with the session is on and connected to the Internet (i.e. the session is really active), then you're in trouble, yeah...

**Comment by ilya-fedin** [comment]
> I cannot have gaps, telephone running on LinageOS

This means you sadly can't use Telegram, like you that or not...

**Comment by overtube** [comment]
but I used telegram without gaps and everything worked fine

**Comment by overtube** [comment]
![1](https://github.com/telegramdesktop/tdesktop/assets/15115920/871f2ff8-dc71-4aef-bdc2-b9d2e713c949)
![2](https://github.com/telegramdesktop/tdesktop/assets/15115920/14e2845c-beff-4249-b3be-533c96ee94bd)
![3](https://github.com/telegramdesktop/tdesktop/assets/15115920/7c40b192-a371-4087-bc8c-764f783d0ba2)

**Comment by ilya-fedin** [comment]
> but I used telegram without gaps and everything worked fine

Yeah, this wasn't a requirement at first but most applications got restricted from getting SMS and apparently gapps are used for some kind of device/app verification. This won't work anymore and you have to accept it...

**Comment by overtube** [comment]
![1](https://github.com/telegramdesktop/tdesktop/assets/15115920/b0e930ea-3219-495b-8046-402277ba8c4b)
![2](https://github.com/telegramdesktop/tdesktop/assets/15115920/b7c58c60-3193-466c-b417-d5bf2584b700)
![3](https://github.com/telegramdesktop/tdesktop/assets/15115920/9bfa38c4-5914-45e5-8b37-3ad1958e55ec)
![4](https://github.com/telegramdesktop/tdesktop/assets/15115920/5a12f00a-48a3-4615-9256-49739fa08d93)
![5](https://github.com/telegramdesktop/tdesktop/assets/15115920/9ec1bac1-eaa5-4afd-8c0c-a0a6f13dcd98)

**Comment by ilya-fedin** [comment]
I'm not sure what you wanted to say with that

**Comment by overtube** [comment]
I want to say that the necessary permissions for the correct operation of the application have been received

**Comment by ilya-fedin** [comment]
I mean permission from the platform. The platform doesn't allow your app to get SMS if it's not the official Android/iOS application and, in case of Android, you have gapps.
