### ISSUE TITLE
webapp does not work

### ISSUE THREAD

**Issue by babaruh** [telegramdesktop/tdesktop#26680]
### Steps to reproduce

1. try to open webapp
2. an empty window opens
3. nothing change

### Expected behaviour

workable wabapp

### Actual behaviour

empty window

### Operating system

Archlinux, i3

### Version of Telegram Desktop

4.9.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This is a known i3 issue: https://github.com/i3/i3/discussions/5091
