### ISSUE TITLE
2GB is not the real file size limit

### ISSUE THREAD

**Issue by grepwood** [telegramdesktop/tdesktop#26688]
### Steps to reproduce

1. Create a file of size 2147483648 bytes
2147483648 B / 1024 (B/KB) = 2097152 KB
2097152 KB / 1024 (KB/MB) = 2048 MB
2048 MB / 1024 (MB/GB) = 2 GB
According to the calculations, it's exactly 2GB, so it should work.
2. Try uploading it

### Expected behaviour

File should be uploaded

### Actual behaviour

Telegram complains it cannot be uploaded

### Operating system

Gentoo

### Version of Telegram Desktop

4.8.1

### Installation source

Other (unofficial) source

### Logs

```shell
What's the `*__REAL__*` file size limit?
```

**Comment by Aokromes** [comment]
2000 MB

**Comment by grepwood** [comment]
How many bytes exactly?

**Comment by grepwood** [comment]
2097152000 bytes seems to work, but additional confirmation would be appreciated

**Comment by john-preston** [comment]
Yes, it's 4000 parts of 512 KB each, so 4000 * 512 * 1024.
