### ISSUE TITLE
Add please tags or bookmarks

### ISSUE THREAD

**Issue by Timz** [telegramdesktop/tdesktop#2669]
Hello! Please add tags or bookmarks for messages. The large chat rooms hard to find important messages.
Often a mask "question / answer". It would be great if it could be seen.
Frequently asked questions in chat rooms and get important answers. It would be great if it could be seen.
Май инглиш ис бэд, так что продублирую по русски:
Уже не первый раз сталкиваюсь с тем что в чате задаются вопросы и на них получают ответы. Найти потом чтото очень проблематично. Было бы здорово чтоб можно было метки/закладки ставить и потом видеть список. Ну и как развитие этих меток метки "вопрос/ответы". Тогда чаты смогут накапливать знания очищенные от котиков и приветов))

**Comment by Kondra007** [comment]
Use #hashtags

**Comment by Timz** [comment]
решение "важное или не важное сообщение" принимает не автор сообщения, а участники, уже ПОСЛЕ того как сообщени прочтут. Поэтому хештеги не подходят

**Comment by Kondra007** [comment]
Please use English next time so that most of users can take part in discussions.
There's no API for "bookmarks" in Telegram Core API, so your issue is invalid and not related to TDesktop, sorry.

**Comment by stek29** [comment]
@Timz Reply to "important" messages with hashtags AFTER you've read them and decided that they should be saved

**Comment by stek29** [comment]
#2346
