### ISSUE TITLE
InlineQueryResultArticle + InlineQueryResultCachedSticker (unaligned)

### ISSUE THREAD

**Issue by DO97** [telegramdesktop/tdesktop#26699]
### Steps to reproduce

Create an inline result with at least one InlineQueryResultArticle and one InlineQueryResultCachedSticker.

### Expected behaviour

![IMG_20230822_173027_150](https://github.com/telegramdesktop/tdesktop/assets/17525578/cd868da1-81bd-444a-8cdf-0fa23fa120c2)

One year ago, circa.

### Actual behaviour

The InlineQueryResultArticle, if placed below, gets mixed up in the same line of the stickers (and maybe viceversa).

![IMG_20230822_173338_255](https://github.com/telegramdesktop/tdesktop/assets/17525578/642f9c48-4d97-43d8-8c1b-7698fcdbd8d3)

### Operating system

Windows 10

### Version of Telegram Desktop

4.9.2

### Installation source

Static binary from official website

**Comment by DO97** [comment]
> Yeah, a mixture of types isn't currently supported :( Need to be fixed at some point, didn't think it'd be used like that back when I was implementing this.

It looks like at some point the result would no longer wrap, as if it was removed by accident.

**Comment by DO97** [comment]
Is it possible to fix it? Thank you.

**Comment by john-preston** [comment]
Is there a bot that sends such results list so I could test it from scratch? You can share such bot and the query to reproduce the issue with me privately at https://t.me/preston
