### ISSUE TITLE
Create message forwarding with spoiler

### ISSUE THREAD

**Issue by d3cryptofc** [telegramdesktop/tdesktop#26697]
### Is your feature request related to a problem?

Sometimes I need to forward messages (no marked as spoiler) from a channel to some groups and users.

### Describe the solution you'd like

Create an option "Hide all messages with spoiler" on forwarding options.

### Describe alternatives you've considered

- Download media and upload again with spoiler. (bad alternative)
- Use a robot that receive messages and give it back with spoiler. (reasonable alternative)

### Additional context

![image](https://github.com/telegramdesktop/tdesktop/assets/47941854/c2874302-80ca-439f-826d-0ab824b5e27e)

**Comment by fabriciocybershell** [comment]
like this!

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by d3cryptofc** [comment]
Oh, great.

I did it, for those interested:
https://bugs.telegram.org/c/31537

 Thank you for your help!
