### ISSUE TITLE
Changing the size and position of the button for recording messages

### ISSUE THREAD

**Issue by tywonek** [telegramdesktop/tdesktop#26701]
### Is your feature request related to a problem?

Currently, the button for recording messages is located in the very corner of the screen, which causes a lot of inconvenience especially in the operation of the phone with one hand, but also the operation of gestures on phones. I often use this option to send messages, it can certainly be done much better. The button could be larger or floating or placed somewhere where it won't cause problems pressing it (such as in the middle and a little higher).

### Describe the solution you'd like

The button could be larger or floating or placed somewhere where it won't cause problems pressing it (such as in the middle and a little higher).

### Describe alternatives you've considered

Changing the size of the button

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
