### ISSUE TITLE
White line at the bottom of the screen when maximized

### ISSUE THREAD

**Issue by Laiteux** [telegramdesktop/tdesktop#26709]
### Steps to reproduce

Maximize tdesktop

### Expected behaviour

Not this

### Actual behaviour

An annoying white line appears at the bottom of my screen whenever I maximize the app.

### Operating system

Windows 11

### Version of Telegram Desktop

4.9.2 x64

### Installation source

Static binary from official website

**Comment by Laiteux** [comment]
https://youtu.be/LlCzqSaWcKI

**Comment by Laiteux** [comment]
dupe of #8746 i opened a few years ago

not on intel anymore btw: https://github.com/telegramdesktop/tdesktop/issues/8746#issuecomment-703371392

also on a single monitor now, if that's worth mentioning.

this has been reintroduced a while ago iirc but i couldnt be bothered opening an issue until now

**Comment by Laiteux** [comment]
![gVVSh8H28d](https://github.com/telegramdesktop/tdesktop/assets/33204743/6a427ffa-fbca-42e2-9316-eddea94efc39)

**Comment by ilya-fedin** [comment]
Please tell (find) the version where this was introduced. There were multiple works in the frame area at different time.

**Comment by Laiteux** [comment]
what's the easiest way to do that?

**Comment by ilya-fedin** [comment]
Ah, forgot to ask: do you have autohidden taskbar on that screen? If yes then this is expected behavior, Windows can't show it if a window fully covers the area.

**Comment by Laiteux** [comment]
I do. single monitor btw

how is this the expected behavior when other apps don't behave that way?

**Comment by ilya-fedin** [comment]
Every app has this. Most have them in the form of system-provided border but Telegram's window is borderless due to custom frame so you see the gap.

**Comment by ilya-fedin** [comment]
Yes, it's not going to be fixed or people would be unable to use auto-hidden taskbar with Telegram.

**Comment by Laiteux** [comment]
i see, that makes sense. thanks for explaining. (:
