### ISSUE TITLE
Add new shortcut for switching accounts

### ISSUE THREAD

**Issue by roomonmoon** [telegramdesktop/tdesktop#26706]
### Is your feature request related to a problem?

I often use keyboard shortcuts in telegrams. I have to switch between accounts using the mouse, it would be much more convenient to use a keyboard shortcut with numbers, just as it is implemented with chats and folders. Moreover, telegram limits the number of accounts in the client, 0-9 digits will be enough.

### Describe the solution you'd like

Possible combinations:

Shift+[1,2,3,4]
Alt+[1,2,3,4]

### Describe alternatives you've considered

There is nothing better than the original.

### Additional context

Is it possible to consider adopting a self-written implementation of this idea?

**Comment by ilya-fedin** [comment]
#8179
