### ISSUE TITLE
Import Multiple Proxies And Button To Remove Unavailable 

### ISSUE THREAD

**Issue by soroushmirzaei** [telegramdesktop/tdesktop#26704]
### Is your feature request related to a problem?

The proxies could just be imported individually. nowadays most of the Telegram channels provide multiple proxies and it's required to import them by link one by one, so it would waste a lot of time to click on them seperately and checkout it's connectivity.

### Describe the solution you'd like

The proxies could be concatenated by character like as `&` and when it's been imported by the app, the concatenated proxies would be splitted and then show a pop-up list of imported proxies to checkout connectivity individually. By this way lots of time would be saved and would be possible to only add the available ones when it's connectivity checking done.

### Describe alternatives you've considered

just make it possible to import multiple proxies into the app at once by something like as concatenated proxies as one link

### Additional context

Apart from this disccusion, it's suggessted to add a button in the proxy setting to make it possible to delete the unavailable proxies only.

**Comment by ilya-fedin** [comment]
#25974, #25145
