### ISSUE TITLE
The confusion of the data directory of the PC platform Linux/Win version

### ISSUE THREAD

**Issue by zhangjint5** [telegramdesktop/tdesktop#26716]
### Is your feature request related to a problem?

On the Linux platform, Telgram runtime data is generated in the ${HOME}/.local/share/TelgramDesktop directory. This is pretty standard.

But in the Windows version, the data is stored in the directory where the .exe is located, which makes people very confused!

### Describe the solution you'd like

It is recommended that the Windows platform store the data in the %USERPROFILE% directory by default!

### Describe alternatives you've considered

It is recommended that the Windows platform store the data in the %USERPROFILE% directory by default!

**Comment by ilya-fedin** [comment]
It's made so that there's no need to build separate builds for portable and non-portable versions. You can place Telegram in a directory it can't write and it will use %appdata%.

**Comment by john-preston** [comment]
Also, if you are speaking about defaults, then by default the setup is placing the exe in the appdata, so the app data is stored in the appdata as well. By default. But you can change the place the exe and data are stored.
