### ISSUE TITLE
Telegram still doesn't play any sound (music, video, etc) on Mac os 4.9.3

### ISSUE THREAD

**Issue by Ilya1510** [telegramdesktop/tdesktop#26714]
### Steps to reproduce

play any video, or music
Apple M2 Max, mac os 13.5.1

### Expected behaviour

hear the sound

### Actual behaviour

no sound

### Operating system

Mac os 13.5.1, Apple M2 Max

### Version of Telegram Desktop

4.9.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Please provide log.txt as instructed in the issue template.

**Comment by Ilya1510** [comment]
> Please provide log.txt as instructed in the issue template.

[log.txt](https://github.com/telegramdesktop/tdesktop/files/12443993/log.txt)

**Comment by ilya-fedin** [comment]
It says you have no audio device :thinking: 
```
[2023.08.26 02:08:38] Audio Playback Devices: 
[2023.08.26 02:08:38] Audio Playback Default Device: 
[2023.08.26 02:08:38] Audio Capture Devices: 
[2023.08.26 02:08:38] Audio Capture Default Device: 
[2023.08.26 02:08:38] Audio Error: No capture device found!
```
Enable the `debugmode` [cheat code](https://github.com/telegramdesktop/tdesktop/wiki/Cheat-Codes), restart tdesktop, reproduce the issue (try to play something), get `last_openal_log.txt` from DebugLogs subfolder. It might be that the file will be empty until you fully quit tdesktop (no background process).

**Comment by Ilya1510** [comment]
> 
[last_openal_log.txt](https://github.com/telegramdesktop/tdesktop/files/12444047/last_openal_log.txt)

**Comment by ilya-fedin** [comment]
Remove `/Users/user1/.alsoftrc` and restart tdesktop

**Comment by Ilya1510** [comment]
omg now it works!!!

**Comment by Ilya1510** [comment]
I think I ve done it before 4.9.3 trying to do something and it was wrong(
btw thank you !!!!!

**Comment by ilya-fedin** [comment]
You may want to enter `debugmode` again to disable debug mode as DebugLogs folder would grow really faast

**Comment by partylikeits1983** [comment]
This is closed, but it still is an issue...
