### ISSUE TITLE
"You can only change your phone number using mobile Telegram apps. Please use an official Telegram app on your phone to update your number."

### ISSUE THREAD

**Issue by esigra** [telegramdesktop/tdesktop#26715]
### Steps to reproduce

1. Execute "telegram-desktop".
2. Click on the 3 horizontal lines near the top-left corner.
3. Click "Setting".
4. Click "Edit profile".
5. Click "Phone number".

### Expected behaviour

Let the user enter a phone number and login code from [https://fragment.com/my/numbers].

### Actual behaviour

Error message about missing feature:
"You can only change your phone number using mobile Telegram apps. Please use an official Telegram app on your phone to update your number."

### Operating system

Gentoo Linux default/linux/amd64/17.1/no-multilib/systemd/merged-usr KDE

### Version of Telegram Desktop

4.8.4

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
not a bug.
