### ISSUE TITLE
[feature request] option to send message by Shift+Enter also

### ISSUE THREAD

**Issue by ifmihai** [telegramdesktop/tdesktop#2671]
I use IPython quite a lot, 
they use Shift+Enter to launch a multiple lines block code
Ctrl+Enter to write a new line of code in the same block

I use wordpress.com also,
they use Shift+Enter to add a new line inside the same paragraph

For me as a user, it's confusing.
My brain got used mostly to Shift+Enter when it comes to "send a bulk of stuff"

I was wondering if you find it useful to add Shift+Enter also, as a method to send
not to mention that, 
on my macbook, there's no Ctrl in the right side of keyboard => i need 2 hands for Ctrl+Enter
Shift+Enter (or Alt+Enter) would be possible with just the right hand.

Ideally it would be to let us define the shortcut in settings.
Or, instead of checkboxes,
a selectbox with more options, Shift+Enter included.
(selectbox would be slicker, will reduce space in settings)

### Configuration
**Operating system:**
Win7 64bit

**Version of Telegram Desktop:**
Telegram Desktop 0.10.19

**Comment by john-preston** [comment]
@ifmihai MacBook should have Cmd+Enter.

**Comment by ifmihai** [comment]
didn't know that, thanks
useful

but issue still stands as i see it
personally i prefer shift+enter anyway

**Comment by Aokromes** [comment]
#1257 ?
