### ISSUE TITLE
Image upload fails

### ISSUE THREAD

**Issue by hamidi2** [telegramdesktop/tdesktop#26720]
### Steps to reproduce

1. Have a considerable number of images to upload (maybe 1000 or more).
2. Upload them simultaneously to a channel or group or private chat, etc. by drag & drop or clicking on the clip icon.
3. Choose to group them or not.

### Expected behaviour

I expect all of the images be uploaded **with their original names and orders one after another** without any problem.

### Actual behaviour

The order is not put under consideration, while if I would upload videos, it would. I know that about videos, the original file is uploaded without any compression, but it can't be a good reason. I know that when I upload images they're compressed, but it can't be a good reason to choose a random name for them! Just keep the original names AND orders.

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.9.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
The API doesn't provide a way to supply names

**Comment by hamidi2** [comment]
So the API should be updated for this purpose. It can get names for images as it does for videos. Technologically it's not impossible.

**Comment by ilya-fedin** [comment]
This issue tracker is purely client-side and server-side devs won't see your request. If you want to report a platform-wide issue, you had to choose the appropriate item while creating the issue,

**Comment by hamidi2** [comment]
Oh, sorry. Do you know what's the address?
As I could understand from your answer, the server doesn't provide a way to get names from images, but provides a way to get names for videos, right?

**Comment by ilya-fedin** [comment]
it doesn't even allow to pass file name while uploading. I'm not sure what address you want, just click "New issue" and choose the appropriate issue type.

**Comment by hamidi2** [comment]
So how do videos keep their original names?

**Comment by ilya-fedin** [comment]
They are just files with an attribute

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
