### ISSUE TITLE
MP4 without sound auto-converts to GIF, with no way to send it as is (as a File)

### ISSUE THREAD

**Issue by alexchexes** [telegramdesktop/tdesktop#26728]
### Steps to reproduce

1. Take an MP4 file without sound, for example, a screen video capture from the ShareX screenshot utility.
2. Attempt to send it either by Drag & Drop or by clicking the "Attach a File" button.

### Expected behaviour

Similar to sending pictures, there should be an option to choose whether you want to send the file "as is" (in the original MP4 format) or to auto-compress/convert it.

### Actual behaviour

Telegram Desktop consistently performs an unwanted conversion of the MP4 file: for MP4 files without sound, it converts them to GIF format, with no way to undo the conversion or send the file in its original format.

### Operating system

Windows 10 21H2

### Version of Telegram Desktop

4.9.2 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
While you may not like this, it's not a bug

**Comment by alexchexes** [comment]
> While you may not like this, it's not a bug

@ilya-fedin Sorry, I considered this a bug because this non-disablable conversion feels like unexpected behavior to me. Should I create this again as a "Feature request"?

**Comment by ilya-fedin** [comment]
I recommend to search for existing issues, I believe this already has multiple duplicates

**Comment by alexchexes** [comment]
There is quite the opposite #7730 (previously, there was a very old #3217 that was almost the same as this, but it was then superseded by the #7730), assuming we're going in circles.

**Comment by ilya-fedin** [comment]
I momentally see #24610 if I search "mp4 gif". And there's way more in closed, yes.

**Comment by john-preston** [comment]
I'm not sure it's converted to anything, maybe it's just being shown in a specific way? With a "GIF" tag, for example. Or is it a different file (byte-wise) in case you "Save As" this file from a receiving Telegram Desktop? I think that the server just adds some attributes along with the file, saying "it's an mp4 sound-less video, so just display it as we display gifs usually".

**Comment by alexchexes** [comment]
@john-preston Thanks. I've checked, and the files are indeed identical. The misleading "GIF" title is simply a representation of how the video is displayed. This brings us back to #24610, where the video that Telegram chooses to play as a GIF becomes non-rewindable.
