### ISSUE TITLE
Night mode should match the system settings by default

### ISSUE THREAD

**Issue by xicely** [telegramdesktop/tdesktop#26725]
### Is your feature request related to a problem?

When I set up light/dark mode in the system settings I expect all the apps to follow it without additional actions for each app. Currently, in Telegram Desktop you have to manually activate this option.

### Describe the solution you'd like

`Settings -> Chat Settings -> Auto-night mode -> Match the system settings` should be turned on by default

### Describe alternatives you've considered

\-

### Additional context

Then I think the prompt to disable auto-night mode when switching night mode will be unnecessary. On mobile platforms user is just notified that auto-night mode is off. I have no idea how it should look like on a desktop given older systems (desktop environments) might not come with light/dark modes

**Comment by john-preston** [comment]
I'll ask about that.

**Comment by amadeusp** [comment]
I'd like that too! Telegram is currently the only app not offering that feature on Linux and it annoys me quite a bit. ;)

**Comment by ItachiSan** [comment]
I would also like to re-add the "match system setting" option.

**Comment by ilya-fedin** [comment]
It wasn't removed to re-add it. This issue is about the option be enabled by default, not removing or adding it.
