### ISSUE TITLE
Linux, X11, Debian Stretch 9, Xfce, tray icon issue: mouse click non-expected behavior

### ISSUE THREAD

**Issue by resurtm** [telegramdesktop/tdesktop#2673]
### Actual behaviour

1. Download Telegram Desktop for Linux
2. Launch it
3. Find tray icon of Telegram
4. Click on it with right mouse button (RMB), context menu is shown, which is normal and expected behavior
5. Click on this icon again, but now with left mouse button (LMB), context menu is shown again, which is not correct—instead Telegram window must be toggled (should become visible, if it was hidden; and should become hidden, if it was opened)
6. Sometimes expected behavior works for a while, but most time it does not

### Configuration
```
resurtm@resurtm-desktop:~$ screenfetch
         _,met$$$$$gg.           resurtm@resurtm-desktop
      ,g$$$$$$$$$$$$$$$P.        OS: Debian testing stretch
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 4.8.0-1-amd64
   ,$$P'              `$$$.      Uptime: 1h 40m
  ',$$P       ,ggs.     `$$b:    Packages: 1574
  `d$$'     ,$P"'   .    $$$     Shell: bash 4.4.5
   $$P      d$'     ,    $$P     Resolution: 1920x1200
   $$:      $$.   -    ,d$$'     DE: XFCE
   $$\;      Y$b._   _,d$P'      WM: Xfwm4
   Y$$.    `.`"Y$$$$P"'          WM Theme: Default
   `$$b      "-.__               GTK Theme: Adwaita [GTK2]
    `Y$$                         Icon Theme: Tango
     `Y$$.                       Font: Sans 10
       `$$b.                     CPU: Intel Core i5 CPU 760 @ 2.801GHz
         `Y$$b.                  GPU: GeForce GT 640/PCIe/SSE2
            `"Y$b._              RAM: 2562MiB / 16041MiB
                `""""           
```

![image](https://cloud.githubusercontent.com/assets/100198/20646115/5fdb73ca-b49e-11e6-9056-f0344b53bc2d.png)

```
resurtm@resurtm-desktop:~$ uname -a
Linux resurtm-desktop 4.8.0-1-amd64 #1 SMP Debian 4.8.5-1 (2016-10-28) x86_64 GNU/Linux

resurtm@resurtm-desktop:~$ cat /etc/debian_version 
stretch/sid

resurtm@resurtm-desktop:~$ cat /proc/version 
Linux version 4.8.0-1-amd64 (debian-kernel@lists.debian.org) (gcc version 5.4.1 20161019 (Debian 5.4.1-3) ) #1 SMP Debian 4.8.5-1 (2016-10-28)
```

![image](https://cloud.githubusercontent.com/assets/100198/20646131/0d420434-b49f-11e6-9a92-0e3ee305007b.png)

![image](https://cloud.githubusercontent.com/assets/100198/20646134/313f6944-b49f-11e6-8aaf-66abf112a94e.png)

### Logs

Do you need logs? I can provide if that information is vital.

**Comment by alleyoopster** [comment]
I found by removing libappindicator-gtk2/3 resolved the issue.

**Comment by stek29** [comment]
#922
