### ISSUE TITLE
Telegram Desktop Maximized Window

### ISSUE THREAD

**Issue by mohroba** [telegramdesktop/tdesktop#26738]
### Steps to reproduce

Generally, in telegram, your message bubble and profile image is on right hand side of the page and other parties of the same chat, are displayed on the left side.
When telegram desktop window is maximized, the message bubble and profile image gets pushed to the other side of window, from right to left.
And sometimes when maximized and the emoji panel is opened and stuck to the far right, this problem goes away.

### Expected behaviour

Your message bubble and profile image should always be on the right side of the window.

### Actual behaviour

Your message bubble and profile image is pushed to the opposite side of window , other parties of chat should be visible.

### Operating system

Windows 10 21H2

### Version of Telegram Desktop

4.9.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
this is intended
