### ISSUE TITLE
Touchpad pinch to zoom stopped working

### ISSUE THREAD

**Issue by TheRedWaxPolice** [telegramdesktop/tdesktop#26731]
### Steps to reproduce

Just click on an image and try to pinch to zoom on a touchpad. It's not working anymore.

### Expected behaviour

pinch to zoom should work on a touchpad like in previous versions

### Actual behaviour

pinch to zoom on a touchpad does nothing

### Operating system

windows 10

### Version of Telegram Desktop

4.9.2 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop never had such ability, apparently your touchpad driver emulated this for the old input API but doesn't do that for the new input API which tdesktop uses now.

**Comment by TheRedWaxPolice** [comment]
Interesting... it was working fine very recently.. like few previous versions.. 
How old is this new input API?

**Comment by ilya-fedin** [comment]
idk how old it is, it's called "DirectManipulation"

**Comment by TheRedWaxPolice** [comment]
So it's impossible to zoom in an image? 🤔

**Comment by ilya-fedin** [comment]
Yeah, at least in tdesktop itself, this was never implemented

**Comment by ilya-fedin** [comment]
I mean with touchpad pinch. You can use ctrl+zoom.

**Comment by TheRedWaxPolice** [comment]
> Yeah, at least in tdesktop itself, this was never implemented with touchpad pinch. You can use ctrl+scroll.

Oh man, that's too bad... 
Is there an official place to download older versions of telegram desktop?

**Comment by ilya-fedin** [comment]
You can use github releases here?

**Comment by TheRedWaxPolice** [comment]
Alright. 
Thank you very much for the assistance. 👍
