### ISSUE TITLE
App crashes if I insert a text containing or type a cyrillic letter "і"

### ISSUE THREAD

**Issue by DanielProg39** [telegramdesktop/tdesktop#26737]
### Steps to reproduce

1. Open a chat
2. Type or paste something like: `Математичні `
3. Lag and crash

### Expected behaviour

The app should continue working stably

### Actual behaviour

The app crashes.

Note that though I use atareao/telegram PPA repo to install and update Telegram, the repo contains the official Telegram binary package, just covered into deb package for more native installation and updating.

### Operating system

Linux Mint 21.2 Cinnamon

### Version of Telegram Desktop

4.9.4

### Installation source

Other (unofficial) source

### Crash ID

a76962b7-dcc2-4313-831c4799-adaeeb8c

**Comment by john-preston** [comment]
@DanielProg39 Can you please share what do you have in "Settings > Advanced > Spell checking" here:

![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/3c170141-e917-4022-8205-2003e1b1417c)

And share which dictionaries you have chosen in there:

![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/ffde2ae5-518a-4c63-b219-0f529eea73f6)

(tell, which ones are enabled)

**Comment by DanielProg39** [comment]
I have English, Russian and Ukrainian dictionaries enabled. As for other settings, wait a sec, I'll look up

**Comment by DanielProg39** [comment]
Here are my spell checking settings:

![image](https://github.com/telegramdesktop/tdesktop/assets/63293432/0a951480-ee7a-44dd-9a05-509781d546f7)

**Comment by DanielProg39** [comment]
Btw, I tried wiping all data and reinstalling (and so redownloading dictionaries) and that didn't help

**Comment by DanielProg39** [comment]
Disabling Ukrainian dictionary doesn't help either

**Comment by ilya-fedin** [comment]
It's the other way around, disabling other dictionaries is likely to help

**Comment by DanielProg39** [comment]
I have a friend that uses official Telegram binary on Fedora, he also has this issue

**Comment by DanielProg39** [comment]
> It's the other way around, disabling other dictionaries is likely to help

Ok, I'll try

**Comment by SmartFinn** [comment]
English + Ukrainian dictionaries work fine. The issue appears only when Russian is enabled.

**Comment by ilya-fedin** [comment]
Yeah, it tries to convert the text to KOI8-R, expectedly fails and returns nullptr. C++ auto-generated wrappers for system APIs then crash on null pointer dereference.

**Comment by DanielProg39** [comment]
> I have a friend that uses official Telegram binary on Fedora, he also has this issue

Flatpak has this issue too (I know that this is not very useful, just will leave this here)

**Comment by DanielProg39** [comment]
Yup, disabling Russian dictionary helps

**Comment by DanielProg39** [comment]
> Yeah, it tries to convert the text to KOI8-R, expectedly fails and returns nullptr. Auto-generated C++ wrappers for system APIs then crash on null pointer dereference.

Got it. Thanks for explanation

**Comment by ilya-fedin** [comment]
Now we have to wait until this is fixed in this third-party project
https://gitlab.com/mnauw/cppgir/-/issues/56

**Comment by Articxok** [comment]
Same problem, with Esperanto letters "ĝ" or "ĥ" and the Italian spell-checker.
