### ISSUE TITLE
 Could NOT find QT (missing: QT_DIR) when build telegram desktop from sourcode

### ISSUE THREAD

**Issue by vunh195** [telegramdesktop/tdesktop#26740]
### Steps to reproduce

1. Follow these steps in https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md
2. But when go to step "Build the project" and run this command
` configure.bat x64 -D TDESKTOP_API_ID=YOUR_API_ID -D TDESKTOP_API_HASH=YOUR_API_HASH `
I got error:
Warn about uninitialized values.
Version: 4.9.4
-- Could NOT find QT (missing: QT_DIR)
CMake Error at cmake/external/qt/package.cmake:35 (message):
  Neither Qt6 nor Qt5 is found
Call Stack (most recent call first):
  CMakeLists.txt:67 (include)

-- Configuring incomplete, errors occurred!
FAILED

### Expected behaviour

build pass

### Actual behaviour

build failed

### Operating system

win11

### Version of Telegram Desktop

4.9.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This usually means the previous step (prepare\win.bat) is not succeeded

**Comment by vunh195** [comment]
> This usually means the previous step (prepare\win.bat) hasn't succeeded
thank u bro, i run again win.bat and it worked.

**Comment by xiangdingquan** [comment]
i have the seem question，i run again win.bat and it dont work.

**Comment by ilya-fedin** [comment]
this likely means win.bat still fails, look at its output
