### ISSUE TITLE
Solution for issue #90

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#26743]
### Is your feature request related to a problem?

I have to start new issue, because mentioned issue is locked. At 64Gram repo and issue tracker I've just found #90 [solution](https://github.com/TDesktop-x64/tdesktop/issues/135) with [font choose](https://github.com/ysc3839/FontMod). Maybe it could be implemented to man TGDesktop app.

### Describe the solution you'd like

https://github.com/ysc3839/FontMod

### Describe alternatives you've considered

Or merge some code from 64Gram.

**Comment by ilya-fedin** [comment]
Not sure what exactly you mean by solution. tdesktop's lib_ui library already has technical code for font choosing. The problem is the lack of someone who would implement the UI part according to Telegram's state designers mockups (@john-preston sadly has no time for this).

(if I'm not mistaken)
