### ISSUE TITLE
Suddenly missing OpenGL from ANGLE graphics backend-menu

### ISSUE THREAD

**Issue by adivvkvns** [telegramdesktop/tdesktop#26747]
### Steps to reproduce

Settings -> Advanced -> ANGLE graphics backend and OpenGL-option is missing there.

**Before:**
![before](https://github.com/telegramdesktop/tdesktop/assets/97660050/de146a32-2afd-4612-b6f7-7d56c5e83a80)
**Now:**
![now](https://github.com/telegramdesktop/tdesktop/assets/97660050/0faead54-1eab-4970-9a26-f3223e8858ce)

### Expected behaviour

Return of **OpenGL**-option into ANGLE graphics backend-menu.
Or i would like to hear an explanation why the **OpenGL** was removed and for how long?

### Actual behaviour

I can't select **OpenGL** in ANGLE graphics backend-menu (advanced settings), the option just **disappeared** in the latest updates and the whole problem leads to **green tint** over the video once visualizing it/playing in the video player in Telegram.
- My laptop's videocard does not support DirectX 11 and 12.
- Green tint does **not** disappear with other options, even if you use **Auto**.
There was **no green** ting when i used **OpenGL** and everything was great with videoplaying inside Telegram.

### Operating system

Windows 11 x64

### Version of Telegram Desktop

4.9.4 with beta enabled

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
not a bug, removed for certain gfx cards (igpus mainly)

**Comment by adivvkvns** [comment]
> not a bug, removed for certain gfx cards (igpus mainly)

until forever? sadly, it worked like charm before...

**Comment by ilya-fedin** [comment]
OpenGL never worked with any GPU. It's the same as Disabled.

**Comment by adivvkvns** [comment]
> OpenGL never worked with any GPU. It was the same as Disabled.

alright thank you.
closed.
