### ISSUE TITLE
I can not see how many subscribers in channel and group

### ISSUE THREAD

**Issue by DengYuncheng27** [telegramdesktop/tdesktop#26742]
### Steps to reproduce

just download and install , I've reinstalled it several times and even updated to the latest version, but the issue persists. Neither channels nor groups display the number of members; it always shows as garbled text.
some example are as follows
![image](https://github.com/telegramdesktop/tdesktop/assets/56923863/47ada267-4d0e-47a5-a32c-6f7eb3888648)
![image](https://github.com/telegramdesktop/tdesktop/assets/56923863/be87470e-9041-42e3-8bd1-da8aeda5ff41)
![image](https://github.com/telegramdesktop/tdesktop/assets/56923863/3877158b-bd82-4a9d-8e6b-b3b2c038a239)
![image](https://github.com/telegramdesktop/tdesktop/assets/56923863/67389402-ff79-4660-98ee-3c48832935a3)

### Expected behaviour

can not see how many members or subscribers in channel or group 
and i hava update latest version of desktop telegram 
![image](https://github.com/telegramdesktop/tdesktop/assets/56923863/ea2f9a2f-2b4c-499c-a6d0-d0a7ed1b677c)
![image](https://github.com/telegramdesktop/tdesktop/assets/56923863/0819f7db-95fb-49c9-937f-ac4f259fa568)

### Actual behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/56923863/c3cd7e9c-2fbf-44b4-a336-70d0207d157a)

### Operating system

win 11 professsion

### Version of Telegram Desktop

4.9.4 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Try to reboot your system. There were issues that after long uptime of Windows various characters get misrendered, apparently a bug in Windows.

**Comment by DengYuncheng27** [comment]
After the system restarts, it still looks like above again，Just garbled in the display of the number of people of channel.

**Comment by DengYuncheng27** [comment]
I solve by change county and region format in windows, and restart telegram is ok .  thank you  
![image](https://github.com/telegramdesktop/tdesktop/assets/56923863/336a2969-aa87-46fb-a995-ba55767087e1)
