### ISSUE TITLE
How to disable Google Breakpad

### ISSUE THREAD

**Issue by mohamad62** [telegramdesktop/tdesktop#2674]
Hello
Is it possible to disable Google Breakpad? I don't want to use it.

Windows 10
Visual Studio 2015

**Comment by john-preston** [comment]
@mohamad62 There is a preprocessor directive for that. You can try to add a TDESKTOP_DISABLE_CRASH_REPORTS define in the project GYP file.

**Comment by mohamad62** [comment]
Thank you, but where can I find that file? 
I add TDESKTOP_DISABLE_CRASH_REPORTS in the menu **Configuration Properties > C/C++ > Preprocessor**, but it still doesn't work

**Comment by john-preston** [comment]
@mohamad62 Telegram/gyp/Telegram.gyp has 'defines' which contains 'AL_LIBTYPE_STATIC'. You can add it there, then once again lauch refresh.bat and build the solution.

**Comment by mohamad62** [comment]
Thank you
