### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by RasTurbo** [telegramdesktop/tdesktop#2675]
When I try to build Telegram, I face the following error
Windows 10
Visual Studio 2015
![untitled](https://cloud.githubusercontent.com/assets/24223873/20666629/709332a2-b57a-11e6-91c4-8714ccff04f8.png)

@

**Comment by john-preston** [comment]
@RasTurbo After building Google Breakpad you should have:

"TBuild\Libraries\breakpad\src\client\windows\(Debug|Release)" folder which contains "lib/common.lib"

**Comment by RasTurbo** [comment]
Actually I've already disabled Google Breakpad, I don't need to use it, Could you please tell me how I can solve the problem without Google Breakpad

**Comment by john-preston** [comment]
@RasTurbo Then you'll need to remove Google Breakpad dependencies from telegram_win.gyp file:

'lib/common',
'lib/exception_handler',
'lib/crash_generation_client',

**Comment by RasTurbo** [comment]
Solved 
Thanks

**Comment by noorzaie** [comment]
@john-preston I can't find telegram_win.gyp. I have telegram_win.gypi instead. and I've deleted lines you have said. but problem not solved.

**Comment by mvgx** [comment]
@john-preston manually copy those libs from` client\windows` to `client `folder
