### ISSUE TITLE
app does not shown after clicking on message notification on wayland

### ISSUE THREAD

**Issue by jamesRUS52** [telegramdesktop/tdesktop#26759]
### Steps to reproduce

Fedora 38
Wayland

Clicking on notification message not show the app, not opening notificated chat 

### Expected behaviour

Open the app, select the notified chat

### Actual behaviour

nothing happen

### Operating system

Fedora 38

### Version of Telegram Desktop

4.8.4

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
This is broken on GNOME side for about a year
https://gitlab.gnome.org/GNOME/gtk/-/issues/5239

**Comment by ilya-fedin** [comment]
As far as I understand, they don't have support for this
https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/43
