### ISSUE TITLE
Build failed on linux

### ISSUE THREAD

**Issue by neoedmund** [telegramdesktop/tdesktop#26758]
### Steps to reproduce

```
git clone --recursive https://github.com/telegramdesktop/tdesktop.git
./tdesktop/Telegram/build/prepare/linux.sh
```
then 
```
docker run --rm -it \
    -v $PWD:/usr/src/tdesktop \
    tdesktop:centos_env \
    /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
    -D TDESKTOP_API_ID=YOUR_API_ID \
    -D TDESKTOP_API_HASH=YOUR_API_HASH
```

### Expected behaviour

pass

### Actual behaviour

```
/var/tmp/sclBvym5Y: line 8: /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh: No such file or directory
```

### Operating system

linux debian 11 xfce3

### Version of Telegram Desktop

git 48072446821edcdd11b502906bb2123a903be321

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I bet you tried to launch the command in some non-standard way and you got problems with escaping characters

**Comment by neoedmund** [comment]
I will try again later. by the way what `$PWD` is?

**Comment by ilya-fedin** [comment]
That's very easy to google and even wikipedia knows
https://en.wikipedia.org/wiki/Pwd#Working_directory_shell_variables

**Comment by neoedmund** [comment]
> I bet you tried to launch the command in some non-standard way (not by pasting to terminal) and you got problems with escaping characters

In Terminal and I merge to one single line, no escaping characters. Seems not that reason.

**Comment by neoedmund** [comment]
Sorry I realized I run it in the wrong path. cd to `tdesktop/` and problem gone
