### ISSUE TITLE
Telegram Desktop crashes when typing certain unicode characters (Ubuntu)

### ISSUE THREAD

**Issue by ralucado** [telegramdesktop/tdesktop#26757]
### Steps to reproduce

1. Open any conversation in version 4.9.4
2. Paste the text "veɪɡəs" in the text box

### Expected behaviour

The program should not crash

### Actual behaviour

Telegram desktop suddenly closes. When re-opened, the draft message saved is prior to the input of the unicode characters.

### Operating system

Linux 22.04.1-Ubuntu x86_64

### Version of Telegram Desktop

4.9.4

### Installation source

Static binary from official website

### Crash ID

`b03efc70-d569-4e43-7680f6aa-91b064d2`

**Comment by Aokromes** [comment]
duplicate.

**Comment by ralucado** [comment]
> duplicate.

Hi sorry, do you mind linking to the original issue this duplicates? I'd like to follow up on that one but I can't find it. Thank you !

**Comment by Aokromes** [comment]
> > duplicate.
> 
> Hi sorry, do you mind linking to the original issue this duplicates? I'd like to follow up on that one but I can't find it. Thank you !

well, it's fixed already on next build.

**Comment by DISN-kolo** [comment]
> > > duplicate.
> > 
> > 
> > Hi sorry, do you mind linking to the original issue this duplicates? I'd like to follow up on that one but I can't find it. Thank you !
> 
> well, it's fixed already on next build.

oh! that's great news. was about to report that too, haha

**Comment by mavoga** [comment]
It still happens on Debian testing, telegram-desktop v4.10.3+ds-1+b1. Example text that causes immediate segmentation fault when pasted (no useful messages on the console): "naručiti čim".

Debian up-to-date testing
telegram-desktop v4.10.3+ds-1+b1
KDE Plasma v5.27.8 running on Wayland
KDE Frameworks v5.107.0
QT v5.15.10

Thanks

**Comment by mavoga** [comment]
@ralucado please reopen this issue

**Comment by mavoga** [comment]
> plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

That version doesn't crash, thanks.
It seems the version is identical. Do you have any advice to spot the problem?

**Comment by mavoga** [comment]
Got it: by disabling the spell checker telegram-desktop doesn't crash anymore.
Is this a Telegram issue or a hunspell issue?

**Comment by Aokromes** [comment]
> Got it: by disabling the spell checker telegram-desktop doesn't crash anymore. Is this a Telegram issue or a hunspell issue?

it's telegram debian package issue.
