### ISSUE TITLE
Add a setting to change fonts

### ISSUE THREAD

**Issue by CrotchBurnt** [telegramdesktop/tdesktop#26755]
### Is your feature request related to a problem?

None

### Describe the solution you'd like

Provide an advanced setting for fonts, like, one typeface for UI, one for monospace, etc.

### Describe alternatives you've considered

None

**Comment by Aokromes** [comment]
#90

**Comment by CrotchBurnt** [comment]
> #90

That issue has been open for nearly 9 years, is there any update?

**Comment by ilya-fedin** [comment]
Well, the fact there's a request doesn't mean it will ever be considered to be implemented.
