### ISSUE TITLE
configure  erro

### ISSUE THREAD

**Issue by xiangdingquan** [telegramdesktop/tdesktop#26769]
### Steps to reproduce

Performing C++ SOURCE FILE Test DESKTOP_APP__Wno_deprecated_declarations_EXISTS failed with the following output:
Change Dir: D:/VSCODE/td/tdesktop/out/CMakeFiles/CMakeTmp

Run Build Command(s):D:/Program Files/microVisualStudio/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_bf264.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && 适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa

  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.37.32822 版
  版权所有(C) Microsoft Corporation。保留所有权利。
  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D DESKTOP_APP__Wno_deprecated_declarations_EXISTS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_bf264.dir\Debug\\" /Fd"cmTC_bf264.dir\Debug\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue  -Wno-deprecated-declarations D:\VSCODE\td\tdesktop\out\CMakeFiles\CMakeTmp\src.cxx
cl : 命令行  error D8021: 无效的数值参数“/Wno-deprecated-declarations” [D:\VSCODE\td\tdesktop\out\CMakeFiles\CMakeTmp\cmTC_bf264.vcxproj]

Source file was:
int main() { return 0; }

### Expected behaviour

PS D:\VSCODE\td\tdesktop\Telegram> .\configure.bat x64 -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb
Warn about uninitialized values.
Version: 4.9.5
CMake Error (dev) at cmake/validate_d3d_compiler.cmake:34 (if):
  uninitialized variable 'WindowsSdkDir'
Call Stack (most recent call first):
  cmake/win_directx_helper/CMakeLists.txt:16 (validate_d3d_compiler)
This error is for project developers. Use -Wno-error=dev to suppress it.

CMake Error (dev) at cmake/validate_d3d_compiler.cmake:43 (if):
  uninitialized variable 'windows_sdk_loc'
Call Stack (most recent call first):
  cmake/win_directx_helper/CMakeLists.txt:16 (validate_d3d_compiler)
This error is for project developers. Use -Wno-error=dev to suppress it.

CMake Warning at cmake/validate_d3d_compiler.cmake:11 (message):
  Could not find Windows SDK.
Call Stack (most recent call first):
  cmake/validate_d3d_compiler.cmake:44 (validate_d3d_error)
  cmake/win_directx_helper/CMakeLists.txt:16 (validate_d3d_compiler)

Resolved NuGet executable: D:/VSCODE/td/ThirdParty/NuGet/nuget.exe
Feeds used:
  C:\Users\43592\.nuget\packages\
  https://api.nuget.org/v3/index.json

Package "Microsoft.Windows.CppWinRT.2.0.210505.3" is already installed.
Using existing WinRT headers.
Using existing WinRT headers.
Using existing WinRT headers.
Feeds used:
  C:\Users\43592\.nuget\packages\
  https://api.nuget.org/v3/index.json

Package "Microsoft.Web.WebView2.1.0.1901.177" is already installed.
Using existing WinRT headers.
Using existing WinRT headers.
-- Configuring incomplete, errors occurred!
See also "D:/VSCODE/td/tdesktop/out/CMakeFiles/CMakeOutput.log".
See also "D:/VSCODE/td/tdesktop/out/CMakeFiles/CMakeError.log".
FAILED

### Actual behaviour

eeee

### Operating system

windows

### Version of Telegram Desktop

4.9.5

### Installation source

Microsoft Store

### Logs

```shell
Performing C++ SOURCE FILE Test DESKTOP_APP__Wno_deprecated_declarations_EXISTS failed with the following output:
Change Dir: D:/VSCODE/td/tdesktop/out/CMakeFiles/CMakeTmp

Run Build Command(s):D:/Program Files/microVisualStudio/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_bf264.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && 适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa

  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.37.32822 版
  版权所有(C) Microsoft Corporation。保留所有权利。
  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D DESKTOP_APP__Wno_deprecated_declarations_EXISTS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_bf264.dir\Debug\\" /Fd"cmTC_bf264.dir\Debug\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue  -Wno-deprecated-declarations D:\VSCODE\td\tdesktop\out\CMakeFiles\CMakeTmp\src.cxx
cl : 命令行  error D8021: 无效的数值参数“/Wno-deprecated-declarations” [D:\VSCODE\td\tdesktop\out\CMakeFiles\CMakeTmp\cmTC_bf264.vcxproj]


Source file was:
int main() { return 0; }
```

**Comment by ilya-fedin** [comment]
Are you sure you're running configure.bat in the respective Native Tools Command Prompt as mentioned in documentation?

**Comment by xiangdingquan** [comment]
yeah its my fault！
