### ISSUE TITLE
Graphical bug when rendering messages with chat wallpaper

### ISSUE THREAD

**Issue by davidmartos96** [telegramdesktop/tdesktop#26766]
### Steps to reproduce

1. Open a private chat
2. Set a chat wallpaper

![image](https://github.com/telegramdesktop/tdesktop/assets/22084723/de4c9573-1aed-486d-8f50-5e069d228c2e)

### Expected behaviour

No glitches when rendering

### Actual behaviour

"My" last messages have a weird display issue. "My" messages at the top half of the screen render correctly. When I scroll this stays the same. Lower half incorrect, top half correct.

### Operating system

Linux Fedora 38 64 bits GNOME

### Version of Telegram Desktop

4.9.5

### Installation source

Flatpak

**Comment by nonethree** [comment]
Same issue

Operating system

Windows 11 Home 10.0.22621 build 22621

Version of Telegram Desktop

4.13.1

**Comment by davidmartos96** [comment]
I have more details about this issue.
I believe it has to do with UI scaling or similar, it only happens on my secondary monitor.
It's like the shader effect doesn't use the correct screen dimensions.

@nonethree Do you have a similar setup?
