### ISSUE TITLE
[Bug|Inconsistency]No "Download selected" when you select more than 15-20+ tracks

### ISSUE THREAD

**Issue by Aphotic** [telegramdesktop/tdesktop#26762]
### Steps to reproduce

try to have a bot like:

https://t.me/deezload2bot
or
https://t.me/DeezerMusicBot
send you the top 30 or an album that has more than 20 tracks then drag em all and right-click and see if "download selected" appears        
or just try to download  20+ mp3s/or any other file (?) from any source at the same time with "download selected"

it's very unclear and inconsistent how the "download selected" actually works
sometimes you can select and download 20+ tracks all together
sometimes you cant download less than 10 tracks all together

i simply do not understand. 

someone on telegram desktop group mentioned it might be related to FIFO ?

### Expected behaviour

"download selected" right-click context menu should allow you to download max 100 selected files without caring about duplicate file names(rename the new ones) existing or how many you selected, if it's not more than 100 at a time selected.

### Actual behaviour

"download selected" does not appear randomly if you select an amount of more than 5 tracks or maybe related to file sizes. idk.

### Operating system

Windows 10

### Version of Telegram Desktop

4.9.4 x64

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
@Aphotic 
Hello. You are free to check a test debug build with some enchantments for "Download Selected".
https://github.com/telegramdesktop/tdesktop/actions/runs/6107522965

**Comment by Aphotic** [comment]
tested it, seems #26762 & #26761 are both fixed!      
Seemingly now you can download to max select 100 mp3 and dl them with "download selected" no matter if there are any already downloaded mp3 among the selection!    
thanks a bunch ♥
