### ISSUE TITLE
Option to enlarge the font without enlarging the entire interface

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#26764]
### Is your feature request related to a problem?

The problem is that the default font size is too small, but the rest of the interface is normal size. Zooming in causes the font to become normal sized and the interface is huge.

### Describe the solution you'd like

Ability to enlarge the font by several units

### Describe alternatives you've considered

Ideally make font customization like in Kotatogram. But even adjusting the font size would be great.

**Comment by Aokromes** [comment]
#90
