### ISSUE TITLE
Cannot add public link when there are 17 and limit is 20

### ISSUE THREAD

**Issue by offstate** [telegramdesktop/tdesktop#26774]
### Steps to reproduce

My account is Premium.
I had 20 public links (channels and groups) and I needed to add one more. 
20 links is the maximum number for Premium and I tried to rename one of existed channel. I got an error that the limit is reached.
I decided to delete one existing channel and create new but that didn't help. For now I already deleted 3 of my old links and the program tells me that I reached the limit of public links.
Finally I have 17 links and I cannot add any more.

### Expected behaviour

Telegram should add new public group|channel or rename existing

### Actual behaviour

In telegram-desktop (linux) version it shows 20 links used when it shows 17 in the list.
In android version it honestly shows 17 links used but doesn't allow to add one more.
![изображение](https://github.com/telegramdesktop/tdesktop/assets/16996529/38ef50b9-8c56-48b5-bff6-3d27a4b3e6b9)
![изображение](https://github.com/telegramdesktop/tdesktop/assets/16996529/547c919d-7f63-4556-9cf6-7b5942fb414e)

### Operating system

ubuntu 20.04, KDE neon User - 5.26, Plasma Shell

### Version of Telegram Desktop

4.9.5

### Installation source

Snap

**Comment by john-preston** [comment]
Can you share your username please?

**Comment by john-preston** [comment]
You can contact me in private at https://t.me/preston

**Comment by offstate** [comment]
> Can you share your username please?

@offstate

**Comment by john-preston** [comment]
@offstate Yeah, I've asked the server side team, but still didn't get any response.

**Comment by john-preston** [comment]
@offstate I'm told that's because you're offering some usernames on fragment. A username offered on fragment is counted even if it's detached from a channel. There are three usernames right now that are not attached to any channel, but are offered on fragment and are counted as your usernames. You can remove them from fragment selling offering and they should be freed, I guess.
