### ISSUE TITLE
No audio output

### ISSUE THREAD

**Issue by tinodj** [telegramdesktop/tdesktop#26780]
### Steps to reproduce

1. After answering a call I couldn't hear audio. 
2. There is no output settings in my call settings. 

<img width="905" alt="image" src="https://github.com/telegramdesktop/tdesktop/assets/7231413/5de6d5cd-8195-4c11-aba0-86c392a7b390">

3. I have no idea how/whether I can test audio output in Telegram or call. 

### Expected behaviour

Audio output should work, also some settings for the output should be provided. 

### Actual behaviour

No audio output, no settings. 

### Operating system

MacOS Ventura 13.5.1 (22G90)

### Version of Telegram Desktop

10.0.4.250868 AppStore

### Installation source

Mac App Store

**Comment by john-preston** [comment]
Your report is about macOS native app. This repository is about Telegram Desktop app, you can try Telegram Desktop from https://desktop.telegram.org
