### ISSUE TITLE
Problem when searching for a contact name starting with a non-letter

### ISSUE THREAD

**Issue by offstate** [telegramdesktop/tdesktop#26783]
### Steps to reproduce

Have some contact starting with #, % or something like that  
For example  #Debugger John
As a human, I believe I can find this contact by query 'debug', but I get nothing in result

### Expected behaviour

Telegram should find words starting with non-letter character

### Actual behaviour

You get nothing unless you type exactly with the right character ('#debug')

### Operating system

ubuntu 20.04, KDE neon User - 5.26, Plasma Shell

### Version of Telegram Desktop

4.9.5

### Installation source

Snap

**Comment by ilya-fedin** [comment]
The search is server side
