### ISSUE TITLE
 The url button in the message sent by the bot cannot open the webapp

### ISSUE THREAD

**Issue by FeiFanLiang** [telegramdesktop/tdesktop#26786]
### Steps to reproduce

If the URL button sent using the bot API is a webapp link, the client will prompt that the robot cannot be added to the attachment menu. There was no problem in doing so in previous versions. I want to confirm whether this is a bug or a new feature. ?
1.
Use a webapp link in the url button of the message, like https://t.me/botusername/appname?startapp=command mentioned in the official documentation
2.Click this button, the client prompts that this robot cannot be added to the attachment menu

### Expected behaviour

Open a webapp like clicking the webapp link directly in the message

### Actual behaviour

This operation was intercepted by the client

### Operating system

win10

### Version of Telegram Desktop

4.9.6 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
This will be fixed in the upcoming 4.9.7. Thanks for your report!
