### ISSUE TITLE
Flatpak crash

### ISSUE THREAD

**Issue by Martinligabue** [telegramdesktop/tdesktop#26794]
### Steps to reproduce

open a media (video/gif)

### Expected behaviour

the opening of the file

### Actual behaviour

crash

### Operating system

Flatpak

### Version of Telegram Desktop

4.9.7

### Installation source

Flatpak

### Crash ID

none provided

### Logs

```shell
nothing abnormal recorded, the app just closes itself
```

**Comment by meklonets** [comment]
I confirm it with official telegram package as well.

**Comment by ilya-fedin** [comment]
Perhaps a crash in system OpenGL drivers, try to disable OpenGL in Telegram settings

**Comment by meklonets** [comment]
> Perhaps a crash in system OpenGL drivers, try to disable OpenGL in Telegram settings

It was disabled already. I've just disabled hardware acceleration as well now, didn't help. 
Looks like something wrong with wayland stack (or qt i don't know).
Start telegram app:
```
$telegram-desktop1 --many -workdir /home/v/.local/share/TelegramDesktop/.0506/
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter

(Telegram:11173): Gtk-WARNING **: 15:29:50.285: Theme parsing error: <data>:1:0: Expected a valid selector
```
Here I click on media on a chat and here the output of a crash:

`The Wayland connection experienced a fatal error: Protocol error`

(btw ArchLinux, swaywm, official binary telegram packacge).

**Comment by Martinligabue** [comment]
I was on Flatpak, the crash did not appear with the Fedora repo package. I had acceleration enabled in both. I have now reinstalled telegram Flatpak, and it did not crash, tested with opengl enabled and disabled. I'm not sure what this means.

**Comment by ilya-fedin** [comment]
Yeah, apparently some incompatibility between Qt and sway. If it only wrote what kind of protocol error happens...

**Comment by EndrII** [comment]
I think it is same issue like [this](https://github.com/telegramdesktop/tdesktop/issues/26795) 
```
The Wayland connection experienced a fatal error: Protocol error
```

**Comment by ilya-fedin** [comment]
And I guess both those issues are dups of #26784
