### ISSUE TITLE
bug report test 2

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#26792]
### Steps to reproduce

something
something else
something more		

### Expected behaviour

it must work

### Actual behaviour

it doesn't work

### Operating system

win10

### Version of Telegram Desktop

4.9.6 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
preston is faster than you
![изображение](https://github.com/telegramdesktop/tdesktop/assets/17829319/03d13d31-a972-4e02-923a-8bdc036d123c)
![изображение](https://github.com/telegramdesktop/tdesktop/assets/17829319/9b5c6155-ec86-43cc-a274-f2d14ac85d38)
