### ISSUE TITLE
Can not join a call with 1000+ participants

### ISSUE THREAD

**Issue by NickSun** [telegramdesktop/tdesktop#26807]
### Steps to reproduce

1. Run the application on any platform (iOS, Win, Unbuntu)
2. Join a call with 1000+ participants

### Expected behaviour

Successful connection to a call

### Actual behaviour

The application is trying to connect but has no luck

### Operating system

Ubuntu, Windows, iOS

### Version of Telegram Desktop

4.9.8

### Installation source

Static binary from official website

**Comment by Djritz44** [comment]
There was no error
