### ISSUE TITLE
Segmentation fault when closing call window on Wayland

### ISSUE THREAD

**Issue by aolo2** [telegramdesktop/tdesktop#26806]
### Steps to reproduce

1. Open any dialog and press 📞 icon to open call window
2. Close the call window by pressing X or "Cancel"

### Expected behaviour

The window should close

### Actual behaviour

Telegram crashed with Segmentation Fault in
`#0  0x00007ffff61cd505 in wl_proxy_marshal () at /lib/x86_64-linux-gnu/libwayland-client.so.0` (can't give full stack obviously)

### Operating system

Debian Sid, Wayland (sway)

### Version of Telegram Desktop

4.9.8

### Installation source

Static binary from official website

### Crash ID

8071aaa4-c810-4332-bf34de9c-98323f86

**Comment by aolo2** [comment]
Shall I do a debug build to get a proper callstack? If so, how do I do that?

**Comment by ilya-fedin** [comment]
@john-preston has debug symbols and should be able to retrieve it from your crash dump under the crash id if you have sent it

**Comment by ilya-fedin** [comment]
I have a feel this can fix, though
https://github.com/desktop-app/lib_base/pull/215

**Comment by NTMan** [comment]
Please look my crash ID I have same experience 097cf5c4-365d-4072-44a8bc85-581dec4c

**Comment by aolo2** [comment]
> I have a feel this can fix that, though [desktop-app/lib_base#215](https://github.com/desktop-app/lib_base/pull/215)

Yes, with this commit everything works as expected for me.

**Comment by aolo2** [comment]
Since this is kind of an important issue, and it is now closed, can you please clarify: this fix will land in the next release?

**Comment by ilya-fedin** [comment]
yes
