### ISSUE TITLE
Why are you pushing out so many updates for 4.9.8, with no changelog?

### ISSUE THREAD

**Issue by superclarkk** [telegramdesktop/tdesktop#26804]
### Steps to reproduce

It's becoming very concerning that every few days I have to update my Telegram Desktop client with another 4.9.8. There's no changelog. The Telegram update chat (mobile number 42777) shows on restart, but isn't updated.

Could someone explain? I've been using Telegram for many years, and never noticed this, or at least the high frequency of updates for the same version.

I'm on Linux. A friend, who runs it on Windows, mentioned that he was concerned too, so it prompted me to raise a ticket.

Other than that, Telegrams great, obviously.  However, this particular isn't good from a user perspective.

Thanks in advance.

### Expected behaviour

Each upgrade should have it's own unique version number. A changelog should always be provided (not just, "Bugs and fixes"). 

### Actual behaviour

Frequent updates for the same version, on Linux and Windows - two completely unconnected, unrelated systems.

### Operating system

Windows and Linux

### Version of Telegram Desktop

4.9.8

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> It's becoming very concerning that every few days I have to update my Telegram Desktop client with another 4.9.8.

> Each upgrade should have it's own unique version number.

4.9.8 is released only today, apparently your memory is not good?

**Comment by ilya-fedin** [comment]
![изображение](https://github.com/telegramdesktop/tdesktop/assets/17829319/7a2694d3-cf97-47a7-9b42-5a6ab15d4581)

**Comment by ilya-fedin** [comment]
I can believe there are versions without a changelog but I can't believe that version numbers don't change and especially I can't believe in multiple days old 4.9.8 given that it was made multiple hours ago only.

**Comment by AiQuant-Finance** [comment]
Official release package may have been 4 hours ago but there was prior updates pushed and not recorded in the change log over the last 14 days. 

What Superclark is saying is correct.

**Comment by ilya-fedin** [comment]
It's not only official release package, the commit raising the version was made 15 hours ago: https://github.com/telegramdesktop/tdesktop/commit/76ac6c3be76665eb17e86f1d91943f3dc7bb534b

And then you can't use that commit if you don't build tdesktop yourself. If you use the release package, then you were able to install it only since 4 hours ago.

It's impossible that you used 4.9.8 multiple days ago, it didn't even exist at that point. You're likely misremember something.

**Comment by john-preston** [comment]
@AiQuant-Finance There were a lot of 4.9.* releases with bugfixes and improvements for web apps. This is going to be the last version working on old Linux systems and macos 10.12, so I tried to fit all the serious fixes there. I hope the update series is finished now and next ones won't be coming so frequently without changelogs.

**Comment by superclarkk** [comment]
> @AiQuant-Finance There were a lot of 4.9.* releases with bugfixes and improvements for web apps. This is going to be the last version working on old Linux systems and macos 10.12, so I tried to fit all the serious fixes there. I hope the update series is finished now and next ones won't be coming so frequently without changelogs.

Thank you for a sensible answer, John. I'm sure all devs were aware what I was referring to. The purpose of giving feedback is to improve the product. If they respond like, ilya-fedin, then users just won't bother.

I may have made a mistake about the exact version number, but you have to understand that it's very confusing when the Telegram notifications are not correct when there's an update, and there's no changelog.

Glad to hear that it's going to be better going forward. As I said, apart from this, it's an amazing product, and I appreciate everyone's hard work in genuinely making a positive difference in people's lives.
