### ISSUE TITLE
telegram-desktop on Fedora closing when trying to initiiate a call.

### ISSUE THREAD

**Issue by silentresearch** [telegramdesktop/tdesktop#26803]
### Steps to reproduce

Open telegram 
Click the call icon to start a voice call.
- app closes - 

### Expected behaviour

Should initiate a call and not crash

### Actual behaviour

app closes - no call 

### Operating system

Fedora 38

### Version of Telegram Desktop

4.9.7

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by silentresearch** [comment]
how to do that? Can't find a beta option in settings...

**Comment by danielleontiev** [comment]
I experience the crash on Arch Linux when I click on a video in channel or private chat

I use

```
Telegram Desktop                  org.telegram.desktop                             4.9.7    stable      system
```

from `flatpak`.

The last thing that appears in the terminal if running directly using

```sh
flatpak run org.telegram.desktop
```

is

```
The Wayland connection experienced a fatal error: Protocol error
```

I use GNOME Shell 44.4 on Wayland.

I've not found the way to submit Crash ID, if you provide more detailed instructions on how to do it I will submit the error

**Comment by ilya-fedin** [comment]
#26784

**Comment by silentresearch** [comment]
that's not an acceptable fix. It causes massive issues with my display.
