### ISSUE TITLE
How to close media player ?!

### ISSUE THREAD

**Issue by mojtabye** [telegramdesktop/tdesktop#2680]
Hi There ! ,
The new media player is great ! , but how to close it completely to prevent conflict with iTunes when we are not using telegram ?!

![](https://cloud.githubusercontent.com/assets/13944347/20754281/75f6091c-b71f-11e6-8425-861a02a3cfa1.png)

**Comment by Kondra007** [comment]
Hover mouse over that "play" icon and you'll see *another* player. In top right corner of that *another* hover your mouse over "time passed" timer and you'll see "close" button. 

![image](https://cloud.githubusercontent.com/assets/2780044/20755382/d52e0ede-b71f-11e6-9fa1-f0b500ce140d.png)

**Comment by mojtabye** [comment]
Hmm , Thanks , UX Issues :D , Hard To Understand !
