### ISSUE TITLE
Telegram desktop is updating release even it is disabled the automatic update

### ISSUE THREAD

**Issue by macbeto** [telegramdesktop/tdesktop#26811]
### Steps to reproduce

I am using the one in the .tar.xz version for linux, which has Telegram and Updater files inside.
I have disabled the Automatic Updates in the setup.
But when there is a new release, when I launch telegram desktop I get a new one window saying is downloading a new versión. If I cancel it doesn't matter because the next time I launch again Telegram the new release is  installed.
I would like to know how to update it manually or not update. 

### Expected behaviour

Not update the application automatically when the check box is unmarked

### Actual behaviour

The application is updating automatically even it is uncheck

### Operating system

Linux Mint 20.3

### Version of Telegram Desktop

4.9.8 right now

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/26078#issuecomment-1479356243
