### ISSUE TITLE
Unable to select multiple files to send

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#26815]
### Steps to reproduce

This used to work as expected until few days ago.

Say you want to send a bunch of photos:

1. Click on the paperclip icon to send some 
2. The file selection window pops up
3. Click on an image file to select it. ctrl+click on another file to select multiple files, and so on
4. When you are done with the selection, click the "Open" button or hit Enter

### Expected behaviour

You should be able to do that.

### Actual behaviour

As soon as you click on the very first file, the file selection window closes as if you had already clicked Open. Basically you can only select one file at a time. To select more, you need to click Add, but then again, only one at a time.

Even if you ctrl+click on the first file (which was never needed), the same happens.

### Operating system

Manjaro Linux

### Version of Telegram Desktop

4.8.4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
try 4.9.8

**Comment by php4fan** [comment]
> try 4.9.8

![TG](https://github.com/telegramdesktop/tdesktop/assets/13969584/e8349f34-9929-4227-aa94-7a56d8afff05)

Much better!

**Comment by ilya-fedin** [comment]
@php4fan please provide more details, it's not clear when your screenshot happens

**Comment by Aokromes** [comment]
tested on manjaro, non-snap, non-flakpak i can run it without problem.

**Comment by php4fan** [comment]
> @php4fan please provide more details, it's not clear when your screenshot happens

Every time I try to start Telegram Desktop

**Comment by ilya-fedin** [comment]
@php4fan upload the newest dumo from tdesktop data directory
