### ISSUE TITLE
Adding Amharic Language support on Telegram Desktop.

### ISSUE THREAD

**Issue by AB-Solution** [telegramdesktop/tdesktop#26813]
### Steps to reproduce

Adding Amharic Language support on Telegram Desktop.

### Expected behaviour

Reading and Writing Amharic Language/Font should be work.

### Actual behaviour

Telegram Desktop Unsupported Amharic Language on Every Client after 4.3 Updates till Now.

Latest updates of Telegram Desktop is so much good and has many features but losses supporting Amharic language on Windows and macOS platforms I was waiting 2 feature updates hoping it works again but no luck. Is there any problem? or Can you make it work again if its possible?

### Operating system

macOS HighSierra, 10.13.6

### Version of Telegram Desktop

4.9.8

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can you better explain what is broken? It's not clear from your report.

**Comment by Aokromes** [comment]
> Can you better explain what is broken? It's not clear from your report.

i think he means amharic client language.

**Comment by ilya-fedin** [comment]
> i think he means amharic client language.

I don't quite understand what you wanted to say :thinking:

**Comment by AB-Solution** [comment]
> Can you better explain what is broken? It's not clear from your report.

Telegram official client app for macOS is not supporting amharic language or the font. can you please checkout image attached below.

Thank you for your cooperation.

![Screen Shot 2023-09-20 at 11 34 46 AM](https://github.com/telegramdesktop/tdesktop/assets/33054939/333ffd2d-bc03-4271-9bf2-d344150b4246)

**Comment by ilya-fedin** [comment]
@AB-Solution does the same happen on Windows? Does it work in other applications?

**Comment by AB-Solution** [comment]
> @AB-Solution does the same happen on Windows? Does it work in other applications?

Thank you for your quick reply, Recently i was testing on other platforms and OS's after the test its working perfectly on iOS (iPhone 7) and Windows 10 Pro (Latest Build). I can read and write Amharic Language on those platform Telegram client.

Even today i have downloaded Telegram Lite for macOS from AppStore and its the same as other versions.

**Comment by ilya-fedin** [comment]
> Even today i have downloaded Telegram Lite for macOS from AppStore and its the same as other versions.

I mean, does it work in other apps rather than Telegram? I feel like your system is incapable to display Amharic characters.

> Recently i was testing on other platforms and OS's after the test its working perfectly on iOS (iPhone 7) and Windows 10 Pro (Latest Build). I can read and write Amharic Language on those platform Telegram client.

But you say in the issue:

> but losses supporting Amharic language on **Windows** and macOS platform

What is the truth? :thinking:

**Comment by Aokromes** [comment]
https://i.imgur.com/KETbURC.png i cannot reproduce on windows.

**Comment by Aokromes** [comment]
https://t.me/TelegramDesktopTalk/106029 also cannot be reproduced by rico on telegram desktop 4.9.7 and macos 13.5.

**Comment by AB-Solution** [comment]
> > Even today i have downloaded Telegram Lite for macOS from AppStore and its the same as other versions.
> 
> I mean, does it work in other apps rather than Telegram? I feel like your system is incapable to display Amharic characters.
> 
> > Recently i was testing on other platforms and OS's after the test its working perfectly on iOS (iPhone 7) and Windows 10 Pro (Latest Build). I can read and write Amharic Language on those platform Telegram client.
> 
> But you say in the issue:
> 
> > but losses supporting Amharic language on **Windows** and macOS platform
> 
> What is the truth? 🤔

Thank you for your help and sorry for the mistake on the report. I didn't meant too

**Comment by AB-Solution** [comment]
> https://t.me/TelegramDesktopTalk/106029 also cannot be reproduced by rico on telegram desktop 4.9.7 and macos 13.5. nor 4.9.9 on 12.6.

Still there is no solution beside me.

Here is the screenshot of Telegram Web, from Chrome Browser on macOS 
![Screen Shot 2023-09-22 at 10 45 59 AM](https://github.com/telegramdesktop/tdesktop/assets/33054939/45e1c743-e875-44ad-8393-18189b5a8f2b)

**Comment by ilya-fedin** [comment]
Does Amharic work in system apps? Not a web browser.

**Comment by ilya-fedin** [comment]
Web sites can provide custom fonts

**Comment by AB-Solution** [comment]
Hello Everybody,
Good evening/morning.

I have an update regarding the error of Telegram Client Amharic character support but i after downloading Telegram messenger client from app store i can read Amharic character on the macOS Telegram messenger. 

checkout screenshot below
![Screen Shot 2023-09-22 at 10 45 59 AM](https://github.com/telegramdesktop/tdesktop/assets/33054939/08e3549d-11cd-473b-b6f2-249d6d180fca)

**Comment by ilya-fedin** [comment]
it's another client, called Telegram for macOS. This client is Telegram Desktop. So what about my request to check with system app?

**Comment by AB-Solution** [comment]
> Does Amharic work in system apps? Not a web browser.

Yes it does.
![Screen Shot 2023-09-22 at 11 03 49 AM](https://github.com/telegramdesktop/tdesktop/assets/33054939/39dff8c2-c35c-472b-be6e-1ba35d73c373)

**Comment by ilya-fedin** [comment]
Apparently it's a Qt bug then, Qt is very bad at fonts... What also means the issue is unfixable.

**Comment by AB-Solution** [comment]
> Apparently it's a Qt bug then, Qt is very bad at fonts... What also means the issue is unfixable.

Ohh.. sorry to hear that, this means for all Telegram macOS users from Ethiopia?

**Comment by ilya-fedin** [comment]
Given the input from @Aokromes, it's not reproducible on modern macOS versions. So I guess not.

**Comment by AB-Solution** [comment]
Hmm.. that's not good man but is it safe to use Telegram Messenger Client from App Store?

**Comment by ilya-fedin** [comment]
it's the app from https://macos.temelgram.org

**Comment by AB-Solution** [comment]
It is from this link >> https://apps.apple.com/us/app/telegram/id747648890?mt=12
