### ISSUE TITLE
Telegram crashes after clicking story circle

### ISSUE THREAD

**Issue by TheUnholyTim** [telegramdesktop/tdesktop#26819]
### Steps to reproduce

 click any story on telegram

### Expected behaviour

Show the story from that profile

### Actual behaviour

it just crashes without spitting any information

### Operating system

Debian GNU/Linux 11 (bullseye) x86_64

### Version of Telegram Desktop

4.9.9

### Installation source

Static binary from official website

### Logs

```shell
[1]    4323 illegal hardware instruction
```

**Comment by ilya-fedin** [comment]
What's the first version with the bug?

**Comment by ilya-fedin** [comment]
Have you tried to get crash ID as instructed in the issue template?
