### ISSUE TITLE
Telegram-desktop slows down entire DE after last updates.

### ISSUE THREAD

**Issue by savelmtr** [telegramdesktop/tdesktop#26812]
### Steps to reproduce

1. Get Ubuntu 16.04
2. Download last Telegram desktop build.
3. Try to fire a reaction to a post, to listen audio-message or to watch video.
4. ...
5. PROFIT

### Expected behaviour

Some releases ago the messager worked fast and smooth. 

### Actual behaviour

Now animations come with freezes and in some cases I get total  freezing of my DE. It's not the best practice, I think.

### Operating system

Ubuntu 16.04

### Version of Telegram Desktop

4.9.8

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@savelmtr There is log of releases:

https://github.com/telegramdesktop/tdesktop/releases

You can:
1. pick a version (like 4.9.1 or 4.8.1 or smth)
2. download Linux x64 binary asset of that version
3. Unpack it to some separate folder, like ~/test_4_9_1
4. Create a "TelegramForcePortable" near the binary, so you'll have "~/test_4_9_1/Telegram" binary and "~/test_4_9_1/TelegramForcePortable" folder
5. Launch it, press Start Messaging, open Settings > Advanced and disable Automatic Updates (in the bottom, I think it'll already start loading an update, but you can turn it off)
6. Authorize there and test how it works

That way you can check old versions on your current system and bisect the versions to find exactly which version (including public beta releases) started to work slowly. But I'm afraid really something different is happening, maybe something changed in the system, and now all versions will work the same way. At least we can check.

**Comment by savelmtr** [comment]
> @savelmtr There is log of releases:
Thanx, John! I've already rollbacks to 4.9.1 and the app works like a charm. So the problem come with new releases, and that's why I created this issue. I hope, we'll find the cause that provokes this behaviour.

**Comment by Aokromes** [comment]
he wants to test every 4.9.x version to check when your problem apears.

**Comment by ilya-fedin** [comment]
not that he just wants, he asks @savelmtr to do that.

**Comment by savelmtr** [comment]
@Aokromes , оk, I'll do it today and let you know which version is the milestone.

**Comment by savelmtr** [comment]
OK, @Aokromes, I've figured out that the problematic version is 4.9.4; I didn't test 4.9.3 cause there is no build and I have not very much experience in building C++ apps (I'm just a python dev).

**Comment by ilya-fedin** [comment]
So 4.9.2 is ok?

**Comment by ilya-fedin** [comment]
Oh, sorry but your system was deprecated in 4.10.0 and no updates will arrive anymore. If you can't reproduce this on a supported system, the issue will be closed.

**Comment by savelmtr** [comment]
> So 4.9.2 is ok?

Yeah, 4.9.2 is ok. I'll plan to use it cause I don't know when I'll decide to upgrade.
