### ISSUE TITLE
Telegram Desktop (Windows) has no sound

### ISSUE THREAD

**Issue by sepehrland** [telegramdesktop/tdesktop#26821]
### Steps to reproduce

I have not any issue in other apps, my telegram is up to dated, Version 4.9.9 X64, I check sound setting in telegram and it's correct. I uninstalled and installed it again and it's not help out. No matter I play voice or video.

### Expected behaviour

playing sound!

### Actual behaviour

sound is muted.

### Operating system

windows 10 home

### Version of Telegram Desktop

4.9.9 X64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://t.me/roscosmos_gk/10911 works for me

**Comment by vadimuz** [comment]
The same issue on macOS. There is no sound in the Telegram desktop application. I tried to re-install... it did not help.
