### ISSUE TITLE
Ability to group/tag chats by context. 

### ISSUE THREAD

**Issue by Liudvikas** [telegramdesktop/tdesktop#2682]
Currently I have many chats from different contexts:
* Work related (8 different groups and many direct chats);
* Home related (6 different groups);
* Hobby/Projects (16 different groups, multiple groups per projects);

Search is great! But it is difficult to find related chats, especially less used ones. Ability to create a tree of chats or to tag them (on client side, not in chat topic) would really help!

Thank you

**Comment by stek29** [comment]
> Search is great!

Well, I'm happy you can use it at least in Telegram.
Now please start using it on GitHub too (#2642).

**Comment by Liudvikas** [comment]
Thanks for your lovely response! Enjoy your day too.

**Comment by auchri** [comment]
@stek29 Why do you 👎 your own comment? 😄
