### ISSUE TITLE
Moving typing indicator to the bottom of the screen, similar to Discord's location

### ISSUE THREAD

**Issue by KeplerDeveloper** [telegramdesktop/tdesktop#26827]
### Is your feature request related to a problem?

Easier on the the eyes to look at the lower part of the screen for typing indicator.

### Describe the solution you'd like

Just add an option in settings, or hard coded in, to change the location of the typing indicator. I think it would work best to move the location as that of Discord's, which is right above the keyboard.

### Describe alternatives you've considered

N/A

**Comment by ilya-fedin** [comment]
#271
