### ISSUE TITLE
Add ability to disable text format triggers

### ISSUE THREAD

**Issue by Idran** [telegramdesktop/tdesktop#2683]
Feature request: some option to disable character triggers like `*bold*` or `_italic_`, either by a client settings toggle or possibly by the use of an escape character like backslash. Minor issue, but I use asterisks in text chat for purposes other than formatting as it stands, and it's always frustrating in any chat client when this gets implemented with no way to work around it.

**Comment by john-preston** [comment]
@Idran There is no such formatting in Telegram Desktop. Perhaps you've used some other version.

**Comment by stek29** [comment]
@Idran Maybe you're talking about webogram?

**Comment by Idran** [comment]
Yep, I screwed up, mixed up which project this was. Haha, sorry, this can be closed.

**Comment by stek29** [comment]
`**bold**` and `__itailc__` were added to TDesktop.

**Comment by Lonami** [comment]
Rather than disable, I would say allow escaping. Probably with `\` (backslash), as it's the most well known character for this stuff.

**Comment by VictorKrasnov** [comment]
_\__ or *\** doesn't work. Is it possible to send bold * symbol or italic _ symbol?

**Comment by ozbek** [comment]
@VictorKrasnov, these are working:

bold asterisk: `*****`
italic underscore: `_____` (though, frankly, I don't see how underscore can be italic:)

**Comment by Aokromes** [comment]
still wanted.

**Comment by Lonami** [comment]
Right clicking on the send button now allows to schedule it. Maybe that same context menu can be reused to "Send without formatting"?

Also, while not as pretty, using `pre` blocks in the entire message prevents all formatting (<kbd>Ctrl+A</kbd> to select all, <kbd>Ctrl+Shift+M</kbd> for monospace).
