### ISSUE TITLE
MacOS - Text Replacement feature doen't work in the message input field

### ISSUE THREAD

**Issue by butaji** [telegramdesktop/tdesktop#26835]
### Steps to reproduce

Start typing in the chat on MacOS shortkey for the Text Replacement, for instance "omw"

### Expected behaviour

Expected to get the OS-native suggestion to replace it with "On my way!"

### Actual behaviour

Text just stays as "omw"

### Operating system

MacOS 13.5.2

### Version of Telegram Desktop

4.9.7

### Installation source

Mac App Store

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/issues/26272#issuecomment-1538449699

**Comment by butaji** [comment]
Looks like the Telegram app is incompatible, according to the link shared.  So, no way to have it available?

(Attached menu from the input dialog)

<img width="421" alt="image" src="https://github.com/telegramdesktop/tdesktop/assets/94799/7bc40fac-3300-4d82-a3b9-8e65926f4e06">

**Comment by ilya-fedin** [comment]
Rather than requesting it for Telegram for macOS or trying [Telegram Electron](https://github.com/Ajaxy/telegram-tt/releases/latest), no.
