### ISSUE TITLE
Can assign roles to group participants and limit access to sub-groups such as the Discord application.

### ISSUE THREAD

**Issue by daffaharizal** [telegramdesktop/tdesktop#26837]
### Is your feature request related to a problem?

Yes, I can't limit group participants to important sub-groups. I want only some group participants to be able to access it.

### Describe the solution you'd like

Can assign roles to group participants, like those in the Discord application.

### Describe alternatives you've considered

The admin or group owner can create and assign roles

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by daffaharizaleid** [comment]
> platform wide bugs / requests belongs to https://bugs.telegram.org/

what this problem is solved? how do I use it and the steps?
