### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by Nuruddinjr** [telegramdesktop/tdesktop#2684]
I don't know what 
### Configuration
**Sierra 10.12.1 (16B2555)**

Date/Time:             2016-12-02 09:53:47.858 +0500
OS Version:            Mac OS X 10.12.1 (16B2555)
Report Version:        12

**Version of Telegram Desktop:**
Version 2.28.51242 
### Logs
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'TLError', reason: 'constructor not found 0'
abort() called

**Comment by auchri** [comment]
That's not Telegram Desktop: https://github.com/overtake/telegram

You can try Telegram Desktop from https://desktop.telegram.org
