### ISSUE TITLE
Voice Messages Don't Respect Call Settings

### ISSUE THREAD

**Issue by Fox-McCloud** [telegramdesktop/tdesktop#26857]
### Steps to reproduce

1. Set a mic input to something other than windows default.
2. Make a Telegram call and note that it is properly using the mic you selected
3. Send a voice mesage; note that it's using the mic that is windows default as opposed to the one in call settings

### Expected behaviour

I expect that the settings under `Call Settings` would apply to voice messages as well as actual calls.

### Actual behaviour

Voice messages default to whatever windows has as the default input.

### Operating system

Windows 11

### Version of Telegram Desktop

4.10x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
These setting are only for calls, that's why they're named "Call Settings" after all

**Comment by Fox-McCloud** [comment]
If that's well and truly the case, then there needs to be a way to configure "Voice Settings", as well.

It's pretty understood that with most applications that have a mic input and output, that the "call" settings usually apply to everything under that application.

**Comment by ilya-fedin** [comment]
Yes, there are already a feature request (if not multiple) in the issue tracker, please use search
