### ISSUE TITLE
[FeatureReq] Customize notification settings for Chats/Groups/Channels seperately

### ISSUE THREAD

**Issue by T3rminat0r** [telegramdesktop/tdesktop#26859]
### Is your feature request related to a problem?

I'd like to define specifc rules for specific Chats/Groups/Channels, i.e. don't show text/sender if there's a new message in some_secret_chat, but show sender/text for normal groups/channels....

### Describe the solution you'd like

I'd love to see customization for displaying text&sender, additonally to the current global setting, as well on the level of "all chats"/"all groups"/"all channels" and then on the "exception" level, for specific, single chats/groups/channels, as well.

### Describe alternatives you've considered

There is no alternative, apart from globally disabling the preview in the notificaiton, which is kind of a harsh "solution", if at all a solution...

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
