### ISSUE TITLE
stories freeze constantly

### ISSUE THREAD

**Issue by Nammehub** [telegramdesktop/tdesktop#26861]
please, watch the GIF
Story doesn't play
Then Windows reports that the program is not responding

Windows 10 x64
v4.10 x64
![](https://i.imgur.com/imZxfsg.gif)

**Comment by Aokromes** [comment]
plz, open task manager when telegram freezes, then right click over telegram -> create dump and send to https://t.me/preston

**Comment by john-preston** [comment]
🤔 What if you disable hardware accelerated video decoding in Settings > Advanced? In the dump at least I see one thread in ID3D11VideoContext_SubmitDecoderBuffers, while other threads are waiting for something.
