### ISSUE TITLE
AppData file

### ISSUE THREAD

**Issue by Victor239** [telegramdesktop/tdesktop#26865]
### Is your feature request related to a problem?

Flathub and other packagers don't have changelogs.

### Describe the solution you'd like

Changelogs can be displayed on Flathub and within distro app updaters, all that's needed is an `.appdata`/[.metainfo.xml](https://docs.flatpak.org/en/latest/conventions.html#appdata-files) file. 

See these examples of another app's [appdata.xml](https://github.com/flathub/io.github.trigg.discover_overlay/blob/master/io.github.trigg.discover_overlay.appdata.xml), and how their changelog is [displayed on Flathub](https://flathub.org/en-GB/apps/io.github.trigg.discover_overlay).

### Describe alternatives you've considered

N/A

**Comment by ilya-fedin** [comment]
There's already a metainfo.xml file in the repo, see the lib/xdg folder

**Comment by ilya-fedin** [comment]
I see flathub has the changelog:
![изображение](https://github.com/telegramdesktop/tdesktop/assets/17829319/51e56a9b-6b5e-4723-8ff3-86e5d7d2ccf7)

**Comment by Victor239** [comment]
Odd, when I updated the app via KDE Discover earlier today I didn't see the changelog for this but I did see others. Maybe it'll appear next update.
