### ISSUE TITLE
telegram is crashed when open a link 

### ISSUE THREAD

**Issue by dr-r00t3r** [telegramdesktop/tdesktop#26869]
### Steps to reproduce

1. click the link on the channel.
2. open the link on the browser
3. Telegram dies.

### Expected behaviour

usually is to open the link in the browser and telegram should be run.

### Actual behaviour
Crash! This happens since Version 4.10.2
I use journalctl to track exception 
you can see more information in this picture.
![telegram_crash_screen](https://github.com/telegramdesktop/tdesktop/assets/27568374/6579d6ea-dded-4807-914a-a281315d45ef)

### Operating system

Linux  6.5.3-arch1 - x86_64 GNU/Linux

### Version of Telegram Desktop

4.10.2

### Installation source

Static binary from official website

### Logs
Sep 29 20:20:53 BlackHat systemd-coredump[233251]: [🡕] Process 209144 (Telegram) of user 1001 dumped core.                                          
         Stack trace of thread 209144:
         #0  0x000056401aa4c6a1 n/a (/home/arch/Telegram/Telegram + 0x60906a1)
         #1  0x000056401aa4cb9f n/a (/home/arch/Telegram/Telegram + 0x6090b9f)
         #2  0x000056401a10d024 n/a (/home/arch/Telegram/Telegram + 0x5751024)
         #3  0x000056401a18e188 n/a (/home/arch/Telegram/Telegram + 0x57d2188)
         #4  0x000056401ac4ebb7 n/a (/home/arch/Telegram/Telegram + 0x6292bb7)
         #5  0x0000564016994828 n/a (/home/arch/Telegram/Telegram + 0x1fd8828)
         #6  0x000056401603e9e1 n/a (/home/arch/Telegram/Telegram + 0x16829e1)
         #7  0x0000564017f4dc68 n/a (/home/arch/Telegram/Telegram + 0x3591c68)
         #8  0x0000564015ae377d n/a (/home/arch/Telegram/Telegram + 0x112777d)
         #9  0x0000564015b4fb41 n/a (/home/arch/Telegram/Telegram + 0x1193b41)
         #10 0x0000564016997e33 n/a (/home/arch/Telegram/Telegram + 0x1fdbe33)
         #11 0x000056401a2cce72 n/a (/home/arch/Telegram/Telegram + 0x5910e72)
         #12 0x000056401a2cd549 n/a (/home/arch/Telegram/Telegram + 0x5911549)
         #13 0x000056401a423779 n/a (/home/arch/Telegram/Telegram + 0x5a67779)
         #14 0x00007f6e98a52f19 n/a (libglib-2.0.so.0 + 0x59f19)
         #15 0x00007f6e98ab12b7 n/a (libglib-2.0.so.0 + 0xb82b7)
         #16 0x00007f6e98a51112 g_main_context_iteration (libglib-2.0.so.0 + 0x58112)
         #17 0x000056401a423c05 n/a (/home/arch/Telegram/Telegram + 0x5a67c05)
         #18 0x000056401a2cdaec n/a (/home/arch/Telegram/Telegram + 0x5911aec)
         #19 0x00005640169d1384 n/a (/home/arch/Telegram/Telegram + 0x2015384)
         #20 0x00005640169d3676 n/a (/home/arch/Telegram/Telegram + 0x2017676)
         #21 0x00005640169d531a n/a (/home/arch/Telegram/Telegram + 0x201931a)
         #22 0x00005640159a9c99 n/a (/home/arch/Telegram/Telegram + 0xfedc99)
         #23 0x00007f6e98627cd0 n/a (libc.so.6 + 0x27cd0)
         #24 0x00007f6e98627d8a __libc_start_main (libc.so.6 + 0x27d8a)
         #25 0x0000564015a2dc6e n/a (/home/arch/Telegram/Telegram + 0x1071c6e)
         ELF object binary architecture: AMD x86-64

**Comment by ilya-fedin** [comment]
> ### Crash ID
> 
> _No response_

You must provide this. The issue template says how to.

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by dr-r00t3r** [comment]
I found this is in the path /home/arch/.local/share/TelegramDesktop/tdata/dumps/c8310530-5e01-499e-ff6ce59f-c7d7579d.dmp
I don't know ,it's the correct crash ID or not

**Comment by ilya-fedin** [comment]
@dr-r00t3r have you sent the dump via crash reporter? If not then the ID is useless... Have you read the issue template with instruction? If not then please read, it has a more detailed explanation.

**Comment by alexey-medvedchikov** [comment]
I can reproduce the issue in 100% of cases. And I'm trying to do what you describe here, but the crash reported doesn't appear. I did exactly what is described:
* Enable beta
* Restart Telegram
* Reproduce an issue
* Checked the folder with dump, it's there
* Started Telegram, nothing happens, no ID is shown in console or anywhere else.

Is there a way to post dump directly via wget/curl?

**Comment by ilya-fedin** [comment]
maybe it's an older dump or the dump of zero size? :thinking:

**Comment by ilya-fedin** [comment]
I want to also raise a concern that the issue has poor information in operating system field. I can't reproduce that on my Linux system.

**Comment by scoaste** [comment]
I can confirm that, in the Linux client version 4.10.2, every time I click on a link it crashes.  I did send the crash report.

**Comment by ilya-fedin** [comment]
The information that you just sent a crash report is not enough, a crash id of the sent report is required.

**Comment by scoaste** [comment]
> The information that you just sent a crash report is not enough, a crash id of the sent report is required. Note that each time a new ID is generated.

Would that be 63ab5ca8-5f9c-11ee-87df-fa163ec8ca8c ?

**Comment by john-preston** [comment]
Both were not uploaded :( Can you upload them here in .zip? Or send them to me at https://t.me/preston

**Comment by dr-r00t3r** [comment]
the crash id c8310530-5e01-499e-ff6ce59f-c7d7579d file is upload !
[telegram_dump.zip](https://github.com/telegramdesktop/tdesktop/files/12775571/telegram_dump.zip)

**Comment by ilya-fedin** [comment]
Accroding to the crash ID from #26872, the crash happens inside Qt's QProcess::startDetached API
```
Thread 0 (crashed)
 0  Telegram!QProcessPrivate::startDetached(long long*) [clone .constprop.0] + 0x391
    rax = 0x00007f26277ae6c8   rdx = 0x0000000000000000
    rcx = 0x0000000000000000   rbx = 0x0000000000000000
    rsi = 0x0000000000000000   rdi = 0x00007f26277b0008
    rbp = 0x00007ffed68c7340   rsp = 0x00007ffed68c7150
     r8 = 0xffffffffffffea90    r9 = 0x0000000000000036
    r10 = 0x0000000000000000   r11 = 0x0000000000000293
    r12 = 0x00007ffed68cc000   r13 = 0x00007ffed68c7260
    r14 = 0x00007f26277ae601   r15 = 0x00007ffed68c718c
    rip = 0x000055e8092286a1
    Found by: given as instruction pointer in context
 1  Telegram!QProcess::startDetached(QString const&, QList<QString> const&, QString const&, long long*) [clone .constprop.0] + 0x1cf
    rbx = 0x00007f25e7e23d00   rbp = 0x00007ffed68c73b0
    rsp = 0x00007ffed68c7350   r12 = 0x00007ffed68c7350
    r13 = 0x00007ffed68c73d0   r14 = 0x00007ffed68c7360
    r15 = 0x0000000000000000   rip = 0x000055e809228b9f
    Found by: call frame info
 2  Telegram!launch(QString const&, QUrl const&, QString const&) + 0x254
    rbx = 0x00007ffed68c7430   rbp = 0x00007ffed68c7490
    rsp = 0x00007ffed68c73c0   r12 = 0x00007ffed68c73d0
    r13 = 0x00007f260d57451e   r14 = 0x00007ffed68c7410
    r15 = 0x0000000000000000   rip = 0x000055e8088e9024
    Found by: call frame info
 3  Telegram!<name omitted> [qgenericunixservices.cpp : 489 + 0x5]
    rbx = 0x0000000000000000   rbp = 0x00007ffed68c7520
    rsp = 0x00007ffed68c74a0   r12 = 0x00007ffed68c74d0
    r13 = 0x00007ffed68c7600   r14 = 0x0000000000000001
    r15 = 0x00007f2627212378   rip = 0x000055e80896a188
    Found by: call frame info
 4  Telegram!QDesktopServices::openUrl(QUrl const&) [clone .isra.0] + 0x347
```

No idea what to do, looks like a Qt bug...

**Comment by ilya-fedin** [comment]
Although this Qt code seem to be using some Linux kernel features, can you try to downgrade to linux-lts? Maybe it's a bug in the kernel after all...

**Comment by ilya-fedin** [comment]
Looks like I was unable to reproduce this due to all my systems being full-featured and having xdg-desktop-portal with allows to not to start processes directly. After blocking access to the portal I can reproduce this...
