### ISSUE TITLE
Not working with libicu version 5.8 or above

### ISSUE THREAD

**Issue by Cysioland** [telegramdesktop/tdesktop#2686]
### Steps to reproduce
1. Install the libicu version 5.8
2. Try to launch Telegram
3. Failure

### Expected behaviour
Telegram should launch

### Actual behaviour
It moans about libicuuc.so.57 being not available

### Configuration
**Operating system:** Antergos Linux (basically Arch Linux)

**Version of Telegram Desktop:** 0.10.19

**Comment by stek29** [comment]
> It moans about libicuuc.so.57 being not available

Because it's built against libicu 5.7?
