### ISSUE TITLE
Impossible to get rid of spam (vertical "videos")

### ISSUE THREAD

**Issue by luntik2012** [telegramdesktop/tdesktop#26876]
### Steps to reproduce

I cannot delete user from contacts because it's not in my contacts

I've already blocked this user earlier and I had no chats with him before receiving spam

I also didn't turn on any checkboxes which say "I agree to receive spam from telegram fz-llc or some other company", so it's defenitely a crime.

So expected behaviour - no spam,
Actual behaviour - gettig spam (notifications about some vertical videos)

### Expected behaviour

no spam from user https://t.me/olga_wellness

### Actual behaviour

getting spam from user https://t.me/olga_wellness

### Operating system

arch linux

### Version of Telegram Desktop

`telegram --version` is broken, according to package manager my telegram version is 4.10.1

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
this is a bug tracker for telegram desktop, maybe that user deletes the user after a wile and recreates.
