### ISSUE TITLE
Telegram-Desktop Ubuntu Gnome Doesn't remember window size with 4.10.2 update

### ISSUE THREAD

**Issue by devtweakr** [telegramdesktop/tdesktop#26871]
### Steps to reproduce

1. Open telegram-desktop in LINUX Gnome 3.36.8

### Expected behaviour

Window size should be restored after close and open.

### Actual behaviour

Window size is not restored after close and open.

### Operating system

Ubuntu 20.04, Gnome 3.36.8

### Version of Telegram Desktop

4.10.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
@devtweakr provide a screen record of the issue, it restores for me

**Comment by devtweakr** [comment]
Attached gif is 4.10.2 behavior, I reverted back to 4.10.0 which works fine, so its definitely something in the 4.10.2 update, i will disable automatic updates until this issue is resolved.
![tg_window](https://github.com/telegramdesktop/tdesktop/assets/60290356/4ffd997f-eac2-46e0-b300-975ef2129145)

**Comment by ironwheal** [comment]
Same thing on KDE: doesn't restore windows size (resets to 452x480) unless "Use system window frame" setting is enabled.

**Comment by ilya-fedin** [comment]
I'm trying to do the same as on GIF but window size gets restored :(

**Comment by silverdrake** [comment]
Same thing as reported and shown on the GIF on Linux Mint with Cinnamon desktop.

**Comment by ilya-fedin** [comment]
Can't reproduce on Linux Mint VM either. The report misses something important to reproduce. Try to reproduce on a VM yourself to find what's missing.

**Comment by ironwheal** [comment]
> Can't reproduce on Linux Mint VM either. The report misses something important to reproduce. Try to reproduce on a VM yourself to find what's missing.

Try multi-monitor setup and place the Telegram window on the non-primary screen

**Comment by silverdrake** [comment]
> Try multi-monitor setup and place the Telegram window on the non-primary screen

Confirm the same situation here, I have two monitors (both 1920x1080), with Telegram opening on the secondary monitor; which worked fine so far. 

Note that if I move Telegram to the primary display, and restart it, the sizing is remembered. 
But if I move it again on the secondary monitor and restart it, it opens for a split second with the size I had set on the primary display and then suddenly resets to the minimal size.

**Comment by ilya-fedin** [comment]
Yeah, I can reproduce with two virtual monitors... But that doesn't seem to give a light: it remembers the geometry right and then restores it to with the same coordinates according to the log. Only when the window position saving timer triggers the next time, it shows the real coordinates like if tdesktop sets the right coordinates but then the system overrides them..

**Comment by devtweakr** [comment]
I have 3 displays and they are listed in this order everywhere

1. DVI-D-0
2. HDMI-0
3. DP-0

I tested on all of them and the window size gets restored on 1. but not on 2. and 3.
It seems 1. is driver/hardware primary, and 3. seems to be my "x11" primary which I use as main
  
![Screenshot from 2023-10-01 23-33-29](https://github.com/telegramdesktop/tdesktop/assets/60290356/8421ab12-40b1-444c-92b8-9ef849028327)

**Comment by devtweakr** [comment]
Like i said, version 4.10.0 has no issues on all displays.
