### ISSUE TITLE
does not support Windows' dark theme (high contrast)

### ISSUE THREAD

**Issue by AdKiller** [telegramdesktop/tdesktop#2687]
### Steps to reproduce
1.  switch to dark theme (high contrast) in Windows 
2.  open Telegram for Windows

### Expected behaviour
Should adapt to Windows theme 

### Actual behaviour
it does not adapt to Windows theme.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
0.10.19

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by stek29** [comment]
#185 ?
