### ISSUE TITLE
Telegram Desktop crashes on linux when trying to open a link

### ISSUE THREAD

**Issue by Jeronimo17** [telegramdesktop/tdesktop#26877]
### Steps to reproduce

Open a link (Firefox)

### Expected behaviour

No crashes

### Actual behaviour

Crashes

### Operating system

Linux Mint 21.2 x86_64

### Version of Telegram Desktop

4.10.2

### Installation source

Static binary from official website

### Crash ID

Null (I don't get anything even if I activate the Beta)

### Logs

```shell
/home/jeronimo17/Telegram/Telegram
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter (**up to this point it works well**)
Violación de segmento (`core' generado)
```

**Comment by Jeronimo17** [comment]
It only happens on one of the 2 laptops I have with the same configuration.

**Comment by Aokromes** [comment]
duplicate and fixed on next version.
