### ISSUE TITLE
Unread indicator on desktop icon will not change

### ISSUE THREAD

**Issue by wadesmart** [telegramdesktop/tdesktop#26884]
### Steps to reproduce

1. Version 4.10.2 ?? - update this morning caused the number of unread messages to not change. 

![image](https://github.com/telegramdesktop/tdesktop/assets/16748667/a26e124b-d2ef-4667-b952-5107823aeefa)

2. Version 4.10.3 update did not change this problem. 

3. I have quit the program, restarted the desktop, restarted the computer but this does not change. 

### Expected behaviour

The indicator should read the number of new messages which is currently 4 and not 77. 

### Actual behaviour

The indicator does not change at all. 

### Operating system

Kubuntu 22.04.3 LTS

### Version of Telegram Desktop

4.10.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Why do you think it should be 4? :thinking:

**Comment by wadesmart** [comment]
Because when I originally posted there were 4 unread. 
Now it should say 0, not 77

**Comment by ilya-fedin** [comment]
But how do you detect how much there is unread? Maybe you think about some local counter while there's indeed 77 globally?

**Comment by wadesmart** [comment]
I didnt create the counter - it is part of the program.

**Comment by ilya-fedin** [comment]
Huh? I didn't say you created the counter. I say it's likely you count unread messages wrongly while this counter is right. Maybe you're forgetting about muted chats and etc.

**Comment by wadesmart** [comment]
Oh - that makes more sense - but there are zero unread messages in any folder.  But there were 77 unread when the update happened this morning.

**Comment by ilya-fedin** [comment]
Personally I can't reproduce and I'm not even sure the report is valid given the little details you provided and the lack of screenshots (counter in window title, counter in tray) confirming it's a bug and not your count mistake.

**Comment by wadesmart** [comment]
My phone:
![image](https://github.com/telegramdesktop/tdesktop/assets/16748667/9848d6a3-18ac-46a2-8b81-4b53c55f2371)

My computer:
![image](https://github.com/telegramdesktop/tdesktop/assets/16748667/4c41ebc3-0561-473f-bfcf-8c401fe2e96e)

The red circle with number 10 is the current unread and I can count that in the Unread on the app:

![image](https://github.com/telegramdesktop/tdesktop/assets/16748667/5258218c-9f6f-4929-9552-6df72820f9b8)

Between the time I took the phone and computer shots it did change but, you can see that the upper Telegram indicator is still 77 and not showing correct.

**Comment by ilya-fedin** [comment]
Yeah, it looks like a bug given that it's not in sync with the red counter. Still I can't reproduce that...

**Comment by wadesmart** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/16748667/2b17d427-060f-4ce7-8d57-fe9499135867)

See the sensor info where the 34 is?  It is like when Telegram updated the icon with the unread number was all captured and reused and the number is now part of the icon.

**Comment by ilya-fedin** [comment]
It updates for me just fine... I switch the count muted chats option and it switches between 8 and 9999 for me.

**Comment by wadesmart** [comment]
I have no muted chats. 

Trying to find the desktop icons though I found this in the log right after the second update:

[2023.10.02 16:52:30] Message Info: bad message notification received (error_code 33) for msg_id = 7285482370087654028, seq_no = 294

[2023.10.02 16:52:30] Message Info: bad message notification received, msgId 7285482370087654028, error_code 33

**Comment by ilya-fedin** [comment]
I don't think these lines are related

**Comment by ilya-fedin** [comment]
it might be some system cache so you may want to clear .cache

**Comment by wadesmart** [comment]
That fixed it. 
Thanks for the help.
Much appreciated.
