### ISSUE TITLE
4.10.3 doesn't open links in Firefox as the default browser (Linux)

### ISSUE THREAD

**Issue by AngryPhantom** [telegramdesktop/tdesktop#26883]
### Issue
The previous version **4.10.2** simply segfaulted when trying to open a link.
Version **4.10.3** came with a "Fix crash on external link opening. (Linux only)".
It doesn't crash now, but it still doesn't open any external link.

And I'm getting this notification in XFCE:

![failed](https://github.com/telegramdesktop/tdesktop/assets/17167075/bc8f4573-50f5-426c-9437-13ebe7a9dd0c)

I'm using a static binary from the official site.

Also I don't see anything bad in the logs either. The last messages are:

```
[2023.10.02 20:18:14] Notification daemon product name: Xfce Notify Daemon
[2023.10.02 20:18:14] Notification daemon vendor name: Xfce
[2023.10.02 20:18:14] Notification daemon version: 0.9.2
[2023.10.02 20:18:14] Notification daemon specification version: 1.2
[2023.10.02 20:18:14] Notification daemon capabilities: action-icons, actions, body, body-hyperlinks, body-markup, icon-static, sound, x-canonical-private-icon-only
[2023.10.02 20:18:25] API Warning: not loaded minimal channel applied.
```

### Expected behaviour

Previous versions of Telegram used to open links without problem.

### Actual behaviour

Links won't open in my default browser (Firefox).

### Operating system

Arch Linux

### Version of Telegram Desktop

4.10.3

### Installation source

Static binary from official website

### Logs

```shell
[2023.10.02 20:18:14] Notification daemon product name: Xfce Notify Daemon
[2023.10.02 20:18:14] Notification daemon vendor name: Xfce
[2023.10.02 20:18:14] Notification daemon version: 0.9.2
[2023.10.02 20:18:14] Notification daemon specification version: 1.2
[2023.10.02 20:18:14] Notification daemon capabilities: action-icons, actions, body, body-hyperlinks, body-markup, icon-static, sound, x-canonical-private-icon-only
[2023.10.02 20:18:25] API Warning: not loaded minimal channel applied.
```

**Comment by ilya-fedin** [comment]
does xdg-open work with the URL you're trying to open?

**Comment by AngryPhantom** [comment]
@ilya-fedin Damn, something was wrong with my system mime I guess. I've managed to fix it. Also, I guess new Firefox 115 ESR behaves differently than the previous 102 ESR. I'm sorry, closing the issue.

**Comment by AngryPhantom** [comment]
@Ghostbird Don't remember exactly, but Telegram began to start Epiphany browser for some weird reason which was not the default one (and I didn't even know it was installed on my Artix Linux). I uninstalled Epiphany and on the next start Firefox asked to be set as the default one and so I set it. But still I didn't like the look and feel of the new Firefox ESR (115 version) and downgraded to the previous one (105 version). I use official tarballs (not from repos) if it matters. Telegram is also from the official tarball.

**Comment by AngryPhantom** [comment]
@Ghostbird 
Funny, but I these are not even set in XFCE:

`xdg-settings get default-url-scheme-handler http(s)`

All I get is this:

`xdg-settings: default-url-scheme-handler not implemented for xfce`

**Comment by Ghostbird** [comment]
Ah, thanks, I guess my situation is a quite a bit more different than I assumed.

**Comment by AngryPhantom** [comment]
@Ghostbird Well, Telegram also opened another browser for me (Epiphany) while everywhere in the system Firefox was the default. All other apps opened Firefox. I still don't know why it happened.

**Comment by ilya-fedin** [comment]
Check what xdg-open actually opens with the links you're trying to open from Telegram, not xdg-settings. Those shell scripts are utterly bugged and each of them (xdg-open, xdg-mime, xdg-settings) is likely to have a different opinion on what is the default.

**Comment by AngryPhantom** [comment]
Yes, this. Somehow my xdg-open got broken after updating to Firefox 115 and I don't know even why. It also opened links in Epiphany.
