### ISSUE TITLE
Allow user to choose font and font size

### ISSUE THREAD

**Issue by alexchopstix** [telegramdesktop/tdesktop#26893]
### Is your feature request related to a problem?

If by problem you mean by not being able to select which font we want to use? Yes.

### Describe the solution you'd like

An option in chat settings to specify which font the app uses.

### Describe alternatives you've considered

Maybe add it into custom theme building, allowing a theme to specify a font to use?

### Additional context

I realize there's another topic about it, but it's closed and it's years old. This really isn't that big of a feature to request I just don't understand why it can't be implemented.

**Comment by ilya-fedin** [comment]
#90

**Comment by alexchopstix** [comment]
> #90

That topic has been closed due to inactivity.  Hence why I made a new topic. Nothing in that thread says they were even remotely interested in adding the feature, or a reason why they won't. I just don't get it. It's a simple feature that almost every chat program has and yet the devs won't implement it. Really a shame.

**Comment by ilya-fedin** [comment]
> That topic has been closed due to inactivity

Can you point to that? I see it's open
![изображение](https://github.com/telegramdesktop/tdesktop/assets/17829319/77900e45-d13c-4eee-aa14-3c30a1ce9044)

**Comment by alexchopstix** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/130067413/ae893f58-7e66-4e57-ac24-c1332bcdff08)

**Comment by ilya-fedin** [comment]
Still, the task is open, so it's a duplicate.

**Comment by alexchopstix** [comment]
So what if it's Open, no one can comment on it. Whatever though messages received, developers could care less about the features users want implemented.

**Comment by ilya-fedin** [comment]
Why should anyone comment to it? It's a tracker, not a place where anyone is supposed to complain. If discussions gets too heated thread gets locked.

**Comment by john-preston** [comment]
Changing font (which will change it's size as well) without breaking UI in various places is not trivial. Changing font size is even harder to make without breaking different parts of the UI (the exception may be just the regular text in the messages, without any other text including reply-to bars, forwarded from names etc). Even if done there will be an issue with emoji that right now have one size through-out the whole application and in case you make the font larger they'll be relatively smaller. If you make font smaller they won't fit and this will lead to even more graphical glitches.
