### ISSUE TITLE
[Feature Request] Accessibility / Dyslexia Aid - Add keyboard shortcut for spelling correction 

### ISSUE THREAD

**Issue by superclarkk** [telegramdesktop/tdesktop#26892]
### Is your feature request related to a problem?

I have a friend with dyslexia who types really fast. He spells incorrectly quite a lot. When I asked him why he doesn't use the spelling correction feature, he says that menus slow him down too much, and wonders why there isn't a keyboard shortcut to cycle through the choices. He makes a good point! This seems like a low-hanging fruit to provide really meaningful and useful functionality.

This request has been made before in #8549, but was closed prematurely.

### Describe the solution you'd like

When the cursor is at an unknown word (underlined in red), a keyboard shortcut should cycle through the suggested list of words.

It seems that the TAB button doesn't already have a function when the cursor is in the message text field.
CTRL+SPACE could also be convenient candidate.

Being able to customize keyboard shortcuts would also help, obviously.

### Describe alternatives you've considered

N/A

**Comment by john-preston** [comment]
Show the submenu by Ctrl+Space and cycle through elements by the same would be nice indeed.

**Comment by superclarkk** [comment]
@john-preston You're a star! Thank you for this, which I noticed in the latest release. We are using it!
