### ISSUE TITLE
The GPU is loaded as much as possible when viewing stories

### ISSUE THREAD

**Issue by suprunchuk** [telegramdesktop/tdesktop#26898]
### Steps to reproduce

1. Install version 4.10.2 x64 from the official website.
2. Log in to your account and find the channel's "stories", or create your own storie and upload it.
3. Open the story and observe a sharp increase in the load on the GPU.

### Expected behaviour

When viewing stories, there should not be a very heavy load on the GPU

### Actual behaviour

I have a pretty powerful built-in graphics processor. When I use my PC, it works within 1-10% of the workload. But as soon as I open the story, the load jumps sharply to 80-90%. Which is quite strange
![2023-10-06_09-06-06](https://github.com/telegramdesktop/tdesktop/assets/57152612/5dbcafaa-1997-4022-bff2-a1e631fce73d)
_____

Laptop Model: Acer Aspire 3 A315-59-7868

_Operating System_: Windows 10 PRO 22H2.
_Processor model_: Intel(R) Core(TM) i7-1255U of the 12th generation with a frequency of 4.70 GHz
_RAM_: 16 GB, DDR4
_Drive configuration_: 1024 GB SSD.
**Video card**: Built-in (**Intel Iris Xe Graphics 96 EUs**)
Image: 1920 x 1080, 60 Hz.

### Operating system

windows 10 pro 22H2

### Version of Telegram Desktop

4.10.2 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
i suggest you to try updating intel drivers.

**Comment by suprunchuk** [comment]
Yes. This seems to have helped. Intel recently released a new driver version. I installed it and the load decreased
![2023-10-29_15-13-23](https://github.com/telegramdesktop/tdesktop/assets/57152612/48803f0c-4972-4bab-a23a-42a593981a06)
