### ISSUE TITLE
[Feature Request] Text quoting with timestamp and author name

### ISSUE THREAD

**Issue by SiZEg** [telegramdesktop/tdesktop#269]
It's very uncomfortable to quote with "forwarding" feature or copy-past and formatting text with quotes, etc. If it's possible make a quoting, please.

Thanks in advance.

**Comment by Dolbager** [comment]
+1

**Comment by formatq** [comment]
+1

**Comment by auchri** [comment]
You can drag and drop messages by timestamp to forward them
