### ISSUE TITLE
Latest telegram release 4.10.3 on Linux lost app icon unread count

### ISSUE THREAD

**Issue by HassanMirza01** [telegramdesktop/tdesktop#26906]
### Steps to reproduce

just install latest release and get a msg from someone, app icon wont show that unread count

### Expected behaviour

app should show number of msgs it has unread on its app icon 

### Actual behaviour

unread msgs count not showing on app icon but showing on notification panel icon only, was fine on previous release

### Operating system

Kubuntu 22.04.3

### Version of Telegram Desktop

4.10.3

### Installation source

Snap

**Comment by ilya-fedin** [comment]
try `rm -rf ~/.cache` and reboot your system

**Comment by ilya-fedin** [comment]
I can reproduce but I don't understand why it doesn't work...

**Comment by mcrapts** [comment]
I have the same issue.

**Comment by ilya-fedin** [comment]
Looks like snap denies tdesktop to export the counter the same as it denies neochat
https://forum.snapcraft.io/t/kde-dbus-issues-neochat/37594
