### ISSUE TITLE
Lost custom taskbar icon

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#26900]
### Steps to reproduce

1. Create new LNK-file for `Telegram.exe` and set custom icon for it.
2. Click `Apply`
3. Try to start Telegram with this LNK-file — click on it.
4. Get default icon at taskbar.
![TG custom icon settings](https://github.com/telegramdesktop/tdesktop/assets/7080928/cdb75370-b892-4f9c-83d4-47b706edf4ac)

### Expected behaviour

4. Get custom icon at taskbar.

It worked fine with older versions, IDK how long, at least from v.4.xxx.

Bug isn't on my side.

### Actual behaviour

See above

### Operating system

Win 8.1 x64

### Version of Telegram Desktop

4.10.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This newer was an advertised feature, that worked by accident.

**Comment by Twilightssuperb** [comment]
@ilya-fedin, yep, it's my hack, but it is convenient to avoid getting confused in launched Telegram windows. 🤓
