### ISSUE TITLE
Unable to change language in expanded reaction popup

### ISSUE THREAD

**Issue by BANOnotIT** [telegramdesktop/tdesktop#26908]
### Steps to reproduce

1. Have non english keyboard
2. Call context menu on message
3. Click arrow down in reactions row
4. Try to switch language and enter reaction name in english

### Expected behaviour

It's expected that it won't block language switching functionality of the OS.

### Actual behaviour

It just doesn't let the DE switch the language. And practically any other system wide keybindings like switching current working screen or moving the window.

### Operating system

Ubuntu 22.04.3 LTS x86_64

### Version of Telegram Desktop

4.10.1

### Installation source

Snap

**Comment by ilya-fedin** [comment]
There's nothing tdesktop can do about that, the underlying window is established by the underlying toolkit (Qt)

**Comment by BANOnotIT** [comment]
@ilya-fedin you somehow managed to not block that in emoji/sticker popup window.

**Comment by ilya-fedin** [comment]
@BANOnotIT it's not a separate window, it's a part of the main window image

**Comment by ilya-fedin** [comment]
As far as I'm aware, the only ways out are wayland or switching to another toolkit. Qt's Wayland QPA doesn't demonstrate such issue.
