### ISSUE TITLE
Bug after restarting "windows audio" service

### ISSUE THREAD

**Issue by FrelVick** [telegramdesktop/tdesktop#2690]
### Steps to reproduce
1. Launch Telegram Desktop
2. Restart "Windows audio" service

### Expected behaviour
Audio messages should play

### Actual behaviour
They don't play

### Configuration
**Operating system:**
Windows 8.1

**Version of Telegram Desktop:**
version 0.10.19

**Comment by POPSuL** [comment]
I have similar issue on linux.

Steps:

1. Launch td and try to play any sound - **works properly**
2. Change audio profile via `pavucontrol` (e.g. analog output to hdmi)
3. Try to play any sound in tg again - **not working**
4. Restart tg and try again - **works!**

**Comment by auchri** [comment]
If somebody know how to fix this -> PR is welcome.

**Comment by POPSuL** [comment]
Just question: for what telegram uses openal for audio? Why not QtMultimedia/Phonon?
