### ISSUE TITLE
Stop bot without blocking it.

### ISSUE THREAD

**Issue by Ali-Flt** [telegramdesktop/tdesktop#26912]
### Is your feature request related to a problem?

I want to stop bots without seeing them in the blocked list in the privacy settings.

### Describe the solution you'd like

An option to clear the blocked list or an option to stop a bot without blocking it.

### Describe alternatives you've considered

There are none.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
