### ISSUE TITLE
When uploading files to telegram, telegram closes completely and me have to start again telegram.

### ISSUE THREAD

**Issue by bagasik** [telegramdesktop/tdesktop#26919]
### Steps to reproduce

Hello.
When uploading files to telegram, telegram closes completely and me have to start again telegram.
Linux 6.1.53-gentoo-r1 x86_64
xfce4 4.18.4
net-im/telegram-desktop-bin-4.10.3

### Expected behaviour

When uploading files to telegram, telegram closes completely and me have to start again telegram.

### Actual behaviour

When uploading files to telegram, telegram closes completely and me have to start again telegram.

### Operating system

Linux 6.1.53-gentoo-r1 x86_64

### Version of Telegram Desktop

telegram-desktop-bin-4.10.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Please do the steps required by the issue template to get crash ID and provide it.

**Comment by bagasik** [comment]
Crash ID not.

$ telegram-desktop 
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
implib-gen: libgdk-3.so.0: failed to resolve symbol 'gdk_wayland_window_get_type' via dlsym: /usr/lib64/libgdk-3.so.0: undefined symbol: gdk_wayland_window_get_type
Аварийный останов

**Comment by ilya-fedin** [comment]
Your system is supported up to 4.9.x. Please downgrade or or get a gtk with wayland.

**Comment by bagasik** [comment]
Launched from the console.
Then I tried to upload a file to the chat and then the telegram turned off completely.
I had to restart telegram.

**Comment by bagasik** [comment]
Installed on gtk system.

dev-util/gtk-doc-am-1.33.2
dev-util/gtk-update-icon-cache-3.24.31
x11-libs/gtk+-3.24.38
x11-libs/gtk+-2.24.33-r3
x11-libs/gtksourceview-4.8.4
x11-misc/lightdm-gtk-greeter-2.0.8-r1
x11-themes/gtk-engines-adwaita-3.28
x11-themes/gtk-engines-murrine-0.98.2-r3

wayland not using!

**Comment by ilya-fedin** [comment]
Yeah, that's the thing. gtk with wayland is required since 4.10.0. Your system is uncapable to run new versions.

**Comment by bagasik** [comment]
мдааа

**Comment by dmitry80mass** [comment]
Вот уроды нах нужен ваш вейленд

**Comment by ilya-fedin** [comment]
Well, it's just a matter of pragmatism. There was a ~1kloc patch to qtbase to make gtk optional in Qt static build. Since 4.10.0 no longer supports major distros without Wayland nor gtk3, there's no sense to continue to maintain that huge patch. So the Qt build now requires gtk3 and requires it with both x11 & wayland (as Qt uses both GdkWaylandWindow and GdkX11Window API). It's just a matter of building a very little libwayland for you while a big simplification of Qt update process for tdesktop. If you don't like that you can always build tdesktop from sources with Qt configured in a way you would like.

**Comment by henning-schild** [comment]
@ilya-fedin thanks. We will add the dependencies to the gentoo package metadata.

And users, please stay polite and write in English.

**Comment by vitaly-zdanevich** [comment]
But I will not switch to Wayland because of Telegram.

**Comment by ilya-fedin** [comment]
Don't switch? No one force you to switch to Wayland, just build libwayland.

**Comment by Phazeus** [comment]
Why not to use x11 in a case of no wayland?

**Comment by ilya-fedin** [comment]
Not sure what you means, that's how it works

**Comment by Phazeus** [comment]
implib-gen: libgdk-3.so.0: failed to resolve symbol 'gdk_wayland_window_get_type' via dlsym: /usr/lib64/libgdk-3.so.0: undefined symbol: gdk_wayland_window_get_type
I don't use Wayland

**Comment by ilya-fedin** [comment]
You don't have to use Wayland but you have to have GTK built with Wayland backend as Qt checks whether GtkWindow is an instance of GtkWaylandWindow in order to know whether GTK is running under Wayland.

**Comment by Phazeus** [comment]
I use GTK+ without  wayland flag compiled.

**Comment by ilya-fedin** [comment]
You have to build gtk with wayland

**Comment by Phazeus** [comment]
And  crashing whole the system?  No thanks.

**Comment by Phazeus** [comment]
Just don't use that function.

**Comment by Phazeus** [comment]
Or use exception-safe methods.

**Comment by ilya-fedin** [comment]
> Just don't use that function.

How? tdesktop just creates an instance of QFileDialog, this functions is used by Qt internals.

**Comment by Phazeus** [comment]
Or make portable version with needed libs ...

**Comment by ilya-fedin** [comment]
> And crashing whole the system? No thanks.

I'm not sure what you mean by that, you would just need to build the little libwayland library and re-build GTK with it. In any case I don't think there's enough users to start to patch Qt or create a separate build (every build takes around 4 hours so having a different build for such users is a big headache)

**Comment by ilya-fedin** [comment]
> Or make portable version with needed libs ...

That won't work. GTK relies on plugins a lot so it will crash for sure due to system having various plugins built for system GTK build.

**Comment by Phazeus** [comment]
"You have to use wayland to make me sure that you don't use it". Ok. Can't use TG any more.

**Comment by ilya-fedin** [comment]
There's a difference between building libwayland/gtk wayland backend and using a Wayland compositor.

**Comment by Phazeus** [comment]
But  it is stupid to do such checks that way. If system doesn't use wayland at all, it is stupid to need in libwayland to check it. If you see that there no wayland at all, don't use such checks....

**Comment by Phazeus** [comment]
I use  Gentoo.  I can't change hardware just for TG working...

**Comment by ilya-fedin** [comment]
> But it is stupid to do such checks that way. If system doesn't use wayland at all, it is stupid to need in libwayland to check it. If you see that there no wayland at all, don't use such checks....

I understand. But as I said, tdesktop is not of control for that code, it's done in third party dependency, the Qt toolkit.

> I use Gentoo. I can't change hardware just for TG working...

I'm not sure why you need to change hardware

**Comment by Phazeus** [comment]
I understand, but ... damn ... :(

**Comment by ilya-fedin** [comment]
I don't understand your problem. Building libwayland is a couple of seconds and then once rebuild GTK whose build will be increased only by a few Wayland-related source files. If that's a problem for you then maybe install Arch/Fedora/Ubuntu/etc and just use prebuilt libraries?

**Comment by Phazeus** [comment]
I need to find old ebuilds for my current versions. I can't recompile whole the system with tons of deps. So, will try to find old GTKs, Mesa,  etc...

**Comment by ilya-fedin** [comment]
Ah. Some gentoo weirdness.

**Comment by henning-schild** [comment]
> Ah. Some gentoo weirdness.

Not at all. Gentoo is requiring the lib to be built with wayland support since this one came up. So it is all good as far as i can tell (gentoo maintainer for telegram-desktop-bin).

What we see here is people failing to explain their point and choosing to use weird ways. Like old packages and basically freezing/forking parts of their setup. Still no clue why. I suggest to ignore until we see good reasoning.

**Comment by Phazeus** [comment]
> > Ah. Some gentoo weirdness.
> 
> Not at all. Gentoo is requiring the lib to be built with wayland support since this one came up. So it is all good as far as i can tell (gentoo maintainer for telegram-desktop-bin).
> 
> What we see here is people failing to explain their point and choosing to use weird ways. Like old packages and basically freezing/forking parts of their setup. Still no clue why. I suggest to ignore until we see good reasoning.

I use Mesa 21.1.8-r1  and can't use never version for some reasons. I used to compile the packages with "-wayland" global USE flag everywhere.  Now, to recompile it with "+wayland" I need to ... find old ebuilds and sources for Mesa and old version for GTK+ to recompile. Because by portages a bit updated and I lost my current compiled versions of software installed...

**Comment by henning-schild** [comment]
Your mesa is outdated. If newer versions have a bug, look into that. And now please stop bothering upstream with your problems .... likely caused by your own changes.

**Comment by beelze** [comment]
There is no need to set +wayland USE flag globally. To get rid of the issue is enough to add:
```
x11-libs/gtk+:3 wayland
media-libs/mesa wayland
```
and rebuild these packages.

**Comment by henning-schild** [comment]
> There is no need to set +wayland USE flag globally. To get rid of the issue is enough to add:
> 
> ```
> x11-libs/gtk+:3 wayland
> media-libs/mesa wayland
> ```
> 
> and rebuild these packages.

In fact you simply do nothing. Because what was described here happens automatically unless one messed too much with USE.
