### ISSUE TITLE
telegram account ban without any reason

### ISSUE THREAD

**Issue by incovered** [telegramdesktop/tdesktop#26920]
### Steps to reproduce

I was just using my account as usual and suddenly it kagged and when I restarted the app it logged my account and when I tried to log in again it showed my number is banned, I am sure that I hadn't done anything wrong, you can even analyse that my id is banned due to any bug

### Expected behaviour

it should login my account

### Actual behaviour

it banned my account

### Operating system

funtouch OS, SDK 31

### Version of Telegram Desktop

10.1.2

### Installation source

Static binary from official website

**Comment by incovered** [comment]
@Aokromes @ilya-fedin @john-preston help me

**Comment by incovered** [comment]
I had also complaint on email but no response, help me its office account and its urgent

**Comment by Aokromes** [comment]
this is telegram desktop bug tracker, not account issue contacta adress.
