### ISSUE TITLE
Telegram Desktop closes unexpectedly when clicking on a user profile from the list of reactions

### ISSUE THREAD

**Issue by nuromirzak** [telegramdesktop/tdesktop#26929]
### Steps to reproduce

1. Enter any group chat in Telegram Desktop
2. Locate a message that has reactions
3. Right-click on the message and hover the list of users who reacted
4. Click on any user profile from the list of reactions or click the number of reactions (areas bordered with a red rectangle in the screenshot)
![image](https://github.com/telegramdesktop/tdesktop/assets/76807326/c4dd0692-5faa-4dca-bbd1-1f4dfaefc86d)

### Expected behaviour

- When clicking on a user's profile, the user's profile should be displayed
- When clicking on the number of reactions, nothing specific should happen

### Actual behaviour

Telegram Desktop closes unexpectedly when:

1. Clicking on any user profile from the list of reactions.
2. Hovering over the reactions (occasionally; the cause is unclear).

### Operating system

Ubuntu 22.04.3 LTS, ubuntu:GNOME

### Version of Telegram Desktop

4.10.3

### Installation source

Snap

**Comment by Aokromes** [comment]
duplicate, will be fixed on next release.
