### ISSUE TITLE
Telephone number verification issue

### ISSUE THREAD

**Issue by chashik** [telegramdesktop/tdesktop#26928]
### Steps to reproduce

Hello, Everyone,
I've faced a terrible issue recently. Cannot change phone number neither on Android, nor on UWP (Unigram) devices. Send tons of letters to sms@telegram.org
No answer for about a month. I need to switch to a new number. I also tried to make clean installation for the new number - I've got message that confirmation sent to my another device. It is complete madness.

I would sincerely appreciate if smbd. from developers could forward my case to some existing support division. 

### Expected behaviour

+375 29 *** **** Belarus A1 mobile and internet provider. I asked them but they do not have complaints from other users.
++Phone number verification during a call to dictate a code.

### Actual behaviour

No calls coming. Sometimes codes go to another device which doesn't exist. Maybe the number is hacked somehow.

### Operating system

Windows 10, Android, Windows 10 on Lumia phone (Unigram)

### Version of Telegram Desktop

4.10.2 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
this is a bug tracker not a support place.

**Comment by chashik** [comment]
@Aokromes ,
Please, don't be hasty,
It is Telegram bug as I see it. 
And I also asked here to forward the issue to support if they can resolve this.
