### ISSUE TITLE
No notifications under linux KDE in another Activity instance

### ISSUE THREAD

**Issue by ReKreker** [telegramdesktop/tdesktop#26927]
### Steps to reproduce

1. Open telegram in first Activity
2. Go to an another Activity
3. Send message with notification

### Expected behaviour

Show notification in another Activity

### Actual behaviour

There is no notification & it's sound

### Operating system

Arch Linux KDE 5

### Version of Telegram Desktop

4.10.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
As far as I understand that's managed by the window manager and nothing could be done about that
