### ISSUE TITLE
Telegram apps fail to verify phone number via call

### ISSUE THREAD

**Issue by chashik** [telegramdesktop/tdesktop#26930]
### Steps to reproduce

Hello, Everyone,
I've faced a terrible issue recently. Cannot change phone number neither on Android, nor on UWP (Unigram) devices. 
Need to switch to a new number ASAP. 
I also tried to make clean installation for the new number - I've got message that confirmation sent to my another device. It is complete madness because I have no telegram installs linked to a new phone number.

### Expected behaviour

Phone number verification during a call to dictate a code.
(+375 29 *** **** Belarus A1 mobile and internet provider. I asked them but they do not have complaints from other users.)

### Actual behaviour

No calls coming. Sometimes codes go to another device which doesn't exist. Maybe the number is hacked somehow.

### Operating system

Windows 10, Android, Windows 10 on Lumia phone (Unigram)

### Version of Telegram Desktop

4.10.2 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
again, this is telegram desktop bug tracker. you have to change phone number from mobile device. so this doesn't belong here.
