### ISSUE TITLE
Suggested fix for the issues with libQt6Svg6 dumping core on Linux

### ISSUE THREAD

**Issue by manfred-h** [telegramdesktop/tdesktop#26937]
### Is your feature request related to a problem?

Yes.

### Describe the solution you'd like

See additional context

### Describe alternatives you've considered

None, a bug is a bug.

### Additional context

I see that qtsvg is manually downgraded to version 6.5.3, while the Qt6 base stuff comes from version 6.6.0.
If this is due to the fact that the telegram-desktop application dumps core on Linux, then I suggest you take a look at the following bug report: [QTBUG-117944](https://bugreports.qt.io/browse/QTBUG-117944).

The following two patches should be added to your patches hierarchy, which will then allow building qtsvg version 6.6.0; please note that version 6.6.1 will include the patches:

1. [Fix nullptr dereference with invalid SVG](https://codereview.qt-project.org/c/qt/qtsvg/+/510674)
2. [Make sure we don't load invalid SVGs twice](https://codereview.qt-project.org/c/qt/qtsvg/+/510714)

**Comment by ilya-fedin** [comment]
Adding a patch would actually be a more of headache as there's currently only a folder and command sequence for qtbase. Thus means creating a folder & adding command sequence just for one patch and one release to remove all that when 6.6.1 is out. IMO it's better to leave it as it is and remove the additional checkout command when 6.6.1 is out
