### ISSUE TITLE
Receiving notifications from another account despite the setting being disabled

### ISSUE THREAD

**Issue by demqa** [telegramdesktop/tdesktop#26938]
### Steps to reproduce

1. Use two accounts in Telegram Desktop
2. Turn off this setting not to receive notifications from other account:
![image](https://github.com/telegramdesktop/tdesktop/assets/33611332/62c8c5e0-2021-415d-8920-974f827c3538)
4. Use one of these accounts
5. Write a message on the second account
6. You will see red badge counter from the second account, even though the option is disabled.
![image](https://github.com/telegramdesktop/tdesktop/assets/33611332/bf269043-5a24-42c9-948d-a268347aa446)

### Expected behaviour

I don't want to see any notifications from other account, which is not used right now. 
Maybe there was a logic that I will not get these bubble-notifications from other account, but who even use these bubbles in 2023?
I expect not to get information about notifications from other account even from this tray icon.

### Actual behaviour

I see badge counter for messages received on another account.

### Operating system

Ubuntu 22.04.3 LTS x86_64

### Version of Telegram Desktop

4.10.3

### Installation source

Snap

**Comment by demqa** [comment]
Also it would be great to add a feature described in #6721.

Maybe if someone can show where the corresponding code is located, I can fix it and attach a PR (but this would be my first experience...)

**Comment by ilya-fedin** [comment]
Sorry but according to @john-preston this is intended behavior. The option is supposed to change only the behavior of desktop notifications, not counters.

**Comment by demqa** [comment]
@ilya-fedin 

Okay. Maybe adding a feature #6721 might be the solution. If I create pull request, will you accept it?
