### ISSUE TITLE
This voice message is too long

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#26934]
### Steps to reproduce

I click on the arrow that points to the A to get it to transcribe the message.

It gives me the error This voice message is too long when the message isn't that long at all & I never had this problem before.

One of the main reasons I pay for the premium service is to get the transcriptions & it only started causing problems 3-4 updates ago. Before that I never had any problems.

Please fix.

### Expected behaviour

It should transcribe the voice message.

### Actual behaviour

I get the error This voice message is too long & I get no transcription.

### Operating system

Win 10

### Version of Telegram Desktop

4.10.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
