### ISSUE TITLE
Download the files in separate folders according to the name of the groups, channels or people

### ISSUE THREAD

**Issue by alexcanario** [telegramdesktop/tdesktop#26932]
### Is your feature request related to a problem?

Not 

### Describe the solution you'd like

I would like to have the option where files that are downloaded manually or automatically into groups, channels or personal contacts could be organized into separate folders with the same name as the group, channel or person. This way we would avoid duplicating files and our files would be more organized.

### Describe alternatives you've considered

Downloaded manually or automatically into groups, channels or personal contacts could be organized into separate folders with the same name as the group, channel or person. This way we would avoid duplicating files and our files would be more organized.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5788
