### ISSUE TITLE
Clicking on a forwarded message from the same chat should jump/scroll to that message

### ISSUE THREAD

**Issue by Ricket** [telegramdesktop/tdesktop#2693]
### Steps to reproduce
1. Forward a message from a chat to the same chat.
2. Click on the message.
3. Nothing happens, or if you click on the user's name then it just shows the user's profile.

### Expected behaviour
Similar to if you click a reply, it should jump/scroll up to the message that was forwarded.

### Actual behaviour
Can't click it, except for the user name. No way to get up to the forwarded message.

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 0.10.19

**Comment by stek29** [comment]
Why won't you just use "Reply"?

**Comment by Ricket** [comment]
Is it unclear how this is an inconvenience? Here's an example scenario to clarify.

> hang on, i'll find that old message I'm thinking of...

> found it! check out the pictures just after it too

> [forwarded] some old message

> ah shit, telegram doesn't let you click on it, hang on let me go find it AGAIN and do the reply thing this time

**Comment by clurect** [comment]
Yeah I've had this happen a lot. It's easier and more intuitive to forward a message when you've been talking about it. Like in Ricket's example I'd have to go back and then type something in the reply box.

**Comment by stek29** [comment]
1) Forward is usually needed to **forward** a message -- _send (a letter or email) on to a **further** destination_ 
2) It's an API issue. 
To jump to some message we need to know it's `id` at least. 
[messageFwdHeader](https://tjhorner.com/tl-schema/constructor/messageFwdHeader) has an optional parameter `channel_post` for this, but it obviously would exist only for messages forwarded from channels.
So TDesktop can't really do anything with this, sorry.

**Comment by mortezae** [comment]
This feature seems to get lost in latest versions.
