### ISSUE TITLE
again, this is telegram desktop bug tracker. you have to change phone number from mobile device. so this doesn't belong here.

### ISSUE THREAD

**Issue by Harry50012** [telegramdesktop/tdesktop#26931]
again, this is telegram desktop bug tracker. you have to change phone number from mobile device. so this doesn't belong here.

p.s. you need google services installed on android to work.

_Originally posted by @Aokromes in https://github.com/telegramdesktop/tdesktop/issues/26930#issuecomment-1763442547_

**Comment by chashik** [comment]
> ```
>           again, this is telegram desktop bug tracker. you have to change phone number from mobile device. so this doesn't belong here.
> ```
> 
> p.s. you need google services installed on android to work.
> 
> _Originally posted by @Aokromes in [#26930 (comment)](https://github.com/telegramdesktop/tdesktop/issues/26930#issuecomment-1763442547)_

Anyway, thanks, 
Will report to Unigram directly..

**Comment by Aokromes** [comment]
it''s not unigram bug. phone change must be done on android or ios device.

**Comment by chashik** [comment]
> it''s not unigram bug. phone change must be done on android or ios device.

@Aokromes ,
They do not allow to create issues..
