### ISSUE TITLE
group with no admin

### ISSUE THREAD

**Issue by mahyar-abdoli** [telegramdesktop/tdesktop#2694]
### Steps to reproduce
We have an old group from the first days of telegram. Those days Admin left the group and we had no admin. We wanted to upgrade to Super-group but we had no admin. We added him to group again but now he is not our Admin.

### Expected behaviour
Tell us what should happen
We want some sort of election to make somebody  admin. or some action to give us an admin. pleas !
### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
All Operation Systems
**Version of Telegram Desktop:**

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by Aokromes** [comment]
#1916

**Comment by stek29** [comment]
@mahyar-abdoli won't you please add a description or close the issue?

**Comment by auchri** [comment]
> We have an old group from the first days of telegram. Those days Admin left the group and we had no admin. We wanted to upgrade to Super-group but we had no admin. We added him to group again but now he is not our Admin.

**Comment by stek29** [comment]
@auchri It wasn't there when I commented :)
