### ISSUE TITLE
The application crashes randomly

### ISSUE THREAD

**Issue by TarasovSavely** [telegramdesktop/tdesktop#26946]
### Steps to reproduce

1. Open the application 
2. Do something, click buttons in menus, click pop-ups windows
3. It's craches! 
P.S. not always after the crash of the telegram offers to send a report, but I still managed to get it

### Expected behaviour

Normal operation

### Actual behaviour

The application crashes

### Operating system

Fedora Linux 38 (Workstation Edition) 64-bit

### Version of Telegram Desktop

4.10.3

### Installation source

Static binary from official website

### Crash ID

b0119ed7-06bd-4328-5a8f0ca5-411cb090

**Comment by Aokromes** [comment]
duplicate, will be fixed on next release
