### ISSUE TITLE
The voice message is not recorded. Sound is not recognized.

### ISSUE THREAD

**Issue by ElizavetaSedova** [telegramdesktop/tdesktop#26948]
### Steps to reproduce

1. I can’t record a voice message. Holding the button does not work after the update.
2. When making a call, the voice is not heard by others. The voice recording device is not picking up sound. There's absolutely nothing wrong with the microphone. Everything worked before the update too.

### Expected behaviour

1. Voice is recorded by holding down the mouse button. 
3. The interlocutor hears me.

### Actual behaviour

1. I can’t hold down the button with the mouse. Reset immediately.
2. The interlocutor cannot hear me with different settings of the voice input device.

### Operating system

Windows 10 v22H2

### Version of Telegram Desktop

4.9.7 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
can't reproduce, also latest version is 4.10.2.
