### ISSUE TITLE
Stable crash on exact sequence in UI

### ISSUE THREAD

**Issue by socketpair** [telegramdesktop/tdesktop#26941]
### Steps to reproduce

1. open context menu on any picture message (possibly not only picture I did not check)
2. open submenu with the list of people who read this message
3. move mouse to the bottom where input editbox is located (main area where we enter message before sending)
4. click on this editbox
5. TG will crash WITHOUT message about sending crash.

### Expected behaviour

Do not crash

### Actual behaviour

Crash

### Operating system

Linux, Fedora 38, X86_64

### Version of Telegram Desktop

4.10.3

### Installation source

Static binary from official website

### Logs

```shell
stdout:

Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.qpa.wayland: setGrabPopup called with a parent, QtWaylandClient::QWaylandXdgSurface(0x7f9474291640) which does not match the current topmost grabbing popup, QtWaylandClient::QWaylandXdgSurface(0x7f9438204aa0) According to the xdg-shell protocol, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly because xdg-shell mandate that child popups close before parents
qt.qpa.wayland: Could not create EGL surface (EGL error 0x3000)

The Wayland connection experienced a fatal error: Protocol error
```

**Comment by socketpair** [comment]
[Uploading Запись экрана от 2023-10-18 15-49-09.webm…]()

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by socketpair** [comment]
@Aokromes how to enable ?

**Comment by socketpair** [comment]
@Aokromes does it trigger on your side? See the video, it is easy as 1-2-3.

**Comment by ilya-fedin** [comment]
Please look at closed issues, this was already reported multiple times

**Comment by socketpair** [comment]
#26887
