### ISSUE TITLE
Pausing a voice message doesn't keep

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#26947]
### Steps to reproduce

So before when I paused a VM from someone I'm messaging with, it would keep unless I restarted my computer, now it doesn't keep if I go to other messages or groups.

Please fix. I have no way of knowing where I left off.

Thanks

### Expected behaviour

It should stay paused unless I restart my computer or TG.

### Actual behaviour

The paused disappears

### Operating system

Win 10

### Version of Telegram Desktop

4.10.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
after how much time it resumes the pause? because can't reproduce myself.

**Comment by ILoveSkilledCoders** [comment]
> after how much time it resumes the pause? because can't reproduce myself.

It doesn't resume anything, it goes back to the beginning. The paused is removed. I have to drag the audio thing to try & find where I left off b/c you guys don't have timestamps.

**Comment by Aokromes** [comment]
it does resume from paused place for me.

**Comment by ILoveSkilledCoders** [comment]
> it does resume from paused place for me.

I don't think you understand what I'm saying.

I pause it, go to another window & it cancels the pause at some point.

It's happened over & over since I think the last 1-2 updates. It never did that before, it always stayed pause unless I restarted my computer.

**Comment by Aokromes** [comment]
i closed the window to tray, i moved to another window, voice message remains paused and if i resume it continues on some place it was paused.
