### ISSUE TITLE
Custom gif 

### ISSUE THREAD

**Issue by julian-rare** [telegramdesktop/tdesktop#2695]
Currently has custom emojis that are png, but no gif, please enable support for gif

**Comment by auchri** [comment]
Please provide a proper description und use the template next time.

**Comment by julian-rare** [comment]
template is for issues, this is a feature

**Comment by auchri** [comment]
github is for issues, not for feature requests ;)

**Comment by julian-rare** [comment]
yes it is, enhancement, if not, where do I request the feature?

**Comment by stek29** [comment]
I guess @julian-rare means stickers by "custom emojis", webp by "png", and he wants an option to make animated stickers. Maybe he doesn't know that you can just send gifs to make... GIFs :)

Or maybe he is talking about @Stickers bot, which accepts only .png images.
