### ISSUE TITLE
Autoview and autoplay don't works in own builds

### ISSUE THREAD

**Issue by Grishanenko** [telegramdesktop/tdesktop#26951]
### Steps to reproduce

1. Install Visual Studio 2022 with Windows SDK 10.1.22000.832 on Windows 10 x64
2. Follow instructions https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win.md

### Expected behaviour

Automatically show pictures and play videos in groups and chats.

### Actual behaviour

I can see pictures and play videos only in Click-to-Play mode.

Windows 10 x64 10.0.15063
.Net Framework 4.8.03761
Git 2.40.1
Python 3.10.0 (64 bit)
Cmake 3.26.0-msvc3
Visual Studio 2022 v17.6.0 Community Edition
Windows SDK 10.1.22000.832

Successfully done prepare.bat
Configured with own API_ID
Building Telegram.exe x86 without errors, after adding /bigobj key to command line for "td_scheme" and "Telegram".

I build v4.10.2 and downgraded to v3.9.6 and v3.9.1
All my builds have bigger (+5..6 MB) Telegram.exe size, according to officials versions.
My builds works, except automatic image and video view. Only Click-to-Show/Play mode.
With official builds on the same profile autoplay works.

### Operating system

Windows 10 x64

### Version of Telegram Desktop

v4.10.2 v4.9.6 v4.9.1

### Installation source

Static binary from official website

**Comment by Grishanenko** [comment]
I build v4.11.1
Default settings
AutoPlay don't work.
File size 129 709 056

Configuration Properties - C/C++ - Optimization: Inline Function Expansion: Any Suitable (/Ob2) -> Only __inline(/Ob1)
AutoPlay don't work.
File size 132 773 888

Configuration Properties - C/C++ - Optimization: Inline Function Expansion: Only __inline(/Ob1) -> Disabled (/Ob0)
AutoPlay works.
File size 129 845 760

Official x32 release
AutoPlay works.
File size 123 522 448

Looks like something wrong in my system or with Visual Studio or something else.

**Comment by john-preston** [comment]
@Grishanenko Yeah, this is something with MSVC. But the reproducible example is too large (tdesktop with autoplay) to submit a nice bug report.

**Comment by Grishanenko** [comment]
I have to use latest MSVC-2022 (17.7.6) or some old stable version will be enough? Which one version you a using now?

**Comment by john-preston** [comment]
@Grishanenko I'm using the latest, I'm building Release builds with LTO enabled, that prevents this bug.

I'm afraid old compiler versions may still be affected and they may not build the codebase because of some compiler/stdlib features not being supported.
