### ISSUE TITLE
Unable to see photo - Hidh-dpi laptop display - Ubuntu 23.04 - Wayland

### ISSUE THREAD

**Issue by francescotaioli** [telegramdesktop/tdesktop#26955]
### Steps to reproduce

1. Open telegram-desktop - snap install - ubuntu 23.04 - **laptop 2.5k display**
2. open a chat, and visualize a photo
3. crash/unable to see photo

Some important details:
I'm running Ubuntu 23.04, on Wayland, with Intel Xe graphics. 

I have a second monitor. If I visualize telegram on that monitor, everything works as expected. I can open all the photos inside the chat, and the slide to the left/right works as well.

If I repeat the same operation on telegram opened in the laptop's display, the following can happen:
- telegram shows the photo (I'm unable to see a correlation between photo, unfortunately), or
- telegram crash, or
- telegram displays a black image, the laptop becomes unresponsive for x seconds, then I visualize the photo, or
- the slide to left/right doesn't work

If telegram opens the photo, and I can close it, it doesn't matter what photo I choose next, the first one is always displayed.

In the log I can see the following:

```
PC Error: request 65 got fail with code 400, error PEER_ID_INVALID
Error: Error in avformat_open_input (code: -542398533, text: Generic error in an external library).
```

### Expected behaviour

I should be able to see photos

### Actual behaviour

See above

### Operating system

Ubutnu 23.04, Wayland

### Version of Telegram Desktop

Version 4.10.3

### Installation source

Snap

### Logs

```shell
PC Error: request 65 got fail with code 400, error PEER_ID_INVALID
Error: Error in avformat_open_input (code: -542398533, text: Generic error in an external library).
```

**Comment by francescotaioli** [comment]
Related to https://github.com/telegramdesktop/tdesktop/issues/26366

Also, disabling OpenGL **(disable OpenGL in Settings -> Advanced)** seems to fix the issue

**Comment by ilya-fedin** [comment]
Are you sure it's about photos? You have a ffmpeg error in the log and ffmpeg is used only for videos.

**Comment by francescotaioli** [comment]
@ilya-fedin yeah, sure, it's about photos.

**Comment by ilya-fedin** [comment]
@francescotaioli this means the log lines are unrelated. Since you're saying it's a crash, a crash ID of crash report is required. Snap doesn't have crash reporting functionality since it wasn't implemented by Canonical so you have to switch to the static binary first. Once you switch to static binary, you should be able to do the steps from the issue template to get crash ID.
