### ISSUE TITLE
<<PKGBUILDDIR>>/Telegram/lib_base/base/platform/linux/base_linux_glibmm_helper.h:66:7: error: redefinition of ‘class Glib::Variant<long long unsigned int>’

### ISSUE THREAD

**Issue by FabioPedretti** [telegramdesktop/tdesktop#26957]
### Steps to reproduce

Build Debian package of telegram-desktop 4.10.3 on Ubuntu 

### Expected behaviour

Builds fine

### Actual behaviour

I got this error:
`<<PKGBUILDDIR>>/Telegram/lib_base/base/platform/linux/base_linux_glibmm_helper.h:66:7: error: redefinition of ‘class Glib::Variant<long long unsigned int>’`

Full build log at: https://launchpadlibrarian.net/690317642/buildlog_ubuntu-mantic-amd64.telegram-desktop_4.8.1+ds-2~bpo12+1~oibaf~m_BUILDING.txt.gz

### Operating system

Ubuntu 23.10

### Version of Telegram Desktop

4.10.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
The version you're trying to build doesn't support that new glibmm. You have to get a newer version.

**Comment by ilya-fedin** [comment]
Yes

**Comment by ilya-fedin** [comment]
You say you're building 4.10.3 but the log has 4.8.1 in the name

**Comment by ilya-fedin** [comment]
cppgir is a part of the sources, sounds like someone is creating problems by making buggy modifications
