### ISSUE TITLE
Telegram Desktop app is closed unexpectedly on Ubuntu

### ISSUE THREAD

**Issue by abdurakhmanova** [telegramdesktop/tdesktop#26956]
### Steps to reproduce

1. Open any chat with several members.
2. Enter a message.
3. Wait till it is viewed by at least one person.
4. Right-click on your message to see pop-up menu with "Seen" or "Reacted" option at the bottom of the menu.
5. Left-click in text field at the bottom of the window to enter new message.

### Expected behaviour

User can enter new message.

### Actual behaviour

Telegram app is closed, so user should re-open it.

### Operating system

Ubuntu 22.04.3 LTS 64 bit

### Version of Telegram Desktop

4.10.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
update to the latest version.

**Comment by romankspb** [comment]
/reopen

I can confirm. This bug is reproduced on Fedora 38.

tsetup.**4.10.3**.tar.xz is latest version for Linux.

**Comment by romankspb** [comment]
> update to the latest version.

tsetup.4.10.3.tar.xz is latest version for Linux.

I can confirm. This bug is reproduced on Fedora 38.

/reopen

**Comment by Aokromes** [comment]
> > update to the latest version.
> 
> tsetup.4.10.3.tar.xz is latest version for Linux.
> 
> I can confirm. This bug is reproduced on Fedora 38.
> 
> /reopen

https://github.com/telegramdesktop/tdesktop/releases nope.

**Comment by romankspb** [comment]
> > > update to the latest version.
> > 
> > 
> > tsetup.4.10.3.tar.xz is latest version for Linux.
> > I can confirm. This bug is reproduced on Fedora 38.
> > /reopen
> 
> https://github.com/telegramdesktop/tdesktop/releases nope.

![изображение](https://github.com/telegramdesktop/tdesktop/assets/785755/2eae8779-edee-4c80-81e3-2f0326deec09)

**Comment by Aokromes** [comment]
it fixes your issue, if you don't like to use betas you will continue to have crashes.
