### ISSUE TITLE
Translate button is not shown upon right click on any message

### ISSUE THREAD

**Issue by amirrh6** [telegramdesktop/tdesktop#26960]
### Steps to reproduce

1. Just right-click on a (preferably non-English) message to trigger the option menu.

### Expected behaviour

The option menu should contain 'Translate' option, just like Telegram for Android.

### Actual behaviour

The 'Translate' option is not displayed at all in option menu.

![Recording 2023-10-23 at 13 01 46](https://github.com/telegramdesktop/tdesktop/assets/65363030/3ac51e3b-0301-4c43-a8cc-27f489e33bd6)

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.10.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
you have translate enabled on settings?

**Comment by amirrh6** [comment]
@Aokromes My bad! I had searched every setting menu for Translation except for 'Language' which I thought it only allows setting the program's language.
