### ISSUE TITLE
Hide stickers / Compact view option 

### ISSUE THREAD

**Issue by TushieSushies** [telegramdesktop/tdesktop#26967]
### Is your feature request related to a problem?

I’d like to disable viewing stickers when in public, I’ve had people join public group chats and sent porn stickers. Or even when I am just scrolling in personal conversations, I’d like the stickers/gifs/media to be hidden in public because they may contain personal / questionable material 

### Describe the solution you'd like

An option to disable/hide stickers and/or gifs/media, perhaps even resize (they’re huge and take a lot of screen real estate) 

### Describe alternatives you've considered

I’ve considered asking everyone in the chat / group to not send stickers / gifs / questionable media but its not feasible

**Comment by ilya-fedin** [comment]
#6999
