### ISSUE TITLE
Flatapk installation desktop icon doesnt work

### ISSUE THREAD

**Issue by clot27** [telegramdesktop/tdesktop#26964]
### Steps to reproduce

Install telegram desktop through flatpak, click on desktop icon created.

### Expected behaviour

App should open

### Actual behaviour

Nothing happens, app doesnt open.

### Operating system

NixOS 23.05

### Version of Telegram Desktop

4.10.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Can't reproduce, works just fine

**Comment by pedohorse** [comment]
a known problem, see discourse for a workaround: https://discourse.nixos.org/t/flatpak-telegram-desktop-desktop-entry-problems/31374/2

**Comment by clot27** [comment]
@pedohorse indeed the solution works, seems like issue with nixos.
