### ISSUE TITLE
Import previous exported chats from telegram

### ISSUE THREAD

**Issue by aradng** [telegramdesktop/tdesktop#26977]
### Is your feature request related to a problem?

A bug in telegram mobile (android) caused an entire chat to disappear from my side instead of a single date delete (did not give me an undo chance). but the data was present on the recipient's device and i managed to export our chat history in both html and Json format. BUT there is no option to import that data back in.

### Describe the solution you'd like

Would be great to implement a feature to allow chat imports from previous telegram exports.

### Describe alternatives you've considered

or sync the chat if counter part has the messages and agrees.

### Additional context

this has happened to me couple of times where instead of deleting a date range in mobile, telegram deletes the entire thing and support has been unresponsive about it for basicly a year! and there's an open issue that has gone unresolved #7201 for the past three years!

**Comment by 23rd** [comment]
https://bugs.telegram.org/c/1221
