### ISSUE TITLE
Lost Premium account even had Two-way verification ON

### ISSUE THREAD

**Issue by dyarbots** [telegramdesktop/tdesktop#26970]
### Steps to reproduce

I lost premium account and when  I try to login New account is opening.

### Expected behaviour

It should open my old account but it is saying that this email or number never had a account.

### Actual behaviour

In the last week of April I converted my account to Premium and in couple of days I lost my account. I tried to tweet or contact on telegram from last 5 months and never get a reply from them as they are not even care. Now I am again trying my best to contact and solve my issue. 
I have a channel with thousands of subscribers and when i search the channel is showing but I can't access it but it can be seen by everyone. Please let me know what i have to do to get my account back.

### Operating system

?

### Version of Telegram Desktop

/

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Can you share the username of the channel?

**Comment by john-preston** [comment]
You can write me at t.me/preston

**Comment by dyarbots** [comment]
I left a message please check
