### ISSUE TITLE
TG Desktop doesnt open tg://resolve links from browser

### ISSUE THREAD

**Issue by NothingPersona1** [telegramdesktop/tdesktop#26972]
### Steps to reproduce

1. Install TG Destop (installer, not portable)
2. Try to open link (t.me format) in Chrome browser (for ex https://t.me/telegram)
3. Clicking on VIEW IN TELEGRAM button does nothing (for ex tg://resolve?domain=telegram)

![image](https://github.com/telegramdesktop/tdesktop/assets/36360262/4ef478fb-3d57-4df5-b089-36c66f80ef84)

### Expected behaviour

Open target channel/chat in the tg desktop

### Actual behaviour

nothing happens

### Operating system

Windows 11

### Version of Telegram Desktop

4.10.2 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by leonardops27** [comment]
are hacking Telegram via PC. The Ubuntu store app is vulnerable.

**Comment by NothingPersona1** [comment]
I installed a clean licensed win11
