### ISSUE TITLE
tdesktop is crashing after closing DurgerKing webapp

### ISSUE THREAD

**Issue by artemiialessandrini** [telegramdesktop/tdesktop#26978]
### Steps to reproduce

1. Run `./Telegram -platform xcb`
2. Open official [DurgerKing](https://t.me/DurgerKingBot) bots WebApp by `MENU` Button
3. Click randomly, opening and closing the WebApp 2-3 times

### Expected behaviour

WebApp is closing and Telegram is alive

### Actual behaviour

WebApp is closing but Telegram crashes

### Operating system

20.04.1-Ubuntu SMP

### Version of Telegram Desktop

Version 4.10.5 beta

### Installation source

Static binary from official website

### Crash ID

02ec3710-e07e-487f-03f588aa-f4bf8459

### Logs

```shell
qt.waylandcompositor.hardwareintegration: Failed to initialize EGL display. Could not get EglDisplay for window.

(Telegram:54123): GLib-GIO-WARNING **: 19:05:38.474: Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal.  It should do one of these.

(Telegram:54123): Gdk-CRITICAL **: 19:05:38.527: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(Telegram:54123): Gdk-CRITICAL **: 19:05:38.527: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(Telegram:54123): Gdk-CRITICAL **: 19:05:38.527: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(Telegram:54123): Gdk-CRITICAL **: 19:05:38.527: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(Telegram:54123): Gdk-CRITICAL **: 19:05:38.527: gdk_monitor_get_workarea: assertion 'GDK_IS_MONITOR (monitor)' failed

(Telegram:54123): Gdk-CRITICAL **: 19:05:38.527: gdk_monitor_get_workarea: assertion 'GDK_IS_MONITOR (monitor)' failed
WaylandCompositor requires eglBindWaylandDisplayWL, eglUnbindWaylandDisplayWL and eglQueryWaylandBuffer.
Nested Wayland compositor could not initialize EGL
Segmentation fault (core dumped)
```

`echo $XDG_SESSION_TYPE`: x11

**Comment by ilya-fedin** [comment]
Does it crash with `GDK_GL=disable`?

**Comment by artemiialessandrini** [comment]
Still fails, while running `./Telegram  GDK_GL=disable`

**Comment by ilya-fedin** [comment]
no, it should be `GDK_GL=disable ./Telegram`

**Comment by shalmeo** [comment]
Telegram Desktop Version 4.11.7
OS: Manjaro Linux x86_64
DE: GNOME 45.1

In my case Web App takes forever to load
![image](https://github.com/telegramdesktop/tdesktop/assets/96947945/83709bc0-3991-49c4-826d-b3ee8cd070cd)

And in the logs we can see
![image](https://github.com/telegramdesktop/tdesktop/assets/96947945/9c441e75-8e17-4180-a679-f7997c1d75fd)

I’ll highlight the most important thing, at the moment you click on the web app
`Gdk-Message: 02:02:35.304: Error 71 (Protocol error) dispatching to Wayland display.`

`qt.waylandcompositor.hardwareintegration: Failed to initialize EGL display. Could not get EglDisplay for window.`

`(Telegram:61878): GLib-GIO-WARNING **: 02:02:35.874: Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal`

`Gdk-Message: 02:02:35.988: Error 71 (Protocol error) dispatching to Wayland display.`

Was there a similar issue? Give me a link or help solve the problem please

**Comment by ilya-fedin** [comment]
@shalmeo it's not loading, it's crashed. tdesktop doesn't have crash handling for webview so it's just an empty window.

**Comment by shalmeo** [comment]
> @shalmeo it's not loading, it's crashed. tdesktop doesn't have crash handling for webview so the window doesn't react.

Do you have any ideas to solve the problem?

Do I need to open an issue to solve my problem? I just really need in webapp in my system

**Comment by ilya-fedin** [comment]
The only environment where webapps are known to work without problems on Linux is KDE X11.

**Comment by artemiialessandrini** [comment]
> no, it should be `GDK_GL=disable ./Telegram`

Also crashing, in the same way.
After clicking Telegram WebApp MainButton with: `(Telegram:9222): Gdk-CRITICAL **: 14:20:23.373: gdk_monitor_get_workarea: assertion 'GDK_IS_MONITOR (monitor)' failed
WaylandCompositor requires eglBindWaylandDisplayWL, eglUnbindWaylandDisplayWL and eglQueryWaylandBuffer.
Nested Wayland compositor could not initialize EGL
Segmentation fault (core dumped)
`

**Comment by ilya-fedin** [comment]
@artemiialessandrini are you sure Telegram is not already running when you start it via command? As it will just focus the window of already running instance otherwise.

**Comment by artemiialessandrini** [comment]
> @artemiialessandrini are you sure Telegram is not already running when you launch it via command? As it will just focus the window of already running instance otherwise.

Well, I have other instances of Telegram installed by snap, apt, but it's not running.

**Comment by artemiialessandrini** [comment]
> The only environment where webapps are known to work without problems on Linux is KDE X11.

I'm doing telegram bot with a webapp development, would you suggest switching to KDE X11 in that matter as a workaround?

**Comment by ilya-fedin** [comment]
> Well, I have other instances of Telegram installed by snap, apt, but it's not running.

I mean the binary could be running. People often just close window instead of quitting via tray icon and then ensuring it's actually not running (there are reports Telegram can get some deadlock and not quit actually) via process list (e.g. `ps aux | grep Telegram`).

**Comment by ilya-fedin** [comment]
> I'm doing telegram bot with a webapp development, would you suggest switching to KDE X11 in that matter as a workaround?

Yes.

**Comment by ilya-fedin** [comment]
@artemiialessandrini can you check whether `LIBGL_ALWAYS_SOFTWARE=1` helps?
