### ISSUE TITLE
Unpausing media hangs the application

### ISSUE THREAD

**Issue by Qunas101** [telegramdesktop/tdesktop#26975]
### Steps to reproduce

1. Open a video or start playing music
2. Pause for more than 2 seconds
3. Try to resume playback

### Expected behaviour

Should resume playback immediately and not freeze

### Actual behaviour

Freezes for 1-2 seconds before resuming

### Operating system

Endeavour OS (Linux), KDE Plasma

### Version of Telegram Desktop

4.10.3 from Arch repo

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by Qunas101** [comment]
Okay, so the official binary doesn't have this issue
