### ISSUE TITLE
The damn file ordering on upload doesn't exist....

### ISSUE THREAD

**Issue by Porkechebure** [telegramdesktop/tdesktop#26971]
### Steps to reproduce

https://github.com/Ajaxy/telegram-tt/issues/300
Same as here

### Expected behaviour

Files are ordered or there is a way to do it

### Actual behaviour

Files are ordered by using who knows what, probably an algorithm called stupid sort (which actually exists)
All described here, this happens on web and app, no difference
https://github.com/Ajaxy/telegram-tt/issues/300

### Operating system

Windows 10 x64

### Version of Telegram Desktop

every

### Installation source

Static binary from official website

**Comment by poliandro** [comment]
This happens only when you use drag and drop. If you use the upload button, all the files will be uploaded in the right order.

**Comment by Aokromes** [comment]
files are upload on the way windows is ordered and the file you have selected.

**Comment by ilya-fedin** [comment]
Windows most likely orders them in the order they're written to disk

**Comment by Porkechebure** [comment]
@poliandro  @Aokromes @ilya-fedin 
Any way that when you upload filesit also puts the caption with the file name automatically?

**Comment by ilya-fedin** [comment]
@Porkechebure i don't quite understand the question

**Comment by ilya-fedin** [comment]
I believe there's already a feature request for that

**Comment by poliandro** [comment]
@Porkechebure No, is not possible with the official clients, but there are scripts that can do that. It will be a nice feature, maybe make a request for this? It will have some advantages in at least 2 situations:
1. Videos. Now they appear in chat without any name, you cannot identify them
2. Files with long names. Telegram cuts the name short, some 60 characters if I remember correctly, so long names will be lost.

**Comment by Porkechebure** [comment]
> @Porkechebure No, is not possible with the official clients, but there are scripts that can do that. It will be a nice feature, maybe make a request for this? It will have some advantages in at least 2 situations:
> 
> 1. Videos. Now they appear in chat without any name, you cannot identify them
> 2. Files with long names. Telegram cuts the name short, some 60 characters if I remember correctly, so long names will be lost.

Yep, that file name cut thing is a cancer, it must be managed to keep the full name saved.
Imagine when uploading a zip splitted file with long name like 

filelongnameeeeeeeeeeeeeeeeeeeeeeeee.zip..01
filelongnameeeeeeeeeeeeeeeeeeeeeeeee.zip..02
filelongnameeeeeeeeeeeeeeeeeeeeeeeee.zip..03
filelongnameeeeeeeeeeeeeeeeeeeeeeeee.zip..04

And you loose track of what is each part. Chaos will arise

**Comment by poliandro** [comment]
And on top oh that, you cannot change the file name, you have to upload the file again with new name.
