### ISSUE TITLE
build failed when using docker

### ISSUE THREAD

**Issue by c0re100** [telegramdesktop/tdesktop#26982]
### Steps to reproduce

1. Follow docker instructions

### Expected behaviour

It should build without issue.

### Actual behaviour

After `docker run --rm -it`........
I got error result
```
[22/1521] Generating D-Bus C code for XdpInhibit (Telegram)
FAILED: Telegram/gen/dbus/Telegram_XdpInhibit_dbus.timestamp Telegram/gen/dbus/Telegram_XdpInhibit_dbus.c Telegram/gen/dbus/Telegram_XdpInhibit_dbus.h /usr/src/tdesktop/out/Telegram/gen/dbus/Telegram_XdpInhibit_dbus.timestamp /usr/src/tdesktop/out/Telegram/gen/dbus/Telegram_XdpInhibit_dbus.c /usr/src/tdesktop/out/Telegram/gen/dbus/Telegram_XdpInhibit_dbus.h 
cd /usr/src/tdesktop/out/Telegram && /usr/local/bin/gdbus-codegen --interface-prefix org.freedesktop.portal. --generate-c-code /usr/src/tdesktop/out/Telegram/gen/dbus/Telegram_XdpInhibit_dbus --c-namespace XdpInhibit --c-generate-object-manager /usr/src/tdesktop/Telegram/SourceFiles/platform/linux/org.freedesktop.portal.Inhibit.xml && echo 1> /usr/src/tdesktop/out/Telegram/gen/dbus/Telegram_XdpInhibit_dbus.timestamp
Traceback (most recent call last):
  File "/usr/local/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
ImportError: cannot import name 'codegen_main' from 'codegen' (unknown location)
```

### Operating system

Arch Linux

### Version of Telegram Desktop

4.11

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Looks like codgen installation is broken in glib. Looking at glib's commit history, https://gitlab.gnome.org/GNOME/glib/-/commit/4ce58df8540f25f823418a1d45ddb07ada52ec22 is probably at fault. Either someone should report this to them or we have to wait until they notice on their own and fix that...

**Comment by ilya-fedin** [comment]
@Aokromes closing this is a bad idea as people are likely to arrive here as the Docker images resulting from the Dockerfile are broken currently.

**Comment by rafitamolin** [comment]
> Looks like codegen installation is broken in glib, `/usr/local/share/glib-2.0/codegen` is almost empty. Looking at glib's commit history, https://gitlab.gnome.org/GNOME/glib/-/commit/4ce58df8540f25f823418a1d45ddb07ada52ec22 is probably at fault. Either someone should report this to them or we have to wait until they notice on their own and fix that...

reported here: https://gitlab.gnome.org/GNOME/glib/-/issues/3161

**Comment by EugenySychev** [comment]
Is there any workaround for build it?

**Comment by x09** [comment]
I need solution too.

**Comment by EugenySychev** [comment]
> I need solution too.
You can try to add `cp -f /usr/share/glib-2.0/codegen/* /usr/local/share/glib-2.0/codegen/` into the build.sh before running build steps.

**Comment by x09** [comment]
> > I need solution too.
> > You can try to add `cp -f /usr/share/glib-2.0/codegen/* /usr/local/share/glib-2.0/codegen/` into the build.sh before running build steps.

 tdesktop $ find -name build.sh
./Telegram/ThirdParty/QR/typescript-javascript/build.sh
./Telegram/build/build.sh
./Telegram/build/docker/centos_env/build.sh
./Telegram/build/docker/build.sh

could you specify?

**Comment by EugenySychev** [comment]
> could you specify?
Telegram/build/docker/centos_env/build.sh 
который при билде докера дергается.

**Comment by x09** [comment]
> > could you specify?
> > Telegram/build/docker/centos_env/build.sh
> > который при билде докера дергается.

cat ./Telegram/build/docker/centos_env/build.sh
```
#!/bin/bash
set -e

cd Telegram
./configure.sh "$@"

if [ -n "$DEBUG" ]; then
	cmake --build ../out --config Debug --parallel
else
	cmake --build ../out --config Release --parallel
fi

```

Я не понимаю откуда и куда, а главное зачем что-то копировать.
cp -f /usr/share/glib-2.0/codegen/* /usr/local/share/glib-2.0/codegen/ - смысл этого?

**Comment by EugenySychev** [comment]
> > > could you specify?
> > > Telegram/build/docker/centos_env/build.sh
> > > который при билде докера дергается.
> 
> cat ./Telegram/build/docker/centos_env/build.sh
> 
> ```
> #!/bin/bash
> set -e
> 
> cd Telegram
> ./configure.sh "$@"
> 
> if [ -n "$DEBUG" ]; then
> 	cmake --build ../out --config Debug --parallel
> else
> 	cmake --build ../out --config Release --parallel
> fi
> ```
> 
> Я не понимаю откуда и куда, а главное зачем что-то копировать. cp -f /usr/share/glib-2.0/codegen/* /usr/local/share/glib-2.0/codegen/ - смысл этого?

Ну как "зачем" - сейчас при вызове codegen  не может найти эти модули, потому как их установку убили в глибе, а вот эта команда она их копирует (по сути устанавливает). Я ставил перед cd Telegram. Собралось после этого.

**Comment by c0re100** [comment]
Basically, It works.
But in my first try, it was failed because std::string has no member 'value_or'.
That's weird lol
So I've removed `cp` in second time, and everything fines.

**Comment by ilya-fedin** [comment]
The codegen of the older glib generates other code so the resulting API is different.

**Comment by ilya-fedin** [comment]
If copying works, `-DDESKTOP_APP_GDBUSCODEGEN=/usr/bin/gdbus-codegrn` should work just as well

**Comment by xxxdens** [comment]
> If copying works, `-DDESKTOP_APP_GDBUSCODEGEN=/usr/bin/gdbus-codegen` should work just as well
where should this line be used? Thanks!

**Comment by EugenySychev** [comment]
> > If copying works, `-DDESKTOP_APP_GDBUSCODEGEN=/usr/bin/gdbus-codegen` should work just as well
> 
> where should this line be used? Thanks!

When you run the build by 'docker run blablabla' you should add this at the end.
