### ISSUE TITLE
Crash when changing status emoji in v4.11

### ISSUE THREAD

**Issue by suprunchuk** [telegramdesktop/tdesktop#26980]
### Steps to reproduce

0. You are a premium user.

1. Install version 4.11.
2. Change the emoji status.

### Expected behaviour

Status changes successfully

### Actual behaviour

When I try to change my emoji status the app crashes

Crash ID: 
69864b1c-0870-4f86-a02f-22d0d7a8bc56
ec6684a2-50e5-403e-94e2-57a4f1eab0e8
9a06278a-d009-4d9c-936b-dc73ba870903

### Operating system

windows x64

### Version of Telegram Desktop

4.11 x64

### Installation source

Static binary from official website

### Crash ID

c1a8eee4-7273-465b-890f-7277e1d3681d

### Logs

```shell
ApiId: 2040
Binary: Telegram.exe
Launched: 29.10.2023 01:03:45
OpenGL ANGLE: Auto
OpenGL Renderer: [not-initialized]
Platform: Windows64Bit
Version: 4011000
Memory-usage: 356 MB (peak), 330 MB (current)
Pagefile-usage: 364 MB (peak), 326 MB (current)
```

**Comment by john-preston** [comment]
Fixed with https://github.com/telegramdesktop/tdesktop/commit/04f040c9c55cd318b72deb0abac9cadae8e319ab
