### ISSUE TITLE
Image embeds open URLs

### ISSUE THREAD

**Issue by Izofeu** [telegramdesktop/tdesktop#26984]
### Steps to reproduce

1. Click on an image in an embed (X embed for example)

### Expected behaviour

The full image gets opened in Telegram.

### Actual behaviour

Web browser opens with the embed's URL.
Started happening since 4.11 and present in 4.11.1. Affects both Windows & Android.
If this is intentional then a toggle would be greatly appreciated, specially considering that if I wanted to open the embed's url, I'd click on the url instead of the image.

### Operating system

Windows 10

### Version of Telegram Desktop

4.11+

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
It's intended, TDesktop reflects the Android app mechanics. If it'll be changed on Android, it'll be changed on TDesktop as well. You can post (or vote for existing, if any) such report on https://bugs.telegram.org. It works on iOS latest update the same way, so this is platform-wide.

**Comment by f242** [comment]
@john-preston when will the mechanics of changing font size for messages be implemented?

**Comment by Xiarno** [comment]
> It's intended, TDesktop reflects the Android app mechanics. If it'll be changed on Android, it'll be changed on TDesktop as well. You can post (or vote for existing, if any) such report on https://bugs.telegram.org. It works on iOS latest update the same way, so this is platform-wide.

Please at least add a toggle because holy this is annoying.

**Comment by Izofeu** [comment]
https://bugs.telegram.org/c/33656
It's intended behavior and I guess that means we won't get a toggle. Yikes. If anyone has any solution that doesn't involve disabling updates, I'm all in.

**Comment by Xiarno** [comment]
> https://bugs.telegram.org/c/33656 It's intended behavior and I guess that means we won't get a toggle. Yikes. If anyone has any solution that doesn't involve disabling updates, I'm all in.

Well if you already did the update you're kinda fricked...

**Comment by Izofeu** [comment]
Nah it's fine. I'll simply downgrade, I'm fine with missing on the new features. I of course don't blame this repo's manager but rather the person responsible for this design decision as a whole (for the Android app).

**Comment by Xiarno** [comment]
> Nah it's fine. I'll simply downgrade, I'm fine with missing on the new features. I of course don't blame this repo's manager but rather the person responsible for this design decision as a whole (for the Android app).

How do you downgrade?

**Comment by Izofeu** [comment]
> > Nah it's fine. I'll simply downgrade, I'm fine with missing on the new features. I of course don't blame this repo's manager but rather the person responsible for this design decision as a whole (for the Android app).
> 
> How do you downgrade?

PC Version:
- SAVE YOUR SETTINGS FIRST (like export them or something), they WILL get lost
- download 4.10.2 from this github page
- run the installer
- install over previous telegram install
- open it, log in
- disable autoupdate from settings
- delete tUpdates folder from telegram's directory
- restart telegram

**Comment by BoffinBrain** [comment]
> It's intended, TDesktop reflects the Android app mechanics. If it'll be changed on Android, it'll be changed on TDesktop as well. You can post (or vote for existing, if any) such report on https://bugs.telegram.org. It works on iOS latest update the same way, so this is platform-wide.

Has anyone made a request for this yet so I can vote on it?

**Comment by Izofeu** [comment]
> > It's intended, TDesktop reflects the Android app mechanics. If it'll be changed on Android, it'll be changed on TDesktop as well. You can post (or vote for existing, if any) such report on https://bugs.telegram.org. It works on iOS latest update the same way, so this is platform-wide.
> 
> Has anyone made a request for this yet so I can vote on it?

https://bugs.telegram.org/c/33679
I doubt they'll change it however. I'm simply not updating to the newest version.

**Comment by john-preston** [comment]
@Izofeu I'll add a button in the corner for now.

**Comment by Xiarno** [comment]
> @Izofeu I'll add a button in the corner for now.

Why not the opposite?
The preview image open it in Telegram like it was before and the corner button open the link?

At that point it wouldn't be that much different than just opening the link itself but that is the point and why everyone is disliking that change.

**Comment by Aokromes** [comment]
> > @Izofeu I'll add a button in the corner for now.
> 
> Why not the opposite? The preview image open it in Telegram like it was before and the corner button open the link?
> 
> At that point it wouldn't be that much different than just opening the link itself but that is the point and why everyone is disliking that change.

because the current way it's intended to be platform wide.

**Comment by Xiarno** [comment]
> > > @Izofeu I'll add a button in the corner for now.
> > 
> > 
> > Why not the opposite? The preview image open it in Telegram like it was before and the corner button open the link?
> > At that point it wouldn't be that much different than just opening the link itself but that is the point and why everyone is disliking that change.
> 
> because the current way it's intended to be platform wide.

I know it's intended but I still don't understand why the change was made in the first place. It was perfectly fine before.

**Comment by Aokromes** [comment]
> > > > @Izofeu I'll add a button in the corner for now.
> > > 
> > > 
> > > Why not the opposite? The preview image open it in Telegram like it was before and the corner button open the link?
> > > At that point it wouldn't be that much different than just opening the link itself but that is the point and why everyone is disliking that change.
> > 
> > 
> > because the current way it's intended to be platform wide.
> 
> I know it's intended but I still don't understand why the change was made in the first place. It was perfectly fine before.

becuase who is in charge decided it to be on this way.

**Comment by Izofeu** [comment]
Like I said, blame the management of Telegram, not the author of this repo.
