### ISSUE TITLE
Caption Markdown

### ISSUE THREAD

**Issue by Pezhvak** [telegramdesktop/tdesktop#2698]
### Steps to reproduce
1. create a bot
2. try to send a file (like audio file with caption that contains some markup)
3. you will see it's not working

### Expected behaviour
Tell us what should happen
It should render B,I,STRONG,EM,A tags.

### Actual behaviour
Tell us what happens instead
it sends markdown tag as a text.

### Configuration
**Operating system:**
MacOS Sierra
**Version of Telegram Desktop:**
0.10.19
### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by stek29** [comment]
Seems bot API issue, and not related to TDesktop at all
