### ISSUE TITLE
Can't download and play open graph video

### ISSUE THREAD

**Issue by ArianHamdi** [telegramdesktop/tdesktop#26988]
### Steps to reproduce

1. send a link that has open graph video.
2. click on download button on the top-left corner of the video
3. it will try to open the link instead of downloading video

### Expected behaviour

Download the video without opening the link

### Actual behaviour

it will try to open the link instead of downloading video

### Operating system

MacOS 14.1

### Version of Telegram Desktop

4.11

### Installation source

Static binary from official website

**Comment by Clawthorn** [comment]
This also occurs with images!

In the previous version you were able to click on embedded images/thumbnails to enlarge them. Now instead it tries opening the link in a browser, which entirely ruins the usefulness of "twitter fixers" such as fxtwitter/vxtwitter, and even Bluesky links.

**Comment by ilya-fedin** [comment]
Update to the latest version

**Comment by ArianHamdi** [comment]
> Update to the latest version

Nice fixed in 4.11.1
