### ISSUE TITLE
Telegram doesnt start on Fedora 38

### ISSUE THREAD

**Issue by 0n1cOn3** [telegramdesktop/tdesktop#26985]
### Steps to reproduce

1. Install tdesktop
2. Execute the executable via terminal (cause theres no error when I double click on Telegram executable)
3. Get this error: symbol lookup error: ./Telegram: undefined symbol: g_resolver_get_timeout

### Expected behaviour

It should start. I have even resetted my whole laptop to be sure its not about my system. But the issue still perists after a fresh os install

### Actual behaviour

./Telegram: symbol lookup error: ./Telegram: undefined symbol: g_resolver_get_timeout

### Operating system

Fedora 38

### Version of Telegram Desktop

4.11.0 and earlier

### Installation source

Static binary from official website

### Logs

```shell
See at actual behaviour
```

**Comment by john-preston** [comment]
Can you please try the version from https://github.com/telegramdesktop/tdesktop/releases/v4.11.1?

**Comment by ilya-fedin** [comment]
I'm unable to find such symbol in the official build
```
 /Telegram  readelf -Ws Telegram | grep g_resolver_get_timeout
   /Telegram  
```
Looks like

> ### Installation source
> 
> Static binary from official website

is false info

**Comment by 0n1cOn3** [comment]
> Can you please try the version from https://github.com/telegramdesktop/tdesktop/releases/v4.11.1? This one:
> 
> 
> 
> https://github.com/telegramdesktop/tdesktop/releases/download/v4.11.1/tsetup.4.11.1.tar.xz

Horray! I can finally start Telegram again on my Fedora boxes! After 3 months 🙂

Latest Release fixed the symbol issue for sure 👍🏻
