### ISSUE TITLE
"Reply in Another Chat" doesn't work for group topics

### ISSUE THREAD

**Issue by ShahriarKh** [telegramdesktop/tdesktop#26986]
### Steps to reproduce

1. Go to (or create) a group with topics
2. Select a message in topic "A" -> Reply -> Reply In Another Chat -> Select topic "B"
3. Write your reply

### Expected behaviour

The reply should be shown in topic "B"

### Actual behaviour

The reply is shown in topic "A"

### Operating system

Windows 10

### Version of Telegram Desktop

4.11

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
how this works on android?

**Comment by john-preston** [comment]
@Aokromes Yeah, this is not correct in tdesktop, should be fixed.

**Comment by ShahriarKh** [comment]
Fixed in 4.11.2. Thanks!
