### ISSUE TITLE
Wrong behavior of link previews (attached images open as link)

### ISSUE THREAD

**Issue by bertmsk** [telegramdesktop/tdesktop#26997]
### Steps to reproduce

Embed any link to page which contains an image. (Twitter for example)
Try to open image from the "link preview"

### Expected behaviour

The image attached to the link opens internally by Telegram

### Actual behaviour

Telegram opens image as link with web browser

### Operating system

Windows (tested with Android version as well)

### Version of Telegram Desktop

4.11.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#26984

**Comment by Izofeu** [comment]
Upvote [this](https://bugs.telegram.org/c/33679) suggestion if you want to get it "fixed".

**Comment by bertmsk** [comment]
> Upvote [this](https://bugs.telegram.org/c/33679) suggestion if you want to get it "fixed".

That's meaningless. Look how many users voted for "disabling stories" (https://bugs.telegram.org/c/30207) -- a must have feature right after the "stories" have been invented. 
I see improving the users' "quality of life" isn't main goal of Telegram's dev team. The things go only worse after each update because there's no feedback response to users needs. Just nonsense replies about "that was intended" or "we're just using Windows/Android/whatever guidlines"

Multiple colors (and even icons) in quotations for example makes visual noise. There's no padding between quoted text and reply. Is UX even been tested?

**Comment by Izofeu** [comment]
I simply downgraded to the previous version and disabled autoupdate. I'm sick of these untested, unwanted updates that nobody asked for and updates that are not discussed with the userbase at all.
