### ISSUE TITLE
Inconsistent behavour with quotes

### ISSUE THREAD

**Issue by SpL1Ne** [telegramdesktop/tdesktop#26996]
### Steps to reproduce

First issue: Reply to message in another chat.
Second issue: Make a quote reply.

### Expected behaviour

On android:
First issue: you can open replied message to see it's whole text.
Second issue: on quote click you moved to original message and quoted text is highlighted.

### Actual behaviour

On PC:
First issue: Opens profile info instead of whole message to which replied.
Second issue: Scrolls to original message without highlighting quoted text.

### Operating system

Win10 22H2

### Version of Telegram Desktop

4.11.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Yes, this is not implemented correctly yet. It's planned at some point.
