### ISSUE TITLE
Allow for more than 5 favourite stickers

### ISSUE THREAD

**Issue by 8fuhst** [telegramdesktop/tdesktop#26994]
### Is your feature request related to a problem?

Currently, when adding stickers to favourites, only the last 5 added stickers will actually be available under the "Favourites" section. Since I use a lot of stickers from different packs, this is very annoying.

### Describe the solution you'd like

I'd like to be able to add more than five stickers to my favourites, s.t. they are displayed like just another pack on top of all the other packs.

### Describe alternatives you've considered

Maybe it would help to be able to "tag" stickers with user-chosen strings, such that stickers become searchable by those tags to the user (the tags would only be set for the user and they would not be able to see the tags of others).

### Additional context

Maybe this is not a telegram desktop issue per se, as this is the same case in the android app. If it's rather related to e.g. the API, I'd be thankful for someone pointing me in the right direction as to where I should open an Issue instead.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
