### ISSUE TITLE
Tray icon visibility problems after the latest update

### ISSUE THREAD

**Issue by alexchexes** [telegramdesktop/tdesktop#26991]
### Steps to reproduce

1. Install the latest stable version of Telegram Desktop.
2. Attempt to locate the Telegram icon in the system tray as you normally would.
3. Notice that the Telegram icon in the system tray has been redesigned and it is now hard to spot. Further observe that a light-gray badge, indicating a truncated number of unread messages (e.g., "...5"), overlaps with the new very-light-gray Telegram icon, making it even more difficult to see.

### Expected behaviour

I expect to see a Telegram icon that is easy to spot in the system tray among the others. When you have multiple tray icons and their order may change, a unique and familiar icon is vital for quickly spotting the app when you need to open it. Additionally, an icon that is not obscured by a badge with meaningless information, such as the "...5" badge when you actually have 12,005 messages, would be much more useful.

### Actual behaviour

1. The new icon in the system tray has undergone a redesign, making it less distinguishable among other tray icons. Furthermore, this tray icon is inconsistent with Telegram icons seen in other locations, like the Start menu, window header, and desktop shortcut.
2. A light-gray badge displaying "...5" overlaps the new, very-light-gray Telegram icon. This badge feels more like a problem than something useful, as it not only overlaps the Telegram icon but also fails to provide useful information when you have a large number of unread messages. While it's debatable whether a badge indicating "12,000 unread messages in muted chats" is useful in the first place (given that these chats are deliberately muted), the badge showing something like "...5" for 12,005 messages is clearly uninformative.

![image](https://github.com/telegramdesktop/tdesktop/assets/49966773/d0983513-158e-49d6-b098-537638a2a09c)

### Operating system

Windows 10 21H2 LTSC

### Version of Telegram Desktop

4.11.1 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/26989

**Comment by navossoc** [comment]
I don't know why people like to change their app icons. You spend years using and looking for the old blue icon, but suddenly everything changes and you have to start all over again.

**Comment by alexchexes** [comment]
> #26989

I searched the existing issues and started writing this one before #26989 was created, but finished it later, so the current issue is now closed as a duplicate `:(`

However, the main complaint in #26989 is about the new design of the Telegram icon itself, not the fact that on some Windows setups the counter overlaps the new icon, making it hard to spot especially when the counter is gray (i.e., it shows messages from muted chats).
