### ISSUE TITLE
Search within a channel doesn't work for me in Linux

### ISSUE THREAD

**Issue by AngryPhantom** [telegramdesktop/tdesktop#26995]
### Steps to reproduce

1. Choose a channel
2. Press a lens icon
3. Start typing to search something

### Expected behaviour

Should give me at least ANY search results when I start typing.

### Actual behaviour

Searching ANY text withing a channel doesn't give me results. It doesn't work for me in any distro. Never worked actually.

Here's the screenshot: https://pixhost.to/show/487/394572954_1.png

I've tried both variants 'GPT' and 'gpt'. Doesn't matter.

Am I doing something wrong?

TIA

### Operating system

Arch Linux

### Version of Telegram Desktop

4.11.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Are you sure it's Linux-only problem? Cause I feel the query on screenshot won't find anything on any platfrom as the server has only whole word search.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by AngryPhantom** [comment]
> Are you sure it's Linux-only problem? Cause I feel the query on screenshot won't find anything on any platfrom as the server has only whole word search.

@ilya-fedin I don't use Windows so I'm not aware of that. I see the issue is closed now. How can I make a feature request? Imho, whole word search is a bit odd. At least you can search any text, word parts, whatever in any decent application (browsers, text editors etc.). It would be really great if the devs could implement adequate search function. It's really needed to find some news or articles in channels that are too big (actually they are all big). It's just often impossible to remember the **exact whole word**.

**Comment by AngryPhantom** [comment]
>https://bugs.telegram.org/

lol, there are tons of 'search' issues and suggestions already. Sorry for my irrelevant Linux-specific issue here. Will just wait for the implementation to come into the app. Cheers.
