### ISSUE TITLE
Replace tray icon with OS-styled one

### ISSUE THREAD

**Issue by baterflyrity** [telegramdesktop/tdesktop#26998]
### Is your feature request related to a problem?

New telegram desktop tray icon uses error-style notifications counter.

![image](https://github.com/telegramdesktop/tdesktop/assets/15788974/9bccc707-a573-4440-9413-95c25a45b6d4)

In Windows red is considered to represent errors by OS design. Hence telegram notifications are instinctively considered as something bad thus user must pay attention twice.

![image](https://github.com/telegramdesktop/tdesktop/assets/15788974/146c3eb1-1faf-4540-8fff-fd7c884264bf)
 
In the example above it is too hard for user to distinguish OS errors and telegram new messages.

### Describe the solution you'd like

I would like to use neutral color for telegram notifications (neither green nor red). Basically it should be changeable but e.g. old blue style is good enough.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/26989

**Comment by baterflyrity** [comment]
Sry for duplicate.
