### ISSUE TITLE
CodeBlock ...

### ISSUE THREAD

**Issue by MaBo2022** [telegramdesktop/tdesktop#26999]
### Is your feature request related to a problem?

---

### Describe the solution you'd like

... please a Toggle / Switcher to turn ON or OFF the new CodeBLock, Thanks, it look not good in every Messages or ChannelDescription (see PIC) :)

![ScreenShot vom 29 10 2023, 18 14 33 Uhr](https://github.com/telegramdesktop/tdesktop/assets/98895587/ced6b86f-c788-4c1e-ac9a-9bcec10a527c)

SORRY MY ENGLISH, IAM GERMAN ...

### Describe alternatives you've considered

---

### Additional context

---

**Comment by guanzo** [comment]
### What kind of feature are you missing? Where do you notice a shortcoming of PTB?

My telegram bot exclusively sends markdown messages. The message content is ASCII tables, JSON, and lots of numbers, all of which benefit visually from markdown's monospace font. The 4.11 update has added a "copy" UI to every markdown message which is obtrusive and ugly.

![image](https://github.com/python-telegram-bot/python-telegram-bot/assets/4676043/506c5a70-987c-4fad-9ee0-077f83987a05)

### Describe the solution you'd like

Make "copy" UI optional, or less prominent, on markdown messages.

### Describe alternatives you've considered

Only show copy UI on mouse hover.

Make the "copy" text display conditionally somehow.

**Comment by john-preston** [comment]
There are two monospace format options in Telegram, one is blocks of monospace, others are inline parts of monospace. If you use the inline type (sent in single ticks ` or somehow else) then it'll look like before. The block type got this upgrade with the header, single-click copy and a dedicated area.

The option to convert block type ones to old layout isn't planned.

**Comment by john-preston** [comment]
So to send the old "part of text is monospace" messages you can send them as inline-monospace tags.

**Comment by kirsan31** [comment]
@john-preston
> There are two monospace format options in Telegram, one is blocks of monospace, others are inline parts of monospace. If you use the inline type (sent in single ticks ` or somehow else) then it'll look like before. 

With single and triples quotes all are clear. But what block will be if we are using `Monospace` from formatting menu? The algorithm is unclear :( And we have many old messages that now receive this new code block :(
For example (this is only one case there are many parsing problems with this):

https://github.com/telegramdesktop/tdesktop/assets/17767561/d97dbbde-b54f-4299-87af-42506277ddfb

**Comment by john-preston** [comment]
Monospace formatting in the menu is flawed, because it tries to guess which one to use. Generally it uses block type formatting if you selected some amount of paragraphs (both edges of the selected block are at a newline) and inline type in case it intersects some line. But this doesn't work very well, so it is easier to use the ticks.

**Comment by kirsan31** [comment]
@john-preston 
> But this doesn't work very well, so it is easier to use the ticks.

And what about multiline without copy block? How to achieve this:
![image](https://github.com/telegramdesktop/tdesktop/assets/17767561/f9f06496-aaa1-40d3-9e02-fae7db8c7352)

**Comment by john-preston** [comment]
Well, this is like surrounding each line in single quotes. Message input field doesn't support that (the fact that you got it for full lines selection looks like a bug, it should've been block monospace part).

**Comment by kirsan31** [comment]
Got it - thank you.

**Comment by guanzo** [comment]
> But how to send multiline code block without new copy bloc?

I don't think this was communicated properly: Apparently you can send multiline strings surrounded with single ticks, and it'll look the same as before this update. Not just for "part of the message", but the entire message.

`msg` is a multiline string (contains `\n` characters). 
Before this update, this code would result in this output:
```py
# Code for 
def sendMarkdown (msg, userId = MY_USER_ID):
    msg = f'```\n{msg}\n```'
    bot.sendMessage(
        userId,
        msg,
        parse_mode=ParseMode.MARKDOWN_V2)
```
![image](https://github.com/telegramdesktop/tdesktop/assets/4676043/719b9f72-632b-4f9d-bcbb-b7e602fe65c1)

After this update, the output is now: 
![image](https://github.com/telegramdesktop/tdesktop/assets/4676043/01777fd4-ea6b-4450-ab82-48e081da8b53)


To get the original output without the "copy" header and extra UI, just use single ticks.
```py
# Uses monospace font which makes formatting data easier.
def sendMarkdown (msg, userId = MY_USER_ID, silent=False):
    msg = f'`{msg}`'
    bot.sendMessage(
        userId,
        msg,
        parse_mode=ParseMode.MARKDOWN_V2,
        disable_notification=silent)
```
