### ISSUE TITLE
KF6 is not yet released.

### ISSUE THREAD

**Issue by microcai** [telegramdesktop/tdesktop#26993]
### Steps to reproduce

when build tdesktop with qt6, it requires kf6CoreAddons which is not yet released.
but @ilya-fedin said that Qt 5 is not supported in telegram-desktop anymore.

### Expected behaviour

build success with qt6 and kf5

### Actual behaviour

configure pharse failed with missing kf6coreaddons

### Operating system

Gentoo

### Version of Telegram Desktop

4.10.5

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
It's nit required, it's an optional dependency. If it's not available, the code falls back to the bundled copy.
