### ISSUE TITLE
Silent crash on cancel of the picture selection dialog at the new group wizard

### ISSUE THREAD

**Issue by DmitriyYukhanov** [telegramdesktop/tdesktop#2699]
### Steps to reproduce
1. Start creating a group: 
![image](https://cloud.githubusercontent.com/assets/883587/21042693/2eadc09a-be04-11e6-9f41-975c06e46dc0.png)
![image](https://cloud.githubusercontent.com/assets/883587/21042701/382aacaa-be04-11e6-9d07-82c0f7362895.png)

2. Press at the empty group photo placeholder:
![image](https://cloud.githubusercontent.com/assets/883587/21042706/409e79ca-be04-11e6-9173-14ca1139d118.png)

3. Cancel the opened file selection dialog:
![image](https://cloud.githubusercontent.com/assets/883587/21042727/615c4f02-be04-11e6-9107-d2339f5753e1.png)

### Expected behaviour
File selection dialog should close and let you continue work with Telegram.

### Actual behaviour
Telegram silently crashes (icon is still at the task bar, but disappears as I over it with mouse cursor).

### Configuration
Windows 10 latest updates.

Telegram 0.10.16

### Logs
Attaching logs, but there is nothing interesting:
[DebugLogs.zip](https://github.com/telegramdesktop/tdesktop/files/641614/DebugLogs.zip)

**Comment by john-preston** [comment]
@DmitriyYukhanov Thank you for your report. This will be fixed in the next version.
