### ISSUE TITLE
~ is gone

### ISSUE THREAD

**Issue by JochemKuijpers** [telegramdesktop/tdesktop#27]
With the latest update, the tilde (the wavy character) is gone.
It has been replaced by a dash?

**Comment by obskyr** [comment]
I really like Open Sans, and would like it to stay. However, I also like using ~, and it rendering as a dash is a problem. I did some research, check it:

![I did my homework.](https://cloud.githubusercontent.com/assets/4363779/5598670/a785ec1c-92ba-11e4-950e-83934a2b2633.png)

What this means is that the tilde hinting breaks at 13px exactly (since 12.5px rounds up to 13px - also sizes below 10px, but that's hardly relevant). Changing the font size up or down one pixel would fix the issue, which is what I propose.

**Comment by phi1010** [comment]
Changing the font size could fail on Windows8, because sizes aren't only measured in pixels anymore, see https://support.microsoft.com/en-us/kb/2900023. A font selection dialog to allow changing both font and size would probably be more helpful.

**Comment by thybak** [comment]
Hi guys!

Do you know if this is going to be 'solved'? It would be helpful to add an option to select the font *and size* We want, don't you think so?

It's annoying to see wrongly the ~ character :[

**Comment by LeoDJ** [comment]
Will there be a public patch, it bothers the hell out of me...

**Comment by ralesk** [comment]
Suspecting FreeType issue https://savannah.nongnu.org/bugs/?23537 which hasn't been worked on since 2008. As mentioned in #950, I poked at the bug listing yesterday, maybe it'll finally stir up the FT developers.

**Comment by Larusek** [comment]
I'm really dissapointed. Over a year of development and such an easy bug is still unresolved. If the font is at fault, why don't you just add custom font selection or at least font size.

**Comment by ralesk** [comment]
There seem to be quite a few fairly trivial issues that nobody cares about :/
I wouldn't say the tilde one is one of them. Some fonts/sizes help, but that's walking around the problem and not actually fixing them. The ball is in FreeType's court, and they haven't bothered with it for years.

**Comment by telegramdesktop** [comment]
@Larusek It is not trivial in case of tdesktop, cause it is quite a complicated thing to make font size larger for one character only, it is not HTML :)

**Comment by Bullsquid** [comment]
@telegramdesktop would it hurt to change font type / font size entirely?

**Comment by telegramdesktop** [comment]
@Bullsquid Yes, that is not an option. I really hoped that Google will fix their font one day, but it seems that the ugly solution with one-letter-font-size will be required.

**Comment by ralesk** [comment]
As much as I like the idea of the app having its own theme and trying to stick to it (and I understand that you don't like that people want to, well, "ruin" the UX :D), sometimes it may be better to allow the user to choose a font (and that's certainly not impossible with Qt), or to let them use the system font.  It's a matter of accessibility sometimes (certain fonts are easier to read for some people, for example).

**Comment by telegramdesktop** [comment]
@ralesk Well, right now at least three fonts that stick to each other should be provided at once (regular, semibold and bold), good fitting semibold font is quite a rare thing.

**Comment by ralesk** [comment]
I didn't notice you guys use three weights.  In most cases, two seems to be enough (might be a personal taste, I avoid light fonts, they aren't fun to read; though I do have good vision).

**Comment by telegramdesktop** [comment]
@ralesk Regular is used everywhere for the text, semibold is used everywhere for names (in conversations list, in messages), because bold is too heavy, bold is used almost nowhere, but still exists.

**Comment by ralesk** [comment]
Ah, okay :)

It does seem like the strength of whatever they call the bold variant depends a lot on the font itself and usually (but not always), the plain bold one isn't too thick.

**Comment by auchri** [comment]
Fixed with 0.9.10

**Comment by obskyr** [comment]
Closed why? Because it's a problem with Open Sans? So no chance of a workaround or font change, huh?

**Comment by telegramdesktop** [comment]
@obskyr Fixed in 0.9.10 version in almost all places (except Search field and maybe some other forgotten places).

**Comment by obskyr** [comment]
Terribly sorry, somehow managed to miss the "fixed" message. I'm definitely happy to see the ~ saga come to an end. So how did it end up being fixed?

**Comment by telegramdesktop** [comment]
@obskyr All tildes are found in messages and other texts + in text input fields (like emojis) and the font is converted to Semibold (like names in the conversations dialog) just for those symbols.

**Comment by Bullsquid** [comment]
Glad to see this one closed but sadly the fix opens another issue. #1263

**Comment by auchri** [comment]
-> https://github.com/google/fonts/issues/399

**Comment by ralesk** [comment]
Holy moly, the actual bug is being worked on, after so many years: https://savannah.nongnu.org/bugs/?23537
