### ISSUE TITLE
[Arch Linux] TD freezes when trying to attach a file

### ISSUE THREAD

**Issue by rado84-github** [telegramdesktop/tdesktop#27001]
### Steps to reproduce

 1. Install the latest telegram-desktop (whether it's static from the website or from arch repo - it's all the same, both freeze).
 2. Click the paperclip to attach a file.
 3. Program freezes completely.
 4. Open any type of system monitor and watch telegram's memory climb to 2GB and beyond.

### Expected behaviour

Clicking the paperclip should open the file selector allowing the user to attach files to a message.

### Actual behaviour

Clicking the paperclip causes the program to freeze completely, making it unuseable.

### Operating system

Arch Linux, Cinnamon

### Version of Telegram Desktop

4.11.1

### Installation source

Static binary from official website

### Logs

[log.txt](https://github.com/telegramdesktop/tdesktop/files/13199044/log.txt)

**Comment by ilya-fedin** [comment]
Can you hold it in frozen state for around a minute? If yes then deadlock detector from debug mode should convert the freeze into a crash and you will get a crash ID if you have beta versions enabled.

**Comment by ilya-fedin** [comment]
See https://github.com/telegramdesktop/tdesktop/wiki/Cheat-Codes for how to enable debug mode (you perhaps need to restart application after that)

**Comment by rado84-github** [comment]
> Can you hold it in frozen state for around a minute? If yes then deadlock detector from debug mode should convert the freeze into a crash and you will get a crash ID if you have beta versions enabled.

I left it open (instead of killing its process) and the QT file selector eventually opened but everything was working very slowly - like "GTA 5 on a Pentium IV" slowly. It took about 2 minutes to attach an image to a message before telegram returned to a useable state. The new log is the same as the one I attached above.

As for these cheat codes, I read them before posting this report and they don't work for me. If you can just tell me where in linux that log directory is, it would be a lot easier and faster for me to provide the log in question.
Also, if you think it would help with the case, I could make a video of the problem.

**Comment by ilya-fedin** [comment]
You need to enable debug mode, not to find log directory. I don't think logs will give anything useful, we have only two options:
1. Make it crash in hanged state (that's what debug mide should help with if it really fully hangs)
2. Profile it. I have no idea how to do that on Linux though.

**Comment by rado84-github** [comment]
IDK how to enable debug mode.
I ran TD in terminal and initially it returned these lines:
`
[rado@arch]: ~>$ telegram-desktop -- %u
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: qt5ct-style, qt6ct-style, Windows, Fusion
qt.dbus.integration: Could not connect "org.freedesktop.NetworkManager" to "stateChanged"
qt.dbus.integration: Could not connect "org.freedesktop.NetworkManager" to "connectivityChanged"
qt.dbus.integration: Could not connect "org.freedesktop.NetworkManager" to "deviceTypeChanged"
qt.dbus.integration: Could not connect "org.freedesktop.NetworkManager" to "meteredChanged"
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.svg: Error while inflating gzip file: SVG format check failed
`
I installed that kvantum engine and now the first two lines are gone but the rest are still there and it's still freezing.

**Comment by ilya-fedin** [comment]
What I described is relevant only for official builds from official website. You seem to use a distro build, it can't have a crash reporter and you will be unable to get a crash id.

**Comment by rado84-github** [comment]
As I said in the OP, it doesn't matter which build I install - both freeze the same way. The only difference between the two is that the executable of the site's build can go wherever I want, whereas the arch build's goes to /usr/bin.

I'm beginning to think telegram isn't the problem here, but qt6 itself. I'll investigate more into that.

**Comment by ilya-fedin** [comment]
Yeah, it's likely, the file dialog is a QFileDialog instance.

**Comment by galenhuntington** [comment]
May or may not be related, but I've started getting crashes when clicking the paperclip, with this:

```
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
Segmentation fault
```

**Comment by ilya-fedin** [comment]
Provide a crash ID
