### ISSUE TITLE
Videos embedded in previews no longer openable

### ISSUE THREAD

**Issue by MKRhere** [telegramdesktop/tdesktop#27003]
### Steps to reproduce

1. Send a link that embeds a video
2. The video loads, plays in muted mode in the embed
3. Click the video, opens the link instead of opening the video

### Expected behaviour

Should open the video as it did prior to the version 4.11

I'm aware of #26984 and #26997. [@john-preston's comment](https://github.com/telegramdesktop/tdesktop/issues/26984#issuecomment-1784069807) says tdesktop will mimic Android behaviour there. As of Telegram for Android v10.2.1 (from the website), embedded images behave as links, but videos do open in a lightbox. So I'm requesting at least that behaviour be restored in tdesktop.

You can see it does actually load the video and play, it's just not openable fullscreen:

![image](https://github.com/telegramdesktop/tdesktop/assets/19621208/0040c13f-dfc6-451d-b737-b02610a7d6df)

### Actual behaviour

Opens the link

### Operating system

Windows 11 (10.0.22621 Build 22621), Debian GNU/Linux 11 (bullseye) & Gnome

### Version of Telegram Desktop

4.11.0

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
duplicate, api thing.

**Comment by MKRhere** [comment]
Duplicate of which issue? What's the API issue? Could you link to it?
