### ISSUE TITLE
Provide GPG signature to verify files

### ISSUE THREAD

**Issue by beerisgood** [telegramdesktop/tdesktop#2700]
Please sign the binary and provide a GPG sig so we can verify the files are realy from you.
Also see this topic to add checksum to the files (SHA512 and/ or SHA3 instead of MD5!): https://github.com/telegramdesktop/tdesktop/issues/2063#issuecomment-266030497

**Comment by arpadox** [comment]
+1

**Comment by beerisgood** [comment]
*push*

Telegram 1.0 is out but not with this enhancement.

**Comment by Orbixx** [comment]
It's surprising that this is not already being done.

**Comment by Orbixx** [comment]
I notice that in the settings for Telegram 1.0, automatic update is selected by default. Perhaps this auto-update process can automatically verify the new package.

**Comment by beerisgood** [comment]
Automatic validation of updates is a must and i hope this is in use and goes over TLS.
But anyway this doesnt fix this bug here.

**Comment by stek29** [comment]
Self-updates are signed indeed, and signature is checked before updating.
But it still doesn't fix this, as @beerisgood noted.

**Comment by beerisgood** [comment]
It looks for me the dev here give a sht* about that security improvement.
And this is the official telegram for desktop client...nice

**Comment by beerisgood** [comment]
*a last push try*

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
Why its closed?
its not fixed yet

Also its not the same like #2063

**Comment by stek29** [comment]
@beerisgood it is. Please, read it once again, and see it suggests GPG.
