### ISSUE TITLE
Empty webpage preview when bot sends a link to a group message

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#27004]
### Steps to reproduce

1. Forward a message from any channel to a private supergroup
2. Copy a link to the forwarded message in this supergroup (e.g. https://t.me/c/1122334455/1234567)
3. Send a message with that link via a bot:

```javascript
bot.invoke("sendMessage", {
  "text": "With preview: https://t.me/c/1123020018/3807539",
  "disable_web_page_preview": false,
  "parse_mode": "html",
  "chat_id": -1001123020018
})
bot.invoke("sendMessage", {
  "text": "Without preview: https://t.me/c/1123020018/3807539",
  "disable_web_page_preview": true,
  "parse_mode": "html",
  "chat_id": -1001123020018
})
```

### Expected behaviour

Identical as if the user sends the same message: no webpage previews for both messages

### Actual behaviour

First message (with webpage previews) contains an empty webpage preview

![image](https://github.com/telegramdesktop/tdesktop/assets/1321838/6ec226a3-1248-4819-8d97-79204e28152d)

### Operating system

Windows 11

### Version of Telegram Desktop

4.11.1

### Installation source

Static binary from official website

**Comment by Tsopic** [comment]
Same

![image](https://github.com/telegramdesktop/tdesktop/assets/3941909/3fbeddba-5d28-4bd3-9699-abd4a9fcd199)
Eating up space without actual usecase
