### ISSUE TITLE
[FeatureReq] Allow Option to get back the old (windows) TG Icons

### ISSUE THREAD

**Issue by T3rminat0r** [telegramdesktop/tdesktop#27008]
### Is your feature request related to a problem?

Currently, the new icon for Telegram in the notification area completely vanishes behind the "unread chats" counter in said area, while the old, blue circle icon was plainly visible behind the notification bubble.

### Describe the solution you'd like

 Can we get the old icon back, or at least an option in the settings to switch between them, please? 
![image](https://github.com/telegramdesktop/tdesktop/assets/9053174/11a61de8-8cf8-4c5f-bab3-1250c02db447)

### Describe alternatives you've considered

Alternatively, just keep the "old" icon, as you did for the task-bar? 
![image](https://github.com/telegramdesktop/tdesktop/assets/9053174/1174f2a4-3af2-4b0b-993d-33dd6b6fcfcb)

**Comment by kirsan31** [comment]
https://github.com/telegramdesktop/tdesktop/commit/a57eecd420ea08e016d147df9c4c2366a5915b21
