### ISSUE TITLE
Tray icon changed after upgrading to 4.11

### ISSUE THREAD

**Issue by hujiecs** [telegramdesktop/tdesktop#27005]
### Steps to reproduce

After (Automatic) Upgrading to 4.11, the tray icon changed immediately. didn't find this change in the release note.

### Expected behaviour

Tray icon should be same as before, like this:
![image](https://github.com/telegramdesktop/tdesktop/assets/13184541/ffbe8e9b-4429-4ca2-a378-e2a84345ee31)

### Actual behaviour

Tray icon  is changed to  this:
![image](https://github.com/telegramdesktop/tdesktop/assets/13184541/06720bde-5367-4db3-b9e2-68605596feab)

### Operating system

Windows 10 Pro 22H2 19045.3448

### Version of Telegram Desktop

4.11

### Installation source

Static binary from official website

**Comment by catterpiler74** [comment]
Добрый день, после обновления десктопной версии телеграм до версии 4.11.1, значек в трее стал белый. Как вернуть прежний значок. Новый не нравится

**Comment by catterpiler74** [comment]
@ilya-fedin , вот ребят, нашел человечка кто считает что белая иконка лучше, себе на лбу нарисуй иконку белую д*****еб

**Comment by catterpiler74** [comment]
https://telegram-for-desktop.ru.uptodown.com/windows/post-download/109082955
old version without white shit icon

**Comment by Aokromes** [comment]
duplicate.

**Comment by hujiecs** [comment]
> duplicate.

@Aokromes can you share the duplicated issue link?

**Comment by archonoff** [comment]
@john-preston thanks man, i came here exactly because of that issue :D

**Comment by scorpion421** [comment]
Until then, set compatibility mode to Windows 7. Colored icon is back instantly :).
