### ISSUE TITLE
Telegram Desktop doesn't start

### ISSUE THREAD

**Issue by develop7** [telegramdesktop/tdesktop#27000]
### Steps to reproduce

1. Run `flatpak run org.telegram.desktop` in console

### Expected behaviour

Telegram Desktop starts

### Actual behaviour

Telegram Desktop doesn't start. Console output:

```console
$ flatpak run org.telegram.desktop 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.
```

### Operating system

openSUSE Tumbleweed 20231025, GNOME 45.0, Wayland session

### Version of Telegram Desktop

4.11.1 beta

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Have you done any permission overrides? If yes, reset them, if not, try to reboot your system.

**Comment by develop7** [comment]
did the reset & reboot, couldn't reproduce anymore. thanks.
