### ISSUE TITLE
Some chats are not visible in folder after upgrade

### ISSUE THREAD

**Issue by meteozond** [telegramdesktop/tdesktop#27006]
### Steps to reproduce

1. Upgrade to 4.11.*
2. Open Folder with chats

### Expected behaviour

Chats are visible

### Actual behaviour

Chats are missing from folder list and strange behaviour in folder edit UI.
![image](https://github.com/telegramdesktop/tdesktop/assets/975689/2f1b3f1a-1f9e-4320-ac22-97b3ad78e95a)

Downgrade didn't help...

### Operating system

Macos

### Version of Telegram Desktop

4.11.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Looks like a server side issue. Is it still happening? What about mobile apps, new logins from mobile apps?

**Comment by meteozond** [comment]
It is working now
