### ISSUE TITLE
Telegram Desktop icon is invisible in Task manager

### ISSUE THREAD

**Issue by VVAf** [telegramdesktop/tdesktop#27015]
### Steps to reproduce

1. Launch the latest version of Telegram Desktop
2. Open Task Manager. Light theme is selected in Windows
3. See that there is no icon next to Telegram Desktop while it is minimized to tray. However, the icon is OK when Telegram is maximized. Also the tray icon changed to some ugly white one which is really hard to find

### Expected behaviour

Normal blue Telegram Icon should be there

### Actual behaviour

There is blank space next to Telegram.exe
![image](https://github.com/telegramdesktop/tdesktop/assets/38762346/35408f50-aa12-4d7a-b62e-6350564a52aa)
![image](https://github.com/telegramdesktop/tdesktop/assets/38762346/cf0a6e17-4928-4dad-b4a5-8c81b23de94c)

### Operating system

Windows 10

### Version of Telegram Desktop

4.11.1

### Installation source

Static binary from official website

**Comment by scorpion421** [comment]
Yeah. Some "wise" guy included the monochrome icons because... yeah... why. Nobody - except one (!) user asked for such craziness. Dunno. This was just a stupid step imho.

**Comment by suprunchuk** [comment]
Fixed since version [4.11.2](https://github.com/telegramdesktop/tdesktop/releases/tag/v4.11.2)
