### ISSUE TITLE
`Ctrl + Shift + .` combination not working on formating

### ISSUE THREAD

**Issue by RC4347** [telegramdesktop/tdesktop#27012]
### Steps to reproduce

1. Quote shortcut not working
2. Other shortcuts works fine

### Expected behaviour

format text

### Actual behaviour

just not working but other shortcuts working

### Operating system

Linux

### Version of Telegram Desktop

4.11.1

### Installation source

Static binary from official website

**Comment by ExposedCat** [comment]
Same issue. Fedora 38, GNOME, Flatpak 4.11.1

**Comment by brxoo** [comment]
Same issue, also on Linux. TD 4.11.2

**Comment by Francehelder** [comment]
Same issue. Endeavour OS, TD 4.11.6
