### ISSUE TITLE
Amount of unread messages not readable since change of status bar icon

### ISSUE THREAD

**Issue by starwarsfan** [telegramdesktop/tdesktop#27010]
### Is your feature request related to a problem?

With the update to 4.11.1 on Windows the status bar icon changed from the blue circle one to the simple single colored arrow. Since then it's nearly impossible to read the notification on top of that icon with the amount of unread messages. See two examples:

Old icon: 
![image](https://github.com/telegramdesktop/tdesktop/assets/1954385/66048483-94c6-4949-ac0a-1b9adf2dc158)

New icon: 
![image](https://github.com/telegramdesktop/tdesktop/assets/1954385/626a6afd-b53a-4c15-ab1f-c40df441f713)

### Describe the solution you'd like

Please use a color schema which is readable, at least with improved contrast.

### Describe alternatives you've considered

No idea on alternative solution.

**Comment by Aokromes** [comment]
duplicate will be fixed on next version.

**Comment by john-preston** [comment]
@starwarsfan First screenshot shows the unmuted unread count, while second screenshot - muted unread count. The same can be shown vice versa, old icon:
![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/68c83a48-f132-4efc-ae32-d208e1d5a410)

New icon:
![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/4961887d-a00e-44d2-9fc2-2014df5587ee)

The color theme of the counter wasn't changed.
