### ISSUE TITLE
Not all video chats have an ability to pin the window.

### ISSUE THREAD

**Issue by paul23093** [telegramdesktop/tdesktop#27018]
### Steps to reproduce

1. Start or join to video chat in any group or channel

### Expected behaviour

Have a pin icon on top right corner to pin the video chat in front of other windows.

### Actual behaviour

Only certain groups or channels (maybe just only channels) have this ability.

### Operating system

MacOS 14.0 Sonoma

### Version of Telegram Desktop

4.11.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/17089
