### ISSUE TITLE
Phantom link previews when no preview available

### ISSUE THREAD

**Issue by MKRhere** [telegramdesktop/tdesktop#27024]
### Steps to reproduce

1. Send a link like https://example.com/?test
2. Sometimes, it creates a phantom preview:

![image](https://github.com/telegramdesktop/tdesktop/assets/19621208/4da276b3-86d1-4382-9409-14470f38159a)

### Expected behaviour

Shouldn't show a preview

### Actual behaviour

It doesn't seem to happen consistently, but I'm seeing a lot of these phantom links

### Operating system

Windows 11 22H2 (10.0.22621 Build 22621), Debian GNU/Linux 11 (bullseye) & Gnome

### Version of Telegram Desktop

4.11.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
duplicate and fixed on next version.
