### ISSUE TITLE
Click on emoji panel move telegram app to the background

### ISSUE THREAD

**Issue by ArianHamdi** [telegramdesktop/tdesktop#27025]
### Steps to reproduce

1. Click right on a message
![image](https://github.com/telegramdesktop/tdesktop/assets/59548833/183aa74f-12df-4f4d-b8f2-bcdee19b7392)
2. Click on the arrow icon
3. If arrow is outside of telegram window clicking on it will move telegram to the background

### Expected behaviour

Open  emoji panel on click

### Actual behaviour

Move telegram to the background

### Operating system

MacOS 14.1

### Version of Telegram Desktop

4.11.1

### Installation source

Static binary from official website

**Comment by itmehr** [comment]
Yastunes ❤️

**Comment by john-preston** [comment]
They broke something in macOS :(
