### ISSUE TITLE
[Feature Request] Add tabs to divide groups, bot, channels and private chats

### ISSUE THREAD

**Issue by fedebyes** [telegramdesktop/tdesktop#2702]
### Expected behaviour
Tell us what should happen
See a tabs where i can find only  groups, bot, channels and private chats
like plus messenger
![image](https://cloud.githubusercontent.com/assets/9150702/21079620/391fdf38-bf97-11e6-93b4-b63989c9b8ee.png)

### Actual behaviour
Tell us what happens instead
All chats together

**Comment by Aokromes** [comment]
#1107 ?

**Comment by kenorb** [comment]
Related: #1107, #1505, #2642, #4873, #5560
