### ISSUE TITLE
Crash when editing Link Preview

### ISSUE THREAD

**Issue by makecraft** [telegramdesktop/tdesktop#27033]
### Steps to reproduce

1. Paste a Link in de Message Box
2. Edit the Link Preview
3. Save the edition

### Expected behaviour

Link Preview editions should be saved correctly

### Actual behaviour

Telegram crash

### Operating system

Manjaro Linux, Gnome 44.5, Wayland

### Version of Telegram Desktop

4.11.2

### Installation source

Static binary from official website

### Crash ID

5ea328a4-88b2-488c-ad423c91-fcab6b52

**Comment by ipamaslo** [comment]
I agree, same problem, Win 11, Telegram 4.11.2 x64

[video](https://github.com/telegramdesktop/tdesktop/assets/146661321/e8508e25-5093-48af-becc-599bf7309fdc)
