### ISSUE TITLE
[Feature Request] Bookmarks\Anchors support

### ISSUE THREAD

**Issue by lebe-dev** [telegramdesktop/tdesktop#2703]
### Actual behaviour
1. You have loooong chat with a lot of unread messages. If you left this chat for a moment you will lost your read position

2. Unable to make bookmark on chat line\position

### Expected behaviour

1. If you leave current chat to another for some time and come back after - chat will be opened at the same row as you left it.

2. Make bookmarks\anchors\whatever for navigation to important chat things

i.e. bookmarking from any modern IDE (Idea, Eclipse, etc.)

**Comment by john-preston** [comment]
@lebe-dev 1. Works that way, the position in the chat is saved between different enterings of this chat.

**Comment by lebe-dev** [comment]
@john-preston no, i checked with news feed before post this request

env: Android Nougat with latest updates

**Comment by gudvinr** [comment]
@lebe-dev Did you noticed that this is github of desktop version? And you're asking about android one, am I right?
> env: Android Nougat with latest updates

**Comment by lebe-dev** [comment]
oh yes, sorry. but how about main subject - bookmarks\anchors?

**Comment by gudvinr** [comment]
@lebe-dev at least you can forward important messages to yourself. There's no API for anchors and I doubt it ever will.

**Comment by lebe-dev** [comment]
but you have LocalStorage on browser side and its capacity will be enough for bookmarks storage

**Comment by auchri** [comment]
If we implement bookmarks, the should be synced.
