### ISSUE TITLE
Issue with quote-replying with a file

### ISSUE THREAD

**Issue by Vadrone** [telegramdesktop/tdesktop#27032]
### Steps to reproduce

1. Quote part of a previous message, and send a file, such as an image, as a reply to this quote.
2. Close and reopen the client, or look at the reply you sent from a different device.
3. Observe how the quote now has become a normal reply to the entire message you were quoting from.

### Expected behaviour

The quote-reply should remain a quote-reply.

### Actual behaviour

The quote-reply becomes a normal reply to the entire message.

Screenshot from the desktop client right after sending a quote-reply, quoting the part "abc" and adding a file:

![pc](https://github.com/telegramdesktop/tdesktop/assets/35540345/7437cb95-8533-447c-a8e9-2712941c0e0b)

What the message looks like in a different location (in this case, mobile):

![mobile](https://github.com/telegramdesktop/tdesktop/assets/35540345/73679ef3-579e-42c9-b3a9-08eb6659c258)

Screenshot from the desktop client after exiting the client and reopening it:

![pc2](https://github.com/telegramdesktop/tdesktop/assets/35540345/01429057-0999-45fc-b1d0-28622a7ca72c)

### Operating system

Arch Linux, rolling release, Hyprland

### Version of Telegram Desktop

4.11.1

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by Vadrone** [comment]
Just downloaded 4.11.2 from the website and tried it there, and the problem still occurs.

**Comment by john-preston** [comment]
@Vadrone Thank you for your report!

This will be fixed in the next version.
