### ISSUE TITLE
Ubuntu 18.04.6 LTS / Telegram Desktop 4.11.3 / ./Telegram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./Telegram)

### ISSUE THREAD

**Issue by JLCrouzet** [telegramdesktop/tdesktop#27037]
### Steps to reproduce

./Telegram

### Expected behaviour

Normal launch should have been working like earlier version !

### Actual behaviour

Instead I do have when launched via Terminal the following error message:
./Telegram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./Telegram)

### Operating system

Linux Dell-E7440 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Version of Telegram Desktop

tsetup.4.11.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Telegram supports Ubuntu 20.04+, please look at README.md

**Comment by Aokromes** [comment]
https://ubuntu.com/blog/18-04-end-of-standard-support

**Comment by JLCrouzet** [comment]
I guess that since I'm using an old Ubuntu 18.04.6 LTS version I shall downgrade to tsetup version 4.9.9 ...
OK then it's working but I can't see some message because telegram-desktop said in French:
Ce message n'est pas pris en charge par votre version de Telegram. Veuillez mettre à jour l'application dans Paramètres > Avancé, ou l'installer depuis https://desktop.telegram.org. Si vous utilisez déjà la dernière version, ce message peut être lié à une fonctionnalité qui n'est pas encore implémentée.

OK agree to close this issue anyway. My 2 cents comment about ALWAYS upgrading everything to get it to work with latest upgrade is not going to anything stable but I do not want to enter endless debate about such global fact ...

BTW the web version has similar limitation on identical messages:
This message is currently not supported on Telegram Web. Try [getdesktop.telegram.org](https://getdesktop.telegram.org/)

**Comment by Aokromes** [comment]
> I guess that since I'm using an old Ubuntu 18.04.6 LTS version I shall downgrade to tsetup version 4.9.9 ... OK then it's working but I can't see some message because telegram-desktop said in French: Ce message n'est pas pris en charge par votre version de Telegram. Veuillez mettre à jour l'application dans Paramètres > Avancé, ou l'installer depuis [desktop.telegram.org](https://desktop.telegram.org). Si vous utilisez déjà la dernière version, ce message peut être lié à une fonctionnalité qui n'est pas encore implémentée.
> 
> OK agree to close this issue anyway. My 2 cents comment about ALWAYS upgrading everything to get it to work with latest upgrade is not going to anything stable but I do not want to enter endless debate about such global fact ...
> 
> BTW the web version has similar limitation on identical messages: This message is currently not supported on Telegram Web. Try [getdesktop.telegram.org](https://getdesktop.telegram.org/)

it's the price you must deal using EOLed os.
