### ISSUE TITLE
Unaligned "via @examplebot" near stickers

### ISSUE THREAD

**Issue by DO97** [telegramdesktop/tdesktop#27048]
### Steps to reproduce

1. Send a sticker with a bot.

### Expected behaviour

The text should be aligned inside the cell.

### Actual behaviour

![2023-11-05 173429](https://github.com/telegramdesktop/tdesktop/assets/17525578/4ff3bb53-1674-438f-b05d-5efa1fafde86)

### Operating system

Windows 10

### Version of Telegram Desktop

4.11.3 and 4.11.3 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Thanks! Maybe in the next (not 4.11.5, after) version.
