### ISSUE TITLE
Message quote is cut to one line preview

### ISSUE THREAD

**Issue by enchained** [telegramdesktop/tdesktop#27043]
### Steps to reproduce

1. Create a test quote in the Saved messages using a forwarded message and a Quote & Reply in the context menu.
2. Compare how it looks on a mobile client (in my case iOS).

![image](https://github.com/telegramdesktop/tdesktop/assets/6181674/abf8a61a-cf3a-47fb-94ba-aa41dd852046)
![image](https://github.com/telegramdesktop/tdesktop/assets/6181674/9169d1f9-46a8-4060-82e2-bef9d5bc4394)

### Expected behaviour

Quote is fully displayed like on mobile clients

### Actual behaviour

Only a single line from the quote is visible

### Operating system

Windows 11

### Version of Telegram Desktop

4.11.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@enchained yeah, it'll be fixed later

**Comment by john-preston** [comment]
Fixed in one of the recent versions.
