### ISSUE TITLE
tdesktop version is snap is still 4.10

### ISSUE THREAD

**Issue by adeptg** [telegramdesktop/tdesktop#27049]
### Steps to reproduce

https://snapcraft.io/telegram-desktop
latest/stable is 4.10.3, while the latest version of the client is 4.11
4.10 doesn't show messages with quotes correctly. Please update the snap distribution to 4.11

### Expected behaviour

there is a 4.11 version of tdesktop here: https://snapcraft.io/telegram-desktop in latest/stable

### Actual behaviour

there is a 4.10.3 version of tdesktop here: https://snapcraft.io/telegram-desktop in latest/stable

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.10.3

### Installation source

Snap

**Comment by ilya-fedin** [comment]
As far as I can see it's the latest
![изображение](https://github.com/telegramdesktop/tdesktop/assets/17829319/b3d0daf8-d5aa-47cf-bcfb-b8c741300ca9)

**Comment by adeptg** [comment]
Yes, it was updated yesterday. Thanks!

Last updated:

    Yesterday - latest/stable
    Yesterday - latest/edge
