### ISSUE TITLE
Font increase

### ISSUE THREAD

**Issue by OSH1980** [telegramdesktop/tdesktop#27047]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Please, add an option for increase font size NOT the whole UI on Linux/Windows! Increasing UI is very annoying - I don't want to have a window big as… you know!

### Describe alternatives you've considered

none

**Comment by Aokromes** [comment]
#90

**Comment by OSH1980** [comment]
Great. So It's too hard for code. Problem solved.

**Comment by OSH1980** [comment]
Great. So It's too hard for code. Problem solved.
