### ISSUE TITLE
Not all comments are loading in posts with hundreds of comments

### ISSUE THREAD

**Issue by enchained** [telegramdesktop/tdesktop#27042]
### Steps to reproduce

1. Find a post with at least hundreds of comments (i.e. https://t.me/moscowmap/58213 and most posts on this channel)
2. Go to the comments, scroll through them to the bottom.
3. Sometimes (not always, but often), when the scrolling stops, unread comment counter still has more comments.
    * If you scroll back to the top, often you can't reach the post or first comments either, only some slice of comments is visible.
    * If you click on the arrow below the unread comment count - comments load but you skip to the bottom with no way to return to where you were.
    * If you do not click on the arrow and go back to the channel instead to open the comments again - you continue where you left (that's how I'm dealing with the bug for now).

I've heard at least 2 people mention it in the discussion recently, so it looks like I'm not the only one experiencing it. I was surprised I could not find it reported here yet. I guess not a lot of people encounter channels with so much comments, but for me it happens quite frequently.

### Expected behaviour

Like on mobile clients, all comments should load while you scroll, and the top post never disappears.

### Actual behaviour

Only a portion of comments loads and there's no seamless way to read them all in order.

### Operating system

Windows 11

### Version of Telegram Desktop

4.11.3

### Installation source

Static binary from official website

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25889
