### ISSUE TITLE
The snap version of tdesktop does not follow the native cursor theme.

### ISSUE THREAD

**Issue by Master811129** [telegramdesktop/tdesktop#27044]
## Possible workaround

I really don't think this this is the actual solution but maybe adding `breeze-cursor-theme` to `stage-packages` in `snapcraft.yaml` will fix the issue at-least for SOME KDE users.

### Steps to reproduce

1. `snap run telegram-desktop`
2. move your mouse on telegram window

### Expected behaviour

Native cursor.

### Actual behaviour

DMZ cursors

### Operating system

Linux

### Version of Telegram Desktop

4.10.3

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Cursor themes are contained in gtk-common-themes snap that is owned by canonical. Appplication snaps aren't supposed to include cursor themes.

**Comment by Master811129** [comment]
Ok, but why did you closed my issue. I still have issues with the mouse cursor. I have `gtk-common-theme` snap but still telegram only shows DMZ cursor and not Breeze cursor (Breeze is pretty common it's the default KDE theme). Plus my other snaps (eg: Firefox, Thunderbird, various KDE/Qt apps) don't have this issue.

**Comment by ilya-fedin** [comment]
Because you need to ask to add the theme at gtk-common-themes repo, not here.

Apparently it works in other apps because they're not snaps or because KDE content snap contains breeze theme but tdesktop is not a KDE application to use KDE content snap.
