### ISSUE TITLE
Upgrade Telegram Desktop Snap

### ISSUE THREAD

**Issue by huezo** [telegramdesktop/tdesktop#27051]
### Steps to reproduce

Update Telegram Desktop Snap please

![imagen](https://github.com/telegramdesktop/tdesktop/assets/15940634/0da7bf9d-459d-4992-93e7-66f54b7a4495)

[https://snapcraft.io/telegram-desktop](https://snapcraft.io/telegram-desktop)

### Operating system

GNU/Linux

### Version of Telegram Desktop

4.10.3

### Installation source

Snap

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/27049
