### ISSUE TITLE
Mention all users in group chat using @everyone @all @here

### ISSUE THREAD

**Issue by hbohatix** [telegramdesktop/tdesktop#27055]
**Steps to reproduce:**
Type `@everyone`, `@all` or `@here` (like in Discort, Slack).

**Expected behaviour**
All members of the group are mentioned even if it's muted for them (like many @username mentions).

**Actual behaviour**
Nothing happened.

Please also enable this feature for iOS and Android version of application 🙏🏼

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
