### ISSUE TITLE
Can't find people through their phone number

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#27057]
### Steps to reproduce

I either just use the search field and paste in the phone number or
I use it like this t.me/+6699694471
Or like this +6699694471

It never finds anyone and this has been going on for years. 

Please tell me if you can fix it or how to find people just with their number.

Thanks

### Expected behaviour

It should bring up the person's profile.

### Actual behaviour

Nothing is found.

### Operating system

Win 10

### Version of Telegram Desktop

4.11.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
