### ISSUE TITLE
tupdater problem don't close root request window

### ISSUE THREAD

**Issue by kinoher** [telegramdesktop/tdesktop#27059]
### Steps to reproduce

wait official update 
run telegram 

### Expected behaviour

in request root window press cancel start old version

### Actual behaviour

when press cancel in request window, tupdater request root permission again and again 
it's infinity loop until pkill Telegram

### Operating system

linux fedora 36 gnome 42 nvudua gtx 1080

### Version of Telegram Desktop

4.11.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I'm unable to reproduce on my system with KDE. It behaves exactly like specified in expected behavior.
