### ISSUE TITLE
[Feature Request]Add option to hide "foldered" chats from all-chats list

### ISSUE THREAD

**Issue by Swesser** [telegramdesktop/tdesktop#27065]
### Is your feature request related to a problem?

This feature will solve the problem of uncontrolled chaos and mess in all-chats list for people, who handle a lot of conversations plus subscribe to lots of news channels.

### Describe the solution you'd like

My idea is to add a checkbox somewhere in Folders settings. It will ask smth like "hide folder chats from all-chats list".

### Describe alternatives you've considered

alternatives to what?

### Additional context

The idea is about separation and better structurisation of chats. For example, I put all "work" chats in a folder, so that I never see them until I show up to work. Same with news - I just pack them into one folder and they never come into my eyesight until I want to check what's going on in the world.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by Swesser** [comment]
> platform wide bugs / requests belongs to https://bugs.telegram.org/

you must be misunderstanding. i requested for a feature

**Comment by Swesser** [comment]
and why is it closed? bro you must be misunderstanding the topic so much
