### ISSUE TITLE
App crashes when adding a new topic to group

### ISSUE THREAD

**Issue by Porkechebure** [telegramdesktop/tdesktop#27061]
### Steps to reproduce

1. Go in a group created some time ago with topics enabled
2. Try creating a new topic
3. As soon as you input the topic name and click "create" the app crashes EVERY time

### Expected behaviour

Creating topic normally without crashing

### Actual behaviour

App crashes without warning

### Operating system

Windows 10 x64

### Version of Telegram Desktop

4.11.5 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by john-preston** [comment]
@Porkechebure Thanks for your report! This will be fixed in the next version (I hope it'll be released tomorrow).

**Comment by Porkechebure** [comment]
> @Porkechebure Thanks for your report! This will be fixed in the next version (I hope it'll be released tomorrow).

So you managed to reproduce it without the need of debug log?

Thanks for your work anyways, you're doing the god's work

**Comment by john-preston** [comment]
@Porkechebure Yes, I saw such crash reports from the deployed already version. Thanks.

**Comment by Porkechebure** [comment]
> @Porkechebure Yes, I saw such crash reports from the deployed already version. Thanks.

Please please please, Add the possibility to put automatically the file name when uploading media files:

![image](https://github.com/telegramdesktop/tdesktop/assets/3466040/18cf15f9-ae36-490c-a055-bfb92ed79728)

It's frustrating to do everything manually

**Comment by joecool1029** [comment]
Just confirming https://github.com/telegramdesktop/tdesktop/commit/a7090c5fbaf2d47216ab99f9bb0a3331ea2d6daf fixes the crash.

**Comment by Aokromes** [comment]
fixed on 4.11.6
