### ISSUE TITLE
Use whole possible space for messages 

### ISSUE THREAD

**Issue by vovagorodok** [telegramdesktop/tdesktop#27068]
### Is your feature request related to a problem?

N/A

### Describe the solution you'd like

I'm using telegram in Linux (perhaps in other platform is same).
Long line messages are limited in size:
![image](https://github.com/telegramdesktop/tdesktop/assets/8137447/9007f5fa-6032-45d4-be6d-b1861f81a2d4)
 And we have a lot of unused space each time.
Can we use whole free space or add option for that?

### Describe alternatives you've considered

N/A

**Comment by kirsan31** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2060

**Comment by vovagorodok** [comment]
Thanks @kirsan31 . Hmm, strange why not add checkbox disabled by default.. It's very needed feature for a lot of people. At first I thought that it was a bug
