### ISSUE TITLE
Replace radio-button by check-box for multi-select questionnaire

### ISSUE THREAD

**Issue by kgksoft** [telegramdesktop/tdesktop#27060]
### Is your feature request related to a problem?

Single control for one-choice and multi-choice questionnaire misleads the user. 

### Describe the solution you'd like

For one-choice questionnaire - use RADIO-BUTTONS (round controls)
For multi-choice - CHECK-BOX (Square - control)

### Describe alternatives you've considered

No alternative

**Comment by ilya-fedin** [comment]
#27026
