### ISSUE TITLE
Deep link to bot with start parameter shows start button every time

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#27064]
### Steps to reproduce

1. Click on a deep-link to a bot with a `start` parameter, such as (this is a real link that you can use to test the issue): https://t.me/fume_bot?start=123 (paste this e.g. into your saved messages so you can click it from there)
2. This opens a private chat with the bot, with a "START" button, so click the "START" button
3. Now go back and click on the initial link again

### Expected behaviour

This time, this should immediately send the start message to the bot with the (unfortunately hidden, but that's a separate issue in both Desktop and app, probably by wrong design) parameter, to which the bot will immediately respond. That is, this second interaction shouldn't show the "START" button again and require to click it. This is how the mobile Telegram app behaves, and there's no reason for the Desktop application to behave differently

### Actual behaviour

No matter how many times you have already talked to the bot and/or sent it a /start command, every single time you click on the deep-link, it will display the START button and you'll need to click it in order for the /start command to be sent. This is inconsistent with the mobile app behavior.

One may argue on which of the two behaviors is better. I personally think the mobile behavior makes much more sense. Either way, the two should have the same behavior.

### Operating system

Manjaro Linux

### Version of Telegram Desktop

4.11.5

### Installation source

Other (unofficial) source

**Comment by oleksvot** [comment]
Relevant, the same issue in Telegram Desktop 4.14.13 x64 on Windows 10. Are there any ways to work around this strange behavior? I need it to behave the same way as in the mobile application, with an instant response when clicking the link.

**Comment by ukushu** [comment]
Same issue: Deep-Link open must NOT require manual press of "start" button from user.

### Expected behaviour

DeepLink was opened and no extra action from user is required

> Such expected behaviour we can see on:
> * Telegram for MacOS
> * Web Telegram
> * iOS telegram
> * Android telegram

### Actual behaviour

Telegram require extra action from user: manually click "Start" button in the bottom of the window

### Operating system / Version of Telegram Desktop

* 5.1.7(Telegram Light MacOS from AppStore)
* 5.2.2 (Windows, static binary from offsite)

for search puproses: Deep-Link, DeepLink, Deep link

**Comment by gasabr** [comment]
isn't it documented expected behaviour

> Start parameter, up to 64 [base64url](https://en.wikipedia.org/wiki/Base64#The_URL_applications) characters: if provided and the bot_username is indeed a bot, the text input bar should be replaced with a Start button (even if the user has already started the bot) that should invoke [messages.startBot](https://core.telegram.org/method/messages.startBot) with the appropriate parameter once clicked. Note that if the bot_username is equal to the [premium_bot_username configuration value »](https://core.telegram.org/api/config#premium-bot-username), clicking on this link should immediately invoke [messages.startBot](https://core.telegram.org/method/messages.startBot) with the appropriate parameter.

https://core.telegram.org/api/links#bot-links

**Comment by ukushu** [comment]
> Note that if the bot_username is equal to the [premium_bot_username configuration value »](https://core.telegram.org/api/config#premium-bot-username), clicking on this link should immediately invoke [messages.startBot](https://core.telegram.org/method/messages.startBot) with the appropriate parameter.

If I correctly understand this text: I need to buy username for my bot on fragment and deeplinks will work without pressing "Start" button. Hm.

**Comment by john-preston** [comment]
@ukushu nope, that "Note" is about a specific, single bot, used to sell premium subscriptions to users.

**Comment by ukushu** [comment]
@john-preston  

>bot_username is equal to the premium_bot_username

how do ```bot_username``` / ```premium_bot_username``` to ```premium user``` (user with subscription) correlate with each other?

**Comment by john-preston** [comment]
@ukushu from your link:

![image](https://github.com/user-attachments/assets/e04ca3dd-d8f1-4306-bdba-88ddd319535d)

**Comment by polyphia** [comment]
Same issue here, expected behavior is for the start parameter to run automatically without having to press Start once user has interacted with the bot previously, which is not happening
