### ISSUE TITLE
[linux] Telegram freezes the whole system GUI when opening any media

### ISSUE THREAD

**Issue by demoth** [telegramdesktop/tdesktop#27062]
## Steps to reproduce

1. Open Telegram chat with an image
2. Click on the image in the message

### Expected behaviour

The picture or video is opened normally

### Actual behaviour

Operating system's GUI is fully frozen, the music from other apps (if it was played) keeps playing, but everything else is frozen, mouse does not move, apps do not move, and it does not go away for at least 5 minutes, more that that haven't tried. Only the hard reboot with laptop's button helps.

The above is copied from #26406 because symptoms are 100% same.

Reporting for 23.10 but the same issue was with 22.04 and 22.10 on this machine.

I have other ubuntu machines at home and this issue never happened there, so I guess it may be machine specific.

### Operating system

Ubuntu 23.10, Gnome 45, Wayland

### Version of Telegram Desktop

4.10.3

### Installation source

Snap

**Comment by ilya-fedin** [comment]
#26393
