### ISSUE TITLE
Out of memory running ./tdesktop/Telegram/build/prepare/linux.sh

### ISSUE THREAD

**Issue by elfmz** [telegramdesktop/tdesktop#27073]
### Steps to reproduce

Ubuntu 20,  Ryzen 7 5800U (16 Logical Threads), 32GB of RAM
Cloned repository and ran ./tdesktop/Telegram/build/prepare/linux.sh
After some time (~half of hour) build process comsumes all available memory and either fails either system becomes stuck requiring reboot

### Expected behaviour

Build should complete

### Actual behaviour

Build process comsumes all available memory and either fails either system becomes stuck requiring reboot

### Operating system

Ubuntu 20

### Version of Telegram Desktop

Current master

### Installation source

Static binary from official website

**Comment by elfmz** [comment]
I assume it would be possible to avoid by reducing CPU-s number used by build process, thus less tasks in parallel will use less RAM in total. Is there way to do this?

**Comment by ilya-fedin** [comment]
Yeah it should be possible. Sadly, there's no configuration to that, it just calls cmake's `--parallel` and relies on the default for meson.
