### ISSUE TITLE
Change Tray Icon

### ISSUE THREAD

**Issue by APT-ZERO** [telegramdesktop/tdesktop#27076]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

\-

### Describe alternatives you've considered

\-

### Additional context

Add multiple Icons and let us select our preferred one for Tray Icon.

**Comment by ilya-fedin** [comment]
> Add multiple Icons

Can you be more specific and enumerate the icons you want?

**Comment by Aokromes** [comment]
you already can get the old tray icon.

**Comment by Aokromes** [comment]
on settings advanced.
