### ISSUE TITLE
Auto caption uploaded files and media

### ISSUE THREAD

**Issue by Porkechebure** [telegramdesktop/tdesktop#27078]
### Is your feature request related to a problem?

When uploading files in any way (file upload modal from the clip button, drag and drop of single and multiple files) I would like to be able to automatically put the caption under it with file name (or also following a pattern like File01, File02 etc).

At the moment media is uploaded without a name:
[Check here](https://user-images.githubusercontent.com/3466040/281068967-18cf15f9-ae36-490c-a055-bfb92ed79728.png)

and it's hard to determine which video is what, which photo is what and whatever else as file name is not shown unless you go checking message info 1 by 1.

### Describe the solution you'd like

There should be a way, ether from telegram setting or from the media upload modal to allow us to automatically caption multiple files and videos automatically, both when sent as separate messages and when sent as group (but sent as group isn't as important as when you send them 1 by 1 or check the option to split the group.)

Would really help to make the files uploaded more usable and clear.

### Describe alternatives you've considered

I don't think there is one unles it's implemented.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3573

**Comment by Porkechebure** [comment]
> #3573

Doesn't look like the same stuff. 
I need it to automatically put the file name in the caption so i can send it with caption name and search it
