### ISSUE TITLE
Bug SMS-Server

### ISSUE THREAD

**Issue by MikhailovMV** [telegramdesktop/tdesktop#27077]
### Steps to reproduce

SMS sending fatal error!

### Expected behaviour

Dest SMS

### Actual behaviour

NoSend SMS

### Operating system

MacOS

### Version of Telegram Desktop

current

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
this is telegram desktop client bug tracker. for server issues contact bugs.telegram.org
