### ISSUE TITLE
Blurry tray icon and main window

### ISSUE THREAD

**Issue by akelsandrlosev** [telegramdesktop/tdesktop#27079]
### Steps to reproduce

Set Windows 11 scaling to 200%
1. Restart your PC
2. Login into your account 

### Expected behaviour

Clear icon and main window without any scaling errors

### Actual behaviour

Blurry tray icon and main window

![Снимок экрана 2023-11-10 130307](https://github.com/telegramdesktop/tdesktop/assets/120099263/3ef7afce-e6ff-4149-8a16-def185e2efc9)
![Снимок экрана 2023-11-10 130255](https://github.com/telegramdesktop/tdesktop/assets/120099263/6a517c0f-108d-4c0f-883f-b7ce4697c57e)

### Operating system

Windows 11 Pro

### Version of Telegram Desktop

4.11.6

### Installation source

Microsoft Store

**Comment by akelsandrlosev** [comment]
Okay, I reinstalled it to be sure, here are some screens.
![Снимок экрана 2023-11-10 153837](https://github.com/telegramdesktop/tdesktop/assets/120099263/ac69169e-98a0-4af9-a1c4-0ff8b8f6d4e8)
![Снимок экрана 2023-11-10 153849](https://github.com/telegramdesktop/tdesktop/assets/120099263/5ec40ae1-8bac-4eaa-be1c-6cedb6ac4e8a)
![Снимок экрана 2023-11-10 153902](https://github.com/telegramdesktop/tdesktop/assets/120099263/b1a7bd07-92e4-426f-8cc0-e626d59ed3de)

**Comment by ilya-fedin** [comment]
Do you still have counter on tray with unread messages?

**Comment by akelsandrlosev** [comment]
> Do you still have counter on tray with unread messages?

Nope, only notification dot.

**Comment by john-preston** [comment]
The one with the dot is supposed to be pixel perfect, from an .svg :(

**Comment by akelsandrlosev** [comment]
> The one with the dot is supposed to be pixel perfect, from an .svg :(
It's pixel perfect after restarting the program. It's some kind of scaling issue, maybe it's applied before logging in, and windows scaling is most likely unique for each user. Or vice versa, it's a black box for me, the important thing is that the problem is fixed by restarting Telegram and only repeats after system boot with Telegram autorun enabled.
