### ISSUE TITLE
Amazon-Link Preview

### ISSUE THREAD

**Issue by bengaltiger65** [telegramdesktop/tdesktop#27089]
### Steps to reproduce

Send a message with a amazon link: https://amazon.es/dp/B072C58SYL

### Expected behaviour

I get a preview from that link with title and image.

### Actual behaviour

Only the link is send, no preivew.

### Operating system

Windows 11

### Version of Telegram Desktop

4.11.6 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Previews are server-side

**Comment by bengaltiger65** [comment]
but why it works on whatsapp?

**Comment by ilya-fedin** [comment]
Because WhatsApp is not a QtWidgets app? idk what whatsapp uses but if it's Electron then:
1. It draws window content GPU accelerated
2. Uses Xwayland by default
3. Can render 1:1 even with Wayland native mode if it uses new enough Electron as web technologies have no problems with scaling and modern Chrome supports fractional-scale-v1

**Comment by bengaltiger65** [comment]
and why it worked fe days ago in telegram?

**Comment by ilya-fedin** [comment]
Oh, I answered to wrong issue.

**Comment by ilya-fedin** [comment]
Regarding thus issue: whatsapp is a completely different service with its own servers. Whether it works with whatsapp or not is unrelated

**Comment by bengaltiger65** [comment]
becasue the other one said server-side... hwo ecer why there is a problem with amazon links?

**Comment by ilya-fedin** [comment]
The link previews are generated by Telegram server. You have created an issue for tdesktop client so no one here can help you.

WhatsApp doesn't work through Telegram servers, you can't make an example from it.

**Comment by bengaltiger65** [comment]
okay where i can cretae issue for telegram server?
