### ISSUE TITLE
Notifications show in the right most monitor

### ISSUE THREAD

**Issue by chris13524** [telegramdesktop/tdesktop#2708]
In a multi-monitor setup, message notifications are displayed in the right-most monitor.

### Expected behaviour
Notification is displayed in primary monitor.

### Actual behaviour
Notification is displayed in right-most monitor.

### Configuration
**Operating system:**
Ubuntu 16.10
Cinnamon 3.0.7

**Version of Telegram Desktop:**
0.10.19

**Comment by auchri** [comment]
Do you use the native notifications?

**Comment by chris13524** [comment]
No, I do not see any option for that in settings.

**Comment by john-preston** [comment]
@chris13524 Are they shown on the monitor you have Telegram Desktop window on?

**Comment by chris13524** [comment]
@john-preston Yes, farthest right monitor has Telegram on it.

**Comment by john-preston** [comment]
@chris13524 It works as expected then :( currently the notifications are shown on the same screen tdesktop window is.

**Comment by chris13524** [comment]
@john-preston Well then I suggest this be made into an option. Similar to the placement on the screen, you should be able to select the monitor.

**Comment by Aokromes** [comment]
#2510
