### ISSUE TITLE
Message text size on desktop

### ISSUE THREAD

**Issue by f9a0f854** [telegramdesktop/tdesktop#27084]
### Is your feature request related to a problem?

nope

### Describe the solution you'd like

The message text size is fixed on telegram desktop. It is too small. I have to zoom interface scaling to have bigger text. But I don't want to zoom in the whole interface, this makes other parts too large. A function just rescale message text in dialogue, really need it. The function is already on the Phone, transplant it to desktop.

### Describe alternatives you've considered

no alternatives

**Comment by Aokromes** [comment]
#90
