### ISSUE TITLE
Enable the spell checker for only certain languages

### ISSUE THREAD

**Issue by ArianHamdi** [telegramdesktop/tdesktop#27092]
### Is your feature request related to a problem?

I type in Persian and English. As I use colloquial expressions in Persian language, the spell checker will warn me about each word, but I would like to have the spell checker active only for the English language.

### Describe the solution you'd like

I would like to have a feature that enables the spell checker only for a specific language, similar to how the 'do not translate' option for languages works.

### Describe alternatives you've considered

Since the warnings in my native language are annoying, I have to disable the spell checker entirely.

**Comment by ArianHamdi** [comment]
Oh seems duplicate of [#17062](https://github.com/telegramdesktop/tdesktop/issues/17062).

I would like to bring attention to it.

**Comment by ilya-fedin** [comment]
You can choose spell check languages in your system settings

**Comment by ArianHamdi** [comment]
Thank you! it worked.
