### ISSUE TITLE
Keyboard Shortcuts in Telegram

### ISSUE THREAD

**Issue by HuCutie** [telegramdesktop/tdesktop#27095]
### Is your feature request related to a problem?

I wanted to reach out and share a suggestion that I believe could enhance the user experience for many of us. As of now, Telegram doesn't seem to have a dedicated keyboard shortcut feature, and I believe implementing this would be a valuable addition.

The ability to use keyboard shortcuts can significantly improve the efficiency of navigating through chats, managing messages, and other interactions within the application. Many users, including myself, find keyboard shortcuts to be a convenient and time-saving feature.

### Describe the solution you'd like

Some shortcuts can be like this, or editable:
**Compose New Message**: Ctrl N
**Switch between Chats**: Ctrl Tab
**Mark as Read/Unread**: Ctrl R
**Open New Window**: Alt A

### Describe alternatives you've considered

I understand that implementing new features requires careful consideration, and I'm more than willing to provide further details, assist in testing, or contribute in any way possible to make this process smoother.

Thank you for your dedication to maintaining and improving Telegram. I believe that the addition of keyboard shortcuts would be a valuable enhancement, and I appreciate your time and consideration of this feature request.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1060
