### ISSUE TITLE
[FR] Add a possibility to hide a "Smileys" button

### ISSUE THREAD

**Issue by ildar170975** [telegramdesktop/tdesktop#27091]
### Is your feature request related to a problem?

Win10x64
Telegram 4.11.6

In many chats I see this blue baloon:

![image](https://github.com/telegramdesktop/tdesktop/assets/71872483/fc395a02-3e98-4d75-9c51-3372b06dcf86)

To scroll down I need to push "arrow down" button.
But if I miss it a little, a list of smileys pops up:

![image](https://github.com/telegramdesktop/tdesktop/assets/71872483/eb314d84-6cc5-4f66-ac3b-6dfa24248e08)

and it is hidden after some delay, and I cannot press the "arrow down" button since it is overlayed by this list.
So, instead of scrolling down the chat, I have to wait until this list is hidden.

### Describe the solution you'd like

Provide an option is Settings -
Hide "Add smiley" button

### Describe alternatives you've considered

none

**Comment by Aokromes** [comment]
you can disable show popup on hover.

**Comment by ildar170975** [comment]
> you can disable show popup on hover.

How can I do that?

**Comment by ildar170975** [comment]
Thank you, @john-preston  !
