### ISSUE TITLE
Audio file WAV button play not exist

### ISSUE THREAD

**Issue by borodadada** [telegramdesktop/tdesktop#27102]
### Steps to reproduce

I re-uploaded the audio file in WAV format, in place of the play button, the download button, there used to be a play button, how can I get it back? Those files that I didn’t touch, everything is fine there, the play button. MP3 work fine!

### Expected behaviour

Button - play.

### Actual behaviour

Button - download.

### Operating system

Windows 10 x64

### Version of Telegram Desktop

last

### Installation source

Static binary from official website

Screenshot

https://ibb.co/h70YZLB

![Snipaste_2023-11-14_18-18-30](https://github.com/telegramdesktop/tdesktop/assets/5166757/18e03df2-9a77-4ddb-b0b0-7b249ef699ce)

**Comment by calvinklink** [comment]
Yep. Noticed this on the date between the 10th and 12th of November. Suddenly the ability to stream WAV is not there.
![Untitled-1](https://github.com/telegramdesktop/tdesktop/assets/123595709/3dabef8f-a667-448b-afc3-45c517c84e8a)

**Comment by borodadada** [comment]
If re-name WAV file TO FLAC and upload, all work fine. It's BUG. I don't' understand why not fixed it
Developers don't read messages here
