### ISSUE TITLE
There is no option to send delayed messages to groups.

### ISSUE THREAD

**Issue by GolD7777777** [telegramdesktop/tdesktop#27119]
### Steps to reproduce

There is no option to send delayed messages to groups.
Can only be sent via the mobile application.

### Expected behaviour

Make it possible to send scheduled messages to groups in the same way as through a mobile application.

### Actual behaviour

Make it possible to send scheduled messages to groups in the same way as through a mobile application.

### Operating system

windows

### Version of Telegram Desktop

4.11.7

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
works for me (TM)
https://i.imgur.com/Ut1J3Ye.png

**Comment by GolD7777777** [comment]
> works for me (TM) https://i.imgur.com/Ut1J3Ye.png

It's not work in groups with topics.
![Снимок экрана 2023-11-19 220204](https://github.com/telegramdesktop/tdesktop/assets/150553088/63f8035e-220b-4b06-a652-f3cf0ea65658)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25926
