### ISSUE TITLE
externalupdater not working

### ISSUE THREAD

**Issue by beergood** [telegramdesktop/tdesktop#27115]
### Steps to reproduce

1. Create /etc/tdesktop/externalupdater with the following content: /usr/bin/Telegram
2. Put Telegram binary to /usr/bin/
3. Launch the Telegram: /usr/bin/Telegram

### Expected behaviour

No desktop file like "org.telegram.desktop.<HEX>.desktop" should be created in ~/.local/share/applications/

### Actual behaviour

File "org.telegram.desktop.<HEX>.desktop" is created insite of externalupdater existence.

### Operating system

Ubuntu 22.04, Gnome.

### Version of Telegram Desktop

4.11.7

### Installation source

Static binary from official website

**Comment by beergood** [comment]
Creating an externalupdater file was, afaik, the only way to prevent tdesktop from annoying .desktop file creation.

**Comment by ilya-fedin** [comment]
It's not the only, there's also `DESKTOPINTEGRATION=0` environment variable the only disables the creation of .desktop file without stopping managing the updates.

The externalupdater itself is turned into a directory and found using QStandardPaths now. It should work in the following order (checking any files in the directory):
1. Application data directory (typically `~/.local/share/TelegramDesktop` on Linux) `/externalupdater.d`
2. Shared application data directories (typically including `/usr/share/TelegramDesktop` on Linux) `/externalupdater.d`
3. The directory containing the binary `/externalupdater.d`

**Comment by beergood** [comment]
1. Regarding DESKTOPINTEGRATION=0: yes, thanks, it disables .desktop creation, but do not suit for the goal of that prevention, cause the Telegram window itself has "indexed" attributes (the name with HEX), so user created desktop file is not actually used in OS integration (see the screenshot)
2. Regarding externalupdater: yes, thanks, it works as you described and helps to have expected intergration behaviour by sacrificing the updates.

Should I close the issue as externalupdater works. and desired (not only by me, btw) OS intergration is beyond the scope of this task?

**Comment by ilya-fedin** [comment]
You can just create the file with the hex in name? It's logged in log.txt and is MD5 of the path to the binary.

**Comment by beergood** [comment]
Yes, I do.
Thanks for help, it helped a lot!
