### ISSUE TITLE
Don't scale images when display scale is not 100%

### ISSUE THREAD

**Issue by migozz** [telegramdesktop/tdesktop#27114]
### Is your feature request related to a problem?

When Windows display scale is not 100%, the images that are smaller than full screen are upscaled and get blurry

The images that are bigger than the screen, are downscaled, and could not be zoomed in (not related to display scale)

In full screen view, there are "save", "rotate", and "three dots" icons, and when you move the mouse to bottom-right corner, you get over "three dots", and the menu that immediately appeared hides other controls, and the lowest menu item gets highlighted under mouse cursor, and you have to move mouse out and in to hide this menu and point to the desired controls. And this menu does not contain these "save" and "rotate" items.

### Describe the solution you'd like

Display images that are smaller than the screen at 100% scale

Display current zoom level

Add zoom controls

Move the pop-up menu higher to not hover the other controls, and not select by default the item that I wasn't going to select with an accidental mouse movement.

Add pause to that menu 1 sec if not clicked

Do not show that menu if not clicked

Add a tooltip to the items that aren't labeled

### Describe alternatives you've considered

-

**Comment by ilya-fedin** [comment]
Is this a request to change the default behavior or add a button/hotkey to display the image pixel-perfect?

**Comment by migozz** [comment]
Change the default behavior.
