### ISSUE TITLE
Failed to update Telegram :(

### ISSUE THREAD

**Issue by BlackCrowxyz** [telegramdesktop/tdesktop#27110]
### Steps to reproduce

Hello,
Wanted to update telegram to version 4.11.7 but after restarting, it sends this error 3 times (I closed and opened Telegram to fix the issue)
![image](https://github.com/telegramdesktop/tdesktop/assets/31730646/2a7fbdcc-d085-4c19-80d9-a86c48418e5c)

### Expected behaviour

No error

### Actual behaviour

Giving error multiple times

### Operating system

Microsoft Windows [Version 10.0.19042.2965]

### Version of Telegram Desktop

4.11.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Some other application has acquired the access to Telegram's file for whatever reason, try to reboot your computer.

**Comment by BlackCrowxyz** [comment]
Sorry for delay, it was okay. thanks for your answer.
Another problem which I have is that whenever I click on proxy list, it takes time to open proxy tab and make telegram slow. I think it is due to many proxies which I have :)
