### ISSUE TITLE
Ctrl+Q is not working anymore

### ISSUE THREAD

**Issue by cijic** [telegramdesktop/tdesktop#27124]
### Steps to reproduce

1. Open app.
2. Try to press the keys Ctrl+Q.

### Expected behaviour

App should close on this keyboard shortcut as it was implemented earlier https://github.com/telegramdesktop/tdesktop/issues/703

### Actual behaviour

Nothing.

### Operating system

Win 7

### Version of Telegram Desktop

4.11.7 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
works for me on windows 10.

**Comment by cijic** [comment]
> works for me on windows 10.

I have specified another Win version.
Earlier, a few month ago, 100% worked as expected.

**Comment by Aokromes** [comment]
i know you use windows 7, but i don't have windows 7, and i doub os will change

**Comment by cijic** [comment]
Can you check was something changed in version 4 connecting with keyboard shortcuts?
Or even specify place in code when I can check it?

**Comment by cijic** [comment]
Found issue on my side.
Closing ticket.

Thanks any way.
