### ISSUE TITLE
If URL ends with a dot wrong page will open

### ISSUE THREAD

**Issue by Sopor** [telegramdesktop/tdesktop#27127]
### Steps to reproduce

Send a URL that ends with a dot `https://viaplay.se/serier/magnum-p.i.`

Click on it or copy it to clipboard!

### Expected behaviour

The page should open `https://viaplay.se/serier/magnum-p.i.`

### Actual behaviour

Telegram will remove the last dot and because the page doesn't exists the site will show another page.

In this case `https://viaplay.se/serier`

### Operating system

Windows 10 x64

### Version of Telegram Desktop

4.11.7 (portable)

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@Sopor The links are parsed on the server side. In case of such links you could use a manually inserted link with Ctrl+K (Cmd+K on macOS) shortcut.

**Comment by Sopor** [comment]
I understand why it will send me to another page.

Everyone knows that if you send a URL to someone you don't add a dot to the end (if you want the URL to work), so i see no reason why Telegram should automatically remove the dot from the URL and treat the dot as it was the end of the line instead of a part of the URL..

I don't check every URL i send if they ends with a dot or not. I copy it and paste URLs to my friends and expect them to work as they are without Telegram to change them.
