### ISSUE TITLE
Can't input typographic «quotes» in message on Fedora 39 Gnome

### ISSUE THREAD

**Issue by eshfield** [telegramdesktop/tdesktop#27123]
### Steps to reproduce

1. Open any dialog
2. Try to type in typographic quotes: «» with `Alt + <` and `Alt + >` shortcuts with [typography symbols enabled](https://medium.com/@png2378/что-такое-типографская-раскладка-47db999baee6)
3. Nothing inserted
4. Another typographic symbols works correctly: I can type → © ₽ but not «»

### Expected behaviour

Typographic quotes insert

### Actual behaviour

Typographic quotes don't insert

### Operating system

Fedora 39 Gnome DE

### Version of Telegram Desktop

4.11.3

### Installation source

Flatpak

### Crash ID

N/A

### Logs

```shell
N/A
```

**Comment by ilya-fedin** [comment]
#26976

**Comment by eshfield** [comment]
I have removed  the Flatpak Telegram version and installed it from tar.xz from the official Telegram site — the problem is still there.
Version 4.11.7

**Comment by ilya-fedin** [comment]
Yeah, it has xkbcommon statcally compiled in. I guess you need to use a distro version until people will find a way to make compositors and clients with different xkbcommon versions to work correctly.

**Comment by eshfield** [comment]
Thanks for helping, Ilya.
Unfortunately it looks like there is no official distro version of Telegram in Fedora — Flatpak only.
Hope this issue will resolve someday in future.

**Comment by ilya-fedin** [comment]
I thought it's in rpmfusion, no? Anyway, the next static binary release updates qtwayland so I guess it's a good time to update xkbcommon as well as docker image has to be rebuilt anyway.

**Comment by eshfield** [comment]
Well, I don't wont to use RPM Fusion.

Also I remembered when I used Ubuntu from 18 to 22 versions I didn't have such problem no matter of Telegram distribution source.

**Comment by ilya-fedin** [comment]
Ubuntu has older xkbcommon likely, Ubuntu LTS updates once in two years

**Comment by ilya-fedin** [comment]
Okaaay, it didn't work, Qt doesn't build with that new xkbcommon
