### ISSUE TITLE
[Feature Request] Tweets with multiple images should unfurl all images

### ISSUE THREAD

**Issue by CVertex** [telegramdesktop/tdesktop#2712]
### Summary

When linking to tweets, Telegram currently unfurls the status text content and the image. When there are multiple images, telegram only shows the final image. This is bad for tweets that use multiple images for jokes and other tweets where the multiple images are the primary and essential piece of the content, not just an attachment.

### Steps to reproduce
1. In any conversation, post https://twitter.com/TheDiLLon1/status/808697839530496000
2. The link should unfurl showing the content of the tweet and one image (Trump and Kanye)

### Expected behaviour

Rather than showing the last image for this tweet. Telegram should include all images, ordered by their time

### Actual behaviour
Only the final image is shown

### Configuration

Windows and iOS
Telegram Desktop v 0.10.16 

### Logs
No logs

### Finally

I love telegram, thanks everyone for their hardwork! It does the core stuff really well, and i really love the fact telegram tries to keep up with the other social networking apps with rich content. This engagements keeps me, my friends and family using telegram

❤️ ❤️ ❤️

**Comment by stek29** [comment]
Sorry, but it's an server side issue + API issue (previews with multiple pictures are not supported at all)

**Comment by CVertex** [comment]
@stek29 :( Where can i make a feature request for this?

**Comment by stek29** [comment]
@CVertex At Twitter or using "Ask a question" button in settings.
Also, wouldn't you close the issue? :)

**Comment by dogancelik** [comment]
I don't think Twitter would listen to us (users)… considering their abrupt changes on the platform…
Because Telegram server is closed source, we don't know if the server or client can support such capability.
