### ISSUE TITLE
Telegram mini apps not working on fedora linux

### ISSUE THREAD

**Issue by Feeralbee** [telegramdesktop/tdesktop#27133]
### Steps to reproduce

1. open @durgerkingbot
2. send /start
3. click on button "order food"

### Expected behaviour

![изображение](https://github.com/telegramdesktop/tdesktop/assets/96689023/ff60034e-4f35-49ee-b6db-481d5be422e2)

### Actual behaviour

Mini app won't open and keeps loading endlessly. If I open it via web.telegram, everything works.
![изображение](https://github.com/telegramdesktop/tdesktop/assets/96689023/f9f0082e-8577-4398-a271-77af45689687)

### Operating system

Fedora 39 Gnome 45.1

### Version of Telegram Desktop

4.11.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Provide log.txt as instructed in the issue template + terminal output

**Comment by danoctua** [comment]
> > Let me know if you need anything else from me.
> 
> Does setting `GDK_GL=disable` help?

No, it doesn't change anything in my case.

**Comment by danoctua** [comment]
> How did you set it?

I tried two ways:

1. Set this env variable before running the application from the Terminal
2. Set it in the Flatseal as an environment variable.

**Comment by ilya-fedin** [comment]
Ok, thanks

**Comment by ilya-fedin** [comment]
info from @Feeralbee is still required (or bot will close the issue).

**Comment by danoctua** [comment]
> It could be related to [flatpak/flatpak#5167](https://github.com/flatpak/flatpak/issues/5167) though. This flatpak bug makes the Wayland webview backend to be unable to work in flatpak package. If it is then the only thing you can do is to use a non-flatpak build.

I just tried to use the snap installation, and the same error appears. So it's probably not related to the flatpak

**Comment by danoctua** [comment]
> Snap is broken as well, yes, but due to libraries versions in core22 (they're too old and self-building newer versions breaks webview for whatever reason). Only the static binary works.

Here is the similar log for the static binary:

```
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.waylandcompositor.hardwareintegration: Failed to initialize EGL display. Could not get EglDisplay for window.

(Telegram:179500): GLib-GIO-WARNING **: 10:43:18.782: Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal.  It should do one of these.
error in client communication (pid 179500)
Gdk-Message: 10:43:19.057: Error 71 (Protocol error) dispatching to Wayland display.
```

Doesn't work for me as well

**Comment by ilya-fedin** [comment]
> No

what about `GDK_DEBUG=gl-disable`?

**Comment by ilya-fedin** [comment]
Yeah, nothing would help to snap, you have to use static binary.

**Comment by danoctua** [comment]
> > No
> 
> what about `GDK_DEBUG=gl-disable`?

Same error, even with a static binary :/

**Comment by danoctua** [comment]
> @danoctua what version of webkitgtk you have?

Sorry, for the delay

![image](https://github.com/telegramdesktop/tdesktop/assets/37304160/1baf9766-7c8c-4f2e-a287-0f9d7f417e35)

**Comment by ilya-fedin** [comment]
@danoctua try to launch with `WAYLAND_DEBUG=1` and redirect the output to a file so you can upload it

**Comment by ilya-fedin** [comment]
@danoctua your case doesn't seem to be related to #26978, it crashes with `WaylandCompositor requires eglBindWaylandDisplayWL, eglUnbindWaylandDisplayWL and eglQueryWaylandBuffer.`, not with a protocol error.

**Comment by ilya-fedin** [comment]
Looks like webkitgtk or gtk is confusing QtWaylandCompositor so it errors out with `wl_display@1.error(xdg_wm_base@12, 0, "wl_surface@16, already has role xdg_toplevel`. I'm not sure what to do with that. Perhaps given the amount of reports it has sense to blacklist everything but KDE X11 for webview on Linux.

**Comment by micka-io** [comment]
Add the same issue, managed to get it working using

`env GDK_BACKEND=x11 QT_QPA_PLATFORM=xcb telegram-desktop`

**Comment by ilya-fedin** [comment]
someone has created a new issue: #27251
