### ISSUE TITLE
Telegram Desktop Freezing and Not responding.

### ISSUE THREAD

**Issue by ChesterCloud** [telegramdesktop/tdesktop#2713]
### Steps to reproduce
1. Telegram 0.10.19 on Windows 10 1607 freezes when I get message and when native notification of windows 10 switched on.
Only thing that I can do, it is just to kill the process.

### Expected behaviour
Work as expected, open notification and message.

### Actual behaviour
Telegram completely freezes and does not respond.

### Configuration
Windows 10 1607 x64 with latest updates.

Telegram 0.10.19

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by auchri** [comment]
Bug of windows and duplicate
