### ISSUE TITLE
Telegram does not launch on the primary display when the "Launch Telegram when system starts" setting enabled

### ISSUE THREAD

**Issue by w3lifer** [telegramdesktop/tdesktop#27136]
### Steps to reproduce

1. Laptop and monitor.
2. Set your monitor as your primary display.
3. Disable the "Use system window frame" setting.
4. Enable the "Launch Telegram when system starts" setting.
5. Log Out & Log In.

### Expected behaviour

Telegram must be open on the primary display.

### Actual behaviour

Telegram opened on the laptop display.

### Operating system

Ubuntu 22.04.3 LTS

### Version of Telegram Desktop

4.11.8

### Installation source

Snap

**Comment by ilya-fedin** [comment]
On the modern Linux like Ubuntu 22.04 applications can't control the position window opens at, it's decided by the system.

**Comment by w3lifer** [comment]
I enabled the "Use system window frame" setting, and now when system starts, Telegram opens on the primary display.
(edited "Steps to reproduce")

**Comment by ilya-fedin** [comment]
As far as I'm aware the modern Ubuntu doesn't have system window frame support :thinking:

**Comment by ilya-fedin** [comment]
If you have the option then you have enabled legacy APIs somehow... You should provide the log as instructed by the issue template.

**Comment by w3lifer** [comment]
> If you have the option then you have enabled legacy APIs somehow... You should provide the log as instructed by the issue template.

I have updated Ubuntu gradually without installing from scratch since Ubuntu 18, maybe that's why

[log.txt](https://github.com/telegramdesktop/tdesktop/files/13462304/log.txt)
[log_start0.txt](https://github.com/telegramdesktop/tdesktop/files/13462305/log_start0.txt)

**Comment by ilya-fedin** [comment]
Actually I'm not sure there's a bug. It should open on the last saved position, not on primary display. The issue title doesn't say any thing about last position, it only says primary/non-primary thingy which doesn't sound like a valid issue.

**Comment by Bibicool69** [comment]
Bonjour

**Comment by w3lifer** [comment]
> Actually I'm not sure there's a bug. It should open on the last saved position, not on primary display. The issue title doesn't say anything about last position, it only says primary/non-primary thingy which doesn't sound like a valid issue.

Yes, indeed, the last position of Telegram in its unexpanded state somehow affects what display it will open on when entering the session. But the "Use system window frame" setting also has some effect.

In its unexpanded form, I mean this:

![Screenshot from 2023-11-25 22-44-39](https://github.com/telegramdesktop/tdesktop/assets/14075412/25e2d39f-1332-4355-a9c0-c5bf81d79a2c)

**Comment by ilya-fedin** [comment]
So, there's no issue, right? It opens on the last position as it should?

**Comment by w3lifer** [comment]
> So, there's no issue, right? It opens on the last position as it should?

I'm not ready to answer this question. The issue can be closed. As soon as I'm sure exactly how it's reproduced, I'll write a comment.

**Comment by ilya-fedin** [comment]
You can see the data of the window position saving/restore in debug logs. You can nter `debugmode` [cheat code](https://github.com/telegramdesktop/tdesktop/wiki/Cheat-Codes) to enable the debug logs, they will be in the DebugLogs subfolder, sliced every 15 mins. The lines of position saving/restoring logic have `Window Pos`.

**Comment by w3lifer** [comment]
This is really not an issue. And the "Use system window frame" setting has no effect on this. It all depends on what screen we minimized it on, but not to the tray, but as above in the screenshot, that is, to an unexpanded state.

**Comment by w3lifer** [comment]
Thanks 🙏

**Comment by Bibicool69** [comment]
What

**Comment by w3lifer** [comment]
> This is really not an issue. And the "Use system window frame" setting has no effect on this. It all depends on what screen we minimized it on, but not to the tray, but as above in the screenshot, that is, to an unexpanded state.

Still, no: the “Use system window frame” setting affects the opening of Telegram when logging into a session. If you enable it, Telegram always starts on the display where it was before leaving the session. If you disable it, then Telegram always launches on the laptop display.

**Comment by ilya-fedin** [comment]
Provide the `Window Pos` lines from the bug moment
