### ISSUE TITLE
Count unread messages from ARCHIVE

### ISSUE THREAD

**Issue by 1223421** [telegramdesktop/tdesktop#27138]
### Steps to reproduce

1. Put chat to archive
2. wait for messages..

### Expected behaviour

The unread count should not include archived chats.

### Actual behaviour

Why are archived chats included in the unread counter?

![1](https://github.com/telegramdesktop/tdesktop/assets/106692737/c97f6d96-0249-4d31-b61b-b6d21772488f)
![2](https://github.com/telegramdesktop/tdesktop/assets/106692737/9dfa3e11-9de8-4868-a73e-b0f5ae423285)

### Operating system

Linux

### Version of Telegram Desktop

4.11.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Because the person who decides the UX has decided so. You can disable notifications for muted chats in settings, for such a setting for archive there's already a feature request, use issue search.
