### ISSUE TITLE
Unexpected page size on Apple Silicon

### ISSUE THREAD

**Issue by RossComputerGuy** [telegramdesktop/tdesktop#27131]
### Steps to reproduce

1. Use an Apple Silicon device with a Linux distro that is supported
2. Install telegram from Flatpak
3. Run telegram

### Expected behaviour

Telegrams should run

### Actual behaviour

```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
```

Related: https://github.com/jemalloc/jemalloc/issues/2572#issuecomment-1823559681

### Operating system

NixOS 23.05 w/ nixos-apple-silicon (kernel: 6.5.0-asahi)

### Version of Telegram Desktop

4.11.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
#24564
