### ISSUE TITLE
after update my telegram wouldn't start on desktop, 

### ISSUE THREAD

**Issue by Vagabondcaravan202020** [telegramdesktop/tdesktop#27137]
### Steps to reproduce

Update telegram
It stops working
Using Pop!_OS 22.04 LTS, 

### Expected behaviour

Expecting it to start / load up as usual

### Actual behaviour

nothing happens

### Operating system

Pop!_OS 22.04 LTS, 

### Version of Telegram Desktop

Latest

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Provide ~/.local/share/TelegramDesktop/log.txt

**Comment by pchmykh** [comment]
Can approve on Fedora 39, flatpak version. Please look for output in attachment.
[2023 11 23 23 00 08 Launched.txt](https://github.com/telegramdesktop/tdesktop/files/13453183/2023.11.23.23.00.08.Launched.txt)

**Comment by ilya-fedin** [comment]
For flatpak there's another issue, please don't mix this one or it will be closed as a duplicate

**Comment by matbon108** [comment]
I just updated via flatpak to verion 4.11.8 and it also won't start. Running form cli shows
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.svg: Error while inflating gzip file: SVG format check failed

Is this related?

**Comment by ilya-fedin** [comment]
The issue says

> ### Installation source
> 
> Static binary from official website

So I don't think so.

**Comment by philmalin** [comment]
Hi there.

I updated Telegram this morning (flatpak) and am getting the same error as matbon108 above.

I've attached the log.txt (located at ~/.var/app/org.telegram.desktop/data/TelegramDesktop for flatpak users), but there doesn't seem to have anything related to the error that gets printed out when running Telegram.

[log.txt](https://github.com/telegramdesktop/tdesktop/files/13453667/log.txt)

**Comment by ilya-fedin** [comment]
Please stop mixing flatpak issues here or the issue will be closed as a duplicate

**Comment by matbon108** [comment]
> Please stop mixing flatpak issues here or the issue will be closed as a duplicate

My apologies for the first post, when searching "flatpak telegram" this is the link that comes up and I suspect philmalin had the same. Where would be the appropriate link?

**Comment by ilya-fedin** [comment]
See the first page of issues
