### ISSUE TITLE
Media Viewer loads previous viewed photo or video first

### ISSUE THREAD

**Issue by alexeynl** [telegramdesktop/tdesktop#27130]
### Steps to reproduce

Click on video or photo in message.

### Expected behaviour

Media Viewer shows video or photo full screen.

### Actual behaviour

Media Viewer first shows full screen previous opened photo or video for a second and than the photo or video i clicked.

Check for screen recording video:

https://www.youtube.com/watch?v=ZdN6GR_VYgM

Timings: 5, 21, 24, 27 seconds.

### Operating system

Windows 10, 11

### Version of Telegram Desktop

4.11.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#27109

**Comment by alexeynl** [comment]
> #17109
It looks like the same issue. 
But worth to mention that 
1) i have this issue on my ryzen notebook since i have bought it in july 2022.
2) i tried a lot of things since i july 2022: starting from reinstall windows (including windows 10) and ends with regular AMD drivers and Windows updates.

**Comment by john-preston** [comment]
@alexeynl I hope it's fixed in code, we'll see in the next release.

**Comment by alexeynl** [comment]
Why is issue was closed?

**Comment by Aokromes** [comment]
because it was duplicate.
