### ISSUE TITLE
Flatpak Telegram Desktop Fails to Launch on Fedora 39 with Wayland

### ISSUE THREAD

**Issue by Wladefant** [telegramdesktop/tdesktop#27141]
### Steps to reproduce

1. Try to launch Telegram Desktop from the KDE menu/launcher.
2. Observe the error message "Launching Telegram Desktop (Failed) - The name is not activatable".

### Expected behaviour

Telegram Desktop should launch successfully from the KDE menu/launcher.

### Actual behaviour

Telegram Desktop fails to launch with the aforementioned error message.

I suspect this may be related to a problem with desktop integration or a D-Bus service activation issue specific to the Flatpak package when not initiated via the command line.

Any assistance or guidance in resolving this issue would be greatly appreciated.

### Operating system

Fedora Linux 39, KDE Plasma Version: 5.27.9, KDE Frameworks Version: 5.111.0,  Qt Version: 5.15.11, Graphics Platform: Wayland

### Version of Telegram Desktop

4.11.8 (from Flathub)

### Installation source

Flatpak

**Comment by Vilianexe** [comment]
i was having the exactly same problem and the log was this
```QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
```
but i updated and it's opening fine now

**Comment by Aokromes** [comment]
duplicate.

**Comment by Wladefant** [comment]
@Aokromes Well would be also nice if you could link the issue as I couldnt find anything

**Comment by Vilianexe** [comment]
> @Aokromes Well would be also nice if you could link the issue as I couldnt find anything

https://github.com/telegramdesktop/tdesktop/issues/27134 i think it's this
