### ISSUE TITLE
Crash after pressing link to downloads folder

### ISSUE THREAD

**Issue by pchmykh** [telegramdesktop/tdesktop#27145]
### Steps to reproduce

1. Open some image at chat
2. Press Download icon
3. Look at 'Image was save to your Downloads folder' notification, which includes link.
4. Press 'Download' link to open directory

### Expected behaviour

5. File manager opens Downloads folder

### Actual behaviour

5. Telegram crashes

### Operating system

Fedora Workstation 39

### Version of Telegram Desktop

4.11.8

### Installation source

Flatpak

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org
