### ISSUE TITLE
Intel MIPI Camera not working with Telegram Desktop on Ubuntu

### ISSUE THREAD

**Issue by astromark** [telegramdesktop/tdesktop#27144]
### Steps to reproduce

1. Start video call with friend

### Expected behaviour

Friend should see my video.

### Actual behaviour

Friend does not see my video.

### Operating system

Ubuntu 22.04.3

### Version of Telegram Desktop

4.11.7

### Installation source

Static binary from official website

**Comment by astromark** [comment]
I initially had issues getting the camera to work with any software but updates to the drivers have now fixed it for any other software I've tried (Zoom, Skype, Cheese...). 
This issue is still present if I use Snap or Flatpak versions.

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
> Friend does not see my video.

What he sees instead?

**Comment by astromark** [comment]
The same as a call with the camera turned off.

**Comment by ilya-fedin** [comment]
You mean camera is not detected at all?

**Comment by astromark** [comment]
If I go to call settings, it does list 'Intel MIPI camera' under the camera option, so it knows the camera is there, but no image shows up.

**Comment by ilya-fedin** [comment]
Sadly camera support is provided by a third-party library...

**Comment by astromark** [comment]
OK. What's the third party library? Maybe if I look into that I can find a solution.

**Comment by ilya-fedin** [comment]
WebRTC

**Comment by astromark** [comment]
Thanks.
