### ISSUE TITLE
High CPU load & power usage when anything in the UI is animated

### ISSUE THREAD

**Issue by lilydjwg** [telegramdesktop/tdesktop#27147]
### Steps to reproduce

1. prepare to watch CPU and/or power usage
2. keep Telegram window focused, but avoid anything changing (except the curosr maybe)
3. keep Telegram window focused, and keep an animated sticker / avatar / typing indicator in view

### Expected behaviour

Only a small amount of extra resource should be used, like other applications like Firefox. Telegram should only update where the animation is to avoid excessive resource usage.

### Actual behaviour

About 170% more CPU is used, and 20W more watts (not including the monitor). The whole window (a bit less than 3840x2160) is refreshed every time something changes.

I've already disabled most animation for this reason, but animated avatars can't be disabled, and thus I have to close the chat as soon as possible.

This issue has been happening months ago. Recently I realized that animated avatars can't be disabled and my money is wasting for a less than 4cm² animation.

### Operating system

Arch Linux, Wayland (Wayfire)

### Version of Telegram Desktop

4.11.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Are you sure it's due to entire window being repainted rather than Telegram is QtWidgets (so drawn with CPU) while Firefox is using GPU to paint all its UI?

**Comment by lilydjwg** [comment]
I don't have data for power usage, but for CPU usage I know that in the past, some old version of Telegram only draws as necessary used much less CPU. (I can't remember which version though; it was when I disabled animations.)

**Comment by ilya-fedin** [comment]
The thing is animations are painted with CPU using 7ms interval between frames so high CPU usage is completely expected

**Comment by ilya-fedin** [comment]
So given that you have no proofs it's actually some painting bug rather than just the app being written with QtWidgets then there's no point in having the issue open. If CPU usage is important to you then perhaps you can only switch to the web client that will utilize your browser's GPU support.

**Comment by lilydjwg** [comment]
I tested with Firefox with CPU rendering vs GPU rendering. It's about the same power usage: about 6 more watts on https://zh.wikipedia.org/wiki/GIF. It's significantly less then Telegram.

**Comment by ilya-fedin** [comment]
Maybe llvmpipe is just more efficient than QtWidgets? Firefox uses llvmpipe mesa driver rather than really painting with CPU code.

**Comment by ilya-fedin** [comment]
#24658 is the your issue perhaps then

**Comment by lilydjwg** [comment]
Anyway less CPU usage was observed with an older version of Telegram. That's why I think painting is the issue.

**Comment by ilya-fedin** [comment]
You also said there were no animations in those versions

**Comment by ilya-fedin** [comment]
Maybe the issue has appeared when Qt switched to native Wayland? There's a report claiming there's bad performance on Wayland: #26343.

**Comment by lilydjwg** [comment]
It is possible.

**Comment by ilya-fedin** [comment]
Check it?

**Comment by lilydjwg** [comment]
Will do later.

**Comment by lilydjwg** [comment]
Tested with xwayland. Confirm. Only animated area is updated and power usage is much lower.

**Comment by ilya-fedin** [comment]
So it's a dup...

**Comment by lilydjwg** [comment]
Yeah. Thanks anyway.
