### ISSUE TITLE
Unread indicator on desktop icon will not change 

### ISSUE THREAD

**Issue by le-cha-sever-bl** [telegramdesktop/tdesktop#27153]
### Steps to reproduce

I have the correct number of unread messages displayed.
![image](https://github.com/telegramdesktop/tdesktop/assets/151947351/34e43003-3d17-4ca7-b5c5-6c307add80d6)
My colleague has the wrong number of messages when logging into his account
![image](https://github.com/telegramdesktop/tdesktop/assets/151947351/c6cedbad-29cd-4dbc-af6a-fa0ace5d8795)
We deleted the entire .local/share/TelegramDesktop folder. It did not help.
When the colleague logs into his account (@ksyrot), the number of messages becomes 9999. But on the phone everything in his account is been read - it should be 0.
When I log into my account (@le_cha_sever), the correct number of messages is displayed.

This issue is similar to this https://github.com/telegramdesktop/tdesktop/issues/26884
We did the suggested solution (https://github.com/telegramdesktop/tdesktop/issues/26884#issuecomment-1743890998), it didn't help us.

### Expected behaviour

The indicator should read the number of new messages.

### Actual behaviour

The indicator always shows 9999 messages

### Operating system

FreeBSD(13.2)/KDE

### Version of Telegram Desktop

v.4.8.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Mobile clients don't show unread messages for muted chats while tdesktop does, maybe that's the difference?

**Comment by le-cha-sever-bl** [comment]
> Mobile clients don't show unread messages for muted chats while tdesktop does, maybe that's the difference?

Thanks, but it is not this case.
We checked

**Comment by ilya-fedin** [comment]
Does it happen on a new system user?
