### ISSUE TITLE
Second accuracy timestamps for messages

### ISSUE THREAD

**Issue by Tsopic** [telegramdesktop/tdesktop#27150]
### Is your feature request related to a problem?

The problem is, that there is no way to know the exact message timestamp in the Mac Desktop app and Android app.

This is needed for life below 1 minute accuracy.

### Describe the solution you'd like

Setting under chat appearance that lets you select message time appearance format: (hh:mm) (hh:mm:ss)

### Describe alternatives you've considered

It seems there is currently none for Mac Desktop App

**Comment by Aokromes** [comment]
idk what client you are using, but on telegram desktop (or telegram lite on macos store) you can
https://i.imgur.com/nkJCTgQ.png

**Comment by Tsopic** [comment]
I use the Mac Main (not Lite) client.

I'm able to successfully see all the timestamps on Windows Machine (With some timestamp format on manipulation on Windows level). Would love to be able to have such timestamps in Android and Mac also. The "hover" on the timestamp does not give me the result seen in your picture. 

The question arises, why do I have to manipulate the win registry for a thing that should be a feature...

Windows machine snapshot:
![image](https://github.com/telegramdesktop/tdesktop/assets/3941909/2ba86f72-99aa-4f66-9537-3cc5b3545bab)


Okay, let's leave the "official" Mac App aside, what about the Android one? Same thing, how do you see accurate timestamps there? Currently, I pretty much have to hop on my win machine to see it.

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
