### ISSUE TITLE
tdesktop development abandoned?

### ISSUE THREAD

**Issue by ManuelSchneid3r** [telegramdesktop/tdesktop#2715]
@john-preston Actually this is not a software issue. Rather a public question. Sorry for abusing the issue tracker for this, but there is no other way of contacting you. Your, until then, frequently commits stopped on Oct, 26th. Has the development of telegram desktop been abandoned?

**Comment by john-preston** [comment]
@ManuelSchneid3r No, there is just a major update being prepared, it will be released together with its source code on github.

**Comment by ManuelSchneid3r** [comment]
@john-preston Thank you for the quick response. When will it be releases (approximately)?

**Comment by john-preston** [comment]
@ManuelSchneid3r I really hope that before the new year :D

**Comment by ManuelSchneid3r** [comment]
Cool, looking forward to it. Thank you.
