### ISSUE TITLE
Transcription isn't working again

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#27151]
### Steps to reproduce

I click on the transcribe button for a VM

### Expected behaviour

It should transcribe what was said

### Actual behaviour

It says failed. At first it wouldn't work, I restarted TG, then it said failed. 

### Operating system

Windows 10

### Version of Telegram Desktop

4.11.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This is a server-side service, you should use "platform-wide" issue type when creating issue

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by ilya-fedin** [comment]
@ILoveSkilledCoders looking through issues you were creating, most of them are server-side. There's no person at this bugtracker who can help to solve them. Given that it seems you're unable to differentiate client-side and server-side issues, please report any future problems via the bugs & suggestion platform that accepts any kind of reports/suggestions. You can also use in-app support for bug reporting/feature requesting.

**Comment by ILoveSkilledCoders** [comment]
I started adding bugs here because no one EVER responds on the other site/link.

Why doesn't anyone respond to the bug reports there?

**Comment by ilya-fedin** [comment]
Not enough moderators I guess. Or they just don't think your issue deserves any comments.

**Comment by ilya-fedin** [comment]
I see they have around 10k bug reports. I wouldn't expect anyone to answer personally with such big flow.
![изображение](https://github.com/telegramdesktop/tdesktop/assets/17829319/4807cfe3-967d-4be3-a2ea-ebe2123880f7)
