### ISSUE TITLE
Resize issue on very high res

### ISSUE THREAD

**Issue by VikiMaster2** [telegramdesktop/tdesktop#2716]
I discovered there's an issue with the Desktop app on windows, I'm using a 21:9  2650x1080 monitor

### Steps to reproduce
1. Resize the app over 1707px
2. 

![image](https://cloud.githubusercontent.com/assets/7188510/21288570/94be93fa-c48f-11e6-8682-a7755a0f2162.png)  Before 1078px   
3.

![image](https://cloud.githubusercontent.com/assets/7188510/21288613/c64e0012-c490-11e6-8f15-4ee569456623.png)
  After 1078px

### Configuration
Microsoft Windows **1607 14393.576**   64bit
Telegram **v0.10.16**

**Comment by gudvinr** [comment]
And why is that issue? It's just easier to read on wide desktops.
But if you don't like it you can always disable with checkbox "Adaptive layout for wide screens" in settings which available when app become wide enough.

**Comment by auchri** [comment]
duplicate
