### ISSUE TITLE
Compilation failed - ninja error file not found

### ISSUE THREAD

**Issue by mrbesen** [telegramdesktop/tdesktop#27162]
### Steps to reproduce

1. checkout dev
2. Make sure the submodules are up to date and the worktree is clean
```bash
git submodule update --recursive
sudo git submodule foreach git clean -fxd  # some submodules had files belonging to root
```
3. build the container
```bash
bash ./Telegram/build/prepare/linux.sh
```
4. try to compile
```bash
docker run --rm -it \
        -v $PWD:/usr/src/tdesktop \
        tdesktop:centos_env \
        /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
        -D TDESKTOP_API_ID=API_ID \
        -D TDESKTOP_API_HASH=API_HASH
```

### Expected behaviour

Telegram should have been compiled

### Actual behaviour

An error occoured and the process exited with code 1

```
Warn about uninitialized values.
Version: 4.11.8
CMake Error at CMakeLists.txt:30 (project):
  Running

   '/opt/rh/rh-python38/root/usr/local/bin/ninja' '--version'

  failed with:

   No such file or directory


-- Configuring incomplete, errors occurred!
```

This happens regardless of `DEBUG=1` and no matter if i insert a valid API_ID and HASH or not.

I have tried to investigate this with bash:

```bash
docker run --rm -it \
        -v $PWD:/usr/src/tdesktop \
        -e DEBUG=1 \
        tdesktop:centos_env \
        bash
[root@66308bcdacc2 tdesktop]# /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
>         -D TDESKTOP_API_ID=YOUR_API_ID \
>         -D TDESKTOP_API_HASH=YOUR_API_HASH
Warn about uninitialized values.
Version: 4.11.8
CMake Error at CMakeLists.txt:30 (project):
  Running

   '/opt/rh/rh-python38/root/usr/local/bin/ninja' '--version'

  failed with:

   No such file or directory


-- Configuring incomplete, errors occurred!
[root@66308bcdacc2 tdesktop]# ls /opt/rh/rh-python38/root/usr/local/bin/ninja
ls: cannot access '/opt/rh/rh-python38/root/usr/local/bin/ninja': No such file or directory
[root@66308bcdacc2 tdesktop]# ninja
ninja: error: loading 'build.ninja': No such file or directory
[root@66308bcdacc2 tdesktop]# which ninja
/usr/local/bin/ninja
[root@66308bcdacc2 tdesktop]# ls /usr/local/bin/ninja -l
-rwxr-xr-x 1 root root 206 Nov  4 20:27 /usr/local/bin/ninja
[root@66308bcdacc2 tdesktop]# find / -name ninja
/usr/local/bin/ninja
/usr/local/lib64/python3.11/site-packages/ninja
/usr/local/lib64/python3.11/site-packages/ninja/data/bin/ninja
[root@66308bcdacc2 tdesktop]#
```

If required i can export and upload the docker image if that helps with the investigation. But i would rather not (its 26.6GB)

### Operating system

Linux Mint 21

### Version of Telegram Desktop

f442d69cb68dc124e46b59655559f0b1b7cc99db

### Installation source

~~Static binary from official website~~
git

**Comment by 23rd** [comment]
If you just want to build the client, I would suggest to grab the ready-to-use [container](https://github.com/telegramdesktop/tdesktop/pkgs/container/tdesktop%2Fcentos_env).

**Comment by ilya-fedin** [comment]
looks like you have run `git clean -fxd` on submodules but not on the root repo so the build cache is still not cleaned

**Comment by mrbesen** [comment]
> looks like you have ran `git clean -fxd` on submodules but not on the root repo so the build cache is still not cleaned

That is true, but i had checked the root with `git status` before. It was also clean.

**Comment by ilya-fedin** [comment]
Yes, it will be clean yet you have to do that
