### ISSUE TITLE
Telegram bugging, cant turun group from public to private. BOT ATTACK as well.

### ISSUE THREAD

**Issue by raullpz17** [telegramdesktop/tdesktop#27166]
### Steps to reproduce

![Screenshot 2023-11-29 at 7 14 33 PM](https://github.com/telegramdesktop/tdesktop/assets/146778529/8cdc0bdb-8289-4a9a-a4d0-88f48b1ca86c)

### Expected behaviour

cant save on my end

### Actual behaviour

i want to save before someone else does it and takes over

### Operating system

mac. telegram

### Version of Telegram Desktop

i tried on my phone too

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
If you can't save it means the server doesn't let you so, it's not a bug in the client
