### ISSUE TITLE
Build prep step fails on Windows 11 when building libvpx

### ISSUE THREAD

**Issue by ssg** [telegramdesktop/tdesktop#27163]
### Steps to reproduce

Run `prepare\win.bat` after taking all recommended steps.

### Expected behaviour

Build should succeed.

### Actual behaviour

Build fails while building libvpx. The error message is:

> `%BuildPath%\Libraries\win64\tg_owt\src\modules/video_coding/codecs/interface/libvpx_interface.h(18): fatal error C1083: Cannot open include file: 'vpx/vp8cx.h': No such file or directory`

The file `vp8cx.h` actually exists under `%BuildPath%\Libraries\win64\libvpx\vpx`.

### Operating system

Windows 11 Pro 23H2

### Version of Telegram Desktop

4.11.8

### Installation source

Static binary from official website

**Comment by SpCoGov** [comment]
I also encountered the same bug, have you solved it?

**Comment by wxhML** [comment]
I have the same problem ,Have you solved it already?
![Uploading 3.png…]()

**Comment by wxhML** [comment]
> Cannot open include file: 'vpx/vp8cx.h': No such file or directory

who help me ?

**Comment by SpCoGov** [comment]
Sorry, I read the wrong issue

**Comment by SpCoGov** [comment]
> > Cannot open include file: 'vpx/vp8cx.h': No such file or directory
> 
> who help me ?


1.     Run tdesktop\Telegram\build\prepare\win.bat in x64 Native Tools Command Prompt for VS 2022.bat
2.     When building to libvpx, you may get an error like you did. Don’t worry, see the next step.
3.     Open vpx.sln (should be called this) in BuildPath\Libraries(may have win64, depending)\libvpx and build it
4.     Run tdesktop\Telegram\build\prepare\win.bat again, and an error will still be reported in libvpx. At this time, press s to skip to continue building the subsequent lib
5.     When building to tg_owt, an error will still be reported: some file in the vpx directory is missing. At this time, you need to open the libvpx folder, copy the vpx folder inside, and then run tdesktop\Telegram\build\prepare\win.bat again, and press r when you get to tg_owt. It will delete all the files in the tg_owt directory. After deleting, you can put the copied vpx folder in it.
6.     Then follow the Build instructions to start Build the project
7.     When you Select Telegram project and press Build > Build Telegram (Debug and Release configurations), it will report an error that a library in the local directory is missing. You can just put the result of the second step of the build in the directory it mentioned.

**Comment by SpCoGov** [comment]
> > Cannot open include file: 'vpx/vp8cx.h': No such file or directory
> 
> who help me ?

1. Run tdesktop\Telegram\build\prepare\win.bat in x64 Native Tools Command Prompt for VS 2022.bat
2. When building to libvpx, you may get an error like you did. Don’t worry, see the next step.
3. Open vpx.sln (should be called this) in BuildPath\Libraries(may have win64, depending)\libvpx and build it
4. Run tdesktop\Telegram\build\prepare\win.bat again, and an error will still be reported in libvpx. At this time, press s to skip to continue building the subsequent lib
5. When building to tg_owt, an error will still be reported: some file in the vpx directory is missing. At this time, you need to open the libvpx folder, copy the vpx folder inside, and then run tdesktop\Telegram\build\prepare\win.bat again, and press r when you get to tg_owt. It will delete all the files in the tg_owt directory. After deleting, you can put the copied vpx folder in it.
6. Then follow the Build instructions to start Build the project
7. When you Select Telegram project and press Build > Build Telegram (Debug and Release configurations), it will report an error that a library in the local directory is missing. You can just put the result of the second step of the build in the directory it mentioned.

**Comment by SpCoGov** [comment]
#26012

**Comment by wxhML** [comment]
> > > Cannot open include file: 'vpx/vp8cx.h': No such file or directory
> > 
> > 
> > who help me ?
> 
> 1. Run tdesktop\Telegram\build\prepare\win.bat in x64 Native Tools Command Prompt for VS 2022.bat
> 2. When building to libvpx, you may get an error like you did. Don’t worry, see the next step.
> 3. Open vpx.sln (should be called this) in BuildPath\Libraries(may have win64, depending)\libvpx and build it
> 4. Run tdesktop\Telegram\build\prepare\win.bat again, and an error will still be reported in libvpx. At this time, press s to skip to continue building the subsequent lib
> 5. When building to tg_owt, an error will still be reported: some file in the vpx directory is missing. At this time, you need to open the libvpx folder, copy the vpx folder inside, and then run tdesktop\Telegram\build\prepare\win.bat again, and press r when you get to tg_owt. It will delete all the files in the tg_owt directory. After deleting, you can put the copied vpx folder in it.
> 6. Then follow the Build instructions to start Build the project
> 7. When you Select Telegram project and press Build > Build Telegram (Debug and Release configurations), it will report an error that a library in the local directory is missing. You can just put the result of the second step of the build in the directory it mentioned.

I have do this ,copy libvpx source code ，but display new problem

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/26012#issuecomment-1879075256

**Comment by wxhML** [comment]
![3](https://github.com/telegramdesktop/tdesktop/assets/18493148/f62b0218-4f57-4106-9792-aeaf06d8f15f)

**Comment by wxhML** [comment]
![3](https://github.com/telegramdesktop/tdesktop/assets/18493148/8b42a76e-baad-493f-bcfd-a204a5252ab6)

**Comment by wxhML** [comment]
> > > > Cannot open include file: 'vpx/vp8cx.h': No such file or directory
> > > 
> > > 
> > > who help me ?
> > 
> > 
> > 
> > 1. Run tdesktop\Telegram\build\prepare\win.bat in x64 Native Tools Command Prompt for VS 2022.bat
> > 2. When building to libvpx, you may get an error like you did. Don’t worry, see the next step.
> > 3. Open vpx.sln (should be called this) in BuildPath\Libraries(may have win64, depending)\libvpx and build it
> > 4. Run tdesktop\Telegram\build\prepare\win.bat again, and an error will still be reported in libvpx. At this time, press s to skip to continue building the subsequent lib
> > 5. When building to tg_owt, an error will still be reported: some file in the vpx directory is missing. At this time, you need to open the libvpx folder, copy the vpx folder inside, and then run tdesktop\Telegram\build\prepare\win.bat again, and press r when you get to tg_owt. It will delete all the files in the tg_owt directory. After deleting, you can put the copied vpx folder in it.
> > 6. Then follow the Build instructions to start Build the project
> > 7. When you Select Telegram project and press Build > Build Telegram (Debug and Release configurations), it will report an error that a library in the local directory is missing. You can just put the result of the second step of the build in the directory it mentioned.
> 
> I have do this ,copy libvpx source code ，but display new problem

I have followed this method ,but the same issue displaye 
![image](https://github.com/telegramdesktop/tdesktop/assets/18493148/f7cbd967-f593-4c14-a0b4-c13c0c8e389c)
![image](https://github.com/telegramdesktop/tdesktop/assets/18493148/eb888c99-be58-4a31-9f8f-eb4495678017)
