### ISSUE TITLE
Telegram will treat “in”, "not" in python error exception as keyword

### ISSUE THREAD

**Issue by LaoshuBaby** [telegramdesktop/tdesktop#27173]
### Steps to reproduce

Send this part of code

```python
  File "C:\Environment\Python311\Lib\site-packages\internetarchive\item.py", line 1119, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading BV1Jz4y1P7jY_p1-弹幕.ass to BiliBili-BV1Jz4y1P7jY_p1-Y2P4J1VB, The specified bucket is not valid. - Bucket names should be valid archive identifiers; try someting matching this regular expression: ^[a-zA-Z0-9][a-zA-Z0-9_.-]{4,100}$ (or, if you are making unusual identifiers, this user may lack the special permission to do so)
```

### Expected behaviour

the in and out in exception string shouldn't be highlighted

### Actual behaviour

![图片](https://github.com/telegramdesktop/tdesktop/assets/42690037/4af69566-20b7-4486-87b1-b2aabac26ff2)

### Operating system

Windows

### Version of Telegram Desktop

4.11.7 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
The highlighting rules are from https://github.com/PrismJS/prism
