### ISSUE TITLE
Preview text overflows its container in some cases

### ISSUE THREAD

**Issue by enchained** [telegramdesktop/tdesktop#27185]
### Steps to reproduce

1. Send this link https://asianews.network/internet-traffic-grows-sharply-in-nepal-after-tiktok-ban/

### Expected behaviour

Preview text should not overflow the parent container. It should always shorten with ... when needed instead.

### Actual behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/6181674/f07e23f1-43bc-4590-9616-1c84c8acc32d)

This specific text overflows the parent container by wrapping the last word "platform" to the next line:

> **[Asia News Network](https://asianews.network/internet-traffic-grows-sharply-in-nepal-after-tiktok-ban/)**
> **Internet traffic grows sharply in Nepal after TikTok ban**
> The growth suggests users are exploring loopholes to bypass national restrictions and access the platform.

### Operating system

Windows 11

### Version of Telegram Desktop

4.12.2

### Installation source

Static binary from official website

**Comment by enchained** [comment]
Encountered another example:

https://ifttt.com/telegram

![image](https://github.com/telegramdesktop/tdesktop/assets/6181674/12656774-2c6f-424c-95f1-3dfa0039bf3a)

> **[IFTTT](https://ifttt.com/telegram)**
> **Telegram Integrations - Connect Your Apps with IFTTT**
> Integrate Telegram with over 900 of your favorite apps & devices to unlock powerful automations on IFTTT. Get started today!

**Comment by BANOnotIT** [comment]
Another reproduction example: https://t.me/tg_msg_bugs/9

![image](https://github.com/telegramdesktop/tdesktop/assets/11363215/240b4fcd-0380-4f78-a8b1-78b6bef7b4f9)

Telegram 4.12.2, ubuntu 22.04, snap
