### ISSUE TITLE
Showing blocked accounts

### ISSUE THREAD

**Issue by HusanboyBayern** [telegramdesktop/tdesktop#2718]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by stek29** [comment]
I wonder why is this still open.
Or why is this still missing proper description.

**Comment by Aokromes** [comment]
#1724
