### ISSUE TITLE
Reactions statistics graph is rendered incorrectly.

### ISSUE THREAD

**Issue by weirdo-neutrino** [telegramdesktop/tdesktop#27187]
### Steps to reproduce

Open channel's statistics.
Scroll to "Reactions" graph.

The example of an incorrect graph:
![image](https://github.com/telegramdesktop/tdesktop/assets/55913074/cb47f950-7092-43e1-afc7-dee4792df35c)

### Expected behaviour

Graph line hitting 0.

### Actual behaviour

There are 0 "Negative" reactions. But the graph line does not touches 0. It goes from one non-zero value on the left to another on the right.

### Operating system

ArchLinux x86_64, Xfce 4.18

### Version of Telegram Desktop

4.12.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Can you provide a channel username? You can send it to https://t.me/preston

**Comment by weirdo-neutrino** [comment]
More info on behaviour.

![Screenshot_2023-12-11_14-08-42](https://github.com/telegramdesktop/tdesktop/assets/55913074/1e273ad1-3722-4133-8a56-1ef645bb6c5c)
![Screenshot_2023-12-11_14-08-54](https://github.com/telegramdesktop/tdesktop/assets/55913074/50afee10-4fd0-4d22-89ca-3565a776ae6a)

When last values are zero and before any non-zero values are added, graph line is not drawn at all.

**Comment by weirdo-neutrino** [comment]
Checked the graph. It is fixed now. v4.13.1

![Screenshot_2024-01-02_21-24-36](https://github.com/telegramdesktop/tdesktop/assets/55913074/9bbad8a6-0d47-4eb7-8c53-06395828ea94)

This issue can be closed.

**Comment by weirdo-neutrino** [comment]
Checked graph today. The bug is fixed. v4.13.1

![Screenshot_2024-01-02_21-24-36](https://github.com/telegramdesktop/tdesktop/assets/55913074/ad7f1f2d-691b-44f7-9350-e99d5f0ba136)

This issue can be closed.
