### ISSUE TITLE
Transparent Images Background - Aesthetic Issue

### ISSUE THREAD

**Issue by dement6d** [telegramdesktop/tdesktop#27181]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Transparent background on transparent images

### Describe alternatives you've considered

.

### Additional context

I would like the images to have transparent backgrounds like how it appears on Discord:
![image](https://github.com/telegramdesktop/tdesktop/assets/93228501/4e023bf3-c25a-4c5a-bc95-56759a6786a1)

**Comment by ilya-fedin** [comment]
Use webp image format for that

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
