### ISSUE TITLE
When opening a group, the last updated topic is opened instead of letting the user choose what topic read (like prev. version)

### ISSUE THREAD

**Issue by gerardbosch** [telegramdesktop/tdesktop#27188]
### Steps to reproduce

1. Click on a group that has topics

### Expected behaviour

1. The topic list expands and no chat is opened yet
2. The user see the list of topics with the new message counter
3. The user decides which topic wants to open to read messages (if they decide to read any at all)
4. The user clicks on the topic that wants to start reading messages

### Actual behaviour

On the release of `v4.12.2`, the behavior when opening groups that has topics enabled has changed: _It seems that now the last **topic** is **automatically opened**_.

This is very inconvenient as the user may not want to read that topic in particular or just wants to see how many new messages are in any topic without even opening them, so the message counter still holds.

**Expected** (the same than previous version and the Android app)
1. The user click on a group
2. The user is presented with the list of topics on that group (no topic is opened)
3. The user decides what to read or whether go back without opening any message.

### Operating system

Linux Ubuntu 23.10

### Version of Telegram Desktop

4.12.2

### Installation source

Snap

**Comment by gerardbosch** [comment]
Telegram Web (`a` and `k` versions) works fine. Android app also OK.

Please, could you revert to the previous behavior on the Telegram Desktop? It's frustrating to open a group, and get a random topic opened unintentionally. Thank you!

**Comment by john-preston** [comment]
It opens the last updated topic as well as the topics list to be able to choose any other topic. So you need the same amount of clicks for opening any topic and the last updated one you just get without clicks at all.

**Comment by gerardbosch** [comment]
> It opens the last updated topic as well as the topics list to be able to choose any other topic. So you need the same amount of clicks for opening any topic and the last updated one you just get without clicks at all.

Hi @john-preston!

Yes, but the thing is that I don't want to open the _last updated topic_, as this changes the unread messages counter and the read pointer.

I would like that the experience would be back consistent to the Web version like the previous Desktop version.

Defaulting to the last updated topic has the following side-effects:

- **You lose the unread pointer in case you were not interested on reading that topic**. This is very probable if  (a) you just want to check how many new messages; (b) if you're in a group with lots topics and you want to access to a specific topic, not the last updated; (c) if you just want to access the group to revisit an old conversation in another topic.

- **The unread message counter gets altered despite you were not interested to check that last updated topic.**


This are the main pain points by which I found the update not ergonomic —I would value more to be able to take the decision on what to open over doing an extra click. The thing is that in my case, I would personally want to chose which topic to open, not a default decision.

Another option could be to make it configurable with a toggle. What do you think about everything?


Cheers!

**Comment by gerardbosch** [comment]
Hi @john-preston, do you think there's any chance to go back to the previous behavior, or make it configurable?
Thank you!

**Comment by gerardbosch** [comment]
I'm on v5.0.2 now and I have realized that the behavior has been rolled back to the old behavior and is back consistent with other platforms.

So if you confirm it, this issue can be closed.

**Comment by john-preston** [comment]
Yup, I've rolled it back.
