### ISSUE TITLE
show schedule message in group topic on telegram desktop for windows

### ISSUE THREAD

**Issue by moooza** [telegramdesktop/tdesktop#27182]
### Steps to reproduce

schedule message not show in group topics on telegram desktop for windows

### Expected behaviour

show calendar icon in topics for view schedule message

### Actual behaviour

you can see schedule message in group topics on mobile app (android) but you can't see on telegram desktop (windows)

### Operating system

windows 11

### Version of Telegram Desktop

4.12.2 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
duplicate.
