### ISSUE TITLE
Can't open links on linux

### ISSUE THREAD

**Issue by pikodd** [telegramdesktop/tdesktop#27198]
### Steps to reproduce

+ Start telegram-desktop
+ go to chat or channel and find a link
+ try to open it by clicking on it

### Expected behaviour

Link opens in browser correctly

### Actual behaviour

Tab in browser opens with `http://target_uri/` as a hostname
I've tried chromium, firefox and librewolf - result is always the same.

### Operating system

Artix Linux, DWM

### Version of Telegram Desktop

4.12.2-1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
I bet the problem is in your system's xdg-open

**Comment by pikodd** [comment]
Yep, my fault, typo in xdg-open. Thanks!
