### ISSUE TITLE
Option to prevent app from running in background

### ISSUE THREAD

**Issue by ExposedCat** [telegramdesktop/tdesktop#27190]
### Is your feature request related to a problem?

Currently Telegram is always running in the background. Using system hotkeys (or close button) is much more convenient than tray>quit

### Describe the solution you'd like

Add a toggle to settings to control whether Telegram will minimize to tray or quit on close.

### Describe alternatives you've considered

none

### Additional context

The feature will be especially great to have on systems without tray (e.g. GNOME without extensions)

**Comment by Aokromes** [comment]
disable show tray icon.

**Comment by ilya-fedin** [comment]
Set sane man's titlebar settings and it won't stay in background
`gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'`
