### ISSUE TITLE
Export chat does not currently include content of buttons 

### ISSUE THREAD

**Issue by ckormylo** [telegramdesktop/tdesktop#27195]
### Is your feature request related to a problem?

Let's say I wanted to export a list of proxy links provided in the Proxy MTProto Telegram Channel: t.me/proxymtproto. The URL for these proxies are contained in buttons as shown below: 

![image](https://github.com/telegramdesktop/tdesktop/assets/143522390/e9ce8833-de93-4f45-a9e9-9c51da3353d9)

When exporting the data in the chat, even if all options are selected, as shown below, the content of the buttons is not exported with it. 

![image](https://github.com/telegramdesktop/tdesktop/assets/143522390/4c794e64-0af1-49d1-8a83-a8b1f86a9f8a)

The results provide an HTML document with the content of the messages themselves but not anything related to the button content (where the URL is contained). 

![image](https://github.com/telegramdesktop/tdesktop/assets/143522390/e2ad8699-4ad7-4868-bd89-0ab1a9e39826)

### Describe the solution you'd like

I would love the ability to export the content of buttons used in channels. 

### Describe alternatives you've considered

I have made sure to check every option available for the chat export. I have also attempted to export the data in both of the available output formats. 

![image](https://github.com/telegramdesktop/tdesktop/assets/143522390/4f5125aa-c851-496c-8347-f48f37de2cd3)

I am unaware of any other alternatives.

**Comment by Aokromes** [comment]
idk if it's enhancement or bug, but i confirm we cannot export that content.

**Comment by Aokromes** [comment]
btw, can you post your button at 
https://t.me/tdesktopbetatest on that way preston can see it?

**Comment by 23rd** [comment]
Should be better now for JSON export.

**Comment by Aokromes** [comment]
indeed, now json gives links for those, what about html ones? :)

**Comment by 23rd** [comment]
Should be better now for HTML export.

**Comment by Aokromes** [comment]
it looks good, for me this ticket can be closed.@ckormylo
