### ISSUE TITLE
Message filtering in groups/channels

### ISSUE THREAD

**Issue by isopropil** [telegramdesktop/tdesktop#27192]
### Is your feature request related to a problem?

Spam trash in groups and channels - is a really big problem

### Describe the solution you'd like

Is it possible to make a message filtering by stop words? A tons of spam trash is really tire.

### Describe alternatives you've considered

It`s a simple solution, but really helpful.

**Comment by Aokromes** [comment]
enable agresive antispam.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
