### ISSUE TITLE
Build example for GYP/CMake  is incomplete 

### ISSUE THREAD

**Issue by blackdev1l** [telegramdesktop/tdesktop#2719]
I've followed all the steps and i got this error: 

```
[  4%] Building CXX object CMakeFiles/codegen_style.dir/obj/gen/codegen_style/moc/moc_structure_types.o
make[2]: *** No rule to make target `/usr/lib/libicutu.a', needed by `codegen_style'.  Stop.
make[1]: *** [CMakeFiles/codegen_style.dir/all] Error 2
make: *** [all] Error 2
```

Apparently  libicu-dev doesan't install libicutu.a dep for codegen_style,
 system is ubuntu (vagrant box ubuntu/trusty64)
### Steps to reproduce
1.  Follow [this](https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-cmake.md) 
2. go to `release` or `debug` folder and lunch `make`
3. ????? 
4. error

### Expected behaviour
Should compile telegram

### Actual behaviour
```
[  4%] Building CXX object CMakeFiles/codegen_style.dir/obj/gen/codegen_style/moc/moc_structure_types.o
make[2]: *** No rule to make target `/usr/lib/libicutu.a', needed by `codegen_style'.  Stop.
make[1]: *** [CMakeFiles/codegen_style.dir/all] Error 2
make: *** [all] Error 2
```

### Configuration
**Operating system:** Ubuntu 

**Version of Telegram Desktop:** Latest

### Logs
[  4%] Building CXX object CMakeFiles/codegen_style.dir/obj/gen/codegen_style/moc/moc_structure_types.o
make[2]: *** No rule to make target `/usr/lib/libicutu.a', needed by `codegen_style'.  Stop.
make[1]: *** [CMakeFiles/codegen_style.dir/all] Error 2
make: *** [all] Error 2

**Comment by stek29** [comment]
It should install `/usr/lib/x86_64-linux-gnu/libicutu.a` according to [filelist](http://packages.ubuntu.com/trusty/amd64/libicu-dev/filelist)...
Maybe GYP/CMake doesn't add `/usr/lib/x86_64-linux-gnu` to library search path...

**Comment by slavablind91** [comment]
Try to find libicu*.a files in /usr/local/lib/ and link them to /usr/lib/ folder. It helps for me

**Comment by CzBiX** [comment]
try apply this patch:

```diff
diff --git a/Telegram/gyp/qt.gypi b/Telegram/gyp/qt.gypi
index a8adbaa..6501950 100644
--- a/Telegram/gyp/qt.gypi
+++ b/Telegram/gyp/qt.gypi
@@ -132,7 +132,7 @@
     'linux_path_xkbcommon%': '/usr/local',
     'linux_lib_ssl%': '/usr/local/ssl/lib/libssl.a',
     'linux_lib_crypto%': '/usr/local/ssl/lib/libcrypto.a',
-    'linux_lib_icu%': '/usr/lib/libicutu.a /usr/lib/libicui18n.a /usr/lib/libicuuc.a /usr/lib/libicudata.a',
+    'linux_lib_icu%': 'icuuc icutu icui18n',
   },
 
   'configurations': {
```

**Comment by stek29** [comment]
@CzBiX Someone should test this and make a PR if it works.

**Comment by xvitaly** [comment]
> Maybe @xvitaly can help.

All this static libaries must be dropped. We did this in Fedora. All other distributions do the same.

**Comment by stek29** [comment]
@xvitaly How can one find build files for Fedora? I'm not familiar with it's package management system :(

**Comment by xvitaly** [comment]
> How can one find build files for Fedora? I'm not familiar with it's package management system :(

https://github.com/xvitaly/tgbuild
