### ISSUE TITLE
[Android App] Wrong file is downloaded when an old one with the same name exists in the same conversation

### ISSUE THREAD

**Issue by josep11** [telegramdesktop/tdesktop#27206]
### Steps to reproduce

There is no way to bug report for android, so I place it here.
1. Start a chat with someone and **send a file named "pec.docx"** with content: "1st".
2. After a while (or probably immediately) **send another file with the same exact name** "pec.docx" but different content: "2nd".
3. From the other chat, try to download the second one and actually the first one will be downloaded.

Here is the bug: https://github.com/telegramdesktop/tdesktop/assets/5558911/608dc51c-c898-4d57-85d8-e7ab132fb0a6

### Expected behaviour

When we download the file, the second one gets downloaded instead of the first one.
However, when we just open the file, the appropriate one is shown.

### Actual behaviour

Regardless if we just tap the second file or we download it, we should get the same result. Displaying/Downloading the second file.

### Operating system

Android 11

### Version of Telegram Desktop

Telegram for Android 10.3.2

### Installation source

Mac App Store

**Comment by Aokromes** [comment]
use https://bugs.telegram.org for android.
