### ISSUE TITLE
Ability to move the chat list to the right

### ISSUE THREAD

**Issue by roj1512** [telegramdesktop/tdesktop#27201]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

I’d like to be able to move the chat list to the right. This helps me move my eyes less if I want to resize it, and be able to keep focus on the more important stuff.

### Describe alternatives you've considered

N/A

**Comment by ilya-fedin** [comment]
#242

**Comment by roj1512** [comment]
Closing in favor of #242.
