### ISSUE TITLE
[Bug] [Linux] Group pinned message bug

### ISSUE THREAD

**Issue by Alkaris** [telegramdesktop/tdesktop#2720]
### Steps to reproduce
1. Have an already pinned old message for group chats.
2. then later click to view it again.
3. 

### Expected behaviour
Tell us what should happen

Should be able to view the pinned message at any time when clicked on the banner for it.

### Actual behaviour
Tell us what happens instead

Clicking on the pinned group message takes you to the pinned massage, and the pinned message suddenly disappears from view after clicking on it.

### Configuration
**Operating system:**

Linux Mint 18 (Cinnamon) 64-bit

**Version of Telegram Desktop:**
v0.10.19

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

[log_11_15.txt](https://github.com/telegramdesktop/tdesktop/files/659867/log_11_15.txt)
[REDACTED]
[tcp_11_15.txt](https://github.com/telegramdesktop/tdesktop/files/659868/tcp_11_15.txt)

**Comment by stek29** [comment]
@Alkaris Including `mtp_*` logs is not a good idea, they have a lot of sensitive information in them.
Also, could you check if it's still happening with 0.10.20?

**Comment by esmaeilpour** [comment]
@Alkaris all messages suddenly disappears from view for me !

**Comment by stek29** [comment]
Does this still happen?

**Comment by Alkaris** [comment]
It appears to be fixed for the time being.
