### ISSUE TITLE
<Alt+num> shortcut keys for direct switching between chats

### ISSUE THREAD

**Issue by leonerd** [telegramdesktop/tdesktop#27202]
### Is your feature request related to a problem?

Keyboard navigation between chats without using the mouse.

### Describe the solution you'd like

Pressing <Alt+1> should switch to the first chat tab; <Alt+2> to the second, and so on. This is similar to most other tab-based applications (web browsers, code editors, other chat clients, etc...) so there's strong muscle memory and existing familiarity in users.

Given that chats move around and change order depending most recent activity, I admit this might be a bit hard to use; but at least since the topmost "pinned" chats are in a stable order, these shortcut keys could be useful to switch to those, even if it doesn't do the rest of the dynamic ones after.

### Describe alternatives you've considered

Already the <Alt+up> / <Alt+down> or <Ctrl+PageUp> / <Ctrl+PageDown> keys switch up and down between adjacent chats, so this feels like a reasonable extension. While you can use keyboard navigation to move relatively, it's hard to jump back to the beginning this way.

### Additional context

Currently the <Alt+num> shortcuts are not considered special; the Alt modifier is ignored and it just inserts the numbers 1, 2, etc.. into the text buffer.

**Comment by khalid-hussain** [comment]
If I'm not mistaken, this already exists?

I'm on version 4.12.2. I have chat folders. `Ctrl + <num>` navigates through the folders. `Ctrl + Tab` and `Ctrl + Shift + Tab` navigates through the chats like tabs in a browser.
