### ISSUE TITLE
Allowing to turn off notification on mobile app when desktop app is executing.

### ISSUE THREAD

**Issue by oakmegaeddie** [telegramdesktop/tdesktop#27213]
### Is your feature request related to a problem?

Even when the desktop app is running, notifications still pop up on the phone, causing continuous vibrations and alerts. However, all this information has already been seen in the desktop app's notifications.

The appearance of the same notifications on different devices disrupts concentration because users are unsure about the content of the notifications on their phones. Upon checking, they realize it's information they were already aware of, leading to a complete waste of the user's time.

### Describe the solution you'd like

Please provide a setting to determine whether to send notifications to the phone while the desktop app is running. The notifications can be resumed only if there is no OS activity for more than 3 minutes.

### Describe alternatives you've considered

Do not send any notifications to the phone while the desktop app is running.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
