### ISSUE TITLE
[URGENT]Telegram not responding to any type of support requests

### ISSUE THREAD

**Issue by Frosty85** [telegramdesktop/tdesktop#27212]
### Steps to reproduce

So, I have been trying to reach out to Telegram support through different modes, I have tried, tried volunteer support within the app, and tried to reach out via Twitter and wrote through telegram.org/support but never received a single response from Telegram.
Here's the issue now, yesterday Telegram banned my account due to spam.
I lost access to my phone number, I don't know if I can renew my contract with a mobile provider. How can I get my account back? I have proof that it is real to my account. I emailed from [dev.osm1@protonmail.com](mailto:dev.osm1@protonmail.com), I just need to replace phone numbers in my Telegram account.

### Expected behaviour

I just need to log in again, with my new phone number.

### Actual behaviour

It doesnt let me in

### Operating system

windows

### Version of Telegram Desktop

10.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
this is telegram desktop bug tracker not account support place.
