### ISSUE TITLE
Link Preview doesn't wrap correctly

### ISSUE THREAD

**Issue by xtianpu** [telegramdesktop/tdesktop#27216]
### Steps to reproduce

1. Type x.com/bambeley and send it to anybody.

### Expected behaviour

Should be wrapped correctly inside preview box

### Actual behaviour

Link preview text is out of preview box boundaries.

![image](https://github.com/telegramdesktop/tdesktop/assets/8172235/9b6a0f29-64c6-40fe-82a2-8bea28551787)

### Operating system

Windows 11

### Version of Telegram Desktop

4.12.2 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#27185
