### ISSUE TITLE
Multiple window for topics

### ISSUE THREAD

**Issue by nero08** [telegramdesktop/tdesktop#27214]
### Is your feature request related to a problem?

Cannot show multiple topics via multiple window like group functionnality (right click => open in new window)

### Describe the solution you'd like

The same way you can CTRL click a chat and a new window will popup, we could do the same for a single topic in a group

### Describe alternatives you've considered

Execute multiple instance of telegram maybe

**Comment by ilya-fedin** [comment]
#26020
