### ISSUE TITLE
"Share my phone number" being checked by default seems like a huge privacy "gotcha"

### ISSUE THREAD

**Issue by realityexists** [telegramdesktop/tdesktop#27219]
### Steps to reproduce

1. (Optional) Set privacy settings to share phone number with nobody
2. Find any other user and bring up their User Info dialog
3. Click "Add to contacts"

### Expected behaviour

"Share my phone number" checkbox is unchecked by default

### Actual behaviour

"Share my phone number" checkbox is checked by default

### Operating system

Windows 7 x64

### Version of Telegram Desktop

4.12.2 x64

### Installation source

Static binary from official website

**Comment by realityexists** [comment]
It's very easy to forget to uncheck that checkbox, so this is a really easy way to unintentionally share your phone number with others. Surely the safer option would be to have that option unchecked (regardless of phone number privacy settings)? If the user wants to share their phone number with all contacts by default they can configure the "Who can see my phone number" setting to do that.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by realityexists** [comment]
Is this platform-wide, though? I assumed the default state of that checkbox is up to the client. Is it something the server tells it to do?

**Comment by Aokromes** [comment]
no, it's the same on every application.
