### ISSUE TITLE
Links without a domain name are not clickable

### ISSUE THREAD

**Issue by tonypowa** [telegramdesktop/tdesktop#27217]
### Steps to reproduce

Hi team 

First of all, apologies if this issue does not belong to this repo. Although, I believe the problem is actually present in all Telegram platforms 

Links in Telegram aren't clickable unless they include a top-level domain (e.g. `.com`) .

My use case is that I can't click on the links present in alert notifications sent from a local source, such as Raspberry pi via `http://localhost:3000/` (which does not use a domain name)

1. To repro simply type in Telegram any URL that does not contain a domain name. E.g. http://localhost:3000/
2. See that the message will render as plain text instead as a hyperlink

### Expected behaviour

http://localhost:3000/ would render just like any other link such as http://google.com/ despite it uses a separator `:` and a port, instead of a top-level domain such as `.com`
(notice that "localhost:3000" does render here in GitHub as a link)

### Actual behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/45235678/57404aed-ad02-4d20-b9ac-9bcfed23f6e9)

### Operating system

Windows 10

### Version of Telegram Desktop

n/a

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Yes, you have chosen not the right issue, you should have choose 'Platform-wide issue' type when creating the issue

**Comment by tonypowa** [comment]
thanks @ilya-fedin  I will close this one and open another with that type .
