### ISSUE TITLE
payment checkout on desktop get stucks

### ISSUE THREAD

**Issue by vincenzopalazzo** [telegramdesktop/tdesktop#27224]
### Steps to reproduce

Try to update to premium from the desktop app

### Expected behaviour

The checkout windows will load correctly

### Actual behaviour

Black screen

![Selection_010](https://github.com/telegramdesktop/tdesktop/assets/17150045/e1dd9982-1334-494f-8bb2-734e0c479c49)

### Operating system

x86 arch linux

### Version of Telegram Desktop

4.12.2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Provide the log.txt as instructed by the issue template + terminal output

**Comment by vincenzopalazzo** [comment]
>Provide the log.txt as instructed by the issue template + terminal output

where I will find the log.txt?

**Comment by ilya-fedin** [comment]
This is described when creating issue

**Comment by vincenzopalazzo** [comment]
When I was trying to reproduce it worked, ok but I am attach the log anyway is you find something strange

[log.txt](https://drive.proton.me/urls/C39NT7YV80#MXn4cVnB3GKg)

**Comment by ilya-fedin** [comment]
I can't open the URL

**Comment by vincenzopalazzo** [comment]
Changed the link to https://pastebin.com/STvht7JF
