### ISSUE TITLE
Update button ovelaps player button

### ISSUE THREAD

**Issue by ckesc** [telegramdesktop/tdesktop#2722]
<img width="105" alt="bug" src="https://cloud.githubusercontent.com/assets/2548610/21310546/e84cffa6-c5f3-11e6-8e1f-5a0c5b168108.png">

 
### Steps to reproduce
1. Get an update for app
2. Listen music
3. Look at top-right corner

### Expected behaviour
Label is not overlapping with player button

### Actual behaviour
"Update" and player button is overlapping

### Configuration
Mac OSX 10.11.6
Telegram Desktop 0.10.19 alpha

**Comment by john-preston** [comment]
@ckesc Thanks! This will be fixed (redesigned) in the future versions.

**Comment by Aokromes** [comment]
Fixed on 0.10.21 :)
