### ISSUE TITLE
Context menu go out the screen

### ISSUE THREAD

**Issue by brain2xml** [telegramdesktop/tdesktop#27227]
### Steps to reproduce

Right click in chat

### Expected behaviour

if right click in bottom of the screen, context menu must open above  

### Actual behaviour

context menu must open out the screen
![Снимок экрана от 2023-12-15 06-13-58](https://github.com/telegramdesktop/tdesktop/assets/132535/9edfe237-c1bd-4914-9fc1-7f2fba25ce16)
![Снимок экрана от 2023-12-15 06-13-34](https://github.com/telegramdesktop/tdesktop/assets/132535/def4d571-a8c1-4255-8af2-09a2917b75ba)

### Operating system

Debian 12

### Version of Telegram Desktop

4.6.5

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Seems to be ok? The first screenshot has entire menu on screen and on the second screenshot it doesn't seem to be an edge of a screen (or provide a fullscreen screenshot where it would be clearly seen)

**Comment by ilya-fedin** [comment]
> 4.6.5

Never mind, this version of tdesktop is not the latest and so is unsupported. You can't report issues.

**Comment by brain2xml** [comment]
This version I installed from debian store. Now I deleted it and installed from snap, everything no works fine
