### ISSUE TITLE
Make LocationClickHandler configurable 

### ISSUE THREAD

**Issue by proofy** [telegramdesktop/tdesktop#27221]
### Is your feature request related to a problem?

google.com is hard coded. So if there is a problem (e.g. in some countries) to access this, the location is not usable.
Or in my case, google maps is not good enough and I want to use Openstreetmaps 

### Describe the solution you'd like

In the preferences I can choose between some location handlers 

### Describe alternatives you've considered

In the expert configuration I can set the URL of the location handler by my self.

### Additional context

In my case the picture of the location comes from Openstreetmap. Why not the link?

**Comment by ilya-fedin** [comment]
#6789

**Comment by proofy** [comment]
OT: Has github something changed in the search, so I haven't found #6789 ?
