### ISSUE TITLE
Crash when resizing window

### ISSUE THREAD

**Issue by csuvbakka** [telegramdesktop/tdesktop#27223]
### Steps to reproduce

1. Start Telegram Desktop
2. Resize window vertically

Only vertical resize causes the app to crash, horizontal works fine.

It seems like no crashlog is generated, `Opened 'C:/telegram/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 0`
Crash reporter works when app is crashed using the `crashplease` cheat code.

### Expected behaviour

Window should be resized

### Actual behaviour

Telegram Desktop crashes

### Operating system

Windows 10

### Version of Telegram Desktop

4.12.2 x64

### Installation source

Static binary from official website

### Logs

```shell
https://pastebin.pl/view/1aa8597c
```

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by csuvbakka** [comment]
Beta is enabled, how do I get the crash ID?

When I start Telegram after crash, crash-report window doesn't appear.
`tdata\working` and `tdata\dumps` is empty

**Comment by csuvbakka** [comment]
I've found the solution.

I am developing a Qt app on this machine and earlier today I've set the `QT_FATAL_WARNINGS` environment variable to 1 for debugging purposes.

After removing the environment variable, Telegram works as expected.
