### ISSUE TITLE
Follow system frame theme

### ISSUE THREAD

**Issue by vovagorodok** [telegramdesktop/tdesktop#27229]
### Is your feature request related to a problem?

N/A

### Describe the solution you'd like

Follow system themes by default like Adwaita in order to have consistency of system UI

### Describe alternatives you've considered

N/A

**Comment by ilya-fedin** [comment]
Why do you have 'by default' in the title? There's no such option at all

**Comment by vovagorodok** [comment]
Maybe not by default, but will be nice to have some option (default for me is better, but for others it may differ). As I see i `Advanced` options is `Use Qt window frame`, but it does not follow default (in my case Adwaita) system frame

**Comment by ilya-fedin** [comment]
Is your issue about window frame exactly? If yes, it sadly couldn't be implemented, Qt is the underlying toolkit tdesktop is written on top of: as long as Qt doesn't support your theme, tdesktop can't as well.

**Comment by vovagorodok** [comment]
Thanks Ilya for fast answers. Lets narrow this issue to window frame. I'm not sure if it should be resolved on Qt or tdesktop side.
![Screenshot from 2023-12-18 17-48-29](https://github.com/telegramdesktop/tdesktop/assets/8137447/67855757-34f0-48a8-8579-8665a8d72e76)
Qt Creator (written on Qt) and Kate (wtitten on Qt and Kde) follows system frame (Adwaita) theme.
![image](https://github.com/telegramdesktop/tdesktop/assets/8137447/fd16aaa5-3013-4010-a5c8-0e74bd1b5c52)
In telegram I have different. Perhaps if Qt application is written in a custom material style it affects to system frame

**Comment by vovagorodok** [comment]
I'm using flatpak telegram version (Qt Creator and Kate are RPM), perhaps it can be issue. I'll check other flatpak Qt based apps

**Comment by ilya-fedin** [comment]
This means those applications are built upon older Qt (likely 5.x) that works via Xwayland. X11 always provides server-side decorations while on Wayland they're optional and GNOME uses its freedom to not to provide them so Qt uses its own client-side decorations that don't support gtk themes. You perhaps use some LTS distro given that your Qt is so old, you likely can get tdesktop from the repos that will use the same Qt version and behave the same way but it also will be that old.

**Comment by vovagorodok** [comment]
I'm on latest Fedora 39 with Qt6 an Wayland. Installed flatpak version of Qt Creator and It has same frame as telegram. Looks that flatpak has issue with forwarding system theme

**Comment by ilya-fedin** [comment]
As far as I'm aware Fedora (as all other distros) ship both Qt 6 and Qt 5 so Qt Creator could be built with Qt 5. KDE applications like Kate don't support Qt 6 at all yet (unless it's a beta version)

**Comment by vovagorodok** [comment]
Qt Creator uses Qt6 as I se:
![image](https://github.com/telegramdesktop/tdesktop/assets/8137447/c475cf6d-fc99-4821-9e06-ca5c1ff1e25a)

Checked additionally `Linux 64 bit: Binary`, doesn't follow frame theme like flatpak version

**Comment by vovagorodok** [comment]
Looks that it is Gnome and Flatpak theme consistency issue. Not telegram issue. Not sure if we can somehow resolve this issue in telegram side

**Comment by ilya-fedin** [comment]
> Qt Creator uses Qt6 as I se:

I would rather suggest to check whether it runs via Xwayland, maybe it forces running via X11

**Comment by vovagorodok** [comment]
`xlsclients` show only:
```
gsd-xsettings
ibus-x11
mutter-x11-frames
```
when QtCreator and telegram is opened

**Comment by ilya-fedin** [comment]
hmm, weird. Maybe it's some Fedora extension. Qt doesn't have support for gtk frames upstream.
