### ISSUE TITLE
Uploading speed on desktop throttled to about 1 MB/s

### ISSUE THREAD

**Issue by Skydev0h** [telegramdesktop/tdesktop#27236]
### Steps to reproduce

1. Upload a file using a desktop client
2. Observe the uploading speed
3. Upload a file using a mobile client on the same network
4. Compare the uploading speed of the desktop client to the speed of a mobile client on the same network

### Expected behaviour

The file should be uploaded at least with the speed obtained with the mobile client (using the same network as the PC).

https://github.com/telegramdesktop/tdesktop/assets/5331782/eb42d82f-1329-43ce-bad5-d1665da393b7

### Actual behaviour

The file is uploaded very slowly (about 1 MB/s). This is not different for premium or non-premium accounts (tested on premium).

https://github.com/telegramdesktop/tdesktop/assets/5331782/f3732d8f-65b0-4545-8828-577f155cd0f0

N.B. The download speed is not affected, it is very fast, as is expected. The upload speed is very slow.

### Operating system

Windows 11 23H2 (22631.2787)

### Version of Telegram Desktop

4.12.2 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
can't reproduce on windows 10.

**Comment by Skydev0h** [comment]
> can't reproduce on windows 10.

Indeed, I tested this on a Windows 10 VM and sometimes the upload speed is higher than 1 MB/s (but mainly it is about this, because the VM is pretty laggy).

But in Windows 11 it is steadily 1 MB/s for the whole file upload.

Also tried it on other 1 Gbit fiber optic uplink (switched to reserve) and on another reasonably powerful Win11 machine with another Premium account with no other accounts logged in - the results were the same.

I think the Internet uplink itself must be OK because the Android application uploads the file extremly fast.

**Comment by TBXin** [comment]
Windows 11 22H2 (22621.2861) same problem here.
TG Desktop upload speed is limited, but android app uploads at full speed of my IPS.

**Comment by rinrab** [comment]
The same was with me. I think that's because telegram servers was overload and working slow. It was slow on phone too.

**Comment by Skydev0h** [comment]
> The same was with me. I think, that's because telegram servers was overload and working slow. It was slow on phone too.

Most likely that's because your WiFi (if you are using it on both PC and Mobile) or ISP was slow, Telegram servers are pretty powerful.

The main idea is that a PC, wired with 1 GBit connection, is slower than a phone on a 5 GHz, but a WiFi, therefore, the PC must be at least as fast as the phone, if there is no some kind of throttling in the application.
