### ISSUE TITLE
Can't scan QR neither telephone number to load my profile in Ubuntu 23.10

### ISSUE THREAD

**Issue by carrizoja** [telegramdesktop/tdesktop#27230]
### Steps to reproduce

Hello,
I installed Telegram from Ubuntu App Center.
I opened Telegram App.
The sync windows appears.
The QR code didn't appear.
The SMS method didn't work.

![Screenshot from 2023-12-15 11-22-04](https://github.com/telegramdesktop/tdesktop/assets/58268794/c6ffc55b-d0a5-4126-a9e9-32c2fd54ac95)
![Screenshot from 2023-12-15 11-23-21](https://github.com/telegramdesktop/tdesktop/assets/58268794/a8747274-05c3-4776-b66d-b28479b5b874)

### Expected behaviour

The QR code should appear.
The SMS method SEND button should work.

### Actual behaviour

The QR code don't appear.
The SMS method don't work.

### Operating system

Ubuntu 23.10

### Version of Telegram Desktop

Telegram 4.12.2

### Installation source

Snap

**Comment by Shadow27374** [comment]
Hello,

I have exactly the same problem.

Ubuntu 23.10

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by carrizoja** [comment]
Good morning!
Thanks for your reply. I tested the App and it works fine! One final
question: where do you recommend to put the Telegram folder? I created an
"Application" folder inside my Ubuntu user profile.
Regards and have a nice day!

**Comment by carrizoja** [comment]
> plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

Thanks! it works well!

**Comment by foreignmeloman** [comment]
@Aokromes so what's wrong with the flatpak or snap version?
