### ISSUE TITLE
Allow closed topics to be archived

### ISSUE THREAD

**Issue by dmnyc** [telegramdesktop/tdesktop#27231]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

For group admins, I’d like a way to archive topics after closing them so they are not visible in the main topic list but only appear in an Archived section.

### Describe alternatives you've considered

Closing topics still leaves them visible in the topic list.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
