### ISSUE TITLE
Resume interrupted downloads

### ISSUE THREAD

**Issue by aerth** [telegramdesktop/tdesktop#27238]
### Is your feature request related to a problem?

After an interruption (or closing the program), unfinished downloads are (and will remain) unfinished with no indication that they are incomplete.

When attempting to download the media again, the file can only be replaced and started from the beginning. If the interruption happened while away from computer, there is no indicator that the downloads are unfinished (Because tgdesktop thinks the download is finished, the message's filesize is hidden and a play button is displayed instead)

### Describe the solution you'd like

When clicking the download button, we should check file size of downloaded media to resume from that index if possible (similar to pause/resume)

### Describe alternatives you've considered

User somehow manually identifies which are unfinished, remove those files and restart download :cry:

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/23977

**Comment by aerth** [comment]
@Aokromes afiak, cancelling removes the file (as it should). but, when download is interrupted, the file remains unfinished.
