### ISSUE TITLE
Round artifacts in message corners 

### ISSUE THREAD

**Issue by grandich** [telegramdesktop/tdesktop#27237]
### Steps to reproduce

- Windows 10 22h2 OS Build 19045.3803
- Intel UHD Graphics 630, driver version 27.20.100.8854
- Dell Monitor P2419H
- 1080 x 1920, Portrait (Flipped)

Strange white semicircle artifacts in message corners

When I move window to other monitor (different graphic card), it works ok.

### Expected behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/1310215/961779b0-ce6a-4566-8632-710ea8c7e808)

### Actual behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/1310215/4ad4ecc2-7461-45aa-afdb-b5276cd2b1e9)

### Operating system

Windows 10

### Version of Telegram Desktop

4.11.8 x64

### Installation source

Microsoft Store

**Comment by john-preston** [comment]
Do you have "Precise HiDPI" experimental option enabled in Settings > Advanced > Experimental Settings?

**Comment by grandich** [comment]
> Do you have "Precise HiDPI" experimental option enabled in Settings > Advanced > Experimental Settings?

No. Switching it on has no effect.

**Comment by grandich** [comment]
I figured out the problem arises only when choosing a Theme (any one except "No Theme")
![image](https://github.com/telegramdesktop/tdesktop/assets/1310215/7196b033-d2a5-4926-8af9-3e83c0e4e9c5)
