### ISSUE TITLE
Could not add user. please try again later

### ISSUE THREAD

**Issue by Kochibov** [telegramdesktop/tdesktop#27242]
### Steps to reproduce

Create group
Manage group
Administration
Add new admin
Select a user
Save
"Could not add user. please try again later"
Tried, Mobile, web, desktop，uninstall ，restart the computer

### Expected behaviour

Slove the issue，cannot add admin

### Actual behaviour

Create group
Manage group
Administration
Add new admin
Select a user
Save
"Could not add user. please try again later"
Tried, Mobile, web, desktop，uninstall ，restart the computer

### Operating system

Windows，IOS

### Version of Telegram Desktop

4.11.7 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
