### ISSUE TITLE
Snap on Xubuntu can't log in (via QR code nor phone number)

### ISSUE THREAD

**Issue by SnapperGee** [telegramdesktop/tdesktop#27248]
### Steps to reproduce

1. Install snap: `sudo snap install telegram-desktop`
2. Launch application.
3. Click "Start Messaging"

### Expected behaviour

A QR code should appear that can be used to log in or alternatively, "Or log in using your phone number" can be clicked and a phone number can be entered to log in.

### Actual behaviour

After clicking "Start Messaging" the QR code never loads (just hangs showing the loading circle with the instruction text below it) and when attempting to do the phone number option, after putting phone number in and clicking "Next", nothing happens.

### Operating system

Xubuntu 22.04

### Version of Telegram Desktop

4.12.2

### Installation source

Snap

**Comment by SnapperGee** [comment]
I already attempted uninstalling and reinstalling the snap as well as rebooting after installing it and the issue consistently happens 100% of the time.

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by SnapperGee** [comment]
> plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

Oh sorry, I forgot to mention I did do that and it did appear to function correctly. Well, the QR code loaded but I didn't login. I'm hoping to and would prefer to use the snap package if possible. Using the static version is totally a viable option, but if that's the permanent solution then support for the snap should officially be cut.

**Comment by angelcervera** [comment]
Same issue in a fresh Ubuntu 23.10 installation:
```
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
```
```
➜  ~ snap info telegram-desktop 
name:      telegram-desktop
summary:   Fast. Secure. Powerful.
publisher: Telegram FZ-LLC (telegram-desktop✓)
store-url: https://snapcraft.io/telegram-desktop
contact:   https://github.com/telegramdesktop/tdesktop/issues
license:   unset
description: |
...
...
...
commands:
  - telegram-desktop
snap-id:      jpdoHqMd90M39DdH2JSZbeQxipqHtwLo
tracking:     latest/stable
refresh-date: today at 09:14 GMT
channels:
  latest/stable:    4.12.2              2023-12-01 (5305) 434MB -
  latest/candidate: ↑                                           
  latest/beta:      ↑                                           
  latest/edge:      4.12.2-5-gfbe93b0af 2023-12-15 (5322) 433MB -
installed:          4.12.2                         (5305) 434MB -

```

**Comment by angelcervera** [comment]
```
➜  ~ telegram-desktop 
Gtk-Message: 16:41:29.485: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:41:29.486: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
[ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter

** (telegram-desktop:49279): WARNING **: 16:42:22.628: atk-bridge: get_device_events_reply: unknown signature
```

**Comment by makgiber1984** [comment]
Same problem with Linux Mint 21.2 Cinnamon, I've tried both the Snap and Faltpack versions, and in both it keeps going around without ever showing the QR. It also doesn't work by entering the phone number.... However, with the linux mint version of the system package, if it works properly...

**Comment by RomanRD** [comment]
Same problem with Ubuntu 18.04.2 LTS. Version is 4.14.3 from snap

**Comment by UrbanKeith** [comment]
Enabling the Waylang mode helped me. (Ubuntu 22.04 / Telegram snap 4.14.3)

To enable the Waylang mode you need to edit the gdm configuration. Run `sudo nano /etc/gdm3/custom.conf`, find the line  `#WaylandEnable=false` and replace it to `WaylandEnable=true`. Then you need to restart gdm `sudo systemctl restart gdm3`
Before logging into the user in the lower left corner (settings button) you need to select "Ubuntu on Waylang".

After these manipulations, the QR code in the application will work correctly

**Comment by SnapperGee** [comment]
> Enabling the Waylang mode helped me. (Ubuntu 22.04 / Telegram snap 4.14.3)
> 
> To enable the Waylang mode you need to edit the gdm configuration. Run `sudo nano /etc/gdm3/custom.conf`, find the line `#WaylandEnable=false` and replace it to `WaylandEnable=true`. Then you need to restart gdm `sudo systemctl restart gdm3` Before logging into the user in the lower left corner (settings button) you need to select "Ubuntu on Waylang".
> 
> After these manipulations, the QR code in the application will work correctly

Thanks for the suggestion, I appreciate it!

**Comment by SnapperGee** [comment]
Looks like the snap is working now after the last update so I'm going to close this for now. Thanks for everyone's feedback and input!

**Comment by Zotoff** [comment]
> Enabling the Waylang mode helped me. (Ubuntu 22.04 / Telegram snap 4.14.3)
> 
> To enable the Waylang mode you need to edit the gdm configuration. Run `sudo nano /etc/gdm3/custom.conf`, find the line `#WaylandEnable=false` and replace it to `WaylandEnable=true`. Then you need to restart gdm `sudo systemctl restart gdm3` Before logging into the user in the lower left corner (settings button) you need to select "Ubuntu on Waylang".
> 
> After these manipulations, the QR code in the application will work correctly

Thanks, man. It hepls

**Comment by nakutnyi** [comment]
This still happens to me with telegram-desktop 4.15.0 and 4.15.0-3-gec427ad45. Ubuntu 18.04.6

**Comment by plimut** [comment]
```
env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/telegram-desktop_telegram-desktop.desktop /snap/bin/telegram-desktop -- %u
Gtk-Message: 11:37:59.645: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Could not open network socket
[ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter

```
```
snap connections telegram-desktop
Interface              Plug                               Slot                            Notes
alsa                   telegram-desktop:alsa              -                               -
audio-playback         telegram-desktop:audio-playback    :audio-playback                 -
audio-record           telegram-desktop:audio-record      :audio-record                   -
camera                 telegram-desktop:camera            :camera                         -
content[gtk-3-themes]  telegram-desktop:gtk-3-themes      gtk-common-themes:gtk-3-themes  -
content[icon-themes]   telegram-desktop:icon-themes       gtk-common-themes:icon-themes   -
content[sound-themes]  telegram-desktop:sound-themes      gtk-common-themes:sound-themes  -
desktop                telegram-desktop:desktop           :desktop                        -
desktop-legacy         telegram-desktop:desktop-legacy    :desktop-legacy                 -
gsettings              telegram-desktop:gsettings         :gsettings                      -
hardware-observe       telegram-desktop:hardware-observe  :hardware-observe               -
home                   telegram-desktop:home              :home                           -
mpris                  -                                  telegram-desktop:mpris          -
network                telegram-desktop:network           :network                        -
network-bind           telegram-desktop:network-bind      :network-bind                   -
network-status         telegram-desktop:network-status    :network-status                 -
opengl                 telegram-desktop:opengl            :opengl                         -
removable-media        telegram-desktop:removable-media   -                               -
unity7                 telegram-desktop:unity7            :unity7                         -
wayland                telegram-desktop:wayland           :wayland                        -
x11                    telegram-desktop:x11               :x11                            -

```
QR code does not load, the application behaves as if there is no network connection.

```
cat /etc/*release*
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.3
DISTRIB_CODENAME=virginia
DISTRIB_DESCRIPTION="Linux Mint 21.3 Virginia"
NAME="Linux Mint"
VERSION="21.3 (Virginia)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.3"
VERSION_ID="21.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=virginia
UBUNTU_CODENAME=jammy

```

**Comment by ldt116** [comment]
Disabling OpenGL worked in my case. I'm using Ubuntu 22.04 LTS with Telegram Desktop version 4.15.2.

Open Ubuntu Software -> Telegram Desktop -> Permission -> Disable **opengl: allow access to OpenGL stack** 
I also disable **Access hardware information**, but I don't think it helps.

![Screenshot from 2024-03-21 12-32-36](https://github.com/telegramdesktop/tdesktop/assets/2363783/7a76820c-d387-45f7-9e02-899af7914286)

This come from #27207 and #27450 , something wrong with vga driver, I think.
