### ISSUE TITLE
PgUp/PgDown provide zero overlap

### ISSUE THREAD

**Issue by pbaykalov** [telegramdesktop/tdesktop#27246]
### Steps to reproduce

1. Press PgUp/PgDown in any chat

### Expected behaviour

Chat content should include small part of previous content as it happens in all modern browsers and document viewers. Ideally there should be 2 lines of text visible from the previous content to not impair reading.

### Actual behaviour

There is zero overlap between previous and current content. First screen is bottom of window before pressing PgDown, second - top of window afterwards.
![image](https://github.com/telegramdesktop/tdesktop/assets/54845956/c1976e28-2434-480b-aaa2-cf7c8fad0b17)
![image](https://github.com/telegramdesktop/tdesktop/assets/54845956/43f992e4-b068-4032-a23c-752e02b9fa26)

### Operating system

Windows 10

### Version of Telegram Desktop

4.12.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#25571
