### ISSUE TITLE
Telegram desktop crashes after updated to 4.13

### ISSUE THREAD

**Issue by thealex55** [telegramdesktop/tdesktop#27254]
### Steps to reproduce

Click mouse right button on chat background around image or video in chat

### Expected behaviour

It shoud work normally

### Actual behaviour

Telegram Desktop client crashes

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.13

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Proivde crash ID as instructed in issue template

**Comment by AndreiGorlov** [comment]
Same on windows x64 client

**Comment by jimmy-1000** [comment]
It's true. Right click on any chat and Telegram closes.
Windows 7 64bits

**Comment by BoffinBrain** [comment]
I just updated to 4.13 and immediately encountered this crash too.

**Comment by RandolphKarter** [comment]
same on debian 12 bookworm
Crash ID: fff07052-627f-4604-b9e683b2-7f164627

**Comment by LeoJuanZ** [comment]
True to windows 10 x64

log files:
[2023.12.23 13:01:50] RPC Error: request 49 got fail with code 400, error PEER_ID_INVALID
[2023.12.23 13:01:50] Message Info: bad message notification received (error_code 33) for msg_id = 7315836452597892816, seq_no = 138
[2023.12.23 13:01:50] Message Info: bad message notification received, msgId 7315836452597892816, error_code 33

**Comment by Aokromes** [comment]
there is no need of more reports.
