### ISSUE TITLE
when opening a picture/image or video, it is not displayed  (instead a white screen appears) bug

### ISSUE THREAD

**Issue by muhtor** [telegramdesktop/tdesktop#27250]
### Steps to reproduce

opening a image or video

### Expected behaviour

111

### Actual behaviour

111

### Operating system

Windows 10

### Version of Telegram Desktop

4.12.2 x64

### Installation source

Static binary from official website

**Comment by CipherDeveloper** [comment]
Expected behaviour: 111 ☠️

**Comment by Aokromes** [comment]
what's your gfx card?
