### ISSUE TITLE
[linux] most scroll after scroll direction change in media view on some logitech hi-res wheel mouse were ignored

### ISSUE THREAD

**Issue by detiam** [telegramdesktop/tdesktop#27252]
### Steps to reproduce

1. open media view in telegram chat
2. scroll on it

### Expected behaviour

media change on every wheel scroll.

### Actual behaviour

most scroll after scroll direction change were ignored.

https://github.com/telegramdesktop/tdesktop/assets/44510779/048491bd-281e-4238-bd5f-d5c67373cffd

tested on static binary from official website too

### Operating system

archlinux rolling kde plasma v5.27.10 wayland

### Version of Telegram Desktop

4.12.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Based on the discussion in #27245, you should report this to kwin so it generates the correct events
