### ISSUE TITLE
Delete all proxy button OR select and delete

### ISSUE THREAD

**Issue by BlackCrowxyz** [telegramdesktop/tdesktop#27264]
### Is your feature request related to a problem?

Troublesome proxy deletion.

### Describe the solution you'd like

Add a delete all proxy + select to delete proxy button

### Describe alternatives you've considered

-

### Additional context

Mobile app has this feature.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5028
