### ISSUE TITLE
Muted group generates notification and sound when message is pinned

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#27265]
### Steps to reproduce

1. mute a group you are in
2. someone (with permission to do that e.g. an admin) pins a message in the group

### Expected behaviour

Should not generate a notification nor sound because the group is muted. 

### Actual behaviour

generates a notification with sound despite the group being muted

### Operating system

Manjaro Linux

### Version of Telegram Desktop

4.12.2

### Installation source

Other (unofficial) source

**Comment by php4fan** [comment]
Certainly happens in muted groups where you are an admin (and some other admin pins the message), but I think I've also seen it happen in groups where I was not an admin.

**Comment by Aokromes** [comment]
not a bug, intended to be on that way, platform wide.

**Comment by php4fan** [comment]
Wow, that's so stupid. But you're right, the mobile app does the same.

**Comment by john-preston** [comment]
There should be a setting session-wide in Settings > Notifications for pinned messages in all groups.

**Comment by php4fan** [comment]
> There should be a setting session-wide in Settings > Notifications for pinned messages in all groups.

Indeed. But even if one wants to be notified of pinned messages in general for non-muted groups, muting a group normally means I don't want _any_ notification for that particular group.

**Comment by john-preston** [comment]
@php4fan Non muted groups get notifications for all messages including pinning anyway.

**Comment by Aokromes** [comment]
> > There should be a setting session-wide in Settings > Notifications for pinned messages in all groups.
> 
> Indeed. But even if one wants to be notified of pinned messages in general for non-muted groups, muting a group normally means I don't want _any_ notification for that particular group.

and send pinnned message with notification means it's important to read, more than the will of user of not being notified.

**Comment by php4fan** [comment]
> Non muted groups get notifications for all messages including pinning anyway.

Really? Regardless of that setting?
Then the setting should say "pinned messages in muted groups", because that's far from obvious. In that case, that's precisely the setting I wanted.

>  send pinnned message with notification means it's important to read, more than the will of user of not being notified.

Pinning a message means it's important that you read it, but not necessarily that you read it the moment it's been pinned.  Especially when it's a preexisting message that had been sent before, and now someone pins it.
