### ISSUE TITLE
no shadow of the window on Linux with Wayland CSD with patched Qt

### ISSUE THREAD

**Issue by camelCaseNick** [telegramdesktop/tdesktop#27263]
### Steps to reproduce

Use a Wayland compositor such as Mutter and install Telegram from Flathub with your Qt patches. If you use client-side decorations, the window has no shadow, even though it seems like it used to have. (see #16316)

### Expected behaviour

The window should have some kind of shadow.

### Actual behaviour

It does not have one.

### Operating system

Debian testing + Flatpak

### Version of Telegram Desktop

4.12.2

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Apparently you have enabled Qt window frame?

**Comment by ilya-fedin** [comment]
No, it's disabled by default but it's the same setting as 'Use system window frame on X11', just named differently on Wayland because not every compositor provides system window frame.

**Comment by ilya-fedin** [comment]
You need to disable it, Qt doesn't provide shdaows in its frame

**Comment by camelCaseNick** [comment]
Okay, so I turned it on without even knowing. Sorry, I missed it. The renaming might've confused me here, though it makes sense with Wayland compositor's different behaviour. Thanks!
