### ISSUE TITLE
allow to ban user from recent actions

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#27267]
### Is your feature request related to a problem?

on groups where a bot deletes spammers post you need to copy user, go to users list making very time taking

### Describe the solution you'd like

allow to ban user on recent actions adding it next to restrict user.

### Describe alternatives you've considered

put it on profile view from recent actions like on android (more time taking)

**Comment by Aokromes** [comment]
another place where to put it can be here https://i.imgur.com/Bmknb4e.png

**Comment by Aokromes** [comment]
edit: atm you can restrict, but the restricted person will continue to be on group and can continue gattering members list or spam by pm.

**Comment by RememberTheAir** [comment]
v5.4.6 supports banning now:

![Telegram_2024-09-05_14-39-02](https://github.com/user-attachments/assets/0244ae86-8ca8-4319-a653-59a70536c2e0)

**Comment by Aokromes** [comment]
and this is why slatebot is needed lol, even this being feature request won't be labeled lol
