### ISSUE TITLE
allow to report profile image from user info

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#27269]
### Is your feature request related to a problem?

atm to report one profile image you must zoom it then report it when a lot of times there is no need to zoom to see it's inadecuate profile image.

### Describe the solution you'd like

allow right click -> report

### Describe alternatives you've considered

none

**Comment by 23rd** [comment]
You are free to test this feature in the nightly build.
https://github.com/telegramdesktop/tdesktop/actions/runs/10644240554

**Comment by Aokromes** [comment]
it works fine :)

**Comment by Aokromes** [comment]
implemented on 5.4.5.
