### ISSUE TITLE
Error in Story Upload Limit Recognition

### ISSUE THREAD

**Issue by alyaa999** [telegramdesktop/tdesktop#27262]
### Steps to reproduce

I encountered an issue related to story uploads in the Telegram app. Here are the details:
1- Start uploading the first story.
2- Begin uploading the second story.
3- Initiate the upload for the third story.
4- Before the third story completes its upload, delete it.
5- Post only two stories.
6- Attempt to upload the third story again.

### Expected behaviour

I expected to be able to upload the third story successfully since I only posted two stories, and the third one was deleted before completion.

### Actual behaviour

The app displays an error message stating "Limited reached" and indicates that I have already posted three stories, even though I only posted two.
![image](https://github.com/telegramdesktop/tdesktop/assets/41211827/594c5970-58b5-4a7c-a35a-dae557d226a5)

### Operating system

Android 10.3.2

### Version of Telegram Desktop

Version 4.13.1 x64

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
this is telegram desktop bugtracker, and you don't use telegram desktop.
