### ISSUE TITLE
Group call video recording quality buggy

### ISSUE THREAD

**Issue by binyominzeev** [telegramdesktop/tdesktop#27272]
### Steps to reproduce

1. I have a group and started a video group chat.
2. Shared screen with some users logging in, some of them showing their cameras.
3. Made a recording of the call and saved it.

### Expected behaviour

I do this everyday and it almost always produces good video quality, with no audio issues.

### Actual behaviour

In the last few days twice repeated, that the group call was fine, nobody complained about quality, but the produced video recording was lagging.

"ffmpeg -v error" produced many errors like this:

[null @ 0x7498400] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 22271 >= 22271

### Operating system

Linux Mint 21.2, Cinnamon

### Version of Telegram Desktop

4.13.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
i think this is handled server side.

**Comment by binyominzeev** [comment]
OK, thank you, I reported it there as well:

https://bugs.telegram.org/c/35662
