### ISSUE TITLE
Input method cursor positioning error

### ISSUE THREAD

**Issue by ikool-cn** [telegramdesktop/tdesktop#27277]
### Steps to reproduce

Everything was fine when I was using the old version of telegram-desktop 4.1.1. After recently upgrading to telegram-desktop 4.13.1, the input method panel is always positioned in the upper left corner of the screen.

### Expected behaviour

The input method panel should follow the typing box

### Actual behaviour

The input method panel is always positioned in the upper left corner of the screen

### Operating system

ubuntu 22.10

### Version of Telegram Desktop

4.13.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Provide screenshots

**Comment by ikool-cn** [comment]
![1](https://github.com/telegramdesktop/tdesktop/assets/4831344/d875d1d5-14a1-46f4-8b20-050741bd7068)
Telegram-desktop

![2](https://github.com/telegramdesktop/tdesktop/assets/4831344/065d2434-b7d2-4c5a-aea1-47cf70e21386)
Other app

@ilya-fedin

**Comment by ilya-fedin** [comment]
What input method is this?

**Comment by ilya-fedin** [comment]
Are you sure this other app works via Wayland just like tdesktop? If it runs in X11 compatibility mode then it could be a bug in your system of not supporting this with native Wayland applications.

**Comment by lilydjwg** [comment]
Are you using fcitx4? It doesn't support Wayland.

**Comment by ikool-cn** [comment]
> Are you using fcitx4? It doesn't support Wayland.

![3](https://github.com/telegramdesktop/tdesktop/assets/4831344/1395a05e-4d93-42b5-bb10-7f323854f641)

Yes, i am using fcitx4,  Now I installed the old version 4.1.1 and everything is normal.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic

$ sudo apt-get install telegram-desktop
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
telegram-desktop is already the newest version (4.1.1+ds-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by ikool-cn** [comment]
> Are you sure this other app works via Wayland just like tdesktop? If it runs in X11 compatibility mode then it could be a bug in your system of not supporting this with native Wayland applications.

![1](https://github.com/telegramdesktop/tdesktop/assets/4831344/4679f067-b1f4-4c76-911a-9628493b83ab)
![3](https://github.com/telegramdesktop/tdesktop/assets/4831344/d994a7f6-96d6-4c83-97e2-2dec6c5465b5)
![2](https://github.com/telegramdesktop/tdesktop/assets/4831344/e9a19ea2-ea74-42d5-92eb-eab0e7145877)

I don’t know what Wayland is, but now I reinstall the old version 4.1.1 and everything is ok

**Comment by ikool-cn** [comment]
> What input method is this?

It's sogou input method [https://shurufa.sogou.com/linux](url)

**Comment by ilya-fedin** [comment]
Well, perhaps you should know, because Wayland is what Ubuntu uses now by default and modern versions of tdesktop run natively under Wayland as well. If your input method doesn't support Wayland then it won't work with modern applications. You have to contact distro support and ask for a Wayland compatible input method or ask how to switch to X11.

**Comment by ikool-cn** [comment]
> Well, perhaps you should know, because Wayland is what Ubuntu uses now by default and modern versions of tdesktop run natively under Wayland as well. If your input method doesn't support Wayland then it won't work with modern applications. You have to contact distro support and ask for a Wayland compatible input method or ask how to switch to X11.

Ok now i know, but why everything is ok when I switch to the old version 4.1.1?

**Comment by dimas1980200** [comment]
Ага я согласен

ср, 27 дек. 2023 г., 13:48 ikool ***@***.***>:

**Comment by ilya-fedin** [comment]
> Ok now i know, but why everything is ok when I switch to the old version 4.1.1?

Because it's a distro build inherited from Debian and they build with older toolkit that doesn't support Wayland natively

**Comment by ikool-cn** [comment]
> > Ok now i know, but why everything is ok when I switch to the old version 4.1.1?
> 
> Because it's a distro build inherited from Debian and they build with older toolkit that doesn't support Wayland natively

ok,thank you!
