### ISSUE TITLE
allow enter to be used on create new topic

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#27271]
### Is your feature request related to a problem?

atm you need to use mouse to accept topic creation, while escape key is allowed to cancel

### Describe the solution you'd like

allow enter key to be used at https://i.imgur.com/JVlh6Ob.png

### Describe alternatives you've considered

none

**Comment by Aokromes** [comment]
also on edit.

**Comment by 23rd** [comment]
Should be better now.

**Comment by Aokromes** [comment]
thx!
