### ISSUE TITLE
Send later

### ISSUE THREAD

**Issue by colotoon** [telegramdesktop/tdesktop#27281]
### Is your feature request related to a problem?

Send later

What is the problem?
Everything is simple. Why in a chat or a group.until topics are enabled, it is possible to send messages later (deferred messages), but as soon as you turn on topics, it is no longer possible to send messages later.
This is not in the context menu, and also, if messages are already scheduled, the "pending messages" icon is not displayed.

But in the mobile version everything is fine.

It's not fair!

Make it possible to send delayed messages from the desktop app!

### Describe the solution you'd like

Make it possible to send delayed messages from the desktop app!

### Describe alternatives you've considered

n\a

**Comment by Aokromes** [comment]
duplicate and application wide issue, search on bugs.telegram.org
