### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by atrdev-rgb** [telegramdesktop/tdesktop#27282]
### Steps to reproduce

1. Installed and Prepared Visual Studio 2022 with 10.0.22000.0 SDK version with third party software
2. run `git clone --recursive https://github.com/telegramdesktop/tdesktop.git`
3. run `tdesktop\Telegram\build\prepare\win.bat`
4. [18/28](Libraries/libvpx): CHANGED, (r)ebuild, rebuild (a)ll, (s)kip, (p)rint, (q)uit?: i press `a`

### Expected behaviour

Build project

### Actual behaviour

![Screenshot 2023-12-28 110858](https://github.com/telegramdesktop/tdesktop/assets/34670899/f6416372-7eb0-4cb6-85f2-36c8134ae8aa)
![Screenshot 2023-12-28 111003](https://github.com/telegramdesktop/tdesktop/assets/34670899/f60d4f07-25c4-486c-84fc-dacbbaeb3547)

error details in log.txt file
[log.txt](https://github.com/telegramdesktop/tdesktop/files/13784524/log.txt)

### Operating system

Windows 11

### Version of Telegram Desktop

latest

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#26012
