### ISSUE TITLE
The "latest" release on GitHub is not latest

### ISSUE THREAD

**Issue by lilydjwg** [telegramdesktop/tdesktop#27280]
### Steps to reproduce

1. open https://github.com/telegramdesktop/tdesktop
2. find the latest release on the right column

### Expected behaviour

It points to a real latest release.

### Actual behaviour

It points to version 4.13.0 but 4.13.1 is available. What's more, 4.13.0 has a crash bug.

### Operating system

Firefox

### Version of Telegram Desktop

4.13.0

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Should be better now.

**Comment by lilydjwg** [comment]
Yes, thanks!
