### ISSUE TITLE
Improve scrolling experience with mouse wheel

### ISSUE THREAD

**Issue by SalehBagheri** [telegramdesktop/tdesktop#27287]
### Is your feature request related to a problem?

The scrolling experience in the **Chat List** is not smooth, and it becomes even more challenging when using the mouse wheel. Finding specific chats has become a cumbersome task due to these issues.

### Describe the solution you'd like

Just make the scrolling experience smoother with the mouse wheel. 

### Describe alternatives you've considered

No alternative idea right now.

**Comment by ilya-fedin** [comment]
#26546?
