### ISSUE TITLE
[TDesktop] switch_inline_query_current_chat buttons don’t work inside topics

### ISSUE THREAD

**Issue by hlopikit** [telegramdesktop/tdesktop#27290]
### Steps to reproduce

1. Inside a topic, use a bot that has a switch_inline_query_current_chat button
2. Tap on the button

### Expected behaviour

The app writes in the input field of the topic the content of the button.

### Actual behaviour

Nothing happens.

### Operating system

Windows

### Version of Telegram Desktop

4.13.1

### Installation source

Static binary from official website

**Comment by natashalysakova** [comment]
The same bug is in MacOS version of Telegram Desktop version 4.15.1

**Comment by veyzz** [comment]
Windows Telegram Desktop 5.5.1 x64: problem still occurs.
