### ISSUE TITLE
It is hoped that the automatic download and automatic playback disabling options for avatars and emoticons can be added to groups and private chats.

### ISSUE THREAD

**Issue by OneMiOne** [telegramdesktop/tdesktop#27297]
### Is your feature request related to a problem?

It is hoped that the automatic download and automatic playback disabling options for avatars and emoticons can be added to groups and private chats.

### Describe the solution you'd like

I hope that automatic download and auto-play disabling options for avatars and emoticons can be added to groups and private chats. Because I don’t want to see NSFW content and other content I don’t want to see in my daily life, so I recommend being selective about emoticons. For playback and downloading, you can also add a default display avatar to the avatar or add a frosted glass mask for selective playback and downloading.

### Describe alternatives you've considered

I hope that automatic download and auto-play disabling options for avatars and emoticons can be added to groups and private chats. Because I don’t want to see NSFW content and other content I don’t want to see in my daily life, so I recommend being selective about emoticons. For playback and downloading, you can also add a default display avatar to the avatar or add a frosted glass mask for selective playback and downloading.

**Comment by ilya-fedin** [comment]
#24658
