### ISSUE TITLE
Saved messages chat lists disappear

### ISSUE THREAD

**Issue by c0re100** [telegramdesktop/tdesktop#27292]
### Steps to reproduce

1. Open Saved Messages
2. View list by click a title
3. Close panel
4. View again
5. list is disappear and UI back to old style Saved Messages(Shared media)

### Expected behaviour

It should always display chat list.

### Actual behaviour

Chat list show only one time.

### Operating system

Windows 10

### Version of Telegram Desktop

4.14

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@c0re100 It is possible that your inbox is not yet ready for the feature.. in that case it'll start working fine within a couple of days. Logs can tell if that's the case.
