### ISSUE TITLE
For Developers, several months of problems with the audio format WAV

### ISSUE THREAD

**Issue by borodadada** [telegramdesktop/tdesktop#27298]
### Steps to reproduce

When uploading a WAV audio file, Telegram does not understand that it is an audio file!
Always was, before bug
![Snipaste_2024-01-01_11-03-12](https://github.com/telegramdesktop/tdesktop/assets/5166757/3d6de196-647c-4cd3-912b-10472bb4062e)
Now
![Snipaste_2024-01-01_11-03-20](https://github.com/telegramdesktop/tdesktop/assets/5166757/ad5ce21d-1e69-49a9-83d7-7fe6c3f942be)
I have to upload a file, then create another one, but I need to rename WAV to FLAC, and then it starts working, BUT it turns out to be 2 downloads. This is an old problem and has not yet been solved!

### Expected behaviour

There should be a button - Play!

### Actual behaviour

Download button, audio format not recognized.

### Operating system

Windows 10 x64

### Version of Telegram Desktop

latest

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#27102
