### ISSUE TITLE
[bug] Black screen when window closed while full screen (OSX)

### ISSUE THREAD

**Issue by tconroy** [telegramdesktop/tdesktop#273]
Steps to reproduce:

1. Open Telegram Desktop
2. Click green "full screen" button. Telegram Window is moved to it's own "Space" (virtual desktop)
3. hit command+w (close window shortcut)

The result is a black screen in the virtual desktop. The desired functionality is the window closes, and the virtual desktop closes as well.

**Comment by auchri** [comment]
Is this still the case? If yes, reopen the issue

**Comment by tconroy** [comment]
This is still the case. Mac OSX Yosemite. Also recently reformatted / reinstalled OSX ( for unrelated reason ), and noticed it's still occurring after a fresh install so it's not my setup.

**Comment by ManuelSchneid3r** [comment]
About a year ago still (or again) the case.

**Comment by john-preston** [comment]
@ManuelSchneid3r This should be fixed in the latest alpha version, no?
