### ISSUE TITLE
Linux ubuntu 22.04 (snap installed ) failed to create dri2 screen

### ISSUE THREAD

**Issue by bobir01** [telegramdesktop/tdesktop#27309]
### Steps to reproduce

1. simply open telegram-desktop as usuall

### Expected behaviour

opens the new telegram window and not showing its process in resource monitor 

### Actual behaviour

but it just lagged , and tried run it from terminal here what i found:
```shell~$ telegram-desktop
[ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
libEGL warning: egl: failed to create dri2 screen
Segmentation fault (core dumped)```



### Operating system

Ubuntu 22.04 Gnome desktop

### Version of Telegram Desktop

4.14.2

### Installation source

Snap

### Crash ID

could not open app

### Logs

_No response_

**Comment by ilya-fedin** [comment]
Can't reproduce

**Comment by voidnick** [comment]
I have the same problem with "latest/stable: 4.14.1 2024-01-02" and with "latest/edge: 4.14.2-5-gcee296163 2024-01-03".

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

uname -a
Linux opi5 5.10.160-rockchip #28 SMP Thu Dec 28 14:57:13 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

**Comment by voidnick** [comment]
glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Panfrost (0xffffffff)
    Device: Mali-G610 (Panfrost) (0xffffffff)
    Version: 23.0.0
    Accelerated: yes
    Video memory: 3731MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.3
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Panfrost
OpenGL renderer string: Mali-G610 (Panfrost)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 23.0.0-devel
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.3 (Compatibility Profile) Mesa 23.0.0-devel
OpenGL shading language version string: 3.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 23.0.0-devel
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

**Comment by dimkamonster** [comment]
same problem with latest/stable: 4.14.3 2024-01-05
~$ telegram-desktop 
[ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
libEGL warning: egl: failed to create dri2 screen
Segmentation fault (core dumped)


Ubuntu 22.04 with latest updates

**Comment by CuSZcXJWGrzbnE** [comment]
I had the same problem with ubuntu running on ESXi
I enabled the Enable 3D Support option and it worked
Previously it worked with it disabled

**Comment by voidnick** [comment]
> I have the same problem with "latest/stable: 4.14.1 2024-01-02" and with "latest/edge: 4.14.2-5-gcee296163 2024-01-03".

Works again at "latest/stable: 4.14.6 2024-01-16". Thanks!
