### ISSUE TITLE
icon has wrong path on debian snap install. I had to manually edit the disktop file to use the current directory as the version number was incorrect 

### ISSUE THREAD

**Issue by dave-watts** [telegramdesktop/tdesktop#27304]
### Steps to reproduce

view that the icon is missing from the menu on a debian (and maybe other linux) gnome desktop

### Expected behaviour

Icon should be shown

### Actual behaviour

no icon shown

### Operating system

debian 10 and 11 gnome 3.38

### Version of Telegram Desktop

3.14.1

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Can't confirm, the path is right
