### ISSUE TITLE
[Feature Request] Show "original sent" timestamp for forwarded messages

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2730]
(not using template because it's useless here)

When you hover mouse over edited message, is shows you "first sent" timestamp and "last edited" one.
![image](https://cloud.githubusercontent.com/assets/2780044/21421607/d11e77d0-c844-11e6-9026-7cec1b33bf67.png)
Since "edited" is not shown for forwarded messages, it will be very nice to see timestamp of original message, which was forwarded.

**Comment by stek29** [comment]
But forwarded messages can't be edited, right?

**Comment by MasterGroosha** [comment]
@stek29 That's why "original sent" timestamp can be placed instead of "last edited" one.

**Comment by stek29** [comment]
Isn't this an API issue?

**Comment by MasterGroosha** [comment]
@stek29 Since TDesktop has "original sent" timestamp for messages - no, this is not API issue

**Comment by stek29** [comment]
@MasterGroosha Where does it?

**Comment by MasterGroosha** [comment]
Look at my screenshot above: message has "original sent" and "edited" timestamps. 
What I suggest is to replace "edited" with "original sent" for **forwarded** messages since they can't be edited.

**Comment by stek29** [comment]
@MasterGroosha What do you mean by "Original send"? Do you want it to show time when message was forwarded and time when original message which is being forwarded was sent?

**Comment by MasterGroosha** [comment]
Exactly

**Comment by stek29** [comment]
@MasterGroosha Oh, I see. Yup, that's not an API issue indeed, messageFwdHeader has Date.

**Comment by auchri** [comment]
Fixed by #3568
