### ISSUE TITLE
Telegram 4.14.1.0 crashed on Windows 10 x64

### ISSUE THREAD

**Issue by JuraLys** [telegramdesktop/tdesktop#27308]
### Steps to reproduce

Telegram 4.14.1.0 crashed on Windows 10 x64 [Version 10.0.19045.3803] see attached log 
[teleg-log.txt](https://github.com/telegramdesktop/tdesktop/files/13821431/teleg-log.txt)

### Expected behaviour

Telegram should not crash

### Actual behaviour

Telegram 4.14.1.0 crashed

### Operating system

 Windows 10 x64 [Version 10.0.19045.3803] 

### Version of Telegram Desktop

Telegram 4.14.1.0 

### Installation source

Static binary from official website

### Logs

```shell
see attachment
```

**Comment by Aokromes** [comment]
try updating to 4.14.2
