### ISSUE TITLE
Scrolling chats behaves as if the CTRL key is pressed

### ISSUE THREAD

**Issue by Trema28** [telegramdesktop/tdesktop#27300]
### Steps to reproduce

1. Scroll through the list of chats with or without pressing the CTRL key.

### Expected behaviour

When the CTRL key is not pressed, scrolling is slow; when the CTRL key is pressed, scrolling is fast.

### Actual behaviour

Scrolling is fast when the CTRL key is not pressed.

### Operating system

Ubuntu 22.04.3 LTS

### Version of Telegram Desktop

4.14

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Are you using X11 or Wayland?

**Comment by Trema28** [comment]
X11

**Comment by ilya-fedin** [comment]
Can you reproduce on Wayland?

**Comment by Trema28** [comment]
On Wayland, the list scrolls slowly even if the CTRL key is pressed. Is this how it should be?

**Comment by ilya-fedin** [comment]
Not sure, this ctrl/shift feature was provided by the underlying toolkit and is broken since the stories update due to the scrolling effects which required scrolling rework and less relying on the tooliit. I don't know whether there's any plan to return this.

**Comment by Dandreholley** [comment]
> ### Steps to reproduce
> 
> 1. Scroll through the list of chats with or without pressing the CTRL key.
> 
> ### Expected behaviour
> 
> When the CTRL key is not pressed, scrolling is slow; when the CTRL key is pressed, scrolling is fast.
> 
> ### Actual behaviour
> 
> Scrolling is fast when the CTRL key is not pressed.
> 
> ### Operating system
> 
> Ubuntu 22.04.3 LTS
> 
> ### Version of Telegram Desktop
> 
> 4.14
> 
> ### Installation source
> 
> Static binary from official website
> 
> ### Crash ID
> 
> _No response_
> 
> ### Logs
> 
> _No response_
