### ISSUE TITLE
Ctrl+Shift+X shortcut for Strikethrough doesn't work anymore

### ISSUE THREAD

**Issue by OctoNezd** [telegramdesktop/tdesktop#27305]
### Steps to reproduce

1. Type text
2. Select it using any method
3. Try hitting Ctrl+Shift+X to strikethrough it

### Expected behaviour

Text becomes stricken through

### Actual behaviour

Nothing happens. Other shortcuts, like monospace and bold work.

### Operating system

Windows 11 22631.2861

### Version of Telegram Desktop

4.14.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
works for me on windows 10...

**Comment by OctoNezd** [comment]
Weird. Gonna try it on my other machine and check if perhaps my machine is somehow blocking ctrl+shift+x shortcut.

**Comment by OctoNezd** [comment]
Checked it on other PC - hotkey works fine. Sorry for bothering. 

Went disabling global shortcuts, and for some reason AMD Software blocks ctrl shift x, despite not even having it registered.
