### ISSUE TITLE
Upload mp4 as File

### ISSUE THREAD

**Issue by mysaeedjoon** [telegramdesktop/tdesktop#27317]
### Steps to reproduce

Hi 
Please please please add upload mp4 as file!

### Expected behaviour

Please please please add upload mp4 as file!

### Actual behaviour

Please please please add upload mp4 as file!

### Operating system

Windows 7

### Version of Telegram Desktop

v4..14.3 x64

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/10468#issuecomment-860936090
