### ISSUE TITLE
Does not save and restore window position on the Gnome Desktop environment

### ISSUE THREAD

**Issue by DAC-Protogen** [telegramdesktop/tdesktop#27316]
### Steps to reproduce

- Resize and position as you like
- Restart the app

### Expected behaviour

As far as I know, the Gnome desktop environment lets apps handle saving and restoring their window size and position.
I expect Telegram to start in the exact same size and position, on the same desktop as I left it when the app has been closed the last time.

### Actual behaviour

Telegram seems to restore its window size properly, but starts on a different position. I have to manually reposition it every time the app is being started. It drives me insane.

### Operating system

Fedora 39 Workstation, Gnome 45

### Version of Telegram Desktop

4.14.2

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
That is not allowed by the modern Linux and there's nothing tdesktop could done about that
