### ISSUE TITLE
SYSTEM MESSAGE

### ISSUE THREAD

**Issue by blavatmari** [telegramdesktop/tdesktop#27310]
### Steps to reproduce

After creating a cloud password for two-step authentication, a system message from Telegram is sent to the chat room. This message contains information about the changes made to the account. It can only be deleted via smartphone, but it will still appear on the PC version. Each time you open the app on your PC, this message will return to the chat list, even though it has already been deleted in the mobile version.

### Expected behaviour

The message should be deleted.

### Actual behaviour

The message returns to the chat list when the PC version is restarted.

### Operating system

Windows 10 Pro x64

### Version of Telegram Desktop

4.14.2 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
the mobile version deletes the message in its local cache. You can't delete the message on server and the PC version has no local message storage so such a button would be useless: the message will re-appear on the next launch after requesting the messages from server.

**Comment by blavatmari** [comment]
> the mobile version deletes the message in its local cache. You can't delete the message on server and the PC version has no local message storage so such a button would be useless: the message will re-appear on the next launch after requesting the messages from server.

Any message other than this can be deleted from both the sender and the user. This has never been a problem before. The problem is specifically with the message about changing the cloud password. Even if you delete it in the chat itself, via the PC version, it will appear in front of your eyes. This is a very obvious bug and, as I found out on another forum, many people have had it for a long time.

**Comment by ilya-fedin** [comment]
> This has never been a problem before.



> many people have had it for a long time.

This sounds like incompatible statements?

**Comment by blavatmari** [comment]
> > This has never been a problem before.
> 
> > many people have had it for a long time.
> 
> This sounds like incompatible statements?

I mean, system messages used to delete quietly, at least for me, but this is what comes back again and again, immediately. As it turns out, this is exactly what many people have encountered before.

**Comment by ilya-fedin** [comment]
You mean exactly this kind of system messages or you was deleting other kinds if system messages? The server doesn't allow to delete any kind of service message I guess.

**Comment by blavatmari** [comment]
> You mean exactly this kind of system messages or you was deleting other kinds if system messages? The server doesn't allow to delete all kinds of service message I guess.

After changing my cloud password, a message from Telegram arrived. I deleted it on my smartphone, deleted it on the PC version. As a result, it is not in the chat on the smartphone, but in the chat on the PC it is there, although I deleted it. And it appears on the PC version every time, every time I log into the app. I have a message hanging in my chat list that cannot be deleted. How can I explain the problem more clearly?

**Comment by ilya-fedin** [comment]
Please re-read my first message. It sounds absolutely expected to me: the server doesn't let delete it so it re-appears every time messages are downloaded. Just forget about that message

**Comment by blavatmari** [comment]
> Please re-read my first message. It sounds absolutely expected to me: the server doesn't let delete it so it re-appears every time messages are downloaded. Just forget about that message

What do you mean, forget it? Why do I need it in the chat room? Why do I hit delete and it stays in the list? That's not normal! Why won't the server let me delete it? Why can I delete it on my smartphone, but I can't delete it on my PC?

**Comment by blavatmari** [comment]
![Screenshot_1](https://github.com/telegramdesktop/tdesktop/assets/155579972/a853263b-d2a0-4267-8dfa-2714584e3f99)
![Screenshot_2](https://github.com/telegramdesktop/tdesktop/assets/155579972/af26f773-fd61-441c-95ad-3ec08ac5424c)
![Screenshot_3](https://github.com/telegramdesktop/tdesktop/assets/155579972/0c8da577-5b65-48f0-8b4a-87a61bb4a785)
![Screenshot_4](https://github.com/telegramdesktop/tdesktop/assets/155579972/dbb055cc-a1e2-421c-b55e-5b9d0d1ddbbc)
![Screenshot_5](https://github.com/telegramdesktop/tdesktop/assets/155579972/22ba7926-1069-4bf7-bbf6-be121272377a)

**Comment by blavatmari** [comment]
> ![Screenshot_1](https://private-user-images.githubusercontent.com/155579972/294021188-a853263b-d2a0-4267-8dfa-2714584e3f99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTQwOTIsIm5iZiI6MTcwNDMxMzc5MiwicGF0aCI6Ii8xNTU1Nzk5NzIvMjk0MDIxMTg4LWE4NTMyNjNiLWQyYTAtNDI2Ny04ZGZhLTI3MTQ1ODRlM2Y5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QyMDI5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmZkM2ZmZDI1YTBmNjRhNmM1M2RlODFmMmQ0NTk5ZGJhYzhhNTU5NWIxNTczYTViOTZkMDk2ODhhMDNiYjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gRH_8lX3owfELq60Tz5EKzD4TNfTwmHK0R-KwwoqAQ8) ![Screenshot_2](https://private-user-images.githubusercontent.com/155579972/294021192-af26f773-fd61-441c-95ad-3ec08ac5424c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTQwOTIsIm5iZiI6MTcwNDMxMzc5MiwicGF0aCI6Ii8xNTU1Nzk5NzIvMjk0MDIxMTkyLWFmMjZmNzczLWZkNjEtNDQxYy05NWFkLTNlYzA4YWM1NDI0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QyMDI5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTk4MWFlOTkyZWVlZjRjODViOTEzNTg2NWQzZDlhYjAxNjk1ZDc3ZWEyOWI4Zjc1MWEyNGZjYjViODBmODQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H_N9voWtrKnE7gyovk7Yv86DpUG804ONawhNpb4-oKw) ![Screenshot_3](https://private-user-images.githubusercontent.com/155579972/294021196-0c8da577-5b65-48f0-8b4a-87a61bb4a785.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTQwOTIsIm5iZiI6MTcwNDMxMzc5MiwicGF0aCI6Ii8xNTU1Nzk5NzIvMjk0MDIxMTk2LTBjOGRhNTc3LTViNjUtNDhmMC04YjRhLTg3YTYxYmI0YTc4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QyMDI5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDBhNzAwYjkyNmFkNjFmMTBlMDA2NmIyMDI5MWMwZTE4N2JhODVkYjc5YmMyMDIyY2NkZjA2YmU3ZjNjYTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.brf802Bv0iQhTKy-7LMuFfP2Oj5uZt7LksUhZQveIms) ![Screenshot_4](https://private-user-images.githubusercontent.com/155579972/294021197-dbb055cc-a1e2-421c-b55e-5b9d0d1ddbbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTQwOTIsIm5iZiI6MTcwNDMxMzc5MiwicGF0aCI6Ii8xNTU1Nzk5NzIvMjk0MDIxMTk3LWRiYjA1NWNjLWExZTItNDIxYy1iNTVlLTViOWQwZDFkZGJiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QyMDI5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Njc1MzU3ZDhkYzRlNDVlMzEzOWZkMWU1NzcyMjdlZjdkMTIxNGJmZjgyM2RlYjA3YzA3YTBiY2E2YjI2NjVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cu9NWI0jcF8iF7sPixN4KqbAtF-Qe_OXO7zuYWVRuNw) ![Screenshot_5](https://private-user-images.githubusercontent.com/155579972/294021199-22ba7926-1069-4bf7-bbf6-be121272377a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTQwOTIsIm5iZiI6MTcwNDMxMzc5MiwicGF0aCI6Ii8xNTU1Nzk5NzIvMjk0MDIxMTk5LTIyYmE3OTI2LTEwNjktNGJmNy1iYmY2LWJlMTIxMjcyMzc3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QyMDI5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjU1Y2RlOWY3ZmUzYTUxOGE2NGMxN2FkYjkxY2U0YjZkOTc5MWQ1OGRmMGFhMTJlNTI4NzU4NmYxMjZiYjM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2cExatcmTuaNiPnv5fcEism1M_5CSarbLXN0-RbiNvg)

Before the fifth screenshot, the app was restarted. It shows that the message came back again. At the same time, it is not among the chats on the smartphone.

**Comment by ilya-fedin** [comment]
> Why can I delete it on my smartphone, but I can't delete it on my PC?

I've explained that in my first message, have you read it?

> What do you mean, forget it?

I mean if the server doesn't let delete it then nothing could be done in tdesktop, sorry. You have to choose 'platform-wide' issue type when creating issue if you want to ask for such possibility on the server.

> Why do I need it in the chat room?
> Why won't the server let me delete it?

Well, you don't need but perhaps that's how it was decided by the people who decide. You're just not allowed to do it and that's it, accept that. :(

> Why do I hit delete and it stays in the list?

Already answered: most likely because the server doesn't let you do so.

**Comment by VadimVadimVadim1337** [comment]
Дуров, 10 iq конечно

**Comment by blavatmari** [comment]
> > Why can I delete it on my smartphone, but I can't delete it on my PC?
> 
> I've explained that in my first message, have you read it?
> 
> > What do you mean, forget it?
> 
> I mean if the server doesn't let delete it then nothing could be done in tdesktop, sorry. You have to choose 'platform-wide' issue type when creating issue if you want to ask for such possibility on the server.
> 
> > Why do I need it in the chat room?
> > Why won't the server let me delete it?
> 
> Well, you don't need but perhaps that's how it was decided by the people who decide. You're just not allowed to do it and that's it, accept that. :(
> 
> > Why do I hit delete and it stays in the list?
> 
> Already answered: most likely because the server doesn't let you do so.

Okay, the server doesn't allow it, let's say. But it's a bug, that's why I created this topic! How else can I get through to the developers to fix it? I am interfering with this message and I want it to disappear! With any other message I can achieve this, but not with this one!

**Comment by ilya-fedin** [comment]
> Before the fifth screenshot, the app was restarted. It shows that the message came back again. At the same time, it is not among the chats on the smartphone.

Ah, so you're deleting not a message but a chat. Perhaps the server bugs and doesn't actually delete the chat, that's indeed reported periodically. Still, if the server bugs, nothing could be done in the client...

**Comment by ilya-fedin** [comment]
> Okay, the server doesn't allow it, let's say. But it's a bug, that's why I created this topic! How else can I get through to the developers to fix it? 

There are multiple types if bug report when you create issue. You have chosen a client-side bug report while your problem is server-side and reached wrong people.

**Comment by blavatmari** [comment]
> > Okay, the server doesn't allow it, let's say. But it's a bug, that's why I created this topic! How else can I get through to the developers to fix it?
> 
> There are multiple types of bug report when you create issue. You have chosen a client-side bug report while your problem is server-side and reached wrong people.

Okay, is there anything you can do to help me?

**Comment by ilya-fedin** [comment]
Personally I can't.

**Comment by blavatmari** [comment]
> Personally I can't.

Where should I direct this problem? Where do I write?

**Comment by ilya-fedin** [comment]
Use the new issue button, choose platform-wide issue type

**Comment by john-preston** [comment]
I suspect this night be a security measure.

**Comment by john-preston** [comment]
I suspect this might be a security measure.
