### ISSUE TITLE
Telegram notifications doesn't disappear when there's not activity on the computer

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#2731]
### Steps to reproduce
1.  Open Telegram and minimize
2. Don't touch anything on the computer
3. Receive notifications

### Expected behaviour
The notifications will be shown and disappear after a few seconds, as usual.

### Actual behaviour
The notifications doesn't disappear after a few seconds

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 0.10.20
**Notifications**: Telegram (not system)

Thanks!

**Comment by john-preston** [comment]
@arieljannai This is intended. If no user input is provided it is assumed that the user is not currently at the computer, so the notifications are delayed for the first user input made.

**Comment by arieljannai** [comment]
Oh ok. Thanks!

**Comment by TerryvanWalen** [comment]
Could there be an option to disable this behaviour or add functionality that the messages dissapear when a movie/netflix is playing? The messages are now stuck on top of the movie.

**Comment by bidlocode** [comment]
option to disable this behaviour would be nice
