### ISSUE TITLE
In dark theme - White flash is seen when maximizing telegram window/restoring from minimized state

### ISSUE THREAD

**Issue by pavel-pargachev** [telegramdesktop/tdesktop#27315]
### Steps to reproduce

1. Chose dark theme
2. Minimize the telegram window
3. Restore the telegram window full screen (maximized state)

Or 
1. Chose dark theme
2. Toggle between normal windows size and maximized to the full screen windows size

### Expected behaviour

Telegram window stayed dark, does not flash with white backgound

### Actual behaviour

Part of telegram window (in case of maximize/normal window size toggling), of full window area (in case of restoring from the minimized state) becomes white for a fraction of a second, which looks like a flash in a dark room.

https://github.com/telegramdesktop/tdesktop/assets/56195158/838d2932-59ea-41ed-845a-0a2f6c454d4a

https://github.com/telegramdesktop/tdesktop/assets/56195158/3a16d0ef-e200-43c5-8df2-618d8aa76daa

### Operating system

Windows 10 22H2 19045.3803

### Version of Telegram Desktop

4.11.6

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
that sadly looks like a problem with your graphics drivers

**Comment by Aokromes** [comment]
also, latest version is 4.14.3
