### ISSUE TITLE
Merge / Append new content into an existing export file

### ISSUE THREAD

**Issue by Deilan** [telegramdesktop/tdesktop#27326]
### Is your feature request related to a problem?

One would like to have a
1. single
2. and up to date export file
3. without a need of reexporting previously exported data
4. without a need of fine-tuning export date parameters

### Describe the solution you'd like

A capability to merge (append) new (not contained) content into an existing export file

### Describe alternatives you've considered

Don't know any

**Comment by ilya-fedin** [comment]
#10497
