### ISSUE TITLE
System Proxy Not working

### ISSUE THREAD

**Issue by lucairr** [telegramdesktop/tdesktop#27328]
### Steps to reproduce

1. Open Telegram Desktop
2. Choose System Proxy

### Expected behaviour

Telegram Desktop should automatically detect System proxy and get connected on selecting the System proxy based on a PAC script file.

### Actual behaviour

Telegram unable to connect.

### Operating system

Windows 10

### Version of Telegram Desktop

4.14.3 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop couldn't do so because the underlying toolkit (Qt) doesn't support this. As far as I'm aware, only web browsers support this because this requires executing javasrcipt.
