### ISSUE TITLE
Long delay when open first media after application idle

### ISSUE THREAD

**Issue by alexeynl** [telegramdesktop/tdesktop#27323]
### Steps to reproduce

1. Not use Telegram for some time (about 15 minutes).
2. Click on any video of photo to view it on full screen.

### Expected behaviour

Photo or video should be opened instantly.

### Actual behaviour

Photo or video is opened with delay about 2-3 seconds. It looks like freeze. After this freeze this and another photo or video is opened instantly:

https://github.com/telegramdesktop/tdesktop/assets/82229750/844b3a6b-3678-4e38-b298-ad3f32eb5da0

https://github.com/telegramdesktop/tdesktop/assets/82229750/f8940a13-97e7-4f47-8b8a-279a0960554c

https://github.com/telegramdesktop/tdesktop/assets/82229750/3e607d39-3cd9-4075-bb03-4ad3209bc640

### Operating system

Windows 11 and Windows 10

### Version of Telegram Desktop

4.14.3

### Installation source

Static binary from official website

**Comment by alexeynl** [comment]
I have this issue more than 1 year on my new laptop. I have update Telegram Desktop reqularly.

**Comment by ilya-fedin** [comment]
This sadly means it's a bug in your graphics driver...

**Comment by alexeynl** [comment]
> This sadly means it's a bug in your graphics driver...

Do you know what is the bug? How can you conclud "this is the bug" without any debug???

I have latest drivers and Windows update installed. I have beed updated drivers and operating system all this time. I also have tried install drivers from different sources: Windows Update, OEM and official AMD drivers.

**Comment by ilya-fedin** [comment]
You say disabling ANGLE helps, ANGLE means using hardware rendering. This is not a problem for every user what means this happens not with any driver / hardware.

**Comment by alexeynl** [comment]
> You say disabling ANGLE helps, ANGLE means using hardware (GPU) rendering.

So when i disable Angle, Telegram uses sofware (processor, not GPU) rendering . Correct?

**Comment by ilya-fedin** [comment]
Yes

**Comment by alexeynl** [comment]
I have created post about this issue at AMD community:
https://community.amd.com/t5/drivers-software/ryzen-6800h-applications-freezes-after-iddle-with-hardware/m-p/656887
Hope i will get support on this.
