### ISSUE TITLE
lelp gclient config "https://chromium.googlesource.com/breakpad/breakpad.git"

### ISSUE THREAD

**Issue by jamesmoriati** [telegramdesktop/tdesktop#2732]
i use gclient config "https://chromium.googlesource.com/breakpad/breakpad.git" in Google Breakpad.

after fetching python267_bin.zip, error : the system cannot find the path specified.

**Comment by jamesmoriati** [comment]
help me

**Comment by jamesmoriati** [comment]
What path should be set?
I just do not know the path.

**Comment by stek29** [comment]
Try to shorten path to build directory.
Put it in drive root for for example.

**Comment by jamesmoriati** [comment]
Thank you. I test.

**Comment by stek29** [comment]
@jamesmoriarti Don't forget to tell if it worked or not.

**Comment by jamesmoriati** [comment]
E:\TBuild\Libraries\depot_tools>SET PATH=%PATH%;E:\TBuild\Libraries\depot_tools;
E:\TBuild\Libraries\depot_tools\python276_bin;

E:\TBuild\Libraries\depot_tools>gclient config "https://chromium.googlesource.co
m/breakpad/breakpad.git"

[P9888 12:36:27.611 client.go:1209 I] Packages to be installed:
[P9888 12:36:27.612 client.go:1211 I]   infra/depot_tools/git_installer/windows-
amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362
[P9888 12:36:27.618 client.go:1068 I] cipd: resolving fetch URL for infra/depot_
tools/git_installer/windows-amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362
[P9888 12:36:27.976 storage.go:249 I] cipd: initiating the fetch
[P9888 12:36:29.425 storage.go:214 I] cipd: about to fetch 29.4 Mb
[P9888 12:36:29.425 storage.go:205 I] cipd: fetching - 0%
[P9888 12:36:34.431 storage.go:205 I] cipd: fetching - 17%
[P9888 12:36:39.437 storage.go:205 I] cipd: fetching - 37%
[P9888 12:36:44.440 storage.go:205 I] cipd: fetching - 57%
[P9888 12:36:49.440 storage.go:205 I] cipd: fetching - 74%
[P9888 12:36:54.445 storage.go:205 I] cipd: fetching - 93%
[P9888 12:36:56.172 storage.go:205 I] cipd: fetching - 100%
[P9888 12:36:56.173 storage.go:205 I] cipd: fetching - 100%
[P9888 12:36:56.173 storage.go:221 I] cipd: fetch finished successfully
[P9888 12:36:56.173 client.go:1023 I] cipd: successfully fetched infra/depot_too
ls/git_installer/windows-amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362
[P9888 12:36:56.302 deployer.go:138 I] Deploying infra/depot_tools/git_installer
/windows-amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362 into c:\users\james\appd
ata\local\temp\tmp6bjazt
[P9888 12:36:56.304 reader.go:162 I] cipd: about to extract 29.4 Mb
[P9888 12:36:56.383 reader.go:172 I] cipd: extracting - 99%
[P9888 12:36:56.384 reader.go:172 I] cipd: extracting - 100%
[P9888 12:36:57.228 deployer.go:228 I] Successfully deployed infra/depot_tools/g
it_installer/windows-amd64:aa854a934e4d7fb24cc10b5d8b6f105494e16362
[P9888 12:36:57.233 client.go:1274 I] All changes applied.
Traceback (most recent call last):
  File "E:\TBuild\Libraries\depot_tools\bootstrap\win\git_bootstrap.py", line 193, in <module>
    sys.exit(main(sys.argv[1:]))
  File "E:\TBuild\Libraries\depot_tools\bootstrap\win\git_bootstrap.py", line 185, in main
    install_git(args, git_version, git_directory)
  File "E:\TBuild\Libraries\depot_tools\bootstrap\win\git_bootstrap.py", line 115, in install_git
    '-Directory="%s"' % git_directory.replace('\\', '\\\\'),
  File "E:\TBuild\Libraries\depot_tools\bootstrap\win\git_bootstrap.py", line 26
, in _check_call
    subprocess.check_call(argv, **kwargs)
  File "E:\TBuild\Libraries\depot_tools\python276_bin\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "E:\TBuild\Libraries\depot_tools\python276_bin\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "E:\TBuild\Libraries\depot_tools\python276_bin\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "E:\TBuild\Libraries\depot_tools\python276_bin\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by jamesmoriati** [comment]
help me.

**Comment by stek29** [comment]
Disable breakpad then. There should be some define flag for that.
And please, do not create duplicate issues. The more annoying you are, the less people want to help you.
