### ISSUE TITLE
Right-click menu opens below pointer even though there is not enough space

### ISSUE THREAD

**Issue by pH142857** [telegramdesktop/tdesktop#27324]
### Steps to reproduce

1. open Telegram Desktop full-screen, or in a smaller window but near the bottom of the screen
2. right click on the lowest message of an existing conversation, so that there is not enough space below the pointer to open the right-click menu

### Expected behaviour

The right-click menu (bearing "reply", "pin", etc.) should open above the pointer in order to be visible.

### Actual behaviour

The right-click menu opens below the pointer, and is therefore not fully accessible as it opens lower than the screen bottom.

### Operating system

Debian Linux 12 GNOME 43.9 Wayland

### Version of Telegram Desktop

4.6.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by pH142857** [comment]
Static version doesn't have that problem indeed. But it is a portable version, this is not what I want on my system. I want to be able to manage it through the normal way on Linux, which is through repositories. 

What is the difference between the static version and the one in the repositories? Is it only a software version gap (the static is now 4.14.3 so that would make sense) or is there something else? 
Is the Telegram Desktop team in touch with the Debian repositories maintainers so that the repositories have a more up-to-date version? Alternatively, any plans for having a custom repository for Telegram?
