### ISSUE TITLE
Flatpak version telegram under wayland is sending unscaled cursor rectangle on scaled monitor

### ISSUE THREAD

**Issue by wengxt** [telegramdesktop/tdesktop#27321]
### Steps to reproduce

Under KDE Plasma 6, set monitor scale to 125%
WAYLAND_DEBUG=1 org.telegram.destkop 2>&1 | grep text_input
And I opened a kruler for measure the text cursor and the screen coordinates.

### Expected behaviour

 zwp_text_input_v2.set_cursor_rectangle shows local surface coordinates value

### Actual behaviour

 zwp_text_input_v2.set_cursor_rectangle shows scaled value

### Operating system

Linux

### Version of Telegram Desktop

4.14.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
isn't this under qt control?

**Comment by wengxt** [comment]
I think so but tg is the only qt app having this issue on my system.

**Comment by ilya-fedin** [comment]
Well, most Qt applications don't use QHighDpiScaling on Wayland while tdesktop does. I guess you can reproduce this with other Qt applications by setting `QT_SCALE_FACTOR` environment variable. They will be additionaly scaled by the specified scale factor but this text-input thing apparently won't. I've added you as a reviewer on the Qt gerrit for the fix but David sadly gave a -1... Maybe you will be able to pursue him.
