### ISSUE TITLE
GNU/Linux - Multimedia Player without Audio

### ISSUE THREAD

**Issue by inukaze** [telegramdesktop/tdesktop#2733]
### Steps to reproduce
1. Install Telegram
2. Open Telegram
3. Tell a contact send you a video file with audio

How i can set the default audio output device on telegram ? for try with : Pulseaudio, Alsa, OSS / OSS4, Roaraudio, Esound, aRts, etc ?

### Expected behaviour
Hear the audio from fail

### Actual behaviour
When you open, the Multimedia Player of Telegram can't reproduce Audio, just images

### Configuration
GNU/Linux : Manjaro OpenRC Xfce
GNU/Linux : Debian Jessie Stable

**Version of Telegram Desktop:**
0.10.20

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by john-preston** [comment]
@inukaze Does the audio output work in Telegram Desktop in other places? Like, when you receive a message and the notification sound should be played or if you try to play a voice message or if you try to play an .mp3 file that you've received?

**Comment by inukaze** [comment]
@john-preston : 

1 - The notifications dont have sound
2 - The mp3 dont have sound neither
3 - The video dont have sound neither
4 - The voice menssage dont have sound neither

**Comment by inukaze** [comment]
Ok i solved make the follow : 

$ pulseaudio -k
$ mv $HOME/.config/pulseaudio-ctl/config $HOME/.config/pulseaudio-ctl/config.old
$ rm -r ~/.pulse ~/.pulse-cookie ~/.config/pulse
$ pulseaudio &

Run the alsamixer, for set the volumen value to 51% to hear
$ alsamixer

Exit from telegram and run it again
Solved

The problem was the "$HOME/.pulse" from some reason, dont work fine after updates, i remove it, the system generate some new cookies for pulseaudio, and its working again.
