### ISSUE TITLE
Allow disabling Stories

### ISSUE THREAD

**Issue by levicki** [telegramdesktop/tdesktop#27339]
### Is your feature request related to a problem?

I am sure I am not the only person suffering from an OCD tied to unread message count or any other "you didn't see this" indicators in app user interfaces.

Please allow us to disable Telegram Stories feature &mdash; the icon in search bar is distracting and some of us aren't at all interested in stories be it from contacts or the Telegram itself.

### Describe the solution you'd like

 - Add an option to disable Stories in Settings

When this option is activated Stories icon would not show up in the search bar.

If you insist on having Stories in the interface for one reason or another it could be added as a separate clickable option here (blue arrow indicates where it could be inserted without being disruptive):

![image](https://github.com/telegramdesktop/tdesktop/assets/16415478/24516557-041e-43bf-9b7a-87c612f22520)

Same could be done for mobile clients as well.

### Describe alternatives you've considered

 - Compiling my custom build of Telegram (time consuming, disruptive because of update frequency)
 - Switching away from Telegram (inconvenient but not impossible)

**Comment by ilya-fedin** [comment]
#26568?

**Comment by levicki** [comment]
@ilya-fedin @Aokromes The fact that the other ticket is open 6+ months and it is still not even acknowledged by any developer while you two have jumped to close this one tells me all I need to know.

It would have been more fair to say outright you won't do it.

**Comment by levicki** [comment]
> @levicki me and Aokromes aren't a part of the team so we have no information on that. The maximum we can help in this case is managing duplicates.

Then at least mark it as a duplicate.

**Comment by ilya-fedin** [comment]
> Then at least mark it as a duplicate, not as completed.

Well, personally I can't do so

> Also, getting someone from the team to look at the other ticket would be nice.

As far as I see preston has already commented on it

**Comment by ilya-fedin** [comment]
I'm not sure this is a good place for such requests though, the people who decide won't look here as this is not an official bugtracker, at best only preston will see the request but it's not he who decides
