### ISSUE TITLE
Ctrl + Shift + 1/2/3/4...

### ISSUE THREAD

**Issue by hosseinhayati128** [telegramdesktop/tdesktop#27334]
### Steps to reproduce

in Farsi `Ctrl + shift + 2` is used to put half-space in writing some word. Recently, when I use `Ctrl + shift + 2` to use half-space in Farsi while typing, it switches between the users instead. so I have to use a full-space in the words that needs half-space. 
I think it would be better if the users could customize the shortcut-keys, specially switching users shortcut in this case.

### Expected behaviour

it should put half-space in Farsi 

### Actual behaviour

Switch the user

### Operating system

Windows

### Version of Telegram Desktop

4.14.4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
not a bug.

**Comment by Aokromes** [comment]
p.s. edit shortcuts is already a feature request.

**Comment by john-preston** [comment]
Maybe I'll have to rollback the shortcuts, because I was hoping those sequences are not used..

**Comment by alirezarezamand** [comment]
> Maybe I'll have to rollback the shortcuts, because I was hoping those sequences are not used..

Please fix this problem as soon as possible, we need to type a half space with the keyboard shortcut Ctrl + shift + 2.

**Comment by BijanProgrammer** [comment]
> not a bug.

We use this shortcut in Farsi very often. Sometimes serveral times in one sentence.

The commit 28b43ef recently added these shortcuts to switch between the user's accounts.
The least you can do is to inactivate these new shortcuts if the user doesn't have multiple accounts.
