### ISSUE TITLE
[feature req.] Make a GTK3 build

### ISSUE THREAD

**Issue by rado84-github** [telegramdesktop/tdesktop#27330]
### Is your feature request related to a problem?

Can you please make a GTK3 build of tdesktop for linux? The qt build is a huge pain in the you-know-what and the developers of qt don't even admit the existence of the problems and keep denying everything, thus leaving the problems unfixed.
Almost any program using Qt has some kind of a problem with the file choosing dialogs and tdesktop is no exception. This is tdesktop with the default option to use qt file dialogs:

![Picture_created_08-01-2024_14-08-29](https://github.com/telegramdesktop/tdesktop/assets/41172201/561c40c0-d018-4444-8d86-327bfe34d99d)

It never opens the dialog to choose a file to attach, it hangs like this for a long time and if you have enough patience to wait it out, eventually the program stops responding.
If I open qt6ct and force GTK3 file dialogs, then it takes an eternity to attach a file but at least it DOES attach it, altough you migh wait 5 minutes or longer before that happens.
Considering programs natively built with GTK3 (such as audacious-gtk3, for instance) don't have this problem, I think that you make a native GTK3 build, the described problem will disappear. I'm guessing the reason for that is because GTK3 dialog is what you see but the GTK3 dialog only translates the user-given command to Qt6 and since Qt6 is glitchy, it makes the whole process very slow.

### Describe the solution you'd like

Make a native GTK3 build of tdesktop.

### Describe alternatives you've considered

GTK3 and/or GTK4.

**Comment by ilya-fedin** [comment]
It's not just 'a build', what you're requesting is entire rewrite of tdesktop in a different toolkit and won't happen of course. What you want instead, is a different client. You can use the official web client that has an Electron version (https://github.com/Ajaxy/telegram-tt/releases/latest) or you can try an unofficial client named Telegrand that is written using GTK4 and Rust.

**Comment by ilya-fedin** [comment]
The issue you're encountering is likely could be solved by removing `~/.config/QtProject.conf`. You're likely to get a better experience by using official builds with patched Qt from https://desktop.telegram.org.

**Comment by rado84-github** [comment]
> It's not just 'a build', what you're requesting is entire rewrite of tdesktop in a different toolkit and won't happen of course. What you want instead, is a different client. You can use the official web client that has an Electron build (https://github.com/Ajaxy/telegram-tt/releases/latest) or you can try an unofficial client named Telegrand that is written using GTK4 and Rust.

Deleting that file in ~/.config did it. I wish I knew about this earlier, it would have saved me a lot of nerves and cursing at the Qt Project! :D
