### ISSUE TITLE
close chat feature

### ISSUE THREAD

**Issue by chrostino** [telegramdesktop/tdesktop#27340]
### Is your feature request related to a problem?

when you open a chat you have no way of closing it without opening another one, sometimes on desktop you leave apps like telegram open on a second monitor but don't want to read messages as soon as they get delivered

### Describe the solution you'd like

it'd be nice a solution to close the chat (not closing telegram or switching chat) like the one on whatsapp desktop, so that it brings you in a state like telegram when you just launched it but still haven't selected a chat.
maybe something just like whatsapp where you right click and have an option "close chat" in the context menu, or maybe something like a button in some corner to close the chat or a shortcut

### Describe alternatives you've considered

a workaround I use is opening the saved messages (where I won't receive messages to involuntarily read) but it's annoying looking for that chat everytime

**Comment by Aokromes** [comment]
you mean escape key?
