### ISSUE TITLE
Please provide an option for disable/enable getting new chat messages with badge about `some contact joined Telegram`

### ISSUE THREAD

**Issue by AMoktar** [telegramdesktop/tdesktop#27341]
### Is your feature request related to a problem?

I'm used to keep my notificatios clean. so I can keep uptodate with any notifications.
Actually this feature with the current situation is bad ux, it pushes users to ignore Telagram notifications at all, since it is contains unnecessary notifications .

Please guys do something about it.

Thanks for Telegram.

### Describe the solution you'd like

I'd love to have a setting option to enable/disable getting new chat about `some contact joined Telegram`

### Describe alternatives you've considered

I'm deleteing these chats manually, and that's a pain.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by AMoktar** [comment]
@Aokromes I don't have permission to create or open new issue or suggestion on https://bugs.telegram.org/
