### ISSUE TITLE
Telegram doesn't receive new messages after the laptop resumes from sleep mode

### ISSUE THREAD

**Issue by generalbytes** [telegramdesktop/tdesktop#27345]
### Steps to reproduce

1. Start Telegram Desktop app and use for one minute to send messages or what ever.
2. Close laptop's lid - computer goes into sleep mode.
3. Ask friend to send you a message (don't open it on mobile)
4. Wait 10h (for example sleep over night)
5. Open laptop lid. Operation system resumes. 
6. Login into Desktop if you have set up password requirement after resume.
7. Telegram Desktop app and all other apps are running.
8. Telegram Desktop app is forever trying to download new messages but never downloads the message from your friend.
9. Kill Telegram Desktop app
10. Open Telegram Desktop
11. Message from your friend gets downloaded and displayed.

My guess is that Telegram Desktop uses system time in some of its communication component and the big system time leap after the computer resume causes it to stop working. Probable fix should be to use uptime instead of system time.

### Expected behaviour

Telegram Desktop app should be able to download new messages after the laptop resumes from sleep.

### Actual behaviour

Telegram Desktop app is unable to download new messages or send messages after the laptop resumes from sleep.

### Operating system

Ubuntu 22.04.3 LTS

### Version of Telegram Desktop

4.11.6 09.11.23

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#16093?
