### ISSUE TITLE
Linux - Folders changes don't save after reboot

### ISSUE THREAD

**Issue by l-konov** [telegramdesktop/tdesktop#27349]
### Steps to reproduce

1. I have the chat in two folders X1 and X2. I want to remove chat from X1 folder. I remove chat via interface.
2. I reboot Telegram Desktop application.
3. After start I have the chat in two folders X1 and X2.

### Expected behaviour

Expected, that after editing the chat will be only in X2 folder.

### Actual behaviour

After editing and app restarting chat sill stay in X1 and X2 folders.

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.14.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
It is important what are the folder rules (do they include only specific chats or some chats lists, some exceptions lists etc).

So in order to fix I'd need to reproduce that. What to do, which folders to create, what to press etc? Exact steps.
