### ISSUE TITLE
Window size jitter when Default interface scale is set to 125%

### ISSUE THREAD

**Issue by CustodialMatter** [telegramdesktop/tdesktop#27348]
### Steps to reproduce

I have a Windows setup and 3 monitors, stock Telegram settings except interface scale is 125%.  I have the Windows Toolbar on auto-hide. I have Telegram's video hardware modes enabled or set to auto, etc.  

For a few Telegram versions this has been happening, regardless which monitor and whether or not I have it maximized or minimized. The interface starts to jitter by about 5-10 pixels at random times. Sometimes it happens when I'm typing, sometimes it's when I'm scrolling, and sometimes when it's idle. It's the strangest thing.

I don't know how to reproduce it, it just appears to happen at random.   I can't tell if the jitter is due to window size or because another element like the font or images or emoji are auto-resizing. Perhaps it's trying to find the bottom of the chat and can't.  Scrolling hard to the bottom and typing doesn't seem to help.

### Expected behaviour

The window margins should never automatically re-adjust

### Actual behaviour

Jitter at random times

### Operating system

Windows 11 23H2

### Version of Telegram Desktop

Telegram Desktop 4.14.4 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Please make a screen record

**Comment by CustodialMatter** [comment]
> Please make a screen record

I'd love to but I can't predict when it happens or how to reproduce it.   

I suspect it has something to do with the disappearing scroll bars. I have a ton of channels, topics, and chats.  The skinny width of the scroll bar is about the same distance as the jitter effect

**Comment by CustodialMatter** [comment]
> Please make a screen record

Here you go!

https://youtu.be/FriecaDS5cA

It appears to be related to when multiple unread images are in a feed. You can see two scrollbars appear on the right, causing the jitter

**Comment by CustodialMatter** [comment]
Update: It happens less often when I turn on Settings > Advanced > use system window frame

But the app looks the same, it doesn't show me a thick windows scrollbar, it still shows the skinny one.

**Comment by ilya-fedin** [comment]
How windows scrollbar is related?

**Comment by CustodialMatter** [comment]
> How windows scrollbar is related?

It can be seen around the 10 second part of this video.  Two scrollbars appear causing the jitter

https://youtu.be/FriecaDS5cA?feature=shared&t=13

**Comment by ilya-fedin** [comment]
Could it be that you have some modified version of Windows?
