### ISSUE TITLE
Build an older version

### ISSUE THREAD

**Issue by wxhML** [telegramdesktop/tdesktop#27347]
### Steps to reproduce

What documentation is available for v1.9.21 that I want to build

### Expected behaviour

What documentation is available for v1.9.21 that I want to build

### Actual behaviour

What documentation is available for v1.9.21 that I want to buildv

### Operating system

windows11 

### Version of Telegram Desktop

v1.9.21  0bd2d951fb74488ee23ae160d49eba977398fffb

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
That version won't connect to the servers

**Comment by wxhML** [comment]
> That version won't connect to the servers

thank you I have find method.
