### ISSUE TITLE
 Feature 'openssl-linked' was enabled, but the pre-condition '!features.securetransport && libs.openssl' failed.

### ISSUE THREAD

**Issue by wxhML** [telegramdesktop/tdesktop#27350]
Feature 'openssl-linked' was enabled, but the pre-condition '!features.securetransport && libs.openssl' failed.
            
![image](https://user-images.githubusercontent.com/18493148/296291777-11ee1e00-29de-4dfe-bd86-bfe1825e3cb4.png)

**Comment by wxhML** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/18493148/e06acd6b-e482-4b0b-9455-11eeb54541a7)
![image](https://github.com/telegramdesktop/tdesktop/assets/18493148/24481e50-2825-4bd2-a8ad-b2acf4f72268)
who help me?

**Comment by ilya-fedin** [comment]
you shouldn't call configure manually, please refer to to the build instruction

**Comment by wxhML** [comment]
> you shouldn't call configure manually, please refer to to the build instruction

I followed the reference manual every step of the way

**Comment by ilya-fedin** [comment]
The screenshot tells you're not following the instruction

**Comment by john-preston** [comment]
How did you get qt_5_12_5? The modern codebase is built with qt_5_15_12.
