### ISSUE TITLE
ERROR: Feature 'openssl-linked' was enabled, but the pre-condition '!features.securetransport && libs.openssl' failed

### ISSUE THREAD

**Issue by wxhML** [telegramdesktop/tdesktop#27354]
> you shouldn't call configure manually, please refer to to the build instruction

I followed the reference manual every step of the way
![image](https://user-images.githubusercontent.com/18493148/296405925-6f64d871-5941-4b6d-a9e9-62ac5031832b.png)

_Originally posted by @wxhML in https://github.com/telegramdesktop/tdesktop/issues/27350#issuecomment-1890254912_

**Comment by john-preston** [comment]
This doesn't happen if you call configure in tdesktop/Telegram folder.

**Comment by wxhML** [comment]
> This doesn't happen if you call configure in tdesktop/Telegram folder.

I don't think so ,This step is according to the official configuration, but it is not yet to the step you said

**Comment by c0re100** [comment]
Probably, he is trying to build an older version of tdesktop.
https://github.com/telegramdesktop/tdesktop/issues/27347

**Comment by wxhML** [comment]
> Probably, he is trying to build an older version of tdesktop. #27347

yean the older version is v1.9.21

**Comment by john-preston** [comment]
This is not going to be investigated, you're on your own, sorry.

**Comment by wxhML** [comment]
> This is not going to be investigated, you're on your own, sorry.

I've already solved this problem.
