### ISSUE TITLE
Feature - Record voice message without holding the button

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#2735]
**Feature**

### Steps to reproduce
1. Start record a voice message
2. Release

### Expected behaviour
The user will be able to press and start recording a voice message, without the need to press the button while recording.
It can be very comfortable and useful for recording a message which is more than 5 seconds long, playing music and send the recording to a friend etc.

### Actual behaviour
The user need to keep holding the record button while recording.

### Configuration
**Operating system:** WIndows 10
**Version of Telegram Desktop:** 0.10.20

___

*Additional things:*
* Is there an issue template for features? It seems that the template is mostly for bugs
* It would be great if you'll also offer that to the developers of the android version (maybe it can be in sharing music - start recording)

**Comment by stek29** [comment]
#1060 covers this
