### ISSUE TITLE
Feature request : deleting telegram messages you sent in chats you are no longer a part of

### ISSUE THREAD

**Issue by MarArMar** [telegramdesktop/tdesktop#27356]
### Is your feature request related to a problem?

I would like to clean up my Telegram account and delete my messages in chats I am no longer a part of

### Describe the solution you'd like

Maybe a button in the settings "Delete my messages in chats I am no longer a part of" and select those or simple delete all

### Describe alternatives you've considered

Deleting the whole account, but it does not delete the messages, it only says "Deleted account"

### Additional context

Thank you for considering this feature

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
