### ISSUE TITLE
crash after playing one-time video message

### ISSUE THREAD

**Issue by DMJWorld** [telegramdesktop/tdesktop#27368]
### Steps to reproduce

1. view all the video message
2. crash

### Expected behaviour

no crash

### Actual behaviour

no crash

### Operating system

windows 10

### Version of Telegram Desktop

4.14.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by john-preston** [comment]
I hope this one is fixed by https://github.com/telegramdesktop/tdesktop/commit/5033b9ef0dde7d763ab955babcf9e51c913e3029

Please check the next 4.14.6 version that'll be available within an hour.
