### ISSUE TITLE
The "Play once" pop-up does not disappear

### ISSUE THREAD

**Issue by TBXin** [telegramdesktop/tdesktop#27369]
### Steps to reproduce

1. Start typing a message after using reply in a super chat

### Expected behaviour

Nothing happened

### Actual behaviour

Pop-up shows on a weird place and do
![111](https://github.com/telegramdesktop/tdesktop/assets/1242348/257ee88f-1a50-47c4-b73e-4fa9883c1b9d)
es not dissapears

### Operating system

Windows 11 22H2

### Version of Telegram Desktop

4.14.5

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I hope this one is fixed by https://github.com/telegramdesktop/tdesktop/commit/83fc19e14371beaad865371e7c0e79ea7e7a6374

Please check the next 4.14.6 version that'll be available within an hour.

**Comment by TBXin** [comment]
> I hope this one is fixed by [83fc19e](https://github.com/telegramdesktop/tdesktop/commit/83fc19e14371beaad865371e7c0e79ea7e7a6374)
> 
> Please check the next 4.14.6 version that'll be available within an hour.

Thanks for quick fix. So far no annoying pop-up.
