### ISSUE TITLE
Bug about channel file multi-selection download file issue

### ISSUE THREAD

**Issue by dev-yangyang** [telegramdesktop/tdesktop#27361]
### Steps to reproduce

1.View channel file
2.Select multiple videos, or select multiple audio
3.Click the right mouse button to pop up the menu

### Expected behaviour

In the past, there was an option to download the selected video or audio at the same time when viewing the channel information file, but now it can only download the single file that the mouse cursor hovers over at this time. If you don't understand what I mean, you can understand that in the normal chat window, select the audio file, and then select several more, at this time, you can download the audio together by downloading the selected file Instead of only downloading one. I remember that this function was available before, but now I can't find it. I tried to use the previous version, but the 2.x version can't be used anymore, and other versions can't find this function. I don't know because this function has started to charge, or it no longer provides this function, or it is a BUG?

### Actual behaviour

Only one can be downloaded now

### Operating system

Windows

### Version of Telegram Desktop

4.10

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
works for me (TM) last time tried yesterday on 4.14.4

**Comment by dev-yangyang** [comment]
> 对我有用 （TM） 上次在 4.14.4 上尝试
For example, if I select these files, the right mouse button menu I want to have a download selected instead of save as, because save as can only download one file, not the target I selected.
![image](https://github.com/telegramdesktop/tdesktop/assets/26545780/b8a92068-01df-44c1-8500-af6082678e82)
What I want is something like a chat window
![image](https://github.com/telegramdesktop/tdesktop/assets/26545780/5c70c79d-93c2-4d81-b894-240608a71755)
Put it this way, do you understand?

**Comment by dev-yangyang** [comment]
Did I not make it clear enough?

**Comment by Aokromes** [comment]
then it's not a bug what you have instead want a feature.

**Comment by dev-yangyang** [comment]
ok, I say it's a bug because it was in the previous version and it's not in the current version.

I'm sorry, but why is this function gone?

@Aokromes

**Comment by ilya-fedin** [comment]
#26866

**Comment by dev-yangyang** [comment]
I'm pretty sure the previous version had this feature because I've used it before. But now this feature is really not found. But I don't know why

@Aokromes

**Comment by john-preston** [comment]
@dev-yangyang I think you're mistaken. There is no trace of such context menu item in the shared media section code.

**Comment by ilya-fedin** [comment]
I think it's a dup of #26866

**Comment by dev-yangyang** [comment]
No, I'm sure I've used this feature before, because I've downloaded thousands of videos from a channel to my hard drive, and I can't have downloaded them with a single click, but I remember that the button that was selected for download was not in the right-click menu, but instead there was a vertical three-dot button next to the forward button in the upper right corner. Perhaps there are some plug-ins that can do this? You know what?

@john-preston @Aokromes

**Comment by ilya-fedin** [comment]
@dev-yangyang can you finally check #26866 and say whether it's the same as your issue?

**Comment by dev-yangyang** [comment]
No, not really, his problem was selecting audio messages in the chat screen, while mine was selecting audio messages when viewing channel files.
![image](https://github.com/telegramdesktop/tdesktop/assets/26545780/36e5d6e3-92b2-4b02-afd3-a052da497414)


@ilya-fedin

**Comment by ilya-fedin** [comment]
@dev-yangyang have you really read the issue? both issues are describing files download in media section

**Comment by dev-yangyang** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/26545780/c7ed4f02-e604-40fc-acec-12b6f20f1235)
Of course, I have seen it, unfortunately we are not talking about the same situation, we understand that, looking at the image, I now want to download the audio I have selected to the hard drive with one click, and no matter how many I select, the download button of the menu can only download the file that I am now cursor over.

@ilya-fedin
