### ISSUE TITLE
Automatic Removal of Share IDs from Shared Links on Telegram

### ISSUE THREAD

**Issue by alir32aa** [telegramdesktop/tdesktop#27362]
### Is your feature request related to a problem?

 this feature addresses a privacy concern. When users share links from platforms like Facebook and YouTube, these URLs often contain unique tracking IDs. These IDs can be used to trace the link back to the original sharer, potentially compromising their privacy. Users may not always be aware of this or know how to manually remove these IDs.

### Describe the solution you'd like

The proposed solution is the integration of an automatic feature in Telegram that detects and removes tracking IDs (such as share IDs) from links shared within the app. This feature would ideally work with popular platforms like Facebook and YouTube initially. When a user copies a link into Telegram, the app should automatically detect and strip any tracking parameters from the URL, making the shared link 'untrackable' and preserving the user's privacy.

### Describe alternatives you've considered

As alternatives, users could manually remove tracking parameters from URLs before sharing, though this requires technical knowledge and is not user-friendly. Another alternative could be by showing a warning that the link is customized for the user.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
