### ISSUE TITLE
Voice Messages - Change input device in settings do not work

### ISSUE THREAD

**Issue by last-vampire** [telegramdesktop/tdesktop#27377]
### Steps to reproduce

I found an old tread 'Voice Messages - Change input device in settings' created 5 years ago. I see problem still axist.
Is it really so hard to add mic replacement for voice messages? It's funny but only system changes take affect but all other programs suffer from it.

### Expected behaviour

Please make existing mic change option to take affect on voice messages too.

### Actual behaviour

When I change mic in call settings nothing happens. 

### Operating system

win10

### Version of Telegram Desktop

4.14

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
There's no option to change input device for voice messages.

**Comment by john-preston** [comment]
Btw now you can change mic used for the voice message recording.
