### ISSUE TITLE
selecting one track/file among a "group sent" with holding the mouse click

### ISSUE THREAD

**Issue by Aphotic** [telegramdesktop/tdesktop#27372]
### Is your feature request related to a problem?

selecting one music track among a group sent tracks takes so much time on Desktop cus when you click a group of mp3s/files sent telegram desktop selects the whole group on android you can just hold your touch on the wanted track to select only that track among grouped tracks sent.
![image](https://github.com/telegramdesktop/tdesktop/assets/30921064/7f641290-dab8-4991-90f4-7ce8a4709815)

### Describe the solution you'd like

allow holding mouse click on the pointed track to be the only selected and not the whole group msg sent, just do what telegram android does.  

### Describe alternatives you've considered

as above

**Comment by Aokromes** [comment]
right click -> select
