### ISSUE TITLE
telegram desktop on ubuntu with x11 takes a lot of time to launch

### ISSUE THREAD

**Issue by dimisjim** [telegramdesktop/tdesktop#27376]
### Steps to reproduce

installed via snap on linux ubuntu 22.04 using X11

problem persists for the past month or so. It takes almost half a minute to launch properly (within this time, the system asks to force quit or wait for it). Previously it was launching in a second or 2

tried it on a desktop with an nvidia card (driver: [545.29.06](https://www.nvidia.com/Download/driverResults.aspx/216530/en-us/)) and a laptop with onboard graphics, if that info helps, and ~the behavior is the same~. I am not experiencing this issue on the non-nvidia laptop.

currently using version 4.14.6

### Expected behaviour

for it to work as before

### Actual behaviour

see above

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.14.6

### Installation source

Snap

**Comment by ilya-fedin** [comment]
I can't reproduce. Please prepare a VM image where this is reproducible.

**Comment by lindy2076** [comment]
I had a similar problem. I had modified my `.xinitrc` and it took almost half a minute to launch any gtk-based app.
Try to copy the content of `/etc/X11/xinit/xinitrc` into your `.xinitrc` and see if it helps.

**Comment by dimisjim** [comment]
@lindy2076 I didn't manually modify my .xinitrc file. It could be that the nvidia driver did however. Right now I am not experiencing this issue on the non-nvidia laptop.

**Comment by kjvona** [comment]
Had the same problem, it was resolved by disabling the "Enable OpenGL rendering for media" from the Advanced settings. Also using nvidia card.

**Comment by ilya-fedin** [comment]
NVIDIA itself could be cause because it's proprietary and buggy. I'd recommend avoid using it.

**Comment by dimisjim** [comment]
>it was resolved by disabling the "Enable OpenGL rendering for media" from the Advanced settings. Also using nvidia card.

will try out and update the issue as soon as I can, thanks

>NVIDIA itself could be cause because it's proprietary and buggy. I'd recommend avoid using it.

not an option, as I already have the card and it is necessary for it to work as best as it can

**Comment by ilya-fedin** [comment]
> not an option, as I already have the card and it is necessary for it to work as best as it can

No one here can do anything either to help you because the driver is proprietary and no developer has a NVIDIA system.

**Comment by dimisjim** [comment]
Which driver would you recommend?

**Comment by ilya-fedin** [comment]
I'd recommend to replace the card ;)
But nouveau is the only alternative I guess. That wouldn't matter after disabling OpenGL in settings, though.

**Comment by dimisjim** [comment]
Yup disabling "Enable OpenGL rendering for media" in advanced settings fixed it
