### ISSUE TITLE
When Viewing a Group with Channels, "Tap to set this message to Play Once" Tooltip Appears and won't Disappear

### ISSUE THREAD

**Issue by BoffinBrain** [telegramdesktop/tdesktop#27371]
### Steps to reproduce

View a group chat that has multiple channels. (You may need to switch to a different channel once or twice for the issue to appear).

### Expected behaviour

N/A

### Actual behaviour

In the chat header, a tooltip "Tap to set this message to Play Once" appears that doesn't point to any relevant toolbar button.

The tooltip will only go away if you switch back to another chat, but will reappear when viewing the group chat with channels.

The position of the tooltip will remain a fixed offset from the left hand side if you resize the window.

The issue is consistently reproducible after a restart and only appeared after today's update, so it's probably a new regression.

![Screenshot 1](https://github.com/telegramdesktop/tdesktop/assets/13255058/e448a04e-afc0-4586-806d-7a2d06fcb8f6)

![Screenshot 2](https://github.com/telegramdesktop/tdesktop/assets/13255058/b69ea5d1-01b3-4e10-a548-7b8791856a6c)

### Operating system

Windows 10

### Version of Telegram Desktop

4.14.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
update

**Comment by BoffinBrain** [comment]
> update

That seems to have fixed it!

I'm not sure why had to force it to check for updates when it auto-updated a couple of hours ago, but 4.14.6 is there now.
