### ISSUE TITLE
Cannot disable monochrome tray icon on Linux

### ISSUE THREAD

**Issue by UlyssesZh** [telegramdesktop/tdesktop#27373]
### Steps to reproduce

Open Telegram desktop on Linux, look at advanced settings.

### Expected behaviour

There is a checkbox to disable monochrome icon.

### Actual behaviour

No such checkbox.

### Operating system

NixOS 23.11

### Version of Telegram Desktop

4.14.4

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
On Linux, there's no monochrome icon feature, it's just whatever is provided by your system icon theme. If you don't like the icon in your icon theme, you have to edit or replace it.
