### ISSUE TITLE
Window minimal size works wrong when resize in split screen mode

### ISSUE THREAD

**Issue by b-kamalov-diginavis** [telegramdesktop/tdesktop#27378]
### Steps to reproduce

1. Open Telegram in split screen mode with other app
2. Resize Telegram to minimal size
[Запись экрана от 2024-01-17 17-49-20.webm](https://github.com/telegramdesktop/tdesktop/assets/84175904/9f86e72d-20aa-497b-bbf3-0a00ba7df131)

### Expected behaviour

Telegram doesn't let other app to move above Telegram

### Actual behaviour

Telegram lets other app to overlap Telegram app

### Operating system

Fedora Linux

### Version of Telegram Desktop

4.14.5

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
This looks like a GNOME bug

**Comment by b-kamalov-diginavis** [comment]
> This looks like a GNOME bug

Is it? Are there any other apps with this behaviour?

**Comment by b-kamalov-diginavis** [comment]
The bug has appeared somewhere in between 4.8.1 and 4.8.3

@ilya-fedin @Aokromes I don't think that this is the GNOME bug

https://github.com/telegramdesktop/tdesktop/assets/84175904/7cf63d08-ee8b-4444-832d-6dce4b9f0fb9

**Comment by ilya-fedin** [comment]
> Is it? Are there any other apps with this behaviour?

Other Qt 6 applications perhaps? GNOME is known to do everything for Qt applications to work buggy.

> The bug has appeared somewhere in between 4.8.1 and 4.8.3

Apparently a Qt update?

**Comment by b-kamalov-diginavis** [comment]
> Apparently a Qt update?

I created an issue for QT and they said that it could be already fixed in QT 6.7. Can you make testing build with recent QT to see if it will be fixed after update?

https://bugreports.qt.io/browse/QTBUG-121381

>This may already be fixed by https://codereview.qt-project.org/c/qt/qtwayland/+/524982
>
>Could you please re-test with a recent Qt 6.7 snapshot or the second beta once that is released?

**Comment by ilya-fedin** [comment]
Sorry but I won't. If they removed the forcing of the minimum size then it's going to be a regression for tdesktop because QWidget has API promise that it couldn't be less than minimum size and tdesktop relies on that

**Comment by b-kamalov-diginavis** [comment]
> If they removed the forcing of the minimum size then it's going to be a regression for tdesktop because QWidget has API promise that it couldn't be less than minimum size and tdesktop relies on that.

Looks like now it will be done with xdg-shell/qt-shell (I don't know what it means)

**Comment by ilya-fedin** [comment]
This means it's no longer forced. If your compositor properly inherits the hints the nothing will be changed for you. If it doesn't, you will be able to resize it smaller than currently but you will have graphical artifacts or crashes.

**Comment by ilya-fedin** [comment]
This logic is 10 years old so I'm very doubt it's the cause. The issue looks to me like GNOME bugs due to some valid but unexpected thing like a different order of requests than gtk does.

**Comment by ilya-fedin** [comment]
I did a report that they break the API promise with the commit. Hopefully it will be reverted or tdesktop is going to be crashy on Linux again.

**Comment by b-kamalov-diginavis** [comment]
> I did a report that they break the API promise with the commit. Hopefully it will be reverted or tdesktop is going to be crashy on Linux again.

Can you share the link to issue so I could monitor how the process is going?

**Comment by ilya-fedin** [comment]
https://bugreports.qt.io/browse/QTBUG-121445
