### ISSUE TITLE
Сlipboard not working in MiniApps

### ISSUE THREAD

**Issue by BaHeK1994** [telegramdesktop/tdesktop#27381]
### Steps to reproduce

1. Open mini app
2. Select text
3. Press CTRL+C or Right mouse button -> Copy

### Expected behaviour

The selected text is not copied to the clipboard

### Actual behaviour

The text should be copied to the clipboard

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.14.6

### Installation source

Static binary from official website

**Comment by Dimoka113** [comment]
I'll assume that you meant that:
Expected behaviour - The text should be copied to the clipboard
Actual behaviour - The selected text is not copied to the clipboard

**Comment by ilya-fedin** [comment]
#26150
