### ISSUE TITLE
under Fedora 38, XfCe4 window manager (also under GNOME) , font size is too small. Please honor <CTRL>+<SHIFT>+<+/-> to Zoom.

### ISSUE THREAD

**Issue by JVD66** [telegramdesktop/tdesktop#27386]
### Steps to reproduce

1. Install Telegram Desktop from :
    $ repoquery telegram-desktop --qf '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH} %{REPONAME} %{BUILDTIME} %{PACKAGER}'
    telegram-desktop-4.8.4-4.fc38.x86_64 rpmfusion-free-updates 2023-12-12 14:21 RPM Fusion

2. Start it up

Fonts are too small : 

![image](https://github.com/telegramdesktop/tdesktop/assets/9722004/215569ae-c269-4114-98da-a58dc2773485)

### Expected behaviour

My display is 3840x2160 pixels (1016x571 millimeters) - my default font sizes for all fonts in:
 o xfwm4-tweaks, xfce4-composite-editor, xfce4-settings / Appearance is 18pt .
 This is the minimum font size I can read on this display.
 
 But Telegram displays in a tiny (@ 10pt ?) font size, under XfCe4, Enlightenment, or GNOME  - it is too difficult to read.
 
 XDG conformant apps should respond to the \<CTRL\>\+\<SHIFT\>\+\<\+\/\-\> keystrokes to increase / decrease the Zoom,
 or size of Fonts and/or Images.
 
 Please add a Font / Image Zoom feature to Telegram Desktop - thanks! 

### Actual behaviour

Telegram displays in too small font size, very difficult to read.

### Operating system

Linux (6.6.8) Fedora Core 38, XFCE4 and / or GNOME and / or Enlightenment

### Version of Telegram Desktop

4.8.4-4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
you are using fedora package not official telegram desktop package.
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
> XDG conformant apps should respond to the <CTRL>+<SHIFT>+<+/-> keystrokes to increase / decrease the Zoom,
> or size of Fonts and/or Images.

Please refer to the document saying that

**Comment by ilya-fedin** [comment]
This sounds like a dup of #16986
