### ISSUE TITLE
issue with showing last seen times for premium users

### ISSUE THREAD

**Issue by ashkanhasebi** [telegramdesktop/tdesktop#27383]
### Steps to reproduce

When viewing a user's profile

### Expected behaviour

Show last seen times of other users for premium users like version 4.14.7

### Actual behaviour

After the update from version 4.14.7 to 4.14.8, it has returned to the previous where it was not possible to see last seen times.

### Operating system

Windows 11

### Version of Telegram Desktop

4.14.8

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/f53b64bc72cd9feab26594ea2b0c9fac4fda3ffb
