### ISSUE TITLE
Option to view photos and videos in windowed mode instead of full screen

### ISSUE THREAD

**Issue by sepsol** [telegramdesktop/tdesktop#27388]
### Is your feature request related to a problem?

I use Telegram for my work and I sometimes receive personal photos on Telegram that I wish to quickly enlarge and glance at without making them full screen. The current built-in photo viewer/video player opens everything in full screen which is annoying.

### Describe the solution you'd like

I would like an option in the settings to be able to open media in windowed mode, either inside the current Telegram chat window (like Unigram on Windows) or at least as a separate window which not full screen. 

Alternatively, if both options mentioned can be added so that the user has 3 choices to choose from it'd be perfect.

### Describe alternatives you've considered

1. Slouching, moving my eyes closer to the screen, and squinting to see the image :)
2. Closing the official Telegram client and opening Unigram to see the picture and then closing Unigram and opening back the official Telegram client to respond
3. Right-clicking on the media, choosing "Save as...", choosing a location, opening File Explorer, navigating to the location, finding and opening the media, deleting the media, and finally coming back to the Telegram screen to respond and explain why I took so long :)
4. Stepping away from my keyboard, pulling up my phone (sometimes unplugging it from the charger), seeing the picture, putting down my phone and coming back to the keyboard to respond

### Additional context

As you can see, it is really inconvenient to view personal media while at work. I have looked at every setting and experimental feature, I have also searched through GitHub issues and found #1710 and https://github.com/telegramdesktop/tdesktop/commit/5d9383b8e4fe33cdb706a4f50cce1aff146ad0b2 but they don't seem to address my issue directly.

**Comment by Aokromes** [comment]
such thing is possible for years if you remove the maximize, telegram will open future photos on non full screen.

**Comment by sepsol** [comment]
@Aokromes that's perfect! I was not aware that such a feature existed for years then :) Could please give more clear instructions? I cannot locate the "maximize" option in the settings.
