### ISSUE TITLE
Bot keyboard not seen while reply mode is active

### ISSUE THREAD

**Issue by baryshev** [telegramdesktop/tdesktop#2738]
### Steps to reproduce
1. Open dialog with any bot that have reply keyboard. I'm testing with [@JournalistBot](https://telegram.me/JournalistBot)
2. Send any message to bot
3. Try to reply to this message (reply to bot messages works fine)

### Expected behaviour
Bot reply keyboard must be visible.

### Actual behaviour
Bot reply keyboard invisible.

### Configuration
**Operating system:** Windows 10, MacOS 10.12.1

**Version of Telegram Desktop:** 0.10.20

**Comment by auchri** [comment]
Same as on android.

**Comment by baryshev** [comment]
@auchri Can you explain why it closed?

**Comment by stek29** [comment]
@baryshev Isn't it clear? :)
> Same as on android

**Comment by baryshev** [comment]
@stek29 android version has the same bug. iOS and macOS versions works as well. Web client allow to send message from keyboard while reply mode is active, but reply is not applied. Looks like absolutely inconsistent behavior. It's not clear why it's closed without fix.

**Comment by stek29** [comment]
I'm pretty sure that there's a bug in iOS and macOS versions, because Android/TDesktop behaviour seems logically correct.
Keyboard sent by bot should be used with bot only, what's the point to use it with your own or other user's message?

Or let's imagine situation when there are two bots in chat. What should we do if user tries to reply to one bot while other bot's keyboard is active?

**Comment by baryshev** [comment]
@stek29 I think that group chat is a bad example here. If more than one bot with keyboard are in the same chat - they are trying to redefine the keyboards of each other. This behavior seems broken at all. But it's important how it works in one-to-one chat with bot. Because reply with keyboard - good solution to 'do something' with message. In my case - i use it for deletion (because bots can't handle native deletes) and changing type of messages.

Typical use case in iOS/macOS client:
1. Double tap on my message
2. Tap on keyboard (`Delete` or `Set type` buttons)

It's much faster and simpler than typing `/delete` command. And it's looks like more native for users.

And i can't see any reasons to prevent this behavior at least at private chats.

**Comment by john-preston** [comment]
@baryshev Well, currently the keyboard is a property of a message. So most consistent way when you reply to a message is to show the keyboard of the message you reply to. The keyboards for the outgoing messages were not supposed at all. Perhaps this could be done for outgoing messages (no idea why would you reply your own message in a regular life anyway), but I would like to avoid such an unclear logic.

**Comment by baryshev** [comment]
@john-preston 

> no idea why would you reply your own message in a regular life anyway

Example.
My bot [@JournalistBot](https://telegram.me/JournalistBot) allow users to create text broadcasts like this: http://journali.st/broadcasts/933756417

User sent messages to bot and bot add it to the broadcast. If user wants to edit message - he just used telegram native edit. But if user want to delete **self message** from the broadcast in iOS and macOS he can double tap on self message and than tap to Delete button (from bot Keyboard). In android and windows desktop user need to init reply dialog and type `/delete` command. Which is more complicated.

I understand your logic about keyboard as message property but bot keyborads can do more and provide application like UX.
