### ISSUE TITLE
No tray icon

### ISSUE THREAD

**Issue by MarvelWild** [telegramdesktop/tdesktop#27385]
### Steps to reproduce

no exact steps - happens randomly

### Expected behaviour

tray icon visible

### Actual behaviour

no tray icon
![tg_bug_tray_icon](https://github.com/telegramdesktop/tdesktop/assets/7306230/0db109c4-f946-4680-861e-0f359dca3608)

### Operating system

windows 10 Version 10.0.19045 Build 19045

### Version of Telegram Desktop

4.14.8

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
check windows tray settings if you have forced hide it.

**Comment by MarvelWild** [comment]
![tg_win](https://github.com/telegramdesktop/tdesktop/assets/7306230/f122d2c2-f500-4ef3-b62b-aa4a0ffa45b8)

It happens randomly, if i kill telegram process, and restart it, icon reappears.
Other apps are fine.
