### ISSUE TITLE
New version (10.6.258588 AppStore) hangs MacBook Pro M1

### ISSUE THREAD

**Issue by MihaelIsaev** [telegramdesktop/tdesktop#27398]
### Steps to reproduce

1. Join group video chat call
2. Macbook will hang completely (only hard restart helps)

### Expected behaviour

Shouldn't affect operating system at all

### Actual behaviour

Completely hangs operating system

### Operating system

macOS Sonoma 14.2.1 (23C71)

### Version of Telegram Desktop

10.6.258588

### Installation source

Mac App Store

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
