### ISSUE TITLE
Telegram mini App doesn't support any layout without QWERTY

### ISSUE THREAD

**Issue by MrBns** [telegramdesktop/tdesktop#27399]
### Steps to reproduce

I am using DVORAK keyboard layout in linux (ubuntu 23.10). I was trying telegram mini app feature.. and I created on.  but problem is that when I typed something..  in my DVORAK keybord  `o` is placed where `s` is in Qwerty keyboard.. and if I try something following DVORAK keyboard it start giving result according to  QWERTY keyboard.. I think its a bug.. 

### Expected behaviour

I want if I type `o` in dvorak keyboard I should get `o` .. not  `s` ..
I should get every keyresult according to that keyboard which one I am using...  please don't force us to use QWERTY. 

### Actual behaviour

I am typing in DVORAK keyboard but getting result according to QWERTY keyboard.

### Operating system

ubuntu (23.10)  - GNOME desktop environment.

### Version of Telegram Desktop

4.14.9

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Yes, sadly it's a [QtWaylandCompositor restriction](https://bugreports.qt.io/browse/QTBUG-74473)...
