### ISSUE TITLE
Request: Ubuntu ARM Release?

### ISSUE THREAD

**Issue by gappleto97** [telegramdesktop/tdesktop#2739]
I would love it if you could compile a version under Ubuntu ARM for easy download. I'm willing to try setting it up on my image if you'd like.

**Comment by thexbasic** [comment]
There is a version for Linux, which includes Ubuntu - I am even running it on my 16.04 laptop.
Its also linked on the main-page: https://desktop.telegram.org/
just click "Show all platforms »" download, extract and execute it.
Not sure why you would go through the trouble and open an issue on the git page... but whatever

**Comment by gappleto97** [comment]
There is no build released for ARM architectures, so that release cannot be installed on Ubuntu ARM

**Comment by stek29** [comment]
#1924 ?

**Comment by gappleto97** [comment]
I'll close then. Did not see that this was a duplicate after searching for "ARM" in issues. Just consider this a +1 for that issue then.

**Comment by stek29** [comment]
@gappleto97  use githhub reactions :)
