### ISSUE TITLE
Launching Telegram Desktop (Failed) the name is not activatable

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#27394]
### Steps to reproduce

On Manjaro Linux:
1. I installed the Flatpak from https://flathub.org/apps/org.telegram.desktop
2. I went to the start menu, and in the Search box I typed "Telegram". The option "Telegram Desktop" showed up, with the Telegram icon.
3. I clicked it

### Expected behaviour

should launch Telegram desktop

### Actual behaviour

This error shows up:

![image](https://github.com/telegramdesktop/tdesktop/assets/13969584/66e8eb2f-5f42-451a-ae6b-322309f70424)

I can launch it from a terminal with "flatpak run org.telegram.desktop", but that's annoying.

### Operating system

Manjaro Linux

### Version of Telegram Desktop

4.14.9

### Installation source

Flatpak

**Comment by php4fan** [comment]
After reboot it works as expected. This might be an issue in Flatpak. Telegram is the only app I have installed so far.

**Comment by ilya-fedin** [comment]
Yes, it's likely flatpak paths just were not set up before you rebooted
