### ISSUE TITLE
Make deb and rpm packages

### ISSUE THREAD

**Issue by kartavenko1983** [telegramdesktop/tdesktop#27396]
### Is your feature request related to a problem?

Please make deb and rpm packages

### Describe the solution you'd like

It would be more convenient to install the application, moreover, with the parameters that are necessary for its operation. I know about the snap and flathub versions, but not everyone likes to use them.

### Describe alternatives you've considered

It would be more convenient to install the application, moreover, with the parameters that are necessary for its operation. I know about the snap and flathub versions, but not everyone likes to use them.

**Comment by ilya-fedin** [comment]
If you don't like snap or flatpak, you have static binary option. Creating deb/rpm sounds like multiplying the efforts for no real reason.

**Comment by kartavenko1983** [comment]
That's what we do

**Comment by ilya-fedin** [comment]
@kartavenko1983 I'm not sure what you mean

**Comment by kartavenko1983** [comment]
I mean, we use a static binary

**Comment by ilya-fedin** [comment]
Nice, just continue to use it. A package won't five you any improvement, rather the other way, you will loss automatic updates.

**Comment by kartavenko1983** [comment]
well, thank you
