### ISSUE TITLE
[Feature Request] Seperated contactlist and conversations

### ISSUE THREAD

**Issue by kocane** [telegramdesktop/tdesktop#274]
I think something that'd add alot to this awesome piece of software would be the ability to seperate the contactlist from conversations so a more classic IM feel could be added back. 

That along with the possiblity of making new messages pop up the chat windows, optionally as minimized, so it's more clear when someone writes you. I hide all tray icons in my Windows 7 to keep a clean look and thus it's hard for me to tell if someone writes unless I would use the popups which frankly are a tad too much

Just some humble suggestions

Thanks and keep up the great work

**Comment by jgiak92** [comment]
+1

**Comment by davho** [comment]
+1

**Comment by auchri** [comment]
They are separated now

**Comment by Kocayine** [comment]
As of current version (because I dont see that) or a future version?

**Comment by auchri** [comment]
current version

**Comment by Kocayine** [comment]
How do you seperate them?

**Comment by auchri** [comment]
The are separated by default (look release notes: https://desktop.telegram.org/#v-0-8-48-stable-08-08-15)

**Comment by Kocayine** [comment]
I feel a bit like an idiot because maybe I'm missing something but are we talking about the same kind of "seperation"? 

I'm thinking like this: http://i.imgur.com/TH9Spqg.jpg

In other words; very much like the original IM apps like Skype, WLM etc. I understand if this is maybe a bit too astray from the way the program is designed.

**Comment by auchri** [comment]
Oh, you mean separate windows

**Comment by Darktemp** [comment]
+1
Oh yes, please :)
I find it very useful to be able to place chat windows of specific persons separately from the main window and it enables to read in multiple chats at once without switching the tab.

**Comment by Aokromes** [comment]
Posted generic suggestion on https://github.com/telegramdesktop/tdesktop/issues/242

**Comment by Aokromes** [comment]
Maybe this can be changed to how some other applications works where you can move things from one place to another even make floating.
Example: i.imgur.com/RPmoUjP.png
infragistics.com/samples/WebImages/windows-forms/Controls/dock-manager/windows-forms-dock-manager-dockable-and-floating-windows-en-us.png

woboq.com/blog/qdockwidget-changes-in-56.html it looks soo good.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2105
