### ISSUE TITLE
Downloads get placed in temp directory

### ISSUE THREAD

**Issue by ZVNexus** [telegramdesktop/tdesktop#27409]
### Steps to reproduce

Click on downloadable file

### Expected behaviour

File gets placed in downloads folder

### Actual behaviour

File ends up in weird path that normal users cannot access

### Operating system

Fedora 39

### Version of Telegram Desktop

4.14.9

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
It's intended behavior, data directory is the only directory accessible in flatpak sandbox

**Comment by ZVNexus** [comment]
> It's intended behavior, data directory is the only directory accessible in flatpak sandbox

The user is not informed of where the sandbox is, if they just open file explorer, none of the folders they are shown are where TG is saving downloads. It's inside a hidden folder which is awful UX. Please reconsider this choice, no normal user is going to have any idea where the picture they just saved is.

**Comment by ilya-fedin** [comment]
> Please reconsider this choice

The thing is there's no choice. That's the only accessible folder and that's it. 

> if they just open file explorer

They can use "Show in folder" menu item.

**Comment by ZVNexus** [comment]
> The thing is there's no choice. That's the only accessible folder and that's it.

There is though? You can easily provide the xdg-download permission in the flatpak yaml. That's what every sane app does.

> They can use "Show in folder" menu item.

That's only if the user is still in the app, and knows that context option exists. The default user response to downloading a file is to open Files and check Downloads.

**Comment by ilya-fedin** [comment]
> There is though? You can easily provide the xdg-download permission in the flatpak yaml. That's what every sane app does.

It's a sandbox hole, so I guess such a change would be rejected by the co-maintainer from the flathub community. And, well, this will lower the level of application security promoted by the application stores like flathub website or gnome software.

> That's only if the user is still in the app, and knows that context option exists. The default user response to downloading a file is to open Files and check Downloads.

I'm not sure you're right. Right clicking on the file is a established UX to do something about the file.

**Comment by ilya-fedin** [comment]
I think if you truly believe that there should be a way for flatpak applications to silently have access to downloads folder without doing sandbox holes (and that's the only intended way for flatpak applications to behave), you should create an issue at flatpak repository to ask for new API. Right now flatpak applications can get access to a folder via the intended APIs only by presenting a file chooser dialog and the use have to pick up the folder to give the access to it.

**Comment by ilya-fedin** [comment]
As far as I know snap wants to get a similar move and make the home plug privileged so the snap package is likely to lose download folder acess suddenly as well.

**Comment by ilya-fedin** [comment]
The Android client seem to have a similar behavior: you don't know where it downloads by default and you have to an analogue of 'save as' to save the file to a visible folder.

**Comment by ZVNexus** [comment]
> (and that's the only intended way for flatpak applications to behave)

Except it's not, there's very detailed documentation on how to do this:
https://docs.flatpak.org/en/latest/sandbox-permissions.html
https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html

It's up to each app to make judgement calls on what makes sense and what doesn't for their app. In the case of apps that handle downloads, granted permission to XDG download folder makes complete sense. Reference the Discord & Slack flatpaks that do this.

I understand that having a complete sandbox is appealing, but in the real world at the moment, it's not feasible. User experience should be prioritized over literally anything else, but we shouldn't be making UX worse in the name of security.

I do agree that giving complete access to the home folder is *not* the way, but just downloads? That's fine IMO.

**Comment by ilya-fedin** [comment]
> Except it's not, there's very detailed documentation on how to do this:
> https://docs.flatpak.org/en/latest/sandbox-permissions.html
> https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html

It's documentation and it explains the technical possibilities of flatpak. What are the intended ways is more a political question and the `--filesystem` permissions are treated as sandbox holes by the community. That's unwritten rules that you won't find documentation for probably but likely can ask about on the flatpak IRC or Matrix.

> It's up to each app to make judgement calls on what makes sense and what doesn't for their app.

There are third party people in the package maintainership from the flatpak project. They will likely reject the PR.

> In the case of apps that handle downloads, granted permission to XDG download folder makes complete sense.

The policy is that it's acceptable only if the application can't handle the access to those directories via portal. tdesktop can so it won't be granted.

> Reference the Discord & Slack flatpaks that do this.

Discord & Slack use Electron so they don't support the portal and have massive sandbox holes.

> I do agree that giving complete access to the home folder is _not_ the way, but just downloads?

ANY `--filesystem` access will mark tdesktop as potentially unsafe.
