### ISSUE TITLE
Telegram not see audio interfaces which was plugged after Telegram launch

### ISSUE THREAD

**Issue by NTMan** [telegramdesktop/tdesktop#27403]
### Steps to reproduce

1. Launch Telegram
2. Paring bluetooth headset or connect external audio interface

![Screenshot from 2024-01-26 13-15-10](https://github.com/telegramdesktop/tdesktop/assets/200750/83c52872-593b-4e14-b798-8731ec08ea35)

### Expected behaviour

Sound present in headset then I listen sound in Telegram

### Actual behaviour

No sound until Telegram restarted

### Operating system

Linux Fedora Rawhide (Pipewire)

### Version of Telegram Desktop

4.14.11 beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Yeah, that's unlikely to be solved because the cross-platform audio library tdesktop uses doesn't provide a way to get device list updates and there's no one with the knowledge of Linux native audio APIs. That's something you have to get used to if you don't plan to help with the implementation.

**Comment by kartavenko1983** [comment]
@ilya-fedin,  yes, the node version 4.11 is beta, everything worked correctly

**Comment by ilya-fedin** [comment]
@kartavenko1983 node version?

**Comment by ilya-fedin** [comment]
The thing is it doesn't anymore and chances that it would be fixed before stable release (or at all) are liw because there's no one to fix the bug

**Comment by kartavenko1983** [comment]
@ilya-fedin Are your people running away? Is there no one to work?

**Comment by ilya-fedin** [comment]
@kartavenko1983 tdesktop's paid developers work on linux support in spare time (linux is not of interest for business due to low market share), their spare time is little and Linux support was almost non-existent before 2020 when I started vlounteering (it was launching but with lots of bugs and unimplemented features). I'm the only person volunteering for Linux support from outside but I don't have an idea how to fix this because I have no experience with Linux audio APIs. And the paid developers too, as far as I know. So unless someone else with pipewire/pulseaudio/alsa knowledge would volunteer, the bug is likely to become a long standing one.

**Comment by kartavenko1983** [comment]
@ilya-fedin Let's see how events will develop. But, interestingly, if the telegram is restarted, then the audio interfaces are picked up, and if they are disconnected and connected again, then the telegram continues to work correctly.

**Comment by ilya-fedin** [comment]
> But, interestingly, if the telegram is restarted, then the audio interfaces are picked up, and if they are disconnected and connected again, then the telegram continues to work correctly.

This sounds expected to me. The audio device is closed when there's nothing to play so as long as the system can open it again, it will work.

**Comment by kartavenko1983** [comment]
@ilya-fedin I see, thanks. Here is another open problem on a similar topic.

#27421 https://github.com/telegramdesktop/tdesktop/issues/27421

**Comment by ilya-fedin** [comment]
Why did you create a duplicate if you see there's already an issue?

**Comment by kartavenko1983** [comment]
@ilya-fedin I saw this topic later than I opened a new one.

**Comment by ilya-fedin** [comment]
but you can close it now

**Comment by NTMan** [comment]
Most annoying thing that with "Default" input/output device Telegram not have sound after connected new headset.
The fact that you cannot select a specific device in the telegram itself is not such a necessary function as the absence of sound as such.

**Comment by kartavenko1983** [comment]
@NTMan You can turn on playback or make a call, and then connect the headset, then the sound will appear. Or restart the telegram after turning on the headset.

**Comment by ilya-fedin** [comment]
> Most annoying thing that with "Default" input/output device Telegram not have sound after connected new headset.

Yeah, it should be simpler to fix just that but there's a conflict between Windows/macOS and Linux behaviors here. So I'm not sure I will get a permission to do that and a fully involved fix will then be needed to implement the same code as for Windows/macOS (what I can't do as already explained)

**Comment by john-preston** [comment]
@NTMan @kartavenko1983 @VladimirMrzv Please check the released 4.14.12 version, I hope it works as before or better.

**Comment by kartavenko1983** [comment]
@john-preston, @ilya-fedin, Yes, everything is working correctly, thank you very much

**Comment by NTMan** [comment]
@john-preston Almost perfect, it would be perfect if devices appear and disappear without re-opening the window on fly.

[Demonstration](https://github.com/telegramdesktop/tdesktop/assets/200750/8436fe52-b5b1-4d04-8381-bf3de23b2f99)

**Comment by alba4k** [comment]
I came to report a different issue, which I suppose is related? The notification sound always plays on the device that was default when telegram was opened

Example: I open telegram. I connect my bt headphones. A notification arrives. The sound still plays on the laptop speakers.

I'm not sure whether I should open a different issue for this? for context, I'm using Hyprland on Arch Linux, and PipeWire

**Comment by ilya-fedin** [comment]
@alba4k update to the latest version, it should already be fixed to the previous state

**Comment by cox88** [comment]
Investing can be a great way to grow your wealth, but it is important to do your due diligence and research before entrusting your money to any platform. Always read the fine print and be wary of promises that seem too good to be true. Remember, if something seems too good to be true, it probably is. In conclusion, while optvalltd
![best 2](https://github.com/telegramdesktop/tdesktop/assets/161655434/8eda9ee6-16ae-48b5-b71c-0de13bed4f28)
![best 2](https://github.com/telegramdesktop/tdesktop/assets/161655434/abc06eaa-cacf-4bb2-8c8f-671975e36517)
 may seem like a great platform to invest with, it is important to be cautious and do your research before investing any money. If you do decide to invest with them, make sure to keep a close eye on your investments and be prepared to take action if anything seems amiss. And if you do find yourself in a situation like mine, don't hesitate to seek help from professionals who can assist you in recovering your lost funds , fusionforensics.tech , to check if you can get a relief I strongly recommend to everyone!
I was able to take action and get instant change after I involved
f u s i o n  f o r e n s i c s. t e c h

**Comment by alba4k** [comment]
yeah this can be closed I believe

also idk what that thing is ^^^^

**Comment by Aokromes** [comment]
> yeah this can be closed I believe
> 
> also idk what that thing is ^^^^

spam.

**Comment by kartavenko1983** [comment]
@ilya-fedin please delete the spam

**Comment by ilya-fedin** [comment]
@kartavenko1983 I can't
