### ISSUE TITLE
Media shows on wrong monitor

### ISSUE THREAD

**Issue by fristhon** [telegramdesktop/tdesktop#27400]
### Steps to reproduce

1. Connect a separate monitor to your laptop
2. Move tdesktop to second monitor and open a media there

This problem has been around for a long time and is so bothering. I have to watch Telegram media in the laptop small monitor instead of the bigger one 😑
somehow like #5126

### Expected behaviour

Media shows on the second monitor

### Actual behaviour

Media opens in laptop monitor

### Operating system

Windows 10.0.19045 Build 19045

### Version of Telegram Desktop

4.14.9 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Are you sure you have a bug? There's an intended behavior when if you switch the viewer to windowed mode and back, it remembers the screen so you can move it to another screen.
