### ISSUE TITLE
Resetting Telegram settings in Windows restart

### ISSUE THREAD

**Issue by o-OHamiD** [telegramdesktop/tdesktop#27401]
### Steps to reproduce

Restart the Windows or Telegram app.

### Expected behaviour

Actually nothing!

### Actual behaviour

Settings reset, like notification settings, recent emoji, some advanced settings, proxy list and settings, chat settings, etc. It doesn't happen all the time or for all settings, sometimes only monochrome icon, sometimes only notifications, sometimes all of them.

What I tried:
disabling and enabling some settings
reinstalling Telegram
It did not help.

### Operating system

Windows 11 pro 23H2

### Version of Telegram Desktop

4.14.9 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@o-OHamiD Please try updating to beta 4.14.10.

**Comment by o-OHamiD** [comment]
> @o-OHamiD Please try updating to beta 4.14.10.

This problem should not be solved in the non-beta version?

**Comment by o-OHamiD** [comment]
> @o-OHamiD Well, for now please tell me if it's fixed in beta for you.

Yes, it doesn't seem to happen anymore (still hasn't after a few restarts)
