### ISSUE TITLE
Fucking internal error +37529537XXX2 [Fucking telegram support????]

### ISSUE THREAD

**Issue by KarKarKarKarkarkar** [telegramdesktop/tdesktop#27411]
### Steps to reproduce

1. Got internal error when try to login
2. Try contact with fucking recover@telegram.org abuse@telegram.org support@telegram.org pavel@telegram.org from mailru/gmailcom/website multiple times
3. Got nothing responsive

### Expected behaviour

Contact with telegram support for recovery account

### Actual behaviour

Fucking telegram support????

### Operating system

Android 10

**Comment by KarKarKarKarkarkar** [comment]
@svenstaro @kenvandine @jhasse @alexandernst 

I got Internal Error when trying to login using Android 10 phone. Fucking telegram support??  Not answering my emails....

**Comment by Aokromes** [comment]
this is telegram desktop BUG TRACKER not telegram support, we cannot help you and even less if your problem is with ANDROID.

**Comment by KarKarKarKarkarkar** [comment]
No official android app repository in GitHub? :( Very bad telegram support. No replies to emails:(

**Comment by Aokromes** [comment]
> No official android app repository in GitHub? :( Very bad telegram support. No replies to emails:(

even if there is one android app repository the issue will be the same, it's application bug report, not platform user issues.

**Comment by KarKarKarKarkarkar** [comment]
> > No official android app repository in GitHub? :( Very bad telegram support. No replies to emails:(
> 
> even if there is one android app repository the issue will be the same, it's application bug report, not platform user issues.

This is application error "Sorry. Internal error." write when I trying login

**Comment by KarKarKarKarkarkar** [comment]
no answering from fucking telegram support team...:(

**Comment by KarKarKarKarkarkar** [comment]
@jhasse @kenvandine @svenstaro @Aokromes fucking internal error now replaced to 'already logged in' error. But I not logged in... I cant contact with support by emails/from telegramorg/support page and even via X personal messages....where is fucking technical support team ?

**Comment by Aokromes** [comment]
not here.
