### ISSUE TITLE
URGENT TELEGRAM SUPPORT NOT RESPONDING

### ISSUE THREAD

**Issue by someteleguy** [telegramdesktop/tdesktop#27415]
### Steps to reproduce

I checked my telegram in the morning on my phone and everything was fine; and then after work I checked it again via my laptop and suddenly I was kicked out of both of my numbers and it said the numbers were banned. I thought it was a computer error but it kicked me out on my phone too. I have no reason to be banned as I have not engaged in any public activities or done anything bad. I only talked to my friends and nothing has happened lately. This is URGENT because there's someone I talk to on there that has a life or death situation and because of this problem and me having trouble contacting them, the personal problems we are having is even worse. This happened days ago and I've emailed Telegram 4 times already via website support and the help button and the email when it gives the banned message. To make things worse, I created a group including only myself and used it as storage but if I lose all of what I had in there because of this that will be terrible. I think this might be a glitch. I did delete my account in order to get away from a stalker once and since some of my friends hadn't been online yet I just texted them to follow my other account and then deleted it. So I wonder if they didn't know it was me and reported the account for that? But I doubt it. I have no other idea of why this would happen. I need to get back in that account yesterday!

### Expected behaviour

Telegram support responding

### Actual behaviour

Failed to respond after several days.

### Operating system

Windows 11 + Android

### Version of Telegram Desktop

unsure

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
sorry but this is telegram desktop BUG TRACKER not a support channel.
