### ISSUE TITLE
Picture-Viewer stays open when local passcode timeout's

### ISSUE THREAD

**Issue by thexbasic** [telegramdesktop/tdesktop#2742]
### Steps to reproduce
1. Setup local passcode (e.g. 1 minute)
2. Open a picture in a chat (Telegram viewer)
3. Wait for Telegram to "lock"

### Expected behaviour
The viewer should close/not allow further viewing.

### Actual behaviour
You can continue to scroll through media and save it.
Which might be a potential security/privacy leak.

### Configuration
Running: Windows 10 Pro
Telegram Desktop: v0.10.20 alpha

### Logs
No need, is there?

**Comment by john-preston** [comment]
@thexbasic Thank you for your report! This will be fixed in the next version.
