### ISSUE TITLE
Please allow adding to folder from the current chat

### ISSUE THREAD

**Issue by danielalejandroamaro** [telegramdesktop/tdesktop#27425]
### Is your feature request related to a problem?

Nop

### Describe the solution you'd like

Please allow adding to folder from the current chat. It can be done from the list of groups/channels/contacts but not from the open chat. It's very useful and requires minimal changes. It also doesn't allow it from the search.

### Describe alternatives you've considered

![image](https://github.com/telegramdesktop/tdesktop/assets/26387903/b55426cb-c206-40f5-9a68-910af7002f8c)
![image](https://github.com/telegramdesktop/tdesktop/assets/26387903/13d2ba82-7068-46d2-91cf-05a919f53806)
![image](https://github.com/telegramdesktop/tdesktop/assets/26387903/8a1c1835-6c23-4d17-bd4c-aaa31de7ef04)

**Comment by enchained** [comment]
That would be a really useful feature. Currently, if a channel recommends you another channel and you open it, you have to manually find it in the list to assign to a folder.

**Comment by 23rd** [comment]
Please check the v5.9.0.

**Comment by danielalejandroamaro** [comment]
i love it 😍
