### ISSUE TITLE
Stuck at "Exchanging encryption keys"

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#27429]
### Steps to reproduce

Make/Receive a voice/video call

### Expected behaviour

Make the call

### Actual behaviour

Stuck at `Exchanging encryption keys` stage

### Operating system

Linux Mint 21.3

### Version of Telegram Desktop

4.14.9

### Installation source

Flatpak

### Logs

```shell
$ flatpak info --show-permissions org.telegram.desktop
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;
devices=all;
filesystems=/home/laptop/Downloads;xdg-run/pipewire-0;/usr/share/themes;
persistent=.TelegramMine;
unset-environment=QT_PLUGIN_PATH;

[Session Bus Policy]
org.kde.StatusNotifierWatcher=talk
org.gnome.Mutter.IdleMonitor=talk
org.ayatana.indicator.application=talk
com.canonical.AppMenu.Registrar=talk
com.canonical.indicator.application=talk

[Environment]
GTK_THEME=Mint-Y-Dark-Aqua
QT_PLUGIN_PATH=
PATH=/app/lib/webview/bin:/app/bin:/usr/bin
QT_STYLE_OVERRIDE=Adwaita-dark
```

**Comment by mbnoimi** [comment]
BTW, This issue occurs since a while but recently I no longer able to receive any call anymore. So I use Android client instead until fixing this issue.

**Comment by ilya-fedin** [comment]
#27365

**Comment by john-preston** [comment]
@mbnoimi Please try out 4.14.12 version released earlier today. I hope calls work there fine (the other end should also have updated TDesktop or one of mobile apps).

**Comment by mbnoimi** [comment]
> @mbnoimi Please try out 4.14.12 version released earlier today. I hope calls work there fine (the other end should also have updated TDesktop or one of mobile apps).

Thank you guys.

Flatpak version is still on 4.14.9 so I think I've to wait for a couple of hours
