### ISSUE TITLE
Some Unicode symbols aren't displayed in the headers or messages

### ISSUE THREAD

**Issue by surpscare** [telegramdesktop/tdesktop#27432]
### Steps to reproduce

1. Fresh installation of Windows 10 Pro
2. Fresh installation of Telegram Desktop
3. Try to find any chat or username containing symbols like Ꮳ Ꭲ Ꭽ Ꮎ or Ꮙ or any other from similar Unicode range, or send them in the message

### Expected behaviour

Expected to display symbols as is, or with rectangles if they are missing
![Screenshot_20240201-153345_Telegram](https://github.com/telegramdesktop/tdesktop/assets/63161216/1c3241c2-f6cb-4e33-8bbb-ca31bc081a1b)
Older Telegram instance (with all updates though) on another machine with Windows 10 Home, also displays them as should.
![image_2024-02-01_15-37-14](https://github.com/telegramdesktop/tdesktop/assets/63161216/01924e4a-5feb-4f48-a39d-b575b942c422)

### Actual behaviour

Symbols are displayed just as spaces
![image](https://github.com/telegramdesktop/tdesktop/assets/63161216/f34ff6b2-898a-4b2d-af52-cc933f4e7ea6)

### Operating system

Windows 10 Pro 22H2 19045.3930

### Version of Telegram Desktop

4.14.9

### Installation source

Static binary from official website

**Comment by Magprone** [comment]
teahouse teahouse teahouse teahouse teahouse

**Comment by ilya-fedin** [comment]
The font resolution is done by the underlying toolkit (Qt). If Qt can't render the fonts, nothing could be done, this kind of code is not under tdesktop control.

**Comment by Aokromes** [comment]
windows 10 fails, but windows 11 shows properly, very likely missing fonts.

**Comment by Aokromes** [comment]
p.s. qbittorrent also fails to show, edge chromium works

https://i.imgur.com/P7srwGW.png

**Comment by ilya-fedin** [comment]
Oh, that means that's Qt classics: it just tries all the fonts in alphabetical order and some font claims to support those glyphs but has them invisible.

**Comment by ilya-fedin** [comment]
I can work around this by patching Qt and adding the intended font to the CJK priority list of fallback fonts is someone will tell what that font is.
