### ISSUE TITLE
Build process causes out of memory issues

### ISSUE THREAD

**Issue by mondalaci** [telegramdesktop/tdesktop#27434]
### Steps to reproduce

Follow the [build instructions for Linux using Docker](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md).

### Expected behaviour

My desktop stays responsive during the build process.

### Actual behaviour

The build process forks numerous `cc1plus` processes, roughly matching the 32 threads of my Intel Core i9-14900K CPU. During the build, my system's 32G RAM gets exhausted, and the desktop becomes unresponsive. Due to the lack of memory, the kernel kills processes, such as Chrome or, occasionally, the window manager, and I get thrown back to the login screen of the display manager.

How can I make the build process not make my system unresponsive and crash processes?

### Operating system

Linux Mint 21.3

### Version of Telegram Desktop

git master

### Installation source

Other (unofficial) source

**Comment by c0re100** [comment]
Maybe you can try docker with `--memory=16g`, limit container max memory.

**Comment by ilya-fedin** [comment]
> Maybe you can try docker with `--memory=16g`, limit container max memory.

This would make the OOM killer just do its work earlier. The right way is to limit the CPU count so ninja uses less jobs and so less memory.

> `./tdesktop/Telegram/build/prepare/linux.sh` also exhibits such issues, but it doesn't seem to accept any argument. Any ideas?

Do the commands from the script manually?

**Comment by c0re100** [comment]
> > Maybe you can try docker with `--memory=16g`, limit container max memory.
> 
> This would make the OOM killer just do its job earlier. The right way is to limit the CPU count so ninja uses less jobs and so less memory.
> 
Ah, you're right.
14900K have 24c/32t, it may uses around 30GB RAM :|
`--cpus=8` should be safe.

**Comment by Aokromes** [comment]
preston got 64GB of ram for such cpu.

**Comment by mondalaci** [comment]
Do both of the affected build commands respect `--cpus=8`?
- ./tdesktop/Telegram/build/prepare/linux.sh
- docker run --rm -it -v $PWD:/usr/src/tdesktop tdesktop:centos_env /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb

**Comment by ilya-fedin** [comment]
Only the latter

**Comment by ilya-fedin** [comment]
No, without improving the scripts there's no solution. Personally I don't need this so it's unlikely I will work on this.

Perhaps you can try workarounds like limiting docker itself via systemd or run docker inside lxd container with limited cpu.

**Comment by mondalaci** [comment]
In the meantime, I've upgraded to 64G RAM, and the build succeeded without any hiccups.

The size of the resulting `out/Release/Telegram` binary became monstrously large: 1915M. Is it normal? Any way to make it reasonably-sized?

When running the binary, I get `./Telegram: symbol lookup error: ./Telegram: undefined symbol: g_app_info_get_default_for_type_async`. Would you please help with this?

**Comment by mondalaci** [comment]
> > Is it normal?
> 
> I'd say it's small. Official builds are like ~4GB before stripping.

Thanks for the hint! `strip Telegram` shrank the binary to 222M, which is quite an improvement. If there are other ways to shrink it even more, please let me know.

> > When running the binary, I get `./Telegram: symbol lookup error: ./Telegram: undefined symbol: g_app_info_get_default_for_type_async`.
> 
> Read the instruction carefully, especially the last lines.

I tried to follow the https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md instructions as closely as possible. I used the following commands:

```
git clone --recursive https://github.com/telegramdesktop/tdesktop.git
./tdesktop/Telegram/build/prepare/linux.sh
cd tdesktop
docker run --rm -it -v $PWD:/usr/src/tdesktop tdesktop:centos_env /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb
```

What have I missed?

**Comment by ilya-fedin** [comment]
> What have I missed?

The backward compatibility note at the end of the instruction

> `strip Telegram` shrank the binary to 222M, which is quite an improvement. If there are other ways to shrink it even more, please let me know.

It should be `strip -s Telegram`

**Comment by mondalaci** [comment]
Thanks for the help regarding `strip -s`, although the `-s` argument doesn't seem to make any difference.

I wouldn't have thought that I needed a backward-compatible binary because I'm using the latest Linux Mint version, but I've just used the `-D CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON` argument and got the following error:

```
/usr/src/Libraries/openal-soft/alc/panning.cpp: In function ‘InitDistanceComp’:
/usr/src/Libraries/openal-soft/alc/panning.cpp:71: warning: inlining failed in call to ‘GetLabelFromChannel’: --param inline-unit-growth limit reached [-Winline]
/usr/src/Libraries/openal-soft/alc/panning.cpp:280: note: called from here
/usr/src/Libraries/openal-soft/alc/panning.cpp:71: warning: inlining failed in call to ‘GetLabelFromChannel’: --param inline-unit-growth limit reached [-Winline]
/usr/src/Libraries/openal-soft/alc/panning.cpp:288: note: called from here
/usr/src/Libraries/openal-soft/alc/panning.cpp:71: warning: inlining failed in call to ‘GetLabelFromChannel’: --param inline-unit-growth limit reached [-Winline]
/usr/src/Libraries/openal-soft/alc/panning.cpp:288: note: called from here
In function ‘operator<’,
    inlined from ‘operator()’ at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_function.h:408:0,
    inlined from ‘_M_lower_bound’ at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_tree.h:1951:0,
    inlined from ‘lower_bound’ at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_tree.h:1270:0,
    inlined from ‘lower_bound’ at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_map.h:1307:0,
    inlined from ‘insert_or_assign’ at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_map.h:968:0,
    inlined from ‘insert’ at /usr/local/desktop-app/Qt-6.6.1/include/QtCore/qmap.h:692:0,
    inlined from ‘insert’ at /usr/src/tdesktop/Telegram/lib_base/base/ordered_set.h:133:0,
    inlined from ‘ReplaceValueInPaletteContent’ at /usr/src/tdesktop/Telegram/SourceFiles/window/themes/window_theme_editor.cpp:321:0:
/usr/local/desktop-app/Qt-6.6.1/include/QtCore/qlatin1stringview.h:257: warning: ‘memcmp’ specified bound [9223372036854775808, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Wstringop-overread]
  257 |         const int r = len ? memcmp(s1.latin1(), s2.latin1(), len) : 0;
      | 
In member function ‘latin1’,
    inlined from ‘operator<’ at /usr/local/desktop-app/Qt-6.6.1/include/QtCore/qlatin1stringview.h:257:0,
    inlined from ‘operator()’ at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_function.h:408:0,
    inlined from ‘_M_lower_bound’ at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_tree.h:1951:0,
    inlined from ‘lower_bound’ at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_tree.h:1270:0,
    inlined from ‘lower_bound’ at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_map.h:1307:0,
    inlined from ‘insert_or_assign’ at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_map.h:968:0,
    inlined from ‘insert’ at /usr/local/desktop-app/Qt-6.6.1/include/QtCore/qmap.h:692:0,
    inlined from ‘insert’ at /usr/src/tdesktop/Telegram/lib_base/base/ordered_set.h:133:0,
    inlined from ‘ReplaceValueInPaletteContent’ at /usr/src/tdesktop/Telegram/SourceFiles/window/themes/window_theme_editor.cpp:321:0:
/usr/local/desktop-app/Qt-6.6.1/include/QtCore/qlatin1stringview.h:60: note: source object allocated here
   60 |     constexpr const char *latin1() const noexcept { return m_data; }
      | 
```

How can I make the build succeed?

**Comment by ilya-fedin** [comment]
> I'm using the latest Linux Mint version

As far as I'm aware it's based on Ubuntu LTS and latest Ubuntu LTS is almost 2 years old as of today.

> How can I make the build succeed?

The output looks like it succeeded. I see only warnings and notes, no errors.

**Comment by mondalaci** [comment]
> > How can I make the build succeed?
> 
> The output looks like it succeeded. I see only warnings and notes, no errors.

Indeed, sorry for the oversight!

Thanks so much for your help! Closing this issue.
