### ISSUE TITLE
Sound is not restarted if pulseaudio/pipewire is restarted

### ISSUE THREAD

**Issue by perezmeyer** [telegramdesktop/tdesktop#27438]
### Steps to reproduce

Debian testing or unstable. Run `systemctl --user restart pipewire pipewire-pulse`, then Telegram no longer has access to audio.

### Expected behaviour

Telegram should detect the change and restart the audio. FWIW everything else on my system "just works".

### Actual behaviour

No audio is produced, mic does not records audio.

### Operating system

Debian testing and unstable

### Version of Telegram Desktop

4.14.9+ds-1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
tdesktop uses high level API of the https://github.com/kcat/openal-soft library. It doesn't have raw access to pulseaudio or pipewire and can't know that.
