### ISSUE TITLE
Monochrome Tray Icon Support for Telegram Flatpak (LINUX)

### ISSUE THREAD

**Issue by Raul1198** [telegramdesktop/tdesktop#27437]
### Is your feature request related to a problem?

on windows there is an option for having a monochrome tray icon which is not available on flatpak

### Describe the solution you'd like

option to change tray icon to monochrome availabe on telegram flatpak

### Describe alternatives you've considered

none

### Additional context

having monochrome tray icon make telegram tray icon (using AppIndicator gnome extension) match/unified with gnome monochrome quick settings icons

**Comment by ilya-fedin** [comment]
That's sadly not possible because Linux has no API to request whether the tray host has white or dark background unlike Windows or macOS.
