### ISSUE TITLE
The payment failed

### ISSUE THREAD

**Issue by AlphaHot** [telegramdesktop/tdesktop#27445]
### Steps to reproduce

![image](https://github.com/telegramdesktop/tdesktop/assets/58410019/4b51b74a-245b-4b00-b470-ae14935e8141)

### Expected behaviour

Buy Telegram Premium.

### Actual behaviour

WebView has crashed. The purchase failed.

### Operating system

Linux, Ubuntu

### Version of Telegram Desktop

4.14.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#25928
