### ISSUE TITLE
Copy / paste does not work in webapps

### ISSUE THREAD

**Issue by Viiprogrammer** [telegramdesktop/tdesktop#27444]
### Steps to reproduce

1. Open web app
2. Try to copy from other app and paste to web app or copy from web app and paste to other app

https://github.com/telegramdesktop/tdesktop/assets/17622604/834dfd07-a3f6-42c4-ab46-85e961e66801

### Expected behaviour

nothing happened

### Actual behaviour

Copy / paste works fine

### Operating system

Ubuntu 22.04.3 LTS x86_64

### Version of Telegram Desktop

4.14.13

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#26150
