### ISSUE TITLE
The WebApp does not use the system keyboard language.

### ISSUE THREAD

**Issue by Viiprogrammer** [telegramdesktop/tdesktop#27442]
### Steps to reproduce

1. Open any webapp
2. Type some text when Russian lang active

https://github.com/telegramdesktop/tdesktop/assets/17622604/c185f429-c165-4bd8-9c0a-dba93c9b8845

### Expected behaviour

Russian keyboard used

### Actual behaviour

Prints English characters

### Operating system

Ubuntu 22.04.3 LTS x86_64

### Version of Telegram Desktop

4.14.13

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#27399
