### ISSUE TITLE
Adding Other Person's Timezone or Current Day/Time in Profile or Chat Screen

### ISSUE THREAD

**Issue by mrahimygk** [telegramdesktop/tdesktop#27447]
### Is your feature request related to a problem?

No it is just a feature request

### Describe the solution you'd like

It would be best to see the day/time of the person I am chatting with. Maybe only when I see their bio, or even in front of their name in chat screen

### Describe alternatives you've considered

I just added another clock for them in my OS

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
