### ISSUE TITLE
Copying text from Telegram Desktop doesn't work

### ISSUE THREAD

**Issue by stdedos** [telegramdesktop/tdesktop#27440]
### Steps to reproduce

Copy using the right click
Using Ctrl+C on the "message" textbox

### Expected behaviour

Text is copied to clipboard

### Actual behaviour

Clipboard is emptied

### Operating system

Microsoft Windows [Version 10.0.18363.836]

### Version of Telegram Desktop

4.14.13

### Installation source

Static binary from official website

**Comment by stdedos** [comment]
Similar to https://github.com/telegramdesktop/tdesktop/issues/25851

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by stdedos** [comment]
Great, I am happy for you 🙃 

Can I/we ... debug somehow? 😅

**Comment by ilya-fedin** [comment]
Do you want to build tdesktop from source code? If not, you can't debug on your machine and in order for developers to debug, you have to find what you missed in the steps to reproduce so they can reproduce and debug on their machines.

**Comment by ilya-fedin** [comment]
The issue might be cause by some third party software installed on your computer so I recommend to reproduce in a freshly created virtual machine

**Comment by stdedos** [comment]
> Do you want to build tdesktop from source code? If not, you can't debug on your machine ... 

I don't know how possible would that be... 

I've never built anything on Windows before - I wouldn't know where to start. 

Isn't there any debugs to activate? Is there some kind of "console" with errors / stacktraces / etc? 

> The issue might be cause by some third party software installed on your computer so I recommend to reproduce in a freshly created virtual machine

Yes, that is possible. ... It is the "everyday Windows machine" after all 😅 
Lots of software exists. 

Never has anyone told me "Ctrl+C is not working? Ah, 'some other software might be the problem'"

**Comment by ilya-fedin** [comment]
> Is there some kind of "console" with errors / stacktraces / etc?

Such console is a part of the Visual Studio IDE. You would have to build tdesktop from source code to use it. Although it might be useless if there's no error nor crash.

> Yes, that is possible.

That might be the missing thing in steps to reproduce. I really recommend to do a fresh installation and find what one has do on top on it to reproduce the issue.
