### ISSUE TITLE
Telegram does not start in minimized form at system startup

### ISSUE THREAD

**Issue by AlexanderShad** [telegramdesktop/tdesktop#27451]
### Steps to reproduce

1. Go to "Settings"
2. "Advanced settings"
3. check the box "Launch Telegram at system startup"
4. check the box "Run minimized"
5. reboot

### Expected behaviour

When the system starts, Telegram should be loaded into the tray, but not open as a window.

### Actual behaviour

When the system starts, Telegram starts, but does not minimize to the system tray. The "Run minimized" checkbox does not work.

### Operating system

ALT Linux Regular Sisyphus x86_64

### Version of Telegram Desktop

4.14.4

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Sorry but I can't confirm your issue. Perhaps something is missing in steps to reproduce or your distro is bugged.

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
Yes, I can't reproduce the behavior you described in my testing VM. I set the minimized checkbox an it starts minimized.

**Comment by AlexanderShad** [comment]
It's clear. I'll write it in the Alt Linux bugzilla

**Comment by ilya-fedin** [comment]
It might be an issue with your system, e.g. maybe you have enabled Telegram to autostart by other means, now it starts multiple times what leads to the window being opened, just like when you open already running instance with applications menu.

**Comment by AlexanderShad** [comment]
At the moment, I got around this situation on wayland in the following way.
added the telegram.desktop file to $HOME/.config/autotart
with the following content

#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Name=Telegram
NoDisplay=true
Comment=telegram on sys trey
Exec=telegram -startintray
Terminal=false

At the same time, the autorun and tray launch checkboxes are disabled

**Comment by ilya-fedin** [comment]
Looks like I reproduced
