### ISSUE TITLE
Can't react to a specific photo in an album

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#27457]
### Steps to reproduce

1. Send (or have someone send) an album (i.e. media group) to a group
2. try to react to the n-th photo with n > 1

### Expected behaviour

you should be able to.
For example, by hovering on any of the photos in the album, just like you can react to the first one by hovering on the message text (which technically is the caption of the first photo in the group). Or by right-clicking on the specific photo.

### Actual behaviour

You can only react to the "main message", which actually is the first photo.
Hovering on any of the other photos, the reaction options don't show up.
By right-clicking on any photo, you have the option to react which misleadingly looks exactly as if you were reacting to that specific photo, but instead you are reacting to the main message, i.e. always the first photo.

The mobile app has exactly the same issue. It's probably by design but it's a flawed design.

### Operating system

Manjaro Linux

### Version of Telegram Desktop

4.14.12

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
> The mobile app has exactly the same issue. It's probably by design but it's a flawed design.

There's `Platform-wide issue` item for such issues when creating issue

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
