### ISSUE TITLE
I would like to mention message deleting options in both personal and group chats.

### ISSUE THREAD

**Issue by Barzy-Yasin** [telegramdesktop/tdesktop#27452]
### Is your feature request related to a problem?

the problem is both participants are able to delete any message they want, including the other one message chats!

### Describe the solution you'd like

my preferred solution is everyone only be able to delete their own messages.

### Describe alternatives you've considered

because, now i can delete my friend's message for both of us.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by Aokromes** [comment]
but this request will be very likely rejected.

**Comment by Barzy-Yasin** [comment]
@Aokromes  i'm sorry, could you tell me why?

**Comment by Aokromes** [comment]
because it's intended on the way it's currently working.

**Comment by Barzy-Yasin** [comment]
oh, I didn't know that. Thanks.
