### ISSUE TITLE
[feat. req.] Microphone boost

### ISSUE THREAD

**Issue by rado84-github** [telegramdesktop/tdesktop#27456]
### Is your feature request related to a problem?

When I call someone using the Google's Phone app, they can hear me just fine. But if I call them on telegram, they can barely hear me and I have to shove my face into the phone and yell in the hopes that they can hear me. The same problem applies to telegram-desktop for linux, even when the microphone is next to my mouth.
There must be something you can do to boost the microphone or better yet - add a slider with that function in the program's settings.
This is probably a bug but I can't provide much more information about it, that's why I decided to put it as a feature request.

### Describe the solution you'd like

Either add a slider in settings with microphone boost or another way where we can adjust the boost levels.

### Describe alternatives you've considered

The only "solution" that has worked so far was running Windows in a VM (because Windows already has a slider for microphone boost), install telegram in it and call my friends through the VM. But that's a bit excessive, if you ask me, considering there's a native linux app which can get the slider in question. Also, I can't take the VM with me to the outside world.

**Comment by ilya-fedin** [comment]
Perhaps that's something to examine with your DE? KDE has an option to set more than 100% to both output and input.

**Comment by rado84-github** [comment]
> Perhaps that's something to examine with your DE? KDE has an option to set more than 100% to both output and input.

I suppose I can boost it on the desktop version but that doesn't change the fact that people can't hear much of me when I call them via the Android telegram. Unlike linux and windows, Android doesn't offer much on the matter and external apps to boost things only make things worse, which I thought I should ask for a native boost from within the app.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
