### ISSUE TITLE
Spambot false positives, indiscriminate banning users

### ISSUE THREAD

**Issue by MrPenguin07** [telegramdesktop/tdesktop#27458]
### Steps to reproduce

1. Forward post from one group to another. In this case a harmless meme. First attempt to forward could see it didn't post to the group, I thought that's odd, so after ~30secs attempted again. BAM instant ban.
2. Confirmed with destination group owner did not report/enable spam settings.
3. Get banned for 2 days
4. Interact with spambot, spot the obvious lie "I’m afraid some Telegram users found your messages annoying and forwarded them to our team of moderators for inspection. The moderators have confirmed the report and your account is now limited until 10 Feb 2024"

Yes this is an obvious lie. I guarantee I have not been reported, nor a moderator having confirmed it.

5. Marvel at the options;
![image](https://github.com/telegramdesktop/tdesktop/assets/127086564/1273989f-bba8-4172-b697-26819eca3f51)

Is this for real? 
Accept fault? 
No method of disputing?
The why was I reported button doesn't actually show you the content that was "reported" - it's simply gives a generic response.

**Note this is a serious bug report. 

### Expected behaviour

I expect telegram to not LIE that posts were reported and a moderator signed off on it. 

I expect there to be a dispute process.

I expect to not be banned for a false positive.

I expect to not be told to "accept the blame" like i'm being tortured into a false confession.

### Actual behaviour

Banned for 2 days

### Operating system

Linux

### Version of Telegram Desktop

4.14.9

### Installation source

Static binary from official website

### Logs

```shell
Me: `/start`

spambot: `I’m afraid some Telegram users found your messages annoying and forwarded them to our team of moderators for inspection. The moderators have confirmed the report and your account is now limited until 10 Feb 2024, 22:28 UTC.`

Me: `Why was I reported?`

spambot: `People usually don’t like it when strangers contact them — so they will report you if they find your messages annoying. And if our moderators confirm the report, your account will be limited. Please only contact people if you're sure that they are expecting messages from you.`

Me: `Tell me more`

spambot: `It really doesn‘t matter what you send, as long as the receivers find it unwelcome. It could have been a photo, an invite link or a chain letter. Please only send messages when you are sure people won’t mind getting them.

As a general rule, people don’t like receiving unsolicited advertisements, links, invite links to groups or channels, random photos and, above all, anything related to commerce or promotion of any kind.

Our moderators check all reports, so if you send annoying content to strangers you will be blocked.`

Me: `this is a mistake`

spambot: `Please use buttons to communicate with me.`
```

**Comment by Aokromes** [comment]
sorry but this is telegram desktop bug tracker, nothing here belongs to user account administration.
