### ISSUE TITLE
Recovering chat history 

### ISSUE THREAD

**Issue by Bogdawell** [telegramdesktop/tdesktop#27468]
### Is your feature request related to a problem?

In principle, I think so, because the problem is that I can’t restore the chat history, so I want it to be possible 

### Describe the solution you'd like

Hello! I want to suggest a really good idea. I think it would be very good if you added a button so that if you click on 3 dots in the chat, there will be another button. Namely, “restore correspondence history”. After the user clicks on the button, a request to restore the correspondence would be sent to the user to whom he sent the offer. I hope you will consider my proposal in detail. Thank you.

### Describe alternatives you've considered

None, this is a completely new idea

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
