### ISSUE TITLE
Support building with Qt4 (of some earlier version) or even TUI?

### ISSUE THREAD

**Issue by barracuda156** [telegramdesktop/tdesktop#27462]
### Is your feature request related to a problem?

Qt5 is broken on older macOS. It does not work on any PowerPC versions, and even if it gets fixed, it will likely be 5.3, still archaic.

Is it feasible to support Qt4, perhaps with limited features (which is perfectly fine)? Even text-only version would do. Maybe, with `ncurses` GUI?

### Describe the solution you'd like

Add fallback code to support older macOS via Qt4, perhaps disabling all fancy stuff.

### Describe alternatives you've considered

Alternatively, use a different and properly cross-platform GUI or even TUI.

### Additional context

While my concern is older macOS, either of these options will improve portability in general.

**Comment by ilya-fedin** [comment]
> Is it feasible to support Qt4, perhaps with limited features (which is perfectly fine)?

Only if you personally would commit the code and maintain it I guess. The current macOS build uses Qt 6.2 already, not even Qt 5.

**Comment by ilya-fedin** [comment]
> Maybe, with `ncurses` GUI?

There would be no code sharing so for such use case you better create a custom client

**Comment by barracuda156** [comment]
@ilya-fedin Got it, thank for replying. Was there some version which built with Qt4? I see README mentioning support for 10.6, but not clear which minimum Qt it required.

**Comment by ilya-fedin** [comment]
No, tdesktop has started from Qt 5.3 if I remember right. But those versions won't connect to modern Telegram servers.

**Comment by barracuda156** [comment]
> No, tdesktop has started from Qt 5.3 if I remember right. But those versions won't connect to modern Telegram servers.

Okay, then it’s a lost case with Qt at least.
