### ISSUE TITLE
Telegram Desktop: wrong dates on the Telegram Calendar

### ISSUE THREAD

**Issue by ST-2017** [telegramdesktop/tdesktop#27464]
### Steps to reproduce

1. Open the Telegram Calendar by scheduling a message.
2. Check the number of days in the previous month in the current month window

### Expected behaviour

The calendar shows the correct number of days in a month and also the dates correspond to real days.

### Actual behaviour

1) Open February 2024. There are 29 days.
2) Click “>” and open March. Observe February. There are 31 days in February (29 days are expected)
3) Click “>” and open April. Observe March. There are 30 days in March (31 days are expected). The real day of April 1st is Monday but it is Sunday on Telegram calendar.

**Video**: https://github.com/telegramdesktop/tdesktop/assets/31862105/2b547d3c-45da-4724-bdfb-d9454c7ebc31

**Note**: it looks like the Сalendar shows the number of days in the previous month equal to the number of days in the current one.
<img width="329" alt="number_of_days_issue" src="https://github.com/telegramdesktop/tdesktop/assets/31862105/10c2e91c-2583-4eb8-bf0e-0c0fa5feea31">

### Operating system

macOS 14.3.1 

### Version of Telegram Desktop

10.7.259037, 10.7.1.259074

### Installation source

Mac App Store

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift

**Comment by ST-2017** [comment]
Do you mean I have to move this ticket to the TelegramSwift repo?

**Comment by Aokromes** [comment]
yes

**Comment by ST-2017** [comment]
Transferred to https://github.com/overtake/TelegramSwift/issues/1076.
