### ISSUE TITLE
Changing Group Chat History property clears all pins when done for the first time

### ISSUE THREAD

**Issue by TXephy** [telegramdesktop/tdesktop#27466]
### Steps to reproduce

1. Open any group with pinned messages
2. Set Chat History for New Members from Hidden to Visible for the first time
Note: this issue is reproducible only once per group chat.

![image](https://github.com/telegramdesktop/tdesktop/assets/43374263/e7c3af8f-200a-4ca6-bcea-8a7764920793)

Changing to:

![image](https://github.com/telegramdesktop/tdesktop/assets/43374263/9bf0f714-c3fb-478c-84ee-7abdf6396310)

This extends to all members of group chat. This is not a bug exclusive to Desktop Version.

### Expected behaviour

Pinned messages should be visible as usual.

![image](https://github.com/telegramdesktop/tdesktop/assets/43374263/d4cc05f8-a449-4826-a014-1f9b25d9cde7)

![image](https://github.com/telegramdesktop/tdesktop/assets/43374263/017646d4-7576-434d-ba3e-094492360dc5)

### Actual behaviour

All pinned messages are deleted. All messages that are older than the change to the group will not be pinnable.

![image](https://github.com/telegramdesktop/tdesktop/assets/43374263/c073a5cf-fc94-4aa3-ae55-01701e44ffb6)

### Operating system

Windows 10 Home, 22H2, OS Build 19045.3930

### Version of Telegram Desktop

Version 4.14.13 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
This switches the group from a legacy group to a supergroup and this involves huge amount of complex logic in merging those two separate chats in the UI as if nothing happened. I guess it is broken somehow for the pinned messages.

If you relaunch the app and open this group, are pinned messages displayed correctly? Or restart doesn't fix the issue?

**Comment by enchained** [comment]
@TXephy Did the restart help? I also want to convert my group, but don't want to lose my pins.

**Comment by TXephy** [comment]
Hello everyone,

Neither relaunching the app, nor reinstalling it restored the pins.

Increasingly enough, on the mobile version it even deletes all Media from the group overview, but they're still visible in the chat if you scroll manually. This issue does not appear on the desktop version.

**Comment by TXephy** [comment]
Hello everyone @john-preston @enchained 

The pins are back. Not sure what happened but it seems to be working fine now.

**Comment by john-preston** [comment]
@TXephy for me it doesn't show it on the first group open after relaunch but shows it after the next openings.

**Comment by john-preston** [comment]
I've found the problem, it would be fixed in the next version.
