### ISSUE TITLE
Saving forwarded message from user with privacy by user with privacy is displayed incorrectly.

### ISSUE THREAD

**Issue by danog** [telegramdesktop/tdesktop#27463]
### Steps to reproduce

1. user A (fwd privacy enabled) sends a message (id 1)
2. user B (fwd privacy enabled) forwards it to a group (id 2)
3. user C saves the message with id 2 to saved messages

The API will correctly return a messageFwdHeader with `from_name=A` and `saved_from_name=B` (verified through MadelineProto).

### Expected behaviour

Telegram desktop displays the saved message as a forwarded message from user A, by user B.

### Actual behaviour

Telegram desktop displays the saved message **not** as a forwarded message, but as a message sent directly by user B (no mention of user A).

### Operating system

Arch linux

### Version of Telegram Desktop

4.14.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Thanks for your report. I hope I've fixed this for the upcoming release (the one after 4.14.16).

**Comment by danog** [comment]
Yep it was fixed, thanks!
