### ISSUE TITLE
Inconsistent access to pornographic content

### ISSUE THREAD

**Issue by rebroad** [telegramdesktop/tdesktop#2747]
### Steps to reproduce
This seems to be an intermittent issue with some users able to view content and some being blocked.
1.  Send a link to a friend for channel hosting pornographic content, e.g. https://telegram.me/tesudastop
2. Friend clicks on the link, and either it works (as it did in my case), or does not, in which case, the message "Sorry, this channel is unavailable because it was used to spread pornographic content." is displayed.

### Expected behaviour
The link should either work for everyone or for no-one.

### Actual behaviour
It works for some people and not for others, with no explanation as to why the preferential treatment.

### Configuration
**Operating system:** Ubuntu 14.04

**Version of Telegram Desktop:** 0.10.20
**Version of Telegram for iOS:** 3.15 (user on this version was blocks, but I don't think it's related to the version, as I have seen the message on Desktop 0.10.20 also)

**Comment by john-preston** [comment]
@rebroad It should be fine in Telegram Desktop. As I know there are very strict rules in the Apple AppStore regarding any erotic materials, so perhaps they're blocked on iOS.

Anyway, the blocking is done on the servers side, so I'm afraid it has nothing to do with this repository :(

**Comment by stek29** [comment]
@john-preston Telegram started blocking channels/groups on ALL platforms.
Example: https://telegram.me/joinchat/BXT-LD0u7TWY3CTakCZ_mQ

**Comment by john-preston** [comment]
@stek29 Well, maybe this is not regular porno that is going on there, who knows. Maybe child porn or I don't know what else. Anyway, this is irrelevant here.

**Comment by stek29** [comment]
@john-preston Sure. 
@rebroad Please use "Ask a question" button in settings, or ping @Telegram on Twitter.

**Comment by skupake** [comment]
View african porn here
https://telegram.me/legalsex

**Comment by skupake** [comment]
View Worldwide porn
https://telegram.me/legalsex
