### ISSUE TITLE
Wrong loader position after webview crash

### ISSUE THREAD

**Issue by Viiprogrammer** [telegramdesktop/tdesktop#27479]
### Steps to reproduce

1. Crash webapp 
2. Click reload

https://github.com/telegramdesktop/tdesktop/assets/17622604/2063be99-656d-46e1-ac37-5957b2c99853

### Expected behaviour

Loader position looks OK

### Actual behaviour

Loader outside the webapp window

### Operating system

Ubuntu 22.04.3 LTS x86_64

### Version of Telegram Desktop

4.14.15

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> 1. Crash webapp

How can I reach this?

**Comment by Viiprogrammer** [comment]
> > 1. Crash webapp
> 
> How can I reach this?

#27481
