### ISSUE TITLE
Telegram Desktop client doesn't allow to schedule message to a group topic

### ISSUE THREAD

**Issue by Gisborn** [telegramdesktop/tdesktop#27472]
### Steps to reproduce

1. Open a group with topics
2. Select a topic
3. Right mouse button click on a send button 
![image](https://github.com/telegramdesktop/tdesktop/assets/17904326/42e23a99-3f5e-403b-a134-f3e0db7d7ca6)

### Expected behaviour

Expected two option:
"Schedule message"
"Send without sound"

### Actual behaviour

There is only one option - "Send without sound"

### Operating system

Windows

### Version of Telegram Desktop

4.14.13 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/25926
