### ISSUE TITLE
Docker build | Empty out/Release directory

### ISSUE THREAD

**Issue by x09** [telegramdesktop/tdesktop#27471]
### Steps to reproduce

https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md

### Expected behaviour

Previous versions were built successfully to **out/Release** directory.
Today, **out/RelWithDebInfo** only
But -e CONFIG=Debug i not specified

### Actual behaviour

Build to  **out/Release** directory.

### Operating system

Linux

### Version of Telegram Desktop

4.14.15

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Yes, it's intended.
