### ISSUE TITLE
Text Limit Reached ERROR on Saving Edited message

### ISSUE THREAD

**Issue by IntenseSoftwares** [telegramdesktop/tdesktop#27491]
### Steps to reproduce

> Send any normal message, (probably) more than 1000 characters
> Edit it
> add or delete a single character

### Expected behaviour

Expected to save the edited message like it functioned before

### Actual behaviour

A negative limit counter appears over the send button and won't let you save the message

### Operating system

Microsoft Windows 10 Pro, 10.0.19045 Build 19045

### Version of Telegram Desktop

4.14.16 x64

### Installation source

Static binary from official website

**Comment by IntenseSoftwares** [comment]
I have telegram beta enabled on my desktop, I have a message containing a list on my private channel, I edited that yesterday without any problems. But after updating when I got the new update today, this happened.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/27389
