### ISSUE TITLE
telegram shuts down for no apparent reason and displays errors on linux

### ISSUE THREAD

**Issue by kartavenko1983** [telegramdesktop/tdesktop#27490]
### Steps to reproduce

Just working in the background

### Expected behaviour

Telegram should not shut down arbitrarily

### Actual behaviour

The application is shutting down during the most normal use

### Operating system

Linux

### Version of Telegram Desktop

4.14.16

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/27482

**Comment by kartavenko1983** [comment]
@Aokromes, Why did you close the topic? In the topic indicated by the link, we are talking about version 4.15. But there was no problem in it, it appeared in 4.14.16

**Comment by kartavenko1983** [comment]
@Aokromes The beta version is not available

**Comment by Aokromes** [comment]
> @Aokromes The beta version is not available

even there is no beta enabling it will generate crashlog.

**Comment by kartavenko1983** [comment]
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by ilya-fedin** [comment]
I believe this is a duplicate anyway and should be closed.

**Comment by kartavenko1983** [comment]
[
[log.txt](https://github.com/telegramdesktop/tdesktop/files/14319541/log.txt)
](url)

**Comment by kartavenko1983** [comment]
@Aokromes 
[log.txt](https://github.com/telegramdesktop/tdesktop/files/14319545/log.txt)

**Comment by kartavenko1983** [comment]
@Aokromes Crash ID: e5a5ae4d-3da7-4c1e-dc8bde9e-78da7265

**Comment by kartavenko1983** [comment]
I sent a report. But telegram in general has become inadequate now. I started hanging up.

**Comment by kartavenko1983** [comment]
Crash ID: 37f92807-ccc0-4a89-77c5edbf-31169a43

**Comment by Daxx** [comment]
Kubuntu 22.10

Having difficulty keeping Telegram 4.14.16 running (random closures)

[log.txt](https://github.com/telegramdesktop/tdesktop/files/14319798/log.txt)

(Log probably shows OpenGL disabled -- made no difference)
No crash id. When TG starts up, there's a dialog which shows briefly, then closes before I can read it.

Now running with `env GTK_USE_PORTAL=1 ...` as a possible workaround.

**Comment by kartavenko1983** [comment]
@Daxx https://github.com/telegramdesktop/tdesktop/issues/27482

**Comment by kartavenko1983** [comment]
@Daxx This theme is a duplicate, it is closed, throw everything into the theme #27482
