### ISSUE TITLE
Video Call Window repaint issue on screens with different scaling

### ISSUE THREAD

**Issue by fireandfuel** [telegramdesktop/tdesktop#27496]
### Steps to reproduce

1. Disable Default interface scale and set it to 125% in the slider below
2. Start a group video call (audio only or video + audio) on a screen with 100% scaling
3. Move the group video call window to a screen with 150% scaling
4. Change the group video call window size on the screen with 150% scaling
5. Move the group video call window back to the screen with 100% scaling

### Expected behaviour

The group video call window should change size by 150% when entering the screen with the higher scaling and can be resized there and moved back to the screen with the lower scaling like the main window.

### Actual behaviour

The group video call window doesn't get resized to fit the new scaling and stays the exact same size what is smaller than the minimum size the window should have. After changing the group video call window's size and moving it back to the causing the group video call window to freeze and not getting repainted, even when the group video call window gets closed and opened again.

### Operating system

Windows 11 x64 (Build 22631.3155)

### Version of Telegram Desktop

4.14.16 x64, 4.15 x64

### Installation source

Static binary from official website

**Comment by kartavenko1983** [comment]
the current version is 4.15, check it out

**Comment by fireandfuel** [comment]
I tried it with the newest version and 4.15 is affected too
