### ISSUE TITLE
Unable to write Korean in Linux Mint 17

### ISSUE THREAD

**Issue by ied206** [telegramdesktop/tdesktop#275]
I'm using Linux Mint 17 amd64 and nabi, Korean XIM (https://github.com/choehwanjin/nabi).
I am unable to read nor write any Hangul, Korean charecters in Telegram D. 

Print bug may be related to font, and if user can select fonts in settings, it may be fixed.
However, writing bug is Qt5's bug, and every application using Qt5 is affected on Ubuntu 14.04+.

It is known that setting Qt's environment variable QT_IM_MODULE to ibus or nabi in Qt Creator is solution, but I'm not sure.

I hope this bug soon be patched.

**Comment by ustcltx** [comment]
The same issue to #375

**Comment by taijuin** [comment]
the answer is similar in : #375

**Comment by taijuin** [comment]
If you are using Chrome app in Linux desktop，maybe you can consider this:（including Simplified Chinese,Traditional Chinese,Korean.

https://chrome.google.com/webstore/detail/telegram/obocnnbgpkjmmdmmhnieggghdphphefm?utm_source=chrome-ntp-icon

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.

**Comment by Mnkai** [comment]
Writing Korean works... kind of. Character composition bug related to 'space' exists.
While composition, 'space' input should finish composition and add whitespace at the behind of composed character. However, 0.8.50 dev version inserts whitespace in front of composed character when pressing space to insert whitespace at the end of composed character. Manually finishing composition with arrow key (or other key) before pressing space key kinda works, but definitely not usable.
![20150816011514minoriworkstation](https://cloud.githubusercontent.com/assets/10909652/9289702/88fd92f8-43b4-11e5-85e1-9a64067f6661.png)

**Comment by 5bpa** [comment]
I got same result with Mnkai's with 0.8.52 stable version
On Ubuntu 14.04 TLS 64bit with Ibus

Thank you.

**Comment by 5bpa** [comment]
@Mnkai When I switched IME to fcitx, it works without such problems.
