### ISSUE TITLE
telegram 4.15.0 Showing the screen to interlocutor does not work.

### ISSUE THREAD

**Issue by bagasik** [telegramdesktop/tdesktop#27509]
### Steps to reproduce

Hello.
My system Gentoo Linux 6.6.13-gentoo x86_64
Graphic shell xfce4 -  4.18.5
Software net-im/telegram-desktop-bin-4.15.0

When calling an interlocutor, the show screen function does not work.
When I call my interlocutor, I see the Screen button at the bottom, I press it, but nothing happens.

Communication takes place computer-to-computer, the systems are the same and the telegram versions are the same.

### Expected behaviour

It should show the interlocutor my desktop screen, but it doesn’t.

### Actual behaviour

show screen function does not work.

### Operating system

Gentoo Linux 6.6.13-gentoo x86_64

### Version of Telegram Desktop

telegram 4.15.0

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> When I call my interlocutor, I see the Screen button at the bottom, I press it, but nothing happens.

Please provide a screen record of that

**Comment by bagasik** [comment]
I do not know how to do it!

**Comment by bagasik** [comment]
![Снимок экрана_2024-02-23_11-08-29](https://github.com/telegramdesktop/tdesktop/assets/70150149/619f1771-39cf-48b0-a87d-1ab05c6b8c27)
Pressing the button screen, nothing happens.

**Comment by ilya-fedin** [comment]
does it work in other applications using webrtc (chrome, firefox)?

**Comment by bagasik** [comment]
> does it work in other applications using webrtc (chrome, firefox)?

I don't know.

**Comment by bagasik** [comment]
In Telegram version 4.13, the show screen function worked.

**Comment by bagasik** [comment]
In the latest versions of Telegram 4.14-4.15 it does not work.

**Comment by ilya-fedin** [comment]
> I don't know.

Please make know, it might be an issue with your system and you better consult your distro community in that case.

> In Telegram version 4.13, the show screen function worked.

Can you bisect through the binaries in github release or through commits and find first bad version?

**Comment by bagasik** [comment]
> Can you bisect through the binaries in github releases or through commits and find first bad version?

Sorry, I made a mistake in the versions.
In these versions the Screen function worked.
4.14.9
4.14.2

Doesn't work in these versions.
4.15.0
4.14.15


I took information on old versions from the Changelog system repository.
https://packages.gentoo.org/packages/net-im/telegram-desktop-bin/changelog

**Comment by ilya-fedin** [comment]
What about the version in between 4.14.9 and 4.14.15? There's quite a lot

**Comment by bagasik** [comment]
> What about the versions in between 4.14.9 and 4.14.15? There's quite a lot

I install the available versions from my system's repository.

**Comment by bagasik** [comment]
Tested between linux-windows, from Windows can show me the screen, but I cannot show the screen.

**Comment by bagasik** [comment]
I will not install it on top of the system package manager.

**Comment by ilya-fedin** [comment]
Then there's nothing to do on this issue
