### ISSUE TITLE
Trying to export history!!!! 

### ISSUE THREAD

**Issue by kristal44** [telegramdesktop/tdesktop#2750]
### Steps to reproduce
1. Load chat
2. select more than 100 messages (actually there are like 35,000 messages)
3. options available just to the first 100 selected...

### Expected behaviour
I want to be able to select all te message without limits. if necesary add and export chat option PLEASEE

### Actual behaviour
Limits my messages to 100 

### Configuration
**Operating system:**
windows 10
**Version of Telegram Desktop:**
0.10.20

**Comment by MasterGroosha** [comment]
Only 100 selected messages can be forwarded at a time.
