### ISSUE TITLE
Tdesktop crashes shortly after sending an image

### ISSUE THREAD

**Issue by atis** [telegramdesktop/tdesktop#27501]
### Steps to reproduce

Send image to chat
Wait

### Expected behaviour

Telegram should not crash

### Actual behaviour

Telegram crashes

### Operating system

Ubuntu 16.04, Mate 1.12.1

### Version of Telegram Desktop

4.15

### Installation source

Static binary from official website

### Crash ID

0a39158e-41e0-4a3a-1396a1a9-3e8728bf

**Comment by kartavenko1983** [comment]
On rosa linux Fresh 4.12, the error is not reproducible.

**Comment by Aokromes** [comment]
also, can't reproduce on ubuntu 22.04.

**Comment by ilya-fedin** [comment]
> ### Operating system
> 
> Ubuntu 16.04, Mate 1.12.1
> ### Version of Telegram Desktop
> 
> 4.15
> ### Installation source
> 
> Static binary from official website

This information seem to contradict: 4.15 supports Ubuntu 20.04+

**Comment by atis** [comment]
Unfortunately the OS on this machine cannot be upgraded.
Issue started about month ago. Binary has been installed long time ago, now only updates via built-in updater. 

![Selection_2030](https://github.com/telegramdesktop/tdesktop/assets/1108226/03c45c8f-5eba-4d60-9fd7-32cac80e1c8d)

**Comment by ilya-fedin** [comment]
> Unfortunately the OS on this machine cannot be upgraded.

But your OS is not supported you can't run this version of Telegram, the last Telegram version supporting your OS is 4.9.9
