### ISSUE TITLE
[Telegram Desktop V4.15 x64][Windows 11 23h2] Contacts bar collapsing without interaction on 1080x1920 display

### ISSUE THREAD

**Issue by pablosme** [telegramdesktop/tdesktop#27511]
### Steps to reproduce

1. Have a monitor with 1080x1920 resolution (portrait mode)
2. In my case, I have multiple groups tabs with multiple chats
3. Select a chat and it will just keep collapsing and decolapsing by itself (no need of interaction)

### Expected behaviour

The group should not collapse by itself, It should collapse and stay like that or dont collapse at all.

### Actual behaviour

It collapses by itself and then decollapse, again, by itself. I suggest some manual option to collapse the group so it wont occupy space on slimmer resolutions. 

### Operating system

Windows 11 23h2

### Version of Telegram Desktop

4.15 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> It collapses by itself and then decollapse, again, by itself.

It's not quite clear what this means, can you do a screen record?

**Comment by pablosme** [comment]
> > It collapses by itself and then decollapse, again, by itself.
> 
> It's not quite clear what this means, can you do a screen record?

See message above, I uploaded a video already

**Comment by john-preston** [comment]
Does it still happen if you change the interface scale in Settings to one way or another?

**Comment by ilya-fedin** [comment]
This looks like it's related to native shadows but I forgot to try to reproduce this issue given the stream of proxy-related crashes

**Comment by ilya-fedin** [comment]
So I switched my monitor to portrait orientation an I can say this doesn't make this reproduce. Perhaps that's not what causing the issue? The screen record looks really weird, like Windows is broken and is missing system components like DWM. Is this the case?
