### ISSUE TITLE
bot username is duplicated when entering @

### ISSUE THREAD

**Issue by ZeN220** [telegramdesktop/tdesktop#27515]
### Steps to reproduce

I'm not sure, but my case looked like this:
1. Press the Inline button with the parameter `switch_inline_query_current_chat`.
2. send a message from inline query (in my case it is a sticker)

And so several times

### Expected behaviour

When entering @, there will be one bot on the list.

### Actual behaviour

Bot repeat in list
![](https://github.com/telegramdesktop/tdesktop/assets/79989516/5aebd26d-8c5e-4582-9e90-11a52478bc87)

### Operating system

Windows 11 23H2

### Version of Telegram Desktop

4.15

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Can you provide me a bot that I can use to reproduce the issue from scratch? You can send it to me privately at https://t.me/preston

**Comment by ZeN220** [comment]
> Can you provide me a bot that I can use to reproduce the issue from scratch? You can send it to me privately at https://t.me/preston

okay, i'll try to find a pattern and text to u
