### ISSUE TITLE
Have contact names automatically update to match what you would see if they were not a contact.

### ISSUE THREAD

**Issue by Sja91** [telegramdesktop/tdesktop#27517]
### Is your feature request related to a problem?

Currently there is no way to see a person's chosen name if you have them saved to your contacts.
Often people will change their name with info such as, away on vacation, in the hospital, at work, or things like that.
Some people I have on my contact from my phone, and I can't see what they go by online.
Sometimes people update their online name and it causes confusion in chat when I keep calling them by their old name because it is what I have in my contact with them.
These are just some of the various frustrations I've dealt with, and I know I am not alone here, as I've heard the same from others.

### Describe the solution you'd like

I think my preferred solution would be just leaving the name blank in the contact's info, and then it just defaults to whatever their name is as set by them.
Failing that, maybe something in their bio at least, smaller name below their normal name or something like that.
Or even both, that would potentially be even better. I would definitely prefer the first option, as it allows the name to be correct seen at a glance, in chat or in my friends list, but if we can also get the smaller name for when we do use the contact system, that would be a great bonus.

### Describe alternatives you've considered

The only alternative I know is... to just not use the contact system. But that seems.... not ideal?

**Comment by obole1** [comment]
Few months back I got an email regarding crypto investment. I jumped at the opportunity. I got scammed of 62,500 euros I was so frustrated. I got a call regarding my funds can be recovered. I was hesitant. Glad i picked up the phone. I got my money back. fusionforensics.tech team is worth every penny

**Comment by john-preston** [comment]
This is a platform-wide suggestion, it belongs to https://suggestions.telegram.org, here nothing will be done, because it is TDesktop-only bugtracker.
