### ISSUE TITLE
Only part of a .zip file is uploaded

### ISSUE THREAD

**Issue by sasha200939** [telegramdesktop/tdesktop#27516]
### Steps to reproduce

1. download a rar file
2. compare the original file size with the downloaded one, its different
3. unzip file and get error because file is corrupted

### Expected behaviour

file is successfully unzip, and size of file in telegram and on pc is similar. 

### Actual behaviour

I try to download a zip archive but when i try to unzip, it cause error. i compare they size and they was different. i re-downloaded this file few times but it didn't help.

### Operating system

windows 10

### Version of Telegram Desktop

4.15

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
can't reproduce myself

**Comment by obole1** [comment]
Few months back I got an email regarding crypto investment. I jumped at the opportunity. I got scammed of 62,500 euros I was so frustrated. I got a call regarding my funds can be recovered. I was hesitant. Glad i picked up the phone. I got my money back. fusionforensics.tech team is worth every penny
![Uploading best 2.jpeg…]()
