### ISSUE TITLE
Major Security Issue that allow user with admin privilege to be able to access data unnoticed 

### ISSUE THREAD

**Issue by hamedhdd** [telegramdesktop/tdesktop#27513]
### Steps to reproduce

in a local or network computer, if you are able to access "logged-in Telegram Desktop" folder the whole session can be copied to another computer without asking for credential information

### Expected behaviour

It expected for database to depend not only by initial login info but hardware id or any unique info to avoid this security issue

### Actual behaviour

if you copy the whole telegram folder to any other computer, you can access all chats and data without asking for credential or 2fa and this copied session will not appear in device list

### Operating system

Windows

### Version of Telegram Desktop

4.15

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> hardware id or any unique info

Can you propose something exact to use for this? You say hardware id but it's not clear on top of what it should built.

**Comment by hamedhdd** [comment]
> > hardware id or any unique info
> 
> Can you propose something exact to use for this? You say hardware id but it's not clear on top of what it should built.

It depends on programmer to make it more secure and reliable
For Example the session stores Machine model (MB Model For PCs) as a session name, but every hardware has a unique Id that can be stored in session data and be double checked upon execution, and then if this id doesn't match it will automatically log the session out

**Comment by ilya-fedin** [comment]
> but every hardware has a unique Id

You want the application to go through all the hardware in the system and save their device id? Wouldn't that require admin privileges and so user complaints? Note that telegram desktop is a cross platform application and should work on three kinds of systems (Windows macOS, Linux).

**Comment by hamedhdd** [comment]
> There is a topic on QT https://forum.qt.io/topic/69684/generate-unique-hardware-id-cross-platform/8 - unsolved suggestion: `QByteArray QSysInfo::machineUniqueId()` does not really works
> 
> > Note that on some systems, this value will persist across reboots and on some it will not.

there are several ways to implant this feature, maybe not the hardware id at all but an unique season that stores on that specific computer to be checked upon app execution!

For now login information stores in a local database in telegram folder that can be copied without need to re-login on a new machine, the only way to protect your chat is setting passcode to lock app on schedule, but this feature is not the solution

**Comment by ilya-fedin** [comment]
> but an unique season that stores on that specific computer to be checked upon app execution

What do you mean by 'unique season'?

> For now login information stores in a local database in telegram folder that can be copied without need to re-login on a new machine, the only way to protect your chat is setting passcode to lock app on schedule, but this feature is not the solution

There's no other way on desktop platforms as they're open and ways to protect on them usually require admin or kernel access (DRM) which doesn't really sound reasonable in tdesktop case.

**Comment by john-preston** [comment]
@hamedhdd Everything the app can check once launched the malicious code can grab together with the session files. So there is no way you'll guard yourself if you have access to the users folder on his machine where the app works fine. The only thing that will guard you against that is a local passcode (if only the attacker won't plant a keylogger in your system), so I suggest you use the local passcode feature. That way stealing the folder or any other hardware-related information won't help the attacker.
