### ISSUE TITLE
Inserting text after emoji wrong placement

### ISSUE THREAD

**Issue by naitgacem** [telegramdesktop/tdesktop#27514]
### Steps to reproduce

1. Start typing some word
2. Insert an emoji
3. Press the left keyboard arrow(to add text before the emoji)
4. start typing
5. See only one letter is rendered _before_ the emoji, the rest is _after_ the emoji

### Expected behaviour

The entire of the text typed after pressing left should come before the emoji

### Actual behaviour

 only one letter is rendered _before_ the emoji, the rest is _after_ the emoji

### Operating system

Windows 10

### Version of Telegram Desktop

4.15

### Installation source

Static binary from official website

**Comment by naitgacem** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/71680271/5ff321a4-c62d-4fbe-b79c-acc844d380c9)

This is a screenshot for clarification.

**Comment by john-preston** [comment]
I cannot reproduce. I type "test ", then insert the emoji from the panel, then press left arrow, then type "test" from the keyboard and I get this:

![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/2324e800-8a54-4a2d-b9e1-f47e3a95aad7)

Maybe something is missing in the steps?

**Comment by naitgacem** [comment]
Oh I see. This only happens if I insert the emoji from `Win + .`  keyboard shortcut. 
Inserting the emoji from telegram panel does indeed produce the expected behavior.
