### ISSUE TITLE
Hope to increase support for the Ioongarch64 architecture

### ISSUE THREAD

**Issue by ToKingl** [telegramdesktop/tdesktop#27522]
### Is your feature request related to a problem?

Loongsarch64 architecture not supported

### Describe the solution you'd like

Hope to increase support for the Ioongarch64 architecture

### Describe alternatives you've considered

Hope to increase support for the Ioongarch64 architecture

**Comment by ilya-fedin** [comment]
tdesktop has no architecture dependent code to add support I believe
