### ISSUE TITLE
Back to the old  design

### ISSUE THREAD

**Issue by TiagoDanin** [telegramdesktop/tdesktop#2752]
What's wrong with new design?
- The letters are very small,

- Very white,
 
- Title bar on Windows is very small

![image](https://cloud.githubusercontent.com/assets/5731176/21574234/96e63b78-ced6-11e6-8ee6-71db7f6ff752.png)

![image](https://cloud.githubusercontent.com/assets/5731176/21573932/b50ee244-ced1-11e6-9c91-e319de566d3c.png)

![image](https://cloud.githubusercontent.com/assets/5731176/21573936/bb766da0-ced1-11e6-8b31-510fdc09242b.png)

### Configuration
**Operating system: Windows 10 and AchLinux**

**Version of Telegram Desktop: 0.10.21**

**Comment by stek29** [comment]
Just back to Old Icon would be enough :)

**Comment by john-preston** [comment]
@TiagoDanin I'm afraid that is not possible. But what "letters are very small" are you talking about? The font and font sizes were not changed with the design.

**Comment by z3ntu** [comment]
I at least want my top-bar again and not a mobile interface with the navigation drawer on the left... There's enough space on my desktop for the few buttons at the top...

**Comment by TiagoDanin** [comment]
Sorry. I thought was small @john-preston

**Comment by skroom** [comment]
Sizes are almost ok, but grey color of title is so confusing - it looks like tg window is always inactive, it blows my mind :)

**Comment by john-preston** [comment]
@skroom The new design supports color themes, so I hope there will be a color theme that suits your needs sooner or later 😌

**Comment by skroom** [comment]
@john-preston sorry, is there any link explaining what new themes are and how create them? Themes are good but I think by default titlebar color could be less confusing

**Comment by stek29** [comment]
@skroom First lines [here](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/default.tdesktop-theme)
Also, you look at this theme and use it as an example (a lot of variables are commented): https://t.me/joinchat/AAAAAD9ONJlGmu3Y_2cTQA

**Comment by andreymal** [comment]
Please restore old design
