### ISSUE TITLE
Wrong quote shortcut

### ISSUE THREAD

**Issue by ollegsey** [telegramdesktop/tdesktop#27529]
### Steps to reproduce

1. Write some text
2. Select the text
3. Press AltGr + Shift + > shortcut

### Expected behaviour

Nothing happens, because the shourtcut is ctrl + shift + >

### Actual behaviour

The text converts to quote and it's impossible to use another shpurtcut that I have fot these keys

### Operating system

Windows 11

### Version of Telegram Desktop

4.15 x64

### Installation source

Static binary from official website

**Comment by obole1** [comment]
Few months back I got an email regarding crypto investment. I jumped at the opportunity. I got scammed of 62,500 euros I was so frustrated. I got a call regarding my funds can be recovered. I was hesitant. Glad i picked up the phone. I got my money back. fusionforensics.tech team is worth every penny
