### ISSUE TITLE
Add privacy option to restrict getting media from Everybody/My Contacts/Nobody

### ISSUE THREAD

**Issue by ADGuschin** [telegramdesktop/tdesktop#27525]
### Is your feature request related to a problem?

Now if your privacy parameter "Messages" is set to "Everybody", that means you can get any type mesages include NSFW content or another unwaned files.

### Describe the solution you'd like

New privacy option, ex. "Media" or "Files" with meaning "Who can send me images, video, audio or documents?" with the same values like for "Voice Messages" option.

### Describe alternatives you've considered

Extend the "Voice Messages" option to allow to choose privacy policy for every type of media content differently.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
