### ISSUE TITLE
Issue with Text Formatting in Quoted Texts

### ISSUE THREAD

**Issue by Hasan-Mir** [telegramdesktop/tdesktop#27527]
### Steps to reproduce

1. Transform a sentence into a quoted text.
2. Select one or more word from the **BEGINNING** of the sentence.
3. Apply a formatting style such as `Bold`, `Italic`, `Underline`, `Spoiler` or etc.

### Expected behaviour

The formatting should be applied without splitting the quoted text into two separate quotes, similar to the behavior observed in Telegram Android:

https://github.com/telegramdesktop/tdesktop/assets/62181905/1a096a29-7fb7-4840-b924-249dad664310

### Actual behaviour

It splits the quoted text into two separate quotes:

https://github.com/telegramdesktop/tdesktop/assets/62181905/7528c7df-6a0f-430e-b92b-3728a35c5da5

### Operating system

Windows 10 Pro 22H2 19045.3930

### Version of Telegram Desktop

4.15

### Installation source

Static binary from official website

**Comment by obole1** [comment]
Few months back I got an email regarding crypto investment. I jumped at the opportunity. I got scammed of 62,500 euros I was so frustrated. I got a call regarding my funds can be recovered. I was hesitant. Glad i picked up the phone. I got my money back. fusionforensics.tech team is worth every penny
![Uploading best 2.jpeg…]()

**Comment by john-preston** [comment]
Thanks for your report. This should be fixed in the next version.

**Comment by Hasan-Mir** [comment]
Fixed in 4.15.1
