### ISSUE TITLE
Better advertising

### ISSUE THREAD

**Issue by rezaei** [telegramdesktop/tdesktop#27523]
### Is your feature request related to a problem?

Hi , 
i want to ask you , don't show us  sexy or pornographic channel as advertising or sponsoring , 
we want to use this application for connecting for our family , our children , or for ourself ... 
please dont show us  channels like this ... 
![image](https://github.com/telegramdesktop/tdesktop/assets/2250985/f7c97b5b-750c-437a-ab60-719657a354a4)

![image](https://github.com/telegramdesktop/tdesktop/assets/2250985/8d4ff9cf-62bf-4dcd-8b16-318747f0aa9b)

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by john-preston** [comment]
@rezaei This is your proxy sponsor. You should disable proxy server which promotes this channel, and you won't see it. This is up to proxy provider to decide which channel is promoted for users of his proxy.
