### ISSUE TITLE
Undetectable scheduled inline results

### ISSUE THREAD

**Issue by DO97** [telegramdesktop/tdesktop#27521]
### Steps to reproduce

1. Load your inline results in a chat (preferably stickers).
2. Right click on one of them.
3. Schedule your inline result selection.

### Expected behaviour

The inline result should be sent at the scheduled time and be visible to bots, at the exact time they're sent.
Otherwise, I'd completely remove the possibility to schedule an inline result, as it is on Android, for example.

### Actual behaviour

The inline result selection is like a ghost to bots. They're not able to detect anything that was sent. This cause many unfixable issues for developers.

### Operating system

Windows 10

### Version of Telegram Desktop

4.14.16

### Installation source

Static binary from official website

**Comment by cox88** [comment]
Investing can be a great way to grow your wealth, but it is important to do your due diligence and research before entrusting your money to any platform. Always read the fine print and be wary of promises that seem too good to be true. Remember, if something seems too good to be true, it probably is. In conclusion, while optvalltd.com  is great platform to invest with, it is important to be cautious and do your research before investing any money. If you do decide to invest with them, make sure to keep a close eye on your investments and be prepared to take action if anything seems amiss. And if you do find yourself in a situation like mine, don't hesitate to seek help from professionals who can assist you in recovering your lost funds , fusionforensics.tech , to check if you can get a relief I strongly recommend to everyone!
I was able to take action and get instant change after I involved
fusionforensics.tech
![Uploading best 2.jpeg…]()
