### ISSUE TITLE
Some phonetic characters aren't displayed properly

### ISSUE THREAD

**Issue by Hosseiny907** [telegramdesktop/tdesktop#27528]
### Steps to reproduce

I'm trying to send some English phonetics, but some characters aren't displayed properly. When you type them the text cursor doesn't go forward and they end up merged into the next letter (next letter goes on top of that). I'm having this problem with following characters but I didn't test all of them: 

Primary stress (ˈ) U+02C8
Secondary stress (ˌ) U+02CC
Length mark (ː) U+02D0

These characters are displayed properly in the android version.

### Expected behaviour

![1709220876430](https://github.com/telegramdesktop/tdesktop/assets/120657589/6e38a2a9-9904-459a-9ba2-798c1ff891ff)

### Actual behaviour

![Screenshot 2024-02-29 185722](https://github.com/telegramdesktop/tdesktop/assets/120657589/6cc1277f-0449-4aa5-b974-a6cf8d9fe074)

### Operating system

Windows 11 23H2 build 22631.3155

### Version of Telegram Desktop

4.14.9

### Installation source

Microsoft Store

**Comment by obole1** [comment]
Few months back I got an email regarding crypto investment. I jumped at the opportunity. I got scammed of 62,500 euros I was so frustrated. I got a call regarding my funds can be recovered. I was hesitant. Glad i picked up the phone. I got my money back. fusionforensics.tech team is worth every penny
![Uploading best 2.jpeg…]()

**Comment by john-preston** [comment]
I wonder if Qt apps in general display this text correctly.

**Comment by ilya-fedin** [comment]
@john-preston this looks like an Open Sans bug, I see it if replace the font. Maybe it needs an update?
