### ISSUE TITLE
Cannot login using the package from Flatpak on Mint

### ISSUE THREAD

**Issue by veer66** [telegramdesktop/tdesktop#27524]
### Steps to reproduce

1. Install Telegram Desktop from Flatpak (Flathub)
2. Open Telegram Desktop
3. Click at the Telegram icon on the taskbar
4. Click at the wait button when the system tried to close Telegram
5. Click at the start messesing button.

### Expected behaviour

Telegram Desktop shows a QR Code.

### Actual behaviour

Waiting sign keeps spinning.

### Operating system

Linux Mint 21.3 x86_64 + 5.15.0-97-generic

### Version of Telegram Desktop

4.15

### Installation source

Flatpak

### Logs

```shell
Gtk-Message: 09:01:10.935: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Could not open network socket
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
```

**Comment by veer66** [comment]
# Neofetch

```
OS: Linux Mint 21.3 x86_64 
Host: 81SY Legion Y540-15IRH-PG0 
Kernel: 5.15.0-97-generic 
Uptime: 1 hour, 16 mins 
Packages: 2598 (dpkg), 22 (flatpak) 
Shell: bash 5.1.16 
Resolution: 1920x1080 
DE: Cinnamon 6.0.4 
WM: Mutter (Muffin) 
WM Theme: Mint-L (Mint-Y) 
Theme: Mint-L [GTK2/3] 
Icons: Mint-L [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-9300HF (8) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
Memory: 3769MiB / 15908MiB 
```

# Video

https://github.com/telegramdesktop/tdesktop/assets/370688/b72bc607-b05d-4a11-b547-db8edf9ad9ca

# Proxy

I don't use any proxy. 

```
env | grep -i proxy
```

The command above return empty result

# Flatseal

I use default values.

![image](https://github.com/telegramdesktop/tdesktop/assets/370688/973dc097-569f-446c-b1a0-166d1ee19216)

**Comment by popey** [comment]
Same on Ubuntu 23.10. It takes ages to paint the window initially, then never shows a QR code, for as long as I left it (a minute or so).

**Comment by ilya-fedin** [comment]
#27450
