### ISSUE TITLE
Shortcut for archive selected chat on desktop

### ISSUE THREAD

**Issue by yagee** [telegramdesktop/tdesktop#27535]
### Is your feature request related to a problem?

Unable to archive chat using only keyboard

### Describe the solution you'd like

Add shortcut for archive current chat.

If it hard to make decision which hotkey combination will be great for this feature - I am asking you to add this feature at least in code for customizing using `shortcuts-custom.json`

I am hardly using keyboard while working on desktop, so all manipulations with Telegram Desktop UI I can completely achieve using only keyboard. Except archiving chat/channel/group.
It would be fantastic if you can add hotkey for archiving currently selected or active chat/channel/group

### Describe alternatives you've considered

No alternatives at all

**Comment by 23rd** [comment]
Feel free to check the v4.15.6 beta.

**Comment by yagee** [comment]
Works perfectly!
Thank you very much!
