### ISSUE TITLE
Bug in the minds of the developers

### ISSUE THREAD

**Issue by pvlbgtrv** [telegramdesktop/tdesktop#27534]
### Steps to reproduce

1. Download client

### Expected behaviour

When you try to log into your account, the verification code is sent to your telegram account. This is the ultimate in stupidity.
Сode should be sent by SMS, or there should at least be a choice of how to send the code.

### Actual behaviour

This is the kind of crap I didn't expect from the most popular messenger ever

### Operating system

Linux

### Version of Telegram Desktop

4.15

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
