### ISSUE TITLE
Link preview of message sent by Tdesktop doesn't follow show_above_text 

### ISSUE THREAD

**Issue by agoudbg** [telegramdesktop/tdesktop#27536]
### Steps to reproduce

1. use a inline bot to send a message with link preview, the bot's code for example:
```
...
link_preview_options: {
    url: 'xxx',
    prefer_large_media: true,
    show_above_text: true, // should show above text
},
...
```

### Expected behaviour

The link preview should be placed above text, like this photo (sent from ios)
![图片](https://github.com/telegramdesktop/tdesktop/assets/55237525/607eb55d-deae-4137-899b-f943af74c27a)

### Actual behaviour

The link preview still show below text
![图片](https://github.com/telegramdesktop/tdesktop/assets/55237525/c24ec126-f424-471b-98d2-043e2a4ab514)

(when other clients view this message link preview is above)

### Operating system

Windows 11

### Version of Telegram Desktop

4.15

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
does it start to render right if you restart the client?

**Comment by agoudbg** [comment]
> does it start to render right if you restart the client?

No, restart doesn't help

But if forward this message it will display above
And when another account view the message it also displays above

**Comment by ilya-fedin** [comment]
@agoudbg are you sure you really restarted the client? Closing main window won't stop the client, it will continue to work in backgorund.

**Comment by agoudbg** [comment]
> @agoudbg are you sure you really restarted the client? Closing main window won't stop the client, it will continue to work in background.

Of course, I'm using the Quit Telegram option in the taskbar icon.
