### ISSUE TITLE
Mic doesn't work without pavucontrol panel opened

### ISSUE THREAD

**Issue by vitacell** [telegramdesktop/tdesktop#27541]
### Steps to reproduce

1. Start Telegram
2. Record an audio
3. Enjoy an empty audio (no sound)
4. Open Pavucontrol and keep it open
5. Record an audio (enjoy not empty audio)

### Expected behaviour

Telegram should record the input as some time ago

### Actual behaviour

Mic input doesn't work if I don't open Pavucontrol and maintain it open. Everytime I want to record and send an audio, I must to open Pavucontrol and maintain it open.

### Operating system

ArchLinux

### Version of Telegram Desktop

4.15

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
@vitacell sorry but this is not reproducible with the steps you provided. Perhaps you have forgot to specify something you don't notice at first glance. Please find and fix the steps.

**Comment by vitacell** [comment]
> @vitacell sorry but this is not reproducible with the steps you provided. Perhaps you have forgot to specify something you don't notice at first glance. Please find and fix the steps.

I am using Wireplumber with pipewire, and pipewire alsa. Not sure how to debug this. Some time ago this didn't happen. Tryed some configs and other DACs, other cables, but this is something about Telegram, pipewire, and pavucontrol.

**Comment by ilya-fedin** [comment]
@vitacell reproducing in a VM could give you an idea what is missing
