### ISSUE TITLE
Gif as a public photo is not animated

### ISSUE THREAD

**Issue by michaelfastov** [telegramdesktop/tdesktop#27549]
### Steps to reproduce

1. get an animated gif
2. set private photo only visible to contacts
3. set this gif as public photo
4. check the avatar from another account which is not in contacts with initial account

### Expected behaviour

gif is animated

### Actual behaviour

gif is static and not animated

### Operating system

IOS

### Version of Telegram Desktop

last version

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
Operating system
IOS

Version of Telegram Desktop
last version

telegram desktop ain't for ios.
