### ISSUE TITLE
Telegram shortcuts conflict with AltGr characters

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#27545]
### Steps to reproduce

Using a keyboard layout that has a character in `AltGr+Shift+.` for instance, or any other `Ctrl+Shift` shortcut will block the character from being input.

### Expected behaviour

The char should be input.

### Actual behaviour

The char doesn’t input, the shortcut is triggered.

On WIndows, AltGr is translated as `Ctrl+Alt`, so `AltGr+Shift` = `Ctrl+Alt+Shift`.
The shortcut should check that Alt is not pressed in order to be triggered

### Operating system

Windows

### Version of Telegram Desktop

4.15

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#27529

**Comment by Geobert** [comment]
> #27529

Indeed, my report is more general as all keys used by `Ctrl+Shift` or `Ctrl` alone are affected

**Comment by ilya-fedin** [comment]
Is that specific to your keyboard layout? It might indicate there's a general Qt bug and tdesktop can't do anything

**Comment by Geobert** [comment]
I’m working on a project that can generate custom keyboard layouts and a user reported the issue mentionned (it’s in french). So I investigate and when the Virtual Key is OEM_COMMA, he can’t input the char in AltGr+Shift+comma (comma on his layout)

I tried his layout by keeping Qwerty’s VK, so his comma key has "C" as VK, and the problematic char was input.
I think it’s a variation of https://medium.engineering/the-curious-case-of-disappearing-polish-s-fa398313d4df
So if Telegram can check that Alt is not pressed before triggering the shortcut, it would fix it. But I don’t know how shortcuts are managed in Qt

**Comment by ilya-fedin** [comment]
This could happen with Ctrl+Shift+. but all other keybinds in the input field use ExactMatch so it couldn't happen if additional Alt modifier is being set.

**Comment by Geobert** [comment]
So it’s a duplicate of the issue you linked, you want me to close this one?

**Comment by ilya-fedin** [comment]
But you were saying

> ll keys used by `Ctrl+Shift` or `Ctrl` alone are affected

Is that not really the case?

**Comment by Geobert** [comment]
I need to test them :) But if I’m right, it should show the same issue

**Comment by Geobert** [comment]
After test, it seems only VK_OEM_COMMA is affected
