### ISSUE TITLE
Saved messages completely erased out of nowhere

### ISSUE THREAD

**Issue by sastromo** [telegramdesktop/tdesktop#27547]
### Steps to reproduce

I don't know.. They just disappeared by themself.. 💢 

### Expected behaviour

Saved messages should not get cleared by the app itself.. 💢 💢 

### Actual behaviour

Saved messages were completely cleared out of nowhere.. 💢 💢 💢
Saved messages lost the pin and the chat was empty..

**I did NOT cleared the history!!**
**I am 100% sure that I did not delete them!!**

![Screenshot_c](https://github.com/telegramdesktop/tdesktop/assets/45545544/17c745ef-ccf9-496b-b4b5-a5379a9bf026)

Years of saved messages there.. gone..  

### Operating system

windows 10

### Version of Telegram Desktop

4.15 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
telegram desktop cannot do this alone.

**Comment by ilya-fedin** [comment]
> Saved messages completely gone without my acknowledge...this is just incredible.

Well, tdesktop is not a right place to report as it can't do this
