### ISSUE TITLE
After removing own username, will still remain contactable in friend's list

### ISSUE THREAD

**Issue by AdKiller** [telegramdesktop/tdesktop#2754]
### Steps to reproduce
1.  Telegram User 1: Set Username
2.  Give only username to Telegram User 2
3.  User 2 sends a message to User 1
4. User 1 deletes his username
5. User 2 can still reply to previous messages and send messages to non existing/blank username of User 1.

### Expected behaviour
After user 1 deletes his username, user 2 should not be able to contact user 1 by username

### Actual behaviour
User 1 remains reachable after deleting username

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
Telegram Desktop 10.20

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by stek29** [comment]
Server side issue.
Also, why would you want this?
I don't want to lose contact with all the people I found via Telegram every time they change their username. And they don't want it too.
