### ISSUE TITLE
Dropdown menu cut off

### ISSUE THREAD

**Issue by mayalogic89** [telegramdesktop/tdesktop#27540]
### Steps to reproduce

1. App open close to bottom edge
2. Right click for drop down menu
3. Noticed dropdown menu got cut off

![image](https://github.com/telegramdesktop/tdesktop/assets/162259983/7916fb31-9c30-4d2a-9786-f865eaf4f9e1)

### Expected behaviour

Dropdown menu should open upwards to access all the menu options.

### Actual behaviour

Drop down menu got cut off, can't access some menu options. 

![image](https://github.com/telegramdesktop/tdesktop/assets/162259983/bf5b0af6-ab8b-4869-a9b0-2264c728456d)

### Operating system

Debian 12

### Version of Telegram Desktop

4.6.5

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
> ### Version of Telegram Desktop
> 
> 4.6.5
> ### Installation source
> 
> Flatpak

There's something wrong with the provided information, the version in flatpak is not 4.6.5
