### ISSUE TITLE
Emoji status picker crash

### ISSUE THREAD

**Issue by kukuruzka165** [telegramdesktop/tdesktop#27544]
### Steps to reproduce

1. Open the settings and click on the emoji in your name
2. Close the window with emojis without waiting for the closing animation (quickly click outside the settings window)
3. Click "change emoji status" in side menu. Or sometimes it is enough to go back to the settings

### Expected behaviour

Emoji status selection window opens

### Actual behaviour

Crash

### Operating system

Windows 11

### Version of Telegram Desktop

4.15

### Installation source

Static binary from official website

### Crash ID

52692e3a-447f-4847-9c33-d3151b0b8358

### Logs

```shell
There is nothing in the logs and the crash report window does not open
```

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by kukuruzka165** [comment]
Damn, i tried probably 5 times and it didn't open. Now you wrote it and it appeared. Beta was always on
Updated issue.

**Comment by john-preston** [comment]
Thanks! I've reproduced that.
