### ISSUE TITLE
 Adding the function of logging into your account using SMS (Alternative) DESKTOP VERSION

### ISSUE THREAD

**Issue by TannicArcher** [telegramdesktop/tdesktop#27558]
### Is your feature request related to a problem?

Yes

### Describe the solution you'd like

The code that is needed when connecting to an account should also be sent via SMS, even if there are already devices in the account (active and inactive)

### Describe alternatives you've considered

-

### Additional context

Let’s say this is the problem: the user’s computer broke down and he had to reinstall the system from scratch.
And when he logs into Telegram and enters the number, he writes that the code was sent to the active device, that is, in the chat of the previous system on which Telegram was installed, but there is no access to it since the system was reset.
And the only way out is to send the code via SMS but it doesn’t work

Screenshot problem

![Снимок экрана (10)](https://github.com/telegramdesktop/tdesktop/assets/113786861/09c3e6db-3675-4315-bc27-2a7fbbb4bc73)

**Comment by ilya-fedin** [comment]
Telegram Desktop can't receive SMS at all, even if you have no other session. That's just prohibited by the server for everything but the official Android and iOS clients and tdesktop can't do anything about that.
