### ISSUE TITLE
Flatpak Application Shortcut is Broken

### ISSUE THREAD

**Issue by Riftr** [telegramdesktop/tdesktop#27550]
### Steps to reproduce

When you attempt to open Telegram from your application menu on Linux, you get an error.

`Failed to start 'Telegram Desktop': The name is not activatable `

Editing the application menu icon to the following allows it to work again:

`flatpak run org.telegram.desktop`

### Expected behaviour

Opens Telegram application

### Actual behaviour

`Failed to start 'Telegram Desktop': The name is not activatable `

### Operating system

Fedora Linux 39

### Version of Telegram Desktop

4.15

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Sorry, but I can't reproduce this on my machine. Perhaps something is missing in steps to reproduce, feel free to make a VM image where this is reproducible to find what is missing or upload it so I can use it to reproduce.

**Comment by Riftr** [comment]
Issue appears to be Fedora related.

One can do `systemctl reload --user dbus-broker.service` after installing and it will work.
