### ISSUE TITLE
Telegram freezes then opening a specific chat

### ISSUE THREAD

**Issue by alba4k** [telegramdesktop/tdesktop#27552]
### Steps to reproduce

1. Open Telegram
2. Click on the problematic chat to open it, or right click -> open in another window. I have tried deleting the chat.

### Expected behaviour

The chat opens normally

### Actual behaviour

The program becomes unresponsive and must be killed and reopened

### Operating system

Arch Linux, up to date

### Version of Telegram Desktop

4.15.0

### Installation source

Static binary from official website

### Crash ID

-

### Logs

```
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
fish: Job 1, './Telegram' terminated by signal SIGTERM (Polite quit request)
```

**Comment by alba4k** [comment]
The problem is there on both the version from the repos and the static binary.

**Comment by ilya-fedin** [comment]
On the static binary, you can enable debug mode with the `debugmode` [cheat code](https://github.com/telegramdesktop/tdesktop/wiki/Cheat-Codes). After enabling it, the built-in deadlock  detector will be activated and will abort the application letting you to go through the crash ID routine explained when creating issue.

**Comment by alba4k** [comment]
I did what you suggested, but nothing happens during the freeze. I suppose that might be because the application isn't 100% stuck (I can still right click the tray, although none of the options do anything)

**Comment by alba4k** [comment]
Apparently, when telegram closed from the tray that time, it just crashed. And it crashed quite badly I must say, as the next time I reopened it it asked me to log in again, and my settings were gone. No big deal, but at least that issue is fixed now. Should I close this as not planned or something?

**Comment by ilya-fedin** [comment]
> I can still right click the tray

This menu is managed by the panel. It only does request to the application after clicking on an action.

**Comment by ilya-fedin** [comment]
> And it crashed quite badly I must say, as the next time I reopened it it asked me to log in again, and my settings were gone.

That's quite bad, maybe there's a QSaveFile missing somewhere...

> Should I close this as not planned or something?

Yeah, there's no practical reason to keep it open if it's unreproducible

**Comment by alba4k** [comment]
I was trying to figure out why I was unable to remove the window border (use system border thing). It happened again.

**Comment by ilya-fedin** [comment]
The transition system border is quite bugged in Qt on Wayland, it will get fully applied only after closing & reopening the window

**Comment by alba4k** [comment]
@ilya-fedin The problem is this border. 
![immagine](https://github.com/telegramdesktop/tdesktop/assets/84153269/b3614491-6ee6-488c-810e-657678753718)

I'm not sure how to get rid of it, it was never turned on in the first place

**Comment by ilya-fedin** [comment]
Disable all titlebar buttons for gtk `gsettings set org.gnome.desktop.wm.preferences button-layout ''`
You need to have xdg-desktop-portal + xdg-desktop-portal-gtk installed as tdesktop is not a gtk application but read the gtk setting via portal.

**Comment by alba4k** [comment]
![immagine](https://github.com/telegramdesktop/tdesktop/assets/84153269/0768b64c-228d-416e-910f-c1263e7c56b2)
Not sure that did much?

It worked fine before my settings got wiped tho, so unsure why that would be different now.
Also I'm not seeing a profile picture in notifications anymore (dunst)

Sorry for bothering you for this ahah, it's just really annoying

**Comment by ilya-fedin** [comment]
You checked the xdg-desktop-portal-gtk, what about xdg-desktop-portal though?

**Comment by alba4k** [comment]
It's running. Didn't check as it was running before too

**Comment by ilya-fedin** [comment]
`busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings Read ss org.gnome.desktop.wm.preferences button-layout` should return exactly what tdesktop gets

**Comment by alba4k** [comment]
```
Call failed: Interfaccia «org.freedesktop.portal.Settings» inesistente sull'oggetto nel percorso /org/freedesktop/portal/desktop
```

(Call failed: interface <...> does not exist on the object in the path /org/...)

**Comment by ilya-fedin** [comment]
looks like it doesn't really work... do you have portals.conf config?

**Comment by alba4k** [comment]
nvm fixed dw, xdg-desktop-portal-hyprland wasn't starting properly. Wrote a script that restarts it after login, everything works now, thanks.

Btw, how come it was working before, even without gkt portal installed?

**Comment by ilya-fedin** [comment]
Using the option you circled on the screenshot likely

**Comment by alba4k** [comment]
No, that just adds more stuff to that window border (telegram icon, name, etc)

**Comment by ilya-fedin** [comment]
i'll repeat myself:

> The transition to system border is quite bugged in Qt on Wayland, it will get fully applied only after closing & reopening the window

**Comment by ilya-fedin** [comment]
in other words: check the checkbox, close the window, open Telegram again

**Comment by alba4k** [comment]
Would be easier if telegram wasn't just freezing when tryint to start it now...

Well I guess the lesson to learn is to never run the static binary again lol

**Comment by alba4k** [comment]
![immagine](https://github.com/telegramdesktop/tdesktop/assets/84153269/c8c68fa6-903c-4770-b34f-9b2010a80436)

Also, it still freeezes immediately after logging in, then crashes after a while
