### ISSUE TITLE
View windows will increase size when open/close actions

### ISSUE THREAD

**Issue by colapsid** [telegramdesktop/tdesktop#27553]
### Steps to reproduce

1. Open image/video in not full screen
2. Close
3. Repeat open
4. Close
5. Repeat open ...

### Expected behaviour

View windows size will not increase size

### Actual behaviour

View windows will increase size when open/close actions

### Operating system

Kubuntu 22.04

### Version of Telegram Desktop

4.15.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Perhaps a bug of old KDE? Or maybe you miss some system configuration required to reproduce? Can't reproduce on my machine...

**Comment by colapsid** [comment]
At Kubuntu 20.04 too. This behaviour have old TG versions.

**Comment by ilya-fedin** [comment]
@colapsid 20.04 is even older and so would have even more bugs. I can't reproduce on my machine with rolling and Plasma 6.

**Comment by colapsid** [comment]
Addition. This behavior working when  View Window sticks to the edge desktop.

**Comment by ilya-fedin** [comment]
> This behavior working when View Window sticks to the edge desktop.

What's 'edge desktop'? :thinking:

**Comment by colapsid** [comment]
"edge desktop" - the corner, where start button... ( :

**Comment by colapsid** [comment]
The issue is happening when "view window" which at corner desktop in not fullscreen.

**Comment by ilya-fedin** [comment]
Looks like I reproduced

**Comment by colapsid** [comment]
:+1:  Super
