### ISSUE TITLE
Telegram and far2l-wx clipboard interaction not working on Wayland

### ISSUE THREAD

**Issue by unxed** [telegramdesktop/tdesktop#27569]
### Steps to reproduce

far2l (Linux port of Windows console file manager called Far Manager or FAR) is using wxWidgets for interface rendering and system clipboard interaction. Unfortunately, on Wayland systems (like Ubuntu 23.10) clipboard copy-paste is not working between far2l and Telegram Desktop.
Steps to reproduce

1. install ubuntu 23.10 on x86_64
2. install far2l-gui package from https://launchpad.net/~far2l-team/+archive/ubuntu/ppa
3. run "far2l"
4. download and run Telegram Desktop
5. try to copy anything from Telegram Desktop to far2l

See also:
https://bugs.telegram.org/c/37976
https://github.com/elfmz/far2l/issues/2053
https://github.com/wxWidgets/wxWidgets/issues/24391

### Expected behaviour

Clipboard is working between far2l gui (wxWidgets-based) version and Telegram Desktop.

### Actual behaviour

Clipboard between far2l gui (wxWidgets-based) version and Telegram Desktop is not working.

### Operating system

Ubuntu 23.10

### Version of Telegram Desktop

4.15.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Sorry but tdesktop doesn't manage the clipboard and can't do anything about that. If you have any problems, please direct them at Qt bugtracker (the underlying toolkit used by tdesktop).

**Comment by unxed** [comment]
> please direct them to Qt bugtracker

Thanks! Done:
https://bugreports.qt.io/browse/QTBUG-123176

**Comment by ilya-fedin** [comment]
Static binary has Qt 6.6.2 at the moment

**Comment by unxed** [comment]
Updated, thanks!

**Comment by unxed** [comment]
Bug reason possibly found:
https://github.com/wxWidgets/wxWidgets/issues/24391#issuecomment-1989195956

**Comment by ilya-fedin** [comment]
I think this info would be more valuable to Qt. All tdesktop is instantiates a QTextEdit and Qt provides the menu with the default actions, shortcut handling and etc.

**Comment by unxed** [comment]
Updated Qt issue, thanks!
