### ISSUE TITLE
2 setting points

### ISSUE THREAD

**Issue by Zik** [telegramdesktop/tdesktop#2756]
### Steps to reproduce
1. open menu
2. click on the profile photo
3. 
![2016-12-31_14-05-39](https://cloud.githubusercontent.com/assets/9817232/21575765/c4d91766-cf63-11e6-97b1-76bf6cb18540.png)

### Expected behaviour
opens a personal chat with myself

### Actual behaviour
open settings
(it would be logical and convenient, since in the settings you can go through the settings menu)

P/S the menu at the top of the window it was convenient

### Configuration
**Operating system:**
windows 10
**Version of Telegram Desktop:**
0.10.21 alpha

**Comment by john-preston** [comment]
@Zik currently this is an easy way to open chat with yourself (personal storage - no such way before), while you still have a way to open settings.

**Comment by Zik** [comment]
@john-preston I'm probably not correctly written, it doesn't open personal storage, it opens settings, clicking on the profile photo :) 
this should open a chat with yourself?
sorry for my english ;)

**Comment by KamranMackey** [comment]
@Zik Yeah, same issue over here as well.

**Comment by Zik** [comment]
![2016-12-31_15-48-47](https://cloud.githubusercontent.com/assets/9817232/21576216/26f5221e-cf73-11e6-88b6-38382943c5ec.jpg)
its? :)

**Comment by Aokromes** [comment]
Fixed on 0.10.22 :)
