### ISSUE TITLE
Telegram snapd tray icon issue

### ISSUE THREAD

**Issue by onurbbr** [telegramdesktop/tdesktop#27567]
### Steps to reproduce

1. Open Telegram Desktop
2. Check tray icon
3. See error.

### Expected behaviour

Tray icon should be visible

### Actual behaviour

Tray icon is missing.

![image](https://github.com/telegramdesktop/tdesktop/assets/47495526/c7ae5bf2-47f1-4c9a-91fc-88e18615d1eb)

### Operating system

Ubuntu 22.04.4

### Version of Telegram Desktop

4.15.1

### Installation source

Snap

**Comment by onurbbr** [comment]
I tried this in flatpak on fedora. There was no problem with Flatpak. The reason I use snap now is because I use Ubuntu. I uninstalled the package and reinstalled it, but the problem still persists.

**Comment by onurbbr** [comment]
I tried this in flatpak on fedora. There was no problem with Flatpak. The reason I use snap now is because I use Ubuntu. I uninstalled the package and reinstalled it, but the problem still persists.

**Comment by ilya-fedin** [comment]
Yeah, I tested with snap package and I can't reproduce. Perhaps you forgot to mention something in steps to reproduce, some custom system configuration?

**Comment by ilya-fedin** [comment]
I test on clean VMs so you have to specify anything I should do after installing such a VM. You can install Ubuntu in a VM yourself to find what's missing to reproduce.

**Comment by Aleksey-Terzi** [comment]
The same problem on "Linux Mint 21.3 Cinnamon 6.0.4", installed from Flatpak.
Just yesterday tried the fresh Linux Mint installation on a different computer and same problem.
![image](https://github.com/telegramdesktop/tdesktop/assets/5383652/2a6aacac-f756-4bf2-b2d1-e783fb8a9686)

If check/uncheck "Show tray icon" the tray icon appears but is broken again after the system restart.

The same issue if I download "tsetup.4.15.2.tar.xz"

However, the tray icon for the old version from https://community.linuxmint.com/software/view/telegram-desktop works without problems

**Comment by ilya-fedin** [comment]
@Aleksey-Terzi sorry but I still can't confirm
![](https://github.com/telegramdesktop/tdesktop/assets/17829319/b45f742f-86f0-4a2b-b86f-d3c5203db15d)
