### ISSUE TITLE
Update to iOS 10 emoji

### ISSUE THREAD

**Issue by KamranMackey** [telegramdesktop/tdesktop#2757]
It would be nice if Telegram Desktop was updated to use the iOS 10.2 emojis, like the Android version was. Would be awesome. :)

**Comment by kostyakoz** [comment]
It would be really great 👍

**Comment by chrjguill** [comment]
see #2437

**Comment by stek29** [comment]
@auchri [^](https://github.com/telegramdesktop/tdesktop/issues/2757#issuecomment-272038921)
