### ISSUE TITLE
System proxy settings on Linux are ignored.

### ISSUE THREAD

**Issue by skidnik** [telegramdesktop/tdesktop#27578]
### Steps to reproduce

1. Open a terminal emulator.
2. Set system proxy settings by executing the following:
```bash
export http_proxy=http://192.168.100.1:8080/
export https_proxy=http://192.168.100.1:8080/
export ftp_proxy=http://192.168.100.1:8080/
export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
export HTTP_PROXY=http://192.168.100.1:8080/
export HTTPS_PROXY=http://192.168.100.1:8080/
export FTP_PROXY=http://192.168.100.1:8080/
export NO_PROXY="localhost,127.0.0.1,localaddress,.localdomain.com"
```
3. Start the Telegram Desktop app from this terminal session (e.g. `./Telegram`)
4. See that Telegram Desktop app does not connect through proxy.

### Expected behaviour

Telegram Desktop app connects through proxy servers set by system proxy settings.

### Actual behaviour

Telegram Desktop app ignores system proxy settings and attempts to connect directly to Telegram servers.
Telegram Desktop behaves this way since 4.15.0. 4.14.16 respects system proxy settings. Tested using **Linux 64 bit: Binary**  from github releases.

### Operating system

Fedora 39, Ubuntu 22.04 (Jammy)

### Version of Telegram Desktop

4.15.0 - 4.15.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
not a bug, disabled intentionally.

https://github.com/telegramdesktop/tdesktop/commit/3af646a584561733269920c0f7713e2f8d5c8470

**Comment by skidnik** [comment]
Am I understanding correctly from https://github.com/telegramdesktop/tdesktop/commit/3af646a584561733269920c0f7713e2f8d5c8470 that those variables will still apply for the flatpak version.

If the option is present in the app settings and does not work it's clearly a bug, so please either remove the relevant radio button or convey in some other way that the system proxy setting is not working in the appimage and distribution packaged versions.

**Comment by john-preston** [comment]
@skidnik This is temporary while we search for a crashfix. I hope the next beta version will restore system proxy, we'll see later this week.

**Comment by Aokromes** [comment]
test after https://github.com/telegramdesktop/tdesktop/commit/a888b8d846cab7d53b63dd3e31f388ba340e9806

**Comment by ilya-fedin** [comment]
I have bad news. No stability was reached with system proxy support: beta versions with it being enabled had 6x times more crash reports than from Windows users despite Linux is only 1% of the userbase. Thus, system proxy will continue to be force-disabled.

**Comment by skidnik** [comment]
Will the system proxy setting work in the flatpak version?

**Comment by ilya-fedin** [comment]
Yeah, it should

**Comment by ilya-fedin** [comment]
Should work now. Maybe not as good as it was previously though...
