### ISSUE TITLE
Context menus are incorrectly scaled with Flatpak

### ISSUE THREAD

**Issue by ansipunk** [telegramdesktop/tdesktop#27575]
### Steps to reproduce

No clue, for some reason the issue is apparent on one PC running latest Fedora with GNOME without any custom themes, however, on other PC with latest Fedora and GNOME everything is ok. I reset all of my flatpak overrides, there should not be a single custom setting. I flipped different switches with OpenGL, hardware acceleration, scaling, Qt window frames, but the problem persists. Obviously I tried updating all of my rpm and flatpak packages, restarting, changing Flatpak and Qt/GTK themes, etc.

### Expected behaviour

Everything should look ok.

### Actual behaviour

Context menus on messages look wrong. Behavior is also weird, clicks are registered on wrong places. I checked with other issues, there were bunch of different issues with the same problem, but all were closed with some magic trick that worked for them, but not for me. Happens with any scaling factors. When I turn on experimental scaling, context menus look and behave correctly, however, performance massively drops when opening media, so I cannot use that workaround.

![image](https://github.com/telegramdesktop/tdesktop/assets/66640708/0d0fc2f3-5d0f-4dbb-9469-85d8affa12da)

### Operating system

Fedora 39

### Version of Telegram Desktop

4.15.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Advanced -> Experimental settings -> Restore default values

If this didn't help, provide the log.txt as explained by the issue template

**Comment by ansipunk** [comment]
@ilya-fedin there's no such button.

**Comment by ansipunk** [comment]
Turns out #27576 is the correct issue. I disconnected second screen and everything worked just fine. You may close this issue.

**Comment by ilya-fedin** [comment]
> https://pastebin.mozilla.org/kMo6Yjcc

Is it any better if you remove `QT_SCALE_FACTOR` environment variable?

**Comment by ilya-fedin** [comment]
Are scale factors the same on both screens? Would it get fixed if you make them use the same ones?

**Comment by ilya-fedin** [comment]
> Turns out #27576 is the correct issue.

I'm not sure... They look related but I'm not sure they have the same cause and can be fixed by one change.

**Comment by ansipunk** [comment]
@ilya-fedin I restarded my PC and the problem appeared again. I tried setting QT_SCALE_FACTOR to 1, 1.0 and none, nothing helped.

**Comment by ilya-fedin** [comment]
@ansipunk please try to unset it. It's a debug variable and shouldn't really be used for everyday use.

**Comment by ansipunk** [comment]
[Screencast from 2024-03-14 16-42-11.webm](https://github.com/telegramdesktop/tdesktop/assets/66640708/c1656e1b-3c51-4f6f-913e-3f4fb61252b7)

**Comment by ilya-fedin** [comment]
> I did. QT_SCALE_FACTOR= flatpak run org.telegram.dekstop

Try `env -u QT_SCALE_FACTOR flatpak run org.telegram.desktop`. Unset is not the same as set to empty value on Linux.

**Comment by ansipunk** [comment]
Issue persists.

**Comment by ilya-fedin** [comment]
Thank you for screencast, that's helpful

**Comment by ilya-fedin** [comment]
> Are scale factors the same on both screens? Would it get fixed if you make them use the same ones?

Please answer these questions

**Comment by ansipunk** [comment]
Yes, they are. They are exact same models. One is placed vertically.

**Comment by ansipunk** [comment]
Arranged like this:
![image](https://github.com/telegramdesktop/tdesktop/assets/66640708/88d541e2-eeb8-4ab5-a2aa-96736071d94f)

**Comment by ilya-fedin** [comment]
Can you run tdesktop like `WAYLAND_DEBUG=1 org.telegram.desktop > wayland_debug.txt 2>&1`, open the menu at the point where it's displayed right and then open it in the bugged state, quit tdesktop (so there's no more changes to the file) and upload the file?

**Comment by ansipunk** [comment]
Interesting. It works right click a link in the message, however, when i right click the whole message instead it breaks.

https://pastebin.mozilla.org/rAkwJV4F

**Comment by ansipunk** [comment]
I see. I might be able to come up with a solution if you tell me where to look.

**Comment by ilya-fedin** [comment]
try to add `LOG(("PopupMenu DPR: %1").arg(devicePixelRatio()));` to PopupMenu::paintEvent. The issue looks like the scaling factor gets changed in while drawing and that should show whether that's what happens...

**Comment by ilya-fedin** [comment]
Can you reproduce this on beta versions that use Qt 6.7.0? Maybe this issue will get different behavior just like  #27576?

**Comment by ansipunk** [comment]
Fixed with new Qt.
