### ISSUE TITLE
Crash when input Chinese with fcitx5 on linux

### ISSUE THREAD

**Issue by oodzchen** [telegramdesktop/tdesktop#27573]
### Steps to reproduce

1. Download telegram desktop from github release page
2. Launch telegram and login
3. Focus on chat input area
4. Switch fcitx5 to Chinese and typing Chinese

### Expected behaviour

Input Chinese to the input area

### Actual behaviour

Telegram desktop crash immediately on Chinese candidate words show up.

### Operating system

openSUSE Leap 15.5

### Version of Telegram Desktop

4.15.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> ### Crash ID
> 
> _No response_

You must fill this

**Comment by oodzchen** [comment]
@ilya-fedin The crash ID is 
```
928db649-b755-4415-1a83519c-c8c5027d
```
