### ISSUE TITLE
Disabling "contact joined Telegram" option has no effect

### ISSUE THREAD

**Issue by 3ternal** [telegramdesktop/tdesktop#27582]
### Steps to reproduce

1. Navigate to Settings -> Notifications and Sounds
2. Turn off the "Contact Joined Telegram" event

### Expected behaviour

User should not receive notifications when a contact joins Telegram

### Actual behaviour

User receives notifications when a contact joins Telegram

### Operating system

Windows 11

### Version of Telegram Desktop

4.15.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This option disables only sound notification

**Comment by 3ternal** [comment]
Well, I guess that means it's not a bug, but it ought to be a feature request. The current phrasing of that option is misleading, and there should be an option to disable the notifications altogether.

**Comment by ilya-fedin** [comment]
It would be a duplicate of https://bugs.telegram.org/c/65
