### ISSUE TITLE
Windows system notifications don't work

### ISSUE THREAD

**Issue by ZloyPirozhok** [telegramdesktop/tdesktop#27581]
### Steps to reproduce

If I use telegram notifications everything comes fine, but I want to use windows inbuilt notifications. So I tick the "Use windows notifications" checkbox, but after that I stop getting any notifications. This hasn't worked for a long time, neither in the portable version of Telegram nor in the install version. If I put the old version of telegram 3.7.3, and switch on "Use Windows notifications", but after upgrading to the latest version, they don't come again.

### Expected behaviour

After enabling the "Use Windows notifcations" checkbox, notifications come to the system tray

### Actual behaviour

After enabling the "Use Windows notifications" checkbox, no notifications are received

### Operating system

Windows 11 Version 22H2 (0S Build 22621.2428)

### Version of Telegram Desktop

v 4.15.0

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can you find the first bad version?

**Comment by rinrab** [comment]
> Can you find the first bad version?

I think that this is an old bug. I found this bug a few months ago but didn't report it.

**Comment by ilya-fedin** [comment]
> I think that this is an old bug. I found it a few months ago but didn't report it.

Anyway, can you?
