### ISSUE TITLE
if you record a voice message and pause it and then send it. around three seconds of the voice recordings disappear

### ISSUE THREAD

**Issue by M4K14** [telegramdesktop/tdesktop#27587]
### Steps to reproduce

record a voice on your telegram desktop
hit the pause button
click send

### Expected behaviour

it shouldn't automatically trim the voice

### Actual behaviour

the last seconds of the voice message is not recorded

### Operating system

windows 10

### Version of Telegram Desktop

4.15.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#3809?

**Comment by M4K14** [comment]
Yeah, thanks. 

It's really annoying btw
