### ISSUE TITLE
telegram desktop 如何实现阅后即焚---Telegram desktop how to realize the burn after reading

### ISSUE THREAD

**Issue by omaidb** [telegramdesktop/tdesktop#2758]
telegram desktop 如何实现阅后即焚---Telegram desktop how to realize the burn after reading

 
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by auchri** [comment]
I don't understand your issue.
