### ISSUE TITLE
Add --help (-help) commandline option or print available options on unkonwn options

### ISSUE THREAD

**Issue by dragetd** [telegramdesktop/tdesktop#27584]
### Is your feature request related to a problem?

I wanted to look up the cli options of telegram-deskop. It is surprising that `-help`, `--help`, `-h` simply start telegram.

### Describe the solution you'd like

If -help, --help or -h is passed as an option or any other unknown options, print out the list of options available (https://github.com/telegramdesktop/tdesktop/blob/d67f25d726470a049194f3fe8175d7599808969d/Telegram/SourceFiles/core/launcher.cpp#L507)

### Describe alternatives you've considered

Printing the available options on any unknown option does change the behavior, I can understand that this might not be wanted. It would be more unix-conform, but maybe some scripts out there use invalid options without knowing, which then break.

But then '-help,--help,-h' would be a nice middle-ground, as this is what people usually try first.

**Comment by ilya-fedin** [comment]
tdesktop has no options meant to be used by end users
