### ISSUE TITLE
Instant View fonts have less readability vs mobile clients

### ISSUE THREAD

**Issue by enchained** [telegramdesktop/tdesktop#27586]
### Steps to reproduce

1. Open Instant View on different clients
2. Compare fonts

### Expected behaviour

All Instant View fonts should be comfortable to read, and preferably be of similar typeface across different platforms. Ideally, in the future there should be an option to pick font typeface, size and background, just like in the mobile clients.

### Actual behaviour

Instant View fonts on tdesktop are harder to read, especially the article text font. 

tdesktop
![image](https://github.com/telegramdesktop/tdesktop/assets/6181674/588b2136-0ca9-4a04-bef9-5e9d911c1f1b)

iOS
![image](https://github.com/telegramdesktop/tdesktop/assets/6181674/037547a1-99d0-4a7c-b209-20b26f44d5cf)

Android
![image](https://github.com/telegramdesktop/tdesktop/assets/6181674/61f8847b-87ce-480f-a9ff-b77073f4110e)

Headers look pretty similar between mobile and tdesktop, but everything else uses serif font on tdesktop, while on mobile sans-serif is used. Serif font on tdesktop is pretty small, harder to read, rough around the edges, the bold parts of text look a bit squished. A slightly larger version of the usual sans-serif font of tdesktop (like in the link previews) would probably be more appropriate here. 

Currently the issue can be partially mitigated by changing the zoom level (Ctrl 0/-/+), but it resets every time.

### Operating system

Windows 11

### Display

1080p 17-inch laptop screen

### Version of Telegram Desktop

4.15.3 beta x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
9414ef570940eef138d04825289d489460309868

**Comment by enchained** [comment]
That's great, it looks much better now. Only the quote typeface still differs between both views:

![image](https://github.com/telegramdesktop/tdesktop/assets/6181674/361d67d1-ad91-4e22-9871-7bfca8f8ad7c)
![image](https://github.com/telegramdesktop/tdesktop/assets/6181674/f7ce9544-107b-4019-8d67-6f6846f18df5)
