### ISSUE TITLE
Telegram installer for windows uses an unsigned binary

### ISSUE THREAD

**Issue by karstennilsen** [telegramdesktop/tdesktop#27583]
### Steps to reproduce

1. Download latest x64 Windows setup
2. Run the setup
3. Setup unpacks a .tmp file in e.g. `%LOCALAPPDATA%\TEMP\9\IS-GO43T.TMP\TSETUP-X64.4.15.2.TMP`
4. This file is not signed

### Expected behaviour

The binary `%LOCALAPPDATA%\TEMP\9\IS-GO43T.TMP\TSETUP-X64.4.15.2.TMP` to be signed by Telegram.

The main setup.exe is signed, all relevant Telegram application executables are also signed.

Because of this missing signature it's impossible to implement secure Applocker policies in a corporate Windows setup for Telegram.

Can you please start signing the unpacked binary in the setup releases?

### Actual behaviour

The binary `%LOCALAPPDATA%\TEMP\9\IS-GO43T.TMP\TSETUP-X64.4.15.2.TMP` is not signed by Telegram.

### Operating system

Windows x64 (any version)

### Version of Telegram Desktop

4.15.2 x64 (but also earlier versions)

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
How do I do that? I prepare the setup using InnoSetup command line compiler (iscc) from a text descriptor and prepared app binaries. It generates the setup.exe which I sign after. How do I sign whatever you are talking about? I didn't even know it exists..

**Comment by karstennilsen** [comment]
This seems to describe how to make sure the tmp file is signed:
https://blog.osarmor.com/340/innosetup-sign-installer-uninstaller/
As far as I can see you can use the InnoSetup gui tool to modify the .iss file the InnoSetup cli compiler (iscc) is using.
Basically you give InnoSetup a sign command line intruction which uses the `f$` as argument of the binary to sign. This way it will both sign the setup.exe as well as the hidden .tmp file it unpacks and executes.

**Comment by karstennilsen** [comment]
Let me know if I can assist any further @john-preston

**Comment by john-preston** [comment]
@karstennilsen Ok, Thanks! I've tried to add the signtool to the InnoSetup and it signed two file, "uninst.e32.tmp" and the resulting setup. I was signing the resulting setup myself anyway, so with that step just one additional file got signed, the 
"uninst.e32.tmp". Is this enough?

**Comment by john-preston** [comment]
Yes, it looks like .tmp file that appears after setup is launched is signed now.
