### ISSUE TITLE
Access list in forum topics

### ISSUE THREAD

**Issue by alchem1ster** [telegramdesktop/tdesktop#27580]
### Is your feature request related to a problem?

I use a Telegram forum to create a shared work chat for the organization. To avoid creating many separate groups, all employees are in one place. The forum is divided into topics by areas. 
The problem is that if I want to unite, for example, only department heads and write them a message that should not be seen by other employees, I have to create a separate group outside the forum, which is extremely inconvenient when there are topics to which different combinations of participants are allowed.

### Describe the solution you'd like

Make each topic a list of forum members who can see it and post in it. Editing rights and restrictions of members, similar to groups, will be unnecessary here, but a simple access list will do.

### Describe alternatives you've considered

I have to either create groups separate from the forums with specific members, or create multiple forums with the same topics. This is inconvenient.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
