### ISSUE TITLE
 Reactions statistics graph crashes Telegram.

### ISSUE THREAD

**Issue by weirdo-neutrino** [telegramdesktop/tdesktop#27597]
### Steps to reproduce

1st way to reproduce:

Open channel's statistics.
Scroll to "Reactions" graph.
Click anywhere on graph to open details window:

![Screenshot_2024-03-14_22-42-12](https://github.com/telegramdesktop/tdesktop/assets/55913074/db3a53b2-7c0f-4bd6-b577-602eb96b85f6)

Then click again on the same column to close details window.

2nd way to reproduce:

Click anywhere on graph to open details window.
Scroll to the bottom of statistics window so details window goes out of sight.

3rd way to reproduce:

Click anywhere on graph to open details window.
Move the graph's time span line which causes details window to close.

### Expected behaviour

Not crash

### Actual behaviour

App hangs and crashes after some time. Previously they were long hangings. Today they were 1 long and 20 short (2-3 sec).

All these examples have details window closing/"going out of sight" in common. And it is true only for reactions graph. No other graph hangs and crashes app.

### Operating system

Arch Linux x86_64, Xfce4 4.18

### Version of Telegram Desktop

4.15.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Prove crash ID as instructed by the issue template

**Comment by weirdo-neutrino** [comment]
I failed to find where I can enable "beta versions installation"in "Settings" -> "Advanced". There is only "Data and storage", "Automatic media download", "Window title bar", "System integration", "Performance", "Spell checker", "Export Telegram data" and "Experimental settings".

There is no crash line in logs too.

I also tried "crashplease" cheat code. Log line is there, but no crash reporter.

**Comment by ilya-fedin** [comment]
Are you sure you filled the installation source field in the issue right?

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by weirdo-neutrino** [comment]
Crash ID: b238d026-cf47-4823-1c9c2388-7c624bec

**Comment by 23rd** [comment]
Will be fixed in the next version.
