### ISSUE TITLE
Media Viewer now appears as a transparent window in Wayland session

### ISSUE THREAD

**Issue by NTMan** [telegramdesktop/tdesktop#27598]
### Steps to reproduce

1. Run desktop under Wayland session
2. Open media in Telegram

![Screenshot from 2024-03-15 03-19-18](https://github.com/telegramdesktop/tdesktop/assets/200750/546238c6-1ce4-45b5-a41b-9ecf216959c1)

Media Viewer now appears as a transparent window
Bug was introduced in 4.15.3 beta version of Telegram desktop

### Expected behaviour

Media Viewer appears as full screen window

### Actual behaviour

Media Viewer now appears as a transparent window

### Operating system

Linux Fedora Rawhide

### Version of Telegram Desktop

4.15.4 beta

### Installation source

Static binary from official website

**Comment by strelok1111** [comment]
Same here 
GNOME Shell 45.2
Telegram 4.15.4 beta
Ubuntu 23.10

If I start X11 session all works correct

**Comment by ilya-fedin** [comment]
Sorry but I can't reproduce this. Perhaps some reproduction steps are missing. Please try to to make this reproduced in a VM to see how your steps look with a clean system.

**Comment by harshil21** [comment]
same thing for me. Except for me it's the media viewer and sometime even Telegram itself. I can't "Open Telegram" from the status bar because the window is transparent and nothing happens (sometimes. With the media player, it's 100% of the time). This started happening from 4.15.1/4.15.2. 

Ubuntu 23.10
Wayland

**Comment by strelok1111** [comment]
Revert version to 4.15.0 and all works fine, I think maybe this is wayland+nvidia+mesa issue

**Comment by ilya-fedin** [comment]
There seem to be no changes between 4.15.0 and 4.15.1 in the viewer

**Comment by strelok1111** [comment]
If there were no changes in this part between versions 4.15 и 4.15.2, maybe it's a matter of settings. Because when I started 4.15 after 4.15.2, the settings were cleared. Is there any way to clear the application settings?

**Comment by ilya-fedin** [comment]
Yeah, it could be. Try `Advanced -> Experimental settings -> Restore default values`.

**Comment by dimas1980200** [comment]
BySex_Net_19772_240p.mp4
<https://drive.google.com/file/d/1P7gtgOfFwIi_B188u2efrTKCt2gI25Fl/view?usp=drivesdk>


пт, 15 мар. 2024 г., 22:41 Strelok ***@***.***>:

**Comment by strelok1111** [comment]
4.15.2 also works fine, but 4.15.3 has this issue

**Comment by ilya-fedin** [comment]
4.15.3 has updated Qt so I don't think something could be done about it, apparenlty it's no more compatible with your hardware. If this happens only with NVIDIA, please reset the experimental settings, OpenGL with NVIDIA hardware is not supported and as soon as you change experimental settings, you lose the warranty and support.

**Comment by strelok1111** [comment]
> 4.15.3 has updated Qt so I don't think something could be done about it, apparenlty it's no more compatible with your hardware. If this happens only with NVIDIA, please reset the experimental settings, OpenGL with NVIDIA hardware is not supported and as soon as you change experimental settings, you lose the warranty and support.

:-(  i see. will use 4.15.2 until wayland or Qt or NVIDIA or mesa fix this, thank you for answer

**Comment by ilya-fedin** [comment]
Assuming you're using proprietary driver, it's not mesa but the NVIDIA company.

**Comment by TheWeirdDev** [comment]
I have the same problem with Telegram 4.15.4 on Gnome (Wayland) and I am running everything on an intel iGPU. This bug is not just on NVIDIA.

**Comment by ilya-fedin** [comment]
That's sad... Almost every minor release, Qt breaks media viewer in some way and it takes from a half of a year to a year to find fix...

**Comment by ilya-fedin** [comment]
The first thing is for you folks to find some way for developers to reproduce. No developer can test on Intel or NVIDIA hardware (personally I have only AMD) so as long as it's intel and NVIDIA specific, no developer can confirm the issue and work on it.

**Comment by TheWeirdDev** [comment]
> The first thing is for you folks to find some way for developers to reproduce. No developer can test on Intel or NVIDIA hardware (personally I have only AMD) so as long as it's intel and NVIDIA specific, no developer can confirm the issue and work on it.

I feel like it's a Wayland thing rather than the GPU brand.

**Comment by ilya-fedin** [comment]
@TheWeirdDev i would be able to reproduce then, right? But I can't

**Comment by TheWeirdDev** [comment]
When I run Telegram on XWayland the problem goes away:

`QT_QPA_PLATFORM=xcb ./Telegram`

**Comment by ilya-fedin** [comment]
Well, I run it natively on Wayland and the viewer works just fine for me.

**Comment by ilya-fedin** [comment]
I have a feel that this is an Intel-only problem the persons above have dual-GPU (PRIME) systems and thinking they have NVIDIA due to marketing.

**Comment by strelok1111** [comment]
> When I run Telegram on XWayland the problem goes away:
> 
> `QT_QPA_PLATFORM=xcb ./Telegram`

Yes this works! Thanks!

**Comment by strelok1111** [comment]
> The first thing is for you folks to find some way for developers to reproduce. No developer can test on Intel or NVIDIA hardware (personally I have only AMD) so as long as it's intel and NVIDIA specific, no developer can confirm the issue and work on it.

I can run debug version and show any log/output.

**Comment by ilya-fedin** [comment]
> I can run debug version and show any log/output.

I sadly have no idea what to ask. This looks like a GPU driver problem and I have no idea what could break in it.

**Comment by NTMan** [comment]
> I have a feel that this is an Intel-only problem, the people above have dual-GPU (PRIME) systems and saying NVIDIA due to marketing (that's what advertised as their GPU and they don't know it's mostly Intel in reality).

I am on AMD GPU

**Comment by ilya-fedin** [comment]
Maybe it's a GNOME only problem? Qt has generally poor compatibility with GNOME has regular regressions. I test on KDE Plasma Wayland.

**Comment by strelok1111** [comment]
> Maybe it's a GNOME only problem? Qt has generally poor compatibility with GNOME and regular regressions. I test on KDE Plasma Wayland and it works just fine.

Gnome on X11 works fine

**Comment by psgreco** [comment]
> I have a feel that this is an Intel-only problem, the people above have dual-GPU (PRIME) systems and saying NVIDIA due to marketing (that's what advertised as their GPU and they don't know it's mostly Intel in reality).

I can see this in my AMD CPU/GPU laptop, Fedora 40 beta, so not related to intel/nvidia

`QT_QPA_PLATFORM=xcb ./Telegram` makes it work too

**Comment by inferrna** [comment]
Output with `WAYLAND_DEBUG=1 QT_DEBUG_PLUGINS=1`
I'm on RadeonSI + Gnome + Wayland

[tg_wayland.log.gz](https://github.com/telegramdesktop/tdesktop/files/14730556/tg_wayland.log.gz)

**Comment by ilya-fedin** [comment]
> tg_wayland.log.gz

Looks like WAYLAND_DEBUG sadly doesn't reveal the interesting part:
```
[1489412.155] xdg_toplevel@56.configure(1680, 1018, array[24])
```
It just display the array size instead of its contents.

**Comment by inferrna** [comment]
Also look at screenshots of wlhax [with and without viewer](https://github.com/telegramdesktop/tdesktop/files/14733528/Screenshits.zip)

**Comment by ilya-fedin** [comment]
Perhaps Qt has broke compatibility with GNOME again? I can't reproduce on Plasma and media viewer hasn't had changes in months

**Comment by ilya-fedin** [comment]
What would be interesting to see is whether GNOME advertises suspended state to the viewer at any point of time since its creation as that sounds like a related feature supported in the new Qt

**Comment by TheWeirdDev** [comment]
> Perhaps Qt has broke compatibility with GNOME again? I can't reproduce on Plasma and media viewer hasn't had changes in months.

Can you test it in a VM?

**Comment by ilya-fedin** [comment]
> Can you test it in a VM?

No, I have a problem with spare space on my system drive... And I would rather avoid running GNOME.

**Comment by strelok1111** [comment]
Update to version 4.15.6, and problem is gone.

**Comment by harshil21** [comment]
> Update to version 4.15.6, and problem is gone.

wow you're right. I looked at the release notes and didn't upgrade cuz i thought it wouldn't fix it

**Comment by TheWeirdDev** [comment]
Yep, it works.

**Comment by NTMan** [comment]
I confirm it fixed with today update (4.15.6)

![Screenshot from 2024-03-26 02-15-41](https://github.com/telegramdesktop/tdesktop/assets/200750/3c000d2b-c351-4813-856b-918e64974f4f)

**Comment by karamanliev** [comment]
This is still broken in 4.16.6 for me.

`QT_QPA_PLATFORM=xcb telegram-desktop` fixes it though

I'm using Gnome Wayland 46 with Nvidia GPU

**Comment by ken-kuro** [comment]
I used the latest built binary at https://telegram.org/dl/desktop/linux, however, this is still broken for me. I'm using Gnome 46 + Wayland and an iGPU.

**Comment by ken-kuro** [comment]
Checked again with flatpak version, it works well, might be relates to dependencies on my arch machine

**Comment by thagabe** [comment]
After reading this, looks like this issue is driver agnostic. The issue stems from Qt changes as it doesn't affect my PopOS laptop Intel iGPU but does affect Arch Linux with Nvidia drivers.

**Comment by ilya-fedin** [comment]
@thagabe you can use official binaries with bundled Qt that is verified to work correctly

**Comment by thagabe** [comment]
Indeed, the official binaries are working correctly.

**Comment by ken-kuro** [comment]
If you're using Wayland Gnome like me, the issue has been fixed in the newest release of mutter, so just update it and try again https://gitlab.gnome.org/GNOME/mutter/-/issues/3435

**Comment by thagabe** [comment]
I noticed earlier this week that the media viewer worked fine on the pacman install so this is all good 👍🏻 Thanks @ken-kuro

**Comment by karamanliev** [comment]
> I noticed earlier this week that the media viewer worked fine on the pacman install so this is all good 👍🏻 Thanks @ken-kuro

Can confirm that pacman version is all good now.

**Comment by LindseyRenea** [comment]
Thank you all soo much on my journey ❤️
