### ISSUE TITLE
Feature Request: Disable Emoji/Sticker button auto popup on hover, at least as an option

### ISSUE THREAD

**Issue by thwerks** [telegramdesktop/tdesktop#27599]
### Is your feature request related to a problem?

how many times now im typing a way only to realize im not typing anything because this asinine sticker/gif popup windows has come up. why even have a button when you dont even have to click it. I almost never use emoji/gif/stickers and if you even get near that button, up comes things i dont want or need. 

its a natural movement to click the text field and move the cursor out of the way to the right to not be obstructing. Horizontal mouse movements require less effort and are therefor more likely to be used. 

### Describe the solution you'd like

at the very least have an option to only popup the sticker popup on a direct click of the button

### Describe alternatives you've considered

this option should probably go in the chat options menu

**Comment by john-preston** [comment]
@thwerks There is an experimental option for that in Settings > Advanced > Experimental settings.
