### ISSUE TITLE
0.10.21 Alpha groups names now showing.

### ISSUE THREAD

**Issue by Mouamle** [telegramdesktop/tdesktop#2759]
### Expected behaviour
The groups names should be colored black ;-;

### Actual behaviour
The groups names are colored white

### Configuration
**Operating system:**
Windows 8.1

**Version of Telegram Desktop:**
0.10.21 alpha

![1](https://cloud.githubusercontent.com/assets/10764639/21576590/e1c87e9c-cf46-11e6-9355-cf597394934d.PNG)

**Comment by john-preston** [comment]
@Mouamle Thank you for your report! This will be fixed in the next version.

**Comment by Geobert** [comment]
0.10.22a fixes this
