### ISSUE TITLE
Instant view doesn't remember last location

### ISSUE THREAD

**Issue by seth-rah** [telegramdesktop/tdesktop#27605]
### Steps to reproduce

1. Have 2 monitors
2. Put Telegram on your secondary display
3. Open instant view on any supported link

### Expected behaviour

Instant view opens on the same display / location as the Telegram Desktop window

### Actual behaviour

Instant view open up on the opposite monitor

### Operating system

Windows 10

### Version of Telegram Desktop

4.15.4 Beta

### Installation source

Static binary from official website

**Comment by seth-rah** [comment]
Confirmed the same issue is present on MacOS

**Comment by Aokromes** [comment]
try on latest version

**Comment by seth-rah** [comment]
Appears to be working on my end

Thanks
