### ISSUE TITLE
Не получается открыть картинку или историю для просмотра.

### ISSUE THREAD

**Issue by VitaliyMkhchyan** [telegramdesktop/tdesktop#27604]
### Steps to reproduce

1. Открыть картинку

### Expected behaviour

Должно появиться окно с картинкой

### Actual behaviour

Появляется невидимое окно с иконкой Telegram

### Operating system

Fedora 39

### Version of Telegram Desktop

4.15.4 beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This is an English-only bugtracker
