### ISSUE TITLE
0.10.21: Clicking notification when Telegram is minimized results in Telegram opening in resized window (Qt::WindowNoState) instead of Qt::WindowMaximized if used

### ISSUE THREAD

**Issue by Sheigutn** [telegramdesktop/tdesktop#2760]
### Steps to reproduce:
1. Open Telegram in maximized window mode
2. Minimize it
3. Click on a notification

### Expected behaviour:
Telegram should also open in maximized window mode (**Qt::WindowMaximized**) if it was minimized in this mode.

### Actual behaviour:
Telegram opens in resized window mode (**Qt::WindowNoState**).

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
0.10.21 alpha

**Comment by Sheigutn** [comment]
It's still not fixed, also not in version 1.0.

**Comment by Sheigutn** [comment]
@auchri Would you please reopen this issue?

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
