### ISSUE TITLE
Brew wont upgrade telegram

### ISSUE THREAD

**Issue by np25071984** [telegramdesktop/tdesktop#27614]
### Steps to reproduce

I see this "Update Telegram" pop up quite often. 

<img width="442" alt="image" src="https://github.com/telegramdesktop/tdesktop/assets/19670887/fa0b2f90-aa69-473d-8a02-e39cd9760df2">

There are two questions:

1. How to turn it off? I update all my apps once a week via terminal and don't want to see this popup between the updates.
2. How to update Telegram via command line? 

```
$ brew upgrade --cask --greedy
$ brew info telegram
==> telegram: 10.9,260554 (auto_updates)
https://macos.telegram.org/
/opt/homebrew/Caskroom/telegram/10.9,260554 (122B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/t/telegram.rb
==> Name
Telegram for macOS
==> Description
Messaging app with a focus on speed and security
==> Artifacts
Telegram.app (App)
==> Analytics
install: 3,240 (30 days), 10,610 (90 days), 38,146 (365 days)
$ brew --version
Homebrew 4.2.12
```

### Expected behaviour

I expected to get Telegram updated after running `brew upgrade --cask --greedy` command.

### Actual behaviour

Nothing happened. Looks like cask brew don't have the last version yet

### Operating system

MacOS Sonoma 14.2.1

### Version of Telegram Desktop

10.9.260554 Stable

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift
