### ISSUE TITLE
В windows-версии приложения Telegram не отображается свыше 21 темы в чатах.

### ISSUE THREAD

**Issue by mountain-biker85** [telegramdesktop/tdesktop#27616]
### Steps to reproduce

Есть чат с 22 темами. В iOS-приложении видно все темы, а если открыть чат в Windows-приложении, то про пролистывании списка тем видно только 21 тему, а 22-я тема уже не отображается. Проблема была замечена только в winows-версии. На iOS и web-версиях всё отображается корректно. Android-версию проверить возможности не было.

### Expected behaviour

.

### Actual behaviour

.

### Operating system

Windows10

### Version of Telegram Desktop

4.15.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
this bug tracker is english only, plz, update your issue or it will be closed on 24h.
