### ISSUE TITLE
Invalid counter of chats

### ISSUE THREAD

**Issue by henrypp** [telegramdesktop/tdesktop#27612]
### Steps to reproduce

open telegram
открой телеграм

### Expected behaviour

normal display of number above 99
нормальное отображение чисел выше 99

### Actual behaviour

displays all numbers above 99 as 99+
отображает все числа выше 99 как 99+

![sshot-001](https://github.com/telegramdesktop/tdesktop/assets/3902025/c299e35d-37f9-4dad-bec2-fa5f487a9541)

приходится мобильное приложение открывать чтоб увидеть акуальное число

### Operating system

win11

### Version of Telegram Desktop

every

### Installation source

Static binary from official website

**Comment by henrypp** [comment]
вообще любое 3-х значное число (да даже 4-х значное) должно нормально рендерится, зачем эта хрень с обрезанием?

**Comment by Aokromes** [comment]
this bug tracker is english only, plz, update your issue or it will be closed on 24h.

**Comment by henrypp** [comment]
@Aokromes and russian command and creator isnt here?

**Comment by Aokromes** [comment]
> @Aokromes and russian command and creator isnt here?

it's but more people contribute here.

**Comment by henrypp** [comment]
@Aokromes and what happenned? authors forgot about this issue?

**Comment by henrypp** [comment]
devs cannot fix this terrible BUG, it is not my problem!

**Comment by henrypp** [comment]
охуеть, и года не прошло как эту залупу исправили наконец!

**Comment by 23rd** [comment]
🤝
