### ISSUE TITLE
Deleting message

### ISSUE THREAD

**Issue by thissaksham** [telegramdesktop/tdesktop#27610]
### Is your feature request related to a problem?

Yes. The other user can delete my message.

### Describe the solution you'd like

I would like a toggle which gives me power to disable or enable the other user from deleting the messages I have sent

### Describe alternatives you've considered

None

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
but it will be a won't fix.
