### ISSUE TITLE
Inline bots seems to have stopped working in Linux

### ISSUE THREAD

**Issue by fmmarzoa** [telegramdesktop/tdesktop#2761]
### Steps to reproduce
1. Type in @gif whatever into a conversation
2. It will even show autocompletion for @gif, but it won't show anything, whatever "whatever" you use

I have checked that at least @music bot has the same problem, for example with @music vivaldi

### Expected behaviour
It should show a bunch of gifs to share instead for @gif, and some music for @music

### Actual behaviour
It shows nothing at least for those bots

### Configuration
**Operating system:**
Linux Ubuntu 16.04

**Version of Telegram Desktop:**
0.10.20
0.10.1

I have checked those two, but previous versions MAY be affected too.
### Logs
[2016.12.31 16:00:50] RPC Error: request 32 got fail with code 400, error BOT_INVALID
[2016.12.31 16:00:51] RPC Error: request 33 got fail with code 400, error BOT_INVALID

**Comment by john-preston** [comment]
@fmmarzoa What version do you try? Current version is 0.10.20 stable and 0.10.22 alpha.

**Comment by fmmarzoa** [comment]
OK, I have updated it by hand to version 0.10.20. The problem persists.

**Comment by MasterGroosha** [comment]
Kubuntu 16.04. Inline bots such as @music and @pic work fine.  
Telegram Desktop 0.10.22 alpha

**Comment by JuanPotato** [comment]
Arch Linux Inline bots also work fine
Tdesktop 0.10.22a

**Comment by fmmarzoa** [comment]
I'll try the alpha version ASAP and update you then.

**Comment by fmmarzoa** [comment]
0.10.23a does not work for me neither.

This is from the logs:

Trying to use @gif:

[2017.01.01 20:46:32] RPC Error: request 14 got fail with code 400, error BOT_INVALID


Trying to use @music:
[2017.01.01 20:46:44] RPC Error: request 23 got fail with code 400, error BOT_INVALID
[2017.01.01 20:46:50] RPC Error: request 24 got fail with code 400, error BOT_INVALID

Now, this is weird, @pic does actually work, but produces these errors in the log nonetheless:
[2017.01.01 20:47:00] TCP Error: network - Network unreachable
[2017.01.01 20:47:00] TCP Error: network - Network unreachable
[2017.01.01 20:47:00] HTTP Error: network error 99 - Network unreachable
[2017.01.01 20:47:00] HTTP Error: network error 99 - Network unreachable

I am going to delete the ~/.Telegram directory to see what happens.

**Comment by fmmarzoa** [comment]
Ok, after removing the ~/.TelegramDesktop, rebooting, restarting Telegram and configuring it again with the code sent to my phone, everything works as expected. So, it seems it something related to the configuration that was broken at some update before, maybe at 0.10.1 since it seems it had been unable to update automatically since then.

Now, to sum it up, this is what I have done:

- Update manually to 0.10.23a version
- Delete the whole ~/.TelegramDesktop directory
- Reboot my laptop
- Restart Telegram, configure my phone number and enter the code needed so it started to work again.

Probably the update wasn't needed, just in case someone else find this problem and want to give a try from the ~/.TelegramDesktop directory deletion, but I am not going to rollback anyway.

Anyway, I'll ask a friend that have been having the same problems with a Slackware to try it.

Thank you.

**Comment by stek29** [comment]
Inline bots sometime stop working, and that has nothing to do with TDesktop.

**Comment by fmmarzoa** [comment]
They were working perfectly until they stop working on the desktop version whilst they continue working perfectly in my iPhone and my Android tablet. They started to work again right after deleting the ~/.TelegramDesktop directory and thus resetting the whole configuration.

Anyway, I am closing this.
