### ISSUE TITLE
Do not include muted chats in unread count on folder badge

### ISSUE THREAD

**Issue by oom-** [telegramdesktop/tdesktop#27624]
### Is your feature request related to a problem?

Hello, 
I made few folders to organize my telegram and uncheck the ``Include muted chats in unread count`` option.

But I still get a +1 count on the folder badge when one muted chat in the folder get unread message(s):
![image](https://github.com/telegramdesktop/tdesktop/assets/11071671/3d5b5f4f-b927-4514-996c-3afe8b1c397b)

### Describe the solution you'd like

It should be an option to not ``include the unread muted chats at the folder count level`` as well.

### Describe alternatives you've considered

x

**Comment by ilya-fedin** [comment]
#7634
