### ISSUE TITLE
Viewing images and videos does not work

### ISSUE THREAD

**Issue by deadraid** [telegramdesktop/tdesktop#27625]
### Steps to reproduce

1. click on any image or video.
![Screenshot from 2024-03-19 23-53-40](https://github.com/telegramdesktop/tdesktop/assets/6043834/1642ac06-7328-4ca8-8a43-0944ab4dd508)

### Expected behaviour

View an image or video in a separate window.

### Actual behaviour

Clicking on any image or video only causes a notification but not the display of the image or video itself. If you minimize Telegram window in the tray at this moment, Telegram hangs.

### Operating system

Ubuntu 23.10 Gnome

### Version of Telegram Desktop

4.15.5 beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#27598
