### ISSUE TITLE
Bug in apply the theme

### ISSUE THREAD

**Issue by TiagoDanin** [telegramdesktop/tdesktop#2762]
### Steps to reproduce
1. Open settings
2. Interface Scale > 125% (or 150% or 200%)
3. Open a theme file (https://gist.github.com/TiagoDanin/f518ccbcb67ac8743c054f6ec4e62fb0)

### Expected behaviour
![image](https://cloud.githubusercontent.com/assets/5731176/21578344/a71d86b2-cf63-11e6-8c72-48ca38215e5c.png)
Without button to apply the theme

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/5731176/21578320/c6ddf37a-cf62-11e6-8eb6-fa9a6d6737a7.png)

Button to apply the theme

### Configuration
**Operating system: Windows 10**

**Version of Telegram Desktop: 0.10.22**

**Comment by MasterGroosha** [comment]
Have you packed your colors file into zip-archive named your_theme.tdesktop-theme?

**Comment by TiagoDanin** [comment]
@MasterGroosha Use only the "colors.tdesktop-theme"

**Comment by john-preston** [comment]
Thanks for your report. This will be fixed in the next version.

**Comment by TiagoDanin** [comment]
Close: Resolved!
