### ISSUE TITLE
Tray icon Notification missing after KDE Plasma 6 update

### ISSUE THREAD

**Issue by serhumanos** [telegramdesktop/tdesktop#27635]
### Steps to reproduce

1. Enable tray icon and notifications
2. Wait for some new message

### Expected behaviour

notification appear as red dot with a white number of un read messages

### Actual behaviour

The tray icon is the same blue telegram

### Operating system

KDE Neon Plasma 6

### Version of Telegram Desktop

4.15.5-beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I can't reproduce, that's how it looks like for me: ![](https://github.com/telegramdesktop/tdesktop/assets/17829319/80e5db16-6191-48a7-93d4-de2678d280e3)

**Comment by serhumanos** [comment]
> I can't reproduce, that's how it looks like for me: ![](https://private-user-images.githubusercontent.com/17829319/316115503-80e5db16-6191-48a7-93d4-de2678d280e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNDczMDgsIm5iZiI6MTcxMTE0NzAwOCwicGF0aCI6Ii8xNzgyOTMxOS8zMTYxMTU1MDMtODBlNWRiMTYtNjE5MS00OGE3LTkzZDQtZGUyNjc4ZDI4MGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDIyMzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5OTc2MDRmOWIzMGZhZDYwZTBmMmM1Njk5Nzc0YjIzNzhlMGRhOTA5MjU1NjhlZTEzMTRkNWVkNGU0ODZmNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wqmYLDWA-mGNQjgdl1-lVG4Cyz4yFDgj2UHJkYjYlAU)

Are you using the official package for linux (no snap or flatpak) ?
my telegran tray icon is blue circle with a white paper plane 
![imagen](https://github.com/telegramdesktop/tdesktop/assets/7744939/73eafb89-1af9-4784-bedf-f657048e6090)
and when there is a new message a red dot used to appear with the number of unread messages in white.

I will mount 2 Virtual machines to compare and I will post again.

**Comment by ilya-fedin** [comment]
> Are you using the official package for linux (no snap or flatpak) ?

Yeah

> my telegran tray icon is blue circle with a white paper plane

Yes, but I use a clean VM. If you have done any customization to your system, you have to find all related customizations leading to the issue in steps to reproduce. I can't really guess that.

**Comment by serhumanos** [comment]
After a few test, I confirm that Telegram is OK!, the lack of "unread messages count" is because of a problem with the icon set, if I try the default Breeze, it look like the past image (no counter with this Icon set too), but if I try others Icons sets, the couter notification y tray icon appears.

Thanks for your time!

**Comment by serhumanos** [comment]
Sorry for re-open this issue, but the in default Icon set, no counter appears, only a dot, but no number on it, as you show in your screenshot

**Comment by ilya-fedin** [comment]
Yeah, that's intended, icon could have either a dot or a counter, what is present depends on the icon theme

**Comment by serhumanos** [comment]
> Yeah, that's intended, icon could have either a dot or a counter, what is present depends on the icon theme

thanks for your reply, sorry if this question is off topic you can close this issue anytime, so, i want to ask you if the notification counter is an specific icon (so i can change or make a new one)

thank again

**Comment by ilya-fedin** [comment]
It depends on icon name. If the icon name is named `telegram`, it's not supposed to have an indicator and the counter will get applied on top. If it's named `telegram-{,mute-, attention-}panel` then it's supposed to already have some indicator and the counter won't get applied on top.
