### ISSUE TITLE
Something has happened with the UI scaling

### ISSUE THREAD

**Issue by MerryPanda** [telegramdesktop/tdesktop#27631]
### Steps to reproduce

Launch the app

### Expected behaviour

Telegram's scaling is the same as Monitor's scaling, everything is smooth.

### Actual behaviour

The default scaling is too big and all ui details and fonts are not smooth.

### Operating system

Windows 10 x 64

### Version of Telegram Desktop

4.15.2 x 64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Provide screenshots and logs. The latter is explained how to get when you create issue.

**Comment by MerryPanda** [comment]
I have reinstalled the app and it works as expected. Sorry for the false alarm 😊

**Comment by MerryPanda** [comment]
I have reinstalled the app and it works as expected. Sorry for the false alarm 😊
