### ISSUE TITLE
Quit Telegram runs Telegram just to close it

### ISSUE THREAD

**Issue by PavanLuca** [telegramdesktop/tdesktop#27638]
### Steps to reproduce

1. Add Telegram to the dock
2. Right-click Telegram on the dock
3. Click Quit Telegram

### Expected behaviour

Logically, this option shouldn't be there if it just starts Telegram to then close it immediately after it has been started. Moreover Telegram is ALREADY closed, and not even running in background.

### Actual behaviour

Telegram is opened and then closed immediately, a nonsense feature.

### Operating system

Zorin OS Core 17.1, Wayland or Xorg doesn't matter, the option is visible anyway and does the same on both

### Version of Telegram Desktop

4.15.2

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
As far as I know, there's no control over when the option is to be shown by the system, so nothing cloud be done on that.

**Comment by ruizlenato** [comment]
Same here

**Comment by PavanLuca** [comment]
Like my Zorin OS Core, so it's possible that depends on GNOME. But by what [I asked on the dedicated Zorin OS forum](https://forum.zorin.com/t/quit-telegram-on-its-context-menu-but-its-already-closed/36203) I don't know exactly, Linux distros and their dependencies and interactions matters between software, OS and hardware is amazingly complicated to me so I never understand who to report issues and bugs 🤷.

**Comment by ilya-fedin** [comment]
I don't think any side will accept this is a bug. They made the API the way they like it and they likely don't care about this niche thing most people won't notice anyway

**Comment by PavanLuca** [comment]
In my opinion, every detail is important. As unimportant as a button like that may seem, the fact that no one cares to make it work as it should can give the feeling that there's no interest in improving the software as far as you can and stick to making it perfect. I'd definitely fix it myself if I only knew how to do it, assuming it won't be fixed. Personally I wouldn't mind removing this option permanently, after all clicking the icon to open Telegram and clicking 🗙 from the title bar to close it seems enough to me.

**Comment by ilya-fedin** [comment]
> I'd definitely fix it myself if I only knew how to do it

It goes through the static actions standardized in freedesktop desktop spec. You need to find where your DE implements it (usually the panel) and add some runtime API to check whether it should be shown. Then, you need to implement the same API you invented in tdesktop and other apps you're interested in.

IIRC there also was some spec used for runtime actions made by Unity but it's not widely implemented AFAIK.

**Comment by PavanLuca** [comment]
In my head it was much more simple, like removing the piece of code from the proper configuration file that tells the context menu to display **Quit Telegram**, that's it 😄.

**Comment by ilya-fedin** [comment]
You can remove the action from the desktop file but that will remove it at all, even if tdesktop is running

**Comment by ilya-fedin** [comment]
> In my head it was much more simple

btw, people saying "Why you can't do this simple thing???" for not simple things at all is quite a frequent phenomenon on GitHub, I noticed 😅
