### ISSUE TITLE
Application window not always hiding on tray icon click

### ISSUE THREAD

**Issue by gudvinr** [telegramdesktop/tdesktop#27632]
### Steps to reproduce

1. Open Telegram Desktop
2. Press on tray icon

### Expected behaviour

App hides its window

### Actual behaviour

App might not hide its window.  
You need to click on icon multiple times.

Sometimes, switching to different application and then clicking on icon helps.

Happens with BOTH prebuilt version from telegram website and distro built version.
Currently I have [extra/telegram-desktop](https://archlinux.org/packages/extra/x86_64/telegram-desktop/) which I installed in hopes to fix this issue, but it didn't.

Also this is not Plasma 6 issue because I had this on 5.27 as well (and maybe earlier too but not sure).

### Operating system

Arch Linux, KDE Plasma 6.0.2

### Version of Telegram Desktop

4.15.2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
It activates the window if it's not active already. This was the expected behavior for everyone so far...

**Comment by ilya-fedin** [comment]
I don't think this will ever be fixed, sorry. Focus handling is very bugged on Wayland, there are multiple ways of doing that and Qt is poor on that. I recommend to switch to Wayland.

**Comment by ilya-fedin** [comment]
Actually, even though I remember similar reports in the past, I can't reproduce this and confirm the issue. Sorry.

**Comment by gudvinr** [comment]
It could be that Plasma 6/Qt 6.6 had some focus-related issues because now I don't experience same issue anymore.

Qt updated to 6.7 and Plasma is 6.0.3 now.
