### ISSUE TITLE
 High CPU usage when offline  - linux

### ISSUE THREAD

**Issue by mark-herbert42** [telegramdesktop/tdesktop#27634]
### Steps to reproduce

1.Disconnect  network.
2.Enjoy 100% CPU usage from telegram desktop.

The issue is coming from ugly useless animated dialog constantly rotating circle and showing countdown "automatically reconnecting in % sec"  and giving option "reconnect now"

The issue can be a bit overriden by disabling interface animations - then CPU usage gets down from 100% of 1 core to 1-2%.  But it disables all animations which are not as bad as this constantly running CPU hog.  And also even disabling rotating circle it still eats the CPU for running countdown.   

### Expected behaviour

For me personally this dialog is useless. It is just a  battery eater, and practical use of it is zero. But maybe someone use it, so why not make it static?  No rotating circles. dynamic countdown.  Message like " Trying to reconnect"  . button "reconnect now" and the shield-button for shortcut to proxy settings  wil do exactly the same job.  

### Actual behaviour

If I just put my laptop to bag without suspending it and go out of wifi conncection with telegram running I get out exteremely hot device with drained batery  - and only program that eat all my battery is this beyond stupid animated dialog on the left-botton edge of telegram-desktop window.

### Operating system

Linux , both Xorg and Wayland sessions, 

### Version of Telegram Desktop

All inclusing latest beta 4.15.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#8068
