### ISSUE TITLE
Instant View Window doesn't use system window frame

### ISSUE THREAD

**Issue by shishkevichd** [telegramdesktop/tdesktop#27639]
### Steps to reproduce

1. Enable `Advanced -> Use system window frame` option
2. Find any post with Instant View and open it.

### Expected behaviour

Instant View window use the system title bar when the `Use system window frame` option is enabled.

### Actual behaviour

Instant View window uses Telegram Desktop title bar, even though `Use system window frame` option is enabled

![Screenshot](https://github.com/telegramdesktop/tdesktop/assets/135337715/74abba24-80f5-48eb-9014-57a33bd899fe)

### Operating system

Windows 10 21H2

### Version of Telegram Desktop

4.15.5 beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
It's only for main window. None of the supplementary windows (call, instant view, media viewer) are meant to be affected by the option.
