### ISSUE TITLE
QR code is not generated when try to connect first time

### ISSUE THREAD

**Issue by sergueikp** [telegramdesktop/tdesktop#27647]
### Steps to reproduce

Install telegram for Ubuntu 22.04
Click on telegram icon
Click on button Start messaging

### Expected behaviour

QR code must be generated to connect to my account
Log in using phone number must be working

### Actual behaviour

QR code is not generated
Log in using phone number is not working

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.15.2

### Installation source

Snap

**Comment by Aokromes** [comment]
duplicate
