### ISSUE TITLE
Telegram does not accept a call from a microphone connected to a sound card

### ISSUE THREAD

**Issue by Rostov4an1n** [telegramdesktop/tdesktop#27644]
### Steps to reproduce

1. I have a sound card to which a microphone is connected, operating in the "2 channel, 24 bit, 48000 Hz (Studio recording)" mode
<details> 
  <summary>Image</summary>
  <img src="https://github.com/telegramdesktop/tdesktop/assets/84803793/16480132-1471-4168-98b7-c625299b19dd">
</details>

2. There is no sound from the microphone at any attempt to communicate, but as soon as I select the "1 channel" mode, the sound appears, but this mode is experimental and is not supported in most applications, because it only works in the old version of the drivers"

3. In the web version of Telegram, the sound with the "2 channel" mode works

4. The problem is that Telegram Desktop does not accept all sound modes, namely "2 channel"

### Expected behaviour

So that Telegram can work in all sound modes

### Actual behaviour

You have to communicate only through the Web version

### Operating system

Windows 11 Pro

### Version of Telegram Desktop

4.15

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This is the library used for sound, please report to it
https://github.com/kcat/openal-soft/issues
