### ISSUE TITLE
The function of publishing posts by timer is missing

### ISSUE THREAD

**Issue by kartavenko1983** [telegramdesktop/tdesktop#27643]
### Is your feature request related to a problem?

The function of publishing posts by timer is missing

### Describe the solution you'd like

Please make it possible to publish posts in channels on a timer at a certain time. The feature is needed not only in desktop clients, but also in mobile versions of Telegram. Therefore, please convey this wish to the developers of mobile clients.

### Describe alternatives you've considered

Please make it possible to publish posts in channels on a timer at a certain time. The feature is needed not only in desktop clients, but also in mobile versions of Telegram. Therefore, please convey this wish to the developers of mobile clients.

### Additional context

There is similar functionality, for example, on YouTube or VK

**Comment by Aokromes** [comment]
if you mean schedule it's already present.

**Comment by kartavenko1983** [comment]
@Aokromes,  Yes, that's exactly what I mean, but how do I use it? I didn't find it on my channel

**Comment by Aokromes** [comment]
write text, right click over send message->schedule.

**Comment by kartavenko1983** [comment]
I understand you, thank you, the topic is closed.
