### ISSUE TITLE
Telegram Desktop Cannot remember the last window position 

### ISSUE THREAD

**Issue by ikool-cn** [telegramdesktop/tdesktop#27652]
### Steps to reproduce

1.Open Telegram Desktop
2.Drag Telegram Desktop to the middle of the screen
3.Close Telegram Desktop
4.Click on tray icon

### Expected behaviour

Telegram Desktop  displays on last position of the screen

### Actual behaviour

Telegram Desktop always displays on the top left corner of the screen

### Operating system

ubuntu 22.10

### Version of Telegram Desktop

4.15.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
That is a system restriction, nothing tdesktop can do about
