### ISSUE TITLE
Cannot delete messages 0.10.22a

### ISSUE THREAD

**Issue by JuanPotato** [telegramdesktop/tdesktop#2765]
### Steps to reproduce
1. Try to delete message by right clicking and selecting delete

### Expected behaviour
Message should delete

### Actual behaviour
Message does not delete

### Configuration
Linux, tdesktop 0.10.22a

I can't delete messages in any chat (private, supergroup, group, channel) and it doesn't matter if they are before 2017.

**Comment by john-preston** [comment]
@JuanPotato Are you talking about messages in chats with users, in group chats, in supergroup chats or in channels?

**Comment by JuanPotato** [comment]
@john-preston The last line meant to say that in any scenario where I should be able to, (with permissions of course) I am not. But I found that selecting the messages and pressing delete does bring up the delete message box. But right clicking and selecting delete does nothing.

**Comment by john-preston** [comment]
@JuanPotato What OS do you try this on?

**Comment by JuanPotato** [comment]
@john-preston I believe I mentioned in the first post, but I'm running Arch Linux with Awesome as my window manager (X11)

**Comment by john-preston** [comment]
@JuanPotato I can't reproduce that in Ubuntu, Windows or macOS :(

**Comment by JuanPotato** [comment]
Ok, so I removed ~/.TelegramDesktop and download the latest alpha and stable. Signed in on both. I can delete in the stable, but not the alpha. Note, I can still delete by using the big Delete button at the top, but right clicking and selecting delete doesn't do anything. I'll see what's the most minimal setup I can make that still has this issue. I'll boot up from a live cd of Arch Linux and see if this is still reproducible

**Comment by john-preston** [comment]
@JuanPotato Please also test if the Select / Forward / Reply buttons work fine from the context menu.

**Comment by JuanPotato** [comment]
@john-preston I just checked and everything works from the context menu, except deleting.

**Comment by john-preston** [comment]
@JuanPotato And if you select one message (so that you see the "Delete" button in the top bar) and then right click it and choose "Delete Selected", will you see the confirmation about the deleting of 1 message?

**Comment by JuanPotato** [comment]
@john-preston Nope, I tried that but forgot to tell you. Clicking the top bar still works as expected

**Comment by JuanPotato** [comment]
0.10.23a still didn't fix this on my setup :\

**Comment by john-preston** [comment]
@JuanPotato I could reproduce that in Linux Mint with LXDE, so I hope I will be able to fix this in the next version.

**Comment by JuanPotato** [comment]
Nice

**Comment by john-preston** [comment]
@JuanPotato Please check the new 0.10.25 alpha version and tell me if it's fixed.

**Comment by JuanPotato** [comment]
@john-preston The issue has been fixed, thank you
