### ISSUE TITLE
Timeout descriptor error on linux version

### ISSUE THREAD

**Issue by ruvasik** [telegramdesktop/tdesktop#27653]
### Steps to reproduce

Run linux version over proxychains

For test:
strace proxcychains ./Telegram

Same behavior with run over torsocks

### Expected behaviour

Telegram runned over proxychains & routing by proxies

### Actual behaviour

run over proxychains - just not running telegram

### Operating system

Debian/Tails

### Version of Telegram Desktop

4.15.2

### Installation source

Static binary from official website

### Logs

```shell
proxychains

pipe2([3, 4], O_CLOEXEC)                = 0
pipe2([5, 6], O_CLOEXEC)                = 0
access("/etc/proxychains4.conf", R_OK)  = 0
openat(AT_FDCWD, "/etc/proxychains4.conf", O_RDONLY) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=3731, ...}) = 0
read(7, "# proxychains.conf  VER 4.x\n#\n# "..., 4096) = 3731
write(4, "\0\0\0\0\0\0\0\0\v\0\0\0\0\0\0\0", 16) = 16
write(4, "...", 11)            = 11
select(6, [5], NULL, NULL, NULL


torsocks

rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 😍 = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
statfs("/sys/fs/selinux", 0x7ffe6b1f2c70) = -1 ENOENT (No such file or directory)
statfs("/selinux", 0x7ffe6b1f2c70)      = -1 ENOENT (No such file or directory)
getuid()                                = 0
geteuid()                               = 0
futex(0x7d80e7d6a0c8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7d80e8353068, FUTEX_WAIT_PRIVATE, 2, NULL
```

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and test again.

**Comment by ruvasik** [comment]
v 4.15.6 - the same

**Comment by ilya-fedin** [comment]
I don't think this will work. Those programs like proxychains seem to do dirty hooks so a crash is expected.

**Comment by ruvasik** [comment]
Why was closed?
Work in proxy chains (tor too) - good functionality for anonymously.

**Comment by ilya-fedin** [comment]
Because proxychains hooks the code, this is expected
