### ISSUE TITLE
Telegram Desktop points to obsolete changelog

### ISSUE THREAD

**Issue by mxdpeep** [telegramdesktop/tdesktop#27659]
### Steps to reproduce

1. click main menu
2. click bottom application semver

### Expected behaviour

go to actual https://github.com/telegramdesktop/tdesktop/releases

### Actual behaviour

go to obsolete https://desktop.telegram.org/changelog

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

4.15.6-beta

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
duplicate.
