### ISSUE TITLE
Telegram desktop creates extra icon on Ubuntu

### ISSUE THREAD

**Issue by VadimVadimVadim1337** [telegramdesktop/tdesktop#27655]
### Steps to reproduce

Boot into ubuntu 23.10
sudo add-apt-repository ppa:atareao/telegram
sudo apt update && sudo apt install telegram
launch telegram through the icon

The icon appears here /home/{YourName}/.local/share/applications

org.telegram.desktop._18faa92ddda377ceaa5a576303af9e59.desktop
If you delete it, it will still appear the next time you launch it.

### Expected behaviour

There will be only one telegram icon

### Actual behaviour

I have two telegram icons

### Operating system

 Ubuntu 23.10 x86_64

### Version of Telegram Desktop

4.15.2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
This package is done by third party and no one here can fix it. Feel free to get official version from https://desktop.telegram.org.
