### ISSUE TITLE
One of lines (delete messages for everyone) doesn't appear full in dialog box

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2766]
TDesktop 0.10.23 alpha, When deleting my message in supergroup, word "chat" doesn't appear in dialog box.

![image](https://cloud.githubusercontent.com/assets/2780044/21582800/016c1222-d078-11e6-95eb-b95583aaac3e.png)

**Comment by john-preston** [comment]
@MasterGroosha Thank you for your report. This will be fixed in the next version.

**Comment by MasterGroosha** [comment]
btw, this is minor and I don't know whether to open a separate issue, but should strings:  
```"lng_delete_for_me_hint" = "This will delete {count:_not_used_|it|them} just for you.";
"lng_delete_for_me_this_hint" = "This will delete it just for you.";```

appear when deleting messages in chat with yourself?

**Comment by john-preston** [comment]
@MasterGroosha Yes, thanks. It should not appear there.
