### ISSUE TITLE
Add code block formatting support ON FORMATING SECTION, not a duplicate

### ISSUE THREAD

**Issue by vadimk1337** [telegramdesktop/tdesktop#27661]
### Is your feature request related to a problem?

This is unfairly closed https://github.com/telegramdesktop/tdesktop/issues/27657, this functionality really does not exist, I will prove it to you.
https://github.com/telegramdesktop/tdesktop/issues/27657
It says  that it is automatically when you send the code it becomes the block code, this is a **lie**, I can demonstrate it on video. 

I will take this text from ide and paste it into telegram desktop

> class HelloWorld {
>     public static void main(String[] args) {
>         System.out.println("Hello World!");
>     }
> }

It is sent as normal text
https://github.com/telegramdesktop/tdesktop/assets/36221770/569169e0-2cd9-4b00-b729-debf2bb1f14c

There is no code in formatting menu
![image](https://github.com/telegramdesktop/tdesktop/assets/36221770/79dc7bc5-61cb-43e0-95b3-0b81aab7e478)

None of the formatting methods will convert the text into a block of code
[Screencast from 2024-03-28 20-54-18.webm](https://github.com/telegramdesktop/tdesktop/assets/36221770/19e33348-5405-4030-836c-40f4c3e406d7)

The only way is to manually add a block from the backtick
[Screencast from 2024-03-28 20-56-23.webm](https://github.com/telegramdesktop/tdesktop/assets/36221770/7f91f822-22be-497c-90b4-fb21cad39641)

But iOS users don't need to write quotes, they can just do it via formatting

https://github.com/telegramdesktop/tdesktop/assets/36221770/0d283e31-ee46-4cdb-bfe2-89f9da909cc8

This is not a server problem, this is a client problem, you just need to add a formatting item that would insert backtick

### Describe the solution you'd like

Add code block formatting support  ON FORMATING SECTION  like on ios

### Describe alternatives you've considered

Add code block formatting support  ON FORMATING SECTION  like on ios

### Additional context

What the client automatically determines where code = false
The only way to make a code block is to add backtick or copy the code block
Need a menu item, not a hacky method like backtick.
Why is the bold font present, I don’t have to write through ** **, but I have to write a block of code through backtick, it's unfair that this is an ios exclusive, it's very easy to implement.

**Comment by ilya-fedin** [comment]
@Aokromes answer was right, this is already supported and the monosapce item is automatic. For it to mark the text as code, you should have an empty line after the code (which shouldn't be selected). I don't know why it is like that, but it's like that.

**Comment by vadimk1337** [comment]
So, I should insert the code, press Shift+Enter, and after that, I should select monospace, and it will become code. Doesn't it seem a bit too obscure? Essentially, only three people know about this feature: me, you, and Aokromes. Even after your hint, it took me three minutes to understand how to reproduce it. Could it be improved? Made more obvious? For example, remove this strange feature of inserting code, then Shift+Enter, formatting it as monospace, and instead provide "code" formatting directly in the formatting menu?

**Comment by ilya-fedin** [comment]
> Could it be improved?

I guess it's just a bug and is meant to be code as long as the selection is not single line.

The feature request is invalid though, as the feature exists.

**Comment by vadimk1337** [comment]
Can you open a bug report so that it automatically detects the code without all these strange actions?

**Comment by ilya-fedin** [comment]
No, it's up to you as it's you who is interested in that
