### ISSUE TITLE
Fatal memory leak bugs

### ISSUE THREAD

**Issue by sapphirepro** [telegramdesktop/tdesktop#27673]
### Steps to reproduce

1. Open telegram desktop.
2. Open some profile with 30+ photos and view them all
3. Open process monitoring tool
4. see how crazy amount ram and video ram eaten

### Expected behaviour

Below 1GB ram used and below 300 mb vram used

### Actual behaviour

Memory leaks around every corner. Quality of app is disgusting, especially counting I have paid for telegram premium.

Fix finally disgusting application quality and endless memory leaks. I don't care of telegram rolling new features non stop, quality is to have #1 . All those new features are nonsense, counting desktop application fully broken.

Also it fails to play videos on click with sound (ends up with non stop loading) and easily trashed whole system away when insane leaks happen that can eat whole 64GB of RAM.

![Screenshot_20240330_231609-1](https://github.com/telegramdesktop/tdesktop/assets/35900229/c952d2f3-8f03-423d-b63e-64c3250ee292)

### Operating system

OpenSuse Tumbleweed

### Version of Telegram Desktop

Latest

### Installation source

Static binary from official website

### Logs

```shell
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
```

**Comment by ilya-fedin** [comment]
> 2\. Open some profile with 30+ photos and view them all

You mean just scrolling or opening in the viewer?

**Comment by ilya-fedin** [comment]
> and below 300 mb vram used

How do you look VRAM usage? I fail to find anything on my system that would show it.

**Comment by sapphirepro** [comment]
> > and below 300 mb vram used
> 
> How do you look VRAM usage? I fail to find anything on my system that would show it.

In Linux it's application called "Resources". You just need to enable there in setting to show vram usage and it shows it. Very nice modern tool. You can get either prebuilt package from your distro, or from here => https://github.com/nokyan/resources

**Comment by sapphirepro** [comment]
> > 2. Open some profile with 30+ photos and view them all
> 
> You mean just scrolling or opening in the viewer?

Yes.

**Comment by ilya-fedin** [comment]
> Yes.

Which one of these?

**Comment by sapphirepro** [comment]
> > Yes.
> 
> Which one of these?

I mean find some contact with 30+ photos in phofile, click on it and start scrolling them all in Telegram's built in viewer. Especially if videos also there, Telegram lags completely and often not playing at all

**Comment by ilya-fedin** [comment]
> I mean find some contact with 30+ photos in phofile, click on it and start scrolling them all in Telegram's built in viewer.

Do you mean this
![](https://github.com/telegramdesktop/tdesktop/assets/17829319/c1e98d58-ef5a-45e9-ae66-58935d432759)
Or avatars? Or maybe it doesn't really matter?

**Comment by ilya-fedin** [comment]
I'm unable to reproduce scrolling in the viewer through those 10196 photos... I had 60% of the VRAM consumed before launching tdesktop (can I find what consumes it?) and I don't see major increase in consumption after starting it. Could it be a bug in your graphics drivers? Have you tried launching with llvmpipe or zink?

**Comment by fcore117** [comment]
Personally i always prevent Telegram ever using GPU(I always turn off GPU from Telegram options). In my point of view IM app never should use GPU, never. I only allow real serious 3D software to use GPU. My Telegram consumes between 100-200mb RAM max.

**Comment by ilya-fedin** [comment]
Well, without IM applications using GPU, you is likely to have troubles with high resolution (how high depends on CPU, of course) video in those applications... Things like color conversion or image scaling are best done by GPU.

**Comment by fcore117** [comment]
> Well, without IM applications using GPU, you is likely to have troubles with high resolution (how high depends on CPU, of course) video in those applications... Things like color conversion or image scaling are best done by GPU.

In your case i can see this useful, for me i do everything like this externally out of Telegram. Often telegram p2p calls running hours in background when doing graphics related things in collaboration and i like that Telegram do **not touch GPU ever**.

**Comment by ilya-fedin** [comment]
p2p calls if they are video calls, relate to this too. In fact GPU rendering was added exactly because video calls on CPU is a performance disaster.

**Comment by fcore117** [comment]
> p2p calls if they are video calls, relate to this too. In fact GPU rendering was added exactly because video calls on CPU is a performance disaster.

For me CPU had been very low with video calls, maybe because 720p or max 1080p. Anyway 98% i use just audio calls only. 

In the end i am glad there is always option to turn off Telegram GPU. **Everyone has a choice this is most important thing.**

**Comment by sapphirepro** [comment]
> > I mean find some contact with 30+ photos in phofile, click on it and start scrolling them all in Telegram's built in viewer.
> 
> Do you mean this ![](https://private-user-images.githubusercontent.com/17829319/318252256-c1e98d58-ef5a-45e9-ae66-58935d432759.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTg4MjIsIm5iZiI6MTcxMTk5ODUyMiwicGF0aCI6Ii8xNzgyOTMxOS8zMTgyNTIyNTYtYzFlOThkNTgtZWY1YS00NWU5LWFlNjYtNTg5MzVkNDMyNzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE5MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZDQ1NmI1NGUxYTk2NGY4OGEyYjJiMTQzNDdlMjY1MDYxNGZiNzg1OWZkNjBhMWJkM2JlMGEzNzZmMjUzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DnVhFEcJdGIp-wxSYAcpxNYvFT--Z1TansOR63emJrg) Or avatars? Or maybe it doesn't really matter?

I meant profile pictures and stories in profile.

**Comment by sapphirepro** [comment]
> I'm unable to reproduce scrolling in the viewer through those 10196 photos... I had 60% of the VRAM consumed before launching tdesktop (can I find what consumes it?) and I don't see major increase in consumption after using it. Could it be a bug in your graphics drivers? Have you tried launching tdesktop with llvmpipe or zink?

![Screenshot_20240401_211100](https://github.com/telegramdesktop/tdesktop/assets/35900229/ab01cbac-00d7-42fc-8c03-134e5f2a59ef)

To be more precise I mean this. Profile photos, pics and videos in profile and stories. As you can see on screenshot it even fails to load profile pic normally, which is common bug for many versions already here. Regarding GPU, I am pretty sure it's not gpu or driver fails, as all the rest works perfectly. Just click on person's avatar and scroll them all, best is someone having live 30+ profile photos. It will eat ram, vram and most probably even crash or cause machine to hang due to out of ram due to memory leak bugs

**Comment by sapphirepro** [comment]
And to be even more precise of what to look at is here.

Just click on that round face icon on top (picture/photo), not below in "photos, images, media etc".
![Screenshot_20240401_211631](https://github.com/telegramdesktop/tdesktop/assets/35900229/9aff515d-8ce8-445d-8591-c5248d8180d1)

**Comment by ilya-fedin** [comment]
> Regarding GPU, I am pretty sure it's not gpu or driver fails, as all the rest works perfectly.

Anyway, can you try? I believe if this was really a bug in tdesktop then there would be lots of reports but you seem to be the only one.

> Just click on that round face icon on top (picture/photo), not below in "photos, images, media etc".

I fail to find peoplen with such big amount of avatars... Can you give some examples?

**Comment by jcmadrioso** [comment]
Regarding with multimedia, after today update to 4.16 version, on Debian 12.5, it crashes whenever a video call is initiated. Disabling OpenGL rendering is a workaround.

**Comment by sapphirepro** [comment]
> I fail to find people with such big amount of avatars... Can you give some examples?

Yes, sure. For example this one: https://t.me/little_bad_girl_pixie

**Comment by sapphirepro** [comment]
> Have you tried launching tdesktop with llvmpipe or zink?

I don't know what's that to be honest. Any detailed instructions? To the rest questions I provided all info needed.

**Comment by ilya-fedin** [comment]
> I don't know what's that to be honest.

You should set a `LIBGL_ALWAYS_SOFTWARE=1` environment variable for llvmpipe or `MESA_LOADER_DRIVER_OVERRIDE=zink` for zink

**Comment by ilya-fedin** [comment]
> Yes, sure. For example this one: https://t.me/little_bad_girl_pixie

I can't reprdoduce. This resources application shows ~350 MB RAM consumption after scrolling through the pictures. Overall VRAM consumption was 42% at the time and decreased to 37% after exiting from tdesktop.

**Comment by sapphirepro** [comment]
> > Yes, sure. For example this one: https://t.me/little_bad_girl_pixie
> 
> I can't reprdoduce. This resources application shows ~350 MB RAM consumption after scrolling through the pictures. Overall VRAM consumption was 42% at the time and decreased to 37% after exiting from tdesktop.

I tried another installation as was suggested by another source, from RPM and customized. It unintentionally lead to logout and settings drop. Configuring it all the same way as was +/- solved situation. Not crashing anymore, but some videos/photos still remain loading forever. So seems Telegram has some issues with configs stored for years
