### ISSUE TITLE
Not loading video thumbnails every time

### ISSUE THREAD

**Issue by Rainb0-0** [telegramdesktop/tdesktop#27676]
### Steps to reproduce

1. View [this](https://t.me/FuckNvidia/37) video's thumbnail
2. If you do/don't see the thumbnail, switch to another chat and then open the channel again
3. You should see the thumbnail sometimes and sometimes just a black image

### Expected behaviour

The video thumbnail should be shown every time

### Actual behaviour

The video thumbnail is not present 100% of the time

### Operating system

Arch linux (rolling release), Gnome 45 X11

### Version of Telegram Desktop

4.15.1-1

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by Rainb0-0** [comment]
The same issue is also present on the official static downloaded from the link you provided

Here are some screenshots for demonstrating the issue :

![image](https://github.com/telegramdesktop/tdesktop/assets/85252899/2d52d1a6-b46b-45c1-af74-e586b2afee52)

![image](https://github.com/telegramdesktop/tdesktop/assets/85252899/f0585c5f-837b-483d-92de-f18ccbf8d3b4)
