### ISSUE TITLE
Compatibility issue with Mac OS X 10.6.8

### ISSUE THREAD

**Issue by UnknownLoacation** [telegramdesktop/tdesktop#2767]
### Steps to reproduce
1. Download the latest version of Telegram Desktop for older OS X systems (https://tdesktop.com/mac32/current?alpha=1)
2. Mount .DMG file and trying to install
3. It is impossible to do and it ends with error:
![2017-01-01 23 23 20](https://cloud.githubusercontent.com/assets/24863635/21583044/50095366-d07f-11e6-9353-0412ba14d62a.png)
![2017-01-01 23 44 48](https://cloud.githubusercontent.com/assets/24863635/21583046/53351660-d07f-11e6-8e1c-d8400fb6d768.png)

### Expected behaviour
App must work

### Actual behaviour
App not working

### Configuration
**Operating system:** Mac OS X 10.6.8 build 10K540

**Version of Telegram Desktop:** 0.10.22

I use Snow Leopard due to testing and the presence of Rosetta. In system not available 64-bit extensions, but any other apps like Firefox ESR and VLC works fine.

**Comment by john-preston** [comment]
@UnknownLoacation I'm sorry, but the OS X build is (and always was) only 64bit :( It should be stated on the app page and I guess I'll have to add it, but it is not (and will not be) working on 32bit OS X systems.
