### ISSUE TITLE
Chats not updated on Linux

### ISSUE THREAD

**Issue by RankoR** [telegramdesktop/tdesktop#27672]
### Steps to reproduce

1. Install telegram desktop on arch linux
2. Launch it
3. Wait a bit

### Expected behaviour

When I switch to the app from background I see all chats updated (seeing new message counters, new messages in open chats and so on)

### Actual behaviour

When I switch to the app from the background, in 90% of cases it's "frozen" in the previous state - the app itself is responsive and usable, but updates (counters and messages) are not loaded until I re-launch the app. I don't have lots of chats, it's like 5 active. I have very stable wired connection, and usually everything works fine on macOS and iOS. Also tried flatpak installation with the same results. 

### Operating system

Arch linux, wayland, KDE plasma 6.

### Version of Telegram Desktop

4.15.6

### Installation source

Other (unofficial) source

**Comment by translit** [comment]
Same issue on macOS, Telegram Desktop 10.9.1.260779 Stable.

**Comment by Aokromes** [comment]
> Same issue on macOS, Telegram Desktop 10.9.1.260779 Stable.

you are using https://github.com/overtake/TelegramSwift

**Comment by ilya-fedin** [comment]
> When I switch to the app from the background

Does that include suspend? Sounds like a dup of #16093

**Comment by RankoR** [comment]
> Does that include suspend?
No, just a regular use without suspending PC.
