### ISSUE TITLE
Crashing on chat opening

### ISSUE THREAD

**Issue by mpz** [telegramdesktop/tdesktop#27670]
### Steps to reproduce

Can't reproduce steps. It is like open chat or make chat unread or etc

### Expected behaviour

Telegram working, not crashing

### Actual behaviour

Crashing. Telegram terminated.

./Telegram 
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.qpa.wayland: Creating a popup with a parent, QWidgetWindow(0x7fc031b18710, name="TWidgetClassWindow") which does not match the current topmost grabbing popup, QWidgetWindow(0x7fc0330e5910, name="TWidgetClassWindow") With some shell surface protocols, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly. Please fix the transient parent of the popup.
  OpenType support missing for "DAOpenSansSemibold", script 20
  OpenType support missing for "davazirmedium", script 20
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.qpa.wayland: Creating a popup with a parent, QWidgetWindow(0x7fc031b18710, name="TWidgetClassWindow") which does not match the current topmost grabbing popup, QWidgetWindow(0x7fc033b57c10, name="TWidgetClassWindow") With some shell surface protocols, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly. Please fix the transient parent of the popup.

### Operating system

Ubuntu

### Version of Telegram Desktop

4.15.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> ### Crash ID
> 
> _No response_

This is required for crash reports

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.
