### ISSUE TITLE
Complete chat separation by folder / hide chat from "all chats" / "chats that are not included in any folder" folder

### ISSUE THREAD

**Issue by luixo** [telegramdesktop/tdesktop#27682]
### Is your feature request related to a problem?

Hello,
Telegram has a potential to be a 360 feed, but it lacks an important structural feature for me that defocus me from consuming specific group of chat all the time and it is hiding the chat from "all chats" (without muting it).

It would be a great option to split all the chats I have into separate groups - and leave the rest in "chats that are not included in any folder" instead of "all chats" (or in addition to it).

### Describe the solution you'd like

It can be achieved in a different ways: an option to hide chat from "all chats" when adding it to a folder, an option to have "chats that are not included in any folder" folder - and more.

### Describe alternatives you've considered

Adding chats / channels in groups and tidy them up from time to time

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
(and it's very likely duplicate)

**Comment by luixo** [comment]
Thank you
I found an issue with the idea as mine on the platform: https://bugs.telegram.org/c/11592
