### ISSUE TITLE
When you open a photo, the previous photo flashes across the entire screen

### ISSUE THREAD

**Issue by suprunchuk** [telegramdesktop/tdesktop#27688]
### Steps to reproduce

1. Open any channel with photos.
2. Expand any photo from the channel post to the full screen of the monitor.
3. Close the photo by pressing Esc.
4. Open another photo.

https://github.com/telegramdesktop/tdesktop/assets/57152612/1b39c895-b368-440a-ac2c-41079dcfc475

### Expected behaviour

A new photo opens instantly

### Actual behaviour

The previous photo flashes for a few milliseconds when opening a new one.

### Operating system

Windows 11 pro

### Version of Telegram Desktop

4.16 x64 beta

### Installation source

Static binary from official website

**Comment by MikeMilligan** [comment]
Can confirm the same behavior on Windows 10. It began today after I updated to 4.16.

**Comment by suprunchuk** [comment]
Fixed with 4.16.1 ae36019ba99131df31a2e7056da720b3bad1b827
