### ISSUE TITLE
No Icon in systemtray on Cinnamon

### ISSUE THREAD

**Issue by Speedy1991** [telegramdesktop/tdesktop#2768]
### Steps to reproduce
1. apt-get install telegram
2. start telegram

### Expected behaviour
Systemtray icon should appear

### Actual behaviour
No icon

### Configuration
Linux Mint 18.1 Cinnamon 64-bit
Cinnamon-Version 3.2.7
Kernel 4.4.0-57-generic
Telegram v 0.10.16

with Linux Mint 17.1 cinnamon all works perfectly fine

**Comment by Speedy1991** [comment]
running 
> sudo apt-get install libappindicator*

fixed it, i didnt check what package was missing exactly

**Comment by Speedy1991** [comment]
After reboot the icon is missing again :/

**Comment by mymedia2** [comment]
> apt-get install telegram

What is the package – `telegram`? I can not find it in repository of Linux Mint.

**Comment by john-preston** [comment]
@mymedia2 This is not an official Telegram build. You can get official binaries from https://desktop.telegram.org

**Comment by Speedy1991** [comment]
oh i totally forgot i used the ppa from https://wiki.ubuntuusers.de/Telegram/
after purging + cleaning my sources and make a clean install with your link, all works fine. Thank you very much :)
