### ISSUE TITLE
Telegram freezes when starting

### ISSUE THREAD

**Issue by glu8716** [telegramdesktop/tdesktop#27687]
### Steps to reproduce

1. Open Telegram

### Expected behaviour

Telegram's window should open and instantly load the interface and the content.

### Actual behaviour

Telegram's window opens, but it freezes for about 20 seconds (with a "blank screen" that draws the same content of the window behind Telegram's one) before loading the interface and the content.

### Operating system

Artix Linux

### Version of Telegram Desktop

4.15.6

### Installation source

Other (unofficial) source

### Logs

```shell
--- This is when the window freezes
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter

--- This is when the window unfreezes and starts loading the interface
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
```

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
> Installation source
> Other (unofficial) source

Can you reproduce with static binary?

**Comment by glu8716** [comment]
I've also tried with the static binary. It also freezes, but just for about 5 seconds (which shouldn't be the case, I guess). The output is the same:
```
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
```
But no `qt.svg: Error while inflating gzip file: SVG format check failed` error.

**Comment by Aokromes** [comment]
maybe you have a lot of fonts installed?

**Comment by glu8716** [comment]
@Aokromes I don't know how to quantify "a lot", but I've tried to change system font and to login without my `fonts.conf`. Still the same.

@ilya-fedin Yes I am.

**Comment by ilya-fedin** [comment]
@glu8716 your case is apparently the same as #27618 then.
