### ISSUE TITLE
Add "post statistic" feature from telegram for android

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#27683]
### Is your feature request related to a problem?

Telegram for Desktop does not have "post statistic" function that telegram for android have:
![084fcf64cc21419cbad41-79a78675a7578c5fdf](https://github.com/telegramdesktop/tdesktop/assets/5204968/b1db2a46-f23d-41b4-9032-6d556ae775d6)
![Screenshot_20240401-230336](https://github.com/telegramdesktop/tdesktop/assets/5204968/33992d75-6ed9-47e8-817f-0e4ec9b7083c)

### Describe the solution you'd like

Having such function to view post statistic.

### Describe alternatives you've considered

Not having such function.

### Additional context

https://bugs.telegram.org/c/1078

**Comment by soredake** [comment]
And?
![image](https://github.com/telegramdesktop/tdesktop/assets/5204968/72034f24-7d15-42d5-b1c7-8a717b9c1229)

**Comment by Aokromes** [comment]
https://i.imgur.com/CNh7E3v.png maybe your channel aint large enough.
