### ISSUE TITLE
Increase tray icon size

### ISSUE THREAD

**Issue by arkrost** [telegramdesktop/tdesktop#2769]
Please provide option to increase tray icon size.

It seems that right now it is [22px](https://github.com/telegramdesktop/tdesktop/blob/d460897f84bad314302df1198b3dbcf3f11bf653/Telegram/SourceFiles/platform/linux/main_window_linux.cpp#L44) on linux. It looks really small on 4K displays.

**Comment by bil-elmoussaoui** [comment]
Instead of increasing the icon size, all the application have to do is to provide scalable icons (svg ones) instead of generating png icons that will alwways look ugly even if you can change the size...
You still can overwrite the icons with the icons you want using a different icon size..

**Comment by stek29** [comment]
#2230
