### ISSUE TITLE
Contact Joined Telegram still showing popups even after disabling it

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#27692]
### Steps to reproduce

1. Use any version
2. Disable Contact Joined Telegram (it comes disabled y default)
3. If someone else joins, it still notifies you on Windows and Linux

### Expected behaviour

It should not show the "Someone joined telegram" either on the conversation chat menu or as a popup notification

### Actual behaviour

It shows them on the conversation section of chats and the popup notification

![image](https://github.com/telegramdesktop/tdesktop/assets/29236/c7d23374-1c07-4d7a-9dec-cb51af410e65)

### Operating system

Ubuntu but also Windows 11

### Version of Telegram Desktop

4.16 (Linux) / 4.15.2 (Windows 11)

### Installation source

Microsoft Store

**Comment by luisalvarado** [comment]
On Windows is worse because it shows the popup notification as if someone had written to me, on linux it does not but it does show the "someone joined Telegram" annoying message and it fills in the whole chat.

**Comment by Aokromes** [comment]
not a bug, that setting disables notification, not creation of users. any way this is consistent with all telegram applications.
