### ISSUE TITLE
Custom tray icon in Linux is no longer used

### ISSUE THREAD

**Issue by gnolooo** [telegramdesktop/tdesktop#27697]
### Steps to reproduce

[As already reported in the Papirus Github](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/3686), when using Papirus icon theme in Arch Linux on Gnome, the custom Papirus icon should be displayed. However, that's no longer the case, because the standard blue icon is displayed. More in the pictures below.

### Expected behaviour

The Papirus tray icon should be displayed:

![temp](https://github.com/telegramdesktop/tdesktop/assets/76843243/9bde9c9f-4817-48e2-804b-e5f4edb9b50b)

### Actual behaviour

The standard blue icon is displayed:

![Schermata del 2024-04-02 19-08-41](https://github.com/telegramdesktop/tdesktop/assets/76843243/034a85c5-17a3-45d9-96d5-043d0e22aa7b)

### Operating system

Arch Linux with Gnome

### Version of Telegram Desktop

4.16.0-1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
There's now a setting for this that you have to enable

**Comment by ilya-fedin** [comment]
It's also definitely custom, the standard one is this: 
![](https://github.com/telegramdesktop/tdesktop/assets/17829319/90a3bb9a-14ae-4654-8480-c04f75fb3eb5)

**Comment by gnolooo** [comment]
Found it, thanks.
