### ISSUE TITLE
No option to close immediately on main window close

### ISSUE THREAD

**Issue by socketpair** [telegramdesktop/tdesktop#27691]
### Steps to reproduce

1. Install Telegram 4.16 in Linux (Gnome DE, Fedora 39)
2. close the main window
3. see in process list that Telegram is not closed

Before there was an option. Now no such option.

Now:
![image](https://github.com/telegramdesktop/tdesktop/assets/1157412/7c19a1c6-8cb6-4d3d-90b1-ebdf132cd1f8)

### Expected behaviour

Have an option to choose behavior on window closure.

### Actual behaviour

Telegram runs in the background unconditionally.

### Operating system

Linux Fedora 39

### Version of Telegram Desktop

4.16

### Installation source

Static binary from official website

**Comment by socketpair** [comment]
Yes, I know there were many discussions about that. Please restore these options back.

**Comment by socketpair** [comment]
https://github.com/telegramdesktop/tdesktop/issues/27190

There is no way to comment there because conversation is closed. But still actual.

**Comment by ilya-fedin** [comment]
It follows the system preference... If the system supports closing but not minimizing (as in titlebar) then it won't close. To make it close, configure the system to either support minimizing or not support closing the window (so the respective buttons are shown in the titlebar).

**Comment by socketpair** [comment]
Okay, if the system supports only closing, does not support minimizing, why default action for CLOSE button is MINIMIZE so ?

**Comment by ilya-fedin** [comment]
It is not minimize, it is working in background... When you have the minimize button, there's a check in the settings that lets you minimize on close and that is a completely different thing which seem to be poorly supported on GNOME as lots of people were disliking it and asking the current behavior.

**Comment by socketpair** [comment]
I have a single button (cross). It is expected to close an app. Why not to do what all other apps do? I don't need TG to work in background. If some people like it - okay. Just give us an option. Totally don't understand why option is removed.
