### ISSUE TITLE
Flatpak Telegram Crashes 4.16 Scudo ERROR: internal map failure

### ISSUE THREAD

**Issue by infriker** [telegramdesktop/tdesktop#27707]
### Steps to reproduce

1) flatpak install org.telegram.desktop
2) flatpak run org.telegram.desktop

### Expected behaviour

Telegram Startup

### Actual behaviour

Telegram just won't start:
Gtk-Message: 11:32:16.324: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Could not open network socket
Scudo ERROR: internal map failure

### Operating system

Linux Mint 21.3 x86_64

### Version of Telegram Desktop

4.16

### Installation source

Flatpak

**Comment by infriker** [comment]
> Do you set some kind of RAM limit?

No, I have 32GB RAM

**Comment by ilya-fedin** [comment]
> ### Steps to reproduce
> 
>     1. flatpak install org.telegram.desktop
> 
>     2. flatpak run org.telegram.desktop

I fail to reproduce that... It starts just fine for me

**Comment by infriker** [comment]
4.15 worked 4.16 dont.

**Comment by infriker** [comment]
@ilya-fedin Hi, here's what I managed to find out about my mistake:
I tried to install the previous comment on Flathub:
sudo flatpak update --commit=4d89e1f5af9e56ac765984e87935782ca84e1e01ea1b1ba416751e5bfff76fbe org.telegram.desktop

Commit: 4d89e1f5af9e56ac765984e87935782ca84e1e01ea1b1ba416751e5bfff76fbe
Subject: Update desktop.git to 4.15.2 (501a0581)
Date: 2024-03-13 10:13:34 +0000


And this version works great.

But this version doesn't work:

sudo flatpak update --commit=c3cdfc1ef49ab9c4e8aed9abb107ad27779ccbf3112c38fa3a969e6b85b7ff41 org.telegram.desktop

Commit: c3cdfc1ef49ab9c4e8aed9abb107ad27779ccbf3112c38fa3a969e6b85b7ff41
Parent: 949ced0a653f06a5cf6798fdbab05862596945440b75f0172622e0b6de2c02ef
Title: Update Qt patches to desktop-app/patches@af70443 (7cb35bc8)
Date: 2024-04-05 03:02:10 +0000


I see the Qt update and I have an error of this version when starting: Qt: Session management error: Could not open network socket

I have a laptop with the same version of Linux Mint 21.3 and this version works fine for me there, unfortunately I do not know how to understand more deeply why this version does not work on my PC. I think it has something to do with the QT packages

**Comment by ilya-fedin** [comment]
It looks like your computer has some limit configured... I sadly can't suggest anything other reinstalling the OS as I can't reproduce myself.
