### ISSUE TITLE
In Linux Telegram crashes almost every time a file is downloaded

### ISSUE THREAD

**Issue by Jeronimo17** [telegramdesktop/tdesktop#27702]
### Steps to reproduce

Save a video or a file with the option to ask for the folder to save activated (I don't know if it is relevant).

### Expected behaviour

No program crash

### Actual behaviour

The program stops responding

### Operating system

Linux Mint 21.3 x86_64 Xfce 4.18

### Version of Telegram Desktop

4.16.1

### Installation source

Static binary from official website

### Crash ID

Crash ID: b7b85c02-006d-49cc-d1193eb0-f858eefa

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by Jeronimo17** [comment]
Crash ID: b7b85c02-006d-49cc-d1193eb0-f858eefa

I was waiting for the Crash ID to come up, sometimes the program stops responding, I send **killall Telegram** and when I reopen it it does not give Crash ID.

**Comment by ilya-fedin** [comment]
That is likely not the answer you would to hear... But it looks like Mint 21.3 has a memory corruption bug in some of the system libraries which trigger random crashes in the allocator. It's not clear what to do with that.

**Comment by Jeronimo17** [comment]
I don't know, but it only happens to me with Telegram in 2 PCs, and I use linux for everything.

**Comment by Jeronimo17** [comment]
Crash ID: 51165e09-04bb-4e25-35b3c58b-03c9b4d0

**Comment by kai3341** [comment]
I have the same problem

**Comment by pfactum** [comment]
Do you experience this while attaching/uploading (_instead of downloading_) a file to a chat as well?

**Comment by Aokromes** [comment]
try on 4.16.5

**Comment by john-preston** [comment]
@pfactum Try 4.15.6 😂

**Comment by john-preston** [comment]
@pfactum Sorry, I (1) mistyped 4.16.6 as 4.15.6 and (2) didn't yet release 4.16.6, which will be available today, but it won't contain any crash fixes. 4.16.5 should have been working without crashes since we rolled back scudo allocator and replaced it with jemalloc, like before.

Can you provide Crash ID from 4.16.5?

**Comment by pfactum** [comment]
How do I get `Crash ID` while using Arch package please?

(_I'm not sure TG crashes even, it just closes silently, no segfault trace anywhere, no nothing_)

**Comment by ilya-fedin** [comment]
@pfactum it is available only for static binary users. Distro package users are supposed either to test the issues they have on the official builds or report to distro bugtrackers thus delegating the work of verifying the issue to the distro maintainer.

**Comment by pfactum** [comment]
Distro guys obviously kicked me out stating it had nothing to do with distro.

Instead, they pointed to https://bugs.kde.org/show_bug.cgi?id=483439, which also points to https://bugs.kde.org/show_bug.cgi?id=471941.

Reading those bugs it seems TG has to be adopted to Qt6 behaviour.

**Comment by pfactum** [comment]
```diff
diff '--color=auto' -Naur tdesktop-4.16.5-full~/Telegram/SourceFiles/core/launcher.cpp tdesktop-4.16.5-full/Telegram/SourceFiles/core/launcher.cpp
--- tdesktop-4.16.5-full~/Telegram/SourceFiles/core/launcher.cpp	2024-04-09 16:19:44.250407858 +0200
+++ tdesktop-4.16.5-full/Telegram/SourceFiles/core/launcher.cpp	2024-04-09 16:20:15.407135589 +0200
@@ -319,6 +319,8 @@
 
 	QApplication::setApplicationName(u"TelegramDesktop"_q);
 
+	QCoreApplication::setQuitLockEnabled(false);
+
 #if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
 	// fallback session management is useless for tdesktop since it doesn't have
 	// any "are you sure you want to close this window?" dialogs
```

This fixed my issue, it seems.

**Comment by ilya-fedin** [comment]
This doesn't look like a right fix given that tdesktop is not using QEventLoopLocker?

**Comment by pfactum** [comment]
Suspiciously similar Reddit thread: https://www.reddit.com/r/kde/comments/1bvjsk2/telegram_desktop_crashing_in_kde/

``` 
UPD: Solved. For anyone that may stumble upon this thread - the solution for KDE Plasma 6 is to turn on the tray bar icon (sic!). If it is disabled, you get what is described below.

Hi everyone. KDE Plasma 6.0.3, Arch, Wayland.

When I try to open some file in telegram-desktop (installed via pacman, not flatpak), the KDE file dialogue appears (the correct one, with previews etc), but whenever I choose a file to upload or just close the dialogue, the whole app crashes. No relevant errors if started in terminal too.

Happens only in KDE, no extra env variables (like QT_QPA... etc) is used in the system.

However, if I run:

QT_QPA_PLATFORMTHEME=xdgdesktopportal telegram-desktop

in terminal, it works great, no crashes. 
```

**Comment by pfactum** [comment]
BTW, I indeed don't enable systray icon.

**Comment by wolfseifert** [comment]
I already commented this a couple of weeks ago https://bugs.kde.org/show_bug.cgi?id=483439#c14 and also found a solution on the kde-side that works for me https://bugs.kde.org/show_bug.cgi?id=483439#c16 but nothing happened. Maybe we need a "rise in pressure".

The problem only occurs if a KFileWidget is used, what may happen even if your application just uses a QFileDialog in code. If you run it with QT_QPA_PLATFORMTHEME=xdgdesktopportal telegram-desktop then the original qt dialog (which looks a bit different) is used and everything is fine. You can also change this by setting LD_LIBRARY_PATH to a qt-online-installed qt version. So depending on your runtime environment (plain qt vs "enhanced" kde) your application works or not.

**Comment by ilya-fedin** [comment]
I think this is offtopic here... This report is about memory corruption crash when opening the file dialog (according to the initial reporter's crash id).

**Comment by kushagra-xo** [comment]
> Suspiciously similar Reddit thread: https://www.reddit.com/r/kde/comments/1bvjsk2/telegram_desktop_crashing_in_kde/
> 
> ```
> UPD: Solved. For anyone that may stumble upon this thread - the solution for KDE Plasma 6 is to turn on the tray bar icon (sic!). If it is disabled, you get what is described below.
> 
> Hi everyone. KDE Plasma 6.0.3, Arch, Wayland.
> 
> When I try to open some file in telegram-desktop (installed via pacman, not flatpak), the KDE file dialogue appears (the correct one, with previews etc), but whenever I choose a file to upload or just close the dialogue, the whole app crashes. No relevant errors if started in terminal too.
> 
> Happens only in KDE, no extra env variables (like QT_QPA... etc) is used in the system.
> 
> However, if I run:
> 
> QT_QPA_PLATFORMTHEME=xdgdesktopportal telegram-desktop
> 
> in terminal, it works great, no crashes. 
> ```

even this solution wont work for me

**Comment by kushagra-xo** [comment]
i just updated and i cannot reproduce this with version: 4.16.7-1

**Comment by Jeronimo17** [comment]
It doesn't seem to be happening anymore **4.16.8**
