### ISSUE TITLE
Windows Remote Desktop uses Telegram player, and the video screen will flicker

### ISSUE THREAD

**Issue by 308879** [telegramdesktop/tdesktop#27704]
### Steps to reproduce

Windows Remote Desktop uses Telegram player, and the video screen will flicker

### Expected behaviour

Windows Remote Desktop uses Telegram player, and the video screen will flicker

### Actual behaviour

Windows Remote Desktop uses Telegram player, and the video screen will flicker

### Operating system

windows

### Version of Telegram Desktop

4.16.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
tried from windows 10 pc with nvidia rtx 3050 to i5 gen 4 pc with windows 11, cannot reproduce.

**Comment by 308879** [comment]
I'm using R5 5600G is an issue with AMD CPU

**Comment by 308879** [comment]
I'm using R5 5600G, is this an issue with AMD CPUs?

**Comment by 308879** [comment]
> tried from windows 10 pc with nvidia rtx 3050 to i5 gen 4 pc with windows 11, cannot reproduce.尝试从windows 10 pc与nvidia rtx 3050到i5 gen 4 pc与windows 11，无法再现.

I'm using R5 5600G, is this an issue with AMD CPUs?

**Comment by dimas1980200** [comment]
***@***.***
