### ISSUE TITLE
Control buttons in wrong position in Linux

### ISSUE THREAD

**Issue by MissingUser** [telegramdesktop/tdesktop#27700]
### Steps to reproduce

Open Telegram version 4.16.1 after update.

### Expected behaviour

To have the control buttons (minimize, maximize and close) in the position configured in the system. In my case in the left of the title bar.

### Actual behaviour

Control buttons appear fixed in right position.

### Operating system

Ubuntu 22.04.04 LTS x86_64 jammy - Kernel 6.2.0-39 - Shell GNOME 42.9

### Version of Telegram Desktop

4.16.1

### Installation source

Static binary from official website

**Comment by MissingUser** [comment]
![TelegramWindowControls](https://github.com/telegramdesktop/tdesktop/assets/37713129/5c78ce1a-0692-4b6b-be09-98599a2a25b9)
As you can see in the attached image, all program windows have the controls on the top left but Telegram, as of version 4.16.1 is not following the system configuration and they appear on the right.
Version 4.16.4 still has this behavior.

**Comment by ilya-fedin** [comment]
Perhaps you have problems with xdg-desktop-portal? That's where tdesktop gets this information from.

**Comment by MissingUser** [comment]
This is the only application with this problem, and it only appeared from the update to version 4.16.1. Previously Telegram had behaved like all other applications. The update was done from within the program itself without coinciding with any other system updates.

**Comment by ilya-fedin** [comment]
> How can I downgrade?

Just get the version from https://github.com/telegramdesktop/tdesktop/releases

**Comment by MissingUser** [comment]
Changing the version is too much trouble for this issue. I will continue with the current situation and if a possible cause is found in the sources it will be fixed.

**Comment by MissingUser** [comment]
Thanks for your interest.
