### ISSUE TITLE
Telegram Desktop crashing on Linux Mint when trying to play video "on top"

### ISSUE THREAD

**Issue by michalko58** [telegramdesktop/tdesktop#27710]
### Steps to reproduce

1. Open any video (opens in window or fullscreen) 
2. Click on "play on top" icon
3. Telegram freezes and crashes afterwards

### Expected behaviour

Video should play on top as it did few versions before.

### Actual behaviour

Telegram is crashing everytime video is played and you try to set it to play on top

### Operating system

Linux Mint 21.3 Cinnamon

### Version of Telegram Desktop

Version: 4016003 beta (the same on stable 4.16 version

### Installation source

Static binary from official website

### Crash ID

Crash ID: ca3087ec-6b71-4b3d-e2e3de82-c9c14ad9

### Logs

```shell
ApiId: 2040
Binary: Telegram
Launched: 05.04.2024 21:50:43
OpenGL: Enabled
OpenGL Renderer: Mesa Intel(R) HD Graphics 530 (SKL GT2)
Platform: Linux
UserTag: d4369e8ba8603779
Version: 4016003 beta

Caught signal 11 (SIGSEGV) in thread 127017978900992
Google Breakpad caught a crash, minidump written in thread 127017978900992
Minidump: /home/misiacik/.local/share/TelegramDesktop/tdata/dumps/ca3087ec-6b71-4b3d-e2e3de82-c9c14ad9.dmp
```

**Comment by chelobaka** [comment]
Same problem but with Plasma Wayland. It started a few a days ago after Telegram update.

**Comment by jlrpalomar** [comment]
Confirmed in LM 21 - Besides this, it also crashes when you're in a direct call with someone and the other person shares its screen (tested with Windows users only)
Crash id: 3046c3b0-8006-4e9c-31862c92-d298ccff

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/27608
