### ISSUE TITLE
microphone icon is missing Windows 10

### ISSUE THREAD

**Issue by Nammehub** [telegramdesktop/tdesktop#27711]
### Steps to reproduce

microphone icon is missing.
Tgdesktop sees recording audio device's activity.
Tgdesktop portable v4.16.2
![image](https://github.com/telegramdesktop/tdesktop/assets/58394819/261fb23b-d005-4f46-94dc-cb25ebe1e06f)
![image](https://github.com/telegramdesktop/tdesktop/assets/58394819/8fb48856-b403-4ac7-81fd-f9b23b539ac6)

### Expected behaviour

microphone icon waiting to be pressed

### Actual behaviour

microphone icon is missing.

### Operating system

Windows 10 22H2 x64

### Version of Telegram Desktop

4.16.2 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
you have started telegram before plug mic?

**Comment by Nammehub** [comment]
> you have started telegram before plug mic?

I need to work with this recording device regardless of whether there is a physically real or virtual microphone
![image](https://github.com/telegramdesktop/tdesktop/assets/58394819/a3a55117-cc16-47cb-84f0-e53a901a29a9)

**Comment by Nammehub** [comment]
appeared on its own after rebooting the PC. Didn't change anything else
Strange lag
