### ISSUE TITLE
Keep crashing on Ubuntu 22.04.1 (Snap only)

### ISSUE THREAD

**Issue by NafiurSiddiqui** [telegramdesktop/tdesktop#27713]
### Steps to reproduce

1. Open Tg
2. Make a call
3. Wait for it to connect
4. Ready to get disappointed

### Expected behaviour

Connects with the other end and connection remains stable

### Actual behaviour

Connects and immediately drops. Sometimes you hear the voice from the other end and drops anyway. (Such a teaser XD)

### Operating system

Ubuntu 22.04.1

### Version of Telegram Desktop

4.16.2

### Installation source

Snap

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/27705
