### ISSUE TITLE
Telegram doesn't autostart minimized although it is set.

### ISSUE THREAD

**Issue by Dan-cer** [telegramdesktop/tdesktop#27716]
### Steps to reproduce

1. In Telegram settings I checked Symbol show in systray, execute Telegram at start, start minimized.
2. After reboot Telegram starts, but not minimized, with open window.
![Telegram](https://github.com/telegramdesktop/tdesktop/assets/800638/3d072d85-f023-45b0-ab89-34a1cb132fb1)

### Expected behaviour

Telegram should autostart minimized.

### Actual behaviour

Telegram autostarts with open window.

### Operating system

Linux Mint LMDE 6 Cinnamon

### Version of Telegram Desktop

4.9.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
Version of Telegram Desktop
4.9.2

that's some extreme old version. update.

**Comment by Dan-cer** [comment]
In mint app manager I find only version 4.6.5+ds-2.
As AppImage I only find Telegram_Desktop-x86_64.AppImage	3.2.5
Flatpak and Snap I don't use.
Build from source code seem to be too difficult to me.
What would you recommend then?

**Comment by Aokromes** [comment]
you wrote you use static binary from webpage, that means download from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
> In mint app manager I find only version 4.6.5+ds-2.

Packages there are maintained by your distro, not by Telegram. You should find the bugtracker of your distro, find the package and file a bug to it.

**Comment by Dan-cer** [comment]
That isn't necessary because it is working. Before I had a version which I not exactly know the download source of.
We can close the issue now as "Solved".
Thank you very much for answering quickly!
