### ISSUE TITLE
The chat list context menu options do not work on Linux

### ISSUE THREAD

**Issue by Akaricchi** [telegramdesktop/tdesktop#2771]
### Steps to reproduce
1. Right-click on any chat in the list.
2. A context menu will show up. Click on any item in the menu.

### Expected behaviour
The action appropriate for the menu item that was clicked should be executed for the chat the menu was invoked for.

### Actual behaviour
Nothing. The menu just disappears. "Pin to top" doesn't pin anything to top, "Enable/disable notifications" does not toggle notifications, "View profile" does not open the user's profile, etc.

### Configuration
**Operating system:** Arch Linux, up to date as of today.

**Version of Telegram Desktop:** 0.10.23 alpha. Started happening in whatever version that introduced material design.

**Comment by john-preston** [comment]
@Akaricchi Thanks for your report. This will be fixed in the next version.

**Comment by john-preston** [comment]
@Akaricchi Please check the new 0.10.25 alpha version and tell me if it's fixed.

**Comment by Akaricchi** [comment]
@john-preston seems to work now, thanks.
