### ISSUE TITLE
Shortcut for switching accounts

### ISSUE THREAD

**Issue by Inspector-Butters** [telegramdesktop/tdesktop#27721]
### Is your feature request related to a problem?

Having a shortcut to switch between logged in accounts would make it much simpler and faster. 

### Describe the solution you'd like

have shortcut with this format: [key] + 1, [key] + 2, ...
that switches to first, second, and ... logged in accounts

[key] could be ctrl/alt/shift or a combination of these.

### Describe alternatives you've considered

The default way is to switch using the list of accounts in the left side menu, but it's not fast.
Another hack is to open the accounts in new windows, but it clutters the workspace.

another idea could be to just switch back and forth between two last used accounts on the client being used.

**Comment by 23rd** [comment]
Open the `tdata/shortcuts-custom.json` and paste the following json:
```
[
    {
        "command": "account1",
        "keys": "ctrl+shift+1"
    },
    {
        "command": "account2",
        "keys": "ctrl+shift+2"
    },
    {
        "command": "account3",
        "keys": "ctrl+shift+3"
    },
    {
        "command": "account4",
        "keys": "ctrl+shift+4"
    },
    {
        "command": "account5",
        "keys": "ctrl+shift+5"
    },
    {
        "command": "account6",
        "keys": "ctrl+shift+6"
    }
]
```

**Comment by mohamadbastin** [comment]
@23rd I did that but could not get it to work. is there something special I need to do ?

**Comment by Aokromes** [comment]
p.s one very unknown shortcut (at least on windows / linux) shift + f1-f12 becomes f13-f24

**Comment by mohamadbastin** [comment]
@23rd Thank you. it was the cmd/ctrl thing on mac. it interferes with the os shortcuts. do you know how to reference the ctrl in the shortcuts-custom.json file specifically?

**Comment by 23rd** [comment]
@mohamadbastin `meta`.
