### ISSUE TITLE
Right mouse button (context) menu has wrong margins on ArchLinux + Gnome + Wayland

### ISSUE THREAD

**Issue by sxiii** [telegramdesktop/tdesktop#27724]
### Steps to reproduce

1. Open telegram
2. Open any chat
3. Right click any message
4. See the wrong margin

### Expected behaviour

Margins should be smaller and also they should follow the items.
![image](https://github.com/telegramdesktop/tdesktop/assets/575925/7fe6eec1-b869-4812-ac72-53750c3d6e6b)

### Actual behaviour

Margins are large and they have a lot of space around the menu.

### Operating system

Garuda Linux Soaring Spizaetus

### Version of Telegram Desktop

4.16.1, installed from Arch Repos, but I think this bug was for several versions already before

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
> Other (unofficial) source

Can you reproduce with official one?

**Comment by sxiii** [comment]
@ilya-fedin hmm, strange. I've tried with official binary and actually it doesn't have these margins. Although I think in the past it had, or maybe I am remembering wrong. So then I guess it's a Arch binary build (AUR script) issue. Hmmm. Probably that it could be closed, although it would be nice where to point the guys who build the Telegram-Desktop in AUR. . .

**Comment by ilya-fedin** [comment]
That looks like a broken Qt theme issue that fills the transparent background with an opaque color. The static binary can't use custom themes (as they are Qt plugins) so it's not affected.
