### ISSUE TITLE
Set default for Enlarge or Shrink photo when posting a link.

### ISSUE THREAD

**Issue by crimzind** [telegramdesktop/tdesktop#27726]
### Is your feature request related to a problem?

Right now, when you share a link, it often generates a image/preview of the content.
Right now, it defaults to Enlarge photo when sharing a link.
I don't like how much space the Enlarge version takes up.
The Shrink version is preferable
However, it's a nuisance having to paste a link, grab the mouse, click another 3 times, and then hit enter to send (or another click).

### Describe the solution you'd like

I'd like to be able to change the default to Shrink...

### Describe alternatives you've considered

...or for Telegram to remember and keep the last used setting.

### Additional context

![image](https://github.com/telegramdesktop/tdesktop/assets/1254414/4b5b2d73-eb0f-4eed-b277-b091d140b225)

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
