### ISSUE TITLE
Group chats

### ISSUE THREAD

**Issue by bugz0** [telegramdesktop/tdesktop#2772]
### Steps to reproduce
1.  the ability to group chats in groups
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by MasterGroosha** [comment]
From what I see, you want to make subgroups in groups, right?  
If yes, then no API for that and this is not TDesktop-related issue, sorry.

**Comment by bugz0** [comment]
Жаль, было бы удобно.Сейчас очень много различных каналов и ботов.Фича выстрелила бы очень в тему, в ватсапах и вайберах такого вроде точно нет) 02.01.2017, 22:46, "Evgeny Petrov" <notifications@github.com>:From what I see, you want to make subgroups in groups, right?If yes, then no API for that and this is not TDesktop-related issue, sorry.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- С уважением, Александр

**Comment by auchri** [comment]
@bugz0 Write english please.
