### ISSUE TITLE
Telegram Desktop does not open on Debian 12

### ISSUE THREAD

**Issue by A-Infor** [telegramdesktop/tdesktop#27727]
### Steps to reproduce

1. Click to open
2. Notice the icon on the taskbar, but no window is shown

### Expected behaviour

That it opens when clicked

### Actual behaviour

Does not open

### Operating system

Debian 12

### Version of Telegram Desktop

4.16.4

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
That doesn't seem to be the truth?
![](https://github.com/telegramdesktop/tdesktop/assets/17829319/260bb6cf-1143-4ba1-a5ea-017f52224bfb)

**Comment by A-Infor** [comment]
It is true on my system, but I don't know which characteristic of my system makes it happen to me and not to you.

**Comment by ilya-fedin** [comment]
@A-Infor try to create a clean VM and try to configure it like your host step-by-step until you find the culprit

**Comment by A-Infor** [comment]
I don't know why, but it worked again. Very strange.
