### ISSUE TITLE
XYB JPEG colour error

### ISSUE THREAD

**Issue by sommio** [telegramdesktop/tdesktop#27732]
### Steps to reproduce

0. Getting the [cjpegli](https://github.com/libjxl/libjxl/blob/main/tools/cjpegli.cc) encoder via `libjxl 0.10.2`
1. Use `cjpegli --xyb --target_size 300000 in.png out.jpeg` to create xyb jpeg images, which need to be less than 700KB or they will be re-encoded by tdesktop.
2. Send an image, tick the "Compress images". JPEGs smaller than 700KB will not actually be re-encoded.
3. Colour errors can now be observed.
![2024-04-09 20-18-50](https://github.com/telegramdesktop/tdesktop/assets/64189793/badf75ee-7e2e-4838-9318-336d743a4803)

### Expected behaviour

Present the correct colour.

![2024-04-09 20-20-48](https://github.com/telegramdesktop/tdesktop/assets/64189793/b576a0fa-6a90-4f85-8908-a8ad6e35221a)

### Actual behaviour

Colour error.

### Operating system

Arch Linux & GNOME 46

### Version of Telegram Desktop

4.16.2

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by sommio** [comment]
Sorry to interrupt, it's working fine.
