### ISSUE TITLE
Telegram desktop tray icon does not work and shows error

### ISSUE THREAD

**Issue by amirhj** [telegramdesktop/tdesktop#27731]
### Steps to reproduce

Run Telegram desktop with or without the -startintray option shows errors. On using the option, the desktop application does not start, but the process is running.

OS: Debian Trixie (13)
Desktop: GNOME Shell 44.9  (using mutter 44.8-3) on Wayland

### Expected behaviour

Show the application tray icon with options menu.

### Actual behaviour

Tray icon does not appear and running with  -startintray option shows error and does not work.

### Operating system

Debian GNU/Linux trixie

### Version of Telegram Desktop

4.16.5

### Installation source

Static binary from official website

### Logs

```shell
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
```

**Comment by ilya-fedin** [comment]
> ```shell
> qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
> ```

Your DE has no tray icon support so you won't see it
