### ISSUE TITLE
Add the ability to select previously set user avatars as the current avatar

### ISSUE THREAD

**Issue by alexgoryushkin** [telegramdesktop/tdesktop#27754]
### Is your feature request related to a problem?

Right now you can set a new avatar for a user from a file, but I'd like to be able to just use one of the user's already uploaded avatars
![image](https://github.com/telegramdesktop/tdesktop/assets/43167451/1ed300b4-7f58-4a5d-a876-f24e9cafe43a)

### Describe the solution you'd like

Add a "select from uploaded" button

### Describe alternatives you've considered

Leave it as it is

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
