### ISSUE TITLE
Telegram v4.16.7 crashes after opening chat

### ISSUE THREAD

**Issue by lukezaa** [telegramdesktop/tdesktop#27756]
### Steps to reproduce

1. Open Telegram.
2. Open chat that crashes Telegram on Linux.
3. Crash.

### Expected behaviour

1. Open Telegram.
2. Open chat.
3. Write with friends.

### Actual behaviour

Telegram core dumped with IOT instruction.

### Operating system

Ubuntu Focal 22.04

### Version of Telegram Desktop

4.16.7

### Installation source

Static binary from official website

### Logs

```shell
Logs from GDB


Thread 56 "Telegram" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffc47ff640 (LWP 122304)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140736490108480) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
```

Backtrace for this thread

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140736490108480) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140736490108480) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140736490108480, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff76f2476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff76d87f3 in __GI_abort () at ./stdlib/abort.c:79
```
```

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by lukezaa** [comment]
b77d4a4d-2dad-4509-422cacb2-c106f5d8

**Comment by lukezaa** [comment]
It looks like background photo crashed Telegram on Linux, after removing it using iPhone on this chat. Telegram works fine on Linux. So this is the issue.

**Comment by ilya-fedin** [comment]
Do you have any errors in terminal? Can you upload this image or provide a link to a group or channel with this photo set as backgroubd?

**Comment by ilya-fedin** [comment]
This also sounds as a dup of #27745
