### ISSUE TITLE
Can not write Local Passcode (Cursor not visible)

### ISSUE THREAD

**Issue by rahul-797** [telegramdesktop/tdesktop#27758]
### Steps to reproduce

1. Open telegram
2. Set Local Passcode

### Expected behaviour

The cursor should be visible by default or even after clicking the text field

![visible](https://github.com/telegramdesktop/tdesktop/assets/106862063/a106261f-c84a-40f8-9165-bce3f103e362)

### Actual behaviour

The cursor is not visible, even after clicking on text field. Have to close and open telegram multiple times for cursor to appear.

![not](https://github.com/telegramdesktop/tdesktop/assets/106862063/90d546e2-dc2d-4fb8-be86-69932d10c45e)

### Operating system

Arch Linux x86-64 (Linux 6.8.5-arch1-1) Gnome 46 Wayland

### Version of Telegram Desktop

4.16.7-1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

you aren't ussing the official binary from website.
