### ISSUE TITLE
Message by Telegram (42777) can't be deleted

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [telegramdesktop/tdesktop#27757]
### Steps to reproduce

1. Approve a device for Telegram Desktop
2. Change some security settings on Telegram Android
3. Notification appears `Two-Step Verification settings changed. Dear ..., your Two-Step Verification password and/or email were changed on 15/04/2024 at 20:16:10 UTC.`
4. Delete the chat on Desktop for both.
5. Restart Telegram Desktop and the message reappears.

### Expected behaviour

The chat should be deleted and not reappear.

### Actual behaviour

The deleted chat reappears on Desktop. 
![image](https://github.com/telegramdesktop/tdesktop/assets/45887282/d5917920-7d19-40cb-a2c9-a685dad52e71)

- The chat does not reappear on telegram-official or telegram-x
- Reinstalling Telegram Desktop, clearing cache, temporary data did not help.

### Operating system

Microsoft Windows [Version 10.0.19044.1288]

### Version of Telegram Desktop

4.11.6 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This means the chat doesn't gets deleted on server side which might be a server side bug. Mobile clients have message database so they remember that you deleted the chat while tdesktop doesn't have one and re-downloads everything from the server on each launch so you get the chats as provided by the server on each launch.

**Comment by ilya-fedin** [comment]
There's no fix, sorry. You can try to reach support to get information about this to server people but no promises this will help.
