### ISSUE TITLE
Clicking on a link opens a telegram window

### ISSUE THREAD

**Issue by electrofloat** [telegramdesktop/tdesktop#27753]
### Steps to reproduce

1. Click on a link in a channel or chat.

### Expected behaviour

It opens in the default browser.

### Actual behaviour

I don't know when exactly this started happening, but for some days now when I click on a link in a channel or chat, instead of opening it in the default browser, it just opens a new telegram window and tries to show the page inside it.

I couldn't find any option anywhere to revert back this behavior to how it was working before.

### Operating system

Windows

### Version of Telegram Desktop

4.16.6

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Well, it's called instant view and is familiar for people using mobile clients... Perhaps you click on button under link preview or on link preview rather the link itself?

**Comment by electrofloat** [comment]
I don't use the mobile client at all.

and as I said I've always used it this way, and it changed. If there's an option to revert it back the the previous behavior than I don't care if it stays.

**Comment by ilya-fedin** [comment]
It has changed, it is intended and it perhaps won't change back. Sorry but you have to get used to the new behavior.

**Comment by electrofloat** [comment]
How is rendering a web page with a constant blue background is an expected change? It does not even show the web page as it does in a browser window.

**Comment by ilya-fedin** [comment]
The bug report doesn't have anything about blue background. It just says you don't like the new behavior.

**Comment by electrofloat** [comment]
Yes. A http(s) link should ALWAYS open in the default browser UNLESS the user stated it wants otherwise. Especially if it worked this ways forever.

**Comment by ilya-fedin** [comment]
Well, it's your opinion

**Comment by electrofloat** [comment]
How does this crap equal to the browser rendered one?:
![image](https://github.com/telegramdesktop/tdesktop/assets/477252/cc3a0886-876e-44a4-a04e-62740a3b359d)

I cannot even do anything about it to NOT open in telegram. I have to at least right click->copy link, then go to the browser and insert link to see the real web page.

**Comment by ilya-fedin** [comment]
@electrofloat you can click on the link itself rather than link preview or button under link preview

**Comment by electrofloat** [comment]
I did just that.. and it still opened that window

**Comment by electrofloat** [comment]
Also.. what is this "unsupported" text here?:
![image](https://github.com/telegramdesktop/tdesktop/assets/477252/cfa386f6-6471-4665-bfda-76eb1018cf62)

**Comment by electrofloat** [comment]
As I said.. it does not even render the pages correctly. Just make an option in the app so people can switch it back and make this crap the default one if that's durov's wish then...

**Comment by electrofloat** [comment]
Also: https://www.telesec.top/telesec/telegram-desktop/arbitrary-code-execution-via-instantview

**Comment by electrofloat** [comment]
Just give a damn option to not use this "new feature"!
