### ISSUE TITLE
Muted channels not updating since 4.16.6

### ISSUE THREAD

**Issue by Purfview** [telegramdesktop/tdesktop#27755]
### Steps to reproduce

Install 4.16.6 version.
Mute channels.

### Expected behaviour

Channels updating - showing the unread counter.

### Actual behaviour

Channels doesn't update.
They update only after the program restart or after click on the channels.

### Operating system

Windows 7 x64

### Version of Telegram Desktop

4.16.6

### Installation source

Static binary from official website

**Comment by bzzz77** [comment]
I can confirm this, 4.6.16, Linux

**Comment by Purfview** [comment]
Maybe it's not a client issue?

**Comment by bzzz77** [comment]
seems 4.16.7 has fixed the issue (Linux)

**Comment by Aokromes** [comment]
> Maybe it's not a client issue?

it's fixed for you too? if yes, you can close ticket.

**Comment by Purfview** [comment]
> it's fixed for you too? if yes, you can close ticket.

Updated to 4.16.7, after ~one hour not a single channel had update.

When it was downgraded to 4.16.5 some channels were updating but some had post made ~30mins ago and it didn't show it. 
Then I downgraded to 4.16.0 and maybe it was better there. What is the time internal for the channel updates?

**Comment by Purfview** [comment]
Same bug with 4.16.8 too

**Comment by meredith2u** [comment]
5.0.2 still has this bug.
