### ISSUE TITLE
Mark muted chats with an icon

### ISSUE THREAD

**Issue by ironcito** [telegramdesktop/tdesktop#27764]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Telegram on Android displays a crossed speaker when a chat is muted. I would like something similar for Telegram Desktop. It would be even better if the muted icons were larger and lined up for easy scanning, like the pin icons, instead of being tiny and at the end of the chat's name, as they are on Android.

### Describe alternatives you've considered

Right now, I have to right-click each chat and see if I'm given the option to mute it or unmute it, thus knowing if it's currently muted or not.

**Comment by ilya-fedin** [comment]
#5981
