### ISSUE TITLE
Telegram Desktop (x64, Windows 10) not showing media, showing .octet-stream instead

### ISSUE THREAD

**Issue by axylisdead** [telegramdesktop/tdesktop#27761]
### Steps to reproduce

Telegram Desktop on the newest version has a weird issue. It shows all videos as a .octet-stream file and not as a video file, for contrast, here is what it looks like on my PC running the newest version of Telegram Desktop vs my phone running the newest version of the Telegram Android client.
![image](https://github.com/telegramdesktop/tdesktop/assets/135433130/4ef212ad-124c-4605-b968-b16ca7fd1161)

![download](https://github.com/telegramdesktop/tdesktop/assets/135433130/fc0abb92-ca0c-4a53-a374-0423ab19779d)
(sorry for the poor image, I can't screenshot on the app because of my privacy settings)

Images and GIFs load fine, only video files are broken

### Expected behaviour

It should load video files as video files.

### Actual behaviour

It loads the files as .octet-stream files, not making them viewable inside Telegram Desktop

### Operating system

Windows 10 Enterprise IOT LTSC

### Version of Telegram Desktop

4.16.7 x64

### Installation source

Static binary from official website

**Comment by axylisdead** [comment]
> Yeah, someone uploads video files and names them "application.octet-stream", which is not a valid name for a video file. So to prevent some security problems they are not rendered as video files anymore.
> 
> I'll change that to try to add a file extension that matches the provided video mime type and then check again, if the resulting filename becomes OK for a video file, then I'll leave this new, updated file name and display them as video file, otherwise they'll stay as you see them now.
> 
> I think (if the sender at least provides a correct mime type for those video files) this will fix the problem in the next version.

No, the issue is with all of the video files, regardless of it's naming structure. All of them have this same issue, regardless of the channel or the way that it's named

**Comment by john-preston** [comment]
@axylisdead That's not true. Here is a channel with a video with a valid filename in the video attributes:

https://t.me/telegram/292

**Comment by john-preston** [comment]
Here is a channel not related to Telegram that uploads videos with normal names: https://t.me/denissexy/8047

If you create a channel and upload a video from your phone you'll see it works fine as well.

**Comment by axylisdead** [comment]
That's strange, my apologies, some of them seem to be working fine on some channels and others seem not to work at all. For example I sent a video to a friend a week ago, and now with the new update it doesn't work at all and I can't see the video anymore

![image](https://github.com/telegramdesktop/tdesktop/assets/135433130/eeef89d0-9b9a-4c19-b37b-9d60b91261f1)

But some on some other channels work absolutely fine, strange

**Comment by Aokromes** [comment]
i have upload a random mp4... works for me 

https://i.imgur.com/ARDuBKi.png

**Comment by pauladeanda111** [comment]
Same for FLAC AND FLA files
-PC: 
![PC](https://github.com/telegramdesktop/tdesktop/assets/36976292/6c2e369d-906d-4226-81a2-84938ab4fe5c)

-Phone Android: 
![Phone](https://github.com/telegramdesktop/tdesktop/assets/36976292/6484ca96-936b-480d-919c-d96721f71b98)

**Comment by Aokromes** [comment]
fla ain't audio format.... maybe misspelled flac?

**Comment by john-preston** [comment]
Actually, .fla is Adobe Flash extension, so I guess this file has incorrect filename. But it should work in the next version with the extension addition.

**Comment by edoooss22** [comment]
![изображение](https://github.com/telegramdesktop/tdesktop/assets/98092486/a3eb299d-6bd0-471d-b0eb-4792694c7a12)
![изображение](https://github.com/telegramdesktop/tdesktop/assets/98092486/69b81375-4e8d-42d2-a882-62a88f01cca1)

The media is not displayed. The audio file is sent via the Bot API. I am sending bytes of an MP3 file.

**Comment by john-preston** [comment]
Please try 4.16.8 version.
