### ISSUE TITLE
Unable to send crash report

### ISSUE THREAD

**Issue by tuxmaster5000** [telegramdesktop/tdesktop#27760]
### Steps to reproduce

1. Start telegram after crash
2.  Try to send the crash data

### Expected behaviour

That the data will be send.

### Actual behaviour

Only the message "Network error" will shown and this will be logged:
```
Apr 16 10:27:39 Telegram[24225]: qt.network.ssl: No functional TLS backend was found
Apr 16 10:27:39 Telegram[24225]: qt.network.ssl: No functional TLS backend was found
Apr 16 10:27:39 Telegram[24225]: qt.network.ssl: No TLS backend is available
Apr 16 10:27:39 Telegram[24225]: qt.network.ssl: No functional TLS backend was found
Apr 16 10:27:39 Telegram[24225]: qt.network.ssl: No functional TLS backend was found
Apr 16 10:27:39 Telegram[24225]: qt.network.ssl: No functional TLS backend was found
Apr 16 10:27:39 Telegram[24225]: qt.network.ssl: No functional TLS backend was found
Apr 16 10:27:39 Telegram[24225]: qt.network.ssl: No TLS backend is available
Apr 16 10:27:39 Telegram[24225]: qt.network.ssl: No functional TLS backend was found
Apr 16 10:27:39 Telegram[24225]: qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed

```

### Operating system

Fedora-38

### Version of Telegram Desktop

4.16.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Fedora 38 is quite old... Can you reproduce on latest OS version (Fedora 40)?

**Comment by tuxmaster5000** [comment]
Same on F39, because F40 are beta.
https://fedoraproject.org/

**Comment by ilya-fedin** [comment]
What does `ls /etc/ssl` return?

**Comment by tuxmaster5000** [comment]
ls /etc/ssl
`cert.pem  certs  ct_log_list.cnf  openssl.cnf  README`
ls -l /etc/ssl
```
lrwxrwxrwx. 1 root root   49  1. Aug 2023  cert.pem -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
lrwxrwxrwx. 1 root root   46  1. Aug 2023  certs -> /etc/pki/ca-trust/extracted/pem/directory-hash
lrwxrwxrwx. 1 root root   28  1. Aug 2023  ct_log_list.cnf -> /etc/pki/tls/ct_log_list.cnf
lrwxrwxrwx. 1 root root   24  1. Aug 2023  openssl.cnf -> /etc/pki/tls/openssl.cnf
-rw-r--r--. 1 root root 1167  1. Aug 2023  README
```

**Comment by ilya-fedin** [comment]
What is the first version with this issue?

**Comment by tuxmaster5000** [comment]
I don't know, because this is the first version, where I can trigger an crash reproducible.
That's why I only noticed it now.
Apart from the reproducible process that leads to the crash, Telegram seems to work normally.

**Comment by ilya-fedin** [comment]
There's a `crashplease` cheat code exactly to trigger crash reporter for debugging

**Comment by tuxmaster5000** [comment]
It will result ins this:
![Bildschirmfoto vom 2024-04-16 17-59-02](https://github.com/telegramdesktop/tdesktop/assets/837503/817980ca-050d-4530-9a7f-0549134501b8)
![Bildschirmfoto vom 2024-04-16 17-59-58](https://github.com/telegramdesktop/tdesktop/assets/837503/1b942e85-9109-44ea-a76b-f28dee5be624)
```
ApiId: 2040
Assertion: Unexpected: Crashed in Settings! settings_codes.cpp:96
Binary: Telegram
Launched: 16.04.2024 17:24:12
OpenGL: Enabled
OpenGL Renderer: [not-initialized]
Platform: Linux
UserTag: de5c4c95ec763343
Version: 4016007

Caught signal 6 (SIGABRT) in thread 140624591257024
Google Breakpad caught a crash, minidump written in thread 140624591257024
Minidump: /home/<username>/.TelegramDesktop/tdata/dumps/8d5bd819-6bbe-473e-adb85cad-623c22f5.dmp
```

**Comment by ilya-fedin** [comment]
Yeah, can you find first broken version now?

**Comment by tuxmaster5000** [comment]
Where I can download the old versions?

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/releases
Note that downgrading will lead to the data directory being cleaned. You can create a `TelegramForcePortable` folder near executable to write the data there.

**Comment by tuxmaster5000** [comment]
I can't find an working one :(
Now I was back to 4.10.3, but in all versions the report part fails.
So no idea to which version I can go back.

**Comment by ilya-fedin** [comment]
Try with 4.16.10

**Comment by tuxmaster5000** [comment]
Hi @ilya-fedin ,
today I have checked it with Fedora-38 + 39. On both now it will works.
Thanks.
