### ISSUE TITLE
Theme preview: Search string isn't translated to english.

### ISSUE THREAD

**Issue by aleixx** [telegramdesktop/tdesktop#2776]
### Steps to reproduce
1. Find a theme with extension .tdesktop-theme
2. Click it
3. Instead of search, i see buscar (search in spanish)
4. http://i.imgur.com/TxCBhuR.png

### Expected behaviour
Search instead of buscar

### Actual behaviour
Buscar instead of search

### Configuration
**Operating system:**

**Version of Telegram Desktop:** v0.10.23

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by john-preston** [comment]
@aleixx what language is set in Telegram? What do you see in your real search field (not theme preview)? Looks like "Write a message..." is also not in English in your screenshot.

**Comment by aleixx** [comment]
Ops you are totally right. I changed from english to spanish (and vice versa) several times...

Sorry for the issue. The only error here is "Apply this theme" is not translated to spanish ("Aplicar este tema").

Thanks for your fast answer.

**Comment by john-preston** [comment]
@aleixx It is not translated yet, right. It will be when the stable version is released.
