### ISSUE TITLE
Can't login on my mobile device to telegram

### ISSUE THREAD

**Issue by bondobrus** [telegramdesktop/tdesktop#27773]
### Steps to reproduce

1. login on mobile with phone

### Expected behaviour

I want to login on my mobile device to telegram, but I can't because I don't have access to my number anymore. However Im logged on my pc to here. I just reinstalled the app so I can't change the number of course from here ... So the case is: I can't login  on phone but I'm logged on my pc. Can I do something with it

### Actual behaviour

Check above

### Operating system

windows/android

### Version of Telegram Desktop

current

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
not a bug, you need active mobile phone session.
