### ISSUE TITLE
should i install  emsdk before build telegram?

### ISSUE THREAD

**Issue by younggggger** [telegramdesktop/tdesktop#27777]
### Steps to reproduce

[18/28](Libraries/libjxl): CHANGED, (r)ebuild, rebuild (a)ll, (s)kip, (p)rint, (q)uit?: BUILDING:
---------------------------------COMMANDS-LIST----------------------------------
if exist libjxl rmdir /Q /S libjxl
if exist libjxl exit /b 1
git clone  --recursive --shallow-submodules https://github.com/younggggger/libjxl.git
cd libjxl
SET "cmake_defines=-DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_FUZZERS=OFF -DJPEGXL_ENABLE_DEVTOOLS=OFF -DJPEGXL_ENABLE_TOOLS=OFF -DJPEGXL_ENABLE_DOXYGEN=OFF -DJPEGXL_ENABLE_MANPAGES=OFF -DJPEGXL_ENABLE_EXAMPLES=OFF -DJPEGXL_ENABLE_JNI=OFF -DJPEGXL_ENABLE_JPEGLI_LIBJPEG=OFF -DJPEGXL_ENABLE_SJPEG=OFF -DJPEGXL_ENABLE_OPENEXR=OFF -DJPEGXL_ENABLE_SKCMS=ON -DJPEGXL_BUNDLE_SKCMS=ON -DJPEGXL_ENABLE_VIEWERS=OFF -DJPEGXL_ENABLE_TCMALLOC=OFF -DJPEGXL_ENABLE_PLUGINS=OFF -DJPEGXL_ENABLE_COVERAGE=OFF -DJPEGXL_ENABLE_PROFILER=OFF -DJPEGXL_WARNINGS_AS_ERRORS=OFF"
cmake . ^
-A %WIN32X64% ^
-DCMAKE_INSTALL_PREFIX=%LIBS_DIR%/local ^
-DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>" ^
-DCMAKE_C_FLAGS="/DJXL_STATIC_DEFINE /DJXL_THREADS_STATIC_DEFINE" ^
-DCMAKE_CXX_FLAGS="/DJXL_STATIC_DEFINE /DJXL_THREADS_STATIC_DEFINE" ^
-DCMAKE_C_FLAGS_DEBUG="/MTd /Zi /Ob0 /Od /RTC1" ^
-DCMAKE_CXX_FLAGS_DEBUG="/MTd /Zi /Ob0 /Od /RTC1" ^
-DCMAKE_C_FLAGS_RELEASE="/MT /O2 /Ob2 /DNDEBUG" ^
-DCMAKE_CXX_FLAGS_RELEASE="/MT /O2 /Ob2 /DNDEBUG" ^
%cmake_defines%
cmake --build . --config Debug
cmake --install . --config Debug
cmake --build . --config Release
cmake --install . --config Release
--------------------------------------------------------------------------------
Cloning into 'libjxl'...

### Expected behaviour

ok

### Actual behaviour

-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test JPEGXL_EMSCRIPTEN
-- Performing Test JPEGXL_EMSCRIPTEN - Failed
-- CMAKE_SYSTEM_PROCESSOR is AMD64
-- Performing Test CXX_FUZZERS_SUPPORTED
-- Performing Test CXX_FUZZERS_SUPPORTED - Failed
-- Performing Test CXX_CONSTRUCTOR_ALIASES_SUPPORTED
-- Performing Test CXX_CONSTRUCTOR_ALIASES_SUPPORTED - Failed
-- Performing Test CXX_MACRO_PREFIX_MAP
-- Performing Test CXX_MACRO_PREFIX_MAP - Failed
-- Performing Test CXX_NO_RTTI_SUPPORTED
-- Performing Test CXX_NO_RTTI_SUPPORTED - Failed
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Performing Test JXL_HWY_DISABLED_TARGETS_FORCED
-- Performing Test JXL_HWY_DISABLED_TARGETS_FORCED - Failed
-- Compiled IDs C:MSVC, C++:MSVC
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Performing Test ATOMICS_LOCK_FREE_INSTRUCTIONS
-- Performing Test ATOMICS_LOCK_FREE_INSTRUCTIONS - Success
-- Could NOT find HWY (missing: HWY_LIBRARY HWY_INCLUDE_DIR) (Required is at least version "0.15.0")

### Operating system

win10

### Version of Telegram Desktop

latest

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Looks like you changed prepare.py script (libjxl is not original and is not on the tag) so it needs new dependencies? The prepare.py in the repo doesn't seem to have such a problem.

**Comment by younggggger** [comment]
congras to me.
The problem of "emoji.h" can't find is solved by me.When Telegram.sln generated,build codegen FIRST,it generate file,emoji.h;then build telegram.
But YOUR building-***.md not mentioned.
![image](https://github.com/telegramdesktop/tdesktop/assets/127868785/086a5af7-1fe3-49b9-a579-b0f49de30e16)

**Comment by younggggger** [comment]
> Yeah, you don't need to do that. You have something done wrongly.

i build telegram from sourcecode because i can't receive sms code from the version of official telegram app.
so when i debug telegram,i don't receive sms code too ,can you tell me where is sms code to send in debug environment of sourcecode?
thank you

**Comment by ilya-fedin** [comment]
@younggggger the server won't you get the code unless you use official Android or iPhone applications. In case of Android, google services must be installed.

**Comment by younggggger** [comment]
> @younggggger the server won't send the code unless you use official Android or iPhone application. In case of Android, google services must be installed.

in debug environment, server don't send the code,how can i log in to debug?

**Comment by ilya-fedin** [comment]
@younggggger you mean the test server? do you use TDESKTOP_API_TEST?

**Comment by ilya-fedin** [comment]
> how to configure TDESKTOP_API_TEST?

`-D TDESKTOP_API_TEST=ON` to configure.bat

**Comment by younggggger** [comment]
thank you ,i take a try

**Comment by younggggger** [comment]
> > how to configure TDESKTOP_API_TEST?
> 
> `-D TDESKTOP_API_TEST=ON` to configure.bat

i added -D TDESKTOP_API_TEST=ON to configure.bat,but still can't receive sms code

**Comment by younggggger** [comment]
> > how to configure TDESKTOP_API_TEST?
> 
> `-D TDESKTOP_API_TEST=ON` to configure.bat

i added -D TDESKTOP_API_TEST=ON to configure.bat,but still can't receive sms code,can you help me?

**Comment by ilya-fedin** [comment]
I have no idea why you can't :(
It worked to me last time I tried... It was quite a long time ago, though.
