### ISSUE TITLE
Indentations in monospace formatted code blocks created in macOS Telegram Desktop are not being retained when message is viewed in web browser.

### ISSUE THREAD

**Issue by allanster** [telegramdesktop/tdesktop#27786]
### Steps to reproduce

1. Create a message in macOS Telegram Desktop with a monospace formatted code block that contains 4 space indentations:

```
var countMethodB  = 0
if not closeAboveMA
    countMethodB := 0
else if rsiIsAbove50
    countMethodB += 1
else
    countMethodB
```
 
 2. View the same message in web browser and the 4 space indentations have been discarded, for example:
[https://t.me/PineCodersQA/19543 ](https://t.me/PineCodersQA/19543)

### Expected behaviour

Messages created in Telegram Desktop with monospace formatted indentations should have their indentations honored when viewed in web browser.

### Actual behaviour

Messages created in Telegram Desktop with monospace formatted indentations have their indentations discarded when viewed in web browser.

### Operating system

macOS 13 Ventura

### Version of Telegram Desktop

4.16.6

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
That's quite a weird report: if web client can't show the indentation, it's a bug of the web client...
