### ISSUE TITLE
Media Viewer broken

### ISSUE THREAD

**Issue by kaiyga** [telegramdesktop/tdesktop#27789]
### Steps to reproduce

Steps to reproduce

Install Wayland, Gnome shell
```pacman -S telegram-desktop```

1.Start Telegram-Desktop
2.Click to media 

![image](https://github.com/telegramdesktop/tdesktop/assets/92279086/55b71e8c-79fc-4687-a10a-f46aa23d7e9e)

### Expected behaviour

View Media ?

### Actual behaviour

Transparent Media Viewer. Can't focus window 
Video is play, sound play. But window is transparent, can't focus 

https://github.com/telegramdesktop/tdesktop/assets/92279086/ffe641ed-f9c3-486c-a45b-131b48b1823b

### Operating system

Arch Linux | Wayland | Shell Gnome 46

### Version of Telegram Desktop

4.16.8

### Installation source

Other (unofficial) source

### Logs

```shell
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.core.qobject.connect: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
qt.svg: Error while inflating gzip file: SVG format check failed
```

**Comment by Romern** [comment]
Same behaviour, using:

```
telegram-desktop 4.16.8-1
gnome-desktop 1:44.0-1
gnome-shell 1:46.0-1
mutter 46.0-3
wayland 1.22.0-1
```
