### ISSUE TITLE
Bad UI performance on Linux Wayland

### ISSUE THREAD

**Issue by PoSayDone** [telegramdesktop/tdesktop#27785]
### Steps to reproduce

#26343 regression

### Expected behaviour

Normal fps

### Actual behaviour

Laggish non responsive UI

### Operating system

NIxOS 23.04, Hyprland

### Version of Telegram Desktop

4.16.7 (nixpkgs)

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
> #26343 regression

> Other (unofficial) source

I'm not sure how there could be a regression given that the fix was done to the tdesktop's Qt patchset and you don't use a build using it?

**Comment by PoSayDone** [comment]
> > #26343 regression
> 
> > Other (unofficial) source
> 
> I'm not sure how there could be a regression given that the fix was done to the tdesktop's Qt patchset and you don't use a build using it?

I am using telegram version from nixpkgs.
Thats how it is build: https://github.com/NixOS/nixpkgs/blob/2af28fdb92772859d606fa7140a00380b7f2cb3b/pkgs/applications/networking/instant-messengers/telegram/telegram-desktop/default.nix

**Comment by ilya-fedin** [comment]
That is exactly my point, it has no fix as it doesn't use the Qt patchset. You have to use static binary, flatpak or snap package.
