### ISSUE TITLE
Drag & Drop of URLs/Links from Telegram Desktop to Browser no longer works

### ISSUE THREAD

**Issue by jmbreuer** [telegramdesktop/tdesktop#27780]
### Steps to reproduce

1. Have a message with a URL/link in Telegram Desktop
2. Grab&drag that link
3. Try to drop that link into an existing browser tab / as a new browser tab / ...

### Expected behaviour

Dragging&Dropping links/URLs should interoperate with web browsers (and other applications that handle URLs in that way).

### Actual behaviour

Dragging&dropping links to my system browser (LibreWolf, but also tried with Firefox and Vivaldi) - as a new tab, into an existing tab, or into the address bar - used to work as expected a while ago, for a period of weeks going on months it no longer works. Trying to 'drop' the link will show the "not a valid/usable drop target for this entity" cursor.

At first, I suspected a change/bug in LibreWolf, but checking against other browsers and with other desktop chat clients (e.g. Signal) makes it obvious that the change/bug is with Telegram Desktop.

With Vivaldi, I can drop links from Telegram into the address bar; but not as a new or existing tab either. It seems that Vivaldi is more lenient with regards to the content types it allows to be dropped as an address than Firefox/LibreWolf.

### Operating system

gentoo 23.0 KDE Plasma x64

### Version of Telegram Desktop

4.15.2

### Installation source

Other (unofficial) source

### Logs

```shell
(there are no log entries that correspond to drag&drop)
```

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

also works for me with 4.16.8 to edge browser.

**Comment by ilya-fedin** [comment]
> At first, I suspected a change/bug in LibreWolf, but checking against other browsers and with other desktop chat clients (e.g. Signal) makes it obvious that the change/bug is with Telegram Desktop.

Are you sure? I would suspect incompatibility between underlying toolkits of librewolf and tdesktop (gtk and qt). Signal uses a yet another toolkit - Electron (Chromium).

And, yeah, you need to check official binaries as @Aokromes. Unofficial builds aren't covered by this bugtracker.
