### ISSUE TITLE
Can't disable formatting shortcuts.

### ISSUE THREAD

**Issue by Innomen** [telegramdesktop/tdesktop#2779]
I want to be able to type * smiles * (without the spaces) instead of **smiles.**

(How ironic, github has this same problem.)

I want to be able to disable it in my messages. It's absurd to force that.

**Comment by Akronix** [comment]
Are you sure you're talking about telegram desktop? in version 0.10.20 `*smiles*` does actually write `*smiles*`
If you want to avoid formatting in the Android app or in the web app, you can always use monospace shortcut surrounding ([two grave accents](https://guides.github.com/features/mastering-markdown/)) And it will write what the enclosing text literally.

**Comment by Innomen** [comment]
Yeah pretty sure.

https://github.com/telegramdesktop/tdesktop/issues/522

Also annoying that there isn't a main telegram github. It's a common thing for problems in one version to be dismissed as not specific to that version such that you end up with no where to express issues.

https://github.com/telegramdesktop/tdesktop/issues/1737

I'm migrating over to signal. Fortunately only a handful of people in my context use telegram. It seems the changes I want aren't ever going to be made and the changes that are made are making it worse.

Pretty positive the server side code is never going to be open sourced, and that alone is just an unacceptable long term security issue.

https://www.reddit.com/r/Telegram/comments/4b45ie/when_if_ever_will_telegrams_server_side_source/

Spell checking, log export, multiple windows, contact differentiation... Looks like none  of it is ever going to happen.

Signal might be feature sparse right now but at least it's building on the right foundation.

**Comment by Akronix** [comment]
OK. Maybe it depends on your underlying operating system, what is it?

Although I could agree with mostly of your opinions about open-sourcing server side, server API updates, community hearing and lacking of a feedback mailbox; this is still not the place for this.
On the other hand, there are many wide-used and not open-source apps that don't necessarily listen to their users and nobody looks to complain: Whatsapp, Facebook, Slack, Snapchat,...

**Comment by Innomen** [comment]
"this is still not the place for this"

That's my point. There isn't one, by design. It's like by the magic of responsibility diffusion what would have been shady if one person or company did it somehow turned ok when it because common practice. 

"and nobody looks to complain"

Perhaps because they make it impossible to do so in such a way as consensus is revealed? See my our previous comment about this not being the place and there not being one.

FWIW, A Google search of "(service name) sucks" returns 8020, 136k, 2040, 5730 results (respectively). That's a fair amount of complaint, and I think you'll agree those numbers are low given I've only chosen one possible simplistic and rude way to express complaint.

In any case, thanks for listening.

**Comment by stek29** [comment]
> GitHub has this same problem 

\*RTFM\*

TDesktop doesn't support markdown. Not for now. Please show us what a magic version do you have: I wish I was able to type \*text\* and get **text**

> log export

What's exactly wrong with log export? You just go to tdata folder and grub the logs.

>  A Google search of "(service name) sucks" returns 8020, 136k, 2040, 5730 results (respectively).

Respectively to?...

> I'm migrating over to signal

Keep us informed.

**Comment by stek29** [comment]
Formatting is done on client side. When your GF tries to send you `*smiles*` app actually sends `smiles` and an entity saying that 6 chars starting at position 0 are bold.

Also, have a look at this [tweet](https://twitter.com/telegram/status/817080202257952768).

And RTFM was about GitHub markdown, not about Telegram.

**Comment by Innomen** [comment]
> Also, have a look at this tweet.

Excellent news! 

The coders are gonna stay pissed and I still say we need a toggle off in settings, and I'll respond to that tweet accordingly.

Thank you :)

**Comment by stek29** [comment]
@Innomen Even better -- look at this: https://telegram.me/tgbeta/1068
@auchri I'd say it's not an <kbd>api issue</kbd>, it's more likely an <kbd>invalid</kbd> report.
