### ISSUE TITLE
Globally ignore user

### ISSUE THREAD

**Issue by Metalneck** [telegramdesktop/tdesktop#27797]
### Is your feature request related to a problem?

A way to ignore (not see any messages from in chats and block from receiving private messages) of a user either per group or preferably globally. There's always at least 1 user that you just can't stand and it would be great to just not see anything from them. This is the only feature Telegram is lacking IMO. 

### Describe the solution you'd like

Enter a user's profile and select a toggle to ignore them or not. This would just not show any of their messages in group chats. Implement it into when you block a user from sending direct messages. 

### Describe alternatives you've considered

There are no alternatives sadly, outside of leaving any group that you would share with the other user.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
