### ISSUE TITLE
Media Viewer is not rendering in GNOME

### ISSUE THREAD

**Issue by jasursadikov** [telegramdesktop/tdesktop#27792]
### Steps to reproduce

Just open any media, like photo or video to show Media Viewer

### Expected behaviour

Media Viewer should be displayed

### Actual behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/14846427/7133cbe2-e1ae-41f8-b159-67f0da849c07)
Media viewer has its own window but it is blank

### Operating system

ArchLinux

### Version of Telegram Desktop

4.16.8

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/27789#issuecomment-2068042887
