### ISSUE TITLE
Option to prevent app from running in background

### ISSUE THREAD

**Issue by recolic** [telegramdesktop/tdesktop#27793]
### Is your feature request related to a problem?

Currently Telegram is always running in the background. Using system hotkeys (or close button) is much more convenient than tray>quit

### Describe the solution you'd like

Add a toggle to settings to control whether Telegram will minimize to tray or quit on close.

### Describe alternatives you've considered

I checked the previous Issue https://github.com/telegramdesktop/tdesktop/issues/27190 , it said "disable show tray icon".

I searched the whole internet to figure out how to disable tray icon, but eventually realized it's impossible.
![image](https://github.com/telegramdesktop/tdesktop/assets/19610256/63231494-d531-4912-91d1-15d4d4a842a8)

So the previous issue #27190 is still valid, I'm reopening it.

**Comment by ilya-fedin** [comment]
> I checked the previous Issue #27190 , it said "disable show tray icon".

The right answer is the second one (provided by me).
