### ISSUE TITLE
!!! STOP HIDING THE F***ING PROXY SETTINGS BUTTON !!!

### ISSUE THREAD

**Issue by babakfp** [telegramdesktop/tdesktop#27791]
### Steps to reproduce

Hi 👋

The Telegram team has made a stupid design decision to hide some buttons randomly. Other developers also make the same mistake in their apps. F***CKING STOP IT.

What are these UI Elements that get invisible randomly and piss me off?

For example this "Proxy settings" button:

<img width="34" alt="Screenshot 2024-04-21 103059" src="https://github.com/telegramdesktop/tdesktop/assets/44144724/cbdde275-7465-44bd-abcb-02b008406a9a">

(On the Android version, it's the Proxy and Downloads buttons).

I want that button to be visible all the f***ing time. Stop hiding it. Delete the stupid code that hides it. It's a f***ing important button, so I need to have it available all the time, but it gets hidden sometimes and there is no way to get it back other than closing (killing) and reopening the app!

Change the design to put it somewhere that it doesn't overlay on content, or add an option that locks it in place all the time.

### Expected behaviour

.

### Actual behaviour

.

### Operating system

Windows

### Version of Telegram Desktop

4.16.8 x64 (add a note on how users can find the version number!!!)

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> Change the design to put it somewhere that it doesn't overlay on content

There's already such a place: advanced settings

**Comment by babakfp** [comment]
> There's already such a place: advanced settings

?

**Comment by ilya-fedin** [comment]
> ?

!

**Comment by babakfp** [comment]
What option are you talking about?

**Comment by ilya-fedin** [comment]
Settings -> Advanced -> Connection type

**Comment by babakfp** [comment]
I found it. Good to know. Thanks 👍🌸

> Change the design to put it somewhere that it doesn't overlay on content, or add an option that locks it in place all the time.

I suggested this so that the team keeps the button visible all the time by relocating it or adding an option. Just in case they were going to insist that the current behavior is so awesome and they can't change it.

Now that you let me know about the "Settings -> Advanced -> Connection type" option, I can say that adding an option to lock the button isn't a good idea because people are not going to know about it.

I would suggest then to change it's location, because it's also pretty hard to spot it sometimes. I would suggest adding a button in this sidebar (and letting users move it to first and last and before the edit button):

<img width="68" alt="Screenshot 2024-04-21 114850" src="https://github.com/telegramdesktop/tdesktop/assets/44144724/22b9f616-d636-4457-b3e7-7563b7065091">

**Comment by Aokromes** [comment]
not a bug, not hiding.

**Comment by babakfp** [comment]
What do you mean by "not a bug"? IT IS A BUG. IT IS AN UNEXPECTED BEHAVIOR BY THE APPLICATION. IT BREAKS THE FUNCTIONALITY OF THE APPLICATION AND MAKES A FEATURE UNFUNCTIONAL FOR THE USER. Doesn't matter that there is a workaround deep in the settings.

**Comment by ilya-fedin** [comment]
Well, I believe it behaves just like it was designed: most users won't ever need those settings so they're deep in settings. For those who set a proxy, the overlay icon appears.

**Comment by babakfp** [comment]
> it behaves just like it was designed

This is exactly the problem. This is a flawed design. This is a bad design.

> most users won't ever need those settings

Telegram has added the proxy feature, there are a lot of channels that share proxies, and obviously, a lot of users need and use it.

Proxies get disconnected, or users may be using a double proxy so sometimes they want to disable one in favor of another. I connect and disconnect proxies all the time because without it the internet is 100% not accessible.

> the overlay icon

Yes, and it has a flawed design.

I want the app that I use to play nice, not to make me crazy!

**Comment by babakfp** [comment]
I reported a similar issue for the Android version a long time ago: https://bugs.telegram.org/c/35812
This shit has annoyed me for literal **years** and it should get fixed!

**Comment by ilya-fedin** [comment]
@babakfp the design is made by the designer and is not something users can request ti change, sorry :(

**Comment by babakfp** [comment]
So, if they say change it, it will get changed?
Give me the contact info of the designer, I must talk with them!

**Comment by ilya-fedin** [comment]
@babakfp that's the main thing - they are not public persons, so you can't request anything from them.

**Comment by babakfp** [comment]
Someone must have connections with them. I want to talk to that person.

**Comment by babakfp** [comment]
Does it still need to get through the design team if the overlay button only changes to stay locked? So it never gets hidden. If it's not specifically stated by the design team that the button randomly should get hidden, then it should be OK to change the behavior.

**Comment by ilya-fedin** [comment]
Any UI change has to be done by designers AFAIK

**Comment by babakfp** [comment]
I created this too so maybe it helps: https://bugs.telegram.org/c/39272

**Comment by babakfp** [comment]
@john-preston Do you have a way to contact the design team? GitHub shows that you are the only member of his organization!

**Comment by f242** [comment]
@ilya-fedin @john-preston The proxy button should always be displayed if there is at least one proxy server in the settings. It should just change its status (color) depending on the connection status, via proxy or directly. It is very far to go to the settings to enable a proxy server.
