### ISSUE TITLE
"send now" multiple selected sheduled messages, order is unexpected (follows compose time, not sheduled time)

### ISSUE THREAD

**Issue by SVNKoch** [telegramdesktop/tdesktop#27802]
### Steps to reproduce

We will need three dates for sheduled messages A, B, C, such that A < B < C (eg tomorrow, in 2 days, in 3 days)
1. schedule message "a" at date A
2. schedule message "c" at date C (⚠️ C first, then B)
3. schedule message "b" at date B
![grafik](https://github.com/telegramdesktop/tdesktop/assets/39488412/9bb22227-59c8-4122-989e-099587dfb686)
4. now select them and send them now
![grafik](https://github.com/telegramdesktop/tdesktop/assets/39488412/cd44acb0-379d-4027-bd1b-5ac4c106f037)

### Expected behaviour

order should of sent messages should be determined by the time of which they are sheduled for
like this 
![grafik](https://github.com/telegramdesktop/tdesktop/assets/39488412/a52a3c5b-670b-4d8b-8b55-bf687287cb0b)
so "a", "b", "c"

### Actual behaviour

order is determined by the time of which the messages were composed, not to when they were sheduled
![grafik](https://github.com/telegramdesktop/tdesktop/assets/39488412/c925c0b5-8844-401b-b066-a7807c1ab2fe)
so "a", "c", "b"

### Operating system

Windows 10 LTSC

### Version of Telegram Desktop

4.16.4 x64

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
What about the mobile client?

**Comment by SVNKoch** [comment]
on mobile (at least android) you don't have the "send now" option, thus this isn't a problem.
![Screenshot_20240427-183958](https://github.com/telegramdesktop/tdesktop/assets/39488412/d7fc2541-b079-4f9b-8686-bb13e9640c0b)

**Comment by 23rd** [comment]
If you wish, you can test a nightly debug build. It should be better now.
https://github.com/telegramdesktop/tdesktop/actions/runs/8866982405

**Comment by kartavenko1983** [comment]
The telegram publication timer is not working correctly. Publication may occur 5-10 minutes later than the scheduled time. The time of publication in the post also changes.

**Comment by SVNKoch** [comment]
@23rd I confirmed in the Telegram_x64 version, that the behaviour **now works as expected**. Thanks for implementing!

@kartavenko1983 comment seems unrealated, I think it has to do with diferent local time vs server time. My sheduled was "early" by like 8 seconds comapred to local machine time, but that is probably just my machine I assume.


Detailed testing:
Sheduled mesages (order of creation: a, c then b):
![grafik](https://github.com/telegramdesktop/tdesktop/assets/39488412/1279c19b-aacd-4684-b882-1516a05ce90b)
after sending all three now:
![grafik](https://github.com/telegramdesktop/tdesktop/assets/39488412/3e1d4fa0-9552-40c6-8b1a-a346323cf9ad)

I also tried multiple messages sheduled to same time => will send in the order in which they were displayed in the sheduled messages preview.
I also tried having sheduled messages A C B, resheduling B to order A B C => sends in the correct order that is also shown in the sheduled messages preview (A B C).

As a programmer inexperienced with c++, the code looks fine too.

**Comment by kartavenko1983** [comment]
@SVNKoch Of course, I understand that there may be a delay, but not for 10 minutes, but for a couple of seconds. In addition, there was a case once that the record was not published at all

**Comment by SVNKoch** [comment]
@kartavenko1983 you might have a valid bug here. However I don't see the relation of that problem to this issue. It has nothing to do with my original problem and is not effected by the proposed solution.
You should create a new bug ticket and best to attach some logs / more details other than just that it sent with delay.

**Comment by SVNKoch** [comment]
It was already fixed in the nightbuilt and I just confirmed it works in the recent release (5.9 x64)
