### ISSUE TITLE
Personal channel information

### ISSUE THREAD

**Issue by star-tek-mb** [telegramdesktop/tdesktop#27808]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I want to include last post and avatar of user's personal channel. Like how it's done in mobile applications.

### Describe alternatives you've considered

Haven't found anything

### Additional context

![case1](https://github.com/telegramdesktop/tdesktop/assets/12962448/99272b3e-eaf4-4cef-b0e9-9ce0318927f2)
![case2](https://github.com/telegramdesktop/tdesktop/assets/12962448/6d01159c-ad63-4bd0-8cf2-493b8f6faaa9)

**Comment by Aokromes** [comment]
you mean https://i.imgur.com/NiCSlUc.png ? already possible on latest beta.

**Comment by star-tek-mb** [comment]
I think its implemented now. Don't know since what version. Thanks!
