### ISSUE TITLE
Version 4.16.9 broke app UI (font aspect)

### ISSUE THREAD

**Issue by tomkoi** [telegramdesktop/tdesktop#27804]
### Steps to reproduce

Upgrade to late test
playing with font and scale options
revert to older version

### Expected behaviour

I really like how the app was until today, not sure what the font it's using, but by mistake I got the 4.16.9 and with new font option change + interface scale all the UI looks bad, and I can't read anything as I used to, I tried to play with the fonts and the scale - nothing helped. After revert to 4.16.8 all good.
Sadly I don't have a screenshot, but I'm Mac m1 user with Dell 4k 27' monitor.

### Actual behaviour

I really like how the app was until today, not sure what the font it's using, but by mistake I got the 4.16.9 and with new font option change + interface scale all the UI looks bad, and I can't read anything as I used to, I tried to play with the fonts and the scale - nothing helped. After revert to 4.16.8 all good.
Sadly I don't have a screenshot, but I'm Mac m1 user with Dell 4k 27' monitor.

### Operating system

MacOS

### Version of Telegram Desktop

4.16.9

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Please upload a screenshot with default settings. There were no change to the default font so it's unclear what happens to you.

**Comment by tomkoi** [comment]
> Please upload a screenshot with default settings. There were no change to the default font so it's unclear what happens to you.

Wish I could explain more from it, but this is the best.
I little bit afraid to update again

**Comment by ilya-fedin** [comment]
The problem is the report is use-less as-is and nothing could be done on it. On developer's machines, the text looks the same.

**Comment by Aokromes** [comment]
https://i.imgur.com/f2BX9Qr.png 4.16.8 on left, 4.16.9 on right, i see both the same.

**Comment by tomkoi** [comment]
Strange, so it’s can be releated to macOS and Hebrew chats (I from IL)
Will try to provide you some output later

Best regards

Tom Koifman
MTR/MTVR labs IT Administrator
Nvidia Israel
• [Office] +972(74)7129340<tel:+972747129340>  •  [Mobile] +972(54)8119335<tel:+972548119335>  • [E-Mail] ***@***.******@***.***>
[A green and black logo  Description automatically generated]

Report a Lab Services Issue<https://nvidia.service-now.com/esc?id=sc_cat_item&sys_id=1e07194e97c25150275ef7300153afaf>
Request for Lab Services<https://nvidia.service-now.com/esc?id=sc_cat_item&table=sc_cat_item&sys_id=55406dad97ec1910275ef7300153af6c>

***@***.***?anonymous&ep=signature>Book time to meet with ***@***.***?anonymous&ep=plink>

From: Aokromes ***@***.***>
Date: Wednesday, 24 April 2024 at 11:30
To: telegramdesktop/tdesktop ***@***.***>
Cc: Tom Koifman ***@***.***>, Author ***@***.***>
Subject: Re: [telegramdesktop/tdesktop] Version 4.16.9 broke app UI (font aspect) (Issue #27804)

https://i.imgur.com/f2BX9Qr.png 4.16.8 on left, 4.16.9 on right, i see both the same. (windows 10)

**Comment by TomCo2210** [comment]
Same here, hebrew font are broken and it looks really bad!
4.16.9 beta on Win11

**Comment by ilya-fedin** [comment]
Please, when you do such reports, upload screenshots of how it was, how it is and how it should be. Otherwise it's not actionable.

**Comment by TomCo2210** [comment]
edited my message with a picture added as example.

**Comment by ilya-fedin** [comment]
@TomCo2210 it looks just not that thick? Is this really a problem?

Please provide the log.txt file from the data directory.

**Comment by tomkoi** [comment]
> https://i.imgur.com/f2BX9Qr.png 4.16.8 on left, 4.16.9 on right, i see both the same. (windows 10)

Strange, so it’s can be releated to macOS and Hebrew chats (I from IL)

**Comment by tomkoi** [comment]
> Same here, Hebrew fonts are broken and it looks really bad! 4.16.9 beta on Win11 ![image](https://private-user-images.githubusercontent.com/17678722/325152560-f9d21789-d83f-4808-808d-b3b94421b563.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDk1NzksIm5iZiI6MTcxMzk0OTI3OSwicGF0aCI6Ii8xNzY3ODcyMi8zMjUxNTI1NjAtZjlkMjE3ODktZDgzZi00ODA4LTgwOGQtYjNiOTQ0MjFiNTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA5MDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyOGJjMWJiMTNkOTc1NmNmMTBhZTdhOGQ1MDI4MzY2ZjQzNWQ4YzJmMTE5NzIwZDY4MGU4MDZkMDM1MTkzYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.br_goKQyPF-7VG6xizOHqZhUJ01buJDt4gHhYR08Lxo) on the right 4.16.9, on the left 4.16.8

thanks Tom :)
this exactly what i saw too

**Comment by Aokromes** [comment]
> > [i.imgur.com/f2BX9Qr.png](https://i.imgur.com/f2BX9Qr.png) 4.16.8 on left, 4.16.9 on right, i see both the same. (windows 10)
> 
> Strange, so it’s can be releated to macOS and Hebrew chats (I from IL)



> > [i.imgur.com/f2BX9Qr.png](https://i.imgur.com/f2BX9Qr.png) 4.16.8 on left, 4.16.9 on right, i see both the same. (windows 10)
> 
> Strange, so it’s can be releated to macOS and Hebrew chats (I from IL)

no, windows have same bug with hebrew texts.

**Comment by ilya-fedin** [comment]
I wonder whether that's a real bug or folks just don't like the new look personally while it's actually ok. Hard to say without logs and a text example.

**Comment by ilya-fedin** [comment]
I checked the old and the new version of Open Sans font: the old one doesn't have support for Hebrew text while the new one does. This means, while you may not like it, this seems like and intended change done by the Open Sans font developers and since tdeksktop uses this font, you have three options:
1. Get used to that
2. Complain to https://github.com/googlefonts/opensans so they improve the Hebrew part. When they will do that, feel free to open an issue at tdesktop repo and I will update the font (or you folks can create a PR directly at https://github.com/desktop-app/lib_ui updating the ttf files)
3. Use the new option to set the font you like

**Comment by tomkoi** [comment]
> I checked the old and the new version of Open Sans font: the old one doesn't have support for Hebrew text while the new one does. This means, while you may not like it, this seems like an intended change done by the Open Sans font developers and since tdeksktop uses this font, you have three options:
> 
> 1. Get used to that
> 2. Complain to https://github.com/googlefonts/opensans so they improve the Hebrew part. When they will do that, feel free to open an issue at tdesktop repo and I will update the font (or you folks can create a PR directly at https://github.com/desktop-app/lib_ui updating the ttf files)
> 3. Use the new option to set the font you like

ok, i've open bug for dev font team:
https://github.com/googlefonts/opensans/issues/87
and used @TomCo2210 picture,
@ilya-fedin  can you please provide the old ttf file that the app used before the font change or i need to download from the font repo? then it's possible to put it's in telegram config manually? (on my comp)

**Comment by ilya-fedin** [comment]
> ok, i've open bug for dev font team:

I'm doubt they will treat it as a valid report. You need to tell them what you find broken in the hebrew glyphs and how they could improve it.

> can you please provide the old ttf file that the app used before the font change or i need to download from the font repo?

those ttfs won't be useful because they were patched for the font choosing logic which is no longer in place. Although, maybe going through open sans repo you will find an unpatched version of the good one?

**Comment by tomkoi** [comment]
> > ok, i've open bug for dev font team:
> 
> I'm doubt they will treat it as a valid report. You need to tell them what you find broken in the hebrew glyphs and how they could improve it.
> 

i not sure really how to explain the problem beside to see that there is really different 

> > can you please provide the old ttf file that the app used before the font change or i need to download from the font repo?
> 
> Those ttfs won't be useful because they were patched for the font choosing logic which is no longer in place. Although, maybe going through open sans repo you will find an unpatched version of the good one?

So how in version 4.16.8 it's still good? The app don't have some config folders/files to change manually if I want too?

**Comment by ilya-fedin** [comment]
> So how in version 4.16.8 it's still good?

Because it's old version which has that logic and those old patched fonts, no?

**Comment by m-sergiy26** [comment]
> https://i.imgur.com/f2BX9Qr.png 4.16.8 on left, 4.16.9 on right, i see both the same. (windows 10)

Offtop. How to change the left side menu of folders to white?

**Comment by ilya-fedin** [comment]
> How to change the left side menu of folders to white?

With a custom theme. I don't know what the theme keys for it are but people in https://t.me/TelegramDesktopTalk likely know.

**Comment by m-sergiy26** [comment]
> > How to change the left side menu of folders to white?
> 
> With a custom theme. I don't know what the theme keys for it are but people in https://t.me/TelegramDesktopTalk likely know.

thanks!

**Comment by ilya-fedin** [comment]
As far as I can see, the old version of Open Sans was 1.10 while the current version is 3.003.

**Comment by tomkoi** [comment]
> > So how in version 4.16.8 it's still good?
> 
> Because it's old version which has that logic and those old patched fonts, no?

i really new in all this so i assume you right :)

> As far as I can see, the old version of Open Sans was 1.10 while the current version is 3.003.

so there is no way to import manually the old tff file?

> Regarding macOS, I believe setting to "System font" should provide you a good result. As falling back to system Hebrew font is what was happening previously.
i tried also with system default font, still something not looks right or good as it's in 4.16.8

**Comment by ilya-fedin** [comment]
> so there is no way to import manually the old tff file?

I see lots of results in google when I search for "open sans 1.10" so you can download it, install by your system means and... perhaps get nothing because the embedded Open Sans will override the system installed one even if you choose Open Sans explicitly in settings.

**Comment by tomkoi** [comment]
> > so there is no way to import manually the old tff file?
> 
> I see lots of results in google when I search for "open sans 1.10" so you can download it, install by your system means and... perhaps get nothing because the embedded Open Sans will override the system installed one even if you choose Open Sans explicitly in settings.

it's bad :( but thank you for the trying at least :)
hope someday i will fixed somehow

**Comment by tomkoi** [comment]
> > i tried also with system default font, still something not looks right or good as it's in 4.16.8
> 
> If you were more specific, like uploading screenshots and marking what you don't like, maybe it would be possible to find what is not right.
you right, anyway 4.16.9 still beta so for now if it's working fine i not touch it

**Comment by nik1t0zz** [comment]
The old version of https://github.com/desktop-app/lib_ui uses "DAOpenSansRegular 1.10" instead of "Open Sans 3.003" that is used in the beta, so just switching out to the old fonts only partially fixes the issue.

Switching the font in TG settings to DAOpenSansRegular will not change the bold font to DAOpenSansSemiBold (or Bold), but will instead change it to some other default bold font, causing a jarring difference.

The new font is incredibly bad when it comes to Hebrew, as other people have pointed out, and my friend says so too, but it also changed the look of the "б" cyrillic B character, that now stands out it a horrible way.

I've sent "feedback" on Google Fonts, but I doubt they will change this character or improve Hebrew (it's been like 4 years now since those changes on their github).

There seems to be two ways of fixing this:
1. Switching back to previous OpenSans version (1.10);
3. Or fixing the behavior that picks Bold, Italics etc versions of fonts, so you could at least revert it correctly (and maybe shipping the old fonts too, so users won't need to download them).

**Comment by ilya-fedin** [comment]
> Switching the font in TG settings to DAOpenSansRegular will not change the bold font to DAOpenSansSemiBold (or Bold), but will instead change it to some other default bold font, causing a jarring difference.

That's what I meant by the old code made specially for those patched fonts being no more in place. You have to find unpatched Open Sans of version 1.10. It will be shadowed by the embedded Open Sans likely, though.

**Comment by nik1t0zz** [comment]
> You have to find unpatched Open Sans of version 1.10 in the Internet.

I can find them in the repo I linked to, specifically at the time of [this commit](https://github.com/desktop-app/lib_ui/tree/f4d28a30014e106e4ae0ff9bf860d1197ca8f214).

> It will be shadowed by the embedded Open Sans likely, though.

It kind of does, but does not - Regular (as in not bold and not italics) version gets switched correctly to the old version that you choose in the settings, but the bold variant gets taken from some other font, ignoring the DAOpenSansSemibold (that *is* present in the settings menu, but gets ignored for Bold font choice).

**Comment by ilya-fedin** [comment]
> I can find them in the repo I linked to, specifically at the time of [this commit](https://github.com/desktop-app/lib_ui/tree/f4d28a30014e106e4ae0ff9bf860d1197ca8f214).

No, I said **unpatched**. These font files are patched. They won't work without special logic.

**Comment by john-preston** [comment]
@ilya-fedin I hope I'll be able to revert OpenSans to 1.10, it should fix the Hebrew characters back to the previous version.
