### ISSUE TITLE
Add separate Thank emoji

### ISSUE THREAD

**Issue by KhaimovMR** [telegramdesktop/tdesktop#27805]
### Is your feature request related to a problem?

I'm cringing every time, when I need to thank somebody with emoji in Telegram.

Praying emoji is not suitable here. And it's not even a half-solution - suggestion to add another emoji pack where Praying emoji is swapped with another more suitable.

### Describe the solution you'd like

In Skype, for example - is one of the best thanking emoji - Man Bowing. This emoji will be sufficient. but the main change should be the adding the kind of the emoji - "thanks" that is inexistent now.

### Describe alternatives you've considered

There's no alternatives.

**Comment by ilya-fedin** [comment]
tdesktop doesn't create emojis, it uses existing emoji packs made by third parties which in turn based on Unicode

**Comment by ilya-fedin** [comment]
With premium you can use absolutely custom emoji sets, though

**Comment by KhaimovMR** [comment]
But every concrete emoji pack is created within the frame if the abstract emojies (a static list of supported emoji types, like smile, grin e.t.c) isn't it? And I've thought that these abstract emojies list are defined in some part of the Telegram. Am I wrong here?

**Comment by Aokromes** [comment]
custom emojies is premium feature.

**Comment by dima74** [comment]
I have telegram premium, how can I get "thank you" emoji? Any emoji pack recommendations?
