### ISSUE TITLE
Mini apps use wrong (US) keyboard layout (wayland)

### ISSUE THREAD

**Issue by danog** [telegramdesktop/tdesktop#27811]
### Steps to reproduce

1. Open mini app that requires the insertion of text in a text field (i.e. the email field for in the @wallet verification flow)
2. Start typing 

### Expected behaviour

The US keyboard layout is used instead of the correct keyboard layout (in my case IT), i.e. the @ appears when using shift+2 (US), not alt-gr+; (IT).

### Actual behaviour

The correct keyboard layout is used.

### Operating system

Arch linux, sway (wayland)

### Version of Telegram Desktop

4.16.9 beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#25126
