### ISSUE TITLE
Autostart desktop file has the executable bit set

### ISSUE THREAD

**Issue by heroin-moose** [telegramdesktop/tdesktop#27812]
### Steps to reproduce

1. Install telegram-desktop
2. Enable 'Launch Telegram when system starts'
3. Run 'ls ~/.config/autostart/org.telegram.desktop.desktop'

### Expected behaviour

The file should not have the executable bit set.

### Actual behaviour

The file has the executable bit set.

### Operating system

Arch Linux, no DE

### Version of Telegram Desktop

4.16.8

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
That is on purpose - some DEs don't launch .desktop files without executable bit
