### ISSUE TITLE
Custom font scaling issue

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#27814]
### Steps to reproduce

1. Update Telegram Desktop to 4.16.9.
2. Set UI scale <100%.
3. Go to "Chat settings" and choose custom font.
4. Restart app.
5. Get broken folders font alignment etc.

### Expected behaviour

All UI font elements should be smaller.

But nope.

75% scaling
Inter:
![TDesktop custom font scaling bug 75](https://github.com/telegramdesktop/tdesktop/assets/7080928/4dd677c1-4324-4af8-b6d1-a778ac3ee58d)
PT Sans:
![TDesktop custom font scaling bug 75 (2)](https://github.com/telegramdesktop/tdesktop/assets/7080928/3a911448-52b7-4d40-8133-d58f3c34727e)

### Actual behaviour

Seems app get forced minimal font size, therefore can't make it smaller. I have no problem with default Open Sans font scaling <100%.

With scaling <75% I get much more bugs: UI fonts elements refuse to get smaller, looks like they keep using minimal font size (8) instead of 6 or 7.

Users were waiting this feature for so long, but you should polish it and find the easiest solution.

### Operating system

Win 8.1 x64

### Version of Telegram Desktop

4.16.9

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I've allowed it to go 1px of font size more in attempt to mimic the original font size in beta version 4.16.10. Can you check if it became better there?

**Comment by Twilightssuperb** [comment]
Nothing has changed after update to 4.6.10. It's a bit weird. 😕

**Comment by ilya-fedin** [comment]
@Twilightssuperb what if you enable freetype in experimental settings?

**Comment by Twilightssuperb** [comment]
Still nothing has changed even after FreeType was enabled.

**Comment by ilya-fedin** [comment]
Maybe your fonts have wrong metrics in capHeight value of the OS/2 table?

**Comment by Twilightssuperb** [comment]
IDK, all TTFs were downloaded from official sources or Google Fonts. BTW, I use Mactype for better rendering. Maybe the reason is in it. But default Open Sans font doesn't conflict with Mactype...

**Comment by ilya-fedin** [comment]
Yeah, please try without mactype

**Comment by Twilightssuperb** [comment]
Still nothing has changed but fonts became more ugly without Mactype. 😅

**Comment by ilya-fedin** [comment]
> IDK, all TTFs were downloaded from official sources or Google Fonts. BTW, I use Mactype for better rendering. Maybe the reason is in it. But default Open Sans font doesn't conflict with Mactype...

It's not like fonts can't contain bugs. e.g. Open Sans was updated to the latest version 3.003 fron Google Fonts when this heta testing phase began and tdesktop got lots if bugs reports that it looks way worse (broken kerning, etc). Falling back to 1.10 helped.

**Comment by Twilightssuperb** [comment]
Well, I've chosen "System font" (but what is it? It doesn't look like Segoe UI), scaling 75% is better now. (Both Inter and PT Sans, e.g., seem bigger at previous screenshots.)
![TDesktop system font family choose 75](https://github.com/telegramdesktop/tdesktop/assets/7080928/13665900-e5bc-4edc-ab87-6e13f64c75d5)
![TDesktop Segoe UI choose 75](https://github.com/telegramdesktop/tdesktop/assets/7080928/7f50efdb-a8f2-481f-b80e-a0dd210eb452)
![TDesktop folders column scaling 75 system font choose](https://github.com/telegramdesktop/tdesktop/assets/7080928/ecde3c2a-418a-4660-b8d3-590aaaf2a847)

**Comment by ilya-fedin** [comment]
> but what is it?

Whatever Qt thinks is the system font. I believe it should be Segoe UI... But wouldn't be surprised if Windows returns some other font to Qt.

**Comment by john-preston** [comment]
@Twilightssuperb I've found the problem in size computation, this should get better in the upcoming release (I hope later today).

**Comment by john-preston** [comment]
Should be fine in 5.0.1?
