### ISSUE TITLE
[Feature Request] Handy shortcut icon to yourself

### ISSUE THREAD

**Issue by Akronix** [telegramdesktop/tdesktop#2781]
This is just an small enhancement but that I'd appreciate:
Since some time, Telegram Android version has a cloud icon in the menu representing a cloud chat with yourself.
It'd be useful to have something equivalent in telegram desktop, maybe in the top blue bar?

**Comment by john-preston** [comment]
@Akronix In the latest alpha version you have main menu where there is your userpic that leads to the chat with yourself.

You can download this version at the bottom of https://desktop.telegram.org/#alpha-version page.

**Comment by Akronix** [comment]
You're right @john-preston, I've alpha version on my desktop but I am currently on my laptop.
Thank you, works great!
