### ISSUE TITLE
Telegram loses context when closed to tray

### ISSUE THREAD

**Issue by heroin-moose** [telegramdesktop/tdesktop#27825]
### Steps to reproduce

1. Enable "Show tray icon"
2. Open a chat, scroll back
3. Close the window
4. Open new window

### Expected behaviour

The chat should be opened at the same position.

### Actual behaviour

No chats are opened, scrolling position lost.

### Operating system

Arch Linux, no DE

### Version of Telegram Desktop

4.16.8

### Installation source

Other (unofficial) source

**Comment by john-preston** [comment]
@heroin-moose This is intended, sorry. If you close the window, it is supposed to close the chat.

**Comment by MayaPosch** [comment]
I noticed this behaviour today after an update as well. Previously if you minimised to the tray and opened the Telegram window again, it'd be in the same chat, at the same location. Now the chat is closed, and the sidebar is also collapsed (apparently another regression?).

As many of us like to minimise the Telegram window to the tray, this new behaviour is very annoying as it forces us to waste space on the taskbar for no good reason.
