### ISSUE TITLE
destroy session then it will freeze

### ISSUE THREAD

**Issue by perayknox** [telegramdesktop/tdesktop#2782]
### Steps to reproduce
1. Login to the account that already logged in smartphone with Telegram Desktop Alpha
2. Destroy the session of telegram desktop alpha from your smartphone
3. See what is happen on the telegram desktop alpha.  

### Expected behaviour
I should see the login textboxes because I've destroyed the telegram desktop alpha's session

### Actual behaviour
I've seen the telegram desktop alpha as frozen. It's just waiting. No action. Exit/Open isn't resolving the problem. 

### Configuration
**Operating system:**
Ubuntu 16.04 
**Version of Telegram Desktop:**
Telegram Desktop 0.10.23 - alpha
### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by john-preston** [comment]
@perayknox It actually freezes? So you can't use it from that moment?

**Comment by perayknox** [comment]
In fact, the word frozen is not exactly the right word. It seems like waiting for the connection. I'm sorry to tell you the wrong way. I wrote it a little hurriedly. 

Everything looks normal, chats are normal, but I can't get new messages (also I can't send new message). Then I restart the Telegram Desktop Alpha and It seems like waiting for the connection. But nothing happening. Here is a video:

https://www.youtube.com/watch?v=LhOrZV11BwE&feature=youtu.be
