### ISSUE TITLE
Including chat information when exiting

### ISSUE THREAD

**Issue by NikitaNipple** [telegramdesktop/tdesktop#27822]
### Is your feature request related to a problem?

Yes, sometimes I accidentally delete chats due to carelessness, not realizing that the wrong chat is selected.

### Describe the solution you'd like

I suggest adding information about the chat (such as its name) when requesting confirmation to exit it. This will help me better identify which chat I'm about to delete/leave.

### Describe alternatives you've considered

Another option could be to consider adding an additional confirmation with a warning that the user is leaving a specific chat.

### Additional context

Sometimes messages can come in multiple chats simultaneously, which can lead to carelessness when selecting a chat to delete. Including chat information when exiting will help prevent accidental deletion of the wrong chat.

**Comment by 23rd** [comment]
If you wish, you can test a nightly debug build. It should be better now.
https://github.com/telegramdesktop/tdesktop/actions/runs/8868021581

**Comment by Aokromes** [comment]
> If you wish, you can test a nightly debug build. It should be better now. [telegramdesktop/tdesktop/actions/runs/8868021581](https://github.com/telegramdesktop/tdesktop/actions/runs/8868021581)

works fine :)
