### ISSUE TITLE
Option to disable startmenu shortcut creation for portable installations

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [telegramdesktop/tdesktop#27829]
It just creates a shortcut every time I run it.

Windows 10 x64
4.16.10 beta x64

**Comment by ilya-fedin** [comment]
Disable Windows notifications, they require registration in the system

**Comment by ilya-fedin** [comment]
@hp8wvvvgnj6asjm7 shortcut is a AppUserModelId handle. Registering in the system == registering AppUserModelId == creating a shortcut.
