### ISSUE TITLE
missing message counter when selecting "delete all from {user}" in all groups

### ISSUE THREAD

**Issue by krakovia-evm** [telegramdesktop/tdesktop#27821]
### Steps to reproduce

1. open a group where you are admin
2. right click on an user
3. select the flag "delete all from {user}"

### Expected behaviour

there was a message counter when you selected that checkbox.
It was so useful to quickly check how many messages a user had sent in a group 😭

### Actual behaviour

it should display the total user messages like the previous version

### Operating system

windows 11

### Version of Telegram Desktop

4.16.10 beta x64

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
If you wish, you can test a nightly debug build. It should be better now.
https://github.com/telegramdesktop/tdesktop/actions/runs/8867245617

**Comment by Aokromes** [comment]
> If you wish, you can test a nightly debug build. It should be better now. [telegramdesktop/tdesktop/actions/runs/8867245617](https://github.com/telegramdesktop/tdesktop/actions/runs/8867245617)

https://i.imgur.com/frVhcVj.png small bug, duplicate text.

**Comment by krakovia-evm** [comment]
> > If you wish, you can test a nightly debug build. It should be better now. [telegramdesktop/tdesktop/actions/runs/8867245617](https://github.com/telegramdesktop/tdesktop/actions/runs/8867245617)
> 
> https://i.imgur.com/frVhcVj.png small bug, duplicate text.

yep!
for the rest is good!

**Comment by 23rd** [comment]
Just in case.
https://github.com/telegramdesktop/tdesktop/actions/runs/8869166760

**Comment by Aokromes** [comment]
for 1 user is ok, can we have  total count and separate count with multiple users?

https://i.imgur.com/xUg9d7v.png :)

**Comment by Aokromes** [comment]
original bug report fixed on 5.0
