### ISSUE TITLE
Issue on building from source on macOs 12.7.4 with Xcode 14.2

### ISSUE THREAD

**Issue by bohlool** [telegramdesktop/tdesktop#27820]
### Steps to reproduce

1- Do required steps for building tdesktop on macOs.
2- After successful release build run the app.

### Expected behaviour

The app should run normally.

### Actual behaviour

The app crashes with this error:
no mapping for user data write
EXC_BAD_ACCESS (SIGSEGV)

### Operating system

macOs 12.7.4

### Version of Telegram Desktop

4.14.4

### Installation source

Other (unofficial) source

**Comment by john-preston** [comment]
@bohlool On arm macbook? This looks like an Xcode issue with too-large binary :(

**Comment by bohlool** [comment]
No, an intel mac book.

**Comment by john-preston** [comment]
@bohlool You can try building with that configuration command:

./configure -D DESKTOP_APP_MAC_ARCH=x86_64

and add all the api_id or any other arguments after that, maybe that way it'll launch?..

**Comment by bohlool** [comment]
@john-preston Thank you very much, It worked.
