### ISSUE TITLE
Ads platform improvement

### ISSUE THREAD

**Issue by danyhm** [telegramdesktop/tdesktop#27838]
### Is your feature request related to a problem?

Hello,

Currently, the Ads platform can display ads in public channels of advertisers' choice only.
the main interaction between users happens in groups. It would be awesome to be able to advertise in public groups as well.
also, more features for the ads campaign are required. for example:
1- link to an external URL
2- select audience by country, city , age, sex 
3- show ads in a proxy provider banner (this is especially useful for proxy providers where they get to show advertisers channels or ads in exchange for TONs directly from Telegram) 
4- the ability to choose channels and groups by hashtags or keywords would also be helpful in case the advertiser doesn't know about the specific group or channels (select channel or groups by activity type)

I hope the Telegram team considers this

### Describe the solution you'd like

NA

### Describe alternatives you've considered

NA

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
