### ISSUE TITLE
Problem displaying monospace font

### ISSUE THREAD

**Issue by Dimoka113** [telegramdesktop/tdesktop#27839]
### Steps to reproduce

1. Open any message that has a monospace font

### Expected behaviour

monospace font must be the same size as regular font
![4 16 10](https://github.com/telegramdesktop/tdesktop/assets/133571582/6b83715a-623d-469b-8b6c-8c58937d3e28)
(Example: Telegram Desktop version 4.16.10) (default font)

### Actual behaviour

monospace font stands out too much compared to regular font
![5 0 0](https://github.com/telegramdesktop/tdesktop/assets/133571582/90540942-39ca-4681-85ae-12852cda0dfc)
(Example: Telegram Desktop version 5.0.0) (default font)

### Operating system

Windows 10

### Version of Telegram Desktop

5.0.0

### Installation source

Static binary from official website

### Logs

```shell
-
```

**Comment by john-preston** [comment]
I guess regular letters ('v', 'u') are now closer in monospace and normal font than they were before :)

But maybe it should be reverted.

**Comment by w3lld0ne** [comment]
Yes, please revert monospace font back, it's ugly as hell now. Or at least make separate font family configuration for it.

**Comment by Aokromes** [comment]
5.0.1
