### ISSUE TITLE
fedora linux error install

### ISSUE THREAD

**Issue by YuriFontella** [telegramdesktop/tdesktop#27831]
### Steps to reproduce

rpm-ostree install telegram-desktop

### Expected behaviour

rpm-ostree install telegram-desktop

### Actual behaviour

error: Could not depsolve transaction; 1 problem detected:
 Problem: cannot install both qt6-qtbase-6.6.2-7.fc40.x86_64 from fedora and qt6-qtbase-6.7.0-3.fc40.x86_64 from @System
  - package telegram-desktop-4.16.8-1.fc40.x86_64 from rpmfusion-free requires qt6-qtbase(x86-64) = 6.6.2, but none of the providers can be installed
  - package telegram-desktop-4.16.8-1.fc40.x86_64 from rpmfusion-free requires libQt6Core.so.6(Qt_6.6_PRIVATE_API)(64bit), but none of the providers can be installed
  - conflicting requests

### Operating system

fedora linux 40 atomic

### Version of Telegram Desktop

4.16.8

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
This bugtracker has nothing to do with the package you installed. You can get official version from https://desktop.telegram.org.
