### ISSUE TITLE
premium subscription issue

### ISSUE THREAD

**Issue by lokyse** [telegramdesktop/tdesktop#27836]
### Steps to reproduce

 I have subscribed premium per month by Premium Bot. my account is @oeegors.

### Expected behaviour

1 Why Premium subscription deducts 288.12 RMB from me every month.
2 In April, I have executed the 'stop' command to cancel the subscription. and bot mentioned, 'Recurring payments have been stopped, so you won't be charged again after the current period expires.' Why subscription fee was automatically paid in May.

### Actual behaviour

1 Cancel my subscription 
2 Refund my money

### Operating system

Macos Monterey 12.7.4

### Version of Telegram Desktop

10.12.2.262594 table

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
your issue aint a client bug very likely, i suggest you to use in app ask a question.
