### ISSUE TITLE
Font rendering is not smooth on 5.0 x84 Desktop version

### ISSUE THREAD

**Issue by AlexSnowLeo** [telegramdesktop/tdesktop#27844]
### Steps to reproduce

1. Install 5.0 x64 version on Windows 11 23H2 (Build 22631.3527)
2. Run telegram
3. And the font rendering not smoothing even on the start screen. The same thing happens when you launch a new application:
![image](https://github.com/telegramdesktop/tdesktop/assets/1458178/760d9b5e-9bd2-4d57-bdd5-83b5c1a9fd24)
![image](https://github.com/telegramdesktop/tdesktop/assets/1458178/25786995-d1ab-4871-b16f-fb814d7abb3d)
![image](https://github.com/telegramdesktop/tdesktop/assets/1458178/7e9c292f-ea01-420a-ad6e-32e38b43f29b)

### Expected behaviour

Smooth font just on prev versions

### Actual behaviour

Font not smoothing

### Operating system

Windows 11 23H2 (Build 22631.3527)

### Version of Telegram Desktop

5.0 x64 Desktop

### Installation source

Static binary from official website

**Comment by AlexSnowLeo** [comment]
It turned out to be fixed only when you turn on this setting:
![image](https://github.com/telegramdesktop/tdesktop/assets/1458178/331c8a98-b453-4cad-9e67-c868ec15db5d)

**Comment by Aokromes** [comment]
try https://www.fosshub.com/qBittorrent-old.html?dwl=qbittorrent_4.5.5_lt20_qt5_x64_setup.exe

**Comment by AlexSnowLeo** [comment]
> try https://www.fosshub.com/qBittorrent-old.html?dwl=qbittorrent_4.5.5_lt20_qt5_x64_setup.exe

I have qBittorrent version 4.6.4 installed, but how can this be related to the telegram client? 

I did not touch the Windows system settings, and tried to change them, but there are no font rendering settings for applications separately.

**Comment by Aokromes** [comment]
> > try [fosshub.com/qBittorrent-old.html?dwl=qbittorrent_4.5.5_lt20_qt5_x64_setup.exe](https://www.fosshub.com/qBittorrent-old.html?dwl=qbittorrent_4.5.5_lt20_qt5_x64_setup.exe)
> 
> I have qBittorrent version 4.6.4 installed, but how can this be related to the telegram client?
> 
> I did not touch the Windows system settings, and tried to change them, but there are no font rendering settings for applications separately.

qbittorrent 4.6.4 uses qt 6, we are asking you to test if on qbittorrent 4.5.5 (qt 5) the same bug exists

**Comment by AlexSnowLeo** [comment]
> qbittorrent 4.6.4 uses qt 6, we are asking you to test if on qbittorrent 4.5.5 (qt 5) the same bug exists

There is no such problem in qBittorrent 4.5.5:
![image](https://github.com/telegramdesktop/tdesktop/assets/1458178/0cf41577-3659-4290-a830-d8f50e68ec33)

Moreover, I turned off the "FreeType font engine" setting and everything is displayed normally. But Telegram has been updated to version 5.0.1
