### ISSUE TITLE
separate counter of messages to be deleted and total amount of multiple messages when deleting from multiple users

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#27845]
### Is your feature request related to a problem?

atm when wanting to delete the messages of multiple users you only get the message of you go to delete 2 messages.

https://i.imgur.com/21eOyUH.png

### Describe the solution you'd like

imho it's better to detail how much total messages and how much messages of each user you go to delete.

https://i.imgur.com/3dH9X4c.png

### Describe alternatives you've considered

none

**Comment by 23rd** [comment]
Please check the v5.8.4 beta.

**Comment by Aokromes** [comment]
cool!
