### ISSUE TITLE
Media Viewer not showing up on Gnome Wayland

### ISSUE THREAD

**Issue by ljuzig** [telegramdesktop/tdesktop#27847]
### Steps to reproduce

When you click over an image in a chat, it does not shows anything, and do not let you close the "invisible window" it created, preventing Telegram from quitting. You have to manually kill the process.

Running with `QT_QPA_PLATFORM=xcb` fixes the media viewer problem but introduces other problems, so it's not really usable on my system.

Everything was working pretty fine a while back, cannot tell the exact version, it broke a few months ago.

### Expected behaviour

Opening a modal popup showing the image.

### Actual behaviour

Nothing apparently, but it creates an empty invisible window that you can see from the All Windows menu in app's icon context menu. You can't close it from there.

![image](https://github.com/telegramdesktop/tdesktop/assets/11982322/03a5667a-913e-40a5-9cc4-9d5c5873eab1)

### Operating system

NixOS 23.11, GNOME 45.5 on Wayland

### Version of Telegram Desktop

4.16.8

### Installation source

Other (unofficial) source: [Official Nixpkgs repo](https://search.nixos.org/packages?channel=23.11&type=packages&query=telegram-desktop)

**Comment by ilya-fedin** [comment]
> Other (unofficial) source: [Official Nixpkgs repo](https://search.nixos.org/packages?channel=23.11&type=packages&query=telegram-desktop)

Please check on official binary or report to your package maintainer
