### ISSUE TITLE
Compose Key not working

### ISSUE THREAD

**Issue by vitaly-zdanevich** [telegramdesktop/tdesktop#27842]
Compose Key (right control) works for me in Firefox, SpaceFM, but not in Telegram. In Firefox on right controll press I see a dot symbol - but nothing in Telegram

### Operating system

Gentoo Linux

### Version of Telegram Desktop

4.15.0-r2

### Installation source

https://packages.gentoo.org/packages/net-im/telegram-desktop

[2024-may-03fri--01-55-53.webm](https://github.com/telegramdesktop/tdesktop/assets/3514015/cfc34a5d-6229-4ea1-a93f-76a8ab98bf6c)

**Comment by ilya-fedin** [comment]
> https://packages.gentoo.org/packages/net-im/telegram-desktop

Please reproduce with official binary or report to your package maintainer instead

**Comment by ilya-fedin** [comment]
and, ideally, try with other Qt applications - Telegram doesn't manage such things as compose key, this is done by the toolkit

**Comment by vitaly-zdanevich** [comment]
I tried in another QT app (https://nulloy.com/) - the same nothing. So, looks like something with QT?

**Comment by ilya-fedin** [comment]
yes

**Comment by vitaly-zdanevich** [comment]
Maybe do you know haw can I fix it on my side?

**Comment by ilya-fedin** [comment]
no, I don't even use compose keys
