### ISSUE TITLE
Add message translation

### ISSUE THREAD

**Issue by Giuseppe7887** [telegramdesktop/tdesktop#27854]
### Is your feature request related to a problem?

This feature Is not related to a real problem with the app

### Describe the solution you'd like

When i read message around groups, sometime i find messages in Russian or some word in english that i don't undersand i think it's a good thing to add in-app translation, to follow the freedom of read whatever i want and the possibility to let undersand the whole world what i want to say.

### Describe alternatives you've considered

Automatic translation of the whole chat with i18n

**Comment by Aokromes** [comment]
go sttings language https://i.imgur.com/LQsJxjA.png

**Comment by Giuseppe7887** [comment]
thanks, why It Is not default
