### ISSUE TITLE
Search field is focused when starting with "launch on startup" and "launch minimized" enabled

### ISSUE THREAD

**Issue by daniels1989** [telegramdesktop/tdesktop#27853]
### Steps to reproduce

1. Enable "Show tray icon", "Launch Telegram when system starts" and "Launch minimized"
2. Quit Telegram completely
3. Launch Telegram with the -autostart option, as provided in the startup section of the start menu. Or just reboot the system.
4. Open Telegram from the system tray

### Expected behaviour

Telegram should open with the list of active chats, as it's always done.

### Actual behaviour

The search field is focused and awaiting input, which means all active chats are hidden. Have to first press esc, or the x in the search field. This started with the new 5.x versions

### Operating system

Windows 10 x64 22H2

### Version of Telegram Desktop

5.0.1

### Installation source

Static binary from official website

**Comment by Henry-ZHR** [comment]
Is the fix valid for official static binary only? I am using `telegram-desktop` v5.1.5 from Arch Linux official repo, and I am still faced with this issue.

**Comment by IlyaIndigo** [comment]
In openSUSE Tumbleweed in version 5.1.5, the same problem.
