### ISSUE TITLE
Telegram desktop 5.0.1 black screen while opening images

### ISSUE THREAD

**Issue by aranelofdoriath** [telegramdesktop/tdesktop#27857]
### Steps to reproduce

0. Radeon RX 570 
1. Open any image in TG chat and screen become black, then restores. Move your mouse or press any button and it becomes black again.

### Expected behaviour

Open image.

### Actual behaviour

Got black screen.

### Operating system

Windows 10 Pro 19043.2364

### Version of Telegram Desktop

Telegram Desktop 5.0.1 x64

### Installation source

Static binary from official website

### Logs

```shell
[2024.05.05 15:12:20] RPC Error: request 69 got fail with code 400, error PEER_ID_INVALID
[2024.05.05 15:12:24] RPC Error: request 86 got fail with code 400, error PEER_ID_INVALID
```

**Comment by Aokromes** [comment]
cant reproduce with nvidia gfx.
