### ISSUE TITLE
While using 'Voice access' Show numbers command, No numbers are appearing on the controls appearing in Telegram App.

### ISSUE THREAD

**Issue by msftedad** [telegramdesktop/tdesktop#27868]
### Steps to reproduce

1. Open Telegram App in Desktop.
2. Open URL: [Telegram: Contact @SCTejTestbot](https://t.me/SCTejTestbot) on edge.
3. SCTestbot home screen will appear.
4. Go to Settings --> Accessibility --> Speech --> Turn on voice access.
5. Say command 'Show numbers'.
6. Observe an issue that While using 'Voice access' Show numbers command to, No numbers are appearing on the controls appearing in Telegram App.

### Expected behaviour

While using 'Voice access' Show numbers command, numbers should be appearing on the controls appearing in Telegram App.

### Actual behaviour

While using 'Voice access' Show numbers command, No numbers are appearing on the controls appearing in Telegram App.

https://github.com/telegramdesktop/tdesktop/assets/93735775/548b3426-4d41-4bf8-a27c-b09795b19dc7

### Operating system

22H2 (22621.1105)

### Version of Telegram Desktop

Telegram (4.16.4)

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/476
