### ISSUE TITLE
'See more on Bing' control is not accessible using keyboard.

### ISSUE THREAD

**Issue by msftedad** [telegramdesktop/tdesktop#27867]
### Steps to reproduce

1. Open Telegram App in Desktop.
2. Open URL: [Telegram: Contact @SCTejTestbot](https://t.me/SCTejTestbot) on edge.
3. SCTestbot home screen will appear.
4. Activate on start button.
5. Navigate to edit filed enter 'accessibility' query and invoke it.
6. Navigate to See more on Bing control on response section.
7. Observe an issue that 'See more on Bing' control is not accessible using keyboard.

### Expected behaviour

'See more on Bing' control should be accessible using keyboard. Focus should land on the control and the control should be actionable using Enter/Spce key.

### Actual behaviour

 'See more on Bing' control is not accessible using keyboard.

https://github.com/telegramdesktop/tdesktop/assets/93735775/1ac78243-79d5-4b85-8390-5c8e6d40e6c5

### Operating system

22H2 (22621.1105)

### Version of Telegram Desktop

Telegram (4.16.4)

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/476
https://github.com/telegramdesktop/tdesktop/issues/2109
