### ISSUE TITLE
Quick reactions controls appearing on responses are not accessible using keyboard.

### ISSUE THREAD

**Issue by msftedad** [telegramdesktop/tdesktop#27865]
### Steps to reproduce

1. Open Telegram App in Desktop.
2. Open URL: [Telegram: Contact @SCTejTestbot](https://t.me/SCTejTestbot) on edge.
3. SCTestbot home screen will appear.
4. Activate on start button.
5. Navigate to edit filed enter 'accessibility' query and invoke it.
6. Navigate to Quick reactions controls on response section.
7. Observe an issue that Quick reactions controls is not accessible using keyboard.

### Expected behaviour

Quick reactions controls appearing on responses should be accessible using keyboard.

### Actual behaviour

Quick reactions controls appearing on responses are not accessible using keyboard.

https://github.com/telegramdesktop/tdesktop/assets/93735775/611b3fd8-b0a8-4724-949d-d48c5d014573

### Operating system

22H2 (22621.1105)

### Version of Telegram Desktop

Telegram (4.16.4)

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/476
https://github.com/telegramdesktop/tdesktop/issues/2109
