### ISSUE TITLE
Failed To Compile in Windows 10

### ISSUE THREAD

**Issue by ghost1372** [telegramdesktop/tdesktop#2786]
### Expected behaviour
hi i want to compile tdesktop in windows 10 i do instruction [here ](https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-msvc.md)but i have problem.
when i write below command 
`
git clone https://github.com/openssl/openssl.git
cd openssl
git checkout OpenSSL_1_0_1-stable
perl Configure VC-WIN32 --prefix=D:\TBuild\Libraries\openssl\Release
ms\do_ms
nmake -f ms\nt.mak
`
in last line (nmake command) i get error : 
`
D:\TBuild\Libraries\openssl>nmake -f ms\nt.mak

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Building OpenSSL
        perl util/copy.pl ".\crypto\buildinf.h" "tmp32\buildinf.h"
Copying: ./crypto/buildinf.h to tmp32/buildinf.h
        perl util/copy.pl ".\crypto\opensslconf.h" "inc32\openssl\opensslconf.h"
Copying: ./crypto/opensslconf.h to inc32/openssl/opensslconf.h
        cl /Fotmp32\cryptlib.obj  -Iinc32 -Itmp32 /MT /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_DYNAMIC_ENGINE /Zl /Zi /Fdtmp32/lib -c .\crypto\cryptlib.c
'cl' is not recognized as an internal or external command,
operable program or batch file.
NMAKE : fatal error U1077: 'cl' : return code '0x1'
Stop.
`
### Configuration
**Operating system:Windows 10   /  Visual Studio 2015**

**Version of Telegram Desktop:Latest Version**

**Comment by john-preston** [comment]
@ghost1372 Are you trying this from VS2015 x86 Native Tools Command Prompt?

**Comment by ghost1372** [comment]
i use Developer Command Prompt, Is that wrong?
i cant find exactly VS2015 x86 Native Tools Command Prompt.
![1](https://cloud.githubusercontent.com/assets/9213496/21710290/f215806e-d3fc-11e6-9d88-3eb0b53b51af.png)

**Comment by ghost1372** [comment]
problem Solved.
Visual C++ Tools not installed.(so i installed it and problem fixed)
