### ISSUE TITLE
'Menu', 'Stickers' and 'Suggestion' controls are not accessible using keyboard.

### ISSUE THREAD

**Issue by msftedad** [telegramdesktop/tdesktop#27874]
### Steps to reproduce

1. Open Telegram App in Desktop.
2. Open URL: [Telegram: Contact @SCTejTestbot](https://t.me/SCTejTestbot) on edge.
3. SCTestbot home screen will appear.
4. Activate on start button.
5. Navigate to Stickers control in edit field using tab key.
6. Observe an issue that 'Menu', 'Stickers' and 'Suggestion' controls are not accessible using keyboard.

### Expected behaviour

'Menu', 'Stickers' and 'Suggestion' controls should be accessible using keyboard. Focus should land on these controls and they should be actionable using Enter/Space key.

### Actual behaviour

'Menu', 'Stickers' and 'Suggestion' controls are not accessible using keyboard.

https://github.com/telegramdesktop/tdesktop/assets/93735775/5bb3eb5d-35cb-4cab-8353-4c85ee1d33ea

### Operating system

22H2 (22621.1105)

### Version of Telegram Desktop

Telegram (4.16.4)

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/476
https://github.com/telegramdesktop/tdesktop/issues/2109
