### ISSUE TITLE
Luminosity contrast ratio for text present in Chat header is less than 4.5:1.

### ISSUE THREAD

**Issue by msftedad** [telegramdesktop/tdesktop#27871]
### Steps to reproduce

1. Open Telegram App in Desktop.
2. Open URL: [Telegram: Contact @SCTejTestbot](https://t.me/SCTejTestbot) on edge.
3. SCTestbot home screen will appear.
7. Open Color Contrast Analyser and check for contrast ratio for the control.
8. Observe an issue that luminosity contrast ratio for text present in Chat header is less than 4.5:1.

### Expected behaviour

Contrast ratio for the text must be greater than or equal to 4.5:1.

### Actual behaviour

Luminosity contrast ratio for text present in Chat header is less than 4.5:1.
<img width="613" alt="Luminosity contrast ratio for text present in Chat header is less" src="https://github.com/telegramdesktop/tdesktop/assets/93735775/aa49e88a-d9f3-40e1-a7fa-2006b22c08c7">

### Operating system

22H2 (22621.1105)

### Version of Telegram Desktop

Telegram (4.16.4)

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/476
