### ISSUE TITLE
Luminosity contrast ratio for text present in 'Menu' control is less than 4.5:1.

### ISSUE THREAD

**Issue by msftedad** [telegramdesktop/tdesktop#27879]
### Steps to reproduce

1. Open Telegram App in Desktop.
2. Open URL: [Telegram: Contact @SCTejTestbot](https://t.me/SCTejTestbot) on edge.
3. SCTestbot home screen will appear.
4. Navigate to start control and activate by using enter key.
5. Navigate to 'Menu' control using tab key.
6. Popup will appear.
7. Open Color Contrast Analyser and check for contrast ratio for the control.
8. Observe an issue that luminosity contrast ratio for 'Menu' control is less than 4.5:1.

### Expected behaviour

Contrast ratio for the text must be greater than or equal to 4.5:1.

### Actual behaviour

Luminosity contrast ratio for text present in 'Menu' control is less than 4.5:1.
<img width="777" alt="Luminosity contrast ratio for 'Menu' control is less" src="https://github.com/telegramdesktop/tdesktop/assets/93735775/5703c570-c86b-4a19-a73b-26b38c4ab770">

### Operating system

22H2 (22621.1105)

### Version of Telegram Desktop

Telegram (4.16.4)

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/476
