### ISSUE TITLE
Keyboard focus indicator does not retain back on the 'More options' button after closing the pop up with 'Esc' key.

### ISSUE THREAD

**Issue by msftedad** [telegramdesktop/tdesktop#27876]
### Steps to reproduce

1. Open Telegram App in Desktop.
2. Open URL: [Telegram: Contact @SCTejTestbot](https://t.me/SCTejTestbot) on edge.
3. SCTestbot home screen will appear.
4. Navigate to 'More options' button and invoke it, references appear, navigate each and every control.
5. Try to close the pop up using esc key.
6. Verify that Keyboard focus indicator does not retain back on the 'More options' button after closing the pop up with 'Esc' key.

### Expected behaviour

Keyboard focus indicator should retain back on the 'More options' button after closing thepop up with 'Esc' key. This ensures that users can continue navigating the interface seamlessly without losing their place or having to manually reposition the focus. The 'More options' button should visually indicate that it has regained keyboard focus.

### Actual behaviour

Keyboard focus indicator does not retain back on the 'More options' button after closing the pop up with 'Esc' key.

https://github.com/telegramdesktop/tdesktop/assets/93735775/f697bf0c-6676-4a7c-8f6a-be7662e1d577

### Operating system

22H2 (22621.1105)

### Version of Telegram Desktop

Telegram (4.16.4)

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/476
https://github.com/telegramdesktop/tdesktop/issues/2109
