### ISSUE TITLE
Follow system theme

### ISSUE THREAD

**Issue by PanderMusubi** [telegramdesktop/tdesktop#27888]
### Is your feature request related to a problem?

Other software, including direct messaging desktop applications such as Signal and WhatsApp, have an option for the theme to follow the system theme. That is the theme set by the desktop environment. In this way the user can switch theme for all applications in one place.

### Describe the solution you'd like

That Telegram Desktop application has an option (preferably the default) to follow the system theme (GNOME / Pop!_OS / COSMIC / KDE). If a theme needs to be mapped, map Day on Light and Tinted on Dark.

![Screenshot from 2024-05-07 16-26-26](https://github.com/telegramdesktop/tdesktop/assets/198964/a28063df-2de8-445c-9c83-c34830f4d860)

![Screenshot from 2024-05-07 16-26-19](https://github.com/telegramdesktop/tdesktop/assets/198964/ef617be6-4bbe-4cfe-bd8f-6744b6a161e4)

### Describe alternatives you've considered

Changing the theme manually, but is a low of work if you need to change the theme a few times per day when switching physical working location (indoor/outdoor e.g.)

### Additional context

Implementing this would make Telegram Desktop more complaint to what is industry standard regarding this and save the user a lot of unneed actions.

**Comment by ilya-fedin** [comment]
There is automatic night mode which you can enable in Settings -> Chat Settings (needs support for your system in Qt though).

Regarding full system theme support, this is not possible without a full rewrite, sorry.

**Comment by PanderMusubi** [comment]
The automatic night mode is what I was looking for.

When switching in gnome-settings, like the screenshot above, Telegram indeed changes to and from night mode.

However, version Telegram Desktop 4.16.8 it does not switch to and from night mode when the appearance is changed via the command line. Other apps do switch after running these commands. I'm using:

     alias light='gsettings set org.gnome.desktop.interface gtk-theme Pop'
    alias dark='gsettings set org.gnome.desktop.interface gtk-theme Pop-dark'

Can automatic night mode also pick upchanges made like this via the command line?

**Comment by ilya-fedin** [comment]
@PanderMusubi no, you're changing gtk theme with those commands, not the light/dark mode, while tdesktop written not in gtk. You should find commands to switch between light and dark mode like what you do in the UI.

**Comment by PanderMusubi** [comment]
Thanks, this led me to:

    #!/usr/bin/env sh
    
    if test "$(gsettings get org.gnome.desktop.interface color-scheme)" = "'prefer-light'"; then
      gsettings set org.gnome.desktop.interface color-scheme prefer-dark
      gsettings set org.gnome.desktop.interface gtk-theme 'Pop-dark'
    else
      gsettings set org.gnome.desktop.interface color-scheme prefer-light
      gsettings set org.gnome.desktop.interface gtk-theme 'Pop'
    fi

And now Telegram Desktop follow like via the UI.
