### ISSUE TITLE
Allow using spotify deeplinks

### ISSUE THREAD

**Issue by ko-vasilev** [telegramdesktop/tdesktop#27882]
### Is your feature request related to a problem?

When creating links in telegram, I want to be able to use spotify deeplinks (ex: `spotify://track/7I4ibsZgwuf46g0xHuTC8s`), right now it doesn't let me use this link and just changes the input color to red indicating a validation error.
Also, this link does not get parsed if I type it in a text message.
![image](https://github.com/telegramdesktop/tdesktop/assets/5964618/a1eeb438-7582-4e78-bc10-24ffd1467fca)

### Describe the solution you'd like

Allow using spotify deeplinks (would be great if this was a config file in the source code that can easily be edited in future if needed)

### Describe alternatives you've considered

The only alternative I know is using 3rd party services that redirect user to the spotify deeplink, but they are usually paid services.

### Additional context

Not sure if this issue is related to a specific client (because it also doesn't work in android/ios apps), or if this is controlled on the server side. Please let me know if this feature request should be reported in another repository.

**Comment by ilya-fedin** [comment]
This sounds like a platform-wide issue. Please use New issue -> Platform-wide issue for such issues.

**Comment by ko-vasilev** [comment]
@ilya-fedin thanks for the suggestion!
If anyone else cares, here is a link to the feature request for the platform: https://bugs.telegram.org/c/39717
