### ISSUE TITLE
CTRL+F from topics list opens global search

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#27887]
### Steps to reproduce

1. open a group chat with topics enabled (topics list view, not messages view)
2. use CTRL+F

### Expected behaviour

tdesktop searches within the group

### Actual behaviour

The global search is opened instead, *behind* the topics list view. Using the "search" option from the three dots menu works correctly

### Operating system

Windows 10

### Version of Telegram Desktop

5.0.1

### Installation source

Static binary from official website

**Comment by saddedmoroz** [comment]
I reproduce steps and get expected behaviour.
Telegram Desktop 5.2.3 x64 portable, GitHub [release](https://github.com/telegramdesktop/tdesktop/releases/tag/v5.2.3)
Windows 10 v1909

**Comment by RememberTheAir** [comment]
yes, it has been fixed, thanks
