### ISSUE TITLE
Upload Speed Throttler

### ISSUE THREAD

**Issue by slumbergod** [telegramdesktop/tdesktop#27891]
### Steps to reproduce

Upload a large file

### Expected behaviour

The file upoads but should not affect the bandwidth for others on the network

### Actual behaviour

In the last few updates, Telegram seems to have increased the upload speed. This is very welcome but unfortunately the linux desktop app is using all of the available upload bandwidth. No one else on my home network is able to use the internet properly when I am uploading a large file.

A simple throttle system would be welcome.

In fact, the recent versions of Telegram Desktop are slowing my computer down when I queue a bunch of large files. Are the files in the queue being loaded into memory instead of being read from disk? Not everyone can afford a new shiny computer with 16Gb of RAM.

### Operating system

Manjaro Linux / XFCE4 (latest rolling release)

### Version of Telegram Desktop

5.01

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
can't reproduce myself on windows with 1 gbps connection.
