### ISSUE TITLE
"Also delete for <User>" is no longer remembered in latest versions

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#27898]
### Steps to reproduce

1. Detele a chat with user with "Also delete for <User>" selected.
2. Try to delete another chat.
3. "Also delete for <User>" state is not remembered.

### Expected behaviour

Telegram for Desktop should remember this option, in previous versions it's correctly remembered.

https://github.com/telegramdesktop/tdesktop/issues/25442#issuecomment-1352830709
https://github.com/telegramdesktop/tdesktop/issues/3334

### Actual behaviour

This option is not remembered.

### Operating system

Windows 11

### Version of Telegram Desktop

5.0.1

### Installation source

Static binary from official website

**Comment by soredake** [comment]
I have reproduced this in Windows 11 vm and real 11 system.

**Comment by john-preston** [comment]
@Aokromes he was speaking about deleting a chat and you were showing a box for deleting a message.

@soredake IIRK the remembering was done only for deleting of messages, not the entire chats. You can always re-delete the chat with a user with the option being enabled after you've deleted it only for you, though, and it should work, I think.

**Comment by soredake** [comment]
Working again.
