### ISSUE TITLE
t.me links are not supported

### ISSUE THREAD

**Issue by nsychev** [telegramdesktop/tdesktop#2789]
### Steps to reproduce
1. Open any chat
2. Send message with link to t.me, for example: "https://t.me/storebot"
3. Click on this link

### Expected behaviour
App should open chat with @storebot without web browser

### Actual behaviour
App opens this link in my default browser and I have to click "Send message" button

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 0.10.20

**Comment by john-preston** [comment]
@nsychev Please try the latest alpha version from the bottom of https://desktop.telegram.org/#alpha-version page. Is it working there?

**Comment by nsychev** [comment]
I downloaded version 0.10.25 (Windows installer), but it haven't loaded my messages in 5 minutes. I can't test it

![image](https://cloud.githubusercontent.com/assets/11004619/21728051/fc069932-d465-11e6-87e2-ceecf0f95acd.png)

**Comment by nsychev** [comment]
Yes, it works in 0.10.25
