### ISSUE TITLE
Resizable input area 

### ISSUE THREAD

**Issue by admzzz** [telegramdesktop/tdesktop#2790]
Can you make in linux version of tdesktop resizable input area & add font's choosing (including choosing of the font's size) in the Settings section, please?
It will be a great thing for the peoples with disabilities.

**Comment by stek29** [comment]
> fonts choosing

#90

> resizable input area

What do you mean?

**Comment by admzzz** [comment]
I was speaking about the possibility for the users with disabilities to:
1) choose font's face and size (larger than the default one) for the typing text and for already sent messages in tdesktop;
2)  enlarge input text area, according to the user's requirements, so that it will contain more line's of text in enlarged font.

**Comment by admzzz** [comment]
Wonna add:
current possibility of scaling the whole interface of tdesktop does not allow to see more than 2 -2.5 lines of currently typing text, so I'm asking about new and different user's conveniences.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2060
