### ISSUE TITLE
Enable Auto-Scroll Feature for Telegram Desktop's Separate Windows

### ISSUE THREAD

**Issue by dukesaeed** [telegramdesktop/tdesktop#27906]
### Is your feature request related to a problem?

Currently, Telegram Desktop offers the convenient "open in new window" feature. However, to enhance productivity, I propose the implementation of an **auto-scroll feature for chats opened in separate windows**.

### Describe the solution you'd like

This feature would enable users to effortlessly keep up with incoming messages, especially news feeds, while working on other screens. By automatically scrolling through the chat content, users can stay updated without manually interacting with the window, optimizing their multitasking experience.

Integrating this auto-scroll functionality would streamline the user experience, making Telegram Desktop an even more versatile tool for seamless communication and information consumption.

### Describe alternatives you've considered

No Alternative

**Comment by ilya-fedin** [comment]
You can enable it in experimental settings
