### ISSUE TITLE
Continues to run in background on platform without tray support

### ISSUE THREAD

**Issue by EdJoPaTo** [telegramdesktop/tdesktop#27900]
### Steps to reproduce

Start Telegram Desktop, close it and the process is still running in background, being one of the processes with the most RAM consumption.

### Expected behaviour

There should be a way to configure running in background.

On my Arch Gnome System there is no tray icon, so there is no option in the settings to disable the tray icon like suggested in #27190.

### Actual behaviour

telegram-desktop stays in the background and continues to eat up RAM.

`killall telegram-desktop` works :sparkles: 

### Operating system

Arch Linux, rolling release, Gnome

### Version of Telegram Desktop

5.0.1 (--version would be neat)

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Do what is suggested in https://github.com/telegramdesktop/tdesktop/issues/27190#issuecomment-1840780300 (the gsettings command)

**Comment by Aokromes** [comment]
for linux:
Set sane man's titlebar settings and it won't stay in background
gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'

**Comment by EdJoPaTo** [comment]
does this mean "wont fix" or "no official support for non gnome and other desktops without tray support"?

**Comment by ilya-fedin** [comment]
@EdJoPaTo this means you have to set up your system

**Comment by EdJoPaTo** [comment]
Sadly I prefer a native Gnome system.

**Comment by ilya-fedin** [comment]
@EdJoPaTo well, other users of GNOME systems have convinced that the native behavior is to continue to run in background like done on macOS as you can still quit application by right clicking application icon and choosing quit.

**Comment by ilya-fedin** [comment]
And, well, such behavior feels the sanest if the system doesn't allow applications to minimize and doesn't have tray icons. I.e. there's just no other way to run in background. Yet, you still can quit application via application menu (or how that is called on GNOME?) and some users even claimed there's some list of background apps where you can quit, too.

**Comment by EdJoPaTo** [comment]
Either I use an application, then I want to see it. Or I don't need it, then I don't want to see it, and it shouldn't be running. Why should it be running? I have notifications disabled anyway so it won't do anything other than eating up RAM.
Why would I need a minimize button when I quit an application anyway? And why would I need a maximize button when I can either use my keyboard or drag the window? And I prefer the approach of Gnome not to have tray icons being a mess in your view all them time. So I think the current state of my system is good. Sadly telegram-desktop doesn't fit this need. Would be better when it wouldn't use that much RAM, but it doesn't do that either.

> Yet, you still can quit application via application menu (or how that is called on GNOME?)

Close isn't quitting the application.

> this means you have to set up your system

Should I set up a timer with `killall telegram-desktop` every 10 min? Might be somewhat annoying but better than the current state.

**Comment by ilya-fedin** [comment]
> Why should it be running?

Other people have said it's the right behavior for GNOME so it's made like that. You have to accept that.

**Comment by ilya-fedin** [comment]
Personally I don't really care what the behavior for GNOME is. If you can implement a better one, feel free to make a PR, I will happily review it.

**Comment by EdJoPaTo** [comment]
> You have to accept that.

That a hidden checkbox controls behavior I can't change as it is hidden?

> If you can implement a better one, feel free to make a PR, I will happily review it.

Everyone can code every language.

Can you please relabel this issue from "completed" to "open" or more likely "not planned" as you don't seem to have any intentions on actually getting this fixed?

**Comment by ilya-fedin** [comment]
no, personally I can't

**Comment by ilya-fedin** [comment]
> Everyone can code every language.

That's sad if you can't but tdesktop lacks contributors just as well, there's no one else to do that work. Personally I volunteer to fix my problems (and I use KDE). Sadly there's no contributor from GNOME community to fix GNOME-specific problems.
