### ISSUE TITLE
Telegram always prompts for bot permissions when adding bot to a group via "startgroup" deep link

### ISSUE THREAD

**Issue by tjkcc** [telegramdesktop/tdesktop#27903]
### Steps to reproduce

To reproduce:

1. All bot's default permissions are set to "false" (via `setMyDefaultAdministratorRights` and via BotFather too).
2. Click https://t.me/Carkarmabot?startgroup=0
3. Select a group
4. Telegram prompts for permissions selection and shows admin rights enabled by default.

### Expected behaviour

The bot should just get added to a selected group.

### Actual behaviour

Telegram is asking to confirm permissions and suggest admin rights.

### Operating system

MacOS 14.4.1

### Version of Telegram Desktop

5.0.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I've tried your link, chose a group and the bot was just added there.

**Comment by tjkcc** [comment]
> I've tried your link, chose a group and the bot was just added there.

I’ve tested this a bit more after creating this issue and found out that the prompt for permissions appears only if you are an admin in the destination group. Which is still odd.
I’m also seeing that these links behave inconsistently on different official clients. On some it doesn’t work at all (bot is not being added to a group), on some it prompts for permissions, on some it doesn’t. I’ve confirmed it with other bot developers. Some are even warning users already that these links might not work and that the bot needs to be added manually.

**Comment by john-preston** [comment]
@tjkcc I couldn't reproduce that while being a creator or an admin-non-creator as well, sorry.

Can you show me a screencast where you click on exactly that link (https://t.me/Carkarmabot?startgroup=0) and choose a group and see interface of choosing the admin rights? I can't understand.

**Comment by tjkcc** [comment]
> @tjkcc I couldn't reproduce that while being a creator or an admin-non-creator as well, sorry.
> 
> Can you show me a screencast where you click on exactly that link (https://t.me/Carkarmabot?startgroup=0) and choose a group and see interface of choosing the admin rights? I can't understand.

Can't replicate anymore in this client. Only in other official clients.
