### ISSUE TITLE
Disable Emoji hoverbutton on Macbook Desktop

### ISSUE THREAD

**Issue by GarageMech** [telegramdesktop/tdesktop#27904]
### Is your feature request related to a problem?

It blocks my chat so I cant see what I need to know before I reply.
It opens automatically when I hover mouse over, happens a lot by accident.
Then blocks out the entire chat.

### Describe the solution you'd like

Give option to disable emoji on mousehover, macbooks already have a hotkey for toggling emojis.

Emoji hover button for macbook is kind of unnecessary.

### Describe alternatives you've considered

Going back to discord.

### Additional context

![Skjermbilde 2024-05-10 kl  02 49 27 am](https://github.com/telegramdesktop/tdesktop/assets/97891419/7f49c514-b285-4e9b-a157-1dc4e0bdf949)

**Comment by Aokromes** [comment]
you can do it on experimental settings.
