### ISSUE TITLE
Window activation on notification appearance instead of notification action in Wayland

### ISSUE THREAD

**Issue by ArkadyBuryakov** [telegramdesktop/tdesktop#27908]
## Prerequisites

**Telegram**
- `Settings > Notifications and Sounds > Draw attention to the window` = `enabled`

**Hyprland**
- `misc.focus_on_activate` = `true` - to enable focus steal window behaviour

**Dunst**
- `mouse_left_click` = `do_action` - to run action that was passed to notification

## Steps
1. Schedule a message (or prepare another account on different device)
2. Move to another workspace from Telegram window
3. Wait for a scheduled message (or send message from another device)

### Expected behaviour

Notification appears.

After click on notification - active focus moves to Telegram window. Chat from notification is opened.

### Actual behaviour

Notification appears **and active focus moves to Telegram window immediately.**

After click chat from notification is being opened in application. **However there is no focus change behavior.**

### Operating system

Archlinux, Hyprland with Dunst notification daemon

### Version of Telegram Desktop

5.0.0-1 from Archlinux extra repo

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
> Notification appears **and active focus moves to Telegram window immediately.**

This sounds intended as

>     * `Settings > Notifications and Sounds > Draw attention to the window` = `enabled`

So I don't see anything actionable here. If you don't like that then just disable the option.

**Comment by ArkadyBuryakov** [comment]
@Aokromes 
I tested on version 5.0.1 binary and got the same behavior.

@ilya-fedin Right now there is a UX missing feature - move active focus to Telegram window on notification action. I may have misinterpreted it with said setting.

Right now I have two options:
- Enable draw attention: Telegram steals focus on notification event. Without me interacting with notification.
- Disable draw attention: On click on notification it is being closed and I have to manually navigate to the Telegram window.

I can say that notification action is performed on click, because active chat is being changed in Telegram window. However there is no focus change event being produced in this action.

**Comment by ilya-fedin** [comment]
> Right now there is a UX missing feature - move active focus to Telegram window on notification action.

@ArkadyBuryakov I can't confirm it's missing on my machine with KDE Wayland. Perhaps your minimalistic setup lacks integration bits between notification daemon and window manager.

**Comment by ArkadyBuryakov** [comment]
It seems you're right. I changed notification daemon and it works correctly.

I'll close the bug, since it has nothing to do with telegram desktop. Thanks!
