### ISSUE TITLE
Ability to select and merge messages into one.

### ISSUE THREAD

**Issue by imanghafoori1** [telegramdesktop/tdesktop#27901]
### Is your feature request related to a problem?

sometimes people are in a hurry and send their messages as small as possible, send and quickly type the rest as yet and one small message. but they all can be merged into a single meaningful one.
So as a group manager or an individual in private chat, we have to right-click on the first one, choose  "edit" and add the following messages by copy/pasting them then hit the "enter" key and delete the rest, which is tedious.

### Describe the solution you'd like

we can select the messages, (like when we want to mass-delete them or forward them) and then we hit the "merge" button so that all the messages get merged into one message.
for example:
1- we select 4 messages.
2- hit merge
3- the selected messages disappear.
4- a new message appears containing the contents of the 4 selected messages.

The same thing can be done for images sent individually. select them and hit merge to become a single album. 

### Describe alternatives you've considered

we can right-click on the selected message and see the merge button as well.

### Additional context

This way groups and private chats can be kept nice and tidy resulting in a more enjoyable environments.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
