### ISSUE TITLE
qt.svg: Error while inflating gzip file: SVG format check failed

### ISSUE THREAD

**Issue by ProgrammingLife** [telegramdesktop/tdesktop#27910]
### Steps to reproduce

1. Open Telegram
2. Watch your journald getting spammed with this error: qt.svg: Error while inflating gzip file: SVG format check failed
3. Or just watch any video and split it to the it own window (image-to-image)

The same as here: https://github.com/telegramdesktop/tdesktop/issues/26779
But it's not fixed until now. It was fixed about 1-2 month ago but now it fails again.

### Expected behaviour

No error when using Telegram

### Actual behaviour

A lot of error messages in journald: qt.svg: Error while inflating gzip file: SVG format check failed

### Operating system

Arch Linux, XFCE

### Version of Telegram Desktop

5.0.1-1

### Installation source

Other (unofficial) source

Installation source: `pacman -S telegram-desktop`

### Logs

```shell
04:56:22.682 UTC user@1000.service qt.svg: Error while inflating gzip file: SVG format check failed
04:56:22.683 UTC user@1000.service qt.svg: Error while inflating gzip file: SVG format check failed
04:56:22.683 UTC user@1000.service qt.svg: Error while inflating gzip file: SVG format check failed
04:56:22.683 UTC user@1000.service qt.svg: Error while inflating gzip file: SVG format check failed
04:56:22.684 UTC user@1000.service qt.svg: Error while inflating gzip file: SVG format check failed
04:56:22.685 UTC user@1000.service qt.svg: Error while inflating gzip file: SVG format check failed
04:56:22.685 UTC user@1000.service qt.svg: Error while inflating gzip file: SVG format check failed
04:56:22.686 UTC user@1000.service qt.svg: Error while inflating gzip file: SVG format check failed
```

**Comment by ilya-fedin** [comment]
Don't add tdesktop to your system log, desktop libraries are known to be very chatty, nothing tdesktop could do about that
