### ISSUE TITLE
In the group there is "Deleted Account" but after remove from group then it's still there (sorry my english not good)

### ISSUE THREAD

**Issue by haloph** [telegramdesktop/tdesktop#27929]
### Steps to reproduce

1. open group have "Deleted Account" inside
2. open "group info"
3. remove from group "Deleted Account" done
4. open group then "Deleted Account" still there
![cap](https://github.com/telegramdesktop/tdesktop/assets/162649102/a66ecca0-2fc8-4579-9d48-ec1c706a78ac)

### Expected behaviour

remove from group "Deleted Account"

### Actual behaviour

but after remove from group "Deleted Account" still there

### Operating system

Windows 10 22H2

### Version of Telegram Desktop

5.0.1 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
can't reproduce
