### ISSUE TITLE
Share links don't work in Web App

### ISSUE THREAD

**Issue by Viiprogrammer** [telegramdesktop/tdesktop#27923]
### Steps to reproduce

1. Open webapp
2. Call
  2.1. `webApp.openTelegramLink('https://t.me/share?url=' + address)`
  or
  2.2. `webApp.openLink('https://t.me/share?url=' + address.value)`
4. ![image](https://github.com/telegramdesktop/tdesktop/assets/17622604/006a9089-cc02-49d2-baa7-482b546220bf)

### Expected behaviour

Open link as share link

### Actual behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/17622604/006a9089-cc02-49d2-baa7-482b546220bf)

### Operating system

Ubuntu 22.04.4 LTS x86_64 / Windows 11

### Version of Telegram Desktop

5.0.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@Viiprogrammer 

The correct link to share looks like: https://t.me/share/url?url={url}

**Comment by Viiprogrammer** [comment]
> @Viiprogrammer
> 
> The correct link to share looks like: [https://t.me/share/url?url={url}](https://t.me/share/url?url=%7Burl%7D)

Hmm, this actually works https://core.telegram.org/widgets/share#custom-buttons

[https://t.me/share?url={url}](https://t.me/share?url=%7Burl%7D) also works too, but outside the WebApp and not present in docs.

Solved, thanks for your answer!
