### ISSUE TITLE
Portable version of Telegram won't receive messages in realtime if portable folder copied to other PC after it was logged in and started from both PCs in a same time

### ISSUE THREAD

**Issue by DJ-ZX** [telegramdesktop/tdesktop#2792]
1. Unpack portable TG on PC1
2. Login with your phone
3. Close app
4. Copy TG folder with all data to PC2
5. Start TG on PC1 and PC2 one by one
6. Start communicating with anyone from any PC - responses will be received on PC1
7. Close both TG's
8. Start TG on PC2 and PC1 one by one
9. Start communicating with anyone - now you will get responses on PC2 only

**Comment by auchri** [comment]
Use the template next time.

**Comment by DJ-ZX** [comment]
I can fix within hour or leave as is?

**Comment by john-preston** [comment]
@DJ-ZX This is the way MTProto server works, single authorization key (that you copied in two places) receives each update only once, so it won't work if launched simultaneously in more than one copy. You should take separate versions and log in in both of them if you want them work correctly at one time.

**Comment by DJ-ZX** [comment]
probably will be good to propose to logout from second copy then - I found one related issue:
if relogin w/o removing "data" folder - it won't help, probably it's possible to detect that version with same authorization key is running and on relogin - recreate authorization key with erasing data folder automatically?

**Comment by john-preston** [comment]
@DJ-ZX I'm going to recreate the key on each login in some time in the future, but there is no way currently to know, that the single key is used from different devices simultaneously.

**Comment by centur** [comment]
I noticed the same weird behaviour in the latest version. This means we can't use portable version from a dropbox and update it only once (and other copies are updated on the next launch from Dropbox). Kinda makes number of reasons of to prefer portable version over installation to fail. 

So there is a single killer argument now - Installation is better because it works as expected, portable - doesn't.

Can we have a key bound to computer name and it's hash where we can decide if we want to re-broadcast notifications to a given PC ( whether it's a valid and approved one)

This also breaks in some way with mobile+desktop version being run simultaneously ( do I need to close mobile version every time I want to run desktop one ???)

**Comment by john-preston** [comment]
@centur You are speaking only about the same auth data. You can use mobile together with many desktop apps if you login in each of them.

What do you mean by "in the latest version"? It always worked that way.

**Comment by centur** [comment]
I'm running TGPortable from Dropbox on few machines (home\work\ travel), and often leave it open there, Previously it was working more or less ok with multiple sessions ( not 100% sure but I think the 0.9.x version has no behavior as described in the bug above) - I can get same messages on all machines (not sure if it was update or dropbox syncing). After some client upgrades - it's started to fall apart.  I can't really trust desktop version and have to check mobile one forth and back. And sometimes mobile version behaves weirdly: e.g. I can send a message when Im on the 4g network but the recipient (who is on the home wifi) receives it only when I walk in the home wifi range and some other stuff with delivery reliability. 

Or I can send a message from one of the running portable clients (which receives updates correctly as I'm reading some messages in group discussions and can see this message in my mobile conversation with the recipient, but recipient claims she never received it or receives it only when we both open mobile clients to compare our conversation history.

Desktop client messages can may be reordered sometimes when reading it from another TG desktop client. It reorders to the correct order when client is re-opened, but I haven't seen such quirks before.

I'm not sure which way implied by "Always worked that way", but as a regular TG user I noticed some behaviour change between some older versions (0.9.x and before) and the latest updates. TG worked differently before (and frankly saying - was more reliable and stable in terms of delivery and message ordering)

**Comment by stek29** [comment]
I think there's no way to detect such behaviour without making changes to server side.
