### ISSUE TITLE
WebApp context menu not closed when click outside window

### ISSUE THREAD

**Issue by Viiprogrammer** [telegramdesktop/tdesktop#27921]
### Steps to reproduce

1. Open webapp
2. Right click for context menu
3. Click outside / etc.

https://github.com/telegramdesktop/tdesktop/assets/17622604/0bd25fbe-5e6e-4f04-b2ce-604f9749a2b2

### Expected behaviour

Context menu closed

### Actual behaviour

Context menu doesn't close

### Operating system

Ubuntu 22.04.4 LTS x86_64

### Version of Telegram Desktop

5.0.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I'm doubt this is fixable on tdesktop level. Qt lacks logic for this for QtQuick windows which the windows of Qt Wayland Compositor are (which contain the webkit windows, including context menus).

**Comment by ilya-fedin** [comment]
https://bugreports.qt.io/browse/QTBUG-69777

**Comment by ilya-fedin** [comment]
Added this to #25126
