### ISSUE TITLE
Explicitly highlight on website that each user needs their own API ID

### ISSUE THREAD

**Issue by prabnur** [telegramdesktop/tdesktop#27934]
### Is your feature request related to a problem?

I Made a simple Pyrogram script that simply takes a message from an influencer channel, extracts a contract address and sends it to BonkBot to make a purchase.
Gave it to my friends to test it out. But I didn't realise that they needed their own API ID? I assumed that's usually an application level thing.
We all got auto banned :(

### Describe the solution you'd like

I wish the information that each user needs a separate API ID and Hash is more explicitly and boldly stated [here](https://core.telegram.org/api/obtaining_api_id)

### Describe alternatives you've considered

It's not too complicated of a feature but upto you and your roadmap.

### Additional context

Would it also be possible to unban me and my friends? My friends also had a considerable amount of money in their BonkBot wallet which they cannot recover without access to their Telegram accounts.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by ilya-fedin** [comment]
> But I didn't realise that they needed their own API ID?

That's not really the case

> I assumed that's usually an application level thing.

That's right

> We all got auto banned :(

There was a discussion about that in https://t.me/TelegramDesktopTalk and there's an opinion that it means the accounts already were marked as suspicious by the anti-spam system (even if you didn't do anything wrong from your PoV) and logging in with a new API ID was a yet another suspicious action leading to ban

> Would it also be possible to unban me and my friends?

mailto:recover@telegram.org
