### ISSUE TITLE
Inline results window size for single results

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2793]
### Steps to reproduce
1. Activate inline bot with only one answer in results array (for example, `@gamee driver`)
2. Also try `@gamee` bot with query `@gamee kjkjflksdfjsdlkjlkj` to have only "Explore Games" button. The size of field is broken as well.

### Expected behaviour
0.10.20 Stable

![image](https://cloud.githubusercontent.com/assets/2780044/21754724/fad99c6e-d616-11e6-94ff-83286dbe25a8.png)
--------------------------------------------
![image](https://cloud.githubusercontent.com/assets/2780044/21754732/3179a0ca-d617-11e6-8cd4-373c86b7607c.png)

### Actual behaviour
0.10.26 alpha
Maybe somehow related to the latest 143181095f4d8a7b4c55e3e7f341abde850132ab

![image](https://cloud.githubusercontent.com/assets/2780044/21754720/e85de7b6-d616-11e6-92b0-a80546aec395.png)
--------------------------------------------
![image](https://cloud.githubusercontent.com/assets/2780044/21754715/d1ec84f6-d616-11e6-9bb0-f9a65c9ea507.png)

### Configuration
**Operating system:** Windows 10 LTSB x64
**Version of Telegram Desktop:** 0.10.26

**Comment by MasterGroosha** [comment]
Still reproducable in 1.0.14alpha

**Comment by john-preston** [comment]
@MasterGroosha Well, this is done on purpose. When this window has a minimal height you can go to Emoji panel and choose an emoticon. In previous version you were unable to choose anything there..

**Comment by MasterGroosha** [comment]
Oh, I thought it was bug. Thank you for the explanation!
