### ISSUE TITLE
Uploads randomly halt

### ISSUE THREAD

**Issue by UpscaleAnon** [telegramdesktop/tdesktop#27938]
### Steps to reproduce

Just upload files I guess. At least happens with .mp4 and .7z files.

### Expected behaviour

Files are supposed to be uploaded successfully.

### Actual behaviour

Last few days, uploads have been constantly getting stuck on certain files. Retrying them over and over does not help and it seems to apply to maybe like 10% files.
Things I've tried that does not help: Restarting internet, Telegram, retry uploading, uploading to different channel, ungroup files, group files, turn on vpn.
It always fails at the very last few megabytes.
Here's a few samples:
![image](https://github.com/telegramdesktop/tdesktop/assets/134393519/823b17de-984c-4f67-9dc8-7d19d8126838)
After retrying, fails the same way, just slightly different megabytes uploaded:
![image](https://github.com/telegramdesktop/tdesktop/assets/134393519/7ce344de-d4b6-4918-8ec1-409245ee068e)
Uploading individually:
![image](https://github.com/telegramdesktop/tdesktop/assets/134393519/7860de66-1889-40f1-8a9d-625f14b2f99b)
All 3 of those video files had issues uploading strangely enough.
And today I'm having issues uploading zip files:
![image](https://github.com/telegramdesktop/tdesktop/assets/134393519/70b8cfd9-4769-446c-9e21-2cf83af1a2ac)
First 2 files refusing to fully upload
![image](https://github.com/telegramdesktop/tdesktop/assets/134393519/52aa027a-e233-400f-a3b7-c40777924fd9)
Second and third from last refusing to fully upload.
I've tried uploading them individually, same issue.
Sometimes they will randomly fix themselves and actually upload, if I wait a really long time.
![image](https://github.com/telegramdesktop/tdesktop/assets/134393519/ea2263a0-cbcc-4827-9acd-af1609d150cb)
Another case, though it solved itself after a while.
![image](https://github.com/telegramdesktop/tdesktop/assets/134393519/743ce907-ae1d-4e26-aaa4-82d615cf42a5)
But maybe there's something going on with Telegram servers, seeing as even now it randomly disconnected or something.
Then again, this issue does not happen if I use web version of Telegram (K version). But the upload is so damn slow in web version that it takes 5-10 times longer.

### Operating system

Windows 10 Home 22H2

### Version of Telegram Desktop

5.0.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
i confirm this issue, lucky after a time it restarts.

**Comment by UpscaleAnon** [comment]
> i confirm this issue, lucky after a time it restarts. (at least for me)

For me it sometimes does, but some files just infinitely try to upload

**Comment by UpscaleAnon** [comment]
Can this for the love of god be fixed soon? It's so damn annoying uploading something, only to have to wait a fucking eternity because it's having a stroke at the very end. You'd think an issue like this where you basically can't use one of the primary functions of Telegram would get fixed pretty quickly and not take over a week.

**Comment by eldepor** [comment]
This is beyond a joke, upload stops for 15 seconds every 12mb. 5 hours and still uploading my files while before it took just minutes.

**Comment by john-preston** [comment]
We can look at DebugLogs of such upload.

- type in Settings "debugmode" and enable debug logs
- reproduce the issue (let the file stuck for a minute or two without progress)
- type in Settings "viewlogs" to open the folder with logs
- quit the app using Ctrl+Q
- .zip the DebugLogs folder
- you can send it to me privately to https://t.me/preston

Keep in mind that logs contain recording of all network activity and data that was transfered between the app and Telegram servers.

**Comment by john-preston** [comment]
From the logs I've seen this is server side upload speed throttling for non Premium users once they exceed some amount of monthly non-speed-limited upload amount.

You can purchase Telegram Premium to improve the upload speed to the old one.

Note that in case of that problem you should see a toast notification inside the application while you slow-upload the file which should explain the limit and suggest you buying Premium to improve things.

In case you don't see an offer to improve speed by purchasing Premium we should maybe check the logs first, because there might be other upload problems, not related to this non-premium server side speed throttling. You can check mtp_... log file yourself to see if there are any FLOOD_PREMIUM_WAIT_... errors.

**Comment by UpscaleAnon** [comment]
> * you can send it to me privately to https://t.me/preston

Sent logs
They contain a lot of this:
API Warning: not loaded minimal channel applied.
Protocol Error: -429 flood code returned!

> From the logs I've seen this is server side upload speed throttling for non Premium users once they exceed some amount of monthly non-speed-limited upload amount.

I have premium as you can see from some of the images I attached in original post where I upload files above 2GB

**Comment by UpscaleAnon** [comment]
Any updates yet?

**Comment by john-preston** [comment]
@UpscaleAnon We are debugging on the server side the problem with non-finishing upload of large files in case of premium users with fast upload speed.

**Comment by UpscaleAnon** [comment]
It seems like it no longer gets stuck at the last few MB, but now it just randomly fails in the uploading process:
![image](https://github.com/telegramdesktop/tdesktop/assets/134393519/84ee411d-a82e-49b4-a41a-d6939a25afe5)
![image](https://github.com/telegramdesktop/tdesktop/assets/134393519/cb6d0bdc-aa22-4045-987a-9bfd59ee65c9)
![image](https://github.com/telegramdesktop/tdesktop/assets/134393519/680b83e9-d464-478e-b60d-73e571aaa1ab)
I only tested a few times, but seems like it fails maybe 20-30% of the time. And so far it has only failed in the first half of the upload.
Let me know if you want me to send logs again.

**Comment by john-preston** [comment]
@UpscaleAnon yesterday was a massive power outage in one of the data centers. Please check now, it should work better.

**Comment by UpscaleAnon** [comment]
> @UpscaleAnon yesterday was a massive power outage in one of the data centers. Please check now, it should work better.

Thank you, it seems to have been fixed fully now. Tried uploading a 2.9GB file 10 times, failed 0 times
Also tried 30 different files (above 2GB), failed 0 times aswell.
Only thing is that it seems to upload in bursts, starting and stopping. But it has done that since the implementation of the faster upload and honestly isn't too much of an issue as I still get around 300mbps upload.
Taskmanager claims 400-500, but having timed it, it appears to be more around 310mbps (101GB over 46 minutes). Which is still way more than before the upload speed update.
