### ISSUE TITLE
"Please install WebKitGTK" when trying to open an, apparently, WebApp on Telegram (Flatpak)

### ISSUE THREAD

**Issue by emanuelserpa** [telegramdesktop/tdesktop#27931]
### Steps to reproduce

1. Open Telegram
2. Click on "Wallet"
3. The following message is shown

![image](https://github.com/telegramdesktop/tdesktop/assets/934124/e6abaf87-ec0b-4b28-a6ac-ce95d6bddd4f)

### Expected behaviour

Should not show the message and work, as the Flatpak shoudn't depend on system WebKitGTK

### Actual behaviour

The WebApp doesn't work because apparently WebKitGTK is missing.

### Operating system

Arch Linux

### Version of Telegram Desktop

5.0.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Install the org.telegram.desktop.webview addon

**Comment by emanuelserpa** [comment]
> org.telegram.desktop.webview

Already installed, it is the first thing I looked.

**Comment by ilya-fedin** [comment]
I can't confirm the issue you report exists, sorry.

![](https://github.com/telegramdesktop/tdesktop/assets/17829319/a8538dcc-275e-4b36-9180-1ae7ee99849c)

**Comment by DenisOlejnik** [comment]
Same problem. 
Telegram is installed via flathub. After logging in and clicking ‘Wallet’ button, ‘Please install WebKitGTK’ appears.

Installed via flatpak: org.telegram.desktop.webview, org.telegram.desktop.

Telegram version 5.1.2
Operating System: Fedora Linux 40
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel Version: 6.8.11-300.fc40.x86_64 (64-bit)
Graphics Platform: Wayland

@ilya-fedin

**Comment by ilya-fedin** [comment]
Sorry, folks, but I can't confirm the issue. Web bots work like a charm for me.

**Comment by stalkerg** [comment]
Same for me, but without flatpack - native install by Gentoo. Why Qt program required something GTK?

**Comment by ilya-fedin** [comment]
This doesn't sound related to the issue given that you say you don't use flatpak. There's a telegram group linked in `New issue -> Question` if you want just to ask questions rather than report a bug.

**Comment by Brensom** [comment]
Same problem.
