### ISSUE TITLE
Chat history popout menu background blurred when used with Plasma 6 blur desktop effect

### ISSUE THREAD

**Issue by peterhass** [telegramdesktop/tdesktop#27946]
### Steps to reproduce

1. Be on Plasma 6, open up System Settings, navigate to Window Management > Desktop Effects and activate 'Blur' effect
![image](https://github.com/telegramdesktop/tdesktop/assets/34499633/4d21c847-9f1c-4be0-891f-c8d21f0502dd)
2. Open any conversation in tdesktop
3. Right click any message

### Expected behaviour

![telegram_bug_popup_menu_without_plasma_blur_effect](https://github.com/telegramdesktop/tdesktop/assets/34499633/966bc645-f1ac-48b0-8a20-9f59a344db19)
Have transparent background between the emoji reaction picker and the context menu

### Actual behaviour

![telegram_bug_popup_menu](https://github.com/telegramdesktop/tdesktop/assets/34499633/023c2180-58ed-4631-b117-96803e3329e4)
Blur effect applies to the space between emoji reaction picker and the context menu

### Operating system

Manjaro Linux, most recent version as 2024-05-20, KDE Plasma 6.0.4 (Wayland)

### Version of Telegram Desktop

v5.0.1

### Installation source

Other (unofficial) source

**Comment by peterhass** [comment]
Don't know too much about QT but I'm interested to dig into the whole issue myself. As of right now, I traced it down to the [PopupMenu widget](https://github.com/desktop-app/lib_ui/blob/037ceb272c4dd2eb456e18b61e374c1fa759d109/ui/widgets/popup_menu.cpp#L263). Seems like it handles this 'emoji picker + context menu' setup so I would hope to fix it there with _some_ Qt attribute that stops the Plasma blur effect from being applied. Am I on the right track there?

**Comment by ilya-fedin** [comment]
It feels like the effect just applies blur on entire surface area and so is not fixable. I don't think it's a good idea to apply blur to all windows, that just can't work good as the WM doesn't know about the content (and, well, it can't know).
