### ISSUE TITLE
Wrong translation to Ukrainian language appeared for specific sentence on Telegram for Windows

### ISSUE THREAD

**Issue by JuraLys** [telegramdesktop/tdesktop#27954]
### Steps to reproduce

Send message 'buna diminjaca army' and select Translate pop-up menu item for it
see result 
![teleg-translat(](https://github.com/telegramdesktop/tdesktop/assets/146434286/5e81cfba-b66c-44d7-9406-db719fa7810b)

### Expected behaviour

correct translation should appear

### Actual behaviour

Wrong translation to Ukrainian language appeared for specific sentence 
![teleg-translat(](https://github.com/telegramdesktop/tdesktop/assets/146434286/8a25d3e2-8f49-4aca-a3e3-695648dece98)

### Operating system

Microsoft Windows [Version 10.0.19045.4412] 

### Version of Telegram Desktop

5.0.1 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
afaik translation ain't handled by client.

**Comment by JuraLys** [comment]
> afaik translation ain't handled by client.

so please redirect to correct project

**Comment by ilya-fedin** [comment]
> so please redirect to correct project

Google Translate
