### ISSUE TITLE
Clarification on the Purpose of the Separate Updater Component in Telegram Desktop.

### ISSUE THREAD

**Issue by hongyi-zhao** [telegramdesktop/tdesktop#27958]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

Hi Telegram Desktop Team,

I noticed that in [the Telegram Desktop binary release](https://github.com/telegramdesktop/tdesktop/releases/download/v5.0.2/tsetup.5.0.2.tar.xz), there are two components: `Telegram` and `Updater`. When I run `Updater`, it launches `Telegram` and the interface looks exactly the same as when I run `Telegram` directly. Additionally, it seems that running `Telegram` also updates the application to the latest version automatically.

Given this observation, could you please clarify the purpose of having a separate `Updater` component? Specifically, if the main `Telegram` application already handles updates, what additional role does the `Updater` component serve?

Thank you for your assistance!

Best regards,
Zhao

### Describe alternatives you've considered

I don't know why it's necessary to provide updated program components in binary distributions or source code development logic.

**Comment by ilya-fedin** [comment]
Main binary downloads the update, runs Updater and exits. Updater replaces Telegram binary and launches it again.
