### ISSUE TITLE
Flatpak release broken on latest org.freedesktop.Platform

### ISSUE THREAD

**Issue by maximilionus** [telegramdesktop/tdesktop#27955]
### Steps to reproduce

1. Update all the flatpak dependencies with `flatpak update`. This will automatically install the `org.freedesktop.Platform/x86_64/23.08` on the latest commit `50f572b0f3fee3b5ee1d5cb001742d4abfff9e710a20251e203750222d605599` from `2024-05-24 09:01:11 +0000`
2. Try to run the Telegram client.

### Expected behaviour

Client starts normally.

### Actual behaviour

Application crashes on the initial clean startup.

```sh
$ flatpak run org.telegram.desktop
telegram-desktop: error while loading shared libraries: librnnoise.so.0: cannot open shared object file: No such file or directory
```

### Operating system

Fedora 40, Gnome 46.1

### Version of Telegram Desktop

5.0.1

### Installation source

Flatpak

**Comment by maximilionus** [comment]
@ilya-fedin Unfortunately I don't really know how Flatpak handles dependencies, so I can not provide any useful answer, just want to share a temporary solution for anyone who will face this issue.

**Comment by ilya-fedin** [comment]
> Unfortunately I don't really know how Flatpak handles dependencies

The thing is, I believe this is an issue in freedesktop runtime, not tdesktop and you should report there.

**Comment by maximilionus** [comment]
@ilya-fedin I do completely agree with you, but I also can not reproduce this issue with any other software, as it's probably not dependant on `librnnoise`, so I'm quite not sure about how should I report this to the origin.

That said, I will monitor the situation and report it here the moment it's fixed.

**Comment by spignelon** [comment]
@ilya-fedin the bug is fixed by freedesktop.

People who are still facing this issue can simply do `flatpak update` and it will be fixed

**Comment by spignelon** [comment]
@maximilionus can you confirm? if yes then you can close the issue

**Comment by maximilionus** [comment]
@spignelon great, thanks for sharing! I will check it out in a few hours and close the issue if everything works.

**Comment by ilya-fedin** [comment]
> as it's probably not dependant on `librnnoise`

As far as I understand it, it's unable to find any libraries provided by application, not just rnnoise. It's more likely that other your applications are using GNOME or KDE runtime rather than freedesktop runtime.

**Comment by maximilionus** [comment]
Yep, confirming the issue being fixed with `org.freedesktop.Platform/x86_64/23.08` update to `0d1cdc87f99e689e25684a540d3b2f3018bfad80d727631f8d1c0447940e870d` from `2024-05-24 18:11:18 +0000`.

Thanks to @spignelon for providing the info.
