### ISSUE TITLE
WebView crashes on Linux with official binary

### ISSUE THREAD

**Issue by Lippiece** [telegramdesktop/tdesktop#27969]
### Steps to reproduce

Open any web app

### Expected behaviour

See the webpage

### Actual behaviour

WebView has crashed

<details><summary>Screenshot</summary>
<p>

![Screenshot_26_17-53-19](https://github.com/telegramdesktop/tdesktop/assets/47634624/b214c0be-655d-4942-aa40-230f68ff4079)

</p>
</details> 

Continuation of the discussion in #27363, as suggested by @ilya-fedin 

### Operating system

Operating System: Garuda Linux  KDE Plasma Version: 6.0.4 KDE Frameworks Version: 6.2.0 Qt Version: 6.7.0 Kernel Version: 6.9.0-1-mainline (64-bit) Graphics Platform: Wayland

### Version of Telegram Desktop

5.0.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> 5.0.1

There were lots of webview crash fixes in 5.0.2

**Comment by Lippiece** [comment]
> > 5.0.1
> 
> There were lots of webview crash fixes in 5.0.2

Both the static executable and the updater binaries result in version 5.0.1, but if you think this is fixed in 5.0.2, I'll suffer until I have access to 5.0.2. However, in the previous thread, there were people who said they have this version and still have the issue, so there still may be comments here.

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/releases

**Comment by ilya-fedin** [comment]
@Lippiece have you got 5.0.2 from the URL I provided?

**Comment by Lippiece** [comment]
> @Lippiece have you got 5.0.2 from the URL I provided?

Yes, thanks. Now it says this:

<details><summary>Details</summary>
<p>

![image](https://github.com/telegramdesktop/tdesktop/assets/47634624/3ac3ae32-78c5-4325-b006-119246c6879b)

</p>
</details>

**Comment by ilya-fedin** [comment]
Attach terminal output and log.txt

**Comment by Lippiece** [comment]
```
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
```

https://gist.github.com/Lippiece/9ca00f8428d4e5d9207f3404a976a40c

**Comment by ilya-fedin** [comment]
Don't you have those KMS errors anymore?

**Comment by Lippiece** [comment]
> Don't you have those KMS errors anymore?

I'm not sure if I understand the question. Which KMS errors?

**Comment by ilya-fedin** [comment]
In [this](https://github.com/telegramdesktop/tdesktop/issues/27363#issuecomment-2132278851) message you were saying you have the same error quoting multiple error lines which refer to KMS/DRM/GBM

**Comment by ilya-fedin** [comment]
> Those 2 lines I pasted is the only thing that was in the console.

Did you get them after opening web application?

**Comment by ilya-fedin** [comment]
> No, they appear on launch.

There's no sense in output if you haven't opened web application...

**Comment by Lippiece** [comment]
> > No, they appear on launch.
> 
> There's no sense in output if you haven't opened web application...

I did open a web application, but there wasn't anything else in the console.

**Comment by ilya-fedin** [comment]
Ah, ok. Is it always "Could not initialize WebView" now or is it flaky if you try to open it multiple times?

**Comment by Lippiece** [comment]
> Ah, ok. Is it always "Could not initialize WebView" now or is it flaky if you try to open it multiple times?

Yes, It's always this message. Some time ago, before 5.0, I was able to resolve such issues by reloading the webview with 3-dot menu, however now there is none, as you can see in the screenshot.

**Comment by ilya-fedin** [comment]
do you have crash dumps for Telegram in `coredumpctl` with the time of opening web application?

**Comment by Lippiece** [comment]
> do you have crash dumps for Telegram in `coredumpctl` with the time of opening web application?

After I started the app a few more times, it presented a login screen for some reason, and after login I've just successfully opened the Wallet app. I have a dump from 4.5 hours ago, but I don't think it's related. I'll post here again if the issue persists.

**Comment by ilya-fedin** [comment]
Hm, perhaps more concrete error messages are needed

**Comment by ilya-fedin** [comment]
5.0.3 now has logging for webview failures (tdesktop itself logs to log.txt while webview process into terminal output). In case this will return, you should now have details there.

**Comment by SharafatKarim** [comment]
I got this error today, and in the terminal I got,
```
wl_global_create: implemented version for 'wl_shm' higher than interface version (2 > 1)
**
Gdk:ERROR:../gtk/gdk/wayland/gdkdisplay-wayland.c:1136:gdk_wayland_display_set_cursor_theme: assertion failed: (display_wayland->shm)
Bail out! Gdk:ERROR:../gtk/gdk/wayland/gdkdisplay-wayland.c:1136:gdk_wayland_display_set_cursor_theme: assertion failed: (display_wayland->shm)
wl_global_create: implemented version for 'wl_shm' higher than interface version (2 > 1)
**
Gdk:ERROR:../gtk/gdk/wayland/gdkdisplay-wayland.c:1136:gdk_wayland_display_set_cursor_theme: assertion failed: (display_wayland->shm)
Bail out! Gdk:ERROR:../gtk/gdk/wayland/gdkdisplay-wayland.c:1136:gdk_wayland_display_set_cursor_theme: assertion failed: (display_wayland->shm)
```

Operating system: Arch Linux with KDE plasma desktop environment (installed from Arch official repo).
My `telegram-desktop` version is, `5.1.5`. Can anyone please help me to fix?

**Comment by ilya-fedin** [comment]
@sammiee5311 this looks like https://bugreports.qt.io/browse/QTBUG-126379, there seem to sadly be no other solution than asking your distro to downgrade libwayland to 1.22.x or older or switching to one of Qt's [supported platforms](https://doc.qt.io/qt-6/supported-platforms.html#linux-x11).
