### ISSUE TITLE
Unable to log in: Flash back and send code to unknown device

### ISSUE THREAD

**Issue by duomilanlan** [telegramdesktop/tdesktop#27968]
### Steps to reproduce

1.Any way to flash back account
2.Re-login attempt

### Expected behaviour

Send code smoothly

### Actual behaviour

Sent code to unknown client, this behavior occurs in PC, web client, android sent SMS code can not be received, support staff has not contacted me for more than a week

### Operating system

Windows 11

### Version of Telegram Desktop

tsetup-x64.5.0.1.exe

### Installation source

Static binary from official website

**Comment by duomilanlan** [comment]
I checked all my devices, including the web side, and they all blinked back and asked me to log in again, only to send the login code to an unknown client

**Comment by taha-ghadirian** [comment]
Hello dear @duomilanlan, 
As you mentioned, it's a platform wide issue that should be submitted on https://bugs.telegram.org/.

Also, I should mention that all telegram clients **except** android and IOS will send the code to other connected clients. 
So if you want to connect your Desktop client, web client, or any unofficial client, you should first login to your account using an official phone app.

**Comment by duomilanlan** [comment]
I used the official phone app, but I couldn't receive its SMS code; The relevant staff has not replied to me for a week, I understand that this is the programmer who writes the code, but you must have better access to the internal support staff than I do; I would be grateful if you could give me a little help. If there is anyone who can help me, I am willing to pay some price, here is my email address:duomilanlan@gmail.com

**Comment by taha-ghadirian** [comment]
> I used the official phone app, but I couldn't receive its SMS code; I haven't heard back from the relevant staff in a week, and I understand that these are some volunteers, but you must have better access to the internal support staff than I do; I would be grateful if you could give me a little help. If there is anyone who can help me, I am willing to pay some price, here is my email address:[duomilanlan@gmail.com](mailto:duomilanlan@gmail.com)

I would highly recommend not trusting anyone online. 
I encourage you to submit a bug report on the official website on https://bugs.telegram.org/, and also connecting with official telegram twitter support on https://x.com/telegram/. 

As I can see on twitter mentions, there are also other people that have same issue like you. I also had this issue once and got fixed by contacting to telegram support on twitter.

**Comment by duomilanlan** [comment]
> 我安装时不要相信网上的任何人。我鼓励您在官方网站https://bugs.telegram.org/ 上提交错误报告，并同意https://x.com/telegram/与官方电报推特支持联系。[](https://bugs.telegram.org/)[](https://x.com/telegram/)
> 
> 正如我在推特上看到的，其他人也遇到了和你一样的问题。 我也遇到过一次这个问题，通过推特上的电报询问这个问题。

The problem is I can't get a response from any source. I know it's all volunteers here. Maybe my mail is in the spam box?

**Comment by duomilanlan** [comment]
> Hello dear @duomilanlan, As you mentioned, it's a platform wide issue that should be submitted on https://bugs.telegram.org/.
> 
> Also, I should mention that all telegram clients **except** android and IOS will send the code to other connected clients. So if you want to connect your Desktop client, web client, or any unofficial client, you should first login to your account using an official phone app.

Could you please contact any of the support staff for me to check their email? I've been sending questions about this for a long time.
![Uploading Screenshot_20240526_233625.jpg…]()
