### ISSUE TITLE
Chronological order after reconnection

### ISSUE THREAD

**Issue by oguimbal** [telegramdesktop/tdesktop#2797]
### Steps to reproduce
1. Write stuff in a conversation
2. Disconnect telegram desktop
3. Write stuff in another telegram client in the same conversation
(i waited a day here... but the same happens with less time, i checked.)
4. Write stuff (with tdesktop) in the same conversation before telegram reconnects
5. Wait until it reconnects and syncs everything...

### Expected behaviour
I would expect order to be a bit off, but not by that much

### Actual behaviour
See screenshot: Stuff written while reconnecting appeared before messages written offline (received after reconnection)
(which was not the case on my friend's end, of course)
I'm a developper, and understand the "why" of this behavior, but its a bit disturbing to see messages I just wrote disapear once reconnected. Not to mention the chronological order which sounds a bit off (see screenshot)...

Just ignore that if it's the expected behavior, but I must not be the only one to find that awkward, am I ?

![image](https://cloud.githubusercontent.com/assets/8973947/21800715/238de1d4-d71f-11e6-956b-6c0f3951b920.png)

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
0.10.20

### Logs
N/A

**Comment by stek29** [comment]
Once I was chatting at 00:00, and it became "Jan 9 | Jan 10 | Jan 9 | Jan 10"

**Comment by stek29** [comment]
Btw, issue title is a bit confusing -- it can happen even without connection being lost.

**Comment by nyuszika7h** [comment]
Yeah, for example if you're sending a large file and others send messages in meantime, your message will still show up before the others even after switching away from and back to the chat, unlike on Android.

**Comment by Gollam** [comment]
We did not lose interest...

**Comment by Gollam** [comment]
Should I also start commenting with a bot to keep this ticket open?

**Comment by nyuszika7h** [comment]
Still an issue.
