### ISSUE TITLE
Cursor chaing position when using shortcuts to change the reply message.

### ISSUE THREAD

**Issue by amiroo54** [telegramdesktop/tdesktop#27970]
### Steps to reproduce

1. Write a message.
2. Use ctrl + up arrow to select the message to reply to.

### Expected behaviour

The cursor stay where it was. 

### Actual behaviour

The cursor moves to first of the line or the upper line.

### Operating system

Arch linux, KDE Plasme DE, Wayland.

### Version of Telegram Desktop

5.0.2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
I don't quite understand the bug report. The actual behavior is the behavior I would expect. Why should it be the way you expect?

**Comment by amiroo54** [comment]
I am truly sorry. I meant to write that in the expected behavior. I will edit it now. Have a good day.

**Comment by ilya-fedin** [comment]
I can't reproduce your bug. Cursors stays where it was.

**Comment by amiroo54** [comment]
After further testing I have noticed this only happens in the topic groups.

**Comment by ilya-fedin** [comment]
Yes, I can reproduce this way

**Comment by MrJavadGG** [comment]
Hello guys.
My friend reported this bug and we thought that you have fixed it.
But it's still there and amiroo is nagging in my PV.
Can you please check this out again?
Tnx😂

**Comment by ilya-fedin** [comment]
I don't know why yiu thought that, the issue is open... I guess this is not a priority, sorry.
