### ISSUE TITLE
Can't mention users without Username with special characters

### ISSUE THREAD

**Issue by taha-ghadirian** [telegramdesktop/tdesktop#27977]
### Steps to reproduce

1. Open a group
2. Type `@AccountName` 
![image](https://github.com/telegramdesktop/tdesktop/assets/36773254/1ba924f8-568d-44a4-90a2-64492c0077c9)
3. Click on the account name that want to mention
![image](https://github.com/telegramdesktop/tdesktop/assets/36773254/cf1dd3b8-a5e8-4f20-a7cf-f8bd48ae122b)

4. Check that all accounts are mentioned correctly:
![image](https://github.com/telegramdesktop/tdesktop/assets/36773254/7d87ac8e-6bef-4d64-b449-603f41ece632)

5. Send the message
![image](https://github.com/telegramdesktop/tdesktop/assets/36773254/c881f90c-f9cb-4c3c-a7e6-c69cfa6d5b80)

### Expected behaviour

As you can see in the screenshots, `N.ZI` account is not mentioned correctly.
![image](https://github.com/telegramdesktop/tdesktop/assets/36773254/c881f90c-f9cb-4c3c-a7e6-c69cfa6d5b80)

### Actual behaviour

`N.ZI` turns to link, and mention notification send to him. Like the other accounts like `saman` and `saturn 🪐`.

### Operating system

Tested on both: Arch linux, Windows 11

### Version of Telegram Desktop

5.0.2

### Installation source

Static binary from official website

**Comment by taha-ghadirian** [comment]
Maybe related to #27976, But **NOT** duplicate.

**Comment by agoudbg** [comment]
I think it related to #27962

**Comment by taha-ghadirian** [comment]
> I think it related to #27962

Don't think so, because I can mention as many as users in any order that I want, but just only some of accounts fail every time.

**Comment by john-preston** [comment]
I couldn't reproduce with some no-username user renamed to "N.ZI", so please:
1. check in 5.0.3 version
2. if it reproduces, collect DebugLogs with this issue being reproduced and send them privately to me at https://t.me/preston

**Comment by taha-ghadirian** [comment]
Works fine on `5.0.3`.
