### ISSUE TITLE
how to make multi quote @'s disappear on a channel

### ISSUE THREAD

**Issue by fowler36** [telegramdesktop/tdesktop#27976]
### Steps to reproduce

Simply that. they just don't disappear on a channel, those multiple quotes. 
Thanks

### Expected behaviour

It should work

### Actual behaviour

Still the same

### Operating system

Windows 10 NT

### Version of Telegram Desktop

5.0.2

### Installation source

Static binary from official website

**Comment by taha-ghadirian** [comment]
Well, that works for me! 
Can you please provide more detail with some examples and screenshots? That would help reproducing the problem.

![image](https://github.com/telegramdesktop/tdesktop/assets/36773254/d71c4dbc-89b1-4803-9b12-48f9679164de)

**Comment by fowler36** [comment]
yeah , i tried again, and it worked . thanks :)
