### ISSUE TITLE
No settings for notifications in Plasma 6 Wayland

### ISSUE THREAD

**Issue by qmmp123** [telegramdesktop/tdesktop#27975]
### Steps to reproduce

Open settings
Navigate to notifications
Scroll down

Let me know if I can provide additional info

### Expected behaviour

You should see something like this 
![image](https://github.com/telegramdesktop/tdesktop/assets/6360702/afaf16b8-a54d-4fb8-8335-baf91b65d363)

### Actual behaviour

There are no options for notifications

### Operating system

OpenSUSE Kalpa 20240521, Plasma 6.0.4

### Version of Telegram Desktop

5.0.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Yes, application doesn't have control over that on Wayland. Nothing could be done about that.

**Comment by kas-cor** [comment]
If you run the settings under sudo, they appear and everything works.
