### ISSUE TITLE
Ubuntu/Wayland TDesktop Video Player Window does not remember the resizing ratio in PiP/Mode

### ISSUE THREAD

**Issue by mrkapqa** [telegramdesktop/tdesktop#27982]
### Steps to reproduce

1. Click video to play in Telegram Desktop
2. Click PiP Mode when in FullScreen Mode
3. Resize Window of Video since it is very small by default (on 16:9 1080p laptop screen 14inch(
4. click another video

### Expected behaviour

would expect that the video player in PIP Mode would remember the video window resizing done in previous steps, 
instead it falls back to "standard" size which is too small for me on thsi laptop

### Actual behaviour

video window always starts in very small window, resizing window does not persist.

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

5.0.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I can't confirm the bug, it uses previous size for me

**Comment by mrkapqa** [comment]
thank you, issue is subdued now, maybe just needed a fresh reboot. scaling much better now.
