### ISSUE TITLE
Miniaps not working on Ubuntu Linux

### ISSUE THREAD

**Issue by webportnoy** [telegramdesktop/tdesktop#27980]
### Steps to reproduce

1. Starting official miniapp example https://t.me/DurgerKingBot
2. Press "Order food"

### Expected behaviour

Open miniapp

### Actual behaviour

Got black screen without any error messages
![Screenshot_20240527_132125](https://github.com/telegramdesktop/tdesktop/assets/35290918/6d51b50a-d7f7-46ca-acee-6b74800ac4c6)

### Operating system

Kubuntu 22.04, X11, KDE Plasma 5.24.7, Qt 5.15.3

### Version of Telegram Desktop

5.0.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Does context menu appear if you right click? Please attach terminal output and log.txt

**Comment by webportnoy** [comment]
> Does context menu appear if you right click? Please attach terminal output and log.txt.

Context menu on right click is working.  Active items in menu are "Reload" and "Inspect Element"
![Screenshot_20240527_134143](https://github.com/telegramdesktop/tdesktop/assets/35290918/a8c5f22a-2c30-4f38-8218-67ab1cf5f250)

[log.txt](https://github.com/telegramdesktop/tdesktop/files/15454830/log.txt)

Teminal:
`~/soft/Telegram$ ./Telegram
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 384x590: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 384x590: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1000x650: Permission denied
`

**Comment by ilya-fedin** [comment]
Do other webkit-powered applications like epiphany work on your PC?

**Comment by ilya-fedin** [comment]
I bet NVIDIA driver breaks webkitgtk on your PC
```
[2024.05.27 13:38:33] OpenGL Renderer: NVIDIA GeForce GT 710/PCIe/SSE2
[2024.05.27 13:38:33] OpenGL Vendor: NVIDIA Corporation
[2024.05.27 13:38:33] OpenGL Version: 4.6.0 NVIDIA 470.239.06
```

**Comment by webportnoy** [comment]
> Do other webkitgtk-powered applications like epiphany work on your PC?

Looks like it's not 
![Screenshot_20240527_135252](https://github.com/telegramdesktop/tdesktop/assets/35290918/370ca86d-06dd-4aea-8a28-a728ac419a26)

**Comment by ilya-fedin** [comment]
mini apps use the same technology... if it is broken on your machine then they just won't work

**Comment by ilya-fedin** [comment]
I don't think anything is possible to do from tdesktop side on this... You're likely need to replace your driver to nouveau to fix this.

**Comment by webportnoy** [comment]
> I don't think anything is possible to do from tdesktop side on this... You likely need to replace your driver to nouveau to fix this.

Changed dirver to open source, and now everything is working. 
Thanks!
