### ISSUE TITLE
 An option to disable ctrl + ↑ (topic groups).

### ISSUE THREAD

**Issue by ChrisTVH** [telegramdesktop/tdesktop#27989]
### Is your feature request related to a problem?

Yes, it seems to be something they added in the last update I received.

### Describe the solution you'd like

It happens that today when I woke up and connected to my favorite group, I wanted to answer a message, as usual to do it faster I press **ctrl + ↑** that's when something totally new came out, that at first I didn't even know what it was and it was in my way, now I know what it is, and it doesn't help me at all.

![image](https://github.com/telegramdesktop/tdesktop/assets/58376852/a295e61b-3f4e-4345-a120-d457cfc68e5b)
Is that option to Reply in…

All I want is that in the options there is a way to disable this I checked to see if it was and I didn't see it, if it is I would be happy to be told.

### Describe alternatives you've considered

I just want to be able to disable this feature, in normal chats and groups it is not there and I don't want to be forced to turn my group into a normal one again.

**Comment by john-preston** [comment]
@ChrisTVH This was a bug, this should be fixed in the newly deployed 5.0.4.

**Comment by ChrisTVH** [comment]
> This was a bug, this should be fixed in the newly deployed 5.0.4.
If I had known I would have reported it as a bug.
