### ISSUE TITLE
Call (either video or audio) controls not responsive with multiple screens

### ISSUE THREAD

**Issue by MauroFoti** [telegramdesktop/tdesktop#27985]
### Steps to reproduce

1. boot with two+ monitors
2. open telegram and make a call (directly call someone or create a group call)

### Expected behaviour

A window appear and I should be able to click buttons to join the call, mute/unmute, share screen and so on.

### Actual behaviour

A window appear but any click on this call window is ignored and instead clicks go to the main telegram window, making it impossible to make and join audio and video calls.

For example if I call a contact, when I click to select audio or video call, the focus switches to the main telegram window and another chat is opened. This also happens when receiving a call and trying to answer it.

The solution is to shutdown, boot with only one of the two monitors connected and at that point I can make and receive calls.

### Operating system

Linux Mint 20.3 Cinnamon

### Version of Telegram Desktop

5.0.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> A window appear but any click on this call window is ignored and instead clicks go to the main telegram window, making it impossible to make and join audio and video calls.

This sounds like a bug of your window manager? Like it thinks that the focused window is not the really one. I think you should report this to your WM.
