### ISSUE TITLE
Telegram crashed on Windows 10 x64

### ISSUE THREAD

**Issue by JuraLys** [telegramdesktop/tdesktop#27995]
### Steps to reproduce

Telegram crashed on Windows 10 x64, see log 
[teleg-log.txt](https://github.com/telegramdesktop/tdesktop/files/15484101/teleg-log.txt)

### Expected behaviour

App should not crash

### Actual behaviour

Telegram crashed on Windows 10 x64

### Operating system

Microsoft Windows [Version 10.0.19045.4412] 

### Version of Telegram Desktop

5.0.3 x64

### Installation source

Static binary from official website

### Logs

```shell
see log in Steps to reproduce
```

**Comment by JuraLys** [comment]
> plz enable beta, restart telegram and send crash id on next start and post id here.

updated to beta but where can I find crash id there?

**Comment by taha-ghadirian** [comment]
> > plz enable beta, restart telegram and send crash id on next start and post id here.
> 
> updated to beta but where can I find crash id there?

After telegram crashed, open it again. An report screen will appear on your screen. 
You can copy CrashId, then click on `send crash report` button. 
![image](https://github.com/telegramdesktop/tdesktop/assets/36773254/cfe93295-6c7e-4663-8156-4c6a948a334b)
