### ISSUE TITLE
Theme does not match in quick preview mode.

### ISSUE THREAD

**Issue by RobiMez** [telegramdesktop/tdesktop#27991]
### Steps to reproduce

1. install the latest beta 
2. Switch your theme to night mode 
3. long press on a user's profile to get the quick preview up 

### Expected behaviour

The quick preview chat theme should match the current theme 

### Actual behaviour

The theme is reverted to the default light theme 

![image](https://github.com/telegramdesktop/tdesktop/assets/53259730/fa8958a9-126a-4d24-9a09-b8ad8e3e5654)
![image](https://github.com/telegramdesktop/tdesktop/assets/53259730/1f217730-57a1-411c-8561-06cea4388cb4)

### Operating system

Windows 11 Pro 23H2

### Version of Telegram Desktop

5.0.5 beta x64 

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
yeah, thanks! will be fixed

**Comment by RobiMez** [comment]
YOS , thanks for fixing it on 5.0.6
