### ISSUE TITLE
The dot "." creates a new line regardless if there is no space afterwards.

### ISSUE THREAD

**Issue by sasatefa2009** [telegramdesktop/tdesktop#27999]
### Steps to reproduce

Typing the following "Our fee is a static percentage over the market rate varying from .5% ~ 3%" in a message will create a new line after the "." and will have the second line start with "5%"

### Expected behaviour

The dot "." mustn't create a new line if it's attached to a number/letter afterward.

### Actual behaviour

The line breaks after the dot, also tried "0.5%" and still breaks the line after the dot.

### Operating system

Windows 10

### Version of Telegram Desktop

5.0.6 beta x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://i.imgur.com/STkdWnc.png can't reproduce on windows 10 and telegram desktop 5.1.0

**Comment by john-preston** [comment]
I think what topic starter means is it *can* break, if line width is some exact value for that, while it shouldn't and should be just treated as a single word. Not that it always breaks.

**Comment by sasatefa2009** [comment]
@Aokromes 
![image](https://github.com/telegramdesktop/tdesktop/assets/22708418/a3a4ffc9-21ad-413d-b4c3-abf7b4416a34)

**Comment by Aokromes** [comment]
ok reproduced it making width smaller https://i.imgur.com/ysKBBky.png

**Comment by sasatefa2009** [comment]
@john-preston Kindly look at this issue because it screws my channel for desktop users.

**Comment by Aokromes** [comment]
> @john-preston Kindly look at this issue because it screws my channel for desktop users.

only if they have a very small width.

**Comment by john-preston** [comment]
@sasatefa2009 I guess it wouldn't break in case it was 0.5% ~ 3%? Only .5% without leading 0 is an issue?

**Comment by john-preston** [comment]
I couldn't reproduce with 0.5%, only with .5% 🤔

**Comment by john-preston** [comment]
I'll try just treating dot as a regular character and see if there will be complaints.

**Comment by sasatefa2009** [comment]
![image](https://github.com/telegramdesktop/tdesktop/assets/22708418/4d0dc112-84d3-40bb-a569-8affcc2c45a4)

![image](https://github.com/telegramdesktop/tdesktop/assets/22708418/9cc50011-469e-42ae-9395-bd31addf6414)

It happens in both cases @john-preston

**Comment by john-preston** [comment]
@sasatefa2009 That's weird, as if bold text is handled differently in this case.

**Comment by sasatefa2009** [comment]
@john-preston It also works with quotation marks "
![CopyQ NPlgBV](https://github.com/user-attachments/assets/e770c603-1d64-47d6-b452-805649ae2aa5)
