### ISSUE TITLE
Telegram tried to access password browser extension

### ISSUE THREAD

**Issue by conromia** [telegramdesktop/tdesktop#27990]
### Steps to reproduce

While browsing the web, an alert came up and said "Telegram-deskto ()" would like access to the Enpass password extension.
This happened randomly and unable to reproduce.
Password manager in use is Enpass.
Browser in use is Brave with Enpass password extension active.
![Screenshot_20240529_103325](https://github.com/telegramdesktop/tdesktop/assets/8295583/e3567529-a81f-4420-afe9-2a52b70f35b1)

### Expected behaviour

Telegram not request access to Enapss password manager.

### Actual behaviour

Enpass prompt to allow or deny access.

### Operating system

Fedora 40 KDE

### Version of Telegram Desktop

5.0.2

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Can you explain what do you want to be changed in tdesktop? tdesktop doesn't use any enpass APIs (personally I hear first time about this thing) so unless you can provide on what exactly tdesktop should start or stop do, the issue is invalid.

**Comment by conromia** [comment]
No need to be arrogant, I'm just a user reporting what I was hoping was a bug and not suspicious behaviour.
I don’t understand why Telegram would be looking at a browser extension either.
I know Enpass and the browser extension use tcp ports to communicate with each other.
Does telegram have the ability to port scan?
This could very well be a flatpak issue, but I am not qualified to research that further.

Regards,
James Burndred
________________________________

**Comment by ilya-fedin** [comment]
> Does telegram have the ability to port scan?

No, it doesn't.

> This could very well be a flatpak issue, but I am not qualified to research that further.

I would rather suspect the extension bugs and adds any application opening a link in your browser or something like that.

> I don’t understand why Telegram would be looking at a browser extension either.

The best thing here is to ask extension developers.

**Comment by Aokromes** [comment]
also, name is "Telegram-deskto ()" not "telegram-desktop" or "Telegram"

**Comment by cfinnberg** [comment]
I know this is closed, but just in case. My Telegram application (5.2.4 beta - Stand alone app for Linux downloaded from telegram.org) also tried to connect to my Enpass Password manager.

**Comment by ilya-fedin** [comment]
You should contact your password manager about fake connection attempts. tdesktop definitely doesn't have such code.
