### ISSUE TITLE
The photo caption is not displayed correctly if you use a 264x132 photo

### ISSUE THREAD

**Issue by Dimoka113** [telegramdesktop/tdesktop#28004]
### Steps to reproduce

Send a photo with a resolution of 264x132 with a caption of 25-45 characters.

### Expected behaviour

Normal display of text in signature...

### Actual behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/133571582/16373eb2-c166-4d57-97f3-b317798d31ba)
I don't know how to describe it...
If it helps somehow, in this example I wrote: "Wow, I found a config that breaks everything"

### Operating system

Windows 10

### Version of Telegram Desktop

5.1.1

### Installation source

Static binary from official website

### Crash ID

-

**Comment by john-preston** [comment]
Thanks!
