### ISSUE TITLE
Putting a caret to the start of the text breaks formatting

### ISSUE THREAD

**Issue by ENCRYPTEDFOREVER** [telegramdesktop/tdesktop#28002]
### Steps to reproduce

1. In a chat write a space-separated text, for example "It looks like there is a bug"
2. Select all text
3. Format it (for example, bold or monowidth)
4. Put a caret to the start of the text
5. Only the first word now remains formatted

### Expected behaviour

Formatting should be unaffected

### Actual behaviour

Formatting breaks

### Operating system

Ubuntu 23.04, both wayland and x11

### Version of Telegram Desktop

5.1 and 5.1.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Is this still an issue with 5.1.2?

**Comment by ENCRYPTEDFOREVER** [comment]
> Is this still an issue with 5.1.2?

Nah, looks like fixed
