### ISSUE TITLE
Make Telegram RPC

### ISSUE THREAD

**Issue by J0nathan550** [telegramdesktop/tdesktop#28005]
### Is your feature request related to a problem?

No? No problem.

### Describe the solution you'd like

I wish Telegram could have in status bars (simillar to discord) have an ability to see what other people playing or doing while telegram is opened.
It should have an API for developers that wish to do games that will be represented in status bar.
Have an feature that not allows to see what you do. Playing or Listening. Doesn't matter.
Overall, I wish to see simillar implementation of Discord RPC in Telegram. Will allow developers to promote their products through out the telegram. And will make application more fun to use.

### Describe alternatives you've considered

?

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
