### ISSUE TITLE
On Telegram startup : whole other desktop applications freeze (can still move mouse)

### ISSUE THREAD

**Issue by MarArMar** [telegramdesktop/tdesktop#28003]
### Steps to reproduce

1. Open Telegram

### Expected behaviour

Telegram could wait a bit but would not freeze other apps

### Actual behaviour

Telegram starts and the whole desktop freezes for ~5 seconds

I can only move mouse but cannot interact with anything

This is very anormal for a very high end setup (AMD Ryzen 9 7950X, 62,0 GiB of RAM, AMD Radeon RX 7800 XT GPU)

Operating System: TUXEDO OS 2
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.5.0-10040-tuxedo (64-bit)
Graphics Platform: X11
Processors: 32 × AMD Ryzen 9 7950X 16-Core Processor
Memory: 62,0 GiB of RAM
Graphics Processor: AMD Radeon RX 7800 XT
Manufacturer: ASUS

### Operating system

TUXEDO OS 2, KDE Plasma 5.27.10, KDE Frameworks Version: 5.114, Qt Version: 5.15, Graphics Platform: X11

### Version of Telegram Desktop

5.1.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Sorry but I can't reproduce such a bug and I don't believe it's on tdesktop side. I don't  see how tdesktop could do that so I think it's a coincidence on your side.

**Comment by alm494** [comment]
confirm the similar behavior on KDE 6.0.5 with both X11 and Wayland sessions. In my case Telegram after a while begins to block all mouse click events and all applications and DE itself affected but mouse can move, Alt-Tab, Alt-F4 an other keys work. The only solution is Alt-F3 to open console and issue reboot command and do not start Telegram

**Comment by ilya-fedin** [comment]
I recommend to report that to your DE. Application shouldn't be able to do that. Apparently you're encountering some DE bug.

**Comment by ilya-fedin** [comment]
I would rather assume it's your DE rather than X server or flatpak

**Comment by ilya-fedin** [comment]
> An X11 application can grab the Xserver, that would give the exact same effect that you describe, but's not an xserver bug.

Well, tdesktop operates on top of Qt framework so the code doesn't even know that what X server is mostly. And so I don't imagine how the code can grab server it doesn't even know about.

**Comment by ilya-fedin** [comment]
> An X11 application can grab the Xserver, that would give the exact same effect that you describe, but's not an xserver bug.

Well, tdesktop operates on top of Qt framework so the code doesn't even know that what X server is mostly. And so I don't imagine how the code can grab server it doesn't even know about.
