### ISSUE TITLE
Hide read in a chat

### ISSUE THREAD

**Issue by linguaccia22** [telegramdesktop/tdesktop#28015]
### Is your feature request related to a problem?

Hi everyone, but is it possible to hide the display in a chat when they send me a message on Telegram?
I speak both on telegram APP IOS/Android and for Windows
It would be great if one wants to read a person's message or even a voicemail but respond later.

### Describe the solution you'd like

an option that can disable the displayed

### Describe alternatives you've considered

the alternative could be to install an additional plugin that can do this

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by john-preston** [comment]
@linguaccia22 Well, there is chat preview now..
