### ISSUE TITLE
REGRESSION In search box, cursor keeps jumping to the end of text

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#28018]
### Steps to reproduce

Let's say you go to search for "stuff", but at second thought, you actually want to search for "some stuff":

1. Click on "Search" to give it focus
2. Type "stuff"
3. Either using the mouse or the left arrow key, move the cursor to the beginning of the text
4. Start typing "some" and then a space

### Expected behaviour

You should end up with the query "some stuff"

### Actual behaviour

After you've typed the "s" for "some", the cursor suddenly jumps to the end of the text for no reason, so you end up with "sstuffome "

This happens at every key stroke: no matter where the cursor was, it jumps back to the end of the text. It's basically impossible to correct what you've written except for using the backspace.

This used to work as expected.

### Operating system

Manjaro Linux

### Version of Telegram Desktop

5.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
update to 5.1.2 and test again.

**Comment by ilya-fedin** [comment]
I can't reproduce

**Comment by php4fan** [comment]
It went away after restarting Telegram.
