### ISSUE TITLE
Missing assets for 5.1.3 release on GitHub

### ISSUE THREAD

**Issue by Jamim** [telegramdesktop/tdesktop#28017]
### Steps to reproduce

1. Open [Releases](https://github.com/telegramdesktop/tdesktop/releases)
2. Find assets for [v 5.1.3](https://github.com/telegramdesktop/tdesktop/releases/tag/v5.1.3)

### Expected behaviour

There used to be 9 asset files.

### Actual behaviour

Only 2 files are listed out of 9 expected.
Notably, there is no `Source code (tar.gz, full)`.

### Operating system

not applicable

### Version of Telegram Desktop

5.1.3

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
it's macos only build.

**Comment by john-preston** [comment]
@Jamim The source code is identical to 5.1.2, the 5.1.3 was only macOS full clean rebuild of the app which fixed a broken build of 5.1.2 on macOS.
