### ISSUE TITLE
Moderation options don't appear when right-clicking mediagroup's caption/box 

### ISSUE THREAD

**Issue by ENCRYPTEDFOREVER** [telegramdesktop/tdesktop#28012]
### Steps to reproduce

1. Be an admin with required rights in a supergroup
2. Right-click anywhere outside of actual attachments (images, etc.) on a message with a mediagroup, sent by a regular non-admin user 
3. Select "Delete" from the context menu
4. No moderation options appear

### Expected behaviour

Moderation options such as "ban", "report", "delete all messages from" should appear

### Actual behaviour

Regular message deletion popup appears

### Operating system

Ubuntu 23.04, wayland 

### Version of Telegram Desktop

5.1.2

### Installation source

Static binary from official website

**Comment by brent85** [comment]
> ### Steps to reproduce
> 1. Be an admin with required rights in a supergroup
> 2. Right-click anywhere outside of actual attachments (images, etc.) on a message with a mediagroup, sent by a regular non-admin user
> 3. Select "Delete" from the context menu
> 4. No moderation options appear
> 
> ### Expected behaviour
> Moderation options such as "ban", "report", "delete all messages from" should appear
> 
> ### Actual behaviour
> Regular message deletion popup appears
> 
> ### Operating system
> Ubuntu 23.04, wayland
> 
> ### Version of Telegram Desktop
> 5.1.2
> 
> ### Installation source
> Static binary from official website
> 
> ### Crash ID
> _No response_
> 
> ### Logs
> _No response_
https://github.com/telegramdesktop/tdesktop/issues/28012#issue-2334011358

**Comment by brent85** [comment]
https://github.com/telegramdesktop/tdesktop/issues/28012#issue-2334011358

**Comment by brent85** [comment]
> [#28012 (comment)](https://github.com/telegramdesktop/tdesktop/issues/28012#issue-2334011358)
