### ISSUE TITLE
WebApp doesn't work

### ISSUE THREAD

**Issue by ekleziast** [telegramdesktop/tdesktop#28023]
### Steps to reproduce

1. send http request (source code attached in logs)
2. open any webapp
3. I have windows 10 

![image](https://github.com/telegramdesktop/tdesktop/assets/18170562/290880ac-749a-4fb6-bd80-f81f7d60c137)

**I don't know. Maybe it didn't happen after I tested sending requests, but after I updated Telegram Desktop, I'm not sure.**

### Expected behaviour

webapp works normally

### Actual behaviour

webapp does not work. I can't right click and open the inspector, so it's some kind of limitation in Telegram Desktop.

@wallet
![image](https://github.com/telegramdesktop/tdesktop/assets/18170562/eee2ac9d-849f-4879-a95d-016ba4a03ced)

@xRocket
![image](https://github.com/telegramdesktop/tdesktop/assets/18170562/63a079c6-eb59-4f4b-9ec1-e8370868d5a1)

### Operating system

Windows 10

### Version of Telegram Desktop

5.1.4 x64

### Installation source

Static binary from official website

### Logs

```shell
public async Task<bool> MakeSwap(decimal amount, string currency, int pairId, string type, string jwtBearer)
{

    _httpClient.DefaultRequestHeaders.Clear();
    _httpClient.DefaultRequestHeaders.Add("Authorization", jwtBearer);

    _httpClient.BaseAddress = new Uri("https://private.ton-rocket.com");

    // no need, just to test, but I think WebApp broke after that exact request
    _httpClient.DefaultRequestHeaders.Add("Origin", "https://web.ton-rocket.com");
    _httpClient.DefaultRequestHeaders.Add("Referer", "https://web.ton-rocket.com/");

    var request = new
    {
        amount = amount,
        checkBalance = false,
        currency = currency,
        executeType = "MARKET",
        pairId = pairId,
        rate = 0,
        type = type // BUY or SELL
    };

    using var stringContent = new StringContent(
        JsonSerializer.Serialize(request),
        Encoding.UTF8,
        "application/json");

    using var response = await _httpClient.PostAsync("/orders/order", stringContent, cancellationToken: CancellationToken.None);
    if (!response.IsSuccessStatusCode)
        throw new Exception(await response.Content.ReadAsStringAsync());

    var estimateResponse = JsonSerializer.Deserialize<EstimateResponse>(await response.Content.ReadAsStringAsync());

    return estimateResponse?.Success ?? false;
}
```
I based this query on a query in @xRocket's exchange section in WebApp

**Comment by zdm** [comment]
Same for me.
I have `windows 11`.

**Comment by john-preston** [comment]
@zdm Please update to 5.1.5.

**Comment by ekleziast** [comment]
@john-preston It worked, thanks you!
