### ISSUE TITLE
Change account phone number in web interface 

### ISSUE THREAD

**Issue by 1-0** [telegramdesktop/tdesktop#28028]
### Is your feature request related to a problem?

My smartphone was stolen, so I cannot enter tdesktop  in windows on my notebook. I enter telegram desktop only on Debian on my notebook, but I cannot switch stolen number for my current number. So I suggest creating opportunity to change account phone number in web interface.

### Describe the solution you'd like

I suggest creating opportunity to change account phone number in web interface

### Describe alternatives you've considered

Switch stolen number for my current number on Debian

**Comment by Aokromes** [comment]
this is telegram desktop bug tracker not telegram web bug tracker, you must report to https://bugs.telegram.org
