### ISSUE TITLE
Quote shortcut does not work on Fedora 39

### ISSUE THREAD

**Issue by BANOnotIT** [telegramdesktop/tdesktop#28021]
### Steps to reproduce

1. Open any chat
2. Enter any message
3. Select some words in that message
4. Do `Ctrl + Shift + .`

### Expected behaviour

Selected text is expected to be Quoted now.

### Actual behaviour

Nothing happens. Neither `.` is inserted instead of selected text, nor style is changed

### Operating system

Fedora 39

### Version of Telegram Desktop

5.1.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
https://bugreports.qt.io/browse/QTBUG-125459

**Comment by AndydeCleyre** [comment]
Can't this be kept open, even if it relies on resolution of the Qt issue? I am experiencing this on Pop OS, self-updating version (not flatpak).

**Comment by ilya-fedin** [comment]
No, there's no sense to keep it open. If you have anything related to say, better to say that to Qt developers.
