### ISSUE TITLE
Cannot insert multiple sequential line breaks in Telegram Desktop

### ISSUE THREAD

**Issue by Kelketek** [telegramdesktop/tdesktop#28029]
### Steps to reproduce

1. Install the Ubuntu snap for Telegram
2. Start typing a message
3. Press shift+enter and observe a new line is created

### Expected behaviour

Using shift+enter a second time should create an additional line break, allowing for paragraphs.

### Actual behaviour

If no text is on the current line, an additional line break using shift+enter is not permitted.

### Operating system

Ubuntu 22.04.4 LTS, default desktop environment (Gnome)

### Version of Telegram Desktop

5.0.2

### Installation source

Snap

### Logs

```shell
Every message I send of late seems to be accompanied by this log message:


[2024.06.08 06:01:53] Skipping message, because it is already in blocks!
```
```

**Comment by Aokromes** [comment]
update.

**Comment by Kelketek** [comment]
@Aokromes I have updated. The problem persists.

```
❯ sudo snap refresh                                                                                                                                                ─╯
All snaps up to date.
```

**Comment by Aokromes** [comment]
then snap is oudated, latest version is 5.1.5
