### ISSUE TITLE
No export option in desktop v 5.1.3

### ISSUE THREAD

**Issue by dhowe** [telegramdesktop/tdesktop#28020]
### Steps to reproduce

Open settings, look for 'advanced' section and fail

### Expected behaviour

export chat data

### Actual behaviour

nothing

### Operating system

Os X 11.7.9 (20G1426)

### Version of Telegram Desktop

10.1.1

### Installation source

Static binary from official website

**Comment by dhowe** [comment]
I am using telegram desktop on mac os, as previously stated -- not sure why the version shows up incorrectly.

The installer is called tsetup5.1.3.dmg

**Comment by john-preston** [comment]
@dhowe There are two versions of Telegram on macOS. The one that has the version 10.something is not Telegram Desktop, but another one. If you want to try Telegram Desktop (which has the Export feature) please download tsetup.5.1.3.dmg from https://desktop.telegram.org, unpack it to Applications and launch it from Applications, not some other version.
