### ISSUE TITLE
you can't open this menu with your current system configuration

### ISSUE THREAD

**Issue by DocL1ch** [telegramdesktop/tdesktop#28024]
### Steps to reproduce

After updating Telegram Desktop to version 5.1.4 i can't open any telegram web app. I'm using windows 11.
![Снимок экрана 2024-06-07 093303](https://github.com/telegramdesktop/tdesktop/assets/85258494/68e754cc-1c8e-4b36-bdcd-0c16b441278c)

### Expected behaviour

The web app should be open

### Actual behaviour

I see only the message `Unfortunately, you can't open this menu with your current system configuration`

### Operating system

Windows 11

### Version of Telegram Desktop

5.1.4

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@DocL1ch Fixed in 5.1.5
