### ISSUE TITLE
Telegram crashes when specific jpeg image is attached

### ISSUE THREAD

**Issue by uniconstructor** [telegramdesktop/tdesktop#28036]
### Steps to reproduce

1) download this jpeg: 
[broken-image.zip](https://github.com/user-attachments/files/15774104/broken-image.zip)
2) extract image 
3) Try to attach it to any chat ("Favorites" for example) - select "attach file" and select image from filesystem
4) When upload preview appears make sure that "compress the image" button is checked
![2024-06-10_16-50](https://github.com/telegramdesktop/tdesktop/assets/1384545/055cda50-54b9-405c-b008-e2a3280de84c)

### Expected behavior

Image compressed and attached to chat message

### Actual behavior

Telegram crashes (crash ID: d85c9612-b734-4409-8446e8a0-da5d86a9)

### Operating system

Ubuntu 22.04 LTS

### Version of Telegram Desktop

5.1.4

### Installation source

Static binary from official website

### Crash ID

d85c9612-b734-4409-8446e8a0-da5d86a9

**Comment by uniconstructor** [comment]
Logs from console:
![2024-06-09_19-35_1](https://github.com/telegramdesktop/tdesktop/assets/1384545/ba6d270b-1057-49fe-86a1-46c23b08b14f)

**Comment by ilya-fedin** [comment]
I see it crashed with "IOT instruction" error. How old your hardware is? What's your CPU?

**Comment by uniconstructor** [comment]
Hardware is relatively new. 
My CPU is `Intel® Core™ i7-10750H CPU @ 2.60GHz × 12`

**Comment by ilya-fedin** [comment]
Looks like we have a UB

**Comment by john-preston** [comment]
Please check 5.1.6.
