### ISSUE TITLE
bug mini-app

### ISSUE THREAD

**Issue by tresting** [telegramdesktop/tdesktop#28039]
### Steps to reproduce

start all mini-app

### Expected behaviour

open mini-app

### Actual behaviour

after the latest updates, many mini-apps do not work, or a gray screen, or part of the functionality does not work, this started after any application required Windows 8, despite the fact that it was Windows 10-11

### Operating system

win 10 win 11

### Version of Telegram Desktop

5.1.5x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/27886
