### ISSUE TITLE
make message width resizable

### ISSUE THREAD

**Issue by mb6ockatf** [telegramdesktop/tdesktop#28035]
### Is your feature request related to a problem?

PRs and issues are being ignored: https://github.com/telegramdesktop/tdesktop/issues/1634 https://github.com/telegramdesktop/tdesktop/issues/2060 https://github.com/telegramdesktop/tdesktop/issues/7993 https://github.com/telegramdesktop/tdesktop/issues/8092 | https://github.com/telegramdesktop/tdesktop/pull/2339

### Describe the solution you'd like

implement a checkbox (or whatever, see issues above) for those who seek this feature

### Describe alternatives you've considered

[this](https://aur.archlinux.org/packages/telegram-desktop-wide/) build, but it was removed from aur

**Comment by ilya-fedin** [comment]
> PRs and issues are being ignored

This is false. They all are closed with an answer.
