### ISSUE TITLE
Can't insert two consecutive line breaks in a message

### ISSUE THREAD

**Issue by DenisKuplyakov** [telegramdesktop/tdesktop#28038]
### Steps to reproduce

1. Open any chat
2. Place cursor to message field
3. Type on keyboard `Hello!<ENTER><ENTER><ENTER>Foobar`.

### Expected behaviour

Expect to see in message field the following:

```
Hello!


Foobar
```

### Actual behaviour

You will see:

```
Hello!
Foobar
```

It looks like consecutive line breaks are skipped.

### Operating system

openSUSE Tumbleweed 20240502, KDE Plasma 6.0.4, KDE Frameworks 6.1.0, Qt 6.7.0, X11

### Version of Telegram Desktop

5.0.2

### Installation source

Snap

**Comment by Aokromes** [comment]
update to 5.1.5
