### ISSUE TITLE
Monochrome icon does not apply to KDE plasma in wayland

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#28033]
### Steps to reproduce

- Go to the configuration (Advanced->System integration) and activate “Show tray icon”.

### Expected behaviour

The “Use monochrome icon” option appears, as it does in x11.

### Actual behaviour

Nothing to appear.

If set up in x11 and moved to wayland, it stops appearing and does not apply.

### Operating system

Arch linux (updated, nothing exotic). KDE plasma 6.0.5

### Version of Telegram Desktop

5.1.4

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Perhaps you don't have xdg-desktop-portal-gtk installed?

**Comment by ilya-fedin** [comment]
If you won't have both then gtk applications in flatpak won't get your settings. If you don't want gtk portal then you have to avoid flatpak or accept applications not knowing your settings.
