### ISSUE TITLE
PDFs open in Firefox instead of the set default PDF reader

### ISSUE THREAD

**Issue by Orest58008** [telegramdesktop/tdesktop#28030]
### Steps to reproduce

1. Upload a PDF file
2. Click on it

### Expected behaviour

PDF file opens in Zathura

### Actual behaviour

PDF file opens in Firefox

### Operating system

Arch Linux, sway

### Version of Telegram Desktop

5.1.2-1

### Installation source

Other (unofficial) source

**Comment by Orest58008** [comment]
Everything related to PDF MIME is set to org.pwmt.zathura (`application/pdf`, `text/pdf`, `/pdf` MIME types; `~/.local/share/applications/mimeapps.list`; I've even tried deleting `application/pdf` from MimeType in `firefox.desktop`)

**Comment by ilya-fedin** [comment]
do both xdg-open and `gio open` open Zathura?

**Comment by Orest58008** [comment]
`gio open` opens as it should, `xdg-open` opens in Firefox

**Comment by ilya-fedin** [comment]
then the issue is with your system
