### ISSUE TITLE
Telegram Desktop not updating some channels

### ISSUE THREAD

**Issue by JeffersM1** [telegramdesktop/tdesktop#28045]
### Steps to reproduce

Default Telegram Desktop settings 
Channel messages arriving on Telegram mobile app. 

### Expected behaviour

The Telegram Desktop should update both the messages sent by channel and the unread message counter, whenever new messages arrive on the mobile app. 

### Actual behaviour

The Telegram Desktop does not update both the messages sent by channel and the unread message counter, whenever new messages arrive on the mobile app. 

Closing and relaunching the desktop app causes the app to display new messages for all channels, and the unread message counter to update.  But subsequent channel messages that occur later are not displayed without repeating this action.

Scrolling up through a channel's one or two previous messages, then scrolling down to the bottom of the messages causes the app to display new messages for that channel to update.  But subsequent channel messages that occur later are not displayed without repeating this action.

A similar problem was reported here: https://discourse.flathub.org/t/telegram-desktop-not-updating-some-channels/6622

### Operating system

Ubuntu 22.04 (X86-64), Cinnamon 5.2.7

### Version of Telegram Desktop

5.0.6 

### Installation source

Snap

**Comment by a15mni** [comment]
having similar problem on windows 10 ver. 5.1.5

**Comment by DddVvv7** [comment]
Confirm. Channels are not updated. There are no notifications. Telegram Portable Desktop 5.1.5 x64. Win10.

**Comment by MSxDOS** [comment]
https://github.com/telegramdesktop/tdesktop/issues/28037

**Comment by DddVvv7** [comment]
Telegram Desktop 5.1.6, not fixed.

**Comment by john-preston** [comment]
Hi. I'll need debug logs to check on this one. To enable collection of debug logs please:

1. Open Main Menu -> Settings
2. Type from the keyboard "debugmode", like a cheat code in a game
3. Agree to enabling debug logs
4. Reproduce the issue (have a new message in one of your channels not appear in the chats list for some time, like, ten minutes, and then open the channel and see that it appeared there instantly)
5. Please collect several screenshots - (a) the channel in the chats list before opening it (so the old message is shown there and you know that a new message should be there for already ten minutes), (b) the channel in the chats list and the channel history after you open it and the new message is shown both in chats list and channel history.
6. Write another cheat code in Settings, "viewlogs", it will open folder with DebugLogs folder.
7. Quit the app completely using Ctrl+Q
8. .zip the DebugLogs folder and send it to me at https://t.me/preston along with the screenshots from (5)

Be aware that all network activity is recorded in debug logs, don't share them publicly.

**Comment by To-Azamat** [comment]
5.1.7, seeing the same behaviour - channels stop updating in Desktop while updating normally on iPhone.

**Comment by LostTeg** [comment]
Same

**Comment by mazurd** [comment]
Same issue (NOT Fixed) Telegram desktop 5.2.2 x64

**Comment by JeffersM1** [comment]
After installing Telegram Desktop 5.1.7 Stable for Linux x64, the problem seems to have gone away.

**Comment by bv-it** [comment]
Какая версия сейчас точно рабочая? (В последней версии глючит обновления сообщений в каналах). Сейчас приходится постоянно перезапускать приложение

**Comment by DddVvv7** [comment]
> Какая версия windows сейчас точно рабочая? (В последней версии глючит обновления сообщений в каналах). Сейчас приходится постоянно перезапускать приложение

Никакая, это проблема серверной части, а не приложения, но разрабам не до этого, потому что Пашке кортизольщику нужно, чтобы ты с утра до вечера пальцем в тыкалках шкрябал, а не мессаги читал))
