### ISSUE TITLE
text overlay the time

### ISSUE THREAD

**Issue by itmehr** [telegramdesktop/tdesktop#28041]
### Steps to reproduce

![image](https://github.com/telegramdesktop/tdesktop/assets/24986586/fb77caec-3d2d-44c0-a168-047796eed43d)
![image](https://github.com/telegramdesktop/tdesktop/assets/24986586/03c97a41-3481-47ed-bf39-adf72c16c5ac)

### Expected behaviour

-

### Actual behaviour

-

### Operating system

windows 11 x64 build 22621.3672

### Version of Telegram Desktop

5.1.5 x64 

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I cannot reproduce that :( I guess I'll need the exact text of the caption and exact images, in .zip format, so that I could reproduce that myself. Or a link to a channel where this can be observed.
