### ISSUE TITLE
Telegram stopped automatically updating news chats and showing the number of unread messages,

### ISSUE THREAD

**Issue by stepanovich202** [telegramdesktop/tdesktop#28049]
### Steps to reproduce

When you start the client, there is a request to update information in each channel with information about the number of unread news. And there are no more requests to update information. When entering any channel, a request occurs and moves to the very bottom of the window and it is impossible to understand what has been read and what has not. Replacing the version with an earlier one does not lead to positive results. The problem began on June 5-6 of this year.

### Expected behaviour

Телеграм должен в автоматическом режыме обновлять информацию в каждом канале и показывать количество не прочитанных сообщений.

### Actual behaviour

Telegram перестал автоматически обновлять новостные чаты и показывать количество непрочитанных сообщений,

### Operating system

windows 7 sp 1

### Version of Telegram Desktop

5.1.5 , 5.1.6

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
duplicate. i don't go to link

**Comment by john-preston** [comment]
Hi. I'll need debug logs to check on this one. To enable collection of debug logs please:

1. Open Main Menu -> Settings
2. Type from the keyboard "debugmode", like a cheat code in a game
3. Agree to enabling debug logs
4. Reproduce the issue (have a new message in one of your channels not appear in the chats list for some time, like, ten minutes, and then open the channel and see that it appeared there instantly)
5. Please collect several screenshots - (a) the channel in the chats list before opening it (so the old message is shown there and you know that a new message should be there for already ten minutes), (b) the channel in the chats list and the channel history after you open it and the new message is shown both in chats list and channel history.
6. Write another cheat code in Settings, "viewlogs", it will open folder with DebugLogs folder.
7. Quit the app completely using Ctrl+Q
8. .zip the DebugLogs folder and send it to me at https://t.me/preston along with the screenshots from (5)

Be aware that all network activity is recorded in debug logs, don't share them publicly.
