### ISSUE TITLE
Telegram Desktop does not show any new posts in a channel

### ISSUE THREAD

**Issue by clifftm** [telegramdesktop/tdesktop#28055]
### Steps to reproduce

1. After restarting the Telegram, the channels, including the number of unread posts, are displayed in the left column
2. When I've read all the posts, the number is gone, shows that there are no new posts available
3. Now I expect that as soon as new posts appear, the number will increase
4. To read new posts, I have to click on each channel. It seems that Telegram is only now looking for new posts.
5. Some channels sometimes show the updates (including the number) at the top of the list, BUT this happens very rarely.

Reinstalling and relogin doesn't help.

### Expected behaviour

Badge counter should increment as new posts appear

### Actual behaviour

To read new posts, I have to click on each channel

### Operating system

Windows 11 23H2

### Version of Telegram Desktop

5.1.17

### Installation source

Static binary from official website

### Logs

```shell
[2024.06.16 15:47:11] OpenGL: QOpenGLContext created, version: 3.3.
[2024.06.16 15:47:11] OpenGL: [TRUE] (Window)
[2024.06.16 15:47:13] RPC Error: request 54 got fail with code 400, error PEER_ID_INVALID
[2024.06.16 15:55:43] Skipping message, because it is already in blocks!
[2024.06.16 15:55:44] Skipping message, because it is already in blocks!
[2024.06.16 15:56:30] API Warning: not loaded minimal channel applied.
[2024.06.16 15:56:30] API Warning: not loaded minimal channel applied.
[2024.06.16 15:57:45] API Warning: not loaded minimal channel applied.
```

**Comment by MSxDOS** [comment]
https://github.com/telegramdesktop/tdesktop/issues/28037

**Comment by vamp1r7771** [comment]
Is anyone going to fix this problem?

**Comment by clifftm** [comment]
Seems they won't as its a "server bug". Much easier to redirect all users to https://bugs.telegram.org/c/41247 . As i see the problem is increasing but very slow, a most common users don't have it, so the fix will be delayed for years

**Comment by vamp1r7771** [comment]
That's fucked up, man, they just don't care

**Comment by web-lite** [comment]
I have the same problem.
Telegram Desktop is installed on the computer, after the latest updates, notifications from channels have stopped being displayed, there are no icons for new messages either. 
This happens after the application has been running on the computer for a short time. 
After the program is completely restarted, notifications are displayed. But after a while they stop being displayed again.
It feels like the channels are disconnected from the Internet, and all notifications are displayed normally on the smartphone.
Channel notifications are enabled on all devices.
