### ISSUE TITLE
Search widget randomly steals focus

### ISSUE THREAD

**Issue by reallyuniquename** [telegramdesktop/tdesktop#28052]
### Steps to reproduce

1. Open a group chat by following a t.me link or using ︙ → View Discussion. **You must not be a member of that group.**

2. Click on any picture or a video.

3. Click again to close a media viewer.

Another case.

1. Open a group chat by following a t.me link or using ︙ → View Discussion. **You must not be a member of that group.**

2. Minimize Telegram app.

3. Maximize Telegram app.

### Expected behaviour

Nothing should happen.

### Actual behaviour

Search field takes focus and search widget is opened.

### Operating system

Windows 10

### Version of Telegram Desktop

5.1.7

### Installation source

Static binary from official website

### Logs

If I close search widget with an X it stops taking focus until I visit the group again. 

I can't always reproduce this but I do encounter this quite often. That's been an issue for a while now.

**Comment by john-preston** [comment]
@reallyuniquename Thanks! I can reproduce both.
