### ISSUE TITLE
Telegram desktop does not automatically check for channel updates

### ISSUE THREAD

**Issue by Mahdi-zarei** [telegramdesktop/tdesktop#28057]
### Steps to reproduce

No particular step is needed. Just join a few channels.

### Expected behaviour

I have joined a few channels on telegram, and up until some months ago the telegram desktop was working correctly and was updating the channels just the same as other clients.

### Actual behaviour

At the point, when channels publish a message telegram desktop does not do anything, and only when i click on those channels suddenly the new messages are loaded. Also if i exit telegram desktop and open it again the messages are loaded. so practically i need to manually check for new messages in channels by opening their respective chats.

### Operating system

Windows 11 23H2

### Version of Telegram Desktop

v5.1.7 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
duplicate.
