### ISSUE TITLE
Add shortcut for rotate video

### ISSUE THREAD

**Issue by zjplab** [telegramdesktop/tdesktop#28053]
### Is your feature request related to a problem?

In the media player window, we have play, pause, zoom(alt+enter) and rotate, among with many other functions. But for commonly used rotate function, there is no short associated with. 

### Describe the solution you'd like

Adding shortcut for rotating will be nice. Or better, develop a mapping config that can let you control which key maps to which function/button. 

### Describe alternatives you've considered

na

**Comment by ilya-fedin** [comment]
> Or better, develop a mapping config that can let you control which key maps to which function/button.

it already exists in tdata directory

**Comment by Aokromes** [comment]
i think he means with a GUI xd

**Comment by zjplab** [comment]
@ilya-fedin @Aokromes  I mean guess the rotate screen `playbackControlsRotate()` function? And there is very limited command registered in https://github.com/telegramdesktop/tdesktop/blob/4047f1733decd5edf96d125589f128758b68d922/Telegram/SourceFiles/core/shortcuts.cpp#L395. It's hardcoded in the code also, not being able to let users decide the keymap.

**Comment by ilya-fedin** [comment]
@zjplab it's not hardcoded, there's a json file tdata as I already said. You see the, function is called "fillDefault".
