### ISSUE TITLE
[Feature Request] Add an option to hide the "Buy premium to increase speed" pop-up notification.

### ISSUE THREAD

**Issue by Hobbix** [telegramdesktop/tdesktop#28050]
### Is your feature request related to a problem?

Add an option to hide the "Buy premium to increase speed" pop-up notification.
When we scroll through the feed, an annoying notification often pops up offering to buy premium.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
but for sure your request will be rejected.
