### ISSUE TITLE
No animation for emoji with random outcome

### ISSUE THREAD

**Issue by Artem13327** [telegramdesktop/tdesktop#28061]
### Steps to reproduce

1. Send an emoji that has a random outcome

### Expected behaviour

There must be animation

### Actual behaviour

No animation

### Operating system

Linux, Xfce 4.18

### Version of Telegram Desktop

5.1.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Please provide a screen record of the issue

**Comment by hamedhdd** [comment]
output animation depends on OS power management and hardware, the situations are not equal, you need to provide more information
