### ISSUE TITLE
android-client： new edited txt file saved to download but is old file

### ISSUE THREAD

**Issue by zedweein** [telegramdesktop/tdesktop#28067]
### Steps to reproduce

1、send a new edited txt file to chat
2、saved to download

### Expected behaviour

expected download is new file rather than not edited old file

### Actual behaviour

saved to download is old txt file not edited

### Operating system

android 14

### Version of Telegram Desktop

v10.13.3（4854）

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
Sorry but this is telegram desktop bug tracker, nothing here belongs to android. android requests belongs to https://bugs.telegram.org/

**Comment by zedweein** [comment]
tks！
