### ISSUE TITLE
Windows ARM version

### ISSUE THREAD

**Issue by tomcoleman** [telegramdesktop/tdesktop#28070]
### Is your feature request related to a problem?

I have been asking for a ARM version since 2020 with no updates or replies.

With snapdragon and ARM coming more into mainstream - when will a ARM version be released?

https://github.com/telegramdesktop/tdesktop/issues/7173

### Describe the solution you'd like

ARM version of telegram desktop

### Describe alternatives you've considered

i have been using x64 but this isnt native and runs through an emulator so drains the battery

**Comment by Aokromes** [comment]
i don't think you will see that, there is no qt6 version for windows 10 or higher, i doub you will see arm version (nor risc-v)

**Comment by ilya-fedin** [comment]
dup of #25266?

**Comment by NicolasOchoaMSFT** [comment]
> @tomcoleman I'm slooowly looking that way, making some experiments from time to time. It's not on the priority list for now, so no time frames, sorry..

@john-prestonI am Nicolas Ochoa, our Microsoft App Assure team would be happy to arrange a conversation with an Arm developer support engineer who can provide guidance and recommendations to develop Telegram for Windows on Arm. We could also send hardware for testing and development if that would help.

**Comment by CryptoManiac** [comment]
> > @tomcoleman I'm slooowly looking that way, making some experiments from time to time. It's not on the priority list for now, so no time frames, sorry..
> 
> 
> 
> @john-prestonI am Nicolas Ochoa, our Microsoft App Assure team would be happy to arrange a conversation with an Arm developer support engineer who can provide guidance and recommendations to develop Telegram for Windows on Arm. We could also send hardware for testing and development if that would help.

No special hardware is needed, the raspberry pi will do. It's slow but more than enough for testing.

**Comment by john-preston** [comment]
@NicolasOchoaMSFT Hi. I'm the Arm developer support engineer (as well as other things engineer), so you can contact me, here or on Telegram at https://t.me/preston

Speaking hardware I have MacBook M3 Max that has Windows on Arm installed in Parallels with Visual Studio and stuff. I started looking into building dependencies natively and on my first try I couldn't get past msys2 that should build FFmpeg and libvpx for me :) I plan giving it another try later.

**Comment by john-preston** [comment]
@NicolasOchoaMSFT I've left my thoughts about building tdesktop for arm in the relevant open issue #25266

**Comment by john-preston** [comment]
I'll just lock this one so that discussion stays in one place.
