### ISSUE TITLE
[SECURITY] Linking your entire userbase to a huge, uncontrollable group chat is a BAD IDEA.

### ISSUE THREAD

**Issue by VixusFoxy** [telegramdesktop/tdesktop#2807]
I'm not so sure that linking to "[@TelegramThemes](https://t.me/TelegramThemes)" in the release notes was such a good idea.
Brilliant idea whomever did that.

Easy way for malicious people to spread their payloads, too.

![Image](http://vixus.nl/o5052_chrome_011217-0625.jpg)

**Comment by Joaquin-V** [comment]
I personally would've preferred a channel rather than a supergroup

**Comment by DarthJahus** [comment]
And thanks to Telegram's amazing moderation tools, that huge supergroup will stay safe and quiet.

**Comment by NateMS** [comment]
This is just ridiculous. What was the expected result? Linking all of the people to the same chat will only give you what is shown in the screenshot, plus it's not exactly keeping the privacy of the users.
