### ISSUE TITLE
Feedback about the blacklist

### ISSUE THREAD

**Issue by sakurayz** [telegramdesktop/tdesktop#28072]
### Is your feature request related to a problem?

For example, if user B is in the blacklist of user A, user B can see the account name of user A. If user A changes the account name, user B can still see the new account name of user A, which is not completely prohibited by this blacklist function.

In another case, User B is in the blacklist of User A, and User B has the mobile phone number of User A. If user A cancels the TG account and registers a new TG account with this mobile number, then everyone who has the mobile number of user A will receive a reminder that the new user joins Telegarm, which is not conducive to privacy, and it is uncertain whether user B will receive the reminder.

### Describe the solution you'd like

Strengthen the blacklist function, so that the blocked person can not find contact information at all。

### Describe alternatives you've considered

I haven't thought of any other backup yet

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
