### ISSUE TITLE
Arch linux telegram-desktop crash when video chat

### ISSUE THREAD

**Issue by adxamjon97** [telegramdesktop/tdesktop#28078]
### Steps to reproduce

when open voice and video chat crashed

### Expected behaviour

I got log

### Actual behaviour

crashed 

### Operating system

arch linux

### Version of Telegram Desktop

5.1.7

### Installation source

Other (unofficial) source

### Crash ID

1

### Logs

```shell
[adxamjon@adxamjon-laptop ~]$ telegram-desktop 
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.svg: Error while inflating gzip file: SVG format check failed
...
qt.svg: Error while inflating gzip file: SVG format check failed
qt.gui.imageio.jpeg: Corrupt JPEG data: premature end of data segment
qt.svg: Error while inflating gzip file: SVG format check failed
...
qt.svg: Error while inflating gzip file: SVG format check failed


#
# Fatal error in: /usr/src/debug/libtg_owt/tg_owt/src/modules/video_coding/codecs/h264/h264_decoder_impl.cc, line 83
# last system error: 1
# Check failed: pixelFormatSupported != kPixelFormatsSupported.end()
# Аварийный останов (образ памяти сброшен на диск)
```

**Comment by ilya-fedin** [comment]
Are you sure this is not a packaging bug? Have you checked with the official build (from https://desktop.telegram.org)?

**Comment by adxamjon97** [comment]
> Are you sure this is not a packaging bug? Have you checked with the official build from https://desktop.telegram.org?

I installed this with sudo pacman -Syu

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
> I installed this with sudo pacman -Syu

That's not what I asked. Please answer the questions I asked.

**Comment by adxamjon97** [comment]
> > I installed this with sudo pacman -Syu
> 
> That's not what I asked. Please answer the questions I asked.

**Comment by adxamjon97** [comment]
It seems my ssd hard drive is full

**Comment by k1gen** [comment]
why was this closed? I have the same issue

**Comment by Aokromes** [comment]
> why was this closed? I have the same issue. statically compiled tgd works fine

because user had full hdd, also, if it's distribution package crash it must be reported to arch.

**Comment by ilya-fedin** [comment]
> why was this closed?

No one has proofed this is a tdesktop bug rather than a packaging bug.

**Comment by nikalexey** [comment]
I have the same problem after upgrading from 5.1.5 to 5.1.7
I uninstalled telegram-desktop from extra and installed telegram-desktop-bin from aur and everything worked fine.

**Comment by ilolm** [comment]
I have the same problem in arch hyprland 6.9.8 kernel and nvidia 555.58.02

**Comment by guipure** [comment]
I have the same problem after upgrading from 5.1.5 to 5.2.3

**Comment by krepkay** [comment]
Same here.
Latest EndeavourOS (Kernel: 6.10.2-arch1-1)
```
pacman -Ss telegram-desktop
extra/telegram-desktop 5.2.3-2 [installed]
    Official Telegram Desktop client
```

**Comment by Aokromes** [comment]
> Same here. Latest EndeavourOS (Kernel: 6.10.2-arch1-1)
> 
> ```
> pacman -Ss telegram-desktop
> extra/telegram-desktop 5.2.3-2 [installed]
>     Official Telegram Desktop client
> ```

this ain't telegram desktop official package.
