### ISSUE TITLE
telegram logs out every few min after i login

### ISSUE THREAD

**Issue by furllmm** [telegramdesktop/tdesktop#28073]
### Steps to reproduce

1. i logged in with my mom's phone number
2. closed the app and passed few min
3. after re opening in both pc and android version its logged out already

### Expected behaviour

-

### Actual behaviour

keeps logged out every few min (same as title

### Operating system

windows 11 

### Version of Telegram Desktop

latest

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by furllmm** [comment]
when its fixes?

**Comment by furllmm** [comment]
when its fixes? @Aokromes

**Comment by furllmm** [comment]
any estimate?

**Comment by Aokromes** [comment]
your problem doesn't belong to this bug tracker.

**Comment by furllmm** [comment]
then how can i fix?
