### ISSUE TITLE
No way to send video "as file", i.e. as-is with no re-encoding

### ISSUE THREAD

**Issue by php4fan** [telegramdesktop/tdesktop#28075]
### Steps to reproduce

When you send an image, you can choose whether to compress it or not:

![image](https://github.com/telegramdesktop/tdesktop/assets/13969584/a596cad8-a8cd-45fe-82a1-b326992c143c)

**For videos, there is no such option:**

![image](https://github.com/telegramdesktop/tdesktop/assets/13969584/242a8d76-ada9-43b4-ae48-5e1a240e1272)

I'm not sure if Telegram always recompresses the videos or only in some cases, but it definitely does (re)compress them in some cases, and the user has no control on it.

Note that **in the mobile app, it is possible** to send a video without re-compression. The UI is completely different, but when you click the clip icon to upload, there is a submenu to choose the type of file, the options being "Gallery", "Video", "Location" and more. If you choose File and then pick an image or video, it is sent as-is, with no further compression or transcoding. It might not be the most intuitive and explicit interface design (and it definitely wouldn't be the right design for desktop), but it does allow you to decide how to send the file.

A sensible interface to have on Desktop would be the same for video as it currently is for images, with a "compress videos" checkbox.

To reproduce:
1. click the clip icon to send a file to a chat
2. select a video file

### Expected behaviour

should offer a "compress videos" checkbox, and ideally also a "remember my choice" like it does for images

### Actual behaviour

There is no such checkbox, Telegram decides what to do with the file

### Operating system

Manjaro Linux

### Version of Telegram Desktop

5.1.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop unlike tandroid doesn't have re-encoding capabilities. That's one of the reasons you can't record circles, stories and etc, etc.

**Comment by php4fan** [comment]
I thought the re-encoding was done by the server, or both. So any video you send from Telegram Desktop is guaranteed to be received as-is?

**Comment by ilya-fedin** [comment]
> I thought the re-encoding was done by the server, or both.

As far as I know it's purely client-side. It's too expensive to do that server-side.

> So any video you send from Telegram Desktop is guaranteed to be received as-is?

Yes.
