### ISSUE TITLE
Content in Telegram chat is not adapting to high contrast themes.

### ISSUE THREAD

**Issue by msftedad** [telegramdesktop/tdesktop#28089]
### Steps to reproduce

1. Open Telegram App in Desktop.
2. Open URL: Telegram: Contact @SCTejTestbot on search filed.
3. SCTestbot home screen will appear.
4. Apply Contrast Themes Aquatic and Desert theme.
5. Observe that Content in Telegram chat is not adapting to high contrast themes.

### Expected behaviour

Content in Telegram chat should be adapting to high contrast themes.

### Actual behaviour

Content in Telegram chat is not adapting to high contrast themes.

https://github.com/telegramdesktop/tdesktop/assets/93735775/b51a3e01-d540-4983-a0a8-68c40c375128

### Operating system

23H2 (22631.3296)

### Version of Telegram Desktop

4.16.4

### Installation source

Microsoft Store

**Comment by ilya-fedin** [comment]
tdesktop needs help with code, not with issues... there's already plenty much issues about accessibility and whatnot, no need to create more...
