### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by bertmsk** [telegramdesktop/tdesktop#2808]
### Steps to reproduce
1. Collect images from chats that total size is over 2G
2. profit!
3. 

### Expected behaviour
Tell us what should happen
Positive local storage images size. Use *unsigned* uint32_t or uint64_t for size counter

### Actual behaviour
Negative size

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.0
![untitled-2](https://cloud.githubusercontent.com/assets/10155479/21881996/a41acae2-d8b9-11e6-98b8-bdcc641d2b63.jpg)

**Comment by stek29** [comment]
#2244 duplicate
