### ISSUE TITLE
Most formatting keyboard shortcuts have no effect

### ISSUE THREAD

**Issue by AndydeCleyre** [telegramdesktop/tdesktop#28084]
### Steps to reproduce

1. Enter text in an outgoing message and highlight it
2. Try keyboard shortcuts for the following format operations:

- bold (ctrl b)
- monospace (ctrl shift m)
- italic (ctrl i)
- quote (ctrl shift .)
- strikethrough (ctrl shift x)
- clear formatting (ctrl shift n)

### Expected behaviour

The text takes on the respective formatting associated with each keyboard shortcut

### Actual behaviour

No visible effect, before or after sending the text

### Operating system

Pop!_OS 22.04 LTS, Plasma

### Version of Telegram Desktop

5.1.7

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I can't reproduce, works just fine for me
https://github.com/telegramdesktop/tdesktop/assets/17829319/e5f66d5e-a8dc-4824-88b9-a4f5c2eee337

**Comment by AndydeCleyre** [comment]
Oh, I have the theme font set to system font -- can you try that?

**Comment by ilya-fedin** [comment]
No, still can't reproduce.

**Comment by AndydeCleyre** [comment]
If I run from terminal, using *some* of those shortcuts *twice in a row* yields ambiguous shortcut events:

```
QAction::event: Ambiguous shortcut overload: Ctrl+B
QAction::event: Ambiguous shortcut overload: Ctrl+Shift+M
QAction::event: Ambiguous shortcut overload: Ctrl+I
QAction::event: Ambiguous shortcut overload: Ctrl+Shift+.
QAction::event: Ambiguous shortcut overload: Ctrl+Shift+X
QAction::event: Ambiguous shortcut overload: Ctrl+Shift+N
```

**Comment by ilya-fedin** [comment]
Maybe you have global menu?

**Comment by AndydeCleyre** [comment]
Yes, I do. Is there a known issue related to that?

**Comment by ilya-fedin** [comment]
No but global menu provides input field items and has the same shortcuts set so they're displayed in the menu items.

**Comment by AndydeCleyre** [comment]
FWIW I confirmed the problem persists when using default font as well.

**Comment by AndydeCleyre** [comment]
I tried downgrading to 5.1.6, which also resulted in all settings being reset, but the problem persisted.

**Comment by ilya-fedin** [comment]
Perhaps this is related to your system settings, then. Spawning a VM and configuring it like your host system step-by-step could help with finding the cause.

**Comment by ilya-fedin** [comment]
I reproduced it with global menu.
