### ISSUE TITLE
Other reactions unavailable on Windows desktop version

### ISSUE THREAD

**Issue by menty666** [telegramdesktop/tdesktop#28087]
### Steps to reproduce

1. Mouse over a message
2. Click the reaction icon
3. Note the lack of scrollbar to access other emojis

### Expected behaviour

On the Android version, a horizontal bar appears allowing more choices for emoji reactions.   Either the same or a scrollable/expandable picker should appear

### Actual behaviour

Instead we see this a vertical picker that can't scroll to other emojis: 

![image](https://github.com/telegramdesktop/tdesktop/assets/8901000/5b97effb-a741-4401-979d-3dc4786f334e)

### Operating system

Windows 10

### Version of Telegram Desktop

5.1.7 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
it's scrollable, use mouse whell.
