### ISSUE TITLE
Floating menu like 'Select' or 'Emoji picker' is broken

### ISSUE THREAD

**Issue by Serpentarius13** [telegramdesktop/tdesktop#28094]
### Steps to reproduce

1. Open floating menu, it should open
2. Try opening it second time, it will close right after opening without any possibility to click it
3. Keyboard will be broken from now on, and menu won't open

### Expected behaviour

Opening menu shouldn't break anything and it should open

### Actual behaviour

Menu breaks keyboard and it doesnt open after second attempt at opening it. Although, it works when I open it with terminal, but breaks with using sway-launcher-desktop, fuzzel or sway exec

### Operating system

Arch Linux, Wayland, Sway

### Version of Telegram Desktop

5.1.7-3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
I can't reproduce, works just fine
https://github.com/telegramdesktop/tdesktop/assets/17829319/f07933e6-a2fb-4d78-8ffe-55c4c0e25483

**Comment by ilya-fedin** [comment]
> ### Version of Telegram Desktop
> 
> 5.1.7-3
> ### Installation source
> 
> Static binary from official website

This also doesn't sound like truth - the version from official website has no -3 postfix

**Comment by Serpentarius13** [comment]
> > ### Version of Telegram Desktop
> > 5.1.7-3
> > ### Installation source
> > Static binary from official website
> 
> This also doesn't sound like truth - the version from official website has no -3 postfix

I thought pacman -S visual-studio-code-bin is a static binary since it is an upstream pacman package. I will try downloading binary from website and will give you a reply, thank you

**Comment by ilya-fedin** [comment]
No, Telegram doesn't maintain any distro packages, all of them are downstream.

**Comment by Serpentarius13** [comment]
> No, Telegram doesn't maintain any distro packages, all of them are downstream.

Yes, this bug persists only in their repo. Thank you
