### ISSUE TITLE
Enable titlebar on Telegram Cllas

### ISSUE THREAD

**Issue by xxfogs** [telegramdesktop/tdesktop#28092]
### Is your feature request related to a problem?

Lack of a titlebar on Telegram calls prevents me from using GNOME windowing system functionality such as "Always on top", "Always on visible workspace", etc.

### Describe the solution you'd like

Add a titlebar to Telegram calls (custom and optionally with the ability to enable system frame)

### Describe alternatives you've considered

I don't see any other sufficient alternatives, as that is the best way to resolve any issues related to a lack of said titlebar

**Comment by ilya-fedin** [comment]
In general, dup of #10002.

> Lack of a titlebar on Telegram calls prevents me from using GNOME windowing system functionality such as "Always on top", "Always on visible workspace", etc.

But this issue isn't really related to titlebar so you can open a separate issue for that. I also believe you can access this functionality via system shortcuts.

**Comment by xxfogs** [comment]
Oh, didn't notice it when searching for similar open issues. Thanks.
