### ISSUE TITLE
Polls in channels are not translated

### ISSUE THREAD

**Issue by AlexWayfer** [telegramdesktop/tdesktop#28096]
### Steps to reproduce

1. Open a channel.
2. See a poll.
3. Have Telegram Premium.
4. Press "Translate".

### Expected behaviour

Polls should be translated.

### Actual behaviour

Polls are not translated.

![image](https://github.com/telegramdesktop/tdesktop/assets/6510020/e8c7987d-8bdc-4b0a-81b7-f10a88c45a52)

### Operating system

Windows 11

### Version of Telegram Desktop

5.1.7 x86

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
it looks to be server side issue, on android it also fails to translate.
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by AlexWayfer** [comment]
OK, thanks, I thought it could be client-related.

Created: https://bugs.telegram.org/c/41376
