### ISSUE TITLE
Linux on share screen (receiver) crash (tested on Hyperland and i3wm)

### ISSUE THREAD

**Issue by P1R** [telegramdesktop/tdesktop#28091]
### Steps to reproduce

1.  have a call with someone.
2.  share the screen.
3.  client that receives the shared screen (on linux) crashes.

### Expected behaviour

be able to see the shared screen

### Actual behaviour

the telegram client who receives the screen crashes

### Operating system

linux

### Version of Telegram Desktop

5.1.7

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by ilya-fedin** [comment]
@Aokromes you can close it, we know there's no such issue on official builds
