### ISSUE TITLE
Allow users to toggle the visibility of stickers

### ISSUE THREAD

**Issue by StevenStavrakis** [telegramdesktop/tdesktop#28095]
### Is your feature request related to a problem?

Problem:

Stickers often take up a lot of space in the UI and can clutter chats, leading to users disengaging with the chats due to other unruly users. Moderating chats for sticker use is not a viable option for obvious reasons. Since stickers can often fail to convey meaning, it should be possible to disable seeing them.

Currently, there is a setting to disable animated stickers, but there should be an option to disable stickers in their entirety.

### Describe the solution you'd like

User settings that allow the user to choose whether or not stickers are visible to them. If the user decides not to see stickers, they can show the emoji corresponding to the sticker, which is visible in the chat preview. The idea is to minimize UI clutter and improve the group chat experience while allowing users who opt in to stickers the freedom to use stickers as they would like. The idea is to minimize UI clutter and improve the group chat experience while allowing users who opt in to stickers the freedom to use stickers as they would like.

### Describe alternatives you've considered

Disabling stickers for the chat outright is not a good solution, as some users would like to use and see stickers within the chat. It seems to be the best option at present.

### Additional context

Example of chat preview in question:

<img width="291" alt="image" src="https://github.com/telegramdesktop/tdesktop/assets/35231833/4adc432e-6f04-4234-9dd6-6df20ba64b0f">

**Comment by ilya-fedin** [comment]
#6999?

**Comment by StevenStavrakis** [comment]
Ok, #26967 was marked as resolved, but I've checked the UI, and there is only an option for that if I'm missing it.

If this is an option, it's not exactly obvious how to find it.

**Comment by ilya-fedin** [comment]
It's closed as a dup of #6999. And your one looks like a dup just as well.

**Comment by StevenStavrakis** [comment]
I think the important difference here is that I want to capitalize on the
already existing "toggle animated stickers" and expand it to toggle
stickers entirely.
