### ISSUE TITLE
Telegram does not translate post polls!

### ISSUE THREAD

**Issue by alirezarezamand** [telegramdesktop/tdesktop#28099]
### Is your feature request related to a problem?

When I translate the content of the channel using Telegram to my desired language, the polls are not translated!

### Describe the solution you'd like

When Telegram translates the content of the channel, it should also translate the survey.

### Describe alternatives you've considered

When Telegram translates the content of the channel, it should also translate the survey.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/28096#issuecomment-2198516560
