### ISSUE TITLE
Linux: Clipboard hotkeys on russian layout

### ISSUE THREAD

**Issue by Hacker-CB** [telegramdesktop/tdesktop#281]
CTRL-C/CTRL-V hotkeys does not work in russian keyboard layout.
Ubuntu 14.10

**Comment by ezdev128** [comment]
The same for LMDE (Linux Mint Debian Edition).

**Comment by evgenymarkov** [comment]
+1 Fedora 21, Gnome 3.14
Please fix hotkeys!

**Comment by Katzen-Gott** [comment]
Looks like it's fixed since v 0.7.14 dev (12.02.15). Please check.

**Comment by ezdev128** [comment]
Fixed. Works at current release (0.7.17).
Thanks!

**Comment by Katzen-Gott** [comment]
@Hacker-CB could you please check if it works for you and close the issue?

**Comment by Hacker-CB** [comment]
Now its work. Thank you.
