### ISSUE TITLE
Crash when opening different media windows

### ISSUE THREAD

**Issue by joporoja** [telegramdesktop/tdesktop#28104]
### Steps to reproduce

1. Open a video in a popup window w/o borders
2. Open another video in the same window
3. Open a photo or a gif file while popup video is present

### Expected behaviour

App should open photos or gifs underneath a popup video

### Actual behaviour

App crashes

### Operating system

Windows 10 x64

### Version of Telegram Desktop

5.2 x64

### Installation source

Static binary from official website

### Crash ID

aeb39b18-7791-47bc-a373-1924714ace65

**Comment by john-preston** [comment]
@qxtalk Thanks. This is a different problem, I've fixed it in code and soon I'll deploy a new 5.2.1 version with the fix.

**Comment by john-preston** [comment]
@joporoja Thanks!
