### ISSUE TITLE
Crash when opening forum topic in a separate window

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#28100]
### Steps to reproduce

1. Right click on a forum topic
2. Select Open in new window

### Expected behaviour

Topic opens in a new window

### Actual behaviour

Crash

### Operating system

Windows 11

### Version of Telegram Desktop

5.2

### Installation source

Static binary from official website

### Crash ID

2be8cc1b-e636-4011-b6e6-c73a9090967a

**Comment by john-preston** [comment]
Ctrl+Click works :) Fixed in code for the context menu as well. Thanks!
