### ISSUE TITLE
'Media viewer' window fails to remember to be in fullscreen mode.

### ISSUE THREAD

**Issue by Tynach** [telegramdesktop/tdesktop#28101]
### Steps to reproduce

1. Open up a group, channel, or personal chat that has had an image file, gif, or video posted in it.
2. Click one of the images, gifs, or videos to open the 'Media viewer' window.
3. It might currently be in fullscreen mode, to reset when it had last been set to fullscreen mode, click the 'Maximize'/'Restore' button once or twice.

    Basically, bring it out of fullscreen mode and then put it back into fullscreen mode. If it was already in fullscreen mode, click the button twice to bring it out and put it back into fullscreen mode. If it is in windowed mode, just click it once to put it into fullscreen mode.

    **Note**: fullscreen mode is different from being maximized; in KDE, I can drag a window to the top of the screen to maximize it, and this behaves differently for the 'Media viewer' window than when I click it's 'maximize' button. Not too important though, and this bug report is *not* about that.
4. Click somewhere in the window, or click the 'x' in the top right corner, to close it.
5. Once more, open the media (the same one, or a different one, does not matter). The 'Media viewer' will correctly be in fullscreen mode.
6. Click somewhere in the window, or click the 'x' in the top right corner, to close it.
7. Finally, one more time, open some form of media. The 'Media viewer' window will now *incorrectly* be in windowed mode. Closing it and re-opening it will continue to bring it up in windowed mode, even though the last time I had chosen which way to have it, I had put it into fullscreen mode.

### Expected behaviour

I was bored and happened to have explored the intended behavior just yesterday, before updating today to 5.2. The 'Media viewer' window would correctly remember wherever I had placed it last, and whether it was in fullscreen mode or not, and continue to always use the last state I put it in whenever I opened an image.

### Actual behaviour

Window position and size seem to be preserved across uses when using windowed mode, so that works the same now as before and appears to be working correctly. However, it will now only remember to be in fullscreen mode *once* before reverting to windowed mode. The fact that it remembers the mode one time tells me it was not a feature that was intentionally removed, but nevertheless the end result is that the feature is broken.

### Operating system

KDE Neon (Ubuntu with usually-up-to-date KDE software), using KDE Plasma 5.27.10 on X11. My laptop had severe problems with the Plasma 6.0 upgrade, so I'm holding back.

### Version of Telegram Desktop

5.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
can't reproduce with https://t.me/tgbetachat/1923146 on windows 10.

**Comment by ilya-fedin** [comment]
@Aokromes that seem to happen only on X11. Even Wayland doesn't have that. What might suggest it's a Qt regression as Qt was updated to 6.7.2 during the beta phase...

**Comment by Tynach** [comment]
> can't reproduce with https://t.me/tgbetachat/1923146 on windows 10.

@Aokromes, glad to know it's not something that'll affect Windows users; was gonna link this to some friends and ask them if they were experiencing it too, but won't need to bug them about it now.

@ilya-fedin: Wayland still doesn't support display calibration, so it's a no-go for me right now. Thankfully it's a minor bug, and I can just put up with it until it's fixed (either in Qt, or whatever workaround is found if it's to do with Qt changing how something works rather than an outright bug).

**Comment by ilya-fedin** [comment]
No, this doesn't seem to be a Qt regression after all, yet Qt provides weird window state changes so it downgrade first from fullscreen to maximized and then from maximized to no state immediately...

**Comment by Tynach** [comment]
@ilya-fedin That's odd. I thought the difference between full-screen and maximized, was whether it took up the whole display, or just the part of the display maximized windows would take up (leaving the desktop environment's panels visible).

For me, when I click the 'Maximize' button it covers the entire display, with the panels faintly visible underneath (due to partial transparency of the area around the media being viewed). When I close that, and then open again, the same thing is true — which had led me to believe it was still fullscreen, rather than maximized.

I take it then that you're able to reproduce the bug?

**Comment by ilya-fedin** [comment]
> I thought the difference between full-screen and maximized, was whether it took up the whole display, or just the part of the display maximized windows would take up (leaving the desktop environment's panels visible).

Yes, that's right.

> When I close that, and then open again, the same thing is true — which had led me to believe it was still fullscreen, rather than maximized.

You won't see maximized state because, as I already said, it downgrades immediately to no state, your eyes won't even notice it. It's only visible when logging in terminal, like that:
```
QFlags<Qt::WindowState>(WindowFullScreen)
QFlags<Qt::WindowState>(WindowMaximized|WindowFullScreen)
QFlags<Qt::WindowState>(WindowNoState)
```
vs how it looks on wayland:
```
QFlags<Qt::WindowState>(WindowFullScreen)
```

> I take it then that you're able to reproduce the bug?

Yeah.

**Comment by ilya-fedin** [comment]
If I prevent it from saving the state in hidden mode, the no state event gets cut but that vague `WindowMaximized|WindowFullScreen` still leads the window to be downgraded from fullscreen to maximized...
