### ISSUE TITLE
How to make Themes?

### ISSUE THREAD

**Issue by madl-ash** [telegramdesktop/tdesktop#2810]
I can't  Find Any Documentation or tutorial or ... on how to make and edit Telegram Themes(.tdesktop-theme) Anywhere.does this mean only devs can make themes?if not,can anyone give me any documentations about it?
P.S : I Can't access @telegramthemes because  I'm  Iranian #2806

**Comment by mjanssen** [comment]
Check out this file:

https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/default.tdesktop-theme

**Comment by madl-ash** [comment]
Thanks,i think you can close this now

**Comment by IgorDePaula** [comment]
404 on checkout file.

**Comment by stek29** [comment]
@IgorDePaula Well, it has built-in theme editor now.

**Comment by IgorDePaula** [comment]
where?

**Comment by mjanssen** [comment]
Creating a new theme can be found at:

Telegram mobile > Settings > Theme > Create New Theme

**Comment by IgorDePaula** [comment]
Only, android, iOS not, and I would like put my prefer background image, in desktop. =/

**Comment by auchri** [comment]
This repo is only about Telegram Desktop.

![image](https://cloud.githubusercontent.com/assets/5092164/25404216/57eb08b6-29ff-11e7-9bfc-b4b0240929de.png)

**Comment by IgorDePaula** [comment]
I follow the desktop theme channel but I not received more themes.. =/

**Comment by IgorDePaula** [comment]
I discovery on my desktop telegram application, thanks
