### ISSUE TITLE
Context Menu Displays Gray Background Instead of Transparent on Manjaro with Xorg

### ISSUE THREAD

**Issue by arrshad** [telegramdesktop/tdesktop#28109]
### Steps to reproduce

1. Open Telegram Desktop (Installed using pacman).
2. Open a chat and right-click on a message or any other area within the chat.
3. Observe the context menu that appears.

### Expected behaviour

The context menu should have a transparent background as intended.

### Actual behaviour

The context menu opens with a gray background instead of a transparent background:
![image](https://github.com/telegramdesktop/tdesktop/assets/108279529/74c4d0ac-debe-42b4-98fb-585c307d9ecf)

### Operating system

Linux 6.9.5-1-MANJARO + X.Org X Server 1.21.1.13

### Version of Telegram Desktop

5.1.5

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
This looks like a problem with your Qt style which is likely drawing on transparent regions
