### ISSUE TITLE
cursor position is incorrect

### ISSUE THREAD

**Issue by Sherlock-Holo** [telegramdesktop/tdesktop#28114]
### Steps to reproduce

1. open telegram-desktop on GNOME X11
2. open a chat
![image](https://github.com/telegramdesktop/tdesktop/assets/10096425/993267ef-cd1d-492b-88ed-705b9759e8ba)

### Expected behaviour

cursor should be vertically centered

### Actual behaviour

the cursor position is slightly upward

### Operating system

Archlinux, GNOME 46.3.1 X11

### Version of Telegram Desktop

5.2.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
> ### Installation source
> 
> Other (unofficial) source

Please report using official versions only

**Comment by john-preston** [comment]
Yeah, something's off..

**Comment by lyp1noff** [comment]
Same here, Arch, Gnome X11

**Comment by egor-khanko** [comment]
> > ### Installation source
> > Other (unofficial) source
> 
> Please report using official versions only

Installed from flatpak (listed as official), updated to the latest version.
Fedora 40, Gnome.
![image](https://github.com/telegramdesktop/tdesktop/assets/32592704/b862a09a-1fb5-49ac-ac89-18e570b461ad)

**Comment by lyp1noff** [comment]
Fixed for me in version 5.3 (position when only emoji printed without text still weird though)

**Comment by Aokromes** [comment]
test on 5.5.1
