### ISSUE TITLE
Broken program window updates with Plasma/Wayland

### ISSUE THREAD

**Issue by chelobaka** [telegramdesktop/tdesktop#28112]
### Steps to reproduce

1. Run Telegram
2. Scroll any chat or open settings

### Expected behaviour

The program window is updated according to user input

### Actual behaviour

Scrolling chats or navigating menus happens without redrawing changed window parts. 

Version 5.2 broke window updates with Plasma/Wayland (5.27.11) , version 5.2.1 made it even worse. 

### Operating system

Debian Testing x64

### Version of Telegram Desktop

5.2.1

### Installation source

Static binary from official website

**Comment by waleev** [comment]
Input goes to top after 5.2.1 update on Ubuntu 22.04:
![изображение](https://github.com/telegramdesktop/tdesktop/assets/7687797/dd5195a2-8b8c-4e27-8338-056d65314396)

**Comment by chelobaka** [comment]
@ilya-fedin, your answer might be very well technically correct, but from end user perspective it sounds quite amusing. Some people use stable distributions for a reason of stability. Even if it's a kwin problem, it would take quite some time to fix and propagate updates to users. 

Can you share kwin version you are testing your application against?

Is there a way to temporarily downgrade Telegram client to pre 5.2 version using official distribution channels?

**Comment by ilya-fedin** [comment]
@chelobaka afaik tdesktop is tested against Ubuntu 22.04 default flavour installation and WSL right now (previously was Ubuntu 14.04 default flavour).

**Comment by chelobaka** [comment]
> afaik tdesktop is tested against Ubuntu 22.04 default flavour installation and WSL right now (previously was Ubuntu 14.04 default flavour).

Ubuntu 22.04 is not that modern. It ships kwin 5.24.7, while Debian testing ships 5.27.11 — the latest version for Plasma 5.

> Just get the binary of the version you want and disable updates? Downgrade would lead to the application data being removed, though.

Yes, how can we get a Telegram binary before version 5.2?

**Comment by ilya-fedin** [comment]
> Ubuntu 22.04 is not that modern. It ships kwin 5.24.7, while Debian testing ships 5.27.11 — the latest version for Plasma 5.

The default flavor doesn't ship kwin at all. What I meant is, tdesktop is not tested against kwin at all afaik.

**Comment by ilya-fedin** [comment]
> Yes, how can we get a Telegram binary before version 5.2?

Via GitHub Releases?
