### ISSUE TITLE
Problem with viewing multimedia files on Windows 11 24H2 26100.560 - 26100.1000 on AMD

### ISSUE THREAD

**Issue by antonridd** [telegramdesktop/tdesktop#28116]
### Steps to reproduce

1. Start the PC
2. Launch Telegram
3. Open any video in any chat.
4. Close the video.
5. Continue using the PC
6. Observe the system animation lags

CPU AMD Ryzen 7 5800X 8-Core Processor 3.80 GHz
GPU AMD Radeon RX 6600 XT 8GB
RAM 16 GB

### Expected behaviour

When playing videos in any channel, Telegram and the operating system should function normally with smooth animations.

### Actual behaviour

When playing a video and then closing it in any channel, the animations of the operating system begin to lag very much

### Operating system

Windows 11 24H2 build 26100.1000

### Version of Telegram Desktop

5.2.1

### Installation source

Static binary from official website

**Comment by antonridd** [comment]
If I select an external video player in the experimental settings, then everything works fine and there are no system lags

**Comment by antonridd** [comment]
The problem persists on 5.2.3

**Comment by antonridd** [comment]
The problem persists on Windows 11 24H2 26100.1150

**Comment by saddedmoroz** [comment]
This may be the result of a problem with your video driver. You could try updating or downgrading it.
AMD video drivers have been known to have issues 🤦‍♂️ Often, the latest version of a driver does not necessarily mean it is stable.

**Comment by antonridd** [comment]
> This may be the result of a problem with your video driver. You could try updating or downgrading it. AMD video drivers have been known to have issues 🤦‍♂️ Often, the latest version of a driver does not necessarily mean it is stable.

with this driver version, everything works well on 23H2. But problems start on 24H2

**Comment by antonridd** [comment]
The problem persists on Windows 11 24H2 26100.1301 and telegram 5.3.1

**Comment by dimas1980200** [comment]
meet.google.com/ayy-ozvj-jbs
***@***.***

вт, 6 авг. 2024 г., 22:06 antonridd ***@***.***>:
