### ISSUE TITLE
Telegram.sln not exist

### ISSUE THREAD

**Issue by ghost1372** [telegramdesktop/tdesktop#2811]
### Expected behaviour
i do steps one by one and every things is ok but Telegram.sln not exist!!!
so i cant open it in VS2015
### Actual behaviour
Install Windows SDKs

If you didn't install Windows SDKs before, you need to install them now. To install the SDKs just open Telegram solution at D:\TBuild\tdesktop\Telegram.sln and on startup Visual Studio 2015 will popup dialog box and ask to download and install extra components (including Windows 7 SDK).

### Configuration
**Operating system:**
Windows 10 
**Version of Telegram Desktop:**
Latest Commit

**Comment by auchri** [comment]
See the 

> Setup GYP/Ninja and generate VS solution

section in the instructions
