### ISSUE TITLE
tdeskop close after open a photo in Ubuntu 24.04

### ISSUE THREAD

**Issue by rejurime** [telegramdesktop/tdesktop#28126]
### Steps to reproduce

1. Open a photo
2. Close the photo
3. If the app work fine repeat after 1, 2 or 3 photos open the windows app close.

### Expected behaviour

Close de photo and continue using tdesktop.

### Actual behaviour

After 1, 2 or 3 photos open the windows app close.

### Operating system

Ubuntu 24.04 - Gnome 46 - Wayland

### Version of Telegram Desktop

5.2.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Tried to open-close 3 times in a row and it's still open

**Comment by trap000d** [comment]
It happens to me too. After some investigation the issue looks like a problem with dbus and systray icon. Steps to repeat:
  1. Start telegram and minimize it to tray
  2. Open dolphin file manager and navigate to any folder with pictures
  3. Open any picture
  4. Telegram icon disappears from tray (but it continue to run in background)

After killing of all telegram instances and restarting it there is an error in console:
```
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.UnknownObject", "No such object path '/StatusNotifierWatcher'")
```

I assume it's a regression introduced by https://github.com/telegramdesktop/tdesktop/commit/8a5797e1bd2c0e4ae49a6722d3b5231ef787288c
 
P.S. 
O/S: Arch Linux
TG ver: extra/telegram-desktop 5.2.3-1 [installed]

**Comment by ilya-fedin** [comment]
@trap000d your issue doesn't sound related as the initial reporter says Telegram window gets closed, nothing about tray icon

**Comment by trap000d** [comment]
Should I create a new issue?

**Comment by ilya-fedin** [comment]
No, this sounds like a KDE bug.

**Comment by trap000d** [comment]
> No, this sounds like a KDE bug.

After further tests I generally agree this is something with KDE stuff.  And most probably it's related to dolphin or it's D-Bus bindings. If I use other file manager (thunar) or run picture viewer from terminal, tray icon does survive. 

Do you suggest to report it to KDE upstream? I suspect it will be buried in the pile together with other 250k issues

P.S. So far only the most recent version of telegram has such problem.

**Comment by ilya-fedin** [comment]
According to your description, it feels like you found 3 bugs on KDE side:
1. Interacting with Dolphin leads to failure of some component and KDE's tray icon daemon de-registers StatusNotifierItemWatcher service
2. KDE doesn't reset registered tray icons on service de-register
3. KDE registers object after registering the service creating a race condition

Fixing only 3 would likely lead to duplicate tray icon for some implementations that didn't disappear before. Fixing 2 and 3 without fixing 1 would likely lead to tray icons from (incomplete) implementations not watching for service restarts being lost (quite a lot likely, even Qt itself has problems with that).

Although maybe it doesn't de-register but rather changes the owner, in which case there's only one bug (the third one). It's still weird it happens when you do something with files in Dolphin, though.

**Comment by trap000d** [comment]
Thanks for clarification. It makes a  perfect sense. I've just spent 20 minutes searching over KDE bug tracker. There are so many similar reports so I see no point of creating one more. I've just picked PCManFM as default one and all seems looking good now - TG icon is still in the tray.

**Comment by ilya-fedin** [comment]
I assume https://invent.kde.org/plasma/plasma-workspace/-/commit/f03ea121200a4b394b5d7af8831861091db0fd7e is the cause

**Comment by ilya-fedin** [comment]
I think you should write to https://bugs.kde.org/show_bug.cgi?id=425315

**Comment by grimm26** [comment]
I don't even use KDE and I'm getting a similar segfault:
```
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.StatusNotifierWatcher was not provided by any .service files")
```

**Comment by rejurime** [comment]
I don't know if this can help, but I have an NVIDIA video card.
NVIDIA Driver Version: 550.100

Recently change from the binary package to flatpak version and works fine.

Can I provide any other information?

**Comment by ilya-fedin** [comment]
Try to reproduce the issue in a clean VM and remember all the steps from VM installation to reproducing the crash.
