### ISSUE TITLE
Update - failed to verify integrity

### ISSUE THREAD

**Issue by artemisclyde** [telegramdesktop/tdesktop#2812]
### Steps to reproduce
1. arch linux
2. update via pacaur

### Expected behaviour
Update should be run without errors.

### Actual behaviour
Update stops, displaying the following
```
==> ERROR: One or mor filres did not pass the validity check!
:: failed to verify telegram-desktop-bin integrity
```

### Configuration
**Operating system:**
x86_64 Linux 4.8.13-1-ARCH
**Version of Telegram Desktop:**
1.0

**Comment by auchri** [comment]
Not an official package

**Comment by louwers** [comment]
Don't use the AUR package, just download the Telegram binary.

**Comment by artemisclyde** [comment]
Although it's closed, some update. The problem can be solved by clearing the pacaur cache.

Of course the official telegram binary works like a charm, too.
