### ISSUE TITLE
Version link points to an outdated version history page

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#28122]
### Steps to reproduce

1. Open Telegram sidebar menu
2. Click on Version 5.2.2 x64 link

or

1. Open Telegram sidebar menu
2. Click About
3. Click on the version under the title

### Expected behaviour

The page should contain the current version history

### Actual behaviour

Outdated page https://desktop.telegram.org/changelog opens:
![image](https://github.com/telegramdesktop/tdesktop/assets/1321838/7c5867c3-8481-46eb-9412-06258171395e)

### Operating system

Windows 11

### Version of Telegram Desktop

5.2.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
duplicate.
