### ISSUE TITLE
Allow clicking links in the Alt+Click chat previews

### ISSUE THREAD

**Issue by kolayne** [telegramdesktop/tdesktop#28136]
### Is your feature request related to a problem?

Currently, chat previews can not be interacted with, unless opened normally with a double click.

### Describe the solution you'd like

It would be nice to be able to click on links (maybe other interactive options? Opening media? Playing voice/video messages or music?) while the chat is in the preview.

### Describe alternatives you've considered

If I want to follow a link from a message without marking the message is read, the only method I'm aware of is to first preview the chat to make sure telegram-desktop loads the message, then disable internet connection, then open the chat and follow the link, then quit telegram-desktop, then enable internet connection. Not too convenient :smiling_face_with_tear:

**Comment by john-preston** [comment]
@kolayne No, this is intended and is consistent with chat preview on mobile apps, where this feature was initially introduced.

**Comment by migozz** [comment]
How should someone like me know about the possibility of alt+click to preview a chat? Or photo long press! How many other features are undocumented and unknown to the user?

**Comment by kolayne** [comment]
@john-preston,

> No, this is intended

:pensive:

> and is consistent with chat preview on mobile apps, where this feature was initially introduced

From the developer's perspective, I suppose, it is, however, from the user's experience it probably is not. At least, on my MIUI 14 (based on Android 13), when a notification arrives for a new message that contains a link, I can follow that link from my notification interface without opening the chat. I use that quite often.

<details>
<summary>Finding out about new features (off-topic)</summary>

@migozz,

> How should someone like me know about the possibility of alt+click to preview a chat? Or photo long press! How many other features are undocumented and unknown to the user?

Not sure what you mean by a photo long press... I just tried it on my tg-desktop (for photos in the chat list, photos in open profiles, media in the chat - nothing special happening).

I find out about new features of _telegram desktop_ specifically (rather than global telegram features) from changelogs. You can access one in the repository (the changelog.txt file) or on the [releases](https://github.com/telegramdesktop/tdesktop/releases) page of tdesktop (which you can subscribe for, by clicking Watch -> Custom at the top of the [tdesktop github page](../)).

</details>

**Comment by john-preston** [comment]
Well, I talk about chat preview features on mobile (long press on userpic in chats list on android or on the whole chat in iOS) -- they both inspired this feature in TDesktop and they don't allow any interaction with chat.

**Comment by migozz** [comment]
It should not be consistent with chat preview on "mobile apps". For ex., a long pressing on an item for mobile apps can be realized, but for desktop apps is not.
All functions should be duplicated in context menu. And hotkeys should be documented in (offline) help by F1.
Reading the changelogs is not something that most people do, and it can be easily forgotten.

I don't know about whether it should be allowed to interact with the chat preview, because I didn't know about any chat preview before, but in chat preview doesn't work PgUp/PgDn, and missing "scroll to bottom" button, which is not consistent with mobile apps.
