### ISSUE TITLE
TG support department

### ISSUE THREAD

**Issue by aliobzor** [telegramdesktop/tdesktop#28134]
### Steps to reproduce

Unblock our telegram channel @promokod_mm 
which was blocked due to quarantine, because we corrected all the violations a long time ago, please improve the work of your support department, we are losing our audience, urgently!

### Expected behaviour

Unblock our telegram channel @promokod_mm 
which was blocked due to quarantine, because we corrected all the violations a long time ago, please improve the work of your support department, we are losing our audience, urgently!

### Actual behaviour

Unblock our telegram channel @promokod_mm 
which was blocked due to quarantine, because we corrected all the violations a long time ago, please improve the work of your support department, we are losing our audience, urgently!

### Operating system

 Unblock our telegram channel @promokod_mm  which was blocked due to quarantine, because we corrected all the violations a long time ago, please improve the work of your support department, we are losing our audience, urgently!

### Version of Telegram Desktop

 Unblock our telegram channel @promokod_mm  which was blocked due to quarantine, because we corrected all the violations a long time ago, please improve the work of your support department, we are losing our audience, urgently!

### Installation source

Microsoft Store

### Logs

```shell
Unblock our telegram channel @promokod_mm 
which was blocked due to quarantine, because we corrected all the violations a long time ago, please improve the work of your support department, we are losing our audience, urgently!
```

**Comment by DeadmindX** [comment]
Yes, please unlock

**Comment by Deinoseer** [comment]
Please pay attention, we ask for a horde of subscribers! We beg you! We really liked this channel!

**Comment by migozz** [comment]
this is not a TG support department
https://journal.tinkoff.ru/telegram-support/
