### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ghost1372** [telegramdesktop/tdesktop#2813]
### Expected behaviour
when i build tdesktop.sln in vs2015 i get error
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "call ninja.exe -C out\Debug\ -k0 MetaLang" exited with code 1.	MetaLang	D:\TBuild\tdesktop\MetaLang.vcxproj	121	

### Configuration
**Operating system:**
Win 10 64x
**Version of Telegram Desktop:**
Latest Commit

**Comment by mohammadrezanadiri** [comment]
Hi,
Instruction set to build the project under Linux (Ubuntu)  is outdated. Some steps are not successfully done. Some packages can't be found. Please update the instruction.

Thanks,
Nadiri
