### ISSUE TITLE
Markdown [inline](link) doesn't work

### ISSUE THREAD

**Issue by KOT4N** [telegramdesktop/tdesktop#28137]
### Steps to reproduce

1. open chat
2. type [inline]
3. type (https://t.me/telegram)
4. send

### Expected behaviour

[inline](https://t.me/telegram)

### Actual behaviour

`[inline](https://t.me/telegram)`

### Operating system

Windows 10 

### Version of Telegram Desktop

5.2.1, 5.2.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
it's not supposed to work, it's just not a feature
