### ISSUE TITLE
Add option to never delete my gifs/stickers

### ISSUE THREAD

**Issue by soredake** [telegramdesktop/tdesktop#28131]
### Is your feature request related to a problem?

I really tired to see telegram for desktop removing unused stickers/gifs once in a while (week? month?), especially now when telegram is throttling non-premium user download speeds,

### Describe the solution you'd like

Having option to never delete my gifs/stickers (no matter the disk size they take).

### Describe alternatives you've considered

Living with this problem, which I want to avoid.

### Additional context

I'm tired of seeing this:
![изображение](https://github.com/telegramdesktop/tdesktop/assets/5204968/da25e6ac-8d99-4922-a9e6-af2a8de4649d)

**Comment by ilya-fedin** [comment]
this list is server-side, tdesktop remove anything on its own from there
