### ISSUE TITLE
secret chat on telegram desktop

### ISSUE THREAD

**Issue by iocc-git** [telegramdesktop/tdesktop#28130]
### Is your feature request related to a problem?

yeah, its hard to write long texts on a mobile and I want to do it on a desktop computer.

### Describe the solution you'd like

secret chat support on telegram desktop win/mac/linux.

### Describe alternatives you've considered

signal supports it but it breaks between updates and their linux support with snap works very badly on my dist.
also its ugly. After 2 years I gave up with signal.

I dont trust facebook/meta messenger and its impossible to run on a mobile without their own app.

### Additional context

I'll be happy to PAY for secret chat on telegram desktop linux!

**Comment by ilya-fedin** [comment]
#871
