### ISSUE TITLE
Cannot type Cyrillic characters in the GTK+3 file chooser

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#28144]
### Steps to reproduce

I'm not even sure actually how does TelegramDesktop determine to use the GTK+3 chooser on my system. I have `XDG_CURRENT_DESKTOP=gnome` and `QT_QPA_PLATFORMTHEME=gtk2`; tried unsetting both, but it still uses the same chooser and loads GTK+ on the start, which can be seen by Gtk-message and Gtk-WARNING lines.

### Expected behaviour

Cyrillic characters can be typed in the location and search fields of the GTK+3 file chooser.

### Actual behaviour

Cyrillic characters are silently ignored.

### Operating system

Debian GNU/Linux Trixie, Compiz

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> I'm not even sure actually how does TelegramDesktop determine to use the GTK+3 chooser on my system. I have XDG_CURRENT_DESKTOP=gnome and QT_QPA_PLATFORMTHEME=gtk2; tried unsetting both, but it still uses the same chooser and loads GTK+ on the start, which can be seen by Gtk-message and Gtk-WARNING lines.

Well, static binary couldn't use your system Qt plugins and Qt has some hard-coded platformtheme plugins priority when the one set by the environment variable is not found.

> Cyrillic characters are silently ignored.

Sorry, but I can't reproduce. Can enter Cyrillic just fine.

**Comment by bodqhrohro** [comment]
> and Qt has some hard-coded platformtheme plugins priority

Which exactly?

**Comment by ilya-fedin** [comment]
> Which exactly?

kde, gtk3, XDG_CURRENT_DESKTOP value with stripped "X-" at the start of the string. In case of tdesktop, only gtk3 plugin is linked in the static binary as it's the only one coming with qtbase.

**Comment by bodqhrohro** [comment]
Eh, it turns out it's not even the TelegramDesktop issue.
```
@bq:03:08:34:/tmp/dl$ wmctrl -l -p
...
0x0020000b  0 3401392 localhost Saved Messages @ Bohdan Horbeshko
...
0x08216551  0 3571564 localhost Choose Files
@bq:03:08:48:/tmp/dl$ ps aux|grep 3401392
bodqhro+   21618  0.0  0.0   9196  2192 pts/12   S+   03:09   0:00 grep 3401392
bodqhro+ 3401392  0.4  1.4 2865892 172824 pts/47 Sl+  Jul26   6:08 Telegram
@bq:03:09:18:/tmp/dl$ ps aux|grep 3571564
bodqhro+   21715  0.0  0.0   9196  2136 pts/12   S+   03:09   0:00 grep 3571564
bodqhro+ 3571564  0.0  0.4 1134904 46548 ?       Ssl  Jul16   1:59 /usr/libexec/xdg-desktop-portal-gtk
```
