### ISSUE TITLE
[Feature request] save (copy, export) history

### ISSUE THREAD

**Issue by edmundlaugasson** [telegramdesktop/tdesktop#2814]
### Steps to reproduce
1. have a conversation in group or 1:1
2. try to save (copy, export) history
3. no other options than manually selecting messages

### Expected behaviour
**Select messages** (smaller history):
* all
* from x to y date
* from beginning to x date
* from x date to end
* copy these messages into memory (CTRL+C) - this could work only when copied messages do fit into memory - program should check whether copied data fits to available memory or not. If not then say that and automatically offer export to file options

Result depends on the program where will be pasted whether there will be text only or also images and other files. There could be made a distinction whether there would be copied text, images or if all content wanted then export feature should be used.

**Export messages** (larger history)
Another and probably better idea in case of history in large scale would be just export messages without selecting/copying them and save the program and computer from application freezing:
* export messages to file:
  * all
  * from x to y date
  * from beginning to x date
  * from x date to end
  * separately: txt (e.g. reStructuredText etc.) for chat and other files in their original format
    * optional checkmarks by exporting:
      * add date, time into filename or not
      * group exported files into folders named by date
  * pdf - as seen in Telegram, split into certain length files

### Actual behaviour
Not yet possible to copy, export

### Configuration
**Operating system:**
64-bit Linux Mint 18.1 with 4.9.2 kernel

**Version of Telegram Desktop:**
1.0

### Logs
Logs are not necessary.

**Comment by auchri** [comment]
Duplicate #126
