### ISSUE TITLE
Typing in Wallet app doesn't work properly

### ISSUE THREAD

**Issue by Aceix** [telegramdesktop/tdesktop#28146]
### Steps to reproduce

1. Open Telegram Desktop
2. Open Wallet from side bar
3. Try sending money to a contact
4. Try typing the amount and notice that it does not respond well (it over-types or does not type at all)

### Expected behaviour

Typing should work normally when I am entering an amount

### Actual behaviour

Typing is abnormal when entering an amount: it over-types (as if the key is pressed and held down) or does not respond at all

### Operating system

Ubuntu 22.04.4

### Version of Telegram Desktop

5.2.1

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Sorry but steps to reproduce are too complex. Could this be reproduced without trying to send money, e.g. with https://t.me/DurgerKingBot?

**Comment by Aceix** [comment]
> Sorry but steps to reproduce are too complex. Could this be reproduced without trying to send money, e.g. with https://t.me/DurgerKingBot?

nope, not with DurgerKingBot: it doesn't seem to work with Wallet.
But you don't need to actually send the money to see this bug. You only should try typing the amount, or click on the "Use Max amount button"

**Comment by ilya-fedin** [comment]
> But you don't need to actually send the money to see this bug.

The thing is I don't have any money on the wallet and -> the wallet doesn't let me to send money -> I can't reproduce

**Comment by Aceix** [comment]
> > But you don't need to actually send the money to see this bug.
> 
> The thing is I don't have any money on the wallet -> the wallet doesn't let me send money -> I can't reproduce

Then I guess someone else has to check it because I don't know how else to repro. 

Also, the strange thing is the bug doesn't seem to happen when sending from TON Space

**Comment by ilya-fedin** [comment]
> Then I guess someone else has to check it because I don't know how else to repro.

Sorry but there's no one else to repro. If this is reproducible only with specific app, perhaps you should report this to wallet. If they would be able to confirm the issue, they can come to tdesktop with more technical details and a simpler reproducer.
