### ISSUE TITLE
Hidden stories open when you click the left part of the "archived chats" section even if it is collapsed

### ISSUE THREAD

**Issue by emv33** [telegramdesktop/tdesktop#28149]
### Steps to reproduce

1. Right-click the "Archived chats" entry of the chat list and collapse it
2. If you don't have any hidden stories, hide some by right-clicking them
3. Click the leftmost part of the collapsed "Archived chats" entry (the part that says "Archiv", where the archive icon would be if you hadn't collapsed the button)

### Expected behaviour

The list of Archived chats should open

### Actual behaviour

A hidden story opens, even though once you collapse the "Archived chats" entry of the chat list it does not show stories so you do not expect a story to open

### Operating system

Windows

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Thanks!
