### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by kuba-orlik** [telegramdesktop/tdesktop#28140]
### Steps to reproduce

1. Keep Telegram Desktop open in the background 
2. Wait. Maybe put your computer to sleep/hibernate and wake it up

### Expected behaviour

Telegram works

### Actual behaviour

Telegram is not connected to the server. There's a spinner in the bottom left corner. I need to either restart Telegram, or click on the spinner and do some back-and-forth changes to the proxy settings and then it connects.

A few of my friends are also experiencing this issue, so I don't thinks it's something with my setup.

### Operating system

Linux

### Version of Telegram Desktop

5.2.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
> ### Installation source
> 
> Other (unofficial) source

Sorry but this issue tracker is only for official builds.
