### ISSUE TITLE
Folder-specific Mute Function for Telegram

### ISSUE THREAD

**Issue by Long18** [telegramdesktop/tdesktop#28148]
### Is your feature request related to a problem?

Currently, Telegram allows users to organize chats into folders (e.g., work, friends, social) for better management. However, users cannot mute entire folders for a selected duration. This limitation means users must manually mute individual chats within a folder, which is time-consuming and inefficient.

### Describe the solution you'd like

I want Telegram to implement a feature that allows users to mute entire folders for a user-defined period. This feature would work similarly to the existing mute function for individual chats and groups, but it would apply to all chats within a selected folder. Users could specify the mute duration (e.g., 1 hour, 8 hours, 1 week, Mute forever) for each folder, providing greater control over notifications during different times or activities.

### Describe alternatives you've considered

An alternative solution is to enhance the existing mute function to allow batch muting of selected chats within a folder. However, this approach would still require more manual steps than muting an entire folder simultaneously. Another alternative could be implementing a "Do Not Disturb" mode that silences all notifications except for those from a custom whitelist of chats or folders.

### Additional context

This feature would be handy for users who must focus on specific tasks or avoid distractions during meetings, work hours, or personal time. For example, a user could mute their "work" folder outside of office hours or mute their "social" folder during focused work sessions

**Comment by ilya-fedin** [comment]
#7529?
