### ISSUE TITLE
Idea to improve efficiency of users who's work use telegram a lot.

### ISSUE THREAD

**Issue by realniceping** [telegramdesktop/tdesktop#28151]
### Is your feature request related to a problem?

My job (i'm software developer) require using Telegram a lot (for communication with my teammates), but also all chat with my friends and family in telegram. Because of this, you have to take time off from work. I want to offer a solution to my problem.

### Describe the solution you'd like

I thinking that hiding folders can solve my problem. But this process should working with some schedule. For example: "Hide chats folder in working days except celebrations". I think my idea can improve telegram experience. 

### Describe alternatives you've considered

I'm not thinking about alternative

**Comment by realniceping** [comment]
UDP: sorry for maybe duplicate other ideas, but all of them sounds little different that my

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7534

**Comment by realniceping** [comment]
> #7534

Maybe we misunderstood  each other. Main goal of my idea it's not a compact interface. I want this feature for focus improving and i don't need hide whole folder bar.

**Comment by realniceping** [comment]
Maybe i can show you example how i want to use it.

Case: i'm working 5/2 (mo tu we th fr) from 9:00 till 17:00, and i want to hide all folder except my folder with working chats and I don't want to receive any notifications from hiding folders

**Comment by ilya-fedin** [comment]
@realniceping you have chosen a client-specific issue type while what you're talking about is a platform-wide fature.

**Comment by realniceping** [comment]
> @realniceping you have chosen a client-specific issue type while what you're talking about is a platform-wide fature.

IMHO, it's just a usefull and interesting feature. This functional also been possible to avaliable only for premium users. I'll buy telegram premium subscribe if it will include this features

**Comment by ilya-fedin** [comment]
@realniceping still, it's a wrong issue type

**Comment by realniceping** [comment]
> @realniceping still, it's a wrong issue type

sry, how to i can suggest idea?

**Comment by ilya-fedin** [comment]
Choose the right issue type (platform-wide issue) when creating issue
