### ISSUE TITLE
No sound for media

### ISSUE THREAD

**Issue by Radgryd** [telegramdesktop/tdesktop#28153]
### Steps to reproduce

All of my media have stopped playing sound on Desktop, the notification sound still works though.

### Expected behaviour

Should play sound.

### Actual behaviour

Does not play sound.

### Operating system

Windows 10 Pro 22H2

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> ### Logs
> 
> _No response_

Fill this

**Comment by Aokromes** [comment]
works for me with https://t.me/roscosmos_gk/14137
