### ISSUE TITLE
Logical errors

### ISSUE THREAD

**Issue by autocpp** [telegramdesktop/tdesktop#28152]
### Is your feature request related to a problem?

Group deletion history, why not delete my messages, but block my previous messages from browsing the group. I can only use another account to view the group's previous messages. this is "掩耳盗铃".

### Describe the solution you'd like

I want people to be able to browse the group's previous messages after deleting the history

### Describe alternatives you've considered

！！！

### Additional context

![屏幕截图 2024-07-09 131809](https://github.com/telegramdesktop/tdesktop/assets/82892908/142116c2-6c88-426c-ad25-41acdb0df188)

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
