### ISSUE TITLE
preview link is not working

### ISSUE THREAD

**Issue by ken1139** [telegramdesktop/tdesktop#28150]
### Steps to reproduce

i have a link 
https://staging-new.itrial.hk/cashback2024summer-105 , send in tg is no perview link， i have try the webpage bot，also not working， i sure that the og title og desc og image is good，please help，thx

### Expected behaviour

will show the preview link in tg

### Actual behaviour

just the link show in the tg，no display og title og image og desc

### Operating system

win11

### Version of Telegram Desktop

5.2.3 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
previews are handled server side.
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by ken1139** [comment]
> previews are handled server side. platform wide bugs / requests belongs to https://bugs.telegram.org/

i cant create the card in https://bugs.telegram.org/
