### ISSUE TITLE
NMake Makefiles  does not support platform specification, but platform  x64

### ISSUE THREAD

**Issue by lilhackQ** [telegramdesktop/tdesktop#28159]
### Steps to reproduce

I enter into all kinds of command lines: configure.bat x64 -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb

### Expected behaviour

pass

### Actual behaviour

CMake Error at CMakeLists.txt:33 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.

### Operating system

windows 64

### Version of Telegram Desktop

lastest

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
looks like you were trying to build not by instruction first and now it's cached? clear the cache

**Comment by lilhackQ** [comment]
> configure.bat x64 -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb

не помогает, теперь выглядит все по другому:

C:\Users\Artem\Desktop\TBuild\BuildPath\tdesktop\Telegram>configure.bat x64 -D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb
Choosing Qt 5.
Choosing Qt 5.15.13
Warn about uninitialized values.
CMake Error: Error: generator platform: x64
Does not match the platform used previously: Win32
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
FAILED

**Comment by lilhackQ** [comment]
![image](https://github.com/user-attachments/assets/b35b2950-0efc-46b3-ba5c-47bf229576f9)

**Comment by lilhackQ** [comment]
![image](https://github.com/user-attachments/assets/ffdeb9cf-d675-416b-aa62-7c3199302cf9)
another problem has arisen, it turns out I didn’t download all the files

**Comment by ilya-fedin** [comment]
Looks like you have networking problems

**Comment by lilhackQ** [comment]
> Looks like you have networking problems

no, everything is fine with the Internet, maybe Avast quarantined some files? (very unlikely however) I still can't even go in with this, because I'm in Russia and there's just the whole window: "not available in your region" and it's a pity to delete

**Comment by ilya-fedin** [comment]
> no, everything is fine with the Internet, maybe Avast quarantined some files? (

are you sure? have you tried to open the url in browser?

**Comment by lilhackQ** [comment]
> > no, everything is fine with the Internet, maybe Avast quarantined some files?
> 
> are you sure? have you tried to open the url in browser?
I just tried it, it worked only with VPN, I’ll go look for my VPN)

**Comment by lilhackQ** [comment]
> > no, everything is fine with the Internet, maybe Avast quarantined some files?
> 
> are you sure? have you tried to open the url in browser?

I tried it, it only worked with VPN, I’ll go look for my VPN)

**Comment by lilhackQ** [comment]
I'm downloading files, but the problem remains the same

**Comment by ilya-fedin** [comment]
I'm not sure what you meant?

**Comment by lilhackQ** [comment]
the problem for which the application was created remains

**Comment by ilya-fedin** [comment]
The application is created to connect people and it remains, yeah.
