### ISSUE TITLE
Cutted message popup menu telegram linux

### ISSUE THREAD

**Issue by dmagister** [telegramdesktop/tdesktop#28160]
### Steps to reproduce

Press the right mouse button on message.

### Expected behaviour

Should be a popup menu with emoji selection line
![IMG20240712205124](https://github.com/user-attachments/assets/2c3c2971-40d4-453f-a8a1-ba71f7381d17)

### Actual behaviour

Popup menu is cutted from right and have artifact
![IMG20240712205136](https://github.com/user-attachments/assets/55a7a6e2-0613-4364-8685-ec6c58ea8923)
Issue introduced after tdesktop 5.1.7-7-g99e88d74b

### Operating system

Kubuntu 24.04, KDE, wayland

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> Press the right mouse button on message.

I fail to reproduce with just this step

![](https://github.com/user-attachments/assets/b5e60a2a-38e5-40be-9a3d-31f1e69e7b31)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/28113
