### ISSUE TITLE
Transparent background option for Wayland

### ISSUE THREAD

**Issue by zhexyez** [telegramdesktop/tdesktop#28166]
### Is your feature request related to a problem?

Not related to a problem.

### Describe the solution you'd like

Support for system-wide or application-specific opacity setting in Wayland (I'm using Hyprland at the moment).

### Describe alternatives you've considered

No alternatives. Perhaps telegram-cli, but nah.

**Comment by ilya-fedin** [comment]
There's no opacity setting in the Wayland protocol or Qt as far as I'm aware. You're confusing something.

**Comment by zhexyez** [comment]
Yes, sorry. I'm confusing Wayland and Hyprland. Nevertheless, this request feature is correct in general. I need an opacity setting.

**Comment by ilya-fedin** [comment]
I'm not sure that's a correct request. If I understand your request right (applying transparency on top of application content), this should belong to some system-wide component. I'm able to do that with Plasma settings just fine.

**Comment by zhexyez** [comment]
Hm, I will look into this with `windowrule` in `hyprland.conf`. Not sure yet it will be possible. Some apps has this feature in their configuration file, such as `kitty` or `waybar` and does not pick up system-wide setting for an opacity. And no, it is not, quote, `"applying transparency on top of application content"`, but rather making the application window itself transparent. Give me a couple of hours, I'll check whether this is possible from `hyprland.conf`

**Comment by zhexyez** [comment]
Okay, it doesn't work. I have<br/>
`windowrule = opacity 0.5 override 0.5 override,^(telegram-desktop)$`
and
`windowrulev2 = opacity 0.5 0.5,class:(telegram-desktop),title:(telegram-desktop)`.
No effect.

**Comment by zhexyez** [comment]
Aha, this works:
`windowrule = opacity 0.5 override 0.5 override,title:(.*)(Telegram)$`.
Capital letter xD

**Comment by zhexyez** [comment]
Ah, it breaks as soon as you select chat, as the title changes. I'll try to mitigate that, but could you please change that? So the title `always` contains `Telegram` or `telegram` in it?

**Comment by zhexyez** [comment]
Nevermind, stupid me.
`windowrulev2 = opacity 0.8 0.8,class:(org.telegram.desktop)` works as expected.
