### ISSUE TITLE
Emoji window disappears on scrolling (touchscreen on linux-wayland)

### ISSUE THREAD

**Issue by tiol11** [telegramdesktop/tdesktop#28161]
### Steps to reproduce

Get to a chat room inside telegram desktop, press the emoj button, start scrolling to look for a different emoji and emojis' window disappears.
Please note, it seems just a visualization issue, because when re-opening the emoji window, the position across the emojis set has changed.

This happens on the telegram-desktop packaged by Debian, but I'm not trying it with flatpak to use the upstream version and be finally able to report it

```
$ flatpak list
Name                           Application ID                                Version           Branch               Installation
Freedesktop Platform           org.freedesktop.Platform                      23.08.20          23.08                system
Mesa                           org.freedesktop.Platform.GL.default           24.1.1            23.08                system
Mesa (Extra)                   org.freedesktop.Platform.GL.default           24.1.1            23.08-extra          system
ffmpeg-full                    org.freedesktop.Platform.ffmpeg-full                            23.08                system
openh264                       org.freedesktop.Platform.openh264             2.1.0             2.2.0                system
John Preston                   org.telegram.desktop                          5.2.3             stable               system
```

### Expected behaviour

Emoji window to be scrollable without having to re-open it

### Actual behaviour

Emoji window disappears and has to be re-opened manually (it scrolls as intended in the meanwhile)

https://github.com/user-attachments/assets/9f025989-4cfd-48ec-8e15-10285e37468c

### Operating system

Mobian trixie, tested both plasma-mobile 6.1 and phosh 0.36

### Version of Telegram Desktop

5.2.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Sorry but telegram desktop is for desktops, not for mobile phones and this doesn't seem to happen on desktops
