### ISSUE TITLE
Telegram Crashes When an Image is Copied externally 

### ISSUE THREAD

**Issue by joelpawapay** [telegramdesktop/tdesktop#28162]
### Steps to reproduce

1. Open Telegram Desktop
2. Copy an image any where on your computer into the clipboard
3. Restore Telegram
4. Telegram Freezes until image is removed from clipboard by copying text

### Expected behaviour

Telegram should not crash upon image being copied

### Actual behaviour

Telegram crashes upon image being copied

### Operating system

Arch Linux, Awesome window manager, Kernel: 6.9.7-arch1-1

### Version of Telegram Desktop

5.1.2

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
> ### Installation source
> 
> Other (unofficial) source

Sorry but third party builds aren't supported

**Comment by Aokromes** [comment]
also, very outdated build.

**Comment by joelpawapay** [comment]
Hi, mistakenly selected that, it is from the AUR so there for an official build
