### ISSUE TITLE
Linux Telegram Desktop Client doesn't display some ancient fonts characters.

### ISSUE THREAD

**Issue by dom1torii** [telegramdesktop/tdesktop#28164]
### Steps to reproduce

1. Install [ttf-ancient-fonts](https://aur.archlinux.org/packages/ttf-ancient-fonts) package (font that contains ancient characters)
2. Open Telegram Desktop
3. Type characters from ttf-ancient-fonts ([preview](https://dn-works.com/wp-content/uploads/2023/UFAS010223/Preview.pdf)). For example "𒉭".

### Expected behaviour

Telegram should display these characters.

### Actual behaviour

Displays square symbol like font is missing.

### Operating system

Arch Linux + KDE Plasma 6.1.2

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This is a third party code responsibility, if it doesn't render then it won't and you have to accept that.
