### ISSUE TITLE
Hyperlink dont highlight one as hyperlink.

### ISSUE THREAD

**Issue by MichaelMonashev** [telegramdesktop/tdesktop#28176]
### Steps to reproduce

Post message with link in .РФ domain zone
```
http://%D1%81%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9%D0%B1%D0%BE%D1%80%D0%BF%D1%80%D0%B8%D1%8D%D0%BB%D1%8C%D0%B1%D1%80%D1%83%D1%81%D1%8C%D1%8F.%D1%80%D1%84
```

### Expected behaviour

hyperlink highlighted as hyperlink.

### Actual behaviour

hyperlink stay as plain text.

### Operating system

windows 7

### Version of Telegram Desktop

5.2.3. x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> http://%D1%81%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9%D0%B1%D0%BE%D1%80%D0%BF%D1%80%D0%B8%D1%8D%D0%BB%D1%8C%D0%B1%D1%80%D1%83%D1%81%D1%8C%D1%8F.%D1%80%D1%84

That's not how domains are encoded
https://www.punycoder.com/

**Comment by MichaelMonashev** [comment]
This link I copied from FireFox address bar.

**Comment by ilya-fedin** [comment]
sorry but that's not a valid link

**Comment by MichaelMonashev** [comment]
Пост был в Избранном. В сообщении уже было две ссылки. Если копировать ссылку в зоне .рф копировать в любой текстовый редактор, то копируется
```
http://сосновыйборприэльбрусья.рф/
```
А если копировать в редактируемое сообщение, то текст сообщения добавляется
```
http://%D1%81%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9%D0%B1%D0%BE%D1%80%D0%BF%D1%80%D0%B8%D1%8D%D0%BB%D1%8C%D0%B1%D1%80%D1%83%D1%81%D1%8C%D1%8F.%D1%80%D1%84
```

Ошибка видимо в интерпретации содержимого буфера обмена.
