### ISSUE TITLE
Add support to aarch64 by removing -fcf-protection flag

### ISSUE THREAD

**Issue by looptc** [telegramdesktop/tdesktop#28173]
### Is your feature request related to a problem?

Yes, I can't compile tdesktop on aarch64 with this compilation flag.

### Describe the solution you'd like

Remove the -fcf-protection flag as this feature is only on intel and amd machines.

### Describe alternatives you've considered

I don't know how to add a feature which is from hardware, but maybe something can be done by software.

**Comment by ilya-fedin** [comment]
Not sure this request is valid as you can remove for yourself locally and there's nothing broken in official builds.

**Comment by looptc** [comment]
Then every aarch64 user included me must remove it everytime you update the source code and we do a pull... It's ok, but I don't think is a good solution for a multiplatform software.

**Comment by ilya-fedin** [comment]
Feel free to use binary packages provided by flatpak and snap. They build just fine.

**Comment by looptc** [comment]
I don't like to run anything I can't see sourcely. But thanks anyway.

**Comment by ilya-fedin** [comment]
I don't see how this issue is valid given that flatpak and snap build without removing it?

**Comment by looptc** [comment]
The `-fcf-protection` flag is a compiler option used in GCC to enable Control-Flow Enforcement Technology (CET) to provide additional security against certain types of attacks, such as Return-Oriented Programming (ROP) and Jump-Oriented Programming (JOP). This technology works by using new CPU instructions and mechanisms to enforce control flow integrity.

However, CET and the `-fcf-protection` flag are specific to x86 architecture (Intel and AMD CPUs) and are not applicable to the AArch64 (ARM 64-bit) architecture.

For AArch64, similar protections are provided by different mechanisms, such as:

1. **Pointer Authentication (PAC)**: This involves using cryptographic signatures to ensure the integrity of pointers and to prevent attackers from controlling the program counter (PC) or return addresses.
2. **Branch Target Identification (BTI)**: This restricts the targets of indirect branch instructions to valid locations, thus mitigating jump-oriented programming attacks.

If you are working on improving security on AArch64, you should look into compiler options and hardware features that support PAC and BTI. In GCC, for example, you might use:

- `-msign-return-address=all` and `-mbranch-protection=standard` for enabling Pointer Authentication and Branch Target Identification.
  
These options will enable similar control-flow integrity protections tailored for the ARM architecture.

**Comment by ilya-fedin** [comment]
I mean flatpak and snap build for arm64 without any changes to source code. Therefore the issue doesn't seem to be valid, no changes needed to build for arm64.

**Comment by looptc** [comment]
Following the steps to compile it (https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md) gives error because that flag is on.

Also, I don't know if the build you provide by flatpak and/or snap are replacing the flag by the proponer ones I pasted in the before comment.

**Comment by ilya-fedin** [comment]
> If you are working on improving security on AArch64

There's sadly no developer with ARM Linux machine so there's no any work on ARM64 support (besides of what worked by itslef, like flatpak/snap arm builds). If you want ARM64 improvements, the only way to get them is creating a PR with them, as no one else except of you will develop it.

**Comment by ilya-fedin** [comment]
> Following the steps to compile it (https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md) gives error because that flag is on.

I'm really doubt that's the only thing you need to change to build on any other arch than x86_64. It likely uses precompiled x86_64 only binaries.

**Comment by looptc** [comment]
I'm using the source code version from GitHub compiled by me, following the steps en in the md I shared before, in aarch64, since more than a week before...

**Comment by ilya-fedin** [comment]
I'm not sure how that is possible, it was using x86_64 only cmake before 2 days ago...

**Comment by looptc** [comment]
The first time I compiled, ~a week ago I had to change the cmake URL to match aarch64 build, and compiled.
Then you updated the source and I only had to fix the compiling flags from the Dockerfile.

Seems that actually uses the cmake from rockylinux image: https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/build/docker/centos_env/Dockerfile#L19C20-L19C25

No more changes are need IMHO.

**Comment by ilya-fedin** [comment]
Ok, feel free to create a PR making so that -fcf-protection is passed on x86_64 only and I will happily review it. I can't develop it since I have no ARM64 hardware, sorry.

**Comment by looptc** [comment]
Don't worry, I couldn't be faster because there were some issues with clonning m4 submodules from freedesktop.

Here is the PR link by if you can't relate to this issue and to have it linked by if some future I need to review it: https://github.com/telegramdesktop/tdesktop/pull/28179

Thanks!
