### ISSUE TITLE
Error interpreting clipboard contents.

### ISSUE THREAD

**Issue by MichaelMonashev** [telegramdesktop/tdesktop#28177]
### Steps to reproduce

Если из адресной строки FireFox-а скопировать ссылку в зоне .рф в любой текстовый редактор, то копируется
```
http://сосновыйборприэльбрусья.рф/
```
А если копировать в редактируемое сообщение в десктопную телегу, то в текст сообщения добавляется
```
http://%D1%81%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9%D0%B1%D0%BE%D1%80%D0%BF%D1%80%D0%B8%D1%8D%D0%BB%D1%8C%D0%B1%D1%80%D1%83%D1%81%D1%8C%D1%8F.%D1%80%D1%84
```
Само сообщение в Избранном. И в нём уже было две ссылки.

Ошибка видимо в интерпретации содержимого буфера обмена.

### Expected behaviour

Скопируется ссылка http://сосновыйборприэльбрусья.рф/

### Actual behaviour

Вместо неё копируется http://%D1%81%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9%D0%B1%D0%BE%D1%80%D0%BF%D1%80%D0%B8%D1%8D%D0%BB%D1%8C%D0%B1%D1%80%D1%83%D1%81%D1%8C%D1%8F.%D1%80%D1%84

### Operating system

windows 7

### Version of Telegram Desktop

5.2.3. x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This is english only bugtracker
