### ISSUE TITLE
Pressing ESC from a chat no longer lands us in the (chat-)searchbox as it used to.

### ISSUE THREAD

**Issue by T3rminat0r** [telegramdesktop/tdesktop#28178]
### Steps to reproduce

1. open any chat in TG Desktop
2. press ESC

### Expected behaviour

The Cursor should be in the search box, so I can start typing another chat's name to switch to it, without having to use the mouse (as the behaviour used to be...)

### Actual behaviour

The cursor is "no where", starting to type after pressing ESC to close a chat does nothing, without first having to click into the searchbox in order to start searching.

### Operating system

Windows

### Version of Telegram Desktop

v5.2.3 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@T3rminat0r For me the cursor is indeed "no where", but when you start typing it instantly focuses the search field and filters the chats as if the cursor was in the field the whole time.

**Comment by ilya-fedin** [comment]
@T3rminat0r this points to the fact you missed some steps to reproduce. It might be some input-related software installed on your PC.
