### ISSUE TITLE
Crash after screen locking

### ISSUE THREAD

**Issue by LetzteInstanz** [telegramdesktop/tdesktop#28171]
### Steps to reproduce

1. Wait screen locking
2. Tg crashes after short time

### Expected behaviour

No crash

### Actual behaviour

Crash

### Operating system

Ubuntu 24.04

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

### Crash ID

95456596-aa29-4fc7-b0ad41a8-5cb6a504

### Logs

[log.txt](https://github.com/user-attachments/files/16246377/log.txt)

**Comment by Aokromes** [comment]
no need of open duplicate ticket for each afected linux distribution.

**Comment by LetzteInstanz** [comment]
> no need of open duplicate ticket for each afected linux distribution.

That issue hasn't a crash dump ID and a log text.

**Comment by Aokromes** [comment]
> > no need of open duplicate ticket for each afected linux distribution.
> 
> That issue hasn't a crash dump ID and a log text.

you can add them there.
