### ISSUE TITLE
Page error on Raspbian

### ISSUE THREAD

**Issue by StanleyMorgan** [telegramdesktop/tdesktop#28174]
### Steps to reproduce

Install latest arm64 snap build on Raspberry Pi 5:
sudo apt update
sudo apt install snapd
sudo reboot
sudo snap install snapd
sudo snap install telegram-desktop

Launch Telegram:
telegram-desktop

### Expected behaviour

Telegram launch

### Actual behaviour

Not started with error

### Operating system

Debian GNU/Linux 12 (bookworm)

### Version of Telegram Desktop

5.2.3

### Installation source

Snap

### Logs

```shell
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/lisitsin/snap/telegram-desktop/common/.cache/gio-modules/libgiolibproxy.so
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
../../../glib/gprintf.c:350: failed to allocate memory
Aborted
```

**Comment by ilya-fedin** [comment]
Sorry but your hardware is not supported by some tdesktop dependencies. Nothing could be done about that.
