### ISSUE TITLE
Sumerian characters support

### ISSUE THREAD

**Issue by sfagnumsky** [telegramdesktop/tdesktop#28184]
### Is your feature request related to a problem?

Sumerian characters aren't displayed in chats nor usernames

![изображение_2024-07-21_193125412](https://github.com/user-attachments/assets/0061e3fe-788b-48bb-9498-482bb3118846)
![изображение_2024-07-21_193132676](https://github.com/user-attachments/assets/6d24b93e-0c48-43a9-a0ed-5f503cbabb8b)

### Describe the solution you'd like

Making sumerian characters display correctly

### Describe alternatives you've considered

I see no alternatives, however

### Additional context

Dear friends of mine and I, we are big fans of Sumerian history, culture and language with its unique writing system. One of our biggest dreams is to communicate via Telegram using Sumerian symbols. Unfortunately, it isn't possible right now in Telegram desktop client for Windows

**Comment by ilya-fedin** [comment]
This means you need to install fonts for the characters
