### ISSUE TITLE
Qt version issue

### ISSUE THREAD

**Issue by hui87667137** [telegramdesktop/tdesktop#28187]
### Steps to reproduce

QT6 has already been installed in my window11 system. When executing configuration.bat x64- D TDESKTOP-API-ID=YOUR-PAPI-ID - D TDESKTOP-API-HASH=YOUR-PAPI-HASH

### Expected behaviour

complete

### Actual behaviour

Choosing Qt 5.
Choosing Qt 5.15.13
Warn about uninitialized values.
Version: 5.2.3
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
CMake Error at cmake/external/qt/package.cmake:61 (message):
Configured Qt version 6.2.4 does not match requested version 5.15.13.
Please reconfigure.
Call Stack (most recent call first):
CMakeLists.txt:60 (include)
-- Configuring incomplete, errors occurred!
FAILED

### Operating system

window11

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
The build system won't work with your system installed Qt, it will use only the one built by prepare.py
