### ISSUE TITLE
xz.git repository changed the URL

### ISSUE THREAD

**Issue by looptc** [telegramdesktop/tdesktop#28189]
Well, that's not a bug itself, but I couldn't find any better category in the list of issue submit. Sorry.

### Steps to reproduce

1. Compile the client for GNU/Linux as explained in https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-linux.md, step: ./tdesktop/Telegram/build/prepare/linux.sh

### Expected behaviour

The xz.git project may be cloned from https://github.com/tukaani-project/xz as explained in https://git.tukaani.org/ 's **Note**

### Actual behaviour

It breaks when building the docker image because it's using the URL which is forbidden actually.

### Operating system

GNU/Linux

### Version of Telegram Desktop

master branch from github

### Installation source

Other (unofficial) source

**Comment by coffnix** [comment]
confirmed.

`---------------------------------COMMANDS-LIST----------------------------------
rm -rf xz
git clone -b v5.4.5 https://git.tukaani.org/xz.git
cd xz
sed -i '' '\@check_symbol_exists(futimens "sys/types.h;sys/stat.h" HAVE_FUTIMENS)@d' CMakeLists.txt
CFLAGS="$UNGUARDED" CPPFLAGS="$UNGUARDED" cmake -B build . \
-D CMAKE_OSX_DEPLOYMENT_TARGET:STRING=$MACOSX_DEPLOYMENT_TARGET \
-D CMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
-D CMAKE_INSTALL_PREFIX:STRING=$USED_PREFIX
cmake --build build $MAKE_THREADS_CNT
cmake --install build
--------------------------------------------------------------------------------
Cloning into 'xz'...
fatal: repository 'https://git.tukaani.org/xz.git/' not found
[4/25](Libraries/xz): FAILED`

**Comment by john-preston** [comment]
Thanks!
