### ISSUE TITLE
Application crashed on incoming or outgoing calls

### ISSUE THREAD

**Issue by djdejawu** [telegramdesktop/tdesktop#28190]
### Steps to reproduce

OS: ___Fedora 39___
Kernel: ___6.9.9-100.fc39.x86_64___
Binary: ___Telegram___

When I'm try to call somebody application is crashed with SIGABRT.
```
$ coredumpctl -1
TIME                           PID  UID  GID SIG     COREFILE EXE                                                   SIZE
Mon 2024-07-22 18:38:18 EST 180086 1000 1000 SIGABRT present  /home/dejawu/Downloads/tsetup.5.2.3/Telegram/Telegram 80.8M
```

### Expected behaviour

Normal call in new window

### Actual behaviour

App crashed without Crash ID

### Operating system

Fedora 39 (x86_64)

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

### Crash ID

7d60160c-2881-49c9-f075acbf-53a3b7be

### Logs

```shell
ApiId: 2040
Assertion: "!boundingRect.isEmpty()" calls_video_bubble.cpp:62
Binary: Telegram
Launched: 22.07.2024 23:08:13
OpenGL: Enabled
OpenGL Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 17.0.6, DRM 3.57, 6.9.9-100.fc39.x86_64)
Platform: Linux
UserTag: 29f5849e0dc4746e
Version: 5002003

Caught signal 6 (SIGABRT) in thread 140117347573184
Google Breakpad caught a crash, minidump written in thread 140117347573184
Minidump: /home/dejawu/.local/share/TelegramDesktop/tdata/dumps/7d60160c-2881-49c9-f075acbf-53a3b7be.dmp

```

**Comment by Aokromes** [comment]
can't reproduce on fedora 40.

**Comment by djdejawu** [comment]
@Aokromes please use Fedora 39

**Comment by ilya-fedin** [comment]
Sorry but crash reports are actionable only with a Crash ID. You have to get the crash ID.

**Comment by ilya-fedin** [comment]
> please use Fedora 39

Sorry but there's no resources to test every existing distro in the universe. Actually the only tested configurations are the default flavour of Ubuntu 22.04 and WSL. Another thing to mention is that Qt also doesn't support every possible distro, if your configuration is not in the list of https://doc.qt.io/qt-6/supported-platforms.html#linux-x11 then you can't expect Qt will work reliably on your system. As you can see, Fedora is not in the list.

**Comment by djdejawu** [comment]
@ilya-fedin If app was crashed in my os and I will be able to search your crash id, offcourse I would provide it for you. But in fact in my fedora 39 and my Gnome it's just closes window without any other debug info and did not provide crash id what you expect. This problem apears about a week ago.

**Comment by ilya-fedin** [comment]
Did you enable beta as explained in the issue template?

**Comment by djdejawu** [comment]
@ilya-fedin nope. did'nt found this in bug report template.

**Comment by ilya-fedin** [comment]
@djdejawu right under the "Crash ID" header and above the text field

**Comment by djdejawu** [comment]
@ilya-fedin update to beta and debug windows is now I see. check crash id. I've update issue.

**Comment by ilya-fedin** [comment]
Sorry but the crash report you sent is corrupted due to the binary being placed in a path with non-latin characters. Please move it and send a new crash report.
