### ISSUE TITLE
cursor misalignment

### ISSUE THREAD

**Issue by RandomGuyNumber731** [telegramdesktop/tdesktop#28198]
### Steps to reproduce

1. open telegram
2. open any chat
3. look at input box
![2024-07-27_00-13](https://github.com/user-attachments/assets/566f1a48-c273-42d4-8f60-31fad74f012c)

### Expected behaviour

usual cursor look

### Actual behaviour

cursor is unpleasingly high

### Operating system

Linux Mint 21.3 Cinnamon

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@RandomGuyNumber731 Please try 5.2.4 beta version.

**Comment by RandomGuyNumber731** [comment]
yeah that work thx
