### ISSUE TITLE
Group's ban list managment

### ISSUE THREAD

**Issue by bertmsk** [telegramdesktop/tdesktop#2819]
### Steps to reproduce
1. Create a group
2. Ban someone
3. Try to unban him :)

### Expected behaviour
A dialog window to manage banned users

### Actual behaviour
Nothing still implemented

**Comment by luckydonald** [comment]
You currently have to use a mobile client to do that :/

**Comment by RememberTheAir** [comment]
Or a bot :(

**Comment by Aokromes** [comment]
already implemented.
