### ISSUE TITLE
Unexpected window context menu appeared instead of photo context menu on Windows 10 x64

### ISSUE THREAD

**Issue by JuraLys** [telegramdesktop/tdesktop#28199]
### Steps to reproduce

1. Open photo which was sent before and right click on it

### Expected behaviour

Photo context menu should appear

### Actual behaviour

Window context menu appears, see
![teleg-context-menu](https://github.com/user-attachments/assets/fc989650-a2fb-4d97-9bb2-7b10df39e849)

### Operating system

Microsoft Windows [Version 10.0.19045.4412] 

### Version of Telegram Desktop

5.2.4 x64 beta

### Installation source

Other (unofficial) source

**Comment by john-preston** [comment]
@JuraLys Should be better in beta version 5.2.5.
