### ISSUE TITLE
Revolutionary Favorite Messages (Saved Messages)

### ISSUE THREAD

**Issue by dukesaeed** [telegramdesktop/tdesktop#28194]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

1- In a channel/group/chat user **Marks a Post as Favorite** (or saved message)
2- In upper section of channel/group/chat User can **Show Only Favorite Mesasages by simply clicking One icon**

![Suggestion](https://github.com/user-attachments/assets/d28e37cd-0f5c-46c4-9d38-2c4d0ff2af58)

### Describe alternatives you've considered

Null

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
