### ISSUE TITLE
Copied peer id is not ready to use

### ISSUE THREAD

**Issue by lilydjwg** [telegramdesktop/tdesktop#28205]
### Steps to reproduce

1. Enable "Show Peer IDs in Profile" in "Experimental settings"
2. Open a chat or user's profile, and try to copy their id

### Expected behaviour

I can copy an ID without commas in the middle and so can be easily used in other places (e.g. reference in a bot request, or  query in a database).

### Actual behaviour

![图片](https://github.com/user-attachments/assets/af40ebbd-c980-48d2-84fc-b05200604671)
```
id: 1,006,503,122
```

I have to manually delete those commas no matter whether I select and copy, or right click and select "Copy".

### Operating system

Arch Linux

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@lilydjwg Just click on it.

**Comment by lilydjwg** [comment]
Oh thanks! I don't know why I didn't try it.
