### ISSUE TITLE
Add other standard ways for navigatating the chat previews, besides the mouse wheel/scroll

### ISSUE THREAD

**Issue by a-pav** [telegramdesktop/tdesktop#28206]
### Is your feature request related to a problem?

Yes, the problem of navigating chat previews. 

### Describe the solution you'd like

Currently, there's only one way to navigate the chat previews, and that is by mouse wheel/scroll.
So in addition to a **_scroll to bottom_** button (#28147), other standard ways of navigation should be added as well.
These are usually `Arrow up`, `Arrow down`, `Page up`, `Page down` keys. `End` and/or `Return` keys for _scrolling to the bottom_ are only intuitive too.

### Describe alternatives you've considered

Not as an alternative, but numpad arrows keys should be working the same too.

**Comment by Aokromes** [comment]
duplicate.
