### ISSUE TITLE
Ubuntu desktop app crashes after non-standard emoji choice in "Share to" window

### ISSUE THREAD

**Issue by ArtfulVampire** [telegramdesktop/tdesktop#28203]
### Steps to reproduce

Share any post from channel to any chat or "Saved messages"
type any emoji in text, e.g. `:heart:`, in the additional text/comment field
Choose any emoji from a pop-up suggest from a non-standard emoji set
![tg](https://github.com/user-attachments/assets/f4a34646-2605-4764-a3bf-6a936867e213)

The problem persists for at least some weeks

### Expected behaviour

The non-standard emoji is successfully added to the comment

### Actual behaviour

App crashes with 100% reproducibility

### Operating system

Ubuntu 22.04.4

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

### Crash ID

d2461f69-c54b-48b1-9b344dbf-76064b98

**Comment by john-preston** [comment]
Thanks! I'll fix that for the next version.
