### ISSUE TITLE
Telegram crashes after the latest beta update was installed

### ISSUE THREAD

**Issue by Milk-Cool** [telegramdesktop/tdesktop#28202]
### Steps to reproduce

1. Update and restart (or launch) Telegram Desktop on BETA channel
2. Observe this error:
```
Caught signal 11 (SIGSEGV) in thread 131503868599744
Google Breakpad caught a crash, minidump written in thread 131503868599744
Minidump: /home/***/.local/share/TelegramDesktop/tdata/dumps/8c338eb9-d7c3-4d21-e5eb9db6-65cb399e.dmp
```

### Expected behaviour

No crashes

### Actual behaviour

Constant crashes

### Operating system

Ubuntu 24.04 LTS

### Version of Telegram Desktop

Can't launch app => can't see the version, updated at ~5am UTC

### Installation source

Static binary from official website

### Crash ID

8eaa41b3-e316-48af-784bc7be-21e80379

### Logs

```shell
Can't access settings
```

**Comment by mrmuminov** [comment]
Also Pop_!OS 22.04 LTS

**Comment by Andrew15-5** [comment]
I restarted my machine just now and suddenly Telegram wasn't running. Apparently I hit the same issue on Pop!_OS 22.04. Installed 5.2.4, and it started downloading the latest version by default. I closed the window and the regular UI showed up. So it's definitely a problem with 5.2.5.

**Comment by Jeronimo17** [comment]
Crash ID: 57e13f3c-b55a-4945-8a3046b6-fcfb1741

**Comment by Jeronimo17** [comment]
I don't know how to go back to the old version without losing the login (I'm in a place with only my laptop 😓).

**Comment by Novosti1** [comment]
Centos 8, same problem, just crashed 30 minutes ago, and i cant restart it.

**Comment by Andrew15-5** [comment]
> I don't know how to go back to the old version without losing the login (I'm in a place with only my laptop 😓).

On Linux, it's as easy as downloading an older version and replacing 2 binaries.

**Comment by Novosti1** [comment]
> > I don't know how to go back to the old version without losing the login (I'm in a place with only my laptop 😓).
> 
> On Linux, it's as easy as downloading an older version and replacing 2 binaries.

You can download old version, but on first start, it's will automaticly updates to last one.

**Comment by Andrew15-5** [comment]
> Installed 5.2.4, and it started downloading the latest version by default. I closed the window and the regular UI showed up.

Just close the window.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/28201

**Comment by john-preston** [comment]
@Andrew15-5 I've deployed 5.2.6 beta which should start fine on X11.

**Comment by Andrew15-5** [comment]
Yeah, I've installed it right away, thanks. Was the problem with pinned commit hash? Because everything else is just version update stuff.

**Comment by john-preston** [comment]
@Andrew15-5 The fix was in a dependent library, our fork of webrtc, commit hash just updated the revision for the dependency.

**Comment by Andrew15-5** [comment]
> commit hash just updated the revision for the dependency.

Well, yeah, that's what I meant. I didn't check what this hash was for. Lemme do that now.

https://github.com/desktop-app/tg_owt/commit/4a60ce1ab9fdb962004c6a959f682ace3db50cbd
https://wayland.freedesktop.org/docs/html/apb.html#Client-classwl__display_1af048371dfef7577bd39a3c04b78d0374

Ah, yes, the missing null pointer check, classic. ;)

Will casually drop the RIIR bomb here and go back to writing (contributing) in Rust.
