### ISSUE TITLE
"View Sticker Set" context menu item is broken (does nothing) for Favorites and Recently Used sections

### ISSUE THREAD

**Issue by ratijas** [telegramdesktop/tdesktop#28209]
### Steps to reproduce

1. Add some stickers as favorites.
2. Send some stickers, so that they appear in the Recently Used section.
3. Right click on stickers in those sections, and select "View Sticker Set" menu item.

### Expected behaviour

No popup with Sticker Set info appears.

### Actual behaviour

Sticker Set popup should appear. Ironically, it appears for context menus of stickers inside stickers sets, making it kinda "works when it's pointless".

Not all the stickers are affected, but most of them: only 4 out of 20 Recently Used stickers, and none of the Favorites could show the popup.  out of those 4 there were both video and static stickers, and they were arranged in random positions, so I don't see any correlation there.

It doesn't matter if the Emoji/Stickers/GIFs view is a popup itself or a sidebar.

### Operating system

Arch Linux, KDE/Plasma

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Should be better now.

**Comment by dimas1980200** [comment]
+
***@***.***

вт, 6 авг. 2024 г., 4:19 ratijas ***@***.***>:
