### ISSUE TITLE
`Alt+Click` might not be the optimal keybind for opening chat previews

### ISSUE THREAD

**Issue by a-pav** [telegramdesktop/tdesktop#28207]
### Steps to reproduce

1. Set your keyboard layout to one of the layouts listed below. 

```sh
setxkbmap -model pc105 -layout fr 
setxkbmap -model pc105 -layout br
setxkbmap -model pc105 -layout ar
setxkbmap -model pc105 -layout ir
```

3. `Alt+Click` on chat photos **using the right alt key** (i.e. `Alt_R`.)

### Expected behaviour

Chat preview to be opened.

### Actual behaviour

Chat is opened as usual; as if you've clicked on it without holding the `Alt` modifier.

### The reason
The reason is that when you're using those languages as your keyboard layout (there are probably more layouts like them, but those are the ones I've tested), `Alt_R` is converted to ‍‍`ISO_Level3_Shift` (observed by `xev`.)

Basically this means that when you're using those layouts, `Alt` key is no longer the usual two separate keys available on two sides of your keyboard. Now you only have one `Alt` key, and that is the left alt (`Alt_L`).

### Affected users
Left hand mouse users who use such keyboard layouts are specially affected by the current behavior.
But you could say that anyone who uses the right Alt key while on such keyboard layouts is also affected.

### Describe the solution you'd like
I think the easiest solution is to simply add a keybinding for `ISO_Level3_Shift + Click`. Users don't need to know about it, they keep using `Alt+Click` as before, but they no longer experience inconsistency while using such keyboard layouts.

### Operating system

Linux, X11

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Sorry but this doesn't sound like a valid bug report as the real alt key still works according to your description.

**Comment by ilya-fedin** [comment]
If the keybind is inconvenient for you, that doesn't make it a bug

**Comment by ilya-fedin** [comment]
What I said is inconvenience isn't qualified as a bug. You may disagree but that's how it is.
