### ISSUE TITLE
Some theme colors only properly apply from a package file with a background image, but not otherwise

### ISSUE THREAD

**Issue by tdfairey** [telegramdesktop/tdesktop#2821]
### Steps to reproduce
1. Create a colors.tdesktop-theme file, using [the default](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/Resources/default.tdesktop-theme) as a template.
2. Within colors.tdesktop-theme, set `msgServiceBg` to `#FF00FF` (magenta, so it's easily noticed)
3. Apply this single theme file using the file picker
4. Send a sticker in any chat
5. Observe that the timestamp for the sticker from step 4 is not magenta.
6. Scroll in a chat with history until the system date header appears, observe that the header is not magenta.
7. Create a zip file with colors.tdesktop-theme inside and name it mytheme.tdesktop-theme
8. Apply the zip file as a theme.
9. Repeat steps 5 and 6, notice no change.
10. Repeat step 7, but add (any) tiled.png file to the archive as well.
11. Repeat steps 5 and 6, notice that both the timestamp and date header are now magenta.

### Expected behaviour
Steps 5, 6, and 9 should yield the same result as step 11, which is the timestamp and header being magenta.

### Actual behaviour
In steps 5, 6, and 9, the defined color for `msgServiceBg` is not respected by the theme system, and is instead generated from the existing chat background image.

### Configuration
**Operating system:**
Windows 10.0.14393 | OS X 10.12.2
**Version of Telegram Desktop:**
1.0 | 1.0 alpha

**Comment by john-preston** [comment]
@tdfairey Themes have several tricky colors when it comes to background colors. This key (and several others) are adjusted to the current background by hue, so they look nice with any background image user chooses. The exact value from theme is used for those keys only if theme author also chose the background image which fits with those colors.

**Comment by tdfairey** [comment]
@john-preston The consideration to the user's background is very understandable. It however is my belief that removing the control from the theme artist in an abstract way may not be the best solution.  Instead of doing this, it may be advantageous to make the hue-matched color available to the theme artist as a value that can be assigned and updated dynamically, even across parts of the theme that are currently static. In this way, the artist can decide how their creation looks, not the user. The potential outcomes are that either artists start incorporating the user's selected background color into more parts of the theme, or it being overridden where the artist feels necessary to achieve a certain look. Both are worth consideration, and are not necessarily bad.

If nothing else, a list of the keys that are generated in the absence of a background would make an excellent addition to the theme documentation when it is complete.

**Comment by john-preston** [comment]
@tdfairey Currently it's only service messages and scrollbar colors: "msgServiceBg", "msgServiceBgSelected", "historyScrollBg", "historyScrollBgOver", "historyScrollBarBg", "historyScrollBarBgOver".
