### ISSUE TITLE
Move folders from the sidebar to the top

### ISSUE THREAD

**Issue by Jaymz665** [telegramdesktop/tdesktop#28210]
### Is your feature request related to a problem?

This is not a serious problem, rather a kind of discomfort, on mobile devices using linux, the presence of a folder on the side "eats up" part of the useful space

### Describe the solution you'd like

The web versions of telegram (version A and version K) have folders above the chats, which is much more convenient and practical, plus the entire space is ergonomically used in portrait mode. I would really like to see this in telegram desktop

### Describe alternatives you've considered

The only reasonable alternative to transferring folders is to manually adjust the size of the sidebar or icons

**Comment by Aokromes** [comment]
duplicate.
