### ISSUE TITLE
[security] macOS: the code-signature changed unexpectedly in 5.3.0

### ISSUE THREAD

**Issue by core-code** [telegramdesktop/tdesktop#28215]
### Steps to reproduce

all previous releases were signed by
John Preston (63FLR8MQA9)

the new release was signed by
Telegram FZ-LLC (C67CF9S4VU)

there is no mention about any change in ownership or signature in the release notes. is this a legitimate release?

### Expected behaviour

continued use of expected signature John Preston (63FLR8MQA9)

### Actual behaviour

use of new and unexpected code-signature

### Operating system

macOS

### Version of Telegram Desktop

5.3.0

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Yeah, that's still me: https://github.com/telegramdesktop/tdesktop/commit/db80096e6b5d9b839d29abcabc6ad56e68884003

I have no idea how this should be presented or what will system say or idk.

My old personal certificate expired and Apple (hate them) couldn't renew my membership and then locked me out of my developer account, still can't get in.

So I've used the corporate certificate, this identity was used for many years already when signing the Mac App Store builds:

https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/build/build.sh#L332-L335

**Comment by core-code** [comment]
thanks for the confirmation that the change is ok!
