### ISSUE TITLE
Markdown backtricks should be supported according to specification

### ISSUE THREAD

**Issue by gwpl** [telegramdesktop/tdesktop#28218]
### Steps to reproduce

According to specification three or more backtricks open block that is closed by same amount for multiline , e.g.:

``````
````````` example opening
```
So three can be inside
```
````````` example closing
``````

And for one liners , any number of backticks open code line that is closed by same amount e.g. ``` ` can open ```` and close with ```` like this ` ``` .

### Expected behaviour

Support for three or more opening/closing backticks like in specs (so i side one can include codeblocks containing lines with other amounts of backtricks). 
Should work on Desktop/Android/etc, allowing to send code snippets with backticks, by fencing them with other amount of backticks according to specification.

### Actual behaviour

It seems to focus on three backticks for multi line and single backticks on single line, and making unclear how to surround code blocks with backticks (as according to specs we should just surround by backticks fence with other amount of backticks).

### Operating system

Android, Linux

### Version of Telegram Desktop

5.2.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop has its own markdown dialect
