### ISSUE TITLE
Coredump after upgrading to 5.3.1

### ISSUE THREAD

**Issue by gbcox** [telegramdesktop/tdesktop#28221]
### Steps to reproduce

Application won't start after upgrade to 5.3.1

### Expected behaviour

Normal operation.  Had to back out to 5.2.6 Linux binary.  5.3.1 immediately crashes.

### Actual behaviour

 PID: 453349 (Telegram)
           UID: 1000 (gbcox)
           GID: 1000 (gbcox)
        Signal: 11 (SEGV)
     Timestamp: Thu 2024-08-01 19:50:25 PDT (4min 48s ago)
  Command Line: ./Telegram
    Executable: /home/gbcox/Telegram/Telegram
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.kde.konsole@77c847c3d4954e2db6f67a2feafeec54.service
          Unit: user@1000.service
     User Unit: app-org.kde.konsole@77c847c3d4954e2db6f67a2feafeec54.service
         Slice: user-1000.slice
     Owner UID: 1000 (gbcox)
       Boot ID: 769046fcba3d458283f454720169cfaa
    Machine ID: 7563e353f11040c19adce9f78704db5a
      Hostname: charon
       Storage: /var/lib/systemd/coredump/core.Telegram.1000.769046fcba3d458283f454720169cfaa.453349.1722567025000000.zst (present)
  Size on Disk: 2.7M
       Message: Process 453349 (Telegram) of user 1000 dumped core.
                
                Module libnss_resolve.so.2 from rpm systemd-255.10-1.fc40.x86_64
                Module libnss_mdns4_minimal.so.2 from rpm nss-mdns-0.15.1-11.fc40.x86_64
                Module libnss_myhostname.so.2 from rpm systemd-255.10-1.fc40.x86_64
                Module libgvfscommon.so from rpm gvfs-1.54.2-1.fc40.x86_64
                Module libgvfsdbus.so from rpm gvfs-1.54.2-1.fc40.x86_64
                Module libdconfsettings.so from rpm dconf-0.40.0-12.fc40.x86_64
                Module libjson-glib-1.0.so.0 from rpm json-glib-1.8.0-3.fc40.x86_64
                Module libatspi.so.0 from rpm at-spi2-core-2.52.0-1.fc40.x86_64
                Module libtracker-sparql-3.0.so.0 from rpm tracker-3.7.3-1.fc40.x86_64
                Module libcloudproviders.so.0 from rpm libcloudproviders-0.3.5-3.fc40.x86_64
                Module libatk-bridge-2.0.so.0 from rpm at-spi2-core-2.52.0-1.fc40.x86_64
                Module libatk-1.0.so.0 from rpm at-spi2-core-2.52.0-1.fc40.x86_64
                Module libgtk-3.so.0 from rpm gtk3-3.24.43-1.fc40.x86_64
                Module libdatrie.so.1 from rpm libdatrie-0.2.13-9.fc40.x86_64
                Module libpangoft2-1.0.so.0 from rpm pango-1.54.0-1.fc40.x86_64
                Module libthai.so.0 from rpm libthai-0.1.29-8.fc40.x86_64
                Module libpixman-1.so.0 from rpm pixman-0.43.4-1.fc40.x86_64
                Module libxcb-shm.so.0 from rpm libxcb-1.17.0-1.fc40.x86_64
                Module libxcb-render.so.0 from rpm libxcb-1.17.0-1.fc40.x86_64
                Module libXrender.so.1 from rpm libXrender-0.9.11-6.fc40.x86_64
                Module libjpeg.so.62 from rpm libjpeg-turbo-3.0.2-1.fc40.x86_64
                Module libXinerama.so.1 from rpm libXinerama-1.1.5-6.fc40.x86_64
                Module libXrandr.so.2 from rpm libXrandr-1.5.4-3.fc40.x86_64
                Module libXcomposite.so.1 from rpm libXcomposite-0.4.6-3.fc40.x86_64
                Module libXfixes.so.3 from rpm libXfixes-6.0.1-3.fc40.x86_64
                Module libXdamage.so.1 from rpm libXdamage-1.1.6-3.fc40.x86_64
                Module libXcursor.so.1 from rpm libXcursor-1.2.1-7.fc40.x86_64
                Module libXext.so.6 from rpm libXext-1.3.6-1.fc40.x86_64
                Module libXi.so.6 from rpm libXi-1.8.1-5.fc40.x86_64
                Module libwayland-egl.so.1 from rpm wayland-1.22.0-3.fc40.x86_64
                Module libwayland-cursor.so.0 from rpm wayland-1.22.0-3.fc40.x86_64
                Module libxkbcommon.so.0 from rpm libxkbcommon-1.6.0-2.fc40.x86_64
                Module libpangocairo-1.0.so.0 from rpm pango-1.54.0-1.fc40.x86_64
                Module libepoxy.so.0 from rpm libepoxy-1.5.10-6.fc40.x86_64
                Module libcairo-gobject.so.2 from rpm cairo-1.18.0-3.fc40.x86_64
                Module libfribidi.so.0 from rpm fribidi-1.0.14-2.fc40.x86_64
                Module libpango-1.0.so.0 from rpm pango-1.54.0-1.fc40.x86_64
                Module libcairo.so.2 from rpm cairo-1.18.0-3.fc40.x86_64
                Module libgdk_pixbuf-2.0.so.0 from rpm gdk-pixbuf2-2.42.11-1.fc40.x86_64
                Module libgdk-3.so.0 from rpm gtk3-3.24.43-1.fc40.x86_64
                Module libzstd.so.1 from rpm zstd-1.5.6-1.fc40.x86_64
                Module liblz4.so.1 from rpm lz4-1.9.4-6.fc40.x86_64
                Module libcap.so.2 from rpm libcap-2.69-8.fc40.x86_64
                Module libsystemd.so.0 from rpm systemd-255.10-1.fc40.x86_64
                Module libdbus-1.so.3 from rpm dbus-1.14.10-3.fc40.x86_64
                Module libwayland-client.so.0 from rpm wayland-1.22.0-3.fc40.x86_64
                Module libblkid.so.1 from rpm util-linux-2.40.1-1.fc40.x86_64
                Module libXau.so.6 from rpm libXau-1.0.11-6.fc40.x86_64
                Module libbrotlicommon.so.1 from rpm brotli-1.1.0-3.fc40.x86_64
                Module libgraphite2.so.3 from rpm graphite2-1.3.14-15.fc40.x86_64
                Module liblzma.so.5 from rpm xz-5.4.6-3.fc40.x86_64
                Module libpcre2-8.so.0 from rpm pcre2-10.44-1.fc40.x86_64
                Module libffi.so.8 from rpm libffi-3.4.4-7.fc40.x86_64
                Module libselinux.so.1 from rpm libselinux-3.6-4.fc40.x86_64
                Module libmount.so.1 from rpm util-linux-2.40.1-1.fc40.x86_64
                Module libgmodule-2.0.so.0 from rpm glib2-2.80.3-1.fc40.x86_64
                Module libxcb.so.1 from rpm libxcb-1.17.0-1.fc40.x86_64
                Module libbrotlidec.so.1 from rpm brotli-1.1.0-3.fc40.x86_64
                Module libharfbuzz.so.0 from rpm harfbuzz-8.5.0-1.fc40.x86_64
                Module libpng16.so.16 from rpm libpng-1.6.40-3.fc40.x86_64
                Module libbz2.so.1 from rpm bzip2-1.0.8-18.fc40.x86_64
                Module libz.so.1 from rpm zlib-ng-2.1.7-1.fc40.x86_64
                Module libxml2.so.2 from rpm libxml2-2.12.8-1.fc40.x86_64
                Module libglib-2.0.so.0 from rpm glib2-2.80.3-1.fc40.x86_64
                Module libgobject-2.0.so.0 from rpm glib2-2.80.3-1.fc40.x86_64
                Module libgio-2.0.so.0 from rpm glib2-2.80.3-1.fc40.x86_64
                Module libX11.so.6 from rpm libX11-1.8.10-1.fc40.x86_64
                Module libfreetype.so.6 from rpm freetype-2.13.2-5.fc40.x86_64
                Module libfontconfig.so.1 from rpm fontconfig-2.15.0-6.fc40.x86_64
                Stack trace of thread 453377:
                #0  0x00007fe5a3f3f3ad malloc_usable_size (libc.so.6 + 0xa93ad)
                #1  0x00007fe59cf5de27 greedy_realloc (libnss_resolve.so.2 + 0x7e27)
                #2  0x00007fe59cf63fde json_buildv (libnss_resolve.so.2 + 0xdfde)
                #3  0x00007fe59cf6637f json_build (libnss_resolve.so.2 + 0x1037f)
                #4  0x00007fe59cf67b27 _nss_resolve_gethostbyname4_r (libnss_resolve.so.2 + 0x11b27)
                #5  0x00007fe5a3fdf311 getaddrinfo (libc.so.6 + 0x149311)
                #6  0x0000562a681815df n/a (/home/gbcox/Telegram/Telegram + 0x55a85df)
                #7  0x0000562a6819cc33 n/a (/home/gbcox/Telegram/Telegram + 0x55c3c33)
                #8  0x0000562a681bf8c9 n/a (/home/gbcox/Telegram/Telegram + 0x55e68c9)
                #9  0x0000562a68a51f7d n/a (/home/gbcox/Telegram/Telegram + 0x5e78f7d)
                #10 0x0000562a689eccab n/a (/home/gbcox/Telegram/Telegram + 0x5e13cab)
                #11 0x00007fe5a3f2d507 start_thread (libc.so.6 + 0x97507)
                #12 0x00007fe5a3fb140c __clone3 (libc.so.6 + 0x11b40c)
                
                Stack trace of thread 453349:
                #0  0x00007fe5a246f890 AddKeySymbols.isra.0 (libxkbcommon.so.0 + 0x21890)
                #1  0x00007fe5a2466cb5 HandleSymbolsFile (libxkbcommon.so.0 + 0x18cb5)
                #2  0x00007fe5a24677a0 CompileSymbols (libxkbcommon.so.0 + 0x197a0)
                #3  0x00007fe5a246882c compile_keymap_file (libxkbcommon.so.0 + 0x1a82c)
                #4  0x00007fe5a2469703 text_v1_keymap_new_from_string.lto_priv.0 (libxkbcommon.so.0 + 0x1b703)
                #5  0x00007fe5a246dbd1 xkb_keymap_new_from_buffer (libxkbcommon.so.0 + 0x1fbd1)
                #6  0x00007fe5a25636eb keyboard_handle_keymap.lto_priv.0 (libgdk-3.so.0 + 0x5d6eb)
                #7  0x00007fe5a3ac7056 ffi_call_unix64 (libffi.so.8 + 0x9056)
                #8  0x00007fe5a3ac36a0 ffi_call_int.lto_priv.0 (libffi.so.8 + 0x56a0)
                #9  0x00007fe5a3ac64ee ffi_call (libffi.so.8 + 0x84ee)
                #10 0x00007fe5a4782f2e wl_closure_invoke.constprop.0 (libwayland-client.so.0 + 0x4f2e)
                #11 0x00007fe5a47837a3 dispatch_event.isra.0 (libwayland-client.so.0 + 0x57a3)
                #12 0x00007fe5a4783a4c wl_display_dispatch_queue_pending (libwayland-client.so.0 + 0x5a4c)
                #13 0x00007fe5a2565a60 _gdk_wayland_display_queue_events (libgdk-3.so.0 + 0x5fa60)
                #14 0x00007fe5a2530acb gdk_display_get_event (libgdk-3.so.0 + 0x2aacb)
                #15 0x00007fe5a256d3be gdk_event_source_dispatch (libgdk-3.so.0 + 0x673be)
                #16 0x00007fe5a41dae8c g_main_context_dispatch_unlocked.lto_priv.0 (libglib-2.0.so.0 + 0x5ce8c)
                #17 0x00007fe5a423cc98 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0xbec98)
                #18 0x00007fe5a41dc383 g_main_context_iteration (libglib-2.0.so.0 + 0x5e383)
                #19 0x0000562a68a44668 n/a (/home/gbcox/Telegram/Telegram + 0x5e6b668)
                #20 0x0000562a68929ed2 n/a (/home/gbcox/Telegram/Telegram + 0x5d50ed2)
                #21 0x0000562a6508c7e9 n/a (/home/gbcox/Telegram/Telegram + 0x24b37e9)
                #22 0x0000562a6508e61b n/a (/home/gbcox/Telegram/Telegram + 0x24b561b)
                #23 0x0000562a65090731 n/a (/home/gbcox/Telegram/Telegram + 0x24b7731)
                #24 0x0000562a63e643e0 n/a (/home/gbcox/Telegram/Telegram + 0x128b3e0)
                #25 0x00007fe5a3ec0088 __libc_start_call_main (libc.so.6 + 0x2a088)
                #26 0x00007fe5a3ec014b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a14b)
                #27 0x0000562a63f09a6e n/a (/home/gbcox/Telegram/Telegram + 0x1330a6e)
                ELF object binary architecture: AMD x86-64

### Operating system

Fedora 40, Plasma 6

### Version of Telegram Desktop

5.3.1

### Installation source

Static binary from official website

**Comment by gbcox** [comment]
Well, not sure what happened.  Seems like there was some kind of corruption or something that happened during the upgrade to 5.3.1.  After I downgraded to 5.2.6 I tried 5.3.1 again and it worked with no issues.  Weird.  Anyway, closing this out.

**Comment by gbcox** [comment]
ok, looks like #16884 is back.  When I turn on automatic update, it immediately tries to download a new release and then restarts into a coredump.

**Comment by krokwen-tftc** [comment]
i also getting segfault on 5.3.1

**Comment by 26fe** [comment]
I am on fedora 40, I get segfault after update. I have downloaded the binary from the site but I still get segfault. I think the issue is in the 5.3.1 not the udpate process. I don't know how to get stacktrace.

**Comment by john-preston** [comment]
@26fe Hi. I've built another version, trying to fix this problem:

https://td.telegram.org/tlinux/tsetup.5.3.2.tar.xz

Please try unpacking this one and replacing your 5.3.1 binary with it. Will it work fine?

**Comment by john-preston** [comment]
@krokwen-tftc Hi. I've built another version, trying to fix this problem:

https://td.telegram.org/tlinux/tsetup.5.3.2.tar.xz

Please try unpacking this one and replacing your 5.3.1 binary with it. Will it work fine?

**Comment by kmare** [comment]
@john-preston had the same problem. Updated to 5.3.2 and everything looks good so far! thanks!

**Comment by 26fe** [comment]
@john-preston it is working. Thank you very much!

**Comment by krokwen-tftc** [comment]
> @krokwen-tftc Hi. I've built another version, trying to fix this problem:
> 
> https://td.telegram.org/tlinux/tsetup.5.3.2.tar.xz
> 
> Please try unpacking this one and replacing your 5.3.1 binary with it. Will it work fine?

it works! thank you!

**Comment by gbcox** [comment]
5.3.2 seems to have fixed the issue.  I have turned auto-updates back on.  Thanks for the quick response.
