### ISSUE TITLE
GNU/Linux build stopped due to '‘webrtc::DesktopCapturer’ has not been declared'

### ISSUE THREAD

**Issue by looptc** [telegramdesktop/tdesktop#28226]
### Steps to reproduce

Follow the steps to compile under GNU/Linux
Changed the flag cf-protection by mbranch-protection=standard (but this may not affect to reproduce)

### Expected behaviour

The expected behaviour is to compile successfully as in the previous beta version (I pulled today).

### Actual behaviour

After cloning and running the docker image preparation script, running the docker run command as in the instructions are specified, the following error throws:

```
/usr/src/tdesktop/Telegram/lib_webrtc/webrtc/platform/linux/webrtc_environment_linux.cpp: In member function ‘virtual std::optional<QString> Webrtc::Platform::EnvironmentLinux::uniqueDesktopCaptureSource() const’:
/usr/src/tdesktop/Telegram/lib_webrtc/webrtc/platform/linux/webrtc_environment_linux.cpp:60:21: error: ‘webrtc::DesktopCapturer’ has not been declared
   60 |         if (webrtc::DesktopCapturer::IsRunningUnderWayland()) {
      |                     ^~~~~~~~~~~~~~~
[6/945] Building CXX object Telegram/CMakeFiles/td_iv.dir/Release/cmake_pch.hxx.gch
ninja: build stopped: subcommand failed.
```

### Operating system

GNU/Linux

### Version of Telegram Desktop

dev branch, tagged as v5.3.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Ensure you have the right version of tg_owt (as in Dockerfile)

**Comment by john-preston** [comment]
@ilya-fedin This problem was about wrongly removed include in lib_webrtc, it should be fixed on the latest 'dev' commit here / latest 'master' commit in lib_webrtc.

**Comment by looptc** [comment]
This commit fixed the issue: https://github.com/desktop-app/lib_webrtc/compare/0222032008a93fb6f198fdeeafd4ee063d0b624b...8751e27d50d2f26b5d20673e5ddba38e90953570 Thank you!
