### ISSUE TITLE
Arrow keys (mis) behavior

### ISSUE THREAD

**Issue by bertmsk** [telegramdesktop/tdesktop#2822]
Non-consistent arrow keys behavior. 
For example pressing an "arrow down" in chat scrolls to the bottom as expected, but "arrow up" brings your own last message for edit. However pressing "arrow down" again not cancels editing.

It would be nice to make "edit last message" for example shift/ctrl+"arrow/whatever" and leave default arrow keys behavior for chat scrolling.

**Comment by auchri** [comment]
Duplicate #2012
