### ISSUE TITLE
Telegram Desktop Browser does not display pages on Ubuntu Linux 22.04.4 amd64

### ISSUE THREAD

**Issue by brailateo** [telegramdesktop/tdesktop#28231]
### Steps to reproduce

1. try to open  tonsite://getting-started.ton) from last Durov message

### Expected behaviour

display the page

### Actual behaviour

the browser's window page is blank thought the text and images are there, they can be selected with the mouse, copied then pasted in a text editor, they are there, but I cannot see them. Tried to change to night mode without success.

### Operating system

Ubuntu Linux Mate 22.04.4 amd 64

### Version of Telegram Desktop

5.3.1 and 5.3.2 have the same problem

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> 1. try to open  tonsite://getting-started.ton) from last Durov message

I don't see any problem here
![](https://github.com/user-attachments/assets/2f3903e5-8467-4b6a-9718-1e58503f98b6)

**Comment by brailateo** [comment]
I have another Linux Mint Mate 22 amd 64 machine, and it displays the browser window page! 
I don't have have any problem with any other apps on the Ubuntu Mate 22.04, it might be a problem of rendering the page, I hoped that you can suggest me any options (related to graphics) I should try to pin the problem. I disabled the OpenGL for media (thought I don't think it is using it).

**Comment by ilya-fedin** [comment]
I remember there are problems with proprietary nvidia drivers, to the point no webkitgtk-based browser work (even the gnome web). Switching to nouveau usually helps.

**Comment by brailateo** [comment]
Thanks, I will try that and come back with information!
Teo

**Comment by brailateo** [comment]
> I remember there are problems with proprietary nvidia drivers, to the point no webkitgtk-based browser work (even the gnome web). Switching to nouveau usually helps.

Switched from nvidia-driver-470 (proprietary) to nouveau, reboot ... still the page is not visible.

![image](https://github.com/user-attachments/assets/ef2c8897-043e-463b-8edf-6851a4588a1a)
![image](https://github.com/user-attachments/assets/94d8eb33-de54-4f3f-a010-d9bea8a59a67)

**Comment by ilya-fedin** [comment]
Does gnome web (epiphany) work for you?

**Comment by brailateo** [comment]
> Does gnome web (epiphany) work for you?

No, I cannot see any pages in epiphany, just the same as in Telegram Browser! 
Teo

**Comment by ilya-fedin** [comment]
Perhaps something is broken system-wide 🤷

**Comment by brailateo** [comment]
> Perhaps something is broken system-wide 🤷

Yes, something is wrong with the video driver!

I experimented on the same computer with Live versions of Linux Mint 22, Debian 12, both of them had the same problem!
Finally, I tried the latest AVL MX Linux (for AudioVideo production) supported by Debian **AND IT WORKED JUST FINE!**

It seems the the live distribution has installed the nouveau driver and everything was OK, I can see the page in Telegram Browser.
I'm leaving here the information about video driver and configuration from AVL MX Linux.

```
$ glxinfo | grep -i vendor
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: Mesa (0x10de)
OpenGL vendor string: Mesa

$ glxinfo | grep -i "vendor\|rendering"
direct rendering: Yes
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: Mesa (0x10de)
OpenGL vendor string: Mesa
demo@avl-mxe-live-iso:~

$ grep LoadModule /var/log/Xorg.0.log
[    22.286] (II) LoadModule: "glx"
[    22.417] (II) LoadModule: "modesetting"
[    22.426] (II) LoadModule: "fbdev"
[    22.430] (II) LoadModule: "vesa"
[    22.441] (II) LoadModule: "fbdevhw"
[    22.457] (II) LoadModule: "glamoregl"
[    25.712] (II) LoadModule: "fb"
[    26.224] (II) LoadModule: "libinput"

$ lsmod | grep "kms\|drm"
drm_exec               12288  1 nouveau
drm_ttm_helper         12288  1 nouveau
ttm                   106496  2 drm_ttm_helper,nouveau
drm_display_helper    237568  1 nouveau
cec                   102400  1 drm_display_helper
drm_kms_helper        253952  4 drm_display_helper,nouveau
drm                   819200  15 gpu_sched,drm_kms_helper,drm_exec,drm_display_helper,drm_ttm_helper,ttm,nouveau

$ lspci -k | grep -EA3 'VGA|3D|Display'
01:00.0 VGA compatible controller: NVIDIA Corporation GK208B [GeForce GT 730] (rev a1)
  Subsystem: Micro-Star International Co., Ltd. [MSI] GK208B [GeForce GT 730]
  Kernel driver in use: nouveau
  Kernel modules: nouveau
```

I'm closing this issue because obviouosly it's a driver/card problem, not from Telegram Desktop!
@ilya-fedin thanks for your help!
Teo
