### ISSUE TITLE
Application freezes opening any video

### ISSUE THREAD

**Issue by Wondertan** [telegramdesktop/tdesktop#28233]
### Steps to reproduce

1. Open app
2. Open any video

### Expected behaviour

Video works

### Actual behaviour

Application freezes and requires to be killed

### Operating system

Linux 6.6.41, Wayland with Sway

### Version of Telegram Desktop

v5.3.2

### Installation source

Static binary from official website

### Logs

I am trying to access logs via `viewlogs` but it does not work for some reason and the only logs I have are from terminal.
```shell
[AVHWDeviceContext @ 0x7fccfa1e2900] Failed to initialise VAAPI connection: -1 (unknown libva error).
```

**Comment by ilya-fedin** [comment]
> I am trying to access logs via `viewlogs` but it does not work

Maybe you don't have a GUI file manager? It should open the folder the logs reside in.

> ```shell
> [AVHWDeviceContext @ 0x7fccfa1e2900] Failed to initialise VAAPI connection: -1 (unknown libva error).
> ```

Did you activate hardware video decoding in settings? It's disabled by default for a reason, the drivers are usually too buggy breaking playback completely.

**Comment by Wondertan** [comment]
> Did you activate hardware video decoding in settings?

Yes. However, disabling it didn't help. The behavior stays the same, but the log with `libva` dissappears

**Comment by ilya-fedin** [comment]
I can't reproduce

**Comment by Wondertan** [comment]
This was likely an issue on my end. Everything started to work automagically after some time.
