### ISSUE TITLE
crash with linux kernel 6.10

### ISSUE THREAD

**Issue by satanix7** [telegramdesktop/tdesktop#28232]
### Steps to reproduce

1. boot ubuntu with linux kernel 6.10
2. run telegram desktop

### Expected behaviour

telegram desktop starts normally

### Actual behaviour

I upgraded my linux kernel from 6.9.9 to 6.10.2 and telegram desktop 5.3.2 crashed with SIGILL (illegal instruction), but when i booted my ubuntu with linux kernel 6.9.9 again everything with telegram desktop is fine

### Operating system

Ubuntu 24.04, Cinnamon 6.0.2

### Version of Telegram Desktop

5.3.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
There seem to be something with the issue, the kernel on Ubuntu 24.04 is 6.8. If you install third party kernel, any breakage is on you to resolve.

**Comment by satanix7** [comment]
I just wanted to inform the problem
Whether you solve it or not is not my business

**Comment by PixelCode5** [comment]
Same here. For me it seems to be related to nvidia gpu hardware acceleration on wayland, turning off fixes the video playback crash issue. Previous version used to work with some occasional crash but now it crashes right off.

**Comment by satanix7** [comment]
Force GDS Mitigation (CONFIG_MITIGATION_GDS_FORCE) was enabled in ubuntu kernel ppa configuration by mistake, disabling it and rebuilding the 6.10.7 kernel fixed this issue
