### ISSUE TITLE
(Design suggestion) Rust implementation of the backend

### ISSUE THREAD

**Issue by hardBSDk** [telegramdesktop/tdesktop#28234]
### Is your feature request related to a problem?

Reduce the number of bugs, the time hunting them and the memory usage.

### Describe the solution you'd like

Write a [Rust](https://rust-lang.org) implementation of the backend, to be an alternative to the C++ backend until it's mature.

Rewrite the C++ code and APIs to Rust is not a good approach, rewrite from scratch in Rust gives better results.

### Describe alternatives you've considered

None.

### Additional context

I would like to know if you already considered a [Rust](https://rust-lang.org) implementation of the Telegram Desktop backend, if not I want to request this to improve the program stability, security, performance and memory management.

- Why the Rust programming language?

It fixes most implementation bugs (memory-safety, type-safety and thread-safety), null-based bugs and some logic bugs.

Thus you spend more time writing code and less time hunting and fixing bugs.

It's also easier to refactor, maintain and package, because Rust use Cargo to do automatic dependency management with [Semantic Versioning](https://semver.org/) enforcement by default.

**Comment by ilya-fedin** [comment]
There are multiple problems with the proposal:
1. There's no such thing as a 'backend', i.e. there's no clear separation between UI and non-UI code (assuming that's what you mean by 'backend'?), almost all the code is UI code (imlepmentations of custom widgets)
2. No one will rewrite the application (except if you want to do that on your own)
2.1. Creating a new project by people interested in this is likely a way better strategy
2.2. Or you can contribute to pre-existing projects like https://github.com/paper-plane-developers/paper-plane
