### ISSUE TITLE
I want telegram saved messages completely secure and private like blockchain technology so i can control my data

### ISSUE THREAD

**Issue by hamza-asif803** [telegramdesktop/tdesktop#28239]
### Is your feature request related to a problem?

I want telegram saved messages completely secure and private like blockchain technology so i can control my data

### Describe the solution you'd like

I want telegram saved messages completely secure and private like blockchain technology so i can control my data

### Describe alternatives you've considered

I want telegram saved messages completely secure and private like blockchain technology so i can control my data

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
