### ISSUE TITLE
Add finger print or password protection to saved message 

### ISSUE THREAD

**Issue by danielddemissie** [telegramdesktop/tdesktop#28236]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

I would like to have a finger print or password protection on my saved message contents since I (most people) use telegram to store sensitive information since it's convenient to do so.

### Describe alternatives you've considered

I think asking client password when someone is trying to access my saved message 

### Additional context

No. I'm a developer I would gladly like to contribute to this future.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/ (think it's useless to add fingerprint only to desktop client if they have access to desktop client and saved messages are finger protected, they can open telegram web and check from there)
