### ISSUE TITLE
help asap

### ISSUE THREAD

**Issue by Lwantstostophim** [telegramdesktop/tdesktop#28242]
### Is your feature request related to a problem?

theres multiple channels and accounts posting csam of a friend who was 14 at the time is there anyway to code or something so there not allowed to be shared please help theres so many accounts and channels trying to post and sell things of him
please is there anything someone can do

### Describe the solution you'd like

hashing images and videos of him so they canr be shared anymore  banning accounts that post him asap 
banning channels with him and videos of other minors

### Describe alternatives you've considered

police, fbi, telegram emails

**Comment by Aokromes** [comment]
Sorry but this is telegram desktop bug tracker, nothing here belongs to user or groups account administration.
