### ISSUE TITLE
make flatpak in flathub verified

### ISSUE THREAD

**Issue by olumolu** [telegramdesktop/tdesktop#28245]
### Is your feature request related to a problem?

Verifying an app in flatpak make it better

### Describe the solution you'd like

Verification for telegram.
Easy to do just need to do it.

### Describe alternatives you've considered

None

**Comment by ilya-fedin** [comment]
It's already verified

**Comment by dimas1980200** [comment]
Анал я хочу войти в твою попку малышка
***@***.***

вт, 6 авг. 2024 г., 13:02 aritra saha ***@***.***>:

**Comment by dimas1980200** [comment]
Да

***@***.***

вт, 6 авг. 2024 г., 13:03 ilya-fedin ***@***.***>:
