### ISSUE TITLE
Completly remove wallet suggestion from attach icon

### ISSUE THREAD

**Issue by KarelWintersky** [telegramdesktop/tdesktop#28243]
### Is your feature request related to a problem?

![image](https://github.com/user-attachments/assets/d88baded-16e2-404c-bc76-8e42e037ccb4)

But:
![image](https://github.com/user-attachments/assets/787a9604-0db1-4841-b58c-26d60eab14b8)

I don't want use `application from independed party NOT AFFILATED WITH TELEGRAM`

This is security problem. 

persistently asking the user to use a third-party application created by unknown developers means asking them to put their security at risk.

This is unacceptable behavior.

At a minimum, there should be an option to disable the wallet if it is not forcibly connected. Otherwise, it looks like IMPOSITION of unnecessary and malicious functionality.

### Describe the solution you'd like

- Remove 'wallet' from chat buttons
- add to Settings, below `Telegram Business`
- 

### Describe alternatives you've considered

disable update TG forever

**Comment by rmnscnce** [comment]
![image](https://github.com/user-attachments/assets/df283008-2888-40cf-9379-beb483552166)

Right click on the "Wallet" attachment option and click "Remove from menu"
