### ISSUE TITLE
Display scaling bug

### ISSUE THREAD

**Issue by apxapob** [telegramdesktop/tdesktop#28241]
### Steps to reproduce

requirements: 2 monitors with different dpi and resolution.

1) Set different scale factors on your monitors.(I have 200% on main and 125% on secondary)
2) Open telegram window on main monitor.
3) Turn off your main monitor
4) Turn it on.

Result: ![image](https://github.com/user-attachments/assets/c77c75bf-22b2-4d56-9dd3-e02236edbff9)

### Expected behaviour

I expect telegram to render correctly.

### Actual behaviour

![image](https://github.com/user-attachments/assets/c77c75bf-22b2-4d56-9dd3-e02236edbff9)

### Operating system

Windows 11

### Version of Telegram Desktop

5.3.1

### Installation source

Static binary from official website

### Crash ID

no

### Logs

```shell
no
```

**Comment by kode54** [comment]
Similar but different effect happens on Linux desktops with mixed DPI: When toggling off the HiDPI (scale 2.0) monitor, the TDesktop window becomes scale 1.0, then doesn't pick up the scale 2.0 when relocated onto the 2.0 display, either manually by dragging, or automatically by the output restore features of the compositor when the output is momentarily removed.

**Comment by ilya-fedin** [comment]
@apxapob is this still happening with 5.6?

**Comment by apxapob** [comment]
> @apxapob is this still happening with 5.6?

yep still happening.

**Comment by ilya-fedin** [comment]
Does it stop happening if you enable system window frame in settings?

**Comment by apxapob** [comment]
> Does it stop happening if you enable system window frame in settings?

yeah, happening with system window frame enabled too

**Comment by ilya-fedin** [comment]
Can you reproduce the same issue with qBittorrent?

**Comment by apxapob** [comment]
> Can you reproduce the same issue with qBittorrent?

qBittorrent has similar issue. When I turn off the monitor the window goes to the second monitor and has broken layout. And when I turn on the first monitor layout is fine, but it shows everything like it has 100% scaling, not 200%. The ui becomes too small.

**Comment by ilya-fedin** [comment]
Oh, so backporting Qt 6 changes is probably useless given that qBittorent which uses Qt 6 is bugged, too...

**Comment by ilya-fedin** [comment]
Can you check which exactly Qt version qBittorent uses right now?

**Comment by apxapob** [comment]
> Can you check which exactly Qt version qBittorent uses right now (in about dialog)?

Qt: 6.3.0

**Comment by ilya-fedin** [comment]
> Qt: 6.3.0

Are you sure your qbittorrent is latest? I see Qt 6.7.3 is mentioned on their website...

**Comment by Aokromes** [comment]
> > Qt: 6.3.0
> 
> Are you sure your qbittorrent is latest? I see Qt 6.7.3 is mentioned on their website...

on latest qbittorrent it's indeed 6.7.3

**Comment by ilya-fedin** [comment]
i wonder whether latest qbittorrent bugs

**Comment by apxapob** [comment]
Updated qbittorrent. The same situation on Qt 6.7.3

**Comment by ilya-fedin** [comment]
ok, thanks

**Comment by ilya-fedin** [comment]
Does this happen with 5.6.1?

**Comment by apxapob** [comment]
I don't know. Where can I check that?

**Comment by ilya-fedin** [comment]
> I don't know. Where can I check that?

I don't quite understand the question. How did you check previously?

**Comment by apxapob** [comment]
oh sorry. I thought I need to find an app with Qt 5.6.1
In telegram 5.6.1 the bug still happens.

**Comment by ilya-fedin** [comment]
What do you do to get out of this state? Does resizing window help? Does moving the window a little bit (the relevant event should be sent on mouse button release) help? Does changing Windows settings (e.g. enabling/disabling dark mode) and then moving the window a little bit help?

**Comment by apxapob** [comment]
I usually just restart telegram. Also I can fix it by changing screen scale factor. Anything else doesn't help.

**Comment by ilya-fedin** [comment]
> Anything else doesn't help.

None of the things I suggested to try?

**Comment by apxapob** [comment]
Yeah.

**Comment by ilya-fedin** [comment]
Hm. I wonder whether the relevant message is sent only with native titlebar. Can you try moving the window with it?

An important thing is to try switch the system dark mode if just moving doesn't work as it sends the event that forces Qt to update its screen list.

**Comment by apxapob** [comment]
Tried that. Didn't help.

**Comment by ilya-fedin** [comment]
Does this happen with 5.6.2?

**Comment by ilya-fedin** [comment]
Can you provide crash id of the crash report (you have to enable beta installation in settings for crash reporter to appear, DON'T wait for an update)?

**Comment by apxapob** [comment]
Crash ID: 3c7ec04c-7038-4481-9c8d-1ba3b03086c3

**Comment by ilya-fedin** [comment]
Can you re-test the bug when you will get 5.6.3?

**Comment by apxapob** [comment]
yeah sure

**Comment by apxapob** [comment]
Yay! I checked 5.6.3 - The bug is finally fixed!
