### ISSUE TITLE
occasional segfaults on linux (gnome)

### ISSUE THREAD

**Issue by SiLiKhon** [telegramdesktop/tdesktop#28253]
### Steps to reproduce

1. run telegram desktop
2. wait long enough (may be related to OS locking and switching the screen off, although I wasn't able to reproduce the crash by just locking the system manually)

### Expected behaviour

no crash

### Actual behaviour

crash

### Operating system

Debian GNU/Linux 12 (bookworm), gnome 43.9

### Version of Telegram Desktop

5.3.2

### Installation source

Static binary from official website

### Crash ID

a3d4890f-7006-43a1-eac96f82-b340b662

### Logs

```shell
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
qt.gui.imageio.jpeg: ./lib/jpegli/decode_scan.cc:535: Incomplete scan detected.
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.StatusNotifierWatcher was not provided by any .service files")
Segmentation fault
```

**Comment by SiLiKhon** [comment]
fyi: updated the OP with a crash ID

**Comment by tandrejo** [comment]
I'm facing random terminations, too. Here's what I have in logs:
![Снимок экрана от 2024-08-09 12-59-48](https://github.com/user-attachments/assets/1db9dddb-520c-45a0-bbaa-64d91b3c17b1)

**Comment by ilya-fedin** [comment]
> a3d4890f-7006-43a1-eac96f82-b340b662

According to this crash ID, the crash happens in Qt and there's nothing tdesktop could do about it.

**Comment by SiLiKhon** [comment]
Thanks @ilya-fedin for looking into this.
However, from the minidump of another such crash I see:
```
Operating system: Linux
                  0.0.0 Linux 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64
CPU: amd64
     family 6 model 140 stepping 1
     1 CPU

GPU: UNKNOWN

Crash reason:  SIGSEGV /SEGV_MAPERR
Crash address: 0x8
Process uptime: not available

Thread 0 (crashed)
 0  Telegram + 0x59227f4
    rax = 0x0000000000000000   rdx = 0x0000000000000000
    rcx = 0x0000000000000000   rbx = 0x0000000000000000
    rsi = 0x0000000000000000   rdi = 0x0000000000000000
    rbp = 0x00007fff4c8be670   rsp = 0x00007fff4c8be608
     r8 = 0x0000000000000000    r9 = 0x0000000000000000
    r10 = 0x00007ff5f0c00a98   r11 = 0x00007ff5a3372160
    r12 = 0x00007ff5cf62b780   r13 = 0x00007ff5cf62b7b1
    r14 = 0x00007ff5cf62b790   r15 = 0x00007ff5cf77aa00
    rip = 0x000055b53f7587f4
    Found by: given as instruction pointer in context
 1  Telegram + 0x5daac58
    rbp = 0x00007fff4c8be750   rsp = 0x00007fff4c8be680
    rip = 0x000055b53fbe0c58
    Found by: previous frame's frame pointer
 2  Telegram + 0x5daac58
    rbp = 0x00007fff4c8be830   rsp = 0x00007fff4c8be760
    rip = 0x000055b53fbe0c58
    Found by: previous frame's frame pointer
 3  Telegram + 0x4f3db66
    rbp = 0x00007fff4c8be8c0   rsp = 0x00007fff4c8be840
    rip = 0x000055b53ed73b66
    Found by: previous frame's frame pointer
 4  libffi.so.8 + 0x6f7a
    rbp = 0x00007fff4c8be8d0   rsp = 0x00007fff4c8be8d0
    rip = 0x00007ff5f1493f7a
    Found by: previous frame's frame pointer
 5  libffi.so.8 + 0x640e
    rsp = 0x00007fff4c8be8f0   rip = 0x00007ff5f149340e
    Found by: stack scanning
 6  libgdk-3.so.0 + 0x6df30
    rsp = 0x00007fff4c8be908   rip = 0x00007ff5ecb60f30
    Found by: stack scanning
 7  Telegram + 0x4f94160
    rsp = 0x00007fff4c8be948   rip = 0x000055b53edca160
    Found by: stack scanning
 8  libffi.so.8 + 0x6b0d
    rsp = 0x00007fff4c8be9f0   rip = 0x00007ff5f1493b0d
    Found by: stack scanning
 9  Telegram + 0x4f94160
    rsp = 0x00007fff4c8bea10   rip = 0x000055b53edca160
    Found by: stack scanning
10  libwayland-client.so.0 + 0xa761
    rsp = 0x00007fff4c8bea60   rip = 0x00007ff5f132a761
    Found by: stack scanning
```

This does not seem like a Qt part to me. I don't have a binary with debug symbols, but from the disassembly of my binary I see that this address (0x59227f4) is in this block:
```
000000000489d390 <_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcm@@Base>:
```
(which indicates a `string::find` call)
In particular, here's the disassembly around the crashing address:
```asm
 59227e8: 0f 1f 84 00 00 00 00  nopl   0x0(%rax,%rax,1)
 59227ef: 00 
 59227f0: f3 0f 1e fa           endbr64
 59227f4: 48 8b 57 08           mov    0x8(%rdi),%rdx      #### <----- crash here, note both registers contain 0.
 59227f8: 48 8b 02              mov    (%rdx),%rax
 59227fb: 48 85 c0              test   %rax,%rax
 59227fe: 74 10                 je     5922810 <_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcm@@Base+0x1085480>
```

I guess this could be some null-pointer string dereference or similar.

I haven't submitted the minidump file this time, but let me know if you need it and how to send it to you.

**Comment by ilya-fedin** [comment]
> However, from the minidump of another such crash I see:

Please upload the minidump of provide its id if it was sent via crash reporting previously

**Comment by SiLiKhon** [comment]
@ilya-fedin 
> > However, from the minidump of another such crash I see:
> 
> Please upload the minidump or provide its id if it was sent via crash reporting previously

I didn't report this time, here's the dump:
[fae590c5-eef8-44a7-8d817fac-8316a4b1.dmp](https://github.com/user-attachments/files/16589046/fae590c5-eef8-44a7-8d817fac-8316a4b1.dmp)

**Comment by SiLiKhon** [comment]
@ilya-fedin
I sent one more report (ID `87f0f842-b23c-4001-a2e923a6-bb5e9fd6`) after another crash.
The dump seems to be quite similar, the crash happening at the same address.

**Comment by ilya-fedin** [comment]
Both dumps are the same as the first one, crashing in Qt code. Nothing related to std::string.

**Comment by SiLiKhon** [comment]
Thanks @ilya-fedin. Is Qt linked statically? Has its version changed recently?
I'm only experiencing these crashes from ~Aug 2024.

**Comment by SiLiKhon** [comment]
> From the crash trace it looks like Qt doesn't like that you disconnect the last monitor from the system. It wants at least one monitor to be present for stable work.

hmm, this makes sense - as the crash usually happens when the system locks the screen due to inactivity, and at the same time I see the external monitor turning on and off couple times (I guess some debian/gnome magic happening, I'm not plugging it out or anything + I should still have the built in laptop screen :rofl:)

(not sure I have enough willpower to compile everything with debug symbols to make a proper report for Qt, but will see how annoying it becomes...)

Thanks again!
