### ISSUE TITLE
Custom theme doesn't adapted to folder sidebar

### ISSUE THREAD

**Issue by artromone** [telegramdesktop/tdesktop#28257]
the same problem as #7509

**Comment by artromone** [comment]
![2024-08-09T23:18:35,053164338+03:00](https://github.com/user-attachments/assets/3d328dd8-d93d-42b6-b629-5b116fa7159f)

**Comment by Aokromes** [comment]
you must edit sidebar yourself.for example like this
https://t.me/addtheme/kd14jziGvcRuiuIC
