### ISSUE TITLE
Image previews not working for (some?) IDN domain names

### ISSUE THREAD

**Issue by notmika** [telegramdesktop/tdesktop#2825]
### Steps to reproduce
1. Send a Telegram message containing a direct link to an image hosted on a website that uses an IDN domain name, for example: "http://ã.co/i/pMDWVn.png"
2. Expect an image preview.
3. ... Don't get one!

### Expected behaviour
An image preview should appear in the Telegram message.

### Actual behaviour
Only the URL to the image is being shown, no preview will ever show up.

### Configuration
Windows 10

Telegram Desktop Version 1.0

### My personal comment
Since I use my own domain, which happens to be an IDN domain name, for screenshot uploads, it's rather annoying for me and the people that I send screenshots to to not be able to get a preview, or even view the image within Telegram like you can using a regular domain name.

**Comment by john-preston** [comment]
@notmika it does work for currently:

![image](https://cloud.githubusercontent.com/assets/17900494/21925571/195f7ee4-d98f-11e6-9c91-60eab0787086.png)

It doesn't show that there is preview while you edit the message, because it is not recognized on the client side, but when you send it the preview gets there.

**Comment by notmika** [comment]
@john-preston What in the world am I doing wrong then, it really never shows for me or anyone I send it to. I'll try again just now..

**Comment by auchri** [comment]
I does work now, but it didn't work yesterday..

**Comment by notmika** [comment]
What?! @auchri that's even more confusing. The image I used in my issue here does somehow work indeed, but now I'm trying some other image it still does not. Not even using the punycode version of the domain.

![image](https://cloud.githubusercontent.com/assets/20849442/21925894/c806b85a-d97f-11e6-8ae1-86d9e4d5e5b2.png)

**Comment by auchri** [comment]
I've tried it yedterday with the link you provided and Telegram was not showing a link preview.

I just tried it again and it works today ¯\_(ツ)_/¯

**Comment by john-preston** [comment]
@notmika there is a problem on server side, it will be fixed soon. Thanks for your report.

**Comment by notmika** [comment]
Just saw this, thanks alot @john-preston :)
