### ISSUE TITLE
Wallet: Error could not initialize WebView  

### ISSUE THREAD

**Issue by M0nteCarl0** [telegramdesktop/tdesktop#28251]
### Steps to reproduce

1. Open Wallet

### Expected behaviour

Do not show wallet content

### Actual behaviour

Do not show wallet content

### Operating system

Astra Linux 1.7 (kernel 5.15)

### Version of Telegram Desktop

5.3.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
It's not going to work on your distro because Qt is not compatible with libwayland 1.23: https://bugreports.qt.io/browse/QTBUG-126379

If you want the application to work without bugs, please switch to a Qt's [supported platform](https://doc.qt.io/qt-6/supported-platforms.html#linux-x11).
