### ISSUE TITLE
Member Count of Group incorrect

### ISSUE THREAD

**Issue by MUB808** [telegramdesktop/tdesktop#28255]
### Steps to reproduce

Im owner my group. 
Group Type - Private
Chat history for new members hidden
Topics off
3 guys in group.
I open chat of group and see on the top 1 member, but in group 3 members (1 owner and 2 admins, im owner).
![image](https://github.com/user-attachments/assets/5092abf3-41c2-463e-8400-d1d657ede32b)

### Expected behaviour

Not 1  member, i wait 3 members
![image](https://github.com/user-attachments/assets/ff6b21bf-c6c6-4074-b912-a95605d7a5c0)

### Actual behaviour

![image](https://github.com/user-attachments/assets/6e7b54be-9794-49a9-972a-72c473f81fd6)
just it show 1 member in group its incorrect

### Operating system

Windows 10 (22H2) build - 19045,4529

### Version of Telegram Desktop

Version 5.3.1 X64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
can't reproduce.

**Comment by MUB808** [comment]
what need for it?
