### ISSUE TITLE
Channels/chats owner transfer

### ISSUE THREAD

**Issue by spbdmg** [telegramdesktop/tdesktop#28269]
### Is your feature request related to a problem?

There is a lot of scam in Telegram with the transfer of the channel/chat owner. I have idea how to reduce the scam with TMA, but I don't have the technical ability to do this.

### Describe the solution you'd like

Transfer of a channel owner to another owner with a hold button via TMA to eliminate scams (the function of creating an intermediary during transfer). The transfer of ownership occurs only after confirmation of both parties through the TMA. The structure in a pic is given as an example.
![Transfer owner](https://github.com/user-attachments/assets/4f3efbe1-7fda-42e4-a2aa-4a42181e6b26)

### Describe alternatives you've considered

Maybe need the ability to transfer the channel owner to the TMA (bot with direct link like @wallet), if it's possible.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
