### ISSUE TITLE
Scam-user can use custom-emoji to look like 'verified' account

### ISSUE THREAD

**Issue by r-hmn** [telegramdesktop/tdesktop#28276]
### Steps to reproduce

1. Start the windows client (version 5.4)
2. Click on the scammer account-entry (like in my case the scammer @integzabyJG , see uploaded picture)
3. in the chat-view, you see the user name in the top, having the 'verified blue icon' behind the name. (At first i expected the user to be authentic.)
4. click on that name in the title-bar. This opens the user-info view.
5. In that user-info floater window, click that 'verified' icon which shows behind/after the name. 
6. This popup shows that the icon comes from some 'status icon theme pack'. So this is not a proper verified account!⚠

### Expected behaviour

Verified icon can only be used with actual verified accounts.

### Actual behaviour

Scammers can use an icon/status pack, to impersonate a verified account.
![user-looks-verified](https://github.com/user-attachments/assets/e0e6577b-2f94-44fb-8e86-992636a30259)
![verified-emoji-from-icon-pack-used-by-scammers](https://github.com/user-attachments/assets/955fd0b3-20c9-4b4b-917b-addf349f54cd)

### Operating system

Windows 10

### Version of Telegram Desktop

5.4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by r-hmn** [comment]
> platform wide bugs / requests belongs to https://bugs.telegram.org/

i went there. and there's no way to add anything, even after logging in. No help-text, nothing..
i was fed up, so went to this platform which has a proper interface.
