### ISSUE TITLE
Video message support on desktop

### ISSUE THREAD

**Issue by KarinaZakirova** [telegramdesktop/tdesktop#28273]
### Is your feature request related to a problem?

Briefly: I cannot send my speaking face to my friends when I'm using my laptop

Longly: The lack of native video message support on desktop platforms creates a significant disconnect in communication, especially for users who primarily rely on their computers for messaging. 

### Describe the solution you'd like

Adding video message support on desktop like on mobile version of the app

### Describe alternatives you've considered

No alternatives!

**Comment by Aokromes** [comment]
duplicate.
