### ISSUE TITLE
Move and rearrange pinned messages in folders For Telegram Mobile (channels, groups, etc.)

### ISSUE THREAD

**Issue by amirhlsn** [telegramdesktop/tdesktop#28278]
### Is your feature request related to a problem?

To move and rearrange of pinned messages in folders, you need to select them one by one, and their order is not preserved.

### Describe the solution you'd like

change the position of all the selected messages by dragging them up or down.

### Describe alternatives you've considered

If you select several channels or groups or any other message that the user has pinned, you can change the position of all the selected messages by dragging them up or down.

**Comment by Aokromes** [comment]
Sorry but this is telegram desktop bug tracker, nothing here belongs to other applications.
