### ISSUE TITLE
Show a preview image of the links (Telegram Android)

### ISSUE THREAD

**Issue by amirhlsn** [telegramdesktop/tdesktop#28279]
### Is your feature request related to a problem?

In the past, it was possible for Android users to see the preview image of the links below the link and click on it to view it on the same page, but in the recent updates this feature was unfortunately removed and by clicking on the image, It will be linked and will not be displayed on the entire mobile screen unless the user drags it with two fingers.

### Describe the solution you'd like

activating it through the Debug Menu section for users who want to activate it.

### Describe alternatives you've considered

The return of this feature in the main part of the program or the possibility of activating it through the Debug Menu section for users who want to activate it.

**Comment by ilya-fedin** [comment]
This is a bug tracker of Telegram Desktop. Not Telegram Android. If you wanted to report for Android, there's a "Other client" button when creating issue.
