### ISSUE TITLE
add topic name when deleting

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#28284]
### Is your feature request related to a problem?

sometimes you may hit the incorrect topic and delete it by mistake

### Describe the solution you'd like

include topic name when deleting, for example:

Are you sure you want to delete the topic named: my topic to delete?

### Describe alternatives you've considered

none

**Comment by 23rd** [comment]
Will be improved in the next version.

**Comment by Aokromes** [comment]
cool.
