### ISSUE TITLE
.png Transperant Background Color - Aesthetic Issue

### ISSUE THREAD

**Issue by ZarifinKolesi** [telegramdesktop/tdesktop#2828]
### Expected behaviour
When we share .png like transperant images with telegram, image's background color should seem as white by default
Example/Original image:
![image](https://desktop.telegram.org/img/td_laptop.png)

### Actual behaviour
When we shared .png like transperant images with telegram, image's background color seeming as black by default. And because of black background, all beuty of image has lost!

Example Image(what happened):
![image](https://cloud.githubusercontent.com/assets/8404792/21910854/89e6e8fa-d926-11e6-87fc-784e10db8cb6.png)

look at those black sides! at background

### Configuration
**Operating system:**  Windows 10

**Version of Telegram Desktop:** 1.0

**Comment by gudvinr** [comment]
@ZarifinKolesi every image you send via telegram "with compression" become jpeg which has no transparency.

**Comment by john-preston** [comment]
@ZarifinKolesi And how exactly do you send this .png, that get black background? I tried to share a link and the preview got white background, I tried to choose a .png as a file attachment and send it as photo (with compression) — it got white background. What steps do you perform to get black background in transparent areas?

**Comment by ZarifinKolesi** [comment]
Good question jhon, I followed this steps:
1- Go there: https://desktop.telegram.org/img/td_laptop.png
2- Right click on image and click "Copy Image"
3- Go telegram desktop app and enter any chat and click/focus "Write a message..." section and push these buttons at the same time: "Ctrl + V"

![image](https://cloud.githubusercontent.com/assets/8404792/21932904/924b8138-d9ab-11e6-8c4f-cfcf4f8ca4a7.png)

**Comment by john-preston** [comment]
@ZarifinKolesi I'm afraid this is a problem not related to Telegram Desktop. The browser already copies the image with the transparent areas been filled by black, if you paste it not in Telegram Desktop, but in any other place (like image editor or smth), you'll see the black background as well.

This is done in Windows, in macOS (for example) the browser copies the image with transparency to clipboard, so it is sent on white background, as Telegram Desktop does.

**Comment by ZarifinKolesi** [comment]
It seems trouble of browser not OS

I have repeated 3 steps above with Microsoft Edge Browser instead of widely used Google Chrome and it has white background as it should be =)

![image](https://cloud.githubusercontent.com/assets/8404792/21933173/02425218-d9ad-11e6-8173-8be75242adbb.png)

and also it should be good if we can mention chrome team here and send them notification about these feedback 

and also it will be good for github team.. :/

**Comment by ZarifinKolesi** [comment]
I have sended feedback about it to Google Chrome team and attached link of this issue report.
Thank you for your time =) Peace! =)
