### ISSUE TITLE
Ubuntu freezes when playing video 

### ISSUE THREAD

**Issue by EDW2k** [telegramdesktop/tdesktop#28280]
### Steps to reproduce

click on video and it opens new video window picture freezes and sound plays short clip on a loop. 

### Expected behaviour

Should play video with audio

### Actual behaviour

Whole Ubuntu freezes

### Operating system

Ubuntu 22.04

### Version of Telegram Desktop

5.3

### Installation source

Snap

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap) version from https://desktop.telegram.org

**Comment by EDW2k** [comment]
I removed old  version and installed official but it has not fixed anything. Can I find crash log etc. to post here?

**Comment by ilya-fedin** [comment]
Perhaps you have not enough powerful pc for the video you're trying to play given that you say whole system freezes?
