### ISSUE TITLE
Have an option to configure default Delete action on app level (reopened)

### ISSUE THREAD

**Issue by megaromb** [telegramdesktop/tdesktop#28287]
### Is your feature request related to a problem?

https://github.com/telegramdesktop/tdesktop/issues/3334

### Describe the solution you'd like

I'd like consistent behavior on mobile and desktop app

The linked issue was about "Delete for all members" confirmation (checkbox) on deleting messages in chats. To understand the issue (and how it's important/inconvenient) please look at the original issue created by @iklimchuk (https://github.com/iklimchuk), which wasn't resolved in the way it was expected. The fix introduced **inconsistency**.

Now the desktop version (Windows 11, 5.4.1) has the checkbox ON, but the mobile one (Android, 11.0.0 (5143)) has OFF by default.

Please make the behavior consistent doing the following:
* Set default value of the checkbox to ON on the mobile clients

### Describe alternatives you've considered

Additionally you could make this default value configurable via app settings on all the clients 

Please feel free to suggest/implement other solution you may find appropriate to gracefully solve the original issue.

**Comment by Aokromes** [comment]
Please make the behavior consistent doing the following:

Set default value of the checkbox to ON on the mobile clients

this bug tracker is for desktop client.
