### ISSUE TITLE
Avatar off button

### ISSUE THREAD

**Issue by Filipp-Druan** [telegramdesktop/tdesktop#28291]
### Is your feature request related to a problem?

I really don't like the avatars of some people who sit in my favorite chats.

### Describe the solution you'd like

One small button in the settings that turns off all avatars. Instead, only letters are displayed.

### Describe alternatives you've considered

I don't want to use any other clients.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
