### ISSUE TITLE
uploads too slow with the latest version 5.4.1

### ISSUE THREAD

**Issue by danardf** [telegramdesktop/tdesktop#28293]
### Steps to reproduce

Open a channel
Drop a file (image or audio file).
The upload takes 20" instead of 2 or 3 seconds for 2Mb or 3.5Mb 

### Expected behaviour

Have a normal upload

### Actual behaviour

The uploads are too slow.

### Operating system

Windows 11 64b full updated 

### Version of Telegram Desktop

5.4.1

### Installation source

Static binary from official website

### Logs

```shell
None
```

**Comment by Aokromes** [comment]
can't reproduce
