### ISSUE TITLE
When I mention my friend in a group, group members can see the nickname I gave him.

### ISSUE THREAD

**Issue by Pszz** [telegramdesktop/tdesktop#28297]
### Steps to reproduce

1. You need to add a nickname to your friend.
2. Enter a group that includes you and your friend.
3. When you @ your friend,And send a message, others see the nickname you added to him.

The nicknames I add to my friends should be private and should not be visible to third parties. 

### Expected behaviour

The nicknames for friends should not be visible to other members.

### Actual behaviour

The friend's nickname was known by other members of the group.

### Operating system

MacOS 12.0.1

### Version of Telegram Desktop

Telegram Desktop 5.4.1

### Installation source

Static binary from official website

### Crash ID

Null

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
also, not really sure if it's bug.

**Comment by john-preston** [comment]
@Pszz Well, in case you mention a user who doesn't have a @usernam, the mention can have arbitrary text, by default the one you've saved for yourself. You can change the text if you like before sending. That's how mentions for users without usernames work on Telegram, if I understood your issue correctly.

**Comment by Pszz** [comment]
> @Pszz Well, in case you mention a user who doesn't have a @usernam, the mention can have arbitrary text, by default the one you've saved for yourself. You can change the text if you like before sending. That's how mentions for users without usernames work on Telegram, if I understood your issue correctly.

--------------------------------------------------------------------------------
Yes, maybe the user didn’t set the first name and last name
So in the group, the @username that others have commented on him is displayed.

But I think the user's account should be displayed

Let's say I nicknamed my boss "Joker". 
When I report to my work group @boss, others, including my boss, see the nickname I gave him. 😄

**Comment by john-preston** [comment]
@Pszz Once again, everyone is seeing exactly what you see in the message input field before you send it. If you don't like what you see you can change it, change the mention text, for example.
