### ISSUE TITLE
2-step verification description is "cut"

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2829]
### Steps to reproduce
1. Try to enable "2-step verification" via settings
2. Try to read the description.

### Expected behaviour
All lines should be seen properly

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/2780044/21922207/5e1a2a2c-d97e-11e6-96e8-519030e0fbbf.png)

### Configuration
**Operating system:** Windows 10 LTSB x64
**Version of Telegram Desktop:** 1.0 alpha

**Comment by john-preston** [comment]
@MasterGroosha Thank you for your report! This will be fixed in the upcoming version.

**Comment by MasterGroosha** [comment]
Fixed in 1.0.1 alpha. Thanks!
