### ISSUE TITLE
macOS popup accent menu does not appear

### ISSUE THREAD

**Issue by jacopo-j** [telegramdesktop/tdesktop#2830]
On macOS it is possible to enter accented characters by holding down the letter that should be accented. For example, to type "è", you can hold down letter "e" for a second, then a popup showing "e" with various accents appears to choose from. The feature is described here: https://support.apple.com/en-us/HT201586
Telegram Desktop for Mac does not seem to support this feature. This may be (is, IMO) a Qt related issue. However, this is very annoying when using a language that has a lot of accents such as Italian, especially on a messaging app. Either a solution or, at least, a workaround should be found.

### Steps to reproduce
1. When typing a message, hold down (for example) the letter "e"

### Expected behaviour
The accent menu should pop up

### Actual behaviour
The accent menu does not pop up

### Configuration
**Operating system:** macOS 10.2.2

**Version of Telegram Desktop:** 1.0

**Comment by luckydonald** [comment]
![image](https://cloud.githubusercontent.com/assets/2737108/21956824/44bd6592-da89-11e6-9b69-a013d2851a1f.png)

**Comment by stek29** [comment]
I'm pretty sure it's a duplicate, but can't find it.

Anyway, app uses Qt input fields, not macOS native ones. And Qt doesn't support those.

**Comment by ytze** [comment]
actually "mac style accents" were working until a couple of telegram updates ago.

**Comment by john-preston** [comment]
@ytze Maybe you've used other macOS app, they've never worked in Qt.

**Comment by toyg** [comment]
It would have been kind to mention that there is a workaround: Option-` + \<letter\>. E.g. to get à, press Option and "`" together and then "a". This works even in Qt (and hence in telegram).
