### ISSUE TITLE
Telegram Mini apps not opening on Ubuntu 24.04 x11.

### ISSUE THREAD

**Issue by MrBns** [telegramdesktop/tdesktop#28307]
### Steps to reproduce

1. Installed telegram on ubuntu from `tssetup.tar.xz` file.
2. did nothing just logged in to accoun.
3. tried to open wallet but it doesn't show anything.   Past I got error to install webkit2gtk. but this time I didn't get any of them. it opens but doesn't show anything.

### Expected behaviour

When I open wallet should show the contents of that mini apps.

### Actual behaviour

Instead of showing bot contents it totally blank.  by right clicking I can access webveiw context menu. here is a small video.

https://github.com/user-attachments/assets/e7971670-8c8d-42b9-83c7-b5d2a9f57cb3

### Operating system

Ubuntu 24.4 - Gnome x11

### Version of Telegram Desktop

5.4.1

### Installation source

Static binary from official website

### Logs

```shell
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
  OpenType support missing for "Open Sans", script 12
  OpenType support missing for "vazirmatn ui nl", script 12
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
```

**Comment by ilya-fedin** [comment]
This looks like your system is broken. Do other applications using webkitgtk (e.g. epiphany) work?

**Comment by MrBns** [comment]
> This looks like your system is broken. Do other applications using webkitgtk (e.g. epiphany) work?

Hi, yes this isn't telegram issue. Sorry for making noice. 

I installed tauri and checked the webview there also webview doesn't work. 
you can close this issue.

**Comment by MrBns** [comment]
got back to ubuntu 23.10.1 and it works perfectly fine. seems like ubuntu 24.04 has a lots of bug with graphical stuffs.

**Comment by Aokromes** [comment]
p.s. everyone can close their own issues.
