### ISSUE TITLE
Telegram disappeared with years and months of content from my group

### ISSUE THREAD

**Issue by aeon1911** [telegramdesktop/tdesktop#28308]
### Steps to reproduce

I have a group with different discussion topics about science and technology aimed at my university. This morning, I woke up with the group having only 5 topics, and with all the pdfs, articles and photos deleted from it, I went to check if it had been hacked or something like that and no different session with IPs from other countries had been accessed, simply They deleted all the group's content without warning, and also without any files being copyrighted as they were articles and photos taken by college students...

### Expected behaviour

Show all topics correctly with all the content of each one.

### Actual behaviour

Only one topic appears on the desktop application, 10 topics appear on the cell phone, and only 5 topics appear on other students' accounts.

### Operating system

WINDOWS 11

### Version of Telegram Desktop

5.4.1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
desktop cannot delete content.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
