### ISSUE TITLE
The program silently closes under a certain condition.

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [telegramdesktop/tdesktop#28306]
### Steps to reproduce

1. Open one of the dialogs, chats or channels as a separate window.
2. Click on the lock button to block the messenger or wait for automatic blocking.
3. Try to enter the password in one of the two windows.
4. The program suddenly crashes silently. (A few months ago, everything was fine).

### Expected behaviour

***

### Actual behaviour

***

### Operating system

Win10

### Version of Telegram Desktop

Latest v5.4.1.

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by Ukhryuk-Hai** [comment]
I don't know where to get a really current beta version of Telegram. First, I enabled "check for beta version" in the settings and pressed the button to manually check for updates - no reaction. Then I went to the official site in search of a beta, but there was only the old version 5.2.5, which I did not install.

As for Crash ID, I did not see any messages about anything like that from the program. It just silently closes and when I launch it later - no messages either.

**Comment by Aokromes** [comment]
> I don't know where to get a really current beta version of Telegram. First, I enabled "check for beta version" in the settings and pressed the button to manually check for updates - no reaction. Then I went to the official site in search of a beta, but there was only the old version 5.2.5, which I did not install.
> 
> As for Crash ID, I did not see any messages about anything like that from the program. It just silently closes and when I launch it later - no messages either.

enabling beta and restarting enables beta.

**Comment by Ukhryuk-Hai** [comment]
I did it. The version has not changed.

**Comment by Ukhryuk-Hai** [comment]
I don't know if this will help, but I have two accounts. It doesn't matter if the second window belongs to the second account.

Can anyone with one account check if they have this bug?
