### ISSUE TITLE
Not repsonsive after update to 5.4.0 (loading list of chats forever)

### ISSUE THREAD

**Issue by ghormoon** [telegramdesktop/tdesktop#28301]
### Steps to reproduce

1. unpack binary downloaded from web
2. run
3. wait few minutes (no window or anything)
4. two log lines appear
5. few more minutes, window with telegram appears, i see I'm logged in, but chat list is "Loading .." forever

i tried removing telegram data in .local and logging in again, but it won't show me any QR code, just the instructions
i assume my previous version was 3.5.2 as that's the info i have in my linked applications on telegram on phone, but maybe that was just when i linked and doesn't reflect versions in between i updated to.

### Expected behaviour

Chats list loads, can write messages etc.

### Actual behaviour

Chat list empty, writinig into saved messages (only chat i can reach through the left top menu) does never get delivered.

### Operating system

Debian 12 (LXC container, both host and container is Debian 12)

### Version of Telegram Desktop

5.4.0

### Installation source

Static binary from official website

### Logs

```shell
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
```

**Comment by ilya-fedin** [comment]
Can you reproduce without container?

**Comment by ghormoon** [comment]
I just tried installing it on host, the log errors are the same, but it seems to load the qr code and login properly.

So it somehow started using something that it was not using before, because it doesn't work in container even if it has access to host X window socket directly. strace shows it waiting long time on some futex when waiting for the log lines

**Comment by ilya-fedin** [comment]
Yeah, it's likely a container problem, not a tdesktop bug

**Comment by ghormoon** [comment]
i's at least a bug on the level, that it doesn't log, what it tries to access and fails. the only thing that changed is tdesktop version.

**Comment by ilya-fedin** [comment]
the static binary has lots of 3rd party dependencies, I'm really doubt they log everything and there's nothing tdesktop could do about that. This is debuggable with a debugger only I'm afraid.

**Comment by ghormoon** [comment]
when trying to get the QR code, i'm getting a fast spam of this in strace, but i'm not sure what is the unavailable resource

```
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 7) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 7) = 0 (Timeout)
[pid 49761] recvmsg(13, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 49761] poll([{fd=6, events=POLLIN}, {fd=13, events=POLLIN}, {fd=16, events=POLLIN}, {fd=34, events=POLLIN}], 4, 8) = 0 (Timeout)
```

**Comment by ilya-fedin** [comment]
strace is usually unhelpful with such type of issues, you need a debugger such as gdb

**Comment by ilya-fedin** [comment]
Note that debuggers require your own build of software to be helpful

**Comment by dimas1980200** [comment]
***@***.***

чт, 22 авг. 2024 г., 5:16 ilya-fedin ***@***.***>:

**Comment by ghormoon** [comment]
weird, i've found `-debug` optiom here https://github.com/telegramdesktop/tdesktop/issues/2058
I assumed maybe i;ll get some more useful error, but nterestingly, it fixes the issue. I have no clue why.

**Comment by ilya-fedin** [comment]
Maybe it's not -debug but the way you started it to specify the argument?

**Comment by ghormoon** [comment]
i started it the same way (it had `-noupdate` before, so i just added it. but it had issues even without `-noupdate`)

**Comment by ilya-fedin** [comment]
magic

**Comment by ghormoon** [comment]
my only explanation is that `-debug` adds some error handling that is not there without it and what fails is not really important bot the basic usecases, so it allows it to run. Maye when i'll have more time i'll try to find out to figure out what is missing in the container, so we can document the dependency.

**Comment by ilya-fedin** [comment]
> so we can document the dependency

What do you mean by that? Such effect usually happens when some system component is installed but broken. So it's really not a tdesktop material but a distro one.

**Comment by ilya-fedin** [comment]
You perhaps mis-analyzed it. When a d-bus service causes hangs, it means the d-bus service is broken (unable to launch). The cause of brokenness could be a missing package indeed but it doesn't make an application dependency, it's still a dependency of that system service and has nothing to do with application (if you delete the d-bus service itself the hangs will stop just as well). The same about drivers as they frequently consist of multiple parts one depending of and not always handling the lack of those parts.
