### ISSUE TITLE
Mining in folded mode

### ISSUE THREAD

**Issue by UnrealKaraulov** [telegramdesktop/tdesktop#28310]
### Steps to reproduce

1. Start utility with name telegram desktop.
2. Read something sometimes.
3. Shrink window to down.

### Expected behaviour

Should stop eating the processor like cake.

### Actual behaviour

Devours a whole CPU thread at 100% like elephant!

![image](https://github.com/user-attachments/assets/aa13fe26-195e-403d-b35d-8a9404e3bc85)

### Operating system

Windows 11

### Version of Telegram Desktop

5.4.1 x64

### Installation source

Static binary from official website

**Comment by rakakarakaka** [comment]
> this bug tracker is english only, plz, update your issue or it will be closed on 24h.

ты что хохол что ли? где ваша демократия ? что за расизм такой?)

**Comment by rakakarakaka** [comment]
> this bug tracker is english only, plz, update your issue or it will be closed on 24h.

подскажу тебе https://translate.google.com/ переведет тебе на любой из 100 языков, даже на мойву хохлятскую

**Comment by rakakarakaka** [comment]
@23rd фу xoxoл что ли, или лягушатник из франции, как там Пашка поживает у вас?

**Comment by UnrealKaraulov** [comment]
> this bug tracker is english only, plz, update your issue or it will be closed on 24h.

i bad know english but tried to replace bad russian words to true english words

**Comment by UnrealKaraulov** [comment]
Added information : render mode = DX12_on_DX11

**Comment by Aokromes** [comment]
no telegram doesn't mines.
