### ISSUE TITLE
Set a local password (per account) to view chats

### ISSUE THREAD

**Issue by morington** [telegramdesktop/tdesktop#28314]
### Is your feature request related to a problem?

The problem is this: if a user's account is taken over by someone else, they will be able to view all of that user's chats.

### Describe the solution you'd like

In the settings for private messages or conversations a user is in, add a function to set a password that will not let the user into the chat until they enter it. You can create a unique password for each chat. The password does not affect other users and can be set only if desired.

### Describe alternatives you've considered

I haven't seen any other alternatives yet

**Comment by morington** [comment]
Additionally, I can add that if a user has children and often gives them their phone, a password for work chats will prevent the child from accidentally doing something in that chat.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
