### ISSUE TITLE
Unfortunately, you can't access this message, but i'm the owner

### ISSUE THREAD

**Issue by souvenp** [telegramdesktop/tdesktop#28312]
### Steps to reproduce

https://github.com/telegramdesktop/tdesktop/issues/8108
I create a private group,and get its id, and let bot send a message, then enter the link https://t.me/c/4xxxxxxxxx/xxxx says 'Unfortunately, you can't access this message.You.aren't a memberof the chat where it was post
the id  is -4xxxxxxxxx, but some other group's id is 2xxxxxxxxx, this is normal

### Expected behaviour

normal

### Actual behaviour

unable to enter

### Operating system

win10

### Version of Telegram Desktop

5.4.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
It's already explained in the issue you mentioned, no need to create a duplicate
