### ISSUE TITLE
Green video in DirectX 9 mode

### ISSUE THREAD

**Issue by UnrealKaraulov** [telegramdesktop/tdesktop#28313]
### Steps to reproduce

1. Install telegram desktop utility
2. Enter and play random video
3. Green video

### Expected behaviour

No green video.

### Actual behaviour

Green video.

![image](https://github.com/user-attachments/assets/31fbe35a-415f-4a63-bca4-32d33fa8f12a)

(sorry for bad english language known)

### Operating system

Windows 11 x64

### Version of Telegram Desktop

5.41 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#24360

**Comment by UnrealKaraulov** [comment]
@Aokromes closed as fixed or not? How to fix green video?

**Comment by ilya-fedin** [comment]
closed as a duplicate
