### ISSUE TITLE
Pasting image to GIMP does not work

### ISSUE THREAD

**Issue by arisudesu** [telegramdesktop/tdesktop#28328]
### Steps to reproduce

1. Open any image in full-screen in Telegram Desktop, right-click, select "Copy".
2. Open GIMP, select menu "File -> Create -> From clipboard" or press Ctrl+V.

OR

1. Open any image in full-screen in Telegram Desktop, right-click, select "Copy".
2. Open GIMP, create empty image with "File -> Create project"
3. Right-click on canvas and select "Edit -> Paste"

### Expected behaviour

Copied image is pasted into GIMP.

### Actual behaviour

Nothing is pasted with error. See attached video.

https://github.com/user-attachments/assets/2126b1ba-a265-4e52-85ac-68d6c4eeae46

### Operating system

Windows 10 22H2

### Version of Telegram Desktop

5.4.1 x64

### Installation source

Static binary from official website

**Comment by arisudesu** [comment]
Clipboard issues strike back in Telegram, similar to [an old issue that needed 2 years to fix](https://github.com/telegramdesktop/tdesktop/issues/10564) but in reverse direction. Copying works but in one rare case.

Also since the previous bug, in fact, was caused by Telegram and was fixed on its side, I tend to think that the new bug is caused by Telegram too and is not a bug in GIMP.

**Comment by ilya-fedin** [comment]
If you look at the code, you would see that the bug is closed with a workaround with special handling for Firefox. Saying that it is caused by Telegram is incorrect.

**Comment by ilya-fedin** [comment]
Yeah, input and clipboard are two things Qt is pretty bugged at
