### ISSUE TITLE
wayland screensharing doesnt work  

### ISSUE THREAD

**Issue by Abhinavpatel00** [telegramdesktop/tdesktop#28329]
### Steps to reproduce

1. open telegram call and try to screen share you it will say an error occured screencast has stopped 
2. i tried to dig into something by launching it to terminal but just got this  whenever i tried to do screencast '"QWidget::repaint: Recursive repaint detected"

### Expected behaviour

i should be able to do screen share 

### Actual behaviour

screen share won't work

### Operating system

Arch linux + sway  (as window manager )

### Version of Telegram Desktop

5.4.0

### Installation source

Static binary from official website

### Logs

```shell
helpful part from log
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name is not activatable")
qt.svg: Error while inflating gzip file: SVG format check failed
QWidget::repaint: Recursive repaint detected
```

**Comment by ilya-fedin** [comment]
Unable to reproduce, screen share starts just fine

**Comment by Abhinavpatel00** [comment]
> Unable to reproduce, screen share starts just fine

are you able to screen cast in any wlroots based wayland compositor like sway?

**Comment by ilya-fedin** [comment]
Sorry but I don't have a wlroots compositor.
