### ISSUE TITLE
IDN domains (with emoji) do not work

### ISSUE THREAD

**Issue by why** [telegramdesktop/tdesktop#2832]
### Steps to reproduce
1.  Write a message containing a domain that doesn't work properly, for example "http://⬆️.ws" 
2.  Send the message
3.  Click the URL

### Expected behaviour
It should open the punycode version of this domain, in the case of this example that is "http://xn--b5i.ws"

### Actual behaviour
It opens your browser and navigates to "ws/" instead, which obviously does not work!

### Configuration
Windows 10
Telegram Desktop Version 1.0

**Comment by notmika** [comment]
Just bumping this. Any chance it can be fixed?

**Comment by legit** [comment]
Annoying issue. Still not working :[

**Comment by notmika** [comment]
Month and a bunch of updates later, still no response. 'Sup?

**Comment by notmika** [comment]
Updated

**Comment by auchri** [comment]
@notmika 

> Write a message containing a domain that isn't clickable (ex: http://🕦.ws)

That's not a bug of telegram desktop (doesn't work on Android too). You should contanct [Telegram on Twitter](https://twitter.com/telegram).

**Comment by notmika** [comment]
I see @auchri thanks

**Comment by Mistero5050** [comment]
@auchri, the fact that it doesn't work on android does not mean that it's not also a telegram desktop problem.

**Comment by stek29** [comment]
@Mistero5050 links are parsed on server side.

**Comment by RadRussianRus** [comment]
2.1.1 still has this issue, but in different form. It looks like this:
![](https://user-images.githubusercontent.com/2903496/80935065-a1c6d600-8dd3-11ea-83c3-097fa9ed55dc.png)
Clicking "Open" does nothing.

**Comment by alissonlauffer** [comment]
Any chance of this being fixed? Thanks.
