### ISSUE TITLE
Telegram crashes when clicking on an image (Qt5 only)

### ISSUE THREAD

**Issue by shamazmazum** [telegramdesktop/tdesktop#28330]
### Steps to reproduce

1. Make a RELEASE build (`-DCMAKE_BUILD_TYPE=RELEASE`) of telegram 5.4.1 with Qt5 using clang (my version is 18.1.5)
2. Open any chat/channel
3. Click on any picture
4. Telegram will crash

### Expected behaviour

Telegram must show an image

### Actual behaviour

Crash

### Operating system

FreeBSD 14.1

### Version of Telegram Desktop

5.4.1

### Installation source

Built from sources downloaded here on Github

**Comment by shamazmazum** [comment]
It's important that you build with optimization flags (make a RELEASE build), otherwise telegram will work as expected.

Commit responsible for this bug: 5180e0e

Moving `_window->createWinId();` back to its original place solved the problem.
So you need either another `#if`/`#endif` block, or call `createWinId()` unconditionally, I don't know what's better.

**Comment by ilya-fedin** [comment]
Can't you just provide a back trace with debug symbols?

**Comment by ilya-fedin** [comment]
> It's important that you build with optimization flags (make a RELEASE build), otherwise telegram will work as expected.

I also have a feel that you should rather report this to clang as miscompilation
