### ISSUE TITLE
Large windows and fullscreen mode move my messages to the left side of the screen (macOS)

### ISSUE THREAD

**Issue by fmatter** [telegramdesktop/tdesktop#2833]
When the window is large enough (including fullscreen), my own messages will be displayed at the same width as that of the other participant(s) in the chat. [Illustration of what I mean](https://gfycat.com/BronzePoliticalEmperorshrimp)

### Steps to reproduce
1. Have open chat with visible message written by self
2. Enlarge window or enter fullscreen

### Expected behaviour
My own messages should stay where they are, glued to the right side of the window.

### Actual behaviour
They move over to the left side of the window.

### Configuration
**Operating system:** macOS 10.12.1

**Version of Telegram Desktop:** 1.0

**Comment by notmika** [comment]
That is supposed to happen as far as I know. It's for readability, otherwise you'd have to look allll the way to the other side of your screen to see the other persons messages..

**Comment by auchri** [comment]
There is a setting for that

**Comment by MasterGroosha** [comment]
By the way, that setting is called "Adaptive layout for wide screens" and is shown only when your TDesktop window is large enough.
(just to be sure you won't miss this option)

**Comment by fmatter** [comment]
> that setting is called "Adaptive layout for wide screens" and is shown only when your TDesktop window is large enough.

Ah. That explains it. I had of course looked for a setting before posting -- but apparently only in a small window. Thanks!
