### ISSUE TITLE
Text RTL problem in Beta Version 5.4.4

### ISSUE THREAD

**Issue by AliDeV7** [telegramdesktop/tdesktop#28331]
### Steps to reproduce

In Beta version 5.4.4, all Persian and Arabic texts in channels and groups are displayed in LTR (Left-to-Right) format! Whereas, up to version 5.4.1 (the stable version), all texts were displayed correctly in RTL (Right-to-Left) format without any issues. This problem occurs when sending or editing text, and when Persian text is combined with English text, the RTL and LTR formatting gets messed up.

Please fix this issue in the stable version.

### Expected behaviour

When the first character in a line is in Persian or Arabic, the text should be displayed in RTL format, and if the first character is in English, the text should be displayed in LTR format.

### Actual behaviour

All text displayed in LTR

### Operating system

Windows

### Version of Telegram Desktop

5.4.4 Beta

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Please show two screenshots, one from 5.4.1, another from 5.4.4 and also copy the text itself in a separate paragraph below so that I could reproduce and see the difference for myself.

**Comment by AliDeV7** [comment]
5.4.4 Beta
![image](https://github.com/user-attachments/assets/279b5d4f-99bf-49ce-bc5b-15ca5a28c8eb)

5.4.1
![image](https://github.com/user-attachments/assets/185e6d32-d7e4-47b9-9196-915109bd1d4c)


text :
The Great Beauty (2013)
Original title: La grande bellezza

✅ | زیرنویس فارسی چسبیده
⛔️ | بدون سانسور 
🔗 | کیفیت 720p

💜 LadyLStories (https://t.me/LadyLStories) 💜

**Comment by john-preston** [comment]
Well, it is displayed rtl, but on smaller width, I guess (see alignment of different rows).

But ok, I'll try to make it using full bubble width again, like it was before.

**Comment by AliDeV7** [comment]
in Edit mode, it has RTL problem too

![image](https://github.com/user-attachments/assets/6a3d791a-8c11-4cff-a122-4a33e0416d47)

Thanks

**Comment by AliDeV7** [comment]
After Just Press (Shift + Enter) everything looks fine 

![image](https://github.com/user-attachments/assets/925bc1bd-3fbb-497c-9fb2-f28d9f5a5944)

**Comment by AliDeV7** [comment]
I mention that in previous telegram version, it's work fine and I don't have any problem with RTL and LTR

**Comment by john-preston** [comment]
Well, the message input field should behave the same in previous stable and the latest beta. But the message text indeed is different.

**Comment by john-preston** [comment]
![image](https://github.com/user-attachments/assets/0b1f6e12-0235-425b-ac47-7cc118cbbad9)
Ok, this will fix the messages. Input field is harder though :(

**Comment by AliDeV7** [comment]
no problem, just final messages will be fix it is ok :)

**Comment by AliDeV7** [comment]
It was strange to me that even the input field worked correctly in previous versions, and suddenly this issue occurred in the latest version.

**Comment by john-preston** [comment]
Input field worked exactly the same as it works in the latest version 🤔

**Comment by john-preston** [comment]
Yeah, it started in Input Field since there are editable blockquotes / code blocks in the input field. They had me change used line separators from those which reset RTL/LTR state of the following text to those which preserve the direction from previous line 😢

**Comment by AliDeV7** [comment]
Yes, I understand now :) I hope you can find a solution for it, and at least the Message display mode won't have any issues in the next version.

Anyway, thank you! I'm very happy to have spoken with one of the developers of the Telegram app.
