### ISSUE TITLE
Fonts in macOS are difficult to see and can't be changed

### ISSUE THREAD

**Issue by carlosrovira** [telegramdesktop/tdesktop#2834]
Hi, Just installed the new Telegram Desktop App and I found it great, but there's a thing I'm suffering and is the actual fonts and size of the font. the fonts in macOs are much difficult to read that the old version.

I think this is not a bug (in the strict term) but something that makes me think in go to the old version while this is enhanced

Thanks for listening

**Comment by Aokromes** [comment]
#90
