### ISSUE TITLE
The old bug with updating counters of unread messages in channels has returned 

### ISSUE THREAD

**Issue by flexile** [telegramdesktop/tdesktop#28344]
### Steps to reproduce

The old bug, repeatedly described in other threads, has returned
https://github.com/telegramdesktop/tdesktop/issues/28117
https://github.com/telegramdesktop/tdesktop/issues/28037

### Expected behaviour

The channel's publication counter should display the actual number of unread messages

### Actual behaviour

The channel's notification counter doesn't update until you open the channel itself.

### Operating system

macOS Monterey

### Version of Telegram Desktop

Telegram Desctop 5.4.1 (as well as 5.4.2; 5.4.4 beta; 5.4.5 beta)

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Please don't open issues closed as api issue. They will be closed again anyway.

**Comment by flexile** [comment]
The issue is closed, but the problem remains? Good.

**Comment by ilya-fedin** [comment]
Client-side developers can't fix server-side issue, there's no point in creating such issue here.

**Comment by Neurotoxin001** [comment]
https://bugs.telegram.org/c/43085 like it here
