### ISSUE TITLE
Exception thrown: Read access violation. _Mem was 0xFFFFFFFFFFFFFFFF.

### ISSUE THREAD

**Issue by atrdev-rgb** [telegramdesktop/tdesktop#28347]
### Steps to reproduce

1. I assemble it and it starts without problems.
2. I am get url https://telegra.ph/usa-03-16-6 (any url) in telegram
3.  I am press button to look
![image](https://github.com/user-attachments/assets/07d399db-5e63-46e1-a17e-6b61d6231ed0)
4. then an error appears:

### Actual behaviour

Exception thrown: Read access violation.
_Mem was 0xFFFFFFFFFFFFFFFF.
An unhandled exception was thrown: read access violation.
_Mem was 0xFFFFFFFFFFFFFFFF.

in the method _As_bytes = __iso_volatile_load32(_Mem);
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\atomic

### Operating system

Windows 11

### Version of Telegram Desktop

5.4.5 beta x64

### Installation source

assembly from https://github.com/telegramdesktop

### Logs
Then i press button to look:
18:12:16:712 "Telegram.exe" (Win32). Loaded "C:\Program Files (x86)\Microsoft\EdgeWebView\Application\127.0.2651.86\EBWebView\x64\EmbeddedBrowserWebView.dll". 
18:12:16:712 "Telegram.exe" (Win32). Loaded "C:\Windows\System32\edputil.dll". 
18:12:17:268 An exception was thrown at address 0x00007FF7D6139E05 in Telegram.exe: 0xC0000005: Read access violation at address 0xFFFFFFFFFFFFFFFF.
18:12:17:268 An unhandled exception was thrown: read access violation.
18:12:17:268 **_Mem** was 0xFFFFFFFFFFFFFFFF.
18:12:17:268

**Comment by ilya-fedin** [comment]
> Then i press button to look:
> 18:12:16:712 "Telegram.exe" (Win32). Loaded "C:\Program Files (x86)\Microsoft\EdgeWebView\Application\127.0.2651.86\EBWebView\x64\EmbeddedBrowserWebView.dll".
> 18:12:16:712 "Telegram.exe" (Win32). Loaded "C:\Windows\System32\edputil.dll".
> 18:12:17:268 An exception was thrown at address 0x00007FF7D6139E05 in Telegram.exe: 0xC0000005: Read access violation at address 0xFFFFFFFFFFFFFFFF.
> 18:12:17:268 An unhandled exception was thrown: read access violation.
> 18:12:17:268 **_Mem** was 0xFFFFFFFFFFFFFFFF.
> 18:12:17:268

I fail to understand what that is? It looks unrelated to the problem given that it says `Telegram.exe` while `WebView has crashed` prints in case system webview process has suddenly exited, not `Telegram.exe`

**Comment by ilya-fedin** [comment]
And all such cases were due to users modifying Windows so far, removing/disabling various its parts and thus breaking the system webview service.

**Comment by Aokromes** [comment]
can't reproduce on windows 10 / 11

**Comment by atrdev-rgb** [comment]
Yes, that's what happened. Edge has been blocked. After unlocking, everything started working fine. However, is it possible to somehow add this to the exception right away, so that later it won’t crash because of such a trifle?

**Comment by Aokromes** [comment]
you want web to work blocking web?

**Comment by ilya-fedin** [comment]
> However, is it possible to somehow add this to the exception right away, so that later it won’t crash because of such a trifle?

What do you mean by this? This text means the system service has crashed. tdesktop can't force system service not to crash.

**Comment by atrdev-rgb** [comment]
try {} catch {} so that if the system component crashes, the application does not crash

**Comment by john-preston** [comment]
Well, the application didn't crash, if I read your report correctly. The webview process (outside of Telegram Desktop, not controlled by code in this repository) exited / crashed. Telegram Desktop just showed you this information.

Or did Telegram Desktop crash after the webview process exited? If so, Crash ID is necessary from the next launch.

**Comment by atrdev-rgb** [comment]
In the prod version the error appeared, but the application did not crash. However, in debug in the IDE application, after this error, further work is not possible. The application closes.
