### ISSUE TITLE
Entirely remove window frame

### ISSUE THREAD

**Issue by mhkarimi1383** [telegramdesktop/tdesktop#28341]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Just like what we have for `nativeWindowFrame` in advanced settings we should have something like `disableWindowFrame` that removes entire frame
this is a very great feature when Telegram used in Window managers

### Describe alternatives you've considered

Nothing

**Comment by ilya-fedin** [comment]
> we should

Why should? No other application has such a feature

**Comment by mhkarimi1383** [comment]
@ilya-fedin 

My other apps are not having any decorations while I'm in HyprWM (e.g. VSCode)

**Comment by ilya-fedin** [comment]
Well, tdesktop follows the preference returned by `busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings Read ss org.gnome.desktop.wm.preferences button-layout`. If it returns empty value, titlebar should disappear. If it returns a error, tdesktop fallbacks to the default (buttons on the right side).

**Comment by mhkarimi1383** [comment]
```shell
gsettings set org.gnome.desktop.wm.preferences button-layout ""
```
removed them, thanks :)
