### ISSUE TITLE
Text rendering error

### ISSUE THREAD

**Issue by MaKeSter333** [telegramdesktop/tdesktop#28340]
### Steps to reproduce

1. Download tdesktop version 5.4.5 beta x64
2. The default font is selected, open any chat, for example, write the text "тёрка". The problem arises not only with the Russian language.

![image](https://github.com/user-attachments/assets/69354fae-d320-427f-a558-81159eff984c)

notice the strange indentation between the letters

### Expected behaviour

Correct text rendering with a standard font

### Actual behaviour

Incorrect text rendering

### Operating system

windows 11

### Version of Telegram Desktop

5.4.5 beta x64

### Installation source

Static binary from official website

**Comment by Zensonaton** [comment]
Same problem here. 
`Я разговаривал с этими людьми`: ![img](https://github.com/user-attachments/assets/71a8a4e9-9011-4810-aee2-60d10d38c771), can be seen in text field and messages.

**Comment by exzolink** [comment]
Same issue

**Comment by Aokromes** [comment]
@MaKeSter333 can you remove "Russian" from issue description? not only russian is bugged.

**Comment by ShamHyper** [comment]
Такая же проблема

**Comment by ShamHyper** [comment]
Same

**Comment by john-preston** [comment]
Thanks! That'll be fixed in the next version.
