### ISSUE TITLE
Extra indentation in words

### ISSUE THREAD

**Issue by Dimoka113** [telegramdesktop/tdesktop#28342]
### Steps to reproduce

Write a word that contains "ret", for example "return"

### Expected behaviour

![image](https://github.com/user-attachments/assets/2d49b981-8927-4e3f-833d-51cf98580717)

### Actual behaviour

![image](https://github.com/user-attachments/assets/d9252be4-0478-4de9-9e14-606459f4c446)
there is extra indentation between "re" and "t"

### Operating system

Windows 10

### Version of Telegram Desktop

5.4.5

### Installation source

Static binary from official website

**Comment by Dimoka113** [comment]
Maybe duplicate #28340 *

**Comment by Aokromes** [comment]
yes
