### ISSUE TITLE
request of adding an account and password login function

### ISSUE THREAD

**Issue by philomel** [telegramdesktop/tdesktop#28343]
### Is your feature request related to a problem?

yes, because i lost my my old account's telephone number, so i cannot log in to my original account now. It's very confused.

### Describe the solution you'd like

Why not add an account and password login function on the telegram login page. 
Since some of the users has set a two-step password to enhance security, why can't we use the first-step password to log in?

### Describe alternatives you've considered

or maybe telegram can be bound to Google login or Apple login, I think it's also good.

### Additional context

null, you can contact me @veronicashimz

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
