### ISSUE TITLE
some times Does not Show UI 

### ISSUE THREAD

**Issue by rezaei** [telegramdesktop/tdesktop#28346]
### Steps to reproduce

Some times Telegram Doesn't show the ui and doesn't work  at all 
then i have to restart  the windows 10 
![Telegram Error](https://github.com/user-attachments/assets/92258711-0818-49e6-88d0-c976427558f9)

![image](https://github.com/user-attachments/assets/a9b0bed8-6938-4044-97c5-a8580349fdec)

### Expected behaviour

.

### Actual behaviour

.

### Operating system

windows 10

### Version of Telegram Desktop

5.4.1 x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
/
plz, open task manager when telegram freezes, then right click over telegram -> create dump and send to https://t.me/preston

**Comment by ChrisMTheMan** [comment]
I'm not the OP but I am having the same problem.  I'm on Win7.  When I try to upload the dump it says I'm limited to 25mb.  The dump file is 366mb.

**Comment by ilya-fedin** [comment]
Upload to e.g. Google Drive?

**Comment by ilya-fedin** [comment]
Or, even better, send the dump privately to https://t.me/preston

**Comment by ChrisMTheMan** [comment]
Trying to sent dump file via TG on my phone right now.

**Comment by ChrisMTheMan** [comment]
I removed all portable and installed versions of TG from my PC.  I removed the install folder and all reg keys.  Rebooted, reinstalled 5.5.1 and it's working great now.
