### ISSUE TITLE
Receive Message Status Updates for Bot Sent Messages

### ISSUE THREAD

**Issue by paymaan73** [telegramdesktop/tdesktop#28345]
### Is your feature request related to a problem?

Receive Message Status Updates for Bot Sent Messages

### Describe the solution you'd like

Hello Telegram Team,

I am writing to request a feature enhancement for the Telegram Bot API. Currently, while we can use webhooks or polling to receive updates on messages sent by users to the bot, there is no straightforward way to receive status updates (e.g., delivered, read) for messages that the bot sends to users.

This feature would be incredibly useful for developers who want to track the delivery and read status of messages sent from their bots to users. It would improve the overall user experience and provide more control over message interactions.

Please consider adding this capability to the Telegram Bot API, as it would be a valuable addition for many developers working with Telegram bots.

Thank you for your consideration.

Best regards,  paymaan kazemi

### Describe alternatives you've considered

Receive Message Status Updates for Bot Sent Messages

**Comment by kia-salvati** [comment]
I have the same problem. If it could be added to the webhook that would be great.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
