### ISSUE TITLE
Crash on interface scale adjustment

### ISSUE THREAD

**Issue by lexcyn** [telegramdesktop/tdesktop#28354]
### Steps to reproduce

Build Telegram from source (in this case I am building the ARM64 version in Windows)
Go into Settings
Adjust default interface scale

### Expected behaviour

Scale should change and ask you to restart the client

### Actual behaviour

Telegram crashes with the following error
![Screenshot 2024-09-04 225050](https://github.com/user-attachments/assets/a3d85757-ae39-45a6-a453-f76b0d853d9b)

Attached log.txt
[log.txt](https://github.com/user-attachments/files/16883375/log.txt)

### Operating system

Windows 11 24H2 (ARM64)

### Version of Telegram Desktop

5.4.6

### Installation source

Other (unofficial) source

**Comment by lexcyn** [comment]
Note that the last working version is 5.4.4.

**Comment by ilya-fedin** [comment]
log.txt won't really help here... You got a breakpoint and so you need Visual Studio's debugger to find where that variable resides at.

**Comment by lexcyn** [comment]
> log.txt won't really help here... You got a breakpoint so you need Visual Studio's debugger to find where that variable resides at.

Seems like an issue with QT 6.8 in `qdrawhelper.cpp`, specifically the ARM NEON instructions:

```
#elif defined(__ARM_NEON__)
        const int16x8_t colorMask = vdupq_n_s16(0x00ff);
        const int16x8_t invColorMask = vmvnq_s16(colorMask);
        const int16x8_t v_256 = vdupq_n_s16(256);
        const int16x8_t v_disty = vdupq_n_s16(disty4);
        const int16x8_t v_disty_ = vshlq_n_s16(v_disty, 4);
        int32x4_t v_fdx = vdupq_n_s32(fdx*4);

        int32x4_t v_fx = vmovq_n_s32(fx);
        v_fx = vsetq_lane_s32(fx + fdx, v_fx, 1);
        v_fx = vsetq_lane_s32(fx + fdx * 2, v_fx, 2);
        v_fx = vsetq_lane_s32(fx + fdx * 3, v_fx, 3);

        const int32x4_t v_ffff_mask = vdupq_n_s32(0x0000ffff);
        const int32x4_t v_fx_r = vdupq_n_s32(0x0800);

        while (b < boundedEnd - 3) {
            uint32x4x2_t v_top, v_bot;

            int x1 = (fx >> 16);
            fx += fdx;
            **v_top = vld2q_lane_u32(s1 + x1, v_top, 0);** < this is the break point
            v_bot = vld2q_lane_u32(s2 + x1, v_bot, 0);
```

**Comment by john-preston** [comment]
@lexcyn Good thing we don't have an official native ARM build =)

**Comment by ilya-fedin** [comment]
I wonder if anyone would spot that before Qt's final release if tdesktop hasn't updated to the beta version (this happens not always)
