### ISSUE TITLE
GIF files sent from Telegram Desktop client are ALWAYS compressed

### ISSUE THREAD

**Issue by Sunsper** [telegramdesktop/tdesktop#28353]
### Steps to reproduce

1. Drag-n-drog a GIF file onto the upper side of the messenger window (where it says that it will send the file **without** compression).
2. Send the file.

### Expected behaviour

The GIF file is sent to the other party without compression.

The thing is that this behavior is completely reproducible in Telegram Web (in both A and K versions).
Only on Telegram Desktop, no matter what I've tried, it is NOT possible to send GIF files without compression, despite the fact that the client still provides you with drag-n-drop choice.

### Actual behaviour

The GIF is sent to the other party as compressed anyway, as though you've dropped the file onto the lower part of the window.
Also on the device/client the file has been sent from it LOOKS like the file hasn't been compressed, but it's actually misleading because the compression is very much evident if you happen to clear up the cache on the client the file was sent from, or look up the sent GIF from another device you're logged into.

### Operating system

Arch Linux x86_64

### Version of Telegram Desktop

5.4.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Server forcefully converts gif into mp4, there's nothing tdesktop could do about that

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by Sunsper** [comment]
> Server forcefully converts gif into mp4, there's nothing tdesktop could do about that

Can't you then just at the very list remove the misleading drag-n-drop option from the desktop client and eliminate this confusion? I mean just like there only a single drag-n-drop option for other types of files, say PDFs.
Because won't you know it, I personally had one very spiteful argument about this with one of my friends, and once in a while I have to explain this phenomenon to other people that never actually noticed it, but now that I told them they're having a mind-blown moment.

**Comment by Sunsper** [comment]
> @Sunsper can you provide the file that causes that?

Literally any file with .gif extension causes two options (compressed and uncompressed) to appear, if that's what you're asking.
![Знімок_20240907_064033](https://github.com/user-attachments/assets/bd7e2a93-c720-435b-8134-50ba8cd6efb1)
On the other hand, files with file extensions like .zip, .pdf and many others I guess provide only one option when they're drag-n-dropped.
![Знімок_20240907_063751](https://github.com/user-attachments/assets/88e81aca-2a84-4aba-9178-25039cf61397)

**Comment by ilya-fedin** [comment]
The problem is I can't reproduce. So I'm asking for exact file.

**Comment by john-preston** [comment]
@Sunsper Can you check 5.5.1 version? I hope I've removed the choice between compressed/uncompressed.

**Comment by Sunsper** [comment]
> @Sunsper Can you check 5.5.1 version? I hope I've removed the choice between compressed/uncompressed.

Well for that I have to wait for 5.5.1 or later to arrive to Arch repositores. Will do once it's there tho.

**Comment by Aokromes** [comment]
> > @Sunsper Can you check 5.5.1 version? I hope I've removed the choice between compressed/uncompressed.
> 
> Well for that I have to wait for 5.5.1 or later to arrive to Arch repositores. Will do once it's there tho.

use official binary, it causes less troubles than distribution packages.

**Comment by Sunsper** [comment]
> > > @Sunsper Can you check 5.5.1 version? I hope I've removed the choice between compressed/uncompressed.
> > 
> > 
> > Well for that I have to wait for 5.5.1 or later to arrive to Arch repositores. Will do once it's there tho.
> 
> use official binary, it causes less troubles than distribution packages.

The problem at hand addressed in this issue has nothing to do with me using build from repositories of my Linux distro, since the exact same problem still bothered me back when I was using Windows as my daily driver and from what I personally can tell it's been there on all desktop clients since forever.

But besides that, I actually never had any problems with build from Arch Linux repos. It's working as expected.

**Comment by Sunsper** [comment]
> @Sunsper Can you check 5.5.1 version? I hope I've removed the choice between compressed/uncompressed.

Though I should note that perhaps the wording should be corrected, because when you drag-n-drop .gif file in the desktop client, it says that the said attachment will be send as a document/file, implying that it won't be compressed, which is absolutely not the case.
This should eliminate the confusion about potato-quality GIFs, hopefully.
