### ISSUE TITLE
Why is monospace different from the desktop client and Android?

### ISSUE THREAD

**Issue by TheFuzzStone** [telegramdesktop/tdesktop#28352]
### Steps to reproduce

![image](https://github.com/user-attachments/assets/231457b3-b61e-43ad-9f4c-d82b10a85877)

1. write some text in any chat ("Saved messages" is ok) from Desktop client
2. format text to monospace
3. do the same from Android client

### Expected behaviour

To make monospace work the same way, preferably as it was before (I mean as an example from the Android client on the screenshot above).

### Actual behaviour

Described above.

### Operating system

Linux

### Version of Telegram Desktop

5.4.5 beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This is intended. Partial monospace is just monospace, whole lines are code.

**Comment by TheFuzzStone** [comment]
@ilya-fedin, so on Android, there's a whole line selected. What's the trick then?

**Comment by ilya-fedin** [comment]
I said how it works on tdesktop, not android. Have no idea what and how android does.

**Comment by TheFuzzStone** [comment]
I just checked, and yes, you're right, if you select part of a word and press Ctrl+Shift+M - you get monospace like on Android (the whole line), and then you can select the second part of the word, press one more time Ctrl+Shift+M, and then you can get the result like it used to be on Desktop, and which now works like that on Android.

Fucking weird logic.
