### ISSUE TITLE
Unable to connect to Telegram, "Strange Http Error: status 5"

### ISSUE THREAD

**Issue by peustr** [telegramdesktop/tdesktop#2835]
Hello guys.

I am using Telegram for Desktop v1.0.0 on MacOS El Capitan v10.11.6.

I launch the app for the first time, and I get the initial screen where I am supposed to input my phone number and region. I get stuck in this screen forever, and on the bottom left there is the message "Connecting..." which eventually times out and switches to "Reconnect in <time> Try now". If I fill in my details and click "Next" in the meantime, nothing happens.

I tried all the trivial solutions like restarting, reinstalling, etc.

After this I tried to launch Telegram in debug mode, which you can do in two different ways, either launch Telegram from the command line with the `-debug` flag, or type "debugmode" on the Settings screen. This logs things in `Library/Application Support/Telegram Desktop/log.txt`.

... which brings me to the weird part of the story. I get a repetition of those logs:
```
[2017.01.13 11:29:33] TCP Error: network - Operation timed out
[2017.01.13 11:30:00] Could not send ping for MTPPingSendAfter seconds, restarting...
[2017.01.13 11:30:37] Strange Http Error: status 5
```

The log comes from [this line](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/mtproto/connection_auto.cpp#L250). I Googled the error a bit and also searched the issues in Github, but unfortunately I have no clue what this error means.

I am not sure of the "Steps to reproduce", to help you reproduce this consistently, I only had to launch the app. I was hoping you could help me with the error.

**Comment by john-preston** [comment]
@peustr The strange error is an internal code, it should not get there — in this place the TCP transport is already chosen. The problem is above: after sending a ping packet the TCP connection times out without getting the response, like something blocks the connection after it is established.

**Comment by peustr** [comment]
Hey, @john-preston thank you for your swift reply.
What about the error code, could we map it to something we can identify? This way we can make it solvable. As you said it is most likely an internal problem (sth blocks the connection), but how could we determine what exactly?

**Comment by john-preston** [comment]
@peustr The error code (status 5) is not an error — this is just the information, that the HTTP transport is still checked while we already chose TCP transport. The problem is that we send a TCP packet and await a response, but instead we get an "operation timeout" network error from that socket.

**Comment by peustr** [comment]
As a follow-up to this, I tried to launch Telegram from a different network connection and it worked, so as John correctly pointed out, my internet connection is blocking the client - nothing wrong with Telegram.
You may close this issue - thank you very much.
