### ISSUE TITLE
Hide archived chats forever from the top of the chat list on telegram desktop on MAC

### ISSUE THREAD

**Issue by fleewortep** [telegramdesktop/tdesktop#28356]
### Is your feature request related to a problem?

there is no option to COLLAPSE archived chats on mac desktop, so the archived chat is ALWAYS on top of the chat list. That drives me crazy.

### Describe the solution you'd like

Make an option to hide archived chats forever

### Describe alternatives you've considered

<img width="396" alt="Screenshot 2024-09-05 at 11 34 56" src="https://github.com/user-attachments/assets/dc10e8d9-523a-47cd-adf0-379684212b31">

**Comment by Aokromes** [comment]
you are using https://github.com/overtake/TelegramSwift

**Comment by fleewortep** [comment]
> you are using https://github.com/overtake/TelegramSwift

yes. there is no collapse option like i showed on a screenshot
