### ISSUE TITLE
Telegram Desktop Flatpak doesn't talk to `org.freedesktop.Notifications`

### ISSUE THREAD

**Issue by xbt573** [telegramdesktop/tdesktop#28360]
### Steps to reproduce

1. Install Telegram Desktop from Flatpak
2. Enable Do Not Disturb mode (KDE desktop)

### Expected behaviour

No notifications or sound appears

### Actual behaviour

Telegram Desktop doesn't show notifications, but it plays notification sound

To fix this, you need to enable Flatpak version of app to talk to `org.freedesktop.Notifications`

### Operating system

Fedora 40

### Version of Telegram Desktop

5.4.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Well, that's intended, flatpak apps are mant to talk to portal. If you want flatpak apps to respect do not disturb, you have to request support for that in the portal API.
