### ISSUE TITLE
Small text in miniapp on linux ( Arch )

### ISSUE THREAD

**Issue by mrafieefard** [telegramdesktop/tdesktop#28362]
### Steps to reproduce

1. Open webapp
2. every text tag is small

### Expected behaviour

It should be in normal size

### Actual behaviour

I open webapp ( any bots ) and every text tag is small

### Operating system

Arch

### Version of Telegram Desktop

5.4.1

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
Can't confirm
![image](https://github.com/user-attachments/assets/e2d5523b-17b2-4a57-ae6c-28450e4ffc6f)

**Comment by mrafieefard** [comment]
> Can't confirm ![image](https://private-user-images.githubusercontent.com/17829319/365296826-e2d5523b-17b2-4a57-ae6c-28450e4ffc6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NTUxNTYsIm5iZiI6MTcyNTY1NDg1NiwicGF0aCI6Ii8xNzgyOTMxOS8zNjUyOTY4MjYtZTJkNTUyM2ItMTdiMi00YTU3LWFlNmMtMjg0NTBlNGZmYzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDIwMzQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NWE4ZjEyOTRkOGZkZjkyNDdhM2YzYmRiNWQyMzFlZTQ5YjllMGU3NjI0MWRiODIxMGY4YWQ2Zjg0NzFlNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QeEf5zSzadjpTYPy7MYdfI7tYPIU8nUFl9I5zA42n0Q)

![image](https://github.com/user-attachments/assets/1eea820b-a931-4b78-bc86-f8e136340cc7)

**Comment by ilya-fedin** [comment]
Can you make a screenshot of https://t.me/DurgerKingBit?

**Comment by mrafieefard** [comment]
Sure
![image](https://github.com/user-attachments/assets/f2fa0c39-e4b3-49f6-8d4a-04c5ebae20a8)

**Comment by ilya-fedin** [comment]
What's your desktop environment and display scaling?

**Comment by mrafieefard** [comment]
I use kde and the resolution is 1680x1050 and scaling is 100%

**Comment by ilya-fedin** [comment]
don't you have the same in flatpak (or maybe even non-flatpak ones?) gtk applications?

**Comment by mrafieefard** [comment]
As write here yes I'm on flatpak

![image](https://github.com/user-attachments/assets/0cc90c0e-75bd-41f1-bd39-491b5257d71f)

**Comment by ilya-fedin** [comment]
Huh? That's not what I asked. I asked whether you have this problem in flatpak gtk applications, not whether you use the flatpak version.

**Comment by mrafieefard** [comment]
Excuse me my bad 
You mean Do I have this problem in other gtk apps?

**Comment by ilya-fedin** [comment]
> You mean Do I have this problem in other gtk apps?

Well, tdesktop is not a gtk app, that's why I haven't used the word "other". But yeah, that's what I ask. Preferably exactly flatpaked gtk apps.

**Comment by mrafieefard** [comment]
No it seems I don't have any problem related to this

**Comment by ilya-fedin** [comment]
I wonder how I can reproduce. Do you use Wayland or X11?

**Comment by mrafieefard** [comment]
I'm on Wayland If I'm not wrong

**Comment by ilya-fedin** [comment]
Provide the result of those commands:
```
gsettings get org.gnome.desktop.interface.font-name
gsettings get org.gnome.desktop.interface.text-scaling-factor
```

**Comment by mrafieefard** [comment]
``` ✘ mrafieefard@Mrafieefard  ~  gsettings get org.gnome.desktop.interface.font-name
Usage:
  gsettings [--schemadir SCHEMADIR] get SCHEMA[:PATH] KEY

Get the value of KEY

Arguments:
  SCHEMADIR A directory to search for additional schemas
  SCHEMA    The name of the schema
  PATH      The path, for relocatable schemas
  KEY       The key within the schema

```
seems not valid command

**Comment by ilya-fedin** [comment]
oops, fixed

**Comment by mrafieefard** [comment]
![image](https://github.com/user-attachments/assets/ea143f92-7448-4e2e-b6d8-ff6f4e74cb90)
But I think this can help you also

'Noto Sans,  10'
1.0

**Comment by ilya-fedin** [comment]
Looks typical. Weird.

**Comment by ilya-fedin** [comment]
Do you have xdg-desktop-portal and xdg-desktop-portal-gtk installed?

**Comment by mrafieefard** [comment]
Seems I didn't but now I install it

**Comment by mrafieefard** [comment]
Oh it fixed

**Comment by mrafieefard** [comment]
I just change font to Sans Serif
