### ISSUE TITLE
add ban date to banned by info like telegram x

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#28367]
### Is your feature request related to a problem?

a lot of times it's a problem to remember when you banned someone, telegram x shows this info

### Describe the solution you'd like

include ban date on banned by row 
https://t.me/tgbetachat/1958906

### Describe alternatives you've considered

none

**Comment by 23rd** [comment]
Feel free to check 5.5.2.

**Comment by Aokromes** [comment]
it's ok for the restricted without kick, but can't see totally banned ones (removed from group).

**Comment by Aokromes** [comment]
5.8.0 implements my desire.
https://t.me/tgbetachat/2000486
