### ISSUE TITLE
Increase the maximum session lifetime

### ISSUE THREAD

**Issue by TheTeslak** [telegramdesktop/tdesktop#28363]
### Is your feature request related to a problem?

Previously, it was tied to the account self-destruction period, which was extended to 24 months, but the session expiration remains at 12 months.

### Describe the solution you'd like

It would be helpful if the session self-destruction period could be extended to 24 months, matching the new account self-destruction period.

### Describe alternatives you've considered

No alternatives considered, as extending the session duration seems the most straightforward solution to align with the account self-destruction period.

**Comment by Aokromes** [comment]
https://i.imgur.com/u7oOEO6.png 5.5.1

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
(atm on android is the same)
