### ISSUE TITLE
Linking more URL schemes

### ISSUE THREAD

**Issue by Dietr1ch** [telegramdesktop/tdesktop#28364]
### Is your feature request related to a problem?

Protocols other than http/https are not linked, like ftp://user:password@host:port/path, steam://launch/730 or todo://new/task?=buyMilk

### Describe the solution you'd like

Support linking custom URL schemes is added, and text like `ftp://user:password@host:port/path` or `steam://launch/730` becomes a link on sent messages.

IANA has a [list of URL schemes](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml), but today many apps use their own custom ones.

### Describe alternatives you've considered

Not adding support, or using a whitelist. Having a whitelist might seem like a security feature at first, but if http:// links to fake and shady things are already allowed, then I don't think it's a real concern.

### Additional context

`ftp://` and `steam://` are not linked,
![image](https://github.com/user-attachments/assets/c94aa86a-3485-434e-bac4-17ecfe70ffc3)

Lists of URI schemes
- https://en.wikipedia.org/wiki/List_of_URI_schemes (lists popular ones)
- https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

**Comment by ilya-fedin** [comment]
Link detection is server side. Clients just respect entities

**Comment by Dietr1ch** [comment]
Thanks for triaging it.

I found this on the API side: https://bugs.telegram.org/c/41466
