### ISSUE TITLE
Invisible media viewer

### ISSUE THREAD

**Issue by Woundorf** [telegramdesktop/tdesktop#28374]
### Steps to reproduce

1. Open any chat where an image is present
2. Click on the image

### Expected behaviour

The image is shown possibly enlarged in a full screen "media viewer" window.

### Actual behaviour

A notification telling that "Media viewer is ready" is the only thing shown. From the desktop manager it can be discovered that an invisible or maybe size 0  window is actually present somewhere.

It's seems to be the same issue reported by other people previously with other versions (e.g. #27847, #27815, #27792, etc.). The issue is present with Wayland and Telegram 5.5.1. It works correctly with Telegram 5.5.1 and Xorg and also with Wayland and Telegram 5.4.1. I don't know if I can provide any other information that could be useful.

### Operating system

Fedora 39 with GNOME Shell 45.9, Wayland and an AMD GPU

### Version of Telegram Desktop

5.5.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This is a GNOME bug. You have to either upgrade your OS or ask your distro maintainers to backport https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3475.
