### ISSUE TITLE
cannot drag-and-drop network file to send as attachment

### ISSUE THREAD

**Issue by sarangtc** [telegramdesktop/tdesktop#28372]
### Steps to reproduce

1. Drag a file from my local network onto telegram desktop

### Expected behaviour

should give popup that says drop files here to send them as a document

### Actual behaviour

get an invalid drop icon

### Operating system

Windows 10 and 11

### Version of Telegram Desktop

5.5.1 and 5.5.1 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can you drag into other applications that are not standard Windows applications?

**Comment by sarangtc** [comment]
yes, can drag and drop from network to WhatsApp desktop application. 
This issue, has only recently started, I think in this update. Was working before

**Comment by walterzilla** [comment]
> This issue, has only recently started, I think in this update. Was working before

Noticed too, sadly...

**Comment by john-preston** [comment]
I think that's the reason:

https://github.com/telegramdesktop/tdesktop/commit/c3fda41224d859631d5d0135544ccada2615d6fe

I made that change because otherwise some links (like `file://[ip.address]/smth` copied from some software, like JetBrains IDEs) and pasted (as an URL-list mime type) was making an outbound network request to that address and lead to IP address leak. I wonder if this can be fixed for some network file URLs still working, but without possible IP address leak.

**Comment by ilya-fedin** [comment]
> I wonder if this can be fixed for some network file URLs still working, but without possible IP address leak.

You can't retrieve the file without revealing the IP address as you have to connect to download it, no? I guess if you don't want IP address leak then closing as wontfix is the only option.

**Comment by john-preston** [comment]
@ilya-fedin Maybe copy-paste / drag-n-drop of a file from File Explorer may be somehow told apart from copying an URL from a text editor 😢

**Comment by ilya-fedin** [comment]
> Maybe copy-paste / drag-n-drop of a file from File Explorer may be somehow told apart from copying an URL from a text editor

But it will still be an IP address leak, no?

**Comment by john-preston** [comment]
@ilya-fedin If you copy a file or drag-n-drop a file from a network drive I think it's ok that your IP may be revealed to this network drive when you request the file. But that's not very cool that you make an arbitrary URL query just when pasting it in the message field, that's not what you expect.

**Comment by walterzilla** [comment]
Just updated, feature seems restored.

**Comment by Aokromes** [comment]
and this is why we need slate bot xd because a lot of times bug fixes forgets to close issues.
