### ISSUE TITLE
Opening a dialog in a separate window

### ISSUE THREAD

**Issue by kochkareal** [telegramdesktop/tdesktop#28375]
### Is your feature request related to a problem?

Sometimes you need to have several dialogs open at once and be able to see them at the same time

### Describe the solution you'd like

I want that when the middle mouse button is clicked on a dialog with the user, it opens in a separate window

### Describe alternatives you've considered

Install multiple telegram apps

**Comment by ilya-fedin** [comment]
Right click -> Open in new window

**Comment by john-preston** [comment]
Or you can Ctrl+Click the chats in the chat list.
