### ISSUE TITLE
Bug Report: Incorrect Referral Link Display in Telegram Desktop

### ISSUE THREAD

**Issue by artem-astafyev** [telegramdesktop/tdesktop#28376]
### Steps to reproduce

1. Open Telegram Desktop.
2. Send a message containing a referral link with a query parameter (e.g., https://github.com/?ref=1).
3. Observe the generated preview card for the link below with incorrect ref parameter like https://github.com/?ref=10860 or https://github.com/.

### Expected behaviour

The preview card should display the same link as the one shared in the message, including the correct referral parameter.

### Actual behaviour

When sending a referral link with a query parameter (e.g., https://github.com/?ref=1) via Telegram Desktop, the preview card beneath the link displays an incorrect URL. For instance, instead of the original referral link, the card shows a different link such as https://github.com/ or https://github.com/?ref=10860. Notably, the correct link is displayed above the card, but the card itself displays a mismatched URL.

### Operating system

Windows 10

### Version of Telegram Desktop

5.5.1

### Installation source

Static binary from official website

**Comment by artem-astafyev** [comment]
Additional Notes:
1. Other query parameters like **sub** or other common parameters are not affected. The issue seems specific to the ref parameter.
2. The text of the link in the message itself remains correct; only the preview card is impacted.

**Comment by ilya-fedin** [comment]
link previews are server side

**Comment by john-preston** [comment]
I guess server attaches a web page preview without 'ref' parameters. I'm not sure if I have to override it somehow or not.

In case you attach several same links with different 'ref' parameters I'll have no way to understand which of them gave the no-'ref' link preview at all 🤔
