### ISSUE TITLE
More Instant view settings (like at mobile OS)

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#28378]
### Is your feature request related to a problem?

Cannot reduce text size. On older laptop text is too large.
![image](https://github.com/user-attachments/assets/d755603e-868f-42e9-938b-db5f646c6d77)

### Describe the solution you'd like

Text settings in three dots menu.

### Describe alternatives you've considered

Set minimal IV font size in Telegram settings (it's more tricky way).

**Comment by 23rd** [comment]
Please check the v5.6.3 with a new ability to zoom instant view windows.

**Comment by Twilightssuperb** [comment]
Yep, looks better. IDK, close issue or stay it idle till futher options (to customize font?) would be implemented.

**Comment by 23rd** [comment]
> But could you add 5% scale step instead of 10%?

Had added a few versions ago.

<details>

<img width="180" alt="image" src="https://github.com/user-attachments/assets/a6ce7ddd-2a93-4200-b8ec-9fe908c82b52">

</details>
