### ISSUE TITLE
add folders to forward like android and unigram

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#28373]
### Is your feature request related to a problem?

forward sometimes can be a pain if you have a lot of contacts with same name

### Describe the solution you'd like

add folder on side of forward https://i.imgur.com/cbMP1mP.png for faster finding.

### Describe alternatives you've considered

add folder on top (looks to small)

**Comment by 23rd** [comment]
I would appreciate if you would test the nightly build for a while, as the added features could potentially have a lot of bugs.
In addition to tabs in the `Forward to…` box and `Share to…` box, a folder type setting between vertical and horizontal views has also been added.

https://github.com/telegramdesktop/tdesktop/actions/runs/11730262274

**Comment by Aokromes** [comment]
i have tested a bit, i noticed one small lag at start but after that it worked fine

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/1ed34c6fa02fe8016bffe8e5bb80b19e487a3b88
