### ISSUE TITLE
Telegram Icon Change Request

### ISSUE THREAD

**Issue by V952** [telegramdesktop/tdesktop#2837]
Dear developers,
As one of really old Telegram users I'd love to see old tray/app icon back or at least have an option to choose between legacy and new icon, because in my honest opinion the old icon was way too better than new one.
Personally, I can patch the PE, but it's a tricky way and I'll have to do it after every update.

**Comment by john-preston** [comment]
@V952 In fact current icon IS the old one, which was changed at some moment to the new one, but it didn't go well, so it went back first on Android and then here as well. It was the one it is now for the whole time on the official https://telegram.org site and in iOS app. And now (as once before) there is a single Telegram icon for all platforms. I'm afraid we won't provide two different builds with the only difference of this icon, sorry.

**Comment by V952** [comment]
Yeah, that's completely understandable. Can you please link me "old" hi-res icon, so I can manually patch it?

**Comment by john-preston** [comment]
@V952 they're in the git, right here. That's the largest one:

https://github.com/telegramdesktop/tdesktop/blob/1045d628d620864fe22908515cfa5769c0bf3629/Telegram/Resources/art/icon512%402x.png

you can find other files in:

https://github.com/telegramdesktop/tdesktop/blob/1045d628d620864fe22908515cfa5769c0bf3629/Telegram/Resources/art
