### ISSUE TITLE
emojis do not work in Telegram Tasktop

### ISSUE THREAD

**Issue by mandoocash** [telegramdesktop/tdesktop#28385]
### Steps to reproduce

emojis do not work in Telegram Tasktop

### Expected behaviour

https://github.com/user-attachments/assets/120883b9-a34e-439c-b94d-e689094342b4
 version Windows 11 It's Telegram Premium

### Actual behaviour

emojis do not work in Telegram Tasktop  version Windows 11 It's Telegram Premium

### Operating system

 Windows 11

### Version of Telegram Desktop

5.5.2x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/28377
