### ISSUE TITLE
Premium emojis not working

### ISSUE THREAD

**Issue by fatheroftrap** [telegramdesktop/tdesktop#28382]
### Steps to reproduce

In no case does the premium emoji work, and it is not possible to send a premium emoji. Even after editing previous messages, the premium emoji gets removed.

### Expected behaviour

.

### Actual behaviour

.

### Operating system

Windows 10

### Version of Telegram Desktop

5.5.2 

### Installation source

Static binary from official website

**Comment by CarlosLopezES** [comment]
Same problem here with the last version, happening on MacOS and Windows 11.

**Comment by john-preston** [comment]
Thanks for your report. I'll going to deploy a fix version later today.

**Comment by Andrey-Popov-Inside** [comment]
Same problem. Premium emotions are sent as usual

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/28377

**Comment by Kickermax** [comment]
Same problem. Win 10

**Comment by ThePitFighter** [comment]
Same problem here
