### ISSUE TITLE
Bug: The chat list is not refreshed when the first message of a new chat is received.

### ISSUE THREAD

**Issue by wibabe** [telegramdesktop/tdesktop#28394]
### Steps to reproduce

When I saw that the channel was clicked and it appears posts.

### Expected behaviour

The chat list is not refreshed when the first message of a new chat is received. I tried the beta version too, it didn't help and the chat is not updated.

### Actual behaviour

The bug has already been known for a month, I hope it will be fixed.

### Operating system

Windows 11

### Version of Telegram Desktop

5.5.3 x64

### Installation source

Microsoft Store

### Crash ID

None

### Logs

```shell
None
```

**Comment by john-preston** [comment]
Please check 5.5.4 version, I fixed at least one issue with new messages in channels not appearing.

**Comment by wibabe** [comment]
The update was delivered, we'll test it for a day, then I'll tell you

**Comment by wibabe** [comment]
Nothing has changed, anyway, the same thing is not updated posts :/

**Comment by wibabe** [comment]
Everything seems to be fine!
