### ISSUE TITLE
Adjust Telegram Audio Volume by Scrolling on Taskbar Icon

### ISSUE THREAD

**Issue by Takhtdar** [telegramdesktop/tdesktop#28392]
### Is your feature request related to a problem?

Currently, scrolling on the Telegram Desktop icon in the Linux Mint taskbar does not change the volume of playing audio. I would like to request adding this feature, similar to how applications like Rhythmbox allow volume control by scrolling while the mouse is hovering over the app's icon in the taskbar. This would enhance usability for Telegram Desktop.

### Describe the solution you'd like

To implement this feature, Telegram Desktop could listen for scroll events when the mouse hovers over its taskbar icon. The scroll direction would correspond to increasing or decreasing the volume of any currently playing audio in the app. This could be achieved by linking scroll input to the internal audio volume control mechanism.

### Describe alternatives you've considered

Manual volume adjustment within the app: This is already possible, but it requires opening the app window and adjusting volume, which can be inconvenient.

Using system volume controls: While it’s possible to control system-wide volume, it doesn't always provide per-app volume adjustment, which this feature would enhance.

**Comment by ilya-fedin** [comment]
This is not implementable with toolkit tdesktop is written in. Use MPRIS volume control.
