### ISSUE TITLE
MacOS X menu on click UI bug

### ISSUE THREAD

**Issue by spam312sn** [telegramdesktop/tdesktop#2839]
### Steps to reproduce
1. Click with left mouse button or using two fingers with touchpad on any message

### Expected behaviour
Menu should be white with 2px radius round corners (as in official material design guide)

### Actual behaviour
Menu is bordered with black bold line

### Configuration
**Operating system:**
Mac OS X Lion
Version 10.7.5
Build 11G63
Graphics Intel GMA X3100

**Version of Telegram Desktop:**
Version: 1.0 (2017-01-11)

### Screenshot
![screen shot 2017-01-13 at 3 08 46 pm](https://cloud.githubusercontent.com/assets/17235291/21931322/857c98aa-d9a3-11e6-98f7-bf89c5b28e5b.png)

**Comment by luckydonald** [comment]
But Mac OS X `10.9.5` is called `Mavericks`, not `Lion`

**Comment by john-preston** [comment]
I can't reproduce that in OS X 10.9, works fine for me.

**Comment by luckydonald** [comment]
Me neither.

**Comment by spam312sn** [comment]
Sorry I made a mistake - version 10.7.5

**Comment by john-preston** [comment]
Indeed. That's very strange, thanks for your report.
