### ISSUE TITLE
Please tell me how to make a block with a button to copy the content

### ISSUE THREAD

**Issue by mandoocash** [telegramdesktop/tdesktop#28398]
### Is your feature request related to a problem?

![화면 캡처 2024-09-12 175152](https://github.com/user-attachments/assets/d123b59d-6b29-43d2-ac22-cd807bdb1bdd)
Please tell me how to make a block with a button to copy the content

### Describe the solution you'd like

Please tell me how to make a block with a button to copy the content

### Describe alternatives you've considered

Please tell me how to make a block with a button to copy the content

**Comment by ilya-fedin** [comment]
there's special button for questions
![](https://github.com/user-attachments/assets/72758eb4-cc79-4bef-9f3e-f6c402626608)
