### ISSUE TITLE
( ͡° ͜ʖ ͡°) doesn't render properly

### ISSUE THREAD

**Issue by JochemKuijpers** [telegramdesktop/tdesktop#284]
It renders like this:
![91cr6hi 1](https://cloud.githubusercontent.com/assets/1162720/5175388/5e9167dc-743a-11e4-89ce-7f7c6f3883b9.png)

Please fix, this is very important to me.

**Comment by noquierouser** [comment]
I can see that ( ͡° ͜ʖ ͡°) is now fixed, but ᕕ( ᐛ )ᕗ is still not rendered properly. Is there any other issue where I can report this situation and keep track of its evolution?

**Comment by auchri** [comment]
lol, what is this supposed to be? :smile: 

I don't think so, open a new one :)
