### ISSUE TITLE
Error When Integrating Telegram UI Component .

### ISSUE THREAD

**Issue by Tianzh3n** [telegramdesktop/tdesktop#28402]
### Steps to reproduce

Hello, I am trying to extract a component from Telegram, such as a button, and integrate it into my own project. I copied ui_utility.cpp and ui_utility.h into my project. Due to dependency issues, I also imported what seems to be platform-related files: lib_ui/platform/ui_platform_utility.h, lib_ui/platform/mac/ui_utility_mac.h, and ui_utility_mac.mm. Then, when I run the project, I get the following error:
<img width="519" alt="image" src="https://github.com/user-attachments/assets/471da704-eaee-4ca2-93a5-9c9dadefa9d7">
I look forward to your response and I am very grateful！！！

### Expected behaviour

just a question

### Actual behaviour

just a question

### Operating system

Mac  Apple M3 Pro

### Version of Telegram Desktop

new

### Installation source

Static binary from official website

### Crash ID

1

### Logs

```shell
ok
```

**Comment by ilya-fedin** [comment]
You have chosen the wrong thing whe creating issue. You have chosen "bug report" but this is not a bug report.

**Comment by Tianzh3n** [comment]
> You have chosen the wrong thing when creating issue. You have chosen "bug report" but this is not a bug report.

Where should I go for help, please?

**Comment by ilya-fedin** [comment]
There's "Question" choice when creating issue
