### ISSUE TITLE
Telegram in Ubuntu not showing images

### ISSUE THREAD

**Issue by LeandroFanzone** [telegramdesktop/tdesktop#28404]
### Steps to reproduce

1. Look for an image attached to a chat
2. Click on it

### Expected behaviour

A popup should appear with a bigger image 

### Actual behaviour

An invisible window is triggered but no image appears. I know there is an invisible window because the Ubuntu Desktop shows two dots in the window count for Telegram in the left vertical application bar, and because if you alt-tab you can see a black Telegram window among the current opened thumbnail windows, but you can't switch effectively to it. 

### Operating system

Ubuntu 24.04

### Version of Telegram Desktop

5.5.4 rev 6168

### Installation source

Snap

**Comment by ilya-fedin** [comment]
This means you haven't upgraded your system in some time and have a GNOME bug that was fixed in latest Ubuntu.

**Comment by LeandroFanzone** [comment]
I have Ubuntu 24.04 up-to-date, Telegram stopped working on the last update. No gnome updates are pending in my installation.

**Comment by ilya-fedin** [comment]
24.04.1?

**Comment by LeandroFanzone** [comment]
No, just 24.04. Should I upgrade to 24.04.1 in order for Telegram to work correctly? The operating system has only five months out!

**Comment by ilya-fedin** [comment]
It's the same operating system so I don't understand. You have to have latest update for your OS for it to work properly.

**Comment by LeandroFanzone** [comment]
Which gnome version should I be using? So I can check.

**Comment by ilya-fedin** [comment]
Any that doesn't have https://gitlab.gnome.org/GNOME/mutter/-/issues/3229

**Comment by LeandroFanzone** [comment]
Well, it seems upgrade to Ubuntu 24.04.1 is broken for some reason. I will wait for it to restore to a sane state, meanwhile I will check out about what gnome version is kosher, but all of this seems rather odd. What about someone using any previous Ubuntu version?

**Comment by ilya-fedin** [comment]
None of still supported Ubuntu versions with latest bugfix updates is affected.

**Comment by LeandroFanzone** [comment]
24.04 is supposed to be supported! The bugfix you mention was included in Gnome 46, which is the version I am using right now.

**Comment by ilya-fedin** [comment]
> 24.04 is supposed to be supported!

But you don't have latest bugfix updates for it.

> The bugfix you mention was included in Gnome 46, which is the version I am using right now.

It's not since first 46 version so you could use the version that doesn't have the fix. The only guarantee if only if you had all bugfix updates installed.

**Comment by LeandroFanzone** [comment]
In the logs of dpkg I have:

2024-08-16 15:23:16 configure gnome-shell:amd64 46.0-0ubuntu6~24.04.3 <none>

So my gnome version seems recent enough for a bug that was fixed four months ago. It must be something else.

**Comment by ilya-fedin** [comment]
The bug is not in gnome-shell, it's in mutter.

**Comment by LeandroFanzone** [comment]
According to [Ubuntu](https://launchpad.net/ubuntu/+source/mutter), I have the latest 46.0 version (installed in April), and there were no further updates. The only Ubuntu version that has a newer version is 24.04.1, with version 46.2, but it cannot be installed now because Ubuntu fucked up the upgrade a couple of days ago. So I assume no Ubuntu version besides Ubuntu 24.04.1 has this bugfix. How is Telegram working for all the rest? And why it stopped working only this week with the last Telegram updates?

**Comment by ilya-fedin** [comment]
> The only Ubuntu version that has a newer version is 24.04.1

I consider it the same version as patch update is just a bugfix update. If it was the other way around and you had a really supported version, then you had a way to request the bugfix to your version from Ubuntu.

> How is Telegram working for all the rest?

They don't disable installation of bugfix updates in Ubuntu?

> And why it stopped working only this week with the last Telegram updates?

The toolkit Telegram uses started to use the API that is bugged in old Ubuntu versions.

**Comment by LeandroFanzone** [comment]
Well, it seems the only way out is to update to Ubuntu 24.04.1 whenever that is possible again, bummer. Mutter 46.2 is from July 31, so at this point if there was a possibility of 24.04 to have it, it would have landed by now.

**Comment by ilya-fedin** [comment]
Maybe you have broke your sources.list? The update [is still on noble-updates](https://packages.ubuntu.com/noble-updates/mutter) and noble-updates exists out of the box.

**Comment by LeandroFanzone** [comment]
You were right, thank you. Ubuntu by default sets the server for updates to the server in the country you live in, so in this case it was not up to date. I switched to the main Ubuntu server and I got the last mutter release, which fixed the Telegram problem. Thank you again, and sorry for the noise.
