### ISSUE TITLE
Download file to Download Folder per Chat-Name

### ISSUE THREAD

**Issue by icariantk** [telegramdesktop/tdesktop#28400]
### Is your feature request related to a problem?

Current downloads are located in a single folder

### Describe the solution you'd like

Auto organizing all download by group or chat where the file was downloaded.

### Describe alternatives you've considered

Make a format defined by user, at least with macros to download to %date% sub folder for example   %chatname%/%date%  for sub folder clasification, %extension% or even %telegramId% etc.

### Additional context

This are the current options:

![image](https://github.com/user-attachments/assets/8dcbc4ec-328f-45de-8556-e10fd1785610)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5788
