### ISSUE TITLE
media viewer not show on ubuntu desktop

### ISSUE THREAD

**Issue by alirayaneh** [telegramdesktop/tdesktop#28401]
### Steps to reproduce

![Screenshot from 2024-09-13 09-39-26](https://github.com/user-attachments/assets/bde1f6f7-bd5f-4d39-a8ed-7567b68e95fb)
i use official telegram desktop on ubuntu . but recently after new update . i cant see any media . when click on any media its not show 

### Expected behaviour

when click on any media its not show 

### Actual behaviour

when click on any media its not show 

### Operating system

ubuntu 24

### Version of Telegram Desktop

5.5.4

### Installation source

Snap

**Comment by HoangFuc** [comment]
i have the same error. Hope to know the solution for this bug

**Comment by Alazar42** [comment]
i have the same error. Hope to know the solution for this bug, even from the official website i downloaded the tar.gz and also from snap but  the error persists
.

**Comment by igamid** [comment]
Having the same issue. Looks like a regression in v5.5.x b/c v5.4.x works as expected on both systems:
system 1
```
OS: Ubuntu 23.10 x86_64 
DE: GNOME 45.2 
Dual screen setup
``` 
system 2
```
OS: Ubuntu 24.04.1 LTS x86_64 
DE: GNOME 46.0
Single screen setup
```

**Comment by ilya-fedin** [comment]
Please upgrade your system. Latest 24.04.1 doesn't have such problem and 23.10 is no more supported so it doesn't receive bug fixes and must be upgaded.

**Comment by alirayaneh** [comment]
> Please upgrade your system. Latest 24.04.1 doesn't have such problem and 23.10 is no more supported so it doesn't receive bug fixes and must be upgaded.

But the problem still exists. And it is not resolved, why did you close the topic?
I am using the latest version of Ubuntu. 24.04
It is ridiculous that you suggest to change the operating system. Changing the operating system is sometimes a complicated and time-consuming process.
I have 2 monitors. Could that be the problem?

**Comment by ilya-fedin** [comment]
> I am using the latest version of Ubuntu. 24.04

I'm pretty sure you're not. A person on other thread had an outdated system despite claiming it's latest. Latest version of Ubuntu 24.04 would return 46.2 for `mutter--version` command. If it returns a different value then it's not latest (if the system clams it's latest anyway then updating mechanism of your installation is broken).

> It is ridiculous that you suggest to change the operating system. Changing the operating system is sometimes a complicated and time-consuming process.

I understand but what you propose? Do you want tdesktop project to fix the bug in your system component? If you would implement that then no problems.

**Comment by alirayaneh** [comment]
![Screenshot from 2024-09-14 00-52-08](https://github.com/user-attachments/assets/8805bb70-f3de-4f5e-8971-d712e76a53bd)
this is my system os details٫
Well, as it is clear, this is not my personal problem and many other people have this bug
In most projects, in such cases, a problem is found and a solution is created in the source of the project. Not to invite all people to change the operating system

**Comment by igamid** [comment]
+ v5.4.1 works fine on both 23.10 and 24.04, so it looks like regression issue.

**Comment by ilya-fedin** [comment]
> In most projects, in such cases, a problem is found and a solution is created in the source of the project.

That is complicated. The bug is in system component. Basically, the system says "don't draw" despite the window is visible. I don't see any solution here, only a workaround - ignoring what system says. But this leads to very increased CPU usage & battery drain. This was done for a half of the year but now that most users don't have a bugged system this workaround doesn't feel acceptable (draining battery for *EVERYONE* in the sake of multiple users who don't know how to update their systems).

**Comment by ilya-fedin** [comment]
> this is my system os details٫

Your system is not latest, sorry.

**Comment by linermgn** [comment]
the same issue

![image](https://github.com/user-attachments/assets/5eafc11c-1e99-406c-8d06-83d466ab4bfb)

**Comment by ilya-fedin** [comment]
This means updates are broken on your system. Maybe something is wrong with sources.list.

**Comment by linermgn** [comment]
> This means updates are broken on your system. Maybe something is wrong with sources.list.

https://askubuntu.com/questions/1525948/how-to-upgrade-to-24-04-1

maybe not my updates were broken

> Upgrades to 24.04.1 from older releases are currently blocked due to a critical bug discovered during initial rollout and enabling of upgrades.

**Comment by ilya-fedin** [comment]
the link is about updating from *other* releases. You're already using 24.04.

**Comment by acosonic** [comment]
24.04.1 was removed ... due to upgrade issues... How about letting us choose default viewer for media?

**Comment by ilya-fedin** [comment]
I see the mutter version is still 46.2 on the repos: https://packages.ubuntu.com/noble-updates/mutter

**Comment by acosonic** [comment]
Yes, but that's 24.04.1 to which we can't upgrade... 

I know that's not your problem, though... 

I can't even edit .desktop file it gets overwritten if I add 
`env QT_QPA_PLATFORM=xcb ./Telegram`

next time I launch there's no env var anymore..

![image](https://github.com/user-attachments/assets/b3e5991c-2e92-45c1-8076-37deee1a3e22)

**Comment by acosonic** [comment]
> > Yes, but that's 24.04.1 to which we can't upgrade...
> 
> There's perhaps misunderstanding. Canonical couldn't disable 24.04 -> 24.04.1 upgrades technically because it's the same version (noble) and updates happen through the same repo (noble-updates), you don't need to run `do-release-upgrade`. What they disabled are 22.04 -> 24.04 upgrades. The only reasons you can't get 24.04.1 are 1) you broke your sources.list somehow (maybe by launching some script you don't even know) and 2) your mirrors are very slow to update.

Not broken...

[https://discourse.ubuntu.com/t/noble-numbat-24-04-1-lts-point-release-status-tracking/46972](https://discourse.ubuntu.com/t/noble-numbat-24-04-1-lts-point-release-status-tracking/46972)

Temporarily suspended...

**Comment by Aokromes** [comment]
> > > Yes, but that's 24.04.1 to which we can't upgrade...
> > 
> > 
> > There's perhaps misunderstanding. Canonical couldn't disable 24.04 -> 24.04.1 upgrades technically because it's the same version (noble) and updates happen through the same repo (noble-updates), you don't need to run `do-release-upgrade`. What they disabled are 22.04 -> 24.04 upgrades. The only reasons you can't get 24.04.1 are 1) you broke your sources.list somehow (maybe by launching some script you don't even know) and 2) your mirrors are very slow to update.
> 
> Not broken...
> 
> [discourse.ubuntu.com/t/noble-numbat-24-04-1-lts-point-release-status-tracking/46972](https://discourse.ubuntu.com/t/noble-numbat-24-04-1-lts-point-release-status-tracking/46972)
> 
> Temporarily suspended...

Therefore, **updates to Noble** have been temporarily suspended while the issue is being addressed.

**Comment by ilya-fedin** [comment]
> Not broken...
> 
> https://discourse.ubuntu.com/t/noble-numbat-24-04-1-lts-point-release-status-tracking/46972
> 
> Temporarily suspended...

Sorry but you're wrong. The link says about 22.04 -> 24.04 updates, not 24.04 -> 24.04.1, just like I explained. As long as packages.ubuntu.com says that the 24.04.1 versions of packages are on noble-updates repo, they couldn't be suspended. If you can't update, your system is broken.

**Comment by acosonic** [comment]
Eventualy I was able to upgrade, but when I specifically enabled "development upgrades", after that, system upgraded to 24.04.1 and mutter is 46.2 I can confirm that media viewer works with 46.2 so my system is/was not broken... 

![image](https://github.com/user-attachments/assets/271795a8-5fff-4753-a8fe-5fea9339f6a6)

**Comment by linermgn** [comment]
> This means updates are broken on your system. Maybe something is wrong with sources.list.

Thank you, you were right

I fixed my `sources.list` as mentioned [here](https://www.veeble.org/kb/sources-list-file-urls-ubuntu/) and a lot of updates were comming. The problem is gone.

**Comment by ilya-fedin** [comment]
> Eventualy I was able to upgrade, but when I specifically enabled "development upgrades", after that, system upgraded to 24.04.1 and mutter is 46.2 I can confirm that media viewer works with 46.2 so my system is/was not broken...

That shouldn't really be needed as 46.2 is on noble-updates. Perhaps your sources.list is broken so that it's missing noble-updates and updates are coming only from noble-proposed.

**Comment by saadazghour** [comment]
`QT_QPA_PLATFORM=xcb ./Telegram`

**Comment by alimo2** [comment]
> `QT_QPA_PLATFORM=xcb ./Telegram`

I'm Fedora 39 and telegram 5.6.1. My media viewer stay minimized. this works for me. tnx
