### ISSUE TITLE
IntegrationInstance Exception When Running Telegram Button Component

### ISSUE THREAD

**Issue by Tianzh3n** [telegramdesktop/tdesktop#28403]
### Steps to reproduce

Hello, I would like to try running the Telegram button component separately in a Twidget. So, I wrote the following code in the main function:
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/a09a6c57-0815-4977-a51e-a41112b93e58">
Here is the result of the execution:
<img width="156" alt="image" src="https://github.com/user-attachments/assets/7ccdcf18-12e3-408d-bd7a-697e51a9a1c5">
I noticed that there is no button shape at all, just a bar-like object.
When my mouse pointer touches this bar-like object, the program crashes with a null pointer exception. The IDE indicates that the exception is occurring at this point: IntegrationInstance.
<img width="411" alt="image" src="https://github.com/user-attachments/assets/b0ca5ed4-b73c-432a-ae1f-1f32c8f401dd">
<img width="348" alt="image" src="https://github.com/user-attachments/assets/ebc401e3-3327-4688-8954-a564462de52d">
May I ask what causes this?
Looking forward to your reply, I appreciate it very much！！！！！！！！！！！

### Expected behaviour

thank you

### Actual behaviour

thank you

### Operating system

MAC os.       M3

### Version of Telegram Desktop

new

### Installation source

Static binary from official website

### Crash ID

thank you

### Logs

```shell
thank youthank youthank youthank youthank you!
```

**Comment by Tianzh3n** [comment]
> not a bug.

Where should I go for help, please?

**Comment by john-preston** [comment]
The UI components are not really meant to be used outside of TDesktop. Or, in other words, you need to perform _a_lot_ of work for the widget system to start working in another application.

The fairly minimum example can be found in a ui-test-application wrap:

https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/tests/test_main.cpp

**Comment by Tianzh3n** [comment]
Thanks for your answer.

> The UI components are not really meant to be used outside of TDesktop. Or, in other words, you need to perform _a_lot_ of work for the widget system to start working in another application.
> 
> The fairly minimum example can be found in a ui-test-application wrap:
> 
> https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/tests/test_main.cpp

**Comment by Tianzh3n** [comment]
> The UI components are not really meant to be used outside of TDesktop. Or, in other words, you need to perform _a_lot_ of work for the widget system to start working in another application.
> 
> The fairly minimum example can be found in a ui-test-application wrap:
> 
> https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/tests/test_main.cpp

May I ask what the main purpose of Integration is? For example, in Telegram, what are BaseIntegration and UiIntegration used for? Is there a necessary connection between them and the functioning of the animations in Telegram's components?

**Comment by john-preston** [comment]
Well, this is the way to provide some required code from the client app back to the library level again.
