### ISSUE TITLE
Smooth scrolling doesn't works on Linux

### ISSUE THREAD

**Issue by steazzy** [telegramdesktop/tdesktop#28408]
### Steps to reproduce

1. Try to scroll with trackpad in any chat.
2. It doesn't smooth scroll

### Expected behaviour

Smooth scrolling like on Windows

### Actual behaviour

It scrolls sharply like on mouse 

### Operating system

Fedora Linux 40, KDE 6.1.4, Wayland

### Version of Telegram Desktop

5.5.5

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
#6746?

**Comment by TogarUshindi** [comment]
Having the same issue. Mouse's scroll wheel function seems to catch about half of scrolling attempts, intermittently. Sometimes several attempts to make one scroll. Happens through browsing images or chats. Every other app scrolls just fine, so this is localized to the Telegram desktop application.

I'm using a Logitech mouse, which can either scroll freely or clicky. When I put it into free-scroll mode, I spin the wheel and it scrolls very jerkily, not smooth like normal. This seems to have started on the most recent update.

I'm on Ubuntu 24. Telegram 5.6.1

**Comment by ilya-fedin** [comment]
@TogarUshindi are you sure you have the same issue? smooth scroll is a feature that that creates animation o scrolling and it's just no present (that's what the linked feature request about). What you explain sounds just like buggy scrolling and thus not at all the same.

**Comment by TogarUshindi** [comment]
Yep. It went away with the update.
