### ISSUE TITLE
Right clicking the tray icon context menu does nothing with display scaling >100%

### ISSUE THREAD

**Issue by Simon1511** [telegramdesktop/tdesktop#28409]
### Steps to reproduce

1. Install Telegram Desktop on Windows 11
2. Set your display scale in Windows Settings to anything above 100% (for example, I use 175% on my 4k monitor)
3. Right click the Telegram Desktop taskbar tray icon to open the context menu

### Expected behaviour

The context menu should appear as normal when right clicking it (for example when I want to use the "Quit Telegram" button in it).

### Actual behaviour

Nothing happens when the display scale is >100%, i.e. the context menu does not appear at all. Setting it back to 100% makes the context menu appear again.

### Operating system

Windows 11 23H2 22631.3447 x86-64

### Version of Telegram Desktop

5.5.5 x64 (also happens with older releases)

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
cant reproduce with 125% scaling on windows 11 23h2 and intel gfx.

**Comment by Simon1511** [comment]
I was able to reproduce it on two devices with AMD GPUs, 1x RX 6900 XT and 1x with the integrated Radeon 780M in my notebook.

**Comment by john-preston** [comment]
@Simon1511 I couldn't reproduce, I tried both 175% scale and 250% scale.
