### ISSUE TITLE
telegram miniapp share option behavior

### ISSUE THREAD

**Issue by OptimusFaber** [telegramdesktop/tdesktop#28412]
### Steps to reproduce

I'm making a telegram bot and I faced 1 small problem (for me it's actually big)
In telegram I can either share my post (I select users who I want to share with) or forward (I select only one user who I want share with and I automatically jumping in chat with that user)
I'm making a bot with mini-app in which by pushing the button you switch to forward option - it works well for android and windows, but however on IOS opens the share window:
```
const telegramShareUrl = `https://t.me/share/url?url=${encodeURIComponent(postUrl)}`;
Telegram.WebApp.openTelegramLink(telegramShareUrl);
```
I would be very happy if anyone will have suggestions here
Thx!

P.s. my full code is at https://github.com/OptimusFaber/Telegram_webapp/tree/main (You have to insert TOKEN of your bot in .env to start the script)

### Expected behaviour

I expected that 
```
const telegramShareUrl = `https://t.me/share/url?url=${encodeURIComponent(postUrl)}`;
Telegram.WebApp.openTelegramLink(telegramShareUrl);
```
will let me forward the massages both on android and ios

### Actual behaviour

On Android and Windows it works for forward
On IOS and Linux it works for share

### Operating system

IOS

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This bugtracker is for Windows, not iOS
