### ISSUE TITLE
The answer gesture is reflected when natural scrolling is on

### ISSUE THREAD

**Issue by alba4k** [telegramdesktop/tdesktop#28414]
### Steps to reproduce

Simply trying to use the 1:1 gesture to answer to a message will have the direction the message moves in inverted

### Expected behaviour

The message should follow the movement of the fingers (just like it works fine in firefox)

### Actual behaviour

The direction is opposite

### Operating system

Arch Linux, Hyprland

### Version of Telegram Desktop

5.5.5

### Installation source

Other (unofficial) source

### Logs

https://github.com/user-attachments/assets/9aa76cc2-04e5-4c56-bf43-3a749a5e50bb

**Comment by ilya-fedin** [comment]
tdesktop does check [QWheelEvent::inverted](https://doc.qt.io/qt-6/qwheelevent.html#inverted) property and reacts accordingly. That's all it can do. If it doesn't work for you, you have a bug somewhere on system level.

**Comment by alba4k** [comment]
@ilya-fedin apparently that spec just doesn't work under wayland? maybe just in kde?

https://github.com/hyprwm/Hyprland/issues/7836#issuecomment-2359008326

Can't this be forced using a toggle?

**Comment by ilya-fedin** [comment]
> apparently that spec just doesn't work under wayland? maybe just in kde?

Maybe? That doesn't mean other compositors can't implement the same.

> https://github.com/hyprwm/Hyprland/issues/7836#issuecomment-2359008326

I heard the inverted property is implemented for the Wayland QPA backend. The X11 QPA backend indeed doesn't have support for this. I think hyprland developer can see how to integate with Qt by looking at qtwayland source code.

> why can't this be forced using a toggle?

The policy is to have as less settings as possible. That's really something that the system should provide via some API. And that's not a problem for 99% of the users (Linux is only 1% of tdesktop userbase).

**Comment by ilya-fedin** [comment]
This seem to look like wayland is pretty aware of natural scrolling?
https://gitlab.freedesktop.org/wayland/wayland/-/blob/main/protocol/wayland.xml#L2385

**Comment by alba4k** [comment]
> And that's not a problem for 99% of the users (Linux is only 1% of tdesktop userbase).

Such a toggle would also be relevant for just 1% of users, wouldn't have to be visible otherwise
