### ISSUE TITLE
Opening topics options triggers dock attention on Gnome

### ISSUE THREAD

**Issue by BANOnotIT** [telegramdesktop/tdesktop#28417]
### Steps to reproduce

1. Go to group with topics
2. Click kebab menu above topics list

### Expected behaviour

Menu is opened

### Actual behaviour

Menu is opened but also telegram triggers "attention" mode in the dock.

[tgd notice tripping.webm](https://github.com/user-attachments/assets/e68a0c82-a4ad-4ccf-82b6-ba89b8106aa9)

### Operating system

Fedora 39, GNOME 45.9, Wayland

### Version of Telegram Desktop

5.5.4

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
not a telegram bug

**Comment by BANOnotIT** [comment]
@ilya-fedin but what's causing this bug? Which project should I report it to? Nothing else causes this stuff.

**Comment by ilya-fedin** [comment]
i guess gnome is incompatible with qt again?

**Comment by john-preston** [comment]
Is regular context menu (on chats list, for example) cause the same?

**Comment by BANOnotIT** [comment]
This one does not cause the problem:
- Chat context menu in chats list caused by mouse right click (Open in new window, Archive, Pin, ...)

Do cause the problem, on the contrary:
- Chat list context **sub**menu on mouse hover and keyboard navigation (Mute notifications > Select tone)
- kebab in topics list (Create topic, view group info, ...)
- Topic info kebab (View topic info, Edit topic, ...)
- Group kebab (Mute notifications, View profile, ...)
- Settings kebab between QR button and Close modal button (Add account, Edit profile, Log out)

**Comment by john-preston** [comment]
well.. no idea what causes it honestly, for me all the popup menus are done the same way

**Comment by ilya-fedin** [comment]
I bet it's the typical disagreement between Qt and GNOME on how focus has to be done. Wouldn't be surprised if that's intended behaviour actually.
