### ISSUE TITLE
Telegram Desktop for Linux hangs

### ISSUE THREAD

**Issue by vporton** [telegramdesktop/tdesktop#28427]
### Steps to reproduce

It hangs at this stage (Ubuntu Linux snap):

![Screenshot from 2024-09-18 15-22-20](https://github.com/user-attachments/assets/97503a7f-47f2-436c-a3e0-3a81cbb57aa7)

### Expected behaviour

Show interface.

### Actual behaviour

It hangs.

### Operating system

Ubuntu Linux 24.04.1

### Version of Telegram Desktop

5.5.4

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Can't reproduce

**Comment by frankhuurman** [comment]
I'm using the telegram-desktop snap (5.5.4, revision 6168) on Ubuntu 24.04.1 as well and it's working fine for me, can't reproduce it either.

Perhaps it would help to know the specs of your PC? or maybe you didn't have a proper internet connection at the time?

**Comment by vporton** [comment]
It works now. Maybe, I really forgot to set Internet on.
