### ISSUE TITLE
Telegram media viewer is not working.

### ISSUE THREAD

**Issue by alisherabdimuminov** [telegramdesktop/tdesktop#28421]
### Steps to reproduce

1. When open images, gifs or videos media viewer opened but not launched, it seems like transparent.

### Expected behaviour

When open images, gifs or videos media viewer opened but not launched, it seems like transparent.

### Actual behaviour

please fix it

### Operating system

Ubuntu 23.04

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
duplicate. 3rd party os issue

**Comment by acosonic** [comment]
Ubuntu 24.04 also doesn't work...
