### ISSUE TITLE
> File upload fails

### ISSUE THREAD

**Issue by sequencerr** [telegramdesktop/tdesktop#28428]
> File upload fails

Maybe you're trying to drag'n'drop a file outside your home directory? Snap sandbox prevents such attempts.

_Originally posted by @ilya-fedin in https://github.com/telegramdesktop/tdesktop/issues/8847#issuecomment-711388519_
            
I'm trying to drag&drop/copy&paste from thunar ~/.ssh to telegram installed via snap and it fails. Clicking attachments button in chat works.

**Comment by ilya-fedin** [comment]
You can't do that, snap sandbox prevents copying from directories starting with a dot

**Comment by sequencerr** [comment]
Oh. Ok. Thanks anyway!
