### ISSUE TITLE
Random crashed under KDE (Fedora & openSUSE)

### ISSUE THREAD

**Issue by ezhan** [telegramdesktop/tdesktop#28426]
### Steps to reproduce

Using Linux (Fedora 40, openSUSE Tumbleweed, both with KDE) time to time for a half a year. And always see Telegram just closing and having to restart it.

1. Use Telegram
2. At some moment it just closes
3. No crash dialog whatsoever
4. Have to restart manually

I do not see this setting in Telegram's settings:
"You have to enable beta versions installation in Settings -> Advanced for the reporter to appear."

### Expected behaviour

It continue working as usual

### Actual behaviour

At some moment it just closes

### Operating system

Linux

### Version of Telegram Desktop

5.5.5

### Installation source

Flatpak

**Comment by ezhan** [comment]
Installed the given flatpak. Run the 
flatpak-coredumpctl org.telegram.desktop

Got:
```
$ flatpak-coredumpctl org.telegram.desktop

The program 'flatpak-coredumpctl' can be found in the following package:
  * flatpak-devel [ path: /usr/bin/flatpak-coredumpctl, repository: repo-oss ]

Try installing with:
    sudo zypper install flatpak-devel
```
Installed this as well. And run:
```
$ flatpak-coredumpctl org.telegram.desktop
Traceback (most recent call last):
  File "/usr/bin/flatpak-coredumpctl", line 83, in <module>
    coredumper.run()
  File "/usr/bin/flatpak-coredumpctl", line 44, in run
    subprocess.check_call(["coredumpctl", "dump"] + shlex.split(self.coredumpctl_matches),
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['coredumpctl', 'dump']' returned non-zero exit status 1.
```
Now I have to wait for the crash and then `$ flatpak-coredumpctl org.telegram.desktop` should give some useful data? 
How should I put here? I'm not a programmer...

**Comment by ilya-fedin** [comment]
> Now I have to wait for the crash and then `$ flatpak-coredumpctl org.telegram.desktop` should give some useful data?

I'm not sure

> How should I put here? I'm not a programmer...

I recommend to just throw out flatpak and use the static binary with automatic crash reporting feature in that case.

**Comment by ezhan** [comment]
Всё оказалось напрасно... :)

OK, installed Telegram 5.4.1 from Tumbleweed repo via KDE Discover. 
But I still do not see any "enable beta versions installation in Settings -> Advanced for the reporter to appear."

**Comment by ilya-fedin** [comment]
> OK, installed Telegram 5.4.1 from Tumbleweed repo via KDE Discover.

I told to install the static binary (which is distributed on dekstop.telegram.org), not from some repo...

**Comment by ezhan** [comment]
OK, installed. Found the beta toggle. Now waiting for crash.

**Comment by ezhan** [comment]
Seems that the build from desktop.telegram.org works fine, no crashes for many days. The problem is with the flatpak version, that unexpected closes...

**Comment by ilya-fedin** [comment]
Well, so either just use the binary or get a backtrace from the flatpak version somehow. Sadly I can't help you with the error you got for `flatpak-coredumpctl` so you have to resolve it on your own first.
