### ISSUE TITLE
WebM support

### ISSUE THREAD

**Issue by flipflop97** [telegramdesktop/tdesktop#2842]
### Steps to reproduce
1. Send an mp4 (or other native supported) video and a webm video
2. compare the results

### Expected behaviour
The webm should be recognised and displayed as a video instead of a file

### Actual behaviour
This happens:
The top one shows an mp4 file and the bottom a webm.
![image](https://cloud.githubusercontent.com/assets/13943260/21934932/ac818480-d9ab-11e6-802d-1bad6678e765.png)

### Configuration
**Operating system:**
Arch Linux with Gnome
**Version of Telegram Desktop:**
1.0

### Logs
Not needed

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by andersbateva** [comment]
Related: #1106

**Comment by stek29** [comment]
1) API issue, WebM isn't supported by server
2) #1106 duplicate, Sending as Video isn't supported by app

**Comment by dogancelik** [comment]
Can you support WebM? (it is a common format)

**Comment by dogancelik** [comment]
Can you support WebM? (it is a common format) @john-preston

**Comment by stek29** [comment]
@dogancelik Support means having in-app player for it?

**Comment by dogancelik** [comment]
@stek29 Yes, thumbnails and player

**Comment by stek29** [comment]
@dogancelik Thumbnails are generated on server side, so it would have to download the file to generate thumbnail for it.
Speaking about player -- I've never seen any app which handles WebM good and isn't a player.
I hate that Chrome plays it and I always copy address from it and paste it to VLC. I'm glad TDesktop isn't trying to play webms.

Also, adding built-in player for videos haven't required much changes and additional stuff -- everything was in there for GIFs. WebM is completely different.

Also, I'd not say that WebM is "a common format" for all of Telegram users, but we can't check that.

And lastly -- you can try to make a PR, good luck with that :D

**Comment by bam80** [comment]
What about WebM audio at least?

**Comment by gtirloni** [comment]
Just found this issue after some relatives couldn't understand what the .webm file I shared was about. They're used to WhatsApp showing a thumbnail at least so it'd help if Telegram could do the same and make converting users easier.

**Comment by dajbelshaw** [comment]
Some screen-capture apps (e.g. Awesome Screenshot) only allow you to download in .webm so having to transcode to MP4 to share with a colleague in Telegram seems... sub-optimal. Would love to see an embedded player for .webm files!

**Comment by RadCatGirl** [comment]
Ну когда же появится возможность просмотра webm?
