### ISSUE TITLE
Unable to open story.

### ISSUE THREAD

**Issue by tuxmaster5000** [telegramdesktop/tdesktop#28432]
### Steps to reproduce

1. click on an story

### Expected behaviour

The the story will opens

### Actual behaviour

Nothing happens on click

### Operating system

Fedora 39 (X11)

### Version of Telegram Desktop

5.5.6beta

### Installation source

Static binary from official website

### Logs

```shell
No error gets logged.
```

**Comment by ilya-fedin** [comment]
Can't reproduce

**Comment by tuxmaster5000** [comment]
5.5.5 will works.

**Comment by ilya-fedin** [comment]
Works on both 5.5.5 and 5.5.6

**Comment by clsv** [comment]
Version 5.5.6 beta, same issue, media view doesn't work at all.

**Comment by ilya-fedin** [comment]
@clsv if you use Wayland, this is a GNOME bug and you have to update to Fedora 36 or ask your distro maintainer to backport the fix.

**Comment by clsv** [comment]
@ilya-fedin Sorry, I forgot to mention that I'm using X11 with XFCE4. Before the upgrade, everything was working fine.

**Comment by ilya-fedin** [comment]
Then I can't reproduce :man_shrugging:

**Comment by clsv** [comment]
I've disabled the OpenGL rendering option for media, and now the media view works fine.

**Comment by tuxmaster5000** [comment]
> I've disabled the option - OpenGL rendering for media, and now the media view works fine.

Thanks, this was the problem. Disabled -> all ok. Enabled -> unable to open the story's.
