### ISSUE TITLE
Premium cannot be purchased

### ISSUE THREAD

**Issue by michal-volf** [telegramdesktop/tdesktop#28437]
### Steps to reproduce

- Write /start to @PremiumBot
- fill details
- confirm Visa Secure

My credit card is using Visa Secure, which requires my bank app to confirm the transaction, after confirming, i'm getting Transaction failed.

### Expected behaviour

Premium purchased

### Actual behaviour

Transaction failed

### Operating system

Windows 11

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

### Logs

```shell
[11:14:54.002 01-0002265] (dc:4_main) Recv: { core_message
  msg_id: 7416651303124011009 [LONG],
  seq_no: 131 [INT],
  bytes: 184 [INT],
  body: { rpc_result
    req_msg_id: 7416651283273345732 [LONG],
    result: { payments_paymentVerificationNeeded
      url: "https://tgpb.smart-glocal.com/redirect/form?u=aHR0cHM6Ly9hcGkuY2hlY2tvdXQuY29tL3Nlc3Npb25zLWludGVyY2VwdG9yL3NpZF96Znc1amZvYm43cnVwZW5lcXg1cjd3dzJoNA==&p=W10=&m=R0VU" [STRING],
    },
  },
} (dc:4,key:824062725026870401)
```

**Comment by pfeux** [comment]
I face the same issue in Telegram Android (non playstore version) that I cannot buy premium

**Comment by Aokromes** [comment]
then it doesn't belongs here,

**Comment by michal-volf** [comment]
i got the error and the log from desktop version

**Comment by Aokromes** [comment]
> i got the error and the log from desktop version and tried it again, and still getting the error

try on direct android, if it fails there it's not telegram desktop bug.

**Comment by michal-volf** [comment]
i understand, thank you, same error on FOSS version
