### ISSUE TITLE
Weird behaviour Telegram App indicator on Ubuntu 24.04.1

### ISSUE THREAD

**Issue by frankhuurman** [telegramdesktop/tdesktop#28439]
### Steps to reproduce

I'm using version 5.5.4(rev 6168) of the telegram-desktop snap and since upgrading from Ubuntu 22.04.4 to 24.04.1 I've noticed weird new behaviour when clicking the Telegram app indicator in the top bar.
![image](https://github.com/user-attachments/assets/6070acfb-15a5-4f75-8c32-a278d25a8e98)

Left clicking has quite the delay before the dropdown menu opens, but right clicking opens it almost instantly.

I can't really record it on my screen cause I don't know how to visually show when I actually click the mouse and how long the delay is but it's a noticeable one for sure.

Other app indicator apps like Steam or Spotify don't have this delay so it seems to me it's a Telegram Desktop & Ubuntu 24.04+ combination that causes it.

Would love to know if anyone can reproduce it.

### Expected behaviour

I expected left-clicking the Telegram-Desktop app indicator to open the dropdown as fast as right-clicking it(like it did on Ubuntu 22.04.4).

### Actual behaviour

There is a +- 1,5 second delay when I left-click the Telegram-Desktop app indicator.

### Operating system

Ubuntu 24.04.1 with Gnome Shell 46.0

### Version of Telegram Desktop

5.5.4

### Installation source

Snap

**Comment by ilya-fedin** [comment]
This menu is presented by your system, not tdesktop. tdesktop has no control over its speed.
