### ISSUE TITLE
Minimize chat's list panel, before hide it.

### ISSUE THREAD

**Issue by seniorivn** [telegramdesktop/tdesktop#2843]
### Steps to reproduce
1. fullscreen app on wide screen, it will have chat's list on the left 
2. make the width less (about 1/3 of the previous), it will become smartphone behavior, the list of chat's, or chat

### Expected behaviour
The idea is to add intermediate state, when there is no place for full chat's list, but still enough for just icons of chat's, 
this could be added as an optional feature, or even standard behavior. 
![telegram_concept_small](https://cloud.githubusercontent.com/assets/5340859/21936180/adf25baa-d9c9-11e6-944d-9f9d5298e823.png)

### Configuration
**Operating system:** Linux  4.9.0-1-MANJARO  x86_64

**Version of Telegram Desktop:**
1.0..0-1

**Comment by john-preston** [comment]
@seniorivn But then it won't have search in chats list, at all.. :(

**Comment by seniorivn** [comment]
@john-preston it's just undiscussed part of issue, i think i that minimized mode button that on my concept is menu button, should be button that brings full list and search back, full sized and if you using shortcut to search, it will appear as well.

**Comment by seniorivn** [comment]
@john-preston and what do you think about idea? Am i only one who thinks it is useful?

**Comment by Aokromes** [comment]
#314

**Comment by gudvinr** [comment]
@auchri This is not resolved although alpha got resize feature.
Chat window still too wide when it hides CL completely.
I think it's better to keep minimized panel with disabled resizing to some threshold instead of hiding. And hide only when window becomes really tight.
