### ISSUE TITLE
Custom font for UI / chat content (esp. CJK)

### ISSUE THREAD

**Issue by q1zhen** [telegramdesktop/tdesktop#28435]
### Is your feature request related to a problem?

It seems that Telegram currently only set a font for latin characters.
Sometimes Chinese characters, on some devices, will fall back using Japanese fonts, and since CJK shares Unicode codepoints, many characters do not display as I would expect in the variant.
It's even worse that Japanese fonts do not cover all Chinese characters in daily usages, and the messages would end up using mixed fonts (and therefore mixed variants), probably because that Chinese fonts are the fallback after Japanese fonts by default.
I believe this would also happen for other languages in CJK.

### Describe the solution you'd like

Provide a custom font selection option, preferably something similar to css's `font-family` that allows multiple fonts, or just a single font selector.

### Describe alternatives you've considered

Provide a CJK variant selection (SC / TC / Japanese / Korean) or some Asian-font-specified settings.

**Comment by ilya-fedin** [comment]
> It seems that Telegram currently only set a font for latin characters.

No, that's a wrong assumption, it just sets the preferred font via Qt's QFont::setFamily API. Qt doesn't allow to set per-language fonts.

Thus, I would say your request is already implemented.

**Comment by Aokromes** [comment]
already exist.

**Comment by q1zhen** [comment]
I apologize for any misunderstandings. What I am proposing is a field in the app settings so that users can use the fonts they prefer to use by themselves for chat contents (or if possible, all UI components).

**Comment by q1zhen** [comment]
Where can I find this setting?

**Comment by ilya-fedin** [comment]
Settings -> Chat settings -> Font family
