### ISSUE TITLE
I will no longer use telegram, i was a telegram user since 2017, being a desktop user is treated like being a criminal, all my accounts have been banned

### ISSUE THREAD

**Issue by mr-459** [telegramdesktop/tdesktop#28444]
### Is your feature request related to a problem?

Telegram is recently turning into what it promised to not be, completely unsafe, unreliable and no longer private platform

you have no reliability on telegram, your accounts can be banned without any reasoning or warning or declaration without violating any rule of the platform and they will never ever respond to any one's request to relive ban and recover account, i've lost a lot of my assets which were on telegram for this reason

as european countries are pressuring telegram to be a dick, it has turned into a complete dick, being a desktop user is now unofficial crime pubished by immidate ban from telegram(no western origined messsenger or social plaform has a desktop version)

i've been a user from 2017 and only 2 of my bussiness accounts which had premium status are surviving and i will stop to use it

### Describe the solution you'd like

dont ban people without any reason, or at least let them take out their resources from the platform

### Describe alternatives you've considered

Alternatives? the only alternative is to hang pavel durov /s

### Additional context

why post on github? because durov will order your immediate ban on reddit or any other platform if you say their being a dick, github programmers are more reasonible people than reddit's petty dictators(subreddit mods)

**Comment by Aokromes** [comment]
Sorry but this is telegram desktop bug tracker, nothing here belongs to user account administration.
