### ISSUE TITLE
Telegram Desktop on Linux hangs

### ISSUE THREAD

**Issue by vporton** [telegramdesktop/tdesktop#28443]
### Steps to reproduce

1. Start Telegram Desktop on Linux.
2. The list of groups is "Loading..." infinitely.

### Expected behaviour

See the list of groups.

### Actual behaviour

I was unable to send a message (displayed as "sending"/"not connected").
Then I unsuccessfully tried to exit from TG. After this I killed it by SIGTERM.
I restarted and see this "Loading...".

### Operating system

Ubuntu 24.04.1 LTS

### Version of Telegram Desktop

5.5.4

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Can't reproduce

**Comment by vporton** [comment]
I also can't connect on configuring it from scratch (tweaking IPv6 option does not help (I don't have IPv6)):
![image](https://github.com/user-attachments/assets/aa36d764-a9af-4e04-bb15-e5f80141ad25)

**Comment by vporton** [comment]
It seems, the problem is with `libgiolibproxy.so`:

```
$ strace telegram-desktop
...
futex(0x5cf063158ee0, FUTEX_WAIT_PRIVATE, 0, NULL) = ?
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/porton/snap/telegram-desktop/common/.cache/gio-modules/libgiolibproxy.so
[ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
```

```
$ ls -l /home/porton/snap/telegram-desktop/common/.cache/gio-modules/libgiolibproxy.so
lrwxrwxrwx 1 porton porton 82 Sep 15 12:59 /home/porton/snap/telegram-desktop/common/.cache/gio-modules/libgiolibproxy.so -> /snap/telegram-desktop/6168/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
$ ls -l /snap/telegram-desktop/6168/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
-rw-r--r-- 1 root root 18584 Mar 31 08:56 /snap/telegram-desktop/6168/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
```

**Comment by ilya-fedin** [comment]
This absolutely doesn't mean it's the cause.

**Comment by ilya-fedin** [comment]
Most likely the connection is just blocked by provider or firewall

**Comment by vporton** [comment]
> Most likely the connection is just blocked by provider or firewall

II checked on PC without a firewall. The PC is connected to phone WiFi hotspot and on the phone itself Telegram does work. So the problem is in Telegram Desktop, not provider.

**Comment by ilya-fedin** [comment]
I can't confirm :man_shrugging:

**Comment by vporton** [comment]
Restarting Telegram (using `pkill telegram-deskto`) didn't solve the problem.

But after Linux reboot, Telegram works.
