### ISSUE TITLE
Bug while downloading images got my phone number banned.

### ISSUE THREAD

**Issue by yataghan012** [telegramdesktop/tdesktop#28449]
### Steps to reproduce

1. Enter a group
2. Enter a topic
3. Download images
4. Scroll up and download about 30 images and videos one by one
5. Close telegram desktop to tray

### Expected behaviour

It should download the images.

### Actual behaviour

It freezed and shut down the program and got my phone number banned and can't log in anymore.

### Operating system

Manjaro OS. Linux LTS 6.6.47-1

### Version of Telegram Desktop

5.4.1-1

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
Sorry but this is telegram desktop bug tracker, nothing here belongs to user account administration. telegram doesn't bans persons because bulk image download.

**Comment by yataghan012** [comment]
> Sorry but this is telegram desktop bug tracker, nothing here belongs to user account administration. telegram doesn't bans persons because bulk image download.

I don't know the exact cause of why it was banned, I'm just describing what happened and I can assure you I was banned right after I was downloading those images, maybe it misinterpreted my actions with spam. 

Also, I should be getting my account back since it was very new and I wasn't doing anything weird whatsoever. I've had other accounts for years and I was never banned on those, this is the first time I'm being banned at all, and it happened bc of this bug. Support doesn't seem to sympathize with my issue, not even a response.
