### ISSUE TITLE
 [Feature Request] Managability of "forward to" list

### ISSUE THREAD

**Issue by TFBosoN** [telegramdesktop/tdesktop#28442]
### Is your feature request related to a problem?

I use telegram for many aspects of my life, such as work, scrolling content, etc..
I'm afraid of forwarding a meme to my work or an archived chat.
So I always have to double check myself and that interrupts the flow.

### Describe the solution you'd like

Tab folders (just like on a main window)

### Describe alternatives you've considered

An allow list of chats to forward to
Or all of them at the same time (like allow list for each folder)

### Additional context

A setting to disable forwarding to archived chats is probably needed too.

Related open issue: https://github.com/telegramdesktop/tdesktop/issues/28373

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/28373
