### ISSUE TITLE
ВЫЛЕТАЮТ АККИ - Я ЗАЕБАЛСЯ

### ISSUE THREAD

**Issue by pushinkateddy** [telegramdesktop/tdesktop#28445]
### Steps to reproduce

ПОЧЕМУ АККИ ВЫЛЕТАЮТ?

### Expected behaviour

ПОЧЕМУ АККИ ВЫЛЕТАЮТ?

### Actual behaviour

ПОЧЕМУ АККИ ВЫЛЕТАЮТ?

### Operating system

all

### Version of Telegram Desktop

all

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
Sorry but this is telegram desktop bug tracker, nothing here belongs to user account administration.
