### ISSUE TITLE
Unable to Start Calls in Private Chats

### ISSUE THREAD

**Issue by virdignus** [telegramdesktop/tdesktop#28447]
### Steps to reproduce

Open a private chat.
Attempt to start a call via the call icon or menu.
Observe no response.

### Expected behaviour

Calls should be initiated in private chats like in group chats.

### Actual behaviour

Calls do not start in private chats, but work in group chats after resolving the "active call" message.

 - Unable to start calls in private chats. When clicking the call icon or menu, there is no response.
 -  In group chats, attempting to start a call results in a message saying that there is already an active call and prompts to end it.
 - After ending the active call, a new voice/video chat can be started, but only in group chats. Private chats remain non-functional.
 - When someone tries to call me in a private chat, my line appears busy.

### Operating system

Linux openSUSE

### Version of Telegram Desktop

5.5.6 beta

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
can't reproduce on 2 different linux distributions.

**Comment by virdignus** [comment]
> can't reproduce on 2 different linux distributions.
How can I debug the error?

**Comment by Aokromes** [comment]
i wonder, can you take screenshots of where you start calls?

**Comment by virdignus** [comment]
> i wonder, can you take screenshots of where you start calls?

A screenshot would be uninformative, as nothing happens in private chats, and there are no messages.

**Comment by Aokromes** [comment]
it will help me to see if you are clicking only on one place instead 2.

**Comment by virdignus** [comment]
> it will help me to see if you are clicking only on one place instead 2.

![image](https://github.com/user-attachments/assets/9ae7854a-c4b7-4dd3-802a-09b66dec6fe2)
![image](https://github.com/user-attachments/assets/3e4d7e42-3a20-4e5b-a6c6-36601b895c52)

**Comment by virdignus** [comment]
The issue was resolved after the update.
