### ISSUE TITLE
Cannot undo "floating media viewer window" ?

### ISSUE THREAD

**Issue by Ryder17z** [telegramdesktop/tdesktop#28459]
### Steps to reproduce

I turned this feature on by mistake

1.  View media
2. click ???
3. cannot undo "floating media viewer window" because there is nothing in settings to undo it nor a button to revert in the window itself or it's context menu

### Expected behaviour

Being able to enable and disable this "feature" as needed.

### Actual behaviour

How do i undo this?

![image](https://github.com/user-attachments/assets/e1ca635e-3a24-4b64-be36-3c39ce47f95f)

### Operating system

Windows 11

### Version of Telegram Desktop

5.5.5 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Click on the maximize button?

**Comment by Ryder17z** [comment]
> Click on the maximize button?

That just maximizes the floating window, it reverts when I closed it, to open

**Comment by ilya-fedin** [comment]
> That just maximizes the floating window, it reverts when I closed it, to open as floating again next time

It should remember :thinking:

**Comment by ilya-fedin** [comment]
@Aokromes can you reproduce?

**Comment by Aokromes** [comment]
can't it remembers last state. (windows 11, telegram desktop 5.5.6)

**Comment by Ryder17z** [comment]
It stopped being reproducible for me.
I'll chalk it up to Win11 being buggy.
