### ISSUE TITLE
Window-related features doesn't work

### ISSUE THREAD

**Issue by amiria703** [telegramdesktop/tdesktop#28456]
### Steps to reproduce

1. Open telegram-desktop.
2. Open an image in image viewer or play a video or open a profile, etc. Do whatever causes a new window to appear.
3. It doesn't work.

### Expected behaviour

Work.

### Actual behaviour

Nothing. If I click to play a video, I hear its sound and music pauses, there is no window to play the video.

### Operating system

ArchLinux with i3wm (X11)

### Version of Telegram Desktop

5.5.6 Beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can't reproduce

**Comment by amiria703** [comment]
> Can't reproduce

Oops. By the way, I found nothing suspicious in logs. How can I find the root cause?

**Comment by ilya-fedin** [comment]
> How can I find the root cause?

Try to reproduce in a VM

**Comment by amiria703** [comment]
Cleared cache (folders in ~/.cache) and it solved.
