### ISSUE TITLE
Telegram 5.5.5 fails to build against glib2/gio in Arch Linux

### ISSUE THREAD

**Issue by christian-heusel** [telegramdesktop/tdesktop#28454]
### Steps to reproduce

1. build the latest telegram desktop in Arch Linux (in this case for the [protobuf 28.2 rebuild](https://archlinux.org/todo/rebuild-todo-list-rebuild-todo-list-for-protobuf-282/))
    1. `pkgctl repo clone --protocol=https telegram-desktop` 
    2. `pkgctl build telegram-desktop`
2. observe a compile error as listed below

### Expected behaviour

Telegram builds just fine

### Actual behaviour

We get a compile error about missing Gio function:
```
1921 /build/telegram-desktop/src/tdesktop-5.5.5-full/Telegram/lib_webview/webview/platform/linux/webview_linux_webkitgtk.cpp: In lambda function:                                                                    
   1 /build/telegram-desktop/src/tdesktop-5.5.5-full/Telegram/lib_webview/webview/platform/linux/webview_linux_webkitgtk.cpp:793:36: error: ‘class gi::repository::Gio::Credentials’ has no member named                  ‘get_unix_pid’
   2   793 |                 return credentials.get_unix_pid(nullptr)
   3     ¦ |                                    ^~~~~~~~~~~~
   4 In file included from /build/telegram-desktop/src/tdesktop-5.5.5-full/cmake/external/glib/cppgir/gi/object.hpp:4,
   5     ¦   ¦   ¦   ¦from /build/telegram-desktop/src/tdesktop-5.5.5-full/cmake/external/glib/cppgir/gi/gi.hpp:35,
   6     ¦   ¦   ¦   ¦from /build/telegram-desktop/src/build/gen/webview/webview.hpp:9,
   7     ¦   ¦   ¦   ¦from /build/telegram-desktop/src/tdesktop-5.5.5-full/Telegram/lib_webview/webview/platform/linux/webview_linux_webkitgtk.cpp:24:
   8 /build/telegram-desktop/src/tdesktop-5.5.5-full/cmake/external/glib/cppgir/gi/callback.hpp: In instantiation of ‘gi::detail::connectable<R(Args ...)>::data::data(T&&) [with T = Webview::WebKitGTK::                {anonymous}::Instance::startProcess()::<lambda(gi::repository::Gio::DBusAuthObserver, gi::repository::Gio::IOStream, gi::repository::Gio::Credentials)>; Enable = void; R = bool; Args = {gi::repository::Gio::      DBusAuthObserver, gi::repository::Gio::IOStream, gi::repository::Gio::Credentials}]’:
```

It sounds like some type of compatibility issue to me, as the current repo version was successfully build against version `glib2-2.80.5-1` while it fails to build against `2.82.1-1` 🤔 

The function is still there: https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gcredentials.c?ref_type=heads#L583

It's used here in telegram: https://github.com/desktop-app/lib_webview/blob/2de655f58dc327e40d5d9df71300a0d0fdb39c9f/webview/platform/linux/webview_linux_webkitgtk.cpp#L793

Here is the full log for completeness:
https://pkgbuild.com/~gromit/telegram-desktop-5.5.5-2-x86_64-build.log

cc @svenstaro 

### Operating system

Arch Linux (rolling)

### Version of Telegram Desktop

5.5.5

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
The only explanation I can give for this is one of those three things:
1. glib has removed this method from the gir data
2. glib has moved this method to another file with gir data
3. glib changed the format of gir data and cppgir fails to parse it

**Comment by ilya-fedin** [comment]
It seems there were major changes as the gir data is no more in gobject-introspection but in glib2 package. I also see new GioUnix-2.0.gir. There's a possibility that this could fix the build:
```
diff --git a/cmake/external/glib/CMakeLists.txt b/cmake/external/glib/CMakeLists.txt
index 3c6fe4b..6f73dc5 100644
--- a/cmake/external/glib/CMakeLists.txt
+++ b/cmake/external/glib/CMakeLists.txt
@@ -16,7 +16,7 @@ endfunction()
 add_cppgir()
 
 include(generate_cppgir.cmake)
-generate_cppgir(external_glib Gio-2.0)
+generate_cppgir(external_glib GioUnix-2.0)
 
 find_package(PkgConfig REQUIRED)
 pkg_check_modules(GLIB2 REQUIRED IMPORTED_TARGET glib-2.0 gobject-2.0 gio-2.0 gio-unix-2.0)
```
But even if it does I can't wrap my head of how to handle both new and old distros. If we request the old one then we won't get the unix-specific methods on new distros. If we request the new one, build on old distros won't work at all.

**Comment by christian-heusel** [comment]
Sadly the patch in question did not help 🤔

**Comment by ilya-fedin** [comment]
Perhaps it also needs additional `#include <giounix/giounix.hpp>` in files using GIO Unix-specific APIs

**Comment by heftig** [comment]
`get_unix_pid` is still in `Gio-2.0` and not in `GioUnix-2.0`.

The problem seems to be introduced by [gobject-introspection@42afef0d](https://gitlab.gnome.org/GNOME/gobject-introspection/-/commit/42afef0dfb970639621574c39d5c1a725613e992) which changed the return type of `get_unix_pid` from

```xml
<type name="gint" c:type="pid_t"/>
```

to

```xml
<type name="pid_t" c:type="pid_t"/>
```

and cppgir fails to recognize `pid_t` as a supported type.

```cpp
// pid_t /*none*/ g_credentials_get_unix_pid (GCredentials* credentials /*none*/, GError ** error);
//  /*none*/ g_credentials_get_unix_pid (::GCredentials* credentials /*none*/, GError ** error);
// SKIP;  type  not supported
```

**Comment by ilya-fedin** [comment]
Ah. That's a cppgir issue then...

**Comment by heftig** [comment]
This might be enough for cppgir?

```diff
diff --git i/tools/repository.cpp w/tools/repository.cpp
index 5b5c737..9140851 100644
--- i/tools/repository.cpp
+++ w/tools/repository.cpp
@@ -10,7 +10,8 @@ static std::set<std::string> basic_types{"gchar", "guchar", "gshort", "gushort",
     "gint", "guint", "glong", "gulong", "gssize", "gsize", "gintptr",
     "guintptr", "gpointer", "gconstpointer", "gboolean", "gint8", "gint16",
     "guint8", "guint16", "gint32", "guint32", "gint64", "guint64", "gfloat",
-    "gdouble", "GType", "utf8", "filename", "gi::cstring", "gunichar"};
+    "gdouble", "GType", "utf8", "filename", "gi::cstring", "gunichar",
+    "dev_t", "gid_t", "pid_t", "socklen_t", "uid_t"};
 
 class RepositoryPriv : public Repository
 {
```

**Comment by ilya-fedin** [comment]
> This might be enough for cppgir?

If you ask me then honestly I have no idea... I'm just a user of cppgir 😅

**Comment by christian-heusel** [comment]
The patch for cppgir proposed by @heftig in https://github.com/telegramdesktop/tdesktop/issues/28454#issuecomment-2372735823 did the trick and made the build pass again! Thanks a lot you two! 🥳
