### ISSUE TITLE
Telegram is not reopening while in tray

### ISSUE THREAD

**Issue by alisherabdimuminov** [telegramdesktop/tdesktop#28457]
### Steps to reproduce

System: Ubuntu 23.04
Telegram: 5.5.4

### Expected behaviour

Telegram should be opened in tray

### Actual behaviour

When I close(minimize to tray) telegram does not open again.

### Operating system

Ubuntu 23.04

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can't reproduce. Likely happens because you're using unsupported OS.

**Comment by alisherabdimuminov** [comment]
it had been working well up to this point.
As of version 5.5.4, such a bug is happening.

**Comment by ilya-fedin** [comment]
I can't confirm. Please upgrade your OS to a supported one.

**Comment by alisherabdimuminov** [comment]
At Ubuntu 24.04 there is also such a problem.
The MediaViewer did not work either.

**Comment by ilya-fedin** [comment]
ensure you have latest updates on your 24.04 installation
