### ISSUE TITLE
Tab completer don't work when mentioned in the caption of the file

### ISSUE THREAD

**Issue by kotecat** [telegramdesktop/tdesktop#28455]
### Steps to reproduce

1. Select a file to which you can specify a caption(for example, a picture)
2. Start typing a mention and try pressing tab.

### Expected behaviour

The mention will be completed as usual in the default input field

### Actual behaviour

![image](https://github.com/user-attachments/assets/bcc0b8ab-16d7-4a75-85dd-cd4b247820b2)

Nothing happens

### Operating system

Windows 10 Home (22H2)

### Version of Telegram Desktop

5.5.6 b x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Thanks! I'll fix that for the next version.
