### ISSUE TITLE
Telegram snap install changes `xdg-mime default text/html`

### ISSUE THREAD

**Issue by SamuelMarks** [telegramdesktop/tdesktop#28450]
### Steps to reproduce

Which means `open file:///tmp/index.html` opens Telegram not my web browser.

### Expected behaviour

Web browser should open

### Actual behaviour

Telegram opens

### Operating system

Ubuntu 24.04.1 LTS

### Version of Telegram Desktop

5.5.4

### Installation source

Snap

### Logs

```
$ xdg-mime query default text/html
telegram-desktop_telegram-desktop.desktop
```

FYI: I was able to fix with:
```
xdg-mime default firefox.desktop text/html
```

**Comment by ilya-fedin** [comment]
There's no such code in tdesktop. Could be that it's a bug in snapd or xdg-utils?

**Comment by ilya-fedin** [comment]
Quick searching through xdg-utils issues reveals that it's a long-standing bug. Nothing tdesktop could do about it.
https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/206
https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/206
