### ISSUE TITLE
Fix Blocking

### ISSUE THREAD

**Issue by Lenzar** [telegramdesktop/tdesktop#2845]
Blocking does not yet work as it should.

Blocking somebody stops them from sending me a private message, but I can still see what they're saying in group chats. I blocked them for a good reason.

**Comment by MasterGroosha** [comment]
That's intended behaviour.

**Comment by Lenzar** [comment]
You're serious? Why should I have my enjoyment of a room spoiled by bad eggs?

**Comment by stek29** [comment]
1) That's API issue
2) That's intended
