### ISSUE TITLE
add to folder -> new folder

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#28466]
### Is your feature request related to a problem?

sometimes you find that you have a chat you are not sure where to put, so you must return to create a new folder

### Describe the solution you'd like

how about allowing to create a new folder on add to folder

### Describe alternatives you've considered

none

**Comment by 23rd** [comment]
Please check the v5.8.4 beta.

**Comment by Aokromes** [comment]
cool!
