### ISSUE TITLE
Indicator of unread messages does not display on taskbar icon

### ISSUE THREAD

**Issue by GrinJ** [telegramdesktop/tdesktop#2846]
### Steps to reproduce
1. Pin telegram to taskbar
2. Don't read some message in chat with someone
![t_icon](https://cloud.githubusercontent.com/assets/4682965/21941371/84e836e8-d9d9-11e6-9d45-52c191e43834.png)
3. Press "X" button or Alt+F4, then open telegram again by clicking on icon in taskbar and you'll see that there is no more counter of unread messages. But on tray icon the counter displays correctly
![t_noicon](https://cloud.githubusercontent.com/assets/4682965/21941420/bbb1f2d6-d9d9-11e6-96b2-77d6703b39e1.png)  ![tray_cion](https://cloud.githubusercontent.com/assets/4682965/21941451/ddc0e8e6-d9d9-11e6-97ed-738886567ce4.png)

4. Rigth-click on telegram tray icon and choose "Quit Telegram". Then open it again and you will see counter on taskbar icon again. 
![t_icon](https://cloud.githubusercontent.com/assets/4682965/21941371/84e836e8-d9d9-11e6-9d45-52c191e43834.png)

### Expected behaviour
On the previous version if i closed and opened telegram app again there was still counter of unread messages. On macOS counter displays correctly (it displays if I pressed "X" or cmd+H)

### Actual behaviour
Indicator of unread messages does not display

### Configuration
**Operating system:**
Windows 10, Version 10.0.14393 Build14393

**Version of Telegram Desktop:**
v 1.0

**Comment by john-preston** [comment]
@GrinJ Thank you for your report! I'll try to fix that in the next version.

**Comment by notuxius** [comment]
I have this issue on Windows 1909, Telegram 2.1.6 - the badge counter isn't showing on the taskbar when the app, for example, was launched minimized on sys startup and when it is minimized in the tray and new notifications arrived
