### ISSUE TITLE
File performer and title aren't shown

### ISSUE THREAD

**Issue by zelark** [telegramdesktop/tdesktop#28467]
### Steps to reproduce

I've already uploaded a file via tg bot api. Its file_id is `CQACAgIAAxkDAAIT92b2YSn8R5fUAWHBCx_TSBTTLAQ4AAJWSwACbl2xSzuiZLEVXOa5NQQ`.

Full info about the file:
```edn
{:duration 1688,
 :file_id "CQACAgIAAxkDAAIT92b2YSn8R5fUAWHBCx_TSBTTLAQ4AAJWSwACbl2xSzuiZLEVXOa5NQQ",
 :file_name "softy_The_Day_I_Passed_lofi_hip_hop_relaxing_beats_pzxY5.m4a",
 :file_size 27292654,
 :file_unique_id "AgADVksAAm5dsUs",
 :mime_type "audio/mp4",
 :performer "Lofi Girl - Chill Beats",
 :title "softy - The Day I Passed ☕️ [lofi hip hop/relaxing beats]"}
```

So you can resend it by file_id to reproduce the bug.

### Expected behaviour

File performer and title are shown as it is in the latest iOS client (my current version 11.1.1).
A screenshot from it
![image](https://github.com/user-attachments/assets/c8be27af-a20d-427d-aa1d-1d006dbca09a)

### Actual behaviour

File performer and title aren't shown
<img width="346" alt="Screenshot 2024-09-27 at 10 40 37" src="https://github.com/user-attachments/assets/a78c4344-940a-4d7e-9260-5e4be67f15b1">

### Operating system

macOS Catalina v.10.15.7

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

**Comment by zelark** [comment]
In native Telegram client for macOS everything is fine 
<img width="283" alt="image" src="https://github.com/user-attachments/assets/c2a9c35f-33f5-4ffa-8344-081606ae0e79">

**Comment by john-preston** [comment]
Yeah, strangely macos qt has a problem with showing some texts with emoji, if not done through my custom text rendering. I'm not using it for file filenames because it doesn't support eliding long strings with ellipsis "..." in the middle of the string (instead of the end), and that's what I want for filenames. It should be supported at some point, but I don't have a ETA :(

**Comment by zelark** [comment]
Thanks. Checked that on Sonomna 14.3.1 there is the same problem.

**Comment by 23rd** [comment]
Should be better in the latest version.

**Comment by zelark** [comment]
Yes, looks better now
<img width="795" alt="image" src="https://github.com/user-attachments/assets/d2d02ed2-9e75-46e6-b845-144327a75c19">

**Comment by Aokromes** [comment]
so, this can be closed now?

**Comment by zelark** [comment]
I guess so, thank you
