### ISSUE TITLE
Telegram desktop doesn't work imageclick

### ISSUE THREAD

**Issue by unera** [telegramdesktop/tdesktop#28462]
### Steps to reproduce

1. Install Debian 11
2. Install telegram desktop 5.5.6 beta

### Expected behaviour

Previous telegram versions have the functional:

if a user clicks image, the application showes a window, where the user can review it, scale it etc

Since latest upgrades my desktop not provides 'image:click' functional. So I can look through proto only mobile version, not desktop.

PS: external links are clickable, but only images aren't clickable.

### Actual behaviour

see above

### Operating system

Debian/11

### Version of Telegram Desktop

5.5.6 beta

### Installation source

Static binary from official website

**Comment by unera** [comment]
Also, version 5.5.5 works fine. If it upgrades by button 'Update Telegram' it stops the functional.

**Comment by ilya-fedin** [comment]
Can't reproduce

**Comment by bodqhrohro** [comment]
Same for me (media viewer won't open at all).

**Comment by inferrna** [comment]
Confirm this. Looks like #27598 
When I click video I can hear sound but no image shows.
But now `QT_QPA_PLATFORM=xcb` don't work.
[tg_xcb_strace.log.gz](https://github.com/user-attachments/files/17180730/tg_xcb_strace.log.gz)
[tg_xcb.log.gz](https://github.com/user-attachments/files/17180731/tg_xcb.log.gz)
[tg_wayland.log.gz](https://github.com/user-attachments/files/17180732/tg_wayland.log.gz)

**Comment by bodqhrohro** [comment]
> Looks like https://github.com/telegramdesktop/tdesktop/issues/27598

Yet I have this on X.Org, and there is no transparent window, just no any window is opened at all. Yet indeed, the sound plays if I open a video.

**Comment by tacieferreira** [comment]
[Uploading facebook-rafarafa334608-22_9_2024-FsFZBYYM.zip…]()

**Comment by bodqhrohro** [comment]
No, thanks, we don't need the whole Facebook to be uploaded here.

**Comment by bodqhrohro** [comment]
Fixed for me in 5.5.7 beta.
