### ISSUE TITLE
Reactions are not exported from chat history

### ISSUE THREAD

**Issue by fulcrum6378** [telegramdesktop/tdesktop#28474]
### Steps to reproduce

Please include message reactions in chat export.

### Expected behaviour

Message reactions are somehow a crucial part of a conversation and should be included in chat export.

### Actual behaviour

Reactions are not exported from chat history.

### Operating system

Windows

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
will be fixed on next release.
