### ISSUE TITLE
Messages sent by me show on the same side as the messages sent by the other person

### ISSUE THREAD

**Issue by ojasvib** [telegramdesktop/tdesktop#28476]
### Steps to reproduce
I just opened the app and noticed this 
![image](https://github.com/user-attachments/assets/2f917d16-9eb1-4991-afff-a2489e84036a)

### Expected behaviour

Messages sent by me should show on the right side

### Actual behaviour

Messages sent by me are shown on the left side

### Operating system

Windows 11

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
disable adaptative layout
