### ISSUE TITLE
Default enabled Precise High DPI scaling

### ISSUE THREAD

**Issue by fireandfuel** [telegramdesktop/tdesktop#28478]
### Is your feature request related to a problem?

Telegram Desktop fails to dynamically detect the screen scaling setting of the current screen where its being displayed on MS Windows 11 x64. It only seems to detect the screen scaling setting of the primary screen when switching on the default interface scaling in its settings.

I would guess that Telegram Desktop _explicitly_ overrides the dynamically detection for enabling its own scaling setting.

### Describe the solution you'd like

Telegram Desktop dynamically detect the screen scaling setting of the current screen where it being displayed, like any other MS Windows app and re-scales the window content dynamically agnostic to the screen scaling setting without restarting the app.

Telegram Desktop's interface scaling maybe be applied on top of the scaling setting of the current screen.

### Describe alternatives you've considered

- Setting a fixed interface scaling to 150% works when I have it on my primary screen only. I need to restart Telegram Desktop every time I change the interface scaling. 
- Setting a fixed interface scaling to 125% is better on my secondary screen, but a bit small for my primary screen. I need to restart Telegram Desktop every time I change the interface scaling. 
- Enable default interface scaling and it seems to detect the scaling setting of the primary screen which is too big for my secondary screen

### Additional context

A multi monitor setup might look like this:
3840x2160 @ 150% scaling (primary screen)
1920x1080 @ 100% scaling (secondary screen)

Usually Telegram Desktop runs on the secondary screen.

**Comment by john-preston** [comment]
Unfortunately, that's a very hard problem to fix with a permittable quality :( You can try "Enable precise High DPI scaling" in Settings > Advanced > Experimental, that way it should scale exactly to the screen you're using it on, but it comes with a lot of graphical glitches / artifacts and I'm not sure how to deal with them nicely with current UI approach.

**Comment by fireandfuel** [comment]
The "precise High DPI scaling" seems to work a lot better for me, I didn't noticed any glitches yet after enabling it. I keep testing it.

**Comment by ilya-fedin** [comment]
I don't understand how you could not see obvious artifacts
![](https://github.com/user-attachments/assets/657bd156-f2c0-4e0c-aea6-eb060d8e7ff6)
The issue is also effectively a dup of #1121
