### ISSUE TITLE
color blind selected message indicator like on android and unigram

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#28470]
### Is your feature request related to a problem?

some people have problems noticing witch messsages are selected or no

### Describe the solution you'd like

on android and unigram a check is added next to selected messages.

https://i.imgur.com/Yeex2Vs.png

### Describe alternatives you've considered

more contrast for selected messages like materialgram.

https://i.imgur.com/7QEDrfL.png

**Comment by 23rd** [comment]
Such enhancements can have various regressions, so it would be awesome if you tested this a bit.

https://github.com/telegramdesktop/tdesktop/actions/runs/11307745238

**Comment by Aokromes** [comment]
some issues found at
https://t.me/TelegramDesktopTalk/126988
https://t.me/TelegramDesktopTalk/127005

on unigram and android the indicator is at left, idk if you must care about that.

**Comment by 23rd** [comment]
Round two.
Some fixes.
Now the Chat Settings has a new option to choose alignment side for checks.

https://github.com/telegramdesktop/tdesktop/actions/runs/11320925584

Would appreciate to hear some feedback.

**Comment by Aokromes** [comment]
https://i.imgur.com/rjtBWix.jpeg
if i open shide bar text will be under it.

**Comment by Aokromes** [comment]
already pushed on 5.6.2
