### ISSUE TITLE
Switching between sound cards when changing the playing track

### ISSUE THREAD

**Issue by AdrianusWest** [telegramdesktop/tdesktop#28481]
### Steps to reproduce

1. Select the default map in the settings.
2. Turn on music.
3. Switch the volume in the tray to a different sound card.
4. When the track is automatically switched randomly, it is reset to the default card specified in the settings. 

### Expected behaviour

The sound is played back according to the sound card selected in the OS.

### Actual behaviour

In fact, the telegram client manages my sound for some reason, although the sound and source priority should be left to the OS.

### Operating system

Arch linux

### Version of Telegram Desktop

telegram-desktop 5.5.5-3 from extra repo

### Installation source

Other (unofficial) source

### Crash ID

-

### Logs

```shell
-
```

**Comment by ilya-fedin** [comment]
No, tdesktop has no code for that. But it's possible that underlying system libraries have bugs.

**Comment by ilya-fedin** [comment]
Another possibility is that the OS doesn't really manage that, reverse to what you expect. This is the case on Windows and macOS for intstance: the OS doesn't automatically move the tracks, tdesktop has to listen for system events and move it manually. But there's no code for that on Linux.

**Comment by ilya-fedin** [comment]
If you insist that it should be up to the OS, I would say there's no bug on tdesktop level as tdesktop has no code for that and you have to bug lower level libraries (the near one is openal-soft).
