### ISSUE TITLE
spoiler not works for video

### ISSUE THREAD

**Issue by 221V** [telegramdesktop/tdesktop#28489]
### Steps to reproduce

spoiler not works for video description and image for youtube links
1 - just send youtube video link to my contact's dialog
2 - <img src="https://i.imgur.com/bCFywuM.png">

### Expected behaviour

expected -- spoiler hides not only url but image and description too

### Actual behaviour

spoiler not works for video description and image for youtube links
<img src="https://i.imgur.com/bCFywuM.png">

### Operating system

lubuntu 22.04 lts

### Version of Telegram Desktop

4.16.6

### Installation source

Static binary from official website

**Comment by 221V** [comment]
updated to 5.5.5 -- the same bug ..

**Comment by 221V** [comment]
check on mobile --
android v10.2.3 (4075) store bundled armeabi-v7a armeabi -
from Play market - redmi 7a -
the same bug..

please fix spoiler ...
thank you!

**Comment by ilya-fedin** [comment]
You can remove the preview by clicking on the cross

**Comment by 221V** [comment]
> You can remove the preview by clicking on the cross

yeah, also I can delete telegram and goto use other messenger app --
yeah, I know about that "you can .." talks

but, please note --
spoiler definitely NOT works in this case -- as we can see ;)

**Comment by ilya-fedin** [comment]
You have the liberty to both have and don't have the preview

**Comment by 221V** [comment]
but Expected behaviour is spoiler hides preview too
as shown on screenshot above - spoiler works incorrect -
this is Schrödinger's spoiler right now :D

I understand your opinion -- please understand my too  🤝

**Comment by ilya-fedin** [comment]
@john-preston has confirmed it's not a bug in a private discussion. But you can create a feature request for link preview spoilers on suggestions.telegram.org.

**Comment by ilya-fedin** [comment]
> There is no cross?

When you insert a link, you get the link preview above the input field. And there's a cross on the right side.

**Comment by IxcheI** [comment]
Ah got it, I was editing my previous message to insert the link and the embedding x takes the same location as the "cancel editing" x
