### ISSUE TITLE
Telegram flatpak - Wrong IME candidate window in fcitx5

### ISSUE THREAD

**Issue by 7HE-W0R1D** [telegramdesktop/tdesktop#28486]
### Steps to reproduce

1. Install telegram from Flathub, version 5.5.5
2. Install and activate fcitx5, add Chinese pinyin input
3. Try to type Chinese in Telegram

### Expected behaviour

Candidate window should be right around cursor

### Actual behaviour

Candidate window is far away from the cursor, in the lower right. Started since the last update, replicated on two computers running Fedora silverblue 41.
![image](https://github.com/user-attachments/assets/740ff9de-f148-4b5c-896c-99e5c61d678a)
![image](https://github.com/user-attachments/assets/34293cf4-812d-4116-a895-11f970bfda17)

### Operating system

Fedora Linux 41.20240930.n.0 (Silverblue Prerelease)

### Version of Telegram Desktop

5.5.5

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
It's not under Telegram control, sorry
