### ISSUE TITLE
Add option to disable middle mouse click

### ISSUE THREAD

**Issue by vitaly-zdanevich** [telegramdesktop/tdesktop#28485]
Problem: sometimes using middle mouse scrolling I accidentally paste _PRIMARY selection_.

I am on Linux.

Similarly, Firefox has the option `middlemouse.paste`.

QT is not allowing that https://bugreports.qt.io/browse/QTBUG-58087

**Comment by ilya-fedin** [comment]
It's buried deeply and is not under tdesktop control
