### ISSUE TITLE
Media viewer is semitransparent

### ISSUE THREAD

**Issue by kolayne** [telegramdesktop/tdesktop#28480]
### Steps to reproduce

1. Open a video or a picture

### Expected behaviour

I can only see the media window, not what's behind it

### Actual behaviour

The preview window is semitransparent. For example, the following is a screenshot of a green rectangle image (viewed after sent in a Telegram chat) over a browser window colored in red.

![image](https://github.com/user-attachments/assets/271a3808-2dfc-4cd7-9001-545b480b9c63)

### Operating system

Arch Linux, i3 version 4.23, picom version 11.2 (vgit-89c2c)

### Version of Telegram Desktop

5.5.7 (git 1cb92ef)

### Installation source

Other (unofficial) source

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/28463
