### ISSUE TITLE
bug with font after update

### ISSUE THREAD

**Issue by 221V** [telegramdesktop/tdesktop#28490]
### Steps to reproduce

1. update from 4.16.6 to 5.5.5 version via Menu -> Settings -> Advanced -> Update

### Expected behaviour

expected the same font as in 4.16.6 version -- uppercase letters has the same height for usual messages

### Actual behaviour

actual behavios, after update 4.16.6 to 5.5.5 version -- uppercase letters has the different height for usual messages --
look at screenshots onto 12th letter of Ukrainian alphabet -- it looks like 13th letter, and has more height than other letters --
onto 4.16.6 version was good, but 5.5.5 version looks like deterioration - not improvement 
https://en.wikipedia.org/wiki/Ukrainian_alphabet 
<img src="https://i.imgur.com/iiL0XBi.png">

<img src="https://i.imgur.com/wf84yxN.png">

and I do not know what font use instead broken "Default" ((
nothing looks like before update ((

note that I not change nothing with fonts or telegram settings --
just update telegram and got broken look of text ...

please return back the "Default" font -- the same look as was in 4.16.5 version..
thank you

### Operating system

lubuntu 22.04 lts

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

**Comment by 221V** [comment]
temporary solution -- most similar to 4.16.6 looks like --
not "Default" font
not "System"
not many other that check

but
"Open Sans"

ok, can live with this

**Comment by john-preston** [comment]
That's weird, cause the default one is "Open Sans".

**Comment by ilya-fedin** [comment]
> That's weird, cause the default one is "Open Sans".

The person doesn't like the new look of `I` that is made for people who don't like that it's the same as `l`

**Comment by 221V** [comment]
> > That's weird, cause the default one is "Open Sans".
> 
> The person doesn't like the new look of `I` that is made for people who don't like that it's the same as `l`

That's weird, cause the only change was updated telegram --
nothing changed in system settings, nothing changed in fonts etc ...

Also laptop was not reboot -- so nothing was not appied with other settings etc
telegram only was updated and restarted

**Comment by 221V** [comment]
> That's weird, cause the default one is "Open Sans".

no, cause with "Open Sans" in setting the same text looks like
<img src="https://i.imgur.com/2lKxp8a.png">

you can to compare with screenshot of same text with "Default" font --
really not the same ..

ty, have good day :)

**Comment by ilya-fedin** [comment]
> That's weird, cause the only change was updated telegram --
> nothing changed in system settings, nothing changed in fonts etc ...

I haven't said anything about system settings. It's a change in Telegram. An intended change. And I told why it was made: people don't like when `I` is the same as `l`, it's a completely intentional change, not a bug.

> upd. The person doesn't like when all ok with latin text but cyrillic text looks like anybody with alcohol problems :D

We can't change one but not the other, that's how open type features work.

**Comment by 221V** [comment]
> > That's weird, cause the only change was updated telegram --
> > nothing changed in system settings, nothing changed in fonts etc ...
> 
> I haven't said anything about system settings. It's a change in Telegram. An intended change. And I explained why it was made: people don't like when `I` is the same as `l`, it's a completely intentional change, not a bug.
> 
> > upd. The person doesn't like when all ok with latin text but cyrillic text looks like anybody with alcohol problems :D
> 
> We can't change one but not the other, that's how open type features work.

maybe just no needs to mix latin l with cyrillic І ?
but ok -- that is your app, and you can do anything with it...

have good day, bye

**Comment by ilya-fedin** [comment]
> maybe just no needs to mix latin l with cyrillic І ?

that's not possible technically as I already explained...

**Comment by 221V** [comment]
> > maybe just no needs to mix latin l with cyrillic І ?
> 
> that's not possible technically as I already explained...

sorry but you not explained nothing cause create problem for users --
search in settings previous good font --
and fixes nothing --

I just repeat --
maybe just no needs to mix latin l with cyrillic І ?

but that is not problem on websites and in other programs --
just telegram devs decides to "improve" to display text in cyrillic ...

ok, ok, ty, have good day

just close this conversation
you not needs users opinions -- so this conversation no needs too..

**Comment by ilya-fedin** [comment]
> you not needs users opinions

This change was applied exactly becuase users asked for it, in #4072

**Comment by 221V** [comment]
yes, one weird user has a strange fondness for ancient newspaper ligatures --
and this is the reason for make default "improvements" for all users ?

and break pixel-perfect default font for users that like it for years..

wow, the great idea!
lets break anything..


why not make optional font for that one weird user with a strange fondness instead?
I do not know..

**Comment by ilya-fedin** [comment]
That issue has 23 participants. Your issue has only you.

**Comment by 221V** [comment]
> That issue has 23 participants. Your issue has only you.

"Argumentum ad Populum" is a [fallacious argument](https://en.wikipedia.org/wiki/Fallacy) which is based on claiming a truth or affirming something is good or correct because many people think so.

**Comment by 221V** [comment]
> That issue has 23 participants. Your issue has only you.

о, так ты же "родной братишка русский", Илюша - для тебя по-русски можно написать ))
возможно, даже поймешь))

говоришь, что милионы не могут ошибаться, да?

Апелляция к большинству ([лат.](https://ru.wikipedia.org/wiki/%D0%9B%D0%B0%D1%82%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D1%8F%D0%B7%D1%8B%D0%BA) argumentum ad populum — «аргумент к народу») — вид [логически ошибочной аргументации](https://ru.wikipedia.org/wiki/%D0%9B%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%83%D0%BB%D0%BE%D0%B2%D0%BA%D0%B0), основанной на мнении, что большинство людей не может ошибаться.

https://ru.wikipedia.org/wiki/Апелляция_к_большинству  
  
.  
  
и сейчас еще и скажешь, наверное, что в 21м веке это нормально --
миллионам русских идти убивать миллионы укранцев только ради изменения линии на карте?

да, Илюша, такое утверждаешь?
миллионы не могут ошибаться, да?

пожелают тебе долгой -- оо-очень долгой жизни --
такой, чтобы тебе ХВАТИЛО времени осознать все ошибки.
и на покаяние тоже чтобы хватило времени.  
  
.  
  
не отвечай мне.
до свидания.
живи долго.

**Comment by 221V** [comment]
Дуров говорил, что набирает лучших из лучших

что я вижу -- человек элементарных логических ошибок аргументации не знает
это лучшие из лучших?))
ясно, понятно

**Comment by ilya-fedin** [comment]
> you not needs users opinions

> one weird user

> That issue has 23 participants

> Argumentum ad Populum

![](https://github.com/user-attachments/assets/7fe1f10f-280e-4d51-a9c8-53b5098b1940)

**Comment by 221V** [comment]
> ![](https://private-user-images.githubusercontent.com/17829319/373875348-7fe1f10f-280e-4d51-a9c8-53b5098b1940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMDcwNDUsIm5iZiI6MTcyODIwNjc0NSwicGF0aCI6Ii8xNzgyOTMxOS8zNzM4NzUzNDgtN2ZlMWYxMGYtMjgwZS00ZDUxLWE5YzgtNTNiNTA5OGIxOTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDA5MjU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxODNjODNhYmQyM2YwNjkwMmNlNjE5MjIyZGQ3ZDc2MTA2MWNkZGY0NzM2NWNkNWY1MTY2ZDE0ZjJjNjg5MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e5Em4jZ7_h2edI7yY2wy71FwCZRk2EpSv381kyNa1E4)

->

<img src="https://i.imgur.com/sUk90L4.jpeg">

> После задержания Дурова в Telegram заявили, что компания соблюдает европейские законы (c)

как забавно - книгами поделиться - нарушение закона! низзя! 🤡🤡🤡

в то же время, убывать украинцев - и угрожать насилием и убийствами,
шерить и позволять шерить фото и видео убийств --
не является нарушением закона 🤡🤡🤡

типическое проявление русской шизы - да, Илюш? @ilya-fedin 

хотя, о чем это я вообще -- в русского же символом есть шиза 🤡 --
курица о двух головах на гербе 🤡 не так ли?

на двух стульях сидеть одновременно --
и стуле копирастеров, и стуле фсб 🤡 
и еще вещать что-то о свободе 🤡 
русские либерали 🤡

тебе просто еще много времени нужно, чтобы наконец осознание --
осознание, какой это у вас гол -- гол в свои ворота!

живи долго!
чтобы наконец совесть проснулась, наконец, и осознание пришло.
