### ISSUE TITLE
Periodically telegram starts sending a huge number of requests

### ISSUE THREAD

**Issue by svallex** [telegramdesktop/tdesktop#28493]
### Steps to reproduce

1. Use the Telegram client as usual
2. After a while it starts spamming with requests (a few thousand requests a minute)

### Expected behaviour

Telegram doesn't send such number of requests

### Actual behaviour

Screenshot from proxyman
<img width="1148" alt="Screenshot 2024-10-04 at 16 41 04" src="https://github.com/user-attachments/assets/37d794c9-550b-4af7-b949-8dde516d2155">

### Operating system

macOS Sonoma 14.6.1

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Sounds like a dup of #28453
