### ISSUE TITLE
Numbers cannot be displayed correctly

### ISSUE THREAD

**Issue by cxw620** [telegramdesktop/tdesktop#28494]
### Steps to reproduce

-

### Expected behaviour

-

### Actual behaviour

See the screenshots:
![图片](https://github.com/user-attachments/assets/54bf4e25-22ab-49e2-9a84-1019936e1b86)
![图片](https://github.com/user-attachments/assets/886bb684-c149-422a-b515-e05c88ac25cc)

Setting language to English / changing fonts doesn't help.

BTW, click on the id and the copied numbers string is normal.

### Operating system

Windows 11 24H2

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
paste those humbers here.

**Comment by cxw620** [comment]
Example:

2078570421

![图片](https://github.com/user-attachments/assets/ddc96a86-3148-4aa0-8e55-f9a9c7c72560)

Edit: recently, only the numbers in the two locations shown in the screenshots are displaying incorrectly.

**Comment by cxw620** [comment]
May be only system with lang setting Chinese has such problem...

And I found this:

![图片](https://github.com/user-attachments/assets/843a4188-76a4-470b-9364-02a0579919fe)

**Comment by Aokromes** [comment]
> May be only system with lang setting Chinese has such problem... I have just bought a new laptop with Windows 11 preinstalled and maybe Windows 11 is to be blame, too...
> 
> And I found this:
> 

i tested both windows 10 and 11 and no problem (english and spanish locale)

**Comment by cxw620** [comment]
> > May be only system with lang setting Chinese has such problem... I have just bought a new laptop with Windows 11 preinstalled and maybe Windows 11 is to be blame, too...
> > And I found this:
> 
> i tested both windows 10 and 11 and no problem (english and spanish locale)

Emmm, my system is fresh-installed, latest Telegram Destop and default settings... The problem remains and I may have to adapt to it, at worst each character has the corresponding number...

**Comment by cxw620** [comment]
OK, the problem is fixed when I change my system lang to English.
