### ISSUE TITLE
Возможность назвать чат по своему только для себя

### ISSUE THREAD

**Issue by asafov** [telegramdesktop/tdesktop#28491]
### Is your feature request related to a problem?

Возникает необходимость назвать чат по своему, не переименовывая его у всех.
Например мы саппортим в телеге клиентов и чат как-то называется. А мне бы хотелось туда дописать например ID клиента или некую информацию, видную только для меня.

### Describe the solution you'd like

Реализовать возможность переименовать чат только для себя. Есть ли это уже у кого-то - не могу сказать.
Как вариант сделать это только для Premium.

### Describe alternatives you've considered

Не рассматривал другие альтернативы, приходится всё держать в голове сейчас.
Я готов и дальше оплачивать премиум как минимум из-за этой фишки.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
this bug tracker is english only, plz, update your issue or it will be closed on 24h.
