### ISSUE TITLE
can't rename contact and other bug(s)

### ISSUE THREAD

**Issue by 221V** [telegramdesktop/tdesktop#28497]
### Steps to reproduce

anyway @ilya-fedin will say "this is not bug but feature"..
but I think this is definitely not user-friendly moment --
and try to describe it here.. lets go!

0 -- we have installed - and logged in - telegram desktop on laptop + telegram on mobile
(lubuntu 22.04 lts and redmi 7a)
1 -- telegram on mobile is closed
2 -- in telegram desktop you rename your contact
3 -- open telegram on mobile (this not requires minutes -- you can try after hours)
4 -- observe how contact on telegram desktop got back old name -- like you was not rename it..
5 -- you can try again with the same effect, wow! cool!

other similar case:
2 -- in telegram desktop you pin chats and channels, change order of penned for better user expirience
4 -- observe how pinned chats and channels has regression in its order - changes its order - became looks like you was not change its order on - telegram desktop .. ((

@john-preston is this api issue? problem with cache on server side? or what..
looks weird, like tg mobile has more priority that telegram desktop..

### Expected behaviour

Expected behaviour:
opening telegram on mobile NOT discards changes made in telegram desktop before

tg versions the same as in [issues 28489](https://github.com/telegramdesktop/tdesktop/issues/28489)

### Actual behaviour

actual behaviour is like described in Steps to reproduce

### Operating system

lubuntu 22.04 lts

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
This looks like the mobile version problem tbh, if everything is fine while relaunching TDesktop before you open the mobile app.

So this doesn't really belong here, there is nothing I can do to fix that in the code of this repository.

If you write exactly what mobile version you're trying (iOS / Android? which version of the official app? installed from where? - in case of Android it could be Play Market, the official website or some other store maybe) I may try to reproduce that and if reproduced I can try reporting to the relevant developer and see where this leads.

In any way it is better to open a bug on https://bugs.telegram.org with exact app versions (both TDesktop and mobile) and steps which are taken, without any vagueness, like:

1. have a contact named "A" in the contact book in iOS and on Telegram
2. rename this contact "A" to "B" in TDesktop
3. open iOS app where this contact already had name "A"
4. open chat with that contact on iOS app
5. relaunch TDesktop and observe name "A" again in TDesktop

or something similar. I'll repeat that this belongs to https://bugs.telegram.org, not here.

**Comment by 221V** [comment]
android v10.2.3 (4075) store bundled armeabi-v7a armeabi -
from Play market - redmi 7a

**Comment by john-preston** [comment]
This looks like a pretty old app, current version is v11.2.0 (5299).

Anyway, the rest (most importantly - exact steps, the issue description steps are a bit vague) is important for me to try to reproduce.

**Comment by 221V** [comment]
ok, thank you, I will update right now)

that will be nice that bug will not repeat more

**Comment by 221V** [comment]
updated on modile to v11.2.0 (5299) store bundled armeabi-v7a armeabi - redmi 7a
now stories can not be hidden (((

story from other user can be hidden -- long tap -- shows menu -- hide
but story from telegram -- on long tap -- not shows menu -- can not hide --
that just vibro (((

I no need stories at all -- just my few chats,
but stat stories at the top(((

exchange one bug to another? :( ok...
