### ISSUE TITLE
Ширина чата

### ISSUE THREAD

**Issue by 1vanK** [telegramdesktop/tdesktop#28509]
### Is your feature request related to a problem?

Интерфейс десктопной версии заточен под мобилки почему-то. Чат читаешь в узенькой полосочке. Неудобо.

### Describe the solution you'd like

Дайте возможность настроить ширину чата или пусть занимает всю доступную ширину

### Describe alternatives you've considered

Дуров, верни стенку

**Comment by Aokromes** [comment]
this bug tracker is english only, plz, update your issue or it will be closed on 24h.

**Comment by 1vanK** [comment]
https://translate.google.com

**Comment by 1vanK** [comment]
@ilya-fedin что у вас с клиентоориентированностью? Почему всякий наемный работник условия ставит клиентам?

**Comment by ilya-fedin** [comment]
We all are open source enthusiasts here. The only hired worker is @john-preston. This bugtracker is a community one and is non-official. The official way of reporting bugs is the in-app support.

**Comment by 1vanK** [comment]
Вы еще и бесплатно батрачите))

**Comment by 1vanK** [comment]
> This is the complete source code and the build instructions for the official [Telegram](https://telegram.org/) messenger desktop client, based on the [Telegram API](https://core.telegram.org/) and the [MTProto](https://core.telegram.org/mtproto) secure protocol.

Бесплатно пилите официальный клиент в неофициальном репозитории? Вот Паша даёт

**Comment by ilya-fedin** [comment]
The reporisotory is official. The issue tracker is not.
