### ISSUE TITLE
After the update 5.5.5 -> 5.6, on Linux selecting the text with the mouse, clicking the middle button pastes the text 2 times

### ISSUE THREAD

**Issue by Giando** [telegramdesktop/tdesktop#28502]
### Steps to reproduce

1. Select the text
2. Click the middle mouse button to compose a new message

### Expected behaviour

Text pasted 1 time

### Actual behaviour

Text pasted 2 time

![Istantanea_2024-10-07_17-47-42](https://github.com/user-attachments/assets/22f4c916-4e36-4d37-a0a9-e3e98bd17711)

### Operating system

Debian GNU/Linux 12.7 amd64

### Version of Telegram Desktop

5.6 & 5.6.1

### Installation source

Static binary from official website

**Comment by Giando** [comment]
> I'm not seeing this. What input method do you use, what's your desktop environment, and are you on X11 or Wayland?

`XFCE X11 glibc 2.36`

With the downgrade to 5.5.5 (Butterfly Module by Coach Oronzo Canà, text note for Italians, who will understand :stuck_out_tongue_winking_eye:) the problem does not exist.

**Comment by svpcom** [comment]
I have the same bug (X11, debian 12, x86_64)

**Comment by ilya-fedin** [comment]
Is this still happening?

**Comment by svpcom** [comment]
@ilya-fedin It seems fixed. Thanks!

**Comment by Giando** [comment]
> Is this still happening?

I confirm the fix in [v5.6.2](https://github.com/telegramdesktop/tdesktop/releases/tag/v5.6.2),
thank you! :yellow_heart:
