### ISSUE TITLE
I can't see the link preview image, does anyone know why? I need help

### ISSUE THREAD

**Issue by mandoocash** [telegramdesktop/tdesktop#28506]
### Steps to reproduce

I can't see the link preview image, does anyone know why? I need help

### Expected behaviour

I can't see the link preview image, does anyone know why? I need help

### Actual behaviour

I can't see the link preview image, does anyone know why? I need help

### Operating system

 Windows 11

### Version of Telegram Desktop

5.6.1x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
previews are made server side.
