### ISSUE TITLE
Media isn't displayed properly on Fedora 40

### ISSUE THREAD

**Issue by sa0tome** [telegramdesktop/tdesktop#28504]
### Steps to reproduce

1. Open any media from Telegram Desktop
2. "Media Viewer" is opened, but nothing is displayed
3. In the screen recording, you can see that I'm trying to select any media -- photo and video -- and media viewer does not display the object as expected

[Gravação de tela de 2024-10-08 00-04-26.webm](https://github.com/user-attachments/assets/fdd921f6-f837-4e07-a938-a8ed5b5c02a9)

This started to happen recently, some versions before, media viewer behavior was completely normal.

### Expected behaviour

When clicked, media should pop up a viewer and display the content.

### Actual behaviour

When clicked, media is not shown in the viewer.

### Operating system

Fedora 40, Gnome 45.10, Wayland

### Version of Telegram Desktop

5.6.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
> Fedora 40, Gnome 45.10

Isn't Fedora 40 providing GNOME 46?

**Comment by ilya-fedin** [comment]
it won't work on GNOME 45 due to https://gitlab.gnome.org/GNOME/mutter/-/issues/3229, you either have to upgrade to GNOME 46.1+ or downgrade to GNOME 44

**Comment by sa0tome** [comment]
Hi!
Yes, I have updated and now it is working. Thank you!
