### ISSUE TITLE
can not set programming language for monospace formatted code block

### ISSUE THREAD

**Issue by 221V** [telegramdesktop/tdesktop#28513]
### Steps to reproduce

1 -- insert code to dialog
```
# {|"\\"|}="\"\\\\\"";;
- : bool = true
```

2 -- select is -> formatting -> monospace

3 -- click onto monospace block header -> set code language -> OCaml -> save

4 -- monospace block disappeared -- not exists after previous "saving"
wtf ? O_o

### Expected behaviour

Expected behaviour: monospace block shows OCaml syntax highlighting and not disappeared after saving OCaml language for code syntax highlighting ... 

### Actual behaviour

monospace block disappeared after saving OCaml language for code syntax highlighting ... 

### Operating system

lubuntu 22.04 lts

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

**Comment by 221V** [comment]
update to v5.6.1 not helps

fix not included yet? ok

**Comment by john-preston** [comment]
Not yet, just in code for now.
