### ISSUE TITLE
Cant copy or paste inside apps and wallet

### ISSUE THREAD

**Issue by FranciscoBSpadaro** [telegramdesktop/tdesktop#28510]
### Steps to reproduce

System OS - POP.OS
install telegram - sudo snap install telegram-desktop
open wallet - try to copy the 24 pass phrase ,  and i cant copy
apps , i tryed to copy texts inside app , exemple , game app , and i cant copy , or paste anyting inside apps

### Expected behaviour

be able to copy and paste inside apps and wallet

### Actual behaviour

cant copy or paste , using ctrl c  , ctrl v , if use right click to select copy or past , the aplication close/crash

### Operating system

Pop-OS

### Version of Telegram Desktop

5.6.1

### Installation source

Snap

**Comment by ilya-fedin** [comment]
see #25126
