### ISSUE TITLE
SECURITY LEAK

### ISSUE THREAD

**Issue by kurttu4** [telegramdesktop/tdesktop#28523]
### Steps to reproduce

1.some random guy from the chat wrote
2.I added him to my contacts
3.I have a block on showing my number to everyone
4.but he was automatically added to the exceptions

### Expected behaviour

the person must be blocked to show my number

### Actual behaviour

he was automatically added to the exceptions and accordingly saw my phone number

### Operating system

Win10

### Version of Telegram Desktop

5.6.1 x64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
It's configurable
![](https://github.com/user-attachments/assets/8f86ac1c-21a4-46a4-ae25-c75ee5dd82ce)

**Comment by kurttu4** [comment]
> It's configurable ![](https://private-user-images.githubusercontent.com/17829319/376023400-8f86ac1c-21a4-46a4-ae25-c75ee5dd82ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDg5ODgsIm5iZiI6MTcyODkwODY4OCwicGF0aCI6Ii8xNzgyOTMxOS8zNzYwMjM0MDAtOGY4NmFjMWMtMjFhNC00NmE0LWFlMjUtYzc1ZWU1ZGQ4MmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDEyMjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MzkyOTY5NzViMzJlODNlNWQ1ZTVhNmNjMjI3MTY5Y2FhZjgyM2M1Nzc1MGRkYzkyYzJkYWNhYTBkOTZiOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a2K18_IGX8xaHCDOPlpfmOCTKONGdIfKaMb-XeBC12c)
Why is there a checkpoint showing the phone number if I set a general checkpoint not to show my phone number to anyone and automatically clicked add user

**Comment by kurttu4** [comment]
like why should I bother, go away and discuss this problem in another forum, this problem also exists in the mobile app

**Comment by kurttu4** [comment]
> like why should I bother, go away and discuss this problem in another forum, this problem also exists in the mobile app too.
> and when a person wrote in the chat ,a window pops up in which there is no check mark

like why should I bother, go away and discuss this problem in another forum, this problem also exists in the mobile app too.
and when a person wrote in the chat ,a window pops up in which there is no check mark
