### ISSUE TITLE
Crash after copying QR code without profile picture

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#28528]
### Steps to reproduce

1. Go to Settings
2. Press QR icon
3. Disable Profile Photo switch
4. Press Copy

### Expected behaviour

QR code should be copied without any crashes

### Actual behaviour

App crashes `Assertion: "!image.isNull()" image_prepare.cpp:994`

### Operating system

Windows 11

### Version of Telegram Desktop

5.6.2

### Installation source

Static binary from official website

### Crash ID

be96f19e-e62a-4249-862f-b047ad736a01

**Comment by kotecat** [comment]
Yes, the same

**Comment by aNNiMON** [comment]
Fixed in 5eafe9652531e443e395e18db729adef13747c71
