### ISSUE TITLE
There is no way to enclose backticks codeblock with telegram backtics

### ISSUE THREAD

**Issue by gwpl** [telegramdesktop/tdesktop#28526]
### Steps to reproduce

Try to send as codeblock, a codeblock with backticks that surround blockcode by default. , it will confuse telegram where codeblocks start and end.

### Expected behaviour

There should be way to send any possible content inside codeblock.

In Markdown it's solved by surrounding codeblock section with amount of backticks that are not inside codeblock, effectively signaling parser on beginning of codeblock, with what closing section is.

### Actual behaviour

Currently it seems unsupported, therefore impossible to contain certain sequences of backticks inside codeblock.

### More examples

* #28218 

### Operating system

ArchLinux

### Version of Telegram Desktop

5.5.4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
update your telegram version before reporting bugs.
