### ISSUE TITLE
Strange display of text, signatures, in chats/channels

### ISSUE THREAD

**Issue by Dimoka113** [telegramdesktop/tdesktop#28529]
### Steps to reproduce

Write any message/send photo to chat

~~Am I the only one who finds this strange?~~
Okay, now I'm sure it's weird #28530

### Expected behaviour

Normal text display...
![image](https://github.com/user-attachments/assets/ed4094b3-9afb-451a-9f8e-fde2e97afe60)
Version 5.6.1

### Actual behaviour

![image](https://github.com/user-attachments/assets/09d91434-fc50-4e80-9301-2e860359ea21)
Version 5.6.2

### Operating system

Windows 10

### Version of Telegram Desktop

5.6.2

### Installation source

Static binary from official website

**Comment by vec715** [comment]
+1, I just got the same issue right after updating to v5.6.2

**Comment by kingleonide** [comment]
+1, how i can downgrade to older version?

**Comment by daniels1989** [comment]
+1, just looks weird now

**Comment by 0stiary** [comment]
+1, It's weird, especially when sending the message it looks okay, but when sent, brrrr (50ms difference between screenshots)
![image](https://github.com/user-attachments/assets/8ef9be6e-f8f2-4f76-b2be-e527f230bfa3) ![image](https://github.com/user-attachments/assets/47627d9a-3d7f-4eed-b5b5-e8c2824aaa33)

**Comment by AndreiZoltan** [comment]
It is awful. Now it takes **twice** as much space as it used to.
![image](https://github.com/user-attachments/assets/c7125286-cb41-437c-a309-19a351c22361)
Telegram is the slowest program on my Linux laptop and performs much worse than on Windows. After spending several minutes in other apps and then returning to Telegram, it starts lagging. Maybe instead of focusing on design tweaks, it's worth prioritizing real improvements.

**Comment by chernandezosma** [comment]
Same happen in Ubuntu 24.04 with Snap Telegram Desktop 5.6.2

![image](https://github.com/user-attachments/assets/50e212ec-31ab-44e2-9043-92f600a111d2)

**Comment by ruizlenato** [comment]
+1

**Comment by ShamHyper** [comment]
+

**Comment by john-preston** [comment]
Yeah, I'll fix it in another version later today.

**Comment by ilya-fedin** [comment]
> Telegram is the slowest program on my Linux laptop and performs much worse than on Windows. After spending several minutes in other apps and then returning to Telegram, it starts lagging.

There's no such known bug. If you really want issues to disappear, do bugreports. For slowness problems, you have to attach a CPU profiler (such as [hotspot](https://github.com/KDAB/hotspot)) report to your issue.

**Comment by D7KrAsh** [comment]
+1

**Comment by jasursadikov** [comment]
+1, on ArchLinux

**Comment by Axuba** [comment]
+1 on fedora 40, flatpak version

**Comment by arthaqs** [comment]
+1

**Comment by Aokromes** [comment]
fixed on 5.6.3
