### ISSUE TITLE
Incorrect display of multimedia on the additional

### ISSUE THREAD

**Issue by vbba1991** [telegramdesktop/tdesktop#28521]
### Steps to reproduce

I open Telegram on an additional monitor with a resolution of 2160x3840 portrait orientation
My main monitor is 1920x1080

### Expected behaviour

The image or video should open on the secondary monitor as before the last two updates

### Actual behaviour

The image or video is stretched across the main and secondary monitors
![Screenshot_1](https://github.com/user-attachments/assets/4c3eb474-8e2f-4a4c-9d31-942d612f3399)

### Operating system

Windows 10, Version 22H2 with Update [19045.5011]

### Version of Telegram Desktop

5.6.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Fixed on dev

**Comment by vbba1991** [comment]
Can I at least know when this will be published? it is impossible to work in telegram

**Comment by ilya-fedin** [comment]
I have no idea :(
