### ISSUE TITLE
[Themes] Is it possible to change "Scroll to bottom" button background?

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2852]
Correct me if I'm wrong, but "scroll to bottom" round button in history now shares its color with `windowBg` (one of main colors).
In [history.style](https://github.com/telegramdesktop/tdesktop/blob/7fb1463c43922b34b696741da536dfafce7a6469/Telegram/SourceFiles/history/history.style#L44) file there're only options to change foregound (the icon inside that button), they're present in palette as `menuIconFg` and `menuIconFgOver`. 
There's also key for button's shadow (`historyToDownShadow`), but nothing for background (default and on hover).
Am I missing something? It would be very nice to allow us change its color.

![image](https://cloud.githubusercontent.com/assets/2780044/21958829/2d8d4f06-dac8-11e6-8e60-089ca38415c6.png)

### Configuration
**Version of Telegram Desktop:** 1.0

**Comment by luckydonald** [comment]
Yes it seems. Seen that.
![image](https://cloud.githubusercontent.com/assets/2737108/21959547/a9ec0f22-daca-11e6-842d-2b997a4a6d8e.png)
Even the hover color
![image](https://cloud.githubusercontent.com/assets/2737108/21959550/b24a109c-daca-11e6-888b-6e13cc3d56d2.png)

**Comment by MasterGroosha** [comment]
@luckydonald on the first screenshot (no hover) the color of the button is changes, but it's the same as the color of the panel below. I've never seen a theme with "scroll to bottom" button having completely another color.

**Comment by john-preston** [comment]
@MasterGroosha I think they could be separated, yes.

**Comment by MasterGroosha** [comment]
This is fixed in 041e366df7aa16c498ae8ccf7171405ec20a5e70 . Thank you!
