### ISSUE TITLE
Problem with text bubbles

### ISSUE THREAD

**Issue by ShamHyper** [telegramdesktop/tdesktop#28534]
### Steps to reproduce

1. Update to last version
2. Send message

### Expected behaviour

If the message is short, then the time of the message should be displayed to the right of the text, as it was before. 
![image](https://github.com/user-attachments/assets/ad51e7f3-47ea-4e70-bb4a-bc9b897f83c3)

### Actual behaviour

At the moment, time is always at the bottom, and makes short "bubbles" of messages sloppy and cumbersome.

![Telegram_W1X0iLrxua](https://github.com/user-attachments/assets/8edbfe50-adbc-47cd-a8fa-a07cabf2dcda)
![image](https://github.com/user-attachments/assets/6eaffd7c-d37e-430d-9929-53f4585b5465)

### Operating system

Windows 10, Windows 11

### Version of Telegram Desktop

5.6.2 x64

### Installation source

Static binary from official website

### Crash ID

Not required in this case

### Logs

```shell
Not required in this case
```

**Comment by All-The-Foxes** [comment]
The same thing is happening on the Linux version of the client. I don't think the OS matters. This change is awful.

**Comment by ShamHyper** [comment]
> The same thing is happening on the Linux version of the client. I don't think the OS matters. This change is awful.
Yep, checked on kali, same problem

**Comment by ShamHyper** [comment]
Duplicate of https://github.com/telegramdesktop/tdesktop/issues/28529
