### ISSUE TITLE
After the update, sometimes the chat time is marked down and sometimes to the side, regardless of the length of the text

### ISSUE THREAD

**Issue by mandoocash** [telegramdesktop/tdesktop#28535]
### Steps to reproduce

After the update, sometimes the chat time is marked down and sometimes to the side, regardless of the length of the text

### Expected behaviour

After the update, sometimes the chat time is marked down and sometimes to the side, regardless of the length of the text

### Actual behaviour

After the update, sometimes the chat time is marked down and sometimes to the side, regardless of the length of the text

### Operating system

 Windows 11

### Version of Telegram Desktop

5.6.2x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
duplicate.
