### ISSUE TITLE
Cannot show right click send options through quick share

### ISSUE THREAD

**Issue by ThigSchuch** [telegramdesktop/tdesktop#28537]
### Steps to reproduce

1. Go to a channel
2. Quick share a message
3. Select to who you will send it
4. Right click "send button"

### Expected behaviour

v5.6.1

https://github.com/user-attachments/assets/2dcec129-c2e4-49e8-a331-1e25e5a17609

### Actual behaviour

https://github.com/user-attachments/assets/67870624-56bd-45ec-b710-77d07c34e7be

### Operating system

Linux Mint 22

### Version of Telegram Desktop

5.6.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
very likely duplicate and will be fixed today.
https://github.com/telegramdesktop/tdesktop/issues/28536

**Comment by ThigSchuch** [comment]
Ya, maybe it's related, but different behaviors between platforms.
Tried on windows, it shows up the menu, but in the left upper corner of screen and then crashes.
In my Linux it doesn't even shows up, but it doesn't crash either XD

**Comment by Aokromes** [comment]
test on 5.6.3

**Comment by ThigSchuch** [comment]
Worked, both Linux and Windows.
