### ISSUE TITLE
Linux mini apps

### ISSUE THREAD

**Issue by Goosegit11** [telegramdesktop/tdesktop#28531]
### Steps to reproduce

1. open mini app
2. Failed to create GBM buffer of size 499x766: Invalid argument
3. close mini app

### Expected behaviour

mini app showing up

### Actual behaviour

mini app doesn't show up, blank page

### Operating system

Arch Linux

### Version of Telegram Desktop

5.6.1

### Installation source

Static binary from official website

### Logs

```shell
Failed to create GBM buffer of size 499x766: Invalid argument
```

`GDK_GL=disable` helps.

**Comment by ilya-fedin** [comment]
Well and what's the point of making issue? We can't do anything about that.

**Comment by ilya-fedin** [comment]
@Goosegit11 I don't believe that, such errors are usually shared with all webkitgtk applications and come from webkitgtk-graphics drivers interaction. Thus I don't see how tdesktop could be at fault. I can't even reproduce that.

**Comment by ilya-fedin** [comment]
Also, remember that there are three versions of webkitgtk in use currently. You might use applications using other version of webkitgtk.

**Comment by Goosegit11** [comment]
well how can i test that? I tried Epiphany and it works fine

**Comment by ilya-fedin** [comment]
Check the dependencies. tdesktop prefers webkitgtk 4.1 on X11 and can fallback to webkitgtk 4.0. Epiphany uses webkitgtk 6.0 to my knowledge.
