### ISSUE TITLE
Message timestamps are always displayed on new row after updating to 5.6.2

### ISSUE THREAD

**Issue by KeterSCP** [telegramdesktop/tdesktop#28530]
### Steps to reproduce

1. Open any chat
2. Type anything
3. Look at the message timestamp

### Expected behaviour

Before v 5.6.2 message timestamps were on the same row as the message

### Actual behaviour

After v 5.6.2 message timestamps for my messages always appear on the new row:

![image](https://github.com/user-attachments/assets/a3ac7a7a-65ff-402b-af97-c1dc6724f726)

### Operating system

Windows 10 (Also the same problem on Windows 11)

### Version of Telegram Desktop

5.6.2

### Installation source

Static binary from official website

**Comment by Dimoka113** [comment]
the same #28529

**Comment by KeterSCP** [comment]
Closing, as this duplicates #28529
