### ISSUE TITLE
Missing touchbar support

### ISSUE THREAD

**Issue by marcodallago** [telegramdesktop/tdesktop#2853]
Hi guys, in the newest version is missing touchbar support for the emoticons :)

Hope you put it back as previous one, which btw was not working every time. Thanks, bye!

**Comment by stek29** [comment]
Was something emoji related changed really?

**Comment by rafus15** [comment]
More than the emoji bar i miss the suggestions which are not available on the last version  1.0.2
I Wish this could be addressed.
Thank you so much

**Comment by auchri** [comment]
QT does not support the touch bar https://bugreports.qt.io/browse/QTBUG-56908

**Comment by ArtFeel** [comment]
I think if everyone votes for this bug in the QT tracker, this feature will be implemented sooner.
✅ https://bugreports.qt.io/browse/QTBUG-56908

**Comment by smileytechguy** [comment]
It seems that touch bar support has been merged into QT: https://codereview.qt-project.org/#/c/221375/

If it is, can we re-open this issue @auchri ?

**Comment by stek29** [comment]
@smileytechguy it's Qt Creator, not Qt itself. And it's done via NSTouchBar as a platform specific code unrelated to Qt at all.
