### ISSUE TITLE
Crush after opening send option

### ISSUE THREAD

**Issue by dajotim937** [telegramdesktop/tdesktop#28532]
### Steps to reproduce

1. Open public
2. Click share buttor for a post
3. Select few chats
4. Right click at send button

### Expected behaviour

Open send menu to remove caption\sender

### Actual behaviour

Menu opens at far top-left corter of monitor and then the app is crushed.

### Operating system

Win10

### Version of Telegram Desktop

5.6.2

### Installation source

Static binary from official website

### Crash ID

Cant get crash reporter to open after crush even when beta version is enabled

**Comment by Avenred** [comment]
Also experiencing this. Here's a screenshot of the button in question which crashes the entire app when right clicked:
![Telegram_1728939688_4531](https://github.com/user-attachments/assets/a9960113-eb8b-471d-abdf-1c19c820994b)

**Comment by dajotim937** [comment]
Crash ID: b2caec24-4841-46cf-9179-61fc2ff5362e

Finally I managed to get Crash ID.
