### ISSUE TITLE
No matter the type or length of the message, sometimes the date tag appears at the very bottom.

### ISSUE THREAD

**Issue by catchmyass** [telegramdesktop/tdesktop#28538]
### Steps to reproduce

1. Go to any chat.
2. Write any message.

![resim](https://github.com/user-attachments/assets/ec7c0fab-1a32-42c7-8b6d-651336cde049)

### Expected behaviour

Having the date on the side as in the previous patch.

### Actual behaviour

No response

### Operating system

Windows 10 

### Version of Telegram Desktop

5.6.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#28529
