### ISSUE TITLE
Strange display of text in chats/channels

### ISSUE THREAD

**Issue by AndreiZoltan** [telegramdesktop/tdesktop#28547]
### Steps to reproduce

Some messages are displayed incorrectly (in a 'bubble' as in version `5.6.2`). For example, type: `ое иуии иуиуииуиуиуииуиу иуииуи иуииуииуиуииуи и?`.

### Expected behaviour

Normal text display:
![image](https://github.com/user-attachments/assets/fe04af68-0ede-474e-b332-b55571fffc9e)

### Actual behaviour

![image](https://github.com/user-attachments/assets/128b6113-d3a1-4f4e-8a28-612e7f3f7573)
Version 5.6.3

### Operating system

Ubuntu 22.04.2 LTS

### Version of Telegram Desktop

5.6.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
you say 5.6.2 and put version 5.6.3, on 5.6.3 must be fixed.

**Comment by kotecat** [comment]
![image](https://github.com/user-attachments/assets/f844e2cf-5f59-47fc-9f87-8a6c23c651af)
same

**Comment by Aokromes** [comment]
https://i.imgur.com/tLCGeM4.png

**Comment by AndreiZoltan** [comment]
> you say 5.6.2 and put version 5.6.3, on 5.6.3 must be fixed.

I may not have expressed it clearly, but what I meant is that issue #28529 is still unresolved in 5.6.3.

**Comment by AndreiZoltan** [comment]
some other examples:
![image](https://github.com/user-attachments/assets/b505398e-5112-4383-8609-3d1f4bbe5a70)
`long long long long long long long long long long long long`
![image](https://github.com/user-attachments/assets/246d722c-6f6d-4fc5-853c-ac4588d730f4)
`pfpp ndj. ,tpjndtncndtyyjcnm ljk;ty hfcgkfxb dv dfnmcz fd?`

**Comment by Dimoka113** [comment]
![image](https://github.com/user-attachments/assets/5f8ae8ae-aa8f-4c24-817a-541de694eacf)
No matter how hard I try, everything looks right.

**Comment by Dimoka113** [comment]
And I don’t quite understand what the problem is specifically in your screenshots?

p.s If you are talking about the transfer, which is in the "Actual behavior", then this should be the case, because otherwise the text will overlap the date

Although maybe I'm wrong

**Comment by AndreiZoltan** [comment]
> p.s. If you are talking about the transition that you have in the photo to “Actual behaviour”, then this is how it should be, because the text can overlap the date.

Thank you for the clarification! I understand now that the text lifting is intentional, and that’s how it should be. I appreciate the explanation.
