### ISSUE TITLE
Telegram Desktop 5.6.3.0 on Windows 10 unexpectedly closes

### ISSUE THREAD

**Issue by lospejos** [telegramdesktop/tdesktop#28549]
### Steps to reproduce

1. Wait some time, let Windows lock screen appears
2. Login to system
3. Telegram is closed unexpectedlty

### Expected behaviour

Telegram not closes unexpectedly after login in lock screen.
Telegram started closing unexpectedly after updating to version 5.6.3.0, previous version has no such bug.

### Actual behaviour

Telegram closes unexpectedly after logon to lock screen

### Operating system

Windows 10 IoT Enterprise LTSC 22H2 build 19045.4894

### Version of Telegram Desktop

5.6.3.0

### Installation source

Static binary from official website

### Logs

```shell
Since I'm not sure log and crash files not contain sensitive/private information I'd rather not put them here, sorry.
```

**Comment by ilya-fedin** [comment]
Provide a crash ID

**Comment by lospejos** [comment]
> Provide a crash ID

After Telegram crashes and I start a new Telegram instance, some small window appears on a very short period of time. It seems that it contains text, something like _"Previous program run was finished incorrectly"_ or something like that - I'm not sure, this window is generally displaying on a very short period of time, so I just can't read this fully.

I see description in creating new issue:

> If you're reporting a `crash`, please enter the crash ID from the crash reporter opening on the next launch after crash. **You have to enable beta versions installation in `Settings -> Advanced` for the reporter to appear.** You don't have to wait for a beta version to arrive.

I'll enable beta versions installation, wait for next crash and try to send Crash Id

**Comment by lospejos** [comment]
> Provide a crash ID

Crash ID: c2cf740c-f46b-40d3-bda0-99e06a266915

ApiId: 2040
Binary: Telegram.exe
Launched: 17.10.2024 15:40:37
OpenGL ANGLE: Auto
OpenGL Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Ti Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11-32.0.15.6590)
Platform: Windows64Bit
UserTag: a15ba75bb64f0f12
Version: 5006003
Memory-usage: 900 MB (peak), 624 MB (current)
Pagefile-usage: 1009 MB (peak), 717 MB (current)

Google Breakpad caught a crash, minidump written in thread 15724
Minidump: c2cf740c-f46b-40d3-bda0-99e06a266915

**Comment by lospejos** [comment]
> Provide a crash ID

Crash ID: 889b1b7a-ba0a-4689-b037-da8b3590fcd7

ApiId: 2040
Binary: Telegram.exe
Launched: 18.10.2024 10:14:05
OpenGL ANGLE: Auto
OpenGL Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Ti Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11-32.0.15.6590)
Platform: Windows64Bit
UserTag: a15ba75bb64f0f12
Version: 5006003
Memory-usage: 903 MB (peak), 752 MB (current)
Pagefile-usage: 953 MB (peak), 815 MB (current)

Google Breakpad caught a crash, minidump written in thread 13348
Minidump: 889b1b7a-ba0a-4689-b037-da8b3590fcd7

**Comment by spaceVpn** [comment]
I have the same problem.
"After Telegram crashes and I start a new Telegram instance, some small window appears on a very short period of time."
"previous Telegram Desktop launch was not finished properly"
[log.txt](https://github.com/user-attachments/files/17487106/log.txt)
[dumps.zip](https://github.com/user-attachments/files/17487143/dumps.zip)
[Link to video tg crash](https://youtube.com/shorts/8zJ0o7j2MLU)
[report.telegramcrash.txt](https://github.com/user-attachments/files/17487211/report.telegramcrash.txt)

**Comment by ilya-fedin** [comment]
@lospejos no, that's if no help, a valid crash id is needed

**Comment by lospejos** [comment]
Also additional information: on my second external display I changed resolution setting from 125% to 100%, and after that it seems this error is not appearing anymore. I'm pretty sure on 95% this was the case. My be it will help others to fix this issue.

**Comment by ilya-fedin** [comment]
If you want the issue to get solved, please provide a crash id of a sent report.
