### ISSUE TITLE
History (ver 1.0) NOT COMPATIBLE with previous versions. Can't rollback, all history lost.

### ISSUE THREAD

**Issue by KarelWintersky** [telegramdesktop/tdesktop#2854]
### Steps to reproduce
1. Update to latest version (v 1.0)
2. Launch. 
3. Close app, rollback executable file to version 10.20
4. Launch app again.
5. ...
6. WTF? Where is my history?

### Expected behaviour
Backward compatibility **needed**.

### Actual behaviour
New version makes all history unaccessible with previous versions. 

### Configuration
Win7x64

**Version of Telegram Desktop:**
10.20 VS 1.0

**Comment by john-preston** [comment]
@KarelWintersky This is not about version 1.0, from the very start for more than three years if you launch an older version with the data files of a newer version they're not used.

All the new versions read the data from any of the old versions, but not vice versa.

**Comment by KarelWintersky** [comment]
> but not vice versa.
bad idea :(

**Comment by john-preston** [comment]
@KarelWintersky Why do you need that anyway? Pointless in my opinion.

**Comment by andreymal** [comment]
@john-preston because new design is bad, of course :) I also downgraded 1.0 to 0.10.20. I think it's possible to add some compatibility flag in data (version of data format?)

However, it is too late now.

**Comment by john-preston** [comment]
@andreymal There is no real data stored, only auth and cache, so if you need to downgrade once, you just log in again and that's all the problem.

Ok, you add a version of data and it changes and you can't use new data files in old version anyway.

**Comment by KarelWintersky** [comment]
damned rounded corners :(

**Comment by Thoufak** [comment]
> @KarelWintersky This is not about version 1.0, from the very start for more than three years if you launch an older version with the data files of a newer version they're not used.
> 
> All the new versions read the data from any of the old versions, but not vice versa.

Hi. I would like to read the cached phone number from the tdata created in the newer version. Is that possible? I'm trying to catch it in the localstorage.cpp at line "case dbiLoggedPhoneNumber", but it appears to be an empty string. The tdata is valid and authorized (I can open it with a newer version).
