### ISSUE TITLE
Incorrect display of message selection checkbox. Covers large messages.

### ISSUE THREAD

**Issue by bouledepate** [telegramdesktop/tdesktop#28545]
### Steps to reproduce

select a couple of messages, including large message.

### Expected behaviour

Correct display of message selection. They should not overlap large messages with text, and should not be located in the center.

### Actual behaviour

Checkboxes overlap text. Example in the image.

![image](https://github.com/user-attachments/assets/bc259307-1cb3-4e48-a7bf-e9cb69e9b644)

### Operating system

Ubuntu 24.04

### Version of Telegram Desktop

5.6.3

### Installation source

Snap

**Comment by Aokromes** [comment]
> These checkboxes look weird. Are they supposed to be there?

yes, other  telegram appliations have them for color blind people.

**Comment by Dimoka113** [comment]
![image](https://github.com/user-attachments/assets/0967772d-78bf-43a0-b88d-77038eb491a1)

Strange, everything displays fine for me...
Perhaps it's only the Ubuntu version

**Comment by Dimoka113** [comment]
![image](https://github.com/user-attachments/assets/ed8b297d-9eda-49af-b964-dac7f00c22a7)
Indeed, if you expand the telegram to full screen, you will get this

**Comment by Dimoka113** [comment]
> Previously, these checkboxes were less noticeable. Now they are in the center of the screen and attract a lot of attention, it is a little annoying. Is it possible to disable? Or roll back this change. In previous versions, this was not the case. It all started with 5.6.2, where the problem was initially in the message form, but it was fixed, and now this has popped up.

These flags did not exist at all before. Regarding visibility, I would say that perhaps they are really too big, but they are not that noticeable.

**Comment by Dimoka113** [comment]
I think we can close the problem, because it was fixed in 5.6.4

![image](https://github.com/user-attachments/assets/c9f7a54c-228a-4d80-a207-7d4c99442bfe)
