### ISSUE TITLE
Incorrect display of the message time

### ISSUE THREAD

**Issue by rpo6oBLLjuk** [telegramdesktop/tdesktop#28542]
### Steps to reproduce

1. Write any short message (1 character)
2. View this message (both on your own behalf and on behalf of the interlocutor in this chat)

### Expected behaviour

Normally, with a small message size (if its last character on the last line does not reach the border of the time widget), the time should be shown on the same line as the end of the message is written.
Your messages:![image](https://github.com/user-attachments/assets/0d1340cf-98eb-4d57-86e9-fa73295b2d05)
Other people's messages:![image](https://github.com/user-attachments/assets/b3849757-828b-4aa8-a075-dab9de2a75b2)

### Actual behaviour

In fact, the timer adds a line for itself.
Your messages:![image](https://github.com/user-attachments/assets/4a5d5d24-4024-4ac3-8cf3-f77578ab1130)
Other people's messages:![image](https://github.com/user-attachments/assets/6bc9e3bb-0b5b-4a53-95d3-3c32df8c6dff)

### Operating system

Windows 11 (22H2)

### Version of Telegram Desktop

5.6.2 x64

### Installation source

Static binary from official website

**Comment by rpo6oBLLjuk** [comment]
In addition, sometimes the timer also pushes back the text of the message (yours):
![image](https://github.com/user-attachments/assets/2a7b01a6-8e3e-4356-8dd1-5da70913d47c)

**Comment by ilya-fedin** [comment]
#28529
