### ISSUE TITLE
[Snap version] The theme preferences inherited by Telegram Desktop doesn't match the one set for other Snaps

### ISSUE THREAD

**Issue by kurtbahartr** [telegramdesktop/tdesktop#28543]
### Steps to reproduce

1. Install Telegram Desktop as a Snap (`sudo snap install telegram-desktop`)
2. Launch the installed app and optionally set it up
3. Enable "Use Qt window frame"

### Expected behaviour

The inherited appearance preferences is consistent with other Snaps.

### Actual behaviour

The inherited theme and icon pack are Adwaita regardless of the preferences set.

I assume adding an Interface for `content[gnome-42-2204]` just like Firefox, Thunderbird and the likes do for example should fix this. If Qt is strictly needed, then going for `content[qt515-core20]` just like WhatSie should also do just fine.

### Operating system

Ubuntu 24.10 "Oracular Oriole" GNOME 47 Wayland

### Version of Telegram Desktop

5.6.2

### Installation source

Snap

**Comment by ilya-fedin** [comment]
As you could notice, that's a "Use Qt window frame" option, not "Use Firefox window frame" "Use Thunderbird window frame". It has nothing to do with firefox or thunderbird. That's what Qt provides, not under tdesktop control and thus bug reports about it not accepted here (you can address them to Qt instead). If you want tdesktop to manage your window frame and be served by tdesktop bugtracker, DON'T enable this option.
