### ISSUE TITLE
Reading verification from other users in groups has stopped being displayed.

### ISSUE THREAD

**Issue by Jafarelsabir** [telegramdesktop/tdesktop#28544]
### Steps to reproduce

1. In the **right-click options** on each message, **the reading verification of messages from other users,** in groups with visual representation in topics mode, has stopped being displayed with the last two updates.

### Expected behaviour

I could usually see if other participants were active, so without receiving a reply it was reassuring to see that my message had been read. With the previous two updates this is no longer possible. Curiously a couple of older messages do allow viewing, but apparently only from those who reacted with an icon.

### Actual behaviour

The reading verification of messages from other users in groups has stopped being displayed.

### Operating system

macOS 15.0.1

### Version of Telegram Desktop

5.6.3

### Installation source

Static binary from official website

**Comment by Jafarelsabir** [comment]
A couple of minutes ago I had the opportunity to check this. It turns out that the “limitation/error” also occurs on the mobile device, that is, in the cell phone app.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by Jafarelsabir** [comment]
> platform wide bugs / requests belongs to https://bugs.telegram.org/

Oh, I'm sorry. It would be great if you could please consider it. I've taken a big step in mentioning the situation here. Thank you, have a nice day.

**Comment by Aokromes** [comment]
> > platform wide bugs / requests belongs to [bugs.telegram.org](https://bugs.telegram.org/)
> 
> Oh, I'm sorry. It would be great if you could please consider it. I've taken a big step in mentioning the situation here. Thank you, have a nice day.

i am not telegram llc company staff, i only maintain bug tracker cleaner.
