### ISSUE TITLE
Missing CTRL+A/CTRL+E shortcuts on macOS

### ISSUE THREAD

**Issue by chris54721** [telegramdesktop/tdesktop#2855]
### Steps to reproduce
1. Focus the message textbox and write something
2. CTRL+A/CTRL+E to move cursor to start/end don't work

### Expected behaviour
When using the CTRL+A shortcut in a textbox in macOS, the cursor moves to the start (without selecting text like in Windows). Same for CTRL+E which moves it to the end.

### Actual behaviour
The above shortcuts do nothing.

### Configuration
**Operating system:** macOS Sierra 10.12.2

**Version of Telegram Desktop:** 1.0

**Comment by luckydonald** [comment]
Wow. I never knew that shortcut.
But as a workaround you could use the arrow keys <kbd>cmd</kbd>+<kbd>⬅</kbd> and <kbd>cmd</kbd>+<kbd>➡</kbd>

**Comment by chris54721** [comment]
I didn't know this one either! Though it would be great to have both.
In Telegram for macOS (the native app) you can also scroll through chats with cmd+opt(?)+arrows.

**Comment by john-preston** [comment]
@chris54721 You can try Ctrl+Tab / Ctrl+Shift+Tab.

**Comment by chris54721** [comment]
@john-preston Thank you! Still, it would be nice to have both available, since I'm used to the OS defaults and probably won't use these workarounds much.

**Comment by Aokromes** [comment]
#1060 ?
