### ISSUE TITLE
Crush in a channel with subtopics when Right-clicking above the input line

### ISSUE THREAD

**Issue by kris-piece** [telegramdesktop/tdesktop#28552]
### Steps to reproduce

1. Go to the Channel subtopic
2. Right-click above the input line (approximately 1-5 pixels)

### Expected behaviour

Opens the interaction menu with the message that you right-clicked on

### Actual behaviour

When right-clicking on the input line in one of the Channel topics Telegram crashes

### Operating system

Win10

### Version of Telegram Desktop

5.6.3

### Installation source

Static binary from official website

### Crash ID

3817dc2d-e6e3-4905-84f7-427513503f6d

### Logs

```shell
[2024.10.18 18:49:48] RPC Error: request 79 got fail with code 400, error PEER_ID_INVALID
[2024.10.18 18:49:52] Assertion Failed! "ptr_ != nullptr" pointers:98
```

**Comment by Aokromes** [comment]
plz enable beta, restart telegram and send crash id on next start and post id here.

**Comment by kris-piece** [comment]
@Aokromes crash ID added

**Comment by john-preston** [comment]
@kris-piece I hope I've fixed that one, thanks.
