### ISSUE TITLE
How to modify the Telegram source code to use my own server address instead of the official Telegram servers without using a proxy?

### ISSUE THREAD

**Issue by kinwe** [telegramdesktop/tdesktop#28550]
### Is your feature request related to a problem?

How to modify the Telegram source code to use my own server address instead of the official Telegram servers without using a proxy?

### Describe the solution you'd like

How to modify the Telegram source code to use my own server address instead of the official Telegram servers without using a proxy?

### Describe alternatives you've considered

I want to connect through an MTProto proxy, but it's not very convenient. Where can I modify the connection address

**Comment by Aokromes** [comment]
it belongs to you.
