### ISSUE TITLE
Instantview doesn't consider RTL direction in desktop

### ISSUE THREAD

**Issue by aminmesbahi** [telegramdesktop/tdesktop#28551]
### Steps to reproduce

The same link points to an RTL direction page on mobile (Android and iOS), which looks correct as an **instant view** but renders as LTR on desktop app.

Desktop:
![image](https://github.com/user-attachments/assets/fa170308-792a-4fdd-aa9c-1777d0256108)

Mobile:
![image](https://github.com/user-attachments/assets/550137a3-8044-4973-8608-5d0981a9507f)

### Expected behaviour

Renders RTL page correctly, same as a mobile app.

### Actual behaviour

It doesn't consider dir=rtl in the desktop app.

### Operating system

Windows 11

### Version of Telegram Desktop

5.5.5 x86

### Installation source

Microsoft Store

**Comment by john-preston** [comment]
Can you please provide the exact link where I can see that?

**Comment by aminmesbahi** [comment]
Sure, 

[this is a telegraph example](https://telegra.ph/%DA%86%D8%B1%D8%A7-%D8%AA%DB%8C%D9%85-%D9%85%D8%A7%DB%8C%DA%A9%D8%B1%D9%88%D8%B3%D8%A7%D9%81%D8%AA-%D8%A7%D8%AC-%D8%AF%D8%B1-%D8%AD%D8%A7%D9%84-%D8%AC%D8%A7%DB%8C%DA%AF%D8%B2%DB%8C%D9%86%DB%8C-React-%D8%A8%D8%A7-%D9%88%D8%A8-%DA%A9%D8%A7%D9%85%D9%BE%D9%88%D9%86%D9%86%D8%AA%E2%80%8C%D9%87%D8%A7-%D9%87%D8%B3%D8%AA%D9%86%D8%AF-10-16)

and 

[this one is based on wordpress's plugin](https://mesbahi.net/fa/blog/1403/07/25/%da%86%d8%b1%d8%a7-%d8%aa%db%8c%d9%85-%d9%85%d8%a7%db%8c%da%a9%d8%b1%d9%88%d8%b3%d8%a7%d9%81%d8%aa-%d8%a7%d8%ac-%d8%af%d8%b1-%d8%ad%d8%a7%d9%84-%d8%ac%d8%a7%db%8c%da%af%d8%b2%db%8c%d9%86%db%8c-react/)

**Comment by john-preston** [comment]
@aminmesbahi Ok, thanks, I'll try to add huge amount 'dir="auto"' attributes and we'll see. It looks like that's the way Telegraph does it.
