### ISSUE TITLE
Finish the dark telegram theme at last, it's hard to work. It's tiring.

### ISSUE THREAD

**Issue by korenevskiy** [telegramdesktop/tdesktop#28566]
### Is your feature request related to a problem?

I am tired of the Telegram Desktop program. The  Unigram is slightly better. I'm asking the developers. make improvements to remove problems. Compared to Whatsapp, Telegram is the worst. Please make it at least a little bit like Whatsapp. And this is not due to habit, it is due to the fact that Whatsapp programmers understand UI better. 
1. Make the numbers of new messages in the circle green (in dark theme). In the white theme, the numbers are in a blue circle, Great. And in the dark it is difficult to focus their attention.
2. Make the names of the chat names in the list bolder text (in dark theme). In the white theme, the chat names are well highlighted, excellent. In a dark topic, chat names are poorly highlighted, it is difficult to focus attention.
3. Make the chat center aligned, just like Whatsapp. (but only my messages are on the left, and chat messages are on the right. I.e. the opposite than in Whatsapp) 
___________________________________________________________________
меня утомляет программа Telegram Desktop. Программа Unigram чуть лучше. Я прошу разработчиков. внести улучшения чтобы убрать проблемы. По сравнению с Whatsapp Telegram хуже всего. Прошу Вас сделайте хоть чуть чуть похожей на Whatsapp. И это не связано привычкой, это связано с тем что программисты Whatsapp лучше понимают в UI. 
1. Сделайте цифры новых сообщений в кружочке зелёными. (тёмной теме)
2. Сделайте имена названия чатов в списке более жирным текстом (тёмной теме).
3. Сделайте выравнивание чата по центру, так же как Whatsapp. (но только мои сообщения слева, а сообщения чата справа. Т.е. наоборот чем в Whatsapp)

### Describe the solution you'd like

described above

### Describe alternatives you've considered

described above

**Comment by ilya-fedin** [comment]
> 1. Make the numbers of new messages in the circle green (in dark theme). In the white theme, the numbers are in a blue circle, Great. And in the dark it is difficult to focus their attention.

You can configure the color in Settings -> Chat Settings

> 3\. Make the chat center aligned, just like Whatsapp. (but only my messages are on the left, and chat messages are on the right. I.e. the opposite than in Whatsapp)

That doesn't sound related to the dark theme and it's configurable, too ("Use adaptive layout for wide screens").

> 2\. Make the names of the chat names in the list bolder text (in dark theme). In the white theme, the chat names are well highlighted, excellent. In a dark topic, chat names are poorly highlighted, it is difficult to focus attention.

Hm, that might be a bug of the underlying toolkit (Qt). Maybe it does something wrong with gamma or stem darkening...

**Comment by ilya-fedin** [comment]
IMO it is better to close this bug report and have separate bug reports for each thing. @Aokromes

**Comment by korenevskiy** [comment]
> You can configure the color in Settings -> Chat Settings

I don't see this setting. There is a general theme design. then I don't see the number of new messages to make a bright circle. Send a screenshot of this setting

**Comment by ilya-fedin** [comment]
Right, it follows the accent color and you select accent color whatever you want

**Comment by korenevskiy** [comment]
Why are you closing the problem? 
After all, changing the accent does not solve my problem. 
Read the problem carefully!!!
It is required that in the night theme, the number of unread messages is displayed in a bright color (green), all other fields should be displayed in a dark accent light according to the selected theme.

**Comment by ilya-fedin** [comment]
This issue tracker is unofficial and the designer doesn't read issues here so there's no point in having an issue about colors here.

**Comment by ilya-fedin** [comment]
Use Settings -> Ask a question in the app
