### ISSUE TITLE
Auto Night mode doesn't work on Arch Plasma

### ISSUE THREAD

**Issue by ItachiSan** [telegramdesktop/tdesktop#28564]
### Steps to reproduce

1. Install Telegram Desktop from the official repos: `sudo pacman -S telegram-desktop`
2. Login, setup Telegram Desktop
3. Enable Auto Night mode

### Expected behaviour

When I update the night mode via e.g. Yin Yang or Plasma's night light triggers, Telegram Desktop should switch to dark mode.

### Actual behaviour

The mode does not switch.

### Operating system

ArchLinux with Plasma 6.2.1, KDE FW 6.7.0, QT 6.8.0

### Version of Telegram Desktop

5.6.3 (repos)

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
I don't honestly know what Yin Yang is and I'm not sure night light should trigger the change. To my knowledge, plasma trigger color scheme event only when you change color scheme, according to https://invent.kde.org/plasma/plasma-integration/-/commit/ad0e165fafd7852b8f53ecb9b0f57a0bf83d522a.

**Comment by ilya-fedin** [comment]
Ah, and it seems the commit is not in any tag so perhaps plasma doesn't support that in any released version so you have to wait or cherry-pick the commit.

**Comment by ilya-fedin** [comment]
I just tried to enable night light and no application changed to night mode, only colors became more yellow

**Comment by ItachiSan** [comment]
I see, it is great you mentioned the commit; hopefully all apps will properly switch when implemented. :smile: 
Yin Yang does change the color scheme, so I guess that will work in the future with Telegram Desktop

**Comment by ilya-fedin** [comment]
That's weird then... It should work. What does `busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings Read ss org.freedesktop.appearance color-scheme` return when Yin Yang changes color scheme? Does the bug happen if you change color scheme manually via Plasma settings?

**Comment by ilya-fedin** [comment]
Nice
