### ISSUE TITLE
telegram apps clipboard bug

### ISSUE THREAD

**Issue by doontp** [telegramdesktop/tdesktop#28560]
### Steps to reproduce

1 copy text to clipboard
2 launch telegram app
3 try to paste

### Expected behaviour

it should be pasted, but telegram app doesnt see clipboard

### Actual behaviour

it ignores clipboard from not in this telegram app, if i write something in that app and copy i can paste text only in app

### Operating system

Ubuntu 24.04.1 LTS x86_64

### Version of Telegram Desktop

5.6.3

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Can't reproduce
![](https://github.com/user-attachments/assets/471cf78a-d851-4ca0-8a7b-33e4a8984b73)

**Comment by doontp** [comment]
https://github.com/user-attachments/assets/b6863d97-1bb3-4c1a-bb51-97924e4eaf2f

**Comment by ilya-fedin** [comment]
A very bad issue description I would say. Duplicate, see #25126.
