### ISSUE TITLE
Scale always bigger in Primiary Monitor even with same scale and DPI in Win 11

### ISSUE THREAD

**Issue by mechcalvin** [telegramdesktop/tdesktop#28563]
### Steps to reproduce

Multiple monitors setup
SAME monitors
SAME display scale in windows 11
SAME dpi

### Expected behaviour

the scale in telegram desktop do not change

### Actual behaviour

1. Set telegram scale in primary monitor to 150%, it will auto reduce to 100% when move to other monitors
2. Set telegram scale in secondary monitor to 150%, it will auto increase to 225% when moved to primary monitor
3. tried "enable precise high dpi scaling" doesn't help

### Operating system

Win 11 23H2

### Version of Telegram Desktop

5.6.3 X64

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Provide the logs as instructed when creating issue
