### ISSUE TITLE
Error: WebView has crashed

### ISSUE THREAD

**Issue by 3xploiton3** [telegramdesktop/tdesktop#28569]
### Steps to reproduce

1. https://t.me/PremiumBot
2. /start
3. pay
4. Error: WebView has crashed

### Expected behaviour

success

### Actual behaviour

![image](https://github.com/user-attachments/assets/f1cd7929-f302-492b-bda5-47519cefee77)

### Operating system

ArchLinux

### Version of Telegram Desktop

5.6.3

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/28559
