### ISSUE TITLE
Nord Thread Protection reports V5.6.3 as malware on Windows 11

### ISSUE THREAD

**Issue by lacostenycoder** [telegramdesktop/tdesktop#28562]
### Steps to reproduce

1. Install Telegram Desktop v5.6.3
2. Install Nord VPN
3. Enable Threat Protection Pro

### Expected behaviour

Not to report Telegram as malware. 

### Actual behaviour

Reports maleware with Severity level: High

![image](https://github.com/user-attachments/assets/5fa59da1-ca47-4691-99e7-dda97e608261)

### Operating system

Windows 11 version 23H2 (OS Build 22631.4317)

### Version of Telegram Desktop

5.6.3 x64

### Installation source

Static binary from official website

**Comment by leandrocunha526** [comment]
Here this version doesn't even connect to the internet anymore and I've already tried a previous version and nothing on Windows 11 24H2.

**Comment by Aokromes** [comment]
false positive, report to nord.

**Comment by leandrocunha526** [comment]
Really, false positive.

**Comment by Aokromes** [comment]
> Really, false positive.

you can check source code and compile yourself to test.
