### ISSUE TITLE
Voice Chat Admins are unable to remove Private Channels from a Group Voice Chat

### ISSUE THREAD

**Issue by its-your-invi** [telegramdesktop/tdesktop#28561]
### Steps to reproduce

1. Join a group voice chat with a public channel
2. Immediately edit the channel to private channel in channel settings
3. Now Voice Chat Admins of the group are unable to remove the channel from the voice chat by Remove button.

### Expected behaviour

That Private channel should be removed.

### Actual behaviour

Remove button doesn't respond and also that Private Channel won't be removed from the Group Voice Chat.

### Operating system

Windows 11 x64

### Version of Telegram Desktop

5.6.3 x64

### Installation source

Static binary from official website

**Comment by its-your-invi** [comment]
> what about on android / ios?

Yes, In Android and ios it's same as desktop.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
