### ISSUE TITLE
TG not recognizing standard microphone

### ISSUE THREAD

**Issue by austrargentina** [telegramdesktop/tdesktop#2856]
I have the following problem which is connected to the built-in microphone:

Whenever I start Telegram it takes 3 minutes to start up. If I check dependencies on Taskmanager it shows a waiting position for the **Windows Audio Service called Audiosrv**. 
If I kill this service, Telegram starts up automatically. But then it is not possible to send any voice messages.

**If I plug in an external microphone, Telegram starts up immediately,** offering the possibility to send voice messages.

**Skype recognizes the standard microphone, just Telegram does not.** 

I read all the related topics, but there are no solutions yet. Probably an option to select audio input would fix the problem.

Any hints on that topic?

Thanks in advance,

Daniel

**Comment by Aokromes** [comment]
#784 ?

**Comment by austrargentina** [comment]
Its that same thread I read over and over. Just wanted to open a new thread to sho importance. 
Probably doesnt make sense to keep reundance to zero.
Thanks, closed the topic!
