### ISSUE TITLE
Topic icons not changing when simultaneously changing the topic name

### ISSUE THREAD

**Issue by peedrr** [telegramdesktop/tdesktop#28572]
### Steps to reproduce

1. Edit topic name and **simultaneously change the topic icon**
2. Edit a different topic, but only change the icon

Notes: 

1. I changed the topic names and/or icons on the Android app. 
2. I'm on NixOS so the binary was built from the GitHub source in this repo (as per [this nix file/procedure](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/instant-messengers/telegram/telegram-desktop/default.nix) ) so I selected _Other (unofficial) source_ below, however it's obviously one of the most 'official' sources ;) ! If someone using one of the listed, "official" sources of Desktop Linux wants to check the behaviour, I'll happily add you to the group to take a look.

### Expected behaviour

Topics should show the newly selected icons on all of Telegram's platforms.

### Actual behaviour

Only the topics for which I **didn't simultaneously change the name** show the updated icons on the Linux desktop app. All others show the default speech bubble thingy containing the first letter of the topic. (New topic names **and icons** are correctly showing on Android)

Linux desktop:
![linux](https://github.com/user-attachments/assets/b2d8729d-713e-4264-8388-2d069375ab14)

Android:
![Android](https://github.com/user-attachments/assets/8f62e4f7-100a-410c-a06e-a421d9f6f3d5)

### Operating system

NixOS 24.11, GNOME 46.4

### Version of Telegram Desktop

5.6.3

### Installation source

Other (unofficial) source

**Comment by john-preston** [comment]
What app do you change the icon from? I tried from Android, I've seen the described behavior, but in reality the icon wasn't changed on the server and only the android app which was making the change was showing the new icon, another devices, including an iOS device nearby and TDesktop didn't show the new icon, because it wasn't changed.

**Comment by john-preston** [comment]
But in case I change the icon and the title from a different app, for example from iOS app or from TDesktop app, different copy of TDesktop app will show correctly both changes - to the icon and to the title - because they were really made, on the server.

**Comment by peedrr** [comment]
Yes, changes were made from Android. 

So you're implying that the bug is within the Android app? It only makes the change locally and not on the server?

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by john-preston** [comment]
@peedrr Yes, correct. I tried to report that to the Android developer. This isn't an API issue, but this isn't a Telegram Desktop issue, it is an Android app issue.

**Comment by peedrr** [comment]
> it is an Android app issue.

So you're confident it relates only to Android and is not "system-wide" as suggested by @Aokromes?

Also when you say "reported", is there now an existing, open issue on gh?

**Comment by john-preston** [comment]
@peedrr I'm sure this is an Android bug, because when you change the same from iOS or TDesktop it works as expected.

I've sent a message to the developer and asked him if he'd fix that. Opening a bug report on bugs.telegram.org won't hurt anyway.

**Comment by Aokromes** [comment]
https://t.me/tgbetachat/1992946
fixed on 11.3.0 android beta.
