### ISSUE TITLE
Text capitalization as button and action captitions

### ISSUE THREAD

**Issue by fluidpanda** [telegramdesktop/tdesktop#2857]
In an older versions of Telegram we'd normal button captions in Channel Mute/Unmute buttons, and Back, Share, Edit, and Delete in a profile window. But now in newer version of Telegram we've these MUTE, UNMUTE, BACK, SHARE, EDIT, and DELETE. I like the older version more, what do you guys think about it?

![01](https://cloud.githubusercontent.com/assets/11980517/21964528/94be5ce2-db5e-11e6-81df-f8e52fde09b5.png)

![02](https://cloud.githubusercontent.com/assets/11980517/21964529/97417aa8-db5e-11e6-81ff-264106dbfec3.png)

![03](https://cloud.githubusercontent.com/assets/11980517/21964530/99348062-db5e-11e6-9449-c157fb943522.png)

![04](https://cloud.githubusercontent.com/assets/11980517/21964531/9bd54a0e-db5e-11e6-8309-e1e86373d59d.png)

**Comment by john-preston** [comment]
@fluidpanda You see the old SEND MESSAGE button, it just wasn't consistent. Button text is upper case in the design guidelines we follow, sorry.

**Comment by fluidpanda** [comment]
@john-preston well, hope it will never happen to ios app

**Comment by stek29** [comment]
I guess it won't, because it's following another design guidelines.
Also, what about closing this?
