### ISSUE TITLE
[Feature] Monospaced font ignores font family settings?

### ISSUE THREAD

**Issue by Dmitresso** [telegramdesktop/tdesktop#28587]
I have ClearType turned off on Windows 10, and 100% scale chat looks clear without [font patching](https://github.com/telegramdesktop/tdesktop/issues/7480#issuecomment-717243482) after update added "Settings -> Chat Settings -> Font family" setting but text supposed to be monospaced ignores settings and application uses embedded font
![изображение](https://github.com/user-attachments/assets/fe83168a-08d3-41b0-88a0-beab92014585)

I suggest inserting one more "Font family" field especially for monospaced text
Maybe introduce a checkbox "Use alternate font for monospace" for selection between embedded and chosen one.

Windows 10 21H2
Telegram 5.6.3 x64

**Comment by ilya-fedin** [comment]
> but text supposed to be monospaced ignores settings

If it will respect it then it will become non-monospace which doesn't look expected at all.

> and application uses embedded font

That's false, it uses system monospace font (Cascadia Code).

**Comment by Aokromes** [comment]
#90
