### ISSUE TITLE
Duplicated icon in Plank

### ISSUE THREAD

**Issue by jonathanhernndez** [telegramdesktop/tdesktop#2858]
If I add a launcher for Telegram in Plank, and then I open it, I get duplicated icons, one normal and one very low res (which is the actual Telegram window and dissapears when I close it). 

![Screenshot](https://cloud.githubusercontent.com/assets/16050351/21964856/37a534a6-db2a-11e6-9287-4473082570a0.png)

I tried adding `StartupWMClass=Telegram` and `StartupWMClass=TelegramDesktop` to the launcher file, but it didn't work (Google Chrome used to have this exact same problem, and the fix was to add the `StartupWMClass` field to the launcher file).

Debian 8.7 (jessie) i686, Xfce, Plank 0.11.3 (built from source), Telegram Desktop 1.0.

**Comment by jonathanhernndez** [comment]
Nevermind, after a few reboots and testing with and without the fix, I realized it's working perfectly now, without adding anything. I guess Plank didn't load the launcher file correctly the first times. I guess this issue can be closed then.

**Comment by Aokromes** [comment]
You can close the tickets you open without need of staff.

**Comment by harrypujols** [comment]
![plank](https://cloud.githubusercontent.com/assets/1799480/24589672/6c1281a8-17ac-11e7-8bf5-42d295ce45b8.png)
Just in case, I ran into this same issue today and found this thread. Perhaps you may want to take a second look at it.

**Comment by auchri** [comment]
@harrypujols The .desktop file got updated in one of the recent updates, maybe this is related to it: #3109
