### ISSUE TITLE
High RAM usage 

### ISSUE THREAD

**Issue by stmp13** [telegramdesktop/tdesktop#28581]
### Steps to reproduce

The app store app consumes a maximum of 1gb of RAM, the desktop version about 2-3gb, but its advantage is the fact that you can make a portable version

### Expected behaviour

is it possible to fix the high RAM consumption for the desktop version?

### Actual behaviour

 desktop version consumes 2-3gb RAM

### Operating system

mac os 15 

### Version of Telegram Desktop

5 6 3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Translate the titlle to English and specify steps to reproduce (as just starting the application is clearly not enough for issue to appera)

**Comment by stmp13** [comment]
> Translate the titlle to English and specify steps to reproduce (as just starting the application is clearly not enough for issue to appear)
It's my first time on github, I don't know how things work here, so I apologize in advance if I've done something wrong

As far as I understand, telegram loads all the gifs and animated stickers into RAM, and if you leave it overnight it just unreasonably starts to grow to about 2.5 gb of RAM consumption 

Everything happens exactly on mac computer with apple silicone processor (tested on mac mini m2 and macbook air m1)

**Comment by ilya-fedin** [comment]
> As far as I understand, telegram loads all the gifs and animated stickers into RAM, and if you leave it overnight it just unreasonably starts to grow to about 2.5 gb of RAM consumption

Just close the chat and all media will be unloaded

**Comment by ilya-fedin** [comment]
I'll repeat: please specify steps to reproduce in the issue like
```
1. Do that
2. Do another thing
3. Do yet another thing
```
What should lead for issue to appear. Otherwise issue validity couldn't be checked.

**Comment by stmp13** [comment]
> > As far as I understand, telegram loads all the gifs and animated stickers into RAM, and if you leave it overnight it just unreasonably starts to grow to about 2.5 gb of RAM consumption
> 
> Just close the chat and all media will be unloaded

of course I closed the chats, but judging by the system monitoring, RAM consumption is not decreasing,

only restarting the application several times a day helps

**Comment by ilya-fedin** [comment]
Waiting for steps to reproduce to be filled.

**Comment by stmp13** [comment]
> I'll repeat: please specify steps to reproduce in the issue like
> 
> ```
> 1. Do that
> 2. Do another thing
> 3. Do yet another thing
> ```
> 
> What should lead for issue to appear. Otherwise issue validity couldn't be checked.


What do you mean? I have to write the sequence of my actions in a telegram within a few hours/day?

**Comment by ilya-fedin** [comment]
I mean specify the steps that lead to the issue. "steps to reproduce" is like self-explaining naming.

**Comment by ilya-fedin** [comment]
If you still don't get it, contacting support might be a better thing than reporting via github.

**Comment by stmp13** [comment]
> I mean specify the steps that lead to the issue. "Steps to reproduce" is like self-explaining naming.

> If you still don't get it, contacting support might be a better thing than reporting via github. You can speak with in-app support using your native language.


Didn't know about support on telegram, is there any?

**Comment by ilya-fedin** [comment]
Settings -> Ask a question

**Comment by stmp13** [comment]
> Settings -> Ask a question

okay, thanks
