### ISSUE TITLE
[Linux client] buttons "minimize/maximize/close" don't fade in a video's fullscreen

### ISSUE THREAD

**Issue by luniotao** [telegramdesktop/tdesktop#28595]
### Steps to reproduce

**1) Play a video**
**2) Make it fullscreen**

### Expected behaviour

The title window buttons should automatically disappear, like they do in Windows OS.

### Actual behaviour

The buttons persist for entire video's runtime
![with-zeroes-appended](https://github.com/user-attachments/assets/7443bab9-10d5-4a5b-9cad-efe7ca17e094)
![default-look](https://github.com/user-attachments/assets/2a10c2fa-bb19-421b-b9e2-a60e356b2580)

### Operating system

Debian Linux, Plasma KDE, X11/Wayland

### Version of Telegram Desktop

Telegram Desktop 4.6.5 from ripository

### Installation source

Snap

### Logs

```shell
Hi. I'm trying to get rid of the "minimize/maximize/close" buttons at the top of Mediaview window, which don't disappear automatically as they do in TG Desktop for Windows. Is there a way to remove them completely or make them invisible for Linux?

It took me a while to find the corresponding asset for these buttons in the custom palette editor, it's called callNameFg. I tried to append two zeroes to its palette code, but I can still clearly see the buttons. I remember old video games like Oblivion or Ragnarok Online had a special color that would make a texture look invisible if applied, it was poisonous-purple. I wonder if there's a special palette code for TG element, which could make it fully transparent. I'd really want to get rid of these buttons in one way or another.
```

**Comment by ilya-fedin** [comment]
> ### Version of Telegram Desktop
> 
> Telegram Desktop 4.6.5 from ripository
> ### Installation source
> 
> Snap

wtf? So is it from repository or from snap? If you really use 4.6.5 then you can't be served by this bugtracker as this version is long outdated.
