### ISSUE TITLE
Add “Send Reaction” as a permission in group settings.

### ISSUE THREAD

**Issue by Fixie00** [telegramdesktop/tdesktop#28591]
### Is your feature request related to a problem?

For example, I want some people to be able to send reactions but not send messages and some people to be able to send messages but not send reactions.

There is a permission for every action you can do within a group EXCEPT “send reactions”. I’m not sure why.

### Describe the solution you'd like

Simply add a permission called “send reactions” under the rest of all the other permissions in group settings.

### Describe alternatives you've considered

Sadly, there are no alternatives to my knowledge.

### Additional context

Here is an example of what it would ideally look like on mobile when implemented. (I know this isn’t desktop, it’s just an example.)

![IMG_4867](https://github.com/user-attachments/assets/dc88386e-12b0-435a-a574-ae94f0dd629a)
![CE95B4B2-B2C7-42F9-9386-8E55DDFE908A](https://github.com/user-attachments/assets/3207302a-a6bb-436b-98e6-c95299085f08)

**Comment by Aokromes** [comment]
to have it there is api, but you already can https://i.imgur.com/LptfAZl.png

**Comment by Fixie00** [comment]
> to have it there is api, but you already can https://i.imgur.com/LptfAZl.png

Please implement into app. Everyone has smart phones these days.

**Comment by Aokromes** [comment]
you have the same setting on android, this is for telegram desktop.

**Comment by Fixie00** [comment]
> you have the same setting on android, this is for telegram desktop.

So only iOS doesn’t have it? That’s weird.
