### ISSUE TITLE
WebView crashes when starting web apps

### ISSUE THREAD

**Issue by soroushalinia** [telegramdesktop/tdesktop#28594]
### Steps to reproduce

1. Open telegram desktop
2. Open a bot with miniapp
3. Start the miniapp 

### Expected behaviour

Mini App should open properly like this
![image](https://github.com/user-attachments/assets/069f08ce-3f9e-48c8-be68-a0b60cd4e073)

### Actual behaviour

Mini app won't open with error:
Error: WebView has crashed.
![image](https://github.com/user-attachments/assets/634c1244-84a7-4e4f-9a11-738fd84b7b54)
 
There is a workaround by setting QT_QPA_PLATFORM=xcb telegram-desktop during launch 

### Operating system

Arch Linux (Gnome) 

### Version of Telegram Desktop

5.6.3

### Installation source

Static binary from official website

### Logs

```shell
Unrecognized value "gl-disable". Try GDK_DEBUG=help
QWindow::setWindowStates does not accept Qt::WindowActive
Can't configure xdg_toplevel with an invalid size QSize(-1, -1)
Can't configure xdg_toplevel with an invalid size QSize(-1, -1)
qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::zwp_text_input_v3_leave(wl_surface*) Got leave event for surface 0x0 focused surface 0x74c9571d3c20
qt.qpa.wayland: eglSwapBuffers failed with 0x300d, surface: 0x0
Unrecognized value "gl-disable". Try GDK_DEBUG=help
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...
```

**Comment by ilya-fedin** [comment]
dup, see #25126
