### ISSUE TITLE
Unable to Reset Password Although My Email and Phone are Linked

### ISSUE THREAD

**Issue by Omar7001-B** [telegramdesktop/tdesktop#28592]
### Steps to reproduce

1. Open Telegram Desktop.
2. Attempt to log in after being logged out unexpectedly.
3. Follow the prompts to enter your password and try to reset it.

### Expected behaviour

Since my email is already linked to my account, the application should allow me to reset my password through the email verification process.

### Actual behaviour

The application prompts for verification via both phone and email on the login process, but when selecting "Forgot Password," it states that a recovery email is not available, preventing any password reset.

Screenshot showing the error message when attempting to reset the password: https://i.imgur.com/NtwhoCq.jpeg

The account is linked to an email, as shown in the following screenshot where it asks for a verification code via email when logging in: https://i.imgur.com/OefZQAs.jpeg. 
This confirms that the email is linked to the Telegram account.

### Operating system

Andriod

### Version of Telegram Desktop

14

### Installation source

Play Store

**Comment by Omar7001-B** [comment]
I have tried reaching out to support multiple times, but I haven't received any response, whether negative or positive. I really need to contact someone at Telegram or on any other platform to help resolve this issue. Your assistance would be greatly appreciated!

**Comment by Aokromes** [comment]
this big tracler is for windows / linux / macos client.
