### ISSUE TITLE
link image preview problem

### ISSUE THREAD

**Issue by MohsenShakibafar** [telegramdesktop/tdesktop#2860]
hi , to read this issu.
i have problem with link preview image in telegram desktop.
when i copy link , it comes up and show other image , not main image that i set in ogp.
note that , title and description was wrong too.
all of them comes from my main site (link), but other links dont show its own title,description and image.
i use all opg debugger and i post link on fb too. all works great , but in telegram....
any idea ?
tnx

EDITE:
i use @webpagebot too , but still have same issue , tnx

sry about that, i forget that.
all of my page link in website.
example:
http://khabar2day.ir/news/%D9%87%D8%AA%D9%84-%D8%B1%D9%88%D8%AF%D8%A7-%D8%A7%D9%84%D9%85%D9%88%D8%B1%D9%88%D8%AC-%D8%AF%D8%A8%DB%8C--%D9%87%D8%AA%D9%84%DB%8C-%D8%A8%DB%8C%D9%86%D8%B8%DB%8C%D8%B1-%D8%AF%D8%B1-%D8%AF%D8%A8%DB%8C---%D8%AA%D8%B5%D8%A7%D9%88%DB%8C%D8%B1
another one:
http://khabar2day.ir/news/%D8%B3%DB%8C%D9%81%E2%80%8C%D9%BE%D9%86%D8%A7%D9%87%DB%8C-%D8%B4%D8%B4%D9%85%DB%8C%D9%86-%D8%AC%D8%AF%D8%A7-%D8%B4%D8%AF%D9%87-%D8%B5%D8%A8%D8%A7
and:
http://khabar2day.ir/news/%D8%AA%D8%B5%D8%A7%D9%88%DB%8C%D8%B1%DB%8C-%D8%B2%DB%8C%D8%A8%D8%A7-%D8%A7%D8%B2-%D8%A2%D8%A8%D8%B4%D8%A7%D8%B1-%DB%8C%D8%AE%E2%80%8C%D8%B2%D8%AF%D9%87-%D8%AF%D8%B1-%DA%86%DB%8C%D9%86

**Comment by john-preston** [comment]
@MohsenShakibafar I'm afraid this is not related to Telegram Desktop. Server handles the URL previews and chooses images. I can't fix that from my side.

**Comment by john-preston** [comment]
@MohsenShakibafar Server uses canonical url if it is specified, and you have:

    <link rel="canonical" href="http://khabar2day.ir/news/">
