### ISSUE TITLE
Ctrl+Q closes the app on Windows

### ISSUE THREAD

**Issue by cmdlinescan** [telegramdesktop/tdesktop#28603]
### Steps to reproduce

1. Press Ctrl+Q at the same time

### Expected behaviour

On macOS it should close, but on Windows it should not.

### Actual behaviour

App closes

### Operating system

Windows 10

### Version of Telegram Desktop

5.7.1 x64

### Installation source

Static binary from official website

**Comment by cmdlinescan** [comment]
Ctrl+Q closes the app on macOS (macOS hotkey itself, it also works in other applications like Safari, etc). It should not do the same thing while running on Windows (I think so).

Is this a telegram bug or it's a telegram feature itself?

**Comment by ilya-fedin** [comment]
It's a feature
