### ISSUE TITLE
Instant Views zoomed out too far when opening

### ISSUE THREAD

**Issue by JosXa** [telegramdesktop/tdesktop#28600]
### Steps to reproduce

1. Navigate to https://t.me/tagesschau24 in tdesktop
2. Open any instant view

### Expected behaviour

It shows the content quickly and in the normal zoom level

### Actual behaviour

IV is zoomed out to something like 20% size:

![{A68D6473-1474-44AD-8807-EB905EB6B07D}](https://github.com/user-attachments/assets/3fa3d186-9ca3-40d3-a714-1eda76daf08c)

It also takes a while to display the content:

https://github.com/user-attachments/assets/53af4d27-1f0e-43f5-8c54-869aaf4b1fa8

### Operating system

Windows 11

### Version of Telegram Desktop

5.7

### Installation source

Static binary from official website

### Logs

```shell
Interface scale: 125%
```

**Comment by rafitamolin** [comment]
Can reproduce

**Comment by john-preston** [comment]
@JosXa Thanks. I've fixed that for the upcoming 5.7.1 release, it'll be available within ten minutes.
