### ISSUE TITLE
Automatic Media Download Settings Not Saved on Exit / Restart

### ISSUE THREAD

**Issue by easyspace** [telegramdesktop/tdesktop#28608]
### Steps to reproduce

1. Settings >> Advanced >> Automatic Media Download
2. Automatically download set to "Off" for everything.
3. Exit Program
4. Start Program again.
5. Issue persists. All settings remain exactly the way they were before changes.

![image](https://github.com/user-attachments/assets/ca10bca2-81c7-4628-bb82-5d5b3bee6439)

### Expected behaviour

The settings should save and the screen should look like this:

![image](https://github.com/user-attachments/assets/d90b232f-ddb6-46f9-a25e-d0a7b35c0e70)

### Actual behaviour

It looks like this instead:

![image](https://github.com/user-attachments/assets/ca10bca2-81c7-4628-bb82-5d5b3bee6439)

### Operating system

Windows 10

### Version of Telegram Desktop

5.5.5 x64

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap, non-linux distribution package, non store) version from https://desktop.telegram.org

**Comment by easyspace** [comment]
Yup, doing so now. Hope the store version gets a fix soon.

**Comment by easyspace** [comment]
> plz try downloading official static (non-flakpak, non-snap, non-linux distribution package, non store) version from https://desktop.telegram.org

Yup, doing so now. Hope the store version gets a fix soon.
