### ISSUE TITLE
Ability to hide from the main list ("All chats") chats included in folders

### ISSUE THREAD

**Issue by Maksym-Kozub** [telegramdesktop/tdesktop#28610]
### Is your feature request related to a problem?

When a user has been reading dozens of channels (chats), and that user has organized them into folders, the main list still shows all those channels. It is quite inconvenient sometimes.

### Describe the solution you'd like

It would be nice to have a setting for each folder "Hide channels in this folder from the main list".

### Describe alternatives you've considered

A possible alternative could be a global setting "Hide from the main list channels included in folders".

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by john-preston** [comment]
Just archive them?

**Comment by Maksym-Kozub** [comment]
> Just archive them?

Thank you so much. I thought that either I will not be notified when there is a new message in an archived chat, or the archived chats will be unarchived as soon as new messages arrive in them. However, now I see that neither of those two assumptions is true. Thank you again.

**Comment by john-preston** [comment]
@Maksym-Kozub It can be customized in Archive settings.
