### ISSUE TITLE
Mac OS font tofu

### ISSUE THREAD

**Issue by spam312sn** [telegramdesktop/tdesktop#2861]
### Steps to reproduce
1. Enter the text in unicode, e.g.:  ͡° ͜ʖ ͡°

**Commentaries**
It is also in notifications

### Expected behaviour
Correct text view, like in Android app

### Actual behaviour
Tofu instead symbols

### Configuration
**Operating system:**
Mac OS 10.7.5 Lion
Build 11G63

**Version of Telegram Desktop:**
Version 1.0 (2017-01-11)

### Screenshot
![screen shot 2017-01-15 at 10 26 44 pm](https://cloud.githubusercontent.com/assets/17235291/21965989/5d9ba390-db73-11e6-8749-e649f9431a83.png)

**Comment by stek29** [comment]
#585
