### ISSUE TITLE
The message counter and video chat icon are superimposed on each other.

### ISSUE THREAD

**Issue by kotecat** [telegramdesktop/tdesktop#28615]
### Steps to reproduce

1. Start Video Chat in any group/supergroup.
2. Narrow down the chats preview to a minimum, leaving only avatars.
3. Select any other chat except the one being tested.
4. Send a message from the second account to the chat being tested.

### Expected behaviour

Message counter and video chat icon should be separate.

### Actual behaviour

The message counter and video chat icon are superimposed on each other.

CLOSED PREVIEW CHAT LIST:
![image](https://github.com/user-attachments/assets/4657bd44-d569-4e81-aa99-357524473a77)

FULL PREVIEW CHAT LIST:
![image](https://github.com/user-attachments/assets/ca49cac4-51ec-456f-b38c-65d85c1bf8ec)

### Operating system

Windows 10

### Version of Telegram Desktop

5.7.2 x64

### Installation source

Static binary from official website

**Comment by kotecat** [comment]
![image](https://github.com/user-attachments/assets/b917e209-abfa-42cf-9919-fa7b5ea03c03)

here's something else

**Comment by 23rd** [comment]
Please check the v5.9.0.
