### ISSUE TITLE
Wrong status of sending video message

### ISSUE THREAD

**Issue by paul23093** [telegramdesktop/tdesktop#28626]
### Steps to reproduce

1. Someone recording you a video message using Telegram Desktop 5.7.2

### Expected behaviour

status Recording a video message -> Sending a video message

### Actual behaviour

status Recording a video message -> Sending a file
![photo_2024-11-08_13-05-41](https://github.com/user-attachments/assets/4b3ed690-e625-4096-b3af-95ae19e5779a)
![photo_2024-11-08_13-05-43](https://github.com/user-attachments/assets/a2d05fc3-3133-4fc8-b366-8de37f13b10d)

### Operating system

MacOS 15.1 Sequoia

### Version of Telegram Desktop

5.7.2

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Should be fixed I guess.
