### ISSUE TITLE
Sticker size is too big in 1.0 (Mac)

### ISSUE THREAD

**Issue by choyongjoon** [telegramdesktop/tdesktop#2862]
### Steps to reproduce
1. Just send a sticker

### Expected behaviour
I expected normal size sticker

### Actual behaviour
![2017-01-16 5 20 24](https://cloud.githubusercontent.com/assets/1563230/21975487/3a0a2224-dc10-11e6-914b-6645c3f87c07.png)

### Configuration
**Operating system:**
OS X El Capitan 10.11.6

**Version of Telegram Desktop:**
1.0

**Comment by auchri** [comment]
duplicate

**Comment by john-preston** [comment]
@choyongjoon It wasn't changed in 1.0, it was that size from the very introduction of stickers in Telegram.
