### ISSUE TITLE
library version error.

### ISSUE THREAD

**Issue by aljustiet** [telegramdesktop/tdesktop#28627]
### Steps to reproduce

run telegram-desktop in terminal

### Expected behaviour

To open

### Actual behaviour

```
❯ telegram-desktop
telegram-desktop: error while loading shared libraries: librubberband.so.2: cannot open shared object file: No such file or directory
❯ doas ln -s /usr/lib/librubberband.so.3.0.0 /usr/lib/librubberband.so.2
❯ telegram-desktop
telegram-desktop: error while loading shared libraries: libx265.so.209: cannot open shared object file: No such file or directory
❯ doas ln -s /usr/lib/libx265.so.212 /usr/lib/libx265.so.209
❯ telegram-desktop
telegram-desktop: symbol lookup error: /usr/lib/libavcodec.so.61: undefined symbol: x265_api_get_209
```

### Operating system

Arch/Hyprland

### Version of Telegram Desktop

5.7.2-2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap, non-linux distribution package) version from https://desktop.telegram.org

**Comment by Scimmia22** [comment]
This isn't a telegram issue or a distribution issue. This is a user that is using a non-Arch ffmpeg package without knowing how to maintain it.

**Comment by aljustiet** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/telegram-desktop/-/issues/16#note_221694
