### ISSUE TITLE
New Feature: messages-posts

### ISSUE THREAD

**Issue by ruslooob** [telegramdesktop/tdesktop#28630]
### Short explanation

Messages can be turned into posts with media-content.

### Solution description

Hello. As the owner of the telegram channel, I lack the functionality that would allow me to publish traditional posts. I write a lot of text content and the traditional message format is not very suitable for me. But I like telegram because of the reach of the audience. I want my posts to be displayed widely on the screen. I also want to add photos to the middle of the post (to show them as you read the post), and not as it is done now.

I want that when creating a message, you can select the "message-post" option so that it has the characteristics that I described above.

### Considired alternatives

1. Use telegram. But then you will have to put up with the limited size of messages and publish long posts in parts. To apply applications that spoilerize the content of the post at its very beginning.

2. Switch to another platform that is better suited for posts. But then you'll have to put up with less audience coverage.

**Comment by agoudbg** [comment]
If you want post rich-text articles, you may use [telegra.ph](https://telegra.ph). 
Telegram has already provided a lot of formatting options to your messages, but things like photos in the middle of post is not realistic, since it's still a message platform.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
