### ISSUE TITLE
[Feature Request] Add a CLI flag to launch application minimized.

### ISSUE THREAD

**Issue by satma0745** [telegramdesktop/tdesktop#28634]
### Is your feature request related to a problem?

I use a custom script to launch Telegram Desktop (I need several separate instances, that's why I need a custom script for this) at system startup. But since I'm launching Telegram Desktop through the custom script, I can't launch it in minimized mode (in my case it results in several additional windows opening on system startup).

### Describe the solution you'd like

I would like to have a CLI flag `-minimized`, which will launch Telegram Desktop in a minimized mode. Just like the option from the settings, but a CLI flag:
![The "Launch Minimized" flag available in settings from the UI](https://github.com/user-attachments/assets/8a756969-6284-4450-ba11-f720d79b8249)

### Describe alternatives you've considered

I've considered using a single Telegram Desktop instance, but it's tied to a specific Virtual Desktop and I want to have separate instances on separate Virtual Desktops, so this option is out.

I also considered minimizing this windows through my custom script, but it proved to be not so easy to do. I thought that since we already have this option in the UI settings, maybe there's a way to pull it to the CLI flags as well.

I tried setting this value through the UI, but the "Launch Minimized" flag appears only when the "Launch Telegram when system starts" is enabled. I also tried going to the instance settings file (on the `-workdir` path), but it looks like this file has binary serialization and I didn't find a good way to set the "Launch Minimized" flag through this file. Maybe I was looking in the wrong place.

### Additional context

I'm on Windows 11 using a custom PowerShell script to manage several independent Telegram Desktop instances.

**Comment by satma0745** [comment]
I'm so sorry, guys.
Looks like Telegram Desktop already has a CLI flag for this: `-startintray`.
Don't know how I didn't notice it before creating an Issue.

**Comment by ilya-fedin** [comment]
Quit all instances. Copy the binary to the directories you specified to `-workdir`. Then, run those binaries just with double click. Enable autostart options in one of them (if it was already enabled, disable and re-enable). This will create a shortcut in the autorun folder in start menu. Re-name the shortcut. Repeat with each instance.

**Comment by ilya-fedin** [comment]
That's a more supported way than `-workdir` as it's a deprecated argument meant for internal purposes that aren't relevant for a long time and could be removed at any time without any warning.

**Comment by satma0745** [comment]
Thanks for the clarifications 🚀! Will switch to the suggested approach and, if any problems will occur, will create a separate GitHub Issue for that.
