### ISSUE TITLE
In latest macos doesn't works video effect on video call

### ISSUE THREAD

**Issue by shadowzoom** [telegramdesktop/tdesktop#28637]
### Steps to reproduce

Make videocall from latest macos, click camera video effects https://support.apple.com/en-gw/guide/mac-help/mchlp2980/15.0/mac/15.0

Colors clicking good, but when im trying to change background to custom wallpaper in videocall, its not clicking.

### Expected behaviour

Fix pls

### Actual behaviour

Fix pls

### Operating system

mac os sqeuoya (latest)

### Version of Telegram Desktop

Latest version on Nov 11.

### Installation source

Mac App Store

**Comment by Aokromes** [comment]
fill version properly.
