### ISSUE TITLE
Contacts avatars are not rendered with anti-aliasing on macOS

### ISSUE THREAD

**Issue by pepijnve** [telegramdesktop/tdesktop#2863]
### Steps to reproduce
1. Open the contacts list ensuring there are contacts in there with custom avatars.

### Expected behaviour
The circular stencil applied to the avatar image has smooth edges

### Actual behaviour
Jaggedness due to aliasing is clearly visible.
This can also be seen in the 'Telegram Service Notifications' avatar. The icon appears to be rendered using nearest neighbour downscaling instead of using some averaging downscaling algorithm.

### Configuration
**Operating system:**
macOS 10.12.2

**Version of Telegram Desktop:**
1.0

### Examples
![screen shot 2017-01-16 at 11 33 07](https://cloud.githubusercontent.com/assets/225326/21979553/99f8696a-dbdf-11e6-8d4e-e9bc772f2b9d.png)
![screen shot 2017-01-16 at 11 33 46](https://cloud.githubusercontent.com/assets/225326/21979572/b15183f8-dbdf-11e6-941b-c95f11b610cc.png)

**Comment by john-preston** [comment]
@pepijnve That's strange. They are supposed to and do look smooth for me. Perhaps you've launched the app when the display was not Retina and then it switched to Retina? (for example, an external hdmi screen was plugged out) App doesn't switch to Retina in runtime, only after restart.

**Comment by pepijnve** [comment]
Empirically it does indeed look like it has something to do with UI scaling.

I'm using a MacBook Pro (Retina, 15-inch, Mid 2014) with a Dell U2713H in a dual monitor setup. The external monitor is configured as the primary display (menu bar is on that screen in 'Arrangement' dialog). Both displays are configured to use the 'Default for display' scaling setting.

On the laptop display itself everything looks perfect. On the external monitor I see the aliasing effects.
I experimented a bit with having the external monitor plugged in and unplugged when launching the application, but as far as I can tell the end result is always the same.

**Comment by john-preston** [comment]
@pepijnve Yes, this is the opposite problem then. The UI always uses retina graphics and images, but the OS (or Qt, I'm not sure) performs the downscale from Retina window to a non-Retina window in such a way :( I'll try to improve that, but it won't work nice in such configuration right now anyway.
