### ISSUE TITLE
folders strip: scrolling the folders list also scrolls the chats list

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#28645]
### Steps to reproduce

1. enable the new "folders on top" option
2. hover with the mouse on the folders strip
3. scroll the folders list

### Expected behaviour

only the folders list is scrolled

### Actual behaviour

the folders list is scrolled, but at the same time the app also scrolls the chats list

### Operating system

Windows 11

### Version of Telegram Desktop

5.7.3

### Installation source

Static binary from official website

**Comment by suprunchuk** [comment]
fixed in v5.7.4 Beta #ad9ebdf

**Comment by suprunchuk** [comment]
fixed in v5.7.4 Beta ad9ebdf
