### ISSUE TITLE
"Close to taskbar" should be disabled if no taskbar is available

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#28646]
### Steps to reproduce

0. Make sure that no taskbar implementation is running
1. Start telegram-desktop
2. Go to Settings > Advanced > System Integration
3. The `Close to taskbar` option is available. Toggling it makes the main window non-closable.

### Expected behaviour

The `Close to taskbar` option should be unchecked and disabled if there is no taskbar.

### Actual behaviour

The `Close to taskbar` option is enabled, even if there is no taskbar. If it is checked, attempting to close the main window does nothing; the window can no longer be closed.

### Operating system

Alpine Linux (edge)

### Version of Telegram Desktop

telegram-desktop-5.7.2-r1

### Installation source

Other (unofficial) source

### Crash ID

n/a

### Logs

```shell
n/a
```

**Comment by ilya-fedin** [comment]
This is impossible to implement, there's no such API

**Comment by WhyNotHugo** [comment]
You're logging an error in cases where it is not available:

> QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "org.freedesktop.DBus.Error.ServiceUnknown")

You're trying to connect to a service. If the connection fails, then you know that it is not available.

**Comment by ilya-fedin** [comment]
It's Qt, not me and it's about tray, not taskbar. You can have a taskbar while not having tray.

**Comment by WhyNotHugo** [comment]
> You can have a taskbar while not having tray.

Sorry, I haven't used Windows in many years. Isn't the taskbar the entire bar, and the tray the portion of the bar where icons are rendered?

What's the difference here? Wouldn't "close to taskbar" show an icon in the tray?

**Comment by ilya-fedin** [comment]
When the system has tray and the tray icon is active, the "Close to taskbar" checkbox is hidden.

**Comment by WhyNotHugo** [comment]
If I understand correctly, "Close to taskbar" is functionally "Minimise instead of closing".

I guess that closing is a no-op for me because my desktop doesn't implement minimisation.

**Comment by ilya-fedin** [comment]
> If I understand correctly, "Close to taskbar" is functionally "Minimise instead of closing".

That's right.

> I guess that closing is a no-op for me because my desktop doesn't implement minimisation.

You mean clicking on the cross does nothing? If it's that then sounds like a real issue indeed. But then I don't see a way to fix it given that I don't want to talk to native Wayland APIs.

**Comment by ilya-fedin** [comment]
I guess what you actually want is #8941 (a separate option to run in background, without side effects of using tray or taskbar)?

**Comment by ilya-fedin** [comment]
There's also a hack for GNOME users, that if `org.gnome.desktop.wm.preferences button-layout` has close button but no minimize button, `Close to taskbar` gets hidden and tdesktop just always runs in background.
