### ISSUE TITLE
Message Loss and Auto Logout in Telegram Lite Version 5.5.5 on macOS

### ISSUE THREAD

**Issue by vorob1** [telegramdesktop/tdesktop#28643]
### Steps to reproduce

I was sending identical messages to different people

### Expected behaviour

I expect to be able to send messages reliably without any issues. In the event of an error, I should receive an error message rather than being logged out and having my messages deleted.

### Actual behaviour

Yesterday, I was sending identical messages to clients using Telegram Lite version 5.5.5 on macOS. At some point, I was automatically logged out from all sessions. After logging back in, I noticed that all the messages I had previously sent were missing. This is highly unsatisfactory as clients did not receive important information on time. Please address this issue and suggest possible solutions to prevent such occurrences in the future.

### Operating system

macOS 14

### Version of Telegram Desktop

5.5.5

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
telegram lite doesn't kicks users because sending messages, it's server what kicked you.
possible reasons:
malcious messages.
spam.
to much actions on to low amount of time.
