### ISSUE TITLE
folders strip not shown after opening an account in a new window

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#28648]
### Steps to reproduce

1. have more than one account logged in
2. CTRL + click to open an account (that has some folders) in a new window

### Expected behaviour

the folders strip is shown

### Actual behaviour

the folders strip is not shown (but folders can be changed using keyboard navigation)

### Operating system

Windows 11

### Version of Telegram Desktop

5.7.3

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Should be better in the v5.7.4.

**Comment by RememberTheAir** [comment]
fixed, thanks
