### ISSUE TITLE
Titlebar shows buttons for unavailable actions

### ISSUE THREAD

**Issue by WhyNotHugo** [telegramdesktop/tdesktop#28647]
### Steps to reproduce

0. Run a compositor which doesn't support at least one of: minimise, window_menu, maximise, fullscreen
1. Start telegram-desktop

In my case, I am reproducing this on swaywm, which can run nested on another compositor.

### Expected behaviour

The titlebar should not show buttons for actions that have been reported as unavailable by the compositor.

### Actual behaviour

The titlebar shows buttons for actions that have been reported as unavailable by the compositor.

### Operating system

Alpine Linux (Edge)

### Version of Telegram Desktop

telegram-desktop-5.7.2-r1

### Installation source

Other (unofficial) source

### Crash ID

n/a

### Logs

Logs with `WAYLAND_DISPLAY=1` indicate that telegram-desktop is being informed of capabilities:

```
[4280808.291] {Default Queue} xdg_toplevel#39.wm_capabilities(array[8])
```

The `8` here is the size of the array in bytes. There is a single item in this array, the int32 `3`, which means `fullscreen`.

**Comment by WhyNotHugo** [comment]
In Settings > Advanced > Window Title Bar, there is a "Use Qt window frame" checkbox. This renders a different titlebar, but it also renders buttons for unavailable actions.

**Comment by ilya-fedin** [comment]
It follows `org.gnome.desktop.wm.preferences button-layout` on settings portal

**Comment by WhyNotHugo** [comment]
The log shows that the compositor is already  informing telegram of its capabilities. Why query an external service for compositor capabilities?

One need to write a custom implementation to expose this GNOME-specific setting via the portal API.

**Comment by ilya-fedin** [comment]
> The log shows that the compositor is already informing telegram of its capabilities. Why query an external service for compositor capabilities?

1. I don't think there's a Qt API for this
2. The GNOME API is of user preference, not capabilities, so it will have to be queried even if there's a Qt API for Wayland capabilities

**Comment by WhyNotHugo** [comment]
Qt is informed of these capabilities and then doesn't let applications query them?

I think this is worth reporting upstream, what do yo think?

---

The XDG settings portal doesn't allow a user to configure settings. It merely relays configurations exposed by _separate_ "portal implementation" daemons. If I wanted to expose a `org.gnome.desktop.wm.preferences` setting, I'd have to write a custom daemon to expose this value.

GNOME and KDE already include a daemon that exposes this and other custom settings, but I hope you'll understand that this is ridiculously over-engineered, considering the value is already being passed by the compositor to the client.

**Comment by ilya-fedin** [comment]
> Qt is informed of these capabilities and then doesn't let applications query them?

As far as I'm aware, they don't have the goal of wrapping each and every native API... That's what they told when I was asking APIs for various Wayland things.

> I think this is worth reporting upstream, what do yo think?

I reported it ~2 years ago: https://bugreports.qt.io/browse/QTBUG-104630

> If I wanted to expose a `org.gnome.desktop.wm.preferences` setting, I'd have to write a custom daemon to expose this value.

You can use xdg-desktop-portal-gtk and set the value via gsettings. That's what KDE does.

**Comment by ilya-fedin** [comment]
> considering the value is already being passed by the compositor to the client

Well, it's not the same as I explained. The compositor could support all those actions but the user may want to have only close button for example (the GNOME's default).

**Comment by ilya-fedin** [comment]
> As far as I'm aware, they don't have the goal of wrapping each and every native API...

There's still no API even for xdg-positioner and the only way to position menus is via global positioning which is a way bigger thing and leads to various bugs with menus, what do you want about some capabiliities most people don't even know about...

**Comment by ilya-fedin** [comment]
Qt's API is a lowest common denominator, mostly copying WinAPI.

**Comment by WhyNotHugo** [comment]
Thanks for the references.

> Qt's API is a lowest common denominator, mostly copying WinAPI.

I've noticed this pattern with dozens of bugs in applications that cannot be fixed due to limitations in Qt. Each of these bugs in not a big deal, but together, they result in an experience of hitting on bug after another, continuously.

**Comment by ilya-fedin** [comment]
I'm doubt any other toolkit provides API for this paritcular issue, btw.

**Comment by WhyNotHugo** [comment]
Firefox doesn't render minimise or maximise buttons on the top right corner; it only renders the close button.

I don't run any other application which renders its own titlebar. All other applications rely on compositor decorations, even Qt6 applications like audacious, or nheko. Only Telegram renders its own bar.

BTW: the non-Qt window frame renders a titlebar with no title. Is this also part of the same issue?

**Comment by ilya-fedin** [comment]
> Firefox doesn't render minimise or maximise buttons on the top right corner; it only renders the close button.

It's because it uses `g_object_get(gtk_settings_get_default(), "gtk-decoration-layout")` which in turn gets the value from `org.gnome.desktop.wm.preferences button-layout` on gsettings. If you had xdg-desktop-portal-gtk installed that bridges gsettings values to portal, you would see the same with tdesktop. And then you would be able to use `gsettings set org.gnome.desktop.wm.preferences button-layout ''` to get rid of titlebar icons from firefox, tdesktop, any gtk application and any other application with custom toolkit reading gtk settings.

**Comment by ilya-fedin** [comment]
> BTW: the non-Qt window frame renders a titlebar with no title. Is this also part of the same issue?

It's just the design.

**Comment by WhyNotHugo** [comment]
> It's just how the designer drew it on mockup.

Er, are you sure that's what the designer intended? To have a titlebar which is completely empty and has no title?

The settings section for "Window title bar" even has a couple of checkboxes to change the content of the titlebar:

![image](https://github.com/user-attachments/assets/f345f3f6-52f9-422a-8a6b-4866d9844c93)

But it doesn't affect the titlebar, only the title as rendered elsewhere.

**Comment by ilya-fedin** [comment]
> Er, are you sure that's what the designer intended?

Personally I have no idea, the widgets exist long before I started contributing to tdesktop. I just trust it's intended.

**Comment by john-preston** [comment]
@WhyNotHugo On the main page of the repository there is a screenshot of the app, of how it's supposed to look.
