### ISSUE TITLE
Consider pinned chats when forwarding messages

### ISSUE THREAD

**Issue by Dimoka113** [telegramdesktop/tdesktop#28650]
### Steps to reproduce

1. Start forwarding a message somewhere else

### Expected behaviour

Previously, in the window for selecting a chat for forwarding, pinned chats were taken into account (let’s say my “Saved messages” are first in the list), and accordingly, when forwarding, the chat should also be first.

### Actual behaviour

Pinned chats are not taken into account.
![image](https://github.com/user-attachments/assets/f49683c9-b5fb-41d8-8905-af8d0bc2b329)

### Operating system

Windows 10

### Version of Telegram Desktop

5.7.3

### Installation source

Static binary from official website

### Crash ID

-

### Logs

```shell
-
```

**Comment by webportnoy** [comment]
After click on share button - order of chats to share is good, pinned chats at the top.
![Снимок экрана от 2024-11-13 14-55-45](https://github.com/user-attachments/assets/54e04a3c-49d6-49f7-9a8d-37bb365e9343)

But if making right click on the message and choose "Share" from pop up menu - order of chats is not correct, archived chats at the top, suddenly .

**Comment by Dimoka113** [comment]
> After click on share button - order of chats to share is good, pinned chats at the top. ![Снимок экрана от 2024-11-13 14-55-45](https://private-user-images.githubusercontent.com/35290918/385747094-54e04a3c-49d6-49f7-9a8d-37bb365e9343.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDA1MzEsIm5iZiI6MTczMTUwMDIzMSwicGF0aCI6Ii8zNTI5MDkxOC8zODU3NDcwOTQtNTRlMDRhM2MtNDlkNi00OWY3LTlhOGQtMzdiYjM2NWU5MzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEyMTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMGI5NTEyZWI1ZjdjM2VhYzk5MDYzZWFhMmM0NjdkZjIwZTIyYjdmNmY3MjZhYWViMTZjMzE3OTIwNjczOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DcXUUUdm0JGGJIyt2etMR3wsSZGmE1DgJBBLZirx_3w)
> 
> But if making right click on the message and choose "Share" from pop up menu - order of chats is not correct, archived chats at the top, suddenly .

Hm, well, I can’t reproduce this specifically, but it’s quite possible that this is also somehow related

**Comment by Banane9** [comment]
Experiencing this too, was like "what the hell did this update do?"

This better not get an "actually, this is intentional" like the click on embed images opening the link.

**Comment by Aphotic** [comment]
while we are at it fix... archived chats now show on top of other chats as if they were not archived as well

**Comment by Aphotic** [comment]
also  another bug found:

  with new  folders  on top with forwarding(with  or without using the arrow on the right)
you  cant  find groups that  have categories in the list  unless  you  dont  forward to a specific  folder, u  have to  just find categorized groups in  All  chats section 
screenshot 1 one shows the categorized group  (Annmorph.) is in  groups folder
screenshot 2  shows  you cant  find categorized groups  in  any  of the folders they are  added(groups)
screenshot  3  shows  that they  exist  in All Chats  while  forwarding
or you just  have to  find  each by  searching  their  name 
![image](https://github.com/user-attachments/assets/d69e5550-68f3-4a2d-8c5e-7069f3ecf0da)
![image](https://github.com/user-attachments/assets/db0689f6-e9ff-44a0-ae41-c6afed38b32c)
![image](https://github.com/user-attachments/assets/3204cdc8-eaea-465c-9390-563e8ce5cd52)

**Comment by suprunchuk** [comment]
fixed in[ v5.7.4 Beta](https://github.com/telegramdesktop/tdesktop/releases/tag/v5.7.4) 9e83562
