### ISSUE TITLE
Automatic logout in Telegram Web.

### ISSUE THREAD

**Issue by Vince972** [telegramdesktop/tdesktop#28652]
### Is your feature request related to a problem?

Hello everybody,

Almost everything is in the title. Like many people, I use Telegram web **_at work_** and there is no automatic logout.

### Describe the solution you'd like

Could you please let users set a custom duration for automatic logout since 1 min (1 min, 3 min, 5 min, 15 min, etc.).

### Describe alternatives you've considered

Sometimes, I forget to logout manually. So, it's very important.

### Additional context

Thank you.

**Comment by Aokromes** [comment]
this is telegram desktop bug tracker. not telegram web. use bugs.telegram.org for such reports.
