### ISSUE TITLE
Crash when clicking on unsubscribed channel name in the star transaction history

### ISSUE THREAD

**Issue by danog** [telegramdesktop/tdesktop#28653]
### Steps to reproduce

1. Subscribe to a paid channel
2. Unsubscribe
3. Open the telegram star transaction history
4. Click on the channel name
5. Click on the channel name in the recipient box

### Expected behaviour

An error indicating that we unsubscribed from the chat and thus cannot access it

### Actual behaviour

Crash

### Operating system

mac os 15.1

### Version of Telegram Desktop

5.7.3 beta

### Installation source

Static binary from official website

### Crash ID

554d5d77-8d89-46bb-99ab-94544ea6942b

**Comment by danog** [comment]
This happens when clicking on channel name for star reactions, as well: 0dae4fd9-3bc4-4e0f-b7a2-592671663ac8

**Comment by 23rd** [comment]
Should be better in the v5.7.4.

**Comment by danog** [comment]
Yep, thanks!
