### ISSUE TITLE
Emoji Shortcuts are not working in Telegram Desktop 1.0

### ISSUE THREAD

**Issue by sikrigagan** [telegramdesktop/tdesktop#2865]
1. Emoji Shortcuts are not working in Telegram Desktop 1.0

### Expected behaviour
On typing `:` emoji helper should appear.

### Configuration
**Operating system:** macOS Sierra version 10.12

**Version of Telegram Desktop:** 1.0

**Comment by auchri** [comment]
There is no emoji helper

**Comment by cascornelissen** [comment]
@auchri, would it be a lot of work to change `:+1:` to an :+1: emoji just like Slack and GitHub do?

**Comment by auchri** [comment]
@cascornelissen #627

**Comment by cascornelissen** [comment]
@auchri, thanks! Guess I looked over that specific issue... I'm sorry ;)
