### ISSUE TITLE
weird layout on tablets

### ISSUE THREAD

**Issue by glebov21** [telegramdesktop/tdesktop#28651]
### Steps to reproduce

Xiaomi pad 6
![IMG_20241114_103950_039](https://github.com/user-attachments/assets/83b70aae-1e47-40d0-9c2a-da505d5939dc)

### Expected behaviour

Left panel need to hiding when chat opened (like on mobiles)

### Actual behaviour

Left (chats) panel use half of screen

### Operating system

Android

### Version of Telegram Desktop

11.3.4

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
Sorry but this is telegram desktop bug tracker, nothing here belongs to android.
