### ISSUE TITLE
Every time the Snap version of Telegram starts, it always opens in a closed state, you have to click Quit and then open Telegram again

### ISSUE THREAD

**Issue by binocry** [telegramdesktop/tdesktop#28656]
### Steps to reproduce

1. open telegram
2. wait
3. telegram opened (with indicator it opened on system tray)  but dont show any 

### Expected behaviour

open app like normal app do

### Actual behaviour

it just show telegram icon on dock and on system tray, but thats it

### Operating system

Ubuntu 24.04

### Version of Telegram Desktop

5.7.2

### Installation source

Snap

**Comment by GenoXu** [comment]
I run Telegram Desktop (v 5.8.2 portable) on windows 11.
After I press "X" to close the app, the window won't show up when I click the taskbar icon unless I minimize it to the tray.
I tried older versions of telegram but got same result.

https://github.com/user-attachments/assets/373154ff-aea1-4a28-8c3d-32313182a99c

**Comment by ilya-fedin** [comment]
@GenoXu I can't say anything about your case but this issue is going to be closed by the bot in two weeks because the initial report is unreproducible
