### ISSUE TITLE
issue with Spotify link preview on telegram web

### ISSUE THREAD

**Issue by blacksrc** [telegramdesktop/tdesktop#28664]
### Steps to reproduce

  1. Go to Spotify app or web. Pick a music link to share. Like: 
  ```
  https://open.spotify.com/track/74fi3KHYEnxwk8oUnOQdMr
  ```
2. Create a markdown from the link above:
```md
[Listen to the Track on Spotify](https://open.spotify.com/track/74fi3KHYEnxwk8oUnOQdMr) 
```
3. Copy the markdown and paste it in telegram web private chat or channel.

### Expected behaviour

To always preview the link form spotify platform.

### Actual behaviour

- In some cases, the preview loads successfully the first time you send the message, but subsequent attempts (sending the link as another message) fail to load the preview.
- Occasionally, the preview fails to load entirely, regardless of how many attempts are made.

### Operating system

linux, telegram-web on firefox

### Version of Telegram Desktop

Telegram Web

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
this is telegram desktop bug tracker not telegram web.

**Comment by blacksrc** [comment]
@Aokromes Could you please guide me to the correct repo please if there is any? I cannot find any specific repo for telegram-web. it will be much appreciated.

**Comment by Aokromes** [comment]
there are 2 different telegram web versions, i suggest you to use bugs.telegram.org
