### ISSUE TITLE
Update telegramdesktop/winget-releaser fork

### ISSUE THREAD

**Issue by vedantmgoyal9** [telegramdesktop/tdesktop#28665]
### Steps to reproduce

WinGet release workflow is failing for a long time due to outdated fork - https://github.com/telegramdesktop/tdesktop/actions/workflows/winget.yml.

@john-preston  @Aokromes Please update the fork.

### Expected behaviour

WinGet release workflow should exit successfully without failing.

### Actual behaviour

WinGet release workflow is failing.

### Operating system

Windows

### Version of Telegram Desktop

N/A

### Installation source

Other (unofficial) source

**Comment by vedantmgoyal9** [comment]
@john-preston

**Comment by john-preston** [comment]
I _think_ I've updated it. We'll see.
