### ISSUE TITLE
Bug report from static analysis)

### ISSUE THREAD

**Issue by Nanamuru** [telegramdesktop/tdesktop#28667]
### Steps to reproduce

Hi guys, I have checked the code of your project with a static analyzer and published the [article](https://pvs-studio.com/en/blog/posts/cpp/1186/). You may be interested in it. 

### Expected behaviour

Read the article=)

### Actual behaviour

bug fix

### Operating system

Ubuntu  22.04.5 LTS

### Version of Telegram Desktop

https://github.com/telegramdesktop/tdesktop/commit/754d4674402523b768226b2ef9c6b26b81aecedd

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
That's nice, thanks!
