### ISSUE TITLE
Number banned after switching between desktop client and Android client when messaging same person

### ISSUE THREAD

**Issue by oneofmanyacdcfanstoo** [telegramdesktop/tdesktop#28671]
### Steps to reproduce

On October 24th at 7:50pm EST, I was messaging my GF from the Desktop Client. I had a picture on my tablet that I wanted to send her, so I got on the tablet (using Forkgram from F-Droid) and sent the picture. For a split second, the picture showed up, and then I was autologged out and my number was banned. Over 30 attempts to contact TG support via official form, email, and Twitter, have resulted in Zero response from anyone.

### Expected behaviour

I expected that since TG is open source, it was okay to use ports of the software on my devices. I expected that the picture I sent would go from my phone to my GF, and the conversation would continue as normal.

### Actual behaviour

When sending the picture, my account was autologged out and my number was banned. I have not done anything illegal or nefarious on TG.

### Operating system

Windows 11 x64 and Android 13

### Version of Telegram Desktop

Current at the time.

### Installation source

Static binary from official website

**Comment by oneofmanyacdcfanstoo** [comment]
Not that it's particularly relevant to the issue, but when I posted on Twitter trying to contact TG support, I was almost overwhelmed with responses from different people saying "Contact so-and-so tech services, they can get you unbanned." I fell for the first one until the person said they wanted money. Telegram is feeding the scamming trade by not responding to support emails.

**Comment by Aokromes** [comment]
Sorry but this is telegram desktop bug tracker, nothing here belongs to user account administration.
