### ISSUE TITLE
Attaching file via a choosing file dialogue doesn't work on Windows for ARM.

### ISSUE THREAD

**Issue by Haskell-mouse** [telegramdesktop/tdesktop#28672]
### Steps to reproduce

0. Vivibook S 15 with X Elite CPU + fresh windows 11 from vendor(Asus)
1. I unarchived the latest binary and logged in. 
2. Tried to attach a document or a photo via the attachment button. 

### Expected behaviour

I expected to see a file selection dialogue box and be able to attach a file to a message. 

### Actual behaviour

I had seen the file dialogue only for a moment (<0.5s), but then it disappeared almost immediately. Retries gave the same results. Attaching via "Drag and drop" works well. 

### Operating system

Windows 11 for ARM

### Version of Telegram Desktop

5.8.1 portable(from this repo's assets)

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
duplicate and fixed on future version.

**Comment by john-preston** [comment]
@Haskell-mouse Please try 5.8.2 version.
