### ISSUE TITLE
Issue with Media Popup on Telegram Desktop

### ISSUE THREAD

**Issue by JoraGevorgyan** [telegramdesktop/tdesktop#28677]
### Steps to reproduce

1. Have a running machine withing given version of OS
2. Install the mentioned version of Telegram Desktop using snap.
3. Click on any media to view.

### Expected behaviour

The media popup should display the selected image or play the video when clicked.

### Actual behaviour

When opening media, the popup appears to activate as a second window (I can hear the sound when playing a video), but the media itself is not visible.

### Operating system

Ubuntu 24.04 LTS (Linux 6.8.0-45-generic)

### Version of Telegram Desktop

version 5.8.2

### Installation source

Snap

**Comment by ilya-fedin** [comment]
> ### Expected behaviour
> 
> The media popup should display the selected image or play the video when clicked.

I get exactly this when trying to reproduce the issue

**Comment by JoraGevorgyan** [comment]
Is it the version 5.8.2 on Ubuntu 24.04?
Did you have installed it from Ubuntu app center?

In my case Telegram runs the second window(I see it in my dashboard) but it's not visible to me.
Please let me know if logs or some other information may be helpful, I can provide.

Thanks in advance

**Comment by ilya-fedin** [comment]
It's version 5.8.2, Ubuntu 24.04 with latest updates (i.e. .1) and installed via `snap install telegram-desktop`

**Comment by JoraGevorgyan** [comment]
I reinstalled using `snap`, but the issue still exists ...  

How can I get log files, so you can see what's exactly happening in my case?

**Comment by ilya-fedin** [comment]
Such kind of things aren't logged. It usually means your system misbehaves.
