### ISSUE TITLE
Missing Features Right-clicking a Message in Private Chats

### ISSUE THREAD

**Issue by rnapoli00** [telegramdesktop/tdesktop#28686]
### Steps to reproduce

Open Telegram Desktop on Windows 11 22631,

Right-click a message in a private chat.

### Expected behaviour

The app should show a menu with a series of possible operations like reacting, copying a message and such.

### Actual behaviour

It is possible only to select the message. no other options are displayed.

### Operating system

Windows 11 22631

### Version of Telegram Desktop

5.8.2

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by rnapoli00** [comment]
I just figured it out: 

being used to the browser version, to bring up the message menu I used to click on the general area where the message is located.
On the desktop version you need to right-click directly on the message.

i'll close the issue.
