### ISSUE TITLE
Can't reorder channels in folder manually by mouse draging.

### ISSUE THREAD

**Issue by AntonieS** [telegramdesktop/tdesktop#28689]
### Steps to reproduce

Open folder with channels on that you subscribed.
Click on channel. 
Try draging channel in right side panel up or down to reorder - it didn't work.

### Expected behaviour

In previous versions (before 5.8.3) you can reorder channels.

### Actual behaviour

Can't reorder channels in folder manually by mouse draging.

### Operating system

Win7/10/11 x64.

### Version of Telegram Desktop

5.8.3

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
The order in folders is last-message-date order, the same as in the main chats list. You can pin chats/channels in the folder and drag-to-reorder them after that. Only pinned chats can be manually reordered, and it works in 5.8.3.

**Comment by AntonieS** [comment]
Yes, You're right. I forgot about that. Sorry.
