### ISSUE TITLE
click on images

### ISSUE THREAD

**Issue by keyd08** [telegramdesktop/tdesktop#28699]
### Steps to reproduce

open the app
open any profile discussion
click on any image 
see your telegram App been closed even if that's not exactly what you wanted 

### Expected behaviour

When you click on images inside profiles you should see the images opened

### Actual behaviour

Inexplicably the result is that the App is been closed 

### Operating system

Linux Fedora

### Version of Telegram Desktop

5.8.3

### Installation source

Flatpak

**Comment by ilya-fedin** [comment]
> open the app
> open any profile discussion
> click on any image
> see your telegram App been closed even if that's not exactly what you wanted

I'm not sure what "profile discussion" means so I opened random chat and clicked on an image from there. The app didn't close.
