### ISSUE TITLE
[Alpha Build] Chats are screwed up

### ISSUE THREAD

**Issue by Nhoya** [telegramdesktop/tdesktop#2869]
### Steps to reproduce
1. Send a message 

### Expected behaviour
In Private messages propics should not be showed and your message should be in the right side of the scren
In Group chats your messages should stay in the right side of the screen
When multiple messages are from the same person are sent the propic should be showed on the first message, not on the last

### Actual behaviour
In private chats popics are shown for each message and all the messages are on the left of the screen while yours should be on the right side

In group chats your messages are on the left side while they should be on the right side and in multiple messages the propic is shown on the last message and not at the first

### Configuration
Debian Jessie

**Version of Telegram Desktop:**
1.0.1

**Comment by MasterGroosha** [comment]
Regarding left/right side: If you make TDesktop window large enough, you'll see an extra option in Settings (see the screenshot below). Change it and your messages will be on the right side regardless of window size.
![image](https://cloud.githubusercontent.com/assets/2780044/22019375/6b506bea-dcc4-11e6-8aa9-787ea60adfee.png)

**Comment by Nhoya** [comment]
Deselecting the option will solve the issue of the right/left side

**Comment by auchri** [comment]
> When multiple messages are from the same person are sent the propic should be showed on the first message, not on the last


Duplicate
