### ISSUE TITLE
Request to add a feature to disable animations when hovering over emojis

### ISSUE THREAD

**Issue by va0zru** [telegramdesktop/tdesktop#28690]
### Is your feature request related to a problem?

Yes, the current hover animations for emojis, reactions, and stickers in the Telegram Desktop app can be distracting. When working in chats for long periods, these animations take away focus and may interfere with productivity. It would be ideal for users who prefer a static interface to have the option to disable these animations.

### Describe the solution you'd like

I would like to see an option in the settings that allows users to disable hover animations and effects on emojis, reactions, and stickers. This option could be added to the "Settings" menu or "Chat Settings," giving users the freedom to enable or disable this feature based on their preferences.

### Describe alternatives you've considered

I don't think there are any alternatives.

**Comment by Aokromes** [comment]
check battery and animations.
