### ISSUE TITLE
Indicator of unread messages does not display on taskbar icon

### ISSUE THREAD

**Issue by mkali67** [telegramdesktop/tdesktop#28696]
### Steps to reproduce

1. Normal operation of Telegram Desktop. After one of the updates:
2. Minimized icon to ray shows indicator of unread messages.
3. At the same time, there is no unread message indicator in the taskbar (like issue #2846).
4. Indicator of unread messages is only visible when the taskbar is enlarged (the "use small taskbar buttons" option is disabled).
5. This error appears/disappears periodically at long intervals after Telegram Desktop updates.

### Expected behaviour

Indicator of unread messages should be visible in the taskbar and tray at the same timewhen task bar is set "use small taskbar buttons" -> ON .

### Actual behaviour

Indicator of unread messages does not display when task bar is set "use small taskbar buttons" -> ON.

### Operating system

Windows 10 Home 22H2 19045.5131

### Version of Telegram Desktop

5.8.3 x64 (and a few previous)

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
It is not a bug, that's just how Windows works, it doesn't show overlay on small taskbar.

**Comment by mkali67** [comment]
I could agree if I updated Windows or installed something that conflicts with Telegram Desktop. But the situation occurred immediately after updating Telegram Desktop. This function worked before.
But it's always easier to blame Windows. Best regards.
