### ISSUE TITLE
No longer launches

### ISSUE THREAD

**Issue by RobinJ1995** [telegramdesktop/tdesktop#287]
I've been using Telegram Desktop for a while now. I just updated it to version 0.6.14-1 using `yaourt` (from the Arch Linux User Respitories). I closed the window, and when I launched it again window wouldn't come up.

`killall telegram`, and when I launch `telegram` from a terminal I get the following messages;
![capture d ecran de 2014-11-25 17 09 30](https://cloud.githubusercontent.com/assets/3089559/5186375/213167fc-74c6-11e4-8b67-314b41d55b0a.png)
It just hangs there until I hit CTRL+C.

**Comment by auchri** [comment]
Is this still the case? If yes, reopen the issue
