### ISSUE TITLE
Timestamps links in reply to certain videos don't work

### ISSUE THREAD

**Issue by M86xKC** [telegramdesktop/tdesktop#28707]
### Steps to reproduce

1. upload a video
2. reply to it with a timestamp eg. 00:02

### Expected behaviour

when clicking the timestamp it should skip the first second of the video

### Actual behaviour

the timestamp is no longer a link that's pressable

### Operating system

Irrelevant (testing on multiple OSes)

### Version of Telegram Desktop

v 5.8.3

### Installation source

Flatpak

### Crash ID

N/A

### Logs

```shell
N/A
```

**Comment by M86xKC** [comment]
here is a channel with an example: https://t.me/+pI3vlZ33H10xNzgz

**Comment by john-preston** [comment]
@M86xKC This video has incorrect attributes, it doesn't have a correct duration set, so whoever sent it did it wrong. When parsing links in captions / replies the duration is taken into account.

**Comment by john-preston** [comment]
@M86xKC If I save this video to disk and send it from disk using TDesktop, it is sent correctly, and the replies with timestamps work.

**Comment by M86xKC** [comment]
I see
Thank you for taking a look into it. Much appreciated
