### ISSUE TITLE
Inertial scrolling continuous when hover from chatlist (left) to chat itself (right) and vice versa

### ISSUE THREAD

**Issue by alivekenny** [telegramdesktop/tdesktop#2870]
### Steps to reproduce
1. Scroll  down list of chats (left part of window)
2. Hover mouse over chat itself (right part of window)
3. Flick down finger on your mouse (two finger for touchpad) for fast inertial scrolling
4. Quickly hover your mouse over chat list (left)

### Expected behaviour
Chat list and chat itself scroll separately and do not affect each other

### Actual behaviour
Chat scrolling suddenly stops and chat list begins to scroll

![Scrolling bug amimation](http://imageshack.com/a/img923/4804/TpOvJj.gif)

### Configuration
**Operating system:** macOS Sierra, MacBook Pro Early 2015

**Version of Telegram Desktop:** 1.0

**Comment by john-preston** [comment]
@alivekenny This is the way Qt handles scrolling on macOS, sorry :( it doesn't handle the touches, but translates them to regular mouse wheel events and sends them to the widget mouse is currently over.
