### ISSUE TITLE
Exported messages are nested within messages with inline buttons.

### ISSUE THREAD

**Issue by klimang** [telegramdesktop/tdesktop#28712]
### Steps to reproduce

1. Select a chat or channel with messages that have inline buttons.
2. Export this chat or channel in HTML format.
3. Open the output HTML file in a browser and open the browser's developer tools.
4. Select a message with inline buttons in the DOM tree of the document.

### Expected behaviour

Not nested messages.

### Actual behaviour

Inside the message with inline buttons are all other messages.

### Operating system

Windows 10 22H2

### Version of Telegram Desktop

latest

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Any public example?

**Comment by Aokromes** [comment]
you can create sample at https://t.me/tdesktopbetatest

**Comment by klimang** [comment]
![1](https://github.com/user-attachments/assets/668ee2e4-e9c8-4500-9452-793a5e397959)

**Comment by 23rd** [comment]
Please check the v5.9.0.
