### ISSUE TITLE
withdraw reward PC error

### ISSUE THREAD

**Issue by Morrigan-Ship** [telegramdesktop/tdesktop#28715]
### Steps to reproduce

i cannot get my reward in PC and Android
in PC i getting this error:
![image](https://github.com/user-attachments/assets/7655228a-fe3b-4986-b479-7e794af9a157)

```internal server error```

### Operating system
windows

### Version of Telegram Desktop
5.8.3

### Installation source
Static binary from official website

### Crash ID
internal server error

**Comment by Aokromes** [comment]
i think you need a minimum of 10 tons.

**Comment by Morrigan-Ship** [comment]
> i think you need a minimum of 10 tons

you wrong
i did some research with some madeline proto developers
its "internal server error error_code: 500"
and some of them told me i can fixed by using USA VPN
i tested some USA VPN's not worked :/

i need help

**Comment by Aokromes** [comment]
https://t.me/tgbetachat/1924243
