### ISSUE TITLE
Pinned Chats Not Working in Folders

### ISSUE THREAD

**Issue by hoeci** [telegramdesktop/tdesktop#28710]
Pinned chats don't seem to work properly in folders but function fine in 'All Chats.' When I try to pin a chat, it rearranges the pinned chats correctly. However, after restarting or changing the order of pinned chats, they break again and show no pinned chats in that folder.

### Operating system

Windows 10

### Version of Telegram Desktop

v5.8.4

### Installation source

Static binary from official website

**Comment by shockterapy** [comment]
same thing, chat pinning feature doesn't work properly in any folders on 5.8.4 beta, on previous version same account still do it without any bugs

**Comment by john-preston** [comment]
@hoeci Thanks! This will be fixed today in another beta.

**Comment by hoeci** [comment]
The problem still exists in 5.8.5. Some folders still have issues, but some seem to be fixed.

**Comment by hoeci** [comment]
Yes, my chats were unpinned across all devices. It's really disappointing.
