### ISSUE TITLE
No pinned chat icon in "avatar-only" list

### ISSUE THREAD

**Issue by gudvinr** [telegramdesktop/tdesktop#2871]
### Steps to reproduce
1. Resize chats list to minimal width

### Expected behaviour
Expected to see pinned chat indicator

### Actual behaviour
No pinned chat indicator

### Configuration
**Operating system:** Ubuntu 16.04.1

**Version of Telegram Desktop:** 1.0.1 alpha

**Comment by iPonyRadio** [comment]
This isn't an issue on 1.0.0 stable on Windows 10 64, as a side note

**Comment by auchri** [comment]
Because there is no "avatar-only" side bar in 1.0.0 😂

**Comment by iPonyRadio** [comment]
@auchri I should probably switch to the alpha branch. Is anyone pushing builds of alpha 1.0.1?

**Comment by auchri** [comment]
@iPonyRadio See https://desktop.telegram.org/changelog#alpha-version

**Comment by iPonyRadio** [comment]
Is the "Avatar only" list only accessible on Linux? I've resized the window to the minimum the client allows on Win10 and I'm seeing nothing different from stable. Am I missing a setting or something?

**Comment by auchri** [comment]
Also the channel icon is missing @john-preston

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8
