### ISSUE TITLE
Media Viewer 'next image' arrow not visible on narrow screen

### ISSUE THREAD

**Issue by sney** [telegramdesktop/tdesktop#28724]
### Steps to reproduce

1. Open Telegram desktop on a monitor with low horizontal resolution, in my case 1200x1920 (16:10 monitor rotated sideways)
2. Click an image in the chat window
3. Observe that the left side 'previous' arrow is visible while the right side 'next' is not

This is a recent issue that first appeared in the last 2-3 months. 

![telegram-left-arrow](https://github.com/user-attachments/assets/db0d0ebf-e5c2-43ec-a32e-110f67da6969)

### Expected behaviour

Should be able to go to the next and previous images without closing the viewer

### Actual behaviour

Clicking where the arrow is expected to be closes the viewer 

### Operating system

Debian trixie/sid, KDE Plasma 5.27 (Wayland)

### Version of Telegram Desktop

5.8.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Checking the issue on my test KDE neon VM with Plasma 6.2.3 and tdesktop 5.8.5, I can't reproduce.

**Comment by sney** [comment]
Is there a way within the client to force an upgrade to 5.8.5? I normally trust it to keep itself up to date.

**Comment by Aokromes** [comment]
> Is there a way within the client to force an upgrade to 5.8.5? I normally trust it to keep itself up to date.

enable beta.

**Comment by sney** [comment]
Alright, issue still present here in 5.8.5. I can't risk the plasma 6 update until after next thursday (Dec 12th), but I'll make a note to do it then and see if that fixes it. 

Just for some additional details: this is a 2 monitor setup, and both arrows appear fine on my main (landscape) monitor. It's only an issue on the secondary portrait screen that I use for chat and email.

**Comment by ilya-fedin** [comment]
Well, that might provide a difference indeed. Can you make a screenshot of your monitor settings? So I see arrangement, resolutions, scaling of each monitor, etc...

**Comment by sney** [comment]
Sure, here's both of them. 

![image](https://github.com/user-attachments/assets/76e845b4-82ca-42e9-8b39-b85cf1efedad)
![image](https://github.com/user-attachments/assets/d6d81459-a695-45c6-947e-126b28859544)

**Comment by sney** [comment]
The asus is 0,240 and the samsung is 2560,0.

**Comment by ilya-fedin** [comment]
I'm unable to get the same settings in VM, the nearest I got is 2048x1152 at 0,246 and 1920x1200 at 2048,0. With those settings, it's still unreproducible...

**Comment by sney** [comment]
I tested with a fresh user in case of any cruft in ~, and the problem remained. 

Then I launched Telegram from a terminal window and noted this output when launching the media viewer on the portrait screen, but not on the landscape screen: 
`qt.gui.imageio.jpeg: ./lib/jpegli/decode_scan.cc:535: Incomplete scan detected.`

**Comment by ilya-fedin** [comment]
> Then I launched Telegram from a terminal window and noted this output when launching the media viewer on the portrait screen, but not on the landscape screen:

I believe you have mis-tested it, it's a warning from the jpeg decoder and it appears depending on which jpeg you have looked at.

**Comment by ilya-fedin** [comment]
> I tested with a fresh user in case of any cruft in ~, and the problem remained.

I believe it's just a bug of old kwin, it likely provides wrong information about screen or something like that

**Comment by sney** [comment]
> > Then I launched Telegram from a terminal window and noted this output when launching the media viewer on the portrait screen, but not on the landscape screen:
> 
> I believe you have mis-tested it, it's a warning from the jpeg decoder and it appears depending on which jpeg you have looked at.

Some applications output useful debugging info if you start them from a terminal. I didn't know if this one was relevant so I shared it. 



> > I tested with a fresh user in case of any cruft in ~, and the problem remained.
> 
> I believe it's just a bug of old kwin, it likely provides wrong information about screen or something like that

Possibly. I guess we will find out next week once my term is done and I have time to fix my PC if needed.

**Comment by sney** [comment]
Still an issue in kwin 6, but now it's intermittent! Sometimes I can get the right arrow to appear, particularly if I click a smaller image that doesn't get zoomed in by the media viewer. But then browsing back/forth to different images always results in it disappearing again.

**Comment by ilya-fedin** [comment]
I need either to reproduce it locally to debug it or you to bisect the first bad version

**Comment by sney** [comment]
Alright. I'll see if I have time to bisect it and let you know. Probably after the new year. 

cheers

**Comment by ilya-fedin** [comment]
Another guess is that it's a bug in your graphics drivers in fact. If that's the case, disabling OpenGL in settings should help.

**Comment by sney** [comment]
> Another guess is that it's a bug in your graphics drivers in fact. If that's the case, disabling OpenGL in settings should help.

That was it! It's just mainline amdgpu running on a RDNA2 iGPU, though it has had some other regressions over the last year now that I think of it. Thanks for the support!

**Comment by ilya-fedin** [comment]
Maybe it's due to https://gitlab.freedesktop.org/mesa/mesa/-/issues/7217. This is a very old issue as you can see and there was a time when it was causing wrong media viewer size for everyone on KDE. GNOME is not affected as it force resizes fullscreen windows to screen size. It seem to be basically a disagreement between Qt and mesa on the order of actions that should lead to window resize. And sadly it seems no one is really bothered given that it's not fixed in 2 years.
