### ISSUE TITLE
Open lossless images fully setting

### ISSUE THREAD

**Issue by kupitmanzv** [telegramdesktop/tdesktop#28723]
### Is your feature request related to a problem?

-

### Describe the solution you'd like

1)Add (Open lossless photo: doc/fully) to advanced settings. Add ~graphical watermark in any corner of the image “LOSSLESS/LOSSY” depending on the type of image. Watermark in context visually when opening an image.

### Describe alternatives you've considered

-

### Additional context

and the same thing on android.

**Comment by ilya-fedin** [comment]
This isn't a place to propose UI changes. https://t.me/designers is.
