### ISSUE TITLE
Message times not matching system time format in linux

### ISSUE THREAD

**Issue by Violet-a** [telegramdesktop/tdesktop#2872]
### Steps to reproduce
1. Go to a chat room
2. Observe the time on each message isn't in 24hr format even though your system is set that way (issue circled in red)
![crisis](https://cloud.githubusercontent.com/assets/25191883/22050774/9285d186-dcf2-11e6-9aa8-5408eee7b3d3.jpg)

3. File a bug on Git Hub

### Expected behaviour
It should stick to the time format that the system is using.

### Actual behaviour
It uses 12hr am/pm format.
### Configuration
**Operating system:**
Linux Mint 17
**Version of Telegram Desktop:**
1.0
### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by YtvwlD** [comment]
It uses the 24hr format for me. (I've set the language to German.)

Perhaps it chooses the time format based on the language?
(This is not right. Language doesn't imply region.)

**Comment by unwind-protect** [comment]
export LC_TIME=en_GB in your system settings or write a wrapper script to launch telegram

**Comment by YtvwlD** [comment]
That would imply that Telegram correctly uses the system settings. Is that right?

**Comment by Aokromes** [comment]
#538
