### ISSUE TITLE
incomplete metadata when exporting a chat

### ISSUE THREAD

**Issue by UserWithoutName9** [telegramdesktop/tdesktop#28726]
### Steps to reproduce

in short, the bottom line is that telegram has a very cool function for exporting data/groups/chats/channels. I use it a lot. And it is possible to record the message data in a .json file. As I understand it, the main point of exporting to json is to save not only the data itself but also the metadata. After adding the Spoiler feature, it became possible to hide text and media under the spoiler graph, however, when exporting messages, only text messages have an "text": [{"type":"spoiler"},...]  metadata record. In other words, the problem (or request) is that everything else except the text has no mention that it was originally sent as a "spoiler". If you just send a picture and the same picture marked as a "spoiler", then in the json file you will not be able to distinguish in any way where the "spoiler" was and where it was not.

### Expected behaviour

The presence of any mark about the "spoiler" not only in the text but also in the media (for example, photos) in the final.json chat export

### Actual behaviour

the presence of a "spoiler" label only for text messages hidden by a spoiler

### Operating system

linux

### Version of Telegram Desktop

5.8.3

### Installation source

Static binary from official website

**Comment by 23rd** [comment]
Please check the v5.9.0.

**Comment by UserWithoutName9** [comment]
> Please check the v5.9.0.

Yes, the problem is solved in the new version, exactly as I saw it for myself. Thank you.
