### ISSUE TITLE
build_macstore

### ISSUE THREAD

**Issue by lcjllrwtt** [telegramdesktop/tdesktop#28738]
### Steps to reproduce

Where is the build_macstore variable defined and assigned?

### Expected behaviour

Where is the build_macstore variable defined and assigned?

### Actual behaviour

Where is the build_macstore variable defined and assigned?

### Operating system

macOS

### Version of Telegram Desktop

5.5.8

### Installation source

Mac App Store

### Logs

```shell
Where is the build_macstore variable defined and assigned?
```

**Comment by john-preston** [comment]
It is set in https://github.com/desktop-app/cmake_helpers/blob/master/variables.cmake#L86

It is not supposed to be used by anyone except the official Mac App Store builds.
