### ISSUE TITLE
Closing the window exits current chat

### ISSUE THREAD

**Issue by syabro** [telegramdesktop/tdesktop#2873]
### Steps to reproduce
1. Open the window and any conversation or chat
2. Press CMD + W
3. Open telegram by pressing icon in dock

### Expected behaviour
It should open chat that was active before the pressing CMD+W with message input focused

### Actual behaviour
No chat screen is now active — message "Please select a chat to start messaging" and search bar is active

### Configuration
**Operating system:**
OS X 10.11.6

**Version of Telegram Desktop:**
1.0

**Comment by auchri** [comment]
Works as expected

**Comment by syabro** [comment]
@auchri why? It's not convenient

**Comment by auchri** [comment]
Use search next time. #2541
