### ISSUE TITLE
Collapsible Codeblock Support

### ISSUE THREAD

**Issue by just-a-pony** [telegramdesktop/tdesktop#28740]
### Is your feature request related to a problem?

Currently, Quote already have collapse support,which is very useful to send long text,and not disturb others.

But for code,which is easily go beyond a hundred lines or more,do not have collapse support,and it's quite annoying sometime to go to use a web pastebin or something,especially since Telegram already have a great support for codeblock.

### Describe the solution you'd like

Just as Collapsible Quote,add a button or something.

### Describe alternatives you've considered

web pastebin,which was something that someone or in sometime just to annoying to use

**Comment by john-preston** [comment]
@just-a-pony This isn't supported by the API on the server.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
