### ISSUE TITLE
NO sound in telegram, videos also  play without sound,

### ISSUE THREAD

**Issue by samphonyy** [telegramdesktop/tdesktop#28746]
### Steps to reproduce

Hi guys, after installing telegram on the new PC i faced with this problem that no music plays in telegram and videos are without sound also ,however other apps work fine  so i belive  that sth has happend to it accidentally 

### Expected behaviour

play music or videos with sound

### Actual behaviour

the music bar on top freezes and does not move

### Operating system

windows x64

### Version of Telegram Desktop

5,9

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
check your mixer when playing a video with sound.

**Comment by samphonyy** [comment]
> check your mixer when playing a video with sound. also check if output is to default device or whatever device you use
I checked all every thing is working good.

**Comment by ilya-fedin** [comment]
> ### Logs
> 
> _No response_

The log?

**Comment by samphonyy** [comment]
> > ### Logs
> > _No response_
> 
> The log?

[ALSOFT] (II) Initializing library v1.22.0-3c8ac415 wasapi_exact_device_time
[ALSOFT] (II) Supported backends: wasapi, dsound, winmm, null, wave
[ALSOFT] (II) Loading config C:\Users\moham\AppData\Roaming\alsoft.ini...
[ALSOFT] (II) Got binary: C:\Users\moham\AppData\Roaming\Telegram Desktop, Telegram.exe
[ALSOFT] (II) Loading config C:\Users\moham\AppData\Roaming\Telegram Desktop\alsoft.ini...
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Vendor ID: ""
[ALSOFT] (II) Name: "Intel(R) Core(TM) i5-14600KF"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key rt-time-limit not found
[ALSOFT] (II) Key game_compat/reverse-x not found
[ALSOFT] (II) Key game_compat/reverse-y not found
[ALSOFT] (II) Key game_compat/reverse-z not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (II) Key drivers not found
[ALSOFT] (II) Starting message thread
[ALSOFT] (II) Message thread initialization complete
[ALSOFT] (II) Starting message loop
[ALSOFT] (II) Initialized backend "wasapi"
[ALSOFT] (II) Added "wasapi" for playback
[ALSOFT] (II) Added "wasapi" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (II) Key eax/enable not found
[ALSOFT] (II) Got message "Enumerate Capture" (0x0007, this=0000000000000000, param=0000000000000000)
[ALSOFT] (II) Got device "Microphone (4- Scarlett 2i4 USB)", "{D61CAA66-4A57-4977-AE52-88209E82DC6F}", "{0.0.1.00000000}.{d61caa66-4a57-4977-ae52-88209e82dc6f}"
[ALSOFT] (II) Got device "Stereo Mix (Realtek(R) Audio)", "{D67E850A-6D69-4AB0-9444-E7E068E37081}", "{0.0.1.00000000}.{d67e850a-6d69-4ab0-9444-e7e068e37081}"
[ALSOFT] (II) Got message "Enumerate Capture" (0x0007, this=0000000000000000, param=0000000000000000)
[ALSOFT] (II) Got device "Microphone (4- Scarlett 2i4 USB)", "{D61CAA66-4A57-4977-AE52-88209E82DC6F}", "{0.0.1.00000000}.{d61caa66-4a57-4977-ae52-88209e82dc6f}"
[ALSOFT] (II) Got device "Stereo Mix (Realtek(R) Audio)", "{D67E850A-6D69-4AB0-9444-E7E068E37081}", "{0.0.1.00000000}.{d67e850a-6d69-4ab0-9444-e7e068e37081}"
[ALSOFT] (II) Got message "Enumerate Capture" (0x0007, this=0000000000000000, param=0000000000000000)
[ALSOFT] (II) Got device "Microphone (4- Scarlett 2i4 USB)", "{D61CAA66-4A57-4977-AE52-88209E82DC6F}", "{0.0.1.00000000}.{d61caa66-4a57-4977-ae52-88209e82dc6f}"
[ALSOFT] (II) Got device "Stereo Mix (Realtek(R) Audio)", "{D67E850A-6D69-4AB0-9444-E7E068E37081}", "{0.0.1.00000000}.{d67e850a-6d69-4ab0-9444-e7e068e37081}"
[ALSOFT] (II) Got message "Enumerate Capture" (0x0007, this=0000000000000000, param=0000000000000000)
[ALSOFT] (II) Got device "Microphone (4- Scarlett 2i4 USB)", "{D61CAA66-4A57-4977-AE52-88209E82DC6F}", "{0.0.1.00000000}.{d61caa66-4a57-4977-ae52-88209e82dc6f}"
[ALSOFT] (II) Got device "Stereo Mix (Realtek(R) Audio)", "{D67E850A-6D69-4AB0-9444-E7E068E37081}", "{0.0.1.00000000}.{d67e850a-6d69-4ab0-9444-e7e068e37081}"
[ALSOFT] (II) Got message "Enumerate Playback" (0x0006, this=0000023BC56C9A48, param=0000000000000000)
[ALSOFT] (II) Got device "Speakers (4- Scarlett 2i4 USB)", "{4E099D59-DE7D-4530-B495-39EB62F27909}", "{0.0.0.00000000}.{4e099d59-de7d-4530-b495-39eb62f27909}"
[ALSOFT] (II) Got device "MSI G2712F (NVIDIA High Definition Audio)", "{83900B85-AEE5-4675-9C05-A3961E5ABC3B}", "{0.0.0.00000000}.{83900b85-aee5-4675-9c05-a3961e5abc3b}"
[ALSOFT] (II) Got message "Open Device" (0x0000, this=0000023BC56C9A48, param=0000023BC56DAEE0)
[ALSOFT] (II) Key frequency not found
[ALSOFT] (II) Key sources not found
[ALSOFT] (II) Key slots not found
[ALSOFT] (II) Key sends not found
[ALSOFT] (II) Created device 0000023BCD482030, "OpenAL Soft on Speakers (4- Scarlett 2i4 USB)"
[ALSOFT] (II) Key sample-type not found
[ALSOFT] (II) Key channels not found
[ALSOFT] (II) Key ambi-format not found
[ALSOFT] (II) Key period_size not found
[ALSOFT] (II) Key periods not found
[ALSOFT] (II) Key hrtf not found
[ALSOFT] (II) Pre-reset: Stereo, Float32, 44100hz, 882 / 2646 buffer
[ALSOFT] (II) Got message "Reset Device" (0x0002, this=0000023BC56C9A48, param=0000000000000000)
[ALSOFT] (EE) Unhandled channel config: 4 -- 0x00000000
[ALSOFT] (II) Requesting playback format:
    FormatTag      = 0xfffe
    Channels       = 2
    SamplesPerSec  = 44100
    AvgBytesPerSec = 352800
    BlockAlign     = 8
    BitsPerSample  = 32
    Size           = 22
    Samples        = 32
    ChannelMask    = 0x3
    SubFormat      = {00000003-0000-0010-8000-00aa00389b71}
[ALSOFT] (II) Got playback format:
    FormatTag      = 0xfffe
    Channels       = 4
    SamplesPerSec  = 44100
    AvgBytesPerSec = 705600
    BlockAlign     = 16
    BitsPerSample  = 32
    Size           = 22
    Samples        = 32
    ChannelMask    = 0x0
    SubFormat      = {00000003-0000-0010-8000-00aa00389b71}
[ALSOFT] (EE) Unhandled extensible channels: 4 -- 0x00000000
[ALSOFT] (EE) Failed to initialize audio client: 0x80070057
[ALSOFT] (EE) Device error: 0x80070057
[ALSOFT] (WW) Error generated on device 0000023BCD482030, code 0xa001
[ALSOFT] (II) Freeing device 0000023BCD482030
[ALSOFT] (II) Got message "Close Device" (0x0005, this=0000023BC56C9A48, param=0000000000000000)
[ALSOFT] (II) Got message "Enumerate Capture" (0x0007, this=0000000000000000, param=0000000000000000)
[ALSOFT] (II) Got device "Microphone (4- Scarlett 2i4 USB)", "{D61CAA66-4A57-4977-AE52-88209E82DC6F}", "{0.0.1.00000000}.{d61caa66-4a57-4977-ae52-88209e82dc6f}"
[ALSOFT] (II) Got device "Stereo Mix (Realtek(R) Audio)", "{D67E850A-6D69-4AB0-9444-E7E068E37081}", "{0.0.1.00000000}.{d67e850a-6d69-4ab0-9444-e7e068e37081}"

**Comment by ilya-fedin** [comment]
Please create an issue (describing the problem as well, of course) with that log at https://github.com/kcat/openal-soft/issues

**Comment by Sunnix01** [comment]
> ### Steps to reproduce
> 
> Hi guys, after installing telegram on the new PC i faced with this problem that no music plays in telegram and videos are without sound also ,however other apps work fine  so i belive  that sth has happend to it accidentally 
> 
> ### Expected behaviour
> 
> play music or videos with sound
> 
> ### Actual behaviour
> 
> the music bar on top freezes and does not move
> 
> ### Operating system
> 
> windows x64
> 
> ### Version of Telegram Desktop
> 
> 5,9
> 
> ### Installation source
> 
> Static binary from official website
> 
> ### Crash ID
> 
> _No response_
> 
> ### Logs
> 
> _No response_
