### ISSUE TITLE
Show image properties right in Telegram

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#2874]
I often need to see image properties of pictures that were sent within chats/groups/channels—to know the pictures solutions. At present time I had to save them in gallery or leave Telegram and open image in external app. It's inconvenient and it takes me too much time. So I wanna have command “Show image properties” in picture viewer (embedded in Telegram) context menu.

Win 8.1 & Android

**Comment by fluidpanda** [comment]
@Twilightssuperb what do you mean by picture solution?

you could very quickly click on a file or image that was send as file in telegram and then choose show in folder option and then go to properties, but images that send with a compression are different in size and smaller than original and they're displayed inline by design

**Comment by Aokromes** [comment]
Maybe he means exif data.

**Comment by stek29** [comment]
@Aokromes or re<b>solution</b>

**Comment by Aokromes** [comment]
exif contains resolution too :)

**Comment by Twilightssuperb** [comment]
EXIF will be enough for me. I just wanna know the pictures solutions directly in Telegram. Something like this: https://addons.opera.com/ru/extensions/details/view-image-info-properties/?display=en or
![21aef12b4bd0edb9a916bd4ed5a3c58a 1](https://cloud.githubusercontent.com/assets/7080928/22555892/61353c30-e976-11e6-9053-3507576c4659.jpg)
Present context menu in Telegram viewer:
![image](https://cloud.githubusercontent.com/assets/7080928/22556083/01ed4e56-e977-11e6-992e-5af67ede5aea.png)
Seems no way to get image properties **within** messenger. ☹

**Comment by ManuelSchneid3r** [comment]
Further please store the exif data when downloading pictures.

**Comment by stek29** [comment]
@ManuelSchneid3r what do you mean? Server erases exif data, unless picture was sent as file.

**Comment by ManuelSchneid3r** [comment]
@stek29 Yes exactly that's the problem. Why is the exif data cleared? These are a few bytes I guess.

**Comment by stek29** [comment]
@ManuelSchneid3r I don't know.
Maybe because:
- Telegram reencodes photos
- A few bytes per photo -- terabytes per day
- exif data is bad for anonymity

**Comment by ManuelSchneid3r** [comment]
> Telegram reencodes photos

But it is still JPEG, isnt it? Is just the size that is reduced.

> A few bytes per photo -- terabytes per day
> exif data is bad for anonymity

Yes I see but the ctime is still existant somewhere. At least the list of pictures show the date.

**Comment by alfredoivan** [comment]
I agree erasing exif by default is great.
Maybe adding an advance feature of letting users check if they want to preserve exif would be even better.

**Comment by stek29** [comment]
@alfredoivan send it as file

**Comment by Twilightssuperb** [comment]
Issue is still actual, it was closed accidentally.
