### ISSUE TITLE
USB audio DAC no audio notice sound issues

### ISSUE THREAD

**Issue by chaosdrop** [telegramdesktop/tdesktop#2875]
### Steps to reproduce
A:
1. Use only a USB DAC or USB Speakers
2. Sleep the computer wait a couple of moments and wake.
3. Telegram will no longer produce audio notifications until it is re-started
Seems to work about 1:20
B more consistent:
1. Telegram is set to automatically start with the system.
2. Telegram starts before the system recognizes USB Speakers / USB DAC
3. Telegram will produce no notification sounds until restarted.

### Expected behaviour
Audio notices should be heard.

### Actual behaviour
No audio notices can be heard.

### Configuration
Windows 10 64-bit
Tested with on-board audio card enabled and completely disabled same results.

**Version of Telegram Desktop:**
1.0

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by auchri** [comment]
Duplicate #776
