### ISSUE TITLE
In gnome-shell context-menu "Quit" doesn't quit, and there's another option that says "Quit telegram"

### ISSUE THREAD

**Issue by csaavedra** [telegramdesktop/tdesktop#28753]
### Steps to reproduce

In gnome-shell context-menu for telegram, there are two options to quit: "Quit" and "Quit telegram". The former only closes the window while telegram runs in background, the latter actually quits telegram. This is confusing and often I chose the wrong one.

This is installed from the Debian testing repository.

### Expected behaviour

Either rename "Quit" to "Hide" or just have one that actually quits the app.

### Actual behaviour

..

### Operating system

Linux and GNOME 47

### Version of Telegram Desktop

4.14.9

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Sorry but that's unimplementable. The "Quit" item is the system one and tdesktop has no way to rename it. The "Quit Telegram" one is the real quit and I don't see a better name for it.

**Comment by ilya-fedin** [comment]
That's also something e.g. Skype does so that's a common thing.

**Comment by csaavedra** [comment]
But then "Quit" could actually quit telegram and make "Quit Telegram" to be "Hide" instead?

**Comment by ilya-fedin** [comment]
No, it couldn't. The system "Quit" item just sends a window close event to my knowledge. And we don't want to quit on window close.

**Comment by ilya-fedin** [comment]
If anything, I guess you have to bug GNOME that they should either rename the item or make it to send a real quit signal (perhaps SIGTERM) rather than window close. The latter would then make custom quit items unnecessary.
