### ISSUE TITLE
Give users the option of selecting language for emoji shortcodes

### ISSUE THREAD

**Issue by lepinkainen** [telegramdesktop/tdesktop#28751]
### Is your feature request related to a problem?

I've been using chat programs since they have existed and my habits are deeply ingrained

Telegram, for some reason, has decided to translate the emoji names based on some rule I can't fathom.

Now when I try to type `:shrug:` nothing happens, because my language is detected as Finnish. So I'd need to type :kohautus: - a thing I would never write in any context.

The exact same issue is for all emojis. I have no clue what they're called in Finnish. I don't want to learn their names in Finnish. In most cases I don't type in Finnish and still the emoji names are translated.

### Describe the solution you'd like

Give users the option to revert back to the default english emoji names instead of forcing the translation based on some undocumented automated solution.

### Describe alternatives you've considered

I tried looking for a setting that allows me to stop this madness, couldn't find one.

**Comment by ilya-fedin** [comment]
I have non-English language in the app yet it does work:
![](https://github.com/user-attachments/assets/1dd9d606-9f91-4546-9f91-6ee41acd2c1b)

**Comment by ilya-fedin** [comment]
Maybe you're using some other client, not tdesktop?

**Comment by otanner** [comment]
I noticed the same issue, and discovered if I change my keyboard layout from Finnish to English I can use the English shortcodes. Changing the keyboard layout is of course not a solution but at least it looks like to be the reason why the shortcodes have changed.

I hope this "enhancement" can be disabled soon and I can get back to familiar English emoji shortcodes.

**Comment by arsenico13** [comment]
I have the same exact problem. All my shortcodes now are in italian and the english ones don't work anymore.
Like @lepinkainen, I have no clue what they're called in italian and I don't want to learn their names in Italian. 

I hope this get fixed soon.

@otanner thanks for the temporary workaround, I'll try that.

**Comment by Iniwuijshi** [comment]
Same issue here. Browsing emoji changed from English to German with update to 11.5.269857 on macOS Sonoma 14.7.1 with _Swiss German_ input source. But everything is setup in English (UK)

**Comment by cakism** [comment]
Same issue, seems to be dependent on keyboard layout like others have written, but not very consistent :S 
Very annoying...

![image](https://github.com/user-attachments/assets/ff16c66b-d290-4ce1-aeb2-fe8d13618abf)

**Comment by realChesta** [comment]
+1 same issue with german keyboard layout on version `11.5.269855 Stable` of the macOS desktop app.

**Comment by Aokromes** [comment]
> Same issue, seems to be dependent on keyboard layout like others have written, but not very consistent :S Very annoying...
> 
> ![image](https://private-user-images.githubusercontent.com/1278380/397385227-ff16c66b-d290-4ce1-aeb2-fe8d13618abf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTYxODUsIm5iZiI6MTczNDYxNTg4NSwicGF0aCI6Ii8xMjc4MzgwLzM5NzM4NTIyNy1mZjE2YzY2Yi1kMjkwLTRjZTEtYWViMi1mZThkMTM2MThhYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTlUMTM0NDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE1YTkwYWZhMDg2MDhhNWI3NWVjNDBiOTZkMzhkYjE0Njg0NWViNWI4Mzg1OGYzMDdkZjNhMDZiNTE0ZjUwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.l5zQBC1pbYbE1XqaS0ujQDAPN4PWMpP_5nbRn6yBsBI)

you are using https://github.com/overtake/TelegramSwift

**Comment by lepinkainen** [comment]
To anyone finding this thread in the future, this ticket in TelegramSwift is the correct place for this issue: https://github.com/overtake/TelegramSwift/issues/1200

**Comment by ilya-fedin** [comment]
I'm highly doubt that developers of other clients look at github issues. It's better to use either the in-app support or the official bugtracker (bugs.telegram.org).
