### ISSUE TITLE
Linux: image click - no preview, nothing happens :(

### ISSUE THREAD

**Issue by vitaly-zdanevich** [telegramdesktop/tdesktop#28761]
It works in one computer, but not in another :(
But I see the images in `~/Download/Telegram Desktop`

### Actual behaviour

sdfsa

### Operating system

Gentoo Linux

### Version of Telegram Desktop

5.5.5

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Can't reproduce
