### ISSUE TITLE
Telegram is not picking up the GTK theme on Ubuntu

### ISSUE THREAD

**Issue by euhurias** [telegramdesktop/tdesktop#28764]
### Steps to reproduce

Telegram is not taking the GTK theme on Ubuntu, every time I'm going to use tele fé it's weird and different from what I used before when I was using gtk Mac big sur

### Expected behaviour

Telegram is not taking the GTK theme on Ubuntu, every time I'm going to use tele fé it's weird and different from what I used before when I was using gtk Mac big sur

### Actual behaviour

Telegram is not taking the GTK theme on Ubuntu, every time I'm going to use tele fé it's weird and different from what I used before when I was using gtk Mac big sur

### Operating system

Ubuntu 24.04

### Version of Telegram Desktop

5.9

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
There's a separate app for macOS, that's why it looks different. tdesktop looks the same on any platform and that's intended.
