### ISSUE TITLE
Add proper support for background notifications on Linux without AppIndicator support OR a taskbar

### ISSUE THREAD

**Issue by ipg0** [telegramdesktop/tdesktop#28763]
### Is your feature request related to a problem?

Right now (as per the solution for #26197) the workaround is to enable "Close to taskbar", but on a Linux WM that doesn't have a taskbar and doesn't support minimised windows (e.g. Hyprland) the window just becomes impossible to close with this option enabled. However, it is still desirable to receive notifications while the client window isn't open.

### Describe the solution you'd like

Implement an *actual* background service/process that would be responsible for receiving notifications

### Describe alternatives you've considered

The current solution is either to add an AppIndicator tray (e. g. in waybar, which may not be desirable, since many users don't need/want one), or hack together a script to programmatically hide specific windows instead of closing them, like [how Hyprland docs suggest](https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#minimize-steam-instead-of-killing) (which is a major crutch and might be impossible in certain environments).

Neither of the options provides a proper way to keep Telegram running in the background _without dealing with side effects_ (the unneeded tray taking up useful space or having to un-"minimise" the client _manually_).

**Comment by ilya-fedin** [comment]
It was told many times that many-times-plicated issues about this problem aren't welcomed. What is welcomed is someone wanting that to actually do a patch, in a way explained [here](https://github.com/telegramdesktop/tdesktop/issues/16062#issuecomment-816868341).

**Comment by ipg0** [comment]
@ilya-fedin I believe this is not a duplicate. In the issue I linked to you specifically suggested the "close to taskbar" option as a solution, which is a bit hacky and doesn't work for all users.

In this issue I'm reporting a problem that has **not** yet been addressed, even if it is related to one that has. Namely, that the current solution doesn't take into account the fact that many environments don't support minimised windows (or a taskbar), which means many users don't have a way to get background notifications, besides enabling an AppIndicator tray (which is a _workaround with side effects_, not a solution).

As for submitting a patch, I've not worked in a C++-based stack and in a very long time, and I don't think I'll be able to find time to re-learn it and submit a patch (or more of a feature) myself.

**Comment by ilya-fedin** [comment]
> In the issue I linked to you specifically suggested the "close to taskbar" option as a solution, which is a bit hacky and doesn't work for all users.

I linked exact message which explains how a "run in background" option (not "close to taskbar" which already presents) has to be added.

> As for submitting a patch, I've not worked in a C++-based stack and in a very long time, and I don't think I'll be able to find time to re-learn it and submit a patch (or more of a feature) myself.

Linux support is worked on by the community. If the people who want the feature can't implement that, it will remain unimplemented.

**Comment by ilya-fedin** [comment]
The only thing I can propose to you is somehow hiding the window with your WM's capabilities, like moving to a separate workspace. That's not ideal but something at least.
