### ISSUE TITLE
QR code for desktop app sign not laoding

### ISSUE THREAD

**Issue by Zedx07** [telegramdesktop/tdesktop#28779]
### Steps to reproduce

1. When I have already signed in via mobile device I want to open the telegram in browser on PC. the QR code page just keeps on loading, I have got SS from network tab too

### Expected behaviour

QR code should be loaded and signed in after scanning via mobile app

### Actual behaviour

QR code page doesnt gets loaded, No response received from server
![image](https://github.com/user-attachments/assets/d5ac38a0-d163-456d-a4af-14eb68c0682f)

### Operating system

Windows 10

### Version of Telegram Desktop

Web app

### Installation source

Microsoft Store

**Comment by ilya-fedin** [comment]
This is the bugtracker of tdesktop, not web app

**Comment by Zedx07** [comment]
So where do I have to raise a issue?

**Comment by ilya-fedin** [comment]
bugs telegram.org perhaps
