### ISSUE TITLE
[Feature Request] Move "Lock" icon to left menu

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2877]
### Steps to reproduce
1. Minimize chats list to "Icons only" state
2. Try to find the "lock" icon

### Expected behaviour
Since the introduction of "Resizable chats list", reaching search field and "lock" icon (if local passcode is set) can be a bit difficult. 
I suggest moving the "lock" icon to the left menu (perhaps a separate color key should be made for it then). However, it will now require three clicks instead of two when chats list is completely hidden and two clicks instead of one when chats list is in its default state.
![image](https://cloud.githubusercontent.com/assets/2780044/22102139/64b2a3c8-de47-11e6-8e43-e9f3c1fa609f.png)
Mad Paint skills, sorry :D

P.S. This can also become a bit inconsistent with Android version, since clicking on left menu header on Android moves you to chat with yourself while on Desktop it closes that menu, but anyway, for those who don't remember `Ctrl+L`, this may be a better solution.

### Actual behaviour
The "lock" icon is unreachable when chats list is in "Icons only" state.

### Configuration
**Operating system:** Windows 10 LTSB x64.
**Version of Telegram Desktop:** 1.0.2

**Comment by john-preston** [comment]
@MasterGroosha You can just press Ctrl+F and press the lock :)

**Comment by MasterGroosha** [comment]
I know, but what about other users who will "lose" it? "Press «Search» to see the «lock» icon".
I think most of those people will just drag chats list to press that icon and then drag again to minimize :) Not perfect UX solution.

**Comment by john-preston** [comment]
@MasterGroosha Press Escape then :)

**Comment by MasterGroosha** [comment]
@john-preston Now it makes sense. Guess my issue is useless then :) Thanks!

**Comment by LestaD** [comment]
Maybe add to that panel?
![image](https://cloud.githubusercontent.com/assets/5620073/22105449/1c43bbc8-de55-11e6-99db-e917b97d605f.png)
