### ISSUE TITLE
Native SVG images support for telegram! 

### ISSUE THREAD

**Issue by gwpl** [telegramdesktop/tdesktop#28788]
### Is your feature request related to a problem?

I've tried to send svg, to find out it was send as jpg!

### Describe the solution you'd like

Native support for SVG images!Native support for SVG images!

### Describe alternatives you've considered

Sending SVG as file is not givng benefit of seeing in telegram what image is like.

Sending both: as image and as file is troublesome, especially if one would like to send e.g. gallery  of 10 svg images...

### Additional context

* not loosing data
* infinite resolution,scaliing
* long term storage svgs maybe smaller files to store on Telegram infrastructure
* while still for some time telegram can store jpeg renderings (or for backwards compatibility during transition period?)
* and allow users who want to send each other SVG files, to see how they look (like images, rendered) in telegram, choose which they want and download (to e.g. print)

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
