### ISSUE TITLE
Unable to send video file 8-bit H264 as video not as regular file

### ISSUE THREAD

**Issue by krasoffski** [telegramdesktop/tdesktop#28798]
### Steps to reproduce

1. Press button with clip 📎
2. Select with file manager file, e.g. `5532773-uhd_4096_2160_25fps.mp4`
 
Here is a link for used video sample: https://www.pexels.com/download/video/5532773/

```
ffprobe -show_streams 5532773-uhd_4096_2160_25fps.mp4 | grep -e codec_name -e bits_per_raw_sample
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '5532773-uhd_4096_2160_25fps.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomavc1
    creation_time   : 2020-10-05T20:23:11.000000Z
  Duration: 00:00:13.48, start: 0.000000, bitrate: 15121 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 4096x2160, 15118 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2020-10-05T20:23:11.000000Z
      handler_name    : L-SMASH Video Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
codec_name=h264
bits_per_raw_sample=8
```

@Aokromes said in #28796 that only H264 8-bit video can be sent as video not a file. But as described above this cannot be performed even with this requirements.

### Expected behaviour

There are options like: `Sent as regular file` and `Sent as video` like in mobile clients.

### Actual behaviour

File `5532773-uhd_4096_2160_25fps.mp4` is sent as regular file.

### Operating system

Linux 6.8.0-49-generic #49~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov  6 17:42:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Version of Telegram Desktop

5.9

### Installation source

Static binary from official website

### Additional info
![issue](https://github.com/user-attachments/assets/2c100814-e65b-4012-9d00-1dd3882491c4)

**Comment by ilya-fedin** [comment]
> @Aokromes said in #28796 that only H264 8-bit video can be sent as video not a file.

It was not @Aokromes.

And this is still not a bug as you're still trying to do some non-sense. I'm unable to reproduce the issue by using a video made with kdenlive's MP4 preset, with a common resolution (1920x1080).

**Comment by krasoffski** [comment]
@ilya-fedin 
What is wrong with video template https://www.pexels.com/download/video/5532773?

Could please share a videos you made with kdenlive's MP4 preset?

**Comment by ilya-fedin** [comment]
> What is wrong with video template https://www.pexels.com/download/video/5532773?

I'm unable to reach that link. If it's the same as ffmpeg output in this issue then it's likely to be the resolution, 4096x2160 is likely just bigger than the limits. But I'm not sure so I avoided speaking that to prevent you from creating new bug reports as this is not bug, just incompatible format, even if I don't know why it's incompatible exactly (there's no claim tdesktop is supposed to read any video).

If you want to just talk about that, there's a question type when opening issue that forwards to the community telegram group.

> Could please share a video you made with kdenlive's MP4 preset?

It would be much simpler if you moved this talk to the community group where you and would be able to just upload the videos to Telegram.

**Comment by krasoffski** [comment]
@ilya-fedin 
Thank you replay, I updated comment above.
