### ISSUE TITLE
Unable to send video file as video not as regular file

### ISSUE THREAD

**Issue by krasoffski** [telegramdesktop/tdesktop#28796]
### Steps to reproduce

1. Press button with clip 📎
2. Select with file manager file, e.g. `cats.mp4`

### Expected behaviour

There are options like: `Sent as regular file` and `Sent as video` like in mobile clients.

### Actual behaviour

File `cats.mp4` is sent as regular file.

### Operating system

Linux 6.8.0-49-generic #49~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov  6 17:42:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Version of Telegram Desktop

5.9

### Installation source

Static binary from official website

### Crash ID

No crashed

### Logs

Not required

**Comment by ilya-fedin** [comment]
This means the codec is not supported. Not a bug.
