### ISSUE TITLE
Proxy Support for Desktop App

### ISSUE THREAD

**Issue by naeemisial** [telegramdesktop/tdesktop#28795]
### Is your feature request related to a problem?

In Pakistan Telegram is banned. we are using with vpn or proxy on Mobile devices. But on Desktop there is no support for Proxy.

### Describe the solution you'd like

Add Proxy Support to Desktop

### Describe alternatives you've considered

I am Using VPN when i need to Use Telegram but VPN sometimes disturbed my other apps.

**Comment by ilya-fedin** [comment]
There's already proxy support in tdesktop
