### ISSUE TITLE
❗ Restore my Telegram account that was mistakenly deleted by Telegram ❗

### ISSUE THREAD

**Issue by okineadev** [telegramdesktop/tdesktop#28790]
### Steps to reproduce

.

### Expected behaviour

.

### Actual behaviour

Good afternoon, recently my @okinea account in Telegram was deleted by mistake

Everything happened like this:
I wanted to create a check in CryptoBot to send it to some chat, I created it and sent it to a chat called "/g/ Chat"
But suddenly the administrator banned me just for an innocent check (in my opinion, it would be better if he deleted the link and gave a warning that it is forbidden)

But the problem is different, after a few minutes my account suddenly disappeared!

I learned from the second account that it was deleted, I was just shocked, on that account I had money, important data, chats and my memories....
It was very hard for me and I was very shocked by this...
I just wanted to give someone a nice little gift...

Later I remembered that usually after spam bots are banned in other chats, they get deleted after a very short period of time, and I assume that my account was banned in that chat, and Telegram (maybe AI) saw it, and judging by my message (link to a check from CryptoBot) he decided I was a bot and blocked me
My account is at least several years old and has many memories in saved messages, also I am an admin of several telegram channels including @okinea_blog and @okinea_portfolio and my account was used to take freelance orders and contact people and family and my contact is listed on my website https://okinea.dev/ and https://github.com/okineadev.

Also, my account had a paid username called "@chosen_guy" which is very valuable to me and cryptocurrency in the wallet

So I'm begging you to give me back my account with all my data, I'm begging you to restore it !!!🙏🙏🙏🙏

I'm writing this here because I've written this dozens of times to Telegram support at all possible addresses, by email, support on the Telegram website, Telegram and Twitter support, no results

And I think that you (developers) or the main developer have connections with Telegram's support or administration, so if you can do it, I beg you to address it to someone so that my number is unblocked

### Operating system

.

### Version of Telegram Desktop

5.9.1

### Installation source

Static binary from official website

**Comment by Dimoka113** [comment]
For questions regarding restoration, this is not the place to write.
https://telegram.org/support

**Comment by okineadev** [comment]
> For questions regarding restoration, this is not the place to write. You can use: [telegram.org/support](https://telegram.org/support)

Like I said - I've done this a million times, and like I said, I posted it here so that the developer who is in contact with the moderators would directly address this issue to them so that they would notice it

**Comment by Dimoka113** [comment]
> > For questions regarding restoration, this is not the place to write. You can use: [telegram.org/support](https://telegram.org/support)
> 
> Like I said - I've done this a million times, and like I said, I posted it here so that the developer who is in contact with the moderators would directly address this issue to them so that they would notice it

Well, I don't think this is the best way to contact the creators, do as you see fit.

**Comment by okineadev** [comment]
> > > For questions regarding restoration, this is not the place to write. You can use: [telegram.org/support](https://telegram.org/support)
> > 
> > 
> > Like I said - I've done this a million times, and like I said, I posted it here so that the developer who is in contact with the moderators would directly address this issue to them so that they would notice it
> 
> Well, I don't think this is the best way to contact the creators, do as you see fit.

Do you think it is better to write to the developer in PM?

**Comment by Aokromes** [comment]
Sorry but this is telegram desktop bug tracker, nothing here belongs to user account administration.

**Comment by Aokromes** [comment]
> > > > For questions regarding restoration, this is not the place to write. You can use: [telegram.org/support](https://telegram.org/support)
> > > 
> > > 
> > > Like I said - I've done this a million times, and like I said, I posted it here so that the developer who is in contact with the moderators would directly address this issue to them so that they would notice it
> > 
> > 
> > Well, I don't think this is the best way to contact the creators, do as you see fit.
> 
> Do you think it is better to write to the developer in PM?

no, developer is developor, he doesn't handle user administartion.

**Comment by okineadev** [comment]
> > > > > For questions regarding restoration, this is not the place to write. You can use: [telegram.org/support](https://telegram.org/support)
> > > > 
> > > > 
> > > > Like I said - I've done this a million times, and like I said, I posted it here so that the developer who is in contact with the moderators would directly address this issue to them so that they would notice it
> > > 
> > > 
> > > Well, I don't think this is the best way to contact the creators, do as you see fit.
> > 
> > 
> > Do you think it is better to write to the developer in PM?
> 
> no, developer is developor, he doesn't handle user administartion.

I understand, and the developer most likely has the closest contact with the administration, so I only ask that you forward this statement to the moderators so that we can solve this problem with the mistaken deletion of my account

**Comment by okineadev** [comment]
> Sorry but this is telegram desktop bug tracker, nothing here belongs to user account administration.

I've sent this everywhere I can, nothing has worked, what else do you want?
If you want to help - pass this statement to the moderators so they can read it and solve the problem, please

**Comment by okineadev** [comment]
I want this to be noticed and this problem solved, I will not put up with this and I will not give up

**Comment by okineadev** [comment]
@john-preston

**Comment by Aokromes** [comment]
> @john-preston
spamming here won't help you to restore your account.

**Comment by okineadev** [comment]
> > @john-preston
> spamming here won't help you to restore your account.
> 

Where should I spam?

**Comment by okineadev** [comment]
So that my message is read

**Comment by okineadev** [comment]
> This is happening to a lot of people - accounts get banned for no reason, it just disappears suddenly and randomly. Telegram is no longer reliable. You will lose memories and chats one day. There is no proper contact or support. Their twitter/x handle [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/smsTelegram?size=32">@smsTelegram](https://github.com/smsTelegram?rgh-link-date=2025-02-03T10%3A51%3A58.000Z) got suspended. I have been spamming them there to restore my accounts since months and never got a response. It is a pity how little they care about users by randomly banning their accounts without reason. They control our accounts and data. Beware before using this app. Whatsapp seems better now.

You can use Telegram, but you need to be ready, have a second sim just in case, and save data only on a flash drive, not in saved messages

By the way, my third account has already been deleted!

Two accounts were recently deleted for absolutely no reason

**Comment by okineadev** [comment]
> They control our accounts and data. Beware before using this app.

I'm not sure about that, I have other guesses about it, but let's not discuss it here
