### ISSUE TITLE
crashes with newest qt6 linraries

### ISSUE THREAD

**Issue by df8oe** [telegramdesktop/tdesktop#28793]
### Steps to reproduce

1. install on system with newest (testing) qt6
2. start the application

### Expected behaviour

Telegram-desktop should start and be accessible

### Actual behaviour

The window opens but is fozen. After a few seconds it closes, telegram-desktop crashes This is due to a changed behaviour in qt6 libs which will step into stable qt6 next time. In the error logs appears

Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter

### Operating system

Archlinux testing, kde-testing, newest (testing) qt6 libraries

### Version of Telegram Desktop

5.9.0-3

### Installation source

Static binary from official website

### Logs

```shell
Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
```

**Comment by Aokromes** [comment]
plz try downloading official static (non-flakpak, non-snap, non-linux distribution package) version from https://desktop.telegram.org

**Comment by df8oe** [comment]
official static throws same error in logs but stays usable.
