### ISSUE TITLE
Feature suggest: Add the function of auto-hiding posts by keywords.

### ISSUE THREAD

**Issue by vacterro** [telegramdesktop/tdesktop#28794]
### Is your feature request related to a problem?

Current problem: At the moment, there is a telegram channel with the necessary educational content on a wide range of software and their branches.

I would like to somehow have a filtering function for this.

### Describe the solution you'd like

Add a keyword filter function.

Make a rule: Is there a word, are there words, is there at least one of and similar rules.

### Describe alternatives you've considered

There is currently no alternative.

### Additional context

Perhaps this option has already been proposed, but I would still like this function very much, specifically for Telegram channels.

Let it be at least a function for premium users, that would be enough.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/
