### ISSUE TITLE
please fix this bug 

### ISSUE THREAD

**Issue by U-13nknow79-N** [telegramdesktop/tdesktop#28809]
### Steps to reproduce

in settings - advanced - system integration lunch minimized not worked when i se t a password for telegram why ? 

### Expected behaviour

in settings - advanced - system integration lunch minimized not worked when i se t a password for telegram why ? and when i close the app - The program closes completely. I want it to automatically minimize when the program has a password and not be on the startup screen. The WhatsApp program minimizes even when I set a password.

### Actual behaviour

Hello and don't be tired, please fix a bug as soon as possible. There is a bug in the PC version of Telegram Windows. In the settings, in the advanced settings, I check the auto-start option to minimize. It turns off in minimized mode by setting the password. That is, in WhatsApp, when I enter the password, there is no such problem without first asking for the password and then the program runs, but in Telegram, we have to enter the password. Minimized does not run. Please add the option. Thank you.
![image_2024-12-28_19-06-27](https://github.com/user-attachments/assets/bab09b56-366e-4193-a1cc-89581433a3c2)

### Operating system

win11*64

### Version of Telegram Desktop

5.9.2

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Unfortunately in TDesktop there is no sense in running the app without initial local passcode unlock.

When you launch the app locked with a passcode the server access credentials are encrypted on the disk using this passcode, so until you enter the passcode there is no way to connect to the server and start receiving updates about new messages or anything.

So if you launch the locked app minimized and won't unlock it, there is no sense in such launch, it won't work anyway until you unmininize and unlock it. So there is no sense to enable autostart minimized with a passcode lock. Either you unlock it or you don't need to launch it at all.

**Comment by elvisisvan** [comment]
the writings, the customizations, the assumed self-aggrandizement, you're delirious

**Comment by john-preston** [comment]
What? 😆

**Comment by elvisisvan** [comment]
> What? 😆

oh c'mon john you can't tell me you don't see it in his writings lol

**Comment by angelwingsjp** [comment]
> The WhatsApp program minimizes even when I set a password.

because they don't protect your data
tdesktop stores a minimum of data on the drive - only your session and attachment cache
