### ISSUE TITLE
Issue with Command Suggestions Display When Typing Slash in Telegram Web  

### ISSUE THREAD

**Issue by icekristal** [telegramdesktop/tdesktop#28804]
### Steps to reproduce

1. Open the web version of Telegram.  
2. Enter any group chat.  
3. Type the slash (/) symbol in the message input field.  

### Expected behaviour

A list of available commands with suggestions should appear, as it does in bot chats.  

### Actual behaviour

In group chats, the list of commands does not appear after typing the slash (/). However, suggestions work correctly in bot chats.  
![photo_2024-12-27_10-44-19](https://github.com/user-attachments/assets/46047eeb-a654-4e16-aa69-61de1cdd5f00)

### Operating system

Tested on Windows 10, Windows 11, and Mac.  

### Version of Telegram Desktop

Telegram Web K

### Installation source

Static binary from official website

### Crash ID

Not applicable.  

### Logs

```shell
Not applicable.
```

**Comment by Aokromes** [comment]
Sorry but this is telegram desktop bug tracker, use bugs.telegram.org for telegram web.
