### ISSUE TITLE
'Tribute' app displays empty screen on Debian (apt and local beta) desktop app

### ISSUE THREAD

**Issue by BertBril** [telegramdesktop/tdesktop#28802]
### Steps to reproduce

![tribute_app](https://github.com/user-attachments/assets/b3d77d9d-657e-4d56-aff8-4eab4419ce82)
1. Got me a link from a channel I like to support: tg://resolve?domain=tribute&appname=app&startapp=sbOe
2. In my desktop app, a new window is opened 'Tribute'. It's empty. Any menu item I choose also delivers an empty window. The popped up window is therefore always empty.

### Expected behaviour

I'd expect content in the new window, enabling me to use the 'Tribute' app.

### Actual behaviour

A window pops up, but it's empty. I cannot use the app.

### Operating system

Debian bookworm stable 12.8. KDE/Plasma 5.27.5

### Version of Telegram Desktop

4.6.5 and 5.9.2-beta

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
That's likely an issue with your system webview engine, it likely just doesn't support HTML/CSS/JavaScript features the app needs

**Comment by BertBril** [comment]
Wow easy come easy go. Of course my 100% regular stable installation of Debian Linux, 100% up-to-date must be the problem. Unbelievable. What a joke, and I put in a lot of time to file this report, tested on different versions, ...

And don't give me the 'it's open source' shit, I've made Open Source software for 25 years, and always felt responsible for users that simply couldn't get their stuff working.

The new generation is there. Entitled, arrogant.

**Comment by ilya-fedin** [comment]
> Of course my 100% regular stable installation of Debian Linux, 100% up-to-date must be the problem.

Those apps are third party and I'm highly doubt they're tested on Linux at all. They're likely tested only for Windows and Android whose system web engines are way more powerful, due to being based on Chrome.
