### ISSUE TITLE
Cannot send images without compression

### ISSUE THREAD

**Issue by kgizdov** [telegramdesktop/tdesktop#2881]
Sometimes I need to send a screenshot or other type images that depend on fine detail being legible - text, small edge details, etc. On the desktop version of Telegram, there is no way to force the image to not be compressed, which defeats the purpose of sending that image in the first place.
### Steps to reproduce
1. Attach an image
2. Send it
3. Watch it drop in resolution significantly...

### Expected behaviour
There should be a way to send images without compression when needed

### Actual behaviour
Images that need high-detail, even when they are small in file size (<400kb), are still compressed beyond recognition

### Configuration
**Operating system:** Linux

**Version of Telegram Desktop:** 1.0.0

**Comment by john-preston** [comment]
@kgizdov When you send jpg or png or image from clipboard there is a preview of sending with a "compress" checkbox.

**Comment by kgizdov** [comment]
oh, yes, there is, my bad...

**Comment by amanuel1995** [comment]
How do I disable that feature completely and always send without compression on Samsung androids
