### ISSUE TITLE
Maximize,Minimize Telegram will reduce its width everytime

### ISSUE THREAD

**Issue by tavrez** [telegramdesktop/tdesktop#2883]
### Steps to reproduce
1. Maximize Telegram window
2. Restore it to window size again
3. It has lower width than previous time
4. Repeating it will make it smaller and smaller

### Expected behaviour
Fixed width

### Actual behaviour
Resizing window

### Configuration
**Operating system:Windows 10 Pro build 1607

**Version of Telegram Desktop:1.0.2

**Comment by auchri** [comment]
Duplicate of #2585 #2327
