### ISSUE TITLE
work mode options not displayed correctly in update 1.0.2

### ISSUE THREAD

**Issue by MetaiR** [telegramdesktop/tdesktop#2884]
hello,
If resize to see just profile picture (and you activated `WorkMode`) you can see just half of its text.
I think if it has an icon it will be greater in this mode.
![screenshot from 2017-01-19 23-14-37](https://cloud.githubusercontent.com/assets/7807264/22122543/9c541180-de9d-11e6-90c7-df7281b37700.png)

**Comment by john-preston** [comment]
@MetaiR This is an unofficial feature :)

**Comment by stek29** [comment]
@john-preston but it is there, and it is a feature.
It's not a priority of course, but IMO this should be fixed.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
