### ISSUE TITLE
1.0.2 align messages incorrectly when maximized

### ISSUE THREAD

**Issue by thiagodp** [telegramdesktop/tdesktop#2887]
### Steps to reproduce
1. Open Telegram Desktop.
2. Maximized it.

### Expected behaviour
My messages continue on the right side and people's message continue on the left side.

### Actual behaviour
All the messages aligned on the left side.

### Configuration
Windows 10, Telegram 1.0.2

### Logs
None.

**Comment by auchri** [comment]
use search
