### ISSUE TITLE
Key combination to jump to unread chat

### ISSUE THREAD

**Issue by moookino** [telegramdesktop/tdesktop#2890]
It would be nice to have key combination to jump to chat with unread messages, without need to use mouse for selecting chat

For example
1st variant
1.Press key combination show list of unread chats
2.Arrow up/down to select from list
3.Enter to open selected unread chat

2nd variant
1.Ctrl/Cmd 1-5 to select one of pinned chat Ctrl/Cmd + some other key to select first not pinned chat

Thanks for all your work! 😸

**Comment by DennisNerush** [comment]
What combination do you have in mind?

**Comment by moookino** [comment]
Maybe something like Ctrl/Cmd + R - like Reply command

**Comment by T3rminat0r** [comment]
Adding to this - now that mentions are tracked by telegram - can we get something like CTRL+M to jump to next mention (starting from oldest or newest, but consistent in that order) ignoring other unread chats?

**Comment by DmitryKuzmenko** [comment]
There is a combination to jump to the next/previous chat: Alt + Up/Down.
As for me it's enough to add Alt + Shift + Up/Down to jump to the next previous channel containing unread content as it's done in Slack/Mattermost.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1060
