### ISSUE TITLE
No "lock telegram" button on UI when chat list minimized to profile pictures

### ISSUE THREAD

**Issue by GanjaBoss** [telegramdesktop/tdesktop#2891]
### Steps to reproduce
1.  Turn on local password
2.  Minimize the chat list into a column of profile pictures
3.  Find no Lock button on UI without resizing back

### Expected behavior
Should be access to lock telegram client without resizing UI

### Actual behavior
No way to lock telegram window without resizing chat list or waiting for auto-lock

### Configuration
**Operating system: Win10**

**Version of Telegram Desktop: 1.0.2**

**Comment by auchri** [comment]
Press strg+f or esc.
