### ISSUE TITLE
Minimizing chat list into a column of profile pictures is cancelled after opening app from tray

### ISSUE THREAD

**Issue by gyunter** [telegramdesktop/tdesktop#2892]
### Steps to reproduce
1. Resize the list by clicking and dragging to make chat list pictures-only
2. Close telegram to tray
3. Open telegram from tray

### Expected behaviour
Telegram chat list should be opened with the same picture-only view

### Actual behaviour
Telegram chat list opens with default view: profile pictures and names. It turns into picture-only view after you click on any chat in chat list.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
v 1.0 11.01.17

**Comment by MetaiR** [comment]
I have the same problem

ubuntu 16.10

**Comment by john-preston** [comment]
@MetaiR It is not cancelled, just the chat is closed. In this mode if no chat is opened you see full chats list to be able to search in it for conversations.
