### ISSUE TITLE
No context menu with touchscreens

### ISSUE THREAD

**Issue by KarlTheBee** [telegramdesktop/tdesktop#2896]
### Steps to reproduce
1. press the touchscreen long at the message textbox 

### Expected behaviour
If you click on the chat list at the left, the long-press touch input works fine and i see a context menu like that if you click with the right mouse
However, the same procedure at the message textbox, no contextmenu shows up

### Actual behaviour
No context menu shows up

### Configuration
windows 8.1 / 10

**Version of Telegram Desktop:**
1.0.2
(pre 1.0.0 versions worked)

**Comment by Aokromes** [comment]
#218 ?
