### ISSUE TITLE
open chats in separate tabs 

### ISSUE THREAD

**Issue by MetaiR** [telegramdesktop/tdesktop#2897]
I hope it's not duplicate.
it's just a suggestion.

we have more spaces than a smartphone on a PC,  I just think it'll be very nice if each chat can be opened on a separate tab like a browser that you can see a website on different tabs. so this can save lots of time and help for chatting with multi persons.

does it possible?

**Comment by john-preston** [comment]
@MetaiR It is not possible right now :( the app is not written well enough.. yet.

**Comment by MetaiR** [comment]
can it be a feature to work on in the future?

**Comment by john-preston** [comment]
@MetaiR Yes, it can be. But there are too many problems currently, so I don't know when I'll be able to work on that:(

**Comment by gudvinr** [comment]
@MetaiR for what? We already have chats list so why do you need another one?

**Comment by Vilmodao** [comment]
@MetaiR 
It's alredy here. You have tabs already. Not on top side but on the left.

**Comment by MetaiR** [comment]
@gudvinr @Vilmodao 
if you have the top one it'll just have a few ones which you talk to theme right now not all of the chats,
 for example, I have about 100 chats (including channel and groups) . I usually checked 20 from theme every hour and sometimes other chats
so if I have a both list (like a browser) I can reach them very faster and can close theme and open others

**Comment by pazis** [comment]
@john-preston Long time, no progress :sob: 

This is really an important feature. Channels and chats update more regularly than personal chats and they come up the list. When somebody is member of a lot of channels and chats, it is really disturbing. 

What are those many problems preventing you from implementing this feature? It looks like easy from distance by the way!

**Comment by john-preston** [comment]
@pazis Currently the app is written badly, it supports only one chat display in the entire process (a lot of code works with that single chat view instance directly). So to support displaying several chats in different tabs a lot of things should be rewritten.

**Comment by RememberTheAir** [comment]
Hey, it would still be pretty cool to be able to open chats in a separate window

**Comment by erfanium** [comment]
I really need this feature!!

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v3.7.6
