### ISSUE TITLE
(Windows) Titlebar color is too hard to distinguish

### ISSUE THREAD

**Issue by hibiyasleep** [telegramdesktop/tdesktop#2898]
![image](https://cloud.githubusercontent.com/assets/5380174/22162277/5f416c6c-df91-11e6-8570-7a895eebcc9d.png)

As title says, titlebar is *too white*, which user may get confused with inactive window or background.

May better with system tint color, or old good blue-color.

ed) Windows in picture, back-to-front: GitHub, inactive Windows 10 Settings app, active TelegramDesktop window.

**Comment by ralesk** [comment]
Seems to be a fad lately, with Gnome 3, Windows, etc. all doing white on white pretty much :)  I haven't looked into the theming, if it can show different colours when focused and when unfocused, but it would be really nice to get either system tint colour or the old telegram blue when focused, and grey when unfocused.

**Comment by fluidpanda** [comment]
@ralesk yeah, it could be very nice to have an option to colour inactive window as we do now with active window colour using windowBg variable, something like windowsBgInactive for example

**Comment by MasterGroosha** [comment]
Just a comment: 
As of TDesktop 1.0.2 there're two keys for Title Bar theme: titleBgActive and titleBg. Theme creators can adapt their themes for your issue.

**Comment by fluidpanda** [comment]
@MasterGroosha thanks, but titleShadow should be in two versions: titleShadow for inactive window and titleShadowActive for window in focus

**Comment by levicki** [comment]
I second this request, there is absolutely no difference between active Telegram window title and inactive Firefox window on my system:

![image](https://cloud.githubusercontent.com/assets/16415478/23143853/f982ab3e-f7c3-11e6-8d94-8edbcc71459f.png)

On the other hand, other applications use my system color preference when they are active:

![image](https://cloud.githubusercontent.com/assets/16415478/23143881/289fd43c-f7c4-11e6-8826-fc5bcee02aa6.png)

In my opinion this should not be a matter of theme. System-wide settings exist for a reason and should be obeyed by all programs by default unless user actually wants to override them on a program by program basis.

**Comment by auchri** [comment]
> In my opinion this should not be a matter of theme. System-wide settings exist for a reason and should be obeyed by all programs by default unless user actually wants to override them on a program by program basis.

#2818 #2958
