### ISSUE TITLE
Feature Request Watch videos and audio inside the program

### ISSUE THREAD

**Issue by TheAppService** [telegramdesktop/tdesktop#29]
Hello,

could you perhaps integrate a feature which allows us to watch videos / listen to audio messages inside the program ? I think there are some open source players on the internet which you can integrate in this program easily.

That would be fine.

Thanks

With best regards

Daniel Ebert

**Comment by Aokromes** [comment]
Any hope for video playing? :)

**Comment by AryanShadowhunter** [comment]
Certainly this is an important feature

**Comment by formatq** [comment]
Video player have implemented since [v0.10](https://github.com/telegramdesktop/tdesktop/tree/v0.10)
