### ISSUE TITLE
(Windows) Default korean font is old and pixelated

### ISSUE THREAD

**Issue by hibiyasleep** [telegramdesktop/tdesktop#2900]
![Current](https://cloud.githubusercontent.com/assets/5380174/22166213/483d9538-dfa3-11e6-875f-edf9b1dcfae1.png)

This font, 'Gulim', is semi-bitmap font and majorly used until Windows XP. This font doesn't render as pixelated (even not a default) in other platform.

![Suggested](https://cloud.githubusercontent.com/assets/5380174/22166241/6f14a9e4-dfa3-11e6-828b-5fe6a553f423.png)

Suggested one for Windows, is 'Malgun Gothic' (맑은 고딕), which replaces Gulim from Windows Vista, and have Latin glyphs similar with 'Segoe UI'.

**Comment by auchri** [comment]
#589
