### ISSUE TITLE
Narrowing/Minimizing the contact list, sends all the chats in the main window onto one side

### ISSUE THREAD

**Issue by DynamicJoker** [telegramdesktop/tdesktop#2902]
### Steps to reproduce
1. Narrow/Minimize the contact list by dragging to the left. 
2. Look at your open chat on the right

### Expected behaviour
Sent and Received messages should be left aligned and right aligned. 

### Actual behaviour
Sent and Received messages show up in a single column, both left aligned.

### Configuration
**Operating system:**
Windows 10 x64
**Version of Telegram Desktop:**
1.0.2

**Comment by MasterGroosha** [comment]
If your history window size (where messages from currently selected chat are displayed) becomes big enough, alternative layout may trigger. To "fix" this, maximize your window, go to settings and uncheck "Adaptive layout for wide screens" option (located somewhere near background options)
