### ISSUE TITLE
Make tray icon a scalable vector graphic (svg) instead of a bitmap

### ISSUE THREAD

**Issue by biels** [telegramdesktop/tdesktop#2906]
Currently the tray icon looks really bad since it is resized by the system and it is a bitmap. 
I think it should be quite easy to change the icon to a scalable vector one.
This is how it looks on my system (KDE Plasma):
![image](https://cloud.githubusercontent.com/assets/5158960/22178335/b94a42cc-e033-11e6-81ff-cc23a457e9cd.png)

**Comment by stek29** [comment]
#2230
