### ISSUE TITLE
Telegram ignores changes to the default playback device

### ISSUE THREAD

**Issue by beppe9000** [telegramdesktop/tdesktop#2909]
### Steps to reproduce
1. Start telegram client
2. play a voice message to verify that playback on the current playback device works
3. click the speaker icon on the taskbar and change the default audio playback device from the dropdown menu
4. Play a voice message
5. Telegram does not comply with the new setting and instead keeps playing audio files to the playback device that was set as default when it was started in step 1.

### Expected behaviour
Telegram complies with the change of default audio device.

### Actual behaviour
Telegram ignores the change

### Notes
 - Related: #2690 (invalidate audio handles) &  #2727 (microsoft rdp changes the default playback device for the duration of the session)
 - If the default playback device is reverted to the one active at telegram's start-up audio will play on that 
device.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.0.2

**Comment by beppe9000** [comment]
@auchri could you link the original issue, please?

**Comment by auchri** [comment]
No, use search

**Comment by beppe9000** [comment]
Come on be constructive! I tried searching before posting.  #776

**Comment by nachoparker** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  pkbrister@zoho.com
    Domain ownyourbits.com has exceeded the max emails per hour (3/3 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:25051)
	by skywalker.onesite.co with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7866-nacho=ownyourbits.com@sgmail.github.com>)
	id 1cVgXf-002Lh2-6g
	for nacho@ownyourbits.com; Mon, 23 Jan 2017 10:28:23 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=fzgDEUlgkgRtK1LyYognrU5tENg=; b=KJg4HRc71unphYTC
	vq3Wg1/1J61G5QMd/mHLIpz3LJWaKlJE4RHkxDMzgbAMOiSN6goguibjdb+uSqnP
	9mKBA8OQmAbvfg1xGJNpjv65V6DtQbqSEW8T3gI8tMkIsT9AaYugdvl+J22BlN3D
	Nfoy+t9XQcdpT6B8Udw2GMPr63Q=
Received: by filter0596p1mdw1.sendgrid.net with SMTP id filter0596p1mdw1-10965-588620EE-2F
        2017-01-23 15:27:42.437775678 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id 9pVgoWzURhi2cp5lVqDD9w
	for <nacho@ownyourbits.com>; Mon, 23 Jan 2017 15:27:42.174 +0000 (UTC)
Date: Mon, 23 Jan 2017 07:27:42 -0800
