### ISSUE TITLE
[feature-request] Add shortcodes as used by much organizations

### ISSUE THREAD

**Issue by Alber70g** [telegramdesktop/tdesktop#2910]
Wouldn't it be nice to use the shortcodes as they are used by a lot of other apps. These two pages could guide as reference:
1. [Emoji's with shortcodes](http://www.webpagefx.com/tools/emoji-cheat-sheet/)
1. [Emoji's with unicode and bytes](http://apps.timwhitlock.info/emoji/tables/unicode)

**Comment by auchri** [comment]
7

**Comment by Alber70g** [comment]
Duplicate of what? I couldn't find an issue with 'shortcode[s]'

**Comment by auchri** [comment]
#627
