### ISSUE TITLE
Messages I sent show up in a on the left side with other messages

### ISSUE THREAD

**Issue by Fatemeh-Mo** [telegramdesktop/tdesktop#2911]
When I send a message (in a group or a private chat), it shows up on the left side with other messages that others have sent. It wasn't like this in the previous versions. It is a very good feature to be able to visually recognize messages of myself.

I think that some people would like all the messages to show up on one side in groups and channels (but not private chats, of course). So maybe it would be good to put some option in the settings page that reads "Put all the messages on one side in groups and channels".

I use Telegram Desktop version 1.0.2.

**Comment by MasterGroosha** [comment]
"Alternative layout for wide screens" option is what you're looking for.

**Comment by Fatemeh-Mo** [comment]
@auchri What issue is this one duplicate of?

**Comment by stek29** [comment]
@Fatemeh-Mo you can see incomplete list in #3262.
