### ISSUE TITLE
ХУЙ!11

### ISSUE THREAD

**Issue by hr111** [telegramdesktop/tdesktop#2913]
Пизда и Джигурда!

Пашка дай денег? А? Нужен лям на статуп!!!

**Comment by auchri** [comment]
English please

**Comment by nachoparker** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  pkbrister@zoho.com
    Domain ownyourbits.com has exceeded the max emails per hour (3/3 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:46823 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by skywalker.onesite.co with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cVjXt-002pLy-Q8
	for nacho@ownyourbits.com; Mon, 23 Jan 2017 13:40:49 -0500
Date: Mon, 23 Jan 2017 10:40:08 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485196808;
	bh=VGbAFZvYS5vsyp60Y2nCCunW532tOWDMEU54+NcAqhs=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=o2V8qVeSIjIyUpegfIBB67FYYnj9CqmTnyEnBthEk0AbiMWtN22M+x90gqUZF15hj
	 y+wqA0LSgqtORubgTy/x7J3OLQIZp02bnCK87rblkq+6DYzGo2EM3gvGzg5ponwJAe
	 NAkRCqqQWXGIXnR1026bpE600LzBSL/7eQlw3CVc=

**Comment by stek29** [comment]
GitHub definitely needs a "facepalm" reaction.
