### ISSUE TITLE
List unread group members

### ISSUE THREAD

**Issue by ldrrp** [telegramdesktop/tdesktop#2916]
See who has and has not read the message in the group with some kind of icon

![image](https://cloud.githubusercontent.com/assets/985837/22223301/6b39794e-e188-11e6-9efe-c3a1991418c7.png)

**Comment by ldrrp** [comment]
@auchri Can you let me know what the duplicate one was? I was unable to find any while i searched

**Comment by auchri** [comment]
#2888 

It seems really hard for some people to use the search

**Comment by nachoparker** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  pkbrister@zoho.com
    Domain ownyourbits.com has exceeded the max emails per hour (3/3 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:25938)
	by skywalker.onesite.co with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7866-nacho=ownyourbits.com@sgmail.github.com>)
	id 1cVmDR-003LW8-5a
	for nacho@ownyourbits.com; Mon, 23 Jan 2017 16:31:53 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=kUgbf5Vb6OOepgwwksvkEB+Hp8Q=; b=IQBHqkgUVFV/6Tei
	MMxlRFO3NOLmTzNM4pXxyUHtUqlg2xGN/MuuGCZPqE3U3gt35Kizx+Rkztsp14pj
	ilEni/mHv1GNIxmLSOuydVSwnfAEC7w/qWx4EGj+D0XpgvY6xqmgVB5xo3CiT/DS
	F4J7jMpRrvEAuTs6kGAuBUou0n8=
Received: by filter0539p1mdw1.sendgrid.net with SMTP id filter0539p1mdw1-22341-58867620-19
        2017-01-23 21:31:12.47354035 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id 8Hl8z4fDQue8M83EVDXPVA
	for <nacho@ownyourbits.com>; Mon, 23 Jan 2017 21:31:12.475 +0000 (UTC)
Date: Mon, 23 Jan 2017 13:31:12 -0800

**Comment by ldrrp** [comment]
@auchri or maybe the other bug title is super long and cant be found with search as ive tried.... rude

**Comment by auchri** [comment]
![image](https://cloud.githubusercontent.com/assets/5092164/22223726/45144f80-e1bc-11e6-9556-91c7512633fd.png)

Your are not the only one

**Comment by ldrrp** [comment]
Any chance u know were to send ppl for api ussues?

**Comment by stek29** [comment]
@ldrrp check other <kbd>api issue</kbd>s.
