### ISSUE TITLE
Add "msg" and "share" behaviour in links like on Android App

### ISSUE THREAD

**Issue by FabianPastor** [telegramdesktop/tdesktop#2917]
It would be cool to have in all platforms the same behaviour when it comes to telegram.me links.

This time i come to ask if you could add the same behaviour like on Android app with links like:
`telegram.me/msg/?text=some%20text`

In Android it lets you send a prefab message to some chat by clicking over it. He then asks you where to send it.

Thank you for your time :D

**Comment by auchri** [comment]
> Thank you for your time :D

Thanks for creating another duplicate #1031
