### ISSUE TITLE
Drag and drop not yet downloaded files from telegram to desktop

### ISSUE THREAD

**Issue by motammem** [telegramdesktop/tdesktop#2918]
### Steps to reproduce
1. Drag a file from telegram and drop them on desktop

### Expected behaviour
Save file to the desired location

### Actual behaviour
Nothing happen

**Comment by stek29** [comment]
Works perfectly for me on Windows 10 (only for already downloaded files ofc)

**Comment by levicki** [comment]
There is already a default folder for saving stuff which can be set to whatever you like (for example to your desktop so you can drag and drop from there to anywhere you want), and you can also right-click and then choose "Save File As" for each file.

Moreover, drag and drop wouldn't work on mobile client (you have nodrop targets) so implementing it on desktop would fragment user experience across platforms -- some people might expect it to work on the phone and tablet too and then file bug reports on it.

**Comment by stek29** [comment]
@levicki 

> Moreover, drag and drop wouldn't work on mobile client (you have nodrop targets) so implementing it on desktop would fragment user experience across platforms -- some people might expect it to work on the phone and tablet too and then file bug reports on it.

Let's remove all the features TDesktop has and some mobile clients don't: compact mode, drag'n'drop from other apps, changing save location, themes, keyboard shortcuts, selecting chats by dragging, reordering pinned chats, workmode, autoupdate system...

**Comment by levicki** [comment]
@stek29

No, let's add everything and a kitchen sink into it. You know, like FTP server, web server, SFTP client, SSH client, music/photo/video editing, Solitaire, Chess, Tetris, automatic archive unpacker... While we are at it, maybe we should also integrate Visual Studio 2017 into Telegram Desktop so you can directly compile code snippets sent via Telegram messages?

If someone wants to download so many files to so many different locations that they need this feature, then they should probably be using a download manager, not Telegram.

IMO, being able to configure a separate download folder for each user/group (with the default initially being <default downloads folder>\<user/group name>) would be much more useful feature to have.

**Comment by stek29** [comment]
@levicki This suggestion perfectly fits with feature philosophy. 
Also, why already downloaded file can be dragged, and not downloaded file can not? That's a bit inconsistent.

**Comment by motammem** [comment]
so anyone gonna implement this feature?

**Comment by LostKoder** [comment]
This feature really is needed
