### ISSUE TITLE
[GUI Crash] Main windows disapears

### ISSUE THREAD

**Issue by Grokzen** [telegramdesktop/tdesktop#292]
On Ubuntu 14.04 the GUI crashes from time to time and starts to output

```
QBackingStore::flush() called for  QWidgetWindow(0x290eb90, name = "MainWindowWindow")  which does not have a handle.
```

in the terminal that was running `Telegram`. 

The application is still running and i get toast notifications from messages but no GUI is present.

I am running the latest version 0.6.15

It either happens when my network go up/down or when i put the machine in suspended mode.

**Comment by auchri** [comment]
Maybe the same as #796
