### ISSUE TITLE
Telegram freezes upon Windows notification

### ISSUE THREAD

**Issue by BarneyFifeFan** [telegramdesktop/tdesktop#2922]
### Steps to reproduce
1. Enable Windows notifications in settings
2. When notification arrives, open Telegram window, select the chat the message came in (if necessary), and place mouse over it while the notification is still showing.

### Expected behaviour
Telegram continues to function.

### Actual behaviour
Telegram freezes, and must be manually killed (via Task Manager) and reopened.

### Configuration
**Operating system:** Windows 10, build 1607

**Version of Telegram Desktop:** 1.0.2 alpha

**Comment by john-preston** [comment]
@BarneyFifeFan I can't reproduce that and I don't know how to fix that :( This was the reason the windows notifications were disabled by default.

**Comment by BarneyFifeFan** [comment]
@john-preston I attempted to get a log of the event, but the event goes unrecorded because the client is crashing. IMO, this is a serious bug (because Windows native notifications are a pretty big deal).

**Comment by john-preston** [comment]
@BarneyFifeFan This had a discussion here: #2296

**Comment by nachoparker** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  pkbrister@zoho.com
    Domain ownyourbits.com has exceeded the max emails per hour (3/3 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o9.sgmail.github.com ([167.89.101.2]:45497)
	by skywalker.onesite.co with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7866-nacho=ownyourbits.com@sgmail.github.com>)
	id 1cWHBJ-003orX-Mg
	for nacho@ownyourbits.com; Wed, 25 Jan 2017 01:35:45 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=wLodSqPehCju5ujdtuMugna/+Eo=; b=cgQPNP4kF6EsY+8M
	OuToTrxJ7obKL6Vkg8Lrm6CM6UdFTTZ5Ipfq/T2kyZh2drZEdEgFRd57WGaZkZqZ
	xxEevk6WNLoCzOa96RaB9QWg7S32Sg3ZaOWO0rptic68JXyFMXEpRKY08cv3uXAl
	e55d3wgYk+4+EhCOKP7mQgpex7Q=
Received: by filter0982p1mdw1.sendgrid.net with SMTP id filter0982p1mdw1-30206-58884718-1B
        2017-01-25 06:35:04.3525676 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id WrYce-U8SfK-j13Rm7w8IA
	for <nacho@ownyourbits.com>; Wed, 25 Jan 2017 06:35:04.280 +0000 (UTC)
Date: Tue, 24 Jan 2017 22:35:04 -0800

**Comment by BarneyFifeFan** [comment]
@john-preston didn't see that issue when I searched the issues; sorry.

**Comment by john-preston** [comment]
@BarneyFifeFan Actually, someone suggested a (very heavy) workaround for that bug on msdn forum, perhaps I'll try to implement that some day.. But that's very unwanted (they suggest to spawn a thread for every notification).

**Comment by win9z** [comment]
After telegram update i have same issue

Windows 10, build 1607
Telegram Desktop: 1.9.14
