### ISSUE TITLE
1.0.2a installer?

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#2923]
For some reason, at work, I can't update Telergam automatically, the request either fails, or says that I'm already on the latest version. It's not a bug from Telegram, we have a tight firewalled network :(

So when I'm aware of an update (thanks to the version at home), I manually download the installer to update the work version. But at this time, no installer for 1.0.2a is available.

**Comment by john-preston** [comment]
@Geobert 1.0.2 is a stable version, you can download and install it over your alpha.

**Comment by Geobert** [comment]
oh! didn't know that, thanks!
