### ISSUE TITLE
Telegram Desktop automatically opens downloaded content (may be a vulnerability).

### ISSUE THREAD

**Issue by plablo** [telegramdesktop/tdesktop#2924]
### Steps to reproduce
1. Go to a chat with sharing content (pdf, zip, exe, etc.)
2. Download that content.
3. Wait unitl done and watch how automatically opens.

### Expected behaviour
Just download.

### Actual behaviour
Download and executes (open file with os filetype association).

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.0.2 Portable
### Logs
No Logs.

**Comment by MasterGroosha** [comment]
You are not the first person who complains about it, but the funniest thing is that I can't reproduce it with neither of my 3 copies of TDesktop (1 installed, 2 portable).

Tried with both `exe` and `pdf`

**Comment by plablo** [comment]
Hi  @MasterGroosha, thanks for your reply. I'm glad to know that I'm not the only one. I will try it with more copies of TDesktop over others Windows 10 installs, so that I can give a bit of light to this issue.

**Comment by iklimchuk** [comment]
can't reproduce it as well. i have to click on the file in order to open it after download.

**Comment by mohsenfaraj** [comment]
Hello i Have this problem too. after an update u didn't deal with this Issue but now again i see i still have this problem. it can be Dangerous if you download a virus by fault! I am using win7 TD1.1.19

**Comment by Aokromes** [comment]
cannot reproduce here too.

**Comment by angadarora** [comment]
I think to reproduce this error you should try this with windows 7 , since its happening with my windows 7 installation but not with windows 10

**Comment by Socialdarwinist** [comment]
![telegram download open versus download distinction 2018-05-25](https://user-images.githubusercontent.com/20446122/40535366-35943e86-6009-11e8-951b-52dbd7c9b769.png)

Guys, it depends on where you click whether the file gets downloaded only or downloaded and opened.
If you click the arrow down, it downloads. If you click the rest of the file message, you download and open.
If your system never downloads + opens, your desktop environment is probably insufficiently configured.

**Comment by plablo** [comment]
Thank you @Socialdarwinist, that's right, at least for me.

**Comment by Transisto** [comment]
A file named **This_is_a_document_you_should_read.pdf** ...............scr was executed with a single click without any notification.
(SCR extension behave the same as EXE in Windows)

I've spent the last week rebuilding my OS from scratch...

I don't see how every popular software on this planet warn before running executable but Telegram doesn't.

**Comment by john-preston** [comment]
@Transisto The OS warns, at least with .exe

In that case I guess an additional in-app warning has to be added ;(
