### ISSUE TITLE
msgIn(Out)Shadow layers issue

### ISSUE THREAD

**Issue by jesterro** [telegramdesktop/tdesktop#2929]
Shadow layer of a messages have some corners that can be visible if any transparency applied to messages background.

Here's an example with 
```
msgInBg: #2E2E2E1A
msgInShadow: #10101080
```
to make it more obvious

![2017-01-27 14 34 48](https://cloud.githubusercontent.com/assets/25265070/22369682/858569d4-e49e-11e6-8090-0267b763abda.png)

Affected layers in colors.tdesktop-theme file:
```
msgInShadow:                        
msgInShadowSelected:                
msgOutShadow:                    
msgOutShadowSelected: 
```

**Comment by john-preston** [comment]
@jesterro Yes, message background colors are not supposed to have any transparency. It is not (and I'm afraid will not be) supported.
