### ISSUE TITLE
Mess in display of messages since 1.0.2

### ISSUE THREAD

**Issue by deansg** [telegramdesktop/tdesktop#2931]
### Steps to reproduce
1. Enter any conversation 

### Expected behaviour
My messages should appear on one side while the other party's messages' should appear on another.

### Actual behaviour
Both my and the other party's messages all appear on the left hand side of the screen, making it very uncomfortable to chat.
I can send an actual screenshot if needed.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.0.2 (before that it worked fine, even in 1.0.0)

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by auchri** [comment]
There's a setting for this
