### ISSUE TITLE
Cannot switch to telegram window with Alt+Tab on Windows

### ISSUE THREAD

**Issue by mmatrosov** [telegramdesktop/tdesktop#2932]
### Steps to reproduce
1. Run telegram App
2. Go to Settings -> General, uncheck "Show taskbar icon"
3. Press Alt+Tab

### Expected behaviour
Telegram window appears on the panel of currently opened windows

### Actual behaviour
Telegram window does not appear on the panel of currently opened windows, and thus is not reachable with Alt+tab

### Configuration
**Operating system:** Windows 7 x64

**Version of Telegram Desktop:** 1.0.2

**Comment by john-preston** [comment]
@mmatrosov Is it working in some other app? (the absence of a taskbar icon together with the availability of the window through alt tab) Perhaps the taskbar icon is the same as the availability through alt tab? :(

**Comment by auchri** [comment]
> Perhaps the taskbar icon is the same as the availability through alt tab

Yes. If there is no taskbar icon, you can not switch to it with <kbd>alt</kbd> + <kbd>tab</kbd>

**Comment by mmatrosov** [comment]
I can see Telegram app in Applications tab in Windows Task Manager. That's why I expected it to be available through alt+tab.
In case this is not possible to implement, another feature would be very useful: _minimize_ to system tray. this means, icon on the task bar is displayed only when the app is not minimized. I saw this behavior in many apps and it works great.

**Comment by auchri** [comment]
![image](https://cloud.githubusercontent.com/assets/5092164/22396634/6de79a20-e55e-11e6-8d48-196fc9841541.png) 😂

**Comment by john-preston** [comment]
@auchri Just enable both tray and taskbar icons and close window by X button.

**Comment by mmatrosov** [comment]
@john-preston, thank you!
