### ISSUE TITLE
playing audio with gaps

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#2935]
### Steps to reproduce
1.  record audio or send audio file
2.  play recorded audio or file

### Expected behaviour
playing audio without gaps

### Actual behaviour
playing audio with gaps

### Configuration
**Operating system:**
windows 10 x64
**Version of Telegram Desktop:**
1.0.3 alpha
### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.
--------------
[audio_2017-01-28_15-37-06.zip](https://github.com/telegramdesktop/tdesktop/files/736881/audio_2017-01-28_15-37-06.zip)

**Comment by stek29** [comment]
Please use template.

**Comment by auchri** [comment]
@f242 Does this also occur in 1.0.2 ?

**Comment by f242** [comment]
@auchri no, with 1.0.2 all fine
