### ISSUE TITLE
Systray icon unread message count over 99

### ISSUE THREAD

**Issue by Subway909** [telegramdesktop/tdesktop#2937]
You can see better on this pic: http://i.imgur.com/LCpdSzL.png
Taskbar icon vs systray icon.

 
### Steps to reproduce
Have more than 99 unread messages.

### Expected behaviour
3 digits count on the notification icon.

### Actual behaviour
Only 2 digits showing (kinda wrong).

### Configuration
**Operating system:**
Windows 10 64 build 1607

**Version of Telegram Desktop:**
1.0.2

### Logs
Insert logs here (if necessary)

**Comment by auchri** [comment]
You see nothing of the blue icon if 3 digits would be displayed

**Comment by stek29** [comment]
@auchri IMO 3 chars will be fine
It'll also be a good idea to use "123K" for 123000 like formatting

**Comment by john-preston** [comment]
@stek29 You don't get any information from "123K" except "there are alot of unread messages", while from "..12" you get information "there are alot of unread messages" + you can notice each time this count is changed.

**Comment by Subway909** [comment]
At the time i had not realized it was showing "..2". I though the number was being clipped.

**Comment by auchri** [comment]
@Subway909 So this issue can be closed?

**Comment by Subway909** [comment]
I think so.

Thanks.

**Comment by stek29** [comment]
@john-preston hm, indeed.
