### ISSUE TITLE
Telegram doesnt save my login details

### ISSUE THREAD

**Issue by sirx** [telegramdesktop/tdesktop#2938]
Everytime I reboot my computer telegram-desktop wants me to put in my number again and this is just annoying on my laptop it works perfectly fine, bot machines run arch linux.

Anyone experiencing similar issues?

**Comment by auchri** [comment]
Use the template.

**Comment by john-preston** [comment]
@sirx Are you using binary from https://desktop.telegram.org? Where is it placed?

**Comment by sirx** [comment]
I placed the binary in my .bin dir where I put all my binarys from external sources where can I find some more log information to paste?

When I run telegram from the terminal it doesn't give me much output except for some gtk errors

**Comment by sirx** [comment]
`Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number

(Telegram:26676): libnotify-WARNING **: Failed to connect to proxy

(Telegram:26676): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
`

**Comment by Aokromes** [comment]
#960
