### ISSUE TITLE
multiple instances of Telegram

### ISSUE THREAD

**Issue by Sebastian43** [telegramdesktop/tdesktop#2939]
It would be some much more convenient to be able to keep a separate chat window open for each partner one is conversing with.  
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Win10 Pro v1511

**Version of Telegram Desktop:**
v1.02
### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by Sebastian43** [comment]
Why does this email say my thread is closed ?
Joe

**Comment by stek29** [comment]
@Sebastian43 Because it was closed.

**Comment by Sebastian43** [comment]
Dear Victor
This is the first of many times that I have tried
that I got a response from telegram.

That is was closed was obvious
from the thread on the website.
I want to know WHY it was closed.
Have I done something wrong ?

I would so much like Telegram to consider some enhancements
but have had no response to my attempts
until this non-explanation of ‘closed’.

Joe

**Comment by auchri** [comment]
@Sebastian43 As you can see, I've closed it because it's a duplicate.

![image](https://cloud.githubusercontent.com/assets/5092164/22415578/e0664e1e-e6c8-11e6-87e1-866252da64a8.png)
