### ISSUE TITLE
Can't edit picture captions with the arrow up key

### ISSUE THREAD

**Issue by timoschwarzer** [telegramdesktop/tdesktop#2940]
### Steps to reproduce
1. Send a picture with a caption
2. Press the arrow up key

### Expected behaviour
It should edit the picture's caption

### Actual behaviour
It edits the latest text-only message

### Configuration
Ubuntu GNOME 16.10 / Linux 4.8.0-34-generic

**Version of Telegram Desktop:**
1.0.3-alpha

**Comment by john-preston** [comment]
@timoschwarzer Well, this works as intended :( Perhaps this should be done as you suggest, but currently it is supposed to work that way (there is some logic in it — editing in this input field something you wrote in it just before).

**Comment by timoschwarzer** [comment]
Okay. I was expecting the up key to edit the last message, including media captions.
