### ISSUE TITLE
[Feature] Use system's language/localization as default language/localization

### ISSUE THREAD

**Issue by mahula** [telegramdesktop/tdesktop#2941]
### Expected behaviour
Use system's language/localization as default language/localization.
Only if system's language/localization is not covered by Telegram, fall back to English as default.

### Actual behaviour
English is the default language/localization.

### Configuration
**Operating system:** All

**Version of Telegram Desktop:** 1.0.2

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?
