### ISSUE TITLE
Twitter image set and video support

### ISSUE THREAD

**Issue by shakesoda** [telegramdesktop/tdesktop#2942]
I regularly link things from twitter, and currently the integration is lacking in feedback for image sets and videos.

### Expected behaviour
Image sets should indicate that they are a set and preferably allow the user to look at all the images without needing to go to twitter. the first image in a set should be displayed.

Videos should indicate that they are videos in some way (or allow playback if possible)

### Actual behaviour
Image sets appear as normal images, and always show the last image in the set instead of the first.
Videos also appear as normal images, with no indication otherwise.

examples:
image set: https://twitter.com/binobinobi/status/825710357129728000
video: https://twitter.com/lebenseuche/status/824665931301482496

### Configuration
**Operating system:**
Windows 10 x64

**Version of Telegram Desktop:**
1.0.2

**Comment by stek29** [comment]
The only way to have multiple images in one message is instant view, which isn't avaliable for twitter and isn't supported in TDesktop.

**Comment by shakesoda** [comment]
is there no way to give *some* ui feedback that sets and videos aren't just single images?

**Comment by stek29** [comment]
@shakesoda sure there is. <kbd>Ask a question</kbd> button in settings, or on [Twitter](https://twitter.com/telegram) (what an irony)
