### ISSUE TITLE
HTTP API connection use IP address as Hostname

### ISSUE THREAD

**Issue by studro** [telegramdesktop/tdesktop#2943]
A number of corporate HTTP proxies do not allow HTTP connections directly to IP addresses (ie. where the Hostname is an IP address rather than a domain). This is done under the assumption that malware may behave in the same way - malware developers often setup an IP endpoint to avoid the traceability associated with registering a domain.

At present, the Telegram Desktop client attempts to make such a connection, as shown in the following log entries:

`[2017.01.30 11:11:31] HTTP Error: content error 202 - Error transferring http://149.154.167.51:80/api - server replied: Forbidden`

I believe that the Telegram Desktop client would be more likely to get through corporate HTTP proxies if it used a domain in the Hostname instead of an IP address:

i.e. `http://example.telegram.org/api` instead of `http://149.154.167.51:80/api`

**Comment by stek29** [comment]
API issue, sorry.
And also a duplicate I think.

**Comment by john-preston** [comment]
@stek29 I'm afraid currently you only can setup some custom HTTP proxy and work that way.
