### ISSUE TITLE
large right margin in telegram posts

### ISSUE THREAD

**Issue by mahmoodn** [telegramdesktop/tdesktop#2945]
There is an issue with my telegram 3.16.1 on Galaxy A5. As you can see in the [picture](https://www.photobox.co.uk/my/photo?album_id=4699584125&photo_id=9616217743), the right margin is large in some posts. Since the width of the screen is small (compare to the height of the screen), I think this issue has to be fixed. Also, some posts are narrower than others as you can see in the [picture](https://www.photobox.co.uk/my/photo?album_id=4699584125&photo_id=9616217743).

Alternative link if the picture link is expired http://uploads.im/vFEV9.jpg

**Comment by auchri** [comment]
This repo is for Telegram Desktop only.

**Comment by mahmoodn** [comment]
So where should I report that?

**Comment by john-preston** [comment]
@mahmoodn I think if some post contains a photo this photos then is used to count the width of the message. So it is displayed as expected.

**Comment by mahmoodn** [comment]
If I rotate the phone (landscape) then the margin will be very very large.
Don't you think it is an issue? If there is some place to report that, please let me know
