### ISSUE TITLE
[Enchancement] Change how TDesktop works with custom localizations.

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2947]
### Steps to reproduce
1. Download custom locale
2. Apply it inside TDesktop
3. Delete custom locale file
4. Restart TDesktop

### Expected behaviour
TDesktop should keep previously selected localization

### Actual behaviour
TDesktop reverts to English (at least, for me)

### Possible solution
Since files (especially in "Download" folder) can be easily deleted either intentionally or by accident, I suggest copying applied custom locale (maybe with `custom_lang.strings` name) into TDesktop folder (where executable binary is located). This way even if user wipes any other folder on his PC, TDesktop won't lose custom localization and revert to default.

### Configuration
**Operating system:** Windows 10 (Should be the same on Linux?)
**Version of Telegram Desktop:** 1.0.4 alpha

**Comment by john-preston** [comment]
@MasterGroosha This makes sense. It works in similar way with color themes.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after more than 2 years. closing.
