### ISSUE TITLE
Falling back to HTTP while using HTTP proxy

### ISSUE THREAD

**Issue by mosajjal** [telegramdesktop/tdesktop#2950]
Hi. HTTP proxies can handle HTTPS requests made as well (as far as I know) so why does Telegram falls back to insecure connection while using HTTP proxy? Setting HTTP proxy inside browsers will allow them to send SSL traffic through it as well (tested with Chrome, Safari, Firefox, IE, Edge).

Can you please explain the reason behind it? Thank you

### Steps to reproduce
1. Set proxy for Telegram Desktop
2. Sniff packets with wireshark
3. See unencrypted messages

### Configuration
Linux

All versions

**Comment by john-preston** [comment]
@mosajjal You can't see unencrypted messages there. You can see HTTP requests with MTProto data being transferred in exactly the same way it is transferred when you use TCP transport or HTTP transport without proxy at all, safely encrypted by MTProto specifications.

**Comment by mosajjal** [comment]
Thanks for the quick response. I've sniffed Telegram traffic and noticed SSL communication when using no proxy. It's not the same

**Comment by john-preston** [comment]
@mosajjal There is no ssl communication in Telegram at all, except webogram (web.telegram.org). It is encrypted in a custom way both with http proxy and without it. Perhaps Wireshark shows it differently.

**Comment by mosajjal** [comment]
maybe. Thanks a lot for the info. I'm gonna go ahead and close this.
