### ISSUE TITLE
Crashing on v1.0.5

### ISSUE THREAD

**Issue by thePier** [telegramdesktop/tdesktop#2951]
### Steps to reproduce (happens randomly)
1.  Open Telegram Desktop
2.  Make another window go fullscreen/above TG's one or minimize TG Dektop
3.  Select Telegram Desktop from taskbar

### Expected behaviour
Telegram Desktop should return in foreground working

### Actual behaviour
Telegram Desktop crashes with Windows error window "Telegram Desktop is not responding"
Afterwards, if I click the TG icon in the taskbar a Windows window opens says that "Telegram.exe" is missing and asks to remove the shortcut, even if the .exe file is still in the 

### Configuration
**Operating system:**
Windows 10 64-bit

**Version of Telegram Desktop:**
1.0.5

### Logs
No useful logs was saved in log.txt regarding the crash

**Comment by portenko** [comment]
I have the same problem. 

But, when I getting some messages with pictures or audios after that telegram begin to hang. I looked this problem several times.

![1111](https://cloud.githubusercontent.com/assets/11551744/22504097/8bbafb10-e896-11e6-97dc-0d1eb207583b.png)

**Comment by Lazek** [comment]
Please recheck in 1.0.6
