### ISSUE TITLE
Error CMakeFiles debug version  

### ISSUE THREAD

**Issue by andreaangiolillo** [telegramdesktop/tdesktop#2952]
Hi everyone!!
I tried to build the Debug version of Telegram (with "**make**" command in **/home/user/TBuild/tdesktop/Telegram**) but I had this error:

### Actual behaviour
[ 34%] profile.style..
[ 34%] window.style..
[ 34%] settings.style..
[ 34%] intro.style..
[ 34%] media_player.style..
[ 34%] Linking CXX executable Telegram
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libXi.a(XExtInt.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libXi.a(XExtToWire.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libXext.a(extutil.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libXext.a(Xge.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libSM.a(sm_client.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libSM.a(sm_error.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libSM.a(sm_process.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(connect.o): relocation R_X86_64_32S against undefined symbol `_IceConnectionStrings' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(error.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(getauth.o): relocation R_X86_64_32 against undefined symbol `_IcePaAuthDataEntries' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(iceauth.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(icetrans.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(misc.o): relocation R_X86_64_32S against symbol `_IceVersions' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(process.o): relocation R_X86_64_32 against symbol `_IceAuthNames' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(protosetup.o): relocation R_X86_64_32S against undefined symbol `_IceProtocols' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(register.o): relocation R_X86_64_32 against undefined symbol `_IceProtocols' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(setauth.o): relocation R_X86_64_32 against undefined symbol `_IcePaAuthDataEntries' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(shutdown.o): relocation R_X86_64_32 against undefined symbol `_IceConnectionObjs' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(watch.o): relocation R_X86_64_32S against undefined symbol `_IceConnectionObjs' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libICE.a(authutil.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libxcb-shm.a(shm.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libxcb-xfixes.a(xfixes.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libxcb-render.a(render.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libXi.a(XIAllowEvents.o): relocation R_X86_64_PC32 against symbol `_XGetRequest' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/Telegram.dir/build.make:14967: recipe for target 'Telegram' failed
make[2]: *** [Telegram] Error 1
CMakeFiles/Makefile2:278: recipe for target 'CMakeFiles/Telegram.dir/all' failed
make[1]: *** [CMakeFiles/Telegram.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

### Configuration
Linux 16.10

**Comment by auchri** [comment]
Here are instructions for building on Ubuntu 14+: https://github.com/telegramdesktop/tdesktop/pull/2926/files#diff-d5d754632898fce5ce975e5cd19dde93

**Comment by omkarnathsingh** [comment]
@auchri It doesn't solves the issue. I am getting same error on Ubuntu 18.04 LTS.

**Comment by psychosys** [comment]
Edit **links.txt** and add  **-no-pie** to your c++ command
