### ISSUE TITLE
Changelog on homepage is very old

### ISSUE THREAD

**Issue by beerisgood** [telegramdesktop/tdesktop#2953]
On https://desktop.telegram.org/changelog the last changelog is for v1.0 from 11.01.17.
Today its 01.02.17 and the changelog now misses **6 releases**

So update it or link directly to the commit site (not user friendly)
Also see #2615 & #2433 Same problem.

**Comment by auchri** [comment]
Here is the (almost) complete changelog: https://github.com/telegramdesktop/tdesktop/releases

> The minor updates (with not a great changelog or smth) are not shown in the version history.

**Comment by beerisgood** [comment]
But if you click on changelog in Telegram (Windows) client then you get https://desktop.telegram.org/changelog as info.
So then change it to https://github.com/telegramdesktop/tdesktop/releases
