### ISSUE TITLE
Show @username together with the contact/group/channel name, it may help for searching

### ISSUE THREAD

**Issue by oxydron** [telegramdesktop/tdesktop#2954]
### Steps to reproduce
1. Look at any contact on your list
2. Note that their @usernames dont show.

### Expected behaviour
1. @username near the name. This would facilitate on searchs, if you know the username instead the name.

### Actual behaviour
Only appears the name.

### Configuration
Windows 10

**Version of Telegram Desktop:**
1.0.5 alpha

**Comment by auchri** [comment]
The username is displayed in the profile of the user.
Also, there's not really enough space to display the username
