### ISSUE TITLE
[enhancement]non-English message searching is limited

### ISSUE THREAD

**Issue by wck963** [telegramdesktop/tdesktop#2960]
**Issue background**

Chinese, Japanese and more non-latin languages usually do not use space as separator of words but have continuous characters in a single sentence. Therefore while Telegram currently have search function which use English words as minimal searching unit, we Chinese would need to type in the whole sentence into the textbox, or the expect message would not appear.

**Solutions**

1. Simply search the whole field without filter out strings without spaces or comma, dot, etc.

2. More practically,  whitelist a sector of unicode chars.

In my personal opinion the first option would not be that bad, but to keep current English feature the second could be better.

Up to you developers, and thank you for creating so awesome the Telegram platform.

**Comment by john-preston** [comment]
@wck963 Unfortunately this is not related to Telegram Desktop, it is a server side messages search. I'll ask about that.
