### ISSUE TITLE
Deleted previous messages while we are typing.

### ISSUE THREAD

**Issue by questionpython** [telegramdesktop/tdesktop#2963]
Deleted previous messages while we are typing.

### Steps to reproduce
1. go to a private chat with a user
2. try to type text
3. In the box type a message. When I am typing. Just accidental. Previous sometimes typed messages Is cleared.

### Configuration
**Operating system:** GNU/LINUX , Ubuntu 16.10
also some my friend have this problem.

**Version of Telegram Desktop:** 1.0.5 ( is lastest version)

**Comment by stek29** [comment]
It should be caused by drafts sync. Is your connection stable?
#2315 #2371

**Comment by 0xCA** [comment]
Something similar happening on windows. Sometimes while I writing a message, several last words disappearing (and draft mark appears in chat list). Wired connection 100/100Mb, 100km 2ms ping.
1.0.5 too

**Comment by questionpython** [comment]
also this bug now available in 1.0.29 (gnu).
why not fix this?

**Comment by gowhari** [comment]
Same for me. Version 1.1.7 on Ubuntu 16.04.2 / Linux 4.4.0

If found when it happens this message will print on stdout:

`QTextCursor::setPosition: Position '8388607' out of range`

**Comment by stek29** [comment]
@gowhari It prints out in other cases too, btw.

**Comment by igorline** [comment]
I'm having lots of chats and the issue is still happening for me. Quite annoying..
