### ISSUE TITLE
archlinux-xfce下telegram-desktop1.0.5无法输入中文

### ISSUE THREAD

**Issue by omaidb** [telegramdesktop/tdesktop#2964]
非常抱歉，不会英语，请哪位看见的大大翻译一下。
桌面环境xfce，输入法fcitx-sougou
telegram-desktop1.0.5
之前在Ubuntu版本下正常，这两天刚上手archlinux，发现其他im下输入法正常，但是telegram-desktop下无法输入中文，日文，韩文，等文字。
 
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by stek29** [comment]
Try to launch telegam like this: `QT_IM_MODULE="fcitx" /opt/Telegram/Telegram`
#1035 duplicate btw
