### ISSUE TITLE
Image viewer doesn't exit

### ISSUE THREAD

**Issue by picsi** [telegramdesktop/tdesktop#2967]
### Steps to reproduce
1. Open an image on Telegram (not a link but an actual image sent yo you)
2. Press ESC

### Expected behaviour
Esc should exit the image viewer. Rather, it closes the opened conversation in the background

### Actual behaviour
Watch as you can't exit the picture viewer by pressing buttons or clicks, only by doing Alt+F4

### Configuration
**Operating system:** Parabola GNU/Linux-libre (Arch variant). Kernel 4.9.6-gnu-1. 

**Version of Telegram Desktop:** 1.0.5

AFAIK this bug was not present in earlier versions, so it might be a regression.

**Comment by Aokromes** [comment]
On 1.0.7 and windows 10 works.

**Comment by auchri** [comment]
#2670
