### ISSUE TITLE
Ubuntu 16.10 Image Preview

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#2968]
Dear all, 

Other apps that use the GTK File Chooser Dialog enable image preview. 

See for example Chrome. Can Telegram Desktop support image preview, too?

Yours,

Robert

![peek 2017-02-04 11-42-telegram-image-preview](https://cloud.githubusercontent.com/assets/170947/22618277/b5d4c220-ead8-11e6-80b6-b7f4d7fcf1d8.gif)

**Comment by john-preston** [comment]
@orschiro And how do I do that?

**Comment by orschiro** [comment]
@john-preston good question. I don't know how to implement this. 

Maybe someone else has some more details!

**Comment by timoschwarzer** [comment]
I don't know how Telegram does build the file dialog internally and I don't know if this might help here, but here is how Chromium did it:

https://bugs.chromium.org/p/chromium/issues/detail?id=15500
https://codereview.chromium.org/151100/patch/3/1005

**Comment by john-preston** [comment]
@timoschwarzer That looks promising, thanks.

**Comment by tapionx** [comment]
I confirm the issue, please fix 🙏🙏
I can help with testing

**Comment by john-preston** [comment]
@tapionx It should be working in the latest versions already.
