### ISSUE TITLE
Fully commented tdesktop-theme file = invalid theme data

### ISSUE THREAD

**Issue by michaelkisiel** [telegramdesktop/tdesktop#2969]
Hey,

when transforming the fully commented [colors.palette](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/Resources/colors.palette) file into a colors.tdesktop-theme file and binding it into your tdesktop-theme/zip thingy the theme is shown as invalid data thus not appliable. I do not see the problem why it should not work.

**Comment by john-preston** [comment]
@michaelkisiel Because colors.palette is not a valid theme file and it is not meant to be, it is a file that is used to generate code for themes reading etc., the syntax there includes some things that are not allowed in themes (like specifying fallback colors).

**Comment by michaelkisiel** [comment]
THX for quick reply. I was aware of it, but when cleaning file of all fallback colors i See no difference to the default.tdesktop-theme file despite the comments, or what am I missing?

**Comment by john-preston** [comment]
@michaelkisiel Yes, fallbacks colors currently should be the only non similar thing. There should be errors in log.txt when you try to read and apply some theme that has invalid data.

**Comment by michaelkisiel** [comment]
@john-preston DAAAAMN! So two things. First, thx for the log.txt ref here. Helped me a lot. Second, i could fix my problem, but i won't tell you with what i was struggling there....just...to....embarrassing! :no_mouth: 

Anyway many thanks for the great desktop app, keep the releases rollin'!

_"Don't you see it Preston, it's gone!"_
