### ISSUE TITLE
Independent executable path to the data file path

### ISSUE THREAD

**Issue by 2wayne** [telegramdesktop/tdesktop#297]
I've packaged TDesktop as a PortableApp and noticed on the first run that the created files e.g. log.txt, data_config and the tdata dir aren't in the Telegram.exe directory `<TelegramDestkopPortable/App/Telegram>`. The files are located in the launcher folder`<TelegramDesktopPortable>`. So could you change that the files are going to be created where the Telegram.exe is stored and not where it is executed.

**Comment by 2wayne** [comment]
Fix this please otherwise it won't working as a PortableApp. Because there actually should be a 'data' file created but can't because there is already a 'Data' folder. Could you make a settings.ini saving all the settings? Because I'd like to set some default values e.g. deactivate automatic updates and set default download location.

**Comment by telegramdesktop** [comment]
.bat file is not a good idea, I'm afraid it changes the working directory to where it is placed. If you use a .lnk shortcut it has a working directory string, by default it is where the .exe is located. So I suggest you launch it by a .lnk shortcut.

To use it as a portable app you should save Telegram.exe in some empty folder, for example Telegram. Then when you launch it, "data" and "data_config" files and "tdata" folder are created in that folder, near Telegram.exe, which store your configuration, including download path and updates disabled.

About Linux version: there were some bugs related to launch-by-symlink, can you please install the last version from scratch and tell me, if autoupdates still behave so, creating files outside two places: the folder, where your binaries "Telegram" and "Updater" are located and "~/.Telegram Desktop"?

**Comment by stychos** [comment]
After your message, I am deleted Telegram, ~/.TelegramDesktop and downloaded fresh 0.7.6 version.
Next, I created empty ~/.TelegramDesktop, and place Telegram and Updater applications there.
Also, I've maked desktop shortcut in /usr/share/applications, and ln -s ~/.TelegramDesktop/Telegram /usr/bin/telegram
Shortcut text is:
```
[Desktop Entry]
Name=Telegram
Comment=Telegram Messenger
Exec=telegram %U
Icon=telegram.png
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Network;Application;
```
Right now it was updated to 0.7.7, and there new files in home again:
![Files, created by the Updater]
(http://dl2.joxi.net/drive/0004/1601/263745/150116/6d570515be.jpg)

**Comment by DarkPark** [comment]
Please add the ability to set path to the data dir via the command line.
Something like this:
```sh
./Telegram --data-path "/some/path/to/telegram/desktop/dir"
```
For Linux it also would be nice to implement [XDG Base Directory Specification](https://wiki.debian.org/XDGBaseDirectorySpecification) as it's not a very good idea to just dump all configs in `/home/user/` directory.

**Comment by 2wayne** [comment]
I fixed the misplaced files issue by setting a working directory. Could you add a settings.ini saving all Telegram's settings?

**Comment by telegramdesktop** [comment]
stychos

Can you contact me at telegram.me/preston so I could ask you for help in testing of Linux autoupdate?

**Comment by Altair2015** [comment]
помогите мне скрыть мой номер от всех

2015-03-03 18:15 GMT+07:00 telegramdesktop <notifications@github.com>:

**Comment by ezdev128** [comment]
@Altair2015, I think it is not a correct issue tree to ask this :-)
Try to create a new issue and describe your problem.
P.S.: у вас в репозиториях есть репа с именем 961*****46. Скорее всего, Ваш номер и есть +7961*****46 :-)

**Comment by stychos** [comment]
@telegramdesktop with happiness if you will wait till tomorrow (I've migrated to hackintosh and haven't Linux for now, will install at night). What time is preferable for you?

**Comment by Altair2015** [comment]
мне будет удобно после 0:00 по местному, это по Москве 20:00

**Comment by DarkPark** [comment]
any thoughts regarding my proposition?
it's about standardization and common ways in Linux

**Comment by Altair2015** [comment]
./Telegram --data-Путь " / некоторые / путь / к / телеграмма / настольные / реж "
куда это надо ввести????

**Comment by Altair2015** [comment]
я согл

**Comment by DarkPark** [comment]
это пример запуска приложения из командной строки с явным указанием директории с данными

**Comment by stychos** [comment]
@Altair2015 это такой троллинг, или Вы просто не поняли суть темы и порядок обсуждения?

**Comment by goodmind** [comment]
any progress here?

**Comment by stychos** [comment]
As far as I know, right after our conversations here, telegram was updated and works fine in Linux, so you can place it whenever you want. Unfortunately, I'm no more Linux user and can not proof my words with up-to-date facts.

**Comment by aliva** [comment]
so what about that --data-path request?

**Comment by aliva** [comment]
I checked tdesktop source code, I seems [psAppDataPath](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/pspecific_linux.cpp#L1079) should be changed, it should return custom data path instead of hard coded home
for windows build they used environment variable `APPDATA`

**Comment by aliva** [comment]
so, [here](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/main.cpp#L37) in main method they parse arguments which also accepts [`-workdir`](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/settings.cpp#L201) as an arguments to set your data path,
and then in the very [next](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/main.cpp#L45) line they call `logsinit`, which force resets your [settings](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/logs.cpp#L192)

good job @telegramdesktop, good job!

**Comment by auchri** [comment]
should be fixed with the PR from @aliva, will be in the next release.

Thank you!
