### ISSUE TITLE
LINK : fatal error LNK1104:  cannot open file “lib/common.lib”

### ISSUE THREAD

**Issue by zhaohansprt** [telegramdesktop/tdesktop#2970]
hi when i try to build telegram in vs2015  this error happened

1>  [826/826] LINK_EMBED Telegram.exe
1>  FAILED: Telegram.exe Telegram.exe.pdb
1>  C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True Telegram.exe "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:Telegram.exe @Telegram.exe.rsp" 1 mt.exe rc.exe "obj\Telegram.Telegram.exe.intermediate.manifest" obj\Telegram.Telegram.exe.generated.manifest
1>LINK : fatal error LNK1104:  cannot open file “lib/common.lib”
1>
1>  Traceback (most recent call last):
1>
1>    File "gyp-win-tool", line 323, in <module>
1>
1>      sys.exit(main(sys.argv[1:]))
1>
1>    File "gyp-win-tool", line 29, in main
1>
1>      exit_code = executor.Dispatch(args)
1>
1>    File "gyp-win-tool", line 71, in Dispatch
1>
1>      return getattr(self, method)(*args[1:])
1>
1>    File "gyp-win-tool", line 179, in ExecLinkWithManifests
1>
1>      subprocess.check_call(ldcmd + add_to_ld)
1>
1>    File "C:\Python27\lib\subprocess.py", line 541, in check_call
1>
1>      raise CalledProcessError(retcode, cmd)
1>
1>  subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:Telegram.exe @Telegram.exe.rsp Telegram.exe.manifest.res' returned non-zero exit status 1104
1>
1>  ninja: build stopped: cannot make progress due to previous errors.
..........

**Comment by zhaohansprt** [comment]
I follow   "Build instructions for Visual Studio 2015"  except that  i  failed on  the Google Breakpad stage and i have  try to  disabled  Google Breakpad   follow  "How to disable Google Breakpad #2674"

**Comment by john-preston** [comment]
@zhaohansprt Disabling breakpad requirements in Windows build isn't currently supported, GYP always include its dependencies in the build :(

**Comment by zhaohansprt** [comment]
solved

**Comment by auchri** [comment]
@zhaohansprt How?

**Comment by zhaohansprt** [comment]
#2675
