### ISSUE TITLE
"Insert Unicode control charcter" submenu is empty

### ISSUE THREAD

**Issue by srazi** [telegramdesktop/tdesktop#2971]
Windows 10 - 64 Bit
Telegram Desktop version 1.0
![bug](https://cloud.githubusercontent.com/assets/1328454/22626009/5378c50a-ebb8-11e6-9397-8349de8068d4.png)

**Comment by john-preston** [comment]
Thank you for your report, I'll try to reproduce that. What OS input language do you use?

**Comment by srazi** [comment]
I'm using two input languages:
1- English (US Keyboard) as default
2- Persian (Standard keyboard)
