### ISSUE TITLE
Option to suppress "X joined the group" messages for each group

### ISSUE THREAD

**Issue by jph108** [telegramdesktop/tdesktop#2972]
### Steps to reproduce
1. Join a group
2. Receive many "XYZ joined the group" notices

### Expected behaviour
It would be nice if, on a group by group basis, there was a way to suppress notices that someone joined the group. I joined a group where a bot posts rarely, but I get notifications every time someone joins, and I don't need to get an alert for that. I want to get an alert every time someone posts something, but not when someone joins. I'd like to be able to set this on a group-by-group basis. 

### Actual behaviour
Every time someone joins the group, a notice gets triggered, even though this isn't something I would like to get a notification for. 

### Configuration
**Operating system:** Mac OS

**Version of Telegram Desktop:** 1.02

**Comment by auchri** [comment]
No api

**Comment by jph108** [comment]
Is there a place to leave feature suggestions. This would be a nice feature to add.

**Comment by SmartManoj** [comment]
@auchri Open and add enhancement label like #3758

**Comment by Aokromes** [comment]
api means telegram servers must support it.
