### ISSUE TITLE
[Themes] attentionButtonFgOver doesn't work in profiles

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2973]
### Steps to reproduce
1. Open person's profile
2. Place mouse cursor over "Block user" button

### Expected behaviour
`attentionButtonFgOver` color should be used

### Actual behaviour
`attentionButtonFg` color is used
Though `attentionButtonFgOver` works as it should in "Logout" menu

### Configuration
**Operating system:** Windows
**Version of Telegram Desktop:** 1.0.6

**Comment by john-preston** [comment]
@MasterGroosha Thanks you for your report. This will be fixed in the next version.

**Comment by ibrashon** [comment]
@john-preston please add disable animations in tdesktop

**Comment by MasterGroosha** [comment]
Seems to be fixed in 1.0.7 alpha. Thank you!
