### ISSUE TITLE
Search chat

### ISSUE THREAD

**Issue by abhyrz** [telegramdesktop/tdesktop#2975]
i can't search chats in Telegram Desktop when use minimazed chat's list

### Steps to reproduce
1. Minimize chat's list
2. Try find some chat
3. Have a sad :-(

### Actual behaviour
Have no search window

### Configuration
Win7Pro, Win7Home, LinuxMint18

**Version of Telegram Desktop:**
1.0.6

Minimized
![default](https://cloud.githubusercontent.com/assets/18555633/22643334/0ca9702c-ec6f-11e6-893e-8094fe51ea84.png)

Minimized menu
![default](https://cloud.githubusercontent.com/assets/18555633/22643362/2bc4c06a-ec6f-11e6-84f1-a774fb7d52dc.png)

Normal menu
![2](https://cloud.githubusercontent.com/assets/18555633/22643370/3a26d120-ec6f-11e6-92cf-1f2b2e15c81b.png)

————————————————————————————————————————

И еще раз на русском, ибо английского, очевидно, не знаю ;-)
В настольной версии приложения пропадает кнопка поиска по чатам при уменьшении ширины меню. в полном размере кнопка есть. скрины выше

**Comment by auchri** [comment]
Press <kbd>ESC</kbd> and you are done ;)

**Comment by abhyrz** [comment]
i know about ESC but i can't use it everytime :-)
telegram team are planning add window for search?

**Comment by john-preston** [comment]
@abhyrz In the narrow-left-column mode the search window is not planned. It doesn't fit there anyway and it should expand the chats list anyway. So just use your keyboard, sorry.
