### ISSUE TITLE
v1.0.6 Linux binaries?

### ISSUE THREAD

**Issue by gavv** [telegramdesktop/tdesktop#2977]
Hi, it seems that binaries for 1.0.6 are missing.

Works:

    wget https://updates.tdesktop.com/tlinux/tsetup.1.0.5.tar.xz

Doesn't work:

    wget https://updates.tdesktop.com/tlinux/tsetup.1.0.6.tar.xz

**Comment by john-preston** [comment]
@gavv Version 1.0.6 was built and deployed only for Windows, because it was fixing some critical bugs in Windows version and did nothing in other OSs.

**Comment by gavv** [comment]
Ah, thanks.
