### ISSUE TITLE
Text formatting not working in Desktop version. However other contacts can send messages with text formatting just fine.

### ISSUE THREAD

**Issue by Flam1ngDem0n** [telegramdesktop/tdesktop#2978]
Text formatting not functioning
### Steps to reproduce
1. Use the "*" or "-" in a chat
2. Send message to contact
3. No bold or italic text shows in chat log

### Expected behaviour
Tell us what should happen
Text should be bold or italicized

### Actual behaviour
Tell us what happens instead
Text does not show either of those.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.0.6

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by auchri** [comment]
#2847
