### ISSUE TITLE
No audio capture

### ISSUE THREAD

**Issue by sovietspaceship** [telegramdesktop/tdesktop#2979]
### Steps to reproduce
Have no pulseaudio installed, ALSA backend only.

### Expected behaviour
Record some sound using the record audio button.

### Actual behaviour
Empty audio recording is sent. On startup, OpenAL complains that

> AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"

It used to work a few versions ago. [apulse](https://github.com/i-rinat/apulse) does not improve the situation. Audio output works perfectly fine.

### Configuration
Linux, ALSA backend with no pulseaudio installed and custom asound.conf. Could be related
to my ALSA configuration, but Telegram is the only application exhibiting this behavior.
Capturing with arecord works with no issues.

Version is Telegram Desktop 1.0.5 alpha

### Logs

```[2017.02.06 23:39:51] OpenAL Logging Level: (not set)
[2017.02.06 23:39:51] Audio Playback Devices: OpenAL Soft
[2017.02.06 23:39:51] Audio Playback Default Device: OpenAL Soft
[2017.02.06 23:39:51] Audio Capture Devices: ALSA Default;HDA Intel PCH, CX20751/2 Analog (CARD=PCH,DEV=0)
[2017.02.06 23:39:51] Audio Capture Default Device: ALSA Default
```

I think OpenAL complains about pulseaudio not existing on my system, though apparently falls back to ALSA since it looks like the default ALSA capture device is opened.

**Comment by Aokromes** [comment]
Try after a00941f
