### ISSUE TITLE
[Feature Request] Highlight messages containing your username in groupchat

### ISSUE THREAD

**Issue by piejanssens** [telegramdesktop/tdesktop#298]
IRC like:
- Autocomplete usernames in groupchat (on tab)
- Hightlight message balloons when it contains your username

**Comment by onotoleonide** [comment]
> Hightlight message balloons when it contains your username
this

**Comment by FichteFoll** [comment]
Autocompletion has been implemented, but highlighting mentions of your username or replies to you would be nice!

**Comment by justserega** [comment]
It would be great if in groupchat with disable notifications username mentions initiate notification. Like it is in Slack.

**Comment by TiagoDanin** [comment]
Highlight - Duplicate #250

**Comment by FichteFoll** [comment]
Not a duplicate. #250 is about code highlighting, while this issue is about highlighting messages that mention you. See the pink line in this example:

![2016-02-20_13 49 21](https://cloud.githubusercontent.com/assets/931051/13196778/c4cb558c-d7d8-11e5-976e-de2bd841995f.png)

**Comment by TiagoDanin** [comment]
@FichteFoll Understand... Sorry :)
+1 When the autocomplete usernames :+1:

**Comment by pruiz** [comment]
And maybe a sound notification on the user being mentioned would be a plus. ;)

**Comment by FichteFoll** [comment]
I get this. Do you have "Play sound" unchecked in your settings?

**Comment by ArmeF97** [comment]
This can be closed

**Comment by stek29** [comment]
@ArmeF97 nope, messages mentioning you are not highlighted, you just get a notification and can go to them faster once, but there's no visual indication (like in irc or discord)
