### ISSUE TITLE
[feature] larger emojis when no text in message

### ISSUE THREAD

**Issue by philiparvidsson** [telegramdesktop/tdesktop#2981]
inspired by iOS 10, messages containing only emojis should be shown larger than when they appear together with text. see screenshot below:

![image](https://cloud.githubusercontent.com/assets/1163299/22707940/b2d8a50c-ed74-11e6-95dc-91df76d7e461.png)

**Comment by auchri** [comment]
It was like that in the android app for some time, but they removed it.
