### ISSUE TITLE
Add new color parameters msgInFg and msgOutFg

### ISSUE THREAD

**Issue by Recouse** [telegramdesktop/tdesktop#2983]
Add new color parameters `msgInFg` and `msgOutFg`. Now you can only edit windowFg and nothing more, it is very inconvenient.

It would be very useful for themes designers.

**Comment by MasterGroosha** [comment]
What should these keys do?

**Comment by Recouse** [comment]
Messages bubble text color.

**Comment by MasterGroosha** [comment]
I think you're looking for `historyTextInFg` (Incoming messages text color) and `historyTextOutFg` (Outgoing messages text color)

**Comment by Recouse** [comment]
Oh, I've not noticed. Tanks :)
