### ISSUE TITLE
Allow editing of currently loaded theme in Settings 

### ISSUE THREAD

**Issue by T3rminat0r** [telegramdesktop/tdesktop#2985]
### Steps to reproduce
1. You notice you would want to change a specific color in the currently loaded theme.
2. You go into Settings and open the Theme Color Editor

### Expected behaviour
I would like an option to change the currently loaded theme, without having to remember where I put it's color scheme file, or even which theme I DID load last ...

### Actual behaviour
I need to find the theme file, extract it, edit the color, and then re-apply the theme.

### Configuration
Independent of OS

**Version of Telegram Desktop:**
1.0.7 alpha

**Comment by john-preston** [comment]
@T3rminat0r You can edit exactly current theme by a button in settings.
