### ISSUE TITLE
Theme editor crashes if comment section uses /*

### ISSUE THREAD

**Issue by parabola949** [telegramdesktop/tdesktop#2987]
### Steps to reproduce
1. Create a new theme, add a comment section like 
```   
/*
 *comments
*/
```
2. Load theme into Telegram
3. Edit theme with new alpha feature
4. Try to change any color

### Expected behaviour
Should save the new color

### Actual behaviour
Crashes, error log shows: 
` Theme Error: could not replace 'dialogsDraftFg: #e81123' in content`
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.0.7 Alpha
### Logs
[2017.02.08 10:27:57] Theme Error: could not replace 'dialogsDraftFg: #e81123' in content
[2017.02.08 10:30:19] Theme Error: could not replace 'dialogsDraftFgActive: #ff0000' in content

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

Granted, I realize maybe this comment style wasn't meant to be used, not even sure which theme I originally got it from, I think one of the solarized themes.  However, if tdesktop can load the theme like this, the editor should probably be able to handle it as well

**Comment by john-preston** [comment]
@parabola949 Can you provide a sample of such theme here?

**Comment by john-preston** [comment]
@parabola949 This will be fixed in the next version, thank you.

Can you tell, what means "crashes" in your report? You mean the editor is closed with an error message or that the whole Telegram Desktop crashes?

**Comment by parabola949** [comment]
Sorry, yes, I meant to put that the editor crashes, not the entire application.  I'll send a theme in a few you can test with

**Comment by john-preston** [comment]
@parabola949 Thanks, I've fixed the problem in the dev branch, so it'll be fixed in the next version.
