### ISSUE TITLE
Allow theming selected state of some theme parametres

### ISSUE THREAD

**Issue by MrYadro** [telegramdesktop/tdesktop#2989]
### Steps to reproduce
1. `windowActiveTextFg`, `historyPeerNUMNameFg`, `msgInMonoFg`, `msgOutMonoFg`

### Expected behaviour
Should have selected state

### Actual behaviour
-

### Configuration
**Operating system:** Linux

**Version of Telegram Desktop:** 1.0.7

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by john-preston** [comment]
Where does `windowActiveTextFg` appear there? I'm curios about differences in In and Out, because `historyPeerNUMNameFg` appear only inside inbox messages, but what do you control by `windowActiveTextFg` in message bubbles and shouldn't it be different in In and Out?

**Comment by MrYadro** [comment]
I think that `windowActiveTextFg` used everywhere from links and hashtags in chats to "links" and profile status in settings. I had to balance those colors.
![screenshot_20170209_162045](https://cloud.githubusercontent.com/assets/1587606/22776851/d35436be-eee3-11e6-927b-d548926ca7a0.png)

About `historyPeerNUMNameFg`
When you forward message from someone, text has selected parameter and it works perfect
![screenshot_20170209_162438](https://cloud.githubusercontent.com/assets/1587606/22776969/54deae1c-eee4-11e6-95cf-a3a610a39947.png)
but if you select  message from someone in group, now name is gone (not really gone, they are the same color in my theme)
![screenshot_20170209_162621](https://cloud.githubusercontent.com/assets/1587606/22777053/9adbbe1e-eee4-11e6-8838-0520c5c22ceb.png)
I know that it's my color theme but why it has selected state when it forwarded, but not when you select it.

I'm not asking for different colors for `windowActiveTextFg` in In and Out, I'm asking for Selected state of that color or split it to Chat and Settings. Same goes to `msgInMonoFg` (not sure about that one, but it might be nice) and `historyPeerNUMNameFg`, could be one color for every Peer, like here:
![screenshot_20170209_165103](https://cloud.githubusercontent.com/assets/1587606/22778058/0f498198-eee8-11e6-99a3-89efd9c2023e.png)
Oh it's `windowActiveTextFg` again.

Thank you.

**Comment by john-preston** [comment]
@MrYadro I can make selected states for historyPeerNUMNameFg, but I can't currently change selected colors for message text colors (including monospace width text and link text colors), because they're used not only for full selected messages, but also for partially selected text inside messages. And currenlty I can't paint selected text parts in color different from the same text not selected parts :(

**Comment by john-preston** [comment]
I mean this:

![image](https://cloud.githubusercontent.com/assets/17900494/22778393/d40aa046-eec7-11e6-8916-bd871f2bdf01.png)

These are the same "selected" colors as when you select full message. And currently I have no way of painting selected text part differently from the rest of the text.

**Comment by MrYadro** [comment]
But you can split `windowActiveTextFg`, riiiiight?
![big_1450724989_image](https://cloud.githubusercontent.com/assets/1587606/22778538/ea4c3244-eee9-11e6-87b4-500a410e2b7a.jpg)
At least one for settings and one for chats.

**Comment by john-preston** [comment]
Yes, for chats can be other than for Settings.

I'll try to split (In / Out) and (plain / Selected) as well, but I'm not sure this will work out.

**Comment by john-preston** [comment]
Ok, they all will be different keys.

**Comment by MrYadro** [comment]
Thank you!

**Comment by MasterGroosha** [comment]
Are `historyCaptionInFg` and `historyCaptionOutFg` gone now?

**Comment by john-preston** [comment]
@MasterGroosha Yes, I use the same bubble background, style and everything for caption text as I use for messages text, so I decided that the color of the text in the bubbles should be unified as well.
