### ISSUE TITLE
Spotify uri handler

### ISSUE THREAD

**Issue by berendhaan** [telegramdesktop/tdesktop#299]
I would love to see spotify-uris opened in the Spotify desktop client.

Url format: spotify:(track|artist):unique_id
Example url: spotify:track:23062qFelDaObxOPDRkVCq

**Comment by adisos** [comment]
+1

**Comment by TiagoDanin** [comment]
+1 Great idea :+1:

**Comment by syabro** [comment]
+1

**Comment by rigo128** [comment]
+1

**Comment by stek29** [comment]
#2677 related

**Comment by pindab0ter** [comment]
Any word on whether/when this is coming?
