### ISSUE TITLE
[bug] Freeze on viewing Venue

### ISSUE THREAD

**Issue by duhow** [telegramdesktop/tdesktop#2991]
### Steps to reproduce
1. Ask a bot to send a location (venue)

### Expected behaviour
View the venue (map and text)

### Actual behaviour
The desktop app freezes and can't do anything. I have to delete the message from another device to fix it.

### Configuration
**Operating system:** Windows 7 SP1

**Version of Telegram Desktop:** 1.0.6

**Comment by auchri** [comment]
Do you have an example for that bot?

**Comment by MasterGroosha** [comment]
@auchri Use `@foursquare` bot (inline mode)

**Comment by auchri** [comment]
I also can't reproduce this (W10)

![image](https://cloud.githubusercontent.com/assets/5092164/23330192/31eaceb6-fb48-11e6-9261-e70a364b7f40.png)

**Comment by duhow** [comment]
Working without problems.
