### ISSUE TITLE
Groups getting orphaned easily

### ISSUE THREAD

**Issue by Lailah** [telegramdesktop/tdesktop#2992]
### Steps to reproduce
1.  A group owner has some kind of problem  (can't login, phone stolen, account disabled or deleted, gets sick, etc.)
2.  Group owner tries to give his or her privileges to someone else so the group doesn't die.
3.  Impossible. There's no way to grant someone else owner (or almost owner) privileges. 
4.  Group ends up orphan and dies in a way or another.

### Expected behaviour
Tell us what should happen
The group owner should be able to give owner privileges to others so the group doesn't die, even if he or she can't keep up with the work.

### Actual behaviour
Tell us what happens instead
Groups get orphaned too often and creating a new group, migrating users, etc is a cumbersome process. Plus all the material shared (links, images, docs, etc) will be lost.

### Configuration
**Operating system:**
Desktop (Linux), Android, web version.

**Version of Telegram Desktop:**
1.0.5

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by auchri** [comment]
This repo is for Desktop only.

**Comment by Lailah** [comment]
Where should I request this then?
Thanks in advance.

**Comment by stek29** [comment]
@Lailah Twitter or Ask a question button in settings.
