### ISSUE TITLE
Changing audio output does not work

### ISSUE THREAD

**Issue by ManuelSchneid3r** [telegramdesktop/tdesktop#2993]
### Steps to reproduce
1. Play sound e.g. voice message
2. Change audio output, e.g. from headset to speakers

### Expected behaviour
Sound should come from speakers

### Actual behaviour
Sound still comes from headset

### Configuration
**Operating system:**
Linux, PulseAudio
**Version of Telegram Desktop:**
1.0.2

**Comment by auchri** [comment]
Update to 1.0.5

**Comment by ManuelSchneid3r** [comment]
Indeed fixed thank you.
