### ISSUE TITLE
User status is set to 'offline' when viewing a photo full screen

### ISSUE THREAD

**Issue by matteocontrini** [telegramdesktop/tdesktop#2996]
### Steps to reproduce
1. Launch Telegram
2. Click on a photo in any conversation
3. Notice on another device that the user status becomes 'offline'

### Expected behaviour
I don't think the user should be put offline. Viewing a photo in Telegram is still being online on Telegram. I think this is confusing for other people that send me a photo and while I view it they see that I'm offline.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.0.7

**Comment by rdrrdl** [comment]
I was very happy when i saw that, i didn't think it was a bug.
When I am staring at a picture of someone, or watching a video, i do not want people thinking i am online and trying to send me things then
thanks so much for the new versions of telegram, and please do not change this feature.

**Comment by matteocontrini** [comment]
You can stare pictures outside Telegram ;)
When I receive a photo from a friend, I don't want him to see me as offline while I'm viewing the photo. It's misleading.

**Comment by leovp** [comment]
Not only that, Telegram sets the status to "Offline" when it loses focus for any reason.
Even when I do a full screenshot I tend to become "Offline" for a fraction of a second.

What's even funnier: if I'm in a group chat and 5 members are online (including me), I can't make a screenshot that says "5 members, 5 online". The moment a screenshot is being captured, Telegram window loses focus and sends me Offline. But a couple of milliseconds later I'm online again...

I really want to help with this issue. BTW: Linux is affected too, so I believe it's a Qt-related issue.

**Comment by rdrrdl** [comment]
seriously?
The older versions of telegram had what I thought was a bug, that it took an extra few seconds to know when I'm not online.
When I am writing to someone, I would like to know if he's looking at the screen or not. Please don't take that away... 
Also, windows 10 has a "delay" option on their snipping tool. I just took a screenshot of all the members online.
I really like this feature and would not want it changed.

**Comment by leovp** [comment]
> The older versions of telegram had what I thought was a bug, that it took an extra few seconds to know when I'm not online.

This is not a bug, but an expected behaviour. There is a timer specifically for this. See here: https://github.com/telegramdesktop/tdesktop/blob/7ab87486dce2c74fc21308a518e65a24891a4b71/Telegram/SourceFiles/facades.cpp#L648

> Also, windows 10 has a "delay" option on their snipping tool. I just took a screenshot of all the members online.

Yes, when you use screenshotter that allow you to mark an area on screen, everything is OK, because focus isn't lost. But if you take a full screenshot, then the focus is lost. Anyway, that was just an example, losing focus for a couple of seconds shouldn't take a user offline, _as per source code_.

>  I really like this feature and would not want it changed.

I understand. But right now it's not an intended feature, but a bug. If you want this behaviour to become expected and normal, you should probably submit a feature request. I will even support this initiative, if it doesn't break online/offline status too much. But as of this moment it's pretty much broken.

**Comment by john-preston** [comment]
@leovp The timeout you refer to is an "idle timeout", which means it is used when there is no input (mouse or keyboard) in the active Telegram window for some time.

**Comment by leovp** [comment]
Can you share your thoughts on the issue? Is this a bug? A couple of month ago I could click on another window, and then go back to Telegram without losing "Online" status. Now every loss of focus changes the status. I think it may be too intesive or frequent. I'm using tiles, so every window is visible at all times. It might be better to revert to previous mode, where you become offline when you close a tab or really are idle for a while...

I'm going to share screenshots or videos to show what's going on.

**Comment by matteocontrini** [comment]
@leovp in old versions, it took 5 seconds for you to go offline when Telegram lost focus. I think it's much better now, as you are immediately put offline when Telegram loses focus. That's how the Android app does it as well.

The issue wasn't questioning this behaviour in general (create another issue for that, if you want), but only the fact that the status is set as offline when you're viewing a photo within Telegram.

**Comment by leovp** [comment]
@matteocontrini Thanks for the info!
> but only the fact that the status is set as offline when you're viewing a photo within Telegram.

Probably because main window loses focus :)
But you are right, they are only a bit related, it's better to separate these issues. I'll investigate both!

**Comment by WiRight** [comment]
Confirm on Debian 9

**Comment by gpchelkin** [comment]
This issue is still present.

**Comment by WiRight** [comment]
This issue is still present.
