### ISSUE TITLE
Failed to compile Opus codec

### ISSUE THREAD

**Issue by sajedmohseni** [telegramdesktop/tdesktop#2997]
### Steps to reproduce
1. git clone https://github.com/telegramdesktop/opus.git
2. Open in VS2015 D:\TBuild\Libraries\opus\win32\VS2010\opus.sln
3. Build Debug configuration

### Expected behaviour
Tell us what should happen
Build Opcus codec without errors

### Actual behaviour
i get these errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'version.h': No such file or directory	test_opus_decode	e:\projects\telegram desktop\libraries\opus\win32\config.h	43	

i tried to compile ffmpeg too, but it failed

logs:
Sajed@Sajed MSYS /e/Projects/Telegram Desktop/Libraries/ffmpeg
$ ./configure --toolchain=msvc --disable-programs --disable-doc --disable-everything --enable-protocol=file --enable-libopus --enable-decoder=aac --enable-decoder=aac_latm --enable-decoder=aasc --enable-decoder=flac --enable-decoder=gif --enable-decoder=h264 --enable-decoder=mp1 --enable-decoder=mp1float --enable-decoder=mp2 --enable-decoder=mp2float --enable-decoder=mp3 --enable-decoder=mp3adu --enable-decoder=mp3adufloat --enable-decoder=mp3float --enable-decoder=mp3on4 --enable-decoder=mp3on4float --enable-decoder=mpeg4 --enable-decoder=msmpeg4v2 --enable-decoder=msmpeg4v3 --enable-decoder=wavpack --enable-decoder=opus --enable-decoder=vorbis --enable-decoder=wmalossless --enable-decoder=wmapro --enable-decoder=wmav1 --enable-decoder=wmav2 --enable-decoder=wmavoice --enable-encoder=libopus --enable-hwaccel=h264_d3d11va --enable-hwaccel=h264_dxva2 --enable-parser=aac --enable-parser=aac_latm --enable-parser=flac --enable-parser=h264 --enable-parser=mpeg4video --enable-parser=mpegaudio --enable-parser=opus --enable-parser=vorbis --enable-demuxer=aac --enable-demuxer=flac --enable-demuxer=gif --enable-demuxer=h264 --enable-demuxer=mov --enable-demuxer=mp3 --enable-demuxer=ogg --enable-demuxer=wav --enable-muxer=ogg --enable-muxer=opus --extra-ldflags="-libpath:/e/Projects/Telegram Desktop/Libraries/opus/win32/VS2010/Win32/Release celt.lib silk_common.lib silk_float.lib"
cl is unable to create an executable file.
If cl is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

_____
I've already installed latest version of git and i checked path (PATH="/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN:$PATH") its correct..

### Configuration
**Operating system:**
Windows 10 x64 Enterprise

**Version of Telegram Desktop:**
Latest version of telegram desktop

### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by auchri** [comment]
I don't think that's an issue of telegram desktop
