### ISSUE TITLE
Back button to return in stack when image viewer is open

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#2998]
### Steps to reproduce
1. Open shared photos -> any image
2. Press "back" on mouse/keyboard

### Expected behaviour
First, image should close, then all other windows must close in stack

### Actual behaviour
Image is still visible, however windows are being closed in stack in background

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.0.8

**Comment by BoffinbraiN** [comment]
Confirmed; still present in 1.1.18.
