### ISSUE TITLE
No indicator applet icon in Unity Ubuntu 16.04 and 16.10

### ISSUE THREAD

**Issue by Alinaki** [telegramdesktop/tdesktop#2999]
### Steps to reproduce
Just run latest and previous Telegram Desktop on Ubuntu 16.04 or 16.10 with Unity

### Expected behaviour
Telegram icon on Unity indicators panel.

### Actual behaviour
![screenshot from 2017-02-11 12-21-15](https://cloud.githubusercontent.com/assets/832780/22852785/17a6e5a6-f055-11e6-876e-9ada9c474259.png)

### Configuration
Ubuntu 16.04 and Ubuntu 16.10 with Unity DE.

Telegram version 1.0.2 (latest Linux update)

**Comment by auchri** [comment]
The latest version is 1.0.6

Please try the binary from https://desktop.telegram.org/
