### ISSUE TITLE
[feature request] multiple Telegram accounts

### ISSUE THREAD

**Issue by Ottobaer** [telegramdesktop/tdesktop#30]
Hello, 

Just an idea that came up. It would be nice to have multiple Telegram accounts you can create/select on startup.

**Comment by telegramdesktop** [comment]
This is not planned right now, one OS user -- one Telegram account. It is preferred to use different OS users with passwords if necessary.

**Comment by alshakero** [comment]
Here is my solution, quite easy.
http://omaralshaker.com/blog/2016/05/28/multiple-telegram-accounts-on-a-windows-pc/

**Comment by stek29** [comment]
@alshakero You can just use portable version
Much easier
Also, @auchri, does it have command line parameter for multiple instances on Windows too?

**Comment by alshakero** [comment]
@stek29 didn't know about this one! Perfect!

**Comment by stek29** [comment]
@alshakero Could you try [this](https://github.com/telegramdesktop/tdesktop/issues/533#issuecomment-219857356) too?
