### ISSUE TITLE
AppVeyor integration

### ISSUE THREAD

**Issue by auchri** [telegramdesktop/tdesktop#3000]
Hey guys,

we are planning to integrate [AppVeyor](https://ci.appveyor.com/project/telegramdesktop/tdesktop) into our GitHub repository.

> AppVeyor is a hosted, distributed continuous integration service used to build and test projects hosted at GitHub on a Microsoft Windows virtual machine.

We already enabled AppVeyor for PR's and commits.
The documentation for the [AppVeyor configuration file](https://github.com/telegramdesktop/tdesktop/blob/feature/appveyor/appveyor.yml) is [here](https://www.appveyor.com/docs/appveyor-yml/).

---

If you want to help to integrate AppVeyor into our repository, we are happy to merge PR's to our [feature/appveyor](https://github.com/telegramdesktop/tdesktop/tree/feature/appveyor) branch!

[Build instructions for Visual Studio 2015](https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-msvc.md)

Since we want to follow our instructions, the main folder for the project is `C:\TBuild`.
There we clone the source code and install the libraries into `C:\TBuild\Libraries`.

---

Current tasks/issues:

- [x] Compile all dependencies and store them into the [Git repo](https://github.com/telegramdesktop/dependencies_windows)
  * [x] OpenSSL
  * [x] LZMA Sdk
  * [x] zlib
  * [x] libexif
  * [x] OpenAL
  * [x] Opus codec
  * [x] FFmpeg
  * [x] QT 5.6.2 patched
  * [x] Google Breakpad
- [ ] Create a README.md for the [dependencies Git repo](https://github.com/telegramdesktop/dependencies_windows)
- [x] Don't build qt every time
- [x] Clone the dependencies repo on AppVeyor
- [x] Run the prepare.bat
- [x] Resolve build errors
- [x] Create a script to clean up the compiled dependencies

<sup>3000 issues 🎉🎉🎉</sup>

**Comment by auchri** [comment]
Current issues:

- [ ] Calling `ms\do_ms` in openssl exits bash script somehow
- [ ] Find a way to extract the LZMA SDK (`.tar.bz2` file)

**Comment by john-preston** [comment]
@auchri I don't quite understand how to build ffmpeg there.
