### ISSUE TITLE
[BUG] upgrading pinned group to supergroup wastes 1 pin

### ISSUE THREAD

**Issue by tkossak** [telegramdesktop/tdesktop#3001]
### Steps to reproduce
1. Pin 5 chats, including one group
2. Upgrade the one pinned group to SuperGroup
3. Restart Telegram
4. The upgraded group is NOT pinned. You have only 4 chats pinned and when you try to pin 5'th chat you get error "Sorry, you can pin no more than 5 chats to the top"

### Expected behaviour
When i have only 4 pinned chats and i click "pin" on the 5'th chat i expect it to be pinned

### Actual behaviour
The error "Sorry, you can pin no more than 5 chats to the top"

### Configuration
**Operating system:**
Linux Mint 18 Cinnamon (x64)

**Version of Telegram Desktop:**
1.0.5

### Logs
I think they are not necessary (they contain only network events?), but tell me if you need them (do they contain any personal/sensitive info?)

**Comment by stek29** [comment]
@tkossak 
> do they contain any personal/sensitive info?
Yes, everything that was sent to / received from server.

**Comment by john-preston** [comment]
Thanks for your report, I hope to fix this in one of the next versions.

**Comment by ugozhaev** [comment]
I have same problem. Do I have to start a new issue?

**Comment by auchri** [comment]
no, It's already fixed in the dev branch
