### ISSUE TITLE
[BUG] Can't edit messages written before upgrading group to SuperGroup

### ISSUE THREAD

**Issue by tkossak** [telegramdesktop/tdesktop#3002]
### Steps to reproduce
1. Create group
2. Write a message in the group (or few messages)
3. Upgrade group to SuperGroup
4. Right click any message you wrote BEFORE you upgraded to SuperGroup and choose "Edit"

### Expected behaviour
The message appears on the bottom of the app, you can change it and post your changes.

### Actual behaviour
The message appears for fraction of a second and then instantly disappers (so you can't edit it)

### Configuration
**Operating system:**
Linux Mint 18 Cinnamon (x64)

**Version of Telegram Desktop:**
1.0.5

### Logs
Probably not needed.

**Comment by MasterGroosha** [comment]
As far as I remember, it's a known thing and API issue rather than TDesktop issue.
