### ISSUE TITLE
No error messages while adding person to group

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#3005]
### Steps to reproduce
1. Have a friend whom you can't add to group due to privacy settings (and you might not know it)
2. Try adding him to group via username while creating it
OR
3. Try adding him to group via username after creating it

### Expected behaviour
An error message ("You cannot add this person due to privacy settings") should be shown (or something like that)

### Actual behaviour
(2): when you press "Create" nothing happens and dialogue window doesn't disappear (`error USERS_TOO_FEW` in logs)
(3): when you press "Invite" dialogue window disappears and nothing happens (`error USER_PRIVACY_RESTRICTED` in logs)

Why I'm posting this to TDesktop repo is because it is unclear for users why dialogue windows don't disappear (2) or why nothing happens (3). On Android, a dialogue window appears with "You cannot add this user..." message.

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.0.9 alpha

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by MasterGroosha** [comment]
It's fixed now. Works like in "Expected Behaviour" section
