### ISSUE TITLE
Allow location selection in Desktop

### ISSUE THREAD

**Issue by tvld** [telegramdesktop/tdesktop#3006]
Our users need to **pick a few locations** on a map: so **not** their current location. It now shows `Sorry, the location sharing is currently unavailable in Telegram Desktop` 
It limits our functionality a lot... Any idea how to get this in here?

**Comment by auchri** [comment]
Hints for the next time:
* Use search before creating a new issue
* Use the template.

#1193

**Comment by tvld** [comment]
ok, sorry, I did. That issue seemed slightly different at first glance, though. Thanks for quick response
