### ISSUE TITLE
[Feature Request] Send audio message without long press; Start/End option.

### ISSUE THREAD

**Issue by TrendaFet** [telegramdesktop/tdesktop#3007]
I think the title explains itself. I find myself needing to record long messages and many times I get cut off by accidentally releasing the microphone button too early.

I would love it if an optional feature was introduced in settings to allow us to start recording then stopping it with another click.

It would be especially useful in group discussions where audio messages sometimes are the dominant form.

Thanks and keep up the great work.

**Comment by auchri** [comment]
Duplicate

**Comment by stek29** [comment]
#1060 btw.
