### ISSUE TITLE
Notifying all users by typing @everyone

### ISSUE THREAD

**Issue by SirwanAfifi** [telegramdesktop/tdesktop#3009]
It would be great to have ability to mention all online users by typing @everyone, just like Slack:
`@everyone announcement message.`

**Comment by MasterGroosha** [comment]
I think this is an API issue since no official Telegram apps (Android, iOS, Desktop, WP) have such feature. Maybe it's impossible with the current MTProto scheme.

**Comment by stek29** [comment]
It's also a duplicate: #2397
