### ISSUE TITLE
'--' sometimes converted to '—' when sending message

### ISSUE THREAD

**Issue by hashashin** [telegramdesktop/tdesktop#3010]
### Steps to reproduce
1.  Type -- after any other word, ie: test --wathever

### Expected behaviour
send: test --wathever

### Actual behaviour
send: test —wathever

note typing "--wathever" or "--" as the only message sends "--wathever" or "--" correctly, sending ie: -- -- sends: — —
Also in the android app this is not the behavior, on my tests "--" it's not converted.
So, not sure if it's feature or a bug. :confused:

### Configuration
Windows 10

1.0.6

Thanks.

**Comment by auchri** [comment]
> So, not sure if it's feature or a bug.

It's a "feature".
