### ISSUE TITLE
Focuses when switching desktops on Windows 10

### ISSUE THREAD

**Issue by dasJ** [telegramdesktop/tdesktop#3011]
### Steps to reproduce
1. Have multiple desktops on Windows 10
2. Have Telegram not focused (behind a maximized window)
3. Use Ctrl+Win+Arrow left/right to switch to another desktop

### Expected behaviour
Telegram stays on the desktop it was before or at least stays in the background

### Actual behaviour
Telegram is in the foreground and has the focus

### Configuration
**Operating system:**
Windows 10 Version 1511

**Version of Telegram Desktop:**
1.0.6

**Comment by auchri** [comment]
Duplicate #1968
