### ISSUE TITLE
Telegram desktop video file specs

### ISSUE THREAD

**Issue by WyRe** [telegramdesktop/tdesktop#3012]
I'm trying to send video files from Telegram desktop app for Linux but it recognizes as simple files. To recognizes them as video files I need to transfer them to my mobilephone and send it from gallery. 

I've tried to convert my videos using the specs specified in here
https://core.telegram.org/blackberry/chat-media-send
using ffmpeg:
 `ffmpeg -i input.webm -vcodec libx264 -acodec aac -s 480x320 output.mp4`

But doesn't work either. Is there someway to send videos from Telegram desktop app and that it recognize as video?

**Comment by john-preston** [comment]
@WyRe There is no way to send a video from tdesktop right now :( if you send a small mp4 file (less than 10mb) it'll be sent as video, because server will get the required attributes, tdesktop will show that after restart.

**Comment by WyRe** [comment]
Ok, thank you for the info, I hope in a future the desktop app could send videos like android app. :)
