### ISSUE TITLE
`@webpagebot` does not update `og:description`

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [telegramdesktop/tdesktop#3017]
### Steps to reproduce
1. Open the bot `@webpagebot`
2. Issue an `/updatepreview` command
3. Copy and paste a link containing `og:description` e.g. http://www.woforo.com/blogs/HosseinAbedi/curse-of-dimensionality

### Expected behaviour
Description should've been updated

### Actual behaviour
State changes to `UPDATE_SUCCESS` but description won't be updated

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.0.6

**Comment by auchri** [comment]
Not related to telegram desktop

**Comment by keyvan-m-sadeghi** [comment]
@auchri would've been nice if you pointed me at the corresponding maintainer, only you guys know who is who and I couldn't find a central telegram org that hosts all its projects. Arrived here by a Google query for `@webpagebot` and `GitHub`.

**Comment by auchri** [comment]
Sorry I also don't know how is the maintainer of the bot. Maybe @john-preston knows it.

**Comment by john-preston** [comment]
@keyvan-m-sadeghi Does the description get updated after relaunch of Telegram Desktop? (in other words, does the bot really not update the description or just Telegram Desktop still uses some old, cached version of description?)

**Comment by keyvan-m-sadeghi** [comment]
Aha! Nice observation @john-preston, yes, it was being cached. Thanks a ton.

**Comment by john-preston** [comment]
@keyvan-m-sadeghi So it looks like tdesktop bug (as I know it should invalidate the cache), thanks for your report.

**Comment by stek29** [comment]
So it's not <kbd>invalid</kbd> <kbd>api issue</kbd> :)

**Comment by auchri** [comment]
#3029
