### ISSUE TITLE
[Feature request] Open "Gifs & Stickers" tab by default

### ISSUE THREAD

**Issue by kissaev** [telegramdesktop/tdesktop#3018]
Option to choose which tab opens by default, Emoji or Gifs and Stickers

**Comment by stek29** [comment]
I think it would be better just to remember what tab was opened. (and remember scroll position)

**Comment by kissaev** [comment]
> I think it would be better just to remember what tab was opened. (and remember scroll position)
Yes, this is be good too.

**Comment by auchri** [comment]
> I think it would be better just to remember what tab was opened. (and remember scroll position)

#1076
