### ISSUE TITLE
[REQUEST] Fedora / Ubuntu official packages of Tdesktop

### ISSUE THREAD

**Issue by sergioad** [telegramdesktop/tdesktop#302]
Hello friends can you make a official Fedora / Ubuntu package with it's official repositores for distributing Tdesktop easilly?

**Comment by Yajo** [comment]
I don't know if you devs know [OBS](https://build.opensuse.org/), but it's worth checking out. It has a nice web UI to let you automate package creation for some of the most common Linux distros, and end users have a common interface with instructions for their distro.

As an example, you can check the final results entering [Enki](http://enki-editor.org/) and clicking on Linux installer.

**Comment by jalcine** [comment]
OBS looks like a really good solution for this, until the packaging is maintained by core distribution managers. Has anyone already started putting Telegram into OBS?

**Comment by cassiodoroVicinetti** [comment]
Duplicate #253
