### ISSUE TITLE
zlib link in build instructions is dead

### ISSUE THREAD

**Issue by parabola949** [telegramdesktop/tdesktop#3020]
In build instructions, http://zlib.net/zlib128.zip link is no longer available.  If 1.2.8 is still the required version, switch to fossils: http://www.zlib.net/fossils/zlib-1.2.8.tar.gz (zip extension was not available).

**Comment by auchri** [comment]
I fixed it already here: https://github.com/telegramdesktop/tdesktop/tree/feature/msvc_fixes

**Comment by parabola949** [comment]
Apologies.  Forgot to remove the `is:open` filter when I previously searched issues for this.

**Comment by mazi5769** [comment]
Bebin madareto gaeydam 
Abji najibeto.   kole omat began
