### ISSUE TITLE
Touchbar emoji doesn't work

### ISSUE THREAD

**Issue by Drakas** [telegramdesktop/tdesktop#3022]
### Steps to reproduce
1. Use a MacBook Pro 2016 with touch bar

### Expected behaviour
Possibility to select emojis from touch bar

### Actual behaviour
The touch bar is disabled with telegram and can't select emojis from it.

### Configuration
Sierra 10.12.3 (16D32)

**Version of Telegram Desktop:**
1.0.5

**Comment by auchri** [comment]
#2853
