### ISSUE TITLE
[bug] line above search results when you're searching by hashtag

### ISSUE THREAD

**Issue by fluidpanda** [telegramdesktop/tdesktop#3023]
### Steps to reproduce
1.  Write a line of text in a chat with someone.
2.  Write another line of text right after the first one with a link and a hashtag.
3.  Leave the chat and type your hashtag in a search box.

### Expected behaviour
Telegram should search for a hashtag and display chat element where you could go and after a click you should see highlighted item with slow transition effect.

### Actual behaviour
But instead of just a transition effect you see a strange blue line above the text box.

### Configuration
**Operating system:** Windows 2008 R2

**Version of Telegram Desktop:** 1.0.9

![1](https://cloud.githubusercontent.com/assets/11980517/23035258/8dcd66fe-f48f-11e6-928d-ae576260cacf.png)

![2](https://cloud.githubusercontent.com/assets/11980517/23035277/9b8d9b42-f48f-11e6-902c-1009c5939484.png)

**Comment by john-preston** [comment]
Thanks for your report! I hope to fix this in the next version.

**Comment by Lazek** [comment]
@john-preston Identical bug: https://github.com/telegramdesktop/tdesktop/issues/2904 - please applied fix too.

**Comment by john-preston** [comment]
@Lazek I cannot reproduce that. What OS / interface scale do you try this in? Maybe you launched it on non retina screen and then view on retina screen or vice versa?

**Comment by Lazek** [comment]
@john-preston Yes, confirmed in old version, already fixed (forgot update ;))

**Comment by john-preston** [comment]
@Lazek I guess this will happen in that cases (when you switched retina to non-retina or back after launching the app), but I can't avoid it for now. In other cases it should not happen.
