### ISSUE TITLE
Problem with new emojis (inconsistency)

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#3024]
### Steps to reproduce
1. Send any "new" iOS emoji via TDesktop to Android
2. Send any "new" iOS emoji via Android to TDesktop
For example, [this](http://emojipedia.org/female-guard/ or Telegram-specific [this](https://telegram.org/blog/unsend-and-usage) (in the bottom)

### Expected behaviour
There should be consistency in how emojis are displayed.

### Actual behaviour
1) Speaking of "¯\_(ツ)_/¯" emoji:
![image](https://cloud.githubusercontent.com/assets/2780044/23066087/dc30b46e-f529-11e6-8972-3ba047ccde51.png)
The first emoji was sent from TDesktop to Android and the second one is sent from Android to Desktop

2) Speaking of "Female guard" emoji (you can choose anything else [here](http://blog.emojipedia.org/ios-10-emoji-changelog/))
If you send "Female guard" emoji from TDesktop to Android, it's displayed correctly.
However if you send "Female guard" emoji from Android to TDesktop, it shows "Male guard" with female modifier (`‍♀`)

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.0.10 alpha

**Comment by john-preston** [comment]
Android sends them not like iOS does :( I'll need to make some workaround, thanks for your report.

**Comment by MasterGroosha** [comment]
Oh, didn't know that. Thank you for the info!

**Comment by MasterGroosha** [comment]
Seems to be fixed in 1.0.11. Thanks!
