### ISSUE TITLE
[Feature Request] Remove Pinned Chats limit

### ISSUE THREAD

**Issue by hadi77ir** [telegramdesktop/tdesktop#3026]
Currently, pinned chats are limited to 5, but someone may have 100+ chats, of which he wants 10 to be pinned.

Please remove this limit. (I'm thinking you're using an array with max length of 5, if that's the case, change it to a linked list :D )

**Comment by auchri** [comment]
This limit is server side.

**Comment by ovidiub13** [comment]
Where do we report the issue for the server then?

**Comment by stek29** [comment]
@ovidiub13 Twitter or Support (Ask a Question button in settings)

**Comment by CodingSpiderFox** [comment]
Has this been reported to the server side project?
If so, could you please provide a link to the issue here?

**Comment by stek29** [comment]
@CodingSpiderFox Server side issues are tracked internally. Even if you get the link you won't be able to view it.

**Comment by CodingSpiderFox** [comment]
Does that mean the issue was reported?

Viele Grüße

Christian

**Comment by stek29** [comment]
@CodingSpiderFox I don't know. I personally haven't reported it.

**Comment by oxydron** [comment]
Wow, this issue is closed. Just 5 pinned chat is so little. I have 9 main groups and 2 of them I need to search on the search field everyday, several times.

**Comment by CodingSpiderFox** [comment]
Can someone please tell me how to contact the server side maintainers?

**Comment by auchri** [comment]
@CodingSpiderFox https://twitter.com/telegram or in app support.

**Comment by CodingSpiderFox** [comment]
Reported it via in-app support. By the way: I was told that this is the official way to report server side issues.

"(Here in this chat is the official way for suggestions by the way. The app developers normally don't comment on such things.)"

**Comment by devcline** [comment]
This is really absurd.

**Comment by CodingSpiderFox** [comment]
Can you explain what in detail you mean by saying absurd and why?

**Comment by devcline** [comment]
@CodingSpiderFox 

- There is no filter / groups in the telegram so the whole list with bots, people and chans are the big mess, sometimes i even miss a messages from the people in this trash, i even created a second account for the groups, to use on another phone, but its another story
- Why to limit up to 5 pins if there is such a filter options ?

**Comment by oxydron** [comment]
Tabs for people, groups, bots and channels. No pin limit.

**Comment by DoJoMast3r** [comment]
Atleast 20 pins!!! 5 is crazy

**Comment by oxydron** [comment]
No pin limit.

2018-05-28 4:30 GMT-03:00 DoJoMast3r <notifications@github.com>:

**Comment by 221V** [comment]
version 1.3.9 telegram desktop ubuntu
and there are pin limit !!

proof -- https://i.imgur.com/fMEljJY.png

**Comment by oxydron** [comment]
Wow seriously that tabs to simplify out things and no pin limit is a bad idea? Ok, it's better to scroll for people, groups, channels and bots on a single list and a nice 5 pin limit.

**Comment by 221V** [comment]
you say "no pin limit"
but there are pin limit !!

maybe you write your thinking not fully correctly ))

**Comment by 3xploiton3** [comment]
Need this feature, please update

**Comment by devcline** [comment]
Open Sesame!

**Comment by Torrichel** [comment]
Same there. @TelegramBackendTeam, please, remove 5 pinned dialogs limit.

**Comment by necros2k7** [comment]
+1

**Comment by luisalvarado** [comment]
Hi dev team, it has been over a year since I posted my issue in regards to this explaining the common sense behind having multiple pin options and being able to sort them (a year) https://github.com/telegramdesktop/tdesktop/issues/4037

And 2 years since the OP here did it. I have no clue why, even at the server side someone though that 5 as a max was enough. Same reason am guessing at one point bill gates thought 640kb of ram was enough. So please solve this rather simple issue. I do not think the way the code was done in the server and the way it was programmed was done in a non future proof way to not solve this months ago.

**Comment by slondr** [comment]
+1

**Comment by necros2k7** [comment]
As a note if server side is troublesome to implement - make client option to pin chats as you like - cause yes common sense is that it`s extremely comfortable to have at hand and see changes on persons/channels chats you like

**Comment by SevakAvet** [comment]
Guys, I understand there's a server-side limit, but as a compromise, why not to raise this limit client-side even though those chats won't be synched? As mentioned before in many comments, not everybody needs sync. I'd be totally fine with 5 synched chats and the rest just pinned in desktop app. Thanks!

**Comment by Dimensionsofahimsa** [comment]
It's impossible for me to use Telegram without more than 5 pinned chats

**Comment by necros2k7** [comment]
Tweak API for god`s sake

**Comment by luisalvarado** [comment]
Hi guys, just in case this issue is linked to issue #6697 but that one is linked to this one, so which one is the actual one?

**Comment by RememberTheAir** [comment]
@luisalvarado #6697 has been closed because as a duplicate of _this_ issue

**Comment by Neurotoxin001** [comment]
There is no API limit on pinned chats, other clients already have increased value of pinned chats. For example — Telegraph Messenger for android doesn't have pin chats limit.

**Comment by RememberTheAir** [comment]
@Neurotoxin001 there is a limit of chats you can pin, the API won't accept any request trying to pin the 6th chat on your list - and the max number of pinned chats is also passed to the clients when they ask for the server config. The clients you mentioned just ignore whatever limit the API wants you to respect, but obviously by doing that they cannot sync the chats the users pin if they want to pin more than 5
