### ISSUE TITLE
Desktop API

### ISSUE THREAD

**Issue by agentcooper** [telegramdesktop/tdesktop#3028]
Is there a suggested way to interact with the desktop client from other apps? Like getting information about the current chat.

I found that some stuff is accessible on Mac through AppleScript, made a small module https://github.com/agentcooper/osx-telegram. Is there a better way?

**Comment by john-preston** [comment]
@agentcooper There is no such API.

**Comment by auchri** [comment]
@agentcooper There are enough api libs to do that: https://github.com/sochix/TLSharp
