### ISSUE TITLE
Cache is not invalidated

### ISSUE THREAD

**Issue by hamid7p** [telegramdesktop/tdesktop#3029]
og:image and og:description is being cached or something doesn't it update.

**Comment by auchri** [comment]
Is it really that hard to use the template?

**Comment by hamid7p** [comment]
sure, I gave you all these info in one sentence to help you fix your bot, and your asking questions about things that bothering your mind's order. Now image how hard it is for me to read one page to understand your template so you can fix your bugs. No offense though just drawing parallel lines of imaginations :)

**Comment by auchri** [comment]
The template exists for a reason. I have no idea which bot are you talking about, which OS you are using or which version of Telegram Desktop you are using.

**Comment by nooncat** [comment]
After using https://telegram.me/webpagebot for cache invalidation, a new version of preview shows in android Telegram . But in the desktop Telegram still show the old version of preview.
It seems that desktop and mobile versions use different caches and WebPageBot not invalidating cache for desktop Telegram.

**Comment by Deusdictum** [comment]
Still not fixed?

**Comment by ericaprieto** [comment]
Any updates?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1049
