### ISSUE TITLE
[Feature Request] Show taskbar button when new message

### ISSUE THREAD

**Issue by kocane** [telegramdesktop/tdesktop#303]
Please, a function like all other IM's where a blinking button shows in the taskbar when theres a new message even if the window is closed. My tray icons are hidden :(...

**Comment by Kocayine** [comment]
Why was this closed?

**Comment by auchri** [comment]
Because it work's (at least in windows and you didn't specify a os)

**Comment by Kocayine** [comment]
The suggestion was to show the taskbar button - if closed - when theres a new message. Much like IM behavior from Skype, WLM etc. ATM it just shows it in the system tray area.

**Comment by auchri** [comment]
Oh you mean the icon in the taskbar

**Comment by Kocayine** [comment]
Thanks!

**Comment by Aokromes** [comment]
this is what you wanted no?
https://i.imgur.com/RgOdznW.png

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Comment by kocane** [comment]
@Aokromes well, some years did pass and I learned to live with the way Telegram works. What I wished for back then was for the Telegram window to open (minimized) when a new message arrived. Much like the old IM clients, WLM, Skype etc.

**Comment by Aokromes** [comment]
that's a the implemented thing is not what i wanted? :)
