### ISSUE TITLE
Replacement of Apple Emoji set with Twemoji

### ISSUE THREAD

**Issue by hadi77ir** [telegramdesktop/tdesktop#3033]
Twemoji is a free emoji set which is licensed under CC-4.0. Apple emoji set causes copyright issues.
Also, Twemoji is of flat design which is better for using in Material Design UI.

[https://github.com/twitter/twemoji](https://github.com/twitter/twemoji)

**Comment by Lazek** [comment]
Nooo, only Apple ;)

**Comment by auchri** [comment]
We want the same emoji on all platforms.
