### ISSUE TITLE
Fast leaking memory leak 

### ISSUE THREAD

**Issue by pschichtel** [telegramdesktop/tdesktop#3034]
### Steps to reproduce
1. Start Telegram
2. Receive message
3. Notice lags until the OOM-Killer terminates Telegram

I'm not entirely sure about the trigger of this behavior. Telegram runs normally for an arbitrary time without any problems or unusual memory consumtion, being used or not. Then suddenly the system starts lagging because telegram is consuming the entire free memory (13 out of 16G on my system depending on what else is running). I think it gets triggered upon receiving some message.

![telegram-memory-consumption](https://cloud.githubusercontent.com/assets/526104/23107584/de50c98c-f6ff-11e6-8044-5e8f57e299b7.png)

This has started with one of the release in the 1.0.x series, but I'm not sure which one.

### Expected behaviour
No massive memory consumtion

### Configuration
**Operating system:** Archlinux (Testing)

**Version of Telegram Desktop:** 1.0.6 (built from source)

### Logs
Will follow

**Comment by pschichtel** [comment]
[logs.tar.gz](https://github.com/telegramdesktop/tdesktop/files/786297/logs.tar.gz)

Could this be theming or IPv6 related?

**Comment by auchri** [comment]
> theming

Do you use a theme? If yes, which one?

**Comment by pschichtel** [comment]
I'm using the Adapta theme



Am 20. Februar 2017 10:21:54 schrieb Christoph <notifications@github.com>:

**Comment by pschichtel** [comment]
I think the Theme is unlikely to be the cause, because I'm using the same theme on another very similar system

**Comment by pschichtel** [comment]
Happened now without the custom theme

**Comment by auchri** [comment]
Did you sent/receive a gif recently?

**Comment by pschichtel** [comment]
No, haven't seen a gif in a while. The problem did not occur since I upgraded to 1.0.12, so I guess this is solved.

I'll reopen it if it happens again.

**Comment by pschichtel** [comment]
Ok, it just happened again today with 1.0.13

**Comment by pschichtel** [comment]
When starting telegram from the console I see this:

```
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=Datei oder Verzeichnis nicht gefunden)
attempt to connect to server failed
Type conversion already registered from type QSharedPointer<QNetworkSession> to type QObject*

(telegram-desktop:12413): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

Usually when this bug is triggered upon receiving a message, I'm not hearing the notification sound

**Comment by pschichtel** [comment]
Upon thinking about it: I think it always freezes somewhere between receiving a message and playing the notification sound. Sometimes I can see the message count indicator on the appindicator icon, sometimes I don't. However I never hear the notification sound when it freezes.

**Comment by john-preston** [comment]
@pschichtel Please check if it works perfectly fine without freezing for a huge amount of time with notifications and all if you _disable_ sound notifications (but leave the notifications themselves enabled). That way we could understand that the problem is in the working with sound somewhere.

**Comment by pschichtel** [comment]
I did already test with disabled notifications, that didn't help. I'll try without sound next. I'm currently running telegram with valgrind in the hope to find something useful.

**Comment by pschichtel** [comment]
I did not happen while running under valgrind which suggests it could be a timing problem

**Comment by pschichtel** [comment]
I tested without sound for 3 days without any problem. Yesterday evening I turned on the sound again and now it happened again.
So I guess its probably notification sound related

**Comment by pschichtel** [comment]
@john-preston anything new on this? The probably didn't occur since I disabled the sound again 12 days ago.

**Comment by fbt** [comment]
Oooh, are we on leaking memory? This is how Telegram behaves on all three of my linux PCs:

https://8fw.me/hell/0a193621d4fdb1d40b0f59d9aa93ef6c025e452d.png

Eventualy it will either hog the system down to an unusable state or the OOM Killer will take care of it.
It fills 32G up with about a week of uptime, maybe a bit more.

**Comment by fbt** [comment]
Nope, same with sound. It keeps eating more and more:
https://8fw.me/hell/b0da4f2526a097d28e7c2630cfa62a8c8e869b5a.png

**Comment by Slater91** [comment]
This bug is still present in the latest available version (1.0.29). I attach the log of the last session which caused my system to go full-swap and ultimately kill the Telegram process.
[log.txt](https://github.com/telegramdesktop/tdesktop/files/937511/log.txt)

**Comment by john-preston** [comment]
@Slater91 It did that in less than 1.5 hours? O_o Are you sure this is the log from the problematic launch?

**Comment by Slater91** [comment]
@john-preston No no, it's way less! I actually caught it ramping up to 2.9GB in less than 30 seconds - it happened at 22:16 (Italian time), so some 15 minutes ago. I quit using ctrl+Q, but the process was not killed and went on consuming memory - I had to abruptly kill it by hand.
I tried disabling audio notifications, as I suspect that's the problem. I will update you if the problem arises again with disabled audio.

BTW: using Linux Mint 18.1 with kernel 4.10.11, GCC 5.4.0.

**Comment by pschichtel** [comment]
@john-preston I just upgraded to Telegram 1.1 and tried the new Calls feature with a friend. he triggered this problem several times in a row on the second call.
This must be related to general Audio playback.

**Comment by pschichtel** [comment]
However playing back wav oder mp3 files never triggered this

**Comment by pschichtel** [comment]
So I'm pretty sure this is somehow related to my system configuration and I just saw a large amount of these log lines in my teamspeak client:

```19.05.17 21:24:09	PulseAudio	Debug	Underflow occurred on device ts3.pa.dummy.playbackdefault - 	```

I have the feeling this is related

**Comment by brainmorsel** [comment]
Have huge memory leak (~500MB per second) on notification sound playback. One error in console log:
`AL lib: (EE) ALCpulsePlayback_reset: Non-0 prebuf, 1324 samples (10592 bytes), device has 3305 samples`
Telegram Desktop version: 1.1.7
OpenAL version: 1.18.0

After downgrade of OpenAL to version 1.17.2 problem was resolved.

**Comment by lorien** [comment]
I have memory leak problem. My OS Debian Stretch, recent telegram desktop version. The telegram could easily consume 2 or 3Gb of memory.

**Comment by yeezy69** [comment]
Same here on Arch with Mate Desktop. I had this problem since many month. I'm using Telegram Desktop every day. But round about one time a week, Telegram sporadically freezes, eating all memory till OOM killer terminates the program. It could happens while receive a message. Desktop notifications and sound are enabled.

**Comment by TihonV** [comment]
I have memory leak (about 500~750Mb/sec) on notification.
Telegram Desktop: 1.1.23
OS: Fedora 27
Arch: x86_64
SRPM: http://download1.rpmfusion.org/free/fedora/development/rawhide/source/SRPMS/telegram-desktop-1.1.23-2.fc28.src.rpm

**Comment by pschichtel** [comment]
Do you have notification sounds enabled @TihonV? I'm pretty sure this is related to audio playback and possibly related to some newer library versions (maybe newer pulseaudio versions?).

**Comment by TihonV** [comment]
@pschichtel Yes. Notifications are enabled.

```
[Tihon@thinkpad-e560 ~]$ pulseaudio --version
pulseaudio 11.1-rebootstrapped
[Tihon@thinkpad-e560 ~]$ pulseaudio --dump-conf
daemonize = no
fail = yes
high-priority = yes
nice-level = -11
realtime-scheduling = yes
realtime-priority = 5
allow-module-loading = yes
allow-exit = yes
use-pid-file = yes
system-instance = no
local-server-type = user
cpu-limit = no
enable-shm = yes
flat-volumes = no
lock-memory = no
exit-idle-time = 20
scache-idle-time = 20
dl-search-path = /usr/lib64/pulse-11.1/modules
default-script-file = /etc/pulse/default.pa
load-default-script-file = yes
log-target = 
log-level = notice
resample-method = auto
avoid-resampling = yes
enable-remixing = yes
remixing-use-all-sink-channels = yes
enable-lfe-remixing = no
lfe-crossover-freq = 0
default-sample-format = s32le
default-sample-rate = 96000
alternate-sample-rate = 44100
default-sample-channels = 2
default-channel-map = front-left,front-right
default-fragments = 4
default-fragment-size-msec = 25
enable-deferred-volume = yes
deferred-volume-safety-margin-usec = 8000
deferred-volume-extra-delay-usec = 0
shm-size-bytes = 0
log-meta = no
log-time = no
log-backtrace = 0
rlimit-fsize = -1
rlimit-data = -1
rlimit-stack = -1
rlimit-core = -1
rlimit-rss = -1
rlimit-as = -1
rlimit-nproc = -1
rlimit-nofile = 256
rlimit-memlock = -1
rlimit-locks = -1
rlimit-sigpending = -1
rlimit-msgqueue = -1
rlimit-nice = 31
rlimit-rtprio = 9
rlimit-rttime = 200000

```

**Comment by vlig** [comment]
Same for me with Arch Linux. Moreover, oom DOES NOT killing Telegram when YouTube plays in fullscreen mode.
I was slept for a while, so noticed this issue.

**Comment by Slater91** [comment]
After I disabled audio notifications, I got no more issues. This seems like the conclusive word on the matter - there's a problem in either Telegram or PulseAudio (though I suspect the former) when notification sounds play.

**Comment by feuerrot** [comment]
I still have issues using version 1.2.6 and my audio notifications are disabled. Usually after a few days of runtime, tgdesktop gets killed by the oomkiller like a few minutes ago:
> [527616.874106] Out of memory: Kill process 22697 (Telegram) score 391 or sacrifice child
> [527616.874136] Killed process 22697 (Telegram) total-vm:8832920kB, anon-rss:6373292kB, file-rss:0kB, shmem-rss:616kB

If I use valgrind it ends in:

> ==6304== More than 1000 different errors detected.  I'm not reporting any more.
> ==6304== Final error counts will be inaccurate.  Go fix your program!
> ==6304== Rerun with --error-limit=no to disable this cutoff.  Note
> ==6304== that errors may occur in your program without prior warning from
> ==6304== Valgrind, because errors are no longer being displayed.
> ==6304== 
> ==6304== Warning: client syscall shmdt tried to modify addresses 0xffffffffffffffff-0xffffffffffffffff
> ==6304== Warning: client syscall shmdt tried to modify addresses 0xffffffffffffffff-0xffffffffffffffff
> ==6304== 
> ==6304== HEAP SUMMARY:
> ==6304==     in use at exit: 476,349 bytes in 5,916 blocks
> ==6304==   total heap usage: 441,701 allocs, 435,785 frees, 257,859,446 bytes allocated
> ==6304== 
> ==6304== LEAK SUMMARY:
> ==6304==    definitely lost: 11,112 bytes in 88 blocks
> ==6304==    indirectly lost: 18,505 bytes in 379 blocks
> ==6304==      possibly lost: 8,565 bytes in 61 blocks
> ==6304==    still reachable: 436,655 bytes in 5,373 blocks
> ==6304==                       of which reachable via heuristic:
> ==6304==                         length64           : 40 bytes in 1 blocks
> ==6304==                         newarray           : 1,552 bytes in 17 blocks
> ==6304==         suppressed: 0 bytes in 0 blocks
> ==6304== Rerun with --leak-check=full to see details of leaked memory
> ==6304== 
> ==6304== For counts of detected and suppressed errors, rerun with: -v
> ==6304== Use --track-origins=yes to see where uninitialised values come from
> ==6304== ERROR SUMMARY: 312117 errors from 1000 contexts (suppressed: 0 from 0)
> valgrind bin/Telegram/Telegram  30,92s user 0,28s system 91% cpu 34,070 total

debian testing, kernel 4.13.0, binary from telegram.org

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2464
