### ISSUE TITLE
Outside of Bubble

### ISSUE THREAD

**Issue by hdd064** [telegramdesktop/tdesktop#3035]
I received a message in Farsi that was not aligned.

**The message:**
سفر ارزان🌏سراسر جهان
🎯👈بهترین نرخ تورها را در کانال تور مسافرتی بیابید👇👇
✅کیش 🇮🇷 ۴۹۰ تومان  
✅مشهد 🇮🇷  ۳۲۰ تومان 
✅استانبول🇹🇷 ۸۵۰ تومان        
✅تفلیس 🇬🇪 ۶۹۹تومان
✅دبی🇦🇪  ۱،۲۹۹ تومان 
✅گوا 🇮🇳۱،۸۹۰تومان
🌹🌸🌺تورهای نوروزی👇👇
✅قشم زمینی🇮🇷 ۵۵۰ تومان  
✅مشهد🇮🇷 ۷۵۰تومان  
✅استانبول🇹🇷 ۱،۴۵۰تومان          
✅ سوچی🇷🇺  ۳،۴۹۰تومان 
🌎تورهای لوکس جزیره موریس، آفریقای جنوبی، مالدیو، مراکش، ویتنام، تونس،کرالا و...🌼
🔴 و دهها مسیر دیگر🔵 
✳️✳️عضو کانال ما شوید✳️✳️

### Actual behaviour
![capture](https://cloud.githubusercontent.com/assets/1020603/23117317/63accc0c-f764-11e6-8f1d-b9e05a083836.PNG)

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.0.12

**Comment by auchri** [comment]
![image](https://cloud.githubusercontent.com/assets/5092164/23118867/14c48b56-f756-11e6-9b66-acd7730e2269.png)

Works for me ™

**Comment by hdd064** [comment]
I've copied the text from GitHub, was no problem. But when I forward the message, there is still the problem.

**Comment by notmika** [comment]
Works perfectly fine even when forwarding.

**Comment by hdd064** [comment]
I'm using the latest stable version (1.0.14) and i still see some messages with this problem.

**Comment by john-preston** [comment]
@hdd064 please try the latest alpha from here: https://desktop.telegram.org/changelog#alpha-version

**Comment by hdd064** [comment]
Yes, the problem is resolved.
