### ISSUE TITLE
RTL fix

### ISSUE THREAD

**Issue by smaznet** [telegramdesktop/tdesktop#3036]
### Expected behaviour
my message should by at right side of windows

### Actual behaviour
but message is on left side

### Configuration
**Operating system: UBUNTU 16.04**

**Version of Telegram Desktop:1.0.12**

![screenshot from 2017-02-20 13-42-40](https://cloud.githubusercontent.com/assets/10239885/23120773/f4c2edee-f772-11e6-93e4-440cb6a09ea7.png)

**Comment by auchri** [comment]
There is a setting for that in the settings

**Comment by smaznet** [comment]
@auchri where is settings?

**Comment by auchri** [comment]
![image](https://cloud.githubusercontent.com/assets/5092164/23214823/6dcd1180-f910-11e6-883c-76e847b03d2e.png)
