### ISSUE TITLE
Impossible to close the window with ALT + F4

### ISSUE THREAD

**Issue by EmptyStackExn** [telegramdesktop/tdesktop#3037]
### Steps to reproduce
1. Open Telegram
2. Close the window with ALT + F4

### Expected behaviour
Closes the window and keeps running underground.

### Actual behaviour
Reopens the window immediately. As a remark, clicking on the "X" button on the upper-right side closes the window correctly.

### Configuration
**Operating system:**
Ubuntu 16.04 with GNOME Classic (Session Flashback)

**Version of Telegram Desktop:**
1.0.12
### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by john-preston** [comment]
@EmptyStackExn Did it work before?

**Comment by EmptyStackExn** [comment]
@john-preston Yes it did. It started to fail since this new version release.

**Comment by john-preston** [comment]
@EmptyStackExn This will be fixed in the 1.0.13.

**Comment by EmptyStackExn** [comment]
@john-preston Thanks 👍
