### ISSUE TITLE
Right clicking the tray icon is needed twice to open the short menu

### ISSUE THREAD

**Issue by liquidplace** [telegramdesktop/tdesktop#3039]
### Steps to reproduce
1. Minimize tDesktop to tray
2. Right click the tray icon (notification area icon)
3. No short menu, tdesktop restores as if icon was left-clicked. 👎 
4. Right click tray icon **again** while tdesktop is visible, short menu now appears. 👍 

### Expected behaviour
Right clicking the tray icon should show the short menu, regardless of tdesktop's window state.

### Actual behaviour
Right clicking the tray icon (first time), restores the minimized tdesktop window. 

### Configuration
**Operating system:**
Windows10 x64 

**Version of Telegram Desktop:**
1.0.12 / no themes / glitch appeared after the latest update

**Comment by auchri** [comment]
Try to update to 1.0.13

**Comment by liquidplace** [comment]
Oh boy you **are** fast 😆 

I wasn't aware you've built an update. You're right 1.0.13 fixed it, it works like a charm! Thank you and for tdesktop in general, good job! 🥇
