### ISSUE TITLE
Window state is lost when the window is closed

### ISSUE THREAD

**Issue by matiaskorhonen** [telegramdesktop/tdesktop#3040]
### Steps to reproduce

1. Select a chat in Telegram Desktop
2. Close the window (Cmd + W on macOS)
3. Re-open the app

### Expected behaviour

The window state should be restored as it was before the window was closed.

This is how native apps work on macOS (for example, see the Messages app).

### Actual behaviour

The window state is reset.

### Configuration

**Operating system:** macOS Sierra 10.12.3

**Version of Telegram Desktop:** 1.0.12

**Used theme**: default

**Comment by auchri** [comment]
See #2541
