### ISSUE TITLE
The window doesn't close on Alt+F4 on Ubuntu

### ISSUE THREAD

**Issue by Roman-** [telegramdesktop/tdesktop#3041]
### Steps to reproduce
1. Open the window
2. Press Alt+F4

### Expected behaviour
The window closes (hides to the tray) like it does on pressing Ctrl+W or clicking the cross GUI button on the upper-left corner of the window.

### Actual behaviour
The window looses its focus for a moment and doesn't close (or, maybe, it re-opens). It sometimes requires several Alt+F4 hits to close. When non-fullscreen, the window also moves a bit upwards on the screen after Alt+F4.

### Configuration
**Operating system:**
Ubuntu 16.04 LTS

**Version of Telegram Desktop:**
1.0.12

**Comment by john-preston** [comment]
@Roman- Please try 1.0.13
