### ISSUE TITLE
[Feature Request] Add IDN Support

### ISSUE THREAD

**Issue by amiremami** [telegramdesktop/tdesktop#3043]
For example when I share this link, it shows look like this:
https://www.ajibtarin.com/misc/11171/%D9%85%D8%B1%DA%AF-%D8%B9%D8%AC%DB%8C%D8%A8-%D8%A8%D8%A7%D9%88%D8%B1%D9%86%DA%A9%D8%B1%D8%AF%D9%86%DB%8C/

Please add IDN support to shows the actual slug for links.

Thanks

**Comment by auchri** [comment]
#2832 
Use the template next time.

**Comment by notmika** [comment]
@auchri This is in no way related to my issue AFAIK.

**Comment by auchri** [comment]
Yes, but it's not an issue of telegram desktop, since it also don't work on android

@amiremami Should contact [Telegram on Twitter](https://twitter.com/telegram)

**Comment by amiremami** [comment]
Ah right, thank you guys 😄  And sorry for not using template 👍
