### ISSUE TITLE
Feature Request: Support default macOS shortcuts in input box

### ISSUE THREAD

**Issue by iredmail** [telegramdesktop/tdesktop#3044]
macOS has some default shortcuts for text editing, it's like Emacs:

* `ctrl-a`: move cursor to the beginning of line
* `ctrl-e`: move cursor to the end of line
* `ctrl-b`: move cursor backward for one character
* `ctrl-f`: move cursor forward for one character

It's faster to use these shortcuts to move cursor instead of the arrow keys.

**Comment by auchri** [comment]
#729 

And use the template next time.
