### ISSUE TITLE
Do not display floating date when scrolling down

### ISSUE THREAD

**Issue by behrang** [telegramdesktop/tdesktop#3046]
When scrolling down to read messages, displaying floating date prevents easy and fast reading of messages. Since that floating date is for helping user to find the date of a message, showing it only when scrolling up is great but it is better to be hidden when scrolling down.

**Comment by auchri** [comment]
And how should someone figure out the date when he is scrolling down?

**Comment by behrang** [comment]
No need for figuring out the date. First, it is mostly today. Second, user can start scrolling a little up and see the date.

**Comment by auchri** [comment]
If you search a message an then scroll down then you aren't able to figure out the date without scrolling back up, which is very inconvenient.

**Comment by behrang** [comment]
Since dates are displayed above messages, users natural action to find date
is scrolling up. In that case, user will immediately see the date.

I don,t mean to scroll up a lot. Just 1 pixel is enough. I mean while
reading messages and scrolling down, date is really annoying.
