### ISSUE TITLE
[KDE] Update broke -startintray

### ISSUE THREAD

**Issue by lucidfox** [telegramdesktop/tdesktop#3047]
The recent update (1.0.12) broke the `-startintray` option for me. 

### Steps to reproduce
1. Run the Telegram executable from the command line with the `-startintray` argument.

### Expected behavior
Telegram should start minimized, as it did before the update.

### Actual behavior
Telegram starts with its window open.

### Configuration
**Operating system:** Kubuntu 16.10, KDE Plasma 5.7.5

**Version of Telegram Desktop:** 1.0.12

**Used theme**: Default

**Comment by auchri** [comment]
Try update to 1.0.14

**Comment by lucidfox** [comment]
Updating to 1.0.14 solved the problem. Thanks!
