### ISSUE TITLE
Emoji/Character picker doesn't open

### ISSUE THREAD

**Issue by matiaskorhonen** [telegramdesktop/tdesktop#3048]
### Steps to reproduce

1. Open a chat and focus the cursor on the message text box
2. Type: control + command + space

### Expected behaviour

The [macOS emoji picker](http://www.imore.com/how-to-use-emoji-on-your-mac) or Character Palette should open (depending on your system configuration etc).

### Actual behaviour

Nothing happens. Something in the Telegram app is overriding the system behaviour.

### Configuration

**Operating system:** macOS Sierra 10.12.3

**Version of Telegram Desktop:** 1.0.12

**Used theme**: default

**Comment by auchri** [comment]
Duplicate #2886
