### ISSUE TITLE
Share theme syntax and values with android version

### ISSUE THREAD

**Issue by gudvinr** [telegramdesktop/tdesktop#3051]
### Expected behaviour
1. Since we have themes in android apps too it's very nice to have consistency of theme syntax and name of attributes across all apps.
2. There's no api but it also good to have one to sync theme settings.

### Actual behaviour
Syntax of `tdesktop-theme` files and `attheme` is different. Also parameters also named differently but most of them can be the same.

This is not only tdesktop issue but you can discuss it with developers of rest of apps though.

**Comment by john-preston** [comment]
@gudvinr This is not planned, sorry.
