### ISSUE TITLE
Application doesn't support input alternate characters by tap&hold method on Mac

### ISSUE THREAD

**Issue by Shiaulis** [telegramdesktop/tdesktop#3054]
### Steps to reproduce
1. Open the application
2. Open any chat
3. Try to tap&hold to call extended characters popover

### Expected behavior

See the attached screenshot.
<img width="232" alt="osx_tipyn_alternate_characters" src="https://cloud.githubusercontent.com/assets/13601748/23186570/5402c22a-f890-11e6-816e-043124a4ffc9.png">
Additional information on Apple site
https://support.apple.com/en-us/HT201586

### Configuration
**Operating system:**
MacOS 10.12.4
**Version of Telegram Desktop:**
1.0.5
**Used theme**:

<details><summary>**Information on Apple site**:</summary>
https://support.apple.com/en-us/HT201586

</details>

**Comment by auchri** [comment]
Basically the same as #729
