### ISSUE TITLE
Disable new messages counter from muted groups in WORKMODE

### ISSUE THREAD

**Issue by puzanov** [telegramdesktop/tdesktop#3055]
### Steps to reproduce
1. Enter workmode
2. Hide muted chats
3. See the unread messages counter in muted chats. 

<img width="812" alt="1__puzanov_windows_____zsh_" src="https://cloud.githubusercontent.com/assets/91070/23209131/1a8aeef4-f922-11e6-8d92-3fed6552143b.png">

### Expected behaviour
Do not show unread messages counter near the "Show all chats" item in workmode.  This is annoying. We are in a workmode, we do not want to see any unread counter here. 

### Actual behaviour
In workmode we see unread counter near the "Show all chats" item and want to click it.  This feature is useless and does not help us be more productive. 

### Configuration
**Operating system:macOS 10.12.2**

**Version of Telegram Desktop: 1.0.14**

**Used theme some dark stuff, dunno where I can find it name **:

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@puzanov Sorry, this was implemented as it was intended.

**Comment by puzanov** [comment]
@john-preston OK, can you add checkbox in settings to disable this counter? This will really help not to distract while working. I find myself always looking at this counter and how it increasing.

**Comment by puzanov** [comment]
Please?

**Comment by sharifzadesina** [comment]
@auchri Why "wontfix"? this is really annoying!!!

**Comment by intr13** [comment]
I fixed it!
![photo_2017-10-17_12-38-28](https://user-images.githubusercontent.com/649282/31657878-3d81ecb6-b338-11e7-8230-ea5557b50a6c.jpg)

**Comment by Croydon** [comment]
A sub-option of "Count unread messages" named "Also count unread messages in muted chats" would be awesome.

It is literally stressing me out to see these numbers constantly. 🙈
