### ISSUE TITLE
Possibility to delete message at a friends chat when forgotten to check checkbox

### ISSUE THREAD

**Issue by CodingSpiderFox** [telegramdesktop/tdesktop#3056]
### Steps to reproduce
1.  Send a message to a friend (regular one-to-one chat)
2.  Right click that the message in your chat window and choose "Delete message"
3.  Be in a hurry and forget to check the checkbox "Delete message at friend <name>" but you actually wanted to remove the message from him (in this case, accidentally sent wrong sticker)
4. I'm no more able to delete the message from him

### Expected behaviour
Two possibilities I think

A:
Show a "undo" box for a short period of time (like 10, maybe 15 seconds, maybe configureable globally for your app) which enables to "restore" the message (actually message should be deleted only after the time period I guess). That way I could have another try

B: 
Add possibility to configure to always remove a message from every fried when you remove it from your own chat.
### Actual behaviour
I am not able to delete the message from my friends chat

### Configuration
Windows 10 Pro x64

1.0.14

Default theme

Best regards

**Comment by john-preston** [comment]
@CodingSpiderFox Currently there is no way to do that without changing the server side API other way than just delay the real query for deleting the message for some time and making the interface more complex, I don't think that is a good idea.

**Comment by CodingSpiderFox** [comment]
What about the option to make it configureable globally within the application? 

Would it make the interface too complex, too?

**Comment by MWFIAE** [comment]
How about leaving an entry in the own chat for the deleted Message? 

Something which only states"[deleted]" so that one could:
1. remove the [deleted] message itself, so nothing is displayed or 
2. delete the message for the other partie too. 

Make it configurable so that one could disable it, if the "soft-delete" is not what you want.

**Comment by stek29** [comment]
@john-preston Btw, can't you ask someone why messages.restoreMessages was removed?

**Comment by CodingSpiderFox** [comment]
They removed such functionality from the server side API?

**Comment by stek29** [comment]
@CodingSpiderFox looks like they did, but tbh I never tested that functionality.

**Comment by MCSH** [comment]
@MWFIAE The API doesn't allow a removed message to be removed again, this time also for the peer. 

I also like the idea of having a global setting to have the checkbox on or off by default.
