### ISSUE TITLE
Telegram portable always adds shortcut to Start Menu

### ISSUE THREAD

**Issue by PekaFat** [telegramdesktop/tdesktop#3057]
### Steps to reproduce
1. Run Telegram **portable** on Windows 10 Enterprise 64bit
2. Close telegram and Open Start Menu
3. You will see telegram shortcut
4. Delete it and run telegram again
5. Open start menu and you will see telegram shortcut again

### Expected behaviour
Telegram adds shortcut to start menu, even after deleting this shortcut

### Configuration
**Operating system:** Windows 10 Enterprise 64bit

**Version of Telegram Desktop:** 1.0.14

**Used theme**: Default

![image](https://cloud.githubusercontent.com/assets/13280748/23228828/66672e48-f957-11e6-872a-ea6c65ee6232.png)

**Comment by Aokromes** [comment]
#2066

**Comment by PekaFat** [comment]
> 22 May 2016

And still no fix? Oh god.
