### ISSUE TITLE
Very poor MP3 quality in built-in player

### ISSUE THREAD

**Issue by makkarpov** [telegramdesktop/tdesktop#3058]
### Steps to reproduce

1. Send any MP3 as file
2. Play it with built-in player
3. Navigate to downloads directory and play it with third-party player

### Expected behaviour

Both (2) and (3) should produce good quality audio output

### Actual behaviour

(3) works fine, yes, because it is not related to Telegram :D 
Sound produced by built-in player will permanently hurt your ears, as if it was 64 kbit/s MP3.

### Configuration

OS: Fedora 25 64-bit, `Linux hostname 4.8.6-300.fc25.x86_64 #1 SMP Tue Nov 1 12:36:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
Telegram desktop: 1.0.14

**Comment by jfsawin** [comment]
I've noticed (very) degraded mp3 playback quality for the past couple months as well (using the Windows version of the client). I'd really like to see this investigated, because it used to be perfect at one point. I'm not sure what changed.

**Comment by john-preston** [comment]
@jfsawin It would help if you find the exact version when it changed. You can find portable binaries for all versions here: https://github.com/telegramdesktop/tdesktop/releases

**Comment by jfsawin** [comment]
@john-preston After some testing, v 0.10.26 is the version that introduces the degraded mp3 playback. The audio player in v 0.10.25 (and before) reproduces mp3 files perfectly.

**Comment by john-preston** [comment]
@jfsawin That's when I've updated the OpenAL version to the latest :( It had 539 commits in there, so it will require to test about 10 versions to find out which one exactly broke the playback :(

**Comment by jfsawin** [comment]
@john-preston Sorry to hear... Hopefully you can get it figured out soon. Was there any reason in particular for updating OpenAL? Would rolling back to the previous OpenAL version be feasible?

**Comment by AsakuraFuuko** [comment]
Same here

**Comment by jfsawin** [comment]
@john-preston Any status on this? The issue still persists in 1.1.7 alpha.

**Comment by Rarzarol** [comment]
As of 1.1.23, this is still an issue. I liked using Telegram for collaborating on music projects before this was an issue, for now, I have to look for alternatives, which is a bummer.

**Comment by Ryan8781** [comment]
I have also noticed that the audio quality in the built-in player is poor for all formats, not just MP3. I have tested MP3, OGG Vorbis and Opus.

**Comment by RevenantX** [comment]
bug still exits in 1.2.1
