### ISSUE TITLE
Dead keys not workig

### ISSUE THREAD

**Issue by ectatomma** [telegramdesktop/tdesktop#3059]
### Steps to reproduce
1. Set the keyboard layout to English International with dead keys
2. Try to write characters using any accent mark (like á é í ó ú ñ)
3. All letters appear without accent marks (like a e i o u n)

### Expected behaviour
Characters with all the accent marks when using dead keys (like á é í ó ú ñ).
 
### Actual behaviour
No accent marks are reproduced by the text box when using dead keys, just plain letters

### Configuration
**Operating system:**
Ubuntu 16.04
**Version of Telegram Desktop:**
1.05
**Used theme**:
Default theme
<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
Duplicate #1041
