### ISSUE TITLE
[Linux] Stop creating ".desktop" file automatically!

### ISSUE THREAD

**Issue by fauzie811** [telegramdesktop/tdesktop#306]
Because I already made a custom ".desktop" file that uses an icon from my current icon theme. But when I launch the app, it just replace the file with the one that uses the default icon from the app. That's annoyying.

Could you just give the user an option?

**Comment by AndydeCleyre** [comment]
@fauzie811 and @sergioad,

Until this crazy system is fixed, if you have the permissions, you can work around the problem with:

```bash
sudo chattr +i telegramdesktop.desktop
````
which will make the file immutable, and immune to telegram updates.

**Comment by sergioad** [comment]
Ok :smile:

**Comment by ItachiSan** [comment]
What about creating a flag that prevents the .desktop file creation?
So, system packagers just can build the package with this flag and add a system-wide .desktop file.

**Comment by AndydeCleyre** [comment]
What's the rationale for generating this during runtime, anyway?

**Comment by john-preston** [comment]
@AndydeCleyre Currently there is no other place to generate it — you unpack and launch the app.

**Comment by AndydeCleyre** [comment]
Even if the decision is to build a `.desktop` generator into the app itself, on Linux desktops, it's not the role of a program to place files like that on the user's system in the proper place. That's what build systems and package managers do.

**Comment by john-preston** [comment]
@AndydeCleyre I'd love not to, but this was the only way to register the app as a custom url scheme handler for making the telegram.me links working, if I remember that correctly.

**Comment by AndydeCleyre** [comment]
I'm looking at the custom uri registration code. It seems to be registering via 3 avenues:

- gconf
- kde service protocol
- xdg mime

Those first two do not appear to depend on the `.desktop` file at all.

I *think* that calling the xdg mime association explicitly is unnecessary if, when the user *does* have a `.desktop` file in the right place (thanks to their package manager, ideally), that file includes "MimeType=x-scheme-handler/tg;" -- which the static (non-generated) file available at `lib/xdg/telegramdesktop.desktop` already includes.

I'm building a version with the desktop file creation and that xdg mime command stripped out, and I'll see if it works as expected.

Also, if the user has multiple telegram clients installed, it wouldn't seem right to snatch back the default association on each install.

**Comment by AndydeCleyre** [comment]
So it seems to work fine. Before installing (and with no other Telegram client installed):

```bash
$ xdg-mime query default x-scheme-handler/tg
$ echo "$?"
4
```

And after installation (via the [PKGBUILD](https://aur.archlinux.org/packages/telegram-desktop/), modified to use my sources):

```bash
$ xdg-mime query default x-scheme-handler/tg
telegramdesktop.desktop
$ echo "$?"
0
```

Clicking links such as [this addsticker one](tg://addstickers?set=EmojiOneAgain) works as it should.

I'm going to submit a pull request here. It would mean that any packagers who were relying on a generated `.desktop` file should be mindful of the change, and either place the one that's in `lib/xdg/` in the proper spot or provide their own.

**Comment by louwers** [comment]
This is very annoying, especially because the created `.desktop` file doesn't even work:
[](http://imgur.com/HxzTwvTl.png)

**Comment by AndydeCleyre** [comment]
Just confirming that the app-generated launcher is broken on Arch Linux. The binary package even includes special instructions on the extra steps this requires of the user, after each install:

```bash
post_install() {
        echo "Remember to delete the official (non-tweaked) launcher by using:"
        echo "rm ~/.local/share/applications/telegramdesktop.desktop"
        echo "After running Telegram Desktop"
}
```
