### ISSUE TITLE
telegram crashes on Ubuntu Unity 8 session

### ISSUE THREAD

**Issue by pixelr0** [telegramdesktop/tdesktop#3060]
### Steps to reproduce
1. unity8 session is already preinstalled on ubuntu 16.10 or 17.04 , you need to choice from the login screen the unity8 session (default session is unity7). you can also use 16.04 + overlay PPA and then add unity8 desktop session
2.  to run Telegram, open the terminal and use ubuntu-app-test to launch the app
"~/Downloads/Telegram$ ubuntu-app-test ./Telegram"

### Expected behaviour
Telegram shoud run, Qt5+ has a mir backbend and most Qt5 apps do run native on Unity8/Mir

### Actual behaviour
Telegram doesn't start

ubuntu-app-test ./Telegram 
This application failed to start because it could not find or load the Qt platform plugin "ubuntumirclient"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
./Telegram(_ZN14SignalHandlers8internal7HandlerEiP7siginfoPv+0x177)[0xa4d757]
./Telegram(_ZN14SignalHandlers8internal12DumpCallbackERKN15google_breakpad18MinidumpDescriptorEPvb+0x2e)[0xa4dffe]
./Telegram(_ZN15google_breakpad16ExceptionHandler12GenerateDumpEPNS0_12CrashContextE+0x3d4)[0xead4d4]
./Telegram(_ZN15google_breakpad16ExceptionHandler13SignalHandlerEiP7siginfoPv+0x97)[0xead7e7]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11620)[0x7f83eb3e4620]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x9f)[0x7f83eab217ef]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f83eab233ea]                    
./Telegram[0x1b26d1e]                                                           
./Telegram[0x1753d3c]                                                           
./Telegram[0x1753d95]                                                                                                                         
./Telegram[0x1ce0fae]                                                                                                                         
./Telegram[0x1754b9c]                                                                                                                         
./Telegram[0x14194c9]                                                                                                                         
./Telegram(_ZN11ApplicationC2ERiPPc+0x1e)[0x8e2eae]                                                                                           
./Telegram(main+0x93)[0x7bd083]                                                                                                               
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f83eab0c3f1]                                                                       
./Telegram[0x81f0bd]    

### Configuration
**Operating system:**
Ubuntu 17.04 Unity8 but it's the same on 16.10 and 16.04 + overlay PPA

**Version of Telegram Desktop:**
1.0.14

**Used theme**:
default

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by Lazek** [comment]
May be duplicate?

https://github.com/telegramdesktop/tdesktop/issues/3053

**Comment by john-preston** [comment]
@pixelr0 unfortunately Unity 8 doesn't work in Parallels Desktop so I can't even try it out for now :(

**Comment by mikhailnov** [comment]
Telegram builds are using a self-built Qt5 with their own patches, probably there is no mor output backend in this Qt.

Xcb is a backend for X server, so TG client should run as an X app, or it should be rebuilt using Qt with mir support.
