### ISSUE TITLE
Search field focused instead of last conversation

### ISSUE THREAD

**Issue by bladeSk** [telegramdesktop/tdesktop#3069]
The search field is focused instead of the last active chat when Telegram is being restored from the tray icon.

0.9.x opened the last/relevant conversation.

This might be a "feature", but it hurts usability a lot. Imagine every time you opened the app on your cell phone, it would exit to the list of conversations instead of being in the last active conversation.

It would be great if you could either revert to previous behavior or have a setting for going back to the original behavior.

### Configuration
**Operating system:** Windows 8.1 x64

**Version of Telegram Desktop:** 1.0.14

**Used theme**: default

**Comment by auchri** [comment]
Please don't create a new, duplicateso issue.

**Comment by bladeSk** [comment]
Sorry, I only searched open issues. I had no idea you had closed all similar issues as invalid. I'll just add this to the long list of requests for reverting this #2541 

I know you probably don't care, but I'm starting to look for an alternative IM just because of this incredibly annoying "feature". Telegram had the best UI of all the clients by far and this completely ruined it for me.

**Comment by auchri** [comment]
@bladeSk > I know you probably don't care, but I'm starting to look for an alternative IM

Maybe you wanna try another client instead? e.g. https://github.com/UnigramDev/Unigram

**Comment by bladeSk** [comment]
While I appreciate the recommendation, UWP is supported only on Windows 10 and besides, the official client looks way more mature and was perfectly fine until this happened. It was, in fact, so solid, that I used to recommended Telegram purely on the grounds of having the best interface.
