### ISSUE TITLE
[Enhancement] "Replace emoji" should replace emoji without hyphen dashes :)

### ISSUE THREAD

**Issue by ADTC** [telegramdesktop/tdesktop#307]
I don't add the hyphen to the smiley text `:)` to make it `:-)`. Telegram Desktop currently only replaces the second one, but I would like it to replace the first one too.

I would love to make this change myself but I might break something not knowing anything more than basics of C++ and not knowing even the basics of Objective-C++. But I did some searches, and looks like you only need to copy-paste-reindent a bunch of lines here:

**Add support:**
* [For `B)`](https://github.com/telegramdesktop/tdesktop/blob/7a600e03d0549cdc3f034a6ae86ac6929523d104/Telegram/SourceFiles/gui/emoji_config.cpp#L4364)
* [For `;P`, `;)`](https://github.com/telegramdesktop/tdesktop/blob/7a600e03d0549cdc3f034a6ae86ac6929523d104/Telegram/SourceFiles/gui/emoji_config.cpp#L4417)
* [For `:p`, `:P`, `:D`, `:*`, `:)`, `:(`](https://github.com/telegramdesktop/tdesktop/blob/7a600e03d0549cdc3f034a6ae86ac6929523d104/Telegram/SourceFiles/gui/emoji_config.cpp#L4575)
* [For `8)`](https://github.com/telegramdesktop/tdesktop/blob/7a600e03d0549cdc3f034a6ae86ac6929523d104/Telegram/SourceFiles/gui/emoji_config.cpp#L4654)
* [For `3)`, `3-(`](https://github.com/telegramdesktop/tdesktop/blob/7a600e03d0549cdc3f034a6ae86ac6929523d104/Telegram/SourceFiles/gui/emoji_config.cpp#L4669)

**Related issue:** #116 

***Sidenote:*** *The [findEmoji method](https://github.com/telegramdesktop/tdesktop/blob/7a600e03d0549cdc3f034a6ae86ac6929523d104/Telegram/SourceFiles/gui/emoji_config.cpp#L4319) looks like a maintenance nightmare... isn't there a better way, like some sort of a hash map with key-value pairs?*

**Comment by joshery420** [comment]
:+1: because almost every other chat program I've used that does this doesn't require the hyphen nose.

Also, I totally agree that a hash/dictionary of some kind would probably be a much better way to implement this.

Sidenote: The ability to choose whether we see the iOS or Android emoji set would be awesome, but I'm sure that's extremely low priority. :wink:

**Comment by ADTC** [comment]
Yeah the current implementation is a dirty hack, but to change it to a hash/dictionary there must be some way to deal with keys of variable lengths.

About your sidenote, this project is for the desktop app. I don't think I would want to see a particular brand of mobile emoji :smile:

**Comment by joshery420** [comment]
@ADTC Oh I know this is the desktop app haha.
Am I crazy, or are the default emoji used in Telegram right now (including the desktop app) the same as the ones iOS uses?
That's the only reason I mentioned it.
That said, desktop app or not, I still don't see anything wrong with having a toggle in the settings to choose which you prefer. :smile:

**Comment by ADTC** [comment]
I don't know man, but to me it looks like the **exact** set of emoji used in WhatsApp. I'm not sure if the set of emoji that WhatsApp uses on its Android client is actually borrowed from iOS... *is it?*

Telegram Desktop:
![Telegram Desktop Emots](https://cloud.githubusercontent.com/assets/6047296/6416415/00b7c04c-bee1-11e4-8a05-e0a94127365d.png)

WhatsApp Android:
![WhatsApp Android Emots](https://cloud.githubusercontent.com/assets/6047296/6416418/05529fb4-bee1-11e4-8f94-87802541cc61.png)

**Comment by joshery420** [comment]
http://emojipedia.org/apple-emoji-list/

Certainly looks like it!
So it looks like use of that emoji set is just decently widespread, that's all.
I'd still love support for the Android emoji at some point, but like I said, low priority.

**Comment by ADTC** [comment]
I had no clue that WhatsApp Android is using Apple emoji. I thought it's WhatsApp's own (since I never saw them anywhere else before). I love them and how they look. To be honest, I don't like Android emoji.. they look crap (unless you can show me pics of them looking awesome) :smile:

**Comment by joshery420** [comment]
Yea haha.
Lucky for you I wan't asking for mandatory Android emoji. ;)
You can keep your damned iOS/WhatsApp emoji as long as you'd like even they fulfilled my wish! :wink:

**Comment by joshery420** [comment]
Also, just fyi there's a pull request that (partially?) handles nose-less smilies.
Linked to it above.

**Comment by ADTC** [comment]
Wait, if we have that 2D array map "replaces[]" in `Telegram/SourceFiles/_other/genemoji.cpp`, why do we still have the mess that is "findEmoji" in `Telegram/SourceFiles/gui/emoji_config.cpp`? Which one is actually used?

**Comment by ADTC** [comment]
So after studying the code, I now understand that `Telegram/SourceFiles/gui/emoji_config.cpp` is actually an **automatically generated** source file, and `Telegram/SourceFiles/_other/genemoji.cpp` is the C++ program that generates this.

So we don't need to modify **`findEmoji`**, we only need to add the new mappings to **`replaces[]`** (as bjaskj did) and re-generate the `emoji_config.cpp` source file. Is that right?

Also I noticed that there's another **`replaces[]`** 2D array in `Telegram/SourceFiles/boxes/emojibox.cpp`. I think this is related to the *"List of supported emojis"* box shown in *Settings* (when *View list* is clicked). We should make sure this list is complete.

**Comment by SharpMelon** [comment]
I'd like to add to the discussion by suggesting that we not only add new mappings but the ability to and and remove new mappings.

**Comment by ADTC** [comment]
@SharpMelon How would it be helpful to let the user configure mappings? :)

**Comment by SharpMelon** [comment]
@ADTC I use emojis other than those currently available for automatic replacement.

| Emoji | Value |
| --- | --- |
| :smile: | :) |
| :sparkles: | *** |
| :expressionless: | :l |
| :purple_heart: | <3 |

Surely I may be one of few with such a need.

**Comment by GandalfSaxe** [comment]
Is there any way to customize the list of replacements?

**Comment by S4JJ4D** [comment]
Hello everyone , i can not find the directory : Telegram/SourceFiles/... .
 can u help me?!

**Comment by auchri** [comment]
@S4JJ4D https://github.com/telegramdesktop/tdesktop/tree/master/Telegram/SourceFiles

**Comment by S4JJ4D** [comment]
@auchri  Thank you ^_^ , are telegram sourcefiles stored in my computer too? 
i mean i would like to access those files and modify them if possible, but i can't find them ... 

btw I'm new to programming and i just know basic C language.

**Comment by auchri** [comment]
@S4JJ4D no :) That folder contains the source files, which are compiled to the binary, which is on your computer

**Comment by S4JJ4D** [comment]
@auchri . when i type ":-)" in telegram it automatically changes to a specific emoji, all i want is to replace ":-)" with ":)" . is there any possible way to do that?!

there is a directory in the attached photo : /Users/antanubis/Tbuild/tdesktop/Telegram/... and as u see there is an cpp file in there, but this directory does not exist in my computer.

**Comment by auchri** [comment]
See #780

**Comment by KilleR** [comment]
I've followed the various chains which this is attached to, and either the integrations are not currently live, or not working, because this is still an issue as of today.
All the linked issues are closed, as far as I can see, with the exception of #780 which does not strictly solve it, but shows that it appears to be "by design" that shorthand "nose-less" emojis are not replaced.

There is an option to enable emoji auto-conversion, is it not possible to have a secondary array of auto-convert emojis, which includes the "nose-less" versions as well as the longer versions?

**Comment by Sutarat66** [comment]
เมื่อ อ. 29 ม.ค. 2562 เวลา 22:33 KilleR <notifications@github.com> เขียนว่า:

**Comment by cobrabr** [comment]
Just want to leave my +1 that this is still an issue as of today.

**Comment by dcrotty45** [comment]
I'm new to Telegram and found this very surprising.  No chat client I've used in recent years requires the dash for emoji replacement.
