### ISSUE TITLE
Bug of Message in Channal

### ISSUE THREAD

**Issue by questionpython** [telegramdesktop/tdesktop#3070]
Bug of Message in Channal(ubuntu 16.10)
https://t.me/shifteganroqaieh315/48
[
![screenshot from 2017-02-25 14-50-13](https://cloud.githubusercontent.com/assets/25328620/23330703/f6f02a1e-fb69-11e6-92af-f5f15cdc9604.png)
](url)

**Comment by auchri** [comment]
Duplicate #3035
