### ISSUE TITLE
Tray menu is shown with wrong theme

### ISSUE THREAD

**Issue by theel0ja** [telegramdesktop/tdesktop#3071]
### Steps to reproduce
1. Right click Telegram's tray icon
2. See ugly Windows 95-like theme in that tray menu

### Expected behaviour
See tray menu with OS's theme, like this with Update Manager:
![image](https://cloud.githubusercontent.com/assets/5832930/23334305/8f9d8c22-fba4-11e6-92a8-5036d4858672.png)

### Actual behaviour
I see the tray menu with ugly Windows 95 theme
![image](https://cloud.githubusercontent.com/assets/5832930/23334297/50fc2082-fba4-11e6-96c9-1191bcfecc80.png)

### Configuration
**Operating system:** Linux Mint 18.1 Cinnamon 64-bit

**Version of Telegram Desktop:** 1.0.12

**Used theme**: Default on Telegram, Mint-Y in OS

**Comment by john-preston** [comment]
What log.txt says about used tray icon? Should be either Qt tray icon or libappindicator or gtk_status_icon.

**Comment by theel0ja** [comment]
@john-preston Wrong title, tray menu's theme, not tray icon (tray icon's in the log.txt: `Using Qt tray icon.`)

**Comment by john-preston** [comment]
@theel0ja Well, Qt handles this menu then. But perhaps that's my fault because I don't allow Qt to load gtk for styles.

**Comment by auchri** [comment]
DUplicate #987
