### ISSUE TITLE
[Suggest]Can I add all read features?

### ISSUE THREAD

**Issue by LisonFan** [telegramdesktop/tdesktop#3073]

**Comment by LisonFan** [comment]
Like Gmail
![image](https://cloud.githubusercontent.com/assets/9424775/23336923/b7948a0e-fc18-11e6-9f17-a409322e0383.png)

**Comment by Aokromes** [comment]
#2697

**Comment by stek29** [comment]
@LisonFan Won't you close this, since it's a duplicate?
