### ISSUE TITLE
i cant close picture view at linux ubuntu

### ISSUE THREAD

**Issue by wandyirawan** [telegramdesktop/tdesktop#3074]
### Expected behaviour
Tell us what should happen
if i click picture should i can close picture if i click esc.
### Actual behaviour
Tell us what happens instead
picture view not close.. my mouse cursor not show.. 
### Configuration
**Operating system:** xubuntu 16.04

**Version of Telegram Desktop:** 1.0.2

**Comment by auchri** [comment]
#2497
