### ISSUE TITLE
Quitting an old group chat generates a notification

### ISSUE THREAD

**Issue by dpq** [telegramdesktop/tdesktop#3075]
### Steps to reproduce
1. Create a group chat
2. Wait an extended period of time
3. Have one of the participants quit the group chat

### Expected behaviour
The participant should quit the group chat quietly without producing any notifications

### Actual behaviour
The chat is moved to the top of the chat list and emits notifications as configured. The problem is  aggravated if it launches a chain reaction of other participants quitting the stale chat (which was e.g. dedicated to a past event)

### Configuration
**Operating system:**
Any (Windows and Linux tested)

**Version of Telegram Desktop:**
Any (up to 1.0.14)

**Used theme**:
Any

**Comment by john-preston** [comment]
@dpq Well, this is because of the service message, which is server-side controlled, it works that way in all the Telegram apps, not just Telegram Desktop, and I can't do much about that.
