### ISSUE TITLE
linux build error

### ISSUE THREAD

**Issue by anpolo** [telegramdesktop/tdesktop#3076]
Hi,

I try to compile telegram desktop on the linux system.
I generate a ninja's files of the project because a cmake project compile very slow.
I have get compiler error when ninja begin compile the Telegram application

> [3/468]  CXX obj/gen/Telegram/moc/Telegram.moc_introwidget.o
> ....
> In  file included from gen/Telegram/moc/moc_introwidget.cpp:9:0:
> gen/Telegram/moc/../../../../../Telegram/SourceFiles/intro/introwidget.h:36:30:
>  error: expected class-name before ‘,’ token
> class  Widget : public TWidget, public RPCSender {
                              ^
> gen/Telegram/moc/../../../../../Telegram/SourceFiles/intro/introwidget.h:36:49:
>  error: expected class-name before ‘{’ token
> class  Widget : public TWidget, public RPCSender {

...

Can you upload actual gyp files for linux system?

Thanks,
Andrey

**Comment by john-preston** [comment]
@anpolo What do you mean by "actual gyp files"? They're actual in the directory, the cmake backend builds them correctly. I'm afraid the ninja build is not adding the precompiled header correctly for you there.

**Comment by anpolo** [comment]
I have following rows in telegram_linux.gypi

> 'cmake_precompiled_header':  '<(src_loc)/stdafx.h',
> 'cmake_precompiled_header_script':  'PrecompiledHeader.cmake',

is it correct?

**Comment by john-preston** [comment]
@anpolo Well, this was added for cmake build to use precompiled headers. I guess ninja build for Windows uses msvs_precompiled_source and msvs_precompiled_header from telegram_win.gypi to work on Windows and I don't know how to specify precompiled header for ninja build on Linux.

**Comment by anpolo** [comment]
@john-preston How do you build on Linux? I used cmake but I spent more 1 hour. is it okay?

**Comment by john-preston** [comment]
@anpolo Usually I don't build on Linux :) Linux is a pain indeed. I'm not sure ninja will make any difference, they'll both use the same gcc launches in parallel, I'm afraid.

**Comment by anpolo** [comment]
@john-preston thanks!
