### ISSUE TITLE
Background from URL crash

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#3077]
### Steps to reproduce
1. Go to settings > Chat background
2. Click "Choose from file"
3. Type URL (like `https://overwatch.pl/wp-content/uploads/2016/12/ow11.jpg`) in file path in dialog

### Expected behaviour
Windows downloads image from URL to cache directory and gives TDesktop sign, that it should open this file.

### Actual behaviour
Telegram Desktop just closes while image downloaded by Windows. On next start it says nothing about crash.

### Configuration
**Operating system:** Windows 10 Anniversary Update (1607, 14393.693)

**Version of Telegram Desktop:** 1.0.16 Alpha

**Used theme**: any

**Additional commentary**: You still can send images by URL in `Open File Dialog`. This issue only about background

**Comment by john-preston** [comment]
@DaFri-Nochiterov Thank you for your report.
