### ISSUE TITLE
[Feature Request] Batch download media

### ISSUE THREAD

**Issue by HankAviator** [telegramdesktop/tdesktop#3080]
### Steps to reproduce
1. Open photos shared with a contact by clicking his profile, then 'xx photos'
2. Right click on the first media file
3. Drag to select multiple media files

### Expected behaviour
A button of "Download" would be appreciated

### Actual behaviour
Not implemented yet.

### Configuration
**Operating system:**
Win 10 x64
**Version of Telegram Desktop:**
1.014
**Used theme**:
None
<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
#1382
