### ISSUE TITLE
Telegram for Visually Impaired Users

### ISSUE THREAD

**Issue by SleepyDeb** [telegramdesktop/tdesktop#3084]
Please,
My cutes girlfriend is blind, she need telegram with others VIPs users like her,
Here a petition to make telegram clients software accessible:
https://www.change.org/p/telegram-should-be-accessible-for-visually-impaired

I have exprerience of Qt framework, i'll try to fix this kind of things.

More informations:
http://www.applevis.com/forum/accessibility-advocacy/petition-telegram-should-be-accessible-visually-impaired

Have a nice day,
Thanks for your time.
Alessio DM.

**Comment by mahula** [comment]
That's a good idea!
@SleepyDeb what do you have in mind? Do you know the [QtSpeech](https://blog.qt.io/blog/2017/01/20/qt-speech-text-speech/) API? It could be used for TTS.
What input methods are you thinking of? Would Braille-based input devices be an option?

**Comment by SleepyDeb** [comment]
@mahula 
No QtSpeech is needed, 
VIP users uses "Screen Reader" to navigate the desktop,
Screen Readers uses a set of API platform dependent to obtain metadata about GUI components,

Qt Widget provide an abstraction layer to that's attributes:
http://doc.qt.io/qt-5/accessible-qwidget.html
 
So, i never tryied, i'll see in next days what i can do, 
I would like to make the same thing on Android version.

Sorry for my bad eng.

**Comment by Aokromes** [comment]
#476 ?

**Comment by SleepyDeb** [comment]
Not should be, Must be, it's a different kind of thing

**Comment by stek29** [comment]
@SleepyDeb Then ask author of original issue or someone with w rights on repo to edit #476's title.
Making a duplicate because you think that word must fits more than should isn't a good thing.
These issues aren't different, even in 2017.
