### ISSUE TITLE
[Persian][bug] text outed box

### ISSUE THREAD

**Issue by xtoolkit** [telegramdesktop/tdesktop#3087]
![sketch](https://cloud.githubusercontent.com/assets/8210666/23588689/639eca40-01d6-11e7-9f47-30e1a0621db4.png)

### Expected behaviour
text outed box

### Actual behaviour
text in box :D

### Configuration
**Operating system:** Windows 10 x64 redstone

**Version of Telegram Desktop:** v1.0.13

**Used theme**: yes

sry 4 my bad english

**Comment by Lazek** [comment]
@john-preston Already fixed?
https://github.com/telegramdesktop/tdesktop/commit/5195b4d3efe8600b8c29d30f9803dce4edccae47

**Comment by john-preston** [comment]
@xtoolkit please check out the latest alpha version from https://desktop.telegram.org/changelog#alpha-version

**Comment by xtoolkit** [comment]
in v1.0.26 fixed problem
