### ISSUE TITLE
[Theme] Inline Keyboard buttons are not colored in certain situation

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#3088]
This is a minor issue, however, I think it should be reported.
If Inline Keyboard has buttons with "spaces" or other "invisible symbols, like ` ` (<-- there's a symbol), buttons are not colored.
The exact symbol in that bot is [here](https://github.com/jacklul/inlinegamesbot/blob/master/src/Commands/Game/TictactoeCommand.php#L37) (gladly bot is open source)

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/2780044/23590294/0d21f62a-01ee-11e7-9418-18c7313403ef.png)

It happens only if such symbol is used. If there're no such buttons, everything's fine.
![image](https://cloud.githubusercontent.com/assets/2780044/23590191/a080e202-01ec-11e7-941d-d1ad33eaea41.png)

### Configuration
**Operating system:** Windows 10 LTSB x64
**Version of Telegram Desktop:** 1.0.18 alpha
**Used theme**: Any

**Comment by jacklul** [comment]
Any whitespace character does this.

**Comment by MasterGroosha** [comment]
@jacklul Seems to be OK on latest Android build

**Comment by Yadkee** [comment]
Still happens.
Windows 7 64 bits -> Bug
Android 5.1.1 -> Works fine

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
