### ISSUE TITLE
[UI] "Chat background" menu rework

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#3089]
Since themes were introduced to TDesktop, I think there's a small problem with "Chat background" menu. For example, it's unclear (IMO) that one can apply theme with "Choose from file" menu. And "Chat background" name has nothing about themes.
In "Expected behaviour" section I show how this menu _may_ look like (thought it seems to have too much text).

### Expected behaviour
![image](https://cloud.githubusercontent.com/assets/2780044/23591101/3978e86a-01fc-11e7-883b-340f00d41c6e.png)

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/2780044/23591074/f618d58a-01fb-11e7-8fd5-90e9bcd428fe.png)

### Configuration
**Operating system:** Any
**Version of Telegram Desktop:** 1.0+
**Used theme**: Any

**Comment by john-preston** [comment]
@MasterGroosha Well, this indeed should be redesigned somehow  some day, but the feature of loading a theme from some file is just a helper feature for the designers, it is not meant to work that way for users — they should simply apply themes from the app itself.

**Comment by MasterGroosha** [comment]
Ok, thanks, I got your point.
I think this can be closed then.
