### ISSUE TITLE
Pre-sent forward-message is displayed in all chats

### ISSUE THREAD

**Issue by retifrav** [telegramdesktop/tdesktop#3090]
### Steps to reproduce

1. Right-click on any message in any chat;
2. Choose `Forward Message`;
3. Choose any recipient (chat or your channel) but **don't** press send button (or Enter).

### Expected behaviour

Pre-sent message should be displayed only in the chosen chat.

### Actual behaviour

Pre-sent message is displayed not only in the chosen chat but in all other chats as well (where you have the right to send messages).

### Configuration

**Operating system:** Mac OS 10.12.3
**Version of Telegram Desktop:** 1.0.18 alpha
**Used theme**: default

**Comment by john-preston** [comment]
@retifrav This works as intended. The idea was: in case you misclicked the chat you were going to forward you can just choose the right one. If you chose the right one — just forward them.

**Comment by retifrav** [comment]
@john-preston, okay then. It's just mobile client (iOS) has different behaviour, and that confused me.
