### ISSUE TITLE
BSOD when getting native Windows notifications from Telegram

### ISSUE THREAD

**Issue by XHotSniperX** [telegramdesktop/tdesktop#3091]
### Steps to reproduce
1. Install Telegram on Windows 10
2. Activate native Windows notifications in Telegram settings.
3. Experience BSOD crash when getting a notification (happens maybe once per week).

### Expected behaviour
The notification should not cause a BSOD.

### Actual behaviour
Right after or while getting a Telegram notification, a BSOD occurs. I have attached the BSOD to this message.
![bsod](https://cloud.githubusercontent.com/assets/8674737/23628138/a8c1411a-02b3-11e7-9889-5ac25e709d52.jpg)

### Configuration
**Operating system:** Windows 10 Pro 64-Bit, Build 14393.693
**PC system specs:** Intel i7 3770K, 16 GB RAM, AMD Radeon R9 290X

**Version of Telegram Desktop:** 1.0.14

**Used theme**: Standard

I never had a BSOD on my system for years other than this now with Telegram. I didn't change any hardware configuration or drivers. Telegram worked fine until version 1.0.* and until I switched the native Windows notifications on. I now switched the setting back to Telegram's custom notifications. Let's see if I get a BSOD again. I already had 3 BSOD during maybe 3 weeks with exactly the same behaviour (when getting a Telegram notification in the background) and the same error.

**Comment by john-preston** [comment]
@XHotSniperX That's a new level for Microsoft. Windows toast notifications are disable by default because for some small amount of users they freeze frequently. Microsoft guys know about the problem but don't want to fix it before the next major Windows update :( But this thing.. I still hope this is not their notifications causing it, but if they are — don't use them :(

**Comment by XHotSniperX** [comment]
@john-preston Ok, thank you! I will use Telegram's custom notifications for now.

**Comment by Aokromes** [comment]
#2639 ?

**Comment by XHotSniperX** [comment]
Ok I can confirm that I also got the exact same BSOD when receiving a Windows notification from the Instagram app on Windows 10 (Telegram was not even running then). So it really is a Windows bug, I guess.
