### ISSUE TITLE
[RFE] Remove link preview when editing

### ISSUE THREAD

**Issue by ojura** [telegramdesktop/tdesktop#3092]
Sometimes, when I send a link, the preview looks bad and I wish to remove it. However, I can't do this by editing the message - when in edit mode, clicking X doesn't suppress sending the preview, it closes the edit mode.

**Comment by stek29** [comment]
@ojura Are you sure? For me first click on `X` removes preview, and second click closes edit mode.

**Comment by ojura** [comment]
I just checked. It seems that this landed in the meantime, great!
