### ISSUE TITLE
Fixed-width fonts doesn't appear

### ISSUE THREAD

**Issue by dikiaap** [telegramdesktop/tdesktop#3093]
### Expected behaviour
Fonts fixed-width should be displayed.

### Actual behaviour
![screenshot from 2017-03-07 19-11-09](https://cloud.githubusercontent.com/assets/8542502/23672367/1103b6d4-03a1-11e7-8ef6-d7ef673913b5.png)

### Configuration
**Operating system: Lubuntu 16.04.2 x86**

**Version of Telegram Desktop: 1.0.5**

Arial, Arial monospaced, Courier, Courier new fonts already installed.

**Comment by auchri** [comment]
Duplicate #2567
