### ISSUE TITLE
Lack of a 64-bit version for Windows.

### ISSUE THREAD

**Issue by Download-Fritz** [telegramdesktop/tdesktop#3094]
Please offer a 64-bit version of the Windows client as an alternative to the 32-bit one.
There might not be a direct benefit for Telegram in the 64-bit architecture, though it would save mode switches (performed by WOW64) and the code might even execute faster due to using the AMD64 instruction set.

**Comment by john-preston** [comment]
It is not planned right now (no huge benefits from that, but requires one more version to be built and supported), but maybe some day such version will be added.

**Comment by sl1pkn07** [comment]
Hi

3years passed and still not offer win 64-bit version

why?

greetings

**Comment by Aokromes** [comment]
there is no real need of 64 bits telegram desktop,

https://github.com/telegramdesktop/tdesktop/issues/3167
