### ISSUE TITLE
"Do Not Disturb" is ignored on OSX

### ISSUE THREAD

**Issue by FabianMeul** [telegramdesktop/tdesktop#3095]
### Steps to reproduce
1. Turn on "Do Not Disturb"
2. Receive a message via Telegram Desktop

### Expected behaviour
The entire app should remain silent.

### Actual behaviour
The notification does not appear, but the "notification sound" does.

### Configuration
**OS Version**: MacOS Sierra 10.12.3

**Telegram Desktop Version**: v1.0.14

**Used theme**: Default

**Comment by john-preston** [comment]
@FabianMeul Thank you for your report. This will be fixed in the next version.

**Comment by GatoPresto** [comment]
Hi!
I have the same issue right know on macOS Sierra 10.12.6 with Telegram Desktop 1.1.19
I hear notification sound and icon bounces. 
Please fix it 😰

**Comment by GatoPresto** [comment]
@FabianMeul ping 😅

**Comment by GatoPresto** [comment]
@john-preston ping 😅

**Comment by GatoPresto** [comment]
@FabianMeul , @john-preston come on people, re-open issue pls. v1.1.22 - the same problem 😑

**Comment by FabianMeul** [comment]
I can't re-open the issue, but I have noticed this behavior as well...

**Comment by GatoPresto** [comment]
@FabianMeul ok, thanks. do you have the same problem right now?

**Comment by stek29** [comment]
Confirmed -- even with DnD enabled icon still "flashes" (bounces), and sound is played.

**Comment by pryg-skok** [comment]
MacOS High Sierra 10.13 -- the problem still persists.

**Comment by FabianMeul** [comment]
Confirmed that this is still an issue in MacOS High Sierra 10.13.1.

**Comment by littlemyx** [comment]
Sierra 10.12.6 same problem

**Comment by vadim8kiselev** [comment]
MacOS High Sierra 10.13.4
Please, fix that, I can't sleep :(

**Comment by barthe** [comment]
OSX 10.14.4  / Tdesktop 1.6.7 still not fixed, I had to close it to watch my GoT episode ... 😄

**Comment by atrasatti** [comment]
Same for WhatsApp desktop on MacOs 10.14.6

**Comment by lofloflof** [comment]
Telegram Desktop 1.9.21 still ignores DnD on macOS 10.15.4
Come on people, it's been three years …

**Comment by eirnym** [comment]
I bet "next release" has never happened

**Comment by TaiSHiNet** [comment]
Thanks @cpwc !!!

**Comment by rdednl** [comment]
to be fair this still happens for telegram voice calls, they appear in the middle of the screen with do not disturb turned on

**Comment by cpwc** [comment]
@rdednl you might want to open a new ticket on this with the various information required. Like the version of telegram you are using.

**Comment by zagorulkinde** [comment]
Still reproduce on 2.1.10 version.

**Comment by Aokromes** [comment]
try 2.1.12

**Comment by john-preston** [comment]
@zagorulkinde That's strange, someone did fix the key in code. 2.1.12 should not really differ from 2.1.10 in this way. It should work after 2.1.7.

**Comment by cpwc** [comment]
@zagorulkinde the fix went into the release v2.1.8 and it works well for me thru v2.1.12. Could you create a new issue with the required information like your OS etc so I can take a look and try to reproduce it.
