### ISSUE TITLE
Link styles in theme editor are not separated

### ISSUE THREAD

**Issue by alivekenny** [telegramdesktop/tdesktop#3099]
### Expected behaviour
Theme editor allows to change color of incoming and outcoming links separatly

### Actual behaviour
There is no styles for different types of links, all of them defines by string `windowActiveTextFg`. And this imposes restrictions on creating beautiful and contrast themes.

![pic](https://cloud.githubusercontent.com/assets/21039303/23749428/ee821fac-04e9-11e7-8dcf-c4a101cc48cb.png)

### Configuration
**Operating system:** Any

**Used theme**: Contest winning theme by Alive Kenny

**Note:** Telegram held contest for creating themes for desktop client: https://www.fl.ru/projects/3126297/konkurs-telegram-na-stili-oformleniya-dlya-desktopnoy-versii.html. I won this competition, despite problem that I described. Now I want you to fix this issue and make theme editor more flexable. I'd like to tune my theme up before it will be included in official client.

**Comment by john-preston** [comment]
@alivekenny I've added separate keys for links in the messages at some moment. They're named historyLinkInFg, historyLinkInFgSelected, historyLinkOutFg and historyLinkOutFgSelected.

**Comment by alivekenny** [comment]
Aww… Great! Thank you.

Will those themes ever be added to official client? Because contest descripion says only about backbround picture. If themes will be added to client, I think that I should send fixed one to developers.

**Comment by john-preston** [comment]
@alivekenny I don't know for now.
