### ISSUE TITLE
Image opens in all workspaces

### ISSUE THREAD

**Issue by mcherep** [telegramdesktop/tdesktop#3100]
Images opened in Desktop are in all workspaces and it's necessary to close the image to move to another workspace.

### Steps to reproduce
1. Open an image received in Telegram Desktop
2. Try to move to another workspace without closing the pop up

### Expected behaviour
Opening an image should pop up in current workspace

### Actual behaviour
Opening an image pops up in all workspaces and does not allow to navigate to another workspace while having an image opened.

### Configuration
**Operating system: Ubuntu 14.04**

**Version of Telegram Desktop: 1.0.14**

**Comment by Aokromes** [comment]
#1710
