### ISSUE TITLE
Link does not open in Firefox nightly 55

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#3102]
### Steps to reproduce
1. click a link on Telegram

### Expected behaviour
Link open in my current default browser, Ffx Nightly

### Actual behaviour
Firefox Nightly get focus, but no link open

### Configuration
**Operating system:**
Win 10
**Version of Telegram Desktop:**
1.0.20 a

I don't know if it's a Telegram issue or a Nightly issue, but links from Discord open correctly.

**Comment by Geobert** [comment]
today, 12nd March, it works again (1.0.21 or Nightly fix? Idk)

**Comment by john-preston** [comment]
@Geobert I think it is nightly fix, I don't remember changing anything for that.
