### ISSUE TITLE
Telegram only starts with Delay

### ISSUE THREAD

**Issue by Speedy1991** [telegramdesktop/tdesktop#3103]
### Steps to reproduce
1. Cinamon Mint 64  bit
2. Telegram for Linux 64 bit
3. Create a Starter with 0 delay

### Expected behaviour
Telegram should start right after log in

### Actual behaviour
Does not start

### Fix
Add a delay of minimum 4 seconds to the starter

Is this behaviour normal? Its working, but looks strange to me

**Comment by wodim** [comment]
Does not start? Anything in the log?

**Comment by Speedy1991** [comment]
where is the log? /var/log/ doesn't contain a telegram folder

**Comment by stek29** [comment]
@Speedy1991 I feel like it's going to be in stdout/stderr.
Try making some wrapper script and redirect output to file like this:

`%TDesktop Command% >$HOME/td.log 2>&1`

**Comment by Speedy1991** [comment]
This issue isn't present anymore, all working fine atm.
