### ISSUE TITLE
Editing of not the latest message on Up Arrow key

### ISSUE THREAD

**Issue by gregzhadko** [telegramdesktop/tdesktop#3104]
### Steps to reproduce
1. Send message to a chat from a mobile app (I used android app)
2. Open windows desktop client and make sure the message you sent is the latest one.
3. Press Up Arrow key

### Expected behaviour
Edit the latest message which was sent from mobile app

### Actual behaviour
Edit the latest message which was sent from the desktop client (it is not the latest in the message list)

### Configuration
**Operating system:**
Windows 10
Android 7

**Version of Telegram Desktop:**
1.0.14

**Used theme**:
Default

**Comment by john-preston** [comment]
@gregzhadko This is intended. Perhaps this could be changed in the future, but right now it uses up arrow to edit what you wrote in that field the last time — the logic now is "put back to this field what there was the last time and let me fix it".

**Comment by MasterGroosha** [comment]
@john-preston well, this explains #2454, but shouldn't "put back to this field what there was the last time and let me fix it" be saved between app restarts? (#2455)?

**Comment by john-preston** [comment]
@MasterGroosha Perhaps it should. But it is not implemented :(
