### ISSUE TITLE
cmd+w has same behavior of cmd+h on macOS

### ISSUE THREAD

**Issue by OrangeNote** [telegramdesktop/tdesktop#3105]
### Steps to reproduce
1. Open Telegram
2. <kbd>cmd</kbd>+<kbd>w</kbd>
3. Telegram hides

### Expected behaviour
<kbd>cmd</kbd>+<kbd>w</kbd> should close the window and keep Telegram as the current (active) application

### Actual behaviour
<kbd>cmd</kbd>+<kbd>w</kbd> has the same behaviour of <kbd>cmd</kbd>+<kbd>h</kbd>: it hides Telegram and switches to another application

### Configuration
**Operating system:** macOS Sierra 10.12.3

**Version of Telegram Desktop:** 1.0.14

**Comment by john-preston** [comment]
@OrangeNote And why do you need to leave the Telegram app as the current without the window shown? I'm thinking about returning the default behaviour, but I want to understand the usecase. This default behaviour maybe could be useful for some apps, but why for Telegram?

**Comment by OrangeNote** [comment]
The problem is that almost every other application works this way and so I am used to these conventions: <kbd>h</kbd> to hide, <kbd>w</kbd> to close window and <kbd>q</kbd> to quit. So the fact that Telegram doesn't follow these conventions bothers me simply because I always get caught off guard when I <kbd>cmd</kbd>+<kbd>w</kbd>. So even if leaving Telegram active after closing window has no purpose, I think it should behave like every application. For those who are fine with current behaviour, well there is <kbd>cmd</kbd>+<kbd>h</kbd> in rescue.

That's my honest opinion. Maybe I'm using <kbd>cmd</kbd>+<kbd>w</kbd> too often when I multitask, or I am too bad at breaking conventions.

**Comment by luckydonald** [comment]
It should indeed not bring up other applications.
If you have enabled "When switching to an application, switch to a Space with open windows for the application" in System Preferences, this gets annoying, as it switches to another desktop space, which probably isn't intended.

Also <kbd>cmd</kbd>+<kbd>0</kbd> is the typical Mac OS shortcut to bring back the main window. (e.g. Mail.app)

**Comment by Aokromes** [comment]
#1147 ?
