### ISSUE TITLE
[Feature Request] Send message from clipboard

### ISSUE THREAD

**Issue by esajjad** [telegramdesktop/tdesktop#3106]
Please append new feature to users able to send text or images from clipboard

![Sample](https://cloud.githubusercontent.com/assets/4344360/23791946/3feac10e-059a-11e7-807a-9b9c6e6acab9.png)

**Comment by MasterGroosha** [comment]
Why don't just open chat and press `Ctrl+V`?

**Comment by esajjad** [comment]
when you want sent a message to multiple chats, forced to open chats, then must wait to loading it, then Ctrl+V

this process kill times!

**Comment by john-preston** [comment]
@esajjad Sorry, we won't add such an option. Your usecase is too specific and I think there are too many menu items already.
