### ISSUE TITLE
Preview viewer loads thumbnail instead full-sized image

### ISSUE THREAD

**Issue by gudvinr** [telegramdesktop/tdesktop#3108]
### Steps to reproduce
1. Start/Restart app
2. Open image from list in shared media

If you click on same photo again it'll shown as expected.

### Expected behaviour
Get normal preview.

### Actual behaviour
Blured image with sharpening when hover above functional elements.

### Configuration
**Operating system:** Ubuntu 16.04

**Version of Telegram Desktop:** 1.0.20 alpha

**Used theme**: [ñumix.tdesktop-theme.zip](https://github.com/telegramdesktop/tdesktop/files/835327/numix.tdesktop-theme.zip)

![image](https://cloud.githubusercontent.com/assets/1712806/23817317/4afeacea-0603-11e7-8dee-63250844215d.png)
![image](https://cloud.githubusercontent.com/assets/1712806/23817367/a28c6e98-0603-11e7-90fc-e777dc4c65b8.png)

**Comment by john-preston** [comment]
Thanks for your report. This should be fixed by e4f7b3c7c2b348de4d98d354c7521104405b26b6

Please test in the upcoming alpha version 1.0.21 that will be deployed today.
