### ISSUE TITLE
Missing icon for muted conversations

### ISSUE THREAD

**Issue by arpadox** [telegramdesktop/tdesktop#3110]
Muted conversations don't have a 'muted' icon. There should be one above or below the 'pinned' one just like on android.
Using v. 1.0.14 on Linux, default theme.

**Comment by auchri** [comment]
Duplicate #3110

**Comment by MasterGroosha** [comment]
@auchri #3110 is this issue. "You say `Duplicate #3110` in #3110" :)

**Comment by stek29** [comment]
#2723
