### ISSUE TITLE
Telegram.dog support?

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#3111]
_Disclaimer: I tried to search for similar issues (open or closed) with "`dog`", "`telegram.dog`" and "`domain`" queries with 0 relevant results. If there's the related issue here, please, let me know._

### Steps to reproduce
1. Open chat with yourself in Telegram Desktop
2. Send yourself `telegram.dog` link, for example, https://telegram.dog/username
3. Click on it

### Expected behaviour
Chat with `@username` should be opened

### Actual behaviour
Default web-browser opens and asks to open `telegram.exe`. This can cause situation when _another_ instance of Telegram will be opened (if you have multiple installed). That's honestly another issue which I solve by "writing to registry", but whatever, not the point.

I'm aware that `telegram.dog` links aren't popular, but Telegram [explicitly mentioned](https://t.me/username/2) them and you can see `dog` links here and there.

### Configuration
**Operating system:** Windows 10 LTSB
**Version of Telegram Desktop:** 0.10.22 alpha
**Used theme**: Doesn't matter.

**Comment by auchri** [comment]
Works for me™

![asd](https://cloud.githubusercontent.com/assets/5092164/23922315/250e52a4-0902-11e7-8f72-dcbef3245304.gif)

**Comment by MasterGroosha** [comment]
@auchri I'm sorry for confusing you. Edited my issue
Please send yourself https://telegram.dog/username link and click on it inside Telegram Desktop.
Instead of opening `@username` channel you'll be directed to web browser.
