### ISSUE TITLE
[Feature Request] Make your account private (like Twitter and Instagram)

### ISSUE THREAD

**Issue by alirahhbar** [telegramdesktop/tdesktop#3113]
I think many people need to make their account private, just like Twitter and Instagram and ...
It's so necessary and prevents unwanted and blocked people to have access to your account with unknown phone numbers.

it's extremely important and makes a significant improvement on user privacy.

Thank you.

**Comment by MasterGroosha** [comment]
This is not related to Telegram Desktop. Please read the specific [FAQ section](https://telegram.org/faq#usernames-and-telegram-me) for usernames and how other people can message you.

**Comment by alirahhbar** [comment]
oh sorry. i couldn't find a good way to contact Telegram creators for bugs and features.
anyway, thanks.
