### ISSUE TITLE
[Minor request] Different background image for each conversation screen

### ISSUE THREAD

**Issue by FurtadoPires** [telegramdesktop/tdesktop#3114]
### Expected behaviour
I change the background picture A for the contact A, and B for the contact B.

### Actual behaviour
Change background for A changes for B too.

I don't know if it's possible to implement this, since the android version doesn't have that either. But It would be nice to have this option (especially for groups). I saw this feature in another app and I really liked, so I think it would be interesting to have in telegram either (if its possible of course).

Thank you for your good work.

**Comment by auchri** [comment]
Duplicate #523
