### ISSUE TITLE
Update Visual Studio Compile Doc

### ISSUE THREAD

**Issue by ghost1372** [telegramdesktop/tdesktop#3117]
hi please update building telegram in Visual Studio, Visual Studio 2017 now is available.

**Comment by john-preston** [comment]
I'm afraid that'll be tricky. I use not the latest Qt version (because they've dropped support for many OS versions which I can't loose for now) and it can have some problems with VS2017 toolset + I saw some problems with GYP on VS2017 online. I didn't try to build there yet.

**Comment by ray-pixar** [comment]
When I want to install Qt5Package from [this](https://visualstudiogallery.msdn.microsoft.com/c89ff880-8509-47a4-a262-e4fa07168408) link, I get following error:
```
The installer could not find an installation of Visual Studio 200x.

Please note that Visual C++ Express is not supported.
```

It seems that newer version of VS tools (version 2.0) has been released. Is it possible to use it ?

**Comment by shaiho** [comment]
And you use vc++ Express? If yes what is your question!!

**Comment by ray-pixar** [comment]
I am using Community edition
