### ISSUE TITLE
[docs] Keyboard Shortcuts

### ISSUE THREAD

**Issue by aero31aero** [telegramdesktop/tdesktop#3118]
### Expected behaviour
Details of all keyboard shortcuts, for now, in perhaps the help/about section of the app. 

Later, modify the setting UI to allow modifying shortcuts there.

**Comment by MasterGroosha** [comment]
Before it's implemented, look inside `tdata\tdata` folder.
`shortcuts-default.json` is a list of default shortcuts
`shortcuts-custom.json` allows you to set your own custom shortcuts.

**Comment by aero31aero** [comment]
Would you accept a PR regarding the UI changes? I'd like to give this a try soon.

**Comment by misterbrownlee** [comment]
👍  lurk mode: engaged

**Comment by auchri** [comment]
Part of #1060
