### ISSUE TITLE
Drag n drop file does not work anymore

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#3119]
### Steps to reproduce
1. drag a file (image/zip/whatever) from file explorer to telegram

### Expected behaviour
should upload the file and popup to ask for a commant

### Actual behaviour
nothing, got the "not allowed" mouse icon

### Configuration
**Operating system:**
Win 10

**Version of Telegram Desktop:**
1.0.21 to 1.0.23

**Used theme**:
custom made

**Note**:
It does work on Win 7 (at work) with the same version of Telegram

**Comment by john-preston** [comment]
@Geobert Perhaps you launch the app as administrator? You should not do so, ever.

**Comment by Geobert** [comment]
Ok thanks, Telegram is launch from a .bat after my VPN is connected, I think that's why it's in admin mode… need to sort this out thanks!

**Comment by john-preston** [comment]
@Geobert Thanks for your report! I hope to fix that in the next version.
