### ISSUE TITLE
Missing option to disable sound when sending message

### ISSUE THREAD

**Issue by suiluj** [telegramdesktop/tdesktop#3121]
### Steps to reproduce
1. Sending a message

### Expected behaviour
No annoying sound.

### Actual behaviour
Short sound on sending a message (only in the new app in Swift)

### Suggestion for a solution
Please add an option for disabling this sound.
(Sorry if it is already there, but i did not find it in the new version of the app).

Thank you very much.

### Configuration
**Operating system:** macOS Sierra

**Version of Telegram Desktop:** 2.9.9

**Comment by john-preston** [comment]
@suiluj This repository is only about Telegram Desktop issues, macOS Swift application is not here.

**Comment by ryderr** [comment]
**THIS IS STILL AN ISSUE PLEASE FIX**

**Comment by john-preston** [comment]
@ryderr It is not. Telegram Desktop doesn't have any sound on message sending.

**Comment by philipsadman** [comment]
@john-preston No, it has

**Comment by Aokromes** [comment]
you very likely are using telegram for macos, not telegram desktop on macos.

**Comment by ryderr** [comment]
still an issue

**Comment by Aokromes** [comment]
report it to telegram swift bugtracker, this is for telegram up to version 1.9.1 not for telegram 5.x

**Comment by max-menshenin** [comment]
very annoying indeed
