### ISSUE TITLE
Opening conversation but quickly hitting back button causes WSOD

### ISSUE THREAD

**Issue by gousta** [telegramdesktop/tdesktop#3122]
### Steps to reproduce
1. Press on chat bubbles to get to your conversations
2. Press on a conversation with a friend
3. The very moment the `< back` button becomes **visible** (while the conversation chat is sliding), quickly press the back button.

### Expected behaviour
You should get back to your conversations list

### Actual behaviour
You see a white screen like you're lost between the sliding transitions

### Configuration
**Operating system:** OS X El Capitan 10.11.6 (15G1217)

**Version of Telegram Desktop:** 2.9.90000

**Used theme**: None

**Comment by john-preston** [comment]
@gousta This repository is only about Telegram Desktop issues, you're talking about macOS Swift, which is not here.
