### ISSUE TITLE
Interface Scale option on Macs with Retina display

### ISSUE THREAD

**Issue by abelim10** [telegramdesktop/tdesktop#3126]
Good afternoon,

I know that there is another [similar issue](https://github.com/telegramdesktop/tdesktop/issues/69), but it's was open an closed in 2014.

Now, in 2017, there are a lot of Macs with Retina display, and it's still impossible to scale Telegram Desktop interface on all these Macs.

On a MacBook Pro from 2016 with default resolution, Telegram Desktop has a too small font size, meanwhile in Telegram for MacOS (the native client) you can enlarge this size in order to read your conversations with less effort.

I love Telegram Desktop, in my opinion is much better than Telegram for MacOS, but since I bought a Mac with Retina display I can't use Telegram Desktop conveniently because of this problem. I don't want to be forced to switch to Telegram for MacOS... Is still impossible to add "Interface scale" option to Telegram Desktop on Macs with Retina display (most of them nowadays)? At least, it would be very useful to be able to enlarge just font size, I mean, emoji size is not so important.

Thank you very much.

**Comment by Aokromes** [comment]
#1121
