### ISSUE TITLE
Using of transparent color in theme settings

### ISSUE THREAD

**Issue by David256** [telegramdesktop/tdesktop#3127]
### Steps to reproduce
1. go to settings
2. edit theme
3. in windowBg value, set a color with transparent as #ffffff0f or another
4. do scroll up/down or try to use telegram client

### Expected behaviour
Tell us what should happen

### Actual behaviour
I was thinking that the telegram client is going to be transparent and I can read through its

### Configuration
**Operating system:** Windows 8.1 but I want to try in Debian, now I only see in Windows

**Version of Telegram Desktop:** 1.0.14

**Used theme**: Default

<details><summary>**Logs**:</summary>
I think tha it is not necessary, but this image whether <br /><img src="http://i.imgur.com/QX0aHly.png" />
</details>

**Comment by john-preston** [comment]
@David256 Transparency is not supported in most of the keys, there could be glitches or it just won't work, like with windowBg. Only the keys with transparency in the original theme support it for sure.

**Comment by David256** [comment]
I was curious 😅
