### ISSUE TITLE
Can you support these input method ( gcin and hime) just like fcitx ?

### ISSUE THREAD

**Issue by taijuin** [telegramdesktop/tdesktop#3129]
here :

https://github.com/telegramdesktop/tdesktop/issues/375

you said:

Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.

------------------------------------------------------

I am currently using Ubuntu16.04

Thank you~

**Comment by john-preston** [comment]
@taijuin I don't have plugins for them :(

**Comment by Vdragon** [comment]
You may acquire Qt5 plugin of hime & gcin from hime-qt5-immodule and gcin-qt5-immodule, seems both provided at least in Ubuntu 16.04's software archive

**Comment by Vdragon** [comment]
For hime input method the qt5 related source are located at:  
https://github.com/hime-ime/hime/tree/master/src/qt5-im

For gcin input method it is in qt5-im directory of the source code which can be acquired from  
http://hyperrate.com/gcin-source/

Hope that helps

**Comment by taijuin** [comment]
http://packages.ubuntu.com/zh-tw/xenial/gcin-qt5-immodule

http://packages.ubuntu.com/xenial/hime-qt5-immodule


Is it helpful?

**Comment by taijuin** [comment]
Someone said : 
How about using system QT?
https://aur.archlinux.org/packages/telegram-desktop-systemqt-notoemoji/

**Comment by stek29** [comment]
@taijuin there's an issue for that: #1815

(this issue isn't a duplicate IMO)
