### ISSUE TITLE
[Feature Request] Hotkeys window/help

### ISSUE THREAD

**Issue by RomuloOliveira** [telegramdesktop/tdesktop#313]
A window/help with all hotkeys available would be nice.

I was using Web Version and I spend some time to get the right keys to navigate through conversations on the desktop version. Desktop uses `Ctrl + Tab` or `Ctrl + PageUp/PageDown`while web version uses `Alt + Up/Down` (for obvious reasons, I know).

**Comment by auchri** [comment]
Look at #1060
