### ISSUE TITLE
Own sent messages switch between left and right alignment

### ISSUE THREAD

**Issue by DingoRender** [telegramdesktop/tdesktop#3130]
### Steps to reproduce
1. make the Telegram Window wider
2. narrow it again

### Expected behaviour
Own messages should stay aligned to one side.

### Actual behaviour
Own messages switch alignment when the window at some point from right to left and back to the left when making the window narrower again.

These two screenshots show what I mean, I just narrowed the window by two pixels for the 2nd picture:
![telegram1a](https://cloud.githubusercontent.com/assets/26544691/24101214/b1c8798a-0d77-11e7-9d9d-47b1835350a3.jpg)
![telegram2a](https://cloud.githubusercontent.com/assets/26544691/24101215/b1d607a8-0d77-11e7-8198-ac840543be58.jpg)

I actually would prefer to have all messages left aligned (like it has been with the old versions. of Skype...), but if I widen the window enough there is that huge waste of space on the right side, and making the window narrower again, makes my sent messages flip back to the right side. 

There should be a setting how you want the messages to be aligned. Maybe something like this:
- all left
- all right
- sent left, received right
- sent right, received left
- all centered

### Configuration
**Operating system:**
Win Vista Home Premium 64bit
**Version of Telegram Desktop:**
1.0.14
**Used theme**:
standart theme
<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
There is a setting for that.

**Comment by DingoRender** [comment]
Where?

**Comment by MasterGroosha** [comment]
@DingoRender "Adaptive layout for wide screens"

**Comment by DingoRender** [comment]
*facepalm*
I'm blind... Thanks.

But then this is should be a feature request. since switching that option off just keeps my sent messages right aligned and I can't bring all messages to the left side.

**Comment by MasterGroosha** [comment]
When you turn "adaptive layout" ON, all messages align to the left side when app's window is wide enough.  
When you turn it OFF, your messages stay on the right side no matter how wide app's window is.

**Comment by DingoRender** [comment]
Yeah. Too sad there isn't an option to always have all messages left aligned.

Thanks anyways. :)
