### ISSUE TITLE
Automatic conversion of << and >> to « and »

### ISSUE THREAD

**Issue by eddex** [telegramdesktop/tdesktop#3133]
### Steps to reproduce
1. Open any chat.
2. Type << or >> in the chat text box.
3. Send.

### Expected behaviour
The message that is sent is << or >>

### Actual behaviour
The two brackets are automatically converted to a « or ». This is really annoying when sending code snippets.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.0.14

**Used theme:** NightModeByCristianOspina

![telegram](https://cloud.githubusercontent.com/assets/5302085/24139625/175e8d34-0e1d-11e7-8737-3560e466cbfc.PNG)

**Comment by auchri** [comment]
Duplicate #522
