### ISSUE TITLE
New MacOS app has no support for emoji by typing the reference string

### ISSUE THREAD

**Issue by spaghetti-** [telegramdesktop/tdesktop#3137]
### Steps to reproduce
1. Start typing an emoji character like `:new_moon_with_face:`

### Expected behaviour

A pop up appears completing and giving us difference choices for that particular emoji.

### Actual behaviour

Nothing happens

### Configuration
**Operating system:** MacOS

**Version of Telegram Desktop:** 2.91.90444 Stable

**Used theme**: None

This feature used to work before the new release of the app.

To try emoji completion you can start typing `:new` (without quotes) into a Github comment box as well and GFM will give you a popup with completion.

**Comment by diazbastian** [comment]
@spaghetti- Wrong place... T[elegram for MacOS](https://macos.telegram.org/) is another application. See https://github.com/overtake/telegram

**Comment by spaghetti-** [comment]
@auchri Oh my bad.

**Comment by spaghetti-** [comment]
@auchri are you sure that that repo by overtake is maintained? The last commit was in Jan?

**Comment by stek29** [comment]
@spaghetti- You should report this in https://t.me/macswift
