### ISSUE TITLE
Insufficient scaling level on high DPI displays

### ISSUE THREAD

**Issue by vasiliuk** [telegramdesktop/tdesktop#3138]
### Steps to reproduce
1. Use windows PC with high res display (4k preferable)
2. Change size of text, apps, and other items: 300%
3. Run telegram client with automatic interface scale

### Expected behaviour
Telegram could scale its interface according to system settings

### Actual behaviour
Telegram able to scale its interface by 200%

### Configuration
**Operating system: Windows 10 Pro**

**Version of Telegram Desktop: 1.0.14**

**Comment by auchri** [comment]
Duplicate #2144

**Comment by alex-jitbit** [comment]
nice. You closed both issues as duplicates of each other. Great job
