### ISSUE TITLE
Link Support for Multiple Language's Alphabets

### ISSUE THREAD

**Issue by ZarifinKolesi** [telegramdesktop/tdesktop#3139]
### Steps to reproduce
1. Send this link to any of telegram chats/groups: http://ebced.kuran114.org/#عبدالرحمن_القمرالنجم (copy and paste don't click)
2. Click your sended link from Windows 10 Enterprise x64 Build 1607 desktop app
3. And it will open link with loosing arabic alphabets...

### Actual behaviour
It opens this link in your browser: http://ebced.kuran114.org/#%D8%B9%D8%A8%D8%AF%D8%A7%D9%84%D8%B1%D8%AD%D9%85%D9%86_%D8%A7%D9%84%D9%82%D9%85%D8%B1%D8%A7%D9%84%D9%86%D8%AC%D9%85

### Expected behaviour
Instead of this link(with real alphabets): http://ebced.kuran114.org/#عبدالرحمن_القمرالنجم

### Configuration
**Operating system: Windows 10 Enterprise x64 Build 1607**

**Version of Telegram Desktop: 1.0.14**

<details>
If you click your link from android telegram app it opens link normally, but not in windows app.... :(
</details>

**Comment by auchri** [comment]
Google chrome and co. does the same.
