### ISSUE TITLE
Resize/Collapse conversation list

### ISSUE THREAD

**Issue by RomuloOliveira** [telegramdesktop/tdesktop#314]
I would like to resize conversation list, since it's gets too much space for me (my screen is 1366x768).

An option to expand/collapse (showing only contact pictures) would be nice too.

**Comment by Aokromes** [comment]
I checked myself and the absolute minimum size of the GUI with contact list is 640x480, i don't see how that can be to much space, hidding contact list it's only 380x480.

**Comment by vladimiry** [comment]
+1

I'm using only Linux desktop version, don't know which behavior on other systems. It would be useful to have 2 features:
- resize contact list area
- collapse contact list area

**Comment by FireNero** [comment]
Is there ETA for this feature? 2 years already passed and there is still no news about it. 
Contact list should be resizable because currently nearly 35% of the screen is wasted for just contact list.

**Comment by stek29** [comment]
@FireNero  https://twitter.com/durov/status/820694979194589186

**Comment by FireNero** [comment]
@stek29 wonderful! Thanks for the link.

**Comment by stek29** [comment]
@FireNero Update your (alpha) app -- it was just released with this issue fixed.
