### ISSUE TITLE
infinite time sending zero-width-space (\u200B)

### ISSUE THREAD

**Issue by iansowinski** [telegramdesktop/tdesktop#3145]
### Steps to reproduce
1. in mac terminal type ```printf "\xE2\x80\x8B" | pbcopy```
2. paste to chat on telegram
3. send

Often [zero-width-space](http://www.fileformat.info/info/unicode/char/200B/index.htm) breaks everything, let's make telegram resistant to it!

### Expected behaviour

It sholud bahave the same as in case of sending normal space ass message.

### Actual behaviour

It tries to send the message but ends up beeing freezed message

### Configuration
**Operating system:**

OS X 10.10

**Version of Telegram Desktop:**

1.0.14

**Used theme**:

default

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
Btw, API thinks that that message is empty (if you try to send it via webogram you get MESSAGE_EMPTY error)
So MainWidget::sendMessageFail should handle MESSAGE_EMPTY, just like HistoryWidget's saveEditMsgFail
