### ISSUE TITLE
sending normal space to yourself triggers "user typing..."

### ISSUE THREAD

**Issue by iansowinski** [telegramdesktop/tdesktop#3146]
### Steps to reproduce
1. Open conversation with yourself
2. Try to send space as only character in message

### Expected behavior

nothing should happen

### Actual behavior

chat header displays that user is writing something (and it is displayed for longer than usual)

### Configuration
**Operating system:**

OS X 10.10

**Version of Telegram Desktop:**

1.0.14

**Used theme**:

default

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
Why should this be an issue? You are actually typing something.

**Comment by Aokromes** [comment]
No longer a bug with the saved messages thing no?
