### ISSUE TITLE
When will email login be added?

### ISSUE THREAD

**Issue by Yoshimaster96** [telegramdesktop/tdesktop#3148]
What it says on the tin. I swear 99% of messaging apps allow email login, with the exception of this one. It really disappoints me.

**Comment by MasterGroosha** [comment]
This is not related to Telegram Desktop only, sorry.
Use "Settings -> Ask a Question" option in official apps to ask questions about Telegram itself

**Comment by Yoshimaster96** [comment]
It does pertain to Telegram Desktop (not exclusively, but mainly).
Honestly I don't care about the apps you mentioned requiring phone login, because they are mobile apps, therefore you are on a phone to begin with. I guess I should have specified.

"I swear 99% of messaging apps allow email login, with the exception of this one. It really disappoints me."

I guess what I meant was:
"I swear 99% of DESKTOP messaging apps allow email login, with the exception of this one. It really disappoints me."

It's just a bit awkward on a desktop, to log in with a phone. Email would make the process much smoother. However, a phone may be necessary for various types of calls, in which case I would require its usage. Skype does this, for example.

**Comment by Yoshimaster96** [comment]
Wait, I can't ask for when specific features are planned to be added? I just want a general time range, something describing your progress on this feature, or otherwise.

**Comment by john-preston** [comment]
@Yoshimaster96 Email login is not planned.

**Comment by Yoshimaster96** [comment]
@john-preston 
Ah okay. If it isn't currently planned, I'd assume it won't be added for quite some time.

However, that does beg the question. From a user's perspective, it seems like it'd be an obvious choice to implement it. But since it's not currently a feature, and you don't have any immediate plans to add it, there must be a very good reason, since it seems out of place from my point of view. Maybe you could elaborate?

**Comment by john-preston** [comment]
@Yoshimaster96 Because Telegram is a mobile first messenger, it is a mobile messenger that has a desktop version added for convenience. The main idea at its launch was to be built around existing graph of mobile contacts (phonebooks), without attempts to build yet another one email based social graph from scratch.
