### ISSUE TITLE
Linux Desktop memory leaks

### ISSUE THREAD

**Issue by coshak777** [telegramdesktop/tdesktop#3151]
### Steps to reproduce
1. Scroll the chat up

### Actual behaviour
after start
![screenshot from 2017-03-26 00-11-10](https://cloud.githubusercontent.com/assets/9570664/24326178/ab2129ec-11b9-11e7-930d-b35c6e771054.png)
after 2 days
![screenshot from 2017-03-26 00-10-42](https://cloud.githubusercontent.com/assets/9570664/24326179/ab2df33e-11b9-11e7-8929-23c6d90abc21.png)
Pressing PageUp in conversation (GIF)
![peek 2017-03-27 16-58](https://cloud.githubusercontent.com/assets/9570664/24360236/6b2005aa-130f-11e7-97c1-6ea217ffcf4e.gif)

### Configuration
**Operating system:** elementary OS 0.4 Loki (Ubuntu Xenial) Linux 4.4.0-67-generic x86_64

**Version of Telegram Desktop:**  1.0.14

**Used theme**: Arc-2 Bright

**Comment by Lonami** [comment]
#3034?

**Comment by coshak777** [comment]
@Lonami, seems like same problem

**Comment by Aokromes** [comment]
@coshak777 you can close the ticket yourself :)

**Comment by stek29** [comment]
@Aokromes or maybe @auchri should do it :D
