### ISSUE TITLE
Image view doesn't allow for multitasking

### ISSUE THREAD

**Issue by Matttter** [telegramdesktop/tdesktop#3157]
### Steps to reproduce
1. open image in conversation
2. switch workspace or alt-tab

### Expected behaviour
It should stay on one workspace and allow me to properly multitask when viewing images
### Actual behaviour
Kind of hijacks the screen and stays on the foreground no matter what
### Configuration
**Operating system:**
Linux Mint
**Version of Telegram Desktop:**
1.0.14
**Used theme**:
None

**Comment by Aokromes** [comment]
#1710
