### ISSUE TITLE
Cannot scale more then 200%, 4k displays are 250% recommended

### ISSUE THREAD

**Issue by RuslanKim** [telegramdesktop/tdesktop#3158]
### Steps to reproduce
1.  Open windows telegram on Windows 10 with 4k display
2. 
3. 

### Expected behaviour
Tell us what should happen
allow upscale up to 350% as Windows 10 allows or follow to Windows scale ratio

### Actual behaviour
Tell us what happens instead
200% scale maximum is allowed

### Configuration
**Operating system:**
Window 10 Anniversary

**Version of Telegram Desktop:**
Telegram 1.0.14

**Used theme**:
default

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
#1121
