### ISSUE TITLE
[Must Have] Defaul white(milk) background

### ISSUE THREAD

**Issue by caxujav** [telegramdesktop/tdesktop#3159]
### Steps to reproduce
No such option to fix it

### Expected behaviour
black font with white or milk background color as DEFAULT
PLUS+: fix for all type smooth "[Font] Bad, Dazzles font" https://github.com/telegramdesktop/tdesktop/issues/3160

### Actual behaviour
Dazzles the eyes any not-standart color as other messengers or mail

### Configuration
**Operating system:**
windows 7 x64
**Version of Telegram Desktop:**
Last updated
**Used theme**:

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
You can install [theme](https://t.me/themes) which suits your needs.
