### ISSUE TITLE
Chat search functionality on Ubuntu 14.04

### ISSUE THREAD

**Issue by heihachi88** [telegramdesktop/tdesktop#316]
Do you plan to add "search" functionality within the chat? Just like skype (ctrl+f and you can make a full text search)

**Comment by tushar-suresh** [comment]
>just write your search term in the search field and let the magic happen ;)

This works.

Can we close this issue?

**Comment by joshery420** [comment]
To be fair, @heihachi88 technically asked for Ctrl+F support too, which the desktop apps don't currently have.
Maybe worth marking this as a duplicate of Issue #364, just because that's received more attention.

**Comment by auchri** [comment]
duplicate of #97 too

**Comment by auchri** [comment]
Added
