### ISSUE TITLE
Make 'Home'/'End' key go to beggining/end of thread if no text has been typed

### ISSUE THREAD

**Issue by louwers** [telegramdesktop/tdesktop#3163]
### Steps to reproduce
1. Press 'End' key while scrolled up in a thread

### Expected behaviour
Go to end of thread

### Actual behaviour
Nothing

### Configuration
**Operating system:** GNU/Linux
**Version of Telegram Desktop:** 1.0.14

---

Additionally, enabling usage of the 'Home' key might also be a good idea!

**Comment by danger89** [comment]
So easy idea, but so powerful.

**Comment by ralesk** [comment]
Even better, since the editor is always in focus and <kbd>Home</kbd> and <kbd>End</kbd> mean home and end in the entered text, what about <kbd>Ctrl+Home</kbd> and <kbd>Ctrl+End</kbd>?

**Comment by louwers** [comment]
That's a fair point. However, the <kbd>PgDown</kbd> & <kbd>PgUp</kbd> keys already have this behavior.

Currently, if text has been typed <kbd>PgDown</kbd> /<kbd>PgUp</kbd> goes to beggining/end of typed text. If no text has been typed: <kbd>PgDown</kbd> /<kbd>PgUp</kbd> scrolls down/up


So my proposal is to make <kbd>PgDown</kbd> and <kbd>PgUp</kbd> scroll regardless of whether text has been typed, make <kbd>Home</kbd> and <kbd>End</kbd> scroll to the beginning/end of text if *no* text has been typed and make it go to the beginning/end of the typed text if text **has** been typed.


---

However, on OS X <kbd>Home</kbd> and <kbd>End</kbd> should go to the beginning and end of the thread regardless of whether text has been typed. This is [customary](https://en.wikipedia.org/wiki/End_key).

**Comment by louwers** [comment]
I did not consider the fact that the editor is always focussed. The behavior of the <kbd>Home</kbd> and <kbd>End</kbd> keys is completely consistent with how other editors work, including <kbd>Ctrl+Home</kbd> and <kbd>Ctrl+End</kbd> (which goes to the begin and end of the message respectively). Therefore, I don't think this behavior should be changed.

New proposal: <kbd>Home</kbd> and <kbd>End</kbd> should only go to the beggining and end of the thread if no text has been typed in the editor. Just like <kbd>PgUp</kbd> and <kbd>PgDown</kbd> only scroll the messages if no text has been typed in the editor.

**Comment by ralesk** [comment]
Ah yes, I always forget about macOS and its weird editior idiosincracies, never having used it much.  Of course as with all shortcuts, they should reflect the OS's customs.

Pinging #1060 as related issue.

**Comment by auchri** [comment]
See #1060
