### ISSUE TITLE
Sorting modes for contact list / groups

### ISSUE THREAD

**Issue by Kthulhu** [telegramdesktop/tdesktop#3165]
### Steps to reproduce
1. Just launch it
2. If you have more than 10 contacts/bots - contact list turns into mess.

### Expected behaviour
1. Would be nice to have contacts organized into user-defined groups: Favorites, Friends, Family, Work, Company1, Company2, Channels, Bots, etc.
2. Would be nice to have "compact" mode for the contact list, when all the contacts have twice smaller height than now.
3. Would be nice to automatically put new bots into "Bots" group.
4. It should be possible to reorder groups as well. Collapse/open group is also would be nice.
5. Would be nice to be able to mute whole group and drag'n'drop contacts between groups.

### Actual behaviour
Mess. Contact list is a mess now.

### Configuration
Win10, latest build.

**Version of Telegram Desktop:**
Latest, i don't know how to find the version.
(Btw, can you add version display to the "system menu" at the left top corner?)

**Used theme**:
Default

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
Duplicate #1107

**Comment by DRSDavidSoft** [comment]
I asked for the same things in #2511.
