### ISSUE TITLE
Could there be possibility to get also telegram usernames saved to Telegrams contacts, not only phone numbers or with phone numbers, in all Telegram apps to different distributions?  

### ISSUE THREAD

**Issue by Juk111** [telegramdesktop/tdesktop#3166]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by 09387415554** [comment]
phone nomber flood

**Comment by stek29** [comment]
This would be a nice feature indeed.Sadly, as you noted, it's not supported on server side.
Try asking Telegram support, or pinging TG on Twitter.
