### ISSUE TITLE
Can't rename some contacts

### ISSUE THREAD

**Issue by GroxExMachine** [telegramdesktop/tdesktop#3168]
### Steps to reproduce
1. Open contact profile from list or from chat header

### Expected behaviour
Expects to have [< BACK], [EDIT] and [DELETE] buttons at the top

### Actual behaviour
Only [< BACK] button are present at the top

### Configuration
**Operating system:**
Windows 7 x64
**Version of Telegram Desktop:**
1.0.14
**Used theme**:
default

![image](https://cloud.githubusercontent.com/assets/3265395/24500301/7fa22892-154d-11e7-9f3d-eb578a761b4d.png)

**Comment by john-preston** [comment]
@GroxExMachine Looks like he isn't in your contact list, at least his phone number is not available.

**Comment by GroxExMachine** [comment]
> Looks like he isn't in your contact list
Yes, I have no his phone in my contacts on the phone. But why should I? To only be able to rename a person? A have a bunch of colleagues in different chats. Dozens of them. 
If I should add there phones just to be able to rename them it is a bad practice.

**Comment by stek29** [comment]
#3166

**Comment by DiegoAccorinti** [comment]
Sometimes you are the manager of a group and you have 50 users. And you need to know who is who, you can not remember the nicknames of everyone. Then there is no way to assign a name to non-phonebook users.
It would be good if a group administrator can "tag" or assign names (only he/she sees) to non-phone contacts that have only aliases.
