### ISSUE TITLE
Unable to send formatted message from desktop client.

### ISSUE THREAD

**Issue by sntp** [telegramdesktop/tdesktop#3169]
I can  send formatted messages using ** and __ from android and web client but can't do that from desktop client.

![screen shot 2017-03-30 at 16 06 53](https://cloud.githubusercontent.com/assets/7084556/24503815/be64f912-1564-11e7-847f-2285f315e654.png)

### Steps to reproduce
1. Send message `**BOLD** __Italic__` from desktop client
2. See result

### Expected behaviour
> **BOLD** _Italic_ from

was sent

### Actual behaviour
> `**BOLD** __Italic__`

was sent

### Configuration
**Operating system:**
macOS 10.12.3

**Version of Telegram Desktop:**
1.0.14

**Used theme**:
Default

**Comment by Aokromes** [comment]
Confirmed on 1.0.26 and Windows 10 RS2.

**Comment by kirsan31** [comment]
#2847
