### ISSUE TITLE
Incorrect version number in Active Sessions in iOS app

### ISSUE THREAD

**Issue by Lazek** [telegramdesktop/tdesktop#3170]
Telegram Desktop 1.0.26
Telegram iOS 3.18

In Telegram Desktop -> Active Sessions - app version detected correctly.

In iOS app in Active Sessions:
For iOS app:
Telegram iOS 3.18 - all right.

For Telegram Desktop:
Telegram Desktop 1000026

Please check, may be need send another variable to servers side with version number.

**Comment by stek29** [comment]
@Lazek That's iOS app bug, you can report it via twitter or support

**Comment by Lazek** [comment]
Sended via https://telegram.org/support

**Comment by anfimovir** [comment]
Fixed in latest version (Telegram iOS 4.2.1).
