### ISSUE TITLE
Voice Call feature

### ISSUE THREAD

**Issue by danger89** [telegramdesktop/tdesktop#3172]
### Steps to reproduce
1. Open Telegram
2. Try to call people (either via the Menu-> Calls or contact person -> Call)

### Expected behaviour
I would like to see this call feature in the Desktop App. So I can actually use Telegram as a Skype alternative, but then even better.

### Actual behaviour
Telegram Mobile App does support voice calls, but Telegram Desktop doesn't.

### Configuration
**Operating system:** Windows & Linux

**Version of Telegram Desktop:** 1.0.26

**Used theme**: Default

**Comment by auchri** [comment]
Duplicate #787
