### ISSUE TITLE
More GCC 7.x build errors

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#3173]
### Steps to reproduce
1. Try to build tag 1.0.26 under GCC 7.
2. 
3. 

### Expected behaviour
Successful build.

### Actual behaviour
Build failure:
```c++
[ 59%] Building CXX object CMakeFiles/Telegram.dir/builddir/build/BUILD/tdesktop-1.0.26/Telegram/SourceFiles/ui/text/text.o
/builddir/build/BUILD/tdesktop-1.0.26/Telegram/SourceFiles/ui/text/text.cpp: In member function 'bool TextPainter::eBidiItemize(QScriptAnalysis*, {anonymous}::BidiControl&)':
/builddir/build/BUILD/tdesktop-1.0.26/Telegram/SourceFiles/ui/text/text.cpp:2136:38: error: this statement may fall through [-Werror=implicit-fallthrough=]
        if(status.eor == QChar::DirEN || dir == QChar::DirAN) {
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/builddir/build/BUILD/tdesktop-1.0.26/Telegram/SourceFiles/ui/text/text.cpp:2139:7: note: here
       case QChar::DirBN:
       ^~~~
/builddir/build/BUILD/tdesktop-1.0.26/Telegram/SourceFiles/ui/text/text.cpp:2193:7: error: this statement may fall through [-Werror=implicit-fallthrough=]
       if(status.eor == QChar::DirAN) {
       ^~
/builddir/build/BUILD/tdesktop-1.0.26/Telegram/SourceFiles/ui/text/text.cpp:2196:6: note: here
      case QChar::DirES:
      ^~~~
/builddir/build/BUILD/tdesktop-1.0.26/Telegram/SourceFiles/ui/text/text.cpp:2104:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
     if(status.lastStrong != QChar::DirAL) {
     ^~
/builddir/build/BUILD/tdesktop-1.0.26/Telegram/SourceFiles/ui/text/text.cpp:2173:4: note: here
    case QChar::DirAN:
    ^~~~
cc1plus: all warnings being treated as errors
```

### Configuration
**Operating system:** Fedora 26+

**Version of Telegram Desktop:** 1.0.26

**Used theme**: default

**Comment by Lazek** [comment]
@john-preston duplicate: https://github.com/telegramdesktop/tdesktop/issues/3171

**Comment by xvitaly** [comment]
> duplicate

No. You are wrong.

**Comment by john-preston** [comment]
It is not a duplicate, but those are not real errors, but GCC 7 specific warnings, so I'm not sure when I'll fix them.

**Comment by ignatenkobrain** [comment]
@john-preston if it is expected (fallthrough), then you should just add comment into the source code:

```
/* FALLTHROUGH */
```

**Comment by john-preston** [comment]
@ignatenkobrain But right now I can add some comments or attributes to silence the warnings to this place and find out that some another place with a fallthrough fires a warning, it is impractical. If a pull request with all the required fixes for GCC 7 build support without breaking any current build will be suggested I'll merge it.

**Comment by mymedia2** [comment]
I daresay it's better to remove `-Werror` flag.

**Comment by xvitaly** [comment]
> I daresay it's better to remove -Werror flag.

Ofc, I know and already done for our Fedora package. But this warnings later will be treated as errors and need to be fixed.

**Comment by vitlav** [comment]
Please, update this issue against telegram-desktop 1.3.0 or newer.
