### ISSUE TITLE
Add the Cloud button on the right panel.

### ISSUE THREAD

**Issue by luckcolors** [telegramdesktop/tdesktop#3174]
### Steps to reproduce
1. Click on the menu button on the desktop app.

### Expected behaviour
The button should be there...

### Actual behaviour
It's not there...

### Configuration
**Operating system: Windows 10 64bit**

**Version of Telegram Desktop: Latest just updated today.**

**Used theme**: Default

### Notes
This is not really an issue but mainly a missing continuity in the ui that always puzzled me.
I know clicking on my user avatar does the same thing.
So yeah, sorry if this will probably be the silliest issue that you saw on github. I couldn't help it. :)

### Android app
![screenshot 30 mar 2017 6_21_05 pm -edited](https://cloud.githubusercontent.com/assets/3228598/24515245/4a1d7cec-1577-11e7-9ef6-4369e0ad9f5e.png)

### Desktop app
![screenshot 2017-03-30 18 41 01](https://cloud.githubusercontent.com/assets/3228598/24515640/82ccbc46-1578-11e7-8247-490b40ea6f0e.png)

**Comment by Lazek** [comment]
@john-preston duplicate: https://github.com/telegramdesktop/tdesktop/issues/2591

**Comment by luckcolors** [comment]
I see. Feel free to close it then.
