### ISSUE TITLE
Status icon behaviour changed since 1.0.14

### ISSUE THREAD

**Issue by Matttter** [telegramdesktop/tdesktop#3175]
### Steps to reproduce
1. open telegram
2. click status icon

### Expected behaviour
Before the 1.0.26 update, it minimized/maximized
### Actual behaviour
Now it shows what I would consider to be right-click behaviour, instead of opening/closing straight away I have to do two clicks now which is very annoying.
### Configuration
**Operating system:** Linux Mint 

**Version of Telegram Desktop:** 1.0.26

**Used theme**: none

**Comment by john-preston** [comment]
@Matttter I have no idea how this happens (it happens all the time, from one version to another several reports appear about the tray icon behaviour in Linux). Very often some of them tell us that it got fixed for some DE and others tell us that it got broken for some DE — and all of this I don't know why :)

I think this comes together with that report about fixed styles: https://github.com/telegramdesktop/tdesktop/issues/987#issuecomment-290412105

**Comment by Matttter** [comment]
What is the expected behaviour? I mean what is the intention of the developers? On Linux mint (cinnamon) it has worked without the context menu until now, but on Gallium OS (an ubuntu for Chromebooks which uses xfce4) it has always forced me to go through the contect menu (only used 1.0.14 I think)

**Comment by john-preston** [comment]
@Matttter I'd say there is no expected behaviour, because all the zoo of Linux systems has different tray icons with different capabilities.

I use libappindicator when it is available (and it has no such thing as click handler — only a menu, which it decides when to show), because it was the only tray icon implementation that worked on Ubuntu (which is believed to be the most popular Linux system) at the time of development.

If it is not available I use gtk status_icon when it is available (and activate window by click) which is deprecated in some systems, but it did work in Ubuntu (which is believed to be the most popular Linux system).

Otherwise I use Qt tray icon, which has a click handler, but I think it works somewhere and doesn't work elsewhere (where it uses the same API as libappindicator) and shows only the menu.

**Comment by Matttter** [comment]
Thanks for your answer. So is this a no-fix or do you want me to provide details, logs... ?

**Comment by john-preston** [comment]
@Matttter You can look up in the log.txt (in ~/.TelegramDesktop or ~/.local/share/TelegramDesktop) and see which tray icon backend is used (and why). But if it is libappindicator I think it should be left that way — this is a library done specifically for tray icons and it should be their feature request to provide a way to set up a click handler.

**Comment by Matttter** [comment]
```
[2017.03.30 18:44:46] Using appindicator tray icon.
[2017.03.30 18:44:46] Not using Unity Launcher count.
```

So this is libappindicator right? It must have been using something else before, really weird. Is there some way I can force the tray icon backend to be changed (terminal argument?)

**Comment by Matttter** [comment]
I just want to thank you btw for being present and actually developing in the open, as opposed to the Android app guy who seems to have no clue about how git works or else just does it on purpose, and who is also (maybe by company directive but idk) really really behind on updates in source (GPL anyone?)

**Comment by xvitaly** [comment]
@john-preston Same problem under Fedora 25+ (with KDE Plasma 5) and Telegram Desktop 1.0.26. No context menu on tray icon.

**Comment by Matttter** [comment]
@xvitaly You misunderstood my issue I think. My issue is that I **do** have the context menu. I want there to be a context menu *only* when I right-click, and just min/maximize when I left-click

**Comment by Matttter** [comment]
And could you look for those same lines in the Telegram log, to see how they compare?

**Comment by xvitaly** [comment]
> And could you look for those same lines in the Telegram log, to see how they compare?

Created new issue #3177 with logs.

**Comment by mikehaertl** [comment]
Another duplicate with logs: #3181

**Comment by felfert** [comment]
Like xvitaly, I have **neither** menu nor a left-click action (Fedora24 with KDE Plasma 5 Desktop).
However, i saw in the logs, that it could not find libappindicator3, so I went ahead and installed it:
````
sudo dnf install libappindicator-gtk3
````
After that, I now have at least a working menu on right-click.

**Comment by felfert** [comment]
Ok, some more experiments regarding appindicator:
After installing libappindicator-gtk3, the list of relevant installed packages was:
````
libappindicator-12.10.0-11.fc24.x86_64
libappindicator-sharp-devel-12.10.0-11.fc24.x86_64
libappindicator-12.10.0-11.fc24.i686
libappindicator-gtk3-12.10.0-11.fc24.x86_64
libappindicator-sharp-12.10.0-11.fc24.x86_64
````
Next step: Uninstalled all the above. After that, situation is as follows:
[log.txt](https://github.com/telegramdesktop/tdesktop/files/885125/log.txt)
The left-click action works initially, but after ~4 clicks, it stops working. Menu pops up correctly on right click and I can Hide/Restore the main window from there. After that, left-click action works again for a few clicks. This behavior sounds suspiciously like a race-condition with some window-state flags when using the qt tray icon...

Being a developer myself, I probably will try to get the beast building on Fedora at the weekend....

**Comment by Matttter** [comment]
Nice work, glad to see I'm not the only one at least

**Comment by Matttter** [comment]
So... i

**Comment by felfert** [comment]
One more observation:
If I use the window-manager for hiding (by clicking on the close-icon of the main window decoration), the left-click action of the tray-icon stays functional - This supports my hunch regarding a race-condition in the qt tray-icon handler.

**Comment by xvitaly** [comment]
>  However, i saw in the logs, that it could not find libappindicator3, so I went ahead and installed it:

On KDE Plasma Telegram Desktop must use native Qt tray icon, not appindicator.

**Comment by felfert** [comment]
> On KDE Plasma Telegram Desktop must use native Qt tray icon, not appindicator.
I find that a bit harsh. After all, it is a multi-platform app and with those, one never can expect a "correct" behavior on **all** the various desktop environments.
An additional (hidden?) parameter for manually overriding the automatic selection of the tray icon framework would be quite useful in such cases.

**Comment by ea4eoz** [comment]
After installing gir1.2-appindicator3-0.1 in Debian Sid + Plasma 5 everything is working fine.

**Comment by felfert** [comment]
New behavior after updating from 1.0.26 to 1.0.27:
Left click stopped working *completely* when using Qt try icon.

**Comment by Matttter** [comment]
1.0.27 didn't change anything for me on either device

**Comment by felfert** [comment]
Sorry for the confusion - After retesting I must take that back. Nothing changed.

**Comment by hk0O7** [comment]
I've been experiencing this issue since 1.0.26 on Linux Mint MATE.

**Comment by jorgicio** [comment]
If you run the telegram-desktop as root, the icon appears. At least this worked for me in MATE 1.18 in Gentoo.

**Comment by focuz** [comment]
Same problem on MX Linux 19 with latest XFCE 4.14.

Tellegram v.1.8.8.

**Comment by ncc-1701-a** [comment]
Sorry for duplicate post, but the same problem on Debian sid (unstable) with XFCE 4.14.
Telegram v.1.8.15.
Other applications (Skype (electron based), Viber (qt5), uget (GTK2) and deluge (GTK3)) are have not this issue.
Additional information: appindicator (libappindicator3-1) has been purged deliberately: it does not help.
Please fix this.
