### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pertsev** [telegramdesktop/tdesktop#3178]
Hello. I already texted to support, but they are ignore me.

I like telegram, but it lacks a couple ~~killer~~ features :)
1) (most wanted) 2x speed button for audio messages. (if you have same sluggish friends like me you will welcome it)
2) "Like" button on messages of other people in chat. I suppose It will save space in chat and will more readable than ton of emojis (stickers).

Thank you!

**Comment by MasterGroosha** [comment]
First of all, these are not TDesktop-related questions (they're meta and not platform-specific).
Second, please read [Feature Philosophy](https://core.telegram.org/tsi/feature_philosophy) document to find the answer to your question.
