### ISSUE TITLE
Broken headings in the docs

### ISSUE THREAD

**Issue by auchri** [telegramdesktop/tdesktop#3182]
### Steps to reproduce
1. Open build docs for [gyp/cmake](https://github.com/telegramdesktop/tdesktop/blob/dev/doc/building-cmake.md) or [xcode](https://github.com/telegramdesktop/tdesktop/blob/dev/doc/building-xcode.md). 

### Expected behaviour
The headings are rendered correctly

### Actual behaviour
The headings are not rendered correctly, because an space is missing.

Expected format by github: `## Heading`
The broken format in the docs: `##Heading`

**Comment by Calijor** [comment]
Done.

**Comment by auchri** [comment]
@Calijor what do you mean by "Done"? :)

**Comment by Calijor** [comment]
I made the spacing edits yesterday but it looks like the pull request didn't go through. I think it did this time.

**Comment by auchri** [comment]
@Calijor No, I can't find it :(
