### ISSUE TITLE
Build fails at "perl init-repository --module-subset=qtbase,qtimageformats"

### ISSUE THREAD

**Issue by CaninoDev** [telegramdesktop/tdesktop#3185]
### Steps to reproduce
1. Follow the build instructions up to `perl init-repository --module-subset=qtbase,qtimageformats`

### Expected behaviour
Successfully initialize the repository

### Actual behaviour
Received the following errors:

> + git submodule init qtbase 
> + git config commit.template /usr/local/src/Tbuild/Libraries/qt5_6_2/.commit-template 
> + git clone --no-checkout git://code.qt.io/qt/qt5/../qtbase.git qtbase 
> Cloning into 'qtbase'... 
> fatal: remote error: no such repository: /qt/qt5/../qtbase.git 
> git clone --no-checkout git://code.qt.io/qt/qt5/../qtbase.git qtbase exited with status 32768 at  init-repository line 198. 
> 	Qt::InitRepository::exe(Qt::InitRepository=HASH(0x5575b6154ba8), "git", "clone", "--no-checkout", "git://code.qt.io/qt/qt5/../qtbase.git", "qtbase") called at init-repository line 534 
> 	Qt::InitRepository::git_clone_one_submodule(Qt::InitRepository=HASH(0x5575b6154ba8), "qtbase", "qt5/../qtbase.git", 0) called at init-repository line 408 
> 	Qt::InitRepository::git_clone_all_submodules(Qt::InitRepository=HASH(0x5575b6154ba8), "qt5", 0, "qtbase") called at init-repository line 644 
> 	Qt::InitRepository::run(Qt::InitRepository=HASH(0x5575b6154ba8)) called at init-repository line 655

### Configuration
**Operating system:**
Ubuntu 16.10 (Yakkety)
**Version of Telegram Desktop:**
1.0.26

**Comment by auchri** [comment]
> `git clone --no-checkout git://code.qt.io/qt/qt5/../qtbase.git qtbase`

Why do you have `..` in the path?

**Comment by CaninoDev** [comment]
I don't know. Is this an environment variable?
