### ISSUE TITLE
GTK dialogues on KDE Plasma

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#3187]
### Steps to reproduce
1. Run Telegram Desktop.
2. Click on "Attach file" button.
3. 

### Expected behaviour
Qt open file window must be shown.

### Actual behaviour
GTK file open window. GTK dialogues is suitable for Gnome, XFCE, LXDE and others DE based on GTK, but not for KDE Plasma. In KDE Telegram Desktop must use only Qt dialogues.

### Configuration
**Operating system:** Fedora 25+

**Version of Telegram Desktop:** 1.0.26

**Used theme**: default

**Comment by Aokromes** [comment]
#987 ?

**Comment by stek29** [comment]
@Aokromes Just #2411 I guess :)
