### ISSUE TITLE
[Feature request] Hide left sidebar to show only pictures.

### ISSUE THREAD

**Issue by SannePetersNL** [telegramdesktop/tdesktop#3189]
In the App for Whatsapp app there is a feature that if you pull on the left sidebar to make it small it will only show the images. I would love it if you could also make something like that.

http://imgur.com/a/3Es3l  <- Picture preview of what I mean in the other app.

**Comment by auchri** [comment]
You can drag the sidebar in Telegram Desktop to only show the contact images 😉 .

**Comment by mikerockett** [comment]
Seems something’s gone wrong with this… After a while, doesn’t seem to want to collapse anymore.
