### ISSUE TITLE
[Feature Request] Twitter preview.

### ISSUE THREAD

**Issue by korjjj** [telegramdesktop/tdesktop#319]
Hi.
I think it'd be nice to have twitter links displayed as full tweets, in a way as it is done for Instagram.

**Comment by Aokromes** [comment]
if this is added, plz create a setting to disable it.

**Comment by HallEffect** [comment]
+1

**Comment by onotoleonide** [comment]
this
also facebook, vk and soundcloud support would be cool too

**Comment by korjjj** [comment]
Awesome, thanks!

**Comment by auchri** [comment]
Added
