### ISSUE TITLE
Where are c* functions/macros?

### ISSUE THREAD

**Issue by light2yellow** [telegramdesktop/tdesktop#3190]
Where are all the functions/macros beginning with c* defined? Searching with GitHub and Google revealed nothing.

For example, [this piece of code](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/application.cpp#L634):
```cpp
if (dpi <= 108) { // 0-96-108
		cSetScreenScale(dbisOne);
	} else if (dpi <= 132) { // 108-120-132
		cSetScreenScale(dbisOneAndQuarter);
	} else if (dpi <= 168) { // 132-144-168
		cSetScreenScale(dbisOneAndHalf);
	} else { // 168-192-inf
		cSetScreenScale(dbisTwo);
	}
// ...
// ...
                cSetRetina(true);
		cSetRetinaFactor(devicePixelRatio);
		cSetIntRetinaFactor(int32(cRetinaFactor()));
		cSetConfigScale(dbisOne);
		cSetRealScale(dbisOne);
```

Where can I find the source code for these functions/macros? Or these are some kind of global ones?

Sorry for the stupid question.

**Comment by stek29** [comment]
[Here](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/settings.h#L40).

**Comment by light2yellow** [comment]
Thanks, missed it somehow.
