### ISSUE TITLE
Mention which unsupported message was received (such as calls)

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#3191]
### Steps to reproduce
1. Ask someone to call you
2. Open Telegram desktop

### Expected behaviour
You'll see a message that calls aren't supported on desktop

### Actual behaviour
You get an amorphous message that the current message type is not supported on this platform.

I think it would be much better to show some more indicative message about it. Maybe it's possible to just show the message type as received from the server, so users will know which message type was it, without going to the phone to check it.

**Comment by john-preston** [comment]
@arieljannai Which version of Telegram Desktop do you use?

**Comment by arieljannai** [comment]
Sorry, I wasn't updated to the latest alpha, now I do :)

**Comment by stek29** [comment]
I guess you can only get the CRC32 of TL type for the unsupported message.
If you were able to get the name for it, then you'd have it.
