### ISSUE TITLE
Selected messages to forward are ignored when clicking on my profile picture

### ISSUE THREAD

**Issue by srazi** [telegramdesktop/tdesktop#3192]
### Steps to reproduce
1. Select some messages
2. Click on forward button to forward them
3. Click on sidebar icon
4. Now click on your profile picture

### Expected behaviour
By clicking on send button you should be able to forward messages to yourself.

### Actual behaviour
Send button and forward message status are disappeared an so you cant forward to yourself in this way.

### Configuration
**Operating system:**
Windows 10 x64
**Version of Telegram Desktop:**
1.0.27

**Comment by auchri** [comment]
@srazi Just write yourself some message so that you appear in your contact list. Then you are able to forward you messages.

**Comment by srazi** [comment]
@auchri Sorry for my bad English. It seems you didn't get what I mean. I try to explain more:
I can forward messages to myself in several ways, for example:
 1. Select messages -> click forward button -> search my name or username -> select my contact item from search result -> click on send button.
 2. Select messages -> click forward button -> go to a group chat info -> select my contact item from chat member list -> click on send button.
 3. First pin my contact item -> select messages -> click forward button -> select my contact item that is pinned -> click on send button.
 4. (the way that I suggested here) Select messages -> click forward button -> click on three parallel lines at top-left -> click on profile picture -> click on send button.

P.S.1: As you can see both way 1 and way 2 needs more mouse or keyboard interaction than the way that I suggested in this issue.

P.S.2: The way 3 is good but one of 5 pin locations is used by my contact item.

**Comment by stek29** [comment]
@auchri That's a workaround.

Being unable to select chat with yourself when forwarding, but being able to do it in normal state is very counter-intuitive, and I'd call it a bug.
