### ISSUE TITLE
No notifications since v1.0.26

### ISSUE THREAD

**Issue by jannblm** [telegramdesktop/tdesktop#3193]
### Steps to reproduce
1. Have notification settings on, Windows notifications either checked or unchecked, and chat not muted. No quiet hours set on system
2. Have Telegram minimised or in the background
3. Receive a message

### Expected behaviour
Notification popup with sound appears, tab flashes with number of unread messages and app icon gets a badge with unread messages.

### Actual behaviour
Tab flashes with number of messages and app icon gets a badge with unread messages, with no notification popup nor sound.

### Configuration
**Operating system:** Windows 8.1

**Version of Telegram Desktop:** v1.0.26 and v1.0.27 Portable

**Used theme**: Default

**Comment by stek29** [comment]
Does Windows 8.1 have DnD mode? If yes, is it disabled?

**Comment by auchri** [comment]
@stek29 Also try upgrading to Windows 8.

**Comment by auchri** [comment]
@jannblm Also try upgrading to Windows 10.

**Comment by jannblm** [comment]
@stek29 Windows 8 has Quiet Hours, just like Windows 10, but I have them disabled. I still get notifications from other programmes that use Windows notifications or their own notifications, just not Telegram since the 1.0.26 update.

**Comment by jannblm** [comment]
I let Telegram run in the background without receiving messages for a few hours, and then at 15:28 I received a message. Got a log entry right at that moment saying the following: "[2017.04.03 15:28:15] Quiet hours changed, entry value: 0". I haven't changed quiet hours today at all. Still disabled, and still getting notifications from all other programmes. Not sure if this may help in finding the issue.

**Comment by john-preston** [comment]
@jannblm Looks like you have NOC_GLOBAL_SETTING_TOASTS_ENABLED registry variable in Software\Microsoft\Windows\CurrentVersion\Notifications\Settings set to 0  which is an API for quiet hours being enabled, at least in Windows 10 :(

**Comment by jannblm** [comment]
@john-preston That fixed it, thank you and sorry for taking your time with something that was wrong with my computer!
