### ISSUE TITLE
Copy word / coupon with Click

### ISSUE THREAD

**Issue by p1rralho** [telegramdesktop/tdesktop#3197]
Is it possible to post a message on the telegram channel, where the possibility to copy the discount code to the clipboard of the android phone?

For example, click "test" and it will be copied to the clipboard:
✂️ CODE: ➡️ TEST

I saw this on the bot, where you can create or show your content (on android).

**Comment by auchri** [comment]
Every message can be copied to the clipboard.

**Comment by p1rralho** [comment]
In this example here, I was able to copy the code: 0064 to the clipboard just by clicking on it

[IMG]http://i63.tinypic.com/fbvyad.png[/IMG]

**Comment by auchri** [comment]
@p1rralho The number you see there is formatted as code.

E.g. \0066\``

**Comment by stek29** [comment]
Also keep in mind that code is copied by click only on Android currently (maybe on iOS, haven't tested)

**Comment by p1rralho** [comment]
Many thanks @auchri
