### ISSUE TITLE
Telegram starts really slow (Linux)

### ISSUE THREAD

**Issue by j00ch** [telegramdesktop/tdesktop#3199]
Since i updated Telegram it starts really slow, about one minute!

### Steps to reproduce
1. Install Telegram
2. Run Telegram

### Expected behaviour
Start instantly

### Actual behaviour
Starts really slow, about one minute until Telegram appears.

### Configuration
Manjaro Linux, Openbox, package installed from AUR. No pulse audio.

**Version of Telegram Desktop:**
1.0.14

**Used theme**:
Default

**Debug**:
Running from terminal:
```
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
AL lib: (EE) ALCcaptureAlsa_open: Could not open capture device 'default': Onjuist apparaat
```
running with strace reveals
`REJECTED EXTERNAL DBUS_COOKIE_SH`

<details><summary>**Logs**:</summary>

[log.txt](https://github.com/telegramdesktop/tdesktop/files/890571/log.txt)

</details>

**Comment by auchri** [comment]
Please try the binaries from https://desktop.telegram.org/.

**Comment by j00ch** [comment]
Thanks for your reply and yep that was the fix! Once i updated to version 1.0.27, the symptoms were gone. Case closed, i notified the package maintainer.

**Comment by MrWaZZup** [comment]
Are you sure new binaries have helped you? I've got same issue. Only 1st launch (after system startup) is slow. Next ones will be instant (as it's been before even for the first one). So, new binaries launched instantly for me... but only until system reboot :)

Ubuntu-Mate 16.04.3 LTS (Xenial Xerus) 64bit
Linux 4.4.0-104-generic x86_64
MATE 1.12.1

**Comment by jm33-m0** [comment]
#4240 mentioned this issue again, not yet fixed in the latest release

**Comment by MrWaZZup** [comment]
Yep, this was me) I've decided to open a new issue as this one is closed. Problem looks similar, but its roots seem to be different.
