### ISSUE TITLE
https instead of git for Qt repo link

### ISSUE THREAD

**Issue by stek29** [telegramdesktop/tdesktop#3200]
<h3>This comment is not relevant anymore, please scroll down a bit</h3>
`init-repository` fails if `git` is used for origin remote.
<details><summary>What happens if I try to init repo:</summary>
<pre>
=> perl ./init-repository --module-subset=qtbase,qtimageformats
+ git submodule init qtbase qtimageformats
Submodule 'qtbase' (git://code.qt.io/qt/qtbase.git) registered for path 'qtbase'
Submodule 'qtimageformats' (git://code.qt.io/qt/qtimageformats.git) registered for path 'qtimageformats'
+ git config commit.template /Users/stek/qt5/.commit-template
+ git clone --no-checkout git://code.qt.io/qt/qt5/../qtbase.git qtbase
Cloning into 'qtbase'...
fatal: remote error: no such repository: /qt/qt5/../qtbase.git
git clone --no-checkout git://code.qt.io/qt/qt5/../qtbase.git qtbase exited with status 32768 at ./init-repository line 198.
	Qt::InitRepository::exe(Qt::InitRepository=HASH(0x7f97af02bf40), "git", "clone", "--no-checkout", "git://code.qt.io/qt/qt5/../qtbase.git", "qtbase") called at ./init-repository line 534
	Qt::InitRepository::git_clone_one_submodule(Qt::InitRepository=HASH(0x7f97af02bf40), "qtbase", "qt5/../qtbase.git", 0) called at ./init-repository line 408
	Qt::InitRepository::git_clone_all_submodules(Qt::InitRepository=HASH(0x7f97af02bf40), "qt5", 0, "qtbase", "qtimageformats") called at ./init-repository line 644
	Qt::InitRepository::run(Qt::InitRepository=HASH(0x7f97af02bf40)) called at ./init-repository line 655
</pre>
</details>

However, if I clone repo via `https://code.qt.io/qt/qt5.git` / change `origin` remote to it, everything works perfectly fine.
I'm not so confident, but I think `..` isn't supported for `git://`

**Comment by auchri** [comment]
@stek29 As stated in the build instructions, the correct command for cloning qt is git clone git://code.qt.io/qt/qt5.git qt5_6_2. I don't know where you got that .. from.

**Comment by stek29** [comment]
@auchri As I said, `init-repository` fails, not the initial clone.

> where you got that `..` from

It's in [`.gitmodules`](https://github.com/qt/qt5/blob/5.6/.gitmodules)

**Comment by auchri** [comment]
Yes, `git clone git://code.qt.io/qt/qt5.git qt5_6_2` should be replaced by `git clone https://code.qt.io/qt/qt5.git qt5_6_2` in [cmake/gyp](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md#qt-562-slightly-patched), [xcode](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-xcode.md#get-the-source-code-5) and [xcode old](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-xcode-old.md#get-the-source-code).

**Comment by john-preston** [comment]
@auchri git checkout 5.6 should be removed as I understand.

**Comment by auchri** [comment]
I think the correct way to do this is:

```
git clone git://code.qt.io/qt/qt5.git qt5_6_2
cd qt5_6_2
perl init-repository --branch --module-subset=qtbase,qtimageformats
...
```

**Comment by stek29** [comment]
@john-preston Yes, if you remove `git checkout 5.6` everything works fine.
Also, why is `git` used instead of `https` ?

**Comment by stek29** [comment]
6746d4ba2d0c470643ee406c99bec497ca6ed9de

**Comment by stek29** [comment]
And speaking of Qt manuals: http://wiki.qt.io/Building_Qt_5_from_Git
> First clone the top-level Qt 5 git repository: 
> <pre>$ git clone git://code.qt.io/qt/qt5.git</pre>
>or (if you're behind a firewall and want to use the https protocol):
> <pre>$ git clone https://code.qt.io/qt/qt5.git</pre>

I guess https is more secure and stable, even if it's a bit slower.

**Comment by stek29** [comment]
Also, maybe it should be changed in both documentation and travis/appveyour.

**Comment by stek29** [comment]
So, should I change it?..
