### ISSUE TITLE
Telegram MAC crashes on rollover at smiley dropdown

### ISSUE THREAD

**Issue by hirasso** [telegramdesktop/tdesktop#3202]
### Steps to reproduce
1. open telegram
2. go to chat
3. try to insert an icon from the select

### Expected behaviour
I would like to select a smiley

### Actual behaviour
Telegram crashes

### Configuration
MAC OSX 10.12.4

**Version of Telegram Desktop:**
2.92

**Used theme**:
Default

**Comment by john-preston** [comment]
@hirasso This is not Telegram Desktop, but different macOS app.

**Comment by auchri** [comment]
@hirasso https://github.com/overtake/telegram

**Comment by hirasso** [comment]
Thanks for the hint! :)

**Comment by stek29** [comment]
@auchri @hirasso Btw, Swift beta bugs should be reported at [@macswift](https://t.me/macswift)

**Comment by hirasso** [comment]
@stek29 thanks
