### ISSUE TITLE
[feature improvement] Improve the sticker-emoji relationship

### ISSUE THREAD

**Issue by oxydron** [telegramdesktop/tdesktop#3204]
With that last update, we got a better window to manage stickers, emojis and gifs, which is great.
But, when you choose a **emoji**, behind the main window appears **stickers window** related to the currently choosen emoji.

![telegram](https://cloud.githubusercontent.com/assets/331134/24663336/fce63aa8-192d-11e7-8d4d-ea913e38beb5.jpg)

A - You choose a emoji.
B - Write the emoji on the input area.
C - Sticker-related window appears behind the main window.

Maybe **join both windows in a single one** would be nicer. For example, while you hover your mouse on an emoji, you get on the side every sticker linked with this emoji.

Another thing that would be nice is emoji/sticker recommendation while type, based on your words.

**Comment by john-preston** [comment]
1. It won't fit well in a small window :(

2. If you decide to show them over the emoji panel (for example to the left of the emoji) you'll get problems when you want to move mouse to the emoji which is to the left of the current - it will be overflown by stickers suggestions.

If you decide to show them to the left of the whole emoji panel you won't be able to get your mouse there - while you move the mouse through the emoji between yours and stickers suggestions they'll change to the ones you've moved through.

I don't see the design to implement that nicely and consistently, sorry.

**Comment by oxydron** [comment]
> I don't see the design to implement that nicely and consistently, sorry.
Can't believe that on the telegram desktop team don't have designers to solve this problem.
And without any exchange of ideas the issue is already closed with a *wontfix* label.
Very nice.

**Comment by john-preston** [comment]
If there will be an issue with a solid proposal that will be approved to be implemented in tdesktop by the team, it will stay opened until implemented or decided not to.

**Comment by oxydron** [comment]
I thought that unify two correlated windows would be a *solid proposal*, but as you say, the current state is better.

**Comment by john-preston** [comment]
@oxydron There is no problem in uniting the windows, but you can't suggest stickers when you put mouse over emoji instead of when you click on it, because it will interrupt your emoji selection.

**Comment by oxydron** [comment]
@john-preston 
> There is no problem in uniting the windows, but you can't suggest stickers when you put mouse over emoji instead of when you click on it, because it will interrupt your emoji selection.

Ok, agreed with you. Two suggestions then:
1. Keep as it is, but only show the sticker recommendations if the stickers/gif/emoji window is closed
2. Rethink this part of the interface and create a better UX in another way you guys see fit.

Best regards :)

**Comment by john-preston** [comment]
@oxydron Thanks for your feedback.
