### ISSUE TITLE
Up key event in chat opens edit view for wrong message

### ISSUE THREAD

**Issue by gudvinr** [telegramdesktop/tdesktop#3205]
### Steps to reproduce
1. Send message from tdesktop
2. Switch to another client and send messages from it
3. Try to press `Up` in chat window to edit message.

### Expected behaviour
TG should open edit view for _last_ sent message.

### Actual behaviour
TG opens edit view for last message that was sent _from this desktop_ even if there are more messages in chat.

### Configuration
**Operating system:** Ubuntu 16.04

**Version of Telegram Desktop:** 1.0.28 alpha

### Screenshot
![2017-04-04 18 22 32](https://cloud.githubusercontent.com/assets/1712806/24665304/ab1013d8-1965-11e7-8ff5-6a50cd368b27.png)

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#2454
