### ISSUE TITLE
Search over members list

### ISSUE THREAD

**Issue by AmirBahrami** [telegramdesktop/tdesktop#3206]
### Steps to reproduce
1. Place an input for search in group profile
2. Search for users in members list

### Expected behaviour
I'd like to search among users shown in groups members list.
Currently the list shows members ahead although a filter on this list would be desirable.
Regards!

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
API issue, sorry.

**Comment by AmirBahrami** [comment]
You're right @stek29; A local search fits to work!

**Comment by john-preston** [comment]
@AmirBahrami It can be done locally for a small amount of group members, but not for large supergroups. I'm not sure it will be good if this search will disappear when the members count exceeds 200 (current per-page limit), when it is needed the most :(

**Comment by AmirBahrami** [comment]
@john-preston Yes, it works for small groups otherwise it will cost and not user friendly... so with this, the only solution seems to be an API update. Do you think it could be achieved soon?

**Comment by john-preston** [comment]
@AmirBahrami I'm afraid not.

**Comment by AmirBahrami** [comment]
@john-preston Thanks for it. :ok_hand: :blush:
