### ISSUE TITLE
```code block```

### ISSUE THREAD

**Issue by legit** [telegramdesktop/tdesktop#3207]
Hey!
Not sure if it's meant to be like this:
https://streamable.com/qyle1
I'm using the latest (alpha) version.
( ``` for every line)

**Comment by Aokromes** [comment]
you cannot use  ```  on start and on end instead on every line?

**Comment by stek29** [comment]
@Aokromes try sending a message with ``` on start and on end, and then edit the message.

**Comment by auchri** [comment]
Duplicate #2179
