### ISSUE TITLE
Add UI to lock the button to send voice messages

### ISSUE THREAD

**Issue by diazbastian** [telegramdesktop/tdesktop#3208]
### Steps to reproduce
1.  Select a chat
2.  Press and hold the microphone icon to record a voice message
3.  Drop to send voice message or drag out to cancel

### Expected behaviour
Assuming that desktop computers have OS that allow multitasking, in many cases it is very useful to be able to lock the voice message recording button to perform another task. The current interface is for multitouch interface and even in such devices (laptop with touch screen, hybrids, etc.) is not very practical.
Alternatively it was proposed to add keyboard shortcuts (#1060) with this functionality, but it is an access that only advanced users use.

### Actual behaviour
Currently there is a unique method that requires active attention from the user.

### Proposal
An alternative way to solve this problem is to add a double click function.
• Double click to start recording and lock it
• Double click to stop and send the recording
• When initiating this method a button should appear to cancel the voice message near the recording button.

This is also functional if you add the experimental video message function in TDesktop 😜.

### Configuration
**Operating system:** Fedora 25 XFCE 64 bit

**Version of Telegram Desktop:** 1.0.28 alpha

**Used theme**: Default

Note: In order not to open another report, I imagine it is in your to-do list to update the interface and animations of voice messages to something similar to what you see on Android or iOS.

![screenshot_2017-04-04-13-39-58](https://cloud.githubusercontent.com/assets/5126124/24679545/7321e316-195b-11e7-9a35-85ee2af09b2c.png)

**Comment by stek29** [comment]
Won't #1060's Voice messages section solve this?

**Comment by diazbastian** [comment]
@stek29 Of course not and I mention it in the same report.
The keyboard shortcuts are an additional access that only use advanced users. Additionally you cann't effectively use shortcuts on virtual keyboards or on hybrid devices (tablet mode) trying to take advantage of multitasking.

**Comment by ralesk** [comment]
I'm not sure what would be the most comfortable or if it is even normal on desktop...  But clicking and holding doesn't seem like a normal action with a mouse, unless you're drag&dropping.

I would say, a single click to start/send/cancel is perfectly fine.  It is a very different event from touch (it is probably exposed separately on the various supported desktop OSes too), with different mechanics, and different user expectations.  It is okay if it behaves differently from touch-oriented app editions.

I guess the button could morph into two buttons (send and cancel) once clicked.

**Comment by stek29** [comment]
@ralesk or morph to listen/cancel/send once stopped

**Comment by haevalencia** [comment]
@ralesk I agree with you, maybe the proposal is to maintain a familiar interface. In any case the area of the voice messages has been improved a little and to some very interesting improvement reports here. Perhaps when the calls arrive to Telegram Desktop the voice messages will also gain more controls.

**Comment by diazbastian** [comment]
I see that in Android beta devs added a method to perform the same function (touch interface), but the idea of the function is there.

![newlockrecorderandroid](https://cloud.githubusercontent.com/assets/5126124/25152785/92703d5c-2460-11e7-9b71-9c585246d020.png)

**Comment by ryukinix** [comment]
There is someone working on that? I would try something if anyone is doing this already.

**Comment by maxiv** [comment]
When record long message, is very uncomfortable to hold the microphone button.

**Comment by TrayHard** [comment]
Finally ffs please let us don't hold lmb on voice icon while making audio message, it's insane. Even on mobile version it's solved, please do it for desktop too!

**Comment by donkeystep** [comment]
Agree, one case - it causes issues with bot working with voice messages - users have to only use mobile, because they can't hold the button for minutes.

**Comment by anacondaq** [comment]
Almost 3 years gone, where is the solution?

**Comment by exegg** [comment]
Incredible how this hasn't been implemented in years.

**Comment by Aokromes** [comment]
pull request are welcomed :P

**Comment by ralesk** [comment]
Haha right yeah, people are Qt/C++ programmers :joy:  I'm pretty sure you could have come up with a better reaction.

Let's rephrase the problem at hand: 3 years and not even a single interaction from the dev account on this issue.

**Comment by dany-on-demand** [comment]
My temporary fix is to turn on the windows click-to-hold accessibility feature. It's annoying but it works until this or #1060 gets closed

**Comment by WilsonNet** [comment]
> 
> 
> My temporary fix is to turn on the windows click-to-hold accessibility feature (""ClickLock"") for the duration of the recording. It's annoying but it works until this or #1060 gets closed

I'm also using this. Really looking forward to this feature.

**Comment by dany-on-demand** [comment]
> > My temporary fix is to turn on the windows click-to-hold accessibility feature (""ClickLock"") for the duration of the recording. It's annoying but it works until this or #1060 gets closed
> 
> I'm also using this. Really looking forward to this feature.

Hi, thanks for the support, but please use the "thumbs up" reaction next time. It's what they were added for as comments like this are just spam & in larger repos may get removed

**Comment by fracol** [comment]
Any update? Amazed that 3rd Party Telegram apps have this option (e.g. Unigram) but the official Telegram app doesn't.

**Comment by GlitchOwl** [comment]
Still waiting

**Comment by veronikazaglotova** [comment]
So no head?

**Comment by InExtremaRes** [comment]
I don't know when was this feature released but in version 2.5.1 (I'm on Linux) if I press the mic button a new icon appears on top of it, just moving the cursor to that icon (that is, moving the cursor upwards) and releasing the button locks the recording until it's manually stopped.

So thank you very much for that. I suppose then this issue can be closed?

**Comment by dany-on-demand** [comment]
@ilya-fedin @john-preston issue can be closed
