### ISSUE TITLE
Bypass channel blocked by pornographic content

### ISSUE THREAD

**Issue by DaniLabs** [telegramdesktop/tdesktop#3209]
### Steps to reproduce
1. Right click over a channel "Open Chat" and you will show the message.
"This channel is blocked because it was used to spread pornographic content."
2. Right click over a channel "Open Conversation in a separate window".
3. You can read and search any content into the channel.

### Expected behaviour
You must be the message "This channel is blocked because it was used to spread pornographic content". The behaviour must be the same as option "Open Chat" and block the channel.

### Actual behaviour
You can read and search any content into the channel blocked

### Configuration
**Operating system:**
OS X El capitan 10.11.6
**Version of Telegram Desktop:**
Telegram Messenger client for macOS Version 2.30.51438

**Comment by auchri** [comment]
This is not Telegram Desktop, but different macOS app.

Bugs should be reported at [@macswift](https://t.me/macswift)

**Comment by stek29** [comment]
@DaniLabs 2.30.X is written in ObjC and won't be updated anymore. I recommend you to try Swift version, and report the bug if issue persists (at chat linked by @auchri)
I won't recommend you to report bugs for 2.30 versions at [@macswift](https://t.me/macswift). Developer would definitely read it, but it's better to report them through support or at overtake/telegram.
