### ISSUE TITLE
Sending messages containing hashtags crashes Telegram

### ISSUE THREAD

**Issue by thomasjmathew** [telegramdesktop/tdesktop#3211]
### Steps to reproduce
1. In any chat or group, type a message containing a hashtag (can be at any point in the message)
2. Press send/enter key

### Expected behaviour
The message should send and Telegram app should not crash.

### Actual behaviour
Message does not send, and app instantly crashes. I can, however, edit a message to include a hashtag after sending, and this does not crash the app.

### Configuration
**Operating system:** Windows 10 Pro 1607

**Version of Telegram Desktop:** 1.0.27

**Comment by Aokromes** [comment]
cannot reproduce on 1.0.28
http://i.imgur.com/08SGDWu.png

**Comment by auchri** [comment]
I also cannot reproduce this issue.

@thomasjmathew Can you provide an example of such message?

**Comment by thomasjmathew** [comment]
I'm now on version 1.0.29 and can no longer reproduce. Seems like this was a local issue or the bug got fixed?

**Comment by eggzon** [comment]
Convert object data that you send into `encodeURIComponent`

e.g var telegramText = "hello"


https://api.telegram.org/bot${token}sendMessage?chat_id=${chatId}&text="+encodeURIComponent(text);
