### ISSUE TITLE
Systray not working as expected and as it used to (KDE4)

### ISSUE THREAD

**Issue by ijpulidos** [telegramdesktop/tdesktop#3213]
Since a couple of updates ago, when I click the systray icon telegram-desktop doesn't minimize or becomes focused, so the whole point of minimizing to systray becomes useless.

### Expected behaviour
I expect that when I click the systray icon the telegram-desktop the window of it appears or get minimized as the common normal behaviour of systray icons.

### Actual behaviour
Clicking the systray icon is not doing anything.

### Configuration
**Operating system:**
Debian linux 8 KDE4

**Version of Telegram Desktop:**
1.0.27

**Used theme**:
Default

**Comment by auchri** [comment]
Please try 1.0.28 alpha version from https://github.com/telegramdesktop/tdesktop/releases

**Comment by john-preston** [comment]
@ijpulidos Please check out the latest stable version 1.0.29 from https://desktop.telegram.org, I hope it has this issue fixed.

**Comment by ijpulidos** [comment]
Working as expected in 1.0.29, thanks!
