### ISSUE TITLE
New tray icon too small on HiDPI display

### ISSUE THREAD

**Issue by kmare** [telegramdesktop/tdesktop#3216]
### Steps to reproduce
Update to 1.0.29 on fedora 25, 4K display

### Expected behaviour
The tray icon and the menu should scale up like the rest of the gui.

### Actual behaviour
The tray icon is too small.

### Configuration
**Operating system:**
Fedora 25
**Version of Telegram Desktop:**
1.0.29
**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>
The Qt tray icon doesn't appear to support HiDPI displays. It was working fine before. Now the icon itself and the menu is kinda tiny.

</details>

**Comment by jkw** [comment]
Example picture showing **Keybase**, **Telegram** and **Pamac**.

![Telegram Linux](https://user-images.githubusercontent.com/388872/28499261-e6ac3032-6fb1-11e7-9409-794fe14055c5.png)

Running on Gnome, 3200x1800 resolution.

**Comment by kmare** [comment]
Yeah, have the exact same problem. Should have provided a screenshot too, thanks.

**Comment by ElvisPresly** [comment]
Ubuntu 16.04
![2017-08-23 19-11-40](https://user-images.githubusercontent.com/18265958/29626294-f0fbed0a-8836-11e7-9652-20bace3cd272.png)

**Comment by ElvisPresly** [comment]
![2017-08-23 19-12-43](https://user-images.githubusercontent.com/18265958/29626334-0ee1cf9c-8837-11e7-8667-323504ab57de.png)

**Comment by auchri** [comment]
@ElvisPresly That looks really awful!

**Comment by stek29** [comment]
@ElvisPresly #2230

**Comment by skunkcla** [comment]
here's my screenshot on linux mint with cinnamon
![telegram_icon](https://user-images.githubusercontent.com/19750119/29739991-7d255354-8a4c-11e7-82ec-3d818310e164.png)

**Comment by stek29** [comment]
That Dropbox icon tho

**Comment by ElvisPresly** [comment]
Deepin 15.5
![deepinscreenshot_ - _20171110145910](https://user-images.githubusercontent.com/18265958/32657704-c24de380-c627-11e7-958d-d4691973f5cf.png)

**Comment by jfkpdq** [comment]
News on this?

**Comment by Pastafarianist** [comment]
![image](https://user-images.githubusercontent.com/1315874/36489574-7163e1de-1737-11e8-9561-a59620b48096.png)
Latest Manjaro Gnome.

**Comment by kmare** [comment]
Still happening with Fedora 27, Gnome 3.26 on Asus Zenbook UX501VW 4K HiDPI screen. Telegram version 1.2.6.

**Comment by davidrolle** [comment]
Same issue on Mint 18.3 with 4K screen (Dell XPS 15)

**Comment by mimecry** [comment]
getting a low-res tray icon on Arch Linux as well (14" 1440p @ 1.5 scaling)

without unread msg count:

![without unread message count](https://i.imgur.com/Rt1g3fJ.png)

with unread msg count:

![without unread message count](https://i.imgur.com/AQBafhg.png)

**Comment by wunderlich** [comment]
I can confirm this issue using Linux Mint 19.2 on a Thinkpad X1 Yoga 4th Gen with a 14" 4K Display.

![grafik](https://user-images.githubusercontent.com/4471366/62461483-4359c200-b785-11e9-81f5-353c868e98d8.png)

Isn't it possible to replace the PNG-Icons with SVG-Icons?

**Comment by circlenaut** [comment]
I can confirm this is an issue in 1.8.4 under Solus 4-current as well

**Comment by pioneer** [comment]
Confirming on Manjaro Cinnamon current.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/3b4dfa138176b4d1e3cb14be1be638ebe2f52713
