### ISSUE TITLE
Hide Text in Markdown [test](teste.img)

### ISSUE THREAD

**Issue by p1rralho** [telegramdesktop/tdesktop#3218]
Hello, I want to post on my channel image using bot, but I would like to hide the word "text" below:
[Text](http://www.teste.com/android1.png)
If I post using this form above, the person can still see the image link by placing the mouse over the "text" page.

Follows an example of how I usually post:
https://s2.postimg.org/vs27671jt/upload1.png

-----------------

Android android [Text](http://www.teste.com/android1.png)
$ 50
Link product: teste.com/1234

**Comment by stek29** [comment]
API issue, Server doesn't accept links in formatting from client​.
