### ISSUE TITLE
Sticker's short desc, search by them and preview

### ISSUE THREAD

**Issue by Nashev** [telegramdesktop/tdesktop#3222]
### Steps to reproduce
1. Decide You need post some sticker to chat
2. Open emoji button, switch to stickers
3. Look at list
4. Post some of them and see in chat list on the left to last message preview.

### Expected behaviour
I must see original size preview of sticker which I pointed by mouse and they caption (like in Skype). Also I must have field to type partial caption and have sticker list filtered by captions. When I send it, in chat list's last message preview I prefer to see this sticker's caption after emoji and "Sticker: " note.

### Actual behaviour
I see long scrollable list of unreadable thumbnails to try recognize what is there painted and written and I stay annoyed and irked
When I send one of them, I will have in chat list's item my sent sticker as some small emoji with just 'Sticker' caption.

### Configuration
Windows 7, Telegram Desktop 1.0.29
![telegram](https://cloud.githubusercontent.com/assets/190140/24789637/f8f7a64e-1b84-11e7-9473-e4c479c7ca3e.png) ![skype](https://cloud.githubusercontent.com/assets/190140/24789638/f8f9c12c-1b84-11e7-9929-d103c2316041.png)

**Comment by auchri** [comment]
No api for this.

**Comment by Nashev** [comment]
Hey! No API for what???

Is a large preview impossible?

May be caption is impossible through API, may be, but some one may be can forward this feature request to API team?

**Comment by auchri** [comment]
Just long click on the sticker to get a larger preview.
