### ISSUE TITLE
build qt error

### ISSUE THREAD

**Issue by kenan2677** [telegramdesktop/tdesktop#3226]
===========USE CMD===============
configure -debug-and-release -force-debug-info -opensource -confirm-license -static -I "C:\TBuild\Libraries\openssl\Release\include" -L "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Lib" -l Gdi32 -no-opengl -openssl-linked OPENSSL_LIBS_DEBUG="C:\TBuild\Libraries\openssl_debug\Debug\lib\ssleay32.lib C:\TBuild\Libraries\openssl_debug\Debug\lib\libeay32.lib" OPENSSL_LIBS_RELEASE="C:\TBuild\Libraries\openssl\Release\lib\ssleay32.lib C:\TBuild\Libraries\openssl\Release\lib\libeay32.lib" -mp -nomake examples -nomake tests -platform win32-msvc2015

=============ERROR=================
c:\tbuild\libraries\qt5_6_2\qtbase\include\qtcore\../../src/corelib/tools/qsco
dpointer.h(39) : fatal error C1083: 无法打开包括文件:“stdlib.h”: No such fil
or directory (C:\TBuild\Libraries\qt5_6_2\qtbase\tools\configure\configureapp.
p)
c:\tbuild\libraries\qt5_6_2\qtbase\include\qtcore\../../src/corelib/tools/qsco
dpointer.h(39) : fatal error C1083: 无法打开包括文件:“stdlib.h”: No such fil
or directory (C:\TBuild\Libraries\qt5_6_2\qtbase\tools\configure\environment.c
)
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 1
0\VC\bin\cl.EXE"”: 返回代码“0x2”
Stop.

**Comment by stek29** [comment]
> stdlib.h: No such file or directory
Do you have Windows sdks installed (or what's the proper way to get minimal working compiler + stdlib + headers on Windows)

**Comment by kenan2677** [comment]
=========NOW ERROR==============

C:\TBuild\Libraries\qt5_6_2\qtbase\tools\configure\configureapp.cpp: fatal error
 C1853: “configure_pch.pch”预编译头文件来自编译器的早期版本，或者预编译头为 C+
+ 而在 C 中使用它(或相反)
environment.cpp

**Comment by auchri** [comment]
Stop creating duplicate issues 

-> https://github.com/telegramdesktop/tdesktop/issues/3227

**Comment by kenan2677** [comment]
@stek29 

=========NOW ERROR==============

C:\TBuild\Libraries\qt5_6_2\qtbase\tools\configure\configureapp.cpp: fatal error
C1853: “configure_pch.pch”预编译头文件来自编译器的早期版本，或者预编译头为 C+

而在 C 中使用它(或相反)
environment.cpp

**Comment by kenan2677** [comment]
===========ERROR===========
C:\TBuild\Libraries\qt5_6_2\qtbase\tools\configure\configureapp.cpp: fatal error C1853: 'configure_pch.pch' precompiled header file is from a previous version of the compiler, or th
e precompiled header is C++ and you are using it from C (or vice versa)

**Comment by kenan2677** [comment]
@stek29 pls help me~~ im crying....

**Comment by auchri** [comment]
@kenan2677 Which version of visual studio do you use?

**Comment by kenan2677** [comment]
@auchri VS2015

===============NOW ERROR================
Unable to determine cl version from the output of "C:\Windows\system32\cmd.exe /
c cl.exe /? 2>&1"
Unknown option e-nomake

**Comment by auchri** [comment]
@kenan2677 Do you use the ** VS2015 x86 Native Tools Command Prompt.bat** ?

**Comment by kenan2677** [comment]
no，I use "cmd+r" and input cmd.exe to start cmd window~

**Comment by kenan2677** [comment]
@auchri now,i'm using VS2015 x86 Native Tools Command Prompt.bat

===============NOW ERROR STILL================
Unable to determine cl version from the output of "C:\Windows\system32\cmd.exe /
c cl.exe /? 2>&1"
Unknown option e-nomake

**Comment by kenan2677** [comment]
C:\TBuild\Libraries\qt5_6_2>where cl.exe

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe

**Comment by kenan2677** [comment]
@auchri please help me ~~ crying~~

**Comment by kenan2677** [comment]
done ~~~ @stek29 thks @auchri thks~
