### ISSUE TITLE
nmake qt 5.6.2 error

### ISSUE THREAD

**Issue by kenan2677** [telegramdesktop/tdesktop#3229]
i use nmake to make qt

==============ERROR SAID=============
QtBootstrapd.lib(qbytearray.obj) : error LNK2019: 无法解析的外部符号 _z_uncompre
ss，该符号在函数 "class QByteArray __cdecl qUncompress(unsigned char const *,int
)" (?qUncompress@@YA?AVQByteArray@@PBEH@Z) 中被引用
..\..\..\bin\moc.exe : fatal error LNK1120: 2 个无法解析的外部命令
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 14.
0\VC\BIN\link.EXE"”: 返回代码“0x460”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 14.
0\VC\BIN\nmake.EXE"”: 返回代码“0x2”
Stop.

**Comment by kenan2677** [comment]
who can help me?

**Comment by stek29** [comment]
Have you built zlib?

**Comment by kenan2677** [comment]
@stek29 I have done for the nmake~  Windows SDK I forget to install....... 55555~~~ thanks~

**Comment by youncoo** [comment]
@kenan2677 老铁，你装的什么windows sdk解决的

**Comment by kenan2677** [comment]
就是说明里的sdk发自我的iPhone------------------ Original ------------------From: youncoo  <notifications@github.com>Date: 周三,9月 13,2017 18:19To: telegramdesktop/tdesktop <tdesktop@noreply.github.com>Cc: kenan2677 <kenan2677@126.com>, Mention <mention@noreply.github.com>Subject: Re: [telegramdesktop/tdesktop] nmake qt 5.6.2 error (#3229)@kenan2677 老铁，你装的什么windows sdk解决的

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/telegramdesktop/tdesktop","title":"telegramdesktop/tdesktop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/telegramdesktop/tdesktop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@youncoo in #3229: @kenan2677 老铁，你装的什么windows sdk解决的"}],"action":{"name":"View Issue","url":"https://github.com/telegramdesktop/tdesktop/issues/3229#issuecomment-329124428"}}}

**Comment by youncoo** [comment]
@kenan2677 能不能详细说下是哪个库
