### ISSUE TITLE
Unexpected error during build

### ISSUE THREAD

**Issue by m3nukim** [telegramdesktop/tdesktop#3231]
### Steps to reproduce
1. get Timer.h and Timer.cpp from github repository 
2. switched these with local files.
3. 

### Expected behaviour
Tell us what should happen

successful make build

### Actual behaviour
Tell us what happens instead

I followed all of procedure without any mistakes. And I did some fixes from "https://github.com/Helias/tdesktop/commit/5b5c60868f30dac919497dc1401e0abae6ea4771" (line number 196~209)

But, error came out during "make". Here is an error i got during build. It happens both debug and release build. 

[ 42%] Building CXX object CMakeFiles/Telegram.dir/home/menukim/TBuild/tdesktop/Telegram/SourceFiles/base/timer.o
In file included from /home/menukim/TBuild/tdesktop/Telegram/SourceFiles/base/timer.cpp:21:0:
/home/menukim/TBuild/tdesktop/out/Debug/../../Telegram/SourceFiles/base/timer.h:87:19: error: ‘base::Timer::_repeat’ is too small to hold all values of ‘enum class base::Timer::Repeat’ [-Werror]
  Repeat _repeat : 1;
                   ^
cc1plus: all warnings being treated as errors
CMakeFiles/Telegram.dir/build.make:1098: recipe for target 'CMakeFiles/Telegram.dir/home/menukim/TBuild/tdesktop/Telegram/SourceFiles/base/timer.o' failed
make[2]: *** [CMakeFiles/Telegram.dir/home/menukim/TBuild/tdesktop/Telegram/SourceFiles/base/timer.o] Error 1
CMakeFiles/Makefile2:523: recipe for target 'CMakeFiles/Telegram.dir/all' failed
make[1]: *** [CMakeFiles/Telegram.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

### Configuration
**Operating system:**
Ubuntu 16.04 LTS (On Virtualbox)
**Version of Telegram Desktop:**
I don't know exactly. I cloned source from github.
**Used theme**:

**Comment by john-preston** [comment]
@m3nukim The dev branch is broken right now :( you can use master.

**Comment by m3nukim** [comment]
@john-preston Thank you very much. I will retry with master :)
