### ISSUE TITLE
Forbid non-priveleged users to invite bots

### ISSUE THREAD

**Issue by Civil** [telegramdesktop/tdesktop#3235]
At this moment any user invite any bot to the group.

Some of them are very annoying, e.X. Bank bots, Pokemon go bots. It's also hard to identify and ban the person who did that. And the bot controls will remain even after you ban the bot.

I suggest to forbid non-priveleged users to invite bots to the groups.

**Comment by cobalto** [comment]
It's probably an API thing, but will like it anyway because I've already suffered with it.

**Comment by stek29** [comment]
API issue.

**Comment by mymedia2** [comment]
There is a [bot][1] which can ban other new bots.

[1]: https://t.me/GroupButler_bot

**Comment by Civil** [comment]
But those bots will be able to add their controls to all users before they get banned. This doesn't solve the problem.

**Comment by Civil** [comment]
@auchri why you've closed this issue? The problem is still there, it's not fixed.

**Comment by stek29** [comment]
@Civil because it's the issue of Telegram (Server Side) and not of Telegram Desktop app. 
You can request it via Twitter or using "Ask a question" button in settings
