### ISSUE TITLE
a tips for windows readme file~

### ISSUE THREAD

**Issue by kenan2677** [telegramdesktop/tdesktop#3237]
In the last section "Build the project" of the readme file .

please add this:
copy D:/TBuild/ninja/ninja.exe to C:\Program Files (x86)\Microsoft Visual Studio 14\VC\bin\

overwise can't build project~

**Comment by john-preston** [comment]
@kenan2677 You don't need to copy ninja there, you need to have it in your PATH.

**Comment by kenan2677** [comment]
@john-preston ah~~ the same~  author forget to wirte this.

**Comment by auchri** [comment]
@kenan2677 

You should read the instructions more carefully, it's mentioned there: https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md#setup-gypninja-and-generate-vs-solution

**Comment by arieljannai** [comment]
@auchri If you mean that it mentioned by this row
> SET PATH=%PATH%;D:\TBuild\Libraries\gyp;D:\TBuild\Libraries\ninja;
so it only sets the path for the current command line session, which made (also me) think it's just for the `gyp\refresh` command
