### ISSUE TITLE
Debug in Telegram macOS

### ISSUE THREAD

**Issue by sooohaib** [telegramdesktop/tdesktop#3239]
Hi, could someone please clarify how to enable `debugmode` using Telegram for macOS. 

I have tried to follow this but no luck: [https://telegram.wiki/desktop/tdesktopdebugmode](https://telegram.wiki/desktop/tdesktopdebugmode )

Many Thanks! 

### Configuration
**Operating system:** macOS

**Version of Telegram Desktop:** Version 2.30.51438

**Comment by john-preston** [comment]
@sooohaib This is not Telegram Desktop, this is another macOS application. You can try Telegram Desktop from https://desktop.telegram.org

**Comment by sooohaib** [comment]
Excellent. Thank you. Worked first time. 

Where would I be able to find the debug logs from here onwards?

**Comment by john-preston** [comment]
@sooohaib "~/Library/Application Support/Telegram Desktop/Debug Logs"

**Comment by sooohaib** [comment]
Thank you. I cant seem to see the Telegram Desktop folder in there. 

When i do `debugmode` in Telgram, I get the message and I do click OK. 

Is there something I am missing?

**Comment by john-preston** [comment]
It should be there. It is not "/Library/Application Support", but "~/Library/Application Support".

**Comment by sooohaib** [comment]
Thank you so much John! 

I am trying to follow this: [https://telegram.wiki/desktop/tdesktopcountingmessages](https://telegram.wiki/desktop/tdesktopcountingmessages)

I cant seem to find `count` in the mtp logs. Any ideas?

Thanks,

**Comment by john-preston** [comment]
When you open chat with someone you'll see a request like this in logs:
```
msg_id: 6406626961577351860 [LONG],
seq_no: 65 [INT],
bytes: 44 [INT],
body: { messages_getHistory
  peer: { inputPeer...
    ...
  },
  offset_id: ... [INT],
  offset_date: 0 [INT],
  add_offset: 0 [INT],
  limit: 50 [INT],
  max_id: 0 [INT],
  min_id: 0 [INT],
},
```
And after that there'll be a response like this:
```
msg_id: 6406626954423127041 [LONG],
seq_no: 67 [INT],
bytes: 8224 [INT],
body: { rpc_result
  req_msg_id: 6406626961577351860 [LONG],
  result: [GZIPPED] { messages_messagesSlice
    count: 14099 [INT],
    messages: [ vector<0x0>
      { message
        ...
  ...
```
You can find it using `msg_id` from the request.

**Comment by sooohaib** [comment]
Brilliant. Thank you so much. 

Does this number show the number of messages I have sent? or does it show the total in the whole conversation?

**Comment by john-preston** [comment]
The total.
