### ISSUE TITLE
Link to gif is displayed in message windows when copied from external source

### ISSUE THREAD

**Issue by omerasif57** [telegramdesktop/tdesktop#3242]
### Steps to reproduce
1. Copy link to a gif.
2. Paste in chat box. Enter 
3. Link shows up with the gif in message window.

### Expected behaviour
Link should not be displayed

### Actual behaviour
Link is displayed with gif
### Configuration
**Operating system:**
Windows 7

**Version of Telegram Desktop:**
Telegram Desktop
**Used theme**:
Visual Pastel Green theme
<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@omerasif57 This is expected. When you copy a link to a gif you simply see a link preview in a message that contains that gif. There is no plans to change that behaviour.

**Comment by omerasif57** [comment]
Alright. 
According to a friend Skype does not show the gif link when pasted. So we were thinking the same for Telegram, if it can be easily implemented. seems to be more neat, in my opinion. Because user is only concerned with the gif so pasting link (OR link preview) would be unnecessary.

**Comment by john-preston** [comment]
@omerasif57 You can;t know for sure, he can be wishing to send the link really.

**Comment by omerasif57** [comment]
okay!
