### ISSUE TITLE
Don't notify each message

### ISSUE THREAD

**Issue by 5ulo** [telegramdesktop/tdesktop#3244]
### Steps to reproduce
1. send message
2. send next message in 2s
3. send next message in 5s
4. send next message in next 5s
5. -- || --
6. you got the point - each message from the same "talky" user is notified

### Expected behaviour
I miss an option to group these notifications like "Don't notify each message if the last message was received e.g. 30s before or 60s etc". There are many people that have bad habbit to write two words and send it.. next two words and send it.. My head goes boom from the notify sound played allover and again.

### Actual behaviour
The notification sound is repeated for each message (which is okay).

### Configuration
**Operating system:** Arch Linux + Gnome Shell

**Version of Telegram Desktop:** 1.0.29

**Comment by stek29** [comment]
#429
