### ISSUE TITLE
too many files in tdata

### ISSUE THREAD

**Issue by ruv** [telegramdesktop/tdesktop#3246]
Why don't you use sub-tree directories structure for cache?
Too many files in one directory affects the application performance in Windows.

### Steps to reproduce
1. Use Telegram for a long time.
2. Look in `%appdata%/Telegram Desktop/tdata/D877F783D5D3EF8C/` (the last path segment may be different).

### Expected behaviour
Up to 1000 files or sub-directories

### Actual behaviour
Many-many files in one directory, tens of thousands. For the moment about 30,000 files.

### Configuration
**Local storage**
For the moment:
-   27882 images, 521.1 MB
-   98 voice messages, 3.1 MB

**Operating system:**
Windows 7

**Version of Telegram Desktop:**
1.0.29

**Comment by john-preston** [comment]
@ruv Yes, this caching should be rewritten some day.. :(

**Comment by stek29** [comment]
@john-preston iTunes has an interesting approach: it puts files inside of directories which have name matching with first two chars of filename (filenames are sha256 hashes in that case).

Like this:
```
aa:
  aabc
  aabd
ab:
  abde
  abef
de:
  dead
```

**Comment by john-preston** [comment]
@stek29 This is the way git works.

**Comment by stek29** [comment]
@john-preston And a lot of other programs, I suppose.
But I was messing with iTunes backup when was writing that comment.

**Comment by Aokromes** [comment]
Lol ruv you made me check my tdata dir, 80.000 files 1.5GB

**Comment by auchri** [comment]
Duplicate #2391

**Comment by stek29** [comment]
@auchri that issue seems to be a bug when clear cache doesn't clear it, while this one is an enhancement, requesting to split those files into directories
