### ISSUE TITLE
./configure in msys64: ERROR: opus not found using pkg-config

### ISSUE THREAD

**Issue by Elypson** [telegramdesktop/tdesktop#3247]
Hi,

### Steps to reproduce
1. compile OPUS as in the description but to path C:\Users\elypson\Documents\vs13\Projects\Telegram\build\Libraries\opus\win32\VS2010\Win32\Release (while vs13 is a directory junction to the same path with Visual Studio 2013 as name)
2. follow those steps up to (and including) the `./configure` line: https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md#building-libraries-1 replacing

`--extra-ldflags="-libpath:/d/TBuild/Libraries/opus/win32/VS2010/Win32/Release celt.lib silk_common.lib silk_float.lib"`

with

`--extra-ldflags="-libpath:/c/Users/elypson/Documents/vs13/Projects/Telegram/build/Libraries/opus/win32/VS2010/Win32/Release celt.lib silk_common.lib silk_float.lib"` (those lib files are in this directory, I have checked)

### Expected behaviour
It should run through smoothly, so that I can run `make && make install` afterwards

### Actual behaviour
there is an error in red: ERROR: opus not found using pkg-config

### Extra information
If I remove `--enable-libopus` from the `./configure` line, it runs through fine as well as `make && make install`, although I am not sure whether this removes OPUS, then. `/mingw64/lib/pkgconfig` also contains a file `opus.pc`

### Configuration
Windows 10

Latest as of 9 April 2017

basic theme, not yet compiled Telegram so far

<details><summary>**Logs**:</summary>
I could attach the 10 KB `config.log` if helpful.

**Comment by john-preston** [comment]
Please try the latest msys2 from http://msys2.github.io/ instead of the one linked in the instructions.

**Comment by grishka** [comment]
I've managed to fix this by installing the latest version of msys2 from http://msys2.github.io/ as opposed to using the direct link from the build instructions.

**Comment by Elypson** [comment]
Thanks, this has resolved my issue 👍

**Comment by Augustu** [comment]
> Thanks, this has resolved my issue 👍

Could you send me a copy of msys2, the link above always redirect to msys2 home page... Thanks in advance. : )
