### ISSUE TITLE
Can't view messages without the Internet connection

### ISSUE THREAD

**Issue by ech2** [telegramdesktop/tdesktop#3251]
### Steps to reproduce
1. Quit Telegram Desktop.
2. Turn of the Internet connection
3. Open Telegram Desktop.

### Expected behaviour
All cached messages should be available for viewing and searching without the Internet connection.

### Actual behaviour
Blank screen without chat list and any messages with text, telling that the program is trying to reconnect to servers.

### Configuration
**Operating system:** macOS 10.12.4.

**Version of Telegram Desktop:** 1.0.29.

**Used theme**: default.

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@ech2 Actually, all cached messages are available for viewing and searching without the internet connection. The problem is — there are no cached messages, messages are not cached by Telegram Desktop. Sorry :(

**Comment by ech2** [comment]
@john-preston  Ah, that's sad, will probably switch back to the Mac-only app (which I think caches the messages). Any plans to implementing caching in this client?

**Comment by timocov** [comment]
@ech2 What about security? If somebody closed your active session you should not to have access to your messages while you offline.

**Comment by ech2** [comment]
@timocov I believe I have enough confidence to decide for myself, how should I treat my own data. I'd be perfectly contented with a disabled by default option to switch the local caching on. In general I think educating people about good security practices is better than imposing «secure» defaults on them.

**Comment by ghost1372** [comment]
any update for this?

**Comment by QGkjTIYUCw** [comment]
Hello, @john-preston 

We will assume that at me the amount of my old correspondence is 1 GiB.

Whether correctly I understand that at **each** start of **Telegram for Desktop** and viewing of all old correspondence   1 GiB of data will be downloaded from the server **every time**?

**Comment by john-preston** [comment]
@QGkjTIYUCw No. It loads as a web page, when necessary.

**Comment by QGkjTIYUCw** [comment]
@john-preston 

That's what I'm talking about.
> each start of Telegram for Desktop **and viewing of all old correspondence**

If you want to see all the old correspondence after the launch of **Telegram for Desktop**, then all the old correspondence will be needed. Therefore, it will be downloaded in its entirety (all 1 GiB). It was about this case that I asked.

I look through all old correspondence after start of **Telegram**. I need it for my work. Therefore at me all old correspondence (1 GiB) is downloaded every time after start of **Telegram**. 

Agree that this is creepy and wrong. 

This is a **big** problem. And this problem has not been solved for more than a year (from 2017-04-10)!

Would you please fix the problem as soon as possible, please? Thanks.

**Comment by john-preston** [comment]
@QGkjTIYUCw It's impossible to fix easily. But I think a lot of your 1 GB is media (files, photos etc), they're cached locally in tdesktop and are not downloaded each time. So you load only texts over and over again and I don't think you have that much texts, maybe several MB.

**Comment by TheAndrey** [comment]
I also do not have enough caching messages. Without the Internet, Telegram Desktop becomes useless.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1087
