### ISSUE TITLE
Build error in Ubuntu - <gsl/gsl>, stdafx.h

### ISSUE THREAD

**Issue by pjy0121** [telegramdesktop/tdesktop#3252]
### Steps to reproduce
1. Install
2. compile
3. failed

### Expected behaviour
Compile success

### Actual behaviour
While installing telegram desktop in Ubuntu 16.04, I encountered this problem.
I faced this problem while installing telegrams.
I was about to run the 'make' command in the tdesktop/out/debug folder according to the manual.
I don't know the mean of <gsl/gsl> header file. What's wrong??

### Configuration
**Operating system:**
Ubuntu 16.04
**Version of Telegram Desktop:**
1.0.23 maybe(I cloned it from telegramdesktop/tdesktop)

<details><summary>**Logs**:</summary>

[ 38%] Built target Telegram__qt_moc
[ 40%] Built target Telegram__codegen_style
[ 40%] Built target Telegram__update_dependent_qrc
[ 40%] Built target Telegram__codegen_scheme
[ 40%] Precompiling stdafx.h for Telegram (C++)
In file included from /home/park/Telegram/tdesktop/out/Debug/Telegram_pch/stdafx.h:61:0:
/home/park/Telegram/tdesktop/out/Debug/../../Telegram/SourceFiles/core/utils.h:27:19: fatal error: 
 No such file or directory gsl/gsl :
 #include <gsl/gsl>
                   ^
compilation terminated.
CMakeFiles/Telegram.dir/build.make:75: recipe for target 'Telegram_pch/stdafx.h.gch/.c++' failed
make[2]: *** [Telegram_pch/stdafx.h.gch/.c++] error 1
CMakeFiles/Makefile2:523: recipe for target 'CMakeFiles/Telegram.dir/all' failed
make[1]: *** [CMakeFiles/Telegram.dir/all] error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] error 2

</details>

**Comment by auchri** [comment]
Does the folder `/home/park/Telegram/tdesktop/third_party/GSL` exist?

**Comment by stek29** [comment]
@pjy0121 please make sure you cloned the repo recursively by checking if the folder @auchri noted isn't empty
If it is empty, try doing `git submodule update --init --recursive`

**Comment by pjy0121** [comment]
Yes. It was empty... Wow! Now, it runs nomally. @stek29  @auchri  Thank you for your help!

**Comment by pjy0121** [comment]
Oh no.. It was not over. This time, I encountered this issue. Do you know the solutions?

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libXi.a(XIAllowEvents.o): relocation R_X86_64_PC32 against symbol `_XGetRequest' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/Telegram.dir/build.make:11346: recipe for target 'Telegram' failed
make[2]: *** [Telegram] error 1
CMakeFiles/Makefile2:523: recipe for target 'CMakeFiles/Telegram.dir/all' failed
make[1]: *** [CMakeFiles/Telegram.dir/all] error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] error 2
```

**Comment by stek29** [comment]
I'm not sure, but maybe you're trying to build and link a dynamic library while should build static one.
I recommend you looking carefully through instructions and travis files.
