### ISSUE TITLE
Windows 10: Telegrams window is always on top

### ISSUE THREAD

**Issue by Paulomart** [telegramdesktop/tdesktop#3253]
### Steps to reproduce (I cant reproduce this myself anymore)
1. start telegram
2. go to a group chat
3. open an picture
4. leave the fullscreen view without clicking X (for example multi monitor, go to another window)
5. telegram is now always on top

### Expected behaviour
The telegram window should not stay always on top, it should go behind other windows.

### Actual behaviour
The telegram window will always stay in front of all other windows. Restarting dosent help.

### Configuration
**Operating system:** Windows10

**Version of Telegram Desktop:** 1.0.29

**Used theme**: Default

**Comment by stek29** [comment]
Should be a duplicate, but can't find original report now

**Comment by viruslab1** [comment]
I have similar problem to. Its jast always on top.

**Comment by garrafote** [comment]
This is super annoying.. is there a workaround?

**Comment by stek29** [comment]
@garrafote revert to anniversary update?

**Comment by garrafote** [comment]
@stek29 I managed to fix it by closing telegram from the tray icon and reopening. 

Also, I tried but could not reproduce the error as described by @Paulomart after I restarted telegram. There seem to be other factors involved in this issue.

**Comment by PrzemekBurczyk** [comment]
This happens for ma after every system restart. I need to close telegram from the tray icon and reopen every time to fix it.

Telegram version 1.0.29
Windows 10 version 1607

**Comment by Zaitypola** [comment]
Closing from the tray as mentioned above worked for me. Thanks

**Comment by TheMprs** [comment]
i solved it by right clicking telegram and quitting it and reopening

**Comment by sebvance** [comment]
I also had this issue on the latest Win10 Creator's Update, and quitting Telegram/restarting resolved it. I was disappointed to find that Telegram didn't have an Always On Top mode.

**Comment by PietsHost** [comment]
this issue still exists... any news on fixing this?

**Comment by wwevo** [comment]
Can confirm, the problem still exists. I have to tray-close Telegram after almost every Windows-restart.

**Comment by mtakala** [comment]
Issue still exists. I have resorted to just not using Telegram on my PC because of this.

**Comment by Feloot** [comment]
Can confirm, and it is really annoying.

**Comment by Azazavr** [comment]
Have the same problem...

**Comment by cod7alex** [comment]
Same for me

**Comment by wwevo** [comment]
I seem to only get it when I auto-start Telegram minimized. It's a bit annoying to close the window after boot, but it's better than having that window covering stuff.

**Comment by auchri** [comment]
Anyone found a way to reproduce this yet?

**Comment by cod7alex** [comment]
@auchri able to reproduce right now with steps from #4056 (basically only step is to start my pc)

**Comment by auchri** [comment]
I'm doing this steps multiple times a months on pysical pc's and on vm's and I'm never experienced that issue 🤷‍♀️
Maybe your windows is kind of broken? Did you try a fresh install of windows.

**Comment by cod7alex** [comment]
but i am not the only one, see above

**Comment by auchri** [comment]
@cod7alex Without instructions to reproduce the error I can't help you, sorry 🤷‍♀️

**Comment by Feloot** [comment]
It doesn't happen to me anymore... I guess it must have been a system update or something

**Comment by lazychaser** [comment]
Same thing. I can't even see attached pictures because telegram is on top on even it's child windows

**Comment by MikePerreman** [comment]
Still happens to me

**Comment by wwevo** [comment]
to me as well, nothing has ever changed since i first reported this ^^

**Comment by Woofard** [comment]
It's not fixed and his Windows is not broken. This is an absolutely annoying app. Yeah, decentralized and private. Cool. The pesky'ness of the app quickly makes you forget it. Shouldn't have to close and open it just to get it running correctly. In addition, there are simple html commands that return it to that behavior once a file association is made as the page loads. Come on already. It's as if it was compiled with an ego to show off...     Heyyyy! Look at me!!

**Comment by john-preston** [comment]
@Woofard What html commands are you talking about?

**Comment by levicki** [comment]
I just had this happen to me on Windows 8.1 x64 -- all of a sudden Telegram window was on top and you could not Alt-Tab to other programs. Quitting and restarting multiple times did not fix it. My Telegram is set to auto-start minimized to tray and to show on taskbar as well.

What fixed the issue for me was closing the application and deleting `tdata` folder. Bear in mind that you will have to reauthenticate and reconfigure everything when you do that.

@john-preston to me this seems as a case of corrupted configuration, but since the files are in custom format and seem encrypted (or at least compressed) there is no way to compare the bad ones with good ones.

**Comment by cod7alex** [comment]
@levicki can you share the full path to `tdata`?

**Comment by levicki** [comment]
@cod7alex I am running the portable version of Telegram so `tdata` folder is in the same folder as the application executable.

**Comment by vadimtsushko** [comment]
I have the same behavior on Ubuntu 16.04

 Closing Telegram from the tray works for me too. But it is still annoying

**Comment by EnforcerZhukov** [comment]
Got the same problem since more than a year ago, Telegram on Windows 10 now on the latest version and this still happens. I'd say it happens after opening a picture but I actually think it also happens randomly, but I'm not completely sure.

In my case closing to the tray doesn't fix the problem, I have to close the application and open it again, then it works fine.

**Comment by amrsoll** [comment]
This also happens to me on Ubuntu ...

**Comment by 29988122** [comment]
This also happens to me... : (

**Comment by xellos81** [comment]
the issue is Windows that recover latest status and reopen all the softwares
you can kill telegram from activity manager and re-open it or change the settings in windows

**Comment by MikhailGordeev** [comment]
The bug on Windows 10 still here, so sad 😞

**Comment by wwevo** [comment]
Yep, still have it as well. Across two different windows 10 installs too, changed motherboard and CPU and installed everything fresh. No minimized autostart for me still.

**Comment by Hezkore** [comment]
Telegram is still Always On Top in Win10 when started via the "Launch Telegram when system starts".
Closing the app and starting it again fixes it, but defeats the purpose of having it auto-start.

**Comment by mroleh** [comment]
> Telegram is still Always On Top in Win10 when started via the "Launch Telegram when system starts" and combined with the "Launch minimized" option.
> Closing the app and starting it again fixes it, but defeats the purpose of having it auto-start.

Actually, this issue still occurs. Telegram Desktop 1.5.15.
Thanks for your help. @Hezkore

**Comment by samuelbchase** [comment]
This is a weird bug, and I can't really imagine what kind of data would help. If there is any more info I can provide, let me know.

On boot it is always on top, until it is exited from the tray once.

**Comment by Hezkore** [comment]
Telegram Desktop 1.6.3 on Windows 10.
Telegram is still always on top when "Launch Telegram when system starts" and "Launch minimized" is combined.

**Comment by raymonlabs** [comment]
Still have same problem, too

**Comment by dmki** [comment]
I think everyone has it, but I'll just add "me too".

**Comment by ownchoice** [comment]
Welp, me too.

**Comment by swapster** [comment]
Yep, the same problem

**Comment by Diesmo** [comment]
Also the same problem.
Closing Telegram in tray and restarting fixes it.

**Comment by bsides** [comment]
Same problem, collecting years now 😮

**Comment by NicoEnking** [comment]
Same problem here.

**Comment by RubensRainelli** [comment]
#bug still present

**Comment by N-i-p-o-l** [comment]
++

**Comment by 50l3r** [comment]
+1

**Comment by rock1246** [comment]
+1

**Comment by whiteand** [comment]
+1

**Comment by Amarillys** [comment]
I Solved it.
+ Cancel its auto-start and minimized options at first,
+ Exit telegram, restart it, and enable auto-start and minimized options again.

That's all.

**Comment by SirNiggo** [comment]
@Amarillys thanks for the suggestion. However, this is only a workaround and should be fixed anyways.

**Comment by 7nolikov** [comment]
problem is still actual

**Comment by rorzo** [comment]
The same problem.

**Comment by aw-dmitri** [comment]
Similar problem here. Goes back to normal after restarting the desktop client.

**Comment by Juggernaut93** [comment]
Problem still present with version 2.1.4. Sometimes it also happens after a client update.

**Comment by EPecherkin** [comment]
Same. Lol, devs, you still can't fix that? Shame on you

**Comment by siliverst** [comment]
> I Solved it.
> 
> * Cancel its auto-start and minimized options at first,
> * Exit telegram, restart it, and enable auto-start and minimized options again.
> 
> That's all.(From my friend's idea).

Thanks, your method helped me.

**Comment by ArieDeha** [comment]
After more than 3 years, the issue is still exists...
Reproduce:
- Check the telegram application to "Launch Telegram when system starts" (setting -> Advanced)
- Check the telegram application to "Launch minimized" (setting -> Advanced)
- Restart your PC
- Let the telegram application run
- Open telegram application window
- Change to other open windows
- The Telegram application is still on top

Please, it is very annoying...

Yes, it can be solved (worked around) by closing the application from the tray, but that's not good, since every time I restart my laptop, it'll be on top again. 
![image](https://user-images.githubusercontent.com/9045281/86586035-7fa72b00-bfb1-11ea-91ce-0e2d780aece2.png)

**Comment by lonelymyp** [comment]
+1
the window began to hang over before restarting.

**Comment by andronov-alexey** [comment]
The problem is still there, stale bot

**Comment by kocmoc941** [comment]
> The problem is still there, stale bot

same

**Comment by filimonic** [comment]
same problem here

**Comment by t0byman** [comment]
same

**Comment by kocmoc941** [comment]
> just close all of tele
> and then open again...
> it's work

Yes, but you should ALWAYS do this when this error occurs...

**Comment by timramone** [comment]
very annoying

**Comment by kaburaf** [comment]
Turn off "Show tray icon" and on "Show taskbar icon". Works for me.
![image](https://user-images.githubusercontent.com/67632971/127603078-13f79126-43c6-48ea-9923-001a7f93aeea.png)

**Comment by thomas-lentz** [comment]
The problem is still there - Windows 10 Pro, 21H1, OS Build 19043.1415 & Telegram Version 3.3

Incredible that no one cares, there have been ways to reproduce it und workarounds. By now somebody unfamiliar with coding, code have investigated the Telegram code and repair it. Anyway it would be a waste of time, because the programmers of the Telegram code should be able to solve this in a few hours.

Regards
 Tom
