### ISSUE TITLE
Can't preview stickers by holding the left mouse button using touchscreen

### ISSUE THREAD

**Issue by paranoidmonoid** [telegramdesktop/tdesktop#3255]
To preview a sticker without sending the user has to left-click on it and hold the mouse button. 
Looks like there's a problem with doing it on a touch screen.
At least on my Lenovo Yoga 2 laptop on Win 10 (I think it's the same on the most devices with the touch screen) the "long left-click" is considered as a RIGHT one. So it looks impossible to preview the full-size of a sticker without sending it.

I don't really have an idea how to solve this case, but maybe it's a stuff to think about.

Telegram 1.0.29 default theme/Win 10/Lenovo Yoga 2 Pro

**Comment by RussianNeuroMancer** [comment]
On Linux long tap on sticket show "Select Message" menu. It's same in Windows?

**Comment by LittleJellycat** [comment]
@RussianNeuroMancer Yes
![image](https://cloud.githubusercontent.com/assets/7117812/25053781/11703438-2162-11e7-90f2-2136ebe07779.png)

**Comment by RussianNeuroMancer** [comment]
Issue is not solved yet, therefore please keep this report open.

**Comment by RussianNeuroMancer** [comment]
At least on Gnome Shell 3.38 (Wayland session) and Telegram 2.2.0 launched with `QT_QPA_PLATFORM=wayland` this issue is still reproducible.
