### ISSUE TITLE
out of memory allocationg error while running make at final step.

### ISSUE THREAD

**Issue by blackbeaninjeong** [telegramdesktop/tdesktop#3257]
### Steps to reproduce
1. do everything right before the final step(run 'make' at /tdesktop/out/release)
2. 
3. 

### Expected behaviour
Tell us what should happen
run make success

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**
i don't know. just following the read.md for my o.s

**Used theme**:
ubuntu 16.04

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)
[ 40%] Building CXX object CMakeFiles/Telegram.dir/obj/gen/Telegram/qrc/qrc_telegram_emoji.o

cc1plus: out of memory allocating 134217488 bytes after a total of 143552512 bytes
CMakeFiles/Telegram.dir/build.make:10343: 'CMakeFiles/Telegram.dir/obj/gen/Telegram/qrc/qrc_telegram_emoji.o' 타겟에 대한 명령이 실패했습니다
make[2]: *** [CMakeFiles/Telegram.dir/obj/gen/Telegram/qrc/qrc_telegram_emoji.o] 오류 1
CMakeFiles/Makefile2:523: 'CMakeFiles/Telegram.dir/all' 타겟에 대한 명령이 실패했습니다
make[1]: *** [CMakeFiles/Telegram.dir/all] 오류 2
Makefile:83: 'all' 타겟에 대한 명령이 실패했습니다
make: *** [all] 오류 2

the make at before step(tdesktop/debug)was successful,but
I don't know why it happens at release directory.....

**Comment by stek29** [comment]
http://stackoverflow.com/questions/11289002/gcc-cc1-out-of-memory-allocating

**Comment by blackbeaninjeong** [comment]
Thank you:) because of  @stek29  help, i can complete my works!!! :)
