### ISSUE TITLE
Unable to click (github bot) links on Telegram MacOSX client 2.93.x

### ISSUE THREAD

**Issue by mmoayyed** [telegramdesktop/tdesktop#3259]
### Description

I am running Telegram Desktop on Mac OS Sierra; `v2.93.x`. This version was downloaded and installed via the App Store. I was just informed that this is the brand new version of the client running on Swift if that matters at all. I have also added and install the excellent Github Bot, available here: https://github.com/ghaiklor/telegram-bot-github

### Actual behaviour

When I receive Github notifications from a repo I am no longer able to click on the title of the notification to open up the browser and get to the post.

### Expected behaviour

I should be able to click on links that are the Github issue titles or pull request titles.

![image](https://cloud.githubusercontent.com/assets/1205228/24902302/06839092-1ebf-11e7-8986-beceb160d55f.png)

### Reproduce

Example:
`New comment on cas#2498 OAuth2 Authentication broken - created access tokens already expired`

Mousing over the part `cas#2498 OAuth2 Authentication broken - created access tokens already expired` turns the mouse cursor into a hand, indicating that one might be able to click on that title and get to the relevant Github issue, but no matter how many times I click, the browser is never opened to browse to Github and that issue.

### Also

- I did originally reported this issue to the Github Bot project, but I was informed that this may be something Telegram might need fixing. See issue link below.
- I am not sure if this is the right project, because I don't see my Telegram version listed in the releases here.

### Linked Issue

https://github.com/ghaiklor/telegram-bot-github/issues/80

### Configuration

**Operating system:**

Mac OSX Sierra; Latest update/patch. 

**Version of Telegram Desktop:**

2.93.91729, Downloaded and installed from App Store.
![image](https://cloud.githubusercontent.com/assets/1205228/24902256/d5d2ccf6-1ebe-11e7-9cd9-aeb32b385e8f.png)

**Used theme**:

N/A

**Comment by auchri** [comment]
This is not Telegram Desktop, but different macOS app.

Bugs should be reported at [@macswift](https://t.me/macswift)
