### ISSUE TITLE
How should i use Hyperlink in Telegram (Without Bots)

### ISSUE THREAD

**Issue by FarshadGrayson** [telegramdesktop/tdesktop#3260]
hi i've searched everywhere but i got nothing about how to do it can someone help me please ?

**Comment by auchri** [comment]
See http://stackoverflow.com/questions/41299085/how-to-make-a-hyperlink-in-telegram-without-bot

**Comment by stek29** [comment]
Sorry, API doesn't accept links (`[]()`) from normal users. You'd have to use a bot, at least inline one.

**Comment by SmartManoj** [comment]
Why it should not be handled by client?
