### ISSUE TITLE
All messages are on the left (1.0.31 alpha)

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#3262]
### Steps to reproduce
* Open a chat with messages you sent and received

### Expected behaviour
My messages are indented to one side, all the others - to the other side

### Actual behaviour
All messages are now on the left

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.0.31 alpha (today's update I believe)

**Comment by stek29** [comment]
#3130
#3036
#2931
#2911
#2902
#2895
#2887
#2135
#1929
#1750
#1659
#1651
#1650
#1639
#1635
#1632
#1623
#1620
#1591
#1587

And many more

**Comment by arieljannai** [comment]
It happened to me just now 🙄 weird

**Comment by stek29** [comment]
@arieljannai TL;DR: Open settings, disable Adaptive layout

**Comment by arieljannai** [comment]
Great!
Am I missing something more by turning off this setting?

**Comment by stek29** [comment]
No
