### ISSUE TITLE
Feature request - allow user to hide RHS emoji panel

### ISSUE THREAD

**Issue by rikmills** [telegramdesktop/tdesktop#3263]
Ubuntu Zesty
Telegram Desktop version 1.0.31

Please add the option and/or feature to allow the new RHS emoji panel to be hidden by default **if the user chooses**, and then only show on demand.

I imagine many or most users will want it there all the time, so not suggesting to make it go away by default for all, but the option to do so if you choose would be great. It does take up a lot of space when  it shows.

**Comment by john-preston** [comment]
@rikmills You can click on the emoji button near the send button to toggle the panel.

**Comment by rikmills** [comment]
@john-preston Indeed. Typically I discover that myself about 30s after submitting this issue!
