### ISSUE TITLE
[feature-improvement] Allow resizing of the new ESG panel on big monitors. 

### ISSUE THREAD

**Issue by oxydron** [telegramdesktop/tdesktop#3265]
With the 1.0.31 update came the new full screen Telegram, which always shows the ESG (emoji-sticker-gifs) tab, which is a very nice.

My suggestion is to just change this new area to be resizable, like the contacts/text area.

![image](https://cloud.githubusercontent.com/assets/331134/24964224/116fc990-1f77-11e7-8b3a-c27dc696b32e.png)
Image: the blue side is already resizable, but not the red one.

**Comment by stek29** [comment]
And also allow to switch contact list and emoji bar

**Comment by set92** [comment]
And please, add a setting to let the users choose if they want that new tab.

Because right now, this remember me that version that put all the textbox in one side of the screen and all the people start complaining about it, and it could have been avoided with a opt-out option in the settings.

**Comment by john-preston** [comment]
@set92 You can click on the emoji icon near the send button to toggle it.

**Comment by Aokromes** [comment]
#713 ?
