### ISSUE TITLE
[feature request] More shortcuts!

### ISSUE THREAD

**Issue by oxydron** [telegramdesktop/tdesktop#3266]
The idea is to add more shortcuts to Telegram Desktop, using common shortcuts to the do obvious things for those used to use shortcuts.

**Home** - Go to the top of the contacts/**text**
**End** - Go the end of the contacts/**text**
**Page up/down** - Roll *n* lines up/down on the contacts list/**text**
**CTRL + O** (open): open the send file dialog.
**CTRL + ?**: select the emoji panel, moving with arrows
**CTRL + ?**: select the sticker panel, moving with arrows
**CTRL + ?**: select the gifs panel, moving with arrows

Maybe ctrl/meta/<other command key here> + the above for **chat** or the reverse commands, putting more priority on chats instead contacts list.

Maybe a fast access command line, much like sublime text command pallete, with the following options:
- Groups
- Channels
- And more maybe.

Best regards :)

**Comment by auchri** [comment]
Duplicate #1060
