### ISSUE TITLE
Hide the count of unread messages in muted chats

### ISSUE THREAD

**Issue by salashnik** [telegramdesktop/tdesktop#3268]
like described here https://github.com/overtake/telegram/issues/141 for MacOS.

I don't like see unread count  for muted chats in system tray icon & in badge on unity panel and/or plank plank.

**Comment by auchri** [comment]
There is a setting for that

![image](https://cloud.githubusercontent.com/assets/5092164/24996270/8955f054-2032-11e7-8d9b-9585027cce73.png)

**Comment by salashnik** [comment]
oh!!! sorry for this. Thank You!!!

But in russian translation is slightly incorrect
May be instead "Подсчитывать непрочитанные из всех чатов" should be "Включать чаты без звука в подсчет непрочитанных" or something like this...

**Comment by stek29** [comment]
@salashnik There's no official russian translation of TDesktop. Ask the person you got it from.
