### ISSUE TITLE
[feature request] [bot api] input suggesstions in private chat

### ISSUE THREAD

**Issue by xaota** [telegramdesktop/tdesktop#3272]
user input "some"
bot return suggestion "... text"
user tap "... text"
input text changed to "some text"
bot return suggestion "... input"
user tap "... input"
input text changed to "some text input"
...

**Comment by stek29** [comment]
Sorry, what? You want text completion and moving text to message input area instead of sending it?

**Comment by xaota** [comment]
yes

**Comment by MasterGroosha** [comment]
That's an API issue. Bots don't see what users type unless you do it via them in inline-mode. And clicking on result will send message, not edit input field.
But it's also an invalid issue since it's not related specifically to Telegram Desktop.

**Comment by stek29** [comment]
@xaota Well, there's no "completion" mechanism in API, sorry.
