### ISSUE TITLE
Telegram crashes after updating Windows 10 to Creators Update

### ISSUE THREAD

**Issue by Wanny** [telegramdesktop/tdesktop#3276]
I just noticed now since yesterday I was at work and too busy to find out...
After updating Windows 10 to Creators Update, Telegram crashes every time I run it.

I checked the **dumps** folder and the first file matches the date and time of the update. The crash reason is "The thread tried to divide an integer value by an integer divisor of zero." (see more below)
![image](https://cloud.githubusercontent.com/assets/569307/25059572/5d561532-215f-11e7-9817-1bdd5bf040e4.png)

### Steps to reproduce
1. Update Windows 10 to Creators Update
2. Run Telegram
3. See it crash

### Configuration
**Operating system:**
Windows 10, build 15063.138

**Version of Telegram Desktop:**
1.0.29.0

**Used theme**:
Can't remember. I'm sure it isn't the reason anyways since I've been using it for a while without problems.

<details><summary>**Logs**:</summary>

**log.txt**
```
[2017.04.14 21:39:47] Launched version: 1000029, alpha: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
[2017.04.14 21:39:47] Executable dir: C:/Users/Wanny/AppData/Roaming/Telegram Desktop/, name: Telegram.exe
[2017.04.14 21:39:47] Initial working dir: C:/Users/Wanny/AppData/Roaming/Telegram Desktop/
[2017.04.14 21:39:47] Working dir: C:/Users/Wanny/AppData/Roaming/Telegram Desktop/
[2017.04.14 21:39:47] Arguments: "C:\Users\Wanny\AppData\Roaming\Telegram Desktop\Telegram.exe"
[2017.04.14 21:39:47] Logs started
[2017.04.14 21:39:47] Connecting local socket to Global\80f8f934732e7df28064d5243e59eaeb-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2017.04.14 21:39:47] This is the only instance of Telegram, starting server and app...
[2017.04.14 21:39:47] Moved logging from 'log_start0.txt' to 'C:/Users/Wanny/AppData/Roaming/Telegram Desktop/log.txt'!
[2017.04.14 21:39:47] Opened 'C:/Users/Wanny/AppData/Roaming/Telegram Desktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 299
[2017.04.14 21:39:48] App Error: _basePath is empty in writeSettings()
[2017.04.14 21:39:48] App Info: reading settings...
[2017.04.14 21:39:48] App Info: reading encrypted settings...
[2017.04.14 21:39:48] OpenAL Logging Level: (not set)
[2017.04.14 21:39:48] Audio Playback Devices: OpenAL Soft
[2017.04.14 21:39:48] Audio Playback Default Device: OpenAL Soft
[2017.04.14 21:39:48] Audio Capture Devices: OpenAL Soft on MicrÃ³fono (Realtek High Definition Audio)
[2017.04.14 21:39:48] Audio Capture Default Device: OpenAL Soft on MicrÃ³fono (Realtek High Definition Audio)
[2017.04.14 21:39:48] App Info: reading map...
[2017.04.14 21:39:48] App Info: reading encrypted map...
[2017.04.14 21:39:49] App Info: reading encrypted user settings...
[2017.04.14 21:39:49] App Info: encrypted user settings read.
[2017.04.14 21:39:49] App Info: reading encrypted mtp data...
[2017.04.14 21:39:49] Map read time: 152
[2017.04.14 21:39:49] Window Shadow: 1, 1, 3, 4, 6, 9, 13, 18, 24, 31, 38, 46
```

**dump**
```
Dump Summary
------------
Dump File:	52f64f11-0b0e-4c60-ab0d-dcb616bc7539.dmp : C:\Users\Wanny\AppData\Roaming\Telegram Desktop\tdata\dumps\52f64f11-0b0e-4c60-ab0d-dcb616bc7539.dmp
Last Write Time:	12-04-2017 21:19:09
Process Name:	Telegram.exe : C:\Users\Wanny\AppData\Roaming\Telegram Desktop\Telegram.exe
Process Architecture:	x86
Exception Code:	0xC0000094
Exception Information:	The thread tried to divide an integer value by an integer divisor of zero.
Heap Information:	Not Present

System Information
------------------
OS Version:	10.0.15063
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
Telegram.exe	C:\Users\Wanny\AppData\Roaming\Telegram Desktop\Telegram.exe	1.0.29.0
<snip>
```

**Comment by Wanny** [comment]
Just tried a separate fresh install and:

- If I just click on "Start Messaging" the app crashes but the dump says something different:
"The thread tried to read from or write to a virtual address for which it does not have the appropriate access."
![image](https://cloud.githubusercontent.com/assets/569307/25059535/aadcd170-215e-11e7-8e97-c4814f89ccfb.png)


- If I click on the "Switch to ``<another language>``" button, the font for some texts looks... strange:
![screenshot_1](https://cloud.githubusercontent.com/assets/569307/25059528/86af0354-215e-11e7-927d-90aeb28ffe40.png)

**Comment by john-preston** [comment]
@Wanny I run from Creators update fine :( can you contact me at https://t.me/preston and send me the crash dumps there?

**Comment by rogersachan** [comment]
@Wanny Is your telegram from the [website](https://desktop.telegram.org/) or the [Windows Store](https://www.microsoft.com/en-us/store/p/telegram-desktop/9nztwsqntd0s)? I upgraded using the app from the Windows Store and had no issues whatsoever.

**Comment by rogersachan** [comment]
@john-preston I see from the error log that you have Telegram installed from the website. Uninstall that version and try the one from the store (version numbers are the same and the app is kept up-to-date.)

**Comment by john-preston** [comment]
@rogersachan Both versions are almost the same and both work  fine for me on Creators Update.

**Comment by john-preston** [comment]
@Wanny please try out the latest alpha version from https://desktop.telegram.org/changelog#alpha-version it should offer you to send a crash report when you launch the app after a crash.

**Comment by Wanny** [comment]
Sadly I went back to Anniversary Update. Will return to Creators update once it hits Windows Update.

**Comment by luizcarlosfaria** [comment]
After crash every time that i'm trying to run, I've tried to perform a clean install: that doesn't solve this problem.
Trying to find other possibilities, i've tried old versions of portable package, all packages since 1.0.27 crashes on start.

**Comment by john-preston** [comment]
@luizcarlosfaria Do you use Skyfonts?

**Comment by luizcarlosfaria** [comment]
Yes

**Comment by john-preston** [comment]
@luizcarlosfaria Does 1.0.26 version work? Can you check once more that 1.0.26 from here:

https://github.com/telegramdesktop/tdesktop/releases/download/v1.0.26/tportable.1.0.26.zip

works, while 1.0.27 from here:

https://github.com/telegramdesktop/tdesktop/releases/download/v1.0.27/tportable.1.0.27.zip

crashes? In two separate folders, one and another.

**Comment by luizcarlosfaria** [comment]
After your question about Skyfonts, i've opened Skyfonts to update. Testing installed 1.0.29 again, crashes, but tportable.1.0.26 works fine!

**Comment by luizcarlosfaria** [comment]
After font update (by skyfonts) the version 1.0.29, installed, are working fine.

**Comment by john-preston** [comment]
@luizcarlosfaria I'd like you to test two separate cleanly unpacked portable versions with version numbers going one after another and see, that one works and one crashes. Thanks for your help.

**Comment by luizcarlosfaria** [comment]
@john-preston  After you ask me about Skyfonts, i've opened to update fonts.
After update fonts, all three versions are working fine:
1.0.29 (installed)
1.0.26 portable
and 1.0.27 portable

All versions are working fine.

Thank you for all.

**Comment by john-preston** [comment]
@luizcarlosfaria So it looks like it crashes for everyone who has skyfonts installed and not updated :( I wonder how many are there..

**Comment by luizcarlosfaria** [comment]
@john-preston  I don't know, i didn't saw other dump files. 
An information about this is, maybe can make it more clearly,  the main form (that have a big button with label "start messaging") were badly formatted until solve this font issue. The label of "start messaging" were using "courier new" or other similar font.
After update fonts, all problems were solved.

**Comment by gez** [comment]
Another Skyfonts user here getting the same crashes.
In my case Skyfonts is updated to the latest version as Telegram, but it still crashes every time. I tried shutting down skyfonts with the same result, re-syncing fonts. Everything I tried did not work.
Any tips?

**Comment by gez** [comment]
Little update: I tried the alpha version and it doesn't crash immediately like the others. This time I could enter my phone number and the validation code, but it crashed after that.
Still the same outcome, but maybe that little difference gives you a hint about where things are going south.

**Comment by john-preston** [comment]
@gez Can you please contact me at https://t.me/preston so I could send you some test versions and you could tell me some debug output and if it works for you there or not?

**Comment by martemorfosis** [comment]
I can confirm that once I installed Skyfonts and batch Installed the top 20 Google Fonts Telegram stopped crashing. I too noticed the font change on the "Start Messaging" button when it was crashing.

**Comment by john-preston** [comment]
@martemorfosis So you didn't have Skyfonts before? All users who've experienced the crash so far were having Skyfonts installed.

**Comment by gez** [comment]
An interesting turn: I have Telegram running now after installing the Open Sans Family through Skyfonts.
Is it possible that missing Open Sans was the culprit? Everything looks fine now and Telegram works, and the font used in the UI looks pretty much like Open Sans.

**Comment by john-preston** [comment]
@gez Yes, it uses open sans, but it should have it inside the binary and work independently of the other system %)

**Comment by martemorfosis** [comment]
@john-preston No I didn't have Skyfonts installed before and was using v1.0.26 with no issues until I upgrade Windows 10 to Creator's Update using an official MS Update Tool to have the update before it was released on the regular Windows Update Channel. After the update Telegram stopped working.

Then I tried installing several other versions but was until I installed Skyfonts + the Top 20 Google Fonts thru it that I have Telegram v alpha 1.0.33 up and running.

**Comment by Wanny** [comment]
Funny enough, I didn't know what Skyfonts was until I read about it in this thread.

**Comment by willsona** [comment]
I was having this same issue, telegram would load then crash right after showing the client, and re-installing and updating skyfonts has solved the issue. I didn't have skyfonts installed at the time but I had installed it previously.
[report.telegramcrash.txt](https://github.com/telegramdesktop/tdesktop/files/966706/report.telegramcrash.txt)

**Comment by john-preston** [comment]
@all @Wanny @luizcarlosfaria @gez @martemorfosis @willsona Anyone here who still experiences such crash and can test a fix? I'm afraid I'll have to roll it out without testing %)

**Comment by luizcarlosfaria** [comment]
Hi @john-preston,

remembering, i've solved that issue on my environment, just opening skyfonts and automatically these fonts was updated.

After that, i can't reproduce this issue again (i'm happy about that!)

I don't know any way to reproduce that. Have any suggestion?

**Comment by Wanny** [comment]
Unfortunately I'm still using Anniversary Update so I can't test it. However, as I mentioned, I was **not** using Skyfonts so at least my issue wasn't caused by it.

**Comment by stek29** [comment]
I don't have SkyFonts installed, but TDesktop works fine after installing Creators Update for me.

**Comment by naseweis520** [comment]
I'm still occassionally facing this issue although I've already run SkyFonts and updated all fonts.
To get Telegram to run I have to start SkyFonts. Uninstalling SkyFonts does not solve Telegram's crashes.

Telegram version: 1.0.0.29
OS: Windows 10 Home 15063.296 "Creators Update"
Exception code: 0xC0000094
Exception information: The thread tried to divide an integer value by an integer divisor of zero
If required I can provide the dump file generated by Telegram.

**Comment by john-preston** [comment]
@naseweis520 Please try the latest alpha version from https://desktop.telegram.org/changelog#alpha-version and tell here if it works where 1.0.29 crashes.

**Comment by naseweis520** [comment]
@john-preston Yes, using 1.0.37 everything works fine. Thank you very much.

**Comment by vasily-v-ryabov** [comment]
Recent stable version from the website (v2.4.3) still crashes on my Win10 version 2004. It happens after entering a phone number and then a 5-digit code. SkyFonts are not installed. Installing Monotype_SkyFonts_Winx64_5.9.5.6.exe didn't help.

**Comment by vasily-v-ryabov** [comment]
Attaching latest crash dump.
[c5c67ed3-edd9-4246-89d1-738e77293726.zip](https://github.com/telegramdesktop/tdesktop/files/5348592/c5c67ed3-edd9-4246-89d1-738e77293726.zip)
