### ISSUE TITLE
Using EmojiOne instead of Apple Emoji

### ISSUE THREAD

**Issue by morealaz** [telegramdesktop/tdesktop#3281]
Why not using EmojiOne?
![emoji](https://cloud.githubusercontent.com/assets/2796369/25066204/35ac22ca-2235-11e7-80cb-62687d59e531.png)

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.

**Comment by stek29** [comment]
@morealaz Because EmojiOne 3.0 looks even worse than Apple Emoji :(
