### ISSUE TITLE
Telegram synchronization

### ISSUE THREAD

**Issue by Cysign** [telegramdesktop/tdesktop#3286]
![photo_2017-04-17_00-06-08](https://cloud.githubusercontent.com/assets/6256909/25074690/f5755e74-2301-11e7-8678-1767becf275c.jpg)

There seems to be a synchronization issue. Please look ah the date :D

**Comment by MasterGroosha** [comment]
This is not Telegram Desktop-specific issue, sorry.

**Comment by auchri** [comment]
and a duplicate

**Comment by stek29** [comment]
of #2797 btw.
