### ISSUE TITLE
Linux app crashes after connecting/disconnecting devices (wireless mouse/bluetooth headphones)

### ISSUE THREAD

**Issue by amankhoza** [telegramdesktop/tdesktop#3287]
### Steps to reproduce
1. Run Telegram in background
2. Plug in or unplug wireless mouse or bluetooth headphones

### Expected behaviour
1. Indicator should stay visible in tray, indicating Telegram is still running.

### Actual behaviour
1. Telegram crashes and the indicator (icon in tray) vanishes.

### Configuration
**Operating system:**
Linux (Fedora 24)
**Version of Telegram Desktop:**
1.0.29-stable and 1.0.33-alpha
**Used theme**:
Default

<details><summary>**Logs**:</summary>
(Telegram:9179): Gdk-ERROR **: The program 'Telegram' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 33800 error_code 10 request_code 131 minor_code 46)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)

</details>

**Comment by john-preston** [comment]
@amankhoza Please try out the latest 1.0.33 alpha version from https://desktop.telegram.org/changelog#alpha-version it should suggest you to send a crash report on the next launch after a crash. Please copy your "report tag" here and send the report if it happens.

**Comment by amankhoza** [comment]
I ran the Telegram 1.0.29 executable from command line and got the following error when it randomly crashed, I will install 1.0.33 and report the crash report:
```
(Telegram:9179): Gdk-ERROR **: The program 'Telegram' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 33800 error_code 10 request_code 131 minor_code 46)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)
```

**Comment by amankhoza** [comment]
Ok, so some good news and some bad new.

**Good news**
The bug is easily reproducible. I have a bluetooth mouse connected, everytime I unplug the mouse's USB receiver, Telegram crashes.

**Bad news**
Even when using 1.0.33 I do not get any suggestions for reporting a crash report on next launch.

**Comment by amankhoza** [comment]
@john-preston Any ideas on how to get some more meaningful logs, as I can easily reproduce the crash now

**Comment by john-preston** [comment]
@amankhoza Any crash should produce a crashdump, they should be in ~/.local/share/TelegramDesktop/tdata/dumps folder. Do you have there any? Does one new occur if you force the app to crash?

**Comment by amankhoza** [comment]
Ok so I found the folder ~/.TelegramDesktop, the dumps directory in tdata is always empty even after a crash, but there is a log.txt file which might have some useful information, contents below:
```
[aman@XPS13 .TelegramDesktop]$ cat log.txt 
[2017.04.25 12:03:24] Launched version: 1000034, alpha: [TRUE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
[2017.04.25 12:03:24] Executable dir: /home/aman/Apps/telegram/, name: Telegram
[2017.04.25 12:03:24] Initial working dir: /home/aman/Apps/telegram/
[2017.04.25 12:03:24] Working dir: /home/aman/.TelegramDesktop/
[2017.04.25 12:03:24] Arguments: "./Telegram" "--sync"
[2017.04.25 12:03:24] Logs started
[2017.04.25 12:03:24] Connecting local socket to /tmp/318f85fdb669aa6dc966fc32e8596374-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2017.04.25 12:03:24] Socket connect error 0, starting server and app...
[2017.04.25 12:03:24] Moved logging from '/home/aman/.TelegramDesktop/log_start0.txt' to '/home/aman/.TelegramDesktop/log.txt'!
[2017.04.25 12:03:24] Opened '/home/aman/.TelegramDesktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 0
[2017.04.25 12:03:24] Could not load 'appindicator3' with version 1 :(
[2017.04.25 12:03:24] Error: failed to load 'gdk_set_allowed_backends' function!
[2017.04.25 12:03:24] Getting DE, XDG_CURRENT_DESKTOP: 'GNOME'
[2017.04.25 12:03:24] Getting DE, DESKTOP_SESSION: 'gnome'
[2017.04.25 12:03:24] Getting DE, KDE_SESSION_VERSION: ''
[2017.04.25 12:03:24] DE: Gnome
[2017.04.25 12:03:24] Tray Icon: Try Qt = [TRUE], Prefer appindicator = [FALSE]
[2017.04.25 12:03:24] App Info: reading settings...
[2017.04.25 12:03:24] App Info: reading encrypted settings...
[2017.04.25 12:03:24] OpenAL Logging Level: (not set)
[2017.04.25 12:03:24] Audio Playback Devices: OpenAL Soft
[2017.04.25 12:03:24] Audio Playback Default Device: OpenAL Soft
[2017.04.25 12:03:24] Audio Capture Devices: Built-in Audio Analog Stereo;Monitor of Built-in Audio Digital Stereo (HDMI);Monitor of Built-in Audio Analog Stereo
[2017.04.25 12:03:24] Audio Capture Default Device: Built-in Audio Analog Stereo
[2017.04.25 12:03:24] App Info: reading map...
[2017.04.25 12:03:24] App Info: reading encrypted map...
[2017.04.25 12:03:24] App Info: reading encrypted user settings...
[2017.04.25 12:03:24] App Error: attempt to write settings while reading them!
[2017.04.25 12:03:24] App Info: encrypted user settings read.
[2017.04.25 12:03:24] App Info: reading encrypted mtp data...
[2017.04.25 12:03:24] Map read time: 21
[2017.04.25 12:03:24] Using Qt tray icon.
[2017.04.25 12:03:24] Tray Icon: Using Qt tray icon, available: [TRUE]
[2017.04.25 12:03:24] Not using Unity Launcher count.
[2017.04.25 12:03:24] TCP Error: network - Network unreachable
[2017.04.25 12:03:24] HTTP Error: network error 99 - Network unreachable
```

**Comment by john-preston** [comment]
@amankhoza :( I don't know how to deal with crashes if they even don't produce crashdumps. The log content is fine :( Perhaps launching with "catchsegv ./Telegram" from the terminal will give a stacktrace?

**Comment by amankhoza** [comment]
Launching with "catchsegv ./Telegram" didn't produce any new info. I tried running old versions of Telegram and found that the last version without the bug was 1.0.28, so the bug was introduced in 1.0.29, I'll try and see if I can spot anything in the code for the update that might be causing it.

**Comment by Aokromes** [comment]
#2478 ?

**Comment by amankhoza** [comment]
@Aokromes It seems the same bug was reintroduced in version 1.0.29, as 1.0.28 and before were working fine.

**Comment by cason** [comment]
Same here:

Telegram: version 1.0.35 alpha, default theme

System: Debian 9.0 stretch/sid

Using strace:
```
open("/usr/share/X11/XErrorDB", O_RDONLY) = 30
fstat(30, {st_mode=S_IFREG|0644, st_size=42077, ...}) = 0
read(30, "!\n! Copyright 1993, 1995, 1998  "..., 42077) = 42077
close(30)                               = 0
write(2, "The program 'Telegram' received "..., 584The program 'Telegram' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 924 error_code 10 request_code 131 minor_code 46)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
) = 584
```

**Comment by viluon** [comment]
The same problem occurs when the system wakes up from hybrid sleep (which may involve reconnecting devices - I'm not sure about this, however).
```
The program 'Telegram' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 49991 error_code 10 request_code 131 minor_code 46)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```
Debug logs are fine. No dumps produced.

**Comment by amankhoza** [comment]
@viluon Yep this happens to me too.

**Comment by viluon** [comment]
Interestingly enough, Telegram did *not* crash after one of the yesterday's wakeups... This information probably makes it even harder to fix :confused:

**Comment by Alukardd** [comment]
I have the same problem as @viluon described before. (crash after suspend my system)
OS: Debian GNU/Linux Stretch.
Same problem with tdesktop v1.0.29 (stable) and with v1.0.37alpha

**Comment by sabotatore** [comment]
I have the similar issue. The Telegram crashes every time when a bluetooth speaker connects/disconnects.
OS: Fedora 25
Telegram: 1.1

**Comment by 3cky** [comment]
Had same issue in Fedora 25, but have found that Telegram crashes are gone after installing libappindicator-gtk3 package.

**Comment by amankhoza** [comment]
@3cky That fixes it for me too :)

**Comment by cason** [comment]
In Debian systems it also seems to work, using the corresponding package libappindicator3-1.

**Comment by antun3s** [comment]
@3cky and @cason the package _libappindicator3-1_  fixes to me. Thanks.

**Comment by PFCKrutonium** [comment]
Also seems to have fixed the issue on Arch Linux `libappindicator-gtk3` package.

**Comment by phamthaibaoduy** [comment]
@3cky it works for me also, thanks 👍

**Comment by Lesik** [comment]
I was having the same issue on **Debian Stretch** when plugging in or out a (wired) USB mouse.

```
The program 'Telegram' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 2102 error_code 10 request_code 131 minor_code 46)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

I can confirm that installing `libappindicator3-1` solved the issue.

**Comment by nuqz** [comment]
Hello, I have the same error as above:

```
The program 'Telegram' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 1800 error_code 10 request_code 131 minor_code 46)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

It happens only when I connect/disconnect any USB devices into PC.
My environment is:
* Debian Stretch with 4.9.0-3-amd64 kernel
* Telegram 1.1.23
* Mate as DE

@3cky @Lesik @cason I confirm, that installing `libappindicator3-1` solved the issue.

**Comment by dgudtsov** [comment]
Hi
the same issue i have with latest telegram version on debian 9.2 with Bluetooth keyboard. if keyboard disconnecting for some reason (power saving or something), then tegram app crashing.

**Comment by stek29** [comment]
#2478

**Comment by thrustix** [comment]
@3cky @Krutonium 
Installing `libappindicator-gtk3` fixed it for me too on Arch linux.

**Comment by Nidhoegger** [comment]
Bugfix works in Debian 9 as well, package is called "libappindicator3-1"

**Comment by Alex-Malkov** [comment]
Linux version 3.16.0-7-amd64 (debian-kernel@lists.debian.org) (gcc version 4.9.2 (Debian 4.9.2-10+deb8u1) ) #1 SMP Debian 3.16.59-1 (2018-10-03)
Telegram v 1.4.3

[1205/133622.737174:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to launch GPU process.
The program 'Telegram' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
(Details: serial 85418 error_code 10 request_code 131 minor_code 46)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the --sync command line
option to change this behavior. You can then get a meaningful
backtrace from your debugger if you break on the gdk_x_error() function.)
