### ISSUE TITLE
Edit message mode

### ISSUE THREAD

**Issue by artemgurzhii** [telegramdesktop/tdesktop#3288]
### Steps to reproduce
1. Send message from laptop
2. Send message from phone
3. Press `arrow top(↑)` on laptop

### Expected behavior
Should turn on edit mode for the last message sent

### Actual behavior
Edit mode was settled for the last message send from laptop

### Configuration
**Operating system:**
MacBook Pro 2016 MacOS Sierra 10.12.4
**Version of Telegram Desktop:**
1.0.29

**Comment by john-preston** [comment]
@artemgurzhii This is intended.

**Comment by stek29** [comment]
#2454
