### ISSUE TITLE
Raspberry Pi specific builds

### ISSUE THREAD

**Issue by sergioad** [telegramdesktop/tdesktop#3290]
Hi friends could you please add support and build Telegram desktop for the Raspberry Pi? Because Raspbian is the official distro for the RPI and UbuntuMATE is the best most modern and most modern distro for the pi I really would love to have Telegram in a nice desktop and not Android

**Comment by auchri** [comment]
Hi friend could you please search for existing issues? Because it's annoying af if people keep creating duplicates of other issues thanks for understanding
