### ISSUE TITLE
MacOS: switching between conversations with hotkeys doesn't work after reboot

### ISSUE THREAD

**Issue by asmisha** [telegramdesktop/tdesktop#3292]
### Steps to reproduce
1. Install Telegram
2. Perform hard reboot of your system (long-press power button, not sure if normal reboot does this)
3. Boot again, launch Telegram

### Expected behaviour
Alt+Up - switches to previous conversation, Alt+Down - to the next one

### Actual behaviour
Alt+Up - edits last message, Alt+Down - does nothing

### Configuration
**Operating system:**
MacOS Sierra 10.12.4 (16E195)

**Version of Telegram Desktop:**
Telegram v2.94.92789 AppStore

</details>

Current workaround is to completely reinstall the application.

**Comment by john-preston** [comment]
@asmisha Sorry, this is not Telegram Desktop, it is another Telegram app. You can try Telegram Desktop from https://desktop.telegram.org

**Comment by asmisha** [comment]
@john-preston Sorry about that :)

**Comment by stek29** [comment]
@asmisha You can report this at https://t.me/macosswift

**Comment by asmisha** [comment]
@stek29  it seems that account doesn't exist

**Comment by stek29** [comment]
@asmisha sorry, I meant https://t.me/macswift
