### ISSUE TITLE
Chat box missing!

### ISSUE THREAD

**Issue by Yoshimaster96** [telegramdesktop/tdesktop#3293]
Upon clicking a link to a particular group, there is no chat box. There is only a single mute button where the chat box should be. What's going on?

**Comment by john-preston** [comment]
@Yoshimaster96 Maybe it is a channel, not a chat?

**Comment by Yoshimaster96** [comment]
Hm? What's that mean?

**Comment by john-preston** [comment]
@Yoshimaster96 there are not only chats in Telegram, but also channels: only channel admin can write there, see https://telegram.org/blog/channels

**Comment by Yoshimaster96** [comment]
There are posts by many people though... Last one was about an hour ago

**Comment by john-preston** [comment]
@Yoshimaster96 I don't know then :( Can you provide a link to that chat?

**Comment by Yoshimaster96** [comment]
NVM, I think I got it figured out.

**Comment by stek29** [comment]
@Yoshimaster96 you can close it too :D
