### ISSUE TITLE
Feature request. Agregate message feed from all channels and users with filter options.

### ISSUE THREAD

**Issue by Losiara** [telegramdesktop/tdesktop#3299]
I can't realy imagine comfortable news reading without scrolling common feed as provided in facebook etc, also with some filter options. 
Today switching between rather large amount of channels is weird.  
Can I hope this feature will be implemented in some future?

**Comment by john-preston** [comment]
@Losiara I'm almost sure that it won't be implemented here before it will be added to one of iOS / Android apps.
