### ISSUE TITLE
Support formatting text (e.g. bold, italic, and link)

### ISSUE THREAD

**Issue by meness** [telegramdesktop/tdesktop#330]

**Comment by MDIV666** [comment]
It's impossible even if you use G+ way to do it?
I mean if you want to *BOLD* _italic_ or -skitetrouth- you just add *, _ or - to the beginning and on the end of sentence.

**Comment by rockneurotiko** [comment]
This is going to be supported in Android and OSX, at least that's what the Bot API updated right now:
[https://core.telegram.org/bots/api#sendmessage](https://core.telegram.org/bots/api#sendmessage)
Check the `parse_mode` field.

**Comment by auchri** [comment]
I think it's already implemented in Telegram Desktop :yum:

**Comment by telegramdesktop** [comment]
@auchri Sorry, but it isn't 😭

**Comment by zackpollard** [comment]
@telegramdesktop Are you planning on implementing this at any point, I feel this would be a good addition and it was stated on the bot API that it would be implemented into other clients "soon" back on september 7th.

**Comment by telegramdesktop** [comment]
@zackpollard It is supported in dev version already.

**Comment by zackpollard** [comment]
Yea, sorry, noticed the dev branch and found the dev builds after I made this post, running the dev build now and updated my bot API to support the formatting :P

**Comment by baziliolg** [comment]
Today they added @bold bot that is absolutely non-intuitive and can't make a part of message italic or bold.
`code` already works, why not add _italic_ and *bold* - the way we all are used to?

**Comment by cubrr** [comment]
> \`code\` already works, why not add _italic_ and *bold* - the way we all are used to?

Agree, that would be pretty slick. Has anyone figured out a way to have \`code\` support multi-line messages though?

**Comment by auchri** [comment]
\`\`\`
asdasd
asdas
dasd
\`\`\`

:wink:

**Comment by cubrr** [comment]
@auchri Oh damn. That's nice. Thanks!

**Comment by KilluaFein** [comment]
someone know if its possible to format italic this string "max_92" ? I'm having problem on escaping the _ inside the string

**Comment by zackpollard** [comment]
@KilluaFein It is possible to escape the _ easily by doing \_ if sending the message with markdown formatting enable via a bot.

**Comment by KilluaFein** [comment]
@zackpollard I've tried that, but returning http error 400: bad request

**Comment by KilluaFein** [comment]
@zackpollard ops, done! correct syntax is _max_\__92

**Comment by mehdi7350** [comment]
Hi how to change telegram to default storage to sd card

**Comment by PeterMX** [comment]
Now than Whatsapp support _italic_ and *bold*, any chance for Telegram??

**Comment by DaFri-Nochiterov** [comment]
For a long time ago... Telegram was added inline-bots
`@bold *bold* _italic_ [link](example.com)`

**Comment by PeterMX** [comment]
> For a long time ago... Telegram has added inline-bots

I knew it, but it is dirty with `via @bold`

**Comment by MeDeVILe** [comment]
@PeterMX just use @markdownrobot

**Comment by baziliolg** [comment]
But why? Why do we have to use 'third party' to be able to just mark a
substring in a message to be shown to others as bold or italic?
I don't know markdown syntax, for example.

@bold bot is no good because makes the whole message bold.
18 марта 2016 г. 11:16 пользователь "MeDeVILe" <notifications@github.com>
написал:

**Comment by john-preston** [comment]
@baziliolg @bold can have custom markdown, try sending \*bold\* and \_italic\_ :)

**Comment by sigod** [comment]
@john-preston Why do we have support for `monospace` out of the box, but for **bold** and _italic_ we have to use `@bold` bot?

**Comment by DaFri-Nochiterov** [comment]
@sigod, API issue. API allows only `code blocks` in messages. Only Bot API allows to send *bold* and _italic_

**Comment by pureby** [comment]
To all the people saying: "just use `@bold`" → **what if I want to keep my messages _private?_**

Besides of that, it's a really "dirty" way indeed (well said @PeterMX ! )

**Comment by MeDeVILe** [comment]
@pureby to keep messages private use Signal :P 
And to have this feature in telegram we have to wait for API update :(

**Comment by pureby** [comment]
Speaking of _"proper way"_, there is actually still a chance for Telegram to be **the first** to do that!
The "proper" way IMHO would be:

`**bold**
//italic//
__underline__`

Typing 2 special characters at the beginning and the end of the word/sentence is just as fast and easy as typing 1, and will prevent all kind of crazy shit from happening (like described above).

I never understood why _italic_ is being represented by... an underscore? Lol. And what should represent underline in this case? Ohh wait, nothing.

I know that all kinds of diginerds will now flame on me by saying the `//` is gonna interfere with hyperlinks... Well, please think twice before writing that kinda comments.

So there you go Telegram, still a chance to beat WhatsApp and be the first.

**Comment by roytam1** [comment]
> So there you go Telegram, still a chance to beat WhatsApp and be the first ;-)
and no, Whatsapp supported text formatting before telegram!

**Comment by stek29** [comment]
@pureby It's markdown, and it's widespread

**Comment by FreshMarv** [comment]
I was really surprised when Telegram offered @bold. It's a really unclean solution imho...
I just noticed that @TwitterForwarderBot uses bold text supposedly without @bold...
Maybe there is a way now that has not been published yet.

**Comment by DaFri-Nochiterov** [comment]
`@TwitterForwarderBot` is bot. Bots can use all of Telegram markdown.

**Comment by sigod** [comment]
> I was really surprised when Telegram offered @bold. It's a really unclean solution imho...

I agree. It's very dirty solution.

**Comment by stek29** [comment]
@sigod @FreshMarv Then ask server dev to allow it. Even if client sends formatted message, bold and italic is erased. So it's nothing TDesktop can do, you should use "Ask a question" or ping telegram on twitter.

**Comment by vasil1c** [comment]
Hi. I am try create telegrambot that coud send preformated messages to user. in web telegram text formated, but mobile erase all tags <pre>. Mat be you start maintain tag <br> in all your clients. Now mobile text not reading.

**Comment by pureby** [comment]
**@stek29** Nice try, but it _is_ mark**up**. "Markdown" is just a widespread markup language. And I have just explained why it is illogical and impractical compared to the better markup language which I have proposed.

No everything that shines is gold.

**Comment by stek29** [comment]
@pureby And this language is used for @bold.

**Comment by pureby** [comment]
**@stek29** And in a lot of other places, like WhatsApp and YouTube; like I've said, it is _unjustly_ widespread. But how is that relevant to this particular discussion?

**Comment by matanster** [comment]
Should adding caption text for hyperlinks be a separate ticket?
I mean, the ability to embed a hyperlink where what is shown is some caption text, not the url that it points to.

**Comment by Behoston** [comment]
may be buttons?

**Comment by stek29** [comment]
@matanser `@bold [foo](http://example.com)` gives [foo](http://example.com)

**Comment by AnimusPEXUS** [comment]
how to write strikeout/crossout text?

**Comment by nO-OnE-910** [comment]
On iOS you're able to select a bit of text, select the '**B** _I_ U' button and then you can **bold** or _italic_ it without any bot 🤔

**Comment by stek29** [comment]
@nO-OnE-910 yeah, formatting is finally allowed on server side.

**Comment by Swissnetizen** [comment]
Sidenote: *bold* and _italic_ isn't actually markdown.

**Comment by GordonsBeard** [comment]
On Telegram web `*bold*` is now coming out as **bold** and this is incorrect.

**Comment by stek29** [comment]
@GordonsBeard @Swissnetizen it's ["Telegram markdown"](https://core.telegram.org/bots/api#markdown-style).

**Comment by kirsan31** [comment]
Yes we need this without bots, ideally with buttons (like ios)!!! And 1 more question - how to deal with @bold message length limit?

**Comment by MeDeVILe** [comment]
Now I know it's possible without bots. Plus messenger imply this in its' last update.

**Comment by MultiverseWolf** [comment]
@MeDeVILe  Where was this? I checked Telegram Desktop and there's no mention of this.

**Comment by dobeerman** [comment]
Really, it should be support of **DOUBLE** special characters to markdown. 
Just try to use any word with underscore symbol and italic markdown together...

**Comment by MultiverseWolf** [comment]
Does anyone know how I can use asterisks without making the text bold? I use asterisks a lot in my daily conversation and its bothering me to no end.

**Comment by kirsan31** [comment]
@MultiverseWolf what? Currently telegramdesktop support text formatting only thru bots, what do you mean?

**Comment by MultiverseWolf** [comment]
@kirsan31 It works for me. If I put asterisks between text it becomes bold.

**Comment by 96Octavian** [comment]
Actually I tried this right now, and I found working those:
*bold text*
_italic text_
`fixed-width text`
On the android app

**Comment by kirsan31** [comment]
@MultiverseWolf @96Octavian 
We are talking here about telegramdesktop isn't it?

**Comment by 96Octavian** [comment]
Sorry I was not clear at all, I can send them from the app and I see them formatted on the desktop, but viceversa still doesn't work I wonder why

**Comment by itJunky** [comment]
How can i post bold text in desktop app? asterisk printed without bolding text now.

**Comment by stek29** [comment]
@96Octavian please don't confuse people.

Neither TDesktop nor **official** Android apps allow you to format a message without bots (except code/pre)

@itJunky only with bots. Try @bold for example.

**Comment by kirsan31** [comment]
In upcoming android version:
**- Ability to make text bold, italic or monospaced without the use of bots.**

Any chance for TDesktop????

**Comment by ttsda** [comment]
funny to look at this thread and the telegram team's response now that telegram android supports this and desktop doesn't

**Comment by qgates** [comment]
Latest android client supports double star bold and double underscore italic. Recent versions supported single star / single underscore, but they've changed it to keep everyone happy as there were complaints from people wanting to star-wrap words.

I'd like to see same in tdesktop (ie. double-star, double-italic). Tdesktop can already show such formatting from messages composed on Android.

**Comment by roytam1** [comment]
What about strikethrough text?

**Comment by kirsan31** [comment]
Now both Ios and Android version support formatting without bots and thru user interface!
Exotic android versions (like MIUI), that have own selection menu, doesn't support this with interface, but at least we can use ** and __
Tdesktop where it most needed, and where it can (and **must**!) be most user friendly, doesn't have this functionality!!!
May be we need create a new issue for this?

**Comment by mtvs** [comment]
and quotes

**Comment by stek29** [comment]
@roytam1 API issue. Feel free to contact Telegram Support.

**Comment by dan31** [comment]
> That is not planned, because it will complicate everything. Telegram is mobile-first app, no such features can be widely used on mobiles.

Using markdown to add bold and italic is intuitive for any developer today. It is now ridiculous in telegram: many of my messages are full of underscores, and we all understand what they mean. Except Telegram 😄

**Comment by roytam1** [comment]
> @roytam1 API issue. Feel free to contact Telegram Support.
actually tried to contact Telegram Support but no response from them.

**Comment by vsvasya** [comment]
Wondering about talks of "markdown support in API" )
It is purely client task - just get plain text and just apply markdown formatting.

**Comment by PeterMX** [comment]
any news?

**Comment by stek29** [comment]
@vsvasya Some time ago Servers rejected parsed formatting from clients if they we're not bots.

**Comment by mrzool** [comment]
@pureby 

> And I have just explained why it is inferior to the markup language proposed by me.

Wow, that's serious. Finally a markup language that makes sense, not like that John Gruber's nonsense we're forced to use every day. How is it going with the implementation? Can we see the code? Are you using C or Perl? Or maybe Rust or Go? Is it already documented?

**Comment by HypeZ85** [comment]
woah, i cannot believe we still cannot use *bold* _italic_ 

this issue was opened 3 years ago. This is totally nonsense

**Comment by pureby** [comment]
@mrzool In case you're wondering about implementation — why don't you just open Telegram and try it out? No need to make a fool of yourself in public — you're not nearly as smart or funny as you think you are ;-)

@stek29 The point @vsvasya (among others) is trying to make (and you keep missing) is that the server does not have to do _anything_ at all. Text formatting can be done strictly on client side by instructing the client to interpret certain combination of raw symbols as formatted text, and displaying it that way on the screen.

**Comment by auchri** [comment]
> _the server is not involved at all._ It is enough to simply instruct _the client_ to interpret certain combination of raw symbols as formatted text.

The server is involved, because _he_ instructs the clients how they should format the messages.

**Comment by pureby** [comment]
@auchri I simply replied to the claim of a certain individual above that _"formatting on desktop is **impossible,** because server rejects formatting"_. Smell the fallacy?
So people came up with an effective and easy _solution_ that does not involve tweaking server settings and has many other upsides (transparency, flexibility and effectiveness). So unless there is some hidden downside to the proposed solution, I don't see what's wrong with letting the server "rest" and instructing the client to do the formatting.

**Comment by auchri** [comment]
@pureby Which "solution" are you talking about?

**Comment by pureby** [comment]
@auchri Server parses nothing but plaintext (with markup being nothing but plaintext symbols), then the client interprets the plaintext markup string and formats text accordingly.

**Comment by stek29** [comment]
@pureby "Server settings" were tweaked almost half a year ago.
Also, it's not an "effective and easy solution", since it requires app to interpret both server side formatting and local formatting. 
Also, keep in mind that TDesktop is part of Telegram, so you can't just add some local TDesktop specific hack if Telegram doesn't want to have that feature -- that won't work.

**Comment by pureby** [comment]
@stek29 All I did above was debunk your repeated claim that markup-based text formatting is "impossible" _due to "server limitations"_. Clearly, it can be technically achieved by clients only, without ever consulting the server — which I demonstrated.

Now _maybe_ there are _other reasons_ why this feature is still not implemented, but that discussion will be based solely on speculations and not facts, so... I'm not going there, and you might just as well have not started it :-)

Have a nice day!

**Comment by john-preston** [comment]
@pureby It just isn't done yet, sorry.

**Comment by pureby** [comment]
@john-preston Thanks for setting the record straight! :-)

**Comment by stek29** [comment]
@pureby 
>  debunk misinformation repeatedly posted by you

What misinformation?

> stek29 commented on May 14, 2016
> @sigod @FreshMarv Then ask server dev to allow it
> ---
> stek29 commented on Oct 6, 2016
> @nO-OnE-910 yeah, formatting is finally allowed on server side.

And about your "solution"
> the server doesn't have to be involved at all. It is enough to simply instruct the client to interpret certain combination of raw symbols as formatted text.

Think again about purpose of this tracker and purpose of TDesktop before suggesting solutions like this. I personally recommend reading [this comment](https://github.com/telegramdesktop/tdesktop/issues/3490#issuecomment-306056072).

**Comment by pureby** [comment]
@stek29 I recommend you stop pretending like you're _some kind of_ TG official. 

We have received a definite answer from _the_ developer: it is not "impossible", it's not a "server issue" — none of the bs you have repeatedly claimed. It is simply not done _yet,_ because there's a lot of work to do. Which I respect fully and greatly.

This discussion is over.

**Comment by stek29** [comment]
@pureby It __was__ impossible, because it __was__ server issue -- at __the time I said__ it was.
I'm TG official, but I tend to speak out what I think and what I know -- that's why comments exist.
And sometimes I can know a bit more about TG than others -- I can try to send formatted text from my account using API directly, and notice it won't work.
Then I tell it to people, so they don't blame __the__ developer for not implementing this.

I've made some (minor) contributions to TDesktop, and I try to help _the_ developer and _the_ auchri by looking through reports, finding duplicates, and doing other things I can do.
But I can't find even comments on issues from you (except this one).
You came from nowhere and started saying I was lying, without even trying to make a research or something. But I can give you a brief history of "formatting without bots" feature in TG.

First official client to support formatting without bots was Webogram, and it was added in zhukov/webogram@68f9e5da778a5c48e5929a96e3b359aa01d24d01 (have a look at commit author).

Before that I _(and other people ofc)_ was asking team for formating without bots, was reminding team about this feature -- since I was accepted to [TSF](https://core.telegram.org/tsi) and even before.

So no, **I'm not TG official**, but maybe, just maybe, I know _more_ about TG _than_ you do.

Anyways, our conversation has nothing to do with this issue report, and you're right -- This discussion is over.
But I decided to post this comment anyways to give you a chance to start blaming me for disinformation in year or two when something stated in it changes, just as you did with my previous comments about this being server side issue.

Oh, and speaking about definite answer from _the_ developer: 
![image](https://user-images.githubusercontent.com/11808223/27011183-598690d4-4ebf-11e7-8812-63f2012d52bc.png)

**Comment by Cthutq1** [comment]
Добрый вечер!
Приношу свои извинения у меня маленький опыт работы с ПК .и многое я делаю скорее интуитивно.
Если возможно настройте мне работу программы. за дополнительную олеату.
Буду Вам очень признателен. Программа пишет какой то файл отсутствует. Где его брать???
С уважением 
Сергей Механик .

**Comment by pureby** [comment]
@stek29 Dear Viktor, I apologize sincerely. I didn't realize the amount of time you put into technical assistance, nor the amount of knowledge that you have about Telegram (which indeed turns out to be more than mine). I guess I just provoked myself into a fight, and then I realized that I'm fighting a person who is actually _helping_ to make the best messaging app for my phone and desktop, which in turn makes communication between me and my loved ones secure, fun and accessible from every device.

Thank you for keeping your cool and staying polite and professional while I tried to provoke you. It took me some unrelated personal blunder and your long and polite reply to realize that what I was doing past months was unjust and stupid, and I hope you can accept my apology and we all get along from now on.

**Comment by haroon-ali** [comment]
Testing Android official app for Arabic text;
__Italic__ text works fine but **bold** doesn't. 
**Arabic bold text** is displayed the same as normal text.

**Comment by pureby** [comment]
Will we ever get ~~[s]strikethrough[/s]~~ ?

**Comment by stek29** [comment]
@pureby it's not supported on server side, ping Telegram on Twitter or ask in-app support

**Comment by ewerybody** [comment]
Whow! There is awesome `code`-snipped support via \`
and code block support with \`\`\` 👍👍 And thats already in for as long as I remember!

But **\*bold\*** and _\_italic\__ have to be done via `@bold` which you can't just type but you have to wait for a popup where you choose the "custom markdown" ... ☹️ 
This seems overly complicated giving that [Threema](https://threema.ch/en/faq/markup) and [WhatsApp](https://faq.whatsapp.com/en/general/26000002) support this for ages already without any hassle.

**Comment by john-preston** [comment]
@ewerybody You can use bold and italic with double * or double _

**Comment by auchri** [comment]
@ewerybody ...without an bot

**Comment by ewerybody** [comment]
Ah nice! At least something! Since when is that in?
And where is the documentation for that?

**Comment by AndydeCleyre** [comment]
I see this is closed, but with what syntax is link formatting supported?

**Comment by stek29** [comment]
@AndydeCleyre no, links are not rejected by server unless you're a bot.

Here's currently supported format:
- **bold** : \*\*bold\*\*
- _italic_ : \_\_italic\_\_
- `code` : \`code\`
- ```pre``` : \`\`\`pre\`\`\` (supports multiline)

There's currently no way to have nested formatting, it's API limitation.

There's currently no way to disable text formatting, except using nested formatting hack. Escaping doesn't work. See #2683.

I'm locking this issue. Feel free to open new issues related to text formatting.
