### ISSUE TITLE
Do not replace copyright, trademark symbols (©, ®, ™)

### ISSUE THREAD

**Issue by ralesk** [telegramdesktop/tdesktop#3300]
These characters are part of nearly every font and most charsets, their existence as emoji (or what looks like an emoji) is unnecessary.

### Expected behaviour

In text and in code blocks, ©, ® and ™ should appear, with the exact same font as the text.

### Actual behaviour

In both normal text, and even more unexpectedly in code blocks, and also in the text input widget, some weird replacement characters appear that look both unsightly and are out of place from the normal font.

![default](https://cloud.githubusercontent.com/assets/1564502/25185692/51160eea-251e-11e7-8acb-569ffe9b4d5b.png)

### Configuration

The issue is not desktop or theme dependent.

**Comment by noquierouser** [comment]
As far as I can tell, the app replaces this symbols with their emoji equivalents. This behavior is not overridden by the "Replace emoji" option in settings.

**Comment by ralesk** [comment]
Bump.
