### ISSUE TITLE
Black and White Icon for Windows 10

### ISSUE THREAD

**Issue by dottenbr** [telegramdesktop/tdesktop#3301]
The current blue telegram icon looks out of place in the Windows 10 system tray:

<img width="170" alt="old" src="https://cloud.githubusercontent.com/assets/9136094/25188764/7474a91a-2527-11e7-9293-bfb5905a6867.png">

You should consider replacing it with black and white to blend in like this and make that configurable in the settings:

<img width="170" alt="new" src="https://cloud.githubusercontent.com/assets/9136094/25188759/70ec0888-2527-11e7-9c6e-6a5431b45505.png">

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#1353 

Also use the template next time.
