### ISSUE TITLE
Quick way to return to previously opened chat

### ISSUE THREAD

**Issue by snarknn** [telegramdesktop/tdesktop#3303]
It's very common situation for me when I'm reading some channel, or chatting with someone and then some new messages are arriving that I have to open, sometimes check previous conversation and then reply. After that I want to return to chat I've read before, and only option I have now is to select it from chats list. It would be very helpful to have some quick way to return back to previous chat. I would say it may be keyboard shortcut but its obviously actual feature for mobile clients too, so i'd like to have some visual interface element for that as well as shortcut.

**Comment by stek29** [comment]
Reminds of "prev channel" button on TV remote

**Comment by misterbrownlee** [comment]
👍  engaged see #3118

**Comment by snarknn** [comment]
Checked shortcuts-default.json, `previous_chat` command is not does what I want.

**Comment by ElectronicRU** [comment]
Upping this, would also be useful when following a shared message to a channel and want to return back.

**Comment by snarknn** [comment]
Hi @stek29,
As far as I see this issue is not implemented yet. Why did you closed it?

**Comment by stek29** [comment]
@snarknn Because it was moved to #1060.
