### ISSUE TITLE
Incorrect link to source on nested forwarding

### ISSUE THREAD

**Issue by ruv** [telegramdesktop/tdesktop#3305]
### Steps to reproduce
1. Forward a message from a one channel into a second channel.
2. Forward it again from the second channel into a third channel (or group).
3. Click on the title of this message in the third channel.

### Expected behaviour
You should be navigated to the source message (either in the second or in the first channel).

### Actual behaviour
You are navigated into the first channel but in the wrong position (i.e. to some another message, not the original).

### Configuration
**Operating system:**
Windows 7

**Version of Telegram Desktop:**
1.0.29

**Comment by john-preston** [comment]
@ruv Thank you for your report! I'll fix that in the next stable version.
