### ISSUE TITLE
Style files creation

### ISSUE THREAD

**Issue by Elypson** [telegramdesktop/tdesktop#3309]
Hi,

this is merely a question regarding the code base. If this is the wrong communication channel, I would appreciate a hint to where this question might be better asked - or whether you even answer questions of this kind at all.

I am considering contributing to Telegram since I love it. While analyzing the software architecture I have a little question mark about the style files. I believe to understand that style files are read by your custom `codegen_style` executable, translated into corresponding cpp/h files with, among others, constants that are then again read to move widgets/elements in the UI to specific positions.

However, how do you create those style files?

I doubt that you put all the particular positions there manually. I would understand some QML-like scheme, but the files are also not just QML files by themselves, neither are they QT UI files.

Even if the UI design part of Telegram is not open for contribution, I would be personally interested in the answer.

Thanks in advance,
Michael Voelkel

**Comment by john-preston** [comment]
@Elypson Hi. Currently all the .style files are written by hand, like the rest of the code. There is no WYSIWYG editors for tdesktop UI controls.
