### ISSUE TITLE
Make it possible to add contacts using their username

### ISSUE THREAD

**Issue by Alirezaaa** [telegramdesktop/tdesktop#331]
You made username option, and We can search them, but there is no option to add contacts using their username.

**Comment by Aokromes** [comment]
+1 to this feature.

**Comment by sergioad** [comment]
Unposible, Telegram does not add the users what you have searched by it's name because privacy

**Comment by Alirezaaa** [comment]
@sergioad I think It's reasonable. Thanks for letting me know.

**Comment by sergioad** [comment]
You are wellcome
