### ISSUE TITLE
Missing messages in some channels

### ISSUE THREAD

**Issue by spiritualcoach** [telegramdesktop/tdesktop#3310]
### Steps to reproduce
1. I have experimented with different bots and my channels - I install newer 1.0.33 alpha on mac os 10.12.4
2. it doesn't show previous messages in one of my channels
3. However, if I reinstall the older version - it does show previous messages.

### Expected behavior
Shows all messages in the channel. DM me to get a link to the channel.

### Actual behavior
Shows only the latest one.

### Configuration
**Operating system:**
10.12.4

**Version of Telegram Desktop:**
1.0.33 alpha

**Used theme**:

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
> DM me to get a link to the channel

The only available way to "DM" you is through FB Messenger. Please post the link, or provide any other way to contact you.

> if I reinstall the older version - it does show previous messages

What is exact version?

**Comment by auchri** [comment]
> The only available way to "DM" you is through FB Messenger. Please post the link, or provide any other way to contact you.

https://t.me/Pavel_Holyavkin

**Comment by john-preston** [comment]
@spiritualcoach thanks for your report! You can see all the releases here: https://github.com/telegramdesktop/tdesktop/releases

Can you please check what version exactly stopped working? You can write me at https://t.me/preston and provide that information and the channel link.
