### ISSUE TITLE
Chats and message history not synced

### ISSUE THREAD

**Issue by gudvinr** [telegramdesktop/tdesktop#3311]
### Steps to reproduce
1. Open Telegram app
2. ...
3. No synced chats

### Expected behaviour
Chat list with messages history.

### Actual behaviour
No chats synced except pinned and new messages.

2-step is on, no strange sessions is present. Everything is ok on android and with 1.0.29.

### Configuration
**Operating system:** Ubuntu 16.04

**Version of Telegram Desktop:** 1.0.33 alpha

**Used theme**: No theme

**Comment by john-preston** [comment]
I've removed your DebugLogs archive link, because logs usually contain sensitive information.

Thank you for your report. This will be fixed in the next alpha version.
