### ISSUE TITLE
(gdb) /out/Debug/Telegram Segmentation fault.

### ISSUE THREAD

**Issue by whywhyy** [telegramdesktop/tdesktop#3314]
### Steps to reproduce
1. build finish,,40% -> 100% 
2. start out/debug/Telgram  ||  out/release/Telegram
3. Segmentation fault (core dumped) -> gdb Telegram

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Ubuntu 16.04
**Version of Telegram Desktop:**
clone 2 week ago
https://github.com/telegramdesktop/tdesktop/

**Used theme**:

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)
////////////////////////////////////////////////////////////////////////////////////////////////
(gdb) r
Starting program: /home/k1-ubuntu/TBuild/tdesktop/out/Release/Telegram 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
google_breakpad::MinidumpDescriptor::MinidumpDescriptor (this=0x57be6a0, 
    descriptor=...) at src/client/linux/handler/minidump_descriptor.cc:57
57	  assert(descriptor.path_.empty());

//////////////////////////////////////////////////////
(gdb) r
Starting program: /home/k1-ubuntu/TBuild/tdesktop/out/Debug/Telegram 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
google_breakpad::MinidumpDescriptor::MinidumpDescriptor (this=0x64e3100, 
    descriptor=...) at src/client/linux/handler/minidump_descriptor.cc:57
57	  assert(descriptor.path_.empty());

</details>

**Comment by auchri** [comment]
@whywhyy Please update to the latest version.

**Comment by whywhyy** [comment]
1. git fetch  -> git merge 
2. ..../tdesktop/out file ->  Trash
3. ..../tdesktop$gyp/refresh.sh
4..../out/debuge$ make
5. waiting ~~~~building ,,,,  :) 
i will be back ,,, haha,,

**Comment by nthtson** [comment]
@whywhyy : I got this problem because of Google Breakpad.

- Please try to reinstall "TBuild/Libraries/breakpad" with "./configure" (remove  *--prefix=$PWD*)
https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md#google-breakpad
