### ISSUE TITLE
Inline bot stickers show up blank

### ISSUE THREAD

**Issue by Tschrock** [telegramdesktop/tdesktop#3317]
### Steps to reproduce
1. Use an inline bot that returns stickers like @ponymotebot
2. The popup shows blank stickers

### Expected behaviour
The stickers should show up.

### Actual behaviour
The stickers are all blank.

### Configuration
**Operating system:** Ubuntu 16.10

**Version of Telegram Desktop:** 1.0.29

**Used theme**: Default

### Additional Info
It seems to work properly for stickers that have been loaded once before, but not new ones:
![screenshot from 2017-04-23 15-35-25](https://cloud.githubusercontent.com/assets/2406499/25316993/76fa3c80-283e-11e7-954a-1689acc914ba.png)

Left-click-and-hold previews work properly:
![screenshot from 2017-04-23 15-38-08](https://cloud.githubusercontent.com/assets/2406499/25317010/923e0ecc-283e-11e7-9297-6f1b01b5dab0.png)

This isn't just me, we have others in our chat having the same issue:
![photo_2017-04-23_16-08-06](https://cloud.githubusercontent.com/assets/2406499/25317047/1351cbc0-283f-11e7-876e-d19f22126b35.jpg)

**Comment by Shikogo** [comment]
Windows 10, I have the same issue with the same bot.

**Comment by aNNiMON** [comment]
The problem still exists on Telegram Desktop 1.3. Tested on Linux and Windows.

![](https://user-images.githubusercontent.com/1321838/40875320-1719130e-6681-11e8-91f4-38b82235a357.gif)

Preview in popup only appears after sending sticker and repeat same query to inline bot.

**Comment by john-preston** [comment]
@aNNiMON Thanks for the bot. I'll look into that.
