### ISSUE TITLE
[Windows 10 Creators Update] Video Player on Telegram Desktop lags and skipping frames

### ISSUE THREAD

**Issue by DutyCorp** [telegramdesktop/tdesktop#3318]
Hi Telegram Desktop developers,
I have an issue with Telegram Desktop's video player. When i play any video with the video player, it always lags when opening and skipping frames.

Steps to reproduce :
1. Open Telegram Desktop
2. Open any chat or channel
3. Play any .mp4 video there using Telegram's video player

Expected behaviour :
The video player runs well and no skipping frames

Actual behaviour :
The video player lags when opening any video and always skipping frames

Configuration
**Operating system**: Windows 10 Home Version 1703 (Creators Update)

**Version of Telegram Desktop**: 1.0.29

**Used theme**: Default Telegram Theme

**Additional notes**: This is not happening in previous version of Windows 10 (Anniversary Update). I think it's because of new Windows 10 codec issue or in Telegram Desktop itself.

</details>

Update : Sorry, i put a typo on Telegram Desktop version. It's 1.0.29, not 1.0.27

**Comment by DutyCorp** [comment]
Dear Telegram Developers,

I just wanna inform that this issue still exist on Telegram Desktop version 1.1

Thanks

**Comment by stek29** [comment]
Do gifs have this issue?

**Comment by DutyCorp** [comment]
Dear stek29,

GIFs work just fine. I guess it's internal video player issue

**Comment by DutyCorp** [comment]
Dear Telegram Desktop developers,

I just wanna give an update that this issue also exists on audio player

**Comment by DutyCorp** [comment]
Dear Telegram Desktop developers,

Thank you for version 1.1.7. The skipping frame issues are reduced, but i still see some frame skipping at the beginning and i probably know why.

When i browsing some video from internal video library, moves from several video and go back, the video work just fine with no frame skipping issues. But when i move far away from that video then go back or clicking the video file from group/channel/chat, the video frame reloads and frame skipping issue exist.  I guess it's the file reader issue that needs to be fixed.

Oh and also the audio player issue is still exist on version 1.1.7

Thanks
