### ISSUE TITLE
[Mac OS] <enter>/<return> to send messages behavior is erratic

### ISSUE THREAD

**Issue by antonioribeiro** [telegramdesktop/tdesktop#3319]
### 1)
1. Type something, type space (sometimes)
2. Hit ENTER
3. It goes to the next line

### 2)
1. Paste an URL (every time)
2. Hit ENTER
3. It goes to the next line

### 3)
1. Paste some text with a <space> in the end of the line (every time)
2. Hit ENTER
3. It goes to the next line

### 4)
1. Paste some text (sometimes)
2. Hit ENTER
3. It goes to the next line

### Expected behaviour
ENTER should send the message no matter of what. 

### Actual behaviour
It goes to the next line (sometimes)

### Configuration
**Operating system:**
Mac OS 10.12.2

**Version of Telegram Desktop:**
2.94.92789

**Used theme**:
Default

**Comment by auchri** [comment]
@antonioribeiro That's a different app

**Comment by john-preston** [comment]
@antonioribeiro You can try Telegram Desktop from https://desktop.telegram.org

**Comment by antonioribeiro** [comment]
https://desktop.telegram.org sends me back here, I'm very confused now...

**Comment by john-preston** [comment]
@antonioribeiro What you mean by "sends"? Also you can download a release from https://github.com/telegramdesktop/tdesktop/releases

**Comment by antonioribeiro** [comment]
So, the thing (I think) is: we have two different Telegram softwares for all platforms: 

**Telegram Desktop (Official Messenger)**: https://telegram.org/apps && https://macos.telegram.org/

and

**Telegram Messenger**: https://desktop.telegram.org/ && https://telegram.org/dl/desktop/mac

Those are not the same software, right? 

This is highly confusing, guys! 

Things get odder when you try to install Desktop, having Messenger, and Mac OS tells you cannot have both...
