### ISSUE TITLE
Ability to complete ignore groups with turned off notifications

### ISSUE THREAD

**Issue by ggeldenhuis** [telegramdesktop/tdesktop#3320]
Currently when you turn off notifications for a group chat it still shows the number of unread chats in the icon on the taskbar on a mac. From my point of view if I turn off notifications I don't want to be aware for anything that goes on in the group, other than seeing the number of unread messages next to the group when I open up the application. If a "silenced" group still contributes to the number of unread messages that I see in the taskbar then really, notifications has only been partially turned off.

**Comment by john-preston** [comment]
@ggeldenhuis If you use Telegram Desktop (an app from https://desktop.telegram.org) you can switch off a checkbox "Include muted chats in unread count" in Settings.

**Comment by ggeldenhuis** [comment]
Awesome! Thanks.
