### ISSUE TITLE
Tray icon should not be a jpg

### ISSUE THREAD

**Issue by light2yellow** [telegramdesktop/tdesktop#3322]
That's how my screen looks like (4k display):

![screenshot_20170425_142955](https://cloud.githubusercontent.com/assets/10786469/25385466/6c7956b0-29c4-11e7-9399-361f8c1e170d.png)

And that's how the tray icon looks like in comparison to others:

![screenshot_20170425_142806](https://cloud.githubusercontent.com/assets/10786469/25385494/8621b03a-29c4-11e7-8c5d-f4cb35aaaad3.png)

Is there any way upstream ships with an svg instead?
Or any other appropriate fix, so that it looks healthy?

I'm using telegram-desktop-bin package from AUR (it installs all versions of icons, but still).

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#2230

**Comment by light2yellow** [comment]
Sorry, searched for the "icon" and didn't find a relevant issue. Thanks for a quick response.
