### ISSUE TITLE
channel problem

### ISSUE THREAD

**Issue by yarat** [telegramdesktop/tdesktop#3325]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by yarat** [comment]
I have a problem with my channel in telegram...a few months ago i removed most of my members....now i have started posting new comments...the problem is that when people want to enter the channel they see a massage which tells them this channel doesn't exist....how can i solve it?

**Comment by yarat** [comment]
could you please help me?

**Comment by auchri** [comment]
That's not related to telegram desktop.

**Comment by yarat** [comment]
do you mean my question?
