### ISSUE TITLE
[Feature request] Better forward Privacy

### ISSUE THREAD

**Issue by Nehemoth** [telegramdesktop/tdesktop#3327]
### Steps to reproduce
1. Select a message that you want to forward
2. Choose the option to forward that message
3. Select the conversation which will received the forward message
4. Send the Message
5. Above the message that you just forwarded you will see the text: "Forwarded Mesassage From Contact Name".
6. Click the Contact Name from whom the message was fordwared
7. You will be able to see the contact details even if isn't in your contact list

### Expected behaviour
You shouldn't be able to see from whom a contact was sent

### Actual behaviour
You can see the contact details from whom a message was forwarded

### Configuration
**Operating system: Windows 7**

**Version of Telegram Desktop:*1.0.29*

**Used theme**:None

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
API issue, feature and a duplicate

**Comment by Nehemoth** [comment]
@stek29 Thank you. Sorry for the Duplication.
