### ISSUE TITLE
[Feature request] Archive Conversations

### ISSUE THREAD

**Issue by Nehemoth** [telegramdesktop/tdesktop#3328]
### Steps to reproduce
1. Select a conversation from the main window
2. A menu will open 
3. 

### Expected behaviour
The Menu should bring an archive Option
You should be able to select multiple conversations

### Actual behaviour
The options to acomplish this aren't there

### Configuration
**Operating system: Windows 7**

**Version of Telegram Desktop:*1.0.29*

**Used theme**:None

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
@Nehemoth Somethimes I want that people would use the template.

**Comment by auchri** [comment]
@Nehemoth Somethimes I want that people would use the template.

**Comment by Nehemoth** [comment]
@auchri better.

**Comment by stek29** [comment]
What do you mean by "archive option"?

**Comment by Nehemoth** [comment]
@stek29 You will have a section called something like "Archived Conversations" [in the main window] where you will go to see all your archived conversations.

**Comment by auchri** [comment]
No api for that

**Comment by dogancelik** [comment]
This would be a good addition, I support this.
