### ISSUE TITLE
[Feature request] Forward to Multiple Conversation

### ISSUE THREAD

**Issue by Nehemoth** [telegramdesktop/tdesktop#3329]
### Steps to reproduce
1. Select a message that you want to forward
2. Choose the option to forward that message
3. 

### Expected behaviour
After selecting the first conversation to receive the forward, I should be able to select more conversations.

### Actual behaviour
I don't have the option to select multiple conversations before sending the forward

### Configuration
**Operating system: Windows 7**

**Version of Telegram Desktop:*1.0.29*

**Used theme**:None

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
@Nehemoth Somethimes I want that people would use the template.

**Comment by Nehemoth** [comment]
let's edit
Thank you.

**Comment by kirsan31** [comment]
#1841?
