### ISSUE TITLE
Windows 10 border on another desktop

### ISSUE THREAD

**Issue by bakl** [telegramdesktop/tdesktop#333]
![screen](https://cloud.githubusercontent.com/assets/10196392/5437207/73068440-847f-11e4-94b4-a88887ea5cd5.png)

Some problem with win 10 virtaul dektop.
When i am selected another virtual dektop i see telegram dektop border

**Comment by telegramdesktop** [comment]
Please check is it still there in 0.7.10?

**Comment by auchri** [comment]
Fixed with 0.8.45
