### ISSUE TITLE
Toggle/Collapse downloaded images/media in chat

### ISSUE THREAD

**Issue by FabianMeul** [telegramdesktop/tdesktop#3330]
### Steps to reproduce
1. Open a chat where the last message is e.g. an @gif entry
2. Tap a toggle icon/button that collapses the image
3. Profit

### Expected behaviour
The behaviour is requested as above. ;-)

### Actual behaviour
The behaviour is requested as above

### Configuration
**Operating system:** MacOS 12.0.4

**Version of Telegram Desktop:** 1.0.29

**Used theme**: Default

I think this could be a great addition to Telegram, as the app makes it super easy to spam "gifs" (which is not necessarily a bad thing!) but gives no option to hide those gifs, besides removing them completely.

**Comment by FabianMeul** [comment]
#1535

**Comment by stek29** [comment]
Does any other Telegram app have it? Could you provide better explanation (maybe something visual)

**Comment by FabianMeul** [comment]
No, I think we'd be the first to implement this. Slack has a comparable functionality, where you can toggle the visibility of media files.

I'll try to whip up a visual proposal tonight. :-)

**Comment by FabianMeul** [comment]
I hope these images explain the concept a little better. :-)

Toggle Open
![media-open](https://cloud.githubusercontent.com/assets/756903/25454011/5a1a717c-2acb-11e7-9afa-9064d89461ca.png)

Toggle Closed
![media-closed](https://cloud.githubusercontent.com/assets/756903/25454016/611b087e-2acb-11e7-8745-41dd0d9b3bf1.png)


PS: Thx to Dmitriy Markov for providing a Sketch design file!
(https://dribbble.com/shots/3289878-Telegram-desktop-messenger-Sketch-included)

**Comment by stek29** [comment]
#687, but this one is much cleaner

**Comment by FabianMeul** [comment]
If this ticket is under serious consideration, I'm willing to spend some extra time to visually refine the proposal :-)

Are there design guidelines for interface proposals?

**Comment by john-preston** [comment]
@FabianMeul I'm afraid it is not under serious consideration for now, sorry.

**Comment by charlesmims** [comment]
I'd like to piggy back on this proposal and ask for slack-like "/" commands    /collapse in this case
