### ISSUE TITLE
Reset/Clear frequently used Emojis

### ISSUE THREAD

**Issue by LeonTheOriginal** [telegramdesktop/tdesktop#3331]
It might be helpful to have an option to reset the "Frequently used" lists at the top of the Emoji/~~Sticker~~ selection to their initial state, so they will be populated anew.

~~For frequently used Stickers I'm not sure if this is doable as they are synchronized, so there might be the need for an API.~~ _Edit:_ Already possible
For frequently used Emojis it should be possible since they are stored only locally.

**Comment by john-preston** [comment]
@LeonTheOriginal It is already possible for the stickers, click on the settings button in the stickers panel.

**Comment by LeonTheOriginal** [comment]
Oops, totally missed that. I made a quick edit to specifically address the emoji list.

**Comment by LeonTheOriginal** [comment]
I didn't had time to test it. Although this is a minor issue, it seems that it still exists.

**Comment by Oubayda-Khayata** [comment]
Sadly, this issue still exists

**Comment by RememberTheAir** [comment]
@Aokromes can you reopen?

**Comment by vn971** [comment]
This issue is indeed still relevant...

**Comment by MateusAuri** [comment]
Can confirm it's still relevant.
I have a pig emoji loitering around in 4th place in my recent emojis panel, and honestly can't remember the last time I used it. Meanwhile, I use the trademark emoji all the time and it just never appears in there.

**Comment by ignoregami** [comment]
My recently used emojis appear to be static (too?) on one computer.  I'd rather not reset my entire Telegram profile just to clear a corrupt "recently" used emoji list.  It wouldn't be an issue if it didn't impact the inline picker.  For example, typing ":lau" lists laughing emoji with the most typical (XD) emoji at the very end of the list.  The crying-laughing emoji is the first on the list.

Picking the wrong laugh can hive dire consequences.

**Comment by spooler** [comment]
Facing the same problem. Recent emojis seems to be frozen, which makes the "recently used" feature not just useless but annoying

**Comment by vn971** [comment]
@stale Issue is still there.

**Comment by anisul-islam-prog** [comment]
I cleared my recent emoji list from mobile hoping that it would be cleared from desktop too. Unfortunately, it is not cleared.

**Comment by Neurotoxin001** [comment]
We still need it

**Comment by MateusAuri** [comment]
we still need it 5 years later, meanwhile they made the emoji menu worse by cluttering it with all the pro stuff

**Comment by robkemme** [comment]
For some reason the recently used emoji performs unpredictable on Telegram Desktop. Would love an option to clear the list.

**Comment by Neurotoxin001** [comment]
I got recent emojis from my old account to my new account, how is it possible even if old emoji pack was removed and when I trying to send emojis from this pack I got error:
`[2022.11.23 01:31:56] RPC Error: request 13691 got fail with code 400, error DOCUMENT_INVALID`

![image](https://user-images.githubusercontent.com/39812401/203434939-931ba2f5-0bad-48f6-88ce-d01dbca32508.png)

4.3.2

**Comment by Neurotoxin001** [comment]
4.6 introduced Emoji Categories and it's beautiful but there is still no "clear recent emojis"...

**Comment by qprjct** [comment]
2023 and this is still an issue! I'd like to ask for a solution to reset / delete frequent emojis as they're stuck and don't change. The same emojis always are on top with months / years of not being used.

Thank you

**Comment by thanks173** [comment]
Just solved by log out and login again.
The emoji list when I type the colon symbol got cleared.

**Comment by qprjct** [comment]
> Just solved by log out and login again. The emoji list when I type the colon symbol got cleared.

Thx for your reply! Will try

**Comment by Maksim-Vinnikov-idf** [comment]
> Just solved by log out and login again. The emoji list when I type the colon symbol got cleared.

Thanks! It's work on desktop for windows. After re-login frequently used emoji list did update.

**Comment by Neurotoxin001** [comment]
But that's not the solution. We need a button for cleaning recent emojis. Like on iOS.

**Comment by Maksim-Vinnikov-idf** [comment]
> But that's not the solution. We need a button for cleaning recent emojis. Like on iOS.

I agree. We need the button. 🔘

**Comment by palbergstrom** [comment]
Very annoying issue. Agree, a button for cleaning recent emojis is missing.

**Comment by Neurotoxin001** [comment]
Seems like fixed

https://github.com/telegramdesktop/tdesktop/commit/23dbe4742aeec4d24fddc9db4871ef2a2ac37507
`"lng_emoji_reset_recent" = "Reset recents";`
