### ISSUE TITLE
Have an option to configure default Delete action on app level

### ISSUE THREAD

**Issue by iklimchuk** [telegramdesktop/tdesktop#3334]
![screenshot - 4_27_2017 6_05_59 pm](https://cloud.githubusercontent.com/assets/10230808/25493389/4631a436-2b76-11e7-8006-d8c26e54758d.png)
### Steps to reproduce
1. Open any chat
2. Right-click on your message and select "Delete"

### Actual behavior
I see confirmation dialog with unchecked "**Delete for ....**" checkbox by default

### Expected behavior
I'd like to have a way to configure default value of this check box. As for me (and I believe for other users as well) 99.(9)% of cases when I delete a message - my intention is to have it deleted for all chat members, deleting of message just for me is quite useless (IMHO, at least I cannot imagine a use case when I really need it). But currently I should manually select this option (Delete for all) every time, which is quite annoying. Moreover, if for some reason you missed this checkbox and deleted a message from your chat only (what happens pretty often when you're in rush and trying to delete a message as fast as it is possible) - you basically have no ways to delete it from other members chats anymore...and you're in trouble :)
It will be really great to have an option in settings which allows to configure default action for delete (for me/for all) and stop asking user about it every time he/she deletes a message.

### Configuration
**Operating system:**
Win10

**Version of Telegram Desktop:**
1.0.29

**Used theme**:
default

**Comment by matheus208** [comment]
It's really frustrating UX because when I click delete my instinct tells me to instantly click "OK", which leads to the message being deleted only for me and I can't find it again to delete it for everyone else.

**Comment by stek29** [comment]
@matheus208 even if you found it, API won't allow to revoke messages you've already deleted for yourself, even if you do it instantly after deletion without revoke.

**Comment by dogancelik** [comment]
Native Mac client has this checked by default which I like, but ability to change the default state is really good for user experience and less frustrating for users who prefer it checked.

**Comment by stek29** [comment]
@john-preston What do you think about remembering last checked/unchecked state?

**Comment by KimTheFirst** [comment]
I have just encountered this issue directly after sending a very embarrassing message to the wrong person, deleting it in a panic, and then realizing that I had now made the message undeletable. 

I can now definitively say that in my opinion, having this option off by default is completely retarded to the utmost extreme in all use cases that I can possibly think of. 

Is there any compelling scenario whatsoever in which it would be desirable to delete a message for yourself and not for the other person?

**Comment by RememberTheAir** [comment]
> I can now definitively say that in my opinion, having this option off by default is completely retarded to the utmost extreme in all use cases that I can possibly think of.

I generally do not like statements that are this extreme but in this case I absolutely agree with @KimTheFirst, when people delete a message in a private chat they want it removed for the other peer too. I cannot think about any other reason to delete a message you've sent. I understand the desktop app needs to be consistent with Android/iOs behaviour (box unchecked), but I really hope they are going to change the default there too. The MacOS client and TGX for Android already check that box by default.

It is really, really frustrating to realize that you can't delete for the other peer a message you've just deleted without checking that box

**Comment by brownsugar** [comment]
I think this should be accepted since the mobile version is checked by default, then when I switched to desktop version, I always forgot to check it, and my messages always only invisible for me...and it can't even be undone.

**Comment by RememberTheAir** [comment]
@brownsugar on mobile it's unchecked by default. At least on the official apps

**Comment by brownsugar** [comment]
@RememberTheAir I'm using Telegram X, isn't that Telegram official app?!

**Comment by RememberTheAir** [comment]
@brownsugar yes it's official but it's also an experimental app which has separate development process and is more free to add features and experiment with different behaviors. The two main mobile clients (Telegram for Android and Telegram for iOS) has that tick disabled by default

**Comment by RememberTheAir** [comment]
@brownsugar yes it's official but it's also an experimental app which has separate development process and is more free to add features and experiment with different behaviors. The two main mobile clients (Telegram for Android and Telegram for iOS) has that tick disabled by default

**Comment by Andikki** [comment]
I'm pretty sure the number of users who dug an embarrassing hole for themselves by accidentally picking "delete for me" instead of "delete for all" far exceeds the number of users who have any use for "delete for me" feature ever.

**Comment by nyuszika7h** [comment]
This is still relevant.

**Comment by soredake** [comment]
https://github.com/telegramdesktop/tdesktop/pull/17268

**Comment by sakhdevel** [comment]
Absolutely agree. It is a very bad UX-problem.

**Comment by RememberTheAir** [comment]
It looks like the default status was changed in f064575

**Comment by RememberTheAir** [comment]
I wonder why this change has been pushed now btw, considering the mobile apps still default to "unchecked". Right now we have to get used to a different behavior on mobile and desktop, for a feature that will either:
- remove messages that cannot be recovered (in case you toggle the checkbox by mistake)
- prevent you from revoking a message you sent (in case you delete a message without toggling the checkbox)

I believe this is not a good idea, unless the default behavior is going to change on the mobile apps too
