### ISSUE TITLE
Cannot type accented characters

### ISSUE THREAD

**Issue by mardy** [telegramdesktop/tdesktop#3335]
This happens on a computer with a Finnish keyboard, with dead keys:

1. Press the dead key "\`"
2. Press "a"

### Expected behaviour
"à" gets inserted into the message edit line

### Actual behaviour
"a" gets inserted

I've also tried to switch to the Finnish layout without deadkeys, and I tried to insert accented characters by pressing Compose, "\`", "a", but that doesn't work either: I get "\`a" on the edit field.

### Configuration
**Operating system:** Ubuntu 16.04

**Version of Telegram Desktop:** 1.0.29 (but this happened with previous versions too)

**Used theme**: default

**Comment by Aokromes** [comment]
#1041

**Comment by Aokromes** [comment]
^^
