### ISSUE TITLE
[Feature Request] Option to use System/EmojiOne emoji set?

### ISSUE THREAD

**Issue by sonic2kk** [telegramdesktop/tdesktop#3336]
The current emoji set that Telegram uses on Web, Android and Desktop are not that great. The iOS emoji set is notoriously disliked from what I know from personal experience and what I have read on the Internet in the past (most of my family use iOS and they always complain about the emojis). The emojis put me off using Telegram for quite a while and they are part of what made me switch to using the [FOSS Telegram Android fork](https://github.com/Telegram-FOSS-Team/Telegram-FOSS).

I think it would be a good idea if Telegram had a streamlined emoji set, so I understand why they have kept this emoji theme. However I think it it would be beneficial to have a choice of which emoji sets to use. Various Linux desktops such as KDE come with the ability to choose which emoji set the system will use. It would be a good idea, in my opinion, to allow users to choose whether to use the default Telegram emoji set (the iOS emojis), the system emoji set or a standard emoji set such as EmojiOne. The FOSS fork of the Telegram Android app uses the EmojiOne set but sadly does not allow for users to choose whether or not to use the system emojis, which can vary from ROM to ROM (though in most cases it's the Google emoji set, I forget the name).

One of the issues I can foresee with this would be the possibility of certain emojis not showing up on different platforms. Maybe someone sends their friend an emoji that isn't in their set or vice versa. It may lead to some frustration. To combat this, there could be a warning when choosing a different emoji set that certain users may not see the same emojis.

I'm unsure of how technically possible it is to use the System emojis, as by having a skim through the source code I could see the emojis are taken from a webp image set. However I thought it may be a good idea to suggest at least the possibility of selecting a custom emoji set. Perhaps it could be added as part of a theme, too? This would allow further customisation of Telegram, which is one of the reasons I love the platform so much.

I looked around in the open issues and couldn't find anything similar to this, and I did some Google searching too and found nothing. You could argue that emojis are not overly important but they are increasingly being used to communicate, and so I feel having a choice of emoji sets is a good idea for users.

Plus, you know, the legacy version of EmojiOne is open source. I believe the current emoji set is licensed.

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#2111 and others.

**Comment by stek29** [comment]
EmojiOne isn't free anymore, and tbh I dislike them really much. It would be better to use Twimoji, if Telegram ever desides to switch.
