### ISSUE TITLE
[Feature request] A button for changing color of all emoji

### ISSUE THREAD

**Issue by toby3d** [telegramdesktop/tdesktop#3339]
At the moment, if I want to change the skin color for emoji, I MUST repeat the sequence "long press -> color choice" FOR EVERY emoji.
![image](https://cloud.githubusercontent.com/assets/5412322/25541815/998a31b8-2c69-11e7-9248-7ef7b10d1940.png)

Why not make a separate button that changes the color for all emoji at once?
![image](https://cloud.githubusercontent.com/assets/5412322/25541882/ce24869e-2c69-11e7-842f-f252255a95a5.png)
![image](https://cloud.githubusercontent.com/assets/5412322/25541891/d3d68646-2c69-11e7-8144-c20fc0fc78fa.png)

**Comment by ratVien** [comment]
Up! I'm using telegram descktop mostly and it's very annoying to choose skin color every time when I want to type emoji. I also would be appreciated if you add green color too! :)

**Comment by Denyerec** [comment]
This thread links to another thread that links *back* this this thread, with no resolution. Has it been accepted as a feature request and if so, where does one see that so I don't accidentally ressurrect a zombie issue in future!

**Comment by RememberTheAir** [comment]
> This thread links to another thread

Nope, this thread doesn't redirect intentionally to any other similar issue - it's just github mentioning the issues where this thread has been referenced

> Has it been accepted as a feature request

Apparently not, but this issue should stay open anyway. @Aokromes can you pleas ereopen it? It has been closed by the stale bot

**Comment by Denyerec** [comment]
Ahh OK, so github linked back to #7645 because ilya-fedin mentioned this ticket (#3339)  - Understood! Regarding skintone emotes they can be copied and pasted from any UTF16 character lookup site successfully, but so far I've not found a way to do it within the app (Android) or to set a default.

**Comment by Philoceratops** [comment]
Any news?

**Comment by olhapi** [comment]
It's really annoying to choose a skin color every time you add an emoji, so just do it
![image](https://user-images.githubusercontent.com/4780263/111029302-b9fc7e00-8404-11eb-8dfc-178990398267.png)

**Comment by TillmanJex** [comment]
Please do this

**Comment by lipemorais** [comment]
Please to this we are almost in 2022

**Comment by Philoceratops** [comment]
Let's all congratulate each other with the 2022 New Year when it comes, let
this thread be useful for something, at least.

пт, 26 нояб. 2021 г., 16:41 Felipe de Morais ***@***.***>:

**Comment by Ryder17z** [comment]
And here we are in 2022 and it's still a problem. I want to disable the skin color picker.

**Comment by gir489returns** [comment]
This is still an issue, fix this already. 👍🏻

**Comment by christophpickl** [comment]
please, please fix this.
whatsapp can do it, so you can too.
🖖🏿🖖🏽🖖🏻

**Comment by ZehMatt** [comment]
Please...

**Comment by kkdd-ddkk** [comment]
bump

**Comment by judielaine** [comment]
Please.

**Comment by samtaggart** [comment]
+1, we need this!

**Comment by kelke** [comment]
I cant believe this feature is not yet a thing..

**Comment by Kirill-Znamenskiy** [comment]
+1

**Comment by yooakim** [comment]
Any chance this will be fixed?

**Comment by MaxBlazer** [comment]
Please do this, guys.

**Comment by tuanacetinkaya** [comment]
2023 March and this is still open? I get it, most of the users doesn't care about small life upgrades that will save a total of 30 seconds when you think about. But what makes telegram a better option and pushes me to communicate with my contacts through this platform (which means 0-cost new users for you guys!) is that I think telegram cares about these convenient features. Making the UX more smooth. 

P.s: it's actually not so hard to put a generic empty emoji and ask: do you want to change all colors or only the default settings.

That way we can both select a new color to apply to all emojis and keep the ones we use different and set default for all previously untouched emojis.

(Yes, life is that easy for me so I care this much about my emoji colors lol)

**Comment by genebean** [comment]
Here’s hoping this happens 🤞🏻

**Comment by moontr3** [comment]
still waiting

**Comment by toby3d** [comment]
By the way, the same Telegram X has been able to do this for a long time. I don't understand what prevents the same option from being displayed by right-clicking on the desktop.

https://github.com/telegramdesktop/tdesktop/assets/5412322/70a80b74-6e6e-4e8c-8f96-7c6357c3edcf

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/bb4476890fb12070a497251b9a9093bcaf5b83eb

**Comment by djsiropchik** [comment]
Hey devs. Please make the same function for the classic telegram app. Why is possible in telegram x and not possible here for years. Come on guys

**Comment by john-preston** [comment]
@djsiropchik It is possible now:

![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/046ec592-eb0e-41ea-96d3-fc3da7bcf0cc)

**Comment by djsiropchik** [comment]
> @djsiropchik It is possible now:
> 
> ![image](https://user-images.githubusercontent.com/17900494/266909667-046ec592-eb0e-41ea-96d3-fc3da7bcf0cc.png)

And where is it? Did you read the post? Did you look a video from the "toby3d"? Please do it and after comment

**Comment by john-preston** [comment]
@djsiropchik cmon, I've shown in the screenshot where it is. In the Emoji & People section on the right there is a button which shows a picker for all emoji at once when you press it. Try in the latest Telegram Desktop version, 4.9.5, you can confirm the version in the side menu on the bottom.

**Comment by djsiropchik** [comment]
> @djsiropchik cmon, I've shown in the screenshot where it is. In the Emoji & People section on the right there is a button which shows a picker for all emoji at once when you press it. Try in the latest Telegram Desktop version, 4.9.5, you can confirm the version in the side menu on the bottom.

![Screenshot_2023-09-11-08-17-59-37_ffb2f5e1b976ff98cfc94f359fbce8de](https://github.com/telegramdesktop/tdesktop/assets/10560876/1c1a4724-f875-435a-ae2e-d5d2a0910319)
Show me this

**Comment by john-preston** [comment]
"This" is a frame from how it is done in Telegram X for Android. In Telegram Desktop it is done in a _different_ way, but it is still done, in the latest versions. It is done exactly like it is asked by @toby3d in the first message of this issue - where he wrote "Why not make a separate button that changes the color for all emoji at once?" -- this button was added in the latest versions and I told you two times already, where it is.

You press this button:

![image](https://github.com/telegramdesktop/tdesktop/assets/17900494/40ab0f89-ff3d-45e9-87a6-bc1f525a8e8d)

and choose a skin color for all emoji at once. So this issue is closed and done - not in form of "Apply to all" button in a single emoji skin color choose dropdown, but in a form of a separate button for all emoji at once.

**Comment by Philoceratops** [comment]
> "This" is a frame from how it is done in Telegram X for Android. In Telegram Desktop it is done in a _different_ way, but it is still done, in the latest versions. It is done exactly like it is asked by @toby3d in the first message of this issue - where he wrote "Why not make a separate button that changes the color for all emoji at once?" -- this button was added in the latest versions and I told you two times already, where it is.
> 
> You press this button:
> 
> ![image](https://user-images.githubusercontent.com/17900494/266915699-40ab0f89-ff3d-45e9-87a6-bc1f525a8e8d.png)
> 
> and choose a skin color for all emoji at once. So this issue is closed and done - not in form of "Apply to all" button in a single emoji skin color choose dropdown, but in a form of a separate button for all emoji at once.

Ok, that last screenshot is a bit more helpful. Thanks.

 Although I don't have that button in my Telegram... yet. Hope it'll roll out on my phone soon enough.

**Comment by john-preston** [comment]
@Philoceratops What phone?! This issue and everything in it is about Telegram Desktop, the app for Windows / macOS / Linux. You can try it from https://desktop.telegram.org

**Comment by djsiropchik** [comment]
> @Philoceratops What phone?! This issue and everything in it is about Telegram Desktop, the app for Windows / macOS / Linux. You can try it from https://desktop.telegram.org

My bad. I'm talking about Android client. It's still unavailable there: (

**Comment by Philoceratops** [comment]
Aaah. Gotcha.
