### ISSUE TITLE
Inverted string characters of last message in group list

### ISSUE THREAD

**Issue by k06a** [telegramdesktop/tdesktop#3340]
### Steps to reproduce
1. Don't know (seen it twice on the same user https://t.me/Gorky_Cow)
2. xxx
3. xxx

### Expected behaviour
Tell us what should happen

I should see user name and first words of last group message

### Actual behaviour
Tell us what happens instead

I see inverted string

### Configuration
**Operating system:**

OS X 10.12.4

**Version of Telegram Desktop:**

1.0.29

**Used theme**:

Default

<img width="1201" alt="2017-04-29 0 14 53" src="https://cloud.githubusercontent.com/assets/702124/25547716/78f29adc-2c71-11e7-8ff1-ef3c0006b46f.png">

**Comment by stek29** [comment]
Just a kid playing with Unicode.

**Comment by k06a** [comment]
@stek29 I don't think this user plays with its every message. This is support chat for television streaming service.

**Comment by stek29** [comment]
@k06a he probably has RTL Mark in his name
