### ISSUE TITLE
one single notification by multiple devices

### ISSUE THREAD

**Issue by y1n0** [telegramdesktop/tdesktop#3341]
I'm thinking that there should be an option that allows to disable notifications when there are multiple active sessions on different devices, and only one of these devices should receive the notification. It is annoying to receive the same notification in so many devices.

### Expected behaviour
when there are multiple connected devices, and there is a new notification, only one of them should receive the notification (and then sound or popup or whatever)

### Actual behaviour
when there are multiple connected devices, and there is a new notification, they all receive it (unless you're right in the concerned discussion)

**Comment by stek29** [comment]
#277
