### ISSUE TITLE
[feature request] counter of pictures in twitter preview

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#3345]
https://twitter.com/lotsohotso/status/591334588150108162
usually I don't know what a tweet contains more than one picture and don't open it in browser
![image](https://cloud.githubusercontent.com/assets/10371194/25600531/66698ca8-2eed-11e7-8415-0d44c0cb2f1b.png)

I propose to add the counter
![image](https://cloud.githubusercontent.com/assets/10371194/25600709/d04a00d4-2eee-11e7-9a7e-a4a348390100.png)
or
![image](https://cloud.githubusercontent.com/assets/10371194/25600715/dfff0100-2eee-11e7-95b5-92a9ab8f8323.png)

**Comment by f242** [comment]
instagram previews have same problem with posts that contains more than one photo

**Comment by stek29** [comment]
API issue.
Previews are generated on server side, and querying additional info on client safe would be bad for privacy.

**Comment by 23rd** [comment]
Is it still problem on server side? 
Because Android client can generate album from Twitter or Instagram URL if post has more than 1 picture.

**Comment by stek29** [comment]
I'd still call it server site issue since current implementation is very hacky: multiple photos are sent as Instant View, and there is no flag indicating that -- domain names are hardcoded in apps.

But now this issue is related to #3492.

**Comment by 23rd** [comment]
This issue can be closed now.
https://github.com/telegramdesktop/tdesktop/commit/bf31722931b6cae2ac56bc52de53679c98ef19fd
https://github.com/telegramdesktop/tdesktop/commit/251f51ca1bae3788f84e41dd7b40b44081ac4c3e
