### ISSUE TITLE
improvement:  can "tag" or assign names to non-phone contacts

### ISSUE THREAD

**Issue by DiegoAccorinti** [telegramdesktop/tdesktop#3353]
### Steps to reproduce
1.   Is a proposal for improvement

### Actual behaviour
Sometimes you are the manager of a group and you have 50 users. And you need to know who is who, you can not remember the nicknames of everyone. Then there is no way to assign a name to non-phonebook users.

### Expected behaviour
It would be good if a group administrator can "tag" or assign names (only he/she sees) to non-phone contacts that have only aliases.

**Comment by stek29** [comment]
API issue and a duplicate

**Comment by DiegoAccorinti** [comment]
ah! tnks.  #3168
