### ISSUE TITLE
Ruble (russian currency) symbol doesn't appear on macOS

### ISSUE THREAD

**Issue by alivekenny** [telegramdesktop/tdesktop#3354]
### Steps to reproduce
1. Type or paste ruble symbol on macOs: ₽ (U+20BD)

### Expected behaviour
Ruble symbol should be appeared

### Actual behaviour
Square symbol appears

### Note
Ruble symbol along with many other characters appears correctly on Windows version of Telegram

### Configuration
**Operating system:** macOS 10.12.3

**Version of Telegram Desktop:** 1.0.29

![bitmap](https://cloud.githubusercontent.com/assets/21039303/25735702/8a30d7b8-3186-11e7-9092-bb7ab6d6476a.png)

**Comment by stek29** [comment]
#1791

**Comment by fitojb** [comment]
Telegram should just use Noto instead, which is the [successor](https://github.com/googlei18n/noto-fonts/blob/master/FAQ.md) project to Droid and Open Sans. Noto aims to cover the complete Unicode character set, and its UI fonts do include the rupee sign.

**Comment by stek29** [comment]
@fitojb Rupee isn't Ruble, but I agree :)

**Comment by alivekenny** [comment]
@stek29 what gives? You close this issue and mark it as a dublicate of #1791, but that one is closed on May 5. Bug is still on loose and some of this issues should be reopened.

**Comment by stek29** [comment]
@alivekenny Stick to #585 and google/fonts#1140
