### ISSUE TITLE
Keep typed text editable when attaching file

### ISSUE THREAD

**Issue by alivekenny** [telegramdesktop/tdesktop#3355]
### Steps to reproduce
1. Type something in chat input but don't send in
2. Attach document or paste it from clipboard
3. Attachment has it's own text area (caption) and it's empty. Now you can't reach typed text without closing attachment popup

### Expected behaviour
Typed text from chat's input moving to attachment input

### Actual behaviour
Typed text left below attachment popup and cannot be reached without closing it.

### Note
This is very frustrating behaviour because many people type something before attaching some file. Slack's developer thought about this and made their attachment behaviour more friendly.

This is how Telegram works:
![telegram-attachments](https://cloud.githubusercontent.com/assets/21039303/25736437/470ee420-318b-11e7-8991-e701fc06f383.gif)

This is how Slack works:
![slack-attachments](https://cloud.githubusercontent.com/assets/21039303/25736436/46d59f80-318b-11e7-9948-33b12911beb8.gif)

### Configuration
**Operating system:** macOS 10.12.3

**Version of Telegram Desktop:** 1.0.29

**Comment by MasterGroosha** [comment]
Duplicate #2725
