### ISSUE TITLE
Cant compile actual version of telegram

### ISSUE THREAD

**Issue by JimmyS83** [telegramdesktop/tdesktop#3356]
Hi,
I made all needed steps to create build environment, but I cant build Telegram VS project :( Could anyone help me with:

```
116/762] RULE Moc-ing cross_animation.h..
1>  [117/762] RULE Moc-ing radial_animation.h..
1>  [118/762] RULE Moc-ing panel_animation.h..
1>  [119/762] ACTION Updating dependent qrc files..
1>  FAILED: gen/update_dependent_qrc.timestamp
1>  d:\TBuild\Libraries\Python27\python.exe gyp-win-tool action-wrapper environment.x86 Telegram_target_update_dependent_qrc_c642e503ab10600cf0ab03d24edc5060..rsp ..\..\Telegram\gyp\
1>  File not found: out\Debug\gen\update_dependent_qrc.timestamp
1>
1>  [120/762] ACTION codegen_lang-ing lang.strings..
1>  FAILED: gen/lang_auto.cpp gen/lang_auto.h
1>  d:\TBuild\Libraries\Python27\python.exe gyp-win-tool action-wrapper environment.x86 Telegram_target_codegen_lang_c642e503ab10600cf0ab03d24edc5060..rsp ..\..\Telegram\gyp\
1>Command Line : error 904: only one input path expected
1>
1>  [121/762] ACTION codegen_scheme-ing scheme.tl..
1>  FAILED: gen/scheme.cpp gen/scheme.h
1>  d:\TBuild\Libraries\Python27\python.exe gyp-win-tool action-wrapper environment.x86 Telegram_target_codegen_scheme_c642e503ab10600cf0ab03d24edc5060..rsp ..\..\Telegram\gyp\
1>  Output path required.
1>
1>  [122/762] ACTION codegen_numbers-ing numbers.txt..
1>  FAILED: gen/numbers.cpp gen/numbers.h
1>  d:\TBuild\Libraries\Python27\python.exe gyp-win-tool action-wrapper environment.x86 Telegram_target_codegen_numbers_c642e503ab10600cf0ab03d24edc5060..rsp ..\..\Telegram\gyp\
1>Command Line : error 904: only one input path expected

...

1>  ninja: build stopped: cannot make progress due to previous errors.
1>D:\TBuild\tdesktop\Telegram.vcxproj(978,5): error MSB3073: The command "call ninja.exe -C out\Debug\ -k0 Telegram" exited with code 1.
```

I will appretiate any hints. Thank you!

**Comment by john-preston** [comment]
@JimmyS83 That's interesting, it started failing on Appveyor that way some time ago. I don't think it is related somehow to the code, perhaps something was changed in GYP or Ninja..

**Comment by JimmyS83** [comment]
Could we use some workaround to make compile happen, without those maybe? I see "The Travis CI build passed" around on Github, it gives me a sparkle of hope.. :)

**Comment by john-preston** [comment]
@JimmyS83 This was a problem with the new GYP version. I've fixed that in the latest commit to the dev branch.

**Comment by JimmyS83** [comment]
Is it now dev compilable? The fix helped with previous problem, but I still struggling with complete compile:
```

[377/762] RULE codegen_style-ing settings.style..
1>  [378/762] RULE codegen_style-ing chat_helpers.style..
1>  [379/762] RULE codegen_style-ing window.style..
1>  [380/762] STAMP obj\Telegram.actions_rules_copies.stamp
1>  [381/762] RC ..\..\Telegram\Resources\winrc\Telegram.rc
1>  [382/762] CXX sourcefiles\telegram.stdafx.obj
1>  FAILED: sourcefiles/telegram.stdafx.obj
1>  ninja -t msvc -e environment.x86 -- "D:\Program Files\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @sourcefiles\telegram.stdafx.obj.rsp /c ..\..\Telegram\SourceFiles\stdafx.cpp /Fosourcefiles\telegram.stdafx.obj /FdTelegram.pdb
1>d:\tbuild\tdesktop\telegram\sourcefiles\base\lambda.h(61): error C2737: 'base::lambda_is_mutable': 'constexpr' object must be initialized
1>d:\tbuild\tdesktop\telegram\sourcefiles\base\lambda.h(61): error C2998: 'const bool base::lambda_is_mutable': cannot be a template definition
1>d:\tbuild\tdesktop\telegram\sourcefiles\base\lambda.h(72): error C2737: 'base::lambda_internal::is_large': 'constexpr' object must be initialized
1>d:\tbuild\tdesktop\telegram\sourcefiles\base\lambda.h(72): error C2998: 'const bool base::lambda_internal::is_large': cannot be a template definition
1>d:\tbuild\tdesktop\telegram\sourcefiles\base\lambda.h(204): error C2976: 'base::lambda_internal::vtable_once_impl': too few template arguments
1>  d:\tbuild\tdesktop\telegram\sourcefiles\base\lambda.h(116): note: see declaration of 'base::lambda_internal::vtable_once_impl'
1>  d:\tbuild\tdesktop\telegram\sourcefiles\base\lambda.h(206): note: see reference to class template instantiation 'base::lambda_internal::vtable_once<Lambda,Return,Args...>' being compiled
1>d:\tbuild\tdesktop\telegram\sourcefiles\base\lambda.h(204): error C2955: 'base::lambda_internal::vtable_once_impl': use of class template requires template argument list
1>  d:\tbuild\tdesktop\telegram\sourcefiles\base\lambda.h(116): note: see declaration of 'base::lambda_internal::vtable_once_impl'
1>d:\tbuild\tdesktop\telegram\sourcefiles\base\lambda.h(204): error C2143: syntax error: missing ',' before '>'
1>d:\tbuild\tdesktop\telegram\sourcefiles\base\lambda.h(255): error C2976: 'base::lambda_internal::vtable_impl': too few template arguments
1>  d:\tbuild\tdesktop\telegram\sourcefiles\base\lambda.h(211): note: see declaration of 'base::lambda_internal::vtable_impl'
1>  d:\tbuild\tdesktop\telegram\sourcefiles\base\lambd

```
And so on..  Is it my bad?

**Comment by john-preston** [comment]
@JimmyS83 I don't know, works fine for me. Which Visual Studio version exactly do you try? Mine is "Microsoft Visual Studio Professional 2015 Version 14.0.25431.01 Update 3" with "cl /HELP" giving the compiler version "Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86"

**Comment by JimmyS83** [comment]
I am using Free (Community Edition) 2015, 32bit edition, installed from offline image (vs2015.com_enu.iso):
_Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23026 for x86_
I believe it shouldnt differs from the Professional version from C++ compiler view.. :(

I even try to use already compiled libraries through appveyor's https://github.com/telegramdesktop/dependencies_windows.git, with quite the same results, so I believe my Libraries builds should be fine also..

I just want to add [Czech language](https://github.com/telegramdesktop/tdesktop/pull/3352), so my old folks can use Desktop Telegram :) I spent half a day with preparing build environment, I believe I can see Finnish flag, but still struggling with some nitpicks :(

**Comment by john-preston** [comment]
@JimmyS83 Libraries are fine, it is tdesktop code which is not building right for you and it is like the compiler is not supporting some of the features. Are you sure it is the latest available msvc compiler?

**Comment by JimmyS83** [comment]
Only thing I can think of is installing Update 3. I will try, if that doesnt help. Regarding language strings, I read later, that language PR are not accepted anymore. Do you think you could import Czech strings into transifex, and approve me as translator?

**Comment by JimmyS83** [comment]
Sucess! Thank you very much for your advices.
I think you can mention in msvc readme that VS 2015 Update 3 is requirement. I was able to sucessfully compile the code using **14.0.25431.01 Update 3** version. [Preview](http://imgur.com/a/8A4cY)

Please, consider my request @transifex. Now I would like to translate also Android official and Web version, unfortunatelly I cant request Czech languages here also (maybe there is some other Czech request pending from other user?)
