### ISSUE TITLE
Delete messages with Cmd+Backspace

### ISSUE THREAD

**Issue by alivekenny** [telegramdesktop/tdesktop#3359]
### Steps to reproduce
1. Select message
2. Try to delete it on Macbook keyboard using Cmd+Backspace

### Expected behaviour
Message deleted

### Actual behaviour
~~Nothing happened, because only Del key deletes messages, but there is not such thing as Del key on Macbook, it replaced with fn+Backspace shortcut, but this shortcut isn't used for deletion on macOS. It uses Cmd+Backspace or just Backspase for deleting.~~

Cmd+Backspace shortcut doesn't work until you press fn+Backspace (or press «Delete» button on top of the window) and then hit «Cancel».

### Configuration
**Operating system:** macOS 10.12.3

**Version of Telegram Desktop:** 1.0.29, 1.1.19

**Comment by stek29** [comment]
Works on 1.1.19

**Comment by alivekenny** [comment]
@stek29 there is a bug. Cmd+Backspace shortcut doesen't work until you press fn+Backspace (or press «Delete» button on top of the window) and then hit «Cancel».

**Comment by stek29** [comment]
I'm still unable to reproduce it.
I think we'll need third person with macOS.

**Comment by stek29** [comment]
@alivekenny Do you have to use fn+Backspace for every selection to get CMD+Backspace to work?

**Comment by alivekenny** [comment]
> Do you have to use fn+Backspace for every selection to get CMD+Backspace to work?
 
Yes.

**Comment by Aokromes** [comment]
this is valid on 1.9.8?

**Comment by alivekenny** [comment]
Yes
