### ISSUE TITLE
[Request] Large emoji

### ISSUE THREAD

**Issue by alivekenny** [telegramdesktop/tdesktop#3361]
Hi!

It would be great if emojis with no text will be sent in large size, like in Slack or Apple Messenger.

Why use stickers when you have over thousand of emojis witch can express emotion pretty accureate, but problem is that they are just too small.

By the way, i believe that iOS version should do it too.

**Comment by auchri** [comment]
Duplicate.

Also try this sticker pack: https://telegram.me/addstickers/sticker_emoji_by_naeim

**Comment by john-preston** [comment]
@alivekenny The images bundled in tdesktop are too small for that anyway :(

**Comment by alivekenny** [comment]
Well, Slack managed this problem somehow, I guess TD can do it too. And sticker pack, well, this is a way, but there are small amount of them. Also smiles and frowns are recognizible in small size anyway. Problem starts when you send something like 🤷‍♂️ or 👨‍🎨

**Comment by alivekenny** [comment]
@john-preston From now on large emojis are the thing in Telegram on iOS and Android. I'd like to see it on the desktop as well :-)

<img src="https://user-images.githubusercontent.com/21039303/55225278-1bd17680-5234-11e9-8826-3c960d56cceb.PNG" width="350">

**Comment by RememberTheAir** [comment]
Original issue: #1414
