### ISSUE TITLE
Additional shortcut key options for sending messages 

### ISSUE THREAD

**Issue by Canis-Enigmas** [telegramdesktop/tdesktop#3366]
### Enhancement Suggestion
Shortcut keys for sending messages currently support either 'Enter' or 'Ctrl+Enter' for PCs and 'Command + Enter' for Macs. 
Due to the differences between keyboard layouts of PCs and Macs, would it be possible to add 'Alt+Enter' as an additional shortcut key for PCs.
This is a big convenience for those of us who switch between both devices often as the location of 'Alt+Enter' on PC keyboards is the same with 'Command+Enter' on Mac keyboards. 
Thank you.

**Comment by Aokromes** [comment]
maybe it can be changed to a multiple selection like some programs allows.
IE
Enter.
Alt+Enter
Control+Enter
Control+Alt+Enter.

**Comment by stek29** [comment]
Or maybe it could be changed to any with custom shortcut system

**Comment by Canis-Enigmas** [comment]
Personally, I actually prefer 'Shift+Enter' from the old Trillian days, but I guess that might be asking a bit too much? Updated the title to better reflect suggestions here.

**Comment by MasterGroosha** [comment]
There is `shortcuts-custom.json` file in `tdata/tdata` folder inside TDesktop's current folder, so in theory your issue might be solved in future if `send_message` action will be added to custom shortcuts list.

**Comment by tiktuk** [comment]
Yes, alt+enter is standard on Mac I think, would be great not having to use a different shortcut in Telegram only.

**Comment by Aokromes** [comment]
Yeah stek29, something like a lot of games where you can select any shortcut https://i.imgur.com/gqsl81f.png

**Comment by Aokromes** [comment]
how about to rename this to "Custom shortcuts system" and put here
https://github.com/telegramdesktop/tdesktop/issues/4258
https://github.com/telegramdesktop/tdesktop/issues/2012

**Comment by Aokromes** [comment]
maybe 

https://doc.qt.io/archives/qq/qq14-actioneditor.html
https://github.com/bjorn/tiled/commit/c1a48ad13b812d6531b372ec8295b19a769257d9

can help someone to create one pull request implementing custom user shortcuts allowing everyone to setup every shortcut they want.

**Comment by Aokromes** [comment]
still wanted

**Comment by ohhai** [comment]
Configurable shift+enter for sending a message would be nice
Also: #2671

**Comment by 23rd** [comment]
465a42a825bfc2be51bb7c77be5d031229e15b10
Why this issue is still open?
