### ISSUE TITLE
(suggestion) show "MYSELF" as a contact would be a killer feature

### ISSUE THREAD

**Issue by eduardoarandah** [telegramdesktop/tdesktop#337]
Telegram is rocketing on professionals and teams, because is exahusting comunicating all day via whatsapp. 

One Killer feature would be to _show yourself as a contact_ so you can easily send documents/pictures between destkop and mobile. 

Would do the same as "pushbullet" from google. 

Many of my friends take telegram only because they can send documents to themselves
![example1](https://cloud.githubusercontent.com/assets/4065733/5460141/f9d3408e-8525-11e4-9b04-ce3b119b5248.jpg)
![example2](https://cloud.githubusercontent.com/assets/4065733/5460142/f9d492a4-8525-11e4-9a6b-f7109d954b88.jpg)

**Comment by kolen** [comment]
Also, you can create private channel (not group) with only you as a member.

**Comment by eduardoarandah** [comment]
Well of course, but apart from telegram desktop for professional life and
sending documents to myself, there's less reasons to use telegram now that
whatsapp is encrypted


El sábado, 9 de abril de 2016, Konstantin Mochalov <notifications@github.com>
escribió:

> Also, you can create private channel (not group) with only you as a member.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/337#issuecomment-207872429>
>


-- 
Enviado desde mi móvil

**Comment by stek29** [comment]
@eduardoarandah 
> low-tech people that make the 95% of users
wow, 95%? Any Proofs?
