### ISSUE TITLE
After WSUS 5/9/2017, Telegram app dies after startup

### ISSUE THREAD

**Issue by berrydan** [telegramdesktop/tdesktop#3373]
### Steps to reproduce
1. Install KB4016240 dated 5/09/2017
2. Relaunch Telegram app
3. 

### Expected behaviour
Telegram app starts in the tray as usual and is functional

### Actual behaviour
The Telegram app starts in the tray but immediately exits, leaving the icon until you hover the cursor over it. Telegram app was working fine before applying Windows Updates.

### Configuration
**Operating system:**
Windows 10 Creators Update 1703 (15063.250)

**Version of Telegram Desktop:**
1.0.29

**Used theme**:
Default

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@berrydan Please try the latest alpha version from https://desktop.telegram.org/changelog#alpha-version does it crash the same way?

**Comment by berrydan** [comment]
One step ahead, was just about to comment... tried 1.0.35a, and it looks like the issue doesn't occur with it.
