### ISSUE TITLE
Calls don't work.

### ISSUE THREAD

**Issue by JrooTJunior** [telegramdesktop/tdesktop#3374]
### Steps to reproduce
a. Try call 
b. Try accept calls

### Actual behaviour
The application crashes at the "connecting" stage

### Configuration
**Operating system:** 

> Arch Linux x86_64
> Linux 4.10.11-1-ARCH
> KDE 5.33.0 / Plasma 5.9.4

**Version of Telegram Desktop:** 1.0.36 alpha

**Used theme**: NightMode.v8

<details><summary>**Logs**:</summary>
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
D/tgvoip: === Updating voip config ===
V/tgvoip: audio_bitrate_step_decr -> 1000.000000
V/tgvoip: audio_bitrate_step_incr -> 1000.000000
V/tgvoip: audio_congestion_window -> 1024.000000
V/tgvoip: audio_frame_size -> 60.000000
V/tgvoip: audio_init_bitrate -> 16000.000000
V/tgvoip: audio_init_bitrate_edge -> 8000.000000
V/tgvoip: audio_init_bitrate_gprs -> 8000.000000
V/tgvoip: audio_init_bitrate_saving -> 8000.000000
V/tgvoip: audio_max_bitrate -> 20000.000000
V/tgvoip: audio_max_bitrate_edge -> 16000.000000
V/tgvoip: audio_max_bitrate_gprs -> 8000.000000
V/tgvoip: audio_max_bitrate_saving -> 8000.000000
V/tgvoip: jitter_losses_to_reset -> 20.000000
V/tgvoip: jitter_max_delay_20 -> 25.000000
V/tgvoip: jitter_max_delay_40 -> 15.000000
V/tgvoip: jitter_max_delay_60 -> 10.000000
V/tgvoip: jitter_max_slots_20 -> 50.000000
V/tgvoip: jitter_max_slots_40 -> 30.000000
V/tgvoip: jitter_max_slots_60 -> 20.000000
V/tgvoip: jitter_min_delay_20 -> 6.000000
V/tgvoip: jitter_min_delay_40 -> 4.000000
V/tgvoip: jitter_min_delay_60 -> 1.000000
V/tgvoip: jitter_resync_threshold -> 0.500000
V/tgvoip: use_system_aec -> true
V/tgvoip: use_system_ns -> true
V/tgvoip: new endpoint 40006: x.x.x.x:525
V/tgvoip: new endpoint 40008: x.x.x.x:528
V/tgvoip: new endpoint 10003: x.x.x.x:534
V/tgvoip: new endpoint 10002: x.x.x.x:535
V/tgvoip: new endpoint 50004: x.x.x.x:523
V/tgvoip: new endpoint 50003: x.x.x.x:532
W/tgvoip: Set remote endpoints
I/tgvoip: update data saving mode, config 0, enabled 0, reqd by peer 0
W/tgvoip: Starting voip controller
V/tgvoip: trying bind to port 26494
D/tgvoip: Bound to local UDP port 26494
I/tgvoip: Receive thread starting
V/tgvoip: Call state changed to 2
I/tgvoip: Detected IPv4 connectivity, will not try IPv6
D/tgvoip: Received init ack
I/tgvoip: peer version from init ack 3
I/tgvoip: before create audio io
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
E/tgvoip: snd_pcm_open failed: Устройство или ресурс занято
Telegram: pcm.c:712: snd_pcm_stream: Проверочное утверждение «pcm» не выполнено.
Аварийный останов (стек памяти сброшен на диск)
</details>

**Comment by morealaz** [comment]
same for me with Arch Linux and Gnome 3.24

**Comment by john-preston** [comment]
@JrooTJunior @morealaz Some crashes will be fixed in the upcoming version today.

Also, do you have SSE2 support? I see some crash reports with SIGILL on SSE2 instructions.

**Comment by JrooTJunior** [comment]
@john-preston, yep. I have SSE2 support.

**Comment by JrooTJunior** [comment]
@john-preston, still doesn't work.

**Comment by morealaz** [comment]
@john-preston: update seems work for me and I have no crash since update, although I can't still use call, because I live in Iran!!!

**Comment by auchri** [comment]
@morealaz That's not an issue of telegram Desktop.

**Comment by morealaz** [comment]
@auchri: I know. 😄

**Comment by JimmyS83** [comment]
maybe stupid comment, but just for sure, watch out firewalls..

**Comment by JrooTJunior** [comment]
@JimmyS83, nope. The problem is not related to the firewall.
Calls started working after the next update.

**Comment by JrooTJunior** [comment]
I think the issue can be closed.

**Comment by EssaAlshammri** [comment]
I still have this issue on ubuntu 16.04
