### ISSUE TITLE
Application disappears when switching displays

### ISSUE THREAD

**Issue by lixoo81** [telegramdesktop/tdesktop#338]
If I switch between laptop display and external monitor when tdesktop is running, the user interface disappears. The only way to recover is to kill the running process and restart the application.

OS: Ubuntu 14.04
App version: 0.6.21

**Comment by ostasevich** [comment]
I can confirm this with Debian 8 GNOME 3.14. After unplugging external monitor application disappears, but process is running and I am getting notifications. With app version 0.7.13 problem is still there.

**Comment by ffflorian** [comment]
The same on Windows 8.1 with Telegram Desktop version 0.8 – with the only difference that the whole process is killed when switching between displays. Would be interesting to see a debug log from that.

**Comment by un-def** [comment]
Confirmed with Xubuntu 15.04 x64 (Telegram Desktop version 0.8.13). Also segfault occurs when laptop lid is closed (with "switch off display" option).

**Comment by auchri** [comment]
#796
