### ISSUE TITLE
Calls don't work in different way

### ISSUE THREAD

**Issue by Hasbreak** [telegramdesktop/tdesktop#3381]
### Steps to reproduce
1. Call to someone.
2. Wait until the person you're calling to answers a call.
3. That's actually all.

### Expected behaviour
The person I call to should be heard through speakers, and the person who answers a call should hear me as well.
Basically, a standard crystal-clear call.

### Actual behaviour
I hear nothing, and they don't hear me when connected to each other.
In the audio volume settings on following tabs, _Applications_ and _Recording Audio_, there's no Telegram listed.
_Nevertheless, audio works on Telegram if new message arrives, or there's
 audio or video playback through the built-in player._

### Configuration
**Operating system: Arch Linux/Kernel _4.10.13-1-ARCH_/KDE Plasma 5.9.5*

**Version of Telegram Desktop: 1.0.37 alpha**

**Used theme**: Breeze.V3

[log_16_45.txt](https://github.com/telegramdesktop/tdesktop/files/990257/log_16_45.txt)
[last_call_log.txt](https://github.com/telegramdesktop/tdesktop/files/990269/last_call_log.txt)

**Comment by john-preston** [comment]
@Hasbreak Does voice message recording work for you?

**Comment by Hasbreak** [comment]
@john-preston It does without any issue. Received voice messages are heard through speakers, and ones that I sent are heard by others.

**Comment by grishka** [comment]
I believe this is going to be resolved if I'll start using PulseAudio directly if it's available on the system. My assumption that everything is going to work anyway since PulseAudio presents itself as a virtual ALSA device turned out to be wrong.

**Comment by Hasbreak** [comment]
It seems to be working just fine in **1.0.37 alpha**.
I think I may close the issue. :)
