### ISSUE TITLE
[BUG] Telegram constantly recreating deleted Start Menu shortcut when entering Settings menu

### ISSUE THREAD

**Issue by Redundanz** [telegramdesktop/tdesktop#3384]
### Steps to reproduce
1.  With the originally created shortcut by the installer in place -> Delete the shortcut.
2.  Open up Telegram if neccessary -> open up the 'Settings' menu
3.  Verify that the Shortcut has been reinstated in the Start Menu folder where it was deleted from

### Expected behaviour
After deleting the 'Telegram' shortcut in the user's Start Menu it should not be reinstated by the application against my wish.

### Actual behaviour
Shortcut gets reinstated directly after opening the Telegram-Settings menu on a fresh program startup after the initial deletion of the shortcut.
![image](https://cloud.githubusercontent.com/assets/7331379/25923342/4c07d3aa-35dd-11e7-8c8c-b627e646d614.png)

### Configuration
**Operating system:** Windows 10 Creators Update 1703

**Version of Telegram Desktop:** 1.0.29

**Used theme**: Standard

<details><summary>**Logs**:</summary>
N/A

</details>

**Comment by telekek** [comment]
It's still not fixed about 1.5 years, please, fix it.

**Comment by stek29** [comment]
See #4526
