### ISSUE TITLE
Hide emoji panel

### ISSUE THREAD

**Issue by Alukardd** [telegramdesktop/tdesktop#3385]
### Steps to reproduce
1.  Install tdesktop 1.0.37.alpha.
2. Open any chat/group/channel (even if you muted in it).
3. See EMOJI/STICKERS/GIFS panel at the right side of the client.

### Expected behaviour
Panel should be popped up by hover or click.

### Actual behaviour
Panel permanently shown in any chat.

### Configuration
TDesktop 1.0.37

**Comment by auchri** [comment]
Click on the "old" emoji button to restore the old behavior.

**Comment by Alukardd** [comment]
Oh, these quirks of the interface...
Thx.
