### ISSUE TITLE
Fwd: use locale setting

### ISSUE THREAD

**Issue by mymedia2** [telegramdesktop/tdesktop#3387]
Salvo Tomaselli writes on https://bugs.debian.org/861861
> The UI has a setting to pick the locale, but really it should just read whatever locale the session is using and apply that, if the translation is available, rather than having me manually do that.
---

### How to reproduce
Launch Telegram with non-English locale, but supported by Telegram Desktop. For example, via command: `LANG=it_IT.UTF-8 ~/path/to/Telegram`.

### Expected behaviour
Telegram should be started in Italian language.

### Actual behaviour
Telegram is started in English language.

### Configuration
**Operating system:** Debian 9.0 GNU/Linux 4.9.0
**Version of Telegram Desktop:** 1.0.29

**Comment by john-preston** [comment]
@mymedia2 The LANG env variable is a standard for translation in Linux?

**Comment by mymedia2** [comment]
I don't know exactly, but I also tested it on a clear system with Italian default locale.

Generally speaking, usually LC_MESSAGES environment variable is responsible for language of user interface. Besides there are LANG and LANGUAGE for this propose.

**Comment by mymedia2** [comment]
By the way, gettext, the most popular translation system in Unix, is guided by the following rules to determine a current language.
https://www.gnu.org/software/gettext/manual/html_node/gettext_2.html#Locale-Environment-Variables

**Comment by Aokromes** [comment]
#2941 ?

**Comment by mymedia2** [comment]
Well, It's really duplicate of #2941
