### ISSUE TITLE
GNU/Linux Typing Unicode Controls

### ISSUE THREAD

**Issue by lehitoskin** [telegramdesktop/tdesktop#3388]
I want to enter a Unicode character, say, ™, but it isn't working out so well.
### Steps to reproduce
1. I click in the message box
2. Type <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-u 2122
3. Nothing happens

### Expected behaviour
Unicode character ™ should appear.

### Actual behaviour
No text is entered in the message box

### Configuration
Gentoo GNU/Linux

**Version of Telegram Desktop:** 1.0.29

**Comment by stek29** [comment]
What IME are you using?

**Comment by lehitoskin** [comment]
Assuming I understand what "IME" is correctly, I'm using en_US.UTF-8

**Comment by diazbastian** [comment]
@lehitoskin This is an old and well-known problem. You should only have installed and correctly configured iBus on your system. This is a GTK+ feature, but it is possible to use it in any application with iBus.

![unicode](https://cloud.githubusercontent.com/assets/5126124/26009490/6f653f3e-371f-11e7-8b4e-a5a4edefe0fa.png)

**Comment by lehitoskin** [comment]
I didn't have ibus installed, but after installing both ibus and ibus-table, it doesn't seem to have done anything. I think I'll have to try and compile it myself.

**Comment by lehitoskin** [comment]
Ah! I lied. I needed to start the daemon and restart my session. Thanks!
