### ISSUE TITLE
Fine control of audio device and volume

### ISSUE THREAD

**Issue by sirati97** [telegramdesktop/tdesktop#3389]
1: Allowing the user to select their own audio devices for calls. In some special setups it might not be the best option to just use the standard communication device
2. Allowing to adjust the volume of incoming and outgoing audio. Sometimes when called from a mobile device the other person is very quite. If you want to understand them, it is required to increase their volume further than system settings allow
3. Allow the user to enable an voice activation feature or push to talk. This way unimportant or annoying background noise  can be dropped.

**Comment by haevalencia** [comment]
Telegram Desktop should continue to be simple, in addition the options that you mention in points 1 and 2 must be handled by the operating system (TDesktop already allows handle incoming audio).
Push to Talk is a totally different feature and Telegram's approach is to improve voice messages. There are already some reports for TDesktop to have the same functionality as the Android and iOS versions.

**Comment by TheAppService** [comment]
I agree with @haevalencia but point 1 should be considered in my opinion.. If an application handles audio input/output devices it should be possible to configure what device should be used and not just only use the system default one..

**Comment by auchri** [comment]
@TheAppService There is already an issue for this.

**Comment by TheAppService** [comment]
@auchri Okay, thanks for the information ;). Then I'll tune out at this point ^^. Maybe a link to this issue would complete the discussion of point 1 mentioned by @TheSirati97.

**Comment by auchri** [comment]
@TheAppService #783

**Comment by TheSirati97** [comment]
@haevalencia Well i know setups especially used for recording potcasts where option 1 is needed.
 
Windows does not allow to amplify the outgoing sound of an program. So no is not handled by the operating system. I had calls where i could barely understand my partner, because telegram outputted their sound so quitely. I was using windows and telegram on full volume as well as an external amplifier which was set to the maximum volume that doesn't give makes you insane by load amplified background noise.

**Comment by stek29** [comment]
Neither does macOS.

**Comment by TheSirati97** [comment]
With the latest beta of Telegram for MacOS they partially added this feature.

**Comment by stek29** [comment]
@sirati97 you're probably talking about native macOS app...

**Comment by stek29** [comment]
@sirati97 You're probably talking about native macOS app written in Swift, not about TDesktop.

Also, I'd love to see these options not just for calls, but for anything, as suggested in #3496.

**Comment by sirati97** [comment]
I meant the native macOS app. Obviously as TDesktop is the same on all platforms. I would love to see that too

**Comment by stek29** [comment]
@sirati97 Nope, there are two different apps for macOS: desktop.telegram.org is TDesktop, and macos.telegram.org is "native macOS app written in Swift"

**Comment by stek29** [comment]
No, I'm not just skimming your replies.
I just haven't understood what you've meant.
> So I was giving an argument for that it is needed: 'The developer of the macOS app also thinks this is a valuable feature - Otherwise he would not have implemented it partially'.

This made everything clear.

> TDesktop is the same on all platforms feature-wise

This is not true, but let's not dig into this. 

Sorry for not understanding you at first, and thanks for explaining your messages.

**Comment by cryptochrome** [comment]
How is this still not implemented, one year later?

**Comment by sirati97** [comment]
Please close this issue as it was implemented
