### ISSUE TITLE
[Suggestion] Add one sticker from a pack

### ISSUE THREAD

**Issue by AleksSenkou** [telegramdesktop/tdesktop#3392]
Reason: I have tens of packs and it's fiddly to thumb through all packs in order to find proper sticker
Only 2-3 stickers per pack are used in general

Suggestion: It will be cool to have an opportunity to add one/several stickers from a pack

Thoughts?

**Comment by diazbastian** [comment]
@AleksSenkou That would be a new feature and I don't see it convenient. Anyway now you can download stickers individually with Telegram Desktop in WebP format (You have to open the context menu in the Sticker and select "Save as ..."), so you can send them directly as a file or create your own pack of stickers.

**Comment by stek29** [comment]
API issue.
