### ISSUE TITLE
[FEATURE REQUEST] KDE File dialog on KDE systems (probably add CMake switch to enable KDE integration)

### ISSUE THREAD

**Issue by msva** [telegramdesktop/tdesktop#3394]
Hi there!

As far, as I can see, when Ubuntuers asked that TDesktop use Gtk file dialog (instead of Qt one), you heard their prays and implemented it (although, that was strange idea by itself, but nevermind).

So, unfortunately, it is not only Ubuntu is Desktop Linux System, and it is not only GNOME is Desktop Environment that users are using ().
Even if not count Enlightenmentand so on, there is many and many users using KDE Plasma nowadays. Which is Qt5 based (!), and have very nice and useful (!!), beauty-looking, qt-based (!!!) File Dialog.

(by the way, in my humble opinion, Gtk one is very ugly and useless in comparsion with it)

Anyways:
Unlike for Gtk one, you doesn't even require many code for integration with software. You can just use `kdialog` utility (which is out of the box with any KDE Plasma installation) with proper arguments:

`--getopenfilename` (open file dialog. Have two optional arguments: `[startDir]` and `[filter]`). When user will select files (and press `open` button (or `enter` key on kb)) `kdialog` will return path(s) to selected file(s) on stdout for you. Alternativelly, `--getopenurl` can be used here. It has exactly same optional arguments, but it return URLs (file://) instead of FS paths, and also it supports protocols like sftp:// smb:// webdav:// and so on, while first one limits user to open only local files, and so returns local filesystem paths)

and

`--multiple` (allows to select multiple files at once).

And the same for saving dialog (`--getsavefilename`/`--getsaveurl`)

Also, `kdialog` can be used for many other "dialog" purposes (progressbar, calendar, slider, info/warn/error messages, color selection, checklist, radiolist, whatever.
So, it can be used for total integration with KDE Plasma and you can interact with it with only commandline arguments (and getting user input from it's stdout).

Yes, you also free to implement all of that "natively" by writing some code, including some headers and linking some libraries, but `kdialog` method gives you possibility to code less and avoid additional dependencies.

So, can you additionally implement file selection/saving dialogs using it for KDE users, please?

**Comment by xvitaly** [comment]
#3187

**Comment by msva** [comment]
ok, thanks (although, I swear, I tried to search for similar issues before reporting).
