### ISSUE TITLE
Telegram doesn't open, shows error message: PowerPC applications are no longer supported

### ISSUE THREAD

**Issue by pfannie** [telegramdesktop/tdesktop#3395]
### Steps to reproduce
1. Open Telegram
2. Be surprised about the error message

### Expected behaviour
Telegram should (as usual) open

### Actual behaviour
It doesn't open and shows the error message:
"You can't open the application "Telegram" because PowerPC applications are no longer supported."

![screen shot 2017-05-14 at 17 37 33](https://cloud.githubusercontent.com/assets/2554078/26035472/acde87ae-38cc-11e7-8e33-07be85d7ef0d.png)

### Configuration
**Operating system:** Mac OS X 10.11.6

**Version of Telegram Desktop:** 1.0.29

### Troubleshooting done
* Downloaded Telegram from the website again -> same problem
* Downloaded Telegram from the App Store -> working fine

**Comment by john-preston** [comment]
I don't know how this happens, I cannot reproduce that :(

**Comment by stek29** [comment]
Could you try starting it from different location?

**Comment by pfannie** [comment]
I can start the app from the disk image and from any other location, but once it was in the Applications folder, the icon changes and I cannot start it anymore.

**Comment by stek29** [comment]
@pfannie Try the following steps:
1. Move app to /Applications
2. Trash it, empty the trash (_Reboot?_)
3. Download app, move it to some other location but not /Applications
4. Start it once
5. Move it to /Applications

**Comment by pfannie** [comment]
Thanks, that fixed it.

**Comment by AliMD** [comment]
same issue !

**Comment by stek29** [comment]
@AliMD Have you tried what I've suggested?
