### ISSUE TITLE
Telegram capture stream

### ISSUE THREAD

**Issue by WyRe** [telegramdesktop/tdesktop#3396]
I would like be able to modify the capture stream of Telegram desktop in Linux when I'm recording; due I should keep the button pushed on I cannot change the pulseaudio source, my suggestion is that capture button would run without need to keep pushed on.

**Comment by auchri** [comment]
Duplicate

**Comment by WyRe** [comment]
@auchri what is the id?

**Comment by auchri** [comment]
e.g. #1060
