### ISSUE TITLE
Option to disable sticker panel

### ISSUE THREAD

**Issue by Yanrishatum** [telegramdesktop/tdesktop#3398]
### Steps to reproduce
1. Update Telegram
2. Have wide enough window
3. Suffer from a huge sticker panel.

**UPDATE**: Just noticed already reported and marked as "invalid". This is not obvious way to disable panel. Either should be signaled better or put into general settings as well.

### Expected behaviour
There should be option to disable that behavior of sticker panel, as not everyone uses them in the first place.
**Update**: This option should be:
1. Better signalled to user, as expecting him to magically know that clicking the small "smile" icon will revert behavior to default is bad idea.
2. Be in the general settings, as that's the first place where user would search for a way to disable panel.

### Actual behaviour
There is no way of disabling sticker panel other than making window smaller.
**Update**: There is way to disable it, but it is completely not obvious.

### Configuration
**Operating system:** Windows 7 Ultimate

**Version of Telegram Desktop:** 1.1

**Used theme**: Recolored to dark default.

**Comment by FrancoCJ** [comment]
Yes pleas, its annoying and tbh there are some gifs/stickers I dont like to show to the world in my screen nor I want 1/3rd of my screen being emojis

**Comment by Arugin** [comment]
Please don't do updates like this. This is totally awful.

**Comment by auchri** [comment]
Just click on the emoji button.

**Comment by mohsenkhanpour** [comment]
First of all if u click on the emoji button it will disappear, its not like its permanent and locked.
But I agree with Arugin updates like this should be tested in the alpha ring first.
I think the problem with the emoji panel is that it's too large, and take too much space of your telegram window, as a messaging app I want the focus on the messaging not the emojis.
I think it would be a very useful implementation if we could resize this panel like the contact panel.

**Comment by auchri** [comment]
@mohsenkhanpour The changes actually were tested in the alpha channel.

**Comment by Yanrishatum** [comment]
@auchri Yes, I've found that if you click on an emoji button it will be hidden. Problem is, that is not obvious way of hiding panel. If user have to search on how to disable such feature it's clearly done incorrectly. As I said, this is easily can be solved by just adding a checkbox in the settings menu or (preferably and) signalling that clicking emoji button will hide/show it. This is issue of usability and interface clarity.

**Comment by txwizard** [comment]
I finally found it, among the unlabeled icons along the bottom of the window. I suggest a simple solution; add balloon tips to all of those icons.

**Comment by stek29** [comment]
Balloon tip is shown 3 times

**Comment by txwizard** [comment]
My installation is at version 1.1.19, for Microsoft Windows, running on Windows 7 x64 Service Pack 1, and I see no balloons, whatsoever.

**Comment by zeroxxx2** [comment]
I just installed this and got pissed. Sure thing it can be easily dismissed by clicking the emoji button, but the fact that I HAD TO SEARCH IT AND STUMBLED ON THIS PAGE was really unnecessary. Designer team, use brain.

**Comment by roelvan** [comment]
Do you guys mean this button? It is not working for me (Mac latest version).
![11-01-2017-14 07 46](https://user-images.githubusercontent.com/2583837/32263817-10e249da-bf0e-11e7-94c5-c97abe6c2d69.jpg)

**Comment by roelvan** [comment]
Found it, that emoji button does not show up on group chats with readonly permissions. So that's why I was confused. This should be improved indeed!

**Comment by john-preston** [comment]
@roelvan This will be, in the next version. Thanks for your feedback.

**Comment by dsounded** [comment]
Please, guys, this make me insane for sure ! :)
