### ISSUE TITLE
Make option to hide emoji panel more discoverable

### ISSUE THREAD

**Issue by Maia-Everett** [telegramdesktop/tdesktop#3399]
Version 1.1 added a "feature" that shows a panel on the right that shows a list of emojis that can be inserted into a message.

While it can be disabled by clicking on the smiling face icon to the right of the text entry field, this behavior is not obvious. In fact, I had to refer to the closed GitHub issue #3398 to figure it out. A close button in the corner of the emoji panel, or even an option in application settings, would be much more discoverable.

![3399-mockup](https://cloud.githubusercontent.com/assets/10684/26046036/34df87a2-3977-11e7-90d7-d03491b3d98c.png)

**Comment by john-preston** [comment]
@lucidfox You can click on the emoji icon to the right of the message input field.

**Comment by lucidfox** [comment]
I know, but the behavior is so counterintuitive and non-discoverable that I had to browse closed issues on GitHub to find out about it. My suggestion is about providing a more obvious alternative, or at the very least making the connection between the icon and the panel more obvious in the UI.

**Comment by farwayer** [comment]
I'm pretty sure close button is necessary. Clicking on emoji icon is real unclear.

**Comment by AuditeMarlow** [comment]
I second lucidfox and farwayer's statements. I've had the emoji/sticker/gif pane open for over 4 hours before figuring out how to close it.

**Comment by sgregori** [comment]
You found it, I have to come here when I spent too many minutes to know how to hide it. I have already closed it, but please add an option.

I'd the panel open for many hours, until looked at issues.

Thank you very much,

**Comment by zclimber** [comment]
Another possible behavior would be to initially set emoji panel as closed. 
This way user would discover the pane when first clicking on emoji icon, and so would reasonably expect that another click on the same icon would hide it.

**Comment by TheLastProject** [comment]
I'm so glad I found this issue. As soon as I updated Telegram my first feeling was "god dammit, they found a way to limit the space I have to chat in **again**". I checked the whole panel for a X button, I checked settings, I couldn't find the way to close it anywhere either, luckily this was the first issue I found before creating my own issue to complain about the (for me, as someone who doesn't use stickers all the much) huge waste of space. It would've been a million times better to have had this panel hidden by default until someone pressed the emoji button, because then they would've been able to logically figure out that that button is a toggle now.

**Comment by MWFIAE** [comment]
Thanks for this issue as i never found it myself...
Part to the fact that I'm primarly using it with my bot which has a custom keyboard. So no smiley icon to click on. First you have to close the keyboard and then you can disable the smileys...

**Comment by LPenos** [comment]
I actually had to search for it and ended up here to find out how to disable to emoji panel.

**Comment by DeadMate** [comment]
Ended up here after hours of googling. Please, review this desicion, it is horrible.

**Comment by pt300** [comment]
I went straight here after not being able to figure out how to close the panel in 2 minutes. I see two options on how to improve that. First one would be for the panel to be hidden by default for user to find out how to open/close it more easily as @zclimber suggested. Other option is what @lucidfox said. Just add an "x" button to the panel.

**Comment by diazbastian** [comment]
The viber panel works exactly like this.

![viber-panel](https://cloud.githubusercontent.com/assets/5126124/26077891/a849c112-398b-11e7-9828-99b31e8079fb.png)

**Comment by chessmango** [comment]
An elegant solution to this could be just to highlight the emoji icon in the message bar.
It'd have the same highlight as the sections of the bar itself, so I reckon it'd work well.

Forgive the weird colouring:
![20170516-074147](https://cloud.githubusercontent.com/assets/8074719/26091791/acd664a6-3a0d-11e7-94a3-1df47222e6cb.png)

**Comment by jaapz** [comment]
@chessmango highlighting would be a good idea, but not *instead* of a close `x`. When people want to close something, they click an `x`. There is no real reason to do it any differenly here, IMO

**Comment by chessmango** [comment]
@jaapz Agreed. Both for best results. :stuck_out_tongue:

**Comment by kslr** [comment]
Support in the settings to add, I spent a long time unable to find the close button, was forced to switch to Mac version.

When I prepared to compile myself, I found the answer here.

:)

**Comment by AuditeMarlow** [comment]
In the new version, a text popup appears above the emoji button that states you can close the pane by clicking on the emoji button again. In my opinion good enough so requesting to close this issue.

**Comment by farwayer** [comment]
If you show help about bad UX it will not make it better. User can missed this 1s popup. He can forget about this behavior.
Adding all familiar X is very simple and right solution. It will prevent to show this unneeded non-expected toast.

**Comment by john-preston** [comment]
@farwayer The X button there doesn't fit with the design :(

You see the emoji icon displayed active when the column is shown and inactive when it is not, it also gives you an understanding that they're related.

**Comment by TheLastProject** [comment]
I found the popup kinda hilarious, because I clicked the popup itself because it said "Click here" and it didn't work. I feel the UI is even more unclear because of it now.

**Comment by john-preston** [comment]
@TheLastProject It has a tooltip with a special arrow in it ¯\_(ツ)_/¯

**Comment by lucidfox** [comment]
> If you show help about bad UX it will not make it better. User can missed this 1s popup. He can forget about this behavior.

I concur. The tooltip is a step in the right direction, but it's still easy to miss. The right answer to a counterintuitive UI decision is not to present a distracting tooltip that nonetheless goes away in a couple of seconds (so the user can miss it), but provide a standard solution.

> The X button there doesn't fit with the design :(

I fail to see how an X button in the top right corner of a panel doesn't fit the design of an application that already uses buttons (including X buttons) in top right corners of panels:

![screenshot_20170518_195045](https://cloud.githubusercontent.com/assets/10684/26202966/9825ce14-3c03-11e7-843c-ce1ed3bd7540.png)

**Comment by john-preston** [comment]
@lucidfox It doesn't fit specifically there because of the tabs with centered text in them, not because it is a button or because it is an X.

**Comment by lucidfox** [comment]
So reserve a little space on the right for the X button and make each tab use 1/3 of the available space, with centered text.

In fact, that's what I did on the picture in the original post - I edited it, shrinking each tab a little to make room for the button.

**Comment by jaapz** [comment]
To support the argument that at least the current set-up is bad UX with some anecdotal evidence. Me, plus three coworkers were all searching for a way to close the panel after the update, only discovering how it actually worked by finding this issue on github.

**Comment by purplesrl** [comment]
+1

I could not figure this out either, and i use telegram only in full screen so it was very annoying I could not close it.

Maybe make the smiley face bold/not-bold to suggest some state change.

**Comment by restyler** [comment]
Shoot I would never think that I can disable sticker panel by clicking on emoji icon without reading this issue. There should definitely be a more obvious way to close the panel.

**Comment by BoffinbraiN** [comment]
Oh wow... I was looking for this button everywhere. I was about to make a new ticket. Thanks for showing me where it was!

**Comment by Aokromes** [comment]
Maybe reuse the new channel / group / person info sidebar and merge it with emojis / gifs / pics?
https://i.imgur.com/5jjCHak.jpg

**Comment by BoffinbraiN** [comment]
To be honest, I'd still prefer if the button didn't do anything on hover (to avoid accidentally opening it when moving the mouse over the corner of the window) and just opened the emoji popup on click. Once that popup is open, you can have a 'pin to sidebar' button with a pin icon in the corner. Please excuse the shoddy pin icon I drew in Paint! Also, I probably used the wrong theme color and it should be in gray, not green.

![untitled](https://user-images.githubusercontent.com/13255058/33915686-961b520a-df9c-11e7-8f54-261b9c587bc1.png)

**Comment by Aokromes** [comment]
#3267 ?

**Comment by securitywyrm** [comment]
I had to come to this thread to find out how to close that window. Thank you!

**Comment by ks7000** [comment]
> I had to come to this thread to find out how to close that window. Thank you!

**Me too!**

But my younger son (23 year old) found solution about 35 seconds. I think (maybe) put a legend on happy face "HIDE ME" but for every language is a bigger problem...

I want contribute to close this issue, please see this tweet for further details about this kind of problem:

https:/twitter.com/Karrenbacs/status/1190628095058960384

**Comment by froh42** [comment]
It is 2020 and I ended up here googing on how to close this ANNOYING panel. Yea, I used it before, but I just forgot how to close it today. This is annoying. Probably I got he popup explaining me how to do things three years ago. Once.
I'm old and have ADHD. I don't bother to remeber such things.

**Comment by hkBattousai** [comment]
I came here to find out how to close the emoji panel.

**Comment by foobargeez** [comment]
Couldn't figure out how to close the emoji panel -- ended up here (thanks to the search engine).

**Comment by purplesrl** [comment]
this is very funny (stale bot) from the Telegram Desktop developers, but well its expected, we close the issue because the user lost interest, how is that? when you comment too much they say 'please stop commenting on this issue' (see Telegram Desktop encryption issue), now they added a bot to disable the idle issues, meaning that if nobody replies for some time the issue does not need to be fixed anymore, which is great! wish I could do the same at my workplace!

**Comment by sflip** [comment]
> this is very funny (stale bot) from the Telegram Desktop developers, but well its expected, we close the issue because the user lost interest, how is that? when you comment too much they say 'please stop commenting on this issue' (see Telegram Desktop encryption issue), now they added a bot to disable the idle issues, meaning that if nobody replies for some time the issue does not need to be fixed anymore, which is great! wish I could do the same at my workplace!

**Comment by john-preston** [comment]
@sflip I'm still thinking how to write / behave about the feature request issues here.

(Un)fortunately it's not anybody's job to implement feature requests from github issues. So they may be here to be discussed and to be implemented in some forks of tdesktop.

If it is some feature without any UI implications at all (like new options in Settings), just a pure improvement, like HTTPS proxy support or smth, then it could be done like a PR here and it'll be merged.

Maybe the stale bot is not a great idea. But leaving them just opened for years doesn't look great as well. It looks like all they need automatic reply explaining the above and a special tag, maybe the existing "enhancement" will do.

**Comment by NightMachinary** [comment]
[**@John Preston**](https://github.com/john-preston) commented on [Apr 23, 2021, 12:45 PM GMT+4:30](https://github.com/telegramdesktop/tdesktop/issues/3399#issuecomment-825484267 "2021-04-23T08:15:37Z - Replied by Github Reply Comments"):
> [@sflip](https://github.com/sflip) I'm still thinking how to write / behave about the feature request issues here.
> 
> (Un)fortunately it's not anybody's job to implement feature requests from github issues. So they may be here to be discussed and to be implemented in some forks of tdesktop.
> 
> If it is some feature without any UI implications at all (like new options in Settings), just a pure improvement, like HTTPS proxy support or smth, then it could be done like a PR here and it'll be merged.
> 
> Maybe the stale bot is not a great idea. But leaving them just opened for years doesn't look great as well. It looks like all they need automatic reply explaining the above and a special tag, maybe the existing "enhancement" will do.

It would be a good idea to at least add the heavily upvoted issues to your internal issue tracker. Some new features, such as animated emojis, don't add any real value to the app, while the upvoted features on Github usually have some concrete value proposition for a significant niche of users.
