### ISSUE TITLE
Copying table data from MS Exel

### ISSUE THREAD

**Issue by x548xx** [telegramdesktop/tdesktop#34]
If I copied the table data and then paste their in telegram recognize them as image, although this text.

**Comment by Katzen-Gott** [comment]
Same when copying from LibreOffice calc. Text is copied as text only if I take contents of cell, if I try to copy the whole cell (or several cells) it is recognized as image. Not sure if it's a bug.

**Comment by auchri** [comment]
I like that its copied as image, especially for cells which contain formatting etc.
