### ISSUE TITLE
[Feature improvement] Allow more than 5 pinned stuff

### ISSUE THREAD

**Issue by oxydron** [telegramdesktop/tdesktop#3406]
### Steps to reproduce
1. Pin 5 things.
2. Try to pin a 6th
3. Nope.

### Expected behaviour
How many pinned stuff I want, not only 5.

### Actual behaviour
Only 5 pinned stuff.

### Configuration
**Operating system:**
Linux master racer.

**Version of Telegram Desktop:**
Last alpha 15/05/2017

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
https://github.com/telegramdesktop/tdesktop/issues/3026

**Comment by oxydron** [comment]
@auchri I did searched. On the next time I'll look into the first 20 issues, because didn't got this #3026 on my search. I'll read the suggested link too.
Sorry for the duplicates, I too don't like to make them.
