### ISSUE TITLE
Layering the answer after pressing on selfswitch-button

### ISSUE THREAD

**Issue by toby3d** [telegramdesktop/tdesktop#3407]
### Steps to reproduce
1. Send something with inline self-switch button via inline-bot in any chat
2. Press the button

### Expected behaviour
Normal offset of the message above the reply line.

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/5412322/26081467/4b172760-39e4-11e7-95a3-e5a57f8b0811.png)
The message is layered on top of the reply panel, closing the button and its other contents. This can be fixed by resizing the window or clicking on the panel. Scrolling does not solve the problem.

### Configuration
**Operating system:** Linux Mint Mate 18.1 x64_86

**Version of Telegram Desktop:** 1.1 alpha
https://desktop.telegram.org/changelog

**Used theme**: Default theme

**Comment by john-preston** [comment]
@toby3d I can't understand, how to reproduce the issue. Can you provide an example with a bot and a request? So I could reproduce that just following your steps. Thank you for the report.

**Comment by toby3d** [comment]
@john-preston I checked in the latest alpha version of the desktop client on Linux. This bug is observed only in groups, supergroups and channels. In the tet-a-tet chats with users and chats with the bots is all right.

**Comment by toby3d** [comment]
## Step 1
Select random bot who can send results with `self_switch` inline-button:
![image](https://user-images.githubusercontent.com/5412322/27841620-86c12fd6-611c-11e7-8f10-0e6ea52cb848.png)

## Step 2
Send random result.
![image](https://user-images.githubusercontent.com/5412322/27841687-f2f3ff6c-611c-11e7-914c-7559436e72af.png)

## Step 3
Click on inline-button ("Ещё" on this screenshots) and you see this bug. Maybe you can remove all texts in input without fixing this bug.
![image](https://user-images.githubusercontent.com/5412322/27841723-28213808-611d-11e7-9cb8-fdc04f802dbd.png)

**Comment by john-preston** [comment]
Thanks.
