### ISSUE TITLE
How to reduce Telegram execution file size on Ubuntu?

### ISSUE THREAD

**Issue by nthtson** [telegramdesktop/tdesktop#3409]
I followed [build instructions for GYP/CMake under Ubuntu 12.04](https://github.com/telegramdesktop/tdesktop/blob/master/docs/building-cmake.md). Everything is fine but Telegram file in folder "out/Release" is too large (> 400mb). 

What should I do to reduce the file size? Because I'm newbie, sorry for the foolish question.

**Comment by john-preston** [comment]
@nthtson You run "strip Telegram" in the Terminal.

**Comment by nthtson** [comment]
@john-preston Thank you very much.
