### ISSUE TITLE
Add an Icon on the tray informing connection problems.

### ISSUE THREAD

**Issue by cobalto** [telegramdesktop/tdesktop#341]
When I'm at work I mute my phone and rely only on tdesktop to chat on telegram.
My network requires web login time after time and tdesktop get stuck offline when this happens.
And with this, sometimes I pass all day disconnected just because it not informed me that I was offline.

**Comment by IlyaIndigo** [comment]
And that in 5.5 years there has been no progress on this issue?
But animated mail stickers in full screen, of course, was easier to do and they are much more important!

**Comment by ilya-fedin** [comment]
After 8 years, I believe it's the time to close this issue. All modern OSes have captive portal detection capability, so it's enough to look at the system network indicator. If you don't, please upgrade to a modern OS if you really want this feature.

It's especially a problem to add new overlays to the icon on Linux as its tray icon API doesn't allow proper icon theming after rasterization (what is necessary to paint an overlay). And we don't want to create a lot of tray icon identifiers with variants for every overlay combination.
