### ISSUE TITLE
[Feature request] Edit older messages with keyboard shortcut

### ISSUE THREAD

**Issue by andreyorst** [telegramdesktop/tdesktop#3410]
Telegram desktop features editing last message by pressing up arrow key. It is great, but lets go further a bit. If I send several messages, like this:
_message one
messa**hr** two, wh**u**ch conta**u**ns mistakes
message three_
and then press arrow key,it will open edit window for the last message, which has no mistakes, and if i will continue press up arrow telegram will start to scroll chat. 

So the idea is to allow continuously press arrow key to switch messages. Or use ctrl+up for this and save scrolling ability. As Telegram Desktop already uses Alt+Up/Down to switch between chats, I don't think that it is hard to implement another very useful shortcut.

Actual behaviour:
![default](https://cloud.githubusercontent.com/assets/19470159/26157263/74c5e806-3b21-11e7-9aa9-c0a17ac5b9c9.png)

**Comment by yggasser** [comment]
It looks cool, dude!

**Comment by stek29** [comment]
#2109
