### ISSUE TITLE
Contacts (except favorites) are not shown after upgrade to 1.1.2

### ISSUE THREAD

**Issue by mgrybyk** [telegramdesktop/tdesktop#3411]
### Steps to reproduce
1.  upgrade to 1.1.2
2. see contacts

### Expected behaviour
contacts should be shown

### Actual behaviour
contacts except favorites are not

### Configuration
windows 10 latest

1.1.2

default

**Comment by john-preston** [comment]
@mgrybyk Can you provide some more information? You mean chats list except pinned chats?

Can you attach "log.txt" after the last launch here? It is located near the Telegram.exe file, by default at "C:\Users\your_username\AppData\Roaming\Telegram Desktop\log.txt"

**Comment by mgrybyk** [comment]
HI again  after multiple restarts and some time other contacts (including pinned) appeared. Sadly I dont have logs at the moment of issue. 

Closing it for now. If anyone else faced to this issue - just wait / restart app or use search to access particular contact.
