### ISSUE TITLE
[feature request] Collect channels with mutual themes in single feed

### ISSUE THREAD

**Issue by vaniakosmos** [telegramdesktop/tdesktop#3415]
My situation: I have many channels with memes and news, and switch between all these channels just to read one post from each is very inconvenient. 

It would be cool to be able to congregate all channels with same theme under one channel and read all newly added memes without extra clicks. 

How I approximately imagine this is on attached picture.
![tg-feed](https://cloud.githubusercontent.com/assets/16745500/26228950/8f0682d6-3c46-11e7-8a85-40031af1b265.png)

**Comment by MasterGroosha** [comment]
I like your picture, it's really nice, however, that's an API issue.
