### ISSUE TITLE
[Feature request] Integrate with native OS sharing functions

### ISSUE THREAD

**Issue by pindab0ter** [telegramdesktop/tdesktop#3417]
I'm a macOS user and have noticed that the [Telegram for macOS](https://macos.telegram.org) client supports using the sharing function (see image). I would like this feature to be implemented for macOS, as well as Windows and/or Linux if applicable.

<img width="133" alt="screen shot 2017-05-19 at 14 16 26" src="https://cloud.githubusercontent.com/assets/5128166/26247356/c8be2cb6-3c9d-11e7-9335-c6aee38c7f9b.png">

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#1983

**Comment by pindab0ter** [comment]
I had, just not thoroughly enough. My apologies.
