### ISSUE TITLE
Close fullscreen button not working

### ISSUE THREAD

**Issue by fkkkkkkkkk** [telegramdesktop/tdesktop#3419]
### Steps to reproduce
1. Open any fullscreen video\image
2. Button not work at well

### Expected behaviour
Look attached video

### Actual behaviour
Look attached video

### Configuration
**Operating system:**
   OS: Arch Linux 
    Kernel: x86_64 Linux 4.10.16-1-ck-ivybridge
    Uptime: 50m
    Packages: 1073
    Shell: zsh 5.3.1
    Resolution: 1366x768
    DE: Cinnamon 3.2.8
    WM: Muffin
    WM Theme: Arc-Dark (Arc-Dark)
    GTK Theme: Arc-Dark [GTK2/3]
    Icon Theme: Numix-Circle-Light
    Font: Noto Sans 9

**Version of Telegram Desktop:**
1.1.2

**Used theme**:
https://t.me/TeleArc/103
[ File : arc_dark.tdesktop-theme ]

![video](https://cloud.githubusercontent.com/assets/5092164/26274674/5a3dd4c8-3d4f-11e7-8d45-eb4f03a6500f.gif)

**Comment by john-preston** [comment]
I'm afraid this is a question to your system, why it hijacks the mouse input from on-top window to the system menu :/

A pull request with a fix will be welcome, I don't know how to bypass such things, it doesn't happen in Ubuntu, for example.

**Comment by xvitaly** [comment]
@john-preston This happen only on multi-monitor configurations.

**Comment by larfadin** [comment]
@xvitaly it works on archlinux gnome with multi monitor.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
