### ISSUE TITLE
Mac Scroll up on Laptop

### ISSUE THREAD

**Issue by Sulium** [telegramdesktop/tdesktop#3422]
### Steps to reproduce
1. Use a mac on telegram desktop
2. 
3. 

### Expected behaviour
There should be a scrollbar in chats, it's very hard for us mac laptop users with trackpads to scroll up cause we have to use 2 fingers which is near impossible. 

### Actual behaviour
There is no scrollbar, making it basically impossible for you to scroll up in telegram chats.

### Configuration
Brand new Mac 2016 laptop

**Version of Telegram Desktop:**
Latest version

**Used theme**:

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
@Sulium What if you move mouse pointer close to the right side? Scrollbar should become visible.

**Comment by Sulium** [comment]
The scroll bar is not visible when you do that.

**Comment by stek29** [comment]
Are you 100% sure you're talking about Telegram Desktop and not about Native Telegram app for macOS?

**Comment by Sulium** [comment]
Yes telegram desktop for Mac OS, Scroll bar doesn't work making it
impossible for trackpad users to scroll up in chats.

**Comment by Sulium** [comment]
I can take a video recording if you want me too.

**Comment by john-preston** [comment]
@Sulium It can be not too visible, but it becomes visible when you scroll the chat. What version of Telegram Desktop do you use?

**Comment by stek29** [comment]
@john-preston but he needs the scrollbar to scroll the chat

**Comment by Sulium** [comment]
On the mac laptops if you are using a trackpad we need to see the scrollbar
at all times so we can just drag it up.

**Comment by stek29** [comment]
I never use scrollbar, and rely on gestures heavily.
Also, I still can't reproduce the issue, and it works perfectly fine for me.

![scrollbar](https://cloud.githubusercontent.com/assets/11808223/26470520/a7908d1e-41a6-11e7-9d8e-0dd340b77747.gif)

**Comment by Sulium** [comment]
This is on on the mac laptop here is a screenshot: http://prntscr.com/fg10k8

I'm not using a mouse just trackpad and it's extremely difficult for me to
scroll up as I've got to do a weird 2 finger gesture. With every other
program other then telegram there is always a scroll bar on the side 24/7,
and in order for me to read telegram chats you need to add / fix this issue.

Btw, sorry for not responding, I've been really busy running my company.

Thanks, looking forward for a fix.

**Comment by john-preston** [comment]
@Sulium Hi. This is not the Telegram Desktop app, but another Telegram app for macOS. You can check out Telegram Desktop from https://desktop.telegram.org

**Comment by stek29** [comment]
> Are you 100% sure you're talking about Telegram Desktop and not about Native Telegram app for macOS?
> 
> Yes telegram desktop for Mac OS

Meh.
Anyway, you can either use TDesktop or report this issue to https://t.me/macswift

**Comment by Sulium** [comment]
oh telegram desktop fixed it. my bad.

**Comment by Sulium** [comment]
anyways with telegram desktop on the new macs, can you add some touch bar
support, like the emoji thing, maybe some other things to, skype and pretty
much everything else big already supports it.

**Comment by stek29** [comment]
@Sulium That's another issue -- see #2853.

@auchri I guess this issue is fixed.

**Comment by anxolin** [comment]
I have the same issue with:

macOS Sierra: 10.13.3
Telegram: 3.8.118923 Stable

I don't see the scrollbars, so I cannot scroll using my mouse (it's very annoying because I use a external mouse and keyboard and I don't have the trackpad nearby).

It also don't work the `Fn + arrow up` to scroll, that is a standard in mac for scrolling.

**Comment by stek29** [comment]
> Telegram: 3.8.118923 Stable

That's not TDesktop, that's another app.
