### ISSUE TITLE
[Feature request] Modify notification sound and receive call sound

### ISSUE THREAD

**Issue by DutyCorp** [telegramdesktop/tdesktop#3423]
Dear Telegram Desktop developers,

I think it's a good idea to modify notification sound and receive call sound just like Mobile version. Therefore we can change notification sound and receive call sound anytime we want

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#151

**Comment by stek29** [comment]
@auchri Well, there's nothing about ringtone in #151... So what about editing it? :D
