### ISSUE TITLE
Member preview of group remains unchanged after opening another group

### ISSUE THREAD

**Issue by fadavi** [telegramdesktop/tdesktop#3424]
### Steps to reproduce
1. Open a group. (name this group "A")
2. Look at the members preview by hovering the mouse on the top bar.
3. Go back and open another group. (name this group "B")
4. Look at the members preview by hovering the mouse on the top bar.

### Expected behaviour
See members preview of second group (B)

### Actual behaviour
You'll see members preview of first group (A)

### Configuration
**Operating system:**
Ubuntu 17.04 Zesty Zapus

**Version of Telegram Desktop:**
1.1.2

**Used theme**:
Default official theme

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by fadavi** [comment]
@Aokromes as far as I tested, its fixed.
