### ISSUE TITLE
Chinese characters ?

### ISSUE THREAD

**Issue by taijuin** [telegramdesktop/tdesktop#343]
tdesktop v 0.7.1 16.12.14
Linux: font for Korean characters added.
----------------------------------------------------------

So Chinese (Taiwan)、Chinese (China)、Japanese...?

**Comment by giyyapan** [comment]
#88

**Comment by deng-kai** [comment]
I need this fix. Thank you

**Comment by taijuin** [comment]
the answer is in : #375

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.
