### ISSUE TITLE
Telegram Web not sending SMS, "too fast"!

### ISSUE THREAD

**Issue by Yoshimaster96** [telegramdesktop/tdesktop#3430]
I tried several times to log in to Telegram Web, but I didn't receive the SMS message. I was confident the phone number is correct. Why is it doing this?

Second, after several tries, it says I was "too fast" and I should try later. Well excuse me for not being able to log in! How long do I have to wait? Is it possible for you to remove this flag from my account?

**Comment by auchri** [comment]
@Yoshimaster96 This repo is for Telegram Desktop only.

**Comment by Yoshimaster96** [comment]
@auchri Where do I post Telegram Web issues then?

**Comment by Aokromes** [comment]
https://github.com/zhukov/webogram/issues

**Comment by maxoku** [comment]
@auchri Did you forget to close that thread? lol 
It's very strange, cuz you didn't have trouble with closing mine without a reason^^.

**Comment by auchri** [comment]
@maxoku It's very strange, cuz I've also other things to do.

**Comment by maxoku** [comment]
@auchri Of course no contents in your reply^^. 
I meant when you added the invalid label you could close the topic at the same time like you did before. 
And if you're so busy then why you're closing threads without a reason? It seems like you had too much time at the moment lol.

**Comment by stek29** [comment]
@maxoku What threads were closed "without a reason"? You didn't write the link to the closed threads^^.

**Comment by maxoku** [comment]
@stek29 I mean that one with invalid label and you wrote in it: https://github.com/telegramdesktop/tdesktop/issues/3465
@auchri Won't you close this thread?

**Comment by ghostskull789** [comment]
well I am having the same issue on the desktop too. I am running it on  mac and after receiving many messages i am unable to reply anyone.
