### ISSUE TITLE
Cross compiling

### ISSUE THREAD

**Issue by p4t0g3n0** [telegramdesktop/tdesktop#3431]
Can I compile Telegram Desktop for Mac and Windows using Ubuntu ?

**Comment by stek29** [comment]
You can't compile any program for Mac and Windows using Ubuntu. Maybe Wine could help you with Windows, but not for Mac, sorry.
Also, this is completely unrelated to TDesktop.

**Comment by Aokromes** [comment]
If you are looking to have the latest of all you can always go to https://ci.appveyor.com/project/telegramdesktop/tdesktop to get precompiled windows binaries.
If you are looking to compile your modifications, you will need to setup your own appveyor account.
@auchri close :)

**Comment by stek29** [comment]
And https://github.com/stek29/homebrew-tdesktop has straightforward and scriptable instructions for Mac. But I'm not sure apps built using it would run on other devices :D

**Comment by p4t0g3n0** [comment]
Thanks I'm going to check both links :D
