### ISSUE TITLE
Emoji dialog doesn't work

### ISSUE THREAD

**Issue by ubcent** [telegramdesktop/tdesktop#3435]
Hello. Sometimes emoji dialog doesn't open and hotkeys don't work in MacOS version. Restarting helps. I don't understand how you can reproduce it. I observed this behavior twice.

### Configuration
MacOS

Telegram 2.99.95700 AppStore

**Comment by stek29** [comment]
This is TDesktop repo.
You can report issues with macOS native app at https://t.me/macswift

**Comment by ubcent** [comment]
OK, thanks!
