### ISSUE TITLE
Telegram Linux can't display Bengali font on Arch Linux

### ISSUE THREAD

**Issue by fakeid30** [telegramdesktop/tdesktop#3448]
### Steps to reproduce
1. Install Arch or Antergos with GNOME 3.
2. Run Telegram
3. Get a message in Bengali . Sample message : আই লাভ ইউ 

### Expected behaviour
I should see the Bengali text

### Actual behaviour
White box appears

### Configuration
Antergos - 2017.5

**Version of Telegram Desktop:**
1.1.2

**Used theme**:
 Arc desktop v2 & Default

![screenshot from 2017-05-28 00-09-08](https://cloud.githubusercontent.com/assets/26362832/26523477/4355412e-433a-11e7-989b-c35cf7f5a395.png)

**Comment by fakeid30** [comment]
Fixed! 

1. Install "noto-fonts" & "ttf-hack" package

**Comment by swarupsro** [comment]
same problem faced ! But ttf-hack is not available for ubuntu 16.04.3 lts

**Comment by d0tfile** [comment]
@swarupsro try [this](https://github.com/source-foundry/Hack#linux).
