### ISSUE TITLE
Disable emoji/gif/sticker panel on fullscreen window

### ISSUE THREAD

**Issue by r105m** [telegramdesktop/tdesktop#3457]
I am not using emoji/stickers, and i do not want to see emoji/gif/sticker panel if my telegram window is fullscreened. It looks like "odnoklassniki".
Maybe this panel can be disablable?

**Comment by stek29** [comment]
@r105m what about clicking on "smilik" near mic icon?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3399
