### ISSUE TITLE
Message date tooltip breaks after cmd+h pressed (macOS)

### ISSUE THREAD

**Issue by chevsky** [telegramdesktop/tdesktop#3461]
### Steps to reproduce
1. Open any chat;
2. Hover your cursor on message date to make tooltip visible;
3. Don't move the cursor and press cmd+h to minimize the window;
4. Open Telegram again.

### Expected behaviour
Message date tooltip is hidden.

### Actual behaviour
Message date tooltip stays on the screen. It stays even if window is minimized via yellow top left button.

### Configuration
**Operating system:** macOS Sierra (10.12.4)

**Version of Telegram Desktop:** 1.1.2

**Comment by stek29** [comment]
Lol.
![image](https://user-images.githubusercontent.com/11808223/27339290-12d24912-55e0-11e7-915c-c6ee7a4f3fd8.png)
