### ISSUE TITLE
Replace emoji properly or manually set

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#3463]
The option to replace emoji doesn't work like it should. It doesn't allow to replace the all variations like ;p ;-p ;P ;-P, only ;-P is supported while without wink is :-p. I can understand that xD should be only that way cuz normal text like xd or XD could be a normal text and be confused unwillingly with emoji (especially xP if it would be added lol), but emoji started with : or ; should be in all variants. 

The second problem is that some of them are replaced with wrong emoji. Maybe an option to manually bind text with chosen emoji should be a good solution if there are problems with it?

**Comment by auchri** [comment]
Duplicate

**Comment by maxoku** [comment]
What duplicate? You didn't write the link to the duplicate thread^^.

**Comment by stek29** [comment]
#780. 7th result for query `is:issue is:open replace emoji`.
