### ISSUE TITLE
Solid color background

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#3464]
It would be nice to set a color to background, not only images.

**Comment by auchri** [comment]
Duplicate

**Comment by maxoku** [comment]
What duplicate? You didn't write the link to the duplicate thread^^.

**Comment by stek29** [comment]
@maxoku [Please, use the search](https://github.com/telegramdesktop/tdesktop/issues?utf8=✓&q=is%3Aissue%20solid%20color)
#820

**Comment by maxoku** [comment]
@stek29 
Thank you, that one I probably missed or something ;p.
