### ISSUE TITLE
Open maximized after click on tray icon

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#3465]
**Steps to reproduce**
1. Maximize the window
2. Minimize to the taskbar
3. Click on the tray icon

**Expected behavior**
Window should open in maximized

**Actual behavior**
Window is opened small (restored)

**Configuration**
Operating system: Windows XP
Version of Telegram Desktop: 1.1.2

**Comment by auchri** [comment]
I dont know what you mean.

> Windows XP

You should really not use windows XP.

**Comment by maxoku** [comment]
?? It supports Windows XP afterall.
Check if it's the same on other systems and then decide about the thread^^.

**Comment by stek29** [comment]
@auchri but Windows XP is listed in supported OSes. Also, just because of XP support tgvoip uses two different APIs on Windows depending on OS version. So I guess it's not getting dropped soon.
One of the reasons TDesktop uses Qt5.6 is XP and OS X 10.7/10.8 support.

**Comment by maxoku** [comment]
@auchri 
Could you answer me already?

**Comment by RememberTheAir** [comment]
I can confirm this on Windows 7 and 10, btw. Telegram won't remember its size after being minimized to tray/closed with `CTRL+W`, if we used one of the Windows shortcut to resize the window (drag to top to maximize, drag to sides to take half of the screen). Also, the more you try, the more the window tends to hide outside of the screen borders
