### ISSUE TITLE
Load on last chat after click on tray icon

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#3466]
**Steps to reproduce**
1. Open chat with a contact
2. Close chat window (x) to be minimized to tray
3. Click on tray icon to open chat window

**Expected behavior**
The window should be opened on last chat

**Actual behavior**
The window is opened without any chat selected

**Configuration**
Operating system: Windows XP
Version of Telegram Desktop: 1.1.2

**Comment by auchri** [comment]
Duplicate

**Comment by maxoku** [comment]
What duplicate? You didn't write the link to the duplicate thread^^.

**Comment by maxoku** [comment]
What duplicate? You didn't write the link to the duplicate thread^^.

**Comment by auchri** [comment]
@maxoku Because it's YOUR exercise to search for related issues before opening new ones.

**Comment by maxoku** [comment]
I don't agree. Well I didn't find it before, so I won't find it this time also^^. 
I don't know what thread you have in mind, but you know it exactly, so what's the harm to post the link? 
I believe you should reason your decision. Maybe you are mistaken and thread you're talking about isn't about the same issue, so I should have a possibility to response.

**Comment by auchri** [comment]
I don't know the exact issue, I have to search it too.

But since it seems that you are too lazy to do a thorough search, here you are: https://github.com/telegramdesktop/tdesktop/issues/2541

**Comment by maxoku** [comment]
Thank you. I wouldn't really guess is the same issue after reading only a title and I don't have a time to read everything, there are hundreds of threads after all. 
It would be nice if you'd answer to my other threads you just closed too.

**Comment by stek29** [comment]
@maxoku if you don't have time to make sure you issue isn't a duplicate, maybe you should not report it at all? It's awfully disrespectful. People like you were the reason Telegram for Android doesn't have public issue tracker anymore, and if @auchri wasn't here, TDesktop issue tracker wouldn't be very useful either.

**Comment by maxoku** [comment]
@stek29 Does anyone have time to read 700 threads? And don't be so rude, cuz you're being disrespectful right now.
