### ISSUE TITLE
Quoting/replying issues

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#3467]
I like the option to quote messages on Skype. On telegram there is a similar option to reply, but there are issues with it. 
1. It would be nice to quote a message without actually replying, adding an additional text to it. 
2. The quoted message is wrapped so I can't read it fully. 
3. If images are quoted there's only a very small thumbnail of it. When I click on it, it sends me to that image, but if I have few similar images next to it it might be hard to determine which one is it. So it would be nice to immediately open the image or mark that image after sending to it. 

4. Quoted messages (reply or forwarded) doesn't put a time of the quoted message. 
5. When I'm forwarding the message there's a possibility to add a text, but that text isn't bind with forwarded message, only posted separately before the forwarded message.

**Comment by stek29** [comment]
API issue.

Also, when you reply to something and go to original message, it gets highlighted.
And don't use reply for case you're describing, use "forward".

**Comment by maxoku** [comment]
The message isn't highlighted. 
Which case do you have in mind? 
What "forward" function do and how can help me here?

**Comment by stek29** [comment]
@maxoku right click on message -> forward. What theme are you using? When going to message from reply it should highlight it.

**Comment by maxoku** [comment]
@stek29 
I know there's a forward function there, I'm not blind. I asked how does it work and how can it help me? Nevermind I just figured out that is a quoting function, but doesn't allow to add text to it and it's annoying cuz I have to choose a contact before it would appear in the message box.
I don't use any there or default one. It isn't highlighted. 
I have another issues, so I'll edit the first post.

**Comment by stek29** [comment]
Forward and reply are only options. 
Behaviour you're describing is normal for forward.
If it doesn't suit you, you'd have to contact Telegram via in-app support, or via Twitter.

All the "issues" you're experiencing are server side limitations, Sorry.

**Comment by maxoku** [comment]
@stek29 Which ones exactly? I posted several issues.

**Comment by stek29** [comment]
@maxoku I can see only "Telegram is missing quote like skype" issue.
Also, what's wrong with replying and greentexting some parts of text?

**Comment by maxoku** [comment]
@stek29 Not my fault you're blind. I posted 5 issues.
And what do you mean with: what's wrong with replying and greentexting some parts of text?

**Comment by stek29** [comment]
@maxoku 
> you're blind

Wow, that's not nice. What if I'm actually blind? 

> I posted 5 issues

In one issue. That's not what people normally do.
Also, would be nice if you at least made some list to clearly see the issues.

> And what do you mean with: what's wrong with greentexting some parts of text and replying?

Just look at this comment. I'm replying to you, and use `>` to highlight parts I'm replying to. I can also modify them, as I did in last one. You can do exact same thing in Telegram, but it won't be highlighted ofc.

**Comment by stek29** [comment]
> It would be nice to quote a message without actually replying

API issue.

> The quoted message is wrapped so I can't read it fully

Actually it's not even wrapped, it's just a message id of original message. So if it gets deleted, "preview" won't show anything too. So that's intended behaviour.

> If images are quoted there's only a very small thumbnail of it

See prev line

> When I click on it, it sends me to that image, but if I have few similar images next to it it might be hard to determine which one is it. So it would be nice to immediately open the image or mark that image after sending to it.

The original message is highlighted for a short amount of time (see screenshot). If it's not, then there should be a bug on your system.
![image](https://cloud.githubusercontent.com/assets/11808223/26756934/f22b17a2-48b5-11e7-9d67-c4adfdb0a81a.png)

> Quoted messages (reply or forwarded) doesn't put a time of the quoted message.

That's what other official apps do, but it's not an API issue indeed, sorry.

> that text isn't bind with forwarded message, only posted separately before the forwarded message

API issue, that's how forwards work.

**Comment by maxoku** [comment]
@stek29 Happy now? ;p
1. Okay, it's api issue, I can use forward for that (and only that lol)
> Actually it's not even wrapped, it's just a message id of original message. So if it gets deleted, "preview" won't show anything too. So that's intended behavior.
2. It shouldn't be like that. It should show full message if desired. If message is still available it should show it full. 
> See prev line
What prev line? It's not the main issue here^^. 
> The original message is highlighted for a short amount of time (see screenshot). If it's not, then there should be a bug on your system.
So if it's a bug then I should create a new thread to report bug? I bet @auchri will close it immediately^^.
> That's what other official apps do, but it's not an API issue indeed.
So it's a valid issue to report and require a feature then ;p.
