### ISSUE TITLE
Create diffs rather than full source code in Qt patch

### ISSUE THREAD

**Issue by SafaAlfulaij** [telegramdesktop/tdesktop#347]
As in title, It's better and cleaner to use the diffs as the qt files might change anytime.

**Comment by telegramdesktop** [comment]
They are done only for one exact version of Qt, when moving to the next version all changes should be reviewed, it happens they are not needed anymore.

I'm not sure how to make diffs with easy way to apply them in all OS (as easy as copying with replacement is for current patch format).
