### ISSUE TITLE
Automatically log out after restarting MacBook

### ISSUE THREAD

**Issue by gustavoavena** [telegramdesktop/tdesktop#3471]
### Steps to reproduce
1. I should restart my Mac, open Telegram and still be logged in.
2. When I restart my Mac, I automatically log out of Telegram.
3.  My configuration:

MacOs Sierra 10.12.3
MacBook Pro 15" 2016 with Touch Bar
Telegram 2.99.95700 - App Store Version
Default Theme (are there others? I didn't know...)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@gustavoavena This is another Telegram macOS application. You can try Telegram Desktop from https://desktop.telegram.org

**Comment by gustavoavena** [comment]
Thanks @john-preston! Sorry for the trouble...

**Comment by stek29** [comment]
@gustavoavena you can report Swift app's issues at https://t.me/macswift.
