### ISSUE TITLE
Video messages in shared media

### ISSUE THREAD

**Issue by vtni** [telegramdesktop/tdesktop#3480]
On a person's profile we can see all sent/received pictures, files, voice messages and so on. It would be nice, if also all video messages (recent new feature) would be listed somewhere.

**Comment by vtni** [comment]
update: I saw that on mobile (android) the video messages are listed under files but not on the Desktop client. Has this a specific reason?

**Comment by stek29** [comment]
@vtni I guess it's just not implemented yet

**Comment by iota77** [comment]
Ping
