### ISSUE TITLE
Can't create public username which start from numbers

### ISSUE THREAD

**Issue by proandreyyy** [telegramdesktop/tdesktop#3482]
### Steps to reproduce
1. Create new channel
2. Change public channel address 
3. Type Channel username, which start from numbers

### Expected behaviour
Tell us what should happen:
I want to create public username for channel in "t.me/123name", that start from numbers!

### Actual behaviour
Tell us what happens instead:
I have an error, says, that I can't use this username

### Configuration
**Operating system:**
Any

**Version of Telegram Desktop:**
Any

**Used theme**:
Every time 

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@proandreyyy Can you create it from another app? Like iOS / Android?

**Comment by stek29** [comment]
@proandreyyy Server won't accept username starting with numbers (it returns error 400 USERNAME_INVALID)

**Comment by proandreyyy** [comment]
@john-preston no. 
Android, iOS, mac, windows...

**Comment by proandreyyy** [comment]
@stek29, why? What the reason to not do anything to solve this problem? Question to telegram developer)

**Comment by stek29** [comment]
@proandreyyy Ask server side developers then -- through the support or twitter.
It's a server side limitation, TDesktop has nothing to do with it.
