### ISSUE TITLE
Create Emoji WebP files for different emojiset

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#3483]
Hi, is there anyway to easily create emoji's webp file for different emoji set, so that I could replace default emoji with another one?
previously, by help of @PeterCxy, I create webp file for emojione, by using following command and changing default emoji font in generator.cpp file:
```bash
gyp --depth=Telegram/gyp --generator-output=../.. -Goutput_dir=out Telegram/gyp/codegen.gyp --format=cmake
cd out/Release
cmake
make codegen_emoji
./codegen_emoji --images -o emoji
```

**Comment by stek29** [comment]
Can't you just replace `/Telegram/Resources/art/emoji.webp` ?

**Comment by morealaz** [comment]
@stek29: that's exactly what I want to do. the question is how to create those emoji webp files?
as I say, I done it previously, but by a bit of hack from @PeterCxy on the code. My question is that, is there any straightforward approach to create these files without need to hack code for every single release!!

**Comment by stek29** [comment]
@morealaz You just replace the file and build app normally, that should be enough.

**Comment by stek29** [comment]
@morealaz So, have you managed to do it?

**Comment by Cthutq1** [comment]
Старый баран. Не могу восстановить потерянны файлы PNG, ДЖИФ, jpg, docx в doc, лента, ТХТ, PDF, или ЗИП. Вы на до мной не смейтесь. Может не то сказал.

**Comment by stek29** [comment]
@Cthutq1 Вы обратились явно не по адресу, и здесь вам не помогут -- разве только заблокируют. Пожалуйста, перестаньте писать не по теме и на русском.

**Comment by shiba89** [comment]
@stek29 I'd like to know how to create those WebP too. I somewhat managed to build that `codegen_emoji`, but it comes without documentation so I have no idea how it should be used.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5958
