### ISSUE TITLE
Favorite emojies

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#3486]
It would be nice if I could choose favorite emojies to be displayed at top instead of recent ones.

**Comment by maxoku** [comment]
@auchri 
Are you kidding me? What duplicate? I was searching for threads like that and couldn't find any.

**Comment by stek29** [comment]
#1707

**Comment by maxoku** [comment]
@auchri @stek29 
Ah, I couldn't find it cuz it's closed already lol. Now both are closed, I suggest to reopen one of them ;p.

**Comment by auchri** [comment]
@maxoku I suggest you to use the template for each issue you create.

**Comment by maxoku** [comment]
@auchri What template?

**Comment by stek29** [comment]
@maxoku There's a template when you create an issue.

**Comment by maxoku** [comment]
@auchri @stek29 You mean the steps and behavior text?

**Comment by stek29** [comment]
@maxoku I guess so.

**Comment by maxoku** [comment]
@auchri @stek29 Well when I used it my thread was closed because of it, so no, thank you lol. 
It wouldn't make any sense with some threads. When I see it's fit then I use it.
