### ISSUE TITLE
Open images from link previews in Telegram

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#3488]
Steps to reproduce
1. Sent link of a page containing an image
2. See preview with a thumbnail of that image
3. Click on that thumbnail

Expected behavior
See image in full size in Telegram

Actual behavior
The page is opened in the browser

Configuration
Version of Telegram Desktop: 1.1.7

If it already loads a thumbnail of the image why can't open it in full size? Why instead of that I need to trouble the browser for that?
@auchri Happy now? ;p

**Comment by Lonami** [comment]
This is happening when the `webPage`'s `type` is `"document"` instead of `"photo"`, even if the `webPage` only has a `photo` present. `tdesktop` should probably guide itself by the photo field being present, not the string.

**Comment by Lonami** [comment]
Probably this?:
https://github.com/telegramdesktop/tdesktop/blob/1ebd9562a2c5bd797f06c961e6282307a2e8602d/Telegram/SourceFiles/data/data_web_page.cpp#L131-L139

**Comment by SmartManoj** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6266#issuecomment-510008596

**Comment by bb010g** [comment]
Would this be a good first issue?

**Comment by maxoku** [comment]
Is it solved?

**Comment by Lonami** [comment]
No, I'm pretty sure it's not solved yet, a friend complained recently about it.

**Comment by maxoku** [comment]
Still not resolved.

**Comment by maxoku** [comment]
Still not resolved.

**Comment by Aokromes** [comment]
> Still not resolved.

https://i.imgur.com/zjcBSxJ.png

**Comment by maxoku** [comment]
> > Still not resolved.
> 
> https://i.imgur.com/zjcBSxJ.png

???
