### ISSUE TITLE
Delete message for everyone by default

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#3490]
Steps to reproduce
1. Write a message of any kind
2. Right click to delete message
3. Click on 'Delete' to delete message

Expected behavior
The message should be deleted for everyone

Actual behavior
The message is deleted only for me

Configuration
Version of Telegram Desktop: 1.1.7

By default should be checked to delete for someone else or everyone. Or only a checkbox (unchecked) that it would be deleted only for me. I thought that way was before, but my friend told me otherwise. Nevertheless I don't need to delete messages only for myself and if I forgot to check it, it will remain for others for confusion.

**Comment by john-preston** [comment]
@maxoku This works how it is supposed to. It should not delete for everyone by default.

**Comment by john-preston** [comment]
I appreciate your feedback about how things should work in this or any other matter (in other issues), but this is not your or mine call to make and it is not decided in this repository issues.

Those issues are for bug reports and pull request for fixing them in the first place, sorry.

**Comment by maxoku** [comment]
@john-preston 
Then maybe an option that it would be checked by default.
It doesn't work like it suppose to for me. I already gave my reasons and you none.
Don't close it before debating^^.
And what do you mean it's only for bugs? It's also for requests and I'm making request^^.

**Comment by john-preston** [comment]
@maxoku This is not for requests, the application development is not community driven. Yes, you give your feedback, and I will know, that one or more users want to see things working that way.

We're not debating here, where you convince me that some other way is better. This is an official desktop application for Telegram, so the team decides how this is going to work.

For instance, the leading applications are Telegram for iOS and Telegram for Android, while Telegram Desktop is catching up with them. So in every common for all apps thing, like "are the messages deleted by default for me or for everyone or this should be a checkbox in settings" the way that Telegram Desktop implements is the way it takes from iOS / Android apps, like the Telegram team decided it to be (the project leader, the UI / UX designers, etc).

You don't argue with them here, they're not here in the first place. Also you can't expect me (the developer) to argue with every request and suggestion you have with them on your behalf, this is not my job. So I appreciate your feedback, but the main purpose for the issues here is improving the quality of that app, fixing and improving the things how they are intended to work, not to change the way they work.

**Comment by savv** [comment]
FWIW, I would love to have an option for this as well.

**Comment by rajkumaar23** [comment]
This is completely in contrast to what is available in mobile versions. iOS has two **separate** buttons `Delete for me` and `Delete for everyone`, whereas Android (Telegram X) has the `Delete for everyone` **checked by default**. Why can't the same be applied to the desktop application (atleast in one-on-one chats)?

**Comment by RememberTheAir** [comment]
> whereas Android (Telegram X) has the Delete for everyone checked by default

Telegram X is an experimental app which has a lot of freedom and might decide to not follow general Telegram guidelines when implementing things, like in this case. The official stable mobile apps don't check that checkbox by default, and tdesktop is consistent with that

**Comment by rajkumaar23** [comment]
Okay, and why not two separate buttons? which is there in iOS.
