### ISSUE TITLE
[Bug] View counter not updated when forwarding messages from channels groups. and view counter for 2 text message after each other, is not same. one counter is for example 3 and other is fpr example 300.

### ISSUE THREAD

**Issue by shirinzanjani** [telegramdesktop/tdesktop#3491]
my channel link is :
https://t.me/joinchat/AAAAAD9mIVRtkD5jnstFUQ

this channel has 23799 member, but all of channel messages dos not have view counter more than 300 or 400!!!

**Comment by stek29** [comment]
> this channel has 23799 member, but all of channel messages dos not have view counter more than 300 or 400!!!

Well, I guess it's not so popular \*shrug\*

Anyways, views are counted on server side. You can ping Telegram on Twitter or ask in-app support.

**Comment by shirinzanjani** [comment]
thanks for your answer.
i saw a question like this here, so i asked my question.
thanks for your help :)
