### ISSUE TITLE
Deleting your "joined the group" service message has incorrect description

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#3493]
### Steps to reproduce
1.  Join a supergroup
2.  Press "Delete" on your join service message

### Expected behaviour
Delete message description should mention that "This will delete it just for you, not for other participants"

### Actual behaviour
Delete message description says "This will delete it for everyone in this chat", which is incorrect, since only admins (and creator) of supergroup can delete service messages for everyone. Correct me if I'm wrong.

### Configuration
**Operating system:** Windows 10 LTSB x64
**Version of Telegram Desktop:** 1.1.7 alpha
**Used theme**: Doesn't matter.

**Comment by john-preston** [comment]
@MasterGroosha There is no way to delete any message just for one participant in a supergroup. So I think it is deleted for everyone. Or for no one at all :)

**Comment by stek29** [comment]
@john-preston Well, that's what it should be, but iirc service messages are not deleted for everyone, since it caused issues with users adding someone and deleting service message to hide it. 
In fact, those messages were undeletable for a long time, and now only admins can delete them.

**Comment by john-preston** [comment]
@stek29 Then the problem is that user sees the delete button at all? Because if they're not deleted for everyone they're not deleted for the user as well (you can test and see if they come back after the app is restarted).

**Comment by MasterGroosha** [comment]
Yep, my bad. The message re-appears after I restart the app. Sorry!

**Comment by stek29** [comment]
@john-preston Yup, it can't be deleted by user at all, so maybe app shouldn't even show delete button?

**Comment by john-preston** [comment]
@stek29 Yes, it should not I think. How does this message appear? When you join by invite link?

**Comment by stek29** [comment]
@john-preston Yes, you join a group by invite link. If "join" message doesn't appear, you can try leaving and joining again to see "You left the group" message.

**Comment by MasterGroosha** [comment]
@john-preston It appears when user joins either via username or invite link. Just tested both cases

**Comment by stek29** [comment]
@john-preston Also, why does that message disappear if server returns pts_count=0 when you try to delete it?

**Comment by stek29** [comment]
@MasterGroosha And theoretically if Alice adds Bob to the chat, Alice would see delete button too.

**Comment by john-preston** [comment]
@stek29 Because it is removed on the client side first and then the request is sent.

**Comment by stek29** [comment]
@john-preston What about hiding it, then checking if it gets deleted and if not, restoring/showing error message?

**Comment by john-preston** [comment]
@stek29 It requires supporting that thing (hiding / restoring a message in the middle of the conversation), it is not supported right now.

**Comment by MordaBoy** [comment]
Hello guys! Is it possible to delete service message "joined the group" for all members?

**Comment by Aokromes** [comment]
only if group owner adds a bot doing it.
