### ISSUE TITLE
Unable to connect call if IPv6 stack is disabled in the kernel

### ISSUE THREAD

**Issue by bbolgradov** [telegramdesktop/tdesktop#3495]
### Steps to reproduce
1. Disable IPv6 stack by using kernel parameter (e.g. add "ipv6.disable=1" to the kernel parameters in grub).
2. (Optionally) Disable IPv6 addresses on all interfaces by adding "net.ipv6.conf.all.disable_ipv6 = 1" to sysctl.conf and reloading it with sysctl -p or simply rebooting.
3. (Optionally) Uncheck "Try connecting through IPv6" in Telegram settings.
4. Try to make/answer a call.

### Expected behaviour
Should be able to connect the call.

### Actual behaviour
Doesn't get past Connecting state.

### Configuration
**Operating system:** Arch Linux 64-bit

**Version of Telegram Desktop:** 1.1.7

**Used theme:** Default

<details><summary>**Logs**:</summary>

[last_call_log.txt](https://github.com/telegramdesktop/tdesktop/files/1054364/last_call_log.txt)

[log_11_45.txt](https://github.com/telegramdesktop/tdesktop/files/1054363/log_11_45.txt)

</details>

**Comment by grishka** [comment]
May I ask, why would you disable the IPv6 stack in the kernel in the first place?
(I didn't even know it's configurable, unfortunately)

**Comment by bbolgradov** [comment]
The networks here don't support it. I've had issues with some other software that preferred my non-existent IPv6 so much that it never tried to use IPv4.

Another (maybe a bit paranoid?) reason one could have - not having to keep up with IPv6 security, since it's not used in the area. A fake IPv6 router advertiser at a public cafe would easily bypass any IPv4 security.

**Comment by grishka** [comment]
Okay, but shouldn't disabling IPv6 address (2 in your initial comment) be enough? I use a single dual-stack UDP socket to transfer both IPv4 and IPv6 traffic through it and, apparently, disabling the IPv6 stack in the kernel also disables the ability to have such dual-stack sockets. Which kinda makes sense, but still... I need to handle this error properly though. Generating hundreds of megabytes of logs of the same error never seems to be a good idea.

**Comment by bbolgradov** [comment]
Sure. I don't remember why I did it in both places, maybe I had an issue before.
However, I remember the night before, when I found this issue, that if I enable the stack and just disable IPv6 assigning, Telegram would crash sometimes when ending a call. I can't confirm that this was the issue though, I need to test more.

**Comment by grishka** [comment]
Fixed it in the library so it will now fail the call if the socket initialization wasn't successful. I'll push the updated version soon.

**Comment by ingvar-lynn** [comment]
Up fucking vote this crap.
Relevant log line:
`E/tgvoip: error creating socket: 97 / Address family not supported by protocol`

**Comment by Photon89** [comment]
I am also hit by this bug. Any news about it?

**Comment by globalqss** [comment]
same here -> v 1.3 01.06.18
disabling IPv6 is more important nowadays - about VPN IPv6 leak

**Comment by ilya-fedin** [comment]
Is this still valid? libtgvoip was replaced with webrtc.

**Comment by globalqss** [comment]
Here:
Operating system: Ubuntu 20.04.1 LTS
Version of Telegram Desktop: 2.3.2
IPv6 disabled

Call works without problem.
