### ISSUE TITLE
Russain letters are duplicated

### ISSUE THREAD

**Issue by vnmone** [telegramdesktop/tdesktop#3497]
### Steps to reproduce
1.  OS Windows 10
2.  switch to russian keyboard
3.  start typing

### Expected behaviour
Correct input of russian letters
### Actual behaviour
The letters are duplicated
For exaple:
"ппррииввеетт"

### Configuration
**Operating system:** Windows 10 pro x64

**Version of Telegram Desktop:** 1.1.7

**Used theme**: default

<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by andreyorst** [comment]
I've saw something similar, when typed my password in World of Warcraft client in russian layout - the `*` symbol that would normally appear was duplicated and for example for letter `Я` i saw `**` instead `*`.

**Comment by vnmone** [comment]
Issue is gone in v1.1.10
