### ISSUE TITLE
How to mark all messages as read?

### ISSUE THREAD

**Issue by mpco** [telegramdesktop/tdesktop#3501]
If can not make it, please add this feature.
Thank you!

**Comment by stek29** [comment]
Surprise-surprise: By actually reading them!

Please, use the issue template. If you're on macOS Sierra, there may be an issue with reading messages.

**Comment by auchri** [comment]
Also duplicate

**Comment by stek29** [comment]
Oh, I missed "all" word. Then it's a duplicate of #2697 indeed.
