### ISSUE TITLE
ability to rename *every* contact in desktop application 

### ISSUE THREAD

**Issue by restyler** [telegramdesktop/tdesktop#3503]
### Steps to reproduce
1. Get a chat of 30 people in Telegram
2. Try to rename some contacts 

### Expected behaviour
I expect to have "Edit" button in every user profile, like this: http://prntscr.com/fhap0n

### Actual behaviour
I don't have "Edit" button on some profiles: http://prntscr.com/fhaonf  which makes using Telegram for big chats unusable

### Configuration
**Operating system:**
Macos Sierra

**Version of Telegram Desktop:**
1.1.7

**Used theme**:
default

#

**Comment by stek29** [comment]
API issue (__and duplicate iirc__)

**Comment by FelikZ** [comment]
I do not have this button if contact is not in my contact book (i.e. I do not know their contact phone and its not added to a system contacts app, iOS).

How I add a note to a user or rename it then?

**Comment by john-preston** [comment]
@FelikZ Currently contacts can only be added by their phone number 😔

**Comment by Silun** [comment]
For contacts that I have added by username (and not by phone number), I find that I can not rename them - or edit any information at all. Please allow us to rename such contacts.

**Comment by RememberTheAir** [comment]
@Silun you can't add users to your contacts by username.

You can add someone only if you have the phone number - otherwise the only thing you can do is starting a chat.

Renaming users can't be a thing on Telegram Desktop as long as the API doesn't support it

**Comment by atk91** [comment]
Why if I have contacted t.me/someone desktop app cannot have an alias for @someone like 'John Doe'? Things will go bad when John Doe will try to change his username to @someoneelse ?

**Comment by atk91** [comment]
@RememberTheAir I was interested in why it's not possible without backend support. Maybe because those aliases needs to by synced across multiple apps instances?

**Comment by RememberTheAir** [comment]
@atk91 yes. Aliasing is something that needs to be synced across devices, because people would expect their other clients to use the aliases they defined from tdesktop. This thing seems totally feasible but needs backend support first, for platform consistency

**Comment by LunarWhisper** [comment]
Users want to be able to at least somehow rename these contacts. There are many cloud services that allow you to easily deliver the configuration file to any device with Internet access.

**Comment by Kinjeiro** [comment]
Hi!

Why closed this issue? It very important feature! Even Skype can do it... Skype, Carl!

We use telegram without phone numbers - just for work chats
And constantly see "HornyGirl" or "Jonh54" nicks very uncomfortable

![4211c17139df874e6251a4e413aee049](https://user-images.githubusercontent.com/1502068/53865943-6c70fd80-4001-11e9-8ce4-930a302d4b26.jpg)

**Comment by restyler** [comment]
> Why closed this issue? It's very important feature! Even Skype can do it... Skype, Carl!

Yup. After a few months of pain and suffering  because of this issue with contact names we just switched to Mattermost for inhouse chats, and skype for chats with external members.

**Comment by anevidomy** [comment]
hmmm... It's strange, that Telegram-programmers cannot fix this bug, it's very easy - you shouldn't sync changed contact names with all devices, just store them in desktop-program and it's enough for 99% users. Please do it!

**Comment by LunarWhisper** [comment]
It really makes it difficult to use the messenger in a corporate environment.

**Comment by stek29** [comment]
@domdorn why do you think "I'm thinking of switching back to WhatsApp" is a valuable addition to conversation? It's almost as if you expected Telegram developers to get worried because you're switching and rush to implement the feature.

**Comment by domdorn** [comment]
sorry @stek29, you're right. I also figured out that if I change the contact name in the mobile app, they stay how they are supposed to be and sync correctly to the desktop.

**Comment by AstraSerg** [comment]
Can you at least add a custom field like **alter name** that can be edited?

**Comment by john-preston** [comment]
@AstraSerg You will be able to add any person to contacts in the next release and name them as you like.

**Comment by AstraSerg** [comment]
@john-preston  Cool! Thanks!

**Comment by AstraSerg** [comment]
> @AstraSerg You will be able to add any person to contacts in the next release and name them as you like.

It's possible now in the recent version. Thank you very much!
