### ISSUE TITLE
Telegram shuts down when trying to set HUGE background image

### ISSUE THREAD

**Issue by andreyorst** [telegramdesktop/tdesktop#3504]
### Steps to reproduce
1. Download or create image about 16000x9000 pixels
2. Try to set background from this file

### Expected behaviour
Background should be set, or warning should be shown

### Actual behaviour
Telegram freezes a bit, then exits with no actual error report

### Configuration
**Operating system:**
Windows 7
**Version of Telegram Desktop:**
1.1.7
**Used theme**:
Breeze v3
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
Please upload this image somewhere ;)

**Comment by john-preston** [comment]
@andreyorst Out of memory perhaps..

**Comment by andreyorst** [comment]
@auchri 
https://drive.google.com/file/d/0B4tzN5LjfRj1QzNMLWgyN3Fnd0U/view?usp=sharing
or
https://drive.google.com/open?id=0B4tzN5LjfRj1WUo3X3VlRWtzRzQ

**Comment by andreyorst** [comment]
Did not happen on Linux

**Comment by stek29** [comment]
@andreyorst What was the memory usage on peak (just curious)?

**Comment by andreyorst** [comment]
@stek29 the normal usage on linux is about 120 MB. When I try to set this huge image it'st going up to 2.0 GB of RAM, and then drops down to 706.5 MB. After i revert the wallpaper to the default one it goes back to 122.5 MB or less.
Ah, and CPU usage is MASSIVE
![image](https://user-images.githubusercontent.com/19470159/27030165-e7ee290e-4f73-11e7-9750-7e9fe5552c18.png)
Tomorrow I will check it on windows

**Comment by andreyorst** [comment]
@stek29 And on Windows 7 Telegram shutdown itself around 700 Megabytes
Note the small ramp of RAM on the graph
![image](https://user-images.githubusercontent.com/19470159/27062481-fb706f84-4ff3-11e7-9283-1de0cda299d2.png)
(whoa, Windows 7 uses so much memory only by itself...)

**Comment by andreyorst** [comment]
Just got my Windows 10. Still happens with this kind of image. Peak memory usage is about 900 MB

**Comment by wodim** [comment]
How about you don't do something stupid like setting a huge image as your bg

**Comment by andreyorst** [comment]
@auchri how about you to be more polite?
My actual job is hardware/software tester, and I like to try uncommon things in software. Why would you even call such thing stupid? Because average user don't do it? Or because you don't? Well I guess I'm not you, and not the average user. I sexually identify myself as a huge background image, respect my rights to be set as a Telegram BG.

Yet, such behaviour and memory usage is not how application should work. I guess telegram tryes to set uncompressed raw image as a background. But I can't explain such insane memory and CPU usage, if it is true. Windows compresses image when you set it as a BG, even if it is a template image 4x4 pixels, it will be compressed. Maybe Telegram should do it too.

**Comment by auchri** [comment]
Why do mention me? I didn't write that comment.

**Comment by andreyorst** [comment]
@auchri sorry, mistyped. pressed tab, thought that it will switch to next name in the list, but it didn't

**Comment by wodim** [comment]
I don't think Telegram does anything, it's probably all handled by Qt. And yes I think it's stupid to set a huge image as a background, I understand as a tester you like to put things on the edge, but come on.
