### ISSUE TITLE
Clean all Message

### ISSUE THREAD

**Issue by telegram-api** [telegramdesktop/tdesktop#3505]
Do add method delete all messages in superGroup?

https://core.telegram.org/method/messages.deleteMessages
This method is limited.
Many messages in this group will be a lot of volume groups

applying for clean all Messages.

Thanks

**Comment by auchri** [comment]
I don't understand your request, sorry.
Also it's not related to Telegram __Desktop__.

**Comment by stek29** [comment]
@telegram-api channels.deleteMessages

**Comment by telegram-api** [comment]
Thanks for the answer

**Comment by telegram-api** [comment]
Hello
@stek29 This method will add? (delete all messages in supergroup).

**Comment by stek29** [comment]
@telegram-api I don't know, ask telegram on Twitter or via inapp support.
