### ISSUE TITLE
Sorry, this channel is not accessible.

### ISSUE THREAD

**Issue by shirakun** [telegramdesktop/tdesktop#3507]
Sorry, this channel is not accessible.
Method: account.getNotifySettings
Result: {"_":"rpc_error","error_code":400,"error_message":"CHANNEL_PRIVATE"}
Been kicked out once
Search for this again when you join
How do

**Comment by stek29** [comment]
You can't join if you was kicked, admins should remove you from banned list.

**Comment by lamlion** [comment]
so how to contact the admin to remove me from banned list?

**Comment by SG5** [comment]
@stek29, admin checks - i'am not in ban/restricted list, but I still get error message
