### ISSUE TITLE
-autostart and -startintray doesn't work on Ubuntu

### ISSUE THREAD

**Issue by vladislav805** [telegramdesktop/tdesktop#3508]
Want to add Telegram to autorun:
### Steps to reproduce
1. Open Terminal
2. `/opt/telegram/Telegram -autostart --` or `/opt/telegram/Telegram -startintray --`

### Expected behaviour
The Telegram was supposed to start in the system tray, without opening the window.

### Actual behaviour
In first case (autostart) nothing happened, process complete immediately. In second case (startintray) the icon appeared in the tray is clickable, but clicking on "Open Telegram" nothing happened. However, notifications about new messages "come" in correctly.

### Configuration
**Operating system:** Ubuntu 16.04 LTS

**Version of Telegram Desktop:** 1.1.7

**Used theme**: doesn't matter, same behavior

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@vladislav805 It was not supposed to work there (was not tested at all, this options were made for Windows version), but I'll try to debug it if I'll have some time.

A pull request with a fix for that bug and comments about the cause of it is also welcome.

**Comment by vladislav805** [comment]
So far only see that the Linux version is missing features `psAutoStart` and `psSendToMenu`

Versions: [Linux (specific_linux.cpp:622)](https://github.com/telegramdesktop/tdesktop/blob/81e728ada01713f562b0d7694eec57ed954e1786/Telegram/SourceFiles/platform/linux/specific_linux.cpp#L622), [Windows (specific_win.cpp:735)](https://github.com/telegramdesktop/tdesktop/blob/81e728ada01713f562b0d7694eec57ed954e1786/Telegram/SourceFiles/platform/win/specific_win.cpp#L735)

In Windows version `_manageAppLnk` create a `.lnk` file in special directory, where programs run automatically after startup.

But how add program to autorun in Linux I don't know...

**Comment by Aokromes** [comment]
#422 ?
