### ISSUE TITLE
[Feature Request] Favorite stickers tab

### ISSUE THREAD

**Issue by aaaguanabarito** [telegramdesktop/tdesktop#3511]
It's a bit inconvenient to have my favorite stickers pushed off the recents tab whenever I feel like using a new one, and then having to look for them again amid dozens of other sticker packs makes things all the more troublesome.

It would be great if you could add a **customizable "Favorites" tab** as a complement to the existing "Recents" one.

**Comment by stek29** [comment]
#3333
