### ISSUE TITLE
Historical searches unable to correctly locate post

### ISSUE THREAD

**Issue by Robadob** [telegramdesktop/tdesktop#3513]
### Steps to reproduce
1.  Search for a specific message in a telegram group (or probably conversation) from many months ago (In this case I've tried it with a few messages from January 2016)
2.  Click the selected message in the found message list

### Expected behaviour
It should scroll to and highlight the specific message

### Actual behaviour
It scrolls to a nearby point (I scrolled up a way and found the message in one instance) and doesn't highlight the message. If the message result button is clicked again, it scrolls to a different point, still not finding/highlighting the message, this can be repeated over and over.

Searching for the same message(s) on the mobile app works as expected, so I doubt it's a protocol limitation (the mobile app is however limited to accessing the first 140 search results).

### Configuration
**Operating system:** Windows 10, x64

**Version of Telegram Desktop:** 1.1.7

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>

I pasted mtp__.txt [here](https://gist.github.com/Robadob/8cd1213af2963b9e2ac0a86db2ecfb2a)

Visible at the top is the search i made 'robert is a troll', which returns two results (one today, and one from 11th Jan 2016).
</details>

**Comment by john-preston** [comment]
@Robadob Thanks for the report. Is it right, that the jump to message works fine for the supergroup messages, but fails for the messages before converting it to supergroup? You can try right clicking and choosing Reply for them and if it can't be done - they're from before it was converted.

**Comment by Robadob** [comment]
Yes you're correct, the affected messages are from before it was a supergroup.

**Comment by john-preston** [comment]
@Robadob Thank you for your report. This will be fixed in the next version.
