### ISSUE TITLE
[Feature Request] Use emoji.codes 

### ISSUE THREAD

**Issue by stormyqq** [telegramdesktop/tdesktop#3515]
I am wondering if you can add https://emoji.codes/ instead of the existing emoji set with at least 48x48px size (on desktop), if it's not possible, can you at least allow us to add our own emojis like stickers? thanks.

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#...

**Comment by stek29** [comment]
emoji.codes is emojione, and they've changed their license -- <s>Webogram</s> TDesktop won't be able to use it.
Also, <s>Webogram</s> TDesktop is part of Telegram "solution", and it has to use same emoji set as other apps.

Oh, and <s>#571 #760</s> #3281 #3336 #2111 and others

(zhukov/webogram#1431 for anyone wondering about <s>these</s>)

**Comment by stormyqq** [comment]
That's bad. telegram is a good software, but not having good emojis and no spelling checker make me not want to use it.

**Comment by yashpalgoyal1304** [comment]
Does anyone know what codes are used by Rocket chat or github or gitlab. They work awesome too.
