### ISSUE TITLE
Please do not replace "--" to "—"

### ISSUE THREAD

**Issue by proea** [telegramdesktop/tdesktop#3518]
### Steps to reproduce
1. send wort -- word

### Expected behaviour
No characters should be replaced

### Actual behaviour
Characters are replaced

### Configuration
**Operating system:** all (for example Linux)

**Version of Telegram Desktop:** latest alpha

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
Please [search for existing](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) issues before creating new ones.
#...

**Comment by proea** [comment]
@auchri 
is duplicate for which one?

**Comment by AndydeCleyre** [comment]
@auchri when marking duplicates, please include a reference to the primary issue.
