### ISSUE TITLE
Instant View Support for RTL Languages

### ISSUE THREAD

**Issue by erfan226** [telegramdesktop/tdesktop#3519]
Hi. Instant view doesn't support RTL websites? how can I make it RTL for Persian?
Just as you can see below, I want to make the instant version which shows content from left to right like the left one, from right to left:
![photo_2017-06-12_16-02-49](https://user-images.githubusercontent.com/17782938/27032142-9e55caee-4f88-11e7-9da1-314fc1520848.jpg)

**Comment by stek29** [comment]
This is not related to TDesktop at all. Please ask in-app support or ping telegram on Twitter.
