### ISSUE TITLE
Theme core problems - "hide all notifications" button paint itself in one color.

### ISSUE THREAD

**Issue by loveengine** [telegramdesktop/tdesktop#3521]
### Steps to reproduce
1. Receive few notifications.
2. Hover your mouse to this button.

### Expected behaviour
Button must color to more gray colors.

### Actual behaviour
Button repainted in one color.

### Configuration
Windows 10 LTSB
Telegram Desktop Alpha 1.1.7
DarkOrange theme
![screenshot_1](https://user-images.githubusercontent.com/29382541/27047599-560ba186-4fb1-11e7-887b-40bb0b07ee40.png)

**Comment by auchri** [comment]
Is this an issue of the theme you use?

**Comment by stek29** [comment]
@auchri seems so, but I can't test it since I'm on macOS. 

@loveengine  please try the latest theme from it's channel -- https://t.me/darkorangetheme/97

**Comment by loveengine** [comment]
Yeah, its issue of this theme, on other themes i didn't see this problem, but creator said that this problem on the client side.

**Comment by stek29** [comment]
@loveengine Then please ask the creator to tell more about this -- why is this considered as issue, and why other themes are able to handle it and his theme is not.

**Comment by jesterro** [comment]
To be honest, I never said abt client's side issue but abt my laziness. Sorry guys. Will fix it asap

**Comment by jesterro** [comment]
@auchri the problem is in that dependence:

**windowActiveTextFg
lightButtonBg**

The theme works great except this small button and I see no way to fix it aside from changing the most part of color scheme. May I request to add a row for any of these parameters, please?

**Comment by john-preston** [comment]
@jesterro Those two are separate keys in the theme.

**Comment by jesterro** [comment]
@john-preston I see it. And both collides on that _Hide All_ button. Any suggestion how to fix it without breaking a color scheme?

**Comment by john-preston** [comment]
@jesterro What do you mean "both collide"? Color of which element would you like to be able to set separately of its current value?

**Comment by jesterro** [comment]
john-preston Sorry for my bad english. I'd like to change Bg or Fg of a  _Hide All_ button when hovering it, without changing _windowActiveTextFg_  and _lightButtonBg_ values.

**Comment by john-preston** [comment]
@jesterro I guess it will be fine if this button will use not only lightButtonBg/lightButtonBgOver for background, but also lightButtonFg/lightButtonFgOver for text? That way it'll be as a simple lightButton, like the ones in a box.

**Comment by jesterro** [comment]
@john-preston it would be great, thank you!
