### ISSUE TITLE
Flowing scrolling in chats don't work, if you don't scroll messages in any chat.

### ISSUE THREAD

**Issue by loveengine** [telegramdesktop/tdesktop#3522]
### Steps to reproduce
1. Open any chat.
2. Don't scroll messages in it.
3. Push button "Down".

### Expected behaviour
Scrolling must be flowing.

### Actual behaviour
It's sharp.

### Configuration
Windows 10 LTSB
Telegram Desktop Alpha 1.1.7

**Comment by john-preston** [comment]
@loveengine If the history is opened at the unread messages and there are a lot of them (more than is loaded already) the scroll won't be animated, because the required messages are not loaded. So it will load the required messages and jump to them instantly.

**Comment by loveengine** [comment]
thank you for answer.

**Comment by twopee** [comment]
Big Thank!
