### ISSUE TITLE
[BUG] Telegram Desktop keeps all sent GIF/MP4 files indefinitely by default without consent, removal is cumbersome

### ISSUE THREAD

**Issue by levicki** [telegramdesktop/tdesktop#3523]
AFAIK it is not disclosed anywhere that Telegram Desktop will save sent MP4/GIF files indefinitely in the cloud without asking for user's consent. The relevant blog post about GIFs [says](https://telegram.org/blog/gif-revolution):

> To make sending your favorite animations easier, we've added a dedicated GIF tab to the sticker panel. Tap on GIFs in chats (long tap on iOS) and ‘Save’ to add them to the panel. Then send them to any chat in one tap.

Nowhere does it explain the behavior of Telegram Desktop client, which appears to be saving them to GIFS panel automatically without asking for user consent.

Deletion of said files is cumbersome at best on both desktop and mobile. There is no way to delete all saved files at once, nor an option to set for how long to keep them (if at all!), not to mention that the little x is too small a target both for mouse aim and touch.

GIF/MP4 files sent by the user should not be, by default, treated differently than other user sent files (txt, zip, doc, ...) because that breaks user's UI functionality (and in this case privacy) expectations. At best, this should be an opt-in, preferrably with a retention period.

Before reporting this I went over the issue #2053 which complains about MP4 files being treated as GIF files. IMO that should be fixed as well -- MP4 files should not be treated the same as GIF files, at least when it comes to adding them automatically to GIFS panel.

### Steps to reproduce
1. Launch Telegram
2. Clear all chat histories
3. Go to Settings -> Manage local storage and clear cache
4. Delete all GIF/MP4 from GIFS panel by clicking the little x
5. Drag and drop (or use Send To Telegram) a GIF/MP4 file to a chat while keeping GIFS panel open
6. Choose "Send as file" when asked how to send

### Expected behaviour
GIF/MP4 file is not added to GIFS panel unless you right-click and choose Save GIF.

### Actual behaviour
GIF/MP4 file is added to GIFS panel automatically upon sending without user consent.

### Configuration
**Operating system:** Windows 8.1 x64

**Version of Telegram Desktop:** 1.1.7

**Used theme**: Default

**Comment by stek29** [comment]
Isn't this done on server side?

**Comment by levicki** [comment]
How would I know, I am just an end-user?

**Comment by tgbugreporting** [comment]
I can only see the last 200 gifs in the panel but if I delete some and refresh then older gifs appear at the bottom.
There seems to be an endless amount of gifs connected to my account but they are not visible anywhere and can only be removed if recently used gifs are removed first.
I could not reach the end by manually deleting a few hundred gifs but I'm sure the history would go back to the time gifs where added to telegram.

There is also a problem with the UI if you have very small gifs the panel puts 5 in one row while the last one in each row gets cut off and doesn't have a visible remove button. (see screenshot)


![snap150](https://user-images.githubusercontent.com/28954329/27124185-7f39cb24-50f0-11e7-802d-a7626138c2d8.png)

**Comment by levicki** [comment]
@tgbugreporting I can confirm the "back to the time GIFs were added to Telegram" part of your statement -- I had all GIF and MP4 files I ever sent using the desktop client in there -- had to manually delete all of them one by one.

@john-preston, could you please take a look?

**Comment by stek29** [comment]
Confirmed to be server side.

**Comment by levicki** [comment]
@stek29 Please clarify, will this be fixed server side "automatically" now that someone is aware of it, or I need to submit another bug report and if so, where?

**Comment by stek29** [comment]
No, I did not report it to anybody on server side because I don't have such connections, I just made sure it is being done by server and client has nothing to do with it.

You'd have to use "Ask a Question" button in settings, or report it on Twitter.

**Comment by levicki** [comment]
@stek29 And what kind of connections do you think I have to server side developers?
I never got any reply to "Ask a Question" so far, and I am not using Twitter.
I understand that this is not Telegram Desktop bug but just closing it without reporting upstream or having the normal channel to report upstream by the original bug reporter is not really helpful.

**Comment by stek29** [comment]
OK, here you go: #issue_hn9bYgmT

**Comment by stek29** [comment]
That "hashtag" is internal issue id, and your report was submitted. Thanks, and sorry if I seemed rude.

**Comment by levicki** [comment]
@stek29 Thank you and don't worry, I am not offended that easily :-)
