### ISSUE TITLE
Stop squeezing everything into one huge binary!

### ISSUE THREAD

**Issue by netsurfer912** [telegramdesktop/tdesktop#353]
guys. your binaries are like big. I don't know how much of this is actually useful code, but I'm sure it's because you've put EVERYTHING in there: Graphics, Fonts, Translations, hell, even the Qt libraries. Don't do that. 

I also just found out that Qt actually supports smooth scrolling with the right configuration, which is awesome ... except Telegram doesn't support it. 

Sorry for being a bit harsh, your work is awesome, but there are just some things bothering me

**Comment by ppparadox** [comment]
I like one big executable. What are the downsides? I'd go even further than that, putting everything in the main folder without creating "$HOME/.TelegramDesktop" for example.

**Comment by netsurfer912** [comment]
sure, why don't we include the operating system itself

**Comment by kireledan** [comment]
Self-containment makes distribution a cinch.
