### ISSUE TITLE
how can i extract the files in D877F783D5D3EF8C to optain the cached data?

### ISSUE THREAD

**Issue by smarty551** [telegramdesktop/tdesktop#3545]

**Comment by john-preston** [comment]
@smarty551 No easy way to do so.

**Comment by smarty551** [comment]
i 'm open for any hard way i tried to force it to load one the old files by name changing but it just override it

**Comment by smarty551** [comment]
also in the source code it's not clear where it compress this files into this form

**Comment by stek29** [comment]
I'd suggest you to study localstorage.cpp if you're open for any hard way :)

**Comment by john-preston** [comment]
@smarty551 By hard way I meant understanding the source code and writing a special software to do that.

Also they're encrypted, so it is possible at all only if you have all those files, including "map" one, which holds the encryption key.

**Comment by smarty551** [comment]
aha aha so that is the key appearing all over the place in the local storage but shouldn't that key change every session mprot starts

**Comment by john-preston** [comment]
@smarty551 That key isn't related to mtproto.

**Comment by ilbeygi** [comment]
can't open with telegram ????
no way ???

**Comment by sasha-x** [comment]
+1 interested too
