### ISSUE TITLE
Main window doesn't show up

### ISSUE THREAD

**Issue by Scvairy** [telegramdesktop/tdesktop#3551]
### Steps to reproduce
1. Start Telegram
2. Try to open up window

### Expected behaviour
Window show up

### Actual behaviour
Window just takes focus, but doesn't appear

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.1.7

**Used theme**: idk

[log_20_30.txt](https://github.com/telegramdesktop/tdesktop/files/1078160/log_20_30.txt)

**Comment by Scvairy** [comment]
Actually, I can enter passcode and app will get in, but there won't be it's window. :/

**Comment by stek29** [comment]
Does pressing <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>↑</kbd> help (maybe a couple of times)?
Also, I remember there was a similar issue, but I can't find it now...

**Comment by gBopHuk** [comment]
Confirm on windows 7. 
I tryed reinstall telegram destop but it didn't help.

**Comment by Scvairy** [comment]
I removed app settings in it's folder (actually, renamed folder with settings), and then it showed up with login page.

**Comment by john-preston** [comment]
@Scvairy What version are you using there? Can you try the old settings folder with version 1.1.13 (from https://desktop.telegram.org/changelog#alpha-version): launch it, reproduce the problem (not seeing the main window), quit the app (from tray) and get the log.txt

**Comment by Scvairy** [comment]
Sure:

[log.txt](https://github.com/telegramdesktop/tdesktop/files/1154155/log.txt)

**Comment by john-preston** [comment]
@Scvairy it doesn't have what I wanted :(

May I ask you to do the following:
- go to the application folder and open "tdata" folder there
- create a file "withdebug" (without extension) in this "tdata" folder
- run that instance of Telegram Desktop (with the problem)
- close the app from task panel (the window is not visible, as I understood)
- in the "DebugLogs" folder from the application folder should be three files with prefixes "log", "mtp" and "tcp"
- copy the one with "log" prefix here

**Comment by Scvairy** [comment]
[log_14_45.txt](https://github.com/telegramdesktop/tdesktop/files/1155396/log_14_45.txt)

**Comment by john-preston** [comment]
@Scvairy That really helps, thanks! Something terribly wrong with the saved window position, it states "Window Pos: Read from storage -32000, -32000, 380, 501" %) I'll investigate that and I hope it will be fixed in the next version.
