### ISSUE TITLE
Can't close full screen image view

### ISSUE THREAD

**Issue by axd** [telegramdesktop/tdesktop#3553]
### Steps to reproduce
1. Open any image
2. Change window's focus (Alt+Tab)
3. Try to close full screen view, you can't.

### Expected behaviour
When you press Alt+Tab it would change you to the other window and if you return you could exit full screen.

### Actual behaviour
When you try to switch to another it remains full screen image view, if you try to close full screen view you can't. You have to kill Telegram process to do so.

### Configuration
**Operating system:**
Ubuntu 16.04

**Version of Telegram Desktop:**
1.1.7

**Used theme**:
Default

**Comment by stek29** [comment]
#2774 ?

**Comment by axd** [comment]
@stek29 Similar but different.

**Comment by Aokromes** [comment]
#3419 ?

**Comment by axd** [comment]
@Aokromes this is very similar what it happens to me, the difference is that his mouse pointer works when click in other windows/buttons, mine's doesn't, I don't have the mouse pointer view. However I'm able to use keyboard shortcuts in background, the Telegram image fullscreen view is overall, so the only way to kill the process is to switch a full console mode (ctrl + alt +f1) and kill it there.
