### ISSUE TITLE
Lines on adjacent screens (displays) in fullscreen mode

### ISSUE THREAD

**Issue by mFoxRU** [telegramdesktop/tdesktop#3557]
### Steps to reproduce
1. Run telegram on a multi-screen setup
2. Make telegram window fullscreen

### Expected behaviour
Telegram should be shown in fullscreen only on one screen
### Actual behaviour
Telegram is shown on one screen and white lines are shown on adjacent screens. Those lines are part of telegram window and will overlay any underlying window. They are also click transparent, so any click will be received by the underlying window. No other application shows such a behavior.

Examples (3 displays in a line):
On the middle screen
![image](https://user-images.githubusercontent.com/5925970/27240626-332ac7a2-52de-11e7-97fa-d5beb36a1e0a.png)
On the right screen
![image](https://user-images.githubusercontent.com/5925970/27240700-7e1811a2-52de-11e7-999d-c5bff2692ac3.png)

### Configuration
**Operating system:**
Windows 7 x64
**Version of Telegram Desktop:**
1.1.7
**Used theme**:
Default or any custom theme
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Double-A-92** [comment]
This bug was also present on Win10. Since the last "Spring Creators Update" it got even worse.
If you got multiple monitors with different resolutions full screen is now completely buggy. 

This is how it looks:
![image](https://user-images.githubusercontent.com/2192982/39950772-23266e5c-5584-11e8-827c-aa57fe6fb599.png)

**Comment by Aokromes** [comment]
this bug is fixed on 1.9.8 no?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
