### ISSUE TITLE
How to keep own changes after any update?!

### ISSUE THREAD

**Issue by AliRezaBeitari** [telegramdesktop/tdesktop#3558]
As I said in the title, when Telegram updates how can I keep my changes for the new version?!

**Comment by stek29** [comment]
`-DTDESKTOP_DISABLE_AUTOUPDATE` if on Linux and Windows
`bool gAutoUpdate = false;` instead of `true` [in settings.cpp](https://github.com/telegramdesktop/tdesktop/blob/c1aa1c5a0f26b29fce1307ba455f9887e7c1c1ec/Telegram/SourceFiles/settings.cpp#L54) on any OS.

**Comment by stek29** [comment]
Update: TDESKTOP_DISABLE_AUTOUPDATE works on macOS too, don't know since when.
