### ISSUE TITLE
Why are videos round?

### ISSUE THREAD

**Issue by JarrettBillingsley** [telegramdesktop/tdesktop#3563]
### Steps to reproduce
1. Take a video.
2. It's round.

### Expected behaviour
It should not be round.

### Actual behaviour
It's round.

### Configuration
**Operating system:** any

**Version of Telegram Desktop:** all the ones that support video

**Used theme**: n/a

This is the silliest thing. WHY ON EARTH ARE THEY ROUND

**Comment by auchri** [comment]
Only video messages are round: https://telegram.org/blog/video-messages-and-telescope

**Comment by JarrettBillingsley** [comment]
Okay, why are VIDEO messages round?

Thanks for the very quick and dismissive reply!

**Comment by auchri** [comment]
Because Telegram Designers said that they should be round ¯\_(ツ)_/¯

**Comment by JarrettBillingsley** [comment]
See, this is what I don't get. Where the hell are we supposed to file issues/feedback on telegram as a whole?

**Comment by auchri** [comment]
@JarrettBillingsley https://twitter.com/telegram or in app support-

**Comment by JarrettBillingsley** [comment]
I've tweeted at them several times with absolutely no response. Brick walls are great.
