### ISSUE TITLE
Fails to build with Qt 5.9: cannot find -lQt5PlatformSupport

### ISSUE THREAD

**Issue by mitya57** [telegramdesktop/tdesktop#3564]
In Qt 5.9, the Qt5PlatformSupport static library was split into a set of smaller libraries, such as Qt5AccessibilitySupport, Qt5FontDatabaseSupport, Qt5ThemeSupport, etc. (see qt/qtbase@ea913750b8793e1e).

But telegram-desktop still [uses](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/gyp/qt.gypi#L37) Qt5PlatformSupport, which results in a build failure with Qt 5.9.0:

    /usr/bin/ld: cannot find -lQt5PlatformSupport

Full build log can be seen [here](https://launchpadlibrarian.net/324641909/buildlog_ubuntu-artful-amd64.telegram-desktop_1.1.0-1build1_BUILDING.txt.gz).

So you need to check what components of former Qt5PlatformSupport were actually used, and link explicitly against them.

**Comment by auchri** [comment]
As you can see in the build instructions, tdesktop still uses qt 5.6 for compatibility to windows XP.

https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md

**Comment by stek29** [comment]
@auchri And not just XP :)

**Comment by mitya57** [comment]
What is wrong with supporting both Qt 5.6 and Qt 5.9? 5.9 is also a long-term support release, and when you no longer need to support a 15 year old OS, you will want to migrate anyway.

Anyway, the `-lQt5PlatformSupport` is not used at all, so I will be filing a pull request to remove it and fix another minor compilation issue.

**Comment by stek29** [comment]
@mitya57 
> the -lQt5PlatformSupport is not used at all

Well, maybe it's not used directly, but qcocoa and qwindows are using it.
