### ISSUE TITLE
"Apply language settings" doesn't work - Kubuntu

### ISSUE THREAD

**Issue by trufanov-nok** [telegramdesktop/tdesktop#3569]
### Steps to reproduce
1. Download client for desktop
2. Go to Settings, type "loading" or try shift+alt+click on "change language" link as described in documentation.

### Expected behaviour
File selection menu should appear

### Actual behaviour
nothing happened. As a result I can't apply russian language.

### Configuration
Kubuntu 17.04, KDE Plasma 5.9.5, Qt 5.7.1, linux 4.10.0-22-generic x86_64

**Version of Telegram Desktop:**
1.1.7
**Used theme**:
default

**Comment by john-preston** [comment]
@trufanov-nok Try typing "loadlang" in Settings.

**Comment by trufanov-nok** [comment]
@john-preston as I said typing does nothing. Keyword for debug enabling/disabling works, but "loading" not. So app receives keyboard input but not able to open system fileopen dialog for some reason.

**Comment by john-preston** [comment]
@trufanov-nok Not "loading", but "loadlang". Does the sending of images from files work in chats?

**Comment by trufanov-nok** [comment]
@john-preston Indeed, it works. I'd misread the keyword.
