### ISSUE TITLE
Inline code formatting is not applied on image captions

### ISSUE THREAD

**Issue by SebinNyshkim** [telegramdesktop/tdesktop#3570]
### Steps to reproduce
Send an image and add a caption with inline code formatting

### Expected behaviour
Inline code snippets in `monotype font`

### Actual behaviour
![tg-desktop-code-caption](https://user-images.githubusercontent.com/13051568/27389051-991bc080-569d-11e7-8e79-23609521d9a1.png)

No code formatting applied. Delimiters visible in caption text.

### Configuration
**Operating system:** macOS 10.12.5

**Version of Telegram Desktop:** 1.1.7

**Used theme**: Default

-----

Is there a concrete reason why code formatting via backticks ` doesn't work inside image captions but any other regular message?

**Comment by john-preston** [comment]
@SebinNyshkim Sorry, they won't work for now, because caption text doesn't have server side support for them like the message text has. Maybe this will be added some day in the future.

**Comment by auchri** [comment]
@SebinNyshkim The months in moment.js starts with 0, so june is 5 + 1 😉 

January = 0
February = 1
...

**Comment by SebinNyshkim** [comment]
@auchri I know that, I have to use it in a project, doesn't make it less awkward to use when everything starts at 1 but months are 0 based. But that isn't the point of this thread 😉

It was just for illustration.
