### ISSUE TITLE
If Bing Maps isn't installed, open shared location in browser

### ISSUE THREAD

**Issue by theel0ja** [telegramdesktop/tdesktop#3571]
### Steps to reproduce
1. Use Windows 10 and don't have Bing Maps ("Maps" in menu) installed
2. Click a shared location

### Expected behaviour
If no Bing Maps installed, open Google Maps in default browser (like on Linux)

### Actual behaviour
![image](https://user-images.githubusercontent.com/5832930/27453845-7591d060-57a0-11e7-8329-f8da0e872887.png)

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.1.7

**Used theme**: Default

**Comment by stek29** [comment]
#1612

**Comment by khabraken** [comment]
This should be in conjunction with a change in protocol to "geo" (rather than the nonstandard "bingmaps"), (see my comments in #1612 ).

Looking at the code, I would have though that if no handler was registered, then it would revert to the gmaps URL behaviour, but the screenshot above seems to indicate that is not the case.

**Comment by tomcpc** [comment]
This is very annoying...

Until they fix this, one workaround would be to create a simple Windows app to redirect "bingmaps" to the browser. I don't know how to create one though.

**Comment by KoalaBear84** [comment]
Yes. I did a quick search to see if there are alternative apps for Maps on Windows which work or redirect to Google, unfortunately didn't find any.

But.. I did find a workaround I saw in another ticket on Github. Right click op it, Copy Link and use it in your browser. It is very strange for me that Windows Maps application looks like taking control over a Google Maps link, but maybe it is Telegram Desktops fault.

**Comment by KoalaBear84** [comment]
If Bings/Windows Maps is installed, which it is, I get this... Ocean, I'm not Spongebob. It should be possible to have something useful as Bing/Windows Maps just doesn't work at all. Tested on multiple devices. The whole world is an ocean..

![image](https://user-images.githubusercontent.com/5886900/41280143-81edaf8c-6e2e-11e8-8c9d-baa9b7c5e2e9.png)

**Comment by KoalaBear84** [comment]
Hmm, I see geo: protocol is not really supported. Telegram Desktop should support choosing your own 'destination'. With at least the following 3 options:
1. Google Maps (browser)
2. OpenStreetMap (browser)
3. Default Windows app / Bing/Windows Maps

Clicking the links opens a blank white page on Chrome, and in IE and Edge it tries to open it through some sort of default app, but there is none, and also nothing in the Windows Store... So changing to geo looks even worse, no support.
https://en.wikipedia.org/wiki/Geo_URI_scheme

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by khabraken** [comment]
I can confirm that the steps described by the OP still result in the "You'll need a new app to open this bingmaps link" message (when Maps is not installed).

Yes there is a context menu with 'Copy Link' (which is a gmaps link) which can be used as a workaround, but it would still be nice if simply clicking did something sensible.
A bingmaps:// link is of dubious use even if it is installed (last I had it installed, it simply wouldnt load any actual maps), but I would be happy if it could just check if a bingmaps handler is actually installed, before using that as the click URL.

**Comment by KoalaBear84** [comment]
Hey there! As far as I remember it is still not fixed.

**Comment by bwims** [comment]
+1  I would also like to be able to click through to my preferred map, but at the very least Google Maps, because Windows Maps stink.

**Comment by internetcoffeephone** [comment]
Bug still exists. Similarly, if the windows store is not installed, you get the following dialog box.

![1](https://user-images.githubusercontent.com/5096835/109960937-a60c9a00-7ce9-11eb-90d9-3b1100b4a873.png)
![2](https://user-images.githubusercontent.com/5096835/109960940-a6a53080-7ce9-11eb-8a6a-d1bb20d8f510.png)

The checkbox does nothing, and the OK button is permanently grayed out.

**Comment by compnut21** [comment]
Ran into this today, also lacking windows store on LTSC. Why can't this just open like normal as a link if it's not installed? Adding this to the list of reasons I'll be moving back to win7 soon anyways.

**Comment by Vlandmist** [comment]
still broken?

**Comment by compnut21** [comment]
> still broken?

Yup. It doesn't work on windows 10 at all if you don't have Windows store installed.
