### ISSUE TITLE
Imgur GIFs can't be played inside the application if the .gif or .gifv is linked

### ISSUE THREAD

**Issue by DarthJahus** [telegramdesktop/tdesktop#3572]
If we share a link to a GIF on imgur, TDesktop offers a preview for the `.gifv`, and shows the image as a clickable link to Imgur.

To share a GIF, we have to get the `.mp4` link, or download and upload it to Telegram.

Imgur gives the `.mp4` link in `og:video` metadata.

**Comment by john-preston** [comment]
@DarthJahus They work at least for some urls, see "http://imgur.com/gallery/OTbmOGR" Maybe you can share the problematic url?

**Comment by DarthJahus** [comment]
Thanks for the fast answer.
Here is one that doesn't play directly: http://i.imgur.com/0NT7pVY
Looks like this:
![image](https://user-images.githubusercontent.com/7353366/27487193-ecd6c5b0-582a-11e7-9959-d9d045e8ab16.png)

While the one you have shared looks like this:
![image](https://user-images.githubusercontent.com/7353366/27487170-d9357876-582a-11e7-8e01-bdd41cbee865.png)

**Comment by stek29** [comment]
Server isn't parsing them properly
