### ISSUE TITLE
CJK font fallback issue

### ISSUE THREAD

**Issue by iamCristYe** [telegramdesktop/tdesktop#3575]
### Steps to reproduce
Using Telegram with CJK texts

### Expected behaviour
Tell us what should happen
Chinese as Chinese and Japanese as Japanese

### Actual behaviour
Tell us what happens instead
Ugly text with mixed Chinese fonts and Japanese fonts

### Configuration
**Operating system:**
Windows 10 1703
**Version of Telegram Desktop:**
latest
**Used theme**:
default

I tried to use the store version of Telegram Desktop, but the CJK behaviours really makes me unable to do that. I know the issue has been put up several times #2900 #2643 #2239 #589 but it has been a long time and I can see no improvements.
I just want to say Telegram is the best IM I've ever used expect this issue, which is a **crucial** one that affects **all Chinese, Japnese and Korean users** and **it is not so difficult to fix**. A potential fix can be found [here](https://github.com/ysc3839/TGFont). Or just give us the option to customize the font as stated in #90.

Thanks!

</details>

**Comment by ShadowJonathan** [comment]
This is really apparent when looking between the android client and the windows desktop client.

There is a good japanese glyph font, though, and it's installed by default into windows 10 (when japanese supplemental fonts are installed?), it's called Meiryo.

[Wiki page](https://en.wikipedia.org/wiki/Meiryo), [Microsoft docs](https://docs.microsoft.com/en-us/typography/font-list/meiryo)

**Comment by john-preston** [comment]
@ShadowJonathan I do not manage the fonts (and fallbacks) directly :( Qt does that on its own.

**Comment by ShadowJonathan** [comment]
Is there no way to configure the fonts that Qt can or does use? If not, then that's a problem for more projects than just this one.

**Comment by john-preston** [comment]
@ShadowJonathan Perhaps there is and I don't know about it. Or perhaps they improve things in the newer Qt versions, but I'm not ready to upgrade, because they stop supporting some systems that tdesktop currently runs on.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/589
