### ISSUE TITLE
Question: pasting image not showing inline

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#3585]
Not a bug, but I don't know where to ask:

When I'm pasting an image, I got the upload box and my image shows inline.
When my gf is pasting an image, it's showing as something to download rather than inline. 

What I'm missing here?

**Comment by john-preston** [comment]
@Geobert There is a checkbox "Compress image" and it manages that behaviour. You send it compressed, like a photo, and she sends it uncompressed, like a file.

**Comment by Geobert** [comment]
That's it! Thanks!

**Comment by Geobert** [comment]
Hi, sometime I don't get the checkbox and the pic get sent as a file. Why?
