### ISSUE TITLE
Unicode 10 Bitcoin sign etc

### ISSUE THREAD

**Issue by wowpetr** [telegramdesktop/tdesktop#3589]
Just support the subj
http://unicode.org/versions/Unicode10.0.0/

**Comment by auchri** [comment]
Emojis will be updaten when the other apps updates them too.

**Comment by wowpetr** [comment]
What about a Bitcoin sign support?

**Comment by stek29** [comment]
@wowpetr Telegram uses opensans font, so you might want to file an issue on it.
Good luck with that, and you can remind them about #537 and other Unicode issues.

**Comment by auchri** [comment]
@stek29 https://github.com/google/fonts/issues/399 btw.

**Comment by fitojb** [comment]
For the record, {Open|Droid} Sans are superseded by the Noto fonts. Noto does include a bitcoin sign.
