### ISSUE TITLE
Can make notification only for desktop version?

### ISSUE THREAD

**Issue by JungPruna** [telegramdesktop/tdesktop#359]
Before start, I apologize for my bad english skill.

I unchecked Notification for a chat group in my iPhone, because it's ringing so many times when my friends chat with their desktops.
However, Notification option in desktop version telegram is unchecked too.
I wanted the group chat still notified in desktop, so I checked in my desktop version.
Then, now my iPhone is ringing when I am not control the telegram window!

Please make it can be checked individually.

**Comment by auchri** [comment]
No, the notification settings are synced to each client
