### ISSUE TITLE
Insecure permission of $HOME/.TelegramDesktop directory

### ISSUE THREAD

**Issue by xuzhao9** [telegramdesktop/tdesktop#3591]
### Steps to reproduce
1.  Install tdesktop and run it
2.  Check the permission of ~/.TelegramDesktop directory
3.  The permission is 755
drwxr-xr-x .TelegramDesktop/

### Expected behavior
The permission should be 700 to avoid other users' read and execute.

### Actual behavior
Other users can view the content of this directory

### Configuration
openSUSE Tumbleweed
User: 1.0.24 Alpha

For more, take a look at:
https://blogs.gentoo.org/ago/2017/05/01/telegram-desktop-insecure-permission-of-home-telegramdesktop-directory/
and
https://bugzilla.novell.com/show_bug.cgi?id=1037007

**Comment by auchri** [comment]
Duplicate #2666
