### ISSUE TITLE
[Bug] Draft blocks ability to join supergroup

### ISSUE THREAD

**Issue by andreyorst** [telegramdesktop/tdesktop#3592]
### Steps to reproduce
1. Open or join a supergroup
2. Type something in text field
3. Switch to another chat to activate draft synchronisation between devices (check it on your phone)
4. Go back to group and leave
5. Open group via link or `@groupname`
6. Press Enter (it's necessary)

Now the **Join Button** isn't working neither on PC, nor on my Android phone. And it's equals for other supergroups either. For example i can't join any chat from combot's page.

Exiting Telegram Desktop doesn't help. I can't find a workaround for it by now.
![image](https://user-images.githubusercontent.com/19470159/27645173-232848b2-5c2e-11e7-8b0c-ccc84256be7f.png)
_animation is working. The only one thing is working actually is animation._
### Expected behaviour
Join button should work

### Actual behaviour
Pressing **Join** invokes animation, but nothing happens.

### Configuration
**Operating system:**
Windows 7
**Version of Telegram Desktop:**
1.1.7
**Used theme**:
Breeze v3

**Comment by stek29** [comment]
Hm, I can't reproduce it.
Can you try it in web version? (web.telegram.org)
