### ISSUE TITLE
telegram project building problem

### ISSUE THREAD

**Issue by lufei2017** [telegramdesktop/tdesktop#3596]
Hello, I was wrong when building telegram. Debugging for a long time, did not find the reason
LNK2038 detected "RuntimeLibrary" does not match the value: "MDd_DynamicDebug" is not matching value "MTd_StaticDebug" (codegen_style.basic_tokenized_file.obj) Telegram C:\\workspace\\TBuild\\tdesktop\\Telegram\\Qt5Cored.lib (qeventdispatcher_win.obj)

**Comment by john-preston** [comment]
@lufei2017 Looks like Qt was built with wrong runtime library. Did you apply the patch?

**Comment by mabbasi90** [comment]
same problem here.... any solution?
