### ISSUE TITLE
https://tdesktop.com/ server for downloading updates is very slow when accessing from Belarus

### ISSUE THREAD

**Issue by proea** [telegramdesktop/tdesktop#3597]
https://tdesktop.com/ server for downloading updates is very slow when accessing from Belarus

**Comment by proea** [comment]
@john-preston thanks for the answer. I think this is not the right approach. Speed is very very small

**Comment by auchri** [comment]
@john-preston Yes, the download speed is really bad.

**Comment by tgbugreporting** [comment]
Why does it not DL the require files form telegram cloud? It would be way faster.

If it runs in the background it should not be fast that's true. But usually I request the update manually when I know there is a new version out. I watch it drop in at like 100-150KB/s that's just not what you expect from Telegram. I remember it was blazing fast in the past.

**Comment by auchri** [comment]
@tgbugreporting It should be fast, even in the background imho. 

Imagine you turn on your device just for 5 minutes. But the download is so slow that it takes more than 5 minutes. Tdesktop has to redownload everything at the next time you turn on your device.

**Comment by john-preston** [comment]
@tgbugreporting Then the amount of downloads raised a lot, I guess :) I'll try to discuss that with admins, but I'm afraid they think it's fine :D

**Comment by john-preston** [comment]
@auchri No, it won't start from beginning :P

**Comment by stek29** [comment]
@john-preston One more reason -- sometimes (pretty often) update check starts to fail for me, and I have to restart the app and check manually to get it working.
Because of slow speed I have to do it 3-4 times per update. This is really frustratating, but not so frustrating as watching sloooooow download.

**Comment by tgbugreporting** [comment]
In-app DL is very very slow again I basically have to DL via web browser to update now
but the official link for the portable alpha version > ahttps://tdesktop.com/win/portable?alpha=1 loads an old version
current version can be found by editing the link to https://tdesktop.com/win/portable?alpha
no sure if someone here can fix this but this causes useless traffic

**Comment by Aokromes** [comment]
IMHO no telegram desktop issue instead telegram servers.
