### ISSUE TITLE
The background of the chat window is reset when the Night mode is turned on and off

### ISSUE THREAD

**Issue by proea** [telegramdesktop/tdesktop#3598]
### Steps to reproduce
1. turn on Night mode
2. turn off Night mode

### Expected behaviour
The background remains unchanged

### Actual behaviour
The background was replaced by flowers

### Configuration
**Version of Telegram Desktop:**
1.1.8 alpha

p.s. I also want to note that it is desirable to replace the standard picture, for example, with the first in the list of built-in image galary

**Comment by john-preston** [comment]
@proea I don't like to save the background image only for night mode off or on (separately), because those are just themes.

Perhaps when you toggle night mode while you have non-default background image chosen it will just be left the same without changing. Do you think that'd be ok?

**Comment by proea** [comment]
It is important that when turning off the night mode, my background is returned as was before the enabling of night mode

**Comment by john-preston** [comment]
@proea I can implement that it won't change at all when you switch to the night mode. If you have your custom background and you enable night mode you'll still have it even in the night mode. Is that fine?

**Comment by proea** [comment]
@john-preston It is better to replace with a dark background, as now, but return it back, as it was before the changes? Is this possible?

**Comment by john-preston** [comment]
@proea That's not that easy. Also after that it would be expected for custom background in the night mode to be saved when you switch it off and back on as well. Which makes it even more "not easy", because night mode is just a custom theme and doesn't have such "remember my background please" option. I'll think about it.

**Comment by proea** [comment]
@john-preston I understood, Thanks.

**Comment by stek29** [comment]
@john-preston it would be nice to use "night mode" as a way to have two different themes installed. 
What I mean is:
- User installs custom theme #1
- He enables night mode (TDesktop's built in night mode theme gets activated)
- He installs custom theme #2
- Now when he disables night mode he gets theme #1, and when he enables it he gets theme `#2`

**Comment by nyuszika7h** [comment]
Or maybe a theme listing could be added like on Android, with "Default" and "Night", also listing any custom themes the user has installed in the past.

**Comment by john-preston** [comment]
@stek29 Interesting idea.

**Comment by stek29** [comment]
0798a0148a5e2f6775b1e05565f257fe6793d484

**Comment by john-preston** [comment]
@nick722 Just go to Settings and press Use default color theme.
