### ISSUE TITLE
Uncorrect workmode 

### ISSUE THREAD

**Issue by loveengine** [telegramdesktop/tdesktop#3601]
### Steps to reproduce
1. Pickrelated

### Expected behaviour
Messages on the icon displayes all dialogs, when workmode is on.

### Actual behaviour
The icon should only show notifications with sound.

### Configuration
Win10 LTSB
TD Alpha 1.1.9
![image](https://user-images.githubusercontent.com/29382541/27745145-eb2f416a-5dca-11e7-8405-7b7ab4ccb4c7.png)

**Comment by john-preston** [comment]
@loveengine You have a checkbox in Settings "Include muted chats in unread counter", try disabling it. Or did I understand you wrong?

**Comment by loveengine** [comment]
Yeah, thank you.
