### ISSUE TITLE
App-Crash - udev Event

### ISSUE THREAD

**Issue by pscheich** [telegramdesktop/tdesktop#3602]
Hey,
there is a Bug with udev events (maybe).

System: Archlinux 64bit
Telegramm-Desktop from AUR v1.1.9
I'm using this udev rules to disable the touchpad if a mouse is connected. 
https://wiki.archlinux.org/index.php/Touchpad_Synaptics#Basic_desktop

If telegram-desktop is running and I remove the usb-mouse or connect it, telegram crashes with this message in terminal:

> The program 'telegram-desktop' received an X Window System error.
> This probably reflects a bug in the program.
> The error was 'BadAccess (attempt to access private resource denied)'.
>   (Details: serial 2036 error_code 10 request_code 131 minor_code 46)
>   (Note to programmers: normally, X errors are reported asynchronously;
>    that is, you will receive the error a while after causing it.
>    To debug your program, run it with the --sync command line
>    option to change this behavior. You can then get a meaningful
>    backtrace from your debugger if you break on the gdk_x_error() function.)

Greets

**Comment by john-preston** [comment]
@pscheich Does the version from https://desktop.telegram.org crash as well?

**Comment by pscheich** [comment]
Yes.

**Comment by nuqz** [comment]
Hello, I have the same error as above:

```
The program 'Telegram' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 1800 error_code 10 request_code 131 minor_code 46)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

It happens only when I connect/disconnect any USB devices into PC.
My environment is:
* Debian Stretch with 4.9.0-3-amd64 kernel
* Telegram 1.1.23
* Mate as DE

@pscheich can you show me your solution, please?

**Comment by stek29** [comment]
#3287
