### ISSUE TITLE
Pre-built custom language pack is not visible in language selector

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#3603]
### Steps to reproduce
1. Build Telegram Desktop with custom language pack.
2. 
3. 

### Expected behaviour
It should be visible in Settings -> Language.

On previous Telegram versions (include 1.1.7) everything worked fine, but on 1.1.8a and 1.1.9 is broken.

### Actual behaviour
Bundled language pack is not shown.

### Configuration
**Operating system:** Fedora 25-27

**Version of Telegram Desktop:** 1.1.9

**Used theme**: n/a

Full patch contents (rebased to 1.1.9 tag):
```diff
--- a/Telegram/Resources/langs/list
+++ b/Telegram/Resources/langs/list
@@ -1 +1 @@
-de,es,it,ko,nl,pt_BR
+de,es,it,ko,nl,pt_BR,ru

--- a/Telegram/Resources/qrc/telegram.qrc
+++ b/Telegram/Resources/qrc/telegram.qrc
@@ -28,5 +28,6 @@
     <file alias="lang_nl.strings">../langs/lang_nl.strings</file>
     <file alias="lang_pt_BR.strings">../langs/lang_pt_BR.strings</file>
     <file alias="lang_ko.strings">../langs/lang_ko.strings</file>
+    <file alias="lang_ru.strings">../langs/lang_ru.strings</file>
   </qresource>
 </RCC>

--- a/Telegram/SourceFiles/lang/lang_instance.h
+++ b/Telegram/SourceFiles/lang/lang_instance.h
@@ -37,6 +37,7 @@ constexpr str_const kLegacyLanguages[] = {
 	"nl",
 	"pt_BR",
 	"ko",
+	"ru",
 };
 
 inline QString ConvertLegacyLanguageId(const QString &languageId) {
--
```

What else I need to patch to add custom language pack into my build?

**Comment by john-preston** [comment]
@xvitaly Language list is now taken from the server, this will allow to have a lot more languages supported later.
