### ISSUE TITLE
TG won't open links if Chrome is the default browser (windows 10)

### ISSUE THREAD

**Issue by nyoru** [telegramdesktop/tdesktop#3604]
Hi everyone!

I have Windows 10 and Telegram Desktop installed, and I cannot open links from any chat if my default browser is Chrome. When I change it on the Windows Settings to Firefox or any other browser, there is no problem at all. 
I'm completely clueless and don't know what could be the source of the problem. I would say the problem is with Windows 10 (it has been buggy since I installed it) but who knows. Anyone have any idea what could be going on or how should I proceed? 

Thanks!

**Comment by auchri** [comment]
@nyoru Works for me.

**Comment by auchri** [comment]
Does it from any other app?

**Comment by nyoru** [comment]
Works fine through the phone app and also through Telegram Web in Chrome itself, the issue is only with Telegram Desktop :(

**Comment by auchri** [comment]
I meant ... does Chrome open links from any other application? e.g. a link in a pdf file

**Comment by nyoru** [comment]
Oh, I hadn't check that out and yep, links didn't work from Acrobat as well, so I just reinstalled Chrome and everything works again :') I should've done that before... Thanks man 👍
