### ISSUE TITLE
Problems with scrolling effect.

### ISSUE THREAD

**Issue by loveengine** [telegramdesktop/tdesktop#3606]
### Steps to reproduce
1. Open any chat.
2. Scroll in them.
3. Push "scroll down" button.

### Expected behaviour
Scrolling must be smooth.

### Actual behaviour
Its scroll down without smooth effect.

### Configuration
Win10 LTSB
TD Alpha 1.1.9
Standart Theme

**Comment by john-preston** [comment]
@loveengine It is smooth if you're not too far from the bottom, otherwise it completely reloads the history.

**Comment by loveengine** [comment]
thank you for answer

**Comment by loveengine** [comment]
Wait. If I scroll up and push on this button, it has smooth scrolling, even if i'm too far from the end.

**Comment by auchri** [comment]
@loveengine Because the history got already loaded.

**Comment by loveengine** [comment]
And when you again scroll down the history clears?

**Comment by john-preston** [comment]
@loveengine "Too far" means "not loaded yet". If you scroll from bottom — it is all loaded. But if you have 10 000 unread messages or you jump from search to a 10 000 message from bottom — it loads only a small part of history, not all down till the bottom.

**Comment by loveengine** [comment]
But if i open any chat and scroll up from unread position it anyway scrolls with smooth animation.
And i see part of all history.
