### ISSUE TITLE
Incorrect display of buttons for Russian localization.

### ISSUE THREAD

**Issue by loveengine** [telegramdesktop/tdesktop#3608]
### Steps to reproduce
1. Pickrelated.

### Expected behaviour
F.e. button "Back" should transform into an arrow without words.

### Actual behaviour
The text of one button is superimposed on the text of the second.

### Configuration
Win10 LTSB 1368*768
TD Alpha 1.1.9
![image](https://user-images.githubusercontent.com/29382541/27748800-6a79723e-5dd9-11e7-821c-505c77c338ff.png)

**Comment by auchri** [comment]
There is no official russian translation.
