### ISSUE TITLE
Add Encrypted Message feature

### ISSUE THREAD

**Issue by jaimemnds** [telegramdesktop/tdesktop#3609]
Let the user create an encrypted message.

Scenario:
Every user has its own "decryption password".
I right-click the text input field and select "Encrypted Message";
The input field changes to a mode where there are two input fields, the upper one allows you to enter the message that will be displayed at first, the lower field is for you to enter the hidden message;
The user that receives a message can right-click the message and try to decrypt it using his "decryption password". If the message was decrypted, the hidden one will be shown; otherwise nothing will happen.

This sounds very useful to me. What do you guys think?

**Comment by stek29** [comment]
API issue.
Also, secret chats are way better imo.

**Comment by codemeow** [comment]
> Also, secret chats are way better imo.

Maybe. Except that there's no secret chats on linux desktop/web.

**Comment by auchri** [comment]
> Maybe. Except that there's no secret chats on linux desktop/web.

 #871
