### ISSUE TITLE
Hashtag search is hidden in single column layout

### ISSUE THREAD

**Issue by ADTC** [telegramdesktop/tdesktop#361]
If I click on a hashtag in the double-column layout (in a message in the right column), the hashtag appears in the search box of the left column, and the search results appear below it.

But in single-column layout, if I click on a hashtag in a message, nothing *appears to happen*. But when I click on the Back link at the top, I find that the search had indeed happened in the Chats list view, but was hidden from view.

In single-column layout, clicking on a hashtag should *not only* search for it, **but also** switch to the search results (Chats view) automatically.

**Comment by telegramdesktop** [comment]
Fixed in 0.7.13.
