### ISSUE TITLE
Feature Request : emoji , stickers panel swipe

### ISSUE THREAD

**Issue by darkworks** [telegramdesktop/tdesktop#3616]
i have request that kindly add arrows to emoji,stickers panel to hide it and view to side 

like :: https://image.prntscr.com/image/yN5SUe-lTOqDxeEGS-1_Hg.png

thanks

**Comment by stek29** [comment]
Do you know you can hide that panel by clicking on smiling face next to mic icon?

**Comment by darkworks** [comment]
thanks :) i was not aware of it :)  however one visible arrow on top will be also good if added it will make it beautiful and visible to everyone , that it slide back and forth with arrows .

**Comment by stek29** [comment]
Is #3399 ok?

**Comment by darkworks** [comment]
thanks :)
