### ISSUE TITLE
Support for 8 (or even any other number) public usernames revocation

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#3617]
### Steps to reproduce
1. Create yet another supergroup/channel
2. Try to setup a public username
3. Try to revoke the oldest username

### Expected behaviour
You should see a full list (currently 8 elements)

### Actual behaviour
You can only see the last 5 entries, the list isn't even scrollable.
![image](https://user-images.githubusercontent.com/2780044/27773838-780eb4aa-5f8b-11e7-9577-4c3adfd1ba8e.png)

### Configuration
**Operating system:** Windows 10 LTSB
**Version of Telegram Desktop:** 1.1.9 alpha

**Comment by john-preston** [comment]
@MasterGroosha What about other apps? (iOS / Android)

**Comment by MasterGroosha** [comment]
Android already supports it by having scrollable list (probably it's not hardcoded to 5 elements)
