### ISSUE TITLE
App minimized reads messages

### ISSUE THREAD

**Issue by tuliosciotta** [telegramdesktop/tdesktop#3620]
### Steps to reproduce
1. Open a conversation.
2. Leave the telegram running in background and open another app.

### Expected behaviour
Messages that arrive while you're in another application are read automatically and are not notified. The user always appears online.

### Actual behaviour
New incoming messages are read automatically with the minimized application.

### Configuration
Operating system: Android 6.0.1

**Comment by auchri** [comment]
> Operating system: Android 6.0.1

This repo is only for Telegram Desktop.
