### ISSUE TITLE
Misleading unread counter when new messages are sent in the current chat

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#3621]
### Steps to reproduce
1. Reduce the size window until the chats list gets hidden
2. Open a chat and scroll up until you're no longer at the bottom
3. Wait for new messages in that chat

### Expected behaviour
The unread notification counter appears **only** over the floating button that brings you at the bottom of the chat

### Actual behaviour
The unread notifications counter appears also on the "_back_" button at the left on the title bar, and that's misleading because when I see an unread counter over there I assume there are new messages from a non-muted chat which is not the current chat.

[Screen-record of the issue](http://i.imgur.com/pJlKlJ3.gifv)

### Configuration
**Operating system:** Windows 7 and Windows 10 Pro 10.0.15063

**Version of Telegram Desktop:** 1.1.9 alpha (portable)

**Used theme**: default

**Comment by john-preston** [comment]
@RememberTheAir I can't reproduce that :( There is already specific code part that removes the current chat unread counter from the top bar displayed unready counter and it works as expected when I test that.

Here it is:

https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/window/top_bar_widget.cpp#L228

Since 7th January 😰

**Comment by RememberTheAir** [comment]
Ugh, I'm very unlucky then. I made several tests but I haven't succeded in receiving new messages without that unread counter appearing there.
I forgot to mention I'm using the portable version, I don't think this makes a difference but I will try with the normal app as soon as I have access to a system where I can install stuffs.
I also tried from 1.1.10 but no luck

**Comment by RememberTheAir** [comment]
@john-preston update on this: the problem I described in this issue is only happening when the settings "_include muted chats in the unreads badge_" is **disabled**. If enabled, the counter in the title bar doesn't increase

**Comment by RememberTheAir** [comment]
As you can see from [this video](https://streamable.com/vpt1b): the app on the left has the otpion to count unread messages in the badge enabled. The app on the center has that option disabled, and is counting new messages in the title bar, as there were new unmuted notifications from other chats

**Comment by RememberTheAir** [comment]
Doesn't happen anymore. I'm closing this
