### ISSUE TITLE
Problem with white images on white background

### ISSUE THREAD

**Issue by alivekenny** [telegramdesktop/tdesktop#3623]
Every time someone send screenshot or some white image it just merges with background. There is no any border between so sometimes when you recive screenshot with text you could be really confused.

I propose to add some boder like on iOS version. It could be really helpful.

![white-background](https://user-images.githubusercontent.com/21039303/27827046-dec2060e-60ce-11e7-985d-6b6ce3262439.png)

How it works on iOS (don't mind black areas):
![bitmap](https://user-images.githubusercontent.com/21039303/27827048-e1086070-60ce-11e7-8a60-bf768b0a6afa.png)

**Comment by auchri** [comment]
Use the template please.
