### ISSUE TITLE
No border between picture and background

### ISSUE THREAD

**Issue by alivekenny** [telegramdesktop/tdesktop#3624]
### Steps to reproduce
1. Set white background image or use theme from attachment.
2. Send or recive screenshot or some white picture.
3. See at picture borders. There are none.

### Expected behaviour
You can tell where the picture ends.

### Actual behaviour
You can's tell where the picture ends and background starts. There is no any border between.

### Note
Every time someone send screenshot or some white image it just merges with background. There is no any border between so sometimes when you recive screenshot with text you could be really confused.

I propose to add some boder like on iOS version. It could be really helpful.

### Configuration
**Version of Telegram Desktop:** 1.1.19

**Used theme**: Veritas 1.7 [veritas-1.7.tdesktop-theme.zip](https://github.com/telegramdesktop/tdesktop/files/1121798/veritas-1.7.tdesktop-theme.zip)

![white-background](https://user-images.githubusercontent.com/21039303/27827462-dc79e23e-60d0-11e7-9631-adf5a2f3b4a7.png)

![bitmap](https://user-images.githubusercontent.com/21039303/27827468-e0746e90-60d0-11e7-8ddf-6abb7d131ec2.png)

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
