### ISSUE TITLE
Add the ability to view admin permissions even if you can't edit them

### ISSUE THREAD

**Issue by nyuszika7h** [telegramdesktop/tdesktop#3625]
### Steps to reproduce
1. Go to a group/channel where you're an admin without the "Add new admins" permission.
2. Try to view your or other admins' permissions in the "Administrators" list or the member list.

### Expected behaviour
I should be able to view admin permissions as an admin even if I can't change them, just like on Telegram Android, which shows the toggles greyed out and tells me I can't edit them.

### Actual behaviour
I can't view permissions in either place when I don't have the permission to add new admins.

### Configuration
**Operating system:** Windows 10 Home x64 (Creators Update)

**Version of Telegram Desktop:** 1.1.9 alpha

**Used theme**: Default (Night mode)

**Comment by john-preston** [comment]
@nyuszika7h Yeah, you're right. But currently the UI shows only the checkboxes that you can edit without any greyed out, so for now it can't show rights for the non-editable admins.

**Comment by nyuszika7h** [comment]
This has been implemented already.
