### ISSUE TITLE
different behavior when forwarding message from channel and from bot

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#3626]
### Steps to reproduce
1. forwarding message from news **channel** to friend
-open news channel
-forward message to friend
-in dialog with friend click on %botname% after forwarded from in title
-back to original message in news channel

2. forwarding message from news **bot** to friend
-open news bot
-forward message to friend
-in dialog with friend click on %channelname% after forwarded from in title
-show bot info

### Expected behaviour
i think in both cases must be back to original message in last step
or make arrow icon in forwarded messages from bot with link to original message

v. 1.1.10 alpha

**Comment by john-preston** [comment]
@f242 Sorry, but in case of bots there is no way to go to original message - there is no such thing, bots send every user their own messages, there is no some unique thing among many users from one bot. In channels there is one message for everyone.

**Comment by f242** [comment]
make @botname clickable in bot info, for quick back to bot messages
