### ISSUE TITLE
Incorrect contacts sort order

### ISSUE THREAD

**Issue by KarelWintersky** [telegramdesktop/tdesktop#3628]
### Steps to reproduce
1. Open contacts 

### Expected behaviour
all contacts arranged 

### Actual behaviour
![](https://habrastorage.org/web/7a8/95b/f3f/7a895bf3f24c4506ae6f6dc34fbe3720.PNG)

### Configuration
**Operating system:**
Win7, android

**Version of Telegram Desktop:**
1.1.10 

**Used theme**:
Default

**Comment by john-preston** [comment]
@KarelWintersky Contacts are sorted by name, not by the last seen timestamp.
