### ISSUE TITLE
can't send images or files to a particular user

### ISSUE THREAD

**Issue by capodieci** [telegramdesktop/tdesktop#3629]
### Steps to reproduce
1. be me
2. try to send an image to that particular user
3. fail in trying to do so

### Expected behaviour
Tell us what should happen
Image should be sent to the user

### Actual behaviour
Tell us what happens instead
Image appears, the circle with the X to cancel the upload appears, upload never starts
<img width="542" alt="screen shot 2017-07-05 at 07 15 21 pm" src="https://user-images.githubusercontent.com/10295680/27876172-66ca030c-61b6-11e7-99f9-0eb9dfe179f8.png">

### Configuration
**Operating system:**
MacOS Sierra 10.12.5 (16F73)

**Version of Telegram Desktop:**
Telegram 3.00.1.100200 AppStore

**Used theme**:
none (didn't find anywhere how to change theme)

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)
I didn't find where to see the logs

</details>

**Comment by capodieci** [comment]
To the same user from mobile no issue to send images, and that user can send me images. I can send images from desktop to any other user. I did start a secret chat with that user, and images can be sent there.

**Comment by john-preston** [comment]
@capodieci This is not Telegram Desktop, but another application for macOS.

You can try Telegram Desktop from https://desktop.telegram.og

**Comment by stek29** [comment]
@capodieci btw, you can report issues in _that_ app to https://t.me/macswift

**Comment by lazysergey** [comment]
@capodieci hi man, did you manage to solve this issue?

**Comment by capodieci** [comment]
yes. One of the last versions (updates) of Telegram has solved it.
