### ISSUE TITLE
Hangs at startup on futex()

### ISSUE THREAD

**Issue by davidgfnet** [telegramdesktop/tdesktop#3631]
### Steps to reproduce
1. Use telegram-desktop package built on fedora rpm-fusion
2. Start the program, nothing happens, CPU seems idle, process running though.
3. Did strace() and something probably around GLib messages printed on stderr followed by a futex that never returns.

I get some messages on the cmdline but that happens in some other apps I think

(telegram-desktop:22175): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(telegram-desktop:22175): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(telegram-desktop:22175): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

**Comment by auchri** [comment]
Please try the version from https://desktop.telegram.org/

**Comment by davidgfnet** [comment]
Does it work if I build it myself and report back? Doesn't make much more
sense to point people to prebuilt binaries that God knows where they come
from :(

**Comment by john-preston** [comment]
@davidgfnet Well, this binaries are provided by Telegram team. I'm not sure they'll work, but at least I tested them on several Linux environments. If you build the app yourself I'm afraid you'll have to look in the problem yourself.
