### ISSUE TITLE
library not found for -lssl

### ISSUE THREAD

**Issue by OmidMahmoudi** [telegramdesktop/tdesktop#3635]
![screen shot - - at](https://user-images.githubusercontent.com/19889603/27980862-6a77e58a-6398-11e7-9cb0-0f762cf488fa.png)

**Comment by stek29** [comment]
What if you apply my patch from #3561?
stek29/tdesktop@9dd2b43075e6db9b6e9bafa525f7b7bce9837ca6

**Comment by OmidMahmoudi** [comment]
i apply your patch, and successfully build it
thank you
