### ISSUE TITLE
Timestamp obscures text on certain stickers

### ISSUE THREAD

**Issue by jfsawin** [telegramdesktop/tdesktop#3636]
### Steps to reproduce
1. Send a sticker

### Expected behaviour
The timestamp shouldn't always cover the sticker, as some stickers have text (or other details) at the bottom which gets obscured. I'd expect the timestamps for stickers to behave in the same way they currently do with photos: only displaying on mouse-over.

### Actual behaviour
The timestamp always covers the sticker, mouse-over or not.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.1.11 Alpha

**Comment by Remu-rin** [comment]
(Preventing autoclosing by bot)
Please change timestamps to displaying only on mouse-over, like photos without caption.

**Comment by nihilist23** [comment]
This is really needed on Android and iPhone as well.
