### ISSUE TITLE
Forward to a chat and change to another

### ISSUE THREAD

**Issue by DarthJahus** [telegramdesktop/tdesktop#3637]
I noticed that Telegram desktop lost a great feature (or maybe was it a bug and it got fixed).
When you pressed Forward, and select a chat, you could go back and select another chat so you forward to it instead of the first. Now, the forward message stays in the first chat you visit.

Version `1.1.11 Alpha`.

**Comment by john-preston** [comment]
@DarthJahus Yes, this was changed intentionally.

**Comment by john-preston** [comment]
You'll be able to click on the bar with forwarded messages and choose another chat for them.
