### ISSUE TITLE
Adding "Search in Google" option to right click context

### ISSUE THREAD

**Issue by LostKoder** [telegramdesktop/tdesktop#3638]
### Steps to reproduce
1. Select a text and right click on it
2. Right click on image

### Expected behaviour
"Search in Google" option appeared in context

### Actual behaviour
"Search in Google" option does not appear in context

Vote Up if you're agree on this <3

**Comment by stek29** [comment]
And what if I prefer to search in DDG? Or in Bing? Or somewhere else?
