### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by kmare** [telegramdesktop/tdesktop#3640]
### Steps to reproduce
1. Simply start Telegram 
2. Let it run for a while (could be hours or even days)
3. At some point it will start consuming lots of CPU 

### Expected behaviour
It shouldn't spend all that CPU load

### Actual behaviour
It just consumes CPU time till the program is restarted

### Configuration
**Operating system:**
Fedora Linux 25 on one i7 laptop and one i5 desktop. Same thing on an Ubuntu 16.04 laptop.

**Version of Telegram Desktop:**
1.1.11 (previous versions too. IIRC 1.0 was ok)
**Used theme**:
Any theme
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

running: top -H -p <PID> will return:
top - 19:57:37 up 4 days, 21:42,  1 user,  load average: 0.83, 1.34, 1.37
Threads:  20 total,   1 running,  19 sleeping,   0 stopped,   0 zombie
%Cpu(s):  9.3 us,  0.7 sy,  0.0 ni, 89.0 id,  0.1 wa,  0.5 hi,  0.3 si,  0.0 st
KiB Mem : 16291228 total,  3390260 free,  5596580 used,  7304388 buff/cache
KiB Swap:  8191996 total,  8191996 free,        0 used.  8155060 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND             
 5470 smee    20   0 2686276 653620 100172 S 10.3  4.0   8:19.68 QThread             
13349 smee    20   0 2686276 653620 100172 S  9.0  4.0   7:38.81 QThread             
13346 smee    20   0 2686276 653620 100172 S  7.7  4.0   6:25.81 QThread             
 5471 smee    20   0 2686276 653620 100172 S  6.7  4.0   5:41.01 QThread             
 5482 smee    20   0 2686276 653620 100172 S  6.0  4.0   5:39.49 QThread             
13348 smee    20   0 2686276 653620 100172 S  4.7  4.0   3:56.05 QThread             
 4829 smee    20   0 2686276 653620 100172 R  4.0  4.0   4:22.86 QThread             
13347 smee    20   0 2686276 653620 100172 S  3.7  4.0   3:12.62 QThread             
27411 smee    20   0 2686276 653620 100172 S  1.7  4.0  22:55.85 Telegram            
27412 smee    20   0 2686276 653620 100172 S  0.0  4.0   0:33.49 QXcbEventReader     
27413 smee    20   0 2686276 653620 100172 S  0.0  4.0   0:06.78 QDBusConnection     
27415 smee    20   0 2686276 653620 100172 S  0.0  4.0   0:13.68 Qt bearer threa     
27416 smee    20   0 2686276 653620 100172 S  0.0  4.0   0:00.00 gmain               
27417 smee    20   0 2686276 653620 100172 S  0.0  4.0   0:00.08 gdbus               
27432 smee    20   0 2686276 653620 100172 S  0.0  4.0   0:00.20 QThread             
27433 smee    20   0 2686276 653620 100172 S  0.0  4.0   0:01.95 QThread             
27434 smee    20   0 2686276 653620 100172 S  0.0  4.0   0:00.00 QThread             
27436 smee    20   0 2686276 653620 100172 S  0.0  4.0   0:06.02 MTP::internal::     
 4205 smee    20   0 2686276 653620 100172 S  0.0  4.0   0:00.00 Qt HTTP thread      
27321 smee    20   0 2686276 653620 100172 S  0.0  4.0   0:00.00 Qt HTTP thread      

</details>

**Comment by etehtsea** [comment]
Same problem on macOS Sierra/tdesktop 1.1.10

**Comment by jimmy88** [comment]
I can reproduce this problem too on Ubuntu 16.04 (laptop)

**Comment by smekras** [comment]
I had the same problem here, i7 desktop, and a laptop, both with Fedora 25.

**Comment by LiamDawe** [comment]
I've noticed this too on Ubuntu, even more so when someone is typing a message/just posted it seems to spike up. Which is especially problematic when gaming.

**Comment by carp3** [comment]
Same here. 
also lots of disk usage ... 
i7/laptop/Win10

**Comment by kmare** [comment]
Is there a way we could help the developers debug the issue? It seems like it's not OS or build specific..

**Comment by stek29** [comment]
@kmare Is Sticker/GIF panel enabled? Is something playing? Are there any GIFs on screen? What if you defocus the app?

**Comment by kmare** [comment]
@stek29 No, the sticker/gif panel is hidden, nothing is playing, no gifs on scree. Moving the focus off the app won't help either. The only way to kill all these QThreads is to quit the app and restart it. So yeah, unfortunately I still haven't figured out what's causing the spawning of all these QThreads causing the high cpu load. At this moment, it looks so random as it could happen after a few minutes or a day.

**Comment by silverfoxy** [comment]
I was basically facing the same issue of high cpu load, as high as 140% on mac osx sierra with latest telegram desktop update (1.1.10 as of now) but I've had this issue on previous versions too, after digging for a little bit I found out that my local storage has caused an integer overflow [(2244).](https://github.com/telegramdesktop/tdesktop/issues/2244)
![screen shot 2017-07-19 at 11 46 54 pm](https://user-images.githubusercontent.com/1313190/28386329-858bd2c2-6ce0-11e7-84e3-997637a8d7bd.png)
And this is the local storage:
<img width="252" alt="screen shot 2017-07-19 at 11 51 23 pm" src="https://user-images.githubusercontent.com/1313190/28386342-904537da-6ce0-11e7-9cd5-21ff825b0f5f.png">
After clearing the local storage now the issue seems to be fixed for me:
![screen shot 2017-07-20 at 12 00 34 am](https://user-images.githubusercontent.com/1313190/28386377-9fc93170-6ce0-11e7-9c6c-b7bfad765cc8.png)

**Comment by kmare** [comment]
@silverfoxy that's actually interesting. I checked my local storage and it seems fine though. So I guess, at least in my case, it has to be something else. Thank you for reporting that though!

**Comment by kordestanchi** [comment]
same problem in ubuntu 14.04 and 16.04.
It starts to use a lot of cpu for no reason.

**Comment by Yetangitu** [comment]
Same here on Debian (Sid) 32bit on a Thinkpad T42p, Telegram takes more and more and more CPU after a (short) while. Tracing the process does not show much more than endless calls to `clock_gettime`, `poll`, `recvmsg` and `futex`:

```
[pid 32000] poll([{fd=6, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=13, events=POLLIN}], 4, 399 <unfinished ...>
[pid 32031] clock_gettime(CLOCK_MONOTONIC, {tv_sec=451257, tv_nsec=102094921}) = 0
[pid 32031] poll([{fd=30, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 32031] clock_gettime(CLOCK_MONOTONIC, {tv_sec=451257, tv_nsec=112063820}) = 0
[pid 32031] poll([{fd=30, events=POLLIN}], 1, 0) = 0 (Timeout)
[pid 32031] clock_gettime(CLOCK_MONOTONIC, {tv_sec=451257, tv_nsec=112284246}) = 0
[pid 32031] clock_gettime(CLOCK_MONOTONIC, {tv_sec=451257, tv_nsec=112347384}) = 0
[pid 32031] clock_gettime(CLOCK_MONOTONIC, {tv_sec=451257, tv_nsec=112414434}) = 0
[pid 32031] clock_gettime(CLOCK_MONOTONIC, {tv_sec=451257, tv_nsec=112492100}) = 0
[pid 32031] poll([{fd=30, events=POLLIN}], 1, 30 <unfinished ...>
[pid 32030] <... poll resumed> )        = 0 (Timeout)
[pid 32030] clock_gettime(CLOCK_MONOTONIC, {tv_sec=451257, tv_nsec=115244212}) = 0
[pid 32030] clock_gettime(CLOCK_MONOTONIC, {tv_sec=451257, tv_nsec=115316570}) = 0
[pid 32030] clock_gettime(CLOCK_MONOTONIC, {tv_sec=451257, tv_nsec=115402338}) = 0
[pid 32030] write(6, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32000] <... poll resumed> )        = 1 ([{fd=6, revents=POLLIN}])
[pid 32030] clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 32000] read(6,  <unfinished ...>
[pid 32030] <... clock_gettime resumed> {tv_sec=451257, tv_nsec=115622205}) = 0
[pid 32000] <... read resumed> "\1\0\0\0\0\0\0\0", 16) = 8
[pid 32030] poll([{fd=31, events=POLLIN}], 1, 0 <unfinished ...>
[pid 32000] clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
[pid 32030] <... poll resumed> )        = 0 (Timeout)
```

This is a relatively recent problem, it started about a month ago. Earlier versions did not show this behaviour.

**Comment by Yetangitu** [comment]
I attached a running Telegram process to `strace` to see where things went berzerk. Telegram behaved nicely, 0.1% CPU, nothing special. Messed around a bit, nothing special.

Then I happened to move the pointer over that #%#¤&/%/%/ smiley button which I'd rather ditch yesterday than today. The blasted popup appeared again with a hoard of moving GIF images. I clicked outside of it to get rid of the dreaded things and had a look at the trace. 5 new threads had been launched and the trace was going wild, suddenly Telegram was hogging 25% CPU. Mind, the popup was gone, no moving images in sight, all peace and quiet on the surface. Below the surface it seems some QThreads were busy doing something anyway, something which took a lot of CPU.

Then I switched the horrible emjoistickergif popup to the 'emoji' tab and closed it. The CPU hoarding stopped. Switched back to the moving misery, closed popup, NO CPU HOARDING. Switched back and forth a few times, sometimes it started hoarding CPU, other times it didn't. The interesting observation is that I never got any hoarding problems when the popup was set to 'emoji' or 'stickers' but did get it when the thing was set to 'gifs'.

**Comment by kmare** [comment]
@Yetangitu thank you for "discovering" that! I'll take a look at that too and see if this is what is causing the 100% CPU load with telegram spawning all these QThreads.

**Comment by kmare** [comment]
I can confirm what @Yetangitu said! It really works! So basically, as soon as you see the CPU load going up cause of telegram, just click on the emoji/stickers/gifs icon once, click on it again and the telegram CPU load will go back to where it should be idling! If anyone else could confirm, please do so. Hopefully the developers will find out a solution.

**Comment by Yetangitu** [comment]
From my observations it is enough to make sure that the popup is not set to 'gifs' before it is closed to avoid Telegram hogging the CPU. I have not seen any hogging since doing this.

**Comment by sstyle** [comment]
#4238

**Comment by sstyle** [comment]
Same on High Sierra Mac OS, **but** 1.1.13alpha takes much less resources.

**Comment by auchri** [comment]
@sstyle Please try the current version, v1.2.6.

**Comment by sstyle** [comment]
@auchri I tried (you can see it here #4238) and found that 1.1.13 much better, but still has this issue.

**Comment by pizzadude** [comment]
This is just Telegram using your computers resources to create the first batch of TelegramCoin, the new cryptocurrency. Nothing to be worried about.

**Comment by sstyle** [comment]
@pizzadude Nice. So we can close this thread )

**Comment by Hulkmaster** [comment]
happened to me right now

**Comment by Hulkmaster** [comment]
launch
high cpu (for a couple of minutes)
low cpu
wait a little bit
high cpu (for a couple of minutes)
low cpu

mac 10.13.3
telegram 1.2.6

**Comment by davronakil** [comment]
Same problem and I'm trying to fix it. Try turning off all notifications. So far I think it's not going crazy anymore.

**Comment by durkmurder** [comment]
I am using v1.2.6. What I saw that if telegram runs CPU load is very high, it consumes 70% of CPU time. The only way to stop this is to minimize telegram window. If you just switch to other app, but leave it on screen, even if it's completely overlaid by another window, it won't help, only minimization helps.

**Comment by remybach** [comment]
fwiw: I've particularly noticed this CPU issue when I've used the `@gif` bot. Even after selecting a gif and the popup has gone away the CPU sits at a really high percentage unless I quit and reopen.

**Comment by john-preston** [comment]
@remybach For me it goes down after the GIFs panel is closed :(

**Comment by remybach** [comment]
@john-preston The panel that's part of the popup when you hover over the emoji, or the popup when you search using the `@gif` bot? I never use the emoji one so I don't know about that one.

Annoyingly, I can't 100% reproduce this. I asked a friend and when he checked his CPU spiked up to 100%, but mine hardly blipped when I just tested.

**Comment by john-preston** [comment]
@remybach The GIFs kill the CPU in Telegram Desktop :( But when the popup hides (both the emoji-stickers-gifs and the inline bot results, like @gif one) it goes back for me.

**Comment by Scukerman** [comment]
In my case telegram starts consuming CPU in two cases:
1. a chat has a message from @gif which is animated and is on screen (on page) right now.
2. telegram starts playing a song from any music channel (e.g. https://t.me/ifletov).

OS: macOS 10.13.3
Telegram: 1.2.6

**Comment by haodemon** [comment]
I found that TelegramSwift (https://github.com/overtake/TelegramSwift) does not have this issue.

**Comment by AntonMalyshev** [comment]
TelegramSwift has low CPU load but is sluggish as hell, not better

**Comment by diegogub** [comment]
I have the same issue on telegram for OSX. High CPU usage after first chat..

**Comment by ManuelSchneid3r** [comment]
Yes. I am simply reading a group chat and my macbook glows. The chat does not allow media by the way. Only text.

**Comment by ryush00** [comment]
After upgrade my Mac to High Sierra, CPU usage also got High.

**Comment by t0str** [comment]
Version 1.2.6 on MacOS 10.13.3, same behaviour. Telegram suddenly starts using a lot of CPU for no apparent reason (no gif playing or anything). Restart of Telegram fixes the issue (until it occurs again). It's a recent issue (don't know the specific version, but it did not happen as of v1.0).

**Comment by Etherealflux** [comment]
I'm observing this behavior when I rapidly scroll through all of my gifs, then mouse away from the popup. My CPU usage spikes to at least 50% on my Ryzen 1700, and the app instantly eats a good 600 MB of memory.

Mousing over the gif menu, so that they briefly display again, fixes it immediately. Memory freed, CPU back to <1%

I have a number of very large MP4 files stored in there - think 1000x1000@60fps. That's probably exacerbating the issue.

It seems like Telegram is trying to render *all of the videos at once*, even though I'm not able to look at them, and just..getting stuck.

**Comment by sstyle** [comment]
Also I found that CPU load is very high when someone typing to me. Load drop If he stops typing.

**Comment by l1x** [comment]
```Also I found that CPU load is very high when someone typing to me. Loading drops If he stops typing.
```

Same here

**Comment by tobsn** [comment]
That's still a thing yes, latest OSX, latest TD... instant CPU spike, instant heat increase to 80C.

**Comment by AntonMalyshev** [comment]
Made me uninstall Telegram Desktop and use mobile version only

**Comment by Yetangitu** [comment]
All these symptoms - CPU hoarding on GIF, when someone is typing, etc - point at the culprit being something related to animations (tight loop running a timer?) as the _typing..._ animation and all that moving-gif-misery share these characteristics. I haven't looked at the source yet, those who have might get an idea of where the problem lies. Maybe I should look at the source ...

**Comment by karray** [comment]
the same here. win 10, telegram 1.2.17 

after telegram runs for a while it starts to load cpu of  about 10-15% and also when someone is typing or a gif play as already mentioned above

**Comment by pryg-skok** [comment]
Telegram desktop 1.2.24 alpha mac os high sierra (10.13.4)  - client constantly uses more than 3% of CPU and has spikes to 10%. In IDLE state while I'm not even reading or chatting there.

**Comment by JustM57** [comment]
TG for no reason starts to use 1850% of CPU. And I7-7950K Xtreme goes dead. But it really may happen because of GIF-bot as I started to use not long ago

**Comment by benjaminmbrown** [comment]
Y'all mining crypto in the background or something?

**Comment by hmepas** [comment]
Mac OS X 10.13.5 
Telegram 1.3.9
Still an issue, out of the blue starts to eating cpu. Not even using emojis. Really annoying.

**Comment by postables** [comment]
Ubuntu 18.04 here, I've tried renicing all TG processes to 19 as well and that barely does anything :/

**Comment by linjan** [comment]
Same here :(
![d1288351](https://user-images.githubusercontent.com/5128657/43233223-8844d61e-907d-11e8-91c5-206878ef2719.png)
![79c1108e](https://user-images.githubusercontent.com/5128657/43233249-a528b70a-907d-11e8-963e-88d4598748ea.png)

**Comment by josiasmat** [comment]
Using Windows 10. CPU usage is acceptable at ~0,4 with no chat opened and minimized. But I think Telegram should use less than that in this situation. Took a screenshot from the threads CPU utilization:
![image](https://user-images.githubusercontent.com/4457615/43357760-df759bfe-925c-11e8-9888-a6b83f582365.png)
No idea about why Telegram calls PlaySoundW if there is no sound to be played...

**Comment by NamGikFuiHung** [comment]
One year after, the problem still exist...

**Comment by gbcox** [comment]
It appears (at least for me) that something in the stored configuration became corrupted - and this issue continued to be propagated between releases.  What I did was to completely remove from my system (un-install and then manually delete all the saved settings).  I then installed and configured everything as if I was a first time user.  This fixed the issue for me.  

If you uninstall, reinstall and you aren't prompted to enter your phone number again, you didn't get rid of everything.  You must erase all traces of the previous installation to ensure you delete whatever was corrupted.

On Fedora Linux, this means to remove the directory that contains the telegram executable AND to also delete the hidden .TelegramDesktop directory AND .local/share/TelegramDesktop AND .config/autostart/Telegram.desktop

If you are on another platform, you'll need to research where all the files are hidden, then manually get rid of them.

Hope this works for others - it worked for me.

**Comment by Scukerman** [comment]
The ones who have problems with their macs, I bought a new one (with touchbar) and the problem disappeared.

Fixed.
😆

**Comment by itcrowd72** [comment]
Ubuntu 18.04 MATE, telegram 1.4.3 eat 30-40% CPU (i7, 8 cores).

**Comment by gskornowicz** [comment]
Also having this issue.
System: Linux Mint 18.1 Serena EDITION="Cinnamon 64-bit" TOOLKIT=GTK
CPU: AMD Phenom(tm) II X4 960T Processor 2.3 GHz

I can confirm that CPU High usage is linked with GIF menu.

**Comment by turbodevelopers** [comment]
The same problem. 30-40% CPU load. Macbook pro, 2018 mid, core i5. MacOS Mojave 10.14

**Comment by ftrebien** [comment]
I'm having this problem on version 1.1.23 on Debian Stretch. It happens only when I am viewing or minimize the app while viewing the chat area of two specific groups, but not other groups. It does not matter if the side panel with emojis, stickers and GIFs is displayed or not, or which tab is selected. If, on the group chat area, I click the group name, showing the group members, the problem goes away. So if I move to other groups or private conversations. One of the groups is quite old (more than 1 year), the other one was created only a few days ago (less than two months). The oldest group, with 9 members, has a significant amount of media: 736 photos, 5 videos, 10 files, 1 voice message, 1903 shared links. The newest, with 8 members, only has 50 photos and 113 shared links. Some of the members had been offline for more than a month, but are back now. I have tried clearing the global storage, but it made no difference. I may have to clear the group's history, but honestly I don't want to. I've checked that the CPU spike happens regardless of which content in the group chat is being viewed, and that the same kind of content (website links with a preview, photographs, YouTube video previews) does not cause a CPU spike when viewing private chats. The two groups were pinned, I tried unpinning, and also silencing them for one hour, but none of those things made a difference. So I think the problem may be some sort of data corruption on those groups' chat history. While I was writing this, the CPU spike stopped happening on one of those groups. The only different thing was that someone had replied one of my messages. Then I tried sending a message with no media, just text, and the problem didn't return. On the other group it still happens. The last message was mine, it was a YouTube link with a preview. So I tried sending a GIF with @gif. Nothing changed, still one group spikes and the other (where I sent the @gif) does not. Then I tried posting a YouTube link. No change still. Re-enabled notifications, sent a GIF, nothing changed. Sent another YouTube video. Brief spike while generating the preview, but nothing else. Switching to the other group still maxes out the CPU again. Restarting the app makes no difference, still one group produces a CPU spike and the other does not.

**Comment by eduzen** [comment]
Same problem. 50-80% CPU load. 
Macbook pro
MacOS Mojave 10.14

**Comment by LeviSchuck** [comment]
This is certainly still a problem, MacBook pro, MacOS Mojave.
usually hovers around 8-9 percent. After restarting telegram it consumes about 4%.

This is contributing to a warm laptop with lower battery life. 
I think it is still actively rendering stuff like gifs even when the app is in the background (on another workspace, or full screen but not active).

**Comment by linjan** [comment]
Lightly lowered CPU load by disabled animations and autoplaying GIFS.
![selection_070](https://user-images.githubusercontent.com/5128657/48699835-7c540580-ebfb-11e8-88f4-3689e42a5dd3.png)

**Comment by yrambler2001** [comment]
After being computer in a sleep for 10 hours, telegram started consuming cpu for about 20 seconds on my Core2 Quad 3GHz.
![image](https://user-images.githubusercontent.com/8398353/50001687-4c074900-ffa6-11e8-94ca-a961b799b681.png)
It looks like QT is accumulate events every second, and after computer being in a sleep there is a gap in time. so qt have *some* events to process.
![image](https://user-images.githubusercontent.com/8398353/50001803-a56f7800-ffa6-11e8-9f36-9a1101680169.png)
![image](https://user-images.githubusercontent.com/8398353/50001814-af917680-ffa6-11e8-86b6-b921eca3341d.png)

**Comment by heaven** [comment]
I notice this when someone is typing a message if that helps (sorry, I didn't read the whole thread, perhaps someone already reported that).

**Comment by DocSnyder0815** [comment]
I can confirm the behavior as mentioned by @heaven. (macOS 10.14.3 (18D109))

**Comment by doc-E-brown** [comment]
Same problem Kubuntu 18.04.  Leave telegram run for a while and CPU on my 4 cores maxes out.  The app is version 1.5.15 and was installed via snap

**Comment by oxydron** [comment]
Using between 30-40% most of the time.
Manjaro (mate) 18.0.1.
Some things I observed too: everytime you open the gifs panel or play a music on it, it spikes to almoost 100% cpu usage then get back to ~35%

**Comment by Justbigmack** [comment]
Same thing for me.  Leaving telegram open makes CPU jump to 80 degrees celcius. Maxed out Macbook pro 2018 MacOS Mojave 10.14.3

**Comment by vetermanve** [comment]
Yes, after night sleep my Telegram start consuming about 1 CPU core quite a long time, I should restart it ti stop waisting my Mac performance...

**Comment by mattparlane** [comment]
Just to add to everything already here... I have a dodgy wifi connection and whenever it drops, Telegram goes to 100% almost immediately. I suspect this is because of the "connecting..." animation, much like the "typing..." animation, which I also experience.

**Comment by bamorim** [comment]
Same thing here. I decided to stop using the desktop and fallback to the web version in hope it consumes less CPU.
From time to time, my fan makes my computer look like a jet engine and when I check telegram is at 50%~90% CPU usage.
maxed out macbook pro 13 2015 (except for the ssd). Using macOS Mojave 10.14.4

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/60501937-7f0ef100-9cda-11e9-9374-cf37e0f437ce.png)
Telegram v1.7.10
 Windows 10 1903

**Comment by gaydenko** [comment]
The same for 1.8.1 on Linux/Manjaro box running KDE. Sometimes the app constantly eats 22-23% without any UI activity (and never less than 6%). Percentage are for Intel i5-6600. At first I was sure it just eat one CPU core. But looking at the load graph I have found all four cores are in use more or less equally.

**Comment by MischievousTomato** [comment]
Same for me on Fedora 30, Amd cpu+gpu, fully updated

**Comment by ValentinJesse** [comment]
Consumes crazy amounts of CPU power. 50% with active window without scrolling and up to 80% with scrolling. My MacBook Pro i7, 16gb ram 2017 is spinning up the fans non-stop

**Comment by user38192** [comment]
Sometimes, 99% CPU usage and 600-800 ram usage. TG Desktop 1.8.8., Windows 10 1903

**Comment by talentlessguy** [comment]
Still an issue on Linux 5 and TG Desktop 1.8.15

**Comment by chapati** [comment]
This issue is over 2 years old already. Very professional approach! But we have animated stickers. Of course stickers are much more important!

**Comment by talentlessguy** [comment]
> This issue is over 2 years old already. Very professional approach! But we have animated stickers. Of course stickers are much more important!

I think this problem has too many factors so each case should be resolved separately.

**Comment by Aokromes** [comment]
> > This issue is over 2 years old already. Very professional approach! But we have animated stickers. Of course stickers are much more important!
> 
> I think this problem has too many factors so each case should be resolved separately.

i supplied multiple valgrind logs, but no one looks to have the knowledge to fix the issues and with that maybe the high cpu load.

**Comment by chapati** [comment]
> This issue is over 2 years old already. Very professional approach! But we have animated stickers. Of course stickers are much more important!

There is even no single comment from developers in this huge 89-comments thread. As once Buddha said, there are only two mistakes one can make along the road; not going all the way, and not starting.

**Comment by chapati** [comment]
> > This issue is over 2 years old already. Very professional approach! But we have animated stickers. Of course stickers are much more important!
> 
> I think this problem has too many factors so each case should be resolved separately.

As once Buddha said, there are only two mistakes one can make along the road; not going all the way, and not starting.

**Comment by SmartManoj** [comment]
@chapati  Be Patient or make a pull request

**Comment by Aokromes** [comment]
some memleaks where fixed making cpu load to drop.
i want to know if everyone thinks this bug is fixed.

**Comment by ivnish** [comment]
I don't have this problem a long ago)

My previous comment was on Oct 18, 2018

**Comment by nordluf** [comment]
> some memleaks where fixed making cpu load to drop.
> i want to know if everyone thinks this bug is fixed.

What version are you talking about? Last update some days ago, fedora 31 - CPU goes up after ~30 minutes

**Comment by nortexoid** [comment]
Can confirm on Manjaro. It's fine at first and then suddenly I check "top" and the application is consuming over 40% of one of my i5 cores.

**Comment by nordluf** [comment]
> What version are you talking about? Last update some days ago, fedora 31 - CPU goes up after ~30 minutes

As a follow-up. A version from testing repo (1.9.8) works well after ~1 day of usage. Non-testing version 1.9.4 consumes CPU

**Comment by Aokromes** [comment]
plz test only desktop.telegram.org or github releases build, i have seen it distribution based packages to give bugs not present on official releases.

**Comment by wchristian** [comment]
On Windows 10 the 1.9.9 version used half a cpu core all night for me despite telegram being in the background.

Interestingly the cpu usage is about the same as if i open the smiley > gifs tab.

**Comment by nortexoid** [comment]
I've tried both the official Manjaro package and the one available on desktop.telegram.org and they show the same unusually high cpu usage still.

**Comment by grravity** [comment]
I get high CPU usage as well, sometimes it drops extremely low, but other times it spikes up using quite a bit (on the same menus) 
I do have lots of groups and chats added, with gifs and images going through them constantly, but they shouldn't be doing anything unless I actually open the chat. Assuming that might be the issue.

Windows 10, TGDesktopVersion: 1.9.14

**Comment by rmrfchik** [comment]
High CPU usage on Debian (60%).
All chats are closed.
perf shows TG decodes some video:
$ perf report |grep -v '^#' | head -3
     8.54%  QThread          Telegram                              [.] ff_h264_decode_mb_cavlc
     2.47%  QThread          Telegram                              [.] ff_h264_filter_mb_fast
     1.49%  QThread          Telegram                              [.] 0x00000000019f1ce1                                                                     

Telegram 1.9.14

**Comment by Aokromes** [comment]
your is very likely https://github.com/telegramdesktop/tdesktop/issues/6312#issuecomment-525712797

**Comment by rmrfchik** [comment]
> your is very likely [#6312 (comment)](https://github.com/telegramdesktop/tdesktop/issues/6312#issuecomment-525712797)

Not sure, there are no any chat opened and no any video are played. Seems like TG don't cancel video decoding.

**Comment by wchristian** [comment]
@rmrfchik Go into a chat, mouse over the emoji button, change the tab away from gifs to emoji, close the chat. Then check your CPU again.

**Comment by rmrfchik** [comment]
@wchristian it helped at once! thanks!

**Comment by nortexoid** [comment]
> @rmrfchik Go into a chat, mouse over the emoji button, change the tab away from gifs to emoji, close the chat. Then check your CPU again.

Seems to have fixed high cpu usage for me. It's been a couple fo days now of testing.

**Comment by loicmolinari** [comment]
On Linux (Debian 10.3), the Telegram process is constantly polling, even though the UI is not animated and no message is sent nor received, as can be seen with this strace output:

```shell
$ strace -p `pidof Telegram`
strace: Process 25205 attached
restart_syscall(<... resuming interrupted poll ...>) = 0
recvmsg(17, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=14, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}], 6, 8) = 0 (Timeout)
recvmsg(17, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=14, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}], 6, 7) = 0 (Timeout)
recvmsg(17, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=14, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}], 6, 8) = 0 (Timeout)
recvmsg(17, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=14, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}], 6, 7) = 0 (Timeout)
 <...>
recvmsg(17, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=14, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}], 6, 7) = 0 (Timeout)
recvmsg(17, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=14, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}], 6, 8) = 0 (Timeout)
recvmsg(17, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=14, events=POLLIN}, {fd=17, events=POLLIN}, {fd=18, events=POLLIN}], 6, 7) = 0 (Timeout)
recvmsg(17, ^Cstrace: Process 25205 detached
 <detached ...>
```

**Comment by wchristian** [comment]
@loicmolinari due to the nature of this ticket it's not really monitored, but if you can write up clear reproduction steps and open up a new ticket, that'll have better chances

**Comment by GitLad** [comment]
FIX IT

**Comment by Yetangitu** [comment]
> FIX IT

While I agree with the idea that it would be good to fix bugs, I disagree with the way the demand is stated. Did you forget the magic word?

**Comment by wchristian** [comment]
in this situation on amount of "please" would help, as @loicmolinari still needs to provide repro steps

**Comment by Yetangitu** [comment]
> in this situation on amount of "please" would help, as @loicmolinari still needs to provide repro steps

Still, it would improve the discourse for no cost at all. I don't know whether @loicmolinari gets paid to work on this project but - this being GH - I generally assume most people around here are volunteers. When I volunteer to do something I tend to dislike being commanded to FIX SOMETHING...

**Comment by wchristian** [comment]
i've released so much open source and my experience says: don't make a fuss of it unless it is targeted harrassment, as the fuss always tends to be bigger than the event itself. :)

https://metacpan.org/author/MITHALDU

**Comment by ilya-fedin** [comment]
>  I don't know whether @loicmolinari gets paid to work on this project

He just reproduced the issue, isn't it? o_O

**Comment by ilya-fedin** [comment]
> FIX IT

Let's rewrite the whole animation engine, do a good deed for everyone!

**Comment by GitLad** [comment]
> > FIX IT
> 
> While I agree with the idea that it would be good to fix bugs, I disagree with the way the demand is stated. Did you forget the magic word?

Mate, no one is going to play nice, people begged for years and no one did stuff, if you are 3rd rate dev looking to beef up your student CV and half-assedly do it then do people a favour and don't. A professional organisation will take it under its wing.

**Comment by sgon00** [comment]
Hi, I am having 70% High CPU Load on MacOS Big Sur. I think it might because I joined too many groups. Is there a built-in cpu usage tool in telegram so that I knew which group is using the highest CPU, then I can leave that group? Thanks a lot.

**Comment by mihailtugushev** [comment]
I had the same problem here, i5 a laptop, with Big Sur 11.2.3

**Comment by sgon00** [comment]
> I had the same problem here, i5 a laptop, with Big Sur 11.2.3

Uninstall this app and install `TelegramSwift` on MacOS. You can find it in github. (To be polite, I am not pasteing its URL here). I am using it right now. It has hardware acceleration and no cpu issues.

**Comment by john-preston** [comment]
@sgon00 It is official Telegram app for macOS, everyone can download it here: https://macos.telegram.org/

**Comment by sgon00** [comment]
> @sgon00 It is official Telegram app for macOS, everyone can download it here: https://macos.telegram.org/

Yeah, I knew. But it's a different project so I feel it's not polite to introduce it in this project. :)

**Comment by john-preston** [comment]
@sgon00 Thanks. I've posted for everyone who reads here, it's just there is no way to reply without a mention using the GitHubBot.
