### ISSUE TITLE
Cannot join a group/channel

### ISSUE THREAD

**Issue by Imadlekal** [telegramdesktop/tdesktop#3643]
Note that the channels/groups I'm trying to join was accessible. In fact, I was writing a message in one of them until (and suddenly) all groups and channels were deleted from my contacts list, and only individuals were left. Now I'm trying to join again, and It says the message given below.

### Steps to reproduce
1. Just try to access a group (in my case t.me/MonacoCard )

### Expected behaviour
This should let me join the group/channel.

### Actual behaviour
I'm having an error message saying 'Sorry, this group is not accessible' 

### Configuration
**Operating system:** Windows 10 - 64 bit

**Version of Telegram Desktop:**  1.1.10

**Used theme**: awesome.tdesktop-theme

**Comment by auchri** [comment]
@Imadlekal How is this related to Telegram Desktop?

**Comment by Imadlekal** [comment]
It's not? having your groups and channels deleted and not being able to join is not a software bug? It looks like one to me.

**Comment by john-preston** [comment]
@Imadlekal This is something related to the server treating you that way :( I'm pretty sure you don't see them / can't join them on Android / iOS as well. And there is nothing I can do about it :(

**Comment by Imadlekal** [comment]
@john-preston  What are the chances that all groups kicked me in the same time? I'm the only one who think this make no sense?

**Comment by john-preston** [comment]
@Imadlekal Perhaps you got blocked or there is some server side issue. I don't say that it makes sense. I say I can't do anything about it — nothing in the Telegram Desktop source code (that I edit) can fix your problem.

**Comment by Imadlekal** [comment]
I didn't even knew you are a developer. No problem though, I appreciate the help 👍

**Comment by BTCBadger** [comment]
@john-preston please help. I have used Telegram - Android and Browser - for years and have created and belong to several groups. Recently I was invited to join a channel, rather important one in my career, but on both platforms I get the "Channel no longer accessible" error - only for this one group. I know the admin and they assure me I am not and never have been blocked and was never a member.

I have chatted with a Telegram volunteer since who was provided all the channel info by the admin. But still not able to cast any light either. This is a total mystery and frustrating because I need this group. Can you please advise.

**Comment by john-preston** [comment]
@BTCBadger You can look in "log.txt" in the Telegram Desktop when you try to open that channel and see if there is an error.

**Comment by BTCBadger** [comment]
I haven't used the Desktop, just Web. Do you suggest I install it?

**Comment by Imadlekal** [comment]
@BTCBadger  yep, pretty good compared to the web version.  (more features, themes etc.)

**Comment by BTCBadger** [comment]
![telegram 1](https://user-images.githubusercontent.com/33288360/32281037-4da97466-bf26-11e7-986e-da6a28eb8a2c.jpg)
![telegram 2](https://user-images.githubusercontent.com/33288360/32281039-4e043edc-bf26-11e7-87c2-49f13fe0c6d0.jpg)

**Comment by BTCBadger** [comment]
Ok will do. These are the error message from web

**Comment by john-preston** [comment]
@BTCBadger No need to install Telegram Desktop for that problem, you've shown the error already.

**Comment by BTCBadger** [comment]
cool, can you help?

**Comment by john-preston** [comment]
@BTCBadger No, unfortunately, I can't :(

**Comment by BTCBadger** [comment]
Ahm.. haha.. anything I can do?

**Comment by BTCBadger** [comment]
I guess I'm asking if you know what is wrong?

**Comment by auchri** [comment]
@BTCBadger The error message lets me assume that you are trying to join a private channel.

**Comment by john-preston** [comment]
@BTCBadger What exactly community are you trying to join? By a public link or a private link? Is it a channel or a supergroup?

**Comment by BTCBadger** [comment]
It's @btcglobalofficial 
https://t.me/btcglobalofficial

There are no banned users on the group & it's still active with new people joining every day. 
Admins on the group can't add people - they can only join from the links above
Telegram
BTCGlobal Official Updates
Welcome to the official BTC Global Updates group.

All company notices, news & system alerts will be posted here.

For general discussion you can jo...

**Comment by remedcu** [comment]
I am also having the same problem as BTCBadger, tried to join Waves Community with always showing the error "Sorry, the group is not accessible"

**Comment by HellScre4m** [comment]
I have the same problem in telegram desktop after a group migrated from private to public mode. No problem on android version but only Telegram Desktop.

**Comment by stek29** [comment]
Does it persist after app restart? Does it work in Webogram?

**Comment by HellScre4m** [comment]
You're right it didn't persist. Seems it's Core API problem not TDesktop. Sorry.

**Comment by jgr33nwood** [comment]
Same issue right now with 👉🏻 Current//CRNC 📲 chat. I thought maybe they hit the user limit, since I am an admin of quite a few channels myself, but it is a supergroup with 80k+ users. https://t.me/joinchat/F-KV7A8VpJrZw-QBRjumRg That link leads to the same exact message. Confirmed not banned, logged in on a second account that has had less than ten mins of login time, same notice. This is HUGE.

**Comment by Linicks** [comment]
I'm having this exact same issue, and have made sure the apps are up to date and devices have been restarted.  What causes this issue?  There is absolutely no reason why I would have been banned from any channel.

**Comment by tzargaryan** [comment]
Hi I just had a similar issue with my telegram app group chat. I wrote back then wanted to reply again and the chat dissapeared. When I am searching fro the chat I can not access it.
