### ISSUE TITLE
GIFs are not clickable after forward

### ISSUE THREAD

**Issue by Kolahzary** [telegramdesktop/tdesktop#3645]
### Steps to reproduce
1. Forward a GIF message 
2. Simply try to click on it...

### Expected behaviour
Normally when someone clicks a GIF on tdesktop it'll be opened in full-screen mode 

### Actual behaviour
Nothing happens when you click it, it's not clickable at all!
But after closing and reopening tdesktop, it would be clickable and full-screen mode will work again!

### Configuration
**Operating system:**
Microsoft Windows 10
also tested on Ubuntu Desktop

**Version of Telegram Desktop:**
1.1.10

**Comment by Maders** [comment]
same issue on macOS Sierra 10.12.5.
