### ISSUE TITLE
Wrong web browser opened when clicking links in chats

### ISSUE THREAD

**Issue by tdammers** [telegramdesktop/tdesktop#3646]
### Steps to reproduce

1. Open a chat in the Linux desktop client, where people have posted URLs
2. Click one of the URLs to open it

### Expected behaviour

The default web browser (as per `x-www-browser`) should pop up and open the URL

### Actual behaviour

Chromium pops up and opens the URL

### Configuration

**Operating system:** Debian GNU/Linux 9 (stretch), Linux 4.9.0-3-amd-64

**Version of Telegram Desktop:** 1.1.10, 64-bit Linux

**Used theme**: Default

**Comment by stek29** [comment]
Does xdg-open work correctly?

**Comment by tdammers** [comment]
D'oh!
