### ISSUE TITLE
Add option to hide last messages in contacts list 

### ISSUE THREAD

**Issue by kiritu** [telegramdesktop/tdesktop#3647]
### Steps to reproduce
Open main window (in windows or mobile app)

### Expected behaviour
Like to see contact list with Contact names without last messages, to maintain privacy

### Actual behaviour
You will see chat list with Contact names and last messages sent from/to them. Messages might have a private data that might be catch in crowd place 

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.1.10

**Used theme**: Standard

</details>

**Comment by andrew-phi** [comment]
This could also save some vertical space and allow to display more contacts per page.

**Comment by stek29** [comment]
#1775
