### ISSUE TITLE
1.1.11 bold + italic behaviour

### ISSUE THREAD

**Issue by andreyorst** [telegramdesktop/tdesktop#3648]
### Steps to reproduce
1. type **
2. then __
3. then some words
4. then **__

### Expected behaviour
**_something like this_**

### Actual behaviour
![image](https://user-images.githubusercontent.com/19470159/28079338-995eef08-6670-11e7-9dc9-2668b45b1a5f.png)

### Configuration
**Operating system:**
Archlinux
**Version of Telegram Desktop:**
1.1.11 alpha

**Comment by john-preston** [comment]
Nesting entities (bold inside italic or italic inside bold) are not supported on the server, so I didn't support them in the app. I would like it to stay that way :D

**Comment by andreyorst** [comment]
Meh, ok then, but that's kinda strange

**Comment by set92** [comment]
version = 1.1.12 alpha in Archlinux
Bold is not working for me locally, I used **try** and the rest of the group can see try bolded but in my computer I don't see it.

**Comment by stek29** [comment]
@set92 #2128?

**Comment by set92** [comment]
Maybe, because I just tried with the @bold bot and it doesnt work, so I suppose is the same error, I tried installing open sans semi bold but is the same, no bold with the bot or with markdown.

**Comment by stek29** [comment]
@set92 anyway it's not related to this issue, please move to the one ok linked

**Comment by john-preston** [comment]
@set92 Looks like the bold text is not displayed for you at all. Are you using the build from https://desktop.telegram.org?
