### ISSUE TITLE
[Feature request] Telegram for console(s)

### ISSUE THREAD

**Issue by MerkeX** [telegramdesktop/tdesktop#3650]
I don't know if this is possible, and the idea could die as soon as I finish typing, but I'll ask anyway.... There's a (even remote) possibility to bring Telegram on consoles? I mean, since on Xbox 360 there's no way to communicate with other players on other consoles (for example, with Skype), it would be useful (I hope) for many players to see that there's a way to communicate with other players or friends. There's a lot of people who still play on old-gen consoles like me, and I would really appreciate the fact to have an app that allows me to communicate with people that not necessarily have my same console. Said this, I genuinely thank you people for reading this (maybe crazy) request, and wait for your response.
P.S. English is not my native language, so grammar errors can be present. Also, i'm not very practised with GitHub, so I'm sorry if I have done something wrong.

**Comment by stek29** [comment]
@MerleX won't web.telegram.org work? 
Anyway, TG has open\* API, so I think the client would have to be done by some third party.

\*: /me tries not to laugh, then starts crying

**Comment by MerkeX** [comment]
@stek29 I have tried "web.telegram.org" on my Xbox One, but you can't make calls, only texting. I really doubt that on the Xbox 360 you can. I know that there's an open source API, and could be possible for anyone to support new platforms; I would do it by myself, but since I have really low programming skills, I think that this project is out of my league. I don't know if someone can suggest me any books where I can study in my spare time, but I suppose that I would need years before being able to develop it.

**Comment by Socialdarwinist** [comment]
I think that it is a good idea for spreading Telegram and reinforcing the portability argument in support of Telegram. Just that it is far-fetched to rank this wish as a Telegram Desktop matter, for when using a console as specified by the OP, one sits typically on a couch and not in front of a desktop.

But what the OP has not considered, but is a valid file of thought, which came me first in mind when I read the issue title, is _running Telegram inside a virtual console_. Like, not from a virtual console, but inside it. CLI-only. Of course not as separate application, but by being passed as argument in the command executing Telegram. It would be nice-to-have, and appealing to geeks.

**Comment by stek29** [comment]
You can use Unigram on Xbox One.
I hope other consoles can handle Webogram.
Anyway, this has nothing to do with TDesktop.
