### ISSUE TITLE
Disabling shortcuts

### ISSUE THREAD

**Issue by Lord-Evil** [telegramdesktop/tdesktop#3652]
When the chat bot displays buttons and you try to input into a text box digits, the button is being triggered instead of text being entered. I really need to be able to disable this functionality, it's meaningless in a desktop client and very irritating.

**Comment by stek29** [comment]
@Lord-Evil What if you type `moderate` in settings?

**Comment by Lord-Evil** [comment]
@stek29 it does the trick indeed! Thanks! Is there a list of this options somewhere?

**Comment by stek29** [comment]
@Lord-Evil [Here](https://github.com/telegramdesktop/tdesktop/blob/197cdc3928d2403814c147f8394ef42ed427c9d8/Telegram/SourceFiles/settings/settings_widget.cpp#L51)
