### ISSUE TITLE
Reduced list of self-destruct options

### ISSUE THREAD

**Issue by Kylmakalle** [telegramdesktop/tdesktop#3655]
### Steps to reproduce
Settings -> Account self-destruct settings
### Expected behaviour
![image](https://user-images.githubusercontent.com/24507532/28112641-76965366-6702-11e7-80a4-4ba4cc7df615.png)

### Actual behaviour
List of options does not even scrollable
![image](https://user-images.githubusercontent.com/24507532/28112650-862c0ef6-6702-11e7-826e-3755645968a6.png)

### Configuration
**Operating system:**
Win 10 x64
**Version of Telegram Desktop:**
1.1.12 alpha

**Comment by MasterGroosha** [comment]
Since there are no "selected" bullets, I guess it's just a bug. All other clients still show the full list with all options available.

**Comment by MasterGroosha** [comment]
+ the same bug with "autolock" option.

**Comment by john-preston** [comment]
@Kylmakalle Yes, this is a bug in the latest alpha version. Sorry about that.
