### ISSUE TITLE
[Feature request] Add an ability to go to the beginning of a chat

### ISSUE THREAD

**Issue by AleksSenkou** [telegramdesktop/tdesktop#3659]
What do you think about being able to go to the beginning of a chat by clicking on `Go to start` button or something? Such button can be located in chat menu.

![image](https://user-images.githubusercontent.com/3635774/28178801-62056610-6808-11e7-9fef-676a7b169093.png)

**Comment by MasterGroosha** [comment]
But why? Anyway, there're 2 solutions (well, more or less):
1) If it is a public supergroup with `@username`, just visit t.me/username/1 (replace "username" with your group's one). This will lead you to the first message of supergroup after converting it from normal group.
2) Use "search by date" feature and set the lowest date possible (August 2013).

**Comment by AleksSenkou** [comment]
@MasterGroosha good to know both solutions. Thank you
