### ISSUE TITLE
[Bug] It doesn't modifies properly the last message (if it is an image comment)

### ISSUE THREAD

**Issue by khvilaboa** [telegramdesktop/tdesktop#3660]
### Steps to reproduce
1. Write a message.
2. Insert an image and put a comment on it.
3. Press the 'edit the last message' shortcut (up arrow).

### Expected behaviour
A dialog to edit the last message appears (image comment).

### Actual behaviour
It allows to edit the message previous to the image.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.1.9

**Used theme**: Default

</details>

**Comment by stek29** [comment]
#2073
