### ISSUE TITLE
Escape button couldn't close full screen previewer after Alt-Tab on Fedora 26

### ISSUE THREAD

**Issue by NTMan** [telegramdesktop/tdesktop#3664]
### Steps to reproduce
1. Open some picture in full screen mode 
2. Press Alt-Tab
3. Escape button now couldn't close full screen previewer

### Expected behaviour
Full screen previewer must closed

### Actual behaviour
Esc work with application which is opened under the previewer

### Configuration
**Operating system:** Fedora 26

**Version of Telegram Desktop:** 1.1.13 Alpha

**Used theme**: No

**Comment by Aokromes** [comment]
#3144
