### ISSUE TITLE
Sync with native contacts on Windows 10

### ISSUE THREAD

**Issue by Christoph142** [telegramdesktop/tdesktop#3665]
Telegram should (optionally?) sync to native contacts on Windows 10.
It'll open up usage via "People" in the fall update.

**Comment by Scvairy** [comment]
And share feature integration would be nice. 👍

**Comment by Milording** [comment]
I'm not sure it's possible in non-UWP apps.

**Comment by Scvairy** [comment]
https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-extensions

Nothing is impossible. 😉

**Comment by cawa-93** [comment]
+1
Integration with the "People" application sounds amazing!
