### ISSUE TITLE
"Switch chat" inline button bug

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#3667]
### Steps to reproduce
1. User uses bot in inline-mode.
2. Bot shows him "switch_pm" button as one of results.
3. User clicks on this button.
4. A chat with bot is opened and bot sends user a message with "switch_inline_query" button.

### Expected behaviour
Nothing should happen, Telegram waits for user's input.

### Actual behaviour
User is immediately returned to previous chat with inline query.
To view this bug in action, open any chat (f.ex. with yourself) and use `@langbot` with any "weird" query such as `@langbot asdasdaddasadasdsa`, then click on that emoji. You'll notice moving to chat with `@langbot` then you're immediatety returned to your previous chat with empty inline query.

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.1.13 alpha

**Comment by john-preston** [comment]
@MasterGroosha As I understand this is an expected behaviour. At least the android app works the same. This is what switch_inline_query button does after switch_pm button.

**Comment by MasterGroosha** [comment]
@john-preston Well, Android app doesn't immediately switches back to original chat, but stays in chat with bot.
Telegram Desktop, however, shows chat with bot for a moment then automatically switches to original chat. Why moving user back if he hasn't pressed any buttons yet?

Tested on Android 4.1.1 (build 1030).

**Comment by john-preston** [comment]
@MasterGroosha A message with switch_inline_query button should be sent in response to whatever information bot got from user - it is used to switch the user back to the chat where he came from.

I tried on Android and it switched me back automatically. Perhaps desktop does it in some cases Android does not?..

**Comment by john-preston** [comment]
@MasterGroosha On Android it doesn't switch you immediately, but really it does :) as soon as you touch the screen in any place.

**Comment by MasterGroosha** [comment]
@john-preston 
> as soon as you touch the screen
Wow, didn't notice that before.

Anyway, it it the correct behaviour? Having one "switch_inline_query" button in keyboard prevents users from using all other buttons. "switch_inline_query" should __allow__ user to choose chat where to initiate inline-mode, not fire automatically upon recieving keyboard with it, right?

**Comment by john-preston** [comment]
@MasterGroosha Not right 😔

The correct behaviour is another:

1. first the bot sends you the buttons / questions / whatever.

2. then bot gathers all the information he needs in one or several messages from you (or zero, just buttons being pressed).

3. finally bot sends you a message with switch inline button that immediately upon being received sends you back to the chat you came from with a substituted inline query that may depend on data bot received from you.

You may walk through this mechanic with the official @like bot.

**Comment by MasterGroosha** [comment]
Sure, but what about the situation when bot tells about its features on `/start` command and advises to use it in inline mode by switching to another chat (that's a common usage, btw). That's exactly how `@langbot` and many other bots behave.

Since "switch_pm_parameter" acts like a "deep-linking" (adding hidden arguments to `/start` command), the situation described above is even more common.

Anyway, if you say it's not a bug, then it's not a bug :)
