### ISSUE TITLE
No indication of edited messages in channels with "Sign Messages" option

### ISSUE THREAD

**Issue by nyuszika7h** [telegramdesktop/tdesktop#3669]
### Steps to reproduce
1. Create a channel with the "Sign Messages" option enabled.
2. Post a message in the channel.
3. Edit the message you posted (or have someone else with the "Edit messages of others" permission edit it).

### Expected behaviour
It should show "edited" on the post, just like on Android, and just like Telegram Desktop also shows when "SIgn Messages" is disabled.

### Actual behaviour
No indication that the post was edited at all. This is especially concerning because admins can edit messages of others even in channels with "Sign Messages" enabled. Ideally, this should either not be allowed, or it should clearly indicate it was modified by someone other than the original poster. But that's a server-side issue.

### Configuration
**Operating system:** Windows 10 Home x64 (Creators Update)

**Version of Telegram Desktop:** 1.1.13 alpha

**Used theme**: Default (Night mode)

**Comment by MasterGroosha** [comment]
This is also fixed in 1.1.14 alpha
