### ISSUE TITLE
Use git tags for releases

### ISSUE THREAD

**Issue by emvigo** [telegramdesktop/tdesktop#367]
Hi,
I think this source tree would need some git tags for marking releases. This would help downstream package mantainers build their packages from source in more automated ways; it would make this amazing piece of software available to more Linux users.

**Comment by athos-ribeiro** [comment]
+1

**Comment by Duncaen** [comment]
This would be very helpfull

**Comment by auchri** [comment]
I'll try to add tags to the commits

**Comment by auchri** [comment]
@Duncaen I've added tags to the latest releases
