### ISSUE TITLE
Ordering: not muted first

### ISSUE THREAD

**Issue by p0123n** [telegramdesktop/tdesktop#3672]
Hi guys, I want to suggest feature request. When too much of channels in the messenger it's too hard to find updated channels. 
So, what if not muted channels will be first in list after pinned channels?

**Comment by RememberTheAir** [comment]
Open the settings and type `workmode`. An option will appear at the top of your chats list to hide muted chats, which is kinda what you're looking for

**Comment by p0123n** [comment]
Nice! But how can I enable this mode in Android app?

**Comment by RememberTheAir** [comment]
@p0123n you can't

**Comment by stek29** [comment]
#2440.
Second result for `is:issue non muted first`
