### ISSUE TITLE
UI Bag in workmode

### ISSUE THREAD

**Issue by loveengine** [telegramdesktop/tdesktop#3673]
### Steps to reproduce
1. Enable workmode.
2. Minimize dialogue window.

### Expected behaviour
Messages overlap each other

### Actual behaviour
In workmode button must be Ellipsis with quantity of messages

### Configuration
Win 10 LTSB
TDesktop Alpha 1.1.13
![image](https://user-images.githubusercontent.com/29382541/28310190-4cbf9096-6bb4-11e7-9472-3db86614f4cf.png)

**Comment by john-preston** [comment]
@loveengine Workmode is an internal not official feature, who told you about it 😆

**Comment by stek29** [comment]
@john-preston Source code? 
Also, iirc TSF sometimes may offer users to try workmode when they're complaining about lack of chat organization.

**Comment by stek29** [comment]
#2884
