### ISSUE TITLE
Channel share button overlaps with reply

### ISSUE THREAD

**Issue by OctoNezd** [telegramdesktop/tdesktop#3675]
### Steps to reproduce
1. Reply to message in channel with sticker

### Expected behaviour
Buttons dont overlap

### Actual behaviour
![image](https://user-images.githubusercontent.com/15308404/28335002-95e6b744-6c05-11e7-8fd2-f9d511a5c697.png)

### Configuration
**Operating system:**
Antergos Linux x86_64
**Version of Telegram Desktop:**
1.1.13 alpha

**Comment by MasterGroosha** [comment]
This is fixed in 1.1.14 alpha
