### ISSUE TITLE
Option to disable link previews by default

### ISSUE THREAD

**Issue by lindhe** [telegramdesktop/tdesktop#3676]
If I type a link in the message field and wait a second there will be a link preview that obscures the message. It can currently be turned off by clicking the X when the preview loads, but that's too much work to to it for all messages. I'd really want to see an option to turn it off by default.

**Comment by stek29** [comment]
@auchri this is about disabling link preview generation for sent messages, not for the received ones.

**Comment by lindhe** [comment]
In that case, I guess it's a dup of issue #839, but that in turn has been marked as a dup of #687 which does not seem like the same issue, which leaves me a bit confused.
