### ISSUE TITLE
When building a preview for a webpage with multiple images, use the first image instead of the last

### ISSUE THREAD

**Issue by BoffinbraiN** [telegramdesktop/tdesktop#3679]
### Steps to reproduce
1. Find any Imgur gallery or Twitter tweet containing 2 or more pictures.
2. Copy a link to the gallery or tweet into Telegram and send it.

### Expected behaviour
The link preview should contain the first image.

### Actual behaviour
Telegram always uses the last image instead.

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.1.10

**Used theme**: N/A

Telegram's behaviour of picking the last image in a collection is at best confusing, and at worst it can even be a spoiler if linking to a comic.

Bonus points if the client can show info about additional images in the preview, such as showing the first image and then a "+2" beside it if there are two more images. That way, people will know that there is more to see, and decide whether to open the link.

Note that this appears to happen in all Telegram clients, including Android and Web. I don't know if previews are built on the server or client side, so this bug may need to be forwarded to another project if it's a server-side feature.

**Comment by john-preston** [comment]
@BoffinbraiN Yes, the previews are prepared by server, sorry. I'll inform a guy about that, but there is nothing that can be done in this repository.

**Comment by BoffinbraiN** [comment]
@john-preston OK, thanks. If a new ticket is made in core Telegram, can you link me to it please?

**Comment by stek29** [comment]
@BoffinbraiN Even if he does you won't be able to view it: Telegram has private "ticket" system (and sometimes they don't even use those systems afaik).

**Comment by BoffinbraiN** [comment]
Oh okay, I forgot the back-end is closed-source. Sad, but it makes sense.
