### ISSUE TITLE
hide link image and not visible to click in text - Telegram

### ISSUE THREAD

**Issue by p1rralho** [telegramdesktop/tdesktop#3683]
I'm trying to post a non-channel image that displays below the text message, I do not want it to display the hidden link in characters (if they click). It's possible?

step 1) post in bot: Item circled in yellow:
http://telegra.ph/file/32c0121526f8cd36885f2.png

step 2) after post in channel, is possible click and visible link (I do not want to display the link in post)
http://telegra.ph/file/8e11dd7bb8ebb028ab7ba.png

thanks

**Comment by stek29** [comment]
This is not related to TDesktop.
Try adding the link to some characters like zero width space.
