### ISSUE TITLE
Banning a user in supergroup remove it from the group and "unban" doesn't work to return them back!

### ISSUE THREAD

**Issue by puraminy** [telegramdesktop/tdesktop#3686]
### Steps to reproduce
1. In a supergroup go to Manage Ban Users
2.  click on "Ban User" and ban someone (X), it notifies that "X was removed!"
3. go to Manage Ban Users, the user X is listed, click "Unban user"

### Expected behaviour
Tell us what should happen
The user X should be added to the group

### Actual behaviour
Tell us what happens instead
The user has been removed and the action doesn't add it back

### Configuration
**Operating system:**
Windows 8.1

**Version of Telegram Desktop:**
1.1.10

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@puraminy This is intended. The unban only lets the user join via invite link or for regular group users to add him.

**Comment by Aokromes** [comment]
close? :)
