### ISSUE TITLE
Telegram Desktop - Collapse window when sticker panel is closed

### ISSUE THREAD

**Issue by XanGit** [telegramdesktop/tdesktop#3688]
Telegram 1.1.10 on Windows 7/64 desktop version

When I open the sticker panel (by clicking the Smilie Icon) the Telegram window automatically grows to show the sticker panel to the right. 

However if I close it again (by again clicking the Smilie) the window width stays the same and I have to manually resize (shrink) it to have the same size as before.

So I would like to make an enhancement request: auto-collapse the window if sticker panel is closed or add a button/shortcut to bring the window to a specific (minimal) size

**Comment by MasterGroosha** [comment]
I think this is fixed in 1.1.24 alpha. At least for me now window shrinks back automatically.
