### ISSUE TITLE
Unable to compose characters in linux

### ISSUE THREAD

**Issue by brandonlujan** [telegramdesktop/tdesktop#3690]
### Steps to reproduce
1. While on the chat try pressing any set of two key compossing
2. Try the method described [here](http://fsymbols.com/keyboard/linux/compose/)

### Expected behaviour
It should enter a composite character, such as á, â, ™, ©, ǒ, etc.

### Actual behaviour
It shows the previous characters as a, a, tm, oc, co…

### Configuration
**Operating system:** elementary OS 0.4.1 Loki, Linux 4.10.0-27-generic, GTK+ 3.18.9

**Version of Telegram Desktop:** 1.1.10

**Used theme**: Original

**Comment by cranes-bill** [comment]
Can't reproduce it!
This is most likely system settings related issue. Does the other Qt apps are working correct on your system? 
Also, see [here](https://github.com/QupZilla/qupzilla/issues/2364#issuecomment-309260731) and you might try that!

**Comment by brandonlujan** [comment]
Attempted that and didn't work, turns out this issue is a duplicate of #1360 and I tried many things from there, putting `ibus-daemon` in the start programs worked (even althought ibus-daemon was running from the beginning, so that was weird). Thanks for the help!
