### ISSUE TITLE
refresh.bat error.

### ISSUE THREAD

**Issue by lianzisong** [telegramdesktop/tdesktop#3691]
### Steps to reproduce
1. execute the refresh.bat

### Actual behaviour
E:\Github\tdesktop\Telegram\gyp>refresh.bat
Traceback (most recent call last):
  File "E:\cmdbin\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "E:\cmdbin\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "E:\cmdbin\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "E:\cmdbin\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "E:\cmdbin\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "E:\cmdbin\gyp\pylib\gyp\generator\ninja.py", line 1692, in CalculateVariables
    gyp.msvs_emulation.CalculateCommonVariables(default_variables, params)
  File "E:\cmdbin\gyp\pylib\gyp\msvs_emulation.py", line 1094, in CalculateCommonVariables
    msvs_version = gyp.msvs_emulation.GetVSVersion(generator_flags)
  File "E:\cmdbin\gyp\pylib\gyp\msvs_emulation.py", line 945, in GetVSVersion
    allow_fallback=False)
  File "E:\cmdbin\gyp\pylib\gyp\MSVSVersion.py", line 485, in SelectVisualStudioVersion
    raise ValueError('Could not locate Visual Studio installation.')
ValueError: Could not locate Visual Studio installation.
FAILED

### Configuration
**Operating system:**
win10

and I install the python 2.7. and visual studio 2017.
I don't know why the pyg can't locate it.
Can't pyg support the vs 2017?

please help me.

**Comment by stek29** [comment]
I guess you should have gyp in your path and run refresh.bat not in cmd, but in console window started from vs folder in start menu. Haven't read the instructions in a while though.

**Comment by john-preston** [comment]
@stek29 I didn't test it on vs2017, I think it won't work without fixes.

**Comment by lianzisong** [comment]
@stek29 I tried execute the refresh.bat in the "developer command prompt" cmd line  ,but it still report the same error.

**Comment by lianzisong** [comment]
@john-preston So ,I have no choice but switch to  the vs2015 ?

**Comment by stek29** [comment]
@lianzisong you can try an updated version of GYP I guess.

**Comment by lianzisong** [comment]
@stek29 
i'm sure I use the latest version of GYP.

**Comment by stek29** [comment]
Oh, looks like Python gyp doesn't support vs2017 indeed...
I wonder if node-gyp would work with TDesktop...

**Comment by lianzisong** [comment]
@stek29 
thanks for your information.
And waht should i modify  the bat to make it use  the node-gyp?

**Comment by stek29** [comment]
@lianzisong sorry, I can't help you with that :(

**Comment by lianzisong** [comment]
@stek29 it's ok..thanks anyway.

**Comment by lianzisong** [comment]
@stek29 @john-preston 
I modify the refresh.bat , set GYP_MSVS_VERSION=2017(default is 2015) .
then it works with no errors.
So I close this issue .

**Comment by stek29** [comment]
@lianzisong does it build and run properly?

**Comment by lianzisong** [comment]
@stek29 
I don't know yet ,My compile environment is not ready yet.

**Comment by lianzisong** [comment]
@stek29 
I'm blocked by the QT configure .
I install the QT vs-addin plugin ,then open the Telegram.sln in the VS 2017,  the vs seems can't switch this project into the QT project .
And I don't know how to configure it  by manual .
So I don't know the build result.

**Comment by chenyu1990** [comment]
[issues#8195](https://github.com/telegramdesktop/tdesktop/issues/8195)
