### ISSUE TITLE
No channels in QuickShare menu

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#3692]
### Steps to reproduce
1.  Open channel
2.  Click on "QuickShare" button near the post
3.  Try to find any channel

### Expected behaviour
There should be channels the user is available to forward messages to (just like on Android/iOS)

### Actual behaviour
There're only groups/users in list.

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.1.14 alpha

**Comment by john-preston** [comment]
Thanks for the report.
