### ISSUE TITLE
Downloading of files, stalls just as the file is about to finish downloading.

### ISSUE THREAD

**Issue by DonMatano** [telegramdesktop/tdesktop#3695]
**This may not happen to every single file I download but it has happened to me for more than five times already.**

### Steps to reproduce
1. Press the Download file from Telegram. The file can be of any size but it seems to increase in possibility of the bug occurring when the file get's bigger.

### Expected behaviour
Download the file to completion as long as the is network.

### Actual behaviour
The file downloads well till it's just about to finish, like a couple of kBs remaining, then it just stalls. The net is still available because I can download other files and chat.

### Configuration
**Operating system:**
Linux Mint 18. Also my friend's Telegram in Ubuntu distro also experienced the same problem. Maybe Ubuntu based distro oriented
**Version of Telegram Desktop:**
1.1.10
**Used theme**:
Not sure what you mean, Custom Theme?????

**Comment by ratansingh98** [comment]
Same with me. Devs please help.

**Comment by arisboch** [comment]
I've got the same problem, especially with BIG files, such a pain! Please help!

**Comment by Giando** [comment]
Same issue.

**Comment by arisboch** [comment]
Thanks to the newest update, it's all OK at least at my end.

**Comment by cristian64** [comment]
I keep encountering this issue every now and then. Today I saw it in 1.5.4.

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by Giando** [comment]
> this issue is still valid on 1.9.8?

As a rule no, it has been fixed since July 2018.
