### ISSUE TITLE
Neither @mentions, nor formatting works when pasting an image

### ISSUE THREAD

**Issue by ExecThTs** [telegramdesktop/tdesktop#3696]
### Steps to reproduce
1. Paste an image into the chat
2. Type any text and try to @mention anyone, or use the new `__formatting__` features
3. The @ key doesn't pop up the userlist. When you send the message, the text isn't formatted

### Expected behaviour
The mention- userlist should pop up in the Image Caption window too. Also the formatted text should display appropriately.

### Actual behaviour
The features mentioned above do not work.

### Configuration
**Operating system:**
Xubuntu 17.04, Arch Linux, Windows 10

**Version of Telegram Desktop:**
1.1.15

Trying to get log files did not succeed -- the log files were not created.

**Comment by stek29** [comment]
API issue and a duplicate.

**Comment by ExecThTs** [comment]
Searched for "mentions" in open issues, didn't find any at first glance. Also, how could be a GUI issue be an API issue?

**Comment by stek29** [comment]
@ExecThTs mentions in captions work just for usernames, and are always parsed on each client unlike mentions in messages, because caption is raw string.
But not showing autocomplete is a duplicate, I think.

**Comment by stek29** [comment]
Ok, I was unable to find it either.
So, formatting is an API issue, and mentions are API issue too, strictly speaking.

However, other apps do have autocompletion for captions. I'd recreate issue for it and close this one, if you don't mind. See #3783.
