### ISSUE TITLE
Telegram needs an additional option to works with OPUS

### ISSUE THREAD

**Issue by cranes-bill** [telegramdesktop/tdesktop#3697]
### Steps to reproduce
1. Select any contact name
2. Click on _microfon_ icon

### Expected behaviour
I'm not sure, what should happen
(I'm newbie with Telegram)

### Actual behaviour
Happens nothing, but i'm receiving the following mesage on the terminal:

`[opus @ 0x7fe0ac026480] The encoder 'opus' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.`

### Configuration
**Operating system:** Linux

**Version of Telegram Desktop:** 1.1.14 Debug (self compiled)

**Used theme**: default

**Comment by john-preston** [comment]
@cranes-bill Does it happen in the official build from https://desktop.telegram.org?

**Comment by cranes-bill** [comment]
>  Does it happen in the official build from https://desktop.telegram.org?

Nope, it works there.

**Comment by john-preston** [comment]
@cranes-bill Then I guess you should build it some other way.

**Comment by stek29** [comment]
@cranes-bill have you followed instructions?

> ./configure ... --enable-libopus ... --enable-decoder=opus ... --enable-muxer=opus

**Comment by cranes-bill** [comment]
@stek29, It is built with system opus library as well as ffmpeg.
@john-preston, OK. i'm closing the issue.
