### ISSUE TITLE
Bold doesn't work with Hebrew font in desktop version of Telegram

### ISSUE THREAD

**Issue by RandallFlagg** [telegramdesktop/tdesktop#3698]
### Steps to reproduce
1. Write a message like this: 

> `**שלום**`

### Expected behaviour
The text should look like this: **שלום**

### Actual behaviour
The text looks like this: שלום

### Configuration
**Operating system:**
windows 10

**Version of Telegram Desktop:**
1.1.15

**Used theme**:
default

<p><b>Some more info</b>:
This can be solved if fonts could be changed by the user

</details>

**Comment by Wasnix** [comment]
Dito with builtin-fonts and Linux UTF-8 (latin charset). I've found this error message in log.txt:

`Font Error: could not resolve 'Open Sans Semibold' font, got 'Open Sans' after feeding '%3'.`

Operating System: Linux Debian 10 (buster) 
Version of Telegram Desktop: 1.1.15
German language.

**Comment by Aokromes** [comment]
#2128 generic bug?
