### ISSUE TITLE
"Forwarded from" tag bug

### ISSUE THREAD

**Issue by Kylmakalle** [telegramdesktop/tdesktop#3699]
### Steps to reproduce
1. Forward message from supergroup to supergroup/private
2. Quit from Telegram Desktop (Ctrl+Q)
3. Launch Telegram again and navigate to the forwarded message

Video: https://my.mixtape.moe/xlilub.mp4

### Expected behaviour
Forwarded from _%%user%%_

### Actual behaviour
Forwarded from _%%supergroup_title%%_

### Configuration
**Operating system:**
Win 10 x64
**Version of Telegram Desktop:**
1.1.15

**Comment by nyuszika7h** [comment]
> Note: Forwarded from %%user%% will be shown if message forwarded TO private group

I can't reproduce that part, this problem also happens in that case for me.

**Comment by Kylmakalle** [comment]
@nyuszika7h Well, behaviour is a bit strange, seems like it's something about client and server Sync, removed that note.

**Comment by stek29** [comment]
@Kylmakalle client generates forwarded tag on his own when it's forwarding a message. When it loads a message which wasn't loaded already, it parses fwd header from server.

**Comment by john-preston** [comment]
Thanks for the report.

**Comment by arieljannai** [comment]
It doesn't have to be forwarded from a supergroup, the same happened to me when forwarding from a normal group to a private chat
