### ISSUE TITLE
Forwarding is broken

### ISSUE THREAD

**Issue by reverendhomer** [telegramdesktop/tdesktop#3701]
### Steps to reproduce
1. Write message to one chat
2. Forward this message to another chat
3. Look at "Forwarded from" label

### Expected behaviour
You will see "Forwarded from %yournickname%"

### Actual behaviour
You see "Forwarded from %nick_of_first_chat%"

### Configuration
**Operating system:**
Fedora 26

**Version of Telegram Desktop:**
1.1.15

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by reverendhomer** [comment]
I think this is kind of duplicate of #3699, but I'm not sure.

**Comment by stek29** [comment]
It's it's pair
