### ISSUE TITLE
[Enhancement] Shortcut for changing focus to "Search" contant's field

### ISSUE THREAD

**Issue by jenkokov** [telegramdesktop/tdesktop#3703]
*Current*: Should use a mouse to found contact/group from the contact list. 
*Feature*: Use shortcut like **Ctrl+J** (jump) or **Ctrl+T** to move focus to **"Search"** field above the contact list, without enabling searching in current chat. 
*Also*: Shortcut like **Alt+Shift+Down/Up** for "Jump to next unread conversation"
Related to: #1060

**Comment by stek29** [comment]
Esc + Ctrl+S?

**Comment by jenkokov** [comment]
Oh, I see now. So easy to do... so hard to find a shortcut, lol. I'll close this issue.
