### ISSUE TITLE
[Enhancement] Add option to not display notifications when in fullscreen app

### ISSUE THREAD

**Issue by emzero** [telegramdesktop/tdesktop#3706]
It would be great if Desktop Telegram included an option to not display notifications when in a fullscreen app like a video or game.

**Comment by stek29** [comment]
OS?

**Comment by emzero** [comment]
I use Windows 7, but I think it could be an useful feature on any platform.

**Comment by Trost123** [comment]
Bump.
Quite annoying when you play a game after a freelance workday, just to get a notification on top of it, accidentally click it. Then you disable notifications and forget to re-enable them the next day, missing messages. (#3684 could help here too)

**Comment by auchri** [comment]
Just enable the native system notifications, should work there.

**Comment by Trost123** [comment]
Is that an OS setting or Telegram setting?
Can you clarify how to do this in Win 7?

**Comment by auchri** [comment]
Yes, upgrade to Windows 10 and enable the "Windows notifications" in the settings.

![image](https://user-images.githubusercontent.com/5092164/30313290-1a7dfb8a-979d-11e7-8b9c-86847397e473.png)

**Comment by Aokromes** [comment]
#2290
