### ISSUE TITLE
***** becomes *

### ISSUE THREAD

**Issue by rehacktive** [telegramdesktop/tdesktop#3713]
### Steps to reproduce
1. Write on any conversation ***** (5 times "*")
2. Send it
3. You will see just one *

### Expected behaviour
Tell us what should happen
You should see *****

### Actual behaviour
Tell us what happens instead
You see *

### Configuration
**Operating system:**
OsX
**Version of Telegram Desktop:**
1.1.15
**Used theme**:
dark
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by AliSawari** [comment]
Yeah that's true , same here

**Comment by AliSawari** [comment]
and also seven of ` (backtics) will be a single on

**Comment by AliSawari** [comment]
I guess that's because of the markdown feature :thinking:

**Comment by sovietspaceship** [comment]
yes lol

**Comment by nyuszika7h** [comment]
Yeah, there's no way to escape formatting characters in the official clients as far as I know. In the bot API, single `*` and `_` are used and you can escape them with a backslash (`\`). You can use `@bold` in inline mode with the "Custom Markdown" option. Note that inline bots' responses are limited to 512 characters.

There's another caveat: you can't escape triple backticks as far as I can tell. If you need an even amount of triple backticks inside monospace text, you can use `@bold` with the "Fixedsys" option. But that won't work for an odd amount. Bot API allows HTML which is straightforward, so you could use a HTML formatting bot and escape special formatting characters as HTML entities (I don't know any existing ones off the top of my had).

**Comment by Lonami** [comment]
This is because Telegram Desktop is using `**` (and `__`) as delimiters when entering **bold** and *italics* text as @AliSawari said (markdown feature). So it's not actually a bug, `*****` is just `**` around `*` → <code><b>*</b></code>.

**Comment by stek29** [comment]
#2683
