### ISSUE TITLE
Codenames for flag emojis are wrong.

### ISSUE THREAD

**Issue by D3sl0nG3r** [telegramdesktop/tdesktop#3715]
### Steps to reproduce
1. Try to text an emoji, lets say ukrainian flag. Type :flag_ua
Same happens with US flag, etc.

### Expected behaviour
Must show correct flag for Ukraine

### Actual behaviour
It shows you flag of UAE. Code of UA flag was :flag_ua, now its flag_ug.

### Configuration
**Operating system:**
Xubuntu 
**Version of Telegram Desktop:**
1.1.16 alpha
**Used theme**:
Default theme

![image](https://user-images.githubusercontent.com/11181091/28639874-5cee4a58-7252-11e7-8901-f2260346e7a1.png)

**Comment by john-preston** [comment]
@D3sl0nG3r Yeah, bug in Linux version indeed 😰

**Comment by john-preston** [comment]
@D3sl0nG3r Should be fixed in 1.1.17 version.
