### ISSUE TITLE
Emoji broken in 1.1.16 in linux build

### ISSUE THREAD

**Issue by maratik123** [telegramdesktop/tdesktop#3718]
### Steps to reproduce
1. Update to 1.1.16 version
2. emoji flag for cyprus changed to another country (it also happened with other flags)

**Comment by maratik123** [comment]
duplicate of https://github.com/telegramdesktop/tdesktop/issues/3715

**Comment by john-preston** [comment]
@maratik123 It should be fine in 1.1.17 version.
