### ISSUE TITLE
Paste text when I press ctrl+c.

### ISSUE THREAD

**Issue by aseredenko** [telegramdesktop/tdesktop#372]
This function doesn't work in Ubuntu client

**Comment by telegramdesktop** [comment]
Good news!

I hope to move to Qt 5.4 one day.

**Comment by adisos** [comment]
bump :)

**Comment by Katzen-Gott** [comment]
Looks like it's fixed since v 0.7.14 dev (12.02.15). Please check.

**Comment by adisos** [comment]
I confirm, v 0.7.17 working properly

**Comment by Katzen-Gott** [comment]
Looks like only reporter ( @aseredenko ) or repository owner ( @telegramdesktop ) can close the issue...

**Comment by aseredenko** [comment]
@Katzen-Gott Yes. This feature works great!
