### ISSUE TITLE
Field for comment at quick share

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#3720]
1. Go to channel or supergroup. Choose any message or post.
2. Click on Quick Share button.
3. Choose recepient. Just push Send... No possibility to write a comment near recepient's username. 

While Android client has field for comment. It appears after I've choose recepient.

Telegram Stable 1.1.16, Win 8.1 x64.

**Comment by MasterGroosha** [comment]
There is **no** "comment" field, it's a list of recepients with integrated search field to help you find repecients better.

**Comment by Twilightssuperb** [comment]
Oh, sorry. But at Android client I can type a comment when I use Quick Share button... I need it so much at Windows desktop version.

**Comment by MasterGroosha** [comment]
@Twilightssuperb I understand you, but that's a feature request, not "QuickShare is broken"

**Comment by Twilightssuperb** [comment]
Well, I've just renamed issue. My fault is I don't see into Quick Share button interface and thought that comment field **is already** implemented. I was wrong. Maybe, @auchri should give new label to #3720. 🙂

**Comment by 23rd** [comment]
5f665b8ecb48802cd13cfb48ec834b946459274a
