### ISSUE TITLE
[Feature request] New emoji system should show a stickers panel related to the visible possible emojis

### ISSUE THREAD

**Issue by oxydron** [telegramdesktop/tdesktop#3723]
Every sticker is linked with one or more emojis. Why not show them too while typing for an emoji?

1. type `:<anyting>`
2. possible emoji show (and emoji linked stickers)

### Expected behaviour
Show emoji and stickers panel while typing the two-dot emoji code

### Actual behaviour
Only show emoji

### Configuration
**Operating system:**
Ubuntu 16.04

**Version of Telegram Desktop:**
1.1.17a

**Comment by john-preston** [comment]
@oxydron You can complete the emoji and see the stickers in 1.1.18 version.
