### ISSUE TITLE
No autostart in Windows Store version

### ISSUE THREAD

**Issue by niks255** [telegramdesktop/tdesktop#3724]
Telegram Desktop from Windows Store doesn't run on system startup. It's just not implemented at all.
It is possible to do. See here: https://blogs.msdn.microsoft.com/appconsult/2017/02/23/supporting-launch-at-startup-in-a-desktop-app-converted-with-the-desktop-bridge/

**Comment by flippinger** [comment]
see #3234

**Comment by cryptochrome** [comment]
1.5 years later, this is still not implemented.

**Comment by aflyhorse** [comment]
3 years later, this is still not implemented.
