### ISSUE TITLE
Telegram automagically adds new contacts which are not in the contact list of my smartphone

### ISSUE THREAD

**Issue by vrubleg** [telegramdesktop/tdesktop#3725]
A year ago my SIM card was broken and I had used a SIM card of my friend to check if my phone works. Telegram remembered all contacts from this SIM card and made some kind of shadow copy of them, because I can't see these contacts anywhere, but Telegram constantly adds new contacts every time when someone from contacts of my friend joins Telegram.

### Expected behaviour
Telegram has to add new contacts automatically only for phone numbers which are in your actual phone numbers list.

### Actual behaviour
Telegram remembers all numbers which Telegram had seen from the beginning of time.

**Comment by auchri** [comment]
Not related to Telegram _Desktop_.

However, you have to delete the contacts inside the Telegram Android app.

**Comment by vrubleg** [comment]
But these contacts are not displayed in the Telegram Android while these persons are joined Telegram. You can remove only that people which already joined, but not all collected contacts.

Where can I file a ticket about Telegram in general?

**Comment by poige** [comment]
Telegram, you start to suck in terms of support I have to admit.

**Comment by snake302** [comment]
Same problem here

**Comment by mostm** [comment]
+1

**Comment by qoops-1** [comment]
+1
