### ISSUE TITLE
Can't install lzmalib

### ISSUE THREAD

**Issue by GsHeri** [telegramdesktop/tdesktop#3729]
### Steps to reproduce
1.  open VS2015
2.  File -> open -> file -> (...)/lzma/C/Util/LzmaLib/LzmaLib.dsw

### Actual behaviour
The project/Solution isn't loaded.
Unidirectional Update opens, i click ok. 
Solution LzmaLib is shown with (0 Projects)
I have not found a way to fix this. Tried LOTs of times. 
even reinstalled VS2015 (14.0.25431.01 U3)

log says 

LzmaLib.sln: Visual Studio needs to make non-functional changes to this project in order to enable the project to open in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without impacting project behavior.
--
  | LzmaLib.sln: File successfully backed up as C:\Projects\TBuild\Libraries\lzma\C\Util\LzmaLib\Backup4\LzmaLib.sln
  | LzmaLib.sln: Solution migrated successfully

but like i said.. solution is empty, there are no properties and no settings i can change.
I also tried to open the .vcxproj, which actually shows the project, but also no settings to be changed and nothing to be done. i guess there must be something really wrong in the way i'm doing it...

### Configuration
**Operating system:**
win10

Can i skip this part? or is there a "working" project? Or is it... working as expected?
I don't know what to do. any help will be appreciated!

thanks

**Comment by auchri** [comment]
@GsHeri How is building lzmalib related to Telegram Desktop?

**Comment by GsHeri** [comment]
well maybe it's not "building"... i'm referring to https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md#building-library (they call it building :D )

**Comment by auchri** [comment]
@GsHeri then you should ask at the lzmalib project

**Comment by GsHeri** [comment]
well since it's part of the tutorial i guess somebody should know how to handle this (or better: i didn't expect something to go wrong, so maybe it's a simple thing i overlooked due to missing experience).
if nobody around here knows what to do with this, i guess i'll have to ask over there :)
