### ISSUE TITLE
When maximizing in a multi-monitor setup, the window sticks out on the other monitor

### ISSUE THREAD

**Issue by gigaherz** [telegramdesktop/tdesktop#373]
I use Windows 7 x64, with two monitors, primary 2560x1440 and secondary 1920x1080. I often maximize Telegram Desktop on the secondary monitor.

What happens is that, if the window isn't maximized while it's 100% on the primary monitor, it has some sort of "leftover" of the unmaximized window on the edge of the other monitor. This can be seen in the attached screenshot:

![telegram-issue](https://cloud.githubusercontent.com/assets/685851/5575029/33d6f5be-8fd0-11e4-858b-ed2b3a985461.png)

Here, the red areas are not mapped to any monitor. I cropped to the area showing the issue for privacy reasons.

The same issue happens on the secondary monitor, when maximizing to the primary monitor while the window was not fully on the primary area.

**Comment by daedalus01** [comment]
I also see this issue, likely for as long as I've been using Telegram. Currently on version 0.8.13.

**Comment by docholiday** [comment]
Same here, but with the second monitor being placed above the one where Telegram is maximized.
There's a white stripe visible:
![telegram white stripe 2-monitor-setup](https://cloud.githubusercontent.com/assets/1399765/9026005/7422ccc2-391e-11e5-9b8e-455a67ac1e51.png)

As my monitors have different resolutions, it is very easy to see where the first one ends
(right with the Firefox tabs) and where the second one starts.

If it helps, my main screen has a resolution of 1600x900, the second has 1280x1024.

**Comment by techkid6** [comment]
:+1: Anyone?

**Comment by auchri** [comment]
I can't reproduce this.

**Comment by techkid6** [comment]
Here is a picture to show.  It happens in the exact situation that the original bug shows.  My monitors are (like in the description) two different resolutions.

I can't get github's uploader working properly so here is an image http://imgur.com/QbQkhfW

**Comment by gigaherz** [comment]
Just as a note: the issue stopped happening to me as soon as I upgraded away from Windows 7. This new installation of Windows 10 doesn't have the issue anymore. Because I had to do a clean installation shortly after I upgraded, I have no means to know if the issue was fixed in Windows after 7 (8/8.1), or if it was some incompatible software I had installed in the past.

I'll leave this open because it seems to happen to other people still.

**Comment by auchri** [comment]
@gigaherz That's possible, all uploaded screenshots are taken on windows 7! So it seems to be a qt/windows 7 bug.

**Comment by techkid6** [comment]
If that's the case I wonder if it's on the Qt tracker...

**Comment by daedalus01** [comment]
I previously had this issue when I was on Windows 7, but after upgrading to Windows 10, I don't seem to have it anymore. As of right now, i'm running the latest 0.9.13dev.

**Comment by telegramdesktop** [comment]
@daedalus01 Well, it is not Qt, but something in Windows. I use custom border less window and handle it directly by WinAPI calls almost without Qt, but I don't know, how to fix that in Win7, in 8 and above it seems to fix itself (in the system).

**Comment by msaadn** [comment]
I am experience this issue to date using dual monitors on Windows 7 x64.

**Comment by shenziro** [comment]
Same here on my Windows 7 x64. 
Is it possible to provide a configuration option that disables the borderless-rendering and let the program render normally using an Windows UI-Window as workaround?

**Comment by shalimski** [comment]
There was a problem, but in version 0.10.20 was fixed.

**Comment by Flexxxo** [comment]
Although this thread is closed now, it unfortunately this still applies on Windows 7 x64 even with latest client 1.1.23.

In fullscreen mode the Telegram window is overlapping onto the second screen (see white area in attached screenshot).

Nvidia GTX 1080 with latest drivers, two indentical 24 inch displays with 1920x1200 px. Telegram is fullscreen on the left display.

![bild_1_21102017-1139](https://user-images.githubusercontent.com/15352119/31850572-bcd32c68-b654-11e7-9102-df59cf6198fc.png)

**Comment by mathiaspl20** [comment]
Still applies on windows 10, build 17134.165 with tdesktop 1.3.10 (alpha) on a 3 monitor setup, all 1080p, one in widescreen mode, two in portrait. I had the monitors offset slightly: ![image](https://user-images.githubusercontent.com/20948508/42844666-0273a502-8a14-11e8-8d76-9c80358ae756.png)
what fixed my issue was aligning the bottom edges of the screens, applying the settings  and then going back to my original settings.

**Comment by housemobile** [comment]
> pretty sure it has to do with some offset, the bug only occurs when my displays are arranged like this:
> 
> ![grafik](https://user-images.githubusercontent.com/18307732/40497156-d128b4a0-5f7b-11e8-9752-3dd0699f5ac3.png)
> 
> there is no overlap when it looks like this:
> ![grafik](https://user-images.githubusercontent.com/18307732/40497194-ea5ac5a8-5f7b-11e8-92ce-f830c544b66f.png)

thanks! this seems to have fixed it!
