### ISSUE TITLE
Can not type classic ":p" or ":s" emoticon (and similar) without emoji selection popup

### ISSUE THREAD

**Issue by vdmkenny** [telegramdesktop/tdesktop#3730]
### Steps to reproduce
1. Type :p in a chat window
2. Emoji selection screen will pop up
3. Pressing enter will select a random emoji, in my case point_left.

### Expected behaviour
Pressing enter when :p is currently typed should send the string :p, or the corresponding emoji to this emoticon. This is the case with any simple emoticon which has a letter after the : character, and breaks expected behaviour from other chat clients, and is very annoying.

### Actual behaviour
An unwanted emoji is selected, in the case of :p, point_left is selected.

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 1.1.18

**Comment by tillove** [comment]
i have the same irritating issue  
both on Fedora25 and Win10

**Comment by sovietspaceship** [comment]
Disable "Replace emoji" in Chat settings

**Comment by john-preston** [comment]
@vdmkenny You can either disable the "Replace emoji" checkbox in Settings or you can type ":p", press Escape and then press Enter.
