### ISSUE TITLE
Any reason why you dump Windows in the trashcan?

### ISSUE THREAD

**Issue by dmxt** [telegramdesktop/tdesktop#3735]
We have professional Windows users and users want to use Telegram for end-to-end encryption conversations. You implemented it for Android, iOS, macOS, UWP and all other kinds of devices BUT Windows. Why?

I even wrote a blog how Windows is a fully viable operating system for designers and developers on [Medium](https://uxdesign.cc/designers-workflow-on-windows-57393856ae59) and it has been republished by uxdesign and Marvel.

**Comment by auchri** [comment]
@dmxt Because this app is for windows, mac and linux and it's not that easy to implement. However, there are other issues with better answers ;)
