### ISSUE TITLE
Allow to disable emoji-autocomplete

### ISSUE THREAD

**Issue by mbek** [telegramdesktop/tdesktop#3736]
As already discussed in #627 -- the autocomplete of emoi's can be highly annoying. 

### Steps to reproduce
1. Type a colon 
2. Type a + (a non-regular emoji, but used anyway)
3. Press enter to send the message
4. Send some-completely different emoji

or

1. Type a colon
2. Type an o (for :o)
3. Press enter
4. Send a completely unrelated smiley

This is highly annoying.

### Expected behaviour
I would expect to either:
1. Only match the exact smiley
or
2. Only match alpha-numeric smilies with atleast 2 chars after the colon
or
3. Be able to disable auto-completion

### Actual behaviour
It is annoying 😄

**Comment by john-preston** [comment]
@mbek You can disable it by disabling the Replace emoji checkbox in Settings. Also you can press Escape to hide the emoji autocomplete panel.

**Comment by RememberTheAir** [comment]
@john-preston what about `xD`, `:o`, `:-)` and so on? Using <kbd>ESC</kbd> doesn't work because there's no popup with suggestions while typing them (it works just for `:o` but only if not wrapped in spaces), they get always converted in emojis unless you wrap them between `, \_\_ or \*\* 

Is there a way to avoid that (I don't know, some sort of escaping) while keeping the emoji suggestions enabled?

**Comment by Priyantha** [comment]
To be honest, the previous 'system' used in Telegram, when you had the 'Replace emoji' checkbox checked worked great. If you typed ";-P" you got your tongue-emoji, which is exactly what you would want.
En if you did a ":o" you god a sad-blue-headed-emoji what's also exactly I would want.

But the new behavior is that there is an annoying pup-up suggestion screen without the possibility to disable it. It would be great to have thát particular function as a option.

**Comment by stek29** [comment]
@Priyantha #3738

**Comment by heaven** [comment]
I don't want to disable emoji replacement, I just want to get rid of this annoying popup, what are my options? There are people who use Telegram for work, not only for sending smiles.
