### ISSUE TITLE
ipv6 http links is not active

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#3737]
### Steps to reproduce
1. open chat
2. post link [http://[2a03:2880:f113:183:face:b00c:0:25de]](http://[2a03:2880:f113:183:face:b00c:0:25de])
3. click on it

### Expected behaviour
opens browser

### Actual behaviour
nothing happened

### Configuration
**Operating system:**
win10 x64 rs2
**Version of Telegram Desktop:**
1.1.18

**Comment by stek29** [comment]
Links are parsed on server side and locally, former has higher priority. 

Wait, it's not highlighted at all, or it is highlighted but doesn't work?

**Comment by f242** [comment]
@stek29 not highlighted at all

**Comment by stek29** [comment]
What about captions?

**Comment by f242** [comment]
@stek29 ipv6 link look like plain text, to open it i need to select, copy and paste in browser

**Comment by stek29** [comment]
@f242 then there are two issues: one in TDesktop (links are not parsed in captions/while message is sending) and one on Server Side (links are not parsed in normal messages and are not processed by server)

**Comment by john-preston** [comment]
I don't think there is a need to parse them locally before the server, because they still won't be clickable inside the messages, which is the most used case.

**Comment by ArmeF97** [comment]
+1 on this, one year has passed 😢

**Comment by ArmeF97** [comment]
why a closed "api issue"? maybe you mean an open "api issue"
@stek29

**Comment by stek29** [comment]
@ArmeF97 this is not a tracker for API issues, this is tracker for TDesktop.

You can contact in-app support, or ping telegram on twitter for api issues.

**Comment by ArmeF97** [comment]
Already tried, and also for other things, never worked...
I just asked (in my previous comment) because I can see some open "api issue" issues https://github.com/telegramdesktop/tdesktop/labels/api%20issue
