### ISSUE TITLE
Replace emoji settings (split into two)

### ISSUE THREAD

**Issue by Peque** [telegramdesktop/tdesktop#3738]
Currently there is an option to enable/disable "Replace emoji".

Considering that:

- Some people like the new `:emoji:` code replacement. But I do not like the `xD` to 😆 conversion (and alike).
- Some others do like the old replacements but do not like the new `:emoji:` code replacements.

Could the "Replace emoji" settings be split into two? One to enable/disable the former kind of replacement and another for the latter.

**Comment by john-preston** [comment]
@Peque I don't think this is a good idea. The division on the "old" and "new" will be strange and not understandable by almost anyone + the old replacements had some of the new ones too -- like the :like: or :v: ones. This will confuse everyone even more.

**Comment by Peque** [comment]
@john-preston Maybe the division could be represented in the settings name to make it clear. In example:

- Replace :emoji_codes:
- Replace :), xD, <3... emoji

**Comment by Entropy0** [comment]
@john-preston If I may add my opinion:
I was actually cunfused by the fact that the two _were_ connected: I had the replacement disabled (as I don't want to use it), but tried to use the ':'-codes and it took me quite a while to find out why they were not working - aside from it being unintuitive for me, this connection is undocumented.

As for reasons why these are two separate things:
One is essentially an Emoji-search, initialized by typing ':' and with accompanying preview in form of the drop-down, while the other is a basic search-and-replace _without indication anything is happening before you send the message_, which can be quite confusing.

**Comment by Peque** [comment]
@Entropy0 Good to know I am not alone with this. :smile:

@john-preston Hope you can consider this again. :heart:

**Comment by Priyantha** [comment]
A copy/paste from my comment on #3736 
--
To be honest, the previous 'system' used in Telegram, when you had the 'Replace emoji' checkbox checked worked great. If you typed ";-P" you got your tongue-emoji, which is exactly what you would want.
En if you did a ":o" you god a sad-blue-headed-emoji what's also exactly I would want.

But the new behavior is that there is an annoying pup-up suggestion screen without the possibility to disable it. It would be great to have thát particular function as a option.
--

It would be great if this feature could be implemented.
The current implementation is a regression in my view to the previous behavior.

**Comment by Peque** [comment]
@Priyantha In my case is exactly the opposite: I did not even start to use Telegram Desktop until there was `:emoji_code:` completion/replacement (I used webogram). The "classic" auto-replacement is a pain for me.

I think the only way to make everybody happy is to actually split the settings. :innocent: :thought_balloon:

**Comment by Priyantha** [comment]
@Peque Splitting the settings would be great I think yes :+1:

**Comment by holzit** [comment]
:emoji_codes: is great and I really missed it in Telegramm. I am used to it form using Mattermost
Are people using :following_some_text: that often that this is bothering people?
I would just like to disable the replacement with xD to 😆  things

**Comment by renatolond** [comment]
I would also like this to be splitted, in fact I came here to create an issue because the replacement was not working when I found (through other issues) that the issue was caused by me having disabled the classic replace emoji.
I like my "xD" to not be an emoji, but I'm also very attached to `:joy:` after using slack for so long :P

**Comment by Peque** [comment]
@john-preston Would you consider reopening this issue? :innocent:

**Comment by Priyantha** [comment]
@Peque that would be great if @john-preston would do this.

**Comment by elisaado** [comment]
Yeah this option would be quite handy :x

**Comment by HifeFish** [comment]
I would also like this issue to be reopened, for the following reason:

I would like to use colon suggestions, so I don't have to use the mouse to insert emoji.

Other than that, I want to send what I type. Automatic replacement of :o and such can change the tone of a message. This is especially bad because the replacement happens only after sending the message, and there is no way to revert it.

**Comment by Darkhogg** [comment]
Since autoreplace writing `xDDD` gets converted to `😆DD`, which is ANNOYING, and didn't happen before. All would be good if I could disable the non-colon replacements but keep the colon ones (which I use *exclusively*).

So, please separate the two types of replacement, thank you.

**Comment by john-preston** [comment]
@Darkhogg I think I'll change "xD" replacement to "xD ", like I changed ":o ", making space mandatory.

**Comment by Darkhogg** [comment]
Good enough for me, but still, please, think about the split. It would be very useful.

**Comment by d4em0n** [comment]
hello, i can't write '[2:]' in the message, because ':]' replaced to emoji, and there is no popup to disable emoji

**Comment by john-preston** [comment]
@d4em0n You can press backspace or Ctrl+Z or you can use backticks to write a monospace part of text without replacements, if you write `[2:] it won't be replaced and will be converted to monospace once you write second`.

**Comment by d4em0n** [comment]
thanks @john-preston, problem solved
