### ISSUE TITLE
Show emoji short codes on hover

### ISSUE THREAD

**Issue by jeyemwey** [telegramdesktop/tdesktop#3739]
As [emoji autocomplete](https://github.com/telegramdesktop/tdesktop/issues/627) (#627) was finally released with 1.1.16, I am seeking another feature request:

> When hovering on emojis in the emoji picker, the name/short code of the emoji should be shown, so you can use the autocomplete functionality the next time that you want to use it.

Would be great and should not be that much of a deal.

Also, there should be the option to turn off these tool-tips - if you want to, I heard some people don't like the autocomplete-feature (#3736).

**Comment by john-preston** [comment]
I think this can be added. I think the tooltips won't be shown when you disable "Replace emoji" checkbox in Settings.

**Comment by jeyemwey** [comment]
Sounds great to me!

Am 31.07.2017 11:11 vorm. schrieb John Preston <notifications@github.com>:

I think this can be added. I think the tooltips won't be shown when you disable "Replace emoji" checkbox in Settings.

**Comment by s-light** [comment]
seems that this was requested before: #743
or at least very similar...
