### ISSUE TITLE
Untie Emoji keyword completion from "Replace Emoji" setting

### ISSUE THREAD

**Issue by Entropy0** [telegramdesktop/tdesktop#3741]
I would very much like to use the ':'-code list for Emoji, as they are much faster than using the mouse to select them, but I also don't want emoticons like "xD" to get replaced without my say-so. 

(It took me a while to even find out that this was the reason the ':'-codes weren't working for me as I had this setting disabled and it is neither documented not intuitive that these two things are related)

**Comment by auchri** [comment]
@Entropy0 Did you search for duplicates before creating this issue?

**Comment by Entropy0** [comment]
@auchri I didn't find any direct copies, but it seems somewhat related to #3721

**Comment by stek29** [comment]
#3738

**Comment by Entropy0** [comment]
Whoops, I blame my lack of sleep yesterday for not seeing that one.

Closing this issue as duplicate,
