### ISSUE TITLE
[Enhancement] Option to disable unread messages counter for specific groups on desktop platform.

### ISSUE THREAD

**Issue by smekhovan8** [telegramdesktop/tdesktop#3744]
There are hundreds and thousands users in some Telegram groups. And in some of these groups are many of 'flood' messages. As a result, total counter of unread messages in taskbar on desktop Telegram version always shows 'over 9000' messages. It would be good to have a option to disable message counter for such groups.
Thanks. Sorry for my bad English.

**Comment by john-preston** [comment]
@smekhovan8 You can exclude the muted chats from the overall unread messages counter in Settings.

**Comment by smekhovan8** [comment]
Thank you. It completely solves the problem.
