### ISSUE TITLE
Improvement to emoji autocomplete

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#3748]
After #627 was introduced, I thought about two more things to improve the emoji autocomplete feature:

* [X] Use case insensitive match - for example, I'm using Hebrew as my main language and the fastest way to write a word in English would be with Capslock or Shift - I believe it would be correct to any non latin language.
* [ ] Add other keywords for the emojis, such as the keywords in [this list](https://github.com/muan/emojilib/blob/master/emojis.json) or [this one](http://unicode.org/emoji/charts/emoji-list.html)

**Comment by stek29** [comment]
Doesn't fix second part

**Comment by Geobert** [comment]
Can I add completion of noseless smiley as well?
`:p` to be completed the same as `:-p` 
`:)` = `:-)`
etc…

**Comment by Geobert** [comment]
still relevant

**Comment by ilya-fedin** [comment]
#780
