### ISSUE TITLE
Telegram desktop crashes when plugging in new audio device

### ISSUE THREAD

**Issue by vdmkenny** [telegramdesktop/tdesktop#3749]
### Steps to reproduce
1. Start telegram-desktop
2. Plug in new audio device (usb headset in my case)
3. Telegram instantly crashes

### Expected behaviour
The application should not crash

### Actual behaviour
Telegram crashes, with the following error:
`The program 'telegram-desktop' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 1383 error_code 10 request_code 131 minor_code 46)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
`
In debugmode I can find nothing relevant.

### Configuration
**Operating system:** Arch Linux, running latest stable version of Gnome 3, on Xorg.

**Version of Telegram Desktop:** 1.1.19

**Used theme**: Incognito theme

**Comment by john-preston** [comment]
@vdmkenny Do you use version from the official website?

**Comment by vdmkenny** [comment]
@john-preston I'm using this package: https://aur.archlinux.org/packages/telegram-desktop-bin/

This makefile uses the upstream, official source.

**Comment by john-preston** [comment]
@vdmkenny If you try the alpha version from https://desktop.telegram.org/changelog#alpha-version it should offer you to send a crash reporty when you launch it after a crash. You can copy the report tag from the crash report send window, send the report and send the tag here so I could look at this specific crash report.

**Comment by vdmkenny** [comment]
@john-preston I just tried the alpha version, and I'm able to trigger a crash by removing/inserting my audio device, but upon relaunching the client, it does not give me anything about a crash report. Do I need to enable it somehow, or is it just not picking up the crash?

**Comment by john-preston** [comment]
@vdmkenny It doesn't see the crash :(

**Comment by Aokromes** [comment]
@vdmkenny try to run telegram with gdb.

**Comment by vdmkenny** [comment]
@Aokromes with gdb, the only thing I get is the same error as before:
The program 'telegram-desktop' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 11631 error_code 10 request_code 131 minor_code 46)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by Aokromes** [comment]
^^ You need the output after running commands, example:
https://github.com/TrinityCore/TrinityCore/blob/master/contrib/debugger/crashreport.gdb

**Comment by stek29** [comment]
#2478
