### ISSUE TITLE
Linux: Input methods (Fcitx etc.) do not work

### ISSUE THREAD

**Issue by TheHellstorm** [telegramdesktop/tdesktop#375]
Telegram on Linux does not support input methods for East Asian languages. For example, fcitx does not work.

In other Linux programs pressing (for example) Ctrl+Space activates the input method. In Telegram, nothing happens. Also, you cannot select the input method with right clicking in the text box, as it would work in other programs.

**Comment by telegramdesktop** [comment]
I use default Qt input fields, I'm not sure how to make them support those features.

**Comment by vipjeffreylee** [comment]
I think you should  link libfcitxplatforminputcontextplugin.so into telegram.Default,Qt5 supported ibus only.Qt5 supported input method is here /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/

**Comment by telegramdesktop** [comment]
Ubuntu does not install fcitx-qt5 package for me, I could not find this plugin in Qt source and don't know where did you take one.

**Comment by vipjeffreylee** [comment]
https://launchpad.net/ubuntu/+source/fcitx-qt5

**Comment by telegramdesktop** [comment]
I've tried that and got "E: Unable to locate package fcitx-frontend-qt5" on ubuntu 12.04. Maybe I should use 14.04 or some other version, but last time I tried it Telegram built on 14.04 failed to launch on 12.04, and built on 12.04 launches everywhere, I didn't have time then to figure out why.

**Comment by telegramdesktop** [comment]
Yeah, it is found in ubuntu 14.04, so I'll look into it some day.

**Comment by giyyapan** [comment]
@telegramdesktop many thanks!
This could be the last thing that stops me using telegram desktop on Linux :)

**Comment by Findxiaoxun** [comment]
Waiting For The Support :)

**Comment by ustcltx** [comment]
@telegramdesktop I hope it will support input methods soon.

**Comment by deng-kai** [comment]
Hi,owner. When you debug on QT5，please concern about these .so files in this folder.Add these to your QT creator environment
![2015-03-03 19 39 34](https://cloud.githubusercontent.com/assets/4125802/6461668/15a3b94e-c1dd-11e4-80ed-65bdb7b1831e.png)

**Comment by taijuin** [comment]
@telegramdesktop

http://www.cnblogs.com/daizhe11/p/3384698.html

https://github.com/telegramdesktop/tdesktop/blob/master/QTCREATOR.md

http://www.smzdy.com/qt5-not-switch-using-chinese-input-methods-ubuntu12-04.html

so ''Qt Creator 3.1.2'' is too old ?

**Comment by taijuin** [comment]
@telegramdesktop

I find the answer through an unofficial Telegram client.

The steps are：
1. Install fcitx :  fcitx...
2. Let fcitx support Qt5 : fcitx-frontend-qt5、fcitx-libs-qt5
3. Install your input method : For example,fcitx-chewing
4. run im-config , let fcitx be the defaul input method framework
    ( In Ubuntu14.04 , do not set the file '/etc/profile' and '~/.profile' 
     , im-config wil change the file '~/.xinputrc' ,the content : 

     run_im fcitx
 
     )
5. then you can input characters correctly in other program
6. In the terminal，run：(copy libfcitxplatforminputcontextplugin.so to the unofficial Telegram plugins directory )
   cd /usr/lib/unofficialTelegram/plugins
   sudo cp /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so ./
7. maybe reboot computer
8. you can input characters correctly in the unofficial Telegram client .

I want to say is that:
@telegramdesktop can create an directory,like  ' /usr/lib/Telegram/plugins ',
 and we can copy libfcitxplatforminputcontextplugin.so to the directory by ourselves. And it will be used by Telegram Desktop.

NOTES :

The unofficial Telegram (Cutegram) : http://aseman.co/en/products/cutegram/

The information source :  http://wangbinweb.github.io/htm/7-notes-for-linux-use.htm

**Comment by FreedomKnight** [comment]
I use ibus-chewing, and it still can't type. (fedora 21)

**Comment by taijuin** [comment]
Maybe 'Telegram Desktop' does not know the directory:

 /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/

and has not it's own plugins directory:(like this)

/usr/lib/Telegram/plugins

**Comment by guoyunhebrave** [comment]
Waiting for this feature.

**Comment by mxa** [comment]
current workaround methods: 1. use the Cutegram client instead. or 2. type your Chinese/Korean/Japanese/... somewhere else and paste it into Telegram.

**Comment by guoyunhebrave** [comment]
@mxa Cutegram doesn't support fcitx too.

**Comment by trainchou** [comment]
waiting for the support!

**Comment by jdh8** [comment]
I tried ibus and gcin on KDE 4, Fedora 21. :(

**Comment by guoyunhebrave** [comment]
If you cannot wait, you can use Telegram web client https://web.telegram.org/

If you use Firefox, you can install Firefox app https://marketplace.firefox.com/app/telegram

If you use Chrome, you can isntall Chrome app https://telegram.org/dl/webogram/chromeapp

These two web app works similiar as native app, but can not support tray icon. I think it is not a big problem. Since both Firefox and Chrome are not 100% stable, your web app may crash occasionally. My Telegram Firefox app crash twice in 3 days.

**Comment by yura121** [comment]
Telegram 0.8.11, Ubuntu 14.04 x64, iBus (ibus-m17n) doesn't work. 
Waiting for the support!

**Comment by guoyunhebrave** [comment]
I think this should be a high priority issue.

**Comment by tigerlee** [comment]
Waiting for this feature.

**Comment by wu-nerd** [comment]
Ubuntu 14.04.2 LTS 
fcitx version: 4.2.8.3
doesn't work

**Comment by AkemiHomura** [comment]
The lib you got with 'apt-get' was not the latest version. My qt-creator crashed when i put it into folder Tools/......../plugin/platforminputcontexts/
I have just compiled the newest libfcitxplatforminputcontextplugin.so and it's working perfectly with Qt5.4.1 on my ubuntu14.04.02(fcitx 4.2.8.5).
I tried some test program and i got fcitx working.
![screenshot from 2015-05-19 23 04 11](https://cloud.githubusercontent.com/assets/8898435/7706192/73016ba6-fe7b-11e4-8e67-5c8bb433b42a.png)
I tried to compile tdesktop with Qt5.4.1 and got trouble in fixing the changed functions such as QTextLayout(QtextEngine *e):d(e) {}.


When i was trying to compile the qtlib with -static, it warned that no dll(so) will be supported.
Thus ibus is not supported because no .so can work. And in cod I found libcomposeplatforminputcontextplugin.a imported only.
I may try compiling with Qt5.4.0 some day but i have no time recently.
The compiled lib was on my google drive: https://drive.google.com/file/d/0B18XN3r6jNU1QlRybTdZbkFmT2s/view
I hope someone can try whether it works.

Sorry for my poor english.

**Comment by adrianiainlam** [comment]
Confirming issue on Ubuntu 14.04.2 with Telegram 0.8.17 and IBus 1.5.5.

Found [this][1] via Google, which may or may not be relevant. The article is in Japanese but the code should be understandable.

[1]: http://emblog-qt.hatenablog.jp/entry/Cant_use_ibus_Input_Method_qtcreator_qt5

**Comment by bigeagle** [comment]
Here is a patched version with ibus and fcitx support https://github.com/aphuse/tdesktop . I've tested, it works quite well.

**Comment by deng-kai** [comment]
@telegramdesktop  please consider the fix upstairs

**Comment by tramchamploo** [comment]
why not create a pull request so that the @telegramdesktop could merge

**Comment by bigeagle** [comment]
@tramchamploo Already pull requested, https://github.com/telegramdesktop/tdesktop/pull/759 ,
But @telegramdesktop never merge code pull requests.

**Comment by redhatlinux10** [comment]
i think is bug affects most of CJK users and is a urgent one, please consider fix it asap, thanks man!

**Comment by Maijin** [comment]
Ubuntu 15.04 8.38 still not fixed :crying_cat_face:

**Comment by pan-long** [comment]
I have given up the native app and I am fine with chrome app now. Everything works in telegram web app.

**Comment by CodeFalling** [comment]
Ubuntu 15.04 with fcitx still not fixed.Waiting for this.

**Comment by taijuin** [comment]
If you are using Chrome app in Linux desktop，maybe you can consider this:（including Simplified Chinese,Traditional Chinese,Korean.

https://chrome.google.com/webstore/detail/telegram/obocnnbgpkjmmdmmhnieggghdphphefm?utm_source=chrome-ntp-icon

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.

**Comment by taijuin** [comment]
I try it,and I really can input Chinese.
This is really good news.
Thank you !

**Comment by lotuslwt** [comment]
I have upgraded Telegram to latest version 0.85.1 on Ubuntu 12.04, but I can't still input Chinese. 
Is fcitx-qt5 first installed? if so, how to install it? 
Thank you !

**Comment by taijuin** [comment]
It is not a Telegram desktop problem!
You can refer to here: ( I have not tested! )( Maybe you should use Ubuntu14.04 )
http://blog.csdn.net/zyh821351004/article/details/43700699

**Comment by Maijin** [comment]
Awesome it works in the latest version now (no need dev) \o/

**Comment by JixunMoe** [comment]
I got it working by force the `QT_IM_MODULE` variable, not sure if this helps.

*Node*: This is Ubuntu, with `fcitx-libs-qt5` and its front-end installed.

```
QT_IM_MODULE=fcitx /opt/telegram/Telegram
```

**Comment by kroody** [comment]
https://bugs.launchpad.net/ubuntu-sdk-ide/+bug/1534492

**Comment by mxa** [comment]
This has worked for me, but is now broken again (using fcitx) since an OS update. The Telegram version did not change.

**Comment by dawncold** [comment]
I don't know why one of my PC needs link qt plugins to Telegram's bin directory but another doesn't need, they are Ubuntu 12.04 LTS and installed fcitx nightly build.

**Comment by px4n** [comment]
For Fedora fcitx users, ensure that you have the package **fcitx-qt5** installed and that you have the following set up either in .bashrc or any environment file.

```
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
```

**Comment by blackwhitetony** [comment]
On manjaro it's quite easy:
just
````shell
sudo pacman -S fcitx-qt5
```
