### ISSUE TITLE
On linux desktop version some keys are not possible to type: ^, ´, ` etc. (but copy paste works!!!) (German keyboard layout)

### ISSUE THREAD

**Issue by hearues-zueke-github** [telegramdesktop/tdesktop#3754]
### Steps to reproduce
1. Open any chat
2. Change keyboard layout to german
3. Try typing: ^ or ´ or `

### Expected behaviour
When ^, ´, ` are pressed twice, there should came the symbol only once.

### Actual behaviour
Nothing happens! But copy paste from other places is working!

### Configuration
**Operating system:** Linux Mint 18.1 "Serena" XFCE

**Version of Telegram Desktop:** 1.1.19

**Used theme**: Standard

**Comment by Aokromes** [comment]
#1041

**Comment by mazi5769** [comment]
no kod danger

**Comment by diazbastian** [comment]
@hearues-zueke-github Install and enable ibus don't work?

**Comment by hearues-zueke-github** [comment]
@diazbastian tnx,
also this link helped me:
https://askubuntu.com/questions/135548/how-to-add-ibus-to-start-up-applications

close 3754

**Comment by josehfurtado** [comment]
Hii! Actually Ubuntu 16 don't work well with IBUS. Install and activate IBus solve Telegram's problem but  most of softwares became like Telegram. THose "~^" don't work in Firefox or some text editor. I type a letter and it appears seconds later in editor. I needed to deactvate Ibus. Now just Telegram have typing problems.
