### ISSUE TITLE
Weird behaviour with the automatically hidden task bar, if TDesktop is maximized

### ISSUE THREAD

**Issue by DarthJahus** [telegramdesktop/tdesktop#3756]
Version `1.1.18 Alpha`

If you maximize TDesktop, and change the settings for Task Bar to make it hide automatically, TDesktop doesn't allow it to appear even though other programs do.

If you resize TDesktop and maximize again, the Task Bar shows when the mouse hovers its area.

If you minimize TDesktop and maximize it, it doesn't allow the Task Bar to show anymore. The same happens if you switch to another app (ALT+TAB) and come back to TDesktop (Task Bar can't appear).

If you disable the "Hide Task Bar" option while TDesktop is maximized, it leaves the maximized state but stays at the same size (takes all the screen). If you move the window, the window keeps that screen size (same as when maximized).

**Comment by auchri** [comment]
Use the template please.

**Comment by DarthJahus** [comment]
I provided the version, the OS version, this doesn't have to do with themes, the expected behaviour is crystal clear and all my text is about steps to reproduce the issue. Or are you just willing some fancy titles?
