### ISSUE TITLE
[Feature Request] Suppress warning opening bot links

### ISSUE THREAD

**Issue by BlackLanzer** [telegramdesktop/tdesktop#3758]
### Actual behaviour
Everytime you click on a link sent by a bot a pop-up ask if you want to open it.

### Expected behaviour
You should be able to set a global setting or a whitelist of bots you trust and just open the links without any warnings.

**Comment by MaxMatti** [comment]
I wouldn't do a whitelist for bots but rather for websites. But I also would like to see something like this implemented.
