### ISSUE TITLE
[Feature Request] cloud storage as a conversation of two

### ISSUE THREAD

**Issue by y1n0** [telegramdesktop/tdesktop#3760]
### behaviour I'd like to see
when I send a message to my cloud it should be forwarded to me, so I have two copies of it: one that I sent, and another one I must receive.

### Actual behaviour
you just send the message and it done (on android, all cloud msgs are as if sent, and on desktop (linux), they're as received)

**Comment by auchri** [comment]
Not an issue of Telegram Desktop.

btw. this makes no sense.
