### ISSUE TITLE
Cannot install Breakpad: TypeError when running "fetch breakpad"

### ISSUE THREAD

**Issue by OrBin** [telegramdesktop/tdesktop#3761]
### Steps to reproduce
1. Follow the [instructions](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md#depot_tools) to install depot_tools.
2. Follow the [instructions](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md#breakpad) to install breakpad - When running the line `..\depot_tools\fetch breakpad`, the error occurs.

### Actual behaviour
during the run of `..\depot_tools\fetch breakpad`, "gclient sync" is called and throws a TypeError.
The full output is attached [here](https://pastebin.com/CrhPpgkq).

### Configuration
**Operating system:** Windows 10 64 Bit with Visual Studio 2015

**Version of Telegram Desktop:** Cloned from `dev` branch.

**Comment by OrBin** [comment]
Found an explanation to the problem and a (temporary) solution:
In [this StackOverflow answer](https://stackoverflow.com/a/45495157/2338522), user 'bc_' explain the bug cause and links to a [patch](https://bugs.chromium.org/p/chromium/issues/detail?id=749720) they applied to it.

**Comment by auchri** [comment]
So it's not an issue of Telegram Desktop.
