### ISSUE TITLE
Update Fails to Install on Windows 10 Pro

### ISSUE THREAD

**Issue by cooperpellaton** [telegramdesktop/tdesktop#3764]
### Steps to reproduce
1. Install Telegram 1.17 on Windows 10 Pro Insider Preview Build 16251.rs3_release.170721-2122
2. Update Telegram to 1.19
3. Update fails.

### Expected behaviour
Normally I would expect that the update would fulfill, but it doesn't work. I've tried this on numerous versions, and different methods and it always fails.
![screenshot_1](https://user-images.githubusercontent.com/5178017/28999833-5e9e6d94-7a25-11e7-9191-830d793e72a9.png)

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:** Windows 10 Pro Insider Preview Build 16251.rs3_release.170721-2122

**Version of Telegram Desktop:** 1.17

**Used theme**:N/A

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@cooperpellaton Some process (antivirus or smth) is locking the "Telegram.exe" file and it can't be overwritten :( It doesn't reproduce when I update, it updates fine.

**Comment by Aokromes** [comment]
works for me(TM) too.
Microsoft Windows [Version 10.0.16257.1]

**Comment by alexnv** [comment]
same issue

**Comment by Aokromes** [comment]
I suggest you to get https://lockhunter.com/ to see what's locking the file to see where it's the issue.

**Comment by dantheman999301** [comment]
I'm getting this as well.

Lockhunter just says it's locked by System. This is happening on two separate machines and the locking started at the same time. Can update by downloading the installer but that's a bit of a faff.

![image](https://user-images.githubusercontent.com/9741849/45078225-5b454380-b0e7-11e8-8fe8-9d82b8a44543.png)

**Comment by Aokromes** [comment]
Ok, it looks it's windows bug and not telegram bug:
https://stackoverflow.com/questions/4378192/windows-2008-r2-kernel-system-process-pid-4-is-locking-files-and-folders
https://www.ryadel.com/en/unlock-file-handle-locked-system-active-process-windows/
https://social.technet.microsoft.com/Forums/windowsserver/en-US/b9ee9739-8ac8-4c83-8bff-1a573d1c5979/windows-7-system-locking-my-files?forum=winservergen

**Comment by Aokromes** [comment]
logout from your use and login again and click update as workaround to this windows bug.
