### ISSUE TITLE
Telegram automagically adds new contacts which are not in the contact list of my DES

### ISSUE THREAD

**Issue by KarelWintersky** [telegramdesktop/tdesktop#3766]
Unknown user (recently registered in Telegram) appeared. 

IT'S A PROBLEM.
SECURITY PROBLEM

**Comment by stek29** [comment]
It's not a security problem, it's privacy problem.
Currently every time tg gets your contact in any way (on smartphones, maybe you logged into someone's account, inserted a Sim or logged into cloud account with contacts sync) it saves it to the cloud. Ones who already registered in telegram are shown and may be deleted, others stay on server but you can't see or remove them (I haven't checked it personally though, there may be some hacks)

Also, TDesktop simply can't get contacts in any way except being added manually, it doesn't have APIs for contact sync on any system (there's a feature request for Windows, look it up)

So it's not a TDesktop problem, and also it's rather a privacy than security issue.

Btw, Android app recently removed "private" page from welcome tutorial with the features 🙃.

**Comment by KarelWintersky** [comment]
My 'mobile' device with installed android-app telegram **does not have SIM card**. It's connected to my home wifi-network. My mobile with SIM card did not support telegram (Android 2.4.6) and does not have any internet access.

Also, I have a TDesktop on my PC. 

Today there was a message: "Kate registred in telegram recently" (Or something similar (I did not make a screenshot)). 

New contact has avatar and publicly visible phone number. **Unknown** to me phone number! 

And I've **never seen** this person before, in my address book there is no person with such a number and none of my friends know her.

WTF?

Sorry for poor english.

**Comment by KarelWintersky** [comment]
A small addition.

I left for a couple of days in those regions where there is no internet. When I returned, I turned on the PC and started the telegram (desktop). An account unknown to me appeared immediately.

Nobody in my absence used a computer.

I launched the telegram on android 5 minutes ago. Of course, unknown to me contact is present there, although I have **already deleted** it from the desktop version.

**Comment by KarelWintersky** [comment]
> on smartphones, maybe you logged into someone's account, inserted a Sim or logged into cloud account with contacts sync

I use only my account. 
My mobile phone with my SIM does not have installed telegram.
I don't use cloud sync.

**Comment by KarelWintersky** [comment]
Also, it is a post at russian habrahabr with this issue.

**Comment by stek29** [comment]
That post is about issue I described. 
Please check active sessions in settings.

**Comment by KarelWintersky** [comment]
![](https://habrastorage.org/web/7e7/441/33b/7e744133b868461382b4087d56d65263.PNG)

**Comment by KarelWintersky** [comment]
Last two sessions, I think, is from notebook.

**Comment by KarelWintersky** [comment]
Problem appears again:

![](https://habrastorage.org/web/700/30e/22f/70030e22fa8c4d57acf2bb9be5c5fbe3.jpg)

Active sessions:

![](https://habrastorage.org/web/37e/482/8d2/37e4828d293149c98eb1614d2847edd9.PNG)

## Details

- My 'mobile phone' with a telegram **does not have** a sim card. It's connected to my home wifi-network. 
- My mobile phone with SIM **does not have** installed telegram (not supported), does not have internet connection, does not have wifi connection. 
- I have a TDesktop on my PC.
- I see this phone number for the **first time**
- And I've never seen this person before, in my address book there is no person with such a number.
- I don't use cloud sync.

## A little update: 

Previously, my "mobile" phone belonged to my friend. Before use, I cleared **all phone books** and **deleted all installed applications**. I also, of course, deleted **the cached data**. My friend **never** installed telegrams on **this** phone (but sometimes uses it from another device).

The above number **is in my friend's phonebook**.

Where **did** this person come from on my telegram contact list?

**Comment by fakeid30** [comment]
It's a security issue that's been known for quite some times. I've reproduced it multiple times, reported to @drklo but he ignores this everytime , maybe it's out of hand of him too. 

## Steps to reproduce this easily : 

- Have a phone, with phone number let's say +123456 (a fully working phone with telegram installed and functioning contacts list)
- Get a friend's phone, and install Telegram on it. Let's say friend's number is +789456 
- Now log out from your Telegram (+123456) , go to log in again, input your friend's number (+789456) , he will get a text. 
- Let your friend log into his Telegram, he'll have your full contact list. 

This should be fixed , like urgently, but I can't get anyone to acknowledge it. Oh well! 😭

**Comment by Aokromes** [comment]
imho not telegram desktop issue instead telegram api or server issue.

**Comment by KarelWintersky** [comment]
You closed issue. Now, it **NEVER** will be solved.

**Comment by john-preston** [comment]
@KarelWintersky But this has nothing to do with Telegram Desktop, it doesn’t import any contacts and it can’t fix that issue anyway :(

**Comment by anfimovir** [comment]
Please simple send information in Telegram Support via: https://telegram.org/support or Twitter.

**Comment by stek29** [comment]
@john-preston Although TDesktop might provide `contacts.resetSaved` :)

**Comment by KarelWintersky** [comment]
> Please simple send information in Telegram Support via: https://telegram.org/support or Twitter.

This is **absolutely** useless action. Absolutely no any answer more that 4 months./

**Comment by RememberTheAir** [comment]
@stek29 yes! Maybe something hidden like in the android app, to not clutter the interface. On the false line of `workmode` or the other hidden keywords we can type in the settings screen. Something like `resetimported`

**Comment by KarelWintersky** [comment]
> Please simple send information in Telegram Support via: https://telegram.org/support
NO Answer more than 2 years.

**Comment by KarelWintersky** [comment]
@john-preston , what about RESET imported option/menu/console-command ?

**Comment by stek29** [comment]
@KarelWintersky use some third party app or android/ios app.

**Comment by KarelWintersky** [comment]
@stek29 , for example?

**Comment by RememberTheAir** [comment]
@KarelWintersky Telegram/Telegram X for Android. They both have an hidden option to reset **all** your contacts

**Comment by JalolBieber** [comment]
To Cleand and Delete Strange and useless contacts use this application. It was so helpful
https://play.google.com/store/apps/details?id=uz.logic.telegram

**Comment by Chrescht** [comment]
This is messy and should not be the case for such a nice app like Telegram. It's all about privacy but then it's not.

**Comment by Nikeyshon** [comment]
Hope this helps
https://www.reddit.com/r/Telegram/comments/75mplv/ios_telegram_keeps_adding_contacts_im_no_longer/

Go to settings, Privacy and security, and in the contacts tabs delete sync contacts

**Comment by chagai95** [comment]
Please reopen this issue I'm still encountering the same problem!

**Comment by RememberTheAir** [comment]
@chagai95 tdesktop doesn't import any contact afaik, so it's not an issue with this particular client

**Comment by chagai95** [comment]
> You closed issue. Now, it **NEVER** will be solved.
> 
> Pls, reopen. Or move to correct repository



> @chagai95 tdesktop doesn't import any contact afaik, so it's not an issue with this particular client

like @KarelWintersky mentioned it will be nice if you can then move it to the correct repository and then reopen it.

**Comment by diogomobicare** [comment]
Problem persists. "Sync contacts" feature is really messed up.

**Comment by dmagliano** [comment]
Problem persists. Sync Contacts feature is messed up.

**Comment by dedalus2** [comment]
Hi guys! This is not a casual thing. Onde day you added "Isabel" to your contacts. Isabel did the same and added you to her contacts. Later you deleted Isabel's contact because it no longer serves you, but she did not.
When Isabel installs Telegram, it sends a message to all the numbers she has in her phone book... where you are.

Is this applicable to all cases?
