### ISSUE TITLE
GNOME: Telegram desktop steals the focus when you click on notifcations from other applications

### ISSUE THREAD

**Issue by Feichtmeier** [telegramdesktop/tdesktop#3769]
### Steps to reproduce
1. use telegram under GNOME3.20+
2. receive a native notification from a different app 
3. click on that native notification and telegram instead of the application receives the focus and jumps into the foreground

### Expected behaviour
The application that sent the noficiation should jump into the foreground

### Actual behaviour
Telegram jumps into the foreground

### Configuration
**Operating system:**
Ubuntu 17.04 GNOME 3.22

**Version of Telegram Desktop:**
1.1.19

**Used theme**:
Default theme

**Comment by john-preston** [comment]
@Feichtmeier I don't know how this happens. Pull request with a fix would help a lot :)

**Comment by stek29** [comment]
what happens if TDesktop sends it's own notifications to different corner?

**Comment by Feichtmeier** [comment]
I do not know how to fix this sadly :/
@stek29  Yes this also occures when you select the telegram notifications instead of the native linux notifications.

**Comment by auchri** [comment]
Duplicate of #1026 btw.
