### ISSUE TITLE
Message Field does not always correctly receive focus on Windows

### ISSUE THREAD

**Issue by brynthomas** [telegramdesktop/tdesktop#377]
if another app is in focus and you click on the text of a History Message inside Telegram, the Message Field does not receive focus. Anything you type gets lost. If you click on the History Message again then Telegram will correctly give the Message Field focus. If you enter the app via clicking on anything except the History Message (say the Cats 'n Dogs background) then the Message Field also correctly gains focus.

On Ubuntu 12.04 if one clicks on the text of a History Message while in another app, the Message Field correctly receives focus.

Seems to be a Windows only problem (but have not tried Mac OS).

**Comment by telegramdesktop** [comment]
Should be fixed in 0.7.8 (the idea was not remove the text selection, if it was, when activating app by click in Windows, only by a second click on already active app), but if nothing is selected the message field should now get focus.
