### ISSUE TITLE
It's possible restore conversations from /tdata folder?

### ISSUE THREAD

**Issue by Astrovic** [telegramdesktop/tdesktop#3770]
Hi,
I've delete the conversations with myself on Telegram Desktop, ed now thy are not visible in Telegram mobile app. 
On Telegram Desktop version there's a /tdata folder, with more that 100files. Would it be possible to retrieve conversations from these files? I tried to delete the most recent files, but Telegram asks me to log in to load the conversations, so only those on the cloud are uploaded :(

**Comment by stek29** [comment]
No, TDesktop doesn't cache messages at all, and media is almost impossible to be restored from those files. 
You've opened that chat on mobile already, so it's probably removed from local db on phone too.
And if yes, there's no way. Sorry about this.

**Comment by Astrovic** [comment]
Thank you @stek29 for the reply. 
No, it was just text messages. I thought those files could help me recover them :(
For what are the backup files useful, since data can not be decoded? Do you confirm that it is not possible to retrieve those text messages in any way through those files?

**Comment by john-preston** [comment]
@Astrovic There are no text messages in those files. This is not backup files. Those are just image / GIF / voice message cache that is very hard to read by themself (at least you'll be required to write a special program for that and if the encryption key was already overwritten it is not possible to read them at all).

**Comment by Astrovic** [comment]
Perfect thank you all. But on the local Android application database, would somehow be able to retrieve text messages? Or will they have been permanently removed there too?

**Comment by SmartManoj** [comment]
What about this feature ?
https://telegram.org/blog/permissions-groups-undo
