### ISSUE TITLE
Does not use the "Default communication device" in windows

### ISSUE THREAD

**Issue by grikdotnet** [telegramdesktop/tdesktop#3771]
### Steps to reproduce
1. Connect a bluetooth headphone as a defaul communication device and speakers as a default device
2. Call anyone
3. Telegram does not use headphones

### Expected behaviour
Telegram should use a default communication device, as other software does,

### Actual behaviour
Telegram does not allow to choose the sound device.

### Configuration
Windows 10

**Version of Telegram Desktop:**
1.1.19

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>

**Comment by grikdotnet** [comment]
Maybe it's a dup for #776, sorry in that case.

**Comment by ScottRFrost** [comment]
I'm able to reproduce this as well.  Windows 10.  Sound output always coming out of the default device and NOT the default communication device.  

Notifications / audio playing / etc should be coming out of my speakers in my monitor, but calls should be coming out of my headset:

![image](https://user-images.githubusercontent.com/3866418/30919272-e0b273bc-a36e-11e7-8886-1b9d97a4ee52.png)

**Comment by stek29** [comment]
I guess you should open an issue on grishka/libtgvoip.

cc #3389

**Comment by stek29** [comment]
Is fixed afaik

**Comment by dtitov** [comment]
This issue is back. Win 10, TG 1.3.7.
