### ISSUE TITLE
Support for SVG animations [FEATURE]

### ISSUE THREAD

**Issue by kenkit** [telegramdesktop/tdesktop#3774]
Hi, 
Is it possible for telegram to support svg animations.
It would be cool if telegram pioneered such a move in messaging clients.
Also, in the desktop client. Can you make new messages come first in the list of messages from the top.

**Comment by auchri** [comment]
@kenkit Use the template please.

**Comment by stek29** [comment]
> Is it possible for telegram to support svg animations

What do you mean? To make svg animations work similar to gifs? 

> Can you make new messages come first in the list of messages from the top.

#2557

**Comment by kenkit** [comment]
Yes, especially in profile pictures.

**Comment by stek29** [comment]
Then it's an API issue, ask Telegram for it on Twitter or via in-app Support.

IMHO it would be rather annoying than useful, and won't fit with [TG's feature philosophy](https://core.telegram.org/tsi/feature_philosophy)

**Comment by yashpalgoyal1304** [comment]
haha. times change :O
