### ISSUE TITLE
tg links opened from firefox on windows don't open telegram correctly

### ISSUE THREAD

**Issue by Thorbijoern** [telegramdesktop/tdesktop#3775]
### Steps to reproduce
1. open tg link (like links to chats) in firefox on windows
2. 
3. 

### Expected behaviour
telegram should open correct and open the chat.

### Actual behaviour
telegram opens like it were installed one second ago, but not in German as it should and instead Englisch, there is the button 'start messaging' and it prompts my phone number.

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.1.19

**Used theme**: is not important i suppose

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
Have you used portable version ago?
Also, are you sure it's the same TDesktop? Can you check executable path in process explorer?

**Comment by Thorbijoern** [comment]
which portable version? I'm not on Windows 8 or 10, so I don't use any app wich might exist, if you mean that.
In Telegram is says:
"Telegram Desktop Version 1.1.19"
and the executable is "%AppData%\Roaming\Telegram Desktop\Telegram.exe"

**Comment by auchri** [comment]
@Thorbijoern There exists an portable version for Windows (https://desktop.telegram.org/). Did you try to reinstall Telegram?

**Comment by Thorbijoern** [comment]
i don't have the portable version, but reinstalled it now and it is working again. I haven't thought of reinstalling it, sorry.

**Comment by stek29** [comment]
Try checking path in Software\Classes\tdesktop.tg\shell\open\command next time

**Comment by SmartManoj** [comment]
Computer\HKEY_CURRENT_USER\Software\Classes\tdesktop.tg\shell\open\command
