### ISSUE TITLE
Opening a profile automatically mutes the chat

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#3780]
### Steps to reproduce
1. search for an username or open an user profile/channel/bot from an username in a message

### Expected behaviour
The channel/user/bot's notifications are not muted as soon as you open the profile (if I recall correctly, channels are muted as soon as you subscribe them)

### Actual behaviour
The notifications checkbox is unchecked (and thus notifications are muted) as soon as you open the profile. If you are fast enough, you can see the checkbox being untoggled in front of your eyes.

Here's a link to a video where I open some random profiles I've never opened before, their notifications checkboxes get automatically unchecked (_note that I'm not clicking on the checkboxes, it was my fault to hover on them with the mouse while recording the video_): [link](https://streamable.com/owvyg)

### Configuration
**Operating system:** Windows 7 and Windows 10 Pro 10.0.15063

**Version of Telegram Desktop:** 1.1.19 alpha portable

**Used theme**: default

**Comment by RememberTheAir** [comment]
Another video: [me looking for random bots](https://streamable.com/axitq). The bot gets automatically muted aso soon as I open its profile

**Comment by stek29** [comment]
I tried but was unable to reproduce it.
Usually it happens when peer is unmuted on server side but tdesktop doesn't know about it -- and when it requests "UserFull" it notices that it's muted and I uncheckes that checkbox.

The only reason bots can be authomatically unmuted that I can think of is muting all users, but tdesktop handles it correctly, without reloading.

Could you enable debug logs, search for random bots and then open mtp_HH_MM.txt log and look for notify_settings of those bots?

**Comment by RememberTheAir** [comment]
@stek29 I searched for the following bots and users:
[@sssbot](https://hastebin.com/aqiwozejax.vbs)
[@fffbot](https://hastebin.com/sicubadade.vbs)
[@hhhbot](https://hastebin.com/tetolojobi.vbs)
[@riccar](https://hastebin.com/ekiwuyifiq.vbs)
[@andrea](https://hastebin.com/honowibege.vbs)

The username links to the result of what I suppose was the result of `UserFull`

**Comment by stek29** [comment]
mute_until is more interesting than flags :)

**Comment by stek29** [comment]
Also, are those users muted on other apps? You can try web.telegram.org.

**Comment by RememberTheAir** [comment]
@stek29 yes, they result muted in other apps (screenshots -> [@riccar](http://i.imgur.com/SW72QsR.jpg), [@fffbot](http://i.imgur.com/dBnSn8g.jpg))

**Comment by RememberTheAir** [comment]
Interesting: just noticed that this is actually happening also from the latest Android beta `4.2.2 (10595)`. So I guess this is an API issue?

When I search for random usernames (users/bots), and I open their profile, notifications are turned off

**Comment by john-preston** [comment]
@RememberTheAir I'm afraid tdesktop is not muting anything on profile open indeed — it just loads the status of notifications and shows it in the profile. The question is why everyone is muted for you on the server side.

**Comment by RememberTheAir** [comment]
@john-preston yes, not a tdesktop problem. Feel free to close this issue. I will report this to the in-app support

**Comment by john-preston** [comment]
@RememberTheAir There are some global notifications settings, perhaps you turned them off? For all users/ all chats?

**Comment by RememberTheAir** [comment]
There are? From where can I do that?

**Comment by RememberTheAir** [comment]
@john-preston there are? From where can I do that?

**Comment by stek29** [comment]
@RememberTheAir Yes. 
You can check them via tjhorer.com/webogram.
Log in, click on "Telegram for Devs", click on Sandbox.

Method is `account.getNotifySettings`
Payload is `{"peer":{"_":"inputNotifyUsers"}}`

**Comment by RememberTheAir** [comment]
@stek29 thanks.

[respose from the API](https://hastebin.com/ijavokobog.json)

I honestly don't understand what this means... are these my default "global" notifications settings?

**Comment by stek29** [comment]
Yes, those are your default notification settings for users (=bots)
You have them muted until 2038 (forever XD)

Here's how to unmute them:
`account.updateNotifySettings`
`{"peer":{"_":"inputNotifyUsers"}, "settings": {"_":"inputPeerNotifySettings", "mute_until":0, "flags": 1 }}`

Setting mute_until to 0 disables mute, setting flags to 1 enables show_previews.
You may also want to add `"sound": "9.m4a"` to set notification sound on apps different from TDesktop. Mine is 9, others should be fine too, maybe even having it empty is ok.

**Comment by stek29** [comment]
Oh, and about the latest layer.
Official site is awfully outdated. Use tl file in this repo, or https://stek29.rocks/tl-schema

**Comment by RememberTheAir** [comment]
@stek29 thanks a lot for the help! It worked :)
