### ISSUE TITLE
Scrolling the Chat List using UP and DOWN keyboard buttons has unexpected behaviour when mouse is over it

### ISSUE THREAD

**Issue by DarthJahus** [telegramdesktop/tdesktop#3781]
### Steps to reproduce

**Video**: https://youtu.be/ETsRAo4ie_0

a.
1. Put the focus on a chat (either press escape to close current chat or go to chat list when the window is small enough to not show conversation part);
2. Use keyboard Down button to browse the chat list;
3. When it arrives at the bottom, scrolling begins and it does it one by one and the newly shown chat has focus.

b.
1. Hover the chat list with mouse (put the mouse cursor on 3rd chat in the list, for example);
2. Use keyboard Down button to browse the chat list;
3. When it arrives at the bottom, the focus is given to the chat that is hovered by the cursor and then it goes down when pressing Down button and you need to go to bottom again in order to scroll.

If this can help, when using Page Down and Page Up, it goes over 5 chats, then scrolls and goes to the bottom (or top) and the focus remains at that position while scrolling. If mouse is over the middle chat, for example, pressing Page Down or Page Up keeps the focus and goes over 2 chats only at each button press.

### Expected behaviour
Expected behaviour is (a) part even if mouse is over the chat list.

### Actual behaviour
Actual behaviour is (b) part. Happens when pressing Up keyboard button as well.

### Configuration
**Operating system:**

**Version of Telegram Desktop:**
1.1.18 Alpha
But this behaviour has been observed for a long time.

**Used theme**:
Default light theme.

_Edit:_ Video link.

**Comment by john-preston** [comment]
@DarthJahus Yeah, thanks for your report.
