### ISSUE TITLE
Download Folder not opened in Nemo

### ISSUE THREAD

**Issue by mxa** [telegramdesktop/tdesktop#3782]
This is a regression, it used to work fine.

### Steps to reproduce
1. download image. Message " Image was saved to your Downloads folder" will appear
2. click on "Downloads" in that message
3. nothing happens

### Expected behaviour
Downloads folder opens in Nemo

### Actual behaviour
Nothing happens

### Configuration
**Operating system:** Linux Mint 18.2 Cinnamon 64bit

**Version of Telegram Desktop:** 1.1.19 alpha

**Comment by stek29** [comment]
Does xdg-open work?

**Comment by john-preston** [comment]
@mxa If someone knows how to fix that it would be great to share.

**Comment by mxa** [comment]
@stek29 yes, `xdg-open ~/Downloads` opens the Downloads folder in Nemo. (There is a GLib-GIO-WARNING, but I think that's unrelated.)

**Comment by auchri** [comment]
@mxa Do you find something like Failed to launch in the logs?

**Comment by mxa** [comment]
@auchri no such thing in the DebugLogs/log_xx_xx.txt

**Comment by stek29** [comment]
@mxa Btw, can you check if you're able to attach files with non-English symbols in their name?

**Comment by mxa** [comment]
@stek29 no problem with that. Just sent a file with some Korean characters to myself from Linux to Android.

**Comment by mxa** [comment]
Mint just pushed a Cinnamon update and it works now. Seems like this issue was not on Telegrams side.
