### ISSUE TITLE
@mention autocomplete in captions

### ISSUE THREAD

**Issue by stek29** [telegramdesktop/tdesktop#3783]
### Steps to reproduce
1. Attach an image/file/video
2. Start typing @username in caption

### Expected behaviour
See suggested usernames, as on Android app

### Actual behaviour
Nothing happens

### Notes
See #3696 for reference and more info.

**Comment by MasterGroosha** [comment]
Isn't it duplicate of #2158?

**Comment by stek29** [comment]
@MasterGroosha It is. I was looking for #2158, but was unable to find it :(
