### ISSUE TITLE
Enhacement: Order for list of opened chats/rooms: first locked/pinned, then chats with notifications activated, last without notifications or silenced, order by date in each section

### ISSUE THREAD

**Issue by jbernal-ej2sistemas** [telegramdesktop/tdesktop#3785]
### Steps to reproduce
1. Have a lot of chats silenced, but very active. When you receive a new message for a contact that notify and push the globe with pending reading, goes quickly to bottom because a lot of messages arrive for channels or contacts silenced. 

### Expected behaviour
I'd like that the contacts/chats with active notifications goes first always, order by date, but only between them. 

### Actual behaviour
All messages are ordered by date, except pinned chats that remains on top.

### Configuration
All

**Version of Telegram Desktop:**
1.1.19

**Used theme**:
Default

**Comment by stek29** [comment]
#2440
