### ISSUE TITLE
Global Notification Settings

### ISSUE THREAD

**Issue by stek29** [telegramdesktop/tdesktop#3786]
There are global notification settings in telegram.
They're accessible with `inputNotifyUsers`, `inputNotifyChats` and `inputNotifyAll`.
Currently there's no way to change them, only per peer settings are editable via TDesktop (`inputNotifyPeer`).

Afaik, mobile apps do support them.
Seems an easy pick for me, you may start looking from #3678 code.

See #3780 to understand why it may be needed.

**Comment by mydexterid** [comment]
I don't know if it is viable here but I just noticed yesterday that if I mute a notification on a chat on the android app for a couple of hours, it also mutes the notification on that chat on the web. (I haven't tried the desktop app yet).

**Comment by stek29** [comment]
@mydexterid It's not related to TDesktop and this issue directly. Maybe #277?
Muted chats are synced between clients.

**Comment by mydexterid** [comment]
@stek29 #277 would be the best solution, but it seems that during the issue's 3 years lifetime nothing happened unfortunately :/ Thought subscribed to that thread, thanks.

**Comment by freemangilgamesh** [comment]
I suggest you add the option to "receive notifications only from contacts" (not groups and channels). Having joint many groups and channels I find it quite annoying to be flooded with notifications. And I think this is the worst thing about telegram on Linux.

**Comment by chirick86** [comment]
5 years ago... Still need that thing.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/d8f53d5f6096ad84177ff2ab3001ac918eed017b
