### ISSUE TITLE
Add Exit button

### ISSUE THREAD

**Issue by DeadMetaler** [telegramdesktop/tdesktop#3787]
https://bugzilla.gnome.org/show_bug.cgi?id=785956
The legacy tray was removed from Linux GNOME Shell and now there is no way to exit from application.
Please add any button to quit from app. 
Also need to add all functionality of tray icon to main window.

### Actual behaviour
You didn' see any tray icons
### Configuration
Linux 
GNOME Shell 3.26 Beta
**Version of Telegram Desktop:**
All versions

**Comment by stek29** [comment]
Doesn't ctrl+q work?

**Comment by DeadMetaler** [comment]
@stek29 Yes. It is working. I doesn't know about this. How about other functions like "Disable notifications"?

**Comment by stek29** [comment]
@DeadMetaler Open settings and unselect "Desktop Notifications"
Minimize to tray is obvious, I guess.

**Comment by pascalwhoop** [comment]
doesn't kill app for me. Disabled desktop notifications, exiting but `ps ax | grep telegram` still shows running process. exit of GUI app needs to exit the process, Telegram is NOT a system service that ought to run in the background

**Comment by john-preston** [comment]
@pascalwhoop It should run in the background only if there is a tray icon available.
