### ISSUE TITLE
Math formulas support

### ISSUE THREAD

**Issue by ohhmm** [telegramdesktop/tdesktop#3788]
### Steps to reproduce
1. copy formula from https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BE%D1%80%D0%B5%D0%BC%D0%B0_%D0%9A%D1%80%D0%BE%D0%BD%D0%B5%D0%BA%D0%B5%D1%80%D0%B0_%E2%80%94_%D0%9A%D0%B0%D0%BF%D0%B5%D0%BB%D0%BB%D0%B8

> Система уравнений 
> A x = b {\displaystyle Ax=b} 
>  разрешима тогда и только тогда, когда 
> rank ⁡ A = rank ⁡ ( A , b ) {\displaystyle \operatorname {rank} A=\operatorname {rank} (A,b)} 
> , где 
> ( A , b ) {\displaystyle (A,b)} 
>  — расширенная матрица, полученная из матрицы 
> A {\displaystyle A} 
>  приписыванием столбца 
> b {\displaystyle b} 
> [1].
> 

or from https://math.stackexchange.com/questions/2282740/extrapolate-a-sum-using-partial-sums-at-powers-of-two

![image](https://user-images.githubusercontent.com/190779/29208132-7377628c-7e91-11e7-927a-084c4fdee39e.png)

 

### Expected behaviour
Expected to use same JS framework as stackexchange or Wikipedia uses to preserve formulas.

### Actual behaviour
for stackexchange it almost works

### Configuration
Windows

**Version of Telegram Desktop:**
1.1.18

**Used theme**:
default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@ohhmm I can't use js frameworks :(

**Comment by stek29** [comment]
So you want Wikitext/LaTeX parsing in TDesktop?

**Comment by ohhmm** [comment]
To copy formulas from wikipedia and math.stackexchange.com websites.
I thought Telegram use QML in which case I imagined JS and MathML.
Wolfram bot allows formula editing. Can it be useful?

**Comment by john-preston** [comment]
@ohhmm Telegram doesn't use QML 😔

**Comment by stek29** [comment]
#1349 #636 #437

> Wolfram bot allows formula editing. Can it be useful?

Or just use bot platform :)
https://t.me/LatexBot can be helpful too.

**Comment by fakeid30** [comment]
Why do you need this feature? I don't think it's useful for most people. So it'll be a bloat if added to core. Bots are the way to do it.

**Comment by ohhmm** [comment]
why do I need to copy a text with image from web? it bloats source code!
lets show images through bots with pseudo graphics! Bots are the way to do
such staff.

**Comment by ohhmm** [comment]
https://s-media-cache-ak0.pinimg.com/236x/e1/87/c2/e187c26bea08057f7507b4520b221dd8--simpsons-cartoon-simpsons-quotes.jpg - sorry, was unable to show here the image other way in cozy way. You see, I was thinking about downloading the image to attach it here to see if it show it then but it was too hard to do. And then "Hay, I can type this text here!"

**Comment by ohhmm** [comment]
RetroShare use QML anyway. Maybe someGSOC someone will implement it in single day in RetroShare. Thank you guys, sorry for bothering.

**Comment by ohhmm** [comment]
![Homer](https://s-media-cache-ak0.pinimg.com/236x/e1/87/c2/e187c26bea08057f7507b4520b221dd8--simpsons-cartoon-simpsons-quotes.jpg)
