### ISSUE TITLE
Retina users cannot scale the interface 😢

### ISSUE THREAD

**Issue by aminozuur** [telegramdesktop/tdesktop#3789]
### Steps to reproduce
1. Open Telegram for MacOS on a Retina MacBook
2. Go to Settings to try to scale (to increase font size)
3. You will see it that setting is hidden/disabled for Retina users. The last [given justification](https://github.com/telegramdesktop/tdesktop/issues/69#issuecomment-50226513) was that retina-ready images would bloat the app. Though I would not mind pixelated graphics, because right now the text is too small for me to use the app 😩

### Expected behaviour
Retina users should be able to scale the interface for enlarged fonts. Even if the graphics and emojis become somewhat pixelated, at least the app will be usable. Right now the font size is way too small, giving me a lot of stress while trying to communicate with my peers.

### Actual behaviour
No scaling option available #sad #suicide #help

### Configuration
**Operating system:** MacOS Sierra

**Version of Telegram Desktop:** 1.1.18

**Comment by stek29** [comment]
200% is default scaling option on retina. 
You can't scale over 200 currently, see #3158.
