### ISSUE TITLE
Differences between the Linux and Windows versions what should be erased

### ISSUE THREAD

**Issue by sergioad** [telegramdesktop/tdesktop#379]
Hello @telegramdesktop I noted some differences between the Windows and Linux versions, some things what I want have here on Linux becaue them ROCKS

1.- the CSDs

On windows the TDesktop's window does not has a SSD (Server Side Decoration / normal titlebar), instead of the mentioned SSD it uses a BEAUTYFULL CSD (Client Side Decoration / it does not has titlebar and has the window controlls on the main bar) why on Linux we have SSDs on the client instead of the CSDs?

This is very strange because Linux has one of the best CSDs implementations on the OS ecosystem, only see the Gnome's CSDs and you will see that, I hope see this feature soon because it will make the Linux version more eye candy than now, this will improve the user experience and atract more people

2.- (and one of the most requested ones) the tray icon

On Windows you use a beautyfull and functional tray icon that lets to the client work in background and advice to you where you get a message, this feature is now possible thanks to the colaborations of @Rush

Both features are very important and I want to see them on Linux, can you implememnt them?

**Comment by nbasov** [comment]
+1 for tray icon. Very uncomfortable to use telegramm without this.

**Comment by sergioad** [comment]
Yes, also the CSDs are AWESOME, I want these features soon

**Comment by gespadas** [comment]
+1 for tray icon !!!

**Comment by sergioad** [comment]
@gespadas nice to see you here, did you have noted that the Linux version has not the beautifull CSDs present on the Windows version?

**Comment by gespadas** [comment]
@sergioad No idea, I don't use Windows since... I can't remember when XD

**Comment by sergioad** [comment]
LOL I see, let me show the image to you

**Comment by telegramdesktop** [comment]
Tray icon using libappindicator with fallback to gtk_status_icon, if libappindicator is not installed, will be added in 0.7.7. I don't know actually, will it work on your system.

**Comment by sergioad** [comment]
@telegramdesktop and what about the CSDs? (client side decorations)

**Comment by gespadas** [comment]
@telegramdesktop I have libappindicator installed on my system (I use ArchLinux + Openbox), but there's no tray icon when launching the Telegram Desktop Client (installed from AUR).
![libappindicator](https://cloud.githubusercontent.com/assets/70158/5777243/206247a2-9d56-11e4-9979-0116d62af0af.png)

**Comment by sergioad** [comment]
@gespadas wait to the 0.7.7.1

**Comment by gespadas** [comment]
@sergioad okas!

**Comment by Nexion** [comment]
Just updated to 0.7.10, tray icon (and afair there were relevant settings also) is absent again :c Pleease, enable it again. It's really uncomfortable to have a constantly open window of IM application and to incidentally close it competely by habitual clicking on the button in window title to hide it.

**Comment by nbasov** [comment]
tdesktop team, thank you so much for your work!

**Comment by AsavarTzeth** [comment]
The problem with CSD is it will look great in some environments, but less so in others. For a popular app like this I prefer an okay looking app for all of Linux.

That being said, I am a Gnome Shell user and I love their native apps. But this is QT, not GTK+, it would not be the same. I would also hate it if it was locked to a certain theme and I was unable to change it to somewhat match everything else.

**Comment by sergioad** [comment]
@AsavarTzeth the Windows version has CSDs and it is also Qt

**Comment by AsavarTzeth** [comment]
@AsavarTzeth yes thank you, I can read :) I am aware of that. What is your point though?

To qoute yourself, you say 
>"Linux has one of the best CSDs implementations on the OS ecosystem, only see the Gnome's CSDs"

Again, this is not GTK+, so even if I do agree with your statement, your example really is not that usefull in this case. Something more usefull would be examples of good looking CSD/QT apps for Linux. These should then preferably also look good with any or most DEs.

All that being said, if it is somehow possible to make it at least as good looking as the Gnome apps that feature the GTKHeaderBar, while keeping it themable (for a unified desktop look), I might reconsider this.

**Comment by stek29** [comment]
Wait, but this issue isn't fixed...

![image_2016-11-07_21-12-47](https://cloud.githubusercontent.com/assets/11808223/20075255/887f8726-a544-11e6-833f-e48844f95930.png)
