### ISSUE TITLE
Again, CPU Usage

### ISSUE THREAD

**Issue by matteyas** [telegramdesktop/tdesktop#3793]
### Steps to reproduce
1. Use Telegram
2. Keep Telegram running.
3. Check historical CPU time usage

### Expected behaviour
Telegram, that is mostly idle in the background (in my use case), should use practically no CPU. Just for reference, Telegram is currently *minimized* and is using between 6 and 9 percent CPU.

### Actual behaviour
Telegram beats all other mostly-idle-processes by at least an order of magnitude.

### Pics or it didn't happen
![image](https://user-images.githubusercontent.com/12509132/29252574-9960b040-806a-11e7-8ff1-573cbca4cf64.png)

### Configuration
OS: Windows 10 Professional (64-bit)  
CPU: i5-4690K  
GPU: GTX 970  
RAM: 16 GB  
Telegram: 1.1.19

**Comment by john-preston** [comment]
@matteyas Sorry about that =(

**Comment by kmare** [comment]
Could you try what's described by Yetangitu here #3640 and report back if it actually works?
Thanks!

**Comment by matteyas** [comment]
@kmare The suggestion seems to work, yes. It was hovering around 5% constantly (with swings up and down), switch to the emoji tab on the smiley interface, now it's back to 0% CPU.

I'll restart Telegram to reset the historic usage log, and see if this is a stable fix (workaround) after some usage as well.

Any devs know about this discovery?

**Comment by juanjux** [comment]
Same here, in Linux (Ubuntu 17.04), suggestion also worked.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3640
