### ISSUE TITLE
Calls are stuttering when calling android clients from an Arch Linux based system

### ISSUE THREAD

**Issue by Bleuzen** [telegramdesktop/tdesktop#3795]
### Steps to reproduce
1. Install TDesktop on an Arch based linux system
2. Call someone who uses Android

### Expected behaviour
There should be no stuttering.

### Actual behaviour
Sound stutters sometimes.

### Configuration
**Operating system:**
Manjaro Linux KDE

**Version of Telegram Desktop:**
1.1.19

**Used theme**:
https://github.com/PapirusDevelopmentTeam/arc-kde/tree/master/extra/telegram

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

Hi when I call someone on Android using TDesktop on Manjaro Linux, the sound stutters sometimes.
This is not the case, when calling from Android to Android or from TDesktop on Arch Linux to TDesktop on Arch Linux (or a spin of, for example Manjaro).

Here are 2 recordings:

[callsstutteringissueexamples.zip](https://github.com/telegramdesktop/tdesktop/files/1222635/callsstutteringissueexamples.zip)

I don't know, if i should upload my "last_call_log.txt" here, because it contains our IPs.

Here is a screenshot of the debug infos during such a call:
![screenshot_20170814_165049](https://user-images.githubusercontent.com/12885163/29278818-21346b6e-8116-11e7-8095-0f661dde102b.png)

**Comment by Aokromes** [comment]
@Bleuzen Try on 1.3.14 :)

**Comment by Aokromes** [comment]
no answer for more than a year, closing.
