### ISSUE TITLE
Filenames are cut to 35 characters on upload

### ISSUE THREAD

**Issue by eljenso** [telegramdesktop/tdesktop#3797]
### Steps to reproduce
1. Upload file with more than 35 characters in filename (excluding extension)
2. Download file on another system (e.g. mobile)

### Expected behaviour
File should have same name like the file which was uploaded.

### Actual behaviour
Filename was cut to 35 characters (plus extension)

### Configuration
**Operating system:**
Fedora 26

**Version of Telegram Desktop:**
1.1.19

**Used theme**:
Default

**Comment by mazi5769** [comment]
method:%20auth.sendCode%20Result:%20{"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_64987"}

**Comment by Medioman92** [comment]
this is affecting also windows 10 and Mac OS 10.12.x

**Comment by stek29** [comment]
Those are server-side limitations.
Here are some tests I made, if you're interested: https://t.me/joinchat/AAAAAEdPtLUeuQ125MHtGw

**Comment by AndydeCleyre** [comment]
It would be nice if the client side app warned the user and offered an opportunity to rename each upload. It is currently possible to upload a large series of similarly named files only to lose the distinguishing parts of the filenames, with no way of knowing which file is which without downloading them.
