### ISSUE TITLE
"Could not send an empty file" if photo path contains ñ

### ISSUE THREAD

**Issue by Lonami** [telegramdesktop/tdesktop#3799]
### Steps to reproduce
1. Download a Wal Ter photo to some location containing `'ñ'` in its path.
2. Copy it from the file manager and paste on Telegram Desktop, or drag it to send it.
3. Wal Ter is not sent:

![photo_2017-08-16_17-07-30](https://user-images.githubusercontent.com/6297805/29370366-6af76ea0-82a5-11e7-82c6-b6aeba34a1fb.jpg)

### Expected behaviour
The Wal Ter meme should have been sent to Durov.

### Actual behaviour
Poor Durov is left without Wal Ter memes.

### Configuration
**Operating system:** Arch Linux, Kernel: x86_64 Linux 4.12.6-1-ARCH, WM: Xfwm4

**Version of Telegram Desktop:** 1.1.19 alpha.

**Used theme**: A dark one.

**Comment by Lonami** [comment]
Seems to work under Windows.

**Comment by stek29** [comment]
Please check your `LC_ALL`
#3784

**Comment by Lonami** [comment]
Yep thanks @stek29 closing in favour of #3784, `LC_ALL` is empty.
