### ISSUE TITLE
[Critical] Telegram kills audio, becomes a zombie process and refuses to open.

### ISSUE THREAD

**Issue by kneuro** [telegramdesktop/tdesktop#3800]
### Steps to reproduce
1. Download Telegram tarball from official website
2. Extract tar into directory
3. Attempt to run Updater or Telegram

### Expected behaviour
Telegram should open and run without a problem.

### Actual behaviour
Does not open, becomes a zombie process and mutes/kills currently playing audio. Unable to capture debug logs because once again, Telegram will refuse to even open past a certain point. 

### Configuration
**Operating system: Xubuntu 16.04 LTS 64bit**

**Version of Telegram Desktop:**
1.1.19

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary) (From inside the terminal):
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"

</details>

**Comment by stek29** [comment]
What are audio settings? Do you have alsa/pulse/whatever?
Can you run TDesktop in debugger and look if you can see where it gets stuck?

**Comment by kneuro** [comment]
I have Pulseaudio. Let me run it in debugger mode, last time I tried it wouldn't do it. Maybe I'm entering the command wrong?

**Comment by stek29** [comment]
I meant running tdesktop in actual debugger, or profiling it somehow.

**Comment by stek29** [comment]
See [this email](http://plug.org/pipermail/plug/2010-August/023681.html) for example.

**Comment by kneuro** [comment]
Eh, doesn't matter, I fixed it. I added "tsched=0" to the "/etc/pulse/default.pa" file.

Seems to work without a problem now. Not sure why that changed anything, but it's Pulse specific.

**Comment by kneuro** [comment]
Also, I'm not finding a general debugger for this kind of app. GDB (GNU Debugger) is meant for C/C++ programs compiled in GCC, I think.

**Comment by stek29** [comment]
Then I guess your sound driver is buggy.

**Comment by kneuro** [comment]
Something! It was weird. It'd only happen with Telegram, not Discord or Skype or anything. Guessing there's some sort of flaw with the driver where it needs to be set to no buffer for realtime audio.

**Comment by stek29** [comment]
@kneuro Idk, never had any issues with pulse when used linux. But googling for _pulse tsched_ gives a lot of messages saying about broken drivers.
