### ISSUE TITLE
[Feature request] Mark message as read from desktop notification popup.

### ISSUE THREAD

**Issue by Trost123** [telegramdesktop/tdesktop#3803]
It would be really cool if you could mark a message as read from desktop notification.
We could add a ✔️ icon next to ❌  icon, that would mark shown message(s) as read. (Decreasing the number in tray icon)

This will be very convenient when someone send you a message like "Ok", "Yes", "No", so you don't have to open the main window just to reset the new messages count on tray icon.
I really hope you can implement this. Thanks! 🙏

**Comment by stek29** [comment]
Send empty message

**Comment by Trost123** [comment]
Thanks for the tip, it works! 👍 
Could be really cool if you could do it with one click though. (Right now it takes click+enter and is not intuitive\documented)

**Comment by john-preston** [comment]
@Trost123 You can mark them read on macOS and when using custom notifications by sending space " " or empty message in reply from the notification.

**Comment by Trost123** [comment]
@john-preston 
stek29 already shared that secret technique with me, thx. It also works in Windows 7 for me.  
I'm just suggesting that it could be realized more obviously with a button in notification window.
