### ISSUE TITLE
[Feature Request] Extend contact and channel management via tags labels.

### ISSUE THREAD

**Issue by rPman** [telegramdesktop/tdesktop#3805]
When i use telegram desktop, list of contacts increasing too much, but i see only names and last message in list, it's too complex to search needed contact not by name.

Best method to do this much easiest, adding custom list of tags labels for each contact and channel, show it instead last message and allow use this names in filter (for example comma separated and using + sign for AND condition, otherwise OR).

For contact or channel add to menu item for adding tag label from list and new custom.

Also need interface button near filter editbox to see list of all custom labels and use it in filter via one click.

**Comment by TiagoDanin** [comment]
See #1107 :)

**Comment by stek29** [comment]
@TiagoDanin this is different from #1107 imho.
I think I've seen a request like this already, but I can't find it.

**Comment by rPman** [comment]
I think so too, this is different, because multiple tags for each contact more comfortable than one.
But, first tag can be treated as category.

**Comment by slonofanya** [comment]
+1. Who could take care of it?

**Comment by auchri** [comment]
There is no api for labels or categories.

**Comment by slonofanya** [comment]
@auchri Maybe you could propose the write this feature request in another repo, don't you?

**Comment by auchri** [comment]
@slonofanya There is no repo for the api

**Comment by slonofanya** [comment]
@auchri Any issue trackers?

**Comment by auchri** [comment]
@slonofanya Nope. You can contact Telegram at Twitter: https://twitter.com/telegram

**Comment by slonofanya** [comment]
ok, thanks

**Comment by stek29** [comment]
@slonofanya or contact inapp support.

**Comment by rPman** [comment]
It can be realised only for local desktop installation, no server api needed, for begining.

**Comment by stek29** [comment]
@rPman No, it can't, that's project policy. Telegram Desktop is part of "Telegram Solution", and it can't add any features "just for local"
Even if it does, it won't be made by Developer, but PR likely won't be merged.
Also, to make this programmer should be familiar with tdesktop's codebase to add everything needed, including encrypted serialization, saving, making search and filtering fast, adding proper ui stuff.
