### ISSUE TITLE
Open "small pictures" in link previews from the app

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#3806]
### Steps to reproduce
1. send a link to a webpage which contains an image **but** it's not a direct link to an image
2. click on the small picture displayed in the preview

### Expected behaviour
The picture is opened from the app itself, [like the Android client does](https://streamable.com/lxoup)

### Actual behaviour
Telegram Desktop opens the url in the browser ([video](https://streamable.com/cjb9f))

### Configuration
**Operating system:** Windows 10/7

**Version of Telegram Desktop:** alpha 1.1.19 portable

**Used theme**: default

**Comment by stek29** [comment]
#3488
