### ISSUE TITLE
GNOME: Tray icon disappears when locking GNOME with GDM3

### ISSUE THREAD

**Issue by Feichtmeier** [telegramdesktop/tdesktop#3807]
### Steps to reproduce
1. Open telegram in gnome (3.20, 3.22 and 3.24)
2. Lock the screen with GDM3
3. Telegram tray icon is gone (other legacy indicators stay like chrome, insync, dropbox)

### Expected behaviour
Tray icon should still be there
### Actual behaviour
Telegram icon is gone
### Configuration
**Operating system:**
Ubuntu GNOME 17.04 and 16.04

**Version of Telegram Desktop:**
1.1.19
**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Aokromes** [comment]
#2191

**Comment by stek29** [comment]
No, this is not a duplicate: it's about tray icon missing after locking screen

**Comment by Aokromes** [comment]
well, the thing is it don't must exist acording that XD

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2191#issuecomment-332231133 and now totally removed.
