### ISSUE TITLE
GNOME: Telegram freezes the system for a while when moving the call window

### ISSUE THREAD

**Issue by Hasbreak** [telegramdesktop/tdesktop#3812]
Hello!
I just migrated from KDE Plasma to GNOME Shell, and I've already found out new issue to get a rid of.
So, the following one causes Telegram itself and GNOME Shell to freeze for a while if the call window is being moved or allocated by the mouse pointer. While being moved "forcefully", the window lags a lot unless it causes the hang.

### Configuration
Operating system: Freshly updated Arch Linux

Version of Telegram Desktop: 1.1.19 stable

**Comment by auchri** [comment]
Use the template please.
