### ISSUE TITLE
GNOME: Telegram call window can cause GNOME shell to freeze.  

### ISSUE THREAD

**Issue by Bryophyllum** [telegramdesktop/tdesktop#3814]
### Steps to reproduce
1. Open Telegram as usual;
2. Make a call;
3. Move the call window over the desktop while calling to one.

### Expected behaviour
There should be no issue with moving the window.

### Actual behaviour
The following bug causes GNOME Shell to freeze for a while. Moreover, when the window is moved "forcefully", its movement is choppy, and it lags a lot unless the GNOME is hung.

### Configuration
**Operating system:Arch Linux*
**GPU:GTX 10xx series|NVIDIA proprietary driver version 384.59-5*
**GNOME Shell version:3.24.2*

**Version of Telegram Desktop: 1.1.19 stable**

**Used theme**: Breeze.v3

**Comment by Aokromes** [comment]
@Bryophyllum Try on 1.3.14 :)

**Comment by Aokromes** [comment]
no answer for more than a year. closing.
