### ISSUE TITLE
Ubuntu 14.04 no notification numbers in unity launcher

### ISSUE THREAD

**Issue by heihachi88** [telegramdesktop/tdesktop#382]
When i launch telegram from my 2nd partition (mounted in /etc/fstab) i get no notification number on upper right corner of the icon:

http://i.snag.gy/BPqnB.jpg

**Comment by aseredenko** [comment]
+1

**Comment by Brawl345** [comment]
I don't think Telegram for Linux has a notification badge for Telegram, because I don't get it either.

**Comment by lpenguin** [comment]
Hi guys! Here is my tdesktop fork with unity layncher support: [Grab builds here](https://github.com/lpenguin/tdesktop/releases). Works on Ubuntu 14.04 x64

**Comment by Brawl345** [comment]
Great! But I can't download it, I get an XML file with "NoSuchKey" - "The specified key does not exist."

**Comment by lpenguin** [comment]
it was some weird github bug - it does not work properly with dots in file names. try again now :)

**Comment by telegramdesktop** [comment]
Launcher count support added in 0.7.7, but I'm not sure it's working in all cases.

**Comment by dmitry-sensei** [comment]
Yes. In OpenBox windows manager with tinit2 tray Notifications are not cleared fully. (i.e. notification about updated version to 0.7.7

**Comment by bil-elmoussaoui** [comment]
The same as this one #956
