### ISSUE TITLE
[FR] Notice to new chat - Telegram block your for week+ for trying to talk

### ISSUE THREAD

**Issue by wucorabalo** [telegramdesktop/tdesktop#3820]
### Steps to reproduce
1. Register in telegram desktop and use it
2. Friends gives you nicknames to add in telegram and all think that it is ok
3. You add one more friend by nickname and write him: "Hi iam your friend Pavel Durov, can we talk?" and friend do second:
  -report spam you caz he noob
  -report spam caz he psycho today
  -blackmailing you he can "report spam" or give him money not to report
  -other
4. He report you 
5. you see this: "Sorry, you can only send messages to mutual contacts at the moment"
6. You blocked for week in telegram and you can be blocked at future more because telegram generous to interlocks.
7. Your life process destroyed caz telegram surprise you. You cant talk with friends you add by nickname before and with whom you talk too much or have a business.

### Expected behaviour
1. Informate your users!!!! Any new chat must have it notice - "you can be reported and blocked all contacts just caz dont use nicknames, we trap you with that" , and button: "OK"
2. It must be no secrets what troll report you, if someone report you - chat log it to both and cant be deleted from contact list at the end of the month or till support process both applications.
Block can be only local and not common to whole telegram. You also must give information to your users about no-nickname talking, telegram must have it manifest: 
Telegram in not free talking program! You can talk only with !mutually! has a telephone.

### Actual behaviour
Lost time and missed opportunities
Support email and spam email dont ans. you more than week and It seems you will never be answered

### Configuration
**Operating system:** any

**Version of Telegram Desktop:** any

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
Why do you create two issues?

**Comment by wucorabalo** [comment]
It is not twice , do you even know how to read?
It is reqest about providing information in order not to divorce its users
