### ISSUE TITLE
Markdown in picture descriptions is not being rendered

### ISSUE THREAD

**Issue by sanlyx** [telegramdesktop/tdesktop#3821]
### Steps to reproduce
1. Send an image to a chat
2. Type some markdown in the image description
3. Enjoy your message being displayed without Markdown rendering

### Expected behaviour
Markdown-formatted text shall be rendered appropriately.

### Actual behaviour
The picture description is displayed as plain text.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.1.19

**Used theme**: Default

**Comment by stek29** [comment]
This is an API issue, sorry.
