### ISSUE TITLE
[Request] Notice on install: "Desctop version Guarantees communication only both having a phone in contacts"

### ISSUE THREAD

**Issue by wucorabalo** [telegramdesktop/tdesktop#3823]
### Steps to reproduce
1. Get reported
"[FR] Notice to new chat - Telegram block your for week+ for trying to talk"
 https://github.com/telegramdesktop/tdesktop/issues/3820
 when write first time "Hi iam your friend Pavel Durov, can we talk?" and blocked talking to mutual contacts only

### Expected behaviour
Notice on install: "Desctop version of telegram Guarantees communication only those who have a mutual phone"

### Actual behaviour
be banned

### Configuration
**Operating system:** any

**Version of Telegram Desktop:** any

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
Easy solution: Don't write random people.

**Comment by wucorabalo** [comment]
what? iam write to friend to add me

**Comment by auchri** [comment]
@wucorabalo If he report you he is maybe bot your friend 🤷🏼‍♂

**Comment by wucorabalo** [comment]
It Reqest  is not about talking it is about text- Notice/Warning  before you can be banned. Is it too much?
