### ISSUE TITLE
[Request] Protection from trolls, when they met on nicknames, automatically interchange and send the phone

### ISSUE THREAD

**Issue by wucorabalo** [telegramdesktop/tdesktop#3824]
### Steps to reproduce
1. Meet your friend by nickname and think life is good
2. Recive random report spam and dont talk week+
https://github.com/telegramdesktop/tdesktop/issues/3820
[FR] Notice to new chat - Telegram block your for week+ for trying to talk
3. Trying give telegram one more chance to use it, asking each to take your phone

### Expected behaviour
[Request] Protection from trolls, when they met on nicknames, automatically interchange and send the phone
Button that send your phone and ask friend accept it by yes/no to be protected from trolls "spam report"
AS KNOW AS AT THIS WORL DIMENSION AS  "FRIEND REQEST" OMG

### Actual behaviour
use skype and dont trust Durov traps more

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
Not related to Telegram Desktop

**Comment by wucorabalo** [comment]
How it is not? Now iam ask it each people accept my phone in chat, i use only Desctop version and it dont grab contacts from phone, caz it separate devices. Friends must add it  by hands.
Why you close this, are you typical "go out" support??

**Comment by auchri** [comment]
@wucorabalo This protection exists for a reason. If your "friends" report you, they don't want that you write them.
I don't really understand why you don't use your phone.
However, I'm not a support. If you need support, you should use the in-app support or contact Telegram on Twitter.

**Comment by wucorabalo** [comment]
@auchri, understandably, I and you, and the whole world have experience of communication in instant messengers.
I like pc not phones, and there is the system itself is not thought out for you about that problem.

I am asking in this reqest:
1. We have friends that add by phone or nickname and they have no my phone
2. Add button "send my phone" with function:  send my phone number to friends with messange "please accept my phone". Buttons with "accept and add" and "NO"

And I described a strong reason why it function must be!
