### ISSUE TITLE
error on ./configure

### ISSUE THREAD

**Issue by noorzaie** [telegramdesktop/tdesktop#3825]
I have this error on ./configure :

`ERROR: opus not found using pkg-config`

this is contents of config.log :

`cl -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -D_WIN32_WINNT=0x0502 -nologo -I/mingw64/include/opus -libpath:/mingw64/lib -c -Fo./ffconf.A99hjWvt.o ./ffconf.axZjBSHv.c
cl : Command line warning D9002 : ignoring unknown option '-libpath:D:/msys64/mingw64/lib'
ffconf.axZjBSHv.c
./compat/windows/mslink -LIBPATH:/d/TBuild/Libraries/opus/win32/VS2015/Win32/Release -nologo -LARGEADDRESSAWARE -I/mingw64/include/opus -libpath:/mingw64/lib -out:./ffconf.0rkR6H81.exe ./ffconf.A99hjWvt.o opus.lib m.lib psapi.lib advapi32.lib shell32.lib
LINK : warning LNK4044: unrecognized option '/ID:/msys64/mingw64/include/opus'; ignored
LINK : fatal error LNK1181: cannot open input file 'm.lib'
ERROR: opus not found using pkg-config`

what is the problem??

**Comment by auchri** [comment]
@noorzaie The problem is that opus is not found.

**Comment by noorzaie** [comment]
@auchri I've already built opus. and I have this directory :

`D:/TBuild/Libraries/opus/win32/VS2015/Win32/Release`

**Comment by stek29** [comment]
_using pkg-config_

**Comment by noorzaie** [comment]
I've followed this instruction step by step :

[https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md](url)

**Comment by mydexterid** [comment]
That is your problem then. That links leads to a 404 page :)
