### ISSUE TITLE
Night Mode doesn't alter the wallpaper

### ISSUE THREAD

**Issue by S-punk** [telegramdesktop/tdesktop#3833]
Night Mode in TDesktop won't alter the user-set wallpaper if enabled. A bright wallpaper, if set, won't fit the dark environment.

TDesktop should have a setting for a separate Night Mode wallpaper or at least change the wallpaper to a hardcoded one specifically tailored for dark environment.

Version of TDesktop: 1.1.19
![2017-08-25 16_29_56-telegram](https://user-images.githubusercontent.com/31348910/29717048-6bd8dc06-89b6-11e7-8a34-a3a658df53ef.png)

**Comment by stek29** [comment]
See #3598.
