### ISSUE TITLE
Option to disable tray counters from bots/channels

### ISSUE THREAD

**Issue by JhonSane** [telegramdesktop/tdesktop#3834]
### Steps to reproduce
1. Select bot or channel
2. Take options
3. "Disable notifications"
4. Notifications in tray shows as gray

### Expected behaviour
Option in selected contact menu to disable "tray-counters" from bots/channels. So we will have tray notif. only from peoples and stay bots as entertiment
Menu type:
"disable notifications"
"disable tray"

### Actual behaviour
just annoying counters in tray not from peoples

### Configuration
**Operating system:** windows 8

**Version of Telegram Desktop:** 1.1.19

**Used theme**: defaul theme

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by 24252411** [comment]
Iam not susccribed is a complete error .  I am sick and tired of this .

2017-08-25 10:59 GMT-05:00 Jhon S <notifications@github.com>:

**Comment by MasterGroosha** [comment]
I'm sorry, but isn't "Include muted chats to unread counter" option the one you're looking for?
