### ISSUE TITLE
Better night mode

### ISSUE THREAD

**Issue by stek29** [telegramdesktop/tdesktop#3835]
_[From this comment](https://github.com/telegramdesktop/tdesktop/issues/3598#issuecomment-312366583)_

It would be nice to use "night mode" as a way to have two different themes installed. 

### Suggested behaviour & Steps to reproduce
- User installs custom theme `#1`
- He enables night mode (TDesktop's built in night mode theme gets activated)
- He installs custom theme `#2`
- Now when he disables night mode he gets theme `#1`, and when he enables it he gets theme `#2`

So night mode would be independent theme "profile" with different default theme, completely independent from light mode.

**Comment by john-preston** [comment]
@stek29 Yes, I thought about that. This is a serious task.

**Comment by tyl3r** [comment]
You guys can make it simple, just let the user choice for both default themes (normal and night mode) in a easy way, it would be nice to add 2 additional text buttons or 2 images (⚪️/⚫️ or 🌞 / 🌚) when you preview a theme, the buttons act for set as default: default theme / night mode theme, then in preferences just rewrite the options, remove the actual "user default color theme" for something like "default theme: X (Restore to default)" and "night mode theme: Y (Restore to default)", then the night mode switch just change between the 2 defined themes. Hope you like the idea.

**Comment by andreyorst** [comment]
I wonder if there is an ability to make both light and dark variant in a single theme. Something like in GNOME for example. In GNOME 3 there are two css files, named gtk.css and gtk-dark.css. User can enable or disable dark theme variant in settings by toggling the switch. Some applications, that support dark mode use gtk-dark.css by default and fallback to gtk.css if there is none.

If telegram will support such thing, there will be no need to set two different themes, a switch will remain in settings if user theme supports nightmode.

**Comment by krupenja** [comment]
Was this closed because this feature is implemented in the upcoming release?

**Comment by Johnnynator** [comment]
It should already be in the alpha release

**Comment by krupenja** [comment]
@Johnnynator Great, thankS!
