### ISSUE TITLE
Have "Delete for <username>" option checked by default when deleting a personal message

### ISSUE THREAD

**Issue by Woowoo678** [telegramdesktop/tdesktop#3836]
### Steps to reproduce
1. Attempt to delete one of your messages in a private message dialog

### Expected behaviour
"Delete for <username>" checkbox to be checked by default, as this would be the most common intention

### Actual behaviour
"Delete for <username>" is not checked by default, leaving me to have accidentally hidden my embarrassing, accidental message from my own view, making it impossible to delete for the other person.

### Configuration
**Operating system:**
Fedora 25 XFCE

**Version of Telegram Desktop:**
1.1.19
**Used theme**:
Default

**Comment by stek29** [comment]
#3334

**Comment by stek29** [comment]
(I know it's a bit different, but they both provide a solution for problem and #3334's solution is more general and flexible, and doesn't break current behaviour)
