### ISSUE TITLE
Show link URL in the bottom left

### ISSUE THREAD

**Issue by MaxMatti** [telegramdesktop/tdesktop#3837]
Would it be possible to show the link URL of a link in the bottom left of the chat window like browsers currently do?

The current setting (in the tooltip) is a bit tedious when checking a few links to find the one that leads to the desired destination and I think most people (or at least me) are used to seeing the URL of a link in the bottom corner.

Edit: and I would tag this as a feature request - if I could. Sorry.

**Comment by jeffythedragonslayer** [comment]
I tried checking this out and can't see any tooltips at all.  (Windows 10 with v1.9.20)  Is there something special I need to do to enable them?

**Comment by Remu-rin** [comment]
You need to hover over hyperlink showed as words, not regular link showed as link. Example: https://t.me/telegram/123
P.S. It's sad that https://github.com/telegramdesktop/tdesktop/issues/5276 is still not fixed.
