### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by noorzaie** [telegramdesktop/tdesktop#3838]
I get error below, when running command `..\depot_tools\fetch breakpad` :

`File "D:\TBuild\Libraries\depot_tools\gclient_eval.py", line 167, in _convert
    return _convert(node.left) % _convert(node.right)
TypeError: not all arguments converted during string formatting`

What's the problem??

**Comment by pracheth** [comment]
@noorzaie How'd you resolve this?

**Comment by noorzaie** [comment]
This error was because of some mistakes during build processes. I've repeat all steps again and build it successfully.
