### ISSUE TITLE
Pressing UP button to edit latest sent message doesn't work after sending empty message

### ISSUE THREAD

**Issue by DarthJahus** [telegramdesktop/tdesktop#3840]
### Steps to reproduce
Video 🎥 : https://youtu.be/w0oF2xBlFnM
1. Send a message
2. Write two spaces (for example) and press ENTER to send
3. Press UP to edit latest sent message

### Expected behaviour
I don't know how TDesktop handles empty messages, but it looks like it is sending them, losing the track of the latest "real" message.

### Actual behaviour
Maybe it can handle this case locally, and just clean the text box if it is known to result in a void message, this way, pressing UP to edit would still work.

### Configuration
**Operating system:** Windows 10 16251.1000

**Version of Telegram Desktop:** 1.1.19 Alpha

**Used theme**: Default day theme

**Comment by DarthJahus** [comment]
I apologize if it's the expected behaviour, but this may enhance it.

**Comment by stek29** [comment]
Some people say it's not a bug and it's used to get old up key behaviour...
I don't think that's needed, since you can type something without sending to scroll with up key.

**Comment by Udeet1107** [comment]
Can I work on this?
I want to start contributing to Telegram. If it is a bug, then I can start looking into fixing it

**Comment by stek29** [comment]
Sure, why not :)

**Comment by 23rd** [comment]
Looks like it's fixed.
