### ISSUE TITLE
Option to disable URL images compression

### ISSUE THREAD

**Issue by Yanrishatum** [telegramdesktop/tdesktop#3841]
### Steps to reproduce
1. Send link to a PNG image.
    1. Example 1: https://i.imgur.com/yficJ0m.png
    2. Example 2: http://pixeljoint.com/files/icons/full/omi.png
2. Click on it for preview or just look at the in-chat thumbnail.

### Expected behaviour
No JPEG artifacts should be present. And next images should be visible:
![with-text](https://i.imgur.com/yficJ0m.png)
![pixelart](http://pixeljoint.com/files/icons/full/omi.png)
### Actual behaviour
Image preview have visible JPEG artifacts which are pretty visible for images with text and on pixel art.
![with-text](https://i.imgur.com/B0dKZD6.png)
![pixelart](https://i.imgur.com/qnhZJOU.png)
(Look at the hands, where artifacts are most obvious)

### Proposal
Option to disable compression of url-loaded images and displaying them as-is.  

### Motivation
While I understand that jpeg used to save disk space, not everyone need to save said disk space (we're living in a time where 1TB+ disks are the norm) and would prefer seeing the image without any compression. This problem is especially frustrating when working with pixel art.

### Configuration
**Operating system:** Win 10

**Version of Telegram Desktop:** 1.1.9

**Used theme**: Customized dark-orange (don't remember the name, was modded manually after applying, but not relevant to issue as same behavior present with default theme)

**Comment by john-preston** [comment]
@Yanrishatum The link previews are generated by server so unfortunately it is not possible to show something else on the client side :(

**Comment by Yanrishatum** [comment]
@john-preston And I suppose there won't be even slight chance telegram core would implement such feature? That compression problem bugged me since the very beginning of my experience with Telegram.
Also no chance of workarounding issue by downloading image by direct url instead of asking telegram server for preview?

**Comment by john-preston** [comment]
@Yanrishatum This could be done in some custom (unofficial) telegram app. In general it is not a good idea to automatically query each received link in order to perhaps show a .png image.

For me personally (and for almost all users I guess) it is not a problem at all, because .png links are not shared frequently. It is easier to send the document without compression inside Telegram.
