### ISSUE TITLE
No video messages in shared media section

### ISSUE THREAD

**Issue by ruv** [telegramdesktop/tdesktop#3843]
### Steps to reproduce
1. Open a group info (the group should have shared voice and video messages).
2. Look at "Shared media" section
3. Why there is a "voice messages" link and there isn't a "video messages" link?

### Expected behaviour
There should be a link to "video messages".

### Actual behaviour
There isn't a link to "video messages".

**Version of Telegram Desktop:**
1.1.19

**Comment by stek29** [comment]
#3480
