### ISSUE TITLE
Emoji autocomplete doesn't work on Linux client

### ISSUE THREAD

**Issue by fourlastor** [telegramdesktop/tdesktop#3846]
### Steps to reproduce
1. Start typing :e

### Expected behaviour
Emoji autocomplete should appear

### Actual behaviour
No emoji autocomplete appears

### Configuration
**Operating system:**
Ubuntu 17.04, Unity version

**Version of Telegram Desktop:**
1.1.19

**Used theme**:
Don't know where to find this

**Comment by john-preston** [comment]
@fourlastor You need to enable emoji replacements in Settings.

**Comment by fourlastor** [comment]
Oh, I see, that makes sense, closing.
