### ISSUE TITLE
REQUEST: Bookmark/Star/Save Messages in Chats for future acces

### ISSUE THREAD

**Issue by Cherry88x** [telegramdesktop/tdesktop#3849]
Would be nice to have a feature in all Telegram versions to bookmark messages and give them a name to save them and find them again like in the Webbrowsers.

_Example usage:_ 

_Recipes sent to you.
Stories.
Funny voice messages.
Quotes._

For normal chats you can go up to the Avatar and you can see the bookmarks like "**shared media**" "**shared files**" etc.

In group chats maybe the same just with the username. 

Would be nice to get Feedback and support for this feature.

**Comment by rgschi-tgm** [comment]
+1 for this feature, I would be happy to see it in the future! 👍

**Comment by stek29** [comment]
#1312
