### ISSUE TITLE
Make chocolatey an official Windows release channel

### ISSUE THREAD

**Issue by adamralph** [telegramdesktop/tdesktop#385]
These days I have to think twice before installing anything which isn't on chocolatey - https://chocolatey.org/.

There is an unofficial package on there right now https://chocolatey.org/packages/tdesktop but it's way out of date.

**Comment by auchri** [comment]
I think it's better to make telegram desktop available via the build in package manager in windows 10: http://www.howtogeek.com/200334/windows-10-includes-a-linux-style-package-manager-named-oneget/

**Comment by adamralph** [comment]
OneGet uses chocolatey as one of its sources, so by putting it on Chocolatey now, you are supported both *now* (Windows 8.1 + chocolatey) and *future* (Windows 10 + Chocolatey/OneGet).

**Comment by ianhyzy** [comment]
Doesn't telegram auto-update anyway? You only need to install it once.

**Comment by adamralph** [comment]
But I may be doing that regularly, and on many machines, and I may want a script for doing this. Such a script will be far easier to maintain if it's just a list of chocolatey install commands, rather than a specialized stuff for each app and the maintenance burden that comes with that.

**Comment by telegramdesktop** [comment]
Well, if $url there does support redirects you should just use "https://tdesktop.com/win/current" for the setup download link:

![image](https://cloud.githubusercontent.com/assets/6113871/5775160/90d553c2-9d87-11e4-8814-c093fafd92af.png)

I don't see what should I do here.

**Comment by adamralph** [comment]
The proposal was for telegram desktop to adopt chocolatey as an *official* release channel, i.e. maintained by the owners of Telegram desktop, so when you push out a release, chocolatey is one of the places you push to.
