### ISSUE TITLE
Search fails with @ prefix

### ISSUE THREAD

**Issue by iwkse** [telegramdesktop/tdesktop#3850]
### Steps to reproduce
1. Type try@test.com
2. Search for test.com

### Expected behaviour
Show the try@test.com matched term

### Actual behaviour
Doesn't show it

### Configuration
**Operating system:** Debian Linux 64bit

**Version of Telegram Desktop:** 1.1.19

**Used theme**: default

**Comment by stek29** [comment]
Even just "test" fails \*shrug\*

**Comment by iwkse** [comment]
Yes, everything after @
I think the bug can also be reproduced with #

**Comment by stek29** [comment]
@iwkse Because server has special handling for hashtags, and for mentions
Also, iirc it should even show replies to `@test` user when you search for `@test`

And also, iirc, tdesktop strips most special symbols from search query, except `@#` and a couple of others, for reasons stated above.

**Comment by roman-voropaev** [comment]
Is it reproducible on last version? Seems to be working.

**Comment by iwkse** [comment]
Yes it's working in the new version. Perfect! Thanks
