### ISSUE TITLE
links with double undrescored word turns italic and broken

### ISSUE THREAD

**Issue by zuci42** [telegramdesktop/tdesktop#3851]
1. Post a http(s) link to any chat with a word: `__init__.py#L16`
2. Now we have subj: https://gh.oh/a/b/ _init_.py#L16

[screenshot for sure](http://i.imgur.com/Q0wVf3u.png)

### Expected behaviour
Links survive markdown
### Actual behaviour
Links broke

### Configuration
tg 1.1.19 @ xenial, amd64

**Comment by stek29** [comment]
Send <code>\` link \`</code> and not <code>link</code>
also see #2683.

**Comment by zuci42** [comment]
```
` link`
```
 is not clickable :(

**Comment by stek29** [comment]
Then `@bold [foobar](link)` maybe... I'm not sure *shrug*
#2683 should solve it.
