### ISSUE TITLE
Double characters automatically converts

### ISSUE THREAD

**Issue by ninazu** [telegramdesktop/tdesktop#3852]
### Steps to reproduce
1. Send `-- >>`

### Expected behaviour
Text are same as it is sent 

>  -- >>

### Actual behaviour
Replaced text
>  — »

### Configuration
**Linux Mint 18.2**
**Telegram Desktop v1.1.19**
**Used default theme**

**Comment by john-preston** [comment]
@ninazu This is done on purpose. I think I'll add a setting for that in some future versions.

**Comment by stek29** [comment]
#522
