### ISSUE TITLE
Automatically stop and resume music on incoming call

### ISSUE THREAD

**Issue by j2L4e** [telegramdesktop/tdesktop#3854]
It'd be nice to automatically stop music players on incoming Telegram calls.

I'm not sure how complicated this would be to implement cross-OS, but I assume that most environments have appropriate mechanisms available.

Here's how KDE Connect does it (uses KDE's media controls via dbus): https://github.com/KDE/kdeconnect-kde/blob/master/plugins/pausemusic/pausemusicplugin.cpp
On macOS it's safe to assume that everyone's using iTunes.

This would be an awesome feature as I tend to not notice incoming calls when music is playing.

**Comment by j2L4e** [comment]
For iTunes it should be as easy as running the appropriate AppleScript like this
`osascript -e 'tell application "iTunes" to pause'` (bash)

**Comment by tdemin** [comment]
> it's safe to assume that everyone's using iTunes

It's not. Spotify is popular too. 

On Linux, it has to be implemented by using the [MPRIS API](https://specifications.freedesktop.org/mpris-spec/latest/).

**Comment by stek29** [comment]
> On macOS it's safe to assume that everyone's using iTunes.

On macOS it's safe to assume that everyone's using iMessage and TDesktop for macOS isn't needed at all.
Honestly, wtf. Why would you assume that? It's just dumb, and makes no sense to me.
There are services like Spotify, Deezer, SoundCloud, GPlay Music. Many people are using browser. There are apps for social networks like VK which only play music. This is not a good idea. Not everyone who has a Mac likes Apple ecosystem. Not everyone just uses built-in apps even if they're bad.
 Apple is trying hard to force people to stick to iTunes -- by opening it on headphone button press, by making a breaking changes to media keys system, by starting iTunes on iDevice connection. Apple loves iTunes so much that you can't even ptrace it. Don't help them, please.

**Comment by stek29** [comment]
Miss clicked on close, sorry.

**Comment by j2L4e** [comment]
I didn't think it through, it doesn't make sense, I get it. And i mean it. 

Yet, from a maintainer of a repo of this reach, I'd expect a more professional reaction.

**Comment by stek29** [comment]
@j2L4e I'm won't call myself a maintainer. GitHub calls me "collaborator".
And sorry if I was rude, but your assumption offended me.
