### ISSUE TITLE
problem in Persian Language

### ISSUE THREAD

**Issue by PurTahan** [telegramdesktop/tdesktop#3855]
in Desktop version of telegram in windows , Persian words not shown correctly:
#### Words Not shown in correct style when using `ـ` char.
for example: `ســـلام` is true bot it shown ![capture](https://user-images.githubusercontent.com/4592452/29998068-cc407744-9036-11e7-9a8c-32bcce1a301d.PNG)

**Comment by stek29** [comment]
#1917

**Comment by PurTahan** [comment]
2 problems reported
the first one is bug.
what about the second one?

**Comment by stek29** [comment]
1) I did not understand second problem -- doesn't italic work?
2) Please, don't open 1 issue for multiple issues. 1 issue = 1 problem/1 suggestion.
