### ISSUE TITLE
Crash in sessions list

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#3856]
### Steps to reproduce
1.  Open "Active sessions" window
2.  Click on X button next to any session. It seems that nothing happens (there's a window "Do you want to terminate this session?"), but it's placed **below** the active window and you can't see it.
3.  Click that X again or try to close any other session. Still "nothing happens".
4. Click "close"

### Expected behaviour
"Do you want to terminate this session?" window should be above the current one, not below, so that you can't try to close 2 sessions at once.

### Actual behaviour
App crashes.

**Comment by john-preston** [comment]
@MasterGroosha Thanks for your report! This will be fixed in the next version, that I hope to deploy today (a lot of bugs in different boxes right now).

**Comment by MasterGroosha** [comment]
@john-preston Should I report a crash while trying to choose group sticker set? Or it's a known issue? 
When you search for a sticker set to make it "group stickers", app crashes.

**Comment by john-preston** [comment]
@MasterGroosha Yeah, I think I see that one too. Thanks, I see your uploaded crash report.
