### ISSUE TITLE
Snooze functionality

### ISSUE THREAD

**Issue by t-my** [telegramdesktop/tdesktop#386]
It would be helpful to snooze notifications certain groups/chats for certain period of time. In this time period you wouldn't receive any notifications from this particular chat. 

As now you have the only option to disable/enable the notifications which is not very convenient.

**Comment by auchri** [comment]
Write it to the telegram team on twitter: https://twitter.com/telegram , it's not client related

**Comment by t-my** [comment]
Okay thanks, closing.
