### ISSUE TITLE
[Linux] Two application icons

### ISSUE THREAD

**Issue by Winterwolf** [telegramdesktop/tdesktop#3863]
Same issue as here: #1127 in Ubuntu Gnome 16.04. Long time ago i used Xubuntu and also had this problem. I have 2 apps: from `~/.local/share/applications/telegramdesktop.desktop` and `/usr/share/applications/telegram.desktop`. If I remove one of them, it creates again after next update.

**Comment by auchri** [comment]
@Winterwolf How did you install Telegram Desktop?

**Comment by Winterwolf** [comment]
```
sudo apt-add-repository  ppa:atareao/telegram
sudo apt update
sudo apt install telegram
```

**Comment by auchri** [comment]
Try the binary from desktop.telegram.org please.

**Comment by Winterwolf** [comment]
@auchri Thanks, but I want ability to update from apt! :(

**Comment by auchri** [comment]
@Winterwolf Then you should contact the owner of the apt package

**Comment by Winterwolf** [comment]
@auchri Ok, I'll try. Thank you!
