### ISSUE TITLE
Random Mp3 playing like Android app

### ISSUE THREAD

**Issue by hectorlinarestascon** [telegramdesktop/tdesktop#3865]
### Steps to reproduce
1. Press play in one chat or group with some songs on it.
2. 
3. 

### Expected behaviour
Button in mp3 player to reproduce randomly mp3. Like repeat button.

### Actual behaviour
Only repeat button.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.1.23

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
#1045
