### ISSUE TITLE
Curly quotes interfere with parsing bold and italic markup

### ISSUE THREAD

**Issue by terrycloth** [telegramdesktop/tdesktop#3867]
### Problem behavior and steps to reproduce
Straight quotes will render the italic and bold markup as normal.

`"__italic__" "**bold**"` == "_italic_" "**bold**"

However, when touching single and double curly quotes, the markup is not rendered at all --- underscores and asterisks display unmodified.

`‘__italic__’ ‘**bold**’`
`“__italic__” “**bold**”`

### Expected behaviour

Markup for italic and bold text should render as such, regardless of surrounding punctuation (except in backtick \`code\` and URLs).

### Configuration
**Operating system:** Fedora 26 Workstation x86_64

**Version of Telegram Desktop:** 1.1.19

**Used theme**: my custom theme --- [cyberpunk.tdesktop-theme.zip](https://github.com/telegramdesktop/tdesktop/files/1283430/cyberpunk.tdesktop-theme.zip)

**Comment by Aokromes** [comment]
#2128 generic bug?

**Comment by sistematico** [comment]
Same issue here.

![image](https://user-images.githubusercontent.com/97509/31312527-cb1f557e-ab93-11e7-8ca8-dfc5739db79e.png)

Arch Linux with Telegram Desktop 1.1.23
      System Locale: LANG=pt_BR.UTF-8
       VC Keymap: br-abnt2
      X11 Layout: br
       X11 Model: abnt2

**Comment by sistematico** [comment]
Fixed with `ttf-liberation` package

**Comment by stek29** [comment]
@sistematico @Aokromes no, I think those issues are completely unrelated.

This issue is about regex used for `__` / `**` which works if wrapped in `' "` but not in `‘ ”`

@terrycloth am I correct?

**Comment by sistematico** [comment]
Ah! Ok, sorry...

**Comment by terrycloth** [comment]
@stek29 yes that sounds right.
(sorry for the late response)

**Comment by ForNeVeR** [comment]
The same with Russian quote marks, «these ones».

**Comment by terrycloth** [comment]
Cool, thanks @john-preston!
