### ISSUE TITLE
Bug: Sticker as a Document

### ISSUE THREAD

**Issue by artemtam** [telegramdesktop/tdesktop#387]
In Shared Media section number of shared documents contains number of sent stickers.

**Comment by auchri** [comment]
Fixed with 0.7.6

**Comment by JustANeter** [comment]
@auchri in 0.7.6 it isn't fixed.

**Comment by auchri** [comment]
@aseredenko @JustANeter it's fixed for me

**Comment by JustANeter** [comment]
@aseredenko @auchri Maybe it isn't bug - it's feauture?) In Telegram Web i see the same.

**Comment by auchri** [comment]
@artemtam @aseredenko I don't see my stickers in telegram web :smile: 
Strange things are happening :hushed:

**Comment by artemtam** [comment]
@auchri oh, i haven't any idea.. Magic :)

**Comment by Eibriel** [comment]
In the Telegram bot (+42777) the stickers count on Shared Media, but on other Normal contacts don't.
Maybe only counts while is not read by the other people?

**Comment by auchri** [comment]
@Eibriel yes, I can confirm that stickers are listed at the shared media until they are read by the receiver.

**Comment by telegramdesktop** [comment]
Stickers actually _are_ documents, they are a .webp images, sent as documents. So they are in the documents overview and in documents count. That's the way server-side works, nothing to do with the client app.
