### ISSUE TITLE
Telegram crashes on desktop (audio call)

### ISSUE THREAD

**Issue by ChristianChiarulli** [telegramdesktop/tdesktop#3870]
### Steps to reproduce
1. Open Telegram
2. Call another user

### Expected behaviour
Call goes through

### Actual behaviour
App crashes

### Configuration
Debian 9 Stretch
kernel 4.9.0-3

**Version of Telegram Desktop:**
idk (the newest)

**Used theme**:
night mode

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
We can't help you without logs.

**Comment by john-preston** [comment]
@ChristianChiarulli When you launch the app next time are you asked to send a crash report?

**Comment by Aokromes** [comment]
#3412 ?

**Comment by Aokromes** [comment]
^^
