### ISSUE TITLE
Request translation of Simplified Chinese (Chinese China) support.

### ISSUE THREAD

**Issue by kxxoling** [telegramdesktop/tdesktop#3872]
Cannot find Simplified Chinese (Chinese China) in supported language nor request language dropdown list: https://www.transifex.com/telegram/telegram-desktop/

**Comment by SJoshua** [comment]
check here: t.me/zh_CN

**Comment by kxxoling** [comment]
Interesting, but why not merge it into the official project?

**Comment by stek29** [comment]
@kxxoling \*shrug\*
Ask TG on Twitter or via in-app support.
