### ISSUE TITLE
Request: Rending Bold for Chinese and Japanese

### ISSUE THREAD

**Issue by SJoshua** [telegramdesktop/tdesktop#3874]
Bold text in Chinese and Japanese won't be rended both in Windows Telegram Messager and Android Telegram Messager. <del>It's okay in previous versions (before half year).</del> (I'm not sure.) 

Since italic is rended normally, I think bold can be so.

![photo_2017-09-10_12-31-11](https://user-images.githubusercontent.com/9545777/30246144-108ffe68-9624-11e7-81c9-f64c9b966569.jpg)

**Comment by stek29** [comment]
#1917 ?..
