### ISSUE TITLE
error on compile source

### ISSUE THREAD

**Issue by gilsefidi** [telegramdesktop/tdesktop#3875]
hi 
nmake -f ms\nt.mak have error

**Operating system:** Windows 10
**IDE:** Visual Studio 2017
**Version of Telegram Desktop:** Last Verison

<details><summary><b>Logs</b>:</summary>
ERROR LOGS : 
C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt\corecrt_memcpy_s.h(47): error C2065: 'errno': undeclare
d identifier
C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt\corecrt_memcpy_s.h(52): error C2065: 'errno': undeclare
d identifier
C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt\corecrt_memcpy_s.h(53): error C2065: 'errno': undeclare
d identifier
C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt\corecrt_memcpy_s.h(76): error C2065: 'errno': undeclare
d identifier
C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt\corecrt_memcpy_s.h(77): error C2065: 'errno': undeclare
d identifier
C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt\corecrt_memcpy_s.h(78): error C2065: 'errno': undeclare
d identifier
.\crypto\cryptlib.c(687): warning C4013: 'getenv' undefined; assuming extern returning int
.\crypto\cryptlib.c(687): warning C4047: '=': 'char *' differs in levels of indirection from 'int'
.\crypto\cryptlib.c(690): warning C4013: 'sscanf' undefined; assuming extern returning int
.\crypto\cryptlib.c(861): warning C4013: 'vfprintf' undefined; assuming extern returning int
.\crypto\cryptlib.c(926): warning C4013: '_vsnprintf' undefined; assuming extern returning int
.\crypto\cryptlib.c(985): warning C4013: '_exit' undefined; assuming extern returning int
NMAKE : fatal error U1077: '"D:\vs install Path\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\cl.EXE"' : return code '0x2'
Stop.
</details>

**Comment by stek29** [comment]
Do you have sdks installed?

**Comment by gilsefidi** [comment]
yes , every things in instructions was install correctly

**Comment by gilsefidi** [comment]
is there any other sdk for compile  ?

**Comment by gilsefidi** [comment]
Problem Solved By updateing Vistual Studio to Last Version
