### ISSUE TITLE
Close Instant View window by clicking Cmd+W

### ISSUE THREAD

**Issue by fedyk** [telegramdesktop/tdesktop#3879]
### Steps to reproduce
1. Open any Instant View link on MacOS.
2. Click `cmd` + `w` to close The Instant View window

### Expected behaviour
Should Close Instant View window

### Actual behaviour
Telegram window is closed, The Instant View Windows is still visible

### Configuration
**Operating system:**
macOS Sierra, v 10.12.6

**Version of Telegram Desktop:**
v3.2.1.104303

**Used theme**:
Not used theme

**Comment by stek29** [comment]
That's different app, report to https://t.me/macswift

Or get https://desktop.telegram.org
