### ISSUE TITLE
Support for giphy.com

### ISSUE THREAD

**Issue by JarnoNijboer** [telegramdesktop/tdesktop#388]
Now that we have support for viewing animated gif inside tdesktop, we need automatic playback for links to gifs on http://giphy.com

The current flow for sending a gif from giphy is:
* Find gif on giphy.com
* Save image to disk
* Send file to tdesktop

It would be nice to just paste links to gif images on giphy in tdesktop

**Comment by auchri** [comment]
#1012

**Comment by 2018happynewyear** [comment]
<a href="http://www.happynewyear2018wishes.com" >Happy New Year 2018 Wishes</a>
<a href="http://www.newyear2018.net/">New Year 2018 </a>
<a href="http://www.happynewyear2018wallpapers.net/" >Happy New Year 2018 Wallpapers</a>
<a href="http://www.newyear2018images.com"  >Happy New Year 2018 Images</a>
<a href="http://www.happynewyear2018photos.com/" >Happy New Year 2018 Photos</a>
<a href="http://happynewyearwallpapers2019.blogspot.com/2017/04/download-latest-hd-desktop-wallpapers-for-happy-new-year-2018.html"> Download latest HD Desktop Wallpapers for Happy new year 2018</a>
<a href="http://www.happynewyear0123456789.net/2017/04/happy-new-year-2018-best-new-year-whatsapp-facebook-messages-sms-to-send-happy-new-year-greetings.html">Best New Year WhatsApp & Facebook Messages</a>
<a href="http://www.happynewyear2018calendars.com/2017/04/indian-calendar-2018-for-indian-festival-and-india-holidays.html">Indian Calendar 2018</a>
<a href="http://www.happynewyear2018calendars.com/2017/04/download-2018-2019-2020-free-printable-calendars-templates-images-index-psd-files.html">Free Printable Calendar 2018</a>
<a href="http://happynewyear2019card.blogspot.com/2017/04/happy-new-year-2018-images-messages-wishes-cards-status-in-albanian.html">Happy New Year 2018 Messages Wishes in Albanian </a>
<a href="http://www.happynewyear0123456789.net/2017/03/happy-new-year-2019-vintage-images-graphics.html">Happy New Year 2019 Vintage Images</a>
<a href="http://www.happynewyear0123456789.net/2017/02/happy-new-year-whatsapp-and-facebook-2018-message-status-images.html">Happy new year whatsapp and facebook 2018 message </a>
<a href="http://www.newyear2020.net">Happy New Year 2020</a>
<a href="http://www.happynewyear2018status.org/" >Happy New Year 2018 status</a>
<a href="http://www.newyear2018wishes.net"  >New Year 2018 Wishes</a>
<a href="http://www.happynewyear2019.net/" >Happy New Year 2019</a>
<a href="http://www.happynewyear2018quotes.org">Happy New Year 2018 quotes</a>
<a href="http://www.happynewyear2018greetings.com/">Happy New Year 2018 Greetings</a>
<a href="http://www.happynewyear2019images.net/">Happy New Year 2019 Images</a>
<a href="http://www.happynewyear0123456789.net/">Happy New Year 2018 Wishes in Different Languages</a>
<a href="http://happynewyear2018wishes.com/" >Happy New Year 2018 Wishes</a>
<a href="http://www.newyear2018images.net/" >Happy New Year 2018 Images</a>
<a href="http://www.happynewyear2019images.org/">Happy New Year 2019 Images</a>
<a href="http://www.happynewyear2018calendars.com/2017/04/indian-calendar-2018-for-indian-festival-and-india-holidays.html">Indian Calendar 2018</a>
<a href="http://www.happynewyear0123456789.net/2017/03/happy-new-year-2019-vintage-images-graphics.html">Happy New Year 2019 Vintage Images</a>
