### ISSUE TITLE
Cinnamon crashes if Telegram uses native notifications

### ISSUE THREAD

**Issue by crlsgms** [telegramdesktop/tdesktop#3886]
### Steps to reproduce
1. Set up native notifications, on cinnamon
2. If marked up on a chat, even randomly
3. click on tray to open telegram

### Expected behaviour
Telegram should open / restore from tray normally, to the previous location. Notifications should pop using system notifications

### Actual behaviour
Telegram sometimes wont restore, have to be closed with right button / exit. Restoring the app, or receving a notification will crash cinnamon. Disabling this feature and using telegram notifications stops the behavior

### Configuration
**Operating system:**
4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3
Cinnamon 3.2.7

**Version of Telegram Desktop:**
1.1.23
**Used theme**:
Stock dark theme

<details><summary><b>Logs</b>:</summary>
I just noticed debugmode, ill collet some logs and post ASAP

**Comment by auchri** [comment]
I'll close this one until you bring up some logs.
You can also install any alpha version and post the crash tag here.

**Comment by Dreyk007** [comment]
I think this is related, but also with Telegram notifications: https://github.com/linuxmint/Cinnamon/issues/8034
