### ISSUE TITLE
Feature request: autodisable notifications 

### ISSUE THREAD

**Issue by Devocub** [telegramdesktop/tdesktop#3887]
Autodisable notifications and calls when certain app running. Like when Open Broadcaster Software (OBS) running then no notifications to not to worry you when you stream (to Twitch or You, for example). Like in Discord did, it calls "Streamer mode".

**Comment by MasterGroosha** [comment]
Don't forget that Discord was initially made as "Chat for gamers", so it has features gamers need the most.  
However, Telegram is a messenger for everyone, so your suggested feature may not be interesting for the most of users.

It may be a useful one, of course, but not for most people.

**Comment by Aokromes** [comment]
#2290
