### ISSUE TITLE
[Feature request] real time screen sharing

### ISSUE THREAD

**Issue by kirsan31** [telegramdesktop/tdesktop#3889]
Not screenshot, but real time (video) desktop sharing, like in skype.
It's last thing that force me, my friends and colleagues using skype or hangout for work :(
Is it possible?

- In individual calls.
- ~~In groups.~~

**Comment by auchri** [comment]
There's no api for that.

**Comment by kirsan31** [comment]
As we have Video Calls now, may be consider to reopen?
/cc @Aokromes

**Comment by RememberTheAir** [comment]
This is still an "API issue", it cannot be implemented by tdesktop without the backend supporting it too

**Comment by omkarnathsingh** [comment]
How API issue? Mac client has screen sharing feature already. In video calls, Source of video need to be changed to screen.

**Comment by kirsan31** [comment]
@omkarnathsingh 
![image](https://user-images.githubusercontent.com/17767561/99878815-1e5abe00-2c19-11eb-9d7c-42c69c608514.png)

**Comment by FoxTrot75** [comment]
Is there any news on feature?

**Comment by 23rd** [comment]
Should be implemented soon.

**Comment by kirsan31** [comment]
@23rd the screen sharing in voice chats of groups is something that I cannot imagine when was creating this topic :-( Can we have screen sharing in individual calls?
Reopen?

**Comment by kirsan31** [comment]
Implemented in 2.9. But really need [better quality](https://github.com/telegramdesktop/tdesktop/issues/16487).
