### ISSUE TITLE
Sure we want Stickers?

### ISSUE THREAD

**Issue by SpeedJack** [telegramdesktop/tdesktop#389]
Are we sure that the Telegram's community really wants these _suc**ng_ stickers?
I choosen Telegram as my primary IM software especially because it has not such things.
I think that there will be many others like me that think that features like these should not be present in a good messaging app.
In addition, if Telegram becomes similar to Facebook, LINE, etc. (and the no presence of useless and annoying things such as stickers was one of the primary differences with these chat systems) there will be no any reason to use Telegram instead of another app.

**Comment by Flash-back** [comment]
Well, I don't care actually. If I don't want I won't use them and if someone like I'm happy for him.

**Comment by SpeedJack** [comment]
And what about an option for disable the receiving of stickers?

**Comment by Aokromes** [comment]
I don't care about stickers, but i think a setting to allow disable them can be a nice idea.

**Comment by sergioad** [comment]
Yes, an option to togle the stickers could be nice but this feature for all the official Telegram clients

**Comment by Nhoya** [comment]
Yes, an option could be nice too!

**Comment by Uthanien** [comment]
I like the stickers. Btw, there not invasive in the app

**Comment by tral** [comment]
+1 for this option. And the sender obligatory should receive the notification like: "Contact disabled receiving this stupid stickers. Don't even try anymore"

**Comment by darkpolice** [comment]
+1 for the options for stickers. Anyways, they are great in my opinion.

**Comment by garex** [comment]
Personally I dont' like this feature :-1:. But... the world consists not from all of us, who dont' like it. So as T. is a messagin app and message consists not from information, but also from emotions, this feature is must have :+1:. With option of disabling of couse. Btw, what is stickers? :) Github has some images — why? :8ball:

**Comment by Alirezaaa** [comment]
Telegram always do things in different ways. Stickers in Telegram is a good feature for many people but someone like @SpeedJack doesn't want to use them anyway. As others said already, existing of an option for disabling sending and receiving stickers is a good feature.

**Comment by kallelix** [comment]
I agree. We need an option to disable or even scale down stickers.

**Comment by a-zazell** [comment]
Really stupid stickers! Please, kill this feature.

**Comment by Eibriel** [comment]
I tend to think in a visual way, in the same way voice messages help to express better to some people, stickers help to express myself. But I don't use the default stickers, I made my own.

![Amorzorzor saltando](http://amorzorzores.com/sticker/sticker_zzr_saltando.png)

**Comment by telegramdesktop** [comment]
I don't see the problem. Stickers are just a .webp images, sent as documents, just a specific way to display an image, that was received as a document, similar to the way photos are displayed. Standard stickers are not very easy to find and send, so I don't think you will receive much of those. Custom stickers are just a way to send an image. In this way I think .gif images should be more distracting, for example. Don't panic, no LINE-way of promoting the stickers feature is planned here :)

**Comment by aaomidi** [comment]
I really wish if we were able to disable stickers and just show the corresponding emojis instead :/ Something like what Skype does with emoticons

**Comment by boecko** [comment]
Please let people decide in their client, if they want to see these stickers or if the just want to see emojis ...

This (Stickers) is the **most annoying feature**, i've seen for a long time.
It just takes space.

**Comment by aaomidi** [comment]
+1

**Comment by Jefffrey** [comment]
Yes, please at the very least let me disable them. I happen to be in some groups where stickers are overused and it just makes it hard to browse through the messages.

**Comment by m7ia** [comment]
I really wish we had a user level preference for replacement of stickers with correspond emoji. The amount of space the stickers take up, especially in a group chat where several users are prone to using them, is quite ridiculous.

**Comment by sc0rp10** [comment]
+1 for "disabling" feature

**Comment by sirian** [comment]
really annoying. +1 for disable option
