### ISSUE TITLE
Arabic Text formatting

### ISSUE THREAD

**Issue by haroon-ali** [telegramdesktop/tdesktop#3891]
According to a post in #330 
Here's currently supported format:

    bold : **bold**
    italic : __italic__
    code : `code`
    pre : ```pre``` (supports multiline)

But actually none of this works with Arabic text except the italic. The text is displayed as normal text.
This is tested on Telegram desktop and telegram for Android, the official latest versions.

**Comment by stek29** [comment]
#1917
