### ISSUE TITLE
FR: Ability to group chats/contacts into "folders" in side panel

### ISSUE THREAD

**Issue by Blasterdick** [telegramdesktop/tdesktop#3892]
It would be great to have that feature in the mobile version as well. So it would be alike categories with default (auto-determining from the channel/group name) and custom names: 

- "Family"
- "Work"
- "Monitoring"
- "News"
- "Fun"
- "NSFW"
- etc.

Also, showing a number of unread messages for every category (if it minimized in "tree" view) would be nice.

**Comment by stek29** [comment]
#3805 or #1107
