### ISSUE TITLE
Use contact's chosen name instead of the phonebook name

### ISSUE THREAD

**Issue by ralesk** [telegramdesktop/tdesktop#3893]
### Steps to reproduce
1. Add contact with their phone number to your phonebook
2. Their name will be replaced by the phonebook name.

### Expected behaviour
There should be an option to see the name *they* set themselves. A lot of times people use their nicknames to set some sort of status information (eg. where they're travelling to) or to display just that: their nicknames.  Meanwhile phone contacts may have all sorts of names, I personally save people with their full legal names, and while I prefer that for *phone* contacts, I do not prefer that for *chat* contacts.

It appears to be possible to set a first and last name within Telegram, but it is not possible to set it to whatever the user has set.

Note, this is different from #2927 and #2263 

### Actual behaviour
The phonebook name shows, and it is impossible to make Telegram display the name the user chose.

### Configuration
**Operating system:** N/A (tdesktop on both Windows and Linux, and Android Telegram all do this)

**Version of Telegram Desktop:** 1.1.23 (doesn't matter, has been happening since the beginning of times)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/549 ?

**Comment by stek29** [comment]
@Aokromes I guess this one is about name chosen by another user, not by you

**Comment by ralesk** [comment]
Bump.

**Comment by sporifolous** [comment]
I would love to see the option to view a user's chosen name. I would have never given Telegram access to my contacts had I known it would permanently rename all of my contacts.

**Comment by TheSned** [comment]
I will add my vote for this feature. +1

**Comment by RememberTheAir** [comment]
@sporifolous  you can still reset all your contacts from the iOs/Android clients

**Comment by ralesk** [comment]
I still do not want to remove or rename my contact in my address book just to be able to see the name they set in Telegram or any other chat client.  It isn't hard, the client has this information, it's a matter of displaying it.

**Comment by saifulwebid** [comment]
I really support this request, as we use Telegram heavily in our office and use display name to show our status, too (to be easily seen by our colleagues in group chats).

**Comment by MrAlexEvers** [comment]
I also support this request, for the same reasons: my friends and I use our display name to give out extra and changeable info.

**Comment by sfuller** [comment]
Please fix this! Giving the user the option to choose which name is used would be amazing. Extra credit if this can be toggled per-user.

**Comment by NightMachinary** [comment]
At least show it on the profiles. That wouldn’t even need a new option.

**Comment by zLPrime** [comment]
This has a practical dimension as well. I have pretty old contacts in my phonebook. So, if somebody joins Telegram, I would like to make sure this is the person I know, not somebody random who got the number.

**Comment by Aokromes** [comment]
if it's api isuee it must be fixed server side.

**Comment by 1valdis** [comment]
Bump. There has to be a possibility to view what users set themselves as their name.

**Comment by yashpalgoyal1304** [comment]
I have faced the scenario given by @ArmeF97 [here](https://github.com/telegramdesktop/tdesktop/issues/4282#issuecomment-356085800) several times and soo soo wished there was some way to avoid the confusion. 

aside: https://github.com/telegramdesktop/tdesktop/issues/3503#issuecomment-503023020
kinda feeling bad that i became the subject of this meme this time: https://xkcd.com/1172/ 😅
