### ISSUE TITLE
Segmentation fault 1.1.23

### ISSUE THREAD

**Issue by cnuptak** [telegramdesktop/tdesktop#3894]
1. Segmentation fault on running
System: 4.9.16-gentoo x86
telegram 1.1.23

Program received signal SIGSEGV, Segmentation fault.
0x08dba00b in ?? ()
(gdb) bt full
#0  0x08dba00b in ?? ()
No symbol table info available.
#1  0x08db9948 in ?? ()
No symbol table info available.
#2  0x081879f2 in ?? ()
No symbol table info available.
#3  0x0818308f in ?? ()
No symbol table info available.
#4  0x081925d6 in ?? ()
No symbol table info available.
#5  0xb523e50b in __libc_start_main () from /lib/libc.so.6
No symbol table info available.
#6  0x0808114d in ?? ()
No symbol table info available.
(gdb) quit

**Comment by Aokromes** [comment]
useless crashlog, you need to compile (or download) on debug mode.
