### ISSUE TITLE
Client stops responding to mouse wheel scrolling

### ISSUE THREAD

**Issue by shentino** [telegramdesktop/tdesktop#3896]
### Steps to reproduce
1.  Start it
2.  Let it run for a good while
3.  Try to use the mouse wheel to scroll one of the two panes

### Expected behaviour
The pane (conversation and/or list  of chats) should scroll when you use the mouse wheel

### Actual behaviour
It scrolls at first, but later gets "stuck" and quits responding to the mouse wheel

### Configuration
Gentoo Linux, kernel version 4.13

**Version of Telegram Desktop:**
1.1.23

**Used theme**:
Whatever the default is, I haven't changed it

**Comment by chris13524** [comment]
Having a similar issue here. Scroll works fine in other applications. Closing and reopening the Telegram window doesn't help. The only thing that fixes it is restarting Telegram entirely.

**Comment by toshokan** [comment]
I'm seeing the same issue. Also on Gentoo GNU/Linux. It seems to happen after the system resumes from suspend.

**Comment by fotonmoton** [comment]
Same here. Possibly duplicate of #2734

**Comment by c0rp-aubakirov** [comment]
Same on arch, Telegram 1.3.14

**Comment by mikserc** [comment]
Same on Ubuntu 18.04.1

**Comment by hansbogert** [comment]
hate to add a confirm post, but this isn't getting any prio.
xubuntu with awesomeWM. Though I saw it under vanilla ubuntu 18.04 as well.

**Comment by gorghino** [comment]
I can confirm this bug on elementaryOS 5.0 (Ubuntu 18) and telegram 1.6.7
Kernel: Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3859 ?

**Comment by darksun27** [comment]
Same problem with Elementary OS running Ubuntu 18.04. Telegram Version: 1.2.17

**Comment by jlemonde** [comment]
Same bug for me on Ubuntu 19.04 and with Telegram 1.8.15

**Comment by carpajr** [comment]
The same issue is noted in Elementary OS running Ubuntu 18.04. Telegram Version: 2.0.1
The scrolling works for some time but stops.
