### ISSUE TITLE
SIGABRT during the voice call

### ISSUE THREAD

**Issue by misanthrop** [telegramdesktop/tdesktop#3898]
### Steps to reproduce
1. Start voice call.

Optional:

2. Run pavucontrol.
3. Change input level.

Not sure the bug is related to pulseaudio and pavucontrol. Possibly the crash is random.

### Expected behaviour
Voice call should continue.

### Actual behaviour
SIGABRT

### Configuration
**Operating system:** Arch Linux x86_64

**Version of Telegram Desktop:** [1.1.23](https://updates.tdesktop.com/tlinux/tsetup.1.1.23.tar.xz) (telegram-desktop-bin package from AUR)

**Used theme**: Night

Core dumps attached:
[core.2.zip](https://github.com/telegramdesktop/tdesktop/files/1308990/core.2.zip)
[core.1.zip](https://github.com/telegramdesktop/tdesktop/files/1308991/core.1.zip)

**Comment by auchri** [comment]
@misanthrop Try the binary from desktop.telegram.org please.

**Comment by misanthrop** [comment]
@auchri It is exactly the same binary, downloaded from https://updates.tdesktop.com/tlinux/tsetup.1.1.23.tar.xz

**Comment by misanthrop** [comment]
UPD: SIGABRT on voice call hang up 

```
#0  0x00007f4b821298a0 raise (libc.so.6)
#1  0x00007f4b8212ae88 abort (libc.so.6)
#2  0x00007f4b68f1d01b pa_queue_free (libpulsecommon-11.1.so)
#3  0x00007f4b68f1c657 pa_pstream_unref (libpulsecommon-11.1.so)
#4  0x00007f4b6916941c n/a (libpulse.so.0)
#5  0x00007f4b69169c38 n/a (libpulse.so.0)
#6  0x0000000001078f33 _ZN6tgvoip5audio15AudioInputPulseD2Ev (telegram-desktop)
#7  0x0000000001078f94 _ZN6tgvoip5audio15AudioInputPulseD0Ev (telegram-desktop)
#8  0x000000000105c266 _ZN6tgvoip14VoIPControllerD1Ev (telegram-desktop)
#9  0x000000000098c558 _ZN5Calls4Call17destroyControllerEv (telegram-desktop)
#10 0x00000000009b975f _ZN5Calls4Call8setStateENS0_5StateE (telegram-desktop)
#11 0x00000000009bfc1d _ZN5Calls4Call12handleUpdateERK8MTPBoxedI12MTPphoneCallE (telegram-desktop)
#12 0x0000000000000000 n/a (n/a)
```

I can upload core dump if necessary.

**Comment by Aokromes** [comment]
#3412 ?
