### ISSUE TITLE
(Bug) Audio Player - "File in use" even though its not playing

### ISSUE THREAD

**Issue by thexbasic** [telegramdesktop/tdesktop#3901]
### Steps to reproduce
1.  Upload a song/audio file to any chat
2.  Play the file via built-in player
3.  Stop playing (Close player with the little X in top right corner)

### Expected behaviour
As soon as the player is closed, the played resource should be free'd.

### Actual behaviour
The previously uploaded file can't be moved, renamed, deleted or overwritten ("in use").
You have to actually play a differrent song/audio first before it works again.
I guess this is not how it should work.

### Configuration
OS: Win10
TG: 1.1.10

**Comment by john-preston** [comment]
@thexbasic Yes, it should free the handle :( I'll try to look into this.

**Comment by MasterGroosha** [comment]
Duplicate #2583?
