### ISSUE TITLE
Different appearance of images pasted by clipboard - Desktop vs. Web

### ISSUE THREAD

**Issue by baerus** [telegramdesktop/tdesktop#3902]
### Steps to reproduce
1. Use web.telegram.org
2. When I "CTRL" + "V" a clipboarded image (taken with software "Greenshot", saves it images in .png, if important for you), then it appears on both sides like this:
![image](https://user-images.githubusercontent.com/3639065/30524557-888007d8-9bf6-11e7-94b6-3a52e75504a5.png)

3. use Telegram Desktop (v1.1.23, auto update on)
4. Repeating the same procedure, it then looks (on both sides) like this:
![image](https://user-images.githubusercontent.com/3639065/30524570-c93f1016-9bf6-11e7-9e87-2069e4626ab6.png)
(The first image was the previous pasted one)

### Expected behaviour
I expect same behaviour. Which is the first (web version) one. I want directly the image, and if I want I enlarge it with a click.

### Actual behaviour
It appears differently. I don't know why, and I don't know whether there is an option for me to change this. I like the web versions behaviour massively better.

### Configuration
**Operating system:**
Win 10

**Version of Telegram Desktop:**
v1.1.23

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
Enable "Compress image" checkbox.

![image](https://user-images.githubusercontent.com/11808223/30525786-0cec2578-9c16-11e7-9735-269e3cf96a5b.png)
