### ISSUE TITLE
New emoji autocompletion break Send on [Enter]

### ISSUE THREAD

**Issue by Alex131089** [telegramdesktop/tdesktop#3906]
### Steps to reproduce
1. Type a message which is ":p" or ending with ":p"
2. Hit Enter to send it

### Expected behaviour
Message is sent as typed

### Actual behaviour
Message is not sent, smiley/message is replaced by an unrelated emoji (:p => 🐷  for example)

Also, the behaviour is not consistent with Webogram / Telegram Web, which doesn't break the Enter to Send behaviour.

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** Latest stable pushed

**Used theme**: not relevant ?

**Comment by MobiusTesseract** [comment]
You can also disable "Replace emoji" in the settings.

**Comment by Alex131089** [comment]
@MobiusTesseract Oh, I didn't realized that, thanks (a lot) !
It completely disable the emoji autocompletion though.

**Comment by MobiusTesseract** [comment]
Yes, I know it's not an actual solution but a workaround, but you also disable it if you run an old version anyway, so this is much preferred from a security standpoint.

**Comment by Aerozolic** [comment]
Any update to this? It's pretty annoying that you have to type space after ":P" to autocomplete it to the actual emoji.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6516 better ticket.
