### ISSUE TITLE
[Bug] Smileys typed in chat don't get replaced with emojis on Linux

### ISSUE THREAD

**Issue by MobiusTesseract** [telegramdesktop/tdesktop#3907]
### Steps to reproduce
1. Type a smiley like :P or ;) (or :-P, doesn't matter)
2. Send the message or type a space afterwards and then send or even include them in a bigger message

### Expected behaviour
The smiley should be replaced with the respective emoji.

### Actual behaviour
Your smileys are sent in ASCII form, exactly as you typed them.

### Notes
"Replace emojis" is enabled in Settings
If I use the Unicode names with small letters like ```:stuck_out_tongue:``` or ```:wink:``` it works fine. The good ol' smileys are what fails.

### Configuration
**Operating system:** LinuxMint 18.2

**Version of Telegram Desktop:** 1.1.23

**Used theme**: Default (Night mode)

**Comment by cono** [comment]
There is no such smileys like :P or ;), look to the default list here:
https://github.com/telegramdesktop/tdesktop/issues/627#issuecomment-301737881

It was previously in setting but can't find atm. You can try: ":-)" and you will that it will work.
