### ISSUE TITLE
Please let users choose their own font style and font size

### ISSUE THREAD

**Issue by ynyounuo** [telegramdesktop/tdesktop#391]
I mean, some default fonts in languages other than English are just ugly and even unrecognizable.

**Comment by Alirezaaa** [comment]
You can change font size using interface scale option in settings; But choosing Our own font style can be a good feature.

**Comment by SafaAlfulaij** [comment]
#90
Looks like the developer won't listen to us, Unfortunately :(

**Comment by Revertron** [comment]
Author, just try to start Telegram without Cleartype on Windows - the fonts are VERY ugly!

**Comment by auchri** [comment]
duplicate #90
