### ISSUE TITLE
Can't open *.pptx directly from Telegram

### ISSUE THREAD

**Issue by evstpetr** [telegramdesktop/tdesktop#3912]
### Steps to reproduce
1. Ask somebody send u valid pptx document.
2. Try to open it from Telegram.
3. Try to open it directly from folder.

### Expected behaviour
Document opening corectly in both ways.

### Actual behaviour
Document opened from folder, 
but when try it from Telegram had error(error from Power Point)
"Sorry, PowerPoint can't read *Document Path*".

### Configuration
**Win7 x64:**

**Version of Telegram Desktop: v 1.1.23**

**Used theme**: Default

**Comment by MasterGroosha** [comment]
Which version of Power Point are you using? 
I have PowerPoint 2016 and it works fine for me (though I have Windows 10, not Windows 7, if it matters)

**Comment by evstpetr** [comment]
I using PP 2016 too, i guess problem with my OS.
