### ISSUE TITLE
Avoid auto-opening transferred scripts after download

### ISSUE THREAD

**Issue by AlexAltea** [telegramdesktop/tdesktop#3913]
Telegram Desktop automatically scripts sent by my contacts when I just want to download them. That behavior is counter-intuitive and might lead to users accidentally running malicious code in their machines. I would suggest blacklisting extensions like `.py`, `.sh`, `.cmd`, etc. such that they are downloaded but the user is shown a warning Yes/No dialog regarding whether to open the file.

### Steps to reproduce
1. Have a contact send you a script (`.py`, `.sh`, etc.).
2. Click anywhere on the button.

### Expected behaviour
The script file should download but **not** execute.

### Actual behaviour
The script file should downloads and gets executed.

### Configuration
**Operating system:** Windows 10 x64
**Version of Telegram Desktop:** 1.1.23
**Used theme**: Default

**Comment by auchri** [comment]
@AlexAltea https://github.com/telegramdesktop/tdesktop/issues/3198

**Comment by AlexAltea** [comment]
My apologies, I searched for existing issues, but chose the wrong keywords. I'll close this.
