### ISSUE TITLE
extremely low pitch sound when recording voice

### ISSUE THREAD

**Issue by reverser69** [telegramdesktop/tdesktop#3914]
hi
i record my voice with other app without any problem
voice sample recorded with latest telegram version is attached.
[audio_2017-09-23_11-24-39.zip](https://github.com/telegramdesktop/tdesktop/files/1326374/audio_2017-09-23_11-24-39.zip)

**Comment by auchri** [comment]
Use the template please.

**Comment by reverser69** [comment]
what template !?

**Comment by reverser69** [comment]
updated microphone driver
and ticked "disable microphone enchantments" in microphone effects tab
problem is fixed now.
i hope it helps someone

**Comment by auchri** [comment]
Template: https://github.com/telegramdesktop/tdesktop/blob/dev/.github/ISSUE_TEMPLATE.md
