### ISSUE TITLE
Incorrectly Linking Punycode Domains

### ISSUE THREAD

**Issue by Makeshift** [telegramdesktop/tdesktop#3917]
### Steps to reproduce
1. Have a punycode domain with an 'emoji' counterpart (eg. https://🐯⚪.ws/ )
2. Copy that into Telegram and send it
3. Telegram allows the full thing to highlight as if it's a link, but when clicking, it takes you to https://ws/ instead.

### Expected behaviour
Telegram should parse the whole domain and clicking it should open the domain in your browser.

### Actual behaviour
Telegram is opening only the tld of the link.

### Configuration
**Operating system:**
Win10 
**Version of Telegram Desktop:**
1.1.23
**Used theme**:
Default

**Comment by auchri** [comment]
Use the search please

**Comment by Makeshift** [comment]
Can you please link the duplicate? I'm unable to find it if it has been reported before. I'm obviously searching the wrong tags.

**Comment by Makeshift** [comment]
Found it, #2832.
