### ISSUE TITLE
Usernames or links are not clickable on people's bio

### ISSUE THREAD

**Issue by Lonami** [telegramdesktop/tdesktop#3923]
### Steps to reproduce
1. Open someone's bio that contains an username, or a link.
2. Try to click said username or link.

### Expected behaviour
Said username or link should actually link to such user or URL.

### Actual behaviour
But it doesn't.

### Configuration
**Operating system:** Arch Linux, Kernel: x86_64 Linux 4.12.13-1-ARCH.

**Version of Telegram Desktop:** 1.1.23.

**Used theme**: Siinde.

**Comment by stek29** [comment]
I think it's a feature.

**Comment by Lonami** [comment]
That's a pretty weird "feature" considering even the links on https://t.me are clickable.

**Comment by stek29** [comment]
I know :(
