### ISSUE TITLE
 "rotate button" during video playback

### ISSUE THREAD

**Issue by beppe9000** [telegramdesktop/tdesktop#3924]
I find frustrating when people sends me a video that plays sideways. Can we get a button like the red one in the edited screenshot below? When pressed the currently playing video should be rotated by 90 degrees.

![edited screenshot depicting the above mentioned button](https://i.imgur.com/KlILUyp.png)
--------------
_I tried to search open issues for "rotate video" and nothing came up so I am opening this one._

**Comment by Aokromes** [comment]
#1413 ?

**Comment by manuelsongokuh** [comment]
+1 vote!

**Comment by Aokromes** [comment]
coming soon on 1.9.10 https://github.com/telegramdesktop/tdesktop/commit/d29c3add799134b50718ba11c80f911503ef168d

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v1.9.10
