### ISSUE TITLE
Sharing an Image compresses the image automatically (Looks bad)

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#3925]
### Steps to reproduce
1. On the Desktop try to share an image (The testing case was PNG but could be JPG also)
2. The received should download the image and then compare the quality with the original
3. The received image looks really bad in quality when compared to the original

### Expected behaviour
There should be an option to disable or to set the amount of compression. For example, an option to not compress JPG or not compress PNG, or at least set the compression rate, or disable it completely. In this case, I need for PNG and JPG to be left alone, without compressing it. Because I use with my team telegram as a working tool (Basically occupies about 80% of our working environment).

### Actual behaviour
It compresses PNG or JPG, so when the receiver gets the image, it looks very low quality. We use the images for websites, so they need to respect quality.

### Configuration
**Operating system:**
Ubuntu 17.04 64Bit

**Version of Telegram Desktop:**
1.1.23
**Used theme**:
Default and Ubuntu Dark Theme (Typically Default)

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by CrafterSama** [comment]
Yeah this is all to happend to me, I also have Ubuntu.

**Comment by auchri** [comment]
![image](https://user-images.githubusercontent.com/5092164/30845880-a1621ab6-a295-11e7-83d0-376ed35d1af0.png)

🤦‍♂️

**Comment by luisalvarado** [comment]
That awkward moment when you feel like an idiot.
