### ISSUE TITLE
Messages are not marked as read when looking at images in overlay

### ISSUE THREAD

**Issue by redconnection** [telegramdesktop/tdesktop#3929]
### Steps to reproduce
1. Open chat with images
2. Start overlay with images
3. Scroll though images via arrow buttons
4. Close overlay

### Expected behaviour

The chat or channel should mark the images read 

### Actual behaviour

The panel still shows the messages as unread in chat

### Configuration
**Operating system:**
10.12.6 OSX

**Version of Telegram Desktop:**
3.4.106100

**Used theme**:

Dark mode

**Comment by stek29** [comment]
> Version of Telegram Desktop:
> 3.4.106100

Sorry, but this is not Telegram Desktop.
You're using native macOS app written in swift. You can report issues about it on https://t.me/macswift.

You can download TDesktop at https://desktop.telegram.org, or find it in Mac App Store (ples no)
