### ISSUE TITLE
Issue showing a photo

### ISSUE THREAD

**Issue by djhvscf** [telegramdesktop/tdesktop#393]
When I user send me a photo sometimes in the photo description says the name of other user. For example "Maria" send me a photo, I open it and in the photo description says "Victor" and I can see the Victor's profile and I don't know "Victor"

**Comment by djhvscf** [comment]
Here is the sender of the mesage
![sender](https://cloud.githubusercontent.com/assets/4496763/5748363/ef76da9c-9c04-11e4-8d23-1cea5204675b.PNG)

Here the message

![photo](https://cloud.githubusercontent.com/assets/4496763/5748370/02d50672-9c05-11e4-9a6f-2308193d1382.PNG)

And here I can access to the other contact, In this case I don't know him

![stranger](https://cloud.githubusercontent.com/assets/4496763/5748382/18450fa2-9c05-11e4-9e80-b81aba0f0f06.PNG)

**Comment by telegramdesktop** [comment]
Maybe Maria has forwarded photo, that Victor has sent her? Then it is so by-design (you can check on iOS / Android app for example). It is just not displayed that the photo/video/document was forwarded.

**Comment by djhvscf** [comment]
In my phone I see the correct name.. I see Maria as sender
