### ISSUE TITLE
Please support whatever font!

### ISSUE THREAD

**Issue by buckle2000** [telegramdesktop/tdesktop#3934]
The default font does not have bold/italic for Chinese. It is also very ugly.
![default](https://user-images.githubusercontent.com/10850402/30946896-240f0cea-a439-11e7-846b-f6dcc42a8be1.png)
So how can we choose an alternative font?

**Comment by stek29** [comment]
You can't choose font for now, but what you can do is use GitHub issues search.

**Comment by buckle2000** [comment]
Well, I do wish to reply to #90.

**Comment by stek29** [comment]
@buckle2000 do you have something meaningful to add?

**Comment by buckle2000** [comment]
Yes, I would like to recommend Noto Font from Google to be the default font family.

**Comment by buckle2000** [comment]
And...really: why do you locked that issue?

**Comment by auchri** [comment]
@buckle2000 Because of the many annoying +111!!!!!! plz fix this asap comments.

**Comment by buckle2000** [comment]
But you can just unsubscribe from that issue!

**Comment by stek29** [comment]
@buckle2000 Noto was already suggested, and it may fix issues with `~` and other problems like lenny face on macOS.
