### ISSUE TITLE
Feature Request: ability to group chats/conversations

### ISSUE THREAD

**Issue by PhantomYdn** [telegramdesktop/tdesktop#3935]
This is a feature request.
I have a lot of different contacts, bots, groups in telegram. Sometimes it's extremly complex to find required one even by using your incredable search capabilities. It will be cool if one of the following will be possible to do:
1) Ability to group conversations/contacts together to have, for example, group for work, personal and etc.
2) Or at least some tabs on top of the list like: "All", "Contacts", "Groups", "Bots". And by clicking on tab you will see all filtered accordingly.

**Comment by PhantomYdn** [comment]
Please provide the original issue. Didn't find it

**Comment by RememberTheAir** [comment]
#1107
