### ISSUE TITLE
[New Feature] Rotate photos option

### ISSUE THREAD

**Issue by Alirezaaa** [telegramdesktop/tdesktop#394]
Rotating photos while viewing them is a good option.

**Comment by auchri** [comment]
Or before sending them

**Comment by Alirezaaa** [comment]
Rotating photos before sending them make Telegram slow to send photos but rotating while viewing is good enough.

**Comment by telegramdesktop** [comment]
Never needed that in-app, so in my opinion it is not a good idea, very rare case.

**Comment by Alirezaaa** [comment]
@telegramdesktop I understand this is a very rare case; But imagine if it happened, it makes users save the picture, open the Telegram folder and then find the picture and view and rotate the picture with default image viewer. I think this path to rotate pictures is very disappointing.

**Comment by ntom** [comment]
Is it not possible to rotate a picture before you send it ? Really ? I'm on mobile can't see how to do it ...

**Comment by amiremami** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1413

This is in fact one of the most annoying things in telegram. I'm not sure why you say it's rare. Because I face it maybe 3 times a day in average. My neck is broken for this! :smile: 

For seeing the correct picture, I have to save it on my desktop and rotate it and then open it.

**Comment by alirezaaa** [comment]
@amiremami I found most of issues sent here are enough good to be get noticed but the owners always come and say something then they close the issue! but most of the time, you will see that suggestion implemented in future releases! This owners' behavior is so weird!

**Comment by auchri** [comment]
@alirezaaa It's because the dev follows an internal roadmap. It's not only the decision of the developer when and which features will be implemented.

**Comment by gorsash** [comment]
Even lazy-to-implement-features viber has this feature

**Comment by stek29** [comment]
See #1413
