### ISSUE TITLE
Window build for opus fails missing v140 build tools (doc issue)

### ISSUE THREAD

**Issue by sjames1958gm** [telegramdesktop/tdesktop#3943]
### Steps to reproduce
Building for windows per instructions

### Expected behaviour
Build should succeed

### Actual behaviour
opus release build fails

The instructions mention VS 2017, but the opus build needs the v140 build tools from VS 2015
These can be installed via the 2017 installer.

**Comment by stek29** [comment]
Can you make a PR please?

**Comment by sjames1958gm** [comment]
I attempted a PR - this is my first one

**Comment by john-preston** [comment]
Should be fine now, all libraries should be built with v141 or v141_xp.
