### ISSUE TITLE
the end button covered by warning message in Android app

### ISSUE THREAD

**Issue by Justsoos** [telegramdesktop/tdesktop#3946]
First of all, it is hard to find a way to report bugs to Telegram team..... too... https://github.com/telegramdesktop/tdesktop/issues/1190

It is a bug of Telegram Android app,  as the screen shot below, if you were restricted by admins of group, and same time you unfortunately got a unsent draft (which also can be resulted by bots), the prompt of warning message should cover up the END button TIGHTLY.

How to reach the button? or how to delete the draft? it is a bug.
![photo_2017-09-30_11-28-39](https://user-images.githubusercontent.com/3480043/31042199-06d04d40-a5d5-11e7-9250-1ba8579fb3b0.jpg)

**Comment by auchri** [comment]
Not related to Telegram Desktop.

**Comment by Justsoos** [comment]
@auchri  could you pls show where for it?

**Comment by stek29** [comment]
Use "Ask a question" button in settings
