### ISSUE TITLE
Up arrow key doesn't show last message for editing in Desktop app

### ISSUE THREAD

**Issue by saeed3s** [telegramdesktop/tdesktop#3948]
### Steps to reproduce
1. send some messages from desktop and then some messages from mobile
2. now come back to desktop and use Up arrow key for editing the last message

### Expected behavior
Tell us what should happen
have to see the last message sent from any devices(in this case from an android device)
### Actual behavior
Tell us what happens instead
I see the last message sent from desktop app for editing
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.1.23
**Used theme**:
default 
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
@saeed3s Use search please
