### ISSUE TITLE
 Improved language switcher and language pack downloader

### ISSUE THREAD

**Issue by afarsi** [telegramdesktop/tdesktop#3949]
Hi there.
You can simply improve telegram's language switcher and make it to download list of all of languages and then if for example, one person wanted to have Persian language, he can download it by a button in front of it. When he touch download button, app should start to download and install related language pack from a repository. With this system, you don't want to inculde all of languages in telegram installation package and make size of app larger.
All of soft keyboards in mobile phones, are using this technique for support all of languages.
This technique is more easier and user friendly than a thing like langbot.
Thanks.

**Comment by Aokromes** [comment]
#3378
