### ISSUE TITLE
Make different notification between when a proson mentoin you and when a person answer to you

### ISSUE THREAD

**Issue by afarsi** [telegramdesktop/tdesktop#3950]
Hi there.
Recently, you added a feature that if a person response to you or mentoin you in group, you will recive a differnet notif with a green @ sign. But you can make it diffrent for example, if a person mentoined you, show @ sign and if a person answered to your message, you will see another sign. Another idea can be make diffrenece between color of @ sign. For example, green and blue or red.
Thanks.

**Comment by stek29** [comment]
Use "Ask a question" button in settings or tweet to Telegram.
