### ISSUE TITLE
Keep certain group unread messages from adding to the total unread count.

### ISSUE THREAD

**Issue by jandr** [telegramdesktop/tdesktop#3953]
Hi, 

I would like to suggest the ability to mark certain groups/chats so its unread messages are not added to the total uf "unread" messages.  If I am in a supergroup, and might have 2000 unread messages overnight, I would prefer to have the "total count" shown in the taskbar not count these, so I can see if I have another unread messages with more priority (e.g. personal chats, or other groups). 

I think the mobile app (Android and iOS) would benefit from such option as well.

**Comment by stek29** [comment]
Please uncheck "include muted chats in unread count" in settings
