### ISSUE TITLE
[Feature request] Down arrow + Enter after search should open chat

### ISSUE THREAD

**Issue by steffanhalv** [telegramdesktop/tdesktop#3955]
### Steps to reproduce
1. Search for chats in the desktop app
2. Press Down arrow on keyboard

### Expected behaviour
Down + Up arrow should browse through the different chats and Enter should open it

### Actual behaviour
Nothing

### Configuration
**Operating system:**
Mac and Windows

**Version of Telegram Desktop:**
2.99.1.96967 Stable

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
Alt+Down/Up?

**Comment by stek29** [comment]
Oh, you're using swift app.

**Comment by steffanhalv** [comment]
Ah, thx. Alt + Down/Up Works. Great!
