### ISSUE TITLE
Cant copy Telegram version in about

### ISSUE THREAD

**Issue by steffanhalv** [telegramdesktop/tdesktop#3956]
### Steps to reproduce
1. Click Telegram -> about
2. Try to select and copy version number

### Expected behaviour
Text should be selectable and able to copy so I can easier paste it to github issues

### Actual behaviour
Its not selectable

### Configuration
**Operating system:**
MacOs

**Version of Telegram Desktop:**

Here comes the problem... I have to type: 2.99.1.96967

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
> 2.99.1.96967

This is not Telegram Desktop.
You can download Telegram Desktop at https://desktop.telegram.org.

Also, you can report issues in app you're using at https://t.me/macswift.

**Comment by auchri** [comment]
Do you find the version `2.99.1.96967` at the releases page?

https://github.com/telegramdesktop/tdesktop/releases

**Comment by steffanhalv** [comment]
It still persist after update ->

**Comment by auchri** [comment]
No it's not. Or do you find your version at the releases page? 

https://github.com/telegramdesktop/tdesktop/releases

**Comment by stek29** [comment]
> And yes, it is Telegram Desktop

No, it is not Telegram Desktop.
It's native macOS app written in swift. 

Telegram Desktop: https://desktop.telegram.org
App you're using now: https://macos.telegram.org

**Comment by steffanhalv** [comment]
Sorry, my fault. This was very confusing a bit annoying, that apple has its own telegram app when you have a better one right here :/

**Comment by stek29** [comment]
Lol it's not Apple's own Telegram app.
Telegram has two different official apps for macOS, and they're both good in their own aspects.
