### ISSUE TITLE
Chats List View - Sorting Options

### ISSUE THREAD

**Issue by romshark** [telegramdesktop/tdesktop#3957]
### Expected behaviour
It would be very useful to have multiple sorting options in the chats list view. There should be at least two options:
- sort by "last updated"
- sort by "last written to"

The second proposed option "last written to" means that chats I wrote to recently should have higher interest priority.

### Actual behaviour
Currently there ain't any sorting options in the chats list and the chats are automatically sorted by the "last updated" criteria.

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.1.23
**Used theme**: _not relevant_

**Comment by MasterGroosha** [comment]
I guess this will lead to inconsistency across multiple devices.

**Comment by romshark** [comment]
I personally have joined lots of groups in Telegram (45 groups currently), each around 500 total members and around 5-10 concurrently active users on average, they update pretty damn frequently (sometimes in an interval of a couple of seconds) randomly jumping up and down in the list view.

In some periods of time I am writing to particular kinds of groups more frequently than others, meaning I'm temporarily prioritizing them over others. I've noticed I'm spending way too much time (often up to 5 seconds and even more) on searching for the particular groups, which is totally annoying. The chat list sorting feature would save me a lot of time and nerves cause then I'll find the groups I'm really interested in almost instantaneously.

I understand that to keep the sorting consistent across multiple devices you'd need to store this information (last wrote to) on the server, so.. why not make this a feature request to Telegram in general?

**P.S.**
Consistency is important indeed, though it's only one part of UX in general.

**Comment by RememberTheAir** [comment]
> I understand that to keep the sorting consistent across multiple devices you'd need to store this information (last wrote to) on the server, so.. why not make this a feature request to Telegram in general?

Problem is, this place is just for TDesktop-related issues. You can suggest platform-wise improvemets to the in-app support or [on Twitter](https://twitter.com/telegram)
