### ISSUE TITLE
Emoji list disappears when scrolling

### ISSUE THREAD

**Issue by jpjacobs** [telegramdesktop/tdesktop#396]
The emoji list in the desktop version of telegram has the pretty annoying habit of disappearing just after scrolling stops.
Steps to reproduce:
Move pointer over the emoji list; it opens automatically (which I don't like either) then the scrolling on my trackpad works, and the moment it stops, the list is closed.

On the same laptop (which happens to have a touch screen as well) it works well scrolling via dragging on the touchscreen...

For all clarity:
OS: Windows 8.1 pro, 64 bit version
Device: Dell Inspiron15z

**Comment by telegramdesktop** [comment]
Which device and OS?

**Comment by jpjacobs** [comment]
My OS and device are:

OS: Windows 8.1 pro, 64 bit version
Device: Dell Inspiron15z

PS: I updated my initial report accordingly.

**Comment by alirezamirian** [comment]
+1
