### ISSUE TITLE
[Upstream] New Unicode Emojis support

### ISSUE THREAD

**Issue by omkarnathsingh** [telegramdesktop/tdesktop#3966]
### Steps to reproduce
1. Send new unicode emojis from Android and iOS devices. (🤩)
2. Open that chat in Tdesktop

### Expected behaviour
It should display those new emojis.

### Actual behaviour
It displays a small box.

### Configuration
**Operating system:** Ubuntu 17.10 Non LTS

**Version of Telegram Desktop:** 1.2.11 Alpha

**Comment by Mistero5050** [comment]
We need first Apple's new emoji font. Someone should have it

**Comment by stek29** [comment]
@Mistero5050 if Android app supports them, it means that Telegram already has it.

**Comment by Mistero5050** [comment]
Does Android Telegram support Unicode 10 emojis?

**Comment by omkarnathsingh** [comment]
@Mistero5050 Android Telegram doesn't support them natively. But as I have Android Oreo, I see the Android's version of same emoji.

**Comment by Mistero5050** [comment]
@omkarnathsingh 
That's obvious, but it requires the last operating system or the user to hack their phone (because Oreo it's not supported by my phone, for example).
We are discussing about having it inside telegram, regardless the operating system's version.

I have Apple Unicode 10's emoji, on my Android 7.1.2, but that's not what we are discussing about

**Comment by omkarnathsingh** [comment]
But as Tdesktop is not from Android or iOS based, it needs to add Latest Unicode emojis on its own so that we dont see boxes.
On Android or iOS, it displays the emojis from its native store.

 (Your example that it doesn't support your mobile is weird and baseless. Noone on earth is bothered of that, that your personal and monetary problem.)

Emoji in Unicode 9

    🤣 Rolling on the Floor Laughing
    🤤 Drooling Face
    🤢 Nauseated Face
    🤧 Sneezing Face
    🤠 Cowboy Hat Face
    🤡 Clown Face
    🤥 Lying Face
    🤴 Prince
    🤵 Man in Tuxedo
    🤰 Pregnant Woman
    🤶 Mrs. Claus
    🤦 Person Facepalming
    🤷 Person Shrugging
    🕺 Man Dancing
    🤺 Person Fencing
    🤸 Person Cartwheeling
    🤼 People Wrestling
    🤽 Person Playing Water Polo
    🤾 Person Playing Handball
    🤹 Person Juggling
    🤳 Selfie
    🤞 Crossed Fingers
    🤙 Call Me Hand
    🤛 Left-Facing Fist
    🤜 Right-Facing Fist
    🤚 Raised Back of Hand
    🤝 Handshake
    🖤 Black Heart
    🦍 Gorilla
    🦊 Fox Face
    🦌 Deer
    🦏 Rhinoceros
    🦇 Bat
    🦅 Eagle
    🦆 Duck
    🦉 Owl
    🦎 Lizard
    🦈 Shark
    🦐 Shrimp
    🦑 Squid
    🦋 Butterfly
    🥀 Wilted Flower
    🥝 Kiwi Fruit
    🥑 Avocado
    🥔 Potato
    🥕 Carrot
    🥒 Cucumber
    🥜 Peanuts
    🥐 Croissant
    🥖 Baguette Bread
    🥞 Pancakes
    🥓 Bacon
    🥙 Stuffed Flatbread
    🥚 Egg
    🥘 Shallow Pan of Food
    🥗 Green Salad
    🥛 Glass of Milk
    🥂 Clinking Glasses
    🥃 Tumbler Glass
    🥄 Spoon
    🛴 Kick Scooter
    🛵 Motor Scooter
    🛑 Stop Sign
    🛶 Canoe
    🥇 1st Place Medal
    🥈 2nd Place Medal
    🥉 3rd Place Medal
    🥊 Boxing Glove
    🥋 Martial Arts Uniform
    🥅 Goal Net
    🥁 Drum
    🛒 Shopping Cart


Emoji in Unicode 10

    🤩 Star-Struck
    🤨 Face With Raised Eyebrow
    🤯 Exploding Head
    🤪 Crazy Face
    🤬 Face With Symbols Over Mouth
    🤮 Face Vomiting
    🤫 Shushing Face
    🤭 Face With Hand Over Mouth
    🧐 Face With Monocle
    🧒 Child
    🧑 Adult
    🧓 Older Adult
    🧕 Woman With Headscarf
    🧔 Bearded Person
    🤱 Breast-Feeding
    🧙 Mage
    🧚 Fairy
    🧛 Vampire
    🧜 Merperson
    🧝 Elf
    🧞 Genie
    🧟 Zombie
    🧖 Person in Steamy Room
    🧗 Person Climbing
    🧘 Person in Lotus Position
    🤟 Love-You Gesture
    🤲 Palms Up Together
    🧠 Brain
    🧡 Orange Heart
    🧣 Scarf
    🧤 Gloves
    🧥 Coat
    🧦 Socks
    🧢 Billed Cap
    🦓 Zebra
    🦒 Giraffe
    🦔 Hedgehog
    🦕 Sauropod
    🦖 T-Rex
    🦗 Cricket
    🥥 Coconut
    🥦 Broccoli
    🥨 Pretzel
    🥩 Cut of Meat
    🥪 Sandwich
    🥣 Bowl With Spoon
    🥫 Canned Food
    🥟 Dumpling
    🥠 Fortune Cookie
    🥡 Takeout Box
    🥧 Pie
    🥤 Cup With Straw
    🥢 Chopsticks
    🛸 Flying Saucer
    🛷 Sled
    🥌 Curling Stone

**Comment by Mistero5050** [comment]
> But as Tdesktop is not from Android or iOS based, it needs to add Latest Unicode emojis on its own so that we dont see boxes.
> On Android or iOS, it displays the emojis from its native store.
I know that, that's why I said that we first need Apple's emoji font, in order to put it into TDesktop

> (Your example that it doesn't support your mobile is weird and baseless. Noone on earth is bothered of that, that your personal and monetary problem.)
I said that because you say that with Oreo you can see them. We know, but we are discussing TDesktop, it was you who bragged Oreo in this topic. It's not a monetary problem, mine, of course. I was just saying (because you brought the argument) that in Android emojis are supported system-wide IF you have the latest version, but most users don't have them because their phone makers doesn't upgrade, in order to force you to buy the next phone. But that's off topic so let's end it here.

I was just sayng, from start, that we need the Apple Emoji Font and then it should be easy to do your request

**Comment by omkarnathsingh** [comment]
If I get you Apple font, will it be possible then? I already have it.

**Comment by Mistero5050** [comment]
It's how it should be done because TDesktop is using Apple's emoji, but you can't dedice it for yourself, I guess Telegram has the license, so we have to wait for legal things. You can fork and do that with your font, maybe a PR, but I think we just have to wait

**Comment by auchri** [comment]
@omkarnathsingh I don't think that the new emoji will be added before they are added to the Android and iOs app.

**Comment by stek29** [comment]
@auchri they are already in iOS app :)

**Comment by Mistero5050** [comment]
I think telegram will sleep until WhatsApp implements them. Whats a shame 😥

**Comment by omkarnathsingh** [comment]
WhatsApp has already given that emoji update. Telegram can wake up now! :P

**Comment by auchri** [comment]
@stek29 But not in the Android app 🤔

**Comment by Mistero5050** [comment]
@auchri  yes, but google is late to process the update, but you can already find the whatsapp apk online with the new unicode version

**Comment by auchri** [comment]
@Mistero5050 I'm not talking about WhatsApp 😆

**Comment by Mistero5050** [comment]
Ok sorry :+1: @auchri

**Comment by NonnEmilia** [comment]
Telegram 4.5 update for Android brings the unicode 10 emoji.

Is it now possible to include them in TDesktop?

**Comment by ArmeF97** [comment]
No one has replied :(

**Comment by omkarnathsingh** [comment]
This is be added soon I guess.

**Comment by ArmeF97** [comment]
Let's all hope. Whatsapp, iOS, Facebook, Twitter, ecc... 
All of them already has Unicode 10 emoji support

**Comment by auchri** [comment]
Please only add a comment if you have something meaningful to say. Otherwise I'll lock the issue.

**Comment by omkarnathsingh** [comment]
Unicode 11 emojis have also arrived. Source: https://emojipedia.org/unicode-11.0/

**Comment by omkarnathsingh** [comment]
Ubuntu 18.04 have inbuilt colour emojis. Can it be used directly in Tdesktop?

**Comment by stek29** [comment]
@omkarnathsingh So does macOS and Windows 10 -- but Telegram as platform insists (afaik) on using Apple Emoji everywhere.

**Comment by ArmeF97** [comment]
@stek29 , we can use Apple's emoji, and let the OS display its set if the character isn't mapped yet in the Apple font telegram desktop has.

Just like in the android version, if Telegram for android does not have the emoji mapped, it will display the system font one.

**Comment by Aokromes** [comment]
for me unicode 10 icons works on windows 10 RS5, but they are B&W.

**Comment by Sasorien** [comment]
They are still not supported in the Tdesktop version for Windows 10!
WhatsApp-Web supports them now for months, but in Tdesktop i cant choose them in the "Emoji-Picker". Like @Aokromes already mentioned.

Why? :(

**Comment by Aokromes** [comment]
Implemented on 1.4.4

**Comment by PoliNetwork** [comment]
Re open this, this emoji is not displayed correctly in telegram desktop 🤷 so the full unicode 11 version is not yet completed.

**Comment by kovachwt** [comment]
Hi @omkarnathsingh 
Can you please respond why this was closed without adding the rest of the Unicode 9/10 emojis? Or direct us to a new issue tracking this?
Aokromes provided a list of U9/10 emojis that are still not implemented in the latest beta version of Telegram Desktop.

**Comment by ArmeF97** [comment]
@kovachwt I've open a new issue here
https://github.com/telegramdesktop/tdesktop/issues/5388
