### ISSUE TITLE
[Feature Request] Lock recording button as in Android APP

### ISSUE THREAD

**Issue by Daniel-M** [telegramdesktop/tdesktop#3967]
### Steps to reproduce
None

### Expected behaviour
To be able to lock the recording stream as in the android app when recording voice messages,

### Actual behaviour
During all the voice message recording you have to keep the client's recording button pressed

### Configuration
**Operating system:**
Linux 4.12.0-2-amd64 #1 SMP Debian 4.12.13-1 (2017-09-19) x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.1.23 Alpha

**Used theme**:
Light

**Comment by stek29** [comment]
Part of #1060
