### ISSUE TITLE
Very small tray icon on Ubuntu 17.10

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#3968]
Dear all, 

Version 1.1.23 suddenly shows a very small and hard to read tray icon on Ubuntu 17.10. 

Did something change in Telegram Desktop or is this due to a change in Ubuntu 17.10?

Can anyone reproduce the problem?

Thank you!

![image](https://user-images.githubusercontent.com/170947/31327830-eeccf17c-acd1-11e7-9f1d-054c5bfe466c.png)

**Comment by marcogiannini** [comment]
same problem with fresh installation

**Comment by diazbastian** [comment]
@orschiro As I mentioned in #3995 gnome no longer displays the status icons by default and therefore it depends on the extensions how they look. What extension are you using?

For example [TopIcon Plus](https://extensions.gnome.org/extension/1031/topicons/) is fully configurable, so you can enlarge the status icon in your particular case.

![topiconsplus-config](https://user-images.githubusercontent.com/5126124/31690493-41b97d18-b369-11e7-97d8-85b2b5235de9.png)

**Comment by orschiro** [comment]
@diazbastian got you! Thanks. 

Hence the issue needs to be addressed over at Ubuntu App Indicator and not here: 

![image](https://user-images.githubusercontent.com/170947/31691433-651ecf24-b396-11e7-8a27-5b96d96a2024.png)

**Comment by orschiro** [comment]
Related: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/68

**Comment by jhasse** [comment]
I think this should also be fixed by #3930 (which isn't included in 1.1.23 AFAIK).

**Comment by auchri** [comment]
@jhasse No, your changes are not included in the latest stable.
