### ISSUE TITLE
"Connecting to proxy" notification interrupt IME input.

### ISSUE THREAD

**Issue by lordfriend** [telegramdesktop/tdesktop#3969]
### Steps to reproduce
1. Setting proxy to a HTTP or socks5 proxy and make that proxy with a unstable latency.
2. Use Any IME on Windows/Ubuntu to input in the message box at the same time telegram show a tip at the bottom left corner says: `Connecting to proxy ....`
3. You will find your IME is interrupted and the alphabet letter directly input in the message box instead of the word you wish by IME. depends on the IME you may also totally lose all your input when interrputed.

### Expected behaviour
Tell us what should happen

The tips: `Connecting to proxy... ` should not interrupt the input.

### Actual behaviour
Tell us what happens instead

The tips: `Connecting to proxy... ` should interrupt the input may be caused by lost focus in the message box. You input with IME lost.

### Configuration
**Operating system:**
- Windows 8.1 pro
- Ubuntu 16.04LTS

**Version of Telegram Desktop:**

1.1.23

**Used theme**:

Any theme, even with default theme

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
https://github.com/telegramdesktop/tdesktop/pull/3868
