### ISSUE TITLE
Change default background image. It's just bad

### ISSUE THREAD

**Issue by alivekenny** [telegramdesktop/tdesktop#3972]
### Steps to reproduce
1. Install Telegram Desktop
2. Open any chat.

### Expected behaviour
Background image is modern but smooth and calm (or there is no background at all which is fine too)

### Actual behaviour
Background image is gaudy, tasteless and smells like Windows XP wallpaper.

### Note
Previous background image was okay and before previous was nice too (like iOS's default patten). But today's image is just garbage. This is not what I expect from my favourite and the only message app. You, guys, form taste of hundreds of thousands of people around the world, and that's what you give them?
Don't think that it's not a problem, because people can change this image. There is a really small amount of users who do that, everyone else just deal with that and live with this horrable flowres. 
Please change it. I begging you.

**Version of Telegram Desktop:** 1.1.23

**Used theme**: Default

**Comment by stek29** [comment]
Just change it if you don't like it.

**Comment by alivekenny** [comment]
Sure I can change it and did it immediately. But most people I know just make wince face moment they open TD, remove it and keep using macOS app instead which is clean and looks modern.

**Comment by stek29** [comment]
so what? :)

**Comment by ArtyomKaltovich** [comment]
>Just change it if you don't like it.

I am sorry, but where is the setting for it?)

**Comment by RememberTheAir** [comment]
Honestly I would like to jump on the train and say the default flowers background sucks hard and it's a background you wouldn't expect to find as the default in a messaging app. Doesn't fit the UI at all imo. Doesn't fit _any_ ui. It's just bad :(

Can't tdesktop use a pattern similar to the default background of mobile apps?

**Comment by yashpalgoyal1304** [comment]
can u please attach the bg image so i can pick a side? 😅

**Comment by alivekenny** [comment]
> can u please attach the bg image so i can pick a side? 😅

I believe that apps should respect OS behaviour and very few of desktop apps have a picture on the background by default. So I think that it would be better to have just a clean white background.

![image](https://user-images.githubusercontent.com/21039303/88787091-c3eeab00-d1ac-11ea-9b6a-c4656121a51e.png)

**Comment by yashpalgoyal1304** [comment]
> just a clean white background

i would not like that particular pick as default. some other washed out/less saturated colors will suite better in my eyes.

but if u want that as a general option, there are already issues filed for that :)
