### ISSUE TITLE
UI resize and emoji panel.

### ISSUE THREAD

**Issue by TristisOris** [telegramdesktop/tdesktop#3973]
### Steps to reproduce
1. open sidebar with emoji.
2. close it.

### Expected behaviour
it must to restore old window width

### Actual behaviour
UI don't resized back.

![1](https://user-images.githubusercontent.com/1270117/31426250-352ea63e-ae6b-11e7-9eb1-fcb932ae7439.PNG)
![2](https://user-images.githubusercontent.com/1270117/31426251-3549d152-ae6b-11e7-8371-7fd94a1588d1.PNG)
![3](https://user-images.githubusercontent.com/1270117/31426252-3567d990-ae6b-11e7-80b6-f12128d55ae3.PNG)

### Configuration
**Operating system:**
win10

**Version of Telegram Desktop:**
1.1.23

**Comment by john-preston** [comment]
@TristisOris Thanks, it will in some of the next versions.

**Comment by Aokromes** [comment]
#713

**Comment by Aokromes** [comment]
I think this is fixed already.
