### ISSUE TITLE
Text width gets reduced when commenting on a narrow image

### ISSUE THREAD

**Issue by JobEngel** [telegramdesktop/tdesktop#3975]
### Steps to reproduce
1. Upload a narrow image (~2x more height than width)
2. Add some caption (long enought that it causes linebreaks)

### Expected behaviour
I'd expect the text not to conform necessarily to the width of the image. Instead it should exceed the width of the image to make it more readable.

### Actual behaviour
The text conforms to the image exactly thereby making the message hard to read.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.1.23

**Used theme**:
Default

**Example Image**:

![image](https://user-images.githubusercontent.com/5955911/31444023-42f1a840-ae9b-11e7-8e7e-3dc8664275df.png)

**Comment by auchri** [comment]
@JobEngel duplicate, but I don't find the original issue

**Comment by auchri** [comment]
Duplicate, but I don't find the original issue 🤷‍♂️
