### ISSUE TITLE
Chinese input is interrupted during spelling when a "Connecting..." message appears at bottom-left corner

### ISSUE THREAD

**Issue by cades** [telegramdesktop/tdesktop#3976]
### Steps to reproduce
1. open Telegram desktop app for Windows
2. enter message page (select anybody)
3. start typing with Chinese input method, spelling words, until a "Connecting..." message appears at bottom-left corner of Telegram app window.
4. input spelling is interruped

### Expected behaviour
I can input Chinese words without problem

### Actual behaviour
input is interrupted during spelling when the "Connecting..." message appears at bottom-left corner, every single time. Here is a [demo video](https://www.dropbox.com/s/03imynitmz8bo3c/reproduce-telegram-bug.mp4?dl=0).

### Configuration
**Operating system:**
Windows 10 Enterprise
version 1607
build 14393.1715

**Version of Telegram Desktop:**
1.1.23

**Used theme**:
default

**Comment by auchri** [comment]
Use search pls.

**Comment by cades** [comment]
@auchri I searched, not found any issue duplicate. Could you tell me the duplicate issue number?

**Comment by cades** [comment]
If you mean #3977, #3977 is opened by me because last night Github is backup their database, thus after I submit #3976 it becomes a 404 not found page. So I submit it again.
After the impact passed, I can see the 2 issues again, and I closed #3977 
so please open #3976 again. sorry for any inconvenience.

**Comment by auchri** [comment]
#3868
