### ISSUE TITLE
Dockerfile for building Telegram Desktop

### ISSUE THREAD

**Issue by auchri** [telegramdesktop/tdesktop#3978]
We want to create a Dockerfile which simplifies the building of Telegram Desktop at Linux and Windows.

Repository for the Dockerfiles: https://github.com/telegramdesktop/docker

(Follow-up to #3937)

**Comment by auchri** [comment]
by @sjames1958gm 

> Here is a file that builds telegram in a docker 12.04 container as a starting point.
[dockerfile.txt](https://github.com/telegramdesktop/docker/files/1380111/dockerfile.txt)

(https://github.com/telegramdesktop/docker/issues/1)

**Comment by auchri** [comment]
@vhborges Hi!
Feel free to make PRs to https://github.com/telegramdesktop/docker_linux_build !

**Comment by auchri** [comment]
@vhborges Also notice that in this branch I've made some progress, but it should be updated to the current build instructions: https://github.com/telegramdesktop/docker_linux_build/tree/auchri-patch-1?files=1

**Comment by noamcore** [comment]
Hi, this might be interesting to build a non-gtk too, just passing some argument to the entrypoint. I'll try to create a multi-stage Dockerfile to help here.

**Comment by vhborges** [comment]
Seems like travis is blocking my pull request. This is my first contribution so I didn't know about it until now, sorry.
Maybe [this](https://github.com/telegramdesktop/docker_linux_build/blob/auchri-patch-1/.travis.yml) file would do the job? My commit has the one included on develop branch.

**Comment by Tolsi** [comment]
Is this somehow progressing?
How do you test your application if you don't have an environment where you can just build it? What is the value of an application with source code that cannot be built?
I love Telegram, but this is absurd.

**Comment by B1Z0N** [comment]
What is the current state of affairs? @auchri, If you could supply us with detailed description of your/others work on docker container, then we could start moving on. Otherwise, there are only one option: start from scratch :(
