### ISSUE TITLE
Broadcast Lists

### ISSUE THREAD

**Issue by TheAppService** [telegramdesktop/tdesktop#398]
Hello,

can you please add an option to add and synchronize your broadcast Lists ? 

Thanks very much

Daniel

**Comment by auchri** [comment]
Duplicate #234

**Comment by telegramdesktop** [comment]
Server-side sync for broadcasts lists is not supported by API, client-side broadcast support in tdesktop is not on the task-list right now.

**Comment by mbnoimi** [comment]
+1
