### ISSUE TITLE
Linux desktop app can't  type Chinese

### ISSUE THREAD

**Issue by SZooo** [telegramdesktop/tdesktop#3982]
My os is Ubuntu16.04.  
Use Fcitx Input Method Frame.

**Comment by ilovesusu** [comment]
$cat .xprofile 
 export GTK_IM_MODULE=fcitx
 export QT_IM_MODULE=fcitx
 export XMODIFIERS=@im=fcitx


this file is important

**Comment by SZooo** [comment]
@ilovesusu 

Does it work ?   It doesn't work for me .

▶ cat ~/.xprofile
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

**Comment by ilovesusu** [comment]
I can use fcitx in tg, you can discuss [here](https://t.me/debianzh)

**Comment by SZooo** [comment]
tg? telegram?  do you type Chinese ?

**Comment by SZooo** [comment]
@ilovesusu 
加我GheenotJ

**Comment by sujunmin** [comment]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

Telegram Desktop 1.1.23 

Fcitx (Chewing)

I can type chinese, but when there is showing 'connecting', my input buffer will be empty, like this.

![test](https://user-images.githubusercontent.com/6415168/31925974-7b57f8ce-b8be-11e7-9a42-da889cdf7a5b.gif)
