### ISSUE TITLE
[Win10] Window doesn't scaling when dragging between displays with different scales.

### ISSUE THREAD

**Issue by Veujin** [telegramdesktop/tdesktop#3984]
### Before:
You are required 2 displays.
### Steps to reproduce
1. Right click on desktop field -> Display settings
2. Set two different scales to two different displays.
3. Restart PC.
4. Move Telegram window between displays.

### Expected behaviour
Window fits scale depends on which display it's placed. (Look at Explorer window behaviour for example)

### Actual behaviour
Window scale is set depends on main display scale at system startup and doesn't change.

### Configuration
**Operating system: Win 10**

**Version of Telegram Desktop: 1.1.23**

**Comment by stek29** [comment]
#1121
