### ISSUE TITLE
Written accent randomly can't be written in Telegram Desktop (@Ubuntu)

### ISSUE THREAD

**Issue by EnforcerZhukov** [telegramdesktop/tdesktop#3986]
### Steps to reproduce
1. Run Telegram Desktop
2. Use it, write stuff on groups and/or private chats
3. Randomly, written accent can't be written (I mean, á é í ó ú)

### Expected behaviour
Pressing written accent + a vowel should write on chat á, é, í, ó, ú

### Actual behaviour
Instead, I get a, e, i, o, u without the written accent

### Configuration
**Operating system:** Ubuntu 14.04 trusty

**Version of Telegram Desktop:** 1.1.23

**Used theme**: Vanilla (Night mode)

A common solution is installing dbus and setting is as the input mode on Ubuntu settings, but it doesn't fix the problem for me.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1041 ?
