### ISSUE TITLE
When typing using IME, if the status bar appears and disappears, the editing text will duplicate

### ISSUE THREAD

**Issue by YukinoHayakawa** [telegramdesktop/tdesktop#3988]
### Steps to reproduce
1.  Type a sentence in an empty chat box using Google Pinyin Input without committing it.
2.  While composing the text using the IME, the status bar at the lower-left corner appears (e.g. "Connecting to proxy...") and disappears.

### Expected behaviour
The text in the chat box remains in composing state.

### Actual behaviour
The composing text is considered finished editing and appended to the chat box, with the IME still in the composing state.
If do nothing and the status bar appears and disappears again, the text box will not affected.
If more text is typed into the IME, the whole sentence being composed enters the chat box with composing state, causing the duplication of the previously input text.
If commit the sentence with the IME, the chat box results in two exact copies of the sentence.

### Configuration
**Operating system:**
Windows 8.1
**Version of Telegram Desktop:**
1.1.23
**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
#3868

**Comment by lordfriend** [comment]
When you will merge the PR to master and release a new version... this bug is very annoying. Need to be sovled ASAP

**Comment by YukinoHayakawa** [comment]
@lordfriend Exactly.
