### ISSUE TITLE
Pause / resume uploads and downloads

### ISSUE THREAD

**Issue by manuelsongokuh** [telegramdesktop/tdesktop#3989]
hi

i love A LOT TELEGRAM than whatapp..
so i need to ask you : will be cool to add 'PAUSE/RESUME' for the upload the file..when i want to start upload so that is resume uploading, **avoid** 'RESTART' if i send the file big size..if i lost connect internet so i restart so i lose time/ lose data traffic..so i think to be ad cool pause/resume..
maybe is for app desktop and app andorid, app ios, app mac, app windows..

thank you

**Comment by SonicoXD** [comment]
Why has no one answered this? I'm not entirely sure if it would be possible to do it because of how everything is encrypted, I've read Telegram doesn't store hashes so...
But if possible, it would be an amazingly useful feature. Sometimes, uploading big files can fail because of a lost connection, or you just need to pause a file upload to upload another.

**Comment by beppe9000** [comment]
I think this is a great idea. Even if everything is encrypted the upload state (including cryptographic variables) should be kept intact until you resume, but not persisted on disk.

**Comment by jahmadiiiii** [comment]
Please add this totally needed in Telegram, I dont use Whatsapp Desktop at all Whatsapp have limited functions but Telegram have no Limited function.

**Comment by richidubey** [comment]
Why is this closed?

**Comment by Aokromes** [comment]
because it's duplicated of #809

**Comment by RememberTheAir** [comment]
Is it? #809 is a request for a downloads/uploads manager, that is, a place from where the user can manage ongoing and completed downloads and uploads I think

**Comment by RememberTheAir** [comment]
Bumping this because I still don't see how #809 can superseed this

**Comment by beppe9000** [comment]
In fact I believe this would be a prerequisite for #809, rather than a duplicate.
