### ISSUE TITLE
Not targeted mailing

### ISSUE THREAD

**Issue by andreykyz** [telegramdesktop/tdesktop#399]
Why you are sent me this one?
![2015-01-15 10 48 10](https://cloud.githubusercontent.com/assets/459919/5754047/0e07be6e-9ca4-11e4-89d3-142c1dedcec5.png)
I use only desktop version of telegram. I now about. Please use target sending.

**Comment by auchri** [comment]
Write it to the telegram team on twitter: https://twitter.com/telegram
