### ISSUE TITLE
Telegram breaks IME when the connection is not stable

### ISSUE THREAD

**Issue by lizongzeshunshun** [telegramdesktop/tdesktop#3990]
### Steps to reproduce
1. Type in the input box normally by using an IME(I'm using Chinese IME)
2. Cut off the network.

### Expected behaviour
Telegram should not break the IME.

### Actual behaviour
The IME is force stopped.

Here is a GIF.

![_desktop_20171015222053](https://user-images.githubusercontent.com/10304206/31585619-4e0d4c34-b1f7-11e7-91c0-bb22d1af081f.gif)

### Configuration
**Operating system:** Windows 10 Pro 1703 / Deepin Linux 15.4.1

**Version of Telegram Desktop:** Version 1.1.23

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
use search.
