### ISSUE TITLE
Can't switch language input on MacOS High Sierra

### ISSUE THREAD

**Issue by Tusko** [telegramdesktop/tdesktop#3992]
### Steps to reproduce
1. Trying to change language, but always US (default) in messager

### Configuration
**Operating system:**
MacOS High Sierra 10.13

**Version of Telegram Desktop:**
3.5.107595

**Used theme**:
Default

**Comment by auchri** [comment]
Do you find `3.5.107595` at the releases page?

**Comment by Tusko** [comment]
@auchri 
got it here https://macos.telegram.org/

**Comment by Tusko** [comment]
It was a bug on macOS High Sierra.
Just changed shortcuts for language switching http://cl.ly/n6KZ

**Comment by auchri** [comment]
https://macos.telegram.org/ is __not__ Telegram Desktop.
