### ISSUE TITLE
Contact panel uses 7-10% more CPU

### ISSUE THREAD

**Issue by LuckyLukert** [telegramdesktop/tdesktop#3996]
### Steps to reproduce
1. start Telegram
2. make sure, the left (contact-)panel is visible
3. let the Telegram window be inactive but visible

### Expected behaviour
0-3% CPU load (this is the case when the contact panel is invisible)

### Actual behaviour
5-6% CPU load + 5% Xorg CPU load
if only a chat is shown (the case if you reduce the with of the window until the contact panel disappears)

### Configuration
**Operating system:**
archlinux, window manager: i3-gnome

**Version of Telegram Desktop:**
0.10.9
**Used theme**:
default theme

**Comment by auchri** [comment]
Current version is 1.1.23 lol

**Comment by LuckyLukert** [comment]
thanks, I didn't notice that Telegram stopped updating.
That fixed the problem.
