### ISSUE TITLE
I've configured my account on 2 devices. but one of them logout automatically and ask to login again & again, please help, i need to setup telegram account on two devices, thanks.

### ISSUE THREAD

**Issue by rbshreshtha** [telegramdesktop/tdesktop#3998]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
Please use the template next time.

Which app is being logged out?
