### ISSUE TITLE
Does not show on Windows 8.1

### ISSUE THREAD

**Issue by nilamdoc** [telegramdesktop/tdesktop#400]
Installed telegram, it shows messages are coming in, when click to open window, does not show the window. I tried, reinstalling the latest version.

**Comment by nilamdoc** [comment]
![telegram](https://cloud.githubusercontent.com/assets/230138/5755747/1df8d25c-9cce-11e4-9087-0495eb94bfa7.jpg)

**Comment by auchri** [comment]
Works for me

**Comment by ChrisCA** [comment]
Also works for me :-/

![screenshot 12](https://cloud.githubusercontent.com/assets/4296262/5761365/50ca7e6c-9cdb-11e4-9c52-f7bb829317ba.jpg)

**Comment by telegramdesktop** [comment]
And for me, both in Windows 8.1 and Windows 10 preview.. Don't know what could be the problem, actually.

**Comment by nmat** [comment]
Works for me also on win 8.1
