### ISSUE TITLE
Ubuntu 17.10 tray icon is very small 

### ISSUE THREAD

**Issue by Turnikov** [telegramdesktop/tdesktop#4000]
Tray icon be normally sized.

Tray icon is very small.

Operating system: Ubuntu 17.10

Version of Telegram Desktop: 1.1.23

**Comment by Turnikov** [comment]
This is not a duplicate, there are open issues about icon not appearing at all. Mine exists, but it is small 
![image](https://user-images.githubusercontent.com/19268034/31780627-f2bb1e1e-b4fe-11e7-8f1e-51d6a190a6f3.png)

**Comment by auchri** [comment]
So you want to tell me that the icon in https://github.com/telegramdesktop/tdesktop/issues/3216 is not appearing?

**Comment by Turnikov** [comment]
I have a regular 1920*1080 display and the icon is properly sized in my Debian installation.
