### ISSUE TITLE
Calls are displayed and ringing despite "Disabled notifications"

### ISSUE THREAD

**Issue by espxx** [telegramdesktop/tdesktop#4002]
Can't be sure is it bug or intended behavior, but it would be fine to make it clear and intuitive.
When Telegram is set to "Disable notifications", it blocks messages but calls are still ringing. In addiction with absence of "Mute call" button, you don't have option to skip any calls if you don't want to answer or manually cancel them, making it obvious to person who calling.

It would be nice to block any Telegram activity if notifications are disabled as it supposed to happen and/or to have "Mute call" option as we all got used to on mobile.

**Comment by Zentriert** [comment]
Yeah it's ridiculous that this feature wasn't introduced the moment that Telegram introduced voice calling - both should have been together. 

MANY people use their notebook/desktop for business, for presentations or for media like watching films. NO ONE wants a call and a popup with loud ringing popping up during this - especially in front of their boss or potential clients. 

I find it a huge oversight that there's currently no way to disable calling on specific devices. Many people don't even have a mic with their notebook/desktop so why are calls (and this annoying popup) on by default on these devices? It was a bad choice.

**Comment by Aokromes** [comment]
#3549
