### ISSUE TITLE
[Feature request] Appropriate tray indicator when notifications are disabled.

### ISSUE THREAD

**Issue by espxx** [telegramdesktop/tdesktop#4003]
For now, Telegram desktop doesn't change its own tray icon whether notifications are enabled or disabled as a tip or reminder to user of current state/status at glance.
Often it may lead to missing of important messages if you switched off notifications and forgot about it, while nothing reminds or indicates it to user, for example grayed out or crossed out tray icon.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3383
