### ISSUE TITLE
Telegram window pops up every time I click notification from another apps

### ISSUE THREAD

**Issue by agur4ik** [telegramdesktop/tdesktop#4005]
### Steps to reproduce
1. Start Telegram on KDE Plasma 5
2. Minimize it to tray
3. Click the notification from **another** app

### Expected behaviour
Only the corresponding app reacts

### Actual behaviour
Telegam window opens as well

### Configuration
**Operating system:** Arch Linux, KDE Plasma 5.11

**Version of Telegram Desktop:** 1.1.23

**Used theme**: Default

Not sure if that's KDE bug or Telegram, but it doesn't happen to other apps.

**Comment by Adonai** [comment]
#1026
