### ISSUE TITLE
Library backend

### ISSUE THREAD

**Issue by davidgfnet** [telegramdesktop/tdesktop#4009]
Hey there!
It seems tdesktop is the only open source code base out there that gets support and love from developer(s). The Android version is mostly a very scary repo that gets a giant commit a year :(

I was wondering, how much effort would it be to de-entangle all the proto mess stuff in a way that we can carve out a library usable by other apps and tools? It would be supernice if the backend and the UI app were a bit more separated, doesn't look like it :|

Appreciate your work, many thanks!
David

**Comment by stek29** [comment]
Python - https://github.com/LonamiWebs/Telethon

Rust - https://github.com/JuanPotato/Vail

Rust - https://github.com/Connicpu/mtproto-rs

PHP - https://github.com/danog/MadelineProto

Kotlin - https://github.com/badoualy/kotlogram

JavaScript - https://github.com/zerobias/telegram-mtproto

C - https://github.com/vysheng/tg, https://bitbucket.org/vysheng/tdcli

Elixir - https://gitlab.com/snippets/1664390

C# - https://github.com/unigramdev/unigram

Elixir — https://github.com/Fnux/telegram-mt-elixir and https://github.com/Fnux/telegram-tl-elixir

Is this enough? :)

**Comment by davidgfnet** [comment]
Thanks for the reply!
So I was looking for something in C/C++, and vysehng/tg seems to be
outdated (2 years old at least) and the tdcli looks nice, but it's using a
private subrepo, so...  yeah not really opensource isn't it?
David

**Comment by gi097** [comment]
It might be enough, but wouldn't it be even better if those libraries were official? I am missing an up to date C++ one tho.

**Comment by john-preston** [comment]
@gi097 Currently tdesktop is poorly written in sense of modularity, so it will be a hard task to extract a well API-ed library out of it :(

**Comment by gi097** [comment]
I understand, keep up the good work.

**Comment by davidgfnet** [comment]
Would you be willing to accept patches to untangle the mess as long as functionality stays the same?

**Comment by auchri** [comment]
@davidgfnet Sure :)

**Comment by stek29** [comment]
Also see https://github.com/QtGram/LibQTelegram.

But:
> Viktor
> Hey, are you still working on your TG app?
> 
> Davide
> no, I have left sfos entirely
> I see no reason to develop in a platform where native developers are "inferior" compared to android ones

_harbour-drama_
pls no bully, he's a really nice guy
