### ISSUE TITLE
Remove Deleted Accounts from super group admin

### ISSUE THREAD

**Issue by meysam81** [telegramdesktop/tdesktop#4010]
### Expected behaviour
I, as a creator must be able to remove deleted accounts from super group admins.

### Actual behaviour
Instead, it doesn't react what so ever to me disabling the admin rights and therefor removing a deleted account from admin users

### Configuration
**Operating system:**
Linux mint 18 cinnamon
**Version of Telegram Desktop:**
1.1.23
**Used theme**:
Default theme

**Comment by stek29** [comment]
Just wait a bit.
