### ISSUE TITLE
Incorrect brackets position in Right-to-Left writing languages 

### ISSUE THREAD

**Issue by zerezhka** [telegramdesktop/tdesktop#4012]
### Steps to reproduce
1. change group name to arabic with brackets (e.g. "(البابونج (رياض الأطفال")  p.s. if i use copy-paste from google-translate github also show it's incorrect"
2. in group edit screen everything is ok, but in dialog it looks incorrect

### Expected behaviour
Correct name in title and in "change message"
User Name changed group name to (البابونج (رياض الأطفال
### Actual behaviour
User Name changed group name to البابونج (رياض الأطفال)
in dialog title we can see also البابونج (رياض الأطفال)

### Configuration
**Operating system:**
Linux(Arch, XFCE)

**Version of Telegram Desktop:**
1.1.23

<details><summary><b>Screenshot</b>:</summary>
https://i.imgur.com/QXSHUou.png
</details>

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
