### ISSUE TITLE
Content-Disposition filename header is ignored in download links

### ISSUE THREAD

**Issue by k3it** [telegramdesktop/tdesktop#4013]
### Steps to reproduce
1.  send a message with link that does not include filename as part of the URL but instead passes the file name in the http header, e.g Content-Disposition: Attachment; filename=example.html
2.  click on the link to download the file

### Expected behaviour
Save the attachment with the filename specified in the Content-Disposition HTTP header

### Actual behaviour
The downloaded file is not saved with the correct filename.   This is the case for many "streaming" URLs as well as dropbox links created with files_get_temporary_link API call.  

more info here:
https://www.dropboxforum.com/t5/API-support/URLs-generated-with-files-get-temporary-link-are-not-parsed/m-p/249086#M14300

### Configuration
Windows, Android, iOS

**Version of Telegram Desktop:**
1.1.23

**Comment by auchri** [comment]
How is this related to Telegram Desktop?

**Comment by k3it** [comment]
sorry may be I did not explain clearly. .  You can see the problem if you connect to @qsorder_bot, type N3QE and then  click /N3QE_de_LY4OO   .  It should  return an MP3 link. if you paste this link in a browser (chrome and others) it would save file as N3QE_de_YT7KM_CQWWCW_CW_20161126_224912Z_7MHz.mp3 which is the correct attachment name per the HTTP header.

the issue is that telegram desktop 'Save Audio file As'  and the audio player shows the file as AADc9WBUoTV55Ro4U51zauDeSYRXYq0J.mp3 instead of the friendly name.

this seems to be the case with the mobile telegram clients as well.

![image](https://user-images.githubusercontent.com/9923389/31957659-7b69f228-b8bd-11e7-8cbd-b9b01eef4bd9.png)

**Comment by stek29** [comment]
Server fetches mp3s from links and generates names for them.

**Comment by k3it** [comment]
@stek29 The server does not fetch the file,  it just sends an external link in the message markup:

`bot.send_message(message.chat.id, txt, parse_mode="Markdown")`
(txt contains the url)

It looks like the client then derives the file name from the link in the message.

**Comment by stek29** [comment]
@k3it No, it does. BotAPI != Real TG Api.
