### ISSUE TITLE
[Feature Request] Add Group Events (pinned, joined, left, changed detail) to items that are searchable

### ISSUE THREAD

**Issue by BinaryKitten** [telegramdesktop/tdesktop#4016]
At the Moment, we can Search within groups for messages which is super helpful, but as a member of a group it would be nice to be able to search for things that happen in the group for example:

- people joining
- people leaving
- the title changing
- the image for the group
- pinned message
- person was removed
- person was added

As the search results is people centric, these results would be linked with the actor. So if John Doe adds or removes a user to the chat it shows John Doe as the user in the search results. 
For those that join/leave - their details would be used.

Here is a basic mock up image

![telegram search update](https://user-images.githubusercontent.com/67553/31990038-d7ad90cc-b96b-11e7-8871-73f5ad88946e.png)

This would allow for me as a non-admin member to find when things happened, which is currently unavailable without someone commenting on it.

**Comment by john-preston** [comment]
@BinaryKitten You can use supergroups and their "Recent actions" menu from profile, it has many search and filtering capabilities.

**Comment by BinaryKitten** [comment]
@john-preston thanks for that, but as far as i'm aware "Recent actions" are only a Admin or Owner facility. 
I mention "as an admin it would be nice" - i'll amend that for clarity.

**Comment by john-preston** [comment]
@BinaryKitten No such search for non-admins, sorry :( It can't be done in Telegram Desktop, because API doesn't offer such search facilities.

**Comment by BinaryKitten** [comment]
Ah - so the search is purely an API results output?
that i was not aware of but would make sense.

I'll see if there's a way to upstream the request for these actions to be added to the searchable. 
Thanks For your speedy response @john-preston

**Comment by stek29** [comment]
@BinaryKitten You can do it on Twitter or via in-app support, just in case.
