### ISSUE TITLE
Windows notifications not working in Fall Creator Update

### ISSUE THREAD

**Issue by Lamba92** [telegramdesktop/tdesktop#4017]
Well, the title is pretty self explaining. Both in classic .exe and Microsoft Store happen.

**Comment by Lamba92** [comment]
Maybe duplicate?
https://github.com/telegramdesktop/tdesktop/issues/3826

**Comment by auchri** [comment]
Please define "not working".

**Comment by Lamba92** [comment]
New messages are correctly received, the red badge correctly appear on the telegram icon near the clock and a notification sound is played. Although no sign of graphical notification is shown to the bottom right of the screen nor inside the notification center.

**Comment by auchri** [comment]
Must be related to your setup, because the work for me with the fall creators update 🤷‍♂️

**Comment by Lamba92** [comment]
Happens both on my Surface Laptop and Alienware 17 (2012) with a clean FCU install from USB drive with previous formattation.
