### ISSUE TITLE
Telegram allows deleting seen messages

### ISSUE THREAD

**Issue by woj-tek** [telegramdesktop/tdesktop#4019]
### Steps to reproduce
1. Receive a message from userA
2. *open* and *view* a message from userA
3. userA removes the message indicating that it should be removed for me as well

### Expected behaviour
userA must not be able to delete a message that has already been seen (I'm ok with removal of the messages before I've seen them)

### Actual behaviour
The message is completely removed! This causes quite a concern and is mind-boggling when you would think that you have seen the massage and look through recent ones yet you can't find it!

### Configuration
**Operating system: macOS HighSierra 10.13**

**Version of Telegram Desktop: 1.1.22**

**Used theme**: Dark/night

I think this is an issue with telegram itself as it happens also in all tested telegram clients, see: 
* https://github.com/telegramdesktop/tdesktop/issues/4019
* https://github.com/zhukov/webogram/issues/1531
* https://github.com/overtake/TelegramSwift/issues/26

**Comment by stek29** [comment]
That's expected, and if you don't like it -- then submit a report to Telegram as whole on Twitter or via support.

**Comment by woj-tek** [comment]
Hmm, at the beginning it wasn't allowed and it changed only recently.

I've submitted the bug to the app developer(s) as Telegram itself doesn't offer any sensible means of communications (I have never had any response neither from support nor their twitter...)

**Comment by stek29** [comment]
It wasn't allowed to revoke messages at all, but when revoke option was introduced then it worked as it does now.

Also, even if App developers do it like you suggest, Telegram should then block their apps for terms violation.

**Comment by woj-tek** [comment]
Hmm, I was under the impression that it wasn't possible to delete seen messages but I may have been wrong.

My suggestion wasn't to merely change the apps themselves (which most likely wouldn't work as there may be forks) but to cooperate with Telegram team (which I believe is already in place). As I said - user interaction with Tigase team is virtually nonexistent so communicating this things to app developers seems like the only route...

**Comment by stek29** [comment]
@woj-tek It doesn't go through support, Twitter or even app devs just because nobody of them likes this suggestion.
I'm pretty sure this was discussed when revoke feature was added, and this decision was made.

Also, there are only downvotes on your suggestion in all three issues. So even normal users seem to either dislike or ignore it. 

And I also think your suggestion doesn't fit Telegram's feature philosophy.

So that's why you'll likely never get an answer, and even if you do, behaviour wouldn't be changed.

**Comment by woj-tek** [comment]
@stek29 there are two downvotes (one of which is yours) which compared to millions of Telegram users is... a small number. It's possibly that (because how it's implemented) haven't caused any uproar yet because... noone noticed (short memory and/or "maybe I'm mistaken")?
WhatsApp solved in in a more elegant way (sic!) that for seen messages there is actually an entry "this message was deleted".
Telegram already marks edited messages so I would say marking a placeholder as "deleted" would make sense (and would fit the principle)

**Comment by stek29** [comment]
@woj-tek 
> there are two downvotes (one of which is yours)

There are three if you count one on Webogram.
And no upvotes.

I've seen a lot of weird requests, but I've never seen this.

> WhatsApp solved in in a more elegant way (sic!) that for seen messages there is actually an entry "this message was deleted".

I kinda like this, but:
- What about Groups?
- What about messages deleted after banning someone in group?

As I've said already, if your suggestion is not answered, then it's most likely doesn't seem good enough for people who see it and can pass it further.

**Comment by woj-tek** [comment]
> There are three if you count one on Webogram.
> And no upvotes.

Well, the subset of the users that may be interested in development of the app and that they know what opensource is and what git is and what github severely limits the audience ;-)
And telegram doesn't have any space typical space where user could express some more general concerns (twitter? app stores reviews)? Having something like a uservoice would be an amazing improvement to the communication but... it seems it won't ever happen.
For example, after talking with my (very non tech savvy) friends about the issue - they all were shocked it's possible (also: majority of the users doesn't follow all the news information even though they are posted as a message to the Telegram) 

> I've seen a lot of weird requests, but I've never seen this.

Why it's weird? For me anything that modifies integrity of my local data is weird (i.e. removing something remotely). I'm fully aware that we are forced more and more with the mentality that we have less and less control over our devices (vide forced upgrades of MS Windows for example) but deleting something from our own data without a trace - *IMHO* is more weird...

> I kinda like this, but:

I don't user groups that much but I'll try to make some suggestions.

> - What about Groups?

AFAIR there is a notion of "everyone read" mark (for example in WA there is a difference when the message was delivered to all and read by all, FAQ https://telegram.org/faq#q-what-do-the-green-checks-mean is lacking in this regard).
But: it could follow same pattern - it could delete the message and:
* if someone in the group has seen it - that user would have na "deleted message" marking
* if someone hasn't yet the message - it would be deleted without the mark

> - What about messages deleted after banning someone in group?

Again, no knowledge about banning but - could follow same pattern as above? (or does banned person's messages get deleted automatically? then it could stay that way...)

> - What about multiple deleted messages?

Then we would have multiple entries for each deleted messages (or they could be squashed like Developer Consoles do in the modern browsers for the repeated entries with the same content -- timestamp is less important IMHO)

**Comment by stek29** [comment]
@woj-tek 
> Why it's weird? For me anything that modifies integrity of my local data is weird (i.e. removing something remotely). 

Sorry, I didn't mean this particular request is weird.

About groups -- your suggestions are quite nice, but they will not fit current TG architecture IMO.
Anyway, as I've said already, this isn't the right place to request such thing. 
Maybe someone will notice this and pass it further, but I can't/won't do that.
Sorry.

**Comment by woj-tek** [comment]
Fair enough, thank you for the discussion and feedback.
