### ISSUE TITLE
[Feature request] Integration with system notifications in Ubuntu

### ISSUE THREAD

**Issue by nplezka** [telegramdesktop/tdesktop#402]
I'd like to see unread notifications with native system integrated in Gnome Shell (and OSD notifications for those who have Unity). It would be great!

**Comment by auchri** [comment]
duplicate #91

**Comment by Aokromes** [comment]
@telegramdesktop you can close this :) btw, if you need help with tickets (close duplicate, label) i can help you.

**Comment by pdonadeo** [comment]
:+1:
