### ISSUE TITLE
@mention @all

### ISSUE THREAD

**Issue by nvisser** [telegramdesktop/tdesktop#4020]
It would be nice to have the ability to mention everyone

**Comment by auchri** [comment]
It would be nice to have the ability to search for existing issues before creating a new one.

**Comment by nvisser** [comment]
Searched but could not find, would you mind linking to the duplicate issue?

**Comment by auchri** [comment]
@nvisser Sure, there you go: http://bfy.tw/Egga

**Comment by Mistero5050** [comment]
#2081
