### ISSUE TITLE
Option to ignore incoming call

### ISSUE THREAD

**Issue by Josemaloco** [telegramdesktop/tdesktop#4021]
Feature request.

When you have a Telegram call on your phone, you can silence it with Volume down and suspend your phone, but there is no such option in Telegram desktop.

Currently, if you want to temporarily ignore someone´s call, you have to move the call window away and mute Telegram on Windows mixer.

**Comment by Aokromes** [comment]
#4002

**Comment by Josemaloco** [comment]
x
