### ISSUE TITLE
How to disable emoji right pane?

### ISSUE THREAD

**Issue by JayBeeDe** [telegramdesktop/tdesktop#4023]
### Expected behaviour
A button should be present to disable the emoji right pane even if the window is maximized.

### Actual behaviour
No button is available, so it is not possible to disable this pane when the window is maximized.

### Configuration
**Operating system: Windows 10**

**Version of Telegram Desktop: 1.1.22**

**Comment by Aokromes** [comment]
https://i.imgur.com/pX9r21z.gifv

**Comment by JayBeeDe** [comment]
Hi, 
Thank you for the animation, but unfortunately, it doesn't describe the way to disable the right pane. Where should I click?

**Comment by stek29** [comment]
@JayBeeDe On emoticon

**Comment by JayBeeDe** [comment]
ok thanks I have found
