### ISSUE TITLE
URLs are improperly parsed

### ISSUE THREAD

**Issue by chrjguill** [telegramdesktop/tdesktop#4024]
### Steps to reproduce
1.  Send a url that contains a double underscore in it
2.  ???
3.  Watch as the URL fails to become a url

### Expected behaviour
You should be able to click links such as https://www.reddit.com/user/______DEADPOOL______

(note: not even github parses this link properly!)

### Actual behaviour

This is what I attempt to send (note, the URL parses properly in the textInput and the URL preview is brought up):
![image](https://user-images.githubusercontent.com/3235827/32140606-938ebde2-bc3d-11e7-93a1-0e38b53c1dc7.png)

It becomes this when I send it:

![image](https://user-images.githubusercontent.com/3235827/32140607-9a1526ec-bc3d-11e7-9e9f-d4cd6f4b6366.png)

I'm pretty sure that this was not the case a month or so ago, and I'm not sure what changed. However, URL parsing has always been a bit tricky, but it should definitely have precedence over markdown parsing, since valid markdown can exist in a URL.

Potentially, something could be done with matching parenthesis/brackets, so if I send `[https://www.reddit.com/user/______DEADPOOL______]`, it will parse the string inside the brackets as a single URL. I'm assuming that `[text](link)` markdown is intentionally limited to bots to prevent scamming/trolling or something, so this could be a good workaround.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.1.23

**Used theme**: built-in darkmode

**Comment by stek29** [comment]
#3851
