### ISSUE TITLE
(Re)connecting to server interrupts user-input

### ISSUE THREAD

**Issue by sec2** [telegramdesktop/tdesktop#4025]
### Steps to reproduce
Every time when app (re)connecting to the server while you are tying with Asian language IMEs.

### Expected behaviour
Tell us what should happen
Showing connecting... message (or any equivalent notifications) should be totally independent and not effecting the current behavior of the application. If the user is typing during (re)connecting, the placeholder should not be blocked or unfocused.

### Actual behaviour
Tell us what happens instead
The input placeholder being blocked (or unfocused?) while (re)connecting (Connecting... text label shows on the left-bottom corner) causes IMEs to abandon current message composition => users have to re-compose their message again.
If the internet condition is bad or the internet environment made Telegram keep reconnecting, the users might never have their messages composed => forced to edit their messages on the textpad or any text editor, copy-and-paste them into Telegram => extremely frustrating.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.1.23
**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Mnkai** [comment]
I also have this problem. @auchri Can you please tell me other issue thread's id for reference?

**Comment by auchri** [comment]
@Mnkai #3868
