### ISSUE TITLE
SOCKS5 proxy option does not support GSSAPI Authorization

### ISSUE THREAD

**Issue by Kutabe** [telegramdesktop/tdesktop#4027]
It seems that socks5 proxy option does not support GSSAPI Authorization.
Any other method is not secure - it passes username and password as plain text.
Please, add GSSAPI support.

**Comment by nartamonov** [comment]
It is especially important while recently Telegram is blocked in Russian Federation. Many users install own private SOCKS5 VPN-servers and want to be secured. Insecure authentification is intolerable.

**Comment by john-preston** [comment]
@nartamonov Is it possible in some easy way using Qt built in proxy support? If so, maybe someone will add a pull request?

**Comment by Kutabe** [comment]
@john-preston im afraid its not possible with qt network library, though i may be wrong.
[QT Wiki](http://doc.qt.io/qt-5/qnetworkproxy.html#socks5): 
> The SOCKS5 support since Qt 4 is based on RFC 1928 and RFC 1929. The supported authentication methods are no authentication and username/password authentication.
And SOCKS5 GSS-API is [RFC 1961](http://www.rfc-editor.org/rfc/rfc1961.txt)
