### ISSUE TITLE
Segmentation fault on voip calls

### ISSUE THREAD

**Issue by reagentoo** [telegramdesktop/tdesktop#4028]
Segmentation fault on voip calls with using ALSA instead of PulseAudio

### Steps to reproduce
1. Build and run Telegram on system without PulseAudio
2. Make voip call

### Configuration
**Operating system:** Linux Gentoo ~amd64

**Version of Telegram Desktop:** 1.1.23 (built from sources)

**Debug info:**
https://gist.github.com/reagentoo/feedd90cfd37750827f75674c4f67f61

**Comment by Aokromes** [comment]
#3412
