### ISSUE TITLE
Notification counter on Linux works only if libappindicator-dev is installed

### ISSUE THREAD

**Issue by marcogiorgio** [telegramdesktop/tdesktop#403]
Hi, I am on Linux Mint 17.1 Cinnamon and I'm testing the new notification icon. It is stuck at 1 notification unread even if I receive other messages or I read all of them. I already tried to reboot the app.
![schermata del 2015-01-16 13 21 10](https://cloud.githubusercontent.com/assets/9744031/5776033/8f168de4-9d82-11e4-94cd-07bbc3056585.png)

**Comment by drguell** [comment]
I have a similar issue, when i recive a new message the notification icon mark it, but when i read the message (and write to the contact), the number "1" (or 2, 3, etc) don't dissapear. Only when i recive new messages, the counter restart.

**Comment by Kazaii** [comment]
Confirming that I also experience this with Cinnamon 2.2.16. Also happens when notifications are set to off in a chat (so a grey icon appears instead).

**Comment by VBelozyorov** [comment]
Same here, seems tray icon doesn't updates by event "message was read", only by "message was received"

**Comment by serjor** [comment]
I'm experiencing the same issue. Mint 17.1 cinnamon btw

**Comment by nplezka** [comment]
Same here, Gnome Shell 3.12

**Comment by mxa** [comment]
Same issue here, mint 17.1  cinnamon 64bit. Quitting and restarting Telegram will remove the stuck notification.

**Comment by ctrlbru** [comment]
Same for me on mint 17.1 cinnamon 64. The behaviour is erratic: when you receive the first msg after starup, it shows one. It's not resetted to 0 when you read it. If you receive another, it stays to 1. If you receive a third without reading the second, the counter shows 2, and sometimes it goes back to 1 when you read them, sometimes it does not.

**Comment by aix27249** [comment]
Same for me, Gnome 2.32

**Comment by EliaGeretto** [comment]
It seems that this happens when you don't have libappindicator installed. As written in issue #80 when you don't have that library Telegram falls back to gtk_status_icon.

**Comment by marcogiorgio** [comment]
I confirm that problem is solved installing libappindicator-dev package

**Comment by boris-il-forte** [comment]
I think the problem is that the application should not check for the presence of "libappindicator-dev", but for the presence of  libappindicator1 (at least this is the debian name). In theory the Dev package contains headers, and the compiled library, that is needed by compiled source code, is in the other package. This issue shuould be reopened.

**Comment by marcogiorgio** [comment]
@telegramdesktop the notification counter works correctly only if libappindicator-dev is installed not with libappindicator1.

**Comment by adisos** [comment]
+1, installing `libappindicator-dev` solved problem

**Comment by aix27249** [comment]
I suppose that if required dependency is unavailable, behavior should be "not implement at all", not "just buggy". So, the message counter should either be displayed in correct way, or not displayed at all.

**Comment by thomich** [comment]
hey hey

i don't wan't install libappindicator-dev, cause it does install a lot of other (not needed) packages... would be fine if this will be fixed in another way...

btw. great app ;).... love it

**Comment by drguell** [comment]
hi, 
I tried to install some libappindicator packages (in archlinux, the headers are included in "normal" package), but nothing, the problem is here.

I installed the next packages:
local/libappindicator-gtk2 12.10.0-4
local/libappindicator-gtk3 12.10.0-4
local/libappindicator-sharp 12.10.0-4

The lib32-libappindicator package try to install a lot of packages and i don't want to install it. Maybe are this package the needed, but isn't a candidate for me. 

btw. congrats for the app, is awesome.

**Comment by drguell** [comment]
I can see that in version 0.7.8 the problem are fixed. 
Thanks!

**Comment by marcogiorgio** [comment]
I confirm that libappindicator-dev and its dependencies aren't required in 0.7.8. Issue closed

**Comment by telegramdesktop** [comment]
From version 0.7.16 tray icons should work through libappindicator in Unity environments and through Qt implementation otherwise (with show/hide of window by left click or other "activate" event). Please check.

**Comment by thomich** [comment]
great.. updated and works fine ;) MANY THANKS..
