### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by mclapson** [telegramdesktop/tdesktop#4031]
Please consider adding a feature to separate groups and individual chats in the chat list, so that groups will show up together - potentially above all individual chats.

**Comment by auchri** [comment]
Please consider searching for duplicates.

**Comment by mclapson** [comment]
I had searched for duplicates, I am a bit disappointed in the passive aggressive response especially if the original request is not linked.

**Comment by auchri** [comment]
@mclapson And I am a bit disappointed about the people which seem to be not able to search for duplicates. About 75% of all new created issues are duplicates.

Assume 5 of this duplicated issues would be created per day and it takes me 5 minutes per issue to search for the duplicated issue, I would waste 25 minutes per day just for searching issues.
If the creators of the issues would search themselves, each of them would just loose 5 minutes and I wouldn't loose 25 minutes.
