### ISSUE TITLE
Telegram doesn't properly block users direct/private messages.

### ISSUE THREAD

**Issue by DewArmy** [telegramdesktop/tdesktop#4033]
### Steps to reproduce
1.  Block a user
2.  Have them try to send you a message (they can still send) and not get a notice that you've blocked them.
3.  Rinse and Repeat.

### Expected behaviour
_Tell us what should happen:_

They should absolutely know they've been blocked, not just blackhole their messages so they think they can keep chatting.

### Actual behaviour
_Tell us what happens instead_

The other person can keep sending messages into nothingness. (person who "soft" blocked them still sees them typing

### Configuration
**Operating system:**
ALL

**Version of Telegram Desktop:**
1.1.22

**Used theme**:
None

**Comment by john-preston** [comment]
@DewArmy This is how blacklisting works in Telegram, it is not related to Telegram Desktop and I can’t fix that :(

**Comment by DewArmy** [comment]
Where can I file the bug request so this can get fixed if not here?

**Comment by stek29** [comment]
@DewArmy On Twitter or via in-app support.
