### ISSUE TITLE
Audio files are played in mono

### ISSUE THREAD

**Issue by Knifa** [telegramdesktop/tdesktop#4034]
### Steps to reproduce
1. Send/receive a stereo audio file to/from someone. (e.g., attached: [sample.zip](https://github.com/telegramdesktop/tdesktop/files/1436267/sample.zip))
2. Play it using the built-in audio player.

### Expected behaviour
Audio should be played using both channels.

### Actual behaviour
Audio is down-mixed to mono. I'm not sure if both channels are combined, or if it's just playing the same single channel on both speakers. Either way, it's not true stereo.

Occurs with multiple formats (mp3/ogg/wav)

### Configuration
**Operating system:**
Windows 10 (Creators Update)

**Version of Telegram Desktop:**
1.1.23

**Comment by daniel13gh** [comment]
Just noticed the same issue. It's certainly not mono but rather strongly reduced stereo.  

The problem only exists on a Desktop client.  Tested on Windows 10 and Ubuntu with the latest Version of Telegram Desktop.

The very same files from the same chats are played normally on mobile (Apple iOS 10, various Androids) 

I can't think of any technical reasons for such a behaviour unless there's some transcoding involved.

**Comment by Knifa** [comment]
Glad someone else noticed!

> I can't think of any technical reasons for such a behaviour unless there's some transcoding involved.
If you download the file and play it in something normal (foobar2k, VLC, etc, etc) it'll sound totally fine so it seems like it must be with the client itself.

**Comment by NECRODEFLORATOR** [comment]
An interesting fact is that initially everything was fine (about a year and a half ago), and then something was updated and this bug happened

**Comment by Knifa** [comment]
Here's another test file. This should be four beeps fully panned left, then four fully panned right:
 [stereo_test.zip](https://github.com/telegramdesktop/tdesktop/files/1515430/stereo_test.zip)

Playing in my usual player (foobar2k) and the source (FL Studio) gives full panning as expected.

Playing in Telegram, the channels leak into each other.

**Comment by Knifa** [comment]
I recorded Telegram playing the audio file so I could look at it in Audacity, using Virtual Audio Cable. It seemed to exacerbate the problem. It looks it's being played twice? Or there's a delay or something?

![image](https://user-images.githubusercontent.com/622619/33397829-d3719432-d544-11e7-8af7-308659b8eccd.png)

Top shows the source. Bottom shows Telegram.

I don't have any other way to record audio output so this is the best I could get.

**Comment by daniel13gh** [comment]
OK. the version 1.2 of the desktop client is there but no improvement on the issue.

Reading the list of the libraries for the Telegram Desktop I wonder if it's FFMPEG taking care of the audio playback in real time. The many settings of FFMPEG, some mistake in its configuration may lead easily to any kind of issue.

**Comment by john-preston** [comment]
@daniel13gh FFmpeg is used to decode and sometimes resample audio and OpenAL is used to play it.

**Comment by NECRODEFLORATOR** [comment]
They fix that s**t!! YEAH!

**Comment by kokoko3k** [comment]
I can confirm that this is (still) an issue in the Linux version too.
