### ISSUE TITLE
Chatbox bug, All Chatbox in Left Position While Maximized (it should be not)

### ISSUE THREAD

**Issue by jerryshaw12** [telegramdesktop/tdesktop#4040]
### Steps to reproduce
1. Open Telegram
2. Maximize it
3. Tada you found the bug

### Expected behaviour
Tell us what should happen
The Chat Bubble Should be in different for sender and receiver  
### Actual behaviour
Tell us what happens instead
 All Chatbox in Left Position
### Configuration
**Operating system:**
Windows 10 1709
**Version of Telegram Desktop:**
1.1.23
**Used theme**:
White/Dark don't have different 
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>
Pics:

what it should be https://imgur.com/a/ohR2q
what it looks like https://imgur.com/a/mIPj1

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1652 ?

**Comment by auchri** [comment]
@jerryshaw12 That's not a bug, there is a setting for that in the settings.

**Comment by jerryshaw12** [comment]
where? i can't find it

**Comment by jerryshaw12** [comment]
oh i found it, i does not show if i am not resize the window to maximized

**Comment by auchri** [comment]
@jerryshaw12 exactly
