### ISSUE TITLE
-- DELETED BY USER -- 

### ISSUE THREAD

**Issue by reb3lzrr** [telegramdesktop/tdesktop#4042]
-- DELETED BY USER --

**Comment by MissSheyni** [comment]
https://Telesco.pe/Na_Za_NiiiN‌

Miss Sheyni

**Comment by MissSheyni** [comment]
body, p, div {
        font-family: arial;
        font-size: 14px;
      }
      body {
        color: #000000;
      }
      body a {
        color: #1188E6;
        text-decoration: none;
      }
      p { margin: 0; padding: 0; }
      table.wrapper {
        width:100% !important;
        table-layout: fixed;
        -webkit-font-smoothing: antialiased;
        -webkit-text-size-adjust: 100%;
        -moz-text-size-adjust: 100%;
        -ms-text-size-adjust: 100%;
      }
      img.max-width {
        max-width: 100% !important;
      }
      .column.of-2 {
        width: 50%;
      }
      .column.of-3 {
        width: 33.333%;
      }
      .column.of-4 {
        width: 25%;
      }
      @media screen and (max-width:480px) {
        .preheader .rightColumnContent,
        .footer .rightColumnContent {
            text-align: left !important;
        }
        .preheader .rightColumnContent div,
        .preheader .rightColumnContent span,
        .footer .rightColumnContent div,
        .footer .rightColumnContent span {
          text-align: left !important;
        }
        .preheader .rightColumnContent,
        .preheader .leftColumnContent {
          font-size: 80% !important;
          padding: 5px 0;
        }
        table.wrapper-mobile {
          width: 100% !important;
          table-layout: fixed;
        }
        img.max-width {
          height: auto !important;
          max-width: 480px !important;
        }
        a.bulletproof-button {
          display: block !important;
          width: auto !important;
          font-size: 80%;
          padding-left: 0 !important;
          padding-right: 0 !important;
        }
        .columns {
          width: 100% !important;
        }
        .column {
          display: block !important;
          width: 100% !important;
          padding-left: 0 !important;
          padding-right: 0 !important;
        }
      }
    
    
    
     
  
  
    
      
        
          
            
              
                
                  
                    
                      
                        
                          
                          
                            
                              
                                
    
      
        
          
        
      
    
  
    
      
        
          
        
      
    
  
    
      
        
            Lucky you
        
      
    
  
    
      
        
          
        
      
    
  
    
      
        
             

We just got you a free premium invite thanks to the 38 people from your Gmail network who recently joined us. 

 


We showcase every idea, project, and start-up from around the world and connect them to the millions of people who could work with them, including you.

 


        
      
    
  Get your invite 
    
      
        
            - from California with love -
        
      
    
  
    
      
        
          
            
              
            
          
        
      
    
  
    
      
        
            

	
		
			
			 
			
			 
		
	



	
		
		
		
			© 2017 Wittycircle Inc
		
		
		
		
			169th 11th St, San Francisco, CA
		
		
		
		
			wittycircle.com
		
	


        
      
    
  
                              
                            
                          
                          
                        
                      
                    
                  
                
              
            
          
        
      
    
  
This email was sent by Wittycircle, to unsubscribe click here.
