### ISSUE TITLE
Wrong emoji for stickers

### ISSUE THREAD

**Issue by chimit** [telegramdesktop/tdesktop#4043]
### Steps to reproduce
1. Create a sticker pack
2. Add a sticker with emoji 💪👨‍🎤

### Expected behaviour
Get these emojis 💪👨‍🎤 bound with a sticker instead of 💪 👨 🎤

### Actual behaviour
After the sticker creation, the emoji for this sticker will be 💪 👨 🎤

### Configuration
**Operating system:** macOS High Sierra 10.13.1 (17B48)

**Version of Telegram Desktop:** 1.1.22

**Used theme**: default

**Comment by stek29** [comment]
Huh?
They're same...

**Comment by chimit** [comment]
Really? Two emojis are same with three emojis?

Arm and soldier = arm, man, microphone?

**Comment by stek29** [comment]
@chimit \*shrug\*

Here's what I see on macOS:
![image](https://user-images.githubusercontent.com/11808223/32413244-96e2565c-c21e-11e7-8e14-b4ed14dbd96f.png)

And here's what I see on Android:
![image](https://user-images.githubusercontent.com/11808223/32413256-d4a5dbe4-c21e-11e7-86ba-bd49254a3ae6.png)

**Comment by stek29** [comment]
Anyway, it has nothing to do with TDesktop, and is either an API issue or Stickers Bot issue.
