### ISSUE TITLE
Build with VS 2017 - Error LNK1104: cannot open file 'qwebpd.lib'	

### ISSUE THREAD

**Issue by phamhop94** [telegramdesktop/tdesktop#4046]
Hello all,
I'm building telegram with VS 2017, following [https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md)
I built fail Telegram project by Error LNK1104: cannot open file 'qwebpd.lib'.
I searched in BuildPath folder, but I didn't find 'qwebpd.lib'.
anyone resolve this problems ? please help me .
thanks.

**Comment by john-preston** [comment]
@phamhop94 This is an image format plugin that Qt build should contain.

**Comment by phamhop94** [comment]
I run below code again, but qwebpd.lib not found...
`git clone git://code.qt.io/qt/qt5.git qt5_6_2
cd qt5_6_2
perl init-repository --module-subset=qtbase,qtimageformats
git checkout v5.6.2
cd qtimageformats
git checkout v5.6.2
cd ..\qtbase
git checkout v5.6.2
git apply ../../../tdesktop/Telegram/Patches/qtbase_5_6_2.diff
cd ..`

**Comment by john-preston** [comment]
@phamhop94 It should be there after configure, jom, jom install part.

**Comment by auchri** [comment]
@john-preston whats about

``configure -debug-and-release -force-debug-info -opensource -confirm-license -static -I "%cd%\..\openssl\Release\include" -no-opengl -openssl-linked OPENSSL_LIBS_DEBUG="%cd%\..\openssl\Debug\lib\ssleay32.lib %cd%\..\openssl\Debug\lib\libeay32.lib" OPENSSL_LIBS_RELEASE="%cd%\..\openssl\Release\lib\ssleay32.lib %cd%\..\openssl\Release\lib\libeay32.lib" -mp -nomake examples -nomake tests -platform win32-msvc2015 jom -j4 jom -j4 install cd ..``

**Comment by john-preston** [comment]
@phamhop94 It should be in "Libraries\qt5_6_2\qtbase\plugins\imageformats" folder.

**Comment by phamhop94** [comment]
In "imageformats" folder has qwebpd.prl file. I dont see qwebpd.lib. Seem I did wrong something.

**Comment by nevilad** [comment]
I had the same issue on a non english windows. Building on a virtual machine with Windows 10 En solved it.

**Comment by nevilad** [comment]
I had the same issue on a non english windows. Building on a virtual machine with Windows 10 En solved it.

**Comment by WilixLead** [comment]
I have same problem on macOS 10.13.3
`ld: library not found for -lqwebp_debug`

When I check directory under `/usr/local/tdesktop/Qt-5.6.2/plugins/imageformats`
I see only `libqico*` and nothing more. Bu under my `buildPath/Libraries/qt5_6_2/qtimageformats/src/plugins/imageformats` I see 
`webp` and many other formats

**Comment by physbyte** [comment]
@john-preston i have same problem, how to fix it?
OS: Windows 10 with all updates.

Need update "Build instructions for Visual Studio 2017"
1. if install Phyton 2.7.0 need add to path:
`BuildPath\ThirdParty\Python27`
2. Download CMake 3.9.6 (maximum) with dll files in bin folder **(.zip archive)** and unpack to **BuildPath\ThirdParty\cmake** (maybe installer have dlls too)
2.1 And too add to path
`BuildPath\ThirdParty\cmake`
or u cant do this:
```
msbuild OpenAL32.vcxproj /property:Configuration=Debug
msbuild OpenAL32.vcxproj /property:Configuration=Release
```

<details><summary><b>Logs after jom</b>:</summary>
E:\tdesktop\BuildPath\Libraries\qt5_6_2>jom

jom 1.1.2 - empower your cores

cd qtbase\ && ( if not exist Makefile E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\bin\qmake E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\qtbase.pro -o Makefile ) && E:\tdesktop\BuildPath\ThirdParty\jom\jom.exe -f Makefile
cd src\ && ( if not exist Makefile E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\bin\qmake E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\src\src.pro -o Makefile ) && E:\tdesktop\BuildPath\ThirdParty\jom\jom.exe -f Makefile
cd tools\bootstrap\ && ( if not exist Makefile E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\bin\qmake E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\src\tools\bootstrap\bootstrap.pro -o Makefile ) && E:\tdesktop\BuildPath\ThirdParty\jom\jom.exe -f Makefile
cd qmake\ && ( if not exist Makefile.qmake-docs E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\bin\qmake E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\qmake\qmake-docs.pro -o Makefile.qmake-docs ) && E:\tdesktop\BuildPath\ThirdParty\jom\jom.exe -f Makefile.qmake-docs
E:\tdesktop\BuildPath\ThirdParty\jom\jom.exe -f Makefile.qmake-docs.Debug
E:\tdesktop\BuildPath\ThirdParty\jom\jom.exe -f Makefile.Debug
cd 3rdparty\pcre\ && ( if not exist Makefile E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\bin\qmake E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\src\3rdparty\pcre\pcre.pro -o Makefile ) && E:\tdesktop\BuildPath\ThirdParty\jom\jom.exe -f Makefile
E:\tdesktop\BuildPath\ThirdParty\jom\jom.exe -f Makefile.Debug
cd tools\moc\ && ( if not exist Makefile E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\bin\qmake E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\src\tools\moc\moc.pro -o Makefile ) && E:\tdesktop\BuildPath\ThirdParty\jom\jom.exe -f Makefile
E:\tdesktop\BuildPath\ThirdParty\jom\jom.exe -f Makefile.Debug
link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:..\..\..\bin\moc.exe @C:\Users\null\AppData\Local\Temp\moc.exe.8304.0.jom
QtBootstrapd.lib(qbytearray.obj) : error LNK2019: ёё√ыър эр эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы _z_compress2 т ЇєэъЎшш "class QByteArray __cdecl qCompress(unsigned char const *,int,int)" (?qCompress@@YA?AVQByteArray@@PBEHH@Z)
QtBootstrapd.lib(qbytearray.obj) : error LNK2019: ёё√ыър эр эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы _z_uncompress т ЇєэъЎшш "class QByteArray __cdecl qUncompress(unsigned char const *,int)" (?qUncompress@@YA?AVQByteArray@@PBEH@Z)
..\..\..\bin\moc.exe : fatal error LNK1120: эхЁрчЁх°хээ√ї тэх°эшї ¤ыхьхэЄют: 2
cd tools\rcc\ && ( if not exist Makefile E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\bin\qmake E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\src\tools\rcc\rcc.pro -o Makefile ) && E:\tdesktop\BuildPath\ThirdParty\jom\jom.exe -f Makefile
jom: E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\src\tools\rcc\Makefile.Debug [..\..\..\bin\rcc.exe] Error 1120
E:\tdesktop\BuildPath\ThirdParty\jom\jom.exe -f Makefile.Debug
link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:..\..\..\bin\rcc.exe @C:\Users\null\AppData\Local\Temp\rcc.exe.6148.0.jom
QtBootstrapd.lib(qbytearray.obj) : error LNK2019: ёё√ыър эр эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы _z_compress2 т ЇєэъЎшш "class QByteArray __cdecl qCompress(unsigned char const *,int,int)" (?qCompress@@YA?AVQByteArray@@PBEHH@Z)
QtBootstrapd.lib(qbytearray.obj) : error LNK2019: ёё√ыър эр эхЁрчЁх°хээ√щ тэх°эшщ ёшьтюы _z_uncompress т ЇєэъЎшш "class QByteArray __cdecl qUncompress(unsigned char const *,int)" (?qUncompress@@YA?AVQByteArray@@PBEH@Z)
..\..\..\bin\rcc.exe : fatal error LNK1120: эхЁрчЁх°хээ√ї тэх°эшї ¤ыхьхэЄют: 2
jom: E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\src\tools\rcc\Makefile [debug] Error 2
jom: E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\src\tools\moc\Makefile.Debug [..\..\..\bin\moc.exe] Error 1120
jom: E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\src\tools\moc\Makefile [debug] Error 2
jom: E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\src\Makefile [sub-moc-make_first] Error 2
jom: E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\src\Makefile [sub-rcc-make_first] Error 2
jom: E:\tdesktop\BuildPath\Libraries\qt5_6_2\qtbase\Makefile [sub-src-make_first] Error 2
jom: E:\tdesktop\BuildPath\Libraries\qt5_6_2\Makefile [module-qtbase-make_first] Error 2
</details>

and sure, i cant build debug/release in Virtual Studio.
<details><summary><b>Logs VS2017</b>:</summary>
1>E:\tdesktop\BuildPath\ThirdParty\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True codegen_style.exe "E:\tdesktop\BuildPath\ThirdParty\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:codegen_style.exe @codegen_style.exe.rsp" 1 mt.exe rc.exe "obj\codegen_style.codegen_style.exe.intermediate.manifest" obj\codegen_style.codegen_style.exe.generated.manifest
1>LINK : fatal error LNK1104: эх єфрхЄё  юЄъЁ√Є№ Їрщы "qwebpd.lib"
</details>

**Comment by 23rd** [comment]
Outdated. Please reopen it if you still have problems with compilation.
