### ISSUE TITLE
i3wm: call window remains on top, unable to close it

### ISSUE THREAD

**Issue by NoMore201** [telegramdesktop/tdesktop#4047]
### Steps to reproduce
1. Open telegram using i3 window manager
2. Receive a call

### Expected behaviour
The call window should close after accepting or refusing call

### Actual behaviour
Call windows remains on top, without the possibility to close it. Also, it will be visible in all workspaces, and WM_CLASS variable of the call window is the same of the main window: `WM_CLASS(STRING) = "telegram-desktop", "TelegramDesktop"`, so it's not possible to control its behaviour through i3 configuration file.

### Configuration
**Operating system:** Archlinux, xorg-server 1.19.5

**Version of Telegram Desktop:** 1.1.23 official binaries

**Used theme**: default, night mode

<details><summary><b>Logs</b>:</summary>
No useful log found

</details>

**Comment by zaps166** [comment]
#3499 ?
