### ISSUE TITLE
macOS: Making app name bold

### ISSUE THREAD

**Issue by talanov** [telegramdesktop/tdesktop#4049]
Please make the application name in the global app menu bold. 
This is made by all apps already, because it is in [guidelines](https://developer.apple.com/library/content//documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuBarMenus.html#//apple_ref/doc/uid/20000957-CH29-SW3).
 
### Configuration
**Operating system: macOS High Sierra**

**Version of Telegram Desktop:3.5.107970**

**Used theme: default**

**Comment by auchri** [comment]
> 3.5.107970

Do you find that version [here](https://github.com/telegramdesktop/tdesktop/releases)?

**Comment by stek29** [comment]
@talanov 
This is not Telegram Desktop.
You can download Telegram Desktop at https://desktop.telegram.org.

Also, you can report issues in app you're using at https://t.me/macswift.
