### ISSUE TITLE
mozjpeg JPEG encoder

### ISSUE THREAD

**Issue by mirhl** [telegramdesktop/tdesktop#405]
https://github.com/mozilla/mozjpeg

To sum up benefits: this would both improve [quality](http://calendar.perfplanet.com/2014/mozjpeg-3-0/) *and* [size](https://blog.cloudflare.com/experimenting-with-mozjpeg-2-0/), while still keeping compatibility with every existing viewer

What's your opinion on including it in the client?

**Comment by Flash-back** [comment]
Good idea!

**Comment by telegramdesktop** [comment]
I'm currently using Qt image readers, I hope they will include it in some version :) I am not very excited about the idea of having a second jpeg encoder along with the used one from Qt.

**Comment by mirhl** [comment]
If it would add to much clutter to the program, qt one will probably be fine then. 
Regards

**Comment by mirh** [comment]
http://lists.qt-project.org/pipermail/interest/2015-May/016965.html
It seems qt won't switch itself to mozjpeg (for as much.. I can't understand if they switched to libjpeg-turbo at least?). 

Though 1) I still wonder if it mightn't be worth the switch, in telegram case 2) It seems there's nothing special from your side to add. 
The alternatives all share the same ABI, and it should just be a matter of compiling against it.
