### ISSUE TITLE
How i can Get User.access_hash, when i know only User.id ? 

### ISSUE THREAD

**Issue by skvoshiz** [telegramdesktop/tdesktop#4050]
How i can Get User.access_hash, when i know only User.id ?

**Comment by auchri** [comment]
How is this related to Telegram Desktop?

**Comment by john-preston** [comment]
@skvoshiz You can’t. That’s the whole point of access_hash, you can’t just go through all possible user_ids and send them messages.

**Comment by stek29** [comment]
@skvoshiz You should get it "legally" -- by getting `user` from server.
[Here's the list of methods/constructors which have it](https://stek29.rocks/tl-schema/latest/type/User).
