### ISSUE TITLE
Autoplay not available

### ISSUE THREAD

**Issue by thob** [telegramdesktop/tdesktop#4058]
### Steps to reproduce
1. Start audio file #1 in channel

### Expected behaviour
File #2 should start playing

### Actual behaviour
Nothing, file #1 just stops playing

### Configuration
Linux Mint 17.3

**Version of Telegram Desktop:**
Alpha 1.1.23

**Used theme**:
Default, night mode

**Comment by thob** [comment]
seems to work again. _(could have been theme-related, as I used another one before)_

**Comment by auchri** [comment]
@thob Most likely not theme related but I'm glad it's working now :)
