### ISSUE TITLE
Tray icon doesn't show up

### ISSUE THREAD

**Issue by TheAppService** [telegramdesktop/tdesktop#406]
Hello,

I don't know why but the telegram icon is not shown in my bar on the top of the desktop. I'm using Ubuntu 14.04.
![bildschirmfoto vom 2015-01-16 17 16 10](https://cloud.githubusercontent.com/assets/6033570/5779510/91ec776a-9da3-11e4-8fd8-2bac00de4f7b.png)

Daniel

**Comment by aseredenko** [comment]
![image](https://cloud.githubusercontent.com/assets/6630181/5780088/62332502-9db0-11e4-9e34-f05616875640.png)
Probably, we should find number of new messages here. But I don't see it here, too.

**Comment by DavideR3da** [comment]
me too! in ubuntu 14.04 tray icon doesn't appear and the the notification of unread message only appear in the title of the unity icon on mouse hover (Telegram Desktop 0.7.7)

**Comment by TheAppService** [comment]
Ok after the update today it works.
