### ISSUE TITLE
unsent and unsaved text deleted when sending other message on other device

### ISSUE THREAD

**Issue by getreal313** [telegramdesktop/tdesktop#4060]
### Steps to reproduce
1. On windows 10 installed desktop telegram start write a longer message and let draft be saved and continue write.
2. On android phone send other quick telegram message for same account.
3. When returning to windows desktop you may find(I did) your last couple of sentences gone.

### Expected behaviour
Tell us what should happen
* Should be able to continue writing my longer message on windows telegram desktop.
### Actual behaviour
Tell us what happens instead
text not saved to draft disappered.
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.1.23
**Used theme**:
don't understand :|
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
That's how draft sync works.
You can use Ctrl/Cmd + Z to get your old text.
