### ISSUE TITLE
please add admin label for the group.

### ISSUE THREAD

**Issue by fankoo** [telegramdesktop/tdesktop#4062]
In the group, sometimes admin need to post important information, however someone make scam we can't recognize which are post by admin. so please add admin label for the admin so we can see who is admin.

**Comment by MasterGroosha** [comment]
This is already implemented in mobile versions (Android, iOS, probably Windows Phone), so I suppose we just have to wait a bit :)

**Comment by auchri** [comment]
Added with Alpha 1.1.26
