### ISSUE TITLE
Is tdesktop still alive?

### ISSUE THREAD

**Issue by mydexterid** [telegramdesktop/tdesktop#4063]
- Last significant commit was in Sept. 5.
- Last tweet was on March 31: https://twitter.com/telegramdesktop/status/847789385101848576
- Last changelog shows 1.1.20: https://desktop.telegram.org/changelog

What is going on?

**Comment by john-preston** [comment]
@mydexterid I’m just a very slow developer 😔

**Comment by mydexterid** [comment]
No issues, just wanted to know if it is still developed :)
