### ISSUE TITLE
Allow scaling above 200%

### ISSUE THREAD

**Issue by flipflop97** [telegramdesktop/tdesktop#4064]
I'm using a high DPI monitor with 250% Windows scaling. Telegram Desktop only supports up to 200% scaling, making it look small in comparison with the rest of the UI. Can this limit be changed to support up to at least 250%?

**Comment by auchri** [comment]
Thanks for search for duplicates <sub>not™</sub>

**Comment by flipflop97** [comment]
Actually, I did search for duplicates but couldn't find one. Can you link me to the other issue?

**Comment by auchri** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1121

**Comment by flipflop97** [comment]
Yes, I found that one, but auto scaling based on monitor DPI and raising the manual scaling limit are two different things. Raising the limits is mentioned in the comments but that's not really what the issue is about.

**Comment by auchri** [comment]
Yes but it would solve your issue too.

**Comment by marhoily** [comment]
Any progress? I would love to have a quick workaround. May be a command line argument or ini file.
I've weak sight, friend who wouldn't use anything but the telegram and a 4K monitor.

**Comment by 96fps** [comment]
On the other end of the spectrum, I use telegram on a single monitor, but it's relatively Low-DPI. Most webpages I view at 67% or 80% scale, it there any chance of dpi scales below 100%?

**Comment by gubenkovalik** [comment]
i scaled it up to 300% and i can't click on settings button to make the scale back to previous, because simply the settings button goes beyond the screen and it is impossible to revert changes back using UI.
![image](https://user-images.githubusercontent.com/5104168/47136793-721daf00-d2bd-11e8-93b3-047c959d9c46.png)
