### ISSUE TITLE
Feature proposition. Tripple tick sign.

### ISSUE THREAD

**Issue by e-coeur** [telegramdesktop/tdesktop#4065]
Greetings.
I want to offer you to develop a new feature in your app.
It is about functionality of indication whether the interlocutor had read your message.
You already have this functionality  with one or two tick signs, but it would be great to know that your interlocutor in group or supergroup read the message that was sent to him via @ sign.

**Comment by auchri** [comment]
No such functionality in the api.

**Comment by stek29** [comment]
And never is going to be added I guess:

> We don't have an additional status for 'message delivered to device',
> because you can use Telegram on multiple devices simultaneously.
> Since you don't know which one of their devices the person
> is actually using, delivery to one of the devices becomes irrelevant.
>
> _from Telegram Support templates_
