### ISSUE TITLE
[linux] Can not close image preview after Alt+Tab

### ISSUE THREAD

**Issue by m00nk** [telegramdesktop/tdesktop#4067]
### Steps to reproduce
1. open any chat
2. click on any image to show the full screen preview
3. press Alt+Tab one or more times

### Expected behaviour
close the full screen preview and switch to another application window

### Actual behaviour
the full screen preview window is still visible but it is inactive and there is no way to close it

### Configuration
Linux Mint 18 (Ubuntu 16.10), XFCE desktop environment

**Telegram Desktop version**:
1.1.23 and many previous (that bus is old).

**Used theme**:
I did not changed the themes before, so... I guess it is default.

**Comment by stek29** [comment]
#3553
