### ISSUE TITLE
[Feature request] add a start minimized option on linux version

### ISSUE THREAD

**Issue by ScorpionIT** [telegramdesktop/tdesktop#407]
I'd like to have the possibility to start telegram minimized in the tray icon

**Comment by auchri** [comment]
Its already in the settings: 
![image](https://cloud.githubusercontent.com/assets/5092164/5782902/f63e8ad0-9dbe-11e4-9ecc-2f5d434959ee.png)

**Comment by ScorpionIT** [comment]
This feature is not present on linux version.
I have corrected the title

**Comment by EmptyStackExn** [comment]
Yes ! That would be great in Linux. In fact, `autostart` is not **even** necessary

Maybe you can **just simply add some option** like `./Telegram --no-startup-window` in order to load the app only in background (as we already have a app indicator).

Then, we would add ourselves the command into `Startup applications`

**Comment by lucidfox** [comment]
+1. This is currently the major reason why I'm not adding Telegram to autostart.

**Comment by auchri** [comment]
@EmptyStackExn v7.10 comes with -runintray cmd parameter

**Comment by netsurfer912** [comment]
I have it on autostart, but the window opening is a little annoying. It's bearable, though.

**Comment by netsurfer912** [comment]
//Since the mobile version of GitHub does not seem to allow comment editing, I'll add another one. 

Many desktop environments have an autostart functionality. I know GNOME has it and you might add a feature to enable it from the tg settings.

**Comment by telegramdesktop** [comment]
Try "-startintray" commandline option in the 0.7.10 version, maybe it will work fine for you. But the window yet is only minimized, not hidden. Maybe I should hide it if the libappindicator could be loaded.

**Comment by EmptyStackExn** [comment]
@auchri @telegramdesktop Thank you ! That works great for me. Maybe you should add the option `-h` in order to list and gather all possible options for new users who would not be aware this feature :+1:

**Comment by anavarre** [comment]
Good idea. `-h` or `--help` sounds excellent.

**Comment by lucidfox** [comment]
Doesn't work for me (Ubuntu 14.10, GNOME 3.12). With -startintray, the main window is still shown, but fails to properly draw its contents and is filled with garbage.

**Comment by nplezka** [comment]
+1 and I have same @lucidfox issue (Ubuntu 14.04, Gnome 3.12)

**Comment by dkessel** [comment]
"Telegram -startintray" works for me in Xubuntu 15.04 . The application gets started and only the indicator is shown, no hidden window.

**Comment by brunoJeeAo** [comment]
With my Ubuntu 14.04 (Unity) I've a 'strange' behavior: Telegram starts with the option "-startintray", but I have to click sometimes on the tray icon to see my chats. First time I've to click on 'Open Telegram', after 'Minimize to tray' and then 'Open Telegram' again!

**Comment by Altair2015** [comment]
2015-03-03 15:30 GMT+07:00 brunoJeeAo <notifications@github.com>:

**Comment by sojusnik** [comment]
See here: https://github.com/telegramdesktop/tdesktop/issues/512

**Comment by shadowlmd** [comment]
Option -startintray doesn't work as expected. When Telegram started with this option in Ubuntu 15.04, I can't open Telegram windows at all. No matter how many times I click tray icon and select "Open Telegram", nothing happens. I have to close Telegram and start it again regular way.

PS: I tried https://github.com/telegramdesktop/tdesktop/issues/407#issuecomment-76905488, it works for me too. Indeed, a sequence of "Open Telegram --> Minimize to tray --> Open Telegram" shows the window finally. I hope you can fix this strange behavior.

**Comment by Kryten2k35** [comment]
I get the same as @brunoJeeAo 's comment. That's better than it starting up on the screen though

**Comment by mbnoimi** [comment]
@telegramdesktop Thanks for the hint.

I wonder why you don't want to add this option in Telegram settings GUI?

**Comment by PlusMinus0** [comment]
Appears to be working in cinnamon.

Just my to cents: The command should be either
-t
--startintray

also, as somebody mentioned: -h and/or --help should not start the program but show available command line options.

**Comment by brunoJeeAo** [comment]
PlusMinus0 the '--startintray' and '-t' options are incorrect, Telegram starts opened however (i.e. same thing if you type '--goofy'.)

**Comment by PlusMinus0** [comment]
I know that they are incorrect, hence "should be". The emphasis is on the number of dashes. A single dash for a single character, two dashes for a longer parameter.

https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html

**Comment by r10s** [comment]
Exactly I was looking for. Thank you very much.
![stayintray](https://cloud.githubusercontent.com/assets/9800740/16338971/4b25476a-3a20-11e6-9234-9e2b529fba72.png)

**Comment by Varentsov** [comment]
It's still buggy https://github.com/telegramdesktop/tdesktop/issues/422

**Comment by garridev** [comment]
still happens...

**Comment by orschiro** [comment]
I can confirm that `-startintray` still opens the window on Ubuntu 16.10.

**Comment by iggbodiam** [comment]
@lucidfox  I found this issue to that -startintray works on QT desktop and not GTK+ desktops, I reproduced the issue on Gnome 3. this is because it doesn't have a tray.  does it make sense? or should telegram minimize on -startintray?

**Comment by Danieliko** [comment]
It's not working for me. Gnome 3.

**Comment by daboross** [comment]
It's working for me in a Gnome 3 session - but using `lightdm` not `gdm` (don't have `gdm` installed so haven't tested).

**Comment by mshkrebtan** [comment]
Works fine on my Debian 9 machine.
I have Gnome 3.22.2, with GDM and Topicons shell extension.

I just copied Telegram's `.desktop` file to `~/.config/autostart`:
```
[Desktop Entry]
Version=1.0
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/opt/Telegram/Telegram
Exec=/opt/Telegram/Telegram -startintray -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
X-Desktop-File-Install-Version=0.23
```
