### ISSUE TITLE
Random newlines in sent messages

### ISSUE THREAD

**Issue by expectocode** [telegramdesktop/tdesktop#4071]
### Steps to reproduce
1. Send some messages on TDesktop, see if newlines are inserted in the view
2. Restart tdesktop - the messages which previously showed up with newlines now show up normally
3. Step 1 still continues

### Expected behaviour
The message should appear on my screen without any newlines (the way other people see them)

### Actual behaviour
Newlines are inserted seemingly randomly

### Configuration
Fedora 26, updated today, 64 bit

**Version of Telegram Desktop:**
1.1.23 alpha

**Used theme**:
Ion

screenshots:
https://imgur.com/a/Vf0dQ

**Comment by expectocode** [comment]
note: the randomness is in which messages get the newlines added. In these messages, each word will always be on a new line

**Comment by xvitaly** [comment]
@expectocode This is not a Telegram upstream bug. This is a known build issue. Maintainer of `qt5-qtbase` package in Fedora updated Qt from 5.7.1 to 5.9.2 in **stable** release of Fedora. I need to rebuild Telegram Desktop against Qt 5.9.2. I will do this today for RPMFusion. Just wait.

**Comment by xvitaly** [comment]
@expectocode Rebuilding package for Fedora 26 was completed successfully. You can get it from [Koji](http://koji.rpmfusion.org/koji/buildinfo?buildID=5640) now or wait until it will be pushed to repositories.

**Comment by expectocode** [comment]
Thanks!
