### ISSUE TITLE
Ability to forward message while replying to a message

### ISSUE THREAD

**Issue by Azahe** [telegramdesktop/tdesktop#4073]
(It is a feature idea so I deleted bug template)

As a telegram user I often forward messages from my friends that have "meme" status in our group chat and fit perfectly in a context of discussion - when I want to respond to a certain message (from a while ago) it is most convinient to use "reply" option - I also want to use our legendary memes in form of forwarded message. Currently I can not fulfill my desires and I feel like there is a part of my life that is missing.

Love you guys, thx

**Comment by SmartManoj** [comment]
Preserve reply to

**Comment by SmartManoj** [comment]
error

**Comment by SmartManoj** [comment]
api issue?
