### ISSUE TITLE
Breaklines replace white spaces on some? messages

### ISSUE THREAD

**Issue by davidgfnet** [telegramdesktop/tdesktop#4076]
### Steps to reproduce
1. Send some messages
2. Some of them will be presented (either inmediately after sending them or after some seconds) as a list of words and breaklines (so all words will be in the same message box but each in a newline). Something line s/ /\n/
3. Close telegram and open it again to find the problem gone. Sometimes old messages will start showing this symptom at random too. Only happens in this client after I updated it from the fedora repos.

**Comment by stek29** [comment]
Are you using official build?
If not, is that build using shared Qt?
What is shared Qt version?
Aren't you on Fedora?
Isn't this #4071 duplicate? :)

(please, use template next time there's no need to ask questions like these)

**Comment by xvitaly** [comment]
@davidgfnet Fedora 26 user? Fetch latest build from [Koji](http://koji.rpmfusion.org/koji/buildinfo?buildID=5640) or just wait until it will be pushed to stable repositories.

**Comment by davidgfnet** [comment]
Yup fixed in y-day's release! Thanks!
