### ISSUE TITLE
When you connect a bluetooth headset to the system, the telegram is crashed.

### ISSUE THREAD

**Issue by dim1triy** [telegramdesktop/tdesktop#4078]
### Steps to reproduce
1. The application at this time is minimized.
2.  Connect bluetooth handset to PC.
3. the telegram is crashed.

### Expected behaviour
Work app :)

### Actual behaviour
Crashed app :(

### Configuration
**Operating system:** Fedora 26-27, Cinnamon 3.6.3 

**Version of Telegram Desktop:** 1.1.23

**Used theme**: default

<details><summary><b>Logs</b>:</summary>
(Telegram:16186): Gdk-ERROR **: The program 'Telegram' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 12299 error_code 10 request_code 131 minor_code 46)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

</details>

**Comment by stek29** [comment]
#2478

**Comment by dim1triy** [comment]
The problem is after installing the connection with the Bluetooth headset
