### ISSUE TITLE
Command for exit chat

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#4083]
[Keyboard Shortcuts](https://github.com/telegramdesktop/tdesktop/wiki/Keyboard-Shortcuts)

Command for exit_chat
Command for search_Telegram without exiting chat
Is it possible to log commands for  actions in Telegram

**Comment by stek29** [comment]
Sorry, I didn't understand it. Try using template.
Also I feel like you have two unrelated requests in one issue, split them if I am correct.

**Comment by SmartManoj** [comment]
How to create custom shortcut for exiting the chat?
Currently it is the escape key

**Comment by SmartManoj** [comment]
```
#ifwinactive, Telegram

+^a::
Send {Esc}
return
```
