### ISSUE TITLE
Name of the user visible when deleting a message (user is not on contact list)

### ISSUE THREAD

**Issue by anonymous42212** [telegramdesktop/tdesktop#4086]
When deleting a message within conversation (receiving user is not on contact list) - the name of the user is visible in deletion popup. I wasn't sure if it was intended feature or a bug, so I'm posting it (Note: the message I wanted to delete was sent by me).

### Steps to reproduce
1. Get message from user outside contact list
2. Send a message to the user
3. Right click on sent message -> delete Message

### Expected behaviour
There should be user number visible in the popup.
### Actual behaviour
There is the name of the user visible in the popup.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.1.23
**Used theme**:
default
<details><summary><b>Logs</b>:</summary>
No logs for this issue

</details>

### Screenshot
![delete image](https://user-images.githubusercontent.com/34031591/33270250-b0be6978-d383-11e7-887b-9ee767fdb4eb.png)

**Comment by Aokromes** [comment]
this is valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
