### ISSUE TITLE
Sticker sets for groups smaller than 100 members?

### ISSUE THREAD

**Issue by tucnak** [telegramdesktop/tdesktop#4087]
Hello,

I maintain framework for bots in Go, [telebot](https://telegram.org/blog#stickers-of-the-group). Telegram Messenger team doesn't seem to have any sort of dev contacts publicly available, so I chose to write here instead. If you consider this issue a noise, please accept my deepest condolences.

[According](https://telegram.org/blog#stickers-of-the-group) to Telegram Blog, only groups with 100+ users can set sticker packs of their own. My group is of about 40 people and we got a sticker pack with our own faces and memes, which I'd happily put in place, but I can't, since the threshold is 100 users no less.

Can you open on reasoning behind this exact (100) threshold for `setChatStickerSet`?

Cheers,
Ian

**Comment by stek29** [comment]
Sorry, but this has nothing to do with Telegram Desktop since it's server side limitation.
Use "Ask a question" button in settings, or request it on Twitter.
