### ISSUE TITLE
Key inputs (Caps Lock) are disturbed while playing audio in TDesktop

### ISSUE THREAD

**Issue by jaekyeom** [telegramdesktop/tdesktop#4088]
### Steps to reproduce
1. [Enable "Use Caps Lock to switch to and from" option in macOS system preferences](https://support.apple.com/kb/PH25311?locale=en_US).
2. Play a sound file (audio) in Telegram Desktop.
3. Switch to other apps and try pressing Caps Lock to change the input source.

### Expected behaviour
Input source switch must happen every time I press Caps Lock (shortly, without holding it which will make it behave like Caps Lock without the option).

### Actual behaviour
Pressing Caps Lock **almost** always fails to make a switch to the other input source, in the other apps. It works fine in Telegram Desktop.
My speculation is that Telegram Desktop enables some sort of event hooking when it starts playing a sound file, and it makes a delay.

### Configuration
**Operating system:**
macOS Sierra 10.12.6

**Version of Telegram Desktop:**
1.1.23

**Used theme**:
Ubuntu Light (but I honestly think it doesn't matter)

**Comment by jaekyeom** [comment]
Plus, although this might have to be filed as a new issue, Telegram Desktop crashed many times at the moments I pressed Caps Lock while playing audio in it.

**Comment by jaekyeom** [comment]
It looks like Sierra's fault: https://community.spotify.com/t5/Desktop-Mac-old/Switching-between-quot-input-sources-quot-with-using-quot-Caps/m-p/1452332#M11702

**Comment by auchri** [comment]
Thanks, I'll close this issue.

**Comment by jaekyeom** [comment]
@auchri With the latest version of tdesktop, I have this issue even when there is no media playing.
I know the problem is macOS, but could you at least give us an option to disable macOS media keys?
