### ISSUE TITLE
Emoji Sidebar disappear after click "X"

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#4089]
### Steps to reproduce
1. Have the emoji sidebar open at right
2. Open a group info on top (it'll go to a new right sidebar)
3. Press X (upper right)

### Expected behaviour
Emoji panel should be displayed

### Actual behaviour
Emoji panel disappears

### Configuration
**Operating system:** Win 10

**Version of Telegram Desktop:** 1.1.24 alpha

**Used theme**: Default

**Comment by D3sl0nG3r** [comment]
Vice versa happens too: #4090

**Comment by LittleJellycat** [comment]
Same in 1.2 version. (Also Win10+default theme)

**Comment by john-preston** [comment]
@LittleJellycat Currently this is expected behavior :( this could be changed in the future.

**Comment by LittleJellycat** [comment]
@john-preston That's annoying. :(
My display is wide and the emoji/stickers panel is permanently open. Hope for the 'pin stickers sidebar' option in the future releases then (or something like this).

**Comment by ArmeF97** [comment]
We can close this becouse now the group info panel is something floating in the center of the screen 👍 so the problem is fixed
