### ISSUE TITLE
Window size is decreased after closing the right panel

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#4091]
### Steps to reproduce
1. Open a group info by clicking on top panel (a group name or an empty space). See gif below
2. Right side panel have opened and window width remains the same
3. Close the right panel

### Expected behaviour
Window width should remain the same

### Actual behaviour
Window width is decreased

![tg](https://user-images.githubusercontent.com/1321838/33401755-159d1246-d563-11e7-967b-459096cc5770.gif)

### Configuration
**Operating system:** Win 7 / Arch Linux

**Version of Telegram Desktop:** 1.1.24 alpha

**Used theme**: Any

**Comment by khorrth** [comment]
The same problem here. Also, please, take atention to the icon. It gets dark on dark background sometimes.

**Comment by xvitaly** [comment]
I think we need a feature to completely disable this annoying panel.

**Comment by john-preston** [comment]
@aNNiMON In this GIF the first closing is correct (the column was showed with the window being expanded and then was hidden with the window being shrinked), but the second one is a bug (the column was shown "inside" the window, without chaning window size, so it should be hidden the same way).

**Comment by john-preston** [comment]
@khorrth This depends on the color theme used. But perhaps I'll change the used key from the active buttons background to active text foreground (so that those icons would have the color of clickable links by default).
