### ISSUE TITLE
Can't jump to date before supergroup conversion

### ISSUE THREAD

**Issue by ariel-** [telegramdesktop/tdesktop#4094]
### Steps to reproduce
1. Have a group which was converted to a supergroup
2. Use the search then jump to a date before the date of conversion
3. You get stuck on that date, even though there are previous messages

### Expected behaviour
Should let me jump to previous dates

### Actual behaviour
You get stuck on conversion date and jump to calendar becomes greyed out, even though messages can be searched for and scrolled before that date.

### Configuration
**Operating system:** Windows 10 64-bit

**Version of Telegram Desktop:** 1.1.23 stable

**Used theme**: Dark Accent Red v2

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@ariel- those are completely separate message histories (normal group and supergroup) - they're just displayed one after another in the UI. Currently calendar works only for the currently shown chat, without that glueing of that histories together :( But this could be done in the future..
