### ISSUE TITLE
Bold formatting no longer works in 1.1.24

### ISSUE THREAD

**Issue by Perlence** [telegramdesktop/tdesktop#4095]
### Steps to reproduce
1. Send a message with bold formatting, e.g. `**beep**`.

### Expected behaviour
Text `beep` must be bold.

### Actual behaviour
Text `beep` has no formatting. Actually, there's no bold formatting in any of the previously sent messages, not only in the ones sent by Telegram Desktop 1.1.24.

### Configuration
**Operating system**: Debian Stretch

**Version of Telegram Desktop**: 1.1.24

**Used theme**: Default

**Comment by MasterGroosha** [comment]
Hmm...maybe it's an OS-specific issue. Works fine for me on Windows.

**Comment by auchri** [comment]
@Perlence does it work with 1.1.23?

**Comment by Perlence** [comment]
@auchri Yep, it does.

**Comment by nshopik** [comment]
Seems to be working on 1.1.24 for me on xubuntu

**Comment by xvitaly** [comment]
Works for me on Fedora 27, tdesktop 1.1.24.

**Comment by Perlence** [comment]
I'm not making this up 😄
![telegram-bold](https://user-images.githubusercontent.com/1044300/33436341-cde049d0-d5f5-11e7-8c9b-873d73a0663e.png)

**Comment by gudvinr** [comment]
Broken on Ubuntu 16.04

**Comment by auchri** [comment]
@gudvinr But works on ubuntu 17.10 🤷🏼‍♂

**Comment by omkarnathsingh** [comment]
Working on 17.10 for me.

**Comment by Perlence** [comment]
Works for me on Debian Jessie with GNOME. It's not clear, what's really happening.

**Comment by Perlence** [comment]
So I removed Open Sans font that I had in `~/.local/share/fonts` and regenerated the font cache with `fc-cache -fv`, now the issue is gone!

@gudvinr See if it helps you.

**Comment by Aokromes** [comment]
#2128 ?

**Comment by yaeuge** [comment]
Same issue on Arch Linux, Telegram ver. 1.3.9 (standalone binaries taken from official site)

**Comment by MasterGroosha** [comment]
Don't see bold on Elementary OS 5.0 Juno, TDesktop 1.5.6 beta.

**Comment by DanyGee** [comment]
No bold on elementary OS Juno and Telegram 1.5.7 beta. :cry:

**Comment by DanyGee** [comment]
Starting Telegram with this parameter...
```
exec env FONTCONFIG_FILE=/etc/fonts/ /path/to/your/telegram/app -- %u
```
...fixes bold text in the App...
![screenshot from 2019-01-18 11 36 00 2x](https://user-images.githubusercontent.com/26818551/51381747-45c03b80-1b15-11e9-8656-c5e0cae6b813.png)
...but brakes dialog boxes fonts (adding an attachment in this example)...
![screenshot from 2019-01-18 11 30 09 2x](https://user-images.githubusercontent.com/26818551/51381452-78b5ff80-1b14-11e9-9fd4-a6e018b5b50f.png)
Any idea how to fix the fix? :smile:

**Comment by Dmitrij-Polyanin** [comment]
For me on Kubuntu this fixed with `sudo apt remove fonts-open-sans`.
But this is not a solution. Because other programs need this font.
But I think this info may help find normal solution.

**Comment by rastersoft** [comment]
In debian SID also fails.

**Comment by marcogiannini** [comment]
the bug is still present on elementary OS 5.0 Juno

**Comment by Aokromes** [comment]
#2128

**Comment by NabiKAZ** [comment]
After 4 years:
Telegram Desktop 1.9.3
![rY9hKKuO5o](https://user-images.githubusercontent.com/246721/72153250-9c77f280-33c2-11ea-8aac-655c2dc7d36d.gif)

**Comment by NabiKAZ** [comment]
After 4 years:
Telegram Desktop 1.9.3
![rY9hKKuO5o](https://user-images.githubusercontent.com/246721/72153574-9cc4bd80-33c3-11ea-92ba-c9aaf2ecc2e5.gif)

**Comment by m7mdyahia** [comment]
Still have the same problem with arabic v1.8.21 windows 10
