### ISSUE TITLE
Bold formatting does not work for Korean and Chinese

### ISSUE THREAD

**Issue by boghison** [telegramdesktop/tdesktop#4097]
### Steps to reproduce
1. Enter `**가** / 가` and compare
2. Enter `**中** / 中` and compare

### Expected behaviour
The characters should be bold, like for Latin (incl. extended) and Cyrillic

### Actual behaviour
There is no difference between bold formatting and no formatting

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 1.1.23

**Used theme**: Default

**Comment by auchri** [comment]
Duplicate #1917
