### ISSUE TITLE
[1.1.24] t.me/share links not working 

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#4099]
### Steps to reproduce
1. Create t.me/share link, for example, https://t.me/share/url?url=https%3A//telegram.org
2. Send yourself such link and click on it
3. Try to "Select chat" as prompted

### Expected behaviour
After selecting chat, a link should be pasted into text field to be sent later.

### Actual behaviour
"Sorry, no way to share here" error

### Configuration
**Operating system:** Windows 10 LTSB x64
**Version of Telegram Desktop:** 1.1.24 alpha

**Comment by john-preston** [comment]
@MasterGroosha wow, thanks.
