### ISSUE TITLE
[Feature Request] Translation in German

### ISSUE THREAD

**Issue by TheAppService** [telegramdesktop/tdesktop#41]
Hello,

I'd like to translate your program in German. It would be cool, if I could do this. You should only say to me how I can do this or create a project on a translation site. 
Thanks for an answer

Daniel

**Comment by telegramdesktop** [comment]
In my opinion translation is more solid when it is done by one person, not by many different translators. So the less people work on the translation (when the result quality is good) the better.

**Comment by SafaAlfulaij** [comment]
You are absolutely right, At least in the small projects.
A quick simple question, Why didn't you use the Qt's TS standard format rather than implementing a custom method? All languages can be added without big problems (like plural).
