### ISSUE TITLE
[Feature Request] Copy channel name

### ISSUE THREAD

**Issue by virtualdj** [telegramdesktop/tdesktop#4102]
Some channels do not report their link (e.g. t.me/xxxx URL) in the **Show channel info** page.
Is it possible to add a **Copy link** feature in the channel popup menu to be able to share the channel with friends?

At the moment the workaround is to forward a message of the channel so that it can be clicked, but IMHO it would be useful (even in the Android app actually) to have the URL directly too, if possible.

**Comment by john-preston** [comment]
@virtualdj If the channel isn't public it doesn't have any direct link afaik.

**Comment by virtualdj** [comment]
@john-preston Thanks. But how does the app link to the original channel when clicking for example on an auto-forwarded message, then?

**Comment by auchri** [comment]
@virtualdj With the channel id? xD
