### ISSUE TITLE
No acces to (generate) invite link on normal group

### ISSUE THREAD

**Issue by rizaumami** [telegramdesktop/tdesktop#4104]
### Steps to reproduce
1. Click on new three dots button at the right end of group's title
2. Click **View group info** on the drop down menu
3. Click three dots button on the **Group info** window

### Expected behaviour
After clicking three dots button in **Group Info** of normal group, there is should be **Manage Group** option in its drop down menu.

### Actual behaviour
**Manage Group** option only exist in supergroup's **Group Info**. As for now, there is no way to see or generate invite link on normal groups.

### Configuration
**Operating system:**
Debian Sid

**Version of Telegram Desktop:**
1.1.25 alpha

**Used theme**:
Telegram: Defautl theme
Debian: Adwaita Dark

**Comment by auchri** [comment]
@rizaumami Normal groups don't have an invitation link.

**Comment by rizaumami** [comment]
@auchri 
Normal group does have an invitation link. Perhaps, you've confused it with public username.
People can join a normal group by invitation link, which only the creator of the group can generate it.

**Comment by john-preston** [comment]
@rizaumami Yes, this is a downgrade in the new profile page implementation. Thanks.

**Comment by rizaumami** [comment]
Fixed on v1.1.26 alpha
