### ISSUE TITLE
[Feature Request] Option to disable automatic media download from specific groups

### ISSUE THREAD

**Issue by Mr-Rixa** [telegramdesktop/tdesktop#4106]
### Steps to reproduce
__1. Open telegram__
__2. Open group and it's options__
~~3. Toggle off all/some media auto download~~

### Expected behaviour
Telegram wouldn't auto download media from group.

### Actual behaviour
Option does not exist so Telegram uses global media download setting.

### Reasoning
I have couple of groups that has some NSFW images posted and I'd rather not have those on my phone gallery, but I'd like to have media download enabled on my family group for example.

### Configuration
**Operating system:** Windows/Android

**Version of Telegram:** 1.1.25a [Win10] / 4.5.1(1144) arm-v7a [android]

**Used theme**: None

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by auchri** [comment]
Well, first of all this repo is only for **Telegram Desktop**.

![image](https://user-images.githubusercontent.com/5092164/33517050-199f07a2-d77d-11e7-9c3f-365f83d76869.png)

Second, if your requested feature is not existing in both the Android app and in Telegram _Desktop_ there is a high chance that it is not supported by the [Telegram API](https://core.telegram.org/#telegram-api). You can request new features for the API on [Twitter](https://twitter.com/telegram) or using the "Ask a question"-Feature in one of the official apps.

**Comment by Mr-Rixa** [comment]
##### Sorry! 😣 and thanks. Tweeted them!
