### ISSUE TITLE
Only default wallpaper changes when activating Night mode

### ISSUE THREAD

**Issue by DarthJahus** [telegramdesktop/tdesktop#4107]
### Steps to reproduce
1. Set default flowers wallpaper, activate Night Mode, wallpaper changes accordingly
2. Select another wallpaper from the gallery, activate Night Mode, wallpaper doesn't change

### Expected behaviour
Maybe a toggle to define either to keep the user wallpaper when switching modes or use the default dark wallpaper.

### Actual behaviour
The wallpaper changes only if the user has used the default flowers wallpaper. That's a really nice feature, but it may be better if it could be used with others as well.

**Comment by auchri** [comment]
See #3598
