### ISSUE TITLE
Wrong cache size

### ISSUE THREAD

**Issue by AliMirlou** [telegramdesktop/tdesktop#4110]
It's been a long time since I haven't cleared my cache and today when I checked local storage in settings, I found this:

![bug](https://user-images.githubusercontent.com/19661419/33526330-c519b668-d854-11e7-85da-eef70fcfc56c.png)

Real cache size was 4.50 GB.
I have telegram desktop version 1.1.23 on Windows 10 v1709 build 16299.19
Not remembering which theme i am using :)

**Comment by john-preston** [comment]
@AliMirlou Yeah, thanks. I'll fix that, but something should be done with such cache sizes :/

**Comment by AliMirlou** [comment]
@john-preston With this change, i don't think anyone would have problems with the cache size for a long time :)
But the cache size should not actually be a problem as long as there is disk space, right?

**Comment by MasterGroosha** [comment]
Suggestion:
Maybe a window might be shown with text "Your cache size is more than X. You can always clear your local cache using (menu name). All messages and media are stored in Telegram Cloud so you will not lose them"
Ideally there should be buttons "Clear cache now" and "Cancel" with checkbox "Don't show this warning next time"

In Windows/Linux it's harder to quickly look at "disk usage per app", IMO, so this feature will be very nice.

**Comment by john-preston** [comment]
@MasterGroosha Maybe. Ideally it should have a max size, defaulted to something like 1GB, and clear everything older automatically.

**Comment by MasterGroosha** [comment]
Just like Android/iOS apps, yes. ("Keep media for")
