### ISSUE TITLE
Music files disappear from shared files when we open the list

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#4113]
### Steps to reproduce
1. join a channel where shared **files** are only `mp3` files (or music files that Telegram Desktop can play with the built-in music player) (eg. [this channel](https://t.me/joinchat/AAAAAEKNMzrPdFDIyPnWPw))
2. open shared files

### Expected behaviour
Nothing weird happens and you can see the list of shared files

### Actual behaviour
Shared files disappear with their "shared files" voice in the channel info screen, until you quit and re-open the app.

Here's a video of what is happening: [video](https://my.mixtape.moe/wioimq.mp4)

Also, once you've done this, every song you try to play (actual **music** that appears in the shared songs, not files) doesn't have the next/previous buttons ([screenshot](https://i.imgur.com/6yXrxxQ.jpg)). As far as I know, the player bar doesn't show these buttons only when we're playing music files that are not seen as songs, but as files

I have more channels where this happens, if needed
***
Anyway:
> join a channel where shared **files** are only `mp3` files

I assumed this problem happens just with these conditions because in chats with different types of files, this doesn't happen
***
**Edit:** just tried to share a non-music file in the channel: [video](https://my.mixtape.moe/kyunkn.mp4). Telegram Desktop ignores all the music files as soon as I open the shared files list

**Edit 2**: [this](https://i.imgur.com/Uw6IXL0.jpg) is what I see (shared files of that channel) from the Android client, latest playstore version
### Configuration
**Operating system:** Windows 7/10

**Version of Telegram Desktop:** alpha 1.1.26 portable

**Used theme**: default night theme

**Comment by john-preston** [comment]
https://github.com/telegramdesktop/tdesktop/commit/951db83ab613d4b10e8856781926e7484b7cfacd this one fixes this issue, not #4120, I've mistyped the number in the commit message.

**Comment by RememberTheAir** [comment]
@john-preston works, thanks!
