### ISSUE TITLE
[Feature request] Have emoji shortcodes as a separate option

### ISSUE THREAD

**Issue by ifarbod** [telegramdesktop/tdesktop#4114]
I'd personally like to have emoji shortcodes (e.g. `:tm:` and so on) as a separate option instead of the current "Replace Emoji".
While it enables the new shortcodes feature, It will also enable the old replacements in the older versions (I don't want `<3` being replaced to ❤️  for example). Is it possible to split both of these behaviors into separate options? Something like `Enable emoji shortcodes` and `Replace emoji`, So like, Being able to either enable both of them, one of them, or neither.

**Comment by RememberTheAir** [comment]
Duplicate of #3738

**Comment by ifarbod** [comment]
Right, I guess I'm gonna close it then.
