### ISSUE TITLE
[FR] Tray menu doesn't appear on right click with KDE4

### ISSUE THREAD

**Issue by EliaGeretto** [telegramdesktop/tdesktop#412]
Hi,

I'm using Arch Linux with KDE4. I have libappindicator installed but, when I left-click on the tray icon, the tray menu doesn't appear. Moreover, if I try to right-click on the tray icon nothing happens, i.e. the main window doesn't appear. By the way, the message counter works correctly.

P.S. I installed libappindicator as a dependency for grive-tools.

**Comment by mxa** [comment]
Works on cinnamon.

**Comment by EliaGeretto** [comment]
With libappindicator installed? Probably it's related to KDE4. I hope the compatibility will be fixed in the next release ;-) I'll change the title.

**Comment by mxa** [comment]
yes, libappindicator was there.

**Comment by EliaGeretto** [comment]
I've marked it as "Feature Request" because I know KDE4 isn't currently supported.

**Comment by soee** [comment]
I think it should also support Plasma 5. Kubuntu 15.04 will use Plasma 5 by default so a working systray with Telegram would be nice move.

**Comment by boris-il-forte** [comment]
Same problem in debian with libappindicator-dev installed.

**Comment by boris-il-forte** [comment]
solved in 7.8

**Comment by EliaGeretto** [comment]
As soon as the package in AUR is updated, I'll check if 7.8 solves the issue.

**Comment by ScorpionIT** [comment]
@EliaGeretto https://aur.archlinux.org/packages/libappindicator-gtk3/

**Comment by EliaGeretto** [comment]
I was referring to the "telegram-bin" package, which is still on 7.7. I have already installed the "libappindicator-gtk3" package.

**Comment by EliaGeretto** [comment]
With 7.8 the icon reacts correctly on right-click: the tray menu pops up. There is still the problem that, on left-click, the main window doesn't appear. Anyway, the feature requested was added so I'll close the report.

**Comment by telegramdesktop** [comment]
From version 0.7.16 tray icons should work through libappindicator in Unity environments and through Qt implementation otherwise (with show/hide of window by left click or other "activate" event). Please check.

**Comment by boris-il-forte** [comment]
Working perfectly on debian Jessie, with KDE
