### ISSUE TITLE
Unable to play flac files

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#4120]
### Steps to reproduce
1. Upload or find `.flac` audio file
2. Press play button

### Expected behaviour
Audio is playing

### Actual behaviour
Audio is not playing

### Configuration
**Operating system:** Linux Mint 18.3, Windows 7, Arch Linux

**Version of Telegram Desktop:** 1.1.26 alpha, 1.1.27 alpha. With 1.1.23 stable everything fine.

**Used theme**: Any

**Comment by john-preston** [comment]
@aNNiMON Can you please send me an audio file, that plays in the stable version, but doesn't play in the alpha version, to https://t.me/preston? Thanks!
