### ISSUE TITLE
[feature request] Accept "@" as search input in global search

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#4121]
### Steps to reproduce
1. type "`@`" in the chat lists search box

### "Expected" behaviour
This is not actually the expected behaviour, but it's more something I other clients support and I would love to see on desktop too. If we globally search for "@"  from other clients, the list of replies to my messages is returned. Telegram desktop doesn't allow to search for single characters unless they are digits or latin letters, so no search is performed and no result is displayed, while it would be possible to retrieve this list.

It's already possible to search globally your mentions by typing "`#m`", and it would be really cool to have the @ "hidden keyword" available too - I really love how it works and it would be a perfect addition to the already implemented mentions/badge system. Also this already works in the in-chat search:
- `#m` returns a list of mentions
- `@` returns a list of replies

[This](https://t.me/tgbeta/2332) is a list of all the official clients that already let us use this magic keywords, just for reference. I understand they do not support this trick by choice, but just because the API returns this result and because the client accepts the "@" as search query

### Actual behaviour
Telegram Desktop doesn't accept "@" as valid global search query (I suppose, since when I type "@" nothing happens)

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.1.27

**Used theme**: default

**Comment by john-preston** [comment]
@RememberTheAir I'll allow searching by '@', but really the server side search for '@' is absolutely the same as for '#m'. But you can search for your mentions if you type the whole '@yourusername' query.

**Comment by RememberTheAir** [comment]
@john-preston awesome, thanks!

I've always used the "search your username" trick, the problem is when you don't have an username and people mention you with weird names, or you changed username. This "@" is very handy, thanks :)

**Comment by RememberTheAir** [comment]
I just figured out that, besides webogram, all the clients return the same result (list of replies) when we input `#m` or `@`, while I thought that searching for `@` would have returned a list of mentions. So this request was pretty pointless

Thanks anyway :)
