### ISSUE TITLE
Redundant chat actions in Saved Messages

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#4122]
### Steps to reproduce
1. Open "Saved Messages" (former "Chat with yourself")
2. Start typing message

### Expected behaviour
No chat action should appear/present. It's simply useless.

### Actual behaviour
"typing..." appears while typing text message.

### Configuration
**Operating system:** Any
**Version of Telegram Desktop:** 1.1.37 alpha

**Comment by john-preston** [comment]
@MasterGroosha Yes, indeed. Thanks.
