### ISSUE TITLE
Unable to run Tg in many workdir mode!

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#4123]
### Steps to reproduce
1. Updated Tg to 1.1.27
2. Run ``./Telegram -many -workdir /home/hanid/.TelegramDesktopSIM2``

### Expected behaviour
Run 2nd profile of Tg

### Actual behaviour
Current version no longer accepts `` -many -workdir`` arguments

### Configuration
**Operating system:** Linux Mint 18.2 x64 xfce

**Version of Telegram Desktop:** 1.1.27

**Used theme**: Night mode

<details><summary><b>Logs</b>:</summary>
Unable to find the log because I'm unable to launch Tg with `` -many -workdir`` arguments

</details>

**Comment by john-preston** [comment]
@mbnoimi This is not a good way, of course, it will fail on autoupdate and maybe some other things. But well, perhaps work through the command line argument can be returned.

**Comment by mbnoimi** [comment]
> This is not a good way, of course, it will fail on autoupdate and maybe some other things. But well, perhaps work through the command line argument can be returned.

It's not a problem because I enabled "Auto Update" in the main workdir while the others disabled

In summary, How can I run multi workdirs?

**Comment by john-preston** [comment]
@mbnoimi No way right now. I will return the way through the command line argument in the next version.

**Comment by mbnoimi** [comment]
> No way right now. I will return the way through the command line argument in the next version.

Oops, I've to revert back to the old version.

Thanks

**Comment by mbnoimi** [comment]
BTW, Where I can find the old version binaries?

**Comment by john-preston** [comment]
@mbnoimi All binaries are available on https://github.com/telegramdesktop/tdesktop/releases page.

**Comment by mbnoimi** [comment]
``-many -workdir`` is a vital option for me because I've 3 phone numbers

**Comment by mbnoimi** [comment]
> All binaries are available on https://github.com/telegramdesktop/tdesktop/releases page.

OMG, Silly me

**Comment by stek29** [comment]
Let's keep it open until regression is fixed :)

**Comment by mbnoimi** [comment]
I downgrade Tg to 1.1.26 it works fine now

**Comment by mbnoimi** [comment]
> This is not a good way, of course, it will fail on autoupdate and maybe some other things. But well, perhaps work through the command line argument can be returned.

BTW, you can set "auto update" to disable for any instance run as ``-many -workdir`` (as I toled you before I do that manually)
