### ISSUE TITLE
Could not start Telegram Desktop error after rebooting Windows. Win7 64x Home Basic

### ISSUE THREAD

**Issue by zemix** [telegramdesktop/tdesktop#4125]
What should I do to resolve this problem? What should I (or you?) fix/change so that the Telegram for Windows normally starts after the reboot?

### Steps to reproduce
1. Download and Install TG for Windows from https://desktop.telegram.org/
2. Set two check-boxes "Auto start TG at System Start", screen https://i.imgur.com/RLxPWWH.png
3. When Windows is start and load - always get an error "Could not start Telegram Desktop...", screen https://i.imgur.com/lyDW1DS.png
Deleting Telegram - Reboot - again Install = doesn't resolve the problem...
Manual start from shortcut on desktop - everything is works fine. Only automatically start after rebooting Windows - not work. 

### Expected behaviour
should automatically start TG Desktop after rebooting Windows

### Actual behaviour
TG do not automatically start after rebooting Windows and I get an error message window with log

### Configuration
**Operating system:**
UserName = ZEM, ComputerName = ZEMPC, OS = Windows 7 64-bit Service Pack 1 (version - SP1 6.1.7601.23915, platform - 2, service pack - 1.0)
Hardware:
CPU Vendor = GenuineIntel
CPU Identifier = Intel64 Family 6 Model 42 Stepping 7
CPU Name = Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
Number of logical CPU cores = 4
RAM = 6000 Mb

**Version of Telegram Desktop:**
v 1.1.23

**Used theme**:
Night default theme

<details><summary><b>Logs</b>:</summary>
Screenshot of Log https://i.imgur.com/lyDW1DS.png

> [2017.12.07 23:28:59] Launched version: 1001023, alpha: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
> [2017.12.07 23:28:59] Executable dir: C:/Users/ZEM/AppData/Roaming/Telegram Desktop/, name: Telegram.exe
> [2017.12.07 23:28:59] Initial working dir: C:/Windows/system32/
> [2017.12.07 23:28:59] Working dir: C:/Windows/system32/
> [2017.12.07 23:28:59] Command line: C:\Users\ZEM\AppData\Roaming\Telegram Desktop\Telegram.exe -autostart
> [2017.12.07 23:28:58] Executable path before check: C:/Users/ZEM/AppData/Roaming/Telegram Desktop/Telegram.exe
> [2017.12.07 23:28:59] Logs started
> [2017.12.07 23:28:59] Connecting local socket to Global\8d43fc65f7f40937db56d5abc193c375-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
> [2017.12.07 23:28:59] This is the only instance of Telegram, starting server and app...
> [2017.12.07 23:29:00] Could not delete 'C:/Windows/system32/log.txt' file to start new logging!
> [2017.12.07 23:28:58] Executable path before check: C:/Users/ZEM/AppData/Roaming/Telegram Desktop/Telegram.exe
> [2017.12.07 23:29:00] FATAL: Could not move logging to 'C:/Windows/system32/log.txt'!

**DebugLogs** from C:\Users\ZEM\AppData\Roaming\Telegram Desktop\DebugLogs folder
log_23_45.txt = https://pastebin.com/raw/dQ6HkD6Q
mtp_23_45.txt = https://pastebin.com/raw/tTkrayC1
tcp_23_45.txt = https://pastebin.com/raw/mZt5eC0L

**Comment by zemix** [comment]
It's 100% Telegram for Windows some kind of bug. I think this is a problem that is something related to the record that Telegram creates at Startup.

Some programs (for example Punto Switcher) create something like this, screen [https://i.imgur.com/yiaBYON.png](url) in path C:\Users\ZEM\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup and Punto Switcher starts all time normally without problems when system boots.

But Telegram also create shortcut in this path! But after reboot Windows - shortcut always disappears!!! And only when you open TG manually - go to Settings - uncheck/check checkboxes again "Launch Telegram when system starts" - TG shortcut will appear again, until next Windows reboot!

old uTorrent 2.2.1 with autostart check-box auto-starts fine!
Punto Switcher auto-starts fine !
a lot of autostarts programs for Windows starts absolutely fine if you set them in their settings, never had problems.

Also after reboot - record about Telegram  auto-start always disappears if you look in "msconfig - tab Autostart". All other progs works fine and if set start when Windows boot - they starts.

**Comment by john-preston** [comment]
@zemix How is working dir in system32 😰

Please try the latest alpha version from https://desktop.telegram.org/changelog#alpha-version

**Comment by zemix** [comment]
I already tried alphpa - in terms of autorun when windows starts - all the same error log on start up
**"How is working dir in system32"** 
strange question, works fine and correct because 
1) the system is reinstalled just a few days ago, a license Home Basic on laptop Lenovo z580, with all the current Windows 7 64 updates from the "Windows Update Center" to this date.
2) all installed programs that start with windows - do it perfectly, without any issues like this https://i.imgur.com/mmXE61v.png
Why you can not take time-tested programs for Windows (ex Dropbox, Box, uTorrent, SKYPE a lot of others ), and implement AUTOSTART  as they do? Is it so difficult? Why Telegram desktop try to reinvent the wheel? Once again Telegram Desktop - its a pretty fine messenger desktop app, very fast, easy and intuitive, but **this is the only program for many years** that I've met, in which autorun does not work, nonsense!

**Comment by john-preston** [comment]
@zemix 1. Telegram Desktop used working directory as a directory for holding its data files. If some shortcut launches it with working directory set to "system32" it doesn't work — because it can't write files there.

2. In the alpha version I've stopped using current working directory for holding its data files there. You can see several issues about that change already.

3. I have no idea how Dropbox, Box, uTorrent, SKYPE a lot of others implement AUTOSTART. But I think the same way as Telegram Desktop. They just don't try to write to their working directory and alpha version does not as well.

4. Please post a screenshot of the error log you get when you try to autostart Telegram Desktop version 1.1.27 alpha, because it should work no matter what working directory is set in the shortcut.

**Comment by zemix** [comment]
@john-preston 
Omg! I am so sorry, looks like I tried to install previous alpha - _tsetup.1.1.25.alpha.exe (30/11/2017)_ - my BAD! 
So I uninstall stable 1.1.23 via default Windows Add/Remove Programs and reboot system
Install _tsetup.1.1.27.alpha.exe_
Set check-boxes "Launch TG when system starts" and "Launch minimized" https://i.imgur.com/LtLNIRU.png
Reboot system -and voila!) TG starts with other autostart programs normally! Try several times to make sure that it works okay! - Indeed, everything works perfectly in terms of "autostart when Windows boot" with this 27 latest alpha version!
For now, thanks a lot - for help and clarification, and for a quick support! Very grateful, and once again my apologize for concern! I hope this will be fixed in a stable version too :)
