### ISSUE TITLE
Translating Telegram

### ISSUE THREAD

**Issue by anfimovir** [telegramdesktop/tdesktop#4126]
Please add support Translating Telegram - https://translations.telegram.org/

P.S.

News in Blog:
https://telegram.org/blog/live-locations

**Comment by shamarin** [comment]
Support. On Android and iOS platforms allready new languages are available.

**Comment by shamarin** [comment]
Maybe to change title to Add new languages to Telegram?!

**Comment by anfimovir** [comment]
No, in this case need add support global new translation system, not only new languages, with auto sync.

**Comment by anfimovir** [comment]
@john-preston hmm, sorted in 1.2.6?

**Comment by john-preston** [comment]
@anfimovir The translations platform was added several months ago. When the guys approve and enable different languages is up to them.

**Comment by anfimovir** [comment]
Russian Language now available in Telegram Desktop.

**Comment by Lenglemetz** [comment]
Hi, 

Is it possible to add French language? :-)
