### ISSUE TITLE
OSX app store Telegram desktop app icon "broken"

### ISSUE THREAD

**Issue by tobsn** [telegramdesktop/tdesktop#4127]
### Steps to reproduce
update to latest on OSX via app store

seems like something went wrong and it shows the default app icon. (on mbp and imac for me)

![2017-12-08 at 1 47 am](https://user-images.githubusercontent.com/109529/33745907-dfe0507a-dbb9-11e7-866a-0845ead9a465.jpg)

edit: removing it from dock and adding it again with a restart in the middle fixed it after the update from a few hours ago which just showed up here. closing issue.

**Comment by stek29** [comment]
Partially fix iamroot, make icons disappear
_Just Apple Things <3_
