### ISSUE TITLE
1.1.27 alpha ignored working directory

### ISSUE THREAD

**Issue by sirati97** [telegramdesktop/tdesktop#4129]
### Steps to reproduce
1.  Start telegram with modified working directory

### Expected behaviour
telegram uses the specified working directory as it did in older versions

### Actual behaviour
telegram uses its application file's folder

### Configuration
**Operating system:**
Win10 FCU

**Version of Telegram Desktop:**
1.1.27 alpha

**Comment by john-preston** [comment]
@sirati97 This won't be supported, sorry. There were several issues here where working directory was something unreliable and it can't be used for the data files by default.

You may still specify working directory through "-workdir" command line argument. Why do you need data in some custom selected working directory?

**Comment by sirati97** [comment]
I have multiple telegram accounts running, but don't want to update them all separately. I will use the "-workdir" then. It's good to hear though that there is a solution.

**Comment by sirati97** [comment]
Okay I tried a couple command lines and none seem to work

"C:\Users\sirati97\AppData\Roaming\Telegram Desktop\Telegram.exe" -workdir "C:\Users\sirati97\AppData\Roaming\Telegram Desktop\sirati97\"

"C:\Users\sirati97\AppData\Roaming\Telegram Desktop\Telegram.exe" -workdir "C:\Users\sirati97\AppData\Roaming\Telegram Desktop\sirati97"

"C:\Users\sirati97\AppData\Roaming\Telegram Desktop\Telegram.exe" -workdir ".\sirati97\"

**Comment by john-preston** [comment]
@sirati97 Indeed, I'm afraid I've disabled it on Windows in this version as well. Sorry, this command line argument will be fixed in the next version.
