### ISSUE TITLE
OS X: Keyboard shortcut for going full screen

### ISSUE THREAD

**Issue by jonashaag** [telegramdesktop/tdesktop#413]
On OS X, ⌘+⇧+F or ⌘+Ctrl+F should make the app go/leaeve full screen.

Also, ⌘+W should close the window.

**Comment by nmat** [comment]
Full screen does not work.

However command+W does work for me on the latest release.

**Comment by jonashaag** [comment]
![screen shot 2015-02-12 at 17 45 05](https://cloud.githubusercontent.com/assets/175722/6172091/02948aac-b2df-11e4-90ac-05d7e49f52ea.png)

This is what happens when I use ⌘+W in full screen mode: The window is going black but not closing. (Latest version)

**Comment by Aokromes** [comment]
#1060 ?
