### ISSUE TITLE
Error LNK1104	cannot open file 'OpenAL32.lib'

### ISSUE THREAD

**Issue by javadkazemi** [telegramdesktop/tdesktop#4131]
hello, at the end of build this error
...
1>[964/965] CXX obj\gen\Telegram\moc\Telegram.moc_settings_scale_widget.obj
1>[965/965] LINK_EMBED Telegram.exe
1>FAILED: Telegram.exe Telegram.exe.pdb
1>E:\TBuild\ThirdParty\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True Telegram.exe "E:\TBuild\ThirdParty\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:Telegram.exe @Telegram.exe.rsp" 1 mt.exe rc.exe "obj\Telegram.Telegram.exe.intermediate.manifest" obj\Telegram.Telegram.exe.generated.manifest
1>LINK : fatal error LNK1104: cannot open file 'OpenAL32.lib'
1>Traceback (most recent call last):
1>  File "gyp-win-tool", line 323, in <module>
1>    sys.exit(main(sys.argv[1:]))
1>  File "gyp-win-tool", line 29, in main
1>    exit_code = executor.Dispatch(args)
1>  File "gyp-win-tool", line 71, in Dispatch
1>    return getattr(self, method)(*args[1:])
1>  File "gyp-win-tool", line 179, in ExecLinkWithManifests
1>    subprocess.check_call(ldcmd + add_to_ld)
1>  File "E:\TBuild\ThirdParty\Python27\lib\subprocess.py", line 186, in check_call
1>    raise CalledProcessError(retcode, cmd)
1>subprocess.CalledProcessError: Command 'E:\TBuild\ThirdParty\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:Telegram.exe @Telegram.exe.rsp Telegram.exe.manifest.res' returned non-zero exit status 1104
1>ninja: build stopped: cannot make progress due to previous errors.
1>E:\TBuild\tdesktop\Telegram\Telegram.vcxproj(1130,5): error MSB3073: The command "call ninja.exe -C ..\out\Debug\ -k0 Telegram" exited with code 1.
1>Done building project "Telegram.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by john-preston** [comment]
@javadkazemi OpenAL32.lib is not found. Perhaps something in those commands:

git clone git://repo.or.cz/openal-soft.git
cd openal-soft
git checkout 18bb46163af
cd build
cmake -G "Visual Studio 15 2017" -D LIBTYPE:STRING=STATIC -D FORCE_STATIC_VCRT:STRING=ON ..
msbuild OpenAL32.vcxproj /property:Configuration=Debug
msbuild OpenAL32.vcxproj /property:Configuration=Release
cd ..\..

failed.

**Comment by javadkazemi** [comment]
@john-preston now this error in console

Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: OpenAL32.vcxproj

E:\TBuild\Libraries\openal-soft\build>msbuild OpenAL32.vcxproj /property:Configuration=Release
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: OpenAL32.vcxproj

**Comment by john-preston** [comment]
`cmake -G "Visual Studio 15 2017" -D LIBTYPE:STRING=STATIC -DFORCE_STATIC_VCRT:STRING=ON ..`

Perhaps this cmake? Because previous failed I think.

**Comment by john-preston** [comment]
Anyway, you need to build openal successfully.

**Comment by javadkazemi** [comment]
thanks!

**Comment by raimand13** [comment]
if " msbuild OpenAL32.vcxproj /property:Configuration=Debug" did not work, try full path address like this " msbuild E:\TBuild\Libraries\openal-soft\build\OpenAL32.vcxproj /property:Configuration=Debug"
