### ISSUE TITLE
add auto copy when text selection

### ISSUE THREAD

**Issue by Artlant** [telegramdesktop/tdesktop#4133]
Indeed, this will greatly simplify, save, simplify the use. Because what's the point of allocating text in a chat without copying it? Similar functionality is available in other IM and this is clearly not enough here. If to that that also it is really necessary to select simply the text (I can not other reason except for copying) that make such option even option

**Comment by auchri** [comment]
Please use the template and add more description to your requested feature.

**Comment by Artlant** [comment]
Why template? What further description? What can be not clear? When you select text (mouse or tochbar), the text is automatically copied.
Template? me what to specify the version of OS and the telegram? This is unnecessary information. I ask to add a NEW functionality. What kind of bureaucracy? If to you laziness that is simple and write, I will fall behind and understand

### Steps to reproduce
none
### Expected behaviour
copy text
### Actual behaviour
nofing
### Configuration
**Operating system:**
Linux hostname 4.14.3-1-ARCH #1 SMP PREEMPT Thu Nov 30 18:33:13 UTC 2017 x86_64 GNU/Linux
**Version of Telegram Desktop:**
local/telegram-desktop-bin 1.1.23-1
**Used theme**:
default

I hope this information has helped you a lot. I can still attach logs for use if this will help you add a new text copying when selecting

**Comment by john-preston** [comment]
@Artlant On linux version selected text should be copied to the appropriate clipboard as all other applications do.

**Comment by stek29** [comment]
@Artlant 
> **Steps to reproduce**
> none
> **Expected behaviour**
> copy text

So you want app to copy some random text while idle? :)

Template is needed to make issue easier for understanding. It helps other to avoid creating duplicates, it helps people reading it understand your request without reading through completely unformated chunk of text a couple of times.

**Comment by Artlant** [comment]
> So you want app to copy some random text while idle? :)

Done right, we read my thoughts. And preferably in Base64 (sarcasm). 

I became completely indifferent to this issues closed by you.
If you could not understand my words, or my description is too complicated, excuse me.

_select text  mouse -> auto copy to clipboard_ = done!

Template this is good when you need to understand the cause of the problem. But I absolutely can not understand why it is needed when adding a new non-significant functional that is not tied to the platform.
Or the proposal to add new functionality requires the completion of a user questionnaire - do I understand you correctly?

I only what I did not like was the reason for closing the issue

> Please use the template and add more description to your requested feature.

"more description"?? What else can you write? The thesis on 50 pages?

I would understand perfectly if you just wrote:
- We do not want to see this opportunity, it does not like / is not safe / unclaimed
- we are too lazy to implement it
- we are not adding a new functionality now. (Fix only)

all these reasons are completely clear to me. This is a free project and I have no right to demand to force and demand to do what I need.
But I sincerely do not understand the reason for "incorrectly filled template". it's better to write: "Get lost! We do not care".  Because this is also the most direct

**Comment by stek29** [comment]
@Artlant template exists for consistency and to make issues easier to understand.
Theme and logs are not needed, but steps/expected/actual would be nice.
It took me some time to realize what exactly are you asking for, and imo it makes sense indeed.

**Comment by linglung** [comment]
> > So you want app to copy some random text while idle? :)
> 
> _select text mouse -> auto copy to clipboard_ = done!
> 
Sure. i really need this feature too.  it's very useful. 
in telegram mobile it has been implemented if message text is in HTML / markdown `reply markup` mode. 

simply, **just one step:** double click that text message, then it's auto copied to clipboard. done!

unfortunately, this doesn't work in telegram desktop.  i often work with copy-paste some texts with my bot, it's so annoying when i should select text (by double click or block all texts) - right click - copy.
