### ISSUE TITLE
how to use qt vs tools

### ISSUE THREAD

**Issue by javadkazemi** [telegramdesktop/tdesktop#4134]
i now so can build project telegram and install qt vs tools but not found " .pro " file  import to qt vs tools
how to edit graphical telegram? 
please help me!

**Comment by stek29** [comment]
TDesktop uses gyp as build system, not qmake.
Please have a look at [docs](https://github.com/t.elegramdesktop/tdesktop/blob/dev/docs/building-msvc.md)
