### ISSUE TITLE
Swipe left on any message to reply to it

### ISSUE THREAD

**Issue by anfimovir** [telegramdesktop/tdesktop#4136]
in Telegram iOS 4.6, available new feature:

Swipe left on any message to reply to it

it's really love ;)

If possible, please add it in Telegram Desktop.

**Comment by auchri** [comment]
Use the template please.
And  I think that swipe actions aren't useful for mouse users.

**Comment by anfimovir** [comment]
@auchri sorry((

**Comment by ashikns** [comment]
What about Android users? Can we have this there?

**Comment by anfimovir** [comment]
@ashikns Please send via:
Telegram support: https://telegram.org/support
Telegram Twitter: https://twitter.com/telegram
Or for android app: https://github.com/DrKLO/Telegram

**Comment by anfimovir** [comment]
Now available for Android.

**Comment by anfimovir** [comment]
@john-preston fixed in?
https://github.com/telegramdesktop/tdesktop/commit/ae7e5be5cdcde1b09160c8beb98727251271186a

**Comment by john-preston** [comment]
@anfimovir I'm not sure what swipe are desktop users waiting for, but I've added some sort of quick reply.

**Comment by anfimovir** [comment]
@john-preston thank you, I'm close this issue.
