### ISSUE TITLE
Forwarding messages by pressing Enter in the new UI 🐛

### ISSUE THREAD

**Issue by JosXa** [telegramdesktop/tdesktop#4138]
Hi there, I like the new user interface to forward messages a lot. However, there's one important feature missing that was previously there:

### Steps to reproduce
1. Press "Forward" on a message
2. Enter "Saved Messages" (or the name of any chat)
3. DO NOT hover over the target chat with the mouse
4. Press Enter

### Expected behaviour
The target chat should be opened with the intent of forwarding the selected message

### Actual behaviour
Nothing happens, except when I hover over the target chat with my mouse, which makes it work.

### Configuration
**Operating system:**
Arch Linux

**Version of Telegram Desktop:**
1.1.27 alpha

**Comment by john-preston** [comment]
@JosXa Please try this in the released 1.1.28 alpha version.

**Comment by JosXa** [comment]
@john-preston Perfect
