### ISSUE TITLE
Wrong player seekbar position

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#4139]
### Steps to reproduce
1. Play an audio file
2. Seek position by clicking anywhere on seekbar

### Expected behaviour
Seekbar position moves to a new position under the cursor

### Actual behaviour
Seekbar position moves to a new position under the cursor for a moment, then moves slightly forward

![screeencast-2017-12-09](https://user-images.githubusercontent.com/1321838/33798081-2f76b46e-dd1b-11e7-9a4b-92c2479012d0.gif)

### Configuration
**Operating system:** Linux Mint 18.3, Window 10, Arch Linux

**Version of Telegram Desktop:** 1.1.27 alpha

**Used theme**: Any

**Comment by john-preston** [comment]
@aNNiMON Does it work differently in the stable version 1.1.23?

**Comment by aNNiMON** [comment]
@john-preston on stable 1.1.23 it works perfectly.
