### ISSUE TITLE
[Feature Request] Webcam Support

### ISSUE THREAD

**Issue by shinenelson** [telegramdesktop/tdesktop#414]
Since this is an exclusively desktop-based version, I think that you should add support to access the webcam of the host computer to add photos. Currently it only supports uploading photos as attachments. Clicking pictures and uploading them directly, like in the mobile app, should be possible too.

**Comment by ryanralph** [comment]
I disagree. As a security conscious person I would actually prefer to isolate the functions of me taking a webcam photo (using a non internet connected tool) and the process of uploading it to a server.

**Comment by Aokromes** [comment]
I think this can be a good idea, it will be a time saver.

**Comment by brunobsouzac** [comment]
It's a safety issue, but it makes sense to have this option as it is focused on the desktop. A user get the smartphone to take pictures becomes much more complicated and we should focus on usability for both desktop and mobile. The telegram it is in need of a reformed, be simple, safe and objective.

Take a picture using the webcam also opens a possibility being requested by users is video calls and connections as well as Skype, but open, simple and secure. Of course the community will decide this with time.

**Comment by mbnoimi** [comment]
+1

**Comment by franciskittu** [comment]
It's a very useful feature!

**Comment by ppparadox** [comment]
+1

**Comment by corb06** [comment]
Please up this feature to a near future release.

**Comment by auchri** [comment]
Duplicate #781
