### ISSUE TITLE
change the return Back as in the old version

### ISSUE THREAD

**Issue by C-A-T9LIFE** [telegramdesktop/tdesktop#4141]
### Steps to reproduce
Go Back

### Expected behaviour
Please change the implementation of the Go Back as was in the previous version. 

### Actual behaviour
Now when you click on a row, the contact information opens.
It has become very uncomfortable.

### Configuration
Windows 10

**Version of Telegram Desktop:**
1.1.29

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by C-A-T9LIFE** [comment]
![capture20171210124847487](https://user-images.githubusercontent.com/16851877/33804296-9e4b2d68-ddaa-11e7-89e1-ca171da2e75b.png)

**Comment by john-preston** [comment]
@C-A-T9LIFE I'm sorry, but that way was decided to be more consistent within the app and with mobile apps as well both in design and in behaviour.

I'll share your feedback with the designer team, but that decision was thought through.
