### ISSUE TITLE
Support grabbing of opengraph information from .co domains

### ISSUE THREAD

**Issue by smileytechguy** [telegramdesktop/tdesktop#4143]
### Steps to reproduce
1. Make a .co domain name with opengraph metadata (I used https://commiso.co/)
2. Send a message with it

### Expected behaviour
An embed is shown

### Actual behaviour
No embed

### Configuration
Windows 10

1.1.23

Night mode

**Comment by smileytechguy** [comment]
Example:

![image](https://user-images.githubusercontent.com/8005215/33806203-6f253460-dd92-11e7-8f34-578ada95f4cf.png)

![image](https://user-images.githubusercontent.com/8005215/33806207-77b1b63a-dd92-11e7-838f-8ae3e543f33f.png)

**Comment by stek29** [comment]
Links are "grabbed" on server side

**Comment by auchri** [comment]
@smileytechguy Well, I checked your site and a cause might be that you use single quotes for the meta tags: `<meta name='robots' content='index,follow'/>`.

Theoretically it should not make any difference, but you could try to change them to double quotes `"`.
Also I don't know if this is the real issue.

**Comment by smileytechguy** [comment]
@auchri Alright, thanks for looking!  I'll try that!

**Comment by auchri** [comment]
@smileytechguy Also you have `<meta name="og:description" content="..."/>` but it should be `<meta property="og:description" content="..."/>`.

See http://ogp.me/#optional

**Comment by smileytechguy** [comment]
@auchri that might make a difference, let me try that.  I did the same with `og:site_name`.  Your initial suggestion with the `'` vs `"` yielded no change.  Thanks for your help!

**Comment by smileytechguy** [comment]
@auchri No change with the `property` vs `name`.  Also, http://opengraphcheck.com/result.php?url=https%3A%2F%2Fcommiso.co%2F%3Faaa shows all the tags that I have.

**Comment by smileytechguy** [comment]
Yeah, it seems to be an issue with `.co`.  My domain https://smileytechguy.com/ works fine, and I copied all the tags for this one from there

**Comment by auchri** [comment]
@smileytechguy Maybe the wrong preview is cached on the servers 🤷🏼‍♂️ I don't know

**Comment by smileytechguy** [comment]
@auchri I added a URL parameter to test, same problem.  /shrug

**Comment by stek29** [comment]
@smileytechguy Try to open it via instantview.telegram.org

**Comment by auchri** [comment]
@stek29 
![image](https://user-images.githubusercontent.com/5092164/33930137-377a2b68-dfec-11e7-98a4-c9f0d554d9e5.png)

**Comment by auchri** [comment]
@smileytechguy Do you find any access from the Telegram bot in your access logs?

**Comment by auchri** [comment]
And can you create an test site?

E.g. `https://commiso.co/test.html`:

```
<html>
<head>
<title> test </title>
<meta property="og:description" content="Eine Testseite" />
</head>

<body>
test
</body>

</html>
```

**Comment by smileytechguy** [comment]
Sorry, didn't see this until now.  The test page works fine...  I'd imagine there is some caching error from before I added the open graph tags

**Comment by smileytechguy** [comment]
Well, I've figured it out.  Adding an image makes it work!

**Comment by smileytechguy** [comment]
https://commiso.co/
