### ISSUE TITLE
Links do not work in **bold** or __italics__

### ISSUE THREAD

**Issue by smileytechguy** [telegramdesktop/tdesktop#4144]
Not sure if this exists, I searched to no avail however.

### Steps to reproduce
1. Send a message with a link between bold tags, such as `__hey you should totally check out https://t.me/__`

### Expected behaviour
Link is highlighted and possibly embed

### Actual behaviour
Link is treated as plain text

### Configuration
Windows 10

1.1.23

Night

**Comment by john-preston** [comment]
@smileytechguy I’m afraid this is server side issue, all text has entities in it (bold, italic, link, monospace) and they can’t intersect.

**Comment by smileytechguy** [comment]
Where can I report server issues?

**Comment by stek29** [comment]
@smileytechguy On Twitter or via in-app support.
