### ISSUE TITLE
Recent used emojis not saving after restart app

### ISSUE THREAD

**Issue by AliN11** [telegramdesktop/tdesktop#4145]
### Actual behaviour
When I use an emoji, It appears in recent used panel. But when I restart the app, recent used emoji panel containing previous emojis (Default emojis)
Note: One way to save them permanently is that click on emoji icon (At bottom-right of the app)

### Expected behaviour
Recent used emojis must not revert to default after restart app.

### Configuration
**Operating system:**
Windows 7 Ultimate
The problem exists on Ubuntu 17 too.
**Version of Telegram Desktop:**
1.1.23
**Used theme**:
Default

**Comment by auchri** [comment]
Duplicate of #4018
