### ISSUE TITLE
Updater does not preserve -workdir parameter

### ISSUE THREAD

**Issue by sirati97** [telegramdesktop/tdesktop#4149]
### Steps to reproduce
1. Use telegram alpha1.1.29 with custom -workdir parameter
2. download update 1.2alpha in telegram and press update

### Expected behaviour
telegram should update and then launch with old workdir

### Actual behaviour
telegram updates and launches telegram without correctly set workdir parameter resulting in login mask

### Configuration
**Operating system:**
Win10 FCU

**Version of Telegram Desktop:**
alpha1.1.29

**Comment by john-preston** [comment]
@sirati97 Yes, forgot about that :(

**Comment by john-preston** [comment]
ah, again wrong issue.

**Comment by john-preston** [comment]
@sirati97 I've fixed that, but it still won't work with the next update, because Telegram.exe doesn't pass the required arguments to updater. It should work correctly in the update from version 1.2.1 to the next one that will be released.
