### ISSUE TITLE
macOS: Whole UI is shrunk into a small portion (1/4) of window

### ISSUE THREAD

**Issue by jaekyeom** [telegramdesktop/tdesktop#4150]
### Steps to reproduce
1. Just launch Telegram Desktop

### Expected behaviour
Just fine

### Actual behaviour
![image](https://user-images.githubusercontent.com/6262727/33811604-e0acedbe-de58-11e7-9bfe-abdbee1a12e9.png)

The whole UI of tdesktop is displayed in a small portion (1/4) of the window (despite the screenshot here, it's the same after unlocking it).
Besides, mouse clicks work in the window coordinate space, not in this shrunk coordinate space (i.e. I have to anticipate which is where in order to click something)

ADDITIONAL INFO:
I'm using an external monitor.
I just figured out a temporary fix for this issue: moving the window to macbook's display and bring it back to the external display.
But after relaunch, it's broken again.

### Configuration
**Operating system: macOS Sierra 10.12.6**

**Version of Telegram Desktop: 1.2**

**Used theme**: Ubuntu theme, and the default theme. The same.

**Comment by john-preston** [comment]
@jaekyeom Hi. Thanks for your report.

So you have a retina macbook and an external non-retina display. If you launch the app and it appears on the macbook screen first (for example because it was closed -- quitted -- being on macbook screen) it shows normally?

If you drag an already launched app it shows normally?

And only time when it shows incorrectly is when you launch it and it first appears on the external screen?

**Comment by jaekyeom** [comment]
@john-preston 
Thank you for the reply.

> So you have a retina macbook and an external non-retina display.

Yes.

> If you launch the app and it appears on the macbook screen first (for example because it was closed -- quitted -- being on macbook screen) it shows normally?

Yes.

> If you drag an already launched app it shows normally?

I'm not sure if I understand you correctly, but dragging a window that already became normal doesn't make it broken, and dragging/resizing a broken one only inside the external display doesn't fix it.

> And only time when it shows incorrectly is when you launch it and it first appears on the external screen?

Yes.

**Comment by john-preston** [comment]
Unfortunately I don't have Sierra to test, I can't reproduce that on High Sierra :(

**Comment by john-preston** [comment]
@jaekyeom Will you be able to test a special build of the app where I'll try to fix that? Please contact me at https://t.me/preston and I'll send you such a special version when it'll be ready.

**Comment by jaekyeom** [comment]
@john-preston Okay! And, in case this makes things easier (e.g. to look for the commit made this change), version 1.1.23 was fine.
