### ISSUE TITLE
[Suggestion] Easier access to Recent Actions

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#4151]
### Expected behaviour
As in previous design, Recent Actions menu could be placed into "Group/Channel Info" screen somewhere near "Leave Group/Channel" or "Delete ..."

### Actual behaviour
Now you have to open Group/Channel info, tap on three dots, select "Manage Group/Channel" and only then click "Recent Actions".
I'm not a pro in UX, but I personally believe that Recent Actions is accessed much more frequently rather than Blocked users or Group/Channel info screens.

### Configuration
**Operating system:** Any
**Version of Telegram Desktop:** 1.2

**Comment by john-preston** [comment]
@MasterGroosha You can click on three dots in the chat? And then group info, recent actions?

**Comment by MasterGroosha** [comment]
Hmm..yes, looks like I missed it somehow.
Still requires one more click than before, but it's okay. 

Thank you!
