### ISSUE TITLE
Broken font rendering on Linux in version 1.2

### ISSUE THREAD

**Issue by ludoo** [telegramdesktop/tdesktop#4153]
### Steps to reproduce
1. open latest version on Linux (1.2)
2. observe broken fonts

Linux fontconfig has antialias turned off, hinting slight.

### Configuration
**Operating system:**
Debian stretch

**Version of Telegram Desktop:**
1.2

Broken rendering
https://storage.googleapis.com/ludo-public/Screenshot%20from%202017-12-11%2012-23-56.png

**Comment by odinnaodin** [comment]
a similar problem https://i.imgur.com/rx1CqZO.png
Operating system: Arch Linux

**Comment by xvitaly** [comment]
@ludoo @odinnaodin Telegram Desktop from official site use it's own build-in static fontconfig and freetype, so it will not respect systemwide font settings. This is a known issue, which can be fixed only after rebuilding against system libraries.

**Comment by ludoo** [comment]
Versions earlier than 1.2 did not exhibit this behaviour.

**Comment by xvitaly** [comment]
@ludoo On Debian you can use packaged version built against system libraries.

**Comment by ludoo** [comment]
Packaged version has the same rendering issues... :)

**Comment by higowas** [comment]
There are no more solutions ?

**Comment by Aokromes** [comment]
Test after https://github.com/telegramdesktop/tdesktop/commit/8ee958bfa08b2ba87cffaf8de4b65b6890e59ea3
