### ISSUE TITLE
Chat window size not resizable, too large

### ISSUE THREAD

**Issue by DaneelReventelov** [telegramdesktop/tdesktop#4154]
### Steps to reproduce
1. Left panel with only chat icons
2. Right panel with emoji 
3. Take the right border of the chat but refuse to size down

### Expected behaviour
In the previous version I can have the size of the chat panel like a smartphone one, same ratio, now is not possible. I would choose what to see and at what dimension, now if I resize the windows is telegram the choose what I have to see and in which way. I simply want the icons of the chats on left pane, a resizeable column of the chat from 200px to 3000px and the emoji column, now I have forced to have the chat pane at more than 700px or I have to remove emoji pane e chat icons pane. For me is impossible to work with this version if I can't have the same view of the sender if is a smartphone, I'm obliged to revert to previous version

### Actual behaviour
Telegram choose what to see if the I resize the window, the chat pane is not resizeable under 700px

### Configuration
Win10

**Version of Telegram Desktop:**
1.2
**Used theme**:

**Comment by Aokromes** [comment]
#4146 ?

**Comment by stek29** [comment]
@Aokromes not the same but close enough and reference same issue I guess.

**Comment by john-preston** [comment]
@DaneelReventelov You can have the same layout as in old version, I think. The third column can’t be too wide, but you can shrink the whole window if you want the chat column to be smaller.
