### ISSUE TITLE
Regression: UI scaling problem when started in external monitor

### ISSUE THREAD

**Issue by khyox** [telegramdesktop/tdesktop#4156]
### Steps to reproduce
1. Move the Telegram window to external monitor (if not already there)
2. Quit Telegram
3. Open Telegram

### Expected behaviour
UI as expected.

### Actual behaviour
UI view reduced to a fixed area (about 690x370 pixels) in the bottom left of the Telegram window, independently of the size of such window. The active regions (sensitive to mouse actions) are correctly placed occupying the whole window area but, then, misaligned with the window contents, which makes the UI almost unusable.

### Configuration
**Operating system:**
OS X El Capitan in MacBook Pro (Retina, 15-inch, Mid 2014)

**Version of Telegram Desktop:**
Version 1.2

**Screenshot**:
![image](https://user-images.githubusercontent.com/4109713/33843474-c582183a-de9d-11e7-96fb-45ff4e7191fc.png)

**Workaround**
Quitting and relaunching Telegram does not solve the issue but moving the window to the native laptop screen solves the problem and it keeps working as expected once it is moved again to the external monitor.

**Comment by auchri** [comment]
@khyox See #4150

**Comment by khyox** [comment]
Sorry for the duplicate! I wrote a draft of the issue some hours ago and when I definitely sent it, you have already solved the issue in the meanwhile! :1st_place_medal: Thanks.

**Comment by john-preston** [comment]
@khyox It should not happen on High Sierra btw.
