### ISSUE TITLE
Feature Request: Show Chosen Name rather than Contact Name

### ISSUE THREAD

**Issue by DragonFlayer** [telegramdesktop/tdesktop#4158]
### Expected behaviour
A Settings Option that allows system-wide display of the name chosen by your contacts rather than the name you've assigned to their contact on your mobile device (Or lack thereof if you deleted the contact from Telegram)

Enabling this setting would do the following:
- Show Chosen User's Name on Chat List
- Show Chosen User's Name on Chat View's Banner
- Show Chosen User's Name on Notifications
- Show Chosen User's Name on User Info Display
- Show Chosen User's Name on Group Chat
- Show Chosen User's Name on Message Forwards
(And any other instance where an user's name may be displayed)

### Actual behaviour
This option doesn't exist, If you synced contacts they will be displayed across the application with their contact name as saved on your mobile device, deleting the contact from Telegram only results on the name being removed and displaying the contact's phone number instead, in the current implementation the following occurs

- Contact Name or Phone Number shown on Chat List
- Contact Name or Phone Number shown on Chat View's Banner
- Contact Name or Phone Number shown on Notifications
- Contact Name shown on User Info Display
- Contact Name shown on Group Chat
- Contact Name shown on Message Forwards

The following are instances in the current implementation where the Chosen User Name is displayed instead (If you deleted their contact)
- Show Chosen User's Name on User Info Display
- Show Chosen User's Name on Group Chat
- Show Chosen User's Name on Message Forwards

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3893
