### ISSUE TITLE
Feature Request:  Group-Specific Member Icon and Name

### ISSUE THREAD

**Issue by DragonFlayer** [telegramdesktop/tdesktop#4159]
### Expected behaviour
Allow Users to set a Profile Photo and Name (Not Username, their Name for Display) to be displayed for each Group they belong to individually

As an example, in Discord, you may set the name to be displayed on a server-to-server basis (if the server allows it on its permissions)

This feature could give users who separate life, work and different friend groups control over what they present themselves as with more granularity without needing to create a new account on a new phone number

### Actual behaviour
Profile Photo and Name are Global across the entire service, independent of chats or groups

**Comment by stek29** [comment]
Sorry
