### ISSUE TITLE
OSX: Application icon is missing

### ISSUE THREAD

**Issue by scf2k** [telegramdesktop/tdesktop#4161]
### Actual behaviour
The application icon looks like a default XCode project icon, not Telegrams

### Configuration
**Operating system:**
OSX 10.13.1

**Version of Telegram Desktop:**
1.2
![screen shot 2017-12-12 at 09 37 42](https://user-images.githubusercontent.com/1437003/33875870-c28f53d0-df34-11e7-9a5f-c6500724ae63.png)

**Comment by john-preston** [comment]
@scf2k I'm afraid this is an macOS bug =( Some advices here https://discussions.apple.com/thread/8095249

**Comment by scf2k** [comment]
Ouch sorry
