### ISSUE TITLE
Some ogg/m4a files are not recognized as "audio files"

### ISSUE THREAD

**Issue by Yanrishatum** [telegramdesktop/tdesktop#4163]
### Steps to reproduce
1. Send ogg or m4a audio file to chat
2. Check what category that file recieved.
2. Check if file was placed inside player playlist or played as singular file.

### Expected behaviour
File placed in "audio files" category as well as added to playlist.

### Actual behaviour
Some audio files are categorized as just files, despite them being playable via internal player but only as singular files and not parts of playlist.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.2

**Example of ogg file that was categorized as just "file":** https://drive.google.com/open?id=1SJLfrXu3A9Qoavmruo9ahDdRdDJ2beMy  
That file was a result of AIMP Audio Converter, OGG Vorbis 8.0 quality, and encoded from original s3m file.
**Example of m4a file:** https://drive.google.com/open?id=1cND6j-f3Xe-aufyQ3MLW6mPQS1RkT714

**Comment by john-preston** [comment]
@Yanrishatum Do you use the same app (Telegram Desktop 1.2) to send those files as the one for playing them?

**Comment by Yanrishatum** [comment]
@john-preston Yes.

**Comment by john-preston** [comment]
@Yanrishatum Stupid bug. Will be fixed in the next versin, I hope to release it today. Thanks for your report with samples to reproduce.

**Comment by john-preston** [comment]
@Yanrishatum Please check the new 1.2.1 version.

**Comment by Yanrishatum** [comment]
@john-preston Yes, it's fixed now for new files. With exception that files that were sent prior this update still in incorrect category and not inside chat playlist. Thanks.

**Comment by john-preston** [comment]
@Yanrishatum Those are not going to be fixed, tdesktop was sending them incorrectly :(

**Comment by Yanrishatum** [comment]
@john-preston Yeah, I pretty much expected it'll work what way. :) It's not a big deal, glad that bug was fixed pretty rapidly.
