### ISSUE TITLE
Tray icon disappeared in 1.2 on Linux

### ISSUE THREAD

**Issue by fpoto** [telegramdesktop/tdesktop#4164]
After restarting my system, Telegram updated to version 1.2.  Now I see no tray icon. In fact, the icon is apparently there: when I enable/disable the tray icon from the Telegram settings window, I see that the notification area expands/shrinks by few pixels.

I run Debian testing

### Configuration
**Operating system:**
Linux Debian

**Version of Telegram Desktop:**
2.1

**Used theme**:
default

**Comment by stek29** [comment]
#3751 ?

**Comment by fpoto** [comment]
Could be. All the symptoms appear to be the same but one: I do not see a blank space where the icon should be, only few pixels (maybe 5 or less), and I cannot click on them to show the menu as the original reporter of #3751 observes.

**Comment by xvitaly** [comment]
@fpoto Gnome 3.26?

**Comment by fpoto** [comment]
Mate 1.18.0

**Comment by fpoto** [comment]
I have these already installed:
libappindicator1:amd64
libappindicator3-1:amd64

while this is not installed:
libappindicator3-0.1-cil:amd64

All the above have an i386 version too, which is not installed.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4142 ?

**Comment by fpoto** [comment]
It seems #4142 is unrelated, as it mentions an icon without number, while I do not see an icon at all

**Comment by andreymal** [comment]
Likely this is not Telegram problem

https://github.com/mate-desktop/mate-panel/issues/537

**Comment by fpoto** [comment]
Looks like my problem, thanks, I'll follow up there

**Comment by Aokromes** [comment]
close this ticket then :)
