### ISSUE TITLE
Notification number in tray in Linux doesn't disappear

### ISSUE THREAD

**Issue by 4rlekin** [telegramdesktop/tdesktop#417]
I'm running Linux Mint 17 with Cinnamon, recently i updated Telegram app to 0.7.7 version which introduced tray icon for linux.
I noticed that though on my tray icon appears number when somethin happen, it doesn't disappear after i check telegram. I will observe matter further and will post additional notes if anything come up.

**Comment by marcogiorgio** [comment]
already posted #403

**Comment by 4rlekin** [comment]
oh sorry, closing
