### ISSUE TITLE
[OT] Increase Stickers Per Pack 

### ISSUE THREAD

**Issue by UdoKifferbrehl** [telegramdesktop/tdesktop#4174]
Hi, this issue is totally off-topic but I do not know where to put it otherwise. Sorry. 
I am a designer and have a sticker pack with 120 stickers. When I try to add more stickers Telegram tells me:

Whoa! That's probably enough stickers for one pack, give it a break. A pack can't have more than 120 stickers right now.

Can someone increase that number please? Is there a specific reason for that limit? 
I cannot cover every emoji with 120 stickers and next year even more of them will [rise](http://blog.getemoji.com/). 

Thank you so much!

**Comment by stek29** [comment]
@UdoKifferbrehl Try asking via in-app support or via twitter 

I'd just make two packs and link to other pack in last sticker

**Comment by AllanForster** [comment]
What do you think @durov?
