### ISSUE TITLE
Feature request: Support push-to-talk in voice chat

### ISSUE THREAD

**Issue by audreytoskin** [telegramdesktop/tdesktop#4175]
It'd be cool if Telegram supported a push-to-talk function for its voice chat: Instead of _always_ transmitting audio, Telegram would only transmit while I'm holding a (configurable) key on my keyboard, and/or a button on the interface. Ideally, the key would still work even if the Telegram client doesn't currently have focus.

Push-to-talk is most commonly associated with voice chat applications geared toward gamers, but I actually find apps like Mumble useful for any sort of voice-chat context, because its push-to-talk feature minimizes any possible background noises or side talk the other person has to listen to.

**Comment by stek29** [comment]
please request at https://github.com/grishka/libtgvoip

**Comment by terrycloth** [comment]
https://github.com/grishka/libtgvoip/issues/38

**Comment by terrycloth** [comment]
Haha, um, @grishka [says this is a tdesktop issue](https://github.com/grishka/libtgvoip/issues/38#issuecomment-351726611).

**Comment by stek29** [comment]
Yeah, I'm just dumb, sorry about that :)


Haven't thought about just enabling/disabling microphone

**Comment by Aokromes** [comment]
still wanted.

**Comment by yontekh** [comment]
please....

**Comment by Rundik** [comment]
Any updates on that?

**Comment by audreytoskin** [comment]
I believe push-to-talk has been implemented for group calls but not 1-to-1 calls.

**Comment by Rundik** [comment]
I don't think push-to-talk is working when the app is not in focus

**Comment by john-preston** [comment]
It should work for group voice and video chats globally, including when the app isn't focused.
