### ISSUE TITLE
Feature request: Group voice chat

### ISSUE THREAD

**Issue by terrycloth** [telegramdesktop/tdesktop#4176]
This is probably more a request against the server API, but being able to make voice calls with a group instead of just individuals would be nice.

I'd originally been imagining a UI design that was exactly the same as with individual chats, where a voice call button is simply added to the top of the group chat window. However, especially for larger groups, you may not always want to talk to _everyone_ in the group at once -- so it would be even better if you could also pick and choose people in your Telegram contacts to invite to the group call.

**Comment by anfimovir** [comment]
Only wait release in main platforms (iOS, Android).
