### ISSUE TITLE
Support for albums

### ISSUE THREAD

**Issue by nyuszika7h** [telegramdesktop/tdesktop#4178]
### Steps to reproduce
1. Send a photo album from Telegram Android/iOS.
2. View it on Telegram Desktop.

### Expected behaviour
Albums should be displayed grouped like on mobile, to reduce the amount of screen space used by them.

### Actual behaviour
Currently, albums are just displayed as if individual images were sent.

### Configuration
**Operating system:** Windows 10 Home x64 (1703)

**Version of Telegram Desktop:** 1.2.1 alpha

**Used theme**: Default (night mode)

**Comment by Aokromes** [comment]
Implemented on 1.2.2 alpha.

**Comment by stek29** [comment]
@Aokromes which was recalled :)

**Comment by NXij** [comment]
The implementation in the 1.2.2 alpha seems incomplete as you're not able to send them out grouped via tdesktop. Receiving them from any other client that can do that works fine though.

Though technically it is exactly what you wished for, I personally would add the grouping option for outgoing images from tdesktop aswell.

**Comment by RememberTheAir** [comment]
@NXij it's an alpha release, so maybe we will get the ability to send albums with the next updates :)
