### ISSUE TITLE
UI request: Create subgroups for my conversations/groups I'm part of.

### ISSUE THREAD

**Issue by ross999** [telegramdesktop/tdesktop#4179]
Many people, including myself belong to many groups. I have around 30 myself. Right now it's very hard to find what I'm looking for and what is most important.

I'd like to suggest allowing users to create groups. For example, let's say I have a few crypto groups and a few web design groups, and maybe some gardening groups. I would like to create a main grouping of each of the various groups for each hobby and use that as a holder area. Make sense?

I'm a UX designer in NYC so if somebody needs help conceptualizing this let me know.

**Comment by ross999** [comment]
Where's the duplicate? I spent time writing this out. At least make a comment and show the duplicate.

**Comment by stek29** [comment]
#3942 #3935 #3905 #3892 #3747 #3805 #3642 #3165 #2702 #2620 #2511 #2359 #2282 #2245 #1725 #1687 #1627 #1505 #1229 #1219 #1107 and others.

**Comment by ross999** [comment]
Great. So it's been asked over 20 times for the past 2 years and nothing has been done? Every group I'm in I see people saying something similar that we need something like this. What needs to happen in order to get this going?

**Comment by mnymic** [comment]
I guess the only way is to build own telegram, with blackjack and grouping.
[Plus Messenger ](https://play.google.com/store/apps/details?id=org.telegram.plus&hl=en_US) did it for Android. Just look at the pciture below: 
![image](https://user-images.githubusercontent.com/38245587/43534879-18f938d8-95c1-11e8-8cc2-1787eafc3472.png)

**Comment by DRSDavidSoft** [comment]
Why #1107 is locked all of a sudden? It seems to contain the main discussions.

**Comment by stek29** [comment]
@DRSDavidSoft because most messages don't add anything important to that "discussion".

**Comment by kenorb** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1505#issuecomment-625897529
