### ISSUE TITLE
[feature request] ability to rename contact in desktop application

### ISSUE THREAD

**Issue by guai** [telegramdesktop/tdesktop#4184]
There was similar feature already, it is closed in 2016
But I see no way to rename a contact right now in the latest release
No edit button or menu item - nothing like that

**Comment by guai** [comment]
Actually I've found edit contact button. But its missing on some contacts while present on others

**Comment by auchri** [comment]
![image](https://user-images.githubusercontent.com/5092164/33986009-8b7356ce-e0bc-11e7-83d1-1d6170daf801.png)

**Comment by guai** [comment]
Pls reopen
This button missing on some of my contacts

**Comment by guai** [comment]
https://gist.github.com/guai/30a9d3dc6f8e68066166ee087d229e6a

**Comment by auchri** [comment]
@guai afaik you can't rename contacts which are not in your adress book.

**Comment by guai** [comment]
And why is that? I have no addressbook on my pc

**Comment by RememberTheAir** [comment]
Contacts are synced when you login into a mobile client. You can then see them from other desktop clients too. You can also rename them.

But you cannot set the name of the users which are not in your Telegram phonebook, which is what you're asking in this issue. Renaming non-contact users should be supported by the API, and Telegram Desktop can't do nothing about it until the server supports non-contacts renaming

**Comment by guai** [comment]
@RememberTheAir, are you saying its impossible display one string in gui instead of another? I don't buy it

**Comment by auchri** [comment]
@guai Not one which is synced to you other devices, no.

**Comment by RememberTheAir** [comment]
@guai it would abviously be possible, but since Telegram is a multiplatform application, having a name on Desktop and another on mobile because the API doesn't support non-contacts renaming would be highly inconsistent and non-sensed

**Comment by guai** [comment]
@auchri, as you said this contact is not on my phone so what syncing are you talking about? there is nothing to sync

**Comment by guai** [comment]
So what do you propose? I should post an issue in to telegram API project? Can you pls point me where it is

**Comment by auchri** [comment]
@guai If you rename that contact on your PC, I'm sure you want the new name on your phone as well.

https://twitter.com/telegram

**Comment by guai** [comment]
> you want the new name on your phone
I don't

**Comment by auchri** [comment]
@guai But every other expects this behaviour.

**Comment by guai** [comment]
Gosh! Why this simple and obvious feature should be so hard? I don't have any twitter, don't they have an issue tracker?

> every other expects this behaviour
No they dont

**Comment by auchri** [comment]
> Why this simple and obvious feature should be so hard?

It may look like an simple feature if you only look at Telegram Desktop, but since the new name should be synced to your other devices, it's not that easy and impossible at the moment (because the api doesn't support it).

> I don't have any twitter, don't they have an issue tracker?

No they don't

**Comment by guai** [comment]
> since the new name should be synced
Who said that?

You can patch this hole in the API on your side temporarily. See no reasons why not

**Comment by auchri** [comment]
> Who said that?

I said that, lol

> You can patch this hole in the API on your side temporarily. See no reasons why not

This repo is only about Telegram **Desktop**, we can't change the api.

**Comment by guai** [comment]
I'm not asking to change any API. I ask for the feature so I be able to edit contact names. in non-synched fashion. Just make a hash-table contactId=>newName. Is it something unimaginable?

**Comment by auchri** [comment]
> unimaginable

We won't implement such an feature on **Desktop** only, if you want to have this feature you have to contact Telegram on Twitter.

**Comment by guai** [comment]
> We won't implement such an feature
Why not? Something prohibits features like this or its just laziness?

**Comment by auchri** [comment]
> Something prohibits features like this

Yes, there is no api to sync the name to other devices and we won't implement Desktop-only features.

**Comment by guai** [comment]
@auchri, that's not the answer to my question

> won't implement

You can't or you don't want to?

**Comment by auchri** [comment]
We don't want to.

**Comment by pascalandy** [comment]
I would love to rename my users as well even if they are not on my phone contacts.
