### ISSUE TITLE
External Links don't work on macOS in Version 1.2.1

### ISSUE THREAD

**Issue by kx550** [telegramdesktop/tdesktop#4189]
### Steps to reproduce
1. Click on an external link in a chat message

### Expected behaviour
The link should open in new browser _tab_.

### Actual behaviour
A new empty browser _window_ opens but not the link content.

### Configuration
**Operating system:**
macOS 10.13.1

Browser used is Google Chrome Version 62.0.3202.94

**Version of Telegram Desktop:**
1.2.1

**Used theme**:
Default

**Comment by stek29** [comment]
Restart your computer/chrome. Happened to me a couple of times, links stopped working for all apps.

**Comment by john-preston** [comment]
@kx550 I'm afraid this is Chromes fault and it happens with all applications with links (except the chrome itself, of course :)

**Comment by kx550** [comment]
Thanks, restarting Chrome fixed this!
