### ISSUE TITLE
[Feature request] Gray system tray icon

### ISSUE THREAD

**Issue by ozcan** [telegramdesktop/tdesktop#419]
System tray icon is awesome, but can you add gray icon also? Grayscale icons are very common in most of the desktop environments.

![image](https://cloud.githubusercontent.com/assets/940884/5802894/db9f15b0-a001-11e4-9489-f40c45b18631.png)

**Comment by bil-elmoussaoui** [comment]
Fixing this #1002  will make it possible to theme the indicator icon, you seem to be using Numix icon theme ;) I built a tool to fix hardcoded tray icons, you can find it in the readme page of Numix base theme

**Comment by AndydeCleyre** [comment]
[This hack](https://github.com/telegramdesktop/tdesktop/issues/2230#issuecomment-239507699), modified for your color/icon preferences, may be useful for some of you until this is sorted.

**Comment by auchri** [comment]
#1908
