### ISSUE TITLE
Mute-notification group's messages doesn't change tray icon on windows

### ISSUE THREAD

**Issue by Taosky** [telegramdesktop/tdesktop#4190]
I mean that gray number shows on tray icon when I use telegram on ubuntu.
It's a useful feature.

**Comment by stek29** [comment]
It's read only when you have unread notifications from unmuted chats

**Comment by Taosky** [comment]
@stek29 yes，but on ubuntu it's gary from unread muted chats. Will windows version been updated to support this feature?

**Comment by Taosky** [comment]
@stek29  Sorry, my fault. it's indeed gray numbers, may be my network isn't good .
Issue closed.
