### ISSUE TITLE
Global search doesn't find the channel

### ISSUE THREAD

**Issue by HaMo0n** [telegramdesktop/tdesktop#4192]
### Actual behaviour
When I search @behtarin_iran on Telegram Global search, Telegram can't find channel. But I'm sure the channel exist because you can see this from Web 
https://t.me/behtarin_iran

### Configuration
**Ubuntu 14.04:**

**Telegram Desktop 1.2.1**

**Comment by stek29** [comment]
Server Side issue, sorry.
I think that started happening after "smart search" update.
