### ISSUE TITLE
non-breaking space does not work

### ISSUE THREAD

**Issue by grepwood** [telegramdesktop/tdesktop#4193]
Hello,

I wanted to write a message containing non-breaking spaces to do something like this:
   ▲
▲  ▲
`noobs can't triforce`

However, my plan was foiled because telegram treats non-breaking spaces as normal spaces. Could someone fix this please? In addition, typing characters via Ctrl+Shift+u on Linux does not work at all. The correct implementation inserts the u, waits for hex code of a unicode char, and prints it upon next press of Enter.

**Comment by stek29** [comment]
It's stripped on server side, even if TDesktop doesn't strip it.
Message has to start with non-whitespace character, because whitespace characters in the beginning and in the end are removed.

**Comment by akaleeroy** [comment]
So what Unicode character can we use that doesn't get detected as whitespace and stripped?

**Comment by volonterx** [comment]
@grepwood @akaleeroy 

U+200C in begin of the string works. 
But it does not give triforce copy/paste protection.

**Comment by Mithgol** [comment]
But what if the whitespace is neither in the beginning not at the end of the string, but in the middle of it?

Even there Telegram Desktop seems to replace non-breaking spaces (Unicode U+00A0) by regular spaces:

1) in sent messages,

2) in received messages,

3) in drafts saved by other applications (such as from Telegram on Android) in a group chat currently being viewed by Telegram Desktop.

Also sometimes a long line containing non-breaking spaces in not wrapped correctly in the input field (below the chat), i.e. a letter that begins the second line can be given some negative indent (and thus disappear almost entirely behind the left border of the field) if immediately preceded by a regular space but also immediately followed by a non-breaking space and some word (that caused the word-wrapping for this letter to begin that second line in the first place).

Observed on Windows 7 SP1 64-bit in Telegram Desktop 1.7.7.

**Comment by Mithgol** [comment]
I have to use the words “seems to replace” (instead of “replaces”) because at least the received messages look fine in other Telegram clients (such as Telegram for Android) until and unless edited in Telegram Desktop. However, Telegram Desktop still displays them **as if** all non-breaking spaces were replaced by regular spaces.
