### ISSUE TITLE
Crash on right-click when maximized

### ISSUE THREAD

**Issue by TychoWerner** [telegramdesktop/tdesktop#4194]
### Steps to reproduce
1. Open up client
2. Make sure client is maximized 
3. Right-click anywhere
4. Client crashes
5. No profit.

### Expected behaviour
No crash

### Actual behaviour
Client crashes

### Configuration
**Operating system:**
[[https://lh3.googleusercontent.com/-qdPEs1FC4M8/WjV__V2Gy9I/AAAAAAAA_iU/fibibv2i4tcLwwKmGcA3WfZ7mfj0ZaJvACHMYCw/s0/Speccy64_2017-12-16_21-20-08.png]

**Version of Telegram Desktop:**
Version 1.2.2 Alpha

**Used theme**:
None.
<details><summary><b>Logs</b>:</summary>
ApiId: 2040
Binary: Telegram.exe
Launched: 16.12.2017 21:19:40
Platform: Windows
UserTag: 86a4886e6136eb15
Version: 1002002 alpha

Caught signal 11 (SIGSEGV) in thread 22520

Backtrace:
24018843
39385009
39156579
1995191178
2006555138
2006555093

Google Breakpad caught a crash, minidump written in thread 22488
Minidump: eec645f7-c2a5-4b56-8976-81afa10971e3

Backtrace:
24018843
24019024
29720271
2006555138
2006555093

</details>

**Comment by NXij** [comment]
This is the reason why the 1.2.2 alpha build was pulled back. Happens for me when it is not maximized aswell.
Seems to be a problem regarding the History widget itself as the context menu works everywhere else.

**Comment by TychoWerner** [comment]
Ah, well I posted this before it got pulled back. I just wanted to get a confirm I wasn't the only one.
