### ISSUE TITLE
Random crashes on voice call

### ISSUE THREAD

**Issue by maxkrivich** [telegramdesktop/tdesktop#4195]
### Steps to reproduce
1.  Open telegram
2.  Choose person and call
3.  Wait some time

### Expected behaviour
Should works without crashes

### Actual behaviour
Application crashes after few minutes 

### Configuration
**Operating system:** Ubuntu 16.04 LTS

**Version of Telegram Desktop:** 1.2.1

**Used theme**: default

**Other**
```sh
$ lspci -v | grep -i audio
00:1b.0 Audio device: Intel Corporation 7 Series/C210 Series Chipset Family High Definition Audio Controller (rev 04)
	Subsystem: ASUSTeK Computer Inc. 7 Series/C210 Series Chipset Family High Definition Audio Controller

$ lsmod | grep snd
snd_hda_codec_hdmi     49152  1
snd_hda_codec_realtek    90112  1
snd_hda_codec_generic    73728  1 snd_hda_codec_realtek
snd_hda_intel          36864  5
snd_hda_codec         126976  4 snd_hda_intel,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_hda_codec_realtek
snd_hda_core           81920  5 snd_hda_intel,snd_hda_codec,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_hda_codec_realtek
snd_hwdep              16384  1 snd_hda_codec
snd_pcm               102400  5 snd_hda_intel,snd_hda_codec,snd_hda_core,snd_hda_codec_hdmi
snd_seq_midi           16384  0
snd_seq_midi_event     16384  1 snd_seq_midi
snd_rawmidi            32768  1 snd_seq_midi
snd_seq                65536  2 snd_seq_midi_event,snd_seq_midi
snd_seq_device         16384  3 snd_seq,snd_rawmidi,snd_seq_midi
snd_timer              32768  2 snd_seq,snd_pcm
snd                    77824  20 snd_hda_intel,snd_hwdep,snd_seq,snd_hda_codec,snd_timer,snd_rawmidi,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_seq_device,snd_hda_codec_realtek,snd_pcm
soundcore              16384  1 snd

$ cat /proc/asound/version
Advanced Linux Sound Architecture Driver Version k4.10.0-42-generic.

$ cat /proc/asound/cards
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7a10000 irq 31
```

<details><summary><b>Logs</b>:</summary>
QObject::startTimer: Timers cannot have negative intervals
D/tgvoip: === Updating voip config ===
V/tgvoip: audio_bitrate_step_decr -> 1000.000000
V/tgvoip: audio_bitrate_step_incr -> 1000.000000
V/tgvoip: audio_congestion_window -> 1024.000000
V/tgvoip: audio_frame_size -> 60.000000
V/tgvoip: audio_init_bitrate -> 16000.000000
V/tgvoip: audio_init_bitrate_edge -> 8000.000000
V/tgvoip: audio_init_bitrate_gprs -> 8000.000000
V/tgvoip: audio_init_bitrate_saving -> 8000.000000
V/tgvoip: audio_max_bitrate -> 20000.000000
V/tgvoip: audio_max_bitrate_edge -> 16000.000000
V/tgvoip: audio_max_bitrate_gprs -> 8000.000000
V/tgvoip: audio_max_bitrate_saving -> 8000.000000
V/tgvoip: jitter_losses_to_reset -> 20.000000
V/tgvoip: jitter_max_delay_20 -> 25.000000
V/tgvoip: jitter_max_delay_40 -> 15.000000
V/tgvoip: jitter_max_delay_60 -> 10.000000
V/tgvoip: jitter_max_slots_20 -> 50.000000
V/tgvoip: jitter_max_slots_40 -> 30.000000
V/tgvoip: jitter_max_slots_60 -> 20.000000
V/tgvoip: jitter_min_delay_20 -> 6.000000
V/tgvoip: jitter_min_delay_40 -> 4.000000
V/tgvoip: jitter_min_delay_60 -> 2.000000
V/tgvoip: jitter_resync_threshold -> 0.500000
V/tgvoip: use_system_aec -> true
V/tgvoip: use_system_ns -> true
V/tgvoip: new endpoint 40004: 91.108.8.4:539
V/tgvoip: new endpoint 40007: 91.108.8.7:533
V/tgvoip: new endpoint 10002: 91.108.12.2:529
V/tgvoip: new endpoint 10001: 91.108.12.1:536
V/tgvoip: new endpoint 50003: 91.108.16.3:533
V/tgvoip: new endpoint 50002: 91.108.16.2:529
D/tgvoip: Send reliably, type=3, len=2, retry=0.500, timeout=20.000
W/tgvoip: Set remote endpoints
V/tgvoip: Adding endpoint: 91.108.8.4:539, UDP
V/tgvoip: Adding endpoint: 91.108.8.7:533, UDP
V/tgvoip: Adding endpoint: 91.108.12.2:529, UDP
V/tgvoip: Adding endpoint: 91.108.12.1:536, UDP
V/tgvoip: Adding endpoint: 91.108.16.3:533, UDP
V/tgvoip: Adding endpoint: 91.108.16.2:529, UDP
I/tgvoip: update data saving mode, config 0, enabled 0, reqd by peer 0
W/tgvoip: Starting voip controller
V/tgvoip: trying bind to port 22687
D/tgvoip: Bound to local UDP port 22687
I/tgvoip: Receive thread starting
V/tgvoip: Call state changed to 2
D/tgvoip: Sending queued packet, seq=2, type=3, len=2
V/tgvoip: Sending UDP ping to 91.108.8.4:539
V/tgvoip: Sending UDP ping to 91.108.8.7:533
V/tgvoip: Sending UDP ping to 91.108.12.2:529
V/tgvoip: Sending UDP ping to 91.108.12.1:536
V/tgvoip: Sending UDP ping to 91.108.16.3:533
V/tgvoip: Sending UDP ping to 91.108.16.2:529
D/tgvoip: SIGNAL BAR COUNT CHANGED: 1
I/tgvoip: Detected IPv4 connectivity, will not try IPv6
D/tgvoip: SIGNAL BAR COUNT CHANGED: 2
D/tgvoip: SIGNAL BAR COUNT CHANGED: 3
D/tgvoip: SIGNAL BAR COUNT CHANGED: 4
V/tgvoip: Call state changed to 2
D/tgvoip: Sending queued packet, seq=7, type=3, len=2
V/tgvoip: Call state changed to 2
D/tgvoip: Sending queued packet, seq=11, type=3, len=2
V/tgvoip: Call state changed to 2
D/tgvoip: Sending queued packet, seq=16, type=3, len=2
D/tgvoip: Received init
I/tgvoip: Peer version is 3
W/tgvoip: Received duplicated packet for seq 1
V/tgvoip: Call state changed to 2
W/tgvoip: Received duplicated packet for seq 1
W/tgvoip: Received duplicated packet for seq 1
W/tgvoip: Received duplicated packet for seq 1
W/tgvoip: Received duplicated packet for seq 1
D/tgvoip: Sending queued packet, seq=21, type=3, len=2
D/tgvoip: queued packet 0, seq 0=21
V/tgvoip: remote acks index 4294967295, value -1.000000
D/tgvoip: queued packet 0, seq 1=16
V/tgvoip: remote acks index 4, value 0.000000
D/tgvoip: queued packet 0, seq 2=11
V/tgvoip: remote acks index 9, value 0.000000
D/tgvoip: queued packet 0, seq 3=7
V/tgvoip: remote acks index 13, value 0.000000
D/tgvoip: queued packet 0, seq 4=2
V/tgvoip: remote acks index 18, value 0.000000
D/tgvoip: queued packet 0, seq 5=0
D/tgvoip: Received init ack
I/tgvoip: peer version from init ack 3
I/tgvoip: before create audio io
V/tgvoip: starting encoder, packets per frame=3
I/tgvoip: decoder: packets per frame 3
W/tgvoip: jitter: found no packet for timestamp 0 (last put = 0, lost = 0)
W/tgvoip: jitter: found no packet for timestamp 60 (last put = 0, lost = 0)
V/tgvoip: Trying to recover late packet
W/tgvoip: jitter: found no packet for timestamp 0 (last put = 0, lost = 0)
I/tgvoip: Sending public endpoints request
D/tgvoip: Sending public endpoints request to 91.108.8.4:539
V/tgvoip: PLC
D/tgvoip: queued packet 0, seq 0=21
V/tgvoip: remote acks index 1, value 5076.152764
D/tgvoip: did ack seq 21, removing
D/tgvoip: Received init
I/tgvoip: Peer version is 3
W/tgvoip: Received duplicated packet for seq 3
V/tgvoip: Call state changed to 3
I/tgvoip: jitter: resyncing, next timestamp = -180 (step=60, minDelay=3)
W/tgvoip: jitter: found no packet for timestamp -180 (last put = 0, lost = 0)
V/tgvoip: Trying to recover late packet
W/tgvoip: jitter: found no packet for timestamp -240 (last put = 0, lost = 0)
V/tgvoip: PLC
V/tgvoip: new endpoint 0: 46.211.158.125:45280
W/tgvoip: Received reflector peer info, my=A7355EB2:22687, peer=7D9ED32E:45280
W/tgvoip: jitter: found no packet for timestamp -120 (last put = 60, lost = 0)
V/tgvoip: Trying to recover late packet
W/tgvoip: jitter: found no packet for timestamp -180 (last put = 60, lost = 0)
V/tgvoip: PLC
D/tgvoip: new delay from stddev 2
V/tgvoip: Sending ping to 91.108.8.4
V/tgvoip: Sending ping to 91.108.8.7
V/tgvoip: Sending ping to 91.108.12.2
V/tgvoip: Sending ping to 91.108.12.1
V/tgvoip: Sending ping to 91.108.16.3
V/tgvoip: Sending ping to 91.108.16.2
V/tgvoip: Sending ping to 46.211.158.125
W/tgvoip: Received duplicated packet for seq 3
W/tgvoip: Received duplicated packet for seq 3
W/tgvoip: jitter: found no packet for timestamp -60 (last put = 120, lost = 0)
V/tgvoip: outstanding delay change: -40
V/tgvoip: Trying to recover late packet
W/tgvoip: jitter: found no packet for timestamp -120 (last put = 120, lost = 0)
V/tgvoip: outstanding delay change: -20
V/tgvoip: PLC
W/tgvoip: Received duplicated packet for seq 3
W/tgvoip: Received duplicated packet for seq 3
D/tgvoip: Current RTT via 46.211.158.125: 0.100, average: 0.100
V/tgvoip: outstanding delay change: 0
V/tgvoip: Trying to recover late packet
W/tgvoip: jitter: found no packet for timestamp -60 (last put = 120, lost = 0)
D/tgvoip: Current RTT via 91.108.8.4: 0.177, average: 0.177
D/tgvoip: Current RTT via 91.108.8.7: 0.184, average: 0.184
I/tgvoip: Switching to p2p (Inet)
D/tgvoip: Received init
I/tgvoip: Peer version is 3
D/tgvoip: Current RTT via 91.108.12.1: 0.414, average: 0.414
W/tgvoip: Received duplicated packet for seq 20
W/tgvoip: Received duplicated packet for seq 20
D/tgvoip: Current RTT via 91.108.12.2: 0.431, average: 0.431
D/tgvoip: Current RTT via 91.108.16.2: 0.437, average: 0.437
D/tgvoip: Current RTT via 91.108.16.3: 0.439, average: 0.439
W/tgvoip: Received duplicated packet for seq 20
W/tgvoip: Received duplicated packet for seq 20
W/tgvoip: Received duplicated packet for seq 20
W/tgvoip: Received duplicated packet for seq 20
D/tgvoip: Received init
I/tgvoip: Peer version is 3
W/tgvoip: Received duplicated packet for seq 29
W/tgvoip: Received duplicated packet for seq 29
W/tgvoip: Received duplicated packet for seq 29
W/tgvoip: Received duplicated packet for seq 29
W/tgvoip: Received duplicated packet for seq 29
W/tgvoip: Received duplicated packet for seq 29
D/tgvoip: Received init
I/tgvoip: Peer version is 3
W/tgvoip: Received duplicated packet for seq 39
W/tgvoip: Received duplicated packet for seq 39
D/tgvoip: Received ping from 46.211.158.125:45280
D/tgvoip: Received ping from 91.108.8.4:539
D/tgvoip: Received ping from 91.108.8.7:533
W/tgvoip: Received duplicated packet for seq 39
W/tgvoip: Received duplicated packet for seq 39
W/tgvoip: Received duplicated packet for seq 39
W/tgvoip: Received duplicated packet for seq 39
D/tgvoip: Received ping from 91.108.12.1:536
D/tgvoip: Received ping from 91.108.12.2:529
D/tgvoip: Received ping from 91.108.16.3:533
D/tgvoip: Received ping from 91.108.16.2:529
V/tgvoip: outstanding delay change: 0
V/tgvoip: outstanding delay change: 0
V/tgvoip: outstanding delay change: 0
V/tgvoip: outstanding delay change: 0
V/tgvoip: Sending ping to 91.108.8.4
V/tgvoip: Sending ping to 91.108.8.7
V/tgvoip: Sending ping to 91.108.12.2
V/tgvoip: Sending ping to 91.108.12.1
V/tgvoip: Sending ping to 91.108.16.3
V/tgvoip: Sending ping to 91.108.16.2
V/tgvoip: Sending ping to 46.211.158.125
D/tgvoip: Current RTT via 46.211.158.125: 0.095, average: 0.097
D/tgvoip: Current RTT via 91.108.8.4: 0.196, average: 0.186
D/tgvoip: Current RTT via 91.108.8.7: 0.197, average: 0.191
D/tgvoip: Current RTT via 91.108.12.1: 0.436, average: 0.425
D/tgvoip: Current RTT via 91.108.12.2: 0.437, average: 0.434
D/tgvoip: Current RTT via 91.108.16.3: 0.459, average: 0.449
D/tgvoip: Current RTT via 91.108.16.2: 0.460, average: 0.449
D/tgvoip: Received ping from 46.211.158.125:45280
D/tgvoip: Received ping from 91.108.8.4:539
D/tgvoip: Received ping from 91.108.8.7:533
D/tgvoip: Received ping from 91.108.12.1:536
D/tgvoip: Received ping from 91.108.12.2:529
D/tgvoip: Received ping from 91.108.16.3:533
D/tgvoip: Received ping from 91.108.16.2:529
D/tgvoip: Send reliably, type=3, len=2, retry=0.500, timeout=20.000
D/tgvoip: Sending queued packet, seq=117, type=3, len=2
D/tgvoip: queued packet 0, seq 0=117
V/tgvoip: remote acks index 4294967295, value -1.000000
D/tgvoip: queued packet 0, seq 1=0
D/tgvoip: queued packet 0, seq 0=117
V/tgvoip: remote acks index 0, value 5088.527753
D/tgvoip: queued packet 0, seq 1=0
E/tgvoip: Can't provide 19942 bytes of audio data at a time
Assertion '!m->thread || !pa_thread_is_running(m->thread) || !in_worker(m)' failed at pulse/thread-mainloop.c:187, function pa_threaded_mainloop_unlock(). Aborting.
V/tgvoip: opus_encoder: setting bitrate to 20000
E/tgvoip: Audio I/O failed
V/tgvoip: Call state changed to 4
V/tgvoip: Call state changed to 3
[1]    30469 abort (core dumped)  sudo ./telegram

</details>

**Comment by Aokromes** [comment]
#3595 ?

**Comment by maxkrivich** [comment]
@Aokromes updates to 1.2.6 and that annoying bug were disappear
