### ISSUE TITLE
[Feature Request] Instant View

### ISSUE THREAD

**Issue by ThigSchuch** [telegramdesktop/tdesktop#4197]
The title speaks for itself, add Instant View to desktop, that helps a lot and we need it.

Even Unigram Desktop have it, and the official Telegram not, come on...

Hope can introduce it soon, thx.

**Comment by john-preston** [comment]
@ThigSchuch I can't introduce it soon :( it requires at least the ability to embed web content inside the app, which I currently don't have.

**Comment by ThigSchuch** [comment]
Not soon, but you think you can do this someday?
Maybe Unigram devs can help with this?

**Comment by john-preston** [comment]
@ThigSchuch Unigram works only on Windows 10, while Telegram Desktop works on Windows starting with XP, OS X starting with 10.6 and Linux, so I’m afraid not.

Some day perhaps, but not in the near future.

**Comment by xvitaly** [comment]
Instant View is not suitable for Telegram Desktop I think. On desktop you can open regular web browser to view hyperlink content.

**Comment by xvitaly** [comment]
> I can open links on phone too, the point here is: read articles instantly, on the program, not in browsers.

This is suitable for mobile devices: view articles without running web browser to save battery charge, but not desktops.

BTW, lots of sites are now blocking Telegram Instant view crawlers, because they don't like losing money from ads.

**Comment by sirati97** [comment]
@john-preston how about using chromium but in order to keep the download size small it must be enabled in settings and chromium is then downloaded as separate dll?

**Comment by MasterGroosha** [comment]
Duplicate #3492
