### ISSUE TITLE
Direct share "send" button not working

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#4198]
### Steps to reproduce
1. click on a ["direct share" button](https://i.imgur.com/Gtt8mjk.jpg)
2. select one/more receiver(s)
3. click on ["send"](https://i.imgur.com/Bdoj9sD.jpg)

### Expected behaviour
The message is forwarded to the selected chats

### Actual behaviour
Nothing happens

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** alpha 1.2.3 portable

**Used theme**: stock night skin

**Comment by ThigSchuch** [comment]
Same happens here, Windows 10, alpha v1.2.3.

**Comment by john-preston** [comment]
@RememberTheAir Thanks for your report!

**Comment by RememberTheAir** [comment]
I'm a bit confused. There was no update but now the direct share button is working again
