### ISSUE TITLE
Chat history search function failure in Chinese

### ISSUE THREAD

**Issue by Fezreal** [telegramdesktop/tdesktop#4199]
see Picture
https://imgur.com/a/EYpAv
https://imgur.com/a/vGkCI
https://imgur.com/a/y216G

Obviously,Search function does not work properly in Chinese

**Comment by auchri** [comment]
First of all: Use the template.

Second, the search only matches full words afaik.

**Comment by Fezreal** [comment]
Aha, fortunately Google Search does not need to be fully matched and works.

**Comment by auchri** [comment]
Afaik this is an api limitation -> https://twitter.com/telegram

**Comment by Fezreal** [comment]
@auchri 
 When time can improve this API?
Almost a year has passed.
