### ISSUE TITLE
Tray icon menu problem

### ISSUE THREAD

**Issue by alirezaaa** [telegramdesktop/tdesktop#420]
Activating window by clicking 'Open Telegram' on tray icon menu while the mouse pointer is not inside of the hidden icons window area causes the hidden icons window be closed.

Needed information:
OS: Windows 8.1
Installed version of Telegram: 0.7.8

**Comment by telegramdesktop** [comment]
Are you speaking about this small window with icons?

![image](https://cloud.githubusercontent.com/assets/6113871/5957493/57ef212a-a7cb-11e4-9aba-0bae7ee81201.png)

Why do you need it opened? Anyway, OS is in control of that window, not me. Or I didn't understand you well.

**Comment by Alirezaaa** [comment]
@telegramdesktop Yes, I'm talking about that window. Please move your pointer to the right corner of Telegram menu; After some seconds you will see the window behind the Telegram window will be closed. This is not default action in Windows.

**Comment by telegramdesktop** [comment]
Well, it does, it is not a default menu. But I don't see a problem here.

**Comment by Alirezaaa** [comment]
This is not a bug; But you can redesign that section better to prevent from closing hidden icons box behind the Telegram menu automatically.

**Comment by auchri** [comment]
Fixed for me

**Comment by alirezaaa** [comment]
I'm currently using Windows 10 (up to date) but the problem still exists.

**Comment by lausianne** [comment]
I don't even see the icon at all in Windows 10 (not yet 1511).

**Comment by telegramdesktop** [comment]
@lausianne Did you look in hidden icons section? Is it enabled in Settings?

**Comment by lausianne** [comment]
@telegramdesktop Yes, sure. Looked everywhere and it has always been enabled. In the task manager I still see telegram running after closing the main window, but elsewhere no trace of it. EDIT: There WAS no trace of it. I tried again now, opening telegram - no icon. Then I closed it again, and now finally the icon appeared.
