### ISSUE TITLE
[Linux] UIM + Anthy (UTF-8) doesn't work

### ISSUE THREAD

**Issue by aphirst** [telegramdesktop/tdesktop#4201]
### Steps to reproduce
1. Set up Japanese input in accordance with [the Arch Wiki](https://wiki.archlinux.org/index.php/Input_Japanese_using_uim), UIM and Anthy (UTF-8)
2. [Build against system QT](https://aur.archlinux.org/packages/telegram-desktop-systemqt/) (otherwise, my normal keyboard layout, UK Intl, didn't work with special characters using AltGr+deadkey+letter e.g. äöü)
3. Select telegram-desktop text field, press Input Mode toggle hotkey, start typing.

### Expected behaviour
System tray icon should indicate switch to Japanese input, typed letters should resolve into hiragana/katakana etc. (i.e. normal functioning of UIM+Anthy)

### Actual behaviour
UIM status does not change, typing continues in accordance with the current standard input.

### Configuration
**Operating system:** Arch Linux x86_64

**Version of Telegram Desktop:** telegram-desktop-systemqt 1.2.1-2

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary) **I can go generate these later on if you like.**

</details>

**Additional info**: I know there are lots of similar existing reports, some open and some closed, but none of them match a keyword search against "UIM".

**Comment by Alkaris** [comment]
A similar issue to this was written up before in issues #442 #3443 
There was a written solution before, but I can't seem to find it.

**Comment by aphirst** [comment]
A small update on my side. Arch now provides telegram-desktop in the main repos, which as far as I understand are by default built against system Qt. The issue persists.

**Comment by NgoHuy** [comment]
@aphirst  you must rebuild uim to recompile with new lib. I can type with uim on telegram-desktop from official Arch's repo.

**Comment by aphirst** [comment]
This issue has graduated to applying to the stable versions of both telegram-desktop and uim.

```
extra/uim 1.8.8-2 [installed]
community/telegram-desktop 1.2.21-1 [installed]
```

Japanese via UIM (+Anthy) now works, but AltGr+[+aeiou no longer produces äëïöü. (Similarly other diacritics like ãōê etc.)

**Comment by aphirst** [comment]
As can be seen, I've reported this upstream, but the fact that only Telegram is affected suggests that the problem is a complex interaction of how both Telegram and UIM work.

**Comment by Alkaris** [comment]
You're probably better off using `ibus` + `ibus-anthy` for the time being, it has less issues regarding Unicode characters, and can still use extra Unicode characters. I like to assign the Right-Win Key as my Compose Key in my keyboard settings. Additionally you can enter unicodes like so;

<kbd>Ctrl</kbd>, <kbd>Shift</kbd> + <kbd>u</kbd> and enter the unicode input mode, then type the unicode number of that character that you want. Like for example äëïöü -> U+00E4, U+00EB, U+00EF, U+00F6, U+00FC.

You'll know when you're in Unicode input mode as you'll get a lowercased <kbd>u</kbd> that is underscored then type in the Unicode number and hit <kbd>Enter</kbd>, don't worry about trying to enter uppercase letters of the Unicode, it's not case sensitive.

**Comment by aphirst** [comment]
Changing from UIM to ibus is maybe a possibility, but I really don't want to have to change my "normal" typing workflow (i.e. for English and German). I've gotten very comfortable how I am, and have so little need for anything outside the UK-intl layout that a compose key still seems to me totally superfluous.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2013 generic bug.
