### ISSUE TITLE
unable to type new lines in channel's edit message popup window

### ISSUE THREAD

**Issue by rindeal** [telegramdesktop/tdesktop#4203]
### Steps to reproduce
1. create a channel
2. type some message and post it
3. right-click on it and select edit
4. type <kbd>Enter</kbd> or <kbd>Ctrl</kbd>+<kbd>Enter</kbd> 

### Expected behaviour
You can add new lines

### Actual behaviour
You can't add new lines

### Configuration
**Operating system:**
Linux-based

**Version of Telegram Desktop:**
1.2

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by MasterGroosha** [comment]
I guess `Shift+Enter` is what you need.
