### ISSUE TITLE
Voice messages playing status is not displayed

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#4205]
### Steps to reproduce
1. Send voice messages
2. Play it

### Expected behaviour
Playing status should be displayed

### Actual behaviour
![2017-12-19 13-54-36-693](https://user-images.githubusercontent.com/1321838/34156295-3b622c98-e4c5-11e7-93ec-dd47cd262a10.gif)

### Configuration
**Operating system:** Windows 7, Arch Linux

**Version of Telegram Desktop:** 1.2.3 alpha

**Used theme**: Any

**Comment by john-preston** [comment]
@aNNiMON Thanks for your report. This will be fixed in the next version.
