### ISSUE TITLE
Prefer system-wide emoji font over baked-in Qt resource

### ISSUE THREAD

**Issue by kdex** [telegramdesktop/tdesktop#4206]
Currently, `telegram-desktop` uses a Qt resource that contains a set of Apple emoji which are copyrighted by Apple. In terms of legal regulations, this might already be problematic, but I'm opening this issue for an entirely different reason: Some operating systems already provide a set of emoji that the user *prefers*. Telegram should respect that.

I'm currently using Arch Linux's `extra/noto-fonts-emoji` package which provides Google's emoji set. Other popular choices are Twitter's twemoji or EmojiOne.

My `telegram-desktop` executable doesn't currently have full coverage over the set included in the Apple resource for all Unicode 10.0 emoji, hence some of the emoji that I'm receiving from other users aren't rendered properly and may look like this:

![screenshot_20171219_182433](https://user-images.githubusercontent.com/4442505/34170142-129f2066-e4ea-11e7-83a4-c75ace79d8e1.png)

If I copy this message and paste it into any other application (e.g. `chromium`), I can see the emoji displayed with Google's Noto font just fine.

![image](https://user-images.githubusercontent.com/4442505/34170295-a25c6970-e4ea-11e7-8eac-004ef13be4b1.png)

As you can see, Telegram isn't trying to render emoji in another font where the glyph is available.

Of course, I could just wait until a newer version of `telegram-desktop` gains full coverage over the current set of emoji defined by the Unicode Consortium, but that's not a long-term solution for the underlying problem.

Could you maybe prefer the system font over the Qt resource and use yours only as a fallback? It should really be a matter of user preference.

(This problem also exists on Android, where the user can select Noto-styled emoji but sees Telegram rendering the Apple-styled emoji set, but I'm only mentioning this for sake of completeness, as I acknowledge that this repository is about `telegram-desktop`.)

### Configuration
Arch Linux, Kernel 4.14.6-1

**Version of Telegram Desktop:**
1.1.23

**Used theme**:
Night mode

**Comment by john-preston** [comment]
@kdex I don't know how to make Qt respect your system fonts in this case. If an emoji isn't replaced by myself (like it happens with the new emoji) I do not choose anything regarding the fonts and Qt is welcome to fallback to system fonts which have requested characters. But (as you can see on your screenshot) it doesn't, so currently if I disable my emoji you'll just be left without emoji at all :(

**Comment by kdex** [comment]
@john-preston Hm. Here's a window in Qt with a single `QLabel` that contains an emoji character. Qt uses my system font without further setup indeed:

![image](https://user-images.githubusercontent.com/4442505/34172469-6a9fc2b8-e4f2-11e7-9842-dd01b3ab3aa3.png)

I guess this is not an issue with Qt then…? 🤔

**Comment by john-preston** [comment]
@kdex Yes, perhaps it is issue with my usage of Qt or with my build of Qt :(

**Comment by kdex** [comment]
Colored characters are actually a fairly new thing. Qt has only been supporting those since version 5.7. But even if you're below 5.7, Google's Noto font still provides monochrome variants of each and every emoji, so that's what I should be seeing in Telegram instead.

Just for reference, I didn't do anything special in Qt:

#### mainwindow.ui
```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>MainWindow</class>
 <widget class="QMainWindow" name="MainWindow">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>400</width>
    <height>300</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>MainWindow</string>
  </property>
  <widget class="QWidget" name="centralWidget">
   <widget class="QLabel" name="label">
    <property name="geometry">
     <rect>
      <x>130</x>
      <y>60</y>
      <width>141</width>
      <height>18</height>
     </rect>
    </property>
    <property name="text">
     <string>This is a text label 🙄</string>
    </property>
   </widget>
  </widget>
  <widget class="QMenuBar" name="menuBar">
   <property name="geometry">
    <rect>
     <x>0</x>
     <y>0</y>
     <width>400</width>
     <height>30</height>
    </rect>
   </property>
  </widget>
  <widget class="QToolBar" name="mainToolBar">
   <attribute name="toolBarArea">
    <enum>TopToolBarArea</enum>
   </attribute>
   <attribute name="toolBarBreak">
    <bool>false</bool>
   </attribute>
  </widget>
  <widget class="QStatusBar" name="statusBar"/>
 </widget>
 <layoutdefault spacing="6" margin="11"/>
 <resources/>
 <connections/>
</ui>
```

Didn't even touch the actual code; so I'm confused why this isn't working for you. Do you have an emoji font installed on your system that Qt can use?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/90 ?

**Comment by Aokromes** [comment]
#3966 ?

**Comment by mirh** [comment]
I'm not sure how much this is the point OP wanted, but I had some channels with titles like "🇩 🇮 🇸 🇫 🇹 🇦 🇳 🇹 🇪" that indeed weren't being displayed properly. 
I installed noto-fonts-emoji and everything was working perfectly.
