### ISSUE TITLE
Feature request: Reply shortcut

### ISSUE THREAD

**Issue by 0e4ef622** [telegramdesktop/tdesktop#4208]
Something like ctrl+up/down would be really useful.
I made a simple patch (https://github.com/0e4ef622/tdesktop/commit/02221b9e64279686c368e6b46c3ae596d68dda28), and me and my friends find it very useful, but I read that you don't accept pull requests with new features, so it's there as a reference to what it should do.

**Comment by anfimovir** [comment]
Please send it via Pull requests: https://github.com/telegramdesktop/tdesktop/pulls
