### ISSUE TITLE
Forwarded video message can't played by the sender

### ISSUE THREAD

**Issue by sadalhayat** [telegramdesktop/tdesktop#4213]
### Steps to reproduce
1. Forward a video message to contact/group/channel (don't forward to Saved Message).
2. Play the the video message by **yourself**.
you can get video message from https://t.me/videomessages

### Expected behaviour
should be played normally.

### Actual behaviour
It opens thumbnail photo in full screen.

![image](https://user-images.githubusercontent.com/18193764/34212393-c34f784a-e5ce-11e7-8eb5-bff86bec586d.png)

### Notes 
• restart TDesktop will resolve it.
• no problem if video message forwarded to Saved Messages.
• no problem on TDesktop 1.2.1 Stable
• recipient can play the video message normally.

### Configuration
**Operating system: Windows 10 x64**

**Version of Telegram Desktop: 1.2.3 Alpha**

**Used theme**: default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by RememberTheAir** [comment]
@sadalhayat I think it's the same problem described in #4202

**Comment by sadalhayat** [comment]
maybe, I'm not sure.
the bug still happened with GIF Autoplay enabled.

**Comment by john-preston** [comment]
@sadalhayat Thanks for the report. That'll be fixed in the upcoming version.
