### ISSUE TITLE
Telegram desktop app changes laptop screen brightness

### ISSUE THREAD

**Issue by ilyagrigoryev** [telegramdesktop/tdesktop#4214]
I have an issue wherenever I open the telegram desktop app, it causes my windows laptop to change the screen brightness and it is annoying me. I have tried disabling adaptive brightness under my power options but still it doesn't solve the problem.

**Steps to reproduce:**
Make the active window of telegram. 
**Expected behaviour:**
Nothing.
**Actual behaviour:**
Change the screen brightness.
**Operating system:**
Windows 8.1 and 10. 
**Version of Telegram Desktop:**
1.2.6 (and earlier)
**Used theme:**
Night mode.

**Comment by MattRh** [comment]
Confirm. Have same issue

**Comment by stepanov-rt** [comment]
Confirm

**Comment by 3beanzz** [comment]
Confirm.
And it's really irritating because my CPU starts going nuts at the same time.

**Comment by argentmize** [comment]
Да, проблема наблюдается.
Windows 10. Адаптивная подсветка отключена.

Если свернуть окно, то яркость возвращается к начальному состоянию. Разворачиваю - яркость снова прибавляется.

**Comment by astridsoraya** [comment]
Confirm

**Comment by Terrev** [comment]
Found the issue for me - Avast auto detected it as a game, and was changing the power mode automatically (and thus brightness) when it was on-screen. _Ugh._

![image](https://user-images.githubusercontent.com/21133460/40638437-eba5876a-62d0-11e8-877c-3280647db3c0.png)

![image](https://user-images.githubusercontent.com/21133460/40638439-efcdd5e0-62d0-11e8-89a4-72d29c1aa291.png)

**Comment by MattRh** [comment]
@Terrev, God, you are right. Same avast bug

**Comment by auchri** [comment]
@MattRh 😆😆😆

**Comment by stek29** [comment]
Contacted Avast about this issue

**Comment by cubanism** [comment]
avast never fixed the issue! weird
thanks for the solution

**Comment by galihboy** [comment]
This is what i do to make it normal.
1. Open on setting menu "Change brightness level".
2. Scroll down and find "Graphic Settings".
3. On menu "Set an app to set preference", choose "Universal app".
4. And on "Select an app" menu, choose Telegram Desktop, then click Add button.
5. Click "Options", and set graphic preference to Power saving.
6. That's all.

**Comment by alexeinemkov** [comment]
> 
> 
> This is what i do to make it normal.
> 
>     1. Open on setting menu "Change brightness level".
> 
>     2. Scroll down and find "Graphic Settings".
> 
>     3. On menu "Set an app to set preference", choose "Universal app".
> 
>     4. And on "Select an app" menu, choose Telegram Desktop, then click Add button.
> 
>     5. Click "Options", and set graphic preference to Power saving.
> 
>     6. That's all.
> 
> 
> If the thing still happen, and you use AVAST antivirus, change the performance setting.
> 
>     1. Open AVAST settings.
> 
>     2. Choose Performance menu.
> 
>     3. In section "Do Not Disturb Mode", if you see Telegram Dekstop app on the list, remove it.
> 
>     4. Done.

I haven't AVAST and first method not working for me. Telegram desktop on Windows 10  still changes laptop brightness.
