### ISSUE TITLE
Send image - activate SEND X file button or set focus in Caption

### ISSUE THREAD

**Issue by anfimovir** [telegramdesktop/tdesktop#4217]
Telegram Desktop 1.2.1
Windows 10 Pro

Step to reproduce:
Simple open chat and click icon for send image, after open "confirmation box", button: SEND 1 FILE - not active, for send it need click mouse, please add support send via simple click: Enter

Or:

After open "confirmation box" set focuse in Caption, after click caption - send via Enter working correctly.

At this moment focus in this box - not set.

![send_image](https://user-images.githubusercontent.com/10336636/34237997-8928a4ba-e610-11e7-9c17-ce4e06c5e46e.PNG)

**Comment by anfimovir** [comment]
@john-preston Hmm, may be already fixed in?
https://github.com/telegramdesktop/tdesktop/commit/3f751bfbb07aea75d57ac91bf5de9578dc9d0b64

**Comment by anfimovir** [comment]
@john-preston Hmm, may be already fixed in?
https://github.com/telegramdesktop/tdesktop/commit/3f751bfbb07aea75d57ac91bf5de9578dc9d0b64

**Comment by anfimovir** [comment]
@john-preston Hmm, may be already fixed in?
https://github.com/telegramdesktop/tdesktop/commit/3f751bfbb07aea75d57ac91bf5de9578dc9d0b64

**Comment by john-preston** [comment]
@anfimovir I hope so.
