### ISSUE TITLE
Autostart on Linux

### ISSUE THREAD

**Issue by TheAppService** [telegramdesktop/tdesktop#422]
Hello,

could you perhaps add the function to let telegram autostart on Linux? And also an Option to start it minimized so it only appears in the bar on top(Ubuntu)?

Thanks

Daniel

**Comment by auchri** [comment]
#407

**Comment by auchri** [comment]
Added with 0.7.10, pls close

**Comment by Zranz** [comment]
I don't think it has been added. There is no option in Settings, and when starting it automatically opens the main window. 

Do I need to start it with some option?

**Comment by auchri** [comment]
yes, try `-startintray` commandline option

**Comment by Zranz** [comment]
It doesn't work properly with the commandline option. Although it indeed starts minimized, there is no way afterwards to open the chat window, and I have to close Telegram and reopen 
(without the command line) if I want the program to work normally.

**Comment by auchri** [comment]
You don't have a tray icon?

**Comment by Zranz** [comment]
I do have a tray icon, but clicking in "Open Telegram" on the tray icon does nothing. Only quit works.
This is the log I get when opening from command line with the -startintray option (which by the way, is the same without any parameters too):

libs init..
loading appindicator3 with version 1..
loaded appindicator3 with version 1!
loading gtk-3 with version 0..
loaded gtk-3 with version 0!
loaded gtk funcs!
loaded appindicator funcs!
status icon api loaded
loading unity with version 9..
loaded unity with version 9!
unity count api loaded
FT_New_Face failed with index 0 : 1
FT_New_Face failed with index 0 : 1
FT_New_Face failed with index 0 : 1
FT_New_Face failed with index 0 : 1
FT_New_Face failed with index 0 : 1

**Comment by TheAppService** [comment]
Yes,

what he says is right(I've just tried it). I hope that it get fixed soon.

**Comment by sojusnik** [comment]
Please implement an option to have Telegram started in the system tray on startup.

**Comment by TheAppService** [comment]
Okay fixed (The option with -startintray)

**Comment by Zranz** [comment]
It works with an odd behaviour in version 0.7.17. 

So after starting from command line with the -startintray option, tray icon is unresponsive to "Open Telegram". One has to first click on "Minimize to tray", and after that to "Open Telegram" to be able to see the main window.

Thanks for the fix in any case.

**Comment by sojusnik** [comment]
How exactly should the proper command look like to start Telegram in the tray?

As for now, under Telegram 0.7.17 and Ubuntu Gnome 14.10, the following isn't working, because Telegram just opens the normal way:

[your_directory]/Telegram -- %u -startintray

**Comment by Zranz** [comment]
[your_directory]/Telegram -startintray

works for me. As I said, with odd behaviour (1st click open telegram, 2nd click minimize telegram, 3rd click open telegram and it finally opens).

**Comment by sojusnik** [comment]
With

[your_directory]/Telegram -startintray

starts focused, but the content of the window is completely black, see yourself: https://mega.co.nz/#!CgwlgJgJ!HChH7BhLdw1liUuWUaWFAxECU6uGkRtuuJ6SeT_VV2Q

Is there a way to reopen this issue, since the minimized startup process is still buggy?

**Comment by Hypfer** [comment]
This option doesn't work with 0.9.15

**Comment by Cysioland** [comment]
It's also buggy for me.

**Comment by Varentsov** [comment]
Still there

**Comment by sakralbar** [comment]
+1, ubuntu 16.04.1

**Comment by skylevels** [comment]
+1 
Ubuntu 16.04.1 x32

**Comment by wirthual** [comment]
+1 Ubuntu 16.04.1 with Telegram 0.10.11

**Comment by garridev** [comment]
still happens...

**Comment by dimon2242** [comment]
Please, fix it!
Ubuntu 16.04.2

**Comment by SnuggIes** [comment]
I've demonstrated @Zranz's bug in a reply to here: #3391 
Hopefully this helps. c:

**Comment by abixadamj** [comment]
Strange behaviour on Mint 18.2 64bit
I have Installed 1.2.6 version yesterday. Everything works perfectly. I have checked 'Show tray icon' and Telegram runs OK. I have added Telegram to Autostart in Mint. Today I have started computer, and Telegram opened in normal windows, without system tray icon.
When I go to Preferences, uncheck 'Show tray icon" and then check it again, icon apperad in tray.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/2a9023479faeadc6b63c640c0f43dee14f831307

**Comment by 1v** [comment]
Not working for me.
Ubuntu 19.10
Telegram 2.0.1
Launch minimized also not working.
