### ISSUE TITLE
[Feature Request] Add an option to search for sticker packs

### ISSUE THREAD

**Issue by VitinhoCarneiro** [telegramdesktop/tdesktop#4220]
It just so happens that many users like me love to add tons of cool custom sticker packs to their collection.

But with so many packs, it becomes a hassle to search for a specific sticker pack. You have to **_literally_** spend **minutes** scrolling through hundreds of tabs until you find the specific pack you want. Emoji search does not work that well if you want to search for a specific pack within 200+ packs. It gets really inconvenient to use stickers like this. 

It would be nice if we could **_search for sticker packs by name_**. And even better, **_attribute tags to stickers/packs we add_** so we can find them by searching for those tags.

This is a request not only for the Desktop client, but also for all of the other clients.

**Comment by stek29** [comment]
> This is a request not only for the Desktop client, but also for all of the other clients.

which makes it invalid :(

However, I don't think that searching for packs by name is :)

**Comment by jvschiavo** [comment]
@stek29 Sorry, I don't get it. Why is it invalid? Letting sticker pack creators atribute names/tags to each sticker would be a great way to search it fast!

**Comment by stek29** [comment]
Invalid for this repo I mean

**Comment by jvschiavo** [comment]
@stek29 Thanks. But what would be the correct repo then?

**Comment by stek29** [comment]
@jvschiavo Telegram's Twitter or in-app support

**Comment by jvschiavo** [comment]
Sorry, but I do not agree with you... But thanks anyway, you are a very active member.

**Comment by EmuAGR** [comment]
This was added into the Android version, maybe it's time to add it to the desktop tone. :)

**Comment by 23rd** [comment]
It seems that the search for stickers has been working for a long time.
