### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by MetaiR** [telegramdesktop/tdesktop#4222]
hello,
sometimes downloading files hangs on 1 last MB (or less) and isn't completed and I have to redownload the file again
it's happened to me several times, for small ones, no matter but for the big ones, it's really bothering.
for example: 

![image](https://user-images.githubusercontent.com/7807264/34259047-efc5a05a-e675-11e7-8b6f-4f9a9d6ba6a7.png)

**Comment by auchri** [comment]
Use the template please.
