### ISSUE TITLE
Name on sign messages on channel aren't showing

### ISSUE THREAD

**Issue by sadalhayat** [telegramdesktop/tdesktop#4223]
### Steps to reproduce
1. open a channel which Sign Messages enabled,
check https://t.me/belajarnetworking
2. Find the author name on messages

### Expected behaviour
the author name should shown.
no problem on TDesktop 1.2.1 Stable.

![image](https://user-images.githubusercontent.com/18193764/34262057-c8a0371a-e69d-11e7-9f8f-759e65c00af0.png)

### Actual behaviour
the author name isn't showing.

![image](https://user-images.githubusercontent.com/18193764/34261983-8e49f90c-e69d-11e7-8979-11ca1262c1c0.png)

### Configuration
**Operating system: Windows 10 x64**

**Version of Telegram Desktop: 1.2.3 Alpha**

**Used theme: default**

</details>

**Comment by ThigSchuch** [comment]
Right, it shows a comma instead.

Same SO and Version here.

**Comment by FawLog** [comment]
It works corrects for me on 1.2.3 alpha, that has been compiled from the dev branch. Seems that this issue has already been fixed and that the binary version of the 1.2.3 alpha older than the current dev branch. 
![default](https://user-images.githubusercontent.com/12209745/34323584-17408aa4-e861-11e7-84c7-22691341832e.png)

**Comment by sadalhayat** [comment]
Thanks @ThigSchuch and @FawLog
