### ISSUE TITLE
Enhancement: Timestamped view

### ISSUE THREAD

**Issue by eyalroz** [telegramdesktop/tdesktop#4224]
I'm using Telegram Desktop v1.2.1 (on a Linux Mint 18.3)

When looking back through chat logs, I would like to be able to see timestamps, not just by hovering for a long while over an individual message's HH:MM time, but for all messages. 

For that purpose I would like to have either a global or (better yet) per-channel setting which replaces the HH:MM faded-color timestamps with a clearer, start-of-bubble, full timestamp. Still better if one could configure which fields go on the timestamp.

Note: This is an orthogonal issue from being able to export a log, where a timestamp is also important. I'm talking about the main window.

**Comment by Aokromes** [comment]
#2705
