### ISSUE TITLE
Show in folder not opening correct folder

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#4225]
1. `Save Voice message as...`
2. Choose a folder which is not `~/Downloads/Telegram Desktop`
3. Save the file
4. `Show in folder`

I expect Telegram Desktop to open the folder selected in `2.` and not `~/Downloads/Telegram Desktop`.

Tested on Linux mint 18.3 Cinnamon with Telegram Desktop `1.2.1`.

Can someone confirm this?

**Comment by ThigSchuch** [comment]
Working here, Windows 10 Telegram Alpha v1.2.3

**Comment by orschiro** [comment]
@ThigSchuch thanks for attempting to reproduce! I just tried it again and this time it worked. Please disregard.

**Comment by orschiro** [comment]
Sorry, have to reopen this issue. It's still happening, although not always. Need more people to test and reproduce, please.

**Comment by aNNiMON** [comment]
Linux Mint 18.3 Cinnamon, Telegram Desktop 1.2.3 alpha, show in folder works fine.

**Comment by d0tfile** [comment]
Arch Linux (4.14.8-1-ARCH, x86_64), Telegram Desktop 1.2.1. `Show in folder` works fine with both `Save file as...` and simple downloading.

**Comment by orschiro** [comment]
Thank you! The issue must be on my side...Will report back if I find the cause.
