### ISSUE TITLE
 [Feature Request] Add an option to show only nickname in groups

### ISSUE THREAD

**Issue by cialu** [telegramdesktop/tdesktop#4226]
Hi, only a feature request if it's possible.

An option to show nickname in groups and name/surname in conversation because is useful to show full name and surname in normal conversation for work and official communications, but not ever in groups. What do you think about?

Regards.

**Comment by MasterGroosha** [comment]
What about people without usernames?

**Comment by cialu** [comment]
@MasterGroosha an option means you can use it or not. If you don't have username, option is also not selectable.

**Comment by MasterGroosha** [comment]
Ah, you mean "show your username instead of name". Misunderstood, sorry. Thought about other participants.

Anyway, this can lead to inconsistency for people who speak to you both in PM and in group. What if you change your username and avatar?

**Comment by cialu** [comment]
People who speak to you both in PM and in group know you, also by avatar.

> What if you change your username and avatar?
I not see any matter.

**Comment by MasterGroosha** [comment]
Also this "feature" should also been ported to Android, iOS, macOS, Windows Phone and Web versions, you know? Otherwise it leads to inconsistency across platforms.

**Comment by stek29** [comment]
If you want users to choose if their name or username should be shown for others, then it's an API issue.

If you want users to choose if they want to see names or usernames of others, then it's an enhancement (which I don't think is worth it tbh)

**Comment by cialu** [comment]
@stek29 the idea is to give users an option to choose if their name or username should be shown for others in groups. So, it's an API issue.

**Comment by stek29** [comment]
@cialu Report in via in-app support or via Twitter then

**Comment by cialu** [comment]
@stek29 ok, thank you.
