### ISSUE TITLE
Unable to create group

### ISSUE THREAD

**Issue by Yanpas** [telegramdesktop/tdesktop#4228]
### Steps to reproduce
1. Create group
2. Choose name
3. Select 2 mates

### Expected behaviour
New group is created

### Actual behaviour
nothing happens. stderr is empty

### Configuration
**Operating system:**
ubuntu 16.04
**Version of Telegram Desktop:**
1.2.1

**Comment by Yanpas** [comment]
Same story on iOS : it shows "an error occured". Seems to be a backend issue.

**Comment by stek29** [comment]
You're likely limited
Try doing it via Webogram and look at the error returned.
