### ISSUE TITLE
Clicking on tray icon and selecting Open Telegram don't brings Telegram window in front when it's behind other window(s)

### ISSUE THREAD

**Issue by ectatomma** [telegramdesktop/tdesktop#4229]
### Steps to reproduce
1. Open a Telegram window
2. Open another program, maximized
3. Click on telegram tray icon
4. Click on Open Telegram
5. Click on Telegram on the taskbar (panel)
6. Bring to focus another window
7. Click again over telegram on the taskbar (panel)

### Expected behaviour
When clicking Open Telegram on the tray icon when the Telegram window is behind other windows, the Telegram window should come to focus in front of all other windows

### Actual behaviour
When clicking Open Telegram on the tray icon, Telegram window is on focus but remains hidden behind other windows and it's not possible to bring it in front clicking on Telegram on the taskbar (panel). It's necessary to switch to another window and clicking again on Telegram on the taskbar (panel) to bring it in front.

### Configuration
**Operating system:**
Xubuntu 17.04 Linux 4.10.0-42-generic #46-Ubuntu SMP Mon Dec 4 14:38:01 UTC 2017 x86_64 GNU/Linux. XFCE4 desktop manager.
 
**Version of Telegram Desktop:**
1.2.1

**Comment by brainplot** [comment]
This is very similar to what happens to me, but there are some minor differences. Clicking on the tray icon doesn't bring up the window, which remains hidden behind all the other open windows.
However, I can get the Telegram window to come up if I click on the icon in the taskbar _twice_.

The following things happen when the system tray icon is clicked:

1. the Telegram icon appears in the taskbar as the currently-focused window but the window doesn't show up and remains "hidden" behind all the other windows.
1. clicking on the icon in the taskbar the first time makes Telegram loose the focus, which is given to the app that previously had the focus.
1. clicking on the icon in the taskbar the second time finally gives the focus back to Telegram and the window does show up this time.

The issue described above doesn't occur when all other windows are minimized.

**Operating system:**
Archlinux mars 4.17.11-arch1 #1 SMP PREEMPT Sun Jul 29 10:11:16 UTC 2018 x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.3.10 (that is the latest provided by the distro to this date)

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
