### ISSUE TITLE
[Feature Request] Add option to hide system tray on Ubuntu

### ISSUE THREAD

**Issue by korg91** [telegramdesktop/tdesktop#423]
It seems that it's not possible to blacklist an app-indicator on Ubuntu if it is hard-coded into the program (see http://askubuntu.com/a/79547/220829).
Would you please add this option in Settings?

**Comment by nevik** [comment]
You can already disable it in the settings page, the option is marked in this screenshot:

![screenshot - 01232015 - 03 29 27 pm](https://cloud.githubusercontent.com/assets/1099818/5876128/cdb6fc9a-a314-11e4-9390-7bd62217b229.png)

**Comment by korg91** [comment]
Ahah you marked the wrong option :)
Anyway, I don't know if the option was available when I opened this issue, but now it is. Thanks.
[closed]

**Comment by nevik** [comment]
whoopsie :D

fixed it ;)
