### ISSUE TITLE
Dedicated icon in Cinnamon sound application menu?

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#4231]
1. Installed `1.2.1-0ubuntu0` from [ppa:atareao/telegram](https://launchpad.net/~atareao/+archive/ubuntu/telegram)
2. Use Linux Mint 18.3 Cinnamon
3. Miss the below icon.

Is this a problem with the ppa package or upstream?

![image](https://user-images.githubusercontent.com/170947/34324873-17643182-e881-11e7-9610-64b60eb60c72.png)

**Comment by cranes-bill** [comment]
Just for the record: i dont't have this problem, but my system is not Linuxmint.
![capture du 2017-12-29 15 42 06](https://user-images.githubusercontent.com/5161278/34438440-a16731c2-ecaf-11e7-97cf-4e19b7e2c0c0.png)

**Comment by orschiro** [comment]
Thanks @cranes-bill.

- What version of Telegram Desktop are you using?
- How did you install it?
- May it be a problem with the PPA package?

**Comment by orschiro** [comment]
Can confirm the problem lies with the PPA mentioned in my original post. 

I tried the binary from https://telegram.org/dl/desktop/linux and there it shows the icon correctly. 

Will close this issue as invalid.

**Comment by orschiro** [comment]
Reopening this issue. @cranes-bill the icon you are seeing, is this a generic one on your system?

I am wondering if we can provide a dedicated sound icon for Telegram to distinguish it more easily from other apps. It is certainly possible if you look at VLC.

![image](https://user-images.githubusercontent.com/170947/34455560-c65fac16-ed81-11e7-864a-91fadaecf059.png)

**Comment by cranes-bill** [comment]
Yep, it is generic icon but i think it is the same on any desktop environment.

**Comment by orschiro** [comment]
Yes, seems to be the same on all desktops. Can we add a dedicated Telegram icon?

The Gradio app shown above has recently added one. So it must be possible. 

And it looks so much more distinguishable. 😊

![image](https://user-images.githubusercontent.com/170947/34460147-1b5f45fc-ee07-11e7-99aa-cf07b1ffe546.png)

**Comment by cranes-bill** [comment]
It should be implemented in the source.
Ref.: https://www.freedesktop.org/software/pulseaudio/doxygen/proplist_8h.html#aee165f0d3f2808271ee4e43e880bd7ed

**Comment by orschiro** [comment]
> It should be implemented in the source.

I would like to request this. What is the source of Telegram Desktop?

**Comment by cranes-bill** [comment]
Sorry if you did not understand me correct, my English is very bad!
I meant that in order to display the dedicated icon, the relevant function must be implemented in Telegram source, but that's only depends on the owners.

**Comment by orschiro** [comment]
> Sorry if you did not understand me correct, my English is very bad!

No, I completely understood you! :-)

> I meant that in order to display the dedicated icon, the relevant function must be implemented in Telegram source, but that's only depends on the owners.

Yes, I understand that. Where is this Telegram source? Is it public? To whom to raise this concern?

**Comment by stek29** [comment]
@orschiro You're asking where is Telegram source in comments to issue at repo with it?..

**Comment by auchri** [comment]
![mega facepalm](https://user-images.githubusercontent.com/5092164/34467276-a54287ee-eeec-11e7-8db5-39994e5e8194.gif)

**Comment by orschiro** [comment]
Haha, sorry, guys. I think I did not explain clearly. :-) 

My question was whether the required change mentioned by @cranes-bill needs to be implemented in Telegram Desktop (this repo) or whether there exists another source (other repo) that Telegram Desktop uses.

**Comment by stek29** [comment]
#2740
