### ISSUE TITLE
Select multiple recipients when forwarding a message

### ISSUE THREAD

**Issue by C-A-T9LIFE** [telegramdesktop/tdesktop#4232]
### Expected behaviour
Select multiple recipients when forwarding a message
for example, when the Ctrl key is pressed

### Configuration
Windows 10

1.2.3

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by C-A-T9LIFE** [comment]
![capture20171224140123251](https://user-images.githubusercontent.com/16851877/34326447-c2507186-e8b4-11e7-85e0-e3645380924d.png)

**Comment by Aokromes** [comment]
#1841
