### ISSUE TITLE
Upload & Downloading Speed Issue

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#4237]
### Steps to reproduce
1. Using either Telegram for iPhone, Android, Telegram Desktop for Windows or Linux, try to upload a video or a large image (1MB or bigger)
2. The speed at which it uploads or downloads from the receiving end is very slow (Between 50KB/s to 150KB/s). The upload is around 50/150KB/s and the download is between 300KB to 1.1MB.
3. This mostly happens with videos and large images. Small images (1MB or Less) do get transfer quickly, even doing multiple of them, they get transferred in a fast time.

### Expected behaviour
It should upload at least I would think at 50% the upload speed (worse case scenario) of my ISP provider or more and it should download at 50% the download speed (again worse case scenario) of my ISP provider or more.

### Actual behaviour
It uploads at around 8x slower (My upload is 10Mbps or 1.25MB/s) and downloads about 5x to 10x times slower (My download speed is 100Mbps or 12.5MB/s) than the real download speed. I have tested way too many times my speed with fast.com or downloading linux distributions, downloading games or updates through steam, servicing files to my development team and even streaming 4k so the download and upload are fine. The single point of failure is telegram when it comes to uploading and downloading files. Now this does not affect me alone since I took my time over the past 4 months to test this throughly including with a testing team for this that cares for Telegram with 42 users (including myself), divided in my working development team and family members in Canada (Ottawa), USA (Chicago, Orlando, Houston, Los Angeles, Detroit, Philadelphia & Seattle), Venezuela (Maracaibo & Caracas), Chile (Santiago), Colombia (Bogota & Medellin), Costa Rica (San Jose, Curridabat & San Rafael), Mexico (Ensenada), UK (London), Australia (Sydney) and Spain (Madrid & Toledo). Without any exception during this time period, everyone had the same upload and download issue on Desktop, iPhone and Android versions.

### Configuration
**Operating system:**
Ubuntu (From 16.04 to 17.10). Windows 7 to 10.

**Version of Telegram Desktop:**
1.2.1

**Used theme**:
Default

With this said, how can I help in finding out the specific issue that is causing this to happen. It should add that I tested Whatsapp (Had to install it again to do a quick test) and it did in fact upload at the correct speed (From 1.25MB/s I was uploading at around 900KB/s and downloading at 7MB/s) compared to the speeds mentioned above for Telegram. All of this tests range from 5Mbps speeds (Venezuela) to 250Mbps speeds (Spain for example). In my case I have 100 Download and 10 Upload.

Hope this helps and I can provide even more information since it took me several months to gather this information and coordinate with everything in testing the upload/download issues.

**Comment by MasterGroosha** [comment]
Could you please try the following:
• Start uploading large file (~100mb)
• Try to upload another file (any size), which will be placed in queue

The question is: will large file be uploading faster with other file in queue or not? It's a very strange issue, but maybe something is wrong with TDesktop. Check #2390

**Comment by Aokromes** [comment]
"Using either Telegram for iPhone, Android, Telegram Desktop for Windows or Linux, try to upload a video or a large image (1MB or bigger)"

Then it doesn't belong to here if it afects all versions.

**Comment by luisalvarado** [comment]
@MasterGroosha OMG Yes. I did what you asked and it did upload faster. Why? I am closing this Ticket as a duplicate of that one.

DUPLICATE OF https://github.com/telegramdesktop/tdesktop/issues/2390

**Comment by 928122119** [comment]
The download speed recently from telegram is quite slow to 128kbps with file more than 3MB, (all surrounding connection is same as before), and test Telecom connection download speed is 55Mbps. 
This issue noises me a week already and still keep on going though I reset 4G+ internet with telecom conection.

**Comment by luisalvarado** [comment]
Thats because of the Coronavirus dude. Its not telegram. Is everything.
