### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#4239]
access key for pop up menus
![screenshot 39](https://user-images.githubusercontent.com/7231077/34356497-3cc99ae0-ea64-11e7-9c0c-cba2f2b41370.png)

**Comment by d0tfile** [comment]
Make title more informative and follow template please.

**Comment by SmartManoj** [comment]
How to quickly forward a message

**Comment by SmartManoj** [comment]
https://smartmanoj.blogspot.com/2018/10/telegram-shortcuts.html
