### ISSUE TITLE
window10 build

### ISSUE THREAD

**Issue by senlinms** [telegramdesktop/tdesktop#4242]
link /NOLOGO /DYNAMICBASE /NXCOMPAT /INCREMENTAL:NO /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST /MANIFESTFILE:"configure.intermediate.manifest" /OUT:..\..\configure.exe @C:\Users\admin\AppData\Local\Temp\configure.exe.13792.8734.jom
link: extra operand '/NXCOMPAT'
Try 'link --help' for more information.
jom: E:\WorkerWoker\WorkSpace\tdesktop\Libraries\qt5_6_2\qtbase\tools\configure\Makefile [..\..\configure.exe] Error 1

**Comment by auchri** [comment]
And whats the problem?

**Comment by senlinms** [comment]
build tdesktop , use this, 

git apply ../../../tdesktop/Telegram/Patches/qtbase_5_6_2.diff
cd ..

configure -debug-and-release -force-debug-info -opensource -confirm-license -static -I "%cd%\..\openssl\Release\include" -no-opengl -openssl-linked OPENSSL_LIBS_DEBUG="%cd%\..\openssl\Debug\lib\ssleay32.lib %cd%\..\openssl\Debug\lib\libeay32.lib" OPENSSL_LIBS_RELEASE="%cd%\..\openssl\Release\lib\ssleay32.lib %cd%\..\openssl\Release\lib\libeay32.lib" -mp -nomake examples -nomake tests -platform win32-msvc2015
