### ISSUE TITLE
Media view should be shown above the taskbar

### ISSUE THREAD

**Issue by nyuszika7h** [telegramdesktop/tdesktop#4244]
### Steps to reproduce
1. *(Not yet sure what specifically breaks this for me, since it's working as expected for the developer.)*
2. Send a photo with a caption or an album.
2. Open the media view by clicking one of the sent photos.

### Expected behaviour
The photo should fit on the visible area of screen and not extend down to the taskbar, which covers it.

### Actual behaviour
The bottom of the photo is covered by the taskbar, also causing the caption for individual images and part of the album thumbnails to be covered.

### Configuration
**Operating system:** Windows 10 Home x64 1703

**Version of Telegram Desktop:** 1.2.5 alpha

**Used theme**: Default (night mode)

**Comment by john-preston** [comment]
@nyuszika7h In my case the Media View window (fullscreen, with photo and caption at the bottom) is shown above the taskbar so it shows the caption correctly.

**Comment by nyuszika7h** [comment]
This seems to be fixed now.

**Comment by nyuszika7h** [comment]
Actually, now it works correctly for albums, but not for individual photos...

**Comment by nyuszika7h** [comment]
Okay, it must have been a temporary glitch, because restarting Telegram fixed it, now the taskbar doesn't cover the media view.
