### ISSUE TITLE
Comment is not added when sending multiple photos

### ISSUE THREAD

**Issue by nyuszika7h** [telegramdesktop/tdesktop#4245]
### Steps to reproduce
1. Select multiple images to send at once. (It doesn't matter if you choose to send them as an album or separate images.)
2. Write something in the "Comment" field.

### Expected behaviour
A caption should be added to one of the images or the comment should be sent as a separate message. (Ideally, you should be able to write a caption separately for each image before sending them.)

### Actual behaviour
The specified comment is not sent at all.

### Configuration
**Operating system:** Windows 10 Home x64 1703

**Version of Telegram Desktop:** 1.2.4 alpha

**Used theme**: Default (night mode)

**Comment by john-preston** [comment]
@nyuszika7h In my case the Media View window (fullscreen, with photo and caption at the bottom) is shown above the taskbar so it shows the caption correctly.

**Comment by john-preston** [comment]
@nyuszika7h It should be sent as a separate message before images. Can you check once more? It is sent before the images in my case.

**Comment by nyuszika7h** [comment]
Oh, yes, I missed that. It was sent with the separate photos option, but not when sent as an album. But it works fine now.
