### ISSUE TITLE
[Feature Request] Show (un)compressed image sizes before sending

### ISSUE THREAD

**Issue by MaggiR** [telegramdesktop/tdesktop#4247]
It would be great if the image sending dialog would show the size of an image, so that the user can decide to send the image compressed or uncompressed depending on the expected image size.

**Comment by john-preston** [comment]
You mean file size?

**Comment by MaggiR** [comment]
Yes, indeed. Since the image resolution is independent of its de facto quality (due to JPEG compression and other factors) it could be a misleading value. But it can be discussed to add an image resolution info too.
