### ISSUE TITLE
Allow using system fonts

### ISSUE THREAD

**Issue by Revertron** [telegramdesktop/tdesktop#425]
I personally hate any means of font-smoothing and antialiasing. Therefore I disable it everywhere.
In Telegram for Windows I have a very ugly font. Please, allow using system fonts.
![telegram_fonts](https://cloud.githubusercontent.com/assets/105154/5815391/71252120-a0a6-11e4-8289-bf87675d0cab.png)

**Comment by ezdev128** [comment]
It seems you have some problem with system fonts. I did not saw this problem on any linux distribution.

![telegram_about](https://cloud.githubusercontent.com/assets/10166012/5816007/788dbfac-a0ac-11e4-8255-19f7fa2cc11d.png)

**Comment by Revertron** [comment]
Just try to read more carefully that I wrote...

**Comment by telegramdesktop** [comment]
Well, this is how Open Sans looks with font smoothing disabled. I suggest you to enable at least Standard font smoothing (not necessary ClearType), so they could be antialiased. I don't know when custom fonts will be allowed.

**Comment by Revertron** [comment]
Like I said on non-retina displays _all_ fonts _with any font smoothing_ look very ugly. Therefore I don't use it. I wonder if anyone can see it?

**Comment by nortexoid** [comment]
Font smoothing doesn't totally work on linux, KDE 4. It could be an issue with Qt4. I see the same thing in some apps on KDE 5 (Plasma 5) using Qt5 (e.g. TeXstudio). Font smoothing works just fine with system fonts using KDE apps. Distribution: Kubuntu 14.10 and 15.10. I can upload screenshots if desired.

**Comment by smoothdeveloper** [comment]
![image](https://user-images.githubusercontent.com/87944/38653757-0dd69c3c-3dc1-11e8-89c7-b502e422052b.png) (windows 7, clear-type disabled)

This issue should be reopened, after last update to 1.2.17, the font became unreadable.

**Comment by john-preston** [comment]
@smoothdeveloper Nothing should've changed. Could you check some previous versions from this page:

https://github.com/telegramdesktop/tdesktop/releases

(downloading and testing Windows Portable, each one in its own folder) and see if it is really better in an old version? And which is the first one being bad?

**Comment by AngryPhantom** [comment]
Bumping up. I'm also having this issue. I always disable font smoothing and antialiasing and I'm using Debian 9 with MATE Desktop. It is perfect without font antialiasing: http://0x0.st/zTo6.png
I installed a special tool `qt5ct`, a configuration tool that sets styles and fonts for Qt5 applications and makes them look homogeneous in GTK environments (previously, there was a tool `qt4-qtconfig` for Qt4 apps).
After that, **any other Qt application** in the system looks identical to GTK apps, for e.g VLC: http://0x0.st/zTol.png
But, unfortunately, this is not the case with Telegram: http://0x0.st/zToU.png

My ~/.config/fontconfig is:

```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <match target="font">
  <edit name="rgba" mode="assign">
   <const>none</const>
  </edit>
 </match>
 <match target="font">
  <edit name="hinting" mode="assign">
   <bool>true</bool>
  </edit>
 </match>
 <match target="font">
  <edit name="hintstyle" mode="assign">
   <const>hintmedium</const>
  </edit>
 </match>
 <match target="font">
  <edit name="antialias" mode="assign">
   <bool>false</bool>
  </edit>
 </match>
</fontconfig>
```

Is it possible to do something with that? I guess a lot of users would be really grateful. Thank you!

**Comment by tamr** [comment]
Since the fonts are embedded, can't you simply patch it with hex editor? Win ex: https://i.imgur.com/NP5njvW.png

**Comment by AngryPhantom** [comment]
I've found a simpler workaround:
`XDG_CONFIG_HOME= /opt/Telegram/Telegram`

Mind the gap/space between `XDG_CONFIG_HOME=` and `/opt/Telegram/Telegram`.

Sorry, but I'm not good at patching/hexing. But why embed fonts? Why not use the system ones (or as a dependency)?
