### ISSUE TITLE
Can you make the Connecting... promopt not snatch the focus

### ISSUE THREAD

**Issue by t123yh** [telegramdesktop/tdesktop#4254]
### Steps to reproduce
1. Use an Input Method and enter something in the `Write a message...` box but don't commit what you've input like this: 
<img width="345" alt="default" src="https://user-images.githubusercontent.com/8972552/34440072-9ead8aba-eced-11e7-995d-70afd9eeacb8.png">
2. Disconnect your LAN cable.

### Expected behaviour
What you've input remains there, not disappearing.

### Actual behaviour
The IM disappears because the lost of the focus (grabbed by `Connecting...` prompt).
<img width="128" alt="default" src="https://user-images.githubusercontent.com/8972552/34440135-0912de46-ecee-11e7-9f8f-54e938157981.png">

We're under an unstable Internet connection. The connection drops every few seconds (though it can get reconnected automatically). But when the connection drops, what we've type is lost. Sometimes it's a long sentence, and we have to type it again from beginning, which is really painful. Could you please make the focus of the TextBox not lost, so the IM won't disappear?

### Configuration
**Operating system:** Manjaro Linux KDE with FCITX as the IM

**Version of Telegram Desktop:** 1.1.23

**Comment by john-preston** [comment]
@t123yh Please update to 1.2.1.

**Comment by t123yh** [comment]
@john-preston Oh, thanks. Is that solved in this version? The Arch User Repository remains version 1.1.23 so I haven't upgrade it yet.

**Comment by john-preston** [comment]
@t123yh There was a pull request about something like that, so perhaps it is fixed.

You can download the version from https://desktop.telegram.org and test it.

**Comment by t123yh** [comment]
Yeah it works! Thank you.
