### ISSUE TITLE
[Feature Request] Ability to remove mediafile from album before sending

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#4256]
### Steps to reproduce
1.  Paste several mediafiles from clipboard to start making an album
2.  Realize you want to exclude one mediafile from album 

### Expected behaviour
There should be a cross (`x`) button on mediafiles to exclude them from album before sending.

### Actual behaviour
You need to cancel sending an album and start making it from scratch.

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.2.5 alpha

**Comment by ThigSchuch** [comment]
Or you can drag it out of the borders.
Would be nice too.

Like
![image](https://user-images.githubusercontent.com/20743110/46477612-6613f680-c7c1-11e8-961b-329cce1afe0a.png)

**Comment by 23rd** [comment]
Implemented in v1.9.7.
