### ISSUE TITLE
Telegram crashes when typing a capital letter O into any chat.

### ISSUE THREAD

**Issue by gsuberland** [telegramdesktop/tdesktop#4259]
### Steps to reproduce
1. Type a capital letter O in any message.
2. Telegram crashes.

This is reproducible on my desktop. The first instance of it showed up on 2017-12-11. Cannot reproduce on another system.

I have tried all other letters and it is only a capital O (shift+o) that does it. Either shift key will do it.

This is honestly the weirdest bug I've ever reported to anyone.

### Expected behaviour
Types a letter 'O'.

### Actual behaviour
Crash.

### Configuration
**Operating system:** Windows 10 x64

**Version of Telegram Desktop:**  1.2.6

**Used theme**: Whatever the default is.

**Keyboard**: QWERTY, UK layout.

### Logs

Logs and crash dump:

- [crashdump.zip](https://github.com/telegramdesktop/tdesktop/files/1594591/crashdump.zip)
- [log_17_00.txt](https://github.com/telegramdesktop/tdesktop/files/1594593/log_17_00.txt)
- [mtp_17_00.txt](https://github.com/telegramdesktop/tdesktop/files/1594594/mtp_17_00.txt)
- [tcp_17_00.txt](https://github.com/telegramdesktop/tdesktop/files/1594595/tcp_17_00.txt)

**Comment by gsuberland** [comment]
I debugged the application and there's a thread that clearly caused the crash. EIP is zero, so it could be an event handler that isn't set, or something like that. ESP and EBP look sane but there's no memory at those addresses, so either my crash dump isn't picking those up or this is some kind of UAF.

Registers:

`EAX = D21799A8 EBX = 09F70095 ECX = 09F70000 EDX = 09F70000 ESI = 09F70095 EDI = 09F70000 EIP = 00000000 ESP = 0A9EFD2C EBP = 0A9EFD44 EFL = 00010246`

**Comment by gsuberland** [comment]
EIP is 00000000 for one thread. ESP and EBP look sane but there's no memory at those addresses. Something accidentally freed the stack, perhaps? Very odd.

**Comment by john-preston** [comment]
@gsuberland If you relaunch the app after crash does it offer you to send a crash report? If not please download the portable alpha version from https://desktop.telegram.org/changelog#alpha-version launch it, autoupdate it in Settings to 1.2.6 and reproduce the crash. After relaunch it should offer you to send a crash report. Please copy the Crash Report Tag here and submit the report.

**Comment by gsuberland** [comment]
I get a "Telegram didn't close properly" window on restarting the application, but it does not offer an option to send a crash report, nor did the alpha version offer to send a crash report.

**Comment by john-preston** [comment]
@gsuberland If alpha version doesn't offer to send a report it means that it wasn't even catched. Are there any dumps in the "tdata/dumps" folder near Telegram.exe file?

**Comment by gsuberland** [comment]
@john-preston Yes. I attached the crash dump in a zip with the original report (crashdump.zip)

Here's another eight to play with: [crashdumps.zip](https://github.com/telegramdesktop/tdesktop/files/1594656/crashdumps.zip)

**Comment by gsuberland** [comment]
Well, I think I found the problem...

![image](https://user-images.githubusercontent.com/6430604/34456531-b4227b82-ed90-11e7-92df-4d1e5ad6f4de.png)

Looks like NZXT's (incredibly crappy) CAM software, that I am unfortunately forced to use to control my water cooler, is injecting a thread into processes in order to monitor FPS or some other nonsense. I still have no idea why pressing shift+o specifically crashes it, but this doesn't look like a Telegram bug specifically.

**Comment by john-preston** [comment]
Yeah, those dumps give me nothing :(

![image](https://user-images.githubusercontent.com/17900494/34456603-8a823ca2-edab-11e7-916e-d297c6a1983c.png)

**Comment by gsuberland** [comment]
@john-preston See above reply - I worked it out with a live debug session.
