### ISSUE TITLE
undefined reference to EC_curve_nist2nid

### ISSUE THREAD

**Issue by amiralies** [telegramdesktop/tdesktop#4260]
### Steps to reproduce
1. build telegram on ubuntu 16.04

### Expected behaviour
Successful build.

### Actual behaviour
Build failed
### Configuration
**Operating system:**
Ubuntu 16.04

<details><summary><b>Logs</b>:</summary>
<pre>
[ 89%] Linking CXX executable Telegram
/usr/local/tdesktop/Qt-5.6.2/lib/libQt5Network.a(qsslsocket_openssl_symbols.o): In function `q_EC_curve_nist2nid(char const*)':
/home/siever/Workspace/TBuild/Libraries/qt5_6_2/qtbase/src/network/ssl/qsslsocket_openssl_symbols.cpp:426: undefined reference to `EC_curve_nist2nid'
collect2: error: ld returned 1 exit status
CMakeFiles/Telegram.dir/build.make:13117: recipe for target 'Telegram' failed
make[2]: *** [Telegram] Error 1
CMakeFiles/Makefile2:85: recipe for target 'CMakeFiles/Telegram.dir/all' failed
make[1]: *** [CMakeFiles/Telegram.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
</pre>

**Comment by stek29** [comment]
#2519
