### ISSUE TITLE
[Feature request] Adding a tooltip to emoticons.

### ISSUE THREAD

**Issue by Heretic121** [telegramdesktop/tdesktop#4262]
Doesn't necessarily have to be a tooltip but; the desktop client allows for us to type out emoticons by "name" ([colon]grin[colon] for example) however I've yet to find a list of emoticon "names", or anything that would make it easy to look up a "name" for an emoticon. Either there is a list that hasn't been placed in a "intuitive" location, or users are reduced to guessing the "name" for the emoticon.

**Comment by auchri** [comment]
https://emojipedia.org

also duplicate.
