### ISSUE TITLE
Send as .. - don't save previos choice

### ISSUE THREAD

**Issue by anfimovir** [telegramdesktop/tdesktop#4263]
Telegram Desktop 1.2.6

Step to reproduce:
Open chat, click icon send file, touch image and..

Default select: **Send as a photo**

We select:
**Send as a file**

After send next file, default selected: **Send as a file**

May be don't save previos select?

**Comment by john-preston** [comment]
@anfimovir Saving is intentional, sorry.

**Comment by anfimovir** [comment]
@john-preston no problem, thank you ;)
