### ISSUE TITLE
Add Title, Name Prefix, Name Suffix and Middle Name To Telegram Contacts

### ISSUE THREAD

**Issue by afarsi** [telegramdesktop/tdesktop#4264]
Hi there.
I have a problem in my phone.
My phone's contacts supporting Name prefix, Name suffix, and Middle Name also. I have a problem with syncing my phone's contacts and telegram. For example, I saved name of my master as Dr. Pavel Durov! I saved Dr. in name prefix of my phone's contacts (However it should be in title section of phone's contacts if it supports title also). But, telegram showing only Pavel Durov not Dr. Pavel Durov in contacts section. It's some time important. Because for example, if forgot name of that master(Pavel Durov or Alexander Zakharov), i can search for Dr only in telegram contacts and find all of my masters.
In addition, there isn't any option in telegram's contacts section to add these sections of when if i want to add Dr. Pavel Durov to my telegram's contacts directly.
I think while in many countries using these sections in names are common, telegram's contacts section should support them:
1-Title(Dr., Prof, Master, Student, Mr., Mrs., MS,...)
2-Name prefix
3-Middle Name(That is common in USA,...)
4-Name suffix
At least, Title should be supported, even if you think user can save other sections in First Name and Last name fields.
I know here is related to telegram desktop, but it's related to all versions of telegram(Including Desktop and Mobile)

**Comment by afarsi** [comment]
In addition, currently First name in telegram contacts is a reqired field. I think it's wrong. Becaue you thinked only about fiendly relateions. For example, If Pavel Durov's friend's will save his name as Pavel. But other persons(For example, his classmates or his co-workers) will save his name as Mr Durov or even Durov. In second case, those person's can's save Durov in Last name only.
I think instead of making First Name as a required field in Add contact section, you should make one of fields(First name or Last name) required. I mean user should sould fill at least one of them and if both of them was empty, system block add contacts.

In additon, you can add another type of add contacts also. It will be with userame and nick name not First name and Last name.
If i don't know a person, but i want to have his conct, i can do it. For example, think about you want to save account of an telegram account of an eshop, news reporter, seller, retailer,...

**Comment by stek29** [comment]
Sorry.

**Comment by VXHa** [comment]
If these features are not supported by TDLib, please try to combine name prefix, first name, surname, name suffix of Android Contacts into the first name field of TDLib, like in Telegram X.

**Comment by VXHa** [comment]
I'm confusing with Telegram for Android.

**Comment by RememberTheAir** [comment]
@VXHa Telegram for Android doesn't use tdlib either 🤔 btw, you can ask to the in-app support or on [Twitter](https://twitter.com/telegram)

**Comment by VXHa** [comment]
Until now, both Telegram for Android and Telegram for Desktop (Windows) don't support Middle Name, Name Suffix and Name Prefix like Google Contacts does.

BTW, file names should be allowed to be longer than 64 characters, like Windows 10 does support

**Comment by anilatx** [comment]
Another voice of support for prefixes/suffixes - majority of my contacts is saved without surname, but all have prefix (place I know them from), and many have suffix - this is a deal-breaker for me, and I can imagine other in same position

**Comment by Ondra1230** [comment]
I dont understant why?On 1/16/21 at 11:54 PM, anilatx wrote:
                
            
            
                
                    From: "anilatx" <notifications@github.com>Date: January 16, 2021To: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Subject: Re: [telegramdesktop/tdesktop] Add Title, Name Prefix, Name Suffix and Middle Name To Telegram Contacts (#4264)
                
                
Another voice of support for prefixes/suffixes - majority of my contacts is saved without surname, but all have prefix (context I know them from), and many have suffix - this is a deal-breaker for me, and I can imagine other in same position

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/4264#issuecomment-761536579",
"url": "https://github.com/telegramdesktop/tdesktop/issues/4264#issuecomment-761536579",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by anilatx** [comment]
> I dont understant why?

In social context it is common to exchange names and numbers without surname. 
So I'd have prefix:Bookclub name:John surname:<empty> postfix: Texan. And Telegram (unlike WhatsApp: BookClub John, Texan) will just show John, like numerous others in the contact list. And setting surname BookClub.Texan would be an ugly hack, just for sake of Telegram)
