### ISSUE TITLE
Issue with hyperlinks

### ISSUE THREAD

**Issue by Suan11** [telegramdesktop/tdesktop#4265]
### Steps to reproduce
1.  If I send a hyperlink, it is being sent as a broken link if though it is a valid link and this is the same case on android phone too.

### Expected behaviour
The link page should open.

### Actual behaviour
The link is broken.

### Configuration
**Operating system:**
Windows 10 
**Version of Telegram Desktop:**
1.2.6
**Used theme**:
Rainfall
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@Suan11 An example of a link?

**Comment by Suan11** [comment]
@john-preston 
https://www.msn.com/en-in/news/techandscience/draped-in-a-sari-worlds-first-robot-citizen-makes-india-debut-at-iit-bombay/ar-BBHwqyL?ocid=spartanntp
