### ISSUE TITLE
Video calling and screen sharing

### ISSUE THREAD

**Issue by braderhart** [telegramdesktop/tdesktop#4270]
### Steps to reproduce
1. Open Telegram
2. Try to video call someone

### Expected behaviour
I would like to be able to video call people and screen share with them like Hangouts, Slack,  Discord, etc.

### Actual behavior
I can only send recorded video clips and use audio in calls, with no support for video calling.

### Reason
I am trying to get my friends to adopt Telegram for it's great features in other areas. They say they need video calling support. I don't absolutely need it right now, but IMO it should be a priority at this point.

It would make Telegram a lot more competitive and speed up adoption. I would assume that internally this is discussed a lot more heavily, but an updated roadmap or call for developers would help provide some transparency.

### Configuration
Operating system: Arch Linux
Version of Telegram Desktop: 1.2.6

**Comment by stek29** [comment]
Telegram doesn't support video calls

**Comment by braderhart** [comment]
I was hoping to label this a feature request.

**Comment by stek29** [comment]
@braderhart other apps should support this -- it's a feature request for Telegram as whole and not for TDesktop. You can request it on Twitter or via in-app support

**Comment by IlyaIndigo** [comment]
А можно ли узнать планируется ли вообще реализация видео звонков (хотя бы только p2p (без прокси)), или она сочтена затратной, или вообще не планировалась изначально, или всё же она будет но не сразу?
А также планируется вообще перевод главного сайта на русский язык?

Меня нет в твитере, и ради этого не хотется там регистрироваться.
Уверен. что эти вопросы задавались тысячи раз, и возможно на них уже давались ответы.

**Comment by 23rd** [comment]
Seems like voice and group calls are in progress. 

https://github.com/grishka/libtgvoip/tree/public/video

But it is annoying to ask that every time, especially in this repository.

**Comment by IlyaIndigo** [comment]
Thank you very much! :-)

To do this, on the main site in the FAQ section should be an item on video calls.

**Comment by mugavri** [comment]
on 6.3 beta for ios has video calls!

**Comment by RomanJos** [comment]
Any update on this ? I use obs as a virtual cam right now
