### ISSUE TITLE
Task bar icon won't get gray with dual displays [macOS]

### ISSUE THREAD

**Issue by nerdroychan** [telegramdesktop/tdesktop#4271]
When using Telegram Desktop 1.2.6 (from Mac App Store) with dual display, the task bar icon won't get gray on the inactive display.

On the active display, the taskbar looks like:

![active](https://user-images.githubusercontent.com/7454941/34477071-89e4ca26-efd1-11e7-9329-2b1322884c7d.png)

On the inactive display, it looks like: 

![inactive](https://user-images.githubusercontent.com/7454941/34477072-8a272628-efd1-11e7-872a-7156a57f1be3.png)

This seems to be a small problem and I'm not sure if it is os-related. But it would be great to get this problem resolved.

Thanks.

**Comment by john-preston** [comment]
@nerdroychan This is because a custom icon is used, not a monochrome one. And system doesn't change its opacity automatically.

Custom icon is used because we want to be able to draw a red or gray unread messages counter over it, not the whole icon with a single color.

**Comment by Aokromes** [comment]
generic #1199 ?

**Comment by nerdroychan** [comment]
@john-preston Does it mean that the icons in the menu bar with different message count are independent non-vector images?

**Comment by john-preston** [comment]
@nerdroychan Yes. But the problem is that they're not monochrome.

**Comment by Deseteral** [comment]
That doesn't seem to be a problem with other apps:

![Screenshot 2019-03-18 at 14 51 54](https://user-images.githubusercontent.com/6249014/54534863-93c6b380-498d-11e9-9b50-f9c0bdbee86d.png)

![Screenshot 2019-03-18 at 14 52 26](https://user-images.githubusercontent.com/6249014/54534853-90332c80-498d-11e9-90d6-72b7ab151ed4.png)
