### ISSUE TITLE
Ability to restrict all of group members at one time and merge channels and public groups

### ISSUE THREAD

**Issue by afarsi** [telegramdesktop/tdesktop#4274]
Hi there.
Currently, admins of telegram groups can restrict each member of groups. But there isn't any way to apply restrictions to all users at one time.
For example, in a calss group, at homework deadlines/ exams, admin of group(teacher) want to restrict students to be able to read his messages and send their files(That is related to their homeworks), but they shouldn't be able to send messages, pictures, and videos.
With this thing telegram, will support chage between groups to channels for temporery times without need to creat a channel for temp time.
With this feature, you can merge public groups and channels together. Becasuse a channel is only a one way group, and with apply restriction to all of users in a group, it will a channel, and by removing it, it will be a public group.
I think telegram should support it in all of versions(From mobile to desktop)
Thanks.

**Comment by stek29** [comment]
> I think telegram should support it in all of versions(From mobile to desktop)

Exactly
