### ISSUE TITLE
Selecting entire line with spaces when selecting a code block

### ISSUE THREAD

**Issue by manzabvil** [telegramdesktop/tdesktop#4276]
### Steps to reproduce
1. double click a code block

### Expected behaviour
Copying only the code block

### Actual behaviour
The entire line with spaces is copied with zero witdh space ( \xE2\x80\x8B )
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.2.6
**Used theme**:
Predefined

![image](https://user-images.githubusercontent.com/9219196/34526952-388445a2-f0a4-11e7-9bbb-1130b8f41553.png)

**Comment by RememberTheAir** [comment]
This doesn't happen just with formatted text but also when there's a new line

Can't be considered a serious bug but I also agree that not highlighting the whole line would be better.

It took me a while to get used to this "new way" of highlighting selected lines, when TDesktop started to behave in this way. Can't deny that at the beginning I was quite annoyed :)

**Comment by manzabvil** [comment]
It adds a Zero Witdh space where it should be \xE2\x80\x8B

I use this for coupon codes for shops, and it cause the coupon doesnt work because of this
