### ISSUE TITLE
Add more languages to Telegram desktop, because they are added to Android and iOS

### ISSUE THREAD

**Issue by shamarin** [telegramdesktop/tdesktop#4277]
With version 4.4 of Telegram on Android and iOS more languages added to Telegram. Telegram is available in French, Indonesian, Malay, Russian and Ukrainian now for this platforms. Telegram now supports 13 languages, which are available in Settings https://telegram.org/blog/live-locations. And on desktop version this languages are not added till now in settings. Please, add them.

**Comment by MasterGroosha** [comment]
Duplicating **your own** issues won't help, it only creates a mess.
#4126
