### ISSUE TITLE
Extend the Grouped Photos feature to services like Twitter and Imgur

### ISSUE THREAD

**Issue by RubeensVinicius** [telegramdesktop/tdesktop#4278]
### Steps to reproduce
Send a link to a tweet or Imgur album with multiple images.

### Expected behaviour
All the images should be embedded on Telegram using the same format introduced on 1.2.6 for uploaded images.

### Actual behaviour
Only the first image is embedded.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.2.6

**Used theme**: Night Mode

**Comment by Aokromes** [comment]
#2396
