### ISSUE TITLE
[Feature request] indicator who read the message in group conversation

### ISSUE THREAD

**Issue by robgal519** [telegramdesktop/tdesktop#4279]
**Expected behaviour**
it would be really nice if i could know who have seen my message in group conversation. ( even indicator that all members have seen the message would be nice) 

**Actual behaviour**
At this point i only see that someone has seen the message. 

I think it would be useful feature

**Comment by auchri** [comment]
Not possible with the current api.

**Comment by stek29** [comment]
#2976
