### ISSUE TITLE
Won't send an animated GIF correctly

### ISSUE THREAD

**Issue by darkon5** [telegramdesktop/tdesktop#428]
If you send an animated GIF file using the "Clip" ("Attached") dropdown menu and click on "Photo", it will only send the fist frame of the GIF. In order to send the full GIF, you need to click on "File" and then select it.

I believe that this is a bug and not an intended function.

**Comment by nplezka** [comment]
Up

**Comment by Sithdown** [comment]
+1

**Comment by vincvincvinc** [comment]
+2

**Comment by Thijs5** [comment]
+1

**Comment by formatq** [comment]
+1

**Comment by telegramdesktop** [comment]
This is intended, Photo is always a static image, gif animations should be sent as documents.

Gifs copied to clipboard _already_ have only one frame in the clipboard, not the whole animated thing, so it just can't be sent like an animated gif document.
