### ISSUE TITLE
Minimize to tray on close no longer working

### ISSUE THREAD

**Issue by sirati97** [telegramdesktop/tdesktop#4280]
### Steps to reproduce
1.  Run telegram on windows
2.  Close by clicking x

### Expected behaviour
In older versions, it minimized to tray which is quite useful

### Actual behaviour
Process terminates

### Configuration
**Operating system:**
WIn10 FCU

**Version of Telegram Desktop:**
1.2.8 alpha

**Comment by john-preston** [comment]
@sirati97 Perhaps you've disabled tray icon in Settings?

**Comment by sirati97** [comment]
Oh man, seems like I fell for this one. I looked through my settings before to make sure that everything was aright and overlooked the tray setting completely. I cannot recall disabling it or being aware of its existence. 

So yes, I must have disabled tray icon by accident. Is there a good way to make this settings functionality clearer?
