### ISSUE TITLE
macOS system shortcut for next/previous chat (cmd+shift+])

### ISSUE THREAD

**Issue by zhovner** [telegramdesktop/tdesktop#4281]
macOS has OS wide shortcuts for navigating to the previous/next tab:

```
cmd+shift+[
cmd+shift+]
```
in native `iMessage.app` these shortcuts are used for previous/next chat.

These shortcuts are also supported in Finder, Safari, Terminal and many other apps.
3rd party apps support these shortcuts too: WhatsApp, Google Chrome, Firefox, etc.

It will be logical to add it in Telegram Desktop.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1060
