### ISSUE TITLE
New ideas for better Telegram Desktop :)

### ISSUE THREAD

**Issue by alish123456** [telegramdesktop/tdesktop#4282]
hi...
I used to start editing the desktop telegram source, but I encountered a lot of problems and did not continue the project!

Anyway I have the ideas that my friends have given me.
Hope to add new ideas and new features to the telegram.
Sorry i'm not good english ☹️☹️

New functionalitys

1. send BUZZ to user (Like yahoo messenger)

2. Send location (in windows 10 by app Maps or use API google maps)

3. Show contact names (Their telegram Firstname)

4. A button to share channels, robots, and users (For quick use)

5. Use custom fonts Messages

6. Add a download manager (Show all downloaded files and Download file at specified time)

7. Send sms invitations to telegrams to phone number of non-Telegram (by user)

8. Lock group or channel or robot by custom password.

9. hide group or channel or robot by user in telegram.

10. Add the user's shortcut (icon) to the desktop or taskbar or start (For easier and faster access)

11. Add button to go to the first message group and channel and robot

12. Sync contacts with Google and Microsoft contacts.

13. View all online contacts

14. add user to interest, like [cutegram](http://aseman.co/en/products/cutegram/)

15. add Secret Chat in telegram desktop.

16. Categorizing chats  (group and channel and robot. Like telegrams unofficial android (telegram plus))

17. Forward in multiple groups at the same time (Like telegrams unofficial android (Mobogram)

18. Take a screenshot of the chats and share

19. Manage multiple accounts in one telegram

20. Warning the contact that is online (Select contacts by user)

21. video call (hahahaha)

22. instant view in telegram desktop :|

23. Autoplay GIFs (in setting)

24. **Speech to text message for send (With [API Google](https://cloud.google.com/speech/). Supports all languages. Very smart)**  Adding this feature will be very attractive

25. Telegram account Backup in google drive or dropbox or sky drive (Like Viber Messanger and whatsapp)

26. Custom sound Notification

27. I'll say the rest later .....
-----------------------------------------------------

telegram Edited by me:

[Profile](http://uupload.ir/files/amls_skerin.jpg)
[Main](http://uupload.ir/files/zhxq_untitled-1.jpg)
[ProfileUser](http://uupload.ir/files/5uah_udsntitsled-1.jpg)
[PopupMessage](http://uupload.ir/files/k6ym_untitled-1.jpg)

**Comment by Aokromes** [comment]
New functionalitys

send BUZZ to user (Like yahoo messenger)

Send location (in windows 10 by app Maps or use API google maps)
https://github.com/telegramdesktop/tdesktop/issues/1193

Show contact names (Their telegram Firstname)
https://github.com/telegramdesktop/tdesktop/issues/3893

A button to share channels, robots, and users (For quick use)

Use custom fonts Messages
https://github.com/telegramdesktop/tdesktop/issues/90

Add a download manager (Show all downloaded files and Download file at specified time)
https://github.com/telegramdesktop/tdesktop/issues/809

Send sms invitations to telegrams to phone number of non-Telegram (by user)

Lock group or channel or robot by custom password.

hide group or channel or robot by user in telegram.

Add the user's shortcut (icon) to the desktop or taskbar or start (For easier and faster access)

Add button to go to the first message group and channel and robot

Sync contacts with Google and Microsoft contacts.

View all online contacts

add user to interest, like cutegram
pin contact?

add Secret Chat in telegram desktop.
https://github.com/telegramdesktop/tdesktop/issues/871

Categorizing chats (group and channel and robot. Like telegrams unofficial android (telegram plus))
https://github.com/telegramdesktop/tdesktop/issues/1107

Forward in multiple groups at the same time (Like telegrams unofficial android (Mobogram)
https://github.com/telegramdesktop/tdesktop/issues/1841

Take a screenshot of the chats and share
print-screen + paste

Manage multiple accounts in one telegram
https://github.com/telegramdesktop/tdesktop/issues/4261

Warning the contact that is online (Select contacts by user)

video call (hahahaha)
https://github.com/telegramdesktop/tdesktop/issues/4270

instant view in telegram desktop :|
https://github.com/telegramdesktop/tdesktop/issues/3492

Autoplay GIFs (in setting)

Speech to text message for send (With API Google. Supports all languages. Very smart) Adding this feature will be very attractive

Telegram account Backup in google drive or dropbox or sky drive (Like Viber Messanger and whatsapp)

Custom sound Notification

I'll say the rest later .....

I sugest you to make one ticket for each of the ones i don't have linked you to existing issues.

**Comment by stek29** [comment]
> I sugest you to make one ticket for each of the ones i don't have linked you to existing issues.

This.

---

1, 2, 5, 6, 11, 12, 15, 16, 19, 22, 23, 26 -- duplicates

3, 7, 9, 14 -- please explain better

4 -- just copy link and share it

13, 21, 25 -- API issue

**Comment by ArmeF97** [comment]
I think 3 means:

If my name is "name1"
and people save me "myrealname"
and if I change my telegram name to "name2"
people who have saved me in thier contacts always see me as "myrealname"

In group maybe sometimes is useful, for example

A is Alice, nickname A1
B is Bob
C is Charles.

Bob has Alice's number

Charles chats with Alice in the group, calling her "A1"
Alice changes her nickname to "A2"
Bob, who have always know that Alice is "A1", now asks himself who is A2, so he would like to go check Alice new Telegram name, without having to delete and re-create the contact

**Comment by yashpalgoyal1304** [comment]
i really agree with 3 and 4. I have faced the scenario given by @ArmeF97 several times and soo soo wished there was some way to avoid the confusion.
