### ISSUE TITLE
 CMake Error at CMakeLists.txt:205 (add_library)

### ISSUE THREAD

**Issue by hosseinmousavi** [telegramdesktop/tdesktop#4285]
I go through instruction to compile telegram on Ubuntu 14.04 but i encounter these erros.
I have Ubunut 14.04 LTS

<details><summary><b>Logs</b>:</summary>
CMake Error at CMakeLists.txt:241 (add_library):
  Cannot find source file:

    ../../src/testing/googlemock/src/gmock-all.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:261 (add_library):
  Cannot find source file:

    ../../src/testing/googlemock/src/gmock_main.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:205 (add_library):
  Cannot find source file:

    ../../src/testing/googletest/src/gtest-all.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:224 (add_library):
  Cannot find source file:

    ../../src/testing/googletest/src/gtest_main.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: Cannot determine link language for target "gmock".
CMake Error: CMake can not determine linker language for target: gmock
CMake Error: Cannot determine link language for target "gmock_main".
CMake Error: CMake can not determine linker language for target: gmock_main
CMake Error: Cannot determine link language for target "gtest".
CMake Error: CMake can not determine linker language for target: gtest
CMake Error: Cannot determine link language for target "gtest_main".
CMake Error: CMake can not determine linker language for target: gtest_main
-- Generating done
-- Build files have been written to: /breakpad/out/Default
[ 97%] Built target common
Linking CXX executable dump_syms
common/libcommon.a(dump_symbols.o): In function `bool (anonymous namespace)::InitModuleForElfClass<google_breakpad::ElfClass32>(google_breakpad::ElfClass32::Ehdr const*, std::string const&, google_breakpad::scoped_ptr<google_breakpad::Module>&)':
dump_symbols.cc:(.text+0x1a2f): undefined reference to `google_breakpad::BaseName(std::string const&)'
common/libcommon.a(dump_symbols.o): In function `bool (anonymous namespace)::InitModuleForElfClass<google_breakpad::ElfClass64>(google_breakpad::ElfClass64::Ehdr const*, std::string const&, google_breakpad::scoped_ptr<google_breakpad::Module>&)':
dump_symbols.cc:(.text+0x1d93): undefined reference to `google_breakpad::BaseName(std::string const&)'
collect2: error: ld returned 1 exit status
make[3]: *** [dump_syms] Error 1
make[2]: *** [CMakeFiles/dump_syms.dir/all] Error 2
make[1]: *** [CMakeFiles/dump_syms.dir/rule] Error 2
make: *** [dump_syms] Error 2

</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4275 ?

**Comment by hosseinmousavi** [comment]
Thanks its' solved by adding -std=c++11 to the flags file Libraries/breakpad/out/Default/CMakeFiles/common.dir/flags.make where my CXX_FLAGS looks like this:
CXX_FLAGS = -std=c++11
ad mentiond in #4275 and also cloning google tests again
