### ISSUE TITLE
Problem opening hyperlinks on Mac

### ISSUE THREAD

**Issue by aniforprez** [telegramdesktop/tdesktop#4286]
### Steps to reproduce
1. Click on any link shared by anyone on the Mac desktop client

### Expected behaviour
It should be opening the link in the default browser (Chrome in my case)

### Actual behaviour
It opens a brand new window in the default browser (Chrome in my case) with an empty new tab and then does nothing. The browser does not navigate to the URL of the link I clicked

### Configuration
**Operating system:** macOS High Sierra v10.13.2

**Version of Telegram Desktop:** 1.2.6

**Used theme**: Only Dark Mode

**Comment by auchri** [comment]
See https://github.com/telegramdesktop/tdesktop/issues/4189

**Comment by aniforprez** [comment]
Ah whoops. Didn't find it

**Comment by john-preston** [comment]
See also Chrome bug report:

https://bugs.chromium.org/p/chromium/issues/detail?id=777863

And some discussion:

https://www.reddit.com/r/mac/comments/72pwzj/high_sierra_opening_link_in_imessage_opens_blank/

Still happens on Chrome 63 to me.

**Comment by aniforprez** [comment]
Yup, relaunching Chrome with the latest update fixed the problem. Thanks!
