### ISSUE TITLE
[Feature Request] Auto save

### ISSUE THREAD

**Issue by muthu32** [telegramdesktop/tdesktop#4288]
I prefer to use whatsapp because, it downloads all images and media that i viewed is automatically stored in retrieval format in hard disk. Whereas telegram saves those files in encrypted format.
Give us option "autosave" in settings to save all viewed images and video without manual click.

Telegram's localstorage is not efficient as whatsapp. 1.3 gb of localstorage for telegram is usable only in telegram.

Whereas 1.3gb of whatsapp localstorage is usable by all other apps.

This is too bad for telegram apps.

**Comment by stek29** [comment]
I don't want other apps to have access to Telegram's files, for example. If I want them to, I'd manually "export" files I need.

**Comment by muthu32** [comment]
Manually export files is already available. Do you like to export them with thousands of clicks?
Do you know what is user friendly?
May be you have so much time, to click thousands of images? But I don't have.

**Comment by stek29** [comment]
I don't want other apps to peek into what images I've seen in TG.

**Comment by muthu32** [comment]
If other apps, don't want to see your images, then your hard disk should not contain any other images (birthday images, party images, camera images) and also all videos should be in encrypted format.
This is necessary feature for those who are terrorist or hacker or companies. This is does not falls under userfriendly. May be your harddisk was full of encryption. But Mine was filled with normal images, videos with system password.

Encrypted files may be a good option but why so many people use whatsapp. There are more normal people who wants to fills their harddisk with normal images than unusable encrypted files.Encrypted files may be a option but not compulsory one. I just want auto save as an option not default one.

**Comment by stek29** [comment]
Honestly I don't give a fuck about whatsapp and reasons people use it. I just said why I don't think this is a good idea, that's all.

**Comment by muthu32** [comment]
Sorry, I can't give up on this feature because I love telegram apps on my pc.
Telegram android also supports this feature.
Settings => Data and storage => Auto download media.
I hope this feature also comes to desktop version.

**Comment by Aokromes** [comment]
this was implemented on 1.5.something.
