### ISSUE TITLE
Telegram Desktop for Linux do not show channels.

### ISSUE THREAD

**Issue by ea4eoz** [telegramdesktop/tdesktop#4289]
### Steps to reproduce
1. Open Telegram Desktop for Linux ( Version 1.2.6 )
2. Browse the message list. No single channel in it. Only Groups and private chats are shown.
3. Search for a channel you know you are suscribed. Click on it. Read some messages. After this, that channel appears in the list.
4. If a channel publish some new content, it appears on the list.

The Android app show all subscribed channels as usual.

### Expected behaviour
All subscribed channels must be shown.

### Actual behaviour
Only Groups and private chats are shown. You must "refresh" subscribed channels (by searching them) to apper on list.

### Configuration
Debian 9

Telegram Desktop 1.2.6 for Linux

Default theme.

**Comment by d0tfile** [comment]
Arch Linux (4.14.12, gnome-shell), Telegram Desktop 1.2.6 (from community repo).
I don't have this problem. User chats, groups and channels - no difference with Telegram on Android.

**Comment by ea4eoz** [comment]
At 14:00 (13:00 UTC) all channels appeared automagically. Maybe a puntual server problem?

Anyway everything is ok now. I'm closing the issue.

Thank you.

**Comment by Aokromes** [comment]
humm i have seen this issue on some, unless i click them they aren't updated.
