### ISSUE TITLE
Moderation: Incomplete banned users list

### ISSUE THREAD

**Issue by dskvr** [telegramdesktop/tdesktop#4292]
### Steps to reproduce
1. Have a high volume supergroup
2. Ban more than a thousand people (spammers, scammers, etc)
3. Try to find a specific member that was recently banned.  
4. Try to be a moderator without going insane. 

### Expected behaviour
Every user should be on the list, they are not. This is confirmed by visually scanning (for the love of..) the banned users list, not finding a user, and then going onto the android version and searching (YES!) for the user and finding them. Sure, this is one workaround, but the android version doesn't say **who** banned the user when you're attempting to figure out the nature of a ban. It's a catch22

### Actual behaviour
The list is incomplete. 

### Configuration
MacOS

**Version of Telegram Desktop:**
Current

**Used theme**:
Dark

**Comment by auchri** [comment]
Please provide your exact Telegram version number and your os version.

**Comment by dskvr** [comment]
@auchri fixed
