### ISSUE TITLE
Moderation: Requires search functionality for banned users

### ISSUE THREAD

**Issue by dskvr** [telegramdesktop/tdesktop#4293]
### Steps to reproduce
1. Have a high volume supergroup
2. Ban more than a thousand people (spammers, scammers, etc)
3. Try to find a specific member that was recently banned.
4. Try to be a moderator without going insane.

### Expected behaviour
A search functionality like on the android version.

### Actual behaviour
Go blind while attempting to find a specific member among thousands. 

### Configuration
**Operating system:**
MacOS

**Version of Telegram Desktop:**
Current

**Used theme**:
Dark

**Comment by auchri** [comment]
Please provide your exact Telegram version number and your os version.

**Comment by dskvr** [comment]
@auchri fixed.

**Comment by auchri** [comment]
Well, if you compare the screenshot on the [main page](https://github.com/telegramdesktop/tdesktop) of this repo to your Telegram app, you will notice that you are using a [different](https://github.com/overtake/TelegramSwift) application.

**Comment by stek29** [comment]
@dskvr https://t.me/macswift
