### ISSUE TITLE
How debug messages

### ISSUE THREAD

**Issue by hosseinmousavi** [telegramdesktop/tdesktop#4295]
I use qDebug() to output variables to console and debug th application but i can't output messages
I get messages in tdesktop/Telegram.SourceFiles/mainwidget.cpp file, in this function
    void MainWidget::feedUpdate(const MTPUpdate &update)
in every case i want to output message but qt give me conversion error

/usr/local/tdesktop/Qt-5.6.2/include/QtGui/5.6.2/QtGui/private/qfixed_p.h:179:16: note:   no known conversion for argument 2 from ‘const MTPMessage {aka const MTPBoxed<MTPmessage>}’ to ‘const QFixed&’

how can i get message body and print it

**Comment by stek29** [comment]
Open settings, type "debugmode", and look for mtp_HH_MM.txt

**Comment by hosseinmousavi** [comment]
No i want the message body variable, how can i access it directly
I tried qDebug << d.vmessage or qDebug << d.vmessage.c_message()
but no luck

**Comment by stek29** [comment]
You need some basic C++ skills \*shrug\*

Once again: look for code which produces mtp logs

**Comment by hosseinmousavi** [comment]
I'm new to cpp
where is it?
