### ISSUE TITLE
The list of messages in the chat is not updated until you open the chat itself.

### ISSUE THREAD

**Issue by abdulgalimov** [telegramdesktop/tdesktop#4296]
See video: http://take.ms/dqYPa.

**Comment by auchri** [comment]
Use the template please.

**Comment by abdulgalimov** [comment]
Explain please, what is a template? and how does this help solve the problem of updating the message list?

**Comment by auchri** [comment]
There is a template for new issues which you should follow:
![image](https://user-images.githubusercontent.com/5092164/34818643-b83a5aa8-f6bb-11e7-83cd-c3331cadbe91.png)
