### ISSUE TITLE
Timeline in Telegram Messanger

### ISSUE THREAD

**Issue by alish123456** [telegramdesktop/tdesktop#4297]
Hello to all friends...

I used before [Messenger Line](https://line.me/en/)

There is a feature in this messenger called Timeline
This feature can post (all types of media) and share with friends Or everyone.
send comments and likes are availabl (for post). like facebook.

To better understand it, install the line Messenger and use this feature
I'm sure you'll love this timeline too will

If this feature is added to the telegram messenger, it will be added to the popularity of the telegram.
It will also be very attractive

what do you think?
If it's good us to share it with the telegram managers (pavel duro)

**Comment by stek29** [comment]
> To better understand it, install the line Messenger and use this feature

No, thanks.
And don't use this tracker to tell others what server-side features you want to suggest.
