### ISSUE TITLE
Telegram Desktop segfaulting at startup on Debian buster using Gnome 3

### ISSUE THREAD

**Issue by rmuellerb** [telegramdesktop/tdesktop#4298]
### Steps to reproduce
1. Installation of Debian Buster
2. $> sudo apt install telegram-desktop
3. $> telegram-desktop

### Expected behaviour
Start of telegram-desktop

## Shell
(telegram-desktop:6324): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'
(telegram-desktop:6324): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(telegram-desktop:6324): GLib-GObject-CRITICAL **: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
(telegram-desktop:6324): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(telegram-desktop:6324): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(telegram-desktop:6324): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(telegram-desktop:6324): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(telegram-desktop:6324): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplay'
(telegram-desktop:6324): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(telegram-desktop:6324): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed
(telegram-desktop:6324): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(telegram-desktop:6324): GLib-GObject-CRITICAL **: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
fish: “telegram-desktop” terminated by signal SIGSEGV (Address boundary error)
## Syslog
kernel: [  561.008751] telegram-deskto[3858]: segfault at 114 ip 00007f1729d8c75c sp 00007ffcac131230 error 6 in libgdk-x11-2.0.so.0.2400.31[7f1729d3e000+af000]

## further description
The problem vanishes, in case the 'XDG_CURRENT_DESKTOP' is set to 'NONE':
```
$> env XDG_CURRENT_DESKTOP=NONE telegram-desktop
```
### Configuration
**Operating system:** Debian Buster (amd64), Gnome 3

**Version of Telegram Desktop:** 1.1.23

**Used theme**: Default

**Comment by auchri** [comment]
@rmuellerb Try the version from desktop.telegram.org, 1.1.13 is really old.

**Comment by rmuellerb** [comment]
@auchri Sorry, was just a typo, it is 1.1.23. Corrected it in the description.

**Comment by auchri** [comment]
@rmuellerb The current version is 1.2.6

**Comment by Aokromes** [comment]
Close because the issue was distribution side package :)
