### ISSUE TITLE
Previewing a message without losing its notification icon

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#4300]
I am huge fan of the unread notification icons that indicate how many unread messages I have received from a person. At the same time, I encounter myself with the desire to peek into a message without losing its notification icon because messages cannot be set back to unread. 

Can you guys think of any way how we could implement such a peek preview that preserves the notification icon? Maybe with a mouseover over the person in the sidebar to preview his or her latest message?

**Comment by maxklock** [comment]
Not just previewing, maybe a menu to "mark as unread" a message

**Comment by orschiro** [comment]
> Not just previewing, maybe a menu to "mark as unread" a message

Great idea!

**Comment by RememberTheAir** [comment]
> Not just previewing, maybe a menu to "mark as unread" a message

This would have to be supported by the API, because you would expect the chat to be marked as unread across all your clients. Message preview, anyway, can be implemented on client, without changes in the servers. The iOs client has something like that, if I recall correctly (hold to preview a chat)

**Comment by henning-schild** [comment]
A mark as unread feature would be great! If you google that you will come across many people wanting that. One workaround is to type something in that chat, which will make that appear at the top marked as "draft". But the real "mark as unread" would be much better. There are several reasons to do that.
1. you are on the go and an answer would require time or research
2. you are in a car and can not reply
3. you simply want to be reminded of a TODO you recieved and already read
 ....

If the API does not support that, having that as an issue for just this one client is probably the wrong place. But let us hope someone will pick it up and it will be implemented across all clients.

**Comment by RememberTheAir** [comment]
Mark as unread as been implemented
