### ISSUE TITLE
Telegram Desktop Crash on Arch 4.14.13

### ISSUE THREAD

**Issue by gforcedev** [telegramdesktop/tdesktop#4301]
### Steps to reproduce
1. Open Terminal
2. Run telegram-desktop

### Expected behaviour
App opens

### Actual behaviour
App crashes with these messages:
QApplication: invalid style override passed, ignoring it.

(telegram-desktop:2180): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(telegram-desktop:2180): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(telegram-desktop:2180): GLib-GObject-CRITICAL **: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(telegram-desktop:2180): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(telegram-desktop:2180): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(telegram-desktop:2180): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(telegram-desktop:2180): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(telegram-desktop:2180): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplay'

(telegram-desktop:2180): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(telegram-desktop:2180): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed

(telegram-desktop:2180): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(telegram-desktop:2180): GLib-GObject-CRITICAL **: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault (core dumped)

### Configuration
**Operating system: Arch 4.14.1 with Gnome 3.26.2**

**Version of Telegram Desktop: 1.2.6-4**

**Used theme**: Not sure.

**Comment by john-preston** [comment]
@gforcedev Please try the binary from https://desktop.telegram.org

**Comment by d0tfile** [comment]
Arch Linux (4.14.13-1-ARCH x86_64) with Gnome (3.26.2). I have no errors with `telegram-desktop` (1.2.6-4)

**Comment by dotnetfox** [comment]
Same problem. Arch Linux (4.14.13-1-ARCH core version).
@john-preston, the binary files working.

**Comment by gforcedev** [comment]
`env | grep DESKTOP` gives me this:

```
GIO_LAUNCHED_DESKTOP_FILE_PID=684
DESKTOP_SESSION=gnome
XDG_SESSION_DESKTOP=gnome
XDG_CURRENT_DESKTOP=GNOME
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/org.gnome.Shell.desktop
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
```

after `unset XDG_CURRENT_DESKTOP` and `unset DESKTOP_SESSION`, running `telegram-desktop` still yields the same errors.

However, running the binary @john-preston linked works without problems, and after running and closing it, `telegram-desktop` seems to be working without complaint (apart from `QApplication: invalid style override passed, ignoring it.`)

**Comment by stek29** [comment]
So official binary works, and some AUR build doesn't?

**Comment by john-preston** [comment]
@gforcedev Official builds are only the ones from the website.

**Comment by gforcedev** [comment]
Ah. Is that arch package mislabeled? It's upstream URL is https://desktop.telegram.org/

**Comment by stek29** [comment]
@gforcedev Use telegram-desktop-bin package then

**Comment by AlexWayfer** [comment]
From https://bugs.archlinux.org/task/65080#comment185140

> Comment by edac val (edacval) - Thursday, 09 January 2020, 06:03 GMT+3
> Fixed by installing libappindicator-gtk3 . libappindicator-gtk3 should be moved from optdepends() to depends().
