### ISSUE TITLE
Add additional library when building

### ISSUE THREAD

**Issue by hosseinmousavi** [telegramdesktop/tdesktop#4303]
Where i can add share library to compile it with telegram.
I want to add mysql connection to telegram but  no luck
I add below to mainwidget.cpp

`#include <mysql_connection.h>
`
`#include <cppconn/driver.h>
`
`#include <cppconn/resultset.h>
`
`#include <cppconn/statement.h>
`

and in MainWidget::feedUpdate

`sql::Driver *driver;
`
`sql::Connection *con;
`
`sql::Statement *stmt;
`
`sql::ResultSet *res;
`
`driver = get_driver_instance();
`
`con = driver->connect("tcp://127.0.0.1:3306","root","root");
`

and  add LDLIBS = -lmysqlcppconn in Makefile

but always give me error at building

`undefined reference to get_driver_instance
`

**Comment by stek29** [comment]
Why are you doing this? Can't you just use some tg library?

Official, C++ and bindings -- https://github.com/tdlib/td

Python - https://github.com/LonamiWebs/Telethon

Rust - https://github.com/JuanPotato/Vail

Rust - https://github.com/Connicpu/mtproto-rs

PHP - https://github.com/danog/MadelineProto

Kotlin - https://github.com/badoualy/kotlogram

JavaScript - https://github.com/zerobias/telegram-mtproto

C - https://github.com/vysheng/tg, https://bitbucket.org/vysheng/tdcli

Elixir - https://gitlab.com/snippets/1664390

Elixir — https://github.com/Fnux/telegram-mt-elixir and https://github.com/Fnux/telegram-tl-elixir

**Comment by stek29** [comment]
And it has nothing to do with TDesktop, it's rather your MySQL lib.

**Comment by hosseinmousavi** [comment]
Thanks for response, when i compile my own standalone mysql connection script like below
`gcc test.cpp -lmysqlcppconn`
everything's OK but don't know how add the `mysqlcppconn` share library to telegram to build with it
I work with telegram source because in almost all implementations there is a delay when receiving new messages and  updates so for mitigating the delay i must to edit source
`https://github.com/LonamiWebs/Telethon/issues/237`

Thanks again stek29

**Comment by stek29** [comment]
@hosseinmousavi tdlib is used by BotAPI and is very stable.
