### ISSUE TITLE
Telegram Desktop does not resize after windows font size change

### ISSUE THREAD

**Issue by junalmeida** [telegramdesktop/tdesktop#4305]
### Steps to reproduce
1.  Use a dual monitor config with 100% and 125% text size
2. Open telegram using the 100% monitor
3. Move it to the 125% monitor

### Expected behaviour
Telegram should readapt its size and text sizes

### Actual behaviour
Still uses 100% at the 125% screen

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.2.6

**Used theme**: Default

**Comment by too4words** [comment]
Same issue here.

**Comment by GnubiBORED** [comment]
same issue here
