### ISSUE TITLE
memset used with constant zero length

### ISSUE THREAD

**Issue by hosseinmousavi** [telegramdesktop/tdesktop#4307]
After many successfull builds, today i got this error
ubuntu 14.04

`[ 50%] Building CXX object` `CMakeFiles/Telegram.dir/home/pepsi/tbuild/tdesktop/Telegram/SourceFiles/mainwidget.o`
`Linking CXX executable Telegram`
`collect2: fatal error: ld terminated with signal 9 [Killed]`
`compilation terminated.`
`/usr/local/lib/libavcodec.a(mpegvideo.o): In function memset:`
`/usr/include/x86_64-linux-gnu/bits/string3.h:81: warning: memset used with constant zero length` `parameter; this could be due to transposed parameters`
`make[2]: *** [Telegram] Error 1`
`make[1]: *** [CMakeFiles/Telegram.dir/all] Error 2`
`make: *** [all] Error 2`

**Comment by stek29** [comment]
> /usr/local/lib/libavcodec.a(mpegvideo.o)

I believe something is wrong with ffmpeg.

**Comment by john-preston** [comment]
@stek29 The link termination has nothing to do with this warning, I get this warning on my successfull builds. Looks like the linker is out of memory or smth.

**Comment by stek29** [comment]
@john-preston indeed, it likely should not die with signal 9 because of that
