### ISSUE TITLE
What about using CMake

### ISSUE THREAD

**Issue by paulolieuthier** [telegramdesktop/tdesktop#431]
I didn't see any issue related to that, but I can't believe it has never been discussed. What are the devs' opinions about using CMake? I love telegramdesktop and I wish its codebase was more organized. Using CMake the devs would keep using their favorites IDEs, on any platform, and maintain an unique build file.

**Comment by inferrna** [comment]
Vote this. As for now build instructions looks crazy.

**Comment by telegramdesktop** [comment]
Well, I don't know, how to do that right, so anyone who can translate crazy instructions to a cmake project can do this for all others who love using cmake.

**Comment by stek29** [comment]
Maybe qmake could be "converted" some way? I'd love to use CLion with TDesktop...

**Comment by auchri** [comment]
Maybe someone can try https://github.com/benapetr/q2c or https://cmake.org/Wiki/CMake:ConvertFromQmake (Instructions: http://www.executionunit.com/blog/2014/01/22/moving-from-qmake-to-cmake/)

**Comment by paulolieuthier** [comment]
I think it doesn't make sense to add CMake as another build tool. It would make a lot of sense to just use it, and remove the others. That's because it's actually a build system generator. So it would generate build files for all real build systems.

@telegramdesktop feel free to close the issue.

**Comment by stek29** [comment]
Thx dear @paulolieuthier for allowing, he was waiting just for you!

**Comment by Aokromes** [comment]
@paulolieuthier you can close the issues you open :)

**Comment by paulolieuthier** [comment]
I just meant I didn't care about the issue anymore, and maybe no one else, so it could be discarded, it the guy didn't care as well. Glad to have entertained you guys.

**Comment by stek29** [comment]
No, I still care!

**Comment by mcirsta** [comment]
Actually I just ran across this issue that I needed gyp to generate CMake and then CMake to build on Linux.
 I can provide an entirely CMake build script for Linux if it will be accepted upstream and then I can also tweak it to work on Windows and maybe even OS X.
 As far as I know even Google is moving away from gyp and while I personally don't have anything against gyp I just think it's a bit cumbersome to use and understand while I prefer CMake.

**Comment by john-preston** [comment]
@mcirsta Google moved from gyp to gn, not to cmake. We will stick with gyp for now, it generates really nice Visual Studio and Xcode projects.

**Comment by mcirsta** [comment]
@john-preston  Thanks for the reply. Yes I know they moved to gn and not to cmake. I was just saying that the gave up on gyp. 
 I'm trying to package telegram-desktop for a Linux distribution and it's turning out to be quite complicated. The first problem was that no other package is using gyp to build so I would have to include it just for telegram-desktop.
 Doesn't cmake generate nice projects for Visual Studio and Xcode these days ?

**Comment by Aokromes** [comment]
For visual studio at least yes.
