### ISSUE TITLE
Sharing via share button in Mac OS

### ISSUE THREAD

**Issue by utegental** [telegramdesktop/tdesktop#4310]
### Steps to reproduce
Trying to share photo via "Share" button in Photos app.

### Expected behaviour
 Don't see "Telegram" in menu to choose the way to share.

### Actual behaviour
Must be able to see share telegram in sharing options. Also it would be good to make Drag-n-Drop to share working.

### Configuration
**Operating system:**
macOS High Sierra 10.13.2
**Version of Telegram Desktop:**
1.2.6

**Comment by stek29** [comment]
#1983

**Comment by Axierastos** [comment]
Is there a solution to this, or it is just not possible yet?

**Comment by miickiie** [comment]
Any progress / update ?

**Comment by john-preston** [comment]
@miickiie No progress, sorry.
