### ISSUE TITLE
[Night Mode] Background remains unchanged if set to not default

### ISSUE THREAD

**Issue by andreyorst** [telegramdesktop/tdesktop#4311]
### Steps to reproduce
1. Change background in the settings
2. Turn on night mode - background will stay the same
3. Turn off night mode
4. change background to default one (flowers)
5. Turn on night mode - the background will change to dark plain color

### Expected behaviour
Background should be changed to dark plain color unless user specified a background for night mode.
### Actual behaviour
Only default image work with night mode.

[Affects multiple users](https://github.com/telegramdesktop/tdesktop/issues/4177#issuecomment-351878358)
### Configuration
**Operating system:**
Linux, windows
**Version of Telegram Desktop:**
1.2.6, 1.2.8 alpha
**Used theme**:
default

</details>

**Comment by stek29** [comment]
#3835
