### ISSUE TITLE
Lots of sticker packs causing massive lags

### ISSUE THREAD

**Issue by Rutori** [telegramdesktop/tdesktop#4312]
I have a lot of stickers on my account (something around 50 packs).
And today I discovered, that if you open sticker menu (causing stickers to load) and start scrolling, application starts taking more and more RAM. My personal record — 900mb.
To be sure, I cleared cache and that didn't help.
Also, when I restart application, all stickers are loading again from the servers everytime.

I believe, that this is because stickers have no cache whatsoever.

**Comment by john-preston** [comment]
@Rutori They start loading from servers again if you clear the cache.

**Comment by Rutori** [comment]
@john-preston Yes, I understand that, but even if I don't clear the cache, they are loading from the servers over and over again, when I'm restarting the app.

**Comment by stek29** [comment]
@Rutori How does RAM usage show what's loaded from cache and what's loaded from server side?

**Comment by Rutori** [comment]
on, nevermind. For some reason I can't reproduce this bug anymore. Guess it's fixed or maybe something else caused memory leak

**Comment by Rutori** [comment]
Actually it wasn't stickers. 
So, the thing is, when I open gif panel (I have a lot of gifs), Telegram.exe starts taking up nearly 1 GB of RAM almost immediately

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1317
