### ISSUE TITLE
Forwarding several albums works not as expected

### ISSUE THREAD

**Issue by rouqs** [telegramdesktop/tdesktop#4313]
### Steps to reproduce
1. send 13 images as 2 albums(10 in first one and 3 images in second) to your "saved messages" chat. 
2. forward them to another chat/group.
done. 
### Expected behaviour
images are sent as 2 albums as they were in saved messages chat. (as 2 albums, first - 10 images, second - 3 images)

### Actual behaviour
telegram forwards them as : album of 5 images, then 5 images separately(one by one) and then album of 3 images. 

### Configuration
**Operating system:** macOS 10.13.2

**Version of Telegram Desktop:** 3.7.3.114679 stable

**Used theme**: night blue 
**Additional details** also it changes how it sends images when amount of images changes. for 12 and less images it works as intended, but with 13 and more it starts to divide albums into separate images, for example when you forward 2 albums of 20 images in total, it sends them as: album of 5 images, 6 separate images, album of 2 images,3 separate images, album of 4 images.

**Comment by lampanon** [comment]
You choose the wrong github page. This repository refers to cross-platform Telegram Desktop, while you are using a native client for mcaOS whose repository is located here: https://github.com/overtake/TelegramSwift

**Comment by rouqs** [comment]
oh my bad, thanks
