### ISSUE TITLE
Resizing window changes message layout

### ISSUE THREAD

**Issue by jagloro** [telegramdesktop/tdesktop#4314]
### Steps to reproduce
In a direct message chat, change the width of the window from small to large. 

### Expected behaviour
Layout remains the same and there should be a setting to choose preferred layout instead it being based on window width

### Actual behaviour
Messages switch between left/right layout and vertical message layout

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.2.6

**Used theme**:
Custom?

**Comment by ErmiShady** [comment]
Nigga Update your app

**Comment by jagloro** [comment]
1.2.7 and 1.2.8 are in pre-release.  Do they have the fix?

**Comment by jagloro** [comment]
![screenshot 6](https://user-images.githubusercontent.com/8039832/35033496-bca825d0-fb1f-11e7-9556-32f70bb31a00.png)
![screenshot 7](https://user-images.githubusercontent.com/8039832/35033497-bcc98b08-fb1f-11e7-893f-34a5ca6f1842.png)

I've attached two screenshots as an example in case I am being misunderstood.

**Comment by auchri** [comment]
There is a setting for that 😉
