### ISSUE TITLE
[MacOS] Character Viewer

### ISSUE THREAD

**Issue by N9199** [telegramdesktop/tdesktop#4315]
### Steps to reproduce
Try to use character viewer by mantaining a key pressed.

### Expected behaviour
Should open a menu to choose from the possible alternate characters

### Actual behaviour
Doesn't happen

### Configuration
**Operating system:**
MacOS Sierra 10.13.2
**Version of Telegram Desktop:**
1.2.6
**Used theme**:
None
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
#1939
