### ISSUE TITLE
Textbox is sometimes cleared after sending the previous message (linux)

### ISSUE THREAD

**Issue by OlegWock** [telegramdesktop/tdesktop#4316]
### Steps to reproduce
1. Use slow internet
2. Send  message to any chat
3. Start typing new message before the previous message is sent
4. When message will be sent, sometimes textbox will be cleared 

### Expected behaviour
The new message should remain

### Actual behaviour
When message will be sent, sometimes textbox will be cleared. I can't say for sure in what cases this happening, maybe when message sending takes too much time

### Configuration
**Operating system:** Ubuntu 16.04

**Version of Telegram Desktop:** v 1.2.6

**Used theme**: Doesn't matter

**Comment by stek29** [comment]
Can you try ctrl+z / cmd+z / rmb+undo? Do they bring text back?

**Comment by OlegWock** [comment]
Yes,Ctrl+Z brings text back

**Comment by stek29** [comment]
Then it's a feature

**Comment by OlegWock** [comment]
But this is not obvious (and even harmful behavior). Why clean the field if the user started typing?

**Comment by stek29** [comment]
What about user typing a message, then picking up the phone, editing and sending it from there?

**Comment by OlegWock** [comment]
I think this happens much less often than just missing half of the message
