### ISSUE TITLE
Secret chat doesn't delete all the messages

### ISSUE THREAD

**Issue by iamserjo** [telegramdesktop/tdesktop#4318]
### Steps to reproduce
1. create a secret chat and set timer to 5 sec
2. type range from 1 to 9 every 500 ms (approximately) 
3. now you can see part of messages are still in the owner chat (in my case left messages are 3 6 9)

### Configuration
**Operating system:**
Mac OS high sierra latest update

**Version of Telegram Desktop:** 3.7.3.114679 appstore

**Used theme**: dark

**Comment by john-preston** [comment]
@iamserjo This is not Telegram Desktop, but another macOS Telegram app. See https://github.com/overtake/TelegramSwift
