### ISSUE TITLE
Coub instant view has no sound

### ISSUE THREAD

**Issue by horuktaras** [telegramdesktop/tdesktop#4320]
Hi, guys. First of all, want to say thanks for your work and great product. 

### Steps to reproduce
1. Copy a link from coub.com (Coub contains coubs and it is a looping video with music). E.g. http://coub.com/view/11fait
2. Paste this link into any chat in Telegram

### Expected behaviour
As user, I expect to see looping video with sound

### Actual behaviour
I can see only looping video. Without sound 

### Configuration
**Operating system:** WIN 10 64x

**Version of Telegram Desktop:** 1.2.6

**Used theme**: default dark

Thanks for ur attention.

**Comment by stek29** [comment]
Preview is generated on server side

**Comment by horuktaras** [comment]
@stek29 I understood. 
I'll search some way to create a ticket on their side.
Thanks

**Comment by belko-letyago** [comment]
But why telegram client for android can play coubs with sound?

**Comment by stek29** [comment]
@belko-letyago because it has special handling for coub/youtube/etc, showing embed in a webview. TDesktop doesn't have that and likely won't because bundling a full-featured browser is going to be messy.
