### ISSUE TITLE
Monospace font not rendered

### ISSUE THREAD

**Issue by flyingrub** [telegramdesktop/tdesktop#4323]
### Steps to reproduce
1.  Open Telegram
2.  Write or receive message with ` around it

### Expected behaviour
The text should be displayed

### Actual behaviour
The character are rendered like this ▯

It is the same on my theme and on the original theme.

### Configuration
**Operating system:*Arch Linux*

**Version of Telegram Desktop:*1.2.6-5*

**Comment by stek29** [comment]
Are you using official binary from desktop.telegram.org / telegram-desktop-bin from AUR?

**Comment by flyingrub** [comment]
Yep

**Comment by stek29** [comment]
Do you have Consolas, Liberation Mono, Menlo or Courier fonts installed?

**Comment by flyingrub** [comment]
It works after installing consolas. Thanks for your help.
