### ISSUE TITLE
i think telegram was attacked by man in the middle !!!

### ISSUE THREAD

**Issue by ghorbani77** [telegramdesktop/tdesktop#4326]
### Steps to reproduce
1. im from iran , my telegram was closed automatically . its may be a bug but i thinks telegram`s data was thiefed from some servers . 

2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@ghorbani77 It was crashing the last couple of days because of a server bug and a client bug. Server bug was fixed, client bug will be fixed in the next update, but it should not crash already.
