### ISSUE TITLE
Telegram client uploads mp3 as file

### ISSUE THREAD

**Issue by dzharikhin** [telegramdesktop/tdesktop#4327]
### Steps to reproduce
1. Try to add mp3 file (I'd rather say the bug relates to files with > 10Mb size, but there's no straight correlation)

### Expected behaviour
The mp3 file is uploaded with music content-type

### Actual behaviour
The mp3 file is uploaded as file - no embedded player available

### Configuration
**Operating system:** Ubuntu 17.10

**Version of Telegram Desktop:** 1.1.23

**Used theme**: default

**Comment by SonicoXD** [comment]
I second this. It happens with probably any audio file, as I use AAC and have the same issue. However, if the music file is sent from Telegram for Android or Telegram X using the Music button, it gets "optimized" and thus it can be played through Telegram.

**Comment by SonicoXD** [comment]
Turns out the problem only happens on Linux, probably on Mac OS too. On Windows, any file format of any size (except WAV) uploads fine.

**Comment by rackelhahn69** [comment]
I've got the same problem on manjaro linux (everything updated to the latest release). It's been like that for a while now.

**Comment by rackelhahn69** [comment]
I just found out that removing the cover-image with EasyTAG solves the problem for me.

**Comment by killingkind** [comment]
I did some testing and it seems that Telegram only uploads with 'music' content-type if the file size is less than 10 mb. Removing the cover image makes the file smaller that's why it worked.

**Comment by agura-lex** [comment]
Same here on Linux (Arch, to be more specific). According to my testing, it has nothing to do with file size. I tried files larger and smaller than 10 MB. It seems that the issue is a album cover as @rackelhahn69 pointed out. Removing it doesn't make a huge difference in size after all, so it's definitely not a size-related issue (at least I can't confirm that it is).

**Comment by rackelhahn69** [comment]
It is definitely not related to the size in my case. Removing the cover image solves the problem for audio files of different sizes.

I'm running Manjaro Linux on my Desktop as well as on my Laptop. I have them both updated to the latest releases and have the same version of Telegram installed. On my Laptop though I can upload mp3-files with cover images as audiofiles without any problems. I probably have some package(s) installed on my Laptop that is/are missing on my Desktop.

**Comment by agura-lex** [comment]
@rackelhahn69, could you please `diff -u` your packages lists and try to find out which one fixes the problem? That would be cool and we can ask distro maintainers to include needed package as a dependency or optdep at least.

**Comment by HUMZZY** [comment]
Change by password ASAP let apple block it Sam

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lmcsu** [comment]
Facing the same issue, mp3 files with covers and size more than 10MB don't upload as music files on my Ubuntu. Removing covers with EasyTAG solves the problem. Telegram Desktop version 1.5.11

**Comment by rackelhahn69** [comment]
> @rackelhahn69, could you please `diff -u` your packages lists and try to find out which one fixes the problem? That would be cool and we can ask distro maintainers to include needed package as a dependency or optdep at least.

<details><summary>Packages installed on laptop and not installed on desktop</summary>
<p>

```
arc-icon-theme
arpack
atomicparsley
autoconf-archive
bleachbit
bogofilter
caribou
catfish
cblas
chrpath
clamav
clang
cmark
compiler-rt
confuse
corebird
ctags
ctpl
cython
cython2
dkms
dleyna-connector-dbus
dleyna-core
dleyna-server
dmd
docbook-xml
docbook-xsl
docbook2x
electron2
enca
evolution-bogofilter
evolution-spamassassin
faba-icon-theme
fltk
gconf-editor
gconf-sharp
geany
geany-plugins
gegl02
gespeaker
ghc
gitg
gksu
gl2ps
glib2-docs
glpk
gmime
gnome-common
gnome-documents
gnome-encfs-hg
gnome-online-miners
gnome-power-manager
gnome-python
gnome-shell-extension-no-topleft-hot-corner
gnome-shell-pomodoro
gobject-introspection
graphicsmagick
graphviz
grub-customizer
gstreamer0.10
gstreamer0.10-base
gstreamer0.10-base-plugins
gtk-doc
gts
gucharmap
gupnp-av
haskell-cmark
haskell-extensible-exceptions
haskell-filemanip
haskell-foundation
haskell-lifted-base
haskell-math-functions
haskell-mmorph
haskell-monad-control
haskell-mwc-random
haskell-nats
haskell-semigroups
haskell-transformers-base
haskell-unix-compat
haskell-vector-th-unbox
help2man
hwloc
idnkit
ipython
itstool
java-environment-common
jdk10-openjdk
jdk8-openjdk
jemalloc
jre10-openjdk
jre10-openjdk-headless
js
js38
jupyter
jupyter-nbconvert
jupyter-nbformat
jupyter-notebook
jupyter-widgetsnbextension
jupyter_console
kbfs
keybase
keybase-gui
lcms
lib32-libtxc_dxtn
libappindicator-gtk3
libcurl-compat
libdbusmenu-gtk3
libev
libftdi
libgit2
libgit2-glib
libgksu
libgnome-keyring
libicuid
libindicator-gtk3
libkate
libkeybinder2
libmspack
libnm-gtk
libphobos
libreoffice-still
libreoffice-still-de
libreoffice-still-en-gb
libtiger
libtracker-sparql
libtxc_dxtn
libusb-compat
libutf8proc
libwnck
libxfont
libxxf86dga
libzapojit
linux49
linux49-r8168
lirc
lua-socket
lua51
macchanger
mallard-ducktype
manjaro-gnome-extension-settings-17.0
manjaro-gnome-settings-17.0
manjaro-wallpapers-17.0
mathjax
maven
mercurial
meson
mhwd-nvidia-304xx
moka-icon-theme
mplayer
mtools
net-tools
netlogo
networkmanager-dispatcher-ntpd
nghttp2
nicotine+
ninja
nlopt
numactl
numix-folders-git
nvm
octave
onedrive-git
openjade
openjdk8-doc
openmpi
opensp
package-query
paprefs
patchelf
pcmciautils
pdfgrep
perl-authen-sasl
perl-canary-stability
perl-cgi
perl-common-sense
perl-convert-binhex
perl-crypt-openssl-bignum
perl-crypt-openssl-random
perl-crypt-openssl-rsa
perl-crypt-ssleay
perl-datetime-format-iso8601
perl-digest-hmac
perl-digest-sha1
perl-io-socket-inet6
perl-io-stringy
perl-json
perl-json-xs
perl-locale-gettext
perl-mail-authenticationresults
perl-mail-dkim
perl-mail-spf
perl-mediawiki-api
perl-mime-tools
perl-net-dns
perl-net-dns-resolver-mock
perl-net-ip
perl-net-smtp-ssl
perl-netaddr-ip
perl-path-class
perl-sgmls
perl-socket6
perl-term-readkey
perl-types-serialiser
perl-xml-sax-expat
perl-yaml-libyaml
python-anytree
python-atspi
python-bleach
python-boto
python-boto3
python-botocore
python-bz2file
python-cachecontrol
python-colorama
python-dateutil
python-decorator
python-defusedxml
python-distlib
python-entrypoints
python-gensim
python-geojson
python-html2text
python-html5lib
python-ipykernel
python-ipywidgets
python-jedi
python-jinja
python-jmespath
python-jsonschema
python-jupyter_client
python-jupyter_core
python-lockfile
python-markdown
python-mistune
python-msgpack
python-nltk
python-numpy
python-pandocfilters
python-parso
python-pep517
python-pickleshare
python-pip
python-progress
python-prometheus_client
python-prompt_toolkit
python-pyrsistent
python-pytoml
python-pyzmq
python-retrying
python-s3transfer
python-scipy
python-send2trash
python-smart_open
python-terminado
python-testpath
python-tornado
python-traitlets
python-wcwidth
python-webencodings
python-wheel
python-yaml
python2-gconf
python2-gnomekeyring
python2-keybinder2
python2-numpy
python2-virtualenv
qhull
qrupdate
qscintilla-qt5
qt4
rar
re2c
recode
riot-desktop
riot-web
samsung-unified-driver
samsung-unified-driver-common
samsung-unified-driver-printer
samsung-unified-driver-scanner
sdl_image
serf
sgml-common
source-highlight
spamassassin
subversion
sundials
swig
transmission-sequential-gtk
vala
vte
whatsapp-web-desktop
wireguard-dkms
xorg-fonts-misc
xorg-server-devel
xorg-util-macros
xorg-xprop
yajl
yaourt
yarn
yelp-tools
zd1211-firmware
```

</p>
</details>

It's any of those 301 packages :grimacing: 
The Manjaro installation on my laptop is four years old and I have never cleaned up anything...
I've tested many mp3-files on my laptop and all of them get uploaded as expected... no matter the size or whether there's a cover image

It's not the kernel (It also works with 4.19 on my laptop) and it's also not `recode`.

Any ideas?

**Comment by mautematico** [comment]
Having same issue on Telegram Desktop 1.5.11

any mp3 file that contains cover-image etag won't be uploaded as music, but as file.
if cover-image etag is removed, then mp3 file is uploaded as audio file correctly

**Comment by agura-lex** [comment]
> > @rackelhahn69, could you please `diff -u` your packages lists and try to find out which one fixes the problem? That would be cool and we can ask distro maintainers to include needed package as a dependency or optdep at least.
> 
> Packages installed on laptop and not installed on desktop
> 
> It's any of those 301 packages grimacing
> The Manjaro installation on my laptop is four years old and I have never cleaned up anything...
> I've tested many mp3-files on my laptop and all of them get uploaded as expected... no matter the size or whether there's a cover image
> 
> It's not the kernel (It also works with 4.19 on my laptop) and it's also not `recode`.
> 
> Any ideas?

After digging through the list, reading descriptions and installing different packages from the list unfortunately couldn't find anything useful, I might try just installing all of them sometime, but I'm skeptical about that. That might be some DE-specific issue as well, I guess. I'm using KDE Plasma.

**Comment by lmcsu** [comment]
Telegram Desktop 1.8.8, Ubuntu 19.10, still not fixed

**Comment by Aokromes** [comment]
atm telegram desktop is 1.8.15

**Comment by mikosh75** [comment]
Latest Telegram for iOS 5.12.2 still not fixed. MP3 over 10MB with cover image is uploaded as file and no audio player possible.
Please fix it, thanks!

**Comment by Aokromes** [comment]
5.12.2 doesn't belongs here.

**Comment by mikosh75** [comment]
> 5.12.2 doesn't belongs here.

Sorry, I saw only now that this repo is for telegram desktop... do you know where I can  file an issue for iOS app? Thanks!

**Comment by Aokromes** [comment]
@tgiostests

**Comment by maximgrafin** [comment]
same issue on the web version and in the android app

**Comment by TNTcraftHIM** [comment]
same issue here on debian 10
