### ISSUE TITLE
[new feature] Multiple accounts

### ISSUE THREAD

**Issue by vagkaefer** [telegramdesktop/tdesktop#4328]
### Steps to reproduce, Expected behaviour, Actual behaviour, Configuration, Version and Theme:
Not applicable

### new feature
The mobile version of Telegram has some features that the Desktop version does not have. I currently have two mobile numbers, I use two accounts on my cell phone, but on the desktop this is not possible. To solve this, I have to leave the web.telegram.org with one account, while the desktop telegram uses another.

Is there any progress to make this option available?

I'm a computer engineer, I've never worked with the telegram apps, but if you tell me the way, I can try to help with this task. Tks

-----
Ps: I readed the contributing and i saw: Unfortunately we do not merge any pull requests that have new feature implementations, translations to new languages and those which introduce any new user interface elements. ;/

Then, exists some provision of this feature?

**Comment by stek29** [comment]
#4261. Use search.
