### ISSUE TITLE
Update Telegram Desktop via Proxy

### ISSUE THREAD

**Issue by chall3ng3r** [telegramdesktop/tdesktop#4332]
### Steps to reproduce
1. Start portable or stable version of Telegram on PC
2. Check for updates

### Expected behaviour
Telegram should look for and download an application update through proxy provided in settings, which is already used for connecting to Telegram service.

### Actual behaviour
For countries where Telegram is blocked, users are able to use a HTTP or SOCKS proxy to connect to service, but Telegram application is not updated through proxy. 

### Configuration
**Operating system:**
Windows 10 Pro 64bit (build 16299.192)

**Version of Telegram Desktop:**
1.2.8 alpha

**Used theme**:
Default - Night Mode

**Comment by john-preston** [comment]
@chall3ng3r It should use http proxy, but not socks proxy.

**Comment by chall3ng3r** [comment]
@john-preston thanks for reply.

Well, there's option to either use SOCKS or HTTP in Telegram, and I'm using private SOCKS proxy which was easy for me to setup. Would not use public HTTP proxies for it. 

Is it possible to push updates on Telegram service's connection? Like sending media / file to chats? 

So it'd be pretty simple, if messages can get through, so does the app update.

**Comment by john-preston** [comment]
@chall3ng3r The idea was to make update available if the messages can't get through. Currently there is no way to download updates through mtproto :(

**Comment by chall3ng3r** [comment]
And I've got an idea 💡

I'll try to setup a bot, which will look for updates, and send the installer attached in a message when there's a new release. #UpdateBot

**Comment by linjan** [comment]
@chall3ng3r how its going?

**Comment by chall3ng3r** [comment]
Hey,

I got a bit busy, but its on my list as I still have to download and install updates manually and on each download, it reminds of this. Will be posting soon update on it.

**Comment by john-preston** [comment]
@omkarnathsingh The updates should use socks5 or http proxy starting from 1.2.18 if you use one of those in the connection settings.

**Comment by omkarnathsingh** [comment]
@john-preston wow. Thats great to hear. Users can now get updates easily everywhere. Thanks.

**Comment by chall3ng3r** [comment]
This is great news @john-preston!

Thank you for adding support for it. Been updating manually for quite some time.
