### ISSUE TITLE
Mark selected message(s) as unread

### ISSUE THREAD

**Issue by Deilan** [telegramdesktop/tdesktop#4333]
Please make an option of marking selected messages or a chat as unread. If it's not already supported by the API, then make it just for the current client app.

**Comment by auchri** [comment]
Please search for existing issues 😉

**Comment by Deilan** [comment]
@auchri I did. Hence, here's a suggestion to do it despite of API support.

**Comment by anatolyborodin** [comment]
@auchri you mean #3716 ?

**Comment by auchri** [comment]
@anatolyborodin yes
