### ISSUE TITLE
Emoticon, Stickers and Gifs menu gets in the way of editing in Telegram Desktop

### ISSUE THREAD

**Issue by DanFoxDavies** [telegramdesktop/tdesktop#4335]
### Steps to reproduce
1. Mistype a message to someone.
2. Move your mouse to your message in the bottom right of the app, to try to right click on it and edit.
3. Notice that your mouse pointer has accidentally crossed the smiley button for the emoticons, stickers and gifs menu, and so has popped up that menu in the way, preventing a fast edit.

### Expected behaviour
Tell us what should happen

The smiley button for that menu should be on the left, next to the attachment button, so as to avoid accidental hovers when editing messages.

### Actual behaviour
Tell us what happens instead

The smiley button is on the right, in the path of mouse movements for edits of one's own messages.

### Configuration
**Operating system:**
Kubuntu 17.10 Linux 4.14.14

**Version of Telegram Desktop:**
1.2.6

**Used theme**:
Night Mode

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by DanFoxDavies** [comment]
This is just a straightforward suggestion for streamlining UX, really.
To be clear, this problem doesn't prevent me editing the message a few seconds later once I've moved the mouse off the menu and allowed it time to disappear, but it does break up the flow and give colleagues time to notice I made a mistake.

**Comment by DanFoxDavies** [comment]
it also gets in the way of the 'skip to end' button, I notice, on occasions of mouse pointer overshoot.

**Comment by stek29** [comment]
#1333

**Comment by stek29** [comment]
I feel you :)
