### ISSUE TITLE
Add inline links

### ISSUE THREAD

**Issue by roi-shtivi** [telegramdesktop/tdesktop#4336]
### Steps to reproduce
1.  Create an inline link
2. 
3. 

### Expected behaviour
"[reddit]-(https://www.reddit.com)" will result a shorten size link. [reddit](https://www.reddit.com)

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
What do you mean by inline link? Links with custom text?

**Comment by roi12381** [comment]
Not a full text link. Insteat of writing "https://google.com/23as4cgg=9d?34" it will just show the name that you want to represent  the link. In the example the name was "reddit" and not the full addres. You have this feature in "Markdown"

**Comment by stek29** [comment]
#3218 was closed when server-side wasn't accepting such links from user, but now it does.
