### ISSUE TITLE
Telegram quality

### ISSUE THREAD

**Issue by Hexawolf** [telegramdesktop/tdesktop#4338]
# Some harmful things down there, prepare to get offended!

* [The sound in Telegram is terrible](https://github.com/procxx/kepka/issues/66). Unable to test precisely with mobile Telegram, but [true for the official desktop version](https://github.com/telegramdesktop/tdesktop/issues/2580).
* [Telegram started draining a lot of energy](https://imgur.com/a/i4Qo6) since [calls was invented](https://www.reddit.com/r/Telegram/comments/638hjz/telegram_using_a_lot_of_battery_android/). I'm not sure about reports, since reporting such issue requires collecting a lot of technical data.
* Maybe it worths thinking about telemetry? The word "telemetry" is considered harmful, but under such conditions it would be good for developers to know about Telegram average battery drain and other similar but still useful things.
* The. God. Damn. Leaks. I'm not even [talking about this](https://github.com/telegramdesktop/tdesktop/commit/2432845df2f08bffa8380650066431cac6e95cc5) or about the indian code itself, but there [are](https://github.com/procxx/kepka/issues/59) damn [leaks](https://github.com/procxx/kepka/issues/58) (actually even in mobile version but unable to confirm). [More](https://github.com/telegramdesktop/tdesktop/issues/3034), [MORE](https://github.com/telegramdesktop/tdesktop/issues/1317), Even [Valgrind report](https://imgur.com/a/gRoB4) (actually quite outdated, but things aren't getting better). Not even talking about security: it is broken simply because Telegram leaks just like a [japan girl](https://imgur.com/a/88x3V).
* Even [this](https://github.com/procxx/kepka/issues/31) isn't going to backport UI/UX changes. You guys **broke the user experience**, [just like Gnome](https://www.reddit.com/r/archlinux/comments/77btio/what_happened_to_gnomes_system_tray/). It was perfect. Please, get in touch with people!

Take this as an act of rage. But I've just grouped all critical things that require (but do not receive) attention. Later I'm probably going to increase this list.

_you should have expected someone to make this_

**Comment by john-preston** [comment]
1. (sound) fixing pull requests are welcome.
2. doesn't belong here, this repository is about Telegram Desktop only.
3. doesn't belong here as well.
4. why procxx/kepka issues? Telegram Desktop keeps all messages and images in memory, so the memory consumption grows, security is irrelevant here.
5. I don't even understand what's your problem here.

**Comment by Hexawolf** [comment]
2. So laptops don't exist at all.
3. I disagree with your answer.
4. Sorry, but you're saying sanitizers are wrong.

**Comment by john-preston** [comment]
2. You've linked android screenshots and issues. Power consumption can't have anything to do with calls on desktop.
4. There could be some real leaks as well, but should not be much, there is still small amount of manual memory management. Fixing pull requests are welcome as well.
