### ISSUE TITLE
Maximize Telegram from system tray shortcut

### ISSUE THREAD

**Issue by Jacobtey** [telegramdesktop/tdesktop#4339]
### Steps to reproduce
1. Start Telegram
2. Press Alt+F4 to minimize Telegram to system tray
3. Can't find a shortcut to maximize Telegram from system tray

### Expected behaviour
Some shortcut to maximize Telegram from system tray

### Actual behaviour
No shortcut to maximize Telegram from system tray

### Configuration
**Operating system:**
Kernel: _4.14.14-1-MANJARO x86_64_ Desktop: _KDE Plasma 5.11.5_ Distro: _Manjaro Linux Hakoila 17.1.2_

**Version of Telegram Desktop:**
1.2.6

**Used theme**:
custom myself called rsm

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by aiamuzz** [comment]
Its more than a year and no response to this request ... this would have been a useful feature !!!

I use telegram on linux ... things are so bad with me that a single left click on the telegram app icon in system tray does not bring up the application window ... the only way is to right click the systray icon and choose from the menu to bring up the application on the desktop.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/3b4dfa138176b4d1e3cb14be1be638ebe2f52713
