### ISSUE TITLE
Duplicate icon when application is pinned to Windows 10 taskbar

### ISSUE THREAD

**Issue by zoncrd** [telegramdesktop/tdesktop#4346]
### Steps to reproduce
1. Install Telegram Desktop client on Windows 10
2. Pin Telegram Desktop to taskbar
3. Launch Telegram Desktop

### Expected behaviour
After launch taskbar Telegram Desktop icon shows highlighted.

### Actual behaviour
Telegram Desktop icon is duplicated:  when you launch it opens in another taskbar icon.
![immagine](https://user-images.githubusercontent.com/6806779/35381271-019fe806-01bc-11e8-839a-bd7448e17397.png)

### Configuration
**Operating system:** Windows 10 Pro, Version 10.0.16299 build 16299

**Version of Telegram Desktop:** Version 1.2.6

**Used theme**: Default (Night mode : ON)

**Comment by SmartManoj** [comment]
The targets are
Telegram.exe -autostart (after update)
Telegram.exe

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/59990251-05cf2880-9660-11e9-9be2-1db1789cccae.png)

1st one is shortcut pinned in Taskbar
2nd one is launched after update

**Comment by SmartManoj** [comment]
Still

**Comment by gorghino** [comment]
I started having this from a week.
Version 1.8.1

**Comment by SmartManoj** [comment]
Not getting in Telegreat

**Comment by oferrotem** [comment]
Same here with version 1.8.15

**Comment by Aokromes** [comment]
cannot reproduce on windows 10 1909 + telegram desktop 1.9.9

**Comment by manuelpelloni** [comment]
Still having this issue with version 2.4.3 and windows 10 2004

**Comment by SmartManoj** [comment]
Don't think so

**Comment by manuelpelloni** [comment]
I tried to reinstall telegram but it didn't work, then I`ve deleted the telegram folder and cleaned the windows registry, after doing that I reinstalled telegram again and it was all fixed

**Comment by SmartManoj** [comment]
@zoncrd 

> Still having this issue with version 2.4.3 and windows 10 2004

**Comment by SmartManoj** [comment]
Still in 2.4.4.2

After the update, Telegram launches without any argument. This cause the bug

**Comment by CastagnaIT** [comment]
same problem with 2.5.1 an annoying problem
having to move the icon on the taskbar manually every time you turn on the computer

**Comment by imanprs** [comment]
Had the same problem with version 2.7.4.
A simple workaround is to unpin the original pinned program, right click on the other one that is the active window of telegram and pin that one instead.

**Comment by soredake** [comment]
Still a problem.

**Comment by LuizBarros99** [comment]
Still happens currently.
My windows is Windows 10 Pro, version 21H2.

**Comment by aandac** [comment]
I had a similar issue with Windows 11 Version 21H2 OS build 22000.493.
@SmartManoj [suggestion is working](https://github.com/telegramdesktop/tdesktop/issues/4346#issuecomment-504845681) 👍

**Comment by soredake** [comment]
It's still a problem.

**Comment by yonaesp** [comment]
the problem persists

**Comment by ilya-fedin** [comment]
Does the bug go away if you enable Windows notifications in Telegram's notifications settings?

**Comment by soredake** [comment]
@ilya-fedin unfortunately, no.

**Comment by ilya-fedin** [comment]
@soredake are you sure? it can become duplicate once you start tdesktop with the option enabled, but after you re-pin tdesktop this should stop happening at the notification implementation sets AppUserModelId explicitly.

**Comment by soredake** [comment]
@ilya-fedin after re-pin of telegram shortcut there is no duplicate, yes, but unfortunately, this option is not enabled by default, so bug is still valid.

**Comment by soredake** [comment]
@ilya-fedin yes, after enabling native notifications and launch at startup option (and re-pinning) there is no duplicate icon anymore.

**Comment by Be1zebub** [comment]
any news? this is a very annoying issue

**Comment by ilya-fedin** [comment]
I'm highly doubt there will be any news given that the issue is very minor. I've tried to propose @john-preston to always have explicit AppUserModelId set but he ignored me every time I asked that. Apparently he is not ready to do that so you have no other choice than to get used to the behavior or enable native notifications.
