### ISSUE TITLE
emoji&stickers menu, annoying

### ISSUE THREAD

**Issue by ProbeKeeper** [telegramdesktop/tdesktop#4347]
### Steps to reproduce
 always

### Expected behaviour
Tell us what should happen

### Actual behaviour

every time I move cursor from somewhere else to messages area, the emoji menu will be triggered( cursor just  move across the emoji button, maybe stay for  1ms ?) then I cannot but wait for the menu to disappear. i cant see what my friends said during the period.  it drives me insane.
![tl](https://user-images.githubusercontent.com/17715262/35402118-82adf6e8-0236-11e8-995c-edff9f43bf65.png)

### Configuration
**Operating system:** windows10

**Version of Telegram Desktop:**
1.26
**Used theme**:
default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

every time I move cursor from somewhere else to messages area, the emoji menu will be triggered( cursor just  move across the emoji button, maybe stay for  1ms ?) then I cannot but wait for the menu to disappear. i cant see what my friends said during the period.  it drives me insane.
</details>

**Comment by chilivili** [comment]
yes. it's very annoying.

**Comment by stek29** [comment]
#1333
