### ISSUE TITLE
Dialog "Choose Recipient" with all subscribed channels

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#4348]
### Steps to reproduce
1. RMB on any message
2. LMB "Forward message"
3. Dialog "Choose Recipient" with bots, contacts, chats and **ALL** subscribed channels

![123](https://user-images.githubusercontent.com/10371194/35405584-834af8cc-01fe-11e8-8347-49b993958686.png)

### Expected behaviour
Tell us what should happen
1. RMB on any message
2. LMB "Forward message"
3. Dialog "Choose Recipient" with bots, contacts, chats and and **only those channels in which I can send messages**

### Actual behaviour
-> Steps to reproduce

### Configuration
**Operating system:**
Win10 x64 FCU
**Version of Telegram Desktop:**
1.2.8 alpha
**Used theme**:
https://t.me/darkorangetheme
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Shelmor** [comment]
same here, would be a really great fix

**Comment by cristaloleg** [comment]
Ping. From what I see Telegram already know which chats are available for sending messages, it's only about filtering list.

**Comment by f242** [comment]
bump @john-preston @stek29

**Comment by john-preston** [comment]
@f242 Initially this was a feature :( so that you won't wonder where is some chat that you were going to send message to, but you were removed from admins or smth. And you'll see an error instead of thinking that the search doesn't work. But I guess the use case is too rare for channels, they can be filtered out.

**Comment by f242** [comment]
It hasn't been fixed yet

**Comment by f242** [comment]
guys! plz move this "feature" to command line option like -**scale** etc

**Comment by f242** [comment]
@john-preston @auchri when you remove unwanted contacts from the forwarding dialog?

**Comment by Aphotice** [comment]
2020 
still not fixed   :}
its been years... 
for someone who forwards 20+ msgs to 100 friends ... this is super-inconvenient...

**Comment by RememberTheAir** [comment]
Closed by 5120d3e?

**Comment by cristaloleg** [comment]
@RememberTheAir looks so <3
