### ISSUE TITLE
Add Markdown style option

### ISSUE THREAD

**Issue by alish123456** [telegramdesktop/tdesktop#4349]
hi
Please add options (italic ,bold,code,pre,link) to Select (highlight text) text in TextBox Message on menu RightClick

**Comment by alish123456** [comment]
@stek29 Please...

**Comment by manuelsongokuh** [comment]
this is very important AGAIN BATTLE to whatsapp..

**Comment by stek29** [comment]
Please, use the template

**Comment by manuelsongokuh** [comment]
in the template.. where is it?

**Comment by manuelsongokuh** [comment]
sorry i'm not uderstand, where is a template???

**Comment by d0tfile** [comment]
@manuelsongokuh "[when creating an issue](https://github.com/telegramdesktop/tdesktop/issues/new)", textarea is filled with template.

**Comment by manuelsongokuh** [comment]
ahh, that is for github..??
not..not.. i believe that is for telegram..telegram is missing : icon for bold, icon for italic,etc..
because telegram desktop has not , mobil (ios,android) has not this icon for bold, etc..

**Comment by stek29** [comment]
._.
