### ISSUE TITLE
Phone numbers should not be required for registering

### ISSUE THREAD

**Issue by karlcow** [telegramdesktop/tdesktop#435]
I'm one of these rare zoïds without a phone number.
The first step for using Telegram is a phone number. 

Are there plans in the future of getting rid of phone numbers for using telegram? 

PS: Slightly related, phone number creates also some privacy issues.

**Comment by auchri** [comment]
Write it to the telegram team on twitter: https://twitter.com/telegram

**Comment by telegramdesktop** [comment]
Well, I think it is not planned, because Telegram is a mobile messenger in the first place, desktop version is only after mobile.
