### ISSUE TITLE
Build failed on ninja -C out/Debug

### ISSUE THREAD

**Issue by rezam90** [telegramdesktop/tdesktop#4353]
### Steps to reproduce
I did the same steps for macos xcode.

### Expected behaviour
command ` ninja -C out/Debug` should not return any error.

### Actual behaviour
command ` ninja -C out/Debug` stopped build with: `ninja: build stopped: subcommand failed.`

### Configuration
**Operating system:** macOS high sierra 10.13.1

**Version of Telegram Desktop:** 1.2.8

**Used theme**: -

<details><summary><b>Logs</b>:</summary>

ninja -C out/Debug
ninja: Entering directory `out/Debug'
[149/339] CXX obj/client/crashpad_client.simulate_crash_mac.o
FAILED: obj/client/crashpad_client.simulate_crash_mac.o 
c++ -MMD -MF obj/client/crashpad_client.simulate_crash_mac.o.d  -I../.. -I../../compat/mac -I../../compat/non_cxx11_lib -I../../compat/non_win -I../../third_party/mini_chromium/mini_chromium -O0 -gdwarf-2 -fvisibility=hidden -Werror -Wnewline-eof -mmacosx-version-min=10.8 -arch x86_64 -Wall -Wendif-labels -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wexit-time-destructors -Wheader-hygiene -Wno-selector-type-mismatch -Wsign-compare -Wstring-conversion -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -fno-strict-aliasing -fstack-protector-all  -c ../../client/simulate_crash_mac.cc -o obj/client/crashpad_client.simulate_crash_mac.o
In file included from ../../client/simulate_crash_mac.cc:20:
../../third_party/mini_chromium/mini_chromium/base/logging.h:90:26: error: comparison of integers of different signs: 'const unsigned int' and 'const int' [-Werror,-Wsign-compare]
DEFINE_CHECK_OP_IMPL(EQ, ==)
~~~~~~~~~~~~~~~~~~~~~~~~~^~~
../../third_party/mini_chromium/mini_chromium/base/logging.h:75:14: note: expanded from macro 'DEFINE_CHECK_OP_IMPL'
      if (v1 op v2) { \
          ~~ ^  ~~
../../client/simulate_crash_mac.cc:185:3: note: in instantiation of function template specialization 'logging::CheckEQImpl<unsigned int, int>' requested here
  DCHECK_EQ(cpu_context.tsh.flavor,
  ^
../../third_party/mini_chromium/mini_chromium/base/logging.h:341:31: note: expanded from macro 'DCHECK_EQ'
#define DCHECK_EQ(val1, val2) DCHECK_OP(EQ, ==, val1, val2)
                              ^
../../third_party/mini_chromium/mini_chromium/base/logging.h:336:20: note: expanded from macro 'DCHECK_OP'
          logging::Check ## name ## Impl((val1), (val2), \
                   ^
<scratch space>:115:1: note: expanded from here
CheckEQImpl
^
1 error generated.
[158/339] OBJCXX obj/util/mac/crashpad_util_test.launchd_test.o
ninja: build stopped: subcommand failed.

<!-- You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs. -->
</details>

The same result for command `ninja -C out/Release`

**Comment by Beshelmek** [comment]
Same problem...

**Comment by rezam90** [comment]
I added the depot_tool to my PATH. but did not fix the problem.
I installed `ninja` with `brew`. but same error.

**Comment by arminkz** [comment]
same problem here ...

**Comment by john-preston** [comment]
Should be fine with new instructions.
