### ISSUE TITLE
Uninstalling Telegram Desktop

### ISSUE THREAD

**Issue by mhd4mr** [telegramdesktop/tdesktop#4355]
Hi
After uninstalling telegram desktop for windows, These keys (in registry) will not be deleted.
See Attached file and fix it.

[Fix.reg.txt](https://github.com/telegramdesktop/tdesktop/files/1670049/Fix.reg.txt)

**Comment by auchri** [comment]
Use the template.

**Comment by aarvindan** [comment]
I am unable to delete the installation.
The telegram.exe appears in the task manager and re-appears instantly even after killing the process
not sure on how to delete it. 
Windows 2012 server

**Comment by jainamshah512** [comment]
Same issue with me
