### ISSUE TITLE
Messages stop scrolling when a sticker is posted

### ISSUE THREAD

**Issue by foxmajik** [telegramdesktop/tdesktop#4356]
### Steps to reproduce
1.  Start a chat
2.  User sends a sticker
3.  Chat stops scrolling

### Expected behaviour
The chat should continue to scroll normally

### Actual behaviour
Chat stops scrolling.

Every time a new message comes in the message "New Unread Messages" is displayed in the chat even though I am sitting here looking at it.

To read new messages I have to switch to the Telegram window and either press Page Down or grab the scroll bar and drag it down.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
0.5.7.1

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@foxmajik If current window is not active the messages are not marked as read in the current chat. That doesn't depend on the type of messages received (stickers or not).

**Comment by auchri** [comment]
@foxmajik 0.5.7.1 is not a version of Telegram Desktop.
