### ISSUE TITLE
Choose file dialog opens in background

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#4359]
When wanting to upload a file, the choose file dialog opens in background instead of foreground. 

Tested with Telegram Desktop 1.2.6 Flatpak on Fedora 27. 

Anyone else with this?

Adding a screencast below:

https://youtu.be/YnKiOCRHkOU

**Comment by stek29** [comment]
What about official binary?

**Comment by orschiro** [comment]
The official binary is not affected. Only the Flatpak.

**Comment by d0tfile** [comment]
Just installed Flatpak and Telegram Desktop from flathub. I don't have any issue, only a lot of `dconf-WARNING`.

**Comment by auchri** [comment]
@orschiro Then you should contact the maintainer of the flatplack package.

**Comment by orschiro** [comment]
> @orschiro Then you should contact the maintainer of the flatplack package.

@auchri thanks! Just done so: https://github.com/flathub/org.telegram.desktop/issues/26
