### ISSUE TITLE
Telegram Desktop doesn't upgrade with ppa

### ISSUE THREAD

**Issue by nplezka** [telegramdesktop/tdesktop#436]
It upgraded to 0.7.7 but not 0.7.8. I had to download it from official site.

**Comment by auchri** [comment]
what's ppa?

**Comment by nevik** [comment]
@auchri a PPA is a *personal package archive*, that is, a .deb package repository for Ubuntu (and derivatives)

It allows installing software that is not in the default Ubuntu software repository (like Telegram) to be installed (and uninstalled!) as a package, with dependency management.

@nplezka is possibly talking about [the Telegram PPA](https://launchpad.net/~atareao/+archive/ubuntu/telegram) maintained by the [team of atareao.es](http://www.atareao.es/).

That said, I am observing the same behaviour -- the Telegram app won't update itself beyond 0.7.7.

I have not investigated into the reason (my guess is the lack of root access to replace the binaries). I'm currently hoping an updated package will soon be posted to the PPA.

**Comment by Norgerman** [comment]
it has its own updater you can find it in settings

**Comment by nevik** [comment]
Indeed it does, I know that and @nplezka  probably does as well.

The problem is not the absence of the self-updater, but the fact that it is not working.

Again, my guess is that, because TDesktop is usually running without root access, it cannot update its own binaries.

**Comment by Norgerman** [comment]
On opensuse, it sometimes works.....but sometimes not(0.7.6-0.7.8 maybe, I forgot it)

**Comment by telegramdesktop** [comment]
Well, autoupdate is only working when the child process (Updater binary) can rewrite Telegram binary. So Telegram process should have write access to the folder where it lies (to place new Updater binary there, then launch it and quit, Updater binary rewrite Telegram with a new version, launches it and quits).

I'm not sure about ppa, I've tested only with the binary in some home folder.

**Comment by nevik** [comment]
@telegramdesktop okay, I've manually changed the permissions on those files. I'll see if the next update works with the builtin updater and report back here :)
