### ISSUE TITLE
QR Code login [feature request]

### ISSUE THREAD

**Issue by stivens13** [telegramdesktop/tdesktop#4361]
Code this feature be implemented? Comparing to WhatsApp, this way is faster and more convenient. In addition, no extra cost for SMS delivery.

**Comment by d0tfile** [comment]
I think it can't be implemented in Telegram Desktop without API changes, so the only way is contact Telegram support via [Twitter](https://twitter.com/telegram) or Telegram (Settings > Ask a Question).

**Comment by stek29** [comment]
How do you even imagine this?

**Comment by auchri** [comment]
@stivens13 And use the template.
