### ISSUE TITLE
Messages get cut/deleted with synchronization

### ISSUE THREAD

**Issue by galloperx** [telegramdesktop/tdesktop#4364]
### Steps to reproduce
1.  Open Telegram on your phone, say you read some messages there, without typing anything. Then after say 5 minutes switch to PC and start typing a really long message to one of your contacts in the desktop app.
2.  Wait for it
3.  ???
4. It deletes all or sometimes half of your message.
It doesn't always happen, but this is a real problem, other Telegram users that I talked to also confirm its existence.

### Expected behaviour
Ability to type messages in any time intervals and of any length

### Actual behaviour
I think Telegram tries to sync itself with mobile app for whatever reason (because it's still "open" I guess) and the way it works is flawed - correct me if I'm wrong, but without even looking at the code I guess it does so in intervals, so it sends part of that long message to mobile - I mean the full message, but it's already grown longer by the time it arrives on mobile with this "sync" feature, then after some time even though you're still actively typing on the desktop app, it somehow decides that it's a good idea to sync what you had on mobile (whatever it just sent there) with your desktop app (and you didn't touch it with your hands, while still typing a long msg on desktop).

I'd suggest implementing a delay and a check to at least see if one of the open app instances in given account is actively generating content, before enforcing this useless backwards sync. Maybe it happens due to different internet latency, whatever the reason, the problem is still there.

### Configuration
**Operating system:**
Any Windows

**Version of Telegram Desktop:**
1.2.6

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
It's mostly caused by internet instability. Sorry for inconvenience. You can use "undo" for now.

**Comment by auchri** [comment]
Also duplicate.
