### ISSUE TITLE
Always on top when starting with system

### ISSUE THREAD

**Issue by stranc** [telegramdesktop/tdesktop#4365]
### Steps to reproduce
1. Activate checkbox Launch Telegram when system starts.
2. Reboot system.
3. Profit.

### Expected behaviour
Telegram mustn't be always on top of all windows.

### Actual behaviour
Telegram overlaps all windows

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.2.6
**Used theme**:
Night mode

**Comment by auchri** [comment]
Duplicate
