### ISSUE TITLE
[Feature Request] Sending drawings and diagrams

### ISSUE THREAD

**Issue by ksami** [telegramdesktop/tdesktop#437]
How about sending drawings to other users especially when discussing project ideas or for maths equations? I use Telegram to discuss projects but for trying to quickly explain something more suitable for diagrams, I have to open another app, screenshot, save as a picture then send it. It would be much faster and easier to directly send a drawing in Telegram, quality not being the issue here.

**Comment by Aokromes** [comment]
I wonder if something like LaTeX can do the job for math equations.

**Comment by ksami** [comment]
I was thinking of something more general. Maths equations alone might be too specific to justify a case for a new feature. Though LaTeX would be a good idea if they do decide to target such a use case.

**Comment by timkrins** [comment]
Seconded. Although I just figured out that I can paste an image from clipboard, which just means I can Alt+PrtScn and paste to get a shot of the my application window (if this helps anyone)

**Comment by ksami** [comment]
Wow that is useful, thanks for that!
