### ISSUE TITLE
How to organize source code?

### ISSUE THREAD

**Issue by jalalimehdi** [telegramdesktop/tdesktop#4371]
I spend more time reading your source code.
Could not understand source code.
Is There A Framework For That?
How to improve my reading and understanding of your code?
How to learn to structure your code properly ?
How to organize source code? 
I would want to ask:
    Are there any principles/logic/best-practices that can help me better at structuring your source tree?
    Are there any graphical/diagrammatic techniques (for eg.: DFD in case of dataflow) that can help me visualize your source tree beforehand based on the analysis of the project?
    What strategy to adopt to structure multi-media files-tree associated with the project?

please guide me 
Thanks

**Comment by stek29** [comment]
Didn't understand much 🤔

**Comment by jalalimehdi** [comment]
How do you organize the class source code of your telegram desktop project?
i am trying to understand your source code but i can not!!
Where can I find the docs for telegram desktop?
do you offer me for read ?
is there a framework for source code?

**Comment by stek29** [comment]
nope, there aren't any docs for source except source itself.
