### ISSUE TITLE
Adding a User into a Group and Removing it then leads to a Report even when the invited User didnt did that.

### ISSUE THREAD

**Issue by AncalagonTheBlack** [telegramdesktop/tdesktop#4372]
### Steps to reproduce
1. Create a New Group and invite someone with a number in your contacts
2. Remove the said contact
3. Ask Spambot for your Status

### Expected behaviour
The account should be useable as before

### Actual behaviour
The Account gets Limited

### Configuration
**Operating system:**

Android 6.01
**Version of Telegram Desktop:**
4.71
**Used theme**:
Standard White

**Comment by RememberTheAir** [comment]
There are two problems with this issue:

1. you got this from the Android client
2. clients are not responsible of spam reports problems, you should contact the in-app support (_settings -> ask a question_)
