### ISSUE TITLE
could you mind add chinese search function ?

### ISSUE THREAD

**Issue by b545798400** [telegramdesktop/tdesktop#4373]
Hi! Telegram   currently  doesn't support  search by chinese.could you mind add this function ?

I know it only support full word search.it's why chinese cann't work.And if we support characters search, maybe will increase more pressure on the server.

I can understand this is difficult.But i very wish telegram could support this at future.It's very kind for chinese user.

Thanks very much!

**Comment by stek29** [comment]
[duplicate](https://github.com/telegramdesktop/tdesktop/issues?utf8=✓&q=is%3Aissue+Chinese+label%3A%22api+issue%22)
