### ISSUE TITLE
Edit unread message

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#4374]
### Steps to reproduce
1. Send message in dialog or chat
2. Let someone read it
3. Send another message
4. While last message isn't read, press up arrow key

### Expected behaviour
Last message appears in textbox and you can edit it

### Actual behaviour
First message appears in textbox

### Configuration
**Operating system:** Windows 7, Linux Mint 18.3

**Version of Telegram Desktop:** 1.2.8 alpha

**Used theme**: Any

**Comment by stek29** [comment]
Isn't read or isn't sent?

**Comment by aNNiMON** [comment]
@stek29 isn't read.

Now I'm faced with another problem. I open dialog and press up arrow key, but now in textbox appears old message, although the last one was read.

![2018-02-01-21-47-07](https://user-images.githubusercontent.com/1321838/35701823-db3f0374-079f-11e8-838b-575dc6c9d032.gif)

**Comment by stek29** [comment]
@aNNiMON and the last one was sent from the same instance of TDesktop, and not from mobile for example?

**Comment by aNNiMON** [comment]
@stek29 it seems it really was sent from mobile client. Anyway, the current behavior is unclear. It would be better to edit any last message, regardless of which client it was sent from and whether it was read or not.

**Comment by stek29** [comment]
#2454
