### ISSUE TITLE
[Feature Request] Hide all muted chats (except pinned)

### ISSUE THREAD

**Issue by webworker01** [telegramdesktop/tdesktop#4376]
Currently if you are a member of many groups it sometimes becomes hard to focus on the chats that you need to at the time. 

My proposal is to simply add a button to the interface that would allow you to hide all muted chats while excluding your 5 pinned chats. 

This would not require any updates to/from the server and simply would be a local setting.

I have already implemented a prototype as a [recipe in Franz](https://github.com/webworker01/recipe-telegram) and the concept works out quite well!  Would love to see something like this in the desktop version, as it's much more responsive and feature complete than the web version.

**Comment by RememberTheAir** [comment]
If you type "_workmode_" in the settings screen, a button on top of your chats list to hide all muted chats will appear

**Comment by webworker01** [comment]
Amazing, this is what I was looking for forever, thank you @RememberTheAir
