### ISSUE TITLE
Turn off all text formatting

### ISSUE THREAD

**Issue by DevelAx** [telegramdesktop/tdesktop#4378]
Is there a way to turn off formatting text at all? 
I use telegram at work and it often spoils some specific texts like programming code which I'd like to send "as it is".

**Comment by auchri** [comment]
Use `` `foo bar` `` or ```` ```foo bar``` ```` for multiline to prevent text formatting.

**Comment by DevelAx** [comment]
Thanks! It works. Although it seems to me (not only to me) it would be great to be able to turn it off permanently for some conversations (users). There a lot of users who don't need these cute emoticons and similar stuff really. And it's not reliable to constantly remember that some specific texts should be marked with ``. Maybe you can consider this option in the next releases.  It wouldn't make any harm to other users.
