### ISSUE TITLE
Searching for Chats doesnt Work on the Desktop App

### ISSUE THREAD

**Issue by AncalagonTheBlack** [telegramdesktop/tdesktop#4379]
If you search for an channel or an user over the integrated telegram search it wont show up anything. 
### Steps to reproduce
1. Search Via @username for an channel or chat.

### Expected behaviour
It should list up all chats with the searched name

### Actual behaviour
it wont show up any channels or chats or usernames
https://imgur.com/a/jsPvU

### Configuration
**Operating system:**
Linux x64
**Version of Telegram Desktop:**
1.2.6
**Used theme**:
https://t.me/TelegramThemes/151572

<details><summary><b>Logs</b>:</summary>

</details>

**Comment by Aokromes** [comment]
works for me on windows 10 + 1.2.8 alpha
https://i.imgur.com/WZmngOw.png

**Comment by AncalagonTheBlack** [comment]
https://imgur.com/a/jsPvU still doesnt work for me :/

**Comment by stek29** [comment]
@AncalagonTheBlack Results are provided by server side. Maybe map logs can shed a light on this.

**Comment by AncalagonTheBlack** [comment]
Where can i get the MAP Logs ? The Problem still occurs and its annoying since i know others have the problem too

**Comment by stek29** [comment]
@AncalagonTheBlack That was auto-fix by keyboard. I've meant mtp logs.

Install alpha version, and/or go to settings and type "debugmode". Make sure debug logs are enabled.
Then go to directory where app stores it's data, and open DebugLogs folder. Each 15 minutes 3 files are created, you'll need the mtp_HH_MM.txt one.

However, it contains sensitive information (basically, everything transmitted from and to server in non-encrypted in any way plaintext form). So, you should probably send it directly to developer, or wipe sensitive info and upload it here.

cc @john-preston

**Comment by Aokromes** [comment]
You don't said what linux are you using, but if stek29 say it's server side, maybe the issue is outside of telegram desktop.
Tested on debian 9:
https://i.imgur.com/8083XwP.png

**Comment by AncalagonTheBlack** [comment]
Well I have an update. It works with the alpha version of telegram but not with the normal one. I stay now a while at the alpha version and will change back to stable as soon as the version should be.

**Comment by stek29** [comment]
Wait for the next update of stable and see if it fixes it.
If it would be still broken, leave a comment.
