### ISSUE TITLE
Support for default file browser on Linux

### ISSUE THREAD

**Issue by rumatoest** [telegramdesktop/tdesktop#438]
Telegram should launch default file manager when to show downloaded files in folder.
I have Kubuntu 14.10 
My default file manager is Dolphin, but I also have nautilus installed.
Telegram opening downloads in folder via Nautilus - this is not correct

**Comment by bil-elmoussaoui** [comment]
You should use `xdg-open` instead of `nautilus`, hope this can be fixed in the next version!

**Comment by stek29** [comment]
Isn't this fixed?
