### ISSUE TITLE
File download could not be started

### ISSUE THREAD

**Issue by halaei** [telegramdesktop/tdesktop#4380]
### Steps to reproduce
1. Try download https://t.me/toomanyrequests/8 in telegram desktop on windows

### Expected behaviour
It should be downloaded.

### Actual behaviour
A dialog box opens with this message:

> File download coud not be started.  This might be the download location you selected is invalid. Try changing the download path in settings.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** latest

**Used theme**: any

I guess the file name contains character invalid for windows file systems but valid for other configurations.

**Comment by aNNiMON** [comment]
I've faced the same issue but with sticker. I created test channel https://t.me/issue4380, once you open it, a dialog will appear:
![image](https://user-images.githubusercontent.com/1321838/42125041-9ab171aa-7c77-11e8-9556-363e98ceec2c.png)
You can relaunch telegram desktop and open channel to see this dialog again.

Operating system: Windows 7, Arch Linux, Linux Mint, Windows 10
Version of Telegram Desktop: 1.3.9

**Comment by aNNiMON** [comment]
Seems like https://github.com/telegramdesktop/tdesktop/commit/b44cf4a094f172fd63432d23e69775974275da11 fixes this.
