### ISSUE TITLE
[feature request] colours of smiley-hands

### ISSUE THREAD

**Issue by knezi** [telegramdesktop/tdesktop#4381]
It is really annoying every time I want to post smileys like thumbs up, that I have to double click - first to choose the emoji and then the skincolour. Can you consider making this possible to set in the settings or simply ask once and then remember the choice?

**Comment by john-preston** [comment]
@knezi It is asked once, after that you need to long press it to change the color.

**Comment by knezi** [comment]
No, it is not. When I restart Telegram, the settings is forgotten.
