### ISSUE TITLE
Add option to disable read receipt

### ISSUE THREAD

**Issue by T0nio** [telegramdesktop/tdesktop#4383]
Hello,

I think it could be a great idea that if it would be possible to disable the read receipt. (this double ticks)
I didn't find this option, and just find it in some unofficial apps. 
I feel that it's a good option for many use-cases (like just social chatting, without wanting to be able to spy your friends activity).

I wondered if there was a reason for that, or if it could be a feature that we could see in a future version.

Thanks !

**Comment by stek29** [comment]
it violates Telegram ToS.
