### ISSUE TITLE
Sometimes connection refused

### ISSUE THREAD

**Issue by c311at** [telegramdesktop/tdesktop#4384]
[log.txt](https://github.com/telegramdesktop/tdesktop/files/1694961/log.txt)
![1](https://user-images.githubusercontent.com/9547040/35803391-ba85e728-0a84-11e8-93ee-766db7aeb1c2.jpg)
 
### Steps to reproduce
1. sometimes the connection is broken
2. messages are not being delivered
3. connection problem occurs

### Expected behaviour
_Tell us what should happen:_ I do not know what you will do, but I have to solve this problem as soon as possible.

I share the visual about the problem.

### Actual behaviour
I do not know what you will do, but I have to solve this problem as soon as possible.
I share the visual about the problem.
![photo_2018-02-05_14-55-33](https://user-images.githubusercontent.com/9547040/35803363-a2c92c9e-0a84-11e8-8513-18c3f0805534.jpg)

### Configuration
**Operating system: Windows 10 x64**

**Version of Telegram Desktop:** 1.2.6 

**Used theme**: Official Night Theme

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)
![image](https://user-images.githubusercontent.com/9547040/35803333-7fabad36-0a84-11e8-95cd-4986b39e0b37.png)

[log.txt](https://github.com/telegramdesktop/tdesktop/files/1694962/log.txt)

</details>

**Comment by stek29** [comment]
That log doesn't help much.
Also, on your screenshots everything looks perfectly fine.

**Comment by c311at** [comment]
[log_start1.txt](https://github.com/telegramdesktop/tdesktop/files/1702352/log_start1.txt)
[log.txt](https://github.com/telegramdesktop/tdesktop/files/1702353/log.txt)
[log_start0.txt](https://github.com/telegramdesktop/tdesktop/files/1702354/log_start0.txt)
