### ISSUE TITLE
Pressing the "back button" on the mouse on the chatlist causes some problems

### ISSUE THREAD

**Issue by Aiku1** [telegramdesktop/tdesktop#4385]
### Steps to reproduce
1. Press the "back button" on the mouse a few times

### Expected behaviour
Well, nothing.

### Actual behaviour
The whole chat list does an animation but stays the same.
If you press it fast enough it will show a black glitched window.

### Configuration
**Operating system:**
Windows 10 x64

**Version of Telegram Desktop:**
1.2.6
**Used theme**:
Default, night mode on

![Example](https://user-images.githubusercontent.com/18646272/35816032-28b33e16-0a9a-11e8-8185-c8b4d8055259.gif) (sorry about that bad-made censor)

**Comment by john-preston** [comment]
@Aiku1 Thanks for your report. I hope it'll be fixed in the next version.

**Comment by Aiku1** [comment]
No problem!
