### ISSUE TITLE
How to make QT Ui changes

### ISSUE THREAD

**Issue by nOmi7** [telegramdesktop/tdesktop#4387]
### Steps to reproduce
1. Build Tdesktop from source using Cmake.

### Expected behaviour
Should create pro files and .ui forms file for QT

### Actual behaviour
No pro or .ui forms for tdesktop on Ubuntu

### Configuration
**Operating system:**
Ubuntu 14.04
**Version of Telegram Desktop:**
1.2.8
**Used theme**:
No

Once project is imported in Clion or in Ubuntu how to edit UI for telegram or make changes to it  There are no QT creator importable files.

**Comment by stek29** [comment]
Because it doesn't use .ui files and Qt's automatic interface stuff.

**Comment by nOmi7** [comment]
@stek29 so how to proceed with QT ?? how should i make the UI changes ? Any pointers to this will be really helpful

**Comment by nOmi7** [comment]
@stek29 can you please help us here 
 how to proceed with UI edits ?? how should i make the UI changes ? Any pointers to this will be really helpful

**Comment by stek29** [comment]
`uichanges* help = nomi.read(sources)`

UI is rendered using custom system of widgets, which are pretty easy to find even with "find file". Everything is rendered in code, "by hands".
