### ISSUE TITLE
Please, change default usage for microphone button.

### ISSUE THREAD

**Issue by Lourens-Rich** [telegramdesktop/tdesktop#4388]
### Configuration
**Operating system:** Linux
**Version of Telegram Desktop:** 1.2.8 alpha
**Used theme**: Default

I think it's not good for classic PC control when you must hold left mouse button for recording audio message.

![_2018-02-06_20-25-47](https://user-images.githubusercontent.com/22860367/35873758-bde5a0dc-0b7b-11e8-831d-1c91c0562640.png)

**Comment by stek29** [comment]
#1688 #2458 #2735 #3208

**Comment by stek29** [comment]
```
[auchri]
Also, use the template next time
```

:D
