### ISSUE TITLE
Delete entries in non private chats for all parties.

### ISSUE THREAD

**Issue by Gruenbaer** [telegramdesktop/tdesktop#439]
I have the possibility to delete entries in my non-private chat log, but it turns out, it is only deleted on my side!

Please change this behaviour so that a deleted chat enty is deleted everywhere, and not only on my device.
That doesn't make much sense.

Best regards,

Emil

**Comment by auchri** [comment]
No,

use the secret chat if you want to delete messages everywhere

**Comment by Gruenbaer** [comment]
OK, then I would suggest to remove the delete functionality in non-secret chats as it suggests that you are able to delete messages - which you clearly are not.

**Comment by auchri** [comment]
No, because if someone send me stupid messages which I don't want to keep in my chat history, I can simply delete it.

yes, not yet.

**Comment by Gruenbaer** [comment]
Right.
So you basically have two different (I guess undocumented) behaviours depending in which type of chat you are.
In a secret chat the deleted essage is _really_ deleted everywhere, and in normal chat it is just removed from my own chat history. 
As stated above, this doesn't make sense and is bad usability.

**Comment by auchri** [comment]
It's documented: https://telegram.org/faq#q-how-are-secret-chats-different

**Comment by Gruenbaer** [comment]
Alright. Well done. Thanks for your time. 
I am sure that all users will immeadetly understand that deleting a message will only delete it in some cases.
Please close this issue, it is obviously resolved.

**Comment by kapcom01** [comment]
I didn't know that **Delete** doesnt actually deletes the messages from the receipent.. I thought it was the same as in secret chats.. Iwould  suggest to differentiate somehow the two *Delete* options.
