### ISSUE TITLE
Add "Quit" to .desktop file?

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#4391]
Hey guys, 

I noticed that Telegram Desktop doesn't have a "Quit" entry which makes it hard to properly close it (at least on GNOME because it doesn't show tray icons by default) without having it continue run in the background. I noticed that other apps like Skype do have a quit entry. 

Now, who is responsible for providing this .desktop file? This repo or do I need to address it to the packager (in my case RPMfusion Fedora)?

Thanks guys!

![screenshot from 2018-02-06 15-04-17](https://user-images.githubusercontent.com/170947/35912243-49de07b6-0bfc-11e8-8f77-89c66958b316.png)

![screenshot from 2018-02-06 15-04-15](https://user-images.githubusercontent.com/170947/35912248-4f42595a-0bfc-11e8-8119-184ad276478f.png)

**Comment by xvitaly** [comment]
@orschiro Just press Ctrl+Q to immediately close Telegram Desktop.

**Comment by orschiro** [comment]
>  Just press Ctrl+Q to immediately close Telegram Desktop.

Nice, works well! Still what do you think of adding Quit to the menu icon?

**Comment by stek29** [comment]
How is that quit exactly supposed to work? What exactly do you mean by "adding Quit to .desktop file"? Could you please provide an example?

**Comment by orschiro** [comment]
> How is that quit exactly supposed to work? 

Do exactly the same as `Ctrl + Q`.

> What exactly do you mean by "adding Quit to .desktop file"? Could you please provide an example?

See the below entry for Skype as an example:

![screenshot from 2018-02-06 15-04-15](https://user-images.githubusercontent.com/170947/35933742-c915c2e6-0c3b-11e8-9307-ffbf2d11a1bd.png)

**Comment by 3v1n0** [comment]
It's a Desktop QuickAction. They can be defined in desktop files.

Then the telegram binary would need a command to perform this when invoked.

**Comment by RussianNeuroMancer** [comment]
@xvitaly 

> Just press Ctrl+Q to immediately close Telegram Desktop.

How to do this from touchscreen?

**Comment by damnfella** [comment]
> 
> 
> @xvitaly
> 
> > Just press Ctrl+Q to immediately close Telegram Desktop.
> 
> How to do this from touchscreen?

Can you bring up a virtual keyboard at any time? If you can, then you should be able to do it.

**Comment by RussianNeuroMancer** [comment]
> Can you bring up a virtual keyboard at any time? If you can, then you should be able to do it.

Gnome Shell on-screen keyboard doesn't have Ctrl button.

**Comment by damnfella** [comment]
> 
> 
> > Can you bring up a virtual keyboard at any time? If you can, then you should be able to do it.
> 
> Gnome Shell on-screen keyboard doesn't have Ctrl button.

I understand. For now, you could try searching for an alternative on-screen keyboard.
Maybe open an issue in the Gnome repo for the keyboard to add those keys and improve the overall functionality of Gnome with touch? 

I don't know if there would be any progress made here unless someone does a pull request for this issue.

**Comment by RussianNeuroMancer** [comment]
> Maybe open an issue in the Gnome repo for the keyboard

[Such bugreport exist](https://gitlab.gnome.org/GNOME/gnome-shell/issues/181), but for now [developer against this idea](https://gitlab.gnome.org/GNOME/gnome-shell/issues/181#note_354947) ("If that is a problem, that is IMO a usability issue with those applications, and I encourage you to file bugs to them.").

> I understand. For now, you could try searching for an alternative on-screen keyboard.

[Alternative keyboard do exist](https://extensions.gnome.org/extension/1631/improve-onscreen-keyboard/), but it's unusable in portrait orientation. Other on-screen keyboards, such as Onboard, is not available in Wayland session (Onboard stop working around Gnome Shell 3.30+ anyway, even in Xorg session). And let's not seriously discuss switching back to Xorg and installing some other keyboard just to have ability to press Ctrl+Q because there is no "Quit" in Telegram's desktop-file, because at this point this will be borderline crazy.

**Comment by ilya-fedin** [comment]
Is this still actual after tray detection was fixed (1.9.13)?

**Comment by RussianNeuroMancer** [comment]
> Is this still actual after tray detection was fixed (1.9.13)?

Is tray expected to work in Gnome Shell?

**Comment by ilya-fedin** [comment]
> Is tray expected to work in Gnome Shell?

What do you mean?

I'm saying that tray detection has been fixed and code that disables running in background works again.

**Comment by xvitaly** [comment]
> Is tray expected to work in Gnome Shell?

Yes, just install [AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) extension.
