### ISSUE TITLE
[Proposal] Add button "mark as read" on message popup

### ISSUE THREAD

**Issue by mubat** [telegramdesktop/tdesktop#4393]
Sometimes messages at popups don't need of reply. And will be comfortable to mark them as read.
I propose add check at popup to mark message as read and not open app.

**Comment by john-preston** [comment]
@mubat You can "send" an empty reply (or a single space as a reply) and it will just mark the conversation as read.

**Comment by mubat** [comment]
@john-preston, it's some QUIRK.
I as window-like user will not know this and **I want button** that do action.
Also button is more friendly functional.

PS 
* click "Mark as read" - 1 action; 
* click "Reply", press space, click "Send" - 3 actions;

**Comment by john-preston** [comment]
@mubat I tried to make such button inside a notification first, but the notification started to look very heavy and the attention was completely switched from the notification content. Didn't come up with really good notification design yet with both reply and mark as read functions.

**Comment by mubat** [comment]
How I see it (Paint-master):

![asdfsadfasd](https://user-images.githubusercontent.com/3623986/35965968-280118f8-0cc5-11e8-9e70-138a7fb953c5.png)

**Comment by omkarnathsingh** [comment]
Looks nice.

**Comment by stek29** [comment]
related: #1625

**Comment by mubat** [comment]
No, I don't lost interest. Just dev team not respond
