### ISSUE TITLE
[Feature Request] Paste bots commands without sending.

### ISSUE THREAD

**Issue by Vilmodao** [telegramdesktop/tdesktop#4394]
![screenshot_2018_02_08](https://user-images.githubusercontent.com/11928504/35974365-de265c96-0ce9-11e8-89f2-c80a2ddef6c7.png)
_ios vs desktop_

Looks like you forgot something on the desktop app.
Sometimes you need add some parameters to a command before send it.

**Comment by MasterGroosha** [comment]
Hover over command (or choose it with arrows on keyboard) and press <kbd>Tab</kbd>

**Comment by Vilmodao** [comment]
Why this ticket was closed?
There is no the way to use this feature with mouse and touchscreen. Keyboard sucks.
![screenshot_2018_02_09](https://user-images.githubusercontent.com/11928504/36029868-09b8086a-0db6-11e8-8cfe-2eb597bc30dd.png)
But why you added this control?! For use keyboard on the next step? Ok.

**Comment by stek29** [comment]
@Vilmodao Then please create a new issue with appropriate title (eg "Paste bot command without sending with touchscreen"), and most importantly, use the template.
