### ISSUE TITLE
http://provider1surv/ not highlighted as URL and not clickable

### ISSUE THREAD

**Issue by neopaf** [telegramdesktop/tdesktop#4400]
this is highlighted as URL and is clickable:
http://provider1surv.msk.provider.ru 

please make
http://provider1surv/ 
highlighted and clickable too.

We use that for internal network resources and it's extremely inconvenient.
3.7.5 AppStore version.

**Comment by neopaf** [comment]
@lelvisl

**Comment by stek29** [comment]
1) 3.7.5 isn't TDesktop.
2) Highlighing is done on server side.

**Comment by neopaf** [comment]
guys, please suggest how to submit our woes to that team?

**Comment by stek29** [comment]
Use "Ask a Question" button in settings, or Twitter

**Comment by neopaf** [comment]
thanks. (did that in the past and NEVER got any reply)

**Comment by neopaf** [comment]
but did it anyway

**Comment by stek29** [comment]
@neopaf well we can't help this :(
