### ISSUE TITLE
Character Accent Menu does not work in MacOS

### ISSUE THREAD

**Issue by vgarvardt** [telegramdesktop/tdesktop#4403]
Active keyboard layout is "ABC - Extended"

### Steps to reproduce
1. Open any chat
2. Focus input field
3. Long press "a", "u" or some other keys

### Expected behaviour
Character Accent Menu appears, so it is possible to type letters like ä, ü, ž, etc (works great in the browser and most of the apps) - looks like an image on the top in this article http://osxdaily.com/2011/08/04/enable-key-repeat-mac-os-x-lion/

### Actual behaviour
Pressed button acts as if the "Key Repeat" behaviour enabled, so I get "aaaaaaa", or "uuuuuu", etc.

### Configuration
**Operating system:** MacOS 10.13.3

**Version of Telegram Desktop:** 1.2.6

**Comment by stek29** [comment]
#2830
