### ISSUE TITLE
Telegram icon in the KDE 5 "Icons-only task manager" panel doesn't show unread messages indicator

### ISSUE THREAD

**Issue by strangeattr** [telegramdesktop/tdesktop#4404]
On Ubuntu with Unity, on Windows 10 and on macOS you can see an overlay indicator showing the number of unread messages on the main icon (not just a tray icon) representing Telegram in the system taskbar/launcher/dock. Unfortunately this doesn't work this way in KDE although it supports this kind of functionality.

From the bare pragmatic point of view this is not a serious problem as the tray icon does the job. From the aesthetic (and display area saving) point of view, however, it seems ugly to have 2 identical icons, one without the unread messages indicator and one with (you can disable the tray icon but not the main icon so you can choose to have both or just the one without the indicator).

Together with Krusader I've used as an example of an app supporting the desired behaviour in KDE, Google Chrome can be considered another example. It (Google Chrome) is said to need libunity for this and I've installed it (before installing Chrome so I hadn't had a chance to check if it might work the desired way without it too) yet Telegram still doesn't seem utilizing it.

![tg1](https://user-images.githubusercontent.com/3106934/36066436-e2352ba2-0ea9-11e8-905c-1a298c3e5d97.png)

### Steps to reproduce
1. Run the Telegram Desktop messenger in the KDE 5 Plasma desktop environment on Linux
2. Make sure the "Icons-only task manager" widget is used for the task bar
3. Wait for new messages to arrive
5. Notice the main icon (not the tray icon, the tray icon works fine) has not changed and doesn't indicate unread messages presence

### Expected behaviour
The main icon (not just the tray icon) representing Telegram on the KDE 5 "Icons-only task manager" panel should display an overlay with the number of unread messages the way it does in Ubuntu with Unity, macOS and Windows 10.

### Actual behaviour
The main icon is static (just the logo) and doesn't change as new messages arrive (although the tray icon shows the unread messages count).

### Configuration
**Operating system:**
Manjaro KDE 17.1.2 stable x86_64, KDE Plasma 5.11.5, KDE Frameworks 5.42.0, Qt 5.10.0, Linux kernel 4.14.16

**Version of Telegram Desktop:**
1.2.8 alpha

**Used theme**:
default

**Comment by stek29** [comment]
4554 is more active tho
