### ISSUE TITLE
High CPU Usage when status of one of the chats in chats list is "...typing"

### ISSUE THREAD

**Issue by behrang** [telegramdesktop/tdesktop#4406]
On macOS:
1. Open Activity Monitor app and go to CPU tab and order by "% CPU" descending.
2. Look at the chat list and wait for one of the chats to become "... typing"
3. Then CPU usage of Telegram Desktop goes to a high value, while "... typing" is visible. When it is removed, either by getting a new message, or the sender stops typing, CPU usage will become low again.

This happens on Telegram Desktop version 1.2.6.

**Comment by behrang** [comment]
I also found out that while playing music, this happens too. But when I minimize the window, CPU usage goes down again.

**Comment by imakecodes** [comment]
Here I have the same issue

**Comment by rshmelev** [comment]
I also get this issue and it's totally disaster. CPU is almost 100%, fan is spinning like crazy, other apps start lagging ( i wish there was a flag to somehow disable this typing animation

**Comment by ru-web-designer** [comment]
![image](https://user-images.githubusercontent.com/3310192/51621697-20349700-1f46-11e9-965b-999aad3bf68c.png)

When someone's typing
![image](https://user-images.githubusercontent.com/3310192/51621753-3b070b80-1f46-11e9-954a-f20037bbe040.png)

When nobody does
![image](https://user-images.githubusercontent.com/3310192/51621767-44907380-1f46-11e9-8cb8-162d85c36923.png)

**Comment by stek29** [comment]
@rshmelev btw, there's an option to disable notifications now.

**Comment by duynguyenhoang** [comment]
MacOs Telegram Desktop version 1.7.4 has the same issue with high CPU usage

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by imakecodes** [comment]
Not anymore for me @Aokromes
