### ISSUE TITLE
Do not replace default log.txt when starting Telegram or Updater

### ISSUE THREAD

**Issue by nevik** [telegramdesktop/tdesktop#441]
Currently, Telegram (and the Updater) clears the log file (`log.txt` in the data folder) every time it starts.

This is making it difficult to debug an issue with the Updater when having TDesktop installed via a PPA package on *buntu (see #436).

Suggestion: Open the default log file in "append" mode instead (this is how the debug log currently behaves, so it would be nice if the default log did the same).

**Comment by telegramdesktop** [comment]
There is a "-debug" param for that, all info from log.txt is duplicated to DebugLogs/log_... file. No need to make a huge log.txt
