### ISSUE TITLE
New Clear Telegram get "Spam block" when "Two-Step Verification" activated, no bot apilation

### ISSUE THREAD

**Issue by taharuw** [telegramdesktop/tdesktop#4411]
### Steps to reproduce
1. Register new clear telegram at 0.00 mobile+desctop
2. Activate "two-step Verification" at 0:09
3. First contact add me by phone at 0:20
4. After 12 hours trying add new contact (in desctop) by "name" - get "warning" from "spam block " tells that "user marked spam" and you will be unblocked at 0:09. It is time will 24 hours(day) as i recive Two-Step Verification in Telegram email on mail. 
There is no appeal in bot and prejudice that we will punish for a longer time!
Thank you telegram!

### Expected behaviour
No like that

### Actual behaviour
appeal
excuses
financial compensation

### Configuration
**Operating system:** android and windows

**Version of Telegram Desktop:** 1.2.6

**Used theme**: default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
Has absolutely nothing to do with TDesktop.
