### ISSUE TITLE
Selecting non-default chat background prevents Night Mode from changing chat background to black

### ISSUE THREAD

**Issue by zarbis** [telegramdesktop/tdesktop#4412]
### Steps to reproduce
1. Go to Settings, change chat background to some other from gallery
2. Toggle Night Mode

### Expected behaviour
Chat background should become black, consistent with dark theme.

### Actual behaviour
Chat background stays the same as selected above, burning user's eyes.

### Configuration
**Operating system:**
Ubuntu 17.04, also reproduces in Windows 10

**Version of Telegram Desktop:**
1.26

**Comment by stek29** [comment]
That's a feature. Also see #3835.
