### ISSUE TITLE
Смайлы по клику

### ISSUE THREAD

**Issue by maksuus** [telegramdesktop/tdesktop#4413]
Добрый день. Сделайте что бы смайлы открывались по нажатию а не по наведению.

**Comment by d0tfile** [comment]
@maksuus, please, fill original template, translate text to english (GitHub is international site, feel free to use [google](https://translate.google.com) or [yandex](https://translate.yandex.ru) to translate) and add to title [Enhancement].

Welcome to GitHub, by the way 👍
