### ISSUE TITLE
Smilies to click

### ISSUE THREAD

**Issue by maksuus** [telegramdesktop/tdesktop#4414]
<! -
Thank you for reporting the problems with Telegram Desktop!

To facilitate our assistance, please enter the details below.
->
### Playback Actions
1.
2.
3.

### Expected behavior
I want smiles to open by clicking on the icon!

### Actual behavior
Now smileys open when hovering that there is no easy way!

### Configuration
Windows 7

** Telegram Desktop Version: **
all

** Used theme **:

<Details> <summary> <b> Journals </ b>: </ summary>
Insert the logs here (if necessary)

<! - You can enter `debugmode` in the settings, and then browse the ~ / .TelegramDesktop / DebugLogs / log _... txt files for the log files.
Enter "debugmode" in the settings again to turn off the logs. ->
</ Details>

**Comment by auchri** [comment]
Duplicate
