### ISSUE TITLE
Building problem & code removal

### ISSUE THREAD

**Issue by digitalist** [telegramdesktop/tdesktop#4415]
### Steps to reproduce
1. Building telegram-desktop with LibreSSL

### Expected behaviour
Working executable

### Actual behaviour
build fails. 

It builds if FIPS_mode_set() call is removed. It seems that `FIPS_mode_set` can be removed, since it does nothing.
### Configuration
TrueOS-Desktop-201712150936/FreeBSD 12 CURRENT, clang7
**Version of Telegram Desktop:**
1.23
**Used theme**:

<details><summary><b>Logs</b>:</summary>
```
/wrkdirs/usr/ports/net-im/telegram-desktop/work/tdesktop-1.1.23/Telegram/SourceFiles/core/utils.cpp:311:3: error: use of undeclared identifier 'FIPS_mode_set'
                FIPS_mode_set(0);
```

It builds if FIPS_mode_set() call is removed. It seems that `FIPS_mode_set` can be removed, since it does nothing.

</details>

**Comment by Johnnynator** [comment]
You can try this patch https://github.com/Johnnynator/void-packages/blob/telegram/srcpkgs/telegram-desktop/patches/04-libressl.patch

**Comment by digitalist** [comment]
Thanks, I'll try it. Hope this fips thing really isn't needed and can rest in peace

**Comment by Johnnynator** [comment]
It isn,t it is disabled by default on musl and the FIPS_mode_set(0) AFAIK only disables it. It worked so far without problems for me.

**Comment by Johnnynator** [comment]
It isn,t it is disabled by default on musl and the FIPS_mode_set(0) AFAIK only disables it. It worked so far without problems for me.

**Comment by Johnnynator** [comment]
It isn,t it is disabled by default on musl and the FIPS_mode_set(0) AFAIK only disables it. It worked so far without problems for me.

**Comment by Johnnynator** [comment]
It isn,t it is disabled by default in libressl and the FIPS_mode_set(0) AFAIK only disables it. It worked so far without problems for me.
