### ISSUE TITLE
Build fails when linking CXX executable Telegram

### ISSUE THREAD

**Issue by R32fanboy** [telegramdesktop/tdesktop#4418]
Running on Ubuntu 16.04 LTS updated with the latest patches. 
Build was stored in the directory /home/user/Tbuild/ with the two branches being /tdesktop and /Libraries
### Steps to reproduce
1. Built dependencies with no Errors.
2. ran make on /Tbuild/tdesktop/out/release and /Tbuild/tdesktop/out/Debug and ended up with the same error.
![telefail2](https://user-images.githubusercontent.com/32889334/36346324-34a02b64-1402-11e8-87c4-833b92eebfa4.png)

/usr/local/tdesktop/Qt-5.6.2/lib/libQt5Network.a(qsslsocket_openssl_symbols.o): In function `q_EC_curve_nist2nid(char const*)':
/home/slighthoof/Tbuild/Libraries/qt5_6_2/qtbase/src/network/ssl/qsslsocket_openssl_symbols.cpp:426: undefined reference to `EC_curve_nist2nid'
collect2: error: ld returned 1 exit status
CMakeFiles/Telegram.dir/build.make:13117: recipe for target 'Telegram' failed
make[2]: *** [Telegram] Error 1
CMakeFiles/Makefile2:85: recipe for target 'CMakeFiles/Telegram.dir/all' failed
make[1]: *** [CMakeFiles/Telegram.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Looks like it's an error with the installer expecting an object from OpenSSL to be there and it is not, or it is not in the place it's looking for. OpenSSL was installed in correct order and is completely up to date in the repository.

**Comment by pentix** [comment]
Hi, I faced the same error just yesterday. I found this

https://github.com/telegramdesktop/tdesktop/issues/2519#issuecomment-253171003

Make sure to checkout `OpenSSL_1_0_2-stable` before compiling OpenSSL. The documentation is wrong there for anything later then Ubuntu 12.04 🙄

**Comment by R32fanboy** [comment]
That did the trick! We are up and running, thanks for the tip!

**Comment by pentix** [comment]
Hi @auchri 

Because in the referred thread, the same was declined by @john-preston:

@EhsaanF 
> Nice job, John. Please change the docs, too. :)

@john-preston 
> Well, the docs are for Ubuntu 12.04, it works there I suppose.

🤷‍♂️
