### ISSUE TITLE
Бесит, что фон с цветочками устанавливается после каждого выхода/входа из приложения

### ISSUE THREAD

**Issue by isopen** [telegramdesktop/tdesktop#4419]
### Steps to reproduce
1. войти в приложение
2. изменить фон
3. выйти из приложения

Необходимо сохранение установленного фона до выхода из телеграм

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.2.6

**Used theme**: Светлая

**Comment by auchri** [comment]
Write english please.

**Comment by stek29** [comment]
Theme and background are intentionally not saved in settings which aren't cleared on logout.

**Comment by isopen** [comment]
On android it works.
