### ISSUE TITLE
XIM not supported on Linux

### ISSUE THREAD

**Issue by shouya** [telegramdesktop/tdesktop#442]
tdesktop version: 0.7.16
platform: gentoo w/ i3wm
input method: hime, that implements XIM interface

```
$ env | grep IM
XIM_PROGRAM=hime
GTK_IM_MODULE_FILE=/usr/lib64/gtk-2.0/2.10.0/immodules.cache
XIM=hime
QT_IM_MODULE=hime
GTK_IM_MODULE=hime
```

Above is considered to be correct configuration because other GUI programs work with it. However, it's not able to switch on the input method in the input box of tdesktop client. ~~Not sure if this problem is related to #88. That bug is critical to CJK language users and hasn't been fix for so long.~~

UPDATE:

The problem with CJK character displaying reported in #88 has recently been fixed. But it seems to have nothing to do with this issue.

**Comment by giyyapan** [comment]
Same problem（unable to switch to input method in telegram） with Ubuntu14.04 and fcitx (Flexible Input Method Framework).

**Comment by giyyapan** [comment]
#375

**Comment by shouya** [comment]
related keyboard problems: #375 #482 #513

**Comment by 1kko** [comment]
I'm also facing same problem. 
tdesktop version: 0.7.17 (stable)
platform: Ubuntu 14.04
input method: fcitx 

```
$ env |grep IM
CLUTTER_IM_MODULE=xim
QT_IM_MODULE=fcitx
IM_CONFIG_PHASE=1
QT4_IM_MODULE=fcitx
XDG_RUNTIME_DIR=/run/user/1000
GTK_IM_MODULE=fcitx
LC_TIME=ko_KR.UTF-8
```

**Comment by shouya** [comment]
根據 hime 論壇的某個 issue，有可能是這些輸入法沒有能很好支援 Qt5 的原因。

https://github.com/hime-ime/hime/issues/509

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.
