### ISSUE TITLE
Bug too much CPU usage when downloading photos and more.

### ISSUE THREAD

**Issue by dfmAbbas** [telegramdesktop/tdesktop#4420]
Telegram version 1.2.6 has a very important bug.

On Mac OS 10.13.2, I encounter a problem with over-CPU usage.
That's when using more than 70% of cpu sources when downloading a few photos or videos.

I already reported this problem, but so far this problem has not been resolved.

Please fix this important bug as soon as possible. Thank .

**Comment by Aokromes** [comment]
#4306 there is no need to open 2 tickets because the previous is no fixed the fast you want.
