### ISSUE TITLE
Wildfowl. Floral background. Floral background.

### ISSUE THREAD

**Issue by isopen** [telegramdesktop/tdesktop#4421]
### Steps to reproduce
1. Sign in to the app
2. Сhange background
3. exit application
loop 1000000
go

It is necessary to save the set background before exiting telegram.

Configuration
Operating system: Windows 10

Version of Telegram Desktop: 1.2.6

Used theme: Light

**Comment by stek29** [comment]
Why do you even log out so often?

**Comment by isopen** [comment]
Because I use telegram not only on my devices.
The bug does not depend on the frequency of the outputs.
**Today checked. Not corrected.**

**Comment by stek29** [comment]
So is it being reset when you explicitly log out from app, or does it happen in other cases?

**Comment by isopen** [comment]
Yes
1. Sign in to the app
2. Сhange background(new background)
3. exit application
4. Sign in to the app(background with flowers)
etc.

**The bug is repeated on multiple devices.**

**Comment by isopen** [comment]
In all applications this background by default (it seems to me that this game).
I understand that this background is specially installed by default for people-trolling.
But what for? It immediately seems like a game and wildfowl.

> P.S.
> Probably someone from the team smoked chamomile before installing

**Comment by isopen** [comment]
Do not worry. People will find the functionality of changing the background as necessary.

**Comment by isopen** [comment]
In general, it's best to change the default background to another. For example, the second from the first line.

**Comment by stek29** [comment]
> Sign in to the app
> exit application
> Sign in to the app

App shouldn't have lost auth after exit on it's own.

---

Вы из приложения выходите и разлогиниваетесь, или просто закрываете его?

**Comment by isopen** [comment]
1. авторизуюсь в приложении
2. увидел фон с цветочками
3. изменил фон на другой
4. разлогинился (вышел из приложения, разорвал сессиию, разорвал сеанс)
5. авторизовался в приложении
6. увидел фон с цветочками
и т.д.

**Comment by isopen** [comment]
Уже примерно пол года переключаю фон с цветочками.
Надоело. Думаю поправите. Там не сложно.

**Comment by auchri** [comment]
Write english.

**Comment by isopen** [comment]
Okey

**Comment by stek29** [comment]
@isopen I don't see any issue in background image being reset on logout. 

First of all, you're not supposed to log out often. You might get rat limited by server if you do that. Use local password lock.

Secondly, imagine people using their personal stuff as background image. Which doesn't get reset on logout. Ouch.

**Comment by isopen** [comment]
Android works conservation. In the desktop does not work. Need a video?

**Comment by john-preston** [comment]
@isopen The background reset on logout is an intended behaviour, video is not needed.

**Comment by isopen** [comment]
The madhouse

**Comment by john-preston** [comment]
@isopen The app is designed to be used without frequent logouts. You can use local passcode if someone else has access to the same computer.

**Comment by isopen** [comment]
I'm so not comfortable. See how the android application works.

**Comment by john-preston** [comment]
@isopen Android app is a phone application which typically has one owner and it's ok to save more things.

On desktop if you logout it is probably because someone else will login next, not you. So saving your custom chat background would be strange.

**Comment by isopen** [comment]
Save for my session. Under android, too, anyone can go.

**Comment by isopen** [comment]
My girl arranged total control over my devices. Steals my token data sessions.
You are a professor on such matters. How can I protect your application?

**Comment by isopen** [comment]
🌼🌼🌼

**Comment by isopen** [comment]
Вы все-таки подумайте над цветочками. Проведите несколько ассоциаций.

**Comment by yashpalgoyal1304** [comment]
maybe try binding the bg to ur theme. that can help u @ isopen i think.
