### ISSUE TITLE
Streaming for video and audio

### ISSUE THREAD

**Issue by gleb-chipiga** [telegramdesktop/tdesktop#4422]
### Steps to reproduce
Ability to start watching videos right away – without having to fully download them first

### Expected behaviour
The behavior should [be the same](https://telegram.org/blog/android-streaming) as in Telegram for Android.

### Actual behaviour
Videos have to download completely before watching.

### Configuration
**Operating system:**
Any.

**Version of Telegram Desktop:**
Any.

**Used theme**:
Any.

**Comment by stivens13** [comment]
Big plus on that, for desktop, it a must-have feature

**Comment by Aokromes** [comment]
#4330
