### ISSUE TITLE
Audio player corrupts audio quality of any audio - not reproducible in mobile apps or Unigram

### ISSUE THREAD

**Issue by DJ-ZX** [telegramdesktop/tdesktop#4426]
There is no specific steps:
Just play any audio sent in app (mp3, aac - does not matter) - stereo is mixed and corrupted
1 - stereo picture when playing in TDesktop
![image](https://user-images.githubusercontent.com/13614247/36350777-7a735acc-14a6-11e8-9912-3934b5927054.png)
2 - stereo picture of same part when playing in XMPlay (or any other player - no enhancements)
![image](https://user-images.githubusercontent.com/13614247/36350790-ac0d1744-14a6-11e8-8690-61aad89a114a.png)

attaching audio records for both playbacks
[test.zip](https://github.com/telegramdesktop/tdesktop/files/1734588/test.zip)

**Comment by RevenantX** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2580
https://github.com/telegramdesktop/tdesktop/issues/3058
https://github.com/telegramdesktop/tdesktop/issues/4034
