### ISSUE TITLE
Secret chat

### ISSUE THREAD

**Issue by tural-esger** [telegramdesktop/tdesktop#4427]
I don't find telegramdesktop's response satisfactory. They say it will confuse users different secret chats will be in different devices. Anyway we can have different secret chats within a single device. They are separate from each other. So desktop secret chat can be separate, as well. Please implement these feature. We (most of the developers)  spend our all day in front of our laptops.

**Comment by auchri** [comment]
Duplicate

**Comment by tural-esger** [comment]
Not duplicate, maybe millionplicate .😜
