### ISSUE TITLE
Top Window Bar Cut Off when Fullscreening

### ISSUE THREAD

**Issue by danmi20** [telegramdesktop/tdesktop#4428]
### Steps to reproduce
1. Open Telegram.exe
2. Maximize the window.

### Actual behaviour
The top bar doesn't go all the way to the top and the X button is missing.
![image](https://user-images.githubusercontent.com/9846863/36352318-bbfd90c0-14bf-11e8-9c71-00027c94e395.png)

### Configuration
**Operating system:**
Windows 10 Home

**Version of Telegram Desktop:**
1.2.6

**Used theme**:
It is happening in every theme I have tried.

</details>

**Comment by skupake** [comment]
Latest porn
https://telegram.me/legalsex

**Comment by danmi20** [comment]
The problem has been fixed (probably because of a Windows update).

**Comment by danmi20** [comment]
The problem is back. I don't know what is causing it but it apparently doesn't happen every time.

**Comment by levrik** [comment]
@danmi20 I opened #4649 yesterday. I started with the latest Windows 10 update (version 1803).
Could it be possible that you had an insider build installed? I didn't have this issue before the update to 1803.

**Comment by danmi20** [comment]
Indeed, I have an insider build. I'm currently on version 1803 (build 17133.1) and the problem still exist.

**Comment by danmi20** [comment]
Indeed, I have an insider build. I'm currently on version 1803 (build 17133.1) and the problem still exists.

**Comment by levrik** [comment]
Can we merge this issue into mine? I've added a bit more information to the issue.

**Comment by danmi20** [comment]
Yes. Maybe just add that it doesn't happen every time. I'm currently using Telegram and it's fine but yesterday I had the same problem. I'm not sure yet what causes it to happen.

**Comment by levrik** [comment]
@danmi20 It's looks fine when Telegram starts up maximized (that's also mentioned in the ticket).
As soon as I unmaximize and maximize it again it looks broken every time until I restart.

**Comment by stek29** [comment]
See #4649
