### ISSUE TITLE
telegram won't open on my windows 10

### ISSUE THREAD

**Issue by acrobatman** [telegramdesktop/tdesktop#4440]
### Steps to reproduce
1. just click telegram.exe (portable version)
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead
After updating my windows to 16299, telegram won't open
I have run it before and it works fine.
But it shows exception 0xc000094 on 16299
Here is the dump

![5d561532-215f-11e7-9817-1bdd5bf040e4](https://user-images.githubusercontent.com/16357426/36434866-0401eb96-169b-11e8-97b8-857a4911c906.png)

[9a9d285f-b062-4e06-83b3-9ecb0a66e39f.zip](https://github.com/telegramdesktop/tdesktop/files/1740819/9a9d285f-b062-4e06-83b3-9ecb0a66e39f.zip)

### Configuration
**Operating system:**
windows 10 16299 x64
**Version of Telegram Desktop:**
1.2.6.0
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@acrobatman Can you send the dump file to t.me/preston? Thanks.

**Comment by acrobatman** [comment]
OK,the file sent to you

**Comment by Aokromes** [comment]
no answer since dec 2018, closing, if this bug is still valid ask to reopen.
