### ISSUE TITLE
404 error at download page for mac os version

### ISSUE THREAD

**Issue by dscottboggs** [telegramdesktop/tdesktop#4442]
### Steps to reproduce
1. visit https://telegram.org/dl/desktop/mac (which redirects to https://updates.tdesktop.com/tmac/tsetup.1.2.6.dmg )
2. observe 404

### Expected behaviour
A .dmg file should download

### Actual behaviour
404 error

### Configuration
**Operating system:**
macOS
**Version of Telegram Desktop:**
n/a

**Comment by rustamtolipov** [comment]
The same for windows version

https://updates.tdesktop.com/tsetup/tsetup.1.2.6.exe - 404 not found

**Comment by rustamtolipov** [comment]
I've installed older version (1.1.10) and tried to update. Update fails:

![image](https://user-images.githubusercontent.com/8638146/36463439-c54e6838-16eb-11e8-943e-ec36ab463678.png)

**Comment by mopperwhite** [comment]
The same for Linux version

https://updates.tdesktop.com/tlinux/tsetup.1.2.6.tar.xz

**Comment by john-preston** [comment]
@dscottboggs Thanks, should be fine now. Sorry :/

**Comment by dscottboggs** [comment]
Thanks for fixing!
