### ISSUE TITLE
Tweet preview width when tweet has tall+narrow image

### ISSUE THREAD

**Issue by hintss** [telegramdesktop/tdesktop#4443]
Linking a tweet with very tall and narrow image (in this case, 250 wide by 1200 tall) results in the text portion of the tweet wrapping lines at the right edge of the image, which ends up being very narrow in relation to the rest of the message.

![image](https://user-images.githubusercontent.com/848163/36507987-31cd903c-1710-11e8-8964-b7e457a199b4.png)

My telegram client version: 

![image](https://user-images.githubusercontent.com/848163/36508029-51b47c1c-1710-11e8-8446-e52322dc71d5.png)

**Comment by stek29** [comment]
That's not TDesktop.

Report the issue to https://t.me/macswift.
TDesktop can be downloaded at https://desktop.telegram.org (or using another Telegram app in AppStore, not the one you got)
