### ISSUE TITLE
TELEGRAM FAILS TO START IN LINUX(KALI 2.0)

### ISSUE THREAD

**Issue by alvinmurimi** [telegramdesktop/tdesktop#4444]
My telegram desktop has been working fine since i installed it, until today, when i got this error while launching it.
```
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
AL lib: (EE) ALCcaptureAlsa_open: Could not open capture device 'default': No such file or directory
AL lib: (WW) alcSetError: Error generated on device (nil), code 0xa004
Telegram: Fatal IO error 2 (No such file or directory) on X server :0.

```
I've got no idea where the error came from, i tried installing the latest version of the app but i still get the same error. As i said, it was working fine before. What might be the problem? I urgently need to use telegram

**Comment by stek29** [comment]
Use Webogram if you need TG urgently.
Something is likely broken in OS, try using other Qt apps, try rebooting if you haven't yet, try using a normal OS or at least make a user for yourself and don't do everything as root.

**Comment by alvinmurimi** [comment]
Ok. Thanks @stek29 for the reply.
When i switch to another user and start telegram, i get this error
```

QXcbConnection: Could not connect to display 
./Telegram[0x8e234d]
./Telegram[0x8e292c]
./Telegram(_ZN15google_breakpad16ExceptionHandler12GenerateDumpEPNS0_12CrashContextE+0x3d1)[0x111c611]
./Telegram(_ZN15google_breakpad16ExceptionHandler13SignalHandlerEiP9siginfo_tPv+0xb0)[0x111c940]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x123b0)[0x7f300a53e3b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x110)[0x7f3009c92a70]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x17a)[0x7f3009c9419a]
./Telegram[0x1dffb61]
./Telegram[0x151f879]
./Telegram(_ZN15QXcbIntegrationC1ERK11QStringListRiPPc+0x2da)[0x14f5afa]
./Telegram[0x14f47fb]
./Telegram[0x1cd02ad]
./Telegram[0x1a01a5d]
./Telegram[0x1a02645]
./Telegram[0x1fc4715]
./Telegram[0x1a039cc]
./Telegram[0x16e4a19]
./Telegram(_ZN11ApplicationC2EN3gsl8not_nullIPN4Core8LauncherEEERiPPc+0x3a)[0xf85b0a]
./Telegram(_ZN4Core8Launcher18executeApplicationEv+0x31)[0x8df841]
./Telegram(_ZN4Core8Launcher4execEv+0x44)[0x8df8d4]
./Telegram(main+0x25)[0x7bc1d5]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f3009c7f561]
./Telegram[0x7d227c]
Aborted

```
Am not sure what the course it. But in the mean time, lemme try out Webogram

**Comment by stek29** [comment]
Something is definitely wrong with Xorg.

**Comment by xvitaly** [comment]
> Something is definitely wrong with Xorg.

Everything wrong with Kali. Kali is the worst distribution ever. Every application on it (even X11 and DE) works under root account.

**Comment by stevenpusser** [comment]
WTF are you using Kali for messaging?
