### ISSUE TITLE
Hebrew bold formatting not working

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#4445]
### Steps to reproduce
1.  Write a text in Hebrew
2.  Surround it by double asterisks
3.  Send

For example, this:
```
עוגיות
__עוגיות__
**עוגיות**

Cookies
__Cookies__
**Cookies**
```
Results in:
![image](https://user-images.githubusercontent.com/3811594/36568096-6a174876-1831-11e8-9f7b-195765c02aa4.png)

### Expected behaviour
The text should be formatted in bold

### Actual behaviour
The text is not bold

### Note:
It seems to be a general problem, since also on my android the result is the same - both on the official and the X versions. I don't know if it's a coincidence or it's related to the backend - so better to report it anyway :)

If it's more general, I would really appreciate it if it can be forward to the relevant developers. It's really missing.

Thanks!

____

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.2.8
**Used theme**: Regular

**Comment by Aokromes** [comment]
#1917 generic bug.

**Comment by arieljannai** [comment]
I added a comment to the more active issue mentioned, relating the same. Closing this one.
