### ISSUE TITLE
Japanese characters are not displayed

### ISSUE THREAD

**Issue by bashkos** [telegramdesktop/tdesktop#4446]
### Steps to reproduce
1. Install Telegram Desktop from Ubuntu Software Center
2. Send message with japanese text, like "本日"

### Expected behaviour
Japanese characters should displayed

### Actual behaviour
Japanese characters not displayed
![screenshot](http://image.ibb.co/e4vSCc/2018_02_25_17_22_49.png)

### Configuration
**Operating system:**
Ubuntu 17.10
**Version of Telegram Desktop:**
1.2.6
**Used theme**:
Night mode

**Comment by d0tfile** [comment]
ArchLinux + Gnome (3.26.2) + Telgram Desktop (1.2.8), no issue. Maybe you have missing fonts? Do other apps work fine? I see gedit, but can you check any asian site with FireFox?
![image](https://user-images.githubusercontent.com/4760202/36640381-5420cd54-1a2e-11e8-8072-b64ef0eeb634.png)

**Comment by bashkos** [comment]
Thank you. It solved problem.
