### ISSUE TITLE
Ibus intelligent pinyin not working in telegram-desktop snap apps

### ISSUE THREAD

**Issue by wolfsonliu** [telegramdesktop/tdesktop#4449]
### Steps to reproduce
1. install the snap telegram desktop
2. open the telegram program
3. switch the input method to ibus intelligent pinyin
4. input words.

### Expected behaviour
Chinese character should be inputed.

### Actual behaviour
You could only input English character, and the Chinese input method was not working at all.

### Configuration
**Operating system:** Ubuntu 16.04

**Version of Telegram Desktop:** 1.2.6

**Used theme**: 

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
> telegram-desktop snap apps 

Does it work in official binary?

**Comment by wolfsonliu** [comment]
I had tried the official one, and it worked. So, I guess it might be the problem of snap sandbox?

**Comment by stek29** [comment]
I guess so, and the snap package isn't official, so you'd have to contact package maintainers.

**Comment by stek29** [comment]
I guess so, and the snap package isn't official, so you'd have to contact package maintainers.

**Comment by chenzhiwei** [comment]
@stek29 Hi, I think the telegram-desktop snap app is the official one now, the PR was merged in https://github.com/telegramdesktop/tdesktop/pull/4505 and it is displayed in supported systems: https://github.com/telegramdesktop/tdesktop#supported-systems

@3v1n0 Hi, I also mentioned this issue in https://forum.snapcraft.io/t/call-for-testing-telegram-desktop/3954, could you help take a look? I can use the ibus IME in the binary client.

**Comment by fujiwarat** [comment]
@chenzhiwei The ibus qt module was recently implemented for qt-base 5.11.

**Comment by fujiwarat** [comment]
http://code.qt.io/cgit/qt/qtbase.git/commit/?id=2adc06f9406ec2f8c02d1619c73f384eb2947498
I confirmed qtbase 5.11.2 includes the fix.

**Comment by chenzhiwei** [comment]
@fujiwarat Thank you for letting me know this change.

Can I enable ibus by upgrading the qtbase to 5.11.2? or the snap/flatpak package should be re-built with qbase 5.11.2?

I tried to upgrade qtbase and a lot of dependencies to [5.11.2](http://ftp.cn.debian.org/debian/pool/main/q/qtbase-opensource-src/) but still can't use ibus in flatpck app.

**Comment by fujiwarat** [comment]
@chenzhiwei Did you try Qt applications on org.kde.Platform//5.11 ?

**Comment by chenzhiwei** [comment]
@fujiwarat No, I tried Slack and it uses org.freedesktop.Platform//18.08.

**Comment by chenzhiwei** [comment]
@fujiwarat So you mean if I can update the runtime(`org.freedesktop.Platform//18.08`) to include the new qt module, then the Slack flatpak app can use ibus without any changes?

**Comment by fujiwarat** [comment]
Yes in case that Slack is a QT application.

**Comment by john-preston** [comment]
@fujiwarat AFAIK Slack is an Electron app.

**Comment by fujiwarat** [comment]
And then probably Electron needs to implement Flatpak IBus. @john-preston Thank you.

**Comment by chenzhiwei** [comment]
Already created an issue to Electron base App: https://github.com/flathub/io.atom.electron.BaseApp/issues/4

@fujiwarat @john-preston Thank you guys.

**Comment by 3v1n0** [comment]
@chenzhiwei having `QTCOMPOSE` and `QT_XKB_CONFIG_ROOT` fixes you the problem?

For ibus, I've blacklisted it because it was breaking the XComposition otherwise in most of setups, you could actually force another IM system by using the environment variable `TELEGRAM_QT_IM_MODULE` that will be used as the `QT_IM_MODULE` whatever you set.

Problem is that inside the snap we might not have access to the proper component.

Logs from `snap run --strace telegram-desktop` or `dmesg` might help in understanding.

**Comment by juhp** [comment]
Perhaps I should open another ticket but for the record I can't get ibus working with the Telegram flatpak either.

**Comment by john-preston** [comment]
@juhp Does ibus work with the binary from desktop.telegram.org?

**Comment by juhp** [comment]
Yes (though I could only get it to run via strace so far on recent Fedora).

**Comment by fujiwarat** [comment]
I don't know why you refer Slack in Flatpak on this telegram-desktop issue but recently I fixed Atom using Electron in Flatpak and hope Slack is also fixed;
https://github.com/ibus/ibus/issues/1991

If this issue in Flatpak, probably I'd like to know how to install with flatpak-builder.
