### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by nazar2sfive** [telegramdesktop/tdesktop#4450]
no1 : i have already downloaded all these files in linux to same download directory. But in windows it again shows me the option to download the file again. when i click on download, the file starts to download again. So i want telegram to know that file is already downloaded.
![image](https://user-images.githubusercontent.com/12841320/36673749-e6dea262-1b2b-11e8-85c8-7819cbeab2d0.png)

no 2 : i want a button on top to select multiple files at once, or all at once.

**Comment by d0tfile** [comment]
no 2: https://github.com/telegramdesktop/tdesktop/issues/1382

**Comment by stek29** [comment]
#1965
