### ISSUE TITLE
🌼🌼🌼  Scrolling in stickers

### ISSUE THREAD

**Issue by isopen** [telegramdesktop/tdesktop#4452]
I have a good internet speed.

### Steps to reproduce
1. View Stickers
2. Quickly scroll to the middle
3. Pictures in focus are displayed very slowly

I think there are not the correct loading priorities. Possible variant. Pause the download of images that are not in focus. Start shipping only those that are in focus.

When cached on the client side, then you also need to think something. With fast scrolling, there may be pauses(with a certain load on the client computer other applications).

Version 1.2.6. Windows 10

Das ist Fantastisch.

**Comment by isopen** [comment]
It seems that the component for loading is one. He is one. You can easily implement the implementation and implement it throughout the application.

Reducing the consumption of traffic is obvious.

**Comment by isopen** [comment]
Here works faithfully https://github.com/DrKLO/Telegram
![image](https://user-images.githubusercontent.com/7373292/36740099-0f224434-1c14-11e8-99ce-1bd524e67d56.png)

**Comment by stek29** [comment]
You should learn not to be that salty.

**Comment by isopen** [comment]
I appreciated the word "salty" :)
I just wrote it here.
If you do not like it, you can delete it. Someone else will write it here.

**Comment by isopen** [comment]
![image](https://user-images.githubusercontent.com/7373292/36751431-c00b4868-1c32-11e8-927e-28fde5d87002.png)

**Comment by isopen** [comment]
**Not clone the repositories, then I do not understand what kind of freedom is involved.**

**Comment by isopen** [comment]
Do not be rude. Please write something adequate on current issues.

**Comment by isopen** [comment]
If want I can write still a heap of bugs here.
