### ISSUE TITLE
₽ symbol isn't displayed correctly 

### ISSUE THREAD

**Issue by maxkachalin** [telegramdesktop/tdesktop#4454]
### Steps to reproduce
1. Run Telegram Desktop.
2. Go to chat with someone.
3. Try to send ₽ symbol.

### Expected behaviour
₽ should be visible in command line and chat window.

### Actual behaviour
Rectangle inserted to command line and chat window instead of ₽ symbol.

### Configuration
Mac OS High Sierra 10.13.3 (17D102)

**Version of Telegram Desktop:**
Telegram Desktop 1.2.6

**Used theme**:
Default

**Comment by isopen** [comment]
![image](https://user-images.githubusercontent.com/7373292/36824327-507a9500-1d34-11e8-9f2a-0270ecaaf407.png)
![image](https://user-images.githubusercontent.com/7373292/36824431-d793aa72-1d34-11e8-82a6-f15618585557.png)

**Comment by isopen** [comment]
Perfectly noticed. More bugs. More. Otherwise, the application quality degrades

**Comment by auchri** [comment]
@isopen I'm going to block you if you don't stop writing stupid comments.

**Comment by isopen** [comment]
Please correct the symbol. I can not explain to my girl why I can not send ₽ to her.

**Comment by maxkachalin** [comment]
@isopen, do you think your comments are funny or relevant to bug with official UTF-8 russian ruble sign?

In addition, bug also applies to «ẞ» symbol as well, for example, and others. I think it could be related to font used by the app but not sure.

**Comment by d0tfile** [comment]
@maxkachalin Telegram Desktop 1.2.8 on Arch Linux + Gnome. Can you check [1.2.8](https://github.com/telegramdesktop/tdesktop/releases/tag/v1.2.8) version?
![image](https://user-images.githubusercontent.com/4760202/36864139-d991b996-1d9c-11e8-9844-4004b1fff24a.png)

**Comment by maxkachalin** [comment]
Mac OS High Sierra 10.13.3 (17D102) + Telegram Desktop 1.2.8 alpha

![2018-03-01 22 22 22](https://user-images.githubusercontent.com/4002368/36865006-583cf2ea-1d9f-11e8-818f-13c9632f61ed.png)

![2018-03-01 22 22 52](https://user-images.githubusercontent.com/4002368/36865010-59ffa7ee-1d9f-11e8-8208-cc2f96dc4d9c.png)

**Comment by isopen** [comment]
@maxkachalin I think without such comments in the developer there will be no desire to fix this kind of trivia. But their order is already growing.

**Comment by PeterMX** [comment]
It works OK on Ubuntu 17.10, Telegram 1.2.8:
![image](https://user-images.githubusercontent.com/9899682/36930054-70967cba-1e5f-11e8-9cab-128adc775426.png)

**Comment by isopen** [comment]
Try for windows 10

Комбинируемая прописная латинская буква Esh
Combining Latin Small Letter Esh
Номер в Юникоде: U+1DEF
HTML-код: &#7663;

**Comment by mastizada** [comment]
Same with "ə" (also capital, "Ə") symbol. It worked perfectly before. Version 1.2.17 Arch Linux (Downloaded directly from telegram.org).

**Comment by Aokromes** [comment]
#3363

**Comment by maxkachalin** [comment]
₽  symbol for example still displayed incorrectly in monospaced font when using three backtics to insert "code".

<img width="121" alt="Screenshot 2019-04-23 22 05 18" src="https://user-images.githubusercontent.com/4002368/56608710-12a9ae80-6614-11e9-988b-9ec934009f64.png">
