### ISSUE TITLE
Displaying chats with unread messages

### ISSUE THREAD

**Issue by Twister83** [telegramdesktop/tdesktop#4455]
### Steps to reproduce
1. Open Telegam.exe
2. Go to the list of chats

### Expected behaviour
I would like to be able to select chats with unread messages.

### Actual behaviour
If you have a lot of chats in Telegram, it is difficult to find those chats where there are unread messages

### Configuration
**Operating system:**

Windows 10

**Comment by d0tfile** [comment]
Duplicate? https://github.com/telegramdesktop/tdesktop/issues/1067
