### ISSUE TITLE
Feature Request: Sub-categories for Shared Media in SuperGroups

### ISSUE THREAD

**Issue by inferKNOX** [telegramdesktop/tdesktop#4456]
Would it be possible to add sub-categories for shared media, to allow for structuring of shared content?

For example, in a study group, it would be easier to deal with if one could make an "Exam Papers" sub-category, "Study Guides" sub-category, etc.
When uploading, it would offer the user to assign the file to an new/existing sub-category, or leave it uncategorised. Any files that are already uploaded can then be categorised or recategorised by an admin with the rights to do so.

In terms of display, they could be collapsible sub-categories under the main shared media categories (ie, Files, Links, etc), and uncategorised files would default to an "uncategorised" sub-category at the bottom of each list.
The month that it was uploaded would then be dividers within the respective sub-categories.

```
> SuperGroup
     > Shared Media
          > Links (Category)
               > Exam Papers (Sub-category)
                    - January (divider)
                    .... (shared content)
                    - February
                    ....
               > Study Guides
                    - January
                    ....
                    - February
                    ....
               > uncategorised (sub-category for remaining uncategorised media)
                    - January
                    ....
                    - February
                    ....
          > Files
               > Exam Papers
                    - January
                    ....
                    - February
                    ....
               > Study Guides
                    - January
                    ....
                    - February
                    ....
               > uncategorised
                    - January
                    ....
                    - February
                    ....

**Comment by RememberTheAir** [comment]
I guess that's something that needs to be supported by the API first, as you would expect to find this categorization on your other loggedin clients too

**Comment by inferKNOX** [comment]
Yup, I've taken the idea here: https://www.reddit.com/r/ideasfortelegram/
Is there any better place than that?

**Comment by isopen** [comment]
This is a new feature. It would be great! I do not think that it will be very soon.

**Comment by auchri** [comment]
@isopen ok bye!

**Comment by isopen** [comment]
1

**Comment by isopen** [comment]
![image](https://user-images.githubusercontent.com/7373292/36903567-b2646598-1e60-11e8-8902-9a2a06dff185.png)

**Comment by stek29** [comment]
API issue indeed
