### ISSUE TITLE
The character is hard to remove

### ISSUE THREAD

**Issue by isopen** [telegramdesktop/tdesktop#4458]
It needs to be corrected
https://youtu.be/qzAkX-xPMXY

version 1.2.6, 1.2.8 windows 10

**Comment by auchri** [comment]
Use the template.

**Comment by isopen** [comment]
Yes, I do not care about your template. I speak as it is.

**Comment by auchri** [comment]
@isopen Then don't write issues.

**Comment by isopen** [comment]
It's complicated.
