### ISSUE TITLE
Voice call is not working. I can't hear the voice of caller.

### ISSUE THREAD

**Issue by tural-esger** [telegramdesktop/tdesktop#4459]
### Steps to reproduce
1. I call someone or they call me.
2.  I can't hear their voice.
3. Microphone and speakers work well with other apps such as Skype< Facebook and so on.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
---------------
libtgvoip v1.0.3 on Windows 6.2.9200  x86
Log started on 3/03/2018 at 11:07:05
---------------
03-03 11:07:05 I: update data saving mode, config 0, enabled 0, reqd by peer 0
03-03 11:07:05 W: Starting voip controller
03-03 11:07:05 V: trying bind to port 23129
03-03 11:07:05 D: Bound to local UDP port 23129
03-03 11:07:05 V: Call state changed to 2
03-03 11:07:05 I: Receive thread starting
03-03 11:07:05 E: error receiving 10054
03-03 11:07:05 E: Packet has null address. This shouldn't happen.
03-03 11:07:05 V: Sending UDP ping to 91.108.8.2:522
03-03 11:07:05 V: Sending UDP ping to 91.108.21.49:540
03-03 11:07:05 V: Sending UDP ping to 188.93.22.234:25
03-03 11:07:05 V: Sending UDP ping to 91.108.8.1:520
03-03 11:07:05 D: SIGNAL BAR COUNT CHANGED: 1
03-03 11:07:05 E: error receiving 10054
03-03 11:07:05 E: Packet has null address. This shouldn't happen.
03-03 11:07:05 I: Detected IPv4 connectivity, will not try IPv6
03-03 11:07:05 D: SIGNAL BAR COUNT CHANGED: 2
03-03 11:07:05 D: SIGNAL BAR COUNT CHANGED: 3
03-03 11:07:05 D: SIGNAL BAR COUNT CHANGED: 4
03-03 11:07:06 V: Call state changed to 2
03-03 11:07:06 E: error receiving 10054
03-03 11:07:06 E: Packet has zero length.
03-03 11:07:06 D: Received init
03-03 11:07:06 I: Peer version is 3
03-03 11:07:06 W: Received duplicated packet for seq 1
03-03 11:07:06 V: Call state changed to 2
03-03 11:07:06 E: error receiving 10054
03-03 11:07:06 E: Packet has zero length.
03-03 11:07:06 D: Received init
03-03 11:07:06 I: Peer version is 3
03-03 11:07:06 D: Received init ack
03-03 11:07:06 I: peer version from init ack 3
03-03 11:07:06 I: before create audio io
03-03 11:07:06 V: buffer size: 2880
03-03 11:07:06 D: capture latency: 60
03-03 11:07:06 V: set current output device done
03-03 11:07:06 V: buffer size: 2880
03-03 11:07:06 D: playback latency: 60
03-03 11:07:06 V: set current output device done
03-03 11:07:06 V: starting encoder, packets per frame=3
03-03 11:07:06 I: Sending public endpoints request
03-03 11:07:06 D: Sending public endpoints request to 91.108.8.2:522
03-03 11:07:06 I: decoder: packets per frame 3
03-03 11:07:06 W: jitter: found no packet for timestamp -3956102967201295 (last put = 0, lost = 0)
03-03 11:07:06 W: jitter: found no packet for timestamp -3956102967201235 (last put = 0, lost = 0)
03-03 11:07:06 V: 03-03 11:07:06 V: Trying to recover late packet
Call state changed to 3
03-03 11:07:06 W: jitter: found no packet for timestamp -3956102967201295 (last put = 0, lost = 0)
03-03 11:07:06 V: PLC
03-03 11:07:06 I: jitter: resyncing, next timestamp = -120 (step=60, minDelay=3)
03-03 11:07:06 W: Received duplicated packet for seq 3
03-03 11:07:06 W: jitter: found no packet for timestamp -120 (last put = 120, lost = 0)
03-03 11:07:06 V: Trying to recover late packet
03-03 11:07:06 W: jitter: found no packet for timestamp -180 (last put = 120, lost = 0)
03-03 11:07:06 V: PLC
03-03 11:07:06 D: new delay from stddev 2
03-03 11:07:06 V: Sending ping to 91.108.8.2
03-03 11:07:06 V: Sending ping to 91.108.21.49
03-03 11:07:06 V: Sending ping to 188.93.22.234
03-03 11:07:06 V: Sending ping to 91.108.8.1
03-03 11:07:06 W: jitter: found no packet for timestamp -60 (last put = 120, lost = 0)
03-03 11:07:06 V: outstanding delay change: -40
03-03 11:07:06 V: Trying to recover late packet
03-03 11:07:06 W: jitter: found no packet for timestamp -120 (last put = 120, lost = 0)
03-03 11:07:06 V: outstanding delay change: -20
03-03 11:07:06 V: PLC
03-03 11:07:06 V: opus_encoder: setting bitrate to 17000
03-03 11:07:06 E: error receiving 10054
03-03 11:07:06 E: Packet has zero length.
03-03 11:07:06 V: new endpoint 0: 85.132.117.223:3726
03-03 11:07:06 W: Received reflector peer info, my=AF0B8455:23129, peer=DF758455:3726
03-03 11:07:06 W: jitter: found no packet for timestamp 0 (last put = 180, lost = 0)
03-03 11:07:06 V: outstanding delay change: 0
03-03 11:07:06 V: Trying to recover late packet
03-03 11:07:06 W: jitter: found no packet for timestamp -60 (last put = 180, lost = 0)
03-03 11:07:06 V: PLC
03-03 11:07:06 V: Sending ping to 85.132.117.223
03-03 11:07:07 V: Trying to recover late packet
03-03 11:07:07 W: jitter: found no packet for timestamp 0 (last put = 240, lost = 0)
03-03 11:07:07 D: Current RTT via 91.108.8.2: 0.207, average: 0.207
03-03 11:07:07 D: Received ping from 91.108.8.2:522
03-03 11:07:07 D: Received ping from 91.108.21.49:540
03-03 11:07:07 D: Current RTT via 91.108.21.49: 0.481, average: 0.481
03-03 11:07:07 V: opus_encoder: setting bitrate to 18000
03-03 11:07:08 V: opus_encoder: setting bitrate to 19000
03-03 11:07:10 V: opus_encoder: setting bitrate to 20000
03-03 11:07:10 V: outstanding delay change: 0
03-03 11:07:11 V: outstanding delay change: 0
03-03 11:07:15 D: Entered VoIPController::~VoIPController
03-03 11:07:15 D: before shutdown socket
03-03 11:07:15 D: before join sendThread
03-03 11:07:15 E: tried to send null packet
03-03 11:07:15 I: === send thread exiting ===
03-03 11:07:15 D: before join recvThread
03-03 11:07:15 D: before join tickThread
03-03 11:07:15 I: === tick thread exiting ===
03-03 11:07:15 D: before close socket
03-03 11:07:15 D: before delete jitter buffer
03-03 11:07:15 D: before stop decoder
03-03 11:07:15 I: ==== decoder exiting ====
03-03 11:07:15 D: before delete audio input
03-03 11:07:15 V: capture thread shutting down
03-03 11:07:15 D: before delete encoder
03-03 11:07:15 D: before delete audio output
03-03 11:07:15 V: render thread shutting down
03-03 11:07:15 D: before delete decoder
03-03 11:07:15 D: before delete echo canceller

[11:07:24.219 01-0000948] MTP Info: emitting needToReceive() - need to parse in another thread, 1 responses, 0 updates. (connection.cpp : 1454)
[11:07:24.219 00-0000949] MTP Info: dcWithShift 2 can wait for 10000ms from current 0 (session.cpp : 212)
[11:07:24.219 00-0000950] RPC Info: parser not found for 155 (mtp_instance.cpp : 829)

[11:07:34.321 01-0000958] (dc:2) Recv: { core_message
  msg_id: 6528611645311280129 [LONG],
  seq_no: 274 [INT],
  bytes: 20 [INT],
  body: { pong
    msg_id: 6528611652189410168 [LONG],
    ping_id: 4681490677411373438 [LONG],
  },
}

</details>

**Comment by stek29** [comment]
Does audio playback work?
Is the user you're talking to heard by others?

Please fill the template properly.

**Comment by Aokromes** [comment]
Try on the latest 1.2.9 alpha :)

**Comment by Aokromes** [comment]
#3938 ?
