### ISSUE TITLE
ZWNJ issue on Telegram Desktop

### ISSUE THREAD

**Issue by ebraminio** [telegramdesktop/tdesktop#446]
Follow up to this [tweet](https://twitter.com/Mardetanha/status/559310935173906432), it seems Telegram desktop has some issue on inserting [ZWNJ](https://en.wikipedia.org/wiki/Zero-width_non-joiner) and [ZWJ](https://en.wikipedia.org/wiki/Zero-width_joiner) on text editor. The issue is not available when text containing these characters copied from or android and web clients.

Steps to reproduce:
1. Install a standard Persian language (fa) Keyboard (available on Windows 8+ or simply download it from [here](http://persian-computing.org/download/Iranian_Standard_Persian_Keyboard_(ISIRI_9147)_(Version_2.0).zip))
2. Open a chat window
3. Switch to Persian Keyboard layout and press Shift+B (B key position on Latin keyboard) or Shift+Space. (it is something like the character I put between quotes: "‌", it is a control character and normally you can not see it but doesn't mean it is not available)
4. Ideally you should be able to press enter and send the message but because telegram can not insert that character it thinks nothing is available to send.

**Comment by telegramdesktop** [comment]
Send a message containing only one control character? What for? Or does it remove such characters from the text after sending (when there is a text except that control character)?

**Comment by ebraminio** [comment]
It is just a minimalized testcase, you can not insert it anywhere more appropriate either. Have a look at the article I've [linked](https://en.wikipedia.org/wiki/Zero-width_non-joiner). ZWNJ is used for expressing words correctly on Persian and Indic languages and is part of the message and shouldn't be just prevented to write. For example:

س [A Persian character] + ZWNJ + س will result:
# س‌س
but without ZWNJ it will be like something that is different and can mean differently:
# سس

**Comment by telegramdesktop** [comment]
I am afraid it is an open Qt bug: https://bugreports.qt.io/browse/QTBUG-42074 and that we should wait while Qt team will fix that, I'm not sure I can fix that myself.

**Comment by telegramdesktop** [comment]
I think I've found a place to fix it inside Qt, I can include the fix in next dev-version (it will be 0.7.14.dev), if you are ready to test this (better in different OS).

**Comment by ebraminio** [comment]
Great!! Yes. I have a Linux and Windows, also a 10.6 old Mac.

**Comment by ebraminio** [comment]
Ops, I've forget that the old 10.6 Mac is no longer around :-)

**Comment by mardetanha** [comment]
I will find mac also, and test it .

**Comment by ebraminio** [comment]
If it is a white-listing of something, also please fix ZWJ, it is just like ZWNJ and is place on ` (back quote) of a standard Persian keyboard and also is not working on tdesktop.

**Comment by telegramdesktop** [comment]
Please try out 0.7.14.dev version from https://desktop.telegram.org/#dev-version-of-telegram-desktop and tell if these characters are fixed there.

**Comment by ebraminio** [comment]
:+1: for Linux and Windows. Thank you

**Comment by mardetanha** [comment]
Fixed on Mac too, Thanks indeed

**Comment by ebraminio** [comment]
So this is fixed, thank you very much :)

**Comment by ebraminio** [comment]
I heard this got broken again from a user. Did you upgrade At and missed this? Can you add it again?
