### ISSUE TITLE
 Upload Foto without compression as WITH compression

### ISSUE THREAD

**Issue by Redee** [telegramdesktop/tdesktop#4462]
### Steps to reproduce
1. Upload Foto without compression

### Expected behaviour
Need correct upload Foto without compression

### Actual behaviour
Upload Foto WITH compression
Only from repeat upload - upload without compression

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.2.6

**Used theme**:
Standard

step1 >>
![step1](https://user-images.githubusercontent.com/2652667/36943451-55f8e1b6-1f92-11e8-9bb1-986824775b81.jpg)

step2 >>
![step2](https://user-images.githubusercontent.com/2652667/36943452-561f36a4-1f92-11e8-9974-82548a2d30df.jpg)

scr_original >>
![scr_original](https://user-images.githubusercontent.com/2652667/36943449-55b125ce-1f92-11e8-92f2-528f645a6d4e.jpg)

scr_uploaded >>
![scr_uploaded](https://user-images.githubusercontent.com/2652667/36943450-55d89186-1f92-11e8-8fef-cdc2be1d84ec.jpg)

**Comment by auchri** [comment]
I you want to send a photo without compression, use "Send as file".

**Comment by Redee** [comment]
Whe second repeat send WITHOUT compression ?

**Comment by Redee** [comment]
LOL closed if still issue !!!!

**Comment by auchri** [comment]
@Redee I don't understand your problem, sorry.

**Comment by Redee** [comment]
Its not my problem - its your!
WITHOUT compression as photo - uploaded like WITH compression.
Arrrrrrrrrrrrrrr

**Comment by Redee** [comment]
LOL again!

**Comment by auchri** [comment]
@Redee If you are not able to explain your problem so that others can understand it, it's NOT our problem.

**Comment by Redee** [comment]
Me need AS PHOTO WITHOUT COMPRESSION - NOT FILE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Redee** [comment]
Why second upload as photo WITHOUT COMPRESSION - try themselves and not talk me - "not able to explain"

**Comment by john-preston** [comment]
@Redee Such option (send as photo without compressing the file) is not available and is not planned, sorry

**Comment by stek29** [comment]
And it needs to be supported by server side anyway
