### ISSUE TITLE
Please add tabs to separate personal messages / groups / channels / bots

### ISSUE THREAD

**Issue by PvUtrix** [telegramdesktop/tdesktop#4463]
If you have as many groups and channels as I do, you begin to lose personal messages as they are being taken down by a never ending stream of messages from groups and channels.
It would be nice to have tabs to separate messages by types
personal / groups / super groups / channels / bots / favourites(optional) 

p.s. This is nicely implemented in an android app , Plus messenger, it's saving me so much time!

**Comment by PvUtrix** [comment]
This is nicely implemented in an android app , Plus messenger, it's saving me so much time!

**Comment by alekseymvt** [comment]
The authors spit on our requests. It's a little better here https://bettergram.io/
