### ISSUE TITLE
i cant send msg to any group + bot

### ISSUE THREAD

**Issue by qandeelmohammad** [telegramdesktop/tdesktop#4464]
and i face this msg 
Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":400,"error_message":"YOU_BLOCKED_USER"}
how i can solve it ?

**Comment by d0tfile** [comment]
Try https://telegram.me/spambot

**Comment by qandeelmohammad** [comment]
i cant send a msg to https://telegram.me/spambot
 i face the same problem

**Comment by d0tfile** [comment]
@qandeelmohammad, any info about "YOU_BLOCKED_USER" is connected to bots. If it is, ask in this chat (https://t.me/BotTalk). If you facing this problem with regular user and not only in Telegram Desktop, contact support via app (Settings -> Ask a Question) or in twitter (https://twitter.com/telegram, i guess).
If you facing this problem only in Telegram Desktop, fill issue template and ask for reopen.

**Comment by stek29** [comment]
@d0tfile that error message is from Webogram *shrug*

**Comment by tcelestino** [comment]
@qandeelmohammad you need to restart bot to resolve this problem.

**Comment by drepram** [comment]
Seems like when I send a message from my phone instead of my computer, it works.
