### ISSUE TITLE
Closing the window on a desktop without a system tray/icons should stop the application

### ISSUE THREAD

**Issue by aruiz** [telegramdesktop/tdesktop#4465]
### Steps to reproduce
1. Open the application on a desktop without a systray (say, GNOME in Fedora 27)
2. Hit Ctrl+W
3. The application keeps running

### Expected behaviour
The application should close

### Actual behaviour
The application remains open

### Configuration
**Operating system:**
Fedora Workstation 27 
**Version of Telegram Desktop:**
1.2.6

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3830
