### ISSUE TITLE
Cursor jumps from message to sticker search

### ISSUE THREAD

**Issue by kiparisandrew** [telegramdesktop/tdesktop#4466]
### Steps to reproduce
1. Set "Show sidebar"
2. Open any chat, and start typing
3. 

### Expected behaviour
I can type message and send it

### Actual behaviour
After first character is inserted type focus jumps to sidebar sticker search field and I can't message noramly. It happens for each putted symbol.

### Configuration
**Operating system:**
MacOS 10.13.2
Macbook 15 touchbar

**Version of Telegram Desktop:**
3.8.118914

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by kiparisandrew** [comment]
I can't use desktop client at all

**Comment by john-preston** [comment]
@kiparisandrew This is another application. You can try Telegram Desktop from https://desktop.telegram.org

**Comment by overtake** [comment]
Hi. Sorry about that. I'm uploading new build with hot fix. check new update in 15 min please.

**Comment by stek29** [comment]
@kiparisandrew In future you can report issues for that app at https://t.me/macswift or https://github.com/overtake/TelegramSwift

**Comment by kiparisandrew** [comment]
Thanks guys! Fix works fine for me.
It nice to see so operative issue fix 👍
