### ISSUE TITLE
"Quick reply" deactivates message box

### ISSUE THREAD

**Issue by Kylmakalle** [telegramdesktop/tdesktop#4467]
### Steps to reproduce
1. (Quick Reply.) Double click near a message for a quick reply.
2. Try to start typing

### Expected behaviour
You're typing in the message box right after double clicking.

### Actual behaviour
Quick reply function makes message box inactive, blinker disappears, you need to activate it again with clicking on it.
[Video](https://streamable.com/r6lqf)

### Configuration
**Operating system:**
MacOS 10.13.3 (17D102) / Win 10 pro (16299.19)
**Version of Telegram Desktop:**
1.2.9 (Alpha)

**Comment by john-preston** [comment]
@Kylmakalle Indeed. This happens if you click inside a bubble I guess. Is it working fine if you click outside of the bubble? I'll fix the inside case in the next version.

**Comment by Kylmakalle** [comment]
@john-preston
Yes, it's working fine if I click outside of message bubble
