### ISSUE TITLE
Please return mentions in channels

### ISSUE THREAD

**Issue by Senderman** [telegramdesktop/tdesktop#4469]
### Steps to reproduce
1. Ask someone to mention you in channel
2. Look at your chats&channels list

### Expected behaviour
"@" appears. It may be useful if, e.g. you won a lottery in channel, or there's news about you. Also, Android Telegram Client still supports this feature

### Actual behaviour
Message with mention looks like an ordinary message

### Configuration
**Operating system:**
Windows 8.1, Archlinux
**Version of Telegram Desktop:**
1.2.9 alpha
**Used theme**:
Any

**Comment by john-preston** [comment]
@Senderman Mentions are not supported by server in channels. So they were just buggy not working in tdesktop, so I've removed them. Sorry.

**Comment by Senderman** [comment]
Well, if channel's mentions are not supported by server, how does it work in Telegram Android?

**Comment by john-preston** [comment]
@Senderman You can set them locally, but in case of telegram desktop it worked worse than on Android, because it doesn't save the state between relaunches. And it looked like you got a mention and when you relaunch the app the mention is gone and some other sync bugs.

**Comment by Senderman** [comment]
Then what about mentions in chats in tgdesktop? Does server support them? If yes, why can't you add server's mentions support for channels? And if not, why they are not buggy?

**Comment by john-preston** [comment]
@Senderman Yes, mentions are enabled in groups and disabled in channels. I think server side developers think this is a correct way of handling mentions.
