### ISSUE TITLE
Option to show Chat time in 12 Hours (eg: 5:32 PM)

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#447]
This is a simple feature request to have an option (maybe by default) so that chats do not show in a 24 hour format (Military), but instead show in 12 Hour (AM/PM).

**Comment by telegramdesktop** [comment]
I think it should be somehow system-setting dependent, not in Settings.

**Comment by auchri** [comment]
You can get the system time format from QTouch: http://qt-project.org/doc/qt-4.8/qtime.html#toString-2

**Comment by luisalvarado** [comment]
Thanks for the comments, the end result should be the time in the 12 or 24 format. In my particular case for example, I use it in Ubuntu and always see it as 24 hours, while Ubuntu is set to 12 hour format.

**Comment by telegramdesktop** [comment]
Time should be displayed like in system in 0.7.14.dev version, available here: https://desktop.telegram.org/#dev-version-of-telegram-desktop

**Comment by Physicist137** [comment]
Its soo annoying to look at the time, and it is on 12hr format!! I tried everything, nothing did work.
Its OK to have both options, but then, should be on settings, so that one can change. Its even OK to set default as system-like. But again, I think should have an option to change it on settings.
So.. that's is what I suggest. =).

I use Fedora 23. System-setting is 24hr. System displays in 24hr. My system-time-locale is 24hrs.
But telegram displays in 12hr!

**Comment by leovp** [comment]
Is there any progress? I have the same issue: my locale is `en_DK`, and everywhere in my system I only see 24-hour clocks. Even `date +%X` shows "00:02:17". But Telegram insists on using AM/PM.

**Comment by varepsilon** [comment]
I have the same issue. Is there enough support to re-open the bug?

**Comment by buckle2000** [comment]
Same issue here.

**Comment by AmirHosseinKarimi** [comment]
I have same issue too.

**Comment by recolic** [comment]
I have locale `zh_CN.UTF-8` and using Arch Linux. `date +%X` shows `17时49分38秒`(Translate: 17:49:38). However telegram gives `下午5:47`(Translate: 5:47 PM).

**Comment by Rua** [comment]
I have this issue as well. I have the system language set to en_IE, and I get 24 hour time. But in Telegram, I get 12 hour time, which is really annoying. Modifying the menu item for Telegram to override the time language works, but every time Telegram receives an update, it resets the menu item and I get 12 hour time again.

**Comment by d0tfile** [comment]
@recolic, @Rua  if you both are using Linux, check output of `locale`. Is `LC_TIME` set to zh_CN.UTF-8/en_IE.UTF-8?

**Comment by Rua** [comment]
Same for me
```
LANG=en_IE.UTF-8
LANGUAGE=en_IE
LC_CTYPE="en_IE.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME=en_IE.UTF-8
LC_COLLATE="en_IE.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="en_IE.UTF-8"
LC_PAPER=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_ALL=
```

**Comment by d0tfile** [comment]
@recolic, when I launch telegram via `LC_TIME=zh_CN.UTF-8 telegram-desktop` I'm getting 12-hour clock. Seems like locale/qt issue, not just telegram. You can change it to en_GB, for example.

@Rua, that's strange. If I launch `LC_TIME=en_IE.UTF-8 telegram-desktop` telegram shows time in 24-hour clock. Do you have any errors if you start it like me?

Btw, i have Arch Linux 4.14.67-1-lts and Telegram Desktop 1.3.12 (modified PKGBUILD)

**Comment by Rua** [comment]
`telegram-desktop` didn't exist, but it did say that there was a package I could install with that name. I was using the version that is downloaded from the website and run directly without installation. I deleted that and installed the package, and now the time seems to display correctly.

**Comment by FichteFoll** [comment]
When I launch with `LC_TIME=en_IE.UTF-8 telegram-desktop` I get time stamps in the form "8:53 P.M." (note the dots). With my normal default `LC_TIME` of `en_DK.UTF-8` it shows as "8:53 PM" instead.

It almost seems like it *is* locale-aware, but the strftime call (or equivalent) is hardcoded to a locale-aware 12h format.

**Comment by germanfr** [comment]
It should respect system wide settings. I can't configure it to use 24h format.

**Comment by JulyIghor** [comment]
why it is still not fixed?

**Comment by talshorer** [comment]
Relying on locale for the default makes sense, but depriving users of the option to switch to 24H is just dumb.

**Comment by JulyIghor** [comment]
> Relying on locale for the default makes sense, but depriving users of the option to switch to 24H is just dumb.

I would be happy if it work like should. I'm on locale that uses 24H, but Telegram Desktop ignoring it and use 12H instead.

**Comment by recolic** [comment]
@JulyIghor I think there should be an option to allow user overwriting datetime format. It can be an environment variable is an inexperienced user should not modify it.

**Comment by JulyIghor** [comment]
It looks like it is not Telegram's team fault, they just using QLocale::system() function from Qt SDK 5.6
But Qt SDK 5.6 is old and QLocale::system() won't work correctly on latest OS.
Any way, if they keep app updated, they responsible to keep it compatible with all supported OSs.

**Comment by andpol5** [comment]
Still no ability to show 24hr time in the latest Linux client.

**Comment by Rua** [comment]
Still having the same issue as well. Is there any news on this?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1920

**Comment by sergiev** [comment]
I face the same problem on latest 1.8 and 1.9beta versions.

**Comment by xahon** [comment]
On ubuntu I use 24-hour format, but telegram still uses 12

**Comment by alabotski** [comment]
Mint 19. The same error =

**Comment by ky0n** [comment]
have this issue too on arch linux
