### ISSUE TITLE
Feature request: chats with disabled notifications should not come up in the list

### ISSUE THREAD

**Issue by VoittajaTomi** [telegramdesktop/tdesktop#4472]
It would be nice option to have, that the chats you disabled notifications for would not come on top of the list, because sometimes you want to ignore them for a while.

**Comment by ThigSchuch** [comment]
Type "workmode" on Telegram Settings

**Comment by electricessence** [comment]
@ThigSchuch workmode?  In settings?  In the desktop app?  Not seeing this.

**Comment by stek29** [comment]
@electricessence *type*

**Comment by VoittajaTomi** [comment]
Thank you for this feature! I can close this now. Do you know if the mobile client has a similar feature.....?

**Comment by stek29** [comment]
@VoittajaTomi No, it doesn't.

**Comment by VoittajaTomi** [comment]
Thank you @stek29 
Great feature, I wonder why it is not shown in the settings.

**Comment by electricessence** [comment]
@stek29  I'm not seeing what you're talking about.  I don't have a way to type "workmode" in settings.
What I have is a setting for "include muted chats in unread count".

**Comment by d0tfile** [comment]
@electricessence just open settings and type `workmode`, not inside any input/textbox.

**Comment by electricessence** [comment]
@d0tfile whoaaaa....   That was weird!  What does this do?
