### ISSUE TITLE
Emoji Replacement and Emoji Autocomplete are the same option, despite being two different things

### ISSUE THREAD

**Issue by doktormerlin** [telegramdesktop/tdesktop#4478]
### Steps to reproduce
1. Disable Emoji Replacement in the settings
2. Try to type something with Emoji autocomplete

### Expected behaviour
The autocomplete functionality should still work.

### Actual behaviour
The emoji autocomplete functionality gets disabled.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.2.10 Alpha

**Comment by auchri** [comment]
#4114
