### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by VBelozyorov** [telegramdesktop/tdesktop#448]
Application is broken after one of updates since 23.01.2015. 
I got Segmentation fault while trying to start x64 app. 

```
OpenSUSE 13.1 x64
Linux 3.11.10-25-desktop
KDE 4.11.5
```
If you need more info about system, please specify what kind of.

Update: I've downloaded x86 version of tdesktop and it works now, seems problem really in x64 build.

Thank you.

**Comment by gregoaplweb** [comment]
I have the same problem in Ubuntu 14.04 with kernel Linux 3.13.0-24-generic
But, as you say, the x86 version works fine.

**Comment by racacere** [comment]
Same problem in Fedora 20 x86-64.
Linux 3.17.8-200.fc20.x86_64
Gnome 3.12.

**Comment by ezdev128** [comment]
Same for Linux Mint (debian edition), LMDE MATE

**Comment by gregoaplweb** [comment]
Telegram sends me the solution. You need to install the libappindicator1 package.
In Ubuntu based distros, type: sudo apt-get install libappindicator1
In Fedora type:  sudo yum install libappindicator1

**Comment by ezdev128** [comment]
It is doesn't works to me. However libappindicator is already installed:

# dpkg -l | grep ^ii | grep indicator
ii  libappindicator-dev                          0.4.92-2                         amd64        allow applications to export a menu into the panel -- development
ii  libappindicator1                             0.4.92-2                         amd64        allow applications to export a menu into the panel
ii  libindicator3-7                              0.5.0-2                          amd64        panel indicator applet - shared library
ii  libindicator7                                0.5.0-2                          amd64        panel indicator applet - shared library

**Comment by guzmanlopez** [comment]
Hi, I had the same problem as @ezdev128. I'm on Linux Mint Debian Edition. I have installed libappindicator1 as @gregoaplweb said but it doesn't work for me too. 

Any help would be appreciated!

**Comment by racacere** [comment]
In fedora: sudo yum install libappindicator*
this solve the problem.

Greetings

**Comment by guzmanlopez** [comment]
Now Telegram 0.79 works for me on LMDE. 
I installed libappindicator1, libappindicator3-dev, libappindicator0.1-cil-dev, libappindicator3-1 and libappindicator0.1-cil.

**Comment by ezdev128** [comment]
Found the missed lib: libappindicator3-1

After: aptitude install libappindicator3-1
an app starts

**Comment by eltioemil** [comment]
Also had this problem in LMDE, I installed libappindicator3-1 and it works fine now.

Thank you guys.

**Comment by telegramdesktop** [comment]
Please try 0.7.10 version, it should not crash anymore.

**Comment by flyboy14** [comment]
Crashes with serfault on arch linux with 3.19.1 kernel.
App version is 0.7.17

**Comment by hnuzhoulin** [comment]
version 0.8.13 work well

**Comment by elisaado** [comment]
Arch Linux,
Gnome.

Now again, just updated Telegram Desktop

**Comment by hvinayan** [comment]
Arch Linux.
i3wm
Same issue again.

**Comment by auchri** [comment]
Follow these steps: https://github.com/telegramdesktop/tdesktop/issues/3053#issuecomment-281582775
