### ISSUE TITLE
Telegram crashes while it is scrolling up between messages 

### ISSUE THREAD

**Issue by David256** [telegramdesktop/tdesktop#4482]
### Steps to reproduce
1. Click in the replied message to scroll up
2. Got crashed telegram

### Expected behaviour
Get auto scroll normally up browsing through the messages

### Actual behaviour
Telegram crashes

### Configuration
**Operating system:** Debian GNU/Linux testing (buster) x86_64

**Version of Telegram Desktop:** 1.2.10 alpha

**Comment by john-preston** [comment]
@David256 Can you please send the crash report when relaunching the app and post "Your Report Tag" from the send report window here.

**Comment by David256** [comment]
In debug mode, `./TelegramDesktop/DebugLogs` is empty and no way is showed any messages except `aborted` in stderr

**Comment by stek29** [comment]
Doesn't it show "TDesktop crashed" window on next start after crash?

**Comment by john-preston** [comment]
@David256 Please check the new 1.2.11 alpha version.

**Comment by David256** [comment]
@stek29, not.
@john-preston, I am at 1.2.11 now and no changes of behavior.
I am going to test in other OS to see

**Comment by john-preston** [comment]
@David256 No need, I see huge amounts of those crash reports in 1.2.11 as well :( I hope it was fixed, but it still isn't.

I still hope to deploy a fix in 1.2.12 later today (or tomorrow morning).

**Comment by john-preston** [comment]
@David256 Please check out 1.2.12 alpha version. I hope it was fixed.

**Comment by David256** [comment]
Oh great!
