### ISSUE TITLE
Inconsistent album creation by pasting copied images from web-browser

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#4483]
### Steps to reproduce
1. Open [this](https://www.pexels.com/search/nature) URL 
2. Copy and paste first image using "Copy image" option in Chrome browser
3. Try with another image 

### Expected behaviour
An album should be created and you can continue adding images (up to 10) to send them at once

### Actual behaviour
Nothing happens when you try to paste 2nd image and so on. Please note it works most of times fine with Firefox (though I'm not sure it works there 100% of time), but doesn't work in Chrome.

### Configuration
**Operating system:** Windows 10 LTSB (2015)
**Version of Telegram Desktop:** 1.2.8 - 1.2.10 alpha

**Comment by john-preston** [comment]
@MasterGroosha I see, thanks.
