### ISSUE TITLE
Build a feature to change ownership, or claim/create ownership, to a group.

### ISSUE THREAD

**Issue by kstorvik** [telegramdesktop/tdesktop#4484]
### Steps to reproduce
1. To make Telegram useful in a serious organisation there is the need to add a feature that makes it possible to change owner (creator), for excample if the owner (creator) is planning to leave.
Or when a owner (creator) for some reason or another ceases to exist, and Groups and Channels become orphaned. there must be the possibility for one of the other members of the Group to take ownership to the Group.
2.  
3.  

### Expected behaviour
Tell us what should happen
 .
### Actual behaviour
Tell us what happens instead
 
### Configuration
**Operating system:**
 
**Version of Telegram Desktop:**
 
**Used theme**:
 
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
API issue, sorry.

**Comment by kstorvik** [comment]
Hi! :)



Why are you closing my issue, even if it is an API issue (partly at least)?


After I got your response, I looked into issues labelled API, and there are already at least one open issue that touches part of what I asked.


In #4011 user morelaz want to leave group/channel that he himself created without deleting it. This issue is left open, so what is the difference between his and mine?

 

Lastly, it kind of would be helpful if the person whom closes an issue would care to explain where an issue, in my case apparently (partly at least) an API issue should be reported, if not here.

 

Regards,
Knut

**Comment by kstorvik** [comment]
Please reopen this issue.

--- Knut

**Comment by auchri** [comment]
This repo is for **Telegram Desktop** only, not for things regarding the api.

![image](https://user-images.githubusercontent.com/5092164/37242559-c93e68d4-246b-11e8-95ab-da27aac2482e.png)

**Comment by kstorvik** [comment]
I kind of got that, but then please explain where i can post an API related issue like this.
BTW i would think that what I am proposing would be of great value to a lot of other users of Telegram too. If the owners/developers of Telegram want to get serious organisations to use Telegram, then there have to be some way for a creator/owner to transfere ownership, and for other users in a group/channel to claim ownership to a orphaned group/channel, otherwise Telegram is of no use to people other than mere personal use.
I represent a national chapter of a international NGO and we have used Telegram, but ar now butting up against the very impassible obstacle of passing ownership of Groups and Channels to the incoming Board of Directors. If this is not solved, we have to find another tool than Telegram.

**Comment by john-preston** [comment]
@kstorvik Unfortunately there is no public issue tracker for the Telegram project as a whole. You can contact Telegram via in-app support or on twitter.com/telegram. This repository (and issues here) can deal only with something related specifically to Telegram Desktop.

**Comment by stek29** [comment]
@kstorvik #4011 is open because Telegram API does allow creators to ""leave"" without deleting, but TDesktop doesn't support it yet.

**Comment by stek29** [comment]
@kstorvik btw, what Telegram usually recommends in such cases is creation of new group.
But, theoretically, support can help you to get ownership transferred, but don't quote me on that.

**Comment by kstorvik** [comment]
@stek29 If a creator leaves a group what is supposed to happen to the group then? Is it possible for others to assume the creator/owner role? It makes little sense to be able to leave, just to have to watch the group die, does it not?

**Comment by john-preston** [comment]
@kstorvik He can give some admin full list of privileges and then leave.

**Comment by kstorvik** [comment]
When will TDesktop support this feature, any plans or maybe a guess? :-)
And what about the multiple account feature of the Android Version, any plans to implement that in TDesktop?

**Comment by RememberTheAir** [comment]
> When will TDesktop support this feature, any plans or maybe a guess? :-)

@kstorvik Telegram Desktop already lets you manage admins permissions.

What you have to do in order to "change the ownership" of a group:
- before the real owner leaves:
  - decide who should be the new "owner"
  - demote **all** the admins
  - promote a new admin (the choosen one) with all the available permissions granted (the real owner can leave now)
- the "new owner" (the admin with full power) should now promote all the previously demoted admins again

In this way you have an admin which is hierarchically above all the other admins, and can do almost everything a real owner can (beside changing the chat username, converting it to private/public, or delete the chat)

This is the only way to do that, at the moment. Not a real ownership change, but covers most of the needs

Note that if the real owner joins again, he will still have his powers

> And what about the multiple account feature of the Android Version, any plans to implement that in TDesktop?

#4261, still open, so maybe there's a hope. For now you can use multiple portable TDesktop if you are using Windows

**Comment by Giszmo** [comment]
What's the status of this? Still not possible to change owner?

**Comment by RememberTheAir** [comment]
@Giszmo it's now possible since version 1.7.9

**Comment by SmartManoj** [comment]
[But 44 issues with the label 'api issue' are still open](https://github.com/telegramdesktop/tdesktop/labels/api%20issue)
