### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by yuyaryshev** [telegramdesktop/tdesktop#4486]
Can you add a switch "Silent mode" to disable all notifications from all users for specified period of time (say 8 hours), except for specific users I whitelisted? 

If even it's hard to save this whitelist to server this feature is still very usefull to me.

**Comment by d0tfile** [comment]
Maybe add customization to `workmode`?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/151#issuecomment-63627345

**Comment by stek29** [comment]
@Aokromes this issue also requests whitelist and doesn't request scheduled time interval :)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/151 updated to add whitelist and scheduled thing can be optional :P
