### ISSUE TITLE
Can't send file

### ISSUE THREAD

**Issue by SilentImp** [telegramdesktop/tdesktop#4487]
### Steps to reproduce
1. Try to send file. 
2. Infinite upload

### Expected behaviour
File should be transfered to your telegram contact

### Actual behaviour
Infinite upload. Contact never receive file.

### Configuration
**Operating system:** OSX 10.13.3

**Version of Telegram Desktop:** 3.7.5.115423

**Used theme**: Day Classic

**Comment by stek29** [comment]
> Version of Telegram Desktop: 3.7.5.115423
> Used theme: Day Classic

That's not TDesktop.

You can download TDesktop at https://desktop.telegram.org.
You can report bugs in app you're using now at https://t.me/macswift or https://github.com/overtake/TelegramSwift
