### ISSUE TITLE
Wrong OutDir in Telegram.vcxproj

### ISSUE THREAD

**Issue by nevilad** [telegramdesktop/tdesktop#4490]
### Steps to reproduce
1. Do all the steps from telegram build instructions till Telegram.vcxproj is created.
2. Open Telegram.vcxproj in any text viewer and find OutDir declaration.

### Expected behaviour
OutDir should depend on Configuration, ex:
..\out\$(Configuration)\

### Actual behaviour
OutDir does not depend on Configuration:
C:\TBuild\tdesktop\out\Debug\
All other projects (Updater etc) are correct.

### Configuration
**Operating system:** Windows 10 En

</details>

**Comment by john-preston** [comment]
@nevilad The project is generated by GYP, I'm not sure where to fix that :(

**Comment by nevilad** [comment]
All other projects (codegen_emoji, codegen_lang, codegen_numbers, codegen_style, crl, Packer, Updater) have correct OutDir value. They are too generated by gyp. Is it not possible to build telegram.vcxproj similarly?

**Comment by 23rd** [comment]
@nevilad @stek29 Seems like everything is okay for now.
