### ISSUE TITLE
Other programs start to play music/sounds faster, when TelegramDesktop is started

### ISSUE THREAD

**Issue by Paraidomat** [telegramdesktop/tdesktop#4492]
### Steps to reproduce
1. Start Spotify and play music or watch a YouTube video using chrome. Everything is good.
2. Start Telegram. Suddenly the music or the video is played a little faster.
3. Close Telegram completely. Music stays fast.
4. Restart Spotify or reload the YouTube-Video Page. Everything back to normal.
5. Goto: 2. ;-)

### Expected behaviour
I expect a normal coexistence between these programs.

### Actual behaviour
See "Steps to reproduce"

### Configuration

**Operating system:**
Ubuntu Budgie
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
NAME="Ubuntu"
```

**Version of Telegram Desktop:**
[v1.2.6](https://desktop.telegram.org/changelog#v-1-2-6-30-12-17)

**Used theme**:
Not sure if it's relevant, but I think I only activated night mode and that's it.

**Comment by AlfTetzlaff** [comment]
I cannot reproduce this behaviour and haven't noticed anything alike in the past 1.5 years.

Telegram 1.5.11
Spotify 1.1.10.546.ge08ef575
Debian 10 4.19 .

**Comment by ntonnaett** [comment]
I had this behavior and fixed it with setting the default-sample-rate variable in /etc/pulse/daemon.conf to 48000. I have no clue which part of the stack is to blame here. I experienced this behavior in another program but forgot which one.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1548
