### ISSUE TITLE
Group is going crazy - I'm in, I'm out, members count is wrong etc.

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#4497]
### Steps to reproduce
1. A friend created a group with a joining link.
2. Some people joined.
3. The group became crazy.
4. The friend upgraded to super group and gave a public name.
5. Still crazy.

### Expected behaviour
The group would be created and we could use it normally.

### Actual behaviour
The group is changing every second about whether or not someone is in the group, the number of members. One second I'm inside the group and the other moment it suggest me to join again.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.2.12

**Used theme**: Default

![image](https://user-images.githubusercontent.com/3811594/37351727-62e3002e-26e4-11e8-87de-d6f5f3837149.png)

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by arieljannai** [comment]
Okay, it's crazy on all platforms. So it's a general problem which I have no idea how to deal with, or whom to report 🤷

**Comment by arieljannai** [comment]
I know it's off-topic here - but how can I report general issues on Telegram, regarding the platform?

I found some over the time: some are just aesthetic and others are some kind of malfunction or bugs.


The issue can be closed as not related only to telegram desktop. I'll let you guys close it for the tracking, if relevant.

**Comment by Aokromes** [comment]
you can close it youself :)
