### ISSUE TITLE
IP address is not updated when it is changed

### ISSUE THREAD

**Issue by Tobishua** [telegramdesktop/tdesktop#4499]
### Steps to reproduce
1. Login to account 
2. Check IP address for current session
3. Change IP address e.g. connect to VPN
4. IP address for the current session will not be updated

### Expected behaviour
The IP address must be updated when the IP address of the connection changes.

### Actual behaviour
IP address is not updated when it is changed

### Configuration
**Operating system:** Linux Ubuntu 16.04.3 LTS

**Version of Telegram Desktop:** 1.2.6

**Comment by stek29** [comment]
I don't think it's managed by client side

**Comment by Tobishua** [comment]
@stek29 hm... You're totally right. Sorry for that issue.
