### ISSUE TITLE
Support formatted Chinese text

### ISSUE THREAD

**Issue by L9m** [telegramdesktop/tdesktop#4502]
### Steps to reproduce
1. Type some formatted Chinese text (eg. `**加粗**`)
2. Send it.
3. It is not working

### Expected behaviour
It will become formatted text.

### Actual behaviour
Not working, just like unformatted text

### Configuration
```
         Operating System: Windows 10 Enterprise 64-bit (10.0, Build 16299) (16299.rs3_release.170928-1534)
                 Language: English (Regional Setting: English)
      System Manufacturer: ASUS
             System Model: All Series
                     BIOS: BIOS Date: 06/02/15 16:44:49 Ver: 04.03
                Processor: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 CPUs), ~3.3GHz
```

**Version of Telegram Desktop:**
Version 1.2.6

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
#1917 I think

**Comment by L9m** [comment]
thanks for your response
