### ISSUE TITLE
Group Avatar bug

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#4503]
### Steps to reproduce
1. Open group chat
2. Go to one's profile (I did it with "Forwarded from" message)
3. Minimize and resize window again (see attached gif)

### Actual behaviour
Group's avatar overlaps group name and stays in header even if you switch chat.

### Configuration
**Operating system:** Windows 7
**Version of Telegram Desktop:** 1.2.12 alpha

P.S. I know this GIF is awful, but at least it clearly shows the bug.

![2018-03-15 14-55-50](https://user-images.githubusercontent.com/2780044/37461982-5d6fb5be-2861-11e8-9e9a-36315c4cb12d.gif)

**Comment by john-preston** [comment]
@MasterGroosha Thanks!
