### ISSUE TITLE
GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.42.1/./gobject/gsignal.c:2461: signal 'child-added' is invalid for instance '0x2dcf110' of type 'GtkMenu'

### ISSUE THREAD

**Issue by shirishag75** [telegramdesktop/tdesktop#451]
Hi all, 
I get the following error each time I run telegram on the desktop. 

    ~/games/telegram$ ./Telegram
    /games/telegram$ FT_New_Face failed with index 0 : 1
    FT_New_Face failed with index 0 : 1
    FT_New_Face failed with index 0 : 1
    FT_New_Face failed with index 0 : 1
    FT_New_Face failed with index 0 : 1
    
    (Telegram:13693): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.42.1/./gobject/gsignal.c:2461: signal 'child-added' is invalid for instance '0x2dcf110' of type 'GtkMenu'    

Looking forward for a fix.

**Comment by ezdev128** [comment]
+1
