### ISSUE TITLE
Markdown `code` is broken if contains URLs with subdirectories

### ISSUE THREAD

**Issue by delivrance** [telegramdesktop/tdesktop#4512]
### Steps to reproduce
1. Send `` `pip3 install -U git+https://github.com/pyrogram/pyrogram` `` (notice the backticks).

### Expected behaviour
A `correctly formatted` message.

### Actual behaviour
The message is not formatted. I have to use the Android app to send such messages.

### Configuration
**Operating system:** Tested with Linux 64 bit and Windows

**Version of Telegram Desktop:** 1.2.6

**Used theme**: Stock

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by delivrance** [comment]
It might also be useful to report that two consecutive hyphens (--) get *sometimes* replaced by an em dash (—) and is quite annoying, especially when you want to preserve them when sending `--inline --fixed-width --code`.

**Comment by stek29** [comment]
Can't you just place a space before ``` ` ``` ?
Also, ``` ` ``` is sometimes used as punctuation mark, that's why there's filtering on if it should be parsed as code or left as is.

**Comment by stek29** [comment]
@delivrance speaking of two hyphens -- see #522

**Comment by Lonami** [comment]
> Can't you just place a space before \` ?

But then you fix that and your `--` flags are broken. So you go and fix the \` but the `-` remains `—`. So you fix `—` for `--` but then forget about the \`. So you put the space and also fix the `—` replacement and *finally* you can send your message as intended!

**Comment by delivrance** [comment]
This has become so annoying up to the point people are literally binary patching the executables just to get rid of the replacements.

**Comment by stek29** [comment]
Agreed -- you can just use rmb formatting now.
