### ISSUE TITLE
tray icon click always shows menu, linux.

### ISSUE THREAD

**Issue by atenrok** [telegramdesktop/tdesktop#452]
version 0.7.9
fedora 20
XFCE

RMB-click o LMB-click produces the same result -- menu (open..., minimize.., quit). I was told LMB-click opens main window in MS Windows, probably the same is expected in linux.

**Comment by aseredenko** [comment]
feature, not bug :)

**Comment by atenrok** [comment]
In this case I want to request a feature: main window pop-up on LMB-click

**Comment by chelipf** [comment]
Hi everyone. I think the tray icon behaivor should be like skype, ktelepathy, etc.

-Left click opens window (the first time).
-Left click minimize window (the second time).
-Right click opens the menu.

Regards.

**Comment by telegramdesktop** [comment]
Sorry, but now tray icon is done through libappindicator (the preferred api in ubuntu for tray icons), and it only allows to set menu for the icon, no click handling. Maybe with moving to Qt 5.4 there will be some different possibilities for tray icons, including such complex behaviour, but now only libappindicator api is used.

**Comment by tushar-suresh** [comment]
This is the default behaviour for all indicator applets in Ubuntu. Left-click opens the menu. I feel it's better to keep it that way and not confuse the user.

**Comment by telegramdesktop** [comment]
Now tray icons should work through libappindicator in Unity environments and through Qt implementation otherwise (with show/hide of window by left click or other "activate" event). Please check.

**Comment by hasinasi** [comment]
I also would like to open the main application window with a single left click. I am just coming to Unity from KDE, and this feels like much more cumbersome having to first open the menu every single time...

**Comment by Peaker** [comment]
I'm using xfce4, and clicking the tray icon still opens the menu (0.9.49), which is a frustratingly slow way to reach the telegram window.

**Comment by HolyBlackCat** [comment]
I had this problem too on Xubuntu, but now it appears to be fixed.

**Comment by atenrok** [comment]
Just tried on Fedora 30, XFCE --  still the same, both right and left
clicks open a menu
