### ISSUE TITLE
Telegram refuses to start (kubuntu 18.04)

### ISSUE THREAD

**Issue by derEremit** [telegramdesktop/tdesktop#4520]
### Steps to reproduce
1.
open krunner 
2. 
type telegram
3. 
start it

### Expected behaviour
telegram should start

### Actual behaviour
It shows telegram for a split-second in task manager, then disappears

### Configuration
**Operating system:**
kubuntu 18.04

**Version of Telegram Desktop:**
  - telegram-desktop
snap-id:   jpdoHqMd90M39DdH2JSZbeQxipqHtwLo
tracking:  stable
refreshed: 2018-02-09T22:30:48+01:00
installed:   1.2.6                   (54)  99MB -
channels:                                  
  stable:    1.2.6                   (54)  99MB -
  candidate: 1.2.6                   (54)  99MB -
  beta:      1.2.12-alpha            (79)  95MB -
  edge:      1.2.12-alpha+git27ce1f8 (110) 95MB -

output dmesg:
[ 9457.061796] audit: type=1400 audit(1521640620.764:60): apparmor="DENIED" operation="ptrace" profile="snap.telegram-desktop.telegram-desktop" pid=6999 comm="Telegram" requested_mask="trace" denied_mask="trace" peer="snap.telegram-desktop.telegram-desktop"
[ 9461.368779] audit: type=1400 audit(1521640625.072:61): apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/etc/xdg/user-dirs.conf" pid=7021 comm="xdg-user-dirs-u" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[ 9461.379988] audit: type=1400 audit(1521640625.084:62): apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/etc/xdg/QtProject/qtlogging.ini" pid=7003 comm="Telegram" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[ 9461.380090] audit: type=1400 audit(1521640625.084:63): apparmor="DENIED" operation="connect" profile="snap.telegram-desktop.telegram-desktop" pid=7003 comm="Telegram" family="unix" sock_type="stream" protocol=0 requested_mask="send receive connect" denied_mask="send connect" addr=none peer_addr="@/tmp/.X11-unix/X0" peer="unconfined"
[ 9461.380422] audit: type=1400 audit(1521640625.084:64): apparmor="DENIED" operation="ptrace" profile="snap.telegram-desktop.telegram-desktop" pid=7023 comm="Telegram" requested_mask="trace" denied_mask="trace" peer="snap.telegram-desktop.telegram-desktop"

**Comment by derEremit** [comment]
update:
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1756793
fixed it

**Comment by Aokromes** [comment]
If it's ubuntu bug close ticket :)
