### ISSUE TITLE
Windows 10 touch not working

### ISSUE THREAD

**Issue by koningsvh** [telegramdesktop/tdesktop#4521]
### Steps to reproduce
1. Open Telegram
2. Touch screen
3. Nothing happens

### Expected behaviour
The app should respond to touch
### Actual behaviour
The app does not respond to touch

### Configuration
**Operating system: Windows 10**

**Version of Telegram Desktop: 1.2.6**

**Used theme**: default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Aokromes** [comment]
works for me on windows 10.0.16299.309 and tdesktop 1.2.6.

**Comment by koningsvh** [comment]
in tdesktop 1.2.14 it works again!

**Comment by koningsvh** [comment]
in tdesktop 1.2.14 it works again!
