### ISSUE TITLE
No changelog after update

### ISSUE THREAD

**Issue by telekek** [telegramdesktop/tdesktop#4525]
### Steps to reproduce
1. Press "update telegram" if there is new update
2. Telegram will restart
3. But there is no changelog from +42777 (telegram service notifications contact)

### Expected behaviour
I should get changelog from +42777 (telegram service notifications contact). I ask my friend check it and he is get changelog:
<details>

![image](https://user-images.githubusercontent.com/37653178/37758406-86a84154-2dc9-11e8-84a7-174c7021f85f.png)

</details>

### Actual behaviour
I didn't get changelog from +42777 (telegram service notifications contact), but I can see that this contact is appears for  a split second after telegram update and then disappears. 
At the same time I can see the login codes from other devices.
I redownload alpha portable (from telegram.org, 1.2.13), reupdate it to last version 1.2.14 and then i saw changelog, BUT when i restart telegram changelog is disappears.

### Configuration
**Operating system:**
Windows 10 x64 Enterprise LTSB (1607, build 14393.2125)

**Version of Telegram Desktop:**
1.2.14 alpha Portable

**Used theme**:
Default

**Comment by john-preston** [comment]
@telekek Yes, changelog messages are not saved between relaunches in tdesktop 😔

**Comment by MasterGroosha** [comment]
I guess this issue is fixed, @john-preston?

**Comment by john-preston** [comment]
@MasterGroosha It should be, yes.

**Comment by MasterGroosha** [comment]
For some reason in 1.5.8 build the problem appeared again.
