### ISSUE TITLE
Telegram is recreating deleted start menu shortcut icon after every launch

### ISSUE THREAD

**Issue by telekek** [telegramdesktop/tdesktop#4526]
### Steps to reproduce
1. Delete the telegram shortcut from windows start menu
2. Launch/relaunch telegram
3. Telegram shortcut is appears in start menu again

### Expected behaviour
After deleting telegram shortcut in windows start menu it shouldn't be appeared again

### Actual behaviour
Shortcut is appeared instantly after opening the telegram on a fresh program startup after the initial deletion of the shortcut

### Configuration
**Operating system:**
Windows 10 x64 Enterprise LTSB (1607, build 14393.2125)

**Version of Telegram Desktop:**
1.2.14 alpha Portable (and many versions before)

**Used theme**:
Default

**Comment by john-preston** [comment]
@telekek Currently it is required for the windows toast notifications to work :( There was an idea to disable this shortcut creation if not windows toast notifications are used (but custom tdesktop notifications), but if windows toasts are used there is no way to show them without that shortcut, this is a Windows API requirement.
