### ISSUE TITLE
Good use of up & down arrow keys, then selecting via space button.

### ISSUE THREAD

**Issue by Ornataweaver** [telegramdesktop/tdesktop#4527]
on Mac (and maybe other OSs) when sharing a message I can type the name of people I want to send the data to, but I can't use up & down arrow keys to focus on them, and select them via space.
I suggest command + return for sending after contacts are chosen.

**Comment by john-preston** [comment]
@Ornataweaver It should work in Telegram Desktop (https://desktop.telegram.org).

Perhaps you're trying another app for macOS, like https://macos.telegram.org?

**Comment by Ornataweaver** [comment]
I downloaded both, yes, you are correct.
Where is their repo? How can I move this issue there?

**Comment by Ornataweaver** [comment]
Yet my solution is different than what happens in Telegram Desktop.
Hitting space doesn't select my contacts. I have to manually choose them one by one via mouse. It's tedious.
Give it a thought.

**Comment by Ornataweaver** [comment]
found it: https://github.com/overtake/TelegramSwift

**Comment by Ornataweaver** [comment]
https://github.com/overtake/TelegramSwift/issues/134

**Comment by Ornataweaver** [comment]
Yet my solution is different than what happens in Telegram Desktop.
Hitting space doesn't select my contacts. I have to manually choose them one by one via mouse. It's tedious.
Give it a thought.
