### ISSUE TITLE
Commonly used smileys end up being autocompleted

### ISSUE THREAD

**Issue by ojura** [telegramdesktop/tdesktop#4528]
Hi, a recent update of Telegram Desktop (1.2.14) started autocompleting commonly used plain text smiley faces such as `:D` or `:P` to `:disappointed` or `:pensive`, which is highly annoying  - if you type `:D` and press enter, you get `:disappointed`. You have to press escape before pressing enter to cancel autocompletion. Can you please remove this?

**Comment by wchristian** [comment]
I wanted to make an issue entitled "typing :D has become really hard" but that title is good too.

I don't think the autocomplete should be removed for those necessarily, but it should be a **suggestion**, not the default thing that happens upon pressing space.

**Comment by ojura** [comment]
Actually, pressing space is not a problem - pressing enter is, when the message ends with the smiley (in that case, you cause the autocomplete to be accepted instead of sending the message).

**Comment by ojura** [comment]
A suggestion lifted from IDEs: ctrl-space is a commonly used shortcut for forcing the autocompletion window to be shown. ":D" and ":P" can be added to a list of exceptions for which the autocompletion window _should not_ be shown. If the user desired autocompletion, they could always force it with a shortcut such as ctrl+space. (Perhaps such a shortcut already exists in the desktop client?)

**Comment by john-preston** [comment]
@ojura Strange, I’ve fixed it to not being shown on :D or :P but I guess I’ve already broke that fix :(

**Comment by Gollam** [comment]
@john-preston IMHO you should also fix it for ":S", it is also a commonly used one.

**Comment by john-preston** [comment]
@Gollam Fix was for no suggestions on colon and single capital letters. And it even was discussed in pull requests and worked.

**Comment by ojura** [comment]
@stek29 a fix is forthcoming?

**Comment by john-preston** [comment]
@ojura Yes, I'll fix this once again. Didn't have time to see what happened yet.

**Comment by N0x1k** [comment]
Can we add another exception for smileys with "nose"? E.g. :-D, :-P, :-S

**Comment by stek29** [comment]
wait, why does `:--------------` get autocompleted as `:a`?..
