### ISSUE TITLE
Package for OS with package management system

### ISSUE THREAD

**Issue by VBelozyorov** [telegramdesktop/tdesktop#453]
Since this app got some external dependencies (libappindicator, for example), looks like now better to distribute it through native package management systems for OS, which use those systems. Isn't it?
Those packages will allow to install all dependencies in right way.

Seems package for mac is already in app store, so I mean linux distros :wink:
If native repos of some systems are updates too slow, you may create your own for `deb` amd `rpm` based systems.

Thank you!

**Comment by ezdev128** [comment]
I'm agree with this too!
Voting for debian ;-)

**Comment by telegramdesktop** [comment]
I'm quite far from Linux way and have no idea how it is working. Right now binary has minimum set of dependencies, working without libappindicator if it is not present in the system, etc. And I'm afraid of increasing the deployment time of new versions through all this different Linux package management systems stuff.

**Comment by nevik** [comment]
@VBelozyorov suggestion: use a precise title for the issue (you can edit it), mentioning that you are particularly talking about packages for linux :)

and for what it's worth, there is [a Telegram PPA](https://launchpad.net/~atareao/+archive/ubuntu/telegram) maintained by the [team of atareao.es](http://www.atareao.es/), which gets weekly updates of tdesktop (if there are new commits).

**Comment by VBelozyorov** [comment]
@nevik I don't know whether correct or not my suggestion about package for Mac. Is it already distributing how it should be in this system?

As I understand, Telegram PPA is somebody's build for Ubuntu. 
In my first post I mean "official" build, but after @telegramdesktop comment I understand, that third party maintainers is the most likely path of packages development in the near future.

**Comment by Trueneo** [comment]
Go on 
https://en.opensuse.org/openSUSE:Build_Service
VLC is multiplatform and uses OBS to update its packages on a lot of distros.

**Comment by nevik** [comment]
@VBelozyorov yes, the PPA is aimed at Ubuntu, but in the end they're just DEB packages, so you can use them on any apt-based Linux, provided you can get the dependencies :)

**Comment by whodafly** [comment]
+1 (Debian and Ubuntu)

**Comment by auchri** [comment]
Duplicate #253

**Comment by liobas777** [comment]
Is there any description, which package mangement system is used for Telegram Windows desktop client? Which files have to be added to the telegram.exe after compilation to get a full working Telegram client? I think that the compiled resources have to be added, but I cant find them in the distributed package.

**Comment by stek29** [comment]
No, Telegram.exe has everything in it.
Or you want to have an alternative update server?
