### ISSUE TITLE
Save GIF doesn't work with preview mp4 links

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#4533]
### Steps to reproduce
1. Send mp4 link, for example https://i.imgur.com/7zn9vRJ.mp4
2. Telegram generates preview with GIF
3. Select 'Save GIF'

### Expected behaviour
GIF should be saved to your GIFs

### Actual behaviour
Nothing happens

### Configuration
**Operating system:** Linux Mint 18.3, Windows 7

**Version of Telegram Desktop:** 1.2.14 alpha

**Used theme**: Any

**Comment by barisdemiroz** [comment]
I am having the exact same issue today.
