### ISSUE TITLE
Annoying emoji auto completion at end of message

### ISSUE THREAD

**Issue by jonashaag** [telegramdesktop/tdesktop#4535]
### Steps to reproduce
1. Type "a :D"
2. Press Return

### Expected behaviour
A message "a :D" is sent

### Actual behaviour
:D gets autocompleted to crying emoji

This is a regression from the previous version.

### Configuration
**Operating system:** macOS

**Version of Telegram Desktop:** 1.2.14

**Comment by seth-rah** [comment]
Was your replace emoji turned on in the previous version?

![image](https://user-images.githubusercontent.com/2222634/37825063-5395db22-2e97-11e8-837f-1e0ac4ba22f3.png)

**Comment by jonashaag** [comment]
Yes. And it's still turned on. The problem goes away if I turn it off, but it comes back if I turn it on again. So probably nothing to do with migrating settings.

**Comment by Soyaro666** [comment]
according to #4528 that's a known bug and a fix is coming. I came here for the same reason ;-)
