### ISSUE TITLE
memory leaks at linux desktop after last update

### ISSUE THREAD

**Issue by 221V** [telegramdesktop/tdesktop#4536]
раньше память держалась сутками на уровне 100-150Мб
сейчас, после последнего обновления -- пол-часа-час и 400-500Мб+ оперативки скушано как с куста

**Comment by 221V** [comment]
new update not solved the problem !
please, help!

как теперь пользоваться телеграмом на слабых старых компютерах?

**Comment by Rutori** [comment]
you can use telegram web until problem solves

**Comment by 221V** [comment]
web sucks because browsers became so more fat and fat((

**Comment by 221V** [comment]
сейчас немного лучше -- протекает до 300 Мб, не до 500Мб

**Comment by auchri** [comment]
@221V Write english please

**Comment by StSav012** [comment]
I can confirm the problem. After some two weeks on Linux, the app was consuming some 84 GB of virtual memory!! As my system was rendered almost unresponsive, I failed to take a note of the exact value. Nonetheless, the memory leak persists. Moreover, I suspect the same issue on Windows as well, for the latest Telegram silently crashes once a day or two there.
@auchri, I can translate some of his posts. Unfortunately, they are not informative: just the amounts of memory consumed by the application. As you can see, the numbers remain virtually the same.
