### ISSUE TITLE
Frequently used emojis doesn't update with keyboard emojis like :grin:

### ISSUE THREAD

**Issue by ahmadalli** [telegramdesktop/tdesktop#4539]
### Steps to reproduce
- Use an emoji for a while by using the keyboard panel

### Expected behavior
It should appear on the frequent emoji panel after some time.

### Actual behavior
It doesn't :)

### Configuration
**Operating system:** Windows 10 1709

**Version of Telegram Desktop:** 1.2.14

**Comment by john-preston** [comment]
It was even done, but was done with bugs :/ If you select an emoji from a list it will be incremented in the recent list.

**Comment by ahmadalli** [comment]
so now if I type and enter (not selecting by mouse) it will be eventually added to the recent?

**Comment by john-preston** [comment]
@ahmadalli Selecting by enter will add to recent. If you just type this colon-grin-colon and send it, without selecting anything from the list, it won't be added.

**Comment by ahmadalli** [comment]
hmmm, great :-D
can't the second one be done too? 😁

**Comment by ahmadalli** [comment]
there seems to be another problem. I'm using `:wave:` periodically for a while but it doesn't show up in the list while I've never used the emojis at the end of list.
