### ISSUE TITLE
Read message receipt in group chats

### ISSUE THREAD

**Issue by zoulja** [telegramdesktop/tdesktop#4540]
It would be really nice if we could understand who exactly in group chat have read the message (so I could push someone and require to respond)
Currently it's not possible, we only see some general "Read" markers(I can't even understand its logic)
Here is example of implementation in Rocket.Chat
[https://hsto.org/webt/7v/sd/0e/7vsd0eyrazuwqrlslrmrlesawkq.png](url)

**Comment by stek29** [comment]
@zoulja Sorry, didn't mean to mark this as duplicate (and didn't mean to assign and unassign myself)

But, it actually was asked before (#4279, #2976)
