### ISSUE TITLE
Drag & Drop not working

### ISSUE THREAD

**Issue by gimmeitorilltell** [telegramdesktop/tdesktop#4541]
### Steps to reproduce
1. Open Telegram
2. Pick any file
3. Drag and drop in TG

### Expected behaviour
The file should be uploaded to the chat

### Actual behaviour
Could not upload empty file message appears
### Configuration
**Operating system:**
Linux Mint 18.3

**Version of Telegram Desktop:**
1.2.14
**Used theme**:
Any theme
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)
This only happens if I install TG thru my software manager. When I download from 
your website and install manually it works as it should.

</details>

**Comment by stek29** [comment]
Are there any non-ascii chars in filename/path to it?

**Comment by Aokromes** [comment]
At least on windows works. I need to check on some linux flavor.

**Comment by gimmeitorilltell** [comment]
I am not very good yet at tracking down any bugs. I just downloaded the program from the website & double click the file to run TG and everything works as it should. Sorry if I can get more time I'll try tracking down some more issues.

**Comment by stek29** [comment]
What exactly are you drag'n'dropping?
Once again, are there any non-ascii (non Latin/Digits/some symbols but some other language?) in path to file you're trying to send?

**Comment by pesfahanian** [comment]
Same problem here on Ubuntu 18.0.4.
