### ISSUE TITLE
Call-end button is not exist

### ISSUE THREAD

**Issue by jsonguard** [telegramdesktop/tdesktop#4542]
### Steps to reproduce
1. Open anyone dialog
2. Press to call-button for start calling
3. Try to close or minimize call-window

### Expected behaviour
Calling to user and press to close or minimize button and don`t see call-window

### Actual behaviour
Call-window is not closing and not minimizing, because button does not exist. **This is visible above all windows, closes half of the screen on any virtual desktop** until a call is not finished

### Configuration
Ubuntu 16.04 LTS

**Version of Telegram Desktop:**
1.2.15
**Used theme**:
Any theme

**Comment by Aokromes** [comment]
@jsonguard Try on 1.3.14 :)

**Comment by Aokromes** [comment]
over a year without answer, closing.
