### ISSUE TITLE
"Sorry, you can pin no more than 5 chats to the top" bug

### ISSUE THREAD

**Issue by lorenzolucioni** [telegramdesktop/tdesktop#4545]
### Steps to reproduce
I have pinned 5 chats in the past, and then removed 3 of them. Now I'm not able to pin more.
This issue ( https://github.com/telegramdesktop/tdesktop/issues/3001 )  has not yet been solved, despite what you told in the issue itself :-(

### Configuration
Ubuntu 17.10
Telegram 1.2.15

**Comment by john-preston** [comment]
@lorenzolucioni If you try to reorder pinned chats (drag the one below the other so that order is changed) and then try to pin exactly five — will it work?
