### ISSUE TITLE
VS 2017 v.15.6.4 build error - cannot open file "common.lib"

### ISSUE THREAD

**Issue by raimand13** [telegramdesktop/tdesktop#4548]
Hi. i get this error every time i try to build Telegram project.
![image](https://user-images.githubusercontent.com/14857040/38095426-b53bd4c4-3385-11e8-9db3-e60b24cbea52.png)

**Comment by john-preston** [comment]
@raimand13 Perhaps some folders are not configured as in instructions?

I can confirm that instructions work, because I was configuring a new workplace a couple of days ago with fresh Windows 10 + fresh Visual Studio Community 2017 15.6.4 by instructions from this repository and everything worked.

I've updated some dependency repositories (zlib, opus, lzma) to use the latest Windows SDK in the project files, but this doesn't look like your problem.

**Comment by raimand13** [comment]
i update and compile all repository again. i get this error now.
*********************************
D:\Sources\telegram_cloned\Libraries\qt5_6_2\qtbase>git apply D:/Sources/telegram_cloned/tdesktop/Telegram/Patches/qtbase_5_6_2.diff
error: patch failed: mkspecs/common/msvc-desktop.conf:30
error: mkspecs/common/msvc-desktop.conf: patch does not apply
error: patch failed: src/corelib/io/qfsfileengine_win.cpp:427
error: src/corelib/io/qfsfileengine_win.cpp: patch does not apply
error: patch failed: src/corelib/tools/qunicodetables.cpp:6227
error: src/corelib/tools/qunicodetables.cpp: patch does not apply
error: patch failed: src/gui/kernel/qhighdpiscaling.cpp:51
error: src/gui/kernel/qhighdpiscaling.cpp: patch does not apply
error: patch failed: src/gui/kernel/qplatformdialoghelper.h:386
error: src/gui/kernel/qplatformdialoghelper.h: patch does not apply
error: patch failed: src/gui/kernel/qwindow.cpp:2525
error: src/gui/kernel/qwindow.cpp: patch does not apply
error: patch failed: src/gui/painting/qpaintengine_p.h:80
error: src/gui/painting/qpaintengine_p.h: patch does not apply
error: patch failed: src/gui/text/qtextengine_p.h:283
error: src/gui/text/qtextengine_p.h: patch does not apply
error: patch failed: src/gui/text/qtextlayout.cpp:694
error: src/gui/text/qtextlayout.cpp: patch does not apply
error: patch failed: src/gui/text/qtextlayout.h:196
error: src/gui/text/qtextlayout.h: patch does not apply
error: patch failed: src/platformsupport/fontdatabases/basic/qbasicfontdatabase.cpp:172
error: src/platformsupport/fontdatabases/basic/qbasicfontdatabase.cpp: patch does not apply
error: patch failed: src/platformsupport/fontdatabases/fontconfig/qfontconfigdatabase.cpp:375
error: src/platformsupport/fontdatabases/fontconfig/qfontconfigdatabase.cpp: patch does not apply
error: patch failed: src/platformsupport/fontdatabases/mac/qcoretextfontdatabase.mm:265
error: src/platformsupport/fontdatabases/mac/qcoretextfontdatabase.mm: patch does not apply
error: patch failed: src/plugins/platforminputcontexts/compose/compose.pro:15
error: src/plugins/platforminputcontexts/compose/compose.pro: patch does not apply
error: patch failed: src/plugins/platforminputcontexts/compose/qcomposeplatforminputcontext.cpp:232
error: src/plugins/platforminputcontexts/compose/qcomposeplatforminputcontext.cpp: patch does not apply
error: patch failed: src/plugins/platforminputcontexts/platforminputcontexts.pro:1
error: src/plugins/platforminputcontexts/platforminputcontexts.pro: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qcocoaapplicationdelegate.mm:210
error: src/plugins/platforms/cocoa/qcocoaapplicationdelegate.mm: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qcocoabackingstore.h:64
error: src/plugins/platforms/cocoa/qcocoabackingstore.h: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qcocoabackingstore.mm:38
error: src/plugins/platforms/cocoa/qcocoabackingstore.mm: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qcocoahelpers.mm:546
error: src/plugins/platforms/cocoa/qcocoahelpers.mm: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qcocoakeymapper.mm:384
error: src/plugins/platforms/cocoa/qcocoakeymapper.mm: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qcocoasystemtrayicon.mm:94
error: src/plugins/platforms/cocoa/qcocoasystemtrayicon.mm: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qcocoawindow.mm:141
error: src/plugins/platforms/cocoa/qcocoawindow.mm: patch does not apply
error: patch failed: src/plugins/platforms/cocoa/qnsview.mm:647
error: src/plugins/platforms/cocoa/qnsview.mm: patch does not apply
error: patch failed: src/plugins/platforms/windows/qwindowsdialoghelpers.cpp:716
error: src/plugins/platforms/windows/qwindowsdialoghelpers.cpp: patch does not apply
error: patch failed: src/plugins/platforms/windows/qwindowskeymapper.cpp:1268
error: src/plugins/platforms/windows/qwindowskeymapper.cpp: patch does not apply
error: patch failed: src/plugins/platforms/windows/qwindowsservices.cpp:127
error: src/plugins/platforms/windows/qwindowsservices.cpp: patch does not apply
error: patch failed: src/plugins/platforms/windows/qwindowswindow.cpp:1020
error: src/plugins/platforms/windows/qwindowswindow.cpp: patch does not apply
error: patch failed: src/plugins/platforms/windows/qwindowswindow.h:265
error: src/plugins/platforms/windows/qwindowswindow.h: patch does not apply
error: patch failed: src/plugins/platforms/xcb/qxcbnativeinterface.cpp:79
error: src/plugins/platforms/xcb/qxcbnativeinterface.cpp: patch does not apply
error: patch failed: src/plugins/platforms/xcb/qxcbnativeinterface.h:68
error: src/plugins/platforms/xcb/qxcbnativeinterface.h: patch does not apply
error: patch failed: src/widgets/dialogs/qfiledialog.cpp:1200
error: src/widgets/dialogs/qfiledialog.cpp: patch does not apply
error: patch failed: src/widgets/dialogs/qfiledialog.h:108
error: src/widgets/dialogs/qfiledialog.h: patch does not apply
error: patch failed: src/widgets/dialogs/qfiledialog_p.h:123
error: src/widgets/dialogs/qfiledialog_p.h: patch does not apply
error: patch failed: src/widgets/kernel/qwidget.cpp:5138
error: src/widgets/kernel/qwidget.cpp: patch does not apply
error: patch failed: src/widgets/util/qsystemtrayicon.cpp:709
error: src/widgets/util/qsystemtrayicon.cpp: patch does not apply
error: patch failed: src/widgets/widgets/qabstractscrollarea.cpp:640
error: src/widgets/widgets/qabstractscrollarea.cpp: patch does not apply
error: patch failed: src/widgets/widgets/qwidgetlinecontrol.cpp:40
error: src/widgets/widgets/qwidgetlinecontrol.cpp: patch does not apply
error: patch failed: src/widgets/widgets/qwidgettextcontrol.cpp:71
error: src/widgets/widgets/qwidgettextcontrol.cpp: patch does not apply

D:\Sources\telegram_cloned\Libraries\qt5_6_2\qtbase>
*********************************

**Comment by raimand13** [comment]
After 3 days work on it. i redirect all command prompt outputs to log files and i fixed it by change "Telegram project properties -> Linker -> General -> Additional Libraries Directories" -> '..\..\Libraries\breakpad\src\out\Debug\obj\client' to ..\..\Libraries\breakpad\src\out\Debug\obj\client\windows".
