### ISSUE TITLE
Troubles building telegram with msvc 2017

### ISSUE THREAD

**Issue by NachoCheeseDip** [telegramdesktop/tdesktop#4549]
### Steps to reproduce
1. Followed official building instruction here https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md. Installed all tools, set them in path, ninja,jom,cmake etc
2. Built all libraries, until reached qt 5.6.2
3.  Done this command to build Qt 5.6.2

```
git clone git://code.qt.io/qt/qt5.git qt5_6_2
cd qt5_6_2
perl init-repository --module-subset=qtbase,qtimageformats
git checkout v5.6.2
cd qtimageformats
git checkout v5.6.2
cd ..\qtbase
git checkout v5.6.2
git apply ../../../tdesktop/Telegram/Patches/qtbase_5_6_2.diff
cd ..

configure -debug-and-release -force-debug-info -opensource -confirm-license -static -I "%cd%\..\openssl\Release\include" -no-opengl -openssl-linked OPENSSL_LIBS_DEBUG="%cd%\..\openssl\Debug\lib\ssleay32.lib %cd%\..\openssl\Debug\lib\libeay32.lib" OPENSSL_LIBS_RELEASE="%cd%\..\openssl\Release\lib\ssleay32.lib %cd%\..\openssl\Release\lib\libeay32.lib" -mp -nomake examples -nomake tests -platform win32-msvc2015

jom -j4
jom -j4 install
cd ..
```

### Expected behaviour
I excpected qt beign build

### Actual behaviour
Instead of build of qt 5.6.2, i get this error after jom -j4:

```
Q:\tg_build\ThirdParty\jom\jom.exe -f Makefile.Debug
link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:..\..\..\bin\moc.exe @C:\Users\q\AppData\Local\Temp\moc.exe.12116.16.jom
QtBootstrapd.lib(qbytearray.obj) : error LNK2019: ссылка на неразрешенный внешний символ _z_compress2 в функции "class QByteArray __cdecl qCompress(unsigned char const *,int,int)" (?qCompress@@YA?AVQByteArray@@PBEHH@Z)
QtBootstrapd.lib(qbytearray.obj) : error LNK2019: ссылка на неразрешенный внешний символ _z_uncompress в функции "class QByteArray __cdecl qUncompress(unsigned char const *,int)" (?qUncompress@@YA?AVQByteArray@@PBEH@Z)
..\..\..\bin\moc.exe : fatal error LNK1120: неразрешенных внешних элементов: 2
        cd tools\rcc\ && ( if not exist Makefile Q:\tg_build\Libraries\qt5_6_2\qtbase\bin\qmake Q:\tg_build\Libraries\qt5_6_2\qtbase\src\tools\rcc\rcc.pro -o Makefile ) && Q:\tg_build\ThirdParty\jom\jom.exe -f Makefile
jom: Q:\tg_build\Libraries\qt5_6_2\qtbase\src\tools\rcc\Makefile.Debug [..\..\..\bin\rcc.exe] Error 1120
        Q:\tg_build\ThirdParty\jom\jom.exe -f Makefile.Debug
        link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:..\..\..\bin\rcc.exe @C:\Users\q\AppData\Local\Temp\rcc.exe.20164.0.jom
QtBootstrapd.lib(qbytearray.obj) : error LNK2019: ссылка на неразрешенный внешний символ _z_compress2 в функции "class QByteArray __cdecl qCompress(unsigned char const *,int,int)" (?qCompress@@YA?AVQByteArray@@PBEHH@Z)
QtBootstrapd.lib(qbytearray.obj) : error LNK2019: ссылка на неразрешенный внешний символ _z_uncompress в функции "class QByteArray __cdecl qUncompress(unsigned char const *,int)" (?qUncompress@@YA?AVQByteArray@@PBEH@Z)
..\..\..\bin\rcc.exe : fatal error LNK1120: неразрешенных внешних элементов: 2
jom: Q:\tg_build\Libraries\qt5_6_2\qtbase\src\tools\rcc\Makefile [debug] Error 2
jom: Q:\tg_build\Libraries\qt5_6_2\qtbase\src\tools\moc\Makefile.Debug [..\..\..\bin\moc.exe] Error 1120
jom: Q:\tg_build\Libraries\qt5_6_2\qtbase\src\tools\moc\Makefile [debug] Error 2
jom: Q:\tg_build\Libraries\qt5_6_2\qtbase\src\Makefile [sub-moc-make_first] Error 2
jom: Q:\tg_build\Libraries\qt5_6_2\qtbase\src\Makefile [sub-rcc-make_first] Error 2
jom: Q:\tg_build\Libraries\qt5_6_2\qtbase\Makefile [sub-src-make_first] Error 2
jom: Q:\tg_build\Libraries\qt5_6_2\Makefile [module-qtbase-make_first] Error 2`
```

error LNK2019: ссылка на неразрешенный внешний символ translates as:

error LNK2019 link to unresolved external symbol.

From what i understand, this functions compress2/uncompress come from zlib library. So i have tried to add the switch -qt-zlib to the configure command, but i got same error. Then i tried to specify zlib directly to qt, adding a switch -system-zlib, the command looked like this:

`configure -debug-and-release -force-debug-info -opensource -confirm-license -static -I "%cd%\..\openssl\Release\include Q:\tg_build\Libraries\zlib" -L "Q:\tg_build\Libraries\zlib\contrib\vstudio\vc14\x86\ZlibStatDebug" -l "zlibstat.lib" -no-opengl -openssl-linked OPENSSL_LIBS_DEBUG="%cd%\..\openssl\Debug\lib\ssleay32.lib %cd%\..\openssl\Debug\lib\libeay32.lib" OPENSSL_LIBS_RELEASE="%cd%\..\openssl\Release\lib\ssleay32.lib %cd%\..\openssl\Release\lib\libeay32.lib" -system-zlib -mp -nomake examples -nomake tests -platform win32-msvc2015`

Configure result shows that qt is picked up zlib:

`Additional libraries........-LQ:\tg_build\Libraries\zlib\contrib\vstudio\vc14\x86\ZlibStatDebug -lzlibstat.lib`

But i get same errors 
```

QtBootstrapd.lib(qbytearray.obj) : error LNK2019: ссылка на неразрешенный внешний символ _z_compress2 в функции "class QByteArray __cdecl qCompress(unsigned char const *,int,int)" (?qCompress@@YA?AVQByteArray@@PBEHH@Z)
QtBootstrapd.lib(qbytearray.obj) : error LNK2019: ссылка на неразрешенный внешний символ _z_uncompress в функции "class QByteArray __cdecl qUncompress(unsigned char const *,int)" (?qUncompress@@YA?AVQByteArray@@PBEH@Z)
```

### Configuration
**Operating system:**
Windows 10 x64

Can someone help, i have done all according to instruction, all libs built without problem, but with the qt, this weird stuff is happening

**Comment by surinkim** [comment]
Your problem is same to me.
I've solve that by following below instructions.

There are some wrong point in [building-msvc2017.md](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md)

-  `configure` option's openssl relative path is incorrect. It should be `%cd%\..\..\openssl\` not `%cd%\..\openssl\`

- `jom.exe` should be run in current directory, not `$ThirdParty\jom\`

So,
 1. Go to, `Q:\tg_build\Libraries\qt5_6_2\qtbase`
 2. For reconfigure, run `nmake confclean`
 3. Run, `configure -debug-and-release -force-debug-info -opensource -confirm-license -static -I "%cd%\..\..\openssl\Release\include" -no-opengl -openssl-linked OPENSSL_LIBS_DEBUG="%cd%\..\..\openssl\Debug\lib\ssleay32.lib %cd%\..\..\openssl\Debug\lib\libeay32.lib" OPENSSL_LIBS_RELEASE="%cd%\..\..\openssl\Release\lib\ssleay32.lib %cd%\..\..\openssl\Release\lib\libeay32.lib" -mp -nomake examples -nomake tests -platform win32-msvc2015` 
 4. Run, `..\..\..\ThirdParty\jom\jom.exe -j4`
 5. Run, `..\..\..\ThirdParty\jom\jom.exe -j4 install`
 6. `cd ..`
 
Note that `%cd%\..\..\openssl`, not `%cd%\..\openssl`

I hope this will help you.

**Comment by 2008820** [comment]
do you solution question? i have same problem

**Comment by 2008820** [comment]
i find solution  way https://github.com/telegramdesktop/tdesktop/issues/3702#issuecomment-367299489

**Comment by 23rd** [comment]
This issue is just out of date.
