### ISSUE TITLE
Built in Snipping tool

### ISSUE THREAD

**Issue by Nejked** [telegramdesktop/tdesktop#455]
Basic snipping tool for Telegram to send screen captures instantly instead of using snipping tool/gyazo as the middleman.

**Comment by Sollex-21412** [comment]
PrintScreen -> Ctrl + V in Telegram. It works at least in Windows.

**Comment by Cameri** [comment]
Linux (Gnome desktop): Shift + Print Screen (Configurable hotkey) to capture a region then Ctrl + V in Telegram.

**Comment by Nejked** [comment]
I want to print a part of the screen, printscreen prints my two screens which is quite the difference :)

**Comment by Cameri** [comment]
Try pressing Alt in combination with Print Screen and it should only grab
the window you are currently focusing on.

**Comment by Nejked** [comment]
I give up, print screen and snipping tool is two different things. "a part of the screen" is referred to a single thing I want to send in telegram and not my whole desktop, I was quite specific in the topic with "snipping tool/gyazo" but since no one seems to get it let's just fuck it

**Comment by Sollex-21412** [comment]
@Nejked Please, don't be so angry ). Of course, we understood your request and just provided workarounds. @telegramdesktop will decide how and when implement this feature.
Peace! =)

**Comment by Nejked** [comment]
I already have a workaround, I typed gyazo in the request, that should mean something

**Comment by telegramdesktop** [comment]
OS X has this built in, other systems have free alternatives, I don't think it is a good idea to implement such feature in-app.
