### ISSUE TITLE
Opened photo remains on the screen when switched to another app with Alt+Tab (Linux)

### ISSUE THREAD

**Issue by linoskoczek** [telegramdesktop/tdesktop#4550]
### Steps to reproduce
1. Open any other application than Telegram
2. Open any photo received or sent in Telegram
3. Switch to another application by using Alt+Tab shortcut

### Expected behaviour
Photo should automatically close and allow you to use the app you switched to.

### Actual behaviour
Photo still covers the screen. Application is switched (you see it for example on left and right part of the screen, because the photo usually doesn't cover everything) but the photo is "in the foreground" and you cannot do anything apart from going to console mode, killing telegram-desktop process and getting back to GUI.

### Configuration
**Operating system:**
Manjaro 17.1.7 Hakoila, but same thing also on for example Linux Mint. I assume it's same for every Linux.
**Version of Telegram Desktop:**
1.2.14 (happened in older versions too)
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Aokromes** [comment]
#3144
