### ISSUE TITLE
Crash on OSX when viewing a message containing "\u180e\u2061" in code or pre tags

### ISSUE THREAD

**Issue by udf** [telegramdesktop/tdesktop#4551]
### Steps to reproduce
1. Copy and send the following text in a message (surround it in ``):
        `]᠎⁡[`
(there are two zero width characters between the "]" and "[")
2. View the message from tdesktop on OSX

Additionally, you can swap the order of the two zero width characters and it still crashes. If the message is deleted in a supergroup, viewing the admin log causes the same crash.

### Expected behaviour
The chat where the message was sent can be read as normal.

### Actual behaviour
tdesktop crashes. The message has to be deleted to make tdesktop usable again.

### Configuration
**Operating system:** Mac OS X 10.13.4

**Version of Telegram Desktop:** 1.2.15

**Used theme**: Default

A crash report is attached as the logs don't seem to contain anything useful.
[Telegram_2018-03-30-144411_Yoricks-MacBook-Pro.crash.txt](https://github.com/telegramdesktop/tdesktop/files/1863693/Telegram_2018-03-30-144411_Yoricks-MacBook-Pro.crash.txt)

**Comment by john-preston** [comment]
@udf Thanks, it crashes me even through GitHub not message with your report 🙈
