### ISSUE TITLE
[Feature Request] Bring back Unread Badge Count in dash (Linux)

### ISSUE THREAD

**Issue by Kruemmelkeks** [telegramdesktop/tdesktop#4554]
In Ubuntu 17.10 (Gnome 3.26) the badge indicating unread messages in the dash does not appear anymore. Only the icon in the system tray does show this badge. As far as I found out, this is because the badge display used some feature from Unity - I managed to bring back the badge count by starting Telegram with 
`env XDG_CURRENT_DESKTOP=Unity /snap/bin/telegram-desktop -startintray` 
in autostart. 

Since Unity won't return, I would be happy to get the badges back in Gnome sessions without using this workaround ;-)

**Comment by stek29** [comment]
> /snap/bin/telegram-desktop

What about official binary from https://desktop.telegram.org?

**Comment by Kruemmelkeks** [comment]
No difference. It's also the same version (1.2.15).

**Comment by Kruemmelkeks** [comment]
Okay, strangely it works now (snap package). I don't remember changing anything expect going from Wayland to Xorg as DE. I will keep an eye on that - o far consider this as done ;-)
Thanks anyway!

**Comment by kanocz** [comment]
The same for KDE5 - both standart "Icon only task manager" and (very popular now) Latte-dock supports displaying message count badge, but XDG_CURRENT_DESKTOP=Unity needed

**Comment by AndydeCleyre** [comment]
@kanocz Is it just me, or does enabling this in plasma like that make it impossible to show and hide the window by left-clicking on the tray icon?

**Comment by kanocz** [comment]
@AndydeCleyre I think it's for everyone... but in most cases if I use counters right on icons I don't use tray icons :)

**Comment by kanocz** [comment]
Created pull request that will resolve this issue :) it's very-very simple, so I hope that it will be approved :)
