### ISSUE TITLE
Memory Leak associated with Loading Images

### ISSUE THREAD

**Issue by BoffinbraiN** [telegramdesktop/tdesktop#4559]
Over the last week, possibly after the last update, I've been having occasional crashes with tdesktop. A couple of other users are confirming this. It might be related to loading images, since they often occur when a new image is being loaded in while scrolling chat.

In my latest case, I found that loading a particular image in a chatroom was failing. Telegram would try to load the image (showing the download progress circle) but fail and show the download button again. Clicking it again failed. Clicking it a third time made Telegram crash. 

### Configuration
**Operating system:** Windows 7 64-bit
**Version of Telegram Desktop:** 1.2.15
**Used theme**: Stock dark theme

I don't currently have any useful logs but I will try and get one next time it happens. Let me know what you'd like me to collect.

**Comment by BoffinbraiN** [comment]
See also: https://github.com/telegramdesktop/tdesktop/issues/4566 These two issues might be related, but cannot tell yet.

**Comment by john-preston** [comment]
How much does "tdata" folder near Telegram.exe take place on your drive? If you rename it to "old_tdata", launch the app and log in again, will it still crash?

**Comment by BoffinbraiN** [comment]
OK, I'm pretty sure it's down to some kind of memory leak. When I quickly scroll through a channel or group that has lots of images, each one adds to the memory usage of Telegram until it's using over a gigabyte of RAM, and then it eventually crashes when it can't load any more.

![image](https://user-images.githubusercontent.com/13255058/38466512-318a41fc-3b22-11e8-9432-61f6241d6ed4.png)

**Comment by john-preston** [comment]
@BoffinbraiN It will be a bit better with todays update (like it was in old versions), but this way you still will be able to crash it eventually.

**Comment by BoffinbraiN** [comment]
@john-preston Seems to be good so far. RAM consumption doesn't increase at such crazy rates now in 1.2.17.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1317
