### ISSUE TITLE
[Feature Request] Ability to group chats

### ISSUE THREAD

**Issue by PavelAgurov** [telegramdesktop/tdesktop#4562]
As a user of Telegram I want to group chats by some Tag: Personal Chats, Work Chats, Public channels and so one. Now it's not easy to use application (specially mobile version) if I have many chats.

**Comment by kirsan31** [comment]
#1107

**Comment by PavelAgurov** [comment]
Categories are also ok. But looks like it was proposed in 2015 and still no changes.
