### ISSUE TITLE
Click on telegram tray icon opens menu instead of window

### ISSUE THREAD

**Issue by Yakoot** [telegramdesktop/tdesktop#4563]
### Steps to reproduce
1. Click on telegram tray icon

### Expected behaviour
Telegram window should close or open

### Actual behaviour
opens the menu

### Configuration
**Operating system:** Archlabs (Arch linux + openbox)

**Version of Telegram Desktop:** 1.2.15

**Used theme**: Dark

<b>Logs</b>:
[log_00_30.txt](https://github.com/telegramdesktop/tdesktop/files/1869457/log_00_30.txt)

**Comment by unknownuser88** [comment]
Same behavior on ubuntu18.04 + gnome

**Comment by stek29** [comment]
#4059
