### ISSUE TITLE
App crash and close many times

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [telegramdesktop/tdesktop#4566]
Telegram app does close many times on many different ways.
Some times close when start downloading a voice, music, video or image or receive a new message or when uploading image, I do not know how it happened or what is the reason but it still after i update to last version.

### Configuration
**Operating system:** Debian 9.3

**Version of Telegram Desktop:** 1.2.15

**Used theme**: Default Night theme

**Logs:**
https://paste.ubuntu.com/p/m3c4kdkhHz/
https://paste.ubuntu.com/p/SJfDDdXcPs/

**Comment by BoffinbraiN** [comment]
Might be the same issue as mine, though it's interesting that you're getting it on Linux.
https://github.com/telegramdesktop/tdesktop/issues/4559

**Comment by john-preston** [comment]
I hope https://github.com/telegramdesktop/tdesktop/commit/e5b2e0a6b5becd6839d793eaf101c7575925563e fixes that so it will crash not more than 1.2.6 and previous versions.

**Comment by AmirHosseinKarimi** [comment]
@john-preston then how to increase size of cache limit?
This method do not download files that bigger than cache limit?!

**Comment by BoffinbraiN** [comment]
Things have been working fine for a month now, so we can probably consider this issue solved.
