### ISSUE TITLE
Telegram starting for a long time on Linux since v1.2.14

### ISSUE THREAD

**Issue by TheEdgeOfRage** [telegramdesktop/tdesktop#4567]
### Steps to reproduce
1. Run telegram
2. Wait for more than 7 seconds to start, where it used to be 1-2s in the previous versions

### Configuration
**Operating system:**
- ArchLinux, Kernel v4.15
- SSD, 16GB RAM, Ryzen 7

**Version of Telegram Desktop:** v1.2.14-1.2.15

**Used theme**: Default Dark

<b>Logs</b>:
https://pastebin.com/2KQsCVvE

**Comment by ema-pe** [comment]
It is strange, because it doesn't happen to me. I'm using Debian 9.4 and Telegram Desktop 1.2.15.

**Comment by TheEdgeOfRage** [comment]
That fixed it, I didn't notice that they released telegram in the offical repo. Thanks :)
