### ISSUE TITLE
Please add the option to change avatars’ border-radius

### ISSUE THREAD

**Issue by natewind** [telegramdesktop/tdesktop#4568]
### Steps to reproduce
1. Open settings.

### Expected behaviour
An option to reduce avatars’ border-radius, i. e. make them rounded squares.

### Actual behaviour
No such option; avatars are always hopelessly round.

### Configuration
**Operating system:** Ubuntu Linux 14.04

**Version of Telegram Desktop:** 1.2.15

**Used theme**: Default

</details>

**Comment by Aokromes** [comment]
#2838 ?

**Comment by natewind** [comment]
Sure, if they actually implement it, it’ll be perfect. But chances are we can get a single additional option sooner.

**Comment by Lonami** [comment]
You can use @Streetwalrus' patch in the meantime: github.com/streetwalrus/dotfiles/blob/master/scripts/telegram-desktop

**Comment by natewind** [comment]
It somehow broke the tray icon, then I quit it, then I had to kill the process in System Monitor, and now Telegram won’t start anymore. I tried suspending (it sometimes magically fixes things), but it only killed my session (it happens sometimes, since Ubuntu was written by blind monkeys). I hope reboot will do it, and I won’t have to reinstall Telegram.
It seems using unofficial patches that I don’t understand myself is a bad idea :-/

**Comment by Streetwalrus** [comment]
I don't use the tray icon, it's possible that my patch is breaking it. Please note that I'm using the binaries from Arch Linux, not the official ones, so you may need to adapt it a little.

**Comment by natewind** [comment]
I think I’ll just wait for an official solution.
Telegram isn’t perfect anyway, so this single issue is not critical...

**Comment by 23rd** [comment]
I think this is related to https://github.com/telegramdesktop/tdesktop/issues/1828 and won't be fixed anyway.
