### ISSUE TITLE
Permanent sound output. 

### ISSUE THREAD

**Issue by mirhl** [telegramdesktop/tdesktop#457]
Just to resume #179, *sound output* is permanent. 
Meaning that you have to restart the program to make it recognize that selected default windows audio device has changed

Could probably fix #418

**Comment by HJTP** [comment]
This is something that annoys me as well, but it is simply a missing feature as far as I know (not a bug). The developers are probably aware of it, I hope they will fix it soon.

**Comment by telegramdesktop** [comment]
From version 0.8.22.dev sound output should not be permanent in any of OS.
