### ISSUE TITLE
error in processing `

### ISSUE THREAD

**Issue by proea** [telegramdesktop/tdesktop#4570]
### Steps to reproduce
1. use 3x ` ` ` symbols for text like https://test/ 

### Expected behaviour
![image](https://user-images.githubusercontent.com/2929968/38309691-4ab4b470-3823-11e8-8825-05b131889916.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/2929968/38309984-10be34e8-3824-11e8-9d3a-d93421a1c5b5.png)

### Configuration
**Operating system:**
Mint 18.3

**Version of Telegram Desktop:**
1.2.15 alpha

**Comment by Lonami** [comment]
This isn't an issue on the latest versions (1.3.7 alpha).
