### ISSUE TITLE
No mention notifications from channels

### ISSUE THREAD

**Issue by rromm** [telegramdesktop/tdesktop#4571]
### Steps to reproduce
1. Ask @nickname user to subscribe and disable new post notify.
2. Write @nickname in channel's post and send.
3. Find out that @nickname user subscribed to this channel not recieved notification, like it WOULD be with **group**.

### Expected behaviour
E.G. I'd like to post who's our new company's managers to let all interested people know, but also I'd give an order to all employees to subscribe to let them recieve notifications if I post about preferment them.

### Actual behaviour
No mention notifications to subscribers if they set it off for new posts.

### Configuration
**Operating system:**
W8.1
**Version of Telegram Desktop:**
Last Alpha

**Comment by john-preston** [comment]
@rromm This is intended and currently depends on the server side settings.

**Comment by rromm** [comment]
@john-preston please advice where should I write this to request this future.
