### ISSUE TITLE
Fn+key functionaly, when video is playing

### ISSUE THREAD

**Issue by legik** [telegramdesktop/tdesktop#4572]
### Steps to reproduce
1. Play the video in from any chat
2. Try to use any combination of Fn+key to change behaviour of operating system (e.g. volume up, play/stop music, etc.) 

### Expected behaviour
The used combination of keys change the behaviour

### Actual behaviour
Nothing happens

### Configuration
**Operating system:**
Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.2.15
**Used theme**:
Default in night mode
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Socialdarwinist** [comment]
I confirm this: You cannot just play a video and therein disable the music you have been hearing via a media key.

Tags: Media Keys, MPRIS 
Related: #3960
Duplicates: #3342 and #4693
