### ISSUE TITLE
still can not input chinese in Ubuntu Bionic Beaver

### ISSUE THREAD

**Issue by Licolnlee** [telegramdesktop/tdesktop#4573]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
It should be able to input chinese in telegram 

### Actual behaviour
it can only enter english 

### Configuration
Ubuntu Bionic Beaver

**Version of Telegram Desktop:**
version 1.2.15

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>
I tried the way that change the telegram desktop execution but it still unable to input chinese

**Comment by stek29** [comment]
Where did you install telegram from? official site or some ubuntu way?

**Comment by Aokromes** [comment]
worked for me on final ubuntu 18.04 and copy and paste:

https://i.imgur.com/PCB9kUs.png

**Comment by stek29** [comment]
Please post more info, I'll reopen the issue if needed.
