### ISSUE TITLE
 [Feature Request] Go to spesific date

### ISSUE THREAD

**Issue by azzamsa** [telegramdesktop/tdesktop#4575]
I think it will be nice to have feature that support going to specific date.

If we have huge chat. It's really a pain to scroll up to see what we've talked in x months ago at y date.

Thanks for awesome app :).

**Comment by john-preston** [comment]
@azzamsa You can click on any date (special service message between days) or even on the floating date at the top of the messages history when you scroll up and jump to a specific date.

**Comment by azzamsa** [comment]
What!

I never know such feature exists. From time to time, I always scrolling. 

Thanks lot @john-preston. Thanks :)

**Comment by john-preston** [comment]
@azzamsa Also you can press Ctrl+F (Cmd+F on macOS) to search in a specific chat — and there will be a calendar icon in the search field that does the same.

**Comment by john-preston** [comment]
@azzamsa Well, there is a search icon in the top bar of the chat — that way you get inside the search in the chat. There is a calendar icon in that search mode — you get to a jump-to-date box from there.

**Comment by azzamsa** [comment]
Thanks :)

Thank you so much for your contribution to community. thanks.
