### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by philiparvidsson** [telegramdesktop/tdesktop#4576]
since 1.2.14 (I think), telegram has started taking many seconds to start. from a near instant startup, to 2-5 seconds (it varies greatly and I don't know why). this is happening both on my home computer and work computer, so seens to be something with telegram it self.

I'd urge the development team to now focus their efforts on reducing bloat in telegram. I don't want to see telegram go down the same path as msn, icq and whatever else. this is a recurring theme throughout software history - the software starts out lean, mean and great. over time, bloat buildup becomes so bad that the software becomes slow and eventually unusable, which is the point when the users start moving on to other, newer software (and history then repeats itself).

please think this through carefully! thanks

**Comment by philiparvidsson** [comment]
this is windows 10 pro 64-bit, fully patched (both at home and at work)

**Comment by john-preston** [comment]
@philiparvidsson Can you try to rename "tdata" folder near your Telegram.exe to something ("old_tdata" for example), then start Telegram, log in again (or your settings and auth data will be reset) and see if it works better after that?

**Comment by philiparvidsson** [comment]
@john-preston I did that a week ago and it didn't change anything unfortunately

**Comment by john-preston** [comment]
@philiparvidsson Well, that's something. Can you please download two separate portable versions, for example those:

1.2.15: https://github.com/telegramdesktop/tdesktop/releases/download/v1.2.15/tportable.1.2.15.zip

1.2.6: https://github.com/telegramdesktop/tdesktop/releases/download/v1.2.6/tportable.1.2.6.zip

And check them separately and confirm the difference in the startup time. What exactly do you mean by startup time — time when you see the window of the application or time when the chats are loaded?

**Comment by philiparvidsson** [comment]
I'm using telegram portable already btw.

the two zips you sent me are both slow, taking ~3 seconds from double-click to displaying window. this is on an i7700 and 32gb ram, so relatively high-end system.

**Comment by john-preston** [comment]
@philiparvidsson Yes, but the 1.2.6 is the version from december :( We can go back some more, but I'm afraid it started to be slow for you without depending on the version. Can you share log.txt from Telegram.exe folder? It should have some timestamps about loading and showing the window, perhaps we can see those three seconds there?

**Comment by philiparvidsson** [comment]
```
[2018.04.07 17:59:27] Launched version: 1002015, alpha: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
[2018.04.07 17:59:27] Executable dir: C:/Users/Philip/Downloads/tportable.1.2.15/Telegram/, name: Telegram.exe
[2018.04.07 17:59:27] Initial working dir: C:/Users/Philip/Downloads/tportable.1.2.15/Telegram/
[2018.04.07 17:59:27] Working dir: C:/Users/Philip/Downloads/tportable.1.2.15/Telegram/
[2018.04.07 17:59:27] Command line: C:\Users\Philip\Downloads\tportable.1.2.15\Telegram\Telegram.exe
[2018.04.07 17:59:27] Executable path before check: C:/Users/Philip/Downloads/tportable.1.2.15/Telegram/Telegram.exe
[2018.04.07 17:59:27] Logs started
[2018.04.07 17:59:27] Connecting local socket to Global\1ebdfd4e18cde259a3f55fc529ba8535-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2018.04.07 17:59:27] This is the only instance of Telegram, starting server and app...
[2018.04.07 17:59:27] Moved logging from 'C:/Users/Philip/Downloads/tportable.1.2.15/Telegram/log_start0.txt' to 'C:/Users/Philip/Downloads/tportable.1.2.15/Telegram/log.txt'!
[2018.04.07 17:59:27] Checking...
[2018.04.07 17:59:27] Checking C:\Users\Philip\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\.
[2018.04.07 17:59:27] Checking C:\Users\Philip\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\..
[2018.04.07 17:59:27] Checking C:\Users\Philip\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Firefox.lnk
[2018.04.07 17:59:27] OpenAL Logging Level: (not set)
[2018.04.07 17:59:27] Audio Playback Devices: OpenAL Soft
[2018.04.07 17:59:27] Audio Playback Default Device: OpenAL Soft
[2018.04.07 17:59:27] Audio Capture Devices: 
[2018.04.07 17:59:27] Audio Capture Default Device: 
[2018.04.07 17:59:28] Window Shadow: 1, 1, 3, 4, 6, 9, 13, 18, 24, 31, 38, 46
```

the delay doesn't show up in the log. I don't have antivirus software but I do have defender running. I'm going to try switching that off and we'll see

**Comment by john-preston** [comment]
@philiparvidsson Please check if the first log.txt entry is _after_ the delay or _before_ the delay, according to the system clock, if possible.

**Comment by philiparvidsson** [comment]
the first log entry is after the delay, definitely. I just disabled windows defender and rebooted and it starts in ~1 or 1.5 seconds. so something has maybe changed there. the interesting thing is it happens almost everytime I start telegram, as if it's rescanning it and doesn't cache it as safe.

**Comment by AuditeMarlow** [comment]
I'm experiencing similar issues with the Linux build.

**Comment by Aokromes** [comment]
#4501 or #4240 has generic issue?

**Comment by mwgamble** [comment]
Telegram startup time has gotten worse recently on my laptop which runs Arch Linux. It now takes minutes to load. I've already tried resetting the `tdata` folder, but it doesn't change anything. Please let me know if I can assist in debugging the issue at all.

**Comment by AuditeMarlow** [comment]
@mwgamble I'm on Arch Linux too and I've resolved Telegram being slow by installing `telegram-desktop` from the official community repositories.

**Comment by lb28** [comment]
For me, the startup time also changed significantly at some point in the last days (I am pretty sure I didn't update telegram or change anything on my system). Startup time is literally around **3-4 minutes** (not seconds), and during that time, the telegram.exe process doesn't use any processor / hard drive resources either. It is surely not a resources issue.

I am on Windows 10 Pro (1809). Just tried fresh installs of both the UWP version (via the store) and the latest desktop version (1.4.3). Both have that problem.

One side note: with the desktop version running in the background, clicking the tray icon brings it up instantly, but executing telegram.exe (_with or without_ it running in the background) is so slow.

Here are some logs I have lying around which reflect the problem, sadly without giving enough insight: the time stamp shows a ~3 minute gap always between `Logs started` and `Connecting local socket to Global\ ....`

[log.txt](https://github.com/telegramdesktop/tdesktop/files/2607986/log.txt)
[log_start0.txt](https://github.com/telegramdesktop/tdesktop/files/2607987/log_start0.txt)
[log_start1.txt](https://github.com/telegramdesktop/tdesktop/files/2607988/log_start1.txt)
[log_start2.txt](https://github.com/telegramdesktop/tdesktop/files/2607989/log_start2.txt)

If I can help in any way (with specific log data or something, idk) please let me know how! I am just now noticing how much I depend on Telegram working everyday :)

**Comment by canpoyrazoglu** [comment]
I'm also having slow startup times since a month or two on macOS. It was instant before, and some day it just started to wait ~8-10 seconds before I get to the main window. It only displays a blank window while waiting. (I'm on macOS 10.14.1 with Telegram 4.7.1.147606 though this issue has been here for several versions)

**Comment by stek29** [comment]
@canpoyrazoglu That is not TDesktop but a different app -- from https://macos.telegram.org.
You can get TDesktop at https://desktop.telegram.org.
(There are two apps in Mac App Store as well).

You can report issues in the app you're using at https://t.me/macswift, or at https://github.com/overtake/TelegramSwift.

**Comment by AdKiller** [comment]
Just confirming that I have been experiencing considerably slower startup times for several months too. The startup time used to be instant on my PC. I am sure some new feature that has been added to Telegram Desktop is causing this. not sure what...

I only have a couple of chats and cleared local storage.

Windows 10 Pro 1803

**Comment by Aokromes** [comment]
try on 1.9.8 it must be fixed.

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
supply detailed information of your system.
