### ISSUE TITLE
Mentions & Replies option is not available in Telegram Desktop

### ISSUE THREAD

**Issue by AxDSan** [telegramdesktop/tdesktop#4579]
### Steps to reproduce
1. Open Telegram Desktop
2. Go to any chat and open the Menu (three vertical dots)
3. Mentions & Replies Option is not there.

### Expected behaviour
The Mentions & Replies option should be there.

### Actual behaviour
Other options are shown.

### Configuration
**Operating system:**
Windows 10 x64

**Version of Telegram Desktop:**
1.2.16

**Used theme**:
None / Only dark mode is on

<details><summary><b>Logs</b>:</summary>
N/A

**Comment by john-preston** [comment]
@AxDSan What option is that? 🙈

**Comment by AxDSan** [comment]
https://i.imgur.com/WYwasmk.png

**Comment by AxDSan** [comment]
Thank you so much!
