### ISSUE TITLE
[Feature Request] Left click on tray icon should show/hide Telegram, not bring up menu

### ISSUE THREAD

**Issue by nicklan** [telegramdesktop/tdesktop#458]
Thanks for getting the tray icon working!  This is a small enhancement request.

Right now left click and right click do the same thing, bringing up the show/hide/quit menu.  Standard behavior (at least on linux) is to have left click show/hide the application, and right click bring up a menu.  This is what basically ever app that has a tray icon does.  It would be great to have the behavior of left click changed to show telegram if it's hidden, and hide it if it's showing.

**Comment by auchri** [comment]
duplicate #452
