### ISSUE TITLE
Bold with ** doesn't work in Hebrew

### ISSUE THREAD

**Issue by danmi20** [telegramdesktop/tdesktop#4581]
### Steps to reproduce
1. Sending \*\*שלום\*\* for example, doesn't make the text bold (it happens in Arabic too).
2. Same problem in the android app.

### Expected behaviour
The text should become bold (it works in English).

### Actual behaviour
The text stays in the regular font.

### Configuration
Windows 10

**Version of Telegram Desktop:**
1.2.17

**Used theme**:
Default, Night mode on (it happens also in any other theme that I tried)

**Comment by stek29** [comment]
#1917
