### ISSUE TITLE
Connecting...

### ISSUE THREAD

**Issue by danjde** [telegramdesktop/tdesktop#4582]
Hi Friends,
On Ubuntu 16.04 using Telegram Desktop, and connection type "predefined" many times, not always I can't see my contact and its messages, all is everything empty, white.
I can only access the settings.

Is it possible to delete your settings? And eventually how?

Many thanks!

Davide

**Comment by danjde** [comment]
Thanks stek29 for your help!
I've found "tdata" only into ".local/share/TelegramDesktop/", but deleting it seems irrelevant.
I think other config files are scattered around the home.
I'm using Gnome Desktop, o you think I should be better to ask into a Gnome forum? 

Many thanks again!

Davide

**Comment by Aokromes** [comment]
try to use your phone or web interface to disconnect your desktop to see if it fixes your issue.

**Comment by danjde** [comment]
Ah, ok!
I will try (now it's working) and then report ;-)

thanks again!

Davide
