### ISSUE TITLE
Stuck on full screen

### ISSUE THREAD

**Issue by arya6000** [telegramdesktop/tdesktop#4583]
### Steps to reproduce
1. Download and run Telegram 64 bit on Linux Mint 18

### Expected behaviour
Tell us what should happen
It should not open in full screen mode

### Actual behaviour
Tell us what happens instead
Opens in full screen mode with no close, maximize, minimize button

### Configuration
**Operating system:**
Linut Mint 18

**Version of Telegram Desktop:**
1.2.17

**Used theme**:
Default

**Comment by Serphentas** [comment]
Can confirm this, similar behaviour is seen here.

**Comment by JoshuaDietz** [comment]
As it happend to me for the first time after I killed Telegram via taskmanager I think some config may be corrupted. If I install Telegram on another user profile everything works. Does anyone know where Telegram stores configs on linux so that I can reinstall it from scratch?

**Comment by JoshuaDietz** [comment]
Okay I resolved it. The solution was to delete the folder where Telegram stores everything. On Debian that's ~/.local/share/TelegramDesktop

**Comment by RememberTheAir** [comment]
@JoshuaDietz you don't need to delete everything, just `~/.local/share/TelegramDesktop/tdata/settings0`

**Comment by Serphentas** [comment]
Wouldn't you lose some local configurations (or other stuff) by doing this ?

**Comment by RememberTheAir** [comment]
I had a really similar problem that forced me to delete a file to restore my screen ratio. Deleting that file might fix your problem too, I described what happens [here](https://github.com/telegramdesktop/tdesktop/issues/5274#issuecomment-430934858)

**Comment by Serphentas** [comment]
Thanks for the input, I'll try when it happens again.

**Comment by JoshuaDietz** [comment]
> Wouldn't you lose some local configurations (or other stuff) by doing this ?

Yes, you will be logged out and lose everything you configured. Since there are not that many configuration options I took that 2 minutes to log in again and configure everything properly after that. But yes, the solution is not good. But still better than a telegram client which blocks your whole screen ;D

**Comment by iqbalfn** [comment]
Removing file `~/.local/share/TelegramDesktop/tdata/settings1` while the app closed is also fix the problem without logging out.

**Comment by WPFilmmaker** [comment]
I still have this issue on Lubuntu 18.04 and Telegram 1.8.15.
I accidentally entered fullscreen mode and now I am stuck there. First, how do you toggle/untoggle fullscreen normally?which shortcut?

Second in  /home/myusername/.local/share  there is no file called settings1 :( 

I tried /usr/share but there is no telegram folder either.

Where is the telegram folder?

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.19? myself i don't have seen this bug for long time.

**Comment by Aokromes** [comment]
@arya6000 poke

**Comment by arya6000** [comment]
I am no longer running into this issue
