### ISSUE TITLE
Make behavior 'Dbl click to reply' optional

### ISSUE THREAD

**Issue by intmainreturn0** [telegramdesktop/tdesktop#4584]
Need an option in settings to disable this new behavior: seems very annoying.

**Comment by john-preston** [comment]
@intmainreturn0 It happens only if there is nothing else where you clicked (no text, no links, etc). What's the problem?

**Comment by john-preston** [comment]
@intmainreturn0 But you can just click to deselect text, while double click for that?.. Currently setting for such case is not planned, sorry.
