### ISSUE TITLE
SOCKS5 proxy doesn't work with SSH tunnel?

### ISSUE THREAD

**Issue by skaurus** [telegramdesktop/tdesktop#4588]
### Steps to reproduce
1. I have a Linux box with an unprivileged user with a password and SSH login enabled
2. In Telegram settings, I choose "TCP with custom socks5-proxy" option, enter an IP address of my Linux box, port, username and password
3. These settings work from Putty, but not in a Telegram

### Expected behaviour
This method of creating custom SOCKS5 proxies has always worked for me, so I expect it to work with Telegram too...

### Actual behaviour
I see `Connection through proxy...` forever (I checked, it is actually forever)

### Configuration
**Operating system:**
Windows

**Version of Telegram Desktop:**
1.2.17

**Used theme**:

<details><summary><b>Logs</b>:</summary>
`TCP Error 18, restarting! - SOCKS version 5 protocol error`

**Comment by stek29** [comment]
SOCKS5 != SOCKS5 over SSH. Telegram doesn't support SSH tunnels.
