### ISSUE TITLE
[Feature request] Labels (or hashtags) for messages

### ISSUE THREAD

**Issue by ifmihai** [telegramdesktop/tdesktop#4590]
I'm part of few groups, relatively small groups. 

Sometimes, some messages are way more important than the others. 
Like persistent questions or topics, that require more careful and thoughtful answers from participants. 
Answers that will surely not come easily.

Problem is, 
Lots of unimportant chatter between these important messages, 
which is natural, ok,
But this not so unimportant chatter makes important messages very hard to find, to get to them.  

So, I saw the need for tagging somehow these important messages. 
Labels? 
A favorites section of messages? 

Any way of categorization will do. 
Personally i would prefer labels or tags, hashtags,
 easiest to conceptualize, easiest to filter messages. 
Twitter like?

It would be awesome to be able to mark messages this way. 
Make them important, make them easy to access in the future. 

But, 
I don't know how spread is this need I saw,
I don't know if it has enough worth to get implmented. 
What do you think? 

At least I created this issue, maybe it will create traction. 

### Actual behaviour
1. Click or right click on message. 
2. Add keywords or labels. 
3. When searching, hash tags like #important would bring up those messages
4. Possibility to delete hashtags afterwards. 

### Configuration
**Operating system:**
Any

**Version of Telegram Desktop:**
Any

**Comment by stek29** [comment]
There are hashtags already.
