### ISSUE TITLE
Secret chat ... nearly 3 years 

### ISSUE THREAD

**Issue by personal-assembly-required** [telegramdesktop/tdesktop#4591]
so, what is the status of secret chat seems like it could have got done some where between the new sticker search and like any other feature.

 that said what is the actual hold up with it is it crypto knowledge syncing with the cloud (it is not supposed to thats the point of end to end  so hard to think it is that )?

**Comment by personal-assembly-required** [comment]
really not even a reply ? and not a link to its duplicate that might have reply? i know its free but that's cold

**Comment by john-preston** [comment]
@personal-assembly-required https://github.com/telegramdesktop/tdesktop/issues/5

It's hard to do particularly in tdesktop. At least the local messages database is required first. With all sync-between-launches problems.

**Comment by john-preston** [comment]
@personal-assembly-required But on macOS you can use native client with secret chats and on Windows 10 you can use Unigram (based on tdlib) with secret chats.

**Comment by personal-assembly-required** [comment]
thank you vary much ok the inevitable followup you said   "local messages database is required first" what actually needs doing to it from my vary limited knowledge sync outwardly appears fine so i dont think its having or making the sync between the launchers so im guessing and saying its having ans storing the local database of messages securely ? (is there some kind of road map / planed out plan that could answer all this ?)

**Comment by john-preston** [comment]
@personal-assembly-required I didn't quite understand your reply.

Right now tdesktop works as web version: on launch it just loads current state from server, without storing messages anywhere on the hard drive between relaunches. Secret chats require offline message storage which should be synced between app launches (all updates that happened while the app was not running should be downloaded and applied before the app is ready for usage again).

In this context it is easier (and better in any sense) for someone to make an app based on tdlib with the storage and secret chats and syncing and everything else working out of the box instead of trying to add them here.

**Comment by personal-assembly-required** [comment]
That may be true, but this is also the official client, The shiny example of telegrams focus and ideals ect.
So instead of bothering with changing the whole app cus that's pointless work. have you considered just implementing a local database for only secret chats, that does not have to be synced ?  i don't know much about tdlib but maybe you might be able to use its code mostly hole sale (assuming its open source and licensing ect )

**Comment by john-preston** [comment]
@personal-assembly-required You can't just take part of tdlib code and use it in tdesktop, it doesn't work that way. It has completely different way of working with the API, storing data in memory and on disk, etc.

To manage secret chats synced db is the most hard part of implementing the offline messages storage, so the fact that you decide to implement only it and not full offline way of working with messages doesn't really change anything that much.

**Comment by fcore117** [comment]
Lets hope it is still coming in future as i do not like that .NET based Unigram X thing. World has gone crazy with node.js and Electron based bloatware and Telegram is one of few IM apps that uses C/C++

Please add Secret chat some day.
