### ISSUE TITLE
Mention candidate list mischosen on Linux

### ISSUE THREAD

**Issue by owen8877** [telegramdesktop/tdesktop#4592]
### Steps to reproduce
1. Open a group chat.
2. Input the mentioning character `@`
3. Tap the down key until the list is scrolled down

### Expected behaviour
The highlighted item jumps continuously down the candidate list.

### Actual behaviour
When the list is about to scroll down to reveal the next item, the highlight position returns to the top of the visible area of the candidate list.

### Configuration
**Operating system:**
4.15.11-1-ARCH

**Version of Telegram Desktop:**
1.2.12 alpha

**Used theme**:
Default theme

Thank you in advance.

**Comment by Aokromes** [comment]
cannot reproduce on 1.9.8 on windows 10 20h1

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
