### ISSUE TITLE
Tdesktop build error in vs2017

### ISSUE THREAD

**Issue by AndyChen11** [telegramdesktop/tdesktop#4594]
### Expected behaviour
Tell us what should happen

### Actual behaviour
error messages:
E:\TBuild\ThirdParty\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True Telegram.exe "E:\TBuild\ThirdParty\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:Telegram.exe @Telegram.exe.rsp" 1 mt.exe rc.exe "obj\Telegram.Telegram.exe.intermediate.manifest" obj\Telegram.Telegram.exe.generated.manifest
1>Telegram.data_sparse_ids.obj : error LNK2005: "class <lambda> base::functors::add" (?add@functors@base@@3V<lambda>@@A) already defined in Telegram.data_shared_media.obj 
1>
### Configuration
**Operating system:**
Win10 +vs2017
**Version of Telegram Desktop:**

**Used theme**:
Added 
#pragma once in functors.h
<details>
</details>

**Comment by 17dengfeng** [comment]
i got it.

change function `add` as inline function.

functors.h 
` auto add = [](auto value) {
	return [value](auto other) {
		return value + other;
	};
};`

to
` inline auto add = [](auto value) {
	return [value](auto other) {
		return value + other;
	};
};`
