### ISSUE TITLE
Force Reply always shows up when I open Telegram app

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#4595]
Whenever I open the chat it shows in some bots even if reply to the message. What was this issue caused by ? How to resolve it ?

![](https://i.stack.imgur.com/APZGW.png)

**Comment by stek29** [comment]
Is it shown in other th apps too?

**Comment by SmartManoj** [comment]
@stek29 yes and also in every platform

**Comment by stek29** [comment]
Maybe it's expected behavior then?
Telegram provides a way for bots to "force reply".

**Comment by stek29** [comment]
Maybe it's expected behavior then?
Telegram provides a way for bots to "force reply".

**Comment by SmartManoj** [comment]
@stek29 even if i reply it shows again

**Comment by SmartManoj** [comment]
@stek29  how to turn off force reply after getting reply in a bot ?  I have send reply markup with none also in my bot but no luck

**Comment by stek29** [comment]
Is gmailbot your bot? :)

Sorry, it's not BotAPI support here, and if everything works in the same way on other devices then it's a feature.

**Comment by SmartManoj** [comment]
The Bot should remove [ReplyKeyboard.](https://core.telegram.org/bots/api#replykeyboardremove)
