### ISSUE TITLE
Delete all messages from user probably shouldn't be an option in delete message

### ISSUE THREAD

**Issue by schoentoon** [telegramdesktop/tdesktop#4597]
### Steps to reproduce
1. Right click delete message in a group where you're moderator
2. Accidentally tick delete all from user box
3. RIP all messages from that user

### Expected behaviour
This option shouldn't be here to begin with. It only makes sense to remove all messages from a certain user in case you're banning or kicking them. This is actually inconsistent with the Android client where this option doesn't show up with the delete message menu.

### Actual behaviour
The option is there and is easily ticked by accident.

### Configuration
**Operating system:**
Linux but not relevant..

**Version of Telegram Desktop:**
1.2.17 alpha

**Comment by john-preston** [comment]
@schoentoon You need not only accidently tick the checkbox, but after that, without unticking it, accidentally press Delete. I can't see how you do that unintentionally.

**Comment by stek29** [comment]
It's a feature. When somebody is aggressively spamming, you might want to delete all of that user's messages at once.

**Comment by schoentoon** [comment]
Feature or not, still inconsistent around other clients.

**Comment by stek29** [comment]
How is it different from other clients?

**Comment by schoentoon** [comment]
On the Android client if I go to the delete message option I don't get the tick boxes for block, kick or delete all messages from user. That's in a different menu in that client. The feature is in all the clients probably, but not on the same location everywhere.

**Comment by zeroone2numeral2** [comment]
@schoentoon I'm using the Android client and those boxes are always visbile, regardless of the way I'm using to delete a message (by tapping on it or selecting it) - according to your admin permissions, of course

**Comment by schoentoon** [comment]
@zeroone2numeral2 Couldn't get that to show up at all yesterday on Android in the same chat where I deleted someone's messages by accident.. But I found out why, it doesn't show those options for fellow moderators, but it does for everybody else. On desktop client it shows it for admins too :roll_eyes:, which shouldn't be the case imo..

**Comment by johnchen902** [comment]
I accidentally deleted all messages from a user yesterday.

I think this option looks like "Delete for all users" (considering there is a similar dialog reading "Delete for everyone"), and with dialog fatigue, it's not impossible to tick it and click DELETE.

This feature may be needed, but we do need to prevent accidental triggers too.
