### ISSUE TITLE
Telegram refuse to start on Debian sid. Actually iterate through fonts and throw errors and start after a 1 minute

### ISSUE THREAD

**Issue by in1t3r** [telegramdesktop/tdesktop#4598]
### Steps to reproduce
1. Start a Telegram from terminal
2. Wait for it to complete it will throw similar to this errors: https://dpaste.de/qU3S
3. It might eventually start or you might need to kill it with SIGKILL and start again anyway it startup time is around a minute.
4. Also I noticed that sometimes when clicking on close it do not go to try but crashes in background.

### Expected behaviour
Telegram before this update was starting pretty damn fast.

### Actual behaviour
Iterrate throw fonts throw errors reading /etc/fonts/fonts.conf file

### Configuration
Debian Sid - SSD for the system - X86_64 architecture

**Version of Telegram Desktop:**
1.2.17 alpha -- binary for linux

**Used theme**:
Night theme

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)
https://dpaste.de/qU3S

I dont have debuglogs if needed ask I can provide them.

</details>

**Comment by stek29** [comment]
#4543
