### ISSUE TITLE
Autorouting with CJDNS (Hyperboria) and TOR

### ISSUE THREAD

**Issue by Foxcool** [telegramdesktop/tdesktop#4599]
Telegram can try to connect automatically with overlay networks if default variant not working.
 
CJDNS gives IPv6 on fc00:* range. You can add servers in this net.
https://github.com/cjdelisle/cjdns

TOR... Everybody knows TOR (:

**Comment by Piterden** [comment]
Just run Tor-browser, then setup socks5-proxy connection to `127.0.0.1:9150`.
That's all!

**Comment by ustoz** [comment]
@Piterden, if pro-government guys pay more attention to shutdown some services, there is very high probability they start ban sites which distribute software like tor/vpn/etc, so support different transport  networks out of the box is really good idea.

**Comment by stek29** [comment]
@ustoz What stops them from banning sites that distribute TDesktop? They did block tdesktop.com/desktop.telegram.org in Russia, for example, while TOR/I2P/CJDNS/etc sites aren't blocked.

**Comment by Mikaela** [comment]
Am I correct in the interpretation that this issue requests Telegram to support .onion services like Facebook does reducing load on the exit nodes and not letting exit nodes see that we are using Telegram?

I think [Onionbalance](https://onionbalance.readthedocs.org/) might be helpful for that.

> Just run Tor-browser, then setup socks5-proxy connection to 127.0.0.1:9150.

The port is 9050 for sytem wide-Tor, 9150 is Tor Browser Bundle default if I have understood correctly.

> TOR... Everybody knows TOR (:

Sorry, I found this comment funny as I had earlier linked to the [Tor FAQ: Why is it called Tor](https://torproject.org/docs/faq.html.en#WhyCalledTor) which says:

>  Note: even though it originally came from an acronym, Tor is not spelled "TOR". Only the first letter is capitalized. In fact, we can usually spot people who haven't read any of our website (and have instead learned everything they know about Tor from news articles) by the fact that they spell it wrong.

**Comment by stek29** [comment]
> Am I correct in the interpretation that this issue requests Telegram to support .onion services like Facebook does reducing load on the exit nodes and not letting exit nodes see that we are using Telegram?

Nope, that one would be a server side issue, and would have nothing to do with this repo.

**Comment by Mikaela** [comment]
> Nope, that one would be a server side issue, and would have nothing to do with this repo.

What would be the best place to open or request it?

**Comment by stek29** [comment]
@Mikaela Contact in-app support or ping Telegram on twitter.
