### ISSUE TITLE
is there anyway to save picture profile in specific folder ?

### ISSUE THREAD

**Issue by Painkiller1991** [telegramdesktop/tdesktop#4604]
i find this method for getting all profile pictures:

 ApiWrap::userPhotosDone

how can i save pictures in my specific folder?

**Comment by Painkiller1991** [comment]
i change this code:

photoIds.reserve(photos.size());
	for (auto &photo : photos) {
		if (auto photoData = _session->data().photo(photo)) {
			photoIds.push_back(photoData->id);
		}
	}


to below code:

photoIds.reserve(photos.size());
	for (auto &photo : photos) {
		if (auto photoData = _session->data().photo(photo)) {
			photoIds.push_back(photoData->id);
			auto filter = qsl("JPEG Image (*.jpg);;") + FileDialog::AllFilesFilter();
			FileDialog::GetWritePath(
				lang(lng_save_photo),
				filter,
				filedialogDefaultName(qsl("photo"), qsl(".jpg")),
				base::lambda_guarded(this, [=](const QString &result) {
				if (!result.isEmpty()) {
					photoData->full->pix().toImage().save(result, "JPG");
				}
			}));
		}
	}

but not worked??? what is wrong? who can help me?

**Comment by Painkiller1991** [comment]
@john-preston

**Comment by stek29** [comment]
Why are you doing this? There are plenty of libs with proper docs and apis for working with Telegram

**Comment by Painkiller1991** [comment]
@stek29 what libs?
