### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [telegramdesktop/tdesktop#4605]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Instance](https://github.com/telegramdesktop/tdesktop/blob/f98fdeab3fb2ba6f55daf8481595f879729d1b84/Telegram/SourceFiles/calls/calls_instance.cpp#L288 "Destructor for Instance")
- [TopBar::setTitle](https://github.com/telegramdesktop/tdesktop/blob/f98fdeab3fb2ba6f55daf8481595f879729d1b84/Telegram/SourceFiles/info/info_top_bar.cpp#L72 "TopBar::setTitle function")

**Comment by john-preston** [comment]
Yes, they are redundant indeed. But tbh they should be replaced by some sort of owning pointers like base::unique_qptr instead of non-owning QPointer, then delete-s will become not needed.

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by john-preston** [comment]
@elfring That could be useful. Any tips on integrating it into VS development workflow?
