### ISSUE TITLE
Voice call hang up on Connecting.. step (can't connect) on Linux

### ISSUE THREAD

**Issue by phplego** [telegramdesktop/tdesktop#4606]
### Steps to reproduce
1. Make sure you are connecting from russian IP
2. Launch Telegram Desktop on Linux Ubuntu
3. Call to any contact

### Notes
* Using proxy which is not blocked in Russia does not solve the problem
* Other functionality (text messages, sending photo, video content and etc) works fine
* Telegram Desktop on **Windows** works fine with the same contacts and same connection

### Expected behaviour
Connection established 

### Actual behaviour
Infinite "Connection..." label displayed

### Configuration
**Operating system:** Ubuntu Linux 16.04 LTS

**Version of Telegram Desktop:** 1.2.17

**Used theme**: Standard

<details><summary><b>Logs</b>:</summary>
log.txt does not contain recent items.

**Comment by Aokromes** [comment]
Try on 1.2.18
