### ISSUE TITLE
Allow Telegram clients to proxy each other

### ISSUE THREAD

**Issue by hurricup** [telegramdesktop/tdesktop#4607]
To help avoiding any type of blocking, telegram users could help each other:

1. If i'm not blocked, I should be able to enable proxying in my telegram client for one telegram user.
2. If i'm blocked I should be able to blindly discover someone with opened and unused proxy and use it.

Such approach makes any attempts to block Telegram useless.

**Comment by john-preston** [comment]
@hurricup Yes, this is cool. But it is really hard to implement :(

**Comment by hurricup** [comment]
The real problem here I can see is discovering each other without centralized directory. Guess this may be distributed too.

**Comment by Lonami** [comment]
Clients acting as a proxy is strange. I wouldn't like strangers to use my client as a proxy. Rather, you should connect to a real proxy. Those clients can run a separate proxy program if they want to. Separation of concerns. This is an application for messaging, not a proxy.

**Comment by hurricup** [comment]
Yes, it is. This could be configurable by users.
 But such approach could be unblockable at all.
