### ISSUE TITLE
Telegram takes several seconds to open

### ISSUE THREAD

**Issue by aitbw** [telegramdesktop/tdesktop#4611]
Hi! :wave: I updated my OS today and when I went to open up Telegram, it took **A LOT** of time before showing up on my screen. I didn't measure the time but I'm assuming it was around the same amount of time described in #4608 and #4609

After a restart, Telegram's startup time definitely lowered considerably. It now shows up after 8 seconds approximately but that's still way too much considering it usually opens up instantly

### Expected behaviour
Telegram should open as soon as I click on its icon

### Actual behaviour
Telegram opens 8 seconds after I click its icon

### Configuration
* **Operating system:** Manjaro Linux with Linux Kernel 4.14.34

* **Version of Telegram Desktop:** 1.2.7

* **Used theme**: Light

### Logs

Logs titled `log.txt` and `log_20_30.txt` can be found [here](https://gist.github.com/aitbw/5df1b0ee452cb8bb63672bdb5d447440)

Let me know if you fellas need more data :smile:

Cheers!

**Comment by stek29** [comment]
Please check if it's #4543

**Comment by aitbw** [comment]
Thanks for the reply @stek29 but unfortunately, it is not :(

I tried installing Telegram from Manjaro's repos as suggested by @Socialdarwinist but the startup time remains the same

Although it's worth noting that monospaced text looks weird, as you can see here:

![screenshot_2018-04-18_15-07-30](https://user-images.githubusercontent.com/9470839/38952661-6789ccdc-431a-11e8-8e9c-f01f1eaf5660.png)

Maybe they're interlinked in some way?

**Comment by smoneck** [comment]
Sounds to me like #4240

**Comment by aitbw** [comment]
Still happening after 1.3 update
