### ISSUE TITLE
Force Reply always shows up when I reopen Telegram Desktop app 

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#4613]
I used force_reply . And after getting the reply , I removed the [replykeyboard](https://core.telegram.org/bots/api#replykeyboardremove).
But the next opening of the app, when I open the bot ,it again shows Force reply

**Comment by stek29** [comment]
Once again: does it show it in other apps too?

**Comment by SmartManoj** [comment]
Now the issue is resolved TGD v1.2.17
