### ISSUE TITLE
Keyword Alert notification

### ISSUE THREAD

**Issue by hurricup** [telegramdesktop/tdesktop#4615]
There are 2 feature requests, both closed without an explanation. Would be really nice to clarify what and why. Talking about #554 #1727

Request is about possibility to override mute by keyword.

**Comment by zeroone2numeral2** [comment]
> closed without an explanation

Both are labeled as API issue. Settings that users would expect to have synced across clients require a change in the API first, which is out of the scope of this repository

**Comment by hurricup** [comment]
would be really nice to have a link to appropriate repository or issue tracker to be able to vote/discuss or just follow this request.

**Comment by auchri** [comment]
@zeroone2numeral2 👍

**Comment by stek29** [comment]
@hurricup telegram's trackers aren't public. You can submit feature requests through in-app support or Twitter.
