### ISSUE TITLE
mute leave chat notification messages

### ISSUE THREAD

**Issue by pva** [telegramdesktop/tdesktop#4616]
Every time somebody leaves chat this chat is moved to the top of the list and is highlighted. We need an option to disable such notifications. There is no need to be notified that someone left the chat.

BTW people already write posts trying to pursue others of doing this: https://ilyabirman.ru/meanwhile/all/left-the-group (in Russian, but still). Can we fix this problem in a client application?

**Comment by stek29** [comment]
It has to be done on server side
