### ISSUE TITLE
[Feature Request] Status Bar Icon Badge (OS X)

### ISSUE THREAD

**Issue by stutumi** [telegramdesktop/tdesktop#462]
Hello, could you please add a badge (something like a red *, doesn't need a message counter) over Status Bar Icon just to tell that your Telegram has unread activity?

**Comment by wcastello** [comment]
This would be nice.

**Comment by dufreyne** [comment]
+1

**Comment by telegramdesktop** [comment]
Which one is the status bar icon? Icon on the top-right does contain the unread counter. Give me a screenshot please.

**Comment by wcastello** [comment]
![screen shot 2015-02-17 at 6 09 56 am](https://cloud.githubusercontent.com/assets/3504711/6224922/ff7eb344-b66a-11e4-84f0-199a2f4fb131.png)

no unread counter here on v 1.38.13535; counter only present in app switcher and dock icons.

**Comment by dufreyne** [comment]
I think the author meant dock icon badge with unread/new messages.

**Comment by stutumi** [comment]
Not Dock, this one:

![screen shot 2015-02-17 at 10 21 56](https://cloud.githubusercontent.com/assets/4337621/6228184/ce5cc6be-b68f-11e4-9e5f-c42205c2a767.png)

![screen shot 2015-02-17 at 10 21 37](https://cloud.githubusercontent.com/assets/4337621/6228192/e87dbd6e-b68f-11e4-85a0-fc9ef880e8bc.png)

I use Dock with auto hide and my Notification Center is disabled, so notifications there are useless for me. I always have to check manually if someone sent me a new message on Telegram instead of just looking at the Status Bar...
