### ISSUE TITLE
[Feature request] Messages spam filter by words list

### ISSUE THREAD

**Issue by maxxx** [telegramdesktop/tdesktop#4620]
Hi. It will be nice to see ability (or plugin?) to hide\mark messages in UI, which contains one of word from special, user-filled words spam list.
Will be useful to "block" annoyning advert posts in channels.

### Configuration
Operating system: win 10
Version of Telegram Desktop: 1.2.17

**Comment by neesti** [comment]
This is very useful into groups too.

**Comment by RememberTheAir** [comment]
This is not supported by the API

**Comment by stek29** [comment]
@neesti you can use bots for that
