### ISSUE TITLE
Some of the text in the input line gets deleted incidentially

### ISSUE THREAD

**Issue by ManuelSchneid3r** [telegramdesktop/tdesktop#4621]
### Steps to reproduce
Happens out of the blue.

### Expected behaviour
Nothing.

### Actual behaviour
Some of the text in the input line gets deleted while writing.

### Configuration
**Operating system:**
Archlinux
**Version of Telegram Desktop:**
1.2.17
**Used theme**:
Standard

**Comment by d0tfile** [comment]
@ManuelSchneid3r are you using proxy? I have similar behavior with proxy (socks5), some parts of text or even full message is being deleted.
Arch Linux / Telegram Desktop 1.2.17-1 (from Arch repo).

**Comment by ManuelSchneid3r** [comment]
Nope.

**Comment by ManuelSchneid3r** [comment]
> Does it come back when you press Ctrl + Z?

I tried this the last time and it worked.

> Do you have slow connection?

Indeed my network connection is not the best atm, I am forced to use a power-line connection which leads to short disconnects every now and then.

**Comment by stek29** [comment]
Then you'd have to just rely on Ctrl Z I'm afraid.
That's how draft sync works.

Imo the only proper way to fix this would be to store what device draft was submitted from with the draft itself on server so app doesn't rewrite it's own draft
