### ISSUE TITLE
Connection lost, stuck on Connecting... Restart helps

### ISSUE THREAD

**Issue by kirsan31** [telegramdesktop/tdesktop#4622]
### Steps to reproduce
1. Russia...
2. Use tdesktop, from several minutes to several hours, until it lost connection.

### Expected behaviour
Automatically reconnecting, because, **if I restart program manually, connection is return.**

### Actual behaviour
Program stuck on connecting indefinitely...

### Configuration
**Operating system:** windows 7 x64

**Version of Telegram Desktop:** 1.2.17

**Connection type**: auto, ipv6 checked (without ipv6 - same behavior)

**Used theme**: default

**DEBUG logs** with connection lost and returning after restart:
[tcp_14_45.txt](https://github.com/telegramdesktop/tdesktop/files/1938102/tcp_14_45.txt)
[log_14_45.txt](https://github.com/telegramdesktop/tdesktop/files/1938103/log_14_45.txt)

**Comment by john-preston** [comment]
@kirsan31 Yeah, thanks for the report. I hope to fix that in the next update..

**Comment by SagePtr** [comment]
Same issue. I need to restart Telegram manually because it suddenly lose connection and stops sending/receiving. Telegram should check heartbeat every few seconds/minutes and automatically reconnect if connection is lost or stuck. And if possible, add menu item to reconnect manually (without restarting app).
I use 1.2.17 now.

**Comment by john-preston** [comment]
@SagePtr It tries to reconnect, but it doesn't do everything it does when it's just launched.

**Comment by Aokromes** [comment]
#4556 ?

**Comment by stek29** [comment]
@Aokromes no, it's about re-requesting simpleconfig, and won't be fixed by just opening it's window.

**Comment by john-preston** [comment]
@stek29 Please check if the latest alpha version 1.2.19 has this problem.

**Comment by stek29** [comment]
@john-preston I assumed it doesn't because I saw commits fixing this behavior.

It's quite hard to make a test environment -- I'd have to block IPs it fetches manually once and then somehow mitm dns/app HTTPS requests.

**Comment by kirsan31** [comment]
> It's quite hard to make a test environment -- I'd have to block IPs it fetches manually once and then somehow mitm dns/app HTTPS requests.

Exactly :(

**Comment by kirsan31** [comment]
Testing latest builds for several days - all ok.

**Comment by nathanchere** [comment]
Has been happening for about 6 months on Telegram for Android as well. Kill/restart app fixes it.

**Comment by ilya144** [comment]
It's still happening. May 19, 2019.

**Comment by chiboreache** [comment]
Same here, on Arch Linux

**Comment by Shimanoff** [comment]
> Same here, on Arch Linux
> 
> only [Kepka](https://github.com/procxx/kepka) works fine

Exactly the same situation. Thanks for kepka, it helped me.

**Comment by chiboreache** [comment]
> kepka worked only a few hours and then lost connection

That's true...
