### ISSUE TITLE
[URGENT]Telegram not responding to any type of support requests

### ISSUE THREAD

**Issue by varunhardgamer** [telegramdesktop/tdesktop#4623]
So, I have been trying to reach out telegram support through different modes, I have tried mailing 1000 times, tried volunteer support within the app, tried to reach out via Twitter but never received a single response from Telegram.
Here's the issue now, There are around 3 channels which have been harassing my female friends on Telegram, and posting pornographic content with their name and **Real** profile pictures, i have tried reporting the channel 1000 times, but all in vain.
I sincerely hope that you guys will look into this issue as soon as possible before the conditions get worse of them because of those channels.

**Comment by auchri** [comment]
@varunhardgamer How is this related to Telegram Desktop?
Personal experience: They always answer within 6 hours.

**Comment by auchri** [comment]
https://telegram.org/faq#q-there-39s-illegal-content-on-telegram-how-do-i-take-it-down btw.

**Comment by varunhardgamer** [comment]
I clearly wrote it, that i ain't getting replies

**Comment by varunhardgamer** [comment]
Lol 6 hours, its more than 6 weeks now,

**Comment by d0tfile** [comment]
@varunhardgamer anyway not a Telegram Desktop issue. Maybe try to contact via twitter.

**Comment by stek29** [comment]
Maybe you should've left your email, telegram username or some other info which would help Telegram team to find your reports just in case they see it :)

**Comment by varunhardgamer** [comment]
**gamelovr695@gmail.com**
I am mailing them with this email.

**Comment by varunhardgamer** [comment]
Thank you all tho. :)
