### ISSUE TITLE
Can you team up with ZeroNet to move on?

### ISSUE THREAD

**Issue by DATSEC** [telegramdesktop/tdesktop#4625]
You are not the first to start this war against states.
Together we can do this.
https://twitter.com/HelloZeroNet/status/918930911198089222

https://github.com/HelloZeroNet/ZeroNet/issues/1396
If you have more ideas suggest we will decide together.

**Comment by stek29** [comment]
It's not the best place to contact telegram as a whole.

I'd recommend using Twitter or some contacts listed on telegram site.
