### ISSUE TITLE
MTP Error: failed to get config!

### ISSUE THREAD

**Issue by debianmanual** [telegramdesktop/tdesktop#4626]
### Steps to reproduce
1. wget https://updates.tdesktop.com/tlinux/tsetup.1.2.17.tar.xz
2. sudo tar -xJvf tsetup.1.2.17.tar.xz -C /usr/local/
3. /usr/local/Telegram/Telegram 

### Expected behaviour
Tell us what should happen
Telegram Desktop shows Loading... msg.

### Actual behaviour
Tell us what happens instead
Contacts and chats should load ..

### Configuration
**Operating system:**
Debian 8 64bit
Linux SVP1121 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux

and
Debian 9 64bit
Linux SVP1121C5E 4.15.0-0.bpo.2-amd64 #1 SMP Debian 4.15.11-1~bpo9+1 (2018-04-07) x86_64 GNU/Linux

**Version of Telegram Desktop:**
Upgraded to latest v 1.2.17

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

[TelegramDesktop.20180424.MTP_Error_failed_to_get_config.txt](https://github.com/telegramdesktop/tdesktop/files/1943009/TelegramDesktop.20180424.MTP_Error_failed_to_get_config.txt)

</details>

**Comment by stek29** [comment]
Sounds like server side issue for me.

Does it still occur? Isn't Telegram blocked in your country, just in case?

**Comment by debianmanual** [comment]
How strange,

@john-preston 
when I deleted "~/.local/share/TelegramDesktop" and start telegram again, all worked again on both PC's. Thanx.
