### ISSUE TITLE
Can not post gifs from **Search GIFs** results if few hours passed after search request

### ISSUE THREAD

**Issue by BaZzz01010101** [telegramdesktop/tdesktop#4627]
### Steps to reproduce
1. Open GIFS tab
2. Search for something
3. Wait significant amount of time (at least few hours)
4. Try to post any gif from this search result into a chat

### Expected behaviour
Gif should be posted successfully

### Actual behaviour
Gif appears in the chat but actually, it's not posted. It has upload spinning indicator but process never finished. If to close client and start again than posted gif will be lost. But if to clear search input instead and repeat same request, same gif can be successfully posted to chat. Noticed that same search request returned a little different gif set. At least same gif had a little different index in the list.

### Configuration
Windows 10 Pro
version: 1709 
biuld: 16299.371

**Version of Telegram Desktop:**
1.2.17

**Comment by john-preston** [comment]
@BaZzz01010101 This is how server side with inline bots work :( it remembers results only for some not very long period of time. Search for gifs work through inline bots.
