### ISSUE TITLE
How to activate spell check?

### ISSUE THREAD

**Issue by Thomanji** [telegramdesktop/tdesktop#4628]
### Steps to reproduce
1. Type something wrong
2. No indication is anything is misspelled.
3. 

### Expected behaviour
Tell us what should happen
Normally it would underline a misspelled word red, than when right click on it should give options to correct the spelling. Like on any basic program or app that deals with text input.

### Actual behaviour
Tell us what happens instead
Nothing, it lets you send even the most basic spelling mistakes without any warning

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.2.17
**Used theme**:
default
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@Thomanji Spellchecker is not available in Telegram Desktop :(

**Comment by Thomanji** [comment]
@john-preston Oh, this is very unfortunate that such a basic function is completely missing. I guess we are forced to use something more advanced that can do a spellcheck.  I checked around a bit and it seems there is not even anything external or 3rd party. A bit disappointing since I though Telegram is more advanced than this.

**Comment by john-preston** [comment]
@Thomanji Sadly it isn't :(

**Comment by DevAlone** [comment]
@john-preston What about these libraries?
http://hunspell.github.io/
http://aspell.net/

**Comment by kirsan31** [comment]
I am working on integrating [sonnet](https://github.com/KDE/sonnet) now...And I can say, that properly static build it on windows with hunspell plugin and hunspell itself, it's not a trivial (at least for me :) ) task...
It's working for now, but I'm not sure that, I will can bring it to a state where it will be ready for integration into tdesktop :(

![spelling](https://user-images.githubusercontent.com/17767561/39496908-53811184-4da9-11e8-96dc-e35ca2596ec3.gif)

**Comment by fa1rid** [comment]
It's ridiculous that this feature is not available yet.

**Comment by Aokromes** [comment]
#96

**Comment by stek29** [comment]
@kirsan31 have a look at #3232

**Comment by kirsan31** [comment]
@stek29  yea many times already :+1:  I  will wright in details a bit late, have no time now:(

**Comment by kirsan31** [comment]
**Main benefits** from using sonnet:

- Language auto detecting.
- Support of: hunspell, aspell, enchant, hspell, nsspellchecker (native Mac OS), voikko. But static build (without code modification ) only hunspell and nsspellchecker.
- Adding spellchecking to tdesktop it's one line of code :)

**drawbacks**:

- Difficult to build (on windows). To build latest version - need a simple code modification, because officially it needed QT 5.8.0.
- Lack of customization (without code modification).

About @stek29 ToDo:

- Update gyp files && Update Instructions -- once finished. _ToDo._
- Consider adding some dictionaries. _https://extensions.libreoffice.org/extensions?getCategories=Dictionary&getCompatibility=any usually offer more full dictionary's for hunspell._
- Move to enchant spelling lib as it supports a lot more backends, including system native backends. _Mac OS native - out of the box._
- Allow enabling/disabling particular dictionaries through settings (as well as disabling spellchecker completely). _ToDo If needed._
- Add user dictionary support. _Out of the box._
- Disable spell check inside of ``` blocks. _As I understand, it can be done, if needed._
- Don't check words at cursor, so user doesn't get ""Misspelled"" words while typing is in progress. _Dunno about this._


Current status: 
I can manual build it on Windows with hunspell. Spellchecking work in tdesktop with auto language detection and user dictionary. It's almost fit my requirements, and this is the main reason, thats slow down my further work on this :)

My thoughts:
- I will add enable/disable spellchecking in context menu.
- localisation? Sonnet uses qt localisations (*.qm files).
- If needed, I can wright (complicated :( ) instruction of building it on windows.
- Sonnet uses system context menu, so if we need menu like in tdesktop, we need modify sonnet's code again...

So, If community need it, we can try _together_ bring it to official client. If not, as I said above, it's almost fit my (and friends of me) requirements :)

**Comment by stek29** [comment]
@kirsan31 TDesktop isn't typical Qt app and is heavily customized, especially in the UI.

I don't want to use Sonnet because it's a wrapper which is good for Qt apps but isn't good for TDesktop.

Also, whole way TDesktop's message input box works needs to be refactored, with proper formatting handling, and only then spellchecking should be integrated.

> Sonnet uses system context menu, so if we need menu like in tdesktop, we need modify sonnet's code again...

But my code already had it working...

**Comment by kirsan31** [comment]
@stek29 

> TDesktop isn't typical Qt app and is heavily customized, especially in the UI.
> 
> I don't want to use Sonnet because it's a wrapper which is good for Qt apps but isn't good for TDesktop.
> 
> Also, whole way TDesktop's message input box works needs to be refactored, with proper formatting handling, and only then spellchecking should be integrated.

I totally agree with you. But there is so much to be done. And _language auto detection_, as for me, is very important, and not such a simple thing... :( So, I wash my hands off :))))

> But my code already had it working...

Sonnet uses its own menu with some logic. So, I can use it as is, or modify it in the source. Or not using it and wright my own, as you suggest :)

**Comment by artnikbrothers** [comment]
Why we don't have such basic stuff @TELEGRAM?!

**Comment by akharitonov** [comment]
Just out of curiosity, why not the built in spellchecking capabilities of an OS?

Both macOS and Windows 8.1\10 expose the needed functionality to developers.

[macOS: Checker](https://developer.apple.com/documentation/appkit/nsspellchecker).

[Windows: Spell Checking API](https://docs.microsoft.com/en-us/windows/desktop/Intl/spell-checker-api), specifically [ISpellChecker](https://docs.microsoft.com/en-us/windows/desktop/api/spellcheck/nf-spellcheck-ispellchecker-comprehensivecheck).

I used both in my projects with little to no issues. It's rather convenient and easy to integrate. Why not just use these APIs in Telegram instead of going through all of the hassle of integrating some 3rd party libraries when the functionality is ready and available in the OS itself?

**Comment by Kyrluckechuck** [comment]
I'd actually really like to know this, it's such a basic feature.. 

I mean Android at least is able to override it and give you spelling suggestions, but there's no reason not to use the default OS one as @akharitonov pointed out (or have an option for it) if you're not going to integrate a spellcheck library!

**Comment by stek29** [comment]
> but there's no reason not to use the default OS one

Default one doesn't just work magically, it needs to be supported explicitly

**Comment by ibnzUK** [comment]
This is crazy. 
Many people around the world are not able to use desktop application just because of spellcheck.
The only workaround is to use web version but it is not as slick as desktop and lacks many functions. 

Also, this has been asked since 2014 and still no solution been implemented. I don't understand how devs missed such a simple function.

**Comment by mehargags** [comment]
I'm very new to Telegram, but my life revolves around supporting clients on Skype, Slack, WhatsApp and Line. I'm shocked such a polished and mature platform doesn't have spell check on its desktop app.

**Comment by VasekTryba4eB** [comment]
Coz telegram is 100% shit!

**Comment by Thomanji** [comment]
What a stupid comment, 100% shit because of spellcheck?
I think we all agree that we prefer Telegram to big brother WhatsApp or 
the google crap they they to force down our troughs. It would just be 
nice to have spellcheck also on the desktop.
The APP is 100% great !!!

**Comment by SpeMarX** [comment]
Totally agree. 

Spellchecking is a sad omission and it's why I use the web version instead, but that's no reason to hate on Telegram as a whole.

**Comment by Kyrluckechuck** [comment]
Agreed.

It's funny though where priorities lie; Discord for example has had basic Spell Checking since pre-alpha despite it being multi-platform since the start (the only unfortunate part being we can't see how they did it since it's closed-source)

**Comment by hsiktas** [comment]
While it as other drawbacks I just use web.telegram.org on the desktop via Chrome's new PWA integration. It has its own icon in the taskbar/dock and spell checking works as expected.

**Comment by mmiscool** [comment]
I feel that this is a needed feature. Why it not here?

**Comment by Sutarat66** [comment]
เมื่อ พฤ. 31 ม.ค. 2562 เวลา 23:46 Michael Molinari <notifications@github.com>
เขียนว่า:

**Comment by TechLoom** [comment]
The desktop app is great, but missing this basic feature is sad. Any reason why this QT library can't be used? https://github.com/manisandro/qtspell

For now, the web client works. But would ❤️ to see spell checking in the desktop app!

**Comment by bruiseviolet** [comment]
This feature is about the only drawback to using the desktop version for me.  I am embarrassingly bad at spelling, and dislike not having this feature.

**Comment by QUPS** [comment]
I tried getting my coworkers to use Telegram, they did for about 6 months but got sick of spelling errors. They are not back on hangouts! 🤦‍♂️

I want to use Telegram, I love it, lack of spell checking is so annoying though, and makes it hard to promote to my coworkers and techie friends.

**Comment by papemco** [comment]
guess telegram is for those who dont care about spellings at all. :smile:

**Comment by RyanNerd** [comment]
Why is this closed when it is obviously still an issue?

**Comment by rx65m** [comment]
> I am working on integrating [sonnet](https://github.com/KDE/sonnet) now...And I can say, that properly static build it on windows with hunspell plugin and hunspell itself, it's not a trivial (at least for me :) ) task...
> It's working for now, but I'm not sure that, I will can bring it to a state where it will be ready for integration into tdesktop :(
> ![spelling](https://user-images.githubusercontent.com/17767561/39496908-53811184-4da9-11e8-96dc-e35ca2596ec3.gif)

I can not find **QTextEdit** on Telegram Directory to edit it as you suggest on https://github.com/KDE/sonnet

Is possible for you to guide me?
Thanks in advance.

**Comment by kirsan31** [comment]
@rx65m 

> I can not find QTextEdit on Telegram Directory to edit it as you suggest on https://github.com/KDE/sonnet
> 
> Is possible for you to guide me?
> Thanks in advance.

I think you can find it [here](https://github.com/kirsan31/tdesktop).

**Comment by rx65m** [comment]
> @rx65m
> 
> > I can not find QTextEdit on Telegram Directory to edit it as you suggest on https://github.com/KDE/sonnet
> > Is possible for you to guide me?
> > Thanks in advance.
> 
> I think you can find it [here](https://github.com/kirsan31/tdesktop).

Thanks a lot for your kindness! I honestly appreciate it.
However, if QTextEdit is a file, there is no QTextEdit in there either.

**Comment by kirsan31** [comment]
@rx65m You can compare this repo with one I have linked, to find where all changes need to go...

**Comment by pandages** [comment]
Windows 10 provides this function at the OS level but it doesn't work within Telegram, probably because of the windowing strategy used (my speculation).

**Comment by Patribu** [comment]
Are there some positive developments on this? This is a crucial function now-a-days that is really missing in TelegramDesktop4Windows
Cheers

**Comment by RobinRaawr** [comment]
I also would like to show my interest in this feature. Thanks!

**Comment by pandages** [comment]
As a result of the lack of this feature, I’ve started using a different TDlib implementation, Unigram, which is a modern windows app and works perfectly.  Can genuinely recommend.

Kaishi Axon

**Comment by Kyrluckechuck** [comment]
@pandages thank you for that recommendation, I'm already loving the contact-pin-integration (pinning a specific contact to the taskbar) and likely will stay switched over for the spellcheck. This is now something I'll create as a separate feature request if it doesn't already exist for this implementation, though it likely will never happen due to it being so platform-specific.

**Comment by abrambailey** [comment]
Weird, why is this closed? It seems spell check is still not working... I am on 5.8.1 Stable on MacOS.

**Comment by abrambailey** [comment]
It seems spell check is still not working... I am on 5.8.1 Stable on MacOS.

This issue is closed due to there being a duplicate, but the duplicate is closed and locked, with no resolution. Confused.

**Comment by john-preston** [comment]
@abrambailey Spellcheck works in version 1.9 beta. 5.8.1 is not Telegram Desktop. You can try Telegram Desktop from https://desktop.telegram.org

**Comment by abrambailey** [comment]
I'm confused about this... Tried installing it... not seeing squiggly lines ... 

![image](https://user-images.githubusercontent.com/978462/68329843-c4cc3380-0097-11ea-9f18-9195d6306163.png)

**Comment by abrambailey** [comment]
I cannot find the 1.9 beta anywhere.

**Comment by john-preston** [comment]
@abrambailey In settings - advanced you can enable autoupdate to beta.

**Comment by abrambailey** [comment]
OK, I got it working, and can see spellcheck works now. Thanks! 

Sorry for the n00b question here, but can someone explain the difference between Telegram Desktop 1.9 and the version of Telegram (Swift) I was using previously ... available here: https://macos.telegram.org/ or here https://rink.hockeyapp.net/apps/6ed2ac3049e1407387c2f1ffcb74e81f

**Comment by RememberTheAir** [comment]
@abrambailey tdesktop is a qt app meant to work on all three major operating system. The MacOS app is just a goodie from Telegram who thought it would be nice to have a native MacOS app with a bit more freedom and some nice additions that are not available on tdesktop, like secret chats

**Comment by vjeko** [comment]
No Linux support?

**Comment by RememberTheAir** [comment]
@vjeko https://github.com/telegramdesktop/tdesktop/issues/96#issuecomment-550201078

**Comment by ColeRominger** [comment]
1.9.2 beta works for me! Thank you for saving me from my typos and keeping me looking professional!

**Comment by mxxcon** [comment]
What is the release schedule for this client? I'm interested in spellcheck feature and would like to know how soon it'd be available in stable version?

**Comment by Kieruss** [comment]
1.9.3 "Enjoy system spell checker support on all modern systems"
Got my hopes up, but I'm guessing Windows 7 isn't considered modern? :(

**Comment by Aokromes** [comment]
over 10 years old os? nope.

**Comment by x-ji** [comment]
For tdesktop on MacOS, the spellchecking is there, but it seems to only check the English dictionary, no matter what input method I used to input the text? Normally in other apps an auto detection happens, so that the dictionary corresponding to the input method is used (e.g. German, Spanish), but here it doesn't seem to be the case?

**Comment by Kieruss** [comment]
> 
> 
> over 10 years old os? nope.

My how time flies, and I still hate Win10. Now I feel like one of those people that wouldn't let go of Win XP :cry: 

Is the spell checking via Windows 10 built-in spell checker? :disappointed:

**Comment by john-preston** [comment]
@Kieruss Windows 8 and later has spell checker API in system and it is used in tdesktop.

**Comment by Aokromes** [comment]
> > over 10 years old os? nope.
> 
> My how time flies, and I still hate Win10. Now I feel like one of those people that wouldn't let go of Win XP 😢
> 
> Is the spell checking via Windows 10 built-in spell checker? 😞

you can make windows 10 to look quite like windows 7

https://i.imgur.com/RiOAUMY.png

**Comment by maxoku** [comment]
Hmm, this [comment](https://github.com/telegramdesktop/tdesktop/issues/96#issuecomment-550201078) suggests like there should be spell checking for Win7. 
Will it be added or the current spellchecker system is final?

**Comment by 23rd** [comment]
Windows 7 does not really have spell check support and adding it to the tdesktop requires extra effort. =(

**Comment by Aokromes** [comment]
> Hmm, this [comment](https://github.com/telegramdesktop/tdesktop/issues/96#issuecomment-550201078) suggests like there should be spell checking for Win7.
> Will it be added or the current spellchecker system is final?

microsoft stops giving support to windows 7 this month, almost any computer running windows 7, update.

**Comment by maxoku** [comment]
@23rd @Aokromes 
Your posts don't answer my question.

**Comment by Kieruss** [comment]
> you can make windows 10 to look quite like windows 7

Its looks are the least of its problems. Its awfulness isn't just skin deep.  I'll stick with Win7 until I have no choice, and then it's off to Linux.. or OSX.

> Hmm, this comment suggests like there should be spell checking for Win7.
It would certainly be nice. Everything else about Telegram is awesome. It's just this one missing feature.

**Comment by jxs** [comment]
not working for me on KDE on archlinux: KDE 5.17.4 and telegram 1.9.3.
 I have the option to enable system spell check but nothing happens, no underlined wrong words spell and no spellchecking option on  right click.
@ColeRominger did you install any other package besides enchant? when you right click do you have the option for spell checking?
thanks

**Comment by cyclinggeorgian** [comment]
spellcheck works on opensuse TW (plasma) in every language for which myspell libraries are installed. nice, telegram harvesting on system capabilities.
although spell correction suggestions are provided only for english.

**Comment by maxoku** [comment]
@cyclinggeorgian 
> although spell correction suggestions are provided only for english.

Or it shows all corrections for English at top and there is no space for suggestions from other languages like it was described [here](https://github.com/telegramdesktop/tdesktop/issues/6767)?

**Comment by cyclinggeorgian** [comment]
> @cyclinggeorgian
> 
> > although spell correction suggestions are provided only for english.
> 
> Or it shows all corrections for English at top and there is no space for suggestions from other languages like it was described [here](https://github.com/telegramdesktop/tdesktop/issues/6767)?

no, no.. it definitely doesn't "cap" anything. it just shows me only english word(s).
