### ISSUE TITLE
Searching emojis by typing in the search box is horrible in the Mac client

### ISSUE THREAD

**Issue by erfanz** [telegramdesktop/tdesktop#4629]
### Steps to reproduce
1. Open the emoji panel
2. Choose an emoji (or not, it's not important) 
3. Click on the normal text box (where you write your message)
4. Start writing something

### Expected behaviour
The expected behaviour is that the writing text appear in the text box. 

### Actual behaviour
Instead, the text appears in the search box of emojis.

### Configuration
**Operating system:**
Mac OS High Sierra

**Version of Telegram Desktop:**
3.8.118914 Stable

**Used theme**:
Dark

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by erfanz** [comment]
ohhh I see. Thank you for pointing that out. I just followed your link and downloaded the Telegram Desktop.
One question though, which client is the official one? And do you know from which source I downloaded that app?

**Comment by erfanz** [comment]
@john-preston ohhh I see. Thank you for pointing that out. I just followed your link and downloaded the Telegram Desktop.
One question though, which client is the official one? And do you know from which source I downloaded that app?

**Comment by john-preston** [comment]
@erfanz Both are, you can see them on the main page of https://telegram.org

**Comment by erfanz** [comment]
@john-preston Thanks

**Comment by stek29** [comment]
You can submit issues and suggestions related to another client in https://t.me/macswift chat.
