### ISSUE TITLE
Telegram not support indic language fonts.

### ISSUE THREAD

**Issue by jskcse4** [telegramdesktop/tdesktop#463]
I'm using telegram in android, windows and Linux platforms....
I found an issue is that the telegram not support Tamil fonts only in Liunx platform, even i use my system language in Tamil.

I found this problem in both Ubuntu 14.04 and Fedora 21(Not in windows and Android).

**Comment by sridher** [comment]
Not supporting Telugu fonts also. I am using telegram in android, wp8.1, iPad and Linux. only Linux (Ubuntu 14.10) has this problem. Other apps on Ubuntu supporting the telugu fonts.

@jskcse4 Chnage the issue title to indian language fonts.

**Comment by telegramdesktop** [comment]
Should be better in version 0.7.16.

**Comment by gnbcreations** [comment]
> Should be better in version 0.7.16.

please share think link are application?

**Comment by Aokromes** [comment]
try on 2.1.12
