### ISSUE TITLE
menu fails to stay open [right click]

### ISSUE THREAD

**Issue by cryptoatropine** [telegramdesktop/tdesktop#4630]
### Steps to reproduce
1.  run program 
2.  right click to bring up menu  [will disappear immediately]
3.  continue to right click finally it will stay open 

### Expected behaviour
i think this is self explanatory the menu should work every time

### Actual behaviour
The menu closes...   on click ... hold click or hold move click 
 

### Configuration
Defaults 

**Operating system:**

Sparky linux -- Stable - testing hybrid -- Running enlightenment 22.3 -- base system Debian 9
using apparmor, and nftables ... apparmor is currently complain mode for Telegram ... so not the cause of this issue ..... nftables is my firewall .... but it's happy .... 

I would gladly help out more if i can, just send me a message ...  

**Version of Telegram Desktop:**

1.2.17

**Used theme**:
Defaults 

i would do this, however  i see no place to type in debugmode in settings ... 
from command line ?? 

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by cryptoatropine** [comment]
probably related to this is the also links fail to open, on click or right click .... the work around i have been using is clipit copy selection feature.  ctrl C also works ..... but the menu is broken ..... err mostly broken .. it dose stay open about 2 % of the time ...

**Comment by stek29** [comment]
You haven't mentioned your OS info.

**Comment by cryptoatropine** [comment]
in regards to this though, i have seen now that the menu is the same in the top right, so i guess it's not a big deal,

**Comment by stek29** [comment]
Do you have "proper" window manager? Right click pop-up is usually drawn in separate window and composition happens on WM side rather than app side.

**Comment by cryptoatropine** [comment]
Enlightenment  is my WM .... newest .. and actually playing around with it, i think it is a focus issue with enlightenment.......  sometimes if i open the tab side bar ... the menu will all of a sudden start working as it should, until telegram is minimized....   

sorry about slow responses i don't always have net ...

**Comment by paolomeraviglia** [comment]
@cryptoatropine how did you solve this issue? I am with debian 10 and enlightenment 22

**Comment by ilya-fedin** [comment]
I have the same issue with Telegram 1.5.3, Arch and Enlightenment 22

**Comment by gecheim** [comment]
I have the same issue with Telegram 1.8.15, Enlightenment Version: 0.22.3
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
