### ISSUE TITLE
10-second pc freeze on opening an image for the first time

### ISSUE THREAD

**Issue by pavlukivan** [telegramdesktop/tdesktop#4635]
### Steps to reproduce
1. install a 2-core cpu
2. open an image ¯\\\_(ツ)\_/¯

Note that it will freeze only for the first time

### Expected behaviour
PC not freezing (i.e. app freeze only)

### Actual behaviour
PC freezing

### Configuration
**CPU:** Intel Core i7-4600U

**Operating system:** win7x64

**Version of Telegram Desktop:** 1.2.17

**Used theme**: dark

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4559 ?

**Comment by pavlukivan** [comment]
not sure, in my case it doesnt crash and loads image fine

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by pavlukivan** [comment]
I use a different pc right now so I can't test it, feel free to close it
