### ISSUE TITLE
Windows 10 1803 - Quiet Hours doesn't mute notification sounds

### ISSUE THREAD

**Issue by Armin2208** [telegramdesktop/tdesktop#4641]
With Windows 1803 Microsoft added a new Feature to Windows, the focus assist, also known as quiet hours. Before the update, you could just activate and deactivate the quiet hours. With the new Version, you have two options: only alarms, and with priority. But with both options enabled, I still hear the telegram notification sound. Notifications are hidden.

I think the desktop app needs some fixes for the newest Windows Version.

Thank you!

**Comment by pchigrin** [comment]
This feature is high demanded. Thanks in advance.

**Comment by dogancelik** [comment]
Notifications were working fine before this version update (1803) but after this update, notifications have stopped working completely (no sound, no toast) even when Quiet Hours / Focus Assist is disabled.

### Focus Assist (after version 1803)
![focus-assist](https://user-images.githubusercontent.com/486818/40881296-9d08057a-66cb-11e8-9671-90b215be10f3.jpg)

### Settings
![settings](https://user-images.githubusercontent.com/486818/40881297-9f0d2814-66cb-11e8-847d-5b7c741e1408.jpg)

**Comment by Tourniquet88** [comment]
I've just upgraded to 1803 and also experience the same problem. 

Please fix this, it's very annoying.

**Comment by john-preston** [comment]
@Tourniquet88 Latest Windows 10 changed API, instead of Quiet Hours there is now Focus Assist for which I don't know how to get it's state (enabled / disabled).

Quiet Hours were using a registry key, but Focus Assist does not, so the old way doesn't work.

**Comment by arieljannai** [comment]
Just adding that the focus assistant has 2 options (at least for now) - priority only, alarms only. So they can handled differently if the user wants (and possible easily)

**Comment by szukai** [comment]
It's now 2019. This would be nice to fix

**Comment by john-preston** [comment]
@szukai PRs welcome. In the earlier versions Windows stored quiet hours setting in registry and tdesktop could read it. Now I don't know where to read it.

**Comment by topharley** [comment]
> @Tourniquet88 Latest Windows 10 changed API, instead of Quiet Hours there is now Focus Assist for which I don't know how to get it's state (enabled / disabled).
> 
> Quiet Hours were using a registry key, but Focus Assist does not, so the old way doesn't work.

This can help: https://github.com/bitdisaster/windows-focus-assist/blob/master/lib/focus-assist.cc

**Comment by tooomm** [comment]
Please, somebody look into this! ❤️

**Comment by Aokromes** [comment]
maybe this can help
https://stackoverflow.com/questions/53407374/is-there-a-way-to-detect-changes-in-focus-assist-formerly-quiet-hours-in-windo

**Comment by xenstar** [comment]
it's not fixed yet, 2020 going on

**Comment by OlegDobriy** [comment]
This bug still exists. Please fix it.

**Comment by Armin2208** [comment]
You guys should disable the Telegram notification sound completely if you can.

**Comment by escape0707** [comment]
Hi lovely @stale bot! You asked me why this issue is staled, but I would like to ask you, too! 😉

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/2730ab1596b897c921e99d33242626f5aa2c01eb
