### ISSUE TITLE
add Tor in Tdesktop

### ISSUE THREAD

**Issue by instapost** [telegramdesktop/tdesktop#4642]
hi
is it possible you add [Tor client](https://www.torproject.org/download/download.html.en) to Telegram Desktop?
Or other similar services like Tor 
telegram has recently Blocked in Iran.

Help us, Iranian users.

**Comment by f242** [comment]
@instapost 
Download https://www.torproject.org/dist/torbrowser/7.5.3/tor-win32-0.3.2.10.zip
Unpack and run tor-win\Tor\tor.exe (minimize window, don't close) Also you can install it as service
Open Telegram settings and set proxy TCP with custom socks5-proxy hostname 127.0.0.1 and port 9050

**Comment by instapost** [comment]
@f242 
thank you. I know personally
But many Iranian (or Russian) users do not know
So if the tor client (Or similar tor) add to Telegram client It would be great and convenient for users.

Regards.

**Comment by DevAlone** [comment]
@instapost, I think it's not necessary. As for me, it would be better to add p2p network which would allow to bypass almost any stupid goverment's block as well as make telegram less centralized, with p2p network some kinds of traffic can go without telegram servers, like public media in channels for example.

**Comment by instapost** [comment]
@DevAlone YES, This is a great idea and I know the telegram is working on it. (With BlockChain)
But launching the service p2p takes months.
currently telegram is block. And it's important now,
because every time it passes, the number of users gets lower (users go to use of WhatsApp or Other Messangers). 

This is a war....

**Comment by Startname** [comment]
@instapost If they add tor to tdesktop is very good 😲
We also provide financial support even if necessary

___

Also Please add Ability Support of Multiple proxy improvements like Telegram X ios and Telegram macOS

**Comment by sorankurds** [comment]
Unfortunately, recently the telegram has blocked in Iran.
Please, like Russia provide a non-filterable version for Iran.

**Comment by stek29** [comment]
Use instructions provided by @f242

**Comment by stek29** [comment]
Also #4599 duplicate

**Comment by Mori79** [comment]
Here's a step-by-step guide on how to circumvent Internet censorship with Tor on different operating systems:
https://sites.google.com/view/howtos/how-to-circumvent-internet-censorship-with-tor

Hope it helps!
