### ISSUE TITLE
Comma in proxy address, why it allowed?

### ISSUE THREAD

**Issue by Monoroch** [telegramdesktop/tdesktop#4646]
### Steps to reproduce
1. Replace dot in proxy address, on comma

### Expected behaviour
1. Don't allow it
2. Or auto replace comma to dot

### Actual behaviour
Application save settings and can't connect

### Configuration
**Operating system:**
Win 10
**Version of Telegram Desktop:**
1.2.17
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.19.

**Comment by BugLight** [comment]
I would like to solve this issue. I am going to create custom input for host (and inherit it from Ui::MaskedInputField) instead of regular Ui::InputField. Should I replace commas with dots? Should I replace spaces also?
