### ISSUE TITLE
Slow start on Fedora 28

### ISSUE THREAD

**Issue by gtirloni** [telegramdesktop/tdesktop#4647]
### Steps to reproduce
1. Install Fedora 28
2. Install Telegram 
3. Open Telegram

### Expected behaviour
Telegram should open under 10sec.

### Actual behaviour
Takes over 1min to start on a fast laptop. 

It seems to be stuck in a loop reading font files:

```
stat("/usr/share/fonts/adobe-source-han-serif-cn/SourceHanSerifCN-Medium.otf", {st_mode=S_IFREG|0644, st_size=11364128, ...}) = 0
openat(AT_FDCWD, "/usr/share/fonts/adobe-source-han-serif-cn/SourceHanSerifCN-Medium.otf", O_RDONLY) = 16
fcntl(16, F_SETFD, FD_CLOEXEC)          = 0
fstat(16, {st_mode=S_IFREG|0644, st_size=11364128, ...}) = 0
mmap(NULL, 11364128, PROT_READ, MAP_PRIVATE, 16, 0) = 0x7fa5c9985000
close(16)                               = 0
munmap(0x7fa5c9985000, 11364128)        = 0
```

### Configuration
**Operating system:**
Fedora 28 x86_64

**Version of Telegram Desktop:**
1.2.17

**Used theme**:
Default

"debugmode" doesn't create logs anywhere.

**Comment by stek29** [comment]
#4543

**Comment by gtirloni** [comment]
@stek29 I should have noticed that, sorry. The extra data point is that yesterday, on Fedora 27, it was not happening. But I'm not entirely sure if I was already on 1.2.17.

**Comment by xvitaly** [comment]
@gtirloni Use packaged version from RPMFusion. It works fine.
