### ISSUE TITLE
[wish] Ability to remove group messages locally

### ISSUE THREAD

**Issue by denizzzka** [telegramdesktop/tdesktop#4648]
Please add ability to remove messages locally from groups.

There was an unpleasant situation when an unacceptable picture was posted to a business group and it hung for a while until the moderators reacted without the possibility to hide it locally.

**Comment by stek29** [comment]
Sorry, has to be implemented properly on server side (and is likely a dupe, I think)
Currently such thing is only possible in normal groups (not supergroups).
