### ISSUE TITLE
Titlebar of maximized window behaves weird on Windows 10 Version 1803

### ISSUE THREAD

**Issue by levrik** [telegramdesktop/tdesktop#4649]
### Steps to reproduce
1. Open Telegram on Windows 10 Version 1803
2. Unmaximize window if isn't already
3. Maximize window

### Actual behaviour
![image](https://user-images.githubusercontent.com/9491603/39540898-6280835e-4e44-11e8-92c9-59380ab117c4.png)
_(see the control buttons at the right; yes, the close button is almost completely out of scope. it's **not** cut off the screenshot)_

Also it looks like the Window is hiding behind the task bar. Normally that one looks more dark.
![image](https://user-images.githubusercontent.com/9491603/39540959-92b4316a-4e44-11e8-85d2-c2a01ff709d5.png)

Initial start as maximized window looks completely normal. As soon as I unmaximize and maximize the window again the issue occurs. It can only be fixed by restarting Telegram.

As mentioned below by @lightlessfilms you can work around this issue by running Telegram in Windows 8 compatibility mode.

### Configuration
**Operating system:** Windows 10 Version 1803
**Version of Telegram Desktop:** 1.2.17

### Additional information

It seems like there's some issue with custom title bars in the new Windows version. Spotify, Discord and Slack are having similar issues. Notable here is that unlike Telegram these apps can "fix itself". If the window got into this state you can just unmaximize and maximize again. If you repeat that again after fixing it's broken again.

![image](https://user-images.githubusercontent.com/9491603/39541047-d5121fea-4e44-11e8-9e31-5d2b52720eb8.png)
![image](https://user-images.githubusercontent.com/9491603/39541066-e0c8abf6-4e44-11e8-8961-31ba5bb2f10a.png)
![image](https://user-images.githubusercontent.com/9491603/39835242-e0fdeede-53cf-11e8-9fe2-76a54e2166de.png)

**Comment by daedalus01** [comment]
Might be related to #4428

**Comment by Pomazan-Bogdan** [comment]
+1

**Comment by stek29** [comment]
> It seems like there's some issue with custom title bars in the new Windows version. Spotify and Discord are having similar issues.

Is "version" 1803 considered stable by MS?

**Comment by levrik** [comment]
@stek29 I think so. Got it via Windows Update yesterday. I'm **not** signed up to the Insider program.

**Comment by stek29** [comment]
@levrik 
Indeed, looks like it went to stable at April 30, according to https://www.howtogeek.com/340688/whats-coming-in-windows-10s-redstone-4-update-available-march-2018/

> Why the " around version?

Because I don't know much about Windows, and just quoted your words :)

Windows is weird *shrug*

I was asking because you mentioned that other apps have issues too -- maybe it's a bug on MS side and should be fixed by them.

**Comment by stek29** [comment]
@levrik I agree :)

**Comment by lightlessfilms** [comment]
The maximized window also overlaps to the second monitor
![2018-05-03 17_40_03-](https://user-images.githubusercontent.com/7137900/39587133-1403968e-4ef9-11e8-828a-3e949f8e8f94.png)

**Comment by wwevo** [comment]
What's the downside of the compatibility mode then?

**Comment by Poolitzer** [comment]
@wwevo does there always have to be one?

**Comment by wwevo** [comment]
Nah, there usually is one though, only my experience. so far I haven't encountered any ^^ Workaround seems to work around the issue just fine

**Comment by Timmyfox** [comment]
Can we expect any more permanent fix that doesn't require workarounds?

**Comment by ChildishGiant** [comment]
Workaround is working great. This also works for discord, whatsapp and loads of other apps with custom title bars.

**Comment by Timmyfox** [comment]
I'm sure it is but it's still a workaround that needs to be done by every single end user; Surely there's a better solution that prevents the bug from happening at all and won't cause trouble for less tech savvy people too?

**Comment by john-preston** [comment]
@Timmyfox I would like to know that solution. I don't know yet how to fix that in code.

**Comment by lightlessfilms** [comment]
@john-preston , @Timmyfox 
I could be wrong here, but I think that this is an issue that needs to be fixed by Microsoft.  
As mentioned by @ChildishGiant this also affects Discord, Whatsapp with custom title bars.
So I believe the DWM (Desktop Window Manager) is at fault here. I could be totally wrong here

**Comment by ChildishGiant** [comment]
It's on Window's

**Comment by john-preston** [comment]
Even Chrome for someone:

https://news.softpedia.com/news/the-maximized-window-bug-is-the-most-annoying-thing-in-windows-10-version-1803-521320.shtml

If anyone has a in-code (C++ / anything?) workaround, I'll be happy to look into it.

**Comment by Aokromes** [comment]
Microsoft already fixed this on RS5, maybe on next days it will be fixed on RS4 (1803)

**Comment by levrik** [comment]
Todays cumulative Windows update didn't fix this issue. I had hopes...

**Comment by mmatrosov** [comment]
Telegram 1.3.10. Bug is still there.

**Comment by weekendjoy** [comment]
why is this simple problem not fixed yet?

**Comment by john-preston** [comment]
@weekendjoy Because it is a Windows bug and there is no known workaround.

**Comment by wwevo** [comment]
Use the compatibility mode for now. Fixes all those pesky visual bugs and has no downside so far. At least not for me.

**Comment by TopperDEL** [comment]
I've just received the mentioned update and can indeed confirm that this solves the issue!

**Comment by ChildishGiant** [comment]
Can also confirm that KB4340917 fixes this. issue can be closed then :)
