### ISSUE TITLE
Offical PPA

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#465]
I found a PPA for Telegram desktop (https://launchpad.net/~atareao/+archive/ubuntu/telegram)

Does it an official one OR It's better to use the binaries from https://desktop.telegram.org/ ?
In case it's official PPA why the maintainers didn't announce about it in the official website?!

PS I'm using Linux Mint x64 17.1

**Comment by nmabhinandan** [comment]
waiting for the answer!!

**Comment by mxa** [comment]
not an answer to the question, but you don't really need the PPA, because the Telegram client takes care of the updating itself.

**Comment by mbnoimi** [comment]
Using package manager for updating process is way perfect than local updater of Telegram client.

I think Telegram updater is suitable to Windows distro but it's not actually for Linux because Linux distros have advanced package managers while Windows not.

**Comment by ezdev128** [comment]
I'm agree with @mbnoimi. I'm not fan of PPA (rather that I would prefer distro-specific package manager) but seems updater is not good solution either.

**Comment by AsavarTzeth** [comment]
I normally agree that official native packages are preferred. But in this case it works just as well the Telegram (or Steam) way. I just extract the archive to ~/.local/share/telegram, run it, copy/link .desktop file to ~/.config/autostart and I am good.

In the end, a PPA would only solve this issue for Ubuntu users. This would then likely be followed by requests by every other distro user. I think the best we could wish for is to get this containerized in the future and wait for the general systemd based package manager :)
