### ISSUE TITLE
Desktop client rings after PC hibernation

### ISSUE THREAD

**Issue by LibertyPaul** [telegramdesktop/tdesktop#4651]
### Steps to reproduce
1. Have a Telegram on PC running Linux (maybe other platforms are affected as well) and on mobile device (iPhone in my case)
2. Put a PC in a hibernation ("Suspend" in Ubuntu terminology)
3. Get an incoming call and don't answer it
4. Wake a PC from hibernation

### Expected behaviour
PC client should not ring for outdated call

### Actual behaviour
When PC wakes up in rings as if call is running now, but actually it was hours in the past.
It stops to ring only after I log in into OS and open Telegram window.

### Configuration
**Operating system:**
Ubuntu GNU/Linux 16.04 x64

**Version of Telegram Desktop:**
1.2.17

**Used theme**:
Don't know. It is black.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by LibertyPaul** [comment]
Please hold on, I will try to reproduce and reply.

**Comment by LibertyPaul** [comment]
The bug does not reproduce.
Let's close the issue then.
Thank you.
