### ISSUE TITLE
Telegram Desktop 1.2.17 cannot connect, even after clearing data directory

### ISSUE THREAD

**Issue by abacabadabacaba** [telegramdesktop/tdesktop#4652]
### Steps to reproduce
1. Remove data directory (`~/.local/share/TelegramDesktop`).
2. Launch Telegram.
3. Try to log in.

### Expected behaviour
It should be possible to log in.

### Actual behaviour
After I enter my phone number and press "Next", nothing happens. "Connecting..." is written in the bottom left corner.

### Configuration
**Operating system:** Debian GNU/Linux 9.4

**Version of Telegram Desktop:** 1.2.17

**Used theme**: default

<details><summary><b>Logs</b>:</summary>

[log_15_45.txt](https://github.com/telegramdesktop/tdesktop/files/1976827/log_15_45.txt)
[log_16_00.txt](https://github.com/telegramdesktop/tdesktop/files/1976828/log_16_00.txt)
[mtp_15_45.txt](https://github.com/telegramdesktop/tdesktop/files/1976829/mtp_15_45.txt)
[mtp_16_00.txt](https://github.com/telegramdesktop/tdesktop/files/1976830/mtp_16_00.txt)
[tcp_15_45.txt](https://github.com/telegramdesktop/tdesktop/files/1976831/tcp_15_45.txt)
[tcp_16_00.txt](https://github.com/telegramdesktop/tdesktop/files/1976832/tcp_16_00.txt)
</details>

**Comment by stek29** [comment]
Please try 1.2.18

**Comment by abacabadabacaba** [comment]
I checked 1.2.20, and the issue appears to have been fixed there.

**Comment by rehmanali007** [comment]
> 1. ~/.local/share/TelegramDesktop
Not working for me. Still having same problum.
