### ISSUE TITLE
What is MTProto Proxy

### ISSUE THREAD

**Issue by Startname** [telegramdesktop/tdesktop#4653]
### Steps to reproduce
1.  What is MTProto in Proxy setting? There is no explanation/Description on the telegram site..
Where should get Values hostname, port, secret ?

### Configuration
**Operating system:** win 10

**Version of Telegram Desktop:** 1.2.18 alpha

**Used theme**: any

**Comment by john-preston** [comment]
@Startname This is a type of proxy specially for Telegram. It is not released yet, sorry.

**Comment by Startname** [comment]
@john-preston thank you.
in iran socks5 not work. (all ports is block)
so MTProto Proxy Can it work?. 
Please give a happy news. We, Iranians love the telegram and we do not want to leave it 😔

**Comment by lrinQVQ** [comment]
@Startname Hi,http proxy can work in Iran
Hostname: 185-122-58-249.googlehosts.org
Port: 80
No authentication required

**Comment by ffallah** [comment]
Iran has advanced DPI (Deep Packet Inspection) hardware, If MTProto is separable from usual SSL or HTTP traffic, it is already doomed to fail. the only solution is to obfuscate Telegram traffic into legitimate SSL traffic.

**Comment by sa3er** [comment]
@john-preston 
It is released sir. In the **alpha version**. Everyone can now download it here:
https://desktop.telegram.org/changelog#alpha-version

Would you please tell us where we can get reliable MTProto Proxies?
.
Screenshot:
<img src="https://i.imgur.com/ZfGIMr5.png">

**Comment by auchri** [comment]
@sa3er https://t.me/MTProtoProxies

**Comment by john-preston** [comment]
@sa3er I released that alpha version :) I mean the mtproto proxy software is not released officialy, not a version of a client app, that will use this software.

**Comment by sa3er** [comment]
None working here.
https://i.imgur.com/NYBc2gn.png

I also tried to create my own server using the instructions at:
https://t.me/MadelineProto/348
Tried various ports including 80 and 443. Yet, no luck.

But for some weird reason, when I turn off "Use Proxy" and leave the "Try connecting through IPv6" the connection to Telegram servers establishes successfully and I can send and receive messages, the speed is very low though,

**Comment by ShafiqSadat** [comment]
@john-preston 
Can they rfilter MTProxy?

**Comment by ffallah** [comment]
@sa3er I think those servers are down, none work for me as well and I am not behind filtering.

**Comment by ffallah** [comment]
@ShafiqSadat I think they can ! but only time will tell.

**Comment by ShafiqSadat** [comment]
@ffallah  So HTTP proxy needs to be released for mobile version !!!
And of course a non-filterable protocol for all OSs

**Comment by ShafiqSadat** [comment]
Exception (p):          Wrong protocol version in Proxy.php:61

**Comment by samenta** [comment]
I tested in #Iran and not work . 
https://t.me/proxy?server=62.210.93.229&port=443&secret=c1a7177aae441df73b336f2dfc1e2f83

**Comment by samenta** [comment]
![sadasdasd](https://user-images.githubusercontent.com/37240038/39883000-735c1020-543a-11e8-9176-d4c30491d4ca.png)

**Comment by samenta** [comment]
how i can find MTproto proxy list ?

**Comment by instapost** [comment]
@samenta 
https://t.me/MTProxy
