### ISSUE TITLE
if anyone know please help, thanks

### ISSUE THREAD

**Issue by Painkiller1991** [telegramdesktop/tdesktop#4654]
hi, i use AddContactBox::onSave() in other function but do not call AddContactBox::onImportDone after finishing his work??

what i missing??? My goal is saving contact without showing the UiBox??

what i see clicking on Create button just call onSave function but not work my way, why??

**Comment by Lonami** [comment]
Er… why is this open? Not quite a bug with tdesktop itself but rather using its code…

**Comment by stek29** [comment]
inb4 op is author of iranian fork violating gpl

**Comment by Lonami** [comment]
@Painkiller1991 don't take @stek29's joke wrong. It was simply a joke. The issue was strange and a strange comment was made.
