### ISSUE TITLE
Message textbox clears twice after sending a message

### ISSUE THREAD

**Issue by ahmadalli** [telegramdesktop/tdesktop#4656]
### Steps to reproduce

1. send a message using a slow and unstable internet connection (like what we have here in Iran right now)
2. start typing another message immediately (without sending it)

### Expected behavior

Your new message must remain intact.

### Actual behavior

After a little time, the textbox (and your new message) clears unexpectedly. It seems textbox.clear calls twice in two different events (like when user hits enter and after the client receives the success message from the server) and causes this issue.

### Configuration

**Operating system:** Windows 10 1803

**Version of Telegram Desktop:** 1.2.17

**Used theme**: Not related

**Comment by stek29** [comment]
Press ctrl+z. It's caused by how drafts work. Search for "draft" to see more issues with deeper explanation.

**Comment by stek29** [comment]
should be fixed
