### ISSUE TITLE
#bug changelog disappear

### ISSUE THREAD

**Issue by RedMoonOTInetwork** [telegramdesktop/tdesktop#4657]
what happened to the changelog? every time the client updates, it no longer appears as before

**Comment by Aokromes** [comment]
works for me (TM)
https://i.imgur.com/R6XO4hE.png

**Comment by RedMoonOTInetwork** [comment]
Not for me, TDesktop on Windows

**Comment by xvitaly** [comment]
@Aokromes Restart client. It will disappear. This is a feature, not a bug. :-)

**Comment by RedMoonOTInetwork** [comment]
@xvitaly no it's bug, Before the chat with the changelog appeared, now it appears for a millisecond and then disappears

**Comment by Aokromes** [comment]
#4525

**Comment by RedMoonOTInetwork** [comment]
ah so according to Preston is normal does not appear?

**Comment by MasterGroosha** [comment]
There is definitely something wrong with changelog message.
![image](https://user-images.githubusercontent.com/2780044/41119528-acaccc80-6a9b-11e8-9500-3e1da1374de2.png)

After update it flickers for a moment and "sinks" down in chat list. So the only way to see this message is either scroll down the chat list or click the notification.
TDesktop 1.3.3 alpha, Windows 10.
