### ISSUE TITLE
Middle name of contact is not displayed

### ISSUE THREAD

**Issue by sgielen** [telegramdesktop/tdesktop#4658]
I share a Telegram account between Telegram Desktop and my iPhone. I guess my contact's names are taken from my phone, and displayed in Telegram Desktop as well. However, it looks like part of the name is missing: the middle name.

I'm not sure how the contact sharing works exactly, so take my "steps to reproduce" with a grain of salt.

### Steps to reproduce
1. On iPhone with Telegram installed, add contact with a middle name. For example, the common Dutch name "Jan de Vries" would be entered as first name "Jan", middle name "de", last name "Vries". (It's similar to entering "de Vries" as last name, but mostly the alphabetic sorting would be wrong.)
2. In Telegram on iPhone, the full name "Jan de Vries" is displayed.
3. Now, open the contact in Telegram Desktop.

### Expected behaviour
The name of the contact in the chat should show as "Jan de Vries".

### Actual behaviour
It shows as "Jan Vries", so the middle name is missing.

### Configuration
**Operating system:**
Desktop: macOS High Sierra (10.13.4)
Phone: iPhone 7 with iOS 11.3 (not sure if that one's relevant)

**Version of Telegram Desktop:** 1.2.17

**Used theme**: default

**Comment by stek29** [comment]
Telegram only has first and last names, sorry.

**Comment by sgielen** [comment]
Hmm, could you perhaps provide some more details? Is this something missing in the Telegram back-end, and would it be possible for me to file a bug there? Or is it a priority thing to not include this information when retrieving contacts locally? (Excuse my ignorance, I don't really know how Telegram gets its contact information.)

**Comment by stek29** [comment]
>  Is this something missing in the Telegram back-end

Yes, and API too. There are First name, Last name and phone number, no middle name or any other info.

> would it be possible for me to file a bug there?

Yup, using Twitter or in-app support you can request this feature, but I don't think it'd be accepted.

> Or is it a priority thing to not include this information when retrieving contacts locally

It's just not possible to do it.
Maybe iOS app can fit middle name into first name or last name, but it's kinda hacky.
