### ISSUE TITLE
[feature request]: Type the emojis from keyboard

### ISSUE THREAD

**Issue by dgronskij** [telegramdesktop/tdesktop#4659]
When typing from a desktop client, looking for a specific emoji may be frustrating. Use of "recently used emojis" is restricted due to 

1. small recently used emoji's list capacity
2. lists across different devices seem not to share recently used emojis with each other
3. context switch between keyboard and the mouse

It would be really great to have a text nomenclature for emoji's that would lead to fast emojis input with the keyboard only and no use of huge emojis lists. Slack messenger does this and feels just fantastic.

For example , when you type `:+1:`, it suggests to replace this string with a "thumbs up" emoji (in fact, there is a suggestion window rising even earlier)

How it's done in Slack:
<img width="511" alt="slack_emoji_from_keyboard" src="https://user-images.githubusercontent.com/12527959/39699422-c987fba2-5201-11e8-8720-73f7d84a9fa7.png">

**Comment by john-preston** [comment]
@dgronskij It is in tdesktop already, you need to switch "Replace emoji" on in Settings.

**Comment by dgronskij** [comment]
@john-preston , wow, sorry then, thank you! Maybe an extra "text value" helper popup (when mouse is over the emoji inside emoji's list) would be helpful? Case: you want to type the emoji from the keyboard, but do not know the "magic `:....` value)
