### ISSUE TITLE
Last seen sometimes isn't update!

### ISSUE THREAD

**Issue by rezapc** [telegramdesktop/tdesktop#466]
hi please fix this problem that last seen of contacts sometimes shows temporarily incorrectly.

**Comment by auchri** [comment]
Is this still the case? If yes, reopen the issue

**Comment by bram85** [comment]
This is still the case. This happens when a machine wakes up from suspend/sleep, for the contacts that have sent messages during that time. The application thinks that the contacts are online at the moment that the machine wakes up.
