### ISSUE TITLE
VS 2017 build fails. After VS update to 15.7?

### ISSUE THREAD

**Issue by kirsan31** [telegramdesktop/tdesktop#4661]
After last VS 2017 update ( 15.6.7 > 15.**7**), I can't build  tdesktop anymore.
The error is:

> tdesktop\telegram\sourcefiles\rpl\event_stream.h(76): error C3779: 'rpl::event_stream<Value>::events': a function that returns 'auto' cannot be used before it is defined.   

rpl::event_stream<Value>::events:
```cpp
auto events() const {
    return make_producer<Value>([weak = make_weak()](
            const auto &consumer) {
        if (auto strong = weak.lock()) {
            auto result = [weak, consumer] {
                if (auto strong = weak.lock()) {
                    auto it = std::find(
                        strong->consumers.begin(),
                        strong->consumers.end(),
                        consumer);
                    if (it != strong->consumers.end()) {
                        it->terminate();
                    }
                }
            };
            strong->consumers.push_back(std::move(consumer));
            return lifetime(std::move(result));
        }
        return lifetime();
    });
}
```
template from producer.h:
```cpp
template <
	typename Value = empty_value,
	typename Error = no_error,
	typename Generator,
	typename = std::enable_if_t<
		std::is_convertible_v<
			decltype(std::declval<Generator>()(
				details::const_ref_consumer<Value, Error>())),
			lifetime>>>
inline auto make_producer(Generator &&generator)
#ifdef RPL_PRODUCER_TYPE_ERASED_ALWAYS
-> producer<Value, Error> {
#else // RPL_CONSUMER_TYPE_ERASED_ALWAYS
-> producer<Value, Error, std::decay_t<Generator>> {
#endif // !RPL_CONSUMER_TYPE_ERASED_ALWAYS
	return std::forward<Generator>(generator);
}
```
Auto template function inside other auto function ... And why it all worked before? My knowledge of the cpp definitely is not enough - help needed :)

**Comment by john-preston** [comment]
@kirsan31 I'm going to update soon. But I'm a bit mad. This code works in all previous versions of msvc, in gcc and in clang. Now MS tells that it finely conforms with the standard and stops building my code :(

**Comment by kirsan31** [comment]
@john-preston Thank you. Today morning I was very surprised too :)))

**Comment by john-preston** [comment]
@kirsan31 For now you can replace "auto events() const {" with "producer<Value> events() const {" and it works.

Also you'll need to disable warning 4180, otherwise QMap<bool(*)(), smth> throws a warning about "const Ptr*" with Ptr being a pointer to a function.

But this is a regression :( I hope I'll find time to prepare a minimal example to reproduce that and submit it to msvc team.

**Comment by john-preston** [comment]
@kirsan31 I've replied using a bot and didn't see that comment was killed by markup parser. Thanks for the clarification.

**Comment by zgl1990** [comment]
@john-preston  I have already solved,thank you。
