### ISSUE TITLE
Adaptive layout option disappears when window size is reduced

### ISSUE THREAD

**Issue by ojura** [telegramdesktop/tdesktop#4662]
Using 1.2.17 on Ubuntu 18.04. I thought I was crazy the other day - I knew that the option for toggling the adaptive layout for wide screens is there, but couldn't find it. Realized just now that it's only there if the window is expanded. Might be better just to show it all the time to avoid unintentionally [gaslighting](https://en.wikipedia.org/wiki/Gaslighting) people. :-)

**Comment by stek29** [comment]
That's a feature

**Comment by stek29** [comment]
#2465
