### ISSUE TITLE
Telegram Desktop closes itself

### ISSUE THREAD

**Issue by SadeSEFKATLiNiN** [telegramdesktop/tdesktop#4663]
### Steps to reproduce
1. Open a lot of program at ubuntu 18.04

### Expected behaviour
Telegram Desktop closes itself.

### Actual behaviour
It should just work...

### Configuration
**Operating system:** Linux x64 Ubuntu 18.04

**Version of Telegram Desktop:** 1.2.17

![image](https://user-images.githubusercontent.com/8404792/40023419-b62d861c-57d3-11e8-8dd1-3954222f384e.png)

**Comment by WiRight** [comment]
I have the same bugs few times in ubuntu 14.04, but now i am in debian 9.3 and it work ok (telegram version 1.2.17)
(sorry for my bad english)

**Comment by stek29** [comment]
does it still happen?

**Comment by WiRight** [comment]
@stek29 in latest updates (1.2.20 aplha) all ok

**Comment by RAHMANINkolesi** [comment]
it is not released yet at : https://telegram.org/dl/desktop/linux
it is already 1.2.17, when new stable verison released at telegram.org

**Comment by humpity** [comment]
Linux Lubuntu 12.04 (yes, yes i know..)

Updated from 1.2.1 to 1.2.17.
Same behaviour, same message.

Went back to 1.2.1. removed Updater. Skipped the update. Back to normal.

**Comment by Aokromes** [comment]
1.4 works fine for me on ubuntu 18.04 if you have a crash i sugest to run telegram with gdb to see how it crashes doing the following:
gdb ./telegram
run
if it crashes:
bt
bt full
use pastebin or gist to paste result of crash.

**Comment by atk91** [comment]
@Aokromes
I think that is happening to me as well
stacktrace is here
https://gist.github.com/atk91/a1130d3569e6e0deaa431adc8b5c3b36

**Comment by Aokromes** [comment]
@atk91 you missed bt full.

**Comment by GiorgioBelli** [comment]
Same Error on Linux Min 19

here the gdb output
https://pastebin.com/nwgBi5vx

**Comment by Aokromes** [comment]
on @GiorgioBelli case it looks spell checker is the reason.

#9  0x000000000102008a in enchant::Dict::check(std::string const&) ()

**Comment by Aokromes** [comment]
your is more https://github.com/telegramdesktop/tdesktop/issues/7086

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
@SadeSEFKATLiNiN @atk91

**Comment by atk91** [comment]
I haven't noticed it for a long time, so maybe it is not

**Comment by Aokromes** [comment]
closing then, if someone gets new crashes plz send crash report and create new ticket with the crash id.
