### ISSUE TITLE
Messages are read automatically after reaching idle status

### ISSUE THREAD

**Issue by MetalDroid** [telegramdesktop/tdesktop#4664]
### Steps to reproduce
1. Open a conversation with any user.
2. Keep the application and that same chat in the foreground.
3. After a few minutes without using the computer, wait for them to write you in that chat. Your status will change to "online" and your messages will be marked as read.

### Expected behaviour
After reaching the idle time, the messages should not be read. This happens while the computer screen is on.

### Actual behaviour
The messages are read when reaching the idle time if the application is in the foreground and the screen is on.

### Configuration
Ubuntu 18.04 and Linux Mint 18.3

Version of Telegram Desktop: 1.2.17

**Used theme**: default theme

<details><summary><b>Logs</b>:</summary>
No logs

</details>

**Comment by cauebs** [comment]
This is not only surprising but can also be an issue when people leave their PCs on and contacts are incorrectly informed that messages are read, leading to silly misunderstandings.

Could someone more familiar with the codebase land a fix for this or is there any obstacle to fixing it?

**Comment by tooomm** [comment]
>This (...) can also be an issue when people leave their PCs on

Also, in this situation:
This leads to notifications not getting send to mobile devices. So you don't get informed about new messages and your contacts think you even read them!

**Comment by steog88** [comment]
same problem. I always leave the desktop in my office on, and often I fail to receive notifications on the mobile when I am home, because the conversation is marked as "read".

**Comment by jublair** [comment]
Issue is also reproducible on Windows. Messages are being marked as read when Telegram Desktop is the active window, even when the PC is locked.

**Comment by MetalDroid** [comment]
This bug is partially fixed. 

I say partially because currently (v1.9.21 beta) what it does is change my status to offline after 30 seconds of inactivity regardless of whether the window has focus or if the screen is On / Off / Locked.

I think this new behavior is still inappropriate, instead it should be:

If the screen is On and the tdesktop window is focused then stay online.

If the screen is Off / Locked or the tdesktop window is not focused, then switch to offline.

I suppose this behavior has not been applied due to other difficulties in the different types of desktop, I am sorry I cannot be of further help.
