### ISSUE TITLE
bug icon proxy 

### ISSUE THREAD

**Issue by Startname** [telegramdesktop/tdesktop#4666]
### Steps to reproduce
1. show two icon proxy when open a channel.

<img src="http://uupload.ir/files/rx55_132122132122.png" alt="img" height="350" width="1000">

### Configuration
**Operating system:** win 10

**Version of Telegram Desktop:** 1.2.19 alpha

**Used theme**: any

**Comment by ThigSchuch** [comment]
Same here, with groups too.

I think it would be better to show Proxy Icon besides Lock Icon, between Search bar and Lock. Resize a little Search Bar and include Proxy there.
The way it's now, I guess it is some kind hidden.

**Comment by MasterGroosha** [comment]
@ThigSchuch or it may be placed in left menu header, where you have your avatar, phone number and "saved messages icon"

**Comment by ThigSchuch** [comment]
@MasterGroosha I thinked there too, but the intention is see the icon all the time. And there you will do a click to see it.
