### ISSUE TITLE
Proxy icon visual bug

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#4668]
### Steps to reproduce
1. Open app with default theme and proxy turned on
2. Switch theme to "night" one.
3. Look at the icon

### Expected behaviour
Proxy icon should be coloured respectively

As a small suggestion, I think proxy icon can be moved to the left menu and placed by the "saved messages" icon in menu's header (next to your name and phone number)

### Actual behaviour
![icon bug](https://i.imgur.com/pqm1YxX.png)

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.2.19 alpha
**Used theme**: Original/Night

**Comment by john-preston** [comment]
@MasterGroosha Thanks for the report.

I think if you're not a geek and have enabled a proxy through a link you should see an indicator of that change and have a way to disable it right in front of you, not somewhere inside the menu.

**Comment by MasterGroosha** [comment]
Fair enough
