### ISSUE TITLE
Block a MTProxy ?

### ISSUE THREAD

**Issue by instapost** [telegramdesktop/tdesktop#4670]
Can governments block MTProxy? with Knowing IP a MTProxy?
Because For some channels sending MTProxy that All of them are visible IPs and Ports.

If TDesktop (or other clients) get/receive automatic MTProxy of servers google and to connect it what?(Encrypted for Invisible By governments. string ip, port and secret) 
___________
I know this should be in APIs telegram But it's really hard to send Comments and suggestions
to the telegram managers.

**Comment by ffallah** [comment]
Well, everyone is so excited about this new MTProto Proxy !
Be patient until Telegram releases the MTProto Proxy Server officially and we will see how it works and if it can be blocked or not.

**Comment by stek29** [comment]
Has nothing to do with TDesktop.
And yes, knowing MTProto proxy ip is obviously enough to block it.
