### ISSUE TITLE
Easier way to figure out what theme color controls what

### ISSUE THREAD

**Issue by JuanPotato** [telegramdesktop/tdesktop#4671]
Just wondering if there is a good way to figure out what color is controlling what elements in a theme.

**Comment by stek29** [comment]
You mean keys to where they actually are used?

**Comment by JuanPotato** [comment]
I mean, if I see something in tdesktop, it isn't too straight forward to find out what key in the theme controls its color. Having something that showed what is the key responsible for the color of an element would be cool. But at the same time I understand it would probably be annoying to add in.

To give you an idea of what I mean
![image](https://user-images.githubusercontent.com/9531780/39960597-96b5457c-55f3-11e8-9f8f-b0e6079c872d.png)

**Comment by stek29** [comment]
How do you imagine this? A special theme maker mode, which would show what key controls current cursor position point in the corner or tooltip? Or do you have a better idea?

**Comment by JuanPotato** [comment]
I like the idea of it showing what key is used for the color that is under the mouse in the corner. How would it deal with shadows or (semi-)transparent colors?
