### ISSUE TITLE
[feature request] Suggestion for popup when clicking proxy URL

### ISSUE THREAD

**Issue by sadalhayat** [telegramdesktop/tdesktop#4672]
When clicking a proxy URL, it will show popup window to add **and** enable the proxy.
Suggestion, it would be nice if there are: 

1. Option to add/save only without auto-enable it.

2. Proxy check status: checking, not available, available (ping: 123ms)

current version: Telegram Desktop 1.2.19 Alpha
![tdesktop_add_proxy](https://user-images.githubusercontent.com/18193764/39856442-2d2ca4a0-545a-11e8-83c9-0dd7b8451417.png)

**Comment by john-preston** [comment]
@sadalhayat Looks good.
