### ISSUE TITLE
How to tick checkbox using keyboard

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#4673]
![image](https://user-images.githubusercontent.com/7231077/39856778-c6b5e606-544e-11e8-8ed7-081852ee79e0.png)
Is there any shortcut like spacebar?

**Comment by john-preston** [comment]
@SmartManoj Sorry, no :( Currently they don't have keyboard focus at all 🙈

**Comment by SmartManoj** [comment]
Workaround
https://smartmanoj.blogspot.com/2018/10/telegram-shortcuts.html

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7194
