### ISSUE TITLE
The problem of windows Telegram  compilation

### ISSUE THREAD

**Issue by airoam** [telegramdesktop/tdesktop#4675]
1>d:\tbuild\buildpath\tdesktop\telegram\sourcefiles\rpl\event_stream.h(76): error C3779: “rpl::event_stream<Value>::events”: 要使用将会返回“auto”的函数，必须首先定义此函数
1>d:\tbuild\buildpath\tdesktop\telegram\sourcefiles\rpl\event_stream.h(37): note: 参见“rpl::event_stream<Value>::events”的声明
1>d:\tbuild\buildpath\tdesktop\telegram\sourcefiles\rpl\event_stream.h(76): note: 参见对正在编译的 类 模板 实例化 "rpl::event_stream<Value>" 的引用

What is the cause of the compilation problem

**Comment by kirsan31** [comment]
#4661
