### ISSUE TITLE
Resolve param domain doesn't work

### ISSUE THREAD

**Issue by mikekosulin** [telegramdesktop/tdesktop#4676]
### Steps to reproduce
1. Open some any link like this with domain param tg://resolve?domain=durov

### Expected behaviour
Telegram starts
Telegram opens channel/bot/group/userchat

### Actual behaviour
Telegram starts, but doesn't open channel/bot/group/userchat

### Configuration
**Operating system:**
Windows 10 Pro 1709 / 16299.371
**Version of Telegram Desktop:**
1.2.17

**Comment by shaggyrec** [comment]
At linux works, but at windows 10 not

**Comment by stek29** [comment]
Do other tg: links work? (i.e. tg://socks)
