### ISSUE TITLE
Use native macOS notification system for notifications

### ISSUE THREAD

**Issue by eirnym** [telegramdesktop/tdesktop#4677]
Reasoning: macOS have a "Don't distrub" mode, which is completely ignored by current system and custom notifications don't add any new functionality

### Steps to reproduce
1. Enable notifications
2. Receive a message

### Expected behaviour
Tell us what should happen
I see a system notification with some action buttons if required. 

### Actual behaviour
Tell us what happens instead
I see a custom notification which is not controlled by "don't disturb" mode and system wide notification settings.

### Configuration
**Operating system:**
macOS Sierra, macOS High Sierra 

**Version of Telegram Desktop:**
1.2.19

**Used theme**:
light and dark

**Comment by stek29** [comment]
It doesn't use custom notifications on macOS (at least on versions where macOS has it's own Notification Center)

however, do not disturb is ignored indeed and the sound is played (since sound is played by tdesktop app and not by system).

See #3095

**Comment by eirnym** [comment]
@stek29 it's not a true that TD isn't using custom framework to show notifictaions. Probably, it's misconfigured.

Within standart notifications you can't select notification position, notification count and you can't do much with style.

**Comment by stek29** [comment]
@eirnym can you please show a screenshot?

**Comment by john-preston** [comment]
@eirnym It uses custom notifications in versions for Windows and Linux and for OS X 10.6-10.7. If you download the latest version for OS X 10.8 or later it uses only system notifications and custom are not available there.

**Comment by eirnym** [comment]
On this screenshot you can see custom not native notifications. Probably, this is framework misconfiguration or wrong compile options. 

![zrzut ekranu 2018-05-13 o 09 33 22_](https://user-images.githubusercontent.com/485399/39965028-a4c3f1d8-5691-11e8-9cee-059cb5a6c590.png)

**Comment by john-preston** [comment]
@eirnym Where did you take that version? Can you try version from https://tdesktop.com/mac/current?alpha=1 ? I think you've downloaded a build for old OS X versions.

**Comment by eirnym** [comment]
I'm sorry, my bad. why is it impossible to use the single fat binary?

**Comment by john-preston** [comment]
@eirnym Those versions require different Qt library versions.

**Comment by stek29** [comment]
@eirnym Because tdesktop binary is already big enough, and making one universal binary isn’t worth it especially considering how old 10.6 is.

@john-preston I think @eirnym was referring to Mach-O binary format feature allowing to bundle multiple binaries in one FAT binary. You can, for example, make one executable that works on macOS and (jailbroken) iOS.

**Comment by eirnym** [comment]
@stek29 @john-preston Thank you for an explanation. I have no more questions on this topic
