### ISSUE TITLE
VS 2017 v.15.7.1 build error - cannot open file "common.lib" 

### ISSUE THREAD

**Issue by airoam** [telegramdesktop/tdesktop#4678]
Hello. i get this error every time i try to build Telegram project.
1>------ 已启动生成: 项目: Telegram, 配置: Debug Win32 ------
1>ninja: Entering directory `..\out\Debug\'
1>[1/1] LINK_EMBED Telegram.exe
1>FAILED: Telegram.exe Telegram.exe.pdb
1>C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True Telegram.exe "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:Telegram.exe @Telegram.exe.rsp" 1 mt.exe rc.exe "obj\Telegram.Telegram.exe.intermediate.manifest" obj\Telegram.Telegram.exe.generated.manifest
1>LINK : fatal error LNK1104: 无法打开文件“common.lib”
1>Traceback (most recent call last):
1>  File "gyp-win-tool", line 323, in <module>
1>    sys.exit(main(sys.argv[1:]))
1>  File "gyp-win-tool", line 29, in main
1>    exit_code = executor.Dispatch(args)
1>  File "gyp-win-tool", line 71, in Dispatch
1>    return getattr(self, method)(*args[1:])
1>  File "gyp-win-tool", line 179, in ExecLinkWithManifests
1>    subprocess.check_call(ldcmd + add_to_ld)
1>  File "C:\Python27\lib\subprocess.py", line 186, in check_call
1>    raise CalledProcessError(retcode, cmd)
1>subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /OUT:Telegram.exe @Telegram.exe.rsp Telegram.exe.manifest.res' returned non-zero exit status 1104
1>ninja: build stopped: cannot make progress due to previous errors.
1>D:\TBuild\BuildPath\tdesktop\Telegram\Telegram.vcxproj(1234,5): error MSB3073: 命令“call ninja.exe -C ..\out\Debug\ -k0 Telegram”已退出，代码为 1。
1>已完成生成项目“Telegram.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

I've done it in the way of  #2674,  but I still failed to compile it.

Windows 10
Visual Studio 2017 V15.7.1

**Comment by airoam** [comment]
@kirsan31   thank    
   resolved

**Comment by jackstowart** [comment]
i have same issue too. how can i solve it?!

**Comment by lnx252008** [comment]
@jackstowart  
Copy common.lib files from ..\Libraries\breakpad\src\out\Debug\obj\client\windows directory to  ..\Libraries\breakpad\src\out\Debug\obj\client  directory
