### ISSUE TITLE
CPU usage 100% for 20 seconds before app window appears

### ISSUE THREAD

**Issue by K4YT3X** [telegramdesktop/tdesktop#4680]
### Steps to reproduce
1. Just launch telegram

### Expected behaviour
Telegram desktop launches normally just like how other apps do.

### Actual behaviour
CPU usage bumps to 100% for about 20 seconds before the app appears and the CPU goes back to mormal.

### Configuration
**Operating system:**
4.15.0-kali3-amd64 #1 SMP Debian 4.15.17-1kali1 (2018-04-25) x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.2.17

**Used theme**:
DarkOrange v3.01

Will provide logs if necessary.

**Comment by Aokromes** [comment]
#4240 #4543

**Comment by stek29** [comment]
> Will provide logs if necessary.

Please do. better check if it's a duplicate :)

**Comment by K4YT3X** [comment]
@stek29 Two of the other issues did mention that tdesktop is starting up slowly, but they're using different versions on different distros. Therefore firing up a new issue for the newest version might not be the worst idea.

**Comment by K4YT3X** [comment]
```

**Comment by K4YT3X** [comment]
> But I have found now that telegram-desktop is now available in the official Arch repository, and I use this now instead of the binaries distributed by the Telegram team and it hasn’t got this error.

This is how @Socialdarwinist solved his problem. However there's no Arch repo on Kali.

**Comment by Lonami** [comment]
For anyone not wanting to dig through the linked duplicates to find the solution, it's https://github.com/telegramdesktop/tdesktop/issues/4240#issuecomment-388311151.
