### ISSUE TITLE
Keyboard Shortcuts for Telegram (FEATURE REQUEST)

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#4681]
On Ubuntu, one thing that would help use Telegram easily is a menu of options to customize keyboard shortcuts with the different windows Telegrams handle. For example if I had a chat opened with a specific user, holding down the LEFT CTRL would allow me to send an audio recording (Similar to how some games do it). The ability to simply customize keys to specific actions in the telegram app and depending on what window is opened inside telegram at that time. A more of a intuitive approach of merging the usage of Telegram on the desktop to how we go about it on a day by day basis.

The reason behind this idea is that I have moved all my clients to Telegram since August of last year and now that they are all here (Either on Windows, Mac or Linux), for me to communicate faster with them, shortcuts would be a great idea to have.

**Comment by stek29** [comment]
See #1060 and others
