### ISSUE TITLE
Abruptly throw out authorization

### ISSUE THREAD

**Issue by AL3x3y0** [telegramdesktop/tdesktop#4683]
### Steps to reproduce
Idk, it happened suddenly

### Actual behaviour
I'm just chatting and suddenly lose auth, try to login, enter code, password, saw contact list for few seconds and lose auth again, try to login again - error too many attempts. But all is fine on iOS and I got no block (checked it on Spam Info Bot). I don't use any proxy.

### Configuration
**Operating system:** Windows 10 x64 LTSB 1607

**Version of Telegram Desktop:**
1.2.19.0

**Used theme**:
Default

<b>Logs</b>:
https://pastebin.com/GK26MCPH

**Comment by jcrush2** [comment]
OS Linux. confirm.

**Comment by john-preston** [comment]
@jcrush2 Please try logging in again, it should work now. Sorry for the problem.

**Comment by jcrush2** [comment]
fix

**Comment by stek29** [comment]
It was a temporary issue which is now fixed on server side. Sorry for inconvenience.
