### ISSUE TITLE
logout after crush OS Linux

### ISSUE THREAD

**Issue by jcrush2** [telegramdesktop/tdesktop#4686]
Telegram desktop 1.2.x (OS Arch Linux).
after the OS crush, logout.

**Comment by john-preston** [comment]
@jcrush2 Please try logging in again, it should work now. Sorry for the problem.

**Comment by jcrush2** [comment]
@john-preston No, this is another problem, the output is after the crush OS.

this problem for 1 year already.

**Comment by jcrush2** [comment]
after this all the settings of Telegram are skipped by default.

**Comment by Aokromes** [comment]
#3963
