### ISSUE TITLE
STOP FUCKING CHANGE <3 TO THE HEART EMOJI

### ISSUE THREAD

**Issue by SurDno** [telegramdesktop/tdesktop#4687]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

Steps to reproduce
1. START HATING EMOJI
2. DOWNLOAD TELEGRAM DESKTOP
3. START HATING TELEGRAM DESKTOP

Expected behaviour
IT SHOULD NOT CHANGE <3 TO THE HEART EMOJI. 

Actual behaviour
IT CHANGES <3 TO THE HEART EMOJI

**Comment by SurDno** [comment]
FUCKING DUPLICATE OF FUCKLING #3738

FUCKING CLOSED

**Comment by TacoTheDank** [comment]
kek

**Comment by john-preston** [comment]
@SurDno It was always replacing it if you had Replace emoji enabled in Settings.
