### ISSUE TITLE
build and dynamically link?

### ISSUE THREAD

**Issue by Geremia** [telegramdesktop/tdesktop#4688]
These [build-instructions](https://github.com/telegramdesktop/tdesktop/#build-instructions) require compiling all dependencies from source and statically linking. Is there a way to build Telegram and dynamically link it?

**Comment by stek29** [comment]
There's no officially supported way to dynamically link to most of the dependencies, sorry.

**Comment by Geremia** [comment]
@stek29 Why is statically linking the official build procedure?

**Comment by john-preston** [comment]
@Geremia So that anyone could download a version from site and it just works.
