### ISSUE TITLE
[Feature request] Systray icon choice

### ISSUE THREAD

**Issue by nplezka** [telegramdesktop/tdesktop#469]
I would request and suggest a systray icon choice, like qBittorrent, from two or three types: the blue-coloured one, the monochromatic one for dark themes and the monochromatic one for light themes. It would be great expecially for us with Ubuntu Unity or Gnome Shell, for a clean panel (or notification bar) 
![schermata del 2015-02-03 21 35 48](https://cloud.githubusercontent.com/assets/10550382/6028840/b2bc9fea-abec-11e4-9ee4-af34d5975d36.png)
(In the screenshot I run a Gnome Shell extension for appindicator support)

**Comment by franksouza183** [comment]
I agree, I think the Telegram could keep the default icon if not found a corresponding status icon on the current icon theme. ![Print of Telegram tray icon](http://i.imgur.com/WwIi597.jpg)

**Comment by Ghokun** [comment]
I started something for Numix icon theme

https://github.com/Ghokun/telegram-numix-tray-icons

**Comment by NikoM87** [comment]
#419
