### ISSUE TITLE
Adding smiles in a pitcure description

### ISSUE THREAD

**Issue by kolayne** [telegramdesktop/tdesktop#4690]
If you're sending a picture, there is no way to add a smile in it's description, because you can't use the smile panel when you're writing it

**Comment by Lonami** [comment]
Latest versions let you type a message (including emoji), and upon pasting the image, the text will be used as a caption. This issue is not relevant anymore.

**Comment by stek29** [comment]
@Lonami so, paste image, realize you want emoji, cancel, type emoji, paste again?

**Comment by Lonami** [comment]
@stek29 currently the caption is entered in a popup. I can't see how you could do it in Desktop without said popup, and there how would you add emoji?. Just get used to first entering the message and then adding the image.
