### ISSUE TITLE
TDesktop loses sync after supergroup reincorporation

### ISSUE THREAD

**Issue by ariel-** [telegramdesktop/tdesktop#4692]
### Steps to reproduce
1. Get invited to a supergroup
2. Get kicked from that supergroup
3. Make sure there are new messages in that supergroup and get a reinvite
4. You won't get any messages until you restart TDesktop. Works fine on Android client.

### Expected behaviour
TDesktop should sync messages when you are reinvited

### Actual behaviour
It gets stuck and any messages received on the meanwhile and new messages are not shown

### Configuration
**Operating system:** Windows 10 1803 x64

**Version of Telegram Desktop:** 1.2.20 alpha

**Used theme**: Dark Accent Red v2

<details><summary><b>Logs</b>:</summary>
No logs

</details>

**Comment by ilya-fedin** [comment]
#1772
