### ISSUE TITLE
Play/Pause Behavior

### ISSUE THREAD

**Issue by ThigSchuch** [telegramdesktop/tdesktop#4693]
### Steps to reproduce
1. Have a keyboard with this butoms:
![image](https://user-images.githubusercontent.com/20743110/40078605-742d6bfa-585b-11e8-8de4-50e5efaeb7ae.png)

2. Play some song in Telegram.
![image](https://user-images.githubusercontent.com/20743110/40078686-b50bab14-585b-11e8-9c90-f5c04c584b21.png)

3. Next and Previous butom, works, ok.
4. Play and Pause, not.
5. Maybe, I guess, can be limited hardware or Windows fault, because neither of those butoms work with app in second plane.

### Expected behaviour
Play or Pause song.

### Actual behaviour
Little break.

### Configuration
**Operating system:**
Windows 8.1

**Version of Telegram Desktop:**
1.2.20 alpha

If helps, some people on 1.2.17 reported it works.

There is other post like this, but in 2017, a year ago.
[Play/pause button on keyboard doesn't work as expected](https://github.com/telegramdesktop/tdesktop/issues/3342)

**Comment by stek29** [comment]
Does it work in other apps?

**Comment by stek29** [comment]
#3342
