### ISSUE TITLE
Emoji replacement in media captions broken

### ISSUE THREAD

**Issue by nyuszika7h** [telegramdesktop/tdesktop#4698]
### Steps to reproduce
1. Send an image or video.
2. Type an emoji short code such as `:joy:` in the caption.. 

### Expected behaviour
It should be replaced with the emoji, assuming "Replace emoji" is enabled.

### Actual behaviour
It isn't replaced at all. This is caused by commit 4b763a7.

### Configuration
**Operating system:** Windows 10 Home x64 (1709)

**Version of Telegram Desktop:** 1.1.20 alpha

**Used theme**: Default (night mode)

**Comment by stek29** [comment]
Related: #4500

**Comment by 23rd** [comment]
Looks like that was fixed.
