### ISSUE TITLE
[Feature request] keyboard shortcut first message, last message

### ISSUE THREAD

**Issue by mdan312** [telegramdesktop/tdesktop#4699]
I suggest using Home, End keys to navigate to first / last message of the current chat (when message edition is empty, cf up/down arrow usage)

**Comment by stek29** [comment]
What's the point of navigating to first message?

**Comment by mdan312** [comment]
Usefulf when in a project group where you share documents and information

**Comment by stek29** [comment]
Aren’t #tags and pinned messages/replies better?

**Comment by mdan312** [comment]
Well #tags and pinned messages are also useful but it is something different. It is useful when dealing with many correspondants to be able to get to the first message to

**Comment by a-sitnik** [comment]
If **Home** can be debated therewith consuming lot of resources on accidental use on large history chats, **End** is obvious and critically needed. There is already software button, all you need is bind it's function.

**Comment by nickaein** [comment]
The `End` key is currently bind to text editor and can be confusing to users. 
Some other combination (e.g. `Ctrl+End`) would be much better.

**Comment by SmartManoj** [comment]
Scroll to bottom button is available for last message.
For first message, adding Beginning button in calendar search

**Comment by SmartManoj** [comment]
> What's the point of navigating to first message?

To see about of bot #6189 6189

**Comment by SmartManoj** [comment]
https://github.com/Sea-n/tdesktop/blob/86783898397b6cf32d0dc9c2f733dfbd4701ed29/Telegram/SourceFiles/window/window_peer_menu.cpp#L845-L851

**Comment by SmartManoj** [comment]
Available in https://github.com/TDesktop-x64/tdesktop
