### ISSUE TITLE
Telegram is closed from time to time

### ISSUE THREAD

**Issue by kipusoep** [telegramdesktop/tdesktop#47]
I'm running into an issue with Telegram. From time to time I check for the icon in het notification bar and notice it's missing; Telegram is completely closed.
I don't know why this is happening for me, maybe it's got something to do with using the standby mode in Windows?
I recently re-installed my laptop and the problem is still there.

**Comment by telegramdesktop** [comment]
I've fixed some issues, I hope this is not happening anymore (test on the latest version, 0.7.10 for current moment).

**Comment by kipusoep** [comment]
Thanks, I'll test the new version :+1:
