### ISSUE TITLE
Typing ":o" doesn't bing the smiley anymore in 1.2.20 alpha

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#4700]
### Steps to reproduce
1. type ":o " (note the space)
2. enter

### Expected behaviour
Should get an emoji

### Actual behaviour
we got the text ":o"

### Configuration
**Operating system:**
Windows 
**Version of Telegram Desktop:**
1.2.20 alpha
**Used theme**:
custom theme

This is because:
https://github.com/telegramdesktop/tdesktop/blob/4b763a76df514c6f98bc588b66b8df070ec66d85/Telegram/SourceFiles/codegen/emoji/data.cpp#L60

why the need of typing ":ok" without space after ":" ?

after the emoji suggestion panel, I already had to add an extra space to get the correct emoji (I got :o: emoji instead). 

Since 1.2.20, I can't type the ":o" emoji at all.

**Comment by john-preston** [comment]
@Geobert :ok is a start of an emoji replacement. If you replace :o instantly you can't type :ok if you want :ok: or :ok_hand:

**Comment by Geobert** [comment]
I see, can we have ":o " (with trailing space) as a workaround then? As we had anyway to add the space to avoid :O: witch was automatically selected in the suggestion box

**Comment by stek29** [comment]
@john-preston Indeed, what about requiring additional whitespace character for non-:: emoji replacements?
The only issue I can see is handling them in the message end.

**Comment by john-preston** [comment]
@stek29 You want only to return :o or to require space in some other replaces as well?

**Comment by stek29** [comment]
@john-preston I think that requiring whitespace makes sense for other replacements too

**Comment by Geobert** [comment]
Fixed in 1.2.21 alpha! Thanks!

**Comment by stek29** [comment]
@john-preston Is :o in the end of message not considered as an issue?

**Comment by john-preston** [comment]
@stek29 I don't think it is. You can press space and get the emoji.

**Comment by Geobert** [comment]
I confirm it works at the end of a message :)
