### ISSUE TITLE
[Feature Request] Audio Equalizer

### ISSUE THREAD

**Issue by achigo16** [telegramdesktop/tdesktop#4701]
I love play music on telegram and I think it's will more better if telegram make this one

**Comment by arifnurdiansyah92** [comment]
Telegram is chat app, not music player

**Comment by royryando** [comment]
This can be useful for user so Telegram will be the default audio player with more audio experience

**Comment by royryando** [comment]
just start your contribution on this repo @achigo16

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4640
