### ISSUE TITLE
It closes itself when you plug in usb microphone while making telegram voice call

### ISSUE THREAD

**Issue by SadeSEFKATLiNiN** [telegramdesktop/tdesktop#4703]
### Steps to reproduce
1. Make telegram call to someone from telegram desktop app
2. Plug in usb microphone while making telegram voice call

### Expected behaviour
It should change usb microphone automatically without closing telegram desktop app nor voice call

### Actual behaviour
It closes telegram desktop app(so also voice call)

### Configuration
**Operating system:** Ubuntu 18.04

**Version of Telegram Desktop:** 1.2.17

**Comment by stek29** [comment]
#2478

**Comment by RAHMANINkolesi** [comment]
@stek29 you closed this but @zaps166 's operating system and steps to reproduce of error is different

in his case it is closing even you connect mouse even you did'nt make telegram voice call,

but in my case at ubuntu 18.04 it is closing only with usb microphone camera connection only while you making voice call on telegram

**Comment by stek29** [comment]
If it's a different issue, please provide more info.

Does it crash? Does it suggest you to send crash log on next start?

**Comment by RAHMANINkolesi** [comment]
yes it suggesting,
I have opened "debugmode" in telegram desktop but where I can find .log file created by errors?

**Comment by stek29** [comment]
@RAHMANINkolesi report the crash and post crash report tag here

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
