### ISSUE TITLE
Disable mark every message as read on open chat

### ISSUE THREAD

**Issue by as3mbus** [telegramdesktop/tdesktop#4704]
### Steps to reproduce
1. Have a thousand of unread message on a group chat
2. going to read several hundred at a time.
3. clicked the group chat

### Expected behaviour
like in android counterpart. it should only mark the message as read for displayed message  

### Actual behaviour
It mark every message as read 

### Configuration
**Operating system:**
Arch Linux 64 Bit
**Version of Telegram Desktop:**
Telegram 1.2.17
**Used theme**:
I forgot
<details><summary><b>Logs</b>:</summary>
i believe log isn't necessary

</details>

**Comment by stek29** [comment]
#775
