### ISSUE TITLE
Feature Request: automatic response to incoming calls

### ISSUE THREAD

**Issue by BlackWarriorNT** [telegramdesktop/tdesktop#4705]
In Skype there is a function of automatic response to incoming calls. Is this functionality possible in Telegram?

**Comment by royryando** [comment]
Telegram can run on as many devices and for this feature there must be a condition. So which particular one would telegram check the condition?

**Comment by BlackWarriorNT** [comment]
for example, enter toggle "respond automatically" in the settings of a particular client

**Comment by stek29** [comment]
What kind of response? Pick up automatically? Deny and send a message?

**Comment by BlackWarriorNT** [comment]
@stek29 yes, **Pick up automatically**

**Comment by stek29** [comment]
It doesn't sound sane to me, but whatever

**Comment by BlackWarriorNT** [comment]
please tell me if you can expect the automatic answer (pick up) function to appear on incoming calls?

подскажите, пожалуйста, можно ли ожидать появления функции автоматического ответа (поднятия трубки) на входящие звонки?
