### ISSUE TITLE
MTProtoProxy on other platforms

### ISSUE THREAD

**Issue by ffallah** [telegramdesktop/tdesktop#4709]
Will MTProtoProxy feature be released on other telegram platforms as well ? or is it an invention of the telegram desktop team and may never see the light on other platforms ?
I would appreciate if u shed some light on this feature and availability.

**Comment by Aokromes** [comment]
Non telegram desktop related issue.

**Comment by stek29** [comment]
It already is available in beta versions of other tg apps.
And as @Aokromes mentioned, it has nothing to do with tdesktop..
