### ISSUE TITLE
Unable to open URLs in messages

### ISSUE THREAD

**Issue by vodolaz095** [telegramdesktop/tdesktop#4711]
### Steps to reproduce
1. click any http or https link in any message
2. Error thrown, but URL not opened in browser 

### Expected behaviour
URL opened.

### Actual behaviour
Error like this displayed

![URL not opened](https://vodolaz095.life/s/AYyepzaKg.png)

`/home/username/.TelegramDesctop/http://example.org: No such file or directory`

### Configuration
**Operating system:**
Fedora release 27 (Twenty Seven). LXDE spin

**Version of Telegram Desktop:**
1.2.17.

Name         : telegram-desktop
Version      : 1.2.17
Release      : 2.fc27
Arch         : x86_64
Size         : 38 M

stack  version from distro repos

**Used theme**:
default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by vodolaz095** [comment]
it is worth notice, that error started to manifest previous week

**Comment by stek29** [comment]
Is xdg-open able to open links?

**Comment by vodolaz095** [comment]
![https://vodolaz095.life/s/F376kGl3U.png](https://vodolaz095.life/s/F376kGl3U.png)

Seems like its xdg-open issue, even if firefox is set... What can it be than?

**Comment by royryando** [comment]
look at this

**Comment by royryando** [comment]
Try this: [AskUbuntu - Where to change how xdg-open opens urls? sync with kde-open?](https://askubuntu.com/questions/788043/where-to-change-how-xdg-open-opens-urls-sync-with-kde-open?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

**Comment by Aokromes** [comment]
maybe it's linux bug?

**Comment by royryando** [comment]
You need to use double quote `xdg-open "https://cont.ws"`

**Comment by Aokromes** [comment]
btw, i can click urls without problem on ubuntu 18.04.

**Comment by stek29** [comment]
It’s defin something wrong on your system. If xdg-open and other tools start opening urls correctly but tdesktop still would have issues, feel free to comment on this issue.

**Comment by vodolaz095** [comment]
@royryando 
![https://vodolaz095.life/s/mR5MQm5g6.png](https://vodolaz095.life/s/mR5MQm5g6.png)
the same.

@stek29 
so ok, prob its xdg-open bug... unrelated to telegram,but, tbh, quite irritating for me.

**Comment by stek29** [comment]
@vodolaz095 I know, and I'm sorry, but I have no idea on how it works and how to fix it. And the last time I used Linux desktop was more than 1.5 years ago :(
