### ISSUE TITLE
Add a way to send quickly a message to a contact

### ISSUE THREAD

**Issue by MartinDelille** [telegramdesktop/tdesktop#4712]
### Steps to reproduce

Type a keyboard shortcut (like Cmd+N on OSX)

### Expected behaviour

Open an input field where you can select a contact in order to start a conversation.

### Actual behaviour

Nothing

### Configuration
**Operating system:**

OSX 10.12.6

**Version of Telegram Desktop:**

3.8.2.119501 App Store

**Used theme**:

Clean

I could try implement this but I would like to think about the best way to do it before stepping into the code.

**Comment by stek29** [comment]
> 3.8.2.119501

That’s not tdesktop, that’s another official client for macOS, written in Swift. You can get tdesktop at desktop.telegram.org (or just download another telegram app you see on AppStore)

Btw, there’s a CMD+K shortcut in the app you’re using.

**Comment by stek29** [comment]
Oh, and you can reach out that macOS app dev at https://t.me/macswift.

**Comment by MartinDelille** [comment]
@stek29  Ok cmd+K is doing the job but cmd+N could be a shortcut alias. Where is the swift code for the desktop MacOS app?
