### ISSUE TITLE
It should not ask for permission to able to open folder which has image file

### ISSUE THREAD

**Issue by RAHMANINkolesi** [telegramdesktop/tdesktop#4713]
### Steps to reproduce
1. Receive an uncompressed image file from another telegram contact
2. Right click on downloaded image file and click: "Show in Folder"

### Expected behaviour
It should automatically open folder without asking permission like in windows

### Actual behaviour
It is asking for permission to able to open folder
![image](https://user-images.githubusercontent.com/8404792/40320633-fbff5e98-5d34-11e8-992b-37b08642c8a5.png)

### Configuration
**Operating system:** Ubuntu 18.04 x64

**Version of Telegram Desktop:** 1.2.17

**Comment by d0tfile** [comment]
Looks like this is problem (or feature) of snap package. Is it official? If not, better contact maintainer.

**Comment by RAHMANINkolesi** [comment]
Yes you are right it is really problem of snap package.
I have downloaded from telegram.org and it hasn't any issue like this.
