### ISSUE TITLE
MTProto Proxy connection timeout

### ISSUE THREAD

**Issue by ffallah** [telegramdesktop/tdesktop#4714]
### Steps to reproduce
1. Start a server to listen for MTProto Proxy connections
2. Enter the proxy details in telegram desktop
3. Telegram desktop connects, sends a packet and closes the connection in 500ms

### Expected behaviour
It should wait longer for response from server.

### Actual behaviour
It closes the connection very fast.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.2.21 alpha
**Used theme**:
default
<details><summary><b>Logs</b>:</summary>
root@raspberrypi:~ # time (nc -l 4444)

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

real    0m0.532s
user    0m0.000s
sys     0m0.000s

</details>

### More info
I am writing a MTProto proxy server in nodejs and I noticed sometimes I dont get the chance to respond to telegram desktop proxy requests as it needs to be forwarded to telegram server and forwarded back, it closes the connection too fast.

**Comment by ffallah** [comment]
Actually it was not a bad problem to have! It made me more creative and I resolved it by having a pool of idle established connections to telegram server. so when a new connection from client is received, there would be no delay in establishing a new connection to telegram server and the connection can be proxied immediately. this solution actually improves the performance of proxy server by a large margin.
I would say dont touch it, it is good as it is.
I am not closing it so devs can know about this issue and its solution if it arises in future.
Thanks

**Comment by amin1softco** [comment]
@ffallah can you share source of your impliment in node.js ?

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
