### ISSUE TITLE
MTProto Proxy skipping auth packet on new socket

### ISSUE THREAD

**Issue by ffallah** [telegramdesktop/tdesktop#4715]
### Steps to reproduce
1. Set a MTProto proxy in telegram desktop
2. Use a packet sniffer or server to monitor the packets

### Expected behaviour
Per telegram standards it should include a new auth packet (64 byte) for every new socket it uses.

### Actual behaviour

It sends the first packet correctly. It is 105 bytes (64+41). but if it doesnt receive a response in timeout seconds, it closes the socket. opens a new socket but this time, it omits the auth packet (64) and sends a 41 byte payload encrypted with old auth keys from last socket !
If I understand correctly per MTProto standards, a new socket means a new auth packet should be sent first.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.2.21 alpha
**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
It should be fixed in the current stable / dev versions.
