### ISSUE TITLE
Hashtag based notifications

### ISSUE THREAD

**Issue by gsivaprabu** [telegramdesktop/tdesktop#4716]
Hi  @telegramdesktop

This is not an issue feature request.

In super group have 5000 members we have discussed different topics. can't find the related message if #hashtag based notification option means really useful. **#featureRequest**

In my village 5,000 to 6,000 members used some one discussing about **#waterProblem #PowerProblem** means **#FreshVegetableSales** .. They can alert easily.  Daily 300 to message every one not able to read all. So this feature really useful for all.

**Comment by stek29** [comment]
There’s no way to do it reliably on client side only, especially in huge supergroups.

And it’s not really necessary since it can be done easily with bots — see @MasterTagAlertBot for example.
