### ISSUE TITLE
Telegram Desktop stucks at connecting to HTTP proxy 

### ISSUE THREAD

**Issue by ntk148v** [telegramdesktop/tdesktop#4719]
### Steps to reproduce
1. Install Telegram Desktop for Linux
2. Set proxy environment variables e.g. mine were exported for http_proxy, https_proxy and no_proxy
3. Set system proxy via Network.
4. Run Telegram (AppImage).

### Expected behaviour
Telegram connects to a configured proxy.

### Actual behaviour
Telegram stucks at "Connecting to proxy" step then try to "Reconnect...", a loop happens.
My computer can connect to proxy well, and other computers in sam LAN with me point to this proxy as well. Both of them can use Telegram without any issues.

### Configuration
**Operating system:** Ubuntu 18.04 Budgie, Kernel 4.15.0-20-generic

**Version of Telegram Desktop:**: 1.2.17 and 1.2.21 alpha - Reinstall doesn't make it works.

**Used theme**: default

<b>Logs</b>

1. [tcp_10_15.txt](https://paste.ubuntu.com/p/cYd4njpMyJ/)

2. [log_10_15.txt](https://paste.ubuntu.com/p/w2kyvm2KHJ/)

**Comment by stek29** [comment]
@ntk148v Do not post your mtp log publicly online. It contains a lot of sensitive info.
