### ISSUE TITLE
gyp: Call to 'pkg-config 2> ... exit status 1 

### ISSUE THREAD

**Issue by ComradeLV** [telegramdesktop/tdesktop#4723]
+ set -e
+ FullExecPath=/home/myname/telegram_source/tdesktop/Telegram
++ dirname gyp/refresh.sh
+ pushd gyp
++ pwd
+ FullScriptPath=/home/myname/telegram_source/tdesktop/Telegram/gyp
+ popd
+ '[' -f /home/myname/telegram_source/tdesktop/Telegram/gyp/../build/target ']'
+ BuildTarget=
++ uname -s
+ MySystem=Linux
+ cd /home/myname/telegram_source/tdesktop/Telegram/gyp
+ '[' Linux == Linux ']'
+ ../../../Libraries/gyp/gyp --depth=. --generator-output=.. -Goutput_dir=../out -Dofficial_build_target= Telegram.gyp --format=cmake
gyp: Call to 'pkg-config 2> /dev/null --cflags appindicator-0.1' returned exit status 1 while in Telegram.gyp.

`libdee-dev ` as mentioned [here](https://github.com/telegramdesktop/tdesktop/issues/2823) is already installed

**Comment by Johnnynator** [comment]
What is the result of `pkg-config --cflags appindicator-0.1` when run manually? It normally should give you a clue what else is missing.

**Comment by Aokromes** [comment]
gyp got removed, so this ticket is deprecated.
