### ISSUE TITLE
Tray icon is hardcoded

### ISSUE THREAD

**Issue by grafa** [telegramdesktop/tdesktop#4726]
You guys have hardoded systray icon and it's not themable by other icon packs. Also the icon is malformed on my system (linux, DE: AwesomeWM)

![image](https://user-images.githubusercontent.com/198654/40509660-84298d40-5f9a-11e8-952f-2851da4ec41d.png)

**Comment by prototype99** [comment]
i don't have that issue, however mine is pixellated, so perhaps it should be changed to an svg icon? (and made compatible with theming)

**Comment by grafa** [comment]
There is a issue about pixelated icon. From what I saw guys from Telegram have adde SVG icon already.

To the hardcoded icon...there is even whole project trying to solve hardcoded icons across many projects. See https://github.com/bilelmoussaoui/Hardcode-Tray

From what I heard the "hardcoded" version causes some weird QT screenshotting of the icons which then results in small/pixelated icons or in my case the weird border around the icon.

I guess telegram guys are able to handle this much better so I have no worries.

**Comment by prototype99** [comment]
hmmm no ebuild (our version of packages) made for gentoo yet of that project, but i'll try and make one and if i get it running i'll make sure to get back on how to use it as a temporary fix. But yeah it's a solid application so i'm sure when they have the time they'll work on it

**Comment by xuzhao9** [comment]
Here is a blog post that provides monochrome systray icon to comply with Breeze theme style: http://www.alexl.netsons.org/172/

**Comment by stek29** [comment]
#1908
Tray icons are yet another zoo on Linux :\

**Comment by grafa** [comment]
Hi @stek29 thank you for the reference to another ticket. From what I can see it's been going for more than 2 year and last comment is 9 months old. You also referenced a few issues that are closd by now.

What are the plans to solve the try icon issue?
