### ISSUE TITLE
Markdown application is broken and depends on "replace emoji" setting.

### ISSUE THREAD

**Issue by tarcisioe** [telegramdesktop/tdesktop#4727]
### Steps to reproduce
1. Try to use markdown markup on messages with "replace emoji" disabled.
2. Notice the message does not have markdown applied to it. Monospace (both with ` and ```) does not work either way.

### Expected behaviour
"replace emoji" should not affect markdown replacement. Monospace should work.

### Actual behaviour
All the markdown interactions now require "replace emoji" to be active. Monospace isn't working at all.

### Configuration
**Operating system:**
Gentoo Linux

**Version of Telegram Desktop:**
1.22 alpha

**Comment by john-preston** [comment]
@tarcisioe Does typing ` on your input method require just one key press or is it some complex character? Because I don't know why it doesn't work for you, works in english keyboard layout for me.

Yes, I think it will work independent with Replace emoji setting starting with the next version.

**Comment by tarcisioe** [comment]
It's a complex character to type (it's a dead key, typed shift+' followed by space). I found it pretty early on because I am usually talking about programming and use monospace a lot to format (bold and italics not so much). Bold and italics are working mostly fine, but I found another weird behaviour:

1. Type `__italic__ __italic__ ` and then a ` (bold does it as well).
2. After ` is typed, the second thing with markdown applied returns to regular font.

**Comment by tarcisioe** [comment]
Can confirm that if ` is not a dead key it works as expected.

**Comment by FabianPastor** [comment]
OS: Debian Testing
Version: 1.2.22 alpha.

Same issue here. Standard Spanish keyboard(if that helps for anything), 2 keypresses needed to write the \` char.
Same behaviour, monospace don't work at all and when written down some bold and italic markdown and it seems they have changed to the right entities writting down a \` char will break all the entities except for the first one.

Some gifs i made that shows this strange bug: 
https://t.me/newschat/131832
https://t.me/newschat/131837

Note: It worked as expected with the version before.
