### ISSUE TITLE
It is hard to use markdown after last update

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#4728]
### Steps to reproduce
1. Start typing something like this in media caption

    \`\`\`
   x = "Abc"
   \`code\`
   \`\`\`

### Expected behaviour
Text is entered without problems and turns into
```
x = "Abc"
`code`
```

### Actual behaviour
Text input becomes a non-trivial task
![2018-05-25 00-02-53](https://user-images.githubusercontent.com/1321838/40514182-f3c3d30c-5fb0-11e8-9f89-27ece31aff68.gif)

One more painful gif
![2018-05-24 23-45-34](https://user-images.githubusercontent.com/1321838/40514346-7eb28404-5fb1-11e8-9247-e158ea54ebd8.gif)
_I understand that text and tags need to be entered sequentially, but some people prefer to enter the tags first and then enter the text inside._

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.2.22 alpha

**Used theme**: Any

**Comment by john-preston** [comment]
@aNNiMON Currently a single-line-monospace text inside a multi-line-monospace text indeed doesn't work as expected.. I don't think it is really that common. But perhaps it can be fixed.

Well, this is a problem indeed. If you don't stop the formatted text after a space or smth there is no easy way to stop it at all, when you got it at the end of your text. You can always insert text in the middle of the formatted block (before the last formatted letter), that way it should work.
