### ISSUE TITLE
1.2.22 Alpha markdown replacement is dependent on "Replace emoji"  setting

### ISSUE THREAD

**Issue by donowolf** [telegramdesktop/tdesktop#4731]
### Steps to reproduce
1. Under Settings -> Chat Settings, uncheck "Replace emoji".
2. Attempt to use markdown such as \*\*bold\*\*, \_\_italic\_\_, \`code\`, or \`\`\`code\`\`\`.
3. The markdown text will not be replaced and when sent the markdown characters are sent as is without altering the text formatting.

### Expected behaviour
The text with markdown formatting should be replaced regardless of emoji settings.

### Actual behaviour
When the "Replace emoji" setting is disabled, markdown support no longer functions.

### Configuration
**Operating system:** Linux (Fedora)

**Version of Telegram Desktop:** 1.2.22 alpha

**Used theme**: None (Night mode)

**Comment by john-preston** [comment]
@donowolf Thanks for the report.
