### ISSUE TITLE
Missing Disable Notification command after mute chat timeout

### ISSUE THREAD

**Issue by royryando** [telegramdesktop/tdesktop#4733]
### Steps to reproduce
1. Join to active group
2. Right click group in chat list -> Click Disable Notification
3. Try disable for 1 hour
4. Minimize / leave Telegram (not close)
5. After an hour -> Check if someone send a message in the group
6. Right click group in chat list
7. Check the list of command when right click
8. Check the color for number of unread chat

### Expected behaviour
5. Message delivered and get notification
7. There is a command **Disable Notification**
8. The color is for enabled chat notification (light)

### Actual behaviour
5. Message delivered and get notification
7. There is no command for **Disable Notification** but **Enable Notification**
8. The color is for disabled chat notification (dark)

The Point : after an hour the chat notification is enabled but the button should be for Disable Notification because the time is out, and the color for number of unread message is dark and it should be light because notification is enabled

### Configuration
**Operating system:** Ubuntu 18.04

**Version of Telegram Desktop:** 1.2.17

**Used theme**: [Dracula](https://draculatheme.com/telegram/)

**Comment by john-preston** [comment]
@royryando Please check the latest alpha version from https://desktop.telegram.org/changelog#alpha-version

**Comment by Aokromes** [comment]
no answer after near 2 years, closing.
