### ISSUE TITLE
1.2.22 Alpha typing cursor is very hard to notice on nightmode/dark themes.

### ISSUE THREAD

**Issue by Aphotice** [telegramdesktop/tdesktop#4734]
### Steps to reproduce
1. turn on night mode or change theme to a dark/black one.
2. start typing watch the typing cursor, yeah not visible enough.
3. move the cursor left and right try to correct a word, not visible enough.

### Expected behaviour
typing cursor must be white or dark depending on the theme & distinguishable in shape.

### Actual behaviour
typing cursor has turned almost black & cant be seen on night mode/black/dark themes.

### Configuration
**Operating system:** Windows 10 Enterprise build 1803

**Version of Telegram Desktop:** 1.2.22 Alpha

**Used theme**: nightmode on default theme or most darker themes

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>
debugging doesn't make any logs in my telegram folder.

![cursor not visible on nightmode-dark theme](https://user-images.githubusercontent.com/30921064/40537992-9f72716c-6025-11e8-9b46-6b50a18adb74.jpg)
![cursor visible on default theme and no nightmode on](https://user-images.githubusercontent.com/30921064/40537998-a2ad7174-6025-11e8-92de-26ff42cfe8c0.jpg)

**Comment by prototype99** [comment]
duplicate at #4732
