### ISSUE TITLE
1.2.22 Message input box doesn't recieve focus after drag & dropping text

### ISSUE THREAD

**Issue by bin-cat** [telegramdesktop/tdesktop#4735]
### Steps to reproduce
1. Drag & drop text or link to message input box.

### Expected behaviour
Telegram window becomes active and input box gets focus (like it was in 1.2.21 and earlier).

### Actual behaviour
Window from which the text was dragged stays active.

### Configuration
**Operating system:** Windows 7 x64

**Version of Telegram Desktop:** 1.2.22

**Comment by stek29** [comment]
What about 1.2.24?

**Comment by bin-cat** [comment]
Focus still stays in text source application.

**Comment by bin-cat** [comment]
Works in 1.3
