### ISSUE TITLE
Off-topic: where to report issues with Mac OS X native version?

### ISSUE THREAD

**Issue by poige** [telegramdesktop/tdesktop#4736]
It constantly amuses with new blunders so its users do need some Github-like place to express theirs excitement!

Agree? Look forward!

**Comment by poige** [comment]
![image](https://user-images.githubusercontent.com/600779/40584046-82935318-61c4-11e8-9a82-06f682cd7b40.png)

**Comment by stek29** [comment]
https://t.me/macswift
