### ISSUE TITLE
Implement URL formatting with []()

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#4737]
1. Paste link into brackets (https://url). 
2. Then type [text] in front of (). Push send.
3. You get no clickable hyperlink:
`[text](https://url)`
4. Go to special formatting bots. Type text again, paste link into brackets—it will be hidden behind the [text].
5. It's quite inconvenient.
6. Telegram for OS X just has this formatting.

**Comment by john-preston** [comment]
@Twilightssuperb I'll add this with a hotkey and context menu item in Formatting submenu, but not with a markdown-like replacement, sorry.

**Comment by Twilightssuperb** [comment]
Anyway it's better than nothing.

**Comment by ratijas** [comment]
It's quite inconvenient to write a post in other editor, then paste into Telegram Desktop (say, into my channel) and having to go through every link, manually cut-replacing them with shortcut. Maybe something can be done about it?  Like an advanced hidden option (sort of WORKMODE) which enables `[links](processing)`, to begin with?
