### ISSUE TITLE
tag and code text formating options not working depending on german keyboard layout variants

### ISSUE THREAD

**Issue by koeppernickel** [telegramdesktop/tdesktop#4738]
### Steps to reproduce
1. Select keyboard layout variant "de no accent keys"*
2. Type ```` ```your code``` ```` or ```` `your tag` ```` in the message box
3. Change keyboard variant to "de"**
4. Type ```` ```your code``` ```` or ```` `your tag` ```` in the message box

*) accents/backticks are printed instantly
**) you have to press accents/backtick two times to be printed

### Expected behaviour
Both variants should produce the same result: The text between the backticks is formatted as tag/code.

### Actual behaviour
Formatting works as expected when using "de no accent keys", but does not work when using the normal "de" variant.

### Configuration
**Operating system:** Antergos Linux, Kernel 4.16.1-11 ARCH, KDE-Plasma 5.12.5, KDE-Frameworks 5.46.0, Qt 5.11.0

**Version of Telegram Desktop:** 1.2.22 alpha

**Used theme**: default

(Btw, is "keyboard layout variation" the right expression? I couldn't find out how you call them in English. :smile:)

(Edit: OK, the right word seems to be "variant".)

**Comment by john-preston** [comment]
@koeppernickel Please try 1.2.23 alpha, I hope it is fixed there.

**Comment by koeppernickel** [comment]
@john-preston It works in 1.2.23 alpha. Thank you!
