### ISSUE TITLE
The Menu bar or the Minimize, Restore, and Close buttons are not visible properly

### ISSUE THREAD

**Issue by YogeshPrasanna** [telegramdesktop/tdesktop#4739]
### Steps to reproduce
1. Open Telegram Desktop Version 
2. click on the maximize button 
3. The menu bar does not display properly 

### Expected behaviour
All the action items in the menu bar such as minimize , maximize and close buttons should display properly 

### Actual behaviour
The menu bar does not display properly , it is sort of cut off , the minimize and maximise buttons in the menu are cut off and the close button is not at all visible 

![telegram_issue_menu_bar](https://user-images.githubusercontent.com/18151732/40579380-b8a7c4ec-6143-11e8-84c0-60f26d295bda.png)

### Configuration
**Operating system:** Windows 

**Version of Telegram Desktop:** 1.2.17

**Used theme**:
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
What version of windows? 
Try to start it in compatibility mode.

**Comment by YogeshPrasanna** [comment]
Yeah , it works fine , when run in compatibility mode

**Comment by stek29** [comment]
Then it's #4649
