### ISSUE TITLE
Building Qt with "Slightly patched" fails

### ISSUE THREAD

**Issue by programcoder** [telegramdesktop/tdesktop#474]
I tried building qt-everywhere-opensource-src-5.3.1.zip as is after downloading and extracting, it does build successfully.

But when I tried the actual steps of copy pasting the _qt_5_3_1_patch contents to, QtStatic/ (multiple times in fresh extracted directory) I get build failure on nmake

![image](https://cloud.githubusercontent.com/assets/1564969/6097825/1faa935c-aff1-11e4-96d2-17566b54b792.png)

If I try to build the Telegram Desktop App with half built Qt (after doing "nmake install" after the above screenshot) 
I get following Linkage error, LINK : fatal error LNK1104: cannot open file 'imageformats\qwebpd.lib'

Neglating the fact that I am trying to build using half built Qt, why isn't the actual Qt + Patch from Telegram does not build?

**Comment by programcoder** [comment]
This is invalid issue now, as it is "automagically" dealt with in the Qt 5.4 new patch which was recently (5-6 days ago) released and builds successfully, 

You may need to attempt for "no white space" while patching, if you are to classy

"git apply --ignore-whitespace"

**Comment by telegramdesktop** [comment]
Yes, should try Qt 5.4 patch, by copying or by applying _qt_5_4_0_patch.diff.
