### ISSUE TITLE
Check updates using proxies

### ISSUE THREAD

**Issue by p1ratrulezzz** [telegramdesktop/tdesktop#4740]
### Steps to reproduce
0. Block in your router/hosts or etc all telegram ips (simulating country block in Russia)
1. Install older version of telegram alpha
2. Run telegram and check update

### Expected behaviour
Telegram update will start downloading

### Actual behaviour
See "checking updates..." and then "Update failed"

### Configuration
Windows 10

v1.2.23 alpha

So in Russia telegram is blocked on provider level. Self-update doesn't work though I'm using proxy (mtproto and socks5 also). If I use VPN (for example, setting country = US) it updates well.

**Comment by john-preston** [comment]
@p1ratrulezzz Latest alpha versions (like 1.2.21 maybe) should use socks5 for autoupdate. But updates don't work through mtproto yet :(

**Comment by p1ratrulezzz** [comment]
Is it possible to choose first available proxy from list for updating? (any socks5 that can connect to update server)

**Comment by Aokromes** [comment]
#4665

**Comment by stek29** [comment]
Maybe a checkbox “use for updates” like “use for calls” should be added
