### ISSUE TITLE
Mentions in media captions don't support suggestions

### ISSUE THREAD

**Issue by Aztek92** [telegramdesktop/tdesktop#4741]
### Steps to reproduce
1. Paste media to the group chat 
2. Try to someone with '@mention'
3. Suggestions don't appear

### Expected behaviour
After pasting a media into a group chat and tagging people i expect suggestions to show up (just like in mobile app). Since you're working now on textbox improvements i was thinking it's the best time to report it. 

### Actual behaviour
After typing @mention there is no suggestions for people in chat. 

### Configuration
**Operating system:** Windows 10 1803

**Version of Telegram Desktop:** 1.2.24

**Used theme**: Default

**Comment by john-preston** [comment]
@Aztek92 Unfortunately I'm (almost) done for now 😭

**Comment by Aztek92** [comment]
I don't know it that's okay to remind about this, but here we go :D

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2158
