### ISSUE TITLE
auto shift capability in MTPROTO proxy settings

### ISSUE THREAD

**Issue by Big-Goal** [telegramdesktop/tdesktop#4745]
Please add **auto shift capability** to MTPROTO proxy settings. So when the in use proxy server become unavailable, Telegram would _automatically shift to an available proxy server_ in the list (respectively from the less to the more ping time).

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by hamed-ehtesham** [comment]
yes, why not?
