### ISSUE TITLE
adjusting proxy servers list in descending way

### ISSUE THREAD

**Issue by Big-Goal** [telegramdesktop/tdesktop#4747]
Please adjust MTPROTO proxy servers section in descending way. As a result the servers will be listed from the available servers with **‘the least ping’ to ‘the most ping’** and after them unavailable servers in proxy list. (While checking the availability of the servers, the available ones will jump to top)

+I think if [auto shift capability enhancement](https://github.com/telegramdesktop/tdesktop/issues/4745) become embeded, this adjustment won't be needed.

**Comment by Aokromes** [comment]
maybe better:
allow to sort proxys by:
ping, ip, name, down / up.
