### ISSUE TITLE
open tg links directly by telegram app in windows

### ISSUE THREAD

**Issue by ShariatPanah** [telegramdesktop/tdesktop#4748]
hey guys, I'm automating some telegram stuff in Windows, though I was wonder if it's possible to open tg links directly in telegram client rather than first open by browser and then by telegram, all programmatically?

I'm coding in visual studio with C#, opening telegram can be done by the following code:
System.Diagnostics.Process.Start("TelegramPath\\Telegram.exe", arguments);

for arguments parameter I tried "t.me//chatUsername" and "tg://resolver?domain=chatUsername" etc... the Telegram client app is being opened but there is no an appropriate chat opened

any suggestions would be appreciated.

**Comment by john-preston** [comment]
@ShariatPanah Try "blabla\Telegram.exe -- tg://blabla"

**Comment by ShariatPanah** [comment]
for the double quotes I assume that I'm supposed to pass it as first parameter to Process.Start Method?
by the way for the first one, it throws exception: "The system cannot find the file specified."

but if I pass "tg://somechat" for second parameter, the telegram will be opened but without appropriate chat opened.

in the log file, I can see this command line:
Command line: path\Telegram.exe tg://someChat

**Comment by john-preston** [comment]
@ShariatPanah Before tg:// place two dashes, like Telegram.exe -- tg://

**Comment by ShariatPanah** [comment]
yes I tried that like this:
`Process.Start(@"path\Telegram.exe -- tg://some");`
but it throws exception: "The system cannot find the file specified."
thanks by the way

**Comment by john-preston** [comment]
@ShariatPanah And if you just remove those two dashes - it runs normally, but without opening the chat?

**Comment by ShariatPanah** [comment]
i tried your command in CMD and nothing successful, just opens telegram app

**Comment by ShariatPanah** [comment]
if I use your command for the first parameter it throws exception anyway, but if I use "tg://some" for second parameter, it would opens telegram but without opening the chat

**Comment by john-preston** [comment]
@ShariatPanah I tried to run:

Telegram.exe — tg://resolve?domain=preston

from CMD and it launched the app and opened the requested chat.

**Comment by ShariatPanah** [comment]
it's weird, I'm trying the exact same command but nothing successful, any suggestions why?

**Comment by john-preston** [comment]
Can you provide log.txt for that launch?

**Comment by ShariatPanah** [comment]
hey thanks buddy it worked in my application, I put it here for future references:
`Process.Start(@"C:\Users\ersir\AppData\Roaming\Telegram Desktop\Telegram.exe", "-- tg://resolve?domain=preston");`

thank you so much :)
