### ISSUE TITLE
Right Click Menu gone after moving mouse from Formatting option 

### ISSUE THREAD

**Issue by smaznet** [telegramdesktop/tdesktop#4749]
### Steps to reproduce
1. Right click on text input box in chat
2. move mouse pointer over formating option
3. right click menu will be gone

### Expected behaviour
Right click menu gones

### Actual behaviour
Should not gone

### Configuration
**Operating system:** Ubuntu 18.04

**Version of Telegram Desktop:** V.1.2.24 alpha

**Comment by alk0** [comment]
Indeed very annoying bug, still not fixed (confirmed on version 1.3.1 alpha, Linux Mint 18)

**Comment by nooitaf** [comment]
To be more precise:
- Open contextmenu in chat textfield
- Mouseover formating option
- Mouseout the formatting option
- Contextmenu closes

The challenge:
- Try to reach "Paste" without closing the contextmenu

Made a video that shows what happens:
- https://i.imgur.com/NYoZPWs.mp4
