### ISSUE TITLE
User interface corrupted under Wayland

### ISSUE THREAD

**Issue by emvigo** [telegramdesktop/tdesktop#4750]
### Steps to reproduce
1. Start Telegram (1.2.24) under a Wayland session

### Expected behaviour
The UI should look nice and functional, as shown below (screenshot taken under X11)
![tdesktop-x11](https://user-images.githubusercontent.com/2376955/40613626-94228df4-627f-11e8-8316-78a223df29bf.png)

### Actual behaviour
The UI is completely corrupted under Wayland (screenshot taken under the exact same machine as above, with the same configuration, but on Wayland)
![tdesktop-wayland](https://user-images.githubusercontent.com/2376955/40613615-87164b14-627f-11e8-8cf3-d4e6210b03b9.png)

### Configuration
**Operating system:** Arch Linux (kernel version: 4.16.11-1-ARCH)

**Version of Telegram Desktop:** Upstream 1.2.24 (Arch version: 1.2.24-1)

**Comment by stek29** [comment]
#2353

**Comment by emvigo** [comment]
I've noticed 1.2.17 works just fine under Wayland (as all other stable releases have always worked for me under Wayland). So, I suspect this is something that has started to happen somewhere within the new 1.2.2x pre-releases.
Screenshot of 1.2.17 under Wayland:
![tdesktop-wayland](https://user-images.githubusercontent.com/2376955/40629295-75097c7a-62ca-11e8-980c-4fe09493e71b.png)

**Comment by stek29** [comment]
@emvigo could you please try to find exact version where it breaks?

**Comment by emvigo** [comment]
I have been able to trace it back to 1.2.22... 1.2.21 crashes due to a segfault. Dealing with binaries here, btw. To test 1.2.18-1.2.20 I would have to compile the whole thing, something my box is not capable of.

**Comment by stek29** [comment]
@emvigo can’t you download releases from GitHub?

**Comment by stek29** [comment]
Ah, you’re using version from arch repos.
You should probably report this issue to them :(
cc @svenstaro

**Comment by svenstaro** [comment]
Most likely an issue with Qt 5.11 which was just moved.

**Comment by emvigo** [comment]
Not sure, as I'm not experiencing any problems with any other Qt5 application so far. I'll double-check things out, of course.

**Comment by svenstaro** [comment]
Can you recompile the official package against current Qt and report results?

**Comment by emvigo** [comment]
@svenstaro Sorry, my box is very limited in resources and can't compile telegram desktop as much as I try :(
