### ISSUE TITLE
Copy Text with Link

### ISSUE THREAD

**Issue by Sea-n** [telegramdesktop/tdesktop#4751]
### Steps to reproduce
1. Find a message with text link (e.g. [this post](https://t.me/Telegreat/47))
2. Right Click on message
3. Select “**Copy Link**”
4. Paste into input field

### Expected behaviour
Keep text link, and no extra metadata, for instance:
> New [MTProto](https://t.me/proxy) proxy

### Actual behaviour
It looks like
> New [MTProto](https://t.me/proxy) (https<span>://</span>t.me/proxy) proxy

### Configuration
**Operating system:** macOS

**Version of Telegram Desktop:** v1.2.24 alpha

**Comment by Big-Goal** [comment]
Same as windows version

**Comment by Sea-n** [comment]
Maybe can refer to [click_handler_types.cpp](https://github.com/telegramdesktop/tdesktop/blob/bf775cb4/Telegram/SourceFiles/core/click_handler_types.cpp#L194-L197) 🤔

**Comment by RememberTheAir** [comment]
This is fixed in 1.7, I think
