### ISSUE TITLE
joining channels programmatically

### ISSUE THREAD

**Issue by ShariatPanah** [telegramdesktop/tdesktop#4752]
so I open up telegram with desired chat opened programmatically using below code in C#:
`Process.Start("path\Telegram.exe", "-- tg:/resolve?domain=somechat");`
now I want to join a channel automatically rather than clicking on JOIN button in channel chat.

is there a command or link or something to do joining programmatically? 
any suggestions would be appreciated 👍

**Comment by john-preston** [comment]
@ShariatPanah No, there is not, sorry. It won't be safe since third party apps on the same system could subscribe you to arbitrary channels without you even knowing about that.
