### ISSUE TITLE
[Feature Request] Select or copy entire code block

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#4753]
Currently there is no way to select or copy entire code block from message without manual selection by mouse or coping full message.

Selection by double-click selects a word:
![Word selection](https://i.imgur.com/MJBU28A.png)

Selection by triple-click selects a line, even if it spans multiple lines:
![Line selection](https://i.imgur.com/XiHEKSv.png)

But selections like this could be done only with manual selection by mouse:
![Block selection](https://i.imgur.com/BN1b2O2.png)

So it would be great if there wil be feature to select or entire code block. Doesn't matter, will it be context menu option or something like triple-click.

Telegram Desktop 1.2.17 on Windows 7 x64, if you need this info.

**Comment by john-preston** [comment]
@RadRussianRus I guess triple click is a good idea for that.

**Comment by RadRussianRus** [comment]
No need to close it.

**Comment by 23rd** [comment]
Can be closed now I think.

**Comment by RadRussianRus** [comment]
Oh, thanks for reminder.
