### ISSUE TITLE
Mouse stuck in "drag and drop" mode

### ISSUE THREAD

**Issue by wil93** [telegramdesktop/tdesktop#4754]
### Steps to reproduce
1. Open telegram
2. Click on first chat (in my case I have 3 pinned chats)
3. Move the mouse down

### Expected behaviour
The second chat should become hovered, but the first chat should stay active

### Actual behaviour
The first chat is "moved" to the second position, just like if I was dragging it

### Configuration
**Operating system:** Ubuntu 18.04

**Version of Telegram Desktop:** 1.2.17

**Used theme**: default

---

It is probably relevant to note that I have a touchscreen.

In my experience, this bug was always present, and was easily triggered by just using touchscreen and mouse alternatively. Also, to work around it, I usually disable the touchscreen (`xinput disable <id of touchscreen>`) and I just kill the telegram process and start it again.

However, now I can't seem to make it work again (touchscreen is disabled, but killing the process is not enough to fix it anymore).

**Comment by Pastafarianist** [comment]
I have also seen the same issue multiple times. Also using a laptop with a touchscreen. I don't have a sure way of reproducing, unfortunately.

**Comment by dserodio** [comment]
Also using Ubuntu 18.04 on laptop with a touchscreen (Dell Inspiron 13-5378). The suggested workaround didn't work for me, and this bug makes Telegram Desktop completely unusable.

**Comment by antony** [comment]
This happens constantly - and you literally have to restart the laptop to get rid of it. Also using touchscreen Dell XPS 13.

Seems to be only telegram which suffers from this.

**Comment by erjo9107** [comment]
I have the same issue, also on a laptop with touchscreen (Dell xps 15).  It seems to work for a couple of mouse clicks, then gets stuck in drag mode...
Can also add that if I manage to go into the chat, and then move the mouse I am selecting multiple messages. So it's not limited to the chat-selecting part. It's the whole telegram app and only the telegram app. Have not found a reliable way to stop it other than restarting the laptop yet. 
Makes telegram app unusable. Stuck using the web version for now...

- Ubuntu 18.04
- Telegram v 1.4.3 (The pain I had to go through to get that number...)
- Default theme

**Comment by veggero** [comment]
I also have this problem with touchscreen. My way to reproduce this is:

- Open a telegram chat
- Hold finger on a message for some seconds
- Still holding the finger, moving it up will select some messages
- Relasing the finger will show the context menu
- Touching again on a message outside the context menu will close it

The mouse is then stuck into dragging mode. My way to stop the bug is:

- Open any other app
- Single tap anywhere

Both works very reliably for me. I use

- Telegram v 1.2.6
- Neon 5.15.3
- Qt 5.12.0
- Default theme

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by erjo9107** [comment]
I recently updated to 1.8.15, but in the previous version I encountered the bug once. I does not happen as frequently as I used to, but it does happen. 
The fix i use is to use the touchscreen to select a chat in Telegram. Then it's all fine.  So my guess is it is related to the touchscreen in some way.  Note that I usually have two monitors, one my laptop with touchscreen and an external monitor without. I have telegram on the non-touchscreen monitor.
I still use a dell xps 15 with Ubuntu installed.  On my homecomputer with windows I have never seen this bug, but on that computer I do not have touchscreen.

**Comment by Aokromes** [comment]
maybe it's 3rd party bug?

**Comment by erjo9107** [comment]
Hard to determine. But I will say that I have experienced it while only running firefox, thunderbird, skype and a terminal window in Ubuntu on my laptop in Telegram 1.9.9. 
And it only happens on Telegram. All other programs works fine. I have tested using touchscreen on the other programs and detected no issues, but rarely use the touchscreen day-to-day.  
I have had the issue pop up when I'm only using one monitor (laptop touchscreen) and two monitors (laptop touchscreen and ordinary hdmi monitor). 
Could be that telegram and Dells linux touchscreen drivers are not cooperating? I have no idea, but as all other programs are working fine (even skype and other chat programs) with them I'm assuming it is something Telegram are using thats causing it.  I would suggest that someone needs to look into how telegram is handling touchscreen integration, especially Dells touchscreens as all above have mentioned Dell laptops (if they have mentioned what they are using).

**Comment by Aokromes** [comment]
> Hard to determine. But I will say that I have experienced it while only running firefox, thunderbird, skype and a terminal window in Ubuntu on my laptop in Telegram 1.9.9.
> And it only happens on Telegram. All other programs works fine. I have tested using touchscreen on the other programs and detected no issues, but rarely use the touchscreen day-to-day.
> I have had the issue pop up when I'm only using one monitor (laptop touchscreen) and two monitors (laptop touchscreen and ordinary hdmi monitor).
> Could be that telegram and Dells linux touchscreen drivers are not cooperating? I have no idea, but as all other programs are working fine (even skype and other chat programs) with them I'm assuming it is something Telegram are using thats causing it. I would suggest that someone needs to look into how telegram is handling touchscreen integration, especially Dells touchscreens as all above have mentioned Dell laptops (if they have mentioned what they are using).

have you tried with other applications using QT?

**Comment by erjo9107** [comment]
Went through this [wikipage](https://wiki.manjaro.org/index.php?title=List_of_Qt_Applications)  (manjaro wiki, so maybe not correct since I use Ubuntu) and didn't find any that i've kept open for longer periods of time as I've done with Telegram.
That said, I'm going to install notepadqq, which if I've understood it right also uses QT, and keep it open. We'll see what happens.
I've found some and few indications that the linux spotify client uses QT. If that's true, I've had no problems with spotify at all and it's almost always on.

**Comment by dniku** [comment]
I've used KeePass XC (built on Qt) for a long time and never experienced any similar issues with it.

**Comment by Sentero-esp12** [comment]
Happening to me on Linux Mint Cinnamon 20. I'm using a Wacom graphics tablet (cth-480).
