### ISSUE TITLE
Telegram Will Not Start

### ISSUE THREAD

**Issue by riw777** [telegramdesktop/tdesktop#4756]
### Steps to reproduce
1. Install Telegram Windows Desktop on Windows 10, latest release
2. Attempt to start
3. 

### Expected behaviour
Tell us what should happen

I should see the telegram window start up.

### Actual behaviour
Tell us what happens instead

Two instances of Telegram start, according to the task manager, each of which consumes about 10% of the CPU, and nothing else happens, even after leaving it running for 10-15 minutes.

### Configuration
**Operating system:**

Windows 10 Pro.

**Version of Telegram Desktop:**

Latest (afaict -- it won't open for me to check, but I did uninstall and reinstall).

**Used theme**:

Won't start to get to this point.

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

i have 7 log attempts, all look identical--

[2018.05.29 07:57:11] Launched version: 1002017, alpha: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
[2018.05.29 07:57:11] Executable dir: C:/Users/russw/AppData/Roaming/Telegram Desktop/, name: Telegram.exe
[2018.05.29 07:57:11] Initial working dir: C:/Users/russw/AppData/Roaming/Telegram Desktop/
[2018.05.29 07:57:11] Working dir: C:/Users/russw/AppData/Roaming/Telegram Desktop/
[2018.05.29 07:57:11] Command line: C:\Users\russw\AppData\Roaming\Telegram Desktop\Telegram.exe
[2018.05.29 07:57:11] Executable path before check: C:/Users/russw/AppData/Roaming/Telegram Desktop/Telegram.exe
[2018.05.29 07:57:11] Logs started

</details>

I can't start to get to the point where I can turn on debug mode.

**Comment by john-preston** [comment]
@riw777 Can you try to launch it after system restart?

**Comment by riw777** [comment]
Same thing :-( ... Is there a way to do start using debug from the command line, rather than after starting the application?

**Comment by john-preston** [comment]
@riw777 Telegram.exe -debug

**Comment by scaper12123** [comment]
I've had this issue on my desktop for the past few weeks now, but I've not had it on my laptop. Telegram just refuses to start, makes multiple instances in my task manager for every time I try to start, then promptly doesn't do anything

**Comment by smolglace** [comment]
I'm having the exact same issue as scaper12123

**Comment by mesk97** [comment]
have the same issue as scaper12123 during last week :(, do multiple reboots, windows upgrade, tool reinstall .. nothing helps me to fix issue

**Comment by speaktech** [comment]
same issue as scaper1213
uninstalled and restarted.
installed the latest version. Opens does nothing.
portable as well. nothing

**Comment by KingDynamite** [comment]
i have the same issue with windows 10 64 bits. i uninstalled and reinstalled, tried the beta version, nothing was starting. i ran telegram in compatibility mode for windows 7 and it started fine.

**Comment by lcpsd** [comment]
i'm too have the same problem...

**Comment by pegelf** [comment]
I have the same problem with Win 10 64Bit. Also there is nothing special in the logs:

> [2019.05.17 15:22:24] Launched version: 1007000, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
> [2019.05.17 15:22:24] Executable dir: C:/Users/pegel/AppData/Roaming/Telegram Desktop/, name: Telegram.exe
> [2019.05.17 15:22:24] Initial working dir: C:/Users/pegel/AppData/Roaming/Telegram Desktop/
> [2019.05.17 15:22:24] Working dir: C:/Users/pegel/AppData/Roaming/Telegram Desktop/
> [2019.05.17 15:22:24] Command line: C:\Users\pegel\AppData\Roaming\Telegram Desktop\Telegram.exe -debug
> [2019.05.17 15:22:24] Executable path before check: C:/Users/pegel/AppData/Roaming/Telegram Desktop/Telegram.exe
> [2019.05.17 15:22:24] Logs started

**Comment by aragen** [comment]
> i have the same issue with windows 10 64 bits. i uninstalled and reinstalled, tried the beta version, nothing was starting. i ran telegram in compatibility mode for windows 7 and it started fine.

I have similar problem and then solved with this

**Comment by JavierC0** [comment]
> i have the same issue with windows 10 64 bits. i uninstalled and reinstalled, tried the beta version, nothing was starting. i ran telegram in compatibility mode for windows 7 and it started fine.

Had the same issue and did the above but with the compatibility mode for windows 8 and it also worked

**Comment by projectMKULTRA** [comment]
Start it with win8 compatibility mode, worked for me with the issues named above.
**DUROV FIX DAT S**T**

**Comment by realrajeshrk** [comment]
> Start it with win8 compatibility mode, worked for me with the issues named above.
> **DUROV FIX DAT!**

Could you give me the download link for Windows 8 compatible mode telegram

**Comment by kirsantov** [comment]
Not working on Win10 64

**Comment by BonBonSlick** [comment]
Updated today, cannot launch now.

**Comment by john-preston** [comment]
@BonBonSlick Can you try now please? Is it still crashing?

**Comment by my3t** [comment]
Same here, it won't launch since yesterday on Windows 10 64 bit.

**Comment by BonBonSlick** [comment]
@john-preston some new patch fixed this, it is fine for me now, thank you!

**Comment by my3t** [comment]
It is also working for me now.

**Comment by nim** [comment]
I have this problem right now
