### ISSUE TITLE
How to integrate telegram on my web like this ?

### ISSUE THREAD

**Issue by magnetogit** [telegramdesktop/tdesktop#4760]
How to integrate telegram on my web like this ?

<img width="420" alt="screen shot 2561-05-30 at 22 40 29" src="https://user-images.githubusercontent.com/21017375/40731372-127fc2f2-645b-11e8-9b9e-6984bf930edf.png">
Thanks.

**Comment by Aokromes** [comment]
this is unrelated to telegram desktop.

**Comment by magnetogit** [comment]
@Aokromes
Can you tell me ?,Where to ask

**Comment by stek29** [comment]
Ask owners of that plugin/site
