### ISSUE TITLE
Don't change Chat List scroll position when current chat is moved 

### ISSUE THREAD

**Issue by ThigSchuch** [telegramdesktop/tdesktop#4762]
I have several conversations.
When I get home, I try to read chats that are not silenced first.
On Mobile, we can go directly to the chat in question tapping the notifications, but, on the desktop, I'm rolling the conversations, if I get to any of them and I answer something, the scroll bar comes back to the beginning. Making me have to roll over again to continue from where I was.

Suggestion: When replying something, the scroll bar stays where it was.
Ps. At least on Android, that's what happens.

**Comment by stek29** [comment]
You might find work mode useful (open settings, type `workmode`)

**Comment by ThigSchuch** [comment]
I use it, a lot, but thinking of others "regular" users and about commodity, better do this than use workmode.

**Comment by katecanaveral** [comment]
What you guys also think about more than 5 pinned chats?

**Comment by stek29** [comment]
wait, can't you just click on your reply to get back to top?

**Comment by ThigSchuch** [comment]
I think I didn't explained right, look at these videos.
[Windows 10](https://imgur.com/a/0EyuudO) and [Android](https://imgur.com/a/F9nfKCl)

Can see what I'm talking about?
Android, if I send a message, chat list stay where it is.
Windows, it follows the chat, going to top.

If I have a lot of messages to read, I'll have to roll down again, every time I answer someone.

**Comment by stek29** [comment]
Ohh, so you're referring to scroll position in chat list, not to scroll position in dialog.
