### ISSUE TITLE
Clicking a different contact from an inactive window causes current contact's messages to be read

### ISSUE THREAD

**Issue by S-U-M-1** [telegramdesktop/tdesktop#4765]
### Steps to reproduce
1. Be on a different window to Telegram (make it the active window) but still allow the Telegram window to be visible on screen.
2. Wait for the currently-open contact in Telegram to send a message (it should be marked as unread).
3. Click on a different contact in the contacts list (this should make the Telegram window active).

### Expected behaviour
The currently-open contact's messages should not be marked as read (as in pre-1.0).

### Actual behaviour
Since 1.0, this action causes the currently-open contact's messages to be marked as read, even if you didn't read them. This has actually caused an argument with one of my contacts once.

### Configuration
**Operating system:**
Windows 7
**Version of Telegram Desktop:**
1.2.17 (this problem has occurred since 1.0)
**Used theme**:
None
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
Well, you have indeed read those messages, haven't you? :)

**Comment by S-U-M-1** [comment]
What sort of a response is that? The functionality was changed for no apparent reason at all. I'll attach a video of the effect if you so wish. It shouldn't be occurring.

**Comment by S-U-M-1** [comment]
@stek29 I made a video showing the bug. Link: https://www.dropbox.com/s/cad21e80ahz6ni9/Telegram%20Read%20Message%20Bug.mp4?dl=0

**Comment by stek29** [comment]
It’s a valid point and I’m not trying to argue or make fun of it — and I agree that this behavior should be considered as a bug — video was not necessary.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4664 ?

**Comment by S-U-M-1** [comment]
> #4664 ?

What about it? It's a different bug. Are you suggesting they could be linked or that they are the same?
