### ISSUE TITLE
[Feature Request] Dark theme

### ISSUE THREAD

**Issue by Voyadexon** [telegramdesktop/tdesktop#477]
First of all I want to say that I really like the desktop client (especially because you can finally change your background now), but one thing that I would like to be added is a dark theme, because the default one is really hurting my eyes, especially at night.

**Comment by Drakulix** [comment]
+1

**Comment by intrd** [comment]
+1

**Comment by drasive** [comment]
+1

**Comment by Aokromes** [comment]
Duplicate? #185

**Comment by arkty** [comment]
+1

**Comment by ccaspers** [comment]
+1

**Comment by vandr0iy** [comment]
@telegramdesktop is there a config file, or a binary, or something, where the appearance values are stored? I've never written qt applications, but, for the sake of my eyes' health i could read up something and contribute. Do you have any documentation which contains that info?

**Comment by branderxero** [comment]
+1

just another option under background. something like:

Theme [ light | dark ]

**Comment by intrd** [comment]
+1
