### ISSUE TITLE
New popups inefficient and slower

### ISSUE THREAD

**Issue by S-U-M-1** [telegramdesktop/tdesktop#4770]
### Steps to reproduce
1. Enter a chat
2. Click the contact's name at the top

### Expected behaviour
As in 1.1.23 for example, Telegram should open the contact information in the same space as the chat. All information should be visible without scrolling (in default resolution). I can click back without having to move my mouse from its position. There are no excess call and settings buttons.
![image](https://user-images.githubusercontent.com/29358863/40808851-70ae135e-6520-11e8-95a7-7b711d93c643.png)

### Actual behaviour
Telegram opens it in a popup which requires scrolling to see all information. I have to move my mouse to click an X or click out of the popup to go back. There are excess call and settings buttons.
![image](https://user-images.githubusercontent.com/29358863/40809102-3998b97c-6521-11e8-9c6e-0f8296f929e5.png)

### Configuration
**Operating system:**
Windows 7
**Version of Telegram Desktop:**
1.2.17
**Used theme**:
None
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@S-U-M-1 Thanks for your feedback. For now the profile pages are left that way. They're better optimized for large screens where you can have third column with current chat profile information always visible without clicks at all.

**Comment by S-U-M-1** [comment]
I have a pair of 27-inch monitors. I have found no use in the chat profile sidebar. I do not want to see that information constantly all the time, obstructing a good portion more of my screen. Just restoring this functionality would make more information visible in a smaller area and allow for faster operation.

**Comment by S-U-M-1** [comment]
@john-preston Besides, the chat profile sidebar suffers from the same problem I described. I have to scroll to view all the information which previously was all visible there for me.
![image](https://user-images.githubusercontent.com/29358863/40810080-9bd0569c-6524-11e8-9585-9cb98aad2655.png)

**Comment by S-U-M-1** [comment]
There is a third reason why the new popups are inefficient. In previous versions, the amount of visible videos and photos would scale with the Telegram window.
![image](https://user-images.githubusercontent.com/29358863/40810285-449e72c2-6525-11e8-8e32-84fdae7cce1a.png)

Now, they are stuck at 4 columns.
![image](https://user-images.githubusercontent.com/29358863/40810311-506a7696-6525-11e8-9ee1-6c1446c9fb07.png)

**Comment by john-preston** [comment]
@S-U-M-1 You can't find anything efficiently in a 20x20 grid anyway.

**Comment by S-U-M-1** [comment]
Not to mention, the thumbnails themselves are smaller.

**Comment by S-U-M-1** [comment]
@john-preston That shouldn't be any one person's right to decide. The fact of the matter is there are needless reversals of productivity in this new popup system. I have large screens and it is not better optimised, and I'd like to see why you think that. In any case, there should at least be an option to either have popups or have the old layout.
