### ISSUE TITLE
Message input color bug in v1.3

### ISSUE THREAD

**Issue by Seed122** [telegramdesktop/tdesktop#4774]
### Steps to reproduce
1. Type a short message
2. Erase it with backspace
3. Type another message

### Expected behaviour
Text color should be black

### Actual behaviour
Text color is light and almost unreadable

### Configuration
**Operating system:**
The bug reproduces on Ubuntu 18.04. Dont know about other platforms :). 

**Version of Telegram Desktop:**
v1.3

**Used theme**:
Light theme. Dark theme does well.

</details>

**Comment by Seed122** [comment]
Can't reproduce after reboot.

**Comment by MelomanCool** [comment]
I've noticed this issue with the dark theme. The text becomes black after erasing and typing again:
![image](https://user-images.githubusercontent.com/5171026/40889432-beaf823c-6777-11e8-9cf1-722b64d4bbd9.png)
![image](https://user-images.githubusercontent.com/5171026/40889451-fffa0942-6777-11e8-8840-f94928312254.png)

**Comment by MelomanCool** [comment]
It seems that this happens not when the text was erased, but when you press backspace at the start of the input box.
For example, I write some text in the box: 
![image](https://user-images.githubusercontent.com/5171026/40889675-10b06c14-677c-11e8-9856-4bb006ae2744.png)
Then, I move the cursor to the start of the box and press backspace:
![image](https://user-images.githubusercontent.com/5171026/40889692-57dd2cbc-677c-11e8-84e1-91f8b065a745.png)
Notice that the text that was already in the box is still white.
If I type something in, the typed text will be black:
![image](https://user-images.githubusercontent.com/5171026/40889705-9262b762-677c-11e8-9581-d44cbc002898.png)
However, if I move the cursor to the right, in the "white" text and type something there, the typed text will be white, too:
![image](https://user-images.githubusercontent.com/5171026/40889736-0248e09c-677d-11e8-94b8-d308eb60dc16.png)

**Comment by MelomanCool** [comment]
@john-preston It doesn't reproduce if I relaunch the app and won't switch themes.
Also, pressing enter inside the empty box makes the color of the text normal again.

**Comment by john-preston** [comment]
Should be fixed in 1.3.1 alpha.

**Comment by MelomanCool** [comment]
It kind of is, but there's still some weird behavior after theme switching.
![output](https://user-images.githubusercontent.com/5171026/41096407-8f78e4c2-6a65-11e8-8ee6-820d907b181d.gif)

**Comment by john-preston** [comment]
@MelomanCool What version did you used to record this?

**Comment by MelomanCool** [comment]
@john-preston The version is 1.3.2.

**Comment by john-preston** [comment]
@MelomanCool I see, indeed. Thanks for the report.
