### ISSUE TITLE
GNU/Linux version 1.3.0 archive is outdated

### ISSUE THREAD

**Issue by alextrezvy** [telegramdesktop/tdesktop#4778]
### Steps to reproduce
1. Download the file 'tsetup32.1.3.0.tar.xz'.
2. Extract & start 'Telegram'.
3. Check the version. It shows '1.2.6'. No connection indeed.

### Configuration
Ubuntu 16.04.

**Comment by john-preston** [comment]
@alextrezvy I can't reproduce. This would be very strange. I guess somehow you end up launching the old binary (I'm not sure how).

**Comment by stek29** [comment]
if you don't quit old version and start new one, it won't start since another instance is running already.

**Comment by alextrezvy** [comment]
@stek29 It seems you were right. Now it says: 'error while loading shared libraries: libgthread-2.0.so.0: cannot open shared object file: No such file or directory'.
