### ISSUE TITLE
When using hotkeys (cmd-shift-m) a window is minimizing instead of making selected text monospaced

### ISSUE THREAD

**Issue by alexander-ii** [telegramdesktop/tdesktop#4779]
### Steps to reproduce
1. Switch a keyboard layout from Latin (EN US) to Cyrillic (RU)
2. Select text and use `CMD` + `SHIFT` + `M` (`CMD` + `SHIFT` + `Ь`)

### Expected behaviour
The selected text becomes monospaced

### Actual behaviour
The window is minimized

### Configuration
**Operating system:**
macOS 10.13.4 (17E202)

**Version of Telegram Desktop:**
1.3

**Used theme**:
Default

**Comment by john-preston** [comment]
@alexander-ii Indeed. Don't know how to fix yet :(

**Comment by romanesko** [comment]
really annoying (

**Comment by 23rd** [comment]
It should be fixed now. Please reopen this issue if you still have problems with it.
