### ISSUE TITLE
Sticker post info crops for stickers with short width

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#4781]
It's actually hard to reproduce because it need much longer info (more views, actually) but i've got screenshots.

How it looks in channel:
![image](https://user-images.githubusercontent.com/2903496/40879580-108e12a8-66ab-11e8-9a82-6e3263597f8e.png)

How it looks when reposted to "Saved Messages":
![](https://user-images.githubusercontent.com/2903496/40879585-23a09b0e-66ab-11e8-83ae-5e3e407981a1.png)

How it looks when reposted to any other chat:
![image](https://user-images.githubusercontent.com/2903496/40879601-5af6ff3a-66ab-11e8-9aea-2eb64f4de9d5.png)

Telegram Desktop 1.3, Windows 7 x64, default theme.

**Comment by john-preston** [comment]
@RadRussianRus Can you provide this sticker pack link here?

**Comment by RadRussianRus** [comment]
@john-preston https://t.me/addstickers/Suflesticks

**Comment by john-preston** [comment]
Should be fixed in 1.3.1 alpha.

(I hope it will fix that, I didn't test on that exact stickers set).

**Comment by RadRussianRus** [comment]
I confirm that it's fixed in 1.3.1 alpha.

![image](https://user-images.githubusercontent.com/2903496/40999099-9122bc84-6912-11e8-8558-fee92f56c10e.png)

![image](https://user-images.githubusercontent.com/2903496/40999118-a028acca-6912-11e8-81a6-759198295e19.png)

![image](https://user-images.githubusercontent.com/2903496/40999174-c96a18bc-6912-11e8-84d3-e94300a4043b.png)
