### ISSUE TITLE
Disappeared voice recording button in 1.3

### ISSUE THREAD

**Issue by svu** [telegramdesktop/tdesktop#4783]
### Steps to reproduce
1.  Install telegram desktop 1.3 on Macos 10.13.5
2. Start telegram
3. There is no 'record voice' button

### Expected behaviour
The voice recording button should be presented on the entry line

### Actual behaviour
There are only 'smiles' and 'send' buttons

### Configuration
**Operating system:**
MacOS 10.13.5

**Version of Telegram Desktop:**
1.3

**Used theme**:
Light

![screen shot 2018-06-03 at 19 30 00](https://user-images.githubusercontent.com/121815/40889783-8d32e9be-6764-11e8-9d17-58962d9f9127.png)

**Comment by poige** [comment]
> Used theme: Light

so cute! Dark here ;)

**Comment by svu** [comment]
Important: This issue is specific to 1.3 downloaded from AppStore. The version directly downloaded as .dmg and installed does not have that issue.

**Comment by john-preston** [comment]
@svu Thanks for the report. It will be fixed in the next Mac App Store release.

**Comment by john-preston** [comment]
@john-preston BTW until 10.13.5 Apple didn't check security permissions on microphone for sandboxed apps. Because Telegram Desktop never asked for that permission but the voice message recording worked just fine.

**Comment by svu** [comment]
Thank you! When will it appear in the store?

**Comment by john-preston** [comment]
@svu I'm not sure :( I hope within a week.
