### ISSUE TITLE
Fullscreen size bug

### ISSUE THREAD

**Issue by ImoutoChan** [telegramdesktop/tdesktop#4785]
### Steps to reproduce
1. Just open stable or alpha version 

### Expected behaviour
App should correctly go to fullscreen mode like expected

### Actual behaviour
App failed to properly go to fullscreen mode, go under taskbar and cut half of the header.

### Configuration
**Operating system:** windows 10, bug is appeared after last big update

**Version of Telegram Desktop:** alpha 1.3 and current stable version

**Used theme**: doesn't matter

This bug is very frustrating and many of my friends also got it after install latest windows update. Probably it can only be replicated on the multimonitor environment.

video:
https://mega.nz/#!pgAQ3KiS!US2bu5GdWPoJ5dnK45EyRFiVj1AZeeJ0W7kR3FNGD9o

**Comment by stek29** [comment]
#4649
