### ISSUE TITLE
The shortcut "shift-tab" dont work.

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#4786]
### Expected behaviour

The chats search box opens.

[Image](http://i.imgur.com/28MbVQW.png)
The image above, show what should happen.

### Actual behaviour
Nothing happen. But in the version prior to this, this happened normally.

### Configuration
**Operation system:** 
Arch Linux x86-64

**Version of Telegram Desktop:** 
1.3

**Used theme:** 
default
<!--
Thanks for reporting issues of Telegram Desktop!

**Comment by john-preston** [comment]
@linuxroot1 You can just use escape?

**Comment by linuxroot1** [comment]
> @linuxroot1 You can just use escape?

Yeah, I can but I'm used to using the "shift-tab".
