### ISSUE TITLE
Telegram segmentation fault, doesn't open desktop client

### ISSUE THREAD

**Issue by jon85p** [telegramdesktop/tdesktop#4791]
Hello!
In a fresh installation of openSUSE Leap 15.0 I got this problem (v1.3.0):
`$ strace ./Telegram
 
execve("./Telegram", ["./Telegram"], 0x7ffda408b0d0 /* 95 vars */) = 0
brk(NULL)                               = 0x7755000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9a93343000
arch_prctl(ARCH_SET_FS, 0x7f9a93343b00) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
`

**Comment by stek29** [comment]
Do you get window saying that TDesktop has crashed on next launch?

**Comment by jon85p** [comment]
Hi @stek29 , the error is reproducible, no window appear in any attempt.

**Comment by phpony** [comment]
Check this first: https://github.com/telegramdesktop/tdesktop/issues/4240#issuecomment-384624327

**Comment by jon85p** [comment]
SOLVED
On v.1.3.8 the problem it's gone.
