### ISSUE TITLE
"Scroll down" button not hides after reply, even if there is no need to scroll

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#4792]
### Steps to reproduce
1. Send message with "Reply" to any message, except yours
2. Click on cited message in your reply

### Expected behaviour
"Scroll down" button should appear only if it scrolls too long and disappear after scrolling to bottom.

### Actual behaviour
"Scroll down" button always appears and can disappear if you either click it or scroll chat up a little, then down.

### Configuration
**Operating system:** Windows 7 x64
**Version of Telegram Desktop:** 1.3
**Used theme**: default

**Comment by john-preston** [comment]
@RadRussianRus The idea of a scroll button after clicking on a cited message is to highlight back the message you went from, not only scroll down. So it works as expected.

BTW there is a bug that when you click on a cited message in a reply that you've sent from that app a moment ago (before relaunching the app) it will NOT give you the scroll down arrow and will NOT highlight this message once you press it. And this is a bug that should be fixed :)

**Comment by RadRussianRus** [comment]
@john-preston Funny, I guess that double meaning of this button with this bug confused me.
