### ISSUE TITLE
Telegram closed when searching a member in a group

### ISSUE THREAD

**Issue by Edu4rdSHL** [telegramdesktop/tdesktop#4795]
### Steps to reproduce
1. Open your telegram desktop application
2. Search a member in a group using the box in the right panel
3. Click on the user profile

### Expected behaviour
Telegram open the user info.

### Actual behaviour
Telegram is closed instantaneously 

### Configuration
**Operating system:** ArchLinux

**Version of Telegram Desktop:** 1.3.0-1

**Used theme**: This happen with anyone theme

<details><summary><b>Logs</b>:</summary>

                                                    
                                                    Stack trace of thread 8893:
                                                    #0  0x00007f0979503ea9 __poll (libc.so.6)
                                                    #1  0x00007f097a372523 n/a (libglib-2.0.so.0)
                                                    #2  0x00007f097a37263e g_main_context_iteration (libglib-2.0.so.0)
                                                    #3  0x00007f097a372692 n/a (libglib-2.0.so.0)
                                                    #4  0x00007f097a39aa2a n/a (libglib-2.0.so.0)
                                                    #5  0x00007f097a10f075 start_thread (libpthread.so.0)
                                                    #6  0x00007f097950e53f __clone (libc.so.6)
                                                    
                                                    Stack trace of thread 8900:
                                                    #0  0x00007f0979503ea9 __poll (libc.so.6)
                                                    #1  0x00007f097a372523 n/a (libglib-2.0.so.0)
                                                    #2  0x00007f097a37263e g_main_context_iteration (libglib-2.0.so.0)
                                                    #3  0x00007f097b2c1e49 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventL>
                                                    #4  0x00007f097b26d85c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQ>
                                                    #5  0x00007f097b0b6ac9 _ZN7QThread4execEv (libQt5Core.so.5)
                                                    #6  0x00007f097b0c0b95 n/a (libQt5Core.so.5)
                                                    #7  0x00007f097a10f075 start_thread (libpthread.so.0)
                                                    #8  0x00007f097950e53f __clone (libc.so.6)

</details>

**Comment by stek29** [comment]
#4560
