### ISSUE TITLE
Month names and Russian translation

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#4797]
Russian language got two cases of using month name.

1. Without day number, e.g. `Июнь` (literally `June`);
2. With day number, e.g. `17 июня` (literally `17th of June`).

But `lng_month*` keys used everywhere so it breaks some of translation. Because of this Russian translation needs to stick only one case, and currently it's second.

What should use **first case**, because there is only month name:
1. Calendar;
2. Shared media: photos, videos, files, voice messages.

What should use **second case**, because there is a day and month:
1. In-chat "pills";
2. Shared links.

### Screenshots (with first case in translation)

Calendar (correct, should be first case):
![image](https://user-images.githubusercontent.com/2903496/40946649-5295d600-6867-11e8-9f0d-d307758e68ff.png)

Shared videos (correct, should be first case, also applies to photos, files and voice messages):
![image](https://user-images.githubusercontent.com/2903496/40946718-bf82d772-6867-11e8-8539-82af7d4905db.png)

In-chat "pills" (incorrect, should use second case):
![image](https://user-images.githubusercontent.com/2903496/40946848-643a9796-6868-11e8-9015-b05f90c80b38.png)

Shared links (incorrect, should use second case):
![image](https://user-images.githubusercontent.com/2903496/40946788-2873f572-6868-11e8-8b09-cdb12464afb0.png)

**Comment by MasterGroosha** [comment]
I guess this is fixed in 1.3.2 alpha and can be closed, right?

**Comment by john-preston** [comment]
@MasterGroosha When right values are assigned on the translations platform it should work.

**Comment by stek29** [comment]
@MasterGroosha I prefer to keep issues open with milestone added until a stable release is deployed.

**Comment by MasterGroosha** [comment]
Just as a follow-up: date tooltips still have this issue:
![image](https://user-images.githubusercontent.com/2780044/41199728-ca504586-6c9f-11e8-9f1f-f60efac94465.png)

**Comment by physbyte** [comment]
True, and 1.3.5 alpha, win 10 in dialogs "Month names in Russian translation" is English.

**Comment by RadRussianRus** [comment]
Telegram Desktop 1.3.9, problem with tooltips still exist.

**Comment by john-preston** [comment]
@RadRussianRus @MasterGroosha date tooltip uses:

`date.toString(QLocale::system().dateTimeFormat(QLocale::LongFormat))`

so it's Qt or system who formats those dates :(

**Comment by MasterGroosha** [comment]
@john-preston Thank you for the comment! I guess this issue can be closed then, right?

**Comment by RadRussianRus** [comment]
@john-preston
Wait. It uses `QLocale::system()`, meaning that no matter what language pack you use, it will always use dates from system locale. Shouldn't it use locale of language pack?

**Comment by john-preston** [comment]
@RadRussianRus Well, here the idea was to show the dates like system shows.

**Comment by RadRussianRus** [comment]
@john-preston
I think mixing locales is strange, but I guess it would be better to open separate issue for this.
