### ISSUE TITLE
Italian language file

### ISSUE THREAD

**Issue by garetjax76** [telegramdesktop/tdesktop#48]
Here's to you the Italian translation of the strings, I hope soon you'll make the app multilanguage-capable.
Please let me know if you add more strings as I'll keep them translated.
Also, I'm new to github, let me know how I can upload the file properly.

direction: "LTR";

lng_maintitle: "Telegram D";

lng_menu_contacts: "Contatti";
lng_menu_settings: "Impostazioni";
lng_menu_about: "?";

lng_open_from_tray: "Mostra Telegram";
lng_quit_from_tray: "Esci da Telegram";
lng_tray_icon_text: "Telegram è ancora in esecuzione,
puoi fare in modo che si chiuda nelle Impostazioni.

Se questa icona sparisce da qui, 
puoi trascinarla di nuovo qui dalle icone nascoste.";

lng_month1: "Gennaio";
lng_month2: "Febbraio";
lng_month3: "Marzo";
lng_month4: "Aprile";
lng_month5: "Maggio";
lng_month6: "Giugno";
lng_month7: "Luglio";
lng_month8: "Agosto";
lng_month9: "Settembre";
lng_month10: "Ottobre";
lng_month11: "Novembre";
lng_month12: "Dicembre";

lng_weekday1: "Lun";
lng_weekday2: "Mar";
lng_weekday3: "Mer";
lng_weekday4: "Gio";
lng_weekday5: "Ven";
lng_weekday6: "Sab";
lng_weekday7: "Dom";

lng_month_day: "{month} {day}";

lng_cancel: "Annulla";
lng_continue: "Continua";
lng_connecting: "Connessione...";
lng_reconnecting: "Riconessione tra %1 s...";
lng_reconnecting_try_now: "Riprova ora";

lng_status_offline: "offline";
lng_status_invisible: "invisibile";
lng_status_lastseen: "ultimo accesso: {when}";
lng_status_lastseen_now: "poco fa";
lng_status_lastseen_minute: "%1 minuto fa";
lng_status_lastseen_minutes: "%1 minuti fa";
lng_status_lastseen_hour: "%1 ora fa";
lng_status_lastseen_hours: "%1 ore fa";
lng_status_lastseen_today: "oggi alle {time}";
lng_status_lastseen_yesterday: "ieri alle {time}";
lng_status_lastseen_date: "{date}";
lng_status_online: "online";

lng_chat_no_members: "Il gruppo non è accessibile";
lng_chat_members: "%1 membri";
lng_chat_members_online: "%1 membri, %2 online";

lng_server_error: "Errore del server.";
lng_flood_error: "Troppi tentativi. Riprova più tardi.";
lng_deleted: "Sconosciuto";

lng_intro1: "Questo è un client [b]desktop[/b] non ufficiale 
del programma di messaggistica mobile [b]Telegram[/b].";
lng_intro2: "Vai su [a href=\"https://telegram.org/\"]telegram.org[/a] per saperne di più.";
lng_start_msgs: "Inizia da qui";

lng_intro_back: "Indietro";
lng_intro_next: "Avanti";
lng_intro_finish: "Fine";

lng_phone_ph: "Il tuo numero di telefono";
lng_phone_title: "Il tuo telefono";
lng_phone_desc: "Conferma il tuo codice Paese e inserisci
il tuo numero di telefono.";
lng_phone_notreg: "Nota: se non hai ancora un account Telegram,
[b]crealo[/b] tramite il tuo dispositivo [a href=\"https://telegram.org/\"]iOS / Android[/a] o {signup}qui »{/signup}";
lng_country_code: "Codice Paese";
lng_bad_country_code: "Codice Paese non valido";
lng_country_ph: "Cerca";
lng_country_done: "Fatto";
lng_country_none: "Paese non trovato";
lng_country_select: "Seleziona Paese";

lng_code_ph: "Il tuo codice";
lng_code_desc: "Abbiamo mandato sul tuo telefono un SMS contenente il codice
di attivazione. Inseriscilo qui.";
lng_code_call: "Telegram ti chiamerà tra %1:%2";
lng_code_calling: "Telegram ti sta chiamando...";
lng_code_called: "Telegram ha chiamato il tuo numero";

lng_bad_phone: "Numero di telefono non valido. Riprova.";
lng_bad_phone_noreg: "Numero di telefono non registrato.";
lng_bad_code: "Hai inserito un codice non valido. Riprova.";
lng_bad_name: "Inserisci il tuo nome e cognome.";
lng_bad_chat_title: "Inserisci il titolo della chat.";
lng_bad_photo: "Immagine selezionata non valida.";

lng_signup_title: "Informazioni e foto";
lng_signup_firstname: "Nome";
lng_signup_lastname: "Cognome";

lng_dlg_filter: "Cerca";
lng_dlg_new_group_name: "Nome gruppo";
lng_dlg_create_group: "Crea";

lng_settings_profile: "Profilo";
lng_settings_edit: "Modifica";
lng_settings_save: "Conferma";
lng_settings_cancel: "Annulla";
lng_settings_upload: "Imposta immagine profilo";
lng_settings_badsize: "La dimensione di questa immagine non è corretta, prova con un'altra.";
lng_settings_crop_profile: "Seleziona un'area quadrata per l'immagine del tuo profilo";
lng_settings_uploading_photo: "Caricamento foto...";

lng_settings_section_notify: "Notifiche";
lng_settings_desktop_notify: "Notifiche desktop";
lng_settings_sound_notify: "Suono";

lng_settings_section_general: "Generale";
lng_settings_auto_update: "Aggiorna automaticamente";
lng_settings_current_version: "Versione {version}";
lng_settings_check_now: "Cerca aggiornamenti";
lng_settings_update_checking: "Ricerca degli aggiornamenti...";
lng_settings_latest_installed: "E' già installata l'ultima versione";
lng_settings_downloading: "Scaricamento aggiornamento {ready} / {total} Mb...";
lng_settings_update_ready: "Nuova versione pronta";
lng_settings_update_now: "Riavvia ora";
lng_settings_update_fail: "Non è riuscita la ricerca degli aggiornamenti :(";
lng_settings_workmode_tray: "Mostra icona in area di notifica";
lng_settings_workmode_window: "Mostra icona nella barra applicazioni";
lng_settings_auto_start: "Esegui Telegram all'avvio del computer";
lng_settings_start_min: "Avvia ridotto a icona";
lng_settings_scale_label: "Dimensione caratteri";
lng_settings_scale_auto: "Auto ({cur})";

lng_settings_section_chat: "Opzioni chat";
lng_settings_replace_emojis: "Sostituisci con emoji";
lng_settings_view_emojis: "Vedi lista";
lng_settings_emoji_list: "Lista degli emoji supportati";
lng_settings_send_enter: "Invia messaggio se premuto Invio";
lng_settings_send_ctrlenter: "Invia messaggio se premuto Ctrl+Invio";
lng_settings_send_cmdenter: "Invia con Cmd+Invio";
lng_settings_cats_and_dogs: "Sfondo con immagine";

lng_download_path_dont_ask: "Non chiedere la cartella di salvataggio per ogni file";
lng_download_path_label: "Cartella file scaricati: ";
lng_download_path_temp: "cartella temporanea";
lng_download_path_clear: "Cancella tutto";
lng_download_path_header: "Cartella per i file scaricati";
lng_download_path_temp_radio: "Cartella temporanea, pulita ad ogni disconnessione o disinstallazione";
lng_download_path_dir_radio: "Cartella manuale, pulita manualmente";
lng_download_path_choose: "Cartella file scaricati";
lng_sure_clear_downloads: "Vuoi eliminare tutti i file scaricati nella cartella temporanea? La pulizia avviene anche ad ogni disconnessione o disinstallazione.";
lng_download_path_failed: "Lo scaricamento del file non è possibile. Controlla la cartella di scaricamento.

Puoi cambiare la cartella dei file scaricati nelle Impostazioni.";
lng_download_path_settings: "Vai alle Impostazioni";
lng_download_finish_failed: "Lo scaricamento del file si è interrotto.

Vuoi riprovare?";
lng_download_path_clearing: "Pulizia...";
lng_download_path_cleared: "Pulizia terminata!";
lng_download_path_clear_failed: "Pulizia fallita :(";

lng_settings_section_advanced: "Avanzate";
lng_connection_type: "Tipo connessione:";
lng_connection_auto_connecting: "Automatica (connessione..)";
lng_connection_auto: "Automatica ({type} in uso)";
lng_connection_http_proxy: "HTTP con proxy";
lng_connection_tcp_proxy: "TCP con proxy";
lng_connection_header: "Tipo connessione";
lng_connection_auto_rb: "Auto (TCP se disponibile o HTTP)";
lng_connection_http_proxy_rb: "HTTP con http-proxy manuale";
lng_connection_tcp_proxy_rb: "TCP con socks5-proxy manuale";
lng_connection_host_ph: "Server";
lng_connection_port_ph: "Porta";
lng_connection_user_ph: "Utente";
lng_connection_password_ph: "Password";
lng_connection_save: "Salva";
lng_settings_reset: "Ripristina le sessioni";
lng_settings_reset_done: "Ripristino sessioni completato";
lng_settings_logout: "Esci";

lng_settings_need_restart: "Devi riavviare Telegram per applicare
alcune delle impostazioni. Riavvia adesso?";
lng_settings_restart_now: "Riavvia";
lng_settings_restart_later: "Più tardi";

lng_profile_settings_section: "Impotazioni";
lng_profile_participants_section: "Partecipanti";
lng_profile_info: "Info contatto";
lng_profile_group_info: "Info gruppo";
lng_profile_add_contact: "Aggiungi Contatto";
lng_profile_edit_contact: "Modifica";
lng_profile_edit_group: "Modifica";
lng_profile_phone: "Telefono: {phone}";
lng_profile_enable_notifications: "Notifiche";
lng_profile_clear_history: "Pulisci vecchi messaggi";
lng_profile_send_message: "Invia messaggio";
lng_profile_share_contact: "Condividi contatto";
lng_profile_delete_contact: "Cancella";
lng_profile_set_group_photo: "Imposta foto";
lng_profile_add_participant: "Aggiungi membro";
lng_profile_delete_and_exit: "Esci dal gruppo";
lng_profile_kick: "Espelli";
lng_profile_sure_kick: "Espelli {user} dal gruppo?";
lng_profile_loading: "Caricamento...";

lng_participant_filter: "Cerca";
lng_participant_invite: "Invita";
lng_create_new_group: "Nuovo Gruppo";
lng_create_group_next: "Prossimo";
lng_create_group_title: "Nuovo Gruppo";

lng_sure_delete_contact: "Sei sicuro di voler cancellare {contact} dalla tua lista contatti?";
lng_sure_delete_history: "Sei sicuro di voler cancellare tutti i vecchi messaggi con {contact}?

L'azione è irreversibile.";

lng_sure_delete_and_exit: "Sei sicuro di voler cancellare tutti i vecchi messaggi e uscire dal gruppo «{group}»?

L'azione è irreversibile.";

lng_sure_enable_debug: "Vuoi abilitare la modalità DEBUG?

Verranno mostrati tutti gli eventi di rete.";

lng_message_empty: "(vuoto)";

lng_action_add_user: "{from} ha aggiunto {user}";
lng_action_kick_user: "{from} ha espulso {user}";
lng_action_user_left: "{from} ha lasciato il gruppo";
lng_action_user_joined: "{from} è entrato nel gruppo";
lng_action_user_photo: "{from} ha aggiunto una nuova immagine del profilo";
lng_action_user_registered: "{from} è entrato in Telegram";
lng_action_removed_photo: "{from} ha rimosso l'immagine del gruppo";
lng_action_changed_photo: "{from} ha cambiato l'immagine del gruppo";
lng_action_changed_title: "{from} ha cambiato il nome del gruppo in «{title}»";
lng_action_created_chat: "{from} ha creato il gruppo «{title}»";
lng_action_checked_in: "{from} è entrato";

lng_forwarded_from: "Inoltrato da ";

lng_attach_failed: "Fallito";
lng_attach_file: "File";
lng_attach_photo: "Immagine";

lng_media_open_with: "Apri con";
lng_media_download: "Scarica";
lng_media_cancel: "Annulla";
lng_media_video: "Video";
lng_media_audio: "Audio";

lng_in_dlg_photo: "Immagine";
lng_in_dlg_video: "Video";
lng_in_dlg_geo: "Mappa";
lng_in_dlg_contact: "Contatto";
lng_in_dlg_audio: "Audio";
lng_in_dlg_document: "File";

lng_send_button: "Invia";
lng_message_ph: "Scrivi un messaggio...";
lng_empty_history: "";
lng_willbe_history: "Seleziona la chat per iniziare a mandare messaggi";
lng_message_with_from: "[c]{from}:[/c] {message}";
lng_from_you: "Tu";

lng_typing: "sta scrivendo";
lng_user_typing: "{user} sta scrivendo";
lng_users_typing: "{user1} e {user2} stanno scrivendo";
lng_many_typing: "{n} stanno scrivendo";
lng_unread_bar: "%1 messaggi non letti";

lng_maps_point: "Posizione";
lng_save_photo: "Salva immagine";
lng_save_video: "Salva video";
lng_save_audio: "Salva audio";
lng_save_document: "Salva documento";
lng_save_downloaded: "{ready} / {total} {mb}";
lng_duration_and_size: "{duration}, {size}";
lng_choose_images: "Scegli immagini";

lng_context_open_link: "Apri Link";
lng_context_copy_link: "Copia Link";
lng_context_open_email: "Scrivi a questo indirizzo";
lng_context_copy_email: "Copia indirizzo email";
lng_context_open_image: "Apri Immagine";
lng_context_save_image: "Salva Immagine con nome...";
lng_context_forward_image: "Inoltra Immagine";
lng_context_delete_image: "Cancella Immagine";
lng_context_copy_image: "Copia Immagine";
lng_context_close_image: "Chiudi Immagine";
lng_context_cancel_download: "Annulla Scaricamento";
lng_context_show_in_folder: "Mostra nella cartella";
lng_context_show_in_finder: "Mostra nel Finder";
lng_context_open_video: "Apri Video";
lng_context_save_video: "Salva Video con nome...";
lng_context_open_audio: "Apri Audio";
lng_context_save_audio: "Salva Audio con nome...";
lng_context_open_document: "Apri File";
lng_context_save_document: "Salva File con nome...";
lng_context_copy_text: "Copia Messaggio";
lng_context_forward_msg: "Inoltra Messaggio";
lng_context_delete_msg: "Cancella Messaggio";
lng_context_cancel_upload: "Annulla Caricamento";
lng_context_copy_selected: "Copia Selezione";
lng_context_forward_selected: "Inoltra Selezione";
lng_context_delete_selected: "Cancella Selezione";
lng_context_clear_selection: "Pulisci Selezione";
lng_really_send_image: "Vuoi inviare questa immagine?";

lng_forward_choose: "Scegli destinatario...";
lng_forward_confirm: "Inoltra a {recipient}?";
lng_forward_share_contact: "Condividi il contatto con {recipient}?";
lng_forward: "Inoltra";

lng_contact_phone: "Telefono";
lng_enter_contact_data: "Nuovo contatto";
lng_edit_group_title: "Modifica nome gruppo";
lng_edit_contact_title: "Modifica nome contatto";
lng_edit_self_title: "Modifica il tuo nome";
lng_confirm_contact_data: "Nuovo Contatto";
lng_add_contact: "Crea";
lng_add_contact_button: "Aggiungi contatto";
lng_contacts_header: "Contatti";
lng_contact_not_joined: "Purtroppo {name} non è ancora entrato in Telegram, ma puoi mandargli un invito.

Ti avviseremo quando uno dei tuoi contatti entra in Telegram.";
lng_try_other_contact: "Prova un altro";
lng_contacts_done: "Annulla";

lng_drag_images_here: "Trascina le immagini qui";
lng_drag_photos_here: "Trascina le foto qui";
lng_drag_files_here: "Trascina i file qui";

lng_drag_to_send_quick: "per inviare velocemente";
lng_drag_to_send_no_compression: "per inviare senza compressione";
lng_drag_to_send_documents: "per inviare come documenti";

lng_selected_clear: "Annulla";
lng_selected_delete: "Cancella";
lng_selected_forward: "Inoltra";
lng_selected_count_1: "%1 messaggio";
lng_selected_count_5: "%1 messaggi";
lng_selected_cancel_sure_this: "Vuoi annullare il caricamento?";
lng_selected_delete_sure_this: "Vuoi cancellare questo messaggio?";
lng_selected_delete_sure_1: "Vuoi cancellare %1 messaggio?";
lng_selected_delete_sure_5: "Vuoi cancellare %1 messaggi?";
lng_selected_delete_confirm: "Cancella";

lng_emoji_no_recent: "Gli emoji più recenti saranno qui";

lng_about_version: "Versione {version}";
lng_about_text: "Applicazione gratuita non ufficiale basata su [a href=\"https://core.telegram.org/mtproto\"]MTProto[/a] e
[a href=\"https://core.telegram.org/api\"]Telegram API[/a] per aumentare velocità e sicurezza

Questo software utilizza la licenza [a href=\"https://github.com/telegramdesktop/tdesktop/blob/master/LICENSE\"]GNU GPL[/a] versione 3,
i sorgenti sono disponibili su [a href=\"https://github.com/telegramdesktop/tdesktop\"]GitHub[/a].";
lng_about_done: "Chiudi";

// Mac specific

lng_mac_choose_app: "Scegli Applicazione";
lng_mac_choose_text: "Scegli un'applicazione per aprire il file \"{file}\".";
lng_mac_enable_filter: "Abilita:";
lng_mac_recommended_apps: "Applicazioni Consigliate";
lng_mac_all_apps: "Tutte le applicazioni";
lng_mac_always_open_with: "Utilizza sempre";
lng_mac_this_app_can_open: "Questa applicazione può aprire \"{file}\".";
lng_mac_not_known_app: "Non è certo che questa applicazione possa aprire \"{file}\".";

// Keys finished

**Comment by telegramdesktop** [comment]
Italian is in the languages list now.
