### ISSUE TITLE
[Feature Request] Donation Button or Bitcoin address: like "Buy a developer a cup of coffee."

### ISSUE THREAD

**Issue by lucribas** [telegramdesktop/tdesktop#480]
I really appreciate the tdesktop application and would like to support and say thanks to the developer team. :)
I am sure that many others users would like to support too.

We all know that open source projects run on time, not money. Said that, the purpose of donations would be used to buy things that help the developer like a book, a better monitor, etc.

That makes sense?

**Comment by stek29** [comment]
Try asking developer directly: https://telegram.me/preston
