### ISSUE TITLE
[Feature request] Notification on certain word

### ISSUE THREAD

**Issue by PASAf** [telegramdesktop/tdesktop#4800]
For now it is possible to disable notifications (for certain time or completely). But what I want is to receive notification if certain word appears in chat. This feature available in Skype from the beginning of time.
![Notification if word mentioned](https://i.imgur.com/2f0lfeZ.png)

**Comment by stek29** [comment]
See #4716

**Comment by PASAf** [comment]
Bullshit that it can't be done on client side. strstr is too hard for you?

**Comment by john-preston** [comment]
@PASAf It can be done client-side, but it won't be, sorry.

**Comment by PASAf** [comment]
@john-preston why?

**Comment by john-preston** [comment]
@PASAf Because it is too geeky / too non-widely-used to be brought in one of all official apps, without cloud sync or support from other platform official apps. This is a perfect example of a feature for some custom fork of this application.

**Comment by PASAf** [comment]
@john-preston do you have statistic or its just words?

**Comment by john-preston** [comment]
@PASAf I'm sorry, but this is obvious.

**Comment by stek29** [comment]
@PASAf Something tells me that official developer working for Telegram knows what majority of Telegram users is like better than you :)

**Comment by PASAf** [comment]
@john-preston I'm sorry, but this is dumb. More widely used app called Skype, bought for billions by Microsoft Corporation still supports this "too geeky not widely used function". I assume you use the opportunity to control at least something because of the awareness of your insignificance in this world.

**Comment by auchri** [comment]
@PASAf Well, if you don't stay polite and continue to personally attack people we have to ban you from this project.

Why don't you create a fork? If this function is so often needed then everyone will use your awesome fork!

**Comment by stek29** [comment]
> More widely used app called Skype, bought for billions by Microsoft Corporation still supports this "too geeky not widely used function"

I'm unable to find this function in latest release of Skype.
