### ISSUE TITLE
Video seeking not working

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#4802]
### Steps to reproduce
1. Play any video (for example 1:20 duration)
2. Seek to any position (e.g. seek to 45 sec after 5 seconds)

### Expected behaviour
Video should resume playing from the new position (45 sec)

### Actual behaviour
Video pauses at the current frame (at 5 sec), seekbar shows new position (45 sec).
Pressing `||` button continues playback from 5 sec, seekbar continues to show 45 sec position.

### Configuration
**Operating system:** Linux Mint 18.3

**Version of Telegram Desktop:** 1.3.1 alpha

**Used theme**: Any

**Comment by john-preston** [comment]
@aNNiMON Holy fuck. What about 1.3?

**Comment by aNNiMON** [comment]
@john-preston  1.3 works fine
