### ISSUE TITLE
[BUG] Call cancels

### ISSUE THREAD

**Issue by physbyte** [telegramdesktop/tdesktop#4804]
### Steps to reproduce
1. When someone will call me in Telegram, window with call info shows 1 second and the telegram cancels the call.

### Expected behaviour
Show window with call info for answer or cancel call.

### Actual behaviour
Window with call info shows 1 second and the telegram cancels the call.

### Addition
-- I can call, and everything will be fine.
-- In version 1.3.0, all is ok.
-- With or without proxy, i've had this problem.

### For reference
In Proxy Settings disappeared the checkbox "Use Proxy for calls".

### Feature request
Ability to disable pop-up window with call info.

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.3.1 Alpha
**Used theme**: Any

<details><summary><b>Logs</b>:</summary>
No logs for this period.
But i see logs like this:

[2018.06.06 03:32:04] Audio Info: recreating audio device and reattaching the tracks
[2018.06.06 03:32:09] Audio Info: Closing audio playback device.
[2018.06.06 03:32:19] Audio Info: recreating audio device and reattaching the tracks
[2018.06.06 03:32:20] Audio Info: Closing audio playback device.
[2018.06.06 03:32:20] Audio Info: recreating audio device and reattaching the tracks
[2018.06.06 03:32:22] Audio Info: Closing audio playback device.
[2018.06.06 03:32:22] Audio Info: recreating audio device and reattaching the tracks
[2018.06.06 03:32:23] Audio Info: Closing audio playback device.
[2018.06.06 03:32:23] Audio Info: recreating audio device and reattaching the tracks
[2018.06.06 03:32:25] Audio Info: Closing audio playback device.
[2018.06.06 03:32:26] Audio Info: recreating audio device and reattaching the tracks
[2018.06.06 03:32:28] Audio Info: Closing audio playback device.

</details>

**Comment by john-preston** [comment]
@physbyte What app is used to make call to you? Tdesktop, iOS, Android, maybe some X version?

**Comment by stek29** [comment]
Also: are you in Russia/China/Iran/other country trying to block Telegram? If yes, are you using socks proxy for calls?

**Comment by physbyte** [comment]
iOS

**Comment by physbyte** [comment]
@john-preston tested Android app and tdesktop, same.

**Comment by john-preston** [comment]
Thanks for your report! This will be fixed in the next version.

**Comment by physbyte** [comment]
@john-preston , how about "Ability to disable pop-up window with call info." ?
It really annoys, when I play video games etc, a window with call information pops up on top of all windows, at an inopportune moment, or I will have to make my own version each time?

**Comment by john-preston** [comment]
@physbyte Right now you can just disable calls in privacy and security.

**Comment by physbyte** [comment]
@john-preston , Yes, but this is not an option. We use the telegram as the only voice chat, and this option is general for all device.

I would like to have a local-storage option for the tdesktop to hide only the pop-up window, in other words, turn off the focus of the telegram window at the time of an incoming call. (sound - is ok)

I think I could do it myself, just add the parameter to the local-storage, and add the condition before the pop-up window is displayed, but then I lose auto-updates and I will have to compile telegrams each time.

For example:

```
void Panel::showAndActivate() {
	// get local storage from settings (example)
	_local_storage = getLocalStorageParams();

	toggleOpacityAnimation(true);
	raise();

	// if allowed to popup set active the window status
	if (_local_storage.call.allow.popup == true) {
		setWindowState(windowState() | Qt::WindowActive);
		activateWindow();
		setFocus();
	}

}
```
