### ISSUE TITLE
"Right-click" context menu disappears

### ISSUE THREAD

**Issue by bormolino** [telegramdesktop/tdesktop#4805]
If you make an right-click on the text-input the context menu disappears direct after moving up with the cursor to the "Formatting" entry on the menu. Moving cursor from above to field "Paste" is working.

Operating System: Ubuntu 16.04 LTS with unity

Telegram Desktop Version: 1.3

**Comment by Wasnix** [comment]
Same Bug in TG Desktop 1.3 on latest Linux: Debian (Buster)

Workaround: Use <Ctrl>+V

**Comment by aNNiMON** [comment]
#4749
