### ISSUE TITLE
Right-click menu in message composer closes when hovering over "Formatting" sub-menu 

### ISSUE THREAD

**Issue by Knusper** [telegramdesktop/tdesktop#4807]
### Steps to reproduce

  1.  Right-click in the "Write a message..." field.
  2. Move the pointer over the "Formatting" menu -> Formatting menu unfolds.
  3.  Move the pointer to another menu item (e.g. paste)

### Expected behaviour

 Other selected menu entry is highlighted and formatting menu disappears.

### Actual behaviour

 Complete right-click activated context menu disappears.

### Configuration
**Operating system:**

openSUSE Linux 42.3 - Plasma Desktop

**Version of Telegram Desktop:**

3.1 installed via flatpak / flathub - also opened an issue in their bugtracker:
https://github.com/flathub/org.telegram.desktop/issues/35

**Used theme**:

Dark. 

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@Knusper Thanks for the report. This will be fixed in the next version.

**Comment by stek29** [comment]
#4749
