### ISSUE TITLE
The unsent message becomes a media captions.

### ISSUE THREAD

**Issue by Edicksonjga** [telegramdesktop/tdesktop#4808]
### Steps to play
1. Write a message and do not send it.
2. Load a file / paste / Ctrl + V / drag
3. The previously written message becomes a subtitle of the medium to be sent.
4. If you send the uploaded file the written message disappears.

### Expected behavior
When loading the file, the previously written message should not become the subtitle of the medium and much less delete if you send to the file loaded. It used to be like that.

### Real behavior
When loading the file what was written as a message becomes the subtitle and if you send the loaded file the message before disappears as it has become the subtitle of the file.

### Configuration
**Operating system:**

Windows 7 Ultimate

**Version of Telegram Desktop:**

Stable Version 1.3
Version Alpha 1.3.1 and 3 or 4 previous versions.

**Used theme**:

By default and in Night mode.

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by MasterGroosha** [comment]
Well, this is a feature which was requested at least twice (#3355 and #2725). Honestly it's much easier to clear caption field (<kbd>Ctrl</kbd>+<kbd>A</kbd>) and paste new text than copy caption text by hand (because your clipboard holds image).

**Comment by stek29** [comment]
@MasterGroosha btw, iirc Tab allows you to switch between caption and message input areas
