### ISSUE TITLE
Chat messages are all in one side when in 1920x1080 resolution

### ISSUE THREAD

**Issue by eduardo211** [telegramdesktop/tdesktop#4809]
### Steps to reproduce
1.  Open Windows 10 Telegram Desktop App
2.  Maxime Telegram on Full HD Monitor (1920x1080)

### Expected behaviour
The messages I sent usually appear on the right side of the window and the messages I received on the left side of the window.

### Actual behaviour
All the messages (sent and received) appear on the left side of the window.

### Configuration
**Operating system:**
Windows 10 Home 64 bits Version 1803

**Version of Telegram Desktop:**
1.3

**Used theme**:
Default

### Obs
I couldn't replicate this issue on the Linux operating system and things work normally on smaller resolutions.

**Comment by MasterGroosha** [comment]
Please, PLEASE use search next time.

Open window as big as possible, go to settings and (un)check "Alternative layout for wide screen"

**Comment by stek29** [comment]
I bet @auchri would love this
