### ISSUE TITLE
Clicking message notification raises the window, but does not focus on it

### ISSUE THREAD

**Issue by AndydeCleyre** [telegramdesktop/tdesktop#481]
This is seen using kwin 5.2.0.1, plasma-framework 5.6.0 and plasma-workspace 5.2.0.

The effect is that, when a message is received and the notification is clicked, the user can see the message, but attempting to type a response will not affect the telegram window until the cursor is moved to hover over it.

**Comment by AndydeCleyre** [comment]
@john-preston I started to look into this and my best guess was that we needed to add `App::wnd()->activateWindow();` to the [Manager::notificationActivated](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/window/notifications_manager.cpp#L80) method.

Before bothering to go through the build process to test, I first wanted to reproduce the issue, and I could not; I tried via the reply button in the native notifications, then via the body of the foreign notifications; I tried with the window hidden (to tray) and the window unhidden but not raised. I was using Plasma desktop `5.8.4`.

I won't close this issue, because I know at least @gordeevart is still experiencing it with Gnome.

I could not test via the body of the native notifications, as the behavior in Plasma for that is to simply hide the notification, not raise the window.

**Comment by AndydeCleyre** [comment]
@gordeevart Would you consider the following to be a solution, if it works?

You can change Gnome's global focus-stealing policy between `smart` and `strict`, with the default being `smart`. I've seen people recommend switching to `strict` to accomplish completely contradictory goals, so I can't say what exactly the expected behavior is, but you can change it with:

```bash
gsettings set org.gnome.desktop.wm.preferences focus-new-windows 'strict'
```

**Comment by GordeevArt** [comment]
Yes. It works! I think it would be enough. Thank you.

**Comment by AndydeCleyre** [comment]
Great. In that case, since I opened this in the first place, I'll go ahead and close it.

**Comment by stek29** [comment]
Still having this issue with XFCE on Arch.
Also, I don't think that issue was fixed, we just found a workaround.

**Comment by AndydeCleyre** [comment]
@stek29 It's hard (for me) to say definitively whether this is a bug, as the window focus behavior is sort of a negotiation between apps and the window manager, not completely controlled by either. If that setting does not work for you, I'll re-open and perhaps you want to try building with the additional method call I mentioned.

If your setting change *does* work, let me know if you still think this should be reopened, and please post the procedure for changing that setting here so searchers can find it.

**Comment by stek29** [comment]
@AndydeCleyre about the procedure: http://docs.xfce.org/xfce/xfwm4/preferences#focus
I'll try it next time I boot into Linux.
