### ISSUE TITLE
[BUG] enable proxy

### ISSUE THREAD

**Issue by physbyte** [telegramdesktop/tdesktop#4811]
### Steps to reproduce
1. Open tdesktop
2. Click on the link like: tg://socks... or https://t.me/socks... for enable proxy.

### Expected behaviour
Opening the dialog box with proxy settings for confirm.

### Actual behaviour
Nothing.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.3.2 Alpha

**Used theme**: Any

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by physbyte** [comment]
@john-preston,yesterday I made a clean install of 1.3.1 and added 3 proxy without problem.

**Comment by john-preston** [comment]
@physbyte Yes, thanks for the report. I'll fix that in the next version, I hope I'll deploy it in a couple of hours.

**Comment by physbyte** [comment]
@john-preston , I looked at the change log #3565953, the inability to send a file from windows is also associated with the "Passcode"?

### Steps to reproduce
1. Select any file to send to Telegram (in Windows) 
2. Right Click on the file > Send to > Telegram

### Expected behaviour
Opening the window with the recipient's choice to send the file.

### Actual behaviour
The window becomes active

**Comment by physbyte** [comment]
@john-preston Yes. Tested right now, it will work without passcode.
