### ISSUE TITLE
Telegram service is not working on any platform.. even website

### ISSUE THREAD

**Issue by ahmadkakarr** [telegramdesktop/tdesktop#4813]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@ahmadkakarr Works for me ¯\_(ツ)_/¯

**Comment by stek29** [comment]
Is Pakistan blocking TG too?
