### ISSUE TITLE
Cannot delete message in group chat

### ISSUE THREAD

**Issue by royryando** [telegramdesktop/tdesktop#4815]
I join a group (super group) and I'm as Admin (without delete message privilege).
Someone(Admin) send an inconvenient picture and I hate it but I can't delete it, this should be a consideration for you. Thank you

**Comment by john-preston** [comment]
@royryando Well, you don't have delete message privilege, so you can't delete messages. I don't understand your problem here. If you don't like the message that much you can always leave the group or clear its history for yourself.

**Comment by royryando** [comment]
No, I mean like "Delete for me only" feature.

**Comment by john-preston** [comment]
@royryando It is not supported by API, sorry.

**Comment by royryando** [comment]
ah.. btw is the Telegram API open source?

**Comment by john-preston** [comment]
@royryando API implementation (server side) is not open source. Some parts of server side code is open source, like mtproto proxy implementation, but not the code of API methods.
