### ISSUE TITLE
Context menu on input line unexpectedly closes after lose cursor focus

### ISSUE THREAD

**Issue by mubat** [telegramdesktop/tdesktop#4816]
###Summary 
Context menu spontaneously closes after losing focus on opened submenu.
On gif mouse clicks was only on input line
![telegram-context-menu](https://user-images.githubusercontent.com/3623986/41147126-32ccd5ea-6b0e-11e8-9d78-ddbb4ceb0f01.gif)

### Steps to reproduce
1. Open context menu on chat input line
2. Navigate cursor to `Formatting` item
3. Navigate cursor to other context menu item

### Configuration
**Operating system:** Linux Mint 18.3 x64 Cinnamon
**Version of Telegram Desktop:** v 1.3
**Used theme**: standart

**Comment by stek29** [comment]
#4749

**Comment by john-preston** [comment]
@mubat Please try the latest alpha version from https://desktop.telegram.org/changelog#alpha-version I hope it has this bug fixed.

**Comment by mubat** [comment]
@john-preston on 1.3.5 alpha works fine
