### ISSUE TITLE
No focus on open file dialog

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#4817]
### Steps to reproduce
1. Press **Open file** button.
2. 
3. 

### Expected behaviour
Open file dialog must get focus.

### Actual behaviour
No focus on Open File dialog. On version 1.3.0 stable everything works fine.

### Configuration
**Operating system:** Fedora 28 with KDE Plasma 5.12

**Version of Telegram Desktop:** 1.3.4 alpha

**Used theme**: none

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by xvitaly** [comment]
@john-preston I think this issue need to be fixed before releasing stable version?

**Comment by john-preston** [comment]
@xvitaly 🤔 Skipped that.
