### ISSUE TITLE
Cannot use scim keyboard for other languages.

### ISSUE THREAD

**Issue by seokbeomKim** [telegramdesktop/tdesktop#482]
I used to use scim keyboard to input Korean characters. 
However, it doesn't work in the telegram application even though I can input Korean character in other QT based programs.

**Comment by mxa** [comment]
Seems like the issue isn't related to the input method. I use IBUS for Korean input and it isn't working either.

**Comment by ustcltx** [comment]
The same issue to #375

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.
