### ISSUE TITLE
End to end encryption is not enabled

### ISSUE THREAD

**Issue by s777s** [telegramdesktop/tdesktop#4820]
### Steps to reproduce
1. Start Telegram client an year ago
2. Start Telegram today
3. Nothing changes! Can't start encrypted end to end chat.

### Expected behaviour
I should be able to start secure end to end encrypted chat.

### Actual behaviour
Desktop version of telegram is unable to simply start encrypted chat.

### Configuration
Any linux distro

Latest version of application from github

**Comment by RadRussianRus** [comment]
Duplicate of #5.

**Comment by omkarnathsingh** [comment]
wow. 4 years and no change :D
