### ISSUE TITLE
Telegram for Desktop adds ♂ after the 🧟 emoji.

### ISSUE THREAD

**Issue by onkarjit** [telegramdesktop/tdesktop#4821]
I typed today the 🧟‍♂️ emoji on my iPhone and I noticed that Telegram for Desktop adds ♂ behind it.

On the iOS, Android and Telegram for MacOS it looks like:

<img width="61" alt="image" src="https://user-images.githubusercontent.com/26631593/41189874-c8c9eb02-6bd4-11e8-99de-bcb33826b71d.png">

On Telegram for Desktop on MacOS I see the following:

<img width="137" alt="image" src="https://user-images.githubusercontent.com/26631593/41189889-f5ef72aa-6bd4-11e8-98ca-42fda5fe876c.png">

On Telegram for Desktop on Windows it looks like:

![image](https://user-images.githubusercontent.com/26631593/41189811-ffa6abc0-6bd3-11e8-97e1-f96ac242f4c5.png)

Telgram for Desktop adds ‍♂ behind the emoji for some reason both on Windows and MacOS.

**Comment by stek29** [comment]
> Telgram for Desktop adds ‍♂ 

No, it doesn't add it, iOS does. Try sending it to https://t.me/UnicodeInfoBot, or just copying it and doing `pbpaste|hexdump`:

```
U+1F9DF ZOMBIE
U+200D ZERO WIDTH JOINER
U+2642 MALE SIGN
U+FE0F VARIATION SELECTOR-16
```

Try to send this: 🧟.

TDesktop does not support zombie emoji yet, so system gets to draw it, but not the zero-width joiner + male sign.

#3966
