### ISSUE TITLE
Telegram for Desktop should make use of Apple Emojis to keep uniformity

### ISSUE THREAD

**Issue by onkarjit** [telegramdesktop/tdesktop#4822]
This is more of a feature request. The official Android Telegram app already uses Apple emoji images instead of displaying platform-native emojis, it would be great if Telegram for Desktop would do this too keep uniformity. Also so that Telegram for Desktop won't have issues like #4821.

**Comment by john-preston** [comment]
@onkarjit It does display Apple emoji. They just weren't updated for a couple of iOS versions :(

**Comment by omkarnathsingh** [comment]
What about this issue? https://github.com/telegramdesktop/tdesktop/issues/3966

Moreover now Unicode 11 has also come.

**Comment by john-preston** [comment]
@omkarnathsingh Well, the same. Newly added aren't yet in tdesktop.

**Comment by onkarjit** [comment]
@john-preston what is causing this delay?

**Comment by john-preston** [comment]
@onkarjit Lack of time.
