### ISSUE TITLE
Telegram X getting stuck after taking a picture

### ISSUE THREAD

**Issue by eggScallion** [telegramdesktop/tdesktop#4826]
### Steps to reproduce
1. Click on "paper clip" icon
2. Click on "camera" icon
3. Take a picture
4. Stucks

### Expected behaviour
It should send the photo that has been taken

### Actual behaviour
The app stucks. Wherever I click, nothing happens. When I click on the "->" icon to send the picture  and restart the app, sometimes the picture has been sent.

### Configuration
Device: Iphone 4
OS Version: 10.3.3

 
**Version of Telegram App:**
App Version "Telegram X"

**Comment by john-preston** [comment]
@eggScallion Sorry, this repository is only about Telegram Desktop, not Telegram in general.

**Comment by stek29** [comment]
See https://t.me/tgiostests

**Comment by eggScallion** [comment]
@john-preston Sorry, didn't see :/
@stekt28 thank you ^^
