### ISSUE TITLE
Half width Top bar

### ISSUE THREAD

**Issue by ahmadmn** [telegramdesktop/tdesktop#4828]
### Steps to reproduce
1. Run Telegram and every thing is Ok
2. Minimize Telegram then Maximize
3. After Maximizing  the top bar will be half width

### Expected behaviour
Top bar must be full width to avoid interfere with resize button of apps behind of Telegram

### Actual behaviour
I want to close Telegram, but the app behind it will be closed.

### Configuration
**Operating system:**
Windows 10 Pro 64bit build 17134

**Version of Telegram Desktop:**
1.3
**Used theme**:
default
![image](https://user-images.githubusercontent.com/5241132/41196766-15b9a00e-6c5e-11e8-8539-7eff6fa85c31.png)

**Comment by stek29** [comment]
#4649
