### ISSUE TITLE
Tilde renders as dash in message field

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#4829]
### Step to reproduce
Type tilde (~) in message field

### Expected behaviour
It should be shown as tilde (~)

### Actual behaviour
It shows as dash (–)

### Configuration
**Operating system:** Windows 7 x64
**Version of Telegram Desktop:** 1.3

**Comment by stek29** [comment]
Not again...

**Comment by MasterGroosha** [comment]
However it renders as it should be in mediafile captions.

**Comment by ThigSchuch** [comment]
Happening here v1.3.7 - Windows 8.1
I was searching about it to report.

**Comment by tarcisioe** [comment]
Happening to me on both Linux and Windows 10.

**Comment by namikiri** [comment]
Can reproduce, version 1,3,7, OS Windows 10 x64.

![Dash Bug](https://i.imgur.com/CMKmuXT.png)
