### ISSUE TITLE
Theme editor: entering values doesn't change color

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#4831]
### Steps to reproduce
1. Open theme editor
2. Open any color
3. Try enter value in any field

### Expected behaviour
Color will change as you enter value

### Actual behaviour
Color not changes even after you save

### Configuration
**Operating system:** Windows 7 x64
**Version of Telegram Desktop:** 1.3

**Comment by john-preston** [comment]
@RadRussianRus Thanks for your report! Please try the latest alpha version from https://desktop.telegram.org/changelog#alpha-version, I hope it is fixed there.

**Comment by RadRussianRus** [comment]
@john-preston Seems it's fixed in latest 1.3.5 alpha.

**Comment by Aokromes** [comment]
close since 1.3.7 stable is already live?
