### ISSUE TITLE
Cannot build, openal-soft in Linux

### ISSUE THREAD

**Issue by OmidMahmoudi** [telegramdesktop/tdesktop#4832]
I encountered a problem when compiling openal-soft.
where is the problem from?
![screenshot from 2018-06-11 03-19-33](https://user-images.githubusercontent.com/19889603/41207247-5ff5333a-6d27-11e8-93c3-bd6d43f1468a.png)

**Comment by stek29** [comment]
Are XOrg libs installed?

**Comment by Aokromes** [comment]
no answer for over a year, closing.
