### ISSUE TITLE
Tray Icon change forever

### ISSUE THREAD

**Issue by necronoise** [telegramdesktop/tdesktop#4833]
### Expected behaviour
Hello everyone, I want to know if its possible to change tray icons forever, I want to make this blue Telegram icon to be black.

### Actual behaviour
I tryied to change by myself and it actually work, but everytime telegram launch, he create a new icon with a red retangle and white numbers (to update my chat account). Can I like stop this numbers and make it show only the icon?

### Configuration
**Operating system:** manjaro i3

**Version of Telegram Desktop:** v 1.3 01.06.18

**Used theme**: Incognito by @IncognitoTheme

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by RadRussianRus** [comment]
See #1908.
