### ISSUE TITLE
[noissue] Telegram now working under Haiku

### ISSUE THREAD

**Issue by sixtyfive** [telegramdesktop/tdesktop#4834]
Hi dear Telegram devs! Via https://www.haiku-os.org/blog/waddlesplash/2018-06-06_haiku_monthly_activity_report_-_052018/, this is just to inform you that Telegram Desktop is now working under Haiku. Apparently they wouldn't mind if that fact happened to appear in some news item somewhere ;-) (see comments on linked page)

**Comment by stek29** [comment]
That's great news, I'm glad to hear it :)
I have been reading on BeOS some time ago and I'm glad to see BeOS inspired OS being actively developed.

However I'm closing this issue to keep the issues section clean, thanks for sharing once again.
