### ISSUE TITLE
[Feature Request] Link by username

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#4835]
When you copy username, it copies in `@username` format. But to use it in link, you'll need to type full `https://t.me/username` format.

Suggestion: if user types `@username` in link field, convert it to `https://t.me/username` format.

**Comment by Lonami** [comment]
But it *is* a username, not a link. Typing "t.me/" (5 characters) shouldn't be much issue.

**Comment by RadRussianRus** [comment]
> But it is a username, not a link.

So? It could convenient way to insert channel/group/user link.

**Comment by RadRussianRus** [comment]
There is no need for this, I guess.
