### ISSUE TITLE
Cannot send tg:// link with custom title

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#4836]
### Steps to reproduce
1. Create a link with any title and any `tg://` link
2. Send it

### Expected behaviour
Message will be with correct `tg://` link

### Actual behaviour
`tg://` link converts to plain text

### Configuration
**Operating system:** Windows 7 x64
**Version of Telegram Desktop:** 1.3.6 alpha

**Comment by john-preston** [comment]
@RadRussianRus Currently those links are not supported (so they get stripped out) by server :( I hope they'll be allowed soon.

**Comment by RadRussianRus** [comment]
@john-preston Could they possibly be converted to `t.me` as a temporary solution?

**Comment by john-preston** [comment]
@RadRussianRus Please try again. I was told that it should work now.

**Comment by RadRussianRus** [comment]
@john-preston I confirm that it works now.
