### ISSUE TITLE
[Linux, GTK] Main window opens in higher position than it was before closing

### ISSUE THREAD

**Issue by sherba800** [telegramdesktop/tdesktop#4837]
### Steps to reproduce
1. Download linux version from official site or from here https://github.com/telegramdesktop/tdesktop/releases
2. Run it in some GTK based environment (see configuration)
3. Close window and try to open it again

### Expected behaviour
When the telegram window is closed/minimized to tray and then opened again from tray/shortcut/terminal it should be in the same place!

### Actual behaviour
When the telegram window is closed/minimized to tray and then opened again from tray/shortcut/terminal it is a bit higher than it used to be before closing. As far as much i tried to reproduce the bug in different desktop environments this behaviour appers on some GTK based environments like cinnamon and xfce. I recorded this strange behaviour https://vimeo.com/274585523

### Configuration
Linux Mint (cinnamon and xfce) and Debian (cinnamon and xfce).
Telegram any version from official site.

**Comment by Aokromes** [comment]
maybe generic bug #1189

**Comment by cranes-bill** [comment]
This behavior is completely reproducible with **VLC** _(don't have other Qt application to try with)_, so for me, it's a **Qt issue**.
