### ISSUE TITLE
Increase emoji size to 20x20 px

### ISSUE THREAD

**Issue by kleuter** [telegramdesktop/tdesktop#484]
I can hardly distinguish all these 16x16px emoji in the popup palette even with a good eye vision. Why not to increase their size to 20x20px (e.g.Skype). Addionally it would be nice to have a **tooltip** under each emoj

Telegram Windows (Qt):
![sshot-2015-04-27- 07-56-37](https://cloud.githubusercontent.com/assets/2600624/7342349/f5c150f4-ecb2-11e4-9b76-46b8d07ebe2f.png)

Telegram Mac (native):
![tel_mac](https://cloud.githubusercontent.com/assets/2600624/7385884/5d575d3a-ee4d-11e4-8c54-33676174fab1.png)

Skype:
![Skype emoji](http://s7.postimg.org/c8kym5s0b/skype_smiles.png)

**Comment by sander85** [comment]
I have to agree here, It's quite impossible to distinguish different emojis and understand what one wants to say with them.

**Comment by rezapc** [comment]
+1

**Comment by vm2mv** [comment]
:+1:

**Comment by dufreyne** [comment]
it would be also nice to have a **tooltip* for each emoj

**Comment by joshery420** [comment]
:+1:

**Comment by kleuter** [comment]
See comparison with mac version in the first post

**Comment by kleuter** [comment]
Seems to have been fixed in the latest beta

**Comment by 24252411** [comment]
EN QUE IDIOMA TENGO QUE DECIR QUE QUIERO CANCELAR MI CUENTA , AHORA Y POR SIEMPRE ? QUE TERQUEDAD LA CANCELO Y VUELVEN A PREGUNTARME  Y DESPUESME APARECE REABIERTA QUE PESADILLA CON USTEDES
gaira.bohorquez@gmail.co

**Comment by kleuter** [comment]
0.8.13 still small emojs in chat
