### ISSUE TITLE
 Rotate Images/Photos/Graphics, Feature Request

### ISSUE THREAD

**Issue by patricmutwiri** [telegramdesktop/tdesktop#4840]
### Steps to reproduce
1. View an image taken in landscape, meant to be portrait

### Expected feature
I need to be able to rotate this image, for legibility purposes.

### Actual behaviour
I download the image, then start editing it to rotate. 

#4839

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1413
