### ISSUE TITLE
Please enable AUTOPLAY for Audio and Video Messages

### ISSUE THREAD

**Issue by DavidRizzo** [telegramdesktop/tdesktop#4842]
Please, I use this for meetings and this would make the meetings flow so much nicer.  Let it be able to be set per chat and per group.  This isn't that hard of a fix.

 
### Steps to reproduce
1.   audio comes but does not play until you click it
2. 
3. 

### Expected behaviour
Tell us what should happen
Audio or video should automatically as soon as it comes in without having to click it

### Actual behaviour
Tell us what happens instead
NOTHING

### Configuration
**Operating system:**
Windows 10, iPhone and Android

**Version of Telegram Desktop:**
1.3.7

**Used theme**:
none

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Aokromes** [comment]
No without a setting. I have telegram opened 24/7 on a computer on my bedroom.

**Comment by stek29** [comment]
feel free to make telegram as a whole add this, and then it might be in tdesktop too.
ask tg on twitter or via in-app support
