### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by P-Alban** [telegramdesktop/tdesktop#4843]
### Steps to reproduce
1. Open some chat
2. Write @
3. Press ESC 2 times

### Expected behaviour
Empty area with "Please select a chat to start messaging"

### Actual behaviour
![]( https://i.imgur.com/5ZTbmz5.png)

### Configuration
**Operating system:** win 7

**Version of Telegram Desktop:** 1.3.7

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Lonami** [comment]
Can reproduce.

**Comment by MasterGroosha** [comment]
It seems to be fixed, right?

**Comment by Aokromes** [comment]
yes.
