### ISSUE TITLE
links from browser not open chat/channel

### ISSUE THREAD

**Issue by ERcapi** [telegramdesktop/tdesktop#4844]
[log_start9.txt](https://github.com/telegramdesktop/tdesktop/files/2095328/log_start9.txt)
[log_start9.txt](https://github.com/telegramdesktop/tdesktop/files/2095331/log_start9.txt)

 
### Steps to reproduce
1. Example: https://t.me/ercapi
2. the link open telegram desktop
3. But not open the channel or user or else.

### Expected behaviour
Tell us what should happen, should open a expecific channel

### Actual behaviour
Tell us what happens instead: open telegram destop, not channel

### Configuration
**Operating system:** Win 10 64

**Version of Telegram Desktop:** 1.3.7

**Used theme**: default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by RadRussianRus** [comment]
@ERcapi You have incomplete command line to open links with `tg://` protocol.
Open `regedit.exe`, go to `HKEY_CLASSES_ROOT\tg\shell\open\command`.
Your `(Default)` value probably looks like this:
`"C:\Users\ercap\AppData\Roaming\Telegram Desktop\Telegram.exe" "%1"`
However, you should add `--` before `"%1"` like this:
`"C:\Users\ercap\AppData\Roaming\Telegram Desktop\Telegram.exe" -- "%1"`

**Comment by ERcapi** [comment]
Thanks for your response. Appear like you said, however I wrote the line as you wrote. I suppose i have to reboot to aply changes isn't it?

**Comment by ERcapi** [comment]
Thanks for your response. Appear like you said, however I wrote the line as you wrote. I suppose i have to reboot to aply changes isn't it?. 

EDIT: I've just tried your solution but it doesnt work. Same problem. Any idea?

**Comment by Aokromes** [comment]
cannot reproduce, anyone else have this issue?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
