### ISSUE TITLE
libxcb.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dsokolov** [telegramdesktop/tdesktop#4846]
### Steps to reproduce
1. Run `./Telegram`

### Expected behaviour
Telegram starts as usual.

### Actual behaviour
`./Telegram: error while loading shared libraries: libxcb.so.1: cannot open shared object file: No such file or directory`

### Configuration
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

**Version of Telegram Desktop:**
1.3.7 for Linux 64-bit

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Note**
Telegram 1.2.* works well.

**Comment by dsokolov** [comment]
Note: Telegram 1.2.* works well.

**Comment by Aokromes** [comment]
this bug was fixed long time ago.
