### ISSUE TITLE
Sticker check marks removed and only accessible on mouse over in latest update

### ISSUE THREAD

**Issue by felixfoertsch** [telegramdesktop/tdesktop#4847]
### Steps to reproduce
1. Open any chat with stickers in it
2. See that the stickers have no check marks
3. Mouse over the stickers

### Expected behaviour
The check marks should always be visible.

### Actual behaviour
The check marks are only visible on mouse over.

### Configuration
**Operating system:** macOS High Sierra, Windows 10

**Version of Telegram Desktop:** 1.3.7

**Comment by john-preston** [comment]
@felixfoertsch This was highly demanded somewhere around the issues.

**Comment by felixfoertsch** [comment]
Then it should be an option imho. Stickers are a vital part of my chats and one of the main reasons why I use Telegram. So -- to me -- it is important to know, whether a sticker has been received or not.

**Comment by john-preston** [comment]
@felixfoertsch Perhaps it could be done that way only on received stickers.

**Comment by Remu-rin** [comment]
> This was highly demanded somewhere around the issues.

https://github.com/telegramdesktop/tdesktop/issues/3636
> it is important to know, whether a sticker has been received or not.

You still see checks on sidebar. If the last message is not by you, you probably don't need them, right?
Also you never saw them on gifs and on photos without captions. Stickers behavior was inconsistent and ruined many of them, most of all those with text at the bottom. I also heard that current behavior was in 2016 and before already, but changed at some moment.
If anything, checks should be moved out of image area. Then no reason to hide them.

**Comment by felixfoertsch** [comment]
> You still see checks on sidebar. If the last message is not by you, you probably don't need them, right?

I don't have a sidebar, since I use telegram to the far left of the screen. I basically use Telegram on the desktop the same way like on mobile.

> If anything, checks should be moved away out of image area. Then no reason to hide them.

This sounds reasonable. Move the time stamp below the stickers (and images) with a translucent background maybe?
