### ISSUE TITLE
System panel conflicts with your replaced panel on Windows 7 (classic theme)

### ISSUE THREAD

**Issue by r57zone** [telegramdesktop/tdesktop#4848]
System panel with system buttons conflicts with your replaced panel on Windows 7 with classic theme.
![](https://user-images.githubusercontent.com/9499881/41354256-910fbc42-6f2f-11e8-9ccd-4ab177c27ffd.png)
![](https://user-images.githubusercontent.com/9499881/41354258-9145e790-6f2f-11e8-975e-2ce628d6b2c4.png)

### Steps to reproduce
1. Set theme to classic
2. Minimize tdesktop, move tdesktop or etc

### Configuration
**Operating system:** Windows 7  (Classic theme)

**Version of Telegram Desktop:** 1.2.17

**Used theme**: Default

**Comment by stek29** [comment]
how do other apps with custom titlebar (like discord) look like?

**Comment by stek29** [comment]
@r57zone is discord's custom titlebar used or windows' one is?

**Comment by r57zone** [comment]
@stek29 custom

**Comment by r57zone** [comment]
I think it is not necessary to fix it already, since Windows 7 is ending its support period, and on 10k there is no classic theme.
