### ISSUE TITLE
Touchpad doesn't working on telegram desktop for Windows 10

### ISSUE THREAD

**Issue by nildes** [telegramdesktop/tdesktop#4849]
### Steps to reproduce
1. Open Telegram
2. Open a conversation
3. Try to scroll up and down

### Expected behaviour
Tell us what should happen
The conversation should go up and down
### Actual behaviour
Tell us what happens instead
Anything Happen

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.3.7
**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Aokromes** [comment]
#2726

**Comment by akhil1234567** [comment]
Nothing happens while scrolling......looks like the touchpad is not working........

**Comment by fortunereject** [comment]
Here's my [workaround](https://github.com/telegramdesktop/tdesktop/issues/2726#issuecomment-416585784)
