### ISSUE TITLE
Message Editing

### ISSUE THREAD

**Issue by P-Alban** [telegramdesktop/tdesktop#4860]
### Steps to reproduce
1. Open some chat
2. Write some code
3. Press edit, then Enter

### Expected behaviour
Tell us what should happen

### Actual behaviour
![](http://g.recordit.co/PcdFbLnLo5.gif)

### Configuration
**Operating system:** win 7 

**Version of Telegram Desktop:** 1.3.7

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@P-Alban ¯\_(ツ)_/¯

**Comment by Lonami** [comment]
Can't reproduce this under 1.3.9 alpha.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by P-Alban** [comment]
Nope
