### ISSUE TITLE
Bug the written text itself is cleared

### ISSUE THREAD

**Issue by ghost1372** [telegramdesktop/tdesktop#4861]
Hi when writing (most of the time when typing fast), the written text itself is cleared
### Configuration
**Operating system:**
Windows 10 17692 64bit
**Version of Telegram Desktop:**
1.3.7
**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/2108985/log.txt)

</details>
you can see behavior in gif<br>
![untitled 2](https://user-images.githubusercontent.com/9213496/41508205-249a89aa-7256-11e8-9953-0bf3d75c3794.gif)

**Comment by stek29** [comment]
#4845
