### ISSUE TITLE
Proper highlight for specific photo in album

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#4864]
### Steps to reproduce
1. Send message with "Reply" to photo in album
2. Click cited photo

### Expected behaviour
After scrolling this photo in album should be highlighted

### Actual behaviour
After scrolling highlight occurs for whole album, but not for specific photo

### Configuration
**Operating system:** Windows 7 x64
**Version of Telegram Desktop:** 1.3.7

**Comment by john-preston** [comment]
@RadRussianRus Current highlighting is done as highlighting the outside area of the message, you need some different highlight for it to work inside the message bubble.

**Comment by RadRussianRus** [comment]
@john-preston I understand. Is it hard to implement?

**Comment by RadRussianRus** [comment]
There is no need in closing it.

**Comment by RadRussianRus** [comment]
Actually it's already done, so I'm closing it myself.
