### ISSUE TITLE
Download images of contact

### ISSUE THREAD

**Issue by Tommy1991** [telegramdesktop/tdesktop#4865]
what is the function for Downloading all images of contacts? i can save just the first one with calling 

`while (!photoData->loaded())`
`			{`
`				clock_t endwait;`
`				endwait = clock() + 1 * CLOCKS_PER_SEC;`
`				while (clock() < endwait) {}`
`			}`
`			photoData->full->pix().toImage().save(iname + mname + pname, "PNG");`

in ApiWrap::userPhotosDone function

can anyone help?

**Comment by stek29** [comment]
just use normal libs for telegram api ffs
