### ISSUE TITLE
Cannot click on emoji (at least under Linux)

### ISSUE THREAD

**Issue by LDVSOFT** [telegramdesktop/tdesktop#4866]
### Steps to reproduce
1. Open any chat
2. Open emoji tray
3. Try to click any of them

### Expected behaviour
It clicks and adds an emoji to input field

### Actual behaviour
It does not...

### Configuration
**Operating system:** Ubuntu 18.04

**Version of Telegram Desktop:** 1.3.7

**Used theme**: *(default)*

**Comment by Zeka13** [comment]
Same Ubuntu 18.10

**Comment by Aokromes** [comment]
this bug is still valid? another ticket stated it was fixed
https://github.com/telegramdesktop/tdesktop/issues/5658

**Comment by Aokromes** [comment]
no answer after months, closing.
