### ISSUE TITLE
Telegram desktop couldn't use MPROTO and SOCKS5 proxies for sending crash reports.

### ISSUE THREAD

**Issue by NTMan** [telegramdesktop/tdesktop#4867]
### Steps to reproduce
1. Produce Telegram crash
2. Try send crash report when Telegram servers blocked by RKN
3. 

### Expected behaviour
Expected that Telegram can use all proxy servers which already used for primary work.

### Actual behaviour
Telegram use another proxy server and couldn't support MPROTO and SOCKS5.

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.3.7 Alpha

**Used theme**: Default

**Actual proxy server dialog**:
![19 06 2018 10-19-48 032](https://user-images.githubusercontent.com/200750/41579029-8f6c6196-73ae-11e8-8657-aa87873ea32e.jpg)

**Expected proxy server dialog**:
![19 06 2018 10-37-53 909](https://user-images.githubusercontent.com/200750/41579033-94e4ad04-73ae-11e8-8b76-b1a014c8bd30.jpg)

**Comment by john-preston** [comment]
@NTMan Crash reports can't be sent by mtproto, because the whole system is not launched yet when we check for the reports.

Socks5 is not supported in that dialog box and that could be fixed indeed.

Thanks for your report.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by NTMan** [comment]
> this issue is still valid?

yes

**Comment by NTMan** [comment]
issue is actual

**Comment by NTMan** [comment]
the feature request still actual

**Comment by NTMan** [comment]
the feature request still actual

**Comment by NTMan** [comment]
the feature request still actual

**Comment by NTMan** [comment]
This problem is still actual.
