### ISSUE TITLE
Move emoji button to the left

### ISSUE THREAD

**Issue by lapo-luchini** [telegramdesktop/tdesktop#4868]
I'd like to propose to move the "emoji button" to the left of the message input field, as it's very easy to accidentally hover it and it then covers much part of the message area, and the mouse have to be moved elsewhere altogether to try again, e.g. pressing the "fast forward" button to go the bottom of a very long chat. 

I'd suggest something like this:
![image](https://user-images.githubusercontent.com/420454/41592023-a6fa6472-73bb-11e8-8146-015b4506b2af.png)

### Steps to reproduce
1. open a huge chat with hundreds of uninteresting messages
2. try to reach for the "fast forward" button
3. being under the window with the mouse point, inadvertently pass over the emoji button
4. being impossibilitated to click "fast forward" because it has been covered by emoji temporary panel
5. say harsh words
6. try again

![image](https://user-images.githubusercontent.com/420454/41591881-40e18e90-73bb-11e8-9b38-43e634de52ff.png)

### Expected behaviour
Being able to easily click on "fast forward".

### Actual behaviour
Having difficulties with it.

### Configuration
**Operating system:**
FreeBSD 11.1

**Version of Telegram Desktop:**
1.2.17

**Used theme**:
default

**Comment by vit1-irk** [comment]
It will be good not only move this on the left, but have the ability to completely disable emoji panel / voice message button like in #4523

**Comment by Aokromes** [comment]
maybe even better 4 possible "locations" setting
left, right, top right, disable.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2294
