### ISSUE TITLE
Georgian font is not shown in Linux x64

### ISSUE THREAD

**Issue by akalongman** [telegramdesktop/tdesktop#487]
Georgian font is not shown in Linux x64 (Ubuntu)

![screenshot from 2015-02-17 13 41 18](https://cloud.githubusercontent.com/assets/423050/6226082/498c5fdc-b6ab-11e4-9add-d90dca6a8d4f.png)

**Comment by telegramdesktop** [comment]
Is it still not displayed in 0.7.16 version?

**Comment by akalongman** [comment]
No, in 0.7.13
In 0.7.16 this bug fixed
