### ISSUE TITLE
telegram needs tabs

### ISSUE THREAD

**Issue by 221V** [telegramdesktop/tdesktop#4873]
telegram needs tabs (filters) for make better organization and quickly find anybody from channels, group chats and private chats

### Organization example
1. tab with channels only
2. tab with group chats only
3. tab with private chats only

### Now we have telegram with
1. channels + groups + private chats in "one big soup" lol ))
2. we can find somebody in contacts
and can not find in "one big soup" when somebody not in contacts, but you need find, and not remember name, and so hard manually-by-eyes find in "one big soup"... fffuuu((
3. without tabs you can not quick find some usefull message, when you do not remember some words literally, and not remember group chat's name.... ffffuuuu(((

please, make something like this or better, for better organization
thanks)
with regards,

**Comment by kirsan31** [comment]
#1107

**Comment by Socialdarwinist** [comment]
I have outlined it with its reasons in #4212 already. The feature will lead Telegram into a new dimension of usefulness but its implementation is a huge amount of work.

**Comment by Socialdarwinist** [comment]
I see, OP thought more about #1107. Well that’s not what I’d mean with tabs, but right, formulated in the confused way of OP this is a duplicate.

**Comment by sxiii** [comment]
Why Implementation is so hard? I am using tabs in "Plus" telegram messanger for many years already! This is 100% worth function. Much more important than video calls

**Comment by kenorb** [comment]
Related: #1107, #1505, #2642, #2702, #4179, #5560

**Comment by shmykelsa** [comment]
That's a +1 for me. Unfortunately Plus Messanger Is not the solution for me since it does not support Google Assistant.

**Comment by sxiii** [comment]
There's also a Bettergram for desktop that support tabs (not in the way Plus does; but at least better then basic telegram (read as better than nothing!)).

**Comment by kenorb** [comment]
It has been implemented now. See: https://telegram.org/blog/folders

> Telegram was updated to version 6.0 (196005)
>
> Chat Folders and More
> 
> • Organize chats into Chat Folders if you have too many chats.
> 
> • Create custom folders with flexible settings, or use default recommendations.
> 
> • Pin an unlimited number of chats in each folder.
> 
> • Archive chats to hide them from "All chats". Muted chats will always stay in the Archive.

**Comment by AmirHosseinHmd** [comment]
It's really weird that after all these years, Telegram still doesn't have this basic and in some sense necessary feature. I and some other people I know still have to use the third-party versions of Telegram just because they have this important feature.
