### ISSUE TITLE
Inside-chat browsing through messages with keyboard

### ISSUE THREAD

**Issue by a-sitnik** [telegramdesktop/tdesktop#4875]
Need something to focus on messages from KB and defocus back to edit. 

**ctrl+arrows** can focus for reply to recent messages only. Need to forward and show images also. And need to focus not only from end of chat but from middle. 

vision usecase: need to find message in one chat and forward to another.

It starts as usual:
`**ctrl+f** -> "Hello kitty" -> choosing by **arrows** needed message -> **Enter**`

But now I need to focus on it. It may be **F6** as address bar shortcut in browser, or reorient **ctrl**, or something you consider as better. And **F6**(or **ctrl** or else) or **Esc**  to focus back to edit field

`**F6** to focus on middle of the screen message -> **arrows** to choose sought and/if "shift/ctrl+arrow" to choose several `

It also needs some cuts for context menu.

`**Enter** for context menu -> **arrows** or **R E C F D C** shortcuts for needed action, **F** in our case -> conventional choose of recipient`

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2109
