### ISSUE TITLE
Group pictures not loading, Telegram crashes

### ISSUE THREAD

**Issue by TheBlackSun** [telegramdesktop/tdesktop#4876]
![telegram group pictures issue](https://user-images.githubusercontent.com/783886/41716880-27ee0fe6-7558-11e8-868f-646e919fe235.png)

### Steps to reproduce
1. Open group.
2. Look at pictures of group.

### Expected behaviour
The pictures are shown.

### Actual behaviour
The pictures are not shown.
When opening a blank, it loads. When arrow-keying through the blank ones, they all load, but telegram crashes after one or two minutes of doing that.

### Configuration
**Operating system:**
Win7 Home Premium x64 (German)
**Version of Telegram Desktop:**
Telegram Desktop v1.3.7
**Used theme**:
Night mode

**Comment by stek29** [comment]
@TheBlackSun do you get a window with "sorry telegram crashed bla bla" on next launch?

**Comment by TheBlackSun** [comment]
Yep, I do.

**Comment by stek29** [comment]
@TheBlackSun please get latest alpha version (desktop.telegram.org/changelog), and if it still crashes, copy report tag from "sorry telegram crashed" window and post it here

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by TheBlackSun** [comment]
A few months ago, I changed the settings around to "don't load automatically" for media in groups, as a mobile Data thing, unrelated to this issue. Other than that, I don't remember changing much.

That being mentioned...
The previews all show, blurred of course because of my "new" settings, and flipping through about 300 pictures and videos in a group, as of right now, I don't seem to be able to reproduce the crash anymore.
