### ISSUE TITLE
[Feature] Encrypt MTPROTO links so the server IP could not be easily discovered and filtered

### ISSUE THREAD

**Issue by mkhahani** [telegramdesktop/tdesktop#4877]
There are some Telegram channels that are providing and offering mtproto servers but, due to the transparency of the mtproto links, the ip addresses get discovered and filtered soon by the governments since they have people observing those channels. It would be great to some how hide the ip address of the server, by encrypting the link for instance.

**Comment by john-preston** [comment]
@mkhahani I don't see any sense in this. If all the information to decode the link will be inside the link itself (so you could apply this link when you find it) same can do "the governments" — just process the link the same way as the app does and see the host:port pair.

**Comment by Aokromes** [comment]
netstat, or sniffers will find the real address of mtproxy, nothing can stop them if they install and use them.

**Comment by mkhahani** [comment]
I'm just looking for a way to make it harder for them to block servers, but of course this is not enough.
Thanks for your response any way.
