### ISSUE TITLE
UI: proxy passwords

### ISSUE THREAD

**Issue by DynamicSTOP** [telegramdesktop/tdesktop#4878]
### Steps to reproduce
1. add socks5 proxy that uses login+pass
2. go to edit proxy (click on new shield icon in the bottom left corner)
3. click on dots near the socks5 proxy, choose edit (Password is hidden in this window)
4. click share
5. paste a link somewhere

![default](https://user-images.githubusercontent.com/9434504/41763178-bcf59820-75fd-11e8-8906-05c282615276.png)
![default](https://user-images.githubusercontent.com/9434504/41763219-ecff63b6-75fd-11e8-8496-1227e9be6bc0.png)

### Expected behaviour
Either stop hiding password in proxy settings or disable sharing proxy with passwords.

### Actual behaviour
Password that should be kept as secret (as i got) is shown as plain text.

### Configuration
**Operating system:** win8

**Version of Telegram Desktop:** 1.3.7

**Used theme**: default?

**Comment by john-preston** [comment]
@DynamicSTOP The idea is not to show it in the UI so that someone from behind the shoulder won't see it and generally it is common to do so.

But if you want to share it, why not.

**Comment by DynamicSTOP** [comment]
@john-preston i just don't get the idea. If someone stands behind, that someone could clearly see pass in chat. It's not even base64 version or for example encrypted using my user id in any way.

Well... my problem is: I've setted up proxy server specifically to be able to continue using telegram and telegram bot api. Because bots are awesome! I've entered all that data on someone else device, thinking that in general average user shouldn't be able to retrive proxy pass from app and share auth data for my proxy server. And now i see that it's available as plain text and i wouldn't have any control of whom and when are using my proxy and for what purpose.

I kinda see it as a security problem that password is so easy to obtain. I might be wrong. I haven't even checked how easy to sniff that data from traffic or how is it getting stored. What i want is to give access to one specific user and now i see that that user can share it with anyone.  

If such thing is intended then that user will go look for other proxy to use and you can close this issue.

**Comment by john-preston** [comment]
@DynamicSTOP Socks5 passwords are passed as plain text over the net, this is socks5 protocol.

**Comment by phpony** [comment]
> I've entered all that data on someone else device, thinking that in general average user shouldn't be able to retrive proxy pass from app and share auth data for my proxy server. 

Please never rely on any "dots" or "masks" in text fields for security. If application knows password and uses it to connect to server - there's million ways to retrieve this data from it:

- reading settings storage of Telegram;
- using tools like http://www.scalabium.com/showpw.htm (there's millions of similar tools!);
- sniffing app's traffic where SOCKS5 auth data is passed in plain text;
- etc...

If you find it reasonably dangerous to share your SOCKS credentials with other people (and it is!), please consider to switch from SOCKS5 to MTProto. It's easy to install, it works faster and is safe. And no worries about passwords or any misuse - it works just for Telegram, and uses has only IP, port and hash for auth!

**Comment by DynamicSTOP** [comment]
Reading from "dots" and "masks" fields requires some knowledge. And i am pretty sure not everyone can do it. But the way how it's done right now, doesn't require anything and available for everyone. You just click on share and you got a password as part of the link in your clipboard.

I don't think that "password" field needs "dots" and "mask" because of this. It just gives false assumption that password is actually securely stored. I don't remember using apps that used masks and after that allowed me copy\paste data from masked field.

For now. I am just changing my proxy server pass and wouldn't provide u\p for anyone else.
I don't think that this discussion would lead anywhere, so i am closing this issue.

**Comment by DynamicSTOP** [comment]
@john-preston Chromium at least asks my system user\pass before showing me passwords while telegram just shares it (though i am pretty sure i still can get user\pass with just bare devtools in any browser). But asking system or user auth data on every attempt to share proxy wouldn't look very user friendly.

Maybe adding "eye" icon close to password that would temporarily remove mask from password would be something reasonable? At least it would show right away that password isn't secure.

**Comment by john-preston** [comment]
@DynamicSTOP So in this case Chromium will ask that other user his username and password (whose Chromium you used to save your password on for him to use, like you did with your SOCKS5 credentials), so he won't have a problem looking at them anyway.

I'm not sure this is a real problem tbh.
