### ISSUE TITLE
use plaintext config to facilitate programmatic editing / backup

### ISSUE THREAD

**Issue by tycho01** [telegramdesktop/tdesktop#4879]
### Steps to reproduce
1. look for legible settings file in `~/.local/share/TelegramDesktop/tdata/`
2. `nano ~/.local/share/TelegramDesktop/tdata/settings1`
3. find the file is binary

### Expected behaviour
I would hope for settings to be stored in a plain-text format, such that I could understand what is in there, edit settings manually, and store my settings online such as to facilitate syncing settings to new machines without manual intervention.

### Actual behaviour
Settings are stored in binary format.

### Configuration
**Operating system:** Linux (NixOS)
**Version of Telegram Desktop:** `1.2.6`

**Comment by john-preston** [comment]
@tycho01 User settings are not only stored in binary, but are encrypted using user local passcode together with all other user data =(

**Comment by Socialdarwinist** [comment]
To be fair there aren’t many behaviour settings in Telegram Desktop.
Some of the settings that are there though, like Ctr+Enter for sending and and emoji replacements could be tied to the Telegram account so this is synced to new desktop devices, for it is reasonable to assume that people’s Enter button and emoji behaviour stays consistent accross devices (this is an API issue however), while layout settings, saving settings, notification settings are probably wished to be different accross devices.
And with these words I have already mentioned all settings that currently exist in Telegram desktop.
For future usage however, a compromise could be: Telegram shall continue to encrypt the user settings, but shall be able to export them and import them (including via terminal parameters) in a readable format, like Firefox exports and imports bookmarks in HTML.

**Comment by Socialdarwinist** [comment]
No, it’s not just you, you probably see it as it. But as it is right now with everything being encrypted, it is rather indifferent. With the current amount of settings you do not really need _to facilitate syncing settings_, innit? I mean, how long does it take to set up new Telegram installations manually? Not longer than syncing.

**Comment by tycho01** [comment]
Admittedly, the amount of time saved wouldn't be particularly significant.

For context, I'm just playing around with NixOS, where the selling point is making your system reproducible using config files, in the first place for installed packages, though the next logical step is just storing dotfiles for individual application settings.
As part of that effort I looked into whether I could get my Telegram theme reproduced using a config file as well.
I'll admit this isn't particularly important. :)

**Comment by stek29** [comment]
Afaik more private stuff like api keys, used backends, cdn keys are also stored in that file
