### ISSUE TITLE
sorry, you have joined too many channels and supergroups, please leave some before joining this one

### ISSUE THREAD

**Issue by thuthao99** [telegramdesktop/tdesktop#4883]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Kyle2142** [comment]
Telegram has a limit of 500 supergroups per account. Not an issue with TDesktop

**Comment by cristaloleg** [comment]
Should we extend message info to make users life a bit easier?
