### ISSUE TITLE
Downloaded executables are flagged as trusted automatically

### ISSUE THREAD

**Issue by Kyle2142** [telegramdesktop/tdesktop#4884]
When I received a .bat file from someone recently, it was instantly run when I clicked on it, no prompt at all.
When I deleted and redownloaded the file, but "Show in folder" and opened it there, windows (smartscreen) correctly notified me, as well as the file properties showing the [security notice at the bottom](https://i.imgur.com/i5GpQCe.png)

Please note that the entirety of this report is not referring to a script that requires admin, but this might be covered too

### Steps to reproduce
1. Ask someone to send an executable (this works with at least .bat, unsure about other formats) to you
2. Left click on the file in telegram (do NOT use "Show in folder" or explorer to open it)

### Expected behaviour
File should not open, and show a prompt/warning about it being an executable instead.

### Actual behaviour
Executing the file from telegram desktop removes the "untrusted" flag that is set after downloading and runs it immediately with no prompt

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.3.7

**Comment by john-preston** [comment]
@stek29 The opposite 🙈 I guess I’ll have to remove that feature one day..

**Comment by Kyle2142** [comment]
@stek29 part of my issue is that tdesktop removes the flag if it's automatically opened from tdesktop.
I was about to continue repeating myself, but I already said all of this in the issue. #3198 does not cover everything I have brought up

**Comment by stek29** [comment]
#2924
