### ISSUE TITLE
No notification: No toast nor sound on Win 10

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#4885]
### Steps to reproduce
1.  Receive a msg

### Expected behaviour
notification sound

### Actual behaviour
no sound, no toast, only badge in tray icon

### Configuration
**Operating system:**
Win 10

**Version of Telegram Desktop:**
1.3.7

**Description**
My GF suddenly stop getting the notification sound.

I've checked:

"Notification & Action" settings, "Get notifications from apps and other senders" is on, Telegram app notification is on.

Quiet hours are off:
![image](https://user-images.githubusercontent.com/72570/41820279-233c2764-77c7-11e8-87a2-8c548293b640.png)

In TDesktop, all the notification checkboxes are on. We tried by unchecking "use windows notification" as well.

Is there any other area we can look?

Telegram does not appear in the sound mixer.
Telegram does not appear in "App Volume" panel setting (I think it's the same as the sound mixer)

**Comment by Deltageo** [comment]
I was experiencing the same issue until I came across this thread. https://github.com/telegramdesktop/tdesktop/issues/3193#issuecomment-291191306
Under HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings there's a registry entry called NOC_GLOBAL_SETTING_TOASTS_ENABLED. It was set to 0 for me so I set it to 1 and it fixed my notifications for telegram.

**Comment by Geobert** [comment]
She does not have this nor do I (and notifications are working on mine). I'll give it a shot though, thank you!

**Comment by Geobert** [comment]
@Deltageo: you were right, I was looking in LOCAL_MACHINE, not CURRENT_USER v_v
Thank you very much!
