### ISSUE TITLE
multiple telegram accounts for  desktop application

### ISSUE THREAD

**Issue by ialireza** [telegramdesktop/tdesktop#4889]
**multiple telegram accounts for  desktop application**

**Comment by MasterGroosha** [comment]
Did you know you can [download](https://desktop.telegram.org) as many portable copies of TDesktop as you wish and login with different accounts?

**Comment by stek29** [comment]
#4261

**Comment by sreenathaa** [comment]
I am looking for a feature in Desktop app as it's in android app.

When a Telegram app can support multiple accounts?

**Comment by mduran63** [comment]
Until now, Unigram is the only option.

**Comment by Kwaskoff** [comment]
How you can close issue if this function is not release?

**Comment by MasterGroosha** [comment]
@Kwaskoff because it is duplicate of #4261, which is open.
