### ISSUE TITLE
Missing emoticons

### ISSUE THREAD

**Issue by BarabasGitHub** [telegramdesktop/tdesktop#4892]
There are emoticons missing in the desktop app (at least compared to android)
There's at least three missing. The one with the crazy eyes, eyebrows and the monocle. Oh and star eyes as well I think. This has been so for a long time and maybe there's a reason for it, but it's annoying because when people do send one of those it's not visible to me on desktop so I've no idea what they're trying to express.

Android (v4.8.9):
![image](https://user-images.githubusercontent.com/12561434/41861774-79ddd3ac-78a2-11e8-80d3-51ee7a5ec906.png)

Desktop (1.3.8):
![image](https://user-images.githubusercontent.com/12561434/41861699-44edef10-78a2-11e8-81fa-9e789f6fd414.png)

**Comment by Aokromes** [comment]
#3966
