### ISSUE TITLE
[Feature Request] disable incoming calls locally

### ISSUE THREAD

**Issue by qgates** [telegramdesktop/tdesktop#4893]
Thanks to #488 using tdesktop for voice calls is often impractical on laptops or desktops with inbuilt loudspeaker and microphone due to the lack of echo cancellation. As a result, I prefer to answer incoming calls on my mobile, but I want to continue using tdesktop for messaging.

The problem is, if someone calls in it disturbes what I'm doing on the laptop which is quite annoying. It would be nice to be able to disable incoming calls on tdesktop locally without affecting other devices connected to a telegram account. Using 'Phone calls privacy' in settings blocks calls for all devices; what I'd like is to disable incoming calls on the local copy of tdesktop only, without disabling them on other devices.

**Comment by Aokromes** [comment]
#3594
