### ISSUE TITLE
cannot install telegram desktop because of blocking %localappdata%/temp

### ISSUE THREAD

**Issue by NurPech** [telegramdesktop/tdesktop#4894]
### Steps to reproduce
1. Block execution of files in %localappdata%/temp
2. try to install telegram desktop
3. 

### Expected behaviour
Is it possible to change the directory where the setup files will be extracted?

### Actual behaviour
Telegram can't be installed because the user can't execute files %localappdata%/temp due to security reasons.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
I tried multiple versions

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
@NurPech use portable version
