### ISSUE TITLE
Errors during start up, taking so long for the desktop client to start

### ISSUE THREAD

**Issue by Daniel-M** [telegramdesktop/tdesktop#4896]
### Steps to reproduce
1. Try to open the app

### Expected behaviour
Desktop client opens and works properly

### Actual behaviour
The Desktop client doesn't load at all. After several tries opening the app, and waiting for about 5 minutes, the client starts showing some log errors which I append at the end of this message. After this the client works as usual (But still with the problems I reported at #4219).

### Configuration
**Operating system:**
Debian Testing (Buster) Linux 4.16.0-2-amd64 #1 SMP Debian 4.16.12-1 (2018-05-27) x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.3.8-alpha

**Used theme**:
Default theme (the one with the Daisies in the background)

<details><summary><b>Logs</b>:</summary>
[2018.06.25 15:48:02] Executable path before check: /home/damejia/opt/Telegram/Telegram
[2018.06.25 15:48:07] FATAL: Could not move logging to '/home/damejia/.local/share/TelegramDesktop/log.txt'!
[2018.06.25 15:53:05] Font Error: could not resolve 'Open Sans Semibold' font, got 'Open Sans' after feeding '%3'.
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4240
