### ISSUE TITLE
[build error] functors.h line 24#Expressions must contain constant values#

### ISSUE THREAD

**Issue by 2008820** [telegramdesktop/tdesktop#4897]
### Steps to reproduce
1.  `constexpr auto add = [](auto value) {
	return [value](auto other) {
		return value + other;
	};
};
`
2.  there is error : Expressions must contain constant values

error image https://user-images.githubusercontent.com/14990750/41886849-b6dbf926-7930-11e8-8b39-ec10148367f9.png

### Expected behaviour
build faild

### Actual behaviour
build faild

### Configuration
**Operating system:windows 10 Professional Edition

**Version of Telegram Desktop:dev

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)
![1](https://user-images.githubusercontent.com/14990750/41886460-024d922c-792f-11e8-942e-fd37441ab337.jpg)
![2](https://user-images.githubusercontent.com/14990750/41886849-b6dbf926-7930-11e8-8b39-ec10148367f9.png)

</details>

**Comment by 2008820** [comment]
error image https://user-images.githubusercontent.com/14990750/41886849-b6dbf926-7930-11e8-8b39-ec10148367f9.png

**Comment by mugavri** [comment]
I have the same error, what to do?

**Comment by Jongkeun** [comment]
@2008820 
I really wanna know how you solved this problem.
Let me know please.

**Comment by 17dengfeng** [comment]
zen me jie jue de ne ?
