### ISSUE TITLE
ni binary downloads for the 1.3.8 release

### ISSUE THREAD

**Issue by ohaessler** [telegramdesktop/tdesktop#4898]
I am looking for the binary downloads for the 1.3.8 release, however, can only find the one for the 1.3.7 release.

Is there any chance to add the binary downloads?

Thanks
Oliver

**Comment by john-preston** [comment]
I've uploaded them now on GitHub as well.

But really all binaries are located at https://desktop.telegram.org, the ones at GitHub releases page are just to provide one more place for download.

**Comment by ohaessler** [comment]
Thanks John. Sorry did not even thought about looking at https://desktop.telegram.org/ 

The GitHub page is just more convenient in scripts to download the archives.
