### ISSUE TITLE
automatic photo download not working?

### ISSUE THREAD

**Issue by chaosdrop** [telegramdesktop/tdesktop#4899]
### Steps to reproduce
1.  Checked the boxes under automatic photo download 
2.  Set a custom path under "Download path"
3.  Had people send me photos and viewed them.

### Expected behaviour
The photos should be automatically downloaded to the download path.

### Actual behaviour
I can't see as though anything happens at all.

### Configuration
**Operating system:**
Windows 10 64-bit
**Version of Telegram Desktop:**
1.3.8
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@chaosdrop Photos are downloaded to the encrypted cache folder, sorry

**Comment by chaosdrop** [comment]
In that case I guess I should make a feature request to be able to store photos un-encrypted on the desktop client. Would it be better to just edit this issue or make another one?

**Comment by stek29** [comment]
@chaosdrop why? if some photo has to be saved, you can use "save as"

**Comment by chaosdrop** [comment]
@stek29 Because you can't save as more than a single message at a time and I have contacts who will send me a couple dozen or more photos at one time. If I could save as multiple messages at once that would also work.

**Comment by ktiniatros** [comment]
> @chaosdrop why? if some photo has to be saved, you can use "save as"

One of the most important usages of Telegram is to let my friends send me all their photos. Thousands of photos. We need automatic download/storage for this. "Save as" is not sufficient.

**Comment by chaosdrop** [comment]
Bumping so the issue doesn't get closed since it's still a issue.

**Comment by ilya-fedin** [comment]
> Bumping so the issue doesn't get closed since it's still a issue.

You have the export feature

**Comment by chaosdrop** [comment]
Exporting can't be done automatically. it is an incredibly manual and time consuming task.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/24900 more than only photos.
