### ISSUE TITLE
Strange forward message

### ISSUE THREAD

**Issue by sigod** [telegramdesktop/tdesktop#49]
Some messages with just a single link look strange when forwarded.

E.g.:
![screenshot 2014-07-13 01 54 05](https://cloud.githubusercontent.com/assets/1175750/3562983/9ff1c4ac-0a17-11e4-8466-bcc204d8313b.png)

Link in message is: `http://some_site.com/long_url?sssssssssssssssss=ТестТестТест`.

Also this applies to message text. `Copy Message Text` on first message:
```
http://some_site.com/long_url?sssssssssssssssss=ТестТест… ( http://some_site.com/long_url?sssssssssssssssss=%D0%A2%D0%B5%D1%81%D1%82%D0%A2%D0%B5%D1%81%D1%82%D0%A2%D0%B5%D1%81%D1%82 )
```

After I restart program messages look normal, but the result of `Copy Message Text` is the same.

**Comment by telegramdesktop** [comment]
Should be fixed in the last versions.
