### ISSUE TITLE
Segmentation fault (0.7.15)

### ISSUE THREAD

**Issue by l0okme** [telegramdesktop/tdesktop#490]
The program drops a segmentation fault on startup, leaving an empty logfile in its folder. I'm using GNOME 3.14 without libappindicator. 0.7.13 works for me though.
_Update:_ On Archlinux 64bit. Forgot to mention that.

**Comment by IzNoGud78** [comment]
It shows the same issue with the 0.7.16 64 bit version on Fedora 21 KDE, while on PCLinuxOS 2014.12 MATE, with the 0.7.16 32 bit version, I haven't encountered any problems.

**Comment by amirmasud** [comment]
same problem with 0.7.16 64bit deepin 2014.2;  also with 0.7.15 dev

**Comment by IzNoGud78** [comment]
the issue persists even on 0.7.17 64 bit version

**Comment by IzNoGud78** [comment]
I had the opportunity to test the release 0.7.19 dev 64 bit on Fedora 21 KDE 64 bit and the issue doesn't longer persist! :thumbsup:

**Comment by l0okme** [comment]
`$ telegram       
libs init..
loading appindicator3 with version 1..
could not load appindicator3 without version.
loading appindicator with version 1..
could not load appindicator without version.
no appindicator :(
/usr/bin/telegram: line 2: 12024 Segmentation fault      (core dumped) ./Telegram`

This is for version 0.7.20 on Arch Linux 64. Error is still there; The app should work without `libappindicator` installed because is isn't necessary and produces an unbelievable overhead (mono needs to be installed, etc).

Now this is the console output for version 0.7.13 on the same OS:
`$ ./Telegram 
libs init..
loading appindicator3 with version 1..
could not load appindicator3 without version.
loading appindicator with version 1..
could not load appindicator without version.
no appindicator :(
loading unity with version 9..
could not load unity without version.
FT_New_Face failed with index 0 : 1
FT_New_Face failed with index 0 : 1
FT_New_Face failed with index 0 : 1
FT_New_Face failed with index 0 : 1
FT_New_Face failed with index 0 : 1`

This one works pretty good. Do you have any suggestion how I can track the error down?

**Comment by amirmasud** [comment]
persists until now (0.7.23 64bit  on deepin 2014.2)

**Comment by btywoniuk** [comment]
Still there (0.8 64bit )

**Comment by pyriand3r** [comment]
0.8.24 on Arch 64bit
telegram app is working, but without appindicator. I don't have a seg fault.

my log

    libs init..
    loading appindicator3 with version 1..
    could not load appindicator3 without version.
    loading appindicator with version 1..
    could not load appindicator without version.
    no appindicator :(
    Using blocking call!
    Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
    Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
    Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
    Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
    Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
    Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

**Comment by Jaczel** [comment]
Same issue. Telegram Desktop 0.8.38 on Arch 64bit with Gnome Shell 3.

<pre><code>
libs init..
loading appindicator3 with version 1..
could not load appindicator3 without version.
loading appindicator with version 1..
could not load appindicator without version.
no appindicator :(
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
</code></pre>

**Comment by telegramdesktop** [comment]
Check out 0.8.41.dev version.

**Comment by telegramdesktop** [comment]
It uses Qt 5.5 and system tray icon is supported better there.

**Comment by pyriand3r** [comment]
works for me
