### ISSUE TITLE
issue notification of changes to the new version at the start of the telegram

### ISSUE THREAD

**Issue by raingart** [telegramdesktop/tdesktop#4900]
I have a problem.
The bottom line is that after the update there is a notification of changes to the new version when the telegram starts. But after a second it disappears and it is no more.

I do not remember exactly, but I kind of threw the account that notified me (possibly) to the black list. But he is not on the blacklist.

OS                                                                                                                                     
Linux pc 4.16.12-1-ARCH #1 SMP PREEMPT Fri May 25 23:30:31 UTC 2018 x86_64 GNU/Linux
telegram ver.
local/telegram-desktop-bin 1.3.7-2

I recorded the video. Pay attention to the upper right corner. And the fact that after the notice there is no more indicator of unread messages.
https://drive.google.com/open?id=13obqYpxfhbSTifR8v3Nk-h9t7XvNC8h9

**Comment by stek29** [comment]
@raingart Telegram Desktop is not visible at all in that screen recording

**Comment by raingart** [comment]
@stek29 and he should not. Here the main notice. There, on the video, the Dunst popup is nearing the end. But there is no new message in the Telegram itself.

**Comment by raingart** [comment]
@stek29 
![screenshot from 2018-06-27 11-31-02](https://user-images.githubusercontent.com/13064767/41962406-98d46832-79fd-11e8-966b-1385f9bfae28.png)
