### ISSUE TITLE
Dynamic width of Hide muted chats button in Work mode

### ISSUE THREAD

**Issue by rizaumami** [telegramdesktop/tdesktop#4901]
### Steps to reproduce
1. Go to **Settings**
2. Type `workmode`
3. Confirm to restart Telegram Desktop into Work mode
    
    ![photo_2018-06-26_19-41-36](https://user-images.githubusercontent.com/11420518/41912247-55e0011e-7979-11e8-99c3-516b27a164c2.jpg)

### Expected behaviour
**Hide muted chats** button width should be dynamic so it wouldn't be cropped when chats panel minimized, hence easier to spot/see. 

### Actual behaviour
On Work mode, there is a button below the hamburger button titled **Hide muted chats**. This text/button is cropped when the chats panel is minimized. 

### Configuration
**Operating system:** Debian Sid 64 bit

**Version of Telegram Desktop:** 1.3.8 alpha

**Used theme**: Default

**Comment by john-preston** [comment]
@rizaumami Well, this is not an officially supported feature =)

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by rizaumami** [comment]
The text is displayed properly on v1.9.8.
