### ISSUE TITLE
The data export window has white edges (In night mode)

### ISSUE THREAD

**Issue by 4nt0n10M4** [telegramdesktop/tdesktop#4902]
### Steps to reproduce
1. Go to Settings and start the data export.
2. While downloading proccess is started change to Night Mode
3. Click on "Exporting your data"

### Expected behaviour
The edges have to been black

### Actual behaviour
The edges are white in Night mode

### Configuration
**Operating system:**
Windows 7 Home Premium 64bits
**Version of Telegram Desktop:**
1.3.8 alpha
**Used theme**:
Night Mode (Default)
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Screenshot:**
https://t.me/antonioma_tk/1017

**Comment by john-preston** [comment]
Thanks!
