### ISSUE TITLE
Workmode can't be enabled during data export

### ISSUE THREAD

**Issue by 4nt0n10M4** [telegramdesktop/tdesktop#4905]
### Steps to reproduce
1. Go to Settings and start the data export.
2. In settings type `workmode`
3. Click on *OK*

### Expected behaviour
The work mode should be activated

### Actual behaviour
The exporting windows ask if you want to Cancel the export

### Configuration
**Operating system:**
Windows 7 Home Premium 64bits
**Version of Telegram Desktop:**
1.3.8 alpha
**Used theme**:
Night Mode (default)
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**GIF:**
https://t.me/antonioma_tk/1019

**Comment by john-preston** [comment]
@4nt0n10M4 Workmode and some other settings change require app restart, so they can’t be changed during the export. This is intended, sorry.

**Comment by 4nt0n10M4** [comment]
Oh, okay.
No problem, but you can make the "Enable workmode?" windows close after pressing a button?

https://t.me/antonioma_tk/1019
