### ISSUE TITLE
[Feature Request] Increase voice/video messages playback speed

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#4907]
This feature already exists in Android beta apps. It would be nice to have it in desktop version.

### Steps to reproduce
1. Play voice message or video message

### Expected behaviour
2. Playback bar appears with `2X` button.
![image](https://user-images.githubusercontent.com/1321838/41991973-e4944b64-7a4f-11e8-8ca3-03e530cba62c.png)

3. By toggling `2X` button voice/video playback speed should increase twice.

### Actual behaviour
2. Playback bar appears without `2X` button.
![image](https://user-images.githubusercontent.com/1321838/41991964-df1cebfa-7a4f-11e8-935a-3df939e7e5d6.png)

**Comment by gwpl** [comment]
https://telegram.org/blog/unread-replace-2x
"2X Voice Messages"
on Android it works for both: Audio and Periscopes.

I would love to have speed up options on desktop as well ! 
I am huge fan of speed listening.
