### ISSUE TITLE
[Feature Request] Lockable Voice Message Button

### ISSUE THREAD

**Issue by PatrickDeTomasi** [telegramdesktop/tdesktop#4909]
Hi Telegram, great stuff, love your software.
Would love to see the exact same feature and feel that you have on your mobile app (android atleast) which gives you the option to "lock" your voice message button when recording, ported to the desktop app. 

I want to be able to lock the voice recording and sit back in my computer chair and chat away.

Thanks guys

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3208
