### ISSUE TITLE
Doesn't start on Windows 10

### ISSUE THREAD

**Issue by lcrivell** [telegramdesktop/tdesktop#4911]
### Steps to reproduce
1. Start Telegram
2. 
3. 

### Actual behaviour
Nothing happens. Telegram.exe process is appearing in Task manager and disappears after 1 second.

### Configuration
**Operating system: Windows 10 Version 1709 OS Build 16299.492 **

**Version of Telegram Desktop: 1.3.8.0 **

**Used theme**:

<details><summary><b>Logs</b>:</summary>
The log file shows this:

> [2018.06.28 07:13:27] Launched version: 1003008, alpha: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
> [2018.06.28 07:13:27] Executable dir: C:/Users/laurent/AppData/Roaming/Telegram/, name: Telegram.exe
> [2018.06.28 07:13:27] Initial working dir: C:/Users/laurent/
> [2018.06.28 07:13:27] Working dir: C:/Users/laurent/AppData/Roaming/Telegram/
> [2018.06.28 07:13:27] Command line: C:\Users\laurent\AppData\Roaming\Telegram\Telegram.exe -update
> [2018.06.28 07:13:27] Executable path before check: C:/Users/laurent/AppData/Roaming/Telegram/Telegram.exe
> [2018.06.28 07:13:27] Logs started

</details>

**Comment by karanssh** [comment]
It seems to work just fine on the few Windows 10 systems I have. Have you tried re-installing telegram? Have you made sure there is no AV process affecting telegram?

**Comment by Aokromes** [comment]
#4756 ?

**Comment by lcrivell** [comment]
> #4756 ?

I should see the log to confirm, but I don’t have any process running after launch

**Comment by Aokromes** [comment]
@lcrivell try https://telegram.org/dl/desktop/win_portable

**Comment by Aokromes** [comment]
try to start from cmd with -debug and check log :)

**Comment by lcrivell** [comment]
-debug gives exactly the same log than indicated initially

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4787 ?
