### ISSUE TITLE
Linux | "connecting" circle appears for a split second.

### ISSUE THREAD

**Issue by illuminatio** [telegramdesktop/tdesktop#4912]
Version: 1.3.8
OS: Debian Stretch
DM: Cinnamon

When I keep Telegram client on screen, I regularly see _something_ bouncing from the bottom of the menu once, and then hiding. It very short, it appears even if I have no unread messages, I have no idea what it is, and it's annoying as hell. If it's a feature, I have no idea how to turn it off.

UPDATE:
Looks like it's a connection status. But when it appears like this it's useless and distracting, it's too fast to serve any useful purpose.

**Comment by illuminatio** [comment]
@stek29 thanks, I think that's it. But I think it shouldn't appear for a split second, there's something wrong with the timing.

**Comment by mrjnox** [comment]
I've experienced the same issue for months now with an otherwise-stable internet connection:

Arch Linux
`telegram-desktop` via official Arch repo
NetworkManager
1GigE wired

**Comment by Aokromes** [comment]
> @stek29 thanks, I think that's it. But I think it shouldn't appear for a split second, there's something wrong with the timing.

well, it's show only if it's trying to connect, if it connects fast it hides fast, if it connects slow of fails to connect it's show for longer time.
