### ISSUE TITLE
Telegram permanently increases Windows timer resolution (causing reduced battery life)

### ISSUE THREAD

**Issue by madriani** [telegramdesktop/tdesktop#4914]
### Steps to reproduce
1. Open Telegram and let it run in background
2. Run, from an elevated command prompt, "powercfg /energy"
3. Open the generated report. Scroll to the "warnings" section and notice that Telegram has increased the timer resolution from 15.6 ms to 1 ms

### Expected behaviour
Telegram should not permanently increase the Windows timer resolution, since this can lead to greatly reduced battery life (up to 25%, according to [this](https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/) and [this](https://blogs.msdn.microsoft.com/e7/2009/01/06/windows-7-energy-efficiency/))

### Actual behaviour
Telegram permanently increases the Windows timer resolution, even when in background

### Configuration
**Operating system:** Windows 10 (version 1803, build 17134.112)

**Version of Telegram Desktop:** 1.3.9

**Used theme**: Built-in night theme

**Comment by DoulosTrieste** [comment]
You can use this to monitor in realtime rather than keep generating powercfg reports:
https://vvvv.org/contribution/windows-system-timer-tool

**Comment by RussianNeuroMancer** [comment]
Same issue with 1.4 in Linux: #4854

**Comment by kocane** [comment]
By using software like Throttlestop, you can monitor the c-states of the processor when using Telegram Desktop.  When Telegram is not running, the stats (in my case) look like this:
![image](https://user-images.githubusercontent.com/7694813/55674531-44054900-58b6-11e9-9c91-daee9ab4d1c3.png)
When launching Telegram and unlocking it, it idles ca. like this:
![image](https://user-images.githubusercontent.com/7694813/55674506-00124400-58b6-11e9-9953-59c13a20e944.png)
So the amount of percentage the CPU idles in C8 is much lower and it hits battery life hard.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4854 generic bug.
