### ISSUE TITLE
New feature is not translated

### ISSUE THREAD

**Issue by rafiuske** [telegramdesktop/tdesktop#4916]
### Steps to reproduce
1. I'm using Telegram desktop in Portuguese (pt-BR)
2. Mark chats in the chat list as Read or Unread.
3. This new label doesn't translated.

Attachment
![desktop_suspend_menu](https://user-images.githubusercontent.com/7706923/42091844-42c70144-7b7d-11e8-8242-c7c49f2dd311.png)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
https://t.me/TelegramDesktopTalk/28110
