### ISSUE TITLE
Switch to Night Mode based on system-wide Dark Mode

### ISSUE THREAD

**Issue by hutattedonmyarm** [telegramdesktop/tdesktop#4918]
macOS 10.14 has added a system-wide dark mode. I'd like to request the feature to set two different themes, one for light, and one for dark mode. Telegram Desktop should automatically apply the correct theme based on the system setting and switch when the system setting changes

**Comment by stek29** [comment]
See electron/electron#13387 for nice overview of related APIs

**Comment by stek29** [comment]
Also, on Windows `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme` might be used, I guess.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/356e3c690730105e9809e6952f87bf39eb337960

**Comment by ilya-fedin** [comment]
There are `QWindowsNativeInterface::isDarkMode()`
Native interface can be observed via https://doc.qt.io/qt-5/qguiapplication.html#platformNativeInterface
But it is added just in Qt 5.15

**Comment by ilya-fedin** [comment]
https://github.com/telegramdesktop/tdesktop/commit/47a237c9243e9597d44cb581802435a9aacdcb1e
https://github.com/telegramdesktop/tdesktop/commit/25d69434ec150d03fcc7989653f00e92123a4e7c
