### ISSUE TITLE
Porting TG-Desktop to another build system

### ISSUE THREAD

**Issue by Cogitri** [telegramdesktop/tdesktop#4919]
Hey there,

since it is tremendously difficult for distros to package telegram-desktop (mainly because of its (for us) _very_ annoying build system, which requires lots of patching for most distros) I'd suggest using another build system for building telegram. I'd personally suggest meson, since it'd still be easily possible to use your patched versions of Qt with that via [subprojects](https://mesonbuild.com/Dependencies.html#building-dependencies-as-subprojects). If you'd consider that useful I'd love to help, I already ported a few projects over to meson.

**Comment by berkus** [comment]
Why use meson if there are perfectly working [CMake-built versions](https://github.com/procxx/kepka/) with no extra patches?

**Comment by Cogitri** [comment]
Oh, near, didn't know about that

**Comment by berkus** [comment]
That would definitely be nice!

**Comment by Aokromes** [comment]
done after 1.9.x
