### ISSUE TITLE
[Feature Request] Show notifications mode on tray icon.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [telegramdesktop/tdesktop#4921]
When I use Not to show notifications, its is difficult to turn it back on, beacase i just dont remember that i disable it, this information did not showes anywere. Only way to check it is to right click on icon and anilise menu itemes.

I think that this is good idea when i set not to show notifications to make tray icon with some special symbol to show that notifications are off. It can be block symbol for example. ⛔

**Comment by batmont** [comment]
still actual, or it can be implemented by temporary disabling like in chats (1-4-18 hours or custom), but in quickest way (through tray icon menu) and for all types of conversations at once

**Comment by DmitrijOkeanij** [comment]
Up
