### ISSUE TITLE
emoji adds extra character

### ISSUE THREAD

**Issue by FTABoy** [telegramdesktop/tdesktop#4923]
this emoji 🙋‍♀ adds an extra character ‍♀ following after 🙋‍♀ when showing it on desktop, no problem on android:
please take a look at screen shots bellow:
![untitled](https://user-images.githubusercontent.com/25687276/42127761-c0709f74-7cb3-11e8-8244-719925ab3b09.png)
![screenshot_20180630-221809](https://user-images.githubusercontent.com/25687276/42127804-5cbfb3c4-7cb4-11e8-98ac-5cb857039b37.png)

also maybe there are other emojis which make this extra odd character appears. thanks

**Comment by stek29** [comment]
See #4821
