### ISSUE TITLE
[Feature Request] Add screenshot to clipboard hot key support

### ISSUE THREAD

**Issue by pexcn** [telegramdesktop/tdesktop#4924]
Hello contributors:

I have an idea to enhance tdesktop.

e.g.: When I click keyboard `CTRL + ALT + A`, then I can screenshot some area on screen.
and click `CTRL + V` can paste send to someone. (sorry for my bad English)

**Comment by rizaumami** [comment]
This already a thing in Linux, at least on Gnome (Xorg?); `SHIFT+CTRL+PRTSC` then draw the area to be screenshoted and save it into the clipboard. Use `CTRL+V` to paste the clipboard.

**Comment by pexcn** [comment]
@rizaumami but windows seems have not this hotkey...

**Comment by auchri** [comment]
@pexcn try the <kbd>print</kbd> key.

**Comment by pexcn** [comment]
@auchri It just full screenshot, cannot cut range...

**Comment by auchri** [comment]
Then use the Snipping Tool or some other program like greenshot.

**Comment by pexcn** [comment]
Okay, thanks. Now I am already using 3rd-party program.
I just think this feature built in tdesktop better. :)
