### ISSUE TITLE
Selection of download path for export data kills desktop manager

### ISSUE THREAD

**Issue by JoshuaDietz** [telegramdesktop/tdesktop#4925]
### Steps to reproduce
1. Open menu
2. Go to Settings
3. Click on "Export Telegram data"
4. Click on the Download Path to change it

### Expected behaviour
I can select the download path

### Actual behaviour
Window to select download path opens but in the same second, my desktop manager (cinnamon) crashes every time. I am asked (by cinnamon) if I would like to restart it. I do that, then I can choose the download path, after confirming it Telegram freezes so I need to kill and restart it. After that, the new download path is set.

### Configuration
Debian 9 with Cinnamon as Desktop manager

**Version of Telegram Desktop:**
1.3.9

**Used theme**:
Default (night mode)

**Comment by john-preston** [comment]
@JoshuaDietz Wow. I think Cinnamon should not crash, perhaps it should be reported to cinnamon.

**Comment by JoshuaDietz** [comment]
@john-preston Yea you're right, but cinnamon did not crash for years and I'm using many programs, so I think Telegram just needs to change a little thing to avoid the crash. But yes, Cinnamon shouldn't crash.

**Comment by john-preston** [comment]
I tried Linux Mint 19 Cinnamon and it works fine. I'm afraid I can't test all the combinations of distributions with desktop managers :( But this definitely should not happen.

**Comment by john-preston** [comment]
Tried Debian 9 with Cinnamon. Works fine as well.

**Comment by john-preston** [comment]
(I tried version 1.3.16 alpha)
