### ISSUE TITLE
Telegram Desktop occasionally logs out on computer power outage

### ISSUE THREAD

**Issue by halaei** [telegramdesktop/tdesktop#4927]
It happened once to me, a couple of times to people around me that after power outage, telegram asks for mobile number & OTP & password.

**Comment by MasterGroosha** [comment]
Could you please follow issue template next time and provide information about your Telegram version and OS used? 

btw, I had this issue as well on older Telegram versions (different ones) on Windows 10.

**Comment by halaei** [comment]
Oops. My OS is Ubuntu 16.04 and I was running the latest telegram version.
