### ISSUE TITLE
Feature request: Monochrome icon

### ISSUE THREAD

**Issue by RobinJ1995** [telegramdesktop/tdesktop#493]
![screenshot_2015-02-18_09-12-53](https://cloud.githubusercontent.com/assets/3089559/6244204/47cbf054-b750-11e4-9416-cd7ad97c0a43.png)
Good to know that Telegram Desktop has a tray icon. I never saw one before this update :+1: 

I'm just nitpicking, but this could look better than it does if Telegram had a monochrome icon;
![screenshot_2015-02-18_09-14-10](https://cloud.githubusercontent.com/assets/3089559/6244212/642486a8-b750-11e4-8013-b39422067265.png)

For example, the ownCloud client has this option;
![screenshot_2015-02-18_09-28-12](https://cloud.githubusercontent.com/assets/3089559/6244217/797a1cca-b750-11e4-9d1c-5d45fbb71bd1.png)

Just a feature request, though.

**Comment by Aokromes** [comment]
#469

**Comment by NikoM87** [comment]
#419

**Comment by bil-elmoussaoui** [comment]
@auchri duplicate
