### ISSUE TITLE
Crash on voice call

### ISSUE THREAD

**Issue by f0x52** [telegramdesktop/tdesktop#4931]
### Steps to reproduce
1. Start call or get called
2. no sound, crash after a few seconds of calling

### Expected behaviour
Tell us what should happen
working calling

### Actual behaviour
Crash:
`Fatal error in /home/preston/Telegram/tdesktop/Telegram/ThirdParty/libtgvoip/webrtc_dsp/webrtc/modules/audio_processing/aec/aec_core.cc, line 205`

### Configuration
**Operating system:**
Debian Sid

**Version of Telegram Desktop:**
1.3.9 Alpha

**Used theme**:
custom

<details><summary><b>Logs</b>:</summary>
```
#
# Fatal error in /home/preston/Telegram/tdesktop/Telegram/ThirdParty/libtgvoip/webrtc_dsp/webrtc/modules/audio_processing/aec/aec_core.cc, line 205
# Check failed: 0 < AvaliableSpace() (0 vs. 0)
#
#
zsh: abort      telegram
```
</details>

**Comment by stek29** [comment]
cc @grishka

**Comment by grishka** [comment]
Might be fixed in libtgvoip 2.1.1

**Comment by Aokromes** [comment]
@f0x52 Try on 1.3.14 :)

**Comment by Aokromes** [comment]
over 1 year without answer, closing.
