### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by JohnMiz** [telegramdesktop/tdesktop#4932]
Hey all,

I have some knowledge in C++ for 4-5 years, I wrote games and some tools with QT.

How can I start contribute here?
I always wanted to start doing that on Github so any help will be welcomed.
Thanks!

**Comment by stek29** [comment]
See https://github.com/telegramdesktop/tdesktop/blob/dev/.github/CONTRIBUTING.md.

I'm not sure this is a good project for first open-source experience tbh.

**Comment by MasterGroosha** [comment]
Please, read TDesktop's [Contributing Guidelines](https://github.com/telegramdesktop/tdesktop/blob/dev/.github/CONTRIBUTING.md) first.
