### ISSUE TITLE
Tg crash in the end of voicecall

### ISSUE THREAD

**Issue by dm4g3** [telegramdesktop/tdesktop#4934]
### Steps to reproduce
1. Start telegram binary ./Telegram
2. Call anyone with voicecall
3. End call with clicking "END CALL"

### Expected behaviour
Normal end of call

### Actual behaviour
Tg crash instantly

### Configuration
**Operating system:**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
(kubuntu)

**Version of Telegram Desktop:**
Telegram got update after first crash, so latest for this moment - 1.3.9

**Used theme**:
Default, night mode

<details><summary><b>Logs</b>:</summary>
I/tgvoip: jitter: resyncing, next timestamp = 49920 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 50040 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 50220 (step=60, minDelay=3,000000)
D/tgvoip: Current RTT via x.x.x.x: 0,408, average: 1,599
D/tgvoip: Current RTT via y.y.y.y: 0,428, average: 1,532
I/tgvoip: jitter: resyncing, next timestamp = 50460 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 50520 (step=60, minDelay=3,000000)
V/tgvoip: opus_encoder: setting bitrate to 9000
I/tgvoip: jitter: resyncing, next timestamp = 50580 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 50820 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 50940 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 51060 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 51120 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 51240 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 51300 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 51420 (step=60, minDelay=3,000000)
V/tgvoip: opus_encoder: setting bitrate to 10000
I/tgvoip: jitter: resyncing, next timestamp = 51480 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 51780 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 51960 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 52080 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 52260 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 52500 (step=60, minDelay=3,000000)
V/tgvoip: opus_encoder: setting bitrate to 11000
I/tgvoip: jitter: resyncing, next timestamp = 52560 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 52980 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 53160 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 53580 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 53700 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 53820 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 53880 (step=60, minDelay=3,000000)
V/tgvoip: opus_encoder: setting bitrate to 10000
I/tgvoip: jitter: resyncing, next timestamp = 54000 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 54120 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 54180 (step=60, minDelay=3,000000)
I/tgvoip: jitter: resyncing, next timestamp = 54360 (step=60, minDelay=3,000000)
D/tgvoip: Entered VoIPController::Stop
D/tgvoip: before shutdown socket
E/tgvoip: tried to send null packet
I/tgvoip: === send thread exiting ===
V/tgvoip: Select canceled
I/tgvoip: === recv thread exiting ===
D/tgvoip: before join sendThread
D/tgvoip: before join recvThread
D/tgvoip: before join tickThread
I/tgvoip: === tick thread exiting ===
D/tgvoip: Before stop audio I/O
D/tgvoip: Left VoIPController::Stop
D/tgvoip: Entered VoIPController::~VoIPController
D/tgvoip: before close socket
D/tgvoip: before stop decoder
I/tgvoip: ==== decoder exiting ====
D/tgvoip: before delete audio input
Assertion 'q->length == 0' failed at pulsecore/queue.c:63, function pa_queue_free(). Aborting.

</details>

**Comment by Aokromes** [comment]
@dm4g3 Try on 1.3.14 :)

**Comment by Aokromes** [comment]
no answer for over a year, closing.
