### ISSUE TITLE
Save as window goes bottom of Telegram window in media full screen mode. 

### ISSUE THREAD

**Issue by dobi-zhd** [telegramdesktop/tdesktop#4936]
### Steps to reproduce
1.Open media in the full screen mode 
2.Select save as option from bottom of the screen
![screenshot from 2018-07-03 14-14-11](https://user-images.githubusercontent.com/40277012/42212477-7b8e37bc-7ecb-11e8-9df6-d321b6cf294d.png)

3.Save as window goes bottom of the Telegram window
![screenshot from 2018-07-03 14-22-57](https://user-images.githubusercontent.com/40277012/42212896-a747c70a-7ecc-11e8-9f67-f6cf6eb541e1.png)

### Expected behaviour
Save as window be the top window

### Actual behaviour
We must switch Telegram window to save as window

### Configuration
**Operating system:**
Linux mint 
**Version of Telegram Desktop:**
Version 1.3.9
**Used theme**:
Default

**Comment by aNNiMON** [comment]
Same on Linux Mint 18.3. Here's a demo
![issue4936](https://user-images.githubusercontent.com/1321838/42214653-bef00190-7ec4-11e8-8f4f-75cfa9b67fbd.gif)
When I open image and select Save as, the file chooser dialog is shortly opens on top of the Telegram window and then goes to bottom.
But when I select Save as with gif or video, the file chooser dialog opens normally on top. However, if you click Cancel, the video or gif disappears.

**Comment by Senderman** [comment]
Almost the same situation on ArchLinux, GNOME. When I try to **attach** file, the nautilus (filemanager) window appears under the Telegram window

**Comment by dobi-zhd** [comment]
Dear sir
Thanks for your warm coorporation.
