### ISSUE TITLE
No option to record a voice message on Windows since v1.3

### ISSUE THREAD

**Issue by Samillion** [telegramdesktop/tdesktop#4938]
This issue has been reported before here #4783 for MacOS, it seems to exist on the Windows version as well.

The option to record a voice message is not there since 1.3. The microphone icon simply disappeared.

### Steps to reproduce
1. Install Telegram using the Windows installer.
2. Open Telegram and activate an account
3. Attempt to send/record a voice message

### Expected behavior
Click on the microphone icon to record a voice message.

### Actual behavior
Microphone icon and the option to record a voice message has disappeared.

### Configuration
**Operating system:** Windows 10 1803 x64

**Version of Telegram Desktop:** v1.3.9

**Used theme**: Dark

**Comment by Aokromes** [comment]
It's there for me on RS5:
https://i.imgur.com/sV5yQrT.png

**Comment by Samillion** [comment]
Does that mean it will be fixed in the next stable release because you're running Alpha or are you saying that this is isolated to me only?

![0001](https://user-images.githubusercontent.com/17427046/42247211-0282fc22-7f20-11e8-85a0-caf3c8f0783e.JPG)
![0002](https://user-images.githubusercontent.com/17427046/42247212-02b0850c-7f20-11e8-8101-35c069a75004.JPG)

**Comment by john-preston** [comment]
@Samillion Please check two portable versions to be sure that it stopped working from 1.3:

Here is 1.2.17: https://github.com/telegramdesktop/tdesktop/releases/download/v1.2.17/tportable.1.2.17.zip

Here is 1.3.0:
https://github.com/telegramdesktop/tdesktop/releases/download/v1.3.0/tportable.1.3.0.zip

You can download and unpack them in some separate unrelated folders and try each of them. If in this test you'll confirm that it works in 1.2.17 and doesn't work in 1.3.0 we will try to narrow it down further.

**Comment by Aokromes** [comment]
I think ATM 1.3.9 alpha and 1.3.9 stable have the same code, idk why you have that bug.

**Comment by Samillion** [comment]
@john-preston Strange. Both portable versions also don't show the microphone icon at all.

I'm trying to figure out what could be affecting Telegram only on my system. Microphone is detected and works well on all, and used to on Telegram on older versions, maybe I'm just not remembering which older version.

**Comment by john-preston** [comment]
@Samillion You can try any old portable version from here:

https://github.com/telegramdesktop/tdesktop/releases

If you find the one that's working we can try to find. Otherwise I guess they all stopped working at the same time due to some changes in your configuration, I'm not sure what exactly.

**Comment by Samillion** [comment]
You're right. It's definitely looking like something specific to my system. I tried down to version 1.2.6 and it's the same thing, no microphone icon. Very strange.

Apologies for the inconvenience. I'll close this for now, and update it with a solution if I ever figure out what's causing it, in case someone else experiences the same thing.

**Comment by Samillion** [comment]
Yup, this was definitely a problem in configuration, more accurately Windows 10 1803. Microphone settings were changed under privacy revoking access to it.

**Solution:**
Go to Windows Settings -> Privacy -> Microphone -> Under "Allow apps to access your microphone", make sure it's "On".
