### ISSUE TITLE
0.7.16 doesn't respect natural scrolling on Linux

### ISSUE THREAD

**Issue by anavarre** [telegramdesktop/tdesktop#494]
Pretty sure this wasn't the case before or it'd have struck me. 0.7.16 doesn't respect the Linux system wide Natural Scrolling option which mimics scrolling on a phone and which was introduced to a desktop OS by Apple.

FWIW I'm using Ubuntu, with the KDE environment (Kubuntu)

**Comment by telegramdesktop** [comment]
Qt handles scrolling, did it respect it in 0.7.13? https://tdesktop.com/linux/tsetup.0.7.13.tar.xz

**Comment by anavarre** [comment]
Just tried and it did work.

**Comment by telegramdesktop** [comment]
Seems like Qt 5.4.0 broke that was fine in Qt 5.3.1 (0.7.13 uses Qt 5.3.1, 0.7.16 uses Qt 5.4.0) - should submit a Qt bugreport I guess. Better check in some other Qt 5.4.0 software first (QtCreator 3.3 for example) that it really isn't only Telegram Desktop.

**Comment by anavarre** [comment]
I can submit a Qt bug report if it's of any help but I won't have much to add to the bug report. If you do report a bug and explain what you see and the libraries you use, I guess the Qt developers would be able to explain what's going on better.

**Comment by auchri** [comment]
If it's not fixed yet, it's a Qt issue, so I close this.

**Comment by hobarrera** [comment]
Is there an upstream Qt issue for tracking this?

**Comment by Arcaena** [comment]
Seconded; is there an upstreatm QT bug being tracked? If not, an option in tdesktop for reversing the scroll direction anyhow would at least help those of us affected by this.
