### ISSUE TITLE
App not perfectly maximizing

### ISSUE THREAD

**Issue by TopperDEL** [telegramdesktop/tdesktop#4942]
### Steps to reproduce
1. Open the Telegram Desktop client
2. Maximize it to the screen

### Expected behaviour
The App Shows in Fullscreen with correctly aligned borders and Buttons.

### Actual behaviour
The app leaves an empty space on top where I can "see through" to the apps below. And on the Right side it doesn't snap to the border of the screen. On my second screen - the left one - the app is misaligned when maximized to that a part of the Right side of the app in visible on the first screen (my Right one).

### Configuration
Windows 10

**Version of Telegram Desktop:**
1.3.9

**Used theme**:
Default
![telegram](https://user-images.githubusercontent.com/1833242/42325734-6709f338-8067-11e8-8878-3c8474219e8a.png)

**Comment by Worrah** [comment]
same here, really annoying 
it happens after recent wndows updates, before all worked fine
first maximize works good, but after it all messed up
![image](https://user-images.githubusercontent.com/34601253/42330116-107c35c6-807b-11e8-8f99-6329938c2e75.png)

**Comment by stek29** [comment]
#4649

**Comment by levrik** [comment]
@TopperDEL @Worrah See my latest comment in https://github.com/telegramdesktop/tdesktop/issues/4649#issuecomment-407722748

**Comment by TopperDEL** [comment]
As mentioned from @levrik above the Windows update KB4340917 (OS Build 17134.191) fixes the issues. I will close it then.
