### ISSUE TITLE
Album caption not displayed

### ISSUE THREAD

**Issue by mbasaglia** [telegramdesktop/tdesktop#4943]
Looks like if someone sends an album, the caption is shown in the last message preview on the chat list but not in the actual chat (it shows the images but not the caption)

### Steps to reproduce
1. Send an album
2. Look at the message on telegram desktop

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/pull/4869 ?

**Comment by mbasaglia** [comment]
This is regarding how telegram desktop displays the caption, not how it sends it.

**Comment by Aokromes** [comment]
it looks like on telegram android.
