### ISSUE TITLE
Can't call without a microphone

### ISSUE THREAD

**Issue by zarEclEC** [telegramdesktop/tdesktop#4945]
### Steps to reproduce
1. Don't own a microphone
2. Call someone

### Expected behaviour
The call starts and my "microphone" is muted and can't be turned on

### Actual behaviour
Can't call

### Configuration
**Operating system:** Windows 10 

**Version of Telegram Desktop:** 1.3.9

**Used theme**: Default

**Comment by ArmeF97** [comment]
Why? To make person without a microphone unable to call? What's the gain?

**Comment by grishka** [comment]
What's the point of calling and not being able to say anything anyway? :)

You could install one of those "virtual audio cable" drivers and play something into the call if you insist.

**Comment by ArmeF97** [comment]
>  What's the point of calling and not being able to say anything anyway? :)

Listen what the other has to say?

> You could install one of those "virtual audio cable" drivers and play something into the call if you insist.

No, I don't see why the user has to do something in his pc when the issue is in this client

**Comment by stek29** [comment]
@ArmeF97 I don't think that lack of microphone is not an issue in PC

**Comment by ArmeF97** [comment]
Just tell me why the call can't start without a microphone... can't the desktop client simply don't use it?
@stek29

**Comment by Aokromes** [comment]
add virtual phone as workaround.

**Comment by ArmeF97** [comment]
Virtual microphone? Already suggested by @grishka , libtgvoip developer. I already replied to him.
Or did you mean something different?

**Comment by ArmeF97** [comment]
I still want this feature request to be open

**Comment by ArmeF97** [comment]
Any update on this?

**Comment by grishka** [comment]
I was since fired and libtgvoip was since retired and they're now using a webrtc-based solution that is sometimes worse than mine was, but whatever. It still doesn't make much sense to have a one-to-one call when one side doesn't have a microphone. You could as well use voice messages to the same effect.

**Comment by ArmeF97** [comment]
For example a group voice chat without a microphone would be useful, you just need to listen

**Comment by ArmeF97** [comment]
keep it open

**Comment by john-preston** [comment]
@zarEclEC Am I right that the group voice / video chats can be joined without camera or microphone? This should be possible.

One-on-one calls were not supposed to be working without a microphone, sorry.

**Comment by kshpytsya** [comment]
[Sign language](https://en.wikipedia.org/wiki/Sign_language) may also be a valid use-case.
