### ISSUE TITLE
can't search Chinese

### ISSUE THREAD

**Issue by kzhui125** [telegramdesktop/tdesktop#4946]
### Steps to reproduce
1.  send Chinese message such as 今天天气不错。
2.  search 天气
3.  No messages found

same as ios version.

**Comment by kzhui125** [comment]
@stek29 

Can this issue be fixed?

**Comment by stek29** [comment]
not on tdesktop side

**Comment by kzhui125** [comment]
Which repository should I post?

**Comment by stek29** [comment]
@kzhui125 contact telegram via in-app support or twitter
