### ISSUE TITLE
fontconfig directory inside home

### ISSUE THREAD

**Issue by koukos** [telegramdesktop/tdesktop#495]
After updating to version 0.7.16 a fontconfig directory appears inside /home/user my home directory. Any workarounds to get rid of it? Can we at least make it hidden. I am using debian Jessie with KDE.
Apart from this rather annoying directory the app works great.

**Comment by hk0O7** [comment]
Same here with Linux Mint 17 (Ubuntu Trusty). If I delete the folder and start Telegram Desktop again, it re-appears, but only filled with '.cache-3' files.

**Comment by telegramdesktop** [comment]
https://bbs.archlinux.org/viewtopic.php?id=173124

Seems like "fontconfig" library looks for "$XDG_CACHE_HOME/fontconfig/*.cache-*" to place the cache files, and somehow when there is no $XDG_CACHE_HOME it places them in ~/fontconfig?

In Ubuntu it creates ~/.fontconfig and everything is fine, but not in other distrs I guess. Maybe setting $XDG_CACHE_HOME somewhere like ~/.cache will help.

**Comment by sojusnik** [comment]
Same here on Ubuntu Gnome 14.10.

**Comment by repsorp** [comment]
Ubuntu 14.10
tdesktop updated today to version 0.7.17
fontconfig directory still appearing in /home/user

**Comment by repsorp** [comment]
Setting XDG_CACHE_HOME:-$HOME/.cache doesn't clear up

**Comment by repsorp** [comment]
tdesktop updated today to version 0.7.18 dev
fontconfig directory still appearing in /home/user

**Comment by slametapr** [comment]
same problem here.. elementary os freya

**Comment by koukos** [comment]
Trying to understand a bit more the cause i figured out the following fontconfig errors in my system:

libs init..
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

My guess is that fixing them should probably avoid the creation of the fontconfig directory.
Any help here?

Best Regards,
K.

**Comment by repsorp** [comment]
Rename ~/fontconfig directory to ~/.fontconfig
No more fontconfig directory appearing inside home directory
Worked for me

**Comment by hk0O7** [comment]
I tried that twice, and somehow the second time worked. Thanks.

**Comment by ppparadox** [comment]
I have the "fontconfig" folder appearing on my desktop each time i launch Telegram Desktop v.0.7.17 on Linux Mint MATE 17.1 x86_64. 
I have a symlink on my desktop for launching. It is pointing to "$HOME/Telegram/Telegram". 
My ~/.profile contains XDG_CONFIG_HOME="$HOME/.cache/" yet nothing appears there.

**Comment by ppparadox** [comment]
Launching from the terminal always shows the following errors:
$ ./Telegram
libs init..
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

**Comment by ytj** [comment]
The same on Mint.

> /opt/telegram/Telegram        
libs init..
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

**Comment by timorei** [comment]
Running Kubuntu vivid beta hereand I just renamed the *fontconfig* directory to *.fontconfig*

I guess there's a messup somewhere looking for ~/.fontconfig and if it's not there create "fontconfig".
Anyways: renaming it (dolphin -> select folder -> rename -> add "." in front -> done. seems to have done it as no fontconfig directory is being created anymore.

**Comment by mvdan** [comment]
Also happening here, rather annoying.

**Comment by hk0O7** [comment]
It started happening to me again, too.

**Comment by ppparadox** [comment]
Post your system specs otherwise you're just whining and not helping.

**Comment by hk0O7** [comment]
Linux Mint 17 MATE Edition (x86_64) here.

**Comment by bil-elmoussaoui** [comment]
The same thing on ubuntu gnome 15.04 beta 2 with gnome 3.16

**Comment by jlacroix82** [comment]
Same thing on Arch Linux. I keep deleting this folder but when I launch Telegram it comes back. I do not want this folder in my home directory unless it's hidden.

**Comment by Yanpas** [comment]
Workaround: create file ".hidden" and put there line "fontconfig". Works with most FMs

**Comment by hk0O7** [comment]
That seems to work, for now. Thanks, Yan!

**Comment by lucaciavatta** [comment]
> Same thing on Arch Linux. I keep deleting this folder but when I launch Telegram it comes back. I do not want this folder in my home directory unless it's hidden.

The same on Fedora 21.

**Comment by vochor** [comment]
I have two Debian Jessie installations, one is x86 and the other is amd64.
After launch Telegram in my "Debian Jessie x86" machine, a "fontconfig" folder is created inside my "home" folder.
However the "fontconfig" folder is not created in my "Debian Jessie amd64" machine at any time.

**Comment by kittee** [comment]
:+1:

**Comment by lucaciavatta** [comment]
New Fedora installation, same problem. I have tried the '.fontconfig' hidden file workaround, bot doesn't work. Every time I start Telegram, the 'fontconfig' folder appears again in my 'home' folder.

**Comment by Yanpas** [comment]
@lucaciavatta try my workaround (look upper)

**Comment by lucaciavatta** [comment]
@Yanpas I did it, but it doesn't work under Fedora Gnome 21.

**Comment by koukos** [comment]
Hello,

I had the same problem with fontconfig directory. 
First time i solved it by renaming it into a hidden .fontconfig directory
After the latest update it appeared again. The problem is that
every time that some fonts are missing it will create a fontconfig
directory and put the missing fonts inside.

Simply cut and paste the contents into .fontconfig and remove it
every time it appears. It's a nasty solution but it works so far.

Hope it helps.

**Comment by ppparadox** [comment]
Every time it reappears = every time you start Telegram...
The .hidden workaround works on Linux Mint MATE 17.1 x86_64 using Telegram 0.8.11.

**Comment by lucaciavatta** [comment]
After the update to version 0.8.11, 'fontconfig' appeared again as usual so I have tried to rename it to '.fontconfig'. I have closed and started again Telegram many times and the folder 'fontconfig' is no longer reappeared.

The update not fixed the issue because 'fontconfig' appeared in home directory at first launch, but now the '.fontconfig' workaround seems working.

**Comment by repsorp** [comment]
ubuntu 15.04 / telegram 0.8.11
'.fontconfig' workaround  doesn't work here
both 'fonconfig' & '.fontconfig' directories in my home directory
workaround from Yanpas is ok

**Comment by lucaciavatta** [comment]
Fresh install Telegram 0.8.11 on Ubuntu 15.04 and 'fontconfig' appears on home folder.

mv '/home/user/fontconfig' '/home/user/.fontconfig' 
solves the issue as on Fedora.

**Comment by lucaciavatta** [comment]
Today on Ubuntu 15.04 'fontconfig' appears again in home folder.
I have tried also the '.hidden' workaround from Yampas, but 'fontconfig' appears again and again.

**Comment by drakulavich** [comment]
Telegram 0.8.17 on Ubuntu 15.04. The same issue.
Thanks Yanpas for the workaround!
```
echo "fontconfig" >> .hidden
```

**Comment by auchri** [comment]
@drakulavich so it's fixed?

**Comment by bil-elmoussaoui** [comment]
yes it's ;)

**Comment by JFingerle** [comment]
I still get the same error on Fedora 21 with Telegram Desktop 0.8.52
```
[jfingerle@jfingerle .TelegramDesktop]$ pwd
/home/jfingerle/.TelegramDesktop
[jfingerle@jfingerle .TelegramDesktop]$ ll
total 50392
drwxr-xr-x. 2 jfingerle jfingerle     4096 Sep  1 11:58 fontconfig
-rw-rw-r--. 1 jfingerle jfingerle      112 Sep  1 11:58 log.txt
drwxrwxr-x. 2 jfingerle jfingerle     4096 Sep  1 11:58 tdata
-rwxrwxr-x. 1 jfingerle jfingerle 51539476 Aug 19 16:55 Telegram
-rwxrwxr-x. 1 jfingerle jfingerle    41982 Aug 19 16:26 Updater
[jfingerle@jfingerle .TelegramDesktop]$ ./Telegram 
libs init..
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/65-0-lohit-bengali.conf", line 32: unknown element "langset"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/65-0-lohit-bengali.conf", line 32: unknown element "langset"
```
