### ISSUE TITLE
Image view gets stuck when alt-tabbing.

### ISSUE THREAD

**Issue by KelvinShadewing** [telegramdesktop/tdesktop#4950]
### Steps to reproduce
1. Click on a photo
2. Alt-tab to anything else
3. Try to click on anything

### Expected behaviour
The image view should appear behind other app windows that take focus or just close when switching to another app, and should disappear when you click away from it like normal after switching.

### Actual behaviour
If you happen to alt-tab, the image view will remain on top of any windows you switch to, and will not disappear when you click the X or around the image. Switching back to Telegram does not fix the issue. I have to use `skill -SIGKILL` to kill the process and then relaunch Telegram.

### Configuration
**Operating system:** Linux Mint 18.2

**Version of Telegram Desktop:** 1.3.9

**Used theme**: Standard night mode

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
#3553
