### ISSUE TITLE
Set HTTP proxy via tg:// protocol

### ISSUE THREAD

**Issue by ameer** [telegramdesktop/tdesktop#4953]
### Steps to reproduce
1. Click on a link like this tg://proxy?server=127.0.0.1&port=8080

### Expected behaviour
The application should open and prompt the user for adding new proxy

### Actual behaviour
Nothing just happens.

### Configuration
**Operating system:**
Windows 10 Enterprise
**Version of Telegram Desktop:**
1.3.9 Alpha
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@ameer tg://proxy is for mtproto proxies only, tg://socks is for socks5 proxies only. HTTP proxy is supported only by Telegram Desktop (is not supported by any of mobile apps), so there is no link format for them.
