### ISSUE TITLE
how can I create chat shortcut on desktop

### ISSUE THREAD

**Issue by emlen** [telegramdesktop/tdesktop#4954]
Some years ago i created this one, but now I couldn't. Could somebody help me? Thanks.

**Comment by stek29** [comment]
if that chat has a username, you can use `tg://resolve?domain=username`

**Comment by emlen** [comment]
Thank You for your answer, but last decision was using command line of telegramdesktop.

**Comment by emlen** [comment]
nobody know?

**Comment by Lonami** [comment]
Not really an issue. Use a link shortcut or pin your very important dialog/chat to the top?
