### ISSUE TITLE
Account has been deleted.

### ISSUE THREAD

**Issue by P-Alban** [telegramdesktop/tdesktop#4956]
I create a new account, connect it to the client, I try to invite users through the api, and the account is immediately deleted. Well I think I created another account, sat on it, did some activity, tried again, and what? HE AGAIN REMOVED. Well, I registered an account from another IP, AND ACCOUNT AGAIN REMOVED, SHIT!
Well, I'll create a simple account, not for interaction with the api, and he'll be spared again!
Are you fucking kidding me ?!

**Comment by stek29** [comment]
How is TDesktop related?

**Comment by stek29** [comment]
anyway, contact `recover@telegram.org`

**Comment by P-Alban** [comment]
sorry, my ass is burn
