### ISSUE TITLE
Add feature to hide messages or groups?

### ISSUE THREAD

**Issue by MetalKingdom** [telegramdesktop/tdesktop#4957]
Would be possible to add this feature in the new updates of telegram?
Something like telegram to exclude some messages or groups without leaving them, just hide them.

**Comment by 23rd** [comment]
You can turn on [hidden workmode](https://github.com/telegramdesktop/tdesktop/wiki/Hidden-modes) and hide all muted chats.

**Comment by 23rd** [comment]
Did you even try to enable `workmode` and see what it does?

**Comment by MetalKingdom** [comment]
How to enable workmode i didnt get to enable this feature? where is how to use it? Some picture?

**Comment by stek29** [comment]
> Open Settings and type “workmode” on the keyboard (if you’re old like me, you remember this iddqd drill). This will give you a button at the top of the chats list that switches between showing all chats and only those for which you have notifications enabled.
