### ISSUE TITLE
Time stamp font issue

### ISSUE THREAD

**Issue by christophertoh** [telegramdesktop/tdesktop#4959]
### Steps to reproduce
N.A.

### Expected behaviour
Time stamp shown on each message bubble to be in numbers

### Actual behaviour
Time stamp shown on each message bubble appears in an unreadable font
<img width="511" alt="telegram pic" src="https://user-images.githubusercontent.com/36026080/42499165-a9034a58-8460-11e8-808e-d8aedac0e423.png">

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
Telegram 1.3.9
**Used theme**:
basic
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@christophertoh Those look like arabic numbers. System time format is used in this place.

**Comment by christophertoh** [comment]
@john-preston thank you! apologise for my ignorance on the arabic numbers. I managed to fix it.
