### ISSUE TITLE
Telegram Desktop doesn't support http proxy with digest authentification

### ISSUE THREAD

**Issue by selivan** [telegramdesktop/tdesktop#4960]
### Steps to reproduce
1. Settings - Connection type
2. Add proxy, type HTTP
3. Enter host, port, username and password for http proxy with digest authentification
4. Press OK, wait while it is trying to check new proxy

### Expected behaviour
Telegram should be able to connect using specified http proxy with [digest authorization](https://en.wikipedia.org/wiki/Digest_access_authentication).

### Actual behaviour
Proxy is shown as "not anavailble". Web browser on the same machine uses the same proxy with same credentials successfully. Problem is in Telegram Desktop.

### Configuration
**Operating system:** Ubuntu GNU/Linux 16.04 Xenial

**Version of Telegram Desktop:** 1.3.9

**Used theme**: default

Example config for squid 3.5 proxy with digest authentification:
```
http_port 3128

auth_param digest program /usr/lib/squid/digest_file_auth -c /etc/squid/passwd
auth_param digest realm proxy

acl authenticated proxy_auth REQUIRED

http_access allow authenticated

# Direct proxy without cache
cache deny all

via off
forwarded_for delete
```
 And creating password file for it: `htpasswd -c /etc/squid/passwd username`

**Comment by stek29** [comment]
I'm afraid that Qt doesn't support it.

**Comment by AbedSHP** [comment]
I have this problem too. may I ask why?

**Comment by Aokromes** [comment]
@AbedSHP you must ask QT devs for this.

**Comment by nice-vladi** [comment]
I have same problem. Can't connect via HTTP proxy (default mikrotik http proxy). Another software like apt, firefox and etc. working perfectly.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4960#issuecomment-404427793
