### ISSUE TITLE
Weird mouse behaviour after resume from suspend.

### ISSUE THREAD

**Issue by antmarra** [telegramdesktop/tdesktop#4962]
### Steps to reproduce
1. Suspend Linux (Ubuntu 18.04) PC with Telegram active
2. Resume PC
3. Telegram Desktop starts behave crazy...

### Actual behaviour
After resuming from suspend, while Telegram active, on mouse over the left pane (contacts) single mouse click starts dragging the contact head instead of simply open the corresponding chat.
Moreover, after that, moving the mouse over the conversation starts selecting messages in it.
Sometimes it is impossible to write into a chat because it starts showing typed chars and selecting them, so every keystroke substitute the previous one (and it keeps on while typing).
It seems that it takes left mouse button click but it doesn't take the button release.
This behaviour seems not take part in other applications.

### Configuration
Linux Ubuntu 18.04 (Gnome) LTS x86-64

Telegram Desktop version: 1.3.9 (but this happened with several previous releases in Ubuntu 18.04)

</details>

**Comment by antmarra** [comment]
I forgot to write... when this behaviour starts, closing and reopening Telegram Desktop DOESN'T resolve this issue.

**Comment by john-preston** [comment]
@antmarra Perhaps you close it to tray and reopen from tray? What if you relaunch it with "Quit Telegram" from the tray menu?

**Comment by antmarra** [comment]
@john-preston I've tried anything. Close Telegram window without quitting, quit Telegram from tray and reopen. Nothing worked.

**Comment by yustnip** [comment]
Have the same trouble. Ubuntu 17.10, 18.04. May be reopen the issue?

Can add that when this mouse behavior happens, a right click on Chrome tab also stops working.

**Comment by stek29** [comment]
> a right click on Chrome tab also stops working

then it's probably not a TDesktop issue :(

**Comment by yustnip** [comment]
It can be a conflict between touchscreen and touchpad. Waiting for the issue will have reproduced again.
