### ISSUE TITLE
Telegram Desktop dies when i plug in my yubikey

### ISSUE THREAD

**Issue by Nyno-Kun** [telegramdesktop/tdesktop#4963]
### Steps to reproduce
1. Have telegram desktop open or in background running
2. insert yubikey
3. telegram is gone

### Expected behaviour
Telegram should not quit if i plug in my yubikey

### Actual behaviour
Whenever i plug in one of my yubikeys, telegram desktop just crashes and is gone until i restart it.
Funny thing: if i have my yubikey attached, telegram starts normal.. until i plug out the yubikey.
Does not happen with other usb devices

### Configuration
**Operating system:**
Debian 9, i3wm
**Version of Telegram Desktop:**
1.3.9
**Used theme**:
Night Mode vanilla

Insert logs here (if necessary)
All i get in logs is this from syslog:
kernel: [4074142.860757] MTP::internal::[2959]: segfault at d150cd8 ip 00007f70d088a0e3 sp 00007f70c00cbc58 error 4 in libc-2.24.so[7f70d0806000+195000]

**Comment by stek29** [comment]
#2478
