### ISSUE TITLE
Telegram desktop crashes when starting a voice call

### ISSUE THREAD

**Issue by alabotski** [telegramdesktop/tdesktop#4965]
Steps to reproduce

    Start telegram desktop
    Call a contact (on Windows)
    Contact answers..

Expected behaviour

Voice call should begin.
Actual behaviour

Telegram crashes (window closes).
Configuration

Operating system:
Windows 10

Version of Telegram Desktop:
1.3.9

Used theme:
Default?

[dumps.zip](https://github.com/telegramdesktop/tdesktop/files/2185394/dumps.zip)

**Comment by ariel-** [comment]
Reproduced on Telegram Desktop Alpha 1.3.12
Windows 10 Enterprise x64 version 1803

Can be reproduced easily calling `@magnaluna`, as soon as you pickup a call/recipient picks up -> crash

**Comment by Aokromes** [comment]
@LeshaRB Try on 1.3.14 :)

**Comment by jawsper** [comment]
Still happens with Telegram Desktop 1.3.14, Windows 10 Pro x64 version 1803...

**Comment by john-preston** [comment]
@LeshaRB It doesn't crash for me on Windows 10, macOS 10.13.6 or Ubuntu 14.04.

**Comment by john-preston** [comment]
@LeshaRB Can you please go to Start -> Settings -> Privacy -> Microphone and switch on "Allow apps to access your microphone". I hope this way calls will work and won't crash.

**Comment by LeshaRB** [comment]
@john-preston I have portable telegram so I don't see it 

![image](https://user-images.githubusercontent.com/439337/44956705-fadcb900-aed0-11e8-9c33-dadcf451913b.png)

**Comment by Aokromes** [comment]
that big list is only for UWP apps :)

**Comment by ariel-** [comment]
Solved with @Aokromes help. To reproduce both "App access to microphone" and "Device access to microphone" disabled -> crash.

**Comment by LeshaRB** [comment]
Have you checked this on the portable version? Or just close the ticket?

**Comment by LeshaRB** [comment]
@ariel- I wait normal release 1.3.16 and try it
