### ISSUE TITLE
Suggest popular stickers don't work

### ISSUE THREAD

**Issue by Clevercat60** [telegramdesktop/tdesktop#4966]
### Steps to reproduce
1. Open a chat
2. Type an emoji

### Expected behaviour
If "Suggest popular stickers by emoji" is enabled, Telegram should suggest my stickers + popular stickers

### Actual behaviour
Telegram only suggests my stickers

### Configuration
**Operating system:** Windows 10 Version 1709

**Version of Telegram Desktop:** 1.3.9

**Used theme**: Default

![clipboarder 2018 07 11-004](https://user-images.githubusercontent.com/41125002/42593345-6836d998-8561-11e8-8e3c-64fd5856965e.png)

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@Clevercat60 Thanks! This was accidentally removed and no one saw until now 😭
