### ISSUE TITLE
Select specific chat to be exported/ability to skip the data already exported.

### ISSUE THREAD

**Issue by Aphotice** [telegramdesktop/tdesktop#4968]
### Steps to reproduce
1. Have a huge amount of private chats(old data,1million limit on each chat).
2. Want to export/back them via the new feature.
3. Close telegram by mistake, PC power outage/crash.

### Expected behaviour
It should let us choose which chats we want to export, so we can skip the ones already exported, or be smart enough to continue after failing midway, skipping the chats it has already backed up/exported, ability to resume from where it left.

### Actual behaviour
it just starts from the beginning.

### Configuration
**Operating system:** Windows 10 Enterprise build 1803

**Version of Telegram Desktop:** 1.3.9 alpha
![image](https://user-images.githubusercontent.com/30921064/42629579-0895d0b0-85e9-11e8-832a-58af6bc71289.png)

**Used theme**: Incognito by @IncognitoTheme
#dark #grey

Notes:
i selected to export ONLY videos.
i want all my private chat's video files.
but i was almost done like(566/588 chats)
but my computer was turned off because of power outage.....

I dont want to do the whole export from the start.
Its not smart enough to see what files it already has so it can skip them at least? it takes 2/3 whole days to download 50GBs of data from start with my horrible internet speed in Iran(900kbps) that is slowed down even more by government blockages & VPNs my speed is like 400kbps at its best. does it use peer to peer connection, its slow. any workaround?
![image](https://user-images.githubusercontent.com/30921064/42629512-c5f23b54-85e8-11e8-88ef-407ac56e5370.png)

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Aphotice** [comment]
🔂 Telegram Desktop 1.3.11 Alpha

• Allow single chat history export.

2018-08-02

i read this in the patch notes & was excited but i cant figure out how to make it export one chat ... i select private chats & it just starts to export all my 300+ chats that litertally take 24+ hour...no way to select single chat.

**Comment by john-preston** [comment]
@Aphotice In the three dot menu inside the chat.

**Comment by Aphotice** [comment]
ah perfect & handy, ill try it tonight!
i greet thee.

**Comment by Aphotice** [comment]
![image](https://user-images.githubusercontent.com/30921064/43721123-319f7476-99a7-11e8-9b39-2983c1658daa.png)
this happened overnight that i let it run on single chat history export on a big chat...
