### ISSUE TITLE
Problem with Instagram link previews

### ISSUE THREAD

**Issue by Clevercat60** [telegramdesktop/tdesktop#4969]
### Steps to reproduce
1. Copy link of an Instagram post with multiple photos
(e.g. https://www.instagram.com/p/BlFdr34luDh)
2. Send that link to a chat
3. Open link preview's photo

### Expected behaviour
Telegram should show all photos of that Instagram post and show thumbnails in the lower part of the screen ([like mobile versions](https://t.me/telegram/82))

### Actual behaviour
Telegram only show the first photo of that Instagram post

### Configuration
**Operating system:** Windows 10 Version 1709 x64

**Version of Telegram Desktop:** 1.3.9

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
#2396
