### ISSUE TITLE
macOS call faild 

### ISSUE THREAD

**Issue by Qt-Preston** [telegramdesktop/tdesktop#4973]
### Steps to reproduce
1. macOS version is 10.13.5
2. The other people call me in telegram,when I receive the notification and answer it,telegram will show a dialog and sey "There seems to be a problem with audio playback on your computer. Please make sure that your computer's speakers and microphone are working and try again."
3. in history,it always show send with text and no record button.
4. my mac can play music or video in other app.
[last_call_log.txt](https://github.com/telegramdesktop/tdesktop/files/2191336/last_call_log.txt)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Aokromes** [comment]
Try on 1.3.14 :)

**Comment by Aokromes** [comment]
no answer for more than 1 year, closing.
