### ISSUE TITLE
I have downloaded more than 100 videos of my tution's or group's channel. but only few of them are shown in download folder. why not others are showing.

### ISSUE THREAD

**Issue by coderofsiliconvalley** [telegramdesktop/tdesktop#4974]
### Steps to reproduce
1. support bulk videos download and should not hang when videos of 1GB are downloaded in quantity of 100's.

### Expected behaviour
videos should be shown in files and can be access from them.

### Actual behaviour
videos are shown only in desktop app and not in files>Telegram Desktop folder

### Configuration
**Operating system:**
Windows 10 pro.
**Version of Telegram Desktop:**
latest.

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
are they videos or documents?

**Comment by Aokromes** [comment]
cannot reproduce, i have download 100s of files and all are there.
