### ISSUE TITLE
Update error! (telegram desktop, last 3 build releases)

### ISSUE THREAD

**Issue by pandages** [telegramdesktop/tdesktop#4975]
This issue is occurring on all of my computers, each from different vendors and with different hardware.  I can provide information on that if necessary, but I don't think it should be.

### Steps to reproduce
1. install telegram desktop.
2. wait for a new build to be released
3. click "update telegram" and watch this error happen

### Expected behaviour
Telegram should update as intended, and as it always has for me in the past.

### Actual behaviour
I get an error message that says:

---------------------------
Update error!
---------------------------
Failed to update Telegram :(
C:\Users\Kaishi\AppData\Roaming\Telegram Desktop\Telegram.exe is not accessible.
---------------------------
Retry   Cancel   
---------------------------

If I then download the new Installer for that version, and execute it, I get a different error message:

---------------------------
Error
---------------------------
C:\Users\Kaishi\AppData\Roaming\Telegram Desktop\Telegram.exe

An error occurred while trying to replace the existing file:

DeleteFile failed; code 32.

The process cannot access the file because it is being used by another process.

Click Retry to try again, Ignore to skip this file (not recommended), or Abort to cancel installation.
---------------------------
Abort   Retry   Ignore   
---------------------------

### Configuration
**Operating system:** Windows 10, current.

**Version of Telegram Desktop:** 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@pandages Some process blocks the updater app the access to the Telegram.exe, so it can't overwrite it :(

**Comment by pandages** [comment]
It sure does, that's evident from the error message.  But there's no indication of -which- process or -why-.  This did not used to happen.  It is a recent issue, and across all of my computers.

**Comment by amenantaud** [comment]
I have the same issue here. It seems that the System process is the one accessing the file, but I don't know why.

**Comment by pandages** [comment]
How did you check that? because the System process is the NTOS Kernel.

**Comment by amenantaud** [comment]
In the resource monitor. Btw I managed to update Telegram by trying again after rebooting my computer.

**Comment by pandages** [comment]
Yes as I mentioned above, at least the way I have installed Telegram Desktop, all I have to do is Log Off, then log back in, and run the installer without having run the program first.  But that's extremely annoying to do and it used to work as intended.

**Comment by deepsystm** [comment]
have same issue now, but when click "retry" it updates successful. Some bad activity??

**Comment by Aokromes** [comment]
maybe it's your antivirus software?

**Comment by alexnv** [comment]
I've had the same problem for months. The antivirus was turned off

**Comment by Aokromes** [comment]
#3764

**Comment by gkonterman** [comment]
I have the same problem, any other solutions?

**Comment by ollegsey** [comment]
I have the same problem, any other solutions?

**Comment by crllrd** [comment]
I have same problem, but for macOS

**Comment by TahseenAlaa** [comment]
I face the same issue right now on Windows 10 x64

**Comment by 01ivr3** [comment]
Same. It does not look like this issue was resolved, nor are is a clear indication of why it is occurring so frequently.

![image](https://user-images.githubusercontent.com/32587577/95643143-10365100-0a62-11eb-90fe-c8f514092e90.png)

**Comment by Muhammadyusuf96** [comment]
I face the same issue right now on Windows 8.1 x64
