### ISSUE TITLE
Reproduction of two media together.

### ISSUE THREAD

**Issue by Darkoonss** [telegramdesktop/tdesktop#4976]
Someone could tell me if this behavior is a bug or if it is anyway.

### Steps to reproduce
1. Have an audio message and an audio file in the conversation.
2. Run one at a time.

![image](https://user-images.githubusercontent.com/13522875/42703275-82ee0bd4-86a2-11e8-928e-0e199f3175cb.png)

### Expected behaviour
Should not the audio started pause first?

### Actual behaviour
The two audios are played together, overlapping each other.

### Configuration
**Operating system:**
Win7 x64

**Version of Telegram Desktop:**
1.3.9

**Used theme**:
Pattern

**Comment by john-preston** [comment]
@Darkoonss The idea was to allow to listen to a voice message (usually short and not very frequent) without stopping your music that is playing, just lowering its volume for about 80% while the voice message is playing.

**Comment by Darkoonss** [comment]
I understand.
I just thought it was strange when it happened. Well, I hope I have helped with something.
But I think it would be nice to have a way to measure it and if audio is great it will stop.
