### ISSUE TITLE
Build issue: ‘producer’ in namespace ‘rpl’ does not name a template type and others

### ISSUE THREAD

**Issue by ItachiSan** [telegramdesktop/tdesktop#4978]
### Steps to reproduce
Using the commands in the PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=telegram-desktop-dev ,
1. Download the sources
2. Apply the patches
3. Enter the sources directory and configure the software
4. Enter the build directory and build

### Expected behaviour
The build should work.

### Actual behaviour
The build fails, due to various problems between the `rpl` and `lib_export`.

### Configuration
**Operating system:** ArchLinux, all packages updated

**Version of Telegram Desktop:** 1.3.8 up to 1.3.10 (versions failing to build)

<details><summary><b>Logs</b>:</summary>
Minimal build log: https://gist.github.com/ItachiSan/bb79335d5fa24b489d01ace7e144de2e
</details>

**Comment by cranes-bill** [comment]
@ItachiSan If i'm not wrong, also not right **GSL** module is used  in this script. See the john-preston's comment [here](https://github.com/telegramdesktop/tdesktop/issues/4967#issuecomment-405035401).

**Comment by ItachiSan** [comment]
@cranes-bill thanks for the reference, I will check it :smile: 
Any other support?

**Comment by angelsl** [comment]
Insert the following line

```
add_precompiled_header(lib_export ../../Telegram/SourceFiles/export/export_pch.h)
```

into `CMakeLists.inj` in the Arch build files.

---

tdesktop uses a patched `gyp` generator that inserts some extra CMake commands to handle precompiled headers. Debian (and the Arch packages that derive from Debian's build scripts) does not want to use a patched `gyp`, so instead they manually insert the lines into the generated `CMakeLists.txt`.

Seems like recently, tdesktop created/split off a small sublibrary called `lib_export` which uses a PCH, so we need to update our manual `CMakeLists.txt` modification for that.

**Comment by ItachiSan** [comment]
@angelsl thanks for the tips! That helped a lot!
Issue is solved due to the comment: https://github.com/telegramdesktop/tdesktop/issues/4978#issuecomment-405251671
