### ISSUE TITLE
Removing chat background in Night mode (in particular)

### ISSUE THREAD

**Issue by rpodric** [telegramdesktop/tdesktop#4979]
### Steps to reproduce
1. Enable Night mode. Note that there's no visible background in this mode, which is appropriate.
2. Choose a chat background other than Daisies (not because it makes sense, but because you're experimenting).
3. Now try to return to using no background. You cannot.

The solution:
1. Select the default Daisies background
2. Disable Night mode
3. Enable Night mode

You will now be back to no visible background.

I think this will tend to come up for people once they try out Night mode and then decide to play with some backgrounds. They might think, like I did, that backgrounds and night mode are not the best pairing, and so they'll want to revert...but they can't without knowing this non-intuitive trick. The only reason I thought to try it is I began to wonder how I got dark mode with no background in the first place.

There is a "blank" box at the bottom of the chat background gallery that I thought might do it, but it doesn't.

The optimal fix would be adding a "Remove background" right in the main "Chat background" area itself in Settings. This would work regardless of being in light or dark mode (it's possible that some may not want a background even in light mode).

### Expected behaviour
You should be able to use no background easily.

### Actual behaviour
If in Night mode, you cannot remove the background without using the above obscure trick. If in light mode, you may not be able to go background-less at all.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.3.7 (and very likely earlier) to 1.3.10

**Used theme**: None

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by signalguest** [comment]
Thank you for the workaround.

That was preventing me using the dark theme only at night.

**Comment by krupenja** [comment]
This is fixed in Telegram 1.3.11 alpha.

**Comment by rpodric** [comment]
Thanks
