### ISSUE TITLE
Valgrind shows many bugs

### ISSUE THREAD

**Issue by ShabbyX** [telegramdesktop/tdesktop#498]
In Linux, try running:

    $ valgrind ./Telegram

You will see many issues with out of bound access in `Fc*` functions and use of uninitialized values in `PaAlsa*` functions (the later may or may not be due to bugs in PA itself). If the `Fc` functions are from a third library, the bugs could be theirs, so you may want to let them know.

**Comment by Aokromes** [comment]
I suggest you to pastebin the log to help developer more :)

**Comment by ShabbyX** [comment]
@Aokromes, I am using the released software, which is surely behind the development version. The most precise log can be achieved by running `valgrind` on the development branch of the developer(s). It doesn't require more than a minute, and it changes based on how the developer addresses them.

**Comment by Aokromes** [comment]
IF developer have a linux enviroment :P

**Comment by ShabbyX** [comment]
@Aokromes I'm pretty sure the developer who has written software using Linux libraries, compiled binaries and tested on Linux has Linux installed.
