### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Qt-Preston** [telegramdesktop/tdesktop#4980]
### Steps to reproduce
1. win10 vs2017 telegram is 1.3.10
2. 
![image_2018-07-14_10-08-01](https://user-images.githubusercontent.com/39729849/42720250-644b2cf2-8756-11e8-81b1-eada50c45f27.png)

3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Joy1024** [comment]
I  encounter the same problem!
![image](https://user-images.githubusercontent.com/3068746/42979153-6391a1e0-8c03-11e8-8a0d-a55cd1114525.png)


building env: win10 vs2017 telegram is 1.3.10

**Comment by Aokromes** [comment]
build system changed, try again on updated version.
ps. i suggest you don't use non-ascii chars for paths.
