### ISSUE TITLE
"Report Message" menu in private supergroups not consistent with mobile clients and terms of service

### ISSUE THREAD

**Issue by Remu-rin** [telegramdesktop/tdesktop#4981]
### Steps to reproduce
1. Have a private (not public) supergroup
2. Mobile clients (e.g. official one and Plus Messenger) have "report" action only in public supergroups, not private. While Tdesktop from version 1.3.0 have it in any supergroup
3. Have someone to report pornographic content in your private supergroup via Tdesktop

### Expected behaviour
1. Tdesktop shouldn't have "report" action in private supergroups, just like mobile clients
2. Private supergroups shouldn't be banned as terms of service state that pornographic content is forbidden only in public bots, groups and channels:
![image](https://user-images.githubusercontent.com/28995228/42724876-e5e9cc7c-8793-11e8-8383-f2dc3c46aa2e.png)

### Actual behaviour
Private supergroup can be banned for some users (e.g. by country or platform, though I'm not using iOS) with this message:
![image](https://user-images.githubusercontent.com/28995228/42724916-86ec415e-8794-11e8-838c-3d5dce0ffeb9.png)

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.3.10 (actually any version from 1.3.0)

**Used theme**: default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Remu-rin** [comment]
Seems like same is for private channels. Unsure what should be with bots though.
And please, fix it on server side too, to make already banned private supergroups and channels accessible again, and to make it impossible to vandals to use old version of Tdesktop (1.3.0 to current) to make harm to supergroups and channels.

**Comment by Remu-rin** [comment]
> Mobile clients (e.g. official one and Plus Messenger) have "report" action only in public supergroups, not private. 

Seems like I was misinformed or it was true for old versions?

**Comment by stek29** [comment]
- Reporting a group won't make it limited instantly
- Private groups/channels are considered public if invite links are publicly available (don't quote me on this, I'm not Telegram representative)
- > Seems like I was misinformed or it was true for old versions?
  
  It was true for old versions
- Channels/groups can be blocked on all platforms, not only on iOS. Sometimes all contents of those channels might be changed to "this channel was blocked". Sometimes blocks affect only specific countries.
- It has nothing to do with TDesktop, sorry. For further info ask Telegram on twitter or via in-app support.
