### ISSUE TITLE
telegram tray icon is blurred on session startup using linux with kde

### ISSUE THREAD

**Issue by 2295** [telegramdesktop/tdesktop#4983]
The telegram tray icon is blurred when it's automatically started at the beginning of a session.
The tray icon is not blurred if I manually start the application.
I can always reproduce this issue.

### Steps to reproduce
1. Open Telegram.
2. Close the current session.
3. Open a new session.

note: the system is configured in order to restore the previous session, that's why telegram reappears when a new session is opened. In order to activate the session restore feature: systemsettings -> startup and shutdown -> On access: restore previous session (I translated this so terms may not be identical).

### Expected behaviour
The telegram tray icon should be sharp from the start.

### Actual behaviour
The telegram icon is blurred when it's automatically started at the beginning of a session.

### Configuration
Operating system: KDE neon User Edition 5.13 x86_64

Version of Telegram Desktop: 1.3.9

Used theme: night theme

blurred:
![telegram_blurred](https://user-images.githubusercontent.com/4668449/42732617-1146af20-8825-11e8-898f-b1850fe8de1a.png)

sharp:
![telegram_sharp](https://user-images.githubusercontent.com/4668449/42732643-6254ee40-8825-11e8-83a9-a649f8f0d8a8.png)

**Comment by Aokromes** [comment]
#2230
