### ISSUE TITLE
Fullscreen issue?

### ISSUE THREAD

**Issue by mortiest** [telegramdesktop/tdesktop#4985]
I've recently updated my system from windows 8 to windows 10, and telegram started having issues when the window is maximized.

If I double click the tray icon and it starts in full screen it will fit the window okay, but if it doesn't, or if I resize and apply full scren again it will look like this:
Ok half screen: 
![image](https://user-images.githubusercontent.com/41268340/42736019-4df2fbdc-8856-11e8-97bc-40d73b09b329.png)

Not ok in full screen: 
![image](https://user-images.githubusercontent.com/41268340/42736026-619ee7e0-8856-11e8-96d2-b64005e9b008.png)

Telegram version: 1.3.10.0
Windows version: 10 Pro 1803
OS build: 17134.165

Using 4 screens all with same resolution, 1920x1080, but with different dimensions. Layout as shown in the screenshot, the app has the same behavior in any of the screens.

![image](https://user-images.githubusercontent.com/41268340/42736010-33403dae-8856-11e8-9c07-d4b56de5beda.png)

**Comment by levrik** [comment]
@mortiest @Nikovic See my latest comment in https://github.com/telegramdesktop/tdesktop/issues/4649#issuecomment-407722748
