### ISSUE TITLE
/usr/bin/xdg-mime: line 323: [: too many arguments

### ISSUE THREAD

**Issue by lindhe** [telegramdesktop/tdesktop#4986]
I get the error `/usr/bin/xdg-mime: line 323: [: too many arguments` when I open links from Telegram on my Linux system. Works just fine, but obviously something minor is broken. Looks like this:

![journalctl](https://user-images.githubusercontent.com/7773090/42736852-4eaf6062-886d-11e8-9060-a0e988d65f98.png)

I searched, and assume that something is up with the following line:

https://github.com/telegramdesktop/tdesktop/blob/b0077d98f0a620ec0755d537ed643e1a2e09dfb6/Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp#L56

Just wanted to point it out, in case you find something semi-important over there.

(I might also be misinterpreting the log message; the error might be in the `xdg-mime` application itself. If you think that is the case, feel free to close this).

**Comment by Skellington** [comment]
I think maybe the problem is on xdg-mime. I'm unable to load themes (.attheme) after solving the problem related with fontconfig, but didn't find anything in logs that point it to be a Telegram bug. I'm on Arch Linux.

**Comment by lindhe** [comment]
Let's say that is the state of things, in that case.

**Comment by john-preston** [comment]
@Skellington .attheme I think is Android Telegram Theme. Themes for Telegram Desktop have .tdesktop-theme extensions.
