### ISSUE TITLE
version number url?

### ISSUE THREAD

**Issue by lemmy04** [telegramdesktop/tdesktop#4988]
Hi, this is not an "issue" as such, I'm building rpm packages from the binary tar archives for linux, and I want to automate that as much as possible.
Is there any URL that I can fetch with curl that contains the version number of the latest release?

**Comment by john-preston** [comment]
@lemmy04 https://updates.tdesktop.com/current contains JSON with different version numbers.

**Comment by lemmy04** [comment]
json? brilliant, I'm going to automate that in ansible...

**Comment by john-preston** [comment]
@lemmy04 I guess you need result.linux.stable.released or result.linux.stable.beta (for version X.Y.Z they contain X * 1000000 + Y * 1000 + Z, first for current stable version, second for current alpha version).

**Comment by stek29** [comment]
@lemmy04 see https://gist.github.com/stek29/82818f1bab1ae95fd471d7c0813fe74f

**Comment by lemmy04** [comment]
I'll take your word for it. That's python, could just as well be chinese to me.
