### ISSUE TITLE
[Windows] Sound recorded from my mic is warped

### ISSUE THREAD

**Issue by Paramood** [telegramdesktop/tdesktop#4990]
The sound is completely unclear on interlocutor side during Telegram call. The issue is definitely on my side since all the people can't hear correct sound from my mic. Also, in other apps the mic works properly so I think it can be fixed in Telegram Desktop.

I investigated ways to workaround the issue and found out that it is reproduced if 'Enable audio enhancement' is marked in the mic settings. It was marked by default and the issue is gone after I unmarked it.

![image](https://user-images.githubusercontent.com/26360776/42762584-61e426f2-8919-11e8-89d4-45f205af5595.png)

### Configuration
**PC:**
Lenovo G510

**Operating system:**
Windows 10 Enterprise 64 bit

**Audio card:**
Conexant SmartAudio HD
Driver version: 8.66.21.50
Hardware ID: HDAUDIO\FUNC_01&VEN_14F1&DEV_5115&SUBSYS_17AAC041&REV_1001

**Version of Telegram Desktop:**
1.3.10

**Used theme**:
Night Mode

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4881 ?

**Comment by Paramood** [comment]
I think it's a completely different issue.

**Comment by xmha97** [comment]
@Paramood 
This is not a problem with the Telegram desktop
Lenovo laptop sound drivers have a problem with Windows 10.
Try this solution:
https://www.youtube.com/watch?v=vWI_Zc2kU5Q
