### ISSUE TITLE
[meta] Can't download latest 32bit Linux alpha from the official site

### ISSUE THREAD

**Issue by zeroone2numeral2** [telegramdesktop/tdesktop#4991]
### Steps to reproduce
1. Go to https://desktop.telegram.org/changelog#alpha-version
2. Try to download v1.3.10 for Linux 32bit

### Expected behaviour
TDesktop 1.3.10 is downloaded

### Actual behaviour
TDesktop 1.3.6 (latest stable release, I guess) is downloaded instead

**Comment by zeroone2numeral2** [comment]
(just tested, same thing happens with the 32bit MacOS build)

**Comment by john-preston** [comment]
@zeroone2numeral2 1.3.10 is downloaded from the main desktop.telegram.org page.

**Comment by zeroone2numeral2** [comment]
@john-preston mmm, I see. But if I go to the alpha page, the lastest stable release is downloaded instead. Nothing important, but feels a bit confusing still

**Comment by stek29** [comment]
maybe linux32 alphas just aren't built

**Comment by Aokromes** [comment]
https://i.imgur.com/W0995o3.png it downloads latest for me.
