### ISSUE TITLE
[Feature request] Hide or collapse messages

### ISSUE THREAD

**Issue by nop144d** [telegramdesktop/tdesktop#4993]
Add capability of hiding/collapsing some messages in chats that are NSFW, for example. Could be non-persistent (i.e. only run-time). Doesn't require to be synced as is mostly important on desktop.

**Comment by stek29** [comment]
See #687

**Comment by nop144d** [comment]
@stek29 Thanks for pointing to the existing request, but do agree that this is slightly different. I don't want a setting, just a right-click menu item along with reply, select, etc. or something like in tree traversal views (regedit, for example).

**Comment by stek29** [comment]
@nop144d If I considered this issue to be a duplicate, I'd close it and mark it as a duplicate.

I've just referenced related issue, that's all.

**Comment by nop144d** [comment]
Yeah I know, I just wanted to take the opportunity and explain the request better taking into account that "See #687" is not much informative to me and others you know.

**Comment by snqlby** [comment]
@stek29 
Can this be implemented by introducing a new tag?
For example, the following markdown tag will hide the message content: 
```
>! Alignment  
```
It would be really great to have something like that for channel authors who publish movie spoilers, as well as for chat users who wish to discuss them without affecting other users.

**Comment by stek29** [comment]
@snqlby that's a platform wide suggestion that needs to be discussed elsewhere.
I'd suggest to look into bots like spoilerobot.

**Comment by nop144d** [comment]
Why is it an API issue? I can't see how the API is involved here. This could be done purely by the means of the client.

**Comment by Aokromes** [comment]
imho anything NSFW must be hidden platform wide (and because we now have sensitive content thing)
