### ISSUE TITLE
[Feature request] Add 'Mark as read' button to notifications

### ISSUE THREAD

**Issue by Clevercat60** [telegramdesktop/tdesktop#4995]
Add a button to notifications for mark message as read

Like this:
![clipboarder 2018 07 17-001](https://user-images.githubusercontent.com/41125002/42841231-ac1eba88-8a1e-11e8-9534-ada13e2387c7.png)

**Comment by john-preston** [comment]
@Clevercat60 You can just send an empty reply (Reply + Enter) and it will mark as read.
