### ISSUE TITLE
[Feature request] Ctrl + k to change chat

### ISSUE THREAD

**Issue by fenandosr** [telegramdesktop/tdesktop#4996]
## Feature request

1. Use `Ctrl + k` to change chat right from your keyboard
2. Display a "modal pop up" that show a list with the chats you can change
3. Filter the list while typing. 

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by zeroone2numeral2** [comment]
You can already do the same thing with `ESC` + start typing

**Comment by stek29** [comment]
The only difference is that you can only use "up/down" and can't use tab.
