### ISSUE TITLE
Emoji replacement not working as it should

### ISSUE THREAD

**Issue by Aerozolic** [telegramdesktop/tdesktop#4997]
Hi!

I've been using Telegram app for Windows 10 for some time now and it's really annoying that it doesn't replace common emoji shortcuts like ":P", ":D", ":(" and so on.

Every other chatting app that I use recognizes those shortcuts and replaces them automatically. Even the MacOS app does it.

Could you please fix this so that using common emoji shortcuts works with Windows 10 app aswell?

Thanks.

App version is 1.3.10.

**Comment by john-preston** [comment]
@Aerozolic Maybe you have emoji replacements disabled in Settings? It replaces some, like :-D

**Comment by stek29** [comment]
@Aerozolic it's not supposed to replace `:D`.
