### ISSUE TITLE
Full-screen problems on windows 10 when I use two screens (hd and full-hd)

### ISSUE THREAD

**Issue by tva94** [telegramdesktop/tdesktop#4998]
Problem shown on next screenshot:
![-1](https://user-images.githubusercontent.com/24491769/42876877-b62b6b9e-8a90-11e8-8955-aef043cc2d07.jpg)
Also on second screen placed small part of telegram window

**Comment by d-Rickyy-b** [comment]
Duplicate of #4649
TL;DR: Windows 8 Compatibility Mode fixes this for now (don't know if/when a proper fix is on the way).

**Comment by levrik** [comment]
@tva94 @d-Rickyy-b See my latest comment in https://github.com/telegramdesktop/tdesktop/issues/4649#issuecomment-407722748

**Comment by d-Rickyy-b** [comment]
@levrik Thanks a lot :)
