### ISSUE TITLE
downloaded files are not correctly labelled

### ISSUE THREAD

**Issue by nazar2sfive** [telegramdesktop/tdesktop#4999]
I dual boot ubuntu and windows 10. Both of them store any downloaded Telegram content to same location.  Among these 6 files i have downloaded them all in windows 10. But if i open ubuntu, they are shown not to be downloaded and i need to download them again, which results in duplicate(1) files to be created again at the same download download location.
Where in telegram is information stored about the downloaded file. So that i could at least copy those files to ubuntu to make them seem downloaded.

I have around 1000s of such files. I get confused as i work between windows 10 and ubuntu.

![image](https://user-images.githubusercontent.com/12841320/42925674-a601e676-8b4e-11e8-94a4-aea6f2cfd293.png)

**Comment by john-preston** [comment]
@nazar2sfive The information is tied to the local account information, it is separate in different instances of tdesktop. Having the login information being shared between Windows and Ubuntu tdesktops was not tested ever and I doubt it will work correctly :(
