### ISSUE TITLE
Downloaded files shouldn't be flagged as trusted automatically

### ISSUE THREAD

**Issue by hugwalk** [telegramdesktop/tdesktop#5000]
From #2924
As virus can be triggered just by opening the file, they shouldn't open automaticlly right after download.

 
### Steps to reproduce
1. Download the file and wait

### Expected behaviour
Executables don't open automatically

### Actual behaviour
It opens without a warning

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.3.10 Alpha
**Used theme**:
Default

**Comment by john-preston** [comment]
@hugwalk Doesn't the system warn you when you launch such executable?

**Comment by hugwalk** [comment]
@john-preston No.

**Comment by stek29** [comment]
@john-preston see #4884

**Comment by john-preston** [comment]
🤔 I remember I've specifically applied a flag for a newly downloaded file. Perhaps the system removes it when tdesktop asks it to launch that file, but that's a strange thing to do.
