### ISSUE TITLE
[Feature Request] Add Option for Minimizing to Launcher

### ISSUE THREAD

**Issue by amxmln** [telegramdesktop/tdesktop#5004]
Many Linux distributions/desktop environments are removing the ability to have tray icons, opting instead to show a notification counter etc. directly on the app icon in the launcher / task bar / dock. For users on those platforms it would be beneficial to have an option that would minimize the application instead of closing it when exiting—similar to the existing behaviour when tray icons are available.

### Configuration
**Operating system: elementary OS**

**Version of Telegram Desktop: 1.3.10**

**Used theme: Default**

**Comment by ilya-fedin** [comment]
Why not just to pin telegram to the dock? :thinking:

**Comment by amxmln** [comment]
Because then there's no way of telling whether the application is running in the background or not.

**Comment by black-roland** [comment]
I just wanted to provide some input. There was a discussion a couple of years ago here #3830 and at least for GNOME it was recommended:

> ...to ask the user if the application should run in the background the first time it click the close button, then enable a setting with "run in the background". The user can deactivate it anytime if changes user's mind.

In the latest Telegram version, the app simply closes after clicking on [x] which is pretty annoying for me.

Also, I've just checked the behavior of Polari (IRC client developed by GNOME) and it simply goes into the background (not minimizes) when clicking [x] and provides an option to control this behavior:

![DeepinScreenshot_select-area_20200311185200](https://user-images.githubusercontent.com/1756198/76436749-a8376380-63c9-11ea-8d3c-c18da2bcc8e1.png)

**Comment by alosarjos** [comment]
I see the discussion has moved here. In my case I would like to get the functionality of running in the background without the app opened. If I would have to move through all my messaging apps when Alt+Tabbing between windows, that would be kinda bad UX IMO. I just want to have it running in the background to receive notifications without interfering with my regular PC usage.

I understand that this is nitpicking, but having Discord, Steam or Geary (For email) behaving in this way and just Telegram not is kinda weird to me.

**Comment by ilya-fedin** [comment]
You can get it now if you have tray

**Comment by alosarjos** [comment]
Yeah, but trays are really not supported on Gnome. And personally, don't really like them at all since most of the time the icons have different sizes or widths, some are monochrome, others go full color and breaks a bit the uniformity of the Shell experience.

**Comment by Aokromes** [comment]
i cannot rename https://github.com/telegramdesktop/tdesktop/issues/1161 but, generic request.
