### ISSUE TITLE
Telegram Desktop not showing images preview always

### ISSUE THREAD

**Issue by deviis** [telegramdesktop/tdesktop#5005]
Hi!

I have been researching about this behaviour a lot but I dont find a reason for this.
The problem is that telegram fails to displays the images of a link sometimes. I have a channel and I always post messages with an url like `<a href="link to imgu jpeg">some text</a>`.

Sometimes the application displays the image, other just doesnt. However, if I forward the message to any user or myself, the image loads instantly.

Is there any size/weight limits that could trigger this effect?

Apologies if this is not the place for the report!

Cheers!

**Comment by john-preston** [comment]
@deviis I'm afraid that's just a bug.

**Comment by deviis** [comment]
It was driving me crazy! I guess we just have to wait until telegram fix it, right?

**Comment by alvarofe** [comment]
Any update when this issue is going to be fixed ?

**Comment by thomich** [comment]
yeah.. i'm on Kubuntu and needed to change the render backend to XRender... as also other apps got similar problem and problem is solved... for me ;)
![selection_020](https://user-images.githubusercontent.com/4398840/43321821-571c806a-91ad-11e8-9b4d-5b4ba17c8a8d.png)

**Comment by thomich** [comment]
check also this bug report about xorg-server
https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1780664

**Comment by deviis** [comment]
I dont think it is just related to linux. I have the same problem on windows. And sometimes in the mobile version too.

**Comment by RNogales94** [comment]
I'm having the same issue, it's looks like very weird because it's look like it doesn't depend of the image but the text in the message, but it happens to in mobile version

**Comment by t1maccapp** [comment]
Same issue. If I press edit the image then shows up.

**Comment by t1maccapp** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1073 – same problem?

**Comment by Laiteux** [comment]
2.0.1 same, please fix :(

**Comment by aden16rus** [comment]
2 years have passed but not fixed,
ubuntu 20.04
telegram 2.1

first image shows after starting but next images not
if i click second time i have notification "media viewer" is ready

**Comment by wotan192** [comment]
It's still actual for me. Windows 10, 2.4.11 beta.
