### ISSUE TITLE
Going back to old pinned message makes currently uploading files disappear

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#5009]
### Steps to reproduce
1. start uploading a file
2. jump to an old pinned message
3. go back to the uploading file

### Expected behaviour
You can still see the file being uploaded

### Actual behaviour
Uploading file disappears, and comes back only when the upload is completed

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.4.8 portable

**Used theme**: default dark

**Comment by mohammad6006** [comment]
same problem version 1.5.15

when I search and go to old message uploading file disappears

**Comment by VHrishikesh** [comment]
In 1.6.4 beta, still the same.

**Comment by john-preston** [comment]
@VHrishikesh Yes, currently they're added only locally and if the chat part is completely replaced (for example if you jump to some old message) then on return back a slice of messages from server will be shown, without the locally created message.

**Comment by VHrishikesh** [comment]
@john-preston So, is it always going to remain like that or is some solution or workaround? If not soon, is there a possiblity that this can be fixed?

**Comment by RememberTheAir** [comment]
Yes, still happening

**Comment by RememberTheAir** [comment]
Can reproduce on 2.7.1

**Comment by RememberTheAir** [comment]
Still an issue on 3.7

**Comment by RememberTheAir** [comment]
Can reproduce on 4.2.4

**Comment by RememberTheAir** [comment]
unstale

**Comment by RememberTheAir** [comment]
yes still happening
