### ISSUE TITLE
[Linux] Weird cursor's styles

### ISSUE THREAD

**Issue by gurland** [telegramdesktop/tdesktop#5010]
### Steps to reproduce
1. Launch Telegram desktop on Ubuntu

### Expected behaviour
I'm expecting for default cursor style (white cursor, normal pointer style, white resizing cursor)
### Actual behaviour
<details>
 <summary>Photos of my new cursor</summary>

![default](https://user-images.githubusercontent.com/30530987/43135420-08d35a16-8f4e-11e8-917a-0e2eeb187d01.png)
![default](https://user-images.githubusercontent.com/30530987/43135429-0e575cee-8f4e-11e8-93f7-8663f98706d2.png)

</details>

### Configuration
**Operating system:**
Ubuntu 17.04
**Version of Telegram Desktop:**
1.3.10
**Used theme**:
Default with enabled night mode

**Comment by Aokromes** [comment]
this bug is still valid using official and not some distribution package?

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Comment by erebus-oneiros** [comment]
This issue is still present. Looking online on different linux forums confirms this. The Snap and Flatpack versions have this weird cursor styles but the .deb or the repository version doesn't.

Another weird behavior: the pointer shows up as the system's default version in screenshots.
