### ISSUE TITLE
Messages marked as read if receiver's window is active

### ISSUE THREAD

**Issue by OSjerick** [telegramdesktop/tdesktop#5011]
I'm not sure if this is actually an issue, but this behavior seems incorrect, with other messaging apps it doesn't happen.

### Steps to reproduce
1. Send a message.

### Expected behaviour
The message should be marked as read if there is activity in the receiver's chat.

### Actual behaviour
If the receiver goes away for a  little and lets the app window active and the chat is active as well the message will be marked as read.

### Configuration
**Operating system:** Windows 7 on the sender, Xubuntu 18.04 on the receiver.

**Version of Telegram Desktop:** 1.3.10 in both sides.

**Comment by MetalDroid** [comment]
[https://github.com/telegramdesktop/tdesktop/issues/4664](url)
