### ISSUE TITLE
Telegram Desktop won't launch on Manjaro Deepin

### ISSUE THREAD

**Issue by Mr-13** [telegramdesktop/tdesktop#5012]
### Steps to reproduce
1. update telegram-desktop to version 1.3.10-1
2. run it from terminal
3.  that's all it says QApplication: invalid style override passed, ignoring it. and stuck.

### Expected behaviour
it normally launches telegram-desktop application.

### Actual behaviour
giving this error:
QApplication: invalid style override passed, ignoring it.

### Configuration
Distribution: ManjaroLinux
Release: 17.1.11
Desktop Environment: Deepin 15.6
Type: 64 bit

**Version of Telegram Desktop:**
1.3.10-1
**Used theme**: 
Deepin(default)

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
What about the version from https://desktop.telegram.org?

**Comment by Mr-13** [comment]
same results

**Comment by john-preston** [comment]
@Mr-13 Do you remember what version was working on your system? (if any)

**Comment by Mr-13** [comment]
1.12.x (x i don't know exactly). now i have some extra details too : 
i cleaned up .local/share/TelegramDesktop/tdata/
now i am able to launch telegram-desktop from terminal but not from .desktop file i.e from launcher 
content of .desktop file
[mr13@deepin ~]$ cat /usr/share/applications/telegramdesktop.desktop 
[Desktop Entry]
Version=1.0
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
Exec=telegram-desktop -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;

**Comment by john-preston** [comment]
@Mr-13 Perhaps this desktop file launches not the version that you've downloaded from https://desktop.telegram.org, but some "telegram-desktop" binary from somewhere?

**Comment by Mr-13** [comment]
i uninstalled every other version and cleaned all cache then setup from the version  from https://desktop.telegram.org created a new .desktop file and telegram-desktop.

**Comment by Aokromes** [comment]
Tried myself with the live cd under one vm and worked for me.
https://i.imgur.com/jvSImZT.png

**Comment by Mr-13** [comment]
@Aokromes looks like you tried on kde. please try on deepin.

**Comment by TheRishka** [comment]
Same issue for me. However, running telegram-desktop under root works.
Running with `QT_QPA_PLATFORMTHEME="" QT_STYLE_OVERRIDE=""` didn't work.
Using any other versions (from official web-site, from binaries) doesn't work as well.

**Comment by Aokromes** [comment]
#4324

**Comment by skverno** [comment]
Same issue for me. 
Manjaro Gnome.
telegram desktop - 1.5.15
Launch from terminal QApplication: invalid style override passed, ignoring it.
    Available styles: bb10dark, bb10bright, kvantum-dark, kvantum, cleanlooks, gtk2, cde, motif, plastique, qt5ct-style, Windows, Fusion

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
