### ISSUE TITLE
error: ‘deduced_call_type’ in namespace ‘crl’ does not name a template type

### ISSUE THREAD

**Issue by fl0at88** [telegramdesktop/tdesktop#5015]
Telegram/SourceFiles/mtproto/rpc_sender.h:982:27: 
error: ‘deduced_call_type’ in namespace ‘crl’ does not name a template type

template <
	typename Lambda,
	typename Function = crl::deduced_call_type<Lambda>>

**Comment by cranes-bill** [comment]
See #4978
