### ISSUE TITLE
[MacOS] Special char input method (emojis) not working

### ISSUE THREAD

**Issue by ManuelSchneid3r** [telegramdesktop/tdesktop#5018]
#3966 would not be as severe to me if the MacOS special char input method was working. 
<kbd>ctrl</kbd>+<kbd>cmd</kbd>+<kbd>space</kbd> usually opens this dialog:

<img width="354" alt="bildschirmfoto 2018-07-27 um 11 58 03" src="https://user-images.githubusercontent.com/3252315/43314795-58c4ec2c-9194-11e8-9e4f-c45c937a03fb.png">

However when telegram (input line in chat window) has focus and I hit the key combo, this input method does _not_ show up.

**Comment by stek29** [comment]
#2886
