### ISSUE TITLE
Uploading files not showing after search in chat

### ISSUE THREAD

**Issue by rad96** [telegramdesktop/tdesktop#5019]
### Steps to reproduce
1. Open Favorites chat
2. Start uplading any file (bigger than 20mb prefered)
3. Press Ctrl - F
4. Search something what was send far in past
5. Select any search result
6. Tap at "Go down" arrow at right bottom corner

### Expected behaviour
Progress of file uploading

### Actual behaviour
Progress of file uploading is not displaying
After it completes - file apperars in Chat

### Configuration
**Operating system:**
Windows 7

**Version of Telegram Desktop:**
1.3.10

**Used theme**:
default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

**Comment by stek29** [comment]
I think it's #5009
