### ISSUE TITLE
[Feature request] Presence awareness

### ISSUE THREAD

**Issue by gtirloni** [telegramdesktop/tdesktop#502]
Right now Telegram's behavior regarding where notifications for new messages should appear seems inconsistent. I've Telegram runninng on WP8 and Windows 8.1 and notifications sometimes appear on the phone, sometimes on Windows. I noticed that, if the desktop window does not have focus, it will also notify the phone. Ideally, it should show a desktop notification and/or bring the desktop window to focus (if configured by the user). I would like to receive notifications on the phone only when I'm logged out of the desktop and/or the screen is locked. Of course, I would like all messages to be in all devices, just not all the notification everywhere.

This is something Skype was struggling in the past and with the recent updates they seem to have gotten it right. I'm only mentioning this as it might be a good example of an already worked out mechanism.

**Comment by nmat** [comment]
+1

**Comment by Aokromes** [comment]
#277
