### ISSUE TITLE
X11 Session Management not implemented corretly

### ISSUE THREAD

**Issue by henning-schild** [telegramdesktop/tdesktop#5022]
### Steps to reproduce
1.  on Linux plasma/kde5 start "telegram-desktop -externalupdater"
2.  log out of plasma and log in again
3.  now telegram-desktop will be running with "-session XXXX" and did not remember to disable the internal updater

### Expected behaviour
telegram desktop should not restart at all, or it should restart with the settings it had when it was stopped

### Actual behaviour
Telegram seems to register with the session manager and request to get restarted, but after restart the internal updater will be enabled again.
This partial session management implementation might also be the cause for other problems (maybe #1059 )

### Configuration
**Operating system:**
Linux with Plasma Desktop
**Version of Telegram Desktop:**
1.3.10

### additional information
telegram desktop should not participate in session management at all, or it should support the whole protocol. It should i.e. set its "RestartCommand" to tell the session manager how to restart it without lossing arguments.
http://doc.qt.io/qt-5/session.html
http://doc.qt.io/qt-5/qsessionmanager.html#setRestartCommand
https://en.wikipedia.org/wiki/X_session_manager

**Comment by john-preston** [comment]
@henning-schild Do you try Telegram Desktop from https://desktop.telegram.org? I can't find anything about participating in session management in my source code, perhaps I've forgot already that I did it somewhere by accident.

**Comment by henning-schild** [comment]
That might be coming from Qt, maybe something you set to enable autostart when tdesktop was last running. Just try the "xsm" steps described in the first link to doc.qt.io, you will find telegram in the ClientList and the RestartCommand will be missing all extra arguments in case you started it with any arguments like `-externalupdater` .
I guess the final goal should be to not appear in this list anymore, would stop the auto(re)start feature. Or to implement the protocol correctly and remember the state. i.e. by adding all command line arguments to RestartCommand

**Comment by john-preston** [comment]
@henning-schild What auto(re)start? I don't remember adding anything about auto(re)start on Linux in my code :( Is it possible that all Qt apps by default use this until you switch it off explicitly?

**Comment by henning-schild** [comment]
I do not know where it is coming from, i am just reporting the current situation. Maybe you have to turn it off in Qt, or some call turns it on for some reason.

Without the ability to rebuild against a regular Qt i also do not see how i could look deeper into that without wasting time. So my contributions will be issues instead of PRs.

**Comment by john-preston** [comment]
@henning-schild Ok, thanks.

**Comment by henning-schild** [comment]
I guess you can unset SESSION_MANAGER before creating the QtGuiApplication or compile your Qt with QT_NO_SESSIONMANAGER.
http://code.qt.io/cgit/qt/qt.git/tree/src/gui/kernel/qapplication_x11.cpp#n5889
http://code.qt.io/cgit/qt/qt.git/tree/src/gui/kernel/qapplication.cpp#n1002

**Comment by henning-schild** [comment]
Or implement the few missing functions and have telegram start automatically on all Linux systems that had it running before i.e. reboot. I think that would be the best solution, but is more work.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by henning-schild** [comment]
I could not reproduce it just now. But since there never was an update here or commit linked to the issue i have no reason to believe it is gone. @Aokromes Do you, and why do you ask?

**Comment by Aokromes** [comment]
i am trying to clean the tracker of old issues :) also, sometimes preston forgets to link bugfixes with issues.

**Comment by henning-schild** [comment]
Closing because i can not reproduce it anymore.
