### ISSUE TITLE
Telegram Desktop is not showing images in channel sometimes

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#5023]
screenshot below taken at the same time from different accounts and two copies of program
both connected through same proxy
relaunch telegram desktop solves problem
i can't reproduce this, it happens occasionally

1.3.10 alpha
win 10 x64 1709
![2018-07-28 18_06_55-](https://user-images.githubusercontent.com/10371194/43358121-51473250-9295-11e8-9253-471ca0c07b8f.png)

**Comment by Aokromes** [comment]
i think this is server bug.
