### ISSUE TITLE
[Feature Request] Quiet startup

### ISSUE THREAD

**Issue by conkeating** [telegramdesktop/tdesktop#5024]
It would be nice if a quiet startup option were added so that the app can be added to the list of start-up applications but instead of opening a window remains minimized to the system tray.

**Comment by stek29** [comment]
There's start in tray option on Windows, command line argument on Linux and a feature request for macOS.

What OS are you talking about?

**Comment by conkeating** [comment]
Ah, I wasn't aware of that. I'm using the Flatpak version of the app on Arch Linux. What option should I be passing to that then?

**Comment by stek29** [comment]
Try `-startintray`, but I'm not sure it'd work well (might cause some glitches with invisible window)
