### ISSUE TITLE
how to manage tdata directory?

### ISSUE THREAD

**Issue by smaznet** [telegramdesktop/tdesktop#5025]
Hi
why this directory size is so big !?
~/.local/share/TelegramDesktop/tdata

![image](https://user-images.githubusercontent.com/10239885/43358545-0876f2d6-92a9-11e8-82fc-b4cd857a73fd.png)

### Configuration
**Operating system:** Ubuntu 18.04

**Version of Telegram Desktop:** 1.3.10

**Used theme**: Dark

**Comment by john-preston** [comment]
@smaznet Unmanaged local cache for media :( you can relogin or even logout and delete this folder manually then login again.

I try to come up with a better local cache management right now, but this won't be very soon.

**Comment by JohnFinn** [comment]
Shouldn't be this directory located somewhere in `~/.cache` instead?
