### ISSUE TITLE
How autoupdate without root is possible?

### ISSUE THREAD

**Issue by hongquan** [telegramdesktop/tdesktop#5026]
This is just a question.
I installed Telegram to _/opt/_. When Telegram informs that new update available, I just click the button and Telegram get updated.
I wonder where it write the new update to, given that _/opt/_ folder requires root permission to write!

**Comment by stek29** [comment]
Isn't it saved as /opt/telegram/Telegram? Do `sudo chown $(id -u) /opt/telegram` then

**Comment by hongquan** [comment]
Oh, I thought that the files under _/opt/telegram/_ are owned by _root_. But I have just checked and they are actually owned by my user. Ok, now I understand why Telegram can update itself.

(I installed Telegram by unzipping _tsdesktop.tar.xz_ and move the files to _/opt/_. I thought that `sudo mv` will put the files under _root_, but it is actually not the case.)
