### ISSUE TITLE
[Linux] The GUI does not open under Linux Manjaro

### ISSUE THREAD

**Issue by ElJulio** [telegramdesktop/tdesktop#5027]
### Steps to reproduce
1. Start telegram-desktop as normal user

### Expected behaviour
The GUI should open

### Actual behaviour
The GUI doesn't open
but there running two telegram processes in the background 

running telegram desktop from the command line shows:

(telegram-desktop:3682): Gtk-WARNING **: 11:23:37.970: Unable to locate theme engine in module_path: "murrine",

(telegram-desktop:3682): Gtk-WARNING **: 11:23:37.971: Unable to locate theme engine in module_path: "murrine",

(telegram-desktop:3682): Gtk-WARNING **: 11:23:37.972: Unable to locate theme engine in module_path: "murrine",
QApplication: invalid style override passed, ignoring it.

### Configuration
Linux 4.14.57-1-MANJARO #1 SMP PREEMPT Sun Jul 22 19:25:51 UTC 2018 x86_64 GNU/Linux

1.3.10-1

### Workaround
When running it as root every thing worked fine.
These  messages appear on the command line:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QApplication: invalid style override passed, ignoring it.

**Comment by Aokromes** [comment]
#5012
