### ISSUE TITLE
Open URL tg Porotocol

### ISSUE THREAD

**Issue by almas3s** [telegramdesktop/tdesktop#5029]
hi. i created a app for windows with login telegram passport.
but if on a OS (windows) user use of many TDesktop and TDesktop Portable how i can open desired telegram (select by user) 

this is my code. in C# :
` Process.Start(new ProcessStartInfo("tg://resolve?domain=...."));`

and in my system Installed TDesktop and in my drive d exist many TDesktop Portable, but this code opening a random of this TDesktops

**Comment by stek29** [comment]
Do t.me links work?

**Comment by hamed-ehtesham** [comment]
i had this problem before too,
this file will help you to change tg protocol association to desired location,
change locations in the file

[telegram reset protocol association.zip](https://github.com/telegramdesktop/tdesktop/files/2240568/telegram.reset.protocol.association.zip)
