### ISSUE TITLE
[Bug] Mobile notifications sometimes fail to clear when viewed on desktop

### ISSUE THREAD

**Issue by joshery420** [telegramdesktop/tdesktop#503]
When using the [Telegram desktop application](https://desktop.telegram.org/) on Windows 7 (work) and 8.1 (home) I occasionally notice that my Telegram notifications on my mobile devices won't react to me viewing messages on the desktop.

That is to say that I won't have the desktop app nor the mobile apps focused when I receive a message, thus receiving a notification on each device/system. When I view the message on my computer, sometimes the mobile devices fail to clear the associated notification.

It's not consistent, since very often it certainly does clear it (super quickly, in fact), but it seems to be that if it fails to clear it immediately it won't eventually correct itself and clear the notification, instead just remaining in my notification shade until I open the app myself.

For the record, I'm referring to notifications on both my Nexus 5 (Android 5.0.1) and my Nexus 7 2013 (5.0.2), regardless of whether or not I'm on work or home WiFi or mobile data.

**Comment by ppparadox** [comment]
+1
