### ISSUE TITLE
high cpu usage on osx 10.12.6

### ISSUE THREAD

**Issue by vanyakosmos** [telegramdesktop/tdesktop#5030]
### Steps to reproduce
1. open telegram
2. browse some meme channel with many media files
3. this is it

### Expected behaviour
Everything work flawlessly 

### Actual behaviour
cooler on my laptop tried to launch it into space

### Configuration
**Operating system:** osx 10.12.6

**Version of Telegram Desktop:** 1.3.10

**Used theme**: dark one

cpu usage jumps from 20 to 100%

<img width="249" alt="screen shot 2018-07-28 at 00 15 28" src="https://user-images.githubusercontent.com/16745500/43370410-42e4e14c-9387-11e8-8f75-5ae3460edc82.png">

**Comment by dfmabbas** [comment]
I also have this problem.
When the Internet is being discontinued for a while, the telegram is using the CPU heavily.

**OS: 10.13.6
Telegram: 1.3.10**

**Comment by riseremi** [comment]
Same here. 

OS: 10.13.3
Telegram: 1.2.6

**Comment by Aokromes** [comment]
#4559 ?
