### ISSUE TITLE
Incorrect copying of link

### ISSUE THREAD

**Issue by vSonne** [telegramdesktop/tdesktop#5032]
### Steps to reproduce
1. Send message when its part is a link
2. Select part of message with link
3. Paste text in new message

### Expected behaviour
Text pasted with integrated link

### Actual behaviour
URL is pasted after link. If link was an end of selected part of message link is not inserted.

### Configuration
**Operating system:**
Windows 7
**Version of Telegram Desktop:**
1.3.10 alpha
**Used theme**:
Dark
<details><summary><b>Logs</b>:</summary>

</details>

**Comment by stek29** [comment]
can you record a video? I can't understand it...

**Comment by vSonne** [comment]
Sure.
[bandicam 2018-07-31 22-08-39-893.zip](https://github.com/telegramdesktop/tdesktop/files/2246763/bandicam.2018-07-31.22-08-39-893.zip)

**Comment by stek29** [comment]
#4751
