### ISSUE TITLE
Messages order isn't kept in some occasions

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#5033]
### Steps to reproduce
1.  Telegram was now down for a bit (at least in Israel)
2.  I sent two text messages in a chat, and then saw it wasn't sent
3. After sometime, Telegram was back and the messages were sent in the opposite order

### Expected behaviour
The messages will be sent at the same order, even if the system was unavailable.

### Actual behaviour
I sent:

    x
    y

Friend received:

    y
    x

### Configuration
**Operating system:** Windows 10, 1803
**Version of Telegram Desktop:** 1.3.10 alpha

**Comment by arieljannai** [comment]
Example that happened to me just now, on a slow connection:

![image](https://user-images.githubusercontent.com/3811594/46532910-24df1d80-c879-11e8-8aee-c2636c077aa5.png)

![image](https://user-images.githubusercontent.com/3811594/46532970-59eb7000-c879-11e8-84cc-392a5a560b75.png)

**Comment by john-preston** [comment]
@arieljannai Yeah, this can happen.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2797
