### ISSUE TITLE
Saved messages bug

### ISSUE THREAD

**Issue by iDavidef** [telegramdesktop/tdesktop#5034]
### Steps to reproduce
1. Forward an inline message from a group or a private chat to saved messages

Independently to window size, you will get this bug

### Actual behaviour
![immagine](https://user-images.githubusercontent.com/15069964/43429799-cbe801a2-9465-11e8-9b5a-c26732a0b332.png)
![immagine](https://user-images.githubusercontent.com/15069964/43429827-fedf0704-9465-11e8-9e1a-8e2bac965232.png)

### Expected behaviour
![immagine](https://user-images.githubusercontent.com/15069964/43429831-0a09e5fe-9466-11e8-945d-852913a07b24.png)

### Configuration
**Operating system:** Windows 10 Build 1803 17134.165
**Version of Telegram Desktop:** 1.3.10

**Comment by john-preston** [comment]
I can't reproduce that :(

Can you place a step-by-step instruction? I tried:

0. Launch Telegram Desktop with a default window size.
1. Open supergroup.
2. Write "@xobot " in the input field.
3. Send "X" from the inline results.
4. Right click the message with "❌ John 👈\n⭕️ ?" text and choose "Forward message".
5. Choose "Saved messages" and see "Done!" toast message.
6. Open "Saved messages".

It looks fine there:

![image](https://user-images.githubusercontent.com/17900494/43525460-7fdb6902-95aa-11e8-8d0d-db6593bc38e8.png)
