### ISSUE TITLE
Theme Editor - Description disappearing by adding new entrys

### ISSUE THREAD

**Issue by BlackRedDead** [telegramdesktop/tdesktop#5037]
### The Problem
When changing Entry's in the Editor that are not part of the ".tdesktop-palette" file, then theire description in the editor gets deleted.

### Steps to reproduce
1. Edit Theme
2. Look for an Entry at the bottom that is saying to be not part of the palette yet
3. Edit it & save to add it to the palette
4a. If you found that entry via search for a keyword in it's description then it disappears from the current search
4b. If not you can't see the description anymore

### Actual Workaround
1. Export Theme
2. Reload Theme
idk why, but then those Descriptions are added

### Expected behaviour
It should still display the discription and be searchable for it.

### Actual behaviour
Description disappears and we have an entry with no description now - that possibly is lost if you can't remember a part of the name or colorcode you entered.

### Configuration
**Operating system:**
Win10
**Version of Telegram Desktop:**
1.3.10
**Used theme**:
Custom, based on default Nightmode
(error happens even befor i changed any text colors!)

**Comment by BlackRedDead** [comment]
well, should be clear that it's regarding the desktop client and not the app! :-)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
