### ISSUE TITLE
Theme Editor - Strange CC value changings

### ISSUE THREAD

**Issue by BlackRedDead** [telegramdesktop/tdesktop#5043]
### Steps to reproduce
A bit difficult, as it happens only on some Entrys!
I bring a small example:
1. Search for the "dialogsVerifiedIconBgOver"
2. Edit it with #f3b600...
3. ...wich gets changed to #f3b200
When it happens the difference is indeed only in a small digit range, so unnoticeable for the end-user - but especially at darker colors it is pretty obvious and anoying if you have attached surfaces!

Another very strange example:
`attentionButtonBgOver`
when i type in _#f37**9**0064_ it changes to _#f37**5**0064_, but when i type in _#f37**a**0064_ it changes to the desired value of _#f37**9**0064_ - what the hell is wrong with this editor?! o.O

### Expected behaviour
It should just take my colorcodes as is and not mess with them!
or explain itself to the user why they change and in wich system codes considered valid!

### Actual behaviour
At some Entrys it changes the entered colorcodes, while on others it works just fine.
I haven't figured out a pattern, but on the entrys where it happen it always happen and it seems to have a system behind it - maybe it's intentional but then i would like to know why and how it works so i can match my colors to it!

### Configuration
**Operating system:**
win10
**Version of Telegram Desktop:**
1.3.10
**Used theme**:
Custom - based on default Nightmode

**Comment by john-preston** [comment]
@BlackRedDead Thanks for the report. This is how edit color box currently works — when it is opened it sets hue/saturation/brightness values and then updates current color from them.

This transformation (rgb -> hsv -> rgb) is not lossless and some values are screwed :(

I'll improve this for the next version, it'll always start and end with rgb and deal with hsv only if you change some of them.

**Comment by BlackRedDead** [comment]
Ah okay, well, as the result is pretty small and in effect neglible - it isn't such important, just anoying!
But nice if it gets fixed, as i use my own values not only to match them better and make a unique looking skin but also to identify myself as the Author!

But thank you for the explaination, that's why i prefer to work with exact RGB/Hex values rather than HSV.

**Comment by john-preston** [comment]
@BlackRedDead The fix is already available in the latest alpha version.

You can download it from https://desktop.telegram.org/changelog#alpha-version

**Comment by BlackRedDead** [comment]
Installed, thx :-)
