### ISSUE TITLE
Client doesn't parse HTML headers of SPAs

### ISSUE THREAD

**Issue by blackst0ne** [telegramdesktop/tdesktop#5045]
### Steps to reproduce

1. Send a message with a link to a single page application in it. E.g. `https://tiddlywiki.com/` 
2. See no HTML headers/description were parsed and shown

### Expected behaviour

HTML headers/description should be shown

### Actual behaviour

No HTML headers/description are shown

### Configuration
**Operating system:** Linux Ubuntu 16.04 LTS

**Version of Telegram Desktop:**  1.3.9

**Used theme**: default

**Comment by stek29** [comment]
Previews are generated on server side.

Also, how do you expect those to be parsed? There are no meta tags, what should be in preview?

**Comment by stek29** [comment]
I doubt that'd ever happen, but feel free to request it on Twitter or via in-app support.
