### ISSUE TITLE
CATEGORY --- TAGS --- CATEGORY --- TAGS --- CATEGORY -- NOW!!!

### ISSUE THREAD

**Issue by Mateusresende** [telegramdesktop/tdesktop#5047]
###**And seriously, it places category, tag,**

and it's hard to stay up all the time organizing the contact agenda.
You lose a lot of time, and we still forget people, because you get thrown back there.
And I have to write down the names on the wall.

**Comment by Mateusresende** [comment]
Why do not you do that?
Why are you taking away what you had in ICQ, MSN, FACEBOOK and then it was taken from facebook and taken from other recent platforms?

This has made our communication much more dispersed.

**Comment by stek29** [comment]
I know, I also want this, but I don't want useless duplicate issues. Sorry.
