### ISSUE TITLE
Disposition of images album changes bug

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [telegramdesktop/tdesktop#5049]
When I make album 10 foto to chanel. I select each foto on spetial place on view. On preview I see 3 fotos on top. After publishing I see 2 fotos on top, and all 2-dimentional sort order breakes.

I am a disigner and It is really matter of sort order. All desing project of selecting each foto each place breakes after changing order on just 1 foto.

**Comment by john-preston** [comment]
@Dmitrij-Polyanin It should not change. Can you provide full example (all of the photos in the album) so I could reproduce that issue?

**Comment by Dmitrij-Polyanin** [comment]
I selected positions.

![2018-08-03_11-47-16](https://user-images.githubusercontent.com/10674646/43633848-24b67214-9713-11e8-9d9d-95556a9e8241.png)

After publish.

![2018-08-03_11-47-43](https://user-images.githubusercontent.com/10674646/43633862-346ffc0c-9713-11e8-9959-5390b9ad8349.png)
![2018-08-03_11-47-51](https://user-images.githubusercontent.com/10674646/43633867-3863e864-9713-11e8-8f64-45fe1e5c3fef.png)

Here is images files - https://yadi.sk/d/54gUQPhs3ZrjqG

**Comment by john-preston** [comment]
@Dmitrij-Polyanin Thanks. I'll adjust the way the album preview is shown before sending to match the one that will be after the album is sent.

**Comment by Dmitrij-Polyanin** [comment]
Mabe I misunderstand you, my english is not perfect.
Is not this is a half of the solution? Its good to see preview, but why not to do just equal positions on when editing and on posting?

**Comment by john-preston** [comment]
@Dmitrij-Polyanin I fixed the album preview that you used so that it will display the same layout that will be when the album will be sent. All Telegram applications (try to) display albums the same way, so now the album preview before sending should show them the same way.
