### ISSUE TITLE
[Bug] Client can't show ( ͡° ͜ʖ ͡°) lenny face

### ISSUE THREAD

**Issue by razpeitia** [telegramdesktop/tdesktop#505]
What I see when I'm typing:
![captura](https://cloud.githubusercontent.com/assets/50978/6312029/79c1fba6-b932-11e4-9967-ef9fc721fcda.PNG)

What I got when the message is sent.
![captura2](https://cloud.githubusercontent.com/assets/50978/6312042/9ac93dd2-b932-11e4-9de9-bcd9123df10f.PNG)

**Comment by MBosco-** [comment]
+1

**Comment by chuckbutler** [comment]
+1

**Comment by JordanGrace** [comment]
+1

**Comment by luiseduardohdbackup** [comment]
+1

**Comment by joshery420** [comment]
+1

**Comment by ciuff** [comment]
+1

**Comment by tvararu** [comment]
+1

**Comment by v3xx3d** [comment]
+1 ( ͡° ͜ʖ ͡°)

**Comment by Dark-Mind** [comment]
+1

**Comment by lPinchol** [comment]
+1

**Comment by zack6849** [comment]
+1

**Comment by Carlangueitor** [comment]
+1

**Comment by JuanPotato** [comment]
+1 ( ͡° ͜ʖ ͡°)

**Comment by telegramdesktop** [comment]
0.7.20 shows (at least in Windows)

**Comment by razpeitia** [comment]
It doesn't show in Yosemite :disappointed:

**Comment by Carlangueitor** [comment]
Yosemite: 
![notlennyface](https://cloud.githubusercontent.com/assets/852555/6645362/958d60b4-c981-11e4-8f96-d39acbae801d.png)

**Comment by joshery420** [comment]
@telegramdesktop this should probably be re-opened since it's not fixed across all platforms.

**Comment by Eiamnacken** [comment]
got the same no mouth opensuse KDE 13.2. The rest of the face works fine

**Comment by ilovepjs** [comment]
+1

**Comment by Moter8** [comment]
:+1: `+1` +1

**Comment by 0x535431** [comment]
+1
For the love of all that's good and holy. We are living in SIN until we get this fixed.
