### ISSUE TITLE
Search bar loses focus immediately after click on "search for messages" menu item when user/group/channel is selected

### ISSUE THREAD

**Issue by diegolagoglez** [telegramdesktop/tdesktop#5051]
### Steps to reproduce
1. Open Telegram Desktop.
2. Left click on a user/group/channel to select it.
3. Right click on the same user/group/channel.
4. Choose "search for messages" menu item.

### Expected behaviour
Search bar should maintain keyboard focus.

### Actual behaviour
Search bar gains keyboard focus and loses it immediately.

### Notes
This behavior doesn't happen if just after open Telegram user right clicks (no left click to select the user/group/channel) and select "search for messages" menu item.

### Configuration
* Ubuntu 16.04 i386 and amd64.
* Telegram Desktop 1.3.10.
* Theme: default.

**Comment by john-preston** [comment]
@diegolagoglez Thanks for the report! Please check the latest 1.3.11 alpha version from https://desktop.telegram.org/changelog#alpha-version

**Comment by diegolagoglez** [comment]
@john-preston Yeah! It works on 1.3.11 alpha. Thanks very much!
