### ISSUE TITLE
Notifications get focus

### ISSUE THREAD

**Issue by Lonami** [telegramdesktop/tdesktop#5052]
### Steps to reproduce
1. Receive a notification.
2. No matter what input had focus, whether the input field in the app or any other, it's lost. The focus is now in the notification, so whatever you were typing simply stops you.

### Expected behaviour
The input field should *not* lose focus! It's extremely annoying.

### Actual behaviour
The input field loses focus.

### Configuration
**Operating system:** Arch Linux x86_64 Linux 4.14.56-1-lts, XFCE4.
**Version of Telegram Desktop:** 1.3.11 alpha.
**Used theme**: Siinde, the best theme.

**Comment by Ristovski** [comment]
Can confirm, this is even more annoying when using a tiling window manager under Linux, as this will steal focus across all workspaces.

**Comment by Lonami** [comment]
Thank you so much.
