### ISSUE TITLE
[Feature Request] Мake full mute.

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [telegramdesktop/tdesktop#5053]
I joined some channels with really big activity mabe 2 posts in a minute. And in Telegram I see numer of new posts run up quickly. It is usless information, because I already know that this group has big activity... And it is bad to see all this bages over time. And even i mute this chat I retheaved gray badges. But they are bad too.

Some ideas how to solve it.

1. Make full mute of group or chanel not to reseave even gray badges.
2. Make contact groups with ability to full mute whole group
3. Make a list of full disabled chats and chanels, like archive or temporary, it will be usefull because I want to have some contacts but not in main list.

**Comment by stek29** [comment]
There's an option in settings to only count unmuted chats on badge.
