### ISSUE TITLE
Message placement are not the same in function of the window "state".

### ISSUE THREAD

**Issue by skid9000** [telegramdesktop/tdesktop#5055]
### Steps to reproduce
1. Open TDesktop on Windows.
2. Open any random chat

### Expected behaviour

When the app is "reduced", the messages are placed like this :

![](https://puush.tuto-craft.com/8f9q0k.jpg)

Your messages on the right and the others on the left.
It should be the same when you max the window.

### Actual behaviour

When you maximized the window, all the messages are on the left ...

![](https://puush.tuto-craft.com/005K2L.jpg)

### Configuration
**Operating system:** Windows 8.1

**Version of Telegram Desktop:** 1.3.10

**Used theme**: Default ?

**Comment by stek29** [comment]
open settings
