### ISSUE TITLE
Ubuntu Snap 251 - QXcbConnection: Could not connect to display :0

### ISSUE THREAD

**Issue by jejo86** [telegramdesktop/tdesktop#5057]
On Ubuntu 18.04 I get an [error](https://github.com/telegramdesktop/tdesktop/files/2259632/TelegramError.txt) when trying to start the latest [ubuntu snap version](https://github.com/telegramdesktop/tdesktop/files/2259633/TelegramVersion.txt)
of telegram-desktop.
Manually creating the folders still throws the [error](https://github.com/telegramdesktop/tdesktop/files/2259634/TelegramErrorAfterCreatedFolders.txt) about the connection to the _display :0_.

I had to revert 
`sudo snap revert telegram-desktop`
to the previous version 233. That one worked immediately.

**Comment by stek29** [comment]
Report it to snap maintainers :)
