### ISSUE TITLE
Group notifications are disabled by themselves

### ISSUE THREAD

**Issue by dobcrypto** [telegramdesktop/tdesktop#5058]
### Steps to reproduce
1. Enable notifications in group 1.
2. New message notification in the group 1. I went in, read, went to another group.
3. Group 1 notifications are disabled by themselves =(
4. Enable notifications in group 1 again. And so on a circle. 
Not in all groups, which is strange.

### Expected behaviour
Group notifications should not be disabled by themselves.

### Actual behaviour
Group notifications are disabled by themselves.

### Configuration
**Operating system: Win 7 x64**

**Version of Telegram Desktop: v 1.3.12**

**Used theme**: Day

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by dobcrypto** [comment]
It seems that the error passed itself.

**Comment by stek29** [comment]
Feel free to report if it comes back.
