### ISSUE TITLE
Portable/relative download path

### ISSUE THREAD

**Issue by QGkjTIYUCw** [telegramdesktop/tdesktop#5059]
Hello.

Now in the settings you can specify only the absolute path for **download path**. When you move the folder containing **Telegram**, this path does not change.

But in the **portable version** there should be an option to specify a path that would start from the place where **telegram.exe** is located. Paths tied to the location of the program are a characteristic feature of **portable** programs.

Now **download path** looks like this (for example):
`F:\Telegram\Download`

In the **portable version** **download path** should look like this (for example):
`.\Download`
or `%TELEGRAM_DIR%\Download`

Thank you.

Telegram portable 1.3.10
Windows XP SP3 (32 bit)

**Comment by oqbnaslyxt** [comment]
I believe that it is necessary to give to the user an opportunity to specify both an absolute path, and a relative path. The user himself will decide what path is more convenient to him. There are some cases when the absolute path is preferable.

I have drawn as it was possible to change a settings dialog by means of EditBox and Button.
![teleg_sets](https://user-images.githubusercontent.com/41783269/43713527-6f741998-9969-11e8-851e-ee8694837e20.JPG)

Thanks.

**Comment by Stimmenhotel** [comment]
Can I +1 this, or will I be blamed for this?
I tried to set this up within the portable version, since I use Telegram Portable on a limited acess PC on a USB-Stick.
Can't guarantee the same path for every use ... This is a little bit sad for a portable app. :(

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1423
