### ISSUE TITLE
Feature Request: Official Emacs mode

### ISSUE THREAD

**Issue by kenokenobingo** [telegramdesktop/tdesktop#5061]
It’d fun to have an official Telegram Emacs mode in order to include chats in this **huge** text editor.

**Comment by stek29** [comment]
You want emacs shortcuts?

**Comment by kenokenobingo** [comment]
No, I’m rather thinking about an Telegram client for emacs, see [this example](https://github.com/zevlg/telega.el).

**Comment by stek29** [comment]
How is that related to tdesktop?..
