### ISSUE TITLE
Russian IP accounts/phone numbers getting autobanned with Telegram API

### ISSUE THREAD

**Issue by bettergram** [telegramdesktop/tdesktop#5062]
Hi,

First off, thanks a lot for open sourcing your code and API :)

We're having some Russian users report that their Telegram numbers/accounts are being banned after logging into our client which uses your API.

It says "Number Is Blocked"

They're either using Russian phone numbers or IPs. Is this normal?

**Comment by bettergram** [comment]
![image](https://user-images.githubusercontent.com/38667236/43706745-caa034da-9998-11e8-9f25-cb9fa3da93c9.png)

**Comment by john-preston** [comment]
@bettergram I'm sorry, I can't help you with that. This repository is only about the Telegram Desktop and you're talking about server side restriction.

**Comment by stek29** [comment]
Contact recover@telegram.org

**Comment by bettergram** [comment]
Thanks John and Stek29.

Do you know who I can contact regarding how the API works with the russian numbers/ips?

We want to know if we can allow russian users or not.

**Comment by john-preston** [comment]
@bettergram You can write details to recover@telegram.org including phone numbers of those users.
