### ISSUE TITLE
Middle-click to "Mark as read"?

### ISSUE THREAD

**Issue by sn3akyb3ar** [telegramdesktop/tdesktop#5063]
I think it would be more handy to use. If you're not going to use it for some other option later, of course.

**Comment by bryanpedini** [comment]
If the "shortcut" isn't already taken by any other gesture, this middle-to-MasR could make happy users of both #1625 (and #4393) and #5998 (and #6004).
(earliest to newest)

Would love so much to see a middle-click feature in Telegram Desktop!!
Thanks in advance!

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4393 better.
