### ISSUE TITLE
Shortcuts for selected text not working

### ISSUE THREAD

**Issue by Imanflow** [telegramdesktop/tdesktop#5065]
I don't remember if this started happening in this version or in a previous update, it's not that i use this feature so frequently.

### Steps to reproduce
1. Write something in the text box
2.  Select the text
3. Press any shortcut (Crtl + Shift + M, Crtl + B...)

### Expected behaviour
Format the text

### Actual behaviour
Nothing
### Configuration
Ubuntu 18.04

1.2.17

Night

**Comment by john-preston** [comment]
@Imanflow 1.2.17 is a very old version.
