### ISSUE TITLE
Telegram Desktop for Windows 10 crashes

### ISSUE THREAD

**Issue by dermeister0** [telegramdesktop/tdesktop#5067]
### Steps to reproduce
1. Install Telegram Desktop from Store.
2. Run it.

### Expected behaviour
Telegram Desktop works correctly.

### Actual behaviour
Telegram Desktop crashes every time.

![2018-08-07_2225](https://user-images.githubusercontent.com/4054844/43785544-bfe62b96-9a90-11e8-8fd9-117aca9f8173.png)

```
C:\Program Files\WindowsApps\TelegramMessengerLLP.TelegramDesktop_1.3.10.0_x64__t4vj0pshhgkwm\Telegram.exe

The data area passed to a system call is too small.
```

### Configuration
**Operating system:**

```
WindowsBuildLabEx              : 17134.1.amd64fre.rs4_release.180410-1804
WindowsCurrentVersion          : 6.3
WindowsEditionId               : Professional
WindowsInstallationType        : Client
WindowsProductName             : Windows 10 Pro
WindowsSystemRoot              : C:\WINDOWS
WindowsVersion                 : 1803
```

**Version of Telegram Desktop:**
1.3.10.0
1.4.0.0

**Comment by bryan-snyder** [comment]
you also can't adjust the telegram app window ... AT ALL.

**Comment by dermeister0** [comment]
Still have the bug after Windows update.

```
WindowsBuildLabEx              : 17763.1.amd64fre.rs5_release.180914-1434
WindowsCurrentVersion          : 6.3
WindowsEditionId               : Professional
WindowsInstallationType        : Client
WindowsProductName             : Windows 10 Pro
WindowsSystemRoot              : C:\WINDOWS
WindowsVersion                 : 1809
```

**Comment by dermeister0** [comment]
Telegram Desktop 1.4.3 works.

**Comment by dermeister0** [comment]
https://blogs.msdn.microsoft.com/sql_server_team/centennial-appsdesktop-bridge-sql-server-and-error-the-data-area-passed-to-a-system-call-is-too-small/

**Comment by dermeister0** [comment]
Fixed the issue by uninstalling SQL Server 2014.
