### ISSUE TITLE
Telegram desktop used 100% CP (all cores)

### ISSUE THREAD

**Issue by zuart** [telegramdesktop/tdesktop#5068]
### Steps to reproduce
1. Start telegram desktop
2. Block user session desktop
3. Wait 1-2 hours

### Actual behaviour
Process used 100% CP (all cores)

### Configuration
**Operating system:** Debian 9 x64

**Version of Telegram Desktop:** LAST

**Used theme**: not-used

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
supply detailed information of your system.
