### ISSUE TITLE
[Feature Request] send contact

### ISSUE THREAD

**Issue by ezdev128** [telegramdesktop/tdesktop#507]
I would like to have an ability to share some contacts with my friends (like in app for iOS for example).

**Comment by telegramdesktop** [comment]
You can share contact from your contact profile:
![image](https://cloud.githubusercontent.com/assets/6113871/6461502/846ffd8c-c1b1-11e4-92e2-b725e386f94e.png)

**Comment by ezdev128** [comment]
@telegramdesktop this is not I'm expecting to achieve.
For example I would like to share contact of my son (which is exists in my contact list) with my sister.
