### ISSUE TITLE
[FEATURE REQUEST] Categories in Chats (UI contained)

### ISSUE THREAD

**Issue by medzer** [telegramdesktop/tdesktop#5071]
### Steps to reproduce
You should use this design and add tabs :
![telegramnew2](https://user-images.githubusercontent.com/34838939/43929480-759da89c-9c35-11e8-9e46-2e8a00afab13.png)

### Expected behaviour
1. Click on tabs in the left chat list to select the one you want amongst: Groups, People, Bots, Custom Tabs)
2. The program filters accounts and only shows the ones based on the selected tab
3. Discuss with the person

### Actual behaviour
Not possible to filter

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by medzer** [comment]
The tabs can also be hidden behind a burger icon, which can also contain the edit icon then, we could also have two icons, or the actual version, i prefer this one anyway, we need to be able to add counters too but user should be able to select if he wants to see the counter or not.

**Comment by McoreD** [comment]
Have you seen https://github.com/bettergram or https://bettergram.io/ which is a fork of Telegram; it shows how this can be done.

**Comment by medzer** [comment]
@McoreD It seems really cool, I see some perspectives between your project and mine, on which email can I contact you?

**Comment by medzer** [comment]
@McoreD very interesting integration with telegram, it's like we are in it haha, and I saw that you also have the burger I talked about !! but why not automatically combining channels, groups, people and favorties, custom tab would be great to create its own group, do you have these features? could't find yet

**Comment by medzer** [comment]
@McoreD your coins feature in the right that we see on the site is huge, is it live?

**Comment by stek29** [comment]
#1107

Thanks for design suggestion btw
