### ISSUE TITLE
Old messages aren't shown without Internet connection at startup

### ISSUE THREAD

**Issue by QGkjTIYUCw** [telegramdesktop/tdesktop#5073]
Hello.

Telegram does not show the list of contacts and old correspondence, if there is no network connection at startup.
This is not the right behavior. The contact list and old messages should be visible, even if there is no network connection.

Could you fix this, please?

Thanks

### Steps to reproduce
1. Disable Internet connection
2. Start Telegram

### Expected behaviour
I expect to see a window with the shown list of contacts and with old messages.

### Actual behaviour
The empty window appears (without list of contacts, without old messages).

### Configuration
Micro$oft Windows XP SP3
Telegram Desktop 1.3.10

**Comment by Aokromes** [comment]
#3251
