### ISSUE TITLE
Picture is not fullscreen

### ISSUE THREAD

**Issue by Djaler** [telegramdesktop/tdesktop#5075]
### Steps to reproduce
1. Open any picture in message 

### Expected behaviour (and it works like this earlier)
Picture is opened on fullscreen

### Actual behaviour
The image together with the interface is shifted down relative to the top panel

### Configuration
**Operating system**: elementary OS Juno (based on Ubuntu 18.04)

**Version of Telegram Desktop**: 1.3.12 alpha

![2018-08-12 12 58 05](https://user-images.githubusercontent.com/7964583/44000864-30ef7958-9e30-11e8-9d12-9c030c96866b.png)

**Comment by evan3334** [comment]
Can confirm this is also an issue on Ubuntu 18.04. 
![image](https://user-images.githubusercontent.com/11367199/44759716-795fe200-aaf0-11e8-9b00-177526090ab0.png)
The fullscreen image view can also be dragged around like a normal window if you grab near the top:
![image](https://user-images.githubusercontent.com/11367199/44759761-af9d6180-aaf0-11e8-8e0e-c4af708acf52.png)

**Comment by rleppink** [comment]
Can confirm. The image only fullscreens correctly once, the first image you open after starting Telegram. After that, all images are opened in windowed mode.

**Comment by stek29** [comment]
#5048 related

**Comment by esl51** [comment]
The same problem on Manjaro XFCE with Telegram Desktop 1.5.4.

**Comment by sprite-1** [comment]
Is there a way to force the picture overlay to be on top of all other windows? As a temporary workaround until the issue gets resolved

**Comment by Djaler** [comment]
I can confirm this. Thanks!
