### ISSUE TITLE
Number of unread messages is displayed for chats with disabled notifications(Ubuntu)

### ISSUE THREAD

**Issue by int512** [telegramdesktop/tdesktop#5076]
If you have unread messages in chats where notifications are switched off, then you will continue get red "badge" on telegram icon like this:
![screenshot from 2018-08-12 21-09-02](https://user-images.githubusercontent.com/127223/44005484-9706f880-9e74-11e8-89de-a93443bc1c7e.png)

I would expect red badge is something for unread messages for chats that have notifications on. And grey badge for the rest.

**Comment by john-preston** [comment]
@int512 I think you can remove muted chats from the badge in Settings.

This counter (I guess, maybe I'm wrong?) is on the icon in the system panel? In that case I can't customize it in any way, sorry.

**Comment by seleznevdev** [comment]
I have the same problem. Telegram Desktop 1.3.14, Ubuntu 18.04.1

![screenshot from 2018-09-22 21-51-03](https://user-images.githubusercontent.com/5261079/45920750-ae721100-beb1-11e8-94c7-4bd3e7da1e84.png)
