### ISSUE TITLE
improve this application!

### ISSUE THREAD

**Issue by Twente-Mining** [telegramdesktop/tdesktop#5080]
This application needs an update for windows and windows

Add tabs. (mac & windows)
Add secret chats. (windows)
let us pin more conversations. letting us pin 5 is just plain stupid (mac&windows)

**Comment by Twente-Mining** [comment]
with which issue is it a duplicate?

**Comment by d0tfile** [comment]
Secret chat: https://github.com/telegramdesktop/tdesktop/issues/871, tabs (kind of): https://github.com/telegramdesktop/tdesktop/issues/1107

**Comment by RememberTheAir** [comment]
> and the part about the pinning?

[You can find the answer in one of the many issues already opened about the 5 chats limit](https://i.imgur.com/mUY0vx8.jpg)
