### ISSUE TITLE
Could you please please please get rid of the emoticon-bar on the Mac client?

### ISSUE THREAD

**Issue by jhohlfeld-otto** [telegramdesktop/tdesktop#5081]
Sorry to say, but on Mac, the emoticon bar really su***. It totally blows up my workflow. As a Mac user, I am accustomed to the system-wide shortcut Cmd+Ctrl+Space to access emoticons from the system-provided character set. This shortcut is suppressed by the Telegram client, which is a huge annoyance 😤 every time I want to answer with a smile ☺️.

 
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@jhohlfeld-otto Ctrl+Cmd+Space was broken in some version of Qt, so it doesn’t work in tdesktop right now :(

**Comment by stek29** [comment]
#2886 + #1333 (and another one which suggests option to disable emoji bar which I can't find rn)
