### ISSUE TITLE
Telegram forgets hashtags

### ISSUE THREAD

**Issue by ZhukovGreen** [telegramdesktop/tdesktop#5082]
Hi, we're using telegram for project communication and what would really benefit us is to make telegram remember all hashtags which are used in the particular channel. Now it is messing them up from another channels/conversations, but not all are available (for example we use `#freecad` but I can't find it here)

![image](https://user-images.githubusercontent.com/10520003/44297004-d32f0380-a2c9-11e8-99b1-181d87e34435.png)

# The expected behavior may be like that:
Once you type `#` you have the list of hashtags which are used in this channel + hashtags from other channels at the end of the list. If you're typing a new hashtag, then you see something like create new

In the search bar if you type hashtag all hashtags appears

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3707
