### ISSUE TITLE
cant leave group. 

### ISSUE THREAD

**Issue by seanred111** [telegramdesktop/tdesktop#5083]
### Steps to reproduce
1. my groups...Rocket pumps
2. @BEASTRABBAN
3. 

### Expected behaviour
Tell us what should happen
leave group/report user for adding me illegaly
### Actual behaviour
Tell us what happens instead
nothing
### Configuration
**Operating system:**
windows
**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stek29** [comment]
What exactly stops you from leaving?

**Comment by john-preston** [comment]
@seanred111 Press escape maybe.

**Comment by seanred111** [comment]
you misunderstand...
    On Monday, August 20, 2018, 4:56:53 AM GMT+2, John Preston <notifications@github.com> wrote:  
 
 
@seanred111 Press escape maybe.
