### ISSUE TITLE
Make sound notification without inbox message

### ISSUE THREAD

**Issue by WiRight** [telegramdesktop/tdesktop#5086]
### Steps to reproduce
1. Using Telegram 
2. Sometimes Telegram will sound notification, but message not received

### Expected behaviour
No more sounds =)

### Actual behaviour
Only then get real notification - play sound

### Configuration
**Operating system:**
(name -a)
`Linux debian 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux`

**Version of Telegram Desktop:**
1.3.12 alpha

**Used theme**:
Default

**Comment by stek29** [comment]
I don't understand.

Do you get TDesktop notification sound when there is no message?
Maybe it's not tdesktop? I've seen some sites which use TDesktop-style pop-ups for ads with exact same sound :)

**Comment by WiRight** [comment]
@stek29 no, i dont use TDesktop site version, cause im from Russia and dont use VPN (we have some problems with accessing to site =) )
Also, chrome was closed (like any browsers)...
Only Desktop version
So, you are right, TDesktop get notification when there is no message)

Sorry for bad english...)

**Comment by stek29** [comment]
@WiRight can you please describe the issue in Russian then?

Also, see https://github.com/telegramdesktop/tdesktop/releases

**Comment by WiRight** [comment]
Использую _1.3.14 alpha_ (обновился вчера)
Пока проблема не появлялась

А теперь по-нормальному =)

Во время пользования компьютером (просмотром YouTube, больше никаких вкладок не открыто) издается звук входящего сообщения TDesktop
Но в самом приложении новых сообщений нет.
Такая же ситуация повторялась, когда не использовался браузер а только IDE для разработки приложения

П.С. издавался только звук, нотификации не было

**Comment by WiRight** [comment]
In version 1.3.16 alpha this bug is not reproduced
