### ISSUE TITLE
Telegram Desktop prevents Ryzen CPU to reach lowest power state in IDLE mode

### ISSUE THREAD

**Issue by spulci** [telegramdesktop/tdesktop#5087]
Minor issue, although it could save a lot of battery power on Ryzen Mobile laptops (btw I'm on a desktop system).

### Steps to reproduce
1. Just launch your Telegram Desktop app and observe the power consumption of your Ryzen PC from the plug (I use a an APC UPS to do this check but you can also use a watt-meter)
2. Wait for a notification to come up. You should receive at least one notification to reproduce the bug.
3.  Observe the power increase in IDLE. You will register about 10 watts more when your pc is IDLE state
4. Close Telegram Desktop. You will see an immediate 10 watt decrease in IDLE mode (correct behaviour)

### Expected behaviour
Telegram Desktop should not maintain a 10 watt increased profile while running in the background

### Actual behaviour
Just after the first notification Telegram Desktop increase the power consumption in IDLE of about 10 watts. No CPU activity can be recorder on Telegram tasks from the task manager. While testing CPU is in IDLE state and cpu activity is around 0%-1%. With Telegram Desktop running after the bug my pc consumes about 53 watts in idle. Shutting down Telegram reduces the power to 43 watts.

### Configuration
Windows 10 64 bit 1803.171347.228 with Radeon RX 570 GPU Adrenalin driver 18.8.1. Ryzen CPU is Ryzen 7 1700 no overclock with 16GB DDR 4 3200mhz on an MSI Gaming Pro Carbon Motherboard with stable BIOS 7A32v1H. Amd chipset driver revision is 18.10.0813.

**Version of Telegram Desktop:**

version 1.3.10

**Used theme**:

Default dark theme

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4914
https://github.com/telegramdesktop/tdesktop/issues/4854

**Comment by spulci** [comment]
@Aokromes thank you for referring these two related bugs. I will check them to see if I can be of help at least for testing purposes. As far as I can understand the bug behind them could be the same.
