### ISSUE TITLE
Pressing InlineKeyboardButton effectively no-op after switching to Supergroup

### ISSUE THREAD

**Issue by stemar94** [telegramdesktop/tdesktop#5089]
### Steps to reproduce
1. Create group.
2. Add some bot.
3. Let the bot send a message with a InlineKeyboardButton.
4. Change group to Supergroup.
5. Press a InlineKeyboardButton.

### Expected behaviour
Bot should get notified of the button pressing. (is working with Android client)

### Actual behaviour
seemingly nothing

### Configuration
**Operating system:**
Linux 4.4.0-133-generic  # 159-Ubuntu SMP Fri Aug 10 07:31:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Version of Telegram Desktop:**
v 1.3.10

**Comment by john-preston** [comment]
@stemar94 Where can I test that (and see that Android app activates them while tdesktop doesn't)? Which bot, what command? Usually bots post new messages after buttons being pressed, but they won't be able to post a new message in the old group that was already converted to supergroup.

**Comment by stemar94** [comment]
@john-preston 

> Where can I test that (and see that Android app activates them while tdesktop doesn't)? 

Normally a visual feedback on the button (spinning circle(android)/little clock(desktop)) indicates, that it was pressed. And waiting for an [answer](https://core.telegram.org/bots/api#answercallbackquery).

> Which bot, what command?

One of my own bots.

> Usually bots post new messages after buttons being pressed, but they won't be able to post a new message in the old group that was already converted to supergroup.

In the current use case I want to edit the message. But as I said, it seems as if there is no callback_query generated by the client. But I cannot say for sure, at least I don't get the visual feedback nor does my bot receive a query.

**Comment by john-preston** [comment]
@stemar94 And is the old message (from old group after it was converted to supergroup) edited by the bot in Android? Or the edition itself doesn't happen?

**Comment by stemar94** [comment]
@john-preston 
>And is the old message (from old group after it was converted to supergroup) edited by the bot in Android? Or the edition itself doesn't happen?
Yes the message gets successfully edited with the android client.
I get the callback_query, handle it and the edit_text is also successful.

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
