### ISSUE TITLE
Permanent high CPU usage under Windows 8.1

### ISSUE THREAD

**Issue by marcoklv** [telegramdesktop/tdesktop#509]
Permanent high CPU usage under Windows 8.1 64-bit Sytem Process usage 15-20 %. If i close
telegram desktop program fan stop and the system process in task monitor going down to normal work. If i start telegram: system process coming up to 15-20 % on cpu usage and fan start on laptop and never stop!

Telegram 0.7.17
XPS Dell Laptop
Windows 8.1 Pro 64bit
Intel® Core™ i7 CPU

**Comment by auchri** [comment]
Not able to reproduce
