### ISSUE TITLE
Global Menu in KDE Plasma

### ISSUE THREAD

**Issue by rawlife56** [telegramdesktop/tdesktop#5090]
### Steps to reproduce
1. Open Telegram app and there isn't any menu because global menu support is missing in KDE Linux.

### Expected behaviour
Global app menu in the top with all basic functions.

### Actual behaviour
No menu at all

### Configuration
**OS- Arch Linux
Desktop environment - KDE**

**Telegram version - 1.3.10**

**Theme - Default*:

**Comment by Tids** [comment]
There isnt any menu in Telegram. So there is nothing to export / show in a global menu.

**Comment by rawlife56** [comment]
Stuff seen in the side bar right now can be cool in the menu as it gives a universal look with Plasma or we can do a implementation like Call, end call, Add people to group, Archive/Mute chat, settings etc.
