### ISSUE TITLE
The problem of windows Telegram compilation

### ISSUE THREAD

**Issue by xy1899** [telegramdesktop/tdesktop#5091]
1>c:\tbuild\tdesktop\telegram\sourcefiles\rpl\mappers.h(422): error C3546: “...”: 没有可用于扩展的参数包
1>c:\tbuild\tdesktop\telegram\sourcefiles\mainwidget.cpp(306): note: 参见对正在编译的 类 模板 实例化 "rpl::details::tuple_mapper<Dialogs::Key &,const rpl::details::argument_mapper<0> &>" 的引用
1>c:\tbuild\tdesktop\telegram\sourcefiles\ui\rp_widget.h(106): note: 参见对正在编译的 类 模板 实例化 "rpl::event_stream<bool>" 的引用
1>c:\tbuild\tdesktop\telegram\sourcefiles\rpl\mappers.h(422): error C3520: “Args”: 必须在此上下文中扩展参数包
My VS2017 version:15.8.1

**Comment by john-preston** [comment]
@xy1899 Yes, the 15.8 compiler has some regressions. I've reported them to Visual Studio team.

The code with workarounds (that will compile under 15.8) will be uploaded here soon (some other things are not public-ready yet).

**Comment by stek29** [comment]
fddc3d6ad9f3bf261e955400543e09964387ac73
