### ISSUE TITLE
Phone number lost after crash of PC

### ISSUE THREAD

**Issue by Martin-Furter** [telegramdesktop/tdesktop#5092]
We have a lot of power outages here and since I have no UPS the PC will lose its power and all data.

Sometimes when this happens telegram desktop loses the phone number and I have to re-enter the phone number and the telegram code. This does not always happen. I guess this happens because telegram desktop doesn't do atomic updates on its files.

I use telegram desktop 1.3.10-2 on debian linux.

**Comment by Aokromes** [comment]
#3963
