### ISSUE TITLE
Extremely slow when typing with Rime's TSF input method on Windows

### ISSUE THREAD

**Issue by EtaoinWu** [telegramdesktop/tdesktop#5093]
### Steps to reproduce
1. Install Weasel input method engine on Windows,
2. Switch to weasel (TSF) input method with any input scheme,
3. Type anything in tdesktop in any chat

### Expected behaviour
You can type normally

### Actual behaviour
The whole application becomes extremely slow; that's, I pressed a key on my keyboard and after the IME respond after about 6 seconds.

### Configuration
**Operating system:** Windows 10 17713.1002, insider slow ring

**Version of Telegram Desktop:** 1.3.10

**Used theme:** By default

<details><summary><b>Logs</b>:</summary>
There are no logs related to this issue.
</details>

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8 and latest weasel?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Comment by EtaoinWu** [comment]
> this issue is still valid on 1.9.8 and latest weasel?

sorry that I've just seen this. After the 2018-11-12 update of weasel, the TSF input method has gone; the issue is not valid anymore.
