### ISSUE TITLE
[Feature request] Reordering foto in album

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [telegramdesktop/tdesktop#5095]
It will be good idia to make possibility to reorder fotos in album.

**Comment by RememberTheAir** [comment]
You can already do that. Just drag pictures around from the album popup before sending it

**Comment by Dmitrij-Polyanin** [comment]
Yes. I am talking about after sending.
I can edit text after sending, but why can`t I edit also fotos...

**Comment by stek29** [comment]
because albums are just bunch of messages with additional field.
You can't change order of messages.

As a workaround, you can edit messages manually and exchange photos. See #5096.
