### ISSUE TITLE
[Visual Bug] The attach file icon should be hidden when editing a message

### ISSUE THREAD

**Issue by MetalDroid** [telegramdesktop/tdesktop#5096]
### Steps to reproduce
1. Send a message
2. Edit the message
3. The attach icon is not hidden

### Expected behaviour
The attach icon should be hidden to avoid creating confusion, because you mistakenly think that you can attach a file to the edited message.

### Actual behaviour
The attach icon is not hidden

### Configuration
Ubuntu 18.04 LTS

**Version of Telegram Desktop:**
1.3.10

**Used theme**:
Default theme

![image](https://user-images.githubusercontent.com/6911792/44585069-50b3b180-a7ab-11e8-84e4-41394351578c.png)

**Comment by stek29** [comment]
Actually, you can, TDesktop just doesn't support editing attachments yet.

**Comment by MetalDroid** [comment]
Hi @stek29 

Maybe I did not explain myself well. 

What I want to say is that when we are going to edit a text message, pressing the button of the clip sends the file to the chat. 

So I suggest hiding that button when we edit messages (as the Android version does) because users mistakenly think they can replace or add files to an edited message.

**Comment by stek29** [comment]
I understand what you've meant.
However, it is possible to replace media in already sent messages, tdesktop just does not support that feature yet.
So, instead of removing, it should attach media to the message being edited.

**Comment by stek29** [comment]
related: #5149

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by MetalDroid** [comment]
Currently pressing the clip button shows a warning message, at least it is an improvement. 

I close this issue
