### ISSUE TITLE
Bad audio quality

### ISSUE THREAD

**Issue by ampetrosillo** [telegramdesktop/tdesktop#5099]
Using Lubuntu 18.04 (shouldn't differ from regular Ubuntu). Client version: 1.2.17 (latest in the official repos). Sound quality of audio files (not voice messages, actual mp3s sent over as a file) is compromised, with clear bad resampling (loss of highs, peaky sound in the low treble/high-mid region). Audio is fine on the web client, or downloading the files and playing them on any local media player.

**Comment by stek29** [comment]
#4426
