### ISSUE TITLE
Exiting full-screen picture viewing by Escape key after Alt+Tab

### ISSUE THREAD

**Issue by backtozero** [telegramdesktop/tdesktop#5100]
When viewing picture in full-screen mode if you press Alt+Tab window switches on the background and image still appears in front. After that you cannot close full-screen viewing by pressing Escape. 
There is no way to quit full screen without using mouse. My guess is it looses focus.

### Steps to reproduce
1. Press on the picture to bring it full screen
2. Press Alt+Tab
3. Press Escape

### Expected behaviour
Full screen should be closed on any other key events except special function keys like [←|→|↑|↓] or so.

### Actual behaviour
Once it looses focus you cannot close it with keyboard anymore.

### Configuration
**Operating system:** Ubuntu 16.04

**Version of Telegram Desktop:** 1.3.10

**Used theme**: Default

**Comment by john-preston** [comment]
@backtozero Please check the latest alpha version from https://desktop.telegram.org/changelog#alpha-version — will it still be the problem?

**Comment by backtozero** [comment]
@john-preston It's gone! Thank you! Works as expected.
