### ISSUE TITLE
[Bug] Inspecting invisible stickers on Stickers -> Trending tab

### ISSUE THREAD

**Issue by f1amy** [telegramdesktop/tdesktop#5101]
### Steps to reproduce
1. Go to the Emoji / Stickers / GIFs menu or similar sidebar
2. Click the "Stickers" tab at the top
3. Click the "Trending" tab (fire icon) at the bottom
4. Inspect some sticker (hold the click button)
5. Move the mouse pointer slightly lower than the sticker that you're inspecting (don't remove the finger from the button)

### Bug presentation
![2018-08-26_22-15-39](https://user-images.githubusercontent.com/27062841/44630981-14d14580-a97f-11e8-8574-a914f05ec1b4.gif)

### Expected behaviour
Nothing changes
### Actual behaviour
The sticker you're inspecting changes to another invisible sticker

### Configuration
**Operating system:** Windows 10 17134 (redstone 4)

**Version of Telegram Desktop:** Tested on 1.3.10 stable and 1.3.12 alpha versions

**Comment by john-preston** [comment]
@f1amy It can be thought of as a feature — you can even preview some more stickers from the pack before you decide if you want it or not :)
