### ISSUE TITLE
[Bug] Chat history search not perfect functional in Chinese

### ISSUE THREAD

**Issue by Fezreal** [telegramdesktop/tdesktop#5102]
see Picture
https://imgur.com/a/EYpAv
https://imgur.com/a/vGkCI
https://imgur.com/a/y216G

Obviously, Chat history search not perfect functional in Chinese
The same situation at iOS Telegram

@auchri   @john-preston  @DrKLO  @Peter  
Please tell me, I should @ who is responsible for the repair of this feature.

**Comment by Fezreal** [comment]
Please actively solve the problem.

**Comment by stek29** [comment]
> Please tell me, I should @ who is responsible for the repair of this feature.

No you should not. Feel free to ping telegram on twitter, or contact in-app support.
