### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by d0tfile** [telegramdesktop/tdesktop#5103]
### Steps to reproduce
1. Clone new version (1.3.13)
2. Try to make
3. 

### Expected behaviour
Compilation without an error

### Actual behaviour
I'm getting couple of errors:
`'SHA_Init’ was not declared in this scope`
`‘SHA_Update’ was not declared in this scope`
`‘SHA_Final’ was not declared in this scope`
Caused by this file:
https://github.com/telegramdesktop/tdesktop/blob/d98bbca353fa12cc7b7fcecd193335db363aec35/Telegram/SourceFiles/base/openssl_help.h#L391-L393
_SHA -> SHA1?_

### Configuration
**Operating system:**
Arch Linux (4.18.4-arch1-1-ARCH)
**Version of Telegram Desktop:**
1.3.13
**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>
https://pastebin.com/9dK5RfMW
</details>

**Comment by john-preston** [comment]
@d0tfile Perhaps you use different OpenSSL version? This code builds in Windows, macOS and Ubuntu with the libraries like in the build instructions.

**Comment by d0tfile** [comment]
@john-preston oh, I tried `OpenSSL 1.1.0i  14 Aug 2018`, my bad. Thank you!

**Comment by Johnnynator** [comment]
I'm confused, aren't `SHA_*` functions only intended for SHA-0 and not for SHA-1. Libressl did remove these in 2015 https://github.com/libressl-portable/openbsd/commit/a35c259729689f7960598492bb39baf404b4abbd and OpenSSL has them guarded in `#ifndef OPENSSL_NO_SHA0` and removed them in 1.1.0 https://github.com/openssl/openssl/commit/474e469bbd056aebcf7e7d3207ef820f2faed4ce#diff-6f0bbf3aa0f683fa334ffeb8e6e80ec3. So I don't think they should be used at all.

**Comment by john-preston** [comment]
@Johnnynator You're right. Thanks! Good thing, they were not used :)

**Comment by john-preston** [comment]
@Johnnynator I thought that there are only SHA_ methods, because there's no SHA1_DIGEST_LENGTH and SHA1_CTX (only SHA_DIGEST_LENGTH and SHA_CTX). But I should use SHA1_ methods with SHA_DIGEST_LENGTH and SHA_CTX.
