### ISSUE TITLE
[Feature Request] Export chat data as JSON

### ISSUE THREAD

**Issue by OctoNezd** [telegramdesktop/tdesktop#5104]
Right now it is only possible to export chat data as HTML... 
![image](https://user-images.githubusercontent.com/15308404/44656363-3ecb4c00-aa01-11e8-8575-89bfa831f7f4.png)

...and whole telegram data as JSON or HTML
![image](https://user-images.githubusercontent.com/15308404/44656378-47bc1d80-aa01-11e8-8201-22c59a722a92.png)

It would be nice if I was able to export specific chat data as JSON

**Comment by ShadowJonathan** [comment]
As i said in #5169, this is severely lacking in the current desktop client.

Another feature missing mentioned in that issue was the absence of IDs in JSON exports, making it impossible to be ingested into a relational database of sorts.

**Comment by ShadowJonathan** [comment]
I'm going to start looking at Tdesktop's code, and prepare for a pull request that will fix both #5169 and this issue.

**Comment by john-preston** [comment]
@ShadowJonathan Right now additional options for single chat history export (like html vs json) won't fit well in the design of the export configuration box :( But feel free to add IDs to JSON export format.

**Comment by alegaballo** [comment]
@john-preston maybe setting a default options in the application menu could solve the issue, this way you wouldn't have to worry about the export configuration box

**Comment by ShadowJonathan** [comment]
> @ShadowJonathan Right now additional options for single chat history export (like html vs json) won't fit well in the design of the export configuration box :( But feel free to add IDs to JSON export format.

Front-end has no precedence over Backend, in terms of "can-do", right now all i'm planning to do is implement a small re-write of the global chat export (from the settings menu), and then i'll dive into individual chat JSON exports.

In the latter case, it can be as easy as adding a checkbox which says "export in machine-readable format (JSON)"

**Comment by Multimodcrafter** [comment]
I'd love to be able to export individual chats in json format! Please add it 😃

**Comment by p0358** [comment]
Bump, this should be a no-brainer. If there's scroll in global chat export, it isn't any issue to include it here as well. It doesn't break anything, doesn't make anything worse, takes little effort to implement and the lack of it is a bummer.
Exporting chats by average users is not something used every day and this JSON export option is really needed. Non-advanced users can still take the advantage of analysis tools, and such exporting option would make it much easier for them. Please implement this.

**Comment by p0358** [comment]
Other options is to make the window taller. But even if the format option is hidden before scrolling, it could just default to HTML for those who don't scroll down. (or at least please add an hidden option somewhere or something) @john-preston

**Comment by mx781** [comment]
@p0358 are you're aware that it can be done globally (https://telegram.org/blog/export-and-more)? took a bit to find and it's not per-user, but you can get a JSON to use!

**Comment by Makeshift** [comment]
Also requesting this feature. I'd like to offer chat analysis tools to people that interact with a specific game-bot in Telegram, but they are unable to get me their chat histories for a specific chat in a machine-readable format without revealing a ton of other information they have no reason to share.

**Comment by lucanello** [comment]
I would love to see this feature in upcoming versions.

**Comment by ahmados** [comment]
why this feature request  seems not difficult to implement but after 1.5 years it is still open?

**Comment by Aokromes** [comment]
lack of time / human resources, durov needs to clone preston 3 or 4 times. :trollface:

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/383e6dec43037b313a852bb3ad7e43a6ed094668
