### ISSUE TITLE
[Feature Request] Export chat data  set from & To date limit 

### ISSUE THREAD

**Issue by gsivaprabu** [telegramdesktop/tdesktop#5105]
Export chat data  set from & To date limit is very useful because large groups have large data so every time its take too much time.

FYI:- 

![image](https://user-images.githubusercontent.com/2444608/44657152-8eb60d00-aa19-11e8-9923-1533c212ad6a.png)

**Comment by timoschwarzer** [comment]
This is implemented on a per-chat basis. I'd like to be able to select a date range on full account exports, too. :slightly_smiling_face:
