### ISSUE TITLE
Popup window of "Export Data" is always on top

### ISSUE THREAD

**Issue by user3323** [telegramdesktop/tdesktop#5107]
version: 1.3.13

Popup window of "Export Data" is always on top...

even if you minimize Telegram window
even when you launch another app on Windows...

Should be fixed.

**Comment by john-preston** [comment]
@user3323 It is hidden when export is in progress. It’s always on top only while preparing the export.

**Comment by user3323** [comment]
@john-preston  

yeah, I see. But it is wrong IMHO.
What is the extra need for it to be on top?
It is simple action and simple function, no need to give this popup extra privileges.
