### ISSUE TITLE
Nightmode in BLUE?!

### ISSUE THREAD

**Issue by Twente-Mining** [telegramdesktop/tdesktop#5108]
I just updated the telegram app to the new version for windows. 
Why did you make night mode blue?
its the worst color to choose when it comes to night mode. 
Blue makes the brain think it's day, so it kinda messes up the brain.

**Comment by RememberTheAir** [comment]
@Twente-Mining that channel is run by telegram and downloading stuffs from there is as secure as running running aq TDesktop binary downloaded from Telegram's site

**Comment by john-preston** [comment]
@Twente-Mining Sorry, only one night theme is embed inside the binary. And the default was changed.

Opening any .tdesktop-theme files inside Telegram Desktop is secure.

**Comment by al-tr** [comment]
but really why? blue is awful for eyes in the darkness, red and yellow are the best, even old theme was kinda ok, but why is it blue? because of telegram logo color or what?
