### ISSUE TITLE
Telegram Export Tool Userpic lost

### ISSUE THREAD

**Issue by protectingproxy** [telegramdesktop/tdesktop#5109]
Hello
I tried to download messages via export tool. 
Userpic of all users, groups, channels are not displayed.
I think if developer will add an item for user selection (download or not), this will be a good solution. 
Understand who are chatting with me is much more convenient when you see his userpic.

**Comment by protectingproxy** [comment]
@john-preston Why you cannot do this function as optional? Somebody needed it...

**Comment by user3323** [comment]
@john-preston 

saving avatars of users and groups - would be a great thing.
