### ISSUE TITLE
[FEATURE REQUEST] Approx. size of every exporting data

### ISSUE THREAD

**Issue by user3323** [telegramdesktop/tdesktop#5110]
version: 1.3.13

It would be nice, if Telegram service would tell the user, how many MB (GB), the user need to prepare to export the data....

And as summary - the **_TOTAL approx. size of all selected data_**.

It should be easy to calculate all these sizes, right?

example: 

![image](https://user-images.githubusercontent.com/24613274/44658950-442d9400-aa0b-11e8-88b5-a81e755f6e7b.png)

PS: what the heck is "Size limit"?
I mean, I can assume what is this.
But why should I?
There should be an explanation of what is this.
And how it works.
And how it will work on different types of data.
What will it cut? Videos, photos, files? What exactly and how?

**Comment by john-preston** [comment]
@user3323 It won't be easy, sorry. No way to know that size in advance, before actually fetching all the data.

**Comment by john-preston** [comment]
@user3323 Files that exceed the "Size limit" will be skipped.

**Comment by user3323** [comment]
@john-preston 

ok, can you put it in **_backlog_**, at least?
