### ISSUE TITLE
Missing git tag for "v1.3.14"

### ISSUE THREAD

**Issue by Tids** [telegramdesktop/tdesktop#5112]
Hi. For the latest release the tag is missing on git.

works https://github.com/telegramdesktop/tdesktop/archive/v1.3.13.zip
dont https://github.com/telegramdesktop/tdesktop/archive/v1.3.14.zip

**Comment by john-preston** [comment]
@Tids Sorry about that, I'll upload the release now.

**Comment by Tids** [comment]
Thanks! Its solved now :)
