### ISSUE TITLE
Spellcheck not working on Windows 7,8,8.1

### ISSUE THREAD

**Issue by ibnzUK** [telegramdesktop/tdesktop#5114]
### Steps to reproduce

Spellchecker, autocorrection or spelling mistake checker not working on Desktop Application. 
Spellchecker works well on Skype, Viber, or any other application but not Telegram Desktop. 

People around the world using spellcheckers on daily basis, how come this is not integrated or possible. Even operating system provides API for spell checking but telegram desktop application disables it.

So far the only workaround I found was to use web or mobile version, this is crazy.

It has been asked from the community since 2014 and nothing has been done. I did massive research on this subject and from what I can see every community member has been ignored regarding this issue. 

Works well on Mac probably even on linux but not Windows OS

There are many API's and solutions but none has been implemented. 
1.  https://docs.microsoft.com/en-us/windows/desktop/api/spellcheck/nf-spellcheck-ispellchecker-comprehensivecheck
2. https://docs.microsoft.com/en-us/windows/desktop/Intl/spell-checker-api
3. https://github.com/KDE/sonnet

### Expected behaviour
It should underline misspelt words and help with choosing the right words on mouse click

### Actual behaviour
does nothing. not even windows spellchecker works in telegram desktop

### Configuration
windows 7 8 8.1 10

**Version of Telegram Desktop:**
All versions of Telegram Desktop

**Used theme**:
all themes

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@ibnzUK «but telegram desktop application disables it»

It doesn't disable spellchecker. There is work to be done for the spellchecker to work on Telegram Desktop and that work was not yet done by anyone.

**Comment by ibnzUK** [comment]
on most installed application windows os genuine spellchecker works, but not telegram desktop, this is why I said it is disabled

**Comment by stek29** [comment]
@ibnzUK That's not how it works. Spellchecker doesn't just magically get supported.

also, #96.

**Comment by ibnzUK** [comment]
The issue opened in 2014 and now locked, nothing has been done. This is why I opened it again, hope this sends developers a clear message on what community wants
