### ISSUE TITLE
Exporting data as JSON does not support some languages

### ISSUE THREAD

**Issue by nir-segal** [telegramdesktop/tdesktop#5116]
When exporting data as JSON I noticed it dose not support several languages (I only saw this with Semitic langs, but I assume there are more). As I understand later standrads of JSON do support utf-8 text.
I would love some form of machine-parse-able data that does support utf-8, as many of TGs users don't only chat in English.

**Comment by john-preston** [comment]
@Vars3 Any data is supported there, some could be escaped. This shouldn't be a problem for machine parsing.
