### ISSUE TITLE
can new feature: bot translate in message realtime?

### ISSUE THREAD

**Issue by manuelsongokuh** [telegramdesktop/tdesktop#5117]
hi i love telegram so much than Whatsapp, other apps..

so i need to ask you:
if who can new feature: translate in message before to send to friend?

example: 
-first i write english in message when i finish to write
-i click a button (Translate icon) and choose other language french and automatic translating this message.
-send to my friend

maybe can use to BOT robot translate..?

see example code from addons of firefox : 
https://addons.mozilla.org/firefox/addon/gtranslate/
i use this addons more times for my browse internet 

this is automatic translate to translate google..
this is good feature?

so this mean i can send my friend other place of world: china, Japanese, Brazil, etc etc..thank for realtime translate in message before to send to friend..

this feature can apply to version:
telegram desktop: win/linux/mac
telegram mobil: android/mac

thank you for create Telegram

**Comment by stek29** [comment]
sorry, but this is not a right place to request such a feature (you can contact support or ping telegram on twitter).

also, afaik there are some inline bots for this already.

**Comment by str** [comment]
@manuelsongokuh please upvote 6707

**Comment by str** [comment]
@manuelsongokuh please upvote #6707
