### ISSUE TITLE
RegisterCustomScheme does not consider "-externalupdater"

### ISSUE THREAD

**Issue by henning-schild** [telegramdesktop/tdesktop#5118]
### Steps to reproduce
1. install tdesktop and start it with "-externalupdater"
2. update tdesktop externally i.e. in gentoo Linux go from 1.3.10 to 1.3.14
3. now if you restart, the new version will trigger creation of a .desktop-file in ~/.local/, which will not contain the argument "-externalupdater" anymore

### Expected behaviour
The command line argument is a clear sign that a package manager feels responsible for tdesktop, and the package should ship a working desktop file.
So when the argument is found it would be best to not execute RegisterCustomScheme because that clearly is part of the internal updater. And the internal one should be disabled with the argument.

### Actual behaviour
Tdesktop will create a .desktop file and configure gnome as well. The created entries do not contain the argument and it will get lost forever, since the .local file will win over the one from the distro. Well that might depend on the window manager.

### Configuration
**Operating system:** Gentoo Linux

**Version of Telegram Desktop:** 1.3.14

**Comment by henning-schild** [comment]
see https://bugs.gentoo.org/618662

**Comment by john-preston** [comment]
@henning-schild That makes sense. Does this packaged .desktop file handle tg:// url scheme?

**Comment by henning-schild** [comment]
While you could imagine someone packaging tdesktop with a self-invented and partial .desktop-file, gentoo uses the one that comes with tdesktop.
`lib/xdg/telegramdesktop.desktop` from the tarball.
https://github.com/gentoo/gentoo/blob/231fac686e1f7a78435194132c15c22738834f0e/net-im/telegram-desktop-bin/telegram-desktop-bin-1.3.14.ebuild#L44

So the answer is yes! If you insist on generating the .desktop file in tdesktop `Exec=` should stay `telegram-desktop -- %u` and not turn into the absolute path to `Telegram`, because that breaks the wrapping and passing the argument.

But it would be best to just not re-generate the .desktop file in the application. Since packages should always install the one found in the tarball. And external updaters will update that when the tarball brings a new one.
