### ISSUE TITLE
Cannot export chat history, with the exprt tool.

### ISSUE THREAD

**Issue by emmauss** [telegramdesktop/tdesktop#5120]
### Steps to reproduce
1. Use the chat history export tool
2. Select the media to export, an the size
3. Only cancel button is available, no export button

### Expected behaviour
The export button should become visible

### Actual behaviour
The export button does not appear

### Configuration
**Operating system:**
Window 10 x86_64
**Version of Telegram Desktop:**
V 1.3.14
**Used theme**:
Dark theme
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@emmauss Please show the screenshot of the export settings window.

**Comment by emmauss** [comment]
![chatexp](https://user-images.githubusercontent.com/5307160/44841631-59850700-ac33-11e8-8d6e-8529987c1b37.PNG)
here

**Comment by john-preston** [comment]
@emmauss I see. Looks like a bug. Can you please open Settings, choose "Export Telegram data" and there choose some data types (so that there will be the export button) and press it. After that cancel that (whole data) export and try to export single chat history once more?

**Comment by emmauss** [comment]
That does not fix it

**Comment by emmauss** [comment]
Export still does not work in the latest prerelease

**Comment by john-preston** [comment]
@emmauss Does it work in 1.4?

**Comment by emmauss** [comment]
It works
