### ISSUE TITLE
After latest update, the notification icon not showing anymore in Ubuntu 

### ISSUE THREAD

**Issue by cbruchert** [telegramdesktop/tdesktop#5121]
### Steps to reproduce
1. Open Telegram Desktop on Ubuntu
2. Make sure "Show tray icon" is set

### Expected behaviour
Telegram icon should appear on the notification bar

### Actual behaviour
No icon appeared

### Configuration
**Operating system:**
Ubuntu 18.04.01 LTS

**Version of Telegram Desktop:**
1.3.14

**Used theme**:
default

**Comment by Aokromes** [comment]
strange, works for me (TM)
https://i.imgur.com/vEGP3wB.png

**Comment by cbruchert** [comment]
Same as #4933 :(
For some reason these indicator-* packages keep coming back to my system. Maybe I need a clean installation.
