### ISSUE TITLE
[FEATURE REQUEST] - width and height of "Caption" of the img

### ISSUE THREAD

**Issue by user3323** [telegramdesktop/tdesktop#5122]
version: 1.3.14

I know, that caption should be caption, it should be something little and small, in addition for the image.

But ...

![image](https://user-images.githubusercontent.com/24613274/44851465-13e33100-ac69-11e8-83b2-ca035e8fd36f.png)

**_2 and half lines in height?_**
It is absolutely should have bigger width and height.

1) it should auto-change it's width and height in the order to how much text it has in it;
2) the popup window should has little triangle thing (bottom right) for manual enlarge this popup window (and so, enlarge the caption text area) :
![image](https://user-images.githubusercontent.com/24613274/44851666-be5b5400-ac69-11e8-972f-d0362125b509.png)

**Comment by Neurotoxin001** [comment]
https://github.com/telegramdesktop/tdesktop/commit/51f960442ec3dfd9a9b5040ded6993a738dade72
