### ISSUE TITLE
Mixing locales

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#5125]
Derived from #4797.

For some reason tooltips use system locale instead of language pack's locale. That looks pretty strange.
Why not using language pack's locale instead of system?

**Comment by RadRussianRus** [comment]
Still interested in this.

**Comment by ilya-fedin** [comment]
> Why not using language pack's locale instead of system?

This would be really unexpected behavior. Imagine that you have a Russian system and English language in Telegram: you will get time/date format from en_US locale with 12-hour format. Not to say that language packs have only lang code, without country and, in addition, it is a problem to convert some their names to Qt format.
