### ISSUE TITLE
[request] handle songs thumbnails, if available

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#5130]
### Steps to reproduce
1. receive a song message with a thumb attribute set

### Expected behaviour

Telegram Desktop handles that thumbnail and displays it below the play icon of the song message, in a similar way [Telegram X for Andorid does](https://i.imgur.com/aN9UcuS.jpg) (or similarily to how png files' thumbails are already handled)

### Actual behaviour

Telegram Desktop ignores songs thumbnails

### Configuration
**Operating system:** any

**Version of Telegram Desktop:** 1.3.15

**Comment by RememberTheAir** [comment]
Still missing

**Comment by 23rd** [comment]
Implemented in 2.5.6 version.
