### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by valeriy-efimov** [telegramdesktop/tdesktop#5131]
### Steps to reproduce
1. Build Telegram desktop.
2. 
3. 

### Expected behaviour
Successful build.

### Actual behaviour
Tell us what happens instead
![image](https://user-images.githubusercontent.com/5989188/44954755-e5a36280-aeaf-11e8-854b-c7259a71cb78.png)

### Configuration
8.1

**Version of Telegram Desktop:**
last
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>
#

**Comment by Johnnynator** [comment]
Did you actually flollow the documentation to build tdesktop?
https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md

**Comment by valeriy-efimov** [comment]
@Johnnynator yes, install all "third party software" and run "x86 Native Tools Command Prompt for VS 2017.bat"
![image](https://user-images.githubusercontent.com/5989188/44955725-ccef7880-aec0-11e8-9bb8-668b57782549.png)

**Comment by 23rd** [comment]
You just downloaded tdesktop repository as archive?

**Comment by 23rd** [comment]
@valeriy-efimov review every output line of cmd. If you just copied whole script and pasted to cmd, it could have just stopped at line, like `gyp dump_syms.gyp` or another one.
As I can see your output of Visual Studio, you just haven't compiled the libraries.

**Comment by 23rd** [comment]
@valeriy-efimov You can look at this: https://github.com/telegramdesktop/dependencies_windows.
This repository contains compiled dependencies for the windows build. 
But it is only good to compile a debug version.
I have a fork of repository, which contains recompiled libraries with new version of Visual Studio. You can just clone it and use.
https://github.com/23rd/dependencies_windows

**Comment by valeriy-efimov** [comment]
now get new error
![image](https://user-images.githubusercontent.com/5989188/44957993-37fd7700-aee2-11e8-9bea-0c44859a204c.png)

**Comment by 23rd** [comment]
Read the instruction closely. At least you have missed Range-V3-VS2015 library.

**Comment by valeriy-efimov** [comment]
@23rd 
![image](https://user-images.githubusercontent.com/5989188/44958233-0e464f00-aee6-11e8-84e4-6eb7e6f7aedf.png)

**Comment by valeriy-efimov** [comment]
@23rd 
![image](https://user-images.githubusercontent.com/5989188/44991561-1a411800-af9d-11e8-9ada-f6807453c79f.png)

**Comment by 23rd** [comment]
Outdated. Please reopen it if you still have problems with compilation.
