### ISSUE TITLE
[BUG] playing mp3 in external app

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#5133]
### Steps to reproduce
1. upload  .mp3
2. press play button
3. 

### Expected behaviour
playing in telegram

### Actual behaviour
playing in external app associated with .mp3, player starts and immediately closes
### Configuration
**Operating system:**
win 10 x64 1803
**Version of Telegram Desktop:**
1.3.15 alpha

problem .mp3 in attachment
[Driftmoon - Avalon (Extended Mix).zip](https://github.com/telegramdesktop/tdesktop/files/2343642/Driftmoon.-.Avalon.Extended.Mix.zip)

and same behaviour on linux
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
cannot reproduce on 1.9.0 beta.

**Comment by f242** [comment]
@Aokromes what answer you need? problem is still present

**Comment by Aokromes** [comment]
well, i cannot reproduce on windows 10 x64 20h1 and telegram desktop 1.9.0 beta.

**Comment by f242** [comment]
video with 1.9.2 beta
[2019-12-31-14-00-52.zip](https://github.com/telegramdesktop/tdesktop/files/4012512/2019-12-31-14-00-52.zip)

**Comment by Aokromes** [comment]
tried myself with same file on windows 10 x64 20h1 and telegram desktop 1.9.4 and audio player opens fine.

**Comment by f242** [comment]
@Aokromes i asked my friend to test and result is the same - no "play" button
![image](https://user-images.githubusercontent.com/10371194/72685366-88d33700-3afa-11ea-8994-c9ba7f53a38f.png)
he is linux user

**Comment by Aokromes** [comment]
ok, i misunderstand what you mean. i suggest you to change title to "Mp3 plays on external player instead in telegram"

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4327
