### ISSUE TITLE
Can't leave group i was added without my consent

### ISSUE THREAD

**Issue by schnphil** [telegramdesktop/tdesktop#5135]
Hello.
Me and a lot of friends were added to a group with a few hundred people we don't know. We can't leave this strange group on the Smartphone App (iOS, Android). We had to use the Desktop app to leave it. When we asked what this is about we were muted.

This issue seems to be a a problem since at least two years https://github.com/telegramdesktop/tdesktop/issues/1614 

Please fix this. This is super creepy and makes me think about using telegram not any longer if there are such security issues.

Thank you

**Comment by stek29** [comment]
How did you try to leave on iOS/Android app?

And if TDesktop worked fine, why did you open an issue here?..
