### ISSUE TITLE
Window doesn't appear when using GTK+ theme for QT

### ISSUE THREAD

**Issue by ryanrms** [telegramdesktop/tdesktop#5136]
### Steps to reproduce
1. Tested on an LXQT desktop running Debian unstable
2. Telegram opens fine with any QT theme except the one that mimics GTK
3. When this is selected, Telegram will not display a window 

### Expected behaviour
Telegram should open normally
### Actual behaviour
Telegram does not show a window

### Configuration
**Operating system:**
Debian unstable kernel 4.18.5-towo.1-siduction-amd64 #1 SMP siduction 4.18-5 (2018-08-24) x86_64 GNU/Linux

**Version of Telegram Desktop:**
 1.3.14-1
**Used theme**:
Default telegram theme, GTK theme as QT theme

**Comment by Aokromes** [comment]
I suppose the reason is https://github.com/telegramdesktop/tdesktop/issues/1815

**Comment by Aokromes** [comment]
no answer after more than 1 year, closing.
