### ISSUE TITLE
Make the selection of the forwarded messages

### ISSUE THREAD

**Issue by agarkoff** [telegramdesktop/tdesktop#5138]
### Steps to reproduce
1. Forward messages from one chat to another

### Expected behaviour
Messages should be allocated as a quote in the same way as it is now done in the web version of Telegram.

### Actual behaviour
Messages are not allocated as a quotation
Do not group messages from one contact

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.3.14

**Comment by Lonami** [comment]
This is personal preference and the way Telegram Desktop does it lets you distinguish from who the messages were forwarded… If you like webogram style better, use webogram.

**Comment by agarkoff** [comment]
If you do not want to make the interface more understandable, then you are not a very smart person.

**Comment by agarkoff** [comment]
The cited messages in the desktop version should look exactly the same as in the web version, because it is clearer. With grouping and correct indents.

**Comment by Lonami** [comment]
I could argue it's less clear if:
1. The window is not tall enough, and
2. There are too many messages from the same person in a row.

At some point, it's not possible in the web version to tell *who* the message was forwarded from or even who forwarded it in the first place. Telegram Desktop on the other hand correctly displays both at any time. So "it is clearer" is subjective.

**Comment by RememberTheAir** [comment]
@agarkoff  You keep saying "clearer" but I really don't see how tdesktop's way of dispalying them is unclear. Can you elaborate a bit? Cause I'm probably not smart enough to grasp it

**Comment by Lonami** [comment]
Let's move from opinion to facts.
Web:
![web](https://user-images.githubusercontent.com/6297805/49697501-817ff100-fbb8-11e8-9c5c-17092ffe1621.jpg)

Desktop:
![desk](https://user-images.githubusercontent.com/6297805/49697502-85137800-fbb8-11e8-9daa-5048ff2cf4c2.jpg)

Hm.

**Comment by stek29** [comment]
Agreed -- it's a matter of personal preference, and no way there's going to be an option for this.
