### ISSUE TITLE
Forward messages as a copy.

### ISSUE THREAD

**Issue by cmfc31** [telegramdesktop/tdesktop#5142]
### Steps to reproduce
1. Select a message. 
2. Click foward option.
3. Check "Send as a copy" option.

### Expected behaviour
Send a copy of the original message under my username, the same way as you can do in Telegram X.

### Actual behaviour
There's no option to send messages as a copy.

### Configuration
**Operating system:**Windows 10 x64

**Version of Telegram Desktop:** 1.3.14

**Used theme**: Night Theme.

**Comment by lucaszanella** [comment]
I also can't see any option to send message as copy

**Comment by RememberTheAir** [comment]
@lucaszanella that's why this issue is still open

**Comment by cmfc31** [comment]
I'm still waiting for this feature.

**Comment by erickskrauch** [comment]
I'm still waiting for this feature.

**Comment by lucaszanella** [comment]
me too

**Comment by cmfc31** [comment]
Same, using Plus Messenger as a work

**Comment by cmfc31** [comment]
Whoops, that's a weird place for a close issue button haha.

Same, using Plus Messenger to forward as copy for now.

**Comment by cmfc31** [comment]
With the latest update the forwarding options feature it's finally here!
![image](https://user-images.githubusercontent.com/34674157/131698166-76965a33-9188-4354-9571-c19d81cb383e.png)
