### ISSUE TITLE
Theme editor crashes whole client on attempt to change non-existent color

### ISSUE THREAD

**Issue by porrided** [telegramdesktop/tdesktop#5143]
### Steps to reproduce
1. Press "Edit theme" in Settings, save the palette file. The theme editor shall then open.
2. Enter gibberish (e.g. "outgoing messages") in the search field so nothing is found/displayed
3. Press Enter

### Expected behaviour
No reaction, since there's no color to pick a value for.

### Actual behaviour
The process crashes, receiving SIGABRT.

### Configuration
**Operating system:** Debian Sid, Linux 4.9.110; perhaps, this is reproducible on other operating systems, no way to test.

**Version of Telegram Desktop:** Debian Sid package 1.3.14-1, tdesktop reports 1.3.14 as well.

**Used theme**: Default (after a reset in Settings)

<details><summary><b>Stdout/stderr log output</b>:</summary>
ASSERT failure in QVector<T>::operator[]: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h, line 436
</details>

<details><summary><b>Logs</b>:</summary>
</details>

**Comment by john-preston** [comment]
@porrided Thanks!
