### ISSUE TITLE
About multi-used strings in User Restriction & Disable Notification Menu

### ISSUE THREAD

**Issue by KazamaSion** [telegramdesktop/tdesktop#5146]
Other sections are no need to be filled with.  
### Expected behavior  
Create a `lng_mute_duration_day#{$type}` to resolve the issue that multi-using the string `lng_rights_chat_banned_day#{$type}`.  

### Detail  
![](https://i.loli.net/2018/09/08/5b9312180c1dd.png)   
The strings included in the left pic are named as `lng_mute_duration_{$time}#{$type}`, the one included in the right photo are named as `lng_rights_chat_banned_{$time}#{$type}`.  
The fact is, when it comes to "for xxx day(s)", they quote the same type of string `lng_rights_chat_banned_day#{$type}`. One is `lng_rights_chat_banned_day#other`, another is `lng_rights_chat_banned_day#one`.(also the two texts framed in) But relatively, "for xxx hours" in the left use `lng_mute_duration_hours#{$type}`, and "for xxx weeks" in the right use `lng_rights_chat_banned_week#{$type}`, which are 2 different naming methods.   
Isn't it would making trouble in localizing? AFAIC, the same string may get 2 different translations in distinct languages in unequal scenario.

**Comment by john-preston** [comment]
@KazamaSion Does it already make a problem in some language or it just could make one, so you want to change that in advance?

**Comment by KazamaSion** [comment]
@john-preston To concluded, It isn't but **maybe**.  
For now, the text "for 3 days" use `lng_rights_chat_banned_day#other`, and "for 1 day" use `lng_rights_chat_banned_day#one`. They can be translated into different translations to avoid the possible problem provisionally.   
If it involved in the translation itself, let me make an analysis.   
The "until" in "Restricted until" is a preposition, which must be following by noun, gerund, pronoun. so the "for" here or inputting the same word "until" makes nonsense. In Android, Android X, iOS, though they use different copywriting: banned/restricted until, block for, etc, but at least they use the correct grammar and adapt the noun as placeholder. And the wrong usage must result in that the translation must make it right, or will reserve the grammar mistake into translation, at least in Simplified Chinese
.   
Changing the original text is not a good idea. If the "for xxx day/week" be changed to "xxx day/week".
the strings included in the left pic will be involved. Same as chaning translations. As mentioned in the first comment, it now can be avoided by translating `lng_rights_chat_banned_day#{$type}` and `lng_rights_chat_banned_day#other` in different ways. However, if it comes to the case "restricted until (for) 3 days", it no longer works and the mistake will be shown.  

**It is an incipient fault which can cause trouble in the future.**

**Comment by john-preston** [comment]
@KazamaSion This can be changed when it's required. But currently tdesktop doesn't have Simplified Chinese translation, so I guess no translator at this point had a problem with current phrases.

**Comment by KazamaSion** [comment]
@john-preston I suppose you remember that TDesktop support custom localization pack. The usage in the multi-language scenario should always be considered.

**Comment by KazamaSion** [comment]
@john-preston Hello there, Chinese now will be the official language. Could you make some changes to this issue?

**Comment by john-preston** [comment]
@KazamaSion I don't quite follow, but if I introduce "lng_mute_duration_days#{one,...,other}" and use it in the "Disable notifications" box (left screenshot) instead of "lng_rights_chat_banned_day" - will it solve the issue with Simplified Chinese translation?

**Comment by KazamaSion** [comment]
@john-preston This is the purpose of this issue, and that is what I mean as well.
Thanks for following this issue, and it will solve the problem with Simplified Chinese translation.
