### ISSUE TITLE
[Feature request] Tabbed sidepanel to sort Chats, Groups, Channels

### ISSUE THREAD

**Issue by roscoevanderboom** [telegramdesktop/tdesktop#5147]
Hi Telegram team!!

Thank you for this amazing project!! I am migrating all old social media habits onto Telegram.

I see in the Telegram X app there is a "Chats" and "Calls" tab. Great function!
Would it be possible to create more in the side panel for "Channels" ; "Groups"?
Or perhaps allow user to create/name their own Tabs, i.e. "Friends" ; "Work"

As we add more conversations it would be nice to sort them a bit better.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1107
