### ISSUE TITLE
[Feature request] IPFS intergration?

### ISSUE THREAD

**Issue by roscoevanderboom** [telegramdesktop/tdesktop#5148]
Are there any plans to integrate Telegram with IPFS? Currently, I use IPFS managers to add files, then I share my links on Telegram. It works very well. But I believe it could be made even more convenient.

Either for Telegram to start it's own IPFS Daemon or connect to a currently running node. At first, it would only be for static content, as IPFS doesn't support data streams yet.

Would it possible to "add contacts by PeerID"? In this way, Telegram could:

- encrypt files ( as it already does ) with receiver ID
- create IPFS object
- send to selected Peer

**Comment by stek29** [comment]
Does not really adhere to Telegram Feature Philosophy.
