### ISSUE TITLE
Media replacement feature

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#5149]
_I feel like there was a similar issue, however I cannot find it now._

### Expected behaviour
Telegram for Android as well as Bot API already support media editing, when you can replace almost any media (file, image, gif) with another media (even of another kind). 

### Actual behaviour
Unfortunately Telegram Desktop doesn't support this.

### Configuration
**Version of Telegram Desktop:** 1.3.16 alpha

**Comment by 23rd** [comment]
Implemented in the latest beta.
