### ISSUE TITLE
[Feature Request] p2p file sharing option & advanced file search

### ISSUE THREAD

**Issue by dexkz** [telegramdesktop/tdesktop#515]
1. For example, If the user is in the same local network, add an option to send files p2p. Very useful office feature
2. Request all the files in the chat, and add filter\search options. Now if i open the chat and use Shared Media button, i see only last few files, and if i want to see more, i must manually scroll through the chat.

**Comment by ezdev128** [comment]
Totally agree with you, @dexkz.
+1000

**Comment by EmptyStackExn** [comment]
**Idea 1**: Questionable. Telegram is based upon a [specific privacy protocol](https://core.telegram.org/mtproto) that makes it so special (contrary to other IM services). Adding such a feature would first need to question the whole privacy protocol : this is not only feature request, it's rather protocol design-choice change request.

I personally and highly doubt on the ratio interest-of-feature / risk-taking. Cryptography is always like "*small is beautiful*".

**Idea 2** : Good idea.

**Comment by ezdev128** [comment]
@EmptyStackExn Don't the same crypto protocol is used in secure chat? It is p2p chat, isn't?
So why it is impossible to send the files via the same way? Why it is not possible to guess if the person in the LAN (rfc1918) or the same real network (within 0-1 hops in TTL) or some other way (e.g. guess multicast user) and send them directly?
I don't saw the depth of protocol, but I pretty sure it could be used with some minimal adjustments in network layer.
Maybe I'm wrong. Correct me if so.

**Comment by ppparadox** [comment]
Something like Retroshare perhaps?
