### ISSUE TITLE
Media replacement is shown incorrecrly in Recent Actions

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#5150]
### Steps to reproduce
1. Send media file (e.g. photo)
2. Replace it with another media (e.g. music)
3. Look at Recent Actions

### Expected behaviour
This is the second part of #5149. When you replace one mediafile with another, it should be correctly stated in Recent Actions (maybe with the previous media shown, but even Telegram for Android doesn't show previous mediafile)

### Actual behaviour
TDesktop states "edited caption" with "previous caption" set to "Empty"

### Configuration
**Version of Telegram Desktop:** 1.3.16 alpha

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by MasterGroosha** [comment]
@Aokromes Yes, this bug is still valid. 
TDesktop 1.9.8

**Comment by MasterGroosha** [comment]
Still valid as of 2.4.4

**Comment by MasterGroosha** [comment]
Still relevant, TDesktop 2.7.4

**Comment by MasterGroosha** [comment]
The issue is still here

**Comment by 23rd** [comment]
Please check the 3.7.2 version.

**Comment by MasterGroosha** [comment]
@23rd Thank you! 
I guess it's not possible to show the previous version of an image, and since the current TD's behavior is consistent with Android and iOS, I'm going to close the issue.

Thanks again :muscle:
