### ISSUE TITLE
[Ubuntu 18.04] Window moves up on activation or launch

### ISSUE THREAD

**Issue by Dabuka** [telegramdesktop/tdesktop#5151]
### Steps to reproduce
1. Launch Telegram
2. Close Telegram to tray
3. Open Telegram
4. Window moved a little bit upward
5. Repeat till the window meets the top of the screen.

### Expected behaviour
Window opened at the exact position it was closed

### Actual behaviour
Window is moving up.

### Configuration
**Operating system:** Ubuntu 18.04

**Version of Telegram Desktop:**
1.3.14

**Comment by stek29** [comment]
#2585
