### ISSUE TITLE
How sync my app (build by TDLib) by "Telegram Desktop – Official Messenger"

### ISSUE THREAD

**Issue by jackstowart** [telegramdesktop/tdesktop#5152]
Hi. i want to build my own telegram app.
and i wanna sync this app by Official Messenger.

The first solution is to using tdata (working directory of Telegram that also contain account info & ..) by my app that created by TDLib. but how? is it possible?

i have a problem too! after some break-point in VS2017 for debug purposes, my tdata deleted automatically! what happen in background?! is it under sandbox functionality?!

**Comment by stek29** [comment]
Sharing sessions is a very bad idea.

**Comment by jackstowart** [comment]
Telegram project is a fully open source project so everyone can think and ask and utter any question about it.
is it clear?
ok good.

**Comment by stek29** [comment]
You're clearly misunderstanding what opensource means.
