### ISSUE TITLE
failed in building-msvc.md

### ISSUE THREAD

**Issue by archive-me** [telegramdesktop/tdesktop#5155]
i wanna build last version of telegram desktop in visual studio v.15.8.3 , but failed building in build "openal-soft" library.Where is the problem?

![untitled](https://user-images.githubusercontent.com/42973767/45283925-6daeeb00-b4f4-11e8-8ae8-66d98c2aac2c.png)

**Comment by maxh323** [comment]
edit the file openal-soft\CMakeLists.txt. delete all records "-D_WIN32_WINNT = 0x0502"

**Comment by Shingen666** [comment]
> edit the file openal-soft\CMakeLists.txt. delete all records "-D_WIN32_WINNT = 0x0502"
just wanted to say that i had the same issue (on Win 7 though) when i tried to build it for the first time recently, and this solution worked for me.
