### ISSUE TITLE
Telegram Desktop cannot find fonts when file chooser dialog box opens

### ISSUE THREAD

**Issue by cocoa1231** [telegramdesktop/tdesktop#5156]
### Steps to reproduce
1. Go to any chat
2. Press the attachment button

### Expected behaviour
A regular dialog box with text should appear

### Actual behaviour
All the text is replaced by unicode boxes. I've attached a screenshot below

### Configuration
Operating System: Arch Linux, GNU/Linux

Telegram Desktop Version 1.3.14

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

### Extra details about the setup
I've modified the `Exec` like in the `.desktop file` from

`Exec = /home/cocoa/Downloads/Telegram/Telegram -- %u`

to

`Exec=/bin/bash -c 'FONTCONFIG_FILE=/etc/fonts /home/cocoa/Downloads/Telegram/Telegram -- %u'`

Because otherwise telegram fails to find the fontconfig file and takes almost 3 minutes just to load. These issues might be related. Output of `printenv` is given below

` LANG=en_US.UTF-8
DISPLAY=:0
XDG_VTNR=1
LOGNAME=cocoa
INVOCATION_ID=b63ae7179a98448a9ee3fa1512b81eb7
PWD=/home/cocoa
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
XAUTHORITY=/home/cocoa/.Xauthority
SHLVL=4
JOURNAL_STREAM=9:18745
COLORTERM=truecolor
XDG_SESSION_ID=1
LESS=-R
WINDOWPATH=1
ZSH=/home/cocoa/.oh-my-zsh
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1004/bus
VTE_VERSION=5202
MAIL=/var/spool/mail/cocoa
_=/usr/bin/printenv
OLDPWD=/home/cocoa
SHELL=/bin/zsh
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
WINDOWID=50331651
TERM=xterm-256color
XDG_CURRENT_DESKTOP=GNOME
PAGER=less
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
HOME=/home/cocoa
XDG_SEAT=seat0
XDG_RUNTIME_DIR=/run/user/1004
LSCOLORS=Gxfxcxdxbxegedabagacad
USER=cocoa
LC_CTYPE=en_US.UTF-8
`

![2018-09-10_15-55](https://user-images.githubusercontent.com/12653684/45292190-0f910080-b512-11e8-87c2-c7a6c081d03d.png)

**Comment by stek29** [comment]
#3418

**Comment by cocoa1231** [comment]
Running it as `sudo` or running the `find` command did not help. I installed the `ttf-opensans` package from the AUR and ran` fc-cache -vf`, but that did not work too. Below is the output when I run telegram from the terminal:

` ✘ cocoa@archlinux  ~  FONTCONFIG_FILE=/etc/fonts Downloads/Telegram/Telegram
Fontconfig warning: no <cachedir> elements found. Check configuration.
Fontconfig warning: adding <cachedir>/var/cache/fontconfig</cachedir>
Fontconfig warning: adding <cachedir prefix="xdg">fontconfig</cachedir>
Fontconfig warning: no <cachedir> elements found. Check configuration.
Fontconfig warning: adding <cachedir>/var/cache/fontconfig</cachedir>
Fontconfig warning: adding <cachedir prefix="xdg">fontconfig</cachedir>
Fontconfig warning: no <cachedir> elements found. Check configuration.
Fontconfig warning: adding <cachedir>/var/cache/fontconfig</cachedir>
Fontconfig warning: adding <cachedir prefix="xdg">fontconfig</cachedir>
Fontconfig warning: no <cachedir> elements found. Check configuration.
Fontconfig warning: adding <cachedir>/var/cache/fontconfig</cachedir>
Fontconfig warning: adding <cachedir prefix="xdg">fontconfig</cachedir>
# Opened file dialog
(Telegram:8607): Pango-WARNING **: 18:06:16.820: failed to create cairo scaled font, expect ugly output. the offending font is 'Open Sans 11'

(Telegram:8607): Pango-WARNING **: 18:06:16.820: font_face status is: file not found

(Telegram:8607): Pango-WARNING **: 18:06:16.820: scaled_font status is: file not found

(Telegram:8607): Pango-WARNING **: 18:06:16.820: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Open Sans 11', text='Recent'

(Telegram:8607): Pango-WARNING **: 18:06:16.825: failed to create cairo scaled font, expect ugly output. the offending font is 'Open Sans 11'

(Telegram:8607): Pango-WARNING **: 18:06:16.825: font_face status is: file not found

(Telegram:8607): Pango-WARNING **: 18:06:16.825: scaled_font status is: file not found

(Telegram:8607): Pango-WARNING **: 18:06:16.868: failed to create cairo scaled font, expect ugly output. the offending font is 'Open Sans Bold 11'

(Telegram:8607): Pango-WARNING **: 18:06:16.868: font_face status is: file not found

(Telegram:8607): Pango-WARNING **: 18:06:16.868: scaled_font status is: file not found

(Telegram:8607): Pango-WARNING **: 18:06:16.868: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Open Sans Bold 11', text='Name'

(Telegram:8607): Pango-WARNING **: 18:06:16.871: failed to create cairo scaled font, expect ugly output. the offending font is 'Open Sans Bold 15.83984375'

(Telegram:8607): Pango-WARNING **: 18:06:16.871: font_face status is: file not found

(Telegram:8607): Pango-WARNING **: 18:06:16.871: scaled_font status is: file not found

(Telegram:8607): Pango-WARNING **: 18:06:16.871: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Open Sans Bold 15.83984375', text='No results found'
Gtk-Message: 18:06:16.879: GtkDialog mapped without a transient parent. This is discouraged.

(Telegram:8607): Pango-WARNING **: 18:06:16.916: failed to create cairo scaled font, expect ugly output. the offending font is 'Open Sans Bold 11'

(Telegram:8607): Pango-WARNING **: 18:06:16.916: font_face status is: file not found

(Telegram:8607): Pango-WARNING **: 18:06:16.916: scaled_font status is: file not found

`

I've added a `# Opened file dialog` when I click on the file dialog. I've also attached the telegram log
[log.txt](https://github.com/telegramdesktop/tdesktop/files/2366592/log.txt)
