### ISSUE TITLE
Not transparent icon in KDE system tray

### ISSUE THREAD

**Issue by qg0** [telegramdesktop/tdesktop#5157]
Tdesktop version: 1.2.17
KDE Plasma Version: 5.13.4
KDE Frameworks Version 5.49.0
Qt Version 5.11.1
OS Version: Linux 4.18.5-1-default
OS Type: 64-bit

Not transparent icon in KDE's system tray. 
![image](https://user-images.githubusercontent.com/919099/45338869-a9f84f00-b5b9-11e8-87ae-ab16c479a1d8.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2230#issuecomment-252503713
