### ISSUE TITLE
You can't tell the difference between text and formatted link.

### ISSUE THREAD

**Issue by alivekenny** [telegramdesktop/tdesktop#5158]
### Steps to reproduce
1. Change theme to Veritas or similar one with contrast text bubbles.
2. Send link with text formating (Cmd+K)

### Expected behaviour
You clearly can tell the text from the link. Like in iOS app.

### Actual behaviour
You can't tell the text from the link. There is no underline or another signs that this is the link.

### Configuration
**Operating system:** macOS 10.13.6

**Version of Telegram Desktop:** 1.3.14

**Used theme**: Veritas

<img height="500" alt="iOS" src="https://user-images.githubusercontent.com/21039303/45343127-67367700-b5b9-11e8-9915-07b399b3e698.png">
<img height="500" alt="TD" src="https://user-images.githubusercontent.com/21039303/45343135-6e5d8500-b5b9-11e8-808c-f9aed3332958.png">

**Comment by john-preston** [comment]
Telegram Desktop shows links with color, not text decorations. So themes that give the same color to links and text are not good for this app :(

**Comment by alivekenny** [comment]
Yeah, I know. It looks ok for incoming messages: gray bubble, black text, blue link, but you can't really pick right color for blue bubble. I know, text underline is so 2005, but it does it's job here for iOS app. Maybe TD should get this too?

**Comment by john-preston** [comment]
@alivekenny Text decorations are not part of a theme (only colors and background are) and it won't look good in both day and night default themes. I guess some slightly different from white color should be found for links in such themes :(
