### ISSUE TITLE
[build error] functors.h line 24 #Expression must have a constant value#

### ISSUE THREAD

**Issue by Jongkeun** [telegramdesktop/tdesktop#5159]
### Steps to reproduce
1.  Follow the [steps ](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md).
2. Change a start project to `Telegram`
3. Build

### Expected behaviour
I hope to build and start the program.

### Actual behaviour
it returns the error log.

### Configuration
**Operating system:**
Windows 10 64bit

**Version of Telegram Desktop:**
The last version of master branch.

**Used theme**:

<details><summary><b>Logs</b>:</summary>

![image](https://user-images.githubusercontent.com/33743343/45348264-2b1b0a80-b5e9-11e8-9866-4430f645fb4d.png)

</details>

I'd like you to help me with other errors as well.
If you wanna more information, tell me please.
Thanks.

**Comment by stek29** [comment]
What version of VS are you using?

**Comment by Jongkeun** [comment]
@stek29 
I'm using VS 2017 Pro version 15.8.2.

**Comment by Jongkeun** [comment]
It has the same errors after updating to 15.8.4.

**Comment by 17dengfeng** [comment]
me too

**Comment by maxh323** [comment]
I also had this error with 15.6.0, 15.6.7, 15.7.0, 15.7.6.
Everything went well with 15.8.5

**Comment by maxh323** [comment]
I updated online from VS15.7.6 to the latest and the error disappeared.

**Comment by Jongkeun** [comment]
@maxh323 Wow how did it?
I didn't make it even though I updated to 15.8.5.

**Comment by Brandhor** [comment]
try to delete all non git committed files or delete tdesktop and checkout again and then run gyp\refresh.bat, that's how I fixed it

**Comment by 23rd** [comment]
Outdated.
