### ISSUE TITLE
Closing window does not end process

### ISSUE THREAD

**Issue by AndydeCleyre** [telegramdesktop/tdesktop#516]
This is seen using tdesktop 0.7.17, kwin 5.2.0.1, plasma-framework 5.7.0 and plasma-workspace 5.2.0.

I do not have libappindicator-gtk{2,3} installed. I do not use the tray icon. I do not have any settings regarding the tray icon available.

Closing the window does not end the process.

**Comment by EmptyStackExn** [comment]
Why would it end ?

Telegram Desktop keeps running in the background and gives you some information with the tray icon: that's the way it works. The fact that libappindicator is installed or not does not change the fact that Telegram keeps running. If you do not agree with that, then you shoud fill a feature request for additional settings.

**Comment by AndydeCleyre** [comment]
The tray icon is optional. If the tray icon is not used, the process should end when the window is closed. Am I missing something here?

**Comment by EmptyStackExn** [comment]
I think I now understand what you mean. Telegram has two ways to show a tray icon depending on the system it is running upon : either `libappindicator` or `QSystemTrayIcon`. In the former, the tray is buggy on some systems and run apps without showing any icon... Dropbox had that problem in its previous versions. I think this is the case for you... Otherwise, I have no idea.

**Comment by AndydeCleyre** [comment]
The tray icon used to be optional -- is it not anymore? I went ahead and installed libappindicator-gtk3 and libappindicator-gtk2 (and all their dependencies) and relaunched telegram, but there's no tray icon and no tray-related option in the settings. Is that expected (the setting gone), or am I missing some dependency for that setting to appear?

**Comment by AndydeCleyre** [comment]
Related to #679.

**Comment by AndydeCleyre** [comment]
Fixed with 0.8.45
