### ISSUE TITLE
Option to disable autosave gifs

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5164]
When sending a gif , it adds to gif panel.
How to disable that auto add because it is hard to search old gifs?

**Comment by Tynach** [comment]
I feel that such an option would be nice, but in the meantime you can hover over a gif with the mouse, which causes a small 'x' to appear in the top right corner of it. Clicking that lets you remove it from your sidebar.

**Comment by SmartManoj** [comment]
error

**Comment by RememberTheAir** [comment]
This issue is an API issue as it's the server that saves the GIF to your saved GIFs catalogue every time you send one

**Comment by SmartManoj** [comment]
Can't we auto-remove?

**Comment by RememberTheAir** [comment]
Yes, but tdesktop is an official app and as such it should behave accordingly to how the api is designed to be used

**Comment by SmartManoj** [comment]
@Aokromes then we have to add api-issue for lot of issues now

**Comment by Tynach** [comment]
Personally, I feel this wouldn't be as much of an issue if you could view more gifs in the sidebar. It's not like they aren't stored by the server; I frequently clear out some gifs by clicking the 'x' button on them, and that lets me see gifs I uploaded but had fallen off the list pop back up on it (though I have to send a gif to get it to update).

This works even if in the meantime I had freshly installed Telegram on a new computer (or OS install), so it's definitely not local caching.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
