### ISSUE TITLE
Restrictive policies under debugging

### ISSUE THREAD

**Issue by jackstowart** [telegramdesktop/tdesktop#5166]
I get api_id and api_hash from telegram.org and update them in the source code.
but every time i change the source code(for custom ui purposes) i have to login again.
when i repeat login process several times, finally "Too many tries. please try again later" appear and can't login again for 24 hours!
surly i am misunderstanding about some debugging issue. help please!

build Telegram project also takes a long time!
is it normal?!

**Comment by jackstowart** [comment]
nobody can help me?!
my issue is just about debugging!
I think it's simple but is out of my vision! help me please!

**Comment by stek29** [comment]
Session should not reset on restart, and it has never happened to me

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
