### ISSUE TITLE
Naming of exported media files

### ISSUE THREAD

**Issue by kardeslik** [telegramdesktop/tdesktop#5167]
Hey there,
Media files (photo, video and voice) are named with index but this isn't that much useful when you look at the files from Finder. I would want to know the media date without looking at the messages at html files.
I've checked the commits and saw that naming has been changed with this  [commit](https://github.com/telegramdesktop/tdesktop/commit/a253d34c008e7680ab968df149307b79482430b9). Is there any specific reason or technical barrier for naming with media date?
Can you somehow add the media date to the file naming?
Thanks.

**Comment by john-preston** [comment]
@kardeslik Just that ordering looked a bit better.

**Comment by kardeslik** [comment]
@stek29 Sure I can. I may also try to edit source code and build it locally but it would be good if app itself provides this by default.
