### ISSUE TITLE
Command-line option to open in background mode

### ISSUE THREAD

**Issue by CLOVIS-AI** [telegramdesktop/tdesktop#5168]
This is not an issue or bug report so I'll omit any fields that do not make any sense here.

When the app's window is closed, some kind of process continues to run in the background to check for notifications, etc. I'd like to run this by itself, with a command-line option for example.

The use-case is: "Allow to put the app in the list of apps launched at startup, but without opening a window or anything. Just start it silently in the background and check for notifications, so I can load the window only if I really want to".

The "launch at startup" should be opt-in. For my part, I'd be fine with a single command-line option to do it and configure the system myself.

### Configuration
**Operating system:** Debian 9

**Version of Telegram Desktop:** 1.3.14

**Used theme**: Night mode

**Comment by stek29** [comment]
`-startintray`.

See #1380 #1820 #948 #422 #407.
