### ISSUE TITLE
IDs for chats / message authors

### ISSUE THREAD

**Issue by tp971** [telegramdesktop/tdesktop#5169]
When exporting in JSON format, neither chats nor message authors have a unique identifier:
* Chat objects in `chats.list[*]` only have `name` containing the display name, which is not unique and can be changed.
* Message objects `chats.list[*].messages[*]` only have a `from` field containing the display name of a user, which is not unique and can be changed.

Suggestions:
* Add a field like `id` to chat objects in `chats.list[*]`.
* Change the `from` field from string to an object containing a user id and a username (if set) and the displayname.

**Comment by ShadowJonathan** [comment]
I would like to add to this and say that a singular chat also does not have an option to export to JSON *at all*, and the HTML that comes out of it has a structure that's not very easily scrapable.

I'm going to make an issue of it's own out of it, i just think it's mention-worthy here.

**Comment by ShadowJonathan** [comment]
@tp971, fixed with #5426? Or are there other fields that would need to be added?

**Comment by Aokromes** [comment]
no answer after near a year, closing.
