### ISSUE TITLE
Could not send an empty file Fedora 28(Telegram does not see all the folders/files)

### ISSUE THREAD

**Issue by Melvasul** [telegramdesktop/tdesktop#5170]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
When drag and drop a file or when searching for a file Telegram should do/see it and send.

### Actual behaviour
Telegram does not do it
For drag and drop: Error could not send an empty file
For searching: Telegram does not see folders

![screenshot from 2018-09-19 10-23-25](https://user-images.githubusercontent.com/11297488/45740895-9753ca80-bbf6-11e8-8c79-80e3aa4ae460.png)

### Configuration
**Operating system:**
Fedora 28
**Version of Telegram Desktop:**
V.1.3.14
**Used theme**:
None
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@Melvasul Are they some sort of network folders or smth?

**Comment by Melvasul** [comment]
No, they are a simple folder I've created manually(for example where I store my local data and so on).
One strange thing is that if I take one file from the Document folder(e.g.) and put it (where the Document folder is) Telegram will still not recognise/see it

**Comment by john-preston** [comment]
@Melvasul The file browsing is handled by the system file dialogs, I have no idea how this can happen and they can be not displayed :( I didn't see anything like that when I was testing on various Linux environments.

**Comment by Melvasul** [comment]
It's strange because I remember that it worked perfectly with my previous F28 installation(same laptop, just had to reset the installation)

**Comment by xvitaly** [comment]
@Melvasul Telegram Desktop from Flatpak?

**Comment by john-preston** [comment]
@xvitaly Wow. So this is intended — an app version that can't select attachments from your home folder? How does anyone use it? %)

**Comment by Melvasul** [comment]
It worked perfectly by enabling the rommon/telegram (and so on)
It's strange because I used flatpak telegram before and did not remember this problems :/

**Comment by xvitaly** [comment]
> Wow. So this is intended — an app version that can't select attachments from your home folder?

http://docs.flatpak.org/en/latest/basic-concepts.html#sandboxes

**Comment by mahmoudxp** [comment]
I have same problem in ubuntu, I copied files in document folder but couldn't send pdf files to telegram channel and have a error msg that "could not send an empty file: ..." . please help

**Comment by Aokromes** [comment]
read the post over your.
