### ISSUE TITLE
Telegram grop with 28k+ user deleted. 

### ISSUE THREAD

**Issue by Peace4life** [telegramdesktop/tdesktop#5171]
Hello, we have a big issue with our telegram group. We lost our telegram group, we had around 28k+ users in our group. We are not able to find the group and not accessible. What can be the reason for the sudden disappearance of the group? 

Someone said that Creator can delete the account, but is it possible to delete a group with more than 25k+ members? 

We tried a demo, tried deleting a group with more than 1k user and we are not able to delete it. It says: Method: channels.deleteChannel
Result: {"_":"rpc_error","error_code":400,"error_message":"CHANNEL_TOO_LARGE"}

Please help me to retrieve the group. How can we retrieve the group?

**Comment by stek29** [comment]
Creator can delete group with more than 1k members via support.

Sorry, this is definitely not the right place to ask a question like this.
If it's "your" group and you know the creator, and he has not contacted support to request group deletion, try to contact support.

Groups are sometimes deleted by TG, but only when they violate ToS.
