### ISSUE TITLE
[Future Request]

### ISSUE THREAD

**Issue by yochem** [telegramdesktop/tdesktop#5173]
### Configuration
**Operating system**: macOS

**Version of Telegram Desktop**: 4.3.4.139634 Stable

**Used theme**: Day / Dark Mojave

Hey Guys,

Just a quick question: on iOS telegram has the function to automatically switch to a dark theme in the night (a certain time, sunset and sunrise...). Is it possible to provide this option in the desktop version, too?

Would be awesome!

**Comment by stek29** [comment]
>  4.3.4.139634 Stable

That's not telegram desktop.
And Scheduled night mode is already available in the app you're using: Settings, Appearance, Auto-Night mode.
