### ISSUE TITLE
The language change confirmation dialog should use the current language rather than target language

### ISSUE THREAD

**Issue by Cladis** [telegramdesktop/tdesktop#5174]
### Steps to reproduce
1. Go to settings
2. Press change language
3. Select language other than current
4. See a confirmation dialog

### Expected behaviour
The dialog from step 4 uses your current language (i.e. the language you used to navigate to the menu)

### Actual behaviour
The dialog from step 4 shows text in the language you have selected. Meaning that if you have selected a wrong language by mistake you cannot even understand the dialog text.

### Configuration
**Operating system:**
Ubuntu Mate 18.04

**Version of Telegram Desktop:**
1.3.14

**Used theme**:
Doen't influence this

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Cladis** [comment]
Hmm, that is a confusing feature then.

I don't have a reliable source for this, but from my observation many users do not know that Esc or clicking outside a confirmation box are possible ways to close a pop-up. I can very much imagine someone wanting to select Portuguese and missclick to see some text and buttons in Korean instead.

**Comment by john-preston** [comment]
@Cladis Perhaps you're right.

**Comment by stek29** [comment]
Maybe Accept should be in Target language, and cancel should be in Old language?
