### ISSUE TITLE
Telegram Desktop does not run on Xubuntu 18.04

### ISSUE THREAD

**Issue by Lonerider2010** [telegramdesktop/tdesktop#5175]
### Steps to reproduce
1. Download tsetup.1.3.14.tar.xz from https://telegram.org/dl/desktop/linux.
2. Uncompress tsetup.1.3.14.tar.xz.
3. Start with ./Telegram

### Expected behaviour
Telegram Desktop should start.

### Actual behaviour
Nothing happens, no start of Telegram Desktop, no error message, it just "waits",
so it doesn't get back to the prompt.

### Configuration
**Operating system:**
```
uname -a:
Linux 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
``
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

**Version of Telegram Desktop:**
1.3.14 according to the downloaded archive.

**Used theme**:
None.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by xdpirate** [comment]
Have you tried one from ubuntu apt?
`sudo apt install telegram-desktop`
Works great for me on both Xubuntu and Kubuntu.

**Comment by Lonerider2010** [comment]
Yes, I tried this, but that didn't change the result.
As mentioned before, my problem is that I don't get any error message, so I don't know what's going wrong.

**Comment by Aokromes** [comment]
works for me (TM) both downloaded from telegram webpage or self compiled.

**Comment by stek29** [comment]
Maybe it's fontconfig again?

**Comment by Lonerider2010** [comment]
Don't know why, but telegram is working now.
@stek29: nothing to do with fontconfig.
Finally I found the log file at ~/.local/share/TelegramDesktop/log.txt (see attachment).
[log.txt](https://github.com/telegramdesktop/tdesktop/files/2409567/log.txt)
So there is one error message: Error: failed to load 'gdk_x11_drawable_get_xdisplay' function!
What does that mean?
And there are 395 (!) Lang Error messages. Is that the default case?

**Comment by Lonerider2010** [comment]
Another question: while running telegram-desktop and watching the log file, I got several messages like:
`Message Info: bad message notification received (error_code 16) for msg_id = <19-digit number>, seq_no = <number>`
So what's going wrong there?

**Comment by Aokromes** [comment]
Test after https://github.com/telegramdesktop/tdesktop/commit/8ee958bfa08b2ba87cffaf8de4b65b6890e59ea3

**Comment by Aokromes** [comment]
maybe this was the long startup fixed few months ago? @Lonerider2010 can you try on 1.5.5 and close ticket if working?

**Comment by zertap** [comment]
I just experienced this same problem.
Not sure what happened. But I manged to work around it.

From ~/.local/share/TelegramDesktop I viewed the newest log_startN.txt file
The log showed a line that it was connecting to local socket under /run/user/
```shell
zertap@ithaqua ~ % ls -lha "/run/user/xxxx/xxxxx-{xxxxx-xxxx-xxxx-xxxx-xxxxxx}"
srwxr-xr-x 1 zertap 1303400513 0 touko  15 08:58 /run/user/xxxx/xxxxx-{xxxxx-xxxx-xxxx-xxxx-xxxxxx}
```
I removed the file, and after that Telegram started properly.
