### ISSUE TITLE
Paused music starts to play after call

### ISSUE THREAD

**Issue by marusak** [telegramdesktop/tdesktop#5177]
### Steps to reproduce
1. Use music player to play music, pause it
2. Accept call
3. Finish call

### Expected behaviour
Music will not start playing as it was paused before the call

### Actual behaviour
Music starts to play

### Configuration
**Operating system:**
Fedora 29, Gnome, music player is Rhythmbox

**Version of Telegram Desktop:**
telegram-desktop-1.3.16-1.fc29

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3854
