### ISSUE TITLE
Don't show notifications for pinned messages in muted channels

### ISSUE THREAD

**Issue by b1rdex** [telegramdesktop/tdesktop#5178]
### Steps to reproduce
1. Join cnahhel
2. Mute it
3. Wait for "message pinned" event

### Expected behaviour
Muted channel should not provide any notifications at all.

### Actual behaviour
"Message pinned" notification recieved

### Configuration
**Operating system:** win 10

**Version of Telegram Desktop:** 1.3.14

**Comment by RememberTheAir** [comment]
Duplicate of #1864, if with "channels" you are talking about group chats. Pinned messages in channels use the channel's notification settings

**Comment by b1rdex** [comment]
@RememberTheAir ty. Yes, I meant group chats.
