### ISSUE TITLE
Telegram 1.3.16 alpha eat 1 Gb RAM on Linux

### ISSUE THREAD

**Issue by tim77** [telegramdesktop/tdesktop#5179]
### Steps to reproduce
1. Install Telegram 1.3.16 alpha.
2. Run Telegram for 10 hours.

### Expected behaviour
Should use much less RAM as before.

### Actual behaviour
Telegram continuously eat more ram. 1 Gb for 10 hours. And continue growing.
![telegram ram](https://user-images.githubusercontent.com/5614476/45911297-04937580-be1a-11e8-93b7-ebc616b68071.png)

### Configuration
**Operating system:** Fedora 29 Workstation x86_64.

**Version of Telegram Desktop:** 1.3.16 alpha.

**Used theme**: Dark.

**Comment by john-preston** [comment]
@tim77 Please check the latest stable to be sure it uses more than it.

**Comment by Aokromes** [comment]
#2464
