### ISSUE TITLE
Telegram icon is incorrect under KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [telegramdesktop/tdesktop#5180]
### Steps to reproduce
1. start KDE Plasma Wayland sesison on some linux system
2. install and open Telegram Desktop
3. 

### Expected behaviour
Telegram icon should be visible in title bar and task manager.

### Actual behaviour
Both title bar and task manager show Wayland generic icon, as you can see in my screenshot.
### Configuration
**Operating system:**
Operating System: Arch Linux 
KDE Plasma Version: 5.13.90
Qt Version: 5.11.2
KDE Frameworks Version: 5.50.0

**Version of Telegram Desktop:**
telegram-desktop 1.3.14-1

![telagram](https://user-images.githubusercontent.com/15967631/45919047-1e5aaa00-be66-11e8-987c-4a2d343b98f8.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4750#issuecomment-392605978 ?

**Comment by nortexoid** [comment]
> Telegram already runs natively under Wayland on my system
> Just its icon is incorrect.

Are you sure? Can you check xlsclients to see whether telegram is listed?

**Comment by glaubersm** [comment]
xwininfo command indicates that Telegram runs under xWayland.
Also when I force X11 with "QT_QPA_PLATFORM=xcb telegram-desktop", the icon is correct.

![telegram](https://user-images.githubusercontent.com/15967631/46287238-3c0bcb80-c558-11e8-8b02-d5268e07de76.png)

**Comment by nortexoid** [comment]
Using the arch packages telegram-desktop and telegram-desktop-bin (AUR), xlsclients shows that they are running non-natively through xwayland. Anyway, telegram-desktop doesn't even work because of https://github.com/telegramdesktop/tdesktop/issues/4717

**Comment by Johnnynator** [comment]
The application icon on wayland is set after the one that is set in the desktop file that is named '${domain-name}.${binary-name}.desktop'. So in this case it searches for a `telegram-desktop.desktop` but there is only a `.desktop` file without the dash and therefore it won't find a icon.

Solution: have matching .desktop and bin names.
