### ISSUE TITLE
High CPU Usage after PC is resumed from standby

### ISSUE THREAD

**Issue by Hades32** [telegramdesktop/tdesktop#5181]
### Steps to reproduce
1. Telegram is running
2. Suspend PC
3. Resume PC

### Expected behaviour
I shouldn't notice anything

### Actual behaviour
CPU on a Surface Notebook i5 is ~50% and severly slows down the whole resume process

### Configuration
Win 10 uptodate

**Version of Telegram Desktop:**
1.3.14

**Used theme**:
Night Mode on

**Comment by stek29** [comment]
What if PC stays in standby for a short amount of time?

**Comment by Hades32** [comment]
Just tested. It seems, like there is a minimum time the PC has to be in standby for the issue to occur. Only a few seconds don't seem to trigger it.

**Comment by stek29** [comment]
@Hades32 probably it's just fetching all the updates from last time it connected tg servers.
Does just restarting the app help?

**Comment by Hades32** [comment]
It eventually settles down, so maybe that's it, but I really don't see why that would need such an extreme amount of CPU on an i5. And it takes rather long even if only a few (text only) updates occurred.

**Comment by nickaein** [comment]
@Hades32 How long it takes until it settles down? Can you also check whether Telegram has high IO disk usage?

**Comment by mcrapts** [comment]
I'm also experiencing this issue. It takes minutes for my laptop to resume from standby just because of Telegram. Everything is slowed down.

**Comment by N8Z7JMYLU** [comment]
Does this issue need any more details for it to be fixed? It still persisting with version 1.4.8.0, the time to settle down to normal usage is taking 5+ minutes

**Comment by AndreyRa** [comment]
Same behaviour last half of year. Already tried to re-install Telegram without any effect.

**Comment by smfilipe** [comment]
The problem still exists in version 1.5.9
My PC becomes unusable for at least 2 minutes on resume if I have left telegram open during sleep, otherwise my PC needs about 6-8 seconds to resume.
The priority of this bug should be increased.

Meanwhile, can somebody recommend an alternative desktop app for telegram?

**Comment by nickaein** [comment]
You should provide more details so this issue can be tracked down:

**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)

**Comment by smfilipe** [comment]
It's the version 1.5.9 as told in previous comment and it's the same conditions as the first reporter.

**Operating system:** Windows 10 uptodate
Version of Telegram Desktop: 1.5.9
Used theme: Default theme

**Comment by AndreyRa** [comment]
**Operating system:** Windows 10 Version 10.0.17763.253
**Version of Telegram Desktop:** 1.5.11
**Used theme**: Standard
I providing you screenshot of this behaviour from TaskInfo task manager. You can see which thread consumpts a lot of CPU. It some thread that is related with WINMM.dll ! PlaySoundW calls. 
![telegram after himernation](https://user-images.githubusercontent.com/4364366/52287941-31d16200-297c-11e9-94b7-dc95e304bce1.png)

**Comment by ZXByteman** [comment]
The same issue on Telegram 1.5.15 and up-to-date Windows 10.
After resume from sleep/hibernate Telegram App consumes almost 100% of CPU resources. If I close and reopen app just after exiting from sleep or hibernate, issue does not appear.
Hardware: Dell Venue 11 7140, it is getting hot and slow, this is how I've detected this issue happen.

**Comment by AndreyRa** [comment]
1.5.15 Same behaviour. The only app that drains down battery of my notebook at startup. Very dissapointed.
![image](https://user-images.githubusercontent.com/4364366/54461711-753e9d80-477e-11e9-9ee0-4911a2279997.png)

**Comment by damat** [comment]
This has to fixed. I'm tired of relaunching Telegram each time after sleep!

**Comment by ZXByteman** [comment]
Unfortunately this issue still exists in 1.6.3 version.

**Comment by smfilipe** [comment]
The Telegram client is unusable because of this issue.
The alternatives are Telegram Web or Unigram. For now, I've replaced Telegram client with Unigram in Windows.

**Comment by AndreyRa** [comment]
Thank you damat for your comment! This gave me the idea of how to automate it.
I have prepared workaround solution that just kills telegram process and runs it again in case of return from hibernate. Zip-archive contains the definition of the task scheduler and a bat-file for the automatic installation of this task.

[KillTelegram.zip](https://github.com/telegramdesktop/tdesktop/files/3051372/KillTelegram.zip)

1. Just unzip file, and run "setup (RUN AS ADMINISTRATOR).bat" with an administrator rights.
2. Please check that task with the name "Kill Telegram After Hibernate" have appeared in the scheduler list.
3. This task must be run from the same username as yours, please check this carefuly.
4. If your user account doesn't have admin rights this task would't work. Please inform me if you have such situation.

**Comment by damat** [comment]
You are Russian, Andrey, aren't ya? ;) I'll give it a try, thanks!

**Comment by eyehol3** [comment]
I'm experiencing the same issue, that's dissapointing

**Comment by sabuty** [comment]
Same issue here. Sounds are disabled in the Telegram Desktop App, which makes the calls to PlaySoundW even more curious.

**Comment by GitLad** [comment]
Are you gonna fix it, it's not a rocket science? Stop asking for version / windows too, it's the same as everyone already reported 10+ times.

It's not about even fixing a specific bug, it's about how aggresive you let telegram be, use up unlimited resources, you should rewrite the code for processing and never allow it reach such bottlenecks.

**Comment by nickaein** [comment]
> Are you gonna fix it

There is no "you". This is an open-source project with contributors that are mostly volunteers.

**Comment by ilya-fedin** [comment]
> you should rewrite the code

Let's rewrite it, do a good deed for everyone!

**Comment by GitLad** [comment]
> > Are you gonna fix it
> 
> There is no "you". This is an open-source project with contributors that are mostly volunteers.

Sherlock, was obvously talking to the active contributors, so yes ofc there is a "you".

Especially those who get paid to do nothing but oversee PRs.

If you can't do anything then don't get engaged with the project, it's a good project and some org would take it under their wing gladly, once wannabe contributors dwindle down.
