### ISSUE TITLE
Preview Stickers on hover, not on lmb hold

### ISSUE THREAD

**Issue by Silicomancer** [telegramdesktop/tdesktop#5184]
### Steps to reproduce
1. Try to send a sticker from an unknown set

### Expected behaviour
When selecting a sticker, I would like to see a bigger version of the stickers when hoovering the mouse cursor above the sticker thumbnails. This would help a lot to avoid sending wrong stickers.

### Actual behaviour
When selecting a sticker from a sticker set, I can only see the small thumbnails. It happens very frequently that I send the wrong sticker because the thumbnails have been too small to see recognize their actual meaning. Please note that I have seen this happen to over people as well. This is very annoying.

### Configuration
Linux
Current Version

**Comment by Johnnynator** [comment]
You have to hold right click to get the preview.

**Comment by Silicomancer** [comment]
Right click and hold? With the right mouse button? Doesn't have any effect here.

**Comment by Johnnynator** [comment]
Sry. I meant left click.

**Comment by Silicomancer** [comment]
Ahaaaaa. That works! Thanks a lot. 
However, that is very uncommon. I would have never figured that out. Why not simply hoovering?

**Comment by Johnnynator** [comment]
Idk. This reassembles the behavior you have on mobile platforms. But I agree a simple preview on zoom would be way more intuitive for a desktop platform.

**Comment by Silicomancer** [comment]
Yes, I agree. Definitely. Without doubt. :-)

**Comment by Aokromes** [comment]
#4117

**Comment by Silicomancer** [comment]
No, I definitely have not lost interest. I lost trust, but not interest.

**Comment by Silicomancer** [comment]
This is ridiculous. I refuse to play this game.
