### ISSUE TITLE
[Feature request] Link for channel tag search

### ISSUE THREAD

**Issue by Andrey96** [telegramdesktop/tdesktop#5187]
### Steps to reproduce
1. Write a message "@themes#dark"
2. Click on the created link

### Expected behaviour
Whole message becomes a link, which is when clicked opens "themes" channel and searches for "#dark".

### Actual behaviour
Only "@themes" becomes a link, which opens "themes" channel without searching anything.

### Configuration
**Operating system:** Ubuntu 16.04

**Version of Telegram Desktop:** 1.3.14

**Used theme**: Default

**Comment by john-preston** [comment]
@Andrey96 Those links are managed server side for all apps, so I can't implement that in tdesktop only :(

**Comment by Andrey96** [comment]
Okay, thank you.

**Comment by SmartManoj** [comment]
Why don't we make two server side calls continuously?
