### ISSUE TITLE
Displaying notifications on main screen

### ISSUE THREAD

**Issue by david1602** [telegramdesktop/tdesktop#5188]
This is not quite a bug report so I skipped the template.

I'm fairly certain though not 100% sure that prior to reinstalling my Windows, I was able to get Telegram to show up its own notifications (not using Windows notifications) on my primary display. However, currently it displays the notifications on the display the telegram window is on. Is there any way around that?

**Comment by Aokromes** [comment]
afaik, nohttps://github.com/telegramdesktop/tdesktop/issues/3681
