### ISSUE TITLE
[Feature request] Lock screen and unlock with pin

### ISSUE THREAD

**Issue by fenandosr** [telegramdesktop/tdesktop#5189]
**Desired behavior:** A lock screen appears chen you click "Lock screen" (or `Ctrl + L`).

This should consider a pin for handling the unlock part.

**Operating system: Debian testing buster**

**Version of Telegram Desktop: 1.3.14**

**Comment by john-preston** [comment]
@fenandosr You have a local passcode option in settings.

**Comment by fenandosr** [comment]
Ok, sorry... That's what I wanted.
