### ISSUE TITLE
`close`, `minimize`, `maximize` buttons disappear

### ISSUE THREAD

**Issue by saitam1** [telegramdesktop/tdesktop#5190]
I am on Ubuntu 18.04.1 and sometimes the `close`, `minimize`, `maximize` buttons disappear:
![tel](https://user-images.githubusercontent.com/23245678/46070665-a7cbee00-c17e-11e8-90f5-8040e65f511f.png)
I am using Telegram version 1.3.14

**Comment by Aokromes** [comment]
this bug is still valid? maybe it was related to some already fixed memory leaks.

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
