### ISSUE TITLE
Hashtag cloud per chat

### ISSUE THREAD

**Issue by majioa** [telegramdesktop/tdesktop#5191]
### Expected behaviour
Add to a share resources page (or may be to another page) of a chat, the subpage with name "Tag cloud" (or may be "Hashtag cloud") , which will show all the hashtags whenever sent to the chat by any of people, and allow to search messages containing the selected hashtag.

### Actual behaviour
There are no hashtag cloud in the app.

### Configuration
**Operating system:**
linux

**Comment by RememberTheAir** [comment]
The API doesn't allow to fetch all the hashtags used in a chat, so this is technically impossible

**Comment by majioa** [comment]
@RememberTheAir I believe that is possible on client side either, just parse all presented messages and, collect tags, that is simplest way to do that without api. And the question, who does accept questions and proposals about api?

**Comment by majioa** [comment]
where is in-app support?
