### ISSUE TITLE
New update on Mac removes the touch bar typing suggestions?

### ISSUE THREAD

**Issue by embluk** [telegramdesktop/tdesktop#5192]
The new update on OSX removes the typing suggestions because the app now supports the touch bar with more features but I found the typing suggestions useful. Is there anyway to get that back?

**Comment by john-preston** [comment]
@embluk I think you’re talking not about Telegram Desktop but about another macOS Telegram app.

**Comment by embluk** [comment]
@john-preston This repo is used to build for macOS, so is it not this one? The new update 4.4 adds touch bar features but removes the old typing suggestion box that use to show there?

**Comment by john-preston** [comment]
@embluk There are two apps for macOS. This one is Telegram Desktop, you can try it from https://desktop.telegram.org. Current version is 1.3.14 (stable) and 1.3.17 (beta).

**Comment by stek29** [comment]
You can report this in https://t.me/macswift.

**Comment by embluk** [comment]
@stek29 Is there not a GitHub for the MacOS version?

**Comment by stek29** [comment]
@embluk https://github.com/overtake/TelegramSwift
