### ISSUE TITLE
Proper transparent png images handling in chat window

### ISSUE THREAD

**Issue by DanyGee** [telegramdesktop/tdesktop#5194]
### Steps to reproduce
1. Open TG
2. Select a png image with transparency in it
3. Send it in chat as image (not as document)

### Expected behaviour
PNG transparency should be preserved 

### Actual behaviour
Transparency gets replaced by black or white color

### Configuration
**Operating system:**
All

**Version of Telegram Desktop:**
All

**Used theme**:
Default

I couldn't find any satisfying answer why TG can't preserve transparency while sending png with alpha channel as an image.
Can you explain it?
Will it be possible in the future perhaps?

**Comment by john-preston** [comment]
@DanyGee "Send as image" is there in API for sending photos from mobile originally, it supports only JPEG format, is compressed and can't have transparency. To preserve transparency you'll have to send your file as a document.

**Comment by DanyGee** [comment]
Ok, thx for the explanation.
Any changes planned to this API, or changing the API itself for something more advanced, which will handle transparency?

**Comment by stek29** [comment]
Maybe you can use stickers?
