### ISSUE TITLE
Telegram Desktop does not remember window position after being minimized

### ISSUE THREAD

**Issue by WhoCares1337** [telegramdesktop/tdesktop#5195]
### Steps to reproduce
1. Have Windows 10 and Telegram Desktop
2. Attach Telegram Desktop to the left half of your screen
3. Minimize TD
4. Restore TD
5. TD is no longer attached to the left half of your screen but somewhere else(tm)
6. ????
7. PROFIT!!!

### Expected behaviour
TD should open its window where it was before it was minimized

### Actual behaviour
windows is restored somewhere else.

### Configuration
Windows 10 Pro

**Version of Telegram Desktop:**
1.3.14
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RememberTheAir** [comment]
Kind of related/duplicate of #4837 #4475 #4453 #1693 #1189

**Comment by WhoCares1337** [comment]
duplicate of #4837 #4475 #4453 #1693 #1189
sorry for the troubles...
