### ISSUE TITLE
The application ignores the "Always automatically download updates" checkbox

### ISSUE THREAD

**Issue by mkarnicki** [telegramdesktop/tdesktop#5197]
### Steps to reproduce
1. Get a new update notification
2. Choose the checkbox "Automatically download updates in the future blah blah"
3. Get another update notification

### Expected behaviour
Telegram should remember to download the updates in the background and not show the "new update" notification every single time there's an update.

### Actual behaviour
Telegram shows the update notification every single time when there's an update available, regardless if the checkbox was checked.

### Configuration
**Operating system:**
OS X 10.11.6

**Version of Telegram Desktop:**
4.4.14.0043

**Used theme**:
?

**Comment by RememberTheAir** [comment]
> OS X 10.11.6
> 4.4.14.0043

You are probably using the native MacOS client, report issues [here](https://github.com/overtake/TelegramSwift)

**Comment by mkarnicki** [comment]
You're right, sorry.
