### ISSUE TITLE
[Feature Request] Shortcut - End key scrolls chat to the bottom

### ISSUE THREAD

**Issue by ThigSchuch** [telegramdesktop/tdesktop#5198]
### Steps to reproduce
1. Scroll some chat up.
2. Press End key.
3. Goes to the bottom.

### Actual behaviour
Nothing.

Open: github.com/telegramdesktop/tdesktop/issues/4699
But without Go to the First, kind of useless.

**Comment by RememberTheAir** [comment]
> Open: github.com/telegramdesktop/tdesktop/issues/4699 but without Go to the First, kind of useless

This issue is still a duplicate tho, this feature has been suggested (and has been discussed by some people) in the issue you linked (which is still open)
