### ISSUE TITLE
Punctuation (Spanish language), tilde, etc. do not work. (Linux)

### ISSUE THREAD

**Issue by cesvlc** [telegramdesktop/tdesktop#52]
á é í ó ú ü can not be written from the keyboard, vocal appear without the tilde / dieresis.

**Comment by sadalsuud** [comment]
I have this problem, but I installed ibus and into settigns manager -> language support and there select option: key board input method system : Ibus.  The daemon ibus should be running too. 

Yo tenía este problema, pero instalé ibus y luego fui en las configuraciones del sistema -> soporte de lenguajes, y hay una opción abajo que dice: método de entrada del teclado, y se selecciona Ibus. 

Xubuntu 16.04 
Telegram 0.9.51

And fine. 
Y listo ... todo bien.

**Comment by Bestulo** [comment]
I have this problem right now and I'm not sure how to solve it on Debian.
