### ISSUE TITLE
Feature Request: Let admins of chats to assign replies

### ISSUE THREAD

**Issue by okunev** [telegramdesktop/tdesktop#5200]
Any crowdy chat starts being messy without a proper structure.

Currently, the only way to maintain the structure of a conversation is to **ask members to use reply** function and ban if they don't. This is really violent. But if admins could drag replying messages to those which were replied, it allows to clean the conversation quickly.

![screen shot 2018-09-27 at 17 35 52](https://user-images.githubusercontent.com/3657051/46153415-cb289300-c27b-11e8-91d5-4a41ca5cede0.png)

**Comment by stek29** [comment]
First of all, there's no way to add reply to a message which was already sent.
And there is no way to allow admins to edit other users' messages.
