### ISSUE TITLE
Abnormal system resources usage

### ISSUE THREAD

**Issue by alsoGAMER** [telegramdesktop/tdesktop#5202]
### Actual behaviour
CPU usage and RAM out of normal, lag consistent throughout the application, start times that go over 1/2 minutes...

### Configuration
[Neofetch screenshot](https://i.imgur.com/FkyHlxR.png)

**Version of Telegram Desktop:**
1.3.17 beta

**Used theme**:
[DarkOrange](https://t.me/darkorangetheme/97)

**Other screenshot**
[System resources usage with tdesktop app open](https://i.imgur.com/b5URTDZ.png)
[System resources usage without tdesktop](https://i.imgur.com/Es2vqC1.png)
[System resources usage by tdesktop during start](https://i.imgur.com/AiVZa8y.png)

**Comment by john-preston** [comment]
@Feder1co5oave What does local storage box in Settings -> Advanced show you? Are there 44k files mentioned? If no, perhaps those are old cached files (from the old system, that were not tracked properly) and perhaps they're being deleted one by one..

**Comment by john-preston** [comment]
@Feder1co5oave The old cache was writing them indefinitely until logout or manual clearing in settings. And if you reinstall the app on an older version or somehow else forgot the authorization they just leaked.

Yes the left 3k (most of them) could be from old multiple profiles usage.

**Comment by Feder1co5oave** [comment]
Good to know, thanks!

**Comment by Aokromes** [comment]
In case someone knows how to fix, debug build 1.8.13 running under ubuntu linux x64

https://gist.github.com/37b7ee627100c703518b6586a1ed9713
