### ISSUE TITLE
The font become bold on Mac

### ISSUE THREAD

**Issue by smcdl** [telegramdesktop/tdesktop#5205]
I found every is bold. including group name and chat window and message box. It's too ugly.
My system is MacOS Mojave.

**Comment by john-preston** [comment]
@smcdl Cam you provide a screenshot?

**Comment by Floens** [comment]
In macOS Mojave subpixel font anti-aliasing seems to be removed. While all text in the OS does look different, the text in telegram desktop looks extremely different, almost bold. See the attached screenshot.

https://mjtsai.com/blog/2018/07/13/macos-10-14-mojave-removes-subpixel-anti-aliasing/

![telegram_macos_bold_font](https://user-images.githubusercontent.com/1012578/46255967-72880e80-c4a4-11e8-958e-6c312a4b629c.png)

**Comment by dketterer** [comment]
You may want to try [reenable subpixel antialiasing](https://www.howtogeek.com/358596/how-to-fix-blurry-fonts-on-macos-mojave-with-subpixel-antialiasing/)

**Comment by dardub** [comment]
Will this be addressed in a future release for users that may not be familiar with finding bugs in github?

**Comment by top4ek** [comment]
Got same in ArchLinux.

**Comment by dielsonsales** [comment]
@dketterer's answer fixed it for Catalina as well.

**Comment by ilya-fedin** [comment]
According to https://bugreports.qt.io/browse/QTBUG-68824, it should be fixed since 1.9.0

**Comment by dielsonsales** [comment]
It's worth noticing this happens on the dark theme only (at least on Big Sur).
