### ISSUE TITLE
Inconsistent audio media support across platforms

### ISSUE THREAD

**Issue by mxa** [telegramdesktop/tdesktop#5209]
There is an issue with playing back audio files across platforms.

An .aif(f) dropped into a chat from Telegram Desktop on a Mac may play there inside the chat, but on Windows it opens in the application which is registered to handle the filetype, on Linux clicking on it will not do anything and on Android it will show the player and notification, but the playback will not start.

I think either Telegram should convert dropped audio files into a consistent format all platforms can play back internally or it should give the option what to do like when dropping images into the chat window. It should never just fail to play back like in the example of an .aif(f) on Linux and Android currently.

**Comment by john-preston** [comment]
@mxa On Linux I think I try to open it in a player, but system doesn't offer anything? Is that possible?

**Comment by mxa** [comment]
@john-preston if I start telegram from the terminal with` /usr/local/bin/Telegram/Telegram -- %u`
when clicking on the aiff file shared from a mac, i get this output:

```
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"                                           
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"                                           
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"                                           
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"                                           
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"                                           
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"                                           
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"                                          
Icon theme "Mint-X" not found.                                                                                                         
Icon theme "elementary" not found.                                                                                                     
Icon theme "gnome" not found.  
```

**Comment by mxa** [comment]
I think the issue on Linux is some problem with optimus/prime, not Telegram related. It however is a Telegram problem on Android, but @DrKLO has no open issue tracker.

**Comment by stek29** [comment]
> It however is a Telegram problem on Android, but @DrKLO has no open issue tracker.

Report it via in-app support.
