### ISSUE TITLE
Regular crashing since last update

### ISSUE THREAD

**Issue by Robadob** [telegramdesktop/tdesktop#5211]
### Steps to reproduce
Unknown, it's happened whilst doing various things (e.g. right clicking messages in a supergroup, it always seems to be in reaction to my interacting with the interface, rather than due to receipt of any specific messages), but Telegram has crashed upwards of 6 times over the past 2 days (since the update Friday evening). One new issue is that the full screen image viewer becomes stuck open (ESC worked to close it the first time, but i think it hasn't on other occasions), however that doesn't seem directly linked to the crashes.

### Expected behaviour
Telegram not crash

### Actual behaviour
Telegram freezes briefly, crashes. After reopened get a box that says it didn't close properly, looking for updates.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.4
**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
There's nothing obvious in log files, but I'll try and post logs next time it crashes.
</details>

**Comment by john-preston** [comment]
@Robadob Can you go to Settings -> Advanced and switch "Install beta versions" on? After that if it crashes and you relaunch, it should offer you to send a crash report. Please send it and write your "crash report tag" (will be in the sending report window) here.

**Comment by Robadob** [comment]
Thanks, will do.

**Comment by Robadob** [comment]
Your Report Tag: 51b7641d-120d-4c60-8634-6aa88e3c2ea8
Your User Tag: 572a2436c97c684e
```
ApiId: 2040
Assertion: Unexpected: Could not allocate! c:\projects\telegram\twin\telegram\sourcefiles\core\crash_reports.cpp:114
Binary: Telegram.exe
Launched: 30.09.2018 18:03:52
Platform: Windows
UserTag: 572a2436c97c684e
Version: 1004000

Google Breakpad caught a crash, minidump written in thread 19368
Minidump: 51b7641d-120d-4c60-8634-6aa88e3c2ea8

Backtrace:
18091899
18092080
27172530
2002137178
2002137130
```

**Comment by john-preston** [comment]
@Robadob I can't see this crash being sent. Can you see if there is a non empty "51b7641d-120d-4c60-8634-6aa88e3c2ea8.dmp" file in your "tdata/dumps" folder near Telegram.exe?

But this looks like a out of memory error. I'm interested what takes all the memory so fast in your case :(

**Comment by Aokromes** [comment]
think telegram is 32 binary, so allocating 2GB of ram will crash it

**Comment by Aokromes** [comment]
P.S:

"One new issue is that the full screen image viewer becomes stuck open (ESC worked to close it the first time, but i think it hasn't on other occasions), however that doesn't seem directly linked to the crashes."

I had this crashes because this on the previous version, with a bit of luck my crash reports can help preston to fix your issue.

**Comment by BoffinbraiN** [comment]
Same issue being experienced here, on Windows 7. 3-4 other friends reporting the same issue on Win 10.
All my recent dump files are also empty, but here are the IDs in case they help...

```
d3818a1f-46f6-4ece-a90e-bd8d7056c706
1e111b79-2a87-4ab7-90ca-e3232651f14f
931d69d2-3987-4abd-8a57-a0486e2fede6
c6173831-71ca-4147-88ff-6e9f4ac55720
```

Event viewer has this to say on the matter...

```
Faulting application name: Telegram.exe, version: 1.4.0.0, time stamp: 0x5bae3388
Faulting module name: Telegram.exe, version: 1.4.0.0, time stamp: 0x5bae3388
Exception code: 0xc0000005
Fault offset: 0x00103d08
Faulting process id: 0x2e70
Faulting application start time: 0x01d45a95ba86cb50
Faulting application path: B:\Program Files (x86)\Telegram Desktop\Telegram.exe
Faulting module path: B:\Program Files (x86)\Telegram Desktop\Telegram.exe
Report Id: 3f9fc390-c70c-11e8-a172-2c4d544e16f8
```

**Comment by Spokehedz** [comment]
I can get it to crash pretty consistently by looking up a GIF and scrolling quickly through the list, or by scrolling through a list of a very image/sticker/voice/gif/etc heavy chat. It seems to pop at about 1.7gb of memory.

Your Report Tag: 2e8e6d1e-2945-4b5c-905f-41377fdee323
Your Report Tag: 71fede41-48b6-4aa2-947c-769e0f7a651a

Your User Tag: ac307974b16051f4

**Comment by KarelWintersky** [comment]
Same issue. 

4-5 times per day: while scrolling chat, while message replying, while opening image. 
Send more than 10 crash reports.

Win7 Pro 64bit
12Gb RAM
v 1.4 28.09.18

**Comment by cuddle-cactus** [comment]
I too am having these crashes several times a day. I have also switched to the beta updates as it seems to allow me to send the crash reports but I am uncertain if any of it is getting through. It doesn't seem to change how often I have these crashed though.

Since I am uncertain if any of my reports get through, I figured I'd post one here to help.

It always seems to be when media is trying to load of some sort, from a sticker to an image to a gif, etc. This time specifically I was in the media viewer looking through images.

    Your Report Tag: ead1ee0e-52cb-4f34-9853-29c074a93d0c
    Your User Tag: 403f2779557b4b37

    ApiId: 2040
    Assertion: "!img.isNull()" c:\projects\telegram\twin\telegram\sourcefiles\ui\images.cpp:320
    Binary: Telegram.exe
    Launched: 07.10.2018 16:56:45
    Platform: Windows
    UserTag: 403f2779557b4b37
    Version: 1004000

    Caught signal 11 (SIGSEGV) in thread 12884

    Backtrace:
    5115771
    24049864
    23821276
    1968267972
    2011500409
    2011500356

    Google Breakpad caught a crash, minidump written in thread 12440
    Minidump: ead1ee0e-52cb-4f34-9853-29c074a93d0c

    Backtrace:
    5115771
    5115952
    14196402
    2011500409
    2011500356

**Comment by KarelWintersky** [comment]
Ну, я уже думаю, не откатиться ли на версию месячной давности. Все равно нужный мне функционал... не появляется.

Хочу табы - чтобы чаты и каналы были в разных вкладках. Говорят, это реализовано было вв каком-то клиенте, который не поддерживается уже два года. 
Хочу чтобы muted-чаты не прыгали наверх в списке при появлении в них сообщения. Иначе нахера я их мьютил?

**Comment by KarelWintersky** [comment]
I open other chat: 

Report tag: **aeda3399-13ca-4680-b55d-5628c9930361**
User tag: **4d93bdaa1ed43ad6**

```
ApiId: 2040
Assertion: "!img.isNull()" c:\projects\telegram\twin\telegram\sourcefiles\ui\images.cpp:320
Binary: Telegram.exe
Launched: 07.10.2018 01:28:58
Platform: Windows
UserTag: 4d93bdaa1ed43ad6
Version: 1004000

Caught signal 11 (SIGSEGV) in thread 6648

Backtrace:
5836667
24770760
24542172
2004038506
2010945794
2010945749

Google Breakpad caught a crash, minidump written in thread 11336
Minidump: aeda3399-13ca-4680-b55d-5628c9930361

Backtrace:
5836667
5836848
14917298
2010945794
2010945749
```

**Comment by john-preston** [comment]
@KarelWintersky I hope this will be fixed in the next version. At least I've found one fast growing memory leak.

**Comment by KarelWintersky** [comment]
@john-preston what about 

- tabs (for private chats, secret chats, channels and groups ) ?
- don't move muted chat to top when a someone posted message there ?

Screens required?

**Comment by Khalphion** [comment]
I have this error regularly as well. Checked the log every time after it crashed. Occurred randomly.

`Assertion: "!img.isNull()" c:\projects\telegram\twin\telegram\sourcefiles\ui\images.cpp:320`

**Comment by john-preston** [comment]
@Khalphion Including 1.4.2?

**Comment by Khalphion** [comment]
> @Khalphion Including 1.4.2?

That's something I need to observe now, since I got the update just 30 minutes ago. Do you think that there's a correlation between the memory leak and the assertion error?

**Comment by john-preston** [comment]
@Khalphion Yes, assertion fails when Qt was not able to allocate memory for the image and it is null. This happens on Windows somewhere after 1.5 GB of RAM usage, because this is a 32 bit application.

**Comment by Khalphion** [comment]
@john-preston Alright, then let's hope that this was the fix. I'm in a group chat where several people are having (or had?) the same issue. I'll come back to you in some days if it doesn't reoccur again or if I see it again. Thanks for your work!

**Comment by shmutalov** [comment]
I think, issue was fixed.

**Comment by Robadob** [comment]
Yes it was, although i don't remember which specific commit.
