### ISSUE TITLE
Feature to setup font on macOS

### ISSUE THREAD

**Issue by DOBRO** [telegramdesktop/tdesktop#5213]
Hi!
It would be great to have a possibility to setup font in settings.
It seems Apple completely forgot about such devices as iMac with high resolution display retina 5K.
Fonts look tiny. So I have to change font size for every application, but Telegram Desktop doesn't support this feature.
Looking forward... )))

... And Thanks for a great work!

**Comment by Aokromes** [comment]
#90 #4072

**Comment by DOBRO** [comment]
Increasing overall scale was the first thing I tried, but it's not a solution for me because of loosing sharpness, everything becomes dimmed (fonts, images etc.)
