### ISSUE TITLE
Default interface scale turn off when DPI scaling changes

### ISSUE THREAD

**Issue by tavrez** [telegramdesktop/tdesktop#5214]
### Steps to reproduce
1. Turn default interface scale on some Windows DPI setting(125% in my case).
2. Close Telegram desktop and change Windows DPI setting(to 100% as example).
3. Open Telegram again, default interface scale is now off and scaling is on the last option it was before changing Windows DPI scaling.

### Expected behaviour
It should automatically come up with new scaling settings, just like how it was before 1.4.
I use an external monitor with different scaling in compare to my laptop, so this happens to me offen.

### Actual behaviour
It won't change and turn auto scaling off.

### Configuration
**Operating system:**
Windows 10 1709
**Version of Telegram Desktop:**
1.4
**Used theme**:
Default

**Comment by tavrez** [comment]
This still happens in 1.4.3

**Comment by Xalaxis** [comment]
And 1.4.4 beta.

**Comment by Byloth** [comment]
It still happens in 1.5! 😭

**Comment by tavrez** [comment]
1.5.1 seems ok, since developers are not managing tickets, I close this for now

**Comment by Byloth** [comment]
> 1.5.1 seems ok, [...]

![example](https://user-images.githubusercontent.com/14953974/49877008-cb6d0f00-fe24-11e8-8784-4c84e0cc5ecb.png)
