### ISSUE TITLE
Image resize antialiasing artifacts in image view

### ISSUE THREAD

**Issue by futpib** [telegramdesktop/tdesktop#5217]
### Steps to reproduce
1. Open a high resolution image URL preview (NSFW example: https://steamuserimages-a.akamaihd.net/ugc/959720488903490135/0ABF5F814DA9CB13A2C2E52D3B9309DE2C582E09/)
2. Observe resize anti-aliasing artefacts

### Expected behaviour
A decent resized image quality or full sized image.

### Actual behaviour
A resized image with weird anti-aliasing artefacts (like if it is resized with nearest neighbour algorithm, or downscaled and then upscaled, see screenshot below).

### Screenshot

Below is a side-by-side comparison of Telegram's image view and the same image in Chromium.

![screenshot_20181002_164727](https://user-images.githubusercontent.com/4330357/46353298-7a8eac80-c664-11e8-8e29-b2c6e1e45b2b.png)

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** Tried both 1.4 and 1.3.14-alpha

**Used theme**: Irrelevant, but tried both default night theme and BreezeDark from https://t.me/BreezeDark

**Comment by mariansam** [comment]
Yeah, this happens to me also. I noticed that when I sent a screenshot of my terminal. - like this
Original:
![image](https://user-images.githubusercontent.com/33497067/46918682-27f2b000-cfd5-11e8-9922-4b1eb87a5aa4.png)
On Telegram:
![image](https://user-images.githubusercontent.com/33497067/46918691-3d67da00-cfd5-11e8-9f14-001333ed2914.png)

**Comment by futpib** [comment]
@mariansam this is not the same issue, your screenshot shows horrible JPEG compression, while I was talking about resizing/antialiasing. JPEG thing applies to every telegram app (mobile and desktop), it is a feature of their servers to reduce image size, while this issue (as far as I understand) is only about telegram desktop.

**Comment by Lonami** [comment]
This is a server-side issue. The server generates low resolution variants to be used as previews with poor quality. If you send the photo through Telegram Desktop it will be resized with proper antialiasing before upload. Nothing to do here.
