### ISSUE TITLE
Pressing enter when adding caption to uploaded image triggers submit instead of confirm using Chinese input method.

### ISSUE THREAD

**Issue by yanglin5689446** [telegramdesktop/tdesktop#5223]
Using chinese input method (or japanese input method) when adding caption to uploaded file will trigger submit before confirmed. When in normal input field it works fine.

### Steps to reproduce
1.  open any contacter 
2. click upload file
3. type something with chinese/japanese input method
4. the text are sent immediately before confirmed(when in unconfirmed status the words are underscored)
demo: ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12843409/46401886-d45ca880-c730-11e8-8bfa-59cb673fd372.gif)

### Expected behavior
The text should be in confirmed state before it was sent, like it is in normal input field.

### Actual behavior
The text is sent in unconfirmed state.

### Configuration
**Operating system:**
Mac OS 10.13.6
**Version of Telegram Desktop:**

**Used theme**:
default

**Comment by john-preston** [comment]
@yanglin5689446 This is not Telegram Desktop, but another macOS Telegram app.

**Comment by yanglin5689446** [comment]
oops,
okay i will close it, thanks!

**Comment by stek29** [comment]
You can get Telegram Desktop at https://desktop.telegram.org

Report issues in the app you are using at https://t.me/macswift
