### ISSUE TITLE
[Feature request] Disable notifications of pinned messages

### ISSUE THREAD

**Issue by MetalDroid** [telegramdesktop/tdesktop#5225]
To maintain consistency with the other Telegram clients (for example Android client, Events section), I suggest an adjustment in the notifications section to disable notification of pinned messages.

It seems to be related to this thread, but what I am saying is different:
https://github.com/telegramdesktop/tdesktop/issues/1864

**Comment by RememberTheAir** [comment]
As someone pointed out in the thread you linked, if we're talking consistency then the client that should change something is the Android one, beceuase it is the only official client that offers that option - Telegram Web, Telegram for iOs, Telegram for WP and Telegram for MacOS don't have it. Also considering that option is not synced, implementing it in every client as local setting would not make sense in a multidevice service as one would expect that option to be synced across client like _evry_ other notification setting. In short, the API should support a global setting for pinned messages. That thing shouldn't be done on the clients side.

I suggest you to ping the in-app support and @telegram on Twitter with this feature request. Maybe if they get enough request we will be able to get rid of annoying pinned messages notifications once for all
