### ISSUE TITLE
Text out of bounds

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#5226]
### Steps to reproduce
1. Use i3 (a linux DE) and resize Telegram

### Expected behaviour
Text messages fit correctly

### Actual behaviour
They don't

### Configuration
**Operating system:** Ubuntu 18.04, i3-wm

**Version of Telegram Desktop:** 1.4

**Used theme**: Night

Sorry for the low-quality photo 
![photo_2018-10-03_15-47-23](https://user-images.githubusercontent.com/6240983/46415767-45e32980-c726-11e8-9835-b129c2ad6644.jpg)

**Comment by john-preston** [comment]
@ArmeF97 Tdesktop has minimum supported window width. If the window manager doesn't respect it bad things like this can occur :(

**Comment by ArmeF97** [comment]
I know this much, but in that specific case it should have been handled better, don't you think? See the photo
@john-preston

**Comment by stek29** [comment]
@ArmeF97 tdesktop assumes that it's minimum width would be respected -- and that assumption is broken. You can't assume that TDesktop would handle things "better" if assumptions app relies on are broken.

**Comment by ArmeF97** [comment]
Ok, I see
