### ISSUE TITLE
Group admin feature request: show only deleted user and user just recently joined

### ISSUE THREAD

**Issue by sharuzzaman** [telegramdesktop/tdesktop#5228]
### Steps to reproduce
1. As admin for a group, click the group name, then click hamburger dot
2. Select manage group
3. Can see a list of user, but cannot filter this user, especially for Deleted Account and recently joined
4. This filter is beneficial to remove spammer that create a temporary account, then join the group. Later the account was deleted, leaving Deleted Account somewhere in the list, but not easy to find. Recently joined list is also good to filter out spammer that just recently joined the group so that they can be banned

### Expected behaviour
User list should have filter for Deleted Account and recently joined user

### Actual behaviour
User list does not have filter for Deleted Account and recently joined user

### Configuration
**Operating system:** Windows, Android

**Version of Telegram Desktop:** 1.4.0

**Used theme**: Standard

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RememberTheAir** [comment]
You can access the mebers list and filter it from two different places: [example 1](https://my.mixtape.moe/qqntcm.mp4) and [example 2](https://my.mixtape.moe/zswajr.mp4)

About Deleted Accounts, Telegram removes them automatically in batches every one week or two.

You can see the members who joined the group less than 48 hours ago from the Recent Actions menu, from where you can limit accounts you don't trust

**Comment by stek29** [comment]
Sorry, no api for that.
