### ISSUE TITLE
:shrug: is broken

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#5229]
### Steps to reproduce
1. write `:shrug:`

### Expected behaviour

It gets replaced by the shrug emoticon

### Actual behaviour

Nothing happens

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.4

**Used theme**: matrix

The last version I've used where it was working was 1.3.10

**Comment by RadRussianRus** [comment]
Strange. Windows 10, TDesktop 1.4. `:shrug:` works fine.

**Comment by RememberTheAir** [comment]
Mmmm. [I can't make it work](https://my.mixtape.moe/xixsqq.mp4)

**Comment by RadRussianRus** [comment]
![image](https://user-images.githubusercontent.com/2903496/46564135-43432880-c90e-11e8-814b-fbc8fe895d5b.png)
Is that option on?

**Comment by RememberTheAir** [comment]
...no. Thank you @RadRussianRus
