### ISSUE TITLE
Different background for each contact

### ISSUE THREAD

**Issue by Innomen** [telegramdesktop/tdesktop#523]
Edit: **Just go here instead: https://github.com/telegramdesktop/tdesktop/issues/2642**

It would be great if I could make it visually obvious who I'm speaking to by setting backgrounds for each contact. Kind of like caller specific ringtones and the like.

If this is covered elsewhere, my apologies.

Thanks for your time.

**Comment by Arttse** [comment]
+1

**Comment by ScottRFrost** [comment]
I agree this is needed.  I have several friend groups with different chats and a different background per chat would be very helpful in telling which one I'm in at a glance.  Perhaps you could even share the chat background out to the group when you change it like you can change the avatar / icon for the group?

**Comment by moodler** [comment]
+1

**Comment by durzo** [comment]
+1 I keep abusing the wrong people

**Comment by digitalsparky** [comment]
+1 durzo keeps abusing the wrong people...

**Comment by Spaxe** [comment]
+1

**Comment by rusins** [comment]
+1

**Comment by Thijs5** [comment]
+1

**Comment by DaFri-Nochiterov** [comment]
+1

**Comment by evilive3000** [comment]
+1

**Comment by kenitive** [comment]
+1

**Comment by haevalencia** [comment]
+1

**Comment by antoniocarlosortiz** [comment]
+1

**Comment by Great-Antique** [comment]
+1 It's really needed

**Comment by jLuca** [comment]
I wish you could add this feature too

**Comment by Innomen** [comment]
Clearly never gonna happen. 

Guess I should have asked for 4000 sticker packs and a freaking bot system, because apparently those are less artistically demanding and easier to code >.>

**Comment by urbanhusky** [comment]
I need this more and more - or more generally: some way to easily discern between context of various chats. I might have some very personal contacts, some acquaintances - and I have to be careful what I share with what group of people.

All it takes is for an acquaintance or some professional contact to pop up in the middle of my recent chats and suddenly I'm very likely to send messages to the wrong person, or in the completely inappropriate tone.

**Comment by Innomen** [comment]
@urbanhusky 

Exactly. I expressly don't share telegram with people because it's hard enough managing the 5 contacts I already have.

It's really hard not to make assumptions about the dev team that sees this as low priority. Do they really talk to friends, family, and colleagues in the exact same way?

How does the contact specific ringtone analogy not ram it home for them?

**Comment by urbanhusky** [comment]
I've opened a perhaps more descriptive feature request of why we want such a thing:
https://github.com/telegramdesktop/tdesktop/issues/2642

**Comment by Innomen** [comment]
@urbanhusky 
Awesome!

**Comment by Aokromes** [comment]
close as superseded by  #2642 ?
