### ISSUE TITLE
Visual bug with language

### ISSUE THREAD

**Issue by LeJoW** [telegramdesktop/tdesktop#5232]
### Steps to reproduce
1. Open Telegram in French
2. Go to `Manage Channel` in an administred channel
3. Go to `Recent Actions`

### Expected behaviour
The title `What is this ?`should appear centered in the box

### Actual behaviour
The title `What is this ?` appears out of the box

![telegram_bug](https://user-images.githubusercontent.com/33910128/46571620-686c8100-c978-11e8-807f-896aa4e35d88.png)

### Configuration
**Operating system: MacOs 10.13.6**

**Version of Telegram Desktop: 1.4**

**Used theme: Night Mode**

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by LeJoW** [comment]
Yes the bug is still valid with **MacOs 10.15.2** and **Telegram 1.9.8**.

**Comment by LeJoW** [comment]
The bug is still valid with **MacOs 10.15.7** and **Telegram 2.4.4**

**Comment by john-preston** [comment]
This is a problem of the translation, I've suggested a fixed phrase (without a newline in front of it), I hope it'll be applied.
