### ISSUE TITLE
Channel Unread Count doesn't clear in MacOS 

### ISSUE THREAD

**Issue by STrRedWolf** [telegramdesktop/tdesktop#5233]
### Steps to reproduce
1. Open Telegram Desktop on MacOS
2. Select a channel with unread messages
3. Scroll to the bottom of the channel

### Expected behaviour
Channel unread message indicator disappears

### Actual behaviour
Channel unread message indicator stays on screen.

### Configuration
**Operating system:**  MacOS X High Sierra

**Version of Telegram Desktop:** 1.4

**Used theme**:  Midnight in Night Mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stek29** [comment]
Do you have multiple displays?

**Comment by STrRedWolf** [comment]
Yes.  Telegram Desktop is on the primary display 99% of the time, though.

**Comment by stek29** [comment]
And you're using extended screen?

**Comment by stek29** [comment]
#1992
