### ISSUE TITLE
"Telegram Desktop" and "Telegram Web" emoji differ

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#5234]
### Steps to reproduce
1. See same message on TG Desktop and TG Web

### Expected behaviour
Same emoji (image)

### Actual behaviour
Different emoji

### Configuration
**Operating system:** Windows 10 64bit v1803 (build 17134.286)

**Version of Telegram Desktop:** 1.4

**Used theme**: Night

See the photo
![immagine_tg](https://user-images.githubusercontent.com/6240983/46572370-e20a6c00-c984-11e8-9ee1-dff2ab1e705f.png)

This is the emoji 😁
https://emojipedia.org/grinning-face-with-smiling-eyes/

**Comment by RadRussianRus** [comment]
Isn't it a Telegram Web problem? In Telegram Desktop it works as it should, no?

**Comment by stek29** [comment]
https://github.com/zhukov/webogram

**Comment by ArmeF97** [comment]
Thanks
