### ISSUE TITLE
[BUG] Very large memory leak (>4GB)

### ISSUE THREAD

**Issue by LightningProd** [telegramdesktop/tdesktop#5237]
### Steps to reproduce
1. Open Telegram Desktop for Linux (1.4).
2. Wait.
3. Memory usage slowly goes up and up.

### Expected behaviour
Amount of Ram used stays low.

### Actual behaviour
Amount of RAM used gets really large (from 6MB to 65MB to 120MB and even 4GB).

### Configuration
**Operating system:** Linux Mint 19 (known to happen on Ubuntu 18.04 too)

**Version of Telegram Desktop:** 1.4

**Used theme**: Matrix

<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/2453320/log.txt)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1317

**Comment by Streetwalrus** [comment]
I also ran into such a leak yesterday, it looks like tdesktop is slowly allocating more and more memory during normal use which eventually leads to the system becoming unresponsive because of the OOM condition (I've seen it go up to 12.5GB in use on my 16GB system).

**Comment by john-preston** [comment]
@Streetwalrus Can you please check the previous stable version:

https://github.com/telegramdesktop/tdesktop/releases/tag/v1.3.14

(disable autoupdates in Settings), does it behave the same way? I can't think of any particular change in the latest version(s) that could give such effect.

**Comment by Streetwalrus** [comment]
I didn't have that problem on 1.3.14 which I'd been running for a month.

**Comment by GoogleGFW** [comment]
![qq](https://user-images.githubusercontent.com/26985927/46581352-9a114500-ca69-11e8-94f2-ba7d5ccdefdb.png)

v1.4   win7 64

**Comment by Streetwalrus** [comment]
1GB isn't really unusual for tdesktop, though it is an unacceptably large amount of memory for what it does.

**Comment by Feuerfuchs** [comment]
The same issue exists for me. Yesterday, after I used Telegram the whole day (i.e. started on ~10am, ended on 2:30am), the RAM usage grew to a whopping 19.2gb. I'm absolutely sure that issue wasn't there in the previous version.

![bildschirmfoto vom 2018-10-07 02-25-36](https://user-images.githubusercontent.com/14197353/46583033-a8069c00-ca50-11e8-99bc-67f4c7a22953.png)

**Comment by f242** [comment]
almost three years problem and still not fixed ¯\_(ツ)_/¯

**Comment by Dyneteve** [comment]
Same thing on windows ( the exe version not the one frm the store ) after the latest update it just fills up the ram up and crashes i get 6 gb ram ussage by sending 20 stickers

**Comment by Dyneteve** [comment]
@john-preston

**Comment by Streetwalrus** [comment]
> almost three years problem and still not fixed ¯_(ツ)_/¯

I doubt this is the same problem. You don't need to do anything in particular to trigger the issue. It just constantly allocates more memory. It looks like typing in the message box, without even sending anything, accelerates it at mind boggling rates (several MB for a few key strokes), but just leaving it running with no interaction is enough to observe the leak.

**Comment by john-preston** [comment]
@Streetwalrus I can't reproduce anything like that :( I tried to use couple of instances of tdesktop on Windows for a day and they both were below 100 MB %) When I started to scroll some photos-heavy chat up for several tens of loadings it went to about 150 MB, but nothing like things described here.

**Comment by Streetwalrus** [comment]
I'm on Linux. Tdesktop has been running for ~24h (with system suspend overnight), and it's sitting at 4700MB in use (resident memory). I can't consistently reproduce allocations while typing, but that's still a lot. I'm not in many groups, most of them aren't very active and the amount of posted images and stickers is average.

**Comment by john-preston** [comment]
@Streetwalrus That's too much. I'm trying to understand what could happen between the latest two releases that can cause such memory usage, but currently I didn't find it out yet.

**Comment by f242** [comment]
asked a friend with linux to take a screenshot
![image](https://user-images.githubusercontent.com/10371194/46627221-71a94980-cb42-11e8-8162-79af6072a564.png)

**Comment by Streetwalrus** [comment]
I have no idea either, there are no specific steps other than "just use telegram normally". It takes hours for it to reach that level. I can try bisecting the problem if you want but that will definitely take a while.

**Comment by john-preston** [comment]
@Streetwalrus I hope I'll be able to bring it back to old way of memory consumption at least :( (it is still unlimited if used long enough, but not that fast).

**Comment by xvitaly** [comment]
@Streetwalrus Memory leaks started since version 1.3.15 (after adding xxhash library). You can start with this.

**Comment by Streetwalrus** [comment]
Interesting, my distribution hasn't shipped 1.3.15 so I've never noticed it until 1.4.

**Comment by xvitaly** [comment]
@Streetwalrus I build and test every alpha versions on Fedora. 1.3.14 is last working version.

**Comment by john-preston** [comment]
@Streetwalrus I've found it! :)

**Comment by Streetwalrus** [comment]
@xvitaly yeah I just realized that .15 to .17 were pre-release versions. Thanks for the pointer.

@john-preston Awesome! :)

**Comment by fisher122** [comment]
![default](https://user-images.githubusercontent.com/574515/47282280-436a4600-d5e7-11e8-82d5-8f8ac15c0e24.png)
nice

**Comment by john-preston** [comment]
@fisher122 What version does it show in the main menu? The latest version still does that? :(

**Comment by fisher122** [comment]
> What version

This, as far as I remember, was the last version before 1.4. Now I have 1.4.4 beta. It took only about 1.5 GB, then I'm tired and I stuffed it in the cgroups with a limit of 400 MB then killing OOM... OOM kills tg app 1-2 times a day.

**Comment by john-preston** [comment]
@fisher122 Please check the same way some 1.3.* from the releases page.
