### ISSUE TITLE
[BUG] When you remove a banned user from the group, the user is not deleted, and the banned count increases

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#5238]
### Steps to reproduce
1. Manage group
2. Banned users
3. Remove from group
4. Remove
5. Close
6. Repeat from step two

### Expected behaviour
the user must be deleted and the counter banned less

### Actual behaviour
users are not deleted, and the banned count is increased

### Configuration
**Operating system:**
Windows 7

**Version of Telegram Desktop:**
1.4

**Used theme**:
Night

![locale](https://user-images.githubusercontent.com/33932755/46600149-b57c5e80-cb02-11e8-8acf-075c84f2883a.gif)

**Comment by Aokromes** [comment]
i think this bug was fixed long time ago.

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
