### ISSUE TITLE
[Feature request] Support FLIF - Best image format out there

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#5239]
https://flif.info/

- It uses less space than other file formats.
- It supports animations and hdr
- It's opensource
- It can be loss or lossless
- It supports "Progressive decoding"
- There is an already implemented JavaScript library for web browsers.

**Comment by Aokromes** [comment]
https://github.com/spillerrec/qt-flif-plugin may help on this.

**Comment by Lonami** [comment]
First the server would need to recognize it as a photo type and then *all* clients would need to be updated with support for it and then somehow the server needs to know whether the client supports it or else convert or hide the media… Not feasible and even if TDesktop supported it API changes are needed.

**Comment by udf** [comment]
@lonami A compromise would be for TDesktop to convert flif to a format recognized by the Telegram servers, but even then it's a pretty niche format.

**Comment by ArmeF97** [comment]
Let's keep this open

**Comment by ilya-fedin** [comment]
> https://github.com/spillerrec/qt-flif-plugin may help on this.

I can add this plugin to cmake_helpers like fcitx input plugin, but I have a feel that no one across @ArmeF97 want this

**Comment by ilya-fedin** [comment]
Oh, looks like this issue should be closed
> FLIF development has stopped since FLIF is superceded by FUIF and then again by JPEG XL (https://jpeg.org/jpegxl/index.html), which is based on a combination of Pik and FUIF. A royalty-free and open source reference implementation of JPEG XL is available on GitLab.

https://github.com/FLIF-hub/FLIF/

**Comment by ArmeF97** [comment]
Oh, ok.
Is JPEG XL supported by tdesktop?

**Comment by ilya-fedin** [comment]
> Is JPEG XL supported by tdesktop?

No, since it is not supported by Qt. And it is impossible to add support until someone write a Qt plugin for it.

**Comment by ArmeF97** [comment]
So we can mark this as "waiting for a qt plugin"

**Comment by ilya-fedin** [comment]
> So we can mark this as "waiting for a qt plugin"

I don't think there are a point to have a ticket until there would be a Qt plugin

**Comment by ilya-fedin** [comment]
Not to say that JPEG XL still is not standartized

> JPEG XL is in the final stages of standardization, but minor changes to the
codestream are still likely. WARNING: until further notice, do not depend on

https://gitlab.com/wg1/jpeg-xl
future decoders being able to decode the output of a current encoder.

**Comment by ArmeF97** [comment]
I'm closing this issue in favor of the new standard, JPEG XL
