### ISSUE TITLE
Hashtag with Umlauts are not recognized

### ISSUE THREAD

**Issue by dschoeni** [telegramdesktop/tdesktop#524]
![image](https://cloud.githubusercontent.com/assets/1913623/6416743/c0e5c460-bea8-11e4-9602-c0181f90473c.png)

Don't know whether this is a bug or intended behaviour - Hashtags do not get recognized with Umlauts though.

**Comment by Sollex-21412** [comment]
+1. Even with cyrillic letters.

**Comment by drasive** [comment]
+1
