### ISSUE TITLE
Hangul (Korean) keyboard input doesn't work properly in Ubuntu 

### ISSUE THREAD

**Issue by wayneoutthere** [telegramdesktop/tdesktop#5240]
### Steps to reproduce
1. install Korean (hangul) keyboard on Ubuntu (I'm on gnome)
2. switch to korean keyboard input
3. type

### Expected behaviour
It should 'just work' in the same way that it 'just works' in the browser on the very same machine/OS
It does work perfectly in Firefox.
it does work perfectly in Gedit

### Actual behaviour
Space bar doesn't work.
cannot delete
input is painful.  
In order to delete or use spacebar you have to switch back to English - doesn't while in Korean mode

### Configuration
**Operating system:** Ubuntu 18.04 LTS 

**Version of Telegram Desktop:**  1.2.17

**Used theme**: None/default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
#2603

**Comment by wayneoutthere** [comment]
Ibus hangul input
"Dubeolsik' hangul keyboard layout

**Comment by dhsuh** [comment]
Same issue here. It started to occur to me after update to 18.04 LTS from 16.04LTS (i believe? It was 16 LTS)

**Comment by wayneoutthere** [comment]
I see you closed this and called it a duplicate.  No problem but if you could kindly leave the active thread here that would be great so we can follow it.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2603 have longer conversation and link to a pull request fixing this bug.

**Comment by SlowMonk** [comment]
anyone sloved the problem with this issue yet?

**Comment by wayneoutthere** [comment]
아이 켄 라이트 히어 i can write here in a browser, but not in Ubuntu apps it seems (still).  Very bad news for Korean input.  I wish I had coding power :(  Also seems that even in the browser there is a problem with the wrong keys going in in English mode.. for example I push the 'a' button and I get a 'q'.
