### ISSUE TITLE
telegram not running on deepin

### ISSUE THREAD

**Issue by ph98** [telegramdesktop/tdesktop#5242]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
open telegram app :|

### Actual behaviour
telegram app didn't run !

### Configuration
**Operating system:**
deepin 15.7 

**Version of Telegram Desktop:**

1.4.0-alpha-2-g7d16ea...

--

**Used theme**:

<details><summary><b>Logs</b>:</summary>
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
QEventLoop: Cannot be used without QApplication
QXcbConnection: Could not connect to display :0
Telegram[0x9cf505]
Telegram[0x9cfa8c]
Telegram(_ZN15google_breakpad16ExceptionHandler12GenerateDumpEPNS0_12CrashContextE+0x382)[0x1672f28]
Telegram(_ZN15google_breakpad16ExceptionHandler12HandleSignalEiP9siginfo_tPv+0x1c3)[0x1672b03]
Telegram(_ZN15google_breakpad16ExceptionHandler13SignalHandlerEiP9siginfo_tPv+0x1ab)[0x167281b]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f3d7ebba390]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f3d7e2f5428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f3d7e2f702a]
Telegram[0x23e0567]
Telegram(_ZN14QXcbConnectionC2EP19QXcbNativeInterfacebjPKc+0xe93)[0x1aafbf3]
Telegram(_ZN15QXcbIntegrationC1ERK11QStringListRiPPc+0x2ea)[0x1a8493a]
Telegram[0x1a8350b]
Telegram[0x22a723d]
Telegram[0x1fc439d]
Telegram[0x1fc4fa5]
Telegram[0x25b3725]
Telegram[0x1fc657f]
Telegram[0x1c83f09]
Telegram(_ZN11ApplicationC2EN3gsl8not_nullIPN4Core8LauncherEEERiPPc+0x3a)[0x154bb5a]
Telegram(_ZN4Core8Launcher18executeApplicationEv+0xae)[0xa04afe]
Telegram(_ZN4Core8Launcher4execEv+0x4d)[0xa04c4d]
Telegram(main+0x32)[0x879652]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f3d7e2e0830]
Telegram(_start+0x29)[0x87b809]
[1]    18133 abort      telegram-desktop

</details>

i tried to install telegram via snap package manager ( https://snapcraft.io/telegram-desktop ) 
but the installed package seems to be broken and i can't run it

**Comment by john-preston** [comment]
@ph98 Can you try to run version from https://desktop.telegram.org?

**Comment by ph98** [comment]
@john-preston tanks for your fast reply :) 
i was installed that version too . 
but it needed some packages and i tried to use a package manager to install it completely .

**Comment by Aokromes** [comment]
#5012

**Comment by ph98** [comment]
@Aokromes tanks for response
but problem not fixed for me :(

**Comment by Aokromes** [comment]
it's not response, it's duplicate ticket :)

**Comment by ph98** [comment]
the error is different , 
so it's not a duplicate.

**Comment by rogeriomq** [comment]
## Instalando telegram no Linux Deepin

- Baixe a versão site oficial do telegram [aqui](https://desktop.telegram.org/)

- Descompacte no local desejado:

   ```bash
     tar -Jxvf tsetup.1.4.3.tar.xz
   ```
   Execute-o ao menos uma vez, para que ele crie automaticamente um atalho de desktop em **~/.local/share/applications** e então pode finaliza-lo.

- Abra com seu editor de preferencia o arquivo 
  _telegramdesktop.desktop_ 

   ```bash
   vi ~/.local/share/applications/telegramdesktop.desktop
   ```

- Em **Exec** modifique a entrada com os seguintes _ENVs_

   `env XDG_CURRENT_DESKTOP=XFCE FONTCONFIG_FILE=/home/man1gold/.config/tgfonts.conf QT_IM_MODULE=xim /home/man1gold/work/Telegram/Telegram -- %u`

- Agora criaremos o arquivo **tgfonts.conf** com o seguite conteúdo em **~/.conf/tgfonts.conf**:

  ```xml

<?xml version='1.0'?>
  <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
  fontconfig>	
    <dir>/usr/share/fonts</dir>
    <dir>/usr/X11R6/lib/X11/fonts</dir> <dir>/usr/local/share/fonts</dir>
    <dir prefix="xdg">fonts</dir>
    <match target="pattern">
  <test qual="any" name="family">
      <string>mono</string>
  </test>
  <edit name="family" mode="assign" binding="same">
      <string>monospace</string>
  </edit>
    </match>
    <match target="pattern">
  <test qual="any" name="family">
      <string>sans serif</string>
  </test>
  <edit name="family" mode="assign" binding="same">
      <string>sans-serif</string>
  </edit>
    </match>
    <match target="pattern">
  <test qual="any" name="family">
      <string>sans</string>
  </test>
  <edit name="family" mode="assign" binding="same">
      <string>sans-serif</string>
  </edit>
    </match>
    <cachedir>/var/cache/fontconfig</cachedir>
    <cachedir prefix="xdg">fontconfig</cachedir>
    <cachedir>~/.fontconfig</cachedir>
    <match target="font">
  <edit mode="assign" name="antialias">
      <bool>true</bool>
  </edit>
  <edit mode="assign" name="embeddedbitmap">
      <bool>false</bool>
  </edit>
  <edit mode="assign" name="hinting">
      <bool>true</bool>
  </edit>
  <edit mode="assign" name="hintstyle">
      <const>hintslight</const>
  </edit>
  <edit mode="assign" name="lcdfilter">
      <const>lcddefault</const>
  </edit>
  <edit mode="assign" name="rgba">
      <const>rgb</const>
  </edit>
    </match>
  </fontconfig>
  ```
Abra o telegram pelo ícone e seja feliz!

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by ph98** [comment]
> this bug is still valid?

I've changed my OS so i don't know if this bug still present or not

**Comment by AliDjango** [comment]
the bug still valid @Aokromes 
os : Raspbian buster lastest update on raspberry pi 3
telegram version : 1.9.9(latest stable for armhf in snap packages)
