### ISSUE TITLE
Windows version uses wrong typeface in showing Chinese text

### ISSUE THREAD

**Issue by showerying** [telegramdesktop/tdesktop#5243]
### Steps to reproduce
1. Install Telegram Desktop from Windows Store
2. Open Telegram Desktop

### Expected behaviour
The font that the app is using is good ol' SimSun（中易宋体）, which is clearly outdated to being UI font at present.
![image](https://user-images.githubusercontent.com/6418433/46716174-8a764400-cc95-11e8-81af-a667f746667d.png)

### Actual behaviour
Microsoft Yahei（微软雅黑）is more common in UWP apps （it's supposed to be the default one）.
![image](https://user-images.githubusercontent.com/6418433/46716242-cdd0b280-cc95-11e8-80c4-4d8b3cd41936.png)

I think there should be a setting for selecting UI font.

### Configuration
**Operating system:**
Windows 10 Home 1809
**Version of Telegram Desktop:**
1.4
**Used theme**:
Default

**Comment by Aokromes** [comment]
#90
