### ISSUE TITLE
can't change language telegram desktop

### ISSUE THREAD

**Issue by zhr0** [telegramdesktop/tdesktop#5244]
### Steps to reproduce
1.  happened after telegram updated to 1.4.2
2. i choose settings and language
3.  changed selection to empty entry on middle in the languages

### Expected behaviour
Tell us what should happen

-Should be able to change language

### Actual behaviour
Tell us what happens instead

-interface doesn't restart and have a empty selection after i choose it and right click menus i get all options white

### Configuration
**Operating system:**

- Debian 9.5 xfce 4.12

**Version of Telegram Desktop:**

- version 1.4.2

**Used theme**:

- default one

Note:
- Did a test and this doesn't happen on telegram desktop 1.4.2 on windows 10

![bug2](https://user-images.githubusercontent.com/6616886/46746071-30ca4580-cca6-11e8-8cae-7850ea67d1f6.png)
![bug](https://user-images.githubusercontent.com/6616886/46746072-30ca4580-cca6-11e8-9b03-0cb7b500b405.png)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2572
