### ISSUE TITLE
URLS with the letter 's' at the end will be ignored

### ISSUE THREAD

**Issue by danger89** [telegramdesktop/tdesktop#525]
When I send or receive a URL with the letter 's' at the end, this letter won't be taken into account. Meaning when I click on the link, Telegram will sent the link to the web-browser WITHOUT the 's' attached. 

See image below:
![domain_urls_s](https://cloud.githubusercontent.com/assets/628926/6417769/237ac9fc-beb0-11e4-9259-c81a5bbb1d66.png)

**Comment by auchri** [comment]
False repo ;)

**Comment by danger89** [comment]
False 'repo' :S?

**Comment by telegramdesktop** [comment]
Can't reproduce that. Sending "http://www.test.com/tests", all message becomes a link. But I don't know about 0.4.0 version, current version is 0.7.17

**Comment by auchri** [comment]
the Screenshot from @danger89 is from telegram web

**Comment by danger89** [comment]
@telegramdesktop 
I say the link to the web-browser without 's', I didn't say I use telegram webbased interface. In fact, I'm using the Telegram Desktop (Windows) version 0.4.0. That is why I create this issue on this github repo.

See attachment again:
![send_url](https://cloud.githubusercontent.com/assets/628926/6466129/d39b424a-c1c5-11e4-8ec6-43852ab1b943.png)


HELLO? you shouldn't close it.. -,-

**Comment by auchri** [comment]
@danger89 Here is the issue in Telegram Web: https://github.com/zhukov/webogram/issues/697

**Comment by danger89** [comment]
@auchri Thanks, sorry for the confusion.
