### ISSUE TITLE
Telegram crashes when You use right click in the message area

### ISSUE THREAD

**Issue by franjorub** [telegramdesktop/tdesktop#5253]
### Expected behaviour

By right clicking on the text area the contextual menu should appear

### Actual behaviour

the program closes unexpectedly when you right click in the message area

### Configuration
**Operating system:**
Linux mint 19
**Version of Telegram Desktop:**
1.2.17
**Used theme**:
nothing
<details><summary><b>Logs</b>:</summary>
ASSERT failure in QList<T>::at: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h, line 541
[1]    21490 abort (core dumped)  telegram-desktop

</details>

**Comment by Aokromes** [comment]
you are using one extreme old telegram revision, i sugest you to update to at least 1.4.3

**Comment by stek29** [comment]
Does it happen on latest version?
