### ISSUE TITLE
updates downloaded but not applied

### ISSUE THREAD

**Issue by y1n0** [telegramdesktop/tdesktop#5254]
## Steps to reproduce
Not sure how to reproduce but here's my setup:
I have Telegram executable and Updater installed under `/opt/Telegram` and a symlink to Telegram in `/usr/bin` which I use for launch.
When there is an update, it is downloaded and the "restart to update button" is shown. But after restart, the update is not installed and it's the old version that's been run.

I thought it has something to do with the permissions, so I recursively set `/opt/Telegram` to `777` but the problem remains. 

### Expected behaviour
after downloading an update and clicking "restart to update", the updated version should start. 

### Configuration
OS: Linux 4.18.12-arch1-1-ARCH x86_64 GNU/Linux with i3
Telegram version: 1.14 but happened with all the pervious ones

There is this line is the logs:
<details><summary><b>Logs</b>:</summary>
[2018.10.13 11:22:09] Command line: /opt/Telegram/Telegram -noupdate
</details>

**Comment by john-preston** [comment]
@y1n0 First the new Updater binary is copied near Telegram binary, then it is launched to copy a new Telegram binary instead of the old one. If any of those copyings fail then the whole update process fails :(

**Comment by y1n0** [comment]
it updated successfully after changing the ownership of Telegram directory to the active user. Though why it did not before despite the user had write permission?
