### ISSUE TITLE
Lost update and wallpaper after switched to workmode and revert back to normal mode

### ISSUE THREAD

**Issue by Fathurhoho** [telegramdesktop/tdesktop#5255]
### Steps to reproduce
1. On normal mode
a. Use custom wallpaper
b. Downloaded telegram update (not installed yet)
2. Switched to workmode
3. Revert back to normal mode
a. Update button is missing
b. Wallpaper set to default

I recorded the steps above, [here is the video](https://telegra.ph/file/b55da475dfd9d4255bddc.mp4).

### Expected behaviour
TDesktop should keep the update file and wallpaper.

### Environment
**Operating system:** Windows 10 64 bit

**Version of Telegram Desktop:** 1.4.2 (beta)
Updated to 1.4.3 and problem (wallpaper) still persist.

**Used theme**: Dark Green by pvashenko, downloaded [from here](https://t.me/themes/143).

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
