### ISSUE TITLE
Updater for an unofficial Telegram client

### ISSUE THREAD

**Issue by mostafa-v** [telegramdesktop/tdesktop#5256]
Hi

I want to develop an unofficial Telegram client and I want to use updater so if I release a newer version of my unofficial client, then users could update with auto-update or from settings page.

Is it possible to use the current Telegram Updater? What changes are needed in client code? What endpoints or downloadable materials should be provided in server side?

**Comment by mostafa-v** [comment]
??

**Comment by Tommy1991** [comment]
do you find your answer???

**Comment by Aokromes** [comment]
check how kotatogram works :)
