### ISSUE TITLE
after 1.4.3 update on ubunty 14, not connecting ...

### ISSUE THREAD

**Issue by ljgww** [telegramdesktop/tdesktop#5257]
### Steps to reproduce
1. start telegram desktop
 

### Expected behaviour
load, connect, show messages

### Actual behaviour
load, starts to connect but never does, cannot see users nor messages

### Configuration
ubunty 14.

**Version of Telegram Desktop:** 1.4.3

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
some servers where down few hours ago.

**Comment by stek29** [comment]
Does it work now?

**Comment by ljgww** [comment]
Now, its working. Ty

**Comment by stek29** [comment]
Check telegram twitter
