### ISSUE TITLE
Text formatting is lost when changing text alignment direction

### ISSUE THREAD

**Issue by arieljannai** [telegramdesktop/tdesktop#5258]
### Steps to reproduce
1. Write something in the text area
2. Add formatting (link, italic etc.)
3. Change the alignment of the text with <kbd>Ctrl</kbd> + <kbd>Shift</kbd>

### Expected behaviour
The text and its formatting won't change, but the alignment will

### Actual behaviour
Alignment changed and formatting is lost

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.4.3
**Used theme**: Default

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Comment by arieljannai** [comment]
Sorry for the delay - still happens

TDesktop 2.0.1 beta

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/3811594/78988691-586bc980-7b3a-11ea-96b7-88458f13bad9.gif)
