### ISSUE TITLE
Hotkey for playing voice messages

### ISSUE THREAD

**Issue by BANOnotIT** [telegramdesktop/tdesktop#5259]
### Expected behaviour
Хотелось бы иметь горячую клавишу, чтобы при выборе чата с новыми сообщениями можно было с его помощью начать прослушивать все сообщения ниже линии "new messages" или те, которые находятся "в области видимости" и не являются проигрынами. Просто линия не всегда появляется, когда окно не закрывается, а проигрывать самое первое не прослушанное - это возможно слишком далеко надо будет искать.

### Configuration
Linux

**Comment by stek29** [comment]
Какой-то очень специфический запрос, сомневаюсь, что это много кому нужно.
Пересоздайте на английском.
