### ISSUE TITLE
Suggestion: Voice notes

### ISSUE THREAD

**Issue by MAGICCC** [telegramdesktop/tdesktop#526]
Is it possible to send voice notes like the mobile version has it? So we can use microphones to send them and can get rid off 3rd party clients/websites such has http://vocaroo.com/

**Comment by auchri** [comment]
duplicate #22 #37

**Comment by MAGICCC** [comment]
Well is it planned in the next versions or not? The linked suggestions are oldish anyway

**Comment by Katzen-Gott** [comment]
@MAGICCC It was added in v0.19.8. Cold you please close the issue? (there is a button below the comment box)
