### ISSUE TITLE
Limit of 5 chats pinned to the top

### ISSUE THREAD

**Issue by t0str** [telegramdesktop/tdesktop#5261]
I would very much like to be able to pin more than 5 chats to the top. The problem comes mostly from being in a lot of groups that have a lot of traffic going on. So all my friends are always buried under the groups. This makes me miss messages sometimes and makes finding their contact hard. I have my most used friends (plus 'Saved Messages') pinned, but there are more contact I need to pin than there are spaces.

Is there a specific reason that this limit exists? Would this be considered to be increased? Where would that need to be communicated? (I think this is also a backend feature since it is synced across devices).

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4762

**Comment by RadRussianRus** [comment]
That was asked so many times.
#3026 #3406 #4037 #4249 #4545 #4600 #4870
It's the server side limit.
