### ISSUE TITLE
Justify align

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#5263]
Hello.

Please support justified align for the paragraphs. 

Thank you.

**Comment by Lonami** [comment]
Are right or centered supported? This would need an API update so clients knew how to render other messages. How do you justify for different screen dimensions?

**Comment by stek29** [comment]
@Lonami I don't think that you're understanding the issue right -- I feel like @neesti just wants text in message boxes to be justify-aligned instead of right aligned.

**Comment by neesti** [comment]
@stek29 Yes, you understand the issue right.
