### ISSUE TITLE
Beta version download url doesn't work/is outdated

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#5265]
### Steps to reproduce
1. got to https://desktop.telegram.org/changelog#beta-version
2. [download the portable exe](https://updates.tdesktop.com/tsetup/tportable.1.3.16.beta.zip)

### Expected behaviour
The app executable is downloaded

### Actual behaviour
404 not found

Edit: it also points to 1.3.16

***

Is the beta version download page still relevant, since from 1.4 we have a new "beta opt-in" switch in Advanced Settings?

**Comment by ThigSchuch** [comment]
Just a mistake in the link, change "beta" for "alpha" and download goes on hahaha

**Comment by john-preston** [comment]
@ThigSchuch Yeah, sorry for that. No new public betas were released yet, old file names are still ".alpha". Fixed that link for now.
