### ISSUE TITLE
macOS application switcher icon looks low res

### ISSUE THREAD

**Issue by danilobytes** [telegramdesktop/tdesktop#5267]
### Steps to reproduce
1. Open Telegram Desktop.
2. Use command-tab to see its icon on the application switcher

### Expected behaviour
The icon should be high resolution on a retina display.

### Actual behaviour
The icon appears blurry on the screen.

### Configuration
macOS 10.14 Mojave

**Version of Telegram Desktop:** 1.4.3

**Used theme**: Midnight

**Comment by Aokromes** [comment]
#4329 ?

**Comment by danilobytes** [comment]
I think that is a different issue. On the dock and everywhere else the icon looks fine. It looks low res only in the application switcher.

**Comment by ichik** [comment]
Same. Capturing screenshot of the problem is pretty hard though.

**Comment by danilobytes** [comment]
@john-preston I've noticed the same blurry icon is now appearing on the notification bubble on macOS.

Should I open a new issue describing that?

**Comment by danilobytes** [comment]
Never mind, it was something on my end in regards to dual monitor setup.

**Comment by danilobytes** [comment]
Sorry for the buzz, but I'm getting the same original behavior of this issue if I use two displays, one is my Macbook's retina screen, the other is a 1080p monitor. The monitor is set as main display of the system.

**Comment by danilobytes** [comment]
If it helps with debugging, the only other app I notice this behavior is Chrome. Moreover if I set the HiDPI screen as the main display the issue is gone. So I guess it is something to do with the way Telegram Desktop "chooses" the icon to use according to the display resolution.
