### ISSUE TITLE
Ubuntu 14.04 fails to shutdown

### ISSUE THREAD

**Issue by Ocelot92** [telegramdesktop/tdesktop#527]
I'm running Ubuntu 14.04, when i start Telegram from the Dash when i try to shutdown/restart/log out Ubuntu by clicking on the buttono on the dialog window (the fancy transparent ones) then Ubuntu just close the Telegram window, leaving it running (I can see the process and the icon in the system tray).

Then if i click on shutdown from the drop down menu on top, the dialog window doesn't reappear and have to shutdoown/restart from the lock screen.

If i start it from ~/Telegram/Telegram or the updater then the shutdown works.

**Comment by auchri** [comment]
#516

**Comment by Ocelot92** [comment]
It's a different problem. I'm not closing the window, the System do it when i shut it down but Ubuntu doesn't shut down, it just close telegram without shutting down itself. I have to shut down the system two times:
- the first it just close the telegram window
- the second it shuts down.

**Comment by auchri** [comment]
@Ocelot92 is there any way to get logs from telegram? Or is there another way to figure out why this happens?

**Comment by auchri** [comment]
Closing this because of #633
