### ISSUE TITLE
Not find for a string of numbers

### ISSUE THREAD

**Issue by McFris** [telegramdesktop/tdesktop#5270]
### Steps to reproduce
1. Open Desktop for Windows
2. Search for digital string ("137" for example)

### Expected behaviour
Find the string in dialog.

### Actual behaviour
No find any string in dialog

### Configuration
Windows 10 1809

**Version of Telegram Desktop:**
1.4.3

**Used theme**:
Midnight

<details><summary><b>Screenshot</b>:</summary>
![default](https://user-images.githubusercontent.com/28977647/47065295-2569a380-d1eb-11e8-8200-8cfe654e6a23.png)
</details>

**Comment by Aokromes** [comment]
it's working on 1.9.8

**Comment by McFris** [comment]
The search still does not work if you plan to search not for a single word but for its content. 
Examples in the screenshots:
![4](https://user-images.githubusercontent.com/28977647/73133760-5d8ea180-403e-11ea-9097-2b9acdf846aa.JPG)
![3](https://user-images.githubusercontent.com/28977647/73133761-5e273800-403e-11ea-9f0a-1688c0996192.JPG)

It also applies a fuzzy search and searches for words other than expected:
![2](https://user-images.githubusercontent.com/28977647/73133764-63848280-403e-11ea-98de-183b907643fe.JPG)
![1](https://user-images.githubusercontent.com/28977647/73133765-63848280-403e-11ea-8150-199df5604f2f.JPG)

**Comment by Aokromes** [comment]
the 2nd "thing" https://github.com/telegramdesktop/tdesktop/issues/7022
