### ISSUE TITLE
What about 75% for interface scaling?

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#5272]
As you've just implemented 250% and 300% for HiDPI screens (1.4.4 build), I would be so satisfied with 75% for non-FullHD displays. It could relax my eyes, because font and UI elements are too large at default scaling (100%). Seems It's not extremely hard to implement. 🤷‍♂️ 

I'm aware of previous issues (for <100% scaling), so just remember that problem has not been solved yet. 🙏🙏

**Comment by john-preston** [comment]
@Twilightssuperb It's interesting to try. It could have some problems with lines becoming less than one pixel. But this could be fixed of course.

**Comment by Twilightssuperb** [comment]
Thx for reply. Well, you can force smallest scaling level to 80% in a pinch, if it could solve some troubles. :) I'm ready to test it in future beta builds.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1121

**Comment by Twilightssuperb** [comment]
@john-preston, thank you very much. Finally u did it. Congratulations. 👏👏👏 I'm not a design geek, even though I see some disadvantages, I'm just glad to have smaller UI at my old laptop. ☺️
