### ISSUE TITLE
Cannot set scaling back to previous value (see description)

### ISSUE THREAD

**Issue by gubenkovalik** [telegramdesktop/tdesktop#5274]
i scaled it up to 300% and i can't click on settings button to make the scale back to previous, because simply the settings button goes beyond the screen and it is impossible to revert changes back using UI.
![image](https://user-images.githubusercontent.com/5104168/47136837-95485e80-d2bd-11e8-980a-5c2246b891ed.png)
![image](https://user-images.githubusercontent.com/5104168/47136979-f8d28c00-d2bd-11e8-91d1-80c207cd3291.png)

**Comment by RememberTheAir** [comment]
Had the same problem. I think Telegram should ask on restart if the changes are ok and revert back to the previous scaling if no answer is given in 15 seconds, more or less in the same way the themes preview works

**Comment by RememberTheAir** [comment]
I've been able to restore the default settings by removing `Telegram/tdata/settings0`

**Comment by WPFilmmaker** [comment]
I still have this issue on Lubuntu 18.04 and Telegram 1.8.15.
I accidentally entered fullscreen mode and now I am stuck there. First, how do you toggle/untoggle fullscreen normally?which shortcut?

Where is the telegram folder? I tried /usr/share but there is no telegram folder either.

in ·#4583 it is suggested to check /home/myusername/.local/share but I have no file called settings1 :(

**Comment by Aokromes** [comment]
hackaround for scale, use the commandline to return to 100% scale.

**Comment by WPFilmmaker** [comment]
@Aokromes Sorry for being dumb but what do I have to type in the commandline ?

**Comment by 23rd** [comment]
According to this 01b4e1946a619010028d2dd2730d507f67066087 commit, the problem was solved a year ago.

![image](https://user-images.githubusercontent.com/4051126/71117049-6c379c80-21e6-11ea-9a56-c32d7def3d3c.png)

**Comment by WPFilmmaker** [comment]
@23rd well if that commit was released, I have to say that it has not fixed the issue...I have latest version (from the updates I get on my system) and I still have the issue..
