### ISSUE TITLE
Qt dependency issue Debian Sid

### ISSUE THREAD

**Issue by padawin** [telegramdesktop/tdesktop#5275]
When installing telegram on debian sid, there is a dependency error occuring regarding `qtbase-abi-5-11-0`.

### Steps to reproduce
1. Try to install telegram with apt:
```
root@ubuntu:~# apt-get install telegram-desktop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 telegram-desktop : Depends: qtbase-abi-5-11-0
E: Unable to correct problems, you have held broken packages.
```

### Expected behaviour
Telegram should be installed.

### Actual behaviour
The installation fails. The .deb file expects a fixed version of qtbase-abi, having another version creates this error.

### Configuration
```
root@ubuntu:~# apt-get install libqt5core5a
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqt5core5a is already the newest version (5.11.2+dfsg-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
```
ghislain@ubuntu: /tmp ✔
> cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
ghislain@ubuntu: /tmp ✔
> uname  -a
Linux ubuntu 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-10-07) x86_64 GNU/Linux
```
My system in freshly updated (last update yesterday)

### Suggested fix

I manually solved it by downloading the .deb file from debian's repo, extracted it and changed the dependency in the file `control` as follow:
```patch
diff --git a/control b/control
index 476628d..f497bfb 100644
--- a/control
+++ b/control
@@ -3,7 +3,7 @@ Version: 1.4.0-1
 Architecture: amd64
 Maintainer: Nicholas Guriev <guriev-ns@ya.ru>
 Installed-Size: 42932
-Depends: qt5-image-formats-plugins (>= 5.5), libavcodec58 (>= 7:4.0), libavformat58 (>= 7:4.0), libavutil56 (>= 7:4.0), libc6 (>= 2.27), libgcc1 (>= 1:3.0), libglib2.0-0 (>= 2.12.0), liblzma5 (>= 5.1.1alpha+20120614), libminizip1 (>= 1.1), libopenal1 (>= 1.14), libopus0 (>= 1.1), libqt5core5a (>= 5.11.0~rc1), libqt5dbus5 (>= 5.5), libqt5gui5 (>= 5.6.0~beta), libqt5network5 (>= 5.5), libqt5widgets5 (>= 5.5), libssl1.1 (>= 1.1.0), libstdc++6 (>= 5.2), libswresample3 (>= 7:4.0), libswscale5 (>= 7:4.0), libx11-6, libxxhash0, qtbase-abi-5-11-0, zlib1g (>= 1:1.1.4)
+Depends: qt5-image-formats-plugins (>= 5.5), libavcodec58 (>= 7:4.0), libavformat58 (>= 7:4.0), libavutil56 (>= 7:4.0), libc6 (>= 2.27), libgcc1 (>= 1:3.0), libglib2.0-0 (>= 2.12.0), liblzma5 (>= 5.1.1alpha+20120614), libminizip1 (>= 1.1), libopenal1 (>= 1.14), libopus0 (>= 1.1), libqt5core5a (>= 5.11.0~rc1), libqt5dbus5 (>= 5.5), libqt5gui5 (>= 5.6.0~beta), libqt5network5 (>= 5.5), libqt5widgets5 (>= 5.5), libssl1.1 (>= 1.1.0), libstdc++6 (>= 5.2), libswresample3 (>= 7:4.0), libswscale5 (>= 7:4.0), libx11-6, libxxhash0, libqt5core5a (>= 5.11.0), zlib1g (>= 1:1.1.4)

 Recommends: fonts-open-sans
 Built-Using: libtgvoip (= 2.2.4-1), mapbox-variant (= 1.1.5-3), ms-gsl (= 1.0.0-2), range-v3 (= 0.3.7-1)
 Section: net
```

The only change is `qtbase-abi-5-11-0` changed into `libqt5core5a (>= 5.11.0)`

Then recreated the .deb file and installed it:

```
root@ubuntu:/tmp# dpkg -i telegram-desktop_1.4.0-1_amd64-new.deb
Selecting previously unselected package telegram-desktop.
(Reading database ... 237311 files and directories currently installed.)
Preparing to unpack telegram-desktop_1.4.0-1_amd64-new.deb ...
Unpacking telegram-desktop (1.4.0-1) ...
Setting up telegram-desktop (1.4.0-1) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.61) ...
Processing triggers for gnome-menus (3.13.3-11) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.8.4-2+b1) ...
```

I'd happily create a pull request, however I am not sure where the sources for the .deb file live.

**Version of Telegram Desktop:**
1.4.0-1

**Comment by Johnnynator** [comment]
You should report this to the debian team. This repo here is only fur issues with the client and not responsible how distros package it.

**Comment by padawin** [comment]
Hi @Johnnynator,

Thanks for your update, I am happy to close this one.
Two questions though first:
- where is the repo/bug tracker of the debian team?
- what would be a better solution to have the software installable? That is maybe more of a generic packaging question.

**Comment by Johnnynator** [comment]
>     * where is the repo/bug tracker of the debian team?

Use some search engine: https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=telegram-desktop;dist=unstable . There is a report button, but I'm not familiar with the way debian tracks bugs so I can't really help you with that.

>     * what would be a better solution to have the software installable? That is maybe more of a generic packaging question.

Imo the distro packaging is ok and works around some other issues. The other way would be to use the official binary avaible on the [telegram website](https://desktop.telegram.org/) but it afaik has some problem with recent fontconfig versions see e.g. #4240

**Comment by padawin** [comment]
Thanks!
It has actually already been addressed.... this morning :-)
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911288
