### ISSUE TITLE
More readable tooltips in the night theme

### ISSUE THREAD

**Issue by Remu-rin** [telegramdesktop/tdesktop#5276]
### Steps to reproduce
1. Hover mouse over a link

### Expected behaviour
TooltipBG and tooltipFG color combination should be more readable, like in other 3 themes. E.g. darker tooltip text:
![-1](https://user-images.githubusercontent.com/28995228/47150740-fe959500-d2f0-11e8-9436-fadc9ed2d6d9.png)

### Actual behaviour
Combination is bad and stresses eyes:
![-2](https://user-images.githubusercontent.com/28995228/47150810-34d31480-d2f1-11e8-9b93-253fe7aaffcf.png)

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.4.3

**Used theme**: Matrix

**Comment by Remu-rin** [comment]
Also maybe it's better to change tooltipBG or borderBG in Midnight theme too? Currently tooltip blends with background of the message:
![-3](https://user-images.githubusercontent.com/28995228/47152745-f4769500-d2f6-11e8-8831-7f62b4cefd93.png)

**Comment by Aokromes** [comment]
this theme ain't official no?

**Comment by Remu-rin** [comment]
It's still official Night theme. Back then called Matrix. Only one of four that have this problem.
![screen](https://user-images.githubusercontent.com/28995228/73163858-9bf59080-4112-11ea-8cd1-18130f109091.png)

**Comment by Aokromes** [comment]
ah ok.

**Comment by Remu-rin** [comment]
Not resolved.

**Comment by Remu-rin** [comment]
Still relevant.

**Comment by Remu-rin** [comment]
Somewhat fixed in https://github.com/telegramdesktop/tdesktop/commit/cb630c69f004be568d5c25f4072e01e8340b5174, though I would prefer a little brighter text for contrast.
![image](https://user-images.githubusercontent.com/28995228/123491394-ff4d6000-d62f-11eb-836f-c1791429cfb2.png)
