### ISSUE TITLE
[bug] Alt+Shift+Click on 'change language' doesn't open dialog for change language

### ISSUE THREAD

**Issue by ezdev128** [telegramdesktop/tdesktop#528]
Alt+Shift+Click on 'change language' doesn't open dialog for change language.

Linux Mint 64bit.

**Comment by ezdev128** [comment]
As one person reported, it is conflict between language keyboard layout buttons change (Alt+Shift). 
@telegramdesktop, I suggest to change this to Ctrl+Click instead of Shift+Alt+Click

**Comment by Katzen-Gott** [comment]
Then it will conflict with Ctrl+Shift which some users use to switch layouts. There must be some other solution to this problem.

**Comment by ezdev128** [comment]
@Katzen-Gott Probably you're right.
Maybe just add additional button "load localization" or so...

**Comment by auchri** [comment]
Improved with 0.8.50 dev (you can load custom localization by typing "loadlang")
