### ISSUE TITLE
message still unreaded in task bar after read on the phone

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#5280]
### Steps to reproduce
I got the message
I read the message on the phone (android)
Back to PC with Telegram desktop
 main window: readed
 system tray icon: readed
 task bar: UNREADED, counter with RED background
Unreaded status disappears after read random muted channel

### Expected behaviour
Readed in all places

### Configuration
**Operating system:**
win 10 x64 1803
**Version of Telegram Desktop:**
1.4.4
**Used theme**:
@darkorangetheme
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by f242** [comment]
need to test

**Comment by f242** [comment]
still valid, to reproduce bug you need to wait about 1 hour after recieve a new message then to read in on phone then go to PC with running telegram desktop and check

**Comment by arjunluthra** [comment]
See this issue every day, any idea on eta?

**Comment by arjunluthra** [comment]
Keeping issue not stale.

**Comment by ilya-fedin** [comment]
> See this issue every day, any idea on eta?

Qt provides no public api to unflash the taskbar, so this issue seems to be unfixable

**Comment by arjunluthra** [comment]
I'm less concerned with the flash but the icon (the flash seems new to be honest) here is what I see at the beginning: 
<img width="116" alt="taskbar0" src="https://user-images.githubusercontent.com/15164684/97365823-8ceb6c80-1863-11eb-80e7-33f6f117e1b9.png">

and then after I read the message:
<img width="158" alt="taskbar1" src="https://user-images.githubusercontent.com/15164684/97365844-996fc500-1863-11eb-92eb-de56d5625851.png">

We've marked the title from Telegram (1) to Telegram but the icon still has the red 1 but there is no message to read.  Not sure if @f242 is looking at the flash being orange or the icon being red with the 1.

**Comment by arjunluthra** [comment]
Keeping issue not stale.

**Comment by arjunluthra** [comment]
keeping not stale.
