### ISSUE TITLE
Preview on dual monitor

### ISSUE THREAD

**Issue by JoLong** [telegramdesktop/tdesktop#5281]
I don't know if this is the right place, but i didn't find anything about it. i have a dual monitor setup, and if i try to open a preview of something, it opens on the second monitor fullscreen, instead of the main one.

### Steps to reproduce
1. don't know if its just his behaviour, but just open a photo.

### Expected behaviour
there is a method to open it on my main monitor? i get the comodity of opening it on the second, but there is a switch for this or something?

### Actual behaviour
it displays the preview on just the second monitor.

### Configuration
Windows 10 Pro, telegram desktop 1.4.3, dark theme.

**Comment by Dramacydal** [comment]
Same on Centos
https://youtu.be/Z9qHFGZu8gI

**Comment by poschi3** [comment]
I have the same problem for about a month or so. In the past the full screen picture opened on the monitor where the chat window is. But now it's always on a wrong monitor (3 monitors setup). 

**Configuration**
Linux Mint 18.3 Cinnamon, Telegram Desktop 1.4.3, classic theme

**Comment by stek29** [comment]
see #5048

**Comment by JoLong** [comment]
sincerely i don't get the topic you have linked, i think it's a different problem.
I'm replying to this post becouse i have kinda find a solution:
if i keep the window of telegram on the main screen, and open a preview of something, the preview goes to the second screen ( even this behaviour is random, sometimes it does it, sometime no ). To make the preview to go on the main screen, where the telegram windows is, i just need to "shake" the window itself by picking it from the top, drag it around the screen for a second or two, and then when i open a preview, it will be displayed on the main screen, and it will always do it as far as a see, atleast until i reboot the system. i don't get why, but i'll keep watching over it.

**Comment by stek29** [comment]
@JoLong this is yet another issue caused by some changes in preview window flags, so that's why I am closing it as a duplicate

**Comment by poschi3** [comment]
@JoLong @stek29 I think #5126 would be a better ticket to mention
