### ISSUE TITLE
[Feature request] Sticker groups or sticker folders

### ISSUE THREAD

**Issue by daiplusplus** [telegramdesktop/tdesktop#5285]
(I would normally fork the project and have an implementation to demo, however the CONTRIBUTING file says that you don't accept changes that make changes to the UX, so I'm just submitting a feature request instead)

### The Problem

I have a lot of sticker packs in my account, about 70 packs with an average of ~30 stickers per pack. Navigating this list of stickers becomes a chore on all the current platforms, but especially on Windows desktop where the current UI is inadequate for navigating large sticker packs:

* The UI, even on desktop, is clearly intended to be used as a touch-first UI, however:
  * Scrolling the list using a traditional ("notched", not smooth/free-spinning) mouse-wheel is slow: each wheel movement only moves the list down 1 row.
  * The vertical scrollbar is very narrow and difficult to target with the mouse, and dragging the scroll thumb can scroll the list too quickly given how small the sticker selection window is, and when scrolling quickly the thumbnails don't load in time so it's difficult to see where in the list you are.
  * The horizontal sticker-set scroller is too narrow to be useful as it only shows 5 sticker packs at a time, the fade-out effect on the side reduces the useful viewing area, and it's difficult to scroll on a PC as you have to drag it with the mouse (which is awkward) or scroll it with a mouse wheel (which often moves too fast).

However, in my case at least, my multiple sticker packs can be logically grouped together (e.g. sticker packs by the same artist, sticker packs regarding the same subject matter, ironic vs non-ironic stickers, etc) - and I'd like to be able to perform that grouping within Telegram.

By drilling-down through groups first, I can find the sticker I want by skipping sticker packs I know I don't want.

I have no preference between flat folders, hierarchical folders (where a sticker pack can exist in only 1 folder at a time), or a "tag" based system where a pack can appear in multiple folders at the same time.

### Configuration
**Operating system:**
Windows 10 Pro (Version 1809)

**Version of Telegram Desktop:**
1.4.3

**Comment by Remu-rin** [comment]
Tag system sounds best. When search in sticker packs implemented, it made stickers usage much better (though it isn't available in list of archived packs, which would be nice too). And it would be even better if user could assign custom tags for packs (saved as local setting until logout), so they can be searched not only by name/link by it's creator.

**Comment by ATecha** [comment]
I like the idea of a tag system as well. For me, some packs have multiple uses, or are giant unorganized collections themselves.

Relatedly, I'd like to see tagging (or some form of organization) for gifs as well. Whatever is implemented for stickers could also be used for gifs.
