### ISSUE TITLE
jom -j4 outputs "Error: File Makefile doesn't exist."

### ISSUE THREAD

**Issue by sangimed** [telegramdesktop/tdesktop#5287]
Hi, 

I'm building the project under Visual Studio 2017 (by following the [guide](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md)) I get this : 
```
C:\Repositories\Telegram\TBuild\Libraries\qt5_6_2\qtbase (HEAD detached at b4ada3f -> origin)
λ ..\..\..\Libraries\..\ThirdParty\jom\jom.exe -j4 install
Error: File Makefile doesn't exist.
```
Everything before this step went well.

**Comment by 23rd** [comment]
Outdated. Please reopen it if you still have this error.
