### ISSUE TITLE
farsi fonts distorted after upgrading ubuntu 18.04 to 18.10

### ISSUE THREAD

**Issue by amirian** [telegramdesktop/tdesktop#5288]
No problem in Ubuntu 18.04 LTS, but after upgrading to 18.10, farsi font is displayed correctly in all applications except Telegram Desktop 1.4.3. I installed additional farsi system fonts and changed the default font but the issue remains.
I had previously installed freeType2 for use in some application and had no issue. May this cause the problem?

**Comment by amirian** [comment]
[This is a screenshot]("https://cdn1.imggmi.com/uploads/2018/10/20/f02e5e2a10573c2f2b181b99a9d98271-full.png")

**Comment by amirian** [comment]
![font](https://user-images.githubusercontent.com/1963455/47252437-fb65ea80-d451-11e8-8ce1-b5c5d9962a50.png)

**Comment by xvitaly** [comment]
>  I had previously installed freeType2 for use in some application and had no issue. May this cause the problem?

Official build use their own very outdated static version of freetype library. Install Telegram Desktop from repositories and it will work fine.

**Comment by YousefSaber** [comment]
@xvitaly except that the distro repository isn't always up to date 

for example the distro repo version of telegram is 1.4.0

**Comment by xvitaly** [comment]
> for example the distro repo version of telegram is 1.4.0

I think you can install more recent version from updates-testing repository.

> I'm also facing the same issue on arabic font

You cannot fix it in official build.

**Comment by YousefSaber** [comment]
@xvitaly I don't think that there is a way to install a testing version of an app from ubuntu repository

I hope that you'll fix this issue soon on your official desktop executable app

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5172
