### ISSUE TITLE
fctix input frame and google pinyin input method can't work with it well

### ISSUE THREAD

**Issue by mrwd2005** [telegramdesktop/tdesktop#529]

**Comment by vipjeffreylee** [comment]
https://github.com/telegramdesktop/tdesktop/issues/375#issuecomment-76573660

**Comment by taijuin** [comment]
the answer is in : #375

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.
