### ISSUE TITLE
Telegram Desktop Linux touches its Updater constantly, forcing indexing service to eat CPU time

### ISSUE THREAD

**Issue by kode54** [telegramdesktop/tdesktop#5290]
### Steps to reproduce
1. Install Kubuntu Linux 18.04.1.
2. Install Portable Telegram Desktop to user home directory.
3. Launch Telegram.

### Expected behaviour
Telegram Desktop should periodically check for updates.

### Actual behaviour
Telegram Desktop runs the equivalent of `touch Updater` nonstop, causing the Baloo file indexer to index it nonstop, eating up a full processor core 24/7 with the baloo_file_extractor, unless the Baloo service is disabled, then the baloo_file_extractor manually killed. It still presumably writes to my SSD nonstop as it's touching the modification timestamp on the file.

### Configuration
**Operating system:**
Kubuntu Linux 18.04.1

**Version of Telegram Desktop:**
1.4.3

**Used theme**:
Midnight Blue

Edit: Never mind, it's not touching it, but the indexer did get caught in an indexing loop on the Updater file.

**Comment by stek29** [comment]
> Never mind, it's not touching it, but the indexer did get caught in an indexing loop on the Updater file.

**Comment by kode54** [comment]
But whose fault is it that the indexer gets stuck on your file? KDE's fault? Ubuntu for patching their own version of KDE?

**Comment by stek29** [comment]
@kode54 why do you think it's Telegram's fault?

**Comment by kode54** [comment]
I’ll report it to KDE, then. It’s probably their fault for trying to process executable files with their indexer.
