### ISSUE TITLE
Feature Request: Hide Gifs & Stickers 

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5292]
Hiding Gifs & Stickers in workmode with small icons for gifs  and corresponding emoji for stickers

**Comment by SmartManoj** [comment]
Also disable preview links

**Comment by Aokromes** [comment]
where is no workmode anymore.

**Comment by SmartManoj** [comment]
> where is no workmode anymore.

> There is no workmode anymore?
