### ISSUE TITLE
Channels/chats/groups with notifications turned on should be on top of the chat list when there are notifications in these chats

### ISSUE THREAD

**Issue by petercommand** [telegramdesktop/tdesktop#5293]
### Expected behaviour
Tell us what should happen
Channels with notifications turned on should be on top of the channel list when there are notifications. Beside the pinned chats, channels/groups/chats with notifications turned on should be on top of the list when there are notifications in these channels/groups/chats.

### Actual behaviour
Tell us what happens instead
Beside the pinned chats, all other channels/chats/groups in the channel(chats) list are sorted by the time the last message in the chat was sent.
### Configuration
**Operating system:**
OSX 10.13.3
**Version of Telegram Desktop:**
1.1.18

**Comment by stek29** [comment]
please, update TDesktop, and check out work mode.
#2590
