### ISSUE TITLE
Feature Request: Stop spamming me with a "update Telegram" window every single time I open up Telegram

### ISSUE THREAD

**Issue by basickarl** [telegramdesktop/tdesktop#5294]
I'm sitting on a Mac.

So I use Telegram a lot and the thing that annoys me the most is the FREQUENT REQUESTS TO UPDATE THE APPLICATION.

Every. Single. Time. I open the application it opens another window in my face telling me to update. This is infuriating.

This should be...: 
1) In-built either into the application, so like a bar running across the whole bottom alerts you, THEN DISAPPEAR after i.e. 5 seconds.
2) I should be able to set how often this update window appears (i.e once every 2 weeks).

**Comment by john-preston** [comment]
@basickarl You're speaking not about Telegram Desktop but about another Telegram app. You can try Telegram Desktop from https://desktop.telegram.org

**Comment by basickarl** [comment]
@john-preston Ah, I see. So I probably have: https://macos.telegram.org/ ? Here is a screenshot of the version I have.

https://imgur.com/a/8Aizi8S

**Comment by basickarl** [comment]
Ah thank you, I see that I had the other one installed. Removed it, thanks!
