### ISSUE TITLE
High CPU issue on reconnecting

### ISSUE THREAD

**Issue by Xeno22** [telegramdesktop/tdesktop#5295]
### Steps to reproduce
1. Start Telegram
2. Restart your internet gateway/router
3. 

### Expected behaviour
It should try to reconnect, but not use so much CPU time for the spinning reload icon.

### Actual behaviour
High CPU usage while reload icon is spinning.

### Configuration
Mac OS 10.14.1 Beta (18B67a)

**Version of Telegram Desktop:**
1.4.3

**Used theme**:
No idea.

<details><summary><b>Logs</b>:</summary>
Where to find?</details>

**Comment by alexkoster** [comment]
I too have experienced high CPU usage on telegram 1.4.3 x86_64 official build running on both Fedora 27 and Fedora 29 Beta (both latest updates and on kernel 4.18.16).  It takes upwards of 30 seconds to start telegram desktop while it uses 100% of a single core's CPU doing so.  Once it launches, it seems the CPU (and memory) usage dies down.  Also would be happy to post logs once I find out how to generate them :-)

**Comment by stek29** [comment]
@alexkoster this issue seems to be different and not related to #4240 -- as well as #5181.

**Comment by stek29** [comment]
Interestingly, it goes down when you disable animations.

**Comment by xvitaly** [comment]
@alexkoster Install version from RPM Fusion. It works fine with no issues.

**Comment by Mhs-220** [comment]
same issues here on Ubuntu 18.04, gnome desktop and installed telegram from snap.

**Comment by dikderoy** [comment]
Easy way to reproduce:
it happens then using socks5/mt-proto proxy, if proxy went down but internet connection is okay the same issue appears.

**Comment by dantimofte** [comment]
I have the same issue.
Macos Mojave, 10.14.2
Telegram desktop 1.5.3
How to reproduce : disable wifi with telegram desktop open

**Comment by nortexoid** [comment]
Probably best to remove animated icons showing that it will try to reconnect in n seconds. Probably best to remove animated icons altogether. I have the same issue on Manjaro KDE. Even when minimized so there's no repaints, Telegram is still constantly taking more cpu than needed.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by dantimofte** [comment]
Hi, it looks like it's not going into 100% anymore, 

It gets as high as 25% now in idle mode when disabling the wifi , and it's at about 2% in idle mode with  wifi  enabled.
