### ISSUE TITLE
Insertion Point is missing 

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5297]
Insertion point while navigating the text.
Its hard to find where is the insertion point while editing the text.
Currently it is hidden.
It is better to show it when it is not in the end of the text

**Comment by SmartManoj** [comment]
Again missing.
After restarting app , it shows

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/62313862-60ee0980-b4af-11e9-88d3-b80d8578ad27.png)

**Comment by SmartManoj** [comment]
Bug

**Comment by SmartManoj** [comment]
### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.7.14

**Used theme**: Midnight

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Comment by SmartManoj** [comment]
Seems no

> this bug is still valid?
