### ISSUE TITLE
Middlemouse-paste does not work correctly. (Linux)

### ISSUE THREAD

**Issue by ManuelSchneid3r** [telegramdesktop/tdesktop#530]
Marking some text in the conversation area does not copy the marked text for the (linux only) middlemouse-paste feaure. 

Short background cite from [archwiki](https://wiki.archlinux.org/index.php/clipboard):

> The ICCCM (Inter-Client Communication Conventions Manual) standard defines three "selections": PRIMARY, SECONDARY, and CLIPBOARD. Despite the naming, all three are basically "clipboards". [...]
> Of the three selections, users should only be concerned with PRIMARY and CLIPBOARD. SECONDARY is only used inconsistently and was intended as an alternate to PRIMARY. Different applications may treat PRIMARY and CLIPBOARD differently; however, there is a degree of consensus that CLIPBOARD should be used for Windows-style clipboard operations, while PRIMARY should exist as a "quick" option, where text can be selected using the mouse or keyboard, then pasted using the middle mouse button (or some emulation of it). This can cause confusion and, in some cases, inconsistent or undesirable results from rogue applications.

**Comment by aluminiumgeek** [comment]
+1 
#961

**Comment by lindhe** [comment]
+1

**Comment by auchri** [comment]
Use the new [reactions of GitHub](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) on **the first entry of this issue** instead of creating unnecessary `+1` comments.

**Comment by lindhe** [comment]
Oh, yeah, sorry. Forgot that was a thing.

**Comment by ManuelSchneid3r** [comment]
As far as I can tell this is not an issue anymore.

**Comment by ManuelSchneid3r** [comment]
Thank you
