### ISSUE TITLE
Official GmailBot Bug

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5300]
[GmailBot](https://t.me/gmailbot)
After specifying To address, it replies Unknown command. Say what?
Not removing Force reply after sending mail.
Where to report this error?
How to get verified badge for bots?

**Comment by RememberTheAir** [comment]
> Where to report this error?

Tweet to @telegram or ask to the in-app support

> How to get verified badge for bots?

Ask to [@BotSupport](https://t.me/botsupport)

**Comment by SmartManoj** [comment]
Asked in April 21 in in-app support

**Comment by RememberTheAir** [comment]
Try to ping them again, anyway this is not the right place where to report bots bugs

**Comment by SmartManoj** [comment]
https://twitter.com/manojkumarkok/status/1055429803984117761 25 Oct 2018
Mailed To security@telegram.org Yesterday 
Still no reply

**Comment by SmartManoj** [comment]
Moved to https://t.me/tgbetachat/128878
