### ISSUE TITLE
[Feature request] Group tab for Private, groups and bots chat

### ISSUE THREAD

**Issue by Ansem93** [telegramdesktop/tdesktop#5303]
Hi everyone,
It would be possibile to have an option to enable group tabs for Private chats, groups chats an bots chat?

**Comment by RememberTheAir** [comment]
Duplicate of #1107 (the main one) and many many many other

**Comment by stek29** [comment]
no, the other issue isn't about searching. also, it's kinda a meta issue for "tabs pls"

**Comment by kenorb** [comment]
Related: GH-5560
