### ISSUE TITLE
CarPlay support?

### ISSUE THREAD

**Issue by ahorseman** [telegramdesktop/tdesktop#5304]
Dear Telegram Desktop team,

sorry if I post this here, but I wasn't able to find any other address to post it and regret if it's misplaced (I found no project for Telegram iOS/Android/... on Github). But I'd like to ask whether there is any plans to support Apple CarPlay / Android Auto with Telegram, so it can be used while driving to receive and response to messages.

Thank you.

**Comment by RememberTheAir** [comment]
+1 for AppleCar/AndroidAuto support, but yes this isn't the proper place. If you haven't tried already, you can contact them on [Twitter](https://twitter.com/telegram) or via the in-app support
