### ISSUE TITLE
Icon tray doesn't show in Juno elementary OS update !

### ISSUE THREAD

**Issue by YousefSaber** [telegramdesktop/tdesktop#5306]
as you can see in the screenshot 

![image](https://user-images.githubusercontent.com/33742499/47521923-9288d300-d894-11e8-96d1-e25d2cc09e90.png)

**Operating system:**
elementary OS ( linux distro ) v5.0 
**Version of Telegram Desktop:**
1.4.3

**Comment by MasterGroosha** [comment]
AFAIK there's no "tray" at all in Juno. You'll have to add it via third-party apps.
