### ISSUE TITLE
memers not removed from the list after they leave supergroups.

### ISSUE THREAD

**Issue by aranmohyeddin** [telegramdesktop/tdesktop#5309]
### Steps to reproduce
1. join a supergroup
2. make the right menu visible(so you have 3 areas, your contacts to the left, chat in the middle and group info to the right
3. have someone else leave the group

### Expected behaviour
Their picture and name should be removed from the list of members in the right pane

### Actual behaviour
The number of members decreases but the leaved member can still be found on the list so the actual number of the elements of the list would be the numbers shown for the member count of the group + 1

### Configuration
**Operating system:**
Linux 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
**Version of Telegram Desktop:**
1.4.3
**Used theme**:
dark

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
