### ISSUE TITLE
[Feature Request] Custom emoticon

### ISSUE THREAD

**Issue by raphaelbastide** [telegramdesktop/tdesktop#531]
The large character emoticons are cool. I would love to create my own to make my friends laugh. I suggest a “upload” button that accepts png for transparency, gif animations can be awesome as well.

![selection_048](https://cloud.githubusercontent.com/assets/193122/6465416/4bab83d0-c1c1-11e4-900e-b6946ae2a810.png)

**Comment by auchri** [comment]
To share stickers of your own, just save your sticker in WebP format with a transparency layer and send it to your friend as a document in Telegram. It will be shown as a sticker.

More information here: https://telegram.org/blog/stickers

**Comment by raphaelbastide** [comment]
Dear @auchri, this is a really good news. I just tried it and it works like a charm!
Thank you for sharing this article. Next step: make those custom emoticons available everywhere.
I guess this issue can be closed as you answered my question.
