### ISSUE TITLE
Show in Folder not working properly

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5311]
### Steps to reproduce
1.  Click show in folder 

### Expected behaviour
Opens explorer

### Actual behaviour
Opens explorer and again switched to Telegram

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.4.3

**Used theme**:Mid-night

**Comment by john-preston** [comment]
@SmartManoj Thanks for the report. I'll fix that in the next version.
