### ISSUE TITLE
Copying and pasting messages with hyperlinks pastes the link twice

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#5313]
### Steps to reproduce
1. copy a message with an [hyperlink](https://github.com/telegramdesktop/tdesktop)
2. paste it in the input box

### Expected behaviour
The text is paste formatted, as it was copied

### Actual behaviour
The text is pasted formatted, but each hyperlink will have its link pasted next to it (eg. "_[hyperlink](https://github.com/telegramdesktop/tdesktop)_" becomes "_[hyperlink](https://github.com/telegramdesktop/tdesktop) (https://github.com/telegramdesktop/tdesktop)_"

I suppose this behaviour comes from the time when Telegram Desktop wasn't able to handle message entities like it does now (hyperlinks were pasted as simple text). Now when you paste the formatted text, the same link is included twice and I have to manually remove the link within brackets manually

### Configuration
**Version of Telegram Desktop:** 1.4.4 beta

**Comment by stek29** [comment]
#4751
