### ISSUE TITLE
telegram snap client passing url to file manager instead of firefox

### ISSUE THREAD

**Issue by zombiehoffa** [telegramdesktop/tdesktop#5314]
### Steps to reproduce
1. install telegram snap on lxqt 18.10
2.  click a link in a chat
3.  watch it append /home/username/ to the url  (i.e. /home/username/http://etc,etc) and not open the link because that is sent to the file manager not firefox.

### Expected behaviour
Tell us what should happen click a link, default web browser (which is firefox in my case) opens up or adds a new tab with the link opening in it.

### Actual behaviour
Tell us what happens instead err message claiming no such file or directory.

### Configuration
**Operating system:** lubuntu 18.10

**Version of Telegram Desktop:**
1.4.3 downloaded through ubuntu snapstore
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by zombiehoffa** [comment]
I assume so. I deleted Firefox to make URLs go to brave but that's not the
ideal behavior.

**Comment by ilya-fedin** [comment]
Please try on 1.9.9, now it uses the common desktop-qt5 snap integration

**Comment by Aokromes** [comment]
plz test on 1.9.17. if no answer of still bug i will close this issue on 7d.

**Comment by zombiehoffa** [comment]
unfortunately I  have switched operating systems since I posted this and no
longer have the ability to test this.
