### ISSUE TITLE
Feature request: Telegram feed

### ISSUE THREAD

**Issue by r57zone** [telegramdesktop/tdesktop#5315]
It would be cool to make a common single feed for channels (maybe optional). Reading new messages in one section is much more convenient.

I would also like some kind of division: "Feed" (and somewhere editing and adding new ones), "Contacts", "Chats".

**Comment by 23rd** [comment]
At the beginning of this year, preston wrote a lot of code for supporting feed, but apparently he had to suddenly get distracted by other features, such as the Telegram Passport.

https://github.com/telegramdesktop/tdesktop/commit/c3c9ba7e51e7e0e302b60c75109c2fb0593785a1

**Comment by stek29** [comment]
@23rd the feature was pretty much cancelled

**Comment by 23rd** [comment]
@stek29 Well, probably it's better to remove this code or move it to separate branch.

**Comment by r57zone** [comment]
So the telegram channels will never replace the usual reading sites or social networks.

**Comment by RememberTheAir** [comment]
@r57zone yeah that's pretty much because they're not meant to replace news sites or social networks ¯\\\_(ツ)\_/¯

**Comment by r57zone** [comment]
@RememberTheAir then it was not necessary to do make channels, since they are inconvenient to read.
