### ISSUE TITLE
[REQUEST] Option to select the sent quality images

### ISSUE THREAD

**Issue by leiniercs** [telegramdesktop/tdesktop#5317]
Hello Telegram staff.

I would love to see an option in Telegram Desktop that allow the user to select the quality to use to send images: low, medium and high. Happens that the current version of Telegram Desktop send images in very low quality. when I want to send an image in high quality I must to send it as an archive.

On the other hand, you are making a great job. congratulations

**Operating system: Debian GNU/Linux 9

**Version of Telegram Desktop: 1.4.3

**Used theme**: Dark

**Comment by emreyarligan** [comment]
You can already send without compression, it means your image will be sent maximum quality. (I know that you know it) . And other option is "quick way" for sending, too many choices for everything is not a good idea because some people may want to send "quickly".

**Comment by leiniercs** [comment]
???

Did you read the entire message?

I made a request for an option in future versions. Of course that we can send images without compression by sending it as an archive (i wrote that in the previous message), but that is not the idea, because others can't visualize it until they download the archive. The idea is to give users the possibility, through and option, to select the quality of the image when we send them, and the others can receive them in that quality as an image message.

Hope TD developers can see this request as valid. If not, everything will continue OK :)

**Comment by Twilightssuperb** [comment]
+1. Plus Messenger allows users to choose random/constant JPEG quality level before sending something as picture. I choose 100%. Sometimes I need this option in groups and channel publishing.

**Comment by 23rd** [comment]
Unfortunately, the server itself compresses the photos, so the choice of 100% quality is almost useless.
As for the TDesktop, it compresses photos to [87% quality](https://github.com/telegramdesktop/tdesktop/blob/3013301a91ab0cecb200419b1ae22c4bbff819af/Telegram/SourceFiles/storage/localimageloader.cpp#L902). Do you think that's not enough? Still, most of the compression is performed by the server.

**Comment by leiniercs** [comment]
Telegram for mobile send better photos. You can see that when you send a photo on mobile and visualize it on desktop, and do the opposite: send from desktop and visualize on mobile, here you can see the lack of quality.

**Comment by Twilightssuperb** [comment]
Still actual for desktop. Please reopen this issue.

**Comment by Mithgol** [comment]
> the server itself compresses the photos

> most of the compression is performed by the server

Vote for the suggestion https://bugs.telegram.org/c/1058 if you want this behaviour stopped on the server.

**Comment by OBATipsy** [comment]
Telegram for mobile send better photos. You can see that when you send a photo on mobile and visualize it on desktop, and do the opposite: send from desktop and visualize on mobile, here you can see the lack of quality.
…

**Comment by Twilightssuperb** [comment]
Why issue was closed? I see nothing about it solution in changelog or recent commits...
