### ISSUE TITLE
Why does telegram try to execute  /usr/bin/bash?

### ISSUE THREAD

**Issue by DevAlone** [telegramdesktop/tdesktop#5318]
### Steps to reproduce
1. Run telegram under AppArmor
2. See audit log saying that telegram tries to execute bash every time it starts
```
type=AVC msg=audit(1540761706.295:237663): apparmor="DENIED" operation="exec" profile="/usr/bin/telegram-desktop" name="/usr/bin/bash" pid=2591 comm="telegram-deskto" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
```

### Actual behaviour
Don't know what to expect, just curious why. I haven't found anything about executing `/usr/bin/bash` in sources

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 1.4.3, the last one from Arch repos

**Comment by DevAlone** [comment]
Hm, version from the official site doesn't do this, both are 1.4.3

**Comment by stek29** [comment]
Arch repo builds are unofficial.

**Comment by patrakov** [comment]
The issue has been traced to the fact that the official telegram build bundles portaudio and the Arch build uses system portaudio. And the system portaudio (unlike the bundled portaudio) is built with JACK support, and thus tries to autostart JACK via bash.
