### ISSUE TITLE
Telegram will not start (Ubuntu 18.10)

### ISSUE THREAD

**Issue by philpem** [telegramdesktop/tdesktop#5319]
### Steps to reproduce
1. Download Telegram 1.4.3 x86_64 from the Telegram website
2. Untar, run Telegram

### Expected behaviour
Telegram should start up

### Actual behaviour
Telegram doesn't start.

When starting Telegram in a terminal, there are the Fontconfig errors from #5316, along with:

```
Fontconfig error: Cannot load default config file

(Telegram:12148): libappindicator-CRITICAL **: 21:46:22.267: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
ICE default IO error handler doing an exit(), pid = 12148, errno = 32
QMutex: destroying locked mutex
```

Telegram then exits, returning to the terminal.

### Configuration
**Operating system:** Ubuntu 18.10, x86_64

**Version of Telegram Desktop:** Latest from website, believed to be 1.4.3 based on filename

**Used theme**: Nil, Telegram won't start

**Comment by albertofwb** [comment]
I get this issue either on ubuntu 18.10, x86_64 
the telegram is downloaded from  https://updates.tdesktop.com/tlinux/tsetup.1.4.3.tar.xz

**Comment by RobertB93** [comment]
Hey,
got the same issue with Telegram downloaded from https://updates.tdesktop.com/tlinux/tsetup.1.4.3.tar.xz on Ubuntu 18.10 64 bit. It worked fine before upgrading from 18.04 to 18.10.

**Comment by albertofwb** [comment]
I finally found a solution is remove the telegram from download and use 
```
sudo apt install telegram-desktop ```

**Comment by 0xEAB** [comment]
#4240

**Comment by 0xEAB** [comment]
> Same here. Is it related with https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1790966/comments/14 ?

No, *Telegram Desktop* isn't an Electron app.
This bug here is a *fontconfig* thing.
