### ISSUE TITLE
Segfault when switching multi-monitor / single monitor on Ubuntu

### ISSUE THREAD

**Issue by Hacker-CB** [telegramdesktop/tdesktop#532]
I'm running KUbuntu 14.04 (KDE).
I'm using Lenovo X240 notebook with docking station.

When notebook is connected to docking station I'm using 2 external monitors.

Telegram stops with segfault message after undocking and switching 2 external monitors -> 1 internal LCD.

**Comment by kalmar** [comment]
I have the same problem on Xubuntu 14.04 when switching between two monitors. I'm using Lenovo B590 with external monitor.

**Comment by thomich** [comment]
i also have same problem:
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 14.10
Release:        14.10
Codename:       utopic

Linux hercules 3.16.0-38-generic #52-Ubuntu SMP Thu May 7 10:51:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GT 650M] (rev ff)

running Telegram from konsole gives this output if i unplug second monitor:

~/Apps/Telegram/Telegram 
libs init..
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number                                                                                                                     
Segmentation fault (core dumped)

**Comment by auchri** [comment]
Duplicate #796
