### ISSUE TITLE
Timestamp no accuracy

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5320]
![image](https://user-images.githubusercontent.com/7231077/47624722-6c3d8e80-db45-11e8-89fc-6cd53cc086e1.png)

### Steps to reproduce
1. Send a message in a bot [skeddy](t.me/SkeddyBot) for quick response

### Expected behaviour
The second message has two seconds before than the first message

### Actual behaviour
It should be 1 second greater or none

### Configuration
**Operating system:**Win 10

**Version of Telegram Desktop:**1.4.3

**Used theme**: Mid night

**Comment by Lonami** [comment]
Your system time is probably wrong.

**Comment by SmartManoj** [comment]
> Your system time is probably wrong.

Nope

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Comment by SmartManoj** [comment]
> this issue is still valid on 1.9.8?

Nope

**Comment by SmartManoj** [comment]
Happens sometimes now again, when we open app

**Comment by ilya-fedin** [comment]
> We can remove the label now?

we can't reopen anyway, it's a duplicate of #2797
