### ISSUE TITLE
Infinite loop from time to time

### ISSUE THREAD

**Issue by FraYoshi** [telegramdesktop/tdesktop#5321]
### Steps to reproduce
it is actually difficult to reproduce, it's easier to get it when the last tab opened has been the gifs one.
Just at some point, even if leaving it miniaturized, it starts using a 100% thread. To stop it, either close and reopen or move the cursor between gifs, stickers and emoji or it will least forever (leaved like 1 hour doing it and never stopped).
It happened months ago and still, continues to randomly happen.

### Configuration
OS: Arch Linux 
Kernel: x86_64 Linux 4.18.16-arch1-1-ARCH
CPU: AMD Ryzen 7 2700X Eight-Core @ 16x 4GHz
GPU: GeForce GTX 1050 Ti
RAM: 5447MiB / 64418MiB
cache and root on SSD.

**Version of Telegram Desktop:**
community/telegram-desktop 1.4.3-1

**Used theme**:
Night mode - a theme which name don't remember

**Comment by FraYoshi** [comment]
update 2019-06-11:
same config but telegram-desktop 1.7.3-1

At some point it started using lot of CPU power doing nothing. I let if do it's nothing for a while ma nothing changed. I tried switching from the emoji tab in which it was to gifs one so stickers and emoji as I started.

Problem solved. So it definitely is something related to that function.

**Comment by Aokromes** [comment]
this bug is still valid? if yes, i suggest you to run telegram under valgrind to see if you can find the reason of loop.

**Comment by FraYoshi** [comment]
Yes, the fact is that the bug manifests sporadically.. actually, the last time I experienced it was months ago.. ^^"

This time I made a video of the thing, unlucky I did not foreseen the recorder to monopolize the show.. It's highlighted but telegram is the one below.

Notice that the loop ends when I enter the "gifs" tab this time and when I come back to the "emoji" one it doesn't start again.

[link to video on youtube](https://www.youtube.com/watch?v=ulFao4L6klQ)

or directly file:
[telegram-desktop-loop-bug.mkv.zip](https://github.com/telegramdesktop/tdesktop/files/4141532/telegram-desktop-loop-bug.mkv.zip)

**Comment by Aokromes** [comment]
can you try on 1.9.21?

**Comment by Aokromes** [comment]
@FraYoshi

**Comment by FraYoshi** [comment]
Hi,
sorry for the long delay..
The bug doesn't present itself in a predictable way, so I can't really reproduce it in order to catch it on Valgrind, I should keep it running under it until it happens and it could mean months...

Since the last report I no longer experienced it and I've regularly updated Telegram.

**Comment by ilya-fedin** [comment]
> I should keep it running under it until it happens and it could mean months...

4 months have passed

**Comment by FraYoshi** [comment]
Sorry, closed before commenting.
By the way, never happened again.
I think 4 months is a long enough period of time :)
