### ISSUE TITLE
Impossible to open context menu in input field via touchscreen

### ISSUE THREAD

**Issue by RussianNeuroMancer** [telegramdesktop/tdesktop#5322]
### Steps to reproduce
1. Verify that touchscreen operate correctly: tap and hold on the message, context menu should appear
2. Now tap and hold in input field

### Expected behaviour
Context menu also appear

### Actual behaviour
Context menu doesn't appear

### Configuration
**Operating system:**
Ubuntu 18.10

**Version of Telegram Desktop:**
1.4

**Used theme**:
Dark theme

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1995
