### ISSUE TITLE
Czech language

### ISSUE THREAD

**Issue by JimmyS83** [telegramdesktop/tdesktop#5327]
Hello,

I am sorry for bothering you, as this is not an "issue", but I know this is one of few option to contact you :)

I am maintaner of unofficial Czech language (quite long time - http://telegram.zde.cz for users, also maintainer of Czech here https://www.transifex.com/telegram-cis/).

I was very happy, when I found out, that Czech is finally avaible at https://translations.telegram.org. Because lack of import custom files to the translation platform, I filled / review/ polished Czech translation for Telegram Desktop and Android through web interface (User: Jirka) during last week. I dont know the approval / review process, but I found mistakes in some of Transifex "applied" Czech strings.

I am not sure, if developers could anyhow process languages for their platform, but just letting you know, that Czech Translation is quite ready there. It would be great to have approved already inserted strings, because a lot of them are shared for example, Android and iOS, but when I looked into iOS translation, I dont see pre-filled strings from Android etc. Or at least know the review process would be good (I can also go through all strings again, and check, if theres no typo, or no-fitting text etc.)

I will continue with iOS, macOS into Czech language, to have same consistent terms on all platforms.

Have a nice day!

**Comment by JimmyS83** [comment]
Daria contacted me on the Telegram, now I can work @ translations.telegram.org directly. I am starting with Telegram Desktop :)

Many thanks,
thanks for all your work!

**Comment by john-preston** [comment]
@JimmyS83 👍

**Comment by stek29** [comment]
@JimmyS83 thanks for translations, and sorry for this taking so long.
