### ISSUE TITLE
[Feature Request] Add page numbers for long post

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5328]
If text is split into 3 messages, adding 1/3 ,2/3 and 3/3 at every message would be better

**Comment by ThigSchuch** [comment]
Why counter if the messages will be sent in sequence?

**Comment by SmartManoj** [comment]
If someone forward a single message from it , we will be know the remaining messages

**Comment by stek29** [comment]
@SmartManoj well, you can add those numbers manually, if it's important in your case.
