### ISSUE TITLE
Ctrl Alt Keys produces upper case

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5329]
Ctrl Alt Keys produces upper case.
Is it bug or not?

**Comment by stek29** [comment]
template. use it.

**Comment by SmartManoj** [comment]
@stek29 
 
### Steps to reproduce
1. Press ctrl alt a
2. 
3. 

### Expected behaviour
-

### Actual behaviour
Produce capital a

### Configuration
**Operating system:**Win10

**Version of Telegram Desktop:**1.4.3

**Used theme**:Midnight

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by 23rd** [comment]
This strange behavior takes place for long time.
If I press and hold `Right Alt` on any language layout, I start write with english capital letters.
But as I could understand, this is not problem of Telegram, this is feature of Qt5. I have same behavior in other applications based on Qt5.
