### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by Innomen** [telegramdesktop/tdesktop#533]
It's cumbersome to have a conversation with two or more people at once since I can't have multiple windows.

I assume this isn't possible, I've tried and tried, and I can't find any other matching requests either. 

Sorry if I missed something.

**Comment by ChaosMarc** [comment]
if you use the portable version from https://desktop.telegram.org/ you can easily launch multiple instances.

**Comment by Innomen** [comment]
Ahh! Good to know. I'll try that right away :)

**Comment by phplego** [comment]
:+1: 
>> you can easily launch multiple instances.
It does not work on Ubuntu. Trying to run a second instance just brings the first into focus.

**Comment by Innomen** [comment]
Every chat window should have a "pop out" button. I'm confident that it will as the desktop app begins to compete with pidgin and the like more :)

**Comment by cobalto** [comment]
Multiple accounts would be nice too, but sure multiple instances looks easier to implement and do the same enough

**Comment by yazeed44** [comment]
+1

**Comment by gjngeldenhuis** [comment]
+1 for multiple accounts

**Comment by mbnoimi** [comment]
+1

**Comment by zippl** [comment]
+1

**Comment by robertgc** [comment]
+1

**Comment by mautematico** [comment]
Are there any news about this multiple instances thing? :)

**Comment by Innomen** [comment]
I guess it's low priority. /shrugs

**Comment by DiThi** [comment]
This has an easy workaround (using several copies of the portable version). There's no workaround for using several instances in mobile, though (other than using several android accounts, but you don't get notifications of the other accounts that way).

**Comment by mautematico** [comment]
When using, let say, Mozilla Firefox, you can pass `-P` and `--no-remote` parameters to get multiple instances running at the same time:

`firefox -P 'profile one'`
`firefox -P 'profile two' --no-remote`

May be tdesktop can use some parameter like those, and give the user choice to select profile/data dir

> (using several copies of the portable version)
I think portable version is not available for GNU/Linux, is it?

Thank you all for the great work!

**Comment by doublejumper** [comment]
+1

**Comment by RobDesideri** [comment]
+1

**Comment by kittee** [comment]
+1 also

**Comment by humiaozuzu** [comment]
Any update?

**Comment by auchri** [comment]
You can start multiple instances with the following command:

1. `Telegram.exe -many -workdir C:\Users\asd\Desktop\instance1\data`
2. `Telegram.exe -many -workdir C:\Users\asd\Desktop\instance2\data`

I think it should be the same for linux.

**Comment by gjngeldenhuis** [comment]
Starting multiple instances is not a solution and closing the ticket is certainly not the way to make this go away.

**Comment by auchri** [comment]
This issue was about multiple instances and it's fixed.

**Comment by mbnoimi** [comment]
@auchri 

>    Telegram -many -workdir "C:\Users\asd\Desktop\instance1\data"

> I think it should be the same for linux..

It doesn't work under Linux as I expected. I created this launcher but unfortunately it fails:

```
[Desktop Entry]
Version=1.0
Type=Application
Name=Telegram Desktop SIM2
Icon=telegram
Exec=/home/halo/.Telegram/Telegram  --many --workdir=/home/halo/.TelegramDesktopSIM2
NoDisplay=false
Categories=Network;
StartupNotify=false
Terminal=false
```

**Comment by EhsaanF** [comment]
Worked perfectly in Ubuntu 15.04 (elementary 0.3.2 distro):
```
Telegram -many -workdir /home/ehsaan/.dubaisimcard/
```

**Comment by MJafarMashhadi** [comment]
@mbnoimi `workdir` directory should be created before launching telegram

**Comment by Innomen** [comment]
It seems my patience will only be punished when petulant devs are at play.

Seriously, why even bother having an issues page if you're going to find excuses to ignore them all?

It seems this app will NEVER have spell checking, multiple windows, log export, or user specific backgrounds. Because reasons? Party like it's 1999. 

Oh wait, even in '99 chat apps had multiple windows, logs, and spell checking.

Pathetic that in 2016 I find myself looking back at the likes of ICQ and Aim and seeing them as objectively more advanced.

We truly are a decadent culture. I wonder how long till we start tearing down our monuments because we've forgotten how to quarry fresh stone.

In any case I'll just encourage my few contacts to migrate to a better app with a maintainer or two that gives a damn for something other than snarking and receiving compliments. 

I pity everyone else afflicted by vendor lock in. Now I know why I'm not permitted to export my chat log. To sustain the aforementioned vendor lock in. 

Enjoy the snide last word devs or devknights. This thread is now being ignored by me as well.

 (Right wing profit motive excuses in 3... 2... 1...)

**Comment by john-preston** [comment]
@Innomen Wow, that was touching.. :'(

**Comment by cobalto** [comment]
@Innomen 
![how_rude](https://cloud.githubusercontent.com/assets/1196314/19176003/2b1f7d02-8c12-11e6-866a-8e14c03177c0.png)

**Comment by stek29** [comment]
@Innomen What's the license of your comment? Can I use it?

**Comment by kittee** [comment]
@stek29 there's no point in asking in this thread since it is now being ignored by him

**Comment by EhsaanF** [comment]
@Innomen It looks like Telegram is ignoring everyone, adding the most *USELESS* features to their clients by leaving bugs unsquished.
I don't what that is called, but they made something fast, but imperfect. Hope someday Durov wakes up and see there's plenty to do yet.

**Comment by stek29** [comment]
@kittee 

![image](https://cloud.githubusercontent.com/assets/11808223/19216607/c154aea4-8dcb-11e6-9220-f174ce256aa6.png)

**Comment by Megachip** [comment]
So really? If I have a windows system with multiple users, all use the same telegram instance... how secure :(

You really shout separate data from executables (in installer version). Think of terminal server etc. with a lot of users...

**Comment by john-preston** [comment]
@Megachip You can have everyone use his own instance. Or you can put your only instance in some write protected place — if Telegram can't write to it's executable path, it uses the current user's "AppData/Roaming/Telegram Desktop" folder.

**Comment by stek29** [comment]
@john-preston Doesn't TDesktop always use AppData unless it's Portable/Alpha build?

**Comment by cryptoneep** [comment]
doesn't work on OSX. driving me nuts..

**Comment by stek29** [comment]
@cryptoneep yup, it doesn't work on macOS sadly :(
Maybe you'll open an issue?

**Comment by anjunatl** [comment]
I've been itching for this feature, and I'm on OS X. I'll look through the code and see if I can do it, and if I can I'll make a pull request.

**Comment by noark9** [comment]
`Telegram -many -workdir pathtoworkdir`

works perfect on fedora 27

**Comment by MrSwed** [comment]
works on win7. but needs to create before workdir

so this could be realized by means of the telegram itself, inho

**Comment by cryptoneep** [comment]
Great, would love this on OSX as well!

**Comment by cobalto** [comment]
Well, It's a canon functionality on the mobile app now...

**Comment by linuxtopia** [comment]
how to apply for Telgram portable version of Linux that workdir? Command line doesnt know Telgram even cause of portable

**Comment by Rocco83** [comment]
+1 on that feature.
A plus would be the possibility to cleanup all of the content upon exit, keeping only the auth stuff.

**Comment by d0tfile** [comment]
@Rocco83 you can use `Telegram -many -workdir pathtoworkdir`, where `pathtoworkdir` it mounted as tmpfs for example. Directory `pathtoworkdir` will be destroyed after reboot.

**Comment by Rocco83** [comment]
@d0tfile thanks for the workaround.
I am anyway looking forward to do it without nasty double application.
As already mentioned, the multiple account are already a feature.
This must be "in" the application.
Also, if pathtoworkdir is missing, then also the authentication will be gone, and has to be re-issued. Which make sense, but again then a "flag" in the application is something that i would expect.

**Comment by Draghmar** [comment]
Could someone explain me how to use this command with portable Telegram on Windows?
`Telegram -many -workdir pathtoworkdir`
I created two folders in Telegram folder and created two shortcust to the .exe file where I putted command for each temp folder. But when I try to launch second instance I'm getting some error:
```
[2018.04.21 15:37:39] Launched version: 1002017, alpha: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
[2018.04.21 15:37:39] Executable dir: D:/Użytki/Telegram/, name: Telegram.exe
[2018.04.21 15:37:39] Initial working dir: D:/Użytki/Telegram/
[2018.04.21 15:37:39] Working dir: D:/Użytki/Telegram/
[2018.04.21 15:37:39] Command line: D:\Użytki\Telegram\Telegram.exe -many -workdir D\Użytki\Telegram\temp2
[2018.04.21 15:37:39] Executable path before check: D:/Użytki/Telegram/Telegram.exe
[2018.04.21 15:37:39] Logs started
[2018.04.21 15:37:39] Many instance allowed, starting...
[2018.04.21 15:37:39] FATAL: Could not open 'D:/Użytki/Telegram/tdata/working' for writing!
```
What I'd like to achieve is to use Telegram with one account on two Windows profiles (I had two: personal and for work), which I often switch (not log out) between and Telegram can work only on one of them. I thought that is something normal for this app when you have web and mobile version working at the same time without any issues.

**Comment by stek29** [comment]
@Draghmar There can't be two apps instances at the same time with one tdata folder. 
Even if you somehow trick TDesktop to launch it would lose messages and show other weird things caused by how one auth key pair for multiple instances works (or rather doesn't work).

You can, however, just log in with two separate instances, or close TDesktop in one profile before opening it in other one.

**Comment by Draghmar** [comment]
Ok, so what's this command actually do? Because I thought it was for that purpose.
Closing is out of the question - too much hassle. And what do you mean by separate instances? Making two copies (folders) of the TDesktop and running each of them on one of the profiles?

**Comment by auchri** [comment]
@Draghmar I think you forgot the :
The path should be D:\foo instead of D\foo.

**Comment by Draghmar** [comment]
@auchri Oh man...How stupid of me. I didn't noticed that missing colon. Thanks!

**Comment by sadalhayat** [comment]
@cryptoneep 

on mac, just use `-workdir`
don't add `-many` argument.

I'll try to create the script for launcher and share it here.

**Comment by sadalhayat** [comment]
![header](http://telegra.ph/file/45ae73cb06e8ec40794ad.png)

## How to run Telegram Desktop as portable app and multiple instances on macOS
http://telegra.ph/tdmac-08-07

**On Linux,** 
you can use `-many -workdir` command line parameter or create the launcher.
https://github.com/telegramdesktop/tdesktop/issues/533#issuecomment-222131863

**On macOS,**
just use `-workdir` parameter, **it won’t work if you add `-many`.** 
`<path to Telegram binary> -workdir <path to folder>`

![command in mac](http://telegra.ph/file/52326362fe78dc86d8a73.png)

---

### How to create TDesktop launcher app with Apple Script Editor:

**1. Open Script Editor on /Applications/Utilities.**

**2. Copy following script:**

```
set rootFolder to POSIX path of ((path to me as text) & "::")
set dataFolder to (rootFolder & "cache")
set appPath to (rootFolder & "Telegram.app")
do shell script "mkdir -p \"" & dataFolder & "\""
do shell script "open -a \"" & appPath & "\" --args -workdir \"" & dataFolder & "\""
```

![script](http://telegra.ph/file/c8fe4c5efb74daa2e5bb5.png)

**3. Save as Application, let’s called “launcher”. Close Script Editor.**

![save as app](http://telegra.ph/file/49fe3b1c94bbf1e385b86.png)

**4. Put the launcher in the same folder with Telegram.app of TDesktop stable/alpha.** 
Download from [desktop.telegram.org](https://desktop.telegram.org/) or [GitHub](https://github.com/telegramdesktop/tdesktop/releases), don’t use TDesktop from Mac AppStore.

**5. Done. Run the launcher.**

You can clone and create alias/shortcut for your launcher, also you can use it as portable app for removable USB disk.

App data are stored in “cache” workdir, same folder with the laucher & app. If you want to use different name, edit the launcher with Script Editor.

![launcher](http://telegra.ph/file/1e411b927501842f8779d.png)

---
cc @john-preston @stek29 @cryptoneep

**Comment by yegor256** [comment]
@auchri doesn't work on macOS for me, unfortunately. I submitted an issue about it, would be great if you can take a look: https://github.com/telegramdesktop/tdesktop/issues/6198

**Comment by lgg** [comment]
@mbnoimi @auchri I used method with `-many` and `-workdir`, but now I can't split them to separate instances of app. (like this 2 instances are different apps). On windows everything works fine btw
![image](https://user-images.githubusercontent.com/12018713/67540047-b02d8a00-f6ec-11e9-983c-293e27b2dea9.png)

**Comment by mbnoimi** [comment]
@lgg The following launcher works fine under Linux Mint 19.2 XFCE

**Telegram-SIM2.desktop**

```
[Desktop Entry]
Version=1.0
Type=Application
Name=Telegram SIM2
Icon=telegram
Exec=/home/halo/.Telegram/Telegram -startintray -many -workdir /home/halo/.TelegramDesktopSIM2
Path=/home/halo/.TelegramDesktopSIM2
NoDisplay=false
Categories=Network;
StartupNotify=false
Terminal=false
```

**Comment by lgg** [comment]
@mbnoimi tray icons are different, but app windows are in one icon on gnome dock
![image](https://user-images.githubusercontent.com/12018713/67575290-e8f94d80-f744-11e9-9d55-c026a2e941ed.png)

**Comment by mbnoimi** [comment]
> @mbnoimi tray icons are different, but app windows are in one icon on gnome dock

Unfortunately I never used Ubuntu desktop.

**Comment by adnanhaddad** [comment]
When running `Telegram -many -workdir "C:\Users\asd\Desktop\instance1\data"`
I'm getting this window with an error: 
![image](https://user-images.githubusercontent.com/33404398/106168811-fe062d00-618e-11eb-9c72-109b06e7b23c.png)

Does anybody have this or have a fix for it?

**Comment by RememberTheAir** [comment]
@adnanhaddad I don't think you need the `-many` flag anymore, I've been using just the `-workdir` option and it works perfectly

**Comment by adnanhaddad** [comment]
@RememberTheAir Thanks for replying. Without the -many flag the command would open the same instance it's already open. I would like to have multiple instances (one on each Desktop I have open). There were no logs to show. I took a screenshot and posted it as is.
