### ISSUE TITLE
Had the same issue on my Windows 10. Even if I use my earbuds, after the call is connected, the sounds somehow start to come from the speakers.

### ISSUE THREAD

**Issue by sl5net** [telegramdesktop/tdesktop#5330]
not solved: Windows 10. Even if I use my earbuds, after the call is connected, the sounds somehow start to come from the speakers.

_Originally posted by @black-wolfie in https://github.com/telegramdesktop/tdesktop/issues/418#issuecomment-423716640_

**Comment by ilya-fedin** [comment]
Is this still valid?

**Comment by Aokromes** [comment]
more than 1 month without answer, if this bug is still valid open a new ticket.
