### ISSUE TITLE
Odd behavior regarding syncing across devices after clearing chat history

### ISSUE THREAD

**Issue by DOBRO** [telegramdesktop/tdesktop#5331]
Hi!
I can't figure out which project this bug belongs to (Telegram Desktop or Telegram iOS).
When I click "Clear history" in any chat, the last message still remains on iPhone.

### Steps to reproduce
In Telegram Desktop:
1. Send message to any contact, say "message 1".
2. Send one more message to this contact, say "message 2".
3. Right button click on the contact and choose "Clear history".

In Telegram Desktop the chat is successfully cleared but the last message on iPhone remains, that is "message 2" is not deleted.

### Configuration
Telegram Desktop 1.4.3: Windows 10, MacOS Mojave.

Telegram iOS 5.0.15

**Comment by SmartManoj** [comment]
Do the reverse too

**Comment by DOBRO** [comment]
> Do the reverse too

If I clear chat history on iPhone, all the chat history on Telegram Desktop is cleared immediately.

**Comment by SmartManoj** [comment]
Try in Telegram Web too

**Comment by DOBRO** [comment]
> Try in Telegram Web too

Unfortunately, I can't check this because web.telegram.org and all domains *.telegram.org are blocked in Russia.

**Comment by SmartManoj** [comment]
https://www.puffinbrowser.com

**Comment by DOBRO** [comment]
I tried it in web version in Puffin Browser (thanks for the link!). After clearing chat history in web version, all the messages are deleted in iphone app too, hmmm...

BTW, there is no possibility to clear the entire chat history with one click in web version. To do this, I should select all messages before. Or I missed something?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1276
