### ISSUE TITLE
[Feature Request] Show messages except from -  in Group

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5333]
Like Show messages from feature , Show messages except from feature.
Or Is it a way to particularly change notification sound for a user in group?
It will be also nice to Show messages from multiple users.

**Comment by john-preston** [comment]
@SmartManoj No way to do that right now :( There is API to search for all messages from a specific user. But there is no API to search for all messages except from a specific user.

**Comment by SmartManoj** [comment]
Is it possible to mute some user in group?

**Comment by Aokromes** [comment]
no.
