### ISSUE TITLE
The message sent immediately after the computer resumes from sleep mode disappears

### ISSUE THREAD

**Issue by PalmtopTiger** [telegramdesktop/tdesktop#5336]
### Steps to reproduce
1. Put the computer into sleep mode.
2. Someone sends you new messages (you can find this out using a mobile client).
3. Wake up the computer and open the chat with this contact (after that the HDD will start up) and send a new message.
4. New messages from this contact will appear, and your message disappears until you restart Telegram Desktop.

### Expected behaviour
The message is placed after the contact messages.

### Actual behaviour
The message disappears.

### Configuration
**Operating system:** Windows 7 SP1 x64

**Version of Telegram Desktop:** 1.4.3

**Used theme**: Monokai (custom)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4556 / https://github.com/telegramdesktop/tdesktop/issues/2258 ?

**Comment by Aokromes** [comment]
no answer after more than a year, closing. if this bug is still valid plz open a new ticket using updated telegram desktop version.
