### ISSUE TITLE
Telegram window appears but is completely transparent except for outline

### ISSUE THREAD

**Issue by untilted-document** [telegramdesktop/tdesktop#5337]
### Steps to reproduce
1. Start telegram - it was already running, popped to front

### Expected behaviour
See main window

### Actual behaviour
A transparent outline appears. It seems functional, i can click close (or where close should be) to close the window etc. Alt-Tab peek shows blank, so does task bar thumbnail - see image

### Workaround
Force quit app and restart - window reappeared properly

### Configuration
**Operating system:**
Microsoft Windows [Version 10.0.17134.345]

**Version of Telegram Desktop:**
1.4.3.0 - 48,948,024 bytes

**Used theme**:
Don't know/default

<details><summary><b>Logs</b>:</summary>
[arc_log.zip](https://github.com/telegramdesktop/tdesktop/files/2538145/arc_log.zip)

</details>

![tgtrans](https://user-images.githubusercontent.com/18049243/47847258-8d5ee300-ddc2-11e8-87a1-567db1ad60b8.png)

**Comment by SmartManoj** [comment]
Windows version

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
