### ISSUE TITLE
problems with resizing on Mac OS X

### ISSUE THREAD

**Issue by dreamflyer** [telegramdesktop/tdesktop#5339]
### Steps to reproduce
1. Run telegram desktop
2. shift + dbclick on top of window

### Expected behaviour
window is expanded to display size

### Actual behaviour
it expanding to display size then it shrink again to initial size, very very annoying.

### Configuration
**Operating system:** Mac OS X 10.10.5

**Version of Telegram Desktop:**  1.2.14, but actually all versions

**Used theme**: default

**Comment by stek29** [comment]
I am unable to reproduce it with 1.4.4 on macOS 10.13.6.

**Comment by Aokromes** [comment]
no answer after more than 1 year, no one else reports this bug, closing.
