### ISSUE TITLE
Exit the program canceled by Telegram

### ISSUE THREAD

**Issue by evgenymarkov** [telegramdesktop/tdesktop#534]
Sometimes, if i want to close OS session i saw this message: http://pikucha.ru/iefCR .
And telegram in tray becomes gray: http://pikucha.ru/iefCS .
Fedora 21, Last KDE 4.*

**Comment by Turbito** [comment]
It happens to me too, in my both computers.
In one i have debian testing, with kde, and in the laptop in have xubuntu 14.10
please fix it

**Comment by auchri** [comment]
Duplicate

**Comment by wirwolf** [comment]
Bug exsist. Please fix.
