### ISSUE TITLE
Media preview broken if display scaling isn't 100% [Windows 10 - Update 1809]

### ISSUE THREAD

**Issue by RaynLegends** [telegramdesktop/tdesktop#5340]
### Steps to reproduce
1. Set Windows' scale for the display to a value different than 100% (for example, 125%, common for full hd displays at 15 or 17 inches)
2. Open telegram
3. Click a video or image

### Expected behaviour
The media viewer should display the video/image.

### Actual behaviour
The media viewer flashes rapidly or isn't shown at all except for random elements like the navigation arrows or the progress bar for videos.

### Configuration
**Operating system:** Windows 10 [1809]
Does not happen with earlier versions of Windows 10.

**Version of Telegram Desktop:** 1.4.3 - 1.4.4

Changing the scale from the settings in Telegram itself has no impact on the issue, neither does changing the theme or closing/reopening telegram and restarting windows.
Enabling compatibility mode (so that scaling is done by windows instead of the application) does not fix the issue.

This release of Windows 10 was quickly removed from Windows Update due to file deletion issues but an updated version is expected to come out this month, it would be cool to have this fixed before it gets published (again).

**Comment by Aokromes** [comment]
i suggest you to update to 1.4.4 beta.

**Comment by RaynLegends** [comment]
Just tried the beta and the problem unfortunately persists.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by RaynLegends** [comment]
Nope, it got fixed, thank you!
