### ISSUE TITLE
Build "~/TBuild/tdesktop/out/Debug" failure

### ISSUE THREAD

**Issue by artfoxhouse** [telegramdesktop/tdesktop#5341]
### Steps to reproduce
1. Follow the build tutorial up to the end when we run make "~/TBuild/tdesktop/out/Debug"
2. recipe for target 'CMakeFiles/lib_storage.dir/all' failed

### Expected behaviour
Compile without errors

### Actual behaviour
Compilation fails

### Configuration
**Operating system:** Ubuntu 18.04

**Version of Telegram Desktop:** 1.4.4 beta

**Used theme**:

<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/2540334/log.txt)

</details>

**Comment by Aokromes** [comment]
#4926
