### ISSUE TITLE
Invisible icon in cinnamon

### ISSUE THREAD

**Issue by dlblv** [telegramdesktop/tdesktop#5342]
Issue like #2638
### Steps to reproduce
1. Download telegram tarball from official site or install telegram-desktop package.
2. Start telegram.
3. Turn on "Settings -> Advanced -> Show tray icon"

### Expected behaviour
Tray icon must be shown.

### Actual behaviour
Icon doesn't appear. Instead of it I recognize tray to expand in a few pixels. This blank space (fully transparent) reacts as a real icon (see screenshots).

### Configuration
**Operating system:**
ArchLinux: Linux 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
DE: Cinnamon 3.8.9
**Version of Telegram Desktop:**
1.4.3

**Used theme**:
any
 
![screenshot from 2018-11-02 01-39-07](https://user-images.githubusercontent.com/20345406/47884111-98f0ef00-de40-11e8-9606-33e52f81e7c6.png)
![screenshot from 2018-11-02 01-39-18](https://user-images.githubusercontent.com/20345406/47884112-99898580-de40-11e8-9850-1a824bfd07d1.png)
![image](https://user-images.githubusercontent.com/20345406/47884180-d6ee1300-de40-11e8-8ef1-0cc6b10fc028.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4253 ?
