### ISSUE TITLE
----------------

### ISSUE THREAD

**Issue by NEUMAORG** [telegramdesktop/tdesktop#5347]
---------------

**Comment by NEUMAORG** [comment]
@john-preston Just stopped opening the client on the PC, look at the log please

**Comment by john-preston** [comment]
@NEUMAORG Nothing there :( Try rebooting PC / try portable version from https://desktop.telegram.org ?

**Comment by NEUMAORG** [comment]
@john-preston Tried, did not work, apparently some problems with the sound

**Comment by john-preston** [comment]
@NEUMAORG I'm afraid it just the last line the log got to, but nothing to do with the problem.

**Comment by Aokromes** [comment]
try to start telegram with -debug to see if it helps.

**Comment by RememberTheAir** [comment]
@NEUMAORG you could directly close the issue lol
