### ISSUE TITLE
Online Status on Side Bar(Feature Request)

### ISSUE THREAD

**Issue by NirvanaDraavon** [telegramdesktop/tdesktop#5348]
Been looking everywhere to make this suggestion, but one thing that I found in agreement with several hundred other users is that Telegram needs an online status feature--not limited to the active conversation tab.

A majority of the time, the reason for myself and other users not reaching out more often or being proactive is due to not knowing if others are online. Without that visual incentive, most users feel uncertain and as though they are lurking in the dark. Therefore, would it be possible to have a basic status symbol next to a user's name in our list of chats?

[Blue or Green](https://gyazo.com/9753f8d0705c3de40952703b7c670a21) = Online/Available
[Yellow](https://gyazo.com/032a1449fb7ba5e648c943181fa142c7) = Away
[Red](https://gyazo.com/e7afa01e7e807d9cc07cd6b4beff5f3e) = Busy/Do Not Disturb
[Gray](https://gyazo.com/7bf556b19a88669f9ce114e27d977f15) = Offline

This sort of quality of life feature would really help to encourage users to reach out more often and feel confident and certain of other user's presence. It surprisingly works well on many other chat platforms and I have always been curious as to why Telegram hadn't implemented it as of yet. Well, technically Telegram does have symbols next to groups and channels to differentiate them from user chats, but perhaps we could add a set of symbols specifically for user statuses too?

If you do consider adding this feature, thank you, please also consider the option of organizing chats by statuses as well!

Blocking a user should hide your status from them, of course.

Thank you for your time. I apologize if this is considered a misuse of the issues section.

**Comment by Aokromes** [comment]
#2435

**Comment by NirvanaDraavon** [comment]
> 
> 
> #2435

Thank you for joining the issues by reference. I wasn't certain if someone else had already made the feature request or not. There are two other things I have thinking about, but that one in particular was the most sought for among fellow users.
