### ISSUE TITLE
starting telegram speeds up music (spotify)

### ISSUE THREAD

**Issue by KuSpa** [telegramdesktop/tdesktop#5349]
### Steps to reproduce
1.  Start spotify and play music
2.  Start Telegram
3.  Listen

### Expected behaviour
Normal music speed and pitch

### Actual behaviour
Faster music speed (approximated 1.2 times as fast)

### Configuration
**Operating system:**
4.15.0-38-generic Ubuntu 18.04 

**Version of Telegram Desktop:**
1.4.3-alpha-2-g0c2de43 (291)

**Version of Spotify:**
1.0.93.242.gc2341a27-15
<details><summary><b>Logs</b>:</summary>

    $dmesg | grep telegram

    [  225.609502] audit: type=1400 audit(1541263186.488:45): apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/etc/openal/alsoft.conf" pid=3121 comm="Telegram" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
    [  226.398574] audit: type=1107 audit(1541263187.280:46): pid=852 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/NetworkManager" interface="org.freedesktop.DBus.Properties" member="GetAll" mask="send" name="org.freedesktop.NetworkManager" pid=3121 label="snap.telegram-desktop.telegram-desktop" peer_pid=873 peer_label="unconfined"
    [  226.400996] audit: type=1107 audit(1541263187.280:47): pid=852 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/NetworkManager" interface="org.freedesktop.NetworkManager" member="GetDevices" mask="send" name="org.freedesktop.NetworkManager" pid=3121 label="snap.telegram-desktop.telegram-desktop" peer_pid=873 peer_label="unconfined"
    [  226.401367] audit: type=1107 audit(1541263187.280:48): pid=852 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/NetworkManager/Settings" interface="org.freedesktop.NetworkManager.Settings" member="ListConnections" mask="send" name="org.freedesktop.NetworkManager" pid=3121 label="snap.telegram-desktop.telegram-desktop" peer_pid=873 peer_label="unconfined"
    [  226.401941] audit: type=1107 audit(1541263187.284:49): pid=852 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/NetworkManager/Settings" interface="org.freedesktop.NetworkManager.Settings" member="ListConnections" mask="send" name="org.freedesktop.NetworkManager" pid=3121 label="snap.telegram-desktop.telegram-desktop" peer_pid=873 peer_label="unconfined"
    [  226.402257] audit: type=1107 audit(1541263187.284:50): pid=852 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/NetworkManager/Settings" interface="org.freedesktop.NetworkManager.Settings" member="ListConnections" mask="send" name="org.freedesktop.NetworkManager" pid=3121 label="snap.telegram-desktop.telegram-desktop" peer_pid=873 peer_label="unconfined"

</details>

**Comment by drunckoder** [comment]
I suspect the issue has something to do with snaps.
As a workaround try getting telegram binaries from https://telegram.org/dl/desktop/linux

**Comment by stek29** [comment]
#1548
