### ISSUE TITLE
Stores the Login when uninstalled on Windows

### ISSUE THREAD

**Issue by friedrichschoene** [telegramdesktop/tdesktop#535]
I uninstalled telegram on my windows machine. Then I reinstalled it one minute later. When I requested the verification code, the typical message popup at the corner of the screen showed up and presented the code, whithout having me logged in yet. This is just a small security issue but should be fixed.

**Comment by cobalto** [comment]
If you Logout your account before uninstall the app the problem persists?

**Comment by auchri** [comment]
I'm not able to reproduce this
