### ISSUE TITLE
Hyper Linking with `[]()` don't work

### ISSUE THREAD

**Issue by Aphotice** [telegramdesktop/tdesktop#5351]
### Steps to reproduce
1. Hyper Linking with 
2. putting things in `[]()` Square Brackets Square Brackets Brackets Brackets 
3. does not work

### Expected behaviour
if i put site name & the site link inside these `[]()` it should create a hyper clickable link for me

### Actual behaviour
i can create hyper link only by selecting a text & then add link to it pressing CTRL+K

### Configuration
Windows 10 Enterprise

**Version of Telegram Desktop:**
1.4.4 beta

**Used theme**:
Incognito by @IncognitoTheme
#dark #grey

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

i want to be able to type & copy paste a template of sites & easily paste them in my channel, dont wanna CTRL+K every link everytime.

**Comment by john-preston** [comment]
@Aphotice It is not supposed to work, sorry.

**Comment by Widowan** [comment]
By the way, it is works on Telegram X, why shouldn't it on tdesktop?
