### ISSUE TITLE
[Bug] Wrong message sending order

### ISSUE THREAD

**Issue by 0xCA** [telegramdesktop/tdesktop#5352]
### Steps to reproduce
1. Copy large text from the Internet, paste it to channel
2. The text is splitted to 4 messages
3. It looks perfectly right
4. Open channel from another device, 3rd and 4th are swapped

OR

1. Selected 23 pics, dragged and dropped them
2. Waited for upload, posted one link
3. Looks right
4. Opened from another device, link is penultimate, last pic is last
5. Swapped again

### Expected behaviour
All messages posted in the right order

### Actual behaviour
Last two messages are swapped

### Configuration
**Operating system:** Latest Windows 10

**Version of Telegram Desktop:** 1.4.3

**Used theme**: null

Also when forwarding multiple albums they always totally messed, but this is another issue I suppose.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5033
