### ISSUE TITLE
4.6.142825 Stable on MacOS displays notifications if there are unread messages in muted groups and channels

### ISSUE THREAD

**Issue by BurkovBA** [telegramdesktop/tdesktop#5354]
![screen shot 2018-11-05 at 14 01 23](https://user-images.githubusercontent.com/7602655/48002715-45162c80-e104-11e8-8746-f03a2bcd4cc3.png)

### Steps to reproduce
1. Mute some groups and channels
2. Let them write new unread messages
3. Looks at your Telegram icon in system tray - it displays +1 new message per each channel/group with unread messages. And seemingly adds 1 by default (so that if you have 2 muted groups, the counter is 3).

### Expected behaviour
Notifications should not be raised for muted channels.

### Actual behaviour
For each muted channel with unread messages I see a bubble with number on Telegram icon in tray.

### Configuration
**Operating system:**
MacOS Sierra 10.12.5

**Version of Telegram Desktop:**
4.6.142825 Stable

**Used theme**:
default

**Comment by stek29** [comment]
Check settings -> Notifications
<img width="701" alt="image" src="https://user-images.githubusercontent.com/11808223/48002789-9ed72080-e11d-11e8-95dd-38610a3839e8.png">

**Comment by BurkovBA** [comment]
@stek29 Thanks for quick response, Viktor. However, this doesn't help, sorry:

![screen shot 2018-11-05 at 14 12 09](https://user-images.githubusercontent.com/7602655/48002909-d4234480-e104-11e8-9979-8b76ca9fc92f.png)

**Comment by stek29** [comment]
This is not TDesktop but a different app -- from https://macos.telegram.org.
You can get TDesktop at https://desktop.telegram.org.
(There are two apps in Mac App Store as well).

You can report issues in the app you're using at https://t.me/macswift, or at https://github.com/overtake/TelegramSwift.

**Comment by BurkovBA** [comment]
Oh, oops, sorry, didn't notice that. So, it's a Swift one, not the C++/Qt one.

Thank you, guys, for doing awesome job on Telegram!
