### ISSUE TITLE
Segfaulted after keyboard hijacking 

### ISSUE THREAD

**Issue by emilio-aburto** [telegramdesktop/tdesktop#5355]
### Steps to reproduce
1. Have telegram desktop windows open in fullscreen
2. Let your dog walk in the keyboard (May have reproducibility problems, the bug I mean)
3. Crashed

I know this doesn't help very much LOL, but I have a stacktrace and that may be helpful.

### Expected behaviour
Weird keystrokes in the open chat, maybe.

### Actual behaviour
Segfaulted

### Configuration
**Operating system:** ArchLinux x64, KDE

**Version of Telegram Desktop:** 1.4.3

**Used theme**: default

**Stack trace**: [telegram-desktop-20181105-132844.kcrash.txt](https://github.com/telegramdesktop/tdesktop/files/2549670/telegram-desktop-20181105-132844.kcrash.txt)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
