### ISSUE TITLE
Crispy font on macOS Mojave

### ISSUE THREAD

**Issue by ingria** [telegramdesktop/tdesktop#5358]
Only happens on light themes:

![photo](https://user-images.githubusercontent.com/2178368/48076290-f34dcf00-e1f5-11e8-98f7-6c8dfd326555.png)

Dark are OK:

![photo_2018-11-06_19-00-11](https://user-images.githubusercontent.com/2178368/48076418-327c2000-e1f6-11e8-9c91-98e0a7b1b28c.jpg)

 

### Configuration
macOS Mojave 10.14.1

**Version of Telegram Desktop:**
1.4.3

**Used theme**:
Default dark and default green.

**Comment by john-preston** [comment]
Did you disabled font smoothing in System Preferences -> General?

**Comment by stek29** [comment]
@john-preston apple has removed subpixel font antialiasing in Mojave.
Google for "mojave font antialiasing" for hundreds of reports, posts, issues and discussions.
There's still a way to force it via defaults.

#5205
