### ISSUE TITLE
Telegram Desktop not switching audio device

### ISSUE THREAD

**Issue by io41** [telegramdesktop/tdesktop#5359]
### Steps to reproduce
1. Launch telegram desktop.
2. Plugin USB Headset. (Note that all other applications now play audio over the USB Headset - it has become the default device)
3. Play voice message.

NOTE: It does not matter what order 1 or 2 come in. Even when it has been restarted (not running in the system tray), with the USB headset already plugged in, or not yet plugged in, it makes no difference. Telegram Desktop never uses it.

### Expected behaviour
Telegram Desktop should play the voice message over the USB headset

### Actual behaviour
Telegram Desktop plays the voice message over the standard system speakers

### Configuration
Manjaro Linux (latest stable release), 64-bit. KDE
Core i7, 16GB Ram

**Version of Telegram Desktop:**
1.4.3 (latest release)

**Used theme**:
Default

Logs:

The only output telegram desktop gives when I play the voice message is:

```
[ogg @ 0x7fc03004b8c0] 727 bytes of comment header remain
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
```

It gives this output regardless of whether the headset is plugged in or not.

**Comment by io41** [comment]
I was too quick with my finger on the trigger there. Not related to Telegram-Desktop. Closing.

**Comment by io41** [comment]
For anyone else, seems to be a bug in choosing the "default" device. When I toggled the default device in the system settings, it worked like a charm.

**Comment by MBurtsev** [comment]
I have some problem
