### ISSUE TITLE
Linux client not reconnecting after resume from suspend

### ISSUE THREAD

**Issue by axfelix** [telegramdesktop/tdesktop#536]
Hi folks,

When minimized to tray, Telegram doesn't seem to reconnect properly (in Ubunty 14.04 under Unity, if it matters) after resume from suspend; when I bring the client back up, it has "connecting..." displayed at the bottom until I go back into the connection settings and hit save (without changing anything).

This might be because (like many Linux users) I had to add the kernel modules of my wireless card to a little SUSPEND_MODULES script so that they're properly brought down and back up immediately before and after the rest of the system suspends (not sure why linux wireless is so prone to not resuming properly otherwise, but this has been necessary on both my Ubuntu desktop using USB wireless and my Arch notebook using builtin, so I guess it's quite common), which means I don't usually have wireless until 5-15 seconds after resuming. Telegram could maybe be trying and giving up within that time?

**Comment by Foodfast** [comment]
The same problem on Linux Mint 17.1 xfce. After suspend icon (and, maybe, program) dissapear, and I must restart program.

**Comment by Foodfast** [comment]
And on Arch Linux this ussue also appear. kernel 3.14. cinnamon DE.

**Comment by rosshamish** [comment]
:+1: I also have this problem.

For the record, a workaround is: Settings -> Connection Type -> Save
( don't actually change the connection type, just open the dialog box and hit save )

**Comment by Foodfast** [comment]
massage from Ross Anderson:
"For the record, a workaround is: Settings -> Connection Type -> Save
( don't actually change the connection type, just open the dialog box and hit save )"

**Comment by rosshamish** [comment]
Haha @Foodfast - I wrote that message and deleted it after re-reading the OP, it's mentioned in there, although its buried in the paragraphs.

**Comment by Foodfast** [comment]
@rosshamish yeah, I try this method and it doesn`t solve the problem. But anyway, thanx for reply ;)

**Comment by helmerj** [comment]
Same problem on Kubuntu 14.10...

**Comment by LibertyPaul** [comment]
Confirm on Ubuntu 14.04

**Comment by AltarBeastiful** [comment]
Same on Opensuse 13.2 using KDE

**Comment by duarte-pompeu** [comment]
It's been happening to me as well, came here to report this.

OS: Ubuntu 14.04 64bit, Gnome desktop.
Telegram version: Telegram Desktop 0.8.7 (it has happened before I updated, though)

**Comment by pschichtel** [comment]
:+1: from my side, the suggested workaround works for me. 
Archlinux with kernel 4

**Comment by arusanov** [comment]
This happening to me as well
OS: Ubuntu 14.04 64bit, Unity desktop.
Telegram version: Telegram Desktop 0.8.11

**Comment by mirrr** [comment]
Archlinux 3.19 x86_64 GNU/Linux
Telegram client doesn't reconnect after most losing network (unstable wi-fi connection or after laptop suspend and sleep). Status is "connecting...". After [Settings -> Connection Type -> Save] connection up and status changed to "Online"

**Comment by sakulstra** [comment]
same problem here: mint 17.1 MATE

**Comment by earendil02** [comment]
I have a very similar problem with my DELL XPS13 (born with Ubuntu) running 15.04 (issue was there even before).
When my connection is reset (after a suspension or for other reasons) Telegram is no longer able to reconnect, the message "Connecting.." is displayed in the bottom left corner, and obviously it doesn't update anymore. It remains stuck in this condition until I quit (via the menu on the indicator panel) and restart it. Simply closing the window doesn't help.
I tried the "edit connection" workaround and seems to work, but the restart is faster ;)
An easily accessible option to manually force a reconnection maybe could help.

**Comment by axfelix** [comment]
This seems to have finally been fixed in the newest version...
