### ISSUE TITLE
Being inactive still marks messages as read if Telegram window has the focus

### ISSUE THREAD

**Issue by Programie** [telegramdesktop/tdesktop#5363]
### Steps to reproduce
1. Make Telegram Desktop the active window
2. Stay inactive for a while while getting messaged
3. Messages are marked as read even if not read

### Expected behaviour
Messages should not be marked as read while being inactive.

### Actual behaviour
Messages are being marked as read even if not touching the keyboard or mouse for a while.

### Configuration
**Operating system:**
Ubuntu 18.10 (with Gnome 3.30.1)

**Version of Telegram Desktop:**
1.4.4 Beta

**Used theme**:
[DarkGreen](https://t.me/desktopThemes/74)

**Comment by MetalDroid** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4664
