### ISSUE TITLE
Add 175% interface scale option

### ISSUE THREAD

**Issue by Nalorokk** [telegramdesktop/tdesktop#5365]
Please add 175% interface scale option, it is a default scale for many 4K displays, and it is one of default option in Windows 10.

**Comment by Trigun27** [comment]
Mmm may be even 225% and 250%. On some laptops with 4k displays even 200 scaling is really small.

**Comment by john-preston** [comment]
@Trigun27 250% is there, no?

**Comment by Aokromes** [comment]
you must be using some outdated version: 

https://i.imgur.com/323GDO0.png

**Comment by Nalorokk** [comment]
Or maybe please consider adding some "expert" options with manual scale input from 1 to 500 (like Windows does), if it is possible for Telegram.

It will probably fix this problem with scaling for different screens for much longer time.

**Comment by Aokromes** [comment]
> Or maybe please consider adding some "expert" options with manual scale input from 1 to 500 (like Windows does), if it is possible for Telegram.
> 
> It will probably fix this problem with scaling for different screens for much longer time.

i suggested preston to change this, the problem is he needs one library to read svg icons c++ compatible and convert every icon to svg

**Comment by john-preston** [comment]
@Aokromes I didn't find an easy way to render SVG graphics with filters (like, not trying to extract that code from WebKit or smth).

Filters are required to make arbitrary shadows, that currently are done as icons as well. If I draw an icon and complex shadows in Photoshop and export it as SVG it does it using filters.

**Comment by pneumotube** [comment]
+1 for the 175% scale. 150% on my setup is too small and 200% is too large.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1121
