### ISSUE TITLE
Disabling notifications in Android silently disables desktop notifications

### ISSUE THREAD

**Issue by TisFoolish** [telegramdesktop/tdesktop#5366]
### Steps to reproduce
1.  Have notifications enabled on Desktop
2. Have someone send you a message.
3.  Go into the notification settings in Android and disable them
4.  [Watch as your Desktop notifications disappear and then reappear when you re-enable them in Android](https://gfycat.com/InformalClassicIndigobunting)

### Expected behaviour
Having notifications turned on in Desktop should work regardless if they're turned off in Android

### Actual behaviour
The Android setting overrides the desktop setting.

### Configuration
**Operating system:**
Win 7

**Version of Telegram Desktop:**
1.4.3

**Comment by john-preston** [comment]
@TisFoolish In Telegram notification settings are cloud based and synced between the devices, sorry.

**Comment by TisFoolish** [comment]
Why?  That's unintuitive, not to mention that the desktop settings are not at all changed.

**Comment by FreedomPrevails** [comment]
@TisFoolish It is how it is supposed to work.
