### ISSUE TITLE
"Persian font" in v1.4.5  is unreadable/ugly

### ISSUE THREAD

**Issue by Aphotice** [telegramdesktop/tdesktop#5368]
### Steps to reproduce
1. Type Persian/Farsi
2. 
3. 

### Expected behaviour
let us choose our font or just use the old one, it was more readable(screenshots at the end of the post)

### Actual behaviour
its ugly xD

### Configuration
Windows 10 Enterprise

**Version of Telegram Desktop:**
 1.4.5 beta

**Used theme**:
Incognito by @IncognitoTheme
#dark #grey

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

old font:
![image](https://user-images.githubusercontent.com/30921064/48232799-19c36400-e3c8-11e8-8686-90a86d9c314e.png)

new font:
![image](https://user-images.githubusercontent.com/30921064/48232811-247df900-e3c8-11e8-83e7-9cdb22fae391.png)

**Comment by Aphotice** [comment]
some more info here:
https://t.me/TelegramDesktopTalk/5583
https://t.me/TelegramDesktopTalk/10749
:}

**Comment by john-preston** [comment]
@Aphotice 

I see that in the new version bold font is finally working:

![image](https://user-images.githubusercontent.com/17900494/48248435-bad60d00-e410-11e8-870c-dd3bfceff838.png)

While in the old font it is not:

![image](https://user-images.githubusercontent.com/17900494/48248443-c45f7500-e410-11e8-823f-50218648471c.png)

That's because I've asked it to fall back to Segoe UI (standard microsoft UI font).

**Comment by Aphotice** [comment]
hmmm yes it's something we Persian/Arab folk are not used to/don't use
is there a way to change it, it will be great to be able to choose our own font....

**Comment by FreedomPrevails** [comment]
@john-preston Please revert the font to old font or let us choose the font in the settings.
The new font in farsi is ugly and sometimes unreadable for some characters like پ.

**Comment by FreedomPrevails** [comment]
I paid more attention and noticed both پ و چ are shown incorrectly and are unreadable. probably because there are not used in Arabic. Farsi has 4 more characters than Arabic. گ پ چ ژ

**Comment by Aphotice** [comment]
while we are at it can we take a look at how clean & readable
Google Noto fonts look like:
https://www.google.com/get/noto/#naskh-arab

Persian/Farsi:
![image](https://user-images.githubusercontent.com/30921064/48283516-ff45c500-e471-11e8-8f0a-6688d7876bd6.png)

Arabic:
![image](https://user-images.githubusercontent.com/30921064/48283528-0967c380-e472-11e8-90d8-dd18c9555ca9.png)

**Comment by FreedomPrevails** [comment]
@Aphotice I agree with you that Google Noto font is clean and readable, but I think it is somehow too formal for a chat application, I still prefer the old font.
I think the best approach is to make the font configurable in the settings.

**Comment by ffallah** [comment]
I can confirm this issue as well. The new font looks so bad for Persian (Farsi).

**Comment by alisentinel** [comment]
Same issue, Really unreadable exactly when using ـِ ـَ ـُ تً , etc...

I suggest to use IranSans font for Persian/Arabic, it's free for non-commercial usage or let us choose it. Many other Persian apps use this font, it supports Bold/Italic/UnderLine Also it has different types like ultralight/light/medium/bold/black.

**Comment by FreedomPrevails** [comment]
@alisentinel IranSans is a very nice font, Can you provide a link on where to get it for free for non-commercial usage ?
Although the license cost is like $3, I have no issues donating such amount to get a commercial license for Telegram Desktop if @john-preston decided to include this font.

**Comment by Aphotice** [comment]
Well, finally I got a chance to test the new beta on my Windows 7 machine and it's even worse than Windows 10:

![image](https://user-images.githubusercontent.com/30921064/48303109-679cb100-e51b-11e8-8dd0-96cf1f1e35b5.png)

This is 1.4.6 beta. As you can see the Regular font is now bold and is using Segoe UI in Windows 7. Windows 7 has Segoe UI version 5.05—Windows 10 has Segoe UI 5.28—Arabic/Persian glyphs in version 5.05 of the font are just copy-pasted from Arial which is an abomination of the Arabic/Persian script. And its even worse in Arabic with heavy usage of ِ and َ and ُ and ً and ٌ and ٍ

And funny thing is that regular text is using Segoe UI Bold. And the Bold text is using Tahoma regular. The itallic text is also using Tahoma.

In 1.4.3 all were using Tahoma. Bold didn't work, yes, but Tahoma has a bold weight, TDesktop is just not using it:

![image](https://user-images.githubusercontent.com/30921064/48303115-77b49080-e51b-11e8-9298-7b209137d547.png)

Now in Windows 10:

![image](https://user-images.githubusercontent.com/30921064/48303117-7f743500-e51b-11e8-81fa-02d072b52656.png)


Both regular and bold are using Segoe UI correctly, but itallic version is still Tahoma.

Beside this mix up, the problem with using Segoe UI as Arabic/Persian fallback font is that Windows 7 has 5.05 version of that font and the Arabic/Persian glyphs in that version are just copy-pasted from Arial. MS finally saw the mistakes in them and tried to fix them in Windows 8.1 by re-designing Arabic/Persian glyphs but again failed miserably. That's why there are so ugly even in Windows 10. They have been re-designed from Arial glyphs with a little Tahoma in mind.

According to the developer of TDesktop, now it is using Segoe UI as Arabic/Persian fallback font instead of Tahoma. But why use such inferior font when Tahoma is still better?

If it's about the bold issue, Tahoma has bold weight, TDesktop is just not using it.

P.S if you want to see the sample text in the above images go here:

https://t.me/TelegramDesktopTalk/11020

**Comment by rezabrando** [comment]
Totally agree with this. The new font is unreadable and so bulky and truly ugly. Telegram Desktop already use Google Open Sans as its default font, so why not use Google Noto Sans Arabic UI:

https://www.google.com/get/noto/#sans-arab

It's clean and also not so formal like Google Noto Naskh Arabic:

**Comment by alisentinel** [comment]
@FreedomPrevails you can use it in any app after purchasing it, if you want use it in commercial apps, you must pay another license for it. If you want, contact me at t.me/alisentinel

I can sign a free non-commercial license for telegram-desktop if they decide to use it, most Iranian apps and website use this font, so it's so user-friendly.

**Comment by john-preston** [comment]
@Aphotice Usually Qt manages fallback fonts, I guess it chose Tahoma before.

I've requested to use Segoe UI as a fallback for Open Sans, because I thought it would be a better fallback, since I thought it is a Windows UI font and should be fine for everybody.

I can't set fallbacks specifically for some language characters, like "fallback for Arabic". Just a fallback font for all glyphs that are not available in the main font.

I think I'll just revert that change for now.

That's strange, I was sure Segoe UI was better than my font and Qt fallback selection. More than that, originally (back in the early days) Telegram Desktop had Segoe UI as it's UI font on all platforms, had it bundled with the app. And only much later it was replaced by Open Sans.

**Comment by FreedomPrevails** [comment]
@john-preston Is it hard to make the font configurable in the settings ?
The current Windows issue aside, the Persian font looks ugly on Mac as well.
If you could make the font configurable, you would kill 2 birds with one stone ;)

**Comment by omoridi** [comment]
Also is bad in version 1.4.7
Please let us to change font and find best font for viewing.
I think below font is good for Persian.
https://github.com/rastikerdar/vazir-font

**Comment by wthreex** [comment]
@john-preston, Bring back Tahoma font (as a persian guy this the best option) and keep the formatting on it (Bold).
