### ISSUE TITLE
Direct share: inconsistent keyboard shortcuts to send the message(s) when a comment is added

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#5369]
### Steps to reproduce
1. click on the direct share icon
2. select one or more recepient(s)
3. write something in the comment input box
4. use CTRL+ENTER

### Expected behaviour
The messages are sent (CTRL + ENTER is the keyboard shortcut to share the messages when no comment is added)

### Actual behaviour
ENTER sends the message(s) with the comment, and CTRL + ENTER adds a newline. This is both incosistent with how messages are sent from the direct share menu when no comment is added, and also with how newlines in similar input boxes (eg. captions) are added (SHIFT + ENTER))

In my opinion a good solution would be use ENTER or CTRL+ENTER depending on the user's settings, or using CTRL+ENTER to send the message and ENTER to add a newline (even though this would be the opposite of the default settings to send/add a new line in the chat screen)

### Configuration

**Version of Telegram Desktop:** 1.4.5

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6634 better generic ticket
