### ISSUE TITLE
[BUG] Tilde character (~) shows up as a straight line

### ISSUE THREAD

**Issue by JuanPotato** [telegramdesktop/tdesktop#537]
![default](https://cloud.githubusercontent.com/assets/9531780/6526118/dd0582a2-c416-11e4-849f-0490ed8a915e.gif)
any time I type in ~ it comes out as a straight line. (refer to gif above)

**Comment by Katzen-Gott** [comment]
Please have a look at #27 (Tilde isn't gone. It's just rendering as a dash in certain sizes of the font)
