### ISSUE TITLE
Twitter posts with photo and video look the same

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#5371]
Original post in Twitter
![image](https://user-images.githubusercontent.com/10371194/48293280-5efe9900-e48f-11e8-8bc4-f2a80840c972.png)

In Telegram post with video looks like usual photo
![image](https://user-images.githubusercontent.com/10371194/48293340-94a38200-e48f-11e8-87ea-1dd8c4fc32e6.png)

Instagram messages with photos and videos are different. Please add it for Twitter too.

### Configuration
**Operating system:**
win10
**Version of Telegram Desktop:**
1.4.5
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stek29** [comment]
#2942
