### ISSUE TITLE
Why i can not join to some groups?

### ISSUE THREAD

**Issue by alirezaimi** [telegramdesktop/tdesktop#5373]
### Steps to reproduce
1. join to some groups like TelegramDesktopTalk or pythontelegrambotgroup or ... in any clients app (android, desktop)
![image](https://user-images.githubusercontent.com/1029949/48299316-022bce80-e4e1-11e8-890a-d93a44b216e6.png)
![image](https://user-images.githubusercontent.com/1029949/48299324-25ef1480-e4e1-11e8-9e11-714ef488df50.png)

### Expected behaviour
join to group !

### Actual behaviour
Some weird error : username XXX not found .

### Configuration
**Operating system:**
any.
**Version of Telegram Desktop:**
1.4.5
**Used theme**:
zalimz

**Comment by stek29** [comment]
What country do you live in?
Can you access other public groups?

**Comment by alirezaimi** [comment]
@stek29 what country ?! seriously country is important for telegram?!!!!!!! 
iran.
yes i can join to other groups, these groups are my problem.

**Comment by omkarnathsingh** [comment]
@alirezaimi Iran users can't join public groups and channels.

**Comment by alirezaimi** [comment]
@alirezaimi on what reason ?!
This is so ridiculous that telegram banned total country with big number of users from accessing to some of its features !!
If this solution is for some problem, then telegram proved that unable to solve problems!

**Comment by omkarnathsingh** [comment]
@alirezaimi There were lot of reports of Iran users spamming in groups, through bots, bot accounts. Telegram considers Iran as spam heavy country, therefore this restriction. Maybe you are a new user, but this restriction is since a long time.

**Comment by alirezaimi** [comment]
@omkarnathsingh 
I have telegram account since beginning days of telegram existence and use it for most of my work communication or ... , but this is very disappointment that i can't join to public community !
`Telegram considers Iran as spam heavy country` !? so !? banned a country for some spam users !? sounds like government ...

**Comment by omkarnathsingh** [comment]
@alirezaimi If possible, as a work-around you can use a Non-Iranian phone number and use with a VPN/Proxy. Many of Iran users do that. I am unsure when will Telegram remove this restrictions.

**Comment by alirezaimi** [comment]
@omkarnathsingh 
thanks for your support, but i'm using of one proxy for by passing my government ideas!
the second one is so absurd, i'm prefer use another messaging app like whatsapp or ...

**Comment by AndydeCleyre** [comment]
This is awful! 

Is there any place to track "api issues" like this?
