### ISSUE TITLE
.Webp files are not displayed.

### ISSUE THREAD

**Issue by Edicksonjga** [telegramdesktop/tdesktop#5374]
### Steps to reproduce
1. Open any Chat.
2. Send .webp file.
3. File is not displayed as Stickers.

![error](https://user-images.githubusercontent.com/37910384/48302806-d35d2a80-e4d7-11e8-8bf2-6fbdec478c79.png)

### Configuration
**Operating system: Windows 7**

**Version of Telegram Desktop: 1.4.5, 1.4.6, 1.4.7**

PD: In version 1.4.5 after sending the .webp file, closing Telegram and reopening generated a "Crash" that was removed by deleting cache. Corrected in version 1.4.6.

**Used theme**: Default.

**Comment by Edicksonjga** [comment]
After several revisions, Telegram Desktop does not check the integrity of the file. This problem occurs when renaming a jpg (or other) file to webp, without converting.

In versions prior to 1.4.5 the application had no problem in viewing a file with Webp format and with the same extension or a file with JPG format and .webp extension.

In the most recent version (1.4.7) send a file with JPG format and .webp extension is not displayed neither for the sender nor for the receiver, but what happens if I closed TDesktop and reopen it ?, the files previously sent (JPG.webp) are visible to the receiver but not to the sender. No hay problemas con archivos Webp.webp.

**Comment by john-preston** [comment]
@Edicksonjga Is it right, that in 1.4.7 the problem is only with ".jpg" files renamed to ".webp". The real ".webp" files (with WEBP content) work fine?

Before 1.4.5 ".jpg" files renamed to ".webp" worked fine too?
