### ISSUE TITLE
Reducing clickbait potential

### ISSUE THREAD

**Issue by beppe9000** [telegramdesktop/tdesktop#5375]
Some channels use this underhanded technique to attract users by disguising the join channel url as an amazon link to an "incredible offer".

![image](https://user-images.githubusercontent.com/6625123/48302836-22b85080-e502-11e8-91d2-2752b6981804.png)

This could also be seen as a potential security issue... see the example below.

The fix would be to show links where the title is an URL that differs from the actual href in an expanded form. 

Such as:
"[http://yourbank.com/](http://evilpasswordharvester.com/)" becoming "http://yourbank.com/ (http://evilpasswordharvester.com/)"
"[http://amzn.to/2riuq7q](https://t.me/joinchat/A_chann_id)" becoming "http://amzn.to/2riuq7q (https://t.me/joinchat/#id)"

Maybe it could be added in global settings with three possibilities: "Expand all links", "Expand mismatched links", "Disabled". That way people can be certain of what they are clicking...

**Comment by omkarnathsingh** [comment]
Don't you see such type of pop-up when opening links?
![Image](https://user-images.githubusercontent.com/12734027/48310066-e8f05400-e5ac-11e8-8e97-8ee4e3939505.png)

**Comment by beppe9000** [comment]
Nope. I have latest version according to the software, and dont' recall disabling anything.

**Comment by stek29** [comment]
confirmation is not shown for t.me -- that's a feature.

**Comment by beppe9000** [comment]
> confirmation is not shown for t.me -- that's a feature.
Wait! That's not the point of this issue.

The problem is that in my example the link text is also an URL, *a different URL*, with great misleading  potential.
