### ISSUE TITLE
No way to stop download of beta version

### ISSUE THREAD

**Issue by wodim** [telegramdesktop/tdesktop#5376]
If in Settings -> Advanced you click the "Install beta versions" button, the beta (and potentially unstable) version will start to download and install with no way to cancel the process.

**Comment by omkarnathsingh** [comment]
@wodim DIsable "Install beta versions" settings if you don't want that.

**Comment by wodim** [comment]
Not really a satisfactory answer. Isn't it possible to add a button to stop the download of a new version?

**Comment by stek29** [comment]
that's not really related to betas, I'd suggest you to make a new issue

**Comment by wodim** [comment]
Well, it's a UX failure nevertheless. The "check for updates" button is a few pixels away from the "install betas" button. The "nuke my telegram" option shouldn't be there just like that.
