### ISSUE TITLE
[Feature Request] Unread counter in windows desktop version.

### ISSUE THREAD

**Issue by psyflame** [telegramdesktop/tdesktop#5378]
Hello! Tnx this perfect messenger! And sorry for my english.

I subscribe many channels and chats in telegram. Each send many messages per day.
In mobile version, example i open unread channel or chat - unread messages counter deсrease as you read.
In desktop version, in this case - unread message counter equals zero.

Can you realise this feature in desktop version?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/775
