### ISSUE TITLE
24 hour timstamp support in linux

### ISSUE THREAD

**Issue by roberth1990** [telegramdesktop/tdesktop#538]
It would be great to have 24 hour timestamp support.

**Comment by nmat** [comment]
This seems to be supported in the client I use for windows 8.

**Comment by roberth1990** [comment]
Well it doesn't in linux.

**Comment by bil-elmoussaoui** [comment]
+1

**Comment by Rua** [comment]
Please add this. My system uses 24 hour time the way I want, locale settings are correct. But Telegram insists on using 12 hour time and there's no option to change it.

**Comment by Aokromes** [comment]
Works for me (TM) on slackware but fails on debian 8.

**Comment by pshpsh** [comment]
LC_TIME="C"

**Comment by Aokromes** [comment]
#618 better generic ticket?
