### ISSUE TITLE
online contact indication in the general list

### ISSUE THREAD

**Issue by C-A-T9LIFE** [telegramdesktop/tdesktop#5382]
### Steps to reproduce
1. View the entire list of contacts

### Expected behaviour
Visibility of who is online, without opening a profile

### Actual behaviour
I can not see who is online

### Configuration
Operating system: Windows 10

Version of Telegram Desktop: 1.4.7 beta

Used theme: Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
#2435
