### ISSUE TITLE
A file wasn't overwrote when save mp4 as a name that already exists.

### ISSUE THREAD

**Issue by dorbae** [telegramdesktop/tdesktop#5383]
### Steps to reproduce
1. I received a media file (mp4).
2. Save this file as name that already exists in local/
3. Click 'Overwrite' button in a dialog that ask overwrite file
4. There were nothing to notify errors. But, file is not replaced. 

### Expected behaviour
File is not overwrote.

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
OS X Mojave 10.14.1
**Version of Telegram Desktop:**
4.6.1.143380
**Used theme**:
Default. May be System Apperance

**Comment by stek29** [comment]
> Version of Telegram Desktop:
> 4.6.1.143380

This is not TDesktop but a different app -- from https://macos.telegram.org.
You can get TDesktop at https://desktop.telegram.org.
(There are two apps in Mac App Store as well).

You can report issues in the app you're using at https://t.me/macswift, or at https://github.com/overtake/TelegramSwift.
