### ISSUE TITLE
Enhancement: Notification on custom strings in group chats

### ISSUE THREAD

**Issue by 2-3** [telegramdesktop/tdesktop#5385]
**Current behavior:**
When a users username is mentioned in a group chat, they receive a notification, and a graphical element appears in the group chats window to allow them to quickly scroll to the relevant message.

**Proposed behavior:**
Additionally to their username, let the user specify per-chat and/or global strings that exhibit the same behavior.

**Motivation:**
Many users use Telegram for support of software. This would help them reply quickly to questions on relevant, differing topics. Additionally, users are sometimes colloquially referred to by multiple nicknames or want to discuss specific topics, and this would enrich their experience.

The first problem can be solved by bots, but it would mean allowing those bots full access to the chats log. The second problem can argued to have a negligible impact. Nevertheless, a similar feature in the majority of IRC clients is well-used and has become an ergonomic standard in these programs.

**Comment by RememberTheAir** [comment]
Duplicate of #4800

**Comment by 2-3** [comment]
I did search, but didn't find that. Sorry!
