### ISSUE TITLE
emoji button onmouseover is annoying

### ISSUE THREAD

**Issue by crevice** [telegramdesktop/tdesktop#5386]
Emoji button that activates every time when the cursor moves through chat text area is very annoying.
It happens every time when i open telegram from tray and navigate to chat, especialy if i want to click scroll down button. Emoji popup covers all chat area and i have to navigate outside telegram window, or click on emoji icon, or do whatever else to it disappear.
![2222](https://user-images.githubusercontent.com/3299740/48481342-417a5800-e81e-11e8-8eb7-eff7e1061208.png)
Also that icon has very giant hitbox, *like your character in dark souls game*, so you can hit it very easily.
![223235352](https://user-images.githubusercontent.com/3299740/48481363-50f9a100-e81e-11e8-9fb5-5120ab4669f6.png)
**So that is proposition: Make emoji button activate on click, like "clip" button on left side of chat text area. Or offer user a choise to disable some of onmouseover events.**

**Comment by Aokromes** [comment]
#4868 https://github.com/telegramdesktop/tdesktop/issues/4523
