### ISSUE TITLE
Visual Studio Build Process issues

### ISSUE THREAD

**Issue by zemuss** [telegramdesktop/tdesktop#5387]
Sorry details below. First issue posted.

**Comment by zemuss** [comment]
Hi I followed the build process from this link: https://github.com/TelegramOrg/Telegram-desktop/blob/dev/docs/building-msvc.md

I get errors on openal-soft making the debug and release. 

I was wondering if anyone has this built follwing these steps? It appears there are some steps missing in the process. 

If I follow the process all they way to the end the Telegram.sln file doesn't get created.

I would like to debug the code to see how the messages are being sent to the chat groups. I am trying to see if it is Polling being used or Event Driven architecture. 

Thanks,
Z

**Comment by Aokromes** [comment]
#5155

**Comment by zemuss** [comment]
Thanks you I will do that tonight.
