### ISSUE TITLE
Application crash when doing clear history and scroll on list of chats

### ISSUE THREAD

**Issue by SaeedZhiany** [telegramdesktop/tdesktop#5390]
### Steps to reproduce
1. Right click on one of groups on chat list and clear history of that group.
2. scroll up (or down) on list

### Expected behaviour
Application must work normally.

### Actual behaviour
Suddenly application completely exit (without any error message) and I must run it again.

### Configuration
**Operating system:**
windows 10
**Version of Telegram Desktop:**
1.4.3
**Used theme**:
RainFall by @May29themes (it can be found at @themes channel)

**Comment by john-preston** [comment]
@SaeedZhiany Can you try the latest beta version? Enable updating to beta in Settings > Advanced.

**Comment by SaeedZhiany** [comment]
@john-preston 

I tried the same scenario on latest beta version. the problem still remains.

**Comment by SaeedZhiany** [comment]
I recently test the scenario on version 1.5.1, the problem has been gone. so I close this issue.
