### ISSUE TITLE
High power consumption on macOS

### ISSUE THREAD

**Issue by Eik-S** [telegramdesktop/tdesktop#5391]
The power consumption of telegram desktop on macOS is too high.

### Steps to reproduce
1. Start Telegram
2. Open the activity monitor

<img width="322" alt="screenshot 2018-11-16 at 11 17 54" src="https://user-images.githubusercontent.com/9152141/48615468-4ad80180-e991-11e8-9779-2222a797b4ff.png">

### Configuration
**Operating system:**
MacOS Mojave 10.14.1 (18B75)

**Version of Telegram Desktop:**
Telegram 1.4.7 Beta

**Comment by Aokromes** [comment]
#4854 
#4914
#5087
