### ISSUE TITLE
Open File Dialog for a MP3 file has no selectable file types.

### ISSUE THREAD

**Issue by peymanr34** [telegramdesktop/tdesktop#5392]
### Steps to reproduce
1. Right Click on a MP3 file from a chat or channel
2. Select "Save Audio File As..."

### Expected behaviour
In "Save as type" section filters expected: `MP3 Files (*.mp3)|*.MP3|All files (*.*)|*.*` 
### Actual behaviour
"Save as type" is empty.

### Configuration
**Operating system:**  Windows 10 Pro 64-bit Version 1803 (OS Build 17134.376)

**Version of Telegram Desktop:** 1.4.3

**Comment by john-preston** [comment]
I can't reproduce that in the latest, please try 1.4.7 beta. I get this:

![image](https://user-images.githubusercontent.com/17900494/48702420-4ff3b580-ec0a-11e8-9e66-f911c3c303de.png)

**Comment by peymanr34** [comment]
I've checked a few MP3 files and apparently this issue occurs with some particular MP3 files.

Files that have this issue:
https://t.me/kambizhosseini/2106
https://t.me/Fareenassemi/957

**Comment by peymanr34** [comment]
@john-preston Hi, Thank you.
