### ISSUE TITLE
Caption field is too small

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#5395]
Since caption limit was increased to 1024, caption field looks too small for this. Its height only 3 lines, ~300px each. It's really small, and you can't see most of your message, if you have big caption, you'll need to scroll a lot.
Caption of multiple files has standard char limit, so for these messages it hurts even more.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2060 generic ticket
