### ISSUE TITLE
Automatic split into albums

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#5397]
If you send more than 10 files and all of them are media files, splitting into albums would be good, because, for example, if you send 100 images, receiver will get only 10 notifications, and they won't need to scroll too long.

**Comment by Lonami** [comment]
I imagine this could get tricky in the dialog that lets you choose how to send them, which allows reordering.

**Comment by RadRussianRus** [comment]
@Lonami
Personally I think that reordering doesn't need here. You can't even see previews if you send too many files, so why bother? If you have time to reorder ~100 pictures, you probably have time to split them by 10 yourself, no?

**Comment by RadRussianRus** [comment]
Still needed.

**Comment by RadRussianRus** [comment]
I think 2.4.5 fixed this issue.
