### ISSUE TITLE
Linux auto update not working properly.

### ISSUE THREAD

**Issue by kenetik** [telegramdesktop/tdesktop#540]
The client properly detects when an update is available, even successfully downloads 'an update' and prompts to restart for the installation upgrade. After restarting, it remains the same version. 

Check out the video: http://youtu.be/OysVsY-kGQg

**Comment by auchri** [comment]
#436

**Comment by kenetik** [comment]
@auchri 

Thanks, gave me what I needed. I fixed the issue for myself on Arch Linux as follows:

    $ whereis telegram
    telegram: /usr/bin/telegram
    $ whoami
    kenetik
    $ sudo chown -R kenetik:users /opt/telegram && sudo chmod -R 777 /opt/telegram

**Comment by ManuelSchneid3r** [comment]
please put telegram into the  proper place /usr/bin and ask for superuser passwort to replace the binary
