### ISSUE TITLE
The huge Mute/Unmute button is too easy to click unintentionally

### ISSUE THREAD

**Issue by ElTopo** [telegramdesktop/tdesktop#5400]
### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.4.7 beta

**Used theme**:
n/a

For channels, there's a huge Mute/Unmute button (replacing the message input box) for user to mute/unmute the channel notification.

Unfortunately, the button is HUGE, and when the Telegram window is only partially visible (covered by other windows), it's way too easy to unintentionally click on it to change status, when user only wants to switch Telegram window to the front. 

I have clicked on the button (many times) without knowing the status was changed, only realized later the channel was muted.

Since user can enable/disable notificaton in the 3-dot menu, can we at least have an option to hide the button if we can't totoally remove it? To be frankly honest I never found that I need such a huge button just for changing status, I much prefer a little bell icon next to search.

**Comment by stek29** [comment]
sorry, but this is consistent with other telegram apps and is unlikely to be changed.

**Comment by ElTopo** [comment]
> sorry, but this is consistent with other telegram apps and is unlikely to be changed.

As far as I know, Telegram X for Android, which is official from Telegram, does not have the "Mute/Unmute" button:
https://play.google.com/store/apps/details?id=org.thunderdog.challegram
