### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by Dimansel** [telegramdesktop/tdesktop#5401]
### Steps to reproduce
1. Get Ubuntu 18.04
2. Follow Build instructions for GYP/CMake under Ubuntu 14.04
3. ... Profit!

### Expected behaviour
Successful build

### Actual behaviour
Failed to compile Qt

### Configuration
**Operating system:**
Ubuntu 18.04
**Version of Telegram Desktop:**
Latest on the dev branch
**Used theme**:

<details><summary><b>Logs</b>:</summary>
<a href="https://gist.github.com/Dimansel/b6bb81ec1d48d378b862c0c5e9fff026/raw/fb9182486fbc37b4fe6e5eed8979c51c8584e18e/log.txt">Terminal output</a>
</details>

**Comment by Aokromes** [comment]
#4926
