### ISSUE TITLE
Editing a message with code 

### ISSUE THREAD

**Issue by ericbrandwein** [telegramdesktop/tdesktop#5402]
### Steps to reproduce
1. Send a message with code in it 
2. Edit it

### Expected behaviour
The backticks ("```") should be shown surrounding the code, so that it can be edited without having to write the backticks again.

### Actual behaviour
The code is shown already formatted in the edit input.

### Configuration
**Operating system:**
Arch Linux

**Version of Telegram Desktop:**
1.4.3

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Lonami** [comment]
The input field has formatting support so there's no need to "add back" the backquotes (which maybe never were put there in the first place, since one can right click or shortcuts to format).

This issue can probably be closed.

**Comment by ericbrandwein** [comment]
Oh  you're right, closing then

**Comment by Sutarat66** [comment]
ช่วยอธิบายเมลที่ส่งมาหาฉัน มันคืออะไร

เมื่อ พฤ. 6 ธ.ค. 2561 เวลา 06:31 Eric Brandwein <notifications@github.com>
เขียนว่า:
