### ISSUE TITLE
No check for updates if running with -many

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#5403]
### Steps to reproduce
1. Start TDesktop with `-many` option
2. Go to Settings > Advanced > click "Check for updates"

### Expected behaviour
It should check for updates.

### Actual behaviour
No update check happens.

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.4.7 beta

P.S. If update isn't allowed with `-many`, why show it?
P.S.2. I don't know why would you ever need multiple copies of Telegram with same account, settings and session. You can use `-workdir` for much better behavior.

**Comment by john-preston** [comment]
@RadRussianRus -many and -workdir should be removed, just use several portable versions for that.

**Comment by RadRussianRus** [comment]
@john-preston Why remove `-workdir`? It's actually useful. You don't need to update every Telegram EXE, you can just update one.

**Comment by RadRussianRus** [comment]
@john-preston 
1. It works fine with autoupdate. `-many` causes problems, but `-workdir` alone works file (but I'm closing all other instances before updating, just in case).
2. Opening links from browser correctly is pain with portables too. You can't choose instance anyway, you're depending on registry or `xdg-open`.

If there was multi-account support, I wouldn't bother.

**Comment by john-preston** [comment]
@RadRussianRus Currently multiple portable versions is as close as it gets to multiple account support. The only argument against it is autoupdate working independently for each instance. But is that really a problem? They'll download slowly in the background and be applied the next time you launch them, why not?

**Comment by Aokromes** [comment]
maybe allow to enable / disable autoupdate from command line?

**Comment by RadRussianRus** [comment]
There is an `-externalupdater` option for that IIRC.
