### ISSUE TITLE
[Feature Request] "Send as Sticker" option

### ISSUE THREAD

**Issue by deletescape** [telegramdesktop/tdesktop#5404]
### Requested feature
An option to send the image as a sticker in the photo sending UI which converts the image to a webp file of the appropriate size and sends that
![image](https://user-images.githubusercontent.com/13785669/48696800-312df880-ebe3-11e8-9201-a86ddc5e1014.png)

### Expected behaviour
There is a button to send the image as a sticker

### Actual behaviour
There is currently no such option

### Configuration
**Operating system:**
Any
**Version of Telegram Desktop:**
1.4.7
**Used theme**:
Any
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stek29** [comment]
Image has to be in webp format to be sent as sticker.
