### ISSUE TITLE
Modal (popup) window loses focus

### ISSUE THREAD

**Issue by Nommyde** [telegramdesktop/tdesktop#5405]
### Steps to reproduce
1. Drag'n'drop a file or paste image into a chat.
2. Press Tab inside the opened modal window

### Expected behaviour
The focus stays inside the modal window (or the window closes)

### Actual behaviour
The focus moves to an inactive area (search input on Tab and message input on Shift+Tab in my case)

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 1.4.3

**Used theme**: default

**Comment by stek29** [comment]
I use that as a feature :D

**Comment by Laiteux** [comment]
Still there

**Comment by Nommyde** [comment]
Still there

**Comment by Sominemo** [comment]
Still here

**Comment by Sominemo** [comment]
Can't touch this

**Comment by Sominemo** [comment]
Still relevant

**Comment by Nommyde** [comment]
Still relevant

**Comment by john-preston** [comment]
It should be fine in the latest version 4.8.8.
