### ISSUE TITLE
Too short name of attached files.

### ISSUE THREAD

**Issue by Dustver** [telegramdesktop/tdesktop#5406]
### When I'm see attached files in conversation screen, long names of files are minimazing.
![telegram-bad-attached-names](https://user-images.githubusercontent.com/12172413/48767742-6ceebe00-ecc8-11e8-9803-16ba6472e396.png)

I want to wrap words in two string to view more readable names of files. Or resize body of message.

_OS: Ubuntu 18.10
TDesktop: 1.4.3
Theme: Night Standart_

Thank you.

**Comment by RadRussianRus** [comment]
There is actually problem not just with files. Chat names that are too long are truncated too. I'd like to suggest at least show full name in a tooltip on mouse over.
