### ISSUE TITLE
怎么安装

### ISSUE THREAD

**Issue by alexischiang** [telegramdesktop/tdesktop#5409]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RadRussianRus** [comment]
In English, please. And it would be better to actually fill issue template.
