### ISSUE TITLE
[Feature Request] Customize font 

### ISSUE THREAD

**Issue by KazamaSion** [telegramdesktop/tdesktop#5410]
### Expected behaviour
The user can choose a specific font using in the application.

The reason why this feature is necessary is that in some system environment, like use Chinese in English operation system with Windows, the font is toooooo ugly to see daily.

**Comment by Aokromes** [comment]
#90

**Comment by RadRussianRus** [comment]
@KazamaSion
If you're on Windows, you can use this `winmm.dll` hook:
https://github.com/ysc3839/TGFont

Native way is not implemented yet.

**Comment by KazamaSion** [comment]
@RadRussianRus I knew this repo, but if it is a built-in feature that will be great.
