### ISSUE TITLE
Download pause 

### ISSUE THREAD

**Issue by RSanjeevi** [telegramdesktop/tdesktop#5411]
### Steps to reproduce
1. only download cancel option in is available
2. need  download pause option

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3989 imho make this generic.

**Comment by Lonami** [comment]
This should probably be closed as a duplicate of #3989 indeed (after making that generic).
