### ISSUE TITLE
Image and video opens on another display

### ISSUE THREAD

**Issue by doubledare704** [telegramdesktop/tdesktop#5412]
### Steps to reproduce
1. Install telegram desktop for ubuntu 18.04.1, open telegram on some display (for e.g we have 3 displays, 0 1 2, open telegram on 2nd index)
2. enter a chat or channel with video or image
3. click on image-video, client opens image or video on display with 0 index ( another display from display where image was clicked or where was telegram client)

### Expected behaviour
Tell us what should happen
Image or video opens on same display
### Actual behaviour
Tell us what happens instead
Opens image-video on notebook's display
### Configuration
**Operating system:**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Version of Telegram Desktop:**
v 1.4.3.
**Used theme**:
midnight
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stek29** [comment]
#5126
