### ISSUE TITLE
Segfault on network disconnect on Linux systems without NetworkManager

### ISSUE THREAD

**Issue by ilya-fedin** [telegramdesktop/tdesktop#5413]
### Steps to reproduce
1. Connect to Wi-Fi network on Linux system with Connman or other network manager, but not NM
2. Disconnect from Wi-Fi network
3. Repeat until segfault (about 3 times)

### Expected behaviour
No segfault

### Actual behaviour
Segfault

### Configuration
**Operating system:** Arch Linux, Void Linux

**Version of Telegram Desktop:** 1.4.3

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
<a href="https://github.com/telegramdesktop/tdesktop/files/2609254/log.txt">log.txt</a>

<a href="https://github.com/telegramdesktop/tdesktop/files/2609255/strace.txt">strace.txt</a>
</details>

**Comment by xvitaly** [comment]
#5218
