### ISSUE TITLE
utf8 with BOM encoding language file

### ISSUE THREAD

**Issue by cmpfrc** [telegramdesktop/tdesktop#5414]
### Steps to reproduce
1. Save a language file with utf8 BOM encoding
2. Try to load on Tdesk
3. 

### Expected behaviour
Telegram desktop should accept any utf8 file, with or without bom

### Actual behaviour
An error occurs:
"Custom lang failed :(
Error: Expected quote before key name!"

### Configuration
**Operating system:**
Win10
**Version of Telegram Desktop:**
1.4.3
**Used theme**:
Classic
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Lonami** [comment]
UTF-8 BOM is so counter-productive. It makes UTF-8 not ASCII compatible. There isn't really a reason to add a BOM, or to support it in TDestkop. This issue can be closed in my opinion.
