### ISSUE TITLE
Flickering GIFs

### ISSUE THREAD

**Issue by Knocks83** [telegramdesktop/tdesktop#5416]
I did nothing to make it appear, i just opened it.
TGD on Windows 10, version 1.4.7.

Night mode on.

The GIFs i send and receive flickers
[Video](https://1drv.ms/v/s!Agyx5q7Fjy04gfEVm1kt7bEFlw3Ehg)

**Comment by stek29** [comment]
tldw: it's a sticker, and the flickering looks like switching from hi-res file to low-res preview

**Comment by StickGuySeven** [comment]
Just updated to 1.5.0 and then to 1.5.1. Issue came up for me as well. This seems to be related to the gif menu being open. Certain gifs I had in the list would make it speed up or slow down swapping back and forth between the high and low res versions. To add onto as well, some gifs fail to load properly where the loading circle is shifting a random to different loading points. Gifs that seem to relate to this issue are extremely random and are from various sources.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Knocks83** [comment]
Sometimes it still does it, I haven't ckecked for the last update (I updated it a few hours ago) but on the previous update it was still doing it

**Comment by StickGuySeven** [comment]
Yeah, still happening on 1.9.8 for Telegram PC
