### ISSUE TITLE
Press TAB to auto-complete inline-bot names

### ISSUE THREAD

**Issue by pedrogarcia** [telegramdesktop/tdesktop#5417]
### Steps to reproduce
1. Pressing tab does not auto-complete inline bot names in individual chats. 

### Expected behaviour
In any field where you can @ someone, in groups or individual chats, pressing tab should auto-complete for inline-bot names. 

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.4.3

**Comment by MasterGroosha** [comment]
Have you tried it yourself? Works like a charm for a very long time (definitely more than a year). You type "@", use up/down arrow to select inline bot, press Tab and have autocompletition.

**Comment by pedrogarcia** [comment]
It only works if you have interacted with the bot before. That's why it wasn't working for me.
