### ISSUE TITLE
[Feature Request] Stripping @ in url

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5418]
Stripping @ in url while resolving tg protocol
https://t.me/@GmailBot will just open telegram only
It works in telegram x

**Comment by stek29** [comment]
That sounds more like Telegram X inconsistency, and something that should be fixed in TGX tbh,.

**Comment by Lonami** [comment]
> and something that should be fixed in TGX tbh

What's the reason to keep this open?
