### ISSUE TITLE
Can't Log In (Need Help)

### ISSUE THREAD

**Issue by antuketot76** [telegramdesktop/tdesktop#5419]
Hi guys, can anyone help me to recover back my account

 
### Steps to reproduce
1. I want log in to my account back.
2. Cant access my phone number.
3. Will provide details to proven the account

### Expected behaviour
I use my telegram desktop using **[container](https://help.comodo.com/topic-72-1-766-9027-Containment-Tasks---Introduction.html)** provided by Comodo Internet Security, yesterday I open my telegram desktop but failed due to telegram ask me log in back.

### Actual behaviour
I try to log in back using my virtual phone number (Primo) but failed due to I cant access anymore to this paid virtual number because this company (Primo) already shutdown their bussiness. Primo transfer all their paid user to new company **[TextPlus](https://textplus.com/)** and replace with new virtual number.
How I gonna access my telegram account back?
I need this account and dont want to loose it, plz help me

### Configuration
**Operating system:** Window 10 Pro 64bit

**Version of Telegram Desktop:** v 1.4.3

**Used theme**: N/A

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stek29** [comment]
There's no way we can help with that here.
Neither can Telegram Support, and I doubt that it'd be ever done.
You should change your number when you lose access to it to avoid situations like this.
Sorry that I can't help you.
