### ISSUE TITLE
[OS X] Text size for chat quotations

### ISSUE THREAD

**Issue by andreyvolokitin** [telegramdesktop/tdesktop#5427]
### Steps to reproduce
1. Set the biggest font size inside "Settings -> Appearance -> Text size"
2. Open chat log
3. The text size for quotations remains small. Other chat text is big as defined by settings

### Expected behaviour
Text size for quotations inside chat log should change according/relatively to text size setting

### Actual behaviour
Text size for quotations remains unchanged despite of the text size setting being used 

### Configuration
**Operating system:** OS X 10.11.4 

**Version of Telegram Desktop:** 4.6.1.143380 AppStore

**Used theme**: Dark Mojave, Minimalist chat view

**Comment by RememberTheAir** [comment]
You are not using Telegram Desktop, you are using https://github.com/overtake/TelegramSwift
