### ISSUE TITLE
Gifs sometime do not get sent

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#5428]
Hard to reproduce :(
### Steps to reproduce
1. Search a gif
2. Send it

### Expected behaviour
gif is sent

### Actual behaviour
gif is not sent, stuck in "sending" state

### Configuration
**Operating system:**
Windows (7 and 10)

**Version of Telegram Desktop:**
1.4.7

**Used theme**:
irrelevant

Can workaround it by relaunching Telegram Desktop.

**Comment by john-preston** [comment]
@Geobert Right after that happens you can look to "log.txt" and see if there is an error at the bottom of the log.

Perhaps you search for GIFs and then the results are there, staying open, for some long time (like, half an hour or an hour) and only after that you try to send it?

**Comment by Geobert** [comment]
I try this to reproduce :) But today, my GF got the issue from the already sent gif history (without searching).

**Comment by john-preston** [comment]
@Geobert Yeah, they don't live very long :(

**Comment by Geobert** [comment]
But why I need to restart Telegram to get rid of this?

**Comment by john-preston** [comment]
@Geobert I think you can just clear the search query and then try once again. Won't it work then?

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Geobert** [comment]
Yes, it's some kind of timeout with giphy

**Comment by Aokromes** [comment]
maybe then 3rd party bug and not telegram?

**Comment by Geobert** [comment]
I don't know, I though telegram could do some kind of workaround. It seems that a search in gifs is valid only for a few minutes. I don't know if there's a way to know how long or to test if the request is still valid from giphy. If invalid, then resend the request so when sending the gif, it just works :)
