### ISSUE TITLE
[Linux] Messed up font in UI

### ISSUE THREAD

**Issue by BehdadEs** [telegramdesktop/tdesktop#5429]
### Steps to reproduce
1. View some RTL text (Like Persian)

### Expected behaviour
Text should be readable

### Actual behaviour
Text is not readable at all in Persian language
![Preview](https://i.imgur.com/kv0SKQp.png)
Here is a normal text from my phone:
![Normal](https://i.imgur.com/rgtZQoD.jpg)
### Configuration
**Operating system:**
Ubuntu 18.10
**Version of Telegram Desktop:**
1.4.7 beta
**Used theme**:
Night mode

**Comment by john-preston** [comment]
@BehdadEs Please try the version from snapcraft.io at https://snapcraft.io/telegram-desktop

**Comment by BehdadEs** [comment]
> @BehdadEs Please try the version from snapcraft.io at https://snapcraft.io/telegram-desktop

@john-preston yep working perfectly fine now

**Comment by Aokromes** [comment]
#5172
