### ISSUE TITLE
Audio messages on Linux

### ISSUE THREAD

**Issue by aroblu94** [telegramdesktop/tdesktop#543]
Linux client does not have a button to record voice and send audio messages

**Comment by auchri** [comment]
Windows client doesn't have it too ;)

**Comment by ppparadox** [comment]
+1

**Comment by phplego** [comment]
+1

**Comment by evnemich** [comment]
+1

**Comment by giordano** [comment]
This should be closed as duplicate of #22

**Comment by Katzen-Gott** [comment]
@aroblu94 It was added in v0.19.8. Cold you please close the issue? (there is a button below the comment box)

**Comment by aroblu94** [comment]
I saw it, thanks!!
