### ISSUE TITLE
Telegram pops up on every click on system notification

### ISSUE THREAD

**Issue by Ri0n** [telegramdesktop/tdesktop#5430]
### Steps to reproduce
1. Install latest suse+kde or kubuntu 
2. Install any application capable to show system notifications
3. Click on the notification

### Expected behaviour
Notification-specific application appears on the screen

### Actual behaviour
Telegram pops up

### Configuration
**Operating system:**
suse tumbleween

**Version of Telegram Desktop:**
1.4.7 beta

**Used theme**:
classic

I have to notice a couple or a little more months ago it didn't have this problem.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stek29** [comment]
#1026
