### ISSUE TITLE
Squid stops working all of sudden (logs included)

### ISSUE THREAD

**Issue by aminvakil** [telegramdesktop/tdesktop#5437]
Squid Version 3.5.20 on CentOS Linux release 7.5.1804 was working fine with telegram until yesterday which suddenly I can't connect to telegram via my squid configuration, other apps are working fine.
My Laptop is Fedora 29 with telegram desktop installed via dnf.
Telegram Desktop Version: telegram-desktop-1.4.3-1.fc29.x86_64

Logs of squid:
```
1543845888.424      0 a.b.c.d TCP_DENIED/407 4170 POST http://91.108.56.130/api - HIER_NONE/- text/html
1543845889.131    363 a.b.c.d TCP_MISS/200 407 POST http://91.108.56.130/api "user" HIER_DIRECT/91.108.56.130 application/octet-stream
1543845889.607    335 a.b.c.d TCP_MISS/200 428 POST http://91.108.56.130/api "user" HIER_DIRECT/91.108.56.130 application/octet-stream
1543845889.867      0 a.b.c.d TCP_DENIED/407 4170 POST http://91.108.56.130/api - HIER_NONE/- text/html
1543845890.134    378 a.b.c.d TCP_MISS/200 860 POST http://91.108.56.130/api "user" HIER_DIRECT/91.108.56.130 application/octet-stream
1543845890.263     75 a.b.c.d TCP_MISS_ABORTED/000 0 POST http://91.108.56.130/api "user" HIER_DIRECT/91.108.56.130 -
```
a.b.c.d stands for my laptop ip and "user" stands for my username in squid configuration

Squid Configuration:
```
acl SSL_ports port 443
acl Safe_ports port 80		# http
acl Safe_ports port 21		# ftp
acl Safe_ports port 443		# https
acl Safe_ports port 70		# gopher
acl Safe_ports port 210		# wais
acl Safe_ports port 1025-65535	# unregistered ports
acl Safe_ports port 280		# http-mgmt
acl Safe_ports port 488		# gss-http
acl Safe_ports port 591		# filemaker
acl Safe_ports port 777		# multiling http
acl CONNECT method CONNECT
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access deny to_localhost
http_port ****
coredump_dir /var/spool/squid
refresh_pattern ^ftp:		1440	20%	10080
refresh_pattern ^gopher:	1440	0%	1440
refresh_pattern -i (/cgi-bin/|\?) 0	0%	0
refresh_pattern (Release|Packages(.gz)*)$      0       20%     2880
refresh_pattern .		0	20%	4320

dns_nameservers 213.133.100.100 213.133.99.99
dns_v4_first on

auth_param digest program /usr/lib64/squid/digest_file_auth -c /etc/squid/***
auth_param digest realm ***
acl users proxy_auth REQUIRED
http_access allow users
```
I've also tried this authentication method, but it doesn't work:
```
auth_param basic program /usr/lib64/squid/basic_ncsa_auth /etc/squid/***
auth_param basic realm proxy
acl authenticated proxy_auth REQUIRED
http_access allow authenticated
```
My server is in Hetzner Co. and I can connect to telegram by using socks5 proxy via ssh, so there isn't problem between my server and telegram servers.

**Comment by stek29** [comment]
not everyone is going to read through squid config and figure out what it does.

how exactly are you using TDesktop with it, and did it ever work with TDesktop?

btw, TDesktop only supports username/password auth for socks.

**Comment by aminvakil** [comment]
@stek29 It worked correctly before from proxy connections and setting up a http proxy, and it was working via username/password as well.

I've tried two authentication methods and without authentication and no one works now.

Also Squid is working fine with all websites, the only problem is with telegram.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by aminvakil** [comment]
As our country starts mass DPI, every squid server gets blocked within days, I uninstalled my squid servers and therefore I haven't tested it for an year.

I can't reproduce the error again.
