### ISSUE TITLE
[Feature request] Hide unwanted people in group chats

### ISSUE THREAD

**Issue by caiwan** [telegramdesktop/tdesktop#5438]
A feature would be nice if one can hide messages of certain people from group chat, regardless if they're blocked or not. In some group chat there may be toxic people who are edge-lords, annoying but doesn't violates any rule, or not being kicked for some reason, but ruins your chat experience with others. Just like mute on Twitter. Not necessarily blocking them, but don't want to see their things either.

If someone is muted, for the user, a placeholder would appear like *<message hidden>* that would be individually shown from context menu.

**Comment by stek29** [comment]
#3772 and more
