### ISSUE TITLE
[Bug / Feature request] Alt+Shift+Click on 'Change Language' doesn't work, add button 'Load Localization'

### ISSUE THREAD

**Issue by ezdev128** [telegramdesktop/tdesktop#544]
Hello,
Because of cannot apply russian localization on LMDE (Linux Mint Debian Edition) I propose to add button 'Load  Localization' with path to ru.strings (for example) instead of doing some magic two-three-button hacks. Just keep it simple.

**Comment by auchri** [comment]
I don't think that the normal users want to see the button. Alt+Shift+Click works for me btw.

**Comment by ezdev128** [comment]
@auchri I bet you do not change the language layout using Alt+Shift.
What to do who has this? Why it is works on Windows with the same layout?
What OS / Environment at your PC? I'm sure Unity, right?

**Comment by auchri** [comment]
Im using Windows and it works fine

**Comment by ezdev128** [comment]
@auchri Sure thing. It works on Windows. But doesn't on Linux.

**Comment by Brawl345** [comment]
It works for me on Ubuntu 14.04

**Comment by ezdev128** [comment]
@Brawl345 yes, someone has reported about this works in latest Ubuntu with unity. But it is doesn't works on Linux Mint, for example.

**Comment by malishev** [comment]
Hotkeys don't work on Linux Mint 17 Cinnamon

**Comment by telegramdesktop** [comment]
From version 0.8.50.dev and after you can type "loadlang" in Settings instead of clicking with Alt+Shift.
