### ISSUE TITLE
[Linux] Scrolling not working after sleep

### ISSUE THREAD

**Issue by igormuba** [telegramdesktop/tdesktop#5440]
### Steps to reproduce
1. Open Telegram Desktop on Linux, scroll, it works
2.  Suspend the system, then wake it up
3.  Scroll stops working on chat list and inside the chats, very annopying

### Expected behaviour
Scroll should continue working....

### Actual behaviour
Scroll stops working only on the telegram desktop app, everywhere else on the system it works perfect, except telegram

### Configuration
**Operating system:**
Elementary OS 5 Juno
Alienware 18
Telegram Desktop app

**Version of Telegram Desktop:**
1.2.17

**Used theme**:
default

**Comment by stek29** [comment]
#3859
