### ISSUE TITLE
Not working properly with a 3rd party app

### ISSUE THREAD

**Issue by YaSoC** [telegramdesktop/tdesktop#5441]
### Expected behaviour
I am using an old application, called Layoutfix. Its simple analog to PuntoSwitcher.
Once you wrote a text in wrong layout, you just select it and then press (CTRL)+(Backspace)
Then text reverts to the next layout. SO, for example you write "руддщ" then it comes to "hello"

### Actual behaviour
Actual behavior with newest version of Telegram (just upgraded to 1.4.8 beta) - (CTRL)+(Bacspace) does nothing.

### Configuration
**Operating system:**
Win 10 x64
**Version of Telegram Desktop:**
1.4.8 beta
**Used theme**:
Dark

**Comment by YaSoC** [comment]
The Layoutfix app itself still works normally with all the other applications.

**Comment by john-preston** [comment]
@YaSoC I'm not sure it works normally with other Qt applications. I use Qt library input fields (they're not native Window input fields), so perhaps it doesn't support them.

**Comment by YaSoC** [comment]
@john-preston  , thanks for fast answer.
I just downgraded to 1.4.0 and it works fine as usual.

Actually, its been working for a long time already with no issues. Just this 1.4.8 beta upgrade produced the issue.

**Comment by john-preston** [comment]
@YaSoC Please check the versions from https://github.com/telegramdesktop/tdesktop/releases page and find out which exactly version stops working with it? Trying "Windows: Portable" versions, for example.

**Comment by YaSoC** [comment]
@john-preston exactly version 1.4.8 stops working with it.

1.4.7 works normally.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by YaSoC** [comment]
> this bug is still valid?

No. It's not valid anymore. 
It's been fixed in next release, more than a year ago
