### ISSUE TITLE
"Count unread messages" is not intuitive

### ISSUE THREAD

**Issue by EricKotato** [telegramdesktop/tdesktop#5442]
Option "Count unread messages" is not intuitive. I understand that function name is consistent with other apps, but on iOS and macOS there is a short description that explains the option. So it would be great if expanatory description would be added.

**Comment by RememberTheAir** [comment]
I still don't understand what it does, can someone explain?

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by RememberTheAir** [comment]
Yes

**Comment by RememberTheAir** [comment]
Still relevant

**Comment by RememberTheAir** [comment]
Still relevant

**Comment by RememberTheAir** [comment]
Still relevant

**Comment by RememberTheAir** [comment]
Still relevant on 3.7

**Comment by RememberTheAir** [comment]
Still relevant on 4.2.4

**Comment by RememberTheAir** [comment]
unstale

**Comment by RememberTheAir** [comment]
unstale

**Comment by RememberTheAir** [comment]
still weird to read

**Comment by RememberTheAir** [comment]
oh I'm late
