### ISSUE TITLE
Telegram 1.4.8 Icon Missing in Gnome (Ubuntu 18.10)

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#5444]
### Steps to reproduce
1. Download Telegram 1.4.8
2. Run the Telegram binary in it (This fixes the fontconfig issue I was having before)
3. The icon does not show when I add Telegram as a favorite option to the sidebar as seen in this image

https://imgur.com/a/n3Pl21m

### Expected behaviour
Icon should show there like previous versions

### Actual behaviour
Its simply an empty placeholder. Also when Telegram is closed and I try to open it through the empty icon, it never opens, I have to manually go to the Telegram folder again and run the Telegram binary from there. Before, in Ubuntu 18.04 it was working beautifully.

### Configuration
**Operating system:**
Ubuntu 18.10

**Version of Telegram Desktop:**
1.4.8

**Used theme**:
Night Theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by luisalvarado** [comment]
OMG @Aokromes Sorry for the super late response. No, everything is working correctly now:

![image](https://user-images.githubusercontent.com/29236/74865421-b4725880-5316-11ea-803e-9e577f713b3b.png)

**Comment by alex-bender** [comment]
@Aokromes but now It's valid for me.

**Comment by alex-bender** [comment]
Ubuntu 18.10
Telegram 1.9.14
Recently I've installed kde plasma, but I'm not sure that this is the cause.
How can I troubleshoot?
The binary is in `/usr/bin/Telegram`.
> Also when Telegram is closed and I try to open it through the empty icon, it never opens

I have the same behavior.
```
$ locate telegramdesktop.desktop
/home/user/.local/share/applications/telegramdesktop.desktop
/var/lib/snapd/desktop/applications/telegram-desktop_telegramdesktop.desktop
```
I've removed this `telegramdesktop.desktop` from `.local` but that didn't work.
How can I proceed?
Thanks
