### ISSUE TITLE
facebook link preview problem

### ISSUE THREAD

**Issue by serhii-horobets** [telegramdesktop/tdesktop#5445]
For example link https://www.facebook.com/photo.php?fbid=1774790229316849&set=a.186833604779194&type=3&theater

telegram windows app:
![default](https://user-images.githubusercontent.com/39026314/49525221-f354f380-f8b5-11e8-9fa4-9295b9b39609.png)
original:
![111](https://user-images.githubusercontent.com/39026314/49525236-fa7c0180-f8b5-11e8-84ad-36f8cbc2f199.png)

This problem also exists at android app, so **most likely the problem is on API-side**

**Comment by stek29** [comment]
Try to contact https://t.me/WebPageBot.
Probably that user has changed his name, but the preview was generated before.

**Comment by serhii-horobets** [comment]
The preview shows the name of the marked people - problem at API
![default](https://user-images.githubusercontent.com/39026314/49578806-3c0eba00-f953-11e8-9add-90b443ab43e2.png)

**Comment by serhii-horobets** [comment]
for example other link https://www.facebook.com/permalink.php?story_fbid=1786989984763540&id=100003576664760
