### ISSUE TITLE
Can't recieve item from clipboard manager (PRIMARY / CLIPBOARD)

### ISSUE THREAD

**Issue by azzamsa** [telegramdesktop/tdesktop#5446]
I use [clipboard manager](https://github.com/erebe/greenclip) all the time. Others app I use can receive item chosen from clipboard manager. e.g emacs, libreofffice, urxvt, but not telegram desktop.  If I want to copy an item from my clipboard manager history, I can't paste it directly to telegram desktop. But I need to paste it to emacs, copy it, then paste it again to telegram desktop. this step is painful.

### Steps to reproduce
1. select and copy "foo" from article
2. select and copy "bar" from article
3. browse old history "foo" with clipboard manager, select it
4. paste it to telegram desktop

### Expected behaviour
Telegram should receive "foo"

### Actual behaviour
Nothing

### Configuration
**Operating system:** Debian 9

**Version of Telegram Desktop:** v.1.4.3

**Used theme**: Default

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by azzamsa** [comment]
I don't check each release of the Telegram Desktop since v.1.4.3.

The current tests:
- Telegram Desktop 1.8.15 & Greenclip 3.1 -> **solved**
- Telegram Desktop 1.8.15 & Greenclip 2.1 -> unsolved
- Telegram Desktop 1.8.1 & Greenclip 2.1 -> unsolved

Now I am using Telegram Desktop 1.8.15 & Greenclip 3.1. So this issue is no longer valid. I don't have any idea which side cause/solve the problem since I don't test each release of them.

Thank you.
