### ISSUE TITLE
[Feature Request] Hide Join and Left messages

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#5449]
Hello.

Please add on option in Telegram settings for hide "join" and "left" messages into groups.

**Comment by Lonami** [comment]
You can do this with a bot.

**Comment by stek29** [comment]
@neesti it'd be better to remove them for everyone in group instead of hiding, and as @Lonami said, you can do that with a bot.

**Comment by neesti** [comment]
But I can only delete them or use from a bot if I become the group admin.

**Comment by neesti** [comment]
And if I'm not a group admin, I can not remove them, therefor I prefer there is an option for hide these messages only for me or only for who need to this option. 

Sorry for my bad English.
