### ISSUE TITLE
Do not trim spaces between words

### ISSUE THREAD

**Issue by ManuelSchneid3r** [telegramdesktop/tdesktop#545]
tdesktop does not allow me to shout

    S H U T   T H E   F U C K   U P

gets 

    S H U T T H E F U C K U P

In emotional situations this has a ridiculous impact on your opinion of tdesktop. (And on my keyboard)

(Note: not even giuthub markdown inline code does :angry: :angry: :angry: )

PS: A simple solution would be to just trim left and right.

**Comment by ppparadox** [comment]
+1

**Comment by andrianov78** [comment]
Do not trim left and right! As shown in #547 python code is sensible for indentation, so trimming invalidates the code.

**Comment by auchri** [comment]
Duplicate #522
