### ISSUE TITLE
App icon for Ubuntu 18.10 and later

### ISSUE THREAD

**Issue by eaglersdeveloper** [telegramdesktop/tdesktop#5451]
Ubuntu 18.10 and later use a new style in accordance with [Yaru Design](https://github.com/ubuntu/yaru).
All application icons use the same shape.

![2018-12-08 15-26-05](https://user-images.githubusercontent.com/40228953/49685516-f6422500-fafd-11e8-8855-af986ca1b81b.png)

Developers of third-party applications can also create an icon specifically for Ubuntu.
Icons must be in /usr/share/icons/Yaru/HxW and HxW@2x folders.

![default](https://user-images.githubusercontent.com/40228953/49685601-305ff680-faff-11e8-8cb8-8ac5a822dd5d.png)

Design guidelines are located on https://snwh.org/suru/guidelines.
I can help with icons.

![telegram](https://user-images.githubusercontent.com/40228953/49685633-2d193a80-fb00-11e8-9219-05d0b49efe58.png)

**Comment by luisalvarado** [comment]
Confirm this is an issue. Affects at least from version 1.4.6 since that was the lowest one I tried before moving to Ubuntu 18.10

It simply looks like an empty placeholder in the dash of Ubuntu and if you try to click on it, nothing happens.

See image here https://imgur.com/a/dWvwZsk

**Comment by eaglersdeveloper** [comment]
Telegram icon doesn't combine with other icons in Ubuntu.
This issue isn't very important.
I create icons for Ubuntu and want to increase the number of applications with Ubuntu icon.

**Comment by ilya-fedin** [comment]
But themed icons should be installed by icon pack and not by app. I.e. you should make a PR for Yaru repo :)
