### ISSUE TITLE
Opportunity to change font in tray icon popup menu manually (Gentoo, XFCE4, Awesome WM)

### ISSUE THREAD

**Issue by buriedaliveIX** [telegramdesktop/tdesktop#5452]
### Steps to reproduce
1.  Launch Telegram as regular
2.  Right mouse button click on Telegram tray icon
3.  Look at the some ugly font

### Expected behaviour
If there was an opportunity to change that font, but not yet

### Actual behaviour
I see very ugly font
I launched Telegram as FC_DEBUG=5 ./Telegram > ~/tg_output.log
As far as I have been able to find out this 'ugly font for me' called Becker
piece of output file tg_output.log

Substitute Edit hinting Assign true

Append list before  [marker]
Append list after  True(w)
FcConfigSubstitute editPattern has 27 elts (size 32)
	family: "Becker"(s)
	style: "Medium"(w)
	slant: 0(i)(s)
	weight: 100(i)(s)
	width: 100(i)(s)
	pixelsize: 12(f)(s)
	foundry: "unknown"(w)
	antialias: True(w)
	hintstyle: 3(i)(s)
	hinting: True(w)
	verticallayout: False(s)
	autohint: False(s)
	globaladvance: True(s)
	**file: "/usr/share/fonts/freefonts/becker.pfb"(s)**
	index: 0(i)(s)
	outline: True(w)
	scalable: True(w)

$ ls /usr/share/fonts/freefonts/
agateb.pfb    brushstr.pfb  elann___.pfb   ftpstrps.pfb  muriel.pfb    shalosti.pfb
agatei.pfb    calig___.pfb  encodings.dir  garmndmi.pfb  oldcnd_r.pfb  shf_____.pfb
agate.pfb     capri.pfb     engravrl.pfb   genoaita.pfb  oldext_r.pfb  slogan.pfb
ans.pfb       carrickc.pfb  erasblkb.pfb   genoarom.pfb  old_town.pfb  spooky.pfb
baskvlb.pfb   cheq.pfb      erasb.pfb      gocmase_.pfb  oldtwn_r.pfb  tekton.pfb
baskvli.pfb   classhvy.pfb  eraselt.pfb    gocmseq_.pfb  oswaldbl.pfb  tempofon.pfb
baskvl.pfb    cooprblk.pfb  erasltra.pfb   goudyob.pfb   parkave.pfb   tempoita.pfb
becker.pfb    coronet.pfb   erasmed.pfb    goudyoi.pfb   postanti.pfb  tribeca.pfb
blippo.pfb    crf_____.pfb  eras.pfb       goudyo.pfb    rechtman.pfb  victoria.pfb
bodonib.pfb   crillee.pfb   florence.pfb   igloolas.pfb  roosthea.pfb  windsord.pfb
bodonii.pfb   cunei.pfb     fonts.dir      linotext.pfb  rudelsbe.pfb  zalescap.pfb
bodoni.pfb    dabkc___.pfb  fonts.scale    luxembrg.pfb  salter.pfb
boecklin.pfb  dos_____.pfb  frquadb.pfb    manzanit.pfb  shaloold.pfb
brahc___.pfb  dragonwi.pfb  frquad.pfb     mazama.pfb    shaloscr.pfb

I see Becker font. How to change him to any other pleasant for my eyes?

### Configuration
Linux srv02 4.14.83-gentoo SMP PREEMPT Sat Dec 1 13:53:40 +07 2018 x86_64
DE: XFCE4 Version 4.12, distributed by Gentoo
WM: awesome v4.3 (Too long)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.0

**Version of Telegram Desktop:**
Telegram-Desktop 1.4.8 beta.
After update Telegram-Desktop 1.5 too.
After update Telegram-Desktop 1.5.2 too.
After update Telegram-Desktop 1.5.5 beta too.
After update Telegram-Desktop 1.5.9 too.
After update Telegram-Desktop 1.6.1 too.

**Used theme**:
Any of Blue, Classic, Midnight or Matrix theme.

XFCE4:
![tg_screen_xfce4](https://user-images.githubusercontent.com/33695630/49757046-09b3e280-fcee-11e8-882e-644aa9f23400.png)

Awesome WM:
![tg_screen_awesome_wm](https://user-images.githubusercontent.com/33695630/52122472-b6a73d80-2655-11e9-96da-2f4541a807e1.png)

**Comment by heroin-moose** [comment]
Bump? This is really annoying.

**Comment by buriedaliveIX** [comment]
Up.

**Comment by buriedaliveIX** [comment]
Solved for me in 1.9.10 beta, tray fonts looks good now.
