### ISSUE TITLE
Duplicated "Edit profile" option

### ISSUE THREAD

**Issue by OctoNezd** [telegramdesktop/tdesktop#5454]
### Steps to reproduce
1. Open Settings
2. Open 3-dot menu

### Expected behaviour
Only logout option should appear

### Actual behaviour
"Log out" and "Edit profile" options appear. "Edit profile" in menu leads to exact same menu as the "Edit profile" in settings. I suppose having duplicates of options is useless and only adds clutter to UI. Feel free to close this issue if you think it's not a huge UI problem :shrug:

![image](https://user-images.githubusercontent.com/15308404/49690267-0fb79100-fb3f-11e8-810a-c8c06be610d0.png)

### Configuration
**Operating system:** Windows 10 1803 Home

**Version of Telegram Desktop:** 1.4.8 Beta

**Used theme**: Midnight

**Comment by Aokromes** [comment]
maybe remove 3 dots and put logout under language text?
