### ISSUE TITLE
Url tooltip on inline url button hover

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#5457]
### Steps to reproduce
1. position your mouse on an inline url button

### Expected behaviour
A tooltip appears showing you the url, in the same way it is shown when you hover on a text link

### Actual behaviour
No tooltip is shown, you have to click on the button or, in case of t.me/telegra.ph urls, you have to open the url and copy the message url to see it (or right click and copy the button url)

### Configuration

**Version of Telegram Desktop:** 1.4.8

**Comment by MasterGroosha** [comment]
By the way, you can right-click on URL button -> "Copy link". Very unintuitive, though.

**Comment by MasterGroosha** [comment]
I think this is a nice feature which is not implemented yet
