### ISSUE TITLE
v1.5 Ugly Persian Font

### ISSUE THREAD

**Issue by DarkSuniuM** [telegramdesktop/tdesktop#5459]
### Steps to reproduce
0. Update to v1.5
1. Open Telegram Desktop
2. Read some Persian text

### Expected behaviour
The font should not look this ugly

### Actual behaviour
![Ugly Persian Font](http://s6.uplod.ir/i/00942/m7ikesblzbc1.jpg)

### Configuration
**Operating system: Archlinux**

**Version of Telegram Desktop: 1.5**

**Used theme: Midnight**

<details><summary><b>Logs</b>:</summary>
telegram-desktop -- %u =>

```
QApplication: invalid style override passed, ignoring it.

(telegram-desktop:3550): Gdk-CRITICAL **: 03:10:32.519: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
  OpenType support missing for "Open Sans Semibold", script 11
  OpenType support missing for "Open Sans", script 11
  OpenType support missing for "Open Sans Semibold", script 14
  OpenType support missing for "Open Sans", script 14
```

</details>

**Comment by Aokromes** [comment]
#5172

**Comment by Mahdyar** [comment]
I have the same problem .

**Comment by john-preston** [comment]
I'm afraid you'll need to try the version from snapcraft: https://snapcraft.io/telegram-desktop

It should work in systems with the new fontconfig version.

**Comment by stek29** [comment]
#5172

**Comment by DarkSuniuM** [comment]
> I'm afraid you'll need to try the version from snapcraft: https://snapcraft.io/telegram-desktop
> 
> It should work in systems with the new fontconfig version.

`./Telegram: error while loading shared libraries: libicuuc.so.55: cannot open shared object file: No such file or directory
`

Can't use snapcraft version, seems like it uses `icu 55` while on Arch systems it's upgraded to v63

```
alireza@Y5070:~ » pacman -Q icu 
icu 63.1-2
```

**Comment by DarkSuniuM** [comment]
> #5172

It's not like that issue, It's not a duplicate, I did have that problem, I fixed that using a fontconfig, but now, even the fontconfig doesn't fix this issue..

**Comment by DarkSuniuM** [comment]
Just updated to v1.5.0-2, the problem is fixed.
