### ISSUE TITLE
GIFs and Telescope messages are not categorized

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#5464]
### Steps to reproduce
1. Open a group with GIFs and/or Telescope messages posted.
2. Open group info.
3. There are the following lists: photos, videos, files, audio files, shared links, voice messages.

### Expected behaviour
GIFs and Telescope messages should be listed somewhere: either in photos/videos, or, better, in dedicated lists.

### Actual behaviour
They don't appear anywhere.

### Configuration
**Operating system:** Debian GNU/Linux 10

**Version of Telegram Desktop:** 1.4

**Used theme**: Classic

**Comment by SmartManoj** [comment]
Also contacts

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by RememberTheAir** [comment]
Kinda. The GIFs part is even more relevant now because the mobile apps have a dedicated tab in the shared medias screen. Round video messages should have their own issue imo

**Comment by RememberTheAir** [comment]
GIFs have now their won item. I think video messages should have their own issue cause they're merged with voice message on every platform - so if GIFs not having their own shared medias item was inconsistent with other apps, video messages are not

**Comment by RememberTheAir** [comment]
Still relevant
