### ISSUE TITLE
No portable for v1.5.1?

### ISSUE THREAD

**Issue by MrX-at-GitHub** [telegramdesktop/tdesktop#5465]
As the title says.

**Comment by MrX-at-GitHub** [comment]
Refreshed release page at this very moment and now it's up.

Thanks.

**Comment by john-preston** [comment]
@MrX-at-GitHub It should be available now.

**Comment by john-preston** [comment]
@MrX-at-GitHub I forget to change versions there 🙈

**Comment by MrX-at-GitHub** [comment]
Oh ok, thanks.
