### ISSUE TITLE
Notification sound off after update Telegram

### ISSUE THREAD

**Issue by cm136** [telegramdesktop/tdesktop#5466]
### Steps to reproduce
1. Use Telegram
2. Wait and install new version (click Update Telegram)
3. After updating Telegram there is no sound when I receive messages. It is necessary to close and open the Telegram so that the sound is turned on.

### Expected behaviour
The sound of notifications should always be

### Actual behaviour
After updating Telegram there is no sound when I receive messages.

### Configuration
**Operating system:**
Windows 10 and KDE Neon Linux
**Version of Telegram Desktop:**
Different versions, but now 1.5
**Used theme**:
Midnight

**Comment by ilya-fedin** [comment]
Is this still valid?

**Comment by Aokromes** [comment]
> 1 month without answer, if this bug is still valid open a new ticket.
