### ISSUE TITLE
Font Khmer language too small display and some typing not correctly

### ISSUE THREAD

**Issue by meashsim** [telegramdesktop/tdesktop#5468]
### Steps to reproduce
1. In chat when typing Khmer Unicode [UTF8]
2. Display too small font ( I attached pic1 )
3. Some character produce space ( I attached pic 2 )
![khmer-font-bug-pict1](https://user-images.githubusercontent.com/12493849/49851884-0ebf8180-fe15-11e8-906d-6961eef6c6b3.JPG)
![khmer-font-bug-pict2](https://user-images.githubusercontent.com/12493849/49851885-0f581800-fe15-11e8-8f78-04cf6636cf36.JPG)

### Expected behaviour
Should display font as normal size readable

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by meashsim** [comment]
No anyone fix?

**Comment by Aokromes** [comment]
#5172 generic bug.

**Comment by ilya-fedin** [comment]
Is this still valid?
