### ISSUE TITLE
Indentation spaces are swallowed in python code

### ISSUE THREAD

**Issue by andrianov78** [telegramdesktop/tdesktop#547]
Any python code is sensible to indentation spaces. Multiple spaces are converted to a single one even on sender side.

**Comment by brandonmoser** [comment]
This is true with any code, like YML files, etc. Pasting text should keep all whitespace and characters.

**Comment by peterfarrell** [comment]
This is affecting me -- makes using app hard for team sharing.  Workaround is to share a file which isn't convenient for short .  Affects any white-space dependent code like YAML and Python.

**Comment by ezdev128** [comment]
I'm agree with that. Odd issue... That's why I prefer to pastebin it and send only a link.

**Comment by auchri** [comment]
Duplicate #545
