### ISSUE TITLE
Буква ё не вводится в текст.

### ISSUE THREAD

**Issue by AndreiZhitkov** [telegramdesktop/tdesktop#5471]
### Steps to reproduce
1. Начать печатать сообщение
2. Нажать и держать клавишу буквы «е».

### Expected behaviour
Tell us what should happen
3. В этот момент должна появится опция на введение буквы «ё»

### Actual behaviour
Tell us what happens instead
Вместо появления альтернативного знака, буква «е» продолжает вводиться повторно.
### Configuration
**Operating system:**
macOS 10.14.2
**Version of Telegram Desktop:**
1.4.3
**Used theme**:
dark
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RadRussianRus** [comment]
Latest stable is 1.5.1, can you test it on this version?

**Comment by AndreiZhitkov** [comment]
It is 1.5.1.
I don't know why the finder was still showing 1.4.3. Disregard that.
Also the same macOS technique of typing the alternative or accented characters doesn't work for Latin alphabets, so the problem is not limited to "ё".

**Comment by john-preston** [comment]
@AndreiZhitkov Yes, it is not supported in Qt apps :( at least with Qt version 5.6.2.
