### ISSUE TITLE
Audio disappears on Telegram 1.5.1 start

### ISSUE THREAD

**Issue by oddtwelve** [telegramdesktop/tdesktop#5472]
1. Start Telegram 1.5.1 while playing audio
2. 
3. 

### Expected behaviour

Sound should be present
### Actual behaviour

Sound disappears from Windows. From all the sources. As if the audio driver was "hijacked" by Telegram. Only Windows restart helps.

**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.5.1
**Used theme**:
Default

**Comment by MasterGroosha** [comment]
Could you please check with the latest TDesktop? Using AIMP and starting TDesktop 1.8.4 doesn't "break" the sound on Windows 10.

**Comment by Aokromes** [comment]
i use audio a lot and never had my audio hijacked.

**Comment by Aokromes** [comment]
no answer after months, closing.
