### ISSUE TITLE
[idea] audio bookmarks or time codes 

### ISSUE THREAD

**Issue by warshell** [telegramdesktop/tdesktop#5473]
Would be nice to see a timecoding or a audio bookmarks to find quickly a pages , chapters, songs in a long audio like on youtube or like bookmarks

**Comment by MasterGroosha** [comment]
Actually, Telegram for Android and iOS support timecodes for video since August'19.
https://telegram.org/blog/silent-messages-slow-mode#timestamps-and-improved-scrubbing
