### ISSUE TITLE
Privacy Issue

### ISSUE THREAD

**Issue by tntc4** [telegramdesktop/tdesktop#5475]
In the **Otions** > **Privacy and security** > **Group invites settings** the option **Everybody** is set by default.
Please set **My constacts** by default because yesterday I was invited in the spammy group.
When I read the chat of this group I found many peoples are angry because they are invited by unknown user.
This is serious security issue because everybody that know your phone number can invite you without your consent.
![screenshot_1](https://user-images.githubusercontent.com/3246834/49936900-d5067d80-fedd-11e8-9b6e-c418d49836f1.png)

**Comment by john-preston** [comment]
@tntc4 Those default settings are managed on the server, so this has nothing to do with Telegram Desktop, sorry.
