### ISSUE TITLE
Custom cloud translations show as not 100% completed

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#5477]
Because some phrases are critical, even when translation is fully complete, it shows as 99% complete. Android client, on other hand, shows them as 100%.

**Comment by john-preston** [comment]
@RadRussianRus What do you mean critical?

**Comment by RadRussianRus** [comment]
There are three of these in Desktop.

* `lng_settings_language`
* `lng_language_switch_about_official`
* `lng_language_switch_about_unofficial`

For some reason `lng_language_switch_link` not counts as critical, even though it's used in `lng_language_switch_about_`.

**Comment by AlessandroMocellin** [comment]
We have the same problem with the localization in the Venetian language (VEC), here: t.me/setlanguage/lenguaveneta

Was this issue of those "critical phrases" resolved? If so, please contact us!
Thanks!
@Academia_Bona_Creansa

**Comment by Aokromes** [comment]
this is "3rd party" bug no? i mean, it doesn't belongs to telegram desktop instead cloud translations team.

**Comment by RadRussianRus** [comment]
> Android client, on other hand, shows them as 100%.

Third party, of course, has problems. But current TDesktop behavior is inconsistent with mobile apps.
