### ISSUE TITLE
Font issues (e.g. Egyptian hieroglyphs)

### ISSUE THREAD

**Issue by stormrise** [telegramdesktop/tdesktop#5479]
### Steps to reproduce
1. I fond telegram on my mac have some font display issue, but not have that on my android
2. so I install full pack of Noto fonts, and the other place like chrome will actual show that font but not telegram
3. as far as now, only tofu shows in some username use Egyptian hieroglyphs font or other special font.
4. and I heard some friends says its ok in windows 10, so I guess its mac version problem.

### Expected behaviour
should able to show fonts

### Actual behaviour
only show some tofu

### Configuration
**Operating system:**
macos mojave 10.14.1

**Version of Telegram Desktop:**
1.5.2

**Used theme**:
original with dark mode on

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Blealtan** [comment]
#90
