### ISSUE TITLE
No option for native notifications in 1.4.7 (BETA)

### ISSUE THREAD

**Issue by Schyken** [telegramdesktop/tdesktop#5480]
### Steps to reproduce
1. Install Telegram Desktop 1.4.7 Beta
2. Navigate the app's settings
3. Search for native notifications

### Expected behaviour
A toggle to use native notifications in Linux should be present in the Notifications section of Telegram Desktop settings

### Actual behaviour
There appears to be no toggle for native notifications in the Notifications settings or any other part of the app's settings. 
### Configuration
**openSUSE Tumbleweed:**

**Version of Telegram Desktop:**
1.4.7 BETA
**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
They are there at least on Debian 10, on Telegram Desktop 1.9.0 can you check if it's fixed for you?

**Comment by Aokromes** [comment]
no answer after months, closing.
