### ISSUE TITLE
Images on Channels and Group showing as not downloaded

### ISSUE THREAD

**Issue by Kurdaitcha** [telegramdesktop/tdesktop#5483]
### Steps to reproduce
1. Post Images to a channel.
2. Scroll up to the first set of images sent.

### Expected behaviour
Image's should be downloaded automatically and show them without the blur and download button.

### Actual behaviour
Images are shown as blurred with a download button, when the download button is pressed it downloads the image instantly. This only started to happen when I downloaded the latest update for Telegram Desktop.

### Configuration
**Operating system:** Windows 7 Home Premium, Service Pack 1, 64bit Operating System.

**Version of Telegram Desktop:** Version 1.5.2

**Comment by Mithgol** [comment]
Still happens in Telegram Desktop 1.9.1 beta.

For example, at https://t.me/uxfromhellchat/14485 files as small as 9 kB are not autodownloaded.

![(screenshot)](https://ipfs.io/ipfs/QmaxYk15n2B58Y2EcgPiYoVrkDRemdKuYHcygUY5UrqiJh/screenshotSmallFiles.png)

**Comment by RememberTheAir** [comment]
@Mithgol these are images sent as file, which for the app are effectively files - and they have their own auto-download settings. From settings -> advanced you can configure the max size of the files/videos/pics/audios tdesktop should auto-download. They are common among these media types though

**Comment by Mithgol** [comment]
@RememberTheAir I believe I have that limit set to “up to 200 MB” for files in groups.

That's why I see it as an ussue when files as small as 9 kB are not autodownloaded.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
no answer after more than 1 month, closing, if this bug is still valid open a new ticket using updated telegram version.
