### ISSUE TITLE
Telegram.sln

### ISSUE THREAD

**Issue by komailghasemi** [telegramdesktop/tdesktop#5484]
hello
i did everything step by step 
but i didnt find Telegram.sln

i searched in issues and i found this link https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-msvc.md#setup-gypninja-and-generate-vs-solution

but its 404 !!!

pls help me ❤❤❤

**Comment by 23rd** [comment]
https://github.com/telegramdesktop/tdesktop/blob/master/docs/building-msvc.md

**Comment by komailghasemi** [comment]
> https://github.com/telegramdesktop/tdesktop/blob/master/docs/building-msvc.md

:| i said did it step by step

**Comment by Painkiller1991** [comment]
@komailghasemi how fix this issue?
