### ISSUE TITLE
Moving the window using Windows key and arrows not working

### ISSUE THREAD

**Issue by Cyberuben** [telegramdesktop/tdesktop#5485]
### Steps to reproduce
1. Connect a 2nd display after booting
2. 2nd display should be set to primary display (located on the right?)
3. Place Telegram on the left half of one of the displays (drag to left or right side, or <kbd>Windows</kbd> + <kbd>🡐</kbd> or <kbd>Windows</kbd> + <kbd>🡒</kbd>)
4. Try to move the window to the right using <kbd>Windows</kbd> + <kbd>🡒</kbd>

### Expected behaviour
The window should move to the half right of the current half, and wrap around to the most left if there is nothing to the right

### Actual behaviour
The window refuses to move to the right. When on the right side of the left display, it moves to the left side of the right display as it should. If it's on the right side of the right display, it moves to the left side of the left display, as it should, but it doesn't move from the left side of either display to the right side of the same display.

I've made a video to illustrate the issue. On the right, you can see my keystrokes (although they might be a bit hard to see): https://0x.ms/J5dE5ZmJk2x

### Configuration
**Operating system:** Windows 10 build 1803, but it has been happening for years

**Version of Telegram Desktop:** `1.5.2` but has been happening for years

**Used theme**: Dark

**Comment by Aokromes** [comment]
works for me on 1.9.8 and windows 10 20h1.
