### ISSUE TITLE
Wrong order of messages when send offline

### ISSUE THREAD

**Issue by skywinder** [telegramdesktop/tdesktop#5486]
### Steps to reproduce
1. Send 1 message from user 1 (online)
2. Send 2nd message from user 2 (offline)
3. Send 3rd message from user 1 (online)
4. Go online for user 2 to send the message

### Expected behavior
Tell us what should happen
Messages should appear in order as they sent.

### Actual behavior
Messages appear in unordered by time sequence (see screenshot)

### Configuration
**Operating system:**
OSX

**Version of Telegram Desktop:**
1.4.3
![image](https://user-images.githubusercontent.com/3356474/50051881-86fbaf00-0155-11e9-838e-c69c48708f75.png)

**Comment by Aokromes** [comment]
#5352 ?
