### ISSUE TITLE
Unread message count do not disapser in Ubuntu 18.04

### ISSUE THREAD

**Issue by pro2s** [telegramdesktop/tdesktop#5487]
### Steps to reproduce
1. Disable Settings, Notification, Count unread messages (when enabled the bug is also present)
2. Get message
3. Read all messages 

### Expected behaviour
There are no any badges on the telegram appindicator icon in the system tray.

### Actual behaviour
There is the gray badge with a message cout on the telegram appindicator icon in the system tray.

### Configuration
**Operating system:** Ubuntu 18.04.1 LTS

**Version of Telegram Desktop:** 1.5.2 installed via the snap

**Used theme**: no

**Comment by TheFire** [comment]
I am seeing the same issue on 2 different ubuntu 18.04 installs using regular Gnome session and shell. Telegram versions 1.5.4 and 1.5.5 beta

**Comment by stek29** [comment]
#5525
