### ISSUE TITLE
Error when start

### ISSUE THREAD

**Issue by art83nik** [telegramdesktop/tdesktop#5488]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>
![telegr err](https://user-images.githubusercontent.com/45947454/50104976-770aca80-023c-11e9-9f81-ea440ab8c8b0.png)

**Comment by stek29** [comment]
tell us more about your configuration. what is that disk?
