### ISSUE TITLE
Problem with deep linking

### ISSUE THREAD

**Issue by jloskin** [telegramdesktop/tdesktop#5489]
### Steps to reproduce
1. Open link from browser. For example tg://resolve?domain={name}

### Expected behaviour
Open chat with user

### Actual behaviour
App open without action

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.5.2

**Comment by chebotarevmichael** [comment]
Yes, I and one of my friends has got same issue.

I have tried from Windows 10 + Telegram Desktop: 1.6.7
and windophone8.1 + Telegram for winphone 3.4.1.0 WP8.1

I try use tor or chrome, it`s doesn`t work. But some time ago it works.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by jloskin** [comment]
Now i`am not windows user, can`t check this moment.
