### ISSUE TITLE
Question: restore account

### ISSUE THREAD

**Issue by alihan784** [telegramdesktop/tdesktop#5490]
Hello, a week ago my telegrams were updated and all account data was erased. I cannot restore access to it via SMS, because the SIM card was lost and was not registered in my name. I can provide the number to which the account was registered, the list of channels to which it was subscribed, the channels to which the message was last sent, the avatar and the name with the last name specified in the account. This is my business account and I cannot lose access to it. I really hope that you will meet me. Official support and volunteers have not responded for a week

**Comment by stek29** [comment]
Contact support, but most likely you'd have to restore access to the SIM.
