### ISSUE TITLE
Suggestions:

### ISSUE THREAD

**Issue by fabyRojas** [telegramdesktop/tdesktop#5493]
- Possibility to make video messages and take pictures from a desktop telegram.
- Voice messages separated from video messages in multimedia files
- Streaming and secret chat.
- Tabs (or even if they appear as a hidden secret as the work mode)
- Folders (as a way to store chat, groups or channels by category, according to each user), with tabs and chat anchors that option would be perfect

**Comment by stek29** [comment]
1 -> #781
2 -> #5464
3 -> #4330

**Comment by stek29** [comment]
Please open separate issue for each suggestion.
