### ISSUE TITLE
Telegram Desktop does not respect 'interface scale' display settings in Ubuntu 18.04

### ISSUE THREAD

**Issue by vdmit** [telegramdesktop/tdesktop#5495]
### Steps to reproduce
1. Set system display scale to 200% or greater
2. Run TD

### Expected behaviour
TD window scales proportionally, same as all other native windows

### Actual behaviour
TD window does not scales

### Configuration
**Operating system:**
Ubuntu Linux 18.04, running on laptop with FullHD screen plus external UHD monitor (4k resolution),
Gnome window system

**Version of Telegram Desktop:**
1.5.2
**Used theme**:
Default

<details>
In my configuration, I have 100% scale on laptop screen, and 200% on external monitor.
When I set 200% scale in TD internal settings, it looks too large on the laptop built-in screen, and vice versa.
</details>

**Comment by vskubriev** [comment]
I confirm the problem

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Comment by vdmit** [comment]
Just checked behavior on latest version.
I have dual monitor configuration, one of them have scale 2x and 4k resolution, and second one (laptop built-in) have FullHD and 1x scale.
I have Telegram window scaled approximately to half of the screen. When I switch to laptop screen, Telegram window fills all the screen. Seems that it tries to get same pixel dimensions as on large screen.
