### ISSUE TITLE
Duplicate russian letter in RDP or VNC session

### ISSUE THREAD

**Issue by newmrac** [telegramdesktop/tdesktop#5496]
### Steps to reproduce
1. Start Telegram Desktop on Windows computer
2. Connect to this computer by RDP or VNC from another Windows computer
3. Try to write messages fast in Telegram. For example I write fast "В Телеграмме десктопном залипают буквы, это не я безграмотный"

### Expected behaviour
Message should bу exactly as I enter on keyboard: "В Телеграмме десктопном залипают буквы, это не я безграмотный"
### Actual behaviour
Some letters replaced by copy of previous letter (word length not changing, but some letters replaced by doubling of previous):
"В Телеграмме дескттпном залипают буквв, этт не я безграмотный".
If write it faster on keyboard, all letters can be replaced by one first letter.
### Configuration
**Operating system:**
Windows 10 Pro x64 1809 English, Windows 10 Pro x64 1803 English
**Version of Telegram Desktop:**
1.5.2
**Used theme**:
Default
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by newmrac** [comment]
Yes. But I believe, that problem appears when keyboard switcher (Punto Switcher) is loaded. If not, problem absent. Looks like conflict with this software.

**Comment by Aokromes** [comment]
then it maybe 3rd party bug?
