### ISSUE TITLE
Unintuitive behavior of tweet preview with video

### ISSUE THREAD

**Issue by salnkv** [telegramdesktop/tdesktop#5499]
### Steps to reproduce
1. Take some link on tweet with video (e.g. https://twitter.com/Google/status/1075435660603867137)
2. Send a message with this link.
3. Look at tweet preview.

### Expected behaviour
Video preview should be with playback icon (like a youtube video preview).
When you click on video preview tweet must be opened in browser.

### Actual behaviour
Video preview has no playback icon.
When you click on video preview image it is opened like a photo. It confuses.

### Configuration
**Operating system**: Windows 10

**Version of Telegram Desktop**: 1.5.2

**Used theme**: default

**Comment by stek29** [comment]
#2942 #5371

**Comment by salnkv** [comment]
So what is official reason why it can't be done?

**Comment by stek29** [comment]
Go to issues I linked and you'll see "API issue" label: it's handled by server side.

**Comment by salnkv** [comment]
Telegram Desktop and Telegram for iOS and for macOS have different server side api? Because iOS and macOS versions display tweets with video properly

**Comment by stek29** [comment]
> Because iOS and macOS versions display tweets with video properly

Not really. They also do display YouTube videos, and so does Android app. But that's just client hardcoded to fetch and show video embed in a webview.

**Comment by blms** [comment]
> > Because iOS and macOS versions display tweets with video properly
> 
> Not really. They also do display YouTube videos, and so does Android app. But that's just client hardcoded to fetch and show video embed in a webview.

In that case, couldn't this be done on Windows as well? This is really more of a feature request, and please let me know if I should create a new issue for it. But it would be nice if a user on Windows could view videos in-client like so:

<img width="718" alt="Screen Shot 2020-02-06 at 8 15 08 PM" src="https://user-images.githubusercontent.com/7234006/73992538-7e4bd680-491d-11ea-8a75-07d3a6d2eedd.png">
