### ISSUE TITLE
Batchfile messaging in Windows

### ISSUE THREAD

**Issue by maex3000** [telegramdesktop/tdesktop#550]
Hello everybody,

after my Cygwin solution for sending messages using windows batchfiles doesn´t work anymore (https://github.com/vysheng/tg/issues/442), I´m wondering if there is another way to automatically sending messages via telegram. Is it possible to automate sending messages in windows?

Help would be greatly appreciated.

Regards
maex

**Comment by auchri** [comment]
I don't think this is related to Telegram Desktop
