### ISSUE TITLE
Linux: Tray Icon stuck showing 2 notifications

### ISSUE THREAD

**Issue by Talking-Animal** [telegramdesktop/tdesktop#5501]
### Steps to reproduce
1. Install package telegram-desktop
2. sign in and set up tray icon

### Expected behaviour
Telegram Desktop's tray icon should not show any notifications.

### Actual behaviour
Telegram Desktop's tray icon shows two notifications that cannot be removed unless the application has one or more real notifications to show, in which case it returns to normal until they are read.

### Configuration
Antergos KDE and XFCE

Telegram Desktop 1.5.2
Both light and dark themes used.

**Comment by Gimrigz** [comment]
I have the same issue, although for me it never clears. Stuck at one, will increment if I have actual notifications but will never go below one.

On Fedora 29/Gnome.

**Comment by sudoranger** [comment]
I'm having the same issue on Ubuntu 18.04 (GTK3 + Gnome Tweak + Dash to Panel). Why are we not getting any attention from the core developers?

**Comment by Sutarat66** [comment]
เมื่อ อ. 1 ม.ค. 2562 เวลา 20:37 sudoranger <notifications@github.com>
เขียนว่า:
