### ISSUE TITLE
unable to exit from inline mode

### ISSUE THREAD

**Issue by andrew-ld** [telegramdesktop/tdesktop#5503]
### Steps to reproduce
https://t.me/TelegramDesktopTalk/14806?embed=1

### Expected behaviour
after deleting the bot username from the textbox it should go back to turn off the "inline mode"

### Actual behaviour
it remains in the inline mode and it is no longer possible to send messages

### Configuration
**Version of Telegram Desktop:** 1.5.2

**Comment by mugavri** [comment]
It happens to me too, a very annoying bug
