### ISSUE TITLE
Korean IME Crash with Vote

### ISSUE THREAD

**Issue by HelloWorld017** [telegramdesktop/tdesktop#5506]
### Steps to reproduce
1. Create vote
2. Enter more than two characters in Korean IME
3. It crashes

### Expected behaviour
The korean text should be entered normally and should not crash.

### Actual behaviour
It crashes. Telegram is turned off.

### Configuration
**Operating system:** Windows 10 (1803)

**Version of Telegram Desktop:** 1.5.3

**Used theme**: Default theme (Midnight)

<b>Logs</b>: <a href="https://pastebin.com/QiQWriry">Here</a>

`[2018.12.23 10:26:03] Assertion Failed! "_eventNestingLevel > _loopNestingLevel" c:\projects\telegram\twin\telegram\sourcefiles\application.cpp:393`

**Comment by john-preston** [comment]
@HelloWorld017 Thank you for the report!

**Comment by tetsaicn** [comment]
Sogou Chinese Pinyin crash either
