### ISSUE TITLE
Unicodes v12 for Emoji´s :green_circle: and  :orange_circle: are not displayed

### ISSUE THREAD

**Issue by PPSid** [telegramdesktop/tdesktop#5513]
### Steps to reproduce
1.  pip3 install python-telegram-bot==11.1.0 emoji==0.5.1
2. Patch / add missing unicodes
--- site-packages/emoji/unicode_codes.py.orig        2018-12-24 06:46:51.838764190 +0000
+++ site-packages/emoji/unicode_codes.py        2018-12-21 04:37:26.148458958 +0000
@@ -912,6 +912,7 @@
     u':grapes:': u'\U0001F347',
     u':green_apple:': u'\U0001F34F',
     u':green_book:': u'\U0001F4D7',
+    u':green_circle:': u'\U0001F7E2',
     u':green_heart:': u'\U0001F49A',
     u':green_salad:': u'\U0001F957',
     u':grimacing_face:': u'\U0001F62C',
@@ -1611,6 +1612,7 @@
     u':open_mailbox_with_raised_flag:': u'\U0001F4EC',
     u':optical_disk:': u'\U0001F4BF',
     u':orange_book:': u'\U0001F4D9',
+    u':orange_circle:': u'\U0001F7E0',
     u':orange_heart:': u'\U0001F9E1',
     u':orthodox_cross:': u'\U00002626',
     u':outbox_tray:': u'\U0001F4E4',
@@ -3409,6 +3411,11 @@
     u':koala:': u'\U0001F428',
     u':label:': u'\U0001F3F7',
     u':beetle:': u'\U0001F41E',
+    u':large_orange_circle:': u'\U0001F7E0',
+    u':large_yellow_circle:': u'\U0001F7E1',
+    u':large_green_circle:': u'\U0001F7E2',
+    u':large_purple_circle:': u'\U0001F7E3',
+    u':large_brown_circle:': u'\U0001F7E4',
     u':large_blue_circle:': u'\U0001F535',
     u':large_blue_diamond:': u'\U0001F537',
     u':large_orange_diamond:': u'\U0001F536',
@@ -3937,6 +3944,7 @@
     u':gift:': u'\U0001F381',
     u':wrench:': u'\U0001F527',
     u':writing_hand:': u'\U0000270D',
+    u':yellow_circle:': u'\U0001F7E1',
     u':yellow_heart:': u'\U0001F49B',
     u':yin_yang:': u'\U0000262F',
     u':zipper__mouth_face:': u'\U0001F910'

3. from emoji import emojize
bot.send_message(emojize(":red_circle:", use_aliases=True))
bot.send_message(emojize(":green_circle:", use_aliases=True))
bot.send_message(emojize(":orange_circle:", use_aliases=True))

### Expected behaviour
As in case of 🔴 should be displayed Green or Orange circle.

### Actual behaviour
Tell us what happens instead

### Configuration
Tested on Windows 10 and Android 6

**Version of Telegram Desktop:**
1.5.2

**Used theme**:
Standard
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stek29** [comment]
wat

**Comment by OctoNezd** [comment]
https://emojipedia.org/green-circle/

Green Circle is a candidate for inclusion in Unicode 12.0 scheduled for release in 2019 and was added to draft Emoji 12.0 in 2018.

**Comment by PPSid** [comment]
Well, that I have seen ;)
Yet, any idea when exactly?

**Comment by OctoNezd** [comment]
First of all - it *may* be included

In theory it should be released on 9th march if I understood http://unicode.org/versions/Unicode12.0.0/ right

**Comment by PPSid** [comment]
большое спасибо, товарищ командир ;)
