### ISSUE TITLE
[Feature Request] Contact List Sorting

### ISSUE THREAD

**Issue by MattKercher** [telegramdesktop/tdesktop#5515]
Hey all,

I was just hoping to suggest the ability to swap the way the contacts list is sorted. It'd be nice to be able to change the sorting between the current method, alphabetical, to the last seen time like the sorting used in Telegram X and the MacOS client. Maybe with a filter popover in the top right corner of the Contact window, something like this?

![poorlymadedemo](https://user-images.githubusercontent.com/1923756/50399795-a7280100-0747-11e9-8f1c-b6bf71711d26.png)

It would be awesome to see something like this if anyone is interested. Thanks!

**Comment by SmartManoj** [comment]
Label for this

**Comment by MattKercher** [comment]
Any word on this?

**Comment by MattKercher** [comment]
This is still an unimplemented feature request so it'd be nice if the feature would remain open. This would bring the Telegram Desktop client in line with every other Telegram client, as they all offer sorting by last seem except Telegram Desktop. Android, MacOS, and iOS all provide the option to sort their contacts by last seen time.

**Comment by MattKercher** [comment]
Hello stale bot, this is still relevant. c:
