### ISSUE TITLE
Extra metadata added to the post preview

### ISSUE THREAD

**Issue by reverendhomer** [telegramdesktop/tdesktop#5516]
### Steps to reproduce
Actually, it's kind of shadow bug, I don't know how to reproduce it. Sorry, I hope the screenshot will clarify this issue.

### Expected behaviour
The text on the left bar is the start of the text in the post

### Actual behaviour
Some metadata was added

### Configuration
**Operating system:**

Fedora Linux 29

**Version of Telegram Desktop:**

1.5.3

**Used theme**:

default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

![screenshot from 2018-12-24 18-42-58](https://user-images.githubusercontent.com/4062234/50403058-a6758600-07ac-11e9-8747-10fe20377143.png)

**Comment by stek29** [comment]
does it persist after restart?

**Comment by reverendhomer** [comment]
> does it persist after restart?

Sorry, can't say since the're new messages in the channel. I saw that bug just once and in one channel. Now all previews are fine.

**Comment by stek29** [comment]
I think that they've just posted it with text accidentally, and have removed it afterwards. I strongly doubt there was any metadata added by tdesktop: maybe preview in chat list wasn't updated.

**Comment by reverendhomer** [comment]
>maybe preview in chat list wasn't updated

Then it is a bug in tdesktop, though different one. I don't know which exactly, but I haven't reproduced this kind of bug since. So if you think this bug lacks of information, feel free to close it.
