### ISSUE TITLE
Touchscreen scroll bug

### ISSUE THREAD

**Issue by alisentinel** [telegramdesktop/tdesktop#5517]
### Steps to reproduce
1. Open a explorer windows (or cmd...)
2. Open Telegram
3. Use touchscreen to scroll down or up in Telegram

### Expected behaviour
The Telegram must scroll up or down

### Actual behaviour
The background explorer windows or cmd scrolls

### Configuration
Windows 10
Lenovo Ideapad 300n (Lenovo ideapad 15iSK)
Touchscreen Driver:
Lenovo pointing device; Elan pointing device v11.4.69.4

**Version of Telegram Desktop:**
All versions

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by alisentinel** [comment]
I don't know, I've just changed my driver
