### ISSUE TITLE
Issue with Persian translation

### ISSUE THREAD

**Issue by srazi** [telegramdesktop/tdesktop#5518]
### Steps to reproduce
1. Use this link (http://t.me/setlanguage/fa-raw) to set language to Persian.
2. See for example `December 24`

### Expected behaviour
It should be:
`دسامبر 24`

### Actual behaviour
It is:
`دسامبر 42` (here I wrote forty two but indeed in application it is `<RLO>24` so its directional is overridden as Right-to-Left. Therefore, it is rendered as `42`

### Configuration
**Operating system:**
Windows 10 64 Bit
**Version of Telegram Desktop:**
1.5.4
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by srazi** [comment]
**Some screenshots:**
![1](https://user-images.githubusercontent.com/1328454/50406414-f3238600-07d9-11e9-8eba-d2ce1b4fdcfd.PNG)

In the following screenshot you can see the issue with `{from} removed {user}` that is translated to Persian as
`{from} {user} را حذف کرد`

When `{user}` is RTL `{from}` is rendered wrongly. It is look like that RLO Unicode control character was prepended to `{from}` that is of course wrong. The correct way of using Unicode control characters here is:
`<RLE>{from}<RLM> {user} را حذف کرد`
That will render like:
`‫{from}‏ {user} را حذف کرد`

But these characters should be added in translation and not in code.

![2](https://user-images.githubusercontent.com/1328454/50406416-f454b300-07d9-11e9-9845-aea27c423ee9.PNG)

Last screenshot with English translation:
![2_en](https://user-images.githubusercontent.com/1328454/50406417-f61e7680-07d9-11e9-9deb-fac434241b13.PNG)

**Comment by srazi** [comment]
Ha ha ha believe me it is Telegram Desktop version 5.4.1  (year 8102) :D
![image](https://user-images.githubusercontent.com/1328454/50406607-0126d600-07dd-11e9-9ae6-6a1187863b8a.png)

**Comment by srazi** [comment]
@john-preston Any idea? Maybe issue is in [text.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/ui/text/text.cpp)?

**Comment by john-preston** [comment]
@srazi Yes, code from the latest Qt version, that shapes Unicode text, should be backported to text.cpp module :(

**Comment by ali7911** [comment]
I think all of problems are because of Left to Right align that should be changed to Right to left.

**Comment by YedidyaLaufer** [comment]
Same problem with Hebrew language.
#bug

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by YedidyaLaufer** [comment]
Yes, it is.

**Comment by M299792458** [comment]
@john-preston please update Qt, I think they fixed that already in newer versions of Qt.
Thanks.

**Comment by Aokromes** [comment]
he is already working updating QT.

**Comment by ilya-fedin** [comment]
> he is already working updating QT.

This is issue is not from Qt

**Comment by Mehrshad3** [comment]
Hello
I think [this website](https://www.unicode.org/reports/tr9) is helpful.

**Comment by srazi** [comment]
Hi @Mehrshad3 
This issue has been fixed, so I close it again.
