### ISSUE TITLE
Support HEIC/HEIF images on Windows 10

### ISSUE THREAD

**Issue by DJ-ZX** [telegramdesktop/tdesktop#5522]
### Steps to reproduce

- 1 Take a picture on iPhone, download it to local storage
- 2a Copy picture to clipboard (for ex. from MS Photos app, open picture from library and copy from menu or with Ctrl+C, works with JPG perfectly)
- 2b Go to Telegram and try to paste image (Ctrl+V)
or
- 3 Use open dialog and try to select any HEIC file

### Expected behaviour
Image should be attached as picture with ability to add comment

### Actual behaviour
HEIC/HEIF files attached just as files

### Configuration
**Operating system:**
Windows 10 (any), HEIF codecs for all aps and even 3rd party for Desktop apps (includimg Windows Photo Viewer desktop app) installed, system supports HEIF files
**Version of Telegram Desktop:**
1.5.x latest beta

Note: Unigram supports HEIF files, but Unigram still has tons of other limitations.
Note2: looks it's valid for Android app too

**Comment by sturmen** [comment]
one caveat: I believe HEIF/HEIC support in Windows 10 requires the purchase of the $0.99 "HEVC Extension" app from the Windows store.

**Comment by DJ-ZX** [comment]
> one caveat: I believe HEIF/HEIC support in Windows 10 requires the purchase of the $0.99 "HEVC Extension" app from the Windows store.

not exactly - normally it's "preinstalled" by vendor and it enables writing but viewing is free - https://www.microsoft.com/en-us/p/heif-image-extensions/9pmmsr1cgpwg?lc=1033&activetab=pivot:overviewtab . But in any case - now it supported also on samsung phones and surface duo which are "MS supported" so change that users will move to HEIF images (videos is a separate problem) groving for windows users as well. Telegram Desktop still the main client (Unigram has limitations) so this is differently something to take a look to.

Same for Android app (I will submit beta feedback there as well)

**Comment by tooomm** [comment]
>I believe HEIF/HEIC support in Windows 10 requires the purchase of the $0.99 "HEVC Extension"

Some people might need it, depending on their windows version. But it's free.
Also check https://www.windowscentral.com/how-open-heic-and-hevc-files-windows-10s-photos-app#install_heif_codec_windows10

**Comment by DJ-ZX** [comment]
issue still exists - cannot attach heif file from any device or even created and edited on Windows as picture in TD

**Comment by ilya-fedin** [comment]
I don't think this would be implemented without support from Qt side

**Comment by DJ-ZX** [comment]
Issue still remains in newer versions ot Telegram despite Windows natively supports HEIF

**Comment by smasharov** [comment]
If I send HEIC file directly from iPhone it has the preview, even on desktop version, but if I send it from the desktop client the preview is missing on all of the devices and clients.

Telegram Desktop 3.4.3

**Comment by john-preston** [comment]
@smasharov The preview is generated by the sender, so that is sort of expected while the format isn't known to the app.

**Comment by smasharov** [comment]
I have opened the [https://github.com/telegramdesktop/tdesktop/issues/23886](url)

**Comment by ilya-fedin** [comment]
What's the point in opening duplicate when you know there's already an issue? :see_no_evil:

**Comment by smasharov** [comment]
it is not a complete duplicate and this issue is not solved for more than years

**Comment by ilya-fedin** [comment]
It's a complete duplicate since both issues are requesting HEIC/HEIF support. And it won't be supported since Qt doesn't support that format.

**Comment by smasharov** [comment]
Maybe it is a Qt issue, but the files send from iOS devices have preview and they are correctly displayed on the Desktop version.
So what is the problem to create previews on the Desktop version? Or at least have ability to generate them on the iOS device after the files were send from the Desktop client?

**Comment by john-preston** [comment]
@smasharov The sender generates a preview and sends it in JPG format. iOS app generates previews because it can read HEIF. Desktop app doesn't generate previews because it can't. iOS app doesn't generate previews for received files without previews because.. it doesn't. It can be a feature request for the iOS app, but it is irrelevant in this bugtracker. And I think they'll answer that it is the sender-s job to generate previews. And they're right ¯\_(ツ)_/¯

**Comment by DJ-ZX** [comment]
> It's a complete duplicate since both issues are requesting HEIC/HEIF support. And it won't be supported since Qt doesn't support that format.

it's not fully true - Qt allows to enable HEIF support but with known bugs in it but also there is 3rd party open source module that can be used https://github.com/jakar/qt-heif-image-plugin

The core issue here that Win10/11 platforms already natively supports HEIF/HEIC/HEVC, so if you have any of most popular smartphones (Apple or Samsung, which both have those formats support) and you want to keep them offline w/o converting to JPEG - makes hard to use Telegram Desktop to send them.
So "native converting" to JPEG under the hood will work too, but having support for formats will be amazing overall. Like native app a bit more that Unigram for numerous reasons, so do not want to switch (now using both only because of HEIF)

**Comment by john-preston** [comment]
@smasharov A (one) feature request for HEIF support can be left opened in this repository, but I can't tell if and when this feature request will be implemented.

**Comment by smasharov** [comment]
but OS have support of HEIC files and they are shown correctly right in the Telegram App, why the client can't generate the previews while sending the files?

**Comment by john-preston** [comment]
@smasharov What do you mean by "HEIC files are shown correctly in the Telegram App"?

**Comment by smasharov** [comment]
I have made corrections in my previous message.

**Comment by john-preston** [comment]
Yes, because native windows app supports this format.

Telegram Desktop uses Qt API QImageReader to read images, which doesn't have support for HEIC format although the system has the codecs.

**Comment by smasharov** [comment]
We just need to create the small preview by Qt plugin, I think it is worth to at least to try to do it.

**Comment by john-preston** [comment]
The plugin linked above is "with known bugs", another one requires additional libraries to be built.

**Comment by ilya-fedin** [comment]
> Qt allows to enable HEIF support but with known bugs

You mean without third-party plugins? If yes, how to enable it?

**Comment by smasharov** [comment]
so https://github.com/novomesk/qt-heic-image-plugin is also not usable?

**Comment by ilya-fedin** [comment]
Having third-party Qt plugins made by noname developers in official builds is probably not a good idea

**Comment by ilya-fedin** [comment]
> For me it is strange that Desktop version supports hevc/h265 and do not support HEIF/HEIC

Videos are read with ffmpeg, images are read with QImage

**Comment by ilya-fedin** [comment]
KDE community has https://invent.kde.org/frameworks/kimageformats library that offers support for a number of modern image formats. If it supported HEIF/HEIC, it were possible to use it and get support for a number a formats at once. But it doesn't support HEIF/HEIC, unfortunately.

**Comment by DJ-ZX** [comment]
> The plugin linked above is "with known bugs", another one requires additional libraries to be built.

any plugin may have the known bugs, the question - is it applicable and secure or not, if not - clear why to not use it, if yes - could be the way

I agree there is no fast solution, but this is a big limitation since more devices incorporate heif formats and raised not today.
So problem is not new and from Qt bugtracker https://bugreports.qt.io/browse/QTBUG-69212 I see that they are aware on that but doing nothing to finalize and fix (I did not find any notice). Also using diffrerent image reading lib could be solution

**Comment by ilya-fedin** [comment]
> Also using diffrerent image reading lib could be solution

Migrating from QImage to some other library is a huge job and I guess @john-preston would agree that it doesn't worth the effort (this issue has only 4 participants excluding me, @john-preston and @Aokromes and only 3 likes)

**Comment by smasharov** [comment]
Most of the ordinary users do not understand such things at all.

I have to periodically sent hundreds of photos to the Telegram group and for recipients it is very good to have a preview before downloading the photos. I do not have a Mac to test this feature on it and it is very inconvenient to send these files from iPhone.

**Comment by ilya-fedin** [comment]
Well, if you're really interested in that, you can try to implement that on your own

**Comment by smasharov** [comment]
I am not a developer, I work in support, so I can only offer different approaches for the solution :-)
In my opinion it should be not hard to add some small library for ability to read image from HEIC.

**Comment by ilya-fedin** [comment]
> In my opinion it should be not hard to add some small library for ability to read image from HEIC.

I don't see Qt HEIC library worth trusting here

**Comment by john-preston** [comment]
@smasharov It can be done but I'm not sure about "not hard" part, it requires a lot of effort to make it work on all platforms in all build scenarios.

**Comment by DJ-ZX** [comment]
@ilya-fedin btw: the one that I referenced is used in 2 other pretty know image viewers in OSS community, maybe not amazing reference, but good enough to keep it supported. Anyways, probably not the most important issue, but still a bug/limitation though

**Comment by ilya-fedin** [comment]
I see another problem: the license of the plugin itself is [ok](https://github.com/novomesk/qt-heic-image-plugin/blob/main/LICENSE), but let's look at its dependencies:
![изображение](https://user-images.githubusercontent.com/17829319/149190548-c65117da-e4d5-4078-86bb-bb8a1c68a891.png)

libheif is [ok](https://github.com/strukturag/libheif/blob/master/COPYING)
libde265 is [ok](https://github.com/strukturag/libde265/blob/master/COPYING)
x265 is [incompatible](https://bitbucket.org/multicoreware/x265_git/src/master/COPYING)

tdesktop depends on openssl which license is incompatible with GPL. tdesktop itself has an exception in its license.

**Comment by smasharov** [comment]
@john-preston what do you mean by "work on all platforms in all build scenarios"? Because on Desktop version for Mac it is working. The problem is only on Windows and maybe Linux platforms.

**Comment by john-preston** [comment]
@smasharov Well, it is not "only", the Windows platform is the main one and it has the most problems with building some of open source libraries, because it doesn't provide the usually used autoconf / make.

It should build and work on Windows, macOS, Linux official builds (the way dependencies are built there, see build instructions in this repository) + also on Linux flatpak and Linux snap build scenarios.

**Comment by smasharov** [comment]
So, it should build and work on all platforms, but this feature is working only on macOS, is it a normal situation?

**Comment by john-preston** [comment]
@smasharov I don't understand.

I wrote above that I don't think this is "not hard" task, because a lot of work needs to be done to ensure that it works on all platforms in all build scenarios. It doesn't work in tdesktop right now - on any platform in any build scenario.

**Comment by ilya-fedin** [comment]
> Because on Desktop version for Mac

Are you sure you're using tdesktop version for mac and not the dedicated client "Telegram for macOS"?

**Comment by 1valdis** [comment]
So it's been over 3 years and we still can't send HEIC pictures as, well, pictures from desktop... 😔 Maybe if you can't make a preview etc from HEIC, make some conversion to usual JPEG? It somehow works on Android and I can send HEIC from there. So why not desktop?

**Comment by ilya-fedin** [comment]
> So why not desktop?

Read the conversation

**Comment by bdigital24** [comment]
> Like native app a bit more that Unigram for numerous reasons, so do not want to switch (now using both only because of HEIF)

I agree with the sentiment of the thread -- I'd love to see native HEIF/HEIC support in Telegram Desktop. 

I have the HEIF and HEVC extensions from the Microsoft store.  I just tried dumping an *.HEIC photo in Unigram and got the same result as telegram desktop -- no "compressed image" preview and album grouping like it does with JPGs. Granted, there is a small thumbnail preview but it's not previewing HEIC/HEIF like TG desktop normally does with JPG and others. 

Is there something in Unigram that I'm missing?

![image](https://user-images.githubusercontent.com/90068251/157483709-1006e07e-5840-4cb3-b394-136bfbacb82e.png)

**Comment by ilya-fedin** [comment]
There's now support for AVIF, HEIC/HEIF and JPEG XL on Linux

**Comment by DJ-ZX** [comment]
What about Windows?

**Comment by ilya-fedin** [comment]
Apparently it needs a Windows enthusiast interested in this feature

**Comment by novomesk** [comment]
In order to build the heif,avif,jxl plugins on Windows, following file has to updated?

https://github.com/desktop-app/cmake_helpers/blob/master/external/kimageformats/CMakeLists.txt

**Comment by ilya-fedin** [comment]
Yeah, one needs to update the preprare.py script and add building of the libraries to it and then updated the file you mentioned, here's an example of how build rules for Windows and macOS look like usually: https://github.com/desktop-app/cmake_helpers/blob/master/external/openal/CMakeLists.txt#L21-L41

**Comment by novomesk** [comment]
Thanks for the info. I'm starting to understand what has to be done.

In the near future, I have other projects in my TODO list.

Afterwards, I can try to play with the scripts (if not implemented meanwhile).

**Comment by novomesk** [comment]
@ilya-fedin I am worried about one thing. What if someone send you a malicious HEIC file? We test kimageformats plugins via Google's oss-fuzz project. Specially crafted input can cause crash of whole application sometimes.

The HEIF plugin from kimageformats uses libheif and it uses libde265. Some issues were solved in libde265 but new incidents were found afterwards.
I say we should be careful when opening HEIC images via libheif/libde265, especially when those images are from unknown sources.

Plugins for AVIF and JPEG XL are quite reliable.

**Comment by ilya-fedin** [comment]
> via libheif/libde265

is there any other choice?

**Comment by novomesk** [comment]
I think only choice is keep helping/encouraging author of libde265 to fix found problems.

**Comment by novomesk** [comment]
I was able to build `Telegram.exe` on Win10 according the [build instructions](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-win-x64.md).
I will continue with editing `prepare.py` to build the necessary libraries for kimageformats. It will take same time...

**Comment by novomesk** [comment]
I think the HEIF plugin from kimageformats will need some changes to that it could be linked statically in Windows build.

**Comment by ilya-fedin** [comment]
Maybe you just haven't modified the qt_static_plugins.cpp in cmake_helpers?

**Comment by novomesk** [comment]
This problem is libheif related.
I know how to solve it.

**Comment by novomesk** [comment]
Following cmake rule make problems on Windows in combination with AUTOMOC:
```
nice_target_sources(external_kimageformats ${kimageformats_src}
PRIVATE
    avif.cpp
    heif.cpp
    jxl.cpp
)
```

I can't compile them together, just one after another.
When I make separate target for each plugin, then it works.

I still need to finalize cmake rules, not to mess debug and release libraries.

I haven't pushed the necessary changes to the HEIF plugin to kimagaformats yet.

I already have working Telegram.exe which shows previews of AVIF, HEIC and JXL images.

**Comment by ilya-fedin** [comment]
I wonder what's the error it returns?

**Comment by novomesk** [comment]
It is something that an expression from the first plugin is redefined by the second and third plugin source.

**Comment by ilya-fedin** [comment]
I want to know what expression is exactly

**Comment by novomesk** [comment]
I will reproduce it tomorrow and post more info.

**Comment by novomesk** [comment]
@ilya-fedin 
This is how the build error looked like:
![kimageformats](https://user-images.githubusercontent.com/52529860/205852255-186e624b-0b51-44fc-a460-4f9e3d330adf.png)

**Comment by ilya-fedin** [comment]
Can you get actual compiler arguments of the compiling command returning these errors?

**Comment by novomesk** [comment]
What is happening there that during the build process `kimageformats\external_kimageformats_autogen\mocs_compilation_Debug.cpp` is created and the content is following:
```
// This file is autogenerated. Changes will be overwritten.
#include <FKSTYVLCUA/moc_avif_p.cpp>
#include <FKSTYVLCUA/moc_heif_p.cpp>
#include <FKSTYVLCUA/moc_jxl_p.cpp>
```
It simply puts 3 different `Meta object code` sources into one file.

I can investigate more but I as wrote, individual targets for each plugin works. Something like this:
```
add_library(kimg_avif OBJECT)
add_library(kimg_heif OBJECT)
add_library(kimg_jxl OBJECT)
add_library(external_kimageformats STATIC $<TARGET_OBJECTS:kimg_avif> $<TARGET_OBJECTS:kimg_heif> $<TARGET_OBJECTS:kimg_jxl>)
```

**Comment by ilya-fedin** [comment]
Looks like cmake issue https://gitlab.kitware.com/cmake/cmake/-/issues/17277, replacing AUTOMOC with qt_generate_moc should help
https://doc.qt.io/qt-6/qt-generate-moc.html

**Comment by ilya-fedin** [comment]
Something like this will work I believe
```
set(kimageformats_srcs)
qt_wrap_cpp(kimageformats_srcs
    ${kimageformats_src}/avif.cpp
    ${kimageformats_src}heif.cpp
    ${kimageformats_src}/jxl.cpp
TARGET
    external_kimageformats
DEPENDS
    ${kimageformats_src}/avif.json
    ${kimageformats_src}heif.json
    ${kimageformats_src}/jxl.json
)

nice_target_sources(external_kimageformats ${kimageformats_src}
PRIVATE
    avif.cpp
    heif.cpp
    jxl.cpp
)
target_sources(external_kimageformats PRIVATE kimageformats_srcs)

**Comment by novomesk** [comment]
It works with little change. I had to put **_p.h** files to the qt_wrap_cpp

Otherwise I got link errors like:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "struct QStaticPlugin const __cdecl qt_static_plugin_QAVIFPlugin(void)" (?qt_static_plugin_QAVIFPlugin@@YA?BUQStaticPlugin@@XZ) referenced in function "public: __cdecl StaticQAVIFPluginPluginInstance::StaticQAVIFPluginPluginInstance(void)" (??0StaticQAVIFPluginPluginInstance@@QEAA@XZ)	Telegram	C:\Devel\TBuild\tdesktop\out\Telegram\qt_static_plugins.obj	1
```

This is how it looks and which works for me on Windows:
[CMakeLists.txt](https://github.com/telegramdesktop/tdesktop/files/10175204/CMakeLists.txt)

Could you test if these changes make no problem on Linux?

**Comment by ilya-fedin** [comment]
I will test a little bit a later, but I believe it should work

**Comment by novomesk** [comment]
New edits:
[CMakeLists.txt](https://github.com/telegramdesktop/tdesktop/files/10176114/CMakeLists.txt)

My edits in qt_static_plugins.cpp:
[qt_static_plugins.cpp.txt](https://github.com/telegramdesktop/tdesktop/files/10176199/qt_static_plugins.cpp.txt)

**Comment by ilya-fedin** [comment]
The empty line should be after #endif, looks ok otherwise

**Comment by novomesk** [comment]
The heif.cpp which I am able to link statically on Windows is now in kimageformats.

But I need that someone updates the submodule so we can use the newest source here.

If you wish to do it later (after next release of kimageformats for example), no problem for me. Just tell me when I can start with PR for prepare.py

**Comment by ilya-fedin** [comment]
You can update it in your PR
