### ISSUE TITLE
[Feature request] Sort Votes options by number of votes

### ISSUE THREAD

**Issue by RMPR** [telegramdesktop/tdesktop#5524]
### Steps to reproduce
1. Create a new poll with the option integrated in chat groups
2. Add Whatever options you want
3. Start the poll

### Expected behaviour
Tell us what should happen
Sort the options by number of votes, or at least give the option to do so.

### Actual behaviour
Tell us what happens instead
Votes are just printed statically.

### Configuration
**Operating system:**
Windows 10 Home version 1803

**Version of Telegram Desktop:**
1.5.4

**Used theme**:
Night Mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Nachtalb** [comment]
I haven't really worked with the voting system yet. But I can imagine that in big groups (several thousand or so) the votes could change so fast that the entries of the votes would jump up and down. This would make it rather unreadable and unpleasing for the eye. I do think though that this would be nice after the poll has stopped.

**Comment by RMPR** [comment]
That's why I said add to add an option, I think i'll be very nice to have a
quick overview of results and since some poll bots already have that
feature...

**Comment by stek29** [comment]
Fixed option positions is a feature, and I doubt reordering could be introduced in one app.
Also, what about poll results being hidden unless voted? How is it supposed to work then? When you vote everything moves, and when you take your vote back everything moves back? I don't think that's a good idea.
