### ISSUE TITLE
my last seen is online after closing telegram desktop

### ISSUE THREAD

**Issue by siamak2** [telegramdesktop/tdesktop#5528]
### Steps to reproduce
1. open telegram desktop.
2. close telegram desktop using x button.

### Expected behaviour
my last seen should be like "last seen today at ##:##".
### Actual behaviour
my last seen is online.
### Configuration
**Operating system:**
windows 7
**Version of Telegram Desktop:**
1.5.4
**Used theme**:
classic

**Comment by john-preston** [comment]
@siamak2 Maybe it is for a short time?

**Comment by siamak2** [comment]
my last seen is online for minutes after closing tdesktop. I didn't check it to see whether I'm online for hours or not.
I want my last seen to be offline (last seen today at ##:##) immediately after closing tdesktop.
currently I minimize tdesktop to go offline and then right click on it and close it (in this way I go offline immediately).

**Comment by Edicksonjga** [comment]
There is no problem in Beta 1.5.5 with Windows 7, if your telegram is in the foreground (shown on the screen) after 30 seconds of inactivity, your status "Online" changes to "Last time ...", if minimizes your telegram (shown in the task bar) its status "Online" immediately changes to "Last time ..." (if it does not change, exit and enter the chat again and you will see that it has changed), if you close your telegram in the "X" (not shown in the taskbar), its status "Online" will immediately change to "Last time ...".

By the way, in Linux, the disconnection for inactivity after 30 seconds works, but when they write to you, their status "Online" only activates and marks the messages as read, this does not happen in Windows. #4664

Operating system:
windows 7
Version of Telegram Desktop Beta:
1.5.5
Used theme:
classic

**Comment by siamak2** [comment]
I tried beta 1.5.5 but the problem still exist.
in both version (1.5.4 and 1.5.5 beta) my last seen status is online for 20 minutes after closing tdesktop.
I want my last seen status to go offline immediately (or a few seconds later) not after 20 minutes.
minimizing is OK (my last seen status go offline immediately).
