### ISSUE TITLE
Forwarded messaged are not deleted if original is deleted

### ISSUE THREAD

**Issue by Andrey-Raspopov** [telegramdesktop/tdesktop#5530]
### Steps to reproduce
1. Forward your message somewhere
2. Delete original message

### Expected behaviour
Both messages will be deleted

### Actual behaviour
Forwarded message remains.

### Configuration
**Operating system:**
Ubuntu, Windows, Android
**Version of Telegram Desktop:**
1.5.4
**Used theme**:
Default

**Comment by 23rd** [comment]
This is how server works.
