### ISSUE TITLE
[Feature request] Display chat times in microseconds 

### ISSUE THREAD

**Issue by veenodp** [telegramdesktop/tdesktop#5531]
### Expected behaviour
I am using telegram desktop client in which i need chat time with below format 
11:21:39.415513 which includes microseconds.

is there any way or alternative that i can make this work

### Actual behaviour
I am able to see the seconds in time by doing some modification in registry
now its showing time with seconds 11:21:39

### Configuration
**Operating system:**
windows 7
**Version of Telegram Desktop:**
1.5.4 telegram desktop
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stek29** [comment]
## Why?


All "chat times" are in unix timestamp with precision up to seconds, there are no microseconds to show.
