### ISSUE TITLE
[Feature request] Allow redline shortcuts in the message input box

### ISSUE THREAD

**Issue by Rafaelsalass** [telegramdesktop/tdesktop#5532]
<!--
Thanks for reporting issues of Telegram Desktop!

To make it easier for us to help you please enter detailed information below.

### Expected behaviour
Allow user to use the readline shotcuts for editting text in the message input

### Actual behaviour
It is not implemented yet

### Configuration
Manjaro linux 64 bit

**Comment by stek29** [comment]
elaborate
