### ISSUE TITLE
Edited messages are displayed to the blocked user

### ISSUE THREAD

**Issue by KrutNA** [telegramdesktop/tdesktop#5533]
### Steps to reproduce
1. Open telegram app
2. Block user
3. Edit any message, sended to this user before blocking

### Expected behaviour
Message is not edited for blocked user

### Actual behaviour
Blocked user can see edited messages

### Configuration
**Operating system: Tested on Linux and Android apps**

**Version of Telegram Desktop: 1.5.4**

**Comment by Aokromes** [comment]
i don't think this is fixable, and if it's the same on other platform it doesn't belong here.
