### ISSUE TITLE
"Create poll" on Chat Info

### ISSUE THREAD

**Issue by ThigSchuch** [telegramdesktop/tdesktop#5534]
### Steps to reproduce
1. Open a chat info 
2. Three dots has a create poll option too

![image](https://user-images.githubusercontent.com/20743110/50541152-4bfa7200-0b7e-11e9-9fbb-6b15e1171bab.png)

### Expected behaviour
Should or not be there?

### Configuration
**Version of Telegram Desktop:**
1.5.5

**Comment by ArmeF97** [comment]
I think not
