### ISSUE TITLE
Telegram Passport does not works

### ISSUE THREAD

**Issue by ajsb85** [telegramdesktop/tdesktop#5536]
Hi, I was trying to login with Telegram Passport.
I already added a password and the information.
But after success in the desktop app the Website did not received the information about the success from the Telegram Desktop.
The reason: Chrome Canary does not open URLs from external apps, because it's a secondary web browser.

Tested in this page: https://core.telegram.org/passport/example

![image](https://user-images.githubusercontent.com/663460/50543199-2480c500-0bd1-11e9-9cea-e28f721589aa.png)

![image](https://user-images.githubusercontent.com/663460/50543200-28144c00-0bd1-11e9-98a2-3499a120c20a.png)

![image](https://user-images.githubusercontent.com/663460/50543201-2a76a600-0bd1-11e9-8dad-a01c42d4d01c.png)

![image](https://user-images.githubusercontent.com/663460/50543223-ef28a700-0bd1-11e9-9505-917d6fe88d86.png)

**Comment by stek29** [comment]
And what is expected behavior?

**Comment by Aokromes** [comment]
no answer for more than a year. closing.
