### ISSUE TITLE
Last frame of uploaded animated GIFs gets deleted

### ISSUE THREAD

**Issue by gaetjen** [telegramdesktop/tdesktop#5537]
### Steps to reproduce
1. Drag and drop a GIF file from a folder in your file system into Telegram to send it. (e.g. this one: https://imgur.com/i1vBV49 )
EITHER
2a. Quit Telegram
3a. Delete, rename or move the original file
4a. Open Telegram, look at the sent message/GIF
OR
2a. Look at the sent message from another app/machine (tried with Android app)

### Expected behaviour
The sent gif should look exactly the same as the original file.

### Actual behaviour
The last frame of the gif is missing.

### Configuration
**Operating system:**
Ubuntu 18.04

**Version of Telegram Desktop:**
1.5.4

**Comment by stek29** [comment]
Server-side issue :(
