### ISSUE TITLE
Feature Request: Keyword Alert

### ISSUE THREAD

**Issue by itstake** [telegramdesktop/tdesktop#554]
please add Keyword alert feature

how it works:

1.a set keyword 'asdf'
2.a turn off b's chat room alert
3.if b chat 'eqwe', telegram will not alert b's message, but b chat 'asdf', telegram will alert b's message
sorry for bad english :(

**Comment by auchri** [comment]
They can mention you and you will get a notification, even if you mute the group

**Comment by melnikovalex** [comment]
Both issues (this and #1727) about this topic are closed. But the feature request is still actual - the feature might be very useful.

Could it be any progress there?

Thank you!
