### ISSUE TITLE
Show video messages within multimedia

### ISSUE THREAD

**Issue by fabyRojas** [telegramdesktop/tdesktop#5542]
A section within multimedia to show the video messages sent

![videom](https://user-images.githubusercontent.com/45982624/50570124-697c3700-0d4a-11e9-9956-54ba32d8dfcc.png)

**Comment by john-preston** [comment]
@fabyRojas They're together with audio messages for now.

**Comment by fabyRojas** [comment]
@john-preston , I understand, but, in the future, could a separate way be implemented to visualize the video messages in the multimedia?

**Comment by fabyRojas** [comment]
I understand, but, in the future, could a separate way be implemented to visualize the video messages in the multimedia?
