### ISSUE TITLE
telegram-desktop fails to emerge due to file permissions

### ISSUE THREAD

**Issue by krisk0** [telegramdesktop/tdesktop#5543]
### Steps to reproduce
1. emerge telegram-desktop
2. 
3. 

### Expected behaviour
success

### Actual behaviour
>>> Preparing source in /tmp/portage/net-im/telegram-desktop-1.5.2/work/telegram-desktop-1.5.2 ...
 [32;01m*[0m Applying patches from /tmp/portage/net-im/telegram-desktop-1.5.2/files/patches ...
 [32;01m*[0m   PrecompiledHeader-cmake.patch ...
[A[72C [34;01m[ [32;01mok[34;01m ][0m
 [32;01m*[0m   add-private-qt-functions.patch ...
[A[72C [34;01m[ [32;01mok[34;01m ][0m
 [32;01m*[0m   fix-xdg.patch ...
[A[72C [34;01m[ [32;01mok[34;01m ][0m
 [32;01m*[0m   gcc-if-constexpr-tmpfix.patch ...
[A[72C [34;01m[ [32;01mok[34;01m ][0m
/tmp/portage/net-im/telegram-desktop-1.5.2/temp/environment: line 387: /tmp/portage/net-im/telegram-desktop-1.5.2/work/telegram-desktop-1.5.2/Telegram/CMakeLists.txt: Permission denied
 [31;01m*[0m ERROR: net-im/telegram-desktop-1.5.2::gentoo failed (prepare phase):
 [31;01m*[0m   (no error message)
 [31;01m*[0m 
 [31;01m*[0m Call stack:
 [31;01m*[0m     ebuild.sh, line  124:  Called src_prepare
 [31;01m*[0m   environment, line 3725:  Called cmake-utils_src_prepare
 [31;01m*[0m   environment, line 1126:  Called _cmake_cleanup_cmake
 [31;01m*[0m   environment, line  341:  Called _cmake_modify-cmakelists
 [31;01m*[0m   environment, line  400:  Called die
 [31;01m*[0m The specific snippet of code:
 [31;01m*[0m    die

### Configuration
**Operating system:**
Gentoo Linux

**Version of Telegram Desktop:**
9999

Workaround:
```
    chmod -R u+w .
    find . -type d | xargs chmod u+x
```
before cmake-utils_src_prepare

**Comment by stek29** [comment]
tdesktop in gentoo repos is not official, you'd have to report issue to maintainers.
