### ISSUE TITLE
no audio in telegram in app player.

### ISSUE THREAD

**Issue by harimurtie** [telegramdesktop/tdesktop#5544]
### Steps to reproduce
1. telegram desktop v1.5.4 on manjaro 18.0.1
2. kernel 4.20.
3. 

### Expected behaviour
working audio in audio/video files within telegram in application  

### Actual behaviour
no audio

### Configuration
**Operating system:**
manjaro i3 18.0.1
**Version of Telegram Desktop:**
1.5.4
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>
workaround : downgrade telegram desktop to v1.4.3

**Comment by Sutarat66** [comment]
เมื่อ พ. 2 ม.ค. 2562 เวลา 00:36 harimurtie <notifications@github.com>
เขียนว่า:

**Comment by Aokromes** [comment]
#5481

**Comment by Sutarat66** [comment]
เมื่อ พ. 2 ม.ค. 2562 เวลา 01:40 Aokromes <notifications@github.com>
เขียนว่า:

**Comment by harimurtie** [comment]
found 2 workaround.
1.kernel 4.20, downgrade telegram desktop to v1.4.3
or 
2.downgrade to kernel 4.19.

**Comment by stek29** [comment]
Does it work with 2x speed?

**Comment by stek29** [comment]
Please upgrade your kernel so there's no sound, and play a voice message with 2x speed (there's a button to speed up voice message playback speed)

**Comment by Aokromes** [comment]
#5481
