### ISSUE TITLE
Telegram on snap doesn't write accents

### ISSUE THREAD

**Issue by DiogoConstantino** [telegramdesktop/tdesktop#5545]
### Steps to reproduce
1. try to type á on telegram

### Expected behaviour
It show write á

### Actual behaviour
It only writes a

### Configuration
Ubuntu with snap package (with other packaging options it doesn't happen)

**Version of Telegram Desktop:**
All

**Used theme**:
Default

</details>

**Comment by stek29** [comment]
#5487

**Comment by alfalco** [comment]
### Steps to reproduce
1. Type ã on Telegram

### Expected behaviour
It show write ã

### Actual behaviour
It only writes a

### Configuration
Ubuntu/Kubuntu with snap package

**Version of Telegram Desktop:**
Snap from channel stable, version 1.5.15

**Used theme**:
Default

**Comment by tcarrondo** [comment]
@stek29 this is not a duplicate of #5487

**Comment by stek29** [comment]
@tcarrondo indeed, thanks.

**Comment by thiagoabreu** [comment]
Same problem. I tried the usual DBus workaround I found in other issues (#1360) for no avail.

**Comment by Germoluso** [comment]
Can confirm. Accents work fine on Telegram obtained via ppa or .deb package (Ubuntu 16.04), but Telegram on Snap simply cannot reproduce them.

**Comment by vekat** [comment]
accents don't work for me either on 18.04, I'm using the regular download version from the website

**Comment by bernardodomingues-hotmart** [comment]
This might be a problem with snap itself. I've just tested another app installed via `snap`(Spotify) and had the same problems with accentuated characters.

**Comment by maxan** [comment]
Hello, everyone! I'm facing the same problem. I'm using the Telegram 1.7.10 within Linux Mint 19.1 from snap.

**Comment by REIS0** [comment]
Same thing here, using telegram desktop from ubuntu repos i have no problems but with snap version, which is more up to date, i can't type any accents.
Telegram 1.7.13 in Pop_OS! 19.04.

**Comment by leandroramos** [comment]
Accents work only if we use en-us as system language, which doesn't make any sense.

**Comment by abnersn** [comment]
Same problem in Brazilian Portuguese and pt_BR.UTF-8 as LANG.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1041

**Comment by leandroramos** [comment]
I think issue #1041 mixes a lot of issues, this should not be closed because it is a snap package exclusive (and very old) issue. This doesn't happen with the tar.gz downloaded from desktop.telegram.org. Different issues.

**Comment by DiogoConstantino** [comment]
I agree, even today someone complained to me about it.

**Comment by ilosamart** [comment]
This is still a problem in Ubuntu 19.10. I'm removing Telegram snap.

**Comment by leandroramos** [comment]
That's why non verified snaps should not appear in the store.

Em sex, 3 de jan de 2020 11:19, Fábio Tramasoli <notifications@github.com>
escreveu:

**Comment by ilosamart** [comment]
I dunno if this is the case, since the app is alledgedly from this team: https://snapcraft.io/telegram-desktop .

**Comment by carlosnovaduarte** [comment]
This is also happening to me. I have a PT-PT keyboard and my system language is set to EN-US. However I am also not able to use accentuated characters such as 'ã' or 'á'.
