### ISSUE TITLE
[Linux] [Snap] telegram-desktop from snapcraft is not using system cursor

### ISSUE THREAD

**Issue by Dibro89** [telegramdesktop/tdesktop#5546]
### Steps to reproduce
1. Install telegram-desktop from snapcraft: https://snapcraft.io/telegram-desktop

### Expected behaviour
Cursor being the same as in desktop environment.

### Actual behaviour
Uses default cursor theme.

### Configuration
**Operating system:**
Ubuntu 18.10 with plasma-desktop

**Version of Telegram Desktop:**
1.5.4

**Used theme**:
Default

### See also
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1579268
Issue #5010

PR #4505:
![image](https://user-images.githubusercontent.com/16293890/50577971-f4892a00-0e3b-11e9-91a0-ecad126546e1.png)

**Comment by Dibro89** [comment]
@3v1n0 Hello, any ideas?

**Comment by mihilbabin** [comment]
telegram-desktop 1.8.15 on KDE Neon - same issue.

**Comment by Aokromes** [comment]
that "telegram-desktop" is snapcraft package or linux distribution package? if the 2nd plz test with official package.

**Comment by Dibro89** [comment]
@Aokromes snapcraft

**Comment by mihilbabin** [comment]
It is snapcraft latest package for me as well.

**Comment by ilya-fedin** [comment]
This seems to be a snap issue itself, I have multiple snaps installed and none of them use system cursor theme (including Firefox) :(

**Comment by Aokromes** [comment]
@Dibro89 @mihilbabin @ilya-fedin test the last row https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1833611

**Comment by ilya-fedin** [comment]
I have the latest `gtk-common-themes` package already 🧐
+1 for close as 3rd party bug
