### ISSUE TITLE
emoji suggestions missing emoji 11

### ISSUE THREAD

**Issue by Bubu** [telegramdesktop/tdesktop#5547]
### Steps to reproduce
1. type :magnet

### Expected behaviour
Magnet emoji (🧲) suggestion appearing

### Actual behaviour
Nothing

### Configuration
**Version of Telegram Desktop:**
1.5.4

**Used theme**:
default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

The reason for this is that the newer emojis aren't present in https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/emoji_autocomplete.json. I'm not sure where this list is from/how it should be updated though.

**Comment by 23rd** [comment]
Looks like that was fixed.
