### ISSUE TITLE
[feature request] boss key

### ISSUE THREAD

**Issue by philiparvidsson** [telegramdesktop/tdesktop#5548]
I would like to propose a "boss key" to activate/hide Telegram.

As an avid user of Cmder (http://cmder.net/), I often press a global kbd shortcut to bring the terminal up and also to hide it.

As I chat at work, I switch back and forth to telegram and other applications a lot. Alt-tab sometimes doesn't cut it, so I would like to request a customizable boss key that shows telegram if it isn't active/focused, and minimizes it if it is active.

**Comment by Aokromes** [comment]
imho minimize is not enough, better minimize to tray.

**Comment by SmartManoj** [comment]
I use win + taskbar_icon_number

**Comment by SmartManoj** [comment]
> Ctrl W - to minimize

Ctrl W - minimize to tray @Aokromes
