### ISSUE TITLE
Add Speaker Settings and Microphone Settings

### ISSUE THREAD

**Issue by Fathurhoho** [telegramdesktop/tdesktop#5551]
Some users included me are using some devices for input (mic) and output (speaker). In my case, i'm usually activate my 'stereo mix' as my default mic and often forget to change it into 'internal or external mic' when start a call with someone. Same goes with the output.

So i need to change the default input/output through 'system sounds settings' and restart telegram. 

Here i need:
- Microphone setting: choose what device become input
- Speaker setting: choose what device become output

...**which is can be affected directly without close/re-open tdeskop**.

1. Operating System: Windows and Linux
2. Client version: TDesktop 1.5.5 Beta

Thanks

**Comment by stek29** [comment]
#5540
