### ISSUE TITLE
Add option that extract user messages in groups by Picture, Sticker, etc...

### ISSUE THREAD

**Issue by mehti1367** [telegramdesktop/tdesktop#5552]
I'd really like if telegram desktop splits all messages of a user in an group, i know there is a option that extract all message from selected user, but example there isn't a option that show only user "picture" messages.

**Comment by stek29** [comment]
So, add User filter to shared media?

**Comment by mehti1369** [comment]
or Vice Versa

**Comment by mehti1367** [comment]
Every time I'd come here to see if this feature has been implement :(
