### ISSUE TITLE
[IDEA] Organizing text conversations

### ISSUE THREAD

**Issue by antt0n** [telegramdesktop/tdesktop#5553]
Hello,
I use Telegram regularly, and in its daily use, one feature is missing in my opinion, cruelly on call.
I think we should add the possibility of sorting our textual conversations into "categories".
The latter could be configured in the application settings and remain non-binding.
When this feature is enabled, a category is automatically created that groups all unsorted text discussions into a category.
To add a discussion in a category, right-click and assign it to a previously created category.
The idea is interesting to me, because it can allow users who use it in a professional and personal context to sort their conversations.
Thank you.

![telegram_2019-01-04_18-25-53](https://user-images.githubusercontent.com/20756073/50701685-d3e4ee00-104e-11e9-9b9f-aca62d4f7c7b.png)

[https://puu.sh/CrBQA/342156ab1a.png](url)

**Comment by MasterGroosha** [comment]
Please, use search next time. This was discussed lots (I mean, LOTS) of times
