### ISSUE TITLE
Long file extensions are out of bounds in preview

### ISSUE THREAD

**Issue by RadRussianRus** [telegramdesktop/tdesktop#5555]
Shouldn't file extension inside file icon be trimmed?
![image](https://user-images.githubusercontent.com/2903496/50793912-ac09ba80-12da-11e9-8501-06e87bcf436e.png)

TDesktop 1.5.5 beta, Windows 10 Pro 1809

**Comment by Aokromes** [comment]
api issue: https://github.com/telegramdesktop/tdesktop/issues/3573

**Comment by RadRussianRus** [comment]
@Aokromes
How is this api issue, when trimming is done on client side?

**Comment by stek29** [comment]
> file extension on left 

wat?

**Comment by stek29** [comment]
@Aokromes turns out he's referring to file extension inside of "file" icon

**Comment by RadRussianRus** [comment]
Updated issue, sorry for confusing.
