### ISSUE TITLE
Send imagem with thumb

### ISSUE THREAD

**Issue by otavioschwanck** [telegramdesktop/tdesktop#556]
It's very important, its very hard to send a photo without a thumb to see the photo.

**Comment by auchri** [comment]
Where do you miss a picture?

**Comment by otavioschwanck** [comment]
When i'll send a picture.  I can see the name of the image files, but not the thumb.

**Comment by ucay** [comment]
Same here.
Using Linux Mint 17 Cinnamon 64-bit

![screenshot from 2015-10-15 10 37 31](https://cloud.githubusercontent.com/assets/3348846/10504392/270765d8-732a-11e5-9c4b-d7c83707e877.png)
