### ISSUE TITLE
[Feature Request] Copy Bettergram tab grouping, it's open source

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#5560]
Hi, there is a Telegram alternative client, which is called Bettergram.
![immagine](https://user-images.githubusercontent.com/6240983/50790556-83c09280-12bf-11e9-9635-18bf29284b5b.png)
As you can see it separates groups, private chats and channels.
Its source is open, so I think it should be easy to integrate this in official telegram. 
Of course it would be better to add an option to continue to have the mixed chats version

What do you think? 
https://github.com/bettergram/bettergram

**Comment by RememberTheAir** [comment]
If Telegram wanted tabs in the official desktop app, they would have already implemented them. At this point it's pretty clear they do no want this kind of chats organization in their official apps

**Comment by john-preston** [comment]
Wow, a really maintained fork. I didn't think someone could do this with such code.

**Comment by kenorb** [comment]
Related: GH-5560

**Comment by kenorb** [comment]
Dup of: GH-4873

**Comment by Xambey** [comment]
this problem is the reason why I prefer bettergram

**Comment by kenorb** [comment]
Chat folders has been implemented now. See: https://telegram.org/blog/folders

> Telegram was updated to version 6.0 (196005)
>
> Chat Folders and More
> 
> • Organize chats into Chat Folders if you have too many chats.
> 
> • Create custom folders with flexible settings, or use default recommendations.
> 
> • Pin an unlimited number of chats in each folder.
> 
> • Archive chats to hide them from "All chats". Muted chats will always stay in the Archive.
