### ISSUE TITLE
Smile icon on theme preview has wrong position

### ISSUE THREAD

**Issue by tsvietOK** [telegramdesktop/tdesktop#5561]
### Steps to reproduce
1. Open Theme preview from a chat(*.tdesktop-theme).
2. While in a preview, look for a smile an the right edge of message input field.
### Expected behaviour
Smile icon should be inside the circle

### Actual behaviour
Smile icon is outside the circle. (top left)

### Configuration
**Operating system:**
Windows 10 Pro 1809
**Version of Telegram Desktop:**
1.5.4
**Used theme**:
This bug doesn't depend on theme

**Comment by john-preston** [comment]
Thanks!
