### ISSUE TITLE
Keyboard shortcut to navigate to chat list search

### ISSUE THREAD

**Issue by p0358** [telegramdesktop/tdesktop#5562]
### Steps to reproduce
1. Intend to go to search bar above chat list
2. Realize there isn't a convenient shortcut for this and you have to move your mouse manually

### Expected behaviour
I would expect a shortcut for this action, so I can navigate between chats easily (when there is too many to use Alt+arrows conveniently)

### Actual behaviour
I need to manually click in search bar in order to search for a chat

### Configuration
**Operating system:** Windows 10 1809

**Version of Telegram Desktop:** 1.5.5 beta

**Used theme**:

<details>
There is load of convenient shortcut keys in Telegram Desktop: https://github.com/telegramdesktop/tdesktop/wiki/Keyboard-Shortcuts
There is one regarding search, which is Ctrl+F, but there's no key to enter search bar in chat list!
It's something similiar to pressing Ctrl+L in a browser window, but Ctrl+L (or Alt+D?) in Telegram locks it.
I'd appreciate if this kind of shortcut could be introduced too, it's the only one I'm missing, and it would speed things up (and the productivity!)
</details>

**Comment by john-preston** [comment]
@p0358 Just press Escape.

**Comment by p0358** [comment]
Oh, that does indeed know, didn't know about it

**Comment by p0358** [comment]
Just now I noticed it says "Exit selected chat and search Telegram" on the wiki, so I'm going to close this issue for now

**Comment by mogwai** [comment]
Why are the keybindings so inconsistent across operating systems. On Mac the keyboard shortcut is `CMD+K` to do this but this doesn't exist on the linux version?
