### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by everyonus** [telegramdesktop/tdesktop#5564]
Is it possible to change the directory from which photos and gifs are downloaded to?

**Comment by ilya-fedin** [comment]
If I understood right
![image](https://user-images.githubusercontent.com/17829319/77236170-ef84d780-6bb3-11ea-8991-46da38d3a532.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1359
