### ISSUE TITLE
Profile picture which never stops loading

### ISSUE THREAD

**Issue by DarkSuniuM** [telegramdesktop/tdesktop#5565]
### Steps to reproduce
1. Open Telegram
2. Try to view https://t.me/SubScript profile's picture

### Expected behaviour
Show a profile picture or the profile picture not be clickable

### Actual behaviour
My friend has 9 photos uploaded on his profile, The latest one never stops loading, In the chats sidebar, It shows the first characters of his saved firstname and lastname on a green background as his profile picture, When I open his profile it's just nothing the, Like a transparent image which is clickable by the way, When I click on that, it's a gray-like image which never stops loading or even if it does, it shows something like transparent pattern that gimp uses for transparent parts of the image

### Configuration
**Operating system: Archlinux**

**Version of Telegram Desktop: 1.5.4**

**Used theme: Midnight**

**Comment by DarkSuniuM** [comment]
https://t.me/ZetaTech_lR/31977
Also there is the picture in this post which never stops loading

**Comment by john-preston** [comment]
@DarkSuniuM On both of those pictures server returns some errors (LOCATION_INVALID on the profile picture and FLOOD_WAIT_ on the post photo). Something's wrong with them on the server-side.
