### ISSUE TITLE
[BUG] [Windows] Mic icon for Voice Notes missing on the Huawei Matebook X Pro (2018)

### ISSUE THREAD

**Issue by MariuxReloaded** [telegramdesktop/tdesktop#5566]
### Steps to reproduce
1. Install Telegram Desktop 1.5.4 on Windows 10 on my new Huawei Matebook X Pro (famous for its webcam and microphone hidden in the keyboard)
2. Start Telegram
3. There is no mic icon for Voice Notes in chats

### Expected behaviour
The mic icon button should be present on the entry line

### Actual behaviour
There are only the Emoticons and Stickers and the Send buttons

### Configuration
Windows 10 1809 October 2018 Update (build 17763.253)

**Version of Telegram Desktop:**
1.5.4

**Used theme**:
Default

**Comment by MariuxReloaded** [comment]
> check you have mic selected on settings->sound:
> 
> https://i.imgur.com/TTpfTKw.png

Yes, of course the mic is selected and it's working.
I've also tried to keep the webcam open, in order to remove any kind of obstacles for the mic, but nothing has changed (Cortana works both with the webcam open and closed), even after closing and re-opening Telegram Desktop

**Comment by MariuxReloaded** [comment]
> try updating to 1.5.5 beta.

I've just performed the installation of the beta version, but nothing has changed. The problem is still there

**Comment by MariuxReloaded** [comment]
> Does microphone show up in calls settings?

> Oh, and have you added telegram to the list of apps which can access microphone in system settings?

Yes, microphone shows up in calls settings, but Telegram Desktop doesn't appear at all in Settings --> Privacy --> Microphone, so I can't enable microphone permissions for it from there

**Comment by MariuxReloaded** [comment]
> > I can't enable microphone permissions for it from there
> 
> I don't use windows much, but iirc there should be a way to add an app manually.

Unfortunately not, I've searched for that kind of solution on the web, before opening this thread here, but it is not possible. That Settings section is just for Windows 10 apps

**Comment by MariuxReloaded** [comment]
Even after updating Telegram Desktop to version 1.5.8, which now allows to choose the default input and output devices from Settings --> Advanced, nothing has changed today. 
I've tried the mic test and it works, I've tried Voice Calls and they work, but the Voice Note button in the chat windows doesn't show up

**Comment by MariuxReloaded** [comment]
After about a month and a lot of new updates of Telegram Desktop, the problem on my Matebook X Pro still persists.
Please, guys, help me fix this issue, because I really need Voice Notes on my laptop (I use them more on the notebook than the smartphone) 😥
Maybe I can create a file log or something similar to send you, in order to find the reason of this problem

**Comment by dogancelik** [comment]
I have the same issue. Unlike OP, I have desktop PC, not laptop.

I tried going back to old versions to restore that microphone icon but it didn't work.
I went back as old as version 1.4.8, the microphone is not there anymore. (I had it before)
![telegram 148](https://user-images.githubusercontent.com/486818/53303542-87fb3c00-387c-11e9-8261-0950a4732fbb.png)

I have 2 microphones (headset and webcam) and for some reason, Telegram can't see either.
I don't have any microphone issue with any other program.

**Comment by MariuxReloaded** [comment]
> I have the same issue. Unlike OP, I have desktop PC, not laptop.
> 
> I tried going back to old versions to restore that microphone icon but it didn't work.
> I went back as old as version 1.4.8, the microphone is not there anymore. (I had it before)
> ![telegram 148](https://user-images.githubusercontent.com/486818/53303542-87fb3c00-387c-11e9-8261-0950a4732fbb.png)
> 
> I have 2 microphones (headset and webcam) and for some reason, Telegram can't see either.
> I don't have any microphone issue with any other program.
> 
> **System settings:** Windows 10 Pro (64-bit), version 1809, build 17763.316

Yeah, that's exactly my same problem!
I imagine your other apps and programs installed on your desktop PC can detect your mic, am I right?
This is a really strange problem 😕

**Comment by reverser69** [comment]
hi 
had the same problem and fixed it 
setting--->sound---->microphone privacy setting--->allow apps to access mic == ON

**Comment by MariuxReloaded** [comment]
> hi
> had the same problem and fixed it
> setting--->sound---->microphone privacy setting--->allow apps to access mic == ON
> win 10 1809

I've already enabled everything there, but nothing's changed 😥

**Comment by MariuxReloaded** [comment]
BTW, If I perform the mic test in the Calls section of Telegram Desktop settings, it is detected without any problems by the program.
WTF?!

![Senza titolo-1](https://user-images.githubusercontent.com/46523668/55234921-79fa5b80-522c-11e9-9339-76a2669b9211.jpg)

**Comment by RazorSiM** [comment]
Can confirm, i have the same porblem. Latest Telegram Desktop version and a Matebook X Pro

**Comment by MariuxReloaded** [comment]
> Can confirm, i have the same porblem. Latest Telegram Desktop version and a Matebook X Pro

And, for the third time since I've bought this amazing laptop, I've performed a clean installation of Windows 10 and the problem is still there 😣
As I've already underlined, all other apps and win32 programs can detect the mic, while Telegram detects it just for voice calls, but not for Voice Notes

**Comment by RazorSiM** [comment]
> > Can confirm, i have the same porblem. Latest Telegram Desktop version and a Matebook X Pro
> 
> And, for the third time since I've bought this amazing laptop, I've performed a clean installation of Windows 10 and the problem is still there 😣
> As I've already underlined, all other apps and win32 programs can detect the mic, while Telegram detects it just for voice calls, but not for Voice Notes

I formatted and installed Win 10 Pro ( i need hyper-v ) so mine is a clean install. The hotkey works as intended for the microphone and it works in voice call test.

Let's wait for any workaround :)

**Comment by MariuxReloaded** [comment]
> > > Can confirm, i have the same porblem. Latest Telegram Desktop version and a Matebook X Pro
> > 
> > 
> > And, for the third time since I've bought this amazing laptop, I've performed a clean installation of Windows 10 and the problem is still there 😣
> > As I've already underlined, all other apps and win32 programs can detect the mic, while Telegram detects it just for voice calls, but not for Voice Notes
> 
> I formatted and installed Win 10 Pro ( i need hyper-v ) so mine is a clean install. The hotkey works as intended for the microphone and it works in voice call test.
> 
> Let's wait for any workaround :)

I've opened this thread about 4 months ago and no workaround or solution has ben proposed ☹

**Comment by dogancelik** [comment]
I don't know what's changed but the microphone icon came back in this version. (`1.7.8 beta`)

![icon](https://user-images.githubusercontent.com/486818/59722587-b7b7c080-922c-11e9-9aaa-26c0848ca48f.png)

**Comment by MariuxReloaded** [comment]
> I don't know what's changed but the microphone icon came back in this version. (`1.7.8 beta`)
> 
> ![icon](https://user-images.githubusercontent.com/486818/59722587-b7b7c080-922c-11e9-9aaa-26c0848ca48f.png)

Good for you, because I've installed version 1.7.8 beta on my Matebook X Pro and nothing has changed 😢

**Comment by Aokromes** [comment]
maybe... try deleting sound card drivers or hand updating them....

**Comment by MariuxReloaded** [comment]
> maybe... try deleting sound card drivers or hand updating them....

I've already tried to do so many times, but nothing has changed...
Exactly today I was thinking about this thread, while my hope for a fix is fading 😢
It is clear that this is a problem of Telegram Desktop itself, since all the other programs and apps of Windows 10 installed on my Matebook X Pro which need the mic are working fine since the day one

**Comment by MariuxReloaded** [comment]
I've formatted my laptop and clean installed the new Windows 10 November 2019 Update and, at last, the mic icon and, consequently, the possibility to send Voice Notes on Telegram Desktop have appeared! 😁😁😁
I can't explain why now and not before, but finally the nightmare is over, so I declare this thread officially closed 😊
