### ISSUE TITLE
Japanese and Chinese IME input candidates unexpectedly covers the input text

### ISSUE THREAD

**Issue by nakata0705** [telegramdesktop/tdesktop#5569]
### Steps to reproduce
1. Enter multiple lines with Japanese or Chinese IME activated. In this step, the IME candidates is displayed below the text being input.
2. Delete all lines and empty the input text box.
3. Enter text again with Japanese or Chinese IME activated.
4. Now, the Japanese or Chinese IME input candidates cover the input text unexpectedly.
5. Once this symptom occurs, I have to move the window focus to another window to fix this symptom. This behavior makes it quite difficult to use multiline chat.

### Expected behaviour
The IME candidates don't cover the input text.

### Actual behaviour
The IME candidates cover the input.

See the animated GIF below for the actual behavior.
![telegrambug](https://user-images.githubusercontent.com/11699525/50991069-18bbc980-1514-11e9-8866-9072fece3507.gif)

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.4.3

**Used theme**: Classic

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@nakata0705 This is how Qt input fields work, sorry. Perhaps this will be better in the more recent versions of Qt, but I can't update to them right now.

**Comment by nakata0705** [comment]
Thank you for the response. Is this the QT bug in your mind?
https://bugreports.qt.io/browse/QTBUG-51923

**Comment by john-preston** [comment]
@nakata0705 I don't have any, but this looks similar.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by nakata0705** [comment]
I checked the behavior with Telegram Desktop 1.9.8 and it showed the exact behavior as I reported.
So this bug is still valid.

**Comment by Aokromes** [comment]
try on 2.1 plz.

**Comment by Osewa-Developer** [comment]
I checked with Windows 10 + Telegram Desktop 2.1. The issue still exists. Please take a look below.
This time I tried both Microsoft Japanese IME and Microsofy Pinyin (Chinese).

Microsoft Japanese IME
![Telegram Desktop 2 1 with MS IME (JP)](https://user-images.githubusercontent.com/63663954/80307453-67ed4280-87c9-11ea-8c81-3abedbca089f.gif)

Microsoft Pinyin (Chinese)
![Telegram Desktop 2 1 with MS Pinyin (CN)](https://user-images.githubusercontent.com/63663954/80307460-7b001280-87c9-11ea-8b46-01ef93c09a11.gif)
