### ISSUE TITLE
Non-ascii passes are not recognized in linux

### ISSUE THREAD

**Issue by Yanpas** [telegramdesktop/tdesktop#557]
I have path to my app /home/yanpas/Документы/Дистрибутивы/Telegram/, but in the launch file (telegramdesktop.desktop) it is shown as
 home/yanpas/ÐÐ¾ÐºÑÐ¼ÐµÐ½ÑÑ/ÐÐ¸ÑÑÑÐ¸Ð±ÑÑÐ¸Ð²Ñ/Telegram so it is unable to launch it from menu.

**Comment by Vdragon** [comment]
I can confirm this issue.  I installed Telegram to /home/Vdragon/軟體/Telegram but the Exec field in the generated freedesktop.org desktop entry is "/home/Vdragon/è»é«/Telegram/Telegram -- %u" instead.

Recommended rename this issue to "Incorrect-path freedesktop.org desktop entry installed when Telegram launched in a path contains non-ASCII characters"

**Comment by Vdragon** [comment]
AFAICS the problem is at https://github.com/telegramdesktop/tdesktop/blob/ad04bf77d1c95a9f53dc9dbf7d12b8e12746e759/Telegram/SourceFiles/pspecific_linux.cpp#L1658

It shouldn't use toLocal8Bit() method to convert the string, maybe toUtf8() instead.
