### ISSUE TITLE
System tray icon does not works with custom icons in Linux

### ISSUE THREAD

**Issue by vmorenomarin** [telegramdesktop/tdesktop#5570]
In recently update, beta 1.5.7, system tray icon does not work with custom icons in Linux. The custom icons that I have build are stored in _ticons_ directory, but only the default blue icon appears in system tray.

![image](https://user-images.githubusercontent.com/13444664/51039593-86530e80-1583-11e9-9c1b-6af86c7c494b.png)
With custom icons.

![image](https://user-images.githubusercontent.com/13444664/51039454-5b68ba80-1583-11e9-917f-a62b798cbe34.png)
After last beta update.

**Comment by john-preston** [comment]
@vmorenomarin I had to change the name from ico to icon because of the #5525.

**Comment by vmorenomarin** [comment]
Fixed. Thanks!!
