### ISSUE TITLE
Segmentation Fault while starting to upload file

### ISSUE THREAD

**Issue by kmahyyg** [telegramdesktop/tdesktop#5572]
### Steps to reproduce

After solved #5422 by myself.  Neither using `proxychains` nor the proxy feature inside the TG, trying to upload from `/media/username/mountpoint/example.test` (mounted a partition in HDD here, test file filesize 17 MiB, Permission 0644, Owner UID=GID=0 or Owner UID=GID=1000 is okay) will cause SEGV.

But, the same file copied to `/tmp` still cannot be uploaded.

Using the `sudo dd if=/dev/urandom of=/tmp/test.test bs=1M count=20` generated a `test.test`
 can be successfully uploaded.

### Expected behaviour

Works fine.

### Actual behaviour

SEGV terminated.

### Configuration

**Operating system:** Arch Linux with all packages instelled latest without using any package in `testing`

**Version of Telegram Desktop:**  1.5.4-2

**Used theme**: Default

**Log File & Console Output & GDB Coredump** can be found here:

https://transfer.sh/hoKNm/tgbug154.tar.gz (MD5: 7ed706417ceeb13cd1e45567cb5269fd)

Link Available in 14 days since the issue opened.

If the file is not available, please leave a comment here.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by kmahyyg** [comment]
Cannot confirm the origin. According to multiple origin, seems caused by a bug in Qt network library. This bug cannot reproduce since program updated.
