### ISSUE TITLE
Linux Mint 19.1 Cinnamon Icon Bug

### ISSUE THREAD

**Issue by BoostRacerKing** [telegramdesktop/tdesktop#5575]
Hallo erstmall ich kann leider kein Englisch aber wenn ich bei Telegram meine benachrichtigung ansehe und an der Taskleiste Unten Rechts kommt da so ein Darstellungs Fehler bei 400 benachrichtigungen obwohl ich die alle gelesen habe kommt der Fehler immer noch
Wenn ich dan eine neue Nachricht bekomme steht da 1 wenn ich die Nachricht gelesen habe steht da immer noch 400 das ist ein Fehler
ich habe den gleichen fehler auch unter Manjaro Linux Cinnamon

Telegram Version 1.54
 

![bug](https://user-images.githubusercontent.com/31882253/51215722-21e8d400-1922-11e9-9423-989eecd4ab1d.jpg)
![bug2](https://user-images.githubusercontent.com/31882253/51216058-5ad57880-1923-11e9-8042-4424d88ae947.jpg)

**Comment by stek29** [comment]
English please
