### ISSUE TITLE
Win10 Desktop version freezes with high CPU load

### ISSUE THREAD

**Issue by keerah** [telegramdesktop/tdesktop#5579]
Have no idea how to repro, but it's just started to happen today on each run. Within a few seconds after run the telegram window freezes and CPU loaded about 30% constantly, can only kill the process. Reinstalling, resetting the app won't help. At the same time I can see the process "Service Host: Program Compatibility Assistant Service" activated also with noticeable CPU load.
Before the problem I had a high CPU load happened a few times due to the chat with lots of videos

### Configuration
Win 10 64x, latest telegram version

PS Was able to make it working after many restarts

**Comment by john-preston** [comment]
Hi. The next time this happens can you please go to the Task Manager, right click the frozen "Telegram Desktop" and click "Create dump file", then find it (you'll see the information about the dump file location after you click), .zip it, contact me at https://t.me/preston and send it. That way I hope I'll see in the debugger where exactly it froze.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by keerah** [comment]
@Aokromes nope, haven't bumped in this for quite long
