### ISSUE TITLE
Feature Request:  Hidden contacts

### ISSUE THREAD

**Issue by phplego** [telegramdesktop/tdesktop#558]
Sometimes it is very important to hide particular contacts from (boy|girl)fiends. It'd be great feature

**Comment by AryanShadowhunter** [comment]
Agree with you

**Comment by cobalto** [comment]
The are already 3 options avaible:
1) Don't allow your [boy|girl]friend to have phisical access to your desktop.
2) Don't use telegram for these kind of things.
3) Live with the consequences of your actions.

But never mind my opinion.

**Comment by AryanShadowhunter** [comment]
We all want to help, making Telegram the best connecting app ever. And if a program wants to be the best, it must pay attention to any ideas offered, even it is not crucial or based on details.

**Comment by joshery420** [comment]
@phplego Unless you both use the same Telegram account on the same desktop (not sure how to solve your problem if that's the case), but if that's not the case at least for now you can PIN lock the desktop app.

This doesn't hide a specific contact (which I have no idea how that'd even work. If the person is hidden from her, it's hidden from you. -_-) but it doesn't prevent other people from looking through your chats.

**Comment by SmartManoj** [comment]
May be he want to hide particular chats?
