### ISSUE TITLE
Telegram Desktop failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by ivan23kor** [telegramdesktop/tdesktop#5581]
### Steps to reproduce
1. Download tsetup.1.5.4.tar.xz from [here](https://desktop.telegram.org/)
2. run '''tar xz tsetup.1.5.4.tar.xz'''
3. Failure is depicted on the image attached

### Expected behaviour
Telegram Desktop running

### Actual behaviour
Failure with an empty log

### Configuration
Ubuntu 16.04

**Version of Telegram Desktop:**
1.5.4

![image](https://user-images.githubusercontent.com/14425140/51284173-a9eedc80-19fb-11e9-90d6-26dae739e4b9.png)

**Comment by Aokromes** [comment]
i suppose this bug was fixed long time ago.
