### ISSUE TITLE
I need to separate conversation type, and have separate tab for Messages, Groups, Channels, Bots.

### ISSUE THREAD

**Issue by NabiKAZ** [telegramdesktop/tdesktop#5582]
I need to separate conversation type, and have separate tab for Messages, Groups, Channels, Bots.
Why don't implement this features?

**Comment by RememberTheAir** [comment]
Duplicate of other 100000 issues, use search next time

**Comment by NabiKAZ** [comment]
Oh sorry for dublicated, seem there are many issue for this:
https://github.com/telegramdesktop/tdesktop/issues/4463
https://github.com/telegramdesktop/tdesktop/issues/3416
https://github.com/telegramdesktop/tdesktop/issues/2511

But, Why don't implement this?

**Comment by Aokromes** [comment]
you can close the ticket yourself, reason is durov brothers doesnt like them
