### ISSUE TITLE
[LINUX] Hight CPU usage on open file action

### ISSUE THREAD

**Issue by fotonmoton** [telegramdesktop/tdesktop#5583]
When I try to open file CPU spikes to 100% and nothing happens after. I think this is because I doesn't have GUI app that can open downloaded file (I try to open zip archive and I doesn't have GUI file manager nor GUI archive manager).

![image](https://user-images.githubusercontent.com/7763084/51388864-5b445e00-1b33-11e9-822a-a720ba558ff9.png)

### Steps to reproduce
1. Download and try to open file (in my case it is zip archive)
2. Open process monitoring utility and see spike in CPU usage (in my case it is `less` process tries to view some file in tmp directory)
3. ?????
4. PROFIT!

### Expected behavior
Maybe some pop up or something indicating that file can't be open or should be opened in some another app. Also no process with 100% CPU load should continuously run in background. 

### Actual behavior
`less` takes 100% of CPU.

### Configuration
**Operating system:**

```
uname -a
Linux machine 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

**Version of Telegram Desktop:**
1.5.4
**Used theme**:
default night theme

**Comment by fotonmoton** [comment]
Seems like problem in `xdg-open` and here is related [issue](https://superuser.com/questions/1007807/xdg-open-hogging-the-cpu-by-forking-itself-endlessly).

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by fotonmoton** [comment]
@Aokromes, don't think so
