### ISSUE TITLE
Blocked user chat still visible in group

### ISSUE THREAD

**Issue by urbanhusky** [telegramdesktop/tdesktop#5584]
Blocked users still appear in group chats.

_But not seeing what they have written breaks context in discussions and replies!_
That never really was a problem in IRC and I'd argue that this is more of a constructed issue. 
Plus, we've got more UI/UX options now: instead of completely hiding their presence, hide their text and  replace it with a de-emphasised placeholder text like "user is blocked" - maybe even allow a "show hidden text" to check what they have written - or something like that.

But please, don't leave me with the options of either leaving the group completely (not acceptable) or still having to deal with that user.

**Comment by stek29** [comment]
#1025
