### ISSUE TITLE
i got an error when calling gyp\refresh.bat

### ISSUE THREAD

**Issue by Painkiller1991** [telegramdesktop/tdesktop#5585]
i do everything like https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md

but in the last line when i call "gyp\refresh.bat --api-id 17349 --api-hash 344583e45741c457fe1862106095a5eb"

i get below error:
gyp: ..\ThirdParty\libtgvoip\libtgvoip.gyp not found (cwd: c:\Users\Public\TBuild\tdesktop\Telegram\gyp)
[ERROR] Failed generating for format: ninja
FAILED

what should i do now?

**Comment by john-preston** [comment]
@Painkiller1991 You should run git submodule init and then git submodule update.

**Comment by Painkiller1991** [comment]
@john-preston  thanks it is work :-)
