### ISSUE TITLE
[Linux] Groups- can't see writer's name 

### ISSUE THREAD

**Issue by stzahi** [telegramdesktop/tdesktop#5587]
### Steps to reproduce
1. Enter a group
2. Look at a message
3. 

### Expected behaviour
Should see the writer's name at the bottom right corner of the message

### Actual behaviour
I can only see the time the message was written, can't see the writer's name.

### Configuration
**Operating system: Ubuntu**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stzahi** [comment]
:(

**Comment by aNNiMON** [comment]
This feature is available for channels with 'Sign messages' option enabled, not for groups.

**Comment by stzahi** [comment]
I don't understand,
In Windows client, as well as in Android client, You can see the writer's name. Only in Linux desktop I can't see it.

**Comment by RememberTheAir** [comment]
@stzahi could you post some screenshots describing the issue?

**Comment by Aokromes** [comment]
no answer after more than 6 months, and on groups on linux i can see who posted the text. closing.
