### ISSUE TITLE
Message Not Show in Offline Mode

### ISSUE THREAD

**Issue by jahmadiiiii** [telegramdesktop/tdesktop#5588]
### Steps to reproduce
1. Make sure your Device Offline.
2. Open Telegram Desktop.
3. Nothing Show

### Expected behaviour
Messages,Channels and Groups Must Show in Offline Mode.

### Actual behaviour
Nothing Show When you Offline.

### Configuration
**Operating system:Windows 10 1809**

**Version of Telegram Desktop:1.5.7**

**Used theme**:Default Telegram Theme When Telegram Installed.

<details><summary><b>Note:This bug affect all version Of Telegram Desktop in Windows and Linux(Stable and Alpha Versions).
Mac OS have not this problem. </b></summary>

</details>

**Comment by lampanon** [comment]
This is absolutely intended. 
Telegram Desktop does not have a local message database, it works as web version: on launch it loads current messages from server, without storing them anywhere on the hard drive between relaunches.
