### ISSUE TITLE
Really old messages are disappearing

### ISSUE THREAD

**Issue by 44trent3** [telegramdesktop/tdesktop#5589]
### Steps to reproduce
1. Open Telegram chat with a shit ton of messages
2. Go back really far
3. Notice that messages are missing and you can't go back anymore even though there are indeed more messages

### Expected behaviour
Tell us what should happen
Uhm, well the expected behavior is to have all the fucking messages. The weird thing is I get this expected behavior on a chat in private message with a load of messages - though I'm not for sure. I checked a personal chat and I have about 1.5mln messages, but the group never exceeds 1.1 million.
### Actual behaviour
Older messages disappear for some reason.

### Configuration
**Operating system: Windows 10**

**Version of Telegram Desktop: 1.5.7 beta, issue appeared on non beta versions as well**

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

One other thing to note: this has been ongoing since August 2017, and I've lost a tonne of messages. Should have reported this sooner. Or idk maybe it's a feature.

**Comment by stek29** [comment]
It's an old api issue, which was partially fixed.
First of all, all of your messages should be available in user to user dialogues and in normal groups.

Channels and supergroups still have 1 million messages limit, but you can export chat history to get older messages.

**Comment by john-preston** [comment]
@stek29 Unfortunately right now in supergroups and channels even exporting a single chat doesn't allow you to access more than 1 mln messages.

**Comment by 44trent3** [comment]
So when is it going to be fixed?

**Comment by alexalder** [comment]
Any news?

**Comment by 44trent3** [comment]
Any news?
