### ISSUE TITLE
Native Notification option gone if Telegram autostarts

### ISSUE THREAD

**Issue by null-von-sushi** [telegramdesktop/tdesktop#5590]
### Steps to reproduce
1. Autostart Telegram
2. Receive a message

### Actual behaviour
Telegram draws it's own notification instead of using the native notification system. 
Also, the native notification toggle in the Telegram settings is gone.

### Expected behaviour
Telegram should continue to use native notifications if that option was previously set.
The option should not disappear either.

### Workaround
Fully quit and restart telegram manually.

### Configuration
**Operating system:** Antergos Linux (Arch Based)

**Desktop Environment:** KDE Plasma 5.14.5

**Version of Telegram Desktop:**
1.5.4

**Used theme**:
On Telegram?
Arc-2 Bright

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by null-von-sushi** [comment]
I think so yes. It's nearly a Year since this bug was posted, so I am not 100% sure what my system configuration at the time was.
I am fairly confident it's a race condition at login between telegram starting and a notification daemon starting though. 

If I kill latte-dock (which is responsible for drawing notifications for me, I think), restart telegram it will use it's own style. Even if latte-dock is started later on, telegram will use it's own notifications. I worked around it by having telegram start with `sleep 5 && telegram-desktop` for now (though that's obviously not a real fix).

It is worth noting that closing telegram, and relaunching it does re-enable native notifications without the user having to manually enable it again, which is nice. So I guess it's either the default now, or it remembers our preferences even if they become 'invalid' for a certain period of time.

**Comment by Storm-Engineer** [comment]
Interestingly this bug only started happening for me at the end of January this year, even though it was reported here over a year ago.
So the trail of tickets leading me here for additional information: #7130  #7308

**Comment by chaptergy** [comment]
Unfortunately I'm having the same issue. Is there a plan when merge request #7321 will be included in the official release? Or which version will contain this fix?

**Comment by Aokromes** [comment]
> Unfortunately I'm having the same issue. Is there a plan when merge request #7321 will be included in the official release? Or which version will contain this fix?

it was merge on 6 march.

**Comment by chaptergy** [comment]
So it was merged to master right away as well and should have been fixed in v1.9.20? Because I'm on version 2.1 and still experiencing this issue.

**Comment by Storm-Engineer** [comment]
Issue still present, BTW... looks like this will never get fixed. :/

**Comment by fopor** [comment]
Sill present on Arch

**Comment by ilya-fedin** [comment]
> Issue still present, BTW... looks like this will never get fixed. :/

This should be fixed on KDE side, KDE shouldn't start Telegram until notification daemon is started.

**Comment by the-Mitu** [comment]
I'm experiencing this issue as well on Kubuntu 20.10 + Telegram installed from Snap package. If it is to be fixed on KDE's side has anyone reported it or know which KDE project should it be reported for?
