### ISSUE TITLE
Group converts to supergroup automatically

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#5593]
### Steps to reproduce
1. Create new group
2. Add new administrator and give him permission "Add new admins", click "SAVE"

### Expected behaviour
Basically nothing

### Actual behaviour
The group converts to a supergroup:
1. Group icon color changes to some new random color(not part of supergroup functionality, just a sign of conversion)
2. "Delete group" button appears in "Group info"
3. "Recent actions" appears in "Manage group" with all service messages for last 48 hours
4. No ability to delete messages "just for you" anymore, only for everyone(but you still have this option for messages which you have sent before conversion)
5. Admins' messages are now marked by 'admin' sign in the top right corner
6. Ability to "report" messages(which is strange for private group)
7. "Removed users" button appears in "Manage group" -> "Permissions"

With last update there is no more difference between groups and supergroups("As of today, supergroups and basic groups are simply groups."), but when you create new group, TECHNICALLY it's still a group, and when you perform some supergroup-related actions(toggle chat visibility for example), it converts to a supergroup.

I suppose when you create new group now, after this update, telegram should create a supergroup from the start. Am I correct? Have I found a bug or this is all part of the plan?

I know it's not possible to convert a supergroup back to a group, but maybe we can have an option to delete messages in a supergroup just for yourself? Some users may not like what others send and they want to delete it, but now you can't do it anymore and have to see all the messages you don't want to see.

### Configuration
**Operating system:** Windows 7 64bit

**Version of Telegram Desktop:** 1.5.8

**Used theme**: Classic

**Comment by RememberTheAir** [comment]
> I suppose when you create new group now, after this update, telegram should create a supergroup from the start. Am I correct? Have I found a bug or this is all part of the plan?

It's intended. New groups starts as normal groups. There are [a bunch of actions](https://t.me/tgbetachat/59941) that trigger the conversion to supergroup, which is silent and hidden to users. It introduces some inconsistent behaviors when deleting messages/being kicked from a group, yes

**Comment by imashxtyz** [comment]
If I create a legacy group and do nothing of what will convert it to a supergroup, will it be converted automatically in future, I mean, does telegram plan to sometime just convert all unconverted groups or legacy groups will be here forever?

Also, sorry this is a bit unrelated, but is there a place where I can request features or suggest some improvements for telegram? I tried to send a message to support, but they rarely answer.

And why do we need "report" button for messages in private groups? Legacy groups don't have those.

**Comment by Sutarat66** [comment]
เมื่อ อ. 22 ม.ค. 2562 เวลา 19:36 imashxtyz <notifications@github.com>
เขียนว่า:

**Comment by treeshateorcs** [comment]
how do i convert a group chat to a supergroup manually? i can't find a howto anywhere on the internet

**Comment by RememberTheAir** [comment]
@treeshateorcs see [this](https://github.com/telegramdesktop/tdesktop/issues/5593#issuecomment-456356552) comment

**Comment by omzy** [comment]
Can there not be a confirmation prompt to advise the user that the group will be converted to a supergroup whenever the specific action is carried out? Instead of doing it silently?

**Comment by RememberTheAir** [comment]
@omzy the idea is that the user shouldn't know there are two underlying kind of group chats. Everything have to look like every group is a supergroup

**Comment by omzy** [comment]
Yes but for simple group chats, i.e friends / family, a normal group is sufficient. I had a normal group with only 4 people, I made some changes to a user permission and the group was automatically upgraded to a supergroup. I only realised this had happened with the "admin" label started appearing next to people's names - which is annoying in itself.

> Everything have to look like every group is a supergroup

Then why doesn't it just start as a supergroup in the first place?

**Comment by mirh** [comment]
> had happened with the "admin" label started appearing next to people's names - which is annoying in itself.

Speaking of which, I eventually figured out that you can indeed customize that label, which is pretty dope. 
But last time I checked, you couldn't use "*empty space*" inside of it.

**Comment by RememberTheAir** [comment]
> I only realised this had happened with the "admin" label started appearing next to people's names - which is annoying in itself.

I agree. Totally unneeded in small chats with friends or family

> Then why doesn't it just start as a supergroup in the first place?

There's a server-side limit that doesn't allow an account to join more than 500 supergroups or channels, while there is no known limit of how many normal group chats you can be member of. I guess that's one of the main reason (not having to display a "sorry, leave some chats before creating a new one" error if an user tries to create a group chat), maybe there are other reasons but I can't remember them. Anyway, if they'll ever remove this limit, new group chats will probably be supergroups by default
