### ISSUE TITLE
Bug Inline Bots

### ISSUE THREAD

**Issue by RowanFazio** [telegramdesktop/tdesktop#5594]
### Steps to reproduce
1. Open an inline bot
2. Search a text

### Expected behaviour
If there is an [InlineQueryResultMpeg4Gif ](https://core.telegram.org/bots/api#inlinequeryresultmpeg4gif)result. TDesktop It does not show it.
In iOS and Android is OK!

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.5.8 Beta

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by nikashitsa** [comment]
I have same bug with @memingbot for InlineQueryResultPhoto (MacOS version 1.5.11). On mobile all works fine.

I can view results, but can't send any of it 😥.
![1](https://user-images.githubusercontent.com/1029908/52407116-95cd6500-2af9-11e9-997b-7d3c2e5c33e1.png)
But this trick works for me: 1) Click and hold on one photo result.
![2](https://user-images.githubusercontent.com/1029908/52407123-982fbf00-2af9-11e9-94a2-d36880a42cf4.png)
2) Add more spaces to query, wait new results. 
![3_more_spaces](https://user-images.githubusercontent.com/1029908/52407127-9960ec00-2af9-11e9-91b5-9f6bae4d497b.png)
3) Now I can send only photo result which I clicked at step 1.

@john-preston please have a look 😇. This happened in last releases.
