### ISSUE TITLE
Always one unreaded on taskbar (Windows)

### ISSUE THREAD

**Issue by martalopes** [telegramdesktop/tdesktop#5596]
### Steps to reproduce
1. Open Telegram Desktop application and minimize
2. Receive a message and the Telegram icon on the taskbar now has a notification (a "1")
3. Open Telegram and read the message and the message appears read on Telegram
4. Minimize Telegram (optional)

### Expected behaviour
The "1" on the Telegram icon on taskbar has to disappear after the message is read .

### Actual behaviour
The Telegram icon on taskbar still has a "1" like a message is still unread.
### Configuration
**Operating system:** Windows 10 

**Version of Telegram Desktop:** 1.5.8

**Used theme**: Midnight (Night mode on)

**Comment by Sutarat66** [comment]
เมื่อ อ. 22 ม.ค. 2562 เวลา 18:56 Marta Lopes <notifications@github.com>
เขียนว่า:

**Comment by esadykov** [comment]
Sometime have the same issue.
But realy have one unread message from Telegram channel:
![image](https://user-images.githubusercontent.com/5658629/52112229-f00c8880-2616-11e9-892d-ca28ec61c4dd.png)
Channel last message date not updated and Telegram-channel in bottom of contact list. Looks lake orignal issue.
