### ISSUE TITLE
Support for custom emoji fonts

### ISSUE THREAD

**Issue by frebib** [telegramdesktop/tdesktop#5598]
Now there is support for emoji packs other than the (horrible) Apple default (which is named incorrectly btw), it would be nice to have support for loading the system default pack/selecting a font to provide emoji support. I personally use Noto emoji and would like that to be uniform in Telegram Desktop too

**Comment by john-preston** [comment]
@frebib Android from the list is noto, similar to what you can find here: https://github.com/googlei18n/noto-emoji/tree/master/png/128

**Comment by frebib** [comment]
Ok great, thanks.

I'd still prefer the functionality to be able to use the system font over the hard-coded defaults

**Comment by john-preston** [comment]
@frebib Emoji are not rendered by a font in tdesktop, it requires specific graphic sprites, that were prepared by hand for the available four emoji sets :(

**Comment by frebib** [comment]
That's disappointing and entirely unsurprising from this software

**Comment by frebib** [comment]
@stek29 why did you close this issue? No fix was implemented
