### ISSUE TITLE
Changing the photo of chanels

### ISSUE THREAD

**Issue by afentev** [telegramdesktop/tdesktop#5601]
To reproduce this bug you should open any public (or private, i dunno) channel where you aren't an admin and place the cursor to the avatar of the channel. There would be a button with white camera. And when you press this button, the window with file choice opens. So you can choose any photo-like file and "update" and avatar in channel. But in fact your photo won't set. Sorry for my eng
Если есть возможность прочитать по-русски, то пишу. Нужно открыть канал, где ты не являешься админом. При наведении курсора на аватарку канала появляется возможность ее обновить. Открываются меню выбора файла, но после выбора аватарка не обновляется. В любом случае, мне кажется, что даже такое поведение не совсем правильное.

I think that in the best case there shouldn't be an ability to update channel photo (if you aren't admin of the channel or don't have necessary permissions)

Upper
<img width="189" alt="1" src="https://user-images.githubusercontent.com/27886622/51560443-988f4f80-1e95-11e9-9795-2716bf3812f0.png">

### Configuration
Windows 10 Proffesional (64)

**Version of Telegram Desktop:** 1.5.8

**Used theme**: classical white

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by MasterGroosha** [comment]
Maybe it has the same "core" bug as #5592, so just referencing it

**Comment by afentev** [comment]
> Maybe it has the same "core" bug as #5592, so just referencing it

This bugs are very akin itself, but in fact they are different, because #5592 author wrote about title and description, not about photo

**Comment by MasterGroosha** [comment]
They're similar, since you are able to do some "admin" actions on non-yours chats. That's why I tied them both
