### ISSUE TITLE
Reply preview became awfully blurry in 1.5.8

### ISSUE THREAD

**Issue by Remu-rin** [telegramdesktop/tdesktop#5602]
### Steps to reproduce
1. Find or make a reply to message with photo or link with image in preview (stickers are not affected)
2. Look at image in reply preview

### Expected behaviour
Preview should be as clear as possible.

### Actual behaviour
Horrible quality. Example of https://t.me/tginfochat/587912 in 1.5.7 and 1.5.8:
![screen](https://user-images.githubusercontent.com/28995228/51561482-350f1d00-1ea9-11e9-8e08-517657bb079d.png)

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.5.8

**Used theme**: Matrix

**Comment by Remu-rin** [comment]
Preview slides at the bottom when you open albums are affected too.

**Comment by john-preston** [comment]
Thanks! I'll fix that in the upcoming version.

**Comment by Remu-rin** [comment]
@john-preston 
Thanks for the fix. But now it seems that when opening albums tdesktop downloads another thumbnails for slides at the bottom. This adds noticeable delay. Is it not possible to use already downloaded full images of album for slides at the bottom like previously (1.5.7)?
