### ISSUE TITLE
Wrong unread count in tdesktop after reading on mobile device

### ISSUE THREAD

**Issue by goonis** [telegramdesktop/tdesktop#5603]
### Steps to reproduce
1. find some channel with enough unread messages in tdesktop (for ex. 200), do not open it.
2. open this channel in telegram for android or ios.
3. this channel unread counter in tdesktop drops to 1-3.
4. restart tdesktop.
5. unread counter again shows around 200.

### Configuration
**Operating system:**
Windows 

**Version of Telegram Desktop:**
1.5.4, 1.5.8

**Comment by RememberTheAir** [comment]
I can confirm, this is still happening on 1.6 too. Doesn't seem to be an API issue because Telegram for Android, Telegram for iOS and Telegram X all show the correct number of unread messages left to read, after partially reading some messages from one of the mobile apps

**Comment by RememberTheAir** [comment]
Bump. This is actually pretty damaging for communications, the number of times I missed some important messages/informations because of tdesktop's wrong unread count is starting to become too high, to be honest

**Comment by nuclight** [comment]
This is probably server bug as I can confirm this on version 1.1.26 which is old enough, but I don't remember such behaviour till last winter.

**Comment by john-preston** [comment]
@nuclight This is tdesktop bug, but it was always there. Before mobile apps were "marking as read" full history when chat was opened, so it worked fine. But after that they've started "reading" only messages that got on the screen and tdesktop started showing wrong unread counters. This will be fixed in the next version.

**Comment by goonis** [comment]
Looks like fixed for me in 1.7, now we really need fix for https://github.com/telegramdesktop/tdesktop/issues/775
