### ISSUE TITLE
Tomorrow's post scheduled after tomorrow (day after schedule time)

### ISSUE THREAD

**Issue by kenorb** [telegramdesktop/tdesktop#5604]
### Steps to reproduce
1. I've created a _New Post to Subscribers_.
2. I've Scheduled post for tomorrow.
3. The post was set 2 days after.

So on 22.01.19 at 14:39, the conversation was like:

```
Ata, [22.01.19 14:39]
When do you want to send your post?

Ata, [22.01.19 14:39]
Enter the time of the post in HH:MM format (e.g. "22:40"). Append am/pm in case of 12-hour format (e.g. "10:40 pm").

kenorb, [22.01.19 14:39]
Tomorrow

Ata, [22.01.19 14:39]
You selected 2019-01-24 10:00. Press Save to schedule post.

kenorb, [22.01.19 14:39]
10:00 am

Ata, [22.01.19 14:39]
Done! Your post will be sent at the scheduled time.

kenorb, [22.01.19 14:39]
Save
```

### Expected behaviour
It is scheduled on 2019-01-23 10:00.

### Actual behaviour
It was scheduled on 2019-01-24 10:00.

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** v1.5.4
**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

Not sure how to find `log.txt`.

If this bug belongs to other place (Bot API), please let me know.

**Comment by MasterGroosha** [comment]
How it's related to Telegram Desktop? And since you're using some third-party bot, how is it relevant to Bot API at all?

Neither client API nor Bot API (as far as of now) don't have any methods for scheduling messages, so your issue is simply invalid :(

**Comment by kenorb** [comment]
@MasterGroosha It's the bot created by [@BotFather](https://botsfortelegram.com/project/the-bot-father/). I thought it's the official Telegram bot.

**Comment by MasterGroosha** [comment]
If that particular bot doesn't have verification mark next to its name, then it's not official.

Everyone can create bots using BotFather (in fact, it just generates you API keys for specific username, writing code is up to you)

**Comment by kenorb** [comment]
It has a mark:

![image](https://user-images.githubusercontent.com/266306/51618856-ee600800-1f26-11e9-8cfa-2fed179520f5.png)

I've created the bot using BotFather, then I think my bot got new commands from [Manybot](https://manybot.io/).

So I think this bug could be on their side, thanks. However, as far as I know, they don't have place to report bugs, and they usually don't reply to e-mails (they didn't for me last report).
