### ISSUE TITLE
Cannot search for polls in chat

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#5605]
### Steps to reproduce
1. Try to search for poll in chat as a separate type in Shared Media
2. Try to search for poll in chat by descrtiption or by options

### Actual behaviour
There is no way to search for specific poll or just filter by polls in chat unless you know where to find it.
There is also no separate category in "Shared" section.

I don't see this functionality in vanilla Android app as well, but it's an issue anyway.

### Configuration
**Operating system:** Any
**Version of Telegram Desktop:** 1.5.8

![image](https://user-images.githubusercontent.com/2780044/51608674-37b15700-1f29-11e9-9dd8-a6c7d1d8e52b.png)

**Comment by RememberTheAir** [comment]
Doesn't work from iOS either. I guess this is more an API issue, because polls don't seem to be indexed for the cloud search. Good that you brought this up

**Comment by ArmeF97** [comment]
It would be nice to have it here
![immagine](https://user-images.githubusercontent.com/6240983/51798687-e77f1100-2216-11e9-8452-8b68c61fe40c.png)
The entry "polls"
