### ISSUE TITLE
MediaView does not fill the entire screen. Linux.

### ISSUE THREAD

**Issue by thirtysat** [telegramdesktop/tdesktop#5607]
### Steps to reproduce
1. Start telegram-desktop
2. Open any media (photo, video)
3. Close the view and open it again.

### Expected behaviour
Media viewing should fill the entire screen.

### Actual behaviour
MediaView initially shows everything is normal. All subsequent opening of viewing media files shift view under the taskbar (tint2, xfce4-panel), closing some of the control elements located below. 

If you close Telegram and restart, the first launch of viewing the media will be normal, the subsequent ones will be broken.

### Configuration
**Operating system:** Manjaro XFCE

**Version of Telegram Desktop:** 1.5.8 official

**Used theme**: Any, original or custom

**Screens**:
![_2019-01-23_17-29-45](https://user-images.githubusercontent.com/29095597/51618616-49016000-1f37-11e9-9ffd-e183a444ef1b.png)
![_2019-01-23_17-30-20](https://user-images.githubusercontent.com/29095597/51618617-49016000-1f37-11e9-9baa-6368e4903d28.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5075

**Comment by thirtysat** [comment]
Many thanks, now it works as it should!
