### ISSUE TITLE
No up & down arrows to iterate through search term

### ISSUE THREAD

**Issue by dm17** [telegramdesktop/tdesktop#5609]
### Steps to reproduce
1. Have latest telegram on latest OSX
2. Search in a chat for something
3. Notice there aren't up & down arrows to scroll through results

### Expected behaviour
cntl+F -> search -> click return or search arrows to go to the next result

### Actual behaviour
cntl+F -> search -> no way to go to next search result

### Configuration
**Operating system:**
10.14.2

**Version of Telegram Desktop:**
4.9.155353

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RememberTheAir** [comment]
Wrong repository. Go to https://github.com/overtake/TelegramSwift

**Comment by MasterGroosha** [comment]
Or directly to https://t.me/macswift where developer of mac-swift app collects bug reports

**Comment by stek29** [comment]
This is not TDesktop but a different app -- from https://macos.telegram.org.
You can get TDesktop at https://desktop.telegram.org.
(There are two apps in Mac App Store as well).

You can report issues in the app you're using at https://t.me/macswift, or at https://github.com/overtake/TelegramSwift.
