### ISSUE TITLE
[REGRESSION] Most used emojis feature is not working properly after 0.7.20

### ISSUE THREAD

**Issue by thybak** [telegramdesktop/tdesktop#561]
Hi!

After updating my client to 0.7.20 version and turning on my passcode locking, I saw that *again* most used emojis show up randomly. Is this feature broken?

Thanks for your hard work here guys ;))

**Comment by telegramdesktop** [comment]
Thanks, there is a bug, update to 0.7.20 forgets all the old recent emojis :( But after that they are saved correctly. I will fix that (including update from prev versions) in next updates, thank you.
