### ISSUE TITLE
High CPU usage on video thumbnail loading

### ISSUE THREAD

**Issue by tort-dla-psa** [telegramdesktop/tdesktop#5610]
### Steps to reproduce
1. Post a video link in chat (link to youtube, for exaple)

### Expected behaviour
Video thumbnail should be downloaded without issues

### Actual behaviour
Thumbnail loading is not happening. And CPU usage goes up to 50-60%.

### Configuration
**Operating system:**
Arch linux

**Version of Telegram Desktop:**
1.5.7 beta

**Used theme**:
Night theme

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by tort-dla-psa** [comment]
Well, I just realized that this bug actually happens with ANY image loading, not only video thumbnails. Not cool

**Comment by krautcat** [comment]
а как какать

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by tort-dla-psa** [comment]
> this bug is still valid?
Yep. CPU usage goes up to ~60% on one core

**Comment by ilya-fedin** [comment]
> Yep. CPU usage goes up to ~60% on one core

Well, if you profile this, maybe the issue will be solved
https://stackoverflow.com/questions/2229336/linux-application-profiling
