### ISSUE TITLE
About date format

### ISSUE THREAD

**Issue by taijuin** [telegramdesktop/tdesktop#5612]
![date](https://user-images.githubusercontent.com/1614551/51702907-f5366a00-204f-11e9-9eaf-5665bc1e2112.png)
`"lng_status_lastseen_date_time" = "last seen {date} at {time}";`

I hope it can be:

last seen 2019.01.20 at 上午9:47

I know this question has already been mentioned, but now it is 2019.

**Comment by taijuin** [comment]
Telegram X Android version:

<string name="language_dateFormatLocale">zh-TW</string>

**Comment by Aokromes** [comment]
#1920
