### ISSUE TITLE
spellchecking still not working in 2019 

### ISSUE THREAD

**Issue by ibnzUK** [telegramdesktop/tdesktop#5613]
Seriously, guys, English spellchecker has been requested since 2014 , with the latest update it is still not available on windows desktop version. Can you please advice on when it will be implemented because I see every year request for spellchecker is being closed and ignored? 
Who else do we need to contact??? As it feels like community problems just being ignored. 

Steps to reproduce
Spellchecker, autocorrection or spelling mistake checker not working on Desktop Application.
Spellchecker works well on Skype, Viber, or any other application but not Telegram Desktop.

People around the world using spellcheckers on daily basis, how come this is not integrated or possible. Even operating system provides API for spell checking but telegram desktop application disables it.

So far the only workaround I found was to use web or mobile version, this is crazy.

It has been asked from the community since 2014 and nothing has been done. I did massive research on this subject and from what I can see every community member has been ignored regarding this issue.

Works well on Mac probably even on linux but not Windows OS

There are many API's and solutions but none has been implemented.

https://docs.microsoft.com/en-us/windows/desktop/api/spellcheck/nf-spellcheck-ispellchecker-comprehensivecheck
https://docs.microsoft.com/en-us/windows/desktop/Intl/spell-checker-api
https://github.com/KDE/sonnet
Expected behaviour
It should underline misspelt words and help with choosing the right words on mouse click

Actual behaviour
does nothing. not even windows spellchecker works in telegram desktop

Configuration
windows 7 8 8.1 10

Version of Telegram Desktop:
All versions of Telegram Desktop

Used theme:
all themes

**Comment by ibnzUK** [comment]
> #96

yeah since 2014 nothing has been done, thanks for pointing.

**Comment by AdKiller** [comment]
safe to say it is never going to be added...

**Comment by rx65m** [comment]
So what is our best option currently? Please! Anyone suggesting?

**Comment by enzogian** [comment]
Hi, yes please this is a very important feature.. is leaving telegram users behind.. pleaaseee.. !
Thanks

**Comment by Aokromes** [comment]
stop posting on a duplicate ticket. the other ticket is open, and anyone can takeover one pull request and make a new pull request to implement this.

**Comment by enzogian** [comment]
sorry I am not so familiar with github so got confused on the interface
etc..
thanks though

**Comment by dmitrii-badretdinov** [comment]
> 
> 
> stop posting on a duplicate ticket. the other ticket is open, and anyone can takeover one pull request and make a new pull request to implement this.

https://github.com/telegramdesktop/tdesktop/issues/96#issuecomment-234671116
?

**Comment by enzogian** [comment]
read my reply, I have apologized for it so please stop sending me this
warning !!!!
