### ISSUE TITLE
Bugged caching behavior for some types of media in 1.5.8

### ISSUE THREAD

**Issue by Remu-rin** [telegramdesktop/tdesktop#5616]
### Steps to reproduce
1. Disable automatic downloading of voices, gifs and round videos
2. Go to chat and click to download voice, gif or round video
3. Observe where client saves data. Or manually check files in download folder (`Download path` setting) and size of cache folder in tdata before and after clicking

### Expected behaviour
In 1.5.7 and earlier voices, gifs and round videos (also photos) were saved in tdata folder. Videos, files and audio were saved in download folder. In 1.5.8 everything is normal only with enabled auto download.

### Actual behaviour
In 1.5.8 with auto download disabled, voices, gifs and round videos are duplicated in both tdata and download folder. Also clearing cache in `Manage local storage` deletes them only in tdata, but not bugged duplicates in download folder.

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.5.8

**Used theme**: Matrix

**Comment by john-preston** [comment]
Should be fixed in 1.5.12.
