### ISSUE TITLE
EmojiOne 4.5

### ISSUE THREAD

**Issue by PoliNetwork** [telegramdesktop/tdesktop#5617]
EmojiOne is now at version 4.5
https://blog.emojipedia.org/emojione-4-5-changelog/

TDesktop is at 4.0

**Comment by PoliNetwork** [comment]
Oh, why? 
Isn't it just a zip to overwrite?

**Comment by john-preston** [comment]
@PoliNetwork Then the ones who have it already downloaded won't be updated.

**Comment by PoliNetwork** [comment]
I think I get it know how it works... 
Then maybe we need to introduce some way to support updating

**Comment by Nachtalb** [comment]
More workaround than a good solution:

I don't know if it actually updates the emojis, but when the emoji files are deleted (MacOS: `/Users/username/Library/Application Support/Telegram Desktop/tdata/emoji/set3` `set3` is `EmojiOne`) the emojis can be re-downloaded using the "Settings > Chat > Choose emoji set"

**Comment by ArmeF97** [comment]
Have you tried? Open this link https://blog.emojipedia.org/emojione-4-5-changelog/ and check which emoji version you have @Nachtalb

**Comment by Nachtalb** [comment]
Thanks for the suggestion @ArmeF97. As it looks it did not update. :/ and is still on 4.0

**Comment by ArmeF97** [comment]
I still want this feature request to be open, to implement something to update emojis without updating the whole desktop app

**Comment by ArmeF97** [comment]
I still want this feature request to be open, to implement something to update emojis without updating the whole desktop app

**Comment by Aokromes** [comment]
> I still want this feature request to be open, to implement something to update emojis without updating the whole desktop app

usually updating OS adds support for new emojis.

**Comment by ilya-fedin** [comment]
IMHO it is better to close the issue since I don't even see EmojiOne in the emoji list. If one wants support for updating emojis without updating the app, one can open a new properly filled issue.

**Comment by ArmeF97** [comment]
> 
> 
> IMHO it is better to close the issue since I don't even see EmojiOne in the emoji list. If one wants support for updating emojis without updating the app, one can open a new properly filled feature request.

I've done that here https://github.com/telegramdesktop/tdesktop/issues/16291
