### ISSUE TITLE
Feature Request: clear/delete button for Chat

### ISSUE THREAD

**Issue by HarburGER** [telegramdesktop/tdesktop#562]
Please Add a clear/delete button for Chat.

Like this (picture):
![telegram_delete_chat_option](https://cloud.githubusercontent.com/assets/11475297/6652202/a90034dc-ca67-11e4-9968-02bc2054af28.png)

Thx =)

**Comment by Travis9011** [comment]
+ 1

**Comment by mattmezza** [comment]
:+1:

**Comment by mmoayyed** [comment]
:+1:
