### ISSUE TITLE
Invisible horizontal stickers

### ISSUE THREAD

**Issue by ufgf** [telegramdesktop/tdesktop#5621]
First of all, I apologize for the curve of English, I just Russian and I can not really write sentences in English. Thank you for understanding.

Steps to reproduce
1. Enter any emoji on which there is a sticker
2. Click LMB and move the cursor past the edges of the stickers horizontally

[GIF](https://i.imgur.com/Rtc8Vh5.gif)

### Actual behaviour
You can choose "invisible" stickers

### Configuration
**Operating system: Windows 8.1 (Microsoft Windows [Version 6.3.9600])**

**Version of Telegram Desktop: 1.5.8**

**Used theme**: Solid Dark Green - v1 and Standard

**Comment by stek29** [comment]
whoa, that's funny.

**Comment by 23rd** [comment]
This is pretty old issue and it has already been mentioned [here](https://github.com/telegramdesktop/tdesktop/issues/5101).
And I agree with Preston, it's more like a feature than a bug.

**Comment by ufgf** [comment]
When make the final verdict, close this Issue, yep?

**Comment by stek29** [comment]
@john-preston oh, sorry, for some reason I thought stickers in next row were different.
