### ISSUE TITLE
Mention (@) isn't cleared after clicking if the mention was a voice message

### ISSUE THREAD

**Issue by foxmajik** [telegramdesktop/tdesktop#5623]
### Steps to reproduce
1. Someone replies in a group chat to your message with a voice message
2. You click the @ to view the message but you don't click play because voice messages are annoying and a useless feature
3. Even though you've acknowledged the mention it never goes away and mentions just stack up forever after that.

### Expected behaviour
Clicking @ to acknowledge the mention should have the same behavior for voice messages as for text messages: It should clear the notification.

### Actual behaviour
You have to download and play the voice message to make the @ go away, which wastes time and data.

### Configuration
**Operating system:**
Windows

**Version of Telegram Desktop:**
1.5.8

**Used theme**:
Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@foxmajik The voice message "unlistened" status is held in the same bit as the mention "unread" status. So if you mark it as read you also mark it as listened for the sender.

Being consistent with the mobile apps, to do this in tdesktop you're required to start listening to it.

**Comment by aNNiMON** [comment]
@john-preston in mobile apps there is an ability to reset mention by holding `@` button for a second. Can this be implemented in tdesktop?

**Comment by Kogoruhn** [comment]
Thats behaviour is REALLY annoying. Please fix it as described in the "expected behavior"!

**Comment by foxmajik** [comment]
Any update on this?
