### ISSUE TITLE
Emoji search doesn't reset found results

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#5624]
### Steps to reproduce
1. Type something in search field in global search, PM or group
2. Replace text in search field with an emoji, e.g. 🤔 or ❤️

### Expected behaviour
Previous search results should be cleared. 

### Actual behaviour
Previous search results are remain visible. 
![tg-issue](https://user-images.githubusercontent.com/1321838/51806987-92301780-2289-11e9-8b9f-7af678dcb4fc.gif)
(another bug: emoji in search field isn't replaced with :thinking: icon)

### Configuration
**Operating system:** Arch Linux, Windows

**Version of Telegram Desktop:** 1.5.8...2.4.3

**Used theme**: Any

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by aNNiMON** [comment]
Still valid in 1.9.8
Reproducible in Windows as well

**Comment by yashpalgoyal1304** [comment]
somewhat related: #3509

**Comment by aNNiMON** [comment]
Still an issue in 2.4.3

**Comment by aNNiMON** [comment]
Works fine in 2.7.1, except replacing emoji
![image](https://user-images.githubusercontent.com/1321838/115682829-834c4880-a35e-11eb-97c1-a6e8f463a1ca.png)
