### ISSUE TITLE
Cannot delete downloaded sound file after closing in telegram

### ISSUE THREAD

**Issue by m-ehsan** [telegramdesktop/tdesktop#5625]
### Steps to reproduce
1. Play a downloaded sound file (eg. MP3 file) with internal player
2. Stop playback and and close player ribbon
3. Try to delete the downloaded file from file system

### Expected behaviour
File shoud be deleted without interrupt.

### Actual behaviour
The file is still open by telegram and operating system does not allow deleting the file.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.5.8

**Used theme**: Default

**Comment by john-preston** [comment]
This shouldn't happen starting with the next version (1.5.16 beta).
