### ISSUE TITLE
Incorrect sorting of avatars after changing avatar

### ISSUE THREAD

**Issue by ufgf** [telegramdesktop/tdesktop#5626]
### Steps to reproduce
1. Change avatar
2. View avatar history

### Expected behaviour
Must be valid sort by time added

### Actual behaviour
Random sorting of avatars

### Configuration
**Operating system: Windows 8.1 and Windows 10 (14393)**

**Version of Telegram Desktop: 1.5.8**

**Used theme**: Solid Dark Green - v1 and Default

<details><summary><b>Logs</b>:</summary>
https://pastebin.com/hSuyS8R8
</details>

**Comment by aNNiMON** [comment]
#5279
