### ISSUE TITLE
Old background images

### ISSUE THREAD

**Issue by Deses** [telegramdesktop/tdesktop#5627]
At some point in the last several updates, some backgrounds were removed (the low poly colorful and a starry night, to name a few). I know that they were available in version 1.4.2 because I just downloaded that old version and they are there.

![image](https://user-images.githubusercontent.com/1654959/51863779-383f5880-2342-11e9-9d2c-778be703004b.png)
![image](https://user-images.githubusercontent.com/1654959/51863728-147c1280-2342-11e9-9a9d-18249b98b777.png)

I haven't seen any mention of that change in the changelog and I haven't found them either in the source code.

Where could I get them? I want to still use them...

**Comment by Deses** [comment]
> @Deses This is a server side list. It changed. Old is available only from the old versions.

Sure, I see. Could anyone make them available somewhere? A zip, maybe?

**Comment by stek29** [comment]
https://0x0.st/zr1Z.zip

**Comment by Deses** [comment]
> https://0x0.st/zr1Z.zip

Thank you, stek!
