### ISSUE TITLE
Animated GIF for profile picture

### ISSUE THREAD

**Issue by rauldipeas** [telegramdesktop/tdesktop#5629]
How could I use an animated GIF on my profile picture?

**Comment by Nachtalb** [comment]
To my knowledge Telegram doesn't support animated profile pics at all.

**Comment by GeroinEXP** [comment]
> How could I use an animated GIF on my profile picture?

https://github.com/mumtozvalijonov/telegram-avatar-time

**Comment by rauldipeas** [comment]
> > How could I use an animated GIF on my profile picture?
> 
> https://github.com/mumtozvalijonov/telegram-avatar-time

I can't figure out how use this.

**Comment by Aokromes** [comment]
telegram android beta 6.3 already allows to include videos up to 10s, very likely this will be platform wide soon(TM)

**Comment by GeroinEXP** [comment]
> > > How could I use an animated GIF on my profile picture?
> > 
> > 
> > https://github.com/mumtozvalijonov/telegram-avatar-time
> 
> I can't figure out how use this.

https://habr.com/ru/post/457078/

**Comment by yashpalgoyal1304** [comment]
@Aokromes so, shall the label api-issue be removed as it is "fixed" now? (just asking for getting an idea on how labelling works here)

**Comment by mazunki** [comment]
The animation does not appear unless you go into the profile. I would like to see the animation in other places as well, at least as an option. I guess some people might not like everyone's pictures to be moving, but I would love it!
