### ISSUE TITLE
Telegram doesn't unlock to settings page on Windows

### ISSUE THREAD

**Issue by Decateron** [telegramdesktop/tdesktop#563]
In version 0.7.20, if you lock Telegram in the settings page, after unlocking, it will open to the chat screen. If you then click on 'Settings', it will animate a transition, but you'll stay on the chat screen. If you click on 'Settings' again, it will then take you to the settings page.

I'm not sure if it's supposed to always open to the chat screen or not, but some part of the program still believes it's on the settings page.

**Comment by telegramdesktop** [comment]
Fixed in 0.7.23
