### ISSUE TITLE
Telegram Desktop freezes when trying to save an image

### ISSUE THREAD

**Issue by helveticau** [telegramdesktop/tdesktop#5630]
### Steps to reproduce
1. Enter any channel
2. Select any image (enter fullscreen view)
3. Press RMB -> 'Save as...'

### Expected behaviour
Telegram Desktop should show Save File dialog over the image.

### Actual behaviour
Telegram Desktop just freezes and it's impossible to interact with the app until you kill it.

### Configuration
**Operating system:** Arch Linux
Linux 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux

**Version of Telegram Desktop:** 1.5.4

**Used theme**: Matrix

It freezes with any image I tried. The Save File dialog appears for a second and then just disappears, leaving TD absolutely frozen.

**Comment by magnus-gross** [comment]
Cannot confirm the bug, although I am running Arch Linux too.
Your version is outdated btw, the most recent version is 1.5.8.

**Comment by Johnnynator** [comment]
I can reproduce it to a degree in KDE Plasma, I highly doubt that it is related to the window manager, more that the any File Manager Action seems to block the Rendering Thread  of Telegram. But the non Opening File Manager is probably a issue on your machine @helveticau 

<detail>
<summary>Screenshot</summary>

[Screenshot](https://i.imgur.com/D96LYpw.png)

</detail>

**Comment by helveticau** [comment]
@Johnnynator 
You know, TD opens File Manager when I need to upload a file or something. It doesn't open FM only when in fullscreen viewing mode.

**Comment by helveticau** [comment]
I updated my TD from 1.5.4 to 1.5.8 (telegram-desktop-bin from AUR) and now the problem is fixed. Probably, the issue can be closed.

**Comment by magnus-gross** [comment]
You are able to close it yourself.

BTW you should probably switch to telegram-desktop from the official repos, it's been there a while.

**Comment by andrealorenzon** [comment]
it happens the same on Mint Linux 20.04
