### ISSUE TITLE
[Feature Request] Add "work mode" toggle under "advanced" settings

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#5631]
As for now, the only way to activate it is to write "workmode" in settings.
It would be nice to have a toggle in settings (with proper warning about restarting telegram to enable it)

**Comment by ArmeF97** [comment]
![immagine](https://user-images.githubusercontent.com/6240983/51933726-3f2da000-2402-11e9-95dc-1269da1751bb.png)

**Comment by Aokromes** [comment]
there is no workmode anymore.

**Comment by ArmeF97** [comment]
Well, now it's better! Thanks!
