### ISSUE TITLE
Bring Back Read Permission

### ISSUE THREAD

**Issue by Fathurhoho** [telegramdesktop/tdesktop#5632]
Read permission is missing. It needed to ban/temporary-ban with one step. Now there is no way to tempbanning someone unless using another client or using a bot. I already tried to toggled off all permissions, but it results is 'mute', actually because member is restricted to send message.

TDesktop version: 1.5.8 Beta

**Comment by Sutarat66** [comment]
เมื่อ พฤ. 31 ม.ค. 2562 เวลา 19:24 Viktor Oreshkin <notifications@github.com>
เขียนว่า:

**Comment by john-preston** [comment]
@Fathurhoho As I see it, other official apps now don't allow to temporary ban user from the group completely. It is either temporary read only ban, or a complete ban ("Remove user"). So this is a consistent change with other applications :(
