### ISSUE TITLE
Expiration of telegram channels

### ISSUE THREAD

**Issue by Dmitri-Sintsov** [telegramdesktop/tdesktop#5633]
I run few Telegram channels related to folk and classical music. In some of the channels I observed the warning that "the channel inactive in 5 months" will be archived or even closed.

I do not run "hot news" channels which expire in a year / a month. Classical and folk music has the timeless value and it does not expire.

I understand that the service wants to encourage to post more content (which I am not always able to do so) and it wants to remove junk channels and to save some storage / database space.

Maybe it's possible as some compromise solution that the channels which has at least 50 posts will never be expired?

Current policy for channel expiration makes the timeless channels like music channels to be undervalued.

**Comment by RememberTheAir** [comment]
> "the channel inactive in 5 months"

The warning actually tells that **the account of the user who created the channel** is going to be deleted because of inactivity, not the channel itself. Even if the creator's account gets deleted, the channel will stay there (possibly unmoderated, if the creator was the only administrator of the channel)

**Comment by Dmitri-Sintsov** [comment]
Ok, that's a bit better, at least the content will not be lost.

Would the owner be able to restore the ownership in case he re-registers from the same phone number?

**Comment by RememberTheAir** [comment]
It's a different account, so nope
