### ISSUE TITLE
Won't start when using QtCurve

### ISSUE THREAD

**Issue by flipwise** [telegramdesktop/tdesktop#5635]
### Steps to reproduce
1. Use KDE Plasma 5 (tested with version 5.14.5)
2. Set "Widget Style" to QtCurve (respective package is: qtcurve-kde)
3. Try launching `telegram-desktop`

### Expected behaviour
Telegram starts normally.

### Actual behaviour
Telegram won't start.

### Configuration
**Operating system:** ManjaroLinux

**Version of Telegram Desktop:** 1.5.4

**Used theme**: System theme is QtCurve.

<details><summary><b>Logs</b>:</summary>
$ telegram-desktop

QApplication: invalid style override passed, ignoring it.
Aborted (core dumped)
</details>

**Comment by flipwise** [comment]
Workaround is to run it as: `QT_STYLE_OVERRIDE="breeze" telegram-desktop `

**Comment by Aokromes** [comment]
this bug is still valid? if yes, try with official package instead distribution package.

**Comment by flipwise** [comment]
Still valid with Manjaro's package.

I don't have the issue when I run the 64-bit binary obtained from the official website.

**Comment by Aokromes** [comment]
ok, then that's 3rd party bug, for sure manjaro package is 1.8.x at max and it was fixed on 1.9.x
