### ISSUE TITLE
Incorrect message for confirmation remove contact

### ISSUE THREAD

**Issue by anfimovir** [telegramdesktop/tdesktop#5636]
Telegram Desktop 1.5.8
Ubuntu 18.10 64 bit

Screenshot:

![remove_contact](https://user-images.githubusercontent.com/10336636/52020563-03720380-24f2-11e9-87e7-8689a92bf4d2.png)

**Comment by stek29** [comment]
it's an issue with translation: https://translations.telegram.org/ru/tdesktop/profile/lng_sure_delete_contact

**Comment by anfimovir** [comment]
Now sorted, thanks you.
