### ISSUE TITLE
1.5.9: Crash on some videos

### ISSUE THREAD

**Issue by Kogoruhn** [telegramdesktop/tdesktop#5639]
### Steps to reproduce
1. Open telegram Desktop 1.5.9
2. run video https://t.me/huepub/6484
3. Profit!

### Configuration
**Operating system:**
Win 7 Professional

**Version of Telegram Desktop:**
1.5.9
**Used theme**:

**Comment by john-preston** [comment]
@Kogoruhn Yeah, on videos without thumbnails. Thanks! I'll fix that later today in 1.5.10.

**Comment by ufgf** [comment]
Update 1.5.10 released, maybe close this issue?
