### ISSUE TITLE
Searching not working well with Asian languages

### ISSUE THREAD

**Issue by brglng** [telegramdesktop/tdesktop#564]
Hi, Telegram developers,

I am a Chinese and have been using Telegram for months. It is really a great software, especially that it syncs all the chat history among devices, and supports searching the log. However I found the searching (in the desktop client) always matches a whole word. For example, when I search "a", "a b c" can be found and "abc" is not shown in the result. This works well for English but not for Chinese, because there is no white space in a Chinese sentense. As a result, e.g. when I search "我", a message which only contains one charactor "我" comes out, and a message which is "我要下了" does not come out. This behavior is not reasonable for Chinese as well as for other Asian languages. Could you please add an option for the searching to toggle bewteen matching or not matching a whole word?

Thanks for your great work!

Best regards.

**Comment by jcppkkk** [comment]
Similar report in Android DrKLO/Telegram/issues/114 
@ruleroller

For example:

In English: "I am Chinese", I can search "I", 'am', "Chinese", any of the word can lead me to the conversation.

In Chinese:"我是中国人"，if I search "我", "是", "中国人", none of them works, because there is no blank in this sentence. But if I just search "我是中国人", the whole sentence, search works.

the same issue In Japanese:"私は中国人です", "私は","中国人","です" also show no search result. "私は中国人です", the whole sentence works, although.

**Comment by auchri** [comment]
api issue

**Comment by jcppkkk** [comment]
Then Where to report API issue? I have looked if there is a official way to report this issue, but found no way to do this.

**Comment by auchri** [comment]
https://twitter.com/telegram

**Comment by winagain** [comment]
Gents , do you get any update about this issue ? i've report to https://twitter.com/telegram a few times but no reply at all.

Whatsapp's ads is coming , hope telegram fix this bug asap which stop a lot of Asian Chinese to switch to telegram

**Comment by brglng** [comment]
This issue has remain not fixed for years. There are a lot of Chinese people using Telegram and there are also lot of Chinese channels and groups on Telegram nowadays, however the search feature is hardly usable for us.

**Comment by brglng** [comment]
I have joined the petition. Thanks for your great idea.

**Comment by ruleroller** [comment]
They didn't fix this before, they won't fix it now.

After years, they offered one new feature may help with the search that we can download the chats, so download the old messages to local, and use tools to search locally, Although.

**Comment by winagain** [comment]
dear ruleroller , i know your suggested solution , but i can't do this when i'm on the bus , right ? let's try and share the petition and see any chance.

**Comment by themikesam** [comment]
it's a huge bug.

**Comment by winagain** [comment]
unfortunately , not too many users care ...
i found it not bug in Chinese but also Japanese

**Comment by hanksb** [comment]
Part of the issue is lack of competition. The other messaging apps either have less encryption, no disappearing messages, or does not have search function altogether.

**Comment by Fezreal** [comment]
problem still exist     2019

god...

@john-preston 

Then Where to report API issue? I have looked if there is a official way to report this issue, but found no way to do this.

**Comment by Fezreal** [comment]
@auchri  please re-open this issue

**Comment by winagain** [comment]
Fezreal , not just Asian language , this bug confirmed exist for any language , even English !!

https://www.reddit.com/r/Telegram/comments/7gjcsf/how_to_search_for_telegram_with_a_keyword_gram/

**Comment by Fezreal** [comment]
@winagain so sad

**Comment by mrr010** [comment]
> api issue
@auchri please re-open this issue

**Comment by themikesam** [comment]
@auchri please re-open this issue

**Comment by davidhcefx** [comment]
# Please solve this bug.
# This is such a basic feature.

**Comment by lcysyx** [comment]
Can't imagine that Telegram as a chat app still can't even search messages until 2020.

**Comment by mrtysn** [comment]
The search only returns results if it is an exact word match. Tested both in English and Turkish. This issue should be re-opened.

**Comment by themikesam** [comment]
# Please reopen this issues 😅

**Comment by deepfish** [comment]
Hope this problem will solve soon.

**Comment by ly4096x** [comment]
Opened a new bug report, and got it closed immediately. Same `api bug` reply without any further explanation. 😞

**Comment by daehan1996** [comment]
> api issue

Please reopen this issue. It's a huge problem that's affecting too many users

**Comment by themikesam** [comment]
> > api issue
> 
> 
> 
> Please reopen this issue. It's a huge problem that's affecting too many users 

Help to report in client, ask a question.

Refer to:
https://github.com/telegramdesktop/tdesktop/issues/7942

**Comment by themikesam** [comment]
> Explanation of `api bug`:
> 
> 
> 
> > 
> 
> > 
> 
> > it belongs to telegram server and not clients.
> 
> 
> 
> I think that's the reason why they keep closing our issues...

Yup, try to report this issues from client.

**Comment by mgs20190702** [comment]
Gents , for more than 5 years of complaint of "chat history partial searching" error to telegram without any feedback , which show us the attitude of this company. 

Now , whatsapp is conquer telegram bit by bit : 
https://9to5google.com/2020/09/21/whatsapp-multi-device-testing/

after this enhancement , only the open API is ahead of competitors , probably 0.00001% users concerns ?

**Comment by Aokromes** [comment]
> Gents , for more than 5 years of complaint of "chat history partial searching" error to telegram without any feedback , which show us the attitude of this company.
> 
> Now , whatsapp is conquer telegram bit by bit :
> [9to5google.com/2020/09/21/whatsapp-multi-device-testing](https://9to5google.com/2020/09/21/whatsapp-multi-device-testing/)
> 
> after this enhancement , only the open API is ahead of competitors , probably 0.00001% users concerns ?

complaining here doesn't help, like you where told, it's API issue not client issue, API issue must be reported in app-> ask a question.

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/724

**Comment by spphinslove** [comment]
opps still not fix this bug.

**Comment by Aokromes** [comment]
again, posting here won't help to fix bug, it's server side bug, preston cannot fix it.

**Comment by Aokromes** [comment]
again, posting here won't help to fix bug, it's server side bug, preston cannot fix it.
