### ISSUE TITLE
Permission/Privilege to "Change channel information" appears blocked.

### ISSUE THREAD

**Issue by Edicksonjga** [telegramdesktop/tdesktop#5640]
### Steps to reproduce
1. Enter the channel and try adding an administrator.
2. Try unchecking the permission to "Change channel information".
3. The permission appears blocked.
4. A message warns that: "This option is enabled for all members in Group Permissions and can not be unchecked.

![sin titulo](https://user-images.githubusercontent.com/37910384/52122464-7914c700-25f9-11e9-98cf-3d72a5115f3a.png)

"We are in a channel, public or private happens the same"

### Expected behaviour:
Regardless of whether the channel is public or private, you must be able to uncheck the permission to change channel information.

### Actual behaviour:
You can not uncheck the "Change channel information" permission, it appears blocked by GROUP PERMISSIONS.

### Configuration:

**Operating system: Windows 7**

**Version of Telegram Desktop: 1.5.8-1.5.10**

**Used theme: Default**

**Comment by john-preston** [comment]
@Edicksonjga Thanks!

**Comment by Edicksonjga** [comment]
@john-preston I hope my little golden star hahaha. You are welcome!
