### ISSUE TITLE
Chat background is reset on closing

### ISSUE THREAD

**Issue by magnus-gross** [telegramdesktop/tdesktop#5641]
When I click on a new chat background shared from Android and apply it, the background is only kept until I restart the app.

### Steps to reproduce
1. Share a new background from Android, e.g. https://t.me/bg/RKoGzb5giVIBAAAAW_S7sn3YmKc?mode=blur+motion
2. Go to tdesktop and click on the link and hit Apply
3. Quit the app with Ctrl+Q and restart it

### Expected behaviour
The background is still there

### Actual behaviour
The background is reset

### Configuration
**Operating system:**
Arch Linux with KDE Plasma

**Version of Telegram Desktop:**
1.5.10

**Used theme**:
https://t.me/bg/RKoGzb5giVIBAAAAW_S7sn3YmKc?mode=blur+motion

**Comment by magnus-gross** [comment]
Also, currently tdesktop does not make use of the "Blur" and "Move" flag, though this should probably be an extra issue.

**Comment by john-preston** [comment]
@magnus-gross Perhaps the image is too large :( I have a limit on stored background width + height <= 10'000

**Comment by john-preston** [comment]
@magnus-gross You shared an official one?

**Comment by magnus-gross** [comment]
@john-preston Yes, it is an official background.
Go to Chat-Settings -> Chat background -> Choose from gallery -> Scroll to the bottom
and it will be the third last wallpaper to choose from.
