### ISSUE TITLE
How to convert to Supergroup in v1.5.11?

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5642]
Unable to find the convert option

**Comment by ufgf** [comment]
Beginning with update 1.5.8, groups immediately become Supergroups, or rather regular groups have acquired the capabilities of Supergroups, so you can forget about them.

**Comment by john-preston** [comment]
@ArmeF97 Not exactly. A normal group is created, but it is seamlessly converted to supergroup when it is required.

**Comment by ArmeF97** [comment]
Won't that change the id of the group? And break exports? 
At this point, where normal groups are useless in comparison of the supergroups, isn't it better to create supergroups directly?

**Comment by john-preston** [comment]
@ArmeF97 There is a limit on how many channels and supergroups a user can have. So it is better for small groups to remain normal groups.

**Comment by SmartManoj** [comment]
@john-preston How much limt ?

**Comment by ArmeF97** [comment]
@john-preston  what would happen if a user is at his limit and the group is converted in a supergroup, when "it is required" (as you said)

**Comment by john-preston** [comment]
@ArmeF97 If he is the creator and converts the group, he wouldn't be allowed to perform the action that required the conversion.

If he was just a member I'm afraid he'll be removed from the group :( but this depends on the server, I'm not sure.

**Comment by john-preston** [comment]
@ArmeF97 I don't know, need to test that.

**Comment by ArmeF97** [comment]
Ok, maybe it's better to move this discussion in a separated issue, don't you think?

**Comment by Olegt0rr** [comment]
@ufgf @ArmeF97 
Guys you're wrong!

You still create groups, not supergroups.
On create:
``` python
"chat": {
   "id": -220514232,
   "title": "MyTitle",
   "type": "group",
   "all_members_are_administrators": true
  },
```

If you try to add an administrator, a conversion to a supergroup will occur.
``` python
"chat": {
   "id": -1001490693730,
   "title": "MyTitle",
   "type": "supergroup"
  }
```

But it's terrible, cause I need to write different help for each telegram client...
Other tg apps still work with old style, with 'Convert to supergroup' button

**Comment by john-preston** [comment]
@Olegt0rr All official apps convert automatically (iOS, Android, macOS).

**Comment by SmartManoj** [comment]
How to delete messages for everyone as default like in supergroup?

**Comment by RememberTheAir** [comment]
@SmartManoj see #3490

**Comment by SmartManoj** [comment]
It is different because here is a checkbox to delete for everyone @RememberTheAir

**Comment by Nagendracv** [comment]
Old groups are not getting converted to supergroups. Delete message is still not working for the old groups. And there is no option to force convert to supergroup.

**Comment by Aokromes** [comment]
make group public, remove it from public, it will be converted to supergroup.
