### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by Painkiller1991** [telegramdesktop/tdesktop#5644]
**Steps to reproduce**

1.Do correctly [build instructions](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md) without any errors
2. Build Telegram desktop
3.

Expected behaviour
Successful build.

Actual behaviour
Tell us what happens instead
![image](https://user-images.githubusercontent.com/37259519/52174231-4956f200-27a6-11e9-8a6a-f1a0ddfc3e03.png)
![image](https://user-images.githubusercontent.com/37259519/52174244-6e4b6500-27a6-11e9-9479-182a2a6417cd.png)

**Comment by kirsan31** [comment]
VS version? See [this](https://github.com/telegramdesktop/tdesktop/issues/5456).

**Comment by Painkiller1991** [comment]
> VS version? See [this](https://github.com/telegramdesktop/tdesktop/issues/5456).

15.6.5

thanks for help, i should upgrade it
