### ISSUE TITLE
[LINUX] Wrong charset on media-saving window

### ISSUE THREAD

**Issue by awd-studio** [telegramdesktop/tdesktop#5645]
![The screenshot](https://user-images.githubusercontent.com/15061745/52174641-a8653880-279f-11e9-84a5-72291129c85b.png)

### Steps to reproduce
1. Open any media (pic, video, etc.)
2. RMC -> "Save As..."

### Configuration
**Operating system:** Linux (Ubuntu / Mate - 18.04.1 / 1.20.1)

**Version of Telegram Desktop:** 1.5.10

**Used theme**: Matrix

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by awd-studio** [comment]
No, it's not.
