### ISSUE TITLE
Need Autostart option on Ubuntu 

### ISSUE THREAD

**Issue by uncertainquark** [telegramdesktop/tdesktop#5647]
Add option in Telegram settings to enable auto-start of it in Ubuntu.

![screenshot from 2019-02-03 17-32-11](https://user-images.githubusercontent.com/22585732/52176504-d7000500-27d9-11e9-94d3-4d0bed470385.png)

Ideally, it should auto-start in the system tray at the top so that it's silently done in the background and doesn't interfere by opening a window. This is crucial to get notifications automatically after system startup.

### Configuration
**Operating system:**
Ubuntu 18.04 

**Version of Telegram Desktop:**
v 1.5.10

**Comment by Tids** [comment]
> Ideally, it should auto-start in the system tray

No. Gnome does not support a systemtray anymore. Telegram should not default to require a systemtray.
Ubuntu ports the systemtray functionilty to newer versions, however the past has told us that they dont port things forever and the day will come when there is no tray anymore.

Apps can run in the background and show notifications. (geary) Thats why we have a notificationcenter.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/422
