### ISSUE TITLE
Feature request: different kind of attachment 

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#565]
I suggest to add different kind of attachments in similar way of Android client

**Comment by mbnoimi** [comment]
![screenshot_2015-03-15-06-53-35](https://cloud.githubusercontent.com/assets/284547/6654793/75c41f0c-cae4-11e4-933a-1e475c598c9b.jpg)

**Comment by cobalto** [comment]
Not you can search images and gifs directly from the internet to send too.
I MISS THIS SO MUCH ON TDESKTOP.

**Comment by mbnoimi** [comment]
@cobalto  +1

**Comment by jonnywilliamson** [comment]
Would love to be able to search for an image inside the app. I use it all the time on the ios app and miss it badly on the desktop one!

**Comment by auchri** [comment]
See #1193 #1012 #781
