### ISSUE TITLE
More than 20 recently used stickers in sticker settings panel

### ISSUE THREAD

**Issue by imashxtyz** [telegramdesktop/tdesktop#5650]
### Steps to reproduce
1. Send more than 20 random stickers you haven't sent before
2. Open sticker settings (the panel where you can reorder and delete sticker packs)

### Expected behaviour
Recently used stickers number should be no more than 20, oldest should be deleted from cash

### Actual behaviour
The number has no limit, looks like they are all saved, although you can't see them on the sticker panel, which shows only 20

### Configuration
**Operating system:**
Windows 7 64bit
**Version of Telegram Desktop:**
1.5.11
**Used theme**:
Classic
![capture](https://user-images.githubusercontent.com/46919076/52204636-7992b380-28c0-11e9-8141-1c37a8ea291b.JPG)

**Comment by Remu-rin** [comment]
> The number has no limit, looks like they are all saved

It resets to 200 after restart.
![1](https://user-images.githubusercontent.com/28995228/52278317-8f63af80-2978-11e9-8e79-4f89e47f2e0a.png)

**Comment by imashxtyz** [comment]
Why 200 and not 20 then?
