### ISSUE TITLE
[Feature Request] Video call support

### ISSUE THREAD

**Issue by manasesjesus** [telegramdesktop/tdesktop#5655]
The title is self explanatory. Voice calls are awesome; support for video would be extraordinary.

**Comment by RememberTheAir** [comment]
Needs server-side support

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4270#issuecomment-354706392

**Comment by IlyaIndigo** [comment]
And desktop-sharing. :-)

**Comment by QuAzI** [comment]
> Video calls need server-side support

Maybe p2p enough in most cases. p2p used for audio calls

Also screen sharing required. Screen sharing can work via dynamic image replacing (like geo sharing work now)

**Comment by matthiasg** [comment]
Is it possible to do screen sharing via an html5 app inside telegram ? does the app have access to some state inside the session to exchange a secret or at least establish a connection between the two parties ? at a minimum the session id itself would be enough i guess
