### ISSUE TITLE
Emoji doesnt clickable

### ISSUE THREAD

**Issue by N-i-p-o-l** [telegramdesktop/tdesktop#5658]
### Steps to reproduce
1. Open any chat
2. Try to click on any standart emoji 

### Expected behaviour
Emoji successfully pasted in chat

### Actual behaviour
Nothing happened

### Configuration
**Operating system:** Win10 x64

**Version of Telegram Desktop:** 1.5.11

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by MasterGroosha** [comment]
Cannot reproduce :(

**Comment by N-i-p-o-l** [comment]
Yes, I dont know why. Peoples around me with the same version. And It's all ok, but not me

**Comment by N-i-p-o-l** [comment]
Oh, I have been reproduced.
1. Turn on local pass code
2. Restart tg desktop
3. Open any chat
4. Try to click on any standart emoji

**Comment by N-i-p-o-l** [comment]
I haven't reproduced in 1.5.15
