### ISSUE TITLE
[Feature Request] Trayicon (color and/or animation) as indicator of connecton (as in Skype)

### ISSUE THREAD

**Issue by IlyaIndigo** [telegramdesktop/tdesktop#5660]
### Steps to reproduce
1. Run telegram-desktop
2. Disable network connection or set wrong proxy server.

### Expected behaviour
The icon will be repainted in gray or another color and some kind of airplane animation will probably appear.

### Actual behaviour
The icon continues to be colored and does not inform the user about the disconnection.

### Configuration
**Operating system:**
All
**Version of Telegram Desktop:**
All
**Used theme**:
Default

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/341
