### ISSUE TITLE
per group / channel automatic media download

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#5661]
### Steps to reproduce
How about allow people to disable or enable media download on specific groups?

### Configuration
N/R (all)

**Version of Telegram Desktop:**
N/R (all)

**Used theme**:
N/R (all)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RememberTheAir** [comment]
I feel like TDesktop is getting a lot of local settings that are not synchronized across instances. I find myself logging in and off from this app really frequently for many reasons (several desktops and laptops, portable devices, two accounts to manage) and every time I need to go through all the options to set them in the way I want. If more local settings are added, it would be nice to be able to export them to a json file or something, so at least we could import them manually

**Comment by Lonami** [comment]
@RememberTheAir perhaps that's worth a new issue, if there isn't one already.
