### ISSUE TITLE
Supergroup conversion breaks chat history export 

### ISSUE THREAD

**Issue by Syntaxvgm** [telegramdesktop/tdesktop#5662]
### Steps to reproduce
1. Convert group with previous chat history to supergroup, do not clear chat
2. Attempt to export entire chat history, any size and media type settings

### Expected behaviour
The entire chat history should be exported. I can see messages before it was converted to a supergroup, even on a new device. 

### Actual behaviour
It only exports as far back as the supergroup conversion. 

### Configuration
Windows 10 Desktop Client 

**Version of Telegram Desktop:**
1.5.11

<details><summary><b>Images of Issue</b>:</summary>

[Beginning of chat log](https://i.imgur.com/GSSo9Lw.png)
[Actual chat history](https://i.imgur.com/etvs1q0.png)
</details>

**Comment by anatolyevich** [comment]
Can confirm this bug on Linux Telegram Desktop 1.6.3. This is pretty sad, since I don't know any other way to export chat data into a readable HTML. Effectively, a big part of the data is locked up.

**Comment by SvenErikLarsen** [comment]
Still happens on tDesktop 1.7 on win10.

**Comment by hbh7** [comment]
Just noticed this issue as well, glad I did as I was cleaning out old chats and it would have sucked to not have seen this. Please fix!

**Comment by sokomo** [comment]
I have checked and confirmed the issue. I had also tried to export chat messages from way back till before the day the group was converted to be a supergroup, and I could not get the old data.

**Comment by CharisAsgard** [comment]
Still same issue on Telegram Desktop version 1.8.1 Windows 10

**Comment by CoeusCC** [comment]
Guess I'll +1 this. Didn't really realize what I was giving up by making this change.

**Comment by hbh7** [comment]
Not sure this is really an "enhancement"... More like core functionality is broken. Perhaps especially so if you consider GDPR requirements for data exporting.

**Comment by john-preston** [comment]
@hbh7 You can export all the data (from both parts of each supergroup) in Settings.

**Comment by user789465** [comment]
well, I guess I'll +1 for the 1 year anniversary of this issue...
is there any other way to export an old group ? 
or any tool to export or dump the data ?

**Comment by geenkaas** [comment]
Also looking for a way to export a ton of data from a migrated group, best I am looking at so far is 100 images at a time...

**Comment by mikedelcastillo** [comment]
This still a bug on Mac too

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5139

**Comment by dgarkavenko** [comment]
I'll +1 this.

**Comment by StodaraHodan** [comment]
+1

**Comment by cesarsicas** [comment]
+1 version 2.1.2 on Ubuntu

**Comment by john-preston** [comment]
@cesarsicas This one will be fixed in the next release, it is in the repository already.
