### ISSUE TITLE
Can't type message after little time after launch

### ISSUE THREAD

**Issue by kolianbolo** [telegramdesktop/tdesktop#5663]
I use desktop client on Ubuntu 18.04 with XFCE. Client version - 1.5.11.
### Steps to reproduce
1. Launch Telegram client
2. Wait on tray ( 1 -5 hour)
3. My friend send me funny kitty photo, but I can't reply him, because I push the buttons, but not see symbols.

### Expected behaviour
I can type the message

### Actual behaviour
I can't type the message 

### Configuration
Ubuntu 18.04 with XFCE, Version of telegram client - 1.5.11

**Version of Telegram Desktop:** - 1.5.11

**Used theme**: dark

**Comment by kolianbolo** [comment]
I was wrong it was ubuntu 18.04

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by kolianbolo** [comment]
I can't reproduce this bug today. I think this bug is no actual more. Thank you for you time.
