### ISSUE TITLE
Allow more fine-grained permissions for media

### ISSUE THREAD

**Issue by jez9999** [telegramdesktop/tdesktop#5665]
Right now you can just choose whether members of a room can "Send Media" or not (there is also "send stickers and GIFs").  Could you also add more specific permissions for "send video", "send audio", and "send voice messages"?

**Comment by RememberTheAir** [comment]
Available permissions are defined by the server, so there's no way for tdesktop to add more specific permissions

**Comment by jez9999** [comment]
Well where do you submit feature requests for that?

**Comment by RememberTheAir** [comment]
On [Twitter](https://twitter.com/telegram) or via the in-app support

**Comment by jez9999** [comment]
Why don't they have it on Github?

**Comment by RememberTheAir** [comment]
¯\\\_(ツ)\_/¯
