### ISSUE TITLE
Can't search for messages of left users

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#5667]
### Steps to reproduce
1. User1 joins a group.
2. User1 posts some messages.
3. User1 leaves the group.
4. User2 clicks the search icon in the group.
5. User2 clicks the silhouette icon in the search field.

### Expected behaviour
All users that have posted non-deleted messages in the group are listed.

### Actual behaviour
Only current members of the group are listed.

### Configuration
**Operating system:** Debian GNU/Linux 10

**Version of Telegram Desktop:** 1.5.4

**Used theme**: Classic

**Comment by TheWug** [comment]
As an administrator in a dozen groups, I hate this so much that I actually use and distribute to fellow mods a patched version of the client that has this capability. PLEEEEEEEEEEEASE fix this.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3895
