### ISSUE TITLE
Telegram crashes on some video files sent by bot and does not recognizes as video when sent by person

### ISSUE THREAD

**Issue by dzek69** [telegramdesktop/tdesktop#5668]
### Steps to reproduce

There are two bugs here, caused by the same thing. I'll describe both behaviors:

Note: This is NOT problem with only single video file, but I gave one as example. These videos are created by newest `youtube-dl` app, and youtube-dl probably created these mp4 with newest ffmpeg from DASH video chunks. Anyway - it's not hard to find videos like that and it's not a problem with single file.

Behavior 1:
1.  Create a bot
2. Make it send video file contained here: [video (4).zip](https://github.com/telegramdesktop/tdesktop/files/2845615/video.4.zip) to an user

Behavior 2:
1. Using Telegram desktop send video file contained here: [video (4).zip](https://github.com/telegramdesktop/tdesktop/files/2845615/video.4.zip) to another user

### Expected behaviour
Behavior 1:
User should get correct preview and duration, like that:
![image](https://user-images.githubusercontent.com/4936805/52487176-52d4c580-2bbd-11e9-9b3d-09106b0f31bc.png)
And playing the video should work

Behavior 2:
User should get correct preview and duration, like that:
![image](https://user-images.githubusercontent.com/4936805/52487176-52d4c580-2bbd-11e9-9b3d-09106b0f31bc.png)
And playing the video should work directly from Message

### Actual behaviour

Behavior 1:
User will receive video message with no preview and 00:00 duration
![image](https://user-images.githubusercontent.com/4936805/52486706-22405c00-2bbc-11e9-98be-bcc3a6bd4204.png). Clicking on that will crash Telegram.

Behavior 2:
User will receive video as file, not as media:
![image](https://user-images.githubusercontent.com/4936805/52487264-8a437200-2bbd-11e9-8222-9d6abade2082.png)

### Configuration
**Operating system:**
Windows 10 x64, 1809 build 17763.253
Windows 7 x64

**Version of Telegram Desktop:**
1.5.11

**Other versions**:
youtube-dl (on ARMv7) 2019.01.30.1
ffmpeg (on ARMv7) 4.1-static https://johnvansickle.com/ffmpeg/ built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516

**Used theme**:
Tested on few, only official themes. "Works" the same on every tested.

<details><summary><b>Logs</b>: (log created on Behavior 1)</summary>
[2019.02.08 16:28:16] Launched version: 1005011, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]

[2019.02.08 16:28:16] Executable dir: C:/Apps/Telegram/, name: Telegram.exe
[2019.02.08 16:28:16] Initial working dir: C:/Apps/Telegram/
[2019.02.08 16:28:16] Working dir: C:/Apps/Telegram/
[2019.02.08 16:28:16] Command line: C:\Apps\Telegram\Telegram.exe
[2019.02.08 16:28:16] Executable path before check: C:/Apps/Telegram/Telegram.exe
[2019.02.08 16:28:16] Logs started
[2019.02.08 16:28:16] Connecting local socket to Global\2c18f954b230b01b900e013039478489-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2019.02.08 16:28:16] This is the only instance of Telegram, starting server and app...
[2019.02.08 16:28:16] Moved logging from 'C:/Apps/Telegram/log_start0.txt' to 'C:/Apps/Telegram/log.txt'!
[2019.02.08 16:28:16] Primary screen DPI: 96
[2019.02.08 16:28:17] App Info: reading settings...
[2019.02.08 16:28:17] App Info: reading encrypted settings...
[2019.02.08 16:28:17] Lang Info: Loaded cached, keys: 2201
[2019.02.08 16:28:17] OpenAL Logging Level: (not set)
[2019.02.08 16:28:17] Audio Playback Devices: OpenAL Soft
[2019.02.08 16:28:17] Audio Playback Default Device: OpenAL Soft
[2019.02.08 16:28:17] Audio Capture Devices: OpenAL Soft on Mikrofon (Realtek High Definition Audio);OpenAL Soft on Zestaw sĹ‚uchawkowy (Bluedio F Hands-Free)
[2019.02.08 16:28:17] Audio Capture Default Device: OpenAL Soft on Mikrofon (Realtek High Definition Audio)
[2019.02.08 16:28:17] App Info: reading map...
[2019.02.08 16:28:17] App Info: reading encrypted map...
[2019.02.08 16:28:17] App Info: reading encrypted user settings...
[2019.02.08 16:28:17] App Info: encrypted user settings read.
[2019.02.08 16:28:17] App Info: reading encrypted mtp data...
[2019.02.08 16:28:17] MTP Info: read keys, current: 5, to destroy: 0
[2019.02.08 16:28:17] Map read time: 5
[2019.02.08 16:28:17] Export Info: Destroy top bar by controller removal.
[2019.02.08 16:28:17] Window Shadow: 1, 1, 3, 4, 6, 9, 13, 18, 24, 31, 38, 46
[2019.02.08 16:28:20] Gif Error: Unable to avformat_open_input for file 'D:/Downloads/Telegram Desktop/video (4).mp4', data size '0', error -1094995529, Invalid data found when processing input
</details>

**Comment by john-preston** [comment]
This file looks corrupted, ffmpeg can't start reading it with an error:

Error -1094995529, Invalid data found when processing input.

So there is no preview and duration.

The crash will be fixed in the upcoming version, thanks.

**Comment by dzek69** [comment]
Which version of ffmpeg?

<details><summary>ffprobe "video (4).mp4"</summary>

ffprobe version 4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mpegts, from 'video (4).mp4':
  Duration: 00:00:10.57, start: 1.466667, bitrate: 1600 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 640x640 [SAR 1:1 DAR 1:1], 30 fps, 30 tbr, 90k tbn, 60 tbc</details>


<details><summary>ffmpeg -n -i video (4).mp4 -c:v libx264 -preset slow -crf 23 -c:a aac -vsync 2 -tune zerolatency -movflags +faststart video (4).encoded.mp4</summary>

ffmpeg version 4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100

Input #0, mpegts, from 'video (4).mp4':
  Duration: 00:00:10.57, start: 1.466667, bitrate: 1600 kb/s
  Program 1
    Metadata:
      service_name    :
Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 640x640 [SAR 1:1 DAR 1:1], 30 fps, 30 tbr, 90k tbn, 60 tbc

Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
Press [q] to stop, [?] for help

[libx264 @ 0x54d5e40] using SAR=1/1

[libx264 @ 0x54d5e40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2

[libx264 @ 0x54d5e40] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x54d5e40] 264 - core 157 r2935 545de2f - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=5 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=8 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=8 lookahead_threads=8 sliced_threads=1 slices=8 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

Output #0, mp4, to 'video (4).encoded.mp4':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0
: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 640x640 [SAR 1:1 DAR 1:1], q=-1--1, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.35.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1

frame=   38 fps=0.0 q=24.0 size=       0kB time=00:00:01.23 bitrate=   0.3kbits/s speed=2.45x
frame=   82 fps= 81 q=24.0 size=     256kB time=00:00:02.70 bitrate= 776.8kbits/s speed=2.66x
frame=  126 fps= 82 q=23.0 size=     256kB time=00:00:04.16 bitrate= 503.4kbits/s speed=2.72x
frame=  180 fps= 88 q=21.0 size=     512kB time=00:00:05.96 bitrate= 703.0kbits/s speed=2.93x
frame=  223 fps= 88 q=25.0 size=     512kB time=00:00:07.43 bitrate= 564.3kbits/s speed=2.93x
frame=  266 fps= 87 q=23.0 size=     768kB time=00:00:08.86 bitrate= 709.6kbits/s speed=2.91x
frame=  313 fps= 88 q=24.0 size=    1024kB time=00:00:10.43 bitrate= 804.1kbits/s speed=2.94x
[mp4 @ 0x54d3e00] Starting second pass: moving the moov atom to the beginning of the file

frame=  316 fps= 87 q=24.0 Lsize=    1105kB time=00:00:10.53 bitrate= 859.5kbits/s speed=2.92x
video:1101kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.385584%

[libx264 @ 0x54d5e40] frame I:2     Avg QP:19.25  size: 27051
[libx264 @ 0x54d5e40] frame P:314   Avg QP:21.70  size:  3416
[libx264 @ 0x54d5e40] mb I  I16..4: 14.3% 46.3% 39.4%

[libx264 @ 0x54d5e40] mb P  I16..4:  0.9%  0.6%  0.7%  P16..4: 37.8%  7.6%  3.3%  0.0%  0.0%    skip:49.2%
[libx264 @ 0x54d5e40] 8x8 transform intra:32.4% inter:62.5%
[libx264 @ 0x54d5e40] coded y,uvDC,uvAC intra: 55.6% 48.9% 2.9% inter: 7.8% 7.9% 0.0%
[libx264 @ 0x54d5e40] i16 v,h,dc,p:  6% 61% 15% 18%
[libx264 @ 0x54d5e40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu:  9% 38% 21%  4%  3%  3%  6%  5% 11%
[libx264 @ 0x54d5e40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu:  8% 65%  7%  3%  3%  3%  4%  3%  5%
[libx264 @ 0x54d5e40] i8c dc,h,v,p: 58% 29%  9%  4%
[libx264 @ 0x54d5e40] Weighted P-Frames: Y:0.3% UV:0.0%
[libx264 @ 0x54d5e40] ref P L0: 58.5% 10.1% 16.5%  5.7%  5.9%  3.3%  0.0%
[libx264 @ 0x54d5e40] kb/s:855.77
<details>

The current one works like a charm. Maybe there is an incompatible update in ffmpeg/mp4 format? I don't know if Telegram uses ffmpeg internally to play/convert videos, but if yes, then maybe it's a matter of updating it

**Comment by dzek69** [comment]
@john-preston How about fixing playback as well? As noted - new ffmpeg handles this file nicely.
