### ISSUE TITLE
[solved][bug] telegram desktop 1.5.11 save as don't get name of the file

### ISSUE THREAD

**Issue by lordmax** [telegramdesktop/tdesktop#5669]
### Steps to reproduce
1. open a chat or group
2. serch for a file
3. right click on the file and press 'save as'
4. on the pop up windows there isn't file name for saving

### Expected behaviour
Older version and every other software when click for save files the file's name are automatically reported

### Actual behaviour
When open the pop up window for file saving the name of the file is missing

### Configuration
OS: Linux Mint 18.3 Sylvia

**Version of Telegram Desktop:**
1.5.11

**Used theme**:
None

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
I can't reproduce that with some random files (that have names in chat). Maybe you try that with some specific file only?

**Comment by lordmax** [comment]
Hi

No, it isn't a specific file. I download many file of many type (epub, doc, odt, txt, png etc) and the problem is only with the linux desktop version and only with the last version

I attach two images

![telegram_salva_file_popup_browser](https://user-images.githubusercontent.com/349971/52524098-81c06980-2c99-11e9-8802-50158fae1739.png)

![telegram_salva_file_popup_linux_desktop](https://user-images.githubusercontent.com/349971/52524102-884ee100-2c99-11e9-87c3-d375472d45c1.png)


The first one is the expected and regular function, clicking on the download icon open a pop up window with the name of the file. This image is taken from Opera Browser the same minute of the second one on the same machine and OS

The second one is the problematic function, clicking che download icon it open a pop up window without the name of the file. It happen only in the last version of the linux's desktop version

Thanks

**Comment by john-preston** [comment]
@lordmax Can you test previous version (or two, or three) from here: https://github.com/telegramdesktop/tdesktop/releases

to see if it still does work for you in the previous version, but does not in the last one? For me it works fine in Ubuntu in 1.5.11:

![image](https://user-images.githubusercontent.com/17900494/52524373-547db680-2cad-11e9-9a1b-8f9306f6df1f.png)

**Comment by lordmax** [comment]
HI.

thanks for your patiente. ^__^

I haven't an old version of telegram desktop, where I can get one?

**Comment by Johnnynator** [comment]
@lordmax They can be found on the github release tab https://github.com/telegramdesktop/tdesktop/releases

**Comment by lordmax** [comment]
> @lordmax They can be found on the github release tab https://github.com/telegramdesktop/tdesktop/releases

ok, sorry, I'm stupid
^_^

But, thanks, really
You made my day

Tried versione 1.5.8, 1.5.9 and they works fine
Tried versione 1.5.12 and it works fine
And, finally, tried versione 1.5.11 and... it works

It's the flatpak version that doesn't works

It's time to remove flatpak from my system, now and for all.

Sorry for the waste of time and thanks for the support and patiente

**Comment by Johnnynator** [comment]
> > @lordmax They can be found on the github release tab https://github.com/telegramdesktop/tdesktop/releases
> 
> ok, sorry, I'm stupid
> ^_^
> 
> But, thanks, really
> You made my day
> 
> Tried versione 1.5.8, 1.5.9 and they works fine
> Tried versione 1.5.12 and it works fine
> And, finally, tried versione 1.5.11 and... it works
> 
> It's the flatpak version that doesn't works
> 
> It's time to remove flatpak from my system, now and for all.
> 
> Sorry for the waste of time and thanks for the support and patiente

Ok, you probably should report this to https://github.com/flathub/org.telegram.desktop/issues then so they can investigate what is wrong.

Also when reporting bugs it is always helpful to note from where you got telegram.
