### ISSUE TITLE
Add setting to disable taskbar flash

### ISSUE THREAD

**Issue by Raptorsnake** [telegramdesktop/tdesktop#5670]
### Steps to reproduce
1. Have a multi monitor setup
2. Enable auto-hide taskbar
3. Run fullscreen programs on each display
3. Receive a message

### Expected behaviour
Desktop or telegram notification is shown while the taskbar reamins hidden.

### Actual behaviour
Notifications are shown AND the taskbar appears with the flashing Telegram icon.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.5.12 and previous
**Used theme**:
All
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by meandmymind** [comment]
Same here. Very annoying thing that can't be removed from user side (wasted 2 hours searching and trying) but can be easily solved programmatically.

**Comment by meandmymind** [comment]
I assume it has something to deal with native notifications manager in SetForegroundWindow() method
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/win/notifications_manager_win.cpp#L443

**Comment by meandmymind** [comment]
Just to hold it here if somebody will ever address this problem.

As stated in a special tdesktop fork [mutegram](https://github.com/mxs42/mutegram) README, function [FlashBounce()](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/platform/win/notifications_manager_win.cpp#L323) is called with every "alert" that is any unmuted chat notification. Problem can be easily solved by providing an option in notification tray to not flash taskbar icon.

I and hundreds of other users would be really glad for addressing this.

**Comment by meandmymind** [comment]
Same issues over past 3 years:
https://github.com/telegramdesktop/tdesktop/pull/5637
https://github.com/telegramdesktop/tdesktop/issues/906
https://github.com/telegramdesktop/tdesktop/issues/897

**Comment by RomanKornev** [comment]
The option has finally been added! https://github.com/telegramdesktop/tdesktop/commit/6f760d513ea41b8017d4abd5f88e615fd5c0a10e
