### ISSUE TITLE
Groups Descriptions are not syncing

### ISSUE THREAD

**Issue by Fedeparg** [telegramdesktop/tdesktop#5672]
### Steps to reproduce
1. Make a change in the description of a group from Android (Not checked on other platforms) and save it
2. The change should appear on the description in Telegram Desktop, but it doesn't
3. Try to change the description from Telegram Desktop and the changes will not appear in the Android client

### Expected behaviour
Group descriptions should be in sync across all platforms

### Actual behaviour
Telegram Desktop seems to have trouble syncing groups descriptions. 

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.5.12
**Used theme**:
Default Night Mode
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Marzal** [comment]
Same problem here, but not in all groups.

**Configuration**

**Operating system:**
Linux 5.3.15 (ArchLinux+KDE-Plasma)

**Version of Telegram Desktop:**
1.8.15

**Used theme:**
Default Night Mode

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1276
