### ISSUE TITLE
[Feature request] Get group admin list

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [telegramdesktop/tdesktop#5673]
On big groups it is difficult to detect admins.
This feature is need because some times we need there permissions to write some messages, and there is lots of others cases.

There can be different  solutions.
1. Make to show them first.
2. Make special button on group info.
3. Make special filter on members search, or button to filter here.

There may be different solutions but this feature is very needed.

**Comment by ArmeF97** [comment]
Duplicate to https://github.com/telegramdesktop/tdesktop/issues/3452
