### ISSUE TITLE
Could not add user. Try again later

### ISSUE THREAD

**Issue by Olegt0rr** [telegramdesktop/tdesktop#5677]
My user send me report that he can't add my bot to his group.
I can't add it too. Telegram client shows error: Could not add user. Try again later

You can watch it here: 
https://youtu.be/nj1x0dOBcgc

### Steps to reproduce
1. Join https://t.me/mafiadavydiv
2. Try to add @TrueMafiaBot

I have tried to create another group - it's not reproducing.

### Expected behaviour
Bot added.

### Actual behaviour
"Could not add user. Try again later"

**Comment by 23rd** [comment]
Did you try in mobile client?

**Comment by john-preston** [comment]
@Olegt0rr Right now only admins can add members to public groups.
