### ISSUE TITLE
[Bug] Some messagges won't load.

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#5679]
### Steps to reproduce
1.  Chat in a group with multiple devices

### Expected behaviour
Every message is seen in all devices

### Actual behaviour
Tdesktop doesn't show some messages, android version does. I have to close telegram and re-open it in order to see all messagges

### Configuration
**Operating system:** Win 10

**Version of Telegram Desktop:** 1.5.12, 1.5.15

**Used theme**: Dark

**Comment by ArmeF97** [comment]
Last message in desktop:
![immagine](https://user-images.githubusercontent.com/6240983/52564479-a08f3f00-2e04-11e9-99f4-343071ac4391.png)

Last message in android:
![immagine](https://user-images.githubusercontent.com/6240983/52564533-bef53a80-2e04-11e9-969d-e659c6cdbd8f.png)

**Comment by ArmeF97** [comment]
![immagine](https://user-images.githubusercontent.com/6240983/52623629-1949d600-2ead-11e9-8963-6b06e52249cc.png)
Today this

**Comment by ArmeF97** [comment]
Still bugged v 1.5.15
![immagine](https://user-images.githubusercontent.com/6240983/52709817-11159780-2f8e-11e9-9838-7e645184d3d1.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1276
