### ISSUE TITLE
Cannot delete private message in group chat

### ISSUE THREAD

**Issue by vokamut** [telegramdesktop/tdesktop#5681]
### Steps to reproduce
1. Have group with unread personal messages
2. Delete group messages history

### Expected behaviour
Delete group messages history with personal messages

### Actual behaviour
The icon @ in the group is not lost and it is possible to go to a remote message.
Screenshot: https://i.imgur.com/4pPpbHe.png

### Configuration
**Operating system:**
openSUSE Tumbleweed 20190205
**Version of Telegram Desktop:**
1.5.12
**Used theme**:
Blue

**Comment by Aokromes** [comment]
workarround: restarting telegram removes it.
