### ISSUE TITLE
Not working bold font on Kubuntu.

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [telegramdesktop/tdesktop#5682]
In editor if i tried to make my text bold it has no effect.
If I post to anyone they can see bold, but I don't see my or others bold. May be fonts problem or something else.

If uninstall open sans font, bold returns, but this is not the solution.

### Configuration
**Operating system:** Kubuntu 18.10

**Version of Telegram Desktop:** 1.5.12

**Used theme**: Default.

**Comment by MasterGroosha** [comment]
Most likely same issue as #4095

**Comment by joserprieto** [comment]
Same here, with Linux Mint.

### Configuration
**Operating system:** Linux Mint 19 (Tara)

**Version of Telegram Desktop:** v 1.5.12 09.02.19

**Used theme**: Cinnamon.

```
$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="19 (Tara)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19"
VERSION_ID="19"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tara
UBUNTU_CODENAME=bionic
```

The issue is with **my** bold text, on Telegram Desktop; bold text of others, i think that i can see well; i'm making some tests...

**Comment by joserprieto** [comment]
Same chat on group; the "sorry" is on bold:

Linux Mint, Telegram Desktop:

![image](https://user-images.githubusercontent.com/1142233/52639087-bf103b80-2ed3-11e9-9e27-7aee76446b57.png)

Mobile, Android 8, Moto G5 Plus:

![image](https://user-images.githubusercontent.com/1142233/52639092-c5061c80-2ed3-11e9-9af7-e502abebb9ae.png)

**Comment by xvitaly** [comment]
Install version from Ubuntu repositories.

**Comment by joserprieto** [comment]
It working for me, @xvitaly 
Thanks!

Repo used:

[atareao telegram repository](https://launchpad.net/~atareao/+archive/ubuntu/telegram)

Commands:

```bash
sudo add-apt-repository ppa:atareao/telegram
sudo apt update
sudo apt install telegram-desktop
```

**Comment by xvitaly** [comment]
> atareao telegram repository

Do not trust repositories, created by users. Telegram Desktop can be installed from main Debian/Ubuntu repo.

**Comment by joserprieto** [comment]
But, what version (on debian/ubuntu repos)?

It's a PPA repository on Launchpad...

**Comment by joserprieto** [comment]
Bionic (LTS):

https://packages.ubuntu.com/bionic/telegram-desktop

version 1.2.17-1

Cosmic (18.10, non LTS):

https://packages.ubuntu.com/cosmic/telegram-desktop

version 1.4.0-1

Disco (dev; _The Ubuntu release that will be delivered in April 2019, designated 19.04._"):

https://packages.ubuntu.com/disco/telegram-desktop

version 1.5.11-1

https://packages.ubuntu.com/search?keywords=telegram-desktop&searchon=names

(For versions minor to bionic, telegram-desktop package isn't available....)

**Comment by llybin** [comment]
Same here. With this patch works correctly: https://git.archlinux.org/svntogit/community.git/tree/trunk/demibold.patch?h=packages/telegram-desktop

**Comment by rastersoft** [comment]
I have version 1.6.7 (seems the current stable) and this also fails. I use Debian SID.

**Comment by Dmitrij-Polyanin** [comment]
Kubuntu 18.04.2 LTS
Telegram 1.6.7
Also fail.

**Comment by llybin** [comment]
Remove ttf-opensans, bold will works.

**Comment by kraftwerk28** [comment]
> Remove ttf-opensans, bold will works.

Thank you so much ^-^

**Comment by rastersoft** [comment]
I have Debian SID and have this same problem, but I don't have ttf-opensans installed.

**Comment by llybin** [comment]
Try to find like that(if I not mistake in command). Deb has another naming.
apt list -a --installed *font*

Patch above show that there have some trouble with this fonts..

**Comment by Dmitrij-Polyanin** [comment]
There is some packages depends on opensans.
In my case pgadmin. If I remove opensans, pgadmin will be removed too :(

**Comment by llybin** [comment]
Yes, it's a not good solution, but works. Use console and psql, be real Linux user 😎

**Comment by kraftwerk28** [comment]
> There is some packages depends on opensans.
> In my case pgadmin. If I remove opensans, pgadmin will be removed too :(

You can just disable OpenSans, not removing it, in Font manager

**Comment by Dmitrij-Polyanin** [comment]
> You can just disable OpenSans, not removing it, in Font manager

Disabling works fine! This is solution for me. pgadmin still works.

**Comment by maximal** [comment]
Same issue on Ubuntu **19.04** with Telegram Desktop **1.7.5 beta**.

**Comment by marcogiannini** [comment]
the bug is still present on elementary OS 5.0 Juno

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4095
