### ISSUE TITLE
Crash with passcode (v 1.5.13)

### ISSUE THREAD

**Issue by misteriosojo** [telegramdesktop/tdesktop#5683]
### Steps to reproduce
1. Update to v 1.5.13
2. Launch Telegram
3. When you give the passcode to unlock Telegram, it unlocks and it crashes immediately
(I already had passcode activated, I don't know if the issue happens also if you activate the passcode just after the update)

### Expected behaviour
Telegram should unlock normally as always.

### Actual behaviour
Crash.
The password is correct, but in log stay that it isn't...

### Configuration
**Operating system:**
Tested on Windows 10 and Ubuntu 18.04.2 LTS

**Version of Telegram Desktop:**
v1.5.13  (with v1.5.12 it worked normally)

**Used theme**:
Dark

<details><summary><b>Logs</b>:</summary>
<br>[2019.02.12 14:31:18] Launched version: 1005013, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
<br>[2019.02.12 14:31:18] Executable dir: /opt/Telegram/, name: Telegram
<br>[2019.02.12 14:31:18] Initial working dir: /home/<b><i>editMyUser</i></b>/
<br>[2019.02.12 14:31:18] Working dir: /home/<b><i>editMyUser</i></b>/.local/share/TelegramDesktop/
<br>[2019.02.12 14:31:18] Command line: /opt/Telegram/Telegram --
<br>[2019.02.12 14:31:18] Executable path before check: /opt/Telegram/Telegram
<br>[2019.02.12 14:31:18] Logs started
<br>[2019.02.12 14:31:18] Fontconfig version: 2.12.6.
<br>[2019.02.12 14:31:18] Connecting local socket to /tmp/<b><i>editMyUUID</i></b>-{<b><i>editMyUUID</i></b>}...
<br>[2019.02.12 14:31:18] Socket connect error 0, starting server and app...
<br>[2019.02.12 14:31:18] Moved logging from '/home/<b><i>editMyUser</i></b>/.local/share/TelegramDesktop/log_start0.txt' to '/home/<b><i>editMyUser</i></b>/.local/share/TelegramDesktop/log.txt'!
<br>[2019.02.12 14:31:18] Opened '/home/<b><i>editMyUser</i></b>/.local/share/TelegramDesktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 4891
<br>[2019.02.12 14:31:19] Font Error: could not resolve 'Open Sans Semibold' font, got 'Open Sans'.
<br>[2019.02.12 14:31:19] Update Info: MTP is unavailable.
<br>[2019.02.12 14:31:19] App Error: _basePath is empty in writeSettings()
<br>[2019.02.12 14:31:19] Primary screen DPI: 96
<br>[2019.02.12 14:31:19] Could not load 'ayatana-appindicator3' with version 1 :(
<br>[2019.02.12 14:31:19] Error: failed to load 'gdk_x11_drawable_get_xdisplay' function!
<br>[2019.02.12 14:31:19] Getting DE, XDG_CURRENT_DESKTOP: 'ubuntu:GNOME'
<br>[2019.02.12 14:31:19] Getting DE, DESKTOP_SESSION: 'ubuntu'
<br>[2019.02.12 14:31:19] Getting DE, KDE_SESSION_VERSION: ''
<br>[2019.02.12 14:31:19] DE: Ubuntu
<br>[2019.02.12 14:31:19] Tray Icon: Try Qt = [TRUE], Prefer appindicator = [TRUE]
<br>[2019.02.12 14:31:19] App Info: reading settings...
<br>[2019.02.12 14:31:19] App Info: reading encrypted settings...
<br>[2019.02.12 14:31:19] Lang Info: Loaded cached, keys: 2201
<br>[2019.02.12 14:31:19] OpenAL Logging Level: (not set)
<br>[2019.02.12 14:31:19] Audio Playback Devices: OpenAL Soft
<br>[2019.02.12 14:31:19] Audio Playback Default Device: OpenAL Soft
<br>[2019.02.12 14:31:19] Audio Capture Devices: Razer ManO'War Analog Mono;Monitor of Razer ManO'War Analog Stereo;Monitor of Built-in Audio Digital Stereo (IEC958);Built-in Audio Analog Stereo
<br>[2019.02.12 14:31:19] Audio Capture Default Device: Razer ManO'War Analog Mono
<br>[2019.02.12 14:31:19] App Info: reading map...
<br>[2019.02.12 14:31:19] App Info: bad decrypt key, data not decrypted - incorrect password?
<br>[2019.02.12 14:31:19] App Info: could not decrypt pass-protected key from map file, maybe bad password...
<br>[2019.02.12 14:31:19] Tray Icon: Using appindicator tray icon.
<br>[2019.02.12 14:31:19] Found Unity Launcher entry telegramdesktop.desktop!
<br>[2019.02.12 14:31:20] App Info: reading map...
<br>[2019.02.12 14:31:20] App Info: reading encrypted map...
<br>[2019.02.12 14:31:20] App Info: reading encrypted user settings...
<br>[2019.02.12 14:31:20] App Info: encrypted user settings read.
<br>[2019.02.12 14:31:20] App Info: reading encrypted mtp data...
<br>[2019.02.12 14:31:20] Map read time: 211
<br>[2019.02.12 14:31:20] TCP Error: network - Network unreachable
<br>[2019.02.12 14:31:20] HTTP Error: network error 99 - Network unreachable
<br>[2019.02.12 14:31:20] Export Info: Destroy top bar by controller removal.
</details>

**Comment by nshopik** [comment]
1.5.13 crashes even without passcode for me
