### ISSUE TITLE
Emoji do not align with text

### ISSUE THREAD

**Issue by magnus-gross** [telegramdesktop/tdesktop#5685]
![img](https://i.imgur.com/WfGqyTt.png)

As you can see in the screenshot, Emojis do not align with the text.

How to reproduce:
1. Type an emoji
2. Type text after the emoji

Expected behaviour:
The text is on the same height level

Actual behaviour:
The Emoji suddenly changes its vertical level, as soon as you type text

Version: 1.5.12 from Arch repos

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by magnus-gross** [comment]
No, they look aligned now.

![Screenshot_20200127_201143](https://user-images.githubusercontent.com/21310755/73205440-4ab0c580-4141-11ea-923f-a599fe4953e8.png)
