### ISSUE TITLE
Gdk-CRITICAL: gdk_window_thaw_toplevel_updates

### ISSUE THREAD

**Issue by ZYZ64738** [telegramdesktop/tdesktop#5687]
### Steps to reproduce
Just try to start telegram-desktop.There is no diffrence in behavior starting it by "XFCE-starter" or by using console-command

### Expected behaviour
Starts Telegram in a window and keep it open

### Actual behaviour
Starts Telegram in a window and closes imediatley

### Configuration
**Operating system:**
Arch Linux (x86_64 Linux 4.20.7-arch1-1-ARCH)

**Version of Telegram Desktop:**
1.5.13-1

**Used theme**:
dunno - cannot keep telegram open to check this out. i dont know a alternative way either.

screenfetch:

OS: Arch Linux 
Kernel: x86_64 Linux 4.20.7-arch1-1-ARCH
Resolution: 5760x1200
DE: XFCE4
WM: Xfwm4
WM Theme: Arc-Dark
GTK Theme: X-Arc-Shadow [GTK2]
Icon Theme: Papirus-Dark
Font: Noto Sans 10
CPU: Intel Core i7-4770 @ 8x 3.9GHz [27.8°C]
GPU: GeForce GT 630
RAM: 2298MiB / 15968MiB

<details><summary><b>Logs</b>:</summary>
(telegram-desktop:2726): Gdk-CRITICAL **: 08:58:42.381: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Speicherzugriffsfehler (Speicherabzug geschrieben)
</details>

Downgrading to 1.5.12-1  "solves" it

**Comment by john-preston** [comment]
@ZYZ64738 Try the 1.5.15 version, the crash should be fixed there.

**Comment by svloginov** [comment]
@ZYZ64738  Fellow Arch Linux user here. I can confirm that telegram-desktop-1.5.15-1 installed via pacman does not crash.

**Comment by ZYZ64738** [comment]
I confirm: telegram-desktop-1.5.15-1 @ arch runs like expected - thnx for your support.
