### ISSUE TITLE
Close the app doesn't kill the process Ubuntu 18.04

### ISSUE THREAD

**Issue by Mfernand** [telegramdesktop/tdesktop#5688]
I'm in Ubuntu 18.04 and after a while with the laptop running close the desktop Telegram but I still receive notification and I can see the process with the top command

**Comment by xvitaly** [comment]
Install Gnome tray extension or disable system tray icon in Telegram Desktop's settings.

**Comment by Mfernand** [comment]
Disabling system tray icon in Telegram Desktop's settings works. but the tray icons never shows
