### ISSUE TITLE
[Bug] Invalid username if starts or ends with underscore symbol

### ISSUE THREAD

**Issue by ezdev128** [telegramdesktop/tdesktop#569]
I just found that the usernames like @abcde_ or @_abcde are invalid. Why?

**Comment by auchri** [comment]
Because the telegram team has decided against it. And they are also not looking nice :yum:

**Comment by vladik2738** [comment]
It's version 1.1.15 and it still says next:
![image](https://user-images.githubusercontent.com/35642018/52738799-1ef00a80-2fd8-11e9-82ff-b7609b7faba0.png)

**Comment by stek29** [comment]
@vladik2738 there are also some usernames which are just banned, and you also can't take usernames with telegram in them, and maximum length limit also exists, and so on.
Should all of those limitations be listed?

**Comment by vladik2738** [comment]
> @vladik2738 there are also some usernames which are just banned, and you also can't take usernames with telegram in them, and maximum length limit also exists, and so on.
> Should all of those limitations be listed?

Yes. If you say that underscores are allowed they SHOULD be allowed. Other limitations could be put in external link, or menu.

Before you sign a document, do you read it? Or just read a header? That's why, everybody has to know the CORRECT information.

**Comment by stek29** [comment]
@vladik2738 this ain't a document you sign with anyone. it's up to telegram to decide which usernames are allowed on their platform and which are not.
Sometimes obscurity is needed for system to function properly.

**Comment by vladik2738** [comment]
> @vladik2738 this ain't a document you sign with anyone. it's up to telegram to decide which usernames are allowed on their platform and which are not.
> Sometimes obscurity is needed for system to function properly.

So you say that's the reason why they say undersores are allowed? Is it the reason why they can't just change that text? lol. *applause*

**Comment by 100rabhcsmc** [comment]
> It's version 1.1.15 and it still says next:
> ![image](https://user-images.githubusercontent.com/35642018/52738799-1ef00a80-2fd8-11e9-82ff-b7609b7faba0.png)

thanks man its very helpful
