### ISSUE TITLE
[Feature request] Cross Chat references

### ISSUE THREAD

**Issue by felix-d-git** [telegramdesktop/tdesktop#5690]
Let's say A and B are both in Group G.

It would be awesome for A to send a direct message to B:

Hey A, have you seen what XX posted in [Group:G].

So B would be notified that he/she might look into G to see what's written there.

[Group:G] would be clickable and open GroupChat G.

**Comment by RememberTheAir** [comment]
Ideally tdesktop could support tg://openmessage urls (as the android app [already does](https://t.me/KeralaGramChannel/1333)) if this becomes an approved/standard feature

**Comment by Aokromes** [comment]
this was implemented long time ago.

**Comment by felix-d-git** [comment]
How does one find the message_id on a desktop installation?

**Comment by RememberTheAir** [comment]
@felix-d-git you can jusr right-click and copy the message link
