### ISSUE TITLE
File dialog (for attachments) styling issues on Ubuntu when installed with snap

### ISSUE THREAD

**Issue by jasny** [telegramdesktop/tdesktop#5691]
### Steps to reproduce
1. Install Telegram using **snap**
2. Click on the 'attachment' button

### Expected behaviour
![screenshot from 2019-02-13 20-01-39](https://user-images.githubusercontent.com/100821/52736545-6374a980-2fca-11e9-91f4-e282cab09a8b.png)

### Actual behaviour
Icons are missing and there are other styling issues

![screenshot from 2019-02-13 20-03-31](https://user-images.githubusercontent.com/100821/52736608-8737ef80-2fca-11e9-9628-39628e44cdd1.png)

### Configuration
**Operating system:**
Ubuntu 18.04

**Version of Telegram Desktop:**
1.5.12

**Used theme**:
Blue

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by jasny** [comment]
I don't think this issue was ever solved, but Telegram switched to the old gnome file dialog. This doesn't match the OS style and honestly looks like crap. So I hope this switch is temporary until the issue is actually fixed.

![Screenshot from 2020-01-27 09-00-30](https://user-images.githubusercontent.com/100821/73158348-dd227c00-40e3-11ea-9613-6b0b1ff9bade.png)

**Comment by Aokromes** [comment]
there was a bug with recent 1.9.x builds that's why i ask if it's fixed on 1.9.8

**Comment by ilya-fedin** [comment]
@jasny can you try 1.9.9?
