### ISSUE TITLE
Invalid username @elephant.

### ISSUE THREAD

**Issue by vladik2738** [telegramdesktop/tdesktop#5692]
### Steps to reproduce
1. Go to telegram desktop or any telegram app.
2. Try to change your username to @elephant

### Expected behaviour
Should say "This username is available" or "This username is already occupied" as this nickname has only a-z characters.

### Actual behaviour
Tell's "This username is invalid".

### Configuration
**Operating system:** GNU/Linux x64

**Version of Telegram Desktop:** 1.5.11

**Used theme**: Default night mode

**Comment by MasterGroosha** [comment]
If you send that username to yourself and click on it with Telegram Desktop, you'll see message "This channel was blocked for spreading pornographic content".

This is not TDesktop's issue at all.
