### ISSUE TITLE
auto-lock windows,miss recording voice message

### ISSUE THREAD

**Issue by muhammadzadeh** [telegramdesktop/tdesktop#5695]
### Steps to reproduce
1. auto lock is enabled and scheduled 5min
2. recording voice message with a duration greater than 5min
3. screen will be locked
4. voice message lost
5.and I should record again😢

### Configuration
**Operating system: winndows 10**

**Version of Telegram Desktop: 1.5.15**

**Used theme: default theme, night mode**

**Comment by john-preston** [comment]
@muhammadzadeh Thanks for your report!
