### ISSUE TITLE
Non-english download path becomes escaped

### ISSUE THREAD

**Issue by mikken** [telegramdesktop/tdesktop#5697]
### Steps to reproduce
Set a download path in Preferences (I set default). My system download path is _/home/rondo/Загрузки_.

### Expected behaviour
Downloaded files should go into specified directory.

### Actual behaviour
Directory named _'xd0\x97\xd0\xb0\xd0\xb3\xd1\x80\xd1\x83\xd0\xb7\xd0\xba\xd0\xb8'_ is created in my home dir, with _Telegram_ dir inside.

### Configuration
**Operating system:** Gentoo

**Version of Telegram Desktop:** 1.5.11 (built from source)

**Comment by mikken** [comment]
This behaviour is still observed.

**Comment by ilya-fedin** [comment]
> This behaviour is still observed.

I can't reproduce, I guess you have unconfigured locale.

**Comment by mikken** [comment]
Okay, looks fixed, and I already had latin path in Telegram's settings as a work-around, it's now Plasma's Bluetooth download feature that also creates this weird dirs.
