### ISSUE TITLE
Message too small in channel

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#5699]
See this message https://t.me/KeralaGramChannel/1333

This is how I see it
![immagine](https://user-images.githubusercontent.com/6240983/52899896-cf842700-31ef-11e9-9903-c1f287683a46.png)

Isn't it too small compared to the one down it? 

I suggest to enlarge it a little

**Comment by Edicksonjga** [comment]
I think there should be more "stuffing" on the sides of the multimedia to make the message look a little better. Android I think uses 30 characters per line.

**Comment by ArmeF97** [comment]
Fixed
