### ISSUE TITLE
Feature request: Add a shortcut to change between contacts 

### ISSUE THREAD

**Issue by carrerasrodrigo** [telegramdesktop/tdesktop#570]
Would be awesome to have a shortcut like 'slack' to change between contacts. I could work like this:
1. press a shortcut like super + k
2. an small windows popups and allows to type the first letters of a name
3. a contact is selected
4. press enter to go to the conversation

I think this could increase a lot the speed changing between chats.

**Comment by Sietsem** [comment]
Note that if you press escape you also gain focus in the search field and after searching you can select a contact with the arrow keys and enter.

**Comment by auchri** [comment]
Or switch between the contacts with ctrl+page up/page down
