### ISSUE TITLE
"Report" box in private group has too options

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#5702]
This is the report box

![immagine](https://user-images.githubusercontent.com/6240983/52913322-4a674380-32bd-11e9-8505-10e066d7f41e.png)

According to [Telegram TOS](https://telegram.org/tos), violence and pornagraphy is banned on public groups, public channels and public bots, not private ones. Yet users are able to report for violence and porn in private groups and channels.

Those tho options should be removed, when in a private group or channel

![immagine](https://user-images.githubusercontent.com/6240983/52913350-96b28380-32bd-11e9-82af-4cc4124daf63.png)

**Comment by UniqueUname** [comment]
Just don't share porn or gore

**Comment by Mushebeq** [comment]
Gore is not banned i guess

**Comment by ArmeF97** [comment]
I don't share none of this, in any chat, even in private.
What I am saying is different

**Comment by stek29** [comment]
"Private" groups with publicly accessible and wide-spread links are considered public too.
If somebody in the group is reporting things in it, then it's not so private anymore.

**Comment by ArmeF97** [comment]
> "Private" groups with publicly accessible and wide-spread links are considered public too.

@stek29  I can't find this in Telegram TOS, can you please link me to a verified source for this?

**Comment by stek29** [comment]
@ArmeF97 I don't think there is a verified source for that. You either believe me (a complete stranger who has nothing to do with telegram team) and facts, or you don't.

It any case, it's definitely not the right place to ask for this.

**Comment by UniqueUname** [comment]
> It any case, it's definitely not the right place to ask for this.
^ This right there. Plus, why do you want to get these options removed? It could help somebody else even if you think they are useless.

**Comment by ArmeF97** [comment]
> > It any case, it's definitely not the right place to ask for this.
> 
> ^ This right there. Plus, why do you want these options removed? It could help somebody else even if you think they are useless.

@UniqueUname  
If I wanted to start a porn group, why should I get reported if I'm not breaking Telegram TOS?

**Comment by korangu** [comment]
Telegram team is fear of Google Play Store and AppStore. They will block any channel,bot, group regardless of public

**Comment by ArmeF97** [comment]
We are talking about telegram desktop

**Comment by UniqueUname** [comment]
> @UniqueUname
> If I wanted to start a private porn group, why should I get reported if I'm not breaking Telegram TOS?


Because there is a slight chance of something illegal could be involved around your "private" porn group.

**Comment by ArmeF97** [comment]
> please don't use tg as a porn hosting service.

I don't think you are entitled to say that. Telegram TOS says what Telegram can be used for, and what not.

**Comment by UniqueUname** [comment]
Well if you are taking a suggestion as an order, that's true.
The issue is closed. It is your problem if you get reported for your actions now.

**Comment by ArmeF97** [comment]
> Well if you are taking a suggestion as an order, that's true.

Can you explain better? I don't understand

> The issue is closed. It is your problem if you get reported for your actions now.

I've never shared porn and I'll never do that
