### ISSUE TITLE
#bug or #feature In Recent Actions the Deleted messages take the date of elimination and do not show the data of when they were sent.

### ISSUE THREAD

**Issue by Edicksonjga** [telegramdesktop/tdesktop#5706]
### Steps to reproduce
1. Delete a message
2. Go to recent actions.
3. The deleted message does not show the shipment data.
4. The deleted message shows the data of when it was deleted.
### Expected behaviour
The message should remain with the data when it was sent and the date of elimination remain as it is (floating when moving).

### Actual behaviour
The deleted message takes the date and time when it was deleted.

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.5.15 and many previous versions.

**Used theme**: Default

**Comment by Aokromes** [comment]
maybe a tooltip can be added of when the message was send.

**Comment by Remu-rin** [comment]
Not resolved.
