### ISSUE TITLE
Crash when changing the language.

### ISSUE THREAD

**Issue by Edicksonjga** [telegramdesktop/tdesktop#5707]
### Steps to reproduce
1. Change the language from the settings or with a t.me/setlanguage link ...
2. Confirm the Telegram restart.
3. When starting "SETTINGS" telegram, enter any of the SETTINGS menu options from Edit profile to Languages.

### Expected behaviour
You must be able to enter the first 6 options of the configuration menu when restarting Telegram.

### Actual behaviour
You can not enter the first 6 options of the configuration menu when you restart Telegram. You have to exit "Settings" and re-enter.

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.5.15

**Used theme:** Default

**Comment by Gliscor** [comment]
I tried to reproduce this bug with no luck.

**Comment by Edicksonjga** [comment]
@Gliscor It still happens to me.

**Comment by url-bird-url** [comment]
In my case, when changing the language the background is reset. Windows 10/1.5.15/Matrix

**Comment by Edicksonjga** [comment]
The problem no longer occurs, I have tried to reproduce many times with different languages, without "success" and that is very good. I do not understand how, but, Closed.
