### ISSUE TITLE
Telegram: please take a stand on accessibility!

### ISSUE THREAD

**Issue by mrkiko** [telegramdesktop/tdesktop#5708]
Hello guys. I am posting this message here, even if a little bit off-topic: can you help me making my
voice heard? I am posting here because it was here where I found helpful and nice people, exchanging ideas, making me,
and other affected users, feel considered, not leaving us alone, ignoring our words. Because I feel like this is
happening by the entire Telegram "organization": I use this word since I can't find a better one. It's currently not
possible for a blind user to use Telegram from an Android device, an iOS device, or a Windows PC. We saw lots of
features getting implemented over these years, but no single bit related to accessibility was ever added. Now, i can't
even access the iOS App's settings. You got lots of success guys: and I am happy for you, leaving alone the technical
side of things (MTProto...). But with success comes something we might call power, and with it something we might call
responsibilities. Development is not easy, especially when you want to do it well and implement a whole lot of features
like it happened with Telegram. But let's be honest, it's not like you miss the resources to do so, even considering
you may not use standard UI elements to make the App look&feel finer. So I feel I can say that, by not implementing
accessibility features, you're actively stopping people from partecipating in all of the activities taking place on the
Telegram network. You're actively building something we might compare to "architectural barriers" in real life.
And unfortunately, the distiction between our digital and real lives can become very blurred some times, just look at how often you pick up
your smartphone. Is this the society you want to live in? A society where a person with a disability gets simply
ignored, isolated, discarded? Is this what the Telegram organization wants to be? Hey guys, after all there a lots of
very important, but unaccessible, websites and maybe Apps: sometimes run by governments and other entities you're
forced to cope with. There are lots of architectural barriers in otherwise beautiful places, stopping people with
disabilities from enjoying them. And so on. Is this an acceptable reason for you to continue ignoring this issue,
company-wide? Can you (telegram.org) make a choice and release a public statement on that, please? This message is not
intended to criticise developers, especially (but not exclusively) volunteers ones, who do this for fun, for building a
better world or for other reasons: I can only say "Thank You" to them, and express them my gratitude for giving their
effort to the world as a gift. Honestly, Thank You. What I am criticising here, is a company-wide policy, even if an
unwritten one. Can we discuss about it? Please guys, take a stand! I am not writing this with the intention of making
bad publicity to this project: it would be simply unfair, don't do this!! Just to start a consctructive talk about
this whole situation.

Note: at the time of this writing (Mon Feb 18 06:41:37 CET 2019), it is not possible to post issues on
https://github.com/TelegramOrg/Telegram-X-iOS
("Issues are disabled for this repo").

**Comment by ArmeF97** [comment]
Issues are open to the base of the fork your linked. We should open issues in android repo

**Comment by mrkiko** [comment]
Thank you very much for your feedback!
For this specific case, what do you recommend?

**Comment by stek29** [comment]
I'd recommend to ask telegram on Twitter (or via inapp support).

I'm closing your issue in favor of #476, although I appreciate your dedication and your great post.

**Comment by john-preston** [comment]
@mrkiko I will be happy to see some work from the community (in PR form) with some basic starting points for adding accessibility support to tdesktop. Right now I have no idea how it should be done.

**Comment by ArmeF97** [comment]
@john-preston  with "ideas" you mean code or simply ideas? If someone were to give you simply ideas, will you implement them?

**Comment by john-preston** [comment]
@ArmeF97 No, sorry, I mean code samples in terms of tdesktop code base.

**Comment by ArmeF97** [comment]
@john-preston  So if you, the tdesktop developer, has no idea how to do it, we are in big trouble 😆

**Comment by mrkiko** [comment]
@stek29 @john-preston @ArmeF97 c
thank you guys for the feedback.

Please do not close this issue - and it's not duplicate of #476: here we
are trying to deal with the same problem but with a wider angle.
i apreciate your welcoming of PRs as well - keeping open to contributions
is fundamental for the health of a project. Still, implementing and
maintaining accessibility properly is something that should be done day by
day, and required a good amount of architectural work.
That's why it would be beneficial if we could talk about this, and take a
decision, and I think it's fair to say that not only the community needs
to be part of that.
Please guys, let's keep this open and as honest as possible, as it is
right now.

**Comment by mrkiko** [comment]
@stek29 I already tried the in-app support, more than once.
Those guys have been very nice and kind, but in the end no result was
gained from my side. And I actually would like to say Yhank You to them as
well!

I am not going the twitter road: I would not like to be overexposed in
social networks at the moment. And also I would like to avoid bad
publicity as I said. I just would like to start a constructive discussion.
Code is important, but people are even more, in my opinion.
Thank you again to all!

**Comment by john-preston** [comment]
@ArmeF97 Maybe someone with experience in adding accessibility support to very complex custom widgets has a much better understanding of the way it should be done.
