### ISSUE TITLE
Request for a more complet font family

### ISSUE THREAD

**Issue by Tids** [telegramdesktop/tdesktop#5709]
Right now Telegram-Desktop is using OpenSans. This is one of the less complete "big" font famililies known to me. Since manjy of my contacts are using special characters for the username or sometimes in chat, on the desktop it's more like a tofu fight, then a chat.

For example "Fabish" in some special character fonts:
## Telegram-Desktop
![bildschirmfoto-20190218144841-168x175](https://user-images.githubusercontent.com/18744080/52955225-6dacf400-338c-11e9-9689-acebb996df78.png)

## Telegram Android
![screenshot_20190218-144858__01](https://user-images.githubusercontent.com/18744080/52955467-05124700-338d-11e9-825e-b814869a65b9.jpg)

For example the Noto Family is mostly complete, also adobe source sans/code/serif pro is something more complete. Another option would be to let telegram use the systemfont

**Comment by mikhailnov** [comment]
> Another option would be to let telegram use the systemfont

+1 for this. Debian (and so Ubuntu) pathes telegram-desktop to use system font.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4072
