### ISSUE TITLE
TDesktop froze my system by taking 65+ GB of memory

### ISSUE THREAD

**Issue by delivrance** [telegramdesktop/tdesktop#5713]
Not a real issue, I'm not even sure if I could help troubleshooting this because the system froze completely and I had to reset. I just found it funny ^^

![image](https://user-images.githubusercontent.com/14043624/53026469-483ee980-3463-11e9-8cd4-c8de894277a2.png)

**Comment by Aokromes** [comment]
you don't even put telegram version, nor os version, supose or linux x64 or macos because no crash on 2gb of ram..... very likely duplicate ticket.

**Comment by FawLog** [comment]
That's macos and I think it's a native app, not a Telegram desktop.
