### ISSUE TITLE
Follow default GTK theme?

### ISSUE THREAD

**Issue by orschiro** [telegramdesktop/tdesktop#5714]
Hi all, 

I know Telegram Desktop is a Qt app. 

Despite that, is there any way I can make it follow my default GTK theme?

I am on Xfce which is a GTK desktop.

In the morning/evening I tend to use a dark GTK theme and during the day, switch to a light theme.

All my apps follow this design which gives me a nice dark/white mode experience. 

The only one that doesn't is Telegram. I know it has a built-in dark mode which I can enable. But I need to switch this manually since it's not following my GTK theme. 

Related question: is it possible to toggle dark mode using the command-line? Then I could create a script that adjusts Telegram according to my GTK theme. 

Thank you! 🎉😄

**Comment by RadRussianRus** [comment]
1. TDesktop supports color themes. You can find some in t.me/themes or make your own.
2. AFAIK, there is no such option to toggle dark mode from command line.

**Comment by orschiro** [comment]
@RadRussianRus thank you for your input. If I recall correctly, the Android version has an auto-night-mode feature. Meaning it switches automatically to a night mode based on time of the day. 

Can we achieve the same on Telegram Desktop?

**Comment by ilya-fedin** [comment]
> Despite that, is there any way I can make it follow my default GTK theme?

That would be harmful, since will create a conflict with Qt's platformtheme plugins

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4918
