### ISSUE TITLE
When compiling I encountered the following error. in ubuntu 14.04

### ISSUE THREAD

**Issue by archive-me** [telegramdesktop/tdesktop#5717]
![2](https://user-images.githubusercontent.com/42973767/57568441-c8d70b80-73fc-11e9-88ea-334fbb5c5c32.png)

**Comment by Johnnynator** [comment]
Firstly pls make sure that your issue report is properly formatted. Secondly what compiler and compiler version are you using. You need at least gcc-7.2.

**Comment by Aokromes** [comment]
build system changed a lot since 2019, try on updated system.
