### ISSUE TITLE
Telegram on Windows Desktop ignores DO NOT AUTO RAISE setting for windows

### ISSUE THREAD

**Issue by rterbush** [telegramdesktop/tdesktop#5719]
### Steps to reproduce
1. On Windows 10, configure focus follows mouse and DO NOT AUTO RAISE for window behavior.
2. Move mouse over partly obscured Telegram window, it instantly raises to top.

### Expected behaviour
Telegram seems to be ignoring the window behavior setting. It should get focus when the pointer is over the window, but it should NOT raise.

### Actual behaviour
Telegram window raises when it gets pointer focus.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.5.15

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by miiichael** [comment]
Noticed this following an upgrade of Win7->Win10. I have focus-follows-mouse (but not auto-raise) enabled. When focus goes from the desktop (or certain apps such as mobaxterm) to Telegram, it auto-raises. When focus goes from other apps (Chrome, Outlook) to Telegram, it does not auto-raise (as expected).

Telegram 1.7.7.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by rterbush** [comment]
This appears to be fixed for me. I'll let someone in charge close it.

**Comment by Aokromes** [comment]
you can close yourself the issues you have opened :)
