### ISSUE TITLE
No status bar icon on Pantheon desktop

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#5721]
### Steps to reproduce
1. Install Telegram on Elementary OS Juno
2. Check that it does not have a telegram indicator in status bar

### Expected behaviour
Tell us what should happen
Telegram status bar notification icon should appear.
I know that it supports all other DE's. Elementary OS Juno Dev's removed support of Ayatana status bar indicator on Pantheon desktop, but can you use their guidelines to create for this desktop environment  status bar icon?

### Actual behaviour
Tell us what happens instead
Status bar icon should be visible on Pantheon Desktop Elementary OS Juno.

### Configuration
**Operating system:**
Elementary OS Juno

**Version of Telegram Desktop:**
1.5.15

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
> but can you use their guidelines to create for this desktop environment status bar icon

What do you mean? I found only applets that are shared libraries

**Comment by ilya-fedin** [comment]
Hmm, the author's account is deleted... I can't find any guidelines and looks like tray support is completely removed, so issue can be closed :thinking:
There are some instructions for returning the tray applet: https://elementaryos.stackexchange.com/questions/17452/how-to-display-system-tray-icons-in-elementary-os-juno
