### ISSUE TITLE
"All members are admins" setting missing

### ISSUE THREAD

**Issue by LeonTheOriginal** [telegramdesktop/tdesktop#5722]
With version 1.5.8, group settings have been unified. This ignores and breaks some functions specific for "regular" groups.
One missing feature is the "All members are admins" checkbox in regular groups. Going to the admin management of an existing group with the option enabled, the checkbox is missing in tdesktop 1.5.8 and later and only the group creator (me) is displayed as an admin. The admin count is also "1" als well as only the creator has a an admin badge in the chat and member list.
(Tested with Version 1.5.15 and 1.4.3)

It would be nice if the checkbox can be re-added and especially the display of the admin list and badges can be fixed.

(The group settings unification also removed the option to manually upgrade a group to a supergroup. This breaks for example the workflow to upgrade to a supergroup just after creating it to retain a complete and consistent group chat history. See #5642.)

**Comment by john-preston** [comment]
@LeonTheOriginal When you changed that checkbox in old version the effect was the same like when you change global permissions for adding new members and editing chat information.

**Comment by LeonTheOriginal** [comment]
Ok, at least the functionality is still there.

(I just checked again: Also in older versions, only the group creator has a blue star in the memeber list, when the option "all members are admins" is activated, so the behavior is consistent.)

**Comment by Aokromes** [comment]
this issue is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
