### ISSUE TITLE
Do not close full image view on click on another screen while user have multiple displays setup

### ISSUE THREAD

**Issue by KovalenkoStas** [telegramdesktop/tdesktop#5724]
### Steps to reproduce
1. Setup a few displays for your computer.
2. Open some image in full screen mode.
3. Move focus to another screen.

### Expected behaviour
On screen with telegram app with open image in full screen mode app state shouldn't change.

### Actual behaviour
Image in full screen mode is closed.

### Configuration
**Operating system:**
<img width="226" alt="screen shot 2019-02-23 at 16 40 59" src="https://user-images.githubusercontent.com/15806486/53287786-f1e6e900-3789-11e9-82db-a0fb691307ef.png">
**Version of Telegram Desktop:**
<img width="281" alt="screen shot 2019-02-23 at 16 41 47" src="https://user-images.githubusercontent.com/15806486/53287787-f4e1d980-3789-11e9-84f9-ee3b3e0d24b8.png">
**Multiple display configuration:**
At least two displays

**Comment by 23rd** [comment]
You are using not Telegram Desktop.
You are using [this version](https://macos.telegram.org), that is not related to current repository.

**Comment by KovalenkoStas** [comment]
@23rd wow, got it. Thank you! There are a lot of telegram repos, so it is a little confusing)
