### ISSUE TITLE
Could not input Chinese characters

### ISSUE THREAD

**Issue by czzshr** [telegramdesktop/tdesktop#573]
OS: Ubuntu 14.04
Chinese input method: (Sogou Pinyin)[http://pinyin.sogou.com/linux/?r=pinyin]
Description: Could not input Chinese characters, so when I want to input, I have to input characters in other application and copy them into telegram.

**Comment by nyagi** [comment]
OS: ArchLinux
Also, Chinese input sources on iBus are not supported.

**Comment by saintwinkle** [comment]
OS: ArchLinux
Also, Chinese input sources on **Fcitx** are not supported.

**Comment by ustcltx** [comment]
https://github.com/telegramdesktop/tdesktop/issues/375

**Comment by taijuin** [comment]
the answer is in : #375

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.
