### ISSUE TITLE
No emojis for chess icons

### ISSUE THREAD

**Issue by qg0** [telegramdesktop/tdesktop#5733]
No emojis for chess icons:

![image](https://user-images.githubusercontent.com/919099/53398437-2ce05b00-39dc-11e9-90ea-b09e73c95820.png)

**Comment by Aokromes** [comment]
delete template is evil, can you try on latest version and state witch os you use?

**Comment by qg0** [comment]
Telegram desktop version 1.8.15
Operating system: OpenSUSE Tumbleweed 5.3.1-1-default #1 SMP Sat Sep 21 13:39:23 UTC 2019 (27a0123) x86_64 x86_64 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/919099/66517369-3d79b780-eb0d-11e9-8833-213bb46c0b3f.png)

**Comment by ilya-fedin** [comment]
These chess symbols aren't emoji, i.e. not a bug

**Comment by ilya-fedin** [comment]
You also can use Ctrl+F here: https://unicode.org/emoji/charts/emoji-list.html
And see that there are only one chess emoji.
