### ISSUE TITLE
enable proxy for calls button disappears in telegram android when enabling proxy

### ISSUE THREAD

**Issue by danyhm** [telegramdesktop/tdesktop#5734]
Since DrKLO/Telegram issues are closed this is the only place i could find to post this issue.

When there are no proxies in proxy list in telegram android there's a button that says "Use proxy for calls".

after adding a proxy server that option disappears and I can't make a call with proxy.

Does anyone know what the problem is ? or how can I use proxies to make a call ?

**Comment by john-preston** [comment]
@danyhm Maybe it is mtproto proxy? It doesn't support calls.

**Comment by danyhm** [comment]
@john-preston  yes it's mtproto. thanks for clarifying this. I wish i could use socks5 but they filtered the whole protocol of socks5 months ago.

**Comment by danyhm** [comment]
@john-preston 
I take that back. it seems they opened socks some time ago and it works now. just to update you.

**Comment by danyhm** [comment]
@john-preston I'm sorry. It seems it's not completely open. most ISPs block Socks and some don't. the servers residing inside the country have no problems.
