### ISSUE TITLE
[Feature request] Switch between chats by Ctrl+Tab in a smart way

### ISSUE THREAD

**Issue by backtozero** [telegramdesktop/tdesktop#5736]
It would be great to make switching between chats in a smart way as it is made for example in JetBrains product line(IntellijIdea, CLion etc.).
Changing which chat will be selected next by a most recent used(MRU) list or so.

**Comment by up-to-you** [comment]
My granny tried to find the right chat with my nickname using ctrl + tab since she always used chrome. I think my daddy will do the same, despite the fact - he uses firefox.

**Comment by p0358** [comment]
I think the current is better for default, but as an option why not

**Comment by 3v1n0** [comment]
Not sure it's the best... You can already do the same with `ctrl + PageUp/down` while there's no way to switch quickly between users.

But probably a palette-based selection would be the best.

**Comment by backtozero** [comment]
There's also was update that allows to switch by Alt+Up/Down.
So I will close this issue. It should be enough.It is not as good as what I want though.

**Comment by 3v1n0** [comment]
@backtozero mh, I don't think this solves anything...

I mean, Ctrl+Tab should go back to the previously used chat, not to the previous chat in list.
Like also firefox and most apps do.

So I'd reopen this issue until we don't have a final no from the developer :)

**Comment by backtozero** [comment]
Yeah i have hit today again a special case.

You are staying on old chat somewhere down in the chat list.
Somebody writes you something important.
You are switching to a new message and there is now way you can get to the old chat without scrolling again or searching.

So i agree, Alt+Down and others is not a solution. Reopening
