### ISSUE TITLE
Can't play HEVC 4K video inside Telegram desktop

### ISSUE THREAD

**Issue by janlukes** [telegramdesktop/tdesktop#5737]
### Steps to reproduce
1. Receive HEVC 4K video
2. 
3. 

### Expected behaviour
Playback without having to open video in external player.

### Actual behaviour
Only video thumbnail is shown but clicking on playback button does nothing

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.5.15

**Comment by john-preston** [comment]
@janlukes Maybe my ffmpeg build doesn't support it. Anyway, 4K will play awfully in tdesktop, it uses cpu decoding and rendering.

**Comment by Mithgol** [comment]
This issue seems somewhat fixed, HEVC 4K video does play in the internal player in Telegram Desktop v1.8.13 on Windows 7 Professional, 64 bit, with Service Pack 1.

(Though it does indeed play awfully.)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6312#issuecomment-525739747

**Comment by turcandan** [comment]
> This issue seems somewhat fixed

No, it's not. It still lags af
