### ISSUE TITLE
Cannot compile using the cmake guide

### ISSUE THREAD

**Issue by UniqueUname** [telegramdesktop/tdesktop#5738]
### Steps to reproduce
1. [Follow this guide](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md)

### Expected behaviour
Everything should magically compile and I should be able to compile and do stuff

### Actual behaviour
openssl refuses to work with current qt version the project uses

### Configuration
Ubuntu 18.04.2 LTS (Bionic Beaver)

**Version of Telegram Desktop:**
Lastest

**Used theme**:
I cannot even use it

Please update the guide or patches related to this.
<details><summary><b>Logs</b>:</summary>
<pre>g++ -c -include .pch/Qt5Network -pipe -O2 -g -fPIC -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -D_REENTRANT -fno-exceptions -Wall -W -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_TSLIB -DQT_NO_LIBINPUT -DQT_NO_USING_NAMESPACE -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_CORE_LIB -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I. -I../3rdparty/zlib -Ikernel -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.6.2 -I../../include/QtNetwork/5.6.2/QtNetwork -I../../include/QtCore/5.6.2 -I../../include/QtCore/5.6.2/QtCore -I../../include/QtCore -I.moc -I../../mkspecs/linux-g++ -o .obj/qsslcertificate_openssl.o ssl/qsslcertificate_openssl.cpp
<b>ssl/qsslcertificate_openssl.cpp:</b> In function ‘<b>uint qHash(const QSslCertificate&amp;, uint)</b>’:
<b>ssl/qsslcertificate_openssl.cpp:63:30:</b> <font color="#EF2929"><b>error: </b></font>invalid use of incomplete type ‘<b>X509 {aka struct x509_st}</b>’
         return qHashBits(x509<font color="#EF2929"><b>-&gt;</b></font>sha1_hash, SHA_DIGEST_LENGTH, seed);
                              <font color="#EF2929"><b>^~</b></font>
In file included from <b>/usr/include/openssl/crypto.h:31:0</b>,
                 from <b>/usr/include/openssl/comp.h:16</b>,
                 from <b>/usr/include/openssl/ssl.h:47</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/../../../../../src/network/ssl/qsslcontext_openssl_p.h:53</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/qsslcontext_openssl_p.h:1</b>,
                 from <b>ssl/qsslsocket_p.h:55</b>,
                 from <b>ssl/qsslsocket_openssl_p.h:63</b>,
                 from <b>ssl/qsslsocket_openssl_symbols_p.h:64</b>,
                 from <b>ssl/qsslcertificate_openssl.cpp:35</b>:
<b>/usr/include/openssl/ossl_typ.h:119:16:</b> <font color="#34E2E2"><b>note: </b></font>forward declaration of ‘<b>X509 {aka struct x509_st}</b>’
 typedef struct <font color="#34E2E2"><b>x509_st</b></font> X509;
                <font color="#34E2E2"><b>^~~~~~~</b></font>
<b>ssl/qsslcertificate_openssl.cpp:</b> In member function ‘<b>QByteArray QSslCertificate::version() const</b>’:
<b>ssl/qsslcertificate_openssl.cpp:87:68:</b> <font color="#EF2929"><b>error: </b></font>invalid use of incomplete type ‘<b>X509 {aka struct x509_st}</b>’
             QByteArray::number(qlonglong(q_ASN1_INTEGER_get(d-&gt;x509<font color="#EF2929"><b>-&gt;</b></font>cert_info-&gt;version)) + 1);
                                                                    <font color="#EF2929"><b>^~</b></font>
In file included from <b>/usr/include/openssl/crypto.h:31:0</b>,
                 from <b>/usr/include/openssl/comp.h:16</b>,
                 from <b>/usr/include/openssl/ssl.h:47</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/../../../../../src/network/ssl/qsslcontext_openssl_p.h:53</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/qsslcontext_openssl_p.h:1</b>,
                 from <b>ssl/qsslsocket_p.h:55</b>,
                 from <b>ssl/qsslsocket_openssl_p.h:63</b>,
                 from <b>ssl/qsslsocket_openssl_symbols_p.h:64</b>,
                 from <b>ssl/qsslcertificate_openssl.cpp:35</b>:
<b>/usr/include/openssl/ossl_typ.h:119:16:</b> <font color="#34E2E2"><b>note: </b></font>forward declaration of ‘<b>X509 {aka struct x509_st}</b>’
 typedef struct <font color="#34E2E2"><b>x509_st</b></font> X509;
                <font color="#34E2E2"><b>^~~~~~~</b></font>
<b>ssl/qsslcertificate_openssl.cpp:</b> In member function ‘<b>QByteArray QSslCertificate::serialNumber() const</b>’:
<b>ssl/qsslcertificate_openssl.cpp:96:45:</b> <font color="#EF2929"><b>error: </b></font>invalid use of incomplete type ‘<b>X509 {aka struct x509_st}</b>’
         ASN1_INTEGER *serialNumber = d-&gt;x509<font color="#EF2929"><b>-&gt;</b></font>cert_info-&gt;serialNumber;
                                             <font color="#EF2929"><b>^~</b></font>
In file included from <b>/usr/include/openssl/crypto.h:31:0</b>,
                 from <b>/usr/include/openssl/comp.h:16</b>,
                 from <b>/usr/include/openssl/ssl.h:47</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/../../../../../src/network/ssl/qsslcontext_openssl_p.h:53</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/qsslcontext_openssl_p.h:1</b>,
                 from <b>ssl/qsslsocket_p.h:55</b>,
                 from <b>ssl/qsslsocket_openssl_p.h:63</b>,
                 from <b>ssl/qsslsocket_openssl_symbols_p.h:64</b>,
                 from <b>ssl/qsslcertificate_openssl.cpp:35</b>:
<b>/usr/include/openssl/ossl_typ.h:119:16:</b> <font color="#34E2E2"><b>note: </b></font>forward declaration of ‘<b>X509 {aka struct x509_st}</b>’
 typedef struct <font color="#34E2E2"><b>x509_st</b></font> X509;
                <font color="#34E2E2"><b>^~~~~~~</b></font>
<b>ssl/qsslcertificate_openssl.cpp:</b> In member function ‘<b>QSslKey QSslCertificate::publicKey() const</b>’:
<b>ssl/qsslcertificate_openssl.cpp:232:32:</b> <font color="#EF2929"><b>error: </b></font>invalid use of incomplete type ‘<b>X509 {aka struct x509_st}</b>’
     X509_PUBKEY *xkey = d-&gt;x509<font color="#EF2929"><b>-&gt;</b></font>cert_info-&gt;key;
                                <font color="#EF2929"><b>^~</b></font>
In file included from <b>/usr/include/openssl/crypto.h:31:0</b>,
                 from <b>/usr/include/openssl/comp.h:16</b>,
                 from <b>/usr/include/openssl/ssl.h:47</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/../../../../../src/network/ssl/qsslcontext_openssl_p.h:53</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/qsslcontext_openssl_p.h:1</b>,
                 from <b>ssl/qsslsocket_p.h:55</b>,
                 from <b>ssl/qsslsocket_openssl_p.h:63</b>,
                 from <b>ssl/qsslsocket_openssl_symbols_p.h:64</b>,
                 from <b>ssl/qsslcertificate_openssl.cpp:35</b>:
<b>/usr/include/openssl/ossl_typ.h:119:16:</b> <font color="#34E2E2"><b>note: </b></font>forward declaration of ‘<b>X509 {aka struct x509_st}</b>’
 typedef struct <font color="#34E2E2"><b>x509_st</b></font> X509;
                <font color="#34E2E2"><b>^~~~~~~</b></font>
<b>ssl/qsslcertificate_openssl.cpp:236:29:</b> <font color="#EF2929"><b>error: </b></font>invalid use of incomplete type ‘<b>EVP_PKEY {aka struct evp_pkey_st}</b>’
     if (q_EVP_PKEY_type(pkey<font color="#EF2929"><b>-&gt;</b></font>type) == EVP_PKEY_RSA) {
                             <font color="#EF2929"><b>^~</b></font>
In file included from <b>/usr/include/openssl/crypto.h:31:0</b>,
                 from <b>/usr/include/openssl/comp.h:16</b>,
                 from <b>/usr/include/openssl/ssl.h:47</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/../../../../../src/network/ssl/qsslcontext_openssl_p.h:53</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/qsslcontext_openssl_p.h:1</b>,
                 from <b>ssl/qsslsocket_p.h:55</b>,
                 from <b>ssl/qsslsocket_openssl_p.h:63</b>,
                 from <b>ssl/qsslsocket_openssl_symbols_p.h:64</b>,
                 from <b>ssl/qsslcertificate_openssl.cpp:35</b>:
<b>/usr/include/openssl/ossl_typ.h:93:16:</b> <font color="#34E2E2"><b>note: </b></font>forward declaration of ‘<b>EVP_PKEY {aka struct evp_pkey_st}</b>’
 typedef struct <font color="#34E2E2"><b>evp_pkey_st</b></font> EVP_PKEY;
                <font color="#34E2E2"><b>^~~~~~~~~~~</b></font>
<b>ssl/qsslcertificate_openssl.cpp:240:36:</b> <font color="#EF2929"><b>error: </b></font>invalid use of incomplete type ‘<b>EVP_PKEY {aka struct evp_pkey_st}</b>’
     } else if (q_EVP_PKEY_type(pkey<font color="#EF2929"><b>-&gt;</b></font>type) == EVP_PKEY_DSA) {
                                    <font color="#EF2929"><b>^~</b></font>
In file included from <b>/usr/include/openssl/crypto.h:31:0</b>,
                 from <b>/usr/include/openssl/comp.h:16</b>,
                 from <b>/usr/include/openssl/ssl.h:47</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/../../../../../src/network/ssl/qsslcontext_openssl_p.h:53</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/qsslcontext_openssl_p.h:1</b>,
                 from <b>ssl/qsslsocket_p.h:55</b>,
                 from <b>ssl/qsslsocket_openssl_p.h:63</b>,
                 from <b>ssl/qsslsocket_openssl_symbols_p.h:64</b>,
                 from <b>ssl/qsslcertificate_openssl.cpp:35</b>:
<b>/usr/include/openssl/ossl_typ.h:93:16:</b> <font color="#34E2E2"><b>note: </b></font>forward declaration of ‘<b>EVP_PKEY {aka struct evp_pkey_st}</b>’
 typedef struct <font color="#34E2E2"><b>evp_pkey_st</b></font> EVP_PKEY;
                <font color="#34E2E2"><b>^~~~~~~~~~~</b></font>
<b>ssl/qsslcertificate_openssl.cpp:245:36:</b> <font color="#EF2929"><b>error: </b></font>invalid use of incomplete type ‘<b>EVP_PKEY {aka struct evp_pkey_st}</b>’
     } else if (q_EVP_PKEY_type(pkey<font color="#EF2929"><b>-&gt;</b></font>type) == EVP_PKEY_EC) {
                                    <font color="#EF2929"><b>^~</b></font>
In file included from <b>/usr/include/openssl/crypto.h:31:0</b>,
                 from <b>/usr/include/openssl/comp.h:16</b>,
                 from <b>/usr/include/openssl/ssl.h:47</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/../../../../../src/network/ssl/qsslcontext_openssl_p.h:53</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/qsslcontext_openssl_p.h:1</b>,
                 from <b>ssl/qsslsocket_p.h:55</b>,
                 from <b>ssl/qsslsocket_openssl_p.h:63</b>,
                 from <b>ssl/qsslsocket_openssl_symbols_p.h:64</b>,
                 from <b>ssl/qsslcertificate_openssl.cpp:35</b>:
<b>/usr/include/openssl/ossl_typ.h:93:16:</b> <font color="#34E2E2"><b>note: </b></font>forward declaration of ‘<b>EVP_PKEY {aka struct evp_pkey_st}</b>’
 typedef struct <font color="#34E2E2"><b>evp_pkey_st</b></font> EVP_PKEY;
                <font color="#34E2E2"><b>^~~~~~~~~~~</b></font>
<b>ssl/qsslcertificate_openssl.cpp:250:36:</b> <font color="#EF2929"><b>error: </b></font>invalid use of incomplete type ‘<b>EVP_PKEY {aka struct evp_pkey_st}</b>’
     } else if (q_EVP_PKEY_type(pkey<font color="#EF2929"><b>-&gt;</b></font>type) == EVP_PKEY_DH) {
                                    <font color="#EF2929"><b>^~</b></font>
In file included from <b>/usr/include/openssl/crypto.h:31:0</b>,
                 from <b>/usr/include/openssl/comp.h:16</b>,
                 from <b>/usr/include/openssl/ssl.h:47</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/../../../../../src/network/ssl/qsslcontext_openssl_p.h:53</b>,
                 from <b>../../include/QtNetwork/5.6.2/QtNetwork/private/qsslcontext_openssl_p.h:1</b>,
                 from <b>ssl/qsslsocket_p.h:55</b>,
                 from <b>ssl/qsslsocket_openssl_p.h:63</b>,
                 from <b>ssl/qsslsocket_openssl_symbols_p.h:64</b>,
                 from <b>ssl/qsslcertificate_openssl.cpp:35</b>:
<b>/usr/include/openssl/ossl_typ.h:93:16:</b> <font color="#34E2E2"><b>note: </b></font>forward declaration of ‘<b>EVP_PKEY {aka struct evp_pkey_st}</b>’
 typedef struct <font color="#34E2E2"><b>evp_pkey_st</b></font> EVP_PKEY;
                <font color="#34E2E2"><b>^~~~~~~~~~~</b></font>
Makefile:22075: recipe for target &apos;.obj/qsslcertificate_openssl.o&apos; failed
make[3]: *** [.obj/qsslcertificate_openssl.o] Error 1
make[3]: Leaving directory &apos;/home/*username goes here*/TBuild/Libraries/qt5_6_2/qtbase/src/network&apos;
Makefile:241: recipe for target &apos;sub-network-make_first&apos; failed
make[2]: *** [sub-network-make_first] Error 2
make[2]: Leaving directory &apos;/home/*username goes here*/TBuild/Libraries/qt5_6_2/qtbase/src&apos;
Makefile:45: recipe for target &apos;sub-src-make_first&apos; failed
make[1]: *** [sub-src-make_first] Error 2
make[1]: Leaving directory &apos;/home/*username goes here*/TBuild/Libraries/qt5_6_2/qtbase&apos;
Makefile:43: recipe for target &apos;module-qtbase-make_first&apos; failed
make: *** [module-qtbase-make_first] Error 2
</pre>
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4926

**Comment by UniqueUname** [comment]
Found a temporary non related fix:
Check the source code box at the software update center and run "sudo apt-get source --compile telegram-desktop"
That does the trick

**Comment by UniqueUname** [comment]
Using Ubuntu 14.5 fixed my issue.
