### ISSUE TITLE
Telegram crashes on OS X El Captain

### ISSUE THREAD

**Issue by Hast** [telegramdesktop/tdesktop#5739]
After updating to the last version of the telegram, it started to crash immediately when opening some specific contacts. Before that, it would always crash only if I played sound or video. Also my top bar mow looks lilke this:

![image](https://user-images.githubusercontent.com/3076280/53520525-88930d00-3ade-11e9-9932-67517b369072.png)

I literally can not use telegram anymore on my mac (Mac Pro 2.1, OS X 10.11.6).

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
