### ISSUE TITLE
0.7.20 can't display quoted message

### ISSUE THREAD

**Issue by roytam1** [telegramdesktop/tdesktop#574]
new telegram clients has "Quote" function but telegram desktop doesn't show the quoted message, and only the reply is shown.

**Comment by zouden** [comment]
+1

The new quote feature is great, but the clients need to be updated to support it. FWIW, users with the old mobile client also can't see the replied-to message until they update their app.

**Comment by tral** [comment]
+1

**Comment by roytam1** [comment]
rev 01ad967640f7f94c58f74b5d573f8e25a70be276 enables displaying and quoting
