### ISSUE TITLE
The appdata doesn't have an OARS rating

### ISSUE THREAD

**Issue by LeandroStanger** [telegramdesktop/tdesktop#5740]
@grulja You can use https://github.com/flathub/flathub/wiki/AppData-Guidelines to help make sure you get everything.

**Comment by grulja** [comment]
This should be reported to upstream.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/f8740c5894b5737762dffe15fa892741fcbe0416
