### ISSUE TITLE
XDG_DATA_HOME ignored when autogenerating .desktop file

### ISSUE THREAD

**Issue by ayekat** [telegramdesktop/tdesktop#5741]
### Steps to reproduce
1. Set `XDG_DATA_HOME` to a non-default path (i.e. *not* `~/.local/share`)
2. Launch Telegram Desktop in that environment

### Expected behaviour
Telegram should generate the `telegramdesktop.desktop` file in
`$XDG_DATA_HOME/applications`, as Telegram now supposedly [respects the XDG
basedir spec][107].

(actually, Telegram shouldn't generate the desktop file at all, but that's
[yet another issue][306])

### Actual behaviour
Telegram generates `~/.local/share/applications/telegramdesktop.desktop`, no
matter what `XDG_DATA_HOME` is set to. This is incorrect, since `~/.local/share`
should only be used as a fallback path if `XDG_DATA_HOME` is unset.

### Configuration
**Operating system:**
Arch Linux

**Version of Telegram Desktop:**
1.5.15

**Used theme**:
Default (Night Mode)

---

**EDIT**: Fixed link for issue #107

[306]: https://github.com/telegramdesktop/tdesktop/issues/306
[107]: https://github.com/telegramdesktop/tdesktop/issues/107

**Comment by ayekat** [comment]
To be a bit more specific, the problematic parts are in [`Telegram/SourceFiles/platform/linux/specific_linux.cpp`][1] and [`Telegram/Resources/fc-custom.conf`][2]

[1]: https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/linux/specific_linux.cpp
[2]: https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/fc-custom.conf#L7

**Comment by Aokromes** [comment]
fixed.
