### ISSUE TITLE
Sent video keeps repeating. No way to stop it.

### ISSUE THREAD

**Issue by m-thomson** [telegramdesktop/tdesktop#5742]
### Steps to reproduce
1. Send an MP4 video file on Mac desktop client
2. 
3. 

### Expected behaviour
It shouldn't play in the sender's client automatically. I'm the one who sent the video.... I know what it contains!

At the very least I should be able to pause or stop it. Nope.

### Actual behaviour
It plays over and over on my client. Wasting battery cycles. If I click the video to view it in the overlay I can pause it there. But upon closing the overlay the video resumes in an *ENDLESS* loop.

### Configuration
**Operating system:**
Latest as of this writing.
**Version of Telegram Desktop:**
Latest as of this writing.
**Used theme**:
None.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by m-thomson** [comment]
Okay, I see now that there is an option to disable auto-play videos. Great.

But that brings up another problem. If I'm in a chat and go to menu > preferences, I'm shown the "General Settings" page with zero indication that any other settings pages exist.

<img width="466" alt="screenshot 2019-02-28 at 4 20 10 pm" src="https://user-images.githubusercontent.com/5273016/53607699-bb87e000-3b74-11e9-8426-2a45f3112245.png">

Shouldn't the user be taken to the top level settings page??

**Comment by john-preston** [comment]
@m-thomson I think you're talking not about tdesktop, but about another telegram app for macOS.

**Comment by m-thomson** [comment]
Hmmm, I thought I was using the official Telegram desktop app for MacOS:

<img width="683" alt="screenshot 2019-02-28 at 9 01 45 pm" src="https://user-images.githubusercontent.com/5273016/53617484-34e6f900-3b9c-11e9-9f43-4d1aa5607b90.png">


But I see now, there appears to be two official MacOS clients(?) You're right though I'm **not** using. Telegram Desktop. Darn, please accept my apologies!

<img width="923" alt="screenshot 2019-02-28 at 9 03 09 pm" src="https://user-images.githubusercontent.com/5273016/53617509-50520400-3b9c-11e9-84be-393053cc8890.png">

Is it true there are two official MacOS clients? I'm quite confused.

**Comment by m-thomson** [comment]
Nevermind, I see what's going on. In my short time with it, Telegram Desktop seems like a much better app. Kudos.

**Comment by john-preston** [comment]
@m-thomson I'm sorry, but looped video playback, like in the native macOS app you were using, is going to appear in Telegram Desktop as well (it is already there on all other platforms). I'm just implementing it too slowly :(
