### ISSUE TITLE
Accidental Phone Calls

### ISSUE THREAD

**Issue by BlackRedDead** [telegramdesktop/tdesktop#5745]
i was watching a horrormovie as a friend accidently calls me trough telegram, twice - he replied he'd be sorry and didn't wanted to disturb me and that he first started a call by accident and then the second as he wanted to cancel the first!

### Steps to reproduce
1. idk (on his side)
2. tipping or clicking on a received accidental phone call starts another accidental phone call without confirmation!

### Expected behaviour vs Actual behaviour
how nice some users might find this feature, if i have no control over it it's just anoying!
if i would implement such feature, i would make sure that it won't start a call just by tipping/clicking someones name or messages! - it's pretty weired that if i click on a "cancel call" button of a received "missed" (actually i declined it!) call it just starts another accidental call!

### Wishes
1. option to deactivate calls "feature" entirely (and stop receiving calls!)
2. confirmation to recall a missed call (you always could accidently tap somewhere, shouldn't start to disturb someone!)
3. maybe move that call button somewhere else, so you can't accidently git it while you want to tap something else - i think it is totaly misplaced in a chatwindow!
(despite the fact that "why the heck a messenger on a smartphone needs a calloption anyway?!" - and without a distinguishing video feature it's pretty much useless - i can just record voice messages, that is indeed a nice feature to have for a messenger!)

***slightly offtopic***
also an argument, if i don't want to use a feature, i won't use it anyway! - so please be kind and think twice about HOW you implement things - fast&dirty isn't helping anything/one and just damaging the creditability of this great application (as it is already hard enough to convince ppl stopping to use 24/7 spyware like WA! - tough the suspicious backing story of telegram with theire "anonymous russian privateers" isn't really that trust improving, i really hope it's not just hidden spy, as greedy companys are always bad, regardless wich nation! - i would like to spend money on telegram, as a donation option! - and i would think it's okay to ask for such once a year! ;-)

### Configuration
**Operating system:**
Windoof 10
**Version of Telegram Desktop:**
1.5.11 (i know, old - i suffer capped internet xP)
My friend used the latest android version!
**Used theme**:
doesn't matter

**Comment by Aokromes** [comment]
#3583
