### ISSUE TITLE
Ability to save proxies without enabling them

### ISSUE THREAD

**Issue by MetaiR** [telegramdesktop/tdesktop#5746]
this is kind of a suggestion and request for a feature,
In telegram X we have this ability to save proxies without enabling them first, this is coming very handy since we don't know when our proxy will be banned by ISPs and want to add some backup proxies

this is a screenshot from telegram X
![photo_2019-03-03_10-49-51](https://user-images.githubusercontent.com/7807264/53692280-194d3f80-3da2-11e9-9399-72f9643b5ee1.jpg)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4672
