### ISSUE TITLE
#bug - Thumbnail image not load

### ISSUE THREAD

**Issue by saturn99** [telegramdesktop/tdesktop#5747]
### Configuration
**Operating system:**

Windows 7 HOME Premium server pack 1

**Version of Telegram Desktop:**
1.5.15

![untitled](https://user-images.githubusercontent.com/5188799/53694428-ff245900-3dc3-11e9-988b-0d8e5d1a4de8.png)
Thumbnail image not load and show !!

**Comment by saturn99** [comment]
UP

**Comment by Aokromes** [comment]
you cannot bump issues on github bugtracker, you only add noise to tracker.
