### ISSUE TITLE
Automatically convert to Emoji broken on Mac (1.39.15576)

### ISSUE THREAD

**Issue by bjaskj** [telegramdesktop/tdesktop#575]
Nothing of these combination gets converted, no matter what I leave the settings for this on true or false:
:-( :-) :-P :-p

**Comment by oieduardorabelo** [comment]
Also, some Emoji, like :+1: :-1: :ok_hand:, they have different shortcuts on Mac, they are:

```
:like: , :dislike:, :up:, :ok:

# and etc
```

They cannot be consistent? Using the same shortcut for Web/Mac App?

**Comment by bjaskj** [comment]
None of these work on the version in the subject of this issue report.
