### ISSUE TITLE
No BuildPath/tdesktop/Telegram/Telegram.xcodeproj file

### ISSUE THREAD

**Issue by MartinDelille** [telegramdesktop/tdesktop#5750]
### Steps to reproduce
1. Follow the documentation here: https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-xcode.md

### Expected behaviour

I should have the following file: `BuildPath/tdesktop/Telegram/Telegram.xcodeproj`

### Actual behaviour

I don't have the file mentioned in the documentation.

### Configuration
**Operating system:** macOS 10.14.3

**Version of Telegram Desktop:** Latest dev branch

**Used theme**: No

**Comment by 2p4g0** [comment]
The same issue. 

Anyone?..

**Comment by 2p4g0** [comment]
Instead of just run 
`gyp/refresh.sh`
you need to run it like this: 
`gyp/refresh.sh --api-id YOUR_API_ID --api-hash YOUR_API_HASH`

**Comment by VitalyChe** [comment]
@MartinDelille How did you resolve the issue?
