### ISSUE TITLE
Create link does not work on non-ascii chars through shortcut (ctrl+k)

### ISSUE THREAD

**Issue by yjyao** [telegramdesktop/tdesktop#5751]
### Steps to reproduce
1. Enter some text that does not end with ascii chars in a chat
2. highlight __any part__ of the text and __press ctrl+k__

When the whole sentence ends with ascii chars, even if the selected part does not end with ascii chars, the shortcut tends to work (I tried many times; sometimes it works, other times it doesn't).

When creating links through the menu (right click -> formatting -> create link), no bugs were observed.

##### Not working
- `你好`
- `こんにちは`
- `Привет`
- `नमस्ते`

##### Working
- `Hello`
- `hey 你好 hey` (This sometimes works, even when only `你好` is selected)

### Expected behaviour
If the text ends with ascii characters, a "Create Link" window pops up.

### Actual behaviour
No reaction.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.5.15

**Used theme**:
Default. Tried under both night mode and daylight mode.

**Comment by 23rd** [comment]
Can't reproduce.

**Comment by yjyao** [comment]
So when you open a chat -> enter `你好` -> highlight `你好` -> press ctrl+k, you see the "Create Link" window popping up as expected? I just tried on 1.6.3 on Windows 10 and nothing pops up.

**Comment by 23rd** [comment]
@yjyao 
![image](https://user-images.githubusercontent.com/4051126/55059095-226abd00-507f-11e9-8182-80f2e66531be.gif)

**Comment by yjyao** [comment]
Weird. I downloaded fresh copies (v1.6.3) from desktop.telegram.org, both portable and install, on two Windows 10 computers, and neither of them worked like your gif showed. Will try on someone else's computer and update later.

**Comment by stek29** [comment]
@yjyao what if you switch layout to English before trying it?

**Comment by yjyao** [comment]
Both my telegram and system language are set to English, unless you mean other layout that I'm not aware?

**Comment by stek29** [comment]
@yjyao Then no idea, sorry. Did it work on other computers?

**Comment by 23rd** [comment]
@yjyao Do you still have a problem with it?

**Comment by yjyao** [comment]
Hey sorry for the delay. I just tried on my friend's laptop (also windows
10) and it was working properly. Only my machines are seeing the same
issue. This might be caused by some of my own configs or conflicts with
other apps I use then.
