### ISSUE TITLE
Group pin not seen by new users coming into the group.

### ISSUE THREAD

**Issue by ddouglas87** [telegramdesktop/tdesktop#5753]
### Steps to reproduce
1. Create a group.
2. Pin a message.
3. Add new people.

### Expected behaviour
New users coming into the group should see the group's pinned message.  They do not.

### Actual behaviour
A new user joins a group and the group shows no previous chat history with no pinned message.

### Configuration
**Operating system:**  All (Linux, Windows, Android, ...)

**Version of Telegram Desktop:**  1.5.8+

**Used theme**:  N/A

### Note
I suspect this might have to do with a group not defaulting to being a super group, if a non super groups behavior is to not show the pinned message.  Because there is now no way to promote a group to a super group to fix it, a hypothetical solution is adding enough people to the channel that the channel promotes itself to supergroup status.  This is not an ideal solution for obvious reasons.

**Comment by john-preston** [comment]
@ddouglas87 It is not visible to new members because the old chat history is not visible. You can change old history visibility when you edit the group (this will implicitly convert it to a supergroup).

**Comment by ddouglas87** [comment]
Thank you.  I see it under Manage group, Group Info.

This doesn't work how it is expected by myself or others around me.

Can this issue be considered for a feature request?  That is, new groups default to visible instead of hidden.

**Comment by john-preston** [comment]
@ddouglas87 This will cause problems, because only supergroups can be visible instead of hidden, and each user has a hard limit on amount of supergroups and channels he can be a member of.
