### ISSUE TITLE
Restore Messages and Media

### ISSUE THREAD

**Issue by Kurdaitcha** [telegramdesktop/tdesktop#5754]
I accidentally deleted conversation using Telegram Desktop when I went back and tried to add the person back it gave me a blank chat window when I tried to talk to them again I was expecting it to show all of the media and messages again but it didn't, is there a way to restore all of the chat history?

**Comment by p0358** [comment]
I think unfortunately no. You can ask the other person to export their archive and send it to you, so you could view it externally
