### ISSUE TITLE
Enabling/disabling notifications while passcode locked

### ISSUE THREAD

**Issue by p0358** [telegramdesktop/tdesktop#5755]
### Steps to reproduce
1. Enable passcode lock in Telegram Desktop
2. Lock the app with passcode
3. Try turning notifications on/off by right-clicking taskbar icon and selecting the option

### Expected behaviour
Tell us what should happen
1. Enable/disable notifications while app is passcode locked
2. Notifications get enabled/disabled, both should be possible, in case you enable notifications, you would simply see them with all contents hidden until unlocking
(the only reason I see it's not working for now is it might save those settings encrypted with encryption key related to passcode; however one should be able to at least disable notifications without unlocking to stop possible interruption)

_OR_

1. Enable/disable notifications while app is passcode locked
2. Confirm "You need to unlock me first" message with OK button
3. Notifications get enabled/disabled

### Actual behaviour
Tell us what happens instead
1. Enable/disable notifications while app is passcode locked
2. Confirm "You need to unlock me first" message with OK button
3. App gets unlocked, but notifications are still at the previous setting
4. Need to repeat step 1 and right-click taskbar icon again after unlocking

### Configuration
**Operating system:** Windows 10 1809

**Version of Telegram Desktop:** 1.5.15

**Used theme**: shouldn't matter

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by p0358** [comment]
@Aokromes yes, just checked

**Comment by p0358** [comment]
Still valid, still a little annoyance where I can't quickly disable those at any time without bringing the Telegram window up (say in a lesson, or worse, in a presentation, where everyone would be forced to see my conversations view)

**Comment by p0358** [comment]
From what I remember nothing has changed regarding to this...

**Comment by p0358** [comment]
Still valid. Not only that, but the whole option to "Disable notifications" is now gone from the menu when the app is locked!!! Certainly not a proper solution...

**Comment by ilya-fedin** [comment]
If it's gone, this couldn't be a valid bug anymore. If you need this option, you can create a new feature request.

**Comment by p0358** [comment]
I guess technically. But the origin of the issue is that toggling notifications while app is locked didn't work. What happened meanwhile was that someone hid the option during locked state instead of figuring out a way to fix it. But I guess opening a new issue might be better at this point, true
