### ISSUE TITLE
CTRL+F doesn't work in shared documents/audios/links

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#5756]
### Steps to reproduce
1. open the shared documents/audios/links screen of a chat
2. use CTRL+F to search for something

### Expected behaviour
The focus is brought to the search input box and you can write in it

### Actual behaviour
Nothing happens when you use CTRL+F

### Configuration
**Operating system:** Linux Mint, Windows 10

**Version of Telegram Desktop:** 1.5.15

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by 23rd** [comment]
Yeah, I wanted to do pull request for it a couple days ago, but found crash instead. =)
