### ISSUE TITLE
Build for VS 2017

### ISSUE THREAD

**Issue by XEGARE** [telegramdesktop/tdesktop#5758]
Hello. The build instructions for Visual Studio 2017 are correct? I don’t see the Telegram.sln project file. Maybe I’m doing something wrong. Execution of commands is performed without errors.

**Comment by 23rd** [comment]
Build instruction is correct. 
After all steps, you will see the project file along `TBuild\tdesktop\Telegram\Telegram.sln` path.

**Comment by XEGARE** [comment]
Telegram.sln is not created along this path, it is not found anywhere. Apparently some team is not working. Unfortunately there is no time to check.
