### ISSUE TITLE
Snap not available for arm64

### ISSUE THREAD

**Issue by MariusQuabeck** [telegramdesktop/tdesktop#5759]
I just tried to install Telegram on my new Pinebook which happens to be arm64.

```
marius@NerdZoom-Pinebook:~$ snap install telegram-desktop
error: snap "telegram-desktop" is not available on stable for this architecture (arm64) but exists on other architectures (amd64, armhf, i386).
```

Can you please add arm64 for the telegram-desktop snap?

**Comment by john-preston** [comment]
Now https://snapcraft.io/telegram-desktop has armhf and arm64 builds. Please check if they're OK.
