### ISSUE TITLE
#bug when /tmp as tmpfs, Telegram not work and always use %100 of RAM

### ISSUE THREAD

**Issue by paledega** [telegramdesktop/tdesktop#5760]
#bug when /tmp as tmpfs, Telegram not work and always use %100 of RAM

**Comment by paledega** [comment]
![photo_2019-03-05_19-32-36](https://user-images.githubusercontent.com/38860643/53820811-7264d100-3f64-11e9-8f75-aed305fdcd39.jpg)

**Comment by paledega** [comment]
my df output:

udev             4054080        0  4054080    0% /dev
tmpfs             814888     9360   805528    2% /run
/dev/sda2      155426152 61307724 86153552   42% /
tmpfs            4074436     8112  4066324    1% /dev/shm
tmpfs               5120        4     5116    1% /run/lock
tmpfs            4074436        0  4074436    0% /sys/fs/cgroup
tmpfs            4074436       12  4074424    1% /tmp
tmpfs            4074436    44816  4029620    2% /home/a/.cache
tmpfs             814884       32   814852    1% /run/user/1000

**Comment by xvitaly** [comment]
I cannot confirm that:

```
mount | grep /tmp
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,seclabel)
```
