### ISSUE TITLE
Regression: can no longer play selected voice/audio messages

### ISSUE THREAD

**Issue by S-U-M-1** [telegramdesktop/tdesktop#5762]
### Steps to reproduce
1. Open Telegram Desktop 1.5.4 or similar.
2. Select 2 or more voice messages.
3. Click the play button on a selected voice message.

### Expected behaviour
The voice message should play (as in version 1.1.23, the version I continue to use today due to various other issues).

### Actual behaviour
The message is deselected instead.

### Configuration
**Operating system:**
Windows 7 64-bit
**Version of Telegram Desktop:**
1.5.4
**Used theme**:
None
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by S-U-M-1** [comment]
Anyone?

**Comment by Aokromes** [comment]
#5481
