### ISSUE TITLE
Icons in call interface are out of frame and pic and video viewer are not centered

### ISSUE THREAD

**Issue by vmorenomarin** [telegramdesktop/tdesktop#5763]
### Steps to reproduce
1. Do a call.
2. Open a video or pic.

### Expected behaviour
1. Icons in call interface in the frame.
2. No crop and centered viewer.

### Actual behaviour
Tell us what happens instead
1. Icons in call interface are out of frame.
![image](https://user-images.githubusercontent.com/13444664/53848828-d77bef00-3f83-11e9-9a08-afef4318f01e.png)

2. Telegram native viewer are not centered and/or are crop in video or pics

![image](https://user-images.githubusercontent.com/13444664/53848875-fed2bc00-3f83-11e9-95e6-cf2075fa4e4a.png)

### Configuration
**Operating system:**
Sistema operativo: KDE neon Developer Edition
Versión de KDE Plasma: 5.15.2
Versión de KDE Frameworks: 5.56.0
Versión de Qt: 5.12.0
Versión del kernel: 4.15.0-46-generic
Tipo de OS: 64 bits

**Version of Telegram Desktop:**
1.5.15 (Beta)

**Used theme**:
breeze.tdesktop-theme

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by vmorenomarin** [comment]
Yes, the problem persists in my SO.

**Comment by ilya-fedin** [comment]
Is this still valid?

**Comment by vmorenomarin** [comment]
SOLVED!

*Víctor Moreno Marín*
*Físico Universidad de Antioquia*
