### ISSUE TITLE
Can't compile libvdpau (CMAKE - Linux)

### ISSUE THREAD

**Issue by UniqueUname** [telegramdesktop/tdesktop#5764]
### Steps to reproduce
1. Follow CMAKE instructions

### Expected behaviour
There should be an autogen.sh file which prepares stuff for make command (located at)
```
git clone git://anongit.freedesktop.org/vdpau/libvdpau
cd libvdpau
./autogen.sh --enable-static
make $MAKE_THREADS_CNT
sudo make install
cd ..
```

### Actual behaviour
There is no autogen.sh file.

```
bash: ./autogen.sh: No such file or directory
```

### Configuration
**Operating system: Ubuntu 14.05 or something**

**Version of Telegram Desktop: lastest from source**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
</details>

**Comment by Johnnynator** [comment]
See #5761

**Comment by UniqueUname** [comment]
Thanks.
