### ISSUE TITLE
Mac OS X menu titles 

### ISSUE THREAD

**Issue by cantoute** [telegramdesktop/tdesktop#5767]
Seems menu titles got lost
instead getting a _NS:99.title 

![pastedgraphic-1](https://user-images.githubusercontent.com/4077221/53906861-b6baa480-402a-11e9-8631-7eb24d22d533.png)

Mac OS X 10.11.6 
Language french

Thanks for your work guys :)

**Comment by cantoute** [comment]
Sorry faulty click...

**Comment by Aokromes** [comment]
you are using (outdated) telegram macos not telegram desktop.

**Comment by stek29** [comment]
This is not TDesktop but a different app -- from https://macos.telegram.org.
You can get TDesktop at https://desktop.telegram.org.
(There are two apps in Mac App Store as well).

You can report issues in the app you're using at https://t.me/macswift, or at https://github.com/overtake/TelegramSwift.
