### ISSUE TITLE
Users appear in restriction exceptions list for no apparent reason

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#5768]
### Steps to reproduce
1. Set group permissions to allow pin messages and disallow change group info for all members
![image](https://user-images.githubusercontent.com/1321838/53945375-2af85500-40ca-11e9-8188-affeed685c3e.png)
2. Go to restriction dialog for any non admin member
![image](https://user-images.githubusercontent.com/1321838/53945699-d1445a80-40ca-11e9-82df-b56c59c493cc.png)
3. By default restriction are same as in step 1
![image](https://user-images.githubusercontent.com/1321838/53945591-a22de900-40ca-11e9-889b-ddd9328289e2.png)
4. Click Save without changing any permission and go to Manage Group - Permissions - Exceptions
![image](https://user-images.githubusercontent.com/1321838/53945917-5c255500-40cb-11e9-9e3a-a7d98b81a7fd.png)
5. Click Delete and go to Recent actions
![image](https://user-images.githubusercontent.com/1321838/53946091-af97a300-40cb-11e9-9b66-0a66b7868592.png)

### Expected behaviour
After step 4 user shouldn't be included in Exceptions list: actually user didn't receive any special restriction.
After step 5 logs shouldn't contain information about changing restriction. Actually he didn't receive permission to change group info.

### Actual behaviour
After step 4 user included in Exception list.
After step 5 logs contain wrong information about restrictions.

### Configuration
**Operating system:** Windows 7, Arch Linux

**Version of Telegram Desktop:** 1.5.15

**Used theme**: Any

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by aNNiMON** [comment]
Still valid in 1.9.8

**Comment by aNNiMON** [comment]
Still valid in 2.4.4

**Comment by aNNiMON** [comment]
Issue still exists

**Comment by aNNiMON** [comment]
3.2.5,  still an issue

**Comment by aNNiMON** [comment]
Reproducible on 3.7.5

**Comment by aNNiMON** [comment]
Reproducible on 4.3.3

**Comment by john-preston** [comment]
@aNNiMON How is this working on mobile apps? Because you may want to save restriction of changing info for a user even if you later enable this permission for everyone in default restrictions.

**Comment by aNNiMON** [comment]
@john-preston, on Telegram Android the situation is the same.  However, on Telegram X the toast appears after clicking Save button:
![image](https://user-images.githubusercontent.com/1321838/209408138-8c58f2f8-5a65-4f99-982a-1b67fcd5d3dd.png)

Telegram X does a bit more work and prevents saving permissions if there are no restrictions compared to chat permissions.
But, looks like the root issue is on a server-side.
