### ISSUE TITLE
if you resize telegram window , it goes all gray

### ISSUE THREAD

**Issue by FernandoMiguel** [telegramdesktop/tdesktop#5773]
### Steps to reproduce
1. open telegram desktop on mac
2. resize or make full desktop

### Expected behaviour
for the window to open and content to load

### Actual behaviour
all window goes gray and you can't click anywhere

### Configuration
**Operating system:**
On MacOS 10.14.4 Beta (18E205e)

**Version of Telegram Desktop:**
1.5.15 from apple store

**Used theme**:
Dark Theme

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Comment by FernandoMiguel** [comment]
Sorry, never got the previous notification.
I haven't tested, but haven't seen this in a while.
If it happens again, I'll open a new ticket
