### ISSUE TITLE
Stop requiring phone registration

### ISSUE THREAD

**Issue by libBletchley** [telegramdesktop/tdesktop#5774]
### Steps to reproduce
1. install the Telegram desktop app
1. launch it
1. see prompt demanding phone number entry
1. exit
1. uninstall the Telegram desktop app
1. (edit) install Jami or Wire, enjoy spam-free service without patronizing mobile phone carriers and feeding privacy-abusing technology.

### Expected behaviour
Users of the *desktop* app should not be asked for a phone number.

### Actual behaviour
Users are forced to supply a phone number to register for an account.  This not only abuses privacy in a number of ways, it also forces users into the marketplace to buy the very service they expect a VOIP mechanism like Telegram Messenger to help them avoid.

In Europe, many are forced to register their mobile phones to a legal identity, thus a burner phone is not even an option.

In the US, all four mobile carriers are privacy abusers.  They cannot be trusted, and privacy-respecting consumers boycott them.  To be clear, all four supported CISPA and additionally they have these issues as well:

|carrier|issues|
|--|--|
|AT&T|ALEC member; paid $100k to cloakroom project; paid $200k to [fight privacy in CA](https://arstechnica.com/tech-policy/2018/04/facebook-donated-200000-to-kill-a-privacy-law-but-now-its-backtracking/); NSA project [Fairview](https://www.nytimes.com/2015/08/16/us/politics/att-helped-nsa-spy-on-an-array-of-internet-traffic.htm); paid Cohen's company a total of $200k; has Koch ties; sponsors Fox News; took $20.3 billion in Trump tax cuts; 4th highest in payments to Facebook for ads one year; [sells](https://motherboard.vice.com/amp/en_us/article/nepxbz/i-gave-a-bounty-hunter-300-dollars-located-phone-microbilt-zumigo-tmobile?) access to their customers’ location data|
|Verizon|paid $200k to [fight privacy in CA](https://arstechnica.com/tech-policy/2018/04/facebook-donated-200000-to-kill-a-privacy-law-but-now-its-backtracking/); NSA project [Stormbrew](https://www.nytimes.com/interactive/2015/08/15/us/documents.html); took $16.8 billion in Trump tax cuts; $1.35 million [fine for violating](https://www.cnet.com/news/verizon-racks-up-1-35-m-bill-for-violating-consumer-privacy/) customers’ privacy; $7.4 million [fine for violating](https://www.huffingtonpost.com/2014/09/03/verizon-privacy_n_5760132.html) customers’ privacy; paid $30 million for Facebook ads one year|
|Sprint|sponsors Fox News; [sells](https://motherboard.vice.com/amp/en_us/article/nepxbz/i-gave-a-bounty-hunter-300-dollars-located-phone-microbilt-zumigo-tmobile?) access to their customers’ location data|
|T-Mobile|paid $100k to Corey Lewandowski; [sells](https://motherboard.vice.com/amp/en_us/article/nepxbz/i-gave-a-bounty-hunter-300-dollars-located-phone-microbilt-zumigo-tmobile?) access to their customers’ location data|

You are forcing Americans to financially support one of the above evils.  Please stop.
### Configuration
**Operating system:**
Debian

**Comment by PeterMX** [comment]
I understand this as "make Telegram a spam machine please"

**Comment by UniqueUname** [comment]
Registration with e-mail:Craploads of spam
Registration with phone number: less spam

**Comment by libBletchley** [comment]
> I understand this as "make Telegram a spam machine please"

No you do not have to force users to pay money to AT&T, Verizon, Sprint, or T-Mobile in order to avoid spam.  Both Wire and Jami have figured out how (there is no spam coming in via those networks and yet they don't force people to give money to AT&T, Verizon, Sprint, or T-Mobile).

**Comment by UniqueUname** [comment]
> > I understand this as "make Telegram a spam machine please"
> 
> No you do not have to force users to pay money to AT&T, Verizon, Sprint, or T-Mobile in order to avoid spam. Both **Wire** and **Jami** projects have figured out how (not a single spam msg coming in via either of those networks and yet they don't force people to give money to AT&T, Verizon, Sprint, or T-Mobile). Learn from them.
> 
> BTW, it's a broken countermeasure as well. If I want to spam Telegram users I'll simply buy a 100 pack or 1000 pack of accounts on the darkweb from someone who has done the registration work for me. You're only abusing the privacy of legit users and directing them to pay money to privacy-hostile telecom corps.

That's obviously a problem with the country of "freedom"
Even though you are right, this is not the correct place to ask. **This is the development page of the desktop client of telegram that only deals with the problems that appears on the desktop client**
Plus it will be easier to identify people who were doing shady stuff. So nope, current system is good.
Just because some platforms does it does not mean that telegram has to do it too.

**Comment by libBletchley** [comment]
([PDF](https://github.com/privacytoolsIO/privacytools.io/files/3101514/phone_registration.pdf))
![phone_registration](https://user-images.githubusercontent.com/18015852/56474510-3be30700-647b-11e9-95e4-d5524b0463cf.png)
