### ISSUE TITLE
[Function request] Add the member search from "Channel information" as shown in "Group information", or Add a search shortcut by being in the member list.

### ISSUE THREAD

**Issue by Edicksonjga** [telegramdesktop/tdesktop#5776]
### Steps to reproduce
1. Go to a channel where you are an administrator.
2. Open the channel information panel and go to the "members".
3. The magnifying glass is not shown to enter the member search in one step.

### Expected behaviour
The magnifying glass should be displayed as shown in the information of a group.

### Actual behaviour
That function is not shown in the channels.
![Sin título](https://user-images.githubusercontent.com/37910384/54164469-21a51a80-4433-11e9-8f1f-1948dbfcb805.png)

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.5.15

**Used theme:** Default

**Comment by john-preston** [comment]
@Edicksonjga Is it there on any other platform, like iOS or Android?

**Comment by Edicksonjga** [comment]
From Android you access the search for members with two touches, both in groups and channels, do not use iOS.

I understand the reason for adding functions according to other platforms, but, the same function (the magnifying glass to find members) can be used in groups on this platform.

![Sin título](https://user-images.githubusercontent.com/37910384/54243204-e4f22580-44fd-11e9-8f28-cbb79c5b75af.png)

 Why not in channels ?, questions of uses maybe ?.

**Comment by Edicksonjga** [comment]
Close if you think solved (for me it is): [Shortcut](https://github.com/telegramdesktop/tdesktop/commit/9dc9e019f6d0b351f649ac25697d35e61a25656a) to access the search in the shared media also works to access the search for members in channels and groups. Telegram Beta 1.5.16
