### ISSUE TITLE
.webp which is send as a photo has transparent background

### ISSUE THREAD

**Issue by Dubzer** [telegramdesktop/tdesktop#5777]
### Steps to reproduce
1.  Download [this](https://lithi.io/file/InAj.webp) webp picture
2.  Drag&drop to tdesktop window
3.  Choose **Send as a photo**
### Expected behaviour
Picture shouldn't has transparent background after sending 

### Actual behaviour
Picture has a transparent background like when you sending webp as file, but it's behaviors like a photo.
[video](https://lithi.io/file/Xps1.mp4) 
After restart picture looks as it should be. 

### Configuration
**Windows 10 1809**

**Version of Telegram Desktop:1.5.15**

**Default dark theme with** [custom background](https://t.me/bg/Gbi3zeIXgVIBAAAAbHXUth5xfMc?mode=blur)

**Comment by Lumiukko** [comment]
I think this is part of a bigger overarching problem, which should be discussed as such.

Webp is an image format. Period.
Just treating webp always as a sticker is just a really bad design decision.

Please treat webp in the same way as PNG or JPG pictures and perhaps change the way stickers are identified.

**Comment by soredake** [comment]
@john-preston can you please option to send webp as a plain photo or document?

**Comment by soredake** [comment]
any progress on this?

**Comment by afgks** [comment]
PLEASE add webp support. I've almost stopped using jpg now that almost all the apps I use support webp.
