### ISSUE TITLE
Cannot access external media when installed as a snap on Ubuntu

### ISSUE THREAD

**Issue by rojer** [telegramdesktop/tdesktop#5778]
### Steps to reproduce
1. Install on Ubuntu 18.04 as a snap
2. Try attaching a file from external media (mounted under /media)

### Expected behaviour
Should be able to attach files from /media/...  

### Actual behaviour
Get a permission error when navigating to /media
This is due to AppArmor activity - permission errors can be observed in dmesg output

### Configuration
**Operating system:**

Ubuntu 18.0.4

**Version of Telegram Desktop:**
1.5.15

**Used theme**:
n/a

**Comment by xvitaly** [comment]
This is intended both in Flatpak and Snap due to container isolation.

**Comment by mcnaveen** [comment]
No Possible fix?

**Comment by Aokromes** [comment]
no, that's how flatpak and snap works
