### ISSUE TITLE
Unread counter didn't disappear

### ISSUE THREAD

**Issue by axd** [telegramdesktop/tdesktop#5779]
### Steps to reproduce
1. Open Telegram
2. Wait for a new message/s
3. Read the conversation and back to the message list

### Expected behaviour
Counter for unread messages should disappear

### Actual behaviour
Counter for unread messages remains it just disappear if you send a message.

### Configuration
**Operating system:** Xubuntu 16.04

**Version of Telegram Desktop:** 1.5.16beta

**Used theme**: Default Night mode

**Comment by prppedro** [comment]
![bugmention](https://user-images.githubusercontent.com/9347060/54250396-5e9c0a80-4522-11e9-9033-2382f63a20d9.png)

Mentions also do not disappear. Even after sending messages. Click'em, nothing happens. 

If I restart Telegram and click it, it vanishes. But if someone tags me again, it won't go away.

**Comment by klimentyev** [comment]
Confirm. Gentoo stable too.

**Comment by john-preston** [comment]
Thanks for you report! This will be fixed in the next version.

**Comment by plibither8** [comment]
Hi @john-preston, I don't mean to push, but when can we expect the next version by? Thanks :)

**Comment by john-preston** [comment]
@plibither8 I hope today, but I'm not sure, there are several other serious bugs :( I've un-deployed 1.5.16 beta on Linux for now, you can downgrade to the 1.5.15 stable (you'll have to sign in once again after that).

**Comment by plibither8** [comment]
Alright, thank you!

**Comment by skobkin** [comment]
Works for me on Gentoo from [net-im/telegram-desktop::mva](https://github.com/msva/mva-overlay/tree/master/net-im/telegram-desktop).
