### ISSUE TITLE
Broken URLs in messages

### ISSUE THREAD

**Issue by meglio** [telegramdesktop/tdesktop#578]
![pp202436](https://cloud.githubusercontent.com/assets/282177/6748805/14a28fe8-cf3e-11e4-80f7-f95cfd778742.png)

**Comment by auchri** [comment]
A URL must not contain a literal space.

http://stackoverflow.com/a/5442701

**Comment by meglio** [comment]
I see - you are absolutely right.

The use-case is that the URL is selected on a page and copied to the buffer, and then pasted into Telegram - and it does contain spaces. So that is the page showing the URL incorrectly.
