### ISSUE TITLE
The "Go to the latest message" Down Arrow won't work

### ISSUE THREAD

**Issue by sujunmin** [telegramdesktop/tdesktop#5780]
### Steps to reproduce
1. Open Telegram.
2. Read the group/chat that unread count more then the number which one page can be displayed.
3. Press Down Arrow to the latest message.
4. It can not go to the latest message.

### Expected behaviour
Go to the latest message of the group/chat.

### Actual behaviour
Can not go to the latest message of the group/chat.

### Configuration
**Operating system:** debian stretch

**Version of Telegram Desktop:** 1.5.16 beta

**Used theme**: Default Night mode
![2019-03-13 09 23 37 的畫面快照](https://user-images.githubusercontent.com/6415168/54246962-f117ca80-4571-11e9-90f6-452c1436cedd.png)

**Comment by john-preston** [comment]
Thanks for you report! This will be fixed in the next version.
