### ISSUE TITLE
Video download in media viewer bypassing settings in 1.5.16

### ISSUE THREAD

**Issue by Remu-rin** [telegramdesktop/tdesktop#5782]
### Steps to reproduce
1. Disable autodownload for everything. Or for everything except photos.
2. Go to chat with photos and videos.
3. Open photo, move by arrows to video.

### Expected behaviour
Video should not download unless a user clicks to download.

### Actual behaviour
Video downloads automatically.

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 1.5.16

**Used theme**: Default

**Comment by john-preston** [comment]
@Remu-rin Video doesn't have autodownload option anymore. It is supposed that if you open photo or video it should try to show it to you. If you move from the video to the next object (photo / video), it won't try to show it anymore.

**Comment by Remu-rin** [comment]
@john-preston 
Android client doesn't autodownload video in the case of moving next/previous in fullscreen viewer, even when video autodownload is enabled in settings. It downloads video only when scrolling chat. Or if you click on it from chat (with disabled autodownload).

Also, why photos and videos are together in fullscreen viewer in the first place? Gifs are separate (and always autodownload in fullscreen viewer), files are separate (and do not autodownload when moving in fullscreen viewer with disabled setting). Seems logical that if a user opens photo they should get only photos in next/previous buttons, and when opening video get only videos in next/prev. It didn't matter a lot previously, because you could disable autodownload, but now it's a problem in tdesktop. Not only for traffic, but also possibility of unwanted loud sound when you just want to slide photos. If they would be separate, then there is no problem in current autodownload behavior.

**Comment by john-preston** [comment]
@Remu-rin They should be together in the viewer because of the albums. Albums can mix photos and videos and you should move through the album in the viewer.
