### ISSUE TITLE
can't switch back from beta to stable

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#5783]
### Steps to reproduce
1.install stable tdesktop
2.switch to beta version in update settings
3.check updates and install beta
4.restart tdesktop
5.switch back to stable version in updates settings
6.check updates

### Expected behaviour
downloading stable version

### Actual behaviour
nothing

### Configuration
**Operating system:**
windows 10 pro 1809 x64
**Version of Telegram Desktop:**
1.5.16 beta
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@f242 A new version can't be easily updated (without loosing the authorization etc) to the previous version, autoupdating works only forward :( But you can instead of 6 just install the stable version on top of your beta.
