### ISSUE TITLE
A switch for turning off the new video feature in 1.5.16

### ISSUE THREAD

**Issue by acethical** [telegramdesktop/tdesktop#5785]
I always download the video in TG one by one, the downloaded files' location folder can be opened by right click on them, then I can open my local media player to watch them(local media player supports more control functions when play videos, such as play in a faster speed to save time)
Start with the 1.5.16(beta), I lost the above function
Hope to add a switcher in setting to get reversed(like 1.5.15 and before) for anyone needs the function

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.5.16

**Comment by john-preston** [comment]
@acethical I have a playback speed feature in the tdesktop player as well now! Just need to add the UI elements for that :)

**Comment by acethical** [comment]
The 1.5.18 added a download button for videos
I could watch video as my old pace, and the new stream function works good as well
I think everyone will be satisfied about the update, and this issue could be closed
Thank you for helping

**Comment by john-preston** [comment]
👍
