### ISSUE TITLE
Unread message count per chat does not clear.

### ISSUE THREAD

**Issue by tarcisioe** [telegramdesktop/tdesktop#5786]
### Steps to reproduce
1. Receive a message in any chat, **even the current one**.
2. Visualise the message. 
3. Message counter will not be cleared until you send a message or press Enter.
4. **Mention counter is never being cleared, unless I clear it on Android.**

### Expected behaviour
Unread messages counter should disappear after messages are read.

### Actual behaviour
It remains until Enter is pressed or a message is sent by the user in the same chat.

### Configuration
**Operating system:** Ubuntu 18.04.

**Version of Telegram Desktop:** 1.5.16

**Used theme**: Default white theme and my custom one.

This used to happen sometimes, sporadically during runtime, but was "solved" by closing and reopening the application. Now that doesn't solve it. Not even removing `tdata` helped.

Message count behaviour (enter pressed in the end).
![output](https://user-images.githubusercontent.com/774694/54296403-a60eaf00-4593-11e9-9854-2243313e8a89.gif)

Mention behaviour:
![output](https://user-images.githubusercontent.com/774694/54296287-5e882300-4593-11e9-8a9a-92452bde0bcd.gif)

**Comment by john-preston** [comment]
Should be fixed in 1.5.17 beta.

**Comment by tarcisioe** [comment]
Can confirm it is fixed. Thanks!

**Comment by tarcisioe** [comment]
@john-preston I had the same issue again in 1.5.17, although this time it started to work again after closing and reopening Telegram Desktop.
