### ISSUE TITLE
High CPU usage issue while working

### ISSUE THREAD

**Issue by rezafarokhi** [telegramdesktop/tdesktop#5787]
### Steps to reproduce
1. When you're working with telegram
2. cpu usage goes up
3. cpu usage goes down when you minimize telegram window

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:** 1.5.15

**Version of Telegram Desktop:** Ubuntu 18.10

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by rezafarokhi** [comment]
#

**Comment by Jungo495** [comment]
wow! i think my notebook become TON node i7-8650U

top - 13:45:41 up 10 days,  3:33,  1 user,  load average: 4.67, 3.37, 2.71
Tasks: 354 total,   1 running, 353 sleeping,   0 stopped,   0 zombie
%Cpu(s): 31.4 us,  3.1 sy,  0.0 ni, 64.7 id,  0.7 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem : 24430432 total,   656332 free, 12557868 used, 11216232 buff/cache
KiB Swap:  3997692 total,  3991056 free,     6636 used.  8726780 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                       
 1791 j         20   0 12.630g 5.491g  88468 S  93.8 23.6   1024:16 Telegram       


Telegram reswpawn helps for few days
