### ISSUE TITLE
Telegram blocked in "Connecting..." state after pc sleep mode

### ISSUE THREAD

**Issue by brunoscopelliti** [telegramdesktop/tdesktop#5790]
### Steps to reproduce
1. Launch telegram.
2. Wait the pc enter sleep mode.
3. Unlock the computer.
4. Send a message to a friend.

### Expected behaviour
The message is delivered to my frind.

### Actual behaviour
Telegram remains in a "Connecting ... " state indefinitely.

![screenshot](https://user-images.githubusercontent.com/3489757/54348407-4246bd80-4649-11e9-8ac1-e26beaa3d541.PNG)

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.5.15

**Used theme**: Default.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4556 / https://github.com/telegramdesktop/tdesktop/issues/2258 ?

**Comment by brunoscopelliti** [comment]
#4556, But I'm using windows 10, not XP :)
