### ISSUE TITLE
Notifications not hiding until message readed

### ISSUE THREAD

**Issue by sattellite** [telegramdesktop/tdesktop#5791]
### Steps to reproduce
1. Enable desktop notifications
2. Disable system notifications
3. Get a new message in chat with enabled notifications

### Expected behaviour

The notification will be shown and will hide after few seconds.

### Actual behaviour

The notification is displayed all the time until I read a new message or hide the notification by  button.

### Configuration
Fedora 29 x86_64
Gnome 3.30.2
Telegram Desktop 1.5.17 with classic theme

**Comment by john-preston** [comment]
@sattellite Is it the same way in the previous version, for example in 1.5.15?

**Comment by sattellite** [comment]
@john-preston in previous versions notifications automatically hide after approximately 10 seconds.

**Comment by sattellite** [comment]
Important condition: the telegram desktop window is not focused.
If window is focused and I recieved a new message in not opened chat, then notification is shown and hide after few seconds.

**Comment by john-preston** [comment]
@sattellite Are you sure that the behaviour for inactive window have changed?

**Comment by sattellite** [comment]
@john-preston yes. Previously, there has never been such that notifications were shown for a long time. After upgrading to 1.5.17, the notifications is shown before the window to be focused. Some times I was restart application, but behavior is saved.

**Comment by john-preston** [comment]
@sattellite Yes, I see a bug. Thank you for the report.
