### ISSUE TITLE
GIFs are not played after switching between them in fullscreen preview

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#5796]
### Steps to reproduce
1. Send two or more gifs in chat
2. Open one of them
3. Switch to another gif by scrolling or by pressing arrow keys

### Expected behaviour
All gifs are played normally

### Actual behaviour
Only first opened gif is played. 
![](https://user-images.githubusercontent.com/1321838/54457454-2129be00-476a-11e9-8694-f80988679fcd.gif)

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.5.18 beta

**Used theme**: Any

**Comment by john-preston** [comment]
@aNNiMON Thanks! I'll fix that in the next version.
