### ISSUE TITLE
Music streaming in 1.5.16

### ISSUE THREAD

**Issue by amirashabani** [telegramdesktop/tdesktop#5797]
New in version 1.5.16:
- Play video files and listen to received music without waiting for them to download.

I believe this feature was meant to replicate music streaming that exists in Android, but the way it's implemented is horrible. In Android, I can choose to download the music, or stream it, but on Desktop, I'm forced to stream it, which is bad. Because when the speed of the net is slow, it stops every some seconds to download and robs you the joy of listening to music! 
Please, either fully implement it so I can choose between downloading and streaming, or add an option in the settings so that I can disable streaming all together!

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commits/dev implemented on 1.5.18

**Comment by amirashabani** [comment]
@Aokromes perfect, thanks
