### ISSUE TITLE
No accentuation on Ubuntu 18.10/19.04 with Snap

### ISSUE THREAD

**Issue by matheusreich** [telegramdesktop/tdesktop#5798]
### Steps to reproduce
1. Install Telegram Desktop from the Software Center, using the Snap version.
2. Everything runs fine, get logged in.
3. Try to type a word with accetuation in Portuguese and I get not accentuation.
### Expected behaviour
Tell us what should happen
I should get every single accentuation on every word I type that has some kind of accentuation.
### Actual behaviour
When I type the word não (no in English), I get nao. No other accentuation works. For example, the word cartão de crédito (credit card in English) appears as cartao de credito.
### Configuration
**Operating system:**
Ubuntu 18.10/19.04(just for testing purposes) 64-bit.
**Version of Telegram Desktop:**
Telegram Desktop version 1.5.15 (Snap Store version)
**Used theme**:
Midnight

**Comment by JulianaGuama** [comment]
Hi. I'm having the same problem. I have linux on my laboratory and on my personal computer and on both no accentuation works on Telegram Desktop.

**Operating system (on both):**
Ubuntu 18.04.2 LTS (64-bits)
**Version of Telegram Desktop:**
Telegram Desktop 1.6.0 (From Snap Store source)

**Comment by jessemoreirao** [comment]
Tive o mesmo problema no Fedora e OpenSUSE com Gnome e XFCE.

**Comment by paulomanrique** [comment]
Still same problem, tested on Ubuntu 18.04 from Snap store.

**Comment by jonata** [comment]
Still an issue on Ubuntu 19.04, Telegram Desktop version 1.8.2

**Comment by pablovp86** [comment]
Same problem, but started to occur on version 1.8.8

**Comment by pablovp86** [comment]
Putting this modification )bold), into the laucher file (~/.local/share/applications), solved my problem:

Exec=**env QT_IM_MODULE=xim** /opt/Telegram/Telegram -- %u

**Comment by Aokromes** [comment]
#1041
