### ISSUE TITLE
Last caption from image/video sticks to gifs

### ISSUE THREAD

**Issue by Remu-rin** [telegramdesktop/tdesktop#5799]
### Steps to reproduce
1. Open any image or video with text caption.
2. Open any gif without caption.

### Expected behaviour
No caption.

### Actual behaviour
Client shows previous caption.

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 1.5.18

**Comment by Remu-rin** [comment]
Additionally client now is not showing captions on gifs even if they exist. Old versions showed them.

**Comment by gabbhack** [comment]
Noticed the same behavior, but caption of the last picture shown on the video with caption

https://imgur.com/a/AXUhj0R
