### ISSUE TITLE
No shortcut to send own contact to people

### ISSUE THREAD

**Issue by vemacs** [telegramdesktop/tdesktop#580]
On android, there's a 'share contact' button in the overflow menu, so you can share your contact with somebody you know through a username. On Windows, to share your own contact with somebody, you need to open your own profile page (using the search bar, which is extremely counterintuitive), then hit share contact, and then type the recipient's username in. 

In addition, there should be an easy way to view your own profile.

**Comment by TheReverend403** [comment]
Agreed, there needs to be a way to send your contact to the person/group you're currently talking to without going through multiple menus.

**Comment by MazenMC** [comment]
+1

**Comment by Aokromes** [comment]
#1060 ?

**Comment by stek29** [comment]
@Aokromes not keyboard shortcut
