### ISSUE TITLE
No action on load in new beta (1.5.18) (with auto download off)

### ISSUE THREAD

**Issue by kirsan31** [telegramdesktop/tdesktop#5801]
Removing of `DocumentData::performActionOnLoad()` in new beta led to no action on file downloaded (with auto download off). For example _pdf_ file: In current version I need 1 click on file to download and open it, in new beta I need 1 click to download and 2 click to open...
@john-preston Is it intended?

**Comment by john-preston** [comment]
@kirsan31 Yes, this is intended. Before it was VERY confusing for users when they'll only download the file (and how to do that if they want to) and when to download and open.

**Comment by kirsan31** [comment]
> @kirsan31 Yes, this is intended. Before it was VERY confusing for users when they'll only download the file (and how to do that if they want to) and when to download and open.

Thanks.
