### ISSUE TITLE
Video description issue

### ISSUE THREAD

**Issue by bestpika** [telegramdesktop/tdesktop#5802]
### Steps to reproduce

1. Open an image with the description.
1. Open a video with the description.

### Expected behavior

The description should show the video's description.

### Actual behavior

The description shows the previous image's description.

### Configuration

- **Operating system:** `Windows 8.1 x64 (9600)`
- **Version of Telegram Desktop:** `1.5.18 beta`
- **Used theme**: `Blue`

<details>
<summary><b>Screenshot</b></summary>

![image](https://user-images.githubusercontent.com/5698157/54475499-dde45380-482c-11e9-9625-aa816c8fed42.png)
![image](https://user-images.githubusercontent.com/5698157/54475520-010f0300-482d-11e9-9cf7-188a9ac778f9.png)
![image](https://user-images.githubusercontent.com/5698157/54475530-26037600-482d-11e9-908a-41b1a91fb78c.png)
![image](https://user-images.githubusercontent.com/5698157/54475533-39aedc80-482d-11e9-9068-f3645afe9b58.png)

</details>

**Comment by john-preston** [comment]
@bestpika Thanks for your report!
