### ISSUE TITLE
Caption bug

### ISSUE THREAD

**Issue by P-Alban** [telegramdesktop/tdesktop#5804]
### Steps to reproduce
1.  Create an image with caption
2. Send a video after
3. Click on image
4. Then click on video
5. Image caption now attached to video

### Expected behaviour
No caption on video

### Actual behaviour
Image caption now attached to video

### Configuration
**Operating system:** Win 10

**Version of Telegram Desktop:** 1.5.18 Beta

**Used theme**: Dark
Video: https://i.imgur.com/olAIM27.mp4
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by matinkaro** [comment]
In last version of telegram desktop Beta (1.5.18), after added feature to stream videos immediately, captions are completely incorrect for videos while open them to stream and it shows previous image caption instead.

**Comment by john-preston** [comment]
@P-Alban Thanks for your report.
