### ISSUE TITLE
confusing view

### ISSUE THREAD

**Issue by dimasay** [telegramdesktop/tdesktop#5807]
### Steps to reproduce
1. Open Telegram in full screen
2. Look at the messages structure.

### Expected behaviour
My messages should be on one side,my contact messages should be on other side. 
I was confused when I saw it. I didn't understand exactly this is my message or not in conversation. This is so strange, ugly like a bug.

### Actual behaviour
Messages on one side.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.5.15
**Used theme**:
Matrix

![image](https://user-images.githubusercontent.com/17139645/54494583-97eac680-48e4-11e9-9cd8-00fd60288588.png)

**Comment by Remu-rin** [comment]
Settings, Chat Settings, uncheck `Adaptive layout for wide screens`.

**Comment by dimasay** [comment]
Thanks
