### ISSUE TITLE
Navigating medias important problems

### ISSUE THREAD

**Issue by alisentinel** [telegramdesktop/tdesktop#5808]
There are 2 problems in navigating medias.
1: Videos will be downloaded even if I've turned off the automatic downloading
2: captions will be wrong after navigating

### Steps to reproduce
1. I've just navigated a channel that include both photos and videos

### Expected behaviour
1: Not download videos automatically
2: True media

**Comment by john-preston** [comment]
@alisentinel In the media viewer both photos and videos will always be downloaded if you open them. Why open them otherwise.

Yes, there is a bug with captions. Thanks!

**Comment by alisentinel** [comment]
@john-preston 
> @alisentinel In the media viewer both photos and videos will always be downloaded if you open them. Why open them otherwise.
You're welcome.

But in previous versions navigating in the media viewer didn't cause downloading them (Only for videos when you unchecked automatic downloading videos in settings). It will be annoying when using roaming or expensive networks or low quality connections (like Iran network that have the most users in telegram)

**Comment by john-preston** [comment]
@alisentinel They're not downloading, but they're starting playing using streaming (playing while downloading). They'll stop loading as soon as you close the viewer or move to another photo video.

Only if you've opened a video and continue keeping it open while the video is playing it'll keep loading next parts of the file to play them.
