### ISSUE TITLE
Notifications are not disabled in channels if rejoined

### ISSUE THREAD

**Issue by WiRight** [telegramdesktop/tdesktop#5809]
### Steps to reproduce
1. Join to channel 
2. Disable notifications (in case forever) 
3. Leave channel
4. Join again in this channel (rejoin)
5. A new message will be notified

### Expected behaviour

Don't receive notifications (cause in group settings set "unmute") 

### Actual behaviour

Getting notifications

### Configuration

**Operating system:**
Linux <user> 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.5.15

**Used theme**:
Default

**Comment by john-preston** [comment]
@WiRight I can't reproduce that.

**Comment by WiRight** [comment]
Ok, i'll try reproduce it later.
Maybe record a video

**Comment by WiRight** [comment]
Can't reproduce it again
