### ISSUE TITLE
Ability to add people to group only knowing their usernames, not their phone number missing

### ISSUE THREAD

**Issue by vemacs** [telegramdesktop/tdesktop#581]
This is possible on the web client, however, it is not possible on the desktop client.

On the web client, you can add people using only their username to a group chat.

**Comment by mattrick16** [comment]
:+1: 

Should be added

**Comment by HostFat** [comment]
And it was already requested :( #213

**Comment by auchri** [comment]
Will be added in the next update, it's already in the dev version

**Comment by cobalto** [comment]
And it's closed with 0.8
