### ISSUE TITLE
Incorrect image caption 

### ISSUE THREAD

**Issue by r0mk1n** [telegramdesktop/tdesktop#5811]
### Steps to reproduce
1. Open image with caption
2. Close image
3. Open image without caption

### Expected behaviour
Image with empty caption should appear

### Actual behaviour
Correct image with caption from previous image shown

### Configuration
**Operating system:**
Win 10 Pro
**Version of Telegram Desktop:**
1.5.18 beta
**Used theme**:
Matrix
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@r0mk1n Is this issue still present in the version 1.6?

**Comment by Aokromes** [comment]
near 6 months since the answer request, if this bug is still valid, plz ask to reopen.
