### ISSUE TITLE
Search by name is broken on 1.6.0

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#5812]
### Steps to reproduce
1. Join any supergroup.
2. Press search button.
3. Try to press *Seacrh by user* or *Search by date* button in left search sidebar.

### Expected behaviour
*Search by user* button can be pressed.

### Actual behaviour
*Search by user* button cannot be pressed due to focus loss:
![Screenshot_20190318_201421](https://user-images.githubusercontent.com/966711/54557025-8247d080-49ba-11e9-9ec9-429299af0c76.png)

### Configuration
**Operating system:** Fedora 29

**Version of Telegram Desktop:** 1.6.0

**Used theme**: default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by MasterGroosha** [comment]
Hmm... indeed, you cannot search user's messages at first, but after you hover over other "things" like images, scrollbars etc, icons become "interactive"
TDesktop 1.6.0, Windows 10 LTSB

**Comment by xvitaly** [comment]
@john-preston Bug still exists in 1.6.1.

**Comment by gleb-chipiga** [comment]
Also search by date is broken in 1.6.1.
