### ISSUE TITLE
[Feature Request] Switch keyboard layout hotkey

### ISSUE THREAD

**Issue by iamthevoid** [telegramdesktop/tdesktop#5814]
There was good practice (in qip, for example. Bad example I thought, but... :) ). There was hotkey for fast switch keyboard layout for already written text in input field, no matter is text selected or not. 

I mean all cases like:

> Ghbdtn? z e;t dst[fk

Can be simply swtiched to

> Привет, я уже выехал

with hotkey combination

This can be based on system level keyboard layouts for correct internationalization

There was also another hotkey in qip - for transliterate written text, but imho it more useless than hotkey described above.

**Comment by 23rd** [comment]
You can use my [fork](https://github.com/23rd/tdesktop/releases) that has this feature for Russian layout.
(`Ctrl + ]`)

**Comment by iamthevoid** [comment]
@23rd Sorry, but I will not use ANY fork :)

**Comment by iamthevoid** [comment]
Hey, I don't want to bot to close my issue. I has not lost interest or solved problem on my own. I wait and hope ((
