### ISSUE TITLE
Can't answer one picture when multiples is sent on talk

### ISSUE THREAD

**Issue by JulianaGuama** [telegramdesktop/tdesktop#5816]
### Steps to reproduce
1.  Someone sent multiples images on talk asking which one is better
2.  I tried to select one picture and use it to answer
3.  I can't use one of the pictures on desktop Telegram to answer cause there is no answer option for only one, but the set of all pictures is possible.

### Expected behaviour
It is possible to select only one picture in a set sent all together and use it as answer.

### Actual behaviour
On Telegram Desktop you can use the set as answer, not one picture of the set.

### Configuration
**Operating system:**
Ubuntu 18.04.2 LTS
**Version of Telegram Desktop:**
1.6.0 (from Snap Store source)
**Used theme**:
Night Mode
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
works for me on 1.9.8.
