### ISSUE TITLE
Need a contribution policy?

### ISSUE THREAD

**Issue by Vdragon** [telegramdesktop/tdesktop#582]
Hi @telegramdesktop , <del>it seems that you still make this repo as a [single person project](https://github.com/telegramdesktop/tdesktop/graphs/contributors),</del> would you mind create a <http://Contribute.md> telling us how to help you out?

Ｖ字龍 <Vdragon.Taiwan@gmail.com>

**Comment by Sollex-21412** [comment]
This is main problem of this app IMHO.

**Comment by NeoLegends** [comment]
+1
