### ISSUE TITLE
Fonts become monospaced when pages are opened from Telegram

### ISSUE THREAD

**Issue by jvlianodorneles** [telegramdesktop/tdesktop#5821]
### Steps to reproduce
1. Open Telegram Desktop
2. Click link

### Expected behaviour
The default browser opens the page rendered correctly. (see attached screenshot below)

### Actual behaviour
The default browser opens the page with monospaced fonts.  (see attached screenshot below)

### Configuration
Ubuntu 18.10 and 19.04 running in several different computers.
Browsers tested: Mozilla Firefox 66.0 (64 bits) and Google Chrome 73.0.3683.86 (Official Version) 64 bits.
Telegram Desktop 1.6.1.
Default theme.

###Screenshots
![Link opened in Telegram](https://user-images.githubusercontent.com/348090/54751726-94905d00-4bba-11e9-8980-bcf5e9f0cd49.png)
Link opened in Telegram

![Link opened directly](https://user-images.githubusercontent.com/348090/54751725-94905d00-4bba-11e9-86f4-b1e78d361eb5.png)
Link opened directly

**Comment by drunckoder** [comment]
OS: Ubuntu 19.04 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Telegram Desktop: v 1.6.7 binary distribution from https://desktop.telegram.org/

Issue persists on several other apps launched from Telegram Desktop: Sublime Text, Nautilus File Manager and few more. Google Chrome even crashes if I open a link from Telegram app.

**Comment by stek29** [comment]
it's probably because telegram has it's own font config files and xdg stuff just passes FONTCONFIG related enviroment variables as is.

**Comment by JochemKuijpers** [comment]
Yep, can confirm. This happens on Fedora 29 using KDE Plasma desktop as well.

**Comment by aruseni** [comment]
I am able to reproduce this, too. I use i3 on Ubuntu.

If you already have opened the browser, a new tab is added. But if the browser isn’t opened, it opens with monospace fonts. So as long as it isn’t fixed, you can just open the browser and then click on links.

**Comment by JochemKuijpers** [comment]
Still happens on Fedora 30 with KDE Plasma Desktop. As a bonus, Telegram takes very long to boot the first time.

**Comment by aruseni** [comment]
@JochemKuijpers Exactly, first boot is very long.

**Comment by aruseni** [comment]
It’s OK though, but UX will be a lot better if it would display something on screen.

**Comment by aruseni** [comment]
It’s OK though, but UX would be a lot better if it displayed something on screen.

**Comment by Aokromes** [comment]
fixed already.
