### ISSUE TITLE
"Export Telegram data" feature and GDPR compliant

### ISSUE THREAD

**Issue by amirelec1365** [telegramdesktop/tdesktop#5823]
### Expected behaviour
"Export Telegram data" feature should not show  supergroups and channel names that one have left.

### Actual behaviour
"Export Telegram data" feature is not compliant with GDPR and right to be forgotten. Generated files include supergroups and channels (even messages) that one have left or banned.
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.6.1

**Comment by p0358** [comment]
I thought it should include everything Telegram knows about you. If anything, Telegram maybe could delete your association with left/banned supergroups/channels, but I don't see how removing it from exported data only would do any good here

**Comment by Aokromes** [comment]
imho p0358 is right here.
