### ISSUE TITLE
Transferred scripts lose executable bits on Linux

### ISSUE THREAD

**Issue by YuKitAs** [telegramdesktop/tdesktop#5824]
### Steps to reproduce
1. Add permission to a Bash script with `chmod a+x`
2. Transfer this script via Telegram Desktop Linux 
3. Download the script on Ubuntu 18.04

### Expected behaviour
The permission of the file should not be changed

### Actual behaviour
The executable script doesn't have executable bits any more after downloading

### Configuration
**Operating system:**
Ubuntu 18.04

**Version of Telegram Desktop:**
1.6.1

**Used theme**:
Default

**Comment by john-preston** [comment]
@YuKitAs Maybe this can be considered a security feature. Anyway there is no permissions attribute for files transferred using Telegram API, so this is not supported. You can send them .zip-ed, this will be both secure (no one will execute anything incidentally) and working (archive should preserve your permissions mask).

**Comment by YuKitAs** [comment]
> @YuKitAs Maybe this can be considered a security feature. Anyway there is no permissions attribute for files transferred using Telegram API, so this is not supported. You can send them .zip-ed, this will be both secure (no one will execute anything incidentally) and working (archive should preserve your permissions mask).

Hi, thank you for your quick clarification and suggestion. And I'm ok with it then.
