### ISSUE TITLE
Smooth scrolling in Windows client

### ISSUE THREAD

**Issue by Intenditore** [telegramdesktop/tdesktop#5825]
Windows client, unlike Mac one, has very harsh jumping scroll. I found no way to make smooth, but it really has to be there. 
Funny thing is when the mouse is over the TG windows that's not "active" the smooth scroll works.
Please, add such option

**Comment by Intenditore** [comment]
Any news from devs?(

**Comment by ilya-fedin** [comment]
#6746 is better issue
