### ISSUE TITLE
Cannot add bot on channel create screen

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#5826]
### Steps to reproduce
1. Choose "Create channel"
2. Proceed to adding users to participants
3. Use search to find a bot
4. Choose a bot and press "Invite"

### Expected behaviour
Selected bot(s) should be added as channel admin(s). Maybe without alert dialog

### Actual behaviour
A popup appears for a ~0.5 second with text "Bots can only be added to channel as admins" with two options. However this popup quickly disappears itself and, as a result, bot is **not** added to channel at all.

### Configuration
**Operating system:** Windows 10
**Version of Telegram Desktop:** 1.6.1

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1386 ?

**Comment by MasterGroosha** [comment]
@Aokromes I've just tested it with TDesktop 1.9.4 and it seems to be working as expected now. I think both issues can be closed.
