### ISSUE TITLE
Minimize Sidebar (Contacts)

### ISSUE THREAD

**Issue by iabhigupta** [telegramdesktop/tdesktop#583]
It would be great, If there is an option (button) to minimize the sidebar. After minimizing the side bar we can use full screen as chat window. And If I want to search for the contacts then after clicking on button it should maximize the side bar and I can see and search contacts. I hope, this would be great option for user and users will like this option.

**Comment by cobalto** [comment]
Yes, an accordion effect at the sidebar would be great.
AND turn it resizable too, sometimes it waste a lot of space for contacts with short names.

**Comment by Aokromes** [comment]
+1 to this features.

**Comment by Jonathancollinet** [comment]
+1

**Comment by auchri** [comment]
Duplicate #314
