### ISSUE TITLE
:facepalm: selects gender-specific variant

### ISSUE THREAD

**Issue by taralx** [telegramdesktop/tdesktop#5830]
### Steps to reproduce
1. :facepalm:

### Expected behaviour
🤦 U+1F926

### Actual behaviour
🤦‍♂️ U+1F926 ZWJ U+2642 VS16

### Configuration
**Operating system:** Mac OS

**Version of Telegram Desktop:** 1.61

**Used theme**: Default

**Comment by omkarnathsingh** [comment]
![image](https://user-images.githubusercontent.com/12734027/54863670-7751bf00-4d71-11e9-9c2a-cfa1fd35b9e0.png)


I am getting like this on Windows. Yours appearing different?

**Comment by taralx** [comment]
No, that looks the same. But the underlying glyphs are different from expected and that changes how it shows up in other clients e.g. Telegram Web.

**Comment by taralx** [comment]
If nothing else the first one should be renamed man_facepalming.

**Comment by Aokromes** [comment]
it defaults to 🤦‍♂️ for me on 1.9.8.

**Comment by taralx** [comment]
Thanks for the confirmation. That's still man_facepalming, not the generic version.

**Comment by taralx** [comment]
Still would like to see this fixed.
