### ISSUE TITLE
Support ALT+A in conversations.

### ISSUE THREAD

**Issue by lk-geimfari** [telegramdesktop/tdesktop#5833]
It would be a really useful feature to support hotkey for selecting all messages in the current conversation because it's a little bit annoying to select all messages manually when you need to delete all of them everywhere.

**Comment by gedamial** [comment]
Wouldn't it be easier to just delete the whole conversation?

**Comment by lk-geimfari** [comment]
@gedamial I just updated Telegram and in the last update, there is such feature which allows deleting the whole conversation (not only for me, but for another person who took in conversation), but yesterday there was no such а feature.

**Comment by lk-geimfari** [comment]
Anyway, this request is not actual anymore. Thanks!

**Comment by batmont** [comment]
> it's a little bit annoying to select all messages manually when you need to delete all of them

>  in the last update, there is such feature which allows deleting the whole conversation

if needed to forward too many messages? I think there should be at least selecting some range of messages, with pressing shift key, like there is in file explorers
