### ISSUE TITLE
[Feature Request] Skip file when export

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#5834]
![immagine](https://user-images.githubusercontent.com/6240983/54884364-486e4280-4e70-11e9-9c54-cbee338cec6f.png)

**Comment by ArmeF97** [comment]
I still want this feature request to be open

**Comment by afwn90cj93201nixr2e1re** [comment]
@Aokromes what about intending new label - 'export' to make all of those issues which are related to export more clean?

**Comment by john-preston** [comment]
Fixed by https://github.com/telegramdesktop/tdesktop/commit/03a868a6e3d4d6fd3f2b135b5d79ed35de4b78cd

Will be available in the next version.
