### ISSUE TITLE
Linux: support copy&paste functionality (XF86Copy, XF86Paste, XF86Cut, XF86Undo, XF86Redo, etc...)

### ISSUE THREAD

**Issue by mikkovedru** [telegramdesktop/tdesktop#5835]
I am a keyboard power user and in that I am greatly helped by the [DreymaR's Extend](https://forum.colemak.com/topic/2014-extend-extra-extreme/). The idea is simple: use the separate Extend key (by default mapped to CapsLock key), which opens up a bunch of functionality without the need to move my fingers too much. 
![image](https://user-images.githubusercontent.com/2521942/54885853-92afed80-4e89-11e9-9dbe-ee10f12f28ae.png)
In practice it's even more amazing and useful than one could imagine.

The problem is that the basic functionality of Cut/Copy/Paste/Undo/Redo doesn't work in Telegram. It works in OS, it works in Firefox, it works in LibreOffice and everywhere else, but sadly it doesn't work in Telegram Desktop.

### Steps to reproduce
1. Install [Extend](https://github.com/DreymaR/BigBagKbdTrixXKB).
2. See for yourself that although other buttons work, the Cut/Copy/Paste/Undo functionality doesn't work in Telegram (for example in Firefox/LibreOffice everything works fine).

### Expected behaviour
[XFree86](http://wiki.linuxquestions.org/wiki/XFree86) has a bunch of [XF86 keyboard symbols](http://wiki.linuxquestions.org/wiki/XF86_keyboard_symbols) and the vast majority of them are not relevant to Telegram. But there is a number of them that are highly relevant. At the very least:
- XF86Copy, 
- XF86Paste, 
- XF86Cut, 
- XF86Undo, 
- XF86Redo

It would be very nice to fix Telegram Desktop to support them.

If one has time, one could additionally look at implementing other shortcuts such as:
(- XF86Back?)
(- XF86Clear?)
(- XF86Forward?)
(- XF86Go?)
(- XF86History?)
(- XF86Search?)

### Configuration
**Operating system:**
Linux Mint 19.1 Cinnamon (4.0.9).

**Version of Telegram Desktop:**
1.6.1.

**Used theme**:
Classic.

**Comment by vitlav** [comment]
Are you sure about other Qt5 based applications works with it?

**Comment by mikkovedru** [comment]
@vitlav . I don't know which application works with what. If you could you give me several examples of the Qt5 based applications then I could test them and report the results here.

**Comment by ilya-fedin** [comment]
> If you could you give me several examples of the Qt5 based applications then I could test them and report the results here.

VLC, qBittorrent

**Comment by mikkovedru** [comment]
It works in both VLC and qBittorrent.

Linux Mint 19.3 Cinnamon (4.4.8).

**Comment by ilya-fedin** [comment]
How can I emulate these keys to test myself?

**Comment by ilya-fedin** [comment]
>     1. install the DreymaR's Extend:

How can I test without that?

**Comment by mikkovedru** [comment]
1. I don't know what kind of signals some specific keyboards send. Some of them might be of the needed format and you can get the keyboard to test.

2. Or you can make your own little application that would send necessary keys.

3. Maybe you can find some program that would allow you to easily change the button combinations? Maybe something like [AutoKey](https://github.com/autokey/autokey) ( not to be confused with the similar Windows' program AutoHotKey )?

4. Or you could edit your keyboard files ( `/usr/share/X11/xkb/` ). You can see the examples in the Extend files (`https://github.com/DreymaR/BigBagKbdTrixXKB/tree/master/xkb-data_mod/xkb`) like here ( https://github.com/DreymaR/BigBagKbdTrixXKB/blob/master/xkb-data_mod/xkb/symbols/extend ): 
![image](https://user-images.githubusercontent.com/2521942/87576957-cea03f00-c6da-11ea-97a9-702d7b02c3d5.png)

I my opinion installing Extend is a way easier/cheaper option.

**Comment by ilya-fedin** [comment]
> I my opinion installing Extend is a way easier/cheaper option.

Not with my distro :see_no_evil:

**Comment by mikkovedru** [comment]
What kind of distro do you have?

Another option is to use VirtualBoxvVMWare, install Linux Mint, Extend and test everything in that virtual installation :-)

**Comment by ilya-fedin** [comment]
> What kind of distro do you have?

NixOS

**Comment by mikkovedru** [comment]
This issue is not resolved and I have definitely not lost interest. It's just that I can't fix the issue by myself and am at a mercy of other people.

**Comment by ilya-fedin** [comment]
>  It's just that I can't fix the issue by myself and am at a mercy of other people.

Well, I have no idea how to implement this and I guess @john-preston as well, so, without a people that know how to implement this, this couldn't be implemented.

**Comment by ilya-fedin** [comment]
@mikkoverdu how tdesktop is installed on your system? looks like this mod installs some xkb configs and if you're using snap or flatpak, it won't work.

**Comment by mikkovedru** [comment]
@ilya-fedin 
I downloaded the Telegram Desktop from the official web page, extracted it, put in the directory and created the shortcut on my Desktop.

**Comment by ilya-fedin** [comment]
will these custom keybinds work if you install telegram from your distro repositories that uses system Qt4?

**Comment by mikkovedru** [comment]
@ilya-fedin 
No. :-(

**Comment by ilya-fedin** [comment]
Have you checked the search field?

**Comment by ilya-fedin** [comment]
@mikkovedru

**Comment by mikkovedru** [comment]
@ilya-fedin 
Yes, I checked both the search field and the message writing fields. None of them work.

**Comment by ilya-fedin** [comment]
> Yes, I checked both the search field and the message writing fields. None of them work.

Are you 100% sure that it works in other Qt applications like qBittorrent? I have a feel that you confused something when you checked previously.

**Comment by uqs** [comment]
I'm currently playing around with QMK and KC_PASTE, which sends XF86Paste, which works perfectly fine in XTerm and Firefox, but I can confirm that it does nothing for a Qt5 programm (Clementine-Player).

**Comment by ilya-fedin** [comment]
So, this is not supported on Qt level and should be requested at Qt bugreport platform instead
