### ISSUE TITLE
missing markup in popup warning

### ISSUE THREAD

**Issue by botayhard** [telegramdesktop/tdesktop#5836]
### Steps to reproduce
1. login in new windows device
2. start export chat
3. click allow in telegram(mobile: +42777) chat

### Expected behaviour
the bold text should have been visible

### Actual behaviour
this(russian localization is most likely associated with a phone number)
![image](https://user-images.githubusercontent.com/30670180/54899770-823c5900-4f03-11e9-8684-4bf9e45f14fe.png)

### Configuration
**Operating system:**
Windows NT 6.3 build 9600
**Version of Telegram Desktop:**
1.6.2
**Used theme**:
standard or nothing

**Comment by john-preston** [comment]
@botayhard Thank you for your report.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by botayhard** [comment]
Nope.
![photo_2020-02-09_18-15-57](https://user-images.githubusercontent.com/30670180/74104704-5e5c2300-4b68-11ea-80a8-15ce48c900d3.jpg)
