### ISSUE TITLE
Telegram Web  emojis not showing 

### ISSUE THREAD

**Issue by ibnzUK** [telegramdesktop/tdesktop#5837]
Telegram web not showing many emojis, if user posts emoji from mobile application especially. 
Can you please update emoji database on telegram web. 

Bellow is attached picture. Very annoying experience and not pleasant look 

![image](https://user-images.githubusercontent.com/38762355/54910873-1ea33300-4ee5-11e9-92cc-a4e06ea13089.png)

**Comment by MasterGroosha** [comment]
Unfortunately, this repository for Telegram **Desktop**, not Telegram **Web**. You should open issue here instead: https://github.com/zhukov/webogram
