### ISSUE TITLE
Leave group function on tdesktop

### ISSUE THREAD

**Issue by LookTJ** [telegramdesktop/tdesktop#5839]
### Steps to reproduce
1. go to any group
2. click the three dots on right hand side
3. click "Leave group"

### Expected behaviour
Tell us what should happen

It should leave the group.

### Actual behaviour
Tell us what happens instead

It doesn't actually leave the group. It pops up back when someone sends a new message.

I had to leave the group on my Google Pixel phone, which worked.

### Configuration
**Operating system:**

Linux 5.0.1-arch1-1-ARCH #1 SMP PREEMPT Sun Mar 10 10:55:53 UTC 2019 x86_64 GNU/Linux

**Version of Telegram Desktop:**

v1.6.2

**Used theme**:

Midnight.

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@LookTJ Yes, thanks! I'll fix that in 1.6.3.
