### ISSUE TITLE
Link Preview Should Be Blocked/Display Warning for Untrusted Redirects

### ISSUE THREAD

**Issue by FreeCitizin** [telegramdesktop/tdesktop#5842]
I've noticed an attack on group of activists on Telegram. The attack consisted of the following:
1. Short url from twitter (t.co) 
2. IP logger
3. A destination that looks legit (Google doc)
I've created similar link with free public IP logger and a document I've found on the internet
YOUR IP WILL GET RECORDED, DO NOT OPEN IF YOU DON'T WANT
https://t.co/PI1uy0mFks

People active on twitter may think that this is a link to a tweet with the document but it's a trap to expose IP.

Solution IMHO is not to show preview if link is going through redirects. Or at least to show a warning in Telegram Desktop.
![RedirectDetective](https://user-images.githubusercontent.com/48927232/54948851-90a36880-4f35-11e9-958d-cbc442e81099.png)

**Comment by stek29** [comment]
First of all, previews are generated on server side.
Second -- processing redirects is a feature.
Yes, telegram might open final url when you click on shortened link, but what if redirect only applies to telegram crawlers?
