### ISSUE TITLE
High GPU usage? 

### ISSUE THREAD

**Issue by beavermml** [telegramdesktop/tdesktop#5844]
### Steps to reproduce
1.  run the Telegram
2.  wait for  a while
3.  high GPU usage in win10 taskmanager under  csrss.exe ( up to more than 50% )
4.  closing telegram ( minimizing it to background ) reduce it back to 0% usage

### Expected behaviour
there should be minimal GPU usage or none at all

### Actual behaviour
high GPU usage under csrss.exe ( Client Server Runtime Process )

### Configuration
Win10 1809
Triple Monitor Setup 
AMD HD 7850

**Version of Telegram Desktop:**
1.6.2

**Used theme**: none

**Comment by egslava** [comment]
Hello, Raja!

Could you, please, also, attach a screenshot with high GPU values?

**Comment by beavermml** [comment]
i dont know either there is an update on 1.6.3 or not OR its actually my windows machine is the problem. Now the problem is all gone.

**Comment by cmltaWt0** [comment]
<img width="797" alt="Screenshot at May 09 22-01-57" src="https://user-images.githubusercontent.com/877401/57479495-37558580-72a6-11e9-8347-537e3fd3e70c.png">



Telegram Desktop v1.6.7
MacBook Pro 15 2016

**Comment by cmltaWt0** [comment]
Running Telegram Desktop on mac book pro for me definitely useless.
The battery is depleted in 2-3h. 

I'll try Native version.
