### ISSUE TITLE
Telegram updates crashes gnome forces logout

### ISSUE THREAD

**Issue by acosonic** [telegramdesktop/tdesktop#5845]
### Steps to reproduce
1. Gnome desktop with extensions (topicon plus, dash to dock)
2. Click on update telegram button when it appears
3. Gnome crashes and forces logout, forgets which extensions were active

### Expected behaviour
Telegram updated without crashing Gnome

### Actual behaviour
Gnome crashed

### Configuration
**Operating system:**
Ubuntu Desktop 16.04 LTS

**Version of Telegram Desktop:**
All

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3963
