### ISSUE TITLE
Why there are two save buttons ?

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5847]
After changed a channel to private, it's public  link is not revoked completely and show in too many public links box. So revoked manually there again.

**Comment by john-preston** [comment]
@SmartManoj Maybe you didn't save the changes to the group type?

**Comment by stek29** [comment]
Are you referring to actual public link, or to joinchat link for the channel?

**Comment by SmartManoj** [comment]
@john-preston Yep, have to save twice

**Comment by SmartManoj** [comment]
Then Why the first save

**Comment by SmartManoj** [comment]
Label - question

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/62371587-dbbc3080-b552-11e9-9f85-efb4eaf14557.png)
