### ISSUE TITLE
#bug mp4 file not show on windows

### ISSUE THREAD

**Issue by telegramcore** [telegramdesktop/tdesktop#5848]
### Steps to reproduce
1. send mp4 video file on telegram through drag and drop
2. 
3. 

### Expected behaviour
it should appear as a gif reproduced cyclically

### Actual behaviour
it appears obscured and not reproducible
![Cattura 000369](https://user-images.githubusercontent.com/37411589/55026038-71264180-5002-11e9-945b-af4f60fd39b3.png)

### Configuration
**Operating system:** Windows 7 Professional 64 bit

**Version of Telegram Desktop:** Beta `1.6.3`

**Used theme**: [Shady Coral ](https://tlgur.com/d/GLNY51E4)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by kirsan31** [comment]
Very often I face with similar bug. mp4 (and may be other formats too) not play (stream) on fist attempt. And playing well after 2 try.
For example, 1 attempt on this [file](https://devblogs.microsoft.com/dotnet/wp-content/uploads/sites/10/2020/04/AddUsings.mp4?_=5) yeld this error in log:

> [2019.04.09 11:04:39] Streaming Error: Error in avformat_open_input (code: -1, text: Operation not permitted).

**Comment by Aokromes** [comment]
this bug is still valid? if yes, i suggest you to supply the affected video

**Comment by tgbetauser** [comment]
¯\_(ツ)_/¯ i Will check

**Comment by Aokromes** [comment]
@telegramcore

**Comment by telegramcore** [comment]
Probably it's fixed, I should try again

**Comment by Aokromes** [comment]
poke.

**Comment by telegramcore** [comment]
Sorry, I had no time to try

**Comment by Aokromes** [comment]
poke, i will close this issue on 2d if no answer of if it's still valid.

**Comment by telegramcore** [comment]
@Aokromes seems fixed
