### ISSUE TITLE
PLEASE REMOVE THIS FEATURE: Delete any message on both ends in any private chat

### ISSUE THREAD

**Issue by NabiKAZ** [telegramdesktop/tdesktop#5851]
> New in version 1.6.2:
> - Delete any message on both ends in any private chat, anytime.

## WTF?!!!!!!!!!!!!!!!!!
**This is just a stupid feature!
This is a violation of rights. Because my private message belongs to me and should not be removed by someone else.
This feature only helps fraudsters to remove our documents from our private chat!
I want and wish and please to remove this badly feature.
If you agree, please vote up(👍).**

**Comment by RememberTheAir** [comment]
API issue

**Comment by NabiKAZ** [comment]
@RememberTheAir  Ok, I don't find any link for it.

**Comment by stek29** [comment]
Contact in-app support, or ask them on twitter.
