### ISSUE TITLE
Telegram Desktop crash when i click to the group @DefoldEngine

### ISSUE THREAD

**Issue by NewTony** [telegramdesktop/tdesktop#5852]
### Steps to reproduce
1. Open Telegram Desktop
2. Click on Group @DefoldEngine

### Expected behaviour
View group chat

### Actual behaviour
The program hangs

### Configuration
**Windows 7 x64 Ultimate SP1**

**Version of Telegram Desktop:**
1.5.15
1.6.3

**Used theme**:
Classic

<details><summary><b>Сommunity</b>:</summary>
I asked in a group, several people have the same problem. All other channels work well.
</details>

<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/3012277/log.txt)
</details>

**Comment by MasterGroosha** [comment]
Can confirm a strange behaviour: whenever I open that group and scroll a bit, my enabled proxy starts to show "connecting" every 0.2 second.
Windows 10, TDesktop 1.6.3

**Comment by NewTony** [comment]
> Can confirm a strange behaviour: whenever I open that group and scroll a bit, my enabled proxy starts to show "connecting" every 0.2 second. ("connecting" -> "online" -> "connecting" every 0.2 sec)
> Windows 10, TDesktop 1.6.3. It doesn't hang though

Yes, I have the same

**Comment by john-preston** [comment]
@NewTony Should be fine now.

**Comment by NewTony** [comment]
> @NewTony Should be fine now.

Yes, now everything works fine. Thank you very much.
