### ISSUE TITLE
Messages markes as "read" on a locked screen

### ISSUE THREAD

**Issue by lapo-luchini** [telegramdesktop/tdesktop#5853]
### Steps to reproduce
1. open Telegram Desktop 1.6.3 on Windows 10
2. open a chat with a specific friend
3. lock screen (or activate screen saver, I guess it's the same)
4. the friend writes to you
5. a "double check" is immediately received by the friend
6. checking on Android app, the message is already marked as read (no number, no notification)

### Expected behaviour
Telegram Desktop should detect that the screen is not really visible and the message should not be marked as seen.

### Actual behaviour
My home PC woke up for some reason (I'm not sure about), and I lost a few notifications because Telegram Desktop back at home was open on that specific chat.

### Configuration
**Operating system:**
Windows 10
(Version	10.0.18362 Build 18362)

**Version of Telegram Desktop:**
1.6.3

**Used theme**:
Night mode.

**Comment by lapo-luchini** [comment]
I tested again:
1. asked a friend to write me and check
2. Windows+L to lock screen
3. his messages were "single check"
Thinking about it, yesterday it happened rather this way:

1. said hello & goodnight
2. put PC to sleep
3. PC woke up on its own
4. screen was still locked (reqeuiring password) but messages were marked as read (for that single chat, 
all others were "normal")

I don't know the internals of Telegram Desktop, but I can suppose it's something like this?

- on "lock" event: ignore chats
- on "unlock" event: start sending read marks again
- on "sleep" event: ignore chats
- on "resume from sleep" event: start sending read marks again (even if the screen is still locked).

Does it make any sense?
(I'll try and RTFS, if I can manage, to check)

**Comment by lapo-luchini** [comment]
I guess the "magic" happens in [`EventFilter::mainWindowEvent`](https://github.com/telegramdesktop/tdesktop/blob/a76658ba467581dc13689b328340ec381d39d689/Telegram/SourceFiles/platform/win/windows_event_filter.cpp#L62), but I'm not sure I see how right now.

**Comment by 23rd** [comment]
Can you test same thing but with old version of tdesktop, e.g. [1.5.15](https://github.com/telegramdesktop/tdesktop/releases/tag/v1.5.15)?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4664
