### ISSUE TITLE
Upgrade Telegram desktop linux to latest version

### ISSUE THREAD

**Issue by Wabri** [telegramdesktop/tdesktop#5856]
I'm on Debian 9 stretch and i want to upgrade telegram desktop without use more than 1 step, so I created a script to do that, but it's not so much easy than i thought.
I want simply update telegram with only one script using wget like this:
`wget -O telegram.tar.xz https://github.com/telegramdesktop/tdesktop/releases/latest/download/tsetup.tar.xz`
But i cannot do that because  the real link is **https://github.com/telegramdesktop/tdesktop/releases/latest/download/tsetup.1.6.3.tar.xz**
To avoid this problem I done some trick using github api:
```
curl --get https://api.github.com/repos/telegramdesktop/tdesktop/releases/latest | grep "browser_download" | grep "tar.xz" | tr -d '"'  > tout
cut -c 29- tout > tlast
rm tout
wget -O telegram.tar.xz -i tlast
rm tlast
tar xf telegram.tar.xz
sudo mv Telegram/Telegram /usr/local/bin/telegram
rm -r ?elegram*
```
It may be easier if tsetup doesn't have the specified version, because this script will be something like this:
```
wget -O telegram.tar.xz https://github.com/telegramdesktop/tdesktop/releases/latest/download/tsetup.tar.xz
tar xf telegram.tar.xz
sudo mv Telegram/Telegram /usr/local/bin/telegram
rm -r ?elegram*
```
Probably this is just my problem so I don't want to request a change just for me, it's just to ask.

### Configuration
**Operating system: Linux Debian 9 stretch**

**Version of Telegram Desktop: Latest**

**Used theme: dark**

**Comment by Johnnynator** [comment]
You can just fetch it from the telegram website instead of github
`wget -O telegram.tar.xz https://telegram.org/dl/desktop/linux`

**Comment by Wabri** [comment]
Huge thanks :1st_place_medal:
