### ISSUE TITLE
MacOS desktop client loses bot deeplink params

### ISSUE THREAD

**Issue by alexshavelev44** [telegramdesktop/tdesktop#5857]
### Steps to reproduce
1. Send share link to bot with deeplinks params (for example https://telegram.me/share/url?url=t.me/alextest44bot?start=123)
2. Press on it. Share to any user/saved messages

### Expected behaviour
In chat should be link `t.me/alextest44bot?start=123` (from the example above)

### Actual behaviour
Chat has `t.me/alextest44bot?start` link

### Configuration
High Sierra 10.13.4

**Version of Telegram Desktop:**
4.9.9

**Used theme**:
Default

**Comment by alexshavelev44** [comment]
video of reproduction https://vimeo.com/327078114

**Comment by john-preston** [comment]
@alexshavelev44 Shouldn't the value of url parameter be urlencoded?

**Comment by alexshavelev44** [comment]
@john-preston no. this form works on windows desktop and ios/android mobile apps. if url will be encoded it won't

**Comment by john-preston** [comment]
@alexshavelev44 But it should. The correct form is when parameters are encoded.

**Comment by alexshavelev44** [comment]
@john-preston ok. if i make `https://telegram.me/share/url?url=t.me%2Falextest44bot%3Fstart%3D123` then after sharing user will see `t.me%2falextest44bot%3fstart%3d123` which isn't clickable

![image](https://user-images.githubusercontent.com/45029602/55183505-a1074d80-5198-11e9-8245-371ad7f2d909.png)
![image](https://user-images.githubusercontent.com/45029602/55183517-a6649800-5198-11e9-8943-0359b3600418.png)

**Comment by john-preston** [comment]
@alexshavelev44 Did you try that in Telegram Desktop? Right now you try on Telegram for macOS, another macOS app. You can try Telegram Desktop from https://desktop.telegram.org

**Comment by stek29** [comment]
This is not TDesktop but a different app -- from https://macos.telegram.org.
You can get TDesktop at https://desktop.telegram.org.
(There are two apps in Mac App Store as well).

You can report issues in the app you're using at https://t.me/macswift, or at https://github.com/overtake/TelegramSwift.
