### ISSUE TITLE
[Feature Request] - Change notification sound (.wav, etc)

### ISSUE THREAD

**Issue by squirrelboot** [telegramdesktop/tdesktop#586]
Simply put, it would be nice to be able to theme the messenger to fit my current system theme. I can change the background picture which is lots of fun, but we can't currently change the notification sound. A simple browse to and select for a wav would be relatively simple I'd imagine.. 

Also, could we possibly allow different backgrounds for different contacts?

**Comment by cobalto** [comment]
Second part #587

**Comment by SniperRus** [comment]
+1

**Comment by kireledan** [comment]
I have implemented this feature. I will be posting a pull request shortly.

**Comment by squirrelboot** [comment]
Thank you!!!

**Comment by Sushubh** [comment]
I just installed the desktop app and I cannot find this option anywhere. Advice please?

**Comment by navjotjsingh** [comment]
Same care. Couldn't spot the setting anywhere.

**Comment by navjotjsingh** [comment]
+1 for the feature. Please add.

**Comment by navjotjsingh** [comment]
Refers to #151
