### ISSUE TITLE
Name secret chats

### ISSUE THREAD

**Issue by omyno** [telegramdesktop/tdesktop#5861]
Currently it is not possible to see which device a secret chat is assigned to. If I start a secret chat with Peter, I don't know if my messages in this chat will arrive at his Laptop, Office PC or mobile phone.

It would be great to either
- automatically show information about the device which the secret chat has been started with ("Secret chat on Peter's MacBook")
- manually name a secret chat (e.g. "Peter's MacBook")

**Comment by RememberTheAir** [comment]
Telegram Desktop doesn't support secret chats. Maybe you are using https://github.com/overtake/TelegramSwift?

**Comment by omyno** [comment]
I am sorry, you are right.
