### ISSUE TITLE
Telegram sometimes freezes while loading GIFs

### ISSUE THREAD

**Issue by DASPRiD** [telegramdesktop/tdesktop#5866]
Since a few weeks (can't pin down the exact version anymore), Telegram keeps freezing about once or twice a day while loading GIFs. This doesn't happen each time, so it isn't reproducible reliably.

I ran Telegram with the `-debug` option, but there's nothing special showing up in the logs nor `STDOUT`.

### Configuration
**Operating system:** Linux
**Version of Telegram Desktop:** 1.6.3
**Used theme**: Default theme, dark mode

**Comment by tux93** [comment]
Happens occasionally here too, couldn't find anything  in the logs either though

openSUSE Tumbleweed
Telegram 1.6.2
Matrix Theme, Night Mode on

Will have to wait and see if it's still there with 1.6.4

**Comment by DASPRiD** [comment]
For now I downgraded to Ubuntu's version of Telegram (1.2.17), which doesn't suffer the problem. But of course I'd like to have the newer features gain ;)

**Comment by tux93** [comment]
Just happened again on 1.6.5, adding the log even though I don't see anything related

[log.txt](https://github.com/telegramdesktop/tdesktop/files/3051980/log.txt)

**Comment by 1kevin335200** [comment]
Save issue.

**Comment by 1kevin335200** [comment]
log file contains only these things:
[2019.05.07 08:12:05] Exception: unknown cons 0xa043
[2019.05.07 08:12:09] Exception: unknown cons 0xa91f
[2019.05.07 08:12:11] Exception: unknown cons 0x7310
[2019.05.07 08:12:12] Exception: unknown cons 0x778c
[2019.05.07 08:12:13] Exception: unknown cons 0x6cf7
[2019.05.07 08:12:14] Exception: unknown cons 0x76b9
[2019.05.07 08:12:15] Exception: unknown cons 0x9941
[2019.05.07 08:12:16] Exception: unknown cons 0x7589

**Comment by 1kevin335200** [comment]
Problem started from v1.5.16, i believe.
Have tested several versions
1.5.17: freezes
1.5.16: freezes
1.5.15: not reproduce yet
1.5.0: not reproduce yet

All above versions have "Exception: unknown cons 0x7589" messages, so it's not fully related.

Also, v1.5.16 has a new feature: Play video files and listen to received music without waiting for them to download, which i think may cause this issue

**Comment by ronlaws86** [comment]
Confirming on Linux build 1.6.7 - Have to go in to the system monitor and forcefully kill the process or you cannot re-open telegram, a zombie process remains even if the GUI App is terminated via the desktop manager,

**Comment by Hamper** [comment]
I have same error, but in stdout:
```
[h264 @ 0x7f4d242ce240] A non-intra slice in an IDR NAL unit.
[h264 @ 0x7f4d242ce240] decode_slice_header error
```

**Comment by ronlaws86** [comment]
Still happening in build 1.8.2 

Linux version: Mint 18.2 - Cinnamon edition.

**Comment by Newbytee** [comment]
Does it only freeze for you? I have a similar issue, except it segfaults (and thus crashes).

**Comment by tux93** [comment]
For me it only freezes and then has to be force-quit

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Newbytee** [comment]
> this bug is still valid?

Yes. It still occurs for me. I'll keep you updated whether I still can reproduce it with 1.9.4.

**Comment by Aokromes** [comment]
try 1.9.8 it's latest and fixed few gifs issues.

**Comment by Newbytee** [comment]
@Aokromes I've been using 1.9.8 and subsequently 1.9.9 for two weeks together now and I've not experienced a single crash, I think it's safe to say this one is fixed on my end at least.
