### ISSUE TITLE
Crashes if "Save Image As..." links to a unmounted disk

### ISSUE THREAD

**Issue by jeyemwey** [telegramdesktop/tdesktop#5868]
### Steps to reproduce
1. Mount a Network Drive linking to another computer or NAS
2. Use the Context Menu to save an image on the drive
3. Disconnect the drive (I moved to an other wifi)
4. Try to save another image.

### Expected behaviour
If the desired folder is not available, Telegram should open Quick Access or `~`. At least, Windows should give a warning that the desired folder is not available.

### Actual behaviour
Telegram crashes.

### Configuration
**Operating system:**
Windows 10 1809

**Version of Telegram Desktop:**
Telegram 1.6.3

**Used theme**:
Classic

**Comment by john-preston** [comment]
@jeyemwey Can you please enable "Install beta versions" in Settings > Advanced and then reproduce the crash? When you launch the app after the crash it should offer you to send a crash report. Please copy the "Your report tag" string from the crash report sending window and send the report. Copy the tag here and I'll try to see in the report at what place it crashes.

**Comment by jeyemwey** [comment]
I can't reproduce the problem in beta.

When I try to reproduce, the app takes _forever_ but then opens `%APPDATA%\Telegram Desktop`. Not `~\Downloads\Telegram Desktop`, but at least it doesn't crash.

Sorry for the inconvenience.

**Comment by Aokromes** [comment]
if this bug is still valid, plz ask to reopen.
