### ISSUE TITLE
[Feature request] Choose a different background by user (no more wrong chat!)

### ISSUE THREAD

**Issue by intrd** [telegramdesktop/tdesktop#587]
Why?
I bet everyone here already typed in the wrong chat.. this could be minimized if you can choose a different background by user

**Comment by Arttse** [comment]
Agree. Necessary feature

**Comment by cobalto** [comment]
lol all the time. Yes, I agree with it.

**Comment by Aokromes** [comment]
+1 to add this feature.

**Comment by Aokromes** [comment]
BTW duplicate of #523

**Comment by AhmedDjoudi** [comment]
True, and also the possibility to pin some conversations so that they don't move when you receive messages.

+1

**Comment by intrd** [comment]
+1 ..

**Comment by yashpalgoyal1304** [comment]
label: duplicate
