### ISSUE TITLE
tg://save

### ISSUE THREAD

**Issue by JerryGreen** [telegramdesktop/tdesktop#5871]
I have a feature request:

I wanna be able to use url something like:

`
tg://save?text=Hello, there! This note should automatically appear in Saved Messages when you click a tg link
`

After a click on such url, the Telegram app should open a "Saved Messages" conversation and paste the text right there:

![image](https://user-images.githubusercontent.com/13215662/55384160-5fcdbf80-5543-11e9-89b9-9d91a8d53c4f.png)

P.S. I'm not sure if the message should be immediately saved or not. I think just to paste the content to the dialog will be good enough.
P.P.S. This will let other apps to integrate with Telegram. I wanna make a browser extension which will let to save links to telegram

**Comment by stek29** [comment]
I'd recommend you to use `tg://share`, and ask for this on twitter or via in-app support.
