### ISSUE TITLE
"Do Not Disturb" is ignored on Windows 10

### ISSUE THREAD

**Issue by felixlinker** [telegramdesktop/tdesktop#5873]
### Steps to reproduce
1. Enable do not disturb
2. Receive any notification

### Expected behaviour
No sounds or visual indicator should appear (besides unread messages symbol)

### Actual behaviour
The notification sounds is played and the taskbar icon is flashing

### Configuration
**Operating system:** Windows 10 Version 10.0.17134 Build 17134

**Version of Telegram Desktop:** from Windows Store 1.6.3

**Used theme**: Default

### Further notes

Behavior is very similar as described in #3095

**Comment by stek29** [comment]
#4641 ?

**Comment by felixlinker** [comment]
Cheers. I didn't know that feature was called "quiet hours" in English so I didn't look up that term when searching for duplicates.
