### ISSUE TITLE
Use default sound input on linux

### ISSUE THREAD

**Issue by Ceda-EI** [telegramdesktop/tdesktop#5874]
### Steps to reproduce
1. Set default audio input device in linux. (in my case, I set it via `pavucontrol` (frontend to `pulseaudio`))
2. Record a voice note.

### Expected behaviour
Telegram uses the default audio input device. 

### Actual behaviour
Telegram does not use the default audio input device. Instead it always uses the in-built sound card (because it is the first card?). It does not respect the default. Changing the setting under `Settings > Advanced > Call Settings > Input device` changes the input device only for calls.

### Configuration
**Operating system:** Linux

**Version of Telegram Desktop:** 1.6.3

**Comment by malnvenshorn** [comment]
Was about to report the same issue. It is the same bug as reported way back in ticket #418 which is closed despite it was not fixed or maybe it's a regression bug?! Calls are working fine, but I'm not able to hear sounds from videos with my headset. Therefore please please please add an option to select the output device independently from the call settings.

**Comment by Palando** [comment]
It seems that Telegram uses the new settings when a new voice message starts but not immediately when I change the output device. I am not sure if this is the same issue because it's about changing the device at run time. (Telegram 1.7.14 with libpulse 12.2.0)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2231
