### ISSUE TITLE
Please add a shortcut to switch between accounts

### ISSUE THREAD

**Issue by broslavski** [telegramdesktop/tdesktop#5875]
### Steps to reproduce
When you try to change account now you should:
1. Click the account icon at the bottom bar.
2. Click account name you need at the accounts list.
3. Click the chats icon at the bottom bar.
4. Choose the chat you need and click it.

### Expected behaviour
There should be a shortcut which easy switches between accounts and eliminates several clicks.

### Actual behaviour
Described in the steps section above.

### Configuration
**Operating system:**
macOS Mojave 10.14.3 (18D109)
**Version of Telegram Desktop:**
5.0.1 (164832) AppStore
**Used theme**:
Day Classic

**Comment by RememberTheAir** [comment]
You're using the native MacOS app, not tdesktop

**Comment by stek29** [comment]
This is not TDesktop but a different app -- from https://macos.telegram.org.
You can get TDesktop at https://desktop.telegram.org.
(There are two apps in Mac App Store as well).

You can report issues in the app you're using at https://t.me/macswift, or at https://github.com/overtake/TelegramSwift.
