### ISSUE TITLE
Telegram re-adds shortcut on every open?

### ISSUE THREAD

**Issue by klepp0906** [telegramdesktop/tdesktop#5877]
### Steps to reproduce
1. Close telegram
2. Delete shortcut from start menu
3. Open Telegram

### Expected behaviour
Telegram should open without recreating any shortcuts.

### Actual behaviour
Telegram opens, but re creates deleted (or in my case moved) shortcut in start menu.

### Configuration
Windows 10

**Version of Telegram Desktop:**
1.6.3
**Used theme**:
blue
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2066#issuecomment-220851137
