### ISSUE TITLE
Media Cache are kept even when download is complete

### ISSUE THREAD

**Issue by ThigSchuch** [telegramdesktop/tdesktop#5878]
### Steps to reproduce
1. Find a media that you can stream.
2. Play it and wait load all.
3. Check media_cache folder. (Will have something downloaded)
4. Check Telegram Desktop folder in Downloads (default). (Will have nothing downloaded)
5. Download it (again?) through "Download" button.

### Expected behaviour
Stream download was complete, move cache (the real file of the media) to Downloads.

### Actual behaviour
Download twice.
Media cache are kept with no need if I stream and download through "Download" icon later.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** v1.6.3

**Used theme**: Default Midnight

**Comment by john-preston** [comment]
@ThigSchuch Yes, unfortunately for now they're independent. In the future it was planned to use loaded cache data for downloading (not re-download any parts), but clearing the media cache in that case was not planned — it will be cleaned anyway in some time.

**Comment by john-preston** [comment]
Now downloading to a file uses the cache for fast download. Also download icon in message isn't shown if the file is fully cached in media cache.
