### ISSUE TITLE
[Feature request] Option to have all messages on left side

### ISSUE THREAD

**Issue by gazzerh** [telegramdesktop/tdesktop#5880]
"Adaptive layout for wide screens" is a great option but it would be nice to have an option to **always** have the messages on the left hand side and not only when the window is above a certain size.

**Comment by Kealix** [comment]
Great idea, would use this feature all the time.

**Comment by Storm-Engineer** [comment]
This very simple feature wouldn't take much work to realize. I'm sad to see this ticket exists for 9 months and there is still no development on it. :(

I made a ticket too ( https://github.com/telegramdesktop/tdesktop/issues/7020 ) which gives a bit more context to why this feature would be needed.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2236
