### ISSUE TITLE
Advertise FreeBSD support on website?

### ISSUE THREAD

**Issue by lapo-luchini** [telegramdesktop/tdesktop#5881]
Now that Telegram Desktop is [officially in FreeBSD Ports](https://www.freshports.org/net-im/telegram-desktop/) it would be nice to advertise the fact [in the official homepage](https://desktop.telegram.org).

Right now, when visiting the website from FreeBSD, «Get Telegram for Linux 64 bit» is shown instead.

**Comment by RememberTheAir** [comment]
It is not officially mantained by Telegram

**Comment by lapo-luchini** [comment]
I see. Then maybe "sorry, no **official** support for your OS" would be better than the wrong OS?
