### ISSUE TITLE
compared to other apps streaming audio takes very high CPU usage 

### ISSUE THREAD

**Issue by YousefSaber** [telegramdesktop/tdesktop#5882]
in Ubuntu 18.10 
Telegram v1.6.7 snap app

streaming audio ( without downloading it first on my PC ) takes very high CPU usage 

Spotify uses only 5% while Telegram uses 10%??

does Telegram has good sound hardware acceleration support in linux ?

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by YousefSaber** [comment]
> this bug is still valid?

yes on Telegram v1.8.5 this issue is still valid spotify uses 7~10% and Telegram 17~20%

**Comment by Aokromes** [comment]
plz test 1.9.8

**Comment by Aokromes** [comment]
plz, test on 1.9.17, if no answer i will close this ticket on the next week.

**Comment by YousefSaber** [comment]
@Aokromes I've tested it on version 1.9.9 beta ( snap app) 
for some reason Spotify snap app has crashed and no longer works I installed the Spotify app from the official repository takes around 20% the executable firefox browser takes around 25~30$
the telegram takes around 20% running local mp3 files on my Ubuntu 19.10 takes around 10~15%
you may want to close the issue if you want I guess that Linux and Ubuntu systems suffer from poor hardware acceleration for both video playback and audio playback but if you could improve or fix this issue for your app that will be appreciated 
since there are no apps that play audio uses CPU less than Telegram you are free to close this issue.
