### ISSUE TITLE
Empty 1x1 photo received

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#5886]
### Steps to reproduce
1. Receive photo from user

### Expected behaviour
Photo is shown normally
![image](https://user-images.githubusercontent.com/1321838/55654008-d21afa00-57f8-11e9-8fa7-9be141705dd1.png)

### Actual behaviour
Sometimes instead of a normal photo, an 1x1 image is shown
![2019-04-05_23-15-20](https://user-images.githubusercontent.com/1321838/55653925-9a13b700-57f8-11e9-9e39-d645fe081009.png)
When I try to open this photo, it shows that this is an empty message:
![2019-04-05_23-15-45](https://user-images.githubusercontent.com/1321838/55653969-b7e11c00-57f8-11e9-86d8-f5e96227ec28.png)
When I try to save image, save file dialog is not displayed

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 1.6.4 beta

**Used theme**: Midnight

**Comment by john-preston** [comment]
@aNNiMON I'll need debug logs for that :( you can contact me at t.me/preston for that.

**Comment by john-preston** [comment]
@aNNiMON I hope this will be fixed on the server side and won't require tdesktop update. Thanks for the report!

**Comment by aNNiMON** [comment]
It works now, thanks!
