### ISSUE TITLE
Can't update to 1.6.4

### ISSUE THREAD

**Issue by YouTwitFace** [telegramdesktop/tdesktop#5887]
### Steps to reproduce
1. Go to settings > Advanced
2. Click check for update
3. Click update telegram

### Expected behaviour
Should update (to 1.6.4)

### Actual behaviour
Nothing

### Configuration
**Operating system:** Linux mint

**Version of Telegram Desktop:** 1.6.3

**Used theme**: Midnight (default)

<details><summary><b>Logs</b>:</summary>
(Can't find logs even with debugmode enabled)
</details>

**Comment by Johnnynator** [comment]
1.6.4 is a beta release, so you should make sure that updating to beta version is allowed.

**Comment by YouTwitFace** [comment]
@Johnnynator it is... the update telegram button appears and it restarts when I click it.

**Comment by stek29** [comment]
is this still an issue?

**Comment by YouTwitFace** [comment]
@stek29 I ended up downloading it from https://desktop.telegram.org but I was able to update 1.6.5, .6 and .7.

**Comment by YouTwitFace** [comment]
I'll close this issue for now. If I have the problem again, I'll reopen it.
