### ISSUE TITLE
CJK Font fallback issue

### ISSUE THREAD

**Issue by imbushuo** [telegramdesktop/tdesktop#589]
All Chinese texts in English OS will display in a strange font. However it will display with Simsun in Chinese OS.

In modern Windows, Microsoft YaHei should be used for Chinese texts.

**Comment by Jamesits** [comment]
Please use the default interface font (and default fallback strategy) of the OS. Simsun used as CJK interface font is uncommon and not elegant.

**Comment by nebulakl** [comment]
+1
take a look of this screenshot to see how ugly it is
![image](https://cloud.githubusercontent.com/assets/12024936/7549621/208a7510-f670-11e4-9bcc-40a86890b38e.png)

**Comment by bennyyip** [comment]
+1

**Comment by Aokromes** [comment]
#90 ?

**Comment by kid1412621** [comment]
Is there a solution for UWP Telegram?

**Comment by Jamesits** [comment]
@kid1412621 If you want to try MacType (note this always has some stability issues on Windows 10) you can use this config: https://gist.github.com/Jamesits/6a58a1b08d5cd09a94a02f30ddaf0e13

**Comment by kid1412621** [comment]
@Jamesits Thx,dude.I don't like MacType,so maybe official will fix this.

**Comment by ChungZH** [comment]
Use [FontMod](https://github.com/ysc3839/FontMod/)

**Comment by ilya-fedin** [comment]
I hope this issue can be finally closed

**Comment by Aokromes** [comment]
https://i.imgur.com/yu5VvoN.png is ok?

**Comment by Aokromes** [comment]
a friend living on korea tells me korean is ok now.

**Comment by Aokromes** [comment]
@imbushuo @nebulakl this issue can be closed?

**Comment by imbushuo** [comment]
@Aokromes Sorry for the late reply. This looks mostly fine with some minor glitches. A perfect solution might get very complicated (i.e. character set detection, CJK variant selection, etc.) as of now I think the issue can be closed.
