### ISSUE TITLE
Unknown crash

### ISSUE THREAD

**Issue by lizr2004** [telegramdesktop/tdesktop#5890]
### Steps to reproduce
I Don't Know, steps below are what i've done
1. listened a voice message
2. type
3. CRASH

### Expected behaviour
works normally

### Actual behaviour
crash without any warning

### Configuration
**Operating system: Archlinux**

**Version of Telegram Desktop: 1.6.3-1**

**Used theme**:
For Telegram: Just *midnight* (night mode on)
For Qt: qt5ct fusion arc(icon) [color](http://fars.ee/rgwG)
For Gtk: Materia-dark-compact arc(icon)

**Logs**:
TOO LONG TO PASTE...
journald: [click me](http://fars.ee/axH1)
coredumpctl: [click me](http://fars.ee/bNJw)
core: [click me](https://0x0.st/zZqe.lz4) so large that may be deleted in 2 months

**Comment by lizr2004** [comment]
Core dumped, but it's too large(lz4 compressed 147M). so i think it can be a memory leak.

**Comment by edward-p** [comment]
Probably, the same issue here:
coredumpctl: [click me](https://0x0.st/zZb0.log)
coredump: [click me](https://0x0.st/zZbI.lz4)

**Comment by stek29** [comment]
Please get latest beta, and you'd have option to report crash. Post the crash tag.
