### ISSUE TITLE
Unable to upload again after interrupting an upload

### ISSUE THREAD

**Issue by threelegcat2015** [telegramdesktop/tdesktop#5891]
Unable to upload again after interrupting an upload of a huge file.
### Steps to reproduce
1. Interrupting an upload (for a file of huge size)
2. Upload another file
3. Restart and retry uploading

### Expected behaviour
File should upload sucessfully.

### Actual behaviour
File can't be uploaded and wait forever.

### Configuration
**Fedora 29 (x86_64)**

**Version of Telegram Desktop:**
1.6.3
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by threelegcat2015** [comment]
Solved after clearing cache. Thx!
