### ISSUE TITLE
Feature request: Hotkey to Switch Accounts

### ISSUE THREAD

**Issue by 360fun** [telegramdesktop/tdesktop#5894]
Would be great if you can add an hotkey to **switch between accounts**! ;) Thanks!

**Comment by lampanon** [comment]
Well, Telegram Desktop version does not support multiple accounts at all. Only by using separate instances. And there is a shortcut for a long time to switch between them - 
```
alt+tab
```


Maybe you're talking about a native app for macos? If So, you asked on the wrong github page.

**Comment by 360fun** [comment]
> Maybe you're talking about a native app for macos? If So, you asked on the wrong github page.
d'oh! >.< sorry :P
