### ISSUE TITLE
Span Inline Buttons in next row

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#5895]
![image](https://user-images.githubusercontent.com/7231077/55672404-69935200-58b8-11e9-8d26-ec263426cbf2.png)

**Comment by Nachtalb** [comment]
How many buttons there are per row is decided by the developer of the telegram bots, not by the client.

**Comment by SmartManoj** [comment]
Then expand the width of the button

**Comment by Nachtalb** [comment]
Then this is probably what you want: #2060

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by RememberTheAir** [comment]
Yes

**Comment by SmartManoj** [comment]
Test link: https://t.me/ToMySweetie/65
