### ISSUE TITLE
Show in Folder not working in Fedora 29

### ISSUE THREAD

**Issue by dimon2242** [telegramdesktop/tdesktop#5896]
### Steps to reproduce
1. Run Telegram Desktop
2. Open any conversation
3. Click right buttom of mouse on any file and click to Show in Folder

### Expected behaviour
Open in file manager (nautilus in this case) folder with this file

### Actual behaviour
File manager (nautilus) isn't opened

### Configuration
**Operating system:**
Fedora 29

**Version of Telegram Desktop:**
1.6.3

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Error in terminal:
nautilus: unknown option --no-desktop
</details>

In GNOME 3.30 nautilus argument "--no-desktop" is deprecated?

**Comment by xvitaly** [comment]
Telegram Desktop from RPM Fusion, Flatpak or official website?

**Comment by dimon2242** [comment]
Official from telegram.org

**Comment by xvitaly** [comment]
Try version from RPM Fusion and don't forget to remove updater/etc from `~/.local/share/TelegramDesktop`.

**Comment by tim77** [comment]
Same here.
Telegram from rpmfusion.
OS: Fedora 30.
