### ISSUE TITLE
[Feature Request] Support mathematical expressions in LaTeX format

### ISSUE THREAD

**Issue by taneher** [telegramdesktop/tdesktop#5898]
It would be great, if Telegram would support mathematical expressions e.g. written in LaTeX notation. So for example `\sigma_{z}' = \dfrac{e^-z}{(1+e^-z)^2}` would show as nicely formatted mathematical expression with super- and subscript, horizontal fraction bar and all the likes.

You could e.g. use [this approach](https://stackoverflow.com/a/32750804) with a online latex equation editor.

**Comment by stek29** [comment]
I'd recommend to use bots for that.

See #3788 #1349 #636
