### ISSUE TITLE
Telegram Desktop: audio messages made with IPhone aren't played.

### ISSUE THREAD

**Issue by lalincedeldeserto** [telegramdesktop/tdesktop#5899]
I can't reproduce audio messages with Telegram Desktop sent from iPhones. I'm using telegram-desktop-1.6.3_1 with Linux (Void Linux, rolling distro):

I suppose the problem is in the codec used by Apple (maybe with latest updates there are incompatibilities).
Audio messages sent with Android works.
I have to press multiple times on the play button to hear part of an audio message (not all of it because it stops sooner).
no problem if you need to know more info about my configuration ;)

**Comment by john-preston** [comment]
@lalincedeldeserto Does the version from https://desktop.telegram.org work?

**Comment by lalincedeldeserto** [comment]
> @lalincedeldeserto Does the version from https://desktop.telegram.org work?

@john-preston the version from https://desktop.telegram.org works like a charm :+1: 
No problems with audio files

**Comment by Qwerty-Space** [comment]
I wouldn't say this is invalid.
It's still an issue that affects the version of tdesktop in different distros repos.  i have the same issue on manjaro, tdesktop 1.7.3 installed from the community repository.

**Comment by Qwerty-Space** [comment]
it would seem that #5843 is a duplicate
