### ISSUE TITLE
Localization shortcut doesn't work properly on Linux

### ISSUE THREAD

**Issue by malishev** [telegramdesktop/tdesktop#590]
The "Shift+Alt+Click" combination doesn't work on some environments, if such a shortcut is selected as language switcher. 

Solution: after changing the language switching shortcut to any other (for ex., Shift+Ctrl), everything works fine on almost all systems (Mint 17 Cinnamon doesn't work anyway).

The same problem is reported in the issue https://github.com/telegramdesktop/tdesktop/issues/544

**Comment by pdonadeo** [comment]
Confirmed not working in Fedora 21

**Comment by GrayWolfik** [comment]
I, too, did not work the choice of language. I use ALT Linux 7 and Mate

**Comment by Tel2440431** [comment]
https://tlgrm.ru/faq/localization.html#hcm=1439543208606890

CTRL+SHIFT+ALT+left click. 
Будьте счастливы.

**Comment by ezdev128** [comment]
@Tel2440431 that doesn't work and never worked before.
П.С.: этой баге сто лет в обед и фиксить не хотят (с)

**Comment by Tel2440431** [comment]
На Linux Mint 17 Cinnamon работает.  14.08.2015, 12:16, "Konstantin M." <notifications@github.com>:@Tel2440431 that doesn't work and never worked before. П.С.: этой баге сто лет в обед и фиксить не хотят (с)—Reply to this email directly or view it on GitHub.

**Comment by ezdev128** [comment]
@Tel2440431 на циннамоне работало. Не работает на LMDE. https://github.com/telegramdesktop/tdesktop/issues/544

**Comment by Tel2440431** [comment]
Не работало на циннамоне. 
Комбинация Шифт+альт+клик не срабатывала. Оказывается, надо было добавить ctrl



На 14 Авг 2015 г., 12:44, в 12:44, "Konstantin M." <notifications@github.com> написал:>@Tel2440431 на циннамоне работало. Не работает на LMDE.

**Comment by ezdev128** [comment]
@Tel2440431 с CTRL так же не работает.
Вообще, имхо, не стоило бы завязываться на хоткеи. Ненадежно это.
Нужна кнопка, что-то типа "Load alternative localization file".

**Comment by GrayWolfik** [comment]
Как не работало, так и не работает. Все комбинации перепробовал еще в первый
раз.

**Comment by Tel2440431** [comment]
Ну, видимо, с LMDE тяжёлый случай..
Минт 17 XFCE работает шифт+альт+клик, минт 17 кде тоже.
Матэ не пробовал, циннамон работает ctrl+shift+alt+click



На 14 Авг 2015 г., 14:22, в 14:22, GrayWolfik <notifications@github.com> написал:>Как не работало, так и не работает. Все комбинации перепробовал еще в

**Comment by telegramdesktop** [comment]
From version 0.8.50.dev and after you can type "loadlang" in Settings instead of clicking with Alt+Shift.
