### ISSUE TITLE
Different backgrounds for different chats suggestion

### ISSUE THREAD

**Issue by D0ctorWh0** [telegramdesktop/tdesktop#5900]
If we could set differrent backgrounds for chats, it would be great. For example it could prevent user from writing to wrong chat

**Comment by stek29** [comment]
#2642

**Comment by gregkotsaftis** [comment]
I have the same issue! Frequent messages to the wrong contact! Sometimes it is SO EMBARRASSING !!!!
pls fix this!

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/523
