### ISSUE TITLE
Unexpected quit after changing download folder

### ISSUE THREAD

**Issue by michelezoncheddu** [telegramdesktop/tdesktop#5903]
### Steps to reproduce
1.  Set a custom download folder
2. Close and open Telegram Desktop at least twice

### Expected behaviour
A regular close

### Actual behaviour
An “unexpected quit” message will appear after few seconds

### Configuration
macOS 10.14.4

**Version of Telegram Desktop:**
1.6.3 (Italian)

**Used theme**:
Blue

<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/3058163/log.txt)
</details>

**Comment by john-preston** [comment]
Please check the latest beta version 1.6.5. Does it still happen there? You can enable updating to the beta versions in Settings > Advanced.

**Comment by michelezoncheddu** [comment]
I couldn't find the beta toggle because the app was installed through the App Store. So I tried installing Telegram with the .dmg file, and I found no bug, even in the 1.6.3 version (and here I found the beta toggle).
Thanks!
