### ISSUE TITLE
ALT+ENTER shortcut doesn't take you to the top when the focus is on a chat

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#5904]
### Steps to reproduce
1. use arrow-down to browse your chats list to the bottom
2. use ALT+ENTER to get back to the top

### Expected behaviour
ALT-ENTER takes you back to the top of your chats list

### Actual behaviour
ALT-ENTER opens the chat you've the focus on

### Configuration
**Operating system:** Windows 10, Linux Mint

**Version of Telegram Desktop:** 1.6.5

**Comment by Edicksonjga** [comment]
Press ALT + ENTER again or simply ENTER to go to the top of the list of chats.

1st ALT + ENTER "Select the chat you were looking for through the navigation in the chat list".
2nd ALT + ENTER "Go up to the beginning of the Chats List."

PS: If the chat is a channel, by pressing the command ALT + ENTER (or ENTER), it does not work, it only works for groups / bots / private chats. In the same way you can use the new floating button.

**Comment by RememberTheAir** [comment]
I know how to workaround it, but this is an issue nonetheless. If I want to open the chat I have the focus on, I use ENTER. If I want to get back to the top, I should be able to use ALT+ENTER. Also because opening the chat and exiting it just to make ALT+ENTER wor (especially when you're on a slow net, becase ESC doesn't work until at least a message is loaded (#4111)) is time consuming

**Comment by RememberTheAir** [comment]
Still relevant

**Comment by RememberTheAir** [comment]
Still valid

**Comment by RememberTheAir** [comment]
Still relevant on 3.7

**Comment by RememberTheAir** [comment]
Still relevant on 4.2.4

**Comment by RememberTheAir** [comment]
doesn't work, still an issue

**Comment by ilya-fedin** [comment]
Both #5905 and this one are a part of the send message handler. Both of these actions happen whenever you press either Enter or Alt+Enter, have you message written in the field or not. When the chat is closed, the handler couldn't be called.

**Comment by RememberTheAir** [comment]
@ilya-fedin btw is this supposed to work? in #5905 you mention that the wiki is maintained by users so it's not an actual source of truth (fair), but it also looks like tdesktop is actually supposed to offer those shortcuts

**Comment by ilya-fedin** [comment]
@RememberTheAir this is a send message shortcut and it's switchable in settings. You're likely having non-default settings. Removing tdesktop data should fix the shortcut for you I believe.
