### ISSUE TITLE
ALT+ENTER inside the chat screen - does it work?

### ISSUE THREAD

**Issue by RememberTheAir** [telegramdesktop/tdesktop#5905]
### Steps to reproduce
1. open a chat with some unread messages
2. use ALT-ENTER

### Expected behaviour
The wiki says that this will bring you to the bottom of the chat

### Actual behaviour
Nothing happens. Clicking on the arrow-down floating button brings me to the bottom of the chat, but ALT-ENTER does nothing

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.6.5

**Comment by lampanon** [comment]
This problem only happens in chats where you cannot send messages (other user's channels for example). This shortcut works as it should in groups and private chats.

**Comment by RememberTheAir** [comment]
@lampanon mmm, it doesn't work in private chats and groups too, for me

**Comment by RememberTheAir** [comment]
Still doesn't work

**Comment by RememberTheAir** [comment]
Still doesn't work

**Comment by RememberTheAir** [comment]
All ALT+ENTER shortcuts (#5904) do not work yet

**Comment by RememberTheAir** [comment]
All ALT+ENTER shortcuts (https://github.com/telegramdesktop/tdesktop/issues/5904) do not work yet

**Comment by RememberTheAir** [comment]
can confirm [this](https://github.com/telegramdesktop/tdesktop/issues/5905#issuecomment-1281906451)

**Comment by ilya-fedin** [comment]
I have just tested and this does work to me. It may not work for you due to some non-default settings.

**Comment by ilya-fedin** [comment]
Note that the wiki is maintained by users, it's not necessarily a (actual) source of truth.
