### ISSUE TITLE
Screen turns off / timeout when scrolling through messages

### ISSUE THREAD

**Issue by Younes-L** [telegramdesktop/tdesktop#5906]
### Steps to reproduce
1. open chat with long enough history
2. scroll
3. don't click, just scroll (two fingers in my case)

### Expected behaviour
screen stays on

### Actual behaviour
screen turns off

### Configuration
**Operating system:** Windows 10 1803 17134.648

**Version of Telegram Desktop:** 1.6.3

**Used theme**: midnight

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Younes-L** [comment]
actually it doesn't just turn off, system initiates sleep/standby procedure
it takes a moment to wake it back up

**Comment by stek29** [comment]
@Younes-L why is this Telegram issue?

**Comment by Younes-L** [comment]
@stek29 I'm no dev but it only happens on telegram. It should tell windows that it's still being actively used when doing nothing but scrolling. I mean when playing videos the screen doesn't turn off even with 0 user interaction. So something can be done here.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
