### ISSUE TITLE
Draft override by mobile clients (android)

### ISSUE THREAD

**Issue by Younes-L** [telegramdesktop/tdesktop#5908]
### Steps to reproduce
1. type some draft on tdesktop
2. have your phone disconnected from internet, or connected but in deep sleep (most importantly the mobile client shouldn't be online and actively syncing)
3. now go online on mobile

### Expected behaviour
mobile client gets latest revision of tdesktop draft

### Actual behaviour
tdesktop draft is erased or replaced by older revision of draft

### Configuration
**Operating system:** Windows10

**Version of Telegram Desktop:** 1.6.3

**Used theme**: midnight

*Notes :* 
*mobile client has no issue syncing with latest draft when edited from tdesktop
*multiple issues like this were closed without problem being solved, some as old as 2016 (#2371)

**Comment by Younes-L** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3981#issuecomment-336320466
Also do you really think "undo" is a solution ? more like a wonky workaround. Not always reliable when multiple edits are made
What if i want the newer draft on my phone ? do i need to go back to laptop and hit undo a bunch of times ?
tdesktop shouldn't lose draft, simple as that.

Keep draft, and use it to update mobile client (or tell telegram servers to do their jobs correctly)

**Comment by stek29** [comment]
@Younes-L what if I want the opposite? What if I want to type something on Phone and continue on Desktop?

**Comment by Younes-L** [comment]
@stek29 that already works, afaik
It shouldn't matter where you type something, what matters is how old the draft is.

**Comment by stek29** [comment]
@Younes-L 
- You start typing
- Phone syncs draft to server
- You type more
- Phone is unable to sync draft (because of network issue, or something else)
- Desktop syncs the draft from server
- You type more on desktop
- Which sync should happen now? Phone or Desktop?

**Comment by Younes-L** [comment]
@stek29 always the newest.
It may be incomplete but at least nothing you type will be overwritten or deleted. If you notice your draft is incomplete on desktop, try to wake your phone. Otherwise it will become the most recent draft, and overwrite what's on the phone. But that would be a working as intended scenario. Always the latest draft is kept.

**Comment by stek29** [comment]
@Younes-L and who decides what's latest and what's not? Is client side time used, or is it server side time? What if older draft syncs with delay and looks like newest on server side? What if client side time is off by a minute and older drafts from it are considered newer?

**Comment by Younes-L** [comment]
@stek29 

Right now, the way draft sync is handled does not make sense and is not consistent. What happens to draft should not depend on what client is being used.

Either make it the same on all clients, or preferably, change it so it follows the common logic of revisions. Let's not ignore the existence of GIT and VCS, but really the ideal solution would be to handle conflicting changes correctly.

Or improve pending messages, so that 2 conflicting drafts can be kept in "outbox" waiting to be sent (not a groundbreaking feature or anything, just regular messages with the timer logo or upload arrow). Right now it's not very useful to send something without internet connection. Can't pause, delay or edit the message being sent. 

I have used tdesktop 3 times. And already encountered this problem.
What if client time is off ? Very unlikely.
By a minute ? Super unlikely.

Even if client device doesn't have automatic time sync through internet, telegram already relies on internal time. When Daylight Saving Time kicks in, sometimes my phone switch to new time before telegram servers. Messages will then show up with 1h difference, even when I'm connected (i.e, if it's 19:00 and I send or receive a message, message timestamp is immediately 18:00 or 20:00. The time is wrong but everything works). Clearly telegram doesn't rely on client time.


If you have some internal knowledge that explains why this feature will forever be broken and can't possibly be fixed, please do let us know. 
I'm starting to feel like I'm being trolled.

**Comment by stek29** [comment]
@Younes-L sorry, I'm not trolling you. What you're saying does make sense -- I was simply explaining why Telegram could've done it the way it is now.

Sadly, this is not really TDesktop issue, but rather issue of whole platform, so I have to close it.
