### ISSUE TITLE
tdesktop linux closes when i reply a comment

### ISSUE THREAD

**Issue by roberthchan** [telegramdesktop/tdesktop#591]
When i use tdesktop 0.7.23 in KDE 4.14.6 i want to do a reply to other member and i do clic any comment left clic -> reply: and when i input first the accent button and immediately another word tdesktop closes unexpectedly.

**Comment by roberthchan** [comment]
Bug fixed thanks to the team Great TDesktop v 0.9.10 stable 04.11.15 Works in KDE 4.19.4 openSUSE 13.2

**Comment by telegramdesktop** [comment]
@roberthchan Thanks for your feedback! I'm glad it is resolved at last.
