### ISSUE TITLE
Little visual bug with gif thumbnails

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#5910]
### Steps to reproduce
1. Save any gif to your telegram by clicking "save gif"
2. Save that gif as file too by clicking "save as file" on desktop with name 1.mp4
3. Delete 1.mp4 from desktop
4. Create any other video or gif on desktop with 1.mp4 name
5. Now open your gifs in telegram - saved gif will have thumbnail of the replaced gif/video
6. But when you post this gif - it's will be the same gif as you save, it's only visual bug with thumbnails

Only telegram restart helps.

### Configuration
**Operating system:**
Windows 10 LTSB 1607

**Version of Telegram Desktop:**
1.6.5 beta

**Used theme**:
Default

![image](https://user-images.githubusercontent.com/39812401/55850733-438edb80-5b5e-11e9-841b-27bc40746cd9.png)
![image](https://user-images.githubusercontent.com/39812401/55850738-48538f80-5b5e-11e9-9744-8a18cd4d0f61.png)

**Comment by Neurotoxin001** [comment]
Still not fixed btw.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Neurotoxin001** [comment]
Yes. 1.9.8

**Comment by Neurotoxin001** [comment]
1.9.14 not fixed

**Comment by john-preston** [comment]
I stream from disk if they're saved, because it is faster. Maybe file size / modification time can be tracked to prevent such problems, but I don't consider this a serious bug - why would you replace them like that? ¯\_(ツ)_/¯

**Comment by Neurotoxin001** [comment]
Idk... Just noticed that accidentally and decided to report it here

**Comment by john-preston** [comment]
Thanks!

**Comment by Neurotoxin001** [comment]
I thought this https://github.com/telegramdesktop/tdesktop/commit/ccbbf6f5f3e4d4311c34dda1936023621b826205 will fix it in 2.1.8 beta, but nah :(

0. close the GIF's panel
1. get any 2 GIF's
2. place them to desktop and name 1.mp4 and 2.mp4
3. post them by 1 in telegram
4. swap names - 2.mp4 become 1.mp4 and 1.mp4 become 2.mp4
now they swapped in telegram too:
https://i.imgur.com/gQ47Z7R.mp4

and if you delete them from desktop - in telegram they will freezed:
https://i.imgur.com/q2kVORV.mp4

**Comment by Neurotoxin001** [comment]
+

**Comment by Neurotoxin001** [comment]
+

**Comment by Neurotoxin001** [comment]
`+`

**Comment by Neurotoxin001** [comment]
Bug is still here
