### ISSUE TITLE
Telegram window no shown at start or restore

### ISSUE THREAD

**Issue by serrnovik** [telegramdesktop/tdesktop#5912]
Telegram doesn't show window or tray.
This was happening from time to time (was for some time flanky behavior, reboot was helping). Now it is persistent behavior, even  after clean install.
Each program start creates zombie looking process in task manager. 
### Steps to reproduce
1.1. Start telegram normally
...
2.1. Reboot pc
2.2. Start telegram normally
...
4.1. Uninstall then Install clean version (latest stable as of the moment 1.6.3 -1006003
3.2. Start telegram normally

### Expected behaviour
Tray icon shown
Main window shown

### Actual behaviour
No window or tray shown. There is process in task manager. If I try rerunning telegram it creates another zombie looking process. If I start telegram 10 times there will be 10 zombie processes.

Using withdebug doesn't give any useful information in logs. Dumps are empty

### Configuration
**Operating system:**
Windows 10 
10.0.17134
[log_start2.txt](https://github.com/telegramdesktop/tdesktop/files/3063209/log_start2.txt)
[log_start1.txt](https://github.com/telegramdesktop/tdesktop/files/3063210/log_start1.txt)

**Version of Telegram Desktop:**
1.6.3 
1006003
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by bernicewygo** [comment]
Exact same issue here. PC updated to Windows 10.0.17134 last night and Telegram no longer opens.

**Comment by john-preston** [comment]
@bernicewygo At my machine Windows 10 has version 1809, OS build 17763.437 and tdesktop works there. Can you try updating the system?

**Comment by bernicewygo** [comment]
Updated to 1803 (up to date for my pc), and issue still persists

**Comment by bernicewygo** [comment]
Running telegram in Windows 8 Compatibility mode seems to work for now.

**Comment by serrnovik** [comment]
Last night update had no notable effect on telegram whatsoever. 
Running telegram in Windows 8 Compatibility mode in fact seems to help as temporary solution. 
The problem seems to be inconsistent from one pc to another. I have it only on one machine out of three (same os version, same account, same telegram version etc)

**Comment by OuterSilent** [comment]
Same problem here (W10 ver 1809, build 17763.475).
I'm running it with W8 compatibility mode.
Anybody have news?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4787 ?
