### ISSUE TITLE
[Ubuntu, Gnome] Change the message counter's color in Launcher Bar

### ISSUE THREAD

**Issue by alebedev87** [telegramdesktop/tdesktop#5913]
### Steps to reproduce
1. Use Ubuntu >= 18.04 with Gnome Desktop Environment >= 3.28.2
2. Have some muted channels and some other contacts or not muted channels
3. Have some messages received (and not read) in the muted channels without any other not muted channel or contact
4. See the message counter color to be red

### Expected behaviour
Minimally: I would like to see the same behavior as the message counter in the system tray, when it remains grey when there are only messages from the muted channels and becomes red when there are some messages from the other not muted channels or contacts.

Ideally: I would like to see 2 different counters of the grey and red colors for all the not read messages coming from the muted and not muted channels accordingly. I would expect the same for the system tray counters too.

### Actual behaviour
The message counter in Launcher Bar always remains red regardless of the type of the channels the messages were received from: muted or not.

### Configuration
**Operating system:**
Ubuntu 18.04.2, Gnome 3.82.2
**Version of Telegram Desktop:**
1.6.3
**Used theme**:
Don't really know what it is, the default, I guess.

### Screenshot
![LauncherBarMessageCounterRed](https://user-images.githubusercontent.com/18031474/55879844-d13eeb00-5b9f-11e9-8cd9-9648b8c9799b.png)

**Comment by john-preston** [comment]
@alebedev87 I'm not sure this is possible to customize.

**Comment by alebedev87** [comment]
@john-preston : you mean it's a technical limitation of Gnome's launcher bar?

**Comment by john-preston** [comment]
@alebedev87 May be. I don't know really, but I have a dbus command to set a string there (or a number?), I don't know if there is a way to specify color somehow. Does any other app do that?

**Comment by Johnnynator** [comment]
There is no way for a program to specify the color of the counter. You might change the color in the desktop theme but nothing that can be done from Telegram's side.

**Comment by alebedev87** [comment]
If I made the right guess, this is the part of the code which sets the counter for the launcher icon: [main_window_linux](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/linux/main_window_linux.cpp#L348) 

And I suppose that this DBus API is targeted by the code: [Launcher DBus API](https://wiki.ubuntu.com/Unity/LauncherAPI#Low_level_DBus_API:_com.canonical.Unity.LauncherEntry)

So, indeed, I don't see any property for the color scheme of the counter. :disappointed:

**Comment by john-preston** [comment]
@alebedev87 I can suggest only exclude muted chats from the badge counter in Settings. This way you'll have a red badge if there are some unread non-muted messages, or no badge at all.

**Comment by alebedev87** [comment]
@john-preston Sounds as a nice setting to me. Do you think it can be applied to the system tray's counter too?

**Comment by john-preston** [comment]
@alebedev87 It is applied to it as well.
