### ISSUE TITLE
[Search] Unable to search Chinese Character 

### ISSUE THREAD

**Issue by offthegrid-mike** [telegramdesktop/tdesktop#5916]
### Steps to reproduce
1. Click Search Icon
2. Search with keywords(not a complete sentence)
3. Result not found

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Mac OSx 10.13
**Version of Telegram Desktop:**
5.1.1 (167004) Beta

**Used theme**:
default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

I am a Chinese user, and I’ve discovered that there is no way for me to search Chinese characters until I typed the EXACT phrases with the phrase contains SPACE/punctuation before/after. However, in Chinese, there is not necessary to have space in each word(unlike English). Here is the example(Refer to the zip attachment, with a snapshot video)

The phrase: 請重新搜尋
which I can’t search by the word 搜尋, until I typed the whole phrase and which is nearly impossible in real life search cause some sentences are really long

[chinese search bug.zip](https://github.com/telegramdesktop/tdesktop/files/3066259/chinese.search.bug.zip)

**Comment by stek29** [comment]
[duplicate](https://github.com/telegramdesktop/tdesktop/issues?q=is%3Aissue+chinese+search)

**Comment by theglance** [comment]
Same on Windows10

**Comment by stek29** [comment]
@theglance and any other platform -- search is server side. Please, have a look at issues I've linked.
