### ISSUE TITLE
Restoring/undeleted removed messages

### ISSUE THREAD

**Issue by kenorb** [telegramdesktop/tdesktop#5918]
### Steps to reproduce

1. Remove individual or all messages of the user.
2. Go to _Recent actions_.

Currently, there is no option to restore removed messages. This is especially trouble, when admin click the option to remove all the message of another user (such as admin), either by mistake, or deliberately. This creates a huge damage.

### Expected behaviour

I'd like to have the ability to restore removed messages.

### Actual behaviour

The current damage by removal all the messages, cannot be restored.

### Configuration

**Operating system:**: Ubuntu

**Version of Telegram Desktop:** v1.6.3

**Used theme**: Dark

**Comment by RememberTheAir** [comment]
The API doesn't let you restore messages, so tdesktop can't do nothing about it

**Comment by kenorb** [comment]
> The API doesn't let you restore messages, so tdesktop can't do nothing about it

Where this feature can be requested for API?

**Comment by RememberTheAir** [comment]
[On Twitter](https:/twitter.com/telegram) or the in-app support
