### ISSUE TITLE
Disabled notifications do not affect incoming call popup

### ISSUE THREAD

**Issue by qwelias** [telegramdesktop/tdesktop#5919]
Disabled notifications do not affect incoming call popup

### Steps to reproduce
1. Disable notification via system tray icon
2. Get incoming call
3. Call popup appears over everything

### Expected behaviour
No call popup

### Actual behaviour
Call popup appears over everything

### Configuration
**Operating system:**
Win10x64
**Version of Telegram Desktop:**
1.6.3

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3382
