### ISSUE TITLE
Send uncompressed photos by default or option to turn off compression

### ISSUE THREAD

**Issue by yivo** [telegramdesktop/tdesktop#5921]
### Steps to reproduce

Send photo.

### Expected behaviour

There is ability to turn off compression of photos.

### Actual behaviour

Photos are always compressed and there are no way to turn this off. The only way to send uncompressed photo is to send as file.

### Configuration
**Operating system:** MacOS, iOS

**Version of Telegram Desktop:** 5.0.1

**Used theme**: Day

**Comment by RememberTheAir** [comment]
You are using the MacOS native client, not Telegram Desktop

**Comment by stek29** [comment]
This is not TDesktop but a different app -- from https://macos.telegram.org.
You can get TDesktop at https://desktop.telegram.org.
(There are two apps in Mac App Store as well).

You can report issues in the app you're using at https://t.me/macswift, or at https://github.com/overtake/TelegramSwift.
