### ISSUE TITLE
sending external link doesn't work correctly

### ISSUE THREAD

**Issue by ehsandaramir** [telegramdesktop/tdesktop#5924]
### Steps to reproduce
1. paste external link to message box
2. click send before the link preview is fetched
3. message is not sent (shows waiting state. if terminate and reopen the whole message is disappeared)

### Expected behaviour
send message with a link preview

### Actual behaviour
message stuck at sending state

### Configuration
**Operating system: Ubuntu 18.04**

**Version of Telegram Desktop: 1.2.17**

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by 23rd** [comment]
Hmm, you have a fairly old version of Telegram.

**Comment by mehti1367** [comment]
Same here, i thought it would just happens to me.

**Comment by SmartManoj** [comment]
> Same here, i thought it would just happens to me. (it happens randomly not to all url messages)

Your Version of Telegram Desktop?

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
