### ISSUE TITLE
attached link to text does not copy from clipboard to telegram after 1.6.6.

### ISSUE THREAD

**Issue by Aphotice** [telegramdesktop/tdesktop#5925]
### Steps to reproduce
1. attach/embed a link on text in 1.6.6
2. copy it to clipboard
3. paste it back in telegram
 now in 1.6.6 if you delete the link infront the embedded will also be deleted/not understood.

### Expected behavior
for example, if i paste my channel's link from clipboard that already had link embedded in it in the 1.6.5 version & delete the link it infront of it would still preserve the embedded link inside Photic Zone as u can see in the screenshot

### Configuration
win10 1803

**Version of Telegram Desktop:**
1.6.6

Notes:
![image](https://user-images.githubusercontent.com/30921064/56079642-87a70800-5e0c-11e9-90f5-b4f1b4924db3.png)

no longer preserves/understand
the channel tag 
when you paste it from windows clipboard

for example, if i paste my channel's link from clipboard that already had link embedded in it in the 1.6.5 version & delete the link it infront of it would still preserve the embedded link inside Photic Zone as u can see in the screenshot

 but now in 1.6.6 if you delete the link infront the embedded will also be deleted/not understood.

i dont know how to make sense in text explaining here.
an expert will know what i am talking about .

example:

🏹Let the Hunt Begin🗡
 Photic Zone

if i directly press CTRL+K and embed/attach a link on a text here right now it will work

but if i copy it from clipboard to telegram, it will get lost.

i used this to quickly copy the footer for my channel posts but now it dsnt work as before.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
