### ISSUE TITLE
Telegram 1.6.7 triggers high consuming discrete GPU on MacBook Pro

### ISSUE THREAD

**Issue by cfinnberg** [telegramdesktop/tdesktop#5928]
### Steps to reproduce
1. Open Telegram on MacBook Pro Early 2013 (10.1)

### Expected behaviour
Integrated (low-consuming) GPU is used

### Actual behaviour
Discrete (high-consuming) GPU is used

### Configuration
**Operating system:**
Mac OS Mojave 10.14.4
GPUs:
Discrete: NVIDIA GeForce GT 650M, 1 Gt
Integrated: Intel HD Graphics 4000, 1536 Mt

**Version of Telegram Desktop:**
1.6.7 (in previous versions of Telegram this problem doesn't appear)

**Used theme**:
Default theme

**Comment by john-preston** [comment]
@cfinnberg This is the only way it doesn't crash all the time (when gpus get switched by some other app). This is apple bug in 10.14.4, I hope they'll fix that in 10.14.5.

**Comment by cfinnberg** [comment]
Thanks for the answer! Yes, I had also noticed the crashing. Is it planned then to switch back to the integrated GPU if apple fixes the bug?

**Comment by john-preston** [comment]
@john-preston Yes, of course. I really did search for another workaround, but nothing worked.

Here is a related Qt Creator bug report: https://bugreports.qt.io/browse/QTCREATORBUG-22215

**Comment by cfinnberg** [comment]
Thanks a lot. Nothing else than to wait that Apple fixes the bug. Closing the issue...
