### ISSUE TITLE
иногда телеграм начинает жечь CPU на 200 процентов на macOs high siera

### ISSUE THREAD

**Issue by korniltsev** [telegramdesktop/tdesktop#5930]
### Steps to reproduce
1. не знаю, возможно связано с отсутствием интернета ( в логах Host unreachable), но при восстановлении подключения к инету, все равно продолжает жечь цпу
Ниже приаттачу логи и трейсы снятые с приложеньки на живую
### Expected behaviour
В простое телеграм не жрет цпу

### Actual behaviour
Иногда телеграмчик сходит с ума и начинает жрать 50-200 процентов цпу

### Configuration
**Operating system:**
macOs high siera

**Version of Telegram Desktop:**
1.6.7 ( ранее такое же наблюдалось в 1.6.3
**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)

[log.txt](https://github.com/telegramdesktop/tdesktop/files/3077955/log.txt)
[trace1.cpu50.txt](https://github.com/telegramdesktop/tdesktop/files/3077952/trace1.cpu50.txt)
[trace2.cpu200.txt](https://github.com/telegramdesktop/tdesktop/files/3077953/trace2.cpu200.txt)
[trace3.cpu200.txt](https://github.com/telegramdesktop/tdesktop/files/3077954/trace3.cpu200.txt)

в логе последняя запись в 01:31 но жрать цпу продолжает до сих пор, щас уже 01:46, трейсы сняты в 01:40

![Снимок экрана 2019-04-15 в 0 15 14](https://user-images.githubusercontent.com/331773/56100368-7fd88800-5f20-11e9-99ef-f1876b27f894.png)

</details>

**Comment by korniltsev** [comment]
вот топ горячих адресов 
```
Telegram`0x0                                              369   3.2%
Telegram`0x000000010a3664d0                               434   3.8%
Telegram`0x000000010a335f00                               766   6.7%
Telegram`0x000000010a79f4d4                               905   7.9%
Telegram`0x000000010a3414e0                               943   8.2%
Telegram`0x000000010a79f593                              2082  18.1%
Telegram`0x000000010a7217c0                              2268  19.7%
```

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5295

**Comment by tharlo** [comment]
I can't see why is this issue closed, while the described behaviour still keeps taking place. OS X High Sierra, 10.13.6, Telegram Desktop 2.5.8.
