### ISSUE TITLE
Telegram crashs on app for armrf devices

### ISSUE THREAD

**Issue by SevenGames7** [telegramdesktop/tdesktop#5931]
### Steps to reproduce
1. Open Telegram (without an account)
2. Log in with an account
3. Set night mode

### Expected behaviour
Telegram works fine

### Actual behaviour
App crashes and when opened again it's needs to login on account again (making it an loop)

### Configuration
**Operating system:**
Raspbian / Debian 9.8
**Version of Telegram Desktop:**
1.3.10/stable (last available for armrf devices on snapcraft.io - telegram.desktop by Telegram FZ-LLC)
**Used theme**:
none, only night mode provided by settings
<details><summary><b>Logs</b>:</summary>
log.txt is empty on /home/pi/snap/telegram-desktop/252/.local/share/TelegramDesktop/log.txt
</details>

**Comment by stek29** [comment]
It crashes when you enable night mode, but works fine otherwise?

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6647 ?

**Comment by SevenGames7** [comment]
> It crashes when you enable night mode, but works fine otherwise?
(On this issue date) Most of time... Sometimes it's got stuck and crashes/close on random moments for unknown reasons, but nowadays i don't use Telegram for armrf devices anymore (sorry for answer so late).

**Comment by SevenGames7** [comment]
> #6647 ?

It isn't the same, my problem was with night mode and this one is about the animated stickers... But it's another bug with old Telegram versions for linux distros c:

**Comment by ilya-fedin** [comment]
Can you get a backtrace from gdb?

**Comment by Aokromes** [comment]
no answer for over a month, closing.if this bug is still valid open a new ticket using updated version.
