### ISSUE TITLE
Downloading Problem

### ISSUE THREAD

**Issue by jahmadiiiii** [telegramdesktop/tdesktop#5932]
### Steps to reproduce
1. First you download a large files or video for example 500mb 
2. Cancel when reached to 100mb or more or even a fault like system automatic restart!
3. Then resume it

### Expected behaviour
Download must resume and when it reached to 100mb and when i cancel it then resume it must resume from last reached.

### Actual behaviour
Download not resumed and must file or video download agian.

### Configuration
**Operating system:**
Windows 10 1809 17763.253
**Version of Telegram Desktop:**
1.6.7 
but this problem happens in all version of telegram desktop even beta versions.
**Used theme**:
Default telegram theme
<details><summary><b>Logs</b>:
</summary>
Insert log.txt here (if necessary)

</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3989
