### ISSUE TITLE
Forwarding multiple msgs from a chat to another brings up channels that i cant even msg(not an admin of).

### ISSUE THREAD

**Issue by Aphotice** [telegramdesktop/tdesktop#5933]
### Steps to reproduce
1. select a few msgs from any chat
2. press the forward button on the top left window
3. try to find your 20+ friends/chats you want to forward to among 1000channels that you can't even forward to.

### Expected behavior
The list of channels that i am not an admin of, should not even be included in the forward list/share list.

### Actual behavior
it brings up a list of channels & other chats all mixed up!

this is very annoying when you want to forward "more than one msg" from personal chats that do not have the arrow/pointer share button on the right of posts(like in channels) or if u you want to forward from personal chat that has no arrow in it in the first place.

you must search your friends name one by one or memorize their names in different languages or just scroll, scroll, scroll down every time u want to forward msg to people one by one among like 1000s of channels. 

### Configuration
**Operating system:**
win10 1803

**Version of Telegram Desktop:**
 1.6.6

Notes:
![image](https://user-images.githubusercontent.com/30921064/56133197-19e01500-5fa1-11e9-8fa5-9c28ff58ac73.png)
![image](https://user-images.githubusercontent.com/30921064/56133257-354b2000-5fa1-11e9-8453-792a92ba459d.png)
help my friends trapped among channels xD

can this pleaaaaase be fixed after more than a year...?
thanks alot  :}
🍎❤️

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4348
