### ISSUE TITLE
[Feature Request] Thumbs Up or Down on comments!

### ISSUE THREAD

**Issue by Patrickdurbin** [telegramdesktop/tdesktop#5935]
Very Simple enhancement

I would be nice to have the ability to Thumbs up a comment and have the text automatically get bigger "standout"  using markdown the more thumbs up it has. maybe turn a darker shade of "good" colors green then  light blue  then blue if its a really good comment with a lot of thumbs ups. 

 If people disapprove of the comment it can turn yellow to orange to red depending upon the amount of negative thumbs on it. (this will help mods) skimming as well. If they see a post with a lot of negative thumb downs it will be easy to pick out to review.

**Comment by Nachtalb** [comment]
What kind of comments do you mean? To my knowledge, there is no such feature as "comments".

If you are talking about a channel which adds reactions to its messages -> this is done with a bot.

**Comment by MrBIMC** [comment]
There's no official api for that inside the telegram itself, so it won't be implemented until(if ever) telegram gets support for emoji-reactions like in slack and discord.
