### ISSUE TITLE
Telegram Desktop does not resolve lnk and Symbolic Link paths on windows

### ISSUE THREAD

**Issue by beppe9000** [telegramdesktop/tdesktop#5936]
### Steps to reproduce
1. Make a symbolic link to a file
2. Try to send it

### Expected behaviour
Normal file sending.

### Actual behaviour
"File cannot be empty" error.

### Configuration
**Operating system:**
Windows Server 2016

**Version of Telegram Desktop:**
1.6.7

**Comment by beppe9000** [comment]
meh

**Comment by ilya-fedin** [comment]
I assume this is intended behavior. If you want upload a file, don't choose symbolic links.

**Comment by beppe9000** [comment]
if sending links instead of the file they point to was intended behaviour this wouldn't fail
![image](https://user-images.githubusercontent.com/6625123/97169049-b33cd980-1789-11eb-9115-e286bcba7808.png)

**Comment by ilya-fedin** [comment]
You can't send symbolic links since they are a file system specific thing, this works like that in any app

**Comment by beppe9000** [comment]
and because of that links should be resolved prior to sending

**Comment by ilya-fedin** [comment]
no, they shouldn't, they should fail

**Comment by beppe9000** [comment]
if the intent of the user is to send the file represented by the link why make it fail ?

**Comment by ilya-fedin** [comment]
> what would be the point of sending the link itself ?

There's no point since they couldn't be sent

**Comment by ilya-fedin** [comment]
> if the intent of the user is to send the file represented by the link why make it fail ?

If the user want to send file, he should just send file, not the link

**Comment by beppe9000** [comment]
i think it's easier to fix this than explaining that to telegram's user base

**Comment by ilya-fedin** [comment]
Looks like no one across you aware of this

**Comment by beppe9000** [comment]
and that is the reason this is labeled as bug

**Comment by ilya-fedin** [comment]
This is labeled as bug because you used the bug template

**Comment by beppe9000** [comment]
yes, because i consider it a bug: a mismatch between user intention (send any file), default system behaviour (following links) and final result (failure)

**Comment by ilya-fedin** [comment]
I consider this intended behavior, tdesktop behaves just like any other messaging app in this case

**Comment by beppe9000** [comment]
it's crippling behaviour for power users

**Comment by beppe9000** [comment]
HNBGTNB
