### ISSUE TITLE
Make better use of horizontal screen space

### ISSUE THREAD

**Issue by beppe9000** [telegramdesktop/tdesktop#5937]
### Steps to reproduce
1. Send many different files with long name and similar names

### Expected behaviour
Full file name is shown.

### Actual behaviour

The file name is truncated instead, even tough screen space is available, making them hard to distinguish if the only difference is not at beginning of ending of the string.

### Possible Solution
The message bubble should expand to accomodate the full length of the file names, based on available horizontal space, or use multi-line mode for file names.

In every case when an ellipsis is the only possibility I think there should be some algorithm that makes sure numbers are fully shown.

### Configuration
**Operating system:**
Windows Server 2016

**Version of Telegram Desktop:**
1.6.7

**Used theme**:
default black

![image](https://user-images.githubusercontent.com/6625123/56219099-75c0a180-6066-11e9-9223-ef5b582b75e6.png)

**Comment by kirsan31** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2060 and many more before it...

**Comment by beppe9000** [comment]
Then it's a bump!

**Comment by Aokromes** [comment]
and https://github.com/telegramdesktop/tdesktop/issues/3573
