### ISSUE TITLE
[Feature Request] Show all GIFs in in the sidebar

### ISSUE THREAD

**Issue by reallywonder** [telegramdesktop/tdesktop#5938]
### Steps to reproduce
1. collect a bunch of gifs
2. the collection grows
3. now there's many of them

### Expected behaviour
All the gifs i've saved and used should be there in the side-bar if i scroll down far enough

### Actual behaviour
The older ones are "missing".

I've googled this before and people say there's an arbitrary limit of 180-200 gifs. I looked through the code files and found the code for the widget panel, and I see that there IS a hard limit of 5 gifs per row, but i don't see any hard-defined limit on the number of rows.

But if I delete 20 or so gifs and restart the app, older ones that i thought were gone and lost are loaded in, so... they're still around, there's just a limit to how many gifs or rows there can be.

### Configuration
**Operating system:**
windows 7

**Version of Telegram Desktop:**
1.6.7

**Used theme**:
default

I do see there is another ticket open about the gifs consuming large amounts of CPU % when the panel is visible, so i could understand if there's an arbitrary limit because of that, but what if there was an opt-in advanced option to show them ALL?

**Comment by john-preston** [comment]
@reallywonder This is a server side limit, it returns only limited (about 200?) amount of the latest saved GIFs. If you remove some, then it returns some older ones. Unfortunately there is nothing I can do about it.

**Comment by scarf** [comment]
having the same experience as the OP and also would like to see all my saved gifs.  using telegram desktop linux v1.7

@john-preston how is this a server-side limit when all the gifs are saved locally?

  i can see in my local storage settings that i have 322 gifs saved and it is only showing me the last ~200.  It's still way under the limits of my cache settings:
summary: 1187.6 MB; total size limit: 10 GB; media cache limit: 1 GB; clear files older than: Never; 32172 images, 528 MB; 1872 stickers, 66.8 MB; 1 video < 1MB; 322 gif animations, 366.2 MB; media cache, 225.6 MB.

**Comment by john-preston** [comment]
@scarf Those are unrelated.

Locally cached GIFs are all animations that you see anywhere - in your saved gifs tab, in chats and channels you open etc.

Saved GIFs tab content is synced between your apps and the list is saved and served to the client by the server. And it gives the client some limited amount of them.

**Comment by scarf** [comment]
I see no practical reason to limit the GIFs shown in the tab.  Please reopen.

**Comment by scarf** [comment]
If Telegram says I have more than 200 gifs saved but isn't showing them, it's a bug not a feature request.  What's the point of cache settings when you can't see your data?  Should be simple enough to load 50 more gifs when we get to the bottom of the list, then unload the first 50 gifs.  That way only 200 are displayed at any time, if that is what the problem is.  Everything else in Telegram doesn't have such limit.  Stickers get archived and can still all be seen, all media in groups/channels can be seen if you just scroll, etc.
