### ISSUE TITLE
Security codes publicly showing in contact list

### ISSUE THREAD

**Issue by kaetemi** [telegramdesktop/tdesktop#594]
When Telegram is open on the desktop, and someone, who happens to be looking at my monitor, tries to gain access to my account; the security code will pop up entirely visible on screen in top of the contact list under the Telegram contact. I am somewhat concerned about the possibility of using this to gain access to an account while the computer is being used, for example, during a projected presentation.

(Haven't checked the notification toaster's behaviour on this, but it would be equally, or even more, problematic if that popped up the code as well.)

**Comment by cobalto** [comment]
I've never ever allowed an burglar to gain physical access of my machine while logged on my bank account. Why would you do that with other things? Log out the damn thing, or just lock it with a code (it's already implemented)

Btw, That's the exact same behavior of the mobile apps, because the code is send as a message from the service account.

**Comment by kaetemi** [comment]
They don't need physical access. They just need to see your monitor if Telegram happens to be opened.

**Comment by cobalto** [comment]
I never receive the passcode of Telegram except when I ask it.
I never ever received an SURPRISE TELEGRAM PASSCODE.

**Comment by kaetemi** [comment]
Anyone just needs to stand behind me and punch in my phone number in their Telegram app. Bang, the code shows up in plain view on my monitor.

**Comment by zal-any** [comment]
Yes, it's a serious problem, when app use only one-time pass generated and doesn't use 2-FA (login/pass + one-time pass). Security problem related to small UI issue :)

+1
