### ISSUE TITLE
VS2019 project Compile Error

### ISSUE THREAD

**Issue by hehenibuxing** [telegramdesktop/tdesktop#5940]
### Steps to reproduce
1. set CHERE_INVOKING=enabled_from_arguments
2. set MSYS2_PATH_TYPE=inherit
3. bash --login ../../tdesktop/Telegram/Patches/build_ffmpeg_win.sh

### Expected behaviour
The expected result is that the bash command will  compile the .sh file sucessfully.
### Actual behaviour
There is an error in building the project with VS 2019, when other build commands are completed. Could you please give me some advice about it? Thank you.

![QQ图片20190419212317](https://user-images.githubusercontent.com/36142720/56458256-e0e7dc00-63b6-11e9-99dd-959975c491c6.png)

### Configuration
**Operating system:windows10

**Version of Telegram Desktop:xx

**Used theme**:xx

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by foodornt** [comment]
dude I had the same error, did you fix it yet?
