### ISSUE TITLE
Replace media bug with .mov extension

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#5941]
### Steps to reproduce
1. Create channel (or do it in any chat) and upload "gif" (.**mp4** without sound)
2. Click edit and replace media to any other "gif", but now instead .mp4 use .mov (without sound too), **you can even just rename .mp4 to .mov, without converting it to actually .mov**
3. Restart telegram desktop app and you will see that isn't a gif, but a real video (it's opens in full screen, but not in chat window, as gif)

### Expected behaviour
Gif/image/video must replace fine and become "gif" whatever I use - mp4 or mov file extension

### Actual behaviour
Replaced gif/image/video by file with .mov without sound is become as video, not as gif

### Configuration
**Operating system:**
Windows 10 LTSB

**Version of Telegram Desktop:**
1.6.7 beta

**Used theme**:
default

If you open testing chat on your phone (I use iOS telegram app (not telegram x)) then you will see it in real time, without needing to restart telegram desktop. File with .mov extension make post with media broken forever, you can't anymore make a "gif" in this post, if you once replaced it with .mov file.

I tested it only with .mov, but I think it may bug with other video file types.

Если по-русски и коротко, то:
1. Заливаем гифку (mp4 без звука) в чат
2. Изменяем её на эту же гифку, но уже с расширением .mov
3. Гифка превращается в видео и в этом посте больше нельзя сделать гифку, даже если залить обратно тот самый первый mp4 без звука

**Comment by john-preston** [comment]
@Neurotoxin001 I guess server doesn't think .mov is a ".mp4 without sound gif animation".

**Comment by Neurotoxin001** [comment]
> @Neurotoxin001 I guess server doesn't think .mov is a ".mp4 without sound gif animation".
So you can't do nothing or you can send this info to server developers?

**Comment by Neurotoxin001** [comment]
I found another way to get this bug:
1. Upload mp4 w/o sound
2. Replace with mp4 with sound
3. Replace with mp4 w/o sound
Now post with this media can't be GIF anymore. It's always will be video (you must restard TDesktop app to see that  GIF become video)
