### ISSUE TITLE
telegram settings - reset after restart or update version

### ISSUE THREAD

**Issue by pavo976** [telegramdesktop/tdesktop#5944]
### Configuration
**Operating system:** ubuntu:18.04

**Version of Telegram Desktop:** 1.6.7

After update telegram version, or dropdown to aks auth code (why it's happens?) app lost settings:
- automatic media download (private chats, groups, channels)
    - also: limit by size (private chats, groups, channels)
- performance
    - enable animation (set: disable)
    - autoplay GIFs (set: disable)

Sometimes lost "proxy settings".

**Comment by simone-omniaweb** [comment]
The same here, Telegram 1.7.14 on Windows 10 Pro. Disabling the "Tile background" option allows the settings to be retained. Enabling it, reset all options to default at each restart. Since at least september 2016

https://github.com/telegramdesktop/tdesktop/issues/2431#issuecomment-247312398

**Comment by nikkou** [comment]
Since my similar issue was closed, I'll rewrite it here:
Every time my laptop goes into hibernation due to low power the proxy list is wiped and chat background is reset to default.

What I tried:
- disabling "Tile background" mode
- reinstalling Telegram

It did not help.

**Comment by alexey-milovidov** [comment]
Still relevant for me.

**Comment by slavik-m** [comment]
Still relevant +

**Comment by Frederick888** [comment]
'Tile background' still resets.

**Comment by Dragonisser** [comment]
> 'Tile background' still resets.

Yep been happening since forever.

System: Windows Enterprise 20H2
Telegram: 3.0.1

**Comment by m0h318** [comment]
yes, chat settings reset for me too

OS: Windows 10 Pro
Telegram: 3.0.1

**Comment by trilean** [comment]
Same here, Telegram 3.1.11 on Ubuntu 20.04 via Snap. This is already the second time this happened to me. The first time I thought it was me who made a mistake. This time I certainly didn't do anything that could have thrown off Telegram.

**Comment by woomiez** [comment]
been happening for years.. how hard can it be to save the state of a checkbox option..

**Comment by Dragonisser** [comment]
The issue is still present as of today version 3.7.3. When does this finally get fixed...

**Comment by woomiez** [comment]
Still ocurring with current 4.2.4 Windows

**Comment by john-preston** [comment]
Please check by updating 4.5.1 to 4.5.2.
