### ISSUE TITLE
[Feature Request] Telegram in "Terminal Mode"

### ISSUE THREAD

**Issue by barriteau** [telegramdesktop/tdesktop#5949]
I know most people loves emojis, stickers and gifs, so I'm pretty sure this isn't going to be a popular request, but I have to try :)

In my head, Telegram in "Terminal Mode" means:

1. Disable and hide all sending emojis options.
2. Disable and hide all sending gifs options.
3. Disable and hide all sending stickers options.
4. Convert received emojis to their equivalent emoticon.
5. Convert received gifs to their equivalent emoticon.
6. Convert received stickers to their equivalent emoticon.
7. Show received URIs as simple links, no preview.
8. Show received photos as links, no preview.
9. Show a simple play button for received videos, no preview.

I can imagine several ways to implement this in the UI: 

A. The simplest way, a single "Terminal Mode" switch bellow the "Night Mode" switch to globally enable/disable, at once, all of the 9 options above.

Or

B. A single "Terminal Mode" switch in "Chat Settings" to enable/disable, at once, all of the 9 options above per chat.

Or

C. Adding a section in "General Settings" with 9 switches to globally enable/disable independently every one of the 9 options; and, a single "Terminal Mode" switch bellow the "Night Mode" switch to globally enable/disable whatever was configured in "General Settings".

Or

D. Adding a section in "General Settings" with 9 switches to globally enable/disable independently every one of the 9 options; and, a single "Terminal Mode" switch in "Chat Settings" to enable/disable whatever was configured in "General Settings" per chat.

Or

E. Adding a section in "Chat Settings" with 9 switches to directly, independently, specifically and granularly, enable/disable every one of the 9 options per chat.

Or

F. Any weird combination between A, B, C, D and E.

Why?

Because cleaner chats would be appreciated by some people.

Because this could make our chats a little SFW.

Because some guys are able to send 32000 stickers in one second.

Because a emojistickergifapocalypse has been predicted in the scriptures and we need to be prepared.

**Comment by john-preston** [comment]
@barriteau TBH this looks like a feature request for a fork.

**Comment by axdiamond** [comment]
I imagine youd be able to develop your own terminal-only Telegram client using the [api](https://core.telegram.org/api) or the [DB Lib](https://core.telegram.org/tdlib)

**Comment by barriteau** [comment]
Hum... It seems I wasn't clear enough, my bad, sorry. The proposed feature isn't the creation of a new telegram-cli, this already exist, and as far as I know, it still works fine (https://github.com/vysheng/tg).

I'm proposing a "Terminal Mode" for Telegram Desktop to be activated and deactivated at will, for all active chats at the same time or for specific chats.

This proposal isn't about getting rid forever of all emojis/stickers/gifs, it's about making them optional, so I don't see it like a fork or a different client.

Maybe calling this a "Terminal Mode" was wrong, sure there are better ways to name it, but I insist, it's not about removing all of the mentioned features, I don't want a client without stickers, I just want to be able to deactivate them temporarily.

**Comment by JochemKuijpers** [comment]
You can already revoke the permission to send GIFs, stickers and media in (super) group chats. If you're not a fan of stickers (or any kind of spam for that matter), just let your conversation partners know. 

Simply hiding these things for you personally will lead to miscommunication for sure. Someone might make a sarcastic remark, send a sticker to clarify it's a joke, and you'll completely miss it, for instance.

**Comment by barriteau** [comment]
It's weird how all of you assumed I'm a stickers-hater, a terminal freak or something like that :)

Things are simpler:

- Dark mode / light mode -> your choice.
- Full screen / small window -> your choice.
- Show last seen / hide last seen -> your choice.
- Small text / big text -> your choice.
- Notifications on / notifications off -> your choice.
- ...
- Options to send emojis-stickers-gifs -> always there, no choice.
- Receiving emojis-stickers-gifs -> always there, no choice.

I'm just saying those features can be optional, as many others are, I'm just saying it's nothing bad if we, users, can switch them on and off.

I think that calling this a _terminal mode_ was a mistake, maybe this confuses everything, my bad.

But trust me, I'm not a stickers-hater (I use them, a lot), I'm not a terminal freak (I do prefer clicking on buttons and anchors), I don't want gifs to be banned, I don't want anything to be revoked, it's just about making optional a group of options that aren't.

I understand, most of you can't conceive a situation in which a human being wouldn't want to send or receive stickers, but it hurts nobody making optional a couple of features.

**Comment by vit1-irk** [comment]
Vote up for this, all these things are very good suggestions

**Comment by SmartManoj** [comment]
Is it a duplicate #5292
