### ISSUE TITLE
[Feature Request] Play next voice message

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#595]
I suggest to add **Play next voice message** option in similar to Viber client which plays next voice messages automatically.

**Comment by brunobsouzac** [comment]
+1 voice messages with automatic play are already on iOS but not for WP, Android, Web and Desktop. It would be easier to listen to voice messages and receive them in real time as Voxer / Zello and Radio.

**Comment by chevi** [comment]
+1
Maybe add "Play all" option for unread audio messages

**Comment by diazbastian** [comment]
Auto playback voice messages was added some time in the mobile versions, so this improvement would be in keeping with current features of Telegram.

**Comment by Aokromes** [comment]
already implemented no? @stek29
