### ISSUE TITLE
Icon should not change when content is posted to channel for which notifications are disabled

### ISSUE THREAD

**Issue by nicolas-raoul** [telegramdesktop/tdesktop#5952]
### Steps to reproduce
1. From Android app, register to a very frequently updated channel (let's call it "NoisyChannel")
2. From Android app, disable notifications
3. Install Telegram Desktop on Ubuntu 19.04
4. Wait for NoisyChannel to post something

### Expected behaviour
Telegram Desktop does not show anything.
That's what happens on the Android app

### Actual behaviour
Telegram Desktop actually updates the app icon to make it look like if some important message had arrived.
Very annoying because it looks like someone is actually trying to contact me.

### Configuration
**Operating system:** Ubuntu 19.04

**Version of Telegram Desktop:** 1.5.11

**Used theme**: Default, night mode

Screenshot taken with 0 new messages in non-muted channels, 11 messages in muted NoisyChannel:
![Screenshot from 2019-04-23 12-22-01](https://user-images.githubusercontent.com/99590/56551133-7905e100-65c2-11e9-9469-0f978c0e7d37.png)

![screenshot](https://user-images.githubusercontent.com/99590/56551019-33491880-65c2-11e9-97b9-594a4c25cf25.png)
As you can see, notifications are not enabled.

**Comment by john-preston** [comment]
@nicolas-raoul In Settings there is a checkbox Include muted chats in the badge.

**Comment by nicolas-raoul** [comment]
Wonderful! Sorry I did not find that.
