### ISSUE TITLE
On the snap package graphic accents do not appear

### ISSUE THREAD

**Issue by DiogoConstantino** [telegramdesktop/tdesktop#5954]
### Steps to reproduce
1. type a vocal with an accent like:
áàãâ

### Expected behaviour
Telegram should display:
áàãâ

### Actual behaviour
Telegram displays:
aaaa

### Configuration
Snap package
Name                 Version             Publisher         Notes    Summary
telegram-desktop     1.6.7               telegram.desktop  -        Official desktop client for the Telegram messenger

**Comment by tcarrondo** [comment]
Same here

**Comment by 00tiagopolicarpo00** [comment]
same problem.

**Comment by stek29** [comment]
#5545
