### ISSUE TITLE
I can't see my files when trying to add an attachment

### ISSUE THREAD

**Issue by str** [telegramdesktop/tdesktop#5955]
### Steps to reproduce
1. Install telegram-desktop as snap
2.  Click on the "add attach" icon to include a file to the chat
3. Try to browse "recent",  "home", or "tmp" files. No file nor folder will be shown

### Expected behaviour
I should be able to see my recent files, my home folder, or the tmp files.

### Actual behaviour
No file nor folder is shown.

### Configuration
**Operating system:** GNU/Linux, Ubuntu 19.04

**Version of Telegram Desktop:** 1.6.7

**Used theme**: night

![image](https://user-images.githubusercontent.com/123817/56658061-dea3ad00-6656-11e9-9d95-7c4d938d79ab.png)

**Comment by stek29** [comment]
Where have you got TDesktop from?

**Comment by str** [comment]
snap telegram-desktop     1.6.7

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5778#issuecomment-472353541
