### ISSUE TITLE
[Windows 10] When Telegram is set to open on boot to the system tray, it refuses to leave the foreground when clicking on another program or even when trying to open an image

### ISSUE THREAD

**Issue by Reonu** [telegramdesktop/tdesktop#5956]
### Steps to reproduce
1.  Enable the option to open Telegram on boot to the system tray.
2. Boot your computer
3. Open Telegram after it starts in the system tray.
4. Click on a background window of another app OR click an image in a Telegram chat

### Expected behaviour
The main telegram window should leave the foreground and the program or image you clicked should be in the foreground instead
### Actual behaviour
Telegram refuses to leave the foreground unless you manually click the minimise button, until you close and re-start the program.
### Configuration
**Operating system:**
Windows 10 1809
**Version of Telegram Desktop:**
1.6.7
**Used theme**:
Default, night mode.
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3253
