### ISSUE TITLE
smile hotkey issues

### ISSUE THREAD

**Issue by gompa** [telegramdesktop/tdesktop#5957]
### Steps to reproduce
1.  type :p
2.  type space behind it 
3.  and it suggests to change to  🅿️
4. press enter to send and smile changes to  🅿️

### Expected behaviour
Tell us what should happen
dont change to emoji if its not the emoji intended
use arrow key to select smile and press enter to change it
if no smile selected dont change on enter
### Actual behaviour
Tell us what happens instead
:P changes to  🅿️

### Configuration
**Operating system:**
linux debian
**Version of Telegram Desktop:**
1.6.7
**Used theme**:
default
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
workarround: use 2 spaces.
