### ISSUE TITLE
Question about emoji sets

### ISSUE THREAD

**Issue by mbasaglia** [telegramdesktop/tdesktop#5958]
This is a question more than an issue.

You can download a couple emoji sets, I've noticed they are stored as a few sprite sheet images.
The order of the emoji in those images seems the same as in the emoji selector.

I was wondering if there's any documentation on which emoji (and in what order) are in those images, it seems slightly different from the order in the emoji standard.

I'm asking this because I'm working on a custom emoji set and I'd like to use it on Telegram.

**Comment by mbasaglia** [comment]
The question hasn't been answered

**Comment by mbasaglia** [comment]
bump

**Comment by mbasaglia** [comment]
.

**Comment by john-preston** [comment]
@mbasaglia The order is the same it is in the iOS. The lists are generated from this data:

https://github.com/desktop-app/lib_ui/blob/master/emoji.txt

The codegen utility source code (which reads this file and prepares all the sprites and data about them inside the app) is here:

https://github.com/desktop-app/codegen/tree/master/codegen/emoji
