### ISSUE TITLE
Escaped URL sent in mobile shows up unescaped in web

### ISSUE THREAD

**Issue by saranya-vatti** [telegramdesktop/tdesktop#5959]
### Steps to reproduce

1. In the mobile chat client, go to any URL on website.
I tried https://www.linkedin.com/jobs/search/?f_C=3858&keywords=software&location=United%20States&locationId=us%3A0
2. Copy this and paste this in the Telegram app
3. Open the telegram web (https://web.telegram.org/)
4. Check the URL pasted. It's decoded!

When apps (linkedin app) tries to open this decoded URL, there might be issues. This does not happen for other chat clients. Why does Telegram decode it? If it is so that the URL is clear to read, then can you do it so that the URL shows up decoded but onclick, actually send an encoded URL as expected?

### Expected behavior
The URL on web should be same as the one passed through mobile app.

### Actual behaviour
The URL on web is decoded whereas the url sent on mobile is encoded.

### Configuration
**Operating system:** Mobile: Google Pixel 3 XL, Android 9

**Version of Telegram Desktop:** Version 0.7.0

**Used theme**: N/A

**Comment by stek29** [comment]
That's not telegram desktop.
