### ISSUE TITLE
Telegram not responding on Mac when uploading file

### ISSUE THREAD

**Issue by valeryAliev** [telegramdesktop/tdesktop#5961]
### Steps to reproduce
1. Click on attach file icon in any dialog
2. Click "file"
3. Wait until window with file list opened
4. Then instead of double click on file to attach, drag and drop file from opened window, like you are trying to attach file by Drag'n'Drop
5. Telegram stop responding to any actions or crash

### Expected behaviour
File should be attached

### Actual behaviour
Telegram stop responding

**Comment by Aokromes** [comment]
this bug is sill valid on 1.9.9?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
