### ISSUE TITLE
Redesign link prewiew

### ISSUE THREAD

**Issue by gagarine** [telegramdesktop/tdesktop#5962]
In a conversation link preview take to much attention and to much space.  Preview are also problematic when more than one link is posted as only one link get a preview. Link preview should be redesigned on mobile and desktop.

Taking a smaller typographic and less contrasted color for the preview's text can be a good start.

Instant view button should not be below the preview but bellow the link, so when you have more than one links it still works.

Also perhaps a way to disable link preview like it was proposed in #687  or a way to delete a preview after a message was posted.

**Comment by john-preston** [comment]
@gagarine You can edit the message and remove the preview when editing.

**Comment by gagarine** [comment]
@john-preston but this is not very practical. For this part, it would be nice to have an action "remove preview"/"add preview" so you don't have to click "edit" and then click to remove or add the preview. Having a way to add preview quickly would also be nice if you disable preview all together but want preview for a particular link.
