### ISSUE TITLE
![image](https://user-images.githubusercontent.com/20015479/56834587-0da06580-6887-11e9-9d01-8c5746df2fcc.png)

### ISSUE THREAD

**Issue by f4h4m** [telegramdesktop/tdesktop#5964]
![image](https://user-images.githubusercontent.com/20015479/56834587-0da06580-6887-11e9-9d01-8c5746df2fcc.png)
Still Annoying in Ubuntu 19.04 ( i got this from ubuntu software)

_Originally posted by @f4h4m in https://github.com/telegramdesktop/tdesktop/issues/5172#issuecomment-487190545_

![image](https://user-images.githubusercontent.com/20015479/56834935-15143e80-6888-11e9-8268-34773f022baf.png)
Ok , just fixed by installing again :smile:

**Comment by soroush** [comment]
Did the same,  though it didn't change. It's a bit strange how re-installing will fix it? Maybe you need to re-open the issue.
