### ISSUE TITLE
Streaming media are not downloaded

### ISSUE THREAD

**Issue by halaei** [telegramdesktop/tdesktop#5965]
Recently, the streaming audio & video files don't get downloaded. So after streaming, if you want to download the file, the whole file transfer re-occur. Previously, the behavior was like android version, streaming == downloading. Not anymore.

**Comment by john-preston** [comment]
@halaei Previously there was no streaming at all, you could only download the file and then play it.

**Comment by halaei** [comment]
Oh, then I think I made a mistake. But still this is an issue, right?

**Comment by MasterGroosha** [comment]
@john-preston I think the issue is that streaming for the first time should also download the video to save traffic with future views.

**Comment by john-preston** [comment]
@MasterGroosha It downloads it to the encrypted cache, like photos etc, so the next views should work fast as long as the cache is not getting to the size limit, then the old parts will be removed.

**Comment by MasterGroosha** [comment]
@john-preston Do you mean that viewing mediafile without explicitly downloading it (by clicking on error) still downloads the media, but to some cache and not "Downloads" folder? 
Then what's the use of it? For example, when I view 500mb video and then I want to save it on my PC, I have to download these 500 mb again? Even though I've viewed it once and it was cached somewhere?

**Comment by john-preston** [comment]
@MasterGroosha Yes, parts of file (that were used in streaming) are saved in the media cache. Right now the cache and downloading are completely independent :( but in one of the future versions they'll work well with each other, so you won't download twice the same file parts. Not the nearest update, but I hope to do that soon.

**Comment by Lonami** [comment]
Would it be much work to have a workaround such as a checkbox in the setting:
* [x] Stream media

Which if, unchecked, first downloads and then plays? Pretty much old behaviour.
