### ISSUE TITLE
Most media fail to load

### ISSUE THREAD

**Issue by Zelgadis87** [telegramdesktop/tdesktop#5966]
Hi all,

I have some problems with media files, using the latest version of Telegram desktop. Basically it seems like 90% of the files are not getting downloaded, and show up as loading spinners forever. This affects profile photos, stickers, media downloads, etc. Some of the files work instantly instead, but are the minority. Uploads are perfectly fine.

Stopped working around a week ago or so, previously was working completely fine. I have tried uninstalling and reinstalling, with no improvement. Also tried changing download folder, from a custom one to the default, but still no improvement. On the new install, it is completely empty.

Telegram Web on the same computer, and Telegram for Android on the same network work perfectly fine.

Seems like a storage issue, but all I can change is the download folder, which doesn't seem to affect the outcome in any way.

### Steps to reproduce
1. Open Telegram
2. Open a chat with a contact

### Expected behaviour
- Profile photos should be loaded
- Stickers should be available
- Media files should download

### Actual behaviour
- Most user icons display the name of the contact instead of the photo; when clicking on their details, photo is blank and clicking on it shows up as a loading spinner
- Most stickers are not present, but some are; (seems rather random, there are sets with 1-2 stickers and there are almost complete sets)
- No media files gets downloaded, loading spinner spins forever; cancelling and retrying doesn't change the outcome

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
V1.6.7

**Used theme**:
Classic

**Logs**:
[log.txt](https://github.com/telegramdesktop/tdesktop/files/3124876/log.txt)

**Comment by john-preston** [comment]
@Zelgadis87 Can you check an older version? Like 1.6.3 or even before, from https://desktop.telegram.org

**Comment by Zelgadis87** [comment]
Tried 1.6.3 and 1.6.2, unexpectedly still doesn't work, have exactly the same problem. I am sure this issue came up in the last 1 week or so, 1 month ago was fine.

I installed old versions on top of the newest one, but it asked for my login, so I imagine settings have been reset. Please let me know if I should have completely uninstalled and reinstalled in order to test correctly.

**Comment by john-preston** [comment]
@Zelgadis87 You can download portable versions and just unpack to some new folder.

**Comment by john-preston** [comment]
@Zelgadis87 To be sure try something older, like 1.5.8.

**Comment by Zelgadis87** [comment]
@john-preston Sorry for the delay, was away from my computer for a few days. I have tried Telegram portable 1.6.3, 1.5.15 and 1.5.8, all with the default configuration, all have the same issue. I am positive those versions were working fine before, so it's not a source code issue.

Regarding profile photos, I have noticed that only bots and some channels have the photo. Medias and link previews never load. Stickers seem rather random.

I have no clue what else to try. Worked fine for years..
Here are logs for Telegram Portable 1.5.8, in case they are useful:
[log.txt](https://github.com/telegramdesktop/tdesktop/files/3139685/log.txt)
Thanks

**Comment by Zelgadis87** [comment]
Issue autosolved itself today. Not sure what happened, but now it works with 1.6.7. Closing the issue.

**Comment by Zelgadis87** [comment]
And it started again, exactly the same as last time. Profile photos, media, stickers, etc. all randomically started to not download again...
Tried reinstalling but nothing.
Telegram Web and Telegram Android correctly works.
Current version is: 1.8.15

**Comment by Zelgadis87** [comment]
@john-preston I don't know if you are the right person to ask, but is there some debugging information I can add to the issue to help investigate the case?

**Comment by john-preston** [comment]
@Zelgadis87 You can contact me at @preston, I’ll ask you to try another version and maybe ask for debug logs.

**Comment by Zelgadis87** [comment]
@preston Hi, thanks for the response!

I have tried the only versions I could find on the website, 1.8.15 and 1.9.1-beta (portable):
[log-1_8_15.txt](https://github.com/telegramdesktop/tdesktop/files/3902982/log.txt)
[log-1_9_1_beta.txt](https://github.com/telegramdesktop/tdesktop/files/3902983/log.txt)

There doesn't seem to be any useful information available in there tho.. :(

**Comment by Aokromes** [comment]
he told you to contact him on telegram to get a private beta :)

**Comment by Zelgadis87** [comment]
Ah.. Ops! 😂😂😅

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Zelgadis87** [comment]
@Aokromes : I have talked a lot with @john-preston and tried various test builds. None was able to fix the issue.  
The problem we found is not related to Telegram Desktop per se, but more with a network issue with *some* of the used data centers. In some cases (most, to be honest) the connection fails, and we found no amount of timeout was able to solve the issue.  
I'm not sure if I can contact some other person more relevant to the issue found.

**Comment by Aokromes** [comment]
maybe on ask a question, idk.

**Comment by Zelgadis87** [comment]
I have tried contacting Telegram support. I'll update the issue when/if I receive an answer.

**Comment by Zelgadis87** [comment]
Telegram support never replied to me. The problem has mysteriously disappeared, so for now I'm closing the issue. Thanks all!
