### ISSUE TITLE
Hyperlinks to direct IPv6 addresses don't result in a clickable link

### ISSUE THREAD

**Issue by chungy** [telegramdesktop/tdesktop#5970]
### Steps to reproduce
1. Insert a direct link to an http server by IP address, for example `http://[2001:db8::1]/`, `https://[2001:db8::1]/`, `http://[2001:db8::1]:8080/`
2. Send the message
3. Link does not show up as a clickable hyperlink, just plain text.

### Expected behaviour
Should result in a clickable hyperlink, like happens with IPv4 equivalents (`http://198.51.100.1/`, eg).

### Actual behaviour
Plain text, not a hyperlink.

### Configuration
**Operating system:** Arch Linux

**Version of Telegram Desktop:** 1.6.7

**Used theme**: Dark

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stek29** [comment]
Sorry, links are parsed on server side.

**Comment by chungy** [comment]
Then where should those bugs be reported?

**Comment by stek29** [comment]
@chungy twitter or in-app support
