### ISSUE TITLE
Invitation limit 200 users ... but how to invite a bot?

### ISSUE THREAD

**Issue by BateauSD** [telegramdesktop/tdesktop#5971]
Hello everyone, good time of day!
After some time I decided to create and add bots to my channels, but I ran into a problem. 
In all the "channels" there is a limit of 200 people invitations, and this creates a problem that you can not add a bot. I can invite the bot to my conference "Group" but I can not do the same for my channels, the list simply does not have the "channels" I need, even with a search.

### Configuration
Windows 10 x64

**Version of Telegram Desktop:**
1.6.7

**Comment by john-preston** [comment]
@BateauSD Bots can only be admins in the channels. You can appoint a bot as an admin on channel edit screen.

**Comment by BateauSD** [comment]
> @BateauSD Bots can only be admins in the channels. You can appoint a bot as an admin on channel edit screen.

The problem is that I can't even invite or add it to my channel.
As well as issue admin rights him.

**Comment by john-preston** [comment]
@BateauSD You can open admins, press add admin and search for your bot by username. Or maybe even by name.
