### ISSUE TITLE
Do not split long messages

### ISSUE THREAD

**Issue by kenorb** [telegramdesktop/tdesktop#5972]
### Steps to reproduce

1. Paste some content.

### Expected behaviour

The message shouldn't not split, it should be posted as one message. Similar like SMS have limit of 160 characters, but they're merged into one.

### Actual behaviour

The text is split into multiple messages.

### Configuration

**Operating system:**: Ubuntu

**Version of Telegram Desktop:** v1.6.7

**Used theme**: Light

Related: GH-5328

**Comment by john-preston** [comment]
@kenorb API has limit on one message size, 4096 symbols. When received you have no idea if several messages were parts of one or not :(
