### ISSUE TITLE
"Clear history" deletes all messages from contact's history, instead of the ones I sent

### ISSUE THREAD

**Issue by vtdmhd** [telegramdesktop/tdesktop#5973]
### Steps to reproduce
1. Issue a "clear history" command with "Also clear for contact" flag
2. On the contact's side, all messages get deleted, including the ones that he sent

### Expected behaviour
On my side, history is completely blank. Onthe contact's side, my messages should be deleted from the contact's history.

### Actual behaviour
On the contact's side, all messages get deleted, including the ones written by him

**Comment by RememberTheAir** [comment]
That's the intended behavior, see [here](https://telegram.org/blog/unsend-privacy-emoji#unsend-anything) and [here](https://t.me/durov/102)

**Comment by vtdmhd** [comment]
Removing the messages I sent is ok. Removing messages someone else sent from his storage me is a security breach and a privacy violation. The policy MUST be reviewed.

**Comment by RememberTheAir** [comment]
@vtdmhd I agree this feature sucks but apparently [most of the users don't agree](https://t.me/durov/103) (although that poll doesn't give a meaningful overview of what the average Telegram user thinks about the unsend anything function). And anyway, it's not a tdesktop issue. You should complain with the in-app support or on Twitter

**Comment by stek29** [comment]
I'm truly sorry to do this since I agree with it not being a good choice for telegram.
