### ISSUE TITLE
In Channels: Clicking on a Deleted user opens the Restrictions panel.

### ISSUE THREAD

**Issue by Edicksonjga** [telegramdesktop/tdesktop#5974]
### Steps to reproduce
1. Go to Deleted Users on your channel.
2. Click on a user.
3. Restrictions opens and not the user's profile.
4. If you tap Save in Restrictions, the deleted user exits the list. (Then see Recent Actions).

### Expected behaviour
When you click on a deleted user you must open your user profile, not the Restrictions.

### Actual behaviour
Clicking on the deleted user opens the Restrictions window. In channels there are no such Permissions.

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.6.7 beta

**Used theme:** Default

**Comment by stek29** [comment]
I disagree: often I click on users in recent actions to adjust restrictions placed on them.
Maybe a way to open profile from restrictions modal should be added instead.

**Comment by Edicksonjga** [comment]
We are talking about a channel, if my memory does not fail me, this applies only to groups. Why would we want to put Permissions to a single user on a channel?
