### ISSUE TITLE
Jumping blinking cursor

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#5976]
### Steps to reproduce
1. Install Fedora 30 KDE
2. Build Telegram from source 

### Expected behaviour
Nothing. (Read more)

### Actual behaviour
I have two layouts in system and change them with Capslock. When I type a msg in the telegram like this: (look at |, it's a blinking cursor)
message:
Test
Test
Test| // I hold on Caps to change layout, and cursor jump after the last word at the message:

Test|
Test
Test

### Configuration
F30 
Linux localhost.localdomain 5.0.9-301.fc30.x86_64 #1 SMP Tue Apr 23 23:57:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**Version of Telegram Desktop:**
1.6.7-2
**Used theme**:
Midnight

I am a bit shocked because i have never seen something like this before.
I can just replace caps to any key and it works well, but it is a bit weird.

**Comment by xvitaly** [comment]
> Build Telegram from source

Install version from RPM Fusion repository.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
months without answer, if this bug is still valid open a new ticket.

**Comment by ilya-fedin** [comment]
> months without answer, if this bug is still valid open a new ticket.

_Wooo, ghost will open a new ticket for your scare_
