### ISSUE TITLE
Can you add secret Chat?

### ISSUE THREAD

**Issue by brasslan** [telegramdesktop/tdesktop#598]
Why does Tdesktop exist???  I will tell you that I downloaded a copy because web.telegram.org won't do secret chat.  If Tdesktop doesn't do secret chat, then I will just use the web app instead.  I'm very disappointed in the 'official' desktop app for this shortcoming!  I was expecting to have new encryption keys on the desktop client and therefor would not be able to sync chats between phone and PC.  That would be fine, and exactly what I want because the secret key on my phone should NEVER leave that device.  The desktop client should be able to create and store some encryption keys that will never leave my desktop.  I should be able to delete and create new keys at will.

**Comment by cobalto** [comment]
Calm down, man.

**Comment by intrd** [comment]
+1

**Comment by p0lipo** [comment]
secret chat would be very nice...

**Comment by ppparadox** [comment]
You clearly don't have a clue about how secret chats work.

**Comment by ustcltx** [comment]
+1

**Comment by brasslan** [comment]
ppparadox, your comment hints at the fact that there is a very good reason why tdesktop doesn't support secret chat.  If you have time for the hint, you should also have time to illumine the rest of the community who also wants this feature added to tdesktop.  Also, after you tell us why it isn't possible, can you tell why those reasons don't apply to the mac desktop software which has secret chat, or the other non official chat apps which does give us the ability for secret chat?

Or the other possibility, you were going off topic with a small attack on my personal technical knowledge by stating that I don't know weather telegram uses asymmetric or symmetric encryption, that I don't know how which encryption algorithms are in use.  That part is true, and I've never claimed that it was false.  What is also true is that it is possible to have the secret chat features on a desktop application.  Other apps have done it, tdesktop has not.  The real question is the title of the thread.  Can it be added to tdesktop?

**Comment by ppparadox** [comment]
End to end encryption. It's in the FAQ. https://telegram.org/faq#secret-chats

**Comment by robertfoss** [comment]
Not supporting secret chats on the desktop client is quite annoying as it prevents me from moving between desktop/laptop and cellphone.

Programmatically it should be possible to send a message from a sender to multiple clients of one receiver.

**Comment by AhmedDjoudi** [comment]
And also groups for the desktop app.

+1

**Comment by NeoLegends** [comment]
@AhmedDjoudi Groups are working?! Select the icon in the right hand side of the search bar to create new ones.

+1 for secret chats and for accepting pull requests!

**Comment by auchri** [comment]
duplicate #871
