### ISSUE TITLE
Messages with code aren't properly editable at the beginning of code

### ISSUE THREAD

**Issue by kortov** [telegramdesktop/tdesktop#5980]
### Steps to reproduce
1.  write a message with code markup
(just write text surrounded with ``` )
```
text
```
2. edit message (just add a symbol at the begining) , hit enter
3. here we go
![bugTg](https://user-images.githubusercontent.com/6348215/57362059-0171ad80-718f-11e9-9c5b-3cf69af272b5.gif)

### Expected behaviour
You can add symbols to the code at the beginning  of  ``` markup

### Actual behaviour
messages with ``` markup aren't editable at the beginning of the code, you can only add content into or after it

### Configuration
**Operating system:**
Windows 7, Pro, 64 bit SP1

**Version of Telegram Desktop:**
1.6.7 
**Used theme**:
classic

NOTE: I think this issue some kind a duplicate of https://github.com/telegramdesktop/tdesktop/issues/4860 but mine is more precise

**Comment by kortov** [comment]
Some more little details: 
when I click left button at the beginning of the code text, it works properly.
![bugTgadd](https://user-images.githubusercontent.com/6348215/57369170-012cde80-719e-11e9-8237-2c499db3ab1b.gif)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by kortov** [comment]
Yep, it's valid

**Comment by kortov** [comment]
Yes, it's reproducable on 1.9.8
