### ISSUE TITLE
Make option to delete / manually grey out / mark messages one read in group chats (on my side only of course) to continue from last read msg

### ISSUE THREAD

**Issue by necros2k7** [telegramdesktop/tdesktop#5984]
In other words make it possible to delete already read channel messages on client side so not to clutter chats

**Comment by Aokromes** [comment]
very likely this needs api support.

**Comment by RememberTheAir** [comment]
The client already knows what is left to read and what not. This doesn't necessarily needs an API, but would be very inconsistent with the rest of the apps

**Comment by necros2k7** [comment]
Maybe client knows but people want to know where they stopped reading and want to continue so not to remember every chat, bookmark or greyed out/deleted system would be great

**Comment by necros2k7** [comment]
Not stale

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
