### ISSUE TITLE
The search icon on Archived Chat is just another back button.

### ISSUE THREAD

**Issue by meh7an** [telegramdesktop/tdesktop#5985]
### Steps to reproduce
1- Open a chat
2- Open Archived Chats.
3- Try to click on the search icon on Archived Chats

### Expected behaviour
It should search the Archived chats list and contents of it (Or just focus on search on main list)

### Actual behaviour
It goes back and no "Search" happens

### Configuration
**Operating system:** Any Desktop OS

**Version of Telegram Desktop:** 1.7

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@meh7an Search happens — in the main list :)

**Comment by meh7an** [comment]
@john-preston I should add that this happens only if workmode is on

**Comment by RememberTheAir** [comment]
@meh7an it depends. if you have a chat open then yes, it needs another click. @john-preston maybe when the lens icon is clicked you should move the focus on the search bar

**Comment by meh7an** [comment]
@RememberTheAir Nice catch. Confirmed the specific situation. Adding to the main issue text

**Comment by RememberTheAir** [comment]
This has been fixed. @meh7an can you confirm?

**Comment by Heliosmaster** [comment]
Confirmed fixed
