### ISSUE TITLE
Telegram Users spoofing username!

### ISSUE THREAD

**Issue by edugrip** [telegramdesktop/tdesktop#5988]
### Steps to reproduce
**I don't know how to reproduce it.** 

### Expected behaviour
Telegram users should have a unique username
### Actual behaviour
People are messaging me from same **username** simultaneously. 

### Configuration
**Operating system:**
I am sorry as this is not related to this Desktop Repo, but the issue is very critical  about every user of telegram. If you know a better place to raise this issue, kindly guide me.

**Comment by Aokromes** [comment]
https://twitter.com/telegram or abuse@telegram.org

**Comment by omoridi** [comment]
Same Display Name is possible.
Same UserName maybe use the untrusted application and sent by that application.

**Comment by edugrip** [comment]
Sorry to raise the flag, Actually there is no way to verify whether it was an L or i but, the case I noted was similar to what @omoridi  has said.  The user was `PaulHitBTC` and the fraudster was using a username that excatly looked like it . However it is quite possible that It was `PauIHitBTC` 
So,
**Providing the user with an option to copy the username could help her verify whether the usernames are exactly same or it is a trap....** this can be done by various means (programmatically capitalizing the text etc.)

**Comment by john-preston** [comment]
@edugrip You can copy username from the user's profile.

**Comment by SmartManoj** [comment]
Why still open

**Comment by SmartManoj** [comment]
why open
