### ISSUE TITLE
Remove Archived Chats from Top of Chat List

### ISSUE THREAD

**Issue by ch3ckmat3** [telegramdesktop/tdesktop#5989]
Thank you for a much requested feature: Archived Chats.

Archived Chats are supposed to be out of sight, but they are put on top of the list in the new release. Please move it in the menu or at the last position in the list (or let users choose what to do with it).

Version 1.7

**Comment by chall3ng3r** [comment]
This... Please. Thank you 👍

**Comment by 23rd** [comment]
Try `Collapse` in context menu.

**Comment by ch3ckmat3** [comment]
> Try `Collapse` in context menu.

thanks :)

I discovered in Android, it is hidden on swipe, and can be shown on pull down. same can be done for desktop version.

**Comment by Geobert** [comment]
Even collapsed, it's still on top of the list.

**Comment by TedsterTech** [comment]
> Thank you for a much requested feature: Archived Chats.
> 
> **Archived Chats are supposed to be out of sight**, but they are put on top of the list in the new release. Please move it in the menu or at the last position in the list (or let users choose what to do with it).
> 
> Version 1.7

This. Please make them actually out or sight like seems should have been intended.

**Comment by Geobert** [comment]
@ch3ckmat3 Why are you closing this?

**Comment by stek29** [comment]
@Geobert because there's an option to collapse them which is consistent with other platforms

**Comment by stek29** [comment]
Although I agree that having a counter when archived chats folder is collapsed is not a good idea.

**Comment by Geobert** [comment]
Even collapsed, we still have them on top which is kinda the opposite of archiving. I'm using collapsed contact so it's way more noticeable:
![image](https://user-images.githubusercontent.com/72570/57612127-22aa1380-756c-11e9-9793-69d61c6185e7.png)

**Comment by RememberTheAir** [comment]
@stek29 I agree that the unread counter should not be visible when the archive is collapsed. That number really pushes you into opening the archive every time there's a new message

**Comment by Hezkore** [comment]
I came here specifically to ask for Archived Chats to NOT be at the top of the list.
It's pretty weird that the chats you're trying to hide instead becomes the most seen and top chat in the entire list.
Either put it in the "side menu" or at the bottom of the list.

**Comment by Neurotoxin001** [comment]
This must be top #1 priority issue.

**Comment by Neurotoxin001** [comment]
Finally done in 1.7.8, thanks!

**Comment by 23rd** [comment]
Fixed in ece315f3c5a14ed43a274e52e7e1c6c1a1cd1a2b.
