### ISSUE TITLE
right click -> view profile is gone after updating to 1.7

### ISSUE THREAD

**Issue by siamak2** [telegramdesktop/tdesktop#5992]
### Steps to reproduce
1. right click on a chat from chat list (on the left side of the app)

### Expected behaviour
show an option called view profile
### Actual behaviour
view profile doesn't exist

### Configuration
**Operating system:**
windows 7
**Version of Telegram Desktop:**
1.7
**Used theme**:
classic
p.s. view profile was available in previous versions

**Comment by john-preston** [comment]
@siamak2 Yes, some items were removed.

**Comment by SimonSchick** [comment]
What's the reason for that?
I liked being able to view someones profile when they messaged me without viewing the message.

**Comment by siamak2** [comment]
@john-preston please return it.
I don't mind if I have long list of options in right click context.

**Comment by john-preston** [comment]
@siamak2 Sorry, guys. Designers mind :(

**Comment by SimonSchick** [comment]
Does that mean it's not coming back?
Any possibility of having the menu customized?

**Comment by SajedMohseni** [comment]
I was gonna submit the same issue. It's really annoying that you can check the profile before actually view the message

**Comment by Younes-L** [comment]
I was busy and just noticed this.
Total deal breaker, what a di** move. It seems many of the most requested changes are held back by these "designers" who care about looks more than functionality. Functionality should always take priority and designer's job is to make clutter optional and think of nice ways to enable/disable it.

Anyway I'm 100% downgrading to 1.6 and never updating again. Thanks.

**Comment by S-U-M-1** [comment]
This must be re-added because now it is impossible to see the profile of unknown users who have messaged you without marking their messages as read.

**Comment by 23rd** [comment]
Returned with e7c40ff2a8b9eebf3f686fd6975dea92ac1fc3d3.

**Comment by SimonSchick** [comment]
@john-preston ty for bringing that back.
