### ISSUE TITLE
High CPU usage since last update on MacOS

### ISSUE THREAD

**Issue by SimonSchick** [telegramdesktop/tdesktop#5993]
### Steps to reproduce
1. Start telegram
2. Interact with Telegram (viewing chats, chatting etc.)
3. CPU usage goes up.

### Expected behaviour
MacBook should not turn into jet engine.

### Actual behaviour
MacBook turns into jet engine.

### Configuration
**Operating system:**
MacOS
```
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E227
```

**Version of Telegram Desktop:**
1.7.0

**Used theme**:
[awesome.tdesktop-theme.zip](https://github.com/telegramdesktop/tdesktop/files/3165021/awesome.tdesktop-theme.zip)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@SimonSchick Can you please compare side to side that 1.7 is working really differently from 1.6.7? Just logout, install the previous version, disable autoupdate in settings and try for some time. Then enable autoupdate, update to 1.7 and compare.

**Comment by SimonSchick** [comment]
Will do tomorrow, thanks for the quick response btw.

**Comment by SimonSchick** [comment]
@john-preston it seems less severe with 1.6.7.
Please note that the majority of the cpu drain originates from 
`/System/Library/PrivateFrameworks/SkyLight.framework/Resources/WindowServer` and not the Telegram process itself.
Once I close Telegram the processes cpu usage effectively drops to 1%.

**Comment by XenHat** [comment]
Also happens on Windows 10. Frequently starts using ~30-35% CPU on an i7-4790K.
Restarting the client temporarily fixes it.
Focusing on/opening the GIF tray and pressing the ESC key a few times also temporarily fixes.
It however always come back.

Turning GIF autoplay *off* does **not** help.

![image](https://user-images.githubusercontent.com/980408/58374325-23e32500-7f0a-11e9-82a1-6a27140b0b1c.png)

**Comment by SimonSchick** [comment]
This is no longer the case.
