### ISSUE TITLE
Show number of unread archive chats instead of sum of unread messages near archive directory

### ISSUE THREAD

**Issue by egorpugin** [telegramdesktop/tdesktop#5995]
This follows mobile experience and less annoying rather than non-stoppable increasing counter when many active chats archived and muted.

**Comment by john-preston** [comment]
@egorpugin You can change that in Settings > Notifications > Count unread messages. It follows the same logic that the app badge does.

**Comment by egorpugin** [comment]
Oh, indeed, sorry.
Thank you!
