### ISSUE TITLE
GCC 9.1+ regression

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#5996]
### Steps to reproduce
1. Build version 1.7.0 from sources.
2. Launch.
3. 

### Expected behaviour
Successful launch.

### Actual behaviour
Segmentation fault with:
```
Thread 1 "telegram-deskto" received signal SIGSEGV, Segmentation fault.
operator() ()
    at /usr/src/debug/telegram-desktop-1.7.0-1.fc30.x86_64/Telegram/SourceFiles/data/data_session.cpp:3305
3305				*changesIn = (result > 0)
```

### Configuration
**Operating system:** Fedora 30

**Version of Telegram Desktop:** 1.7.0

**Used theme**: n/a

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by xvitaly** [comment]
This crash caused by GCC 9.1.1 regression.

GCC 9.0.1 works, GCC 9.1.1 crashes. Will report to GCC upstream as soon as possible, but we need to find workaround until it will be resolved.

**Comment by xvitaly** [comment]
Reported this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1708621

**Comment by xvitaly** [comment]
Tested build with `-O0` (disabled optimizations). It works.

**Comment by tux93** [comment]
Can confirm this issue on openSUSE Tumbleweed
Telegram Desktop 1.7.0 built with GCC 9.1.1 results in Segmentation fault

**Comment by perestoronin** [comment]
Same error with tg 1.7.14 & gcc 9.1.0. 
Please fix it or tell me solution, other than migrate back to gcc 8.3.0.

**Comment by Johnnynator** [comment]
The related gcc bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90949
It is already fixed in gcc upstream, you can cherry-pick the patch from there.
