### ISSUE TITLE
Respect 'back' mouse button when opening archive chats

### ISSUE THREAD

**Issue by mxs42** [telegramdesktop/tdesktop#5997]
Back button should go back to chat list if you open archived chats.
Currently it closes active chat and then does nothing.

**How it should work:**

**Case 1**
1. You go to archived chats.
2. 'Back' press closes archived chats list.   

**Case 2**
1. You go to archived chats.
2. You open a chat from there.
3. 'Back' press closes chat.
4. 'Back' press closes archived chats list.

**Case 3**
1. You open chat from main list.
2. You go to archived chats.
3. 'Back' press closes archived chats list.

**Case 4**
1. You open chat from main list.
2. You go to archived chats.
3. You open a chat from there.
4. 'Back' press returns to the chat you opened from main list.
5. 'Back' press closes archived chats list.

**Comment by 23rd** [comment]
Sorry, but the fourth case is an enhancement and does not repeat patterns of behaviour of `Escape` key.
Open a new issue if you still need it.
