### ISSUE TITLE
Notification from archived chats and mark all as read

### ISSUE THREAD

**Issue by wanderleihuttel** [telegramdesktop/tdesktop#5998]
First of all, thanks for this feature! I guess the users was expecting for this feature for a long time.

- Would be interesting create an option in the notification menu to not show or count the messages not read in the "archived chats" menu.
- Another suggestion is to create an option to mark all messages read from every chat, including archived chats

Thanks Wanderlei

**Comment by neesti** [comment]
I think suggestion 1 (NO count the messages not read in the "archived chats" menu) is very useful after version 2.0
