### ISSUE TITLE
Archived chat - hide removed user (from preview)

### ISSUE THREAD

**Issue by anfimovir** [telegramdesktop/tdesktop#5999]
Telegram Desktop 1.7.0
Windows 10 Pro, 64 bit

In Archived chats (in left column) - showing: removed account

Screenshot:
![removed_account](https://user-images.githubusercontent.com/10336636/57558758-a656db00-7387-11e9-9495-2013e962b79c.PNG)

In iOS - not visible, please hide its for desktop too.

**Comment by Qwerty-Space** [comment]
Right click → collapse
![image](https://user-images.githubusercontent.com/6967592/66064807-0bc98500-e53e-11e9-86cd-55ceaf4ec44a.png)
