### ISSUE TITLE
Insert username in messagebox with ctrl+click on user name or username avatar in chat

### ISSUE THREAD

**Issue by formatq** [telegramdesktop/tdesktop#600]
If no username write a custom name of contact

**Comment by auchri** [comment]
Please add a description of the issue you have

**Comment by formatq** [comment]
Sorry for my English.
So, something like this:

When I click on the user name in the chat window by holding CTRL key then in the message text field inserted his @username. If @username is not set, then inserted Contact Name, or nothing happens.
