### ISSUE TITLE
Question: Is FILES sent to chats / groups / channels - ENCRYPTED on the telegram side or not?

### ISSUE THREAD

**Issue by anacondaq** [telegramdesktop/tdesktop#6001]
Hi, after reading a lot of code in desktop version of telegram, I got confused very much.
My question is very simple and very important at the same time:

**Short question:**
> Are files what we send to telegram (chats, channels, groups) encrypted on the disk space at telegram or not?

**Long Question:**
I can't find any file encryption/decryption for files at all at client-side of the telegram.
I start to worry about my files, because out of the box Telegram positioned as secure messaging application, but at the same time as I understand (I can be wrong, correct me, if I'm) - files not encrypted and stored simply as a simple files in the telegram storage without any encryption and technically and in theory and in real practice telegram can view, read, and do whatever they want with the files.

If files encrypted -> tell me when, when we send a file and on the file while uploading the file encrypted or not? Because everything looks like chats encrypted, but files do not.

**Comment by john-preston** [comment]
@anacondaq All data is sent encrypted, chats and files. They're encrypted in the same way, it is done by the mtproto protocol implementation.

**Comment by anacondaq** [comment]
Thank you for the answer! I will continue to analyze the code, have a nice day.
