### ISSUE TITLE
[Feature Request] Mark all archived chats as read

### ISSUE THREAD

**Issue by MasterGroosha** [telegramdesktop/tdesktop#6004]
### Expected behaviour
It would be nice, if right-click on "Archived chats" entry allows to mark all archived chats as read

### Actual behaviour
For now you have to click on all chats one by one

### Configuration
**Version of Telegram Desktop:** 1.7.0

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5998

**Comment by MasterGroosha** [comment]
@Aokromes well, that issue is about marking all chats as read, not only archived ones. And since that issue covers several topics, I’d prefer to keep this one open

**Comment by beppe9000** [comment]
I think that any unread archived chat should be subtracted from the unread chats total shown in the notification area and in the window title. Having the option to mark all archived chat read by the right click menu is probably useful.

**Comment by ashed** [comment]
And how **all** chats may be "marked as read" all together?

**Comment by RememberTheAir** [comment]
@ashed no way to do that

**Comment by ashed** [comment]
But this implemented in mobile clients. Maybe there is a way?

**Comment by ashed** [comment]
**Mark all as read** was implemented in Telegreat desktop client in version 1.3.
How it workd, when you tell me that is impossible?

**Comment by beppe9000** [comment]
is it possible to do a pull requesto from there ?
