### ISSUE TITLE
Mouse Wheel not work in version 1.7

### ISSUE THREAD

**Issue by omoridi** [telegramdesktop/tdesktop#6005]
Hi, In version 1.7, Mouse wheel do not work.

**Comment by MasterGroosha** [comment]
Would you be so kind to provide details of your issue? At least which Operating System (OS) you're using

**Comment by Aokromes** [comment]
works for me (TM) on windows 10 20h1.

**Comment by omoridi** [comment]
My Mouse Wheel work on every place of windows but on telegram do not work, and I must scroll with telegram scrollbars.

3 Device have this issue but now I have 2 device version
Microsoft Windows [Version 10.0.18895.1000]
Microsoft Windows [Version 10.0.17134.706]

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3896

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3859 maybe if after sleep.

**Comment by omoridi** [comment]
If you mean after sleep the computer? I must to say no, I restart computer and run telegram and see these problem.
don't forgot this problem goes only at version 1.7, the below version worked.

**Comment by omoridi** [comment]
after set Persian language mouse wheel worked!
http://t.me/setlanguage/fa-raw
