### ISSUE TITLE
Revoke / Change Group Invite Link doesn't work

### ISSUE THREAD

**Issue by Alexa69** [telegramdesktop/tdesktop#6007]
Hi

My group is under attack by Spammers I was able to handle the issue with Anti-Spam bot. but to reduce the pressure on the bot I attempted to change the group invitation URL through the Invite link option and revoked the previous links and made a new address BUT it DOESN'T WORK and people are still able to join group using the previous links!

is there anyway to completely change the join GROUP address :( ?!

**Comment by stek29** [comment]
@Alexa69 revoke only revokes YOUR link.

Every admin has their own invite link.
You should either ask all of your admins to revoke their links, or just remove "add by invite link" permission for all of them.

Sorry for your group, usually groups get locked down in such cases until spamers calm down.
