### ISSUE TITLE
Scrollbar width

### ISSUE THREAD

**Issue by olliefr** [telegramdesktop/tdesktop#6008]
### Steps to reproduce
1. Open Telegram
2. Go to any chat which is more than one screen long
3. 

### Expected behaviour
Scroll bars have adjustable width (in Settings)

### Actual behaviour
Scroll bars are too narrow

### Configuration
**Operating system:** 
Windows 10

**Version of Telegram Desktop:**
Latest as of today, but it's not relevant.

**Used theme**:
Default (Dark)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

The default width for scroll bars is too small. Please provide an option to set the scroll bars to OS default width. I can change my scroll bar width in Atom, which is also Electron-based via a stylesheet, but Telegram is packaged into a single executable, which is also signed. It would be a waste of resources for someone to recompile Telegram just for the sake of having scroll bars which work as those in the rest of the system.

**Comment by Aokromes** [comment]
#2974
