### ISSUE TITLE
Telegram Desktop forcing dedicated GPU on macOS

### ISSUE THREAD

**Issue by Philipp-p** [telegramdesktop/tdesktop#6010]
### Steps to reproduce
1.  Start the application

### Expected behaviour
Not using the dedicated GPU

### Actual behaviour
It forces my OS to enable he dedicated GPU, as it listed as requires high performance GPU in activity monitor

### Configuration
**Operating system:**
macOS 10.14.4
**Version of Telegram Desktop:**
1.7
**Used theme**:
Blue

**Comment by Philipp-p** [comment]
Theme switching does not resolve the issue

**Comment by 23rd** [comment]
a058e75a6d64de6c17eb172db69997dc60b6ccaa

**Comment by Philipp-p** [comment]
I'm not entirely sure, but apparently the bug in macOS that forced you to implement this work around got fixed in version 10.14.5. Please see https://github.com/jwilm/alacritty/issues/2221

**Comment by john-preston** [comment]
I'll need to check that, thanks.

**Comment by otrsk** [comment]
It would be great to have those hours of extra battery life back indeed :)

**Comment by k06a** [comment]
Same problem for me. Installed iStats Menu to be notified when active GPU changed.

**Comment by Philipp-p** [comment]
Version 1.7.3 does no longer exhibit this behavior

**Comment by temoto** [comment]
Possibly regression, forces high perf GPU
Telegram desktop: 1.8.2
OSX: 10.12.6

**Comment by otrsk** [comment]
FYI: The current version from App Store (as of Aug 26: 5.6.1 (179691) AppStore) doesn't suffer from this.

**Comment by 23rd** [comment]
@otrsk 5.6.1 is not the Telegram Desktop.

**Comment by otrsk** [comment]
@23rd Yes, it's just that it turned out to be a perfect replacement of Telegram Desktop for me, thus the FYI :)

**Comment by anka-213** [comment]
I still have this issue on the latest version on app store

**Comment by otrsk** [comment]
> I still have this issue on the latest version on app store

You can use the `Telegram` app instead now, current AppStore version is 7.3 (211379), https://apps.apple.com/de/app/telegram/id747648890?l=en&mt=12 (s. also https://macos.telegram.org/ ).

**Comment by anka-213** [comment]
> You can use the `Telegram` app instead now, current AppStore version is 7.3 (211379), https://apps.apple.com/de/app/telegram/id747648890?l=en&mt=12 (s. also https://macos.telegram.org/ ).

That was apparently the one I was using, which also had this problem, not the one in this repo. I've switched to using telegramdesktop and now it works fine.

There is already an issue for that in its issue tracker (https://github.com/overtake/TelegramSwift/issues/334), so I can switch back when that is fixed.
