### ISSUE TITLE
New notification sound lowers audio message volume

### ISSUE THREAD

**Issue by Twiiiiin** [telegramdesktop/tdesktop#6012]
### Steps to reproduce
1.  Listen to an audio message 
2.  Receive a message

### Expected behaviour
I expect to continue listening the audio without problems

### Actual behaviour
Notification sound plays and audio message's volume gets automatically lowered, making me lose bits of the message

### Configuration
**Operating system:** MacOS High Sierra 10.14.4

**Version of Telegram Desktop:** 1.7

**Used theme**: Standard - Night Mode

**Comment by Lonami** [comment]
This is the intended behaviour. I believe on Android background music, for instance, also gets lower when receiving a notification. So it's consistent.

**Comment by Twiiiiin** [comment]
I see it is intended, but still would be useful to put a switch, to let notifications not lower other things' volume. Even on android music, as you mention, it is really annoying to have my volume dropped because i received a message

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Twiiiiin** [comment]
I think it would still be relevant as a feature, and it is not included, so yeah! Still valid

**Comment by Lonami** [comment]
This still occurs.
