### ISSUE TITLE
[Feature Request] Little pen icon instead of "edited"

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#6013]
Telegram X on Android has this cute little pen icon instead of dull "edited" mention for edited message. I think it unclutter the chat messages :)

**Comment by Lonami** [comment]
You can use [@nobadge](https://t.me/nobadge) or suggest a translation in Telegram's translation site. Nothing more to be done on the client itself.

**Comment by Geobert** [comment]
nice workaround!
However it does not look good:
![image](https://user-images.githubusercontent.com/72570/57914480-9f97fe80-7886-11e9-9319-4b4a96d14820.png)

**Comment by Lonami** [comment]
That's a problem with the font used, though. The alternative is using the actual pen which renders as emoji, but that's far more distracting :(

**Comment by Geobert** [comment]
Any way to change the font for a better looking one? Or it's because it's too small so any font will produce medium result like this?

**Comment by Geobert** [comment]
workaround : https://t.me/setlanguage/nobadge-en
