### ISSUE TITLE
Numbers aren't taggable

### ISSUE THREAD

**Issue by kenorb** [telegramdesktop/tdesktop#6014]
### Steps to reproduce

1. Post tag like #1111

It's not linked.

### Expected behaviour

It's linked.

### Actual behaviour

It's not linked.

### Configuration

**Operating system:** Ubuntu Cosmic

**Version of Telegram Desktop:** 1.7

**Used theme**: Default

**Comment by Aokromes** [comment]
it's intended

**Comment by Lonami** [comment]
It is strange however that searching by `#1111` finds exactly `#1111` only, though. Might as well make them clickable hashtags. But, this is a server-side issue, not client-side, so it can be closed.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1529
