### ISSUE TITLE
Problems with scaling in KDE.

### ISSUE THREAD

**Issue by Alidrod** [telegramdesktop/tdesktop#6015]
Steps to reproduce:
Change scaling in KDE to 1.5.
Scaling in Telegram Desktop is 100%.

Actual behaviour:
![image](https://user-images.githubusercontent.com/33231572/57790710-f5b05900-7743-11e9-9082-697ebbcfc9dd.png)

Configuration:
OS: Arch Linux
DE: KDE 5.58.0 / Plasma 5.15.5

Version of Telegram Desktop: 1.7

Theme: Default Night mode

**Comment by john-preston** [comment]
@Alidrod Is it the version from site?

**Comment by Alidrod** [comment]
> @Alidrod Is it the version from site?

No, it's version from official Arch Linux repositories.

**Comment by Kezii** [comment]
Can confirm with the arch package, but the version from the site seems to not be affected

**Comment by Sebastiaan76** [comment]
I have this exact problem too. Was fine, but recent Arch update and now getting the same issue - only Telegram is affected.

**Comment by Houkime** [comment]
In Arch telegram is patched before build. It might be not even a problem with program itself but with patches. 
Exact patches can be looked up here https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/telegram-desktop

**Comment by Johnnynator** [comment]
What is your uses at version and what is your KDE scaling set to?

**Comment by svenmauch** [comment]
I can confirm this bug for Arch Linux using Telegram Desktop from the stable repository. It also affects the default light theme and any DPI setting in Telegram as long as Display Scaling is activated in KScreen.

Here's the bug report for Arch Linux: https://bugs.archlinux.org/task/62594

**Comment by Sebastiaan76** [comment]
Definitely Arch related, as the AUR version works fine, so it's something Arch specific to do with how they packaged/patched this.
