### ISSUE TITLE
Links are not clickable on Linux

### ISSUE THREAD

**Issue by slavafomin** [telegramdesktop/tdesktop#6016]
Hello!

Thank you for this great app and your hard work!

However, just recently, the URLs in message text stopped becoming clickable (they render as normal text instead). You have to edit the message and save it again to make the links to become highlighted and clickable.

And this behavior seems somewhat random, sometimes the message is submitted with clickable links, sometimes not. I wish I had more details to help in debugging this issue.

```
$ cat /etc/issue
Ubuntu 18.10
```
```
$ uname -a
Linux destiny 4.18.0-18-generic #19-Ubuntu SMP Tue Apr 2 18:13:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I'm running Telegram Desktop version `1.7`.

**Comment by Aokromes** [comment]
works for me on debian 9. (also on ubuntu 18.10)

**Comment by Aokromes** [comment]
no answer for near a year. closing.
