### ISSUE TITLE
[Feature Request] Archived Chats: Don't show counter when collapsed

### ISSUE THREAD

**Issue by zackpollard** [telegramdesktop/tdesktop#6017]
### Expected behaviour
The MacOS Telegram App already does this, however it would be nice if the counter was not shown when the archived chats section is in the collapsed state, or at least for there to be an option to hide the counter when in the collapsed state in the settings.

### Actual behaviour
Whether collapsed or expanded, the archived chats section shows the counter.

### Configuration
Version of Telegram Desktop: 1.7.0

**Comment by SmartManoj** [comment]
Title : Don't show counter for Archived Chats  when collapsed

**Comment by Heliosmaster** [comment]
Still think this would be valuable
