### ISSUE TITLE
[Feature request] Add lock-to-record for voice messages

### ISSUE THREAD

**Issue by Mrazzotta** [telegramdesktop/tdesktop#6018]
### Expected behaviour
It would be nice to add same swipe up or similar solution to lock recording action for voice messages as it's done in mobile clients.

### Actual behaviour
User forced to keep icon button pressed to keep voice message being recorded. Moreover it's easy to lose result by accidental mouse moving since user has to keep cursor precise above the mic icon. Situation is getting worse when you at laptop using touchpad, making you sticked with finger to it.

### Configuration
**Operating system:**
Win10 x64

**Version of Telegram Desktop:**
1.7.0+
**Used theme**:
Any

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4909
