### ISSUE TITLE
[Feature request] Add ability to group chats into folders

### ISSUE THREAD

**Issue by pxl-th** [telegramdesktop/tdesktop#6019]
It would be great if one can group several chats into dedicated folder, with similar to `Archive chat` mechanic.
For example, you can group co-workers into folder `Work` and stuff.
This would make main chat list less cluttered and it would be easier to find particular person instead of scrolling through huge list of all chats.

**Comment by Lonami** [comment]
While the API already has support for `N` folders, it also forbids using any besides the one designated to archiving chats. This may be a reality in the future.

**Comment by RememberTheAir** [comment]
In addition to Lonami's comment, an official statement from telegram about folders: https://twitter.com/telegram/status/1128702087901208577

**Comment by Aokromes** [comment]
#1107
