### ISSUE TITLE
Change data export directory format

### ISSUE THREAD

**Issue by lapo-luchini** [telegramdesktop/tdesktop#6020]
### Steps to reproduce
1. export data

### Expected behaviour
Create a directory naming scheme that has a proper ordering on multiple exports.

### Actual behaviour
Using `DataExport_dd_mm_yyyy` the time order of exports gets mixed up.

I'd suggest to switch to ISO8601, i.e. `DataExport_yyyy_mm_dd` so that time order is the same as ASCII order.

**Comment by adripo** [comment]
I also need this date format to keep folders organized. Cannot order them properly in windows.
