### ISSUE TITLE
Wrong notification position

### ISSUE THREAD

**Issue by corelof** [telegramdesktop/tdesktop#6022]
### Previous actions

I've turned my laptop(1366x768 resolution) on and entered telegram desktop. After it I've connected external monitor(2560x1080 resolution) and seen that notifications are in wrong place. 
![Screenshot from 2019-05-17 13-46-50](https://user-images.githubusercontent.com/25709818/57923617-72117c00-78ab-11e9-92bb-0e0a4d0310c9.png)

### Expected behaviour

Notification in right bottom corner.

### Actual behaviour
Notification appeared on position, which was right bottom corner on 1366x768 resolution screen.

### Configuration
**Operating system:**
Ubuntu 18.04 with i3wm.

**Version of Telegram Desktop:**
1.2.17

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
