### ISSUE TITLE
Distorted Text on Qt 5.13beta3 on Linux (X11)

### ISSUE THREAD

**Issue by Scrumplex** [telegramdesktop/tdesktop#6023]
### Steps to reproduce
1. Install Qt 5.13beta2
2. Start a X11 Session
3. Start Telegram Desktop

### Expected behaviour
The text should look normal as it does on Wayland

### Actual behaviour
The text is distorted and has lines striking through

### Configuration
**Operating system:** Arch Linux with kde-unstable repositories enabled

**Version of Telegram Desktop:** 1.7

**Used theme**: Breeze Dark (distributed through https://t.me/BreezeDark)

![Screenshot](https://x.scrumplex.rocks/img/1558091130.png)

**Comment by xvitaly** [comment]
Telegram Desktop use Qt Private API, so you must rebuild it against exact version of Qt.

**Comment by Scrumplex** [comment]
Okay. I am currently rebuilding Telegram, to see if that fixed it. Still weird imo, that it works on Wayland without any rebuild.

**Comment by Scrumplex** [comment]
Looks like it works when rebuilt with Qt 5.13beta2. Closing this as this is a packaging issue then.
