### ISSUE TITLE
Wrong/missing emoji pic for default ("Mac") and Android emoji set for :woman_detective:

### ISSUE THREAD

**Issue by Spacehug** [telegramdesktop/tdesktop#6024]
### Steps to reproduce
1. Bring up emoji panel
2. Pick :woman_detective: emoji by long-pressing it and hovering over any skin tone except the default
3. Observe what got displayed

### Expected behavior
🕵🏻️‍♀️🕵🏼️‍♀️🕵🏽️‍♀️🕵🏾️‍♀️🕵🏿️‍♀️ should appear in the selection box and in the chats

### Actual behavior
🕵🏻️‍♂️🕵🏼️‍♂️🕵🏽️‍♂️🕵🏾️‍♂️🕵🏿️‍♂️ appears in the selection box and in the chats

### Configuration
**Operating system:**
Tested on `Linux 192-168-1-164 5.0.13-arch1-1-ARCH #1 SMP PREEMPT Sun May 5 18:05:41 UTC 2019 x86_64 GNU/Linux` and `Windows 10 x64 Home`
**Version of Telegram Desktop:**
1.7
**Used theme**:
All default themes

**Notes**:
The issue is solely related to TDesktop, Android and iOS apps are not affected and they display the correct emoji. So it must be lack of proper image and/or some kind of fallback mechanics. Also, only Mac and Android sets are affected, Twemoji and EmojiOne are not.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Spacehug** [comment]
Yes, as of today this bug is still present.
The system I have just reproduced it on is:
```
OS: Manjaro 18.1.5 Juhraya
Kernel: x86_64 Linux 5.3.18-1-MANJARO
DE: KDE 5.66.0 / Plasma 5.17.5
WM: KWin
```
TDesktop version is `1.9.8`

**Comment by 23rd** [comment]
Android emoji set still has a bug, but it should be updated independently from the code of this repository.
