### ISSUE TITLE
Since last update i can't search for messages inside groups

### ISSUE THREAD

**Issue by willywilly12345** [telegramdesktop/tdesktop#6026]
### Steps to reproduce
1. Nothing to reproduce really, i knew that when i right click a group a serach for messages option should appear.
2. 
3. 

### Expected behaviour
When i right click a group a search for messages option should appear.

### Actual behaviour
The option disappeared 

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.7

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@willywilly12345 There is a search button in the top bar of the group when you open it.

**Comment by panamariuss** [comment]
Stupid me ! thank you

**Comment by heatherkovich69** [comment]
wtf 19073157219

kovich
