### ISSUE TITLE
 the release 1.7 is not showing up correctly!

### ISSUE THREAD

**Issue by OmidMahmoudi** [telegramdesktop/tdesktop#6027]
### the release is not showing up correctly!
I downloaded the latest version of the telegram source, but the release is not showing up correctly. Can you help me out where is my problem?

![1](https://user-images.githubusercontent.com/19889603/57979235-3227d180-7a30-11e9-861c-7a4baa5f4ad3.png)

**Comment by kirsan31** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5967
