### ISSUE TITLE
[i18n] want to translate for Chinese(China)

### ISSUE THREAD

**Issue by caizixian** [telegramdesktop/tdesktop#603]
I want to start translating the desktop app and become the coordinator of Chinese(China) team.

I translated Sentry and became coordinator of Chinese(China) team before which you can see at my Transifex profile at https://www.transifex.com/accounts/profile/caizixian/

**Comment by dongfengweixiao** [comment]
已经翻译完毕了：https://github.com/telegramdesktop/tdesktop/pull/683
正在提交请求，等待合并。

**Comment by meteormatt** [comment]
:+1:
