### ISSUE TITLE
Window does not open with left-click in status bar

### ISSUE THREAD

**Issue by LevinGermann** [telegramdesktop/tdesktop#6034]
### Steps to reproduce
1. Left-Click on the Telegram icon in the system tray

### Expected behaviour
The telegram window should open, like the way it does with a right-click -> Open Telegram

### Actual behaviour
Nothing happens

### Configuration
**Operating system:** Manjaro 18.0.4, Deepin version

**Version of Telegram Desktop:** 1.7

**Used theme**: None

[log.txt](https://github.com/telegramdesktop/tdesktop/files/3197111/log.txt)

I see some stuff in the log related to appindicators, which might be related to this issue...

[2019.05.20 11:05:44] Could not load 'ayatana-appindicator3' with version 1 :(
[2019.05.20 11:05:44] Could not load 'appindicator3' with version 1 :(
[2019.05.20 11:05:44] Could not load 'ayatana-appindicator' with version 1 :(
[2019.05.20 11:05:44] Error: failed to load 'gdk_set_allowed_backends' function!
[2019.05.20 11:05:44] DE: Gnome

This last line assumes that my DE is Gnome, which is not true.

**Comment by LevinGermann** [comment]
Note that when I hover over it, there's a light background indicator that the Telegram icon is selected, and once I click on it, the background disappears.
I guess this indicates that the click-event has been fired, but is just not handled in the background.
![image](https://user-images.githubusercontent.com/9347206/58022594-14309e80-7b0e-11e9-81e0-747dc71ef065.png)
![image](https://user-images.githubusercontent.com/9347206/58022616-1d217000-7b0e-11e9-8147-82e3f62b9b27.png)
(my screenshot program removes the cursor, it's hovering over the icon)

**Comment by xf3** [comment]
On Linux Mint 19.1 Xfce LMC on tray icon acts just like RMC (Opens context menu), but when running Telegram desktop with sudo, LMC on tray icon opens Telegram window normally.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/3b4dfa138176b4d1e3cb14be1be638ebe2f52713
