### ISSUE TITLE
Kiss emoticon (:*) suggests ✖️ emoji

### ISSUE THREAD

**Issue by Xjs** [telegramdesktop/tdesktop#6035]
### Steps to reproduce
1. Type `:*` in a chat window
2. Observe suggestion popup that suggests the ✖️ emoji

### Expected behaviour
The ✖️ emoji shouldn't be suggested.

### Actual behaviour
The ✖️ emoji is suggested when typing ":*".  (Why is it suggested anyway? The ✖️ emoji has the name »heavy multiplication x«, and as far as I am aware, there are no unicode characters with asterisks in their names.)

### Configuration
**Operating system:** Windows 10 Pro Insider Preview (build 18898.1000)

**Version of Telegram Desktop:** 1.7

**Used theme**: Classic with custom background

**Comment by LevinGermann** [comment]
This is not reproducible in Linux - Manjaro, same Telegram Version 1.7.
:x works as expected
![image](https://user-images.githubusercontent.com/9347206/58048419-077e6b80-7b4b-11e9-8abb-dd9be1cf9e22.png)
:* as well, doesn't give any suggestions.
![image](https://user-images.githubusercontent.com/9347206/58048459-0fd6a680-7b4b-11e9-9881-c7186411796c.png)

**Comment by Xjs** [comment]
Screenshot from Windows 10: ![image](https://user-images.githubusercontent.com/58270/58084424-261c4b00-7bbb-11e9-8b67-a145c4471789.png)

Maybe it is relevant that this is the Microsoft Store version? The Microsoft store says »modified 13/05/2019«. I am observing this behaviour only since a few days, before it was fine. It could have been brought on by that latest update.

**Comment by john-preston** [comment]
@Xjs You can disable emoji suggestions in Settings > Chat Settings. But some suggestions, like that one, should be removed indeed.

**Comment by Aokromes** [comment]
i get https://i.imgur.com/3W1QzHL.png

**Comment by Xjs** [comment]
> @Xjs You can disable emoji suggestions in Settings > Chat Settings. But some suggestions, like that one, should be removed indeed.

@john-preston I know that, but in general I use and like emoji suggestion.

**Comment by Xjs** [comment]
`:/` also suggests a ➗ sign, which is also not what I'd expect.

**Comment by Aokromes** [comment]
this no longer suggests :/ or :*
