### ISSUE TITLE
Stickers blinking

### ISSUE THREAD

**Issue by TABmk** [telegramdesktop/tdesktop#6036]
### Steps to reproduce
1. Open any chat with stickers
2. Open gifs tab
3. Scroll few lines

Also one more way:
1. Open full side emoji panel
2. Open gifs tab
3. Scroll few lines

### Actual behaviour
All stickers starts blinking (gif attached)
In second way all stickers in all chats starts blinking when panel is open

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.7

**Used theme**: Night mode

![QU6BGmMAD1](https://user-images.githubusercontent.com/7514285/58018310-22c98680-7b0b-11e9-93de-f5df128e38b1.gif)

**Comment by YevhenPoliakov** [comment]
The same issue on version 1.8.15 (win 10 x64)

**Comment by devcline** [comment]
this is weird, same here

**Comment by Khalphion** [comment]
Can confirm this (Version 1.9.3, Windows 10 x64).
If you switch back to the stickers panel, the flickering stops again. It seems to be connected to the GIF playback.

**Comment by mailani19** [comment]
Can confirm it does this on windows 7 x64.  version 1.9.3. as well.
It has the added 'benefit' of immediately maxing out the CPU usage as long as the stickers are still flickering.

**Comment by aaronw2** [comment]
Can confirm on Linux v1.9.9. It seems to happen if I have a game going on. My guess is it's a lack of resources somewhere it never recovers from.

**Comment by Nyaan** [comment]
Confirmed on Windows 10 (1809 - Build 17763.973) - Telegram Desktop 1.9.9
Dealing with this bug for seeeveral months now.

Sometimes the client even crashes completely.
**Pleaaase** try to debug and fix this <3

**Comment by ilya-fedin** [comment]
Is this still valid? I guess this could be fixed since https://github.com/telegramdesktop/tdesktop/pull/7323

**Comment by Nyaan** [comment]
Seems fixed! :)
