### ISSUE TITLE
cursor gets resetted when using keyboard to reply to a message

### ISSUE THREAD

**Issue by lollilol** [telegramdesktop/tdesktop#6038]
### Steps to reproduce
1. Write a message
2. Use CTRL + Arrow Up (arrow up once or more times)

### Expected behaviour
The cursor should be at the end of the message/where it was before
![image](https://user-images.githubusercontent.com/38194372/58021303-d3835600-7b0a-11e9-9d71-e0b6cda3fe53.png)

### Actual behaviour
The cursor is at the beginning of the message
![image](https://user-images.githubusercontent.com/38194372/58021279-c36b7680-7b0a-11e9-81e2-399f43516798.png)

### Configuration
**Operating system:** Windows 10 1809 (Build 17763.503)

**Version of Telegram Desktop:** v1.7

**Used theme**: Doesn't matter

**Comment by 23rd** [comment]
This will be fixed in one of the next versions.
