### ISSUE TITLE
Hide the app after click on item in contact list

### ISSUE THREAD

**Issue by sergeyshmakov** [telegramdesktop/tdesktop#6039]
**What is the bug:**
Clicking on the item of contact list in full size window mode my app is hiding.

**How I found this bug:**
After some time of iddle in telegram use, close/open notebook.
_May be this bug reproduces while clicking on any point at the screen. In my case I clicked only on contacts list_

**How I fix this bug:**
Closing app on window applications icon not fixes the bug.
I can fix it only fully close telegram app and open it again.

OS: Windows 10 Pro
Telegram: v1.7

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
