### ISSUE TITLE
Images aro not always donloaded

### ISSUE THREAD

**Issue by maerco** [telegramdesktop/tdesktop#604]
In order to download received images, I need to waited many minutes.
They remain in low resolution for a long time before to be downloaded.

**Comment by whodafly** [comment]
I'm getting the same problem. Version 0.8.4. Images take forever to download, sometimes never "completing" until I restart my computer.

This is what I see:
![telegram_image_downloading](https://cloud.githubusercontent.com/assets/1080682/7145064/dda31de0-e2e9-11e4-861e-feab5484d8f0.png)
