### ISSUE TITLE
[Feature request] A new design for Archived Chats icon

### ISSUE THREAD

**Issue by meh7an** [telegramdesktop/tdesktop#6042]
As it seems, Archived Chats is a part to archive unused chats and showing it as a pinned chat even on collapsing it is a little wired.

I had a small redesign for collapsed mode that can be useful.

![photo_2019-05-21_22-12-11](https://user-images.githubusercontent.com/47609307/58118145-8049fa00-7c15-11e9-8579-2bb58482f6ad.jpg)

**Comment by Aokromes** [comment]
this request is still wanted?

**Comment by Aokromes** [comment]
no answer after months, new "collapse" way was added months ago, closing.
