### ISSUE TITLE
Unable to revert to default nickname

### ISSUE THREAD

**Issue by sdomi** [telegramdesktop/tdesktop#6045]
### Steps to reproduce
1. Set a custom nickname for one of your contacts
2. Try to revert it via saving it as a blank one

### Expected behaviour
It should behave like web.telegram.org - after saving a contact with a blank First and Last name, it should revert to the default

### Actual behaviour
The app doesn't allow First Name to be removed

### Configuration
**Operating system:** Void Linux, but it works the same on every platform

**Version of Telegram Desktop:** 1.6.3, but the same happens on newer ones

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by redsPL** [comment]
![](http://f.sakamoto.pl/0e9e27b9-64f9-4e88-9acd-fb6d0fdd1a0cfile_89.jpg)
Seems like it - 2.1.6 on Linux

**Comment by Aokromes** [comment]
workaround, delete the contact and add again.

**Comment by redsPL** [comment]
Not a great one, because it forces you to set a name - although the field is populated with their current name, by using this approach, you won't know if that person ever changes their nickname.

By clearing the local nickname on web.telegram.org, all clients will always show the currently correct nickname.

**Comment by sdomi** [comment]
Commenting mostly to prevent the bot closing the issue.

All you really need to do is to **remove** the check for empty name which shouldn't be there in the first place - the rest of the logic has to be already coded in, because if you don't have a custom nickname, Telegram will just display the contact name.

![](https://f.sakamoto.pl/ed08503f-1a78-48cf-a7a5-1f3846f2c22bfile_128.jpg)

**Comment by sdomi** [comment]
Commenting - AGAIN - to keep this issue open. The invalid behaviour is still here in 2.7.1

**Comment by sdomi** [comment]
@Aokromes please open the issue again, it *was not* resolved, the bug still occurs.

**Comment by sdomi** [comment]
Still there in tdesktop 3.2.2.

With every passing day I'm getting closer to getting up and doing it myself

**Comment by RememberTheAir** [comment]
I believe this is the intended behavior. It doesn't work like that on any of the official apps, and on any of the new web clients. If you want to revert to the user's chosen name, you should delete the contact (and re-add it if needed)

**Comment by sdomi** [comment]
It literally works that way on the Z web version and the old web version. After clicking the `V` button, the field is left blank, and the name reverts to the default one. See attached pics.

![image](https://user-images.githubusercontent.com/22369758/143001216-88bf15f5-a168-4298-8851-119c01f60eec.png)
![image](https://user-images.githubusercontent.com/22369758/143001249-c0d91299-649c-4f3a-a379-dd281a2b3431.png)

**Comment by RememberTheAir** [comment]
The old web client has long been deprecated and shouldn't be used as reference for how features should work. Web Z's behavior I believe is the one that should be fixed, since it's the only one that works like that and it's also buggy, so it might simply be an unfinished implementation
