### ISSUE TITLE
No push notification when the app is in background

### ISSUE THREAD

**Issue by chetanpm** [telegramdesktop/tdesktop#6048]
### Steps to reproduce
1. App running in the background.
2. Use some other application in the foreground
3. New messages won’t notify until the telegram app is activated after which it says updating>>connecting and then shows new messages

### Expected behaviour
New message should push to the app even when the app is not in focus.

### Actual behaviour
Notification works only when app is freshly out of focus. There is no notification after long periods of inactivity of the app.

### Configuration
**Operating system: MacOS 10.14.14**

**Version of Telegram Desktop: 5.2.2 (170935) Stable**

**Used theme**: Night Blue

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by p0358** [comment]
Wrong repo, this is for Telegram Desktop, you have Telegram for Mac OS X

**Comment by chetanpm** [comment]
> Wrong repo, this is for Telegram Desktop, you have Telegram for Mac OS X

The version I have is Telegram Desktop. It is not the ‘for Mac OS’ Version.

**Comment by RememberTheAir** [comment]
> Version of Telegram Desktop: 5.2.2 (170935) Stable

You are either reporting the wrong version number or misunderstanding tdesktop for Telegram for MacOS. See https://github.com/overtake/TelegramSwift

**Comment by 23rd** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5921#issuecomment-483126605
