### ISSUE TITLE
Move libnotify code out of nogtk ifdefs

### ISSUE THREAD

**Issue by msva** [telegramdesktop/tdesktop#6049]
### Steps to reproduce
1. Build tdesktop with GTK disabled (for using Qt/KDE file dialogs and other KDE integration)
2. Notice missing option to use "native" system notifications
3. Notice that KDE's notification system still implements DBUS interface for that, but tdesktop doesn't use it, since libnotify code somewhy hidden under GTK ifdefs (although it has almost no dependency on GTK).

### Expected behaviour
tdesktop should be able to use libnotify even with disabled linking against GTK 

### Actual behaviour
tdesktop does not.

### Configuration
**Operating system:**
Gentoo/Linux 
**Version of Telegram Desktop:**
1.7.0

**Comment by xvitaly** [comment]
libnotify require GTK (both library, and it's headers). You cannot build without GTK, but with libnotify.

Btw, libnotify code from Telegram Desktop should be removed and replaced by modern DBus integration for native desktop notifications which can work in any DE on any distributions.

**Comment by msva** [comment]
Well, actually, it **doesn't** depend on gtk as "libgtk".
It depends on:
- libgdk_pixbuf
- libgobject
- libglib
- libgio

They're from `gdk-pixbuf` and `glib` packages, which are **related** to GTK, but not a GTK itself.
So, I still sure it can be used without GTK...

But, yes, your idea of dropping libnotify and implementing it in the proper DBUS way is a nice solution too.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Johnnynator** [comment]
Nope, obsolete since 3d36b4f86693a49c281fda7af82823b185674142
