### ISSUE TITLE
remove limit on pinning non-archived chats

### ISSUE THREAD

**Issue by msva** [telegramdesktop/tdesktop#6050]
Can you, please, consider removing the limit of non-archived pinned chats, please?

It is absolutelly not enough to have only 5 of them...

P.S. Yes, I'm aware that mobile version has that limitation too. And I even suspect it is TG API limitation.
But still, if core TG devs think that pinned chats can reduce server performance (or what argumentation they using to excuse the limitation) clients can store pinned lists locally... It will still be **much** better, that having only 5 of them...

**Comment by RememberTheAir** [comment]
> And I even suspect it is TG API limitation

It is. Pinned chats are limited to 5 because pinning more would hide new content from the main screen, that's what telegram said on Twitter. Anyway, this issue is a duplicate

**Comment by CeH9** [comment]
> limited to 5 because having more would hide new content from the main screen

There is a lot of space. Alternatively you can make separate tab for favorites. 

![image](https://user-images.githubusercontent.com/7687412/58316176-a345fb00-7e1b-11e9-87f0-7fcf8aeeb20a.png)

**Comment by RememberTheAir** [comment]
@CeH9 mobile phones don't usually show that many chats on the main screen, also some people are used to resize Telegram's window to the smallest size possible.

inb4 "allow us to pin chats locally" "if you have a small screen just don't pin that many chats"

**Comment by CeH9** [comment]
![image](https://user-images.githubusercontent.com/7687412/58317584-bc03e000-7e1e-11e9-99a3-c53715c2ad07.png)

Same look & feel across all platforms is good principle, but there is no reason to limit desktop just because mobile can't support such feature or because someone use small window.  Moreover, think about it as "extra option" for desktop users. Just make option in settings, Give users freedom of choice.

**Comment by RememberTheAir** [comment]
> Same look & feel across all platforms is good principle, but there is no reason to limit desktop just because mobile can't support such feature

Apparently Telegram values platform consistency more than a richer customization of the desktop client

**Comment by msva** [comment]
> Apparently Telegram values platform consistency more than a richer
> customization of the desktop client

And that was the reason why @john-preston refused "wide baloons" patch and now 
I apllying it locally and re-port it to the new codebase after every release 
>_>

I already tried to patch that "pinned tabs limit", but since it depends on TG 
API it is irrelevant, and it still doesn't work.

And I'm not ready to maintain such a big local patch for "local pinnted tabs 
storage" implementation :-/

**Comment by artikrh** [comment]
To be honest, you can leave the 'trade-off' option of not seeing new chats to end-users. Or, you can implement an arrow key that cues you to scroll down for new messages. This 5 pinned chats limit is ridiculous -- and NO, I don't want to pin chats in the archived window.
