### ISSUE TITLE
Open links without warning

### ISSUE THREAD

**Issue by KoalaBear84** [telegramdesktop/tdesktop#6051]
### Expected behaviour
Open links without warning when CTRL is pressed. This is easy to implement and very useful as I get messages with links from trusted sources, a warning is not needed.

### Actual behaviour
It will show a warning

### Configuration
**Operating system:**
Windows 10 Pro

**Version of Telegram Desktop:**
1.7

**Used theme**:
Normal

**Comment by KoalaBear84** [comment]
Added in the next version?

**Comment by 23rd** [comment]
@KoalaBear84 Yes, in version 1.7.1 you can open links with pressed `Ctrl`.

**Comment by KoalaBear84** [comment]
Great! Thanks! 👍
