### ISSUE TITLE
Wrong timestamp on forwarded messages

### ISSUE THREAD

**Issue by Hi-Angel** [telegramdesktop/tdesktop#6052]
### Steps to reproduce
1. Forward at least a few minutes old message in a chat

### Expected behaviour
Forwarded message has timestamp of when it was written

### Actual behaviour
Forwarded message has timestamp of when you forwarded it.

![Screenshot_20190522_214358](https://user-images.githubusercontent.com/7935057/58200141-bac99a80-7cda-11e9-9f23-82d36384027f.png)

### Configuration
**Operating system:** Archlinux

**Version of Telegram Desktop:** 1.7

**Used theme**: Classic

**Comment by 23rd** [comment]
You can hover over the timestamp of forwarded message and see the details.

**Comment by Hi-Angel** [comment]
Cool, I didn't know it. Still, it's not useful for forwarded messages to have the same date as the comment that one often sends together with them. It's always confusing. It would be better to either α. show the date of creation of the message forwarded, or β. show both dates.

**Comment by Hi-Angel** [comment]
> It's always confusing

To elaborate: when you see a dozen of messages with the same timestamp, the first thought is "wtf, it's impossible to consciously write so many messages at once". Then you figure that "Forwarded" title implies that they all got forwarded at the same moment, and then you wonder "Why do I see the current time instead of the time they were written at".

It is more rational to show timestamps of the original dialog, and leave the "received-at timestamp" to the popup. Because when you receive forwarded messages, you want to know how this dialog evolved, e.g. have the 2nd message been answered 2 minutes later or 2 days later, etc.

And btw: with current solution a lot of effort required to see the flow of the forwarded dialog by hovering over each message, and waiting for the popup.

Whereas "me received them" timestamp is the same everywhere; besides it matters less.

**Comment by Aokromes** [comment]
it's illogic and even more confusing on a linear flow to show different time than the one when they where forwarded

**Comment by Hi-Angel** [comment]
valid
