### ISSUE TITLE
Impossible to disable blinking notification on Windows

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [telegramdesktop/tdesktop#6053]
### Unwanted notification
There isn't a setting to edit the possibility of seeing a "visual notification" (orange blinking notification) that in Windows 10 is impossible to disable in the settings, neither disabling all the notifications settings of the app (from the app and from windows notification panel).

![notification blinking](https://i.imgur.com/Mru4Snc.png)

I tried the application Unigram from the store and that doesn't show the annoying orange blinking each message you receive while the app is in background.

### Configuration
**Operating system:** Windows 10 Pro, May 2019 update

**Version of Telegram Desktop:** 1.7 (from Windows Store)

**Comment by 23rd** [comment]
I haven't tried, but maybe that's what you need.
[github.com/mxs42/mutegram](https://github.com/mxs42/mutegram)

**Comment by john-preston** [comment]
@23rd I’ll add a setting in the next release.

**Comment by MarcoDiFrancesco** [comment]
The setting has still not been added.

**Comment by a3s** [comment]
So what?

**Comment by MarcoDiFrancesco** [comment]
I still wait for it

**Comment by a3s** [comment]
@MarcoDiFrancesco I know, I'm also waiting for feature that should have been from the first version.

**Comment by sanjayananda** [comment]
Any updates? Have hoped for this for a long time.

Has anyone had success with mutegram? @23rd mentioned it above.

**Comment by MarcoDiFrancesco** [comment]
Mutegram worked for me a while ago, and the option to turn off the noification has never been added.

**Comment by john-preston** [comment]
At last I did it here: https://github.com/telegramdesktop/tdesktop/commit/6f760d513ea41b8017d4abd5f88e615fd5c0a10e
