### ISSUE TITLE
Unicode Letters Can't Show in Telegram Desktop on Mac OS

### ISSUE THREAD

**Issue by chenrylee** [telegramdesktop/tdesktop#6056]
### Steps to reproduce
Install **Telegram Desktop** from **App Store**

### Expected behaviour
Unicode letters, like **𝔖𝔶𝔩𝔳𝔞𝔫𝔞𝔰 𝔚𝔦𝔫𝔡𝔯𝔲𝔫𝔫𝔢𝔯**, can't show, 

### Configuration
**Operating system:** Tested on Mac OS 10.12 and above

**Version of Telegram Desktop:** Test all versions so far

**Used theme**: Midnight

The letters show normally in Native Telegram for Mac.

**Comment by CssHammer** [comment]
Will this be fixed or what?

**Comment by Aokromes** [comment]
can you try on 1.9.1 beta?

**Comment by CssHammer** [comment]
> can you try on 1.9.1 beta?

Yes, still wasn`t fixed. I see rectangles instead of letters

**Comment by Aokromes** [comment]
and on 1.9.21 beta? :)

**Comment by chenrylee** [comment]
> and on 1.9.21? :)

I'm using the latest MAS version (1.9.13), some still can't show. And I found an interesting thing: **When the letters are in name (incl. quote & reply), it can't show; while the letters are in message, it shows normally.**  
![](https://i.loli.net/2020/03/22/3ZkRbScEaGr7u5v.jpg)

**Comment by doctor-frankenstein** [comment]
Now i found the special letters from UTF8 can display correctly at chat window,  but still broken in profile, please check my screenshot

![good at chat window](https://user-images.githubusercontent.com/46594603/80445468-f3d8a900-8946-11ea-84d7-b17610c35d52.png)

![broken at profile](https://user-images.githubusercontent.com/46594603/80445564-34382700-8947-11ea-99dc-be27e5cd1082.png)

**Comment by gaplo917** [comment]
Still not able to show unicode in username in telegram desktop 2.1.

![Screenshot 2020-07-06 at 1 06 02 PM](https://user-images.githubusercontent.com/5468398/86557727-a94c5c00-bf89-11ea-9e1c-5487f9fdad69.png)

left: Telegram MacOS
right: Telegram Desktop
![Screenshot 2020-07-06 at 1 04 59 PM](https://user-images.githubusercontent.com/5468398/86557731-ab161f80-bf89-11ea-9971-ec3d609501e8.png)

Sample text
```
𝑇𝑎𝑚𝑎𝑘𝑖
```

**Comment by Liam0205** [comment]
Any progress on this issue?

**Comment by Liam0205** [comment]
Telegram 2.1.13 on macOS reproduces this issue too.

**Comment by ilya-fedin** [comment]
> Any progress on this issue?

there can't be any progress since font rendering is completely on Qt side

**Comment by Aokromes** [comment]
https://bugreports.qt.io/browse/QTBUG-59553

**Comment by ilya-fedin** [comment]
> https://bugreports.qt.io/browse/QTBUG-59553

I dont' think that *this* bug is applicable for this issue, Qt has a problem with these glyphs with semibold style on any platform

**Comment by Liam0205** [comment]
> > Any progress on this issue?
> 
> there can't be any progress since font rendering is completely on Qt side

Well, I doubt it...

These chars could be shown correctly on the page of profile modification.

![image](https://user-images.githubusercontent.com/3348485/88051994-267fef80-cb8c-11ea-8c91-761352e2e46f.png)
![image](https://user-images.githubusercontent.com/3348485/88052040-37c8fc00-cb8c-11ea-829f-30c50d3f11c7.png)

**Comment by Liam0205** [comment]
To me, it seems to be a font selection issue, rather than font rendering.

**Comment by ilya-fedin** [comment]
> To me, it seems to be a font selection issue, rather than font rendering.

Yes, Qt has problems with font selection

**Comment by Liam0205** [comment]
> > To me, it seems to be a font selection issue, rather than font rendering.
> 
> Yes, Qt has problems with font selection (font fallback mechanism)

Copy that.

Would you provide a workaround to bypass this problem?

**Comment by ilya-fedin** [comment]
> Would you provide a workaround to bypass this problem?

no, there are no workaround, unfortunately

**Comment by ilya-fedin** [comment]
> These chars could be shown correctly on the page of profile modification.

fallback is broken with the semibold style for some unknown reason

**Comment by Liam0205** [comment]
> > These chars could be shown correctly on the page of profile modification.
> 
> fallback is broken with the semibold style for some unknown reason

One of my friends reports that everything works fine on his macOS 10.15.5 (which is the same to mine). i.e., this issue is stably reproducible on my mac, but is stably irreproducible on his mac. 
Why would this happen?

**Comment by ilya-fedin** [comment]
> Why would this happen?

It is better to ask Qt devs

**Comment by Liam0205** [comment]
I believe there might be something other than Qt causes this issue. It may be font configuration of macOS system preference.

I'll test this later this week, on a new installed macOS. If there will be any clues, I'll report them here.

**Comment by AndydeCleyre** [comment]
I don't have access to macOS right now, but since SemiBold is mentioned here, I'll note that part of my [workaround](https://aur.archlinux.org/packages/telegram-desktop-userfonts/) for fonts when building for Linux is replacing use of DemiBold with Bold, so you may want to try that:

```console
$ sed -i 's/DemiBold/Bold/g' Telegram/lib_ui/ui/style/style_core_font.cpp
```

On my phone right now... That may not be proper syntax for the default `sed` on macOS.

**Comment by WuglyakBolgoink** [comment]
ping

**Comment by ilya-fedin** [comment]
> ping

Connection timed out

**Comment by 0x1f415** [comment]
bumping as this continues to be a problem (on macOS).

interestingly the characters from the "Math Bold Script" set (eg `𝓪𝓼𝓭𝓯`) display as boxes while fraktur (`𝖆𝖘𝖉𝖋`) text displays fine.

**Comment by ilya-fedin** [comment]
There's no reason to bump, it only Qt devs can fix it

**Comment by omoidase** [comment]
all i see is square boxes.. did anybody find a resolution to this?
