### ISSUE TITLE
[Feature Request] Ability to download file by link

### ISSUE THREAD

**Issue by denisbednov** [telegramdesktop/tdesktop#6059]
When a user sends a link that points to file, then show button "Download" which downloads the file to user store (like any sent file).

![image](https://user-images.githubusercontent.com/5417828/58321753-b068e700-7e27-11e9-86d9-c4923714089c.png)

**Comment by jaekyeom** [comment]
Fyi, it already does that for some URLs.
![image](https://user-images.githubusercontent.com/6262727/70886241-5d05f280-201e-11ea-949c-0e084985741b.png)
