### ISSUE TITLE
Emoticons too small

### ISSUE THREAD

**Issue by completit** [telegramdesktop/tdesktop#606]
Hi guys,

Could you please increase the size of the emoticons, on the Laptop I can barely understand some of them.
![screenshot - 27 03 2015 - 21 52 29](https://cloud.githubusercontent.com/assets/5355219/6875953/ddb450a0-d4cb-11e4-9436-2207c8b8d091.png)
Apparently this supposed to look like a cactus...

**Comment by SniperRus** [comment]
+1. They are too small. In text and in selection baloon

**Comment by ustcltx** [comment]
+1

**Comment by kleuter** [comment]
https://github.com/telegramdesktop/tdesktop/issues/484
