### ISSUE TITLE
UI: Button "add user" and "search" not on the same y-coordinate level.

### ISSUE THREAD

**Issue by MairwunNx** [telegramdesktop/tdesktop#6061]
### Steps to reproduce
1. Open any group;
2. Open group info;
3. See forward to "XX MEMBERS" (Where XX - number of members);

### Expected behaviour
The same position of the icons on the Y coordinate.

### Actual behaviour
![image](https://user-images.githubusercontent.com/39625750/58370201-5beb6780-7f0c-11e9-8155-29643d1c6029.png)

![image](https://user-images.githubusercontent.com/39625750/58370238-ecc24300-7f0c-11e9-98a3-81969475f333.png)
### Configuration
**Operating system:** `Windows 10 1809`.

**Version of Telegram Desktop:** `1.7`.

**Used theme**: `Midnight`. `150% Scale`.

**Comment by john-preston** [comment]
Yeah, thanks. I'll fix that in the next version.

**Comment by Aokromes** [comment]
fixed.
