### ISSUE TITLE
New gTLDs not hyperlinked on outgoing messages in private chats

### ISSUE THREAD

**Issue by nyuszika7h** [telegramdesktop/tdesktop#6062]
### Steps to reproduce
1. Open a private chat with someone.
2. Send a message containing a new gTLD (e.g.: example.google, example.xyz)

### Expected behaviour
The domain should be hyperlinked.

### Actual behaviour
The domain does not appear hyperlinked on the sender's side, but it does on the receiver's side.

If it is a forward or sent to a group/supergroup/channel, there is no issue.

### Configuration
**Operating system:** Windows 10 1903

**Version of Telegram Desktop:** 1.7

**Used theme**: Midnight

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/805

**Comment by nyuszika7h** [comment]
How is it a server issue if it only happens in a very specific case and it works correctly on all other Telegram apps?

**Comment by Aokromes** [comment]
fixed on 1.9.9
