### ISSUE TITLE
[Feature Request]Rename chanel and group name

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#6066]
Please let user to rename chanel and group name (info) as locally (only into his/her telegram). 

For example I joined in a chanel or group that its name is: "A" and I don't like its name and I would like to rename its chanel name to my favorite name but only in My Telegram.

**Comment by neesti** [comment]
Is this feature compatible with Telegram API?

**Comment by RememberTheAir** [comment]
@neesti nope. Renames would happen locally only

**Comment by neesti** [comment]
But when I right click on a chanel or group, there is not any option for rename NOW!

**Comment by RememberTheAir** [comment]
I said "would happen", tdesktop would only be able to let you rename chats locally. All your custom names would be lost on logout/uninstall and the mobile apps wouldn't be able to show them. That's why this issue should be labeled as API issue. Can't happen on tdesktop
