### ISSUE TITLE
Do not replace emoji with enter

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#6067]
### Steps to reproduce
1. type `:p`
2. hit `Enter`

### Expected behaviour
I want to send `:p`, not this emoji:
![image](https://user-images.githubusercontent.com/72570/58413535-eea51700-8070-11e9-86dd-8a2d18145049.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/72570/58413543-f2d13480-8070-11e9-8d97-5c0276750c16.png)
is sent

### Configuration
**Operating system:**
Windows 
**Version of Telegram Desktop:**
1.7
**Used theme**:
Night mode

Maybe an option to disable emoji replacement with `Enter`?

**Comment by john-preston** [comment]
@Geobert Sorry, but this is a very common usecase — start typing and press "Enter" to select the first suggestion in the list. You can disable emoji suggestions in Settings.

**Comment by Geobert** [comment]
The thing is that I use the suggestions, but having enter to complete feels weird. Tab is the usual key for completion (IRC, dev IDE…).
I understand that as it's already available, some ppl use it, hence the option to disable it, instead of totally removing it.

**Comment by 23rd** [comment]
Just type two spaces after your emoji (`:p  `) and press enter. =)

**Comment by Geobert** [comment]
> 
> 
> Just type two spaces after your emoji (`:p `) and press enter. =)

Yeah, I know the workaround, be it feels cumbersome :-/

**Comment by Geobert** [comment]
Or even a dark art way to disable it is ok for me (like config file edition)

**Comment by cdubz** [comment]
@john-preston can you clarify how this can be disabled? Using Telegram 5.4 (175009) Stable on macOS 10.14.5, the only option I see in Settings that appears to be related is "Automatically replace emojis", but toggling that has no affect on the emoji suggestions/replace.

**Comment by RememberTheAir** [comment]
@cdubz you are not using tdesktop, you are using the native MacOS app

**Comment by cdubz** [comment]
> @cdubz you are not using tdesktop, you are using the [native MacOS app](https://github.com/overtake/TelegramSwift)

Ack. Sorry for the noise! 🤦‍♂

**Comment by lapo-luchini** [comment]
Personally, I'd enable the suggestion on the second letter instead of the first: when I write ":not" I want the "notes emoji" almost for sure, but ":p" and ":P" and ":O" are too frequently used "as themselves" and needing the double space, or escape, _each and everytime_ they're used is really annoying.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5927
