### ISSUE TITLE
The group moves up and down in the list after clicked.

### ISSUE THREAD

**Issue by Kiaazad** [telegramdesktop/tdesktop#6068]
There's this function that if we click a group a second time it will jump to the most recent message. however, the group moves up and down after the first click and another group will be clicked instead. 

### Steps to reproduce
1. join several active groups
2. click a group with some new messages
3. try to click it again to jump to the latest post

### Expected behaviour
the groups or chats shouldn't change position in the list, at least for few seconds after an interaction.

### Actual behaviour
chats jump all over causing missed clicks.

### Configuration
**Operating system:**
windows seven
**Version of Telegram Desktop:**
1.7 portable
**Used theme**:
default
<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by Kiaazad** [comment]
it's not a bug per se, just an annoying behavior. yes, groups still jump to the top based on which has the most recent activity (I assume) and moving the selected one down, in the 1.9.8 version.
It should be relatively easy to pin the groups on place while selected or keep the updated chats under the selected one at all time.

**Comment by SmartManoj** [comment]
Still?

**Comment by Kiaazad** [comment]
It seems to be improved some time ago and I didn't notice to close this issue sooner.
