### ISSUE TITLE
[Feature request] Add an option to make the media preview fill the window, instead of the whole screen.

### ISSUE THREAD

**Issue by HenkKalkwater** [telegramdesktop/tdesktop#6069]
Whenever I click on an image or any other kind of media, I would like to the media preview to fill up the Telegram window, instead of my whole screen.   
* Having it fill up the entire screen is kind of against the concept of a desktop environment with windows, in my opinion.  
* It is annoying whenever you want a larger view of a picture having it side by side with another application.  

Perhaps a setting could be implemented in the settings to switch between the proposed and old behaviour, or a button could be added to the media preview to switch.  

A rough mockup of what I am trying to describe:  
![Mockup of the feature request][mockup]

[mockup]: https://i.imgur.com/ng10INo.png "Mockup of the feature request"

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1710

**Comment by HenkKalkwater** [comment]
Ah, didn't notice that one. Thanks!
