### ISSUE TITLE
Reconnect after laptop sleep

### ISSUE THREAD

**Issue by robertfoss** [telegramdesktop/tdesktop#607]
After my laptop resumes, the telegram client will no longer receive any new messages.

To receive new messages the client has to be killed and restarted.

I'm on Ubuntu 14.04

**Comment by kireledan** [comment]
This happens to me as well. Im running Arch.

**Comment by skyjack** [comment]
The same for Win8.1: status "connecting...".
W/a: restart Tg.

**Comment by basheersubei** [comment]
+1

Have to restart application on Ubuntu 14.04 as well

**Comment by basheersubei** [comment]
I believe this is a duplicate of #536

**Comment by Foodfast** [comment]
+1 Very annoying issue. Linux Mint 17.1, Arch.
