### ISSUE TITLE
"Telegram didnt close properly" on i3 window manager

### ISSUE THREAD

**Issue by clue44** [telegramdesktop/tdesktop#6070]
### Steps to reproduce
1. Run Telegram under Linux with the i3 Window Manager
2. Open Telegram. Close it normally. Open it again, and it opens normally. Close it.
3. Logout from I3
4. Login again
5. When you start Telegram, you get the message "Telegram didnt close properly".

### Expected behaviour
The message should not appear since telegram was closed properly before logging out. And even if I do kill telegram on logging out, i really dont want this message every time i start it.

### Actual behaviour
The message appears every time Telegram is started after logging in. Can we at least get an option to disable this message? It feels a lot like Windows where you get bothered with unnecessary messages.

I think this probably happens because the tray icon is still there after closing telegram (also typical of Windows, where close often doesnt mean exit and apps are still running). So when logging out, the tray icon gets killed and telegram figures it wasnt closed properly.

### Configuration
**Operating system:**
Linux with i3 window manager

**Version of Telegram Desktop:**
1.7

**Used theme**:
Classic

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
plz, try to run telegram with gdb or valgrind to see if you can find some relevant crash.

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
