### ISSUE TITLE
Add option to init the app minimized in system tray

### ISSUE THREAD

**Issue by perezmeyer** [telegramdesktop/tdesktop#6072]
### Steps to reproduce
1. Add telegram-desktop to applications started at desktop init. 
2. Telegram starts with it's window open on init.

### Expected behaviour
Option to start t-d minimized (to system tray).

### Actual behaviour
Not possible

### Configuration
Debian GNU/Linux, sid (unstable)

**Version of Telegram Desktop:**
1.7.0

**Used theme**:
Not relevant

**Comment by 23rd** [comment]
You can use command line argument `-startintray`.

**Comment by perezmeyer** [comment]
Indeed it's there. The bug is still valid though: it would really be cool to have this documented and availabled in the UI.

**Comment by Aokromes** [comment]
#948

**Comment by perezmeyer** [comment]
Mm, yes, this bug should be merged with #948 then
