### ISSUE TITLE
Ubuntu 19 Qt Build Error

### ISSUE THREAD

**Issue by Alexa69** [telegramdesktop/tdesktop#6073]
Hi Guys
I want to compile the Telegram Desktop from source on New Ubuntu 19

I am following the instructions here : 
https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md

things go well until Qt part, it doesn't compile correctly 

qtextformat.o .obj/moc_qtextobject.o .obj/moc_qtextdocument.o .obj/moc_qtextimagehandler_p.o .obj/moc_qtexttable.o .obj/moc_qtextlist.o .obj/moc_qbrush.o .obj/moc_qpainter.o .obj/moc_qpdfwriter.o .obj/moc_qplatformbackingstore.o .obj/moc_qvalidator.o
make[3]: Leaving directory '/home/alex/tele/Libraries/qt5_6_2/qtbase/src/gui'
make[2]: Leaving directory '/home/alex/tele/Libraries/qt5_6_2/qtbase/src'
make[1]: *** [Makefile:46: sub-src-make_first] Error 2
make[1]: Leaving directory '/home/alex/tele/Libraries/qt5_6_2/qtbase'
make: *** [Makefile:44: module-qtbase-make_first] Error 2

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4275
