### ISSUE TITLE
Telegram will call you

### ISSUE THREAD

**Issue by advius** [telegramdesktop/tdesktop#6075]
Greetings,

I have got a question about Telegram log in,

When I log in to telegram via SMS message, on the screen show countdown witch description Telegram will call you in <countdown>.

Does it mean phone call with Telegram?

Thank you for your answer.
### Steps to reproduce
1. Log in to Telegram via SMS code

### Configuration
Ubuntu 18.04 Bionic Beaver 

**Version of Telegram Desktop:**
Telegram 1.7.0

**Comment by p0358** [comment]
A bot should call your phone number and read out the verification code using text-to-speech

**Comment by advius** [comment]
@p0358 Thank you very much for your answer.
