### ISSUE TITLE
Better build instruction for Linux?

### ISSUE THREAD

**Issue by mbasaglia** [telegramdesktop/tdesktop#6076]
The current build instructions at https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md assume Ubuntu 14.04, which is ancient; and require installing unstable versions of a bunch of libraries system-wide, which I'm not too keen on.

There are a few bugs on telegram desktop which I'd like to fix but can't do that if I can't even build it...

**Comment by xvitaly** [comment]
Building against system-wide libraries requires lots of patching of GYP scripts. Install version from Flatpak.

**Comment by mbasaglia** [comment]
My issue is that the build instruction make you install the libraries, does using flatpak avoid that? how does it handle the monkey-patched Qt library?

**Comment by xvitaly** [comment]
Flatpak version built againt Qt runtime.

**Comment by 23rd** [comment]
>and require installing unstable versions of a bunch of libraries system-wide, which I'm not too keen on.

Well, you can use docker for building.

**Comment by mbasaglia** [comment]
> Well, you can use docker for building.

Feels like a non-solution tbh, are all libraries statically linked? it would also make debugging very awkward because of the path differences.

Surely there must be a way to build telegram desktop without polluting your system

**Comment by xvitaly** [comment]
> Surely there must be a way to build telegram desktop without polluting your system

First you need to remove whole ugly GYP and rewrite building system to cmake, like already did in [Kepka fork](https://github.com/procxx/kepka).

**Comment by mbasaglia** [comment]
@xvitaly if I install Telegram from Flatpak how does that help me making changes to the telegram sources?

**Comment by mbasaglia** [comment]
If I try to compile disregarding the monkey patched libraries I have issues with the crl submodule, which seems to only support windows and apple but it's in the dependencies of other stuff

**Comment by john-preston** [comment]
@mbasaglia It supports Linux as well, with Qt thread pool as a backend.

**Comment by mbasaglia** [comment]
It just doesn't compile, I get to "#error "Configuration is not supported."" in crl_common_list.h which from what I've seen you avoid that branch by being on apple and have CRL_USE_DISPATCH defined or go to a different branch on that file by having the winapi

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4275
