### ISSUE TITLE
Mentioning someone in a group reveals how he/she is stored in private contact list

### ISSUE THREAD

**Issue by leonty** [telegramdesktop/tdesktop#6077]
### Steps to reproduce
1. Use iPhone client
2. In a group chat mention some member who is also in your contact list with own title using @ and clicking on him in the offered list.
2. Other participants will see this mentioning as exact title from your contact list (ex. "jerk from X department")

### Expected behaviour
The mentioned member name should be displayed for others using the name from thiers contact list. Or using his own nick in telegram.

### Actual behaviour
Other members see a message where the mentioned user is displayed as it's stored in the sender contact list. That's a reveal of private information.

### Configuration
iPhone8, iOS 12.2 

**Version of Telegram Desktop:**
5.7

**Used theme**:
default (classic)

**Comment by Aokromes** [comment]
this doesn't belong here. this is for telegram desktop (windows, macos, linux) not for telegram ios or native macos.
