### ISSUE TITLE
Missing "cancel" button on forced logout dialog

### ISSUE THREAD

**Issue by fmorato** [telegramdesktop/tdesktop#6079]
![Screenshot from 2019-06-01 22-08-25](https://user-images.githubusercontent.com/12693347/58753045-91babe00-84c1-11e9-898b-79993000ef33.png)

### Steps to reproduce
Not sure I was logged out. Happened after changing something in the local network.
Didn't find the logs.
This issue is anyway about the UX.

### Expected behaviour
There should be a `cancel` button on the dialog.

### Actual behaviour
There is no `cancel` button on the dialog.

### Configuration
**Operating system:**
Linux

**Version of Telegram Desktop:**
1.7 from flatpak

**Used theme**:
dark

**Comment by Aokromes** [comment]
well, the cancel button is only needed if you have secret chats, and telegram desktop doesn't support it.

**Comment by Aokromes** [comment]
now that i think a good reason to have this button can be you don't own anymore the phone number linked to the account and you only use telegram desktop.
