### ISSUE TITLE
Bug when I sent photos in portrait

### ISSUE THREAD

**Issue by rafaelmr2** [telegramdesktop/tdesktop#608]
Hi,

I'm using telegram desktop 0.8 in Fedora 21. When I send a photo in portrait, it goes in landscape.

**Comment by Alex131089** [comment]
+1, I guess the rotation information is in a tag (exif tag ?) and the compression is ignoring the tag when reducing the size.
Can you fix it ?

**Comment by auchri** [comment]
duplicate #907
