### ISSUE TITLE
update please the version

### ISSUE THREAD

**Issue by huezo** [telegramdesktop/tdesktop#6084]
**update please the version**

current
https://github.com/telegramdesktop/tdesktop/releases/tag/v1.7.3
=========

![Screenshot_20190603_095141](https://user-images.githubusercontent.com/15940634/58815765-6cbf6b80-85e5-11e9-9ddb-cebdfa01aa6a.png)

**Comment by john-preston** [comment]
Yeah, snapcraft build failed. I'll try to fix it.
