### ISSUE TITLE
Change the downloads path in the Windows Store version  

### ISSUE THREAD

**Issue by Abd354** [telegramdesktop/tdesktop#6086]
### Steps to reproduce
1. Install Telegram from Windows Store
2. Try to change the download path

### Expected behavior
There should be an option to change the download path to a custom path (like desktop or any another custom path) 

### Actual behavior
Such an option does not exist in the Windows Store version, the default download path is C:\Users\"The user name"\Downloads\Telegram Desktop

### Configuration
**Operating system: Windows 10 Pro x86 1903**

**Version of Telegram Desktop: 1.7.3**

**Used theme**: default

**Comment by Aokromes** [comment]
this is even possible on store aplications?

**Comment by Aokromes** [comment]
https://t.me/tgbetachat/215770 not possible.
