### ISSUE TITLE
Telegram Desktop stopped showing some unicode characters like Amharic since version 1.7.3

### ISSUE THREAD

**Issue by mikyz2012** [telegramdesktop/tdesktop#6089]
### Steps to reproduce
1. Use Telegram desktop version 1.7.3 or above
2. Write and send anything in Amharic.
3. View the message sent.

### Expected behavior
Written message should be viewable.

### Actual behavior
The Amharic characters are left blank.

### Configuration
**Windows 10, Intel(R) Core(TM) i3-3120M CPU @2.50GHz, 6GB RAM**

**Version of Telegram Desktop:Version 1.7.3 and up**

**Used theme: Midnight
![Screenshot (64)](https://user-images.githubusercontent.com/42240194/58853546-6263a700-86a3-11e9-9369-6c184a0c7ac5.png)

**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
Amharic never worked for me on windows 10....

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4072

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4072#issuecomment-425806123
