### ISSUE TITLE
Telegram Desktop(macOS) not reopen his window in the same monitor.

### ISSUE THREAD

**Issue by nickfassis** [telegramdesktop/tdesktop#6090]
### Steps to reproduce
1. Open the telegram in a macOs Machine.
2. Move the window to the second monitor.
3. Close the app.
4. Reopen the app.

### Expected behaviour
The window will open on the same monitor i have closed, and on the same location.

### Actual behaviour
The window opens on the same location but on the first monitor.

### Configuration
macOS Mojave(10.14.5)

Telegram Desktop 1.7.3

Regular theme

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2840
