### ISSUE TITLE
Window turns black when moving it to second screen

### ISSUE THREAD

**Issue by Alge** [telegramdesktop/tdesktop#6091]
### Steps to reproduce
1. start app
2. move to secondary screen

### Expected behaviour
The window should work normally on the second screen

### Actual behaviour
All content of the window becomes black

### Configuration
macOS Mojave (10.14.4)

**Version of Telegram Desktop:**
1.7
**Used theme**:
Default

**Comment by serebryakov-av** [comment]
I also have very same bug:
1. Open the application.
2. Hide the application.
3. Close a MacBook.
4. Open it after a long period (usually 10-20 minutes) and unlock.
3. Plug a secondary screen.
5. Show the application.

-> Window gets black.
