### ISSUE TITLE
[Feature Request] Open Specific Chat/Contact on Startup (Command-line Switch)

### ISSUE THREAD

**Issue by hced** [telegramdesktop/tdesktop#6093]
I'd like to be able to quickly open a specific chat/contact window when starting up Telegram. I've found [this page](https://github.com/telegramdesktop/tdesktop/wiki/Command-Line-Switches) that specifies currently available switches, but I'd like to see this implemented to be able to e.q. add desktop shortcuts for favorite contacts.

**Comment by 23rd** [comment]
As far as I know you can create shortcut file with url for this purpose. For example `Telegram.lnk` file with `tg://stickers` local url.
