### ISSUE TITLE
Desctop client crashes when start playing music after last update

### ISSUE THREAD

**Issue by 8l4ckm1rr0r** [telegramdesktop/tdesktop#6094]
### Steps to reproduce
1. Upload any music file 
2. Click on them to play
3. Crash.

### Expected behaviour
Music starts to play

### Actual behaviour
Telegram crashes

### Configuration
**Operating system:** Windows 10 with latest updates

**Version of Telegram Desktop:** 1.7.4 - beta

**Used theme**: Midnight
[crash report.txt](https://github.com/telegramdesktop/tdesktop/files/3256351/crash.report.txt)

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
Is it correct that you upload a file, then move or delete it from the place from where you've uploaded it and then click play?

**Comment by 8l4ckm1rr0r** [comment]
> 
> 
> Is it correct that you upload a file, then move or delete it from the place from where you've uploaded it and then click play?

Absolutely correct.

**Comment by john-preston** [comment]
Ok, thanks! I'll fix that in the 1.7.5 beta version today.

**Comment by 8l4ckm1rr0r** [comment]
> 
> 
> Ok, thanks! I'll fix that in the 1.7.5 beta version today.

Thanks a lot, otherwise I had to roll back to the previous version.
