### ISSUE TITLE
Message is not marked read if it is a video reply

### ISSUE THREAD

**Issue by belegnar** [telegramdesktop/tdesktop#6096]
### Steps to reproduce
1. Publish message to supergroup
2. Answer with video
3. Read supergroup

### Expected behaviour
@ sign disappeared

### Actual behaviour
@ sign stay in place

### Configuration
Linux 4.4.0-140-generic #166~14.04.1-Ubuntu SMP Sat Nov 17 01:52:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Version: 1.7.3

Theme: from gallery #29
![1](https://user-images.githubusercontent.com/263551/58968829-5d941580-87bf-11e9-8566-9f1b4675035a.png)

**Comment by john-preston** [comment]
@belegnar It is considered unread while it was not watched.

**Comment by belegnar** [comment]
> @belegnar It is considered unread while it was not watched.

thx a lot! but why telegram on mobile do it another way?
