### ISSUE TITLE
Waveforms are rendered differently between apps

### ISSUE THREAD

**Issue by Lonami** [telegramdesktop/tdesktop#6099]
I would guess waveforms are supposed to all look the same across applications, but that's not the case.
![text858](https://user-images.githubusercontent.com/6297805/59019622-b065df80-8848-11e9-88fa-0559b4cc4920.png)

So my question is, which implementation is correct?

**Comment by Jeepeo** [comment]
Tg X better

**Comment by Lonami** [comment]
Still not consistent, at least with Telegram X.

**Comment by Aokromes** [comment]
well, it matches Telegram, the thing is, it matches telegram ios? if yes, this issue can be closed.

**Comment by Lonami** [comment]
I don't have a iOS device to test this on (and had Telegram Android uninstalled so I didn't try there), so someone else will have to confirm that.

**Comment by Lonami** [comment]
There's been sort of an improvement but still not exactly the same:

![image](https://user-images.githubusercontent.com/6297805/97078092-ae412400-15e9-11eb-8deb-fcf097660e8e.png)

Good enough I guess?
