### ISSUE TITLE
Support hotkeys and close chat with Esc

### ISSUE THREAD

**Issue by rampitec** [telegramdesktop/tdesktop#61]
One thing really missing on Windows in the program - a way to quickly close chat window with Esc.

That would be also cool to restore chat window with a hotkey. For example I was using Alt-~ to restore miranda, and that was very efficient.

**Comment by telegramdesktop** [comment]
Escape was done.

**Comment by rampitec** [comment]
I have just updated the app on Windows, Escape support is still not there. It closes chat, not the chat window, though that is here for a while already.

**Comment by cjmaxik** [comment]
@rampitec +1

**Comment by aleksey-khokhryakov** [comment]
+1 for closing chat by pressing Escape key

**Comment by splintor** [comment]
Would also be nice if Esc closed the chat window - see #1367.
