### ISSUE TITLE
[Feature Request] A way to easily check all recent mentions

### ISSUE THREAD

**Issue by starg09** [telegramdesktop/tdesktop#610]
I know it's already posible searching for "@username", but it would be nice to have a quick button to acces that mentions list, and maybe with a counter so we know we've been mentioned while we've been offline. That counter would clear only when you check on that list, so even if you open a group chat, which may have over 2k unread messages, you still know there's some part where they wanted you to read :)

**Comment by SniperRus** [comment]
+1

**Comment by zaz600** [comment]
+1 mentions and replies

**Comment by jtojnar** [comment]
Something like this:

![screenshot](https://cloud.githubusercontent.com/assets/705123/11164393/07a10aa0-8aef-11e5-82c5-256490a3451e.png)

Clicking the mentions link would search for your @ handle (optimally only for the unread mentions).

**Comment by SniperRus** [comment]
up

**Comment by theus** [comment]
A notification center...

**Comment by zaz600** [comment]
@theus after reboot?...
six months later?...

**Comment by theus** [comment]
@zaz600  I don't know if API allow this resource, but I think that Telegram knows if message was read or not. Something like this: the notification of reply/mention would stay in the center until you read.

**Comment by zaz600** [comment]
History is also needed, not only unread

**Comment by mahdiG** [comment]
Also you can change the color of unread messages if they include mentions.

**Comment by Aokromes** [comment]
already implemented no?

**Comment by stek29** [comment]
Search for `#m`
