### ISSUE TITLE
Problem with openssl build using MSVC build instructions

### ISSUE THREAD

**Issue by rasoulcpu** [telegramdesktop/tdesktop#6102]
in MSVC build instruction , openssl part, there is `git checkout OpenSSL_1_0_1-stable` but openssl git repo has not any `OpenSSL_1_0_1-stable` branch

perhaps it should be `OpenSSL_1_0_1`, but after running `nmake -f ms\nt.mak` we have this error:
```
 Assembling: tmp32\x86cpuid.asm
tmp32\x86cpuid.asm(155) : error A2022:instruction operands must be the same size
```

**Comment by 23rd** [comment]
Can't reproduce.
[This branch](https://github.com/openssl/openssl/tree/OpenSSL_1_0_1-stable) exists and I able to switch to it.
