### ISSUE TITLE
Add "include in unread count" chat-specific setting

### ISSUE THREAD

**Issue by Intenditore** [telegramdesktop/tdesktop#6105]
The issue:
There are too many chats we don't really care of. They constantly generate +1 to unread counter. Checking off "Include muted chats in unread" solves the problem only partially - this way we can't keep tracking the chats we care.
The solution:
Add a chat-specific option "include in unread count" which will override "include muted chats in unread count" for a particular chat/channel. 
That would be very handy option

**Comment by neesti** [comment]
This feature is very needful. Please add this feature. 
Thank you.

**Comment by neesti** [comment]
I think adding this feature is more important after version 2.0

> This feature is very needful. Please add this feature.
> Thank you.

**Comment by alekseyl1992** [comment]
the absence of the feature stops me from joining public group chats and channels :(
because I have all group chats muted, but I want work/personal chats to be included in unread count and the opposite for public chats/channels

**Comment by ilya-fedin** [comment]
#3916
