### ISSUE TITLE
Telegram Desktop shows Windows native titlebar

### ISSUE THREAD

**Issue by Q0** [telegramdesktop/tdesktop#6106]
### Steps to reproduce
1. Run TG
2. Minimize the client, maximize
3. Focus and click titlebar

![aU8eTflwyA](https://user-images.githubusercontent.com/15221660/59082233-50406d80-891c-11e9-9bf2-29ca317482a5.gif)

### Expected behaviour
Nothing

### Actual behaviour
Windows Native titlebar appears

### Configuration
**Operating system:**
Win 7
**Version of Telegram Desktop:**
1.7.6 portable
**Used theme**:
midnight (night mode)
<details><summary><b>Logs</b>:</summary>

> [2019.06.07 10:00:12] Launched version: 1007006, install beta: [TRUE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
> [2019.06.07 10:00:12] Executable dir: C:/Portable/Telegram/, name: Telegram.exe
> [2019.06.07 10:00:12] Initial working dir: C:/Portable/Telegram/
> [2019.06.07 10:00:12] Working dir: C:/Portable/Telegram/
> [2019.06.07 10:00:12] Command line: C:\Portable\Telegram\Telegram.exe -noupdate
> [2019.06.07 10:00:12] Executable path before check: C:/Portable/Telegram/Telegram.exe
> [2019.06.07 10:00:12] Logs started
> [2019.06.07 10:00:12] Connecting local socket to Global\b9d9d1705d42070756d25f9e36ed2b70-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
> [2019.06.07 10:00:12] This is the only instance of Telegram, starting server and app...
> [2019.06.07 10:00:12] Moved logging from 'C:/Portable/Telegram/log_start0.txt' to 'C:/Portable/Telegram/log.txt'!
> [2019.06.07 10:00:12] Primary screen DPI: 96
> [2019.06.07 10:00:12] App Info: reading settings...
> [2019.06.07 10:00:12] App Info: reading encrypted settings...
> [2019.06.07 10:00:12] Lang Info: Loaded cached, keys: 2325
> [2019.06.07 10:00:12] OpenAL Logging Level: (not set)
> [2019.06.07 10:00:12] Audio Playback Devices: OpenAL Soft
> [2019.06.07 10:00:12] Audio Playback Default Device: OpenAL Soft
> [2019.06.07 10:00:12] Audio Capture Devices: OpenAL Soft on РњРёРєСЂРѕС„РѕРЅ (Realtek High Definition Audio)
> [2019.06.07 10:00:12] Audio Capture Default Device: OpenAL Soft on РњРёРєСЂРѕС„РѕРЅ (Realtek High Definition Audio)
> [2019.06.07 10:00:12] App Info: reading map...
> [2019.06.07 10:00:12] App Info: bad decrypt key, data not decrypted - incorrect password?
> [2019.06.07 10:00:12] App Info: could not decrypt pass-protected key from map file, maybe bad password...
> [2019.06.07 10:00:12] Window Shadow: 1, 1, 3, 4, 6, 9, 13, 18, 24, 31, 38, 46
> [2019.06.07 10:00:31] App Info: reading map...
> [2019.06.07 10:00:31] App Info: reading encrypted map...
> [2019.06.07 10:00:31] App Info: reading encrypted user settings...
> [2019.06.07 10:00:31] App Info: encrypted user settings read.
> [2019.06.07 10:00:31] App Info: reading encrypted mtp data...
> [2019.06.07 10:00:31] MTP Info: read keys, current: 6, to destroy: 0
> [2019.06.07 10:00:31] Map read time: 39
> [2019.06.07 10:00:31] Export Info: Destroy top bar by controller removal.
> [2019.06.07 10:00:52] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:00:58] App Info: writing encrypted user settings...
> [2019.06.07 10:01:41] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:02:36] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:03:56] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:03:56] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:03:56] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:03:56] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:04:24] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:04:34] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:04:48] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:05:02] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:05:02] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:05:21] App Info: writing encrypted user settings...
> [2019.06.07 10:05:37] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:05:39] Skipping message, because it is already in blocks!
> [2019.06.07 10:06:37] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:06:37] Audio Info: recreating audio device and reattaching the tracks
> [2019.06.07 10:06:39] Audio Info: Closing audio playback device.
> [2019.06.07 10:07:29] Skipping message, because it is already in blocks!
> [2019.06.07 10:07:39] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:07:39] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:08:00] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:08:00] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:08:22] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:08:22] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:08:36] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:09:22] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:09:50] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:09:50] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:10:01] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:10:36] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:10:47] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:11:41] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:11:41] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:12:54] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:13:41] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:14:15] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:14:15] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:14:30] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:14:30] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:14:40] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:14:50] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:15:28] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:15:47] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:16:17] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:16:39] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:16:43] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:16:45] Skipping message, because it is already in blocks!
> [2019.06.07 10:16:55] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:16:55] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:17:50] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:17:50] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:18:04] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:18:06] Skipping message, because it is already in blocks!
> [2019.06.07 10:18:15] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:19:11] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:19:11] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:19:11] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:19:39] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:19:43] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:20:39] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:20:51] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:21:36] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:21:36] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:21:42] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:22:17] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:23:02] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:23:02] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:23:47] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:24:17] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:24:34] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:25:48] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:25:48] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:25:58] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:26:35] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:27:02] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:27:13] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:27:50] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:27:55] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:29:16] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:29:16] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:29:37] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:29:47] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:30:03] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:30:03] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:30:13] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:30:59] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:30:59] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:31:50] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:32:00] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:32:29] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:32:40] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:33:59] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:33:59] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:33:59] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:34:31] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:34:36] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:35:21] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:35:31] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:36:52] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:37:54] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:38:10] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:38:14] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:38:44] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:40:15] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:40:25] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:41:00] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:41:00] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:41:00] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:41:42] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:41:42] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:41:49] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:41:49] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:42:09] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:43:34] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:44:27] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:44:43] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:45:42] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:45:42] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:45:55] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:46:08] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:46:22] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:46:37] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:47:46] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:48:14] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:48:43] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:49:41] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:49:41] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:49:46] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:49:59] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:50:09] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:50:37] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:50:50] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:51:38] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:51:50] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:52:39] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:53:44] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:54:40] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:55:15] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:56:00] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:56:00] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:56:10] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:56:10] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:57:31] API Warning: not loaded minimal channel applied.
> [2019.06.07 10:59:52] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:00:19] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:03:53] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:04:56] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:06:35] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:07:21] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:08:06] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:08:06] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:08:43] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:09:59] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:10:11] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:11:30] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:12:19] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:13:27] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:13:44] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:20:10] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:21:45] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:22:32] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:23:39] Skipping message, because it is already in blocks!
> [2019.06.07 11:23:50] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:25:58] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:27:19] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:27:39] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:29:20] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:29:31] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:30:02] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:30:10] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:31:37] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:31:37] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:35:49] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:36:35] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:36:47] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:37:20] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:37:53] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:38:47] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:39:00] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:39:37] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:39:47] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:40:16] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:46:25] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:47:20] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:48:22] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:48:32] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:48:53] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:50:10] App Info: writing encrypted user settings...
> [2019.06.07 11:50:36] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:50:45] API Warning: not loaded minimal channel applied.
> [2019.06.07 11:50:56] App Info: writing encrypted user settings...
> [2019.06.07 11:51:15] App Info: writing encrypted user settings...
> [2019.06.07 11:51:58] App Info: writing encrypted user settings...

</details>

**Comment by pneumotube** [comment]
Yeah, I have this issue too on the latest build (1.7.6).

**Comment by andreylc** [comment]
I confirm. I also have a problem with the top bar. Telegram Desktop 1.7.6 beta. Windows 7.
[Screenshot](https://i.imgur.com/qRJxsfX.png)

**Comment by john-preston** [comment]
@andreylc Yeah, thanks. I'll fix that in the next version.
