### ISSUE TITLE
Out of the text of the page! [Closed-Moved]

### ISSUE THREAD

**Issue by rasubuntu** [telegramdesktop/tdesktop#611]
Hi there.
When using the telegram version of Android, I encountered an interesting case.
When the width of the text was written, the text box is made out of the page.
Here is the text like this:
----ubuntu@----ubuntu:~$ vnstat -h
http://s4.picofile.com/file/8179549684/photo_2015_03_28_23_16_24.jpg

MDPI, Android 4.2.2 :)

**Comment by auchri** [comment]
This is the desktop version of telegram

**Comment by rasubuntu** [comment]
Oh!
Sorry.. I do not remember :D
Thank You

**Comment by Katzen-Gott** [comment]
@rasubuntu you can close the issue (there is 'comment and close' button under the comment box).
