### ISSUE TITLE
Volume adjustment with TouchBar got stuck when TD is in focus and playing audio/video

### ISSUE THREAD

**Issue by k06a** [telegramdesktop/tdesktop#6110]
I am having this bug for 1 year.

### Steps to reproduce
1. Start audio or video in TD
2. Try to change volume by dragging volume indicator (with single gesture, without first tap)

### Expected behaviour
Volume should be changes

### Actual behaviour
Volume indicator got stuck

### Configuration
**Operating system:** macOS 10.14.5

**Version of Telegram Desktop:** 1.7.3

**Used theme**:Default

**Comment by john-preston** [comment]
@k06a I guess it is macOS 10.14.5, not 10.15.5?

**Comment by k06a** [comment]
@john-preston sure)) Thanks for the fast response, I am having this issue more than 1 year with different versions of TD and macOS.

**Comment by john-preston** [comment]
@k06a Are you sure you're talking about Telegram Desktop? It got touchbar support only last month, in the latest versions.

**Comment by k06a** [comment]
@john-preston yep, I am talking about system volume indicator. I will try to record a video of this bug.

**Comment by k06a** [comment]
![ezgif com-optimize-3](https://user-images.githubusercontent.com/702124/59145898-d929d880-89f2-11e9-8717-6cd40e99658f.gif)

**Comment by john-preston** [comment]
@k06a But this is a system control :( I have no idea why it can freeze that way, it is not Telegram Desktop code which controls this slider.

**Comment by k06a** [comment]
@john-preston sure it’s system, but this bug happens only while I play audio/video in Telegram Desktop :(

**Comment by 23rd** [comment]
Unfortunately, I can't reproduce your problem.
Perhaps this behavior occurs not only in the Telegram Desktop?

**Comment by k06a** [comment]
@23rd yep, I am using lots of different software for chatting, calling, playing and this bug happens in TD but may not happen when I try to reproduce second time. But since TD relaunch first try usually reproduces a bug.
