### ISSUE TITLE
[Feature request] folderised pinned messages

### ISSUE THREAD

**Issue by Hassan-Fa** [telegramdesktop/tdesktop#6111]
instead of one message being pinned , would be so much more useful if could create new folders on a narrow tab exactly the way pinned messages are shown , and save messages in them,
exactly like bookmark tab in firefox browser. ❤️

**Comment by SmartManoj** [comment]
This has to be implement in the Telegram API.

**Comment by SmartManoj** [comment]
https://t.me/tgbeta/4217

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
