### ISSUE TITLE
libappindicator GTK dependency verbository

### ISSUE THREAD

**Issue by pzillmann** [telegramdesktop/tdesktop#6112]
### Steps to reproduce
1. Make sure libappindicator.so is missing from your system
2. start Telegram client

### Expected behaviour
Error Message should show up that libappindicator.so is missing or that the user should install libappindicator-gtk3 package

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**
Manjaro Linux

**Version of Telegram Desktop:**
Newest

On GTK systems the client forks itself and in the initialization process is no indicator that libappindicator.so is missing. It is not linked into the software so that ldd could detect that dependency.

A clear message is missing before the program exits.
No window spawns.

Edit: found the logfile under ~/.local/share/TelegramDesktop/log.txt which states
```
[2019.06.08 12:40:53] Could not load 'ayatana-appindicator3' with version 1 :(
[2019.06.08 12:40:53] Error: failed to load 'gdk_x11_drawable_get_xdisplay' function!
```

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after near 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
