### ISSUE TITLE
Cannot record audio-message with connected wireless device.

### ISSUE THREAD

**Issue by YGromyk** [telegramdesktop/tdesktop#6113]
### Steps to reproduce
1. Connect to wireless speakers or headphones.
2. Try to record an audio message.
3. Send it.

### Expected behavior
Normal audio speed and actual duration of the audio.
### Actual behavior
The timer shows the wrong time during the recording and the audio is unlistenable. 

### Configuration
**Operating system:**
macOS Mojave
Version: 10.14.5 (18F203)
**Version of Telegram Desktop:**
5.3 (171638) AppStore
**Used theme**:
Mojave Dark

**Comment by 23rd** [comment]
Sorry, you are using the Mac native client, not the Telegram Desktop.
https://github.com/telegramdesktop/tdesktop/issues/5921#issuecomment-483126605

**Comment by YGromyk** [comment]
@23rd sorry, my bad
