### ISSUE TITLE
Let the creator of a supergroup delete all of his/her own messages

### ISSUE THREAD

**Issue by letMyDogGoPls** [telegramdesktop/tdesktop#6116]
### Steps to reproduce
1. Create a supergroup
2. Send some messages
3. Try to delete all messages at once

### Expected behaviour
The creator of a supergroup should have the "Delete all from this user" button on his/her own messages. At the moment no one can delete them all at once, only one by one. Messages from all other users (admins or normal users), can be deleted all at once, but not messages from the creator. There should be a way for the owner to delete all of his/her own messages. 

### Actual behaviour
The creator's messages can only be deleted one by one (up to 100 at a time), and not all at once. 

### Configuration
**Operating system:** Windows 10, 64 bit

**Version of Telegram Desktop:** 1.7.3

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this must be done api side.
