### ISSUE TITLE
Appveyor builds are failing constantly

### ISSUE THREAD

**Issue by Ashesh3** [telegramdesktop/tdesktop#6118]
### Steps to reproduce
1.  Trigger a build at appveyor with master or dev branch

### Expected behaviour
The build should succeed

### Actual behaviour
Appveyor builds have been failing since past 13 days. 

```
C:\TBuild\tdesktop\Telegram\SourceFiles\apiwrap.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj [C:\TBuild\tdesktop\Telegram\Telegram.vcxproj]
  C:\TBuild\tdesktop\Telegram\Telegram.vcxproj(1350,5): error MSB3073: The command "call ninja.exe -C ..\out\Debug\ -k0 Telegram" exited with code 1.
```
### Configuration
appveyor.yml

### Source
https://ci.appveyor.com/project/telegramdesktop/tdesktop/history

https://ci.appveyor.com/project/telegramdesktop/tdesktop/builds/25161768

**Comment by john-preston** [comment]
@Ashesh3 As I see, Appveyor still doesn't support Visual Studio 2019. This error doesn't happen in VS2019. I was hoping they'll add it and I won't have to add '/bigobj' flag.

**Comment by Ashesh3** [comment]
I don't know if this helps but they do have option to select VS 2019 in their build image settings, so maybe they do support it. 

![image](https://user-images.githubusercontent.com/3626859/59192682-e71d5c00-8ba0-11e9-9fc0-cf0f316d54a9.png)


> @Ashesh3 As I see, Appveyor still doesn't support Visual Studio 2019. This error doesn't happen in VS2019. I was hoping they'll add it and I won't have to add '/bigobj' flag.

**Comment by Ashesh3** [comment]
@john-preston Hey, do u where  can i add `/bigobj` flag if i decide to fork this repo and build with appveyor? Seems somewhere inside generate.py since that generates sln file.. but i am not really sure.
Thanks!

**Comment by 23rd** [comment]
@Ashesh3 [https://github.com/Forkgram/tdesktop/commit/9f736964dfb6545bb15b0eb93d545d593316287e](This commit) will fix your appveyor build.

**Comment by Ashesh3** [comment]
@23rd yep! did that! Thanks! works great!

**Comment by 23rd** [comment]
I think now it can be closed.
