### ISSUE TITLE
High idle CPU usage related to application state when window is closed

### ISSUE THREAD

**Issue by N8Z7JMYLU** [telegramdesktop/tdesktop#6119]
Referencing the already ongoing issues here https://github.com/telegramdesktop/tdesktop/issues/5181 & here https://github.com/telegramdesktop/tdesktop/issues/5295 the high usage from standby is directly influenced by how the Telegram window has been minimized. This behavior continues during normal runtime.

-----
Closing the Telegram window to tray **without** a chat being open, resuming from standby will cause the above mentioned high CPU usage and inability to reconnect for several minutes.
![Window-Visible-Usage](https://user-images.githubusercontent.com/29806150/59193872-69008b80-8b87-11e9-82a3-6d3479ac3d54.jpg)

Closing the Telegram window to tray while **having a chat open**, the idle thread usage drops and also inhibits this bug from manifesting.
![Window-Closed](https://user-images.githubusercontent.com/29806150/59193869-630aaa80-8b87-11e9-939d-85b6006d323e.jpg)

After resuming from standby, the main window has to be brought up and closed again while a chat is open for the active threads to "calm down" and remain there. This has to be repeated every time it's minimized/maximized.

### Configuration
**Operating system:** Windows 10 1809

**Version of Telegram Desktop:** 1.7.7.0

**Used theme**: Default

**Comment by chengluyu** [comment]
I encountered the same problem on macOS Mojave 10.14.5. The app eats more than 500 MB memory even in idle status.
![image](https://user-images.githubusercontent.com/2239547/59327583-8581fc80-8d1c-11e9-9a50-1ff983d93303.png)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com

**Comment by GitLad** [comment]
FIX IT
