### ISSUE TITLE
Minimal zoom level for “-scale ...” factor

### ISSUE THREAD

**Issue by Twilightssuperb** [telegramdesktop/tdesktop#6120]
Tried to experiment with minimal “-scale ...” argument for 1366x768 screen. 75 — Telegram runs OK. 70 — no decreased UI, runs with default 100% zoom. Is it a bug or a feature?

**Comment by john-preston** [comment]
@Twilightssuperb Yeah, 75% was set as a minimal value, below that need some additional work for it not to crash, so it was considered unnecessary.

**Comment by Twilightssuperb** [comment]
Understood, thx.
