### ISSUE TITLE
The client crashes when you select inline result with a video

### ISSUE THREAD

**Issue by tuscen** [telegramdesktop/tdesktop#6122]
### Steps to reproduce
1. Start an inline query in a supergroup 
2. Receive an inline result with mpeg4 gif
3. Try to select it

### Expected behaviour
The selected mpeg4 gif should be sent to the chat

### Actual behaviour
The client crashes

### Configuration
**Operating system:** macOS 10.14.5, Windows 10 1903 Build 18362.145

**Version of Telegram Desktop:** 1.7.7

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
next time you get a crash can you click send crash report and put crash id here?

**Comment by tuscen** [comment]
I totally forgot about this issue. It seems to have been fixed in later versions because I haven't seen it lately in exactly the same context (it's from a test suit of a bot api library I'm maintaing).
