### ISSUE TITLE
Autoplay GIFs broken for manually downloaded GIFs until restart

### ISSUE THREAD

**Issue by Remu-rin** [telegramdesktop/tdesktop#6123]
### Steps to reproduce
1. Disable GIFs auto download. Autoplay GIFs should be enabled
2. Go to chat with a new GIF, click to download
3. Switch to another chat and switch back to first

### Expected behaviour
Downloaded GIFs should autoplay

### Actual behaviour
Manually downloaded GIFs autoplay until you switch to another chat. Then they are stopped and looks like not downloaded. They will become normal after tdesktop restart

### Configuration
**Operating system:** Windows

**Version of Telegram Desktop:** 1.7.7

**Comment by mehti1367** [comment]
same here :

![ezgif-1-eb7858135eb4](https://user-images.githubusercontent.com/34035991/59433495-dc600280-8dfe-11e9-8bf1-56b24509e5f9.gif)
