### ISSUE TITLE
Text mention links cannot be copied

### ISSUE THREAD

**Issue by nyuszika7h** [telegramdesktop/tdesktop#6125]
### Steps to reproduce
1. Find a message with a text mention
2. Right click the link
3. Click "Copy Link"

### Expected behaviour
The text mention's link (`tg://user?id=USERID`) should be copied.

### Actual behaviour
The message's link is copied instead.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.7.7

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by john-preston** [comment]
@nyuszika7h There is no links to users without usernames in Telegram =(

**Comment by nyuszika7h** [comment]
Bot API has `tg://user?id=USERID` like I mentioned, can't that be used?

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by RememberTheAir** [comment]
Yes
