### ISSUE TITLE
[Feature request] scriptable interface

### ISSUE THREAD

**Issue by vinipsmaker** [telegramdesktop/tdesktop#6127]
Is there interest in making Telegram interface scriptable through D-Bus? It could help close the gap between Telegram and IRC.

A few useful commands for a start:

* Event: new message
* Send message
* List chats
* Search/history-navigation

**Comment by henning-schild** [comment]
There are a ton of libraries i.e here on github. (i.e.https://github.com/Adi3000/tgl)  You probably do not want such a feature within this app, it is a weird beast bringing its own Qt etc.
What is also fun are the bots, again with libs for all common scripting languages available in many places.
