### ISSUE TITLE
Uploading from a different file system

### ISSUE THREAD

**Issue by ericbrandwein** [telegramdesktop/tdesktop#6128]
### Steps to reproduce
1. Upload a file from an NTFS file system while in an ext4 file system

### Expected behaviour
The file is uploaded

### Actual behaviour
The upload fails

### Configuration
**Operating system:** Ubuntu

**Version of Telegram Desktop:** 1.7.3

**Used theme**: Midnight

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by vitlav** [comment]
No log, no details... There are no reasons to fail with a different file system during upload. Can check read the file with other program?

**Comment by Aokromes** [comment]
@ericbrandwein

**Comment by Aokromes** [comment]
no answer for over a month, closing.
