### ISSUE TITLE
When using native notifications, the new message notifications should be low priority

### ISSUE THREAD

**Issue by colomar** [telegramdesktop/tdesktop#6129]
### Steps to reproduce
1. In Settings, select "Notifications -> Use native notifications"
2. Have a new message arrive

### Expected behaviour
Notifications about new messages should have the priority set to "low", since the system tray icon informs about the number of unread messages anyway.

### Actual behaviour
The notifications arrive with normal priority, meaning that e.g. in KDE Plasma they pile up in the notification history.

### Configuration
**Operating system:**
KDE neon (based on Ubuntu 18.04)

**Version of Telegram Desktop:**
1.7.3

**Comment by colomar** [comment]
When posting this issue, I didn't have in mind that the tray icon is optional, so setting the priorities to low might actually not be the best idea, after all.

**Comment by magnus-gross** [comment]
Yeah, I am also not sure for what is the right choice to make here.
I have made a working test implementation at https://github.com/magnus-gross/tdesktop/tree/lowUrgency, which doesn't collect the notifications in the history widget, but this should at least be consistent on all platforms.

@john-preston If you decide to go this way, I can make a PR or feel free to merge from my branch directly. :)

**Comment by Pointedstick** [comment]
In my KDE Plasma setup, I have my chat apps like Telegram set up not show up in the history, mimicking the effect of setting the priority to low. I quite like it, personally.

If this is done, you might want to consider using the default priority for messages that mention your username. That might be pretty nice, actually.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by ilya-fedin** [comment]
> this issue is still valid?

Yes, the priority is still default (and will be)

**Comment by Pointedstick** [comment]
> > this issue is still valid?
> 
> Yes, the priority is still default (and will be)

If you're not going to change this, maybe close the bug report?

**Comment by magnus-gross** [comment]
Yes I also think this can be closed, as you can simply override the notifications priority level in KDE if you don't like Telegram's default.
