### ISSUE TITLE
Writing a message to a person picked from a group, chat disappear

### ISSUE THREAD

**Issue by fmarzolo** [telegramdesktop/tdesktop#6132]
### Steps to reproduce
1. Open a group, ensure you not have a specific test person contact in address book
2. click on profile of test person, click "send message" to contact directly this person
3. type the message

### Expected behaviour
I expect that the chat with this person will open and I can see the just typed message appear

### Actual behaviour
The client seems to lost focus, message disappear after pressing Enter, none chat has focus, and if I click on the contact I can't see the just typed message. When I repeat a second time the message, all run fine.

### Configuration
Windows 10 (1809)

**Version of Telegram Desktop:**
1.7.7

**Used theme**:none

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by fmarzolo** [comment]
I think this was resolved
thank you


Il giorno gio 4 giu 2020 alle ore 11:02 Aokromes <notifications@github.com>
ha scritto:
