### ISSUE TITLE
Notification in action center is not cleared even if the messages are read and unread counter is zero

### ISSUE THREAD

**Issue by itsmekmk7** [telegramdesktop/tdesktop#6134]
### Steps to reproduce
1. Get a message
2. Open it from the app, not from the notification in the action center

### Expected behaviour
The action center notification should be cleared when the messages are read
### Actual behaviour
Action center notification are not cleared even if messages are read

### Configuration
Windows 10, version 1903

Telegram Version **1.7.7**

**Default Theme**:

**Comment by tooomm** [comment]
Yes, that issue is very annoying with 1.8.8. The constantly wrong notification status on the windows action center icon is just confusing.

**Comment by tooomm** [comment]
Yes, it is still valid
