### ISSUE TITLE
Display smileys bigger like on mobile (when smiley-only msg)

### ISSUE THREAD

**Issue by tooomm** [telegramdesktop/tdesktop#6138]
### Expected behaviour
When the message contains only smileys, display them bigger to stress emotions like users are used to from mobile.

### Actual behaviour
Normal sized smiley is displayed.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.7.3

**Used theme**: Default

**Comment by 23rd** [comment]
See #2804 and #3520.
