### ISSUE TITLE
Ability to interact with received contact details

### ISSUE THREAD

**Issue by tooomm** [telegramdesktop/tdesktop#6139]
### Expected behaviour
Receiving a shared contact / contact details displays a tile with the name and number. A user should be able to click on that and interact with that information like sending a message or adding to contacts.

### Actual behaviour
No interaction possible. One can not click the tile, write a mesage or add to contacts etc.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.7.3

**Used theme**: Default

**Comment by john-preston** [comment]
@tooomm When there is no actions it means that this phone number is not registered on Telegram, so you can't do anything with that number in Telegram Desktop.

**Comment by tooomm** [comment]
@john-preston When I added that same phone number to the contacts manually I could start chatting with my friend. ;)
Could the problem be that you have to enter a phone number with the country code (like +44 for example), but the number got send to me without it... which should be the normal case because people don't save numbers with local country codes as long as it's no foreign number?

**Comment by john-preston** [comment]
@tooomm Yes, I guess server didn't recognize your friend by the short number.

**Comment by tooomm** [comment]
Well, on mobile the same number/contact tile can be interacted with.

**Comment by SmartManoj** [comment]
Could you provide a ScreenShot?

**Comment by tooomm** [comment]
Same chat, same contact:

- Telegram Desktop (non clickable, non interactable):
![tile_desktop](https://user-images.githubusercontent.com/9874850/60037731-a64e3880-96b2-11e9-92d4-1355df7adaf0.png)

- Telegram iOS (clickable, interactable)
![tile_mobile](https://user-images.githubusercontent.com/9874850/60037735-a817fc00-96b2-11e9-83d4-80f78424e027.png)

**Comment by SmartManoj** [comment]
Only this contact or all

**Comment by tooomm** [comment]
That might be the first contact I received... :)

**Comment by SmartManoj** [comment]
is the contact user joined on telegram when u receive it?

**Comment by tooomm** [comment]
Yes. He uses Telegram already

**Comment by SmartManoj** [comment]
the sender may forward contact from bot.

**Comment by tooomm** [comment]
What do you mean? The contacts he send me was not a bot contact.
And I'm pretty sure the user just used the share option as he is not an experienced or tech-savy user.

**Comment by SmartManoj** [comment]
Could you confirm again ?

**Comment by SmartManoj** [comment]
Send a contact to ur saved message and check

**Comment by tooomm** [comment]
It works with different numbers. So the problem goes probably back to

>Could the problem be that you have to enter a phone number with the country code (like +44 for example), but the number got send to me without it... which should be the normal case because people don't save numbers with local country codes as long as it's no foreign number?

On Telegram Desktop, only numbers with international country codes are recognized.
On Telegram iOS it works without as well.

**Comment by SmartManoj** [comment]
On mobile client we need to sync with phone contacts  . So they have like this.
I think Ur friend send contact from the phone contacts  and not shared from user profile

**Comment by SmartManoj** [comment]
> Send a contact to ur saved message and check

Again send without country code and check it still persists

**Comment by tooomm** [comment]
Yep, that might be it. If I share/send a contact from my phone's address book without country code saved it'll only be intractable on my phone - not with Telegram Desktop.

But still, these contact tiles without country code should be interactable on Telegram Desktop the same as they are on iOS, no?
People not only share contacts internally in the app.

**Comment by SmartManoj** [comment]
Not like that , without country code the number should not be unique.
In mobile client they may have some linking.
And they must send with country code.

**Comment by john-preston** [comment]
@tooomm How exactly do you interact with such contacts on iOS? What can you do with them? I see View Contact button.

**Comment by tooomm** [comment]
I can call him, add to contacts etc.
![GitHawk Upload by tooomm](https://i.imgur.com/R7jy3wJ.jpg)

**Comment by SmartManoj** [comment]
So you can't send message.
What would `Add to existing`  do ?

**Comment by tooomm** [comment]
It would better be named „...existing contact“. 

It opens the contacts section within telegram and allows to add the number to a known contact

**Comment by SmartManoj** [comment]
Then will it create a another contact with same name ?
//Can a contact contain more than 1 number ?

**Comment by tooomm** [comment]
It looks like a contact can contain more than one number...

**Comment by SmartManoj** [comment]
> It would better be named „...existing contact“.
> 
> It opens the contacts section within telegram and allows to add the number to a known contact

Contacts section of telegram or Contacts app

**Comment by tooomm** [comment]
Right. My wording was still not exactly clear...
It opens the contacts section of telegram.
