### ISSUE TITLE
Change the UI

### ISSUE THREAD

**Issue by thewhitetulip** [telegramdesktop/tdesktop#614]
The current UI is mobile focused, we can redesign the UI to suit the purposes of being used on a desktop, it will require major work, I have a few ideas in mind, I can create a mockup if there is a positive response.

**Comment by ManuelSchneid3r** [comment]
It is fine like it is, isn't it? Have u tried majn/telegram-purple?

**Comment by thewhitetulip** [comment]
I don't know what is majn/telegram-purple, I'll check it out and let you know :)

The thing is telegram should have tabs like Lync does

**Comment by ManuelSchneid3r** [comment]
It is a github repo, check it out. Its a plugin for pidgin. So you can have the tradidtional look n feel of an IM. Telegram is pretty modern. See current alternatives.
