### ISSUE TITLE
Uploading images after one of the latest updates

### ISSUE THREAD

**Issue by SDKiller** [telegramdesktop/tdesktop#6143]
### Steps to reproduce
1. Upload image file

### Expected behaviour

Ask if I want to upload as photo or file

### Actual behaviour

File is silently uploaded "as file"

### Configuration
**Operating system:**

Windows 7

**Version of Telegram Desktop:**

**Used theme**:

default

After one of recent updates telegram desktop no more asks me if I want to upload image "as photo" or "as file", all image files are uploaded silently "as files", with ugly small preview area and "Open with" link.

Could not find if it can be configured in settings. 
Is it intended behavior?

![QIP Shot - Screen 2898 16 06 19](https://user-images.githubusercontent.com/2150916/59565285-b2524e80-9051-11e9-9bb9-411c9fa66786.png)

**Comment by 23rd** [comment]
> Upload image file

What exactly are you doing?
Any image can be sent using the attachement button (or `Ctrl+O` shortcut), using the clipboard (or `Ctrl+V` shortcut) or using drag'n'drop.

**Comment by SDKiller** [comment]
Seems the issue is gone after windows restart. sorry for taking your time
