### ISSUE TITLE
allow to hide ("collapse") saved messages the same as archived conversations

### ISSUE THREAD

**Issue by tooomm** [telegramdesktop/tdesktop#6146]
Title says it all.
That would also automatically display them at the top of the chat list (in a nice, unobtrusive way) without the need to pin them. Plus, that way they look less like an ordinary chat, but some special area.

**Update:**
Even more, after 1.7.8 with https://github.com/telegramdesktop/tdesktop/issues/5989 addressed. There is already a button in the main menu for saved chats.
Let us collapse (and hide!) them just like archived chats.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.7.3

**Used theme**: Default

**Comment by SmartManoj** [comment]
api issue ?

**Comment by RememberTheAir** [comment]
@SmartManoj no

**Comment by SmartManoj** [comment]
Can't do in mobile also

**Comment by tooomm** [comment]
Yes. Mobile lacks the same feature.
But one have to send a request in a different place regarding that.

So weird that saved and archived work and behave so differently.

**Comment by SmartManoj** [comment]
Ctrl + 0 to open saved message.
So you can open whenever you want.
It would be easy to move to the archived chats?

**Comment by Casuallynoted** [comment]
I would also like to see this feature for better chat organisation.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
