### ISSUE TITLE
[Feature Request] Copy number in contact media

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6147]
Copy contact number

**Comment by 23rd** [comment]
What exactly do you mean?

**Comment by SmartManoj** [comment]
Copy number in contact media

**Comment by Placid7** [comment]
@SmartManoj Please describe the expected behavior and desired results. i.e. "copy contact number" - from where to where?

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/60606671-676a6200-9dd9-11e9-99f3-ef56a36bb067.png)
On context menu of contact

**Comment by Placid7** [comment]
Are you saying you want to right click on any message and for the context menu to have an option to copy the individuals contact details?

**Comment by SmartManoj** [comment]
Nope , only for contact

**Comment by SmartManoj** [comment]
> ![image](https://user-images.githubusercontent.com/7231077/60606671-676a6200-9dd9-11e9-99f3-ef56a36bb067.png)
> On context menu of contact

Last message

**Comment by Placid7** [comment]
I think what you're requesting is for Telegram desktop to recognize the text as a phone number first. You could say the same for Addresses. To copy as contact details Telegram would need to be able to recognize the details as a contact information.
Name: "X"
Number: "X"
Also whatever app you are sending the details to would have to know how to interpret that information. This wouldn't be a telegram enhancement and would need to be handled by the OS itself much like Android does.

**Comment by SmartManoj** [comment]
Nope it is a contact object

**Comment by Placid7** [comment]
Ok we're going in circles. You say it's "contact media" how was the message created?

**Comment by SmartManoj** [comment]
User Info --> share contact
