### ISSUE TITLE
last seen

### ISSUE THREAD

**Issue by physbyte** [telegramdesktop/tdesktop#6148]
### Steps to reproduce
1. Contact was online **15.06.19 at 22:00**
2. Open his profile/dialog the next day (16.06.19) after this time expires (for example, 23:20), but before 17.06.19.
3. Tdesktop shows that the contact was online at 22:00 (no date)

### Expected behaviour
tg shows that the contact wast online 15.06.19 at 22:00

### Actual behaviour
tg shows that the contact was at a certain time, without a date.

### Configuration
**Operating system:** w10

**Version of Telegram Desktop:** 1.7.7

**Used theme**: Any

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Placid7** [comment]
@physbyte If there is not date then that should indicate the time stamp is for the current date.

![Capture](https://user-images.githubusercontent.com/16446194/60606156-77098c80-9d80-11e9-990b-29d855db9d6b.PNG)

**Comment by physbyte** [comment]
@rthomas529 Maybe I did not explain well, or you did not understand.

The error lies in the fact that the telegram shows that the contact was at a certain time (as if recently, but without forming a text like "recently or 5 minutes ago"), although in reality, he was online the PREVIOUS day, this is confusing.


I believe that the error lies in the formation of the date, with the wrong time zone. @john-preston

**Comment by physbyte** [comment]
26.10.2019 current time is 21:05 (my local time), but telegram show me contact "last seen today at 0:21"

**Comment by physbyte** [comment]
@john-preston now 26.10.2019 current time is 21:05 (my local time), but telegram show me contact "last seen today at 0:21"
