### ISSUE TITLE
[Feature Request] Mark images/files as NSFW

### ISSUE THREAD

**Issue by Rintack** [telegramdesktop/tdesktop#615]
I would like to be able to mark images or files as NSFW so they wont open full size as soon as i max out the window.

Thank you and keep up the good work!

**Comment by squirrelboot** [comment]
I second this

**Comment by squirrelboot** [comment]
You never know where a friend uses their program
On the pc, phone, or web. I've sent stuff to friends at work and they were like.. dude.. I'm at work. I'd no idea. So an NSFW would be cool. Or you know, secret chat for PC would do it? Can also add hashtags like #NSFW when you send stuff to friends for the time being.

**Comment by auchri** [comment]
No api for that
