### ISSUE TITLE
Question: Changelog outdated

### ISSUE THREAD

**Issue by tooomm** [telegramdesktop/tdesktop#6152]
After updating, Telegram sends you a message which links to https://desktop.telegram.org/changelog

The latest information there is about 1.7.2, even though the App updated to 1.7.7

**Comment by john-preston** [comment]
@tooomm 1.7.8 is a beta version, you need to enable installing beta versions in Settings > Advanced.

**Comment by tooomm** [comment]
Thanks. I realized that in between. Hehe Sorry for the confusion.

I updated the issue for that reason and removed that side question. :)
The initial issue persists: the linked to changelog after updating is outdated.

**Comment by john-preston** [comment]
@tooomm This version just doesn't contain anything significant.

**Comment by tooomm** [comment]
Sure, reading the changelog here in GitHub it's mostly small fixes. But yeah...
It could say at least `v1.7.3 to v1.7.7 (date): Bugfixes`.

It's a bit confusing if you get send to an outdated page after a fresh update.
