### ISSUE TITLE
[Bug] [GNOME 3] Notification tray icon disappears after screen unlocking

### ISSUE THREAD

**Issue by cty12** [telegramdesktop/tdesktop#6153]
### Steps to reproduce
1. Launch telegram desktop. Notification tray icon displays normally. 

![Screenshot from 2019-06-18 15-29-51](https://user-images.githubusercontent.com/4571899/59713719-0a1dc080-91de-11e9-8d46-9f089307d7d2.png)

2. Lock screen and unlock. Notification tray icon disappears. 

![Screenshot from 2019-06-18 15-31-37](https://user-images.githubusercontent.com/4571899/59713774-2e799d00-91de-11e9-8db5-c1448bb762dd.png)

### Expected behaviour
The icon should persistently displays regardless of locking / unlocking the screen. Please see the Chrome icon(s) in the attached screenshots for an example. 

### Actual behaviour
The icon disappears after unlocking the screen!

### Configuration
**Operating system:** Fedora 30 with GNOME 3.32.2

(This is GNOME-related and OS independent. I use [Topicons Plus](https://extensions.gnome.org/extension/1031/topicons/) to bring the notification tray to the top panel, since it is not displayed by default in GNOME 3 since some recent version. )

**Version of Telegram Desktop:** 1.7.7

**Used theme**: N/A

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by cty12** [comment]
Seems to be fixed with version `1.7.10`.

**Comment by kmare** [comment]
I can confirm it is actually fixed with 1.7.10.
