### ISSUE TITLE
Add favorite stickers management

### ISSUE THREAD

**Issue by Geobert** [telegramdesktop/tdesktop#6154]
Android's Telegram can favorite stickers which appears in their own category. TDesktop display them on top which is great, but we don't have the feature to add favorite stickers. I think we can only delete them from favorite.

**Comment by john-preston** [comment]
@Geobert You can add stickers to favorites from right click menu on a sent sticker. Send it once and add to favorites from the chat screen.

**Comment by Geobert** [comment]
OH didn't see this one, thanks!
