### ISSUE TITLE
View Count Missing for a specific forwarded post of itself in channel

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6155]
### Steps to reproduce
1. [Sherlock Holmes Series ](https://t.me/joinchat/AAAAAFVp2uvbK2Ex24u-Mg)
2. June 15 , 19 message
3. 

### Expected behaviour
View Count

### Actual behaviour
Tell us what happens instead
![image](https://user-images.githubusercontent.com/7231077/59764347-38bc9980-92b9-11e9-97b2-6963f84c890a.png)
Missing count

### Configuration
**Operating system:** Win

**Version of Telegram Desktop:** 1.7.7

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RememberTheAir** [comment]
Try to use a normal hour format, without seconds

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/59764897-6524e580-92ba-11e9-9d6d-4e1b7816e072.png)
Still
Theme : Dark

**Comment by SmartManoj** [comment]
If a post is deleted how long the count remains?
