### ISSUE TITLE
Template Change

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6157]
Colon and spacing changed

```### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:
```
To
```### Configuration
**Operating system** : 

**Version of Telegram Desktop** : 

**Used theme** : 
```

**Comment by Sasha-Sorokin** [comment]
Why do you need spaces before the colons?

**Comment by SmartManoj** [comment]
In this `**Operating system:**`
No space after the star.
So if we type `**Operating system:**Win` bold does not work

**Comment by SmartManoj** [comment]
> Why do you need spaces before the colons?

Is colon need bold also?

**Comment by Sasha-Sorokin** [comment]
I mean, you don't need spaces after the asterisks (before colons):

```
**Operating system**: 

**Version of Telegram Desktop**: 

**Used theme**: 
```

---

Also you'd better open a pull request to change the Issue Template instead of creating a new issue:
https://github.com/telegramdesktop/tdesktop/blob/master/.github/ISSUE_TEMPLATE.md
