### ISSUE TITLE
[Feature Request] Use username for channels too as default

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6160]

**Comment by RememberTheAir** [comment]
Using the "share contact" option will make you send a Contact object in another chat. How would sharing a bot/channel/group work? By sharing a link to the channel/chat/bot? You cancopy it from the chat itself and send it to the contact. No need to add other item to a menu that is already really crowded with options

**Comment by SmartManoj** [comment]
Atleast we can add here
![image](https://user-images.githubusercontent.com/7231077/59918708-2d957500-9443-11e9-9b55-c254a0ff75eb.png)

**Comment by SmartManoj** [comment]
Also Copy as link would be better along with username
