### ISSUE TITLE
[Feature Request] Ability To Separate (Super)Groups, Direct Messages and Channels

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [telegramdesktop/tdesktop#6164]
For people that have large amounts of groups/supergroups, channels, and direct messages.. it can be an extreme pain to find stuff without searching.

I think it would be extremely beneficial to be able to separate them, instead of having one long list all mixed up.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1107
