### ISSUE TITLE
[Request to add] Again, secret chat

### ISSUE THREAD

**Issue by Khomyak-sibiryak** [telegramdesktop/tdesktop#6165]
Telegram has long ceased to be just a mobile application. Now this is a cross-platform messenger. Although he has come a long way, his change history is relatively modest.

While other “mobile” applications reduce the functionality for mobile platforms and are expanding for desktop computers. Telegram-desktop still does not add secret chats, lagging behind the mobile version of the client.

Much time has passed since the last addition requests. You do not think it's time to implement secret chats in the Telegram-desktop?

**Comment by SatoMew** [comment]
This is explained [here](https://core.telegram.org/tsi/e2ee-simple).

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/871

**Comment by Khomyak-sibiryak** [comment]
**SatoMew**, Of course, many reasons are obvious. But sometimes it is worth returning to requests to show that in modern realities this functionality is relevant.

**Comment by Khomyak-sibiryak** [comment]
**Aokromes**, This topic was closed in 2016. I wonder how things are at the moment.
