### ISSUE TITLE
[Bug] gif document is displayed incorrectly.

### ISSUE THREAD

**Issue by MairwunNx** [telegramdesktop/tdesktop#6166]
###### The display of a gif document should be normal with its native resolution (800x600)
![404-drib23](https://user-images.githubusercontent.com/39625750/59966684-8b4fbd00-9528-11e9-9a02-1230146c914e.gif)

###### The gif document is displayed with the wrong resolution, often several times smaller than it.

gif document original: 

![image](https://user-images.githubusercontent.com/39625750/59966624-981fe100-9527-11e9-862e-12b01c094d5c.png)

how is the gif document displayed by the user:

![image](https://user-images.githubusercontent.com/39625750/59966640-cf8e8d80-9527-11e9-88c8-ccd54e0924a1.png)

### Configuration
**Operating system:** `Windows 10 1809`

**Version of Telegram Desktop:** `1.7.8-beta`

**Used theme**: `Midnight`

**Comment by Mart-Bogdan** [comment]
I'd suggest to add way to transfer actual gifs, instead repacking them as mp4

So send gif as a doceument

**Comment by Mart-Bogdan** [comment]
A workaround would be to zip the file first

**Comment by MairwunNx** [comment]
Another option is to use services such as imgur.

**Comment by kirsan31** [comment]
This behavior is not tdesktop's only problem, but whole telegram. And it's started about a yer ago,
I [already had this question](https://github.com/telegramdesktop/tdesktop/issues/2206#issuecomment-386700308). Have no answer...
