### ISSUE TITLE
Grouping chats

### ISSUE THREAD

**Issue by neygomon** [telegramdesktop/tdesktop#6167]
Hello. maybe it is worth adding a function for grouping chats? for example, "work", "study" and so on ... not to create a group, but to place chats, in folders, so to speak ... so as not to search for the right person in a large number of dialogs. I think the function will appeal to many ..

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/2642

**Comment by neygomon** [comment]
@Aokromes, I know.
It's issue created in 2016 year...
