### ISSUE TITLE
[Feature Request] Channels - Ability For Owner To See Who Posted What

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [telegramdesktop/tdesktop#6168]
Would really love the ability for the owner of groups to be able to see who posted what, without it being visible to all the other members.

**Comment by omkarnathsingh** [comment]
@Z3ROGRAV1TYx You can use the recent actions to see it. Give it a try :)

**Comment by Z3ROGRAV1TYx** [comment]
@omkarnathsingh I've tried it before and I just checked again, nothing shows there for posts. If I turn signatures on, then stuff shows.

**Comment by omkarnathsingh** [comment]
Then its API like that.

**Comment by Z3ROGRAV1TYx** [comment]
What do you mean?

**Comment by omkarnathsingh** [comment]
Server don't send recent actions when Signatures are off. TDesktop project can't do anything if server do not support them.

**Comment by secretcage** [comment]
> Would really love the ability for the owner of groups to be able to see who posted what, without it being visible to all the other members.

I think you referring to owner of channel to see who posted what . 
Recent actions are for groups and different to this topic .
You want to see which admin posts on channel and there is no option for that
