### ISSUE TITLE
How to add another language?

### ISSUE THREAD

**Issue by AryanShadowhunter** [telegramdesktop/tdesktop#617]
I want to translate telegram to another language and add it to the Telegram Desktop languages list. Is there anyone who could help me up?

**Comment by basheersubei** [comment]
I have no experience with working on Telegram, but I guess you could just use hints from what this guy did to translate to Russian #366

**Comment by AryanShadowhunter** [comment]
@basheersubei Thanks for your helpful answer

**Comment by Katzen-Gott** [comment]
@AryanShadowhunter if your problem is solved, you can close the issue (there is button under the comment box)
