### ISSUE TITLE
Windows Library launches after update

### ISSUE THREAD

**Issue by HYBRID-BEING** [telegramdesktop/tdesktop#6174]
I'm experiencing a peculiar issue with updating Telegram - each time i update it, Windows Library opens up instead of Telegram. Telegram itself updates correctly and launches manually without problem, but it's getting a bit annoying.

### Steps to reproduce
1. Wait for a new update.
2. Press Update Telegram Button
3. Confirm.

### Expected behaviour
Telegram closes, updates and launches.

### Actual behaviour
Telegram closes, updates and Windows Library launches.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
Latest versions, currently 1.7.10
**Used theme**:
Night Mode
[log.txt](https://github.com/telegramdesktop/tdesktop/files/3324579/log.txt)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by HYBRID-BEING** [comment]
Yeah, still happens.

**Comment by ilya-fedin** [comment]
Is this still valid?

**Comment by HYBRID-BEING** [comment]
Sorry for late reply/
It still did happen at time of your post, but, to exclude any kind of privilege errors, i tried reinstalling Telegram with admin rights in Program Files, and waited for a few more updates to see if it had any impact.
I think one update went smoothly, but after latest update again Windows Library was opened in explorer window (not sure if it's relevent, but i'm using QTTabBar).
Are there any logs i can check to see what's going on with installation? Maybe there's is something somewhere in the Windows Event Viewer?

**Comment by ilya-fedin** [comment]
tdesktop won't work right installed in Program Files since it installs for a user, install it to AppData.

**Comment by HYBRID-BEING** [comment]
I no longer use that laptop and no longer install to Program Files - can't reproduce issue anymore.
