### ISSUE TITLE
Create Group or Channel is unavailable

### ISSUE THREAD

**Issue by akrupiy** [telegramdesktop/tdesktop#6176]
### Steps to reproduce
1. Menu -> New Group / New Channel
2. Enter Group / Channel Name
3. In case of group, select users. 
4. Click «Create»

### Expected behaviour
New Group or Channel was created

### Actual behaviour
Error window: «Sorry, this action is unavailable». Channel or Group doesn't create. This bug always show for a 1.5 years.
![image](https://user-images.githubusercontent.com/6741847/60170098-45913e00-9821-11e9-99d2-def64598e85a.png)
 If i need new group i'm asking a friends to create it. This makes using telegram really hard.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.7.10

**Used theme**: Any theme

I'm using Telegram since 2016 year, real person, never spam or send messages to unknown peoples.

**Comment by 23rd** [comment]
Can you create group or channel from other clients?

**Comment by akrupiy** [comment]
> Can you create group or channel from other clients?

Well, i can't check in web version because in Russia Telegram is banned by federal goverment :)
But in Mobile Version i have an another error. 

![image](https://user-images.githubusercontent.com/6741847/60215147-6e94eb80-9880-11e9-8134-3a89397eec1f.png)

Channel and Group doesn't created finally. 
All other my friends (and even my wife from same wifi network e.t.c.) can creating groups / channels...

**Comment by 23rd** [comment]
So, this issue is not related to this repository.

https://github.com/telegramdesktop/tdesktop/issues/4484#issuecomment-372028220
> You can report api issues here: https://twitter.com/telegram

**Comment by Aokromes** [comment]
you can try to use telegram web with opera vpn as workaround.

**Comment by kenorb** [comment]
I've the same issue:

> Sorry, this action is unavailable.

Some detailed message about the error would be nice. Probably I've reached the limit, but it's not clear.
