### ISSUE TITLE
Outdated channel terminology

### ISSUE THREAD

**Issue by SatoMew** [telegramdesktop/tdesktop#6181]
### Steps to reproduce
1. Find a channel.
2. Access it.
3. Check every channel-related UI.

### Expected behaviour
The "subscriber" terminology replaces "member" in channels like on the mobile apps.

### Actual behaviour
Channel subscribers are still referred to as "members".

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.7.10
**Used theme**:
Built-in

**Comment by gustavoaca1997** [comment]
Can I try to solve this as my first PR to this project?

**Comment by Aokromes** [comment]
> Can I try to solve this as my first PR to this project?

yes :)
