### ISSUE TITLE
Implement bubble-less chat UI

### ISSUE THREAD

**Issue by SatoMew** [telegramdesktop/tdesktop#6182]
### Steps to reproduce
1. Go to Settings.
2. Click or tap on Chat Settings.
3. Scroll down to the Messages section.

### Expected behaviour
Users can disable message bubbles like on Telegram X for Android, which also disables chat backgrounds. The Messages section may not be the more appropriate, however.

### Actual behaviour
Users are not allowed to configure the display of message bubbles at all.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.7.10
**Used theme**:
Built-in

**Comment by 23rd** [comment]
#5634.
