### ISSUE TITLE
[Feature Request] Forward and Delete

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6185]
We select some random 15 messages between 30 messages.
If we want to forward and delete msg, we select and forward.Once forwarded the selection is gone. So We need to select again. It will be useful if  there is a Forward and Delete button.

**Comment by stek29** [comment]
If it ever gets implemented, it has to be decided on platform level.

**Comment by SmartManoj** [comment]
Will Telegram track `api issus` labels?

**Comment by stek29** [comment]
No, you have to report them on twitter or via in app support

**Comment by SmartManoj** [comment]
Why api issue?
Why dont we call two api concurrently?

**Comment by SmartManoj** [comment]
Why some api_issues are still open?

**Comment by nuclight** [comment]
@stek29 why "API issue" ? This could be implemented by just a checkbox "don't clean selection messages after operation", so user can then manually apply different operation to still selected messages. Very infrequently needed feature, though - but still has nothing to do with API.

**Comment by SmartManoj** [comment]
Could you transfer api-issues to [this repo](https://github.com/SmartManoj/Telegram-Feature-Requests/issues)?

Could you add labels for [auto-closed ones] because there are some [Feature Requests] in this ?(https://github.com/telegramdesktop/tdesktop/issues?q=is%3Aissue+is%3Aclosed+label%3A%22auto+closed%22
)
