### ISSUE TITLE
Crash when sending big image to chat

### ISSUE THREAD

**Issue by ashakirov** [telegramdesktop/tdesktop#6187]
### Steps to reproduce
1. Create big "png" image file. For example 17000x17000 pixels.
2. Drag and drop this file to any telegram chat
3. App crashes

### Expected behaviour
App should send image to chat. Android and MacOS clients resize big image first. On MacOS client resize that image from 17000x17000 to 1280x1280 then send resized one to chat.  

### Actual behaviour
App crashes without any messages

### Configuration
**Operating system:** 
 Windows 10 Pro

**Version of Telegram Desktop:**
1.7.10

**Used theme**:
default 

<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/3334191/log.txt)
</details>

<details><summary><b>Dump</b>:</summary>
[dump.zip](https://github.com/telegramdesktop/tdesktop/files/3334206/dump.zip)
</details>

**Comment by Aokromes** [comment]
plz next time click send crash and post id here.

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
