### ISSUE TITLE
[Bug] Gif image is not playing in preview mode

### ISSUE THREAD

**Issue by mervick** [telegramdesktop/tdesktop#6188]
### Steps to reproduce
1. Upload gif image
2. Click on gif image in chat for full view

### Expected behaviour
It should play gif image

### Actual behaviour
Gif image is not playing

### Configuration
**Operating system:**
Linux izman 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.7.10

**Used theme**:
Dark theme

![Peek 2019-06-27 16-23](https://user-images.githubusercontent.com/2429298/60270832-ddfaf180-98f9-11e9-9d8a-695f1d69716e.gif)

**Comment by TronicLabs** [comment]
same for 1.8.1 Version

**Comment by egorpugin** [comment]
Same on 1.8.15 (win).
Attaching sample gif for reference.

![f447da59-75ed-4562-b545-d62ae147ae6b](https://user-images.githubusercontent.com/4325333/68817264-37d63b00-0692-11ea-9563-f8bbf7feb10b.gif)

**Comment by Aokromes** [comment]
if the last one was bugged it works for me on 1.9.8.

**Comment by mervick** [comment]
Now it fixed.
Gif image is playing in preview mode, but size of the image in the preview mode is smaller than original and the same as on thumbnail.

**Comment by Twente-Mining** [comment]
I believe this bug is back
