### ISSUE TITLE
[Feature Request] How to see 'About' of bot ?

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6189]
### Steps to reproduce
1. Go to already started bot having lengthy conversation
2. How to see about without scrolling to the top
3. 
![image](https://user-images.githubusercontent.com/7231077/60271327-c29ae100-990f-11e9-9469-eefc026e4c41.png)

**Comment by RememberTheAir** [comment]
Search by date -> hold the left arrow to scroll back to some years ago -> "go" button, you'll reach the beginning of the conversation

**Comment by SmartManoj** [comment]
holding not works , have to click

**Comment by Aokromes** [comment]
i don't think this "issue" is a bug on telegram.

**Comment by stek29** [comment]
It’s an issue of whole platform, not tdesktop
