### ISSUE TITLE
[BUG] Can't send gifs

### ISSUE THREAD

**Issue by brunogarciavaz** [telegramdesktop/tdesktop#6190]
I've been having this problem for almost 2 months now, but I can't exactly recall what version started causing it.

### Steps to reproduce
1. Save a gif
2. Open the gif tab and click to send

### Expected behaviour
GIF should be downloaded and then be sent immediately 

### Actual behaviour
GIF is downloaded, but the loading spinner never goes away and re-appear whenever I click to send. This makes it impossible to send gifs.
Here's a gif I recorded showing the problem, hosted on imgur: https://imgur.com/a/WP2CB5T

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.7.10

**Used theme**: Default

**Comment by 23rd** [comment]
As a temporary workaround, you can send GIFs with the `CTRL` key pressed.

**Comment by Forger7** [comment]
Can confirm the workaround works although it's annoying as every gif keeps having the loading circle forever, even in the chatwindow.

Behaviour happens on Arch Linux in Version 1.8.15

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
