### ISSUE TITLE
Automatic select fast proxy

### ISSUE THREAD

**Issue by smkplus** [telegramdesktop/tdesktop#6193]
Please make Automatic select fast proxy
I have to find and select best proxy is there a way that it select automatically?

**Comment by Aokromes** [comment]
imho better https://github.com/telegramdesktop/tdesktop/issues/5040

**Comment by smkplus** [comment]
@Aokromes 
![image](https://user-images.githubusercontent.com/16706911/60411193-e6487a80-9be0-11e9-9783-6714d1ab3ccf.png)
