### ISSUE TITLE
[Request] Disable Pin Notifications Client Side

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [telegramdesktop/tdesktop#6194]
Some people don't want to get notified by pins at all in certain groups, there is no way to disable pin notifications per group.

The only way is if the person pinning doesn't select notify.. but you can't control that client side. And in a huge group, the likelihood of one or two people complaining to the admin won't change that.

I think it would be an excellent option to disable pins per group, client side.

**Comment by 23rd** [comment]
?
![image](https://user-images.githubusercontent.com/4051126/60387842-4f7da000-9ab2-11e9-8ebf-fd29215e15d3.png)

**Comment by Z3ROGRAV1TYx** [comment]
@23rd That disables pins for every single group though, you can't disable them per group/channel

**Comment by 23rd** [comment]
Oh, anyway this is duplicate.
https://github.com/telegramdesktop/tdesktop/issues/2791#issuecomment-496952349
