### ISSUE TITLE
If system have 2 display with different scale, Telegram always use scaling from main display

### ISSUE THREAD

**Issue by T-Troll** [telegramdesktop/tdesktop#6196]
### Steps to reproduce
1. Connect 2 display and set different scale
2. Run Telegram
3. Move telegram window to other display

### Expected behaviour
It should re-scale ui and fonts according to diplay settings there it's window located

### Actual behaviour
It still have UI/font scaling from main display

### Configuration
**Operating system:**
Windows 10 x64
**Version of Telegram Desktop:**
1.7
**Used theme**:
Dark

**Comment by iamGavinJ** [comment]
Another variation on this issue.  When switching between docked (dual monitors) and un-docked (built in screen only) Telegram doesn't redraw/rescale for the active screen's scale setting.

![image](https://user-images.githubusercontent.com/15910740/62647475-80e55900-b905-11e9-8ad2-d302caf95b38.png)

**Comment by vskubriev** [comment]
The same issues are for Ubuntu 18.04 (DE by default)

**Comment by T-Troll** [comment]
> Another variation on this issue. When switching between docked (dual monitors) and un-docked (built in screen only) Telegram doesn't redraw/rescale for the active screen's scale setting.

More precisely, Telegram doesn't mention any display configuration change and always use the scale from the display it starts from.

**Comment by EletronicElephant** [comment]
I have seen this bug since 2017. Is there any plan to fix it?

**Comment by Aokromes** [comment]
maybe this can give a light.
https://doc.qt.io/qt-5/highdpi.html
https://doc.qt.io/qt-5/scalability.html

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1121

**Comment by evemilano** [comment]
After 4 years the bug is still here

**Comment by T-Troll** [comment]
> After 4 years the bug is still here

Yes, but it stop using it.
