### ISSUE TITLE
[Bug] Voice messages play no sound

### ISSUE THREAD

**Issue by RandomWolf** [telegramdesktop/tdesktop#6197]
### Steps to reproduce
1. Receive a voice message in a group chat or from a private chat
2. Play the voice message in Telegram itself via the play button

### Expected behaviour
The audio file plays with the sound emitting from what is configured to be the standard audio device, for example a set of speakers.

### Actual behaviour
The audio message is being played, but no sound is coming from any audio device that Windows registered. Every other application can play sound just fine.
### Configuration
**Operating system:**
Windows 10 Build 1803
**Version of Telegram Desktop:**
1.7.10
<b>Logs</b>:

[log_extract.txt](https://github.com/telegramdesktop/tdesktop/files/3345321/log_extract.txt)

**Comment by Aokromes** [comment]
#5481
