### ISSUE TITLE
Options -many and -workdir don't have any effect

### ISSUE THREAD

**Issue by yegor256** [telegramdesktop/tdesktop#6198]
I'm trying to start Telegram Desktop 1.7.10 on macOS Mojave 10.14.5 with the following options:

```
$ open -a 'Telegram Desktop' --args '-many -workdir /tmp/xxx'
```

However, it starts the way it usually starts, keeping its data in `/Library/Application Support/Telegram Desktop` directory. The options provided have no effect. Am I doing something wrong or it's a bug?

Removing the `-many`, as suggested [here](https://github.com/telegramdesktop/tdesktop/issues/533#issuecomment-411331438), doesn't help either.

Starting the app directly, without the use of `open`, doesn't help either:

```
$ /Applications/Telegram\ Desktop.app/Contents/MacOS/Telegram\ Desktop -workdir /tmp/xxx
```

**Comment by 23rd** [comment]
```
cd /Applications/Telegram.app/Contents/MacOS/
./Telegram -many -workdir /tmp/xxx
```

**Comment by yegor256** [comment]
@23rd but it doesn't work for me... Hm... What this could be?

**Comment by Sasha-Sorokin** [comment]
@yegor256 Does the folder exist? On Linux these options did not work for me and were just re-launching Telegram until I manually created the specified folder (via `mkdir`).

**Comment by yegor256** [comment]
@Sasha-Sorokin yes, indeed, it works if the directory is already there. However, it doesn't work if the name of the app is `Telegram Desktop.app`. Renaming it to `Telegram.app` helps.
