### ISSUE TITLE
Native notifications do not work on wayland

### ISSUE THREAD

**Issue by eternal-sorrow** [telegramdesktop/tdesktop#6199]
### Steps to reproduce
1. Run any wayland environment on Linux (sway in my case)
2. Start Telegram Desktop (make sure it runs natively on Wayland, use envvar `QT_QPA_PLATFORM=wayland` if needed)
3. Open settings and see if you can enable native notifications

### Expected behaviour
Native notifications enabled.

### Actual behaviour
No option to enable native notifications

### Configuration
**Operating system:** Gentoo Linux

**Version of Telegram Desktop:** 1.7.9

**Used theme**: default

<details><summary><b>Logs</b>:</summary>
<code>
Failed to gtk_init_check(0, 0)!
</code>
</details>

I want to add that I use flatpak build of tdesktop, but I don't think it's relevant in this case. For long time I thought it's issue of flatpak or their build of tdesktop or combination of flatpak and sway compositor or something in this area. But later by digging tdesktop's code and debug logs I've found the culprit - GTK integration is failing to initialise on wayland because tdesktop enforces X11 backend for GTK and therefore native notifications are not initialised either.

The beginning of my struggle with this issue is here: https://github.com/flathub/org.telegram.desktop/issues/55#issuecomment-460129433
The rest is here: flathub/org.telegram.desktop#72

**Comment by eternal-sorrow** [comment]
Any news here?

**Comment by eternal-sorrow** [comment]
Does anyone here give an actual damn?

**Comment by Johnnynator** [comment]
Adding Wayland to the allowed gdk backend seems to get this working. I haven't opened any PR yet, since I have not tested if it could break under certain other Conditions.

**Comment by eternal-sorrow** [comment]
@Johnnynator that's good to hear. Is there any way I could help?
