### ISSUE TITLE
Linux: Notification steals focus/notification is an extra window

### ISSUE THREAD

**Issue by Brawl345** [telegramdesktop/tdesktop#62]
If you get a notification, you loose the focus on another window, e.g. the browser. It actually  opens a second window with the notification, which also makes it difficult to switch windows.
![bildschirmfoto vom 2014-07-18 16 17 01](https://cloud.githubusercontent.com/assets/5049892/3627166/37af45ae-0e86-11e4-9a68-38aee97c806e.png)
![bildschirmfoto vom 2014-07-18 16 18 12](https://cloud.githubusercontent.com/assets/5049892/3627225/d2f5d3a2-0e86-11e4-9499-50aeeacfc94f.png)

**Comment by Feichtmeier** [comment]
I have to confirm that this is still present if you activate the native notifcations in GNOME 3
For example I receive a notifcation from Geary Mail and click on it and telegram is started ofc, then telegram steals the focus of the notification and jumps into the background. This is really annoying.
