### ISSUE TITLE
Add own channel post view count to chat list

### ISSUE THREAD

**Issue by SatoMew** [telegramdesktop/tdesktop#6200]
### Steps to reproduce
1. Run Telegram Desktop.
2. Create a channel if necessary.
3. Publish something to the channel.

### Expected behaviour
Like Telegram X for Android, Telegram Desktop should display the view count of the last post we have made to a channel on the chat list.

### Actual behaviour
Telegram Desktop does not display the view count of our last channel post on the chat list.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.7.10
**Used theme**:
Built-in

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by RememberTheAir** [comment]
Yes, but the current behavior is consistent with every other official production app

**Comment by SatoMew** [comment]
I think it's still a valid suggestion for an enhancement.

**Comment by SatoMew** [comment]
Same as before.

**Comment by RememberTheAir** [comment]
unstale
