### ISSUE TITLE
Untick delete chat when blocking user

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6201]
### Steps to reproduce
1. Block user
2. 
3. 

### Expected behaviour
Checkbox should not be ticked
There should be some settings for checkbox value. #3334 
### Actual behaviour

![image](https://user-images.githubusercontent.com/7231077/60576333-d4aad280-9d9a-11e9-8fa2-07d118183d6c.png)

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stek29** [comment]
Just untick it manually

**Comment by SmartManoj** [comment]
Opposite behaviour like #3334

**Comment by SmartManoj** [comment]
Inconsistent with mobile client
