### ISSUE TITLE
Do not play audio messages from iPhones

### ISSUE THREAD

**Issue by comicrocharly** [telegramdesktop/tdesktop#6205]
### Steps to reproduce
1. Open telegram
2. Enter in a chat and receive a vocal message
3. Try to play it

### Expected behaviour
Tell us what should happen
should play the audio message from an iphone user
### Actual behaviour
Tell us what happens instead
 The vocal stops playing almost instantaneously.
if the message it's old instead there aren't problem
### Configuration
**Operating system:**
Majaro Linux - XFCE
Kernel 4.19.56-1 LTS
**Version of Telegram Desktop:**
1.17.10
**Used theme**:
none
<details><summary><b>Logs</b>:</summary>
[log.txt](https://github.com/telegramdesktop/tdesktop/files/3357015/log.txt)

</details>

**Comment by 23rd** [comment]
#5843.
