### ISSUE TITLE
More options to system integration to open tg links

### ISSUE THREAD

**Issue by hooddy** [telegramdesktop/tdesktop#6209]
### Steps to reproduce
1. Open any t.me link in browser

### Expected behaviour
Telegram portable must get tg link and open it
I think it'll be right to app some option for it into Telegram settings (добавить в раздел "Интеграция в систему" ассоциации с файлами и протоколами телеги)

### Actual behaviour
Win8.1 installed from scratch says I don't have any application to open tg links when I click on "View in Telegram".

![Безымянный](https://user-images.githubusercontent.com/6899176/60661740-48181700-9e63-11e9-8210-95882f55de15.png)

### Configuration
**Operating system:**
Win8.1 SL Rus

**Version of Telegram Desktop:**
1.7.10 portable

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
no answer after more than 1 month, closing, if this bug is still valid open a new ticket using updated telegram version.
