### ISSUE TITLE
Can't have both native notifications and Qt-style file dialogs at the same time on KDE

### ISSUE THREAD

**Issue by xuzhao9** [telegramdesktop/tdesktop#6211]
### Steps to reproduce
1. Build telegram with TDESKTOP_DISABLE_GTK_INTEGRATION: native notification isn't available on KDE, but the app will use Qt-style file open/save dialog.

2. Build telegram without TDESKTOP_DISABLE_GTK_INTEGRATION: on KDE, native notifcation is be available, but the app will be forced to use GTK-style file open/save dialog.

### Expected behaviour
On KDE, we want:
1. Native notification is enabled, so that users can use system-wide non-distrub-mode settings.
2. Still use Qt-style file open/save dialog, without falling back to the GTK ones.

### Actual behaviour
Can't reach the desired behavior with tweaking the TDESKTOP_DISABLE_GTK_INTEGRATION compiling option.

### Configuration
**Operating system:**
openSUSE Tumbleweed 20190703

**Version of Telegram Desktop:**
Latest

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Johnnynator** [comment]
Also obsolete sine `GTK_INTEGRATION` isn't needed anymore for native notifications.
