### ISSUE TITLE
Telegram Flatpak fails to display CJK characters

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#6217]
### Steps to reproduce
1. Install Telegram Desktop from Flathub
2. Enter some random CJK characters

### Expected behaviour
CJK characters should be displayed.

### Actual behaviour
All CJK characters are displayed as tofu.
![t-fail1](https://user-images.githubusercontent.com/32593169/60705466-c941dd80-9f39-11e9-8985-2d26d44c7a4f.png)
![t-fail2](https://user-images.githubusercontent.com/32593169/60705467-c9da7400-9f39-11e9-960c-35f4e1887eb7.png)

### Configuration
**Operating system: Fedora 30**

**Version of Telegram Desktop: 1.7.9**

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3575 ?

**Comment by Tinup-Ne** [comment]
> #3575 / #2572 ?

CJK failure occurs only in Flatpak version. No problem with apt installation (Ubuntu universe repository), yum/dnf installation (RPM Fusion) and official Windows installer.

**Comment by nahuelwexd** [comment]
Same issue here. On Arch, the workaround is to install Noto fonts, but in Flatpak there's no way to fix this

![image](https://user-images.githubusercontent.com/18204745/64071206-e8639f80-cc4a-11e9-9557-122d3dd67320.png)

**Comment by janhn** [comment]
> Same issue here. On Arch, the workaround is to install Noto fonts, but in Flatpak there's no way to fix this
> 
> ![image](https://user-images.githubusercontent.com/18204745/64071206-e8639f80-cc4a-11e9-9557-122d3dd67320.png)

There is a way: see https://github.com/flathub/org.telegram.desktop/issues/63 for a workaround, patching the flatpak font configuration (`fc-custom-1.conf`).

**Comment by Aokromes** [comment]
according the linked issue it must be fixed on flatpak.
