### ISSUE TITLE
[Feature Request] Add built-in shadowsocks proxy protocol

### ISSUE THREAD

**Issue by CalvoSotelo7** [telegramdesktop/tdesktop#6218]
### Is your feature request related to a problem?
Reports says mtproto is detected by gfw. Many chinese telegram user's mtproto proxy will be blocked within 3 days.

### Describe the solution you'd like
Add built-in shadowsocks to proxy protocol, because shadowsocks is most used proxy in china and has go python c version, easy to port to telegram.

### Describe alternatives you've considered
V2ray is good too but may be too complex

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4577#issuecomment-379478095
