### ISSUE TITLE
OS X: After entering passcode it is shown in non-secure way in dialog

### ISSUE THREAD

**Issue by f-squirrel** [telegramdesktop/tdesktop#622]
Steps to reproduce:
1. Wait untill TG is locked
2. Activate TG window(do not click in passcode edit box)
3. Type password(nothing is typed in edit box)
4. Type password in edit box and press enter

Result:
Your password is typed in non-secure way in message box of last active dialog.

**Comment by rurigk** [comment]
It happens in linux at same conditions
I have sent my password several times to my girlfriend (luckily it was her)

**Comment by stek29** [comment]
So, when the lock button is used it focuses on passcode box automatically. But if it's locked automatically focus stays where it was?

Btw, @skyjack can you change issue title pls?

**Comment by skyjack** [comment]
@stek29 , actually I'm not able t reproduce this issue.
At Mac when TG is locked passcode edit box is in focus automatically and there password is not written in dialog box anymore.
I propose to close this.

**Comment by Whitebock** [comment]
The bug still occurs on Windows (#2358) but I can not reproduce it by following the steps from @skyjack 
When it is happening to me I can see the passcode textbox loose focus _while writing_.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by f-squirrel** [comment]
> this bug is still valid on 1.9.8?

Hi, I don't have 1.9.8. However, the bug is not valid on 1.9.9.
