### ISSUE TITLE
Cannot undo initial single-character messages

### ISSUE THREAD

**Issue by SatoMew** [telegramdesktop/tdesktop#6220]
### Steps to reproduce
1. Open a chat.
2. Type a single-character message.
3. Attempt to clear the input by pressing Ctrl + Z or using the Undo function in the context menu.

### Expected behaviour
The message field should be cleared even if it is the first input in the chat. If a second character is added to the message, the undo operation works normally and all subsequent single-character messages can be undone properly until the user switches to another chat.

### Actual behaviour
The undo operation on the message field does absolutely nothing.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
1.7.11
**Used theme**:
Built-in

**Comment by SmartManoj** [comment]
Bug?

**Comment by SmartManoj** [comment]
Exclude bug label too @Aokromes

**Comment by SmartManoj** [comment]
Bug still exists

**Comment by ilya-fedin** [comment]
> Bug still exists in 2.4.4.1

This behavior is produced by Qt and happens in every other Qt application. I assume this is intended behavior.

**Comment by Aokromes** [comment]
> Exclude bug label too @Aokromes

i am not who added the bot xd also, a lot of bugs are fixed and never reported back fixed.

**Comment by SmartManoj** [comment]
Just now deleted the message @Aokromes

**Comment by SmartManoj** [comment]
@ilya-fedin 

> > Bug still exists in 2.4.4.1
> 
> This behavior is produced by Qt and happens in every other Qt application. I assume this is intended behavior.

In Qt 5.15 too?

**Comment by ilya-fedin** [comment]
Don't know, my system has Qt 5.14.2

**Comment by SatoMew** [comment]
I'm not sure if it is a Qt issue or not, but older versions did not have this behavior. I don't recall the version that started having this quirk, though.

**Comment by Aokromes** [comment]
> I'm not sure if it is a Qt issue or not, but older versions did not have this behavior. I don't recall the version that started having this quirk, though.

can you download various versions from releases tab and test?

**Comment by SatoMew** [comment]
> can you download various versions from releases tab and test?

The bug started in version 1.2.22, but it affected every single-character message instead, so there was a partial fix in 1.2.25 that results in the current behavior.

**Comment by ilya-fedin** [comment]
> affected every single-character message instead

What do you mean by this?

**Comment by SatoMew** [comment]
> What do you mean by this?

Every time you type in a message with only one character in versions 1.2.22, 1.2.23, and 1.2.24, you cannot undo it until you type a second character. Version 1.2.25+ continue to experience this behavior, except it's limited to the first single-character message in the current execution of the app. In contrast, versions 1.2.21 and earlier behave as expected and always let you undo these messages.

**Comment by SatoMew** [comment]
Please refer to my previous reply.

**Comment by SatoMew** [comment]
This regression persists in the current releases.
