### ISSUE TITLE
Tdesktop interacts with mouse clicks when covered by another app on MacOS

### ISSUE THREAD

**Issue by astorath** [telegramdesktop/tdesktop#6221]
### Steps to reproduce
I don't have actual steps to reproduce the issue, cause it does not happen every time.

1. Open telegram desktop in chat mode (with stickers side bar open as well)
2. Switch (CMD+TAB) to another window covering telegram window, vscode for instance
3. Mouse click on a place on a screen, where telegram resides (covered by vscode window)

### Expected behaviour
Mouse should interact with new window on top of telegram

### Actual behaviour
Sometimes mouse click brings telegram desktop window back on top instead

### Configuration
**Operating system:** MacOS 10.14.5
*This happened on previous MacOS versions also, like 10.13, so it is not version-specific*

**Version of Telegram Desktop:** 1.7.3
*This happened on previous TD versions, the issue is not new*

**Used theme**: Midnight

**Comment by andrii-rymar** [comment]
Having the same issue. It seems Telegram Desktop creates an invisible element which is displayed on top of any other opened windows.

<details>
<summary>Example (gif)</summary>

> ![telegram_desktop_macos_issue](https://user-images.githubusercontent.com/23473680/61637043-7f7a2680-ac9f-11e9-8050-7762cb49dd12.gif)

</details>
