### ISSUE TITLE
[Question]  Snap package for armhf not updated

### ISSUE THREAD

**Issue by AliDjango** [telegramdesktop/tdesktop#6222]
### Expected behaviour
Tdesktop version 1.7.10 must be available for armhf in snap packages
### Actual behaviour
Latest snap version available for armhf is 1.3.10

### Configuration
**Operating system:**
Raspbian on raspberry pi 3

**Comment by Aokromes** [comment]
i don't think arm packages maintenance belongs to here.

**Comment by Aokromes** [comment]
anyone?

**Comment by Aokromes** [comment]
acording preston:
Snap package is maintained by me with help from someone from canonical, but I never did armhf build, it was done once a long time ago and no one put any effort to it since.

**Comment by john-preston** [comment]
Now https://snapcraft.io/telegram-desktop has armhf and arm64 builds. Please check if they're OK.

**Comment by AliDjango** [comment]
I'll test ASAP.
just a question:Should we expect frequent updates for armhf build from now on?

**Comment by AliDjango** [comment]
I've tested the latest stable build for armhf
OS : Raspberry pi
I can confirm everything is working fine except that videos won't play.
I guess the problem is with VideoCore IV GPU that needs special code and video decoder to work

**Comment by AliDjango** [comment]
Audio files and Voice Messages don't work as well

**Comment by AliDjango** [comment]
Notifications don't have sound

**Comment by Aokromes** [comment]
plz open separate tickets for each issue you find.

**Comment by mishailovic** [comment]
Any chance that the snap package for raspberry pi will be updated? I want voice chats on raspberry pi

**Comment by ilya-fedin** [comment]
> Any chance that the snap package for raspberry pi will be updated?

ARM support is community maintained, someone should fix build on arm and send a PR
