### ISSUE TITLE
Can't access to porn-banned channel

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6224]
### Steps to reproduce
1. Update to 1.7.12
2. Try to open https://t.me/blyadtoivo for example
3. You can't
![image](https://user-images.githubusercontent.com/39812401/60755039-df5fa480-9ff2-11e9-9a45-c9bedf824b3c.png)

### Configuration
**Operating system:** Win 10 LTSC 1809

**Version of Telegram Desktop:** 1.7.12

**Used theme**: Default

With 1.7.11 all is fine.

Why iOS restrictions now on desktop client?

**Comment by Neurotoxin001** [comment]
![image](https://user-images.githubusercontent.com/39812401/60755855-67977700-9ffe-11e9-8f5a-8fcaf9241337.png)
Another reason.
https://t.me/tvrain_pirate

**Comment by Cloppershy** [comment]
It might be this change:
https://github.com/telegramdesktop/tdesktop/commit/567bf6064485a25da3c5d17f292246160f97c3da#diff-b99ddd9318c76137723d8b371d3ef526R615

Before, an unavailable reason was only set if `data.is_restricted()` is true. After the change, it is always set as long as `data.vrestriction_reason()` is not null. I'm not sure what the Telegram API returns, but if for some reason it returns a `vrestriction_reason` even if `is_restricted` is false, it would cause an issue.

**Comment by john-preston** [comment]
@Cloppershy Yes, there was a bug, I'll fix in the next version.

**Comment by 0xF6** [comment]
meh
![image](https://user-images.githubusercontent.com/13326808/60756559-5bfc7e00-a007-11e9-90a8-373bb0bc442b.png)

waiting for fix~ 🤗

**Comment by john-preston** [comment]
@Neurotoxin001 Should be fixed in 1.7.13.

**Comment by matiboux** [comment]
It is fixed. Thanks.

**Comment by Neurotoxin001** [comment]
Fixed, tnx.

**Comment by mehti1367** [comment]
Not Fixed in iran.

**Comment by Neurotoxin001** [comment]
> Not Fixed in iran.

In some countries like Iran you can't view banned channels even from desktop. Use web.telegram.

**Comment by vpapidokha** [comment]
The same one is for Ukraine on MacOS and iOS. Can you fix this?
![IMG_096F81332438-1](https://user-images.githubusercontent.com/20145156/67865987-ec1f7f80-fb30-11e9-990a-40e8c1ab456d.jpeg)
