### ISSUE TITLE
Image with captions in album is not highlighted on selecting

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#6227]
### Steps to reproduce
1. Send album with 2 or more images
2. Add captions to all of them
3. Try to select one image

### Expected behaviour
Selected image should be highlighted

### Actual behaviour
Selected image is not highlighted. Highlights are visible only when all photos in album are selected.

### Configuration
**Operating system:** Windows 7, Arch Linux

**Version of Telegram Desktop:** 1.7.12 beta ... 1.9.9

**Used theme**: Any

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.9?

**Comment by Remu-rin** [comment]
Yes.

**Comment by aNNiMON** [comment]
Works fine on 2.1.17 beta :tada:
