### ISSUE TITLE
Users can't see my animated stickers, but I can

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6229]
### Steps to reproduce
1. Download json animation, for example https://lottiefiles.com/7148-the-nyan-cat (https://assets1.lottiefiles.com/packages/lf20_jpxsQh.json)
2. Change file extension .json to .tgs
3. Drop this file to chat
4. You can see the animation, but other users see only file:

What I see
![image](https://user-images.githubusercontent.com/39812401/60758649-35980c00-a022-11e9-8ec5-2f99d903c4b7.png)

What users see
![image](https://user-images.githubusercontent.com/39812401/60758645-2fa22b00-a022-11e9-8c61-24ce7bc27168.png)

### Configuration
**Operating system:** Win10 LTSC 1809

**Version of Telegram Desktop:** 1.7.13

**Used theme**: Default

**Comment by john-preston** [comment]
@Neurotoxin001 This is not supposed to work, sorry :( .tgs is a special format, tdesktop indeed shows any lottie animation if sent with .tgs extension, but this is not how .tgs is supposed to be created.
