### ISSUE TITLE
proxy settings is not saved in built-in crash reporter

### ISSUE THREAD

**Issue by f242** [telegramdesktop/tdesktop#6232]
every crash i need to set up proxy in crash reporter for sucessfully sending crash report

**Comment by john-preston** [comment]
@f242 I hoped it won’t be needed that often 😭

**Comment by Aokromes** [comment]
> every crash i need to set up proxy in crash reporter for sucessfully sending crash report

if you add proxy, restart before it crashes it's remembered?

**Comment by f242** [comment]
> if you add proxy, restart before it crashes it's remembered?

i can't set proxy to crash reporter without crash
