### ISSUE TITLE
Animated stickers including image layer are not displayed

### ISSUE THREAD

**Issue by Jiyuu** [telegramdesktop/tdesktop#6233]
### Steps to reproduce
1. send animated sticker(.tgs file) which includes an image layer

### Expected behaviour
Both the image layer  and the regular layer should be displayed

### Actual behaviour
Only the regular layer is displayed while the image layer is not shown

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.7.13 

**Used theme**:
default

<details><summary><b>Details</b>:</summary>

Attached is an example animated sticker which includes both an image layer as well as a normal shape layer.
if you rename the file from tgs into json and upload it to 
http://rlottie.com/
you can see how it should be displayed.
</details>

[sample.zip](https://github.com/telegramdesktop/tdesktop/files/3365148/sample.zip)

**Comment by john-preston** [comment]
I think that the plugin for exporting .tgs from after effects won't even allow you to export image layers.

.tgs is not just a renamed .json, it is a limited format and should be exported by a fork of the original plugin.

**Comment by Jiyuu** [comment]
@john-preston
I figured it should be supported based on the fact that documentation for lottie at
https://github.com/airbnb/lottie-web/tree/master/docs/json says it should be supported,
Additionally the link i gave as an example for a site that shows proper image layers is a demo of the https://github.com/Samsung/rlottie/blob/master/README.md project,
Which as far as i understand is the library you use to support tgs on tdesktop as well.
So i expected it should work...

**Comment by john-preston** [comment]
@Jiyuu Sorry, but no, they don't work, only a limited subset of lottie format works in stickers.

**Comment by Jiyuu** [comment]
@john-preston
I see, so tgs is a limited subset of lottie specifically.
I the format documented anywhere or does it need it be reverse engineered from the Aftereffects plugin you linked to?

I would like to use a library to create such files instead of loading things into aftereffects manually ..

**Comment by john-preston** [comment]
@Jiyuu Well, it should be lottie json, 512x512, 30 or 60 fps, no more than 3 seconds, with some restrictions on the features used, compressed then with gzip.

**Comment by john-preston** [comment]
@Jiyuu Here are the requirements: https://core.telegram.org/animated_stickers

**Comment by Jiyuu** [comment]
@john-preston

Thank you for that!
Ill see if i can get something working.

Should i close the issue?
