### ISSUE TITLE
Telegram Desktop too long to start (2-3 minutes)

### ISSUE THREAD

**Issue by full-0** [telegramdesktop/tdesktop#6236]
### Steps to reproduce
1.  Install the latest version of Telegram Desktop for Mac
2. Launch Telegram Desktop

### Expected behaviour
Launch within less than 5 seconds

### Actual behaviour
Takes 2-3 minutes to launch. 

During launch TD tries to connect to one of network drives mapped in the past and not currently mapped. That repeats 3-4 times until TD finally launches.

Reinstalling does not help

Perhaps what can help is to completely remove all preferences and data used by TD to initiate a true fresh install - please advice how to do so

### Configuration
MacOS 10.14.5

**Version of Telegram Desktop:**
1.7.10

**Comment by lz233** [comment]
linux(zorinos) has same problem.

**Comment by cmbernard333** [comment]
Linux Mint 19 seeing the same issue with the tdesktop package from the website. The flatpak is out of date so I tried the native one from the desktop.

**Comment by syentix** [comment]
Same problem here on Pop_OS! 19.04. Got the tar.xz file from the website and started it through the terminal with `./Telegram`.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4576
