### ISSUE TITLE
Animated stickers play as 2 - 4 FPS with some mouse manipulation.

### ISSUE THREAD

**Issue by MairwunNx** [telegramdesktop/tdesktop#6238]
### Steps to reproduce
1. Go into a conversation in which there are 2 - 3 stickers at a sufficient distance from each other so that you can see them.
2. Click on one of these animated stickers and move the cursor a couple of pixels.
3. Just enjoy.

### Expected behaviour
Stickers must in any case be reproduced in 60 FPS.

### Actual behaviour
Stickers with certain mouse manipulations are reproduced in 2 - 4 FPS.

### Configuration
**Operating system:** `Windows 10 1809 17763.593`

**Version of Telegram Desktop:** `1.7.13`

**Used theme**: `Midnight`

**Comment by NickKush** [comment]
Same here. Srange behaviour
![8NQFRAwELj](https://user-images.githubusercontent.com/10407618/60838246-f230cf80-a1d2-11e9-94ff-e43ac02dfe70.gif)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
it looks fixed to me on 1.9.8

**Comment by MairwunNx** [comment]
Yes, bug is still valid. I can record video or gif on latest beta version.

**Comment by Aokromes** [comment]
strange for me it works fine, you have a potato machine?

**Comment by MairwunNx** [comment]
@Aokromes joke is as thin as a needle. It's easy to reproduce.

Configuration: 

## i7 4771 3.9GHz, 14GB DDR3 1600, GTX 960 2GB.

**Comment by Aokromes** [comment]
strange, i have one hexacore xeon with same gfx and cannot reproduce the bug.

**Comment by MairwunNx** [comment]
I can record again with enabled mouse pointer on video, for better demonstrating.

**Comment by NickKush** [comment]
> this bug is still valid?

Yes, still valid. 
Telegram version 1.8.15
On Windows 10 and Ubuntu 18.04 it works

**Comment by Aokromes** [comment]
plz don't report bugs on non-updated versions.

**Comment by NickKush** [comment]
Oops. Sorry. Telegram don't have an update on apt. 
Updated from official site to 1.9.8 version. Still have the issue

**Comment by VadVergasov** [comment]
Still exists on 2.4.3 but looks different: they are just slowing down. But when you leave the cursor all will be fine after a few seconds.
Windows 10 x64 Home 2004.

**Comment by gorghino** [comment]
Still valid with Telegram 2.7.1 (official binary). Even dragging just one sticker on the screen, its speed decreases to few fps.
Even gifs are slowed down.

gorgo@pop-os 
------------ 
OS: Pop!_OS 20.10 x86_64 
Host: Blade 15 Advanced Model (Early 2020) - RZ09-033 5.04 
Kernel: 5.8.0-7642-generic 
Shell: bash 5.0.17 
Resolution: 4384x2466 
DE: GNOME 3.38.3 
WM: Mutter 
Terminal: gnome-terminal 
CPU: Intel i7-10875H (16) @ 2.300GHz 
GPU: Intel UHD Graphics 
Memory: 5497MiB / 15867MiB
