### ISSUE TITLE
[Feature Request] Support Custom Thumbnail on videos

### ISSUE THREAD

**Issue by mehti1367** [telegramdesktop/tdesktop#6239]
It would be nice there is a ability to customize thumbnail of videos like youtube , telegram just sets first frame as a thumbnail for videos.

**Comment by Neurotoxin001** [comment]
There is will be a bunch of clickbait garbage, if it's become as feature.

**Comment by Kurdaitcha** [comment]
I guess this makes sense, I have never really needed to set a custom thumbnail like on YouTube using Telegram but the ability to select a specific frame of a video would be helpful to me as sometimes the first frame on a series of videos is just black and doesn't really make sense as a preview even when blurred.
