### ISSUE TITLE
[Feature Request] Wrap message with stickers when forward

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6240]
### Is your feature request related to a problem?
![image](https://user-images.githubusercontent.com/7231077/60770241-8f6a0600-a0f6-11e9-8983-6f6e0e81aeed.png)

**Comment by SmartManoj** [comment]
Why invalid

**Comment by 23rd** [comment]
You asked to update the templates, but still ignore them.
You have not provided any text and I have no any idea what you are asking.

**Comment by SmartManoj** [comment]
> You asked to update the templates, but still ignore them.
> You have not provided any text and I have no any idea what you are asking.

Could you add description as placeholders in template.
I think the image is clear enough

**Comment by SmartManoj** [comment]
When forwarding a message , I use stickers as separators.

Currently , I send a sticker, then forward message , then again send a sticker.

Instead of doing this , I want to send the stickers automatically
