### ISSUE TITLE
[Question] API issue

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6241]
Why tdesktop doesn't implement features in desktop only?
There are lot of issues 
https://github.com/telegramdesktop/tdesktop/issues/5187#issuecomment-509006741
https://github.com/telegramdesktop/tdesktop/issues/6185#issuecomment-508923088
https://github.com/telegramdesktop/tdesktop/issues/1165#issuecomment-147090376

**Comment by RememberTheAir** [comment]
Telegram cares a lot about consistency among their apps. Different Telegram clients should have a similar behavior, when people use a feature from eg. tdesktop they expect to find it on the mobile apps too

**Comment by SmartManoj** [comment]
Then what about secret chats in tdesktop?

**Comment by 23rd** [comment]
> Then what about secret chats in tdesktop?
Priorities are still far from secret chats.

Please do not duplicate existing open issues, I added this template not for this.
