### ISSUE TITLE
High CPU usage after some time of using

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6242]
### Steps to reproduce
1. Just use telegram for some time (I use it from 1:20 to 9:12), send gifs/stickers/messages in chats/conferences
2. Open task manager
3. You can see 10-12% cpu usage even if it hidden in tray. CPU temperature is UP too (on 5-7 degrees):
![image](https://user-images.githubusercontent.com/39812401/60786996-1c49a980-a161-11e9-83f6-931e1f6c716d.png)

Restart the app is helps. After restart it's 0-1% in tray and 3-5% with active window of app.

### Configuration
**Operating system:** Win10 LTSC 1809

**Version of Telegram Desktop:** 1.7.14 (same on 1.7.13)

**Used theme**: Default

https://pastebin.com/A3SDN5uw

**Comment by Neurotoxin001** [comment]
Pls somehow catch this bug and fix it, tired to restart telegram. In logs no "critical" errors or changes compared with log in first post here.

**Comment by Neurotoxin001** [comment]
Ok, seems like I found problem.

When I go to "Advanced" settings and then "Manage local storage" I see "Summary -298423746238428374", so I think issue was there. I press "clear all" and now all is fine, for now. Here is my settings in this menu:
![image](https://user-images.githubusercontent.com/39812401/61189435-38d06f00-a696-11e9-8f9a-6c8213779319.png)

**Comment by Neurotoxin001** [comment]
Nope, it's not "Manage local storage" issue.

Here is another log:
https://pastebin.com/ZMQ5tZdq

**Comment by Neurotoxin001** [comment]
With interface animation disabled I can't reproduce this issue, so I think that option is the problem.

**Comment by Neurotoxin001** [comment]
Still no issues with disabled animation, please check it.

**Comment by Neurotoxin001** [comment]
Same issue in 1.7.15

**Comment by Neurotoxin001** [comment]
Seems like it's fixed after I reinstall app...

**Comment by Neurotoxin001** [comment]
Nope, not fixed even with disabled animation, 1.7.15

**Comment by Neurotoxin001** [comment]
Wtf is this?
![image](https://user-images.githubusercontent.com/39812401/62551671-184e9b80-b875-11e9-9c47-77f7450a73b2.png)

**Comment by Neurotoxin001** [comment]
Obvious memory leak here.

**Comment by john-preston** [comment]
@Neurotoxin001 This looks like int32 overflow, not a memory leak. All sizes should be in int64 there, but I guess somewhere it got converted.

**Comment by Neurotoxin001** [comment]
I wondering why there is no one with this issue but me.

**Comment by Neurotoxin001** [comment]
It's still not fixed
![image](https://user-images.githubusercontent.com/39812401/63295939-94fe6280-c2d6-11e9-80a1-ab27e7f69437.png)
1.8.1

**Comment by SnejUgal** [comment]
I experience the same issue on Ubuntu 18.04 with Telegram v1.8.1 from Flathub, and I experienced it on earlier versions too. I notice it when I simply switch chats or even just leave some chat open for some time without even interacting with it at all.

**Comment by Aokromes** [comment]
In case someone knows how to fix, debug build 1.8.13 running under ubuntu linux x64

https://gist.github.com/37b7ee627100c703518b6586a1ed9713

**Comment by Neurotoxin001** [comment]
Seems like it's still not fixed even in 1.8.15 

![image](https://user-images.githubusercontent.com/39812401/67078767-9c3cd200-f19a-11e9-8453-0e9e965ecc82.png)

**Comment by HankAviator** [comment]
It's been an outstanding issue for a while, observed on Windows 10. Didn't pay much effort to investigate it though, but it's been always there.

**Comment by Aokromes** [comment]
try after https://github.com/telegramdesktop/tdesktop/commit/5f5d5629f8e36f4eb6f9c478eb1b76a4cdb08b17

**Comment by Neurotoxin001** [comment]
Ok, I will use 1.9.6 for ~48h and answer if this crash still happens.

**Comment by HankAviator** [comment]
Issue still persists.
Stack for process:
```
ntoskrnl.exe!KeSynchronizeExecution+0x5b76
ntoskrnl.exe!KeWaitForMutexObject+0x1c2d
ntoskrnl.exe!KeWaitForMutexObject+0xab4
ntoskrnl.exe!KeWaitForMutexObject+0x255
ntoskrnl.exe!KeTestAlertThread+0x25a7
ntoskrnl.exe!KeWaitForMutexObject+0x3828
ntoskrnl.exe!KeSynchronizeExecution+0x3132
Telegram.exe!?setDrawRegion@Surface@rlottie@@QAEXIIII@Z+0x2e4efb
```

**Comment by Neurotoxin001** [comment]
After ~24h of using seems all is fine, % of cpu usage is ok, ram usage ok too.

**Comment by HankAviator** [comment]
I got 40%+ CPU usage for prolonged time while having laptop plugged in and lid closed but didn't know what to attach here.

**Comment by Neurotoxin001** [comment]
1.9.7 no issues too.

**Comment by arghfrank** [comment]
started for me with 1.9.14 - after a while (a few hours, usually) cpu load goes to 20-30%. quitting & restarting "helps", but .. :-|

**Comment by atonn** [comment]
on Linux, this usually only happens to me when a GIF is playing in the current window, even when minimized

**Comment by Neurotoxin001** [comment]
Don't saw this issue since 1.9.8
