### ISSUE TITLE
Cannot render some characters after update  v 1.7.13 06.07.19

### ISSUE THREAD

**Issue by xceejay** [telegramdesktop/tdesktop#6243]
### Steps to reproduce
1. 
![bug](https://user-images.githubusercontent.com/44475401/60800549-ef979100-a164-11e9-9770-4be4ce5a0834.png)
![bug1](https://user-images.githubusercontent.com/44475401/60800569-f6be9f00-a164-11e9-9ffb-207a5423c899.png)

### Expected behaviour
Tell us what should happen
I could see the characters before update to v 1.7.13 06.07.19
### Actual behaviour
Tell us what happens instead
A box appears instead of the actual characters
### Configuration
**Operating system:**
Linux Debian Buster(10)

**Version of Telegram Desktop:**

**Used theme**:
Modified Midnight

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
works for me on 1.7.14 and debian 9, for sure it's something on debian 10.

**Comment by Aokromes** [comment]
works for me on fully updated debian 10.
