### ISSUE TITLE
Animated stickers shown with wrong colors

### ISSUE THREAD

**Issue by hsantanna** [telegramdesktop/tdesktop#6247]
### Steps to reproduce
1. Insert an animated sticker
2. Wait few seconds (like 5 or less)
3. The animated sticker will start to show up with wrong colours

### Expected behavior
The animated stickers should continue to play with the right colors

### Actual behavior
After few seconds playing, the animated stickers get the colors changed to wrong colors and keep playing with the wrong colors.

### Configuration
Arch Linux:
`Linux 5.1.16-zen1-1-zen #1 ZEN SMP PREEMPT Wed Jul 3 20:25:07 UTC 2019 x86_64 GNU/Linux`
`mesa 19.1.1`
`KDE Plasma Desktop 5.16.2`

**Version of Telegram Desktop:**
`Telegram 1.7.14-1`
(installed from community-testing Arch Linux repository)

**Used theme**:
`Classic theme with the gray dogs and cats background. `
Tested with other backgrounds too, but with the gray dogs and cats background the colors from animated stickers goes really bad.

![Screenshot_20190708_123106](https://user-images.githubusercontent.com/982230/60824883-da306000-a180-11e9-8af8-963216c31462.png)
![Screenshot_20190708_123354](https://user-images.githubusercontent.com/982230/60824893-def51400-a180-11e9-92d3-b997836c7b09.png)
![telegram-background](https://user-images.githubusercontent.com/982230/60824909-e74d4f00-a180-11e9-9db7-54c5a2f8155a.jpg)

**Comment by louwers** [comment]
![image](https://user-images.githubusercontent.com/649392/60848367-a0924000-a1e6-11e9-990c-de6eb28eff44.png)
For me most stickers show up with the right colors, but the outlines are pixelated.

**Comment by farseerfc** [comment]
Please upgrade to 1.7.14-2 and that should fix this. 1.7.14-1 was a partial patch that had this problem, and I came up with a fix for that patch. See also https://github.com/telegramdesktop/tdesktop/issues/6219
