### ISSUE TITLE
Misaligned messages when exporting

### ISSUE THREAD

**Issue by AndrewLaneX** [telegramdesktop/tdesktop#6248]
### Steps to reproduce
1. Change your first name to `<` and last name to `💩`
1. Send a message to a chat
1. Export that chat

### Expected behaviour
Tell us what should happen
![image](https://user-images.githubusercontent.com/32808683/60836716-4c5e7000-a194-11e9-85a6-53a0a87f6f4f.png)

### Actual behaviour
Tell us what happens instead
![image](https://user-images.githubusercontent.com/32808683/60836595-04d7e400-a194-11e9-86be-7012866a18c8.png)

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.7.14

**Comment by YouTwitFace** [comment]
It seems to be because it adds `<?` and breaks the html.

**Comment by Aokromes** [comment]
yeah very likely missing escape for <
