### ISSUE TITLE
 Characters on buttons are blank

### ISSUE THREAD

**Issue by viktor-bushmin** [telegramdesktop/tdesktop#6249]
### Steps to reproduce
1. Try to add sticker pack
2. Chars on buttons are blank

### Expected behaviour
All chars on buttons should be readable

### Actual behaviour
Some characters are blank
Fixed after apllication restart

### Configuration
Windows 10 Pro

1.7.14

**Used theme**:
Classic
![Снимок](https://user-images.githubusercontent.com/38643520/60861924-bb83a500-a224-11e9-9971-ef8631c5522a.PNG)
![Снимок1](https://user-images.githubusercontent.com/38643520/60861925-bb83a500-a224-11e9-8a19-84a47cc8c571.PNG)

**Comment by SmartManoj** [comment]
Is it happen every time

**Comment by viktor-bushmin** [comment]
No, it was one time. Never see that again.
