### ISSUE TITLE
(v 1.7.14, Windows10) Scrobbling through animated stickers cause app crash 

### ISSUE THREAD

**Issue by mehti1367** [telegramdesktop/tdesktop#6253]
![bug](https://user-images.githubusercontent.com/34035991/60890580-ccf29e80-a270-11e9-8b97-41a08277aef9.gif)

**Comment by john-preston** [comment]
Please post your crash report tag here. (from the submit crash report window)

**Comment by mehti1367** [comment]
@john-preston 

```
ApiId: 2040
Assertion: "offset >= 0 && size() - offset >= 0" span:555
Binary: tback2.exe
Launched: 09.07.2019 17:23:41
Platform: Windows
UserTag: 412624fff674f1f5
Version: 1007014
Memory-usage: 80 MB (peak), 59 MB (current)
Pagefile-usage: 74 MB (peak), 74 MB (current)

Google Breakpad caught a crash, minidump written in thread 19656
Minidump: 8b7d3e19-af0b-4cc9-b763-7a05f3144733

Backtrace omitted.

```

**Comment by john-preston** [comment]
@mehti1367 I need the crashdump :( Please copy the report tag from the "send crash report" window, then submit the report and then write the tag here.

**Comment by mehti1367** [comment]
ok:

```
Your Report Tag: fd5c9023-8fc4-40ea-9e62-240c5285a70c
Your User Tag: 412624fff674f1f5

```

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 1 month, if this bug is still valid, open a new ticket with one updated telegram version downloaded from desktop.telegram.org or github.com
