### ISSUE TITLE
[Question] Is there an implicit 1MiB limit for uncompressed animated stickers?

### ISSUE THREAD

**Issue by bodqhrohro** [telegramdesktop/tdesktop#6254]
I handicrafted [an animated sticker](https://0x0.st/zLtD.tgs) with a lot of rectangles. Due to it's homogeneous structure, it is compressed quite well, giving 25.3 KiB (which meets the specified 64KB limit), but uncompressed JSON has 1.5 MB size.

While lottie-web displays the JSON correctly, telegram-desktop has some issues. There is no preview:
![2019-07-09-161315_1366x768_scrot](https://user-images.githubusercontent.com/2134486/60890761-a595d480-a264-11e9-94ec-0e2bef2a5254.png)
and when I add such a sticker to a pack, it's displayed either transparent or as a blurred static image:
![2019-07-09-161608_1366x768_scrot](https://user-images.githubusercontent.com/2134486/60890940-00c7c700-a265-11e9-9cd4-72840d9ddc9f.png)

By experimenting with the number of layers and rectangles, I finally noticed that this starts happening when the size of **uncompressed** data exceeds 1 MiB. Is this an undocumented limitation or a bug?

**Comment by john-preston** [comment]
@bodqhrohro Yes, there is an inner limit for 1 MB. After some real stickers (not gzip-bombs) having slightly more than 1.1 MB I decided to increase the limit to 2 MB (this one will be in iOS app as well).

We need to place some limit. I think 2 MB is more than enough for any real world thing.

**Comment by bodqhrohro** [comment]
OK, thanks. Now it turns out that the size of repetitive data actually matters. There is, for example, an issue with transformations shapes, which makes it needed to redundantly specify transformation properties (a/p/s/r/o), even though there are default values for them in the JSON schema. But it should be adressed to Bodymovin team, as it crashes not only Telegram, but upstream Lottie parsers as well.
