### ISSUE TITLE
Regarding tdesktop-closer 

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6255]
tdesktop-closer  closes [Feature Request]  too like https://github.com/telegramdesktop/tdesktop/issues/4523.
So let it close except Feature Request Labels https://github.com/telegramdesktop/tdesktop/pull/6202#issuecomment-508921158

**Comment by SmartManoj** [comment]
@tdesktop-closer Don't close issues if the last comment is from Author

**Comment by SmartManoj** [comment]
Use https://github.com/apps/no-response
Sample https://github.com/soscripted/sox/issues/406

**Comment by SmartManoj** [comment]
@Aokromes Could you exclude enhancement label in stale bot ASAP?
Got a 32 notification

**Comment by ilya-fedin** [comment]
> Could you exclude enhancement label in stale bot ASAP?

It is handy to close feature requests no one interested for
