### ISSUE TITLE
[Feature Request] Enhance Share panel

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6256]
### Is your feature request related to a problem?

 Filter search in Share panel

### Describe the solution you'd like

A filter icon 
Enable Dragging to select chats

**Comment by RememberTheAir** [comment]
Filter what?

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/60894516-78571f80-a280-11e9-9281-cc56be337734.png)
If we want to send all friends whose name starts with A, we have to search for A all time , also hide selected users

**Comment by SmartManoj** [comment]
also enable Dragging to select chats

**Comment by SmartManoj** [comment]
Workaround - use undo
