### ISSUE TITLE
Underline not working

### ISSUE THREAD

**Issue by luxarts** [telegramdesktop/tdesktop#6257]
### Steps to reproduce
1. Write some text in a chat between `^^`. E.g. `^^Hello world^^`
2. Press send

### Expected behaviour
Message with underline.

### Actual behaviour
Plain text message. E.g. ^^Hello world^^

### Configuration
**Operating system:**
Windows 10 Pro 10.0.17763 (build 17763) 

**Version of Telegram Desktop:**
1.7.14

**Used theme**:
Default

**Comment by SmartManoj** [comment]
Press Ctrl U

**Comment by john-preston** [comment]
Underline works using Ctrl+U (Cmd+U on macOS) or through the right-click menu.
