### ISSUE TITLE
Caret moving to text field beginning if using Ctrl+ArrowUp to reply to a message

### ISSUE THREAD

**Issue by p0358** [telegramdesktop/tdesktop#6259]
### Steps to reproduce
1. Start typing something in a chat
![obraz](https://user-images.githubusercontent.com/5182588/60941384-432dea00-a2df-11e9-930f-da3b7b3979a0.png)
2. Press Ctrl+ArrowUp one or more times to select a message to which you want to reply
![obraz](https://user-images.githubusercontent.com/5182588/60941423-648ed600-a2df-11e9-9351-c99cfc5e5370.png)

### Expected behaviour
Caret/cursor should stay in the same place (ex. at the end of the text field), so we can continue typing as if nothing happened.

### Actual behaviour
Caret/cursor is moved to the beginning of the text field (as if you pressed Home button), so you have to put it again in the place it was before, for example by pressing End button to go to the end.
It probably comes from an assumption that user would first select a message to reply to and then start writing text, and that's why it was missed, but I find myself doing it the opposite way most of the time.

### Configuration
**Operating system:** Windows 10 1809

**Version of Telegram Desktop:** 1.7.14

**Used theme**: custom

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by 23rd** [comment]
#6038.
