### ISSUE TITLE
[Bug] [Windows] Switch to Telegram window (Alt+Tab) consumes CPU and freeze Telegram for a few seconds

### ISSUE THREAD

**Issue by ezdev128** [telegramdesktop/tdesktop#626]
Switch to Telegram window (Alt+Tab) consumes CPU and freeze Telegram (0.8) for a few seconds.
Only on Windows (XP SP3) desktop. Have not tested on Windows7/8/10.
Doesn't appears on Linux.
![Task manager](http://s22.postimg.org/voso178g1/switch_window_to_telegram.png)

**Comment by SanKro** [comment]
you should consider to switch to another OS
http://windows.microsoft.com/en-US/windows/end-support-help

XP isnt anymore and telegram should not support an dead end

**Comment by ezdev128** [comment]
It could be a problem with 7/8/etc too, not only with XP, I just haven't any of them.
Any else thoughts?

**Comment by AryanShadowhunter** [comment]
I have windows 8 and when i switch to telegram, CPU utilization will only increase by about 3%
As @SanKro Said, Updating your OS to Windows 7 / 8 / 8.1 / 10 may solve this issue.

**Comment by SanKro** [comment]
i think Telegram for windows requires a desktop with compositing possibily, so everything from Vista.
Thats also the reason why telegram for windows dont run that well in wine.

**Comment by ezdev128** [comment]
@SanKro I don't agree with your opinion. 
I think It should be very flexible and tolerate to OS, should be very lightweight and consume the least resources, especially, desktop compositing/Aero.
This messenger SHOULD NOT turn into a Skype, in a very ponderous and buggy monster.

**Comment by SanKro** [comment]
@ezdev128 it *is* flexible, lightwight and tolerate every OS ... every OS that still has support!

there is no reason to tolerate or develop for windows XP. it is old, insecure and everything that forces users to switch to something modern is a good thing because of that.

i wouldnt use telegram if it would be a messy thing like skype, but beside a few ugly bugs on some systems, its a good thing. it even respecs the windowmanager on different linuxes...

**Comment by ezdev128** [comment]
@SanKro As I said before, I saw no issues on any linuxes I tried. 
Btw, 
> there is no reason to tolerate or develop for windows XP. it is old, insecure *and everything that forces users to switch to something modern is a good thing because of that.* - that is kind marketing and tricks to force people to buy stronger computers and new software. And, of course, it's definitely holy war between NT 5.1 and >5.1.

**Comment by auchri** [comment]
It's normal that switching between programs needs a little cpu power. Get a better hardware if your system can't handle this
