### ISSUE TITLE
[1.7.14] Mouse clicks in image viewer don't work

### ISSUE THREAD

**Issue by chrisgbk** [telegramdesktop/tdesktop#6260]
### Steps to reproduce
1. Click on an image in a chat to open full view
2. Attempt to use the clickable arrows on the sides or the X in the top right
3. Clicks are ignored.
4. Note: I have a touchscreen and a USB mouse. The touchscreen works fine in this window, just the mouse doesn't work. Was working in previous versions. No other telegram window is affected.

### Expected behaviour
Image should be replaced with previous or next, or the viewer should close.

### Actual behaviour
Clicks and mouse movement are ignored, and occasionally end up being captured by other telegram windows. If you spam right click on the text entry box while the image viewer is open, by positioning so you can see it on the side of the image, eventually the menu will open and after a few more right clicks the image viewer will accept mouse clicks. This only lasts until the image viewer is closed.

### Configuration
**Operating system:** Windows 7

**Version of Telegram Desktop:** 1.7.14

**Used theme**: Night mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Aokromes** [comment]
i don't have seen this bug for long.
