### ISSUE TITLE
How to create new stickerpack from other people stickers ? [Question] 

### ISSUE THREAD

**Issue by ASHIT-AXAR** [telegramdesktop/tdesktop#6261]
most of the stickers in a pack are useless (but some of those) for me. i have +25 packs with 30~100 stickers each.
is there a way to collect my favorite ones (from multiple packs) into a new custom pack ?

**Comment by RememberTheAir** [comment]
You have to use the official bot [@stickers](https://t.me/stickers) to create your packs, otherwise have a look at [@MyPackBot](https://t.me/MyPackBot) or [@stickersthiefbot](https://t.me/stickersthiefbot). Or ask the in-app support, it's off-topic here

**Comment by ASHIT-AXAR** [comment]
thank you.
@stickersthiefbot was so helpful
later i found @ezstickerbot better match.
