### ISSUE TITLE
Smiles button overflows bottom panel

### ISSUE THREAD

**Issue by igoradamenko** [telegramdesktop/tdesktop#6264]
# Steps to reproduce
1. Open Telegram Desktop 1.7.14.
2. Open any chat.
3. Check the smiles/stickers/emojis button.

### Expected behaviour
It shouldn't be placed beyond the borders of the bottom line.

### Actual behaviour
It's placed. Check the area above the button on the screenshot. There's a white border.

![image](https://user-images.githubusercontent.com/6537798/60946181-3b2d7480-a2f6-11e9-870f-9f9712bdb732.png)

### Configuration
**Operating system:** macOS 10.13.6

**Version of Telegram Desktop:** 1.7.14

**Used theme**: Default I guess. Here is what my settings look like:

![image](https://user-images.githubusercontent.com/6537798/60946305-8cd5ff00-a2f6-11e9-9630-c4fb12706cdb.png)

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/61185409-cc924300-a676-11e9-8050-bfeedaaa14b9.png)
