### ISSUE TITLE
Cannot build openssl

### ISSUE THREAD

**Issue by UniqueUname** [telegramdesktop/tdesktop#6265]
### Steps to reproduce
1.  Configure openssl
2. 
3. 

### Expected behaviour
It should do stuff and print out no errors

### Actual behaviour
This happens: 
```
>perl util\mk1mf.pl dll no-asm VC-WIN32  1>ms\ntdll.mak
unknown option - Files
unknown option - (x86)\OpenSSL
unknown option - Files
unknown option - (x86)\Common
unknown option - Files\SSL
````

### Configuration
**Operating system: Windows 10**

**Version of Telegram Desktop: Freshly pulled from master, until commit https://github.com/telegramdesktop/tdesktop/commit/9c909c8992ab52b278c718ecf50c9ac41fb207a6**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

Although I exactly copied commands from guide to my dev prompt, this still happens. I tried to set it to a different folder but no luck, it still tried to install it to C:\Program Files (x86)\OpenSSL
I even tried to create symlink directories to C:\Program Files (x86) and C:\Program Files (x86)\Common Files\
It looked like it worked at first place but it didn't do anything, there were no files created on these folders after building it.

**Comment by SmartManoj** [comment]
Version of Telegram Desktop: Lastest atm - 1.7.14?

**Comment by UniqueUname** [comment]
Okay, I fixed it myself and I now feel like giant glowing brain
Although the perl is acting up, the build wouldn't even work even if the perl configured openssl libraries to program files folder because you never install openssl libraries to said location.
What I did was I created a folder to install release and debug openssl files seperately
```
perl Configure no-shared --prefix="C:\(any location that does not have any space on its path)\OpenSSL" --openssldir="C:\(any location that does not have any space on its path)\SSL" VC-WIN32
```
Same goes for the debug but with a different path
after ``nmake -f ms\nt.mak``, you have to run ``nmake -f ms\nt.mak install`` or it won't install required libraries.
Then, while configuring the qt, I used these paths and it worked, hooray.
