### ISSUE TITLE
[Feature Request] View Telegram at a specific date

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6267]
### Is your feature request related to a problem?
It is hard to find which users we send particular message at a particular time

### Describe the solution you'd like
Hide message after the date

**Comment by RememberTheAir** [comment]
You can search by date on any Telegram app

**Comment by SmartManoj** [comment]
> You can search by date on any Telegram app

This applies for one chat only

**Comment by SmartManoj** [comment]
We could search the particular message directly

**Comment by SmartManoj** [comment]
Is it possible to send another message to the users ( around 20) ?
If we view Telegram at a specific time, they appear by last used order in share panel .

**Comment by SmartManoj** [comment]
Sample Use case

We send a photo to some users. After some time if we want to delete it , it is hard to find

**Comment by SmartManoj** [comment]
https://t.me/tgbeta/4192
