### ISSUE TITLE
[Bug] Sticker window is not responding and crash

### ISSUE THREAD

**Issue by seriogatatarinov** [telegramdesktop/tdesktop#6271]
### Steps to reproduce
1. Mouse over smile button
2. Click on gear wheel

![image](https://user-images.githubusercontent.com/11258276/61033800-d729af80-a3cc-11e9-9b42-7da7670f46b6.png)

### Expected behaviour
Sticker window is open

![image](https://user-images.githubusercontent.com/11258276/61033408-1d324380-a3cc-11e9-9367-4299c984fbf9.png)

### Actual behaviour
Telegram Desktop is not reponding and crashing

![image](https://user-images.githubusercontent.com/11258276/61033446-33d89a80-a3cc-11e9-941f-69e5c8480678.png)

### Configuration
**Operating system:** Windows 10 1803

**Version of Telegram Desktop:** 1.7.14

**Used theme**: Midnight

<details><summary><b>Logs</b>:</summary>

> [2019.07.11 11:01:01] Launched version: 1007014, install beta: [TRUE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
> [2019.07.11 11:01:01] Executable dir: D:/Programs/Telegram Desktop/, name: Telegram.exe
> [2019.07.11 11:01:01] Initial working dir: D:/Programs/Telegram Desktop/
> [2019.07.11 11:01:01] Working dir: D:/Programs/Telegram Desktop/
> [2019.07.11 11:01:01] Command line: D:\Programs\Telegram Desktop\Telegram.exe
> [2019.07.11 11:01:01] Executable path before check: D:/Programs/Telegram Desktop/Telegram.exe
> [2019.07.11 11:01:01] Logs started
> [2019.07.11 11:01:01] Connecting local socket to Global\06d8495464a1d998c68c23d716c242a3-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
> [2019.07.11 11:01:01] This is the only instance of Telegram, starting server and app...
> [2019.07.11 11:01:01] Moved logging from 'D:/Programs/Telegram Desktop/log_start0.txt' to 'D:/Programs/Telegram Desktop/log.txt'!
> [2019.07.11 11:01:01] Opened 'D:/Programs/Telegram Desktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 351
> [2019.07.11 11:01:02] Update Info: MTP is unavailable.
> [2019.07.11 11:01:02] App Error: _basePath is empty in writeSettings()
> [2019.07.11 11:01:32] Crash report check for sending done, result: Report
> [2019.07.11 11:01:33] Crash report sending done, result: Done
> [2019.07.11 11:01:42] Primary screen DPI: 96
> [2019.07.11 11:01:43] App Info: reading settings...
> [2019.07.11 11:01:43] App Info: reading encrypted settings...
> [2019.07.11 11:01:43] Lang Info: Loaded cached, keys: 2396
> [2019.07.11 11:01:43] Lang Error: Unexpected tag (key 'lng_call_box_status_group:count')
> [2019.07.11 11:01:43] Lang Error: Unknown tag (key 'lng_manage_discussion_group_warning:visible')
> [2019.07.11 11:01:43] OpenAL Logging Level: (not set)
> [2019.07.11 11:01:43] Audio Playback Devices: OpenAL Soft
> [2019.07.11 11:01:43] Audio Playback Default Device: OpenAL Soft
> [2019.07.11 11:01:43] Audio Capture Devices: OpenAL Soft on РњРёРєСЂРѕС„РѕРЅ (Realtek High Definition Audio);OpenAL Soft on FrontMic (Realtek High Definition Audio)
> [2019.07.11 11:01:43] Audio Capture Default Device: OpenAL Soft on РњРёРєСЂРѕС„РѕРЅ (Realtek High Definition Audio)
> [2019.07.11 11:01:43] App Info: reading map...
> [2019.07.11 11:01:43] App Info: reading encrypted map...
> [2019.07.11 11:01:43] App Info: reading encrypted user settings...
> [2019.07.11 11:01:43] App Info: encrypted user settings read.
> [2019.07.11 11:01:43] App Info: reading encrypted mtp data...
> [2019.07.11 11:01:43] MTP Info: read keys, current: 5, to destroy: 0
> [2019.07.11 11:01:43] Map read time: 91
> [2019.07.11 11:01:43] Export Info: Destroy top bar by controller removal.
> [2019.07.11 11:01:43] Window Shadow: 1, 1, 3, 4, 6, 9, 13, 18, 24, 31, 38, 46

</details>

**Comment by SmartManoj** [comment]
Include report

**Comment by john-preston** [comment]
I need a crash report tag. Next time you see the send report window please copy the string after "Your Report Tag", then send the crash report and after that send the tag here.

**Comment by SmartManoj** [comment]
Use of crash report tag?

**Comment by seriogatatarinov** [comment]
> I need a crash report tag. Next time you see the send report window please copy the string after "Your Report Tag", then send the crash report and after that send the tag here.

da05fffc-fd74-457c-9ce9-1863f4422f9a
