### ISSUE TITLE
[Feature Request] Mark as Read Button inside notifications

### ISSUE THREAD

**Issue by giupardeb** [telegramdesktop/tdesktop#6272]
### Is your feature request related to a problem?
NO

### Describe the solution you'd like
insert a button 'Mark as read' near a ''Reply'' button

![image_2019-07-11_10-13-07](https://user-images.githubusercontent.com/4471950/61034208-210e9780-a3c5-11e9-9200-705c122c4a97.png)

Thank you so much for your work!

**Comment by john-preston** [comment]
@giupardeb Just press Reply and then Enter :)

**Comment by RememberTheAir** [comment]
As it has already been said in #3803, the current way of marking as read is not really obvious and the only way to know it works like that is to come here and search for the issue

**Comment by giupardeb** [comment]
ah @john-preston ... I did not know...but I agree with @RememberTheAir a button would be better..

**Comment by john-preston** [comment]
@giupardeb I made a button there first, but it was awfully large and attracted too much attention.

**Comment by giupardeb** [comment]
mmm.. I understood..it would be created a 'minibutton' or when you click on 'X' button, automatically the messages was marked as read.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/4393
