### ISSUE TITLE
Can't register phone number - Invalid phone number(?) +36 50 ....

### ISSUE THREAD

**Issue by Riflerat** [telegramdesktop/tdesktop#6273]
### Steps to reproduce
Settings -> Edit profile -> Phone number -> Change Phone Number -> New phone number ->Entering new phone number: +36 50 xxx xxxx -> Error message: Invalid phone number. Please try again

Same happens trying to register the phone number beginning +36 50 ... as a new number.

### Actual behaviour
I can't register phone number.
My phone number beginning: +36 50....

### Configuration
OS:
Linux, Android

**Version of Telegram Desktop:**
1.7.14

**Comment by SmartManoj** [comment]
api issue
