### ISSUE TITLE
Bad rendering while scrolling in the chat area

### ISSUE THREAD

**Issue by M1que4s** [telegramdesktop/tdesktop#6274]
While I scroll in the chat area, I seen this problem.
![Telegram render Issue](https://user-images.githubusercontent.com/31262466/61054343-43041c00-a3bd-11e9-80ce-cd2d71cff2ef.png)

### Steps to reproduce
1. Put the mouse over any chat
2. Then scroll without move the mouse

### Expected behaviour
Each chat should be seen clearly without problems

### Actual behaviour
When scroll, the chats are blurred or duplicated as shown in the image

### Configuration
**Operating system:** Linux Mint 19.1 Tessa

**Version of Telegram Desktop:** 1.7.14

**Used theme**: Custom ("Falling Leaves", downloaded from [Desktop Themes](https://t.me/themes) channel)

**Comment by john-preston** [comment]
@M1que4s This is a theme bug, some keys should not have transparent values, otherwise the effects are unpredictable =(

**Comment by M1que4s** [comment]
@john-preston you're right, I just tried it with the original theme and it does not happen, thank you very much
