### ISSUE TITLE
[Feature Request] Drag and Drop support

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6275]
### Is your feature request related to a problem?

Drag and Drop when setting profile photo
Currently the way to set profile  photo is by prompt dialog box

**Comment by SmartManoj** [comment]
add focus to file area also when using Drag and Drop for editing files 
Currently it allows on Caption area
![image](https://user-images.githubusercontent.com/7231077/61259162-a1067a00-a796-11e9-910d-8f77c5a0c81c.png)

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5619

**Comment by yashpalgoyal1304** [comment]
@SmartManoj since the main description is duplicate one, this issue can be pivoted to the second comment and requested for reopen.

**Comment by SmartManoj** [comment]
@Aokromes  Should I create a new issue for the second comment?
