### ISSUE TITLE
[Feature Request] Message Reactions

### ISSUE THREAD

**Issue by livejamie** [telegramdesktop/tdesktop#6277]
It would be nice to be able to react to messages with different emojis

![image](https://user-images.githubusercontent.com/49513/61089345-a9a22d80-a3ef-11e9-8fa7-00fc7009dd33.png)

This is almost standard behavior and can be found in Slack, Discord, Facebook Messenger.

It's also being used by Keybase.

Thank you.

**Comment by SmartManoj** [comment]
api-issue

**Comment by livejamie** [comment]
Where is the appropriate place to request this @SmartManoj @23rd 

Thank you

**Comment by SmartManoj** [comment]
https://t.me/ChannelLikeBot
https://t.me/like

**Comment by SmartManoj** [comment]
#5300

**Comment by wanecek** [comment]
Are there any plans to integrate a similar behavior provided by e.g. "like" or "ChannelLikeBot" into the official Telegram API? The current flow, with the sender having to pre-define the available "reactions" is a bit backwards (normally it's not the sender that is to define the available reactions, unless you are doing e.g. polls). Behavior as flexible as Slack's (allowing any emoji to be used as a reaction) would be ideal. 

A quick idea: If desirable, it would maybe be possible to add this functionality without extending the API, instead relying on the client-side changes only. My thinking for this is that clients can interpret messages that:
1. are replies to an earlier message in the conversation,
2. only consist of a single emoji

as "reactions", which supporting clients could then enhance/collapse into a reaction-like UI. 

Arguably, a less "hacky" solution would be better in the long-term. 

CC: @SmartManoj @23rd

**Comment by Aokromes** [comment]
message reactions are very likely coming soon(TM) but it must be implemented api side before telegram desktop can implement them.

**Comment by wanecek** [comment]
That's great news @Aokromes, thank you! Do you know if there are plans, or even progress, in implementing reactions in the API, or if it is still only under consideration?

**Comment by Aokromes** [comment]
don't look at me xd

https://t.me/tgbetachat/172200

**Comment by livejamie** [comment]
That's just a mockup that somebody posted as a feature request?

**Comment by RememberTheAir** [comment]
@23rd the test implementation never made it to production so I guess it's still an API issue :)
